### ISSUE TITLE
script_file does not work with _update

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#10007]
Running with 1.4.4, when trying to update an existing document, one cannot use the undocumented `script_file` because it complains of a validation error (expecting "script" or "doc").

```
POST /test/type/1/_update
{
  "script_file" : "AddTag",
  "lang": "groovy",
  "params": {
    "tag": "tag5"
  }
}
```

Fails due to:

```
{
   "error": "ActionRequestValidationException[Validation Failed: 1: script or doc is missing;]",
   "status": 400
}
```

As a workaround, you can supply the script file directly using the `script` parameter (even with dynamic scripting disabled for Groovy because it recognizes that it is a file).

```
POST /test/type/1/_update
{
  "script" : "AddTag",
  "lang": "groovy",
  "params": {
    "tag": "tag5"
  }
}
```

**Comment by colings86** [comment]
@pickypg This should be fixed from 1.4.5 onwards with the addition of the ScriptParameterParser. would you be able to run the same test on the HEAD of the 1.4 branch an confirm?

**Comment by lmenezes** [comment]
@colings86 I ran into the same issue today, and with latest from 1.4 branch it works correctly.
For previous version of 1.4, sending the script_file parameter on the URL also works. Problem was just that while reading the body, the scirpt_file parameter was missing.

**Comment by javanna** [comment]
I think we can close this, I added version labels.
