### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test {p0=indices.exists/10_basic/Test indices.exists with local flag} failing

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#100088]
**Build scan:**
https://gradle-enterprise.elastic.co/s/dcj3ywljyqzjs/tests/:qa:mixed-cluster:v7.17.14%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=indices.exists%2F10_basic%2FTest%20indices.exists%20with%20local%20flag%7D

**Reproduction line:**
```
./gradlew ':qa:mixed-cluster:v7.17.14#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=indices.exists/10_basic/Test indices.exists with local flag}" -Dtests.seed=3CEBD0A30B49C4CF -Dtests.bwc=true -Dtests.locale=lt-LT -Dtests.timezone=Europe/Tallinn -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dindices.exists/10_basic/Test%20indices.exists%20with%20local%20flag%7D

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([3CEBD0A30B49C4CF]:0)

```

**Comment by tvernum** [comment]
@stu-elastic Do you recall why you labelled this `:Security/FIPS`? It doesn't look related to Security or FIPS to me.

**Comment by gwbrown** [comment]
I've relabeled this for Data Management because I can't identify a connection to the security team either.

**Comment by masseyke** [comment]
This doesn't appear to be directly related to `Test indices.exists with local flag`. That test appears to have just started running when the suite timeout was hit. I notice that `Test cat nodes attrs output` took more than 3 minutes, which seems odd. But there's not any useful information in the log about it.

**Comment by masseyke** [comment]
Out of curiosity, I plotted the runtimes of all the tests. There's no upward trend or anything -- just a _lot_ of fast tests, and the one that took 3 minutes.
<img width="715" alt="Test Runtimes" src="https://github.com/elastic/elasticsearch/assets/453603/a15197ad-08af-43a8-813c-bbd0db1f3583">

**Comment by nielsbauman** [comment]
We haven't seen any failures for a while now (also not according to the [failure dashboard](https://es-delivery-stats.elastic.dev/app/r/s/Mu742)), so I'll close this.
