### ISSUE TITLE
Weighted centroid for geohash_grid

### ISSUE THREAD

**Issue by rashidkpc** [elastic/elasticsearch#10004]
Currently when using the geohash_grid we get back a a grid. This is useful, but when drawing a map the best assumption we can make is that the data all falls square in the middle of the, well, square. For example, When mapping a geohash grid over California, a large portion of the population of the Bay Area tends to appear lost at sea when using lower precision geohash_grids.

It would be great to get a high precision "center" for lower precision geohash_grid aggs for situations in which many of the document fall to one edge or another of the bucket.

**Comment by nknize** [comment]
@rashidkpc I expect this feature to be in for 2.0beta2. It currently depends on feature branch: https://github.com/elastic/elasticsearch/tree/enhancement/LuceneGeoPointField-Integration which is blocked by elastic/infra#315.

In the meantime here is an example of the output:
```javascript
  "aggregations" : {
    "geohashgrid" : {
      "buckets" : [ {
        "key" : "g",
        "doc_count" : 8,
        "centroid" : "[72.37982577458024, -18.86329485476017]"
      }, {
        "key" : "v",
        "doc_count" : 7,
        "centroid" : "[64.23251533415169, 68.72181602753699]"
      }, {
        "key" : "5",
        "doc_count" : 6,
        "centroid" : "[-63.65684769116342, -24.55287636257708]"
      }, {
        "key" : "3",
        "doc_count" : 6,
        "centroid" : "[-19.161130998283625, -103.60427623987198]"
      }, {
        "key" : "j",
        "doc_count" : 5,
        "centroid" : "[-68.90129841165617, 71.04619401041418]"
      } ]
    }
  }
```

The centroid is a GeoJSON compliant point - so lon, lat ordering.

You can try this out if you want, just clone my working branch at: https://github.com/nknize/elasticsearch/tree/feature/10004

**Comment by eskibars** [comment]
+1
