### ISSUE TITLE
ESQL: grouping by just a keyword ignores null values

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#100109]
### Description

Not sure if it's a regression or not but when grouping by just one keyword field, the null group is not returned:
```
from employees | stats by gender | sort gender 
```
should return [F, M, null] yet only [F, M] are.

It looks like the hashing function (whether ordinal or not) ends up dropping null along the way. 
This doesn't happen with multiple keys as long as the keyword is not the first key:

```
from employees | stats by languages, gender | sort desc
```

```
null | null
null | F
null | M
etc...
```

**Comment by dnhatn** [comment]
Thanks Costin. I can reproduce the issue, and I think OrdinalsGroupingOperator doesn't handle nulls properly.

**Comment by dnhatn** [comment]
I've opened https://github.com/elastic/elasticsearch/pull/100117.
