### ISSUE TITLE
Race condition in lifecycles of DiscoveryService and Discovery

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#10017]
A fresh master does (rarely) not send the first cluster state due to a race condition in lifecycles of `DiscoveryService` and its member `Discovery`. In `DiscoveryService.doStart()` the `Discovery` is started but the lifecycle for `DiscoveryService` is started only after that. This is why when the first cluster state reaches `DiscoveryService.publish` the lifecycle might or might not have started.

I am not yet sure what the implications are. However, when I add an artificial delay in `DiscoveryService.doStart()` like this:

```
@Override
    protected void doStart() throws ElasticsearchException {
        initialStateListener = new InitialStateListener();
        discovery.addListener(initialStateListener);
        discovery.start();
        logger.info(discovery.nodeDescription());
        try {
            //NOCOMMIT
            sleep(1000);
        } catch (InterruptedException e) {

        }
    }
```

The `NoMasterNodeTests` fail occasionally. It seems like sometimes the cluster is not blocked properly for writes. In addition, this makes all test in pr #9952 fail as described [here](https://github.com/elasticsearch/elasticsearch/pull/9952#issuecomment-77535805).
I think this needs to be investigated.

**Comment by clintongormley** [comment]
@brwe Is this still an issue?

**Comment by dakrone** [comment]
@brwe is this still an issue?

**Comment by brwe** [comment]
No, the code above does not even exist anymore.
