### ISSUE TITLE
Scripting: Java API does not match the REST layer

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#10011]
The REST layer has the `script`, `script_id` and `script_file` options that can be used to configure scripts that are respectively inline, indexed or in a file in `config/scripts`. However, the Java API only accepts a `String script` parameter, which makes the reference documentation confusing for users of the Java API.

For examples, see eg. ScriptSortBuilder for sorting or StatsBuilder for aggregations.

**Comment by javanna** [comment]
+1 we should streamline this to any builder/api that can execute scripts and make the java api more similar to the REST layer...

**Comment by colings86** [comment]
+1 From 1.4.5 onwards we will have a ScriptParameterParser class to ensure consistent parsing of script parameters, so it seem logical to also have a ScriptParameterBuilder to ensure consistent building of script parameters

**Comment by uboness** [comment]
Why not just have a `Script` construct that is both `ToXContent` and exposes a static `parse` method... Then we can use it everywhere and clean up the code (we recently added it in alerts.... Would love to have it in core)

**Comment by bradvido** [comment]
Being able to specify the script language and script parameters is important too. I can't figure out any way to do it with the 1.4.4 Java API and the StatsBuilder class.

**Comment by colings86** [comment]
This was fixed in https://github.com/elastic/elasticsearch/pull/11164. All script APIs in 2.0 have the same request syntax and can specify type, language and parameters
