### ISSUE TITLE
[CI] Release builds failing due to missing beats artifact POM file

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#100152]
Our release jobs started failing after the Gradle 8.3 upgrade: https://gradle-enterprise.elastic.co/s/xbdlduhiytbiq

My suspicion is something has changed with artifact repo defaults and it's now trying to resolve a POM file even though the repo is configured as artifact-only.

**Comment by mark-vieira** [comment]
@breskeby can you look into this?

**Comment by breskeby** [comment]
@mark-vieira yes

**Comment by mark-vieira** [comment]
Resolved by #100157
