### ISSUE TITLE
ESQL: Optimize aggregations over literals/constant expressions

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#100182]
### Description

Aggregations over literals and constant expressions can often be optimized so that no aggregation is evaluated.

Example:
```
from employees | stats m = max(1)
```
is equivalent to
```
from employees | eval m = 1 | keep m
```

Perform this optimization where possible (`count(1)` being a case where it's not possible).

**Comment by costin** [comment]
The same optimization applies to other aggs such as min(1), max(3), avg(4) - see SQL's [ReplaceAggregatesWithLiterals](https://github.com/elastic/elasticsearch/blob/0a31ce64a9ff3ff3516b60eca41549f280714cb4/x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/optimizer/Optimizer.java#L775).

**Comment by alex-spies** [comment]
Superseded by https://github.com/elastic/elasticsearch/issues/100634
