### ISSUE TITLE
[CI] composeBuild failures

### ISSUE THREAD

**Issue by piergm** [elastic/elasticsearch#100254]
### CI Link

https://gradle-enterprise.elastic.co/s/5mxcon5wdw6yu 
https://gradle-enterprise.elastic.co/s/7yxo5rm6igysi 
https://gradle-enterprise.elastic.co/s/a3oct673yqahk 
https://gradle-enterprise.elastic.co/s/rbyv3lyjurfie 
https://gradle-enterprise.elastic.co/s/ojpn7ujkw3vsy 
https://gradle-enterprise.elastic.co/s/oc6vxusi25fue 
https://gradle-enterprise.elastic.co/s/rziogf3kvpdno 
https://gradle-enterprise.elastic.co/s/qwtdfaec6sw6o  
https://gradle-enterprise.elastic.co/s/6vxnnkzmfre6k 
https://gradle-enterprise.elastic.co/s/6zrah2d62vmxo 
https://gradle-enterprise.elastic.co/s/fra6bqxs3neu2 
https://gradle-enterprise.elastic.co/s/dfduqdvhowdm2

### Repro line

:distribution:docker:composeBuild

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure excerpt

An example of failure exception for unix:
```
A problem occurred starting process 'command '/usr/bin/docker-compose''
> Could not start '/usr/bin/docker-compose'
  > Cannot run program "/usr/bin/docker-compose" (in directory "/var/lib/jenkins/workspace/elastic+elasticsearch+7.17+multijob+platform-support-unix/os/oraclelinux-8&&immutable/distribution/docker"): error=2, No such file or directory
    > error=2, No such file or directory
```
and an example of failure exception for windows:
```
A problem occurred starting process 'command '/usr/bin/docker-compose''
> Could not start '/usr/bin/docker-compose'
  > Cannot run program "/usr/bin/docker-compose" (in directory "C:\Users\jenkins\workspace\platform-support\1313\distribution\docker"): CreateProcess error=2, The system cannot find the file specified
    > CreateProcess error=2, The system cannot find the file specified
```

**Comment by mark-vieira** [comment]
This is addressed by #100218
