### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test {p0=aggregations/typed_keys/Test typed keys parameter for value_count aggregation} failing

### ISSUE THREAD

**Issue by piergm** [elastic/elasticsearch#100269]
**Build scan:**
https://gradle-enterprise.elastic.co/s/qt66c6a5jta4w/tests/:qa:mixed-cluster:v7.17.14%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=aggregations%2Ftyped_keys%2FTest%20typed%20keys%20parameter%20for%20value_count%20aggregation%7D
**Reproduction line:**
```
./gradlew ':qa:mixed-cluster:v7.17.14#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=aggregations/typed_keys/Test typed keys parameter for value_count aggregation}" -Dtests.seed=DA9493FA1C5F9023 -Dtests.bwc=true -Dtests.locale=fi -Dtests.timezone=America/Cayenne -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Daggregations/typed_keys/Test%20typed%20keys%20parameter%20for%20value_count%20aggregation%7D
**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([DA9493FA1C5F9023]:0)

```

**Comment by kkrik-es** [comment]
Not reproducible, seems like tests randomly took longer to complete. Closing for now.
