### ISSUE TITLE
es count With kibana4 hits quantity is different？

### ISSUE THREAD

**Issue by wujiandong** [elastic/elasticsearch#10036]
HI guys
curl localhost:9200/nginx-2015.0301-08*/_count

{"count":3463956,"_shards":{"total":5,"successful":5,"failed":0}}

![image](https://cloud.githubusercontent.com/assets/3368758/6550621/9d5c017e-c666-11e4-86ff-2450110a8c99.png)

ES return count is 3463956,but kibana4 is 2,947,387 hits,why?

**Comment by clintongormley** [comment]
Hi @wujiandong 

I'd ask this on the Kibana list instead.
