### ISSUE TITLE
Add an index_filter option to the `_pit` API

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#100346]
### Description

The `_pit` API takes an index pattern and returns a handle to a point-in-time snapshot of all shards matching this index pattern.

So far so good. But nowadays, it's more and more common for users to use very wide index patterns and rely on filters to narrow down the set of shards to query. The two typical examples are filters on the `@timestamp` field and on `constant_keyword` fields such as `data_stream.dataset`. Shards that don't match the filter on the `@timestamp` or `data_stream.dataset` fields would get ignored as part of the `can_match` phase.

Unfortunately `_pit` doesn't have a way to skip these shards. So if you create a `_pit` on `logs-*`, you might end up with a very large PIT ID, due to the large number of shards that match this index pattern. It would be nice to be able to restrict the set of shards that a PIT is created on through an `index_filter` (same name and semantics as the `index_filter` option of the `_field_caps` API). E.g.

```javascript
POST /logs-*/_pit?keep_alive=1m
{
  "index_filter": {
    "bool": {
      "filter": [
        { "range": { "@timestamp": { "gte": "now-1d" } } },
        { "match": { "data_stream.dataset": "kubernetes.state_deployment" } }
      ]
    }
  }
}
```

**Comment by droberts195** [comment]
Just realised this is the same as #99740, just with a concrete example in the description.

**Comment by jpountz** [comment]
@henrikno pointed out the same, I'm closing this issue in favor of #99740.
