### ISSUE TITLE
Disable queryNorm function in search client

### ISSUE THREAD

**Issue by gucasbrg** [elastic/elasticsearch#10037]
diasble coord as lucene funtion
            public float coord(int overlap, int maxOverlap) {
                return 1;
            }
es can set as BoolQueryBuilder bqb = QueryBuilders.boolQuery();
		       bqb.disableCoord(true);
can ES has diasble  queryNorm as lucene function
            public float queryNorm(float sumOfSquaredWeights) {
                return 1;
            }
in search client with java?

**Comment by clintongormley** [comment]
Hi @gucasbrg 

No, we have no control over query norm.  It is the same for every result anyway
