### ISSUE TITLE
[CI] SnapshotResiliencyTests causing excessive log out

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#100434]
This test is creating over 1G of log output which is causing CI to hang when parsing results.

**Comment by DaveCTurner** [comment]
Does that mean we can't see any of the logs? It would be awfully useful to have a hint what's doing all the logging.

**Comment by mark-vieira** [comment]
I was able to track this down. Turned out it was an interaction with another test class that was modifying logging levels. Opening a PR shortly.
