### ISSUE TITLE
[Transform] Add timeout option and cancellation support to transform checkpoint actions

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#100494]
The transforms functionality uses two internal actions to calculate checkpoints. These are implemented in `TransportGetCheckpointAction` and `TransportGetCheckpointNodeAction`.

These actions need modifying to behave better in large and partially broken environments. At the moment if an outer action that's called them times out they will both continue to do their work internally. This can lead to a buildup of heap usage and CPU usage on the clusters where they're running (which could be the local cluster or remote clusters in a CCS environment).

Both actions should support:

1. Timeouts
2. Cancellation

For cancellation, the most likely scenario is that a parent task, for example transform stats, gets cancelled, and this cancellation cascades down to the transform checkpointing tasks. At each iteration of the potentially long running loops in these tasks they need to be checking for cancellation and exiting these loops if it is detected.

Timeouts should be passed down from stats calls as suggested in: https://github.com/elastic/elasticsearch/blob/8e074712649b0326b2c5f046ba1bd6968d7d06cc/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/transforms/TransformTask.java#L207

**Comment by droberts195** [comment]
Adding a timeout parameter to the request objects will need transport BWC work. It may be hard to get this into 8.11 with the serverless release cadence. If that's the case then the fix for this issue should be split into 2 PRs, with checking the cancellation flag backported to 8.11 and the new timeout parameters just in 8.12.

**Comment by przemekwitek** [comment]
> For cancellation, the most likely scenario is that a parent task, for example transform stats, gets cancelled, and this cancellation cascades down to the transform checkpointing tasks. At each iteration of the potentially long running loops in these tasks they need to be checking for cancellation and exiting these loops if it is detected.

Understood. One question though:
When we run `_stats` (which is a `TransportTasksAction`), we have two tasks at hand:
- transform persistent task
- `_stats` action task

Then we go through all the layers down to `GetCheckpointAction` which loops through shards. But in this loop, should it poll persistent task `cancelled` bit or `_stats` action `cancelled` bit?
Currently, it seems the `TransformTask.getCheckpointingInfo` method is passing the pTask's parent-assigning client down to the `GetCheckpointAction`. 
So if I implement polling for `cancelled` bit, it will be the pTask's bit, **not** the action task's bit.

**Comment by przemekwitek** [comment]
Status update: I'm almost done with the "cancelled" part. Will send the PR for review early next week.
