### ISSUE TITLE
[Feature] Query template modularity (or, re-using template queries in template queries)

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#10047]
It would be super useful to have the ability to reuse query templates from other query templates, e.g.

```
POST /_search/template/title_search
{
    "template": {
        "query": {
            "match": {
                "title": "{{query_string}}"
            }
        }
    }
}

POST /_search/template/article_search
{
    "template": {
        "query": {
            "bool":{
             "should":[
                "match": {
                   "content": "{{query_string}}"
                },
                "template_id":"title_search"
          ]
         }
        }
    }
}
```

It will then be the user's responsibility to make sure one change to a template doesn't break other templates, and that required params are all satisfied across all used templates.

In particular I see this being asked for over and over again by various clients, as their queries are growing bigger and bigger beyond what they could maintain easily.

**Comment by clintongormley** [comment]
This works already:

    PUT t/t/1
    {
      "title": "foo"
    }
    
    PUT t/t/2
    {
      "title": "bar"
    }
    
    POST /_search/template/title_search
    {
      "template": {
        "query": {
          "match": {
            "title": "{{foo}}"
          }
        }
      }
    }
    
    POST /_search/template/article_search
    {
      "template": {
        "query": {
          "template": {
            "id": "title_search",
            "params": {
              "foo": "{{bar}}"
            }
          }
        }
      }
    }
    
    
    GET _search
    {
      "query": {
        "template": {
          "id": "article_search",
          "params": {
            "bar": "foo"
          }
        }
      }
    }

**Comment by mbystryantsev** [comment]
>This works already
@clintongormley, in elasticsearch 5.0+ `Template Query` marked as deprecated. How to reuse templates now?

**Comment by clintongormley** [comment]
@mbystryantsev we won't be supporting template embedding going forward
