### ISSUE TITLE
[Feature][function_score] Execute a function on scores in score_mode

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#10049]
Currently `score_mode` only supports a basic set of operations on scores provided by the functions executed in function score query: `multiply`, `sum`, `avg`, `first`, `max`, `min`.

It will be very useful to have the ability to execute a more involved function on them instead, e.g.: `_score1 + _score3 - _score2*_score5`, where scores can be numbered or names after the functions order / names.

**Comment by dakrone** [comment]
Related to https://github.com/elastic/elasticsearch/pull/19710

**Comment by clintongormley** [comment]
Closing in favour of #19710

**Comment by synhershko** [comment]
Thanks @clintongormley @dakrone - as long as that solution allows for sibling scores to be passed as parameters to that script, that would work.
