### ISSUE TITLE
Add alias filter to slowlog entries

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#10044]
When using filtered aliases filtered by type, it will be helpful for slowlog to report the types queried.   Currently, it returns `types[]`.

```
POST /_aliases
{
  "actions": [
    {
      "add": {
        "index": "index_name",
        "alias": "slowlogalias",
        "filter": {
          "term": {
            "_type": "doc_type"
          }
        }
      }
    }
  ]
}
```

**Comment by clintongormley** [comment]
Hi @ppf2 

I don't think we should single out the doc types, but I agree that we should include the full filter that is being applied thanks to the alias.

**Comment by pgomulka** [comment]
with types being removed or deprecated we won't need to implement this.
