### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test {p0=tsdb/80_index_resize/clone} failing

### ISSUE THREAD

**Issue by edsavage** [elastic/elasticsearch#100526]
**Build scan:**
https://gradle-enterprise.elastic.co/s/rhucs2r5vdiuu/tests/:qa:mixed-cluster:v7.17.14%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=tsdb%2F80_index_resize%2Fclone%7D
**Reproduction line:**
```
./gradlew ':qa:mixed-cluster:v7.17.14#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=tsdb/80_index_resize/clone}" -Dtests.seed=3A14B6F71F3B3517 -Dtests.bwc=true -Dtests.locale=de-LU -Dtests.timezone=Europe/Berlin -Druntime.java=21
```

**Applicable branches:**
8.11

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dtsdb/80_index_resize/clone%7D
**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([3A14B6F71F3B3517]:0)

```

**Comment by kkrik-es** [comment]
This is not reproducible, seems like an one-off - tests just happened to run more slowly. Closing for now.
