### ISSUE TITLE
filtered query w/ has_child query and filter applied to child documents

### ISSUE THREAD

**Issue by asanderson** [elastic/elasticsearch#10058]
Enable a filtered query to apply filter to both parent and child documents but return parent documents for has_child query.

e.g. 
curl -X PUT "http://localhost:9200/foobar" -d "{\"mappings\":{\"Foo\":{},\"Bar\":{\"_parent\":{\"type\":\"Foo\"}}}}"

curl -X PUT "http://localhost:9200/foobar/Foo/1" -d "{\"foo\":\"abc\",\"access\":\"yes\"}"

curl -X PUT "http://localhost:9200/foobar/Bar/2?parent=1" -d "{\"bar\":\"xyz\",\"access\":\"no\"}"

The following filtered query would not return a result, since the filter would be applied to both the parent and child documents; however, as implemented now, the parent document would be returned, since the filter is not applied to the child document.

```
{
   "query": {
      "filtered": {
         "query": {
            "has_child": {
               "type": "Bar",
               "query": {
                  "term": {
                     "bar": "xyz"
                  }
               }
            }
         },
         "filter": {
            "term": {
               "access": "yes"
            }
         }
      }
   }
}
```

Perhaps an additional filtered_query strategy could be specified which would apply the filter first to both parent and child documents.

**Comment by clintongormley** [comment]
Hi @asanderson 

Trying to extend the filtered query to say "also apply to this has-child subclause" doesn't make sense to me.  Things would suddenly get very complicated with action-at-a-distance.

If you want the condition to apply to the sub-clause, then you should include it in the sub-clause.  It'll still be able to use the cached filter.

**Comment by asanderson** [comment]
Again, it makes sense in the very real scenario where you have a common access control field for which you want to guarantee a filter is applied to all parent and child records.  The filters are already huge, so having to wrap the has_child subclause into a filtered query and copying the huge filter from the outer filtered query is very ugly.

**Comment by asanderson** [comment]
So, good luck w/ implementing a common access control field strategy w/ Shield that applies to both parent and child documents, if you leave this closed.

**Comment by clintongormley** [comment]
You raise a good point...  How to completely exclude documents from all queries that match some filter.  Reopening for discussion

**Comment by clintongormley** [comment]
@uboness this may be of interest to you

**Comment by asanderson** [comment]
Currently, it's a pain to have to rewrite an end-user's query to wrap all their queries and filters w/ a common access control filter.  There should be an easier way to do this.  From an API user perspective, the ideal solution would be to specify top-level pre_filter similarly to how easier it is to specify a post_filter. If agreed, then feel free to close this again and open up a new feature to support this pre_filter concept.

**Comment by marshall007** [comment]
@clintongormley are there any workarounds for this issue? We have a similar situation where we're trying to apply boolean `{ should, filter }` queries at both the parent and child levels. We would essentially want to treat the parent/child `should` and `filter` sub-queries as if they were siblings on the same boolean query.

I tried something along these lines, but you are not allowed to have duplicate `has_child` queries on the same type in a single query:

```js
{
  bool: {
    filter: [
      {  }, // parent.bool.filter
      {
        has_child: {
          type: '...'
          query: // child.bool.filter
        }
      }
    ]
    should: [
      {  }, // parent.bool.should
      {
        has_child: {
          type: '...'
          query: // child.bool.should
        }
      }
    ]
  }
}
```

**Comment by cbuescher** [comment]
cc @elastic/es-search-aggs

**Comment by jaymode** [comment]
We discussed this during a team meeting and outside of the security use case, we could not think of a non-contrived example where this would be needed. Given that and the existing complexity of parent child, we do not feel like this is something we should introduce within our query dsl and code.

In terms of a solution for this type of issue, we do offer document level security in our security product which will provide the behavior that this request is asking for.
