### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test {p0=indices.put_alias/all_path_options/put alias with missing name} failing

### ISSUE THREAD

**Issue by edsavage** [elastic/elasticsearch#100524]
**Build scan:**
https://gradle-enterprise.elastic.co/s/4rctef4ruy3e2/tests/:qa:mixed-cluster:v7.17.14%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=indices.put_alias%2Fall_path_options%2Fput%20alias%20with%20missing%20name%7D
**Reproduction line:**
```
./gradlew ':qa:mixed-cluster:v7.17.14#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=indices.put_alias/all_path_options/put alias with missing name}" -Dtests.seed=CD5457ABE8E451FD -Dtests.bwc=true -Dtests.locale=he -Dtests.timezone=Zulu -Druntime.java=21
```

**Applicable branches:**
8.11

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dindices.put_alias/all_path_options/put%20alias%20with%20missing%20name%7D
**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([CD5457ABE8E451FD]:0)

```

**Comment by benwtrent** [comment]
There is nothing in the node logs around the time of the test that indicates anything was wrong :(. 

The nodes all look like they were initialized and waiting. I am not sure?

Here are the mixed-cluster logs from the failure: 

[mixed-cluster.zip](https://github.com/elastic/elasticsearch/files/12850238/mixed-cluster.zip)

**Comment by benwtrent** [comment]
Flagging as low risk as it honestly just looks like the suite took a long time and finally timed out and it happened to be running this test at the time. The test did not take a long time run or fail.

**Comment by benwtrent** [comment]
The test failed quickly due to suite timeout. Suite timeout has been increased to 60m, closing this as the individual test isn't to blame, but instead the entire suite runtime and infra.

Related: https://github.com/elastic/elasticsearch/pull/100585
