### ISSUE TITLE
Data separation and access control - collect logs of multiple tenants

### ISSUE THREAD

**Issue by tyyko** [elastic/elasticsearch#10057]
Please don't point me at the new product 'shield' as is not open-source :(

If I will use ELK stack to collect logs from different tenants(example: all websites/web application hosted by me)
How can I provide my 'clients' the possibility to check and query their logs without seeing the others?
How can I assure that is not possible to a user to see the logs not related to his applications?
Should I have to find a way to have this data-separation on elasticsearch, kibana or both?

On a MySQL Server I would just use different DB and users but here I am a bit new about that project.

Is the only way do deploy an ELK stack for each 'client'? 

Thank you

**Comment by clintongormley** [comment]
Hi @tyyko 

You should probably ask for suggestions about approaches to this on the mailing list instead.  Like with MySQL, you could use a separate index per client, then in your web front end, you could limit each user to just their index or indices.
