### ISSUE TITLE
Recovery should wipe the shard state file before starting recovery

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#10053]
When we start recovery of a shard we should wipe the state file of the copy if it's present otherwise gateway allocating can get confused interpreting a shard that is not fully recovered ie. due to a recovery failure as a valid copy since we only write the state when the shard is started.

**Comment by s1monw** [comment]
@brwe can you take care of this?

**Comment by bleskes** [comment]
I wonder if the correct time to wipe any _state file is before the temp file rename. Until then, the recovery doesn’t mess with any non-temp files. If the recover is cancelled, we leave the target shard intact.

**Comment by s1monw** [comment]
@bleskes agreed.. we should remove it before we rename the first file.

**Comment by brwe** [comment]
Just for reference, here is the relevant test failure: http://build-us-00.elasticsearch.org/job/es_core_1x_small/1800/
