### ISSUE TITLE
Function score on ChildrenQuery execute diffrent in master version

### ISSUE THREAD

**Issue by lukapor** [elastic/elasticsearch#10051]
Hi, I am testing new master version of elasticsearch and have one question.

I am using some statistics (store in usagestatistics object) which is child object of lets say document object. I implemented sort by most user used document by function score on child query. In a version 1.4.x it is ok, on master version i got error on some shard where i dont have childs (error below). It is any option to ignore this.

error is

    {
      "index": "develop_compositedata_0",
      "shard": 3,
      "status": 500,
      "reason": "QueryPhaseExecutionException[[develop_compositedata_0][3]: query[+companyId:[88 TO 88]^0.0 +deleted:F^0.0 +((typeId:[2 TO 2] typeId:[4 TO 4]^0.08 typeId:[32 TO 32]^0.02 typeId:[1 TO 1]^0.3 typeId:[2048 TO 2048]^0.0 typeId:[65536 TO 65536]^0.0)~1) +((authorizationTokens:noauth^0.0 authorizationTokens:noauthsubject^0.0 authorizationTokens:111^0.0 authorizationTokens:89^0.0 authorizationTokens:187^0.0 authorizationTokens:214^0.0 authorizationTokens:217^0.0 authorizationTokens:10244^0.0 authorizationTokens:10257^0.0 authorizationTokens:161^0.0)~1) +ConstantScore(+stringFields.dynstring_30303030303030302d303030302d303030302d303030302d3030303030303030303030302f47656e6572616c2f4e616d65.value:mi*)^0.01 +((main:[0 TO 0]^0.0 main:[-1 TO -1]^0.0)~1) +blocked:F^0.0 ChildrenQuery[min(0) max(2147483647)of usagestatistics/compositedata](filtered(function score (+userId:[111 TO 111]^0.0,function=script[doc['usagestatistics.searchBoost'].value], params [null]))->cache(_type:usagestatistics))],from[0],size[7],sort[<score>,<custom:\"sortName\": org.elasticsearch.index.fielddata.fieldcomparator.BytesRefFieldComparatorSource@2c1574e4>!]: Query Failed [Failed to execute main query]]; nested: RuntimeException[org.elasticsearch.script.groovy.GroovyScriptExecutionException: ElasticsearchIllegalArgumentException[No field found for [usagestatistics.searchBoost] in mapping with types []]]; nested: GroovyScriptExecutionException[ElasticsearchIllegalArgumentException[No field found for [usagestatistics.searchBoost] in mapping with types []]]; "
    }

and query:

    {
      "from": 0,
      "size": 7,
      "sort": [
        {
          "_score": {
            "missing": "_last",
            "order": "desc"
          }
        },
        {
          "sortName": {
            "missing": "_last",
            "order": "desc"
          }
        }
      ],
      "fields": [
        "id",
        "compositeId",
        "name",
        "typeId",
        "external",
        "blocked",
        "deleted",
        "serviceId",
        "processInstanceId",
        "serviceInstanceId",
        "ownerServiceId",
        "ownerProcessInstanceId",
        "main",
        "modified"
      ],
      "query": {
        "bool": {
          "must": [
            {
              "term": {
                "companyId": {
                  "value": 88,
                  "boost": 0
                }
              }
            },
            {
              "term": {
                "deleted": {
                  "value": false,
                  "boost": 0
                }
              }
            },
            {
              "bool": {
                "should": [
                  {
                    "term": {
                      "typeId": {
                        "value": 2,
                        "boost": 1
                      }
                    }
                  },
                  {
                    "term": {
                      "typeId": {
                        "value": 4,
                        "boost": 0.07999999821186066
                      }
                    }
                  },
                  {
                    "term": {
                      "typeId": {
                        "value": 32,
                        "boost": 0.019999999552965164
                      }
                    }
                  },
                  {
                    "term": {
                      "typeId": {
                        "value": 1,
                        "boost": 0.30000001192092896
                      }
                    }
                  },
                  {
                    "term": {
                      "typeId": {
                        "value": 2048,
                        "boost": 0
                      }
                    }
                  },
                  {
                    "term": {
                      "typeId": {
                        "value": 65536,
                        "boost": 0
                      }
                    }
                  }
                ],
                "minimum_should_match": "1"
              }
            },
            {
              "bool": {
                "should": [
                  {
                    "term": {
                      "authorizationTokens": {
                        "value": "noauth",
                        "boost": 0
                      }
                    }
                  },
                  {
                    "term": {
                      "authorizationTokens": {
                        "value": "noauthsubject",
                        "boost": 0
                      }
                    }
                  },
                  {
                    "term": {
                      "authorizationTokens": {
                        "value": "111",
                        "boost": 0
                      }
                    }
                  },
                  {
                    "term": {
                      "authorizationTokens": {
                        "value": "89",
                        "boost": 0
                      }
                    }
                  },
                  {
                    "term": {
                      "authorizationTokens": {
                        "value": "187",
                        "boost": 0
                      }
                    }
                  },
                  {
                    "term": {
                      "authorizationTokens": {
                        "value": "214",
                        "boost": 0
                      }
                    }
                  },
                  {
                    "term": {
                      "authorizationTokens": {
                        "value": "217",
                        "boost": 0
                      }
                    }
                  },
                  {
                    "term": {
                      "authorizationTokens": {
                        "value": "10244",
                        "boost": 0
                      }
                    }
                  },
                  {
                    "term": {
                      "authorizationTokens": {
                        "value": "10257",
                        "boost": 0
                      }
                    }
                  },
                  {
                    "term": {
                      "authorizationTokens": {
                        "value": "161",
                        "boost": 0
                      }
                    }
                  }
                ],
                "minimum_should_match": "1"
              }
            },
            {
              "constant_score": {
                "query": {
                  "bool": {
                    "must": [
                      {
                        "query_string": {
                          "query": "mi*",
                          "fields": [
                            "stringFields.dynstring_30303030303030302d303030302d303030302d303030302d3030303030303030303030302f47656e6572616c2f4e616d65.value"
                          ],
                          "default_operator": "and",
                          "analyzer": "standard-4office",
                          "allow_leading_wildcard": false,
                          "analyze_wildcard": true,
                          "minimum_should_match": "100%",
                          "use_dis_max": false
                        }
                      }
                    ]
                  }
                },
                "boost": 0.009999999776482582
              }
            },
            {
              "bool": {
                "should": [
                  {
                    "term": {
                      "main": {
                        "value": 0,
                        "boost": 0
                      }
                    }
                  },
                  {
                    "term": {
                      "main": {
                        "value": -1,
                        "boost": 0
                      }
                    }
                  }
                ],
                "minimum_should_match": "1"
              }
            },
            {
              "term": {
                "blocked": {
                  "value": false,
                  "boost": 0
                }
              }
            }
          ],
          "should": [
            {
              "has_child": {
                "type": "usagestatistics",
                "score_type": "sum",
                "query": {
                  "function_score": {
                    "query": {
                      "bool": {
                        "must": [
                          {
                            "term": {
                              "userId": {
                                "value": 111,
                                "boost": 0
                              }
                            }
                          }
                        ]
                      }
                    },
                    "score_mode": "sum",
                    "boost_mode": "max",
                    "script_score": {
                      "script": "doc['usagestatistics.searchBoost'].value"
                    }
                  }
                }
              }
            }
          ],
          "minimum_should_match": "0"
        }
      }
    }

**Comment by clintongormley** [comment]
Hi @lukapor 

I think you're running into this change: https://github.com/elastic/elasticsearch/commit/6079d88d433387933d55d6500e6aaa04d6a6b1ce

You can no longer prepend the field name with the type name, as it results in ambiguous field lookups.
