### ISSUE TITLE
sub aggregation of metric aggregation

### ISSUE THREAD

**Issue by zijian1981** [elastic/elasticsearch#10059]
Is  it  possible to support sub  aggregation of  metric aggregation ?
For  example ,term agg→mean  agg →max agg

**Comment by colings86** [comment]
What would you expect the output of this to be? if you want to calculate the mean and max of a field for each terms bucket you can do the following:

```
{
  "aggs": {
    "terms_agg": {
      "terms": {
        "field": "category",
        "size": 10
      },
      "aggs": {
        "mean_agg": {
          "avg": {
            "field": "value"
          }
        },
        "max_agg": {
          "max": {
            "field": "value"
          }
        }
      }
    }
  }
}
```

Does this fit what you wanted to do?

**Comment by zijian1981** [comment]
No,i want to calculate the max value from all the mean value

**Comment by markwalkom** [comment]
You cannot do this at this stage. Once you get an aggregation result you can only sub-aggregate that, not do a different aggregation across those results.

**Comment by colings86** [comment]
@zijian1981 there is an issue open for this kind of thing (https://github.com/elastic/elasticsearch/issues/10000) which is being considered as part of https://github.com/elastic/elasticsearch/issues/9876

**Comment by colings86** [comment]
Closing in favour of #10000 and #9876
