### ISSUE TITLE
Regarding TTL Settings

### ISSUE THREAD

**Issue by Sameerkpatro** [elastic/elasticsearch#10055]
I am getting an Error as below while configuring ELK.Caused by: org.elasticsearch.index.mapper.MapperParsingException: Root type mapping not empty after parsing! Remaining fields:   [logstash-* : {_ttl={enabled=true, default=500}}] [_default_ : {dynamic_templates=[{string_fields={mapping={index=analyzed, omit_norms=true, type=string, fields={raw={index=not_analyzed, ignore_above=256, type=string}}}, match_mapping_type=string, match=*}}], properties={geoip={dynamic=true, path=full, properties={location={type=geo_point}}, type=object}, @version={index=not_analyzed, type=string}}, _all={enabled=true}}]
        at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:276)

My default configuration is :

{
"logstash-*" : {
    "_ttl" : { "enabled" : true, "default" : "500" }
}
}

I also tried the below configuration but it fails:

{
"template" : "logstash-*",
    "mappings" : {
        "_default_" : {
            "_ttl" : { "enabled" : true, "default" : "5s"  }
        }
}
}

Can anyone please suggest what could be the issue?

Thanks

**Comment by clintongormley** [comment]
Hi @Sameerkpatro 

How are you configuring this?  The below works fine for me:

    PUT _template/test
    {
      "template": "logstash-*",
      "mappings": {
        "_default_": {
          "_ttl": {
            "enabled": true,
            "default": "5s"
          }
        }
      }
    }
    
    PUT /logstash-one/test/1
    {}
    
    GET logstash-one/_mapping

Btw, using TTL for logging is likely a very bad approach, as older documents need to be physically deleted.  Much better to just drop old indices.

**Comment by clintongormley** [comment]
No more info. Closing
