### ISSUE TITLE
[ES|QL] Unhandled error on non existing policy

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch#100593]
### Elasticsearch Version

8.11.0

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

When sending a ESQL query with the `enrich` command that involves a policy that does not existing a `NullPointerException` is thrown and shown as error messages to the user:

Query:
```
row a  = 1| enrich missing-policy
```

Returns:
```
null_pointer_exception - Cannot invoke "org.elasticsearch.xpack.core.enrich.EnrichPolicy.getMatchField()" because "policy" is null
```

### Steps to Reproduce

See above.

**Comment by costin** [comment]
This looks like a validation error that can be caught by the verifier.
