### ISSUE TITLE
Page cache recycler using >10% of heap

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#10060]
From talking to @jpountz , the page cache recycler is not supposed to use > 10% of heap.  We are seeing it use more than 10% in one of the heap dumps received (ES 1.4.1).  Filing this ticket to track. Thx @jpountz !

![image](https://cloud.githubusercontent.com/assets/7216393/6603370/e918cc18-c7de-11e4-813a-e4565d822ab4.png)

![image](https://cloud.githubusercontent.com/assets/7216393/6603356/ddf4e88a-c7de-11e4-8ebc-5709096e23f9.png)

**Comment by jpountz** [comment]
For the record, this is on a 30.1GB heap.

**Comment by jpountz** [comment]
This looks related to #10077

**Comment by jpountz** [comment]
I just verified #10077 . This is very likely the cause of this issue.
