### ISSUE TITLE
Interoperability of /_query and /_search with GET/POST/DELETE

### ISSUE THREAD

**Issue by drewbroadley** [elastic/elasticsearch#10065]
Hi there,

I've got an issue where /_query POST creates something, yet you need to use /_query to DELETE from a Query DSL search.

It would be great to have it so /_query is interoperable with /_search, unless I'm missing something in the documentation it would make sense for this.

I'm proposing that /_search becomes an alias to /_query (eventually removed) and then you can do the folllowing:

GET: To perform a search relating to terms in URI
POST: To perform a search using the Query DSL provided in the RAW data
DELETE: To perform removal of documents matching the Query DSL provided in the RAW data.

**Comment by clintongormley** [comment]
Hi @drewbroadley 

GET/POST _search both allow searches with or without body. Either of these can contain queries, post-filters, aggs, suggestions etc.  DELETE _query is delete-by-query, and all it accepts is a query, nothing else.

We're trying to reduce "synonyms" in the API, so I'm not keen to add more options - i think that would just add to the confusion.

Most people will be using one of the official clients, which I think are a bit clearer, eg:

    $es->search( body => { query => {....}})
    $es->delete_by_query( body => { query => {...}})
