### ISSUE TITLE
Add support for doc values for analyzed fields

### ISSUE THREAD

**Issue by Asimov4** [elastic/elasticsearch#10061]
We would like to use doc values for analyzed fields.

The doc mentions that it is not possible:
http://www.elastic.co/guide/en/elasticsearch/guide/current/doc-values.html

> Doc values can be enabled for numeric, date, Boolean, binary, and geo-point fields, and for not_analyzed string fields. They do not currently work with analyzed string fields.

Will that eventually be supported?

**Comment by clintongormley** [comment]
Hi @Asimov4 

We have been discussing it internally.  The biggest question is: what is the right datastructure? The answer depends on what people want to use the analyzed values for.

Could you talk about your use case(s)?

**Comment by mattweber** [comment]
+1, case-insensitive sorting of string fields where you use the keyword tokenizer and lowercase token filter.

**Comment by rmuir** [comment]
I tend to think @mattweber 's use case is an important one. But we should think of a way to solve it but where its not trappy if someone wants this. They should be able to have docvalues, but they should also not have norms and other things: it should still act 'not analyzed'. 

There is a big difference to me between supporting that, and putting the entire tokenized contents of moby dick into a docvalues field.

**Comment by Asimov4** [comment]
The main use case I have in mind is performing top terms aggregations or significant terms aggregations to do keyword analysis on the text fields of the documents stored in our index. We use the [default language analyzers](http://www.elastic.co/guide/en/elasticsearch/reference/1.5/analysis-lang-analyzer.html) for these text fields.

**Comment by mattweber** [comment]
Another use-case is ICU collation.  Really any kind of minimal analysis that produces a couple tokens at most.

**Comment by rmuir** [comment]
ICU collation IMO is different. its just a DV sort key: doesn't need tokens or an analyzer anymore, and thats how exposed in lucene since 4.2

**Comment by reardencode** [comment]
:+1: for at least allowing doc_values on fields whose whose analyzer is guaranteed to only generate a single value.

**Comment by rayward** [comment]
:+1: 

Have the exact same situation as @mattweber, I've got several sub-fields using an analyzer like that for sorting:

```
"lowercase_single_token" : {
  "filter": [
    "lowercase",
    "asciifolding"
  ],
  "tokenizer" : "keyword",
  "type": "custom"
}
```

**Comment by passing** [comment]
hi @clintongormley 

in the context of log messages, we have a few cases where we use analyzers that generate always a single token:

*synonyms*
we have an analyzer that uses a filter to group severity values that mean the same thing, like "warn" and "warning"
```
                "filter" : {
                    "synonym_severity" : {
                        "type" : "synonym",
                        "expand" : "false",
                        "synonyms" : [
                            "crit, critical, alert, emerg, emergency, panic => fatal",
                            "err, severe => error",
                            "warning => warn",
                            "trace => debug"
                        ]
                    }
                }
```

*replacing/masking*
we have an analyzer that uses a char_filter to remove numbers from error messages, so we can aggregate on similar messages ("could not read attribute x for object 123" and "could not read attribute x for object 4567" are both transformed to "could not read attribute x for object #")
```
                "char_filter" : {
                    "clean_number" : {
                        "type" : "pattern_replace",
                        "pattern" : "[0-9,.]*[0-9]",
                        "replacement" : "#"
                    }
                }
```

*trim*
we have an analyzer that uses a tokenizer which returns only the first line of an error message. so we can aggregate on that..
```
                "tokenizer" : {
                    "string_head_tokenizer" : {
                        "type" : "pattern",
                        "flags" : "DOTALL",
                        "pattern" : "([^\\n]{1,512}).*",
                        "group" : "1"
                    }
                }
```

it would be very helpful to be able to use doc-values for these cases

**Comment by clintongormley** [comment]
Hi @passing 

Thanks for the detailed comment.  We're intending to deprecate the `string` type and replace it with `text` and `keyword` types, where the keyword type will allow analysis (as long as the tokenizer is `keyword`)  and will support doc values.  See https://github.com/elastic/elasticsearch/issues/12394

For your trim example, you could change to using the pattern replace token filter and it would still work with the `keyword` field type. https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pattern_replace-tokenfilter.html

I'm going to close this issue in favour of #12394
