### ISSUE TITLE
Reindexing in elasticsearch 7.17 as preparartion to 8.x upgrade failing

### ISSUE THREAD

**Issue by indunallithodi** [elastic/elasticsearch#100739]
Team,
Have 6.8 server with 6.8 indices(created in 5.6 and upgraded to 6.8 few years back) with multi-type
Reindexed to single-type in 6.8- deleted 5.6 ones
Installed 7.17 and booted success as GREEN
as preparing to 8.x; trying reindex in 7.17 and failing (processing few 100s only from few million count) on 4 indices of 7(these 4 had multi type in 6 and changed to _doc in 7.17 with reindex)

"cause": {
    * "type": "mapper_parsing_exception",
    * "reason": "failed to parse",
    * "caused_by": {
      * "type": "json_parse_exception",
      * "reason": "Duplicate field 'type' at [Source: (ByteArrayInputStream); line: 1, column: 65]"}},
  * "status": 400} 
  
How to proceed with reindexing of 6.x to 7.17
Ref: https://discuss.elastic.co/t/reindex-in-elasticsearch-7-17-as-pre-upgrade-to-8-x/344575

**Comment by mark-vieira** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
