### ISSUE TITLE
[DOCS] No need to restart nodes when adding reloadable secure settings

### ISSUE THREAD

**Issue by consulthys** [elastic/elasticsearch#100777]
### Elasticsearch Version

8.10.2

### Java Version

_bundled_

### OS Version

Darwin iMac.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

### Problem Description

In the official documentation that explains how to [set up a repository on Azure Storage](https://www.elastic.co/guide/en/elasticsearch/reference/current/repository-azure.html), the following sentence can create confusion (emphasis added where the confusion resides):

> To enable Azure repositories, you have first to define your azure storage settings as [secure settings](https://www.elastic.co/guide/en/elasticsearch/reference/8.10/secure-settings.html), **before starting up the node:**

Further down the page, we can read this (emphasis is mine):

> The account, key, and sas_token storage settings are **reloadable secure settings**, which you add to the Elasticsearch keystore

The confusion stems from the fact that we first read that the secure settings must be added to the keystore **before starting the node** and later we learn that those settings are reloadable, without having to restart the node.

I think that **before starting up the node** should be removed as it is not correct since secure settings can be reloaded without restarting the nodes.

### Steps to Reproduce

1. Go to https://www.elastic.co/guide/en/elasticsearch/reference/current/repository-azure.html
2. Read the **Setup** section and notice the confusion

**Comment by shainaraskas** [comment]
suspect there is a nuance here about settings needing to be set _initially_ before reload works as expected. investigating.
