### ISSUE TITLE
Marvel reports incorrect document count and store size.

### ISSUE THREAD

**Issue by ajaybhatnagar** [elastic/elasticsearch#10079]
See the query result which says about 45M docs and 94GB  as size, Marvel graph have these values nearly half of actual values.
health status index       pri rep docs.count docs.deleted store.size pri.store.size
green  open   test_insert   5   1   44999486            0    188.2gb         94.1gb

![doccount](https://cloud.githubusercontent.com/assets/8180763/6639123/2c67705c-c963-11e4-86ac-333760152919.png)

**Comment by bleskes** [comment]
Thx for reporting. Just to make sure we put some things aside, I want to double check you have a single node cluster (the image is from a node stat chart while the cat call looks like it comes from an index stats). If not, the marvel chart just shows the shards assigned to that node, not the entire index. 

Also - can you check what the `_nodes/stats` api reports when calling ES directly? look for `indices.docs.count` & `indices.store.size_in_bytes` in the output

**Comment by ajaybhatnagar** [comment]
Thanks for prompt review. I just wiped the whole cluster and will be running the same test again provide requested details. For info,  the cluster had 5 data nodes, one index , 5 shards and one replica. Each data node had one primary and one replica shard.

If I understood correctly, the info is only for the node (i.e. documents stored on the node). Rough estimates (assuming balanced distribution), should be about (45Pri+45Rep)=90M/5 ~=18M documents on the node and size ~= 188/5=38Gb 

May be the titles on the could be improved to make it more specific.

**Comment by bleskes** [comment]
> If I understood correctly, the info is only for the node (i.e. documents stored on the node). Rough estimates (assuming balanced distribution), should be about (45Pri+45Rep)=90M/5 ~=18M documents on the node and size ~= 188/5=38Gb

Yeah. I think this means the marvel stats are OK?

> May be the titles on the could be improved to make it more specific.

The dashboard is called node stats and you get to it by clicking on a node. The chart is under "Indices Store" which needs to be clicked open. What would you suggest renaming the chart to in order to make it clearer, given this context?

**Comment by ajaybhatnagar** [comment]
Suggested titles for the two charts 
Documents on <Host> and 
Doc. Size on <Host> 
where <Host> is the actual hostname in cluster.

**Comment by bleskes** [comment]
yeah. These are a bit tricky as they don't scale when people view data for multiple nodes. I hear you though and I'll think about possible improvements here. I'm closing this for now, as the stats seems correct. Please feel free to reopen if I missed something.
