### ISSUE TITLE
Bug in PageCacheRecycler?

### ISSUE THREAD

**Issue by prog8** [elastic/elasticsearch#10077]
I hit a problem where PageCacheRecycler seems to be too big. I have an impression this is bigger than the limit. Default page.limit.heap is 10% and default weights for byte/long/int/float/double are 1/1/1/1/1. This implies that for 30G heap NONE of pages should be bigger than 600MB if I'm not wrong.

Looking into PageCacheRecycler.maxCount method calculates higher values for bigger data types. If for float maxCount is 1000 for double it is 2000. I think this is not correct because (later in PageCacheRecycler class) I can see this:

    return new byte[BigArrays.BYTE_PAGE_SIZE];
    return new int[BigArrays.INT_PAGE_SIZE];
    return new long[BigArrays.LONG_PAGE_SIZE];
    return new float[BigArrays.FLOAT_PAGE_SIZE];
    return new double[BigArrays.DOUBLE_PAGE_SIZE];
    return new Object[BigArrays.OBJECT_PAGE_SIZE];

All of those arrays seems to have by default the same size 16kB.

My intuition says that all calls like:

    bytePage = build(type, maxCount(limit, BigArrays.BYTE_PAGE_SIZE, bytesWeight, totalWeight), searchThreadPoolSize, availableProcessors, new AbstractRecyclerC<byte[]>() {
    doublePage = build(type, maxCount(limit, BigArrays.DOUBLE_PAGE_SIZE, doubleWeight, totalWeight), searchThreadPoolSize, availableProcessors, new AbstractRecyclerC<double[]>() {

should be

    bytePage = build(type, maxCount(limit, BigArrays.PAGE_SIZE_IN_BYTES, bytesWeight, totalWeight), searchThreadPoolSize, availableProcessors, new AbstractRecyclerC<byte[]>() {
    doublePage = build(type, maxCount(limit, BigArrays.PAGE_SIZE_IN_BYTES, doubleWeight, totalWeight), searchThreadPoolSize, availableProcessors, new AbstractRecyclerC<double[]>() {

I'll simulate maxSize of double[] with current calls of maxCount, 30G heap and 10% limit for recycled pages size.

maxCount(3'000'000'000, 2048, 1, 4.1) -> 1 / 4.1 * 3'000'000'000 / 2048 = 357278
Each page size is 16kB so ... 16kB * 357278 implies **5.7GB** (only for doubles). Isn't it too much? Can anyone take a look and verify?

Moreover i see another - minor bug

    final double totalWeight = bytesWeight + intsWeight + longsWeight + doublesWeight + objectsWeight;

It seems that floatWeight is missing

**Comment by jpountz** [comment]
You are totally right! Would you like to open a pull request? I'm just asking in case you would like to do it since you already did the investigation but if you have no time for it, I'll happily do it.

**Comment by prog8** [comment]
I'd be glad if you can prepare the change. Thanks!

**Comment by jpountz** [comment]
No problem, I will!

**Comment by jpountz** [comment]
It's been fixed and the fix will be in 1.5 and future versions. Thanks for reporting this bug and investigating!
