### ISSUE TITLE
Need additional line in config file, to work tutorial's example.

### ISSUE THREAD

**Issue by nesah** [elastic/elasticsearch#10074]
I'm afraid to say, I wrote bellow 'additional line' in ' elasticsearch/config/elasticsearch.yml
', to work tutorial's example about 'Updating Documents' by 'script'.
So, it is needed to add an explanation in tutorial.

// additional line
script.groovy.sandbox.enabled: true

// error
{
  "error" : "ElasticsearchIllegalArgumentException[failed to execute script]; nested: ScriptExceptio
n[dynamic scripting for [groovy] disabled]; ",
  "status" : 400
}

**Comment by javanna** [comment]
Thanks @nesah I just added a note mentioning that dynamic scripting needs to be enabled in order for the script based update to work.

**Comment by nesah** [comment]
@javanna, thank you very much : )
