### ISSUE TITLE
 Failed to load eclipse jdt formatter: java.lang.RuntimeException: java.net.SocketTimeoutException: 

### ISSUE THREAD

**Issue by ChrisHegarty** [elastic/elasticsearch#100753]
[elastic / elasticsearch # main - packaging upgrade tests » 8.2.0,rocky-linux-8-packaging #1980](https://gradle-enterprise.elastic.co/s/3ftpwyhc2gupi)
Failure message:
A problem occurred configuring project ':x-pack:plugin:esql:compute'.
> java.io.IOException: Failed to load eclipse jdt formatter: java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
  > Failed to load eclipse jdt formatter: java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
    > java.net.SocketTimeoutException: timeout
      > timeout
        > Socket closed

**Comment by ChrisHegarty** [comment]
I'm not sure what the problem is here, but it look related to the machine environment or configuration?

More failures:

[elastic / elasticsearch # main - packaging upgrade tests » 7.0.0,ubuntu-20.04-packaging #1980](https://gradle-enterprise.elastic.co/s/qomcdp5l4fvgi)
Failure message:
A problem occurred configuring project ':x-pack:plugin:esql:compute'.
> java.io.IOException: Failed to load eclipse jdt formatter: java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
  > Failed to load eclipse jdt formatter: java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
    > java.net.SocketTimeoutException: timeout
      > timeout


The following build resulted in FAILURE:
[elastic / elasticsearch # main - packaging upgrade tests » 7.13.1,rocky-linux-8-packaging #1980](https://gradle-enterprise.elastic.co/s/nrn7s7jded73m)
Failure message:
A problem occurred configuring project ':x-pack:plugin:esql:compute'.
> java.io.IOException: Failed to load eclipse jdt formatter: java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
  > Failed to load eclipse jdt formatter: java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
    > java.net.SocketTimeoutException: timeout
      > timeout


The following build resulted in FAILURE:
[elastic / elasticsearch # main - packaging upgrade tests » 8.8.2,rocky-linux-8-packaging #1980](https://gradle-enterprise.elastic.co/s/2xy3l3gpi7koy)
Failure message:
A problem occurred configuring project ':x-pack:plugin:esql:compute'.
> java.io.IOException: Failed to load eclipse jdt formatter: java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
  > Failed to load eclipse jdt formatter: java.lang.RuntimeException: java.net.SocketTimeoutException: timeout
    > java.net.SocketTimeoutException: timeout
      > timeout

**Comment by mark-vieira** [comment]
This was a fun one. It turns out the spotless tasks make queries to a public P2 repository to get dependency information _and_ eagerly resolve those dependencies on task creation. We mostly avoid this problem by _lazily_ registering and configuring these tasks but this project was configuring the `spotlessJava` task in a non-lazy way, triggering eager creation of the task, and therefore going out and fetching these dependencies on every build with an empty local cache. I've opened https://github.com/elastic/elasticsearch/pull/100789 so that that we at least should never hit this error in a build that doesn't even run spotless.
