### ISSUE TITLE
elasticsearch.bat fails to start

### ISSUE THREAD

**Issue by agiletestware** [elastic/elasticsearch#10078]
D:\elasticsearch-1.4.4\elasticsearch-1.4.4\bin>elasticsearch.bat
The system cannot find the path specified.

No error message. Not really what the batch file does not start.

**Comment by dadoonet** [comment]
I would bet that JAVA_HOME is not set or "java" command can not be found.
Could you check your Java settings?

**Comment by agiletestware** [comment]
yup, you were right. Maybe a better error message in the future
