### ISSUE TITLE
[DOCS] Fix error in the scripted_metric documentation

### ISSUE THREAD

**Issue by consulthys** [elastic/elasticsearch#100769]
### Elasticsearch Version

8.10.2

### Installed Plugins

-

### Java Version

_bundled_

### OS Version

Darwin iMac.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

### Problem Description

In the `scripted_metric` documentation that describes the [scope of each script](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-scripted-metric-aggregation.html#scripted-metric-aggregation-scope), it is stated what follows regarding the `map_script`:

> If no combine_script is specified, the resulting state needs to be stored in the state object.

However, it is not possible to not provide the `combine_script` anymore since [this issue](https://github.com/elastic/elasticsearch/issues/32804).

As it is clearly stated that both map and combine scripts are required, the above sentence should be removed from the documentation, to not confuse readers.

### Steps to Reproduce

1. Got to https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-scripted-metric-aggregation.html#scripted-metric-aggregation-scope
2. The third sentence for `map_script` should be removed

**Comment by pernelkanic** [comment]
Can I work on this issue?

**Comment by jrodewig** [comment]
@pernelkanic Yes — Please feel free. [Contributions](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-code-and-documentation-changes) are welcome.

**Comment by pernelkanic** [comment]
I have opened the pr

**Comment by pernelkanic** [comment]
i have updated the pr!
