### ISSUE TITLE
Bug when fvh highlighting a phrase query on an ngrammed field

### ISSUE THREAD

**Issue by bsander** [elastic/elasticsearch#10071]
Not really sure how to accurately describe this bug. I've narrowed it down to a combination of the following elements:
- Fast Vector Highligter
- Phrase query with slop
- Performing a search where at least one of the words is a prefix of another word in the query (in the case below: `in` and `internet`.

Steps to reproduce:

``` bash
#1. Create index with mapping
curl -XPUT "http://localhost:9200/bugtest" -d'
{
  "settings": {
    "analysis": {
      "analyzer": {
        "suggest_analyzer": {
          "type": "custom",
          "tokenizer": "my_edgeNgram",
          "filter": [
            "lowercase"
          ]
        }
      },
      "tokenizer": {
        "my_edgeNgram": {
          "type": "edgeNGram",
          "min_gram": 1,
          "max_gram": 20,
          "token_chars": [
            "letter"
          ]
        }
      }
    }
  },
  "mappings": {
    "case": {
      "properties": {
        "text": {
          "type": "string",
          "term_vector": "with_positions_offsets",
          "index_analyzer": "suggest_analyzer",
          "search_analyzer": "simple"
        }
      }
    }
  }
}'

#2. Put a document in it that will match the query
curl -XPUT "http://localhost:9200/bugtest/case/1" -d'
{
  "text": "Something is happening in the internet.."
}'

#3. Perform a highlighted phrase query where the first token is a prefix of the second
curl -XPOST "http://localhost:9200/bugtest/_search" -d'
{
  "query": {
    "match": {
      "text": {
        "query": "in internet",
        "type": "phrase",
        "slop": 50
      }
    }
  },
  "fields": [],
  "highlight": {
    "fields": {
      "text": {}
    }
  }
}'
```

This results in the following error on es 1.4.4:

``` json
{
   "took": 2,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 4,
      "failed": 1,
      "failures": [
         {
            "index": "bugtest",
            "shard": 2,
            "status": 500,
            "reason": "FetchPhaseExecutionException[[bugtest][2]: query[text:\"in internet\"~50],from[0],size[10]: Fetch Failed [Failed to highlight field [text]]]; nested: StringIndexOutOfBoundsException[String index out of range: -2]; "
         }
      ]
   },
   "hits": {
      "total": 1,
      "max_score": 0.039147545,
      "hits": []
   }
}
```

As said, this only happens when a search is performed where the first word is a prefix of the second. When I change the query just one letter to `is internet` everything works as expected.

**Comment by s1monw** [comment]
hmm can you do me a favor and try simple analyzer for both search and index? It seems like the suggest analyzer is messing with positions here...

**Comment by bsander** [comment]
Yes, I tried that too while chasing down this thing. If all analysis on the field is changed to `simple` the problem doesn't occur.

**Comment by nik9000** [comment]
My Experimental highlighter doesn't seem to mind that use case.  I imagine its something with the FVH.  I'll do a bit of debugging.

**Comment by nik9000** [comment]
Looks like the FVH just messes up the fragments somehow: ```subInfos=(ininternet((30,32)(30,38)))/1.0(0,100)```

**Comment by nik9000** [comment]
It puts the "in" part of the match on top of the "internet" part of the match....

It does that because ```in``` is a prefix of ```internet```.....

The experimental highlighter doesn't mind these because it contains a filter that removes overlaps like this.

I think the right thing to do here is to stop FieldTermStack from spitting out overlaps.  Or to teach BaseFragListBuilder to merge the overlaps.  Probably the second one is better because its broader - it'd handle other overlaps in case they come up.

**Comment by bsander** [comment]
Hi @nik9000, is this still something that's being worked on?

**Comment by nik9000** [comment]
@bsander I'm not, no. I diagnosed it but never worked on it. Right now issues like this are a weekend project for me and with three kids I don't typically get to it. Its also a bit of a conflict of interest for me because the experimental highlighter is my baby. And the more time I work on it the less I want to go back and fix stuff in the other 3 highlighters....

**Comment by clintongormley** [comment]
Closing in favour of #21621
