### ISSUE TITLE
[Transform] Integrate transforms with the node shutdown API

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#100891]
Transforms currently do not take account of whether the node they're running on has been notified that it is shutting down.

In stateful Elasticsearch this never seemed to matter. I don't remember ever seeing a report of a failed transform that could be attributed to its node shutting down.

In stateless Elasticsearch we currently see many transform failures during rolling restarts of clusters. There are a variety of reasons, and some of the failures occur after moving to the new node rather than while running on the node that is shutting down.

Given that we haven't seen problems in current GA product, and don't want to disturb the code too much, a compromise solution to dealing with node shutdowns on transform nodes would be to say that if a transform suffers a condition that causes it to call `fail` on a node that is shutting down, instead of actually failing the transform should just mark itself locally complete so that the persistent tasks framework relocates it to a different node. If the cause of failure was something systemic to the cluster then it will fail again on the new node after redoing its most recent work. But if the cause of failure was something related to the node shutdown then the transform should pick up its work successfully on the new node, thus avoiding a spuriously failed transform.

**Comment by prwhelan** [comment]
> instead of actually failing the transform should just mark itself locally complete so that the persistent tasks framework relocates it to a different node

https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/persistent/AllocatedPersistentTask.java#L144

**Comment by prwhelan** [comment]
>Given that we haven't seen problems in current GA product, and don't want to disturb the code too much, a compromise solution to dealing with node shutdowns on transform nodes would be to say that if a transform suffers a condition that causes it to call fail on a node that is shutting down, instead of actually failing the transform should just mark itself locally complete so that the persistent tasks framework relocates it to a different node. If the cause of failure was something systemic to the cluster then it will fail again on the new node after redoing its most recent work. But if the cause of failure was something related to the node shutdown then the transform should pick up its work successfully on the new node, thus avoiding a spuriously failed transform.

We'll go with this option.  The alternative is to mimic what ML and health do, which is a proactive graceful shutdown by listening for node shutdowns on cluster changes: [ML Example](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/assignment/TrainedModelAssignmentClusterService.java#L117), [Health example](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/health/node/selection/HealthNodeTaskExecutor.java#L103).  We already have a [TransformClusterStateListener](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/transform/src/main/java/org/elasticsearch/xpack/transform/TransformClusterStateListener.java) and may be able to reuse that.

Benefits of the alternative are to potentially prevent errors from even occurring in the first place, but the costs are a potentially intrusive change that impacts GA.  We'd need something reactive anyway in case the proactive fails, so we'll go with the reactive option first.
