### ISSUE TITLE
Exponential, Gauss and Linear decay function classes have incorrect `equals`

### ISSUE THREAD

**Issue by Marcono1234** [elastic/elasticsearch#100870]
### Elasticsearch Version

8.10.3

### Java Version

Java 17

### OS Version

Windows 10

### Problem Description

The `equals` method implementation of the following classes looks incorrect:
- `ExponentialDecayFunctionBuilder.ExponentialDecayScoreFunction`
- `GaussDecayFunctionBuilder.GaussScoreFunction`
- `LinearDecayFunctionBuilder.LinearDecayScoreFunction`

They all look like this:
```java
public boolean equals(Object obj) {
    if (super.equals(obj)) {
        return true;
    }
    return obj != null && getClass() != obj.getClass();
}
```

There are two problems:
- The fast `return true` for `super.equals(obj)` seems quite brittle and only works because those classes all directly extend `Object` and therefore that `super.equals` call actually checks for identity equality
- `getClass() != obj.getClass()` looks wrong; that should probably check `==`

Suggested implementation:
```java
public boolean equals(Object obj) {
    return obj == this
        || (obj != null && obj.getClass() == this.getClass());
}
```

### Steps to Reproduce

These all erroneously print "true":
```java
System.out.println(ExponentialDecayFunctionBuilder.EXP_DECAY_FUNCTION.equals("a string"));
System.out.println(GaussDecayFunctionBuilder.GAUSS_DECAY_FUNCTION.equals("a string"));
System.out.println(LinearDecayFunctionBuilder.LINEAR_DECAY_FUNCTION.equals("a string"));
```

**Comment by jww1226** [comment]
Can I work on it?

**Comment by craigtaverner** [comment]
> Can I work on it?

If you wish to work on this and create a PR that resolves this, please first read the contributor guidelines at https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-code-and-documentation-changes, and be sure follow that advice.
