### ISSUE TITLE
setup elasticsearch on a server

### ISSUE THREAD

**Issue by mtuchi** [elastic/elasticsearch#10085]
Am new in elastic search, i am building a search engine for my website using elasticsearch and php.
i want to update my project in my hosting server everything works perfectly in my localhost (my PC) but when i update the project in my hosted server this is what i get 

<code>
Fatal error: Uncaught exception 'Elasticsearch\Common\Exceptions\Curl\CouldNotConnectToHost' with message 'couldn't connect to host' in /home/uhuru372/public_html/unilodb/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/AbstractConnection.php:320 Stack trace: #0 /home/uhuru372/public_html/unilodb/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(313): Elasticsearch\Connections\AbstractConnection->throwCurlException(7, 'couldn't connec...') #1 /home/uhuru372/public_html/unilodb/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(200): Elasticsearch\Connections\GuzzleConnection->processCurlError(Object(Guzzle\Http\Exception\CurlException)) #2 /home/uhuru372/public_html/unilodb/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/GuzzleConnection.php(104): Elasticsearch\Connections\GuzzleConnection->sendRequest(Object(Guzzle\Http\Message\EntityEnclosingRequest), '{"query":{"bool...') #3 /home/uhuru372/public_html/unilodb/vendor/ in /home/uhuru372/public_html/unilodb/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/AbstractConnection.php on line 320
</code>

Help or suggestion will be much appreciated

**Comment by dadoonet** [comment]
Hi @mtuchi 

You should better ask this on the mailing list. We can definitely help you there.
Provide there more details about what you are exactly doing. I don't see why you are using CURL from PHP but may be I am misunderstanding your trace here.

Closing as it's not an issue but more a usage question.
