### ISSUE TITLE
`OperationModeUpdateTask.hashCode` is incorrect

### ISSUE THREAD

**Issue by Marcono1234** [elastic/elasticsearch#100871]
### Elasticsearch Version

8.10.3

### Java Version

Java 17

### OS Version

Windows 10

### Problem Description

The `hashCode` method of `org.elasticsearch.xpack.core.ilm.OperationModeUpdateTask` seems incorrect. It calls `super.hashCode`, but no superclass overrides the method, so effectively it calls `Object.hashCode` and therefore for two different objects their hash code will most likely always differ, even if they should be considered equal.

### Steps to Reproduce

```java
Object o1 = OperationModeUpdateTask.ilmMode(OperationMode.RUNNING);
Object o2 = OperationModeUpdateTask.ilmMode(OperationMode.RUNNING);

// This works
System.out.println("Equals: " + o1.equals(o2));
// This doesn't work; prints different hashCode values
System.out.println("hashCode:\n  o1: " + o1.hashCode() + "\n  o2: " + o2.hashCode());
```

**Comment by DaveCTurner** [comment]
I can't immediately think of a great reason why anything would test these things for equality or otherwise care about their hashcode. Should we just remove the `equals` and `hashcode` impls?

**Comment by DaveCTurner** [comment]
> I thought maybe this is relevant for you nonetheless which is why I created this issue; I hope that was ok.

It was indeed, thanks for the report @Marcono1234
