### ISSUE TITLE
Secure settings reload API will return a success when the keystore contains invalid settings

### ISSUE THREAD

**Issue by jakelandis** [elastic/elasticsearch#100844]
### Elasticsearch Version

all

### Java Version

_bundled_

### OS Version

all

### Problem Description

Elasticsearch has an API that can reload secure settings (if the secure settings supports hot reloads) from the keystore. If you place a non-existent setting in the keystore, then the reload API will still return a success. The next time Elasticsearch restarts will you discover that you have an invalid setting due to the node not starting up. We should be able to catch that scenario in the reload API and return a failure with a reason. Note - this bug only applies to non-existent settings. Returning if an existing setting is valid after reload is much different and considerably more difficult issue to address. 

### Steps to Reproduce

Start Elasticsearch
Update the keystore with a setting that does not exist.
Call the reload API (note it returns success)
Restart Elasticsearch (note it will fail to start)

The fix here is to ensure the call to the reload API returns a failure. Restarting Elasticsearch with an non-existent key should continue to fail to start after this is fixed.

**Comment by jfreden** [comment]
Resolved in: https://github.com/elastic/elasticsearch/pull/103176
