### ISSUE TITLE
Java API Doc Typo

### ISSUE THREAD

**Issue by Fulwing** [elastic/elasticsearch#100873]
### Elasticsearch Version

8.10

### Java Version

_bundled_

### OS Version

win 10

### Problem Description

for the [delete index](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/getting-started-java.html#_deleting_an_index), I think there is a typo, it should be delete not create.

### Steps to Reproduce

N/A

**Comment by SWITCHin2** [comment]
Can I work on it?

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
