### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test {p0=aggregations/percentiles_tdigest_metric/Non-keyed test} failing

### ISSUE THREAD

**Issue by arteam** [elastic/elasticsearch#100955]
**Build scan:**
https://gradle-enterprise.elastic.co/s/h5heihbkhfl6s/tests/:qa:mixed-cluster:v7.17.15%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=aggregations%2Fpercentiles_tdigest_metric%2FNon-keyed%20test%7D
**Reproduction line:**
```
./gradlew ':qa:mixed-cluster:v7.17.15#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=aggregations/percentiles_tdigest_metric/Non-keyed test}" -Dtests.seed=A1A6C6B7E8C3C222 -Dtests.bwc=true -Dtests.locale=es-DO -Dtests.timezone=America/Puerto_Rico -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Daggregations/percentiles_tdigest_metric/Non-keyed%20test%7D
**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([A1A6C6B7E8C3C222]:0)

```

**Comment by kkrik-es** [comment]
Timeout, not much to do.. Will keep it open for 1-2 days, then close.
