### ISSUE TITLE
[ES|QL] Provide some documentation for builtin operators/functions

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch#100958]
### Description

It is not super clear where builtin operators (i.e. `%`, `+`, `like`, `in`, `>`) can/should be used.

For instance comparison operators can be used for numbers, dates or strings but this is not documented anywhere.
Ideally this information would be really useful at `SHOW FUNCTIONS` level, but I understand it can be too much.
Maybe `SHOW BUILTIN` command can be useful here.

Either way improve the documentation around this can be useful without extending ES|QL itself.
Right now we had to manually test and document all possible builtin operators signatures to discover the stretch of them, but having a source of truth would be great.

**Comment by nik9000** [comment]
This is being tracked in #100558, though it's going slowly.
