### ISSUE TITLE
[ES|QL] Improve functions documentation to list also function alias names

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch#100959]
### Description

The `SHOW FUNCTIONS` command returns several functions not documented anywhere:

```
to_str
to_ul
to_ulong
..etc
```

these seems to be some alias names of existing functions (i.e. `to_str` => `to_string`).
It would be nice to have them documented on each function page.

**Comment by nik9000** [comment]
We're tracking this work in #100558 - though it's going slowly.
