### ISSUE TITLE
Move IndicesStatsRequest to expose CommonStatsFlags directly

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#10096]
Currently IndicesStatsRequest has a method per possible index metric. Internally theses are stored using a `CommonStatsFlags` object. This means that every time we add a stat we need to remember to add a method and remember to map it in `RestIndicesStatsAction` rather we should just expose the underlying flag, just like `NodesStatsRequest.indices()` allowing for some automation in the mapping.

**Comment by Plokji** [comment]
Hi I'm new to contributing to OSS. I would like to have a try and resolve this issue.
Thanks.
