### ISSUE TITLE
[Transform] Supply an `index_filter` when calling field caps and creating a PIT reader

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#101049]
Transforms can be configured to search incredibly broad index patterns. These cause the lower level actions used by transforms to iterate huge numbers of shards unless measures are taken to restrict which shards are considered using information available in cluster state.

Anywhere where transforms calls an action that iterates shards it must use the `index_filter` functionality of that action to reduce scope. Calls to be changed:

- [x] Field caps
- [ ] Creating PIT readers - requires #99740 be implemented as a pre-requisite

**Comment by przemekwitek** [comment]
There is a PR already opened that adds `index_filter` to `open_point_in_time` request (https://github.com/elastic/elasticsearch/pull/102388).
Once that PR is merged, I will be able to plug the source query to this index filter.

**Comment by javanna** [comment]
Heads up: #102388 is merged, an index_filter can now be specified as part of the open point in time call.
