### ISSUE TITLE
Run script on write to multi-index alias

### ISSUE THREAD

**Issue by grantr** [elastic/elasticsearch#10107]
Indexing into multi-index aliases would be super useful. What if it were possible to define a script on an alias that runs on incoming documents and emits an index name? Sort of like an alias filter.

For example:
```
curl -XPOST 'http://localhost:9200/_aliases' -d '{
    "actions" : [
        {
            "add" : {
                 "index" : "logs-20150316",
                 "alias" : "logs-daily",
                 "placement": {
                   "lang": "groovy",
                   "script": "
                     date = new Date().parse(doc['timestamp'])
                     'logs-' + date.format('YYYYmmdd')"
                 }
            }
        }
    ]
}'
```

In real life, the script would probably be defined in a file instead of dynamic. If the script doesn't return a valid index name, the usual "multiple indices matched" error could be thrown.

/cc @drewr @TwP

**Comment by dakrone** [comment]
@grantr this is going to be tough because the `doc['timestamp']` would be loaded from field data or doc_values, however, the document doesn't yet exist in the index, so there's nowhere to load field data from?

**Comment by dakrone** [comment]
In order to support this, I think we would need to parse the document itself and provide a way of accessing it (perhaps just using `_source` would work, I don't know) in a script.

**Comment by grantr** [comment]
@dakrone The index request has the document in hand, so it doesn't have to come from the index. I figured it could be passed to the script somehow.

**Comment by dakrone** [comment]
@grantr yeah, it would be the `_source` equivalent (pre-analysis) instead of `doc` equivalent (post-analysis)

**Comment by grantr** [comment]
@dakrone that's fine. the `doc['timestamp']` example was just pseudocode. I wouldn't expect the document to have already gone through the indexing pipeline. I expect 99% of the use cases for this would be looking at dates and numbers, and the other 1% at non-analyzed strings.

**Comment by javanna** [comment]
I marked this for discussion. I am -1 on this specific proposal, I think it would slow indexing down and, while scripting is very appealing and powerful, I am not sure I would want to see it supported here, feels scary.

Why would you want to write into a different index depending on document fields though? When it comes to logging, there usually is a single index (the most recent one?) that you would write into out of the indices that the alias points to. We could add a new property to the multi-index alias that holds the index name for write operations, which needs to be a single index and part of the indices that the alias points to for reads. If not specified, behaviour remains the same as now (no write will happen). Thoughts?

**Comment by grantr** [comment]
Thanks for your thoughts @javanna!

> Why would you want to write into a different index depending on document fields though?

Specifying a single write index would be a good start, but doesn't fit our use case. For one of our time-series indices used for tracking exceptions, it isn't enough to always write to the most recent index. Documents might be queued or in flight during the rollover, causing some documents to be indexed in the wrong index.

We also move documents that are marked as interesting (i.e. viewed by a human) out of rotating indices and into a permanent index so that links to them never expire. The index must be deterministic so we can find the interesting documents to be moved later.

Another use case is splitting a large mutable index into multiple smaller ones for better maintainability. Documents would be bucketed by id or some other field.

> I think it would slow indexing down

Scripting might slow indexing slightly, but the user who needs this functionality pays that cost whether it's in the app or in Elasticsearch, so the end-to-end latency is the same.

> I am not sure I would want to see it supported here, feels scary.

What about scripting support here feels scary? It doesn't seem any scarier than running scripts on searches, where a misbehaving or poorly written script could take a node down. Scripting in any context is a power feature that needs to be used with care.

**Comment by clintongormley** [comment]
It feels to me like the right place for this is logstash, which already does things like using the timestamp to determine which index the document should be sent to.  Logstash is an ETL pipeline, but Elasticsearch isn't.  I'd much rather not add this kind of complexity to ES.

**Comment by grantr** [comment]
> Logstash is an ETL pipeline, but Elasticsearch isn't.

The recent deprecation of rivers makes this statement more acceptable. Elasticsearch definitely was an ETL pipeline until then.

I still don't understand the resistance to this feature, but it seems pretty definite, so I'll close this. We'll implement it as a proxy most likely.
