### ISSUE TITLE
Permit shards to move away from shutting down nodes despite pending snapshot activity

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#101171]
Today the `SnapshotInProgressAllocationDecider` prevents a shard from moving while there is some outstanding snapshot work for that shard, but that means that there's a risk that a shard might never move if snapshots happen frequently enough. As a workaround for this situation, today in ESS we stop SLM and wait for all ongoing snapshots to complete before proceeding with certain plan changes. This leaves a gap in the sequence of regular snapshots that might last many hours, extending the possible window of data loss should a recovery be necessary.

I think it would be preferable to keep SLM running and permit shards to move despite ongoing snapshot activity. The result would be a `PARTIAL` snapshot, missing only the data for shards that moved while being snapshotted (although when we complete https://github.com/elastic/elasticsearch/issues/71333 then these shard snapshots would retry on their new nodes and succeed).

Specifically, I think we should adjust the `SnapshotInProgressAllocationDecider` to permit shard movements away from a node that is marked for shutdown despite ongoing snapshot activity. I suspect we should still block movements if any of the pending snapshots are not `.partial()` (since in this case a single shard movement will cause the whole snapshot to fail) but this isn't the case that matters with SLM.

**Comment by ywangd** [comment]
I wonder whether it should be a separate flag instead of relying on the exisitng `partial` flag. 
(Not really part of this dicussion, but it helps to explain my above question) I wonder whether all snapshots should always be partial. Failing the entirely snapshot due to a single missing primary seems to be rather punishing for large clusters? If all snapshots are partial, it seems to make more sense to have a separate flag to control shard locking behaviour to increase the chance to have a full snapshot.

**Comment by ywangd** [comment]
Is this issue of a duplicate of #98081? It has more context now. So we might want to close #98081 instead if it is indeed a duplicate.

**Comment by DaveCTurner** [comment]
> Is this issue of a duplicate of https://github.com/elastic/elasticsearch/issues/98081?

Oh it is indeed. Thanks for spotting that.

> I wonder whether it should be a separate flag instead of relying on the exisitng partial flag.

I agree that partial snapshots make much more sense than full ones in pretty much all cases because of all the work that a failed full snapshot discards only to repeat on the next one. Indeed it'd be good if aborting a snapshot didn't actively remove the partially completed state, see https://github.com/elastic/elasticsearch/issues/75340. I'm not sure there's much need to offer a choice about the specific behaviour proposed in this issue tho - users need to be prepared to handle missing shards during a restore either way, and I'm not sure this change would make much of an impact on the shard-level success rate in practice. I'd rather we improved the success rate with #71333 instead of making this optional at least - maybe we could say that #71333 is a prerequisite for this change.

**Comment by ywangd** [comment]
> I'm not sure this change would make much of an impact on the shard-level success rate in practice

If it does _not_ have a noticeable impact on shard-level success rate, my point is moot. I was a bit concerned whether users would observe partial snapshots tend to finish with less content which makes it harder to get a full restore.

> I'd rather we improved the success rate with https://github.com/elastic/elasticsearch/issues/71333 instead of making this optional at least - maybe we could say that https://github.com/elastic/elasticsearch/issues/71333 is a prerequisite for this change.

That would be ideal. But seems to be a much higher bar compared to what is proposed here? Depending on how urgent we need this particular change, we might still want to go with the change proposed here without #71333?

**Comment by DaveCTurner** [comment]
Comment moved from [related issue](https://github.com/elastic/elasticsearch/issues/71333#issuecomment-1784909901):

This plan turns out to be pretty tricky to fit into the snapshots state machine as it currently stands today. The assumption that shards don't move while being snapshotted is implicit in several places deep within the convoluted logic of the `SnapshotsService`, and I am not confident we will find them all. I'm going to try a different approach, integrating things more closely with graceful node shutdown and avoiding the need to handle other kinds of node departure:

---

## Abort shard snapshots on shutting-down nodes

Adjust the `SnapshotShardsService` to notice that the local node has a shutdown marker and treat that as if all its ongoing shard snapshots are aborted. When each one completes, respond indicating it should move back to state `WAITING` rather than going to `FAILED`.

I suspect this won't work (or at least it will break some invariants) in older versions, so if the min cluster version is too old then skip this logic.

## Stop moving shards from WAITING/QUEUED to INIT state on shutting-down nodes

Adjust the `SnapshotsService` to treat primaries assigned to shutting-down nodes as if they were unassigned.

---

I think with these two changes we will react well to graceful shutdowns, stopping shard snapshot work ASAP without causing a `PARTIAL` snapshot, permitting the shards to relocate elsewhere, and resuming the shard snapshot work on more appropriate nodes.

I don't think we need to put extra effort into limiting the retries with this plan, as suggested in an earlier comment. As long as the node shutdown markers aren't flapping and the shards eventually relocate or the node restarts, each snapshot will complete.

If we cannot relocate a shard onto a new node then the snapshot will also never complete. However I believe that we treat this as a failure case in other ways too, eventually timing out and either stopping the node or else removing the shutdown marker, either of which permits the snapshot to proceed.

**Comment by ywangd** [comment]
(copied from https://github.com/elastic/elasticsearch/issues/71333#issuecomment-1786418746)

Thanks for the code diff which gives me more concrete understanding on the proposal. I think it works in the context of node-shutdown. I do have some questions for your [comment](https://github.com/elastic/elasticsearch/issues/101171#issuecomment-1786528812) and about how this propsoal compared to the broader node-departure scenarios.

> The assumption that shards don't move while being snapshotted is implicit in several places deep within the convoluted logic of the SnapshotsService

Could you please share one or a few examples of this tanglement? 

> integrating things more closely with graceful node shutdown and avoiding the need to handle other kinds of node departure

This suggests node-shutdown is easier to handle compare to the more generic node-depature. I think this makes sense intuitive. But I cannot quite articulate why. Is this because we can preemptively react to the shutdown request and we can assume (and rely on?) shards will come back eventually. While for a general node-departure scenario, it is unknown whether the shard would come back which leads to the "finite number of retry" issue? It seems moving shard back to WAITING state should make no difference for either node-shutdown or node-departure?

> I suspect this won't work (or at least it will break some invariants) in older versions, so if the min cluster version is too old then skip this logic.

Why won't this wor with old versions? Is it because UUID shard-generation, i.e. old versions that do not use UUID shard-generation could overwrrite each other?

> If we cannot relocate a shard onto a new node then the snapshot will also never complete. However I believe that we treat this as a failure case in other ways too, eventually timing out and either stopping the node or else removing the shutdown marker, either of which permits the snapshot to proceed.

How do we "eventually timing out"? Will this be new code? I am not quite sure how "stopping the node" can permit snapshot to proceed? To allow snapshot to resume when "removing the shutdown marker", the change needs to be made in `SnapshotsService`, right? Essentially a corollary of "Stop moving shards from WAITING/QUEUED to INIT state on shutting-down nodes"?

Appologies if some of the questions are naive. Still trying to get my head around this area. Thanks!

**Comment by DaveCTurner** [comment]
> > The assumption that shards don't move while being snapshotted is implicit in several places deep within the convoluted logic of the SnapshotsService

> Could you please share one or a few examples of this tanglement? 

For example in `SnapshotsService#processWaitingShardsAndRemovedNodes` we won't process a `WAITING` shard until the state is exactly `started()` - `relocating()` means to continue to wait, and likewise `SnapshotsService#waitingShardsStartedOrUnassigned` is only looking at `started()` shards.

> > integrating things more closely with graceful node shutdown and avoiding the need to handle other kinds of node departure

> This suggests node-shutdown is easier to handle compare to the more generic node-depature. I think this makes sense intuitive. But I cannot quite articulate why. Is this because we can preemptively react to the shutdown request and we can assume (and rely on?) shards will come back eventually. While for a general node-departure scenario, it is unknown whether the shard would come back which leads to the "finite number of retry" issue? It seems moving shard back to WAITING state should make no difference for either node-shutdown or node-departure?

Pretty much yes. It isn't valid to move shard to `WAITING` for the node-departure case, we either have to move them to `INIT` on a new node, or `MISSING`, depending on whether there's another copy or not. Or `FAILED` I guess if there's been too many failovers without making progress. And all of that is happening underneath a bunch of other conditionals in `SnapshotService`.

> > I suspect this won't work (or at least it will break some invariants) in older versions, so if the min cluster version is too old then skip this logic.

> Why won't this wor with old versions? Is it because UUID shard-generation, i.e. old versions that do not use UUID shard-generation could overwrrite each other?

Mainly because of things like older versions not moving a shard from `WAITING` back to `INIT` if the shutdown marker is removed, meaning the snapshot will be stuck forever. Neatly enough if we abort the snapshot on the data node and wait for the data node to notify the master that it has completed then that preserves the property that two data nodes are never writing to the same shard path, which means it also works correctly with the pre-7.6 repository format.

> > If we cannot relocate a shard onto a new node then the snapshot will also never complete. However I believe that we treat this as a failure case in other ways too, eventually timing out and either stopping the node or else removing the shutdown marker, either of which permits the snapshot to proceed.

> How do we "eventually timing out"? Will this be new code? I am not quite sure how "stopping the node" can permit snapshot to proceed? To allow snapshot to resume when "removing the shutdown marker", the change needs to be made in `SnapshotsService`, right? Essentially a corollary of "Stop moving shards from WAITING/QUEUED to INIT state on shutting-down nodes"?

The timeout is ultimately a control-plane thing. Stopping the node ensures we run `SnapshotsService#processWaitingShardsAndRemovedNodes` which will move `WAITING` shards to `INIT` or `FAILED`, and we need to do something similar when removing the shutdown marker.

**Comment by DaveCTurner** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/101717.
