### ISSUE TITLE
add command-line configuration check command

### ISSUE THREAD

**Issue by tamsky** [elastic/elasticsearch#10119]
I'd like to run a command that confirms:
  The contents of my `elasticsearch.yml` does not result in an exception being thrown at startup due to a configuration item value being invalid.

An example of this pattern can be found in the bind nameserver:
`named-checkconf /etc/named.conf`

This would allow configuration automation tools to validate files after modification but before restarting the service and finding out it doesn't start.

**Comment by clintongormley** [comment]
Interesting idea.  First step though is actually detecting bad settings in Elasticsearch itself.  Very often we'll just ignore anything we don't understand.  Stalled by #6732

**Comment by clintongormley** [comment]
Closing in favour of #6732
