### ISSUE TITLE
Change cluster name not indexes

### ISSUE THREAD

**Issue by DanyHubGit** [elastic/elasticsearch#10115]
Hi, I have a problem with changing elasticsearch cluster name.
If I change the cluster name (tag cluster.name) in elasticsearch.yml file config, elasticsearch doesn't create any index, when receive the input by logtash.
If I reset the elasticsearch cluster name with the default value of standard configuration (elasticsearch), elasticsearch server restart to create indexes.

Are there any steps or commands to execute to have a new cluster (not default name!), with an own name and that create correctly the indexes?

Tnxs a lot,

**Comment by dadoonet** [comment]
You should ask questions on the mailing list instead of here.

That said, it's IMO a misusage of logstash. You need also to change the cluster name in LS output (depending on the elasticsearch output type you are using).

Closing as it's not an issue.
