### ISSUE TITLE
Mapping transform doesn't support file and indexed scripts

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#10113]
Looks like the mapping transform feature supports dynamic scripts only. When submitting the following request:

```
curl -XPUT localhost:9200/test -d '{
  "mappings" : {
    "example" : {
        "transform" : {
            "script_id" : "1",
            "lang": "groovy"
        }
    }
  }
}
'
```

the mapping stored in the cluster state becomes the following, hence it loses the information about where the script should be loaded from:

```
{
  "test": {
    "mappings": {
      "example": {
        "transform": {
          "script": "1",
          "lang": "groovy"
        },
        "properties": {
          "test": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

Might relate to #9995.

**Comment by clintongormley** [comment]
@colings86 i thought that the change in https://github.com/elastic/elasticsearch/pull/11164 would fix this, but apparently not?

**Comment by colings86** [comment]
@clintongormley it should do. Have you tried it?

**Comment by clintongormley** [comment]
yes, eg i save a file called `test.groovy`, then

    PUT t
    {
      "mappings": {
        "t": {
          "transform": {
            "script": {
              "file": "test"
            }
          }
        }
      }
    }

then i get:

    {
       "error": {
          "root_cause": [
             {
                "type": "script_parse_exception",
                "reason": "Value must be of type String: [script]"
             }
          ],
          "type": "mapper_parsing_exception",
          "reason": "mapping [t]",
          "caused_by": {
             "type": "script_parse_exception",
             "reason": "Value must be of type String: [script]"
          }
       },
       "status": 400
    }

**Comment by colings86** [comment]
Hmm, ok I'll take a look

**Comment by colings86** [comment]
@clintongormley currently the `transform` object is treated as the script (this is actually (almost) backwards compatible as previously the `transform` object could have `lang`, `script` and `params` fields) , which is why you are getting the error. The following request does work:
```javascript
PUT t
{
  "mappings": {
    "t": {
      "transform": {
          "file": "test"
      }
    }
  }
}
```

I can change it so that we require the `script` object under the `transform` object but since we only have scripted transforms it seemed cleaner this way. WDYT?

**Comment by clintongormley** [comment]
@colings86 doh - i should have realised.  thanks for testing. 

Closed by https://github.com/elastic/elasticsearch/pull/11164
