### ISSUE TITLE
Deprecate replication:async

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#10114]
Async replication clashes with index sealing (#10032).  Another downside of async replication is that clients cannot be sure that changes have reached the replica. The benefits of async replication can be achieved simply by having more clients (threads or forks). 

Let's deprecate this in 1.5

**Comment by dakrone** [comment]
+1 to deprecate in 1.5, remove in 2.0

**Comment by rjernst** [comment]
+1

**Comment by s1monw** [comment]
+1

**Comment by s1monw** [comment]
@clintongormley can you deprecate it in the docs please for 1.5

**Comment by clintongormley** [comment]
Deprecated in the docs for 1.5.0, and removed from the docs and REST spec in 2.0.

Still needs to be removed in the code.

**Comment by dadoonet** [comment]
Just a note here. It sounds like we deprecated this in docs but we did not add `@Deprecated` annotation in elasticsearch code itself. Should we add it so Java developers would be aware of it when compiling their code?

**Comment by javanna** [comment]
Yes I think we should @dadoonet , can you open an issue or even take care of this with a PR against 1.x?

**Comment by fsaravia** [comment]
Hey everyone, does [this document](https://www.elastic.co/guide/en/elasticsearch/guide/current/distrib-write.html) needs to be updated to state that `async` replication has been deprecated? The document has a `replication` section that talks about `sync` and `async` options.

**Comment by clintongormley** [comment]
@fsaravia the Guide targets ES 1.4.  Yes, it does need a big update for 2.0... i know, i know

**Comment by fsaravia** [comment]
@clintongormley oh, sorry about that. I didn't realize it targets ES 1.4 :)
