### ISSUE TITLE
download.elasticsearch.org: ERROR: no certificate subject alternative name matches

### ISSUE THREAD

**Issue by groovecoder** [elastic/elasticsearch#10129]
Sorry I couldn't see a repository specifically for the elasticsearch.org site. We have a travis install script that uses `wget` to get the elasticsearch `.deb` from download.elasticsearch.org:

https://github.com/mozilla/kuma/blob/3ae992e8f1552c227b26aa02954035da8014043e/scripts/travis-install#L18

But we just started to get this error today from [our Travis builds](https://travis-ci.org/mozilla/kuma/jobs/54732362).
```
+wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.7.deb
--2015-03-17 15:20:49--  https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.7.deb
Resolving download.elasticsearch.org (download.elasticsearch.org)... 2406:da00:ff00::36f3:4d9e, 2406:da00:ff00::36e1:85c3, 2406:da00:ff00::36e1:40a1, ...
Connecting to download.elasticsearch.org (download.elasticsearch.org)|2406:da00:ff00::36f3:4d9e|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name `download.elasticsearch.org'.
To connect to download.elasticsearch.org insecurely, use `--no-check-certificate'.
```

**Comment by rkh** [comment]
see https://github.com/travis-ci/travis-ci/issues/3394#issuecomment-82483124 for explanation and workaround

**Comment by clintongormley** [comment]
Also, switching the domain to `download.elastic.co` should work
