### ISSUE TITLE
Balance Shard Recovery

### ISSUE THREAD

**Issue by kadaan** [elastic/elasticsearch#10123]
When recovering it appears that the choice of which shards to recover concurrently does not lead to a deterministic and sensible order.  For example, in a cluster where the indices have 3 replicas (for a total of 4 copies of data) and 4 shards, within a single index all of shard 1 can be recovered before shard 2.  Additionally, across indices within the same cluster, it would be preferable to ensure that multiple copies of data exists as soon as possible for all shards in all indices, before loading extra replicas.

**Comment by kadaan** [comment]
Related to: elastic/elasticsearch#10121

**Comment by kadaan** [comment]
Additionally, it would be useful for Elasticsearch to try harder to determine which shards can be recovered with zero copying and perform those first. This would allow more shards to be recovered earlier in the recovery.

**Comment by kadaan** [comment]
The node_concurrent_recoveries  setting also can cause slow recoveries by forcing shard to start recovering on a non-optimal node because there are not enough recovery slots on the optimal node.  ES should determine that it is better to wait to start recovery on certain shards rather than force data movement.

**Comment by kadaan** [comment]
Related to: elastic/elasticsearch#2908

**Comment by clintongormley** [comment]
We now recover sync flushed shards first, and we support recovery order. closing
