### ISSUE TITLE
How can I detect if the transmissiom of the og events has been deactivated

### ISSUE THREAD

**Issue by phillo197** [elastic/elasticsearch#101254]
### Description

Can someone please help me. I am new to Elastic ML and I need help to configure a Elastic ML-Job, which detects the deactivation of the transmission of log events.

**Comment by cuevana8** [comment]
+1 Like 🔔🔔🔔[🔔](https://github.com/flslib/fl-studio-cracked)

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
