### ISSUE TITLE
Unable to install plugins

### ISSUE THREAD

**Issue by OElesin** [elastic/elasticsearch#10126]
I want to install some river plugins on my elasticsearch instance but because I installed elasticsearch via deb, I cannot locate the bin directory. Please how do I go about this?

**Comment by JLVeiga** [comment]
If you’ve installed the .deb package, then the plugin exectuable will be available at /usr/share/elasticsearch/bin/plugin

**Comment by OElesin** [comment]
Found it.Thanks
