### ISSUE TITLE
Dead Master Resulted In Red Cluster Health

### ISSUE THREAD

**Issue by kadaan** [elastic/elasticsearch#10122]
The master node on our cluster died, which resulted in a cluster with red health.  All shards were unassigned and had to be recovered.  The failure of the master node should not result in a dead cluster.

**Comment by bleskes** [comment]
Indeed it shouldn’t. Can you give some more information? Typically a new master should be elected and take over the role of the old master…

**Comment by kadaan** [comment]
Basically I had a nose which would not join the cluster.  It was not able to communicate with the current master and the master could not communicate with the node. After numerous attempts to repair it I decided to shutdown the master to see if moving the master to another node would help. I shut it down via kopf (which uses the shutdown api I believe). Right after this kopf went dead and then the cluster was red with all shards unassigned. i will get the logs from all modes to see what happened.

**Comment by clintongormley** [comment]
@kadaan any more info?  Also, did you only have one master eligible node?  What is your cluster config?

**Comment by kadaan** [comment]
Unfortunately I don't have any more info.  All nodes are master eligible, so there should have been 11 others able to step in.  I have not seen this since, so I would be fine to close it.
