### ISSUE TITLE
_ttl problem

### ISSUE THREAD

**Issue by onthefloorr** [elastic/elasticsearch#10138]
Dear Elasticsearch,

We use the elasticsearch's _ttl feature which is not clear to us. The next is written in the latest documentation : 

Expired documents will be automatically deleted regularly. You can dynamically set the indices.ttl.interval to fit your needs. The default value is 60s . 
The deletion orders are processed by bulk. You can set indices.ttl.bulk_size to fit your needs. The default value is 10000.  

--------------

Knowing this, we modified the indices.ttl.interval to 30s and indices.ttl.bulk_size to 3. After, we sent some  (2000) logs into our index with _ttl : 1m . 
After a while, we noticed that more logs have been deleted as expected. So all logs were deleted within 30s after one minute elapsed but there only 3 logs should have been deleted.
Is this normal ? We thought that only 3 logs will be deleted. How is the deletion of logs implemented on the elasticsearch ? Could you give me more information on the deletion of logs ?

**Comment by javanna** [comment]
Hi @onthefloorr I think this would get a better answer if you ask it on the mailing list. If it then turns out to be a bug or a feature request you can then move it here to github. Closing for now.
