### ISSUE TITLE
[EQL] Support `sequence` with reverse ordering

### ISSUE THREAD

**Issue by BenB196** [elastic/elasticsearch#101320]
### Background

While looking at some performance issues for a detection rule: https://github.com/elastic/detection-rules/issues/3226, I found that it would have been useful for EQL `sequence` to support the ability to search for sequences in a reverse order.

### Use Case

There are instances where the first "event" in a sequence might be extremely noisy, but the later "events" in the sequence are sparse. Because of this EQL needs to spend a good amount of effort processing these noisy events to then not do anything with them. Ideally, it would be nice if you could provide the later (less noisy) "events" first, to act as a sort of early circuit breaker, then have EQL go "backwards" (reverse) and not only potentially skip out on wasteful processing, but also have EQL deal with much smaller scopes here.

**Comment by wchaparro** [comment]
Superceded by ES|QL
