### ISSUE TITLE
[DOCS] Add an info that the ignore_throttled parameter was deprecated in version 7.16

### ISSUE THREAD

**Issue by bunste** [elastic/elasticsearch#101348]
As I have already described [here](https://discuss.elastic.co/t/deprecation-info-missing-in-the-docs/345744/1) in the forum, I recently encountered the following deprecation warning:

    [ignore_throttled] parameter is deprecated because frozen indices have been deprecated. Consider cold or frozen tiers in place of frozen indices.

According to the [release notes](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/release-notes-7.16.0.html) this change was introduced in version 7.16.

However, a corresponding deprecation info is still missing in some places in the 8.10 (which is _current_ at the time of this writing) documentation, for example for the [Search API](https://www.elastic.co/guide/en/elasticsearch/reference/8.10/search-search.html).

The search function finds all relevant documentation pages relatively quickly.

**Comment by abdonpijpelink** [comment]
Thank you for reporting this @bunste ! This has been fixed in https://github.com/elastic/elasticsearch/pull/101838
