### ISSUE TITLE
Downsample time zone usability issue

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#101309]
The fact that downsampling rolls data up using UTC as fixed timezone is a known limitation: 
https://www.elastic.co/guide/en/elasticsearch/reference/8.10/downsampling.html#querying-downsampled-indices-notes

However when querying a tsdb data stream this can still come as a surprise. As long as downsampling hasn't been execute or configured or querying only the non downsampled part of a data stream (recent data isn't usually downsampled), the `date_histogram` aggregation works fine with any configured time zone. However when a search with a `date_histogram` does hit a shard that contains downsampled data, then the search fails with the following error: `Field [@timestamp] of type [date] is not supported for aggregation [timeseries] with timezone [America/Los_Angeles]`. This can be confusing as the user may not know that the data stream that is being queried has been configured to downsample at some point in time. And this failure is unlikely to happens when recent data is queried. Kibana adds timezone parameter automatically to the `date_histogram` aggregation, so often this outside of the control of the user (especially with builtin dashboards).

There are various options we can explore in order to mitigate this usability issue. This issue serves as a placeholder. Note that this isn't a `date_histogram` aggregation issue only. This is an issue that will need to be addressed in es-ql too.

**Comment by lalit-satapathy** [comment]
Hi Team,

Do we have a plan for when this will be addressed? This is key gating item to be able to use the downsampling data.
