### ISSUE TITLE
rename UNICODE_CHAR_CLASS to UNICODE_CHARACTER_CLASS in regex flags

### ISSUE THREAD

**Issue by rpedela** [elastic/elasticsearch#10146]
The documentation states that one should use the Java Pattern API flags for ES regex. However I received an error when I used ```UNICODE_CHARACTER_CLASS```. Looking at the source, ```UNICODE_CHAR_CLASS``` is used instead. Can this be renamed to match the Java Pattern API?

See #2895 for the source code.

**Comment by clintongormley** [comment]
... or at least adding a synonym

**Comment by srogljan** [comment]
What about this? :-)
https://github.com/elastic/elasticsearch/pull/11598
