### ISSUE TITLE
Update documentation to warn about potential issues with conflicting field definitions

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#10149]
http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#all-mapping-types

>Field names with the same name across types are highly recommended to have the same type and same mapping characteristics (analysis settings for example). There is an effort to allow to explicitly "choose" which field to use by using type prefix (my_type.my_field), but it’s not complete, and there are places where it will never work (like faceting on the field). n In practice though, this restriction is almost never an issue. The field name usually ends up being a good indication to its "typeness" (e.g. "first_name" will always be a string). Note also, that this does not apply to the cross index case.

Based on comments in https://github.com/elastic/elasticsearch/issues/8870 and the known issues around not having validation today on same field name across multiple types in an index, it sounds like it is more appropriate to have a more forceful warning vs. a recommendation - until alternatives are available for #8870.

**Comment by rjernst** [comment]
With #8870 complete, the documentation has been updated to reflect that field types must match for the same field across document types. I don't think there is anything more to do here. Please reopen if you feel the documentation is still missing something.
