### ISSUE TITLE
Springboot integration Elasticsearch @Filed fails

### ISSUE THREAD

**Issue by wuwei0727** [elastic/elasticsearch#101415]
The springboot version is 2.3.12.RELEASE, the Elasticsearch client uses 7.6.2, and the corresponding spring data Elasticsearch is 4.0.9
![image](https://github.com/elastic/elasticsearch/assets/100761249/6545f51f-affa-4c4d-854a-c56703540f49)

Now when using the officially provided ElasticsearchRepository interface to save data, there is an ESInfraredOriginal class. This class has the @Document (indexName = "infrared-original") annotation, and each attribute has the @Field annotation.
![image](https://github.com/elastic/elasticsearch/assets/100761249/e8de6873-6db5-4e52-9237-e95e013fbabf)

My interface inherits the official ElasticsearchRepository：
![image](https://github.com/elastic/elasticsearch/assets/100761249/d7815b5c-3bc1-4055-b9bf-58a2c20eeb33)

I used the controller to test and the index was created, but why is the type different? My annotation @field specifies type, why does it not take effect? Why are the types of Elasticsearch different?
![image](https://github.com/elastic/elasticsearch/assets/100761249/ce74d987-76e1-44c9-a95e-33c0768fb29c)

**GET /infrared-original1/_mapping：**
![image](https://github.com/elastic/elasticsearch/assets/100761249/89dac8dd-b94e-4a73-be08-990a26b968d1)

**Comment by JVerwolf** [comment]
Hi @wuwei0727, the spring ES integration project is maintained by the community and located here: https://github.com/spring-projects/spring-data-elasticsearch

This might be a better place to ask your question.
