### ISSUE TITLE
ESQL: Too large response payload (on sparse indices)

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#101490]
### Description

`from logs-* | limit 10000`
can trigger

```
Unable to retrieve search results
[esql] > Unexpected error from Elasticsearch: The content length (536885793) is bigger than the 
maximum allowed string (536870888)
```

**Comment by nik9000** [comment]
I've opened a docs change.

I wonder if we should add some kind of truncation somehow, at least when talking to kibana. And, to be honest, paging would be nice here too....
