### ISSUE TITLE
Removing duplicates from merged aggregation results

### ISSUE THREAD

**Issue by SMUnlimited** [elastic/elasticsearch#10142]
**Scenario 1**
This is a very simplified scenario but captures the problem we are facing.

We have a team lead document with a field for “Primary Product” and a field for “Secondary Product”.  We want to show the distribution of all products amongst team leads. To do so we would do a term aggregation on “Primary Product” and a term aggregation on “Secondary Product”. 

As this is the same products we want to merge the buckets together (done manually). This is simple to do with the term aggregation but has a problem. If both fields have the product, the document count will be one more than it should be once you merge the buckets. We need a way to realise if a document is already included in the count of the first aggregation, so we don’t add the same document from the second aggregation.

**Scenario 2**
This next scenario is similar to our actual use case where we make use of nested documents but it is the same problem as above.

Each team lead is a top level document nested with team members. We then want to show the distribution of teams that contain males or females, assuming a single team leader exists per team. 

Again we would run two aggregations. For team leaders this would be a term aggregation on gender. For team members this would be a nested term aggregation on gender followed by a reverse nested aggregation to get team leader counts for each gender. The two aggregation result buckets would then have to be manually combined. But it’s the same problem of working out when a team lead was already included in the first aggregation so any duplicate team leads that match in the second aggregation can be ignored.  (The aggregation we would use can be seen here https://gist.github.com/SMUnlimited/86e03e8f59ac6a09935c)

Another solution could be to include the team lead himself as a nested team member so we can just do a single nested term aggregation followed by a reverse nested aggregation to get the team member counts.  But this means you are duplicating all the team lead data which is not ideal.

:boom: What do people think would be the best way to solve this problem?

*Note we haven’t thought about other types of aggregations yet (some may not be as straightforward to merge buckets) but in theory could also be applied.*

**Comment by SMUnlimited** [comment]
A crazy solution that just might work. Set no parent fields! The parent fields are themselves only available in a nested document. And all nested documents are only in a single nested path. Then when we do an aggregation we can get the merged results of the parents and children without any duplication of parent doc counts or data. 

If at some point we are only interested in the parent or children on our aggregation, we set a field on nested documents that says whether it is the parent fields or not. Then do a (term?) aggregation to split the nested documents into 2 buckets of parent nested docs and children nested docs, followed by the actual aggregation we want to do. 

The upcoming inner hits feature can be used when we are after displaying the parent fields to a user.

Only disadvantage is this doesn't solve the problem for multiple levels of nesting.

**Comment by clintongormley** [comment]
Hi @SMUnlimited 

Any chance you could upload some actual REST examples?  It's easier reading code than descriptions :)

**Comment by SMUnlimited** [comment]
@clintongormley There is an example in the gist:

https://gist.github.com/SMUnlimited/86e03e8f59ac6a09935c

**Comment by clintongormley** [comment]
@SMUnlimited I think you need to solve these problems at index time.  For instance, if you want to count identical primary and secondary products as 1, then you should merge these products into a single field, eg using `copy_to`:

    PUT myindex
    {
      "mappings": {
        "lead": {
          "properties": {
            "primary_product": {
              "type": "string",
              "index": "not_analyzed",
              "copy_to": "all_products"
            },
            "secondary_product": {
              "type": "string",
              "index": "not_analyzed",
              "copy_to": "all_products"
            },
            "all_products": {
              "type": "string",
              "index": "not_analyzed"
            }
          }
        }
      }
    }
    
    PUT myindex/lead/1
    {
      "name": "John",
      "primary_product": "Foo",
      "secondary_product": "Bar"
    }
    
    PUT myindex/lead/2
    {
      "name": "Mary",
      "primary_product": "Foo",
      "secondary_product": "Foo"
    }
    
    GET /myindex/lead/_search
    {
      "size": 0,
      "aggs": {
        "products": {
          "terms": {
            "field": "all_products"
          }
        }
      }
    }

This returns:

      "products": {
         "doc_count_error_upper_bound": 0,
         "sum_other_doc_count": 0,
         "buckets": [
            {
               "key": "Foo",
               "doc_count": 2
            },
            {
               "key": "Bar",
               "doc_count": 1
            }
         ]
      }
