### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test {p0=synonyms/30_synonyms_delete/Delete synonym set - index uses the synonym set, so it can't be deleted} failing

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#101587]
**Build scan:**
https://gradle-enterprise.elastic.co/s/474p4e3kherrk/tests/:qa:mixed-cluster:v7.17.15%23mixedClusterTest/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=synonyms%2F30_synonyms_delete%2FDelete%20synonym%20set%20-%20index%20uses%20the%20synonym%20set,%20so%20it%20can't%20be%20deleted%7D
**Reproduction line:**
```
./gradlew ':qa:mixed-cluster:v7.17.15#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=synonyms/30_synonyms_delete/Delete synonym set - index uses the synonym set, so it can't be deleted}" -Dtests.seed=FBBB717E95061895 -Dtests.bwc=true -Dtests.jvm.argline="-Des.concurrent_search=true" -Dtests.locale=ar-OM -Dtests.timezone=America/Barbados -Druntime.java=21
```

**Applicable branches:**
8.11

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT&tests.test=test%20%7Bp0%3Dsynonyms/30_synonyms_delete/Delete%20synonym%20set%20-%20index%20uses%20the%20synonym%20set,%20so%20it%20can't%20be%20deleted%7D

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([FBBB717E95061895]:0)

```

**Comment by cbuescher** [comment]
Quick initial diagnosis: [jstack shows](https://gradle-enterprise.elastic.co/s/474p4e3kherrk/tests/task/:qa:mixed-cluster:v7.17.15%23mixedClusterTest/details/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=synonyms%2F30_synonyms_delete%2FDelete%20synonym%20set%20-%20index%20uses%20the%20synonym%20set,%20so%20it%20can't%20be%20deleted%7D/1/output) that something is preventing the "wipeCluster" step to finish:

**Comment by cbuescher** [comment]
I'll put this on "medium" risk for now since I believe this is probably something due to an unfortunate timing issue in our tests.

**Comment by benwtrent** [comment]
@cbuescher I think we should close this in favor of: https://github.com/elastic/elasticsearch/issues/69973

Looking at the test runtimes, It only ran for 0.5 second before failing due to suite timeout. This isn't something search can do anything about.

2023-10-31T01:28:16,817 before test
2023-10-31T01:28:17,399 after test
