### ISSUE TITLE
Describe types as "partition by" instead of tables

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#10153]
We often describe types as "like a database table" (eg http://www.elastic.co/guide/en/elasticsearch/reference/master/glossary.html#glossary-type), when really they are closer to "PARTITION BY" in Oracle.  We should update this description, especially in the light of #8870

**Comment by ppf2** [comment]
+1 and linking a related one:  https://github.com/elastic/elasticsearch/issues/10149

http://www.elastic.co/guide/en/elasticsearch/reference/master/mapping.html also has a brief note on mapping type is like a database table.  It does describe it as not a complete isolation, but perhaps we can remove the reference to database table.

**Comment by jpountz** [comment]
+1 I think this is the right way to describe types.

**Comment by nik9000** [comment]
> +1 I think this is the right way to describe types.

Its certainly a ton better than tables. +1

**Comment by kingIZZZY** [comment]
As a newb on day 3 with ES, I can attest that the guide's analogy from RDBMS structures (index>type>doc>field is like database>table>row>column) versus what i gathered after learning the *truth* about indexes and types (after some IRC chatting) &mdash; the true picture is ***completely*** different, and using that RDBMS analogy was unhelpful in understanding the right idea of how ES works and how to plan/design indexes.

**Comment by clintongormley** [comment]
I've rewritten the section on types.
