### ISSUE TITLE
What should we do with groovy sandboxing?

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#10156]
Our groovy engine supports sandboxing, which can be enabled/disabled through settings. Sandboxing was disabled by default from `1.4.3` on though since we found out that it could be worked around (see also https://www.elastic.co/blog/running-groovy-scripts-without-dynamic-scripting).

At this point I wonder if it makes sense to maintain the sandboxing that we currently have, as we know it's not effective. I would vote for just stating that groovy is not sandboxed and remove all the sandboxing shenanigans from master (2.0), unless we have a better idea for safe sandboxing... especially once we got #10116 in.

Thoughts?

**Comment by dakrone** [comment]
hmm.. good question, I wonder though whether someone with an extremely narrow use-case for scripts could still use the sandbox by only whitelisting exactly what methods they need?

Other than that, if it's not useful I'm +1 on removing it, we can always re-add it later if needed.

**Comment by nik9000** [comment]
+1 on removing it

**Comment by clintongormley** [comment]
+1 on removing it
