### ISSUE TITLE
[DOCS] ILM documentation uses a generic "time series" concept

### ISSUE THREAD

**Issue by andreidan** [elastic/elasticsearch#101532]
### Description

The ILM documentation uses the "time series" concept to refer
to any data which ages with time and has a lifecycle definition
that can be expressed relative to its ageing characteristics.

e.g.
- https://www.elastic.co/guide/en/elasticsearch/reference/current/overview-index-lifecycle-management.html 
- https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-index-lifecycle-management.html#manage-time-series-data-without-data-streams
- https://www.elastic.co/guide/en/elasticsearch/reference/8.10/use-elasticsearch-for-time-series-data.html

However, the "time series" term can be confusing as it's overloaded 
(recently) by the addition of the time series data stream https://www.elastic.co/guide/en/elasticsearch/reference/8.10/tsds.html.
Time series indices also refer to indices that belong to a TSDS 
(and we also have a specific page for their settings https://www.elastic.co/guide/en/elasticsearch/reference/8.10/tsds-index-settings.html )
Additionally, the times series data stream has a separate page that discusses
automating TSDS with ILM https://www.elastic.co/guide/en/elasticsearch/reference/8.10/downsampling-ilm.html

This proposes we potentially find a different concept in the 
ILM doc, moving away from "time series" to something else, 
or perhaps clarifying up front the difference between the generic
time series concept that ILM uses and the more concrete time series
data stream.

**Comment by abdonpijpelink** [comment]
There was a related discussion on this topic a while ago. Linking it here for awareness: https://github.com/elastic/elasticsearch/pull/87897

**Comment by shainaraskas** [comment]
according to https://github.com/elastic/elasticsearch/pull/87897, this is an industry term so we probably want to focus on multiple definitions
