### ISSUE TITLE
cutoff_frequency in match query does not work as expected

### ISSUE THREAD

**Issue by truongduy134** [elastic/elasticsearch#10154]
I use cutoff_frequency in match query to exclude stopwords. However, the cutoff_frequency does not seem to behave as mentioned in Elasticsearch documentation.

Steps to reproduce the problems: (I used Elasticsearch Sense plugin)
1) Index the following 2 documents with standard analyzer:
POST /me/test
{ "text": "the test" }
and 
POST /me/test
{ "text": "the building" }

2) Query:
GET /me/test
{
   "query": { "match": { "text": { "query" : "the car", "cutoff_frequency" : 0.001 } } }
}

I would expect the query returns 0 result ("the" is treated as a high-frequency word and should be excluded). However, both indexed documents are returned.

I am not sure if I misuse cutoff_frequency in this case...

**Comment by clintongormley** [comment]
HI @truongduy134 

By default, your index has 5 primary shards, so each of your two documents is sitting on a shard by itself.

See http://www.elastic.co/guide/en/elasticsearch/guide/current/relevance-is-broken.html

If you create your index as follows, then your example works as expected:

    PUT me
    {
      "settings": {
        "number_of_shards": 1
      }
    }

**Comment by truongduy134** [comment]
@clintongormley  : Thanks a lot for the explanation :+1:
