### ISSUE TITLE
Tribe/Query node doesn't work in pure IPv6 environment

### ISSUE THREAD

**Issue by cheramilm** [elastic/elasticsearch#10152]
In pure IPv6 environment, we configure query node and send query request to query node, and found it  doesn't work and requests finally send to 127.0.0.1, we run the request:
http://masternode:9200/_nodes/is_query:true/settings?pretty

would return some result like:

    {
      "cluster_name": "ElasticsearchCluster",
      "nodes": {
        "-eddeG7aRtOowARRz-QJRA": {
          "name": "ES-QueryNode1/ElasticsearchCluster",
          "transport_address": "inet[/fd3e:842e:1c9d:10:0:0:0:1fe%0:9301]",
          "host": "Query",
          "ip": "127.0.0.1",
          "version": "1.3.2",
          "build": "dee175d",
          "attributes": {
            "client": "true",
            "is_query": "true",
            "data": "false",
            "is_index": "false"
          },
          "settings": {
            "node": {
              "client": "true",
              "is_query": "true",
              "is_index": "false",
              "name": "ES-QueryNode1/ElasticsearchCluster"
            },
            "bootstrap": {
              "mlockall": "true"
            },
            "http": {
              "enabled": "false",
              "netty": {
                "maxInitialLineLength": "65536"
              }
            },
            "tribe": {
              "name": "ElasticsearchCluster"
            },
            "name": "ES-QueryNode1/ElasticsearchCluster",
            "path": {
              "data": "\\xxxx\\data",
              "work": "\\xxxx\\elasticsearch-1.3.2",
              "home": "\\xxxx\\elasticsearch-1.3.2",
              "conf": "\\xxxx\\elasticsearch-1.3.2\\config",
              "logs": "\\xxxxelasticsearch-1.3.2/logs"
            },
            "config": "\\xxxx\\elasticsearch-1.3.2\\config\\elasticsearch.yml",
            "cluster": {
              "name": "ElasticsearchCluster"
            },
            "discovery": {
              "zen": {
                "ping": {
                  "unicast": {
                    "hosts": "masternode:9300"
                  }
                }
              }
            }
          }
        }
      }
    }

Please notice the line "ip" : "127.0.0.1",

If we setup such ES cluster in IPv4 environment, and run same request:

    {
      "cluster_name": "ElasticsearchCluster",
      "nodes": {
        "3lmWVMs1T_upCWAFHOxS-w": {
          "name": "ES-QueryNode1/ElasticsearchCluster",
          "transport_address": "inet[/192.168.1.66:9302]",
          "host": "Instance2",
          "ip": "192.168.1.66",
          "version": "1.3.2",
          "build": "dee175d",
          "attributes": {
            "client": "true",
            "is_query": "true",
            "data": "false",
            "master": "false"
          },
          "settings": {
            "path": {
              "logs": "C:/elasticsearch-1.3.2 Tribe/logs",
              "home": "C:\\elasticsearch-1.3.2 Tribe"
            },
            "cluster": {
              "name": "ElasticsearchCluster"
            },
            "node": {
              "data": "false",
              "client": "true",
              "is_query": "true",
              "master": "false",
              "name": "ES-QueryNode1/ElasticsearchCluster"
            },
            "http": {
              "enabled": "false"
            },
            "discovery": {
              "zen": {
                "ping": {
                  "unicast": {
                    "hosts": [
                      "masternode:9300"
                    ]
                  }
                }
              }
            },
            "tribe": {
              "name": "ElasticsearchCluster"
            },
            "name": "ES-QueryNode1/ElasticsearchCluster"
          }
        }
      }
    }

We can get correct IP: 
"ip" : "192.168.1.66",

**Comment by clintongormley** [comment]
Hi @cheramilm 

It is not clear to me how you have configured your cluster, and whether it has even formed a cluster.  Could you provide more details please?

**Comment by clintongormley** [comment]
No more info provided. Closing, Feel free to reopen with more info
