### ISSUE TITLE
Index is partially created if it refers to a missing synonyms set

### ISSUE THREAD

**Issue by Mikep86** [elastic/elasticsearch#101693]
### Elasticsearch Version

8.12.0

### Java Version

_bundled_

### OS Version

Cloud

### Problem Description

An index is partially created and in an inoperable state if it refers to a missing synonyms set at creation time. The only way to recover is to delete the broken index and re-create it after creating the synonyms set.

### Steps to Reproduce

1. Create an index that uses a synonym filter that refers to a missing synonyms set:

```
PUT /test_index
{
  "settings": {
    "analysis": {
        "analyzer": {
            "my_custom_index_analyzer": {
                "tokenizer": "standard",
                "filter": [
                    "lowercase"
                ]
            },
            "my_custom_search_analyzer": {
                "tokenizer": "standard",
                "filter": [
                    "lowercase",
                    "my_synonym_filter"
                ]
            }
        },
        "filter": {
            "my_synonym_filter": {
                "type": "synonym_graph",
                "synonyms_set": "my-synonyms-set",
                "updateable": true
            }
        }
    }
  },
  "mappings": {
    "properties": {
        "title": {
            "type": "text",
            "analyzer": "my_custom_index_analyzer",
            "search_analyzer": "my_custom_search_analyzer"
        },
        "summary": {
            "type": "text",
            "analyzer": "my_custom_index_analyzer",
            "search_analyzer": "my_custom_search_analyzer"
        }
    }
  }
}
```

Elasticsearch will return a `200` response after 30 seconds:

```
{
  "acknowledged": true,
  "shards_acknowledged": false,
  "index": "test_index"
}
```

2. Try to query the index:

```
GET /test_index/_search
{
  "query": {
    "match_all": {}
  }
}
```

Elasticsearch will respond with a `503` error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "no_shard_available_action_exception",
        "reason": null
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "test_index",
        "node": null,
        "reason": {
          "type": "no_shard_available_action_exception",
          "reason": null
        }
      }
    ]
  },
  "status": 503
}
```

3. Create the missing synonyms set:

```
PUT _synonyms/my-synonyms-set
{
  "synonyms_set": [
    {
        "id": "synonym-1",
        "synonyms": "js, javascript, java script"
    }
  ]
}
```

4. Try to query the index again by repeating step 2. You will get the same `503` response.

**Comment by benwtrent** [comment]
@Mikep86 if you call `POST /test_index/_close` then create the synonym set and reopen the index `POST /test_index/_open`, does it then work?

Trying to figure out if the only option is deleting the index and starting over.

**Comment by Mikep86** [comment]
@benwtrent 

> if you call POST /test_index/_close then create the synonym set and reopen the index POST /test_index/_open, does it then work?

Yes, this works!

**Comment by benwtrent** [comment]
OK, we have two work arounds! I am glad closing and opening again works!

**Comment by carlosdelest** [comment]
This has been addressed in https://github.com/elastic/elasticsearch/issues/125603
