### ISSUE TITLE
Enhance Query API key information API

### ISSUE THREAD

**Issue by SiddharthMantri** [elastic/elasticsearch#101691]
#### Summary: 

Enhance [Query API key information API](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-query-api-key.html) to support API key management page use cases

#### Description: 

To improve user experience Customers with a large number of API keys are unable to use the API key management page today as there is a lack of pagination support in the GET endpoint. To enable such users to use this feature, we (Kibana security team) are moving away from the Get API key information API to the Query API. We require some changes to the Query API key API to support enhanced searching and term aggregation. 

- **Search Capabilities**
    -  Description: Extend the current search capabilities of the API endpoint to accept new query fields.
    - Requirement: Add a new query field called `type` to the [existing ones](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-query-api-key.html#security-api-query-api-key-request-body)
    - Possible values: `cross_cluster`, `rest`. The filter will only call one or the other and never both at the same time

- **Term Aggregation:**
    - Description: When loading a subset of API keys, the endpoint should provide all associated usernames, types and if the keys are active/expired,  irrespective of the number of keys loaded.
    - Use Case: For instance, a user visits a UI page and loads 10 API keys. These 10 keys are a subset of a total of 20 keys, each created by a different user. The UI's Owner dropdown should display all 20 usernames, even if only 10 are loaded. Similarly, having that information for active/expired keys and types of keys would be needed as well.
    - Note: The term aggregation should honor the privileges `manage_api_key` and `manage_own_api_key` for the results. For those users who have the `manage_own_api_key` privileges, the results should not include the keys that do not belong to them. 

**UI**

<img width="653" alt="image" src="https://github.com/elastic/elasticsearch/assets/1442420/15907d7b-fda0-4bb8-a1b2-b0c5cda83468">

This is the existing UI which loads all the API keys and then displays them using an in-memory table. 

We intend to move away from this in-memory table. To support a 1:1 mapping between the old and new features, we would also require some enhancements to the API to support use cases of the search bar

Free text search
If a user searches with the term `exp`, the table currently displays results as follows

<img width="618" alt="image" src="https://github.com/elastic/elasticsearch/assets/1442420/07843908-f062-4ded-9507-8cf7abe0c5dc">

This also works similarly if the user searches by API key “type” as ‘personal/cross_cluster` or any other criteria on that page.

<img width="635" alt="image" src="https://github.com/elastic/elasticsearch/assets/1442420/4a68ad04-cb84-42b7-b808-cc38cd9e75e5">
 

To keep the user experience similar across this change, a free text query capability like this one would be a very welcome addition to the Query API key information API. 

We’d like to inspect the following fields for free text search: 
- Username
- Type
- Name
- Id

**Comment by albertzaharovits** [comment]
@SiddharthMantri 
1) I think we can expose allowing searching on the API Key type (`rest` or `cross_cluster`) without any problems.
2) Wrt to the "Free text search" I think ES should expose the multi-match query type https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html (it does not today), and Kibana should call that to search on both the `username` and `name` fields (given the user typed-in text)
3) Wrt to aggregations, regular ES searches actually specify an `aggs` param to `_search` requests https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html. Currently, the Query API key doesn't allow for it though. There are 2 options: we either allow aggs similarly to the `_search` endpoint (I don't _think_ we need to do any validation, but I'll check for it), or we offer some hard-coded specific (term) aggregations, e.g. for `username`, `type` and `expiry` ones, that can be toggled via a simple boolean/enum parameter to the Query API Key API.

I'm going to raise this with the broader team tomorrow, but I would like to first check with you if the above sounds that it's sufficient to achieve the UI features you've described.

**Comment by n1v0lg** [comment]
@albertzaharovits re:

> I think we can expose allowing searching on the API Key type (rest or cross_cluster) without any problems.

It's a little more complicated than it looks, though nothing insurmountable. What complicates this is for API keys created before we introduced the `type` field, the field is (logically) undefined; these API keys and are implicitly `rest` keys. This means that you can't simply query for `rest` and get all `rest` keys; you need to query for s.th. like `(rest OR undefined)` -- or we come up with an alternative approach for special handling of `type`. ES-5990 (no link since it's a private Jira issue) gives more context. We mainly didn't prioritize working on this because there was no clear need for it. Now that we have an ask though, we can revisit 👍

**Comment by SiddharthMantri** [comment]
@albertzaharovits 

Wrt point 3, If i understand correctly, we could query the API as 

```
{
  "aggs": {
    "agg-api-keys": {
      "terms": {
        "field": "username"
      }
    }
  }
}
```
And then add multiple aggs for each of the fields so that we get the "hits" for each of these fields? 

Overall, from reading the docs, this looks like a good solution to how we're expecting the UI to function.

**Comment by albertzaharovits** [comment]
> Wrt to aggregations, regular ES searches actually specify an aggs param to _search requests https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html. Currently, the Query API key doesn't allow for it though. There are 2 options: we either allow aggs similarly to the _search endpoint (I don't think we need to do any validation, but I'll check for it), or we offer some hard-coded specific (term) aggregations, e.g. for username, type and expiry ones, that can be toggled via a simple boolean/enum parameter to the Query API Key API.

We discussed this in yesterday team's meeting. We're OK to provide the `aggs` parameter to the Query API Key API (`_security/_query/api_key`) in an identical fashion to how it's used for the regular `_search` endpoint, possibly limiting the types of aggs.

**Comment by albertzaharovits** [comment]
@kc13greiner I'm starting to work on this now.

**Comment by albertzaharovits** [comment]
@kc13greiner @SiddharthMantri I've raised a draft PR that should address all the requirements in the [description](https://github.com/elastic/elasticsearch/issues/101691#issue-1972967048).
I would appreciate if you could give it a try while it goes through reviews and testing, in order to ensure that it really meets the requirements. Thanks!

**Comment by albertzaharovits** [comment]
This has been resolved by implementing:
 * support for querying by [key type (`rest` or `cross_cluster`)](https://github.com/elastic/elasticsearch/pull/103695)
 * support for [aggregations (some types only)](https://github.com/elastic/elasticsearch/pull/104895)
 * support for the multi-field [simple query string query type](https://github.com/elastic/elasticsearch/pull/104132)

**Comment by albertzaharovits** [comment]
As well as support for the [`match` query type.](https://github.com/elastic/elasticsearch/pull/104594)
