### ISSUE TITLE
index creation date when restoring data to a new index from it's snapshot

### ISSUE THREAD

**Issue by vineet-negi009** [elastic/elasticsearch#101649]
### Description

I have a index named "elastic-27-10-2023" which was created on 27th of October 2023, and checked it's index creation date using "GET _cat/indices/elastic-27-10-2023?h=creation.date.string,i"
i have taken a snapshot of this index.
due to ilm policy, this index gets deleted after two days.
Now, on 30th, i have restored this index from it's snapshot.
now, when i check the index creation date using "GET _cat/indices/elastic-27-10-2023?h=creation.date.string,i" , it's showing 2023-10-27Txxxxxxx as the index creation date.

but index is created now on 30th from the snapshot, so index creation date should be 2023-10-30Txxxxxxx instead of 2023-10-27Txxxxxxx

Is this expected ?, if yes, why ?

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
