### ISSUE TITLE
Reject metric names longer than 63 characters

### ISSUE THREAD

**Issue by stu-elastic** [elastic/elasticsearch#101679]
Opentelemetry 1.30+ supports names 255 characters or less, but we'll need to wait until the next apm-java-agent release to upgrade.  For now, we should reject > 63 character names in the registry to avoid runtime failures that are hard to track down.

Refs: https://github.com/elastic/apm-agent-java/issues/3400

**Comment by pgomulka** [comment]
this was implemented by #101680 
at the same time we upgraded to latest apm agent that allows for 255 chars https://github.com/elastic/elasticsearch/pull/102691
