### ISSUE TITLE
[GEO] Deprecate 'validate_*' options in GeoPointMapping

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#10170]
No need to carry 3 validate options in GeoPointFieldMapping. This is just causing confusion so next version of ES will deprecate the validate_lat, validate_lon option and simply use validate.  The following version will remove validate_{lat|lon} altogether.

**Comment by martijnvg** [comment]
Bumping the version up to 1.7.1 for the today's release.

**Comment by MaineC** [comment]
+1 on merging validate_lat/lon and normalize_lat/lon into one version each.

As this will break backwards compatibility anyway - what do you think about the proposal from @clintongormley here: https://github.com/elastic/elasticsearch/pull/10248#issuecomment-110442561 ?

**Comment by nknize** [comment]
re: coerce, I really like it from a mapping consistency stand point. Perhaps we use it to eliminate ```normalize``` and set the default to ```false```.  Keep ```validate``` but default to ```true``` which I think maximizes use-case flexibility?  Default behavior is the expectation that ES will receive valid lat/lon positions and throw an exception when it doesn't. This forces a user to explicitly update the mapping as an indication that they really want ES to do the normalization (and/or silence the exception) instead of the application.  /cc @clintongormley

**Comment by clintongormley** [comment]
> re: coerce, I really like it from a mapping consistency stand point. Perhaps we use it to eliminate normalize and set the default to false

++

> Keep validate and default to true which I think maximizes use-case flexibility? Default behavior is the expectation that ES will receive valid lat/lon positions and throw an exception when it doesn't. 

On other fields we validate by default, and turn off validation with `ignore_malformed: true` - why not use this instead of `validate`?

**Comment by nknize** [comment]
> On other fields we validate by default, and turn off validation with ignore_malformed: true - why not use this instead of validate?

++ wonderful!!  I'll make this change to the existing PR for 1.7.1 and completely remove validate/normalize_* in master.
