### ISSUE TITLE
ESQL: unexpected count(*) query planning slowdown at scale

### ISSUE THREAD

**Issue by luigidellaquila** [elastic/elasticsearch#101763]
A simple query like 

```
FROM logs-* 
| STATS count=count(*) 
| SORT count DESC 
| LIMIT 0
```

takes a few milliseconds to execute on a small cluster (< 10 nodes), but on bigger clusters (20 - 70 nodes) it takes hundreds of milliseconds (recorded execution time up to 600ms on a 70 node cluster).

The query is optimized as follows:

```
Limit[10000[INTEGER]]                                                             ! LocalRelation[[count{r}#284],EMPTY]
\_Limit[0[INTEGER]]                                                               ! 
  \_OrderBy[[Order[count{r}#284,DESC,FIRST]]]                                     ! 
    \_Aggregate[[],[COUNT(*[KEYWORD]) AS count]]                                  ! 
      \_EsRelation[person][@timestamp{f}#286, boolean{f}#287, !dense_vector, !..] ! 

```
That seems correct. 

Probably most of the cost is on the planning itself (maybe `_field_caps`?)

Interestingly, adding groupings to the STATS makes things better, eg. a query like

```
FROM logs-* 
| STATS count=count(*) BY agent.version 
| SORT count DESC 
| LIMIT 20
```

is more efficient, and adding one more grouping

```
FROM logs-* 
| STATS count=count(*) BY agent.version, agent.type 
| SORT count DESC 
| LIMIT 20
```

makes it even more efficient.

**Comment by dnhatn** [comment]
Yes, the difference lies in the requested fields within the field-caps of these requests. The IndexResolver would request all fields for the query `FROM logs-* | STATS count=count() | SORT count DESC | LIMIT 0`, whereas it would only request ['agent.version', 'agent.version'] for the query `FROM logs-* | STATS count=count(*) BY agent.version | SORT count DESC | LIMIT 20`.

**Comment by astefan** [comment]
The challenge here is to recognize a local relation (aka `limit 0` query) and not create a `*` `_field_caps` call unnecessarily.
Note, though, a `limit 0` query can still need the `*` `_field_caps` call only to be able to return a list of columns with no rows of course. This is not the case for `FROM logs-* | STATS count=count(*) | SORT count DESC | LIMIT 0` (which only needs columns from `stats`) but it is for `FROM logs* | limit 0`.
