### ISSUE TITLE
build docs to PDF and post

### ISSUE THREAD

**Issue by kevinkluge** [elastic/elasticsearch#10176]
I've heard a few requests for a PDF version of the docs.  The prototype generated content was pretty good, but was missing branding.  This issue is to track building these docs regularly and adding some amount of branding (e.g. a header or footer).

**Comment by scharfmn** [comment]
From a user: please do make this happen. It would really help.

**Comment by clintongormley** [comment]
We're working on it.

**Comment by scharfmn** [comment]
That's great. Thank you for the info. In the meantime, if someone could post an answer to [this question](http://stackoverflow.com/q/31003832/1599229) (I'm trying to self-generate) it would be a big help, and probably not just to me.

**Comment by clintongormley** [comment]
This issue was moved to elastic/docs#61
