### ISSUE TITLE
这个参数有什么用

### ISSUE THREAD

**Issue by akkw** [elastic/elasticsearch#101861]
https://github.com/elastic/elasticsearch/blob/c773e04761f9709c1c190ab0bebb69a6356ce4b7/server/src/main/java/org/elasticsearch/action/support/replication/ReplicationRequest.java#L47C25-L47C32

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
