### ISSUE TITLE
Add support for proxy scheme in S3 repository client

### ISSUE THREAD

**Issue by bsakmd** [elastic/elasticsearch#101873]
### Description

Please add option to choose proxy scheme (http vs https) in Elasticsearch settings for S3 client for snapshot repository.
Currently when setting snapshot repository for S3 there are only 2 proxy parameters available:
```
s3.client.default.proxy.host:
s3.client.default.proxy.port:
```
But there is no option to select proxy scheme (http or https). Default seems to be https.
A proxy server can listen on http only port but in same time forward traffic to https sites so this should be decoupled from endpoint protocol.
Example proxies with full URL showing difference:

`http_proxy: http://proxy.example.net:3128`
`https_proxy: http://proxy.example.net:3128`

Docs:
https://www.elastic.co/guide/en/elasticsearch/reference/8.10/repository-s3.html#repository-s3-client

Please note that this has been already implemented in case of xpack:
 `xpack.security.authc.realms.oidc.oidc1.http.proxy.scheme: http`.

**Comment by KhushPatibandha** [comment]
hey i would like to work on this, can you tell me where to start?

**Comment by KhushPatibandha** [comment]
[xpack implementation](x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/common/http/Scheme.java) do I have to implement this in the s3 repository?

**Comment by KhushPatibandha** [comment]
[xpack implementation] (https://github.com/elastic/elasticsearch/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/common/http/Scheme.java) do i have to implement this in the s3 repository?

**Comment by iakhiljoy** [comment]
Our goal is to add the below parameter correct?
s3.client.default.proxy.**scheme**: http / s3.client.default.proxy.**scheme:** https

**Comment by iakhiljoy** [comment]
@KhushPatibandha Are you still on it? or Else I would like to take it up.

**Comment by DaveCTurner** [comment]
@iakhiljoy yep that'd be a good name for the new parameter.

**Comment by iakhiljoy** [comment]
I was going through the code and as well as documentation and found that currently we do have an option to set the scheme in s3 repository using the protocol parameter. Are they both referring to the same?
<img width="906" alt="Screenshot 2023-11-20 at 10 37 50 PM" src="https://github.com/elastic/elasticsearch/assets/23418305/77da6ef0-7fad-4c7a-87c1-7bedc988c029">

**Comment by DaveCTurner** [comment]
Hmm, if we were to follow that naming convention then the new setting would be called `s3.client.default.proxy.protocol`. Yet I think that's confusing, "[Proxy Protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt)" refers to a specific protocol that is not related to the choice between HTTP and HTTPS, and there are other protocols specific to proxies too (e.g. [SOCKS](https://en.wikipedia.org/wiki/SOCKS)). I think I'd still prefer `s3.client.default.proxy.scheme` even though it is inconsistent. I'll see whether the rest of the team have strong opposing opinions.

**Comment by DaveCTurner** [comment]
TBC the name of the setting isn't very important, we can change it during review easily enough. Don't wait for a decision on that front before proceeding.

**Comment by iakhiljoy** [comment]
Sure, I will start working on the required changes.

**Comment by heissanjay** [comment]
@DaveCTurner I've opened a pull request for this issue. Could you please have a look when you have some time? Thanks
