### ISSUE TITLE
Inconsistent Text Trimming in `Unified` Highlighter with `number_of_fragments` Set to `0`

### ISSUE THREAD

**Issue by ahoogol** [elastic/elasticsearch#101803]
### Elasticsearch Version

8.10.4

### Java Version

_bundled_

### OS Version

Elastic Cloud - GCP - Iowa (us-central1)

### Problem Description

When using the Elasticsearch `unified` highlighter, I've encountered an inconsistency related to the `number_of_fragments` option. The issue arises when `number_of_fragments` is set to 0, indicating that we want to highlight the entire content of a field. However, the `unified` highlighter unexpectedly trims the text.

The expected highlight for the input text `" a b c d "` with `number_of_fragments` set to `0` should be:

    "highlight" : {
      "text" : [
        " a  b (c) d "
      ]
    }

However, the actual response is:

    "highlight" : {
      "text" : [
        "a  b (c) d"
      ]
    }

### Steps to Reproduce

    PUT test_trim
    {
      "mappings": {
        "properties": {
          "text": {
            "type": "text",
            "analyzer": "whitespace"
          }
        }
      }
    }

    PUT test_trim/_doc/1
    {
      "text": " a  b c d "
    }

    GET test_trim/_search
    {
      "query": {
        "match": {
          "text": "c"
        }
      },
      "highlight": {
        "pre_tags": "(", 
        "post_tags": ")", 
        "fields": {
          "text": {}
        },
        "number_of_fragments": 0, 
        "type": "unified"
      }
    }

**Comment by mayya-sharipova** [comment]
This happens because we [trim](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/lucene/search/uhighlight/CustomPassageFormatter.java#L70) a passage before outputting it.

I guess it makes sense not to do the trimming if `number_of_fragments` is 0.

**Comment by xswapx** [comment]
If no one is working on this can it be assigned to me?

**Comment by yashdamani** [comment]
I'm working on a PR for this, but is `./gradle :run` supposed to take long for a first time setup? It's been going on for ~2 hours now. I know the contributing doc says it will take a while, but just want to confirm if this amount of time is okay too?
I've tried  `./gradle :run` and  `./gradle :run --parallel` so far.
