### ISSUE TITLE
Seeing too many merge threads (Elasticsearch 1.3.4)

### ISSUE THREAD

**Issue by mashudong** [elastic/elasticsearch#10181]
There are 562 merge threads in a hprof dump of our elasticsearch process, we have no merge related configs, the default max number of merge threads seems to be 3 (http://www.elastic.co/guide/en/elasticsearch/reference/1.3/index-modules-merge.html),
then how could I control the number of concurrent merge threads?

![image](https://cloud.githubusercontent.com/assets/3242209/6748485/0f287612-cf21-11e4-93db-e50d854470c9.png)

**Comment by clintongormley** [comment]
@mikemccand any ideas about this?

**Comment by mikemccand** [comment]
Egads, that's way too many running merge threads!  @mashudong can you pull all threads (use /_nodes/hot_threads but pass threads=10000 so we get all of them not just the top 3 hot ones)?

**Comment by saiprasadmishra** [comment]
Hi All

I am seeing a similar issue in our ES version 1.3.2 also. Did you figure out why it has so many lucene merge threads....looks like threads are just started and not getting stopped.

**Comment by saiprasadmishra** [comment]
@mikemccand I am seeing 100s of lucene merge threads apart from 2 [merge] threads even though max_thread count was 1

curl -XPUT 'localhost:9201/index_v1/_settings' -d '
{
  "index": {
    "merge.scheduler.max_thread_count": 1
  }
}'

**Comment by mikemccand** [comment]
@saiprasadmishra can you also post all threads?

**Comment by clintongormley** [comment]
@saiprasadmishra Please could you post the output of this command:

    curl -XGET "http://localhost:9200/_nodes/hot_threads?threads=10000"

**Comment by jpountz** [comment]
Closing due to lack of feedback
