### ISSUE TITLE
SimpleNettyTransportTests#testTracerLog stalls

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#10187]
`SimpleNettyTransportTests#testTracerLog` stalls on my macbook, I saw this a couple of times today while running the whole core suite from command line. The suite timeout kicks in at some point and stops it.

**Comment by javanna** [comment]
Assigning this to @bleskes as he has the logs and said he knows what is going on. Thanks @bleskes !

**Comment by bleskes** [comment]
example: http://build-us-00.elastic.co/job/es_core_15_centos/64/
