### ISSUE TITLE
Benchmark api in master

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#10182]
We currently have the benchmark api in the master branch. We are going to refactor it once #6914 is in, which may take a while. I don't think it will make it into `2.0`.

This issue is just a reminder to back out the current benchmark api code before we release `2.0`, unless ready by then.

**Comment by clintongormley** [comment]
Can we remove the code now and just put it in a separate branch?

**Comment by javanna** [comment]
Sure I can take care of this. WIll create a new branch from master and then remove any reference of it from master. Makes sense?

**Comment by bleskes** [comment]
+1

**Comment by javanna** [comment]
I did some digging, we already have a branch for this, which is ahead of master, where the refactoring of the benchmark api was taking place till it stalled waiting for #6914 : 

https://github.com/elastic/elasticsearch/tree/feature/bench

No need to recreate a new branch then, everything should be there. Will just go ahead and remove the benchmark api from master if nobody objects.
