### ISSUE TITLE
Bulk response can return errors and drops in incorrect order

### ISSUE THREAD

**Issue by sihtam23** [elastic/elasticsearch#101921]
### Elasticsearch Version

8.8.0

### Java Version

_bundled_

### OS Version

Ubuntu 22.04

### Problem Description

When using ingest pipelines with a bulk request to index a handful of documents it is consistently possible to get a response where the positions of items in the bulk response do not match up with the right position in the bulk request. Successful responses match up correctly with their requests but drops and errors can be muddled up. Obviously this is a problem because if I wish to retry failed requests I don't know which request to retry. A workaround is to set the index in the bulk request as the id but this is a little hacky for my liking and I would prefer Elasticsearch to return responses in the same order as the request was issued. I usually pass in no id and let Elasticsearch create one or the pipeline.

Returning requests in the same order should be possible as the "slot" or item id seems to be passed around just fine on the transport side but looking at TransportBulkAction it appears the BulkRequestModifier class is responsible for not caring about the order of drops/errors. The drops/errors get added to the list in whatever order they are received and then the successful response get inserted in their correct "slots" amongst those drops/errors.

The bug that easily exposes this issue best has been fixed in v8.9.0 (see #97354) but fixing that bug doesn't fix this underlying issue as I'll bet there is another way to create it! I assume the problem is because I'm using the inference processor and perhaps inference returns asynchronously and messes with the order. I haven't tried to recreate this error in any other way.

### Steps to Reproduce

Let's assume you've got Elasticsearch running with the elser model loaded already...

```
PUT _ingest/pipeline/drop_fail -d '
{
  "processors": [
    {
      "drop": {
        "if": "ctx.drop != null"
      }
    },
    {
      "fail": {
        "message": "hello world",
        "if": "ctx.fail != null"
      }
    },
    {
      "inference": {
        "model_id": ".elser_model_1",
        "inference_config": {
          "text_expansion": {
            "results_field": "tokens"
          }
        }
      }
    }
  ]
}'
``` 

```
POST _bulk?pipeline=drop_fail -d '
{ "index": { "_index": "myindex", "_id": "1" } }
{ "text_field": " ོ" }
{ "index": { "_index": "myindex", "_id": "2" } }
{ "drop": "" }
{ "index": { "_index": "myindex", "_id": "3" } }
{ "fail": "" }
'
``` 

I get the items back in the order: 2, 3, 1 from this request

**Comment by joegallo** [comment]
@sihtam23 I see it now! I've gotten this to reproduce locally -- I see what you mean about how #97354 fixes the bug that provokes the bad behavior, but that the bad behavior is still latent.

It looks to me like this happens if an asynchronous ingest processor throws an exception, so the bug would be provoked if there's an exception from the `enrich` or `inference` processors.

**Comment by joegallo** [comment]
Oh, and **thank you** for reporting this!.
