### ISSUE TITLE
Accessing other documents in top hit aggregation

### ISSUE THREAD

**Issue by usfhussam** [elastic/elasticsearch#10197]
I wonder whether it is possible to access another document in top hit aggregations.
For example, I am adding a script_field to the top hits and I want to compute the value of this field based on the next document. So If I want to compute this field for the first hit, I need to access a certain field in the second hit. Is it possible to do so?

**Comment by clintongormley** [comment]
Hi @usfhussam 

No, this wouldn't be possible.  This sounds like some post-processing phases that should be done on the client side.
