### ISSUE TITLE
Add ability to retrieve on-disk templates

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#10193]
Templates that go into `{config}/templates` are usable, however they do not show up in the templates API (`GET 0:9200/_templates`).

It would be great if there were a way to retrieve the templates via the REST API.

Follow-up to #10160

**Comment by clintongormley** [comment]
Disk based templates are no longer supported.  Closing

**Comment by drekbour** [comment]
@clintongormley "Disk based templates are no longer supported" I cannot find where it mentioned this in the release notes? What is the recommended replacement?

https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-2.0.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-2.1.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html

**Comment by ogirardot** [comment]
and if I may, why ??
It's a key feature to be able to "provision" an Elasticsearch cluster in a programatically *easy* way.

**Comment by alexjhart** [comment]
I agree this was a useful feature.

**Comment by TigranTsat** [comment]
Was a useful feature...

**Comment by clintongormley** [comment]
@drekbour it is mentioned here: 
https://www.elastic.co/guide/en/elasticsearch/reference/2.1/breaking_20_index_api_changes.html#_file_based_index_templates

It was removed here (https://github.com/elastic/elasticsearch/pull/10870) and disk based mappings was removed here (https://github.com/elastic/elasticsearch/pull/10870) 

It was removed as part of a cleanup of all disk based resources (except node-level config and, unfortunately, scripts https://github.com/elastic/elasticsearch/pull/10870#issuecomment-97424660).  Elasticsearch is API driven.  File based resources can differ between nodes, can't be retrieved or checked via the cluster etc.  Instead, templates can be setup across all nodes in the cluster by a single PUT request.

**Comment by ogirardot** [comment]
I understand, but with provisioning tools like Ansible, that means that we need to wait for the node we're currently adding to be up to PUT the proper templates / mappings / configs ...
