### ISSUE TITLE
ESQL: add DATE_DIFF functionality

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#101942]
### Description

Similar to what [ES SQL](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-functions-datetime.html#sql-functions-datetime-diff) has, we need functionality for datetime related data types difference: `eval duration=@timestamp-timestamp_end` or `eval duration=DATE_DIFF("year", @timestamp, timestamp_end)`.

**Comment by costin** [comment]
We should also wire this in the planner to allow overloading of + / - operators without having to modify Add/Sub classes.
That is convert DATE - DATE or DATE + INTERVAL to DATE_DIFF(DATE, DATE) or DATE_ADD(DATE, INTERVAL).

**Comment by NicolasGras** [comment]
Hello @astefan and @costin, can I try to work on it please?
In my laptop I have created a new class `DateDiff.java` in **esql** plugin, and I can use a DATE_DIFF function to make requests with ESQL.
![image](https://github.com/elastic/elasticsearch/assets/8484741/5b933d91-1f6d-431d-b8b6-0f0ef2909998)

Let me know if it is ok for you.
Thanks :)
