### ISSUE TITLE
使用helm离线部署elasticsearch 提示geoip更新失败

### ISSUE THREAD

**Issue by TheWindIsRising** [elastic/elasticsearch#102055]
### Elasticsearch Version

7.15.0

### Java Version

1.8

### OS Version

Linux nacns-0001.novalocal 5.4.258-1.el7.elrepo.x86_64 #1 SMP Tue Oct 10 22:42:49 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

当我使用k8s部署elasticsearch7.15.0集群时，data节点出现错误{"type": "server", "timestamp": "2023-11-10T09:25:27,350Z", "level": "ERROR", "component": "o.e.i.g.GeoIpDownloader", "cluster.name": "elasticsearch", "node.name": "elasticsearch-data-0", "message": "error updating geoip database [GeoLite2-Country.mmdb]", "cluster.uuid": "ER0bW8OvRdatyKmbn1ksIA", "node.id": "8uwQTkI5TiOgSocO2H9ocg" ,
![image](https://github.com/elastic/elasticsearch/assets/124865830/1e8f1398-5b3f-4cc2-b2fa-a2c47c6ef559)
我怎么能够关闭更新？
![image](https://github.com/elastic/elasticsearch/assets/124865830/7aa78767-466a-402c-b56a-1eda549da6ed)

### Steps to Reproduce

使用k8s部署elasticsearch7.15.0

### Logs (if relevant)

![image](https://github.com/elastic/elasticsearch/assets/124865830/195b0fe2-447b-43fb-b584-e853e0b411fd)

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
