### ISSUE TITLE
[DOCS] Missing figure in the Ingest pipelines in Search documentation page

### ISSUE THREAD

**Issue by consulthys** [elastic/elasticsearch#102072]
### Elasticsearch Version

8.11

### Java Version

_bundled_

### OS Version

Darwin iMac.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

### Problem Description

When viewing the [Ingest pipeline in search](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest-pipeline-search.html) documentation page, all figures are missing, namely:
* `ingest-pipeline-ent-search-ui.png`

The figure are available in the [raw ASCIIDOC page](https://github.com/elastic/elasticsearch/blob/8.11/docs/reference/ingest/search-ingest-pipelines.asciidoc), but not in the [generated documentation](https://github.com/elastic/built-docs/blob/master/html/en/elasticsearch/reference/8.11/ingest-pipeline-search.html), and hence, not on the (https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest-pipeline-search.html)[public documentation website].

### Steps to Reproduce

1. Go to https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest-pipeline-search.html
2. Notice the broken image link for `ingest pipeline ent search ui`

**Comment by leemthompo** [comment]
Thanks @abdonpijpelink, I'll take care of this!
