### ISSUE TITLE
failed to write to elasticsearch from hadoop hive

### ISSUE THREAD

**Issue by sdba2** [elastic/elasticsearch#10207]
I've a table in hive and I want to write it's data to elastic index.

i created an index in elastic : 
curl -XPOST localhost:9200/aaa -d '{
"mappings" : {
"aaa_type" : {
"properties" : {
"f1" : {"type" : "string"},
"f2" : {"type" : "string"}
}
}
}
},

I've downloaded the elasticsearch-hadoop-2.0.2 and in hive i did :

1) add jar elasticsearch-hadoop-2.0.2.jar ;
2) create external table tbl1(f1 string, f2 string) stored by 'org.elasticsearch.hadoop.hive.EsStorageHandler' tblproperties('es.resource'='aaa/aaa_type' , 'es.index.auto.create'='true','es.nodes'='server1') ;
3) insert overwrite table tbl1 select f1,f2 from source_table;

command number 3 get the error :
Error during job, obtaining debugging information...
FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask

Then i've downloaded a new beta version elasticsearch-hadoop-2.1.0.Beta3 and instead of the above step 1 i've used : 
add jar elasticsearch-hadoop-2.1.0.BUILD-SNAPSHOT.jar;

but the error was the same!

what am i missing ?

**Comment by javanna** [comment]
Hi @sdba2 I think this type of questions would be better answered in our mailing list. We generally use github issues for actual bugs of feature requests. Thanks!
