### ISSUE TITLE
Unneeded warning log emitted for tsdb data stream that have imported backing indices.

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#102088]
When using the modify data stream api to import a backing index to a tsdb data stream then it always gets added as first backing index. Even if the correct `index.time_series.start_time` and `index.time_series.end_time` index settings are set. 

This confuses the get data stream. It expects that the backing indices are in order of the time slice it represents. In case the get data stream api returns warnings. In this case the warning is not a sign of something being incorrect. 

Either the logic of get data stream api should be updated to not log a warning message in the case the indices are out of order. Or the modify data stream api should insert the backing index into the right slot.

**Comment by lkts** [comment]
See also #106890.
