### ISSUE TITLE
rest-api-spec in its own repository?

### ISSUE THREAD

**Issue by timschlechter** [elastic/elasticsearch#10201]
I would like to add [rest-api-spec](https://github.com/elastic/elasticsearch/tree/master/rest-api-spec) as a submodule to my project. At the moment, it's located in the main elasticsearch repository, which forces me to add the whole elasticsearch-repo as a submodule.

Would it be possible to move the rest-api-spec folder to its own repository and add it as a submodule to the elasticsearch repository?

**Comment by javanna** [comment]
Hi @timschlechter , the `rest-api-spec` dir used to be a separate project a while ago, and every language client would use it as a submodule exactly as you describe. We decided though to move it to the `elasticsearch` repo for a few reasons, if memory serves. First of all we wanted to make sure that the REST spec and tests stayed up-to-date with the actual elasticsearch code and the `elasticsearch` repo felt like a more natural location for it. Also, REST spec and tests evolve in the different `elasticsearch` repo branches, and we found ourselves needing to have exactly the same branches on the separate repo that we had. Last but not least, I think we weren't too happy with git submodules and some of their limitations and things are working better without for us.

I don't think we want to go back at this point, I hope that is not a blocker for you. If you do wish do checkout only that directory out of the elasticsearch repo, there should be a couple of ways to do it with git though.

**Comment by timschlechter** [comment]
Keeping submodules in sync whith the main repo is indeed a painfull excersize, and one might ask why use submodules when main repo and submodule evolve at the same pace. So I totally understand the choices you made.

It's not a blocker for me, it just makes it a bit more convinient for other projects which want to use the spec files directly. But as said it's not a blocker for me, and I can't imagin it would be a blocker for anyone.

Thanks for the info, I'll close this one.
