### ISSUE TITLE
failed to put mapping on indices

### ISSUE THREAD

**Issue by sdba2** [elastic/elasticsearch#10208]
i have several big (200-300 gb) indices using one mapping.
when trying to delete one of them it took 1-2 minute/s
at that time new inserts keep getting : 
failed to put mapping on indices [[index_name]], type [type_name] 

how can i avoid those errors ?
is there a timeout parameter for the mapping ?

**Comment by clintongormley** [comment]
HI @sdba2 

You deleted the index? or a mapping?  Deleting an index should be quick, but deleting a mapping could take a long time.  In fact, in master we've removed the ability to delete mappings.

If you deleted the index, then I'm surprised it took that long, but perhaps you have slow disks.

**Comment by clintongormley** [comment]
No more info. Closing. Feel free to reopen with more detilas
