### ISSUE TITLE
[DOC] Define logger options

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#10211]
This came up [via the community](https://groups.google.com/d/msgid/elasticsearch/0ec824b1-e98f-404a-afcf-b78390bae81e%40googlegroups.com).

Basically we need to expand our docs around what different log options are available for each aspect of Elasticsearch; indexing, cluster, discovery etc etc.

**Comment by dakrone** [comment]
Closing this as logging now uses the stock log4j2.properties file, which is documented by the log4j2 project.
