### ISSUE TITLE
Better template handling

### ISSUE THREAD

**Issue by KlavsKlavsen** [elastic/elasticsearch#10219]
Currently elasticsearch handles a faulty index template in it's templates folder, by reverting to built in default :(

Recommendation is to "push" the template to ES.. but the problem with that recommendation, is that I no longer have a documented change process.. when I control all servers in version controlled setup - and roll out config, using puppet - I have complete documentation of all changes in production.

Thats why I want to use the template files method.. also - that means we can change the templates - without giving access to elasticsearch (it may contain sensitive information).

I'd simply like to use the index templates defined in file "feature" - and have it be a bit less dangerous (ie. handle errors better) to use.

My suggestion would be to actually parse templates every hour - to check if they look ok - so I have an entire day to react to parse errors.. and the other suggestion, is to save the "last valid/used" template in memory atleast (or in yesterdays index) - so it can use "last known good version" - instead of throwing everything out, because I made a mistake when updating the template.

**Comment by clintongormley** [comment]
Support for file based index templates have been removed in #11052, in favour of using the API.
