### ISSUE TITLE
Don't allow indices containing too-old segments to be opened

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#10215]
Elasticsearch 2.x (Lucene 5.x) will support all Lucene 4.x segments, but not Lucene 3.x segments. We should not allow any indices with too-old segments to be opened on cluster restart.  These indices should be left in a closed state, and the reason for not opening should be logged.

If the user tries to open the index with the index-open API, they should receive an exception explaining the reason.

We will advise users of 1.x to install the migration advisory plugin #10214 before upgrading to check the age of their segments.  The upgrade path in this case will be to install Elasticsearch 1.6 and to run the upgrade API.

If users ignore this advice and go straight to 2.x, then they will be unable to open these indices.  At this point, the upgrade path will be to move these indices to a new directory, install 1.6, and use the upgrade API.  Once upgraded, they can install 2.0 and rely on the dangling indices function.

**Comment by skearns64** [comment]
We'll have to be sure to handle the case where some of the shards of a given index have 3.x segments, while other shards contain only 4.x segments. This means we should try to find a way to take/keep the whole index offline, or ensure that the manual process index upgrade process works in this case.
