### ISSUE TITLE
[GEO] add "ignore" option to geo_shape orientation param

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#10227]
Spawned from #9511 discussion, there is an interest in providing an option for "orientation" indifference on ```geo_shape``` types.  That is, the "old" way of computing coordinate orientation for polygons (which is not compliant with OGC standards and will fail on ambiguous polygon).  Requested by the community, this option would be in the form of: ```orientation: ignore``` to provide backwards compatibility with projects that handle their own coordinate orientation logic (or already provide shapes in a manner than skirts orientation issues prior to ES 1.4.3).

Note that if a user opts to ignore orientation and an ambiguous polygon is provided, InvalidShapeExceptions will occur - this is the price the user is willing to pay.

**Comment by nknize** [comment]
/cc @colings86 @clintongormley @rjernst @tschaub

Note: In addition to permitting "invalid" polygons, this option (aside from being 'opt in') goes against the "prevent users from 'hurting' themselves" philosophy.  Its low hanging fruit but I open this issue for quick feedback before bringing it in.

**Comment by rjernst** [comment]
Is there a real need for this, or is it laziness? Are there any performance benefits to the "old" way if you don't have holes? Is it just saving the user from having to sort their points and supply them in a deterministic order when the poly is "simple"?

**Comment by tschaub** [comment]
Thanks for your willingness to work on this @nknize.  @rjernst - you're right to assume this can mostly be explained away as laziness - see https://trac.osgeo.org/gdal/ticket/2310.  We're serializing geometries as GeoJSON without first checking or enforcing any winding order.  This was working with Elasticsearch < 1.4.3.  Now it doesn't work for polygons that have interior rings and also span > 180 degrees longitude.  I'll confirm this now, but it struck me initially that the heuristic about dateline crossing was only being applied when determining if an interior ring was within an exterior ring, and *not* when performing an intersects query.  I'll do some more testing to determine where it looks like the right hand rule is being assumed.

I think what we'll do for now is update things to always create geometries following the right-hand rule.  And then we'll decide what to do with geometries we accept from clients (before sending to Elasticsearch).

So, thanks again for considering the `orientation: ignore` property.  I'll update the clients that we control and the other places we construct geometries to always use the right-hand rule.  We've added text to the proposed GeoJSON IETF draft encouraging people to do the same (see geojson/draft-geojson#43), so maybe things will get better over time.

**Comment by clintongormley** [comment]
@nknize Is this still relevant or can it be closed?

**Comment by nknize** [comment]
Closing this issue. As discussed in #12325 we need to require OGC/ISO compliance. There are already separate tools that fix bad (non-compliant) data and adding this option/leniency just invites trouble in the long run.
