### ISSUE TITLE
ESQL: More memory accounting improvements

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#102267]
Extends https://github.com/elastic/elasticsearch/issues/99173
- [ ] block referencing
- [ ] Filter blocks
- [ ] Expand blocks
- [ ] enrich memory accounting
- [ ] Remove Block.Ref
- [ ] Remove nonBreakingBlockFactory
- [ ] Remove deprecated Block methods

**Comment by alex-spies** [comment]
@dnhatn , I'll happily take the filter+expand blocks as follow-ups to the general refcounting.
As previously discussed, I'd love your help esp. on Block.Ref as that one profits from good knowledge on the implicit ownership of blocks during evaluation.

**Comment by dnhatn** [comment]
>  I'll happily take the filter+expand blocks as follow-ups to the general refcounting.

++, please go ahead. Thank you, Alex!

**Comment by alex-spies** [comment]
Duplicate of https://github.com/elastic/elasticsearch/issues/100528
