### ISSUE TITLE
debian repository for 1.4 is broken

### ISSUE THREAD

**Issue by gardsted** [elastic/elasticsearch#10223]
It seems the repository is broken - it complains like the following when I do an apt-upgrade after inserting the repo like this:

    wget -qO - https://packages.elasticsearch.org/GPG-KEY-elasticsearch | apt-key add -
    add-apt-repository "deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main"

The error looks like this

    W: Failed to fetch http://packages.elasticsearch.org/elasticsearch/1.4/debian/dists/stable/Release  Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)

**Comment by electrical** [comment]
Hi, using `add-apt-repository` automatically adds a deb-src line for source packages.
But since we don't have those we also don't have the source data.
If you remove that line you can run `apt-get update` without any errors.

**Comment by clintongormley** [comment]
I've added a warning to the docs explaining this.
