### ISSUE TITLE
ESQL: BWC and mixed version testing

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#102270]
Add bwc and mixed version testing.

- [x] Mixed cluster for CSV spec tests (https://github.com/elastic/elasticsearch/pull/102198)
- [x] Mixed cluster for YAML tests (https://github.com/elastic/elasticsearch/pull/102392)

**Comment by dnhatn** [comment]
Added in https://github.com/elastic/elasticsearch/pull/102198.
