### ISSUE TITLE
Search preference based on node attributes

### ISSUE THREAD

**Issue by grantr** [elastic/elasticsearch#10229]
Say I have data nodes in two availability zones. Each node has an attribute with its zone name, and shard allocation awareness is enabled based on that zone name. Every shard has a copy in both zones.

Now I want to minimize search traffic across zones to reduce latency. I'd like to set a search preference that prefers shards in the same zone as the coordinator, since communicating with those shards will be faster.

This would probably look something like `preference=_prefer_availability_zone:_local`. In this case, specifying a zone isn't helpful, because I want the value to be the coordinator's value.

This is a more general approach to https://github.com/elastic/elasticsearch/issues/5925.

**Comment by javanna** [comment]
Hi @grantr, if I'm not mistaken this is exactly what shard allocation awareness already does, beyond making sure that shards are properly distributed across the different zones. Have a look at the docs [here](http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cluster.html#_automatic_preference_when_searching_geting).

**Comment by grantr** [comment]
@javanna thanks! Still learning new things after 5 years :)
