### ISSUE TITLE
add node id to _cat/shards

### ISSUE THREAD

**Issue by lmenezes** [elastic/elasticsearch#10226]
would be nice having node id in here. Even though having nodes with the same name and ip is not a likely scenario, it's still possible.

if this sounds reasonable, I would be more than happy to send a PR.

**Comment by javanna** [comment]
Makes sense to me, what do you think @drewr ?

**Comment by drewr** [comment]
Agree, we should have node name and id on all APIs.

**Comment by lmenezes** [comment]
Will you take care of it, or should I send a PR?

**Comment by drewr** [comment]
@lmenezes Happy to have a PR!
