### ISSUE TITLE
ES 1.5.0 won't start on windows

### ISSUE THREAD

**Issue by wbsimms** [elastic/elasticsearch#10225]
I downloaded ES 1.5 today, unzipped into a new folder and ran the batch file. This is result:

C:\Users\XXXXX\Downloads\elasticsearch-1.5.0\elasticsearch-1.5.0\bin>elasticsearch.bat
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.Version
        at org.elasticsearch.bootstrap.Bootstrap.buildErrorMessage(Bootstrap.java:261)
        at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:248)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)

C:\Users\XXXXXX\Downloads\elasticsearch-1.5.0\elasticsearch-1.5.0\bin>java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

Am I missing something?

**Comment by Mpdreamz** [comment]
The 1.5 release works for me on windows. If you place an `echo` in front of https://github.com/elastic/elasticsearch/blob/master/bin/elasticsearch.bat#L44 what does `bin\elasticsearch` print? It might be that your %JAVA_HOME% or %ES_HOME% is set to something that interferes with the classpaths.

**Comment by wbsimms** [comment]
C:\Users\Wm.Barrett\Downloads\elasticsearch-1.5.0\elasticsearch-1.5.0\bin>elasticsearch.bat
"C:\Program Files\Java\jre1.8.0_31\bin\java"  -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8  -Delasticsearch -Des-foreground=yes -Des.path.home="C:\Users\Wm.Barrett\Downloads\elasticsearch-1.5.0\elasticsearch-1.5.0"  -cp ";C:\Projects\elasticsearch/lib/elasticsearch-1.5.0.jar;C:\Projects\elasticsearch/lib/*;C:\Projects\elasticsearch/lib/sigar/*;C:\Users\Wm.Barrett\Downloads\elasticsearch-1.5.0\elasticsearch-1.5.0/lib/elasticsearch-1.5.0.jar;C:\Users\Wm.Barrett\Downloads\elasticsearch-1.5.0\elasticsearch-1.5.0/lib/*;C:\Users\Wm.Barrett\Downloads\elasticsearch-1.5.0\elasticsearch-1.5.0/lib/sigar/*" "org.elasticsearch.bootstrap.Elasticsearch"

I see what's going on. A failed process had setup environment variables for ES_*.

The easy work around was to start a new shell.
A sanity check would be to remove any existing ES_* environment vars if present. However, I would just chalk this up to a users learning curve.

Thanks!

**Comment by wbsimms** [comment]
Closed. Not a bug.
