### ISSUE TITLE
Java client instance doesn't recover from temporary ES unavailability 

### ISSUE THREAD

**Issue by l15k4** [elastic/elasticsearch#10222]
Hey,

I'm using ES 1.4.2 and it seems to me that if java client cannot temporarily ping node within `client.transport.ping_timeout` then it never manages to ping it again and [this happens](https://gist.github.com/l15k4/f40a115edb67c1fd4779)... Let say that I do a query from a different client (like Sense) that returns big result set, say `search?size=200000` that takes more than `client.transport.ping_timeout` then java client never recovers and a java client request that occurred within the unavailability never gets a response back... 

So my solution to that was increasing `client.transport.ping_timeout`, but the problem with this now is that the transport client never returns response on that original request that occurred within the temporary unavailability...

This means a lot of "resiliency" coding on the java-client side ....

Btw I tried that when `sniffing` was both enabled and disabled.

**Comment by clintongormley** [comment]
Hi @l15k4 

I've labelled this for discussion but as a side note, you should never be asking for 200,000 results in one request.  Instead you should use scrolling to just keep pulling batches of results until you have the requisite number.

**Comment by clintongormley** [comment]
So much has changed since this issue was opened that I'm going to close.  Please reopen if you're still seeing issues with recent versions
