### ISSUE TITLE
7.13.1 编译报错

### ISSUE THREAD

**Issue by tomlikeyou** [elastic/elasticsearch#102366]
### Elasticsearch Version

7.13.1

### Java Version

jdk15.0.2

### OS Version

window10

### Problem Description

下载tag7.13.1zip源码压缩包导入idea，编译报错

`Build file 'D:\Work\work\SourceAnalysis\elasticsearch-7.13.1\build.gradle' line: 29

An exception occurred applying plugin request [id: 'elasticsearch.global-build-info']
> Failed to apply plugin 'elasticsearch.global-build-info'.
   > Installation is not valid. Original error message: A problem occurred starting process 'command 'D:\Work\jdk8\bin\java.exe''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
`
oracle jdk版本：本地jdk版本装过15.0.2，16.0.2版本都报同样错误，另外报错目录下没有任何文件
gradle版本：7.0.1
idea ：2021
os：window10

jdk环境变量如下：
![image](https://github.com/elastic/elasticsearch/assets/49068465/cc6c7c53-778a-426d-8d6c-5390d6684961)
![image](https://github.com/elastic/elasticsearch/assets/49068465/b08bc4a5-9ead-4db6-91bf-ae84fd2af5ab)
![image](https://github.com/elastic/elasticsearch/assets/49068465/794d119e-06eb-4cdd-aa23-bf5a7ab99dc6)
![image](https://github.com/elastic/elasticsearch/assets/49068465/30c5b2b0-5a66-4b20-b0e5-b3ffe042c254)
![image](https://github.com/elastic/elasticsearch/assets/49068465/1af1cbf2-d498-4179-aec4-8673b1a06c4a)

### Steps to Reproduce

如问题描述

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.

Your issue relates to Elasticsearch version 7.13.1 which has passed end-of-life, so I am closing this. If you can reproduce this issue in a supported version then we will reopen it.
