### ISSUE TITLE
Inconsistent Multiple Inputs Filtering in `Unified` Highlighter with `number_of_fragments` Set to `0`

### ISSUE THREAD

**Issue by ahoogol** [elastic/elasticsearch#102342]
### Elasticsearch Version

7.15.0

### Java Version

_bundled_

### OS Version

Windows 10

### Problem Description

When using the Elasticsearch `unified` highlighter, I've encountered an inconsistency related to the `number_of_fragments` option. The issue arises when `number_of_fragments` is set to 0, indicating that we want to highlight the entire content of a field. However, the `unified` highlighter unexpectedly filters the values of text.

The expected highlight for the input text `["a _ _", "_ _ _"]` with `number_of_fragments` set to `0` should be:

    "highlight" : {
      "text" : [
        "(a) _ _",
        "_ _ _"
      ]
    }

However, the actual response is:

    "highlight" : {
      "text" : [
        "(a) _ _"
      ]
    }

### Steps to Reproduce

```
PUT test_frag
{
  "mappings": {
    "properties": {
      "text": {
        "type": "text",
        "analyzer": "whitespace"
      }
    }
  }
}
PUT test_frag/_doc/1
{
  "text": ["a _ _", "_ _ _"]
}
GET test_frag/_search
{
  "query": {
    "term": {
      "text": {
        "value": "a"
      }
    }
  },
  "highlight": {
    "pre_tags": "(", 
    "post_tags": ")", 
    "fields": {"*": {}},
    "number_of_fragments": 0
  }
}
```

**Comment by bcmeireles** [comment]
Hello, I’ve looked into this issue and started working on it. Is it possible for me to claim it and be assigned to it?

**Comment by mayya-sharipova** [comment]
@bcmeireles Thank you for desire to contribute to Elasticsearch. Because you are an external contributor, we can not assign this issue to you. For external contributors, whoever submits a PR first that addresses this issue, will be a person whose code will be merged.

**Comment by mayya-sharipova** [comment]
I think we should close this issue as this is expected.

When you index `["a _ _", "_ _ _"]` you provide two different values for a field, and we highlight each value independently. As the second value did not contain a query term, it is not returned.

**Comment by mayya-sharipova** [comment]
@bcmeireles. There is another [highlighting issue](https://github.com/elastic/elasticsearch/issues/101803) that could be a good as a first time issue. 

 We  can not assign you to an issue, as you are an external contributor. But if your PR is first to address the issue, we will merge it.
