### ISSUE TITLE
How to add documents to existing index

### ISSUE THREAD

**Issue by Anaghasri** [elastic/elasticsearch#10236]
Hi,
Am using Elasticsearch 1.4. My requirement is I will have data every hour and that needs to be uploaded. So the approach that I have taken is to create an index - demo_<date> and upload the data. Now, my question is how to append the subsequent hours data into this index.
Request you to throw light on this.

**Comment by s1monw** [comment]
please use the mailing list for questions like this. The issue tracker is only for bugs / features and development.

thanks
