### ISSUE TITLE
Search results differ between [All Types] and Search Entire Index

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#10233]
I have noticed that my search results differ between 

$ curl -XGET 'http://127.0.0.1:9200/myindex/_search?pretty' -d '{ "query": { "term": {  "datacentre.id": "f96a1379-75bd-40f8-8a82-59931ac3819d" }} }'
$ curl -XGET 'http://127.0.0.1:9200/myindex/rs/_search?pretty' -d '{ "query": { "term": {  "datacentre.id": "f96a1379-75bd-40f8-8a82-59931ac3819d" }} }'

The former returns no hits.  Only the latter returns the following result:

{  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.30685282,
    "hits" : [ {
      "_index" : "myindex",
      "_type" : "rs",
      "_id" : "90fb8dce-6b8a-4b0d-836c-d77293a3dbaa",
      "_score" : 0.30685282,
      "_source":{"label":"My test server","id":"90fb8dce-6b8a-4b0d-836c-d77293a3dbaa","type":"Linux","hostname":"My Linux Server","description":"Test","hosts":[{"id":"c3cde0b6-d488-420c-b32f-e4f1c7c91366","label":"A Sample Web Service"}],"datacentre":[{"id":"f96a1379-75bd-40f8-8a82-59931ac3819d","label":""}]}
    } ]
  }
}

I am working around the problem in elasticsearch.js by searching all my types with:
 client.search({ type: ['rs','ws','x','y'] ... });

**Comment by javanna** [comment]
HI @PhaedrusTheGreek I cant' quite reproduce this. Which version are you on? Could you send a complete curl recreation that shows the problem please?

**Comment by clintongormley** [comment]
Hi @PhaedrusTheGreek 

Do you have a type called `datacentre`? Or do you have more than one type with a `datacentre` field, possibly with different mappings?  This is almost definitely to do with ambiguous field lookups, and should be fixed with the changes in #8070

**Comment by PhaedrusTheGreek** [comment]
Yes, that is the case.  I have more than one type with 'datacentre' field.

**Comment by javanna** [comment]
I think we can close, we are aware of the problem and fixing it with #8870.
