### ISSUE TITLE
Integration test fails after upgrade to 1.5.0

### ISSUE THREAD

**Issue by jaroslawZawila** [elastic/elasticsearch#10238]
I have bunch of integration tests which works fine with elasticsearch  version 1.4.4 and  lucene version 4.10.3. When I upgrade to elasticsearch version 1.5.0 and lucene 4.10.4 tests does not work anymore. 
They are failing with "java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler" exception. 

I am running tests on Centos 6.5 with java 1.7.0_75

**Comment by javanna** [comment]
Hi @jaroslawZawila can you please share some more details about your tests? What do they test exactly and how? Anymore info on the error that you get back (e.g. the whole stacktrace)?

**Comment by jaroslawZawila** [comment]
I have got to bottom of my problem. It is caused by PowerMock not by ElasticSearch.
