### ISSUE TITLE
Debian init script exits with $?=1 when ES already started

### ISSUE THREAD

**Issue by andsens** [elastic/elasticsearch#10237]
Running `/etc/init.d/elasticsearch start` when ES is running gives an error (`$?` is 1).

According to the [LSB guidelines](http://refspecs.linuxbase.org/LSB_3.0.0/LSB-generic/LSB-generic/iniscrptact.html), an init script should exit with 0 when starting an already running service:
> In the case of init script commands other than "status" (i.e., "start", "stop", "restart", "try-restart", "reload", and "force-reload"), the init script shall return an exit status of zero if the action described by the argument has been successful. Otherwise, the exit status shall be non-zero, as defined below.  
In addition to straightforward success, **the following situations are also to be considered successful**:  
* restarting a service (instead of reloading it) with the "force-reload" argument
* **running "start" on a service already running**
* running "stop" on a service already stopped or not running
* running "restart" on a service already stopped or not running
* running "try-restart" on a service already stopped or not running

**Comment by tlrx** [comment]
@andsens thanks for reporting. Yes, we have to make the return codes conform with LSB guidelines. I'm currently working on it ;)

**Comment by clintongormley** [comment]
I believe this has been fixed. Please reopen if that is not the case
