### ISSUE TITLE
Docker manifest is missing architectures

### ISSUE THREAD

**Issue by minddust** [elastic/elasticsearch#102332]
### Elasticsearch Version

7.17.15

### Java Version

_bundled_

### OS Version

Darwin MacBook-Pro.local 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020 arm64

### Problem Description

Pulling 7.17.15 from dockerhub on macos with apple silicon throws 

```
 ⠇ elasticsearch Pulling                                                                                                                                                        1.7s 
no matching manifest for linux/arm64/v8 in the manifest list entries
```

inspecting the manifest shows that some architectures are missing:

```
$ docker manifest inspect elasticsearch:7.17.15
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 2567,
         "digest": "sha256:93e81ebea43a24a9d1007aa9415af8291ec6744ad6d5317b505c53f5907d47b7",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 840,
         "digest": "sha256:cbbd6e4451930d464df2b0fc54ffed7b7cda4e4b1d8152d328742e6719bc1638",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```

### Steps to Reproduce

define docker image with version 7.17.15 and pull

**Comment by mark-vieira** [comment]
Indeed, the arm variant is missing for 8.11.1 as well.

@elastic/release-eng did we get any notification from Dockerhub that there were issues building our ARM images for the most recent releases?

**Comment by mark-vieira** [comment]
@minddust in the meantime you can get the image from the Elastic docker register via `docker pull docker.elastic.co/elasticsearch/elasticsearch:7.17.15`.

**Comment by alpar-t** [comment]
We don't know of any issues, i opened https://github.com/docker-library/official-images/issues/15753 to get some insights

**Comment by mark-vieira** [comment]
This has been resolved with the folks at Dockerhub and both x64 and aarch64 images are available for all recent releases.
