### ISSUE TITLE
Regular expression query string within nested query doesn't work

### ISSUE THREAD

**Issue by photonicworld** [elastic/elasticsearch#10230]
Query-string query within a nested query doesn't seem to work. 

Version tried: 1.5.0

For e.g: Query as below to find authors of all comments can not be searched with a regular expression query string. However regexp query seems to be working fine. 
```
{
   "query": {
      "nested": {
         "path": "comments",
         "query": {
             "query_string": {
                "query": "author:/.*virus/"
             }
         }
      }
   }
}
```

**Comment by javanna** [comment]
Hi @photonicworld could you post a complete recreation of your problem please, including documents and the response that you get back from your query?

**Comment by clintongormley** [comment]
Hi @photonicworld 

It does work, but you need to specify the full path to the nested field, ie `comments.author:`:

    DELETE t
    
    PUT t
    {
      "mappings": {
        "t": {
          "properties": {
            "comments": {
              "type": "nested",
              "properties": {
                "author": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
    
    PUT t/t/1
    {
      "title": "My post",
      "comments": [
        {
          "author": "foo bar"
        }
      ]
    }
    
    GET /t/_search
    {
      "query": {
        "nested": {
          "path": "comments",
          "query": {
            "query_string": {
              "query": "comments.author:/f.*/"
            }
          }
        }
      }
    }
