### ISSUE TITLE
how to access matched_queries from a sort script

### ISSUE THREAD

**Issue by yanchaoguo** [elastic/elasticsearch#102328]
### Description

example:
{
  "_source": ["title"], 
  "sort": {
    "_script":{
      "type":"number",
      "script":{
         
        "source": """
            //  how to get _matched_queries value
        """
      }
    }
  }, 
  "query": {
    "match": {
      "title": {
        "query": "招聘",
        "_name":"T"
      }
    }
  }
}

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
