### ISSUE TITLE
ESQL: Disabling all fields breaks loading metadata fields

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#102393]
### Elasticsearch Version

main

### Java Version

_bundled_

### OS Version

whatever

### Problem Description

```
disabling all fields removes the index from ESQL
```
  - do:
      indices.create:
        index: test
        body:
          mappings:
            dynamic: false

  - do:
      bulk:
        index: test
        refresh: true
        body:
          - { "index" : { "_index" : "test", "_id" : "id-1" } }
          - { "wow": 1, "such": "_source", "you'd": "never", "expect": ["amazing", "source"] }

Now run `FROM tests [METADATA _source]` and it'll complain about some nullpointerexception. It's because it can't find the relation `test` - because it's empty of fields. Indeed - there's only `_source` - no normal fields.
```

### Steps to Reproduce

see above

### Logs (if relevant)

_No response_

**Comment by astefan** [comment]
I've run into this one as part of investigating this one https://github.com/elastic/elasticsearch/issues/101763.
We need a way to recognize an "empty" es relation, something that also mirrors a `field_caps` response that is "empty" of "normal" fields. Empty "normal" fields is, also, the solution to https://github.com/elastic/elasticsearch/issues/101763 aka a very light `field_caps` call.
