### ISSUE TITLE
Dense Vector without dims property causes NullPointerException when calling _cluster/stats

### ISSUE THREAD

**Issue by herrBez** [elastic/elasticsearch#102416]
### Elasticsearch Version

8.11.1

### Java Version

_bundled_

### OS Version

N/A (Elastic Cloud)

### Problem Description

`_cluster/stats` returns a NullPointerException when there is an index with a dense_vector without dims, which is allowed as reported in the [documentation of the dense_vector type](https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html). 
This endpoint is also used by Elastic-Agent/Metricbeat to gather cluster statistics and this bug can cause them not to work.

### Steps to Reproduce

Create a new index with the following mapping:
```
PUT breaking-cluster-stats
{
  "mappings": {
    "properties": {
      "foo": {
        "type": "dense_vector"
      }
    }
  }
}
```

Execute `_cluster/stats`. It will return:

```
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": "Cannot invoke \"java.lang.Integer.intValue()\" because the return value of \"java.util.Map.get(Object)\" is null"
      }
    ],
    "type": "null_pointer_exception",
    "reason": "Cannot invoke \"java.lang.Integer.intValue()\" because the return value of \"java.util.Map.get(Object)\" is null"
  },
  "status": 500
}
```

### Workaround

Create mapping with dims property or index a vector with the number of dimensions needed, e.g.: 
```
PUT breaking-cluster-stats/_doc/1 
{
  "foo": [1,1,1,1,...,1]
}
```

### Logs (if relevant)

Stack Trace:
> java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null at org.elasticsearch.action.admin.cluster.stats.MappingStats.lambda$of$0(MappingStats.java:91) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.admin.cluster.stats.MappingVisitor.visitMapping(MappingVisitor.java:38) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.admin.cluster.stats.MappingVisitor.visitMapping(MappingVisitor.java:39) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.admin.cluster.stats.MappingVisitor.visitMapping(MappingVisitor.java:39) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.admin.cluster.stats.MappingVisitor.visitMapping(MappingVisitor.java:39) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.admin.cluster.stats.MappingVisitor.visitMapping(MappingVisitor.java:39) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.admin.cluster.stats.MappingVisitor.visitMapping(MappingVisitor.java:39) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.admin.cluster.stats.MappingVisitor.visitMapping(MappingVisitor.java:39) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.admin.cluster.stats.MappingVisitor.visitMapping(MappingVisitor.java:19) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.admin.cluster.stats.MappingStats.of(MappingStats.java:73) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.admin.cluster.stats.TransportClusterStatsAction$MetadataStatsCache.lambda$refresh$0(TransportClusterStatsAction.java:293) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:299) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.admin.cluster.stats.TransportClusterStatsAction$MetadataStatsCache.refresh(TransportClusterStatsAction.java:293) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.admin.cluster.stats.TransportClusterStatsAction$MetadataStatsCache.refresh(TransportClusterStatsAction.java:278) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.common.util.CancellableSingleObjectCache$CachedItem.startRefresh(CancellableSingleObjectCache.java:289) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.common.util.CancellableSingleObjectCache.get(CancellableSingleObjectCache.java:167) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.admin.cluster.stats.TransportClusterStatsAction.newResponseAsync(TransportClusterStatsAction.java:132) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.admin.cluster.stats.TransportClusterStatsAction.newResponseAsync(TransportClusterStatsAction.java:58) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.support.nodes.TransportNodesAction$1.lambda$onCompletion$1(TransportNodesAction.java:142) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.support.nodes.TransportNodesAction.lambda$doExecute$0(TransportNodesAction.java:152) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.ActionListenerImplementations$ResponseWrappingActionListener.onResponse(ActionListenerImplementations.java:236) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:50) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983) ~[elasticsearch-8.11.1.jar:?] at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.11.1.jar:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by ChrisHegarty** [comment]
Seems like a regression, and possibly straightforward(ish) solution. I'll can take a look.

**Comment by ChrisHegarty** [comment]
On 8.10.4 it is not possible to create the index with a mapping without specifying the dimensions, e.g.

```
$ curl -XPUT localhost:9200/foo-index -u elastic:password -H 'Content-Type: application/json' -d'
{
  "mappings": {
    "properties": {
      "foo": {
        "type": "dense_vector"
      }
    }
  }
}
 ' | jq .
```

Response:
```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Missing required parameter [dims] for field [foo]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping: Missing required parameter [dims] for field [foo]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "Missing required parameter [dims] for field [foo]"
    }
  },
  "status": 400
}
```

and the server logs:
```
[2023-11-21T16:24:27,549][INFO ][o.e.c.m.MetadataCreateIndexService] [chegars-MacBook-Pro.local] failed on parsing mappings on index creation [foo-index]org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping: Missing required parameter [dims] for field [foo]
at org.elasticsearch.server@8.10.4/org.elasticsearch.index.mapper.MapperService.parseMapping(MapperService.java:400)
at org.elasticsearch.server@8.10.4/org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:376)
at org.elasticsearch.server@8.10.4/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.updateIndexMappingsAndBuildSortOrder(MetadataCreateIndexService.java:1339)
at org.elasticsearch.server@8.10.4/org.elasticsearch.cluster.metadata.MetadataCreateIndexService.lambda$applyCreateIndexWithTemporaryService$2(MetadataCreateIndexService.java:472)
at org.elasticsearch.server@8.10.4/org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:731)
```

**Comment by ChrisHegarty** [comment]
Ok, I misinterpreted the description. We do not expect this to work in 8.11 without specifying the dimensions in the mapping.

**Comment by benwtrent** [comment]
Dims is optional in 8.11. we should handle the places where there aren't null checks.

**Comment by ChrisHegarty** [comment]
Thank you @benwtrent - agree. I misinterpreted the issue, d'oh!   I see that automatic mapping was added as part of #98512.

**Comment by joh4nd** [comment]
> Dims is optional in 8.11. we should handle the places where there aren't null checks.

@benwtrent are you sure?

1. I don't observe automatic mapping of the inserted docs when specifying the following according to [search-tutorial/vector.search](https://www.elastic.co/search-labs/tutorials/search-tutorial/vector-search/store-embeddings):

`, mappings = {'properties': {'embedding': {'type': 'dense_vector'}}}`

2. When manually  including the mapping of the index return by elasticsearch prior to mapping the embeddings, I get an error in the Flask app. 


Mapping
`self.es.indices.create(index = index_name, mappings = {'properties': {'time': {'type': 'text', 'fields': {'keyword': {'type': 'keyword', 'ignore_above': 256}}}, 'text_col': {'type': 'text', 'fields': {'keyword': {'type': 'keyword', 'ignore_above': 256}}}, 'user_col': {'type': 'text', 'fields': {'keyword': {'type': 'keyword', 'ignore_above': 256}}},'embedding': {'type': 'dense_vector'}}})`

Error
`elasticsearch.BadRequestError: BadRequestError(400, 'search_phase_execution_exception', 'failed to create query: Cannot invoke "java.lang.Integer.intValue()" because "this.dims" is null')`

Are you sure "dims" in this case is not null because the mapping specifies no dim for the embedding?

3. entering the index _search endpoint in my browser after the above step 2, no hits are returned.

`timed_out	false
_shards	
total	1
successful	1
skipped	0
failed	0
hits	
total	
value	0
relation	"eq"
max_score	null
hits	[]`

**Comment by benwtrent** [comment]
@joh4nd what version of ES are you using?

I just confirmed in 8.11.4 that the following works fine:

```
DELETE vectors

# automatically set to index, but no dims set
PUT vectors
{
  "mappings": {
    "properties": {
      "vector": {
        "type": "dense_vector"
      }
    }
  }
}

# verify dims is empty
GET vectors

# index first vector, now dims is set to 3
POST vectors/_doc
{
  "vector": [1,2,3]
}

# verify
GET vectors
```

**Comment by joh4nd** [comment]
@benwtrent thanks a lot for the extremely quick response :-)

I am using the 8.11.0 container image. I will try on 8.11.4.

**Comment by joh4nd** [comment]
Thanks again, benwtrent. I am just exploring, and fortunately, having refactored from the ES python client `es.bulk()` to `helpers.bulk()`, there are no more warnings or errors, and all the docs are inserted successfully!
