### ISSUE TITLE
VectorValuesField appears more than once in this document (only one value is allowed per field)

### ISSUE THREAD

**Issue by AlexanderOtt85** [elastic/elasticsearch#102478]
### Elasticsearch Version

8.11.1

### Java Version

_bundled_

### OS Version

docker-image = docker.elastic.co/elasticsearch/elasticsearch:8.11.1

### Problem Description

While trying to index image-vectors into a dense_vector field in a nested structure we still getting the following error

```
"error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "VectorValuesField \"du.medium.keyframe_tc_hit.vector\" appears more than once in this document (only one value is allowed per field)"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "VectorValuesField \"du.medium.keyframe_tc_hit.vector\" appears more than once in this document (only one value is allowed per field)"
  },
  "status": 400
```

### Steps to Reproduce

[elasticsearch_8_11_image_vector.txt](https://github.com/elastic/elasticsearch/files/13440981/elasticsearch_8_11_image_vector.txt)

**Comment by AlexanderOtt85** [comment]
If i change "include_in_parent" in the "keyframe_tc_hit" area to "false" then the problem does not occur. It therefore seems to be related to include_in_parent

**Comment by gbanasiak** [comment]
This makes sense. When `include_in_parent` is set to `true` the field is added to parent as a standard flat field, so multiple of those could occur ([doc](https://www.elastic.co/guide/en/elasticsearch/reference/8.11/nested.html#nested-params)). At the same time dense vectors are always single-valued ([doc](https://www.elastic.co/guide/en/elasticsearch/reference/8.11/dense-vector.html)) so I think this result is expected. I don't think it's a bug but a documented limitation.

**Comment by mayya-sharipova** [comment]
@AlexanderOtt85 Thank you for reporting this issue. I see that this behaviour for vectors is different from  other fields.  And @gbanasiak is right, we need to update our documentation.

What is your use case of `include_in_parent` for vectors? What is your expectation of querying it? Can you disable it?

**Comment by benwtrent** [comment]
We currently do not support more than one vector directly in a field outside of the nested context. Closing this bug.
