### ISSUE TITLE
Docker Secrets with Compose

### ISSUE THREAD

**Issue by bremoi** [elastic/elasticsearch#102430]
### Elasticsearch Version

8.11.0

### Java Version

_bundled_8

### OS Version

Docker

### Problem Description

Hi,

I'm trying to use Docker Secrets using the [official Docker Compose file](https://github.com/elastic/elasticsearch/blob/8.11/docs/reference/setup/install/docker/docker-compose.yml).

I'm able to use secrets with Elasticsearch through the "ELASTIC_PASSWORD_FILE" variable, but I didn't find the equivalent for "ELASTICSEARCH_PASSWORD" Kibana variable.

Have you a solution for this?

Thanks in advance.

Regards

### Steps to Reproduce

N/A

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
