### ISSUE TITLE
TLS error caused by: TlsError(TLS error caused by: SSLError(hostname 'my_ip' doesn't match either of 'FE80:0:0:0:E062:44FF:FEA0:4B20', 'platform',

### ISSUE THREAD

**Issue by ShayDuane** [elastic/elasticsearch#102402]
### Elasticsearch Version

8.11.0

### Java Version

_bundled_

### OS Version

ubuntu

### Problem Description

I'm new to Elasticsearch. I followed the official documentation to install and start a single-node Elasticsearch service. The service automatically enabled security features and generated a CA certificate for me, which is located in the config/cert directory. Then, on my local machine, I was able to successfully connect using:
```
es_client = Elasticsearch("https://127.0.0.1:9200", basic_auth=('elastic', '***********'), verify_certs=True, ca_certs='path/elasticsearch-8.11.0/config/certs/http_ca.crt')
```
However, when I downloaded the http_ca.crt certificate to my Mac and tried to connect using:
```
es_client = Elasticsearch("https://my server ip:9200", basic_auth=('elastic', '******'),verify_certs=True, ca_certs='./http_ca.crt')
```
I encountered an error:
```
TLS error caused by: TlsError(TLS error caused by: SSLError(hostname 'my server ip' doesn't match either of 'FE80:0:0:0:E062:44FF:FEA0:4B20', 'platform', 'FE80:0:0:0:24D1:66FF:FE8F:19', 'localhost', '10.203.0.64', 'FE80:0:0:0:4C14:B9FF:FE56:E593', '10.204.0.64', '10.206.0.65', '0:0:0:0:0:0:0:1', '127.0.0.1', '10.205.0.65', 'FE80:0:0:0:88E2:D8FF:FE39:AFB0', '10.201.202.75', 'FE80:0:0:0:34F7:C1FF:FE05:5531'))
```

What should I do to resolve this?"

### Steps to Reproduce

just like Problem Description

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
