### ISSUE TITLE
[CI] Error evaluating vault in packaging tests

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#102437]
We hit a ton of these errors: https://buildkite.com/elastic/elasticsearch-periodic-packaging/builds/505#018bf3b4-5c16-4fb4-8148-05ca84c0fda9

It's not obvious why this only happens some of the time but perhaps there are some environment variables not being passed properly in the case of packaging tests?

Additionally I noticed this message in these builds which indicates that we seem to be configuring the cache inconsistently?

![image](https://github.com/elastic/elasticsearch/assets/4106672/655a4fc6-9c97-48ab-a4cd-3e369cd40dbd)

**Comment by mark-vieira** [comment]
@breskeby this is most likely fallout from #102180

**Comment by breskeby** [comment]
I've already raised https://github.com/elastic/elasticsearch/pull/102438 as a revert for now. Need to look into this tomorrow. Looking into this more in detail tomorrow

**Comment by mark-vieira** [comment]
We've reverted the build cache connector changes so we can close this.
