### ISSUE TITLE
Partials not working in Mustache template

### ISSUE THREAD

**Issue by zdeseb** [elastic/elasticsearch#10256]
There is feature in Mustache templates called [Partials](http://mustache.github.io/mustache.5.html) which allows to include one template into another.

This could be very useful feature (especially while constructing more complex queries) but it doesn't work correctly in ES [pre-registered templates](http://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html#pre-registered-templates)

**Steps to reproduce:**

1. create file _child.mustache_ file in _config/scripts_ folder with content
`"match_all": {}`

2. wait until ES compiles this file what is indicated by following text in log
`compiling script file [...\config\scripts\child.mustache]`

3. create file _parent.mustache_ file in _config/scripts_ folder with content
```
{
  "query": {
    {{>child}}
  }
}
```

4. When ES tries to compile parent template, following error occurs
```
failed to load/compile script [parent]
org.elasticsearch.common.mustache.MustacheException: Template 'child' not found
```

It looks like ES understands partial syntax but is unable to find existing template.

I'm facing this problem in ES 1.4.4 but [the same problem was in 1.2.2](https://groups.google.com/forum/#!searchin/elasticsearch/mustache/elasticsearch/ihTskQ2RheA/vxTNlOC_Z5wJ) too

**Comment by clintongormley** [comment]
Related to #10047

**Comment by clintongormley** [comment]
No plans to implement partials, given then outcome of #10047
