### ISSUE TITLE
python API es.explain on range query : inconsistent int size constraints

### ISSUE THREAD

**Issue by Alix-Martin** [elastic/elasticsearch#10255]
I'm trying to use explain on a range query through the python API : 

(Pdb) es.explain("test8_ref05", doc_type="document", id="www.orange.fr/", body = """{"query": {"range": {"meta_description_ic": {"gte": 2147483648}}}}""")
{'_index': 'test8_ref05', '_type': 'document', '_id': 'www.orange.fr/', 'explanation': {'value': 1.0, 'details': [{'value': 1.0, 'description': 'boost'}, {'value': 1.0, 'description': 'queryNorm'}], 'description': 'ConstantScore(meta_description_ic:[-2147483648 TO *]), product of:'}, 'matched': True}

My lower bound, 2147483648 (=2^32), does not fit into a java int, and apparently gets cast to -2147483648

This does not happen if I use the ES API directly through Sense : 

GET test/document/www.orange.fr/_explain
  {"query": {"range": {"meta_description_ic": {"gte": 2147483648}}}}

{
   "_index": "test",
   "_type": "document",
   "_id": "www.orange.fr",
   "matched": false,
   "explanation": {
      "value": 0,
      "description": "ConstantScore() doesn't match id 0"
   }
}
which is what I expect, since my document has
"meta_description_ic": 1590728576

**Comment by clintongormley** [comment]
Hi @Alix-Martin 

Please reopen this issue on https://github.com/elastic/elasticsearch-py/issues

thanks
