### ISSUE TITLE
log "listening on interface 0.0.0.0:9200" when the server is ready to accept HTTP reqs

### ISSUE THREAD

**Issue by ORESoftware** [elastic/elasticsearch#102500]
### Description

For devops purposes, we need to know when the server is listening -
better than polling it with http reqs every 5 seconds - better to tail the logs and look for matches.

> MongoDB outputs: waiting for connections ...
> RabbitMQ outputs: started TCP listener on ...

So I would suggest:

> ElasticSearch is ready to accept HTTP requests on host and port: blah

something like that.

**Comment by DaveCTurner** [comment]
Elasticsearch is ready to accept HTTP connections by the time it logs this message:

```
{"@timestamp":"2023-11-23T07:29:34.758Z", "log.level": "INFO", "message":"publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.http.AbstractHttpServerTransport","elasticsearch.cluster.uuid":"WG-6OFXVSaisxUoMlx40cA","elasticsearch.node.id":"Dzfwnce1Q_C7aJxY_jw-0g","elasticsearch.node.name":"node-0","elasticsearch.cluster.name":"elasticsearch"}
```
