### ISSUE TITLE
[KIBANA 4] Unable to use other aggregation than count

### ISSUE THREAD

**Issue by pueffl** [elastic/elasticsearch#10258]
As I got now answer in the forums, I announce this as a possible bug:

I want to create a View which shows an average request time in Kibana (which worked in Kibana 3). I have configured the conversion of the according Integer-String in Logstash as follows:

    mutate {
        convert => ["request_time", "integer"]
    }

In Kibana, I see 'request_time' marked with an exclamation mark in a triangle (no idea what that means exactly, I found no information about this).
The I try to create a Visualization: When I want to do an Y-Axis Aggregation and select 'Average' as the Addregation, I get an empty Field-DDLB where I would expet at least 'request_time' to select as the base to build the calculation.

**Comment by bleskes** [comment]
@pueffl I'm sorry to send you to yet-another-place, but I think your best chance for a good answer is at the Kibana github repo (https://github.com/elastic/kibana ). Do you mind opening the issue there? it is watched but the Kibana devs. 

I'm closing it here for now as it is not an ES issue (as far as I can tell).

**Comment by pueffl** [comment]
No problem, I opened the issue there :-)
