### ISSUE TITLE
`min_score` not working in `function_score` query

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#10253]
The new `min_score` functionality in the `function_score` query doesn't seem to to work as advertised.  For instance:

    DELETE t
    
    PUT t
    {
      "mappings": {
        "t": {
          "properties": {
            "name": {
              "type": "string"
            },
            "foo": {
              "type": "nested",
              "properties": {
                "key": {
                  "type": "string",
                  "index": "not_analyzed"
                },
                "value": {
                  "type": "long"
                }
              }
            }
          }
        }
      }
    }
    
    PUT /t/t/1
    {
      "name": "test",
      "foo": [
        {
          "key": "bar",
          "value": 10
        },
        {
          "key": "bar",
          "value": 20
        },
        {
          "key": "bar",
          "value": 30
        },
        {
          "key": "bar",
          "value": 40
        }
      ]
    }
    
This query returns a score of 4 for the above document, which means that it should be filtered out by the `min_score` of `10`:
    
    GET /_search
    {
      "query": {
        "function_score": {
          "boost_mode": "replace",
          "min_score": 10,
          "query": {
            "nested": {
              "path": "foo",
              "score_mode": "sum",
              "query": {
                "constant_score": {
                  "filter": {
                    "match_all": {}
                  }
                }
              }
            }
          }
        }
      }
    }

**Comment by brwe** [comment]
This is a bug indeed and it seems to me for two reasons: 
1) when the score is 4 the document should not be returned 
2) the score should not be 4 in the first place. `"boost_mode": "replace"` should cause the score to be 1 (default if no functions and no query given).
I'll work on  a fix. For now the workaround would be to define a 

`"weight": 1,` 

if you really want to score all matches with 1 (which does not make much sense imo but should still work) or

```
 "script_score": {
        "script": "_score"
}, 
```
in case one actually wants the score of the query to be used.

**Comment by pickypg** [comment]
To be clear, `min_score` as a child of `function_score` is new in 1.5.0.

`min_score` at the _root_ document level works locally running 1.4.4.

**Comment by brwe** [comment]
Currently the way it works is this: If function_score encounters a query without a function, then the query is just executed as is without wrapping in a function score query (https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/index/query/functionscore/FunctionScoreQueryParser.java#L161) so min_score has no effect in this case. This was implemented so on purpose but it seems to me that now with the min_score there is a usecase where you would want to use function_score without a function. I'll change that.
