### ISSUE TITLE
Inconsistent results 

### ISSUE THREAD

**Issue by andavarlaxman** [elastic/elasticsearch#10252]
Hi Elastic Users,
  We have 6 shards 2 replicas(3 nodes). While am searching in node1 it returns one result, then pass the query to node2 & 3 it returns different order.

I tried preference = _primary & _primary_first It will returns correct order in all the nodes.

But I tried preference = userId(003fdaa6-c5e7-4578-a70e-1c010d358960). This will also returns the first results(Inconsistent results).

Could you please help me how to resolve the issue.

Thanks in advance

**Comment by markwalkom** [comment]
Please use the mailing list for these sorts of problems - https://groups.google.com/forum/#!forum/elasticsearch

Github issues are for problems relating to code issues/bugs.
