### ISSUE TITLE
elasticsearch cluster

### ISSUE THREAD

**Issue by citePerson** [elastic/elasticsearch#102527]
### Elasticsearch Version

8.10.3

### Java Version

_bundled_

### OS Version

 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

{"@timestamp":"2023-11-23T11:19:38.217Z", "log.level":"ERROR", "message":"fatal exception while booting Elasticsearch", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.bootstrap.Elasticsearch","elasticsearch.node.name":"es02","elasticsearch.cluster.name":"docker-cluster","error.type":"org.elasticsearch.ElasticsearchSecurityException","error.message":"failed to load SSL configuration [xpack.security.transport.ssl] - cannot read configured PEM private key [/usr/share/elasticsearch/config/certs/es02/es02.key] because the file does not exist","error.stack_trace":"org.elasticsearch.ElasticsearchSecurityException: failed to load SSL configuration [xpack.security.transport.ssl] - cannot read configured PEM private key [/usr/share/elasticsearch/config/certs/es02/es02.key] because the file does not exist\n\tat org.elasticsearch.xcore@8.10.3/org.elasticsearch.xpack.core.ssl.SSLService.lambda$loadSslConfigurations$11(SSLService.java:618)\n\tat java.base/java.util.HashMap.forEach(HashMap.java:1429)\n\tat java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1707)\n\tat org.elasticsearch.xcore@8.10.3/org.elasticsearch.xpack.core.ssl.SSLService.loadSslConfigurations(SSLService.java:614)\n\tat org.elasticsearch.xcore@8.10.3/org.elasticsearch.xpack.core.ssl.SSLService.<init>(SSLService.java:159)\n\tat org.elasticsearch.xcore@8.10.3/org.elasticsearch.xpack.core.XPackPlugin.createSSLService(XPackPlugin.java:502)\n\tat org.elasticsearch.xcore@8.10.3/org.elasticsearch.xpack.core.XPackPlugin.createComponents(XPackPlugin.java:342)\n\tat org.elasticsearch.server@8.10.3/org.elasticsearch.node.Node.lambda$new$16(Node.java:738)\n\tat org.elasticsearch.server@8.10.3/org.elasticsearch.plugins.PluginsService.lambda$flatMap$1(PluginsService.java:261)\n\tat java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)\n\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)\n\tat java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)\n\tat java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)\n\tat java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)\n\tat java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)\n\tat java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)\n\tat org.elasticsearch.server@8.10.3/org.elasticsearch.node.Node.<init>(Node.java:754)\n\tat org.elasticsearch.server@8.10.3/org.elasticsearch.node.Node.<init>(Node.java:338)\n\tat org.elasticsearch.server@8.10.3/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:234)
org.elasticsearch.server@8.10.3/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:234)\n\tat org.elasticsearch.server@8.10.3/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:72)\nCaused by: org.elasticsearch.common.ssl.SslConfigException: cannot read configured PEM private key [/usr/share/elasticsearch/config/certs/es02/es02.key] because the file does not exist\n\tat org.elasticsearch.sslconfig@8.10.3/org.elasticsearch.common.ssl.SslFileUtil.fileNotFound(SslFileUtil.java:66)\n\tat org.elasticsearch.sslconfig@8.10.3/org.elasticsearch.common.ssl.SslFileUtil.ioException(SslFileUtil.java:37)\n\tat org.elasticsearch.sslconfig@8.10.3/org.elasticsearch.common.ssl.SslFileUtil.ioException(SslFileUtil.java:32)\n\tat org.elasticsearch.sslconfig@8.10.3/org.elasticsearch.common.ssl.PemKeyConfig.getPrivateKey(PemKeyConfig.java:130)\n\tat org.elasticsearch.sslconfig@8.10.3/org.elasticsearch.common.ssl.PemKeyConfig.createKeyManager(PemKeyConfig.java:88)\n\tat org.elasticsearch.xcore@8.10.3/org.elasticsearch.xpack.core.ssl.SSLService.createSslContext(SSLService.java:478)\n\tat java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)\n\tat org.elasticsearch.xcore@8.10.3/org.elasticsearch.xpack.core.ssl.SSLService.lambda$loadSslConfigurations$11(SSLService.java:616)\n\t... 23 more\nCaused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config/certs/es02/es02.key\n\tat java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)\n\tat java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)\n\tat java.base/java.nio.file.Files.newByteChannel(Files.java:379)\n\tat java.base/java.nio.file.Files.newByteChannel(Files.java:431)\n\tat java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)\n\tat java.base/java.nio.file.Files.newInputStream(Files.java:159)\n\tat java.base/java.nio.file.Files.newBufferedReader(Files.java:2897)\n\tat org.elasticsearch.sslconfig@8.10.3/org.elasticsearch.common.ssl.PemUtils.parsePrivateKey(PemUtils.java:130)\n\tat org.elasticsearch.sslconfig@8.10.3/org.elasticsearch.common.ssl.PemKeyConfig.getPrivateKey(PemKeyConfig.java:122)\n\t... 27 more\n"}
ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/docker-cluster.log

### Steps to Reproduce

I used Docker Compose to build a group according to the document, but the second and third nodes encountered the above problem,Please help to see why

### Logs (if relevant)

{"@timestamp":"2023-11-23T11:19:38.217Z", "log.level":"ERROR", "message":"fatal exception while booting Elasticsearch", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.bootstrap.Elasticsearch","elasticsearch.node.name":"es02","elasticsearch.cluster.name":"docker-cluster","error.type":"org.elasticsearch.ElasticsearchSecurityException","error.message":"failed to load SSL configuration [xpack.security.transport.ssl] - cannot read configured PEM private key [/usr/share/elasticsearch/config/certs/es02/es02.key] because the file does not exist","error.stack_trace":"org.elasticsearch.ElasticsearchSecurityException: failed to load SSL configuration [xpack.security.transport.ssl] - cannot read configured PEM private key [/usr/share/elasticsearch/config/certs/es02/es02.key] because the file does not exist\n\tat org.elasticsearch.xcore@8.10.3/org.elasticsearch.xpack.core.ssl.SSLService.lambda$loadSslConfigurations$11(SSLService.java:618)\n\tat java.base/java.util.HashMap.forEach(HashMap.java:1429)\n\tat java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1707)\n\tat org.elasticsearch.xcore@8.10.3/org.elasticsearch.xpack.core.ssl.SSLService.loadSslConfigurations(SSLService.java:614)\n\tat org.elasticsearch.xcore@8.10.3/org.elasticsearch.xpack.core.ssl.SSLService.<init>(SSLService.java:159)\n\tat org.elasticsearch.xcore@8.10.3/org.elasticsearch.xpack.core.XPackPlugin.createSSLService(XPackPlugin.java:502)\n\tat org.elasticsearch.xcore@8.10.3/org.elasticsearch.xpack.core.XPackPlugin.createComponents(XPackPlugin.java:342)\n\tat org.elasticsearch.server@8.10.3/org.elasticsearch.node.Node.lambda$new$16(Node.java:738)\n\tat org.elasticsearch.server@8.10.3/org.elasticsearch.plugins.PluginsService.lambda$flatMap$1(PluginsService.java:261)\n\tat java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)\n\tat java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)\n\tat java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)\n\tat java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)\n\tat java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)\n\tat java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)\n\tat java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)\n\tat java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)\n\tat java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)\n\tat org.elasticsearch.server@8.10.3/org.elasticsearch.node.Node.<init>(Node.java:754)\n\tat org.elasticsearch.server@8.10.3/org.elasticsearch.node.Node.<init>(Node.java:338)\n\tat org.elasticsearch.server@8.10.3/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:234)
org.elasticsearch.server@8.10.3/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:234)\n\tat org.elasticsearch.server@8.10.3/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:72)\nCaused by: org.elasticsearch.common.ssl.SslConfigException: cannot read configured PEM private key [/usr/share/elasticsearch/config/certs/es02/es02.key] because the file does not exist\n\tat org.elasticsearch.sslconfig@8.10.3/org.elasticsearch.common.ssl.SslFileUtil.fileNotFound(SslFileUtil.java:66)\n\tat org.elasticsearch.sslconfig@8.10.3/org.elasticsearch.common.ssl.SslFileUtil.ioException(SslFileUtil.java:37)\n\tat org.elasticsearch.sslconfig@8.10.3/org.elasticsearch.common.ssl.SslFileUtil.ioException(SslFileUtil.java:32)\n\tat org.elasticsearch.sslconfig@8.10.3/org.elasticsearch.common.ssl.PemKeyConfig.getPrivateKey(PemKeyConfig.java:130)\n\tat org.elasticsearch.sslconfig@8.10.3/org.elasticsearch.common.ssl.PemKeyConfig.createKeyManager(PemKeyConfig.java:88)\n\tat org.elasticsearch.xcore@8.10.3/org.elasticsearch.xpack.core.ssl.SSLService.createSslContext(SSLService.java:478)\n\tat java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)\n\tat org.elasticsearch.xcore@8.10.3/org.elasticsearch.xpack.core.ssl.SSLService.lambda$loadSslConfigurations$11(SSLService.java:616)\n\t... 23 more\nCaused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config/certs/es02/es02.key\n\tat java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)\n\tat java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:261)\n\tat java.base/java.nio.file.Files.newByteChannel(Files.java:379)\n\tat java.base/java.nio.file.Files.newByteChannel(Files.java:431)\n\tat java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)\n\tat java.base/java.nio.file.Files.newInputStream(Files.java:159)\n\tat java.base/java.nio.file.Files.newBufferedReader(Files.java:2897)\n\tat org.elasticsearch.sslconfig@8.10.3/org.elasticsearch.common.ssl.PemUtils.parsePrivateKey(PemUtils.java:130)\n\tat org.elasticsearch.sslconfig@8.10.3/org.elasticsearch.common.ssl.PemKeyConfig.getPrivateKey(PemKeyConfig.java:122)\n\t... 27 more\n"}
ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/docker-cluster.log

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
