### ISSUE TITLE
ESQL: Remove OwningChannelActionListener

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#102667]
[This PR](https://github.com/elastic/elasticsearch/pull/102638) introduced `OwningChannelActionListener`, a thin wrapper around `ChannelActionListener` that `decRef`s (i.e. closes) responses when calling `onResponse`.

`OwningChannelActionListener` is deprecated because it is not consistent with other `ActionListeners` - which are normally ref count neutral.

Remove `OwningChannelActionListener`. Probably replace by `ChannelActionListener` and make sure that we close all responses after using them in `ChannelActionListener.onResponse`.

**Comment by dnhatn** [comment]
Fixed in #103537
