### ISSUE TITLE
SQL: investigate separating `SqlVersion` from `Version`

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#102689]
### Description

With the work around decoupling features support from `Version`, we'll need to look into decoupling `SqlVersion` from `Version`. `SqlVersion` is used by ES SQL and its driver clients (JDBC, ODBC) to establish if and how they can communicate to each other.

Some of the complexities we'll need to account for:
* Currently, both the server and the clients (1) embed their release version and (2) apply a version check.
On the client side, a xDBC driver will refuse to work with a pre-7.7.0 server. For this the clients (so, also the released ones) just issue a `/` request.
* On the server side, the check makes sure that the client is (1) post-7.7.0 (the client sends the server its own version) and (2) maximum one major behind. We'll want to keep the decision of allowing the client connection on the server. For instance, there is currently one case where the connection is allowed, but the response is shaped based on client's version (i.e. if the driver understands a - back then - newly introduced type, `unsigned_long`: SQL queries of an "old" client not touching `unsigned_long` fields are ok to run).
* The xDBC clients are released part of the stack and if ES/serverless will have higher frequency release cycles than the stack, we'll need to harmonise the versioning/features_check between them.

This means, we'll still need to support the old version format (in ES SQL) if we decide to gate features based on some other mechanism than `SqlVersion`.

**Comment by bpintea** [comment]
The need for this "features" check stems from the compatibility matrix between clients and server releases: we want this matrix to be as wide as possible, meaning an older client to be able to connect to a newer server: after an upgrade of the server, the clients can lag behind for a while. Making the matrix narrow would mean discomfort / issues for users. The issue with new-server-old-client is that newly added functionality in the server might not be supported by the client. Taking the `unsigned_long` example: a client executes `SELECT * FROM index` (i.e. "give me all the fields in `index`") . If `index` contains an `unsigned_long` field and the server will return it, the (old) client won't know anything about it and will fail to process the response. So keeping the design objective mentioned above - keep connection decision on the server - we'll need a mechanism for the server to understand what "features" the connecting client supports.

**Comment by thecoop** [comment]
Alternatively, could we just separate out SQL version into its own version number, independent of ES release or serverless version? Then just bump the version number when there's a change (similar to MLConfigVersion)
