### ISSUE TITLE
Optimize pattern check for aliases for GetAliases API

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#102676]
When finding aliases for GetAliases API, we step through all indices and for each index we step its aliases to see whether they match the requested patterns.

https://github.com/elastic/elasticsearch/blob/33cbb8ee231564fe464e1829e95a4b1ff839f2c0/server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java#L430-L435

When an aliases is assigned to many indices, the pattern matching can be performed multiple times which is not necessary. If number of patterns are large, the problem can be even worse because the pattern matching has a 3rd loop through the patterns for each alias.

https://github.com/elastic/elasticsearch/blob/33cbb8ee231564fe464e1829e95a4b1ff839f2c0/server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java#L436-L440

We should look into ways to avoid the unnecessary pattern matchings.

**Comment by bcully** [comment]
Original code modified for https://github.com/elastic/elasticsearch/pull/104145
