### ISSUE TITLE
Remove existing _es090* files since Bloom filters are now deprecated?

### ISSUE THREAD

**Issue by SjonHortensius** [elastic/elasticsearch#10261]
After upgrading to 1.5.0 which includes #8571 I was hoping I could free up some diskspace from our nodes. Is there a way to remove the *_es090 files (since they are unused) now that the functionality is deprecated or do I need to wait for the entire functionality to be removed as well?

**Comment by mikemccand** [comment]
You cannot [easily] remove these files from existing shards, however natural merging over time will remove them since the newly merged segment will not write any bloom filters.

**Comment by SjonHortensius** [comment]
Okay so the only way to get rid of them would be to ex&import existing data to a new index on e/s 1.5 which will then not write the bloom filters. The es090*  consumes roughly 40% of our disk-space so this might actually be an interesting option for us

**Comment by mikemccand** [comment]
Hang on: it's only the .blm files that will go away, and this almost certainly should not be 40% of your index...

**Comment by SjonHortensius** [comment]
Ah, you're right; that is actually less then 1%. So maybe this isn't as interesting as I thought. Thanks!
