### ISSUE TITLE
Simple query string accepting "field:" syntax in the query

### ISSUE THREAD

**Issue by ferdy-galema** [elastic/elasticsearch#10277]
Why does the simple query string parser not accept "title:foobar" in the query like the normal query string parser does?

It would be nice to combine the fault tolerance of the simple query string parser with the "specify field in the query" syntax of the normal query parser.

**Comment by clintongormley** [comment]
The simple query string does not support field syntax by design, as it allows users to query any field that they like

**Comment by ferdy-galema** [comment]
Fair enough, fields can be supplied next to the query, but still then it's
not possible to query something like

pants:blue AND shirt:red

because all fields are thrown together in query. In this example I only
want people with blue pants and red shirts, which is not possible in a
single simple query. (According to what you are saying).

Please correct me if I'm wrong. In any case, thank you for your time.

**Comment by clintongormley** [comment]
No, you're correct.  But perhaps at this level, you want to build your own query parser that allows for the level of control that you're after.
