### ISSUE TITLE
ES 1.5 response syntax error

### ISSUE THREAD

**Issue by ramzy27** [elastic/elasticsearch#10273]
I just downloaded elasticsearch 1.5. After having successfully indexed a document that includes an attachment file , I tried to get my index data in order to test some queries . When I make a simple /_search query i get a not valide Json response.
![es1 5error](https://cloud.githubusercontent.com/assets/3472300/6842729/925447b8-d39b-11e4-8ebd-455d6e735d19.PNG)

**Comment by javanna** [comment]
Hi @ramzy27 could you please post a recreation of what you did, especially the complete search response so we can double check?

**Comment by ramzy27** [comment]
1) I created the following mapping {
    "rfp": {
        "properties": {
            "file": {
                "type": "attachment"
            },
            "filename": {
                "type": "string"
            },
            "filedate": {
                "type": "date"
            },
            "tags": {
                "type": "string",
                "index_name": "tag"
            },
            "author": {
                "type": "string"
            },
            "couple": {
                "type": "nested",
                "include_in_parent": true,
                "properties": {
                    "question": {
                        "type": "string",
                        "analyzer": "english"
                    },
                    "response": {
                        "type": "string",
                        "analyzer": "english"
                    }
                }
            }
        }
    }
}
2)I indexed one document
3)Made a search query 
![es1 5error2](https://cloud.githubusercontent.com/assets/3472300/6842869/1b0b19be-d39d-11e4-8cd3-9877eb664148.PNG)

**Comment by javanna** [comment]
I'm afraid the problem is in your document. elasticsearch doesn't validate json, and just returns what you sent to it, which is why the search response is not a valid json. Have a look [here](https://github.com/elastic/elasticsearch/issues/9415). We've been discussing how we could improve this on #2315 but we haven't reached an agreement yet.
