### ISSUE TITLE
CI: testOldIndexes fails to find docs after sort

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#10279]
See: http://build-us-00.elastic.co/job/es_core_1x_window-2008/1258/testReport/junit/org.elasticsearch.bwcompat/OldIndexBackwardsCompatibilityTests/testOldIndexes/

(note that the message is confusing, expected is what the search returned)
```
java.lang.AssertionError: 
Expected: <0L>
     got: <2858L>

	at __randomizedtesting.SeedInfo.seed([6135E006EB9CCAB2:46EFA250AC715F05]:0)
	at org.junit.Assert.assertThat(Assert.java:780)
	at org.junit.Assert.assertThat(Assert.java:738)
```

**Comment by bleskes** [comment]
another example: http://build-us-00.elastic.co/job/es_core_1x_strong/3200/testReport/junit/org.elasticsearch.bwcompat/OldIndexBackwardsCompatibilityTests/testOldIndexes/

**Comment by rjernst** [comment]
This was fixed in a follow up commit yesterday:
314ee9c
