### ISSUE TITLE
[CI] InstallPluginActionTests testOfficialPluginSnapshot failing

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#102711]
Zombie threads after the test class has run!

**Build scan:**
https://gradle-enterprise.elastic.co/s/22o6baukcol3k/tests/:distribution:tools:plugin-cli:test/org.elasticsearch.plugins.cli.InstallPluginActionTests/testOfficialPluginSnapshot%20%7Bp0=com.google.common.jimfs.JimfsFileSystem@3d49fd31%20p1=org.elasticsearch.plugins.cli.InstallPluginActionTests$1Parameter$$Lambda%2F0x0000000401326ae0@4016ccc1%7D

**Reproduction line:**
```
./gradlew ':distribution:tools:plugin-cli:test' --tests "org.elasticsearch.plugins.cli.InstallPluginActionTests" -Dtests.method="testOfficialPluginSnapshot {p0=com.google.common.jimfs.JimfsFileSystem@3d49fd31 p1=org.elasticsearch.plugins.cli.InstallPluginActionTests$1Parameter$$Lambda/0x0000000401326ae0@4016ccc1}" -Dtests.seed=731BAED44590999D -Dtests.locale=et -Dtests.timezone=America/Barbados -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testOfficialPluginSnapshot%20%7Bp0%3Dcom.google.common.jimfs.JimfsFileSystem@3d49fd31%20p1%3Dorg.elasticsearch.plugins.cli.InstallPluginActionTests$1Parameter$$Lambda/0x0000000401326ae0@4016ccc1%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.plugins.cli.InstallPluginActionTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium))))

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([731BAED44590999D]:0)

```

**Comment by alex-spies** [comment]
Another case of zombie threads here: https://gradle-enterprise.elastic.co/s/ynzblfvohrsyo

Repro line:
```
REPRODUCE WITH: ./gradlew ':distribution:tools:plugin-cli:test' --tests "org.elasticsearch.plugins.cli.InstallPluginActionTests" -Dtests.method="testSlowSignatureVerificationMessage {p0=sun.nio.fs.LinuxFileSystem@2f98635e p1=org.elasticsearch.plugins.cli.InstallPluginActionTests$$Lambda/0x0000000501317a78@49c8f6e8}" -Dtests.seed=D80EF465FDEE3510 -Dtests.locale=lv-LV -Dtests.timezone=Asia/Beirut -Druntime.java=21

```

**Comment by DaveCTurner** [comment]
https://gradle-enterprise.elastic.co/s/zugg6aa6qadei is another one

**Comment by ldematte** [comment]
All test failure issues I examined point to the same culprit:

```
at java.base@21.0.1/java.io.FileInputStream.readBytes(Native Method)	
	at java.base@21.0.1/java.io.FileInputStream.read(FileInputStream.java:287)	
	at java.base@21.0.1/java.io.FilterInputStream.read(FilterInputStream.java:119)	
	at java.base@21.0.1/sun.security.provider.NativePRNG$RandomIO.readFully(NativePRNG.java:426)	
	at java.base@21.0.1/sun.security.provider.NativePRNG$RandomIO.implGenerateSeed(NativePRNG.java:443)
```
The NativePRNG uses by default /dev/random as a source of randomness for seeds; according to comments on the [class itself](https://github.com/openjdk/jdk/blob/master/src/java.base/unix/classes/sun/security/provider/NativePRNG.java) 

>  On some Unix platforms, /dev/random may block until enough entropy is
  available, but that may negatively impact the perceived startup
> on some versions of Linux entropy can be exhausted very quickly and could thus impact
 startup time.

It is strange that it locks for so long, but I guess on a test machine there is no much to be used as a source of randomness, so it might be happening.

I'm investigating if it is possible to make SecureRandom use the NONBLOCKING approad (SecureRandom#NonBlocking or forcing to use /dev/urandom.
It is less secure than usin /dev/random, but this should be not too important in tests.

**Comment by jonathan-buttner** [comment]
@ldematte do we need to backport the change to 8.11? Seems like the failure is happening on that branch too: https://gradle-enterprise.elastic.co/s/tbqtq25kff6em

**Comment by ldematte** [comment]
Yes @jonathan-buttner you are right, I will backport it

**Comment by piergm** [comment]
Another instance here: https://gradle-enterprise.elastic.co/s/a43nw5dbfysdk
Is in 8.11 aswell.
