### ISSUE TITLE
`ecs@mappings` template breaks dynamic mapping of intermediate object fields

### ISSUE THREAD

**Issue by axw** [elastic/elasticsearch#102794]
### Elasticsearch Version

083b59122b3cdf5168d2d2351e53fca99009baf5 (8.12-SNAPSHOT)

### Java Version

_bundled_

### OS Version

Linux

### Problem Description

The `ecs@mappings` component template's dynamic templates unintentionally match dynamically mapped object fields, attempting to map them as non-object field types, breaking ingestion of that object's child properties.

For example, the dynamic template [`ecs_usage_scaled_float`](https://github.com/elastic/elasticsearch/blob/824d06c8cf7fd4811a0ff42e3554bc70dbfb7e0a/x-pack/plugin/core/template-resources/src/main/resources/ecs%40mappings.json#L145-L153) will match the "usage" object when dynamically mapping `a.usage.b: 123`.

### Steps to Reproduce

```
PUT /_index_template/xyz
{
  "index_patterns": ["xyz"],
  "composed_of": ["ecs@mappings"],
  "template": {
    "mappings": {
      "dynamic": true
    }
  }
}

POST /xyz/_doc
{
  "a.usage.b": 123
}
```

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Malformed content, found extra data after parsing: END_OBJECT"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Malformed content, found extra data after parsing: END_OBJECT"
  },
  "status": 400
}
```

(Also that error message is completely unhelpful.)

**Comment by axw** [comment]
P.S. this is not a hypothetical issue, it affects dynamic mapping of the metric field `system.process.cgroup.memory.mem.usage.bytes` when using that component template.

**Comment by eyalkoren** [comment]
#102795 proposes to fix this issue with changing the [`*.usage` dynamic template](https://github.com/elastic/elasticsearch/blob/824d06c8cf7fd4811a0ff42e3554bc70dbfb7e0a/x-pack/plugin/core/template-resources/src/main/resources/ecs%40mappings.json#L145-L153) as follows:
```
        {
          "ecs_usage_scaled_float": {
            "mapping": {
              "type": "scaled_float",
              "scaling_factor": 1000
            },
            "path_match": "*.usage",
            "unmatch_mapping_type": "object"
          }
        }
```
While this fixes the reported issue, it still leaves room for other failures, for example when ingesting a document that contains:
```
        {
          "chair.usage": "sitting"
        }
```

Therefore, #102807 may be preferable as it would allow to do:
```
        {
          "ecs_usage_scaled_float": {
            "mapping": {
              "type": "scaled_float",
              "scaling_factor": 1000
            },
            "path_match": "*.usage",
            "match_mapping_type": ["long", "double"]
          }
        }
```

**Comment by javanna** [comment]
For completeness, could you include the definition of the component template that causes issues?

**Comment by axw** [comment]
@javanna it's linked in the Problem Description section (I linked to the dynamic template in the component template.)
