### ISSUE TITLE
Call to info() raises HTTP exception of Invalid media-type value on headers [Content-Type]

### ISSUE THREAD

**Issue by assaft** [elastic/elasticsearch#102736]
### Elasticsearch Version

8.9.2

### Java Version

_bundled_

### OS Version

MacOS 23.1.0 Darwin

### Problem Description

When calling the info() function, it raises an exception:
```
elasticsearch.BadRequestError: BadRequestError(400, 'media_type_header_exception', 'Invalid media-type value on headers [Content-Type]')
```

I debugged this and found that the failure is in this call:
```python
        meta, resp_body = self.transport.perform_request(
            method,
            target,
            headers=request_headers,
            body=body,
            request_timeout=self._request_timeout,
            max_retries=self._max_retries,
            retry_on_status=self._retry_on_status,
            retry_on_timeout=self._retry_on_timeout,
            client_meta=self._client_meta,
        )
```
In the file `elasticsearch/_sync/client/_base.py
/Users/assaft/workspace/langchain/test1/venv/lib/python3.11/site-packages/elasticsearch/_sync/client/_base.py`

And the value of `request_headers` is:
```python
{'accept': 'application/json'}
```

If I intervene while debugging and add the content-type to make it:
```python
{'accept': 'application/json', "Content-Type": "application/json"}
```
It solves the problem.

To fix this, the function `info()` in `elasticsearch/_sync/client/__init__.py`  needs to be changed; currently it is putting only the `accept` header. Line 2348:

```python
        __headers = {"accept": "application/json"}
```

Notes:
* The problem might be index-specific, but I have no control over the index as it was created by a customer.
* The problem is limited to info().; calling search() works perfectly fine. This is because search() passes the Contet-Type header properly.

### Steps to Reproduce

I'm creating an elasticsearch instance and immediately call info().
Note that I can call search() and it works properly so there is no connection problem.

**Comment by pxsalehi** [comment]
@assaft Are you using https://github.com/elastic/elasticsearch-py?

**Comment by assaftibm** [comment]
Yes - the Python client. Didn't notice there's a separate repo for that. Should I open the issue in the other repo?

**Comment by assaft** [comment]
Yes - the Python client. Didn't notice there's a separate repo for that. Should I open the issue in the other repo?

**Comment by pxsalehi** [comment]
> Should I open the issue in the other repo?

Yes. And maybe close this one please.
