### ISSUE TITLE
there are inaccurate description in tcpretries.asciidoc

### ISSUE THREAD

**Issue by zrlw** [elastic/elasticsearch#102788]
### Elasticsearch Version

8.11

### Java Version

_bundled_

### OS Version

linux

### Problem Description

“Windows defaults to just 5 retransmissions which corresponds with a timeout of around 6 seconds.”
“Five retransmissions corresponds with a timeout of around six seconds.”
tcp_retries2=5 means timeout with first transmission plus 5 retransmissions: 12.6 seconds=(2^6 - 1) * 0.2.
tcp_retries2=15: 924.6 seconds=(2^10 - 1) * 0.2 + (16 - 10) * 120.

### Steps to Reproduce

NOT REQUIRED

**Comment by zrlw** [comment]
https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt
```
tcp_retries2 - INTEGER
	This value influences the timeout of an alive TCP connection,
	when RTO retransmissions remain unacknowledged.
	Given a value of N, a hypothetical TCP connection following
	exponential backoff with an initial RTO of TCP_RTO_MIN would
	retransmit N times before killing the connection at the (N+1)th RTO.
```

**Comment by zrlw** [comment]
![image](https://github.com/elastic/elasticsearch/assets/40652892/772ec904-11c2-4d14-92d6-414bff6630b7)

**Comment by DaveCTurner** [comment]
An experiment confirms that (on a recent Linux at least) the timeout is more like 13s with the suggested `net.ipv4.tcp_retries2=5`.
