### ISSUE TITLE
failed to install lang-groovy

### ISSUE THREAD

**Issue by hyhsoftware** [elastic/elasticsearch#10276]
follow the documents, I execute the command 
./plugin --install elasticsearch/elasticsearch-lang-groovy/3.0.0

but it shows 

Message:
   Error while installing plugin, reason: IllegalArgumentException: Plugin installation assumed to be site plugin, but contains source code, aborting installation.

anyone help me?

**Comment by dadoonet** [comment]
This version does not exist.
Which elasticsearch version are you using BTW?

**Comment by pickypg** [comment]
@hyhsoftware The Groovy language plugin is installed by default with Elasticsearch starting with Elasticsearch 1.3 and later.

**Comment by dadoonet** [comment]
Yeah. I need to update groovy plugin README to make sure users are aware of it.
