### ISSUE TITLE
how to create custom mapping for the same field

### ISSUE THREAD

**Issue by hordemark** [elastic/elasticsearch#10272]
When I put the following JSON to elasticsearch. It get error about nested: NumberFormatException
{  
   "id":"eee",
   "crosstab":{  
      "dims":[  
         {  
            "id":1
         },
         {  
            "id":"asd"
         }
      ]
   }
}

I  knew dims.id have different type, what should I do to avoid create index dim.id or create custom mapping.

**Comment by javanna** [comment]
Hi @hordemark can you please ask your question on the [mailing list](https://groups.google.com/forum/?fromgroups=#!forum/elasticsearch)?
