### ISSUE TITLE
ElasticSearch results using JAVA

### ISSUE THREAD

**Issue by AndiG1985** [elastic/elasticsearch#10285]
HI all, 
I am trying to use ElasticSearch within the JAVA API. As a JSON File (named Google.json) I am using the following structure:
{
 "markers": [
	 {
              "point":"new GLatLng(40.266044,-74.718479)", 
	  "homeTeam":"Lawrence Library",
              "awayTeam":"LUGip",
              "markerImage":"images/red.png",
              "information": "Linux users group meets second Wednesday of each month.",
              "fixture":"Wednesday 7pm",
              "capacity":"",
             },
             {
              "point":"new GLatLng(40.266044,-74.75022)", 
	  "homeTeam":"Hamilton Library",
              "awayTeam":"LUGip HW SIG",
              "markerImage":"images/white.png",
              "information": "Linux users group meets second Tuesday of each month.",
              "fixture":"Tuesday 7pm",
              "capacity":"",
             }
           ]
 }

Using Jackson I am converting this file into a JAVA Hashmap. Then I try to search in field "fixture" for the Word "Tuesday". I am finding this, but as a result I am getting the complete "markers" List back instead of only the second element. I am now wondering what the problem is with my approach.

Here is my JAVA code:

JSONParser parser= new JSONParser();
String path="d:\\Google.json";
		
Node node = nodeBuilder().local(true).node();
Client client = node.client();

/* Jackson mapper*/		
ObjectMapper mapper = new ObjectMapper();
File jsonFile=new File(path);
        
try {
        	/*Read in file using Jackson into HashMap*/
            Map<String, Object> mapObject=new HashMap<String, Object>();
        	mapObject = mapper.readValue(jsonFile, new TypeReference<Map<String, Object>>(){});

        	/*Create index*/        	
        	IndexResponse response=null;
            response = client.prepareIndex(index, type)
    				.setSource(mapObject)				
    				.execute()
    				.actionGet();
        	
            
        	} catch (JsonParseException e1) {
	     e1.printStackTrace();
	} catch (JsonMappingException e1) {
	    e1.printStackTrace();
	} catch (IOException e1) {
	    e1.printStackTrace();
	}
        
        QueryBuilder qb=QueryBuilders.matchQuery("fixture","Tuesday");
        
        SearchResponse response= client.prepareSearch(index)
        		.setTypes(type)
        		.setSearchType(SearchType.QUERY_AND_FETCH)
        		.setQuery(qb)
        		.setFrom(0)
        		.setSize(100)
        		.setExplain(true)
        		.execute().actionGet();
        
        SearchHit[] results = response.getHits().getHits();
        
        System.out.println("Current results: " + results.length);
        
        for (SearchHit hit : results) {
        	System.out.println("------------------------------");
        	Map<String,Object> result = hit.getSource();   
        	System.out.println(result);
        }

It would be great to get any hint/help on this!

Cheers,
Andi

**Comment by javanna** [comment]
HI @AndiG1985 could you please ask your question on the [mailing list](https://groups.google.com/forum/?fromgroups=#!forum/elasticsearch)? We generally use github issues for bugs and feature requests. Thanks!
