### ISSUE TITLE
Add a way to set array of types in `match_mapping_type`

### ISSUE THREAD

**Issue by eyalkoren** [elastic/elasticsearch#102807]
### Description

In addition or instead of #102795, it would be useful to be able to set multiple input JSON types for dynamic templates' `match_mapping_type`, for example: `"match_mapping_type": ["string", "long", "double"]`. 
Otherwise, in order to achieve accurate dynamic templates we would need to duplicate them.
For example, consider the following use cases:
- numeric fields, where both `long` and `double` are relevant, as well as `string` to allow for automatic numeric detection
- auto detection of dates, which requires `string` as well as numbers (not only `long`, also `double` to support sub-millisecond-resolution representation of milliseconds)

Since the number of possible [input mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html#match-mapping-type) is very small, having this capability may make [`unmatch_mapping_type`](https://github.com/elastic/elasticsearch/issues/102795) unnecessary.

cc @axw

**Comment by axw** [comment]
Seems sensible to me. Also aligns with the short-term fix that I have in progress, which is to duplicate `ecs_usage_scaled_float` and set `match_mapping_type` for each of `double` and `long`.

**Comment by javanna** [comment]
This sounds sensible, and goes in the same direction as #66364 but for match on type.
