### ISSUE TITLE
Build requires network access to check it's using the right Gradle version

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#102907]
Discovered this while on a plane journey without said network access:

https://github.com/elastic/elasticsearch/blob/759280c75856de312ec7b2a99c219cec4cc61b1b/build-tools-internal/build.gradle#L361-L363

Is there a way we can make this do something reasonable without network access?

**Comment by mark-vieira** [comment]
This is resolved lazily, so should only be necessary when running the associated task. Do you recall exactly what task you were trying to run?

**Comment by DaveCTurner** [comment]
Does `precommit` download stuff like the ML binaries? I didn't think it did.

**Comment by DaveCTurner** [comment]
Ok thanks for the advice and for indicating how you expect things to work today (which is quite different from how it was the last time I opened my laptop on a plane journey). I don't see a path forwards here without doing more offline work until I hit the same problem, which I'm not going to do, so I'm closing this.
