### ISSUE TITLE
[Feature Request] Support inner_hits.size > 1 for nested dense vector fields

### ISSUE THREAD

**Issue by dbuades** [elastic/elasticsearch#102950]
### Description

Aa discussed in [this PR](https://github.com/elastic/elasticsearch/pull/99763), the addition of such a feature would prove to be very useful for certain use cases.

For example, let's say that we have a scientific article with 4096 tokens that we split in 8 passages of 512 tokens for embedding purposes. The first passage might correspond to the abstract and the last passage to the conclusion.

Now, a user makes a query that can be answered with that scientific article, and we want to match the passages that are more relevant inside that document. There might be the case that both the abstract and the conclusion are relevant, and thus, we would like to show both.

This is possible by having two separate indexes for passages and articles, but if we use the new search on nested dense_vector fields introduced in Elastic 8.11 and only have a single article index, this is no longer possible. The reason being that inner_hits.size == 1 limits ourselves to one passage per article.

CC @benwtrent

**Comment by asxzy** [comment]
It would be great to see this feature. In my use case, I indexed the document by chunks and want to get out the topn chunks for RAG. More like top-k nested chunks but aggregated by document id. Would be great if it works with RRF as well.

**Comment by xlianghang** [comment]
This is useful for my scenario, where you need to both structure the subdata and count the relevance of each subdata item.

**Comment by jasper-s** [comment]
Very useful indeed, our usecase would also benefit from this addition greatly
