### ISSUE TITLE
[Transform] Unexpected changes in transform configuration.

### ISSUE THREAD

**Issue by przemekwitek** [elastic/elasticsearch#102933]
### Elasticsearch Version

main + all released versions back to 7.9

### Java Version

_bundled_

### OS Version

n/a

### Problem Description

It was observed that some transforms behaved badly after the update of **another** (unrelated) transform.

### Steps to Reproduce

1. Update the settings of one transform
2. Observe how these settings get effective for **another** transform

**Comment by droberts195** [comment]
I think the transforms that get incorrectly updated are those running on the same node as the transform that was intended to be updated.

So the likelihood of seeing this problem increases the more transforms that are running, and decreases the more transform nodes there are. By default transform nodes are the hot data nodes, so if transforms are perfectly balanced and there are more hot data nodes than running transforms then this bug won't be seen.

**Comment by przemekwitek** [comment]
> I think the transforms that get incorrectly updated are those running on the same node as the transform that was intended to be updated.
> 
> So the likelihood of seeing this problem increases the more transforms that are running, and decreases the more transform nodes there are. By default transform nodes are the hot data nodes, so if transforms are perfectly balanced and there are at least as many hot data nodes as there are running transforms then this bug won't be seen.

Adding to that, there is a mechanism that re-fetches the transform configuration from the internal index and uses it to override the in-memory configuration. So the buggy settings will usually be overridden by the correct settings which also makes this bug non-deterministic.
