### ISSUE TITLE
Support for overrideEnabled flag in Rename Processor

### ISSUE THREAD

**Issue by ShourieG** [elastic/elasticsearch#102984]
### Description

Recently there have been some issues for users using many of elastic's integrations, where the ingest pipeline crashed due to a **rename** **target_field** already existing. One such recent issue is linked here: https://github.com/elastic/integrations/issues/8244. 
This is usually solved by adding extra logic in the ingest pipelines but often leads to an unnecessary increment of pipeline logic. 

Proposed Solution: Add support for **overrideEnabled flag** similar to the Set processor. 

Questions: 
1) Is there any specific reason that this was originally omitted from the Rename processor ?
2) Any specific requirements for a PR adding this change into elasticsearch ?

**Comment by dakrone** [comment]
I don't think there was a specific reason this was originally ommitted, and it seems reasonable to me. The only thing is that it cannot change the existing default behavior. We should also call it `override` to match the `set` processor version.
