### ISSUE TITLE
ESQL: data returned by default

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#102949]
### Description

When dealing with a large mapping (e.g. ECS), queries that do NOT perform projections end up returning a LOT of fields, with the vast majority being empty.
Instead of returning the fields, the underlying content (_source) could be returned instead - thus the amount of data returned, depends on the actual document structure stored.

**Comment by nik9000** [comment]
Did we fix this in https://github.com/elastic/elasticsearch/pull/102428 ? I think that might be all for now.

**Comment by costin** [comment]
Yes, you did!
