### ISSUE TITLE
[CI] InstallPluginActionTests testOfficialPluginStaging {p0=sun.nio.fs.LinuxFileSystem@2416498e p1=org.elasticsearch.plugins.cli.InstallPluginActionTests$$Lambda/0x0000000201317a78@6b2e0f78} failing

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#103056]
**Build scan:**
https://gradle-enterprise.elastic.co/s/aw5euayxbjmem/tests/:distribution:tools:plugin-cli:test/org.elasticsearch.plugins.cli.InstallPluginActionTests/testOfficialPluginStaging%20%7Bp0=sun.nio.fs.LinuxFileSystem@2416498e%20p1=org.elasticsearch.plugins.cli.InstallPluginActionTests$$Lambda%2F0x0000000201317a78@6b2e0f78%7D

**Reproduction line:**
```
./gradlew ':distribution:tools:plugin-cli:test' --tests "org.elasticsearch.plugins.cli.InstallPluginActionTests" -Dtests.method="testOfficialPluginStaging {p0=sun.nio.fs.LinuxFileSystem@2416498e p1=org.elasticsearch.plugins.cli.InstallPluginActionTests$$Lambda/0x0000000201317a78@6b2e0f78}" -Dtests.seed=B4B3D73CFC4B8DAC -Dtests.locale=da-DK -Dtests.timezone=Asia/Dushanbe -Druntime.java=21
```

**Applicable branches:**
8.11

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.plugins.cli.InstallPluginActionTests#testOfficialPluginStaging {p0=sun.nio.fs.LinuxFileSystem@2416498e p1=org.elasticsearch.plugins.cli.InstallPluginActionTests$$Lambda/0x0000000201317a78@6b2e0f78}`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testOfficialPluginStaging%20%7Bp0%3Dsun.nio.fs.LinuxFileSystem@2416498e%20p1%3Dorg.elasticsearch.plugins.cli.InstallPluginActionTests$$Lambda/0x0000000201317a78@6b2e0f78%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.plugins.cli.InstallPluginActionTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([B4B3D73CFC4B8DAC]:0)

```

**Comment by rjernst** [comment]
Closing since the backport is complete.
