### ISSUE TITLE
key_as_string is always showing up as 1970-01-01 in Date Histogram

### ISSUE THREAD

**Issue by devnull52** [elastic/elasticsearch#10304]
Using ElasticSearch 1.5.0 and datehistogram, the key_as_string is always showing up as 1970-01-01. I am using publicly available IMDB movie DB to test ES. Please advice if I am doing something wrong.

```js
GET /movies/movie/_search?search_type=count
{
    "aggs" : {
        "movie-releases-by-year" : {
            "date_histogram" : {
                "field" : "fields.year",
                "interval" : "50",
                "min_doc_count": 0,
                "format" : "yyyy-MM-dd" 
            }
        }
    }
}
```

```js
{
   "took": 2,
   "timed_out": false,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "hits": {
      "total": 4903,
      "max_score": 0,
      "hits": []
   },
   "aggregations": {
      "movie-releases-by-year": {
         "buckets": [
            {
               "key_as_string": "1970-01-01",
               "key": 1900,
               "doc_count": 51
            },
            {
               "key_as_string": "1970-01-01",
               "key": 1950,
               "doc_count": 1480
            },
            {
               "key_as_string": "1970-01-01",
               "key": 2000,
               "doc_count": 3309
            }
         ]
      }
   }
}
```

**Comment by dadoonet** [comment]
Can you send your mapping please?

**Comment by devnull52** [comment]
Hi David,

Thanks for getting back. I am a novice on ElasticSearch, so apologies in
anticipation if I might be doing something incorrectly. I am basically
trying to play around with publicly available IMDB Movie data to understand
search concepts.

What I was hoping to get is a date histogram by Release date:-

Code, Log and Mapping attached. Environment : I am running ES 1.5.0 ( MBP,
Java 8 ) via Home Brew. Code is compiled using Maven.

1970 (Release year in my mind maps to a Date): 10 ( Number of movies
released in the year ).
1971 : 1
1972 : 2 etc



On Sun, Mar 29, 2015 at 12:35 AM, David Pilato <notifications@github.com>
wrote:

> Can you send your mapping please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch/issues/10304#issuecomment-87357238>
> .
>

  {
      "fields" : {
         "directors" : [
            "Roland Emmerich"
         ],
         "release_date" : "2013-06-26T00:00:00Z",
         "rating" : 6.4,
         "genres" : [
            "Action",
            "Drama",
            "Thriller"
         ],
         "image_url" : "http://ia.media-imdb.com/images/M/MV5BMTAyNzQyNTcwNjVeQTJeQWpwZ15BbWU3MDAwOTQ4Nzk@._V1_SX400_.jpg",
         "plot" : "While on a tour of the White House with his young daughter, a Capitol policeman springs into action to save his child and protect the president from a heavily armed group of paramilitary invaders.",
         "title" : "White House Down",
         "rank" : 60,
         "running_time_secs" : 7860,
         "actors" : [
            "Channing Tatum",
            "Jamie Foxx",
            "Maggie Gyllenhaal"
         ],
         "year" : 2013
      },
      "id" : "tt2334879",
      "type" : "add"
   },
   {
      "fields" : {
         "directors" : [
            "Michael Bay"
         ],
         "release_date" : "2013-04-11T00:00:00Z",
         "rating" : 6.5,
         "genres" : [
            "Comedy",
            "Crime",
            "Drama"
         ],
         "image_url" : "http://ia.media-imdb.com/images/M/MV5BMTU0NDE5NTU0OV5BMl5BanBnXkFtZTcwMzI1OTMzOQ@@._V1_SX400_.jpg",
         "plot" : "A trio of bodybuilders in Florida get caught up in an extortion ring and a kidnapping scheme that goes terribly wrong.",
         "title" : "Pain & Gain",
         "rank" : 61,
         "running_time_secs" : 7740,
         "actors" : [
            "Mark Wahlberg",
            "Dwayne Johnson",
            "Anthony Mackie"
         ],
         "year" : 2013
      },
      "id" : "tt1980209",
      "type" : "add"
   },
   {
      "fields" : {
         "directors" : [
            "Baltasar Kormákur"
         ],
         "release_date" : "2013-07-30T00:00:00Z",
         "rating" : 7,
         "genres" : [
            "Action",
            "Comedy",
            "Crime",
            "Drama",
            "Thriller"
         ],
         "image_url" : "http://ia.media-imdb.com/images/M/MV5BNTQ5MTgzNDg4OF5BMl5BanBnXkFtZTcwMjAyODEzOQ@@._V1_SX400_.jpg",
         "plot" : "A DEA agent and a naval intelligence officer find themselves on the run after a botched attempt to infiltrate a drug cartel. While fleeing, they learn the secret of their shaky alliance: Neither knew that the other was an undercover agent.",
         "title" : "2 Guns",
         "rank" : 62,
         "running_time_secs" : 6540,
         "actors" : [
            "Denzel Washington",
            "Mark Wahlberg",
            "Paula Patton"
         ],
         "year" : 2013
      },
      "id" : "tt1272878",
      "type" : "add"
   }
curl -XPOST localhost:9200/movies/ -d '{
    "settings" : {
        "number_of_shards" : 1,
        "number_of_replicas" : 0
    },
    "mappings" : {

       "movie": {

            "_all" : {
                "enabled" : "false"
            },
            "_id" : {
                "path" : "fields.title"
            },
            "properties": {
                "fields": {
                    "type": "object",
                    "properties": {
                        "directors" : { "type" : "string" },
                        "release_date" : { "type": "date" },
                        "rating" : { "type": "float" }, 
                        "genres" : { "type" : "string" },
                        "image_url" : { "type": "string" },
                        "plot" : { "type": "string" },
                        "title" : { "type": "string" },
                        "rank" : { "type": "long" },
                        "running_time_secs" : { "type": "long" },   
                        "actors" : { "type" : "string" },
                        "year" : { "type" : "date", "format" : "yyyy" }
                    }
                },
                "id": {
                    "type": "string"

                },
                "type": {
                    "type": "string"
                }
            }

        }
    },
    "aliases" : {
        "all_movies" : {},
        "recent_movies" : {
            "filter" : {
                "term" : {"year" : 2014 }
            }
        },
        "eighties_nineties" : {
            "filter" : {
                    "range" : {
                        "year" : {
                            "gt" : 1979,
                            "lt" : 2000
                        }
                    }
                }
            }
    } 
}'

**Comment by rjernst** [comment]
@devnull52 What you posted there is just a sample document.  I assume then you are using dynamic mappings? Can you run the following command and post the output?

```
curl -XGET 'http://localhost:9200/movies/_mapping/movie'
```

**Comment by patricksurry** [comment]
It looks like it's interpreting fields.year as an timestamp (millis since epoch) rather than a year value like you expect.  So all your keys are a few seconds appear 1/1/1970 and hence your key-as-string is constant.

**Comment by devnull52** [comment]
Hi Ryan,

Please see below. I created mappings during index creation time.
Please let me know if there is anything else I can provide.


{
  "movies" : {
    "mappings" : {
      "movie" : {
        "_all" : {
          "enabled" : false
        },
        "_id" : {
          "path" : "fields.title"
        },
        "properties" : {
          "facets" : {
            "properties" : {
              "date_histogram" : {
                "properties" : {
                  "field" : {
                    "type" : "string"
                  },
                  "interval" : {
                    "type" : "string"
                  }
                }
              }
            }
          },
          "fields" : {
            "properties" : {
              "actors" : {
                "type" : "string"
              },
              "directors" : {
                "type" : "string"
              },
              "genres" : {
                "type" : "string"
              },
              "image_url" : {
                "type" : "string"
              },
              "plot" : {
                "type" : "string"
              },
              "rank" : {
                "type" : "long"
              },
              "rating" : {
                "type" : "float"
              },
              "release_date" : {
                "type" : "date",
                "format" : "dateOptionalTime"
              },
              "running_time_secs" : {
                "type" : "long"
              },
              "title" : {
                "type" : "string"
              },
              "year" : {
                "type" : "date",
                "format" : "yyyy"
              }
            }
          },
          "id" : {
            "type" : "string"
          },
          "query" : {
            "properties" : {
              "match_all" : {
                "type" : "object"
              }
            }
          },
          "type" : {
            "type" : "string"
          }
        }
      }
    }
  }
}

**Comment by rjernst** [comment]
@devnull52, @patricksurry is correct (thanks!). Date fields internally store their value as an epoch based timestamp (in milliseconds). The fact that "key" comes back as an int in your first posted response shows the actual value is far to low (it should be much large to be a timestamp representing e.g. the year 1950).

I see your mappings have a format set for the field. IIRC, format won't work unless you pass the value as a string (otherwise it interprets as a timestamp).  Your example documents show you are passing year as an int.

**Comment by devnull52** [comment]
Ryan, Patrick and David -- thanks for picking this up and responding
patiently. I did not read the documentation. I changed the mapping and
it worked like a charm.

**Comment by clintongormley** [comment]
Great to hear it is resolved. Closing this issue
