### ISSUE TITLE
Disk usage has increased in the nightly Logging benchmark

### ISSUE THREAD

**Issue by ChrisHegarty** [elastic/elasticsearch#103002]
Disk usage has increased in the nightly Logging benchmark [1] (on 2023-12-04), from 182GB to 190GB. A little more than 4%. This lines up with the bump to Lucene 9.9.0 in Elasticsearch. 

![Screenshot 2023-12-05 at 17 36 34](https://github.com/elastic/elasticsearch/assets/62058229/84d6d174-07aa-46f1-b83d-f4ce3b63ae95)

Lucene 9.9.0 has changed postings back to using FOR (from PFOR)[2] . This is the likely change that has resulted in the additional usage.

[1] https://elasticsearch-benchmarks.elastic.co/#tracks/logging/nightly/default/30d - look at `nightly-elastic/logs-io`
[2] https://github.com/apache/lucene/pull/12741

Note from the Lucene 9.9.0 changelog: "GITHUB#12696: Change Postings back to using FOR in Lucene99PostingsFormat. Freqs, positions and offset keep using PFOR."

**Comment by ChrisHegarty** [comment]
Elasticsearch can add back PFOR encoding for posting, in our own codec.

**Comment by martijnvg** [comment]
Maybe a heuristic for using PFOR would be if an index is backing index of a data stream? (`mapperService.mappingLookup().isDataStreamTimestampFieldEnabled()` would do the trick)
