### ISSUE TITLE
UpdateByQueryRequest serialize method will not return all serialized string

### ISSUE THREAD

**Issue by cangkuren** [elastic/elasticsearch#103169]
### Elasticsearch Version

8.5.1

### Java Version

openjdk version "1.8.0_302"

### OS Version

window 10

### Problem Description

my updatebyqueryrequest is
`{"query":{"term":{"subjectId":{"value":592}}},"script":{"params":{"businessTypeId":2},"lang":"painless","source":"ctx._source.subjectShared.add(params.businessTypeId)"}}`
and the serialize code is 
`public void updateByQueryRequest(UpdateByQueryRequest updateByQueryRequest) throws IOException {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream(3000);
        updateByQueryRequest.serialize(new JacksonJsonpGenerator(new JsonFactory().createGenerator(outputStream)), new JacksonJsonpMapper());
        Message message = messageProducer.generateMessage(syncToEsTopic);
        message.setProperty(qmqKey, SyncEsAction.UPDATE_BY_QUERY_REQUEST);

        message.setProperty(qmqMessageBody, outputStream.toString());
        messageProducer.sendMessage(message);
    }
`
    
 but I found the actual output is :
`{"query":{"term":{"subjectId":{"value":592}}},"script":{"params":{"businessTypeId":2`
when I dive into the source code, I found it do the serialization for script and others.
![image](https://github.com/elastic/elasticsearch/assets/19160275/fb34b0a4-345a-48ab-93d9-da4759e783e0)

### Steps to Reproduce

just execute the serialize method that the UpdateByQueryRequest provided.

**Comment by gbanasiak** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question around the use of scripts with Java HLRC (High-Level Rest Client), and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Some pointers:
* Java HLRC documentation including script example: https://www.elastic.co/guide/en/elasticsearch/client/java-rest/7.17/java-rest-high-document-update-by-query.html (please note this client is deprecated)
* documentation for new Java client: https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/index.html
