### ISSUE TITLE
filebeat is unable to display metrics on kibana discover tab

### ISSUE THREAD

**Issue by skumarya-tibco** [elastic/elasticsearch#103170]
### Elasticsearch Version

8.8.0

### Java Version

17.0.7 2023-04-18 LTS

### OS Version

MAC OS Darwin Kernel Version 22.5.0

### Problem Description

we was using 7.16 elasticsearch,kibana and filebeat verison earlier which used to scrap metrics and displayed in the kibana discover tab but when upgraded to 8.8.0 it doesn't display 
elastic,kibana and filebeat yaml file we are using is 
apiVersion: elasticsearch.k8s.elastic.co/v1
      kind: Elasticsearch
      metadata:
        name: elasticsearch
        labels:
          app.kubernetes.io/part-of: {{ .Chart.Name }}
          app.kubernetes.io/name: elasticsearch
          spotfire-str-installer: "true"
      spec:
        version: {{ .Values.elasticsearch.version | quote }}
        nodeSets:
        - name: default
          count: 1
          config:
            node.roles: ["master", "data", "ingest", "remote_cluster_client"]
            node.store.allow_mmap: false
          volumeClaimTemplates:
          - metadata:
              name: elasticsearch-data
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: {{ (index .Values .Values.size).elasticsearch.disk | quote }}
          podTemplate:
            spec:
              enableServiceLinks: false
              containers:
              - name: elasticsearch
                resources:
                  limits:
                    memory: {{ (index .Values .Values.size).elasticsearch.memory | quote }}
        http:
          tls:
            selfSignedCertificate:
              disabled: false
          service:
            spec:
              ports:
              - name: https
                port: 9200
                protocol: TCP
                targetPort: https
      ---
      apiVersion: kibana.k8s.elastic.co/v1
      kind: Kibana
      metadata:
        name: kibana
        labels:
          app.kubernetes.io/part-of: {{ .Chart.Name }}
          app.kubernetes.io/name: kibana
      spec:
        version: {{ .Values.kibana.version | quote }}
        count: 1
        podTemplate:
          spec:
            containers:
            - name: kibana
              env:
                - name: ELASTICSEARCH_URL
                  value: https://elasticsearch-es-http:9200
                - name: ELASTICSEARCH_HOSTS
                  value: https://elasticsearch-es-http:9200
        elasticsearchRef:
          name: elasticsearch
        http:
          tls:
            selfSignedCertificate:
              disabled: false
          service:
            spec:
              ports:
              - name: https
                port: 443
                protocol: TCP
                targetPort: https
      ---
      apiVersion: beat.k8s.elastic.co/v1beta1
      kind: Beat
      metadata:
        name: filebeat
      spec:
        type: filebeat
        version: {{ .Values.elasticsearch.version | quote }}
        elasticsearchRef:
          name: elasticsearch
        kibanaRef:
          name: kibana
        config:
          filebeat.autodiscover:
            providers:
              - node: $(NODE_NAME)
                type: kubernetes
                hints.default_config.enabled: "false"
                templates:
                - condition.equals.kubernetes.labels.tekton_dev/memberOf: "tasks"
                  config:
                  - paths: ["/var/log/containers/*\${data.kubernetes.container.id}.log"]
                    type: container
          processors:
          - add_cloud_metadata: {}
          - add_host_metadata: {}
          output.elasticsearch.index: "tekton"
          setup.template.name: "tekton"
          setup.template.pattern: "tekton"
          filebeat.modules:
          - module: system
            syslog:
              enabled: true
            auth:
              enabled: true
        daemonSet:
          podTemplate:
            spec:
              serviceAccountName: prometheus
              automountServiceAccountToken: true
              terminationGracePeriodSeconds: 30
              dnsPolicy: ClusterFirstWithHostNet
              hostNetwork: true
              containers:
              - name: filebeat
                securityContext:
                  runAsUser: 0
                  {{- if eq .Values.cloud "openshift" }}
                  privileged: true
                  {{- end }}
                volumeMounts:
                - name: varlogcontainers
                  mountPath: /var/log/containers
                - name: varlogpods
                  mountPath: /var/log/pods
                - name: varlibdockercontainers
                  mountPath: /var/lib/docker/containers
                env:
                  - name: NODE_NAME
                    valueFrom:
                      fieldRef:
                        fieldPath: spec.nodeName
              volumes:
              - name: varlogcontainers
                hostPath:
                  path: /var/log/containers
              - name: varlogpods
                hostPath:
                  path: /var/log/pods
              - name: varlibdockercontainers
                hostPath:
                  path: /var/lib/docker/containers
      !
Also we cant see the time keeper dropdown in kibana discover tab

### Steps to Reproduce

deploy the elastic kibana and filebeat the yaml provided above we cant see metrics displayed in kiaban discover tab

**Comment by gbanasiak** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question around Elastic Stack upgrade and Filebeat setup, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
