### ISSUE TITLE
Filebeat parsing module for Claroty

### ISSUE THREAD

**Issue by jeethsam** [elastic/elasticsearch#103179]
### Description

Hi All,

Several OT/ICS vendors are using Elastic as part of their security suite, I need to develop parsers for the logs from Claroty CTD device. https://claroty.com/industrial-cybersecurity/ctd
I would like to see Claroty out of box parsing module and OOB integration in Elastic. 
Attached are some anonymized logs.

Regards,
Jeethendar S
[Claroty_ctd_logs_sample.txt](https://github.com/elastic/elasticsearch/files/13612776/Claroty_ctd_logs_sample.txt)

**Comment by gbanasiak** [comment]
Thanks very much for your interest in Elasticsearch.

This is a repo with Elasticsearch server code but you're asking for a new Filebeat module. Such enhancement request should rather be raised in https://github.com/elastic/beats. Please start from posting a question at https://discuss.elastic.co/c/beats on how to best address your requirement before opening a GH issue.

I hope you don't mind if I close this issue.
