### ISSUE TITLE
grand parent/parent/child aggregation (NullPointerException)

### ISSUE THREAD

**Issue by rkarakaya** [elastic/elasticsearch#10315]
Hi,

I have tested against 1.4.3 and 1.5.0 and I am getting NPE during the aggreagation below:

MAPPINGS:

<PRE>
    "user": {
      "dynamic": "false",
      "_timestamp": {
        "enabled": false,
        "format": "date_optional_time"
      },
      "_index": {
        "enabled": false
      },
      "_ttl": {
        "enabled": false
      },
      "_size": {
        "enabled": false
      },
      "properties": {
        "tags": {
          "index": "not_analyzed",
          "postings_format": "default",
          "similarity": "default",
          "fielddata": {
            "loading": "lazy"
          },
          "type": "string"
        },
        "revenue_t": {
          "type": "double"
        },
        "revenue_avgd": {
          "type": "double"
        },
        "segments": {
          "index": "not_analyzed",
          "postings_format": "default",
          "similarity": "default",
          "fielddata": {
            "loading": "lazy"
          },
          "type": "string"
        },
        "install_date": {
          "format": "dateOptionalTime",
          "type": "date"
        },
        "revenue_avgm": {
          "type": "double"
        },
        "user_id": {
          "index": "not_analyzed",
          "postings_format": "default",
          "similarity": "default",
          "fielddata": {
            "loading": "lazy"
          },
          "type": "string"
        },
        "slot": {
          "type": "long"
        },
        "profile": {
          "properties": {
            "age": {
              "type": "long"
            },
            "team": {
              "index": "not_analyzed",
              "postings_format": "default",
              "similarity": "default",
              "fielddata": {
                "loading": "lazy"
              },
              "type": "string"
            }
          }
        }
      },
      "_all": {
        "enabled": false
      }
    },

    "session": {
      "dynamic": "false",
      "_source": {
        "enabled": false
      },
      "_routing": {
        "required": true
      },
      "_timestamp": {
        "enabled": false,
        "format": "date_optional_time"
      },
      "_index": {
        "enabled": false
      },
      "_ttl": {
        "enabled": false
      },
      "_size": {
        "enabled": false
      },
      "properties": {
        "spid": {
          "index": "not_analyzed",
          "postings_format": "default",
          "similarity": "default",
          "fielddata": {
            "loading": "lazy"
          },
          "type": "string"
        },
        "sts": {
          "format": "dateOptionalTime",
          "type": "date"
        }
      },
      "_all": {
        "enabled": false
      },
      "_parent": {
        "type": "user"
      }
    },
	

    "event": {
      "dynamic": "false",
      "_source": {
        "enabled": false
      },
      "_routing": {
        "required": true
      },
      "_timestamp": {
        "enabled": false,
        "format": "date_optional_time"
      },
      "_index": {
        "enabled": false
      },
      "_ttl": {
        "enabled": false
      },
      "_size": {
        "enabled": false
      },
      "properties": {
        "con": {
          "index": "not_analyzed",
          "postings_format": "default",
          "similarity": "default",
          "fielddata": {
            "loading": "lazy"
          },
          "type": "string"
        },
        "ets": {
          "format": "dateOptionalTime",
          "type": "date"
        },
        "data": {
          "properties": {
            "balance": {
              "type": "double"
            },
            "level": {
              "type": "long"
            },
            "page": {
              "index": "not_analyzed",
              "postings_format": "default",
              "similarity": "default",
              "fielddata": {
                "loading": "lazy"
              },
              "type": "string"
            },
            "invoiceID": {
              "index": "not_analyzed",
              "postings_format": "default",
              "similarity": "default",
              "fielddata": {
                "loading": "lazy"
              },
              "type": "string"
            },
            "tas": {
              "type": "long"
            },
            "pid": {
              "index": "not_analyzed",
              "postings_format": "default",
              "similarity": "default",
              "fielddata": {
                "loading": "lazy"
              },
              "type": "string"
            }
          }
        },
        "et": {
          "index": "not_analyzed",
          "postings_format": "default",
          "similarity": "default",
          "fielddata": {
            "loading": "lazy"
          },
          "type": "string"
        }
      },
      "_all": {
        "enabled": false
      },
      "_parent": {
        "type": "session"
      }
    }

</PRE>

SAMPLE DATA:

USER:
<PRE>
{
  "_index": "testapp3",
  "_type": "user",
  "_id": "bD0CGpdVOAbF",
  "_version": 1,
  "_score": 1,
  "_source": {
    "user_id": "bD0CGpdVOAbF",
    "slot": 0,
    "segments": [
      "yandas trol",
      "dayisi bakan"
    ],
    "tags": [
      "asia"
    ],
    "install_date": "2015-04-12T06:16:54.787Z",
    "revenue_t": 300.6897,
    "revenue_avgd": 0,
    "revenue_avgm": 0,
    "profile": {
      "team": "karabukspor",
      "age": 34
    }
  }
}
</PRE>

SESSION

<PRE>
{
  "_index": "testapp3",
  "_type": "session",
  "_id": "nKyJHGgCBl9t5oG7",
  "_version": 1,
  "_score": 1,
  "_source": {
    "spid": "4Jn7mOG6dtkrimdKQFUETmCD",
    "sts": "2015-04-20T20:11:20.209Z"
  },
  "fields": {
    "_parent": "bD0CGpdVOAbF"
  }
}
</PRE>
EVENT:
<PRE>
{
  "_index": "testapp3",
  "_type": "event",
  "_id": "AUxqJOcTwN0lu_3PUVp2",
  "_version": 1,
  "_score": 1,
  "_source": {
    "et": "UserBalance",
    "ets": "2015-04-20T20:23:20.209Z",
    "con": "cellular",
    "data": {
      "balance": 8.722086988665563
    }
  },
  "fields": {
    "_parent": "nKyJHGgCBl9t5oG7"
  }
}
</PRE>

QUERY:
<PRE>
{
  "query": {
    "match_all": {
      
    }
  },
  "from": 0,
  "size": 10,
  "explain": false,
  "version": false,
  "aggs": {
    "segments": {
      "terms": {
        "field": "segments",
        "size": 20
      },
      "aggs": {
        "to_session": {
          "children": {
            "type": "session"
          },
          "aggs": {
            "to_event": {
              "children": {
                "type": "event"
              },
              "aggs": {
                "filtered": {
                  "filter": {
                    "term": {
                      "et": "UserBalance"
                    }
                  },
                  "aggs": {
                    "average_balance": {
                      "avg": {
                        "field": "data.balance"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

</PRE>

ERROR:

<PRE>
[2015-03-30 13:40:45,265][DEBUG][action.search.type       ] [Tagak the Leopard Lord] All shards failed for phase: [query]
org.elasticsearch.search.query.QueryPhaseExecutionException: [testapp3][3]: query[ConstantScore(*:*)],from[0],size[10]: Query Failed [Failed to execute main query]
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:163)
        at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:286)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:297)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
        at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
        at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.NullPointerException
        at org.elasticsearch.search.aggregations.bucket.children.ParentToChildrenAggregator.doPostCollection(ParentToChildrenAggregator.java:149)
        at org.elasticsearch.search.aggregations.Aggregator.postCollection(Aggregator.java:335)
        at org.elasticsearch.search.aggregations.bucket.children.ParentToChildrenAggregator.doPostCollection(ParentToChildrenAggregator.java:186)
        at org.elasticsearch.search.aggregations.Aggregator.postCollection(Aggregator.java:335)
        at org.elasticsearch.search.aggregations.Aggregator.postCollection(Aggregator.java:334)
        at org.elasticsearch.search.aggregations.AggregationPhase$AggregationsCollector.postCollection(AggregationPhase.java:178)
        at org.elasticsearch.search.internal.ContextIndexSearcher.search(ContextIndexSearcher.java:202)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:491)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:448)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:281)
        at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:269)
        at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:157)
        ... 8 more

</PRE>

**Comment by martijnvg** [comment]
@rkarakaya Thanks for reporting. The bug has been fixed via #10263 and will be included in the upcoming 1.5.1 release.

**Comment by rkarakaya** [comment]
thanks a lot..
