### ISSUE TITLE
Catch exceptions from cluster state listeners when they are notified?

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#10317]
When the cluster state service is closed then all listeners are notified. We currently do not handle unchecked Exceptions that are thrown when `ObserverClusterStateListener.onClose()` is called, see for example https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/cluster/service/InternalClusterService.java#L167 . This might be trappy because it means that all listeners that come after one that caused an exception will not be notified and code after listener notification will not be executed as well. I ran into this in https://github.com/elastic/elasticsearch/pull/10172 : custom implementation of `onClose()` caused a `EsRejectedExecutionException` which then caused thread leaks in tests because the exception was not caught. 

Should we always handle unchecked exceptions in general when we notify listeners?

**Comment by clintongormley** [comment]
@brwe is this still relevant?
