### ISSUE TITLE
Endless mapping refresh

### ISSUE THREAD

**Issue by EikeDehling** [elastic/elasticsearch#10318]
- We're running ES 1.4.2
- Can sometimes be solved by closing/re-opening affected indices, but the issue usually returns prettys soon
- This "clogs" up pending tasks and some tasks get stuck / cluster actions will now always timeout (e.g. loading/removing warmers)
- This consumes all network capacity on the ES nodes

https://gist.github.com/EikeDehling/a015a5137ac5d99dc850

[buzzcapture@hermes ~]$ curl http://artemis3:9200/_cat/pending_tasks
18149502    1s HIGH   refresh-mapping [postings-5360000000][[posting]] 
18149503 745ms HIGH   refresh-mapping [postings-5500000000][[posting]] 
18149509 736ms HIGH   refresh-mapping [postings-5360000000][[posting]] 
18149504 737ms HIGH   refresh-mapping [postings-4180000000][[posting]] 
18149510 735ms HIGH   refresh-mapping [postings-5190000000][[posting]] 
18149512 735ms HIGH   refresh-mapping [postings-5430000000][[posting]] 
18149506 736ms HIGH   refresh-mapping [postings-5430000000][[posting]] 
18149505 736ms HIGH   refresh-mapping [postings-5500000000][[posting]] 
18149511 735ms HIGH   refresh-mapping [postings-5430000000][[posting]] 
18149515 732ms HIGH   refresh-mapping [postings-5430000000][[posting]] 
18149519 290ms HIGH   refresh-mapping [postings-5430000000][[posting]] 
18149521 289ms HIGH   refresh-mapping [postings-5190000000][[posting]] 
18149513 734ms HIGH   refresh-mapping [postings-5100000000][[posting]] 
18149525 287ms HIGH   refresh-mapping [postings-5100000000][[posting]] 
18149507 736ms HIGH   refresh-mapping [postings-5500000000][[posting]] 
18149508 736ms HIGH   refresh-mapping [postings-5500000000][[posting]] 
18149514 733ms HIGH   refresh-mapping [postings-5500000000][[posting]] 
18149516 299ms HIGH   refresh-mapping [postings-4180000000][[posting]] 
18149517 298ms HIGH   refresh-mapping [postings-5360000000][[posting]] 
18149518 291ms HIGH   refresh-mapping [postings-5430000000][[posting]] 
12674966  1.7d NORMAL master ping (from: [Y8LnaPqjTv-4Vn4CWXWWlQ])     
18149520 290ms HIGH   refresh-mapping [postings-5430000000][[posting]] 
12676681  1.7d NORMAL master ping (from: [Y8LnaPqjTv-4Vn4CWXWWlQ])     
18149522 289ms HIGH   refresh-mapping [postings-5190000000][[posting]] 
18149523 288ms HIGH   refresh-mapping [postings-5100000000][[posting]] 
18149524 288ms HIGH   refresh-mapping [postings-4180000000][[posting]] 
12678378  1.7d NORMAL master ping (from: [Y8LnaPqjTv-4Vn4CWXWWlQ])     
18149526 286ms HIGH   refresh-mapping [postings-5430000000][[posting]] 
18149527 286ms HIGH   refresh-mapping [postings-5190000000][[posting]] 
18149528 286ms HIGH   refresh-mapping [postings-4180000000][[posting]] 
18149529 286ms HIGH   refresh-mapping [postings-5500000000][[posting]] 
18149530 284ms HIGH   refresh-mapping [postings-5500000000][[posting]] 
18149531 284ms HIGH   refresh-mapping [postings-5360000000][[posting]] 
18149532 284ms HIGH   refresh-mapping [postings-5100000000][[posting]] 
18149533 284ms HIGH   refresh-mapping [postings-5500000000][[posting]] 
18149534 281ms HIGH   refresh-mapping [postings-5360000000][[posting]]

**Comment by bleskes** [comment]
@EikeDehling can you enable debug logging for `indices.cluster` and grep the logs for the output of this line? I want to see what the difference is between the two sources . A gist will be great.
```
logger.debug("[{}] parsed mapping [{}], and got different sources\noriginal:\n{}\nparsed:\n{}", index, mappingType, mappingSource, mapperService.documentMapper(mappingType).mappingSource());
```

**Comment by EikeDehling** [comment]
@bleskes Thanks for the quick reponse!

Gist here: https://gist.github.com/EikeDehling/129aa3f8213ad8552f49

The difference in mapping appears to be in nested elements, apparently they are not ordered alphbetically? The difference in serialisation is under posting.properties.body.fields._text_.fielddata , there entries there are ordered differently in the original/parsed version.

**Comment by EikeDehling** [comment]
This gist is a bit easier to read:

https://gist.github.com/EikeDehling/fc1289cc443b7acdc3f4

The issue is under the key `posting.properties.body.fields._text_.fielddata` : Ordering is different for the original/parsed mapping.

**Comment by bleskes** [comment]
@EikeDehling thx for that. It's accurate. The problem lies in the way the field data settings are rendered:

https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/index/mapper/core/AbstractFieldMapper.java#L756

```
builder.field("fielddata", (Map) fieldDataType.getSettings().getAsMap());
```

The order of the keys in that map is arbitrary (practically). It may be different between master and nodes causing this endless loop.

To work around this, you can set `indices.cluster.send_refresh_mapping` to false (requires node restart). This will disable the sending of mapping refresh instructions. You must remember to remove this settings before you upgrade to the next ES version, which will have a fix for this.

**Comment by bleskes** [comment]
@EikeDehling do you run on Java8 by any chance? (wondering to better understand how frequently this can happen)

**Comment by EikeDehling** [comment]
We're running Java7, 1.7.0_45

Thanks for the tip about settings.

I also found that line of code indeed, i'll try and make a patch/test.

**Comment by bleskes** [comment]
Cool. If you wait an hour or two, I’ll probably make a PR with a fix.

**Comment by EikeDehling** [comment]
This is my proposed patch+unit test, happy to compare to what you're producing. Sorry, i'm not that handy with github/PR's yet.

https://gist.github.com/EikeDehling/2e34a78a54de646b71ca

Any chance there will also be a 1.4 release with a fix?

**Comment by wkoot** [comment]
@bleskes You said that the `indices.cluster.send_refresh_mapping` requires node restart, what would the effect be if you only have a few (say half of) the nodes which have this setting set to false?

**Comment by bleskes** [comment]
Then the other half might still send refresh mapping to the master. You need it on all data nodes. But you can do a rolling restart, one by one.

**Comment by EikeDehling** [comment]
I am trying this fix in our staging environment, i'll let you know if that fixes the issue.

https://github.com/EikeDehling/elasticsearch/commit/cc79d71bbc4d55cb12a50df2acc67ca6ba4ac5dc

**Comment by bleskes** [comment]
@EikeDehling looks good can you make a PR ? see https://www.elastic.co/contributing-to-elasticsearch . Also it would be great if you simplify the test and add random keys (but we can iterate on the PR).

**Comment by EikeDehling** [comment]
I made a PR, and afterwards signed the contributor license, i hope that's ok.

I randomized the test and simplified a bit, happy to hear suggestions for improvements.
