### ISSUE TITLE
Attachment search not working in Elasticsearch 1.5.0 if search string contains more than three characters

### ISSUE THREAD

**Issue by rhdip** [elastic/elasticsearch#10313]
I am trying to search for a given string in the content of the file. Say I have a file abc.docx and it contains the word "shark" in it. If I search for "sha", it returns the file abc.docx. However, if I search for "shar", it does not return that file i.e it seems to process only 3 character search strings while doing content search. I checked this in the latest version(1.5.0) and version 1.4.3 as well and it din't work either. This seems to be working in Elasticsearch 1.4.2. Please let me know if you need further inputs on this.

**Comment by dadoonet** [comment]
When you write "attachment search", do you mean that you are using the mapper attachment plugin or is it something else?
Can you post what is your mapping and how does a document which is supposed to match actually look like?

**Comment by rhdip** [comment]
Yes I am using the mapper-attachments plugin. The file I am trying to search can be any file word, excel etc. 

I am providing the C# code. The UpdateIndex() method indexes the file name and its contents and the Search() method searches within the indexes.

The mapper class:

    public class AttachmentES
    {
        /// <summary>
        /// Index for Attachments table
        /// </summary>    
       [ElasticProperty(Index = FieldIndexOption.NotAnalyzed)]
       public ICollection<string> title { get; internal set; }
    
       [ElasticProperty(Index = FieldIndexOption.NotAnalyzed)]
       public string name { get; internal set; }
    
       [ElasticProperty(Index = FieldIndexOption.NotAnalyzed)]
       public ICollection<string> text { get; set; }
    
       [ElasticProperty(Index = FieldIndexOption.NotAnalyzed)]
       public string content { get; internal set; }
    
       public string Id { get; internal set; }
 
       [ElasticProperty(Type = Nest.FieldType.Attachment, Store = false, TermVector = Nest.TermVectorOption.WithPositionsOffsets)]
       public ESAttachment File { get; set; }
    }

The UpdateIndex method:

    public void UpdateIndex(int attachmentID)
    {
        //get the attachment details from database
        var atta = from a in dbES.GetAttachmentES(attachmentID).ToList()
                   select new AttachmentES
                   {
                       name = a.FileName,                      
                       Id = a.AttachmentID,                     
                   };

        AttachmentES objAttachmentES = new AttachmentES();
        objAttachmentES = atta.FirstOrDefault();

        client.CreateIndex("attachment", c => c.AddMapping<AttachmentES>(m => m.MapFromAttributes()));

        setting.SetDefaultIndex("attachment");
        foreach (AttachmentES itm in atta)
        {
            
            int id;
            id = Convert.ToInt32(itm.Id.Split('_')[0]);
            var rootPath = (CommonClass.AttachmentRootPath());


            if (string.IsNullOrEmpty(itm.name) == false)
            {
                string filePath = rootPath + "\\" + id;// +new FileInfo(itm.name).Extension;


                var attachment = new ESAttachment();

                string fileExt = Path.GetExtension(itm.name);

                if (File.Exists(filePath))
                    attachment._content = Convert.ToBase64String(File.ReadAllBytes(filePath));

                else if (File.Exists(filePath + fileExt))
                    attachment._content = Convert.ToBase64String(File.ReadAllBytes(filePath + new FileInfo(itm.name).Extension));

                switch (new FileInfo(itm.name).Extension)
                {
                    case ".txt":
                        attachment._content_type = "text/plain";
                        break;
                    case ".doc":
                        attachment._content_type = "application/msword";
                        break;
                    case ".docx":
                        attachment._content_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
                        break;
                    case ".xls":
                        attachment._content_type = "application/vnd.ms-excel";
                        break;
                    case ".xlsx":
                        attachment._content_type = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                        break;
                    case ".ppt":
                        attachment._content_type = "application/vnd.ms-powerpoint";
                        break;
                    case ".pptx":
                        attachment._content_type = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
                        break;
                    case ".pdf":
                        attachment._content_type = "application/pdf";
                        break;

                    //Images
                    case ".png":
                        attachment._content_type = "image/png";
                        break;
                    case ".jpeg":
                    case ".jpg":
                        attachment._content_type = "image/jpeg";
                        break;
                    case ".bmp":
                        attachment._content_type = "image/bmp";
                        break;
                    case ".gif":
                        attachment._content_type = "image/gif";
                        break;

                    //Videos
                    case ".wmv":
                        attachment._content_type = "video/x-ms-wmv";
                        break;
                    case ".avi":
                        attachment._content_type = "video/x-msvideo";
                        break;
                    case ".flv":
                        attachment._content_type = "video/x-flv";
                        break;
                    case ".mp4":
                        attachment._content_type = "video/mp4";
                        break;


                    //zip
                    case ".zip":
                        attachment._content_type = "application/zip";
                        break;

                    //xml
                    case ".xml":
                        attachment._content_type = "application/xml";
                        break;
                }

                attachment._name = itm.name;
                itm.File = attachment;
                client.Index<AttachmentES>(itm);
            }
        }
    }

The Search method:

    public List<ESSearchResult> Search(string searchString, int userId = 0)
        {
        List<ESSearchResult> lstIDs = new List<ESSearchResult>();
        ESSearchResult objItem = new ESSearchResult();

        string ElasticSearchPath = ConfigurationManager.AppSettings["ElasticSearchURL"].ToString();
        Uri o = new Uri(ElasticSearchPath);
        setting = new ConnectionSettings(o);
        client = new ElasticClient(setting);

        setting.SetDefaultIndex("attachment");

        string q1 = "*" + searchString + "*";

        var result12 = client.Search<AttachmentES>(body1 =>
                     body1.Index("attachment").Query(query12 =>
     query12.QueryString(qs1 => qs1.Query(q1))
     ).Fields("id"));

        List<string> lst = (from p in result12.FieldSelections
                            select p.FieldValues(item => item.Id).ElementAt(0).ToString()).ToList();

        List<String> lstAttachments = new List<String>();
        foreach (var i in lst)
        {                        
            lstAttachments.Add(i);            
        }

        objItem = new ESSearchResult();
        objItem.ObjectEntity = Enums.ESEntity.AttachmentES;
        objItem.ObjectRowIDs = lstAttachments.Distinct().ToList<string>();


        lstIDs.Add(objItem);

        return lstIDs;
    }

**Comment by dadoonet** [comment]
As far as I understand your code and mapping, you are using default analyzer for mapper attachment sub fields.
It means that if you index `shark`, you won't be able to find it if you search for `sha` term because there are obviously different.

You could define another analyzer for your attachment field though I have no idea on how you can do it with Nest. May be @Mpdreamz has an idea here.

Here is a link to the documentation which shows you how to do it using REST API: https://github.com/elastic/elasticsearch-mapper-attachments#using-mapper-attachments

May be you could use a edge n gram tokenizer. But note that it will generate a lot of sub tokens so it will consume more disk space.

The fact that `sha` matches is because I think you somehow have `sha` somewhere in your text. I don't think it's related to elasticsearch version 1.4.2. From the top of my head, I don't think also about a change in mapper attachment plugin which could cause that.

Closing as I don't see any issue here.
Feel free to reopen if you think it is or open an issue in mapper attachment project itself.

**Comment by rhdip** [comment]
When I try to index using "**client.Index(itm);**" I get the following error:

"System.Net.WebException was caught
  HResult=-2146233079
  Message=The operation has timed out
  Source=Elasticsearch.Net
  StackTrace:
       at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.ReturnStreamOrVoidResponse[T](TransportRequestState`1 requestState, ElasticsearchResponse`1 streamResponse)
       at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.CoordinateRequest[T](TransportRequestState`1 requestState, Int32 maxRetries, Int32 retried, Boolean& aliveResponse)
       at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.DoRequest[T](TransportRequestState`1 requestState)
       at Elasticsearch.Net.Connection.RequestHandlers.RequestHandler.Request[T](TransportRequestState`1 requestState, Object data)
       at Elasticsearch.Net.Connection.Transport.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters)
       at Elasticsearch.Net.ElasticsearchClient.DoRequest[T](String method, String path, Object data, IRequestParameters requestParameters)
       at Elasticsearch.Net.ElasticsearchClient.IndexPut[T](String index, String type, String id, Object body, Func`2 requestParameters)
       at Nest.RawDispatch.IndexDispatch[T](ElasticsearchPathInfo`1 pathInfo, Object body)
       at Nest.ElasticClient.<>c__DisplayClass671`1.<Index>b__675(ElasticsearchPathInfo`1 p, IndexDescriptor`1 d)
       at Nest.ElasticClient.Dispatch[D,Q,R](D descriptor, Func`3 dispatch)
       at Nest.ElasticClient.Index[T](T object, Func`2 indexSelector)
       at EmailNotificationLibrary.SOLRSearch.RefreshElasticSearchindex(String connectionString, Int32 communityID)"

This happens when I install the service ElasticSearch 1.5.0. But when I revert to ElasticSearch 1.4.2, the same line of code works fine.
