### ISSUE TITLE
BlobStoreCacheMaintenanceService.PeriodicMaintenanceTask should not hold a reference to a SearchResponse

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#103245]
From the discussion in https://github.com/elastic/elasticsearch/pull/103118 and motivated by the fact that `SearchResponse` will be ref-counted soon. `BlobStoreCacheMaintenanceService.PeriodicMaintenanceTask` currently holds a reference to a `SearchResponse` in a field. 
This seems unnecessary and can be refactored to make it so that the search response is only held in a local variable, removing the need for tricky ref-counting on it -> remove that reference to resolve this issue.

**Comment by DaveCTurner** [comment]
#103383 resolves this
