### ISSUE TITLE
exclude._ip transient cluster setting not working in ES 1.4 or 1.5

### ISSUE THREAD

**Issue by dhaworth** [elastic/elasticsearch#10321]
We use the exclude._ip cluster setting to push data from nodes when updating our cluster and this doesn't seem to be working in ES 1.4 or 1.5. This is what our cluster settings look like, but shards on the node with the excluded ip do not get pushed from the node:
```json
{
    persistent: { },
    transient: {
        cluster: {
            routing: {
                allocation: {
                    exclude: {
                        _ip: "x.x.x.x"
                    }
                }
            }
        }
    }
}
```

**Comment by clintongormley** [comment]
Hi @dhaworth 

Are you sure that your shards have somewhere to go?  Try using the cluster reroute API with explain to understand why your shards are not being moved.

**Comment by clintongormley** [comment]
Any more info?

**Comment by dhaworth** [comment]
Apologies for the delay. I currently have a 3 node cluster in our staging environment where all nodes are both master and data nodes. If I exclude one of the nodes, the shards on that node should get pushed to the other two, but they aren't.

This is the explanation I get from the cluster reroute API, which seems like it may be suspect, but I'm not exactly sure how to interpret it.

```json
"explanations" : [ {
  "command" : "move",
  "parameters" : {
    "index" : "decide",
    "shard" : 0,
    "from_node" : "i-xxxxxxxx",
    "to_node" : "i-yyyyyyyy"
  },
  "decisions" : [ {
    "decider" : "move_allocation_command",
    "decision" : "NO",
    "explanation" : "shard [decide][0] not found"
  } ]
} ]
```

Let me know if you need additional info. Thanks.

**Comment by clintongormley** [comment]
It seems it is not finding shard zero of index `decide` on the `from_node`.  Check the location of your shards with:

    GET _cluster/state/routing_table/decide

**Comment by dhaworth** [comment]
That's interesting because I don't have an index named `decide` on this cluster, or any other cluster I've had this problem on. That routing table api call returns this:

```json
{
	cluster_name: "Analytics15",
	routing_table: {
		indices: { }
	},
	routing_nodes: {
		unassigned: [ ],
		nodes: { }
	},
	allocations: [ ]
}
```
I don't see the word `decide` anywhere in my elasticsearch.yml or in `GET _cluster/state`. I do have the following plugins installed in case they may somehow be at fault:
* kopf
* HQ
* bigdesk
* kibana (which isn't technically a plugin anymore, but I do have installed on the same instance)

Any thoughts on where this may be coming from?

**Comment by clintongormley** [comment]
Could you paste the output of the cluster-reroute command that you issue? (assuming that the output is still the same?)

**Comment by dhaworth** [comment]
Ugh, sorry. That `decide` index thing was my fault. I tried it with an actual index and node and got the following:
```json
"explanations" : [ {
  "command" : "move",
  "parameters" : {
    "index" : "analytics-2014-01",
    "shard" : 4,
    "from_node" : "i-xxxxxxxx",
    "to_node" : "i-yyyyyyyy"
  },
  "decisions" : [ {
    "decider" : "same_shard",
    "decision" : "YES",
    "explanation" : "shard is not allocated to same node or host"
  }, {
    "decider" : "filter",
    "decision" : "YES",
    "explanation" : "node passes include/exclude/require filters"
  }, {
    "decider" : "replica_after_primary_active",
    "decision" : "YES",
    "explanation" : "shard is primary"
  }, {
    "decider" : "throttling",
    "decision" : "YES",
    "explanation" : "below shard recovery limit of [2]"
  }, {
    "decider" : "enable",
    "decision" : "YES",
    "explanation" : "allocation disabling is ignored"
  }, {
    "decider" : "disable",
    "decision" : "YES",
    "explanation" : "allocation disabling is ignored"
  }, {
    "decider" : "awareness",
    "decision" : "YES",
    "explanation" : "no allocation awareness enabled"
  }, {
    "decider" : "shards_limit",
    "decision" : "YES",
    "explanation" : "total shard limit disabled: [-1] <= 0"
  }, {
    "decider" : "node_version",
    "decision" : "YES",
    "explanation" : "target node version [1.5.0] is same or newer than source node version [1.5.0]"
  }, {
    "decider" : "disk_threshold",
    "decision" : "YES",
    "explanation" : "enough disk for shard on node, free: [138.7gb]"
  }, {
    "decider" : "snapshot_in_progress",
    "decision" : "YES",
    "explanation" : "no snapshots are currently running"
  } ]
```
The ip address of the `to_node` in this case is excluded:
```json
{
	persistent: { },
	transient: {
		cluster: {
			routing: {
				allocation: {
					exclude: {
						_ip: "y.y.y.y"
					}
				}
			}
		}
	}
}
```

**Comment by clintongormley** [comment]
It says:

    {
        "decider" : "filter",
        "decision" : "YES",
        "explanation" : "node passes include/exclude/require filters"
      }, 

which makes me think that the IP you're using is not the same as the IP returned by `getHostAddress()` (see https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodeFilters.java#L73). This may not be the same as the bind or publish address.  Could you check for this?

**Comment by dhaworth** [comment]
It looks like you're right. We recently switched from Amazon Linux (CentOS) to Ubuntu and it looks like the ip address of every node according to ES is now 127.0.1.1. This certainly explains the exclude not working. It looks like I have a configuration issue, either in `/etc/hosts` or with ES itself.

If you know a quick fix for this I'd appreciate any advice, otherwise I'll figure it out on my own. Thanks for helping me track this down.

**Comment by clintongormley** [comment]
I don't know of a quick trick, but glad we could get to the bottom of this.  thanks for reporting back
