### ISSUE TITLE
token_count does not seem to work with the path_hierarchy tokenizer

### ISSUE THREAD

**Issue by HayDegha0917** [elastic/elasticsearch#103366]
### Elasticsearch Version

7.10.2

### Java Version

_bundled_

### OS Version

Linux

### Problem Description

When using the path_hierarchy tokenizer on a path-like document field, the tokenizer works. However, creating a field of type `token_count` does not work; the value of that field is always `1`, no matter how many levels there are in the path.

We were hoping to use this functionality to answer questions such as: What are the documents that are one level below the documents with `ocs_path.tree` = `/ods` (see the example below for context). Without the ability to query the token count, we have to use regular expressions, and that is stressing out the CPU.

### Steps to Reproduce

Follow the stripped down test case.

```
DELETE my-index-000001

PUT my-index-000001
{
  "mappings": {
    "properties": {
      "ocs_path": {
        "type": "keyword",
        "fields": {
          "tree": {
            "type": "text",
            "analyzer": "dir_paths",
            "fielddata": true
          },
          "level": {
            "type": "token_count",
            "analyzer": "dir_paths"
          }
        }
      }
    }
  },
  "settings": {
    "analysis": {
      "normalizer": {
        "ocs_std_normalizer": {
          "filter": [
            "lowercase",
            "asciifolding"
          ],
          "type": "custom",
          "char_filter": []
        }
      },
      "analyzer": {
        "dir_paths": {
          "tokenizer": "path_hierarchy",
          "delimiter": "/"
        }
      }
    }
  }
}

GET my-index-000001/_mapping

PUT my-index-000001/_doc/1
{ "ocs_path": "/ods" }

PUT my-index-000001/_doc/2
{ "ocs_path": "/ods/surface" }

GET my-index-000001/_search
{
  "query": {
    "match": {
      "ocs_path.level": "2"
    }
  }, 
  "fields": [
    "*"
    ]
}

GET my-index-000001/_search
{
  "query": {
    "match": {
      "ocs_path.tree": "/ods"
    }
  }, 
  "fields": [
    "*"
    ]
}
```

The first query always returns 0 hits, even though it should return one. The second query works as expected.

Note that just listing everything

```
GET my-index-000001/_search
{
  "fields": [
    "*"
    ]
}
```

does not list all the parsed path elements, which seems odd.

### Logs (if relevant)

_N/A_

**Comment by pxsalehi** [comment]
Thank you for reporting this @HayDegha0917. `7.10` is not supported. Do you see the same issue on 7.17 or 8.x?

**Comment by cbuescher** [comment]
The issue here most likely is that the "path_hierarchy" tokenizer stacks all generated tokens in the same token position on the stream, as can be verified by
```
POST /my-index-000001/_analyze
{
  "field" : "ocs_path.tree",
  "text" : "/ods/surface"
}

---

{
  "tokens": [
    {
      "token": "/ods",
      "start_offset": 0,
      "end_offset": 4,
      "type": "word",
      "position": 0
    },
    {
      "token": "/ods/surface",
      "start_offset": 0,
      "end_offset": 12,
      "type": "word",
      "position": 0
    }
  ]
}
```

That behavior is intended, or at least changing it would be a breaking change. The "token_length" field type on the other hand seems to count different token positions only. So I don't see how you could use the two in the intended way together at the moment.

I'll mark this as an enhancement request but from what I see so far this has always been the behavior and should not be considered a bug.

**Comment by benwtrent** [comment]
This behavior is intended and any change here would break that behavior. A different analyzer than path_hierarchy would need to be done to get the token count for paths.
