### ISSUE TITLE
Logging: Allow to change log level of single node all the time

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#10335]
In order to improve debug capabilities, we should allow for changing the node level of a single node all the time, regardless of its state. Reason for this is, that it is impossible to increase logging, in case the node is not part of the cluster, which makes it hard to debug network issues/outages.

The the Cluster Update Settings API only works if the node is joined into a cluster.

Not sure about the right solution here, but could be
- Parse the cluster update settings API and apply logging settings locally all the time?
- Have an own endpoint?
- Support files?

**Comment by javanna** [comment]
Hey @spinscale by "if the node is not part of a cluster" you mean that the node doesn't have a master, thus we would return a master not discovered exception?

**Comment by spinscale** [comment]
@javanna yes, think of a network segregation of the single node, which returns in a "master not discovered" error when running the cluster update settings API

**Comment by javanna** [comment]
@spinscale why can't we restart the node then to change log settings then? The node doesn't do anything in such situation. Maybe there are other usecases for this, but in general I wonder if it's really needed. Marking for discussion.

**Comment by spinscale** [comment]
restarting means loosing the current state which could be debugged and analyzed further with more logging output.. if restarting solves the problem, that is good, but the possibility for further debugging should remain in that state IMO

**Comment by javanna** [comment]
I see your point...I was just assuming that restarting wouldn't fix the issue. I think having a more concrete example here would help. I bet you are referring to #10337 ?

**Comment by spinscale** [comment]
@javanna exactly, intended for cases like that. But totally up for discussion, IMO it would be useful

**Comment by dakrone** [comment]
What about implementing this feature: #1990? We already have the infrastructure for it, and then if one node needed to have the log level changed you could edit `logging.yml` and that particular node would pick it up without incrementing the cluster state.

**Comment by ppf2** [comment]
This is helpful not just for troubleshooting the networking use cases Alex mentioned.  Imaging debugging query execution where the query is isolated to a specific index and will only hit a shard on a specific node, it will be helpful to be able to *dynamically* enable debug/trace loggers for just this one node without having to turn it on for all nodes.

**Comment by jasontedor** [comment]
Enabling dynamic configuration reloading requires granting additional permissions to Log4j. I have not seen convincing feedback that this is a needed feature worth granting these additional permission. For now, I will close this issue but we can reconsider under a new issue based on compelling feedback.
