### ISSUE TITLE
Elasticsearch inner_hits query results in ArrayOutOfBoundsException

### ISSUE THREAD

**Issue by mariusdw** [elastic/elasticsearch#10334]
Hi! Please have a look at the following. Elastic is throwing an ArrayOutOfBoundsException when requesting inner_hits in my search query. The query works fine if inner_hits is not included. I feel this is a bug in elasticsearch. To  reproduce:

<pre><code>curl -XPOST 'http://localhost:9200/twitter'

curl -XPOST 'http://localhost:9200/twitter/_mapping/tweet' -d '
{
    "tweet": {
        "properties": {
            "comments": {
                "properties": {
                    "messages": {
                        "type": "nested",
                        "properties": {
                            "message": {
                                "type" : "string", 
                                "index": "not_analyzed"
                            }   
                        }
                    } 
                }
            }
        }
    }
}'

curl -XPOST 'http://localhost:9200/twitter/tweet' -d '
{
    "comments": {
        "messages": [
            {"message": "Nice website"},
            {"message": "Worst ever"}
        ]
    }
}'

curl -XGET 'http://localhost:9200/twitter/tweet/_search' -d '
{
    "query": {
        "nested": {
            "path": "comments.messages",
            "query": {
                "match": {"comments.messages.message": "Nice website"}
            },
            "inner_hits" : {}
        }
    }
}'

Response:

{"took":54,"timed_out":false,"_shards":{"total":5,"successful":4,"failed":1,"failures":[{"index":"twitter","shard":4,"status":500,"reason":"ArrayIndexOutOfBoundsException[-1]"}]},"hits":{"total":1,"max_score":1.4054651,"hits":[]}}

</code></pre>

Should the document not have been returned with the "Nice website" comment in the inner_hits array?

**Comment by martijnvg** [comment]
@mariusdw This is a bug. Elasticsearch mistakes the `comments` to be a nested object field and in your example it is just an object field.

This error will be fixed, but your mapping design (an object field that has a nested object field) is raise a question. Elasticsearch indexes the `messages` json objects in a special way so that it can be used by nested query, nested sorting, inner hits etc. But the parent field is an object field and no special indexing happens there, so the nested features only work on the `messages` nested level. Is there a special reason why you chose this? It only makes sense if you have a single comment per field, otherwise I sugegst that you change the `comments` field to be of type `nested` too.

**Comment by mariusdw** [comment]
Hi Martijn. Thanks for your reply. The example was just to reproduce the issue that I am experiencing with my real data structure. I kind of modified the example given in the elastic documentation to achieve this and maybe in the process of trying to simplify, used an example that isn't "practical" :)

Maybe I should rather explain my real data structure. In our system, we store configuration for various hardware devices. There are two levels of settings that can be configured: 
1. Individual settings - settings that apply to an individual device only.
2. Group settings - settings that apply to all devices unless overridden by an individual setting.

Each configuration server reports these settings (together with some other data) to a central server that stores it as JSON documents in elasticsearch. We then do interesting things like check which percentage of devices that has a certain setting is online etc.

As there will only ever be one "group settings" for all devices of a certain type, I have decided to store this as a simple singular object inside my document. The individual settings for each device is then stored inside this single object as nested documents. 

Looking at your answer I think a simple workaround for me for now would be to change the "group settings" to also be a nested document.

**Comment by martijnvg** [comment]
@mariusdw That decision to use object field makes perfect sense. When PR #10353 gets in inner hits will work again with your mapping. 

Changing the group settings to nested field will make it work for now, but does increase memory usage (due the fact that you have a nested `nested` field). I suggest that you move back to object field when 1.5.1 gets out.
