### ISSUE TITLE
Possible bug with recovery and gateway.expected_nodes after process restart on ES 1.4.4

### ISSUE THREAD

**Issue by mbarrin** [elastic/elasticsearch#10340]
Hi,

We are running `Elasticsearch` `1.4.4` on `Java(TM) SE Runtime Environment (build 1.7.0_60-b19)`

We have a cluster with 15 nodes: 3 master, 3 client, 9 data.

All the config files have:

```yaml
gateway.expected_nodes: 15
```

Based on the reading of my documentation this should actually be 12, as expected nodes only counts `master` and `data` nodes. So in our case it should never be hitting expected nodes. As we would only have 12 total for the sake of this setting.

So when we restart a `data` node process, the cluster should be at 11 or 14 of the expected nodes. Either way less than 15.

The documentation states that: `Setting gateway.expected_nodes also defaults gateway.recovery_after_time to 5m`. And we don't define a value for this in our config file

So if I am not mistaken when we reboot a node it should never hit the 15 expected nodes and it should wait 5 minutes for recovery. However what we are noticing is that reallocation of the shards is happening immediately.

eg. the moment data1 stops, its shards are being being assigned to other nodes in the cluster, it is not waiting for 5 minutes, or for the expected number of nodes.

I believe this is a bug and thought I should submit.

**Comment by bleskes** [comment]
You are correct in saying that expected nodes only relates to data + master nodes. I think the source of the confusing is that it also *only* holds for the initial cluster forming after a full cluster restart or an outage. In those cases the master waits until it sees enough nodes to start assigning shards.

For a single node restart, I believe you expect something like delaying the re-assignment of a shard for a couple of minutes with the hope the node will come back. I think there is an issue for it somewhere but can't find it now. If you confirm I'll dig it up and/or open another issue.

**Comment by mbarrin** [comment]
Ah thanks for the clarification. I assume disabling shard allocation for the purpose of the reboot is the best idea then?

**Comment by bleskes** [comment]
it's a controlled reboot yes. See http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cluster.html#shards-allocation .

Let me know if we can close this...

**Comment by mbarrin** [comment]
Yes I will close this issue.
