### ISSUE TITLE
Decrease master only node's connections

### ISSUE THREAD

**Issue by vsop-479** [elastic/elasticsearch#103486]
### Description

If master node is not a data node, and never used for handling client's requests (not a coordinate node). I think there is no need to create `BULK`, maybe even `REG` connections for it.

**Comment by DaveCTurner** [comment]
Thanks for the suggestion @vsop-479. The elected master node does various auxiliary tasks which require `REG` and `BULK` connections today even without handling client requests, and sometimes users may need to send client requests to a dedicated master to troubleshoot a faulty cluster. It would make the system significantly more complicated, and harder to use, if we did this, and the benefits of this change seem almost nonexistent. I'm closing this issue to indicate that we won't be pursuing this idea.
