### ISSUE TITLE
[CI] MlWithSecurityUserRoleIT.test {yaml=ml/text_expansion_search/Test weighted tokens search} failing 

### ISSUE THREAD

**Issue by pxsalehi** [elastic/elasticsearch#103442]
### CI Link

https://buildkite.com/elastic/elasticsearch-pull-request/builds/4617#018c6843-2107-447e-b533-f0007b73bb38

### Repro line

./gradlew ':x-pack:plugin:ml:qa:ml-with-security:yamlRestTest' --tests "org.elasticsearch.smoketest.MlWithSecurityUserRoleIT.test {yaml=ml/text_expansion_search/Test weighted tokens search}" -Dtests.seed=98DCE01D04EFCB17 -Dtests.locale=en -Dtests.timezone=Europe/Lisbon -Druntime.java=21

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure excerpt

```

org.elasticsearch.smoketest.MlWithSecurityUserRoleIT > test {yaml=ml/text_expansion_search/Test weighted tokens search} FAILED
--
  | java.lang.AssertionError:
  | Expected: ((a string containing "action [cluster:monitor/xpack/ml" or a string containing "action [cluster:admin/xpack/ml") or a string containing "action [cluster:admin/ingest")
  | but: was "Failure at [ml/text_expansion_search:231]: \nExpected: \"the octopus comforter smells\"\n     but: was \"the octopus comforter is leaking\""
  | at __randomizedtesting.SeedInfo.seed([98DCE01D04EFCB17:1088DFC7AA13A6EF]:0)
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  | at org.junit.Assert.assertThat(Assert.java:956)
  | at org.junit.Assert.assertThat(Assert.java:923)
  | at org.elasticsearch.smoketest.MlWithSecurityUserRoleIT.test(MlWithSecurityUserRoleIT.java:57)


```

**Comment by pxsalehi** [comment]
This ended up OOM-ing the CI pod/machine. Based on previous similar OOM messages, my understanding is that this is possible due to large log outputs that might result from the failure. But I am not 100% sure about this.
```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"
```

**Comment by pxsalehi** [comment]
(I just realized that the title of the PR linked above where this failure happened seemed terribly related to an OOM! But that PR doesn't change the memory usage of the nodes.)

**Comment by droberts195** [comment]
Changing to `low-risk` based on diagnosis.

**Comment by kderusso** [comment]
This should be resolved with merged PR
