### ISSUE TITLE
Date formatting error when doing descending sort on empty epoch_millis date field

### ISSUE THREAD

**Issue by vishalgoel2** [elastic/elasticsearch#103489]
### Elasticsearch Version

8.11.3

### Java Version

_bundled_

### OS Version

Linux 69d007f8c352 6.4.16-linuxkit #1 SMP PREEMPT Thu Nov 16 10:49:20 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Summary
Encountering a date formatting issue in Elasticsearch 8.x.x when performing a search with sorting the documents in descending order based on the `date` type field with the `epoch_millis` format

### Expected Result
The search results should be returned without errors, and the documents should be sorted by the `date` field in descending order.

### Actual Result
Encountering a date_time_exception with the reason `Field EpochMillis cannot be printed as the value -9223372036854775808 cannot be negative according to the SignStyle`

### Additional Information
- This issue is reproducible consistently.
- The date mapping is configured with the `epoch_millis` format.
- There should be at least one document with an empty date field to trigger the date_time_exception.
- The error occurs when attempting to perform a search with sorting by date in descending order.
- This issue is not present in Elasticsearch version 7.x.x, and sorting by date in descending order works as expected in the earlier version.

### Steps to Reproduce

1. Create an index with a date field mapping using the epoch_millis format
    ```bash
    curl -X PUT "http://localhost:64780/event" -H 'Content-Type: application/json' -d '
    {
      "mappings": {
        "properties": {
          "id": {
            "type": "keyword"
          },
          "date": {
            "type": "date",
            "format": "epoch_millis"
          }
        }
      }
    }'
    ```

2. Populate the index with sample data using the Bulk API
    ```bash
    curl -X POST "http://localhost:64780/event/_bulk" -H "Content-Type: application/x-ndjson" --data-binary @- <<EOF
    {"index":{"_id":"1"}}
    {"id":"1","date":1702578895}
    {"index":{"_id":"2"}}
    {"id":"2","date":1702578895}
    {"index":{"_id":"3"}}
    {"id":"3","date":1702578895}
    {"index":{"_id":"4"}}
    {"id":"4","date":1702578895}
    {"index":{"_id":"5"}}
    {"id":"5","date":1702578895}
    {"index":{"_id":"6"}}
    {"id":"6","date":1702578895}
    {"index":{"_id":"7"}}
    {"id":"7","date":1702578895}
    {"index":{"_id":"8"}}
    {"id":"8","date":1702578895}
    {"index":{"_id":"9"}}
    {"id":"9","date":1702578895}
    {"index":{"_id":"10"}}
    {"id":"10"}
    EOF
    ```

3. Attempt to perform a search with sorting by date in descending order
    ```bash
    curl -X GET "http://localhost:64780/event/_search?sort=date:desc" -H 'Content-Type: application/json'
    ```
   Response
   ```bash
   {"error":{"root_cause":[{"type":"date_time_exception","reason":"Field EpochMillis cannot be printed as the value -9223372036854775808 cannot be negative according to the SignStyle"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"event","node":"3PjSjabrRgqTQrWNZG4GyQ","reason":{"type":"date_time_exception","reason":"Field EpochMillis cannot be printed as the value -9223372036854775808 cannot be negative according to the SignStyle"}}],"caused_by":{"type":"date_time_exception","reason":"Field EpochMillis cannot be printed as the value -9223372036854775808 cannot be negative according to the SignStyle","caused_by":{"type":"date_time_exception","reason":"Field EpochMillis cannot be printed as the value -9223372036854775808 cannot be negative according to the SignStyle"}}},"status":500}
```

**Comment by ghostspiders** [comment]
This is a bug, use the format "strict_date_optional_time||epoch_millis" to avoid this error.

**Comment by mptraa** [comment]
> This is a bug, use the format "strict_date_optional_time||epoch_millis" to avoid this error.

Hello, I have tried the suggested workaround with Elasticsearch versions 8.10.4, 8.13.1 and 8.13.2. 
I'm getting the following error:

```json
{
  "error": {
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "failed to parse date field [-9223372036854775808] with format [strict_date_optional_time||epoch_millis]: [failed to parse date field [-9223372036854775808] with format [strict_date_optional_time||epoch_millis]]"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "test",
        "node": "test-node",
        "reason": {
          "type": "parse_exception",
          "reason": "failed to parse date field [-9223372036854775808] with format [strict_date_optional_time||epoch_millis]: [failed to parse date field [-9223372036854775808] with format [strict_date_optional_time||epoch_millis]]",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "failed to parse date field [-9223372036854775808] with format [strict_date_optional_time||epoch_millis]",
            "caused_by": {
              "type": "date_time_parse_exception",
              "reason": "date_time_parse_exception: Failed to parse with all enclosed parsers"
            }
          }
        }
      }
    ]
  },
  "status": 400
}
```

Is there any other workaround for this issue?

**Comment by benwtrent** [comment]
Its auto-parsing as a year. I don't know how else we can provide a fix for this other than the mapping indicates it needs to be strict. 

Closing as its a mapping configuration issue.
