### ISSUE TITLE
Merging mappings with `subobjects: false` can result in invalid mappings

### ISSUE THREAD

**Issue by felixbarny** [elastic/elasticsearch#103497]
### Elasticsearch Version

8.11

### Java Version

_bundled_

### OS Version

macOS 14.2

### Problem Description

I found a way to corrupt the mappings using `subobjects: false`. The reason is that ES is only validating that there must be no object mappers within in an object that's configured with `subobjects: false` while parsing mappings:

https://github.com/elastic/elasticsearch/blob/fb5c74475b1526302453a72677af2ec23ddbfc64/server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java#L312-L320

However, it's possible to create an invalid mapping using two distinct mapping updates that are valid on their own but invalid when the mappings are merged.

This invalid mapping merge is caught in testing with this assertion that re-parses the merged mappings:

https://github.com/elastic/elasticsearch/blob/fb5c74475b1526302453a72677af2ec23ddbfc64/server/src/main/java/org/elasticsearch/index/mapper/MapperService.java#L526

Since assertions are disabled in production, it's possible to create an invalid mapping.

To fix this, we could enable the assertion in production, too. Or, maybe a better way would be to catch the error scenario earlier, during mapping merge.

In these cases, we could check if we're trying to add an `ObjectMapper` even though subobjects are disabled:

https://github.com/elastic/elasticsearch/blob/fb5c74475b1526302453a72677af2ec23ddbfc64/server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java#L546-L549

### Steps to Reproduce

```
PUT test
{
  "mappings": {
    "properties": {
      "parent": {
        "type": "object",
        "subobjects": false
      }
    }
  }
}

PUT test/_mapping
{
  "properties": {
    "parent.child.grandchild": {
      "type": "keyword"
    }
  }
}
```

```
# POST test/_search 503 Service Unavailable
{
  "error": {
    "root_cause": [
      {
        "type": "no_shard_available_action_exception",
        "reason": null
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "test",
        "node": null,
        "reason": {
          "type": "no_shard_available_action_exception",
          "reason": null
        }
      }
    ]
  },
  "status": 503
}
# GET test/_mapping 200 OK
{
  "test": {
    "mappings": {
      "properties": {
        "parent": {
          "subobjects": false,
          "properties": {
            "child": {
              "properties": {
                "grandchild": {
                  "type": "keyword"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by ghostspiders** [comment]
i a beginner with Elasticsearch, I have tested the modifications in the screenshot and they work. Is this modification reasonable?
![微信图片_20240203220321](https://github.com/elastic/elasticsearch/assets/30502753/97289c4a-389d-411d-b449-d5157885abba)
@felixbarny
