### ISSUE TITLE
Provide a query profiling api

### ISSUE THREAD

**Issue by kamaradclimber** [elastic/elasticsearch#10348]
It would be useful to get a query profiling api to help users understand which part of the query/filter/aggregation takes time.

Context
--------
When preparing queries that will be run frequently, it is hard to predict query performance on large datasets.
Causes I can think of:
- filters caches already created or not
- data being indexed (invalidating caches at each merge?)
- field cardinality
- custom parameters defined in mapping (e.g precision for longs)
- query/filter operand orders

Current solution, involves testing each query/filter part (each operand) independently (at least) 3 times to warm caches, with and without data being written. This gives hints but does not help building complex queries/filters/aggregations. 

Suggestion
----------------
Having a query profiling api could help users find:
- whether query/filter is slow or fast compared to fetch
- whether a filter is properly cached or if cache has to be created
- whether order has impact on query time
- if given filter/query operand improves the query time (or not)
- if times is spent on "shard phase"  or on "merge phase" (maybe not using the correct terms)

It seems to have been asked [before][1].
Several databases provide this kind of api: [sql server][4] (through execution plan), [solr][2] (debug=timing/query), [mongodb][3]

I understand than ES query model is different from solr, but I think there is a possible improvement to help testing thoughfully instead of following the numerous advices ("term" query is faster than xxx, "filter x" is better because it can be cached) that we currently find on the net.

I'd be happy to provide more details on my use case if necessary (target is to store time series in ES).

What do you think?
[1]: http://elasticsearch-users.115913.n3.nabble.com/Tracing-query-execution-td3648329.html
[2]: https://wiki.apache.org/solr/CommonQueryParameters
[3]: http://docs.mongodb.org/manual/reference/method/cursor.explain/
[4]: https://technet.microsoft.com/en-us/library/ms178071(v=sql.105).aspx

**Comment by kamaradclimber** [comment]
cc @dpanth3r

**Comment by dakrone** [comment]
@kamaradclimber I believe @polyfractal is currently working on this

**Comment by polyfractal** [comment]
@kamaradclimber Absolutely agree with you!  This information is very important, and we don't have a good way to expose (or even collect it) today.  

I have a WIP PR here:  https://github.com/elastic/elasticsearch/pull/6699

It was stalled for a while due to technical reasons, but we've recently rebooted it with a new approach (details here https://github.com/elastic/elasticsearch/pull/6699#issuecomment-85234304).

**Comment by kamaradclimber** [comment]
@polyfractal this is a very great step towards what I am looking for, I'd really like this to be merged.

Improvements I can think of once your patch is in master:
- display if the query used a cache or not
- display merge time (time to merge the results of subqueries/filters)

**Comment by clintongormley** [comment]
Closing in favour of #6699
