### ISSUE TITLE
Highlight the not correct matching keyword

### ISSUE THREAD

**Issue by ahyh** [elastic/elasticsearch#103495]
### Description

Hello, everyone, I meet a Highlight query issue and I am not sure ElasticSearch has already support it or not.
And this is my question: 
I hava a BoolQueryBuilder parsed from ("a" and "b") or ("c"), and I want to highlight the keyword if matched

`
GET /test_user/_search
{
  "query": {
    "bool": {
      "should": [
        {
          "bool": {
            "must": [
              {
                "match_phrase": {
                  "desc": {
                    "query": "a"
                  }
                }
              },
              {
                "match_phrase": {
                  "desc": {
                    "query": "b"
                  }
                }
              }
            ]
          }
        },
        {
          "bool": {
            "should": [
              {
                "match_phrase": {
                  "desc": {
                    "query": "c"
                  }
                }
              }
            ],
            "minimum_should_match": "1"
          }
        }
      ],
      "minimum_should_match": "1"
    }
  },
  "highlight": {
    "fields": {
      "desc": {}
    }
  }
}
`

this bool query hit a document, and the index contains "a" and "c", but highlight "a" and "c", but this hit is matched by "c", not ("a" and "b"), I only want to highlight "c".
I searched in stackoverflow, maybe this is my question: https://stackoverflow.com/questions/44621694/elasticsearch-highlight-with-multiple-queries-not-work-as-expected.
Do ElasticSearch support it now? or ElasticSearch has plan to support it later?

**Comment by cbuescher** [comment]
Hi @ahyh! Your question is better suited to the support forums over at [discuss.elastic.co](https://discuss.elastic.co/). We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by ahyh** [comment]
Thank you very much @cbuescher
