### ISSUE TITLE
ESQL: "show functions" always generate non-nullable fields

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#103558]
### Description

For a query with filter on `description`, the filter is removed from the logical plan by the `FoldNull` rule that sees the field as always non-nullable.

Example:
`show functions | eval a = true | sort a | where description is not null`

has the following plan:

```
TopN[[Order[a{r}#344,ASC,LAST]],500[INTEGER]]
\_Eval[[true[BOOLEAN] AS a]]
  \_ShowFunctions[]
```

Marking this one as bug, because I don't see why values of `show functions` cannot be `null`. Nevertheless, low impact or not even a bug, reporting it for awareness.

**Comment by luigidellaquila** [comment]
This does not produce anymore. 
Now the plan for `meta functions | eval a = true | sort a | where description is not null` (`SHOW` is now `META`) is

```
[2024-07-04T14:20:25,998][DEBUG][o.e.x.e.s.EsqlSession    ] [runTask-0] Optimized logicalPlan plan:
TopN[[Order[a{r}#35,ASC,LAST]],1000[INTEGER]]
\_Eval[[true[BOOLEAN] AS a]]
  \_Filter[ISNOTNULL(description{r}#30)]
    \_MetaFunctions[]


[2024-07-04T14:20:26,002][DEBUG][o.e.x.e.s.EsqlSession    ] [runTask-0] Physical plan:
TopNExec[[Order[a{r}#35,ASC,LAST]],1000[INTEGER],null]
\_EvalExec[[true[BOOLEAN] AS a]]
  \_FilterExec[ISNOTNULL(description{r}#30)]
    \_ShowExec[[name{r}#24, synopsis{r}#25, argNames{r}#26, argTypes{r}#27, argDescriptions{r}#28, returnType{r}#29, descript
```

Same thing if we filter by any of the other fields.

Closing
