### ISSUE TITLE
Support geo_shape in ES|QL

### ISSUE THREAD

**Issue by craigtaverner** [elastic/elasticsearch#103586]
### Description

In https://github.com/elastic/elasticsearch/issues/103585 we added support for `geo_point` in ES|QL. The next most obvious type to support is `geo_shape`: In addition we should support functions for this:

* `to_geoshape(string)` to take a WKT string and convert it to a `geo_shape`
* `to_string(geo_shape)` should take a `geo_shape` and convert it to WKT

**Comment by iverase** [comment]
This is mostly blocked by https://github.com/elastic/elasticsearch/issues/103751. We need to know how the field is going to be consumed because we want to load different data structures depending on that.
