### ISSUE TITLE
[CI] SamlAuthenticationIT classMethod failing

### ISSUE THREAD

**Issue by edsavage** [elastic/elasticsearch#103525]
**Build scan:**
https://gradle-enterprise.elastic.co/s/m43xadboic2sk/tests/:x-pack:qa:saml-idp-tests:javaRestTest/org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT

**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT#classMethod`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('classMethod'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
com.carrotsearch.randomizedtesting.ThreadLeakError: 1 thread leaked from SUITE scope at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT: 
   1) Thread[id=84, name=ForkJoinPool.commonPool-worker-2, state=TIMED_WAITING, group=TGRP-SamlAuthenticationIT]
        at java.base/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:449)
        at java.base/java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1891)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1809)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

  at __randomizedtesting.SeedInfo.seed([8F7933F85B352C6]:0)

```

**Comment by slobodanadamovic** [comment]
This failure seems to be caused by the recent change to idp-fixture: https://github.com/elastic/elasticsearch/issues/103320

Rene's comment suggest that this is a known issue which we need to ignore for now, see https://github.com/elastic/elasticsearch/pull/103320/files#r1424129050.

In this case the failure reported leakage of `ForkJoinPool.commonPool-worker-2` thread.
 I've raised a [PR](https://github.com/elastic/elasticsearch/pull/103577) to ignore all threads which start with `ForkJoinPool.commonPool-worker-` and not just `ForkJoinPool.commonPool-worker-1`.

**Comment by slobodanadamovic** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/103440
