### ISSUE TITLE
[GEO] add bounding box optimization for geo_polygon filter

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#10356]
Currently, geo_distance filters have a built-in bounding box optimization, configurable through the optimize_bbox option. It would be great if geo_polygon filters also had this optimization, as it can be quite expensive to check every point against the query polygon.

**Comment by jtibshirani** [comment]
If the request sounds reasonable, would you mind if I took a stab at this? I would plan to stick with the current behavior for interpreting orientation (since #5968 is still open).

**Comment by nknize** [comment]
@jtibshirani Absolutely. This is a good issue for getting started if you have not already contributed. Thanks for being sensitive to #5968. Just a heads up (although you shouldn't have this problem if you're mirroring the optimization from GeoDistanceFilter) be careful not to use any JTS or S4J functionality in the GeoPolygonFilter logic. This filter is used for ```geo_point``` types and does not require those dependencies. That's the only gotcha holding up the PR for #5968.

**Comment by clintongormley** [comment]
@nknize I'm assuming this is no longer required given the new geopoints?  Can this be closed, along with the linked PR?

**Comment by nknize** [comment]
Closed the PR. Closing issue in favor of #14537
