### ISSUE TITLE
[ES|QL] is_finite and is_infinite only accepts double types

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch#103684]
### Elasticsearch Version

8.13

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

The ES|QL math functions `is_finite` and `is_infinite` only accepts `double` values and errors on `integer` or other types:

<img width="1097" alt="Screenshot 2023-12-22 at 12 49 37" src="https://github.com/elastic/elasticsearch/assets/924948/d40ffe01-0d56-4c64-b931-c8f875c4514c">
<img width="1102" alt="Screenshot 2023-12-22 at 12 49 30" src="https://github.com/elastic/elasticsearch/assets/924948/8e44682d-79c5-4778-8246-1e3a4573fddb">

Also, this thing is not documented: https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-functions-operators.html#esql-is_infinite

### Steps to Reproduce

See above

**Comment by dej611** [comment]
Also applies to `is_nan`

**Comment by bpintea** [comment]
What would be the use case for this? One has a field of numeric type, but not knowing exactly its type? 
Otherwise the integers would all return `true`, `false`, `false` respectively, no need to invoke a function.

> Also, this thing is not documented: https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-functions-operators.html#esql-is_infinite

Good point, labeled.

**Comment by dej611** [comment]
You mean it is working for field of numeric type but not for literal numeric types? If so, this is a general thing which is not documented anywhere. It would be useful to know whether a function supports a numeric type as field or as literal in general.

**Comment by bpintea** [comment]
No, no, sorry. These functions only work for floating point types (only doubles in our case). I was only asking why you'd like them to work on integer types.

**Comment by nik9000** [comment]
I believe we're removing these functions because we're turning `NaN` into `null`, right @not-napoleon ?

**Comment by dej611** [comment]
I see. 

> No, no, sorry. These functions only work for floating point types (only doubles in our case), both expressions and literals (`row x = 1. | eval is_infinite(x/0), is_finite(0.)`). I was only asking why you'd like them to work on integer types. Edit: I guess that'd be for convenience? Since smth like `| eval is_finite(0)` will complain, indeed (you'd have to write smth like `| eval is_finite(to_dbl(0))`, which _is_ a bit cumbersome).

Exactly, for convenience. If removed are they going to have any deprecation grace period, or just dropped?

**Comment by bpintea** [comment]
> we're turning NaN into null

Indeed, we've decided to turn the infinities and NaN to `null`.

**Comment by bpintea** [comment]
> If removed are they going to have any deprecation grace period, or just dropped?

I guess there could be a grace period, but once the infinities and NaN turning into `null` is going to be in place, there won't be a way to test/use them (there's no infinite/NaN literal and the operations - like `1./0` - will just return `null`; and a warning).

**Comment by not-napoleon** [comment]
> I believe we're removing these functions

That is correct.  Json does not have a way to serialize `NaN` or infinite double values, and as such we don't support them anywhere else in Elasticsearch.  We decided a while ago to convert all such values into `null` in ES|QL, and that's on the list of supportability tasks that need to be done before GA.  

> If removed are they going to have any deprecation grace period, or just dropped?

That's a good question.  My preference would be to not have a grace period, and definitely not follow the full normal deprecation process (I don't want to live with these until 9.0). I suppose we could leave them with "Returns null if the input is null, otherwise returns false" (or true, in the case of `is_finite`).

**Comment by dej611** [comment]
Ok, so to sum up the decisions:
* `NaN` values are going to be converted into `null`
* `is_nan`, `is_finite `, `is_infinite ` are going to be dropped

What will happen to existing queries using such functions? I would expect a grace period where these 3 functions will support `null` as valid input, reporting a warning message, meanwhile the consumers migrate their queries.

**Comment by dej611** [comment]
No, I didn't assume `null` was an implicit type. If that is that's ok.
