### ISSUE TITLE
Docker Secrets

### ISSUE THREAD

**Issue by bremoi** [elastic/elasticsearch#103629]
### Description

Hi,

I'm able to use secrets with Elasticsearch through the "ELASTIC_PASSWORD_FILE" variable, but I didn't find the equivalent for "ELASTICSEARCH_PASSWORD" variable in Kibana container.
So, to improve security, it would be interesting to add "ELASTICSEARCH_PASSWORD_FILE".

Thanks a lot

**Comment by mayya-sharipova** [comment]
@bremoi Thank you for filing the issue. If the issue is related to Kibana, can you please open in the Kibana repo: https://github.com/elastic/kibana.

**Comment by bremoi** [comment]
Hi @mayya-sharipova,

Sure, [done](https://github.com/elastic/kibana/issues/173832).
