### ISSUE TITLE
ESQL:  Introduce aggregate functions returning the distinct values in a group

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#103600]
### Description

Certain queries need to know the range values inside a group, in particular the unique (distinct) values that appeared within each group.
Consider the following `values()` aggregate function:
`stats values = values() by g`
For each group g, values would return the distinct values as multi-field, e.g.:
```
g | values
a | [1,2,3,4]
b | [10,11,12,13]
...
```

**Comment by felix-lessoer** [comment]
+1

**Comment by mick-lue** [comment]
+1, pretty much essential for Security Use Cases in my opinion

**Comment by ofirEdi** [comment]
+1 In many occasions it is required to get all values of a field/s matching for certain aggregation (group by) and not only mathematical aggregate functions.
At the moment we implement this by aggregating fields with count and then on our service we send for each result search query with terms aggregation with all the fields from group by as filters.
