### ISSUE TITLE
ComputeService should not acquire and hold all SearchContexts at once

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#103666]
If an ESQL query hits a thousand shards, then the ComputeService acquires and holds all search contexts. This can use a massive number of file descriptors and memory. I think we should rework the ComputeService to handle these incrementally.

**Comment by nik9000** [comment]
I had a look right before Christmas and it's a little tangled. There's two tricky things I've found so far:
1. We use the IndexReader for a bunch of optimizations very very early.
2. We have no good way for the Lucene sources to signal that they've produced the last block for shard and no way to pick that signal up in the values reader operator and ordinals agg operator.

So far, those are two things I can think of. I think we really do want *something* around delaying building the infrastructure for field loading until we see a document from a segment. We may even want this "start/stop" segment signaling too.

I wonder if we might limit the number of shards we process in a single "go" on each local node. Like, maybe only grab 64 shards at a time? Like, grab the first index, dump all of it's shards in a list, grab the second one, if the list is <=64 then dump it's shards in too. Something like that. Then we're only optimizing on 64 shards at a time. And we can't get as good with the work stealing. But that feels simpler.

Not that we shouldn't do this too. We totally should.

**Comment by dnhatn** [comment]
> We have no good way for the Lucene sources to signal that they've produced the last block for shard and no way to pick that signal up in the values reader operator and ordinals agg operator.

In each driver, we execute shard by shard sequentially with any data_partitioning. This means that the current shard is considered finished once the operator encounters a new shard.

**Comment by nik9000** [comment]
Right. So we only need one shard's worth of field loading infrastructure open at a time. I'm not sure that's true after a topn, but I think it's mostly true.

**Comment by dnhatn** [comment]
Ah, that's a good point. I missed that.

**Comment by dnhatn** [comment]
> I'm not sure that's true after a topn, but I think it's mostly true.

I think the proposal to batch 64 shards also encounters this problem

**Comment by nik9000** [comment]
> I think the proposal to batch 64 shards also encounters this problem

If we'd do 64 shards we'd plan each batch separately. But, yeah, it'd hit the same problem.

I think it's ok - we can limit the number of open shards for fetching. The way you propose should work ok. It's just not as clean as "there is only one".

I've spent today running down a vector leak but I'll have a look at the values reading stuff tomorrow.

**Comment by dnhatn** [comment]
@nik9000 I have thought a bit more about this issue. I believe your proposal to batch 64 shards at a time is the best solution. Since we don't currently perform a reduction per node, the change should be pretty contained in the DataNodeRequestHandler. I don't think we need to worry about the pauses between these batches. Even if we consider performing reduction per node in the future, there's no need to perform the reduction for all these batches, as the performance doesn't matter much in this context. I also think one of us should work on this. WDYT?

**Comment by nik9000** [comment]
Sorry, I hadn't noticed your comment! I did look at not batching, but, we really do rely on these things being open. It'd take a bit of surgery to change. But batching is, like you say, contained.

Yeah, I think if it's "just" the batching then, yeah, one of us can handle it. And should do it soon.

**Comment by dnhatn** [comment]
Thanks Nik! I have opened #104832.
