### ISSUE TITLE
Keep elasticsearch core small

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#10368]
Over time we accumulated a lot of features in elasticsearch core which have different status. Some of them are very important building blocks while other ones are only useful for esoteric use-cases or have known issues. Keeping the core small is important for a variety of reasons so maybe we should consider creating a new elasticsearch-extra plugin, with a best-effort only backward compatibility policy, which would contain such esoteric features.

Some ideas of what could move from core to such a plugin:
 - the `token_count` field mapper (esoteric)
 - the `murmur3` field mapper (not really needed)
 - the `fuzzy_like_this` query (super costly + esoteric)
 - the `top_children` query (questionable approximation)
 - the `significant_terms` aggregation (scalability issues on large data)
 - the `scripted_metric` aggregation (useful for experimentation but hard to use and slow)

**Comment by s1monw** [comment]
+100 I just read the title :)

**Comment by rmuir** [comment]
+1

**Comment by mikemccand** [comment]
+1

**Comment by kimchy** [comment]
Talking specifically on the list, I think we can simply remove `top_children`  and `fuzzy_like_this`, I don't think they are that helpful and would be a shame to even have a plugin that tries to maintain them.

I think we should keep `sig_terms` in core, its an important aggregation that needs to meet the level of "core".

`token_count` and `murmur` I think its ok to move it to a plugin, I think its interesting to know how many people use the murmur option in conjunction with cardinality, if a lot, then it might be a core level feature?

**Comment by s1monw** [comment]
IMO this is less about what but rather about a direction IMO. just my $0.05

**Comment by clintongormley** [comment]
These changes have been made. Closing
