### ISSUE TITLE
Ability to change scripts directory

### ISSUE THREAD

**Issue by electrical** [elastic/elasticsearch#10369]
At the moment the scripts directory is hard coded to `scriptsDirectory = new File(env.configFile(), "scripts");` but it would be handy to make this configurable.
Main reason is that with the Puppet module we allow multiple instances, and it would be handy that all instances on a single node can share the same directory where the scripts are located.

**Comment by javanna** [comment]
This seems like a duplicate of #6766 ?

**Comment by electrical** [comment]
@javanna oops you are right. must have overlooked it. Closing this one. thanks!
