### ISSUE TITLE
Not an Issue, just looking for some valuable feedbacks and help...

### ISSUE THREAD

**Issue by dev-shubh** [elastic/elasticsearch#10364]
I wish to do the following operation using elasticsearch 1.4 and Kibana 4:
1. Aggregate field x with time for every 10 mins
2. Aggregate field y with time for every 10 mins
3. Take a ratio of the two fields i.e  Ratio (aggregated field x)/(aggregated field y)

Can this be done using scripted scripts in Scripted fields in Kibana 4....

**Comment by jpountz** [comment]
Please use the mailing list to ask questions, we use Github issues only for bugs and feature requests.
