### ISSUE TITLE
Kibana appears to break-down when I use scripted fields.

### ISSUE THREAD

**Issue by dev-shubh** [elastic/elasticsearch#10362]
I am new to elasticsearch and Kibana. I was trying to use scripted fields in Kibana 4. 
![scripted_fileds](https://cloud.githubusercontent.com/assets/11183147/6936697/8dec0ebe-d872-11e4-9dae-731bac392fdc.png)
I tried some very simple arithmetic operations(division) on two fields in scripted fields and it worked just fine. Then I was trying to use aggregations under scripted fields script and my kibana 4 worked working. 
![kibana_error_snap](https://cloud.githubusercontent.com/assets/11183147/6936714/bab90a32-d872-11e4-8869-2c07dbd618d5.png)

Any help would be great. Also let me know if its possible to write script to do aggregation in scripted field script section.

**Comment by clintongormley** [comment]
Hi @dev-shubh 

I suggest you ask this on the kibana list instead.
