### ISSUE TITLE
Repeating errors every day:Connect reset by peer

### ISSUE THREAD

**Issue by YoungYoungYeha** [elastic/elasticsearch#103703]
### Elasticsearch Version

7.4.1and7.10.2

### Java Version

1.8

### OS Version

4.14.71-1.el7.centos.x86_64

### Problem Description

According to online posts, modifying the keepalive time to 3 minutes or 1 minute will still result in an error message。
The ES cluster uses kubernetes deployment.The keepsave of the data node machine is 300s, while the keepsave of the pod is 7200s。I have checked many blogs but cannot solve it. Please help me solve it

### Steps to Reproduce

The version of the jar package used is elasticsearch-reset-client 、 httpcore-nio:4.3、httpclient:4.5.12、 httpcore:4.4.13

### Logs (if relevant)

java.io.IOException: Connection reset by peer
at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:828)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:248)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1514)
at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1484)
at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1454)
at org.elasticsearch.client.RestHighLevelClient.index(RestHighLevelClient.java:871)

**Comment by DaveCTurner** [comment]
Thank you very much for your interest in Elasticsearch. Unfortunately the issue you have reported relates to Elasticsearch version 7.10.2 which is very old and has passed [end-of-life](https://www.elastic.co/support/eol). We will not investigate issues related to unsupported versions here on Github, so I am closing this to indicate that no action is needed from the Elasticsearch development team. It's possible that you will find a volunteer to help you with this issue on the [community forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), but our strong recommendation would be to upgrade to a supported version of Elasticsearch as a matter of some urgency. If you can reproduce your issue on a supported version then please open a fresh bug report.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.
