### ISSUE TITLE
Missing repository breaks Stack monitoring

### ISSUE THREAD

**Issue by psanz-estc** [elastic/elasticsearch#103752]
### Elasticsearch Version

8.11

### Java Version

_bundled_

### OS Version

Rocky Linux 8.8

### Problem Description

ES nodes were not listed in the Nodes tab in Elasticsearch monitoring (using metricbeat)

![image](https://github.com/elastic/elasticsearch/assets/44199691/349cf086-4cd8-43aa-ba93-8daf2afe3bec)

There wasn't any evident error until we checked `node_stats` API call, which returned:

```
      {
        "type": "failed_node_exception",
        "reason": "Failed node [LpMeXt8VR66qc6kVsBGA0w]",
        "node_id": "LpMeXt8VR66qc6kVsBGA0w",
        "caused_by": {
          "type": "repository_exception",
          "reason": "[ESRepo] repository type [fs] failed to create on current node",
          "caused_by": {
            "type": "repository_exception",
            "reason": "[ESRepo] failed to create repository",
            "caused_by": {
              "type": "repository_exception",
              "reason": "[ESRepo] location [\\\\node01.net\\ESRepo] doesn't match any of the locations specified by path.repo because this setting is empty"
            }
          }
        }
      }
```

ESRepo repository shouldn't be there, and it seems it was causing the node_stats  call to "fail" and inadvertently, the Elastic Stack monitoring page to return an empty list

As soon as we removed this from "Stack Management \ Snapshot and Restore \ Repositories" the nodes under the "Nodes" tab showed up immediately

### Steps to Reproduce

Create/configure a FS repo with an empty `path.repo` defined
Check [node stats API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html) 
The API call will return a `failed_node_exception` due to `doesn't match any of the locations specified by path.repo because this setting is empty`
Elastic Stack monitoring won't show any of the nodes in the Node tab

**Comment by volodk85** [comment]
@psanz-estc may I know how you getting this?

>Create/configure a FS repo with an empty path.repo defined

According to the [code](https://github.com/elastic/elasticsearch/blob/362a7f0a958954a2c4d43d9d67c2d02a586db52e/server/src/main/java/org/elasticsearch/repositories/fs/FsRepository.java#L94-L117) fs path resolution is happening using `path.repo` settings regardless `absolute` or `relative` path is specified, meaning to define fs repo you have to set correct `path.repo` settings in the first place.

**Comment by ywangd** [comment]
Yeah, we need non-empty `path.repo` to create a repository. However, the error can happen when the node restarts with the `path.repo` setting removed or new node without `path.repo` setting joins the cluster. I wonder whether the original report is either of these cases?

**Comment by ywangd** [comment]
Closing this issue as detailed in the above message. Thanks for reporting.
