### ISSUE TITLE
Date format error when search last year data

### ISSUE THREAD

**Issue by cherrychen0825** [elastic/elasticsearch#103778]
### Elasticsearch Version

7.5.2

### Java Version

_bundled_

### OS Version

Linux bsa162 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

It's 2024.1.2.  
I search data of 2023.12. 31。 The result of 2023.12. 31 is wrong： the key is right(1703952000000，2023-12-31 00:00:00)， but the key_as_string is wrong(2024-12-31)。

### Steps to Reproduce

Query:
curl -XGET 'http://10.67.X.X:XX/XX-2023123*/_search?pretty' -H 'Content-Type:application/json' -d'{"query":{"bool":{"filter":[{"range":{"start_time":{"gt":1703606400000,"lte":1704167251155}}}]}},"track_total_hits":true,"aggs":{"group":{"date_histogram":{"field":"start_time","interval":"1d","time_zone":"+08:00","min_doc_count":0,"format":"YYYY-MM-dd"}}},"size":0}

Result:
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 2,
    "successful" : 2,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 238,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "group" : {
      "buckets" : [
        {
          "key_as_string" : "2023-12-30",
          "key" : 1703865600000,
          "doc_count" : 130
        },
        {
          "key_as_string" : "2024-12-31",
          "key" : 1703952000000,
          "doc_count" : 108
        }
      ]
    }
  }
}
![image](https://github.com/elastic/elasticsearch/assets/12975186/8eecca53-9365-457c-8961-231f9c0ebf5b)

**Comment by DaveCTurner** [comment]
Thank you very much for your interest in Elasticsearch. Unfortunately the issue you have reported relates to Elasticsearch version 7.5.2 which is very old and has passed [end-of-life](https://www.elastic.co/support/eol). We will not investigate issues related to unsupported versions here on Github, so I am closing this to indicate that no action is needed from the Elasticsearch development team. It's possible that you will find a volunteer to help you with this issue on the [community forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), but our strong recommendation would be to upgrade to a supported version of Elasticsearch as a matter of some urgency. If you can reproduce your issue on a supported version then please open a fresh bug report.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.
