### ISSUE TITLE
Provide a logger that reports a breakdown of the indexing time 

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#10379]
It will be helpful if we have a logger that can be set to DEBUG or TRACE level that reports a breakdown of the time spent on each step of an indexing request, eg. time spent indexing to primary, time spent indexing to replica, time spent in bulk/index queue (if applicable), etc..

**Comment by clintongormley** [comment]
This could be very heavy to have for every indexing request. Would it still be useful if it were implemented like the Profile API?  ie on a per request basis?

**Comment by GlenRSmith** [comment]
Agreed it would be heavy for every indexing request. Moreover, there would be diminishing return of value, I suspect, for profiling query after query after query. Better to be able to *sample* on a timed or counted basis.

A profile API - or perhaps a keyword arg, could facilitate that. Whatever the indexing agent is could be configured to post to this endpoint on a either the time or count periodic basis.

If you *really* want to profile every. single. document. then go for it.

Yeah, the API approach puts really nice granularity into the hands of the user.

It could conceivable accept some URL params to indicate desired verbosity or operational granularity (if such a thing is even feasible, breaking down further into the time spent in each analysis phase for that document, or, on another axis, breaking it down per field).

**Comment by jasontedor** [comment]
In almost three years we have seen no feedback from the community on this feature request. As such, I am going to close this issue. We can always reopen it or open a new based on compelling feedback.
