### ISSUE TITLE
New Index creation time increases with more and more indexes in the cluster.

### ISSUE THREAD

**Issue by ajaybhatnagar** [elastic/elasticsearch#10378]
I am trying to test index creation performance in the cluster. I noticed as total number of indexes increases in the cluster, creating a new index takes more and more time. (no data loading at all and no other activity in cluster other than new index creations).

First 1000 index created in  approx 10 minutes
Next 1000 index creation took close to 40 minutes and it keeps degrading. Resources on the nodes (master & data)  are not bottleneck.

Thanks
Ajay

**Comment by ajaybhatnagar** [comment]
ES version is 1.4.4, java  1.8.0_40

**Comment by jpountz** [comment]
Are you testing it purely for experimental purposes or is index creation time actually a bottleneck for your use-case? In the latter case can you explain why you need to create so many indices?

Managing thousands of indices is something that will raise issues for a variety of reasons, I'm afraid index creation time is only one of the symptoms. If you can, I would advise to model your data in such a way that you don't need so many indices.

**Comment by clintongormley** [comment]
No more info. Closing

**Comment by ubershmekel** [comment]
This may be affecting my project. It took me a week to finish indexing 400 indices and the remaining 100 seem to be taking much longer to create (~5 minutes per index at the start and ~10-30 minutes now). Why does the amount of existing indices affect new index creation? E.g. you wouldn't expect writing to a file to be slower based on the amount of folders on the drive (unless there's fragmentation which seems to be an .

Degraded search warm-up is perfectly reasonable, but creating the index I expected to perform consistently. Perhaps these limitations can be explicitly mentioned at

https://www.elastic.co/blog/found-sizing-elasticsearch
https://www.elastic.co/blog/performance-considerations-elasticsearch-indexing

Even the great answer here seems oblivious to this limitation http://stackoverflow.com/questions/14465668/elastic-search-multiple-indexes-vs-one-index-and-types-for-different-data-sets

**Comment by dadoonet** [comment]
@ubershmekel join us on discuss.elastic.co 

And provide more info about your setup (nodes, memory...)

**Comment by markwalkom** [comment]
FYI this is also at https://discuss.elastic.co/t/why-are-indices-slower-to-create-the-more-indices-you-have/29205
