### ISSUE TITLE
Provide a way to drop norms for already optimized/older indices

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#10383]
Here is a use case:

- There are a lot of optimized/older indices that are not getting written to (and no further deletions) but all of them have a great number of fields with norms enabled
- The user realized that they don't really need norms for these fields after the fact.

In order for norms to be dropped, a segment merge has to occur.  Currently, in order to force a segment merge for these indices (with just 1 segment), we can modify the index mapping to disable norms for these indices, add a dummy document with these fields (now with norms disabled), and optimize again.

It will be nice to provide a way to drop norms for these optimized indices without having to ingest a dummy document.  I think there was an attempt to provide a force option (https://github.com/elastic/elasticsearch/pull/5294) but was subsequently deprecated in 1.4 (http://www.elastic.co/guide/en/elasticsearch/reference/1.4/indices-optimize.html)

**Comment by rmuir** [comment]
I agree, this is too tricky and we should make it easy and not error-prone.

There are a couple possibilities (or combination of) we could use here with 2.0:
* ElasticSearchMergePolicy could check mappings and apply omitNorms to the FieldInfos it presents at merge, so there need not be any dummy document. It means the setting would kick in for a corresponding forceMerge, and also kick in even when indexing is happening, for fields that are "no longer being indexed to" .
* ElasticSearchDirectoryReader could also apply the same FilterCodecReader at read time when segments have norms but mappings has them turned off. This means you could issue a close/open index and the norms are disabled instantly (they are still on disk, but will not be loaded into RAM).
* We could try to fix/add back the force option in some way.
* (other simpler or more complicated solutions).

**Comment by mikemccand** [comment]
+1

I like the ESDirectoryReader solution?  Then, you don't even need merges to run to make the norms effectively go away?  (They would still be on disk, but that's OK: the real horror happens when they are loaded into RAM).

**Comment by jpountz** [comment]
+1 this sounds like a nice solution to me

**Comment by jpountz** [comment]
Norms are going to be disk-based as of Lucene 5.3 (probably Elasticsearch 2.1) soI'm wondering that being able to drop norms is not that useful anymore, and probably not worth the complexity?

**Comment by clintongormley** [comment]
Norms are now disk based. Closing

**Comment by ppf2** [comment]
You guys are awesome!
