### ISSUE TITLE
[CI] InternalEngineTests testConcurrentEngineClosed failing

### ISSUE THREAD

**Issue by luigidellaquila** [elastic/elasticsearch#103861]
**Build scan:**
https://gradle-enterprise.elastic.co/s/qzvswg7p64vra/tests/:server:test/org.elasticsearch.index.engine.InternalEngineTests/testConcurrentEngineClosed

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.index.engine.InternalEngineTests.testConcurrentEngineClosed" -Dtests.seed=F8DD0298C7176C72 -Dtests.locale=es-CO -Dtests.timezone=Universal -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.index.engine.InternalEngineTests#testConcurrentEngineClosed`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testConcurrentEngineClosed'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.index.engine.InternalEngineTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: (No message provided)

  at __randomizedtesting.SeedInfo.seed([F8DD0298C7176C72]:0)
  at org.elasticsearch.index.engine.InternalEngine.flushHoldingLock(InternalEngine.java:2174)
  at org.elasticsearch.index.engine.Engine.flushAndClose(Engine.java:1935)
  at org.elasticsearch.index.engine.InternalEngineTests$8.doRun(InternalEngineTests.java:3706)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by DaveCTurner** [comment]
This assertion was introduced in https://github.com/elastic/elasticsearch/pull/103871 but in fact it's bogus and would have been bogus before those changes too, so I'm calling this `low-risk`.
