### ISSUE TITLE
Filtering aggregation values

### ISSUE THREAD

**Issue by krueger** [elastic/elasticsearch#10386]
Hi,

in our project we need to filter the values of an aggregation. A possible solution is to use the filter param:

GET /sample/document/_search
{
  "aggs": {
    "value_facet": {
      "terms": {
        "field": "value_id",
        "include": "a|b"
      }}}}

I think a better way would be, to use a value param, like this:

GET /sample/document/_search
{
  "aggs": {
    "value_facet": {
      "terms": {
        "field": "value_id",
        "values": ["a", "b"]
      }}}}

to restrict the values. Can this be implemented or is there another possibility to implemented this?

Greetings,
Martin

**Comment by jpountz** [comment]
This is already supposed to work: if you supply an array of strings it will be interpreted as the list of values you are interested in but if you supply a string it will be interpreted as a regexp. The documentation mentions this but I agree it would be nice to make things clearer by also giving an example (PRs welcome ;-)).

**Comment by krueger** [comment]
Ok, thx for you answer. I used an old version of es, with the latest it works.
