### ISSUE TITLE
ES startup error: memory locking requested for elasticsearch process but memory is not locked

### ISSUE THREAD

**Issue by smallemployees** [elastic/elasticsearch#103885]
### Elasticsearch Version

6.8.20

### Java Version

_bundled_ 1.8

### OS Version

centos7.9

### Problem Description

ES startup error: memory locking requested for elasticsearch process but memory is not locked

### Steps to Reproduce

ES startup error

**Comment by DaveCTurner** [comment]
Thank you very much for your interest in Elasticsearch. Unfortunately the issue you have reported relates to Elasticsearch version 6.8.20 which is very old and has passed [end-of-life](https://www.elastic.co/support/eol). We will not investigate issues related to unsupported versions here on Github, so I am closing this to indicate that no action is needed from the Elasticsearch development team. It's possible that you will find a volunteer to help you with this issue on the [community forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), but our strong recommendation would be to upgrade to a supported version of Elasticsearch as a matter of some urgency. If you can reproduce your issue on a supported version then please open a fresh bug report.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.
