### ISSUE TITLE
The cluster keeps increasing unassigned_shards shards?

### ISSUE THREAD

**Issue by yang-bsft** [elastic/elasticsearch#10380]
We are running ES 1.4.2
Suddenly, we noticed that the cluster state became red last night, although all indexing, query, search are working fine.

The reason why the cluster became red but service is still running fine is that the ES cluster has the unassigned_shards kept increasing. We don't know where those shards are from and which index do those shards belong to?

Are we hitting a but in ES?

Can anyone at least help point out why ES keeps increasing number of shards?

Thanks

**Comment by yangou** [comment]
It turns out to be our issue. Please help close it.
