### ISSUE TITLE
ESQL functionality fails when creating a CSV (Share -> CSV Reports -> Generate csv)

### ISSUE THREAD

**Issue by victory-gin** [elastic/elasticsearch#103877]
### Description

My customer wrote an ESQL query within Kibana Discover that successfully produced the output he required from an Oracle database. The main issue relates to the data in the table on Discover and how that data is reproduced with a CSV (viewed in MS Excel). 
Customer used  a KEEP command on certain fields he wanted to maintain as columns in the data table, but since these reference rather long dot notation ECS fields, he used a RENAME command to make them easier to read. The CSV report emailed in a Watch came back with every renamed field correctly renamed as a column in Excel, but all values were - (dash symbol).
 
We then tested the CSV functionality directly within Discover with Share -> Generate CSV and got the same results. When customer commented out the RENAME, all the values were produced correctly, both on Generate CSV and the Watch email.
The biggest concern he had was that running any aggregations also failed to translate properly into a CSV. Customer would require the ability to run different aggregations and use those results to generate CSV reports. 

Customer tested this with a STATS distinct count for database IDs; in Discover this produced a data table with 3 rows that gave the correct distinct count. When he generated a CSV, this produced an Excel sheet with each database ID on its own line, and the null - (dash symbol) for the "count__" field's values.
@stratoula This is in reference to our discussion from the ESQL Slack channel.

**Comment by stratoula** [comment]
@victory-gin thanx. This is a kibana problem and we are tracking this here https://github.com/elastic/kibana/issues/173390 so I think we should close this.
