### ISSUE TITLE
The thread pool is full, causing task pile-up and write rejections

### ISSUE THREAD

**Issue by hubcomsix** [elastic/elasticsearch#103951]
### Elasticsearch Version

8.x

### Java Version

_bundled_

### OS Version

Centos 7.4

### Problem Description

The thread pool is full, causing task pile-up and write rejections 

### Steps to Reproduce

org.elasticsearch.common.util.concurrent.EsRejectedExecutionException:  
rejected execution of org.elasticsearch.common.util.concurrent.TimedRunnable@790ac6ff on 
QueueResizingEsThreadPoolExecutor 
[name = 15xxxxxxxxx132/search, queue capacity =1000, min queue capacity =1000,  max queue capacity =1000, 
frame size =2000, targeted response rate = 1s,  task execution EWMA=6.6ms, adjustment amount =50,  
org.elasticsearch.common.util.concurrent.QueueResizingEsThreadPoolExecutor@69e4b10 [Running, pool size =13, active threads =13, queued tasks =1000, completed tasks =445155395]

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
