### ISSUE TITLE
Failed to parse mapping: no handler for type [semantic_text] declared on field [semantic]

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#103925]
### CI Link

https://gradle-enterprise.elastic.co/s/gumq6rhprvp4s/tests/overview?outcome=FAILED

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

main

### Failure history

N/A

### Failure excerpt

Various variants of failures caused by:
```
org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping: No handler for type [semantic_text] declared on field [field]
```

**Comment by carlosdelest** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/103965
