### ISSUE TITLE
Explanation with null description causes NullPointerException in distributed query

### ISSUE THREAD

**Issue by mausch** [elastic/elasticsearch#10399]
I'm writing a custom score function that returns a deeply-nested Explanation object. When a description in one of the nested Explanations is null I get a NullPointerException from the node. This doesn't happen when I run things on a single node, so it's likely some issue with the serialization of Explanation objects.

**Comment by clintongormley** [comment]
Hi @mausch 

Any chance you can provide some simple code which replicates the problem?  Without more to go on, I doubt anybody will pick this one up...

thanks

**Comment by mausch** [comment]
Due to the nature of the issue unfortunately this is not easy to reproduce with some simple code.

From my point of view it means setting up a new plugin project with maven and so on, create a module class that registers a custom ScoreFunctionParser which in turn instantiates a custom ScoreFunction that returns an Explanation with a null description. And then run this on many instances of ES in a cluster and run a query with `"explain": true`. Sadly I can't afford to spend so much time on a non-blocking issue.

But perhaps someone with better knowledge of ES internals could directly unit-test the serialization of `Explanation` and see if that's really what's causing the `NullPointerException` I see.

**Comment by jpountz** [comment]
@mausch Indeed our serialization logic treats descriptions as non-null strings while you can create Lucene explanations with `null` descriptions. However an explanation with a `null` description feels useless to me, I'm tempted to consider that the bug is that the explanation API does not require the description field. Is there a reason why you don't set a description on your explanations?

**Comment by mausch** [comment]
I simply forgot to call `setDescription` on some `Explanation` instance and got this NullPointerException which was not helpful at all to diagnose the cause of the problem. That's why I'm reporting it, things like waste people's time.

If it was up to me I'd absolutely make `Explanation` immutable and check for null in the constructor. But I don't think you can change this by now, it seems like it would be a pretty important breaking change in Lucene. 

A less breaking change would be marking the no-arg constructor and setters with `@Deprecated` but I doubt people will go for even that.

Instead, ES could simply throw a more specific exception so that people at least don't have to guess what the problem is.

**Comment by jpountz** [comment]
> it would be a pretty important breaking change in Lucene.

In general we try to weigh the pros/cons of API breaks: breaking an API is unpleasant but leaving API traps is probably worse. I'll open an issue.

> Instead, ES could simply throw a more specific exception so that people at least don't have to guess what the problem is.

I can do that.

**Comment by mausch** [comment]
Cool, thanks!

**Comment by jpountz** [comment]
I opened https://issues.apache.org/jira/browse/LUCENE-6446 and #10689
