### ISSUE TITLE
search templates created with restapi   are not deleteing completely 

### ISSUE THREAD

**Issue by kumar007007** [elastic/elasticsearch#10397]
We created a search templates with rest api  will adds to .scripts index , when we delete the templete it says success and when we explore the index the  templete  won't appear .
  When we recreate the search template with same name  it will create , when we execute the template search it will take the old  deleted  template code . we  updated to latest version 1.5  from 1.4.
You can easily replicate this issue ween u created a template with some wrong syntax , and delete  that template and recreate with same name with valid syntax , then execute it wont work .  I tried to flush cache on that index reorganize too

**Comment by clintongormley** [comment]
@kumar007007 could you provide a simple curl recreation which demonstrates the issue please?

**Comment by kumar007007** [comment]
// new index 

POST testindex/test
{
  "searchtext": "dev1"
}

// creating template with  wrong type to create error 

POST _search/template/git01
{
    "query": {
                 "match_all": {
                       "searchtext": {
                              "query": "{{P_Keyword1}}",
                              "type": "oooophrase_prefix"
                                      }
                              }
              }
}


//   calling template  it should error ,  it will give error 

GET testindex/_search/template
{
 "template": {"id": "git01"}
,
"params": {
"P_Keyword": "dev"
}
}

//  fixing the template error by updating right type 
POST _search/template/git01
{
    "query": {
                 "match_all": {
                       "searchtext": {
                              "query": "{{P_Keyword1}}",
                              "type": "phrase_prefix"
                                      }
                              }
              }
}

//  fixing the template error by deleting  and recreating  template 
DELETE  _search/template/git01


POST _search/template/git01
{
    "query": {
                 "match_all": {
                       "searchtext": {
                              "query": "{{P_Keyword1}}",
                              "type": "phrase_prefix"
                                      }
                              }
              }
}
//  using template still will give error 

GET testindex/_search/template
{
 "template": {"id": "git01"}
,
"params": {
"P_Keyword": "dev"
}
}

**Comment by clintongormley** [comment]
Hi @kumar007007 

Your example didn't actually work, but it gave me enough to demonstrate the problem: existing templates never get reparsed, even when they are overwritten:

     # create test doc
    POST testindex/test
    {
      "searchtext": "dev1"
    }
    
     # Create bad template
    PUT _search/template/git01
    {
      "query": {
        "match": {
          "searchtext": {
            "query": "{{P_Keyword1}}",
            "type": "ooophrase_prefix"
          }
        }
      }
    }
    
     # Throws exception
    GET testindex/_search/template
    {
      "template": {
        "id": "git01"
      },
      "params": {
        "P_Keyword1": "dev"
      }
    }
    
     # Overwrite with correct template
    PUT _search/template/git01
    {
      "query": {
        "match": {
          "searchtext": {
            "query": "{{P_Keyword1}}",
            "type": "phrase_prefix"
          }
        }
      }
    }
    
     # Search fails with old error
    GET testindex/_search/template
    {
      "template": {
        "id": "git01"
      },
      "params": {
        "P_Keyword1": "dev"
      }
    }
    
     # Create template with new ID
    PUT _search/template/git02
    {
      "query": {
        "match": {
          "searchtext": {
            "query": "{{P_Keyword1}}",
            "type": "phrase_prefix"
          }
        }
      }
    }
    
     # Now it works correctly
    GET testindex/_search/template
    {
      "template": {
        "id": "git02"
      },
      "params": {
        "P_Keyword1": "dev"
      }
    }

**Comment by clintongormley** [comment]
@MaineC coule you look at this one too please?

**Comment by ericbernal** [comment]
i have the same issue.. forcing us to resort to only managing templates from file and not index.  
@MaineC show us some magic
