### ISSUE TITLE
es 1.5.0 count doesn't work

### ISSUE THREAD

**Issue by jeffreyji666** [elastic/elasticsearch#10392]
Here is my script:

    GET /engzo/topic/_search?pretty=true
    {
      "query": {
        "bool": {
          "must": {
            "term": {
              "isDeleted": false
            }
          },
          "should": [
            {
              "match": {
                "title": {
                  "query": "test",
                  "type": "boolean",
                  "operator": "AND"
                }
              }
            },
            {
              "match": {
                "body": {
                  "query": "test",
                  "type": "boolean",
                  "operator": "AND"
                }
              }
            },
            {
              "query_string": {
                "query": "test",
                "fields": [
                  "title",
                  "body"
                ]
              }
            }
          ]
        }
      }
    }

and I got this:

    {
      "took": 13,
      "timed_out": false,
      "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
      },
      "hits": {
        "total": 414736,
        "max_score": 14.740633,
        "hits": [
          {
            "_index": "engzo",
            "_type": "topic",
            "_id": "9566",
            "_score": 14.740633,
            "_source": {
              "topicId": 9566,
              "title": "test",
              "body": "test",
              "createdAt": "2014-03-03T08:03:26.000+08:00",
              "updatedAt": "2014-03-03T08:03:26.000+08:00",
              "replyCounts": 0,
              "starCounts": 0,
              "isDeleted": 0
            }
          },
          {
            "_index": "engzo",
            "_type": "topic",
            "_id": "106554",
            "_score": 14.740633,
            "_source": {
              "topicId": 106554,
              "title": "test",
              "body": "test",
              "createdAt": "2014-06-10T04:21:46.000+08:00",
              "updatedAt": "2014-07-01T10:04:05.000+08:00",
              "replyCounts": 0,
              "starCounts": 0,
              "isDeleted": 0
            }
          },
          {
            "_index": "engzo",
            "_type": "topic",
            "_id": "369577",
            "_score": 14.740633,
            "_source": {
              "topicId": 369577,
              "title": "Test",
              "body": "Test",
              "createdAt": "2014-11-06T11:38:28.000+08:00",
              "updatedAt": "2014-11-06T13:56:55.000+08:00",
              "replyCounts": 0,
              "starCounts": 0,
              "isDeleted": 0
            }
          },
          {
            "_index": "engzo",
            "_type": "topic",
            "_id": "401588",
            "_score": 14.740633,
            "_source": {
              "topicId": 401588,
              "title": "test",
              "body": "test",
              "createdAt": "2014-11-24T09:11:57.000+08:00",
              "updatedAt": "2014-11-24T09:11:57.000+08:00",
              "replyCounts": 0,
              "starCounts": 0,
              "isDeleted": 0
            }
          },
          {
            "_index": "engzo",
            "_type": "topic",
            "_id": "45838",
            "_score": 14.455909,
            "_source": {
              "topicId": 45838,
              "title": "test",
              "body": "test",
              "createdAt": "2014-04-28T12:49:04.000+08:00",
              "updatedAt": "2014-04-29T05:13:04.000+08:00",
              "replyCounts": 0,
              "starCounts": 0,
              "isDeleted": 0
            }
          },
          {
            "_index": "engzo",
            "_type": "topic",
            "_id": "99753",
            "_score": 14.455909,
            "_source": {
              "topicId": 99753,
              "title": "test",
              "body": "test",
              "createdAt": "2014-06-05T03:30:54.000+08:00",
              "updatedAt": "2014-08-17T05:39:08.000+08:00",
              "replyCounts": 0,
              "starCounts": 0,
              "isDeleted": 0
            }
          },
          {
            "_index": "engzo",
            "_type": "topic",
            "_id": "91185",
            "_score": 14.423123,
            "_source": {
              "topicId": 91185,
              "title": "test",
              "body": "test",
              "createdAt": "2014-05-28T13:41:30.000+08:00",
              "updatedAt": "2014-05-28T13:45:33.000+08:00",
              "replyCounts": 0,
              "starCounts": 0,
              "isDeleted": 0
            }
          },
          {
            "_index": "engzo",
            "_type": "topic",
            "_id": "281450",
            "_score": 14.423123,
            "_source": {
              "topicId": 281450,
              "title": "test",
              "body": "Test",
              "createdAt": "2014-09-04T10:35:50.000+08:00",
              "updatedAt": "2014-09-04T11:42:12.000+08:00",
              "replyCounts": 0,
              "starCounts": 0,
              "isDeleted": 0
            }
          },
          {
            "_index": "engzo",
            "_type": "topic",
            "_id": "35181",
            "_score": 14.368841,
            "_source": {
              "topicId": 35181,
              "title": "test",
              "body": "test",
              "createdAt": "2014-04-20T20:19:43.000+08:00",
              "updatedAt": "2014-04-20T20:19:43.000+08:00",
              "replyCounts": 0,
              "starCounts": 0,
              "isDeleted": 0
            }
          },
          {
            "_index": "engzo",
            "_type": "topic",
            "_id": "74362",
            "_score": 14.368841,
            "_source": {
              "topicId": 74362,
              "title": "test",
              "body": "test",
              "createdAt": "2014-05-16T08:48:20.000+08:00",
              "updatedAt": "2014-08-26T06:34:25.000+08:00",
              "replyCounts": 0,
              "starCounts": 0,
              "isDeleted": 0
            }
          }
        ]
      }
    }

but when I try to get the count by the following script:

    GET /engzo/topic/_count?pretty=true
    {
      "query": {
        "bool": {
          "must": {
            "term": {
              "isDeleted": false
            }
          },
          "should": [
            {
              "match": {
                "title": {
                  "query": "test",
                  "type": "boolean",
                  "operator": "AND"
                }
              }
            },
            {
              "match": {
                "body": {
                  "query": "test",
                  "type": "boolean",
                  "operator": "AND"
                }
              }
            },
            {
              "query_string": {
                "query": "test",
                "fields": [
                  "title",
                  "body"
                ]
              }
            }
          ]
        }
      }
    }

it said:

    GET /
    {
      "count": 414736,
      "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
      }
    }

actually It is the total number of the index type. Is this a bug?

**Comment by clintongormley** [comment]
The `count` matches the `hits.total` value returned from your search request.  So apparently that is the number of documents that your query matched.  The search request just returns the first 10 results by default.

**Comment by jeffreyji666** [comment]
so How could I get the count that meets up the search condition?

**Comment by clintongormley** [comment]
@jeffreyji666 search defaults to a `size` of 10, so if the count is greater than 10, use 10 instead...

Not sure why you would want to do that though

**Comment by jeffreyji666** [comment]
I mean I want to get the number of the record which meets the search condition, so I can do the pagination.

**Comment by clintongormley** [comment]
@jeffreyji666 that's what the `count` represents.  What do you think is wrong?

btw, deep pagination is problematic in a distributed system.  there's a good reason that google only returns 100 pages of results.

**Comment by jeffreyji666** [comment]
I got it wrong. I will close this issue. thanks.
