### ISSUE TITLE
MapperParsingException when indexing document

### ISSUE THREAD

**Issue by cashgl** [elastic/elasticsearch#10401]
I'm trying to index a document using the following procedure:
```java
byte[] source = myDocument;
final IndexResponse response =  client
        .prepareIndex(index, type, id)
        .setSource(source)
        .execute()
        .actionGet();
```
When I'm doing so, I get a `MapperParsingException` saying that it can't parse an input string within my document. However, when I attempt to index the exact document through a REST client with the Index API, it completes without any issue. It would be nice if I could use Elasticsearch's Java API to index my documents, but if there isn't a solution, I'll have to make a REST call.

**Comment by dadoonet** [comment]
Please ask questions like this on the mailing list and provide details about what you have in `source` field.
May be your `byte[]` is not correct?

try with a String first.
