### ISSUE TITLE
Repeatedly segfaults on Ubuntu 14.04

### ISSUE THREAD

**Issue by alexmorozov** [elastic/elasticsearch#10400]
Hi,
After upgrading our (super-tiny) instance from 0.90 to 1.5 ES has started to crash. Here are some of the java dump files: https://gist.github.com/alexmorozov/b49f1c8c755236d237b6
It crashes randomly, there`s no specific query that causes segfault.
Can it be a memory issue?
We run at default settings (max 1G heap), but we have only about 50 documents in the index (with many fields though).

**Comment by jpountz** [comment]
The crash happens while compiling a groovy script. Can you share the groovy script that you are using in your search request?

**Comment by alexmorozov** [comment]
Sure. The script is generated dynamically, here`s the common one: https://gist.github.com/alexmorozov/b4aa8aabc8df69731aab . Note that this script doesn`t crash the server alone, ES segfaults after many of such requests.
And I`m not sure it`s in Groovy, as far as we created it in the 0.90 (mvel) days.

**Comment by clintongormley** [comment]
No more feedback in 9 months. Closing
