### ISSUE TITLE
Enhancement: hint user on node version mismatch

### ISSUE THREAD

**Issue by faxm0dem** [elastic/elasticsearch#10403]
When comissioning new nodes with a lower ES version (_e.g._ 1.4.0 _vs._ 1.4.2), obviously only new shards get allocated to the new nodes, while older shards (using newer lucene version) never reallocate to new nodes. While this is fine, there should be a hint in the logs, something in the likes of:

```
[cluster.routing.allocation.decider] [somenode] old ES version detected [oE5QByo8RVSVqVDerxB-7A][comissionednode] existing shards will not be reassigned to this node"
```

Would have saved me some time today ;-)

**Comment by clintongormley** [comment]
@faxm0dem nice idea, but I'm not sure how doable it is.  The allocation decider makes lots and lots of decisions, which ones do we choose to log?

@dakrone what's your take on this?

**Comment by javanna** [comment]
@dakrone thoughts on this?

**Comment by dakrone** [comment]
I think this is something we could pursue, it'd be nice to tell people about version mismatches.

> The allocation decider makes lots and lots of decisions, which ones do we choose to log?

I don't think we should do this in the allocation decider, rather I think we should do this when the node joins via zen discover, log some sort of warning about node version mismatch. I think in all cases the mismatch should be short-lived (rolling restart, or a mistake), so it'd be good to let people know as soon as the nodes are joined.

Do you think this is something we should add to zen @ywelsch?

**Comment by ywelsch** [comment]
@dakrone I think that the allocation explain API in ES 5 should be sufficient for this purpose. We can extend the message that is given by the `NodeVersionAllocationDecider` to state the reason why we won't allow recovery from a new to an old-version node (currently it only states "target node version [%s] is older than source node version [%s]").
