### ISSUE TITLE
Inconsistent value types for node status/info

### ISSUE THREAD

**Issue by Cidan** [elastic/elasticsearch#10404]
When viewing the following URL, http://localhost:9200/_nodes/_local, queue sizes are not consistent in types, for example:
```
merge: {
type: "scaling",
min: 1,
max: 4,
keep_alive: "5m",
queue_size: -1
}
```

versus:

```
get: {
type: "fixed",
min: 8,
max: 8,
queue_size: "1k"
}
```

The queue_size value should always be an integer, fully expanded out, ie, 1000 and not "1k". This will make monitoring these queues much simpler.

**Comment by clintongormley** [comment]
+1
