### ISSUE TITLE
Rank_feature query should support sparse_vector field type

### ISSUE THREAD

**Issue by kderusso** [elastic/elasticsearch#104090]
The [rank_feature](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-rank-feature-query.html) query boosts relevance scores based on numeric values of `rank_feature` or `rank_features` fields. 

We should update this so it will also work with `sparse_vector` fields.

**Comment by benwtrent** [comment]
This is indeed interesting. I would hope we move sparse_vector further away from `rank_features` in the future. This could be done by adjusting how values are indexed, etc. and forcing us to have to support rank_feature queries could hamper that for very little gain.

What do you think @jpountz ?

**Comment by kderusso** [comment]
Closing this issue, as we decided to introduce a `sparse_vector` query instead.
