### ISSUE TITLE
Be lenient with "has_child" filter against a missing type

### ISSUE THREAD

**Issue by tuxpiper** [elastic/elasticsearch#10415]
Currently a search request or query containing a filter like:

```
       "has_child": {
          "type": "missingtype",
          "query": { "term": { "text": "yay" } }
       }
```

Will fail with a QueryParsingException ("No mapping for for type [missingtype]") if the mapping type it refers to is not defined.

I think (and propose) that it would be useful to be able to at least instruct ES to be lenient in that case, and just evaluate the filter to false.

I think this would make sense, moreover, it would be consistent with the behavior of search on a missing type, i.e. currently:

```
curl http://localhost:9200/my-index/missingtype/_search?q=sometext
```

Doesn't fail, it returns 0 hits, despite of "missingtype" being (obviously) missing.

Any reason why something similar shouldn't be done for the "has_child" filter?

--

Supporting use case:

We've got an app that indexes the full text of office documents that are attached to another type of entity, whose contents we also index in ES. We designed this as a parent-child relationship, indexing full text in a child type of the main entity type.

Currently, we are in the process of allowing end users to tweak their ES mappings, that means multiple (per user) parent mappings, each with their corresponding child mapping for indexed documents.

We would find it very clean and convenient to just create all these mappings lazily, and create the children type just when that user pushes an office document. The problem is that, unless we proactively make sure that the children types exist, our text search requests will break.

**Comment by clintongormley** [comment]
@martijnvg what's your take on this?

**Comment by martijnvg** [comment]
@tuxpiper I agree we should be able to be lenient towards a missing parent type.

@clintongormley The idea I had was adding a `_unmapped_fields` option to the search dsl. Which can have the: `ignore`, `warn` and `error` (default). This option shouldn't just apply for `has_child` and has_parent, but also `nested` and other queries rely on mapping settings.

This idea came from: https://github.com/elastic/elasticsearch/pull/9521#issuecomment-73956623

**Comment by tuxpiper** [comment]
That sounds good @martijnvg , having such option in the search dsl would work great for us.

Thanks for reviewing this!

**Comment by tuxpiper** [comment]
@clintongormley @martijnvg  since the reception of the idea seems to be positive, we are looking forward to having a notion of when this behavior could be incorporated in ElasticSearch. Thanks!

**Comment by kausalyb** [comment]
@clintongormley @martijnvg we would like to know the possible timeline of this feature will be into elastic search. 
 My issue is same as mentioned this link https://github.com/elastic/elasticsearch/issues/10882.
Until then , I would be helpful if you can suggest any workaround for this.

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/12016
