### ISSUE TITLE
Search results missing after upgrade from 1.1.2 to 1.5.0

### ISSUE THREAD

**Issue by tomcashman** [elastic/elasticsearch#10414]
We're experience strange behaviour with search results after upgrading from 1.1.2 to 1.5.0. We were indexing documents that had nested objects and had to use queries to separate results for different pages (really a separate index should be used, but changing requirements, etc. etc.). This is an example object and an example of the query used for one page (index, type, field names changed for confidentiality):

```bash
curl -XPOST http://localhost:9200/example-index/example-type/1234567890 -d '{
   "fieldA": true,
   "fieldB": {
      "nestedFieldA": "value",
      "nestedFieldB": "value"
   }
}'
```

```bash
curl -XPOST http://localhost:9200/example-index/example-type/_search -d '{
      "query": {
         "bool": {
            "must_not": {
               "filtered": {
                  "query": {
                     "match_all": {}
                  },
                  "filter": {
                     "missing": {
                        "field": "fieldB.nestedFieldA",
                        "existence": true,
                        "null_value": false
                     }
                  }
               }
            }
         }
      }
}'
```

This worked before and returned the correct results. Once we upgraded to 1.5.0 it returned no results. However, if we index new documents, only the new documents are returned in the results.  I can see the previous documents are still there by running a match_all query

I thought it might have to do with running an _upgrade against the index so I did that but it did not resolve the issue.

**Comment by jpountz** [comment]
This is due to a bug in 1.5.0: https://github.com/elastic/elasticsearch/pull/10268 which will be fixed in 1.5.1. Sorry for the incovenience.

**Comment by tomcashman** [comment]
No problem, thanks for the quick response.

**Comment by HenleyChiu** [comment]
FYI,

I don't think this was ever fixed in 1.5.1 as I've ran into the same problem with the latest version.

I assume this is going to be in a future release?

**Comment by tdoman** [comment]
We've also experienced the same problem with 1.5.1.  Will newly indexed documents be effected or the just old data?  If so, is a re-index of the old data a valid temporary work around?

**Comment by rjernst** [comment]
@tdoman If it is the same problem as this issue then it would affect any *indices* created before 1.3.0. Reindexing the same docs into an old index will not fix the problem, but creating a new index should fix the issue.  If you are seeing this in 1.5.1, can you please describe your setup and the problem on #10590?

**Comment by tdoman** [comment]
We had been running 1.1 until about a week ago when we upgraded to 1.5.1.  That's a lot of work to execute the work around but we can create new indexes and then update our aliases if that's the only way to go.
