### ISSUE TITLE
Found 1 record, but cannot see data

### ISSUE THREAD

**Issue by thoaingo** [elastic/elasticsearch#10413]
Request:
POST property_v2/property/_search
{
  "from": 1,
  "size": 20,
  "sort": [
    {
      "Models.MinPrice": {
        "order": "asc"
      }
    }
  ],
  "filter": {
    "and": {
      "filters": [
        {
          "ids": {
            "values": [1726485],
            "type": "property"
          }
        }
      ]
    }
  }}
Here is response. 
{
   "took": 1,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": null,
      "hits": []
   }
}

But when you use: http://localhost:9200/property_v2/property/1726485, it return data.

**Comment by javanna** [comment]
Hi @thoaingo this type of question would be better handled if it was sent to our [mailing list](https://groups.google.com/forum/?fromgroups=#!forum/elasticsearch). I suspect what you see is due to `from: 1` in your request, in any case can you move the discussion to the mailing list please?
