### ISSUE TITLE
Allow functionality of the EQL `sequence` command within ESQL

### ISSUE THREAD

**Issue by victory-gin** [elastic/elasticsearch#104161]
### Description

I have a customer that uses the EQL `sequence` command from the Timeline correlation tab. This is very useful for following user activity.
However, they have asked for that command's functionality to be brought into ESQL to increase it's potential for improving their threat hunt capabilities.

**Comment by ninoslavmiskovic** [comment]
@victory-gin please move this to the enhancement repo: https://github.com/elastic/enhancements

We have a internal process to handle enhancement requests - thanks

**Comment by ossie-git** [comment]
Hi @victory-gin. Any reason why this was closed as completed? Are **sequences** supported in ES|QL? I can't seem to find any mention of how to use them in ES|QL. Thanks

**Comment by victory-gin** [comment]
Hey @ossie-git we transitioned this enhancement request into an internal repo to continue. No new updates as of yet

**Comment by ossie-git** [comment]
Thanks @victory-gin Is there any resource / matrix where users can know what features are currently supported by ESQL and which are missing (such as sequences, etc) for it to finally replace all the other query language options?  Thanks
