### ISSUE TITLE
http.publish_address should allow for more fine-grained configuration

### ISSUE THREAD

**Issue by torrancew** [elastic/elasticsearch#10424]
Our use case for this ticket involves an ES cluster with an Nginx proxy in front of the HTTP API, to enforce TLS mutual authentication. This works perfectly fine for simple use cases, however, when using the ruby client with some of its more advanced/robust features (specifically, reload_connections) we noticed that we would configure a client, it would make a request to determine cluster state, and then attempt to perform communications over http://$IPADDRESS:9200, which is firewalled off. I attempted to set http.publish_host and publish_port, but observed the following problems:

1) while http.publish_host had a visible impact on the output of the /_nodes endpoint, ultimately the client gem still wants to use the IP that the name I set resolves to, rather than the name I set itself.
2) setting http.publish_port had no visible impact
3) there is no apparent way to manipulate the protocol, to advertise https instead of http

A lot of these pain points could be resolved if a user were allowed to directly control http.publish_address, but I have been unsuccessful at doing so.

I realize that shield may solve this problem, but given that we have a functional TLS proxy, and a functional ES cluster, Shield seems a bit like using a jackhammer to drive a nail in this case.

**Comment by clintongormley** [comment]
Hi @torrancew 

The ruby client should use the address provided in this output:

    GET /_nodes/http

You should be able to set an `https` flag in the ruby client itself, which will automatically use https:// for sniffed nodes instead of http.  eg see https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport#authentication

Either way, Elasticsearch doesn't know about https, and it shouldn't.

**Comment by torrancew** [comment]
@clintongormley Thanks, that clears up the https matter, but I'm still having trouble setting an http publish port that differs from the port Elasticsearch is listening on. What is the proper config key for that? Currently, we set `http.publish_port` in elasticsearch.yml, with no visible effect.

**Comment by clintongormley** [comment]
Hi @torrancew 

If I start Elasticsearch as follows:

     ./bin/elasticsearch --http.publish_port 9506

then it listens to localhost:9200 but the HTTP port is set to :9506

    GET /_nodes/http

Returns:

    {
       "cluster_name": "elasticsearch",
       "nodes": {
          "OrGQUNFjQe6BWmPPE7_1XA": {
             "name": "Tyrannosaur",
             "transport_address": "inet[/192.168.2.184:9300]",
             "host": "Slim-2.local",
             "ip": "192.168.2.184",
             "version": "1.5.0",
             "build": "5448160",
             "http_address": "inet[/192.168.2.184:9506]",
             "http": {
                "bound_address": "inet[/0:0:0:0:0:0:0:0:9200]",
                "publish_address": "inet[/192.168.2.184:9506]",
                "max_content_length_in_bytes": 104857600
             }
          }
       }
    }

**Comment by torrancew** [comment]
Thanks, this helps quite a bit, but I still have a few problems left to solve (or perhaps I'm doomed to not be able to use cluster enumeration?)

Primarily, I need to advertise a hostname, not an IP, for certificate validation to pass.
Past that, I see that I can set a scheme per-host when instantiating the Elasticsearch::Client instance, but I don't understand how that would carry over to hosts discovered after connecting. Is there a setting at a higher scope that I'm missing?

**Comment by clintongormley** [comment]
> Primarily, I need to advertise a hostname, not an IP, for certificate validation to pass.

Elasticsearch internally deals only with IP addresses, not hosts, so I think you're out of luck there.  Sniffing is used when the client is part of the same network as the clusters.  This sounds like you have a determined list of proxies in front of Elasticsearch, which you could list specificially rather than relying on sniffing.

**Comment by torrancew** [comment]
@clintongormley thanks. In this case, our automation installs a local proxy per Elasticsearch cluster node, so the list is inherently as dynamic as the cluster itself. That said, we can probably make due with specifying the list, and maintaining it separately - we were just hoping that we could make the cluster do the work for us.
