### ISSUE TITLE
Cancellation checks during bulk scoring add significant runtime cost

### ISSUE THREAD

**Issue by original-brownbear** [elastic/elasticsearch#104273]
From profiling the scroll phase of the http_logs rally track:

<img width="1504" alt="image" src="https://github.com/elastic/elasticsearch/assets/6490959/207a58e3-e27d-4220-b3b8-d2bb595ce653">

These checks are far more expensive than the docCount method call itself. We also have other code where we call `ExitablePointValues` back-to-back to e.g. compare it's `size()` and `getDocCount()` return, thus running redundant checks.

We could optimise the checks itself, but like we did elsewhere it's probably better to trade cancellation liveness for performance here?

**Comment by DaveCTurner** [comment]
Doing the check less often seems ok (if easy to do without losing too much promptness) but it does look like there's some easy optimisations to the check itself. The flamegraph indicates that most of the time is just iterating the `HashSet`? Does this need to be a `HashSet`? We fill it with lambdas, there's not going to be any duplicates in there are there?

Can you share an expanded flamegraph for the check itself?

**Comment by original-brownbear** [comment]
<img width="2389" alt="image" src="https://github.com/elastic/elasticsearch/assets/6490959/8aacbb03-c079-4694-9a86-a46ff95d362d">

Here you go I don't think there's much you can optimize here. I think we could move to an `ArrayList` for the data structure for sure (as you say it's only lambdas going in there so there's never any equality anyway), but if you look at the graph everything is inlining 100% already. The cost really isn't in the code but in the fetching of the data I'd guess (could check that later). And really, even if we optimised this massively by say 80%, it's still too much overhead IMO.
I bet this could be refactored in a way that makes this check a single volatile read (but at quite some cost in work and come complexity) by running the actual check on another thread for timeouts and pushing flag cancellation checks via a callback mechanism
 ... but really, it seems more reasonable to just find a way to not check in hot loops :) That should be less work and give a much more predictable performance return.

**Comment by DaveCTurner** [comment]
Hmm `ensureNotCancelled` shouldn't be that expensive either, see #104305.

**Comment by benwtrent** [comment]
@original-brownbear can we close this? Or is there still an issue here?

**Comment by original-brownbear** [comment]
@benwtrent it's cheaper now but still quite visible in profiling last time I checked, I believe this shouldn't show up at all ideally. I'll try to remember updating the flame graph so people can understand the priority better.

**Comment by original-brownbear** [comment]
Jup this can be closed, the cancellation check isn't even visible in flame graphs anymore :)
<img width="964" alt="image" src="https://github.com/user-attachments/assets/8de2f19a-5774-4fd8-b95e-193849e21822">
