### ISSUE TITLE
Better migration path to new script parameters

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#10427]
For 2.0 we modified and unified our script parameters with #7977 . This was done in a backwards compatible manner in 1.x, but broke backwards compatibility on master, as only new parameters are read on master. A note has been added to our migration docs, but I fear that is not enough.

We should consider being more polite to our users and tell them what they have to change in their request if they send the old parameters, and fail gracefully. At the moment, if you send a request that includes the old script parameters, they get ignored, and we might end up throwing a NPE, or outputting an `AssertionError` with assertions enabled.

I saw this when sending a request referring to a file script using `file` instead of `script_file`. I'm sure there are other cases. Instead of assertions there we should have proper exceptions that get thrown whenever one of the mandatory arguments is not present.

**Comment by javanna** [comment]
Assigning this to you @colings86 ;)

**Comment by clintongormley** [comment]
@colings86 is this still relevant?

**Comment by colings86** [comment]
@clintongormley I need to check. I'll update this issue when I have tested

**Comment by colings86** [comment]
WIth the new script API updates, the error messages are a lot better when old parameters are passed in. Closing this issue, but feel free to open issues for specific scriptable APIs if necessary
