### ISSUE TITLE
mlt does not support the q parameter.

### ISSUE THREAD

**Issue by harph** [elastic/elasticsearch#10425]
More like this functionality completely ignores the *q* parameter. The results are the same with or without it.

According to the documentation: [http://www.elastic.co/guide/en/elasticsearch/reference/1.5/search-more-like-this.html](http://www.elastic.co/guide/en/elasticsearch/reference/1.5/search-more-like-this.html)

*"The API simply results in executing a search request with moreLikeThis query (http parameters match the parameters to the more_like_this query). This means that the body of the request can optionally include all the request body options in the [search API](http://www.elastic.co/guide/en/elasticsearch/reference/1.5/search-search.html) (aggs, from/to and so on)."*

This means that the *q* is a valid argument and that the expected behavior is to be able to filter the mlt results.

Here is an example of the url: http://localhost:9200/en_docs/document/1/_mlt?q=type:blog&mlt_fields=title,summary&pretty

The results I'm getting back don't meet the *q* condition.

**Comment by clintongormley** [comment]
@alexksikes please could you take a look

**Comment by alexksikes** [comment]
For your use case I would recommend switching to the MLT Query which, as being part of the query DSL, would allow you to filter out the results. What is meant in the documentation is that you can use any  of request body options of the search API but excluding a query, as the MLT API is already performing a query.

**Comment by harph** [comment]
Thank you @alexksikes That's exactly what I ended up doing.
