### ISSUE TITLE
[CI] BWC tests failing on 7.17 clusters when FIPS is enabled

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#104234]
We're getting [failures](https://gradle-enterprise.elastic.co/s/tpwsnlis6x5l2/console-log?page=4#L3427) in BWC tests when FIPS is enabled because we are applying some incompatible configuration to the BWC cluster.

```
» [2024-01-10T21:13:36,451][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [v7.17.17-0] uncaught exception in thread [main]
»  org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [xpack.security.fips_mode.required_providers] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
»  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:173) ~[elasticsearch-7.17.17-SNAPSHOT.jar:7.17.17-SNAPSHOT]
```

**Comment by mark-vieira** [comment]
@jakelandis here's another one. Looks like this was added in #103483. I think this brings up a larger question of how we should treat this FIPS config in BWC tests. We _probably_ want to test upgrading with FIPS enabled on the old clusters, but to do so we need to ensure the config is compatible across versions.

In the new test clusters framework we can add this kind of thing conditionally based on node version but that's not easy to do in the old framework. We have a couple options:

1. We can make 7.17.17 support this new setting.
2. We can add some logic to `ElasticsearchNode` to ignore this setting if the node version isn't compatible.

**Comment by jakelandis** [comment]
https://github.com/elastic/elasticsearch/pull/104287 raised to fix the test failures.
