### ISSUE TITLE
[CI] Packaging test failure for 7.17 due to missing VAULT_ADDR envvar

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#104295]
### CI Link

https://buildkite.com/elastic/elasticsearch-periodic-packaging/builds/1079#018cfc26-7ca8-44a3-967a-97b399f44de6

### Repro line

N/A

### Does it reproduce?

Didn't try

### Applicable branches

7.17

### Failure history

N/A

### Failure excerpt

Another failure is https://buildkite.com/elastic/elasticsearch-periodic-packaging/builds/1079#018cfc26-7ca4-477e-a7d6-ad9c3e6dc6d1

```
* Where:
--
  | Initialization script '/opt/buildkite-agent/.gradle/init.d/init.gradle' line: 21
  |  
  | * What went wrong:
  | A problem occurred evaluating initialization script.
  | > You must set the VAULT_ADDR environment variable to use this init script.
```

**Comment by mark-vieira** [comment]
@brianseeders are these just transient errors due to Vault being unavailable?

**Comment by brianseeders** [comment]
It looks like neither step ran the global env hook that sets up Vault (like [here](https://buildkite.com/elastic/elasticsearch-periodic-packaging/builds/1079#018cfc26-7b24-4c5b-b4ae-34da11a94e9d/1)), which means it had trouble cloning the plugin repo during agent startup. So, transient github issues

**Comment by mark-vieira** [comment]
Given it's a transient issue I'll close this. If it becomes overly frequent we might look at ways to mitigate this.
