### ISSUE TITLE
[ES|QL] Complete annotation on remaining functions

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch#104248]
### Description

On #103686 I've managed to annotate completely most of the functions, but 3 of the were left with partial annotation types.

* `coalesce`
* `round`
* `mv_dedupe`

**Comment by nik9000** [comment]
@dej611 did we finish this one already?

**Comment by nik9000** [comment]
@drewdaemon, did we finish this one?

**Comment by drewdaemon** [comment]
Yeah, all good. Thank you.
