### ISSUE TITLE
[CI] Old index tests can take a long time to create replicas

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#10434]
This seems to happen just for 0.90.13, when replicas is set to 2 (from a very cursory checking of the recent failures). When I run with the same seed on my local box, the test finishes fine.

Examples:
http://build-us-00.elastic.co/job/es_core_master_regression/1730/testReport/org.elasticsearch.bwcompat/OldIndexBackwardsCompatibilityTests/testOldIndexes/
http://build-us-00.elastic.co/job/es_core_master_regression/1731/testReport/org.elasticsearch.bwcompat/OldIndexBackwardsCompatibilityTests/testOldIndexes/
http://build-us-00.elastic.co/job/es_core_master_debian/4710/testReport/junit/org.elasticsearch.bwcompat/OldIndexBackwardsCompatibilityTests/testOldIndexes/

**Comment by mikemccand** [comment]
I think it's useful to have back compat indices with "many" segments: this uncovered one nasty lucene back-compat bug (now fixed), that was only tickled if merges kicked off immediately on upgrade.

**Comment by bleskes** [comment]
@mikemccand agreed it's well worth the extra time. We just need to figure out what exactly is slow there. If it ends being sane given the number of files, we'll just bump up the timeout.

**Comment by rjernst** [comment]
We fixed this by increasing the timeout for ensureGreen, as well as setting replicas to always be 1, instead of 1 or 2.

**Comment by javanna** [comment]
I guess we should remove the `AwaitsFix` from 1.5 branch then (not sure why it was annotated that way on 1.5 only).

**Comment by s1monw** [comment]
@javanna I did this like 60 sec ago :)

**Comment by javanna** [comment]
great, thanks @s1monw ;)
