### ISSUE TITLE
parameter script_file does not seem to work (but "script": "script_file_name" does) 

### ISSUE THREAD

**Issue by vanatteveldt** [elastic/elasticsearch#10438]
The documentation at http://www.elastic.co/guide/en/elasticsearch/reference/1.x/modules-scripting.html suggests that you can use a script stored in {{conf.dir}}/scripts/name.groovy by specifying "script_file": "name" in the query. However,  when I use "script_file" I get a NulllPointerException. However, using "script" and pointing to the script filename seems to work fine. So, it seems that the docs are inconsistent with the actual behaviour, at least with version 1.4.4

A "curl" test file and session transcript are available here: https://gist.github.com/vanatteveldt/59ff5730b025270e8035

**Comment by clintongormley** [comment]
Hi @vanatteveldt 

Thanks for reporting. This should be fixed already in #7977
