### ISSUE TITLE
ESQL: missing equals and hashCode for some functions

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#104393]
Some functions are missing correct implementations for `equals` and `hashCode`. This applies at least to
- ~~[DateDiff](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateDiff.java)~~ **Update:** This one is actually fine.
- [DateExtract](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/date/DateExtract.java) and other `ConfigurationFunctions` (we could just implement this for `ConfigurationFunction` in this case).

Other functions may need to be checked as well.

**Comment by nik9000** [comment]
Interesting that this hasn't bit us. I know we have a ton of function test case utilities, but they don't actually use equals and hashCode - they are more about building the function and running it.
