### ISSUE TITLE
Update all examples to use full path names

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#10439]
With #9670 in place, all doc examples which reference fields need to be updated to use full path names, as the short name variants will no longer work.

Should probably add a note to http://www.elastic.co/guide/en/elasticsearch/reference/master/api-conventions.html as well.

**Comment by clintongormley** [comment]
@debadair could you add this to your list please

**Comment by clintongormley** [comment]
Also need to remove any mention of using a `type.` prefix when using the full path name, as this no longer works (see #9492)

**Comment by aurorahunter** [comment]
Hi @debadair : Is this still a valid issue? If it is fixed, can we kindly close this? 
Thank you
Varsha

**Comment by debadair** [comment]
I think this can be safely closed as the example testing should have long since caught most stragglers. We can open specific issues if there are remaining issues in samples that are not automatically tested.
