### ISSUE TITLE
maven emits scary warnings

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#10433]
At least with master (did not check other branches) I see this:

[WARNING] Some problems were encountered while building the effective model for org.elasticsearch:elasticsearch:jar:2.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-resources-plugin @ line 1104, column 21
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-resources-plugin @ line 1367, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.

**Comment by dadoonet** [comment]
@rmuir this should be fixed when we will merge the PR about parent project.
Parent project defines all plugins correctly.

**Comment by rmuir** [comment]
Ok, thanks for looking @dadoonet !

**Comment by dadoonet** [comment]
We can also fix it directly without merging my PR though.

**Comment by rmuir** [comment]
Yeah, I don't know the branches impacted or which ones you plan to merge your PR to. I just didn't want it to get missed.

**Comment by dadoonet** [comment]
+1! The original plan was to merge the PR in 1.5, 1.x and master.
Now 1.5 has been released, I think it will may be go to 1.x and master?

For info, PR is waiting for a review here: #9735 :)

**Comment by rmuir** [comment]
Well, for the record, that PR just looks fantastic to me. Consolidating that stuff should really make plugins easier and better tested. But I don't know enough about maven to really give you a competent review.

**Comment by tlrx** [comment]
@dadoonet @rmuir my fault - I should have seen those warnings when merging #10330. By the way I'm not sure the parent project PR will fix thoses warnings so I created #10453.

**Comment by dadoonet** [comment]
@tlrx I agree. My initial thought was that there was duplicated maven plugins. Something I fixed while creating the parent project.
But, as Tanguy said, I would not have fixed the issue reported by @rmuir.
