### ISSUE TITLE
GEOIP Database Update Issue: Documentation Followed, Databases Not Updating on Ingest Nodes

### ISSUE THREAD

**Issue by DomDaigle** [elastic/elasticsearch#104484]
### Elasticsearch Version

8.11.1

### Java Version

_bundled_

### OS Version

4.18.0-513.5.1.el8_9.x86_64

### Problem Description

I encountered some unexpected behavior when trying to use geoip database from our MAXMIND subscription (not the built-in Geoip DB). The GEOIP databases are not updating on Elasticsearch ingest nodes. I'm not certain if I made a mistake or if there's an issue with the documentation or GEOIP itself.

#### Expected Behavior
According to the documentation, I expected the GEOIP databases to update successfully on ingest nodes.

#### Actual Behavior
However, when checking the status with "GET _ingest/geoip/stats," I see that the updates have not occurred:

```json
{
  "stats": {
    "successful_downloads": 0,
    "failed_downloads": 1,
    "total_download_time": 0,
    "databases_count": 0,
    "skipped_updates": 0,
    "expired_databases": 0
  },
  "nodes": {}
}
```

I'm currently stuck and uncertain about the next steps to resolve this issue. I've followed the documentation and conducted troubleshooting steps as outlined, but the problem persists. Any assistance or guidance from the community would be greatly appreciated.

### Steps to Reproduce

I followed the steps outlined in the section ["Use a custom endpoint"](https://www.elastic.co/guide/en/elasticsearch/reference/current/geoip-processor.html#manage-geoip-database-updates) of the documentation.

### Node Configuration

I have a total of 14 Elasticsearch nodes (ELK STACK version: 8.11.1):

- 8 data nodes
- 3 ingest nodes
- 3 master nodes

### Troubleshooting Steps

I have taken several steps to troubleshoot the issue:

1. Executed "elasticsearch-geoip" for updating databases, which appeared to complete successfully.
   
   ```
   elasticsearch@elasticsearch-5c64694f74-26mxt:~/bin$ ./elasticsearch-geoip -s /geoip/ -t /geoip/
   Found GeoIP2-City.mmdb, will compress it to GeoIP2-City.tgz
   Adding GeoIP2-City.tgz to overview.json
   overview.json created
   ```

2. Checked file permissions on the target folder and confirmed they are appropriate.

   ```
   elasticsearch@elasticsearch-5c64694f74-26mxt:/geoip$ ls -ls
   total 207891
   135949 -rw-r--r--. 1 root          root          139210785 Jan 17 16:44 GeoIP2-City.mmdb
   71942  -rw-rw-rw-. 1 elasticsearch elasticsearch  73668587  Jan 17 16:48 GeoIP2-City.tgz
   1 -rw-rw-rw-. 1 elasticsearch elasticsearch       122 Jan 17 16:48 overview.json
   ```

3. Made configurations and settings adjustments as described in the documentation, including updating endpoint URLs, restarting Elasticsearch, and confirming settings.

   - All nodes have the settings "ingest.geoip.downloader.endpoint: https://mydomain.com/overview.json" in elasticsearch.yml. 
   - Elasticsearch service on all nodes were restarted after adding the endpoint settings.

   ```
   GET _cluster/settings?include_defaults
   
   "geoip": {
         "cache_size": "1000",
         "downloader": {
           "eager": {
             "download": "false"
           },
           "enabled": "true",
           "endpoint": "https://mydomain.com/overview.json"
         }
       }
   
   ```

   - I changed the pull interval from 3 days to 1 day. The cluster settings confirm.

   ```
   ...
   "ingest": {
       "geoip": {
         "downloader": {
           "poll": {
             "interval": "1d"
           }
         }
       }
     }  
   ```

4. Tested the connection to the endpoint from all nodes, and all of them can retrieve data from the endpoint.

   - Command executed and result from all nodes:

   ```
   $ curl -XGET https://mydomain.com/overview.json
   [{
       "name": "GeoIP2-City.tgz",
       "md5_hash": "3fe7b4df652ad2b6679da1f043255fb1",
       "url": "GeoIP2-City.tgz",
       "updated": 1705510085337
   }]
   ```

5. Attempted changing the URL part of overview.json to the full URL endpoint, but it did not resolve the issue.

   ```
   [{
       "name": "GeoIP2-City.tgz",
       "md5_hash": "3fe7b4df652ad2b6679da1f043255fb1",
       "url": "https://mydomain.com/GeoIP2-City.tgz",
       "updated": 1705510085337
   }]
   ```

6. Set the log level to trace following the instructions in this [article](https://support.elastic.co/knowledge/e93a5752). Observed many log lines, including:
   
   ```
   [2024-01-17T12:47:50,093][TRACE][o.e.i.g.DatabaseNodeService] [ingest_1] Not checking databases because geoip databases index does not exist
   ```

7. Followed instructions to delete the .geoip_databases index from this [article](https://support.elastic.co/knowledge/b48427cc), but I cannot see this index in my cluster. I attempted to output all indices with the API call:

   ```
   GET _cat/indices?format=JSON&bytes=b&expand_wildcards=all
   ```

   However, there is no .geoip_databases index in the output.
   
   #### References:
- Documentation: ["Manage GEOIP Database Updates"](https://www.elastic.co/guide/en/elasticsearch/reference/current/geoip-processor.html#manage-geoip-database-updates)
- Troubleshooting Article: [Support - Elastic Knowledge Base](https://support.elastic.co/knowledge/e93a5752)
- Deleting the .geoip_databases Index: [Support - Elastic Knowledge Base](https://support.elastic.co/knowledge/b48427cc)

**Comment by DomDaigle** [comment]
I wanted to provide an update on the issue I previously reported regarding the updating of GeoIP databases from our MaxMind subscription on Elasticsearch ingest nodes.

After further investigation and insights from Elastic Support, we identified SSL handshake errors on the Elasticsearch node tasked with downloading the GeoIP database. The solution involved adding our CA certificate to the JVM's truststore used by Elasticsearch. This was a learning moment for me as I initially assumed that all SSL-related queries or API calls within Elasticsearch would automatically use the SSL configurations specified in `elasticsearch.yml`. This assumption turned out to be incorrect.

Post updating the truststore across all Elasticsearch nodes, the GeoIP database began to download as expected, which was a significant breakthrough. However, I encountered a new challenge. The tag "_geoip_database_unavailable_GeoLite2-City.mmdb" persisted in indices using the geoip processor. To address this, I followed the steps outlined in the "[Use a custom endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/current/geoip-processor.html#manage-geoip-database-updates)" section of the documentation. Notably, before executing step 3, I renamed our `GEOIP2-City.mmdb` database file to `GeoLite2-City.mmdb`. This workaround proved effective, yet it introduces a new layer of complexity by necessitating the replication of the default filename.

This brings up questions about potential improvements or alternative solutions that could simplify this process and eliminate the need for such workarounds. I'm keen to hear your thoughts on this matter and any suggestions you might have.

Thank you for your ongoing support and assistance.

**Comment by jbaiera** [comment]
> The tag "_geoip_database_unavailable_GeoLite2-City.mmdb" persisted in indices using the geoip processor. 

I'm assuming you mean that documents that are processed with the geoip processor are still being tagged saying that it cannot find the database in question.

> To address this, I followed the steps outlined in the "[Use a custom endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/current/geoip-processor.html#manage-geoip-database-updates)" section of the documentation. Notably, before executing step 3, I renamed our GEOIP2-City.mmdb database file to GeoLite2-City.mmdb. This workaround proved effective, yet it introduces a new layer of complexity by necessitating the replication of the default filename

I see, are you using a pipeline that you yourself have defined or is this a pipeline provided by Elastic or a 3rd party? You can update your geoip processor to use the geoip2 city file instead of the geolite2 one by using the `database_file` property on the processor definition: https://www.elastic.co/guide/en/elasticsearch/reference/current/geoip-processor.html

That said, if the pipeline is managed by some other software like an Elastic or 3rd party observability or security solution, those edits may be overwritten if the pipeline ever sees an update. In that case you may want to check into providing a geolite2 version of the database files alongside the geoip2 types.

**Comment by jbaiera** [comment]
I'm going to go ahead and close this out since it doesn't seem like there's a specific bug with the geo ip databases. If you disagree with that please let us know and we can see about reopening and reclassifying the issue. Additionally, if you have any further questions feel free to post on our [forums](https://discuss.elastic.co/), as there is a pretty active community there that can help get you some further guidance.
