### ISSUE TITLE
mappings are unexpectedly modified if analysis plugin is removed

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#10448]
Say you're using a custom analysis plugin (perhaps one that defines a "canadian" analyzer), and add a mapping that refers to this analyzer, plus a document:

https://gist.github.com/jtibshirani/1ac46d1624655ba1b694

If you bring down the cluster, remove the plugin from each 'plugins' directory, then restart the cluster, Elasticsearch will throw a MapperParsingException, but then do a dynamic mapping update using the contents of the document. The mappings are then permanently changed, which can often render the index useless. This is particularly bad because as far as I know, there's no way to force the mappings back to their original version (besides hacking the index metadata file).

This only seems to be an issue in ES 1.4.5 and earlier.

**Comment by clintongormley** [comment]
This no longer seems to be the case - Elasticsearch keeps throwing exceptions but doesn't change the mapping any longer.  Closing
