### ISSUE TITLE
New Feature - sourceAsMap()/sourceAsString() for TermVectorsResponse

### ISSUE THREAD

**Issue by sleighsoft** [elastic/elasticsearch#10441]
I recently tried to get the result of a TermVectorsRequest as a map/json string and found no suitable function to do so.

GetResponse already has that feature: elasticsearch/src/main/java/org/elasticsearch/action/get/GetResponse.java

I managed to do convert the result into a string with the following code:

``` java
TermVectorResponse resp = client.prepareTermVector().setIndex(index).setType(type).setId(id).execute().actionGet();
XContentBuilder builder = XContentFactory.jsonBuilder();
builder.startObject();
resp.toXContent(builder, ToXContent.EMPTY_PARAMS);
builder.endObject();
```

With:

``` java
Map<String, Object> map = XContentHelper.convertToMap(builder.bytes(), false).v2();
```

to convert it into a map

or

```
builder.string();
```

to convert it into a string

I would like to see this functionality as easy to use functions for TermVectorsResponse
(sourceAsMap() and sourceAsString())

I could also implement that in the TermVectorsResponse class if you also find it useful.

**Comment by clintongormley** [comment]
@alexksikes any thoughts?

**Comment by alexksikes** [comment]
I agree that would be a useful feature, that is having the choice between string or map representation for term vectors. This would be similar to GetResponse#getSourceAsString or GetResponse#getSourceAsMap, but on the term vectors returned, not on the source, right?

**Comment by sleighsoft** [comment]
Yes that's right.
I just mentioned it for better understanding.

**Comment by mayya-sharipova** [comment]
I will be closing this issue for now, as there are not much activity on it.

This is still a valid issue though, and if anyone wants to contribute a patch,  we encourage you to do so.
Thanks
