### ISSUE TITLE
Clean up extra/temp files before file-based recovery

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#104473]
If a node crashes part-way through a recovery then it may leave some temp files on disk. A subsequent recovery attempt will eventually clean up any unnecessary files but that cleanup happens towards the end of the recovery process, after making a new copy of the shard on disk, and it's possible that there may not be space for all this data because of the space wasted on old temp files.

Today one of the preparatory steps on a recovery target is to replay any safe operations from the local translog and then flush to make a new safe commit, which happens before we even start to copy any data from the recovery source. After successfully making that new safe commit I think it'd be reasonable to do another cleanup step to discard anything that isn't referenced from that commit, which would include any temporary files from a previous recovery. I suspect we might also be able to clean some things up before replaying the local translog.

**Comment by bcully** [comment]
An alternative might be to try to reuse any files transferred in a previous recovery attempt, and only clean those that we wouldn't retransmit?

**Comment by DaveCTurner** [comment]
That's true, but I'd rather we didn't introduce any extra complexity in this area unless we're sure it's needed.

**Comment by bcully** [comment]
Maybe the simplest, safest thing to do is to only delete known temp files (anything starting with `RECOVERY_PREFIX` (`recovery.`). This can be done at any time before transfer and doesn't have any dependencies on the state of a local commit?

**Comment by DaveCTurner** [comment]
Yes I think that's safe and covers most of the problem.

I'd be interested to know if there's a simple way to ask Lucene to delete any cruft it might have left over from any commit or merge that was running at the point in time that the shard failed. It's possible that it cleans this all up as part of calling `IndexWriter#commit()` anyway. I took a quick look and saw evidence that it does some cleanup at this point, but didn't dig deeply enough to determine whether that cleanup catches everything.

**Comment by bcully** [comment]
I suppose we could attempt to call `cleanupAndVerify` if we can produce a snapshot locally, which I think should take care of failed merges etc? If that fails (e.g., because there's no segments file or something) we can fall back to deleting temp files by name.

**Comment by lkts** [comment]
This change was reverted in https://github.com/elastic/elasticsearch/pull/139569.
