### ISSUE TITLE
[CI] MvLastTests testEvaluateBlockWithoutNullsFloating {TestCase=mv_last(<geo_shapes>) DEDUPLICATED_UNORDERD} failing

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#104496]
This actually causes an OOME!

**Build scan:**
https://gradle-enterprise.elastic.co/s/divx5eulljeiy/tests/:x-pack:plugin:esql:test/org.elasticsearch.xpack.esql.expression.function.scalar.multivalue.MvLastTests/testEvaluateBlockWithoutNullsFloating%20%7BTestCase=mv_last(%3Cgeo_shapes%3E)%20DEDUPLICATED_UNORDERD%7D

**Reproduction line:**
```
./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.expression.function.scalar.multivalue.MvLastTests.testEvaluateBlockWithoutNullsFloating {TestCase=mv_last(<geo_shapes>) DEDUPLICATED_UNORDERD}" -Dtests.seed=3B623E28838E7C7B -Dtests.locale=zh-TW -Dtests.timezone=America/Martinique -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
[Failure dashboard for `org.elasticsearch.xpack.esql.expression.function.scalar.multivalue.MvLastTests#testEvaluateBlockWithoutNullsFloating {TestCase=mv_last(<geo_shapes>) DEDUPLICATED_UNORDERD}`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testEvaluateBlockWithoutNullsFloating%20%7BTestCase%3Dmv_last(%3Cgeo_shapes%3E)%20DEDUPLICATED_UNORDERD%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.expression.function.scalar.multivalue.MvLastTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.OutOfMemoryError: Java heap space


```

**Comment by mark-vieira** [comment]
Here's another build with OOM errors: https://gradle-enterprise.elastic.co/s/lam6k3yvtp4vs
