### ISSUE TITLE
Hanging transport connection thread on EC2

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#10447]
Observed on 1.4.4, 1.5.0.

To repro:  Set up four-node cluster on EC2, 1 master, 2 data, 1 client only.  Under certain load test conditions with load driving against the client node only, the client node reaches a state where it can no longer handle indexing or query operations, and many administrative commands (_cat) fail.

_cat/indices and _cat/shards will fail 100% of the time.  _cat/nodes will fail sometimes, succeed others.  This always occurs in a regular repeating pattern, with the same number of successes and failures each time.

Restarting the client node always clears the problem.

Restarting one of the data nodes may clear the problem.

The problem never occurs if there is only one data node.

The behavior around the restart of the data node suggests that this is caused by a hanging transport thread in the client.  When the data node connected to that thread is restarted, the transport thread is knocked loose and the client returns to normal operation.

A test case that can regularly cause the problem is available on a separate machine in the same EC2 zone.  Please contact me for access to the test system where this can be reproduced.

**Comment by seang-es** [comment]
The same tests performed by our customer on a non-EC2 cluster did not result in the same error.  This seems to be an edge case around EC2's networking and the load they are using to drive the client node.

Configuration is completely vanilla except for the use of unicast discovery.  No plugins installed.

**Comment by nornagon** [comment]
I'm seeing what appears to be a similar issue. 1.4.4 and logstash 1.5.0rc2. I have 4 total nodes (m3.large), 3 data-only (data: true, master: false) and one client/master (data: false, master: false). Logstash (also hosted on ec2) is sending around 50 messages/sec via the "transport" protocol to the client node.

After a while, searches stop working and the client node no longer responds to `GET /_status` — the request just hangs. It's still responsive to `/_cluster/health`, though. Restarting the client node fixes it for a while.

**Comment by nornagon** [comment]
The `/_cat/{nodes, shards, indices}` behaviour matches what @seang-es is seeing also (nodes succeeds sometimes, shards/indices fail always)

**Comment by nornagon** [comment]
Possibly related: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1317811

**Comment by markwalkom** [comment]
Just to note, @nornagon mentioned he was seeing no disconnects after he upgraded his kernel;
> nornagon
> 11:01 warkolm: fwiw, updating my (ubuntu) kernel from 3.13.0-36 to 3.13.0-48 seems to have fixed the issue (at least, it hasn't happened in the last hour or so, where before it was happening every 10 minutes or so)

**Comment by spinscale** [comment]
Hey,

indeed this is a kernel issue, which has been introduced in kernel 3.7. It is resolved upstream in 3.18 but I guess some vendors patched this in their own releases, ubuntu being one them, by fixing it in `3.13.0-46.75`

If you dont want to restart, you could also run `sudo ethtool -K eth0 sg off` - but this has a performance impact, as the kernel has to do things, that the NIC is supposed to do resulting in copying of more data.

thx to @nornagon for pointing into the right direction.

### Further Resources

* https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1317811
* https://bugs.launchpad.net/ubuntu/+source/linux-lts-raring/+bug/1195474
* http://ubuntu.5.x6.nabble.com/Trusty-Utopic-SRU-Avoid-quot-rides-the-rocket-quot-and-dropped-packages-td5091302.html
* http://packages.ubuntu.com/trusty/kernel/linux-image-3.13.0-48-generic and the [changelog](http://changelogs.ubuntu.com/changelogs/pool/main/l/linux/linux_3.13.0-48.80/changelog) mentioning it
* https://lkml.org/lkml/2014/8/11/416
* http://patchwork.ozlabs.org/patch/379108/
* https://www.kernel.org/pub/linux/kernel/v3.0/ChangeLog-3.18.1
* http://vger.kernel.org/~davem/skb.html
* http://www.brendangregg.com/blog/2014-09-11/perf-kernel-line-tracing.html
* https://github.com/elastic/elasticsearch/issues/10447
