### ISSUE TITLE
CopyOnWriteHashMap/Set tests are extremely slow

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#10442]
Suite: org.elasticsearch.common.collect.CopyOnWriteHashMapTests
Completed on J0 in 153.03s, 4 tests

Suite: org.elasticsearch.common.collect.CopyOnWriteHashSetTests
Completed on J2 in 180.31s, 3 tests

I do not understand why we have our own copy-on-write hashmaps/sets, nor why we would need tests for them that take minutes to run?

**Comment by jpountz** [comment]
This is super slow indeed, I will look into it.

The history here is that we used to use immutable maps that we would copy whenever we would need to make changes but it did not play well with dynamic mappings (O(n) field introduction, see https://github.com/elastic/elasticsearch/pull/6707) so we finally used these new classes (see https://github.com/elastic/elasticsearch/pull/7486) which are immutable too but have faster modifications.
