### ISSUE TITLE
[GEO] Add relations to GeoShapeQueryBuilder

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#10459]
As of 1.5.0 and earlier spatial relation support is only available to ```GeoShapeFilter```. ```GeoShapeQuery``` returns any geometry that ```INTERSECTS || WITHIN || CONTAINS``` the search geometry.  In order for a user to achieve a spatial relation search a post filter must be used which will result in a traversal over the candidate result set.  This enhancement adds relation support to ```GeoShapeQuery``` to avoid the need for post filtering.

This improvement is spawned from #10271

**Comment by clintongormley** [comment]
Hi @nknize 

Is this already resolved?

**Comment by nknize** [comment]
Indeed. Resolved by #14810
