### ISSUE TITLE
[GEO-JavaApi] ShapeBuilder.new{Geometry} should accept initialization parameters

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#10458]
Many of the static builder methods in ShapeBuilder are cumbersome to use. Below is an example for creating a newEnvelope

```java
Shape shape = ShapeBuilder.newEnvelope().topLeft(0, 10).bottomRight(10, 0).build()
```

Java users should have the option to pass the coordinates as parameters:
```java
Shape shape = ShapeBuilder.newEnvelope(0,10,10,0).build();
```

Other static initializers like this would make the java api more "user-friendly" simply by adding parameters or parameter lists.

**Comment by nknize** [comment]
Spawned from #10271

**Comment by clintongormley** [comment]
This appears to have been done in the search refactoring.  Closing
