### ISSUE TITLE
Max shard for each node

### ISSUE THREAD

**Issue by sadegh1404** [elastic/elasticsearch#104640]
### Description

Elasticsearch already support configuration for max shard per node for cluster and index level. 
but in some cases resource of nodes in one cluster is different  and since Elasticsearch balances nodes based on number of shards (not disk space) I need to set max shard for each node separately. 
Thanks for this great tool.

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

More specifically, if you have nodes with different resources then you can divide them into tiers and allocate shards to each tier according to ILM rules. Also recent versions of Elasticsearch do indeed take disk usage into account as well as shard count.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
