### ISSUE TITLE
ESQL: document locale rest parameter 

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#104671]
### Description

ESQL Rest endpoints supports `locale` parameter and returns results (especially dates) according to it - this needs to be documented:
```
POST _esql
{
  "locale": "it_IT",
  "query": """
          ROW birth_date_string = "2023-01-15T00:00:00.000Z" 
          | EVAL birth_date = date_parse(birth_date_string)
          | EVAL month_of_birth = date_format(birth_date, "MMMM")
   """
}
```
/cc @luigidellaquila

**Comment by leemthompo** [comment]
@costin what's the default locale? Should we refer to some external documentation for locale short codes?

**Comment by costin** [comment]
Correct - more information about ISOs [here](https://www.oracle.com/java/technologies/javase/jdk17-suported-locales.html).

**Comment by leemthompo** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/104985
