### ISSUE TITLE
Unable to set custom default analyzer by reference.

### ISSUE THREAD

**Issue by apogrebnyak** [elastic/elasticsearch#10460]
Feature request.

I want to be able to have a common `ToXContext` object that sets up a custom analyzer, and then be able to set it as a default by reference, e.g. the request would look something like this:

```
"settings":{"index":{
  "analysis": {
    "filter": {
      "doublemetaphone_filter": {
        "replace": "true",
        "type": "phonetic",
        "encoder": "doublemetaphone"
      }
    },
    "analyzer": {
      "doublemetaphone_analyzer": {
        "filter": [
          "standard",
          "lowercase",
          "stop",
          "doublemetaphone_filter"
        ],
        "tokenizer": "standard"
      },
      "default": {
        "type": "doublemetaphone_analyzer"
      }
    }
  }
}}
```
If I try to do this, ES complains that `doublemetaphone_analyzer` is an unknown type.

Currently, the only way to use a custom analyzer as a default one, is to define it with the name `default`.

**Comment by apogrebnyak** [comment]
I think it's better to separate analyzer definition, and whether or not it is used by default, or not.

For some indexes I want to enable custom analysis on a few fields and use something else as a default for everything, for others I always want to use a custom analyzer as default.

Having been able to define `default` analyzer in terms of already defined custom analyzer leads to a better code reuse and is in accordance with DRY principal.

-Alex

**Comment by clintongormley** [comment]
Given that this issue doesn't seem to have garnered any support in the last 9 months, I'm going to close it.  Feel free to reopen if you feel it is really important.
