### ISSUE TITLE
[ES|QL] auto_bucket annotation is missing the string type of third and fourth args

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch#104646]
### Elasticsearch Version

8.13.0

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

In the `auto_bucket` annotation is missing the `string` type for the third and fourth arguments.
See the `show functions` output:

```
double|date auto_bucket(field:integer|long|double|date, buckets:integer, from:integer|long|double|date, to:integer|long|double|date)
```

### Steps to Reproduce

```
show functions | where name == "auto_bucket"
```

**Comment by alex-spies** [comment]
This might be superseded by https://github.com/elastic/elasticsearch/issues/102756 in the future.

**Comment by fang-xing-esql** [comment]
> This might be superseded by #102756 in the future.

This is a good catch. I'm including the supported data types in this PR #104547.

**Comment by astefan** [comment]
@ivancea this might be the same issue as https://github.com/elastic/elasticsearch/issues/105375
