### ISSUE TITLE
allow relocating primary shards on shared filesystems without failing the shard

### ISSUE THREAD

**Issue by kozaczynski** [elastic/elasticsearch#10469]
In the current implementation of replica shard when a primary shard is relocated to a different node the cluster enters red state for the duration of the shared storage handoff. That duration is proportional to the shard size. 
The desired behavior is that the cluster doesn't enter the red state at all. An acceptable constraint is that for the duration of the storage handoff no documents can be added to the shard.

Wojtek K. 
Microsoft

**Comment by s1monw** [comment]
I will look into this, yet the ` That duration is proportional to the shard size. ` is a property of the shared filesystem not of elasticsearch in this case.

**Comment by kozaczynski** [comment]
The duration comment is about the current behavior that we need to change. The cumulative effect of that behavior is that when we restore a large index with 30+ shards into a cluster that already has number of large indexes we see the cluster go in-and-out of the red state for an extended period of time.

**Comment by s1monw** [comment]
I think the issue with going in-and-out of the  red state here is mainly triggered by the restore operation. I think you should disable allocation for those indices or at least for the primary while you restore? Yet, I think it's a bug that we go red here or at least a not so nice impl detail. Yet, the only other downside (aside of a false-red kind of) of this is that you can't write to that index for the time being. Yet, I stated looking into it but it's not a trivial change so it might take some time to get it fixed
