### ISSUE TITLE
索引统一管理

### ISSUE THREAD

**Issue by HFNU112** [elastic/elasticsearch#104673]
### Description

一个project,如果按照类型划分有多个索引，现存的索引管理这方面不能管理多个索引，一次性查询不好管理，不如放到类似一个目录下（树形结构）进行管理。另外在现有功能上丰富下增删查改。现有的索引模板虽然可以相同索引名的前缀的相关，但是对于查询索引管理上不太友好。当然这款产品在项目中受到欢迎，在项目中数据收集、分析速度挺快的相比数据库。如果我提到的issue完善，这款产品更有利开发者的使用体验。

**Comment by thecoop** [comment]
This is the google translation of the question above:

> If a project has multiple indexes divided by type, the existing index management cannot manage multiple indexes, and it is difficult to manage one-time queries. It is better to put them in a directory (tree structure) for management. In addition, the existing functions are enriched and added, deleted, checked and modified. Although the existing index template can be related to the prefix of the same index name, it is not very friendly for query index management. Of course, this product is popular in projects, where data collection and analysis are very fast compared to databases. If the issue I mentioned is improved, this product will be more beneficial to developers' experience.

@HFNU112 Is this question more about the user experience of managing indexes in kibana?

**Comment by HFNU112** [comment]
yes

**Comment by HFNU112** [comment]
> This is the google translation of the question above:
> 
> > If a project has multiple indexes divided by type, the existing index management cannot manage multiple indexes, and it is difficult to manage one-time queries. It is better to put them in a directory (tree structure) for management. In addition, the existing functions are enriched and added, deleted, checked and modified. Although the existing index template can be related to the prefix of the same index name, it is not very friendly for query index management. Of course, this product is popular in projects, where data collection and analysis are very fast compared to databases. If the issue I mentioned is improved, this product will be more beneficial to developers' experience.
> 
> @HFNU112 Is this question more about the user experience of managing indexes in kibana?

用kibana操作ElasticSearch管理索引的问题

**Comment by w6et** [comment]
A small suggestion, the index may support labels or tags, so that Kibana can be filtered by labels/tags, and then Kibana supports custom cascading search criteria(a json tree or others), and different labels/tags combinations can be assigned to different roles. @thecoop

**Comment by DaveCTurner** [comment]
You can already define arbitrary metadata on indices via the [`_meta` mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-meta-field.html), and group indices using [aliases](https://www.elastic.co/guide/en/elasticsearch/reference/current/aliases.html), so I'm not sure there's anything more for the Elasticsearch team to do here.

The question about filtering indices by labels/tags, or organising them into a tree, seems more suited for https://github.com/elastic/kibana/issues since that's where the index management UI is implemented.

**Comment by thecoop** [comment]
@HFNU112 As @DaveCTurner says, this question is better answered by the kibana team, please open an issue in https://github.com/elastic/kibana/issues or ask on the [discussion forum](https://discuss.elastic.co/) and they'll be able to look at your suggestions.

**Comment by HFNU112** [comment]
@DaveCTurner 感谢您的回答。我明白在elasticsearch 这边索引映射的问题。这个在项目设置统一响应结果定义映射类型很方便。谢谢elasticsearch团队在这款产品上为我们带来便利。

**Comment by DaveCTurner** [comment]
via Google translate:

> @DaveCTurner Thanks for your answer. I understand the problem of index mapping on elasticsearch. It is very convenient to define the mapping type for unified response results in the project settings. Thank you to the elasticsearch team for bringing us convenience on this product.

You're welcome @HFNU112 🙂
