### ISSUE TITLE
Simplify murmur3 type

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#10465]
I don't think we should allow trappy options like indexed=true or docvalues=false for this field. Cardinality and range of values is enormous by definition.

**Comment by pickypg** [comment]
I think it would be great to default:

```yml
"index" : "no",
"doc_values" : true
```

for

```yml
"type" : "murmur3"
```

Doc values _should_ be true in 2.0 already, but it makes a lot of sense to not index the field by default as well.

**Comment by rjernst** [comment]
@pickypg I don't think it should be defaults, it should just be not allowed to have anything about `index: no` and `doc_values: true`.
