### ISSUE TITLE
Support ANT-like syntax in path_match for dynamic mappings

### ISSUE THREAD

**Issue by blevine** [elastic/elasticsearch#10467]
Use case:

I'm indexing documents with nested objects where some of the objects include unique ids (GUIDS). I want all such id fields to be "not_analyzed." The id fields always have an '_id' suffix and these fields can appear at arbitrary levels in the document hierarchy. I'm trying to come up with a dynamic mapping template to address this so that any field of the form "*_id" regardless of the nesting depth will be marked as "not_analyzed." I don't think there's a way to specify this as a single path_match.  In practice, I suppose the nesting will never go deeper than let's say, 5.  So I could define 5 path_match patterns like *_id, *.*_id, *.*.*_id...etc. Although experience shows that the moment I do this, we'll find the need to go to 6 levels ;-). 

Ideally, you'd be able to specify a path in ANT-like syntax e.g., **/*_id.

**Comment by clintongormley** [comment]
Hi @blevine 

Just `match` should work for you:


    DELETE test
    
    PUT /test
    {
      "mappings": {
        "test": {
          "dynamic_templates": [
            {
              "ids": {
                "match": "*_id",
                "mapping": {
                  "type": "string",
                  "index": "not_analyzed"
                }
              }
            }
          ]
        }
      }
    }
    
    PUT test/test/1
    {
      "foo_id": 123,
      "bar": {
        "foo": "some text",
        "bar_id": "123"
      }
    }
    
    GET test/_mapping

**Comment by blevine** [comment]
Too obvious ;-)  Thanks!
