### ISSUE TITLE
Getting compilation error when parsing Timestamp from logs file 

### ISSUE THREAD

**Issue by Anand-J-Kadhi** [elastic/elasticsearch#10475]
Hi,
I am getting compilation error when trying to parse a timestamp in format '2013-02-03' i.e 'yyyy-MM-dd'. Actually i am trying to parse the timestamp in the logs file on 'http://grokdebug.herokuapp.com/' website with a input  : 
2015-02-02 11:00:58
and pattern :
 date {
    match => [ "timestamp", "yyyy-MM-dd HH:mm:ss" ]
    }
 Whenever i use yyyy-MM-dd format i get compilation error. Attaching screen shot for the same 

![compilation error](https://cloud.githubusercontent.com/assets/11851015/7043159/345e9bbc-de05-11e4-8195-c3ee2e5d1b18.png)

If i give one space after the yyyy  like yyyy -mm the error goes but i am unable to match this input, could you please look into this issue or suggest me any solution.

Thanks and regards,
Anand J.kadhi

**Comment by clintongormley** [comment]
Hi @Anand-J-Kadhi 

It sounds like you have a question with logstash, not Elasticsearch. Please ask your question on their mailing list instead.

**Comment by Anand-J-Kadhi** [comment]
Sorry for the mispost, thanks i will post on this on Logstash.
