### ISSUE TITLE
fuzzy关键字模糊查询匹配不上

### ISSUE THREAD

**Issue by HFNU112** [elastic/elasticsearch#104783]
### Elasticsearch Version

elasticserch v7.8.0

### Java Version

jdk21

### OS Version

jdk8

### Problem Description

在ES的DSL查询脚本：fuzzy 查询字段值如果带有 特殊字符 - （短划线）例子：
GET /index/_search
{
  "query": {
      "fuzzy": {
        "FEILD": {"value": "abc-tom-yoiu"}
       
      }
  },
  "from": 0,
  "size": 20
} 此时查询不出结果。

### Steps to Reproduce

GET /index/_search
{
  "query": {
      "fuzzy": {
        "FEILD": {"value": "tom-abc-you"}
       
      }
  },
  "from": 0,
  "size": 20
}

**Comment by DaveCTurner** [comment]
Thank you very much for your interest in Elasticsearch. Unfortunately the issue you have reported relates to Elasticsearch version 7.8.0 which is very old and has passed [end-of-life](https://www.elastic.co/support/eol). We will not investigate issues related to unsupported versions here on Github, so I am closing this to indicate that no action is needed from the Elasticsearch development team. It's possible that you will find a volunteer to help you with this issue on the [community forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), but our strong recommendation would be to upgrade to a supported version of Elasticsearch as a matter of some urgency. If you can reproduce your issue on a supported version then please open a fresh bug report.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.
