### ISSUE TITLE
Dangling indices may not be imported if found on elected master node

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#10487]
Dangling indices are indices that are found on disk but do not exist in the cluster state. To be safe, those are imported into the cluster state instead of automatically deleting them. This is done by reading their meta data and sending the master node a request to add them to the current meta data. 

At the moment, this request may be lost if the dangling index is discovered on the master and the master only (which means the master imported it's cluster state from another node it deemed better, or index is copied into alive cluster, like our tests do ). This is because the dangling request import logic doesn't take into account that the local node might be the master and tries to send the request via the transport layer to itself. However, the local node may not be connected (we only connect if the local node is a unicast host target or after 10s have passed and `InternalClusterService.ReconnectToNodes` kicks in).  

A generic solution was added in #10350 but it had to be pulled out, we now need to fix this in the dangling index code.

**Comment by clintongormley** [comment]
@brwe Would this issue be of interest to you?

**Comment by clintongormley** [comment]
@ywelsch would this be of interest to you?

**Comment by bleskes** [comment]
this can be closed now. #10350 was pulled out of 1.x and we opened this issue to track it (note the original 1.6.0 label). Now that 2.x is the release version this isn't an issue anymore. I'm closing it and adapting the labels.
