### ISSUE TITLE
has_child applied on an alias does not work

### ISSUE THREAD

**Issue by mikiot** [elastic/elasticsearch#10481]
I am using elasticsearch 1.5.0 and I have a filtered alias.
The index contains 2 types A and B. B is a child to A. The filter extracts from the index all the types applying some conditions. B gets soft deleted (marked as deleted in the document with a flag) and does not show in the documents returned when searching the alias. But when I query for A that do not have B (using a has_child filter), all A are returned regardless if they any children in the alias (they still have children in the index).

This is a workaround for this issue https://github.com/elastic/elasticsearch/issues/10135. I removed the has_child filter for the alias (see person in the issue ) tried to filter on search time with this simple filter:

``` 
{"filter":{"has_child":{"type":"message","filter":{"match_all":{}},"min_children":1}}}
```
Also I think that the children aggregation is affected in this scenario as any aggregation on A will take into consideration the deleted B.

Is this a bug?

**Comment by clintongormley** [comment]
Hi @mikiot 

The `filter` (now renamed to `post_filter`) is only applied after aggregations are calculated.  This is not a bug, it is by design.  You would need to include the `has_child` clause in your main `query` for it to be applied where you want it.

**Comment by mikiot** [comment]
But I use it in my main query (not in alias filter) and it does not wok. And my main problem are not aggregations, but the fact that if I do a simple filter on the alias it does not work and it should because this makes aliases pretty useless when using parent/child relationships.

**Comment by clintongormley** [comment]
Currently you have to include that filter clause anywhere that you use a `has_child` filter/query, otherwise it won't work.

Related: https://github.com/elastic/elasticsearch/issues/10058
