### ISSUE TITLE
[Script fields] Using script fields to get the second value of an array in a document may get the value in the previous document.

### ISSUE THREAD

**Issue by Refreshing-C** [elastic/elasticsearch#104998]
### Elasticsearch Version

elasticsearch8.11

### Java Version

_bundled_

### OS Version

centos7

### Problem Description

When all test documents are in the same segment, using script fields to get the second value of an array in a document,
the previous doc has a field named domain_id with value [1, 8], the next doc has the field which has the value [1]
when use
```
"script_fields": {
	"val": {
		"script": {
			"source": "doc.domain_id.values[1]",
			"lang": "painless"
		}
	}
}
```
to get domain_id's second value, the result is 8,8, but 8,0 is right.

### Steps to Reproduce

1、create an index as follows
```
PUT localhost:9200/test
{
	"settings": {
		"refresh_interval": "120s",#ensure all documents is written to the same segment "number_of_shards": 1,
		"number_of_replicas": 0
	},
	"mappings": {
		"arrays": {
			"dynamic": false,
			"properties": {
				"domain_id": {
					"type": "integer"
				}
			}
		}
	}
}

```
2、write some data
```
PUT localhost:9200/_bulk
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 1}}
{"domain_id":[1]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 2}}
{"domain_id":[1]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 3}}
{"domain_id":[2]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 4}}
{"domain_id":[3]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 5}}
{"domain_id":[1]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 6}}
{"domain_id":[1]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 7}}
{"domain_id":[1,8]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 8}}
{"domain_id":[1]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 9}}
{"domain_id":[1]}
```

3、execute the query
```
GET localhost:9200/test/_search
{
	"_source": "domain_id",
	"script_fields": {
		"val": {
			"script": {
				"source": "doc.domain_id[1]",
				"lang": "painless"
			}
		}
	}
}
```

4、the result is wrong
```
{
	"took": 105,
	{
		"_index": "test3",
		"_type": "arrays",
		"_id": "6",
		"_score": 1.0,
		"_source": {
			"domain_id": [
				1
			]
		},
		"fields": {
			"val": [
				0
			]
		}
	},
	{
		"_index": "test3",
		"_type": "arrays",
		"_id": "7",
		"_score": 1.0,
		"_source": {
			"domain_id": [
				1,
				8
			]
		},
		"fields": {
			"val": [
				8
			]
		}
	},
	{
		"_index": "test3",
		"_type": "arrays",
		"_id": "8",
		"_score": 1.0,
		"_source": {
			"domain_id": [
				1
			]
		},
		"fields": {
			"val": [
				8
			]
		}
	}
}
```
.....
the result in the last hit should be 0,but 8,we think it uses the previous hit result.

**Comment by Refreshing-C** [comment]
sorry, The last line is wrong, the last result should be 0, but 8,we think it uses the previous result.

**Comment by thecoop** [comment]
@Refreshing-C your mapping definition and bulk ingest commands seems to be invalid, and its not clear what you're declaring as an array and at what level. It might help to format code blocks with markdown (indent the block by 4 spaces)

    like this

**Comment by javanna** [comment]
I can reproduce this, it is not a `script fields` specific issue, I can reproduce it with a basic runtime field, and it does not matter how the runtime field is used:

```
GET /test/_search?size=0
{
  "aggs" : {
    "test" : {
      "terms" : {
        "field" : "val"
      }
    }
  }, 
  "runtime_mappings": {
    "val": {
      "type" : "long",
      "script": {
        "source": "emit(doc.domain_id[1]);",
        "lang": "painless"
      }
    }
  }
}

{
  "took" : 30,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 9,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "test" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : 0,
          "doc_count" : 6
        },
        {
          "key" : 8,
          "doc_count" : 3
        }
      ]
    }
  }
}

```

There is only one document with `8` as a value, rather than 3 like the aggs result above returns. This is a bug in how the results array is shared across docs when reading from doc values. The array gets resized to length 2 as soon as the doc with two items is loaded, after which the following docs override only the first value of the array, as that's the only available item, but if the script tries to load specifically the second value, the previously loaded item is returned. This cannot be reproduced iterating through values of the array, because we don't let the script go over the doc value count for each doc.
