### ISSUE TITLE
Java API produces invalid search request with AggregationBuilders.topHits("topHitsAgg").setNoFields()

### ISSUE THREAD

**Issue by hkorte** [elastic/elasticsearch#10492]
The Java API allows to construct a top_hits aggregation without fields using the method setNoFields():

    AggregationBuilders.topHits("topHitsAgg").setNoFields()

This is translated to

    {"top_hits":{"fields":[]}}

Unfortunately, the top_hits aggregation does not support "fields". Executing a request built like that leads to a SearchPhaseExecutionException:

    ...Parse Failure [Unknown key for a START_ARRAY in [topHitsAgg]: [fields].]];

I think this is misleading. I see two options to avoid this confusion:
* the top_hits API allows setting "fields" (at least to an empty array)
* the Java API does not offer this method

It is obviously not a big problem, I just stumbled over this and thought it's worth mentioning. I tested this behavior with ES 1.4.1 and 1.5.0. Here is a gist to reproduce it:
https://gist.github.com/hkorte/64e630ec579c15697c6d

**Comment by wbowling** [comment]
This is probably fixed by #12962 as top hits now supports "fields".

**Comment by clintongormley** [comment]
Closed by #12962
