### ISSUE TITLE
ESQL: Inconsistent resolution message for unresolved fields

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#104955]
### Description

In some places, the Analyzer uses a different error message for unresolved attributes - instead of the "Cannot find x, did you mean [y,z,w]?" a basic "No match found for ..[]" is returned.
See [the pattern resolution](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java#L589) vs the [regular one](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/analysis/Analyzer.java#L598).

This gets picked up when dealing with escaped wildcard:
```
FROM index
| STATS COUNT(*)
| SORT `count(*)`
```
 """Found 1 problem:
line x:y: No match found for [count(*)]"""

Thus there are two problems here:
- an escaped name containing * gets confused for a pattern (it's not)
- the escaped pattern doesn't match anything, see whether it makes sense to provide suggestions for it

**Comment by astefan** [comment]
A more severe use case:

```
row a = 5 | stats Count(*) by a | eval `Count(123)` = a * a | keep `Count(*)`

   Count(*)    |  Count(123)   
---------------+---------------
1              |25              
```
