### ISSUE TITLE
ESQL: broken repro lines in csv tests

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#105017]
CSV test cases with a [skip annotation](https://github.com/elastic/elasticsearch/blob/7ce8d76559f89e39b17ba1ab713b7370f37454fb/x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec#L949) cannot be run individually, and when they fail the reproduction line does not work (`No tests found for given includes`).

To reproduce, run the csv tests but change expected result for [groupByNull](https://github.com/elastic/elasticsearch/blob/7ce8d76559f89e39b17ba1ab713b7370f37454fb/x-pack/plugin/esql/qa/testFixtures/src/main/resources/stats.csv-spec#L954) and attempt to use the repro line.

The issue seems to be caused by the `+` sign used in the skip reason. If we change the csv test header from
```
groupByNull#[skip:-8.12.99,reason:bug fixed in 8.13+]
```
to
```
groupByNull#[skip:-8.12.99,reason:bug fixed in 8.13]
```
the repro line works as expected.

**Comment by luigidellaquila** [comment]
It would be nice not to see the `#[skip..` part at all in the logs and in the repro lines

**Comment by julian-computes** [comment]
I'd like to open a PR for this if the below solution is acceptable:

Instructions like `skip` beginning with `#` are no longer considered part of test names, so the `groupByNull` test may now only be matched in the repro line without its instructions: `./gradlew ... -Dtests.method="test {stats.GroupByNull}"`.

To accomplish this, test names and instructions will be factored apart when they're parsed in [SpecReader](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/ql/test-fixtures/src/main/java/org/elasticsearch/xpack/ql/SpecReader.java).
