### ISSUE TITLE
ESQL: pushdown CIDR_Match

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#105042]
### Description

[Cidr_match](https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-functions-operators.html#esql-cidr_match) function is common in the security space and thus frequent in ESQL and thus needs to be as performant as possible.
Currently this is implemented only inside the engine -  this needs to be improved so it can be pushed down to the storage as a Terms/TermQuery which currently doesn't happen.
We have this functionality [already supported in EQL](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/eql/src/main/java/org/elasticsearch/xpack/eql/planner/QueryTranslator.java#L169) and it should be straight-forward to port it to ES|QL.

As this has significant performance implications, I'm marking this as a bug.

**Comment by bpintea** [comment]
We have this function [in ESQL already](https://www.elastic.co/guide/en/elasticsearch/reference/master/esql-functions-operators.html#esql-cidr_match) as well, we just need to push it down.
