### ISSUE TITLE
node.roles: data takes precedence over specialised data roles 

### ISSUE THREAD

**Issue by louisong** [elastic/elasticsearch#105000]
### Description

When we set node.role to [data](https://www.elastic.co/guide/en/elasticsearch/reference/8.12/modules-node.html#data-node) and specialised data roles, `data` role takes precedence over specialised data roles (`data_hot`, `data_warm`, `data_cold`, etc) affecting the behaviour of [index.routing.allocation.require._tier_preference](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-tier-shard-filtering.html#data-tier-allocation-filters).

```
node.roles: ["data", "data_hot"]
node.roles: ["data", "data_warm"]
node.roles: ["data", "data_cold"]
```

Related Discuss Forum thread: https://discuss.elastic.co/t/can-both-allocate-this-shard-and-improve-the-cluster-balance/285579/5

### Doc Enhancement Request
[Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.12/modules-node.html#node-roles) should explain the generic data roles takes precedence over specialised data role when being set together.

**Comment by henningandersen** [comment]
This bit certainly looks off https://www.elastic.co/guide/en/elasticsearch/reference/8.12/modules-node.html#data-node in that it explains that you cannot use `data` and the specialized roles together. Further up, it is explained correctly though.

**Comment by leemthompo** [comment]
If anyone wants to take a crack at opening a PR to get ball rolling, I can help shepherd this over finish line :)
