### ISSUE TITLE
How to pass specific characters password to ElasticSearch through Sulu/ArticleBundle

### ISSUE THREAD

**Issue by Braskalyne** [elastic/elasticsearch#105013]
### Elasticsearch Version

6.8.0

### Installed Plugins

Sulu - SuluArticle/Bundle

### Java Version

_bundled_

### OS Version

Ubuntu 20.04

### Problem Description

I'm working on a project using Sulu 2.4.15 - php 8.2 - Symfony 5.5 - Sulu/Article-bundle 2.5.1

I usually use ElasticSearch with Sulu, which is recommended as standard. But until now, I've never secured the ElasticSearch connection via login/password.
For this project, our customer is imposing a password made up of special characters, but I can't get in.
For my example, I have an elastic 6.8.0 image: 
![Capture d’écran de 2024-02-01 13-46-28](https://github.com/elastic/elasticsearch/assets/44805901/85b1b3cd-9194-438c-9186-c5669187b7ae)
The password is "toto?"
When I access my ES via Curl by encoding the password ( toto%3F ) I have no problem: 
![Capture d’écran de 2024-02-01 13-48-46](https://github.com/elastic/elasticsearch/assets/44805901/ece1bbae-bce1-42db-b746-293751c15211)

But when I try to run a command that requires connecting to ElasticSearch from Sulu/ArticleBundle, like a sulu:article:reindex , I can't authenticate (1st screen is my .env.local, 2nd screen is the command on the left / the logs of ES on the right)

![Capture d’écran de 2024-02-01 13-53-00](https://github.com/elastic/elasticsearch/assets/44805901/62988bfa-8ffd-4eaf-b88a-6d665820069e)

![Capture d’écran de 2024-02-01 13-53-33](https://github.com/elastic/elasticsearch/assets/44805901/1dc1e85d-127e-48f3-ba0f-70f027ded779)

However, if I set the password in my ES docker to "toto" and remove %3F from my .env url, I don't have any connection problems. The problem comes from the special character "?

Digging through the error messages, I came across this file : 
vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php

And I realized that just before the query, the string was not decoded. If I modify it manually at this point, either by using an urldecode function or by hard-coding it, then I'm able to connect & do my reindex : (lines 235 and 236 both operate) : 

![Capture d’écran de 2024-02-01 13-58-01](https://github.com/elastic/elasticsearch/assets/44805901/ede2612a-b06f-4014-b419-8a05f4e45969)

But I don't understand why I need to manually "urldecode" my string, and this solution isn't viable since it's in the vendor/ folder.

I feel like I've searched in multiple places, asked on Slack Sulu, but I can't find any answer for what seems to be a very basic concern.

I've already tried it in my .env :

ELASTICSEARCH_HOST=http://elastic:toto%3F@127.0.0.1:9200
ELASTICSEARCH_HOST="http://elastic:toto%3F@127.0.0.1:9200"
ELASTICSEARCH_HOST=http://elastic:toto?@127.0.0.1:9200
ELASTICSEARCH_HOST=http://elastic:toto\%3F@127.0.0.1:9200
ELASTICSEARCH_HOST=http://elastic:toto\?@127.0.0.1:9200
ELASTICSEARCH_HOST=http://elastic:toto%%3F@127.0.0.1:9200
etc...

Thanks a lot !

### Steps to Reproduce

Install ES 6.8.0 : 

```
cat docker-compose.yml 
version: '3,7'

services:
  elasticsearch:
   image: elasticsearch:6.8.0
   ports:
     - 9200:9200
   environment:
     - discovery.type=single-node
     - ELASTIC_PASSWORD=toto?
     - xpack.security.enabled=true

```

Install a 2.5 Sulu project : https://docs.sulu.io/en/2.5/
Install Sulu/ArticleBundle 2.5 : https://github.com/sulu/SuluArticleBundle

Try a command like 

`bin/console sulu:article:reindex` 

### Logs (if relevant)

![Capture d’écran de 2024-02-01 14-03-21](https://github.com/elastic/elasticsearch/assets/44805901/79fd66d7-82c5-41bd-b597-08ec43dc05d4)

**Comment by henningandersen** [comment]
This sounds like either a problem in sulu or on the php client. For the latter, the https://github.com/elastic/elasticsearch-php repo would be the right place to report such a bug. If you are unsure if this is a bug in the php client or not (I certainly am), asking for help first in discuss.elastic.co is preferred, we generally reserve github issues for confirmed bugs.
