### ISSUE TITLE
Tribe using HTTP

### ISSUE THREAD

**Issue by frecar** [elastic/elasticsearch#10504]
Hi, is it possible to make Tribe connect to clusters using HTTP?

I want to use a single connection when querying the clusters.

**Comment by javanna** [comment]
Hi @frecar can you please ask your question on the [mailing list](https://groups.google.com/forum/?fromgroups=#!forum/elasticsearch). We'd rather use github issues for bugs and feature requests. Thanks!

**Comment by clintongormley** [comment]
And for posterity: no, the tribe has to join the clusters as a client node, but you can send http requests to the tribe (which then forwards the requests over the transport layer)
