### ISSUE TITLE
elasticsearch arguments -Xms and -Xmx do not work

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#10506]
The documentation details these:
http://www.elastic.co/guide/en/elasticsearch/guide/master/heap-sizing.html
so it looks like they worked once, and IMO they should work again (environment variables aren't always easy to set), but it looks like it can't work the way the script currently calls exec:
https://github.com/elastic/elasticsearch/blob/master/bin/elasticsearch#L154

> /opt/elasticsearch/bin/elasticsearch -Xms4g -Xmx4g -Des.path.conf=/etc/elasticsearch

results in:

> elastic+ 4122 171 1.7 6903540 269320 ? Sl 12:57 0:05 /usr/bin/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Delasticsearch -Des.foreground=yes -Des.path.home=/opt/elasticsearch -cp :/opt/elasticsearch/lib/elasticsearch-1.5.0.jar:/opt/elasticsearch/lib/*:/opt/elasticsearch/lib/sigar... -Xms4g -Xmx4g -Des.path.conf=/etc/elasticsearch org.elasticsearch.bootstrap.Elasticsearch

**Comment by clintongormley** [comment]
@robin13 you can see that your custom settings have been added to the end of the command line parameters, and if you do:

    GET _nodes/jvm

you will see that your settings have taken effect
