### ISSUE TITLE
ESQL: `AUTO_BUCKET()` can return `NaN`

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#105166]
### Description

Specifying a zero as the number of buckets with numeric field will return `NaN` instead of `null` (due to div by 0).
Ex: `ROW AUTO_BUCKET(1, 0, 0, 0)`

Same for negative number of buckets (due to log10(negative)).
Ex: `ROW AUTO_BUCKET(1, -1, 0, 0)`

Same for a number of buckets value that wraps over int (due to int overflow).
Ex: `ROW AUTO_BUCKET(0, 100000000000, 0, 0)`

Related: #98698.

**Comment by luigidellaquila** [comment]
This issue does not seem to reproduce anymore.
`AUTO_BUCKET` function was [renamed](https://github.com/elastic/elasticsearch/pull/107197) as `BUCKET` and is [now only allowed as a grouping function](https://github.com/elastic/elasticsearch/pull/107272), so the queries above return a validation exception.

The following queries return `NULL` as expected.

```
ROW a = 1 | stats max(a) by BUCKET(1, 0, 0, 0)
ROW a = 1 | stats max(a) by BUCKET(1, -1, 0, 0)
ROW a = 1 | stats max(a) by BUCKET(0, 100000000000, 0, 0)
```



Internally, some parts of [the code](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/grouping/Bucket.java#L302-L307) still produce a `NaN`, but downstream it is resolved to `NULL`.

I'll add some tests, then I think this can be closed.
