### ISSUE TITLE
Support for Azure bicep

### ISSUE THREAD

**Issue by pq43** [elastic/elasticsearch#105111]
### Description

Hey there! Love elasticsearch - any chance we could get support for Azure bicep? Specifically for the [Azure Native ISV Service](https://www.elastic.co/guide/en/cloud/current/ec-azure-marketplace-native.html).

I see we already have support via
- The Azure console
- [Azure Terraform](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/elastic_cloud_elasticsearch)
- The [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/elastic?view=azure-cli-latest)
- The Azure [REST API](https://docs.microsoft.com/en-us/rest/api/elastic)
- [PowerShell](https://docs.microsoft.com/en-us/powershell/module/az.elastic/?view=azps-8.0.0#elastic)

but It'd be really helpful for us if we could configure some bicep resource as well to manage this. I imagine it'd be similar to terraform? 

Thank you so much!

**Comment by DaveCTurner** [comment]
Hi @pq43, thanks for your interest in Elasticsearch. The Elasticsearch Service and its integrations aren't managed in this repository so I'm going to close this issue. The best way to proceed would be for you to open a support case about this idea. The support engineer will be able to route it to the right team.
