### ISSUE TITLE
Use DisableFsyncFS in tests to avoid fsync most of the time

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#10518]
Spinoff from #10516 where we fixed ElasticsearchMockDirectoryWrapper to skip fsync most of the time, but really the right way to do this is as Lucene did, at the filesystem level...

**Comment by clintongormley** [comment]
@mikemccand is this a change you're still planning making?

**Comment by mikemccand** [comment]
@clintongormley I'll close it for now ... but I do think we should eventually do this, once we cutover ES tests eventually to use Lucene's randomized MockFS infrastructure ... the change from #10516 was really a hacky workaround ...
