### ISSUE TITLE
[GEO] Modify GeoShapeFieldMapper to accept precision field updates

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#10514]
Related to #10513  There are a couple enhancement discussion points here:
- GeoPointFieldMapper disallows any changes. This makes sense since changing any one of the parameters compromises the integrity of all existing commits.  Thus new commits require a full reindex.
- We should be able to allow the changing of precision on GeoShapeFieldMapper since each existing term is identified in the PrefixTree as either an internal or leaf node.  If we increase the precision, existing terms will terminate at the level of the leaves, so they will remain at the same precision when they were created.  The converse is true, decreasing precision will reduce the resolution of newly created shapes and the leaf nodes will prevent traversal beyond the shapes tree depth.  This will be a separate enhancement issue beyond the scope of fixing this bug.

**Comment by clintongormley** [comment]
@nknize is this still relevant?

**Comment by nknize** [comment]
This is still relevant for `geo_shape` - for now. I'll be revisiting shortly.  

Use case: a mapping is created with highest level of precision (without knowing an optimal precision a priori). Suddenly `geo_shape` queries and inserts become sluggish. This allows precision changes without requiring a full reindex.

**Comment by nknize** [comment]
Now that we have [BKD based GeoShapes](#32039) we are no longer supporting PrefixTrees
