### ISSUE TITLE
ES|QL: document default precision for count_distinct()

### ISSUE THREAD

**Issue by luigidellaquila** [elastic/elasticsearch#105120]
`count_distinct` function accepts two parameters: the first one is the value to count, the second one is the precision.

The second parameter and the algorithm behind it is [well documented](https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-functions-operators.html#esql-agg-count-distinct), but we don't report the default value (that is `3000`). We should document it.

**Comment by leemthompo** [comment]
@luigidellaquila I see this is documented on the [master branch of docs]( https://www.elastic.co/guide/en/elasticsearch/reference/master/esql-functions-operators.html#esql-agg-count-distinct), but I don't have any context on why this update wasn't backported to 8.12

**Comment by alex-spies** [comment]
Wasn't this already added in https://github.com/elastic/elasticsearch/pull/104623?

I can see the default value (`precision_threshold`) in the [most up-to-date docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/esql-functions-operators.html#esql-agg-count-distinct).

**Comment by luigidellaquila** [comment]
oh, my bad, it's sorry for the noise. Closing
