### ISSUE TITLE
[doc] Documentation not clear about uniqueness of ids in an index

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#10515]
A document is uniquely identified by index, type and id. Two documents in an index can have the same id if they have different types. However, the documentation does not seem to explicitly say so anywhere. It would be good to describe this somewhere, probably in http://www.elastic.co/guide/en/elasticsearch/reference/1.x/docs-index_.html
similar to how it is described in the guide:
http://www.elastic.co/guide/en/elasticsearch/guide/master/_document_metadata.html#_id

**Comment by debadair** [comment]
Obsoleted by the removal of types.
