### ISSUE TITLE
ES doesn't decode JSON escapes

### ISSUE THREAD

**Issue by tpievila** [elastic/elasticsearch#10512]
JSON allows any unicode codepoint in Basic Multilingual Plane to be represented with \u escape mechanism. Instead of handling the escape, ES seems to save the data as is. This causes problems later when searching. For example if the original document contained a field with \u00e4, a search like _search?q=name:\u00e4 would find it, but _search?q=name:ä or _search?q=name:%e4 doesn't.

If this is by design, it needs to be documented at http://www.elastic.co/guide/en/elasticsearch/guide/current/_document_oriented.html#_json and other places which currently state that ES uses JSON (without any disclaimers).

**Comment by clintongormley** [comment]
Hi @tpievila 

Elasticsearch does support the `\u` escape, and stores strings as UTF8:

    DELETE test 
    
    PUT test/test/1
    {
      "text": "\u00e4"
    }
    
    GET /test/test/_search
    {
      "aggs": {
        "indexed_terms": {
          "terms": {
            "field": "text"
          }
        }
      }
    }

The above returns:

    {
       "took": 2,
       "timed_out": false,
       "_shards": {
          "total": 5,
          "successful": 5,
          "failed": 0
       },
       "hits": {
          "total": 1,
          "max_score": 1,
          "hits": [
             {
                "_index": "test",
                "_type": "test",
                "_id": "1",
                "_score": 1,
                "_source": {
                   "text": "ä"
                }
             }
          ]
       },
       "aggregations": {
          "indexed_terms": {
             "doc_count_error_upper_bound": 0,
             "sum_other_doc_count": 0,
             "buckets": [
                {
                   "key": "ä",
                   "doc_count": 1
                }
             ]
          }
       }
    }


However your query for `?q=%E4` is in UTF-16, not UTF-8.  This works:

    GET /test/test/_search?q=%c3%a4
