### ISSUE TITLE
All shards failed to start!

### ISSUE THREAD

**Issue by SephenXu** [elastic/elasticsearch#10520]
Hi all,

Since I use multiple paths, this problem often occurs when I restart the cluster, but sometimes this error has inexplicably disappeared. Tried deleting segments.gen files, seem to have no effect.

This is the Debug mode's log when opening one of the index ：    https://gist.github.com/SephenXu/66b92d51eaa63ac85579

jdk:1.6
elasticsearch version : v1.1.2
Really need your help!

Regards,
Sephen Xu

**Comment by markwalkom** [comment]
Please note that ES 1.1.X is not supported on Java 6. See https://www.elastic.co/subscriptions/matrix for more information.

Also the mailing list is your best option for these sorts of operational issues - https://groups.google.com/forum/#!forum/elasticsearch. Github is for code related problems or bugs.

**Comment by SephenXu** [comment]
But the document said, for Java 6, ES versions < 1.2.0 is ok! When did it change?

**Comment by markwalkom** [comment]
Which document?

**Comment by SephenXu** [comment]
https://www.elastic.co/blog/elasticsearch-1-2-0-released
"Elasticsearch now requires Java 7 and will no longer work with Java 6."
Isn't meant that since 1.2.0, es no longer work with java 6, but not contained 1.1.x?

**Comment by markwalkom** [comment]
Supported and required are different things though.
1.2 won't run with java 1.6 at all. 1.1 will but it's not officially supported.

Also Java 6 has been end of life for years now.

**Comment by s1monw** [comment]
give your logs you data is not present where you started elasticsearch did you delete any data files / directories?
