### ISSUE TITLE
monitors are appearing sporadically in kibana (uptime)

### ISSUE THREAD

**Issue by sarahnani** [elastic/elasticsearch#105219]
## Problem
test logs are arriving in elastic (discover), but only some are appearing on monitors (uptime)

1. print of the monitors of one of our tests that appeared at kibana between 1pm and 4pm. That is `scheduled every 13 minutes` and has `4 replicas`:
a. only two monitors appeared:
![image](https://github.com/elastic/elasticsearch/assets/90160557/e0842387-aa18-4505-bcf5-aca5388cd986)
 
2. print of logs in discover from the same test between 1pm and 4pm:
a. logs of 61 tests appeared. They have a `journey/start` filter:
![image](https://github.com/elastic/elasticsearch/assets/90160557/b45b5d7d-591d-4f01-aba9-2d65fb2b4b29)

3. print of logs in discover from the same test between 1pm and 4pm:
a. only 2 logs appeared with the `heartbeat/summary` filter. And coincidentally, they are the same tests that appear on the monitors in kibana:
![image](https://github.com/elastic/elasticsearch/assets/90160557/153768e1-c742-4f22-afbc-b2e4e5551954)

## Question
Can you help me understand why some monitors are not appearing in kibana, even with the data arriving in elastic?

**Versions:**
We use `@elastic/synthetics: 1.0.0-beta.14`
and run our synthetics tests in using docker image: `docker.elastic.co/beats/heartbeat:7.15.0`
and the version of `elasticsearch/kibana is 8.6.0`
![image](https://github.com/elastic/elasticsearch/assets/90160557/75f6a88b-e0ad-4d6a-91eb-cd1036189e2a)

**Comment by kingherc** [comment]
Hi @sarahnani , from skimming through the issue, I believe I read that Elasticsearch truly receives the data but Kibana is not showing it? Then I'd suggest I close this issue in Elasticsearch repository, and for you to re-open the issue in https://github.com/elastic/kibana/ , for Kibana team to comment first on why the data is not appearing. If Kibana team finally detects there is an Elasticsearch issue, feel free to open a new issue in this repository.
