### ISSUE TITLE
put warmer api should check for data read blocks too

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#10522]
Put warmer api currently checks for metadata write blocks only. Given that it executes a search request before storing the warmer, to verify that the search request is valid, it should also check for data read blocks.

Will be solved with #9203

**Comment by rjernst** [comment]
Isn't the fact warmer validation works via an actual search request a problem with validation? Will the query parsing refactoring allow fixing this? I don't think doing a metadata write should require data read...

**Comment by javanna** [comment]
valid point @rjernst , I agree the inner search and requiring to read data as part of a metadata write operation might feel weird. That said this issue was meant to keep track of the missing check for blocks issue that was found in #9203, which we are fixing there. We can then open a new issue if we want to change how the put warmer api works internally.
