### ISSUE TITLE
`lowerAliases` AttributeMap in the `LogicalPlanOptimizer` is never used after being built

### ISSUE THREAD

**Issue by sabi0** [elastic/elasticsearch#105312]
`lowerAliases` AttributeMap in the `LogicalPlanOptimizer`'s `projectAggregations()` method is populated but then never used:

https://github.com/elastic/elasticsearch/blob/6433217efed97199caf9c5740b5871a469f7e928/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/optimizer/LogicalPlanOptimizer.java#L360-L363

**Comment by costin** [comment]
Thank you for the contribution however please be mindful of this section of the [contributing guide](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#reviewing-and-accepting-your-contribution) as reviewing PRs carries a cost:

>We normally immediately reject isolated PRs that only perform simple refactorings or otherwise "tidy up" certain aspects of the code. We think the benefits of this kind of change are very small, and in our experience it is not worth investing the substantial effort needed to review them. 
>This especially includes changes suggested by tools.
