### ISSUE TITLE
Provide better visibility into cost of deeply nested aggregations

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#10538]
As users start to leverage more complex and nested aggregations, they are more likely to run into performance problems due to the combinatorial explosion of nodes in the aggregation tree.

I'm unsure what exactly this would entail.  Perhaps the number of "operations" per layer in the hierarchy, or the number of buckets generated per layer (inclusive of lower layers).

It would be great to provide robust profiling at some point <sub>(**cough* * #6699) </sub>, but I think even simple metrics for now would be very helpful.  For example, I don't think users realize how many operations and buckets are involved in a 5-deep aggregation with a branching factor of 50-per-node.  Especially in situations where an entire "report" is being generated and pruning methods like `breadth_first` don't work.

I'm imagining these statistics either as a top-level element in the agg response, or as a per-layer response element.  It would also be ideal if these were enabled by default, which shouldn't be too difficult if they are just lightweight counters and nothing invasive like timings.

**Comment by clintongormley** [comment]
+1

**Comment by colings86** [comment]
+1

**Comment by smflorentino** [comment]
I've actually been tasked to to do this at work. I have counters for buckets generated as well as buckets pruned at each layer in the aggregation hierarchy, as well as the time taken for the combine phase of aggregation at each data node. Not sure if the time will be useful yet - I'm pretty new to ES and I'm working to get this tested on some production data this week. Still trying to tackle the operations count, too. Hoping to post results and code soon.

**Comment by mpereira** [comment]
+1

**Comment by clintongormley** [comment]
@polyfractal @colings86 now that the profile API has been added for queries, we should look at extending it for aggregations.

**Comment by polyfractal** [comment]
Closed by #18414

![emot-toot](https://cloud.githubusercontent.com/assets/1224228/16586086/1122b2ee-4292-11e6-9d38-8c64cd1ccc90.gif)
