### ISSUE TITLE
[ES|QL] Throwing on STATS BY constant statement

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch#105383]
### Elasticsearch Version

8.13.0

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

The following error:

```
verification_exception\n\tRoot causes:\n\t\tverification_exception: Found 1 problem\nline 1:42: expected an aggregate function but found [1]
```

is thrown by the following query:

```
from a_index | stats avg(numberField) by 1
```

I think the problem is double:
* I would expect to error in the first place as user
* The error message is wrong: expected an aggregate function at `by` level?

### Steps to Reproduce

See above.

**Comment by astefan** [comment]
Another variant of the same inconsistency: `from employees | stats b = count(salary), x = max(languages) by b` throws

```
                "type": "verification_exception",
                "reason": "Found 1 problem\nline 1:65: invalid stats declaration; [b] is not an aggregate function",
                "stack_trace": "org.elasticsearch.xpack.esql.VerificationException: Found 1 problem\nline 1:65: invalid stats declaration; [b] is not an aggregate function
```

**Comment by astefan** [comment]
The issue in the original description doesn't reproduce anymore and it returns the expected outcome.
The second issue I reported doesn't reproduce anymore either.

@fang-xing-esql please make sure we have tests for these two situations and then close this issue. Thanks
