### ISSUE TITLE
[ES|QL] Enrich does not support field text type as matching field

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch#105384]
### Elasticsearch Version

8.13.0

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

The following error is thrown:

```
verification_exception\n\tRoot causes:\n\t\tverification_exception: Found 1 problem\nline 1:33: Unsupported type [TEXT] for enrich matching field [stringField]; only KEYWORD allowed
```

With he following query:
```
from a_index | enrich policy on stringField with var0 = otherField
```

### Steps to Reproduce

See above

**Comment by craigtaverner** [comment]
With recent work to expand the support of more types in ENRICH, it seems possible to take this one as an extension of that. See https://github.com/elastic/elasticsearch/pull/106186
