### ISSUE TITLE
scale_float does not honor limits for long values

### ISSUE THREAD

**Issue by carlosdelest** [elastic/elasticsearch#105361]
### Elasticsearch Version

7.17 / 8.x

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

When using `scaled_float`, there is no range check on the value and scaling factor to be outside the `long` value range.

According to [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html) for `scaled_float`:

> scaled_float - A floating point number that is backed by a long, scaled by a fixed double scaling factor

However, that assumption is not checked on document ingestion. The following mapping:

"properties": {
  "a_scaled_float": {
    "scaling_factor": 1000000,
    "type": "scaled_float"
  }
There's a scaled_float mapping configuration with value 1000000.
So, why did the number 1707339753294418 become 9223372036854.775? Shouldn't it be 1707339753294418000000?

{
  "_index": "test-index",
  "_id": "Z5t_iY0BLRoRMvLbP6e3",
  "_score": 1,
  "_source": {
    "a_scaled_float": 1707339753294418
  },
  "fields": {
    "a_scaled_float": [
      9223372036854.775
    ]
  }
}

This is due to the rounding up done [here](https://github.com/elastic/elasticsearch/blob/17bc83f481ddcfc032f6743a7a64c64000d55740/modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/ScaledFloatFieldMapper.java#L388), which produces a `long` value which is outside range, and thus returns `MAX_LONG`.

As this provides an incorrect result, and the value is outside of the `long` range, the correct behaviour should be to error on the value as other numeric types do.

### Steps to Reproduce

Set a mapping with properties:

```json
PUT test-index
{
      "mappings": {
        "properties": {
            "scaled_float": {
              "type": "scaled_float",
              "scaling_factor": 1000000
            }
        }
      }
}
```

Ingest a document:

```json
PUT test-index/_doc/1
{
  "scaled_float": 1707339753294418
}
```

This should return an error, as the number is outside the `long` range.

**Comment by carlosdelest** [comment]
We need to update docs [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html#_which_type_should_i_use) to provide proper guidance. 

Also, the new behaviour should be corrected depending on the `IndexVersion` the index was created on. In case it's greater or equal than the fix version, it should return an error for a value that is not indexable using a `long` - unless `ignore_malformed` is specified as `true`.

**Comment by benwtrent** [comment]
To move the point that saturation should probably be disabled by default.

```
PUT scaled_float
{
	"mappings": {
		"properties": {
			"value": {
			    "type": "scaled_float",
			    "scaling_factor": 1000000
			}
		}
	}
}

POST scaled_float/_doc
{
	"value": 100000000000000.0
}

GET scaled_float/_search
{
	"fields": [ "value" ],
	"query": {
		"range": {
			"value": {
				"lt": 10000000000000.0,
				"gt": 100000000000000.0
			}
		}
	}
}
```

Returns hits, even though its impossible to have a number that is less than `10000000000000.0` and greater than `100000000000000.0`.
