### ISSUE TITLE
ESQL: Missing MV_ (multi value) functions

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#105322]
### Description

A list of missing [MV_ functions](https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-functions-operators.html#esql-mv-functions) that we should add asap - most of them being scalars:

- [x] mv_append @luigidellaquila https://github.com/elastic/elasticsearch/pull/107001
- [x] mv_slice (~mv_index~) @fang-xing-esql 
- [ ] mv_map
- [x] mv_sort https://github.com/elastic/elasticsearch/pull/106095
- [x] mv_zip @fang-xing-esql 
- [ ] mv_filter
- [ ] mv_find @fang-xing-esql 
- [ ] ~mv_range~

**Comment by nik9000** [comment]
Just as note:

The ones of these that take a multivalue field and output a multivalue field won't get to use the standard multivalue code generation. 

`mv_sort` can use some of the infrastructure in `MultivalueDedupe` - though probably just a tiny bit. There's a sort in there. It might not be worth digging.

I think `mv_map`, `mv_filter`, and `mv_find` might need more discussion. They touch on the multivalue handling syntax we'd talked about earlier.

**Comment by luigidellaquila** [comment]
Thanks for the feedback Nik.
As a small addition, we could also consider a more natural syntax for mv_concat (eg. `field1 || field2`) and for mv_index (eg. (`field[2]`, `field[3..5]`)

**Comment by nik9000** [comment]
It does make sense to have a "normal" array-like syntax for `mv_index`, I think. Maybe an alias. But folks are super used to arrays.

Looks like we have `mv_concat` already. I'm not sure if it makes sense for that to have a special syntax though.

**Comment by luigidellaquila** [comment]
> Looks like we have mv_concat already.

Sorry, it's just me making confusion, I mean `mv_append`, not `mv_concat`

**Comment by costin** [comment]
The functions that made sense in this list have been implemented - closing the ticket from now.
