### ISSUE TITLE
[ES|QL] auto_bucket() throws error on literal number as third argument

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch#105375]
### Elasticsearch Version

8.13.0 @ 7c039b172836b90a77099ca5ba79115dca979b0e

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

The following error:

```
"verification_exception\n\tRoot causes:\n\t\tverification_exception: Found 1 problem\nline 1:11: third argument of [auto_bucket(now(), 5, 5, 5)] must be [datetime or string], found value [5] type [integer]"
```

is thrown with the following queries:

```
row var = auto_bucket(now(), 5, 5, 5)
row auto_bucket(now(), 5, 5, 5)
from index | auto_bucket(now(), 5, 5, 5)
```

In the `auto_bucket` documentation is stated that both the third and fourth args can be either a number of a date string.
I guess this is mostly a documentation issue as the string version is required due to the date type passed as first argument, but need confirmation here.
In such case I would expect:
* to make the documentation more clear on this
* to have a better error message that clarifies the context.

### Steps to Reproduce

See above.

**Comment by astefan** [comment]
This is actually the expected behavior, @dej611. `now()` generates a date, having a number as third and fourth parameters is not accepted. When the first argument is of type date, those two arguments must be either date or string.
When the first argument is a numeric, then third and fourth parameters must be numeric.

**Comment by alex-spies** [comment]
Looking at the supported types table [here](https://www.elastic.co/guide/en/elasticsearch/reference/master/esql-functions-operators.html#esql-bucket), it says that the `from` and `to` parameters for a datetime `field` can be omitted or of type `datetime`. We do not mention string here, which could be improved, and maybe the wording of the description for the `from` and `to` params could be made more specific.
