### ISSUE TITLE
Introducing `ignore_malformed: true` in metrics@settings component template break Fleet

### ISSUE THREAD

**Issue by nchaulet** [elastic/elasticsearch#105314]
### Elasticsearch Version

8.13.0

### Java Version

_bundled_

### OS Version

any

### Problem Description

That PR https://github.com/elastic/elasticsearch/pull/105180 introduced `ignore_malformed: true` in metrics@settings component template this break Fleet installation of packages like `apm`, `fleet-server` fail with an error like this one 

```
Failed installing package [fleet_server] due to error: [ResponseError: illegal_argument_exception Root causes: illegal_argument_exception: field [event.ingested] of type [date] doesn't support synthetic source because it ignores malformed dates]
```

cc @felixbarny 

### Steps to Reproduce

Try to install apm or fleet_server integration in Fleet

**Comment by felixbarny** [comment]
Sorry for that. I've created a fix here: https://github.com/elastic/elasticsearch/pull/105324
