### ISSUE TITLE
[ES|QL] Better error message on invalid string for cidr_match

### ISSUE THREAD

**Issue by dej611** [elastic/elasticsearch#105376]
### Elasticsearch Version

8.13.0

### Java Version

_bundled_

### OS Version

MacOS

### Problem Description

The following error:

```
ql_illegal_argument_exception\n\tRoot causes:\n\t\tql_illegal_argument_exception: Should not fold expression
```

is thrown on the following queries:

```
row var = cidr_match(to_ip(\"127.0.0.1\"), \"a\")
row cidr_match(to_ip(\"127.0.0.1\"), \"a\")
```

As a user, the error message is not easy to decypher. It would be nice to improve it to something like "invalid cidr_block string provided as arg #" or something even better. 

### Steps to Reproduce

See above.

**Comment by astefan** [comment]
There are two aspects here:
- `illegal_argument_exception: Should not fold expression` is a bug and it's related to cird_match function not properly dealing with a constant value for the first argument meaning `to_ip(\"127.0.0.1\")`. I've created https://github.com/elastic/elasticsearch/pull/105403
- the subsequent arguments are meant to be constants and an error should be created. But, in the same line with https://github.com/elastic/elasticsearch/issues/100038 it's a question of where the values are coming from (user or index). Should this be value treated as `null` (and an warning issued) or as an exception (letting the user know the query and the value he/she used is wrong)?

**Comment by shayfeld** [comment]
Hi @astefan ,

I am trying to use CIDR_MATCH in version 8.12.2 and I get the next error
```
Unable to retrieve search results
[esql] > Unexpected error from Elasticsearch: esql_illegal_argument_exception - esql_illegal_argument_exception: Expected a FieldAttribute or MetadataAttribute but received [CIDR_MATCH(client.ip, "127.0.0.2/32", "127.0.0.3/32")]
```
The query
`| WHERE CIDR_MATCH(client.ip, "127.0.0.2/32", "127.0.0.3/32")
`

**Comment by astefan** [comment]
@shayfeld I cannot reproduce this issue. Please, have a reproduceable set of steps and create a new issue. I also suggest trying the same test in the latest ES version; we are moving at a fast pace and many changes take place between versions. Thanks.

**Comment by shayfeld** [comment]
Hi @astefan, 

We reproduced the bug with the support team on version 8.12.2.
I would appreciate it if you looked into the bug to make sure it does not reappear in future versions.
Meanwhile from version 8.13 the methods ">,<,>=,<=" can be used for numbers only and there is no function for IP's like between or range.

**Comment by bpintea** [comment]
@shayfeld,

> I would appreciate it if you looked into the bug to make sure it does not reappear in future versions.

Thanks for the notification, we've established what the root cause was and that it was addressed. We'll add more tests as needed.

> the methods ">,<,>=,<=" can be used for numbers only

The comparisons should work for IP types too (and there are [tests](https://github.com/elastic/elasticsearch/blob/103633aa7b99d8d76b6b50ec6bb18428ec1160ad/x-pack/plugin/esql/qa/testFixtures/src/main/resources/ip.csv-spec#L313) to check it). If this somehow doesn't work, please open another issue.
