### ISSUE TITLE
Internal: replace empty index block checks with global block checks

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#10530]
While working on #9203 we noticed (see [comment](https://github.com/elastic/elasticsearch/pull/9203#discussion_r27642154)) that many `checkBlock()` methods were checking blocks on an empty index like this:

``` java
protected ClusterBlockException checkBlock(PutIndexTemplateRequest request, ClusterState state) {
        return state.blocks().indexBlockedException(ClusterBlockLevel.METADATA, "");
}
```

I think most of this kind of calls can be replaced by a global block check like:

``` java
return state.blocks().globalBlockedException(ClusterBlockLevel.METADATA);
```

**Comment by javanna** [comment]
+1 we might have to dig if that is indeed a 1:1 replacement, but for sure the different checkBlocks variants could be clarified a bit. I think if it's about index blocks they shouldn't accept empty indices ideally.
