### ISSUE TITLE
Fully support IPv6

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#10535]
Currently it's possible to configure ES with IPv6 in some places, however, we don't do tests or qualification for ipv6 for things like multicast (see: #4989).

We should determine the best way to support a full ipv6 environment. One way we could do this is the addition of a `net.use_ipv6: true` setting so that a user has to fully opt-in to ipv6, rather than a mix of both ipv4 and ipv6 that is commonly configured out of the box on machines today.

**Comment by rmuir** [comment]
closed by and #12942 and #12999
