### ISSUE TITLE
Enhance `RankBuilder`s to be able to access additional data after the query phase

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#105472]
Currently, `RankBuilder` is limited to only gather data during the query phase. This limitation is fine for RRF, but is not sufficient to support future ranking enhancements. Collecting data during the query phase means that it must be collected for all documents which is very inefficient for re-ranking on only top documents. We should add a way for additional data to be collected during the fetch phase (or possibly even a new phase in between query and fetch) so re-ranking can take place with data gathered efficiently on only top documents after the fetch phase prior to a search response.

**Comment by pmpailis** [comment]
All relevant PRs have now been merged 🎉 
Closing this one :)
