### ISSUE TITLE
ESQL: Re-enable dependency checks

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#105436]
### Description

Re-enable the optimizers dependency checkers - see:
https://github.com/elastic/elasticsearch/pull/105371#issuecomment-1940377580

**Comment by alex-spies** [comment]
When re-enabling, we should make sure that a failed dependency check results in a 500 response code sent back to the user; therefore, we can't throw a `VerificationException` or any other client exception - we could throw an `IllegalStateException` instead. See discussion [here](https://github.com/elastic/elasticsearch/pull/105371#discussion_r1505453452).

**Comment by bpintea** [comment]
Fixed in #118114.
