### ISSUE TITLE
_cat/recovery should report translog replay progress

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#10542]
`_cat/recovery` and `_recovery` should record the translog progress (percentage or otherwise) in terms of how much phase 3 of recovery has been processed.

For large shards, it can be painful watch automatic relocation's like:

```
my-index-2015-04-10 47    3053258  replica    translog NODE-SOURCE NODE-TARGET n/a        n/a      352   100.0%        20911663130 100.0%
```

The translog is ~20 GB in this example, so it's very hard to guess how long I will have to wait until it finishes replaying it on the target node.

**Comment by ppf2** [comment]
May be related to https://github.com/elastic/elasticsearch/pull/10042

**Comment by pickypg** [comment]
Yep! Didn't see that this made it into 1.5. The above was running 1.4.4.
