### ISSUE TITLE
Gauss decay function gives unexpected results

### ISSUE THREAD

**Issue by ncolomer** [elastic/elasticsearch#10546]
Hi there,

We observed strange behavior when using the gauss decay function ([function score query](http://www.elastic.co/guide/en/elasticsearch/reference/1.x/query-dsl-function-score-query.html)) on a `date`field. It gives unexpected results (that no more look gaussian) when the date difference with `now` becomes too large, resulting into boosting docs that should not be. Here is a [graph](https://gist.github.com/ncolomer/99c2ac85d5a04d7d1fdf#file-results-20-days-png) of the issue.

You can find the detailed procedure, a shell script to reproduce and some results/observations in [this gist](https://gist.github.com/ncolomer/99c2ac85d5a04d7d1fdf).

Tests were run on elasticsearch `1.1.0` and `1.5.1`

**Comment by clintongormley** [comment]
@brwe could you take a look at this please

**Comment by marcelkornblum** [comment]
I feel as though it's related to the date format - I'm using date_optional_time and saw this behaviour. My assumption is that the field value is being translated as milliseconds, while the scale and offset are seen as integers (i.e. date to millisecond discrepancy)...

**Comment by brwe** [comment]
Thanks a lot for the script to reproduce and sorry for the late reply.
It seems to me that when you convert the result to output you neglect the exponents "E-...". A result score from your script like

```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1.0325352E-4,
    "hits": [
      {
        "_index": "test",
        "_type": "test",
        "_id": "1",
        "_score": 1.0325352E-4
      }
    ]
  }
}
```

then becomes 1.0325352 while it should be 0.00010325352. Can you confirm?

**Comment by ncolomer** [comment]
@brwe you're right! Sorry for the noise, it was a stupid mistake on my part. I corrected the related gist.
Thanks for your feedback!
