### ISSUE TITLE
Highlighting targeted fields

### ISSUE THREAD

**Issue by anshudutta** [elastic/elasticsearch#10559]
I am having problems highlighting targeted fields. Lets say I have a query as below
{
   "size": 10,
   "from": 0,
   "query": {
      "filtered": {
         "query": {
            "query_string": {
               "query": "subject:Librar? AND title:event"
            }
         }
      }
   },
   "highlight": {
      "fields": {
         "subject": {
            "number_of_fragments": 0
         },
         "title": {
            "number_of_fragments": 0
         }
      }
   }
}

What I expect is that - all words in the field subject matching the expression "Librar?" to get highlighted and all words in the field title containing "event" should get highlighted. However, I get library in titles as highlighted. If I change the query to .. "subject:Library AND title:event", i get the expected result. The wildcard * or ? seems to throw off the highlighting. Is there a fix or am i doing something wrong.

**Comment by clintongormley** [comment]
Hi @anshudutta 

You're looking for `require_field_match`. See http://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html#field-match
