### ISSUE TITLE
Include OS details in _nodes output

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#10557]
It'd be handy if a call to _nodes gave you some basic information around the OS, things like;
* Vendor - Debian, RHEL, MS etc
* Version - 12.04, Win 7, RHEL 7 etc
* Release - point release info
* Architecture - x32, x64 etc

Dunno how possible this is with sigar, but it'd be awesome on the support side of things.

**Comment by eskibars** [comment]
The _nodes API now (#12049) provides

    os: {
      refresh_interval_in_millis: 1000,
      name: "Mac OS X",
      arch: "x86_64",
      version: "10.11.2",
      available_processors: 4,
      allocated_processors: 4
    }

I think this is about everything you need.  The only partially remaining one is Vendor, which I'm not sure can/be accurately inferred down to the "RHEL" level in any case.  It is down to Linux / Windows / Mac OSX.  Does this fulfill what you need @markwalkom ?

**Comment by markwalkom** [comment]
Yep, thanks :D

**Comment by eskibars** [comment]
Great.  Closing.
