### ISSUE TITLE
PIT request generates crazy id's that cause cross cluster search to fail

### ISSUE THREAD

**Issue by desean1625** [elastic/elasticsearch#105580]
### Elasticsearch Version

8.10.3

### Java Version

_bundled_

### OS Version

docker

### Problem Description

I am seeing issues with PIT search and cross cluster causing thread counts to spike, and other issues. 
I have a few clusters with rolling indexes. There are about 147 open indexes per cluster that match my index-* and 6 clusters.

What looks like happens is the request come in and the wildcards are expanded to open indexes. those indexes are then used to create a pit id.

Since my clusters have 635 open indexes that match this causes the pit request to get an id that is 6229980 bytes long

This pit id is then used for a scroll for each request until all records are retrieved. Kibana export CSV requests 500 records per request. The resulting response for those records is a total of 5486 bytes.

This is causing huge issues in search response times and causes threads max out.

### Steps to Reproduce

Create 600 indexes that match index-*
then 
POST *:index-*/_pit?keep_alive=1m

**Comment by desean1625** [comment]
It appears the pit id that is returned is a base64 representation of not just all the indexes that match but a repeat of all matching indexes for every shard. This creates a very long pit id.

**Comment by DaveCTurner** [comment]
I'm closing this as a duplicates https://github.com/elastic/elasticsearch/issues/80187. It's definitely a problem.
