### ISSUE TITLE
Debian repositories don't work for e.g. armhf although packages are arch independent

### ISSUE THREAD

**Issue by dm8tbr** [elastic/elasticsearch#10551]
Following http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html#_apt
will yield this:  
    W: Failed to fetch http://packages.elasticsearch.org/elasticsearch/1.5/debian/dists/stable/Release \
    Unable to find expected entry 'main/binary-armhf/Packages' in Release file (Wrong sources.list \
    entry or malformed file)

I'm not particularly familiar with the inner workings of apt repositories, but I know for sure that the packages, if downloaded and installed manually, work just fine on ARMhf. It would be nice if users wouldn't need to jump through hoops.

Stumbled into this while trying to set up an ELK stack on an C1 instance of http://scaleway.com

As there is no directory indexing when trying to browse the repository URL, retrieving the packages manually is unnecessarily hard.

**Comment by markwalkom** [comment]
We don't have ARM packages sorry. You can see what is supported here - https://www.elastic.co/subscriptions/matrix

If you have a JVM you can just use the tar.gz/zip.

**Comment by dm8tbr** [comment]
You do realize that I tested your packages on ARM and they work?
*"I know for sure that the packages, if downloaded and installed manually, work just fine on ARMhf."*

After all they are architecture independent. Of course it's your choice to pretend that they don't. Have a nice day.

**Comment by markwalkom** [comment]
I personally don't have ARM to test on, and I don't believe that we have infrastructure to do it either.
So unfortunately, for now, it's not supported.

**Comment by kimchy** [comment]
I think there are 2 levels here:

1. Make the packages work for this case, even though we don't continuously test on ARM.
2. Support ARM officially.

The first part, making our packages work and be installable in this case is worth it I think, @electrical can you maybe chime in into what we need to do here?

The second part is more complex. In order to officially support ARM, we need to make sure we continuously run both Lucene and Elasticsearch tests on it, and commit to fixing or at least raising bugs that are relevant to this platform. Even though there is a version of Java that runs on ARM, we see that those things matter and can expose bugs that are related to the environment it runs on.

@markwalkom, I will reopen the issue and see what @electrical has to say about the packaging aspect, it might be simple fix, dunno....

**Comment by dm8tbr** [comment]
Thanks @kimchy, indeed at no point I was looking for official, or even commercial support, as @markwalkom implied.
Your architecture independent packages, as said earlier, install just fine and from my limited testing the resulting elasticsearch and logstash installations work well. Also because the packaging seems to explicitly work with armhf builds of openJDK for quite a while: https://github.com/elastic/elasticsearch/commit/6356ad2228c47ade41f2f717f60f22363a987211
The only lacking bit is to adjust the deb repository to make the packages discoverable. Preferably for any architecture, if not possible then at least armhf (but be prepared for someone asking about MIPS or powerPC down the road). Sadly I can't help with that detail as I am not that well familiar with Debian repositories and their metadata.

PS: Should you at any point be interested to do testing on ARM, then looking at http://scaleway.com might be wroth it, as they have implemented a "cloud" interface for reasonably powerful, native ARMv7 server hardware. That's where I noticed the issue.
PPS: On a tangent, you may want to explicitly state on your website that anything else than x86/AMD64 is not officially supported, because the page that @markwalkom pointed to, saying it would state so, does in fact nowhere state that. I went and searched the whole website and couldn't find any mention of it, actually. Partly understandable as, aside from architecture specific JRE bugs, it should just work anywhere.

**Comment by rmuir** [comment]
From the lucene side, I don't think ARM is possible to support, its not open source or in openjdk, as opposed to other platforms. 

Aarch64 is different, its open source, etc. But personally i won't spend one iota of time on oracle "commercial" platforms, I don't know about anyone else.

**Comment by dm8tbr** [comment]
@rmuir I'm not sure I follow you. What isn't open source or in openjdk?
If this is about the JDK/JRE, I'm running openJDK on ARMv7 right now:
ii  openjdk-8-jre:armhf  8u40-b27-1  armhf   OpenJDK Java runtime, using Hotspot Zero
That's on what is soon to be released as Ubuntu 15.04, but 14.04 also has openjdk 7.
I couldn't care less about Oracle.

**Comment by rmuir** [comment]
I feel differently about zero/shark. Its open source. 

However for other technical reasons I am suspicious about it, especially its level of testing, additional llvm dependency, etc. This configuration is still called `experimental` by IcedTea. Is it ready for prime time? If not, trying to get lucene's test suite working will not be a fun task.

**Comment by electrical** [comment]
Regarding the repository it is indeed limited to i386 and x86_64/amd64. you can however force it for your case in your repo config.

'deb [arch=amd64] http://packages.elasticsearch.org/elasticsearch/1.5/debian stable main'

**Comment by driegel** [comment]
@electrical Thank you for that info. It helped to install logstash from the apt repo on Raspberry Pi 2B.
My raspberry is currently running Ubuntu 15.10.

There is a good use case for installing Logstash on Raspberry Pi 2/3: collecting logs at a small satellite office and forward them to the central site. I will do some more testing of performance...

+1 to support Logstash on armhf and aarch64

**Comment by vielmetti** [comment]
This has been about a year since the last comment; has there been any activity?

**Comment by hagna** [comment]
It seems like the way to get this working is to install jvm and then dpkg install the .deb.

Java works 

`root@raspberrypi:/home/pi# java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-1~deb9u1-b12)
OpenJDK Client VM (build 25.151-b12, mixed mode)
`

But dpkg install reports these errors and does not put logstash in /opt/logstash/bin/logstash

`root@raspberrypi:/home/pi# dpkg -i logstash-6.2.0.deb 
(Reading database ... 66865 files and directories currently installed.)
Preparing to unpack logstash-6.2.0.deb ...
Unpacking logstash (1:6.2.0-1) over (1:6.2.0-1) ...
Setting up logstash (1:6.2.0-1) ...
Using provided startup.options file: /etc/logstash/startup.options
OpenJDK Client VM warning: TieredCompilation is disabled in this release.
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/open3.rb:206: warning: executable? does not in this environment and will return a dummy value
NotImplementedError: waitpid unsupported or native support failed to load; see http://wiki.jruby.org/Native-Libraries
Excess arguments.
`

**Comment by rjernst** [comment]
The apt repository has undergone a lot of changes since this issue was first created. We have added unified apt repositories for all elastic software, per major version, and also started using aptly to build the repository. Unfortunately, it looks like [aptly also has issues with noarch packages](https://github.com/smira/aptly/issues/585). Additionally, there is already a workaround (installing .deb file directly) as mentioned above. While we may support arm directly in the future, keeping this issue open indefinitely only adds noise to the enormous backlog of open issues in the elasticsearch repo. Thus, I am going to close this issue.

**Comment by rjernst** [comment]
Also please note that I realize the above example using dpkg didn't work, but that was for logstash, and if dpkg doesn't work, neither would installing through apt-get with an apt repository.

**Comment by ainola** [comment]
Thanks for the update, @rjernst. Installation does indeed work with dpkg, one just needs to supply the `--force-architecture` flag.

Here's hoping that aptly will smooth out noarch packages.

**Comment by Grief** [comment]
@hagna I was able to fix the issue with the instruction from https://thesecuritystoic.com/2017/08/home-security-iii-elk-on-a-raspberry-pi/ (slightly modified for my device):

```
apt-get install ant make gcc
git clone https://github.com/jnr/jffi.git
jffi
ant jar
cp build/jni/libjffi-1.2.so /usr/share/logstash/vendor/jruby/lib/jni/arm-Linux
cd /usr/share/logstash/vendor/jruby/lib
zip -g jruby.jar jni/arm-Linux/libjffi-1.2.so

apt install -f
```
And it finishes the configuration:

```Setting up logstash (1:6.5.3-1) ...
Using provided startup.options file: /etc/logstash/startup.options
OpenJDK Client VM warning: TieredCompilation is disabled in this release.
Successfully created system startup script for Logstash
```
