### ISSUE TITLE
Fatal exception while booting Elasticsearch

### ISSUE THREAD

**Issue by carrot016** [elastic/elasticsearch#105619]
### Elasticsearch Version

8.12.1

### Java Version

_bundled_

### OS Version

Linux PTXXXLPF4A722G 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

Underlying file changed by an external force

### Steps to Reproduce

Upgrade from 8.12.0 to 8.12.1 and run elasticsearch using docker

### Logs (if relevant)

elasticsearch-1  | {"@timestamp":"2024-02-19T12:02:08.108Z", "log.level":"ERROR", "message":"fatal exception while booting Elasticsearch", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.bootstrap.Elasticsearch","elasticsearch.node.name":"localhost","elasticsearch.cluster.name":"elasticsearch-localhost","error.type":"org.apache.lucene.store.AlreadyClosedException","error.message":"Underlying file changed by an external force at 2024-02-19T12:02:08.093708886Z, (lock=NativeFSLock(path=/data/elasticsearch/node.lock,impl=sun.nio.ch.FileLockImpl[0:9223372036854775807 exclusive valid],creationTime=2024-02-19T11:28:51.099866109Z))","error.stack_trace":"org.apache.lucene.store.AlreadyClosedException: Underlying file changed by an external force at 2024-02-19T12:02:08.093708886Z, (lock=NativeFSLock(path=/data/elasticsearch/node.lock,impl=sun.nio.ch.FileLockImpl[0:9223372036854775807 exclusive valid],creationTime=2024-02-19T11:28:51.099866109Z))\n\tat org.apache.lucene.core@9.9.2/org.apache.lucene.store.NativeFSLockFactory$NativeFSLock.ensureValid(NativeFSLockFactory.java:179)\n\tat org.elasticsearch.server@8.12.1/org.elasticsearch.env.NodeEnvironment.assertEnvIsLocked(NodeEnvironment.java:1294)\n\tat org.elasticsearch.server@8.12.1/org.elasticsearch.env.NodeEnvironment.nodeDataPaths(NodeEnvironment.java:1053)\n\tat org.elasticsearch.server@8.12.1/org.elasticsearch.env.NodeEnvironment.assertCanWrite(NodeEnvironment.java:1470)\n\tat org.elasticsearch.server@8.12.1/org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:308)\n\tat org.elasticsearch.server@8.12.1/org.elasticsearch.node.NodeConstruction.validateSettings(NodeConstruction.java:484)\n\tat org.elasticsearch.server@8.12.1/org.elasticsearch.node.NodeConstruction.prepareConstruction(NodeConstruction.java:246)\n\tat org.elasticsearch.server@8.12.1/org.elasticsearch.node.Node.<init>(Node.java:181)\n\tat org.elasticsearch.server@8.12.1/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:236)\n\tat org.elasticsearch.server@8.12.1/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:236)\n\tat org.elasticsearch.server@8.12.1/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:73)\n"}

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
