### ISSUE TITLE
Bulk update should support script_file

### ISSUE THREAD

**Issue by jakrol** [elastic/elasticsearch#10567]
Bulk update supports `script_id` to provide the name for an indexed script and `script` for inline script, but no `script_file` for using scripts stored in `config/scripts/`. When I tried to use `script_file` I got an

    {
      "error": "ActionRequestValidationException[Validation Failed: 1: script or doc is missing;]",
      "status": 400
    }

**Comment by clintongormley** [comment]
Hiya @jakrol 

This is fixed in 1.5.0
