### ISSUE TITLE
Use tanuki wrapper for running in debian

### ISSUE THREAD

**Issue by dernasherbrezon** [elastic/elasticsearch#10587]
It gives the following (the most valuable):
* autorestart
* bounce if JVM failed to respond to ping command. Usually when full GC consumes all CPU
(Full list of features at: http://wrapper.tanukisoftware.com/doc/english/introduction.html )

Tanuki wrapper could be easily integrated with init.d on debian:
* https://packages.debian.org/source/sid/service-wrapper-java it already contains start/stop scripts for wrapper configurations.

**Comment by tlrx** [comment]
Tanuki wrapper is a great tool but I'm a bit scared to use it with sysv-init or systemd scripts. For what I've [read)(http://wrapper.tanukisoftware.com/doc/english/prop-ping-timeout.html), there is a chance that in case of a "JVM ping timeout" the wrapper will restart a new JVM without maybe correctly shutting down the first one.

**Comment by dernasherbrezon** [comment]
We used wrapper in production for a long time, but I never encounter such shutdowns. Wrapper just sends normal "kill -9" to JVM. Anyway, if JVM hangs it's not possible to correctly execute shutdown/restart.

Unfortunately I'm not aware about any plans for elastic packaging..As a suggestion I would create separate package configuration for debian. With https://github.com/tcurdt/jdeb and https://github.com/dernasherbrezon/maven-apt-plugin it might be fairly easy.

**Comment by tlrx** [comment]
Debian and RPM packages already exist and are released for every version of elasticsearch (see  https://www.elastic.co/blog/apt-and-yum-repositories). And yes, we're using jdeb :)

I don't like the ping timeout feature because it introduces something outside elasticsearch that can kill/restart a node while it's working or freezing. I'm curious to know what others think about this.

**Comment by clintongormley** [comment]
In fact, we used to use the java service wrapper (see https://github.com/elastic/elasticsearch-servicewrapper) but decided against it because of the licensing.
