### ISSUE TITLE
doc/log enhancement: disk watermark

### ISSUE THREAD

**Issue by faxm0dem** [elastic/elasticsearch#10588]
The documentation and key name of the cluster setting `cluster.routing.allocation.disk.watermark.low` is inconsistent with the message from the logfile. When value is set to default of `85%` (according to [documentation](http://www.elastic.co/guide/en/elasticsearch/reference/1.5/index-modules-allocation.html#disk)), the warning message says:

```
low disk watermark [15%] exceeded
```

It is IMHO misleading

**Comment by dakrone** [comment]
You're right, this should be pretty easy to fix by either standardizing on displaying the used space or free space everywhere.

**Comment by mkis-** [comment]
Hello! I've attempted a fix for this by changing the logging so that it displays used space when dealing with percentages.

I've also created a pull request.
