### ISSUE TITLE
_tier values not filled in Kibana Discover despite advanced settings properly configured 

### ISSUE THREAD

**Issue by Danouchka** [elastic/elasticsearch#105817]
### Elasticsearch Version

Elastic Cloud 8.12.2  on GCP Belgium

### Java Version

_bundled_

### OS Version

NA

### Problem Description

in Kibana discover _tier field has no value  neither in the top left list of fields , neither in doc view 
But with _search endpoint, 
- you can add a filter on terms such as "data_content" , "data_warm" and results are properly returned  
- For unknown reason,  filtering on "data_hot" returns no result ( whereas hot nodes are tagged as both data_content and data_hot) 

<img width="1623" alt="Capture d’écran 2024-02-26 à 21 40 17" src="https://github.com/elastic/elasticsearch/assets/48563314/a52119ad-47cd-4cbf-9fb2-1f77b005c06c">

<img width="1903" alt="Capture d’écran 2024-02-26 à 21 40 29" src="https://github.com/elastic/elasticsearch/assets/48563314/43b24fe3-405c-40d4-9b17-27e4615882a9">

<img width="1894" alt="Capture d’écran 2024-02-26 à 21 40 39" src="https://github.com/elastic/elasticsearch/assets/48563314/79809f04-c363-400f-b57b-699cfbf6fc3a">

<img width="1889" alt="Capture d’écran 2024-02-26 à 21 40 57" src="https://github.com/elastic/elasticsearch/assets/48563314/93e6d69c-7544-4be3-9373-a5a2063e3fdf">

<img width="1416" alt="Capture d’écran 2024-02-26 à 21 45 55" src="https://github.com/elastic/elasticsearch/assets/48563314/c3304b07-56a5-4035-9fd5-127f20647d99">

### Steps to Reproduce

a) Add _tier field in the list of metadata fields in Stack Management > Kibana > Advanced Settings > metaField 
b) Go to Kibana on any indice, _tier field has no value  neither in the top left list of fields , neither in doc view 
c) But with _search endpoint, you can add a filter on terms such as "data_content" , "data_warm" and results are properly returned  but For unknown reason,  filtering on "data_hot" returns no result ( hot nodes are tagged data_content and data_hot)

**Comment by Danouchka** [comment]
cc @kertal @mattkime

**Comment by javanna** [comment]
It is not clear to me whether this is an Elasticsearch problem or a Kibana problem. Given that `_search` seems to work properly, I would lean towards this being a Kibana problem. @kertal do you have more info that help us understand where the problem is? Thanks!

**Comment by kertal** [comment]
@javanna sure. I can answer the Kibana part of this. When triggering a search to ES in Discover, there's no `_tier` value as a meta field available in the search results (`_index`, `_id`,`_version`,`_score`). I haven't seen a `_tier` field so far. I assume it works as expected. The question: Is there a way to enable a `_tier` or `_tiers` field to be returned in the result set as meta field?

**Comment by javanna** [comment]
thanks for clarifying @kertal, have you tried requesting the `_tier` field explicitly?

**Comment by kertal** [comment]
@javanna TIL, this works, so using `fields` of search, we can request meta fields, however, when requesting just `*` , is there a way to request `*` for available meta fields?

**Comment by javanna** [comment]
fields=* will only return the meta fields that are returned by default, e.g. `_ignored` but not `_tier`. You then need to do `fields=*,_tier` I believe.

**Comment by kertal** [comment]
@javanna thx, this could be considered. where can we find the meta fields returned by default? just learned about `_ignored`, which I might have ignored in the past :)

**Comment by kertal** [comment]
I think this can be closed, added a new issue in Kibana: https://github.com/elastic/kibana/issues/178179

**Comment by javanna** [comment]
> where can we find the meta fields returned by default?

you mean docs that says which meta fields are returned by default, or where can you find those in the search response?

**Comment by kertal** [comment]
which meta fields are returned by default, but I found answers for that:
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-fields.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.html#search-fields-param
