### ISSUE TITLE
Continuous Profile-Guided Optimization (PGO) platform based on Elastic Universal Profiling

### ISSUE THREAD

**Issue by zamazan4ik** [elastic/elasticsearch#105802]
### Description

Hi!

I evaluate multiple approaches to applying Profile-Guided Optimization (PGO) to the IT ecosystem (if you are interested you can check the results [here](https://github.com/zamazan4ik/awesome-pgo/)). According to my tests, PGO helps with achieving better performance for many existing applications.

There are two major kinds of PGO: Instrumentation and Sampling (about both of them you can read the Clang compiler [documentation](https://clang.llvm.org/docs/UsersManual.html#differences-between-sampling-and-instrumentation)). Despite Instrumentation-based PGO is much more well-known in the community (from my experience), it has major drawbacks. One of the biggest drawbacks is the performance overhead during the profiling phase.

To resolve this issue, Google invented Sampling PGO (also sometimes called AutoFDO (https://github.com/google/autofdo)). This approach uses `perf`-based profiling to collect the PGO profiles directly from the production environment, and then use them during the optimization phase. More details about the whole ecosystem around AutoFDO in Google can be found in their [paper](https://research.google/pubs/pub45290/).

Unfortunately, right now there is no open-source ecosystem to support the AutoFDO approach at scale as it's done in Google. But the Elastic Universal Profiling platform looks like an important piece in this pipeline (we can say it could replace Google Wide Profiler (GWP) in the AutoFDO setup in Google).

My idea is to think about building the same system as Google has internally but based on Elastic Universal Profiling. It could be an interesting opportunity for Elastic to become a unique solution in the continuous optimization area.

It would be great to hear thoughts about the idea from the Elastic devs.

Thank you for your attention.

P.S. Similar discussion in the Grafana Pyroscope project: https://github.com/grafana/pyroscope/discussions/2783

**Comment by gbanasiak** [comment]
@zamazan4ik Many thanks for this valuable suggestion. The best place to have this discussion would be https://discuss.elastic.co/c/observability/profiling. Could you start a new topic there?

We prefer to use issues in this repository to track bugs and feature requests specific to Elasticsearch search engine. I hope you don't mind if I close this issue.

**Comment by zamazan4ik** [comment]
Oh, sure. Didn't know about that platform. I will create a discussion there - thanks!

**Comment by gbanasiak** [comment]
Great, please post a link here for cross reference. Thank you!

**Comment by zamazan4ik** [comment]
Here we go: https://discuss.elastic.co/t/continuous-profile-guided-optimization-pgo-platform-based-on-elastic-universal-profiling/354605
