### ISSUE TITLE
elasticsearch using secrets - demands 400 perm, but docker default is 444

### ISSUE THREAD

**Issue by mamema** [elastic/elasticsearch#105828]
### Elasticsearch Version

8.12.2

### Installed Plugins

none

### Java Version

_bundled_

### OS Version

docker 25.0.2 on debian 12

### Problem Description

using build in docker secrets with docker swarm and map the secret to /run/secrets/secret
are having file permission 444 but elastic search demands 400 and refuses to boot further.

user is unable to change permission, as /run/secrets/ is a read only file system

### Steps to Reproduce

using build in docker secrets with docker swarm and map the secret to /run/secrets/secret

map secret to env:
- ELASTIC_PASSWORD_FILE=/run/secrets/secret

**Comment by brianseeders** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by mamema** [comment]
hmm, are you sure? If the docker host implements 444 with docker secrets which the user cannot change in docker swarm with docker secrets, then demanding 400 by an a ipplication which then refuses to boot, i am considering as a bug.
this is a dead loop the only change possible is that elasticsearch docker accepts the standards from docker.

**Comment by sheran** [comment]
@mamema I had this same issue trying to deploy ES to my docker swarm. I traced it here: https://github.com/elastic/elasticsearch/blob/de6ece610e6abdfb288803a8ac7bcbc2e976fbc0/distribution/src/bin/elasticsearch-env-from-file#L58

I added perm 444 and rebuilt the ES docker image and can confirm that it works. Currently I have an arm64 image up on my [dockerhub](https://hub.docker.com/repository/docker/sherangee/elasticsearch/general).
