### ISSUE TITLE
simply scripts to only support one file type in script engines

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#10598]
In the onFileInit method as part of the class ScriptService it appears that an assumption is made that there will always only be one type of file for each of the ScriptServiceEngines that is available.  This can be simplified by only allowing one type of file per ScriptServiceEngine since that assumption is already made anyway.

**Comment by s1monw** [comment]
+!

**Comment by javanna** [comment]
Hi @jdconrad you mean [here](https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/script/ScriptService.java#L486)? If that's the case that is not the assumption we are making there, we have to pick one type, which one doesn't matter, the call will return the same result for the same engine.

I am all for simplifying this in master, but I think we properly support multiple types, this is not a bug. The only script engine that I can remember which supports multiple types is javascript (`js` and `javascript`), maybe we want to change that at some point and change the `ScriptEngineService` interface but that's a breaking change for every script engine plugin.

**Comment by rjernst** [comment]
Sure this is breaking, but I also don't see how this "feature" is actually helping anything.  +1 to break in master. And I would just remove the `javascript` type.

Do we also really need separate extension/type? They seem redundant? It seems like we could have one, and that is both the `lang` parameter value, as well as the extension for on disk scripts.

**Comment by javanna** [comment]
I agree that we don't need multiple types. Breaking all scripting plugins is a bit scary but might be worth it here, on master only. Maybe @dadoonet and @uboness want to comment as well.

That said, @jdconrad if I got this right and what you found is not a bug, can you please update the title and description of the issue or open a new one? It feels weird that the whole (good) discussion started from a bug that is not :)

**Comment by jdconrad** [comment]
@javanna That's the location.  After further reading of the code, I realize my initial understanding was incorrect.  I still believe that we can simplify this supporting only one file type and users should be able to follow that convention via the documentation.

**Comment by clintongormley** [comment]
+1 to having only a single file type per script language

**Comment by dadoonet** [comment]
About extension/type separation, we just need to think of some languages like ruby. I think that a common extension is rb not ruby.
So it would mean that language type would have to be set as rb. Not a big deal though.

**Comment by clintongormley** [comment]
Let's do this

**Comment by dakrone** [comment]
I'm going to do this as part of https://github.com/elastic/elasticsearch/pull/18226
