### ISSUE TITLE
Display full col name when header option is used with cat apis

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#10599]
Currently, if you specify header options for the cat api using the `h=` and `v` options, eg. `http://localhost:9200/_cat/thread_pool?h=host,ip,bs,ba,bq,br&v`, it returns the short form for the header/column names in the verbose header output which is not that user friendly.  It will be nice to provide an option for it to display the full column name when header options are used.

```
host   ip           bs ba bq br 
Iceman 192.168.56.1  4  0  0  0 
```

**Comment by clintongormley** [comment]
Hi @ppf2 

This is already supported - just use the long names in the `h=` spec, eg:

    GET _cat/thread_pool?h=bulk.active,bulk.size&v

returns:

    bulk.active bulk.size 
              0         4 

And the short/long names can always be accessed via:

    GET _cat/thread_pool?help

**Comment by ppf2** [comment]
oh nice !
