### ISSUE TITLE
Report max queue size reached for thread pools

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#10601]
When tuning bulk thread pool queue sizes, it can be helpful if there is a way to report on the max queue size "reached" so far to help developers/admins plan ahead for further queue size increases where appropriate (without waiting for rejections to occur).

**Comment by clintongormley** [comment]
A max queue size reached probably isn't that much use, given that it is the max size since the node was first started.  A high value could come from a one-off abnormality.  Much more useful to monitor the current queue size over time. I don't think we should implement this.
