### ISSUE TITLE
Acknowledged: false for successful delete operations

### ISSUE THREAD

**Issue by magnhaug** [elastic/elasticsearch#10607]
When deleting a "large" index (13M documents), it gives "acknowledged: false", even though no warnings are logged. The index is correctly deleted from all nodes. When deleting a smaller index, it says "acknowledged: true".
What is the semantics here? If it was due to a timeout, I'd expect a "ProcessClusterEventTimeoutException".
As a user, I'd be less confused if the API would be consistent, so I wouldn't go looking for stray data that was not deleted properly in case of a "acknowledged: false".

Example:
```
~$ curl -XDELETE localhost:2500/small_index?pretty
{
  "acknowledged" : true
}
~$ curl -XDELETE localhost:2500/big_index?pretty
{
  "acknowledged" : false
}
```

I'm running a clean install of ES 1.4.2.

**Comment by clintongormley** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/11258
