### ISSUE TITLE
master left problem

### ISSUE THREAD

**Issue by hp-NPH** [elastic/elasticsearch#10604]
Hi ,We have four nodes(1 master and data  node  &&  3 only data nodes) ,however,when the index increased to  134044389 ,our data nodes often left the cluster. After I looked the ES logs,I discovered that the GC time was too long .
        the  dropped data node log just like the following:
![tm](https://cloud.githubusercontent.com/assets/10142769/7152859/a814890c-e375-11e4-9434-7726da66bb83.png)
       and the master node log like this:
 
![tm 111](https://cloud.githubusercontent.com/assets/10142769/7152893/5874382e-e376-11e4-875d-0baccba218f1.png)
      
      and our server info  : 
       RAM  8g  
       ES_HEAP_SIZE 4G
        
      Who can help me,Thanks for all !  (My English is very poor...)

**Comment by dadoonet** [comment]
No problem with your english.
But Please ask question on the mailing list. We can help you there.
You should provide there also your full logs (use gist.github.com to share them).



Does not look like an issue. Closing.
