### ISSUE TITLE
Enable SignificanceHeuristics which are aware of the term being scored

### ISSUE THREAD

**Issue by dimitardenev** [elastic/elasticsearch#10613]
We would like to implement custom significance heuristic for the significant_terms aggregation which are aware of the term being scored. In our use case the terms have part-of-speech tags as prefixes which we want to take into account when we compute the score. 

Here is an example: 
* the terms "blue" and "car" have the absolutely same document frequencies in the index
* blue is an adjective and is indexed as adj_blue 
* car is a noun and is indexed as n_car 
* nouns have score modifier 1.3, adjectives have score modifier 0.3

We want to to multiply the term scores from an underlying significance heuristic (jlh score, mutual information, chi square, gnd) with the respective modifier.

**Comment by markharwood** [comment]
Thanks for opening this issue. The solution will add an extra parameter to the SignificanceHeuristic.getScore(..) method with an object representing the term being scored.

>We want to to multiply the term scores from an underlying significance heuristic

We suggest that your custom heuristic simply wraps and calls a choice of existing heuristic, multiplying the result by your POS weightings for the given term. We don't want to complicate the Query DSL to support this nesting of scoring functions as it is probably an exceptional use case.

**Comment by markharwood** [comment]
I coded up the solution to this but it presents a couple of issues:
1) It exposes internals of the term selection process that we may later want to refactor. Ultimately we would like to avoid dealing with terms and use global ordinals internally for efficiency's sake and exposing the terms to scoring heuristics would prevent us from making such a change or complicate it.
2) It adds extra performance costs to the scoring process as raw values (long primitives or ByteRefs) have to be materialized as Long or String values to be provided as context to scoring heuristics e.g. the Scripted heuristic needs to access to Long or String objects. This adds overhead and is extra work for the garbage collector.

Given these two general concerns and the fact that this use case is an uncommon one we have chosen not to implement this feature at this stage. 
There is a work-around for you in that you can potentially channel your parts-of-speech values to different indexed fields (eg. "adjText" and "nounText") and perform significant terms analysis on those fields separately.
If sufficient numbers of other people request access to terms in scoring heuristics we may choose to reconsider this feature. Thanks again for opening this issue and prompting this investigation.

**Comment by dimitardenev** [comment]
Hello, 
first of all, thanks for the time you took to look in such a depth at the issue! I understand that an implementation will slow down considerably the computation time. Fortunately, the suggested work-around will solve our problem.

**Comment by markharwood** [comment]
Just out of interest - have you demonstrated improved results by splitting nouns/adjectives or is this just theoretical at the moment? My assumption was that significance could always be drawn from pure stats without the need for special consideration of actual values.

**Comment by dimitardenev** [comment]
This theoretical at the moment. It is promising though. It solves a long-standing problem with the right boosts for nouns, adjectives and verbs. Now we can return top-K nouns, verbs, adjectives to our clients and avoid merging ourselves. No need anymore to express business logic by separate boosts for nouns, verbs and adjectives.
