### ISSUE TITLE
[GEO] Consolidate duplicate Bounding Box classes

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#10617]
Aggregations, Filters, Builders all have some form of a Bounding Box implementation. This task is to consolidate all of these duplicate "rogue" classes into one (possibly in GeoUtils).

Note: this consolidation could eventually be replaced w/ an integration of the Apache SIS geometry package and using the Envelope geometry.

**Comment by clintongormley** [comment]
@MaineC has this been resolved by https://github.com/elastic/elasticsearch/pull/11969 ?

**Comment by MaineC** [comment]
@clintongormley no, #11969 only touches the GeoBoundingBox*QueryBuilder*. What I believe @nknize is talking about is how bounding boxes are represented in general - though he'd have to comment on which classes in particular he is referring to. The two I found with a quick search github:

* [Internal class of InternalGeoBounds](https://github.com/elastic/elasticsearch/blob/148265bd164cd5a614cd020fb480d5974f523d81/core/src/main/java/org/elasticsearch/search/aggregations/metrics/geobounds/InternalGeoBounds.java#L202)
* [Two points in GeoBoundingBoxQueryBuilder](https://github.com/elastic/elasticsearch/blob/76fa9023b6378681de34672d2e94227e8b464cfd/core/src/main/java/org/elasticsearch/index/query/GeoBoundingBoxQueryBuilder.java#L59)

**Comment by nknize** [comment]
There's also 2 BoundingBox classes within Lucene. 

The full objective is to refactor all geometry logic out of elasticsearch and into lucene. This issue starts small by simply consolidating all of the different bounding box classes.

**Comment by adamrmelnyk** [comment]
Are you still looking to make this change? I did a quick search but only came up with those two classes. Did you mean you wanted to make this an inner class in GeoUtils or just under commons/geo?

**Comment by Shubhangi2901** [comment]
Hi @nknize if this issue is still open i would like to work on this! :)

**Comment by abprash** [comment]
Hi @Shubhangi2901 , mind if i take a shot at this? :)

**Comment by Shubhangi2901** [comment]
Hi @abprash I have actually made some progress on it and am hoping to an initial commit soon. Once I push the update, if there are other big parts left, I'd love to collaborate if you'd like.

**Comment by abprash** [comment]
@Shubhangi2901 , sure, sounds good. Thanks!

**Comment by talevy** [comment]
Hi @abprash and @Shubhangi2901! awesome to hear you two decided to collaborate on this. Just following up to see if there is anything we can do to help!

**Comment by talevy** [comment]
I believe much of the parsing logic has been consolidated in `GeoBoundingBox.parseBoundingBox` in #50253. 

How was your attempt at consolidating more of the code going @abprash and @Shubhangi2901?

**Comment by talevy** [comment]
Closing due to some latest cleanup and #50253
