### ISSUE TITLE
Timestamp querying, sliding window

### ISSUE THREAD

**Issue by sgerlach** [elastic/elasticsearch#10615]
When querying Elasticsearch often users need to be able to look at a time window for a period of time. Currently, Kibana is handling this translation of window from "Last x Days" to the timestamp and adding the query parts
```
"@timestamp" : {
   "gte": [timestamp]
}
```
Would be an awesome feature to be able to add the relative times to the elasticsearch query and have elasticsearch do the timestamp processing
ie
```
"@timestamp": {
    "from": "x days ago"
}
```
or something like that

**Comment by dadoonet** [comment]
I think you can do it using `now/d-1d` or `now-1h` for example.

have a look at http://www.elastic.co/guide/en/elasticsearch/guide/current/_filter_order.html

May be I misundertood your question or your question is more for Kibana project?

**Comment by sgerlach** [comment]
Nope, that's exactly what I meant! My search-foo is lacking this morning!
