### ISSUE TITLE
Is this a bug for SQL?

### ISSUE THREAD

**Issue by Gitttttttt** [elastic/elasticsearch#106157]
### Elasticsearch Version

8.12.2

### Installed Plugins

ik

### Java Version

1.8.0_121

### OS Version

centos7

### Problem Description

I am testing according to the documentation（https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-getting-started.html ）
The expected result is this:
![image](https://github.com/elastic/elasticsearch/assets/38375081/846c1f04-33a6-4649-9733-dd6045396019)

But the results are not in line with expectations, it's like this：
![image](https://github.com/elastic/elasticsearch/assets/38375081/3b5a20de-81bd-4eda-9d67-18f702442c18)

### Steps to Reproduce

follow the doc: https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-getting-started.html
with es8.12.2

**Comment by mosche** [comment]
Thanks for reporting @Gitttttttt. 

Please do avoid posting images and favor markdown formatted text instead. Images can't be searched and make it difficult to copy paste content in order to reproduce issues.

Java 1.8 isn't supported by 8.12.2, so I suspect you're using the bundled JDK. 

Unfortunately, I wasn't able to reproduce the issue using the ES Docker distribution based on the information provided. Can you provide more accurate steps to reproduce this?

**Comment by Gitttttttt** [comment]
@mosche 

Could it be because there is a problem with my plugin installation? When I used the command to install the elasticsearch-analysis-ik-8.12.2.zip, it reported an error:
![image](https://github.com/elastic/elasticsearch/assets/38375081/de204aaa-a7bf-4dde-a155-2e91b15c5b94)

Then I directly unzipped the  zip package to the plugins directory and restarted es. I found that the plugin was loaded successfully.
![image](https://github.com/elastic/elasticsearch/assets/38375081/8cc61796-52cd-451e-8476-83fd44ea9f55)

Next, all the operations I did came from the document (https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-getting-started.html)

First, I created an index：
`
[es@master1 elasticsearch-8.12.2]$ curl -u es:111111 --cacert config/certs/http_ca.crt -H 'Content-Type: application/json' -X POST "https://172.16.60.112:9200/library/_bulk?refresh"  -d'
{"index":{"_id": "Leviathan Wakes"}}
{"name": "Leviathan Wakes", "author": "James S.A. Corey", "release_date": "2011-06-02", "page_count": 561}
{"index":{"_id": "Hyperion"}}
{"name": "Hyperion", "author": "Dan Simmons", "release_date": "1989-05-26", "page_count": 482}
{"index":{"_id": "Dune"}}
{"name": "Dune", "author": "Frank Herbert", "release_date": "1965-06-01", "page_count": 604}
'
`
And then, I found the problem when querying（The correct result should have two pieces of data，but just one）:
`
[es@master1 elasticsearch-8.12.2]$ curl -u es:111111 --cacert config/certs/http_ca.crt -H 'Content-Type: application/json' -X POST "https://172.16.60.112:9200/_sql?format=txt&pretty"  -d'
> {
>   "query": "SELECT * FROM library WHERE release_date < '1995-01-01'"
> }
> '
    author     |     name      |  page_count   |      release_date      
---------------+---------------+---------------+------------------------
Frank Herbert  |Dune           |604            |1965-06-01T00:00:00.000Z


Below is all the data：

[es@master1 elasticsearch-8.12.2]$ curl -u es:111111 --cacert config/certs/http_ca.crt -H 'Content-Type: application/json' -X POST "https://172.16.60.112:9200/_sql?format=txt&pretty"  -d'
{
  "query": "SELECT * FROM library"
}
'
     author     |     name      |  page_count   |      release_date      
----------------+---------------+---------------+------------------------
James S.A. Corey|Leviathan Wakes|561            |2011-06-02T00:00:00.000Z
Dan Simmons     |Hyperion       |482            |1989-05-26T00:00:00.000Z
Frank Herbert   |Dune           |604            |1965-06-01T00:00:00.000Z
`

**Comment by bpintea** [comment]
> I found the problem when querying（The correct result should have two pieces of data，but just one

This test doesn't reproduce as a regression, as in your case. It might be a setup issue, can you try a "clean" Elasticsearch installation with no external plugins and see if that will yield different results?
Also, if that's not already the case, you might also want to run Elasticsearch with the bundled JDK.

You can also try a range query directly, without using SQL, to validate your data:
```
GET library/_search
{
  "query": {
    "range": {
      "release_date": {
        "lt": "1995-01-01"
      }
    }
  }
}
```

**Comment by Gitttttttt** [comment]
@bpintea 
I upgraded jdk21 and uninstalled the ik plug-in, but the result is still the same!

`
[es@master1 elasticsearch-8.12.2]$ curl -u es:111111 --cacert config/certs/http_ca.crt -H 'Content-Type: application/json' -X POST "https://172.16.60.112:9200/_sql?format=txt&pretty"  -d'
> {
>   "query": "SELECT * FROM library WHERE release_date < '1995-01-01'"
> }
> '
    author     |     name      |  page_count   |      release_date      
---------------+---------------+---------------+------------------------
Frank Herbert  |Dune           |604            |1965-06-01T00:00:00.000Z
`

But, when I query using the original method, I get the correct results:

`
[es@master1 elasticsearch-8.12.2]$ curl -u es:111111 --cacert config/certs/http_ca.crt -H 'Content-Type: application/json' -X POST "https://172.16.60.112:9200/library/_search?format=txt&pretty"  -d'
> {
>   "query": {
>     "range": {
>       "release_date": {
>         "lt": "1995-01-01"
>       }
>     }
>   }
> }
> '
{
  "took" : 126,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 2,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "library",
        "_id" : "Hyperion",
        "_score" : 1.0,
        "_source" : {
          "name" : "Hyperion",
          "author" : "Dan Simmons",
          "release_date" : "1989-05-26",
          "page_count" : 482
        }
      },
      {
        "_index" : "library",
        "_id" : "Dune",
        "_score" : 1.0,
        "_source" : {
          "name" : "Dune",
          "author" : "Frank Herbert",
          "release_date" : "1965-06-01",
          "page_count" : 604
        }
      }
    ]
  }
}
`

**Comment by Gitttttttt** [comment]
Maybe there's something wrong with the SQL mode.

**Comment by bpintea** [comment]
Sorry, should have payed more attention to the way you're using curl:
```
-d'
{
"query": "SELECT * FROM library WHERE release_date < '1995-01-01'"
}
'
```
you're using simple quote both for embedding the query object and within the query. The inner quotes are lost and the query becomes equivalent to `SELECT * FROM library WHERE release_date < 1995-01-01`, i.e. `...WHERE release_date < 1993` which is also allowed, and which interprets `1993` as milliseconds.

What you need to do is either:
* use quotes only: `-d"{ \"query\": \"SELECT * FROM library WHERE release_date < '1995-01-01'\" }"`
* or put the object query into a file and use `--data-binary "@path_to_that_file"` curl argument.


Will close this issue as there's no defect, but feel free to open a new one if you find one. 
Feel free to also use our forum, where other these issues might have been [answered already](https://discuss.elastic.co/t/error-with-sql-query-with-curl/295232/2).
