### ISSUE TITLE
elasticsearch using wrong jvm ,force?

### ISSUE THREAD

**Issue by rrphotosoft** [elastic/elasticsearch#10611]
Hi,
I recently downloaded es 1.5.0.
When I try a simple bin/elasticsearch
I get the following:
    - RuntimeException[Java version: 1.7.0_51 suffers from critical bug https://bugs.openjdk.java.net/browse/JDK-8024830 which can cause data corruption.
Please upgrade the JVM, see http://www.elastic.co/guide/en/elasticsearch/reference/current/_installation.html for current recommendations.
If you absolutely cannot upgrade, please add -XX:-UseSuperWord to the JVM_OPTS environment variable.
Upgrading is preferred, this workaround will result in degraded performance.]

However my java version is correctly set:
    java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~precise1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

What could be wrong here? How do I force it to use the right version? 
I am downgrading to 1.3.5, because I don't see this error with 1.3.5

Regards,
Bhargav

**Comment by rmuir** [comment]
Look and see if JAVA_HOME is set to an older one.

**Comment by rrphotosoft** [comment]
Hi,
My java home variable is set to the correct java.
In both the .bashrc and the /etc/environment.

**Comment by rmuir** [comment]
The java version it prints out is the version it is reporting. So something about your environment is off, you are not using the java you think you are.

**Comment by rjernst** [comment]
> I am downgrading to 1.3.5, because I don't see this error with 1.3.5
First, this won't work if you have indexed any documents (Lucene is not "forwards compatible", it has no idea how to read data written from a newer version).

But more importantly, the error is there because this is a serious bug that can cause index corruption. Ignoring it by trying to mask the problem is not going to save you from the potential corruption.

@rmuir is right, something is not right about your environment.

**Comment by rrphotosoft** [comment]
Hi guys,
Thanks for the input, but I'm not getting very far with this.
Where does ES look to determine the JVM?
I can't think of anything more than setting the JAVA_HOME variable.
If you have any suggestions on how I can try to debug this, it would be really useful.
Furthermore, with respect to forward compatibility, I won't be facing that, the data was originally indexed on 1.3.5, I wanted to update to leverage some of the newer features.

Someone else seems to have faced a similar issue, but there was no answer to the question on SO, wonder what they did to solve it:
http://stackoverflow.com/questions/28924660/elasticsearch-using-incorrect-jvm

Thanks again,
Bhargav

**Comment by rjernst** [comment]
Are you on a *nix machine? Try running these commands:
```
$ readlink `which java`
/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java
$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home
```

If you do not have JAVA_HOME set (are you sure it is set for the user running elasticsearch? is elasticsearch started via init.d?) then elasticsearch uses whichver java it finds on `PATH`.

**Comment by rrphotosoft** [comment]
Hi,
1.I am not starting es using init.d
2.I have checked rechecked and triple checked the home variable, it correctly points to the upgraded version of JAVA.
3.The issue is that the JAVA that ES is picking up is different from the one on my HOME  variable.
Is there any way to debug this through the .jar files and look at what path ES  is using and why?
Which files should I be looking at? I don't mind compiling from source. I'm getting stonewalled trying to use newer features, and each time, I find that upgrading to 1.5+ is what I need to be doing ,a version upgrade is now really important.
I hope someone can help out here.
Regards,
RR.

**Comment by imotov** [comment]
@rrphotosoft if you are running elasticsearch using `bin/elasticsearch` script, java selection occurs [here](https://github.com/elastic/elasticsearch/blob/1.5/bin/elasticsearch#L111).  You don't need to recompile anything to debug it. It's just a shell script. Could you run the following command to make sure that JAVA_HOME is configured correctly:
```
ls -l $JAVA_HOME/bin/java
```

**Comment by dakrone** [comment]
Closing since we have not heard back in over 6 months.
