### ISSUE TITLE
Cannot install Elasticsearch through `homebrew`

### ISSUE THREAD

**Issue by ProjectsOfMLee** [elastic/elasticsearch#106264]
### Elasticsearch Version

latest 8.12

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 22.6.0 arm64

### Problem Description

When I follow the official documentation to run 

```
brew tap elastic/tap

brew install elasticsearch-full
```
I get: 

Error: elastic/tap/elasticsearch-full: undefined method `plist_options' for Formulary::FormulaNamespace8aeab54ffd9c1d4653b79411e18c1af3005cf750e04fe35e27a9a54f1dba4b3f::ElasticsearchFull:Class

Already checked `brew` is up-to-date.

### Steps to Reproduce

1. install homebrew
2. open terminal 
3. copy the two lines of installation mentioned above

**Comment by mayya-sharipova** [comment]
For MacOS, you should install Elasticsearch either from an archive or docker. [Our documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.12/install-elasticsearch.html) provides guidance for this.
