### ISSUE TITLE
Remove ability to specify default mapping on disk

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#10620]
Having to set special files on every node seems like an anti-pattern for one of the main goals for ES (everything available through an API).  We already have the ability to set the default mapping through the API, and the code handling disk based default mappings just adds complication without benefit.  We should remove this for 2.0.

**Comment by jpountz** [comment]
+1

**Comment by clintongormley** [comment]
I'm strongly in favour of this.  Using config files to set mappings is an anti-pattern, which just creates more maintenance and more room for error.
