### ISSUE TITLE
Elasticsearch inner_hits query does not return second nested field in object field

### ISSUE THREAD

**Issue by mariusdw** [elastic/elasticsearch#10629]
Hi All

Please refer to issue <a href="https://github.com/elastic/elasticsearch/issues/10334">10334</a> that was marked as fixed in the latest release (1.5.1). I have tested this today and it still doesnt work correctly. The ArrayOutOfBoundsException is gone, however I now get incorrect data back.  Only the first entry is returned regardless of which entry has matched the search request.

To Replicate: Setup the same template and data as in issue <a href="https://github.com/elastic/elasticsearch/issues/10334">10334</a>:

<pre><code>curl -XPOST 'http://localhost:9200/twitter'

curl -XPOST 'http://localhost:9200/twitter/_mapping/tweet' -d '
{
    "tweet": {
        "properties": {
            "comments": {
                "properties": {
                    "messages": {
                        "type": "nested",
                        "properties": {
                            "message": {
                                "type" : "string", 
                                "index": "not_analyzed"
                            }   
                        }
                    } 
                }
            }
        }
    }
}'

curl -XPOST 'http://localhost:9200/twitter/tweet' -d '
{
    "comments": {
        "messages": [
            {"message": "Nice website"},
            {"message": "Worst ever"}
        ]
    }
}'

</code></pre>

Now search for the message "Worst ever"

<pre><code>
curl -XGET 'http://localhost:9200/twitter/tweet/_search?pretty' -d '
{
    "query": {
        "nested": {
            "path": "comments.messages",
            "query": {
                "match": {"comments.messages.message": "Worst ever"}
            },
            "inner_hits" : {}
        }
    }
}'
</code></pre>

The following gets returned:

<pre><code>
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.4054651,
    "hits" : [ {
      "_index" : "twitter",
      "_type" : "tweet",
      "_id" : "AUzCMIjnYDWhRGHuJRhC",
      "_score" : 1.4054651,
      "_source":
{
    "comments": {
        "messages": [
            {"message": "Nice website"},
            {"message": "Worst ever"}
        ]
    }
},
      "inner_hits" : {
        "comments.messages" : {
          "hits" : {
            "total" : 1,
            "max_score" : 1.4054651,
            "hits" : [ {
              "_index" : "twitter",
              "_type" : "tweet",
              "_id" : "AUzCMIjnYDWhRGHuJRhC",
              "_nested" : {
                "field" : "comments",
                "offset" : 0,
                "_nested" : {
                  "field" : "messages",
                  "offset" : 0
                }
              },
              "_score" : 1.4054651,
              "_source":{"message":"Nice website"}
            } ]
          }
        }
      }
    } ]
  }
}
</code></pre>

This is clearly the incorrect inner hit. As discussed previously with martijnvg a workaround is if I change the object field in my mapping to be nested as well, like this:

<pre><code>
curl -XPOST 'http://localhost:9200/twitter/_mapping/tweet' -d '
{
    "tweet": {
        "properties": {
            "comments": {
                "type": "nested",
                "properties": {
                    "messages": {
                        "type": "nested",
                        "properties": {
                            "message": {
                                "type" : "string", 
                                "index": "not_analyzed"
                            }   
                        }
                    } 
                }
            }
        }
    }
}'
</code></pre>

however doing so results in a larger memory footprint which is undesirable. Also note the use case in #10334 in my second post on the issue that explains why I only need a normal object field containing nested fields.

**Comment by martijnvg** [comment]
@mariusdw agreed, that looks incorrect

**Comment by martijnvg** [comment]
Fixed via #10663. If a non nested object field the direct parent of a nested object field, its field is inlined with the nested identify of the child nested object. Since a normal object isn't nested using a dummy nested identity didn't make sense. (this was the fix for #10334)
