### ISSUE TITLE
Documents in `.watcher-history` index may be enormous

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#106389]
Seen in a heap dump from a node that went OOME: someone configured a watch thusly:

```json
{
  "input": {
    "search": {
      "request": {
        "search_type": "query_then_fetch",
        "indices": [
          "logstash-prod-all-*"
        ],
        "rest_total_hits_as_int": true,
        "body": {
          "size": 10000,
          "query": {
            "bool": {
              "filter": [
                {
                  "range": {
                    "@timestamp": {
                      "gt": "now-15m"
                    }
                  }
                }
              ]
            }
          }
        }
      }
    }
  },
  "condition": {
    "compare": {
      "ctx.payload.hits.total": {
        "lt": 100
      }
    }
  }
}
```

I mean clearly this is a daft way to detect this condition, but in any case Watcher dutifully records the entire search response, all 10k docs, well over 1GiB of data, in every entry in the `.watcher-history` data stream. I get why it might be useful to do this for debugging but in production it'd be better to avoid generating such large docs.

**Comment by dakrone** [comment]
I believe this is a duplicate of https://github.com/elastic/elasticsearch/issues/94745

**Comment by DaveCTurner** [comment]
Yep, thanks Lee, same thing indeed.
