### ISSUE TITLE
Don't allow fuzziness specified as a `minimum similarity` and require edits [0,2]

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#10638]
Lucene deprecated this in 4.0 and we only try best effort to support it. Folks should only use edit distance rather than some length based similarity. Yet the formular is simple enough such that users can still do it in the client if they really need to.

**Comment by rmuir** [comment]
+1

**Comment by s1monw** [comment]
@clintongormley are you ok with this

**Comment by s1monw** [comment]
ping @clintongormley

**Comment by clintongormley** [comment]
+1 remove min_similarity and percentages of fuzziness.  Fuzziness should accept 1, 2, or AUTO
