### ISSUE TITLE
Security Auto-Configuration: Transport CA is named "HTTP CA"

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#106455]
In security auto configuration we generate separate CAs for transport & HTTP
But they have the same name: `CN=Elasticsearch security auto-configuration HTTP CA`
- https://github.com/elastic/elasticsearch/blob/b7eafce32cb1e7dfdcb259aab89b886ff93a1c66/x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java#L117

The transport CA should be named `CN=Elasticsearch security auto-configuration transport CA` (or something like that)

**Comment by adityakukankar** [comment]
Hi @tvernum, I've opened a pull request for this issue. Could you please review it when you have some time? Thanks!

ps I am new to making contributions here.

**Comment by Rsujithkumar** [comment]
transport with different names, you can update the constants accordingly.
-Add a constant for the transport CA with a distinct name.
-Ensure that the transport CA uses the new constant.
