### ISSUE TITLE
[Supportability] Consider limiting template update to only `manage_index_templates` but not `manage` (likely to be breaking change)

### ISSUE THREAD

**Issue by kunisen** [elastic/elasticsearch#106452]
### Description

From a supportability perspective, we would like to ask ES team to consider limiting template update to only `manage_index_templates` but not `manage` (likely to be breaking change).

Reason behind this is, cluster `manage` privilege is too wide, it can touch index templates (which is more index oriented) and snapshot, license, etc. 
From a supportability perspective, as an administrator or maintainer of Elasticsearch, 
- They may have to tweak the cluster settings like recovery speed or avoiding hot spot (index total shard per node) 
- But they don't need to change index settings and mappings

When thinking in that aspect, it feels like we should make this privilege more granular. 

I also understand this might be considered as a breaking change, because it will change the way of current privilege assignment. 
FWIW, maybe not a very logically reasonable idea, some drive-by thoughts:
- It seems we do separate privileges for snapshot taking. In manual, it says [`monitor, manage_slm, cluster:admin/snapshot, and cluster:admin/repository`](https://www.elastic.co/guide/en/elasticsearch/reference/8.12/snapshots-restore-snapshot.html). But it seems like we also allow to [create snapshot independently with `manage` cluster privilege](https://www.elastic.co/guide/en/elasticsearch/reference/current/create-snapshot-api.html) (not thru SLM).
- Which made me think, maybe we can first add a deprecation note in manual, and then remove that from manual first, and later remove that totally.

Please let us know if having a `manage` to do all kinds of work is actually intentional and we don't want to separate. That's also fine if we have a good reason for this. 
Thanks!

---

cc @TomonoriSoejima

**Comment by bytebilly** [comment]
@kunisen my understanding is that `manage` is a superset of all `manage_*` privileges, with the very only exception of `manage_security`.

Are you asking to also exclude `manage_index_template` from `manage`?
If the problem is that `manage` is too broad and some user needs only a subset of it, does it make more sense to create other missing `manage_*` instead, so that users can create a more limited role?

Changing `manage` would be a very strong breaking change, and it would be counterintuitive. This may also open up additional "exception requests" that is an undesirable outcome.

**Comment by kunisen** [comment]
Thanks @bytebilly for your response!

Maybe I didn't explain the motivation clearly enough, so please allow me to add more context: 

From a high level, it seems using `manage` can control:
- update template (mentioned in this ticket)
- reroute (cf: https://github.com/elastic/elasticsearch/issues/106450),
- take snapshot (cf: https://www.elastic.co/guide/en/elasticsearch/reference/current/create-snapshot-api.html),
- change cluster setting about recovery speed (for old versions),
- change cluster setting to avoid hot spot (index total shard per node)
- etc...

From a support perspective, we probably only want to avoid updating template because that can be destructive (while others can also be of risk without experience, but this update template is something apparently different - it contains mapping and setting which are normally not need to update frequently). 

So as you can see, if we want to exclude `manage_index_template` from `manage`, but keep other permissions, we need to ask for other individual permissions respectively, which is also not a trivial task. But I fully understand your point, if it's a very strong breaking change, then we probably need to go with having each fine-grained privilege separately way. 

Happy to discuss internally too if needed.

**Comment by kunisen** [comment]
Close it out as tweaking `manage` privilege is too breaking change to go and can't be expected to have a great value to go. 
Alternatively, we will raise separate and individual request to add more fine-grained privilege instead. 
Thanks!
