### ISSUE TITLE
Support `ignore_dynamic_beyond_limit` for all fields using synthetic source

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#106487]
### Description

When index requests exceed the `ignore_dynamic_beyond_limit` setting new fields are not dynamically mapped and new fields will be ignored. As a result, when reconstructing the original object, we are not able to reconstruct the field from doc values as no doc value fields are written for fields that are ignored. Here we need to apply a similar approach to what we do when supporting `ignore_malformed` and `ingore_above`, storing the field value "as-is" in a hidden stored field.

Notice that this is a bit kore complicated then the other two cases because in this case the field is not mapped.

**Comment by kkrik-es** [comment]
I think #107567 fixed this.
