### ISSUE TITLE
Update `Aggregator` and `GroupingAggregator` interfaces to accept sorted pages/blocks.

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#106414]
Time series function like rate additionally need access to timestamp field. However the current `Aggregator` and `GroupingAggregator` interfaces only allow access to the blocks of the field an aggregate should be computed for. 

This issue is about changing the interface so that when needed time series function can access value for additional  fields (like `@timestamp`).

This task is only required if the rate function code is going to be auto generated.

Relates to #105397

**Comment by dnhatn** [comment]
Fixed in #106703
