### ISSUE TITLE
Support `ignore_malformed` for all non-string fields using synthetic source

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#106483]
### Description

Non-string fields need to support `ignore_malformed` when synthetic source is enabled. The idea is to store the field value "as-is" in its json representation and later use the the value reading it from a hidden stored field.

Here the strategy to adopt is [similar to what we did for the `ip` type](https://github.com/elastic/elasticsearch/pull/90038). We catch an exception happing when parsing the field value and if storing the malformed value is enabled we just use `IgnoreMalformedStoredValues#storedField` to store the value.

(Maybe we can do a nice refactoring before and avoid relying on catching the exception)

**Comment by lkts** [comment]
Fields that need support:

- [ ] aggregate_metric_double #108746
- [ ] scaled_float
- [ ] date, date_nanos
- [ ] geo_point
