### ISSUE TITLE
post_filter breaking changes

### ISSUE THREAD

**Issue by gge-etudes** [elastic/elasticsearch#10647]
While upgrading from version 1.1.1 to 1.5.1 the post_filter fails with :
nested: ElasticsearchParseException[Expected field name but got END_ARRAY \"post_filter\"];

--FAILS
  "post_filter": [
    {
      "script": {
        "script": "(!doc.containsKey('DebutVisibilite') || doc['DebutVisibilite'].empty || doc['DebutVisibilite'].value <= today) && (!doc.containsKey('FinVisibilite') || doc['FinVisibilite'].empty || doc['FinVisibilite'].value >= today) && (!doc.containsKey('FinValidite') || doc['FinValidite'].empty || doc['FinValidite'].value >= date)",
        "params": {
          "today": 1429228800000,
          "date": 1429228800000
        }
      }
    }
  ]

--SUCCEEDS
  "post_filter":
    {
      "script": {
        "script": "(!doc.containsKey('DebutVisibilite') || doc['DebutVisibilite'].empty || doc['DebutVisibilite'].value <= today) && (!doc.containsKey('FinVisibilite') || doc['FinVisibilite'].empty || doc['FinVisibilite'].value >= today) && (!doc.containsKey('FinValidite') || doc['FinValidite'].empty || doc['FinValidite'].value >= date)",
        "params": {
          "today": 1429228800000,
          "date": 1429228800000
        }
      }
    }

So how can i apply multiple post filter conditions, ex : 1 script + 1 term etc... ?

**Comment by dadoonet** [comment]
I guess you could use a `bool filter` with many `must` clauses to wrap all your filters? Would this work for you?

I don't think it's an issue here but more a question.
You should prefer the mailing list for that kind of question.

Closing but feel free to reopen if you think it's a bug.

**Comment by gge-etudes** [comment]
Hi, thanks for your reply.

Well i think it's an issue because it used to work in previous releases.
Anyhow, i had to apply those filters outside of the query because of caching and faceting issues.

Right now it's ok as i only have one post_filter clause in this particular project.
But still, i'd like to know what are the guidelines to achieve the exact same result as before.

I tried to use a bool filter inside a post_filter without success, but it may be a matter of syntax.

**Comment by dadoonet** [comment]
I just tried this on 1.1.1:

```
DELETE index
PUT index/type/1
{
  "foo": "bar"
}

GET index/type/_search
{
  "post_filter": [
    "term": {
      "foo": "bar"
    }
  ]
}
```

It fails as expected:

```
{
   "error": "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[nKIQFEpFTQu0s_qXbmoNtg][index][1]: SearchParseException[[index][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\n  \"post_filter\": [\n    \"term\": {\n      \"foo\": \"bar\"\n    }\n  ]\n}\n]]]; nested: QueryParsingException[[index] [_na] filter malformed, must start with start_object]; }{[nKIQFEpFTQu0s_qXbmoNtg][index][0]: SearchParseException[[index][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\n  \"post_filter\": [\n    \"term\": {\n      \"foo\": \"bar\"\n    }\n  ]\n}\n]]]; nested: QueryParsingException[[index] [_na] filter malformed, must start with start_object]; }{[nKIQFEpFTQu0s_qXbmoNtg][index][4]: SearchParseException[[index][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\n  \"post_filter\": [\n    \"term\": {\n      \"foo\": \"bar\"\n    }\n  ]\n}\n]]]; nested: QueryParsingException[[index] [_na] filter malformed, must start with start_object]; }{[nKIQFEpFTQu0s_qXbmoNtg][index][2]: SearchParseException[[index][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\n  \"post_filter\": [\n    \"term\": {\n      \"foo\": \"bar\"\n    }\n  ]\n}\n]]]; nested: QueryParsingException[[index] [_na] filter malformed, must start with start_object]; }{[nKIQFEpFTQu0s_qXbmoNtg][index][3]: SearchParseException[[index][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\n  \"post_filter\": [\n    \"term\": {\n      \"foo\": \"bar\"\n    }\n  ]\n}\n]]]; nested: QueryParsingException[[index] [_na] filter malformed, must start with start_object]; }]",
   "status": 400
}
```

Note that the oldest doc don't mention you can use an array of filters: http://www.elastic.co/guide/en/elasticsearch/reference/0.90/search-request-post-filter.html

So you might hit something else here.
Could you check on your end and create a full SENSE script as I wrote which runs in 1.1.1 and breaks in 1.5.1?

**Comment by gge-etudes** [comment]
OK, so your sample works if you add curly braces around the term filter :
POST index/type/_search
{
   "post_filter":[
      {
         "term":{
            "foo":"bar"
         }
      }
   ]
}

But only with a sole filter, so this query fails :
POST index/type/_search
{
   "post_filter":[
      {
         "term":{
            "foo":"bar"
         }
      },
      {
         "term":{
            "foo":"bar"
         }
      }
   ]
}

Whereas the bool filter approach works like a charm :
POST index/type/_search
{
   "post_filter":{
      "bool":{
         "must":[
            {
               "term":{
                  "foo":"bar"
               }
            },
            {
               "term":{
                  "foo":"bar"
               }
            }
         ]
      }
   }
}

Strange thing... you can express a post filter as an array made of a single item.
So I was assuming it could be an array populated by multiple items... but no.
The bool filter way is fine to me.

Thank you very much.
