### ISSUE TITLE
With min_doc_count: 0, terms agg now creating null bucket (new in 1.5.1?)

### ISSUE THREAD

**Issue by tylerprete** [elastic/elasticsearch#10640]
Running this query on my data:
```
GET beta/place/_search?search_type=count
{
 "query": {
   "match_all": {}
 },
 "aggs": {
   "ratings": {
     "terms": {
       "field": "price",
       "size": 100,
       "min_doc_count": 0
     }
   }
 }
} 
```

I'm getting this back:
```
   "aggregations": {
      "ratings": {
         "doc_count_error_upper_bound": 0,
         "sum_other_doc_count": 0,
         "buckets": [
            {
               "key": "2",
               "doc_count": 612985
            },
            {
               "key": "1",
               "doc_count": 542859
            },
            {
               "key": "3",
               "doc_count": 125294
            },
            {
               "key": "4",
               "doc_count": 57340
            },
            {
               "key": "null",
               "doc_count": 0
            }
         ]
      }
   }
```

At the very least, I can say I'm not getting null buckets in version 1.3.9. I don't have any 1.4 servers up right now to check.

Also, it only happens for min_doc_count=0. If I remove that, it goes away.

Is this desired behavior?

I found this existing issue: https://github.com/elastic/elasticsearch/issues/6273
but that seems to asking for a null bucket, and it's still open.

**Comment by jpountz** [comment]
This can happen if you have a deleted document which is only marked as deleted for now and has "null" as a value for "price". See first note under http://www.elastic.co/guide/en/elasticsearch//reference/1.5/search-aggregations-bucket-terms-aggregation.html#_minimum_document_count

**Comment by tylerprete** [comment]
Just FYI, this index doesn't have any deleted documents. We never issue deletes with our workflow. And I only started seeing it in ES 1.5+. But it's fine, I can workaround it.

**Comment by jpountz** [comment]
@tylerprete Then maybe you have other types on the same index and `null` is a possible value on those types for the `price` field?
