### ISSUE TITLE
Inefficiency with PerFieldDocValuesFormat and ES87TSDBDocValuesProducer

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#106468]
`SegmentReader` instances in tsdb indices with a sufficient number of fields do take some space (1000+ fields, could use 800kb of jvm heap). This is small, but many segment readers may exist for these tsdb indices and could use a non-trivial amount of jvm heap (e.g. 200mb). Looking closer it looks like often the `docValuesProducer` uses up to 50% of the memory being used by a `SegmentReader` (much more than `fieldInfos` field). There are two large maps in these cases in `org.apache.lucene.codecs.perfield.PerFieldDocValuesFormat$FieldsReader` and `org.elasticsearch.index.codec.tsdb.ES87TSDBDocValuesProducer` (for `sortedNumerics` field). 

It seems wasteful that the same fields are being mentioned in both of these maps. Maybe we can use a single map instead to keep track of the right doc values producer for a field?

**Comment by jpountz** [comment]
I wonder if there's some quick wins there. For instance I see TreeMaps there, which probably date from the time when these classes implemented `Accountable` and we wanted to have a nice order in the RAM usage tree. We don't seem to rely on the order nowadays and could switch to more RAM-effecient HashMaps?

**Comment by martijnvg** [comment]
If I recall correctly the large treemap was in `PerFieldDocValuesFormat.FieldsReader`. Do you think we can change `fields` in that class from `TreeMap` to `HashMap` without breaking bwc?

**Comment by jpountz** [comment]
I think so, I was looking at that code for other reasons so I opened apache/lucene#13284. In general I'm wary of optimizing for the RAM usage in case of many fields, which can quickly become a rabbit hole. However this one change looks rather straightforward.

**Comment by martijnvg** [comment]
This change was include with the Lucene 9.11.0 release, which will be included in Elasticsearch 8.15.0.
I think the mentioned Lucene PR reduces the mentioned inefficiency sufficiently and no follow up is required.
