### ISSUE TITLE
Support `ignore_above` for all string fields using synthetic source

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#106485]
### Description

String fields need to support `ignore_above` when synthetic source is enabled. The idea is to store the field value "as-is" in its json representation and later use the the value reading it from a hidden stored field.

**Comment by lkts** [comment]
Fields supporting `ignore_above`:
* `keyword` - supports synthetic source for ignored values already
* `icu_collation_keyword` - uses fallback synthetic source and therefore automatically includes ignored values in synthetic source
* `wildcard` - supports synthetic source for ignored values already
* `flattened` - not supported
