### ISSUE TITLE
ESQL: MV_MEDIAN should always return double and not round

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#106479]
`MV_MEDIAN` returns the same type as its input, while `MV_AVG` always returns `double`. This also makes `MV_MEDIAN` inconsistent with `MEDIAN`, which always returns `double` (similarly to `AVG`).

Additionally, `MV_MEDIAN` rounds down to the nearest integer, which `MEDIAN` does not.

We should make `MV_MEDIAN` consistent by having it always return `double` and not round down, so that `MV_MEDIAN([1,2]) == 1.5`.

**Comment by alex-spies** [comment]
This also partially blocks https://github.com/elastic/elasticsearch/issues/100634 as we cannot just replace `MEDIAN(const)` by `MV_MEDIAN(const)`.

**Comment by nik9000** [comment]
My reasoning for `MV_MEDIAN` returning the input type as that it always generates something that can fit in the original type. Except for the silly rounding.  I'm not sure that that reasoning is valid, but it's much more reasonable than trying to make the `MEDIAN` agg return the same type as the input.

**Comment by alex-spies** [comment]
I think this is not relevant anymore.
- For doubles, `MV_MEDIAN` has the expected behavior, which is consistent with the `MEDIAN` aggregation; in particular, it doesn't round and doesn't return an element from the provided multivalue.
- As @nik9000 mentioned, `MV_MEDIAN` returning an actual element from the provided multivalue (for types other than double) can be useful.

To always get a behavior consistent with `MEDIAN` (aggregation), one can just use `MV_MEDIAN(TO_DOUBLE(x))`; this was also used to [implement `MEDIAN(const)`](https://github.com/elastic/elasticsearch/blob/13afe0fda9c50a0adc5d17b2f1a994168ce6baf3/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/aggregate/Median.java#L70), which invalidates my comment from above.
