### ISSUE TITLE
Shield - Circular Dependency - start failed

### ISSUE THREAD

**Issue by damienlust** [elastic/elasticsearch#10658]
Based on the latest version of shield and ES,
These other plugins are used :
   loaded [WebPlugin, license, shield, mapper-attachments, QuartzPlugin], sites [HQ]

But the start of ES fails:

[2015-04-17 16:47:10,470][INFO ][http                     ] [Node1] Using [org.elasticsearch.shield.transport.netty.ShieldNettyHttpServerTransport] as http transport, overridden by [shield]
{1.5.1}: Initialization Failed ...
1) IllegalStateException[This is a proxy used to support circular references involving constructors. The object we're proxying is not constructed yet. Please wait until after injection has completed to use this object.]2) Tried proxying org.elasticsearch.transport.TransportService to support a circular dependency, but it is not an interface.

**Comment by clintongormley** [comment]
Hi @damienlust 

I'm guessing the clash is with the WebPlugin?  Given that (a) we have no control over that plugin and (b) rivers are deprecated, I don't think there is much we can do to fix this.

**Comment by damienlust** [comment]
Thanks for the feedback,
What's the alternative to crawl a website?
The river webplugin seems the most popular?
Thanks

**Comment by clintongormley** [comment]
@damienlust I'm not sure. I had a look for a suitable logstash plugin, but can't find one. Really, you can use any web scraping framework, because it runs outside Elasticsearch.

**Comment by dadoonet** [comment]
I heard about some efforts around nutch 2.
And some plugins like https://github.com/duffj/nutch-elasticsearch

Never tested it though.
