### ISSUE TITLE
terms aggregation ERROR : parse failure on include array of values

### ISSUE THREAD

**Issue by rrphotosoft** [elastic/elasticsearch#10655]
Hi,
I'm using a terms aggregation and would like to use the include feature to only include certain terms on which buckets should be created.
Unfortunately I am not able to find the right syntax.
The documentation mentions the following:

"It is possible to filter the values for which buckets will be created. This can be done using the include and exclude parameters which are based on regular expression strings or arrays of exact values."

How do you pass an array of exact values?
Here is my example:
{
   "query" :{..},
   "aggregations":{
         "sector_ids":{
             "terms":{
                 "field":"sector_id"
             },
             "aggs":{
                 "unique_keywords":{
                     "terms":{
                         "field":"keywords.analyzed_name",
                         "include": ["xeon","argon"]
                     }
                 }
             }
         }
     }
}

This throws an error:

"Parse Failure [Unknown key for a START_ARRAY in [unique_keywords]: [include].]];"

I am using ES 1.3.5, however I don't think it has anything to do with my version.

Any help is appreciated, until then I will have my program generate a pattern of all the keywords that I wish to include, but that becomes a  really lousy piece of monkey patching.

Regards,
RR.

**Comment by jpountz** [comment]
> I am using ES 1.3.5, however I don't think it has anything to do with my version.

If I'm  not mistaken this was added in 1.5.0 (previously only regexps were supported) viq https://github.com/elastic/elasticsearch/pull/7529. Assigning this to myself, I'll fix the documentation to make it clearer.

**Comment by jpountz** [comment]
I pushed a commit to the docs, this should reflect on the website soon.

**Comment by rrphotosoft** [comment]
Thanks for the clarification!
