### ISSUE TITLE
Nested documents:  include_in_parent does not seem to work with geo_shape objects

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#10653]
To repro:

```
PUT ltest

PUT ltest/_mapping/test
{
  "test":{
    "properties":{
      "rootField1" : { "type" : "string" },
      "nestedDoc" : { 
        "type" : "nested", 
        "include_in_parent" : true, 
        "dynamic" : false, 
        "path" : "full", 
        "properties" : { 
          "innerField1" : { "type" : "string" }, 
          "innerField2" : { "type" : "geo_shape" }, 
          "innerField3" : { "type" : "geo_point" }, 
          "innerField4" : { "type" : "boolean" } 
        } 
      } 
    } 
  }
}

PUT ltest/test/1
{
  "rootField1":"testname",
  "nestedDoc":{
    "innerField1":"innerstring",
  "innerField2":{
    "type" : "point",
    "coordinates" : [-77.5, 38.5]
  },
  "innerField3":{
      "lat":"41.12",
      "lon":"-71.34"
  },
  "innerField4":true
}
}

GET ltest/_search
{
  "query":{
    "match_all":{}
  },
  "filter":{
    "nested":{
      "path":"nestedDoc",
      "filter":{
    "geo_shape":{
      "nestedDoc.innerField2":{
         "shape":{
        "type":"envelope",
        "coordinates":[[-78,38],[-77,39]]
      }
    }
  }
}
}
}
}

GET ltest/_search
{
  "query":{
    "match_all":{}
  },
  "filter":{
    "geo_shape":{
      "nestedDoc.innerField2":{
         "shape":{
        "type":"envelope",
        "coordinates":[[-78,38],[-77,39]]
      }
    }
  }
}
}
```

The first search works correctly using a nested filter.  The second does not return a result, even though the object should be available at the parent level.  Term filters using the 'innerfield1' string type work as expected, even without the nested filter.

**Comment by rjernst** [comment]
The problem here is how geo shapes interact with lucene, mixed with the implementation of `include_in_parent` (note that this would also fail for `include_in_root`). Geo shapes values are generated while indexing using a stream of binary tokens. Due to the fact that these could be extremely memory intensive, this stream is not resettable.  So what happens here is the child doc exhausts the stream while indexing, then the parent tries to use the same stream, but it just gets an empty iteration.

**Comment by clintongormley** [comment]
Thanks for the explanation @rjernst - given how expensive this is, i'd say that we shouldn't change this behaviour.  In fact, the `include_in_*` options were mostly a workaround for the early days of nested objects, when the query/agg framework was not as evolved.

Probably all we need is a doc update.
