### ISSUE TITLE
ESQL CSVTests failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#106501]
Pretty much every test in this suite fails from time to time.

### CI Link

https://gradle-enterprise.elastic.co/s/ojn7nl2reehnu/tests/task/:x-pack:plugin:esql:test/details/org.elasticsearch.xpack.esql.CsvTests/test%20%7Bgrok.TypeConversions%7D?top-execution=1

### Repro line

```./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.CsvTests" -Dtests.method="test {grok.TypeConversions}" -Dtests.seed=673DAFB9C9F716F9 -Dtests.locale=ms-MY -Dtests.timezone=America/Toronto -Druntime.java=21```

### Does it reproduce?

No

### Applicable branches

main

### Failure history

https://es-delivery-stats.elastic.dev/app/r/s/ph4sk

### Failure excerpt

```java.lang.IllegalArgumentException: Unrecognized class type class [Lorg.apache.lucene.util.BytesRef;```

**Comment by mark-vieira** [comment]
Muted in `main`.

**Comment by nik9000** [comment]
> Muted in `main`.

Well that's a huge portion of ESQL's tests. I'll see if I can track this down.

**Comment by nik9000** [comment]
Reproduces every few runs.

**Comment by nik9000** [comment]
Seed doesn't do anything. fun.

**Comment by nik9000** [comment]
Oh my! The problem is on tests that use `ROW` we just pick a random dataset. We just pick the first one that comes back when you iterate the values. From a `Map`. The iteration order is random. And some of them can't be used with the thing we return. Will push a fix.
