### ISSUE TITLE
[CI] ThreadPoolTests testScheduledFixedDelayRejection failing

### ISSUE THREAD

**Issue by gmarouli** [elastic/elasticsearch#106618]
This test was introduced in https://github.com/elastic/elasticsearch/pull/106542

**Build scan:**
https://gradle-enterprise.elastic.co/s/vhbjdbibh2se2/tests/:server:test/org.elasticsearch.threadpool.ThreadPoolTests/testScheduledFixedDelayRejection

**Reproduction line:**
```
./gradlew ':server:test' --tests "org.elasticsearch.threadpool.ThreadPoolTests.testScheduledFixedDelayRejection" -Dtests.seed=CA7F3E4D95D9A00F -Dtests.locale=bg-BG -Dtests.timezone=Asia/Anadyr -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.threadpool.ThreadPoolTests#testScheduledFixedDelayRejection`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testScheduledFixedDelayRejection'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.threadpool.ThreadPoolTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: safeAwait: CountDownLatch did not reach zero within the timeout

  at __randomizedtesting.SeedInfo.seed([CA7F3E4D95D9A00F]:0)
  at org.junit.Assert.fail(Assert.java:89)
  at org.junit.Assert.assertTrue(Assert.java:42)
  at org.elasticsearch.test.ESTestCase.safeAwait(ESTestCase.java:2097)
  at org.elasticsearch.threadpool.ThreadPoolTests.lambda$blockExecution$12(ThreadPoolTests.java:555)
  at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1570)

```

**Comment by albertzaharovits** [comment]
Started failing [recently](https://es-delivery-stats.elastic.dev/app/r?l=DISCOVER_APP_LOCATOR&v=8.14.0&lz=N4IgjgrgpgTgniAXKSsGJAYwDYEMDO%2BAcrgLZQAEiFA9jAOYB0Ue%2BALgJab5S4yYALRmwExeAEwAONGtkYAVURIAKM7PKjt8FAIJEAIhQB2ZKNTaa2AZUFRxEbHYBiHAB539LXHABKUAFZQmJw0RiAANCB4RvQQuPRQSCAA1tDwIAC%2Bkfh0bEgA2vkgAAKc5OxkkhEg4pqYIAC6DZGYshCkRvgFzSAcRrWuSQBmAEYj4pgAbAAcAJwAtCNQAEwAzPMALCOr4vPTAAwArADs87i4G%2FvLULN2%2B5iH1X0WMABuuNhJuBBsNNVDHGwLy6iHyPXEuDYuAAahwoAB3ACS4mGYwmMwWSzWm22uwOJzOFyuNzuD2qZSgPlwMUSyBAQxgNFISWWVw28326wAjKt5Mtloh9vtBftGEL9gAtcl%2FDBGGjwzKRMQMzQCRFGF7vT50rXQJCTcX7SKSb48JBsGDQDIZIA%3D%3D).
Thank you for muting @DaveCTurner !

**Comment by DaveCTurner** [comment]
:+1: looks flaky since it was introduced yesterday; muted on `main`, `8.13` and `7.17`.

**Comment by DaveCTurner** [comment]
Ok yeah this test doesn't quite work. The problem is that we need the scheduled task to be rejected, but because it's racing with the blocking tasks it might end up in the queue and therefore it never runs.

**Comment by DaveCTurner** [comment]
Just a test bug --> low-risk
