### ISSUE TITLE
TopHits advance()'s backwards

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#10661]
I saw this by adding assertingcodec to the mix in our tests:

FAILURE 0.55s | TopHitsTests.testNestedFetchFeatures <<<
   > Throwable #1: java.lang.AssertionError: Hit count is 1 but 2 was expected.  Total shards: 9 Successful shards: 8 & 1 shard failures:
   >  shard [[qcEkX24CTsSgeHjwon4SYA][articles][5]], reason [ElasticsearchException[target must be > docID(), got 1 <= 3]; nested: AssertionError[target must be > docID(), got 1 <= 3]; ]
   > 	at __randomizedtesting.SeedInfo.seed([EEBE1D571C1FD8E9:9F4B07A5A1F77FA4]:0)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:145)
   > 	at org.elasticsearch.search.aggregations.bucket.TopHitsTests.testNestedFetchFeatures(TopHitsTests.java:804)
   > 	at java.lang.Thread.run(Thread.java:745)

**Comment by rmuir** [comment]
I also hit this with SimpleNestedTests.simpleNestedMatchQueries() with AssertingCodec

**Comment by martijnvg** [comment]
The failure in the TopHits are caused by the nested aggregator. The TopHitsAggregator doesn't invoke advance by itself. (the combination is being tested here)

**Comment by s1monw** [comment]
@martijnvg  can you fix this?

**Comment by martijnvg** [comment]
@s1monw sure, I'll fix this.

**Comment by jpountz** [comment]
@martijnvg SimpleNestedTests still has an `AwaitsFix` with this bug url, should it be removed?

**Comment by martijnvg** [comment]
@jpountz yes, it should! I guess I forgot that. the test needs to be changed a bit too... the matched queries should be asserted on the inner hits instead of the root hit.
