### ISSUE TITLE
Scan and scroll query not working when combined with range query

### ISSUE THREAD

**Issue by SrikanthKS** [elastic/elasticsearch#10665]
Hi,

I am trying to use Java API for executing scan and scroll query while combining it with range query but I am not getting any hits. I am not sure if it's a problem with my query or my data but below is my code:

    String from = "1429192800000";
    String to = "1429193100000";
		
    QueryBuilder qb = rangeQuery("myField")
				 .gte(from)                          
			         .lte(to);
		
    SearchRequestBuilder searchBuilder = client.prepareSearch(oldIndex)
				.setTypes("myType")
		        .setSearchType(SearchType.SCAN)
		        .setScroll(new TimeValue(Integer.parseInt(scrollOpenTime)*60000))
		        .setQuery(qb)
		        .setSize(Integer.parseInt(size));

And here's my output:

    {
      "_scroll_id" : my64BitScrolliD,
      "took" : 576,
      "timed_out" : false,
      "_shards" : {
        "total" : 15,
        "successful" : 15,
        "failed" : 0
      },
      "hits" : {
        "total" : 0,
        "max_score" : 0.0,
        "hits" : [ ]
      }
    }

I have tried querying without using java api and still it doesn't return any hits. Here's my query:

    curl -XGET "http://localhost:9220/path/to/cluster/myIndex/myType/_search?search_type=scan&scroll=1m -d '{
     "size": 100,
        "query": {
            "range": {
                "reqDT": {
                    "from": "1429192800000",
                    "to": "1429193100000"
                }
            }
      }
    }'

And I get the same output as above. The field for which I have applied the range query holds an epoch timestamp and data exists between the specified range so there is no mistake with the query I suppose (I have tested it with just _search API and without using scan and scroll and it worked!). Could anyone point me in the right direction? Also please let me know if any more information is required.

Thank you!

EDIT 1: Corrected -XPOST to -XGET

EDIT 2: I would like to add that the scan and scroll query works fine if I don't combine range query with it! Since there is a really large amount of data, I want to get the results in batches by specifying the time range.

**Comment by dadoonet** [comment]
I think it's not an issue but a usage question. Mailing list is a better place for that.

That said, could you provide a sample script which reproduces your problem?
Have a look at https://www.elastic.co/help.

**Comment by clintongormley** [comment]
@SrikanthKS just to confirm: ranges work with scan/scroll as can be demonstrated here:

    PUT my_index
    {
      "mappings": {
        "my_type": {
          "properties": {
            "reqDt": {
              "type": "date"
            }
          }
        }
      }
    }
    
    PUT my_index/my_type/1
    {
      "reqDt":  1429192800000
    }
    
    GET my_index/my_type/_search?search_type=scan&scroll=1m
    {
      "size": 100,
      "query": {
        "range": {
          "reqDt": {
            "from": 1429192800000,
            "to": 1429193100000
          }
        }
      }
    }

**Comment by henushang** [comment]
hi, I get the same question, and what's you solution?
