### ISSUE TITLE
Random sampler aggregation results depend on segment count

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#106657]
### Elasticsearch Version

`main`

### Java Version

_bundled_

### OS Version

OS-independent issue

### Problem Description

We'd like the random sampler aggregation to produce consistent results regardless of the number of segments in an index. However, the returned document count per bucket depends on the number of segments. 

### Steps to Reproduce

The following test case reproduces the issue. We explicitly flush after each document to provoke the issue. If we do a force merge at the end, the random sampler aggregation behaves as expected. Note that the test also eliminates all randomness by using the recently introduced shard seed.

```java
@ESIntegTestCase.ClusterScope(scope = ESIntegTestCase.Scope.TEST, numDataNodes = 1)
public class RandomSamplerAggregationIT extends ESIntegTestCase {

    public static final String TEST_INDEX = "test-001";

    @Override
    protected Collection<Class<? extends Plugin>> nodePlugins() {
        return List.of(getTestTransportPlugin());
    }

    @Override
    protected boolean addMockHttpTransport() {
        return false; // enable http
    }

    @Before
    public void setupData() throws Exception {
        prepareCreate(TEST_INDEX, indexSettings(1, 0)).setMapping(
            "@timestamp",
            "type=date",
            "transaction.name",
            "type=keyword",
            "transaction.stacktrace",
            "type=keyword"
        ).get();

        ensureGreen(TEST_INDEX);

        index(
            TEST_INDEX,
            "1",
            "{\"@timestamp\": \"1698624000\", \"transaction.name\":  \"encodeSha1\", \"transaction.stacktrace\": [\"aaaaaa\"]}"
        );
        flush(TEST_INDEX);
        index(
            TEST_INDEX,
            "2",
            "{\"@timestamp\": \"1698624001\", \"transaction.name\":  \"encodeSha1\", \"transaction.stacktrace\": [\"aaaaaa\"]}"
        );
        flush(TEST_INDEX);
        index(
            TEST_INDEX,
            "3",
            "{\"@timestamp\": \"1698624002\", \"transaction.name\":  \"encodeSha1\", \"transaction.stacktrace\": [\"aaaaaa\"]}"
        );
        flush(TEST_INDEX);
        index(
            TEST_INDEX,
            "4",
            "{\"@timestamp\": \"1698624003\", \"transaction.name\":  \"encodeSha1\", \"transaction.stacktrace\": [\"aaaaaa\"]}"
        );
        flush(TEST_INDEX);
        refresh();
        // uncomment this - it produces the expected result
        // forceMerge();
    }

    @TestLogging(
        value = "org.elasticsearch.search.aggregations.bucket.sampler.random.RandomSamplingQuery:TRACE,org.elasticsearch.search:TRACE",
        reason = "debugging"
    )
    public void testRandomSampler() {
        int seed = 947097719;
        TermQueryBuilder query = QueryBuilders.termQuery("transaction.name", "encodeSha1");
        RandomSamplerAggregationBuilder randomSampler = new RandomSamplerAggregationBuilder("sample").setSeed(seed)
            .setProbability(0.2d)
            .subAggregation(new TermsAggregationBuilder("group_by").field("transaction.stacktrace"));
        randomSampler.setShardSeed(42);

        assertResponse(
            prepareSearch(TEST_INDEX).setTrackTotalHits(false)
                .setSize(0)
                // take advantage of request cache and keep a consistent order for the same request
                .setRequestCache(true)
                .setPreference(String.valueOf(seed))
                .setQuery(query)
                .addAggregation(new MinAggregationBuilder("min_time").field("@timestamp"))
                .addAggregation(new MaxAggregationBuilder("max_time").field("@timestamp"))
                .addAggregation(randomSampler),
            response -> {
                SingleBucketAggregation sample = response.getAggregations().get("sample");
                Terms stacktraces = sample.getAggregations().get("group_by");
                // as the sampling rate is 0.2, we see 5 times more samples (random sampler agg automatically adjusts sample count)
                assertEquals(5L, stacktraces.getBucketByKey("aaaaaa").getDocCount());
            }
        );
    }
}
```

If we add a couple of trace statements:

```patch
diff --git a/server/src/main/java/org/elasticsearch/search/aggregations/bucket/sampler/random/RandomSamplingQuery.java b/server/src/main/java/org/elasticsearch/search/aggregations/bucket/sampler/random/RandomSamplingQuery.java
index 1878f15824b..a2cd6480e4c 100644
--- a/server/src/main/java/org/elasticsearch/search/aggregations/bucket/sampler/random/RandomSamplingQuery.java
+++ b/server/src/main/java/org/elasticsearch/search/aggregations/bucket/sampler/random/RandomSamplingQuery.java
@@ -8,6 +8,8 @@
 
 package org.elasticsearch.search.aggregations.bucket.sampler.random;
 
+import org.apache.logging.log4j.LogManager;
+import org.apache.logging.log4j.Logger;
 import org.apache.lucene.index.LeafReaderContext;
 import org.apache.lucene.search.ConstantScoreScorer;
 import org.apache.lucene.search.DocIdSetIterator;
@@ -29,6 +31,7 @@ import java.util.function.IntSupplier;
  * A query that randomly matches documents with a user-provided probability within a geometric distribution
  */
 public final class RandomSamplingQuery extends Query {
+    private static final Logger logger = LogManager.getLogger(RandomSamplingQuery.class);
 
     private final double p;
     private final int seed;
@@ -41,6 +44,7 @@ public final class RandomSamplingQuery extends Query {
      *                  can be generated
      */
     public RandomSamplingQuery(double p, int seed, int hash) {
+        logger.trace("Create RandomSamplingQuery with p=[{}], seed=[{}], hash=[{}]", p, hash, seed);
         if (p <= 0.0 || p >= 1.0) {
             throw new IllegalArgumentException("RandomSampling probability must be between 0.0 and 1.0, was [" + p + "]");
         }
@@ -56,6 +60,7 @@ public final class RandomSamplingQuery extends Query {
 
     @Override
     public Weight createWeight(IndexSearcher searcher, ScoreMode scoreMode, float boost) throws IOException {
+        logger.trace("createWeight(searcher=[" + searcher + "], scoreMode=[" + scoreMode + "], boost=[" + boost + "])");
         return new Weight(this) {
             @Override
             public boolean isCacheable(LeafReaderContext ctx) {
@@ -75,7 +80,9 @@ public final class RandomSamplingQuery extends Query {
 
             @Override
             public Scorer scorer(LeafReaderContext context) {
-                final SplittableRandom random = new SplittableRandom(BitMixer.mix(hash ^ seed));
+                int randomSeed = BitMixer.mix(hash ^ seed);
+                logger.trace("random seed=[" + randomSeed + "]");
+                final SplittableRandom random = new SplittableRandom(randomSeed);
                 int maxDoc = context.reader().maxDoc();
                 return new ConstantScoreScorer(
                     this,
@@ -119,8 +126,10 @@ public final class RandomSamplingQuery extends Query {
 
         @Override
         public int advance(int target) {
+            logger.trace("advance to [{}]", target);
             while (doc < target && doc < maxDoc) {
                 doc += distribution.next();
+                logger.trace("doc=[{}]", doc);
             }
             doc = doc < maxDoc ? doc : NO_MORE_DOCS;
             return doc;
```

the test output indicates that the doc iterator is called for each segment (it is created four times):

```
  1> [2024-03-22T07:24:35,469][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] random seed=[-1436384276]
  1> [2024-03-22T07:24:35,469][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] random seed=[-1436384276]
  1> [2024-03-22T07:24:35,491][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] advance to [0]
  1> [2024-03-22T07:24:35,491][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] advance to [0]
  1> [2024-03-22T07:24:35,491][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] doc=[0]
  1> [2024-03-22T07:24:35,491][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] doc=[0]
  1> [2024-03-22T07:24:35,491][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] advance to [1]
  1> [2024-03-22T07:24:35,491][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] advance to [1]
  1> [2024-03-22T07:24:35,492][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] doc=[15]
  1> [2024-03-22T07:24:35,491][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] doc=[15]
  1> [2024-03-22T07:24:35,493][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] random seed=[-1436384276]
  1> [2024-03-22T07:24:35,493][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] random seed=[-1436384276]
  1> [2024-03-22T07:24:35,493][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] advance to [0]
  1> [2024-03-22T07:24:35,493][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] advance to [0]
  1> [2024-03-22T07:24:35,493][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] doc=[0]
  1> [2024-03-22T07:24:35,493][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] doc=[0]
  1> [2024-03-22T07:24:35,493][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] advance to [1]
  1> [2024-03-22T07:24:35,494][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] advance to [1]
  1> [2024-03-22T07:24:35,494][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] doc=[15]
  1> [2024-03-22T07:24:35,494][TRACE][o.e.s.a.b.s.r.RandomSamplingQuery] [node_t3] doc=[15]
````

**Comment by iverase** [comment]
I wonder if segment concurrency is part of the issue here.  Moving the issue to ML, they have developed this aggregation.

**Comment by danielmitterdorfer** [comment]
> I wonder if segment concurrency is part of the issue here

I might have not done it correctly but during the investigation I did try to override `supportsParallelCollection` in `RandomSamplerAggregationBuilder` (returning `false`) and the test still failed.

**Comment by danielmitterdorfer** [comment]
@benwtrent I believe that you're the most knowledgeable person regarding this aggregation. Would you mind taking a look at this?

**Comment by benwtrent** [comment]
@danielmitterdorfer have you tried moving the random seed and generator outside of the scorer? Scorers are indeed per segment, but the weights won't be. But, then for sure, the parallel support would have to be turned off.

**Comment by danielmitterdorfer** [comment]
> have you tried moving the random seed and generator outside of the scorer?

I have only modified the code so I can add a trace statement. As the seed is always the same I'm not certain whether that would help? As far as I understand it, we iterate too often over the documents (I might be totally wrong as my knowledge of aggregation framework internals is very limited)?

>  Scorers are indeed per segment [...]

Does this mean that my expectation is wrong? Is it expected that the returned document count per bucket depends the number of segments? I suppose that this is unexpected but I don't have enough context to judge why the random sampler aggregation behaves that way. If my expectation is correct (i.e. the returned document count should be independent of the segment count) could you please take a look at the reproduction test case and see whether you can find the root cause?

**Comment by tveasey** [comment]
> Is it expected that the returned document count per bucket depends the number of segments?

This is indeed correct.

To explain why this will happen (even if you seed the RNG the same for each segment). Suppose I split a segment in two splitting at the midpoint. Traversal is skipping a random number of docs each step it takes (with expected size roughly 1 / p) where these are drawn from a RNG per segment. When I traverse the first half segment I will get the same set of random skips in the two cases. However, for the second half the steps will be different because the RNG state will be different since the case I have one segment I have been updating it.

Even if you use one RNG for all segments there is still an potentially a difference. Although you get an identical sequence of steps, the first step is an offset w.r.t. the start of each segment. If the docs are all in one segment (imagine stacking them one on top of the other) in effect the offset is w.r.t. the last document in the preceding "segment".

There are also cases where the doc order matters for random sampling but not for regular aggregations. Things like sum, mean, etc are transitive so the doc order is irrelevant (up to floating point error) when computed without sampling. Clearly, taking random steps and changing the order causes one to visit different docs though.

I would prefer not to try and make this behave the same way for any index configuration. We should be able to take advantage of segment parallelism properly. Also, as above, if the document order changes we have no hope of preserving values that stay the same for non-sampled aggregations. The way to think about this is that all statistics returned by the random sampler aggregation are in effect random variables. If you run with a seed on the exact same index configuration then you get the same exact same result (repeatability for point in time). Otherwise, you get guarantees about the distribution. For example, the mean error is zero, the size of variance of the count is 1 / np, etc.

**Comment by danielmitterdorfer** [comment]
Thanks for the in-depth explanation! If I interpret your statements correctly the consequence from a user perspective is, that one should not rely at all on the absolute value of `doc_count`. 

For example, here is a terms aggregation I ran as part of a random sampler agg:

```
{
  "size": 0,
  "aggregations": {
    "sample": {
      "random_sampler": {
        "probability": 0.00006650881155,
        "seed": -207162021
      },
      "aggs": {
        "stacktraces": {
          "terms": {
            "field": "Stacktrace.id"
          }
        }
      }
    }
  }
}
```

these are the doc counts (shortened to show only three buckets):

```json
{
  "sample": {
    "seed": -207162021,
    "probability": 0.00006650881155,
    "doc_count": 2873,
    "stacktraces": {
      "doc_count_error_upper_bound": 120285,
      "sum_other_doc_count": 40505911,
      "buckets": [
        {
          "key": "_q_HDlY1qNFgF2e5Po379Q",
          "doc_count": 872065
        },
        {
          "key": "9ZWC3FI6CKI56wgB1srUUw",
          "doc_count": 405961
        },
        {
          "key": "QfO3p_t6SUgm9ktJQAhoxg",
          "doc_count": 360854
        }
      ]
    }
  }
}
```

The top-level `doc_count` is apparently not scaled (smaller than the sum of the `doc_count` values in the buckets) and the per-bucket `doc_count` values depend on the number of segments in the index at that point. It seems it is only safe to make inferences about the ratio of individual buckets (e.g. `_q_HDlY1qNFgF2e5Po379Q` occurs  872065 / = 2.148 times more often than `9ZWC3FI6CKI56wgB1srUUw`)? 

This behavior seems trappy to me and I wonder whether we should either document this behavior or remove `doc_count` alltogether from the response?
