### ISSUE TITLE
Metrics: Measure synthetic source per-request document reconstruction latency

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#106659]
### Description

In the following months we will see usage of synthetic source increasing as a result of integrations adopting new index modes like `tsdb` and `logs`. When using synthetic source we reconstruct the original document using doc values and stored fields instead of just fetching the `_source` field. This implies larger latencies resulting from having to iterate all fields of a document to reconstruct the source instead of just fetching a single field. We would like to keep track of the time spent to reconstruct documents using synthetic source, measuring the per-request latency to reconstruct all the document sources involved in a specific request.

**Comment by lkts** [comment]
#106732 is merged but we are missing a widget in a dashhboard.
