### ISSUE TITLE
master not discovered or elected yet, an election requires a node with id [F-Tn-Q6vQuKE0Fgi5qtUMg] + 503 master not discovered exception

### ISSUE THREAD

**Issue by Haoke98** [elastic/elasticsearch#106639]
### Elasticsearch Version

8.3.3

### Java Version

_bundled_

### OS Version

Linux hm-195 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

There are two Master nodes and 6 data nodes in my ElasticSearch cluster. The Master node with the ID of [F-Tn-Q6vQuKE0Fgi5qtUMg] is the selected Master node. Then yesterday I accidentally delected this already elected Master node and then it could not be restored. There was another situation in the cluster where the Master could not be elected. This Master node reported the following error:
```
master not discovered or elected yet, an election requires a node with id [F-Tn-Q6vQuKE0Fgi5qtUMg], have only discovered non-quorum [{OPT__Master2}{ezEK9jukQTGtVW2DP3cSjA}{tHNwll8bTlmlmNes1HJPJg}{OPT__Master2}{192.168.1.30}{192.168.1.3 0 :9801}{m}];
```
Secondly, I followed many tutorials on the Internet and chose to modify voting_config_exclusions to solve this problem. However, at this time, when calling the /_cluster/voting_config_exclusions interface, a `503 master not discovered exception` error was reported. Then I tried other interfaces, as long as it was All interfaces related to the cluster reported the error `503 master not discovered exception`. I really don’t know how to repair this cluster without losing the data on the other 6 data nodes? By the way, My Elastic Search version is 8.3.3, and all nodes in the cluster are 8.3.3

### Steps to Reproduce

All connection is good and discovered successfully, but  the problem is still exist.

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
