### ISSUE TITLE
Could not resolve org.elasticsearch.ml:ml-cpp:8.12.2-SNAPSHOT

### ISSUE THREAD

**Issue by ichar0** [elastic/elasticsearch#106738]
Could not determine the dependencies of task ':x-pack:plugin:ml:explodedBundlePlugin'.
> Could not resolve all task dependencies for configuration ':x-pack:plugin:ml:nativeBundle'.
   > Could not find org.elasticsearch.ml:ml-cpp:8.12.2-SNAPSHOT.
     Searched in the following locations:
       - https://artifacts-snapshot.elastic.co/ml-cpp/8.12.2-SNAPSHOT/downloads/ml-cpp/ml-cpp-8.12.2-SNAPSHOT-deps.zip
     Required by:
         project :x-pack:plugin:ml

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by mark-vieira** [comment]
The 8.12 branch is end-of-life with the release of 8.13 today.

**Comment by rblohagavkar91** [comment]
Hi,

We are using Elastic search 8.13.3 and we are facing same issue - **Could not find org.elasticsearch.ml:ml-cpp:8.13.3-SNAPSHOT.**

8.14.1 is working fine for us. What could be the issue with 8.13.3 version?

Thanks
