### ISSUE TITLE
[CI] SecureHaHdfsFailoverTestSuiteIT and HaHdfsFailoverTestSuiteIT classMethod failing

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#106776]
Looks related to https://github.com/elastic/elasticsearch/issues/106739, but this time it's complaining about jar hell.

CC @breskeby

**Build scan:**
https://gradle-enterprise.elastic.co/s/er263iwnzamim/tests/:plugins:repository-hdfs:javaRestTest/org.elasticsearch.repositories.hdfs.SecureHaHdfsFailoverTestSuiteIT

**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.repositories.hdfs.SecureHaHdfsFailoverTestSuiteIT#classMethod`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('classMethod'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.repositories.hdfs.SecureHaHdfsFailoverTestSuiteIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.RuntimeException: found jar hell in test classpath

  at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:106)
  at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:307)
  at java.lang.Class.forName0(Class.java:-2)
  at java.lang.Class.forName(Class.java:467)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:631)

  Caused by: java.lang.IllegalStateException: jar hell!
  class: org.bouncycastle.LICENSE
  jar1: /dev/shm/bk/bk-agent-prod-gcp-1711454666052002008/elastic/elasticsearch-periodic/test/fixtures/hdfs-fixture/build/distributions/hdfs-fixture-8.14.0-SNAPSHOT-hdfs3.jar
  jar2: /opt/buildkite-agent/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bc-fips/1.0.2.4/9008d04fc13da6455e6a792935b93b629757335d/bc-fips-1.0.2.4.jar

    at org.elasticsearch.jdk.JarHell.checkClass(JarHell.java:315)
    at org.elasticsearch.jdk.JarHell.checkJarHell(JarHell.java:233)
    at org.elasticsearch.jdk.JarHell.checkJarHell(JarHell.java:84)
    at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:104)
    at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:307)
    at java.lang.Class.forName0(Class.java:-2)
    at java.lang.Class.forName(Class.java:467)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:631)

```

**Comment by breskeby** [comment]
should be fixed by https://github.com/elastic/elasticsearch/pull/106762

**Comment by breskeby** [comment]
seems its something deterministic I have to figure out that makes this one fail. I still suspect an encoding issue somehow
