### ISSUE TITLE
ipv6 support for unicast hosts

### ISSUE THREAD

**Issue by DominicBoettger** [elastic/elasticsearch#10675]
Adding 

-Des.discovery.zen.ping.unicast.hosts="2a01:ddd:eeee:ffff:0:0:0:2" fails with address not reachable.

also
-Des.discovery.zen.ping.unicast.hosts="[2a01:ddd:eeee:ffff:0:0:0:2]" does not work.

Best regards
Dominic

**Comment by rmuir** [comment]
Fixed by #12999
