### ISSUE TITLE
Regression in get index settings `human=true` in 8.9

### ISSUE THREAD

**Issue by s-nel** [elastic/elasticsearch#106795]
### Elasticsearch Version

8.9

### Java Version

_bundled_

### OS Version

Docker, Elastic Cloud

### Problem Description

It appears that there is a regression in the `GET /<index>/_settings?human=true` API in 8.9.

In 8.8.2, Elasticsearch returns the created version of the index in semantic, human-readable format

```json
{
  ".security-7": {
    "settings": {
      "index": {
        ...
        "creation_date_string": "2024-03-27T02:26:11.291Z",
        "creation_date": "1711506371291",
        "version": {
          "created_string": "8.8.2",
          "created": "8080299"
        },
```

But in 8.9.0 the `created_string` format changed and it's no longer human-readable
```json
{
  ".security-7": {
    "settings": {
      "index": {
        ...
        "creation_date_string": "2024-03-27T02:26:21.362Z",
        "creation_date": "1711506381362",
        "version": {
          "created_string": "8090099",  <---- here's the issue
          "created": "8090099"
        },
```

Notice that `creation_date_string` is returning the expected formatted string, but `created_string` isn't.

### Steps to Reproduce

1. Call `GET <index>/_settings?human=true`
2. Notice that `version.created_string` is a number not a human-readable version

**Comment by gkatiforis** [comment]
Hi @s-nel, can I take this up?

**Comment by mosche** [comment]
This is due to migrating these versions away from release version to `IndexVersion`.
Fixing this should be trivial using `IndexVersion.toReleaseVersion`.

**Comment by gkatiforis** [comment]
Hi @s-nel , @mosche , can I work on this?

**Comment by mosche** [comment]
Sure, of course 👍  Thank you for looking into this @gkatiforis
