### ISSUE TITLE
Snapshot indices with wildcard not working

### ISSUE THREAD

**Issue by tostasqb** [elastic/elasticsearch#10678]
My indices naming convention is `[client_name]_movements_[year]` and I have set my backup repositories to backup data by client:

	curl -XPUT 'http://localhost:9200/_snapshot/es_client_one' -d '{
		"type": "fs",
		"settings": {
			"indices": "client_one_*",
			"location": "/opt/backups/es_client_one",
			"compress": true,
			"verify" : "true"
		}
	}'

when testing a first snapshot:

    curl -XPUT "http://localhost:9200/_snapshot/es_client_one/snapshot_20150420_1437"
the result was that every index with no exceptions were backed up to "/opt/backups/es_client_one"

note: version 1.4.4

**Comment by imotov** [comment]
@tostasqb please note that mailing list is much better place to ask questions like this. We are trying to keep github issue for tracking bugs and feature requests. The list of indices should go into the [snapshot command](http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_snapshot) not into repository settings.

**Comment by tostasqb** [comment]
honest mistake.
Thank you sir
