### ISSUE TITLE
how to set code styele for elasticsearch

### ISSUE THREAD

**Issue by fafeidou** [elastic/elasticsearch#106734]
### Elasticsearch Version

8.12

### Java Version

_bundled_

### OS Version

mac

### Problem Description

already set build-conventions/formatterConfig.xml ,but not Take effect

### Steps to Reproduce

thanks

```[tasklist]
### Tasks
```

**Comment by gmarouli** [comment]
Hi @fafeidou , thank you very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

If this is not a question but indeed a bug report, please feel free to reopen it and enrich it with a reproduction path. For example:
- The steps you took to install it
- The specific command that is failing including, what did you expect to happen and what did you experience happening.
- The exact OS version.

The information above is essential for us to debug this issue.
