### ISSUE TITLE
请问下这个向量存储的embeddings模型是什么模型

### ISSUE THREAD

**Issue by iaoxuesheng** [elastic/elasticsearch#106859]
### Elasticsearch Version

8.7.1

### Java Version

_bundled_

### OS Version

ubuntu

### Problem Description

请问下这个向量存储的embeddings模型是什么模型

### Steps to Reproduce

请问下这个向量存储的embeddings模型是什么模型

### Logs (if relevant)

请问下这个向量存储的embeddings模型是什么模型

**Comment by mosche** [comment]
Closing this, please provide enough context (in english) so we can understand your issue.
