### ISSUE TITLE
ES do not wait for all shards being closed before shutdown/restart

### ISSUE THREAD

**Issue by somebody32** [elastic/elasticsearch#10680]
Hi!

I have a one node setup and spotted that if I create a lot of indices/shards and then immediatly will try to restart the server, it will come back online in the red state with a couple of unassigned shards and errors in log like this:

```
Caused by: java.io.EOFException: read past EOF:   
NIOFSIndexInput(path="/var/lib/elasticsearch/elasticsearch/nodes/0/indices/intelligence-reports-2014.05.01/3/index/segments_2”)
```
The problem is that ES starts to flush shards to the hard drive, but does not manage to do that in time, so some shards remain unflushed.

Init script that comes bundled with ES gives 20 seconds for it to finish all preparations:
start-stop-daemon --stop --pidfile "$PID_FILE" \ --user "$ES_USER" \ --retry=TERM/20/KILL/5 > /dev/null

If you bump that period, ES have [hardcoded rule to do that in 30 secs](https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/indices/IndicesService.java#L153), otherwise:
```
[2015-04-21 15:04:03,558][INFO ][node ] [collaboration] stopping ...   
 [2015-04-21 15:04:33,581][WARN ][indices ] [collaboration] Not all shards are closed yet, waited 30sec - stopping service    
[2015-04-21 15:04:33,581][INFO ][node ] [collaboration] stopped    
[2015-04-21 15:04:33,581][INFO ][node ] [collaboration] closing ...    
[2015-04-21 15:04:33,587][INFO ][node ] [collaboration] closed
```

I know that I can "fix" this by send `flush` after massive write is finished, but why ES needs to kill himself after 30 secs and does not wait for shards to close?

**Comment by somebody32** [comment]
Managed to fix this and make it robust by switching `cluster.routing.allocation.enable` from `ALL` to `NEW_PRIMARIES`. But this seems very strange anyway

**Comment by somebody32** [comment]
Was quick in decisions, allocation switch didn't help. That happening just after heavy writes, ie:

1. Clean all indexes
2. Write 370 indexes in batches
3. Wait for cluster green state and pending tasks == 0
4. Restart cluster, a couple of shards will be unassigned

**Comment by saimonmoore** [comment]
yeah this happened to me too. Would like to know too.

**Comment by ivanilves** [comment]
Confirm it happened to me too. Would like to have configurable **shard_close_timeout** or something...

**Comment by clintongormley** [comment]
@tlrx do we force shutdown of ES nodes from the init scripts? I thought we'd removed that?

**Comment by clintongormley** [comment]
Oh, it's not in the init script...

@s1monw what do you think about this?

**Comment by tlrx** [comment]
> @tlrx do we force shutdown of ES nodes from the init scripts? I thought we'd removed that?

We force shutdown by killing process after ~20 sec (see [here for RPM](https://github.com/elastic/elasticsearch/blob/master/src/packaging/rpm/init.d/elasticsearch#L113) and [here for DEB](https://github.com/elastic/elasticsearch/blob/master/src/packaging/deb/init.d/elasticsearch#L189)). I don't remind we decided to remove this for elasticsearch.

I'm not familiar with the IndicesService class but I find those 30 sec a bit strange.

**Comment by clintongormley** [comment]
> We force shutdown by killing process after ~20 sec (see here for RPM and here for DEB). I don't remind we decided to remove this for elasticsearch.

So it looks like `killproc` is sending a -9 after our specified 20 seconds (see https://github.com/elastic/elasticsearch/pull/3973#issuecomment-54807069) , but Elasticsearch is waiting for 30 seconds... Perhaps we should make the init script timeout longer.

**Comment by clintongormley** [comment]
@somebody32 @saimonmoore @ivanilves what versions of Elasticsearch are you seeing this on?

**Comment by somebody32** [comment]
@clintongormley 1.5.0 (and looks like no difference in 1.5.1 too)

And, as I said, the problem not only in init script. Bult-in 30 seconds grace period was not enough in our case to flush all shards

**Comment by bleskes** [comment]
@tlrx  - @s1monw 's PR fix the internal wait in ES. I might be missing something here but I think the RPM/DEB still needs to be changed for it to be effective no?

**Comment by tlrx** [comment]
@bleskes right - I created #11248 to track this.
