### ISSUE TITLE
Documentation Review

### ISSUE THREAD

**Issue by Malek-Zaag** [elastic/elasticsearch#106813]
There is a repeating "the" on  "What is a Schema ?" section
https://www.elastic.co/blog/found-elasticsearch-mapping-introduction

**Comment by mark-vieira** [comment]
@nkvoll Not sure what the process is for fixing typos is 11 year old blog posts but maybe you can investigate? In the mean time I'm going to close this issue as it's not an Elasticsearch bug.

**Comment by nkvoll** [comment]
Thank you @Malek-Zaag for reporting and @mark-vieira for pinging me in on this. This should now be fixed ✅
