### ISSUE TITLE
KnnVectorQueryBuilder does not respect allowUnmappedFields

### ISSUE THREAD

**Issue by Mikep86** [elastic/elasticsearch#106846]
### Elasticsearch Version

8.13

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

`KnnVectorQueryBuilder` does not respect the `index.query.parse.allow_unmapped_fields` index setting. If this is set to `true` (the default value), queries should be rewritten to `MatchNoDocsQuery` if the field specified in the query does not exist. However, `KnnVectorQueryBuilder` always returns an error in this case.

### Steps to Reproduce

1. Create an index with default settings

```
PUT test-index 
```

2. Run a `knn` query against a missing field

```
GET test-index/_search
{
    "query": {
        "knn": {
            "field": "missing",
            "query_vector": [ 1.0, 2.0 ]
        }
    }
}
```

**Comment by benwtrent** [comment]
closed by: https://github.com/elastic/elasticsearch/pull/107047
