### ISSUE TITLE
Kibana (or possibly ES) crashing every time Discover is clicked

### ISSUE THREAD

**Issue by ashwgupt** [elastic/elasticsearch#10697]
Hi,

My rather a working setup has gone rouge all of a sudden and has started throwing below errors everytime I select my Kibana's Discover section. Even worse as my demostration date to management is approaching fast :-(

Any help will be highligh appreciated.

Error Throwing on Browser (Firefox):-
Oops!
Looks like something went wrong. Refreshing may do the trick.
Go Back or clear your session 

Discover: err.stack is undefined.
Notifier.prototype.error@http://localhost:5601/index.js?_b=5930:45607:7
bound@http://localhost:5601/index.js?_b=5930:32081:16
init</</<@http://localhost:5601/index.js?_b=5930:118772:11
qFactory/defer/deferred.promise.then/wrappedCallback@http://localhost:5601/index.js?_b=5930:20873:31
qFactory/ref/<.then/<@http://localhost:5601/index.js?_b=5930:20959:26
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://localhost:5601/index.js?_b=5930:22002:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@http://localhost:5601/index.js?_b=5930:21814:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:5601/index.js?_b=5930:22106:13
done@http://localhost:5601/index.js?_b=5930:17641:34
completeRequest@http://localhost:5601/index.js?_b=5930:17855:7
createHttpBackend/</xhr.onreadystatechange@http://localhost:5601/index.js?_b=5930:17794:1

Environmental Information:-

the version of JVM - "1.8.0_31" (for both Kibana and ES)
local configuration - All Default (for both Kibana and ES)
operating system - Linux 2.6.32-431.11.2.el6.x86_64 (for ES) and Win 7 (for Kibana)

Health Status of my ES Server:-
curl -XGET 'http://127.0.0.1:9200/_cluster/health?pretty'
{
  "cluster_name" : "fil_logs_cluster01",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 421,
  "active_shards" : 421,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 421
}

Cluster Stats of my ES Cluster:-
curl -XGET 'http://localhost:9200/_cluster/stats?human&pretty'
{
  "timestamp" : 1429609506180,
  "cluster_name" : "fil_logs_cluster01",
  "status" : "yellow",
  "indices" : {
    "count" : 85,
    "shards" : {
      "total" : 421,
      "primaries" : 421,
      "replication" : 0.0,
      "index" : {
        "shards" : {
          "min" : 1,
          "max" : 5,
          "avg" : 4.952941176470588
        },
        "primaries" : {
          "min" : 1,
          "max" : 5,
          "avg" : 4.952941176470588
        },
        "replication" : {
          "min" : 0.0,
          "max" : 0.0,
          "avg" : 0.0
        }
      }
    },
    "docs" : {
      "count" : 11726,
      "deleted" : 4
    },
    "store" : {
      "size" : "14.1mb",
      "size_in_bytes" : 14789369,
      "throttle_time" : "0s",
      "throttle_time_in_millis" : 0
    },
    "fielddata" : {
      "memory_size" : "1.3mb",
      "memory_size_in_bytes" : 1411360,
      "evictions" : 0
    },
    "filter_cache" : {
      "memory_size" : "811.7kb",
      "memory_size_in_bytes" : 831188,
      "evictions" : 0
    },
    "id_cache" : {
      "memory_size" : "0b",
      "memory_size_in_bytes" : 0
    },
    "completion" : {
      "size" : "0b",
      "size_in_bytes" : 0
    },
    "segments" : {
      "count" : 513,
      "memory" : "20.9mb",
      "memory_in_bytes" : 21936938,
      "index_writer_memory" : "0b",
      "index_writer_memory_in_bytes" : 0,
      "index_writer_max_memory" : "205.5mb",
      "index_writer_max_memory_in_bytes" : 215552000,
      "version_map_memory" : "0b",
      "version_map_memory_in_bytes" : 0,
      "fixed_bit_set" : "0b",
      "fixed_bit_set_memory_in_bytes" : 0
    },
    "percolate" : {
      "total" : 0,
      "get_time" : "0s",
      "time_in_millis" : 0,
      "current" : 0,
      "memory_size_in_bytes" : -1,
      "memory_size" : "-1b",
      "queries" : 0
    }
  },
  "nodes" : {
    "count" : {
      "total" : 1,
      "master_only" : 0,
      "data_only" : 0,
      "master_data" : 1,
      "client" : 0
    },
    "versions" : [ "1.4.4" ],
    "os" : {
      "available_processors" : 2,
      "mem" : {
        "total" : "1.7gb",
        "total_in_bytes" : 1901912064
      },
      "cpu" : [ {
        "vendor" : "Intel",
        "model" : "Xeon",
        "mhz" : 2892,
        "total_cores" : 2,
        "total_sockets" : 1,
        "cores_per_socket" : 2,
        "cache_size" : "20kb",
        "cache_size_in_bytes" : 20480,
        "count" : 1
      } ]
    },
    "process" : {
      "cpu" : {
        "percent" : 0
      },
      "open_file_descriptors" : {
        "min" : 1477,
        "max" : 1477,
        "avg" : 1477
      }
    },
    "jvm" : {
      "max_uptime" : "1.1d",
      "max_uptime_in_millis" : 98348135,
      "versions" : [ {
        "version" : "1.8.0_31",
        "vm_name" : "Java HotSpot(TM) 64-Bit Server VM",
        "vm_version" : "25.31-b07",
        "vm_vendor" : "Oracle Corporation",
        "count" : 1
      } ],
      "mem" : {
        "heap_used" : "160.8mb",
        "heap_used_in_bytes" : 168635336,
        "heap_max" : "1007.3mb",
        "heap_max_in_bytes" : 1056309248
      },
      "threads" : 44
    },
    "fs" : {
      "total" : "1007.8mb",
      "total_in_bytes" : 1056858112,
      "free" : "526mb",
      "free_in_bytes" : 551628800,
      "available" : "474.8mb",
      "available_in_bytes" : 497942528,
      "disk_reads" : 410938,
      "disk_writes" : 525704,
      "disk_io_op" : 936642,
      "disk_read_size" : "1.8gb",
      "disk_read_size_in_bytes" : 2031592448,
      "disk_write_size" : "2gb",
      "disk_write_size_in_bytes" : 2153283584,
      "disk_io_size" : "3.8gb",
      "disk_io_size_in_bytes" : 4184876032,
      "disk_queue" : "0",
      "disk_service_time" : "1.7"
    },
    "plugins" : [ ]
  }
}

**Comment by markwalkom** [comment]
We reserve github for bugs and feature requests, while this appears to be an operational matter.

I'd suggest that you send something to the mailing list for assistance - https://groups.google.com/forum/#!forum/elasticsearch

**Comment by ashwgupt** [comment]
Sure, thanks

**Comment by programmer11** [comment]
I am having the same issue as above. Could you tell me the resolution to it?

**Comment by markwalkom** [comment]
Please use the forums - https://discuss.elastic.co
