### ISSUE TITLE
Allow custom version_type comparison methods via plugins

### ISSUE THREAD

**Issue by schmichael** [elastic/elasticsearch#10692]
It would be useful to be able to write custom document version comparison methods as plugins (or perhaps even scripts?) in order to support custom version semantics such as vector clocks.

**Comment by bleskes** [comment]
Hi Michael,

Can you elaborate on which API you would need and how you would implement the vector clocks? Remember that ES user a primary back up model where only accepts writes on the primary shard copy. If there is no primary available, writes will be rejected (with a default timeout of 1m). This means there is only 1 official version of each document.

**Comment by schmichael** [comment]
@bleskes Sure, I'm still sketching out a new system, so this feature may not be necessary.

The system involves a pipeline in which mutations are merged into documents upstream from ES using vector clocks for partial ordering. By the time documents reach the end of the pipeline for indexing they may be indexed out of order such that a document with version `A:3,B:3` is indexed *after* a document with version `A:9,B:3`. The `A:3,B:3` version of the document should be dropped as a later version is already indexed.

However, without a mechanism for resolving conflicts such as `A:4,B:2` vs `A:3,B:3`, a deterministic fallback algorithm would have to be used in its place (such as a simple lexicographical comparison) and undermine the consistency benefits of using vector clocks in the first place...

...so I think perhaps the better solution is for a system upstream in our pipeline to generate a monotonic version number for use by the indexer. Not sure it can be done without either a lot of coordination or stale (but always moving forward in time) documents in the index, but it's probably better than adding complexity to ES.

I'll go ahead and close this unless someone else can think of how vector clocks without a custom conflict resolution mechanism are safe/useful.
