### ISSUE TITLE
Chinese Support

### ISSUE THREAD

**Issue by cr2121** [elastic/elasticsearch#10695]
Dear team,

I have a document:
`
{"tags": [
"1",
"天猫",
"京东商城"
],
"name": "tao"}
`

When I use 
`{
    "query":{
        "bool" : {
            "must" : {
                "terms" : {
                    "tags" : ["1"],
                     minimum_should_match : 1
                 }
            }
         }
    }
}`
got right result.

But when I query with
`{
    "query":{
        "bool" : {
            "must" : {
                "terms" : {
                    "tags" : ["天猫"],
                     minimum_should_match : 1
                 }
            }
         }
    }
}`
got nothing.

**Comment by johtani** [comment]
Please ask questions like this on the [mailing list](https://groups.google.com/forum/?fromgroups=#!forum/elasticsearch).

And your `tags` field analyzed by analyzer, however `terms` query does *not analyzed*.

See: http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html
