### ISSUE TITLE
parsing logs with same prefix

### ISSUE THREAD

**Issue by rakesh91** [elastic/elasticsearch#10698]
Hi,
I have been logstash to parse my logs for quite some time and its been cake walk for me. Now I had to add few more data point to some specific logs and its failing somewhere. Failing means logstash is not sending the data to ES properly.
For example:
previous logs:
  1. A B C D
new logs:
 1. A B C D
 2. A B C D E F                

I wrote corresponding rules for grok and placed rules for 2 and 1 in the same order in grok filter. Then logstash is not sending output to ES. If I put the 1st rule above the second rule, 'E' and 'F' 's data are missing in output. 

So please tell me, what is the mistake I am doing?

**Comment by dadoonet** [comment]
Not an Elasticsearch issue.

You should ask this on logstash mailing list and if it's an issue open it in logstash repository.

Closing.

**Comment by rakesh91** [comment]
@dadoonet Thanks, Sorry for the mistake.
