### ISSUE TITLE
Pattern capture email example not complete

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#10690]
https://github.com/elastic/elasticsearch/blob/master/docs/reference/analysis/tokenfilters/pattern-capture-tokenfilter.asciidoc#pattern-capture-token-filter

The pattern capture example in the doc says it will produce the following tokens:
>When the above analyzer is used on an email address like:
john-smith_123@foo-bar.com
it would produce the following tokens: [ john-smith_123, foo-bar.com, john, smith_123, smith, 123, foo, foo-bar.com, bar, com ]

The pattern in the doc example:

```
 "patterns" : [
                  "(\\w+)",
                  "(\\p{L}+)",
                  "(\\d+)",
                  "@(.+)"
               ]
```

The above does not actually produce the `john-smith_123` token.  Adding the last line in the patterns array will produce the additional `john-smith_123` token (though I am not sure if it is the best way since I'm not a regex guru):

```
               "patterns" : [
                  "(\\w+)",
                  "(\\p{L}+)",
                  "(\\d+)",
                  "@(.+)",
                  "([^@]+)"
               ]
```

**Comment by clintongormley** [comment]
thanks @ppf2 - fixed
