### ISSUE TITLE
What is the embeddings model for this vector store?

### ISSUE THREAD

**Issue by iaoxuesheng** [elastic/elasticsearch#106945]
### Elasticsearch Version

8.7.1

### Java Version

_bundled_

### OS Version

ubuntu20.04

### Problem Description

What is the embeddings model for this vector store?

### Steps to Reproduce

What is the embeddings model for this vector store?

### Logs (if relevant)

What is the embeddings model for this vector store?

**Comment by kingherc** [comment]
@iaoxuesheng this bug issue contains minimal information and I cannot make something useful out of it. Closing for now. Please re-edit if you need to, and we can re-open it. Thanks
