### ISSUE TITLE
I just want to know what the word embedding model used in our project to convert text into vector storage is

### ISSUE THREAD

**Issue by iaoxuesheng** [elastic/elasticsearch#107024]
### Elasticsearch Version

8.7

### Java Version

_bundled_

### OS Version

ubuntu20.04

### Problem Description

I just want to know what the word embedding model used in our project to convert text into vector storage is

### Steps to Reproduce

I just want to know what the word embedding model used in our project to convert text into vector storage is

### Logs (if relevant)

I just want to know what the word embedding model used in our project to convert text into vector storage is

**Comment by yukha-dw** [comment]
Please do not ask question as a bug, the documentation might help you https://www.elastic.co/guide/en/machine-learning/8.13/ml-nlp.html

**Comment by tlrx** [comment]
Thanks for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by iaoxuesheng** [comment]
> Thanks for your interest in Elasticsearch.
> 
> This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co/). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.
> 
> There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

thankyou for your help
