### ISSUE TITLE
SQL: Update docs about X-Pack

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#107005]
### Description

De-emphasise X-Pack in SQL docs. Grep'd:
* [index](https://www.elastic.co/guide/en/elasticsearch/reference/current/xpack-sql.html)
* [overview](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-overview.html)
* [getting started](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-getting-started.html):
 ```suggestion
  - There is a script to start it shipped in x-pack’s bin directory:
  + There is a script to start it shipped in Elasticsearch'es `bin` directory:
  ```

**Comment by lcawl** [comment]
There are a handful of other lingering occurrences of "{xpack}" and "X-Pack" in the asciidoc files, which should probably be cleaned up at the same time.
