### ISSUE TITLE
Publish cluster nodes via mDNS to be able to build a unicast seed list for new host

### ISSUE THREAD

**Issue by bguezzie** [elastic/elasticsearch#10706]
It would be nice if mDNS could be used to discover an initial list of nodes for an ES cluster.  That list could then be used to set up a new node for unicast with a sensible initial list of nodes, without needing to have a static list known in advance.

**Comment by clintongormley** [comment]
This ticket hasn't garnered any support in the last 9 months, and I think it is unlikely that we would add something like this to core.  This would probably be doable as a plugin if anybody has the TUITs.
