### ISSUE TITLE
Elasticsearch concurrent search requests block each other

### ISSUE THREAD

**Issue by TheGreatYamcha** [elastic/elasticsearch#10704]
I have a cluster of 5 nodes running ES 1.4.4 on Linux. My application sends search requests using the java transportClient. I've noticed a very unusual behavior:
If multiple requests (threads) come in, Elasticsearch won't return any of the thread's response until it's finished processing all of them and then sends all the responses at once.
I initially thought this might be because my transportClient was singleton, but the problem persisted when I made it create a new client per request.

**Comment by nilsga** [comment]
Do you have any thread dumps for when this happens? We seem to have some blocking issues with the TransportClient as well, and I'm curious if it could be the same thing we're experiencing. So comparing the thread dumps would be helpful.

Also, is this something you experienced after upgrading from some other version? If yes, which version were you running previosly?

**Comment by clintongormley** [comment]
@TheGreatYamcha could you upload some code demonstrating the problem?

**Comment by TheGreatYamcha** [comment]
I managed to fix the problem. This was the original code:
```java
OrFilterBuilder fb = FilterBuilders.orFilter();

for (String key : indexValueMap.keySet()) {
fb.add(FilterBuilders.indicesFilter(
  FilterBuilders.termFilter("hashedValue", indexValueMap.get(key)), key).noMatchFilter("none"));
}
FilteredQueryBuilder qb = QueryBuilders.filteredQuery(null, fb);
SearchResponse sr = client.prepareSearch().setPostFilter(fb).execute().actionGet();
```
and then simply changed the last line to:
```java
SearchResponse sr = client.prepareSearch().setQuery(qb).execute().actionGet();
```
and everything worked i.e. I wasn't able to reproduce the problem.
Although the second code was significantly faster even on a single thread, so it might be that with this, there wasn't enough threads to replicate to problem.

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/10940
