### ISSUE TITLE
How does the shard of the index re shard after the ES node goes offline?

### ISSUE THREAD

**Issue by smallemployees** [elastic/elasticsearch#107185]
### Elasticsearch Version

7.17.18

### Java Version

_bundled_ 1.8

### OS Version

centos 7.9

### Problem Description

I replaced the original data node and found that the previous indexes were in an unallocated state

### Steps to Reproduce

How should I operate to solve the problem

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
