### ISSUE TITLE
ArgMax and ArgMin aggregations

### ISSUE THREAD

**Issue by rcrezende** [elastic/elasticsearch#10716]
Have argmin and argmax aggregations [http://en.wikipedia.org/wiki/Arg_max]

As percentiles, that would be a multi-value metric aggregation, but size limit controls that.

Request
```
{
    "aggs" : {
        "product_with_max_price" : {
            "argmax" : { 
                "arg" : "price",
                "field" : "product",
                "size" : 5
              }
          }
    }
}
```

Response
```
{
    ...
    "aggregations": {
        "product_with_max_price": {
            "values": {
               "ferrari" : 500000,
               "lamborghini" : 500000
            }
        }
    }
}
```

**Comment by colings86** [comment]
@rcrezende you should be able to get this information with the existing aggregations by using the `terms` and `max` aggregations:

```json
{
  "aggs": {
    "product_with_max_price": {
      "terms": {
        "field": "product",
        "size": 5,
        "order": {
          "max_price": "desc"
        }
      },
      "aggs": {
        "max_price": {
          "max": {
            "field": "price"
          }
        }
      }
    }
  }
}
```

This will get a list of the top 5 terms ordered by maximum price. Your client can then look for the top N which have the same value. With https://github.com/elastic/elasticsearch/issues/10000 coming in 2.0 you could use the `max_bucket` aggregation to do this last step for you and return only the terms which have the maximum value.

A similar approach could be used for the argmin.

**Comment by clintongormley** [comment]
Agree with @colings86 - going to close this
