### ISSUE TITLE
[ES|QL] Add Base64 to text conversion inside ES|QL

### ISSUE THREAD

**Issue by ninoslavmiskovic** [elastic/elasticsearch#107135]
### Description

We have received requests for adding Base64 (and other hashing) conversion in ES|QL. 

Use case examples: 

- There are situations where data might be sent as base64, and analysts manually need to decode it in these situations today (or ask the assistant)
- [Security] - Obfuscation attacks leverage techniques like Base64 encoding to hide the true intent of code or data, making it more challenging for security tools and analysts to detect and mitigate potential threats. (Attackers use Base64 to encode malicious scripts, payloads, or configuration settings within malware. Since Base64-encoded data is a harmless string of ASCII characters, it can bypass simple detection mechanisms that look for specific binary patterns or malicious signatures in the code. 
- [Observability] Base64 has benefits for O11y in terms of compatibility, safety, and integrity of data transmission. It helps ensure that data, whether binary or text with special characters, can be accurately and efficiently logged, monitored, and analyzed across diverse systems and platforms.

**Comment by nik9000** [comment]
A couple of questions:
1. Do you want an ENCODE and DECODE method?
2. What type should the `DECODE` method produce? We don't yet have a "binary" type in the language - though I don't think that'd be too hard to add. The trick is what would you want to *do* with a binary type? Look for sequences of bytes? Convert the binary to a string using some character set? All of those are more functions we'd have to add too. Adding functions isn't super hard, but it's more.

**Comment by ninoslavmiskovic** [comment]
@nik9000 

1. I see the use case for decoding higher than encode. Basically what we want to do is remove the obstacle for users to have to go to an external website to do decode the base64. Encode can be a separate request IMO. 
2. I think converting it to a string would make sense, and also something that can be seen in other languages like e.g Kusto/KQL ([link](https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/base64-decode-tostring-function)).

@abatsakis and @costin WDYT ?
