### ISSUE TITLE
could not pack/validate JSON response

### ISSUE THREAD

**Issue by rock1013** [elastic/elasticsearch#107186]
### Elasticsearch Version

Version: 8.13.1, Build: deb/9287f29bba5e270bd51d557b8daccb7d118ba247/2024-03-29T10:05:29.787251984Z, JVM: 22

### Installed Plugins

none

### Java Version

_bundled_

### OS Version

Linux server102 5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

After update to 8.12.2 and 8.13.1,ES response of fluentbit cant over 64KB. Json will be truncated. So it cant be parsed.

### Steps to Reproduce

With update to 8.12.2 and 8.13.1, the fluentbit logs errors.

### Logs (if relevant)

Here is some tcpdump result: 192.168.3.200 is es 240 fluentbit
![image](https://github.com/elastic/elasticsearch/assets/13289772/23d8e812-79e8-4b63-957d-c6053c9c4076)
[httpflow.txt](https://github.com/elastic/elasticsearch/files/14896881/httpflow.txt)
Thanks for help.
[fluentbitError.txt](https://github.com/elastic/elasticsearch/files/14896891/fluentbitError.txt)

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by rock1013** [comment]
Sure, I've post it in ES forum. @DaveCTurner, thank you for help.

**Comment by rock1013** [comment]
Helllo @DaveCTurner, Can I reopen this issue? Cuz I found if we set <chunked_transfer_encoding off;>on my nginx, this issue happens. This seems has relation with this https://github.com/elastic/elasticsearch/pull/105258.

**Comment by DaveCTurner** [comment]
No, that's not an Elasticsearch bug so there's no need to have an issue here tracking it. Support for chunked transfer-encoding is required in all clients (it's a mandatory part of the HTTP/1.1 spec).

**Comment by rock1013** [comment]
Thanks for your answer. And I can understand the reason now. Thank you.
