### ISSUE TITLE
Master node behind proxy

### ISSUE THREAD

**Issue by Kiryuumaru** [elastic/elasticsearch#107193]
### Description

Im having trouble deploying it on azure container apps. I have deployed 2 container apps for master and data nodes, i have problem connecting my data nodes to my master node.
The logs says:
`master not discovered yet, this node has not previously joined a bootstrapped cluster`
I notice in logs that my seed_host was converted to an IP address which i cannot access.
I suspect this might be because the azure container apps sits behind its internal load balancer. 
It would be great if there is an option to make data nodes connect to its master node host as it is from a proxy or load balancer

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by DaveCTurner** [comment]
... specifically, adding support for a proxy in front of the elected master node is not going to solve the problem you describe. See [these docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#modules-network-binding-publishing) for more information.
