### ISSUE TITLE
Need help on azure container apps

### ISSUE THREAD

**Issue by Kiryuumaru** [elastic/elasticsearch#107189]
I am a complete beginner in es. Im having trouble deploying it on azure container apps. I have deployed 2 container apps for master and data nodes, i have problem connecting my data nodes to my master node.
Master config:
```
.WithEnvironment("network.host", "0.0.0.0")
.WithEnvironment("node.name", "es-master")
.WithEnvironment("cluster.name", "es-cluster")
.WithEnvironment("ES_JAVA_OPTS", "-Xms4g -Xmx4g")
.WithEnvironment("xpack.security.enabled", "false")
.WithEnvironment("xpack.security.enrollment.enabled", "false")
.WithEnvironment("node.store.allow_mmap", "false")
.WithEnvironment("cluster.initial_master_nodes", "es-master")
```
Data config:
```
.WithEnvironment("network.host", "0.0.0.0")
.WithEnvironment("cluster.name", "es-cluster")
.WithEnvironment("ES_JAVA_OPTS", "-Xms4g -Xmx4g")
.WithEnvironment("xpack.security.enabled", "false")
.WithEnvironment("xpack.security.enrollment.enabled", "false")
.WithEnvironment("node.store.allow_mmap", "false")
.WithEnvironment("discovery.seed_hosts", "https://es-master.sample-123abc.southeastasia.azurecontainerapps.io")
```
The logs says:
`master not discovered yet, this node has not previously joined a bootstrapped cluster`

I also tried allowing public access for testing and tried connecting local docker es data node to it. still no luck.
I also notice in logs that my seed_host was converted to an IP address which i cannot access.
I suspect this might be because the azure container apps sits behind its internal load balancer.
Is there any way for the data nodes to connect to master node behind proxy?

What might be the proper way of deploying es to azure container apps?

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by Kiryuumaru** [comment]
I already asked the forum last week..

**Comment by DaveCTurner** [comment]
Sorry, we do our best but can't guarantee a timely response to all questions there. That doesn't change my guidance tho, this isn't the right place to ask your question.
