### ISSUE TITLE
Update Rally logs track to use new `logs` index mode

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#107222]
### Description

After introducing the new index mode `logs` we would like to update the Rally `elastic\logs` track to include indexing, storage usage and query latency tests. The idea is to have the new track and its challenges ready soon after introducing the new index mode so to be able to see improvements  or, eventually, regressions as soon as we introduce new features. We should rely as much as possible on default settings which are settings we identified to represent typical scenarios. We need to udpate dashboards too so that we are able to spot differences by looking at graphs.

**Comment by martijnvg** [comment]
Maybe additionally the http_logs can be modified to have an additional challenge for the new index mode?
