### ISSUE TITLE
`knn` query hits cache, but actually doesn't cache knn search

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#107264]
### Elasticsearch Version

8.14

### Java Version

_bundled_

### OS Version

_any_

### Problem Description

When using knn as a query, it will hit cache, but it will not improve search response time.

NOTE: Cache isn't supported for DFS. Meaning cache isn't supported for top-level knn.

### Steps to Reproduce

```
DELETE my_vectors
PUT my_vectors
{
  "mappings": {
    "properties": {
      "vectors": {
        "type": "dense_vector"
      }
    }
  }
}

POST my_vectors/_doc
{
  "vectors": [1,3,4]
}


POST my_vectors/_search?request_cache=true
{
  "query" {
  "knn": {
    "query_vector": [1,1,1],
    "num_candidates": 100,
    "field": "vectors"
  }}
}
```

Then call `GET my_vectors/_stats` and note how the `request_cache` is has cache. But, the response time isn't improved.

**Comment by jpountz** [comment]
This may be expected. The top-level `knn` section returns global top vectors, so the top vectors for a shard depend on what other shards that participate in the same request have, and you can't really cache shard responses? I would expect us to do the same when queries use global term statistics.

**Comment by benwtrent** [comment]
@jpountz you are absolutely correct, request cache is completely disable for DFS. But I was wrong about this work for knn query. I need to double check, but it seems like we only cache after rewrite, which means knn query will not get cached correctly.

**Comment by benwtrent** [comment]
Well, I am not 100% sure, looking at how the cache works, it should work before we rewrite in query_then_fetch. 

Maybe my rally is not measuring things correctly, but I don't detect any difference between cache vs. non cached.

**Comment by benwtrent** [comment]
OK, it was a bug in my rally set up. We do in fact cache `query:{knn:{..}}` without issue when `request_cache` is provided in the URL. 

My favorite kind of bug, one where I was just testing wrong :)
