### ISSUE TITLE
[ES|QL] generate function docs and definitions for operators

### ISSUE THREAD

**Issue by drewdaemon** [elastic/elasticsearch#107220]
### Description

With https://github.com/elastic/elasticsearch/pull/106782, we will get function definitions for eval functions. We'd also like them for operators.

**Comment by drewdaemon** [comment]
@nik9000 not that I know of!

**Comment by nik9000** [comment]
@fang-xing-esql did this today! #https://github.com/elastic/elasticsearch/pull/108749

**Comment by fang-xing-esql** [comment]
> @fang-xing-esql did this today! ##108749

Yeah, Kibana docs are added for operators in this PR. Let us know if it is sufficient or need anything else @drewdaemon .

**Comment by drewdaemon** [comment]
You are heroes! I will pull these into our validator soon. That will be the point when I will be able to provide feedback, but that can take the form of further issues. Very excited about this!
