### ISSUE TITLE
Index sorting and nested fields

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#107349]
### Description

In Elasticsearch index sorting does not work if nested fields are used. This Elasticsearch limitation derives from a Lucene limitation [which has been fixed recently](https://github.com/apache/lucene/pull/12829). We currently use index sorting for time series indices but plan to use it for logs too.

Note that at the moment nested fields are also not supported in synthetic source but we plan to address this limitation in #106460.

The limitation behind using index sorting and nested fields is a result of the fact that nested documents need to be written contiguously to their parent document inside the Lucene segment to make sure that the parent/child relationship is correctly mantained. Index sorting used to break this relationship in Lucene ,since sorting of parent documents was missing the logic to move nested document next to the linked parent document. This has been fixed recently so we need to make sure we make use of the Lucene functionality so that we can remove the limitation in Elasticsearch too. Failing to support nested fields while index sorting is used might make using the new "logs" index mode not possible, since `nested` fields are used by a few integrations indexing logs in logs-\*-\* data streams.

After reading the description of the Lucene fix it looks like the parent child relationship in Lucene is accomplished by using a (common) numeric value which is stored using numeric doc values. As a result, taking advantage of this feature in Lucene might require we change our implementation of nested fields to use numeric doc values too.

**Comment by jpountz** [comment]
>  As a result, taking advantage of this feature in Lucene might require we change our implementation of nested fields to use numeric doc values too.

FWIW I would not change the way that we implement nested fields. I would just configure a new special parent field via `IndexWriterConfig#setParentField`, and still index/search nested fields the way we have always indexed them. This would result in a bit of duplication as there would be 2 ways of identifying root documents, but I would not consider this a blocker.
