### ISSUE TITLE
Deprecate + Remove More Like This API

### ISSUE THREAD

**Issue by kimchy** [elastic/elasticsearch#10736]
This API always caused more pain then use based on my experience. It tries to help out, and automatically fetch the fields from a doc and build a search request with MLT query in it, but almost always, the situation is more complicated than that (more complex search request, munging the source, no source / stored fields, ...), and the API ends up being misleading.

I think with the MLT query we have the right foundation for (certain type of) more like this functionality. And the user can "get" a document and more easily decide (with the use case in mind) how to build the best search request (which include the MLT query).

Also, I haven't seen in practice many users using the MLT API itself, and the ones I helped, we almost always ended up going for "get" + MLT Query for the flexibility it has.

So, I suggest we deprecate it in 1.6, and remove it in 2.0, thoughts?

**Comment by s1monw** [comment]
> So, I suggest we deprecate it in 1.6, and remove it in 2.0, thoughts?

+1

**Comment by clintongormley** [comment]
+1

**Comment by alexksikes** [comment]
+1 I agree the MLT API is cumbersome and should be replaced with the query. However, the API is still more efficient because the document is fetched only once, and not on every shard. As soon as we have #10217 in place we can fully remove it. +1 to deprecate it in 1.6.
