### ISSUE TITLE
Multiple timeouts/requests taking too long

### ISSUE THREAD

**Issue by joaooo** [elastic/elasticsearch#107374]
**Elastic.Clients.Elasticsearch version**:
8.12.0
**Elasticsearch version**:
8.x.x
**.NET runtime version**:
8

**Description of the problem including expected versus actual behavior**:
When submitted to loading tests (let's say arround 30000-40000 per minute) elasticsearch v8 starts originating timeouts or taking too long to reply (up to 80seconds easily with those values)

this is the query im doing:
`{
  "from": 0,
  "query": {
    "bool": {
      "must": [
        {
          "nested": {
            "path": "productVariants.productVariantOfferPrices.offerPrice",
            "query": {
              "range": {
                "productVariants.productVariantOfferPrices.offerPrice.validFrom": {
                  "lte": "2024-03-25T09:10:39"
                }
              }
            }
          }
        },
        {
          "nested": {
            "path": "productVariants.productVariantOfferPrices.offerPrice",
            "query": {
              "range": {
                "productVariants.productVariantOfferPrices.offerPrice.validTo": {
                  "gte": "2024-03-25T09:10:39"
                }
              }
            }
          }
        },
        {
          "nested": {
            "path": "storeFront",
            "query": {
              "term": {
                "storeFront.searchUrls": {
                  "case_insensitive": true,
                  "value": "mytest"
                }
              }
            }
          }
        }
      ]
    }
  },
  "size": 20,
  "sort": [
    {
      "relevance": {
        "nested": {},
        "order": "desc"
      }
    }
  ]
}`

I have arround 91045 documents (a lot of nested) and im paginating my results per 20. I can't get rid of the nested due to company reasons. There isnt that many information regarding how nested performance is penalized, here are a few questions to make me understand the situation better:
- Combining two nested queries into one (like i could do), would provide better performance or elasticsearch is able to do that under the hood?
- Besides using Filters to try to improve the performance (without removing the nested) is there anything else i could do?

**Comment by flobernd** [comment]
Hi @joaooo, this is related to the Elasticsearch server and not the .NET client. We will most likely require further information about your cluster in order to help you.

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
