### ISSUE TITLE
Bug reported to be fixed 2 years ago may not be. I don't have the right to re-open my issue.

### ISSUE THREAD

**Issue by Mrodent** [elastic/elasticsearch#107339]
### Elasticsearch Version

8.13.1.

### Java Version

_bundled_

### OS Version

W10

### Problem Description

**Closed issue appears to need re-opening. Although author of it, I don't have the right to re-open:**

 Possible problem with Fast Vector Highlighter + Multi-Fields between 7.10.2 and 7.16.3 issue [#84690](https://github.com/elastic/elasticsearch/issues/84690) 

### Steps to Reproduce

see referenced issue, my post of just now.

**Comment by Mrodent** [comment]
After studying the docs I can see how this is in fact done. There is indeed a slight tweak to the grammar needed (I am updating the original thread...)

**Comment by Mrodent** [comment]
Closed and then re-opened... in fact I find that there is, even after the grammatical modification (inclusion of "matched_fields" field) I still find that there is a limitation: I find that I can only seemingly have a maximum of 4 "pre-tag" (and matching "post-tag") fields. See details in [my last comment](https://github.com/elastic/elasticsearch/issues/84690#issuecomment-2049130582) in the other issue thread.

**Comment by DaveCTurner** [comment]
Sorry it's almost impossible to handle this as, effectively, a diff on top of an older issue that was resolved. If you think there's an issue in this area still, please open a fresh bug report describing the remaining problem and including relevant reproduction steps.
