### ISSUE TITLE
/_cluster/enrollment_token endpoint does not work

### ISSUE THREAD

**Issue by prashanthbgoud** [elastic/elasticsearch#107342]
### Elasticsearch Version

8.13.2

### Java Version

_bundled_

### OS Version

Linux ip-xxx.xxx 5.15.0-1056-aws #61~20.04.1-Ubuntu SMP Wed Mar 13 17:45:04 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

### Problem Description

as per the discussion https://github.com/elastic/elasticsearch/issues/71438

request `curl -uelastic:password -X 'Content-Type: application/json' -XPOST  https://xx.xx.xx.xx/_cluster/enrollment_token`

should give response
```
{ "enrollment_token":"eyJhZHIiOiIxOTIuMTY4LjEuNDM6OTIwMSIsImZnciI6IjQ4OkNDOjZDOkY4Ojc2OjQzOjNDOjk3Ojg1OkI2OjI0OjQ1OjVCOkZGOkJEOjQwOjRCOkQ2OjM1OjgxOjUxOkU3OkE5Ojk5OjYwOkU0OjBBOkM4OjhEOkFFOjVDOjREIiwia2V5IjoiVnVhQ2ZHY0JDZGJrUW0tZTVhT3g6dWkybHAyYXhUTm1zeWFrdzl0dk5udyJ9Cg==" }
```

I see this is not working, see below for error. I have a requirement of generating token from outside the elasticsearch instance.

```
root@xyz-1.development:~$ curl -k -uelastic:xxxx -X 'Content-Type: application/json' -XPOST  https://xx.xx.xx.xx:9200/_cluster/enrollment_token
{"error":"no handler found for uri [/_cluster/enrollment_token] and method [POST]"}
```

### Steps to Reproduce

run `curl -uelastic:password -X 'Content-Type: application/json' -XPOST  https://xx.xx.xx.xx/_cluster/enrollment_token`

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

Specifically, there's nothing in the [reference manual](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html) to indicate that your expectations about this API are accurate.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by prashanthbgoud** [comment]
> Specifically, there's nothing in the [reference manual](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html) to indicate that your expectations about this API are accurate.
>  @DaveCTurner Please check the discussion [here](https://github.com/elastic/elasticsearch/issues/71438)

**Comment by DaveCTurner** [comment]
This isn't the right place for user questions. Please ask your question on the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead.
