### ISSUE TITLE
Limiting search depth in documents on per request basis failing due to unintended date conversion

### ISSUE THREAD

**Issue by OmarHawk** [elastic/elasticsearch#107309]
### Elasticsearch Version

8.11.3

### Java Version

_bundled_

### OS Version

Kubernetes operator

### Problem Description

We have an index that contains fields with different types, like String or Date. Our index data is quite deeply nested - more than 4 levels, as we are using Spring Data Elasticsearch to push relational data with foreign key relationships into the index. Having all these data in the index itself is quite alright for us, as it gives us the flexibility to also search for deeply related object information. In some use cases, we actually need that and limiting the content during indexing time is not an option. 

But for the standard full text search (query_string), this produces search results that no end user understands, why they are returned. This is because certain related entities contain quite generic words in their values making them look like false positive findings.

Therefore, our idea was to to limit the search depth within documents to only find something up to a certain depth level (like level 2 or 3): 

### Steps to Reproduce

We tried to pass in the fields parameter like the following for a search for the String "ok", so it just searches up to level two (note it does *not* happen with a single wildcard `["*"]` or leaving that parameter completely away, but it does happen, if I try to directly address all fields of a nested entity: `["sourceidUsecaseid.*"]`

POST: http://localhost:9200/streamdata/_search?pretty
```
{
    "profile": true,
    "query": {
        "query_string": {
            "query": "\"ok\" || /.*[oO][kK].*/",
            "fields": ["*.*"]
        }
    },
    "sort" : [
    { "date" : {"order" : "desc"}},
    "_score"
  ]
}
```

This produces an error like this:

```
{
    "error": {
        "root_cause": [
            {
                "type": "parse_exception",
                "reason": "failed to parse date field [ok] with format [strict_date_optional_time||epoch_millis]: [failed to parse date field [ok] with format [strict_date_optional_time||epoch_millis]]"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "streamdata",
                "node": "WcGkOYBKQ1iUmrlyH6BLpw",
                "reason": {
                    "type": "query_shard_exception",
                    "reason": "failed to create query: failed to parse date field [ok] with format [strict_date_optional_time||epoch_millis]: [failed to parse date field [ok] with format [strict_date_optional_time||epoch_millis]]",
                    "index_uuid": "Z8PIcaNOTtCEVNm8LwezkQ",
                    "index": "streamdata",
                    "caused_by": {
                        "type": "parse_exception",
                        "reason": "failed to parse date field [ok] with format [strict_date_optional_time||epoch_millis]: [failed to parse date field [ok] with format [strict_date_optional_time||epoch_millis]]",
                        "caused_by": {
                            "type": "illegal_argument_exception",
                            "reason": "failed to parse date field [ok] with format [strict_date_optional_time||epoch_millis]",
                            "caused_by": {
                                "type": "date_time_parse_exception",
                                "reason": "date_time_parse_exception: Failed to parse with all enclosed parsers"
                            }
                        }
                    }
                }
            }
        ],
        "caused_by": {
            "type": "parse_exception",
            "reason": "failed to parse date field [ok] with format [strict_date_optional_time||epoch_millis]: [failed to parse date field [ok] with format [strict_date_optional_time||epoch_millis]]",
            "caused_by": {
                "type": "illegal_argument_exception",
                "reason": "failed to parse date field [ok] with format [strict_date_optional_time||epoch_millis]",
                "caused_by": {
                    "type": "date_time_parse_exception",
                    "reason": "date_time_parse_exception: Failed to parse with all enclosed parsers"
                }
            }
        }
    },
    "status": 400
}
```

Seemingly, the date fields that are behind the nested object(s) make ES try to convert my search string into a date and running into a failure. If I'd leave the exact match part of my query away from it, like this:

```
{
    "profile": true,
    "query": {
        "query_string": {
            "query": "/.*[oO][kK].*/",
            "fields": ["*.*"]
        }
    },
    "sort" : [
    { "date" : {"order" : "desc"}},
    "_score"
  ]
}
```

It will even print out a more detailed result:

```
{
    "error": {
        "root_cause": [
            {
                "type": "query_shard_exception",
                "reason": "Can only use regexp queries on keyword and text fields - not on [routeridRouter.usecaseid.createdDate] which is of type [date]",
                "index_uuid": "Z8PIcaNOTtCEVNm8LwezkQ",
                "index": "streamdata"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "streamdata",
                "node": "WcGkOYBKQ1iUmrlyH6BLpw",
                "reason": {
                    "type": "query_shard_exception",
                    "reason": "Can only use regexp queries on keyword and text fields - not on [routeridRouter.usecaseid.createdDate] which is of type [date]",
                    "index_uuid": "Z8PIcaNOTtCEVNm8LwezkQ",
                    "index": "streamdata"
                }
            }
        ]
    },
    "status": 400
}
```

**Comment by OmarHawk** [comment]
Maybe, this can be handled like the "search all" case, i.e. just don't search the fields, where a conversion cannot be done - instead of running into an error. At the moment, this behaviour is a bit inconsistent to me.

**Comment by OmarHawk** [comment]
Ok, setting `"lenient": true` suppresses the errors
```
{
    "profile": true,
    "query": {
        "query_string": {
            "query": "/.*[oO][kK].*/",
            "fields": ["*.*"],
            "lenient": true
        }
    },
    "sort" : [
    { "date" : {"order" : "desc"}},
    "_score"
  ]
}
```

**Comment by cbuescher** [comment]
Hi @OmarHawk, reading through this issue it seems to me that the error you are seeing is intentional and your diagnosis is correct:

> Seemingly, the date fields that are behind the nested object(s) make ES try to convert my search string into a date and running into a failure.

However this isn't a bug but something but an intended usage error. So I'm closing this issue and would like to recommend using the support forums over at [discuss.elastic.co](https://discuss.elastic.co/) for other suggestions on how you can solve your use case.
