### ISSUE TITLE
[Security] Enhancing Permissions for System Indices

### ISSUE THREAD

**Issue by Harmlos** [elastic/elasticsearch#107366]
### Description

**Description:**

It is necessary to implement the capability to grant access to system indices with rights limited to read, search or monitoring, excluding the ability to modify them. This access should be available both for local users viewing dashboards and for external users processing data in external systems.

**Why the enhancement is needed:**

There's a need to create a role that allows viewing specific system indexes with read-only rights. Meanwhile, access to system indexes is required for collecting various statistics, building dashboards with data from non-default system indexes, tracking agent coverage and installation status on hosts, enriching data in CMDB, building dashboards displaying rule operations and exceptions in a more visually intuitive way, and so forth.

Creating system accounts with full rights is undesirable, and based on the description, even that option won't work shortly.

Using transform partially solves the problem but introduces significant lag between updating data in the user index based on system data. Additionally, the implementation becomes burdensome and adds extra links in the system.

While some data is available via API, it's necessary not only to export data to another system but also to create dashboards to expand existing views.

**Comment by jakelandis** [comment]
You shouldn't need direct access to system indices except possibly for ad-hoc troubleshooting. I would suggest to identify which workflows require direct access to system indices and file enhancement requests to provide explicit API's to read that data in the context of your workflow. The goal of system indices is to eventually prohibit direct access entirely, hence the warning while reading:

> #! this request accesses system indices: [index-name], but in a future major version, direct access to system indices will be prevented by default

That said ... what you describe here (IIUC) is already possible with a role that looks like (using .enrich as the example of a system index): 
```
POST _security/role/test1
{
  "indices": [
    {
      "names": [
        ".enrich*"
      ],
      "privileges": [
        "read"
      ],
      "allow_restricted_indices": true
    }
  ]
}
```
^ will give read only access that system index. You can see this with:
```
GET _security/user/_has_privileges
{
  "index": [
    {
      "names": [
        ".enrich-something"
      ],
      "privileges": [
        "read"
      ]
    },
    {
      "names": [
        ".enrich-something"
      ],
      "privileges": [
        "write"
      ]
    }
  ]
}
```
which (when run with a user that only has that role) results in
```
{
  "username": "memyselfandi",
  "has_all_requested": false,
  "cluster": {},
  "index": {
    ".enrich-something": {
      "read": true,
      "write": false
    }
  },
  "application": {}
}
```

However, as mentioned, this may not work in a future major version (we won't make that change in a minor) and would suggest to move away from the need to read system indices directly sooner than later. I will close this enhancement request but feel free to re-open if I missed something.
