### ISSUE TITLE
escaping appears to turn off fuzzy matching and wildcards

### ISSUE THREAD

**Issue by apolishch** [elastic/elasticsearch#10733]
I've got the folllowing query

'query': {
          'query_string': {
            'fields': ['*.searchable', 'name', 'account.name', 'subject'],
            'escape': true,
            'query': query
          }
        }

Using the (very poorly documented I might add) escape feature: https://github.com/elastic/elasticsearch/issues/41

This appears to turn of wild cards and fuzzy search, e.g.: searching for:
exp~+exp*

Does NOT return expansion.

Is this by design? If so, is there any way to escape characters, while still maintaining the Query DSL functionality?

This is desirable in case a customer wanted to search for say a string containing AND~

**Comment by clintongormley** [comment]
@apolishch heh I didn't even know about the `escape` option, even though I apparently commented on that issue :)

Setting `escape` to true seems to defeat the point of using the `query_string` query.  Rather use the `match` query for these cases.

That said, you can escape individual special chars with `\`, eg:

    PUT test
    {
      "mappings": {
        "test": {
          "properties": {
            "text": {
              "type": "string",
              "analyzer": "whitespace"
            }
          }
        }
      }
    }
    
    PUT test/test/1
    {
      "text": "This AND~ that"
    }
    
    GET _search
    {
      "query": {
        "query_string": {
          "default_field": "text",
          "query": "AND\\~"
        }
      }
    }
