### ISSUE TITLE
Index template with data streaming enabled, appended with a life cycle with deletion, subsequent indexes will become unwritable

### ISSUE THREAD

**Issue by nutsplay** [elastic/elasticsearch#107456]
### Elasticsearch Version

8.8.1

### Java Version

unknown

### OS Version

unknown

### Problem Description

Index template with data streaming enabled, appended with a life cycle with deletion, subsequent indexes will become unwritable

### Steps to Reproduce

Three indexes a-xxxx.xx.xx, b-xxxx.xx.xx, c-xxxx.xx.xx
Three index templates a, b, and c were created and data stream was enabled.
Create a life cycle policy to delete indexes older than 14 days and attach them to a, b, and c
All subsequent indexes will be unwritable.
logstash logs "Could not index event to Elasticsearch a-xxxx.xx.xx "reason"=>"no such index [a-xxxx.xx.xx]"
Try to create the index manually PUT /a-xxxx.xx.xx reson:cannot create index with name [a-xxxx.xx.xx], because it matches with template [a-xxxx.xx.xx] that creates data streams only, use create data stream api instead

**Comment by nutsplay** [comment]
At the same time, I cannot delete the three index templates a, b, and c no matter what.

**Comment by nielsbauman** [comment]
Hi @nutsplay, thank you for taking the time to open this issue. Although the steps you provided give me some idea of what you're trying to do, I haven't been able to reproduce this myself. Could you provide the HTTP requests you're sending to Elasticsearch please? Then we can try to reproduce and help you solve this.

**Comment by nielsbauman** [comment]
Hi @nutsplay, we haven't heard back in a while, so I hope you don't mind me closing this issue. Feel free to reopen this if you still feel like this is an issue. Please include some steps for us to reproduce when you do.
