### ISSUE TITLE
Get term aggregation based on doc count

### ISSUE THREAD

**Issue by dobariya** [elastic/elasticsearch#10747]
Is it possible get term aggregation where doc count is 1 or according to the specified thresh hold

**Comment by clintongormley** [comment]
You can sort by doc count ascending:

    {
      "aggs": {
        "fewest_docs": {
          "terms": {
            "field": "foo",
            "order": {
              "_count": "asc"
            }
          }
        }
      }
    }

And when https://github.com/elastic/elasticsearch/issues/9876 is in, you'll be able to remove anything with higher doc counts.
