### ISSUE TITLE
[Feature Request] Include Query Source Attribution in RRF Ranking Results

### ISSUE THREAD

**Issue by Rassyan** [elastic/elasticsearch#107448]
### Description

The introduction of the `rank` feature with `rrf` (Reciprocal Rank Fusion) in Elasticsearch 8.x has been a significant advancement for combining results from multiple queries. However, in its current preview state, the feature does not provide visibility into the source of each document's retrieval—whether it was from a vector search or a text search. This information is essential for in-depth query analysis and optimization.

### Feature Request

This issue proposes an enhancement to the `rank`/`rrf` feature to optionally include the attribution of each document's retrieval source. The ability to identify whether a document was retrieved by a specific query type (text or vector) would greatly assist in fine-tuning search strategies and understanding their individual effectiveness.

### Use Case

In complex search scenarios where multiple query types are used, it is beneficial to analyze the performance and relevance contribution of each individual query. This analysis is hindered without the knowledge of the retrieval source for each document in the fused result set.

### Suggested Implementation

A possible implementation could involve an additional parameter within the `rank`/`rrf` DSL that, when enabled, annotates each result with its originating query type. For instance:

```json
"rank": {
  "rrf": {
    "window_size": 5,
    "rank_constant": 1,
    "annotate_source": true
  }
}
```

The response could then include a field indicating the source of retrieval for each document, such as `"retrieval_source": ["standard"]` or `"retrieval_source": ["knn"]`.

### Benefits

- **Enhanced Analysis**: Provides essential insights for query performance analysis and optimization.
- **Customization**: As an optional feature, it maintains the current functionality for users who do not require this level of detail.
- **Community Collaboration**: Opens a discussion for further refinement and ensures the feature aligns with Elasticsearch's vision for search capabilities.

### Conclusion

Incorporating retrieval source attribution into the RRF ranking process would be a valuable enhancement for Elasticsearch users who require detailed analysis of their search strategies. It would promote a deeper understanding of the search results and facilitate more effective query tuning.

Should the community find this proposal viable, I am open to contributing to the code implementation for this feature.

Thank you for considering this enhancement.

**Comment by benwtrent** [comment]
@Rassyan does adding query `_name` to the individual queries that are being merged not show which queries matched? I think continuing to lean on `_name` for the query objects is the way to do this, maybe not a new idea in RRF itself.

**Comment by Rassyan** [comment]
@benwtrent 
Thank you for your suggestion to leverage named queries (`_name`) for identifying the contributing queries in merged results. This approach works well with standard text queries, providing clear identification in the results. However, I have encountered an issue when applying the `_name` attribute to `knn` queries, as it appears to be unsupported:

```
{ 
  "error": { 
    "root_cause": [ 
      { 
        "type": "x_content_parse_exception",
        "reason": "[1:61] [knn] unknown field [_name]"
      }
    ],
    "type": "x_content_parse_exception",
    "reason": "[1:61] [knn] unknown field [_name]"
  },
  "status": 400
}
```

In light of this, I would like to inquire about the possibility of extending the `_name` functionality to `knn` queries to maintain consistency across query types.

Furthermore, I have an additional requirement that extends beyond the identification of query sources. For the purpose of query tuning and performance analysis, it would be highly beneficial to understand the individual scores contributed by each query in a multi-query retrieval scenario. This level of detail is particularly relevant when using the `rrf` (Reciprocal Rank Fusion) feature, where understanding the individual scores that contribute to the final fused score can provide valuable insights for optimization.

The `_name` attribute, while useful for source identification, does not provide information on the scoring contributions of each query. Therefore, I am seeking guidance on whether there is a mechanism within the current `rrf` implementation that could expose these individual scores, or if there is potential for such a feature to be developed.

The ability to analyze the score contributions from each retrieval source would be a significant enhancement for those of us looking to fine-tune our search strategies and improve the relevance of our search results.

I appreciate your consideration of these points and look forward to any insights you may have. Should there be interest in pursuing these enhancements, I am ready and willing to contribute to the development efforts.

**Comment by styrmis** [comment]
@Rassyan The `_name` attribute is supported on `knn` [when it is inside a `query`](https://www.elastic.co/guide/en/elasticsearch/reference/8.13/query-dsl-knn-query.html#knn-query-top-level-parameters), but does not appear to be supported currently on the top-level `knn` object—theres is an issue (#106254) open for this.

I agree that it would be very valuable to be able to profile the retrieval sources for results and their relative contributions with RRF and KNN.

**Comment by Rassyan** [comment]
@benwtrent 

I've submitted a PR (#107645) that addresses the `_name` support for kNN queries as discussed in this issue. This should resolve the first part of the issue we've been tackling.

Regarding the "help make rrf more explainable" mentioned in the latter part of this issue, could you provide some insights on how we might approach this? If it's substantial, we might consider keeping this issue open for that discussion or opening a new one specifically for that purpose.

Looking forward to your review and thoughts.

**Comment by benwtrent** [comment]
You can see the attributing queries via query names & `include_named_queries_score` for detailed explaining.

More detailed explaining for RRF has also recently been added (8.15+) indicating position in original sets, etc.
