### ISSUE TITLE
Pagination of percolate results

### ISSUE THREAD

**Issue by robertkern** [elastic/elasticsearch#10741]
It is currently possible to set the "size" option to limit the number of percolate results, but it's not possible to set "from" (so we can paginate through the results).

If a percolate request matches thousands or millions of percolators, it'd be nice to be able to paginate through them rather than process them all in one go. Is this something that has been considered for an upcoming version?

Thanks!

**Comment by jpountz** [comment]
I'm not sure we want to support things like scroll for the percolator, but in general I think it'd be great if it worked in a more similar way to the search API. Maybe some refactoring happening on #13646 are going to help in that regard.
