### ISSUE TITLE
TSDB rollover logs should default to Debug

### ISSUE THREAD

**Issue by StephanErb** [elastic/elasticsearch#107473]
### Description

We have adopted TSDB widely. One of the most common log messages are these TSDB logs:

> [elasticsearch.server][INFO] [.ds-metrics-prometheus.collector-default-2024.04.03-000867] updating [index.time_series.end_time] from [2024-04-04T08:03:44.000Z] to [2024-04-04T08:08:43.000Z]

They don't really add much value from an end-user perspective. I thus believe those should be logged at debug level only.

**Comment by martijnvg** [comment]
Yes, I agree this should be changed.

Unfortunately this isn't just changing the log level of a log statement.
This logger belong to settings infrastructure and is essentially logged
every time a dynamic settings gets updated. I think this log statement
should stay at the info level. However in the case of the
`index.time_series.start_time` and `index.time_series.end_time` settings
the log level should be lowered to debug.
