### ISSUE TITLE
Get one to one match in aggregation 

### ISSUE THREAD

**Issue by dobariya** [elastic/elasticsearch#10748]
I am storing sms communication in elastic search for sender and receiver

Can we implement searching for sender to only one reciever

Case: A send sms  to B
Case: A send sms  to B, C, D

I only want one to one so if I search only included A to B than only give me first case a result. How to exclude second case when I need to one to one exact.

**Comment by clintongormley** [comment]
Hi @dobariya 

Please ask questions like these on the mailing list.  The GitHub issues list is for bug reports and feature requests.  I'd suggest indexing the number of receivers, and adding that condition to the query.
