### ISSUE TITLE
Score value is 0 in _explanation with random_score query

### ISSUE THREAD

**Issue by marevol** [elastic/elasticsearch#10742]
Sending random_score function query with explain=true to Elasticsearch 1.5.1, the value is always 0 in _explanation as below.

    ...
                  {
                     "value": 0,
                     "description": "Math.min of",
                     "details": [
                        {
                           "value": 0,
                           "description": "product of:",
                           "details": [
                              {
                                 "value": 0,
                                 "description": "random score function (seed: 49)"
                              },
                              {
                                 "value": 1,
                                 "description": "weight"
                              }
                           ]
                        },
                        {
                           "value": 3.4028235e+38,
                           "description": "maxBoost"
                        }
                     ]
                  },
    ...

I looked into RandomScoreFunction class. 
I think that exp.setValue(CombineFunction.toFloat(score(docId, subQueryScore.getValue()))) needs to be call in explainScore method.

**Comment by rjernst** [comment]
I think this was actually fixed today as part of upgrading our lucene snapshot in master:
https://github.com/elastic/elasticsearch/pull/10727/files#diff-8

So this is already fixed in 2.0.  I will backport the fix 1.x.
