### ISSUE TITLE
Missing documentation for http.max_header_size

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#10752]
I'd expect to see documentation for ```http.max_header_size``` [here]( http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html), but I don't....

**Comment by clintongormley** [comment]
@robin13 why not send a PR ;)

**Comment by robin13** [comment]
Discovered this parameter being used by a user who had huge http headers (110kb), and had already set ```htttp.max_header_size: 100kb```
I was not able to identify why/how the customer was creating such huge headers.
