### ISSUE TITLE
Range Aggregation: no way to set "keyed": true with the Java API

### ISSUE THREAD

**Issue by bradvido** [elastic/elasticsearch#10757]
According to [the v1.4 documentation](http://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-aggregations-bucket-range-aggregation.html#_keyed_response), the range aggregation has a `keyed` parameter that can be set to `true` to indicate the aggregation should use unique keys like "0-100" and return the results in a map instead of an array.

However, I cannot find any way to set the `keyed` boolean flag with the Java API (1.4). There is a method to manually specify the key name when you add a range `RangeBuilder.addRange(String key, double from, double to) `, but no apparent way to have ES auto-create the keys as the documentation suggests.

Also, the docs first mention a `key` flag, but in the JSON sample it's labeled as `keyed`

**Comment by clintongormley** [comment]
@colings86 any ideas?

**Comment by colings86** [comment]
@bradvido In the Java API you are returned a Range object which holds the buckets. in version 1.4 there is a method `getBuckets()` which will return you a `List` of buckets (equivalent of giving you an array) and a method `getBucketByKey(String)` (equivalent to map lookups) which will return you a specific bucket given a string key. The `keyed` parameter is not available in the Java API as it would have no affect. Regardless of whether `keyed` is set to `true` or `false` the same object would be returned and those methods would still be available. The purpose of the `keyed` method is to allow clients which deal directly with the JSON response to specify the structure of the JSON. The Java API does not deal with the JSON response but directly with the response objects created in the aggregation.

**Comment by clintongormley** [comment]
thanks @colings86 - closing
