### ISSUE TITLE
[ML] Inference API upgrade tests

### ISSUE THREAD

**Issue by jonathan-buttner** [elastic/elasticsearch#107590]
### Description

The inference API needs upgrade tests to catch issues with node shutting down and running a multi versioned cluster.

A cluster with different node versions could illuminate issues with serialization.

We should add testing scenarios to exercise these code paths.

**Comment by maxhniebergall** [comment]
Will these tests catch NamedWritable errors?

**Comment by maxhniebergall** [comment]
I think this issue is complete, no? Although it seems like we need to look at the community PR linked above

**Comment by jonathan-buttner** [comment]
Yeah you're right we can close this. I'm not sure why I mentioned nodes shutting down in this issue 🤔 We do need tests for shutting down nodes while performing inference but we have a different issue for that. I'm going to close this and we can address the shutdown tests in a different issue.
