### ISSUE TITLE
Nested query returns no result when nested object has the same field name as parent

### ISSUE THREAD

**Issue by agliznetsov** [elastic/elasticsearch#10753]
1. create index with nested mappings:

{
   "mappings": {
      "movie": {
         "properties": {
            "cast": {
               "type": "nested"
            }
         }
      }
   }
}

2. post a document:

{
   "title": "The Matrix",
   "cast": [
      {
         "title": "test"
      }
   ]
}

3. search nested:

{
   "query": {
      "filtered": {
         "query": {
            "match_all": {}
         },
         "filter": {
            "nested": {
               "path": "cast",
               "filter": {
                  "term": {
                     "title": "test"
                  }
               }
            }
         }
      }
   }
}

no result found -> bug

It works if nested object uses different field name rather then 'title'

**Comment by rjernst** [comment]
I don't think this has anything to do with the field names being the same, since the type of both are `string`. I believe this is related to #8872. Can you change your term query to use `cast.title` as the field and see if it works?

**Comment by agliznetsov** [comment]
Indeed it works with "cast.title". Does it mean that a full path must be used in the term despite the fact that there's also a path specified one level higher?

**Comment by clintongormley** [comment]
@agliznetsov yes that is the case with nested clauses.  In fact, in 2.0 it will be the case for ALL fields.  See #8070
