### ISSUE TITLE
Publish signed jar files to maven

### ISSUE THREAD

**Issue by alexanderkjall** [elastic/elasticsearch#10758]
The jar files provided on maven doesn't have a pgp signature provided with them.

This makes it hard to verify the authenticity of the packages that we download.

**Comment by clintongormley** [comment]
@dadoonet what do you think?

**Comment by dadoonet** [comment]
I need to think a bit more about it and run some tests. A first thought is that now we have  f733fda55e0a49ffc3e96e3e691ddaf4bb12b615 merged in, we can support it now without breaking our release script.

I mean that IIRC, maven gpg plugin ask you explicitly for a passphrase.
We can probably set gpg plugin to use the new `GPG_KEY_ID`, `GPG_PASSPHRASE`, optionally `GPG_KEYRING` @spinscale created.

Will try it.

**Comment by jpountz** [comment]
This seems to be fixed in master.

**Comment by alexanderkjall** [comment]
Verified that the latest version have .asc files in maven central. Big thanks to everyone involved.

**Comment by s1monw** [comment]
w00t!! @alexanderkjall thanks for raising this in the first place
