### ISSUE TITLE
Lingering license warning response headers

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#107573]
### Elasticsearch Version

8.9 and up

### Java Version

_bundled_

### OS Version

any

### Problem Description

Response headers such as `Warning: 299 Elasticsearch-8.* "Your license will expire in [6] days. Contact your administrator or update your license for continued use of features"` continue to be returned even though the license has been successfully [updated](https://www.elastic.co/guide/en/elasticsearch/reference/current/update-license.html).
Moreover, multiple such warnings might be returned for different countdowns.

In case, following a license update, no **new** warnings are returned (but the existing ones continue to show up), licensed functionality should not be impacted come the deadline.

### Steps to Reproduce

Authentication **and** auditing need to be enabled.
The license needs to expire 7 days from the current time.
Uploading a new license doesn't make the existing response warnings go away.

**Comment by albertzaharovits** [comment]
The cause is that the http worker's thread context gets populated with the license warning by auditing in the IP filter here https://github.com/elastic/elasticsearch/blob/eb6af0e6b549d0810d8b89791556bc791b766652/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/transport/filter/IPFilter.java#L334, which is not guarded by the usual "preserve threadcontext inside try-with-resources" https://github.com/elastic/elasticsearch/blob/eb6af0e6b549d0810d8b89791556bc791b766652/modules/transport-netty4/src/main/java/org/elasticsearch/transport/netty4/AcceptChannelHandler.java#L33 , like, for example, authentication (validator) is https://github.com/elastic/elasticsearch/blob/eb6af0e6b549d0810d8b89791556bc791b766652/modules/transport-netty4/src/main/java/org/elasticsearch/http/netty4/Netty4HttpHeaderValidator.java#L138-L140

**Comment by albertzaharovits** [comment]
Thanks @tvernum for aiding with the investigation on this one!

**Comment by DaveCTurner** [comment]
We _should_ be protecting against this kind of thing in the network layers too - can you share a full stack trace to the point where the thread context pollution is happening?

**Comment by albertzaharovits** [comment]
@DaveCTurner 
![Capture d’écran 2024-04-18 à 10 16 35](https://github.com/elastic/elasticsearch/assets/4568420/3e3e5347-86cf-40be-ab62-ba9ef9b3d930)

**Comment by DaveCTurner** [comment]
Ok thanks, yeah I think we have to fix this in the `AcceptChannelHandler` then.

**Comment by albertzaharovits** [comment]
> Ok thanks, yeah I think we have to fix this in the AcceptChannelHandler then.

Thanks for looking into it! Will do!.

**Comment by jcertesio** [comment]
Very much appreciate the attention on this - thank you.
