### ISSUE TITLE
Delete API without without any write

### ISSUE THREAD

**Issue by Soltaniant** [elastic/elasticsearch#107673]
### Description

while using the delete API, either its simple CRUD form, or delete_by_query, it seems that it will write a sample dummy document in the index, keeping its version updated.

Though regarding what Lucene actually does while deleting a document, **we expect elasticsearch not to make any footprint in this process and so do not touch any segment** (creating or even breaking any).

> We are sure, that in the future we will need the version field which is stored currently, and there is no problem if same document with lower version be indexed later ...

What should we do? **is there any way so that deleteing a document from a rollovered index does not affect its performance?**

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

Specifically, I think you're describing the behaviour we'd expect to see, and it's not clear what, if any, action is needed from the ES dev team.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
