### ISSUE TITLE
Unable to locate package openjdk-11-jre-headless 7.17 ubuntu-2004-aarch64

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#107613]
### CI Link

https://gradle-enterprise.elastic.co/s/7nh4jhoqhib7m

### Repro line

./gradlew :test:fixtures:geoip-fixture:composeBuild

### Does it reproduce?

Didn't try

### Applicable branches

7.17

### Failure history

https://gradle-enterprise.elastic.co/scans?search.tags=7.17%2Caarch64%2Cci%2Clinux%2Cplatform-support-arm%2Cubuntu-2004-aarch64&search.timeZoneId=Europe%2FBucharest

### Failure excerpt

This only failed twice but at a 4h interval period, which makes me think it's not transitory.

```
Exit-code 17 when calling /usr/local/bin/docker-compose, stdout: #0 building with "default" instance using docker driver

#1 [geoip-fixture internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 0.0s

#2 [geoip-fixture internal] load build definition from Dockerfile
#2 transferring dockerfile: 354B done
#2 DONE 0.0s

#3 [geoip-fixture internal] load metadata for docker.io/library/ubuntu:18.04
#3 DONE 0.6s

#4 [geoip-fixture 1/3] FROM docker.io/library/ubuntu:18.04@sha256:152dc042452c496007f07ca9127571cb9c29697f42acbfad72324b2bb2e43c98
#4 DONE 0.0s

#5 [geoip-fixture 2/3] RUN apt-get update -qqy
#5 CACHED

#6 [geoip-fixture 3/3] RUN apt-get install -qqy openjdk-11-jre-headless
#6 3.269 E: Unable to locate package openjdk-11-jre-headless
#6 ERROR: process "/bin/sh -c apt-get install -qqy openjdk-11-jre-headless" did not complete successfully: exit code: 100
------
 > [geoip-fixture 3/3] RUN apt-get install -qqy openjdk-11-jre-headless:
3.269 E: Unable to locate package openjdk-11-jre-headless
```

**Comment by mark-vieira** [comment]
I tried this locally and it worked so I don't think it's an issue of the package _actually_ being unavailable. Strange we've had multiple failures in a row here though. Let's keep an eye on this.

**Comment by mark-vieira** [comment]
Looks to be passing now. Closing.
