### ISSUE TITLE
Hanging threads with TransportClient

### ISSUE THREAD

**Issue by nilsga** [elastic/elasticsearch#10766]
We have had some instability issues with our ES cluster lately, where our application using the Java TransportClient stops responding to requests towards the cluster. Our setup consists of 3 master nodes and 4 data nodes, and our application consists of 5 nodes. The symptoms we are experiencing is that after some time, a situation occurs that freezes most or all ES requests. We have been profiling and digging through thread dumps, and when the freeze occurs we see a lot of these (typically 20+):

```
"AkkaSystem-akka.actor.default-dispatcher-445" - Thread t@540
   java.lang.Thread.State: WAITING
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for <2f9d8510> (a org.elasticsearch.common.util.concurrent.BaseFuture$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:279)
	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:118)
```

The number of these seems to grow steadily but slowly, which might indicate that not all the requests that are coming in are blocked, but maybe certain requests that reach one particular node in the cluster? What is also interesting is that in the freeze situation, there is alway at least one of these threads hanging:

```
"elasticsearch[Quentin Beck][transport_client_worker][T#1]{New I/O worker #1}" - Thread t@34
   java.lang.Thread.State: WAITING
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for <44a58cd8> (a org.elasticsearch.common.util.concurrent.BaseFuture$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:279)
	at org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:118)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:45)
```

So it appears that all our application threads that are blocked are waiting for this single `transport_client` thread to complete. I suspect there are two issues here really. One is that one of the `transport_client` thread is never timed out. And the second is that there seems to be some synchronization going on between all (or many) of the other requests that are blocking on `BaseFuture$Sync`

We are running ES 1.5.0 with OpenJDK 1.8.0_31 on both server and client.

**Comment by nilsga** [comment]
Here's a gist with output from the stats/health endpoints: https://gist.github.com/nilsga/cd1f0f037b43340f7ad0

**Comment by kjbekkelund** [comment]
This just occured again, but now with:

```
{"version":"1.8.0_31","vm_name":"Java HotSpot(TM) 64-Bit Server VM","vm_version":"25.31-b07","vm_vendor":"Oracle Corporation","count":1}
```

This time it ran on localhost with one server connecting to one Elasticsearch node (compared to above with our cluster of 5 nodes connecting to 7 elasticsearch nodes).

I've included a thread dump at https://gist.github.com/kjbekkelund/405580860216d1d69b8f

**Comment by clintongormley** [comment]
Wondering if this is related to https://github.com/elastic/elasticsearch/issues/10704

**Comment by clintongormley** [comment]
@spinscale any thoughts here?

**Comment by nilsga** [comment]
I think we have located the trigger of the problem. The thread dump for the `transport_client` thread was missing some interesting information. This is a more complete stack:

```
 elasticsearch[Magneto][transport_client_worker][T#4]{New I/O worker #4} [WAITING] [DAEMON]
*** java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(int) AbstractQueuedSynchronizer.java:1304
*** org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get() BaseFuture.java:279
*** org.elasticsearch.common.util.concurrent.BaseFuture.get() BaseFuture.java:118
*** org.elasticsearch.action.support.AdapterActionFuture.actionGet() AdapterActionFuture.java:45

<some company specific classes>

*** org.elasticsearch.action.support.AbstractListenableActionFuture.executeListener(ActionListener) AbstractListenableActionFuture.java:120
*** org.elasticsearch.action.support.AbstractListenableActionFuture.done() AbstractListenableActionFuture.java:97
*** org.elasticsearch.common.util.concurrent.BaseFuture.set(Object) BaseFuture.java:167
org.elasticsearch.action.support.AdapterActionFuture.onResponse(Object) AdapterActionFuture.java:96
org.elasticsearch.client.transport.TransportClientNodesService$RetryListener.onResponse(Object) TransportClientNodesService.java:227
org.elasticsearch.action.TransportActionNodeProxy$1.handleResponse(ActionResponse) TransportActionNodeProxy.java:73
org.elasticsearch.action.TransportActionNodeProxy$1.handleResponse(TransportResponse) TransportActionNodeProxy.java:57
org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(Channel, StreamInput, TransportResponseHandler) MessageChannelHandler.java:163
org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(ChannelHandlerContext, MessageEvent) MessageChannelHandler.java:132
org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(ChannelHandlerContext, ChannelEvent) SimpleChannelUpstreamHandler.java:70
org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline$DefaultChannelHandlerContext, ChannelEvent) DefaultChannelPipeline.java:564
org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(ChannelEvent) DefaultChannelPipeline.java:791
org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(ChannelHandlerContext, Object, SocketAddress) Channels.java:296
org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(ChannelHandlerContext, SocketAddress, Object) FrameDecoder.java:462
org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(ChannelHandlerContext, Channel, ChannelBuffer, SocketAddress) FrameDecoder.java:443
org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(ChannelHandlerContext, MessageEvent) FrameDecoder.java:303
org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(ChannelHandlerContext, ChannelEvent) SimpleChannelUpstreamHandler.java:70
org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline$DefaultChannelHandlerContext, ChannelEvent) DefaultChannelPipeline.java:564
org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(ChannelEvent) DefaultChannelPipeline.java:559
org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channel, Object, SocketAddress) Channels.java:268
org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channel, Object) Channels.java:255
org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(SelectionKey) NioWorker.java:88
org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(Selector) AbstractNioWorker.java:108
org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run() AbstractNioSelector.java:337
org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run() AbstractNioWorker.java:89
org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run() NioWorker.java:178
org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run() ThreadRenamingRunnable.java:108
org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run() DeadLockProofWorker.java:42
java.lang.Thread.run() Thread.java:745
```

So what has happened is that our application code executed a new call to ES within the completion handler of the previous ES call, which in turn is executed on the `transport_client` thread. This is obviously not a good idea, so we have to change this. But still, it would be interesting to know why this would cause (what looks like) a deadlock, and why it impacts other ES requests as well.

**Comment by s1monw** [comment]
I think we this is the same issue https://github.com/elastic/elasticsearch/pull/10644 ?

**Comment by kjbekkelund** [comment]
@s1monw Not sure I've understood that issue correctly, but is this only when there is a connection error? Will we see these connection error in the Elasticsearch logs? I can't seem to find anything in the logs that indicate any issues.

**Comment by s1monw** [comment]
@kjbekkelund I think this is can happen on all retries of some sort?

**Comment by kjbekkelund** [comment]
@s1monw Ah, of course, `RetryListener`. Btw, this also happenend on `localhost`, so there shouldn't be any connection errors at least. I'm not sure when Elasticsearch retries, but we have some update calls — however, I can't seem to be able to correlate this error with those calls.

**Comment by nilsga** [comment]
It looks related, but I'm not sure its the same issue. In our case, it is the success handler that has been invoked on the `transport_client` thread.

**Comment by s1monw** [comment]
> It looks related, but I'm not sure its the same issue. In our case, it is the success handler that has been invoked on the transport_client thread.

so IMO what happens here and as well as in #10644 is that we are executing stuff on the transport clients thread which is actually the default behavior. if you want this you can set `#listenerThreaded(true)` on your request then this shouldn't happen anymore. We need to find a better solution for this in the future...

**Comment by nilsga** [comment]
But why the apparent deadlock?

**Comment by s1monw** [comment]
> But why the apparent deadlock?

I don't know your code but if you execute a blocking network operation on a thread that is supposed to execute this operation as well as handling it's response your are running into a deadlock since you are blocking for the call to come back but there is no thread to handle the response. Does this make sense?

**Comment by nilsga** [comment]
I can see that it is a "typical" deadlock scenario, but I still don't quite get why it only happens some times, and why it seems to block many other (seemingly) unrelated requests while there are many free transport threads available. Anyway, we refactored the problematic code, so it is no longer a problem for us, so if this is "by design", then you can go ahead and close the issue.

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/10940

**Comment by makeyang** [comment]
@clintongormley 
I have checked the code and it turns out the pull: https://github.com/elastic/elasticsearch/pull/10644/commits/91e2bb193ce0655ed4e80fede321abcba281caac
 hasn't merged into any code base below:
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java
https://github.com/elastic/elasticsearch/blob/v2.0.2/core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java
https://github.com/elastic/elasticsearch/blob/v2.1.2/core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java
do I miss something or what?

**Comment by colings86** [comment]
Not sure how you determined that this has not been merged. I can see this commit in some of the lines of the master branch link you listed above by doing looking at the blame view: https://github.com/elastic/elasticsearch/blame/master/core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java#L272

Maybe it would solve your problem quicker if you explained clearly on the discuss forums what issue you are seeing which is leading you to believe this?
