### ISSUE TITLE
Add ability to use a stored script with a terms aggregation

### ISSUE THREAD

**Issue by tagg7** [elastic/elasticsearch#10760]
Currently, the only way to use a script with a terms aggregation is to use dynamic scripting (which is now disabled by default). 

There should instead be a way to use an indexed script or a script stored on disk, similar to what is possible for a query filter script.

Note that this is only valid for unsandboxed languages.

**Comment by clintongormley** [comment]
Hi @tagg7 

You can use the `script_file` or `script_id` parameters instead of `script`. I've updated the docs to reflect this.
