### ISSUE TITLE
Remove compound format index settings

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#10778]
The `index.compound_format` and `index.compound_on_flush` settings shouldn't be changeable any more.  We should remove these settings.

**Comment by clintongormley** [comment]
Closed by #15594

**Comment by atombender** [comment]
Sorry to hijack this, but I just discovered that Elasticsearch will switch to the compound format for some large indexes, and this means you lose segment-level stats in `/_stats`, which is problematic for a certain type of benchmarking/stress testing I'm doing. Is there a way to get compound segment stats directly from the files?
