### ISSUE TITLE
[ESQL] Difference in performance of two equivalent queries with st_centroid_agg 

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#107716]
I have an index that contains a geo_point field. The following query takes 0.5 seconds to run:
```
from points | stats st_centroid_agg(location) 
```

But the following query takes more than 20 seconds:

```
from points | stats st_centroid_agg(TO_GEOPOINT(location)) 
```
Both queries are equivalent but the first one is reading values from doc values while the second one is reading them from _source. We can probably do better than that.

**Comment by craigtaverner** [comment]
Wrote some benchmarks to show centroid performance in aggs, as well as ESQL, and included this particular version, and the performance difference is really incredible:
<img width="262" alt="Screenshot 2024-05-14 at 18 00 58" src="https://github.com/elastic/elasticsearch/assets/114451/abf06f7e-6d43-4ea4-9961-6fa078211f39">

**Comment by craigtaverner** [comment]
After merging #108713 local benchmarks showed the two queries performing about the same.

|                                                         Metric |                          Task |            Value |   Unit |
| --: | --: | :-- | --: |
|                                        50th percentile latency |                 centroid-esql |    189.207       |     ms |
|                                        90th percentile latency |                 centroid-esql |    200.989       |     ms |
|                                       100th percentile latency |                 centroid-esql |    210.415       |     ms |
|                                        50th percentile latency |     centroid-to_geopoint-esql |    188.44        |     ms |
|                                        90th percentile latency |     centroid-to_geopoint-esql |    201.031       |     ms |
|                                       100th percentile latency |     centroid-to_geopoint-esql |    210.058       |     ms |
