### ISSUE TITLE
Nested and Multi-field should not re-use field name

### ISSUE THREAD

**Issue by gamars** [elastic/elasticsearch#10772]
I would like to use spring-data-elastic search as part of a larger data-project. 

While I was pleasantly surprised to see the fine-grained control the @Field annotation is providing I am a bit confused by the repeating field.name repetition as part of the multi-field and nested Types: 

in MappingBuilder.java
```
    private static void addNestedFieldMapping(...) throws IOException {
	builder.startObject(field.getName() + "." + annotation.dotSuffix());
        ...
    }
```
should it not read:
```
   private static void addNestedFieldMapping(...) throws IOException {
      builder.startObject(annotation.suffix());
   }
```

**Comment by dadoonet** [comment]
I think you are not opening this issue in the right project.
MapperBuilder is there: https://github.com/spring-projects/spring-data-elasticsearch

Closing.

**Comment by gamars** [comment]
indeed, that is what you get when having too many tabs open. Sorry for the inconvenience :/

**Comment by dadoonet** [comment]
lol! No problem :)
