### ISSUE TITLE
dot_product not work!

### ISSUE THREAD

**Issue by longday1102** [elastic/elasticsearch#107780]
### Elasticsearch Version
8.13.0

Below is the code where I define my data fields, in which the ```content_vector``` field with similarity is ```dot_product```. In the process of getting the embedding vectors from my model, I normalized the values in each vector to a length of 1. The ```actions``` variable is the setting for me to push my data to elasticsearch. 
However, this code encounters the error ```elasticsearch.helpers.BulkIndexError: 423 document(s) failed to index.```
I found that if I replace ```_source``` in ```actions``` with ```doc``` or change the ```similarity``` of the ```content_vector``` field to ```cosine```, no error will occur.
```
fields_setting = {
        "mappings": {
            "properties": {
                "content": {
                    "type": "text",
                    "similarity": "BM25",
                    "analyzer": "vn_analyzer"
                },
                "grade": {
                    "type": "integer"
                },
                "subject": {
                    "type": "integer"
                },
                "unit": {
                    "type": "text",
                    "similarity": "BM25",
                    "analyzer": "vn_analyzer"
                },
                "title": {
                    "type": "text",
                    "similarity": "BM25",
                    "analyzer": "vn_analyzer"
                },
                "section": {
                    "type": "text",
                    "similarity": "BM25",
                    "analyzer": "vn_analyzer"
                },
                "content_vector": {
                    "type": "dense_vector",
                    "index": True,
                    "dims": hidden_size,
                    "element_type": "float",
                    "similarity": "dot_product"
                }
            }
        }
    }

index_config = ESConfig.index_config(stopwords = stopwords, fields_setting = fields_setting)
es.indices.create(index = "es_text", body = index_config, request_timeout = 1000)

actions = [
        {
            "_op_type": "index",
            "_index": args.index_name,
            "_id": cfg["_id"],
            "_source": {
                "content": cfg["content"],
                "content_vector": cfg["content_vector"],
                "grade": cfg["grade"],
                "subject": cfg["subject"],
                "unit": cfg["unit"],
                "title": cfg["title"],
                "section": cfg["section"],
            }
        } for cfg in document
    ]
helpers.bulk(es, actions, request_timeout = 1000)
```

Can someone explain to me why there is such an error?

**Comment by benwtrent** [comment]
@longday1102 this is likely due to your vector values not being normalized (magnitude of length 1). 

The bulk response should have some details contained in the response indicating the failure.

**Comment by longday1102** [comment]
> @longday1102 this is likely due to your vector values not being normalized (magnitude of length 1).
> 
> The bulk response should have some details contained in the response indicating the failure.

I normalized the length of the dense_vectors to 1 but that didn't solve the error.

**Comment by benwtrent** [comment]
@longday1102 to solve the issue, we will need to know what the bulk error failure details are. Could you provide those? An option is as well to attempt to index the same documents (or just one of the failing ones) manually via the Kibana Console or CURL.

**Comment by benwtrent** [comment]
@longday1102 any information on this still failing? If not, I will close this issue.

**Comment by benwtrent** [comment]
Barring any other feed back, closing. Will reopen if necessary.
