### ISSUE TITLE
Investigate more generic handling of `queryName` field in QueryBuilders

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#10776]
Working on #10669 the issue came up that most of the queries implementing "QueryBuilder" can be named queries supporting the `_name` parameter and also have internal `queryName` field. When constructing the actual lucene query this is used to store the resulting named query in the QueryParseContext. We should try to think about a more generic way to handle this for all queries.

From the 37 queries currently implementing QueryBuilder only 7 don't support having a "queryName":

  * BoostingQB
  * ConstantScoreQB
  * FunctionScoreQB
  * MatchAllQB
  * SpanMultiTermQB
  * TemplateQB
  * WrapperQB

**Comment by dakrone** [comment]
I think all queries should support `_name` for the sake of completeness

**Comment by clintongormley** [comment]
agree with @dakrone - if a query doesn't support it, it's a bug

**Comment by javanna** [comment]
+1 on supportong `_name` across the board. As part of the query refactoring we should indeed make this more generic, to make sure we don't forget about it for some queries.

**Comment by javanna** [comment]
I think we should do the same with `boost` rather than repeating it for every query. We should support boost across the board too no?

**Comment by javanna** [comment]
Closed via #11974

**Comment by gaojccn** [comment]
这是给查询条件起个别名吗
