### ISSUE TITLE
Unbox Tuple at call sites.

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#10787]
See #10784 for an example doing this for Bootstrap class. IMO this is an easy win for readability of the code and it would be good to do it everywhere.

Unboxing these immediately gives the developer back control of the variable and parameter names. Even when the name is simple like 'settings' it is better than 'v1' or 'v2'. It tells something, as opposed to 'newSettings' or 'oldSettings'. 'v1' and 'v2' are never good names.

**Comment by s1monw** [comment]
++
