### ISSUE TITLE
Incorrect version value in Get snapshot API

### ISSUE THREAD

**Issue by Kxrr** [elastic/elasticsearch#107821]
### Elasticsearch Version

8.13.2

### Java Version

_bundled_

### OS Version

macOS 12.6 arm64

### Problem Description

I got a incorrect version value in **Get snapshot API**.

The version value  I expected should be `8.13.2` but got `8503000`.

```json
{
  "snapshots": [
    {
      "snapshot": "snapshot-hsjzkg",
      "uuid": "SW36jieIQXqUf_BnIq_AOw",
      "repository": "repository-jrxm",
      "version_id": 8503000,
      "version": "8503000",
      "indices": [
        "index-yzdp"
      ],
      "data_streams": [
        
      ],
      "include_global_state": true,
      "state": "SUCCESS",
      "start_time": "2024-04-24T08:35:41.777Z",
      "start_time_in_millis": 1713947741777,
      "end_time": "2024-04-24T08:35:42.593Z",
      "end_time_in_millis": 1713947742593,
      "duration_in_millis": 816,
      "failures": [
        
      ],
      "shards": {
        "total": 8,
        "failed": 0,
        "successful": 8
      },
      "feature_states": [
        
      ]
    }
  ],
  "total": 1,
  "remaining": 0
}
```

And the latest document said the version value is `float` type which seems to be wrong too.

<img width="756" alt="image" src="https://github.com/elastic/elasticsearch/assets/13625556/ef5c022f-9b24-41d7-aeb2-2553f2c4bb28">

### Steps to Reproduce

1. backup a index on ES 8.13.2
2. access `Get snapshot API` to get snapshot info

**Comment by DaveCTurner** [comment]
Kinda a snapshot/restore issue but really it relates to the recent core/infra project on versions, see e.g. https://github.com/elastic/elasticsearch/issues/106795
