### ISSUE TITLE
Support * wildcard to retrieve stored fields

### ISSUE THREAD

**Issue by lvernaillen** [elastic/elasticsearch#10783]
Currently you can retrieve stored fields of a search hit using the [fields](http://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-fields.html) option.
However you cannot use wildcards.

Suppose I have document with several title fields such as "book_title", "chapter_title", "paragraph_title", "section_title" and I want to have all those title fields returned from a query.

It would be nice to have something like this:

```
{
    "fields" : [ "*_title" ],
    "query" : {
        "term" : { "category" : "quote" }
    }
}
```

No need to specify all the fields and when new title fields are added they are automatically returned.
Wildcard * is already supported when specifying the fields in a multi_match query or when specifying the fields to highlight for example.

A current workaround is using [source-filtering](http://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html), which does allow the * wildcard. 

```
{
    "_source": "*_title" ,
    "query" : {
        "term" : { "category" : "quote" }
    }
}
```

**Comment by clintongormley** [comment]
Agreed.  Btw, using `_source` is the preferred way of doing this, rather than using stored fields to store all of your fields a second time.
