### ISSUE TITLE
Remove `ElasticsearchIllegalArgumentException` and `ElasticsearchIllegalStateException` in favor of the JDK one

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#10794]
These exceptions are obsolete and our REST layer handles the response code just fine now.

**Comment by dakrone** [comment]
@s1monw can be remove `Preconditions.checkNotNull` in favor of the JDK `Objects.requireNonNull` also?

**Comment by s1monw** [comment]
IMO we can

**Comment by dadoonet** [comment]
Could we have any issue with the transport layer if we change the JDK version and if JDK does not serialize the same way those exceptions?

**Comment by s1monw** [comment]
> Could we have any issue with the transport layer if we change the JDK version and if JDK does not serialize the same way those exceptions?

That makes no difference we also use the same serialization no matter if the exception is in our code or not.
