### ISSUE TITLE
HLRC version compatible issue

### ISSUE THREAD

**Issue by wyn20140226** [elastic/elasticsearch#107931]
### Description

The current 7.10 version of elasticsearch, and the use of HLRC is also 7.10, if you use e s8.10, how can HLRC be compatible? I see that the official website can only have a solution after 7.16

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by wyn20140226** [comment]
Hello, where is the record in the forum? I didn't find it, thanks
