### ISSUE TITLE
Replication: how to apply back pressure from stalled replication options

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#10797]
With https://github.com/elastic/elasticsearch/pull/10786 shard operations on a replica might need to wait for mappings to be published on the replica so that the indexing request is processed. Is it ok to wait indefinitely / what options do we have to apply back pressure?

**Comment by bleskes** [comment]
IMO this should be done on the primary, once we have the op in flight counter @brwe  is working on in #10610

**Comment by clintongormley** [comment]
@bleskes anything to do here?

**Comment by bleskes** [comment]
yeah, this is still an issue. If something goes wrong on this level, indexing operations will be accumulating in memory and nodes can go OOM. We had a couple of things we talked about that could help here:

1) A request circuit breaker with a limit to the total memory of in-flight requests.
2) A hard but configurable limit to the total number of concurrent operations on a shard. The idea here is that indexing threads will block if there are two many ongoing operations, applying back pressure to the client.

I like #1 better and it's more generic, but #2 is trivial to implement when we get #15956 in. The implementation in that PR has a such limit built in (which we disabled by making it MAX_INT).

**Comment by jpountz** [comment]
@bleskes Do you know if recent changes made this issue invalid or fixed somehow?

**Comment by bleskes** [comment]
@jpountz it's still the same, although we do have a request circuit breaker on the node with the primary now, so if this really accumulates it will start rejecting requests. I don't think it addresses this issue but I'm also not sure if it's worth keeping around.

**Comment by jpountz** [comment]
OK, I'll close then.
