### ISSUE TITLE
Can not update mapping of inner object

### ISSUE THREAD

**Issue by hurshprasad** [elastic/elasticsearch#10801]
curl -XPUT "http://elasticsearch/users/_mapping/user-type" -d'
    {
      "user-type": {
        "properties": {
          "address.state.name": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      }
    }

this ends up creating a whole new mapping

    "properties": {
                   "address": {
                      "properties": {
                         "state": {
                            "properties": {
                               "abbreviation": {
                                  "type": "string"
                               },
                               "id": {
                                  "type": "long"
                               },
                               "name": {
                                  "type": "string"
                               }
                            }
                         },
                         "zip_code": {
                            "type": "string"
                         }
                      }
                   },
                   "address.state.name": {
                      "type": "string",
                      "index": "not_analyzed"
                   },

I am on 1.5 release

**Comment by dadoonet** [comment]
@hurshprasad indeed. There are misunderstanding here.

1. you can not update an existing field. You need to create another mapping (or index) and reindex your documents. So even if your syntax would have been correct, it would have failed at the end.
2. your syntax is incorrect. You should use nested objects to define your mapping:

```json
DELETE issue
PUT issue
PUT issue/10801/_mapping
{
  "10801": {
    "properties": {
      "address": {
        "properties": {
          "state": {
            "properties": {
              "abbreviation": {
                "type": "string"
              },
              "id": {
                "type": "long"
              }
            }
          },
          "zip_code": {
            "type": "string"
          }
        }
      }
    }
  }
}
PUT issue/10801/_mapping
{
  "10801": {
    "properties": {
      "address": {
        "properties": {
          "state": {
            "properties": {
              "abbreviation": {
                "type": "string"
              },
              "id": {
                "type": "long"
              },
              "name": {
                "type": "string",
                "index": "not_analyzed"
              }
            }
          },
          "zip_code": {
            "type": "string"
          }
        }
      }
    }
  }
}
GET issue/10801/_mapping
```

If you have any question like this, please prefer the mailing list.

Closing as I don't think it's an issue here. Feel free to reopen if you think it is.
