### ISSUE TITLE
[Profiling] Support multiple associated groups for TopN

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#108018]
As of 8.14.0, the TopN API allows to specify a request body parameter called `aggregation_field`.  It specifies the name of a field in the respective events index (`profiling-events` or the index denoted by the `indices` request body parameter). When specified, this field is used to build sub-groups for the associated function. One use-case for this field is to get the (APM) service names in which a function has been called.

We should extend support to allow not only one but multiple associated groups, which requires the following changes:

1. Add a new request body parameter called `aggregation_fields` (note the trailing `s`) that takes an array of aggregation fields. We should limit the size of this array to at most `N` items to avoid a bucket explosion and reject the request with a validation exception if it contains more items. The UI would require `N=2` so we should limit it to that size.
2. Use this request body parameter to determine the respective counts of all associated sub-groups.
3. Change the response body to return a nested structure of sub-groups (see below for an example) if `aggregation_fields` is present. For backwards-compatibility the old format should still be support if `aggregation_field` (note the singular) is set instead of `aggregation_fields`.

Here is a hypothetical example response showing the `sub_groups` of a single TopN function for a request where `aggregation_fields` is set to `["service.name", "transaction.name"]`:

```json
{
  "sub_groups": {
    "service.name": {
      "basket": {
        "count": 312,
        "transaction.name": {
          "add-to-basket": {
            "count": 199
          },
          "delete-from-basket": {
            "count": 113
          }
        }
      }
    }
  }
}
```

**Comment by cauemarcondes** [comment]
LGTM
