### ISSUE TITLE
Confusing error message when I have a syntax error on bucket function

### ISSUE THREAD

**Issue by stratoula** [elastic/elasticsearch#108053]
### Elasticsearch Version

8.15

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 22.6.0

### Problem Description

Trying to write the `bucket` command I had a syntax error. ES returns 2 errors. The first is correct, it describes what I should do to fix the query but the second is wrong as it says that the column doesn't exist. The column exists and if I fix the syntax error the buckets will be created

![image (34)](https://github.com/elastic/elasticsearch/assets/17003240/4db8ff08-1fc2-4515-bf67-708b91d0d468)

### Steps to Reproduce

Just try to create a syntaxx error on the bucket function. Example:

```
from index  | stats count_distinct(message.keyword) by BUCKET(bytes_gauge, 10)
```

This returns the errors:

```
[esql] > Unexpected error from Elasticsearch: verification_exception - Found 2 problems
line 1:84: function expects exactly four arguments when the first one is of type [LONG] and the second of type [INTEGER]
line 1:64: Unknown column [message.keyword]
```

**Comment by astefan** [comment]
The way we resolve the Aggregates misses to further attempt to resolve the aggregates if resolving the groupings in unsuccessful.
