### ISSUE TITLE
`date_histogram` and `histogram` might produce duplicate buckets in mixed version scenarios

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#108181]
Due to the change in https://github.com/elastic/elasticsearch/pull/105359, the order of the buckets generated during a partial reduction for date histograms and histograms aggregations has been changed. This is normally ok except when the results of these partial reductions are shared between clusters in different versions.

One of this cases is cross-cluster search when the coordinator node is in a previous version. The resulting buckets are then in an unexpected order, failing to merge the buckets successfully.

Another case is rolling upgrades with enough shards to enable incremental reduction. In that case incremental reductions performed on nodes on 8.13 might produce incorrect results when the coordinating node is before 8.13.

**Comment by jbyroads** [comment]
According to 8.13.4 release notes, this was fixed as part of that release.

![image](https://github.com/elastic/elasticsearch/assets/45469917/bc7276ea-c822-463d-b5ae-345020e34707)

**Comment by wchaparro** [comment]
closed - corrected in 8.13.4 (as noted above)
