### ISSUE TITLE
ESQL - EventStats (Aggregate & Get original events) command

### ISSUE THREAD

**Issue by getkub** [elastic/elasticsearch#108143]
### Description

Need a functionality similar to 'Eventstats' of splunk
- eventstats command generates summary statistics from fields in your events and saves those statistics into a new field. 
- The eventstats command places the generated statistics in new field that is added to the original raw events.

This way we can aggregate and then do further analysis using original data

**Comment by nik9000** [comment]
We've been calling this "INLINESTATS" because it adds the results of the `STATS` command into the results stream of data. I have an issue to track it (#107589), but it's super bare. I'll expand it and close this one. That'll let folks searching for EVENTSTATS find the other one.

**Comment by getkub** [comment]
thanks @nik9000  for the quick update. In Splunk etc there are two type of such commands (one is 'eventstats' and other is 'streamstats' while streaming). So if you can look into both within inlinestats that would be great

**Comment by nik9000** [comment]
We're certainly going to *start* with EVENTSTATS. The windowing stuff will come eventually!
