### ISSUE TITLE
[DOCS] Missing information in Health API documentation

### ISSUE THREAD

**Issue by consulthys** [elastic/elasticsearch#108173]
### Elasticsearch Version

8.13

### Installed Plugins

-

### Java Version

_bundled_

### OS Version

-

### Problem Description

When hitting the `_health_report` API endpoint, the response contains the following details for the `shards_availability` indicator:
```
# GET _health_report/shards_availability 200 OK
{
  "cluster_name": "769d3fc80cf24f62a94299876a975d8e",
  "indicators": {
    "shards_availability": {
      "status": "yellow",
      "symptom": "This cluster has 8 unavailable replica shards.",
      "details": {
        "unassigned_primaries": 0,
        "initializing_primaries": 0,
        "creating_primaries": 0,
        "restarting_primaries": 0,
        "started_primaries": 214,
        "unassigned_replicas": 8,
        "initializing_replicas": 0,
        "restarting_replicas": 0,
        "started_replicas": 192,
        "creating_replicas": 0                    <--------------------------
      },
      "impacts": [
        ...
```

In the [Health API documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/health-api.html#health-api-response-details-shards-availability), however, the `creating_replicas` description is missing.
<img width="278" alt="Capture d’écran 2024-05-02 à 05 50 07" src="https://github.com/elastic/elasticsearch/assets/1280019/102cd8d3-6a9d-4d8b-80b7-816834185c05">

### Steps to Reproduce

1. Hit `GET _health_report/shards_availability`
2. Browse to https://www.elastic.co/guide/en/elasticsearch/reference/current/health-api.html#health-api-response-details-shards-availability
3. Compare the docs with the response

**Comment by szabosteve** [comment]
Opened a PR to fix this issue: https://github.com/elastic/elasticsearch/pull/108296
