### ISSUE TITLE
Make script parameters in significant terms same as elsewhere

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#10810]
The `script_type` parameter in sigterms is non-standard.  

http://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-bucket-significantterms-aggregation.html#_scripted

We should use the same script construct that we use elsewhere.

**Comment by clintongormley** [comment]
@markharwood See https://github.com/elastic/elasticsearch/pull/10649 and https://github.com/elastic/elasticsearch/pull/7977

**Comment by colings86** [comment]
@markharwood this should have been fixed in https://github.com/elastic/elasticsearch/pull/11164. You might need to test to confirm though

**Comment by markharwood** [comment]
Just tried it and it works. Thanks @colings86
