### ISSUE TITLE
[CI] DanglingIndicesRestIT.testDanglingIndicesCanBeDeleted failing

### ISSUE THREAD

**Issue by edsavage** [elastic/elasticsearch#108288]
### CI Link

https://buildkite.com/elastic/elasticsearch-periodic-platform-support/builds/2637#018f4c10-dc4e-48be-8ee7-ba0ea1a047c1

### Repro line

./gradlew ':qa:smoke-test-http:javaRestTest' --tests "org.elasticsearch.http.DanglingIndicesRestIT.testDanglingIndicesCanBeDeleted" -Dtests.seed=BAF5712830721EF6 -Dtests.locale=fi-FI -Dtests.timezone=NZ -Druntime.java=21

### Does it reproduce?

No

### Applicable branches

main

### Failure excerpt

org.elasticsearch.http.DanglingIndicesRestIT > testDanglingIndicesCanBeDeleted FAILED
--
  | java.lang.AssertionError:
  | Expected: <3>
  | but: was <2>
  | at __randomizedtesting.SeedInfo.seed([BAF5712830721EF6:164B422ACB257E03]:0)
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
  | at org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2160)
  | at org.elasticsearch.http.DanglingIndicesRestIT.listDanglingIndexIds(DanglingIndicesRestIT.java:176)
  | at org.elasticsearch.http.DanglingIndicesRestIT.testDanglingIndicesCanBeDeleted(DanglingIndicesRestIT.java:166)

**Comment by ywangd** [comment]
Failed again
* https://gradle-enterprise.elastic.co/s/yrc4yauo3fv4e/tests/task/:qa:smoke-test-http:javaRestTest/details/org.elasticsearch.http.DanglingIndicesRestIT/testDanglingIndicesCanBeDeleted?top-execution=1
* https://gradle-enterprise.elastic.co/s/edzokzq7dqvra/tests/task/:qa:smoke-test-http:javaRestTest/details/org.elasticsearch.http.DanglingIndicesRestIT/testDanglingIndicesCanBeDeleted?top-execution=1

**Comment by luigidellaquila** [comment]
Failed again

https://gradle-enterprise.elastic.co/s/fgz24muow2ol6/tests/task/:qa:smoke-test-http:javaRestTest/details/org.elasticsearch.http.DanglingIndicesRestIT/testDanglingIndicesCanBeDeleted?top-execution=1
