### ISSUE TITLE
Check and fix incorrect documentation for timeout related parameters

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#108224]
[Templates](https://github.com/elastic/elasticsearch/blob/main/docs/reference/rest-api/common-parms.asciidoc) are used to document common parameters such as `timeout` and `master_timeout`. Many APIs do support both parameters. However there are also APIs that support only one of them. For example, [ClusterGetSettings API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-get-settings.html#cluster-get-settings) supports only `master_timeout` while [NodesStats API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-get-settings.html#cluster-get-settings) supports only `timeout`. In addition, the APIs that support only `timeout` parameter may have a different default than the 30 seconds defined in the template, e.g. NodesStats API defaults to no timeout. We should cross-check with the API implementation to make sure documentation is consistent.

**Comment by leemthompo** [comment]
@lcawl is working on our API docs automation project which should alleviate some of these manual concerns. Just CC'ing in case that might solve issues like this sooner rather than later. :)

**Comment by ywangd** [comment]
@leemthompo Full automation would for sure be better and welcomed in the long run. For the timebeing, we plan to have this issue as an onboarding task for new team members. Thanks!

**Comment by nicktindall** [comment]
Summary of findings [here](https://docs.google.com/spreadsheets/d/1vsBAt5Z8qAidfW9CcDKtfxXfHv4HBWVicJMwvnkhRfc/edit#gid=0)

Still WIP
