### ISSUE TITLE
[CI failure] org.elasticsearch.transport.netty.NettyTransportMultiPortTests

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#10824]
There are leaked threads, however I found this exception before that in the output. Might be related?

2015-04-27 10:14:36,536][INFO ][transport.netty          ] Exception [BindTransportException] occurred, rerunning the test after [1] failures
  1> org.elasticsearch.transport.BindTransportException: Failed to bind to [56378]
  1> 	at org.elasticsearch.transport.netty.NettyTransport.bindServerBootstrap(NettyTransport.java:426)
  1> 	at org.elasticsearch.transport.netty.NettyTransport.doStart(NettyTransport.java:295)
  1> 	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:85)
  1> 	at org.elasticsearch.transport.netty.NettyTransportMultiPortTests.startNettyTransport(NettyTransportMultiPortTests.java:186)

See http://build-us-00.elastic.co/job/es_core_14_centos/3919/

**Comment by cbuescher** [comment]
Maybe this one is related?
http://build-us-00.elastic.co/job/es_core_15_regression/179

Expected to get exception when connecting to port 49730

Stacktrace

java.lang.AssertionError: Expected to get exception when connecting to port 49730
	at __randomizedtesting.SeedInfo.seed([D687F4FC67362C05:9D6F87E86388EC96]:0)
	at org.junit.Assert.fail(Assert.java:93)
	at org.elasticsearch.transport.netty.NettyTransportMultiPortTests.assertConnectionRefused(NettyTransportMultiPortTests.java:185)

**Comment by clintongormley** [comment]
Much has changed since this was opened. Closing
