### ISSUE TITLE
Typed parameters in Java index API

### ISSUE THREAD

**Issue by magnhaug** [elastic/elasticsearch#10825]
I believe the method signature for `IndexRequestBuilder.setSource(Map<String, Object> source)` should be changed to `IndexRequestBuilder.setSource(Map<String, ?> source)`.
Since the method is overloaded, a call to `setSource` with a `Map<String, String>` as parameters will invoke the method `IndexRequestBuilder.setSource(Object... source)`, to great confusion. 

The same goes for `CreateIndexRequestBuilder.setSettings(Map<String, Object> source)` in the indices admin client, and a few others.

**Comment by clintongormley** [comment]
@javanna could you take a look please?

**Comment by javanna** [comment]
I think this makes sense, will mark as adoptme.
