### ISSUE TITLE
Test destructivePackagingTest fails

### ISSUE THREAD

**Issue by edsavage** [elastic/elasticsearch#108287]
### CI Link

https://buildkite.com/elastic/elasticsearch-periodic-packaging/builds/2306#018f4a62-2eee-4e47-acd2-4720ebc25c1b

### Repro line

./.ci/scripts/packaging-test.sh destructivePackagingTest

### Does it reproduce?

Didn't try

### Applicable branches

main, 8.14

### Failure excerpt

```

1> [2024-05-05T20:22:15,238][INFO ][o.e.p.u.Shell            ] [TEST-ArchiveGenerateInitialCredentialsTests.test20NoAutoGenerationWhenAutoConfigurationDisabled-seed#[9DC27A5E53D93422]-workerest_thread_info] Ran: [bash, -c, expect - <<EXPECT
--
  | 1> set timeout 60
  | 1> spawn -ignore HUP sudo -E -u elasticsearch /tmp/elasticsearch/bin/elasticsearch -p /tmp/elasticsearch/elasticsearch.pid -v
  |  
  | 1> expect {
  | 1>   "uncaught exception" { send_user "\nStartup failed due to uncaught exception\n"; exit 1 }
  | 1>   timeout { send_user "\nTimed out waiting for startup to succeed\n"; exit 1 }
  | 1>   eof { send_user "\nFailed to determine if startup succeeded\n"; exit 1 }
  | 1>   -re "o\.e\.n\.Node.*] started"
  | 1> }
  |  
  | 1> EXPECT
  | 1> ] exitCode = [1] stdout = [spawn -ignore HUP sudo -E -u elasticsearch /tmp/elasticsearch/bin/elasticsearch -p /tmp/elasticsearch/elasticsearch.pid -v


```

**Comment by mark-vieira** [comment]
I'm wondering if we just need to bump the timeout here. It seems odd that there's roughly a 30 second delay from when we start ES to when we start seeing logging.

https://gradle-enterprise.elastic.co/s/ny53faw2kfl24/tests/task/:qa:packaging:destructiveDistroTest.default-linux-archive/details/org.elasticsearch.packaging.test.ArchiveGenerateInitialCredentialsTests/test20NoAutoGenerationWhenAutoConfigurationDisabled?expanded-stacktrace=WyIwIl0&top-execution=1
