### ISSUE TITLE
[DEB] Unable to install older versions via packages.elasticsearch.org

### ISSUE THREAD

**Issue by mfn** [elastic/elasticsearch#10826]
I cannot install e.g. 1.5.1 via the repository. When I add this line:
```
deb http://packages.elasticsearch.org/elasticsearch/1.5/debian stable main
```
and after `apt-get update` perform
```
$ sudo /usr/bin/apt-get install elasticsearch=1.5.1
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '1.5.1' for 'elasticsearch' was not found
```
I can, however, download it manually from the download page but changing the URL myself: https://www.elastic.co/thank-you?url=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.5.1.deb

Is this intentional?

I'm using 1.5.1 for a specific case in a Vagrant machine which doesn't install now.

**Comment by spinscale** [comment]
Hey,

this is not intentional. I'll take a look. Thx for reporting!

**Comment by spinscale** [comment]
can you retry and report back? I just tested with a fresh ubuntu VM and it worked on that one.

**Comment by mfn** [comment]
Works now for me too ... ?!?!

**Comment by spinscale** [comment]
The `Packages` file wasnt created correct, recreated it the right way.

nice, thx a lot for confirming! Closing then.
