### ISSUE TITLE
Allocation Explain API default unassigned primary

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch#108207]
### Description

👋 Would you kindly consider defaulting to a primary shard when the [Allocation Explain API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-allocation-explain.html) is ran without a request body? 

E.g. 01611206 the no-request-body returned info about a replica which stated `last_allocation_status: no_attempt` (which made it sound like user needed to investigate software-hardware/logic setup) but attempting the same index's primary shard with an explicit request body reported `no_valid_shard_copy`. 

AFAICT we generally assume users should resolve primaries first in all cases, so I believe it generally makes sense that IF no request body is provided our code's random shard to report on would default attempt to report on a primary.

**Comment by idegtiarenko** [comment]
I believe it is already prioritizing unassigned primaries if any:

https://github.com/elastic/elasticsearch/blob/2b3cfcec2a444e4ca79086c01d70f7a3bb6df9f1/server/src/main/java/org/elasticsearch/action/admin/cluster/allocation/TransportClusterAllocationExplainAction.java#L152-L161

**Comment by idegtiarenko** [comment]
Implemented in https://github.com/elastic/elasticsearch/pull/76220
