### ISSUE TITLE
Request more emphasis on JVM compatibility and recommandation

### ISSUE THREAD

**Issue by benoit-intrw** [elastic/elasticsearch#10821]
In the process of testing upgrade from 1.3.6 to 1.5.1 I got the following message 
```
[2015-04-24 14:47:55,960][ERROR][bootstrap                ] Exception
java.lang.RuntimeException: Java version: 1.7.0_51 suffers from critical bug https://bugs.openjdk.java.net/browse/JDK-8024830 which can cause data corruption.
Please upgrade the JVM, see http://www.elastic.co/guide/en/elasticsearch/reference/current/_installation.html for current recommendations.
If you absolutely cannot upgrade, please add -XX:-UseSuperWord to the JVM_OPTS environment variable.
Upgrading is preferred, this workaround will result in degraded performance.
```

I read again release notes between 1.3.6 and 1.5.1 but don't found any mention on this restriction.

It's explained on this page [Java (JVM) version](http://www.elastic.co/guide/en/elasticsearch/reference/current/setup.html#jvm-version) but I think it should be clearly mentioned on released notes.

**Comment by clintongormley** [comment]
Hi @benoit-intrw 

You're correct - it was missing from the release notes.  That's now fixed: https://www.elastic.co/downloads/past-releases/elasticsearch-1-5-0

thanks for reporting
