### ISSUE TITLE
Utility method to read timeout parameter from REST requests

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#108225]
In #107986, we introduced a utility method to read `master_timeout` from REST requests. We could use a similar utility method for the `timeout` parameter as well. Different APIs have different ways to decide the default `timeout` value. For this issue, we can leave them untouched.

**Comment by prathm3** [comment]
Hi @ywangd , I would like to work on this this task.

**Comment by ywangd** [comment]
@prathm3 Thanks for your interests in Elasticsearch. Unfortunately this issue is already assigned internally. I encourage you to look for other issues.
