### ISSUE TITLE
Add environment path for snapshot repositories

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#10828]
Now the security manager is enabled by default (see #10717 and comments), the repositories of type `fs` must use an environment path (something like `path.snapshots`?) as a base directory for storing snapshots. This path will be added to the policy file by the `org.elasticsearch.bootstrap.Security`.

**Comment by s1monw** [comment]
+1

**Comment by kimchy** [comment]
Today, I believe we allow for users to add fs repository through an API with a path to the endpoint. Maybe the change would be that on the node config, one configures the name+path tuples for folders that within them a custom FS repository can be added to? That way its well contained within paths that are pre configured on node level? If we do this, it will be a backward comp. breaking change, so we need to explain how to upgrade from previous versions to it. Thoughts? /cc @imotov

**Comment by imotov** [comment]
@kimchy I couldn't say I really like it, but I think this is the best proposal so far.
