### ISSUE TITLE
Highlight more_like_this query

### ISSUE THREAD

**Issue by svola** [elastic/elasticsearch#10829]
This is a feature request:

would it be possible to enable highlighting for more_like_this queries?

That would be extremely helpful, as it's not transparent which terms have been used to match a document!

**Comment by nik9000** [comment]
I seem to highlight it just [fine](https://en.wikipedia.org/w/index.php?title=Special%3ASearch&profile=default&search=morelike%3Acats&fulltext=Search). [This](https://en.wikipedia.org/w/index.php?title=Special%3ASearch&profile=default&search=morelike%3Acats&fulltext=Search&cirrusDumpQuery=yes) is how I do it. I do use the [experimental highlighter](https://github.com/wikimedia/search-highlighter) and haven't tested the others but I don't see why they _can't_ do it.

**Comment by svola** [comment]
@nik9000 Thanks for the link. I'll try out that plugin. But with core ElasticSearch highlighting doesn't work for all queries. With match-queries it's working, but not with more_like_this queries.

I'm not the only desperate person...
http://stackoverflow.com/questions/28723308/elasticsearch-more-like-this-with-highlights

**Comment by VorticonCmdr** [comment]
I would like this feature as well and according to this https://discuss.elastic.co/t/keyword-extraction/224/2 it already should work, but for me it does not.

**Comment by maxcom** [comment]
Highlight on mlt query works with fast vector highlighter (you need to index term positions and offsets to use it).

**Comment by svola** [comment]
@maxcom Ok, so I need to change the mapping of the fields, right? Thanks! I will try that...

**Comment by maxcom** [comment]
Yes, you need to change mapping and reindex your data. Note that storing term positions significantly increases index size and may have an impact on search performance.

**Comment by svola** [comment]
Ok, but it's good to know that it's possible! Thanks!

**Comment by svola** [comment]
@maxcom you made my day! Super happy about it...
