### ISSUE TITLE
Error 302 after Configuration alert msteam in watcher elasticsearch

### ISSUE THREAD

**Issue by vanhaiit90** [elastic/elasticsearch#108343]
### Elasticsearch Version

8.6.2

### Java Version

_bundled_

### OS Version

Redhat 9.1

### Problem Description

hi everyone !
Last week I have complete configure alert Microsoft Teams integration to watcher

`send_to_teams": {
"webhook": {
"scheme": "https",
"host": "[xxx.webhook.office.com](http://xxx.webhook.office.com/)",
"port": 443,
"method": "post",
"path": "/",
"params": {},
"headers": {
"Content-Type": "application/json"
},
"body": """{"APM Failed Transaction Rate Alert HTTP 500" : { "Found {{ctx.payload.hits.total}}" : { "HTTP errors in the last minute {{alert.actionGroup}}{{^context.isRatio}}{{#context.group}}{{context.group}} - {{/context.group}}{{context.matchingDocuments}} log entries have matched the following conditions: {{context.conditions}}{{/context.isRatio}}{{#context.isRatio}}{{#context.group}}{{context.group}} - {{/context.group}} Ratio of the count of log entries matching {{context.numeratorConditions}} to the count of log entries matching {{context.denominatorConditions}} was {{context.ratio}}{{/context.isRatio}}" : "Service Name: {{ctx.payload.hits.hits.0._source.service.name}}"}}}"""
}
}`

But I don't understand why it doesn't display the alert on ms team even though the email still displays the alert normally . I checked and see it display error 302. Please help solve this problem. Thank you so much.

### Steps to Reproduce

![699a774981c326af9433303c4c5e180a233e18ae](https://github.com/elastic/elasticsearch/assets/63385356/40f4708b-7bcd-45cb-8f24-420d8cd0770f)

**Comment by nielsbauman** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
