### ISSUE TITLE
`ecs@mappings`'s `ecs_geo_point` path match is overly broad

### ISSUE THREAD

**Issue by axw** [elastic/elasticsearch#108338]
`ecs@mappings` has a `ecs_geo_point` dynamic template with a `path_match` on `["location", "*.location"]`. This is overly wide, and matches non-ECS fields. All ECS `geo_point` fields end with `geo.location`:

```
$ grep flat_name generated/ecs/ecs_flat.yml  | grep location
  flat_name: client.geo.location
  flat_name: destination.geo.location
  flat_name: host.geo.location
  flat_name: observer.geo.location
  flat_name: server.geo.location
  flat_name: source.geo.location
  flat_name: threat.enrichments.indicator.geo.location
  flat_name: threat.indicator.geo.location
```

I think the dynamic template should just `path_match` on `*.geo.location`, as otherwise we risk breaking ingestion for custom/non-ECS fields that happen to end in "location".

**Comment by felixbarny** [comment]
Changing the pattern to `*.geo.location` sounds like a good idea.
