### ISSUE TITLE
syntax bug in documentation

### ISSUE THREAD

**Issue by minde-eagleeye** [elastic/elasticsearch#10832]
missing comma in one of examples can be found in 
http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cluster.html#allocation-filtering

![image](https://cloud.githubusercontent.com/assets/7629410/7351106/16ce57d6-ecfb-11e4-9517-5520805958fe.png)

**Comment by dadoonet** [comment]
@minde-eagleeye Thanks for reporting. Did you know that you can send a PR with the change by clicking on the small "edit" button just on this page? 
Wanna do contribute it?

**Comment by minde-eagleeye** [comment]
I did not see that, I'll do it know thank you.
