### ISSUE TITLE
Response error.root_cause shouldn't empty

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch#10836]
While playing around with master I received the following error response:
```json
{
  "error": {
    "root_cause": [],
    "type": "access_control_exception",
    "reason": "access denied (\"java.io.FilePermission\" \"default-mapping.json\" \"read\")"
  },
  "status": 500
}
```

The `root_cause` should probably contain something, even if it is just a copy of the outer level error.

**Comment by s1monw** [comment]
yeah that`s a bug if there is no `ElasticsearchException` wrapping this thing I guess it omits it... I will fix today or tomorrow thanks for opening this
