### ISSUE TITLE
Prohibit creation of rollup jobs in clusters that have never used rollup.

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#108381]
The rollup feature was never GA-ed and is still tech preview. It has been deprecated since 8.11.0 in favor of downsampling. At some point the rollup functionality will be removed. In order to prepare for the removal of rollup, the creation of rollup in clusters with no rollup usage will be prohibited. To avoid any new usages of rollup while it is scheduled to be removed.

**Comment by rayafratkina** [comment]
cc @alisonelizabeth 

Do we want to do something in the Kibana management UI to prevent users from creating new rollup jobs?
Should we display some message in the UI about the upcoming deprecation?

**Comment by martijnvg** [comment]
@rayafratkina Apologies for the late reply. Maybe my memory isn't correct, but I thought we already highlight that rollup is deprecated? 

I think the UI should highlight that rollup is deprecated (if we haven't done already) and will be removed. Additionally I think it makes sense to warn users that creating a rollup job in an cluster with no rollup usage will fail.
