### ISSUE TITLE
bug in bulk java api?

### ISSUE THREAD

**Issue by rrphotosoft** [elastic/elasticsearch#10839]
Hi, 

I have noticed what looks like a small bug in the java bulk api for ES.
I'm not sure if this is the right place to post it but here goes anyways:

Assume that we set the bulk size to execute every 10 requests.
The expected response is that the afterBulk Callback should be called, once the response is executed.
Unfortunately if I add just 10 items to the bulk queue, there is no response, i.e the afterBulk Callback is not triggered.
I can see that the items are added through sense, or even in the ES console.

In case I add more than 10 items, I get responses for everything after the first 10.

Code to reproduce the issue:
N.B:
*ElasticClientHolder in the code below, is a singleton holding a connection to ES

Elasticsearch v - 1.4.4
Ubuntu 12.04 LTS

      public class BulkProcessorTestClasses {
	 private BulkProcessor bulkprocessor;
	 private BulkRequestBuilder builder;
	
	public BulkProcessor getBulkprocessor() {
		if (bulkprocessor == null) {
			this.bulkprocessor = BulkProcessor
					.builder(ElasticClientHolder.getInstance(),
							new BulkProcessor.Listener() {

								@Override
								public void afterBulk(long execution_id,
										BulkRequest req, BulkResponse resp) {
									// TODO Auto-generated method stub
									System.out.println("execution id:" + execution_id);
									System.out.println(req.toString());
									BulkItemResponse[] resp_items_arr = resp.getItems();
									for(int i=0; i < resp_items_arr.length; i++){
										System.out.println(resp_items_arr[i].getItemId());
									}
									System.out.println(resp.hasFailures());
								}

								@Override
								public void afterBulk(long arg0,
										BulkRequest arg1, Throwable arg2) {
									// TODO Auto-generated method stub
									System.out.println("the whole bulk failed.--->"
											+ arg2.getLocalizedMessage());
								}

								@Override
								public void beforeBulk(long arg0,
										BulkRequest arg1) {
									// TODO Auto-generated method stub
									System.out
											.println("these were the number of requests sent to es. bulk");
									System.out.println(arg1.numberOfActions());

								}

							}).setBulkActions(10)
					.setBulkSize(new ByteSizeValue(1, ByteSizeUnit.GB))
					.setFlushInterval(TimeValue.timeValueSeconds(30))
					.setConcurrentRequests(1).build();
		}
		return bulkprocessor;
	}
        //**
      
	public BulkRequestBuilder getBuilder() {
		if (this.builder == null) {
                         //elasticsearchclientholder is a singleton holding a connection to ES.
			this.builder = ElasticClientHolder.getInstance().prepareBulk();
		}
		return builder;
	}
	
	
	public void build_and_test_bulk_request(){
		for(int i=0; i < 10; i++){
			JSONObject elastic_object = new JSONObject();
			elastic_object.put("test_name", "name_" + String.valueOf(i));
			getBulkprocessor().add(
					new IndexRequest("test_index",
							"test_mapping")
							.source(elastic_object.toJSONString()));
		}
	}
	
	public BulkProcessorTestClasses(){
		build_and_test_bulk_request();
	}
	
        /***
        * the maping contains a single string property called test_name.
        * in an index called test_index, and a type test_mapping.
        *
        */

      }

Calling the build_and_test_bulk_requests returns nothing.

Regards,
RR.

**Comment by dadoonet** [comment]
The problem here is that you don't close the bulkprocessor when you exit your test method.
So bulk is not flushed.

**Comment by rrphotosoft** [comment]
Hi, 
Thanks for the clarification, I realize my mistake, it wasn't in the example on the website, sorry for the trouble, another problem I'm having is how to access the request json string, for those items which failed? I cannot find any methods on the ActionRequest Class that give me access to the json string of the failed request. I need this for logging purposes. Can you help me on that?
Regards,
RR

**Comment by dadoonet** [comment]
So we close this issue.
Please use the mailing list for your questions. We can definitely help you there.

**Comment by rrphotosoft** [comment]
Im sorry,it still does not work  , I tried getbulkprocessor.close() , and getbulkprocessor.flush()
I get not callback.

**Comment by rrphotosoft** [comment]
I would request you to please reopen the issue.

**Comment by rrphotosoft** [comment]
Hi,
I am trying to debug the issue.
The problem does not reside with flush or close.
As I mentioned in my initial post, the records are <i>being indexed</i>. So flush or close is not necessary, execute() is being correctly called.
It is the callback that is not triggered.
I hope that helps to solve the issue.
Regards,
RR.

**Comment by imotov** [comment]
@rrphotosoft I slightly modified your test case to remove the reference to ElasticClientHolder  https://gist.github.com/imotov/d3fe3043949bab3e3e71 and executed it against locally running v1.4.4. I have got the following output:

```
[2015-04-28 15:00:47,428][INFO ][org.elasticsearch.plugins] [Shadowcat] loaded [], sites []
these were the number of requests sent to es. bulk
10
```

Do you expect to see something else?

**Comment by rrphotosoft** [comment]
@imotov Yes, you expect to see "execution_id : 0".

**Comment by imotov** [comment]
@rrphotosoft oh, sorry. The line `bulkprocessor.close();` is what messes it up. It closes the processor immediately. I have updated the gist https://gist.github.com/imotov/d3fe3043949bab3e3e71 Could you give it a try?

**Comment by rrphotosoft** [comment]
@imotov , Hi, it still doesn't work. The first 'n' requests do not trigger the callback, irrespective of the bulk size or whether you call .close/.flush or not.

**Comment by imotov** [comment]
@rrphotosoft when I execute the latest code that I posted I get the following:

```
[2015-04-29 00:49:28,162][INFO ][org.elasticsearch.plugins] [Rafferty] loaded [], sites []
these were the number of requests sent to es. bulk
10
execution id:1
org.elasticsearch.action.bulk.BulkRequest@21152a7a
0
1
2
3
4
5
6
7
8
9
false
```

Seems to be working for me.

**Comment by rrphotosoft** [comment]
@imotov , ok, I was testing it with my original code.
 The difference is that , you have added the "awaitclose" call at the end. 

1.This is not in the docs - I would vote for a docs update which mentions that "awaitclose" needs to be called explicitly.
2.How can you decide for how long to set the awaitclose call?

Regards,
RR.

**Comment by imotov** [comment]
@rrphotosoft I have added description of close and awaitClose to documentation. The timeout in awaitClose depends on how long it takes for your documents to get to elasticsearch, so you will have to find it experimentally. The awaitclose call is not part of the execute method because some clients are using different strategies to determine when the bulk processing is done. For example, you can have a countdown latch that gets decremented in each afterBulk call. In this case the close method would be the way to go. If you have any other questions regarding usage of bulk processor, please feel free to ask them on the mailing list.

**Comment by rrphotosoft** [comment]
@imotov , thanks for your help, and for updating the docs. Cheers!
