### ISSUE TITLE
真的是垃圾

### ISSUE THREAD

**Issue by cklogic** [elastic/elasticsearch#108495]
### Elasticsearch Version

all

### Java Version

all

### OS Version

all

### Problem Description

我只是想下载ES的安装包，结果让我注册和登录账号，我注册和登录了，然后直接给我创建了个Cloud实例？？？

### Steps to Reproduce

我只是想下载ES的安装包，结果让我注册和登录账号，我注册和登录了，然后直接给我创建了个Cloud实例？？？

### Logs (if relevant)

垃圾！

**Comment by joegallo** [comment]
Duplicate of https://github.com/elastic/elasticsearch/issues/108497
