### ISSUE TITLE
[ES|QL][Kibana request] Support _ignored metadata

### ISSUE THREAD

**Issue by stratoula** [elastic/elasticsearch#108401]
### Description

We want in the Discover - Logs experience to display the ignored information per user request. https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-ignored-field.html. 

I am expecting this to be another `metadata` option such as `from logs metadata _ignored`. This is important for the users to know the names of the  fields in a document that have been ignored when the document was indexed.

**Comment by flash1293** [comment]
Is this a duplicate of https://github.com/elastic/elasticsearch/issues/108324 ?
