### ISSUE TITLE
field_value_factor should support a default value for documents that don't have the field

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#10841]
I want to use field_value_factor to remove the last places we use dynamic scripting but I need to support default values if the field isn't set. I have unset fields because my load process is two stepped - I load all the documents first and then I run queries against the loaded set of documents to set the value of this field.

I _could_ make sure to always set the value of the field but that seems brittle - I'd like to just default the field being missing to a 0 input to the field_value_factor function.

This looks pretty simple to implement and I'd be happy to do it if its something Elasticsearch wants.

**Comment by dakrone** [comment]
+1 to this, would happily take a PR!

**Comment by nik9000** [comment]
Thanks!

**Comment by dakrone** [comment]
Thank *you*!
