### ISSUE TITLE
Limit the value in prefix query 

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#108486]
### Description

Prefix queries with a huge values can lead to OOM. Limit the maximum length of the value to be submitted.

**Comment by YahelyUshpiz** [comment]
working on it

**Comment by benwtrent** [comment]
We need to determine what a "huge value" means. 

Additionally, I am not 100% sure we want to simply disable this for all users. If we blindly reject query prefixes we think are "large", it would break existing behavior (e.g. user's who expect a query to work now has their query always fail with no recourse). 

Maybe there should be a setting indicating the allowed prefix size or if "large" prefixes are allowed?

We cannot use the setting [search.allow_expensive_queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html#query-dsl-allow-expensive-queries) to indicate if large prefixes are allowed or not, as its already used to determine if prefix queries themselves are allowed.

**Comment by mayya-sharipova** [comment]
It is reasonable to have a limit of `1000`.  

I suggest we  reuse the setting [index.max_regex_length](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-max-regex-length) and update the documentation that it allows applies to prefix queries. 

@benwtrent What do you think?

**Comment by benwtrent** [comment]
@mayya-sharipova I think using [index.max_regex_length](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-max-regex-length) is a good idea. Default of 1k is prudent.

**Comment by arshPratap** [comment]
Hi @mayya-sharipova  @benwtrent  .. if this issue is open can this be assigned to me. I would love to contribute to elasticsearch 
Thanks
Arsh Pratap
