### ISSUE TITLE
Unable to install rpm on CentOS 5.10

### ISSUE THREAD

**Issue by dvdklnr** [elastic/elasticsearch#10843]
Hello,

On CentOS 5.10 rpm bombs with

[root@eshost ~]# rpm -i elasticsearch-1.5.2.noarch.rpm
error: elasticsearch-1.5.2.noarch.rpm: Header V4 RSA/SHA1 signature: BAD, key ID d88e42b4
error: elasticsearch-1.5.2.noarch.rpm cannot be installed

Is it possible to sign the rpm with V3? 

Thanks,

David

**Comment by pickypg** [comment]
The issue appears to be that it cannot verify the public key for Elasticsearch running on CentOS/RHEL 5.

Trying to import the public key on a fresh install of CentOS 5.11:

```bash
# rpm --import https://packages.elasticsearch.org/GPG-KEY-elasticsearch
error: https://packages.elasticsearch.org/GPG-KEY-elasticsearch: import read failed(-1).
```

**Comment by s1monw** [comment]
`5.11` seems pretty old and the wiki recommends to move away from it. I wonder if we should support it or just recommend to move on as centos does? http://wiki.centos.org/Download

**Comment by markwalkom** [comment]
Technically we don't support RHEL/CentOS <6.X - https://www.elastic.co/subscriptions/matrix

**Comment by clintongormley** [comment]
Closing
