### ISSUE TITLE
No way to use cross_field over nested docs

### ISSUE THREAD

**Issue by serj-p** [elastic/elasticsearch#10840]
Hi, here is my example 

Mapping:

    {
        "contact": {
            "_source": {
                "enabled": true
            },
            "dynamic": false,
            "properties": {
                "address": {
                    "dynamic": false,
                    "type": "nested",
                    "properties": {
                        "city": {
                            "type": "string",
                            "analyzer": "standard"
                        },
                        "country": {
                            "type": "string",
                            "analyzer": "standard"
                        }
                    }
                },
                "name": {
                    "type": "string",
                    "analyzer": "standard"
                }
            }
        }
    }

Doc:

     {
        "name": "Ivan Bobkovits",
        "address": [
            {
                "country": "Ukraine",
                "city": "Kherson"
            }
        ]
    }

Query:

    {
      "multi_match": {
        "operator": "and",
        "query": "Ivan Kherson Ukraine",
        "type": "cross_fields",
        "fields": [
          "name^9999",
          "address.*",
        ]
      }
    }

Which finds nothing. Is there a way to avoid indexing of the plain nested object into the main doc to be able to search crosswise?

**Comment by clintongormley** [comment]
Hi @serj-p 

Nested docs are entirely separate documents (although externally they are hidden).  You need to use a `nested` query to access the fields in those docs, and this may match multiple docs, each with their own `_score`, so these scores need to be reduced to a single number (eg min/max/av/sum).  

The `multi_match` query that you specify is only accessing the root doc, so you can only access the fields in that doc.  You can copy the values of the nested doc into the root doc with `include_in_parent` or `include_in_root`.

**Comment by eratio08** [comment]
Is the `include_in_root` still a valid parameter? - I can't find anything about in the doc
Or is there another way to enable nested field to be used in a multi_match?

**Comment by clintongormley** [comment]
@eratio08 yes it is, or you could use `copy_to` to just copy the nested fields of interest.  See https://github.com/elastic/elasticsearch/issues/12461

**Comment by eratio08** [comment]
How would the `copy_to` equivalent look like for a nested type like the following?
```JSON
{
  "mappings": {
    "my_type": {
      "properties": {
        "foo": {
          "type": "nested",
          "include_in_root": true,
          "properties": {
            "bar": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}
```

something like this?

```JSON
{
  "mappings": {
    "my_type": {
      "properties": {
        "foo": {
          "type": "nested",
          "copy_to": "my_type",
          "properties": {
            "bar": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}
```

**Comment by clintongormley** [comment]
You can't copy to the same path, but you could do:

    {
      "mappings": {
        "my_type": {
          "properties": {
            "foo": {
              "type": "nested",
              "properties": {
                "bar": {
                  "type": "string",
                  "copy_to": "foo_bar"
                },
                "baz": {
                  "type": "string",
                  "copy_to": "foo_baz"
                }
              }
            },
            "foo_bar": {
              "type": "string"
            },
            "foo_baz": {
              "type": "string"
            }
          }
        }
      }
    }

Or even:

    {
      "mappings": {
        "my_type": {
          "properties": {
            "foo": {
              "type": "nested",
              "properties": {
                "bar": {
                  "type": "string",
                  "copy_to": "all_foo"
                },
                "baz": {
                  "type": "string",
                  "copy_to": "all_foo"
                }
              }
            },
            "all_foo": {
              "type": "string"
            }
          }
        }
      }
    }

in which case you don't need cross-fields

**Comment by eratio08** [comment]
So the `"include_in_root": "true"` is a little more convenient because I don't have to address new field names.

Thanks so far!
