### ISSUE TITLE
Enable docvalue_fields parameter for dense_vector fields

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#108470]
### Description

Search request supports [docvalue_fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-fields.html#docvalue-fields) parameter that is currently not supported for `dense_vector` fields.

The reason it is was disabled is disable aggregations on this field.
Investigate if is possible to keep aggregations still disabled but enable `docvalue_fields`  on `dense_vector` fields.

**Comment by Rassyan** [comment]
Hello @mayya-sharipova,

I hope this message finds you well. I've been exploring the enhancement of `dense_vector` field values retrieval from `doc_values` and have a preliminary implementation in place. My initial tests indicate promising functionality.

Here are the key aspects of the current implementation:

- Introduction of a custom `BinaryDocValues` tailored for `dense_vector` fields.
- On-demand vector data loading to optimize memory efficiency.

<img width="1727" alt="image" src="https://github.com/elastic/elasticsearch/assets/26055883/0b13ea7e-2b21-4186-b1d6-2ac0af09e6cf">

I'm eager to ensure that this work aligns with the project's goals and would greatly appreciate your guidance on a couple of points:

- Could you suggest any performance benchmarks or specific use cases that the community is aiming to address with this feature?
- Would there be a preferred data format for the vectors that would best serve the needs of downstream processing?

I'm very interested in contributing to this feature and would be honored to incorporate your expertise as we refine the approach.

Thank you for considering my input.

Warm regards, Rassyan
