### ISSUE TITLE
elasticsearch caught exception while handling client http traffic, closing 

### ISSUE THREAD

**Issue by slipknotc** [elastic/elasticsearch#108534]
### Elasticsearch Version

7.16.2

### Installed Plugins

ik

### Java Version

JDK17

### OS Version

Linux LGDB-smspes03 4.19.90-25.16.v2101.Ky10.x86_64 #1 SMP Tue Jun 7 12:16:51 CST 2022 x86_64 x86_64 x86_64 GNU/LINUX

### Problem Description

![1715405204521](https://github.com/elastic/elasticsearch/assets/20942160/e1258248-b3a5-4065-947e-5df7eb67ffb0)

### Steps to Reproduce

i dont know,i just check log file,find it.

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

Specifically, you're using an old and now-unsupported version. Also, a screenshot of part of an error message is not enough information to form a valid bug report.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
