### ISSUE TITLE
Expose Lucene 5's heap explain API

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#10857]
The new explain API for detailing heap usage can be a huge help in debugging large Elasticsearch systems - for performance or crashes

Obviously if you can add the ES's structures to this functionality , all the better

https://issues.apache.org/jira/browse/LUCENE-5949

**Comment by rmuir** [comment]
Duplicate of #9111

**Comment by synhershko** [comment]
Cool, thanks
