### ISSUE TITLE
[CI] DebMetadataTests test05CheckLintian failing

### ISSUE THREAD

**Issue by mark-vieira** [elastic/elasticsearch#108514]
This looks to be fallout from https://github.com/elastic/elasticsearch/pull/108088 due to the fact that we are not stripping debug symbols from these binaries.

**Build scan:**
https://gradle-enterprise.elastic.co/s/buie66rpbkbgs/tests/:qa:packaging:destructiveDistroTest.default-deb/org.elasticsearch.packaging.test.DebMetadataTests/test05CheckLintian

**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.packaging.test.DebMetadataTests#test05CheckLintian`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test05CheckLintian'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.packaging.test.DebMetadataTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c lintian --fail-on-warnings /opt/buildkite-agent/builds/bk-agent-prod-gcp-1715342669985179265/elastic/elasticsearch-periodic-packaging/distribution/packages/deb/build/distributions/elasticsearch-8.15.0-SNAPSHOT-amd64.deb]
   result: exitCode = [1] stdout = [W: elasticsearch: shared-lib-without-dependency-information usr/share/elasticsearch/lib/platform/linux-x64/libvec.so
N: 411 tags overridden (191 errors, 166 warnings, 54 info); 5 unused overrides] stderr = [warning: the authors of lintian do not recommend running it with root privileges!
warning: --fail-on-warnings is deprecated]

  at __randomizedtesting.SeedInfo.seed([504DF3A885E5975E:90B36F443F91F2E5]:0)
  at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:143)
  at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
  at org.elasticsearch.packaging.test.DebMetadataTests.test05CheckLintian(DebMetadataTests.java:45)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

**Comment by ldematte** [comment]
Hey @mark-vieira , when this is happened? I thought I fixed this with https://github.com/elastic/elasticsearch/pull/108088/commits/06baf865d4e66be7818c9cad63449f78f30396bf

**Comment by breskeby** [comment]
@ldematte last listed failure in test triage is this one: https://gradle-enterprise.elastic.co/s/m5pzhu7btxmnm/tests/task/:qa:packaging:destructiveDistroTest.default-deb/details/org.elasticsearch.packaging.test.DebMetadataTests/test05CheckLintian?top-execution=1

**Comment by mark-vieira** [comment]
The above linked failure include that commit so it doesn't look like it's been mitigated.

**Comment by mark-vieira** [comment]
It looks like the warning is `shared-lib-without-dependency-information` which is a problem with dependencies not being provided when the binary is being linked. So this is different than the debug symbols issue addressed in https://github.com/elastic/elasticsearch/commit/06baf865d4e66be7818c9cad63449f78f30396bf.

**Comment by ldematte** [comment]
That might be different: `shared-lib-without-dependency-information` 
I see it as a warning, but maybe you are treating warnings as errors?
We actually have no dependency (as seen with ldd), but we do not compile with --nostdclib, which might leave "something" that trips lintian.
Is there a way for me to check lintian quickly on my local machine?

**Comment by mark-vieira** [comment]
FYI, you can build the debian package by just running `./gradlew buildDeb`.

**Comment by mark-vieira** [comment]
On an Apple silicon machine you'll actually want to use `./gradlew buildAarch64Deb`.

**Comment by ldematte** [comment]
I'll need to use x64 lintian/libs.
The aarch64 lib has been in for a while, and has not being tripping lintian for some reason (maybe the x64 version is more strict/more complete)
