### ISSUE TITLE
x-pack-ml binary not getting built while building the elasticsearch from source for s390x

### ISSUE THREAD

**Issue by Megha-Rajanna** [elastic/elasticsearch#108596]
`x-pack-ml` binary not getting built while building the elasticsearch from source for s390x

Below is the command used for building it form source:

`./gradlew :distribution:archives:oss-linux-s390x-tar:assemble --parallel`

```
[root@colonist1 x-pack-ml]# ls
commons-math3-3.6.1.jar                  joni-2.1.29.jar  platform                      plugin-security-test.policy
elasticsearch-grok-7.17.20-SNAPSHOT.jar  LICENSE.txt      plugin-descriptor.properties  super-csv-2.4.0.jar
jcodings-1.0.44.jar                      NOTICE.txt       plugin-security.policy        x-pack-ml-7.17.20-SNAPSHOT.jar
[root@colonist1 x-pack-ml]# pwd
/root/new_elastic/elasticsearch/distribution/archives/oss-linux-s390x-tar/build/distributions/elasticsearch-7.17.20-SNAPSHOT/modules/x-pack-ml
[root@colonist1 x-pack-ml]# cd platform/
[root@colonist1 platform]# ls
[root@colonist1 platform]# pwd
/root/new_elastic/elasticsearch/distribution/archives/oss-linux-s390x-tar/build/distributions/elasticsearch-7.17.20-SNAPSHOT/modules/x-pack-ml/platform
[root@colonist1 platform]# ls -lrt
total 0
[root@colonist1 platform]#
```

**Comment by DaveCTurner** [comment]
Thank you very much for your interest in Elasticsearch. Unfortunately the issue you have reported relates to a platform which is not supported. We will not investigate issues related to unsupported versions here on Github, so I am closing this to indicate that no action is needed from the Elasticsearch development team. It's possible that you will find a volunteer to help you with this issue on the [community forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), but our strong recommendation would be to use a supported platform. If you can reproduce your issue on a supported platform then please open a fresh bug report.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.

**Comment by Megha-Rajanna** [comment]
@DaveCTurner - Thanks for the response. We are working on porting of elasticsearch on s390x platform to get official support. Could you please help us in understanding how and from where `x-pack-ml` binary is getting generated for amd64?

`elasticsearch/distribution/archives/oss-linux-s390x-tar/build/distributions/elasticsearch-7.17.20-SNAPSHOT/modules/x-pack-ml/platform/linux-*/bin/*`

**Comment by DaveCTurner** [comment]
Simply porting Elasticsearch to a new platform is not going to make that platform officially supported, sorry. We have no plans to add support for s390x at this time. It's possible that you will find a volunteer to help you with this issue on the [community forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) but we can't help you here on Github.
