### ISSUE TITLE
API to update node attributes dynamically

### ISSUE THREAD

**Issue by namannigam** [elastic/elasticsearch#108632]
### Description

While trying our hands on an existing production cluster to perform [shard-allocation-filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-allocation-filtering.html). 
I realized [realizing](https://stackoverflow.com/a/78478978/1746118) that the node attributes, if added to a cluster, must be updated during a startup or a restart of each cluster node has to be performed.

Is it convenient and feasible to expose an API for settings to update node attributes and modify them dynamically? In cases, specifically when I want to associate just a label along with my nodes.

**Comment by DaveCTurner** [comment]
Thanks for the suggestion @namannigam. It makes sense as a concept but unfortunately implementing this would be pretty tricky as things currently stand - the decision to make node attributes as they are today was made many years ago and is rather deeply embedded in the code these days. Yet, a rolling restart should not be a particularly difficult thing to do to adjust node attributes. Therefore I think it's very unlikely we'll get around to doing this for the foreseeable future so I'm going to close this issue.
