### ISSUE TITLE
Eliminating results with hate words

### ISSUE THREAD

**Issue by lazywizar** [elastic/elasticsearch#10867]
It would be great to have feature to efficiently filter out docs with hate words in my elasticsearch result. Currently we are having bool filter in every search query for the list of all words.

Preprocessing and NOT indexing the docs with bad words in one solution and another is using a percolator before every query. Both the solutions can not enforce the rule if the index is made by some client out of our control.

It would be great to have a ES level solution for the same.

**Comment by clintongormley** [comment]
@lazywizar this request is very context sensitive.  I suggest that you add an alias to the index with a filter on the hate word, and allow users to search via that alias instead.
