### ISSUE TITLE
[CI] Netty4TransportMultiPortIntegrationIT testThatTransportClientCanConnect failing

### ISSUE THREAD

**Issue by idegtiarenko** [elastic/elasticsearch#108627]
Seems to happen only on 7.17 and windows-2016

**Build scan:**
https://gradle-enterprise.elastic.co/s/76ongcrk2ajce/tests/:modules:transport-netty4:internalClusterTest/org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT/testThatTransportClientCanConnect

**Reproduction line:**
```
gradlew ':modules:transport-netty4:internalClusterTest' --tests "org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT.testThatTransportClientCanConnect" -Dtests.seed=137E95DDC3A21473 -Dtests.locale=ar-TN -Dtests.timezone=Etc/UTC -Druntime.java=21
```

**Applicable branches:**
7.17

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT#testThatTransportClientCanConnect`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testThatTransportClientCanConnect'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([137E95DDC3A21473]:0)

```

**Comment by cbuescher** [comment]
I have another one here on Windows 2016 that seems to result from an OOM. 
https://buildkite.com/elastic/elasticsearch-periodic-platform-support/builds/2768#018f831a-412e-43ef-a692-004c4db0417c

I'm looking at several "7.17 and windows-2016" and just want to link another issue I've just observed here: https://github.com/elastic/elasticsearch/issues/108755

**Comment by pxsalehi** [comment]
Setting to medium risk since this is only on windows2016.

**Comment by DaveCTurner** [comment]
low-risk, just a test bug I think

**Comment by DaveCTurner** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/109590
