### ISSUE TITLE
mapping type long question

### ISSUE THREAD

**Issue by Stabaoc** [elastic/elasticsearch#10866]
I meet a problem . When I index an value , for example `{"id": -8848340816900692111}`,
then i search it ,it shows that `"id": -8848340816900692000`. 
Anyone can help? I want know why does elasticsearch do this and how can i deal with.
Thanks.

**Comment by markwalkom** [comment]
Please join us in #elasticsearch on freenode or on the mailing lists at https://groups.google.com/forum/#!forum/elasticsearch for troubleshooting help, we reserve github for confirmed bugs and feature requests.

**Comment by Stabaoc** [comment]
OK!

**Comment by imotov** [comment]
Most likely a duplicate of #5518.
