### ISSUE TITLE
Does not honor cache sizes changed on the fly

### ISSUE THREAD

**Issue by spuder** [elastic/elasticsearch#10860]
You can use the API to change settings on the fly. 

    PUT /_cluster/settings -d '{ "persistent" : { "indices.breaker.fielddata.limit" : "75%" } }'
    PUT /_cluster/settings -d '{ "persistent" : { "indices.fielddata.cache.size" : "65%" } }'

If you then look at the settings, you will find that the `indices.breaker.fielddata.limit` field was applied, but the cache.size is not. 

```bash
curl -XGET 'elasticsearchpool.example.com:9200/_cluster/settings?pretty'
{
  "persistent" : {
    "indices" : {
      "breaker" : {
        "fielddata" : {
          "limit" : "75%"
        }
      }
    }
  },
  "transient" : {
    "cluster" : {
      "routing" : {
        "allocation" : {
          "enable" : "all"
        }
      }
    }
  }
}
```

Also tried the following requests

    GET /_all/_settings?pretty
    GET /_cluster/settings?pretty
    GET /_stats/fielddata?pretty&fields=*

jpsandiego42 and afx114 in the IRC channel also confirmed that the cache settings don't work when changed on the fly.

**Comment by spuder** [comment]
Related to https://github.com/elastic/cookbook-elasticsearch/pull/314

**Comment by clintongormley** [comment]
The fielddata cache size is not dynamically updatable, which is why it is ignored.  I'm not sure whether it is possible to change this value on the fly without invalidating everything already in the cache, which presumably is why it is not dynamic.

**Comment by jpountz** [comment]
I am currently removing the ability to change the cache size on the filter cache because it added too much complexity (https://github.com/elastic/elasticsearch/pull/10897) so I don't think we should add it on the fielddata cache.

**Comment by jpountz** [comment]
Closing: supporting this would be tricky and very prone to memory leaks due to existing segments referencing old caches through their close listeners.
