### ISSUE TITLE
SHA1/256 functions is only possible to use for String, it's impossible for byte[] in painless

### ISSUE THREAD

**Issue by ser-sergeev** [elastic/elasticsearch#108718]

**Comment by slobodanadamovic** [comment]
Thank you very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by slobodanadamovic** [comment]
@ser-sergeev Apologies, I've interpreted this as a question. This is a correct place to raise an enhancement requests.
And in your case, I believe you could convert the `byte[]` to `String` and then call `sha256()`. Here is what I have in mind:

```
byte[] bytes = doc['myByteField'].value;
StringBuilder stringBuilder = new StringBuilder();
for (int i = 0; i < bytes.length; i++) {
  stringBuilder.append((char)(bytes[i] & 0xFF));
}
return stringBuilder.toString().sha256();
```

**Comment by slobodanadamovic** [comment]
@ser-sergeev I see now that there can be potential issues with wrong encoding. Let me tag the responsible team for painless to get their input on this.

**Comment by jdconrad** [comment]
Closing this as it is unlikely to be prioritized.
