### ISSUE TITLE
Don't try and look for "default-mapping.json" in CWD

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch#10877]
to reproduce:

    wget -O - http://s3-eu-west-1.amazonaws.com/build-eu.elasticsearch.org/origin/master/nightly/JDK7/elasticsearch-latest-SNAPSHOT.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
    /tmp/elasticsearch/bin/elasticsearch

This will break when your cwd is on a different filesystem you get:

     java.security.AccessControlException: access denied ("java.io.FilePermission" "default-mapping.json" "read")

Other way to reproduce is to remove this line:

    permission java.io.FilePermission "${project.basedir}${/}target${/}-", "read"

and instead make it only grant access to target/classes and target/test-classes, then all tests fail trying to read those files from CWD.

I believe the correct solution is not to try and read anything from CWD since that can be anywhere and should not be relevant.

**Comment by rmuir** [comment]
We also try to read elasticsearch.yml from the CWD (at least in tests).

**Comment by tlrx** [comment]
I've done #10721 for this

**Comment by rmuir** [comment]
@tlrx in addition we still have the issue of java code trying CWD in some circumstances, stuff like this logic in Environment.java:

        if (settings.get("path.home") != null) {
            homeFile = PathUtils.get(cleanPath(settings.get("path.home")));
        } else {
            homeFile = PathUtils.get(System.getProperty("user.dir"));
        }

I don't understand how the user's home directory makes sense.

**Comment by rmuir** [comment]
Environment.resolveConfig is the other bad guy. It tries CWD *first* then and only then, looks in configured config/ dir (imagine path="elasticsearch.yml" in this snippet below):

    public URL resolveConfig(String path) throws FailedToResolveConfigException {
        String origPath = path;
        // first, try it as a path on the file system                   <-- TRIES CWD BEFORE ANYTHING ELSE
        Path f1 = PathUtils.get(path);
        ...
        if (path.startsWith("/")) {
            path = path.substring(1);
        }
        // next, try it relative to the config location
        Path f2 = configFile.resolve(path);
        ...
        // try and load it from the classpath directly
        URL resource = settings.getClassLoader().getResource(path);
        if (resource != null) {
            return resource;
        }
        // try and load it from the classpath with config/ prefix
        if (!path.startsWith("config/")) {

**Comment by rmuir** [comment]
created a branch with some commits to clean this up. But there is still more to fix and could use some help (the guice stuff etc a big annoyance here)

https://github.com/elastic/elasticsearch/tree/die_cwd_die

**Comment by clintongormley** [comment]
#10923 has been merged, and we no longer allow file based mappings.  Closing
