### ISSUE TITLE
Improve test quality of org.elasticsearch.index.codec package

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#108706]
This is achieved by improving test coverage and adding test duels for specific codecs.
The following sub packages need increased test coverage:

- [ ] `org.elasticsearch.index.codec.bloomfilter` package.  Currently 90% of lines and 71% of branches tested.
- [ ] `org.elasticsearch.index.codec.postings` package.  Currently 94% of lines and 79% of branches tested.
- [ ] `org.elasticsearch.index.codec.tsdb` package.  Currently 97% of lines and 85% of branches tested.
- [ ] `org.elasticsearch.index.codec.zstd` package.  Currently 93% of lines and 50% (?) of branches tested.

The following classes need increased test coverage:

- [ ] `CodecService`. Currently 81% of lines and 62% of branches tested.
- [ ] `ForUtil`. Currently 93% of lines and 82% of branches tested.
- [ ] `LegacyPerFieldMapperCodec`. Currently 85% of lines and 50% of branches tested.
- [ ] `PerFieldFormatSupplier`. Currently 75% of lines and 61% of branches tested.
- [ ] `PerFieldMapperCodec`. Currently 57% of lines and 50% of branches tested.

Lastly, we should add test duel for a few custom codecs:
- [x] Tsdb doc values codec. Write a test that generates random content and encode this using the default Lucene doc values codec and then by our tsdb doc values codec. Assert that both codecs produce the same output. #108853
- [x] Zstd stored fields. Write a test that generated random content and encode it using Lucene's default stored fields codec and then the zstd codec. Then finally assert that both Lucene indices read the same content. #112048

**Comment by ivamly** [comment]
Hello!

I'm relatively new to open source and would love to contribute to the project. @martijnvg, could I take on this task? Is there anything specific I need to know or do before starting?

I would greatly appreciate any advice, recommendations, and guidance on where to begin and which part of the work might be best to start with. Thank you in advance!

**Comment by lkts** [comment]
Hi @ivamly, thank you for your interest in contributing to Elasticsearch. There is a linked pull request with some improvements that @martijnvg did already. You can use built-in code coverage tooling in IntelliJ to see what is the current state of code coverage of the classes mentioned in the first comment. If you see how code coverage can be increased we'll be happy to accept a pull request.

**Comment by martijnvg** [comment]
Closing as the test duels improved the test coverage.
