### ISSUE TITLE
Add template support to _msearch

### ISSUE THREAD

**Issue by jpotisch** [elastic/elasticsearch#10885]
It would be great if the `_msearch` resource supported template queries or had a `template` subresource to allow multi-search using predefined templates. For example:

```shell
$ cat requests
{"index" : "main"}
{ "template": { "id": "template1" },"params": { "q": "foo" } }
{"index" : "main"}
{ "template": { "id": "template2" },"params": { "q": "bar" } }

$ curl -XGET localhost:9200/_msearch/template --data-binary @requests; echo
```

Instead I either have to make multiple requests to `/_search/template` or take our relatively large search templates and send them as extremely verbose and repetitive ad-hoc requests to `/_msearch`. If `/_msearch` or `/_msearch/template` supported template queries it would allow much cleaner and more efficient multi-search queries, and more consistency between `/_search` and `/_msearch`.

**Comment by s1monw** [comment]
@MaineC can you take a look at this? I will assign it to you

**Comment by MaineC** [comment]
@s1monw Sure. The proposal makes a lot of sense to me.
