### ISSUE TITLE
403 error on Debian repository

### ISSUE THREAD

**Issue by Anthony25** [elastic/elasticsearch#10880]
Hello,
I followed the documentation to use the official repository for Debian Wheezy, but when installing the package `elasticsearch`, I get the error

```
Err http://packages.elasticsearch.org/elasticsearch/1.5/debian/ stable/main elasticsearch all 1.5.2
  403  Sorry, not allowed to fetch that type of file: elasticsearch-1.5.2.deb
Failed to fetch http://packages.elasticsearch.org/elasticsearch/1.5/debian/pool/main/e/elasticsearch/elasticsearch-1.5.2.deb  403  Sorry, not allowed to fetch that type of file: elasticsearch-1.5.2.deb
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Thanks

**Comment by clintongormley** [comment]
Hi @Anthony25 

I can retrieve http://packages.elasticsearch.org/elasticsearch/1.5/debian/pool/main/e/elasticsearch/elasticsearch-1.5.2.deb just fine.  I wonder if it was a temporary glitch?  Would you mind trying again?

**Comment by Anthony25** [comment]
Sorry about my non response, I will test it tomorrow.

Thanks for your answer !

**Comment by Anthony25** [comment]
Sorry for the delay, the repository seems to work now.

Thanks for your answer !
