### ISSUE TITLE
detect_noop should work with bulk update

### ISSUE THREAD

**Issue by sewi-cpan** [elastic/elasticsearch#10881]
#6822 introduced the *detect_noop* option for the Update API. It should be supported in the Bulk API, because bulk updates are much more efficient.

Error during update: Search::Elasticsearch::Error::Unknown params <detect_noop> in <update>.

**Comment by clintongormley** [comment]
@sewi-cpan this is a bug in the Perl client - please open here https://github.com/elastic/elasticsearch-perl/issues

**Comment by nik9000** [comment]
I was going to say that I use it with bulk updates all the time!
