### ISSUE TITLE
Require units for disk-aware allocation

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#10888]
Encountered a customer issue where the operator had set the high- and low- watermarks for disk aware allocation to '98' and '95', thinking they were setting to 98% and 95%.  Elasticsearch read these as 95 bytes and 98 bytes, which led to an out of disk space error when a node was restarted.  We should make units mandatory for this setting to avoid this kind of confusion, or at least enforce sensible settings if units are not specified.

**Comment by s1monw** [comment]
++ thanks sean! @clintongormley can we schedule this for 2.0

**Comment by clintongormley** [comment]
Related to #7633
