### ISSUE TITLE
Optimize error handling after lazy rollovers

### ISSUE THREAD

**Issue by nielsbauman** [elastic/elasticsearch#108838]
Currently, we're looping over all the requests in the bulk request for _each_ failed lazy rollover ([here](https://github.com/elastic/elasticsearch/blob/a2008bd190ec05db4cbd6e3cafd7d5850add647f/server/src/main/java/org/elasticsearch/action/bulk/TransportBulkAction.java#L481), and once https://github.com/elastic/elasticsearch/pull/108108 is merged, we'll do it in `BulkOperation` too). While this is probably around O(n) in practice, it's technically O(n^2), if each document was destined to a different failure store and each rollover failed.

A better alternative would be to collect all the failed rollovers and traverse the documents one time.

**Comment by cam4phor** [comment]
Hi @nielsbauman, may I work on this issue?

**Comment by nielsbauman** [comment]
Hi @cam4phor, sure, go ahead! Thanks for your interest in Elasticsearch :)

**Comment by cam4phor** [comment]
Thanks, I'll update my findings here

**Comment by vishakha-mali** [comment]
well, I'm new on open source.I have seen this project using java but I'm sure where to start.Can anyone help me...

**Comment by Kushal-Dalasaniya** [comment]
Hi @nielsbauman , I have been working on optimizing error handling after lazy rollovers and have raised a PR for this: [PR #111572](https://github.com/elastic/elasticsearch/pull/111572). Additionally, I have signed the contributors' document.

As I am new to open source contributions, I would greatly appreciate any feedback or guidance you can provide to ensure I have addressed this issue thoroughly.
