### ISSUE TITLE
Dynamic mapping for nested objects

### ISSUE THREAD

**Issue by dvdeurse** [elastic/elasticsearch#10882]
Suppose we create an index with the following dynamic mapping in order to indicate that any element starting with 'nested_' should be typed as nested:

```json
{
  "test": {
    "dynamic_templates":[
      {
        "nested_field": {
          "mapping":{
            "type":"nested"
          },
          "match":"nested_*"
        }
      }
    ]  
  }
}
```

If you want to perform a nested query when there is no data in the index yet, we'll get an exception. For example:

```json
{
  "query": {
    "nested": {
      "path": "nested_field",
      "query": {
        "match": {"nested_field.a": "foo"} 
      } 
    }
  }
}
```
would give us a "failed to find nested object under path" exception.

We can avoid this error by declaring the mapping of the nested fields in a static way (instead of dynamic), but then you loose the power of these dynamic templates. 

So my question is: would it be possible to silently ignore these "failed to find nested object under path" exceptions so that it makes sense to declare nested types inside the dynamic templates?

**Comment by clintongormley** [comment]
Hi @dvdeurse 

This idea is being discussed here: https://github.com/elastic/elasticsearch/issues/10415#issuecomment-89832189

I'll close this as a duplicate
