### ISSUE TITLE
Extract XContent API as separate library

### ISSUE THREAD

**Issue by ruckc** [elastic/elasticsearch#10886]
I'm currently using the XContent API from elasticsearch for performant JSON string building for complex object structures.  It would be nice if this API was extracted from the elasticsearch core.

**Comment by clintongormley** [comment]
Hi @ruckc 

Thanks for the suggestion. We've talked about this internally and we'd prefer having this code where we can make changes quickly, without impacting others.  However, it is under an Apache2 license, so you're free to fork it and extract it yourself.
