### ISSUE TITLE
Exists is fast, but Not Exists is slow, because it requires using MustNot

### ISSUE THREAD

**Issue by DR9885** [elastic/elasticsearch#108930]
### Description

Exists is fast, but Not Exists is slow, because it requires using MustNot. And I've heard that MustNot does not perform as well as must.

It would be better to have exists have a "true" or "false" value, so we can use Must.

**Comment by gwbrown** [comment]
Thanks very much for your interest in Elasticsearch.
This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.
There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

**Comment by DR9885** [comment]
@gwbrown, this is not a question. This is a feature request to change how the behavior how "Exists" filter works.

PROBLEM: 
If a user wants to filter not exists, they have to use must_not, which performs slower, because it needs the inverted index
```
"exists": { "field": "user" } // exists
"must_not": { "exists": { "field": "user.id" } } // not exists
```

RECOMMENDED CHANGE:
This would make the Does Not Exists query faster, because it would search the inverted index
```
"exists": { "field": "user", "value":true } // exists
"exists": { "field": "user", "value":false } // not exists
```

**Comment by DR9885** [comment]
opened details in new issue: https://github.com/elastic/elasticsearch/issues/109221
