### ISSUE TITLE
_doc variable

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#108971]
We use the `_doc` name for detecting the doc block in our local planner. We would encounter issues if a variable with the same name exists.

```FROM test | EVAL _doc = length(color) | WHERE _doc == 3 | KEEP _doc,data | LIMIT 5```

The above query fails with:

```
class org.elasticsearch.compute.data.IntVectorBlock cannot be cast to class org.elasticsearch.compute.data.DocBlock 
(org.elasticsearch.compute.data.IntVectorBlock and org.elasticsearch.compute.data.DocBlock are in unnamed module of loader 'app')
```

**Comment by astefan** [comment]
Tested this in the `main` branch now and the issue is not there anymore.
