### ISSUE TITLE
Feature Request: Aggregation on partial field value

### ISSUE THREAD

**Issue by stuartjk1606** [elastic/elasticsearch#10899]
I have a number of different load injector boxes and processes that generate load through our system under test. The tool in use produces masses of logs out but none of it is easily accessible or readable. I am therefore using ELK to process the loads with success, however, presenting some of the data is problematic.

The process names have a structure of:
<process>_<name>_Stress<nn>_Thread_<nn>
but there are around 180 of them. Each process thread generates 1 of 11 different message types. The message types are only distinguishable using a 10 character substring within a field containing strings and semi_colon delimited text and generally in the same location (between character 60 and character 70.

In elasticsearch none of these fields are analysed as this makes the queries and results even messier in Kibana and poses the same problem when choosing analysed elements of a field (only picking element 1&2 or 10-12).

When aggregation is done on either of these fields, "message type" is presented as the long string in the visualisation key with only the first 10-15 characters showing, and "process name" resutls in all 180 processes rather than the 7 process types.

These processes are likely to change over time as we introduce new test scenarios and message types so I do not want to hard code them in just in case we miss something.

Is it possible to have elasticsearch return substrings, partials, lefts, rights etc of a field and group them as such rather than the entire field content so all <process>_<name>a are grouped together and *<msg_type>A* are grouped together? Ideally without code edits to either elastic or kibana? Something in JSON Input such as { "field_length": 10 } or { "partial_start": 60, "partial_for": 15 } would suffice.

**Comment by colings86** [comment]
@stuartjk1606 you could do this with the script option on the terms aggregation. You can use the script to get the value of a particular field and extract a portion of it to be used as the key for the terms bucket as in this example: 

```javascript
DELETE test

POST test/doc/1
{
  "my_field": "string_of_multiple_parts_1"
}
POST test/doc/2
{
  "my_field": "string_of_multiple_parts_2"
}
POST test/doc/3
{
  "my_field": "other1_of_multiple_parts_3"
}
POST test/doc/4
{
  "my_field": "other1_of_multiple_parts_4"
}

# Normal terms agg will return a bucket for each unique term
GET test/_search
{
  "size": 0, 
  "aggs": {
    "my_terms": {
      "terms": {
        "field": "my_field",
        "size": 10
      }
    }
  }
}

# Scripted terms aggregation will return buckets where the key is defined by the output of the script run on each document
GET test/_search
{
  "size": 0, 
  "aggs": {
    "my_terms": {
      "terms": {
        "script": "doc['my_field'].getValue().substring(0,6)", 
        "size": 10
      }
    }
  }
}
```

see this section of the docs for more information on useing scripts with the terms aggregation: http://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-script

and this section for more information about scripting in general with Elasticsearch: http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html

**Comment by stuartjk1606** [comment]
Just to clarify, I am trying to return these in the Kibana front end which does not allow for aggregation via direct scripting that I can see, which I am dissapointed with anyway.

I tried to add this directly to the JSON input in Kibana on the terms "Process" aggregation (no option for "scripted")

>{ "script": "doc['Process'].getValue().substring(0,6)" }

Which returns

"
>>Query Failed [Failed to execute main query]
>>...
>>Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
>>...
>>"

I have also added a partial.groovy script in %elasticsearch%/config/scripts containing both the below lines

>doc[field_name].getValue().substring(partial_start,partial_for)
>doc[Process].getValue().substring(0,6)

Add then again added it to the aggregation json input box while setting Terms to Process

>{ "script_file": "partial",
>"params": {
>    "field_name": "'Process'",
>    "partial_start": 0,
>    "partial_for": 6 }}

Both instances of partial.groovy return GroovyScriptExecutionException[ArrayIndexOutOfBoundsException[null]]

**Comment by colings86** [comment]
@stuartjk1606 I didn't realise you were doing this in Kibana. The first way you described won't work because Kibana only allows Lucene expressions by (for security reasons) which don't support strings, only numeric values. It looks like the script_file approach is working in that it is finding the script and attempting to execute it (hence the GroovyScriptExecutionException) but its erroring during execution, possibly due to getting an empty string back from the `getValue()` method and so throwing an ArrayIndexOutOfBoundsException. Maybe add a check for empty string to your script and also ensure the string length is greater than or equal to 6 before you substring it?

**Comment by clintongormley** [comment]
Be aware that, while scripting allows you to do these kinds of aggregations with data you already have indexed, the query performance will be nowhere near as good as having your data indexed properly.  For instance you could use the `pattern` tokenizer to extract the relevant bits of the string into separate fields:

    DELETE test
    PUT test
    {
      "settings": {
        "analysis": {
          "analyzer": {
            "first_part": {
              "tokenizer": "first_part"
            },
            "second_part": {
              "tokenizer": "second_part"
            }
          },
          "tokenizer": {
            "first_part": {
              "type": "pattern",
              "pattern": "^([^_]+)",
              "group": 1
            },
            "second_part": {
              "type": "pattern",
              "pattern": "^[^_]+_([^_]+)",
              "group": 1
            }
          }
        }
      }
    }
    
    PUT test/_mapping/test
    {
      "properties": {
        "code": {
          "type": "string",
          "index": "not_analyzed",
          "fields": {
            "first": {
              "type": "string",
              "analyzer": "first_part"
            },
            "second": {
              "type": "string",
              "analyzer": "second_part"
            }
          }
        }
      }
    }
    
    POST test/test/_bulk
    {"index":{}}
    {"code":"foo_abc"}
    {"index":{}}
    {"code":"Foo_abc"}
    {"index":{}}
    {"code":"foo_def"}
    {"index":{}}
    {"code":"Foo_def"}
    
    GET /test/_search?size=0
    {
      "aggs": {
        "first": {
          "terms": {
            "field": "code.first"
          },
          "aggs": {
            "second": {
              "terms": {
                "field": "code.second"
              }
            }
          }
        }
      }
    }

**Comment by jilinhao** [comment]
GET logstash-i-2017.11.30/_search?pretty
{
    "aggs" : {
        "destid" : {
            "terms" : {
                "script" : {
                    "source": "doc['destid'].value",
                    "lang": "painless"
                }
            }
        }
    }
}

why?
{
  "error": {
    "root_cause": [
      {
        "type": "parsing_exception",
        "reason": "Unexpected token VALUE_STRING [script] in [destid].",
        "line": 5,
        "col": 29
      }
    ],
    "type": "parsing_exception",
    "reason": "Unexpected token VALUE_STRING [script] in [destid].",
    "line": 5,
    "col": 29
  },
  "status": 400
}
