### ISSUE TITLE
[CI] Netty4TransportMultiPortIntegrationIT testThatTransportClientCanConnect failing

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#108966]
Looks like a deadlock

**Build scan:**
https://gradle-enterprise.elastic.co/s/plcgq7j4qjiyo/tests/:modules:transport-netty4:internalClusterTest/org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT/testThatTransportClientCanConnect

**Reproduction line:**
```
gradlew ':modules:transport-netty4:internalClusterTest' --tests "org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT.testThatTransportClientCanConnect" -Dtests.seed=5D241B68AB9DD92 -Dtests.locale=sr-Latn -Dtests.timezone=Pacific/Apia -Druntime.java=21
```

**Applicable branches:**
7.17

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT#testThatTransportClientCanConnect`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testThatTransportClientCanConnect'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([5D241B68AB9DD92]:0)

```

**Comment by nielsbauman** [comment]
Another occurrence: https://gradle-enterprise.elastic.co/s/flbidijmtrnuk/tests/task/:modules:transport-netty4:internalClusterTest/details/org.elasticsearch.transport.netty4.Netty4TransportMultiPortIntegrationIT/testThatTransportClientCanConnect

**Comment by jfreden** [comment]
Another failure: 
https://buildkite.com/elastic/elasticsearch-periodic-platform-support/builds/2928#018fc7c4-4ddd-44d1-ab4e-fd26b8fb2851

**Comment by mosche** [comment]
Test doesn't exist on main anymore, on 7.17 it's muted.
@thecoop should we just close this?

**Comment by thecoop** [comment]
I'm loath to close something that might be a deadlock, and its muted because the test is failing. However, realistically, we aren't going to look at this. So...probably...

**Comment by DaveCTurner** [comment]
> on 7.17 it's muted.

@mosche where are you seeing this? I think I fixed this test in #109590 and I don't see anything that would be muting it.

**Comment by mosche** [comment]
My bad @DaveCTurner, I didn't refresh

**Comment by mosche** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/109590
