### ISSUE TITLE
Postprocessing for aggregation results

### ISSUE THREAD

**Issue by orangeudav** [elastic/elasticsearch#10895]
Hi! Is there any way to subj? Often i need exclude some agg parts by the condition. Or, can i process (add/remove/modify keys and values) agg results with some groovy script before response to client?

**Comment by jpountz** [comment]
If you only need to remove content, we have this other issue where we are working on allowing to script the selection of returned elements from the response: https://github.com/elastic/elasticsearch/issues/7401

Regarding modifications, there are some ongoing efforts to add the ability to post-process aggregation results. Some of them will be in 2.0, see https://github.com/elastic/elasticsearch/issues/9876 for more information.

I'm closing this issue as I think the two other issues that I pointed to capture the same requirements.
