### ISSUE TITLE
Semantic Text doesn't support OpenAI Text Embeddings

### ISSUE THREAD

**Issue by maxhniebergall** [elastic/elasticsearch#108921]
### Elasticsearch Version

8.15.0-SNAPSHOT; Build date: 2024-05-22T13:38:42.447493535Z  

### Java Version

_bundled_

### OS Version

cloud

### Problem Description

Using the semantic text field with an OpenAI text embedding inference endpoint fails.

```
'status': 400, 'error': {'type': 'status_exception', 'reason': 'Invalid inference results format for field [infer_field] with inference id [my_openai_embedding_model], got chunked_text_embedding_service_float_results'}}}","{'_index': 'big-data-test-index', '_source': {'infer_field': 'Crossotus ugandae adalah spesies kumbang tanduk panjang yang tergolong famili Cerambycidae. Spesies ini juga merupakan bagian dari genus Crossotus, ordo Coleoptera, kelas Insecta, filum Arthropoda, dan kingdom Animalia.'}}"
```
 
This error occurs because the ChunkedTextEmbeddingFloatResults returned by the openAI text embedding inference endpoint is not supported by semantic text:
https://github.com/elastic/elasticsearch/blob/aad04b145598305cecf22fb698bb0603bc5639f3/x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/mapper/SemanticTextField.java#L287

### Steps to Reproduce

using the python client

```
client.inference.put_model(
    task_type="text_embedding",
    inference_id="my_openai_embedding_model",
    body={
        "service": "openai",
        "service_settings": {"api_key": API_KEY},
        "task_settings": {"model": "text-embedding-3-small"},
    }
)

client.indices.create(
    index="big-data-test-index",
    mappings={
        "properties": {
            "infer_field": {
                "type": "semantic_text",
                "inference_id": "my_openai_embedding_model"
            }
        }
    },
)

documents.append(
    {
        "_index": "big-data-test-index",
        "_source": {"infer_field": text['text']},
    }
)

response = helpers.bulk(client, documents, raise_on_error=False, timeout="60s")

```

**Comment by davidkyle** [comment]
Thanks @maxhniebergall, I believe we would have a similar problem if using a service that returns byte embeddings `ChunkedTextEmbeddingByteResults`. I'm looking at how to refactor this to make any `ChunkedTextEmbeddingXXXResults` class compatible

**Comment by carlosdelest** [comment]
Hi @davidkyle ! Let us know about the refactoring outcome so we can plan on implementing compatibility with byte embeddings 👍

**Comment by maxhniebergall** [comment]
fixed by https://github.com/elastic/elasticsearch/pull/109442
