### ISSUE TITLE
not_analyzed field empty vs null for docs before and after some value

### ISSUE THREAD

**Issue by vedil** [elastic/elasticsearch#10905]
I have a dynamic template so that any filed ending with "_r" is not_analyzed
now i use the following curl commands

curl -XPUT 'http://10.0.0.91:9200/twitter/tweet/1' -d '{"user":"user1", "message_r":""}'
curl -XPUT 'http://10.0.0.91:9200/twitter/tweet/2' -d '{"user":"user2", "message_r":"test message"}'
curl -XPUT 'http://10.0.0.91:9200/twitter/tweet/3' -d '{"user":"user1", "message_r":""}'

curl -XGET 'http://10.0.0.91:9200/twitter/tweet/_search?pretty' -d '{"query":{"filtered":{"filter":{"missing":{"field":"message_r"}}}}}'

here i get only one hit, twee/1

curl -XGET 'http://10.0.0.91:9200/twitter/tweet/_search?pretty' -d '{"query":{"filtered":{"filter":{"term":{"message_r":""}}}}}'
here i get one hit, tweet/3

why the difference in the results?

**Comment by dadoonet** [comment]
Super interesting. I don't have an answer yet but here is a full recreation:

```
DELETE twitter
PUT twitter
{
  "mappings": {
    "tweet": {
      "properties": {
        "message_r": {
          "type": "string",
          "index": "not_analyzed"
        }
      }
    }
  }
}
PUT /twitter/tweet/1
{"user":"user1", "message_r":""}
PUT /twitter/tweet/2
{"user":"user2", "message_r":"test message"}
PUT /twitter/tweet/3
{"user":"user1", "message_r":""}
GET /twitter/tweet/_search?pretty
{"query":{"filtered":{"filter":{"missing":{"field":"message_r"}}}}}
GET /twitter/tweet/_search?pretty
{"query":{"filtered":{"filter":{"term":{"message_r":""}}}}}
```

The funny thing is that document 1 does not come back though it has the same content.

**Comment by vedil** [comment]
i think some thing happens after indexing the second doc, there is value for that field, so 1 and 3 are indexed differently

**Comment by dadoonet** [comment]
So this is happening when you have more than one shard.
With a single shard, result is correct:

```
PUT twitter
{
  "settings": {
    "number_of_shards": 1
  }, 
  "mappings": {
    "tweet": {
      "properties": {
        "message_r": {
          "type": "string",
          "index": "not_analyzed"
        }
      }
    }
  }
}
```

It means that the "second" shard does not behave as the first one. 
Tested on 1.5.1. Will upgrade to see if I can reproduce on newer version.
Will also downgrade to see if it's a new bug.

**Comment by vedil** [comment]
that is interesting, i did not try changing the shards, so i am seeing it with 5 shards. the version i am using is 
"version" : {
    "number" : "1.4.0",
    "build_hash" : "bc94bd81298f81c656893ab1ddddd30a99356066",
    "build_timestamp" : "2014-11-05T14:26:12Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.2"
  },

**Comment by dadoonet** [comment]
On 1.4.2, it seems to work well. Going to run more tests

**Comment by dadoonet** [comment]
Ok. It looks like a racing issue. I mean that I can not reproduce anymore on 1.5.1... o_O

**Comment by vedil** [comment]
once you have the tweet/2 rest of the tweets are indexed differently, probably you need to clean up all so that previous mappings are not there.
after indexing twitter/1 when i see mapping i did not see message_r in the properties
after twitter/2 it will be there in mappings.

**Comment by jpountz** [comment]
There is a known issue on Elasticsearch < 1.5.0 which does not generate dynamic mappings for the empty string, which causes issues to the missing and exists filters: https://github.com/elastic/elasticsearch/pull/8329

**Comment by dadoonet** [comment]
I restarted the full test by cleaning first "data" dir. So I don't get why I got also this issue on 1.5.1 cluster but I can't reproduce it anymore now.

**Comment by dadoonet** [comment]
@vedil I can confirm what @jpountz said. If you are using dynamic mappings with 1.4.x, the requests don't give the same results. But with 1.5.x, both requests don't give any result.

When using `not_analyzed`, results are different.

Could you test with a newer version? And also share your dynamic template so I can try to reproduce exactly what you see?

**Comment by vedil** [comment]
here is the mapping that i am using

{
          "string_template": {
            "match": "*_r",
            "match_mapping_type": "string",
            "mapping": {
              "type": "multi_field",
              "fields": {
                "{name}": {
                  "type": "string",
                  "analyzer": "string_lowercase"
                },
                "unanalyzed": {
                  "type": "string",
                  "index": "not_analyzed"
                }
              }
            }
          }
        }

will try on 1.5.x version

**Comment by dadoonet** [comment]
This full script works well on 1.5:

```
DELETE twitter
PUT twitter
{
  "mappings": {
    "tweet": {
      "dynamic_templates": [
        {
          "es": {
            "match": "*_r",
            "mapping": {
              "type": "string",
              "index": "not_analyzed"
            }
          }
        }
      ]
    }
  }
}

PUT /twitter/tweet/1
{"user":"user1", "message_r":""}
PUT /twitter/tweet/2
{"user":"user2", "message_r":"test message"}
PUT /twitter/tweet/3
{"user":"user1", "message_r":""}
GET /twitter/tweet/_search?pretty
{"query":{"filtered":{"filter":{"missing":{"field":"message_r"}}}}}

GET /twitter/tweet/_search?pretty
{"query":{"filtered":{"filter":{"term":{"message_r":""}}}}}
```

The fact is that for the first query `message_r` field is never missing so you don't get any result.
But the second query matches documents 1 and 3.

**Comment by vedil** [comment]
yes with 1.5.2 version i am getting the above mentioned behaviour.
time to upgrade my server :)

**Comment by vedil** [comment]
me wonders @dadoonet how were you able to reproduce the issue in the first place, one difference i see in mappings is i was using multifield and you were not using that :(

**Comment by dadoonet** [comment]
If by "issue" you mean the fact that only one record was returned, I have no idea as I can't reproduce it anymore! 
I guess we can close it, right?

**Comment by vedil** [comment]
yes i am closing it.
