### ISSUE TITLE
please help me change the php code from pagination from + size to search_after

### ISSUE THREAD

**Issue by chongshengdz** [elastic/elasticsearch#109082]
please help me change the php code from pagination from + size to search_after, product_id is the unique id for sorting.

   $start = ($params['page'] - 1) * $params['limit'];
    $body = [
        '_source' => ['product_id','name','categories','category_0_name','category_1_name','model','manufacturer'],
        'query' => $query,
        'from' => $start,
        'size' => $params['limit'],
        'sort' => ['product_id' => ['order' => asc]]
    ];

    $search = [
        'index' => $index,
        //'type' => $type,
        'type' => '_doc',
        'body' => $body
    ];

    $return = [
        'hits' => [],
        'total' => 0,
        'took' => null,
        'filters' => [],
    ];

    try{
        $results = $this->client->search($search);
    }catch(\Exception $e){
        $this->registry->get('log')->write('FATAL: Search failed. Error: '.$e->getMessage());
        return $return;
    }

    $return['took'] = $results['took'];
    $return['timed_out'] = $results['timed_out'];

    $language = $this->session->data['language'];

    if (isset($results['hits']) && count($results['hits'])):
        $return['total'] = $results['hits']['total'];
        $return['hits'] = [];
        $position = 1;
        foreach ($results['hits']['hits'] as $hit):
            $return['hits'][] = $hit['_id'];
            $return['products'][$hit['_id']] = [
                'id' => (int) $hit['_id'],
                'product_id' =>   $hit['_source']['product_id'],
                'name' => $hit['_source']['name'][$language],
                'category_0_name' => isset($hit['_source']['category_0_name'][$language]) ? $hit['_source']['category_0_name'][$language] : '',
                'category_1_name' => isset($hit['_source']['category_1_name'][$language]) ? $hit['_source']['category_1_name'][$language] : '',
                'position' =>   $position,
                'model' =>   $hit['_source']['model'],
                'position_overall' =>   $position + $start,
                'manufacturer' => isset($hit['_source']['manufacturer']) ? $hit['_source']['manufacturer']['name'] : '_none_',
            ];
            $position++;
        endforeach;
    endif;

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by chongshengdz** [comment]
> Thanks very much for your interest in Elasticsearch.
> 
> This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.
> 
> There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

please help me
