### ISSUE TITLE
Memory leak in Elasticsearch v1.5.1

### ISSUE THREAD

**Issue by cold-gin** [elastic/elasticsearch#10906]
Hello. I am running the ELK stack inside of docker. My elasticsearch container has v1.5.1 installed. I am seeing a consistent memory leak while running the elasticsearch container. While running the stack, I do the following:

1.) docker ps
2.) docker inspect {container id of es} (to get pid)
3.) top | grep {pid of es}

If you monitor the process with top while running logspout, performing Kibana searches, etc, the elasticsearch process never gives back any memory and the memory percentage increases gradually over time. Also, I had upgraded from 1.4.0 to 1.5.1 in an attempt to mitigate the problem, as the memory leak exists in 1.4.0 also.

This has become a serious concern as we would like to be able to stand up the ELK stack for QA and PROD, but cannot while the memory leak exists.

Thanks

**Comment by cold-gin** [comment]
Interesting, I don't see the memory leak when I upgrade to v1.5.2, so maybe it's fixed? Looks like the levels dropped after accessing the indices through Kibana, and doing searches against them.. I won't be able to verify this further until early next week, so I will update this issue after I test it and verify that the leak has been corrected. Thanks

**Comment by clintongormley** [comment]
@cold-gin Elasticsearch is never going to give back memory that it uses for the heap.  You can control the size of the heap with ES_HEAP_SIZE (which you should definitely set before starting), plus mlockall etc.

See the docs here for more details: http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html

Elasticsearch also uses some off-heap memory, which may be released back to the OS. I don't believe that anything has changed in related code between 1.4 and 1.5.  I think the most likely thing is that you haven't configured ES correctly yet, and once you do, it will all behave as expected.

I suggest asking further questions on the mailing list instead.  If you do encounter a real memory leak, please reopen this issue.

**Comment by cold-gin** [comment]
Thanks and sorry for any confusion. Whether it is coincidence or not, I would just like to say that when monitoring the elasticsearch container after upgrading to v1.5.2 I definitely do not see the increasing memory usage behavior that I was seeing earlier where the percentage continued to go up. The memory of the container process has definitely stabilized in 1.5.2 and it was definitely growing from 1.4.0 - 1.5.1. Again, just making this observation. Thank you once again for the information, I greatly appreciate it.
