### ISSUE TITLE
Create a new REST endpoint to make the current elected master abdicate to another eligible master node

### ISSUE THREAD

**Issue by DiannaHohensee** [elastic/elasticsearch#109128]
### Description

We have master abdication logic for shutdown. We should create an endpoint to force a master failover, to resolve production problems -- issues caused by networking, or even Elasticsearch issues. This would avoid restarting nodes, which creates downtime, as the only solution to force a failover.

**Comment by DaveCTurner** [comment]
I'd rather not do this I think - such an API would only be useful for working around other bugs we might encounter, and would make it much much harder to pin down and fix such bugs.

**Comment by DiannaHohensee** [comment]
Something like https://github.com/elastic/elasticsearch/issues/99285 might address the production problems instead.
