### ISSUE TITLE
Investigate whether it's possible to allow dots in sparse vector feature names

### ISSUE THREAD

**Issue by tteofili** [elastic/elasticsearch#109118]
Since a dot in ES field names is typically indicating a subfield, we disallowed feature names having dots within `rank_feature` and `sparse_vector` fields. Since we don't usually index sparse vectors as dynamic fields, we might investigate whether it's possible to change this for those field types. In fact when fields are purposely mapped we should be able to allow anything as the input dimension. 

This is related to a customer request we got in this area:
> The rank_features field is giving error if we have a dot(.) in the field. Majority of our keywords like "9 ft. patio umbrella" are giving errors. So want to know is there any workaround to allow the fields having dot...
> i have tried adding "subobjects":false in the mapping for the rank_features field type but its not supported too
> if there is no workaround then I need to figure out what to do...
```
"type": "document_parsing_exception",
    "reason": "[117:13] failed to parse: [rank_features] fields do not support dots in feature names but found [9 ft. patio umbrella]",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "[rank_features] fields do not support dots in feature names but found [9 ft. patio umbrella]"
    }
```

**Comment by kuaikuai** [comment]
Now, how to support dots in rank_features name?
mapping like this:
"properties": {
        "food_rank_score": {
          "type": "rank_features"
        }
}

**Comment by benwtrent** [comment]
This issue was for sparse vectors and did not apply to rank_features
