### ISSUE TITLE
Decaying part of the score

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#10911]
We use an exponential decay that scales only a portion of the score implemented in a [script score](https://github.com/wikimedia/mediawiki-extensions-CirrusSearch/blob/master/includes/Searcher.php#L1401). Specifically, we use it to express the notion that we care some about how old the content is. It works better for news use cases, but here is an example from Wikipedia which I give because its handy:
* [No score decay since edit time](https://en.wikipedia.org/w/index.php?title=Special%3ASearch&profile=default&search=nuclear+program&fulltext=Search)
* [Small portion of score decays with edit time](https://en.wikipedia.org/w/index.php?title=Special%3ASearch&profile=default&search=prefer-recent%3A.1+nuclear+program&fulltext=Search)
* [Most of the score decays with edit time](https://en.wikipedia.org/w/index.php?title=Special%3ASearch&profile=default&search=prefer-recent%3A.9+nuclear+program&fulltext=Search)

It'd be nice if we could do that with a decay function. This:
```js
                     {
                        "exp": {
                           "timestamp": {
                              "origin": "now",
                              "scale": "160d"
                           }
                        }
                     },
```
gets about half the job done, but it doesn't allow me to apply the portion of the scale.

I dug around in the code and didn't see a way to get what I wanted. Any ideas? I'm happy to implement something if it makes sense. Maybe a score function that wraps other score functions?

```js
            {
               "portion": {
                  ".4": "no_change",
                  ".6":
                     {
                        "exp": {
                           "timestamp": {
                              "origin": "now",
                              "scale": "160d"
                           }
                        }
                     }
                  },
               }
            }
```

**Comment by nik9000** [comment]
Or maybe its better to just use Lucene Expression Language for this.

**Comment by nik9000** [comment]
Got it with expression language.

**Comment by clintongormley** [comment]
++  for using scripting here
