### ISSUE TITLE
Access file-based stored search template through API

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#10910]
A file-based search template is currently opened on startup, but does not appear as a stored search template when attempting to list stored templates through the REST or Java API's.  These should be accessible.

**Comment by clintongormley** [comment]
Related to #10713

**Comment by ppf2** [comment]
+1 and also for index templates.  Currently (and as documented), index templates added via config/templates are not included in the _template api output.  This can be confusing to admins.

**Comment by rjernst** [comment]
File based index templates were remove in 2.0: #11052

**Comment by dakrone** [comment]
Since file-based templates were removed in 2.0 I am closing this.
