### ISSUE TITLE
Issue with highlighting on _all field with different analyzers

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch#10914]
Hey there,

Using 1.5.2, there seems to be some sort of issue, or at least confusion about how highlighting works on the `_all` field.

For example, when using dynamic mappings on fields, highlighting works as expected:

```json
DELETE /testhighlightindexdynamic

POST testhighlightindexdynamic/type1/1
{
  "field1": "organization",
  "field2": "organization"
}

POST /testhighlightindexdynamic/_search
{
  "query": {
    "match": {
      "_all": "organization"
    }
  },
  "highlight": {
    "fields": {
      "*": {}
    }
  }
}
```

I get both fields highlighted as expected:

```json
{
   "took": 3,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 0.2712221,
      "hits": [
         {
            "_index": "testhighlightindexdynamic",
            "_type": "type1",
            "_id": "1",
            "_score": 0.2712221,
            "_source": {
               "field1": "organization",
               "field2": "organization"
            },
            "highlight": {
               "field1": [
                  "<em>organization</em>"
               ],
               "field2": [
                  "<em>organization</em>"
               ]
            }
         }
      ]
   }
}
```

However if I use a different analyzer on one of the fields and perform the same search, I no longer get both fields highlighted:

```json
DELETE testhighlightindex

PUT /testhighlightindex
{
  "mappings": {
    "type1": {
      "dynamic": "strict",
      "properties": {
        "field1": {
          "type": "string",
          "analyzer": "snowball"
        },
        "field2": {
          "type": "string",
          "analyzer": "standard"
        }
      }
    }
  }
}

POST testhighlightindex/type1/1
{
  "field1": "organization",
  "field2": "organization"
}

POST /testhighlightindex/_search
{
  "query": {
    "match": {
      "_all": "organization"
      }
  },
  "highlight": {
    "fields": {
      "*": {}
    }
  }
}
```

This returns results with only `field2` highlighted (which is using the standard analyzer):

```json
{
   "took": 5,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 0.2712221,
      "hits": [
         {
            "_index": "testhighlightindex",
            "_type": "type1",
            "_id": "1",
            "_score": 0.2712221,
            "_source": {
               "field1": "organization",
               "field2": "organization"
            },
            "highlight": {
               "field2": [
                  "<em>organization</em>"
               ]
            }
         }
      ]
   }
}
```

It looks like the highlighter code only applies the analyzer of the search field, not the analyzer for the field defined in the mapping?  You can reverse the field that is highlighted in this second case by setting the analyzer on the `_all` field to "snowball".

Is this expected behaviour?

**Comment by javanna** [comment]
I see what happens: the query gets analyzed once with the `_all` analyzer, which gives `organization` as token to highlight. The content of each field to highlight gets retrieved and re-analyzed on-the-fly using the same analyzer that was used at index time (may differ per field). In this specific case `field` is analyzed using `snowball` which produces `organ` as output, thus there is nothing to highlight (`organization` != `organ`).

This is the expected behaviour. This is probably the bigger downside of querying one field and highlighting other fields. Highlighting the same fields that get queried probably makes more sense and solves the issue.
