### ISSUE TITLE
ESQL- Creation of multi-value field on usage of stats command

### ISSUE THREAD

**Issue by 0xR3D4NT** [elastic/elasticsearch#109161]
### Description

Coming from a Cyber-security background of using a different solution, I feel there should be functionality in ESQL "stats" command where aggregation functions should also provide us a way to include "non-grouping" columns forming a mv-field, in the final results when we are grouping them. 

For example : I need a query to give me results of how many and from which locations a successful login activity is observed from a single user account. 
what i am expecting : 
`...
| keep @timestamp, user, activity, outcome, location
| where (activity == login AND outcome==success)
| stats numberOfLocations = distinct_count(location), values(*) by user
...` 

So as per above suggestion i would be able to trigger an alert with a multi-value field "value(location)" which will contain all the location in this aggregation. This v field is generated cz i am grouping by user, and i am including the non-grouping columns in the results.

**Comment by bpintea** [comment]
> aggregation functions should also provide us a way to include "non-grouping" columns

This bit is tracked in this ticket: https://github.com/elastic/elasticsearch/issues/107589

> ... forming a mv-field

This won't happen, but it'll give you all the columns available before the aggregation/`STATS`, so that should be even better.

Will close this as effectively a duplicate, but feel free to reopen if needed.
