### ISSUE TITLE
securitymanager issue with windows temp dir: or at least for @Mpdreamz

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#10925]
As seen on #10887, there is a problem where @Mpdreamz does not have access to java.io.tmpdir somehow. @rjernst has also been running tests in a VM and so far cannot reproduce it.

But I think there may be a sneaky bug. And we need to get to the bottom of it, otherwise the JDK not having access to the default temp dir will cause mayhem in this situation.

**Comment by rmuir** [comment]
@Mpdreamz if you don't mind, could you run this:

    %JAVA_HOME%\bin\java -XshowSettings -version

If this doesnt tell us what is happening, I will make a branch with some debugging logic to track it down.

**Comment by rjernst** [comment]
For comparison, here is mine:
https://gist.github.com/rjernst/bd4886757068c03cefe6

**Comment by gmarz** [comment]
For comparison, since I'm not able to reproduce this either, here's the output of mine: https://gist.github.com/gmarz/23ba9c3b7635bc3ccac7

**Comment by Mpdreamz** [comment]
here's mine https://gist.github.com/anonymous/7d8f6ea699a0cd292562

**Comment by rjernst** [comment]
I was able to recreate this issue by creating a temp dir exactly as @Mpdreamz has (`C:\Users\mpdreamz\AppData\Local\Temp`), setting `TMP` and `TEMP`, and running elasticsearch. I was then able to do it with an arbitrary temp dir (`C:\dev\temp`).

**Comment by rjernst** [comment]
And now it stopped reproducing...

**Comment by gmarz** [comment]
@rjernst I can consistently reproduce this as well by setting `TMP` and `TEMP` to anything other than `%USERPROFILE%\AppData\Local\Temp`

**Comment by gmarz** [comment]
In @Mpdreamz's settings, the user is hard coded: 

` java.io.tmpdir = C:\Users\mpdreamz\AppData\Local\Temp\`

Is `mpdreamz` the actual user you're running as?

**Comment by rmuir** [comment]
@gmarz when you set those environment variables, how does it reflect in java.io.tmpdir? Can you set them and run -XshowSettings -version again?

fyi I created a branch with additional debugging: https://github.com/rmuir/elasticsearch/tree/eight_point_three

**Comment by gmarz** [comment]
Setting `TMP`/`TEMP` to `C:\temp` yields:

`java.io.tmpdir = C:\temp\`

as expected.  Here's the full output: https://gist.github.com/gmarz/2a76c7c2312a11a22347

**Comment by rmuir** [comment]
@gmarz thank you.

my current suspicion is (as silly as this seems) some crazy bug involving the extra trailing slash there. See how java.home or other properties don't have that? 

Can you try from the latest commit here and see if my hack prevents the issue? I just want to rule that out:

https://github.com/rmuir/elasticsearch/tree/eight_point_three

If it fails on startup, I will try a different hack.

**Comment by gmarz** [comment]
@rmuir still fails.  Here's the output with your added debugging: https://gist.github.com/gmarz/5b229eea3f179d2cc9c5

**Comment by rmuir** [comment]
Thank you @gmarz ! Now the problem is clear:

     ("java.io.FilePermission" "C:\Users\GREGM_~1\AppData\Local\Temp\" "read,write")
     ("java.io.FilePermission" "C:\Users\GREGM_~1\AppData\Local\Temp\-" "read,write,delete")
     ("java.io.FilePermission" "C:\Users\GREGM_~1\AppData\Local\Temp\\-" "read,write,delete")

yet

    access denied ("java.io.FilePermission" "C:\temp\7019676636582904207.tmp"

So somehow java.io.tmpdir is a chameleon.

**Comment by gmarz** [comment]
Ah, that's interesting.  Nice catch!

**Comment by gmarz** [comment]
I wonder though how it still knows about `C:\Users\GREGM_~1\AppData\Local\Temp\` though considering it's not in any environment variable.

**Comment by rmuir** [comment]
JDK code uses GetTempPathW (https://msdn.microsoft.com/en-us/library/windows/desktop/aa364992%28v=vs.85%29.aspx) to initialize it, and that function can use USERPROFILE to derive it in some cases. But it makes no sense to me... Can you change this USERPROFILE to something else as a hack and see if it reflects in logs?

**Comment by gmarz** [comment]
I changed `USERPROFILE` to `C:\foo`.  Doesn't look like it's being reflected anywhere: https://gist.github.com/gmarz/36b2869da353b5f4a734

**Comment by rmuir** [comment]
Thanks for trying. I am going to stare at some of the code involved and maybe add some more debugging commits. I'll remove the extra-slash-hack as that is unrelated here. I really want to try to figure out where it gets C:\Users\GREGM_~1\... from

**Comment by rmuir** [comment]
Fixed by #10965
