### ISSUE TITLE
must filter is not working as expected

### ISSUE THREAD

**Issue by mjspka** [elastic/elasticsearch#10927]
1. I have two types of documents indexed in elasticsearch. One is of type, "SERVICE_OFFERING" and the second one is of type, "SUBSCRIPTION.". You can see the screenshot of this in the below image.

![image](https://cloud.githubusercontent.com/assets/12202653/7435879/b1af2718-effc-11e4-9543-431167c17c66.png)

2. Now if I query based on catalogId I am getting results back.

Elasticsearch TRACE: 2015-05-01T19:25:00Z
  -> POST http://localhost:9201/inventory/_search
  {
    "query": {
      "query_string": {
        "fields": [
          "serviceType",
          "displayName",
          "description",
          "*.displayName",
          "*.description",
          "*.value"
        ],
        "query": "vm"
      }
    },
    "filter": {
      "bool": {
        "should": [
          {
            "term": {
              "catalogId": "90d9650a36988e5d0136988f03ab000f"
            }
          },
          {
            "term": {
              "catalogId": "fb2881884b787853014b7ada21670004"
            }
          }
        ]
      }
    },
    "size": "1",
    "from": "0"
  }
  <- 200
  {
    "took": 4,
    "timed_out": false,
    "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
    },
    "hits": {
      "total": 8,
      "max_score": 0.7508366,
      "hits": [
        {
          "_index": "inventory",
          "_type": "subscription",
          "_id": "90e72e034ce89baf014ce8c0f8d20140",
    .....
    .....

3. But if I am doing query based on catalogId and docType then I not seeing any results.

Elasticsearch TRACE: 2015-05-01T19:27:08Z
  -> POST http://localhost:9201/inventory/_search
  {
    "query": {
      "query_string": {
        "fields": [
          "serviceType",
          "displayName",
          "description",
          "*.displayName",
          "*.description",
          "*.value"
        ],
        "query": "vm"
      }
    },
    "filter": {
      "bool": {
        "should": [
          {
            "term": {
              "catalogId": "90d9650a36988e5d0136988f03ab000
            }
          },
          {
            "term": {
              "catalogId": "fb2881884b787853014b7ada2167000
            }
          }
        ],
        "must": [
          {
            "term": {
              "docType": "SUBSCRIPTION"
            }
          }
        ]
      }
    },
    "size": "1",
    "from": "0"
  }
  <- 200
  {
    "took": 3,
    "timed_out": false,
    "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
    },
    "hits": {
      "total": 0,
      "max_score": null,
      "hits": []
    }
  }

Elasticsearch DEBUG: 2015-05-01T19:27:08Z
  Request complete

As per elasticsearch documentation, The must filter should return the documents where it matches along with should filter.

4. Now I have used the query with must filter only as follows. I still do not see any results.

Elasticsearch TRACE: 2015-05-01T19:28:46Z
  -> POST http://localhost:9201/inventory/_search
  {
    "query": {
      "query_string": {
        "fields": [
          "serviceType",
          "displayName",
          "description",
          "*.displayName",
          "*.description",
          "*.value"
        ],
        "query": "vm"
      }
    },
    "filter": {
      "bool": {
        "should": [],
        "must": [
          {
            "term": {
              "docType": "SUBSCRIPTION"
            }
          }
        ]
      }
    }
  }
  <- 200
  {
    "took": 2,
    "timed_out": false,
    "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
    },
    "hits": {
      "total": 0,
      "max_score": null,
      "hits": []
    }
  }

Elasticsearch DEBUG: 2015-05-01T19:28:46Z
  Request complete

FYI: The build information of elasticsearch that I am using is as follows,
{
  "status" : 200,
  "name" : "Human Torch",
  "cluster_name" : "pmalla-lt-csa-c28",
  "version" : {
    "number" : "1.4.3",
    "build_hash" : "36a29a7144cfde87a960ba039091d40856fcb9af",
    "build_timestamp" : "2015-02-11T14:23:15Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.3"
  },
  "tagline" : "You Know, for Search"
}

I would appreciate if you can get back to me at the earliest.

**Comment by dadoonet** [comment]
Typically a usage problem and a misunderstanding on how a search engine works.
`SUBSCRIPTION` has been indexed as `subscription`. You can't find `SUBSCRIPTION` term.

Please use the mailing list if you have any follow up question.
I recommend also reading this chapter: http://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-analysis.html

Closing as not an issue.

**Comment by mjspka** [comment]
Thank you.
