### ISSUE TITLE
Refactor ESQL optimizer rules

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#109215]
Split the `OptimizerRules` class and associated tests into individual top level classes and single-class test files.

Right now, the `OptimizerRules` class is over 1000 lines long, and has another 1000+ lines in core, and all it does is wrap many small static classes.  Those should all be pulled up to the top level, and have individual test files, so it's clearer what our coverage gaps are.

**Comment by astefan** [comment]
I think this is complete with [PR1](https://github.com/elastic/elasticsearch/pull/112338), [PR2](https://github.com/elastic/elasticsearch/pull/112589), [PR3](https://github.com/elastic/elasticsearch/pull/110654), [PR4](https://github.com/elastic/elasticsearch/pull/110728), [PR5](https://github.com/elastic/elasticsearch/pull/109644) (and maybe others) merged.

Other work that is related, but far more involved than the regular approachable refactoring, is captured in [this comment](https://github.com/elastic/elasticsearch/pull/112589#issuecomment-2338226178) about moving the majority of the remaining test methods in individual files with time and when working on specific areas. This work requires much more targeted knowledge about optimization rules and which tests are related more to a specific rule than others.
