### ISSUE TITLE
Primary shards with `index.shared_filesystem` should be able to be recovered by any node

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#10932]
When a cluster using `index.shared_filesystem` lose its copy of the primary shard, we currently don't allocate the shard because ES doesn't think the data exists anywhere else.

It would be nice if Elasticsearch knew that the index existed on shared storage and allowed the primary shard to be allocated to a different node in the cluster in the case that no node has a copy of the shard state.

**Comment by s1monw** [comment]
++
