### ISSUE TITLE
[Logging] Enhance error logging to include index name during field limit exceedance

### ISSUE THREAD

**Issue by Rassyan** [elastic/elasticsearch#109337]
## **Issue Summary:**
Current error logs do not specify the index name when the field count exceeds the limit, impeding quick issue identification.

## **Detailed Description:**
The `DocumentParsingException` for field limit exceedance lacks critical information regarding the index affected. This omission complicates troubleshooting in environments with numerous indices.

**Error Log Snippet:**
```
[o.e.x.m.e.l.LocalExporter] unexpected error while indexing monitoring document org.elasticsearch.xpack.monitoring.exporter.ExportException: org.elasticsearch.index.mapper.DocumentParsingException: [-1:2376] failed to parse: Limit of total fields [1000] has been exceeded while adding new fields [13] at org.elasticsearch.xpack.monitoring.exporter.local.LocalBulk.lambda$throwExportExceptions$2(LocalBulk.java:128)...
```

## **Suggested Enhancement:**
Amend the logging within `LocalBulk` to append the index name to the error message, following the node identifier.

**Desired Log Output:**
```
[o.e.x.m.e.l.LocalExporter] [node_id] [index_name] ...failed to parse: Limit of total fields [1000] exceeded...
```

## **Impact:**
This change will streamline the process of identifying and rectifying field-related configuration issues.

## **Additional Information:**

**Log Screenshot:**
Attached is a screenshot of the error log indicating the field limit exceedance without specifying the index name. This visual evidence supports the need for enhanced error logging.

![image](https://github.com/elastic/elasticsearch/assets/26055883/b7a38e46-3ed0-4083-8cad-8a570ee84022)

**Confirmed Index with Exceeded Field Limit:**
Upon investigation, the index that has exceeded the field limit of 1000 is `.internal.alerts-observability.logs.alerts-default-000001`. This information was determined through manual inspection and should ideally be part of the automated error logging for faster resolution.

I am open to further discussion on this matter and willing to contribute to its resolution.

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
