### ISSUE TITLE
Split brain problem in 2 node elasticsearch cluster

### ISSUE THREAD

**Issue by gouravdhelaria** [elastic/elasticsearch#10935]
Version: 1.4. 
Say there are 2 nodes X and Y, both capable of becoming master. 
When network goes down, both nodes get disconnected from each other and assume the responsibility of master. 
When network is restored, they don't ping each other and form a cluster.

Elasticsearch service has to be restarted on any one of the nodes for them to form a cluster. Even after they form a cluster, all primary shards remain on one node ( on which the service was restarted ), and all replica shards are on the other node.

**Comment by markwalkom** [comment]
Take a look through this page in the docs, in particular `minimum_master_nodes` -  http://www.elastic.co/guide/en/elasticsearch/guide/current/_important_configuration_changes.html. This sort of situation is also why we recommend having an uneven number of master eligible nodes.

This isn't a bug though, if you have other problems like this then please raise them on the mailing list - https://groups.google.com/forum/#!forum/elasticsearch

**Comment by gouravdhelaria** [comment]
Moving to forum:
https://groups.google.com/forum/#!topic/elasticsearch/QavwaaYcSEY
