### ISSUE TITLE
LOOKUP shouldn't duplicate the output if the same field was already present in the input

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#109392]
### Description

This is a follow up to [LOOKUP work](https://github.com/elastic/elasticsearch/pull/107987#discussion_r1625832750) where, if there is a field with a name identical to the one LOOKUP introduces, both of them appear in the results. We need to be consistent here and:
- only one of the fields should be in the results
- that field should be the one introduced by LOOKUP (same approach is being used by the ENRICH command)

**Comment by nik9000** [comment]
I don't believe both appear in the results:
```
// Makes sure the LOOKUP squashes previous names 
doesNotDuplicateNames
required_capability: lookup
FROM employees
| SORT emp_no
| LIMIT 4
| RENAME languages.long AS long
| EVAL name = CONCAT(first_name, " ", last_name)
| LOOKUP long_number_names ON long
| RENAME long AS languages
| KEEP emp_no, languages, name
;

emp_no:integer | languages:long | name:keyword
         10001 |              2 | two
         10002 |              5 | five
         10003 |              4 | four
         10004 |              5 | five
;
```

At least, not in the code as it stands as of yesterday. The LOOKUP result wins. Now, the column pruning happens too late which is a problem, but the output presently looks ok.

Also, I might be doing it in a weird way. The QL rules are indeed complex.

**Comment by astefan** [comment]
@nik9000 the query I was looking at few hours ago is much simpler:

```
{
    "query": "ROW int = 5, name = 123 | LOOKUP int_number_names ON int",
    "tables": {"int_number_names": {"int:integer": [0,1,2,3,4,5,6,7,8,9,10], "name:keyword": ["zero","one","two","three","four","five","six","seven","eight","nine","ten"]}}
}
```

The result I got:

```
      int      |     name      |     name      
---------------+---------------+---------------
5              |123            |five           
```

**Comment by nik9000** [comment]
neat!
