### ISSUE TITLE
Need new filter should_not

### ISSUE THREAD

**Issue by DR9885** [elastic/elasticsearch#109379]
### Description

Need new filter should_not, this will be much cleaner than the current one. Plus it would put less weight on the network traffic.

Current Way to do this.
```
{
  "bool": {
     "should": {
        "bool": {
           "must_not": {
              "match": {
                 "fieldA": "Foo"
              }
           }
        },
        "bool": {
           "must_not": {
              "match": {
                 "fieldB": "Bar"
              }
           }
        }
     }
  }
}
```

Recommended way to do this
```
{
  "bool": {
    "should_not": {
      "match": {
        "fieldA": "Foo"
      }
      "match": {
        "fieldB": "Bar"
      }
    }
  }
}
```

**Comment by javanna** [comment]
I am not sure about the advantages and usecases of what you are proposing. It seems to me that it would not be very commonly used, and increases the already wide surface of the query DSL, especially given that there's an existing way to achieve what you want.

**Comment by benwtrent** [comment]
Agreed, I think the true answer here is to better optimize `not` to handle performance problems.

Closing as won't do
