### ISSUE TITLE
[DOCS] Conflicting definition of `index.time_series.start_time`

### ISSUE THREAD

**Issue by consulthys** [elastic/elasticsearch#109331]
### Elasticsearch Version

8.13

### Installed Plugins

-

### Java Version

_bundled_

### OS Version

-

### Problem Description

In the TSDS official documentation, there are two conflicting definitions of `index.time_series.start_time`.

In the [**Look-back time** section](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html#tsds-look-back-time), it is stated:

> When you create a data stream for a TSDS, Elasticsearch calculates the index’s `index.time_series.start_time` value as:
> `now - index.look_back_time`
> `                 ^^^^`

In the next section titled [**Accepted time range for adding data**](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html#tsds-accepted-time-range), it is stated:

> When the TSDS is first created the initial backing index has: an `index.time_series.start_time` value set to 
> `now - index.look_ahead_time`
> `                 ^^^^^`

### Steps to Reproduce

Compare the two following sections of the TSDS documentation, specifically the definition of `index.time_series.start_time`:
1. [Look-back time](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html#tsds-look-back-time)
2. [Accepted time range for adding data](https://www.elastic.co/guide/en/elasticsearch/reference/current/tsds.html#tsds-accepted-time-range)

**Comment by lkts** [comment]
Thanks for the report.
