### ISSUE TITLE
Synthetic source and source-only snapshots testing

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#109333]
### Description

[Source-only repositories](https://www.elastic.co/guide/en/elasticsearch/reference/current/snapshots-source-only-repository.html) store source-only snapshots and allows users to reduce storage usage when using snapshots.
Source-only snapshots store only metadata and stored fields (the `_source` field is stored), while doc values and inverted indices are not stored. Source-only snapshots are only supported if the `_source` field is enabled and no source-filtering is used.

For index modes using synthetic source by default, like `tsdb` and `logsdb`, we need to make sure we have a path allowing users to still use source-only snapshots by reindexing or directly supporting at least a limited set of queries (match_all and get). Such snapshots normally need reindexing to be searchable.

**Comment by martijnvg** [comment]
Test was added and behavior is as expected.
