### ISSUE TITLE
Support multiple clusters in marvel

### ISSUE THREAD

**Issue by clly** [elastic/elasticsearch#10931]
I came across a mailing list entry here (http://elasticsearch-users.115913.n3.nabble.com/Marvel-monitoring-multiple-ES-clusters-by-one-Monitoring-ES-cluster-td4053005.html) where you say that a single marvel instance isn't able to support monitoring multiple clusters.  I've had trouble but it still kindof works if you filter them down.  

I'm wondering when this is planned, if it's still planned, and if not, if is it possible to create separate per cluster indexes so that I can at least switch between cluster indexes?

**Comment by clintongormley** [comment]
Hi @clly 

I believe it is still planned, but for the moment you need separate marvel installs.  I'll leave this for @bleskes to comment on in more detail.

**Comment by bleskes** [comment]
@clly it is high on the agenda to support multiple cluster in the next major version of  Marvel. However, we plan to rewrite Marvel to take use of the latest and best available today (most notably Kibana 4) which means it will take some time... 

The current UI kinda works if you know what you're doing but it can be very confusing and break subtly in some places, which why we say it's not supported.

I'm going to close this for now - we are tracking this and it will take time so I don't feel it's worth it to keep it open here.

Let me know if you have any question
