### ISSUE TITLE
REST: Calling `_anything` returns confusing error message

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#10946]
Using any non reserved string starting with an underscore results in an `IllegalArgumentException`, maybe we should add a more useful error message here like `unknown request` instead of `no feature for name`. The 4xx HTTP is fine already.

```
# curl 'localhost:9200/_siohgjoidfhjfihfg?pretty'
{
  "error" : {
    "root_cause" : [ {
      "type" : "illegal_argument_exception",
      "reason" : "No feature for name [_siohgjoidfhjfihfg]"
    } ],
    "type" : "illegal_argument_exception",
    "reason" : "No feature for name [_siohgjoidfhjfihfg]"
  },
  "status" : 400
}
```

**Comment by javanna** [comment]
This happens because such a request gets interpreted as a get index request with no index nor type, and the expression that starts with '_' is seen as a potential feature to filter out the output (e.g. `_aliases` etc.). This is odd, I agree we should fix it.

**Comment by s1monw** [comment]
at least you can read the error now :)

**Comment by javanna** [comment]
> at least you can read the error now :)

right, that's some beautiful structured output :)
