### ISSUE TITLE
Java API documentation - refresh API

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch#10942]
There doesn't appear to be any documentation for the Java API on how to use the refresh API to say, force an index to refresh.

I can see code for using `client().admin().indices().prepareRefresh()` within the test suite but I'm unsure if this is the right/only way to initiate an index refresh.

**Comment by dadoonet** [comment]
I'll add it shortly after #15713. 

Some examples that will be added to the guide soonish:

```java
// Refresh all indices
client.admin().indices().prepareRefresh().get();

// Refresh one index
client.admin().indices().prepareRefresh("twitter").get();

// Refresh many indices
client.admin().indices().prepareRefresh("twitter", "company").get();
```
