### ISSUE TITLE
can't create index start with "logstash-"

### ISSUE THREAD

**Issue by zitang** [elastic/elasticsearch#10947]
I used to use elasticsearch & logstash to manage log, but today I found the logstash related index can't be created.

Then I try to create an index with "logstah-" prefix manually, it failed:
```
curl -XPUT localhost:9200/logstash-a

{
    "error":"MapperParsingException[mapping [“date”]]; nested: MapperParsingException[Root type mapping not empty after parsing! Remaining fields:   [“store” : true]]; ","status":400
}
```

If I create a index with other prefix, it works:
```
curl -XPUT localhost:9200/logstash_a

{
    "acknowledged":true
}
```

Any idea on it? Thanks.

**Comment by dadoonet** [comment]
I just tested it on 1.5.1 and everything is working.
I think you have a bad index template somewhere?

So when elasticsearch tries to apply it it fails with this error?

Any chance you can share all the information? How you reproduce that?

**Comment by zitang** [comment]
sorry, I've found the reason,
I've ran a script to create some index templates, one template is conflict with logstash template, both templates are:

"template" : "logstash-*",

After delete this template, it works.
