### ISSUE TITLE
Unable to correctly query data using 'query_string'

### ISSUE THREAD

**Issue by LiJie20190102** [elastic/elasticsearch#109434]
### Elasticsearch Version

7.17.21

### Java Version

21.0.2

### OS Version

3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

I use "search profile" to obtain the analysis results. I obtained all the "MultiTermQueryConstantScoreWrappers", and I used each "MultiTermQueryConstantScoreWrapper" separately to obtain the data. However, when I used all the "MultiTermQueryConstantScoreWrappers", I could not obtain the correct results

### 1.   prepare data

`PUT user_aaa
{
  "mappings": {
    "properties": {
      "address": {
        "type": "text",
        "index": false
      },
      "age": {
        "type": "long"
      },
      "name": {
        "type": "text"
      }
    }
  }
}

PUT user_aaa/_doc/1
{
  "name":"04V5:J20240506104423001!1!130322198402082311"
}

PUT user_aaa/_doc/2
{
  "name":"04V5!J20240506104423001!1!130322198402082311"
}

`

### 2.    search script

`GET user_aaa/_search?
{
  "query": {
    "query_string": {
      "query": "04V5*!J20240506104423001*!1*!130322198402082311*",
      "fields": ["name"]
    }
  }
}`

at this time, data cannot be queried

### 3.    kibana 'Search Profile'
![image](https://github.com/elastic/elasticsearch/assets/53458004/7cd8f6a3-d752-45a6-962c-74d485b20eaa)

### 4.    When "query" is "04v5 *", "1 *", "j2024050610423001 *", "130322198402082311 *", data can be searched, and all are MultiTermQueryConstantScoreWrappers. However, when "query" is "04V5 *! J2024050610423001 *! 1 *! 130322198402082311 *", data cannot be searched
![image](https://github.com/elastic/elasticsearch/assets/53458004/a55f5c90-d290-426d-bca0-461de4925d84)

![image](https://github.com/elastic/elasticsearch/assets/53458004/73f7f664-2e5a-4e3e-a224-77882123f176)

**Comment by benwtrent** [comment]
`!` indicates `NOT` in query_string. You might want to escape it if you don't want it to be parsed as such: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_boolean_operators



Additionally, the indexed terms with the default analyzer will actually be:
```
{
  "tokens": [
    {
      "token": "04v5",
      "start_offset": 0,
      "end_offset": 4,
      "type": "<ALPHANUM>",
      "position": 0
    },
    {
      "token": "j20240506104423001",
      "start_offset": 5,
      "end_offset": 23,
      "type": "<ALPHANUM>",
      "position": 1
    },
    {
      "token": "1",
      "start_offset": 24,
      "end_offset": 25,
      "type": "<NUM>",
      "position": 2
    },
    {
      "token": "130322198402082311",
      "start_offset": 26,
      "end_offset": 44,
      "type": "<NUM>",
      "position": 3
    }
  ]
}
```

So, I am not sure you want the `!` at all in your query?
