### ISSUE TITLE
Improved IDE support for Elastic

### ISSUE THREAD

**Issue by ryanhamilton** [elastic/elasticsearch#109471]
### Description

Hi,
I'm the author of qStudio, a Free SQL IDE that includes drivers for Elastic Search.
https://www.timestored.com/qstudio/

I'm looking for someone to test the driver.
Ideally they would try querying every data type and check that the server tree populates.

I'm trying to build a Free SQL tool that supports every database but testing everyone myself takes hours so I'm asking for help where possible.

Thanks,

![image](https://github.com/elastic/elasticsearch/assets/7273208/f77cfa2c-2a7a-4090-a9f9-c541168b9ca0)

**Comment by gwbrown** [comment]
Hi, thanks for your interest in Elasticsearch. We like to keep issues in this repository reserved for bug reports and feature requests, which is important with the high volume of issue traffic. As such, I'm going to close this issue. If you have a request for a change to Elasticsearch, please open a new ticket, or for questions, there's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer.
