### ISSUE TITLE
Problem with _site plugin using 1.5.2

### ISSUE THREAD

**Issue by jettro** [elastic/elasticsearch#10958]
Hi after the upgrade from 1.5.1 to 1.5.2 the site plugins break. I keep getting 404 for all plugins. I do not have the most common setup, but it is not strange as well. I have my plugins in a separate folder and that does not seem to work. I use a script to startup a node:

```
#!/bin/bash

NODE=idmc

CURRENT_PROJECT=$(pwd)
CONFIG=$CURRENT_PROJECT/config
DATA=$CURRENT_PROJECT/data
LOGS=$CURRENT_PROJECT/logs
PLUGINS=$CURRENT_PROJECT/../../plugins/

BASH_ES_OPTS="-Des.config=$CONFIG/elasticsearch.yml -Des.path.conf=$CONFIG -Des.path.data=$DATA -Des.path.logs=$LOGS -Des.path.plugins=$PLUGINS"

ELASTICSEARCH=$HOME/javalibs/elasticsearch/elasticsearch-1.5.2

$ELASTICSEARCH/bin/elasticsearch $BASH_ES_OPTS
```
If I change the ELASTICSEARCH parameter to 1.5.1 it works. Any problem with the -Des.path.plugins and the security fix for 1.5.2?

Thanks Jettro

**Comment by clintongormley** [comment]
Hi @jettro 

Setting `PLUGINS` to an absolute path should fix this.

@spinscale perhaps we should be be converting the plugin path to absolute before we use it?

**Comment by jettro** [comment]
Sorry for the delay, did not have the right laptop with me to try it out.
But I change the configuration to an absolute path and the result is the
same. Going to try to create a test to show the problem, but since elastic
has become kind of big I am not sure I can do it soon :-)

Thanks, so far,
Jettro

On Mon, May 4, 2015 at 5:23 PM, Clinton Gormley <notifications@github.com>
wrote:

> Hi @jettro <https://github.com/jettro>
>
> Setting PLUGINS to an absolute path should fix this.
>
> @spinscale <https://github.com/spinscale> perhaps we should be be
> converting the plugin path to absolute before we use it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch/issues/10958#issuecomment-98750789>
> .
>



-- 
Jettro Coenradie
http://www.gridshore.nl

**Comment by spinscale** [comment]
@jettro can you just paste the configuration you used with an absolute path, that failed as well? I am happy to do the rest.

**Comment by jettro** [comment]
Went over all the steps once more and I now have a working configuration.

PLUGINS=/Users/jettrocoenradie/javalibs/elasticsearch/plugins

BASH_ES_OPTS="-Des.config=$CONFIG/elasticsearch.yml -Des.path.conf=$CONFIG
-Des.path.data=$DATA -Des.path.logs=$LOGS -Des.path.plugins=$PLUGINS"

ELASTICSEARCH=$HOME/javalibs/elasticsearch/elasticsearch-1.5.2

Usually I have the following line:
PLUGINS=$CURRENT_PROJECT/../../plugins

That fails, most likely due to the ../../ in there

But the exact path for PLUGINS does work.

regards Jettro

**Comment by spinscale** [comment]
thanks for the reproduction. the PR referenced in here will fix that problem.

right now the easiest workaround is to use absolute paths... or call some specific function to get the absolute path before passing to elasticsearch, like

```
abspath () { case "$1" in /*)printf "%s\n" "$1";; *)printf "%s\n" "$PWD/$1";; esac; }
```

**Comment by jbrablec** [comment]
tried this under cygwin with above
eg.
CURRENT_PROJECT=$(pwd)
CONFIG=$CURRENT_PROJECT/config
bin/elasticsearch "-Des.config=$CONFIG/elasticsearch.yml"
{1.5.1}: Setup Failed ...
- FailedToResolveConfigException[Failed to resolve config path [/elk/elasticsearch/config/elasticsearch.yml], tried file path [\elk\elasticsearch\config\elasticsearch.yml], path file [C:\cygwin\elk\elasticsearch\config\elk\elasticsearch\config\elasticsearch.yml], and classpath]
org.elasticsearch.env.FailedToResolveConfigException: Failed to resolve config path [/elk/elasticsearch/config/elasticsearch.yml], tried file path [\elk\elasticsearch\config\elasticsearch.yml], path file [C:\cygwin\elk\elasticsearch\config\elk\elasticsearch\config\elasticsearch.yml], and classpath
        at org.elasticsearch.env.Environment.resolveConfig(Environment.java:213)
        at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareSettings(InternalSettingsPreparer.java:68)
        at org.elasticsearch.bootstrap.Bootstrap.initialSettings(Bootstrap.java:112)
        at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:183)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)


-- this path exist "/elk/elasticsearch/config/elasticsearch.yml"

**Comment by jbrablec** [comment]
and plugins simply not loading

CURRENT_PROJECT=$(pwd)

7ep@pc /elk/elasticsearch
$ PLUGINS=$CURRENT_PROJECT/elasticsearch/plugins

7ep@pc /elk/elasticsearch
$ bin/elasticsearch " -Des.path.plugins=$PLUGINS"
[2015-05-06 23:28:40,784][WARN ][bootstrap                ] jvm uses the client vm, make sure to run `java` with the server vm for best performance by adding `-server` to the command line
[2015-05-06 23:28:40,964][INFO ][node                     ] [Fasaud] version[1.5.1], pid[2956], build[5e38401/2015-04-09T13:41:35Z]
[2015-05-06 23:28:40,964][INFO ][node                     ] [Fasaud] initializing ...
[2015-05-06 23:28:40,974][INFO ][plugins                  ] [Fasaud] loaded [], sites []
