### ISSUE TITLE
Elastic search smart chinese plugin returns invalid tokens

### ISSUE THREAD

**Issue by hari-ram-s** [elastic/elasticsearch#109530]
### Elasticsearch Version

7.17.15

### Installed Plugins

smartcn, icu, kuromoji, nori

### Java Version

17.0.8 2023-07-18 LTS

### OS Version

Mac OS Sonoma 14.5

### Problem Description

I was recently checking the `smartcn` plugin, and the returned tokens do not look relevant.

I used the config from here - https://www.elastic.co/guide/en/elasticsearch/plugins/current/_reimplementing_and_extending_the_analyzers.html
And used the `/_analyze` endpoint to test the tokenizer.

When I pass this string, `大卫贝克汉姆今天射入一粒精彩进球。` (Translates to `David Beckham scored a wonderful goal today.`), it returns 14 tokens out of which 8 seems irrelevant.

Irrelevant tokens and their translations from google:-
```
大 - Big
卫 - guard
贝 - cowry
克 - gram
汉 - chinese
姆 - Mu
入 - enter
粒 - grain
```
None of the tokens above relate to my text passed. Am I missing something here or is this how this plugin would behave?

Is there any way to improve this tokenizer?

**PS:** I don't know the Chinese language and I completely rely on Google Translate to validate the result.

### Steps to Reproduce

1. Install `smartcn` plugin.
2. Create a custom analyzer with the following config.
```
PUT smartcn_example
{
  "settings": {
    "analysis": {
      "analyzer": {
        "chinese_analyzer": {
          "tokenizer":  "smartcn_tokenizer",
          "filter": [
            "porter_stem",
            "smartcn_stop"
          ]
        }
      }
    }
  }
}
```
3. Analyze this sample text to get the tokens. (`大卫贝克汉姆今天射入一粒精彩进球。`)
```
GET smartcn_example/_analyze
{
  "analyzer": "chinese_analyzer",
  "text": "大卫贝克汉姆今天射入一粒精彩进球。"
}
```
4. A total of 14 tokens will be returned out of which 8 are irrelevant (mentioned in the problem description).

**Comment by benwtrent** [comment]
@hari-ram-s I do not know what would be the valid tokens for the given text. What would they be?

This is what I get for the latest ES version. Looks like not much different than what you pasted:

```
{
  "tokens": [
    {
      "token": "大",
      "start_offset": 0,
      "end_offset": 1,
      "type": "word",
      "position": 0
    },
    {
      "token": "卫",
      "start_offset": 1,
      "end_offset": 2,
      "type": "word",
      "position": 1
    },
    {
      "token": "贝",
      "start_offset": 2,
      "end_offset": 3,
      "type": "word",
      "position": 2
    },
    {
      "token": "克",
      "start_offset": 3,
      "end_offset": 4,
      "type": "word",
      "position": 3
    },
    {
      "token": "汉",
      "start_offset": 4,
      "end_offset": 5,
      "type": "word",
      "position": 4
    },
    {
      "token": "姆",
      "start_offset": 5,
      "end_offset": 6,
      "type": "word",
      "position": 5
    },
    {
      "token": "今天",
      "start_offset": 6,
      "end_offset": 8,
      "type": "word",
      "position": 6
    },
    {
      "token": "射",
      "start_offset": 8,
      "end_offset": 9,
      "type": "word",
      "position": 7
    },
    {
      "token": "入",
      "start_offset": 9,
      "end_offset": 10,
      "type": "word",
      "position": 8
    },
    {
      "token": "一",
      "start_offset": 10,
      "end_offset": 11,
      "type": "word",
      "position": 9
    },
    {
      "token": "粒",
      "start_offset": 11,
      "end_offset": 12,
      "type": "word",
      "position": 10
    },
    {
      "token": "精彩",
      "start_offset": 12,
      "end_offset": 14,
      "type": "word",
      "position": 11
    },
    {
      "token": "进球",
      "start_offset": 14,
      "end_offset": 16,
      "type": "word",
      "position": 12
    }
  ]
}
```

**Comment by hari-ram-s** [comment]
Hello, @benwtrent. It's about the invalid tokens that are returned. As given in the description, we got tokens like `卫` (means 'guard'), `入` (means 'enter') and so on. These tokens do not relate to the given text. And FYI, the given text translates to 'David Beckham scored a wonderful goal today' in English (I used Google Translate to translate Chinese to English).

The given text and these tokens do not relate to each other in any way.

**Comment by benwtrent** [comment]
@hari-ram-s I don't speak, nor do I understand Chinese. For all I know, these tokens are absolutely correct, even though in their individual contexts they don't make sense. I would expect that character formations and character pieces in Chinese change as they are combined. 

If we know what the tokens should be, maybe there is something we can do.

**Comment by hari-ram-s** [comment]
@benwtrent, yes Chinese is a context-based language and that is why we want to generate tokens based on context. I believe the problem lies in the plugin's difficulty in recognizing nouns and generating corresponding tokens for them. The characters in the text `David Beckham` are returning invalid tokens. I got valid tokens for the remaining text.

I tried with other names, and `smartcn` still struggles.

We also use `kuromoji` and `nori` plugins for Korean and Japanese, and they are able to identify the nouns and generate tokens accordingly.

**Comment by hari-ram-s** [comment]
@benwtrent any work-around for handling nouns?

**Comment by benwtrent** [comment]
@hari-ram-s I don't think so. This particular analyzer is working as intended.

I do not off hand know of another analyzer that would work perfectly for your example.

There are other Chinese language analyzers but they seem to do a more simple bigram splitting of characters, which doesn't seem any better than this current behavior.

**Comment by hari-ram-s** [comment]
Alright. But I disagree that it is working as intended. A good analyzer should be able to identify and parse nouns instead of blindly splitting the characters in them. Anyways, thanks!

**Comment by benwtrent** [comment]
> A good analyzer should be able to identify and parse nouns instead of blindly splitting the characters in them.

For this analyzer, that is what its doing. So, its not a bug in the analyzer per-se, but a capability gap. 

Here are some other analyzer options from which you can likely create a custom analyzer: https://lucene.apache.org/core/9_11_1/analysis/common/org/apache/lucene/analysis/cjk/package-summary.html

I wonder if some of them work in the way you intend?
