### ISSUE TITLE
Allocation of replicas failed since 1.4.4 -> 1.4.5 upgrade (works again after upgrading more nodes)

### ISSUE THREAD

**Issue by rtoma** [elastic/elasticsearch#10951]
Since upgrading a single node in a 10 node cluster from 1.4.4 to 1.4.5 we get unassigned replicas for all new indices created after the "010" node got upgraded.

Example _cat/shards/xxx below:
```
index                          shard prirep state        docs  store ip            node
logstash-tst-endeca-2015.05.03 0     p      STARTED    214976 71.5mb 10.98.252.118 shd-logsearch-db-010.esaccdata10
logstash-tst-endeca-2015.05.03 0     r      UNASSIGNED
logstash-tst-endeca-2015.05.03 1     p      STARTED    214879 72.7mb 10.98.252.118 shd-logsearch-db-010.esaccdata10
logstash-tst-endeca-2015.05.03 1     r      UNASSIGNED
logstash-tst-endeca-2015.05.03 2     p      STARTED    214957 70.9mb 10.98.252.118 shd-logsearch-db-010.esaccdata10
logstash-tst-endeca-2015.05.03 2     r      UNASSIGNED
```

Changing number of replicas to any other number (even 0 and back to 1) does not fix this.

Rerouting shards is not allowed because of ```NO(target node version [1.4.4] is older than source node version [1.4.5])```

I have never seen this behaviour. Many times we upgraded rolling over the span of multiple days, with new indices created at every day rollover.

I already checked the changelog of 1.4.5 but could not find anything related. Still I believe this is a bug.

Full output of reroute command:
```
{"error":"RemoteTransportException[[shd-logsearch-db-007.esaccmaster07
inet[/10.98.252.198:9300]
cluster:admin/reroute]]; nested: ElasticsearchIllegalArgumentException[[move_allocation] can't move [logstash-tst-endeca-2015.05.03
0], from [shd-logsearch-db-010.esaccdata10
NP3t4GAkRl2emR07pZw97A
shd-logsearch-db-010.bolcom.net
inet[/10.98.252.118:9300]]{datacenter=ams5, zone=shd-logsearch-db-010, master=false}, to [shd-logsearch-db-007.esaccdata07
IHd_NcH4TVCcD7uibZzX6w
shd-logsearch-db-007.bolcom.net
inet[/10.98.252.115:9300]]{datacenter=ams4, zone=shd-logsearch-db-007, master=false}, since its not allowed, reason: [
YES(shard is not allocated to same node or host)
YES(node passes include/exclude/require filters)
YES(shard is primary)
YES(below shard recovery limit of [2])
YES(allocation disabling is ignored)
YES(allocation disabling is ignored)
YES(node meets awareness requirements)
YES(total shard limit disabled: [-1] <= 0)
NO(target node version [1.4.4] is older than source node version [1.4.5])
YES(enough disk for shard on node, free: [3.5tb])
YES(no snapshots are currently running)]]; ","status":400}
```

**Comment by rtoma** [comment]
Browsed https://github.com/elastic/elasticsearch/blob/v1.4.5/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/NodeVersionAllocationDecider.java#L70

Lucene was changed between 1.4.4 and 1.4.5 (Upgrade to Lucene 4.10.4 bugfix release #9960).
Even though its 'just' a bugfix release, the AllocationDecider does not allow recovery:
```
/* we can allocate if we can recover from a node that is younger or on the same version
* if the primary is already running on a newer version that won't work due to possible
* differences in the lucene index format etc.*/
```

**Comment by rtoma** [comment]
We upgraded a 2nd node and now replicas are started...

Maybe its worth it to improve the release notes text and warn about the impact of an upgrade lucene version?

**Comment by s1monw** [comment]
this has nothing todo with Lucene. We are not forward compatible so we can't recover from a newer version. Thanks for clarifying this issue anyway

**Comment by clintongormley** [comment]
Reopening: I think this at least requires a doc update.

**Comment by jessegonzalez** [comment]
This issue bit me, and had me scratching my head for a while. I could figure out what may have caused 8 out of 10 shards to be "successful" with 0 "failed".
