### ISSUE TITLE
Transport versioning for plugins in order to support rolling upgrades

### ISSUE THREAD

**Issue by scampi** [elastic/elasticsearch#109599]
### Description

When doing a rolling upgrade and a new version of a plugin is installed, a cluster will have nodes with different versions -- old and new versions. In case the new version of the plugin changes the way a custom request/response is serialized, this can cause failures when trying to read/write that custom object.
For example, a node with the old plugin's version sends a request to a node with the new plugin's version installed: the receiving node will fail to deserialize the request (in case the new version changed the request serialization).

Let's consider the case where `node O` contains the plugin with the old version, and `node N` the plugin with the new version. Also, the plugin has its own versioning that doesn't follow Elasticsearch's, e.g., several versions of the plugin could be intended to work for a same version of Elasticsearch.
In Elasticsearch this versioning problem at the transport layer is handled by providing the `TransportVersion`:
- In the `StreamInput` API the version of the node that _sent_ the request. On `node N` this allows to deserialize the request in the way it was done before the upgrade.
- Similarly in the `StreamOutput` API the version of the _receving_ node is accessible. On `node N` this allows to write the response in the format that was previously expected.

In order to support rolling upgrade of plugins, there is a need for the `StreamInput` and `StreamOutput` APIs to expose the plugins' version of the sending and receiving nodes, in the same way `TransportVersion` does it for Elasticsearch.
The former case could be solved by the plugin using a custom serialization scheme where the plugin's version is first serialized. However, for the latter case where the custom request/response is serialized (sent to a node with potentially an older version), there is no way to retrieve the plugin's version on the node that will receive the request/response.

**Comment by DaveCTurner** [comment]
I think this observation is valid, there is no particularly easy way to solve this today. Each minor Elasticsearch release will typically have a different `TransportVersion` (although even this is not guaranteed, it is in practice true). That means that the simplest approach would be to align the wire protocol changes in your plugin with minor Elasticsearch releases.

You could also design your plugin's wire protocol to have a certain amount of flexibility _between_ minor releases. For instance, you could include in each message payload an opaque `BytesReference` which you can parse with as much leniency as you need. We've done that in ES in the past, permitting (but ignoring) trailing data on some messages so that newer versions can append data to existing messages without confusing older nodes. Also we use `XContent` in some places to allow adding fields to messages without breaking compatibility. I expect that will often be enough to keep going until the next minor release when you can clean up any leniency introduced in the interim.

But it seems like there would have to be some changes on the ES side in order to properly address the problem of multiple plugin wire protocols per ES minor release.

**Comment by scampi** [comment]
Thanks for the comments

> That means that the simplest approach would be to align the wire protocol changes in your plugin with minor Elasticsearch releases.

I believe that is not a solution because it means Elasticsearch would have to be upgraded alongside the plugin. The goal is to allow upgrading a plugin independently of Elasticsearch, e.g., a plugin gets a new feature for the Elasticsearch version currently installed on a cluster.

> You could also design your plugin's wire protocol to have a certain amount of flexibility between minor releases. For instance, you could include in each message payload an opaque BytesReference which you can parse with as much leniency as you need. We've done that in ES in the past, permitting (but ignoring) trailing data on some messages so that newer versions can append data to existing messages without confusing older nodes. 

Do you have an example of how that was done ? Wouldn't the custom request/response ultimately fail anyway ? For example, if a field was serialized as a string, but in the new version it is serialized as a number: the code depending on that field would fail as it gets undefined data. One could imagine also `writeLong` versus `writeVLong` type of scenario.

> Also we use XContent in some places to allow adding fields to messages without breaking compatibility.

Thanks, that's good to keep in mind. But the problem remains in most cases. Also, this seems that this solution would require data to be duplicated. For example, to address above case of string versus number; the value is serialized as an object with a version attribute:

- the old version expects an object like below

  ```json
  {
     "my_field": {
        "type": "V1",
        "value": "abc"
     }
  }
  ```

- the new version has to write the following with the value **duplicated**, since it doesn't know what is the version of the plugin on the node **receiving** the custom request/response, something like below:

  ```json
  {
     "my_field": [
        {
           "type": "V1",
           "value": "abc"
        },
        {
           "type": "V2",
           "value": 123
        }
     ]
  }
  ```

**Comment by DaveCTurner** [comment]
> For example, if a field was serialized as a string, but in the new version it is serialized as a number: the code depending on that field would fail as it gets undefined data. One could imagine also writeLong versus writeVLong type of scenario.

Right, that's why I suggest always to include a `BytesReference` so that you have somewhere to put extra fields which is not  subject to such strict parsing.

> Also, this seems that this solution would require data to be duplicated.

Yes, without changes in ES I think that will be unavoidable. I'd suggest leaving those sorts of changes until the next minor release.

**Comment by thecoop** [comment]
@scampi Thanks for the issue, we discussed it in our team meeting today.

Unfortunately there's no real way to manage multiple plugin serialization formats for the same elasticsearch release - this has always been an issue. Adding proper support would be quite a lot of work, and given this is the first request we've had of this type, realistically not going to happen anytime soon.

There are several ways you can manage this within your own plugin code, for example:

* Include a 'version' vint at the start of each serialized object so you know how to handle it
* Propagate version information for each node in cluster state so your plugin knows which version it needs to serialize for so it can be read by all nodes
* Create a transport action in your plugin that nodes can use to swap version numbers
* Use a strict serialization protocol, or use protobuf directly, to serialize your plugin data in a backwards-compatible way

Given we aren't going to work on this infrastructure anytime soon, I'll close this issue. If you want to work on it yourself, please do submit PRs to the elasticsearch codebase to add plugin versioning support, and we'll consider them closely. And if we get more requests for this functionality, we'll definitely reopen and reconsider this.

**Comment by prdoyle** [comment]
Could this be a good use for cluster state? Plugins that need versioning of their behaviour (including communication protocol) could store the current cluster-wide version in cluster state, and then they could register a state listener to coordinate everyone using the new behaviour.

**Comment by scampi** [comment]
> Propagate version information for each node in cluster state so your plugin knows which version it needs to serialize for so it can be read by all nodes

In the `writeTo` method of a request/response, how do you get the node ID at the receiving end ? That would be needed to adopt above solution, from what I understand. Would adding such a getter on the `StreamInput` and `StreamOutput` interfaces be possible, or is that a similar complexity to exposing a plugin's version ?

**Comment by thecoop** [comment]
You don't know which node it is being serialized from, but you could use cluster state to determine the _minimum_ serialization version required to talk to all active nodes, and so anything serialized with that version can be read by all nodes. We already do a similar thing with [`ClusterState.getMinTransportVersion`](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/cluster/ClusterState.java#L304)
