### ISSUE TITLE
Synthetic source failure when `doc_values: false`

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#109546]
### Description

All fields which support doc values have them enabled by default. Anyway, if sorting and/or aggregation and/or accessing a field from a script is not required users can disable doc values by specifying `doc_values: false` in index mappings.

LogsDB uses synthetic source by default and, as a result, fields without doc values cannot be reconstructed. If a field has `doc_value: false` and `store: false` in LogsDB we have to ways to deal with it:
1. fallback to using `_ignored_source` so that we can reconstruct the document contents including such fields too.
2. throw an error and require mappings not including `doc_values: false`

**Comment by lkts** [comment]
This was implemented for number fields and `keyword`. Pretty much every single other field that natively supports synthetic source won't with without doc values. This work is pending.
