### ISSUE TITLE
Accept ["_none_"] to disable stored fields

### ISSUE THREAD

**Issue by axeljohnsson** [elastic/elasticsearch#109581]
### Elasticsearch Version

8.13.4

### Java Version

_bundled_

### OS Version

Amazon Linux 2

### Problem Description

According to the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.14/search-fields.html#disable-stored-fields), it should be possible to disable stored fields via the `_none_` property. This works as intended, but only if the value is a single string and not a list.

I have tested two different queries via `curl` where the only difference is:

```shell
$ diff request-good.json request-bad.json
2c2
<   "stored_fields": "_none_",
---
>   "stored_fields": ["_none_"],
```

The "bad" request returns:

```json
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": "Cannot invoke \"java.util.List.size()\" because the return value of \"org.elasticsearch.search.fetch.StoredFieldsContext.fieldNames()\" is null"
      }
    ],
    "type": "null_pointer_exception",
    "reason": "Cannot invoke \"java.util.List.size()\" because the return value of \"org.elasticsearch.search.fetch.StoredFieldsContext.fieldNames()\" is null"
  },
  "status": 500
}
```

We are using the elasticsearch-java client which always serializes the value as a list. Therefore, do you think it makes sense for the **server** to accept a list like this `["_none_"]`?

### Steps to Reproduce

Set `"stored_fields": ["_none_"]` when searching.

**Comment by gwbrown** [comment]
I've altered the title of this issue to make it clearer that this is a feature request which happens to be inspired by the behavior of the `elasticsearch-java` client, rather than a bug report for that client. If you would like to file a bug report for the client, please do so on the [GitHub repository for the `elasticsearch-java` client](https://github.com/elastic/elasticsearch-java).

**Comment by javanna** [comment]
@axeljohnsson I am unable to reproduce this with a very simple search request. The code seems to be handling the cause you mention, but perhaps your request exercise a specific codepath. Could you post a complete recreation of how you get the error please?

**Comment by axeljohnsson** [comment]
On 8.13.4 it is easy to reproduce, not so much on 8.14.1, and for a good [reason](https://github.com/elastic/elasticsearch/pull/104711).

I will close this issue and look forward for when we upgrade our cluster.

**Comment by javanna** [comment]
Ah that makes sense, I even reviewed that PR with the fix, but I forgot about it. Great to hear we've fixed it already.
