### ISSUE TITLE
Add the ability to synchronously inject data before startup

### ISSUE THREAD

**Issue by ereOn** [elastic/elasticsearch#10954]
As I was trying to create a docker image for an ElasticSearch instance, I wanted to inject some data directly into the image.

Sadly, it seems there is no way of injecting data when the service is not running : I had to create a script that starts the service in background, polls the server with cURL requests until they succeed then stops the service.

All of this seems fragile but I couldn't find a more satisfying solution. What would it take to allow for offline-injection of data in a synchronous manner ?

**Comment by clintongormley** [comment]
Just copy a pre-prepared `data` dir into your new image.

**Comment by ereOn** [comment]
@clintongormley So much for dicussion I see :)

Is there a stable API to generate a customized data folder or does one have to fire up an instance, fill it and just copy the result ?

**Comment by jpountz** [comment]
@ereOn There is no way to do it without starting a node. Starting a node, indexing some data and copying the data directory will work indeed.
