### ISSUE TITLE
Supporting dots ('.') as separator for dynamic_date_formats

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#10961]
dynamic_date_formats does don't support dots in mapping

**Steps to repro**

1- Modify default-mapping.json file and add

```
{
    "_default_" : {
        "dynamic_date_formats" : ["yyyy.MM.dd HH:mm"]
    }
}
```

2- Create new index and add a new document, without setting the mapping

```
{
    "my_date": "2012.03.08 12:30"
}
```

3- Verify that the my_date field is stored as string, and not as date

```
{
    "tryit_now": {
        "mappings": {
            "dateFormats": {
                "dynamic_date_formats": [
                    "yyyy.MM.dd HH:mm"
                ],
                "properties": {
                    "my_date": {
                        "type": "string"
                    }
                }
            }
        }
    }
}
```

According to the [DocumentParser.java](https://github.com/elastic/elasticsearch/blob/b4efb6c472715756f9920a653be70d3ce16767cc/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java#L466) we only allow ":", "-" and "/" for separator for dynamic dates.

**Comment by gmoskovicz** [comment]
The workaround for this will be to refactor our mapping and add slashes to the dynamic format:

```
{
    "_default_" : {
        "dynamic_date_formats" : ["yyyy/MM/dd HH:mm"]
    }
}
```

Also, to use any of the [date formats](http://www.elastic.co/guide/en/elasticsearch/reference/1.3/mapping-date-format.html) suggested in our documentation.

**Comment by clintongormley** [comment]
@gmoskovicz In what locales are periods used in dates by default?

**Comment by gmoskovicz** [comment]
@clintongormley we have been seeing that some systems are using dot separator as the default for their dates.

A wat to hack this is also to add seconds to the date format, therefore it will contain 2 ":" and will overpass the restriction:

```
{
    "_default_" : {
        "dynamic_date_formats" : ["yyyy.MM.dd HH:mm:ss"]
    }
}
```

Nowadays the restriction is that the full pattern should contain at least 2 ":", two "-" or two "/"

**Comment by gmoskovicz** [comment]
But i am concerned also that there are not strict locales using periods in dates by default.

**Comment by clintongormley** [comment]
The problem with using periods for date detection is that it could break floating point numbers, written as strings.  Also, I don't know of any locales that use periods by default (but that may just be ignorance).

We could reduce the requirement for "more than 1" colon, slash etc for date detection.  Or maybe this would cease to be an issue if we finally get around to merging https://github.com/elastic/elasticsearch/pull/6227

/cc @spinscale

**Comment by gmoskovicz** [comment]
According to [this](http://en.wikipedia.org/wiki/Date_format_by_country) there are some using dots as separator.

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/1694
