### ISSUE TITLE
Regression in 8.6.0: Not returning empty arrays when source filtering inside them

### ISSUE THREAD

**Issue by Wim-De-Clercq** [elastic/elasticsearch#109668]
### Elasticsearch Version

from 8.6.0 until current

### Java Version

openjdk version "19.0.1" 2022-10-18

### OS Version

Linux e3b996519639 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC

### Problem Description
Exclude filtering causes empty objects from the response to disappear entirely.

This is probably very similar to these.
https://github.com/elastic/elasticsearch/issues/29622
https://github.com/elastic/elasticsearch/issues/23796

But the thing is that this WAS working fine in 8.3.x, 8.4.x, 8.5.x, ...

8.6.0 broke this feature again.

#### setup data
```
PUT /test
```

```
PUT /test/_mapping
{
  "properties": {
    "myArray": {
      "properties": {
        "myField": {
          "type": "keyword"
        }
      }
    }
  }
}
```

```
PUT /test/_doc/1
{
  "myArray": [{"myField": "value", "other": "value"}]
}
```

```
PUT /test/_doc/2
{
  "myArray": []
}
```

#### search
```
POST /test/_search
{
  "_source": {
    "includes": ["myArray"],
    "excludes": ["myArray.myField"]
  }
}
```

#### result
```
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 2,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "test",
        "_id": "2",
        "_score": 1,
        "_source": {}
      },
      {
        "_index": "test",
        "_id": "1",
        "_score": 1,
        "_source": {
          "myArray": [
            {
              "other": "value"
            }
          ]
        }
      }
    ]
  }
}
```
It should contain "myArray" with empty arrays.

**Comment by lkts** [comment]
It looks like this change in behaviour was caused by #91127.

**Comment by kved96** [comment]
+1 to this we rely on the old behavior in all of our clients quite heavily and it would be a huge undertaking to build compatibility. Is this something that can be prioritized for a fix? @elasticsearchmachine

**Comment by lkts** [comment]
re-tagged based on the tags in #112250
