### ISSUE TITLE
[openbsd] shield doesn't work on OpenBSD, probably because of blowfish

### ISSUE THREAD

**Issue by jirib** [elastic/elasticsearch#10968]
Hello,
I'm trying to learn elasticsearch and I tried shield plugin with ES 1.5.1 on OpenBSD 5.7 snapshot amd64.

```
# ./bin/elasticsearch -v     
Version: 1.5.1, Build: 5e38401/2015-04-09T13:41:35Z, JVM: 1.7.0_71
# find plugins/shield/           
plugins/shield/
plugins/shield/LICENSE.txt
plugins/shield/NOTICE.txt
plugins/shield/config
plugins/shield/commons-codec-1.10.jar
plugins/shield/automaton-1.11-8.jar
plugins/shield/unboundid-ldapsdk-2.3.8.jar
plugins/shield/elasticsearch-shield-1.2.1.jar
```

It could be related to blowfish implementation but I'm not sure. Let's compare shields hashed passwords and OpenBSD blowfish hashed passwords:

```
# cat config/shield/users                                                                                                                                                                                          
es_admin:$2a$10$PQHKemNIRLEz.qWIPNQSbe0y2Yp/B7bIfgdJtjJo5r9g8VBtMosk2
# 
I-search: 
# cat config/shield/users 
# grep jirib /etc/master.passwd  
jirib:$2b$10$m.........anonymized....:1000:1000:staff:0:0:jirib:/home/jirib:/bin/ksh
```

IIRC there was an issue with blowfish $2a passwords, here is what OpenBSD people wrote:

> Solar found a bug in the OpenBSD implementation of bcrypt when hashing long passwords. The length is stored in an unsigned char type, which will overflow and wrap at 256. Although we consider the existence of affected hashes very rare, in order to differentiate hashes generated before and after the fix, we are introducing a new minor 'b'.
>
> OpenBSD 5.5 (coming this spring) will accept and verify 'b' hashes, although it will still generate 'a' hashes. OpenBSD 5.6 (coming this fall) will change to generating 'b' hashes by default.

> A future release of Solar's bcrypt code should also support 'b'. 

With shied plugin installed:

```
$  curl -u es_admin -XGET 'http://127.0.0.1:9200/'  
Enter host password for user 'es_admin':
{"error":"AuthenticationException[unable to authenticate user [es_admin] for REST request [/]]","status":401}
```

With shield plugin removed:

```
$  curl -XGET 'http://127.0.0.1:9200/'              
{
  "status" : 200,
  "name" : "Ringmaster",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.5.1",
    "build_hash" : "5e38401bc4e4388537a615569ac60925788e1cf4",
    "build_timestamp" : "2015-04-09T13:41:35Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
````

(I apologize but I could not manage to get some logging about auth issue.)

If you need more info I'd be pleased to provide it.

**Comment by clintongormley** [comment]
@jaymode could you take a look at this please

**Comment by jaymode** [comment]
@jirib how did you install elasticsearch on OpenBSD? Is the config directory with the shield folder in it the same directory that contains your elasticsearch.yml?

**Comment by jirib** [comment]
from OpenBSD ports/packages (http://cvsweb.openbsd.org/cgi-bin/cvsweb/ports/textproc/elasticsearch/). shield and license was under /usr/local/elasticsearch/plugins.

```
/etc/elasticsearch
/etc/elasticsearch/elasticsearch.in.sh
/etc/elasticsearch/elasticsearch.yml
/etc/elasticsearch/logging.yml
/usr/local/elasticsearch
/usr/local/elasticsearch/bin
/usr/local/elasticsearch/bin/plugin
/usr/local/elasticsearch/bin/elasticsearch
/usr/local/elasticsearch/lib
/usr/local/elasticsearch/lib/antlr-runtime-3.5.jar
/usr/local/elasticsearch/lib/apache-log4j-extras-1.2.17.jar
/usr/local/elasticsearch/lib/asm-4.1.jar
/usr/local/elasticsearch/lib/asm-commons-4.1.jar
/usr/local/elasticsearch/lib/elasticsearch-1.5.1.jar
/usr/local/elasticsearch/lib/groovy-all-2.4.0.jar
/usr/local/elasticsearch/lib/jna-4.1.0.jar
/usr/local/elasticsearch/lib/jts-1.13.jar
/usr/local/elasticsearch/lib/log4j-1.2.17.jar
/usr/local/elasticsearch/lib/lucene-analyzers-common-4.10.4.jar
/usr/local/elasticsearch/lib/lucene-core-4.10.4.jar
/usr/local/elasticsearch/lib/lucene-expressions-4.10.4.jar
/usr/local/elasticsearch/lib/lucene-grouping-4.10.4.jar
/usr/local/elasticsearch/lib/lucene-highlighter-4.10.4.jar
/usr/local/elasticsearch/lib/lucene-join-4.10.4.jar
/usr/local/elasticsearch/lib/lucene-memory-4.10.4.jar
/usr/local/elasticsearch/lib/lucene-misc-4.10.4.jar
/usr/local/elasticsearch/lib/lucene-queries-4.10.4.jar
/usr/local/elasticsearch/lib/lucene-queryparser-4.10.4.jar
/usr/local/elasticsearch/lib/lucene-sandbox-4.10.4.jar
/usr/local/elasticsearch/lib/lucene-spatial-4.10.4.jar
/usr/local/elasticsearch/lib/lucene-suggest-4.10.4.jar
/usr/local/elasticsearch/lib/spatial4j-0.4.1.jar
/usr/local/elasticsearch/data
/usr/local/elasticsearch/data/elasticsearch
/usr/local/elasticsearch/data/elasticsearch/nodes
/usr/local/elasticsearch/data/elasticsearch/nodes/0
/usr/local/elasticsearch/data/elasticsearch/nodes/0/node.lock
/usr/local/elasticsearch/plugins
/usr/local/elasticsearch/plugins/syslog
/usr/local/elasticsearch/plugins/syslog/elasticsearch-syslog-1.4.0.3.jar
/usr/local/elasticsearch/config
/usr/local/elasticsearch/config/shield
/usr/local/elasticsearch/config/shield/logging.yml
/usr/local/elasticsearch/config/shield/role_mapping.yml
/usr/local/elasticsearch/config/shield/roles.yml
/usr/local/elasticsearch/config/shield/users
/usr/local/elasticsearch/config/shield/users_roles
```

**Comment by jaymode** [comment]
You will need to move the `/usr/local/elasticsearch/config/shield` to `/etc/elasticsearch/shield`. Can you please confirm that this works?

We do not mention OpenBSD, but have some documentation around this issue when installing elasticsearch that the configuration path may need to be set when using the plugin and esusers commands[1]; we're still working on improving this too.

[1] http://www.elastic.co/guide/en/shield/current/getting-started.html#_configuring_your_environment

**Comment by jirib** [comment]
Works, thank you. Thus NOTABUG.

I have also couple of unrelated questions:

On OpenBSD we do not tell people to setup env vars but daemons set this env vars for themselves.

- handling JAVA_HOME: we use something like this JAVA_HOME="$(/usr/local/bin/javaPathHelper -h elasticsearch)"
- handling ES_INCLUDE: we have the file in /etc/elasticsearch/elasticsearch.in.sh

Do you have any recommendation for us while not telling people to define shell env vars?
Maybe we could for ES_INCLUDE do symlink from /usr/local/elasticsearch/bin/elasticsearch.in.sh -> /etc/elasticsearch/elasticsearch.in.sh ? Or could you add ES_INCLUDE file search also for /etc/elasticsearch?

We could define JAVA_HOME in ES_INCLUDE file? Thus 'bin/plugin' or 'bin/shield/esusers' would work.

If we would define 'ES_JAVA_OPTS="-Des.path.conf=/etc/elasticsearch"' in ES_INCLUDE file would be plugins' configuration located in /etc/elasticsearch (like you told me to mv 'conf/shield' to '/etc/elasticsearch'...)?

Thank you for help and advices.

**Comment by jirib** [comment]
> We could define JAVA_HOME in ES_INCLUDE file? Thus 'bin/plugin' or 'bin/shield/esusers' would work.

Do this "bins" work independently or do they inherit elasticsearch configuration? I mean as we define '-Des.config=/etc/elasticsearch/elasticsearch.yml' thus elasticsearch instance knows about its 'path.config' from yml file, but would know 'path.config' also 'bin/plugin' and/or 'bin/shield/esusers'?

**Comment by jirib** [comment]
FYI I did following modication and 'bin/plugin' and 'bin/shield/esusers' work out of the box (without JAVA_HOME in env) and after shield plugin installation I have 'shield' conf directory in /etc/elasticsearch.

```
# diff -uNp /usr/local/share/examples/elasticsearch/                                                                                                                             [5/1813]
elasticsearch.in.sh    elasticsearch.yml      logging.yml            
cal/share/examples/elasticsearch/elasticsearch.in.sh /etc/elasticsearch/elasticsearch.in.sh                                                                                            <
--- /usr/local/share/examples/elasticsearch/elasticsearch.in.sh Fri May  1 04:37:07 2015
+++ /etc/elasticsearch/elasticsearch.in.sh      Tue May  5 12:56:53 2015
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+JAVA_HOME="$(/usr/local/bin/javaPathHelper -h elasticsearch)"
+ES_JAVA_OPTS="-Des.path.conf=/etc/elasticsearch"
+
 ES_CLASSPATH=$ES_CLASSPATH:$ES_HOME/lib/elasticsearch-1.5.1.jar:$ES_HOME/lib/*:$ES_HOME/lib/sigar/*
 
 if [ "x$ES_MIN_MEM" = "x" ]; then
@@ -64,4 +67,4 @@ JAVA_OPTS="$JAVA_OPTS -XX:+HeapDumpOnOutOfMemoryError"
 JAVA_OPTS="$JAVA_OPTS -XX:+DisableExplicitGC"
 
 # Ensure UTF-8 encoding by default (e.g. filenames)
-JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8"
\ No newline at end of file
+JAVA_OPTS="$JAVA_OPTS -Dfile.encoding=UTF-8"
# ls -l bin/elasticsearch.in.sh                                                                                                                                                         
lrwxr-xr-x  1 root  wheel  38 May  5 12:55 bin/elasticsearch.in.sh -> /etc/elasticsearch/elasticsearch.in.sh
```

**Comment by jirib** [comment]
Ah, not really, I also modified 'bin/plugin' to use ES_INCLUDE too.

```
# If an include wasn't specified in the environment, then search for one...
if [ "x$ES_INCLUDE" = "x" ]; then
    # Locations (in order) to use when searching for an include file.
    for include in /usr/share/elasticsearch/elasticsearch.in.sh \
                   /usr/local/share/elasticsearch/elasticsearch.in.sh \
                   /opt/elasticsearch/elasticsearch.in.sh \
                   ~/.elasticsearch.in.sh \
                   /etc/elasticsearch/elasticsearch.in.sh \
                   $ES_HOME/bin/elasticsearch.in.sh \
                   "`dirname "$0"`"/elasticsearch.in.sh; do
        if [ -r "$include" ]; then
            . "$include"
            break
        fi
    done
# ...otherwise, source the specified include.
elif [ -r "$ES_INCLUDE" ]; then
    . "$ES_INCLUDE"
fi
```

**Comment by jaymode** [comment]
@jirib thanks for the updates on it working and your testing with the scripts and configuration settings.

@tlrx has been working on a lot of our packaging and scripts recently. In other OS's we are usually reading configuration variables from /etc/sysconfig/elasticsearch or /etc/default/elasticsearch; not sure if the equivalent exists in OpenBSD.

That said, I think this discussion may be better continued on the mailing list https://groups.google.com/forum/#!forum/elasticsearch or the new discussion forums https://discuss.elastic.co/
