### ISSUE TITLE
The English word 'IT' cannot be filtered

### ISSUE THREAD

**Issue by zidingyi94** [elastic/elasticsearch#109605]
elasticsearch version：7.10.0
index setting：{
  "settings": {
    "analysis": {
      "filter": {
        "my_stopwords": {
          "type": "stop",
          "stopwords": ["a"]  
        }
      },
      "analyzer": {
        "custom_index_analyzer": {
          "type": "custom",
          "tokenizer": "ik_smart",
          "filter": [
            "lowercase",
            "my_stopwords"  
          ]
        },
        "custom_search_analyzer": {
          "type": "custom",
          "tokenizer": "ik_smart",
          "filter": [
            "lowercase",
            "my_stopwords"  
          ]
        }
      }
    }
  },
    "mappings": {
    "properties": {
        "dimension": {
            "type": "keyword"
        },
        "description": {
            "type": "text",
            "analyzer": "ik_max_word",
            "search_analyzer": "ik_smart"
        },
        "value": {
            "type": "text",
            "analyzer": "custom_index_analyzer",
            "search_analyzer": "custom_search_analyzer"
        },
        "dynamic": {
            "type": "keyword"
        },
        "loaded_time": {
            "type": "date",
            "format": "strict_date_optional_time||epoch_millis"
        },
        "scene_code": {
            "type": "keyword"
        }
    }
    }
}
When I created such an index and inserted a piece of data with value=IT, I could not recall IT correctly when I searched through matchquery, but I could recall a single CT of the same length. I have excluded IT from the list of stopped words, but I still cannot recall it.In addition, I want the value field to support mixed Chinese and English

**Comment by cbuescher** [comment]
Hi @zidingyi94 ! Your question is better suited to the support forums over at [discuss.elastic.co](https://discuss.elastic.co/). We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
