### ISSUE TITLE
Add testing for invalid XContent queries

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#10974]
The query parsers already check for problems in XContent (e.g. missing fieldnames, wrong token types) in many places. We should investigate if it is possible to have some generic tests in the BaseQueryTestCase that check for expected exceptions and other things that happen when parsing invalid json.

**Comment by javanna** [comment]
@cbuescher did you have anything in mind around this? Would you want to pick it up?

**Comment by cbuescher** [comment]
@javanna I think there are a few general checks we could do (like missing brackets, adding brackets) but I doubt that there are any other tests that are general enough for BaseQueryTestCase that produce predictable errors across all query parsers. Relabeled it and so this is not an issue that's concerning Query Refactoring, if thats okay.

**Comment by clintongormley** [comment]
@cbuescher is this something that has been done as part of search refactoring, or still needs to be done?

**Comment by cbuescher** [comment]
@clintongormley there are two general cases that have been added ( #14220, #14255). This kind of tests can alway be improved further, that's why I kept this open as a reminder to think about it again and see if tests can be extended even more, but we can close this if you like.

**Comment by javanna** [comment]
I think we did enough here. We will improve this when we need to (aka when we find more bugs that our tests didn't catch). But I think we are in a very good place!
