### ISSUE TITLE
LogsDB - Performance Testing

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#109798]
### Description

As part of the effort to test integration of LogsDB we would like to run performance testing taking advantage of Rally. Our focus is on comparing indexing throughput, query latency and storage footprint when indexing, querying and storing logs in LogsDB ve standard indices.

- [x] Create and run a new LogsDB track from the `elastic/logging` and `http_logs` Rally tracks and compare indexing throughput performance versus standard indexing mode.
- [x] Create and run a new LogsDB track from the `elastic/logging` and `http_logs` Rally tracks and compare query latency performance versus standard indexing mode.
- [x] Create and run a new LogsDB track from the `elastic/logging` and `http_logs` Rally tracks and compare storage footprint performance versus standard indexing mode.
- [x] Create and run a new LogsDB challenge from the `elastic/logging` and `http_logs tracks` which executes ESQL queries. Compare query latency performance versus standard indexing mode (notice that the `http_logs` track does not have a specific ESQL challenge while `elastic/logging` already has one).

**Comment by martijnvg** [comment]
The tasks mentioned here for `elastic/logs` track have been completed. Recently the http_logs track has been adjusted to support index mode logsdb.

**Comment by Evesy** [comment]
@salvatore-campagna Were the results of this performance testing published anywhere? We're interested in switching some indices over to logsdb but was hoping to see some benchmarks on the impact of indexing performance before doing so
