### ISSUE TITLE
Jackson libs version update

### ISSUE THREAD

**Issue by cbharadwaja** [elastic/elasticsearch#109706]
The latest version of Jackson libs are available where an upper limit is enforced on the input being parsed from version 2.17. This fixes a security issue reported by SonaType.

**Comment by DaveCTurner** [comment]
Thank you for your report.

Elastic's security reporting guidelines are available at https://www.elastic.co/community/security. Per those guidelines, all reports of potential security issues or vulnerabilities should be sent via email to [security@elastic.co](mailto:security@elastic.co)

We are unable to discuss potential issues of this nature here. Please send your report to the email address above, where it can be appropriately handled.

And please also note that a Jackson upgrade is also in progress, see https://github.com/elastic/elasticsearch/pull/109717 and related issues.
