### ISSUE TITLE
Throw exception if unrecognised params present in bulk request

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch#10977]
If additional elements (like `_source`) are present in the metadata line of the bulk request body, some arguments get ignored. This is an example where `_id` gets ignored (works fine without the `_source` there):

    curl -XGET 'http://localhost:9200/?pretty'
    #[200] (0.002s)
    #{
    #  "cluster_name": "elasticsearch",
    #  "name": "Xemnu the Titan",
    #  "status": 200,
    #  "tagline": "You Know, for Search",
    #  "version": {
    #    "build_hash": "53bf0729d5cab01181e98d2de34c73a97fa2b1f8",
    #    "build_snapshot": true,
    #    "build_timestamp": "2015-05-05T10:11:47Z",
    #    "lucene_version": "4.10.4",
    #    "number": "1.6.0"
    #  }
    #}
    curl -XPUT 'http://localhost:9200/test?pretty' -d ''
    #[200] (0.095s)
    #{
    #  "acknowledged": true
    #}
    curl -XPOST 'http://localhost:9200/test/_bulk?pretty&refresh=true' -d '{"index": {"_index": "test", "_type": "doc", "_source": {"hello": "world"}, "_id": 0}}
    {"idx": 0}
    '
    #[200] (0.089s)
    #{
    #  "errors": false,
    #  "items": [
    #    {
    #      "create": {
    #        "_id": "AU0jlPM2pgX4WOPmtASc",
    #        "_index": "test",
    #        "_type": "doc",
    #        "_version": 1,
    #        "status": 201
    #      }
    #    }
    #  ],
    #  "took": 85
    #}

**Comment by clintongormley** [comment]
@HonzaKral we should throw an error there about unrecognised params, but the `_source` field doesn't belong in the metadata line.

**Comment by HonzaKral** [comment]
Agreed, but it also caused the _id to be ignored, which is a bug
