### ISSUE TITLE
ESQL: extend SHOW command

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#109818]
### Description

The `SHOW` command currently only support `INFO` as argument.
We should extend it to allow reporting on the following:
* functions available to use in the query;
* clusters available to query;
* indices, data streams and aliases;
* columns (names, types).

**Comment by idegtiarenko** [comment]
I wonder if we should include nodes, shards and segments as well?

**Comment by bpintea** [comment]
Dupe of #103692
