### ISSUE TITLE
[CI] PackageTests failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#109852]
**Build scan:**
https://gradle-enterprise.elastic.co/s/dw3wvyugemt5g/tests/:qa:packaging:destructiveDistroTest.default-rpm/org.elasticsearch.packaging.test.PackageTests/test60Reinstall

**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.packaging.test.PackageTests#test60Reinstall`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test60Reinstall'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.packaging.test.PackageTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.RuntimeException: Installing distribution org.elasticsearch.packaging.util.Distribution@6ab86626 failed: exitCode = [1] stdout = [] stderr = [package elasticsearch-0:8.15.0~SNAPSHOT-1.x86_64 is already installed]

  at __randomizedtesting.SeedInfo.seed([B0DC0D812F3EF1D7:5A4C809F7F11AE46]:0)
  at org.elasticsearch.packaging.util.Packages.installPackage(Packages.java:93)
  at org.elasticsearch.packaging.util.Packages.installPackage(Packages.java:82)
  at org.elasticsearch.packaging.test.PackagingTestCase.install(PackagingTestCase.java:244)
  at org.elasticsearch.packaging.test.PackageTests.test60Reinstall(PackageTests.java:215)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1570)

```

**Comment by masseyke** [comment]
I've just hit this same thing with `test70RestartServer` (https://gradle-enterprise.elastic.co/s/lbijfjtretvqm/tests/task/:qa:packaging:destructiveDistroTest.default-rpm/details/org.elasticsearch.packaging.test.PackageTests/test70RestartServer?expanded-stacktrace=WyIwIl0&top-execution=1):
```
java.lang.RuntimeException: Installing distribution org.elasticsearch.packaging.util.Distribution@15460327 failed: exitCode = [1] stdout = [] stderr = [package elasticsearch-0:8.15.0~SNAPSHOT-1.x86_64 is already installed]
at __randomizedtesting.SeedInfo.seed([85844D7407F3F7B5:47B963FD75F42733]:0) |  
-- | --
  |   | at org.elasticsearch.packaging.util.Packages.installPackage(Packages.java:93) |  
  |   | at org.elasticsearch.packaging.util.Packages.installPackage(Packages.java:82) |  
  |   | at org.elasticsearch.packaging.test.PackagingTestCase.install(PackagingTestCase.java:244) |  
  |   | at org.elasticsearch.packaging.test.PackageTests.test70RestartServer(PackageTests.java:229) |  
  |   | at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) |  
  |   | at java.lang.reflect.Method.invoke(Method.java:580) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982) |  
  |   | at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996) |  
  |   | at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) |  
  |   | at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) |  
  |   | at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390) |  
  |   | at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850) |  
  |   | at java.lang.Thread.run(Thread.java:1570)


```

**Comment by benwtrent** [comment]
I just had one fail for `test70RestartServer` as well. Same error message: https://gradle-enterprise.elastic.co/s/zofmxtxjke3cc

I am going to mute `test70RestartServer` if its not already muted.

**Comment by benwtrent** [comment]
I have now had another test in `PackageTests` fail. I am going to mute this entire class and consolidate failures into this issue.

**Comment by benwtrent** [comment]
Here is another failure, but a different test than before: https://gradle-enterprise.elastic.co/s/mwsjvhfqp6ydk
