### ISSUE TITLE
[ESQL] Load and Return Date Nanos Values

### ISSUE THREAD

**Issue by not-napoleon** [elastic/elasticsearch#109987]
### Description

Add a new DataType to ESQL to represent the Elasticsearch date nanos field type.  The new data type would (initially, and for the scope of this ticket) not be supported by any functions, even functions which nominally support every type (like `COALESCE`).  This ticket strictly covers correctly loading and returning the values from within ESQL.

Internally, we can use long block for this, as they are currently stored as longs and we see no reason to change that.

 - [ ] Write new CSV test data that uses date nanos
 - [ ] Write CSV tests for loading and returning date nanos
 - [ ] Create a new data type
 - [ ] Field Loader integration
 - [ ] Make sure we're correctly returning it over HTTP
 - [ ] Do we need a feature flag for this?

**Comment by nik9000** [comment]
> * Do we need a feature flag for this?

I know we'll need an `EsqlCapability` for testing, but I don't think we need a feature flag. Unless we're worried about the "half way" support for things like `COALESCE`.
