### ISSUE TITLE
Mapping: Date Bug When Using numeric_resolution

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#10995]
When I switch numeric_resolution to use seconds on a date field and input a date as "yyyy-MM-ddThh:mm:ssZ" it appears to calculate the incorrect number of milliseconds stored internally.

As an example, using the date "2015-04-28T04:02:07Z"  I was seeing the following number of milliseconds stored internally:

Using milliseconds: 1.4301...E12
Using seconds: 1.4301...E15

I would expect these to be the same since they are both ultimately stored as milliseconds.

**Comment by jpountz** [comment]
Oh, this is a bad bug indeed. Numeric resolution should only be applied to dates provided as numbers, not as formatted dates.
