### ISSUE TITLE
es Migration data error

### ISSUE THREAD

**Issue by smallemployees** [elastic/elasticsearch#109909]
### Elasticsearch Version

7.17.18

### Java Version

_bundled_ 1.8

### OS Version

centos7.9

### Problem Description

no_valid_shard_copy no segments file checksum failed hardware problem

### Steps to Reproduce

What are the repair methods available

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
