### ISSUE TITLE
ESQL: support for weighted average aggregation

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#109940]
### Description

We could easily support https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-weight-avg-aggregation.html with a surrogate expression.

**Comment by astefan** [comment]
As an aid to this, [this PR](https://github.com/elastic/elasticsearch/pull/107414/files) is a good starting point.

**Comment by fang-xing-esql** [comment]
Resolved by https://github.com/elastic/elasticsearch/pull/109993
