### ISSUE TITLE
[CI] ValuesIntAggregatorFunctionTests classMethod failing

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#109932]
**Build scan:**
https://gradle-enterprise.elastic.co/s/be7jmqtelosou/tests/:x-pack:plugin:esql:compute:test/org.elasticsearch.compute.aggregation.ValuesIntAggregatorFunctionTests

**Reproduction line:**
```
null
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
[Failure dashboard for `org.elasticsearch.compute.aggregation.ValuesIntAggregatorFunctionTests#classMethod`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('classMethod'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.compute.aggregation.ValuesIntAggregatorFunctionTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).

  at __randomizedtesting.SeedInfo.seed([EDC079DF42C286BD]:0)

```

**Comment by nik9000** [comment]
> `null`

Amazing

**Comment by nik9000** [comment]
A bunch of tests ran mega slow and timed out. That's what we get I guess.

It doesn't reproduce locally. I'll poke more tomorrow when I'm back.

**Comment by nik9000** [comment]
Most tests are running fast but `ValuesIntAgg` is slow here:
```
                     testMultivaluedWithNulls  93.727
                         testManyInitialFinal  39.214
                 testInitialIntermediateFinal 165.748
              testManyInitialManyPartialFinal 136.727
                    testNullIntermediateFinal   0.024
        testManyInitialManyPartialFinalRunner 353.345
                         testSimpleLargeInput   0.523
                   testEmptyInputInitialFinal   0.145
                         testSimpleWithCranky   0.068
       testEmptyInputInitialIntermediateFinal   0.058
                             testInitialFinal 378.527
                        testSimpleDescription   0.089
                               testEmptyInput   0.169
                             testIgnoresNulls   0.941
testManyInitialManyPartialFinalRunnerThrowing   0.285
                              testMultivalued  30.53
```

This doesn't reproduce. At all. It takes 20 seconds locally.

Here's the logging for some of the slow ones:
```
[2024-06-19T15:30:31,940][INFO ][o.e.c.a.ValuesIntAggregatorFunctionTests] [testInitialFinal] before test
[2024-06-19T15:36:50,455][INFO ][o.e.c.a.ValuesIntAggregatorFunctionTests] [testInitialFinal] after test
[2024-06-19T15:24:37,801][INFO ][o.e.c.a.ValuesIntAggregatorFunctionTests] [testManyInitialManyPartialFinalRunner] before test
[2024-06-19T15:30:31,127][INFO ][o.e.c.a.ValuesIntAggregatorFunctionTests] [testManyInitialManyPartialFinalRunner] after test
```

Here's the stacktrace around the timeout:
```
  2> 	at app//org.hamcrest.core.IsEqual.areEqual(IsEqual.java:40)
  2> 	at app//org.hamcrest.core.IsEqual.matches(IsEqual.java:23)
  2> 	at app//org.hamcrest.collection.IsIterableContainingInAnyOrder$Matching.isMatched(IsIterableContainingInAnyOrder.java:69)
  2> 	at app//org.hamcrest.collection.IsIterableContainingInAnyOrder$Matching.matches(IsIterableContainingInAnyOrder.java:54)
  2> 	at app//org.hamcrest.collection.IsIterableContainingInAnyOrder.matchesSafely(IsIterableContainingInAnyOrder.java:25)
  2> 	at app//org.hamcrest.collection.IsIterableContainingInAnyOrder.matchesSafely(IsIterableContainingInAnyOrder.java:14)
  2> 	at app//org.hamcrest.TypeSafeDiagnosingMatcher.matches(TypeSafeDiagnosingMatcher.java:57)
  2> 	at app//org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:10)
  2> 	at app//org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
  2> 	at app//org.elasticsearch.test.ESTestCase.assertThat(ESTestCase.java:2303)
  2> 	at app//org.elasticsearch.compute.aggregation.ValuesIntAggregatorFunctionTests.assertSimpleOutput(ValuesIntAggregatorFunctionTests.java:41)
  2> 	at app//org.elasticsearch.compute.aggregation.Aggrega  2> torFunctionTestCase.assertSimpleOutput(AggregatorFunctionTestCase.java:82)
  2> 	at app//org.elasticsearch.compute.aggregation.AggregatorFunctionTestCase.testMultivalued(AggregatorFunctionTestCase.java:115)
```

I've opened a PR (#110001) to speed up the tests. I don't think the timeout is actually the fault of the test, but it's something.
