### ISSUE TITLE
Query templates don't play nice with Expression script queries requiring parametrs

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#10992]
A query template containing a clause like this:

```
                                         "script": {
                                            "script": "doc['myfield'].value < param1 - 1000*60*60*24*5",
                                            "lang": "expression",
                                            "params": {
                                              "param1": "{{foo}}"
                                            }
                                          }
```

Doesn't work, executing it with a numeric constant as a parameter will throw saying the parameter has to be numeric (and it is).

**Comment by rjernst** [comment]
I think the problem is query templates can really only deal with string parameters, because in order to fill in template parameters can only be described in strings. I think what we need to do is "pass through" the type, so running your query template with this should work:

```
GET /_search
{
    "query": {
        "template": {
            "query": ..., 
            "params" : {
                "foo" : 10
            }
        }
    }
}
```
However, at a quick glance it doesn't seem like mustache has this ability. @uboness any ideas?

**Comment by clintongormley** [comment]
This works as long as the template is saved as a file, eg: save this as `config/scripts/test.mustache`:

    {
      "script_fields": {
        "FIELD": {
          "script": "param + 123",
          "lang": "expression",
          "params": {
            "param": {{param}}
          }
        }
      }
    }

Then this request works:

    GET _search/template
    {
      "template": "test",
      "params": {
        "param": 10
      }
    }

It also works when storing the template in .scripts index as a string:

    POST _search/template/x
    {
      "template": "{  \"script_fields\": {    \"FIELD\": {      \"script\": \"param + 123\",      \"lang\": \"expression\",      \"params\": {        \"param\": {{param}}      }    }  }}"
    }

However, passing the same script as an inline string doesn't:

    GET _search/template
    {
      "template": "{  \"script_fields\": {    \"FIELD\": {      \"script\": \"param + 123\",      \"lang\": \"expression\",      \"params\": {        \"param\": {{param}}      }    }  }}",
      "params": {
        "param": 1
      }
    }

Throws this exception:

    Failed to parse template]; nested: JsonParseException[Unexpected character ('{' (code 123)): was expecting either valid name character (for unquoted name) or double-quote (for quoted) to start field name

**Comment by clintongormley** [comment]
@MaineC is this related to #8393?

**Comment by colings86** [comment]
@clintongormley I just tested your steps on master and the new script API logic has resolved the issue, inline, file and index templates work with your template content using both the new API and the old one.

**Comment by gkozyryatskyy** [comment]
This 
`curl -XPOST localhost:9200/_scripts/mustache/scr1 -d '{"template" : { "size" : {{size}} }}'`
still throws an exception
`{
   "error":{
      "root_cause":[
         {
            "type":"illegal_argument_exception",
            "reason":"failed to parse template script"
         }
      ],
      "type":"illegal_argument_exception",
      "reason":"failed to parse template script",
      "caused_by":{
         "type":"json_parse_exception",
         "reason":"Unexpected character ('{' (code 123)): was expecting either valid name character (for unquoted name) or double-quote (for quoted) to start field name\n at [Source: [B@8133db3; line: 1, column: 28]"
      }
   },
   "status":400
}
`

elasticsearch 2.2.0

**Comment by clintongormley** [comment]
@gkozyryatskyy your exception has nothing to do with this issue. You are passing invalid JSON, so you need to pass your template as a string instead.

**Comment by gkozyryatskyy** [comment]
@clintongormley Thx for you reply. I understand the problem, but is there any other api to pass templates with out json validation? Now Im using java api PutIndexedScriptRequestBuilder.
