### ISSUE TITLE
Aggregation to calculate the number of buckets in a given aggregation

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#11008]
This aggregation will take the output of any multi bucket sibling aggregation and return the number of buckets in that aggregation.

**Comment by colings86** [comment]
The use case for this feels very weak and not useful at all so this PR will be closed until we have a more compelling use case for adding it in. Most of the applications of this aggregation would also be covered by finding the length of the buckets array in the original aggregation

**Comment by acarstoiu** [comment]
Here is a simple use case: you don't want to get all the buckets over the network, you just want their count. You could simply instruct _Elasticsearch_ to drop the results of basic aggregations and keep the pipeline aggs - see #15823.
