### ISSUE TITLE
Documentation for Index Modules > Store does not explain all options

### ISSUE THREAD

**Issue by Xylakant** [elastic/elasticsearch#11000]
The documentation at http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-indices.html#throttling mentions that the settings for `indices.store.throttle.type` are `merge`, `none`, `all` and refers to http://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-store.html for further detail. However, the referenced page does not explain all options, most notably `all` is missing. The referenced page also continues to say 

    (...) it can be set as well using the index.store.throttle.type, and index.store.throttle.max_bytes_per_sec.  
    The default value for the type is `node` (...)

adding yet another unexplained option (`node`).

**Comment by clintongormley** [comment]
I've improved the docs - hope this helps.

**Comment by Xylakant** [comment]
I'm still confused: What does `indices.store.throttle.type: none` do?

And what are the valid values for `index.store.throttle.type` and what do they do? `node` is mentions, but the exact implications are unclear to me.

**Comment by clintongormley** [comment]
`none` turns off throttling.  `index.store.throttle.type` can be set to `none`, `merge`, `all`, or if not set then it uses the node level setting (not an index level setting).

note: these settings have been removed from the docs in master, because we don't think you should be setting them :)

**Comment by Xylakant** [comment]
what's the replacement on the node level

**Comment by clintongormley** [comment]
What do you mean?

**Comment by Xylakant** [comment]
sorry, I misread your previous comment. So none turns off store level throttling as in "unlimited"?

**Comment by clintongormley** [comment]
yes, "no throttling" :)
