### ISSUE TITLE
About Elasticsearch License

### ISSUE THREAD

**Issue by reggiechen31** [elastic/elasticsearch#110018]
### Description

The licenses of the Elasticsearch 7.11 and later versions are changed from apache 2.0 to SSPL and Elastic license.If we use the 7.10 and earlier versions, does it still comply with Apache2.0?
Thank you

**Comment by albertzaharovits** [comment]
@reggiechen31 please use our discuss forum for questions in general: https://discuss.elastic.co/t/will-elasticsearch-7-10-allow-me-to-remain-under-apache-2-0-license/288898 .
We use github to track & discuss code changes only.
