### ISSUE TITLE
Unnecessarily slow performance from Ingest date processors when a templated timezone or locale are used

### ISSUE THREAD

**Issue by joegallo** [elastic/elasticsearch#110191]
Mustache template application can be (relatively) expensive, especially in the case of ingest processor execution where we necessarily have to perform it on every document.

There's an edge case of the `date` ingest processor where template application is applied in a loop. Consider the following:

```
PUT _ingest/pipeline/date
{
  "processors": [
    {
      "date": {
        "timezone": "{{{ timezone }}}",
        "field": "date",
        "formats": [
          [...]
        ]
      }
    }
  ]
}

POST _ingest/pipeline/date/_simulate
{
  "docs": [
    {
      "_index": "index",
      "_id": "id",
      "_source": {
        "date": "funtimesahead",
        "timezone": "UTC"
      }
    }
  ]
}
```

In this case, for each document that's processed by the pipeline, we'd attempt to parse `"funtimesahead"` with each format in order until the value is successfully parsed -- that's fine (so to speak). What's not fine is that we happen to run mustache template evaluation inside that loop! The timezone is always going to be `"UTC"` and we can apply the template just once before the loop in order to determine that.

The same issue applies for locale.

-----

Separately (and I doubt there's much we can do about this without eating a breaking change, though perhaps we should document it) -- using a templated value for timezone and locale is not cooperative when the values might not be present. (edit: TODO I need to write this up better, this might warrant being its own separate bug, but I needed somewhere to put the note for now so it's not lost to time.)

**Comment by kanoshiou** [comment]
Hi, I’ve submitted a PR to fix the problem. The templates are now evaluated once before the loop, which should improve efficiency. Please review the PR and let me know if there are any concerns or further improvements needed.
