### ISSUE TITLE
Deep structured Document has issue when using term query.

### ISSUE THREAD

**Issue by toyangxia** [elastic/elasticsearch#11020]
I created two documents. One with deep structure and the other just flat string document:
curl -XPOST http://localhost:9200/test/test/ -d '
{
  "foo" : {"bar":"val_WILL_NOT_SHOW", "txt" : "val_THIS_EITHER"}
}'

curl -XPOST http://localhost:9200/test/test/ -d '
{
  "action" : "login"
}'

When I query  them, the structured document CANNOT be returned:
curl -XGET 'http://localhost:9200/test/test/_count' -d '
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "foo.bar": "val_WILL_NOT_SHOW"
          }
        }
      ]
    }
  }
}'

The flat string document works fine:
curl -XGET 'http://localhost:9200/test/test/_count' -d '
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "action": "login"
          }
        }
      ]
    }
  }
}'

**Comment by jpountz** [comment]
I suspect your issue is not related to deep nesting but to the fact that you are using the `term` query on an `analyzed` string. You should either use the `match` query instead or index your string fields as `not_analyzed`. This reproduction works for me:

```
DELETE test 

PUT test 
{
  "mappings": {
    "test": {
      "properties": {
        "action": {
          "type": "string",
          "index": "not_analyzed"
        },
        "foo": {
          "properties": {
            "bar": {
              "type": "string",
              "index": "not_analyzed"
            },
            "txt": {
              "type": "string",
              "index": "not_analyzed"
            }
          }
        }
      }
    }
  }
}

POST test/test
{
  "foo" : {"bar":"val_WILL_NOT_SHOW", "txt" : "val_THIS_EITHER"}
}

POST test/test
{
  "action" : "login"
}

GET /test/test/_count
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "foo.bar": "val_WILL_NOT_SHOW"
          }
        }
      ]
    }
  }
}
```
