### ISSUE TITLE
Ingest node: terminate processor

### ISSUE THREAD

**Issue by andrewkroh** [elastic/elasticsearch#110218]
### Description

Add a new ingest processor to terminate processing. When the processor is invoked, then execution of the ingest pipeline stops (control returns to calling pipeline if there is one).

A pattern we use today in pipelines to abort additional processing is to invoke the `fail` processor which jumps to the pipeline's on_failure handler, but this has the unwanted side-effect of being associated with a failure state and invokes additional processors (`on_failure`).

This [pipeline](https://github.com/elastic/integrations/blob/35fc7a1a53e5375f3906f56eceac701bdb00616a/packages/qualys_vmdr/data_stream/user_activity/elasticsearch/ingest_pipeline/default.yml#L7-L10) is an example of where this would be used. I would rather abort the processing at this point without adding a failure message.

**Comment by PeteGillinElastic** [comment]
I didn't realize that I also need to edit `processors.asciidoc` to actually make the docs show up. PR for that out now.

**Comment by andrewkroh** [comment]
Is updating `elasticsearch-specification` normally in-scope for when a new processor is added? This would enable derivatives of the spec, like API clients and the Kibana Dev Console autocomplete, to know about the processor.

https://github.com/elastic/elasticsearch-specification/blob/53edb7836cd4d15fc15c1341a5eb7bf9dfb5d50a/specification/ingest/_types/Processors.ts#L31

**Comment by dakrone** [comment]
@andrewkroh it's supposed to be in scope whenever we make user-facing changes or additions, but we frequently forget about it. Thanks for the reminder!

**Comment by PeteGillinElastic** [comment]
> Is updating `elasticsearch-specification` normally in-scope for when a new processor is added? This would enable derivatives of the spec, like API clients and the Kibana Dev Console autocomplete, to know about the processor.
> 
> https://github.com/elastic/elasticsearch-specification/blob/53edb7836cd4d15fc15c1341a5eb7bf9dfb5d50a/specification/ingest/_types/Processors.ts#L31

Oh, I didn't know this was a thing. (Sorry, I'm still new here!) I'll raise a PR, assuming I can figure out how to cargo-cult the typescript...

**Comment by PeteGillinElastic** [comment]
https://github.com/elastic/elasticsearch-specification/pull/3003 out for review

**Comment by PeteGillinElastic** [comment]
I think this is finally all done!
