### ISSUE TITLE
LogsDB - Indexing overhead performance testing of `ignore_malformed`

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#110255]
### Description

LogsDB uses stored fields under the hood to deal with malformed field values and as a fallback mechanism in situations where doc values are not available. This behaviour favours user experience at the expense of performance, especially indexing performance (CPU/memory overhead). A significant factor is that supporting `ignore_malformed` needs some copying of different data structures involved in the parsing logic. These copy operations occur whenever `ignore_malformed` is enabled for complex field types where the entire field content must be preserved to handle potential parsing issues with nested values. In such scenarios, the copied data structures are used to capture and store malformed values.

We need to evaluate the performance penalty introduced by this logic and understand its impact especially on indexing throughput. Ideally we would like run two tests using the same index mode but with and without `ignore_malformed` enabled. Note also that standard log templates enable `ignore_malformed` by default in order to avoid data loss.

The outcome of this benchmarking activity is crucial for planning any necessary actions to mitigate performance issues in the event of unacceptable overhead.

**Comment by kkrik-es** [comment]
`ignore_above` does this as well, at least for `flattened` fields. We should include that in our testing as well.

**Comment by dnhatn** [comment]
I ran two benchmarks where we randomly injected malformed values for the ip and date fields (excluding `@timestamp`) at rates of 1% and 50%. Overall, the results look good.

[1_percent.txt](https://github.com/user-attachments/files/17053129/1_percent.txt)
[50_percent.txt](https://github.com/user-attachments/files/17053130/50_percent.txt)

**Comment by kkrik-es** [comment]
We're also worried that there's a default tax when we enable `ignore_malformed` and `ignore_above` at the index level, as some mappers create copies of their values "just in case", so the overhead is there even if there are no malformed values. Is it possible to test this, i.e. have a run where the value is set for all indexes and another where it's unset? It may be tricky if some indexes override the value in their template, in elastic/logs..

**Comment by lkts** [comment]
I think we want to evaluate impact of using `CopyingXContentParser` which means we need to benchmark with field types like `histogram`, 'geo_point`, `aggregate_metric_double`, `flattened` with and without `ignore_malformed`. We expect to see some impact when `ignore_malformed` is enabled _even if there are no malformed values at all_ and the goal is to see how significant it is. If it is significant we may need to reconsider the approach to handle `ignore_malformed` in such cases.

**Comment by dnhatn** [comment]
```
|   Mean Throughput | index-append | 274835           | 267826           | -7009.51    | docs/s |   -2.55% |
| Median Throughput | index-append | 276432           | 267062           | -9370.01    | docs/s |   -3.39% |
```

I benchmarked the `geo_point` track with `ignore_malformed` and synthetic_source, and the indexing throughput decreased by several percent. This reduction is expected, as we unconditionally copy tokens in CopyingXContentParser. Unfortunately, we don’t have rally tracks with histogram types, which are expected to have larger overhead with CopyingXContentParser.

[geopoint.txt](https://github.com/user-attachments/files/17102359/geopoint.txt)
