### ISSUE TITLE
Reduce allocations in Metadata#Builder#updateAliases

### ISSUE THREAD

**Issue by ywangd** [elastic/elasticsearch#110217]
[Updating aliases](https://github.com/elastic/elasticsearch/blob/29c5b4950cf8c8639c01a275204f21d3ef2aee51/server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java#L1894) is part of handling cluster state publication. Slowness in this process can cause the node to lag behind and eventually leave the cluster (this has already been observed). Currently the code has some inefficiency when there are many aliases associated to an index and there are many updated indices.

For an index, we loop through each alias to add it
https://github.com/elastic/elasticsearch/blob/29c5b4950cf8c8639c01a275204f21d3ef2aee51/server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java#L1896-L1898

The `putAlias` method allocates a `HashSet` on each invocation
https://github.com/elastic/elasticsearch/blob/29c5b4950cf8c8639c01a275204f21d3ef2aee51/server/src/main/java/org/elasticsearch/cluster/metadata/Metadata.java#L1925-L1929

The new `HashSet` is created to only add a single item (or nothing at all if the alias already exists). If there are many aliases, there will be many `HashSet` allocations which is rather wasteful. The `removeAlias` method also has a similiar inefficiency. We should look into ways for optimization.

**Comment by DaveCTurner** [comment]
See also https://github.com/elastic/elasticsearch/issues/104456 for a more general issue about sizing guidance for aliases.
