### ISSUE TITLE
Discrepancy in Arabic Snowball Stemmer for the word "بطاطس"

### ISSUE THREAD

**Issue by ShamikMukhopadhyay** [elastic/elasticsearch#110274]
### Elasticsearch Version

7.17.3

### Java Version

_bundled_

### OS Version

Linux elasticsearch-client-0 5.15.0-1058-gke #63-Ubuntu SMP Thu Apr 18 16:09:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

I am experiencing a discrepancy in the stemming results for the Arabic word "بطاطس" between Elasticsearch and an online Arabic stemmer tool. (https://arabicstemmer.com/)

### Steps to Reproduce

Steps to Reproduce:

Run the following _analyze API call in Elasticsearch:
```
GET /_analyze
{
  "text": "بطاطس",
  "analyzer": "arabic"
}
```
Compare the output with the online tool: https://arabicstemmer.com/
Elasticsearch output: "بطاطس"
Online tool output: "طاطس"
Expected Behavior:
The stemmed output for "بطاطس" should be consistent with the online tool, which stems it to "طاطس".

Actual Behavior:
Elasticsearch does not stem the word "بطاطس" and returns it unchanged.

Additional Information:

Elasticsearch Analyzer Configuration: Using the default Arabic analyzer.
Attached are screenshots showing the discrepancy in stemming results.

Screenshots

<img width="895" alt="Screenshot 2024-06-28 at 16 50 34" src="https://github.com/elastic/elasticsearch/assets/89913154/1bf80f9e-0b8b-4427-9796-8c7fb3b5d030">

<img width="1163" alt="Screenshot 2024-06-28 at 16 50 58" src="https://github.com/elastic/elasticsearch/assets/89913154/18584fe1-9db9-4c67-a04f-24abe3d93454">

**Comment by benwtrent** [comment]
@ShamikMukhopadhyay this is because the stemmers are functionally different, the online one is the `snowball` stemmer, which does support multiple languages. This is not the default one used in the arabic analyzer.

If you want the same output as the snowball stemmer, you can use that instead of the arabic analyzer in ES. 

Here is an example of a custom analyzer using other arabic settings but with the snowball stemmer.

```PUT /arabic_example
{
  "settings": {
    "analysis": {
      "filter": {
        "arabic_stop": {
          "type":       "stop",
          "stopwords":  "_arabic_" 
        },
        "arabic_keywords": {
          "type":       "keyword_marker",
          "keywords":   ["مثال"] 
        },
        "arabic_stemmer": {
          "type":       "snowball",
          "language":   "Arabic"
        }
      },
      "analyzer": {
        "snowball_arabic": {
          "tokenizer":  "standard",
          "filter": [
            "lowercase",
            "decimal_digit",
            "arabic_stop",
            "arabic_normalization",
            "arabic_keywords",
            "arabic_stemmer"
          ]
        }
      }
    }
  }
}
```
