### ISSUE TITLE
Fix path to elasticsearch jar in elasticsearch.in.bat for developer proposes

### ISSUE THREAD

**Issue by comdiv** [elastic/elasticsearch#11038]
Now elasticsearch.in.bat assumes that 
elasticsearch-* is placed in 
%ES_HOME%/lib/elasticsearch-*.jar;
but after usual 
mvn clean package -DskipTests elasticsearch is compiled not  to  %ES_HOME%/lib/ but %ES_HOME%/
so it's more friendly to add both paths to elasticsearch.in.bat

**Comment by clintongormley** [comment]
@comdiv On my system, it is compiled to `./target/`, and the packages placed into `./target/releases`.  Most developers would run elasticsearch through the IDE, or by unpacking the zip.  

`./bin/elasticsearch` is intended for the packaged version - I'm not sure I want to extra paths to it.

**Comment by comdiv** [comment]
It doesn't break usual usage. But allow to launch elastic search process for quick checking.

**Comment by rjernst** [comment]
You can use `mvn exec:exec` to do a quick check of actually running elasticsearch. Note this requires first running `mvn compile`.

**Comment by comdiv** [comment]
thx
