### ISSUE TITLE
ES return different result every time for more like this query for same document searched 

### ISSUE THREAD

**Issue by dobariya** [elastic/elasticsearch#11037]
I have some 16 text documents with enough content  in each.
step 1: I index them with a string type field named "content" with store =false and TermVectorOption.WithPositions.
Now i make a request for more like this query as below 

{
 "query": {
    "more_like_this" : {
        "fields" : ["content"],
       "ids" : ["AU0uWRRxsLZwpQ7lzURn"],
        "min_term_freq": 1,
        "min_doc_freq": 1
    }
    }
}

step 2: I get the result and i note down the documents returned with score.

Step 3: Now I delete whole index by issuing below command

http://local:9200/test 

returning 

{
    "acknowledged": true
}

which confirms whole index is deleted

Now again i take same 16 documents and index again resulting every time it index same documents with different sequence and step 2 I get different result and score for same document I searched in step 1.

Is this a bug or am i missing anything to set?

**Comment by clintongormley** [comment]
Hi @dobariya 

I'm assuming that you're indexing these documents without specifying an ID, which means that each doc gets an autogenerated ID, and is assigned to a different shard each time that you reindex.  This means that the term frequencies are different for each reindex, which gives you the different results.

See http://www.elastic.co/guide/en/elasticsearch/guide/current/relevance-is-broken.html for a fuller explanation.

Please feel free to reopen if my assumptions are incorrect.

**Comment by dobariya** [comment]
Thanks @clintongormley  for the reply.
Yes i can understand the logic behind auto generated Id.
Is it required to index documents in sequence with a sequence id?because am indexing documents with parallel thread running for indexing and i used sequence id but its still not working.If i remove parallel thread indexing with sequence id input then it works well.
Is it mandatory to index documents in sequence with sequence id ?

For eg:

if i index documents in the following sequence id it works
1,2,3,4,5,6

but if i index in the following way then it does not work
2,6,4,1,3,5

if its mandatory to follow first method then it's a burden to index in sequence which will affect speed.I need to index 1 million documents in an hour or 2 which i can only achieve with parallel threads running.

Please help me suggest how to index the documents so that i can get same relevancy for every time i re index

**Comment by clintongormley** [comment]
@dobariya Either (a) have one shard or (b) have enough data.  Term statistics will even out the more data you have..

As I said, read this: http://www.elastic.co/guide/en/elasticsearch/guide/current/relevance-is-broken.html

It explains it all
