### ISSUE TITLE
http 401

### ISSUE THREAD

**Issue by liqunlin** [elastic/elasticsearch#110315]
### Elasticsearch Version

7.9.3

### Installed Plugins

analysis-icu,analysis-ik,analysis-pinyin,analysis-smartcn,elasticsearch-analysis-ansj,repository-s3 ,sql

### Java Version

openjdk version "15" 2020-09-15

### OS Version

Linux p-l67-32-16 5.15.81

### Problem Description

When we were doing a master-slave cluster switch drill, we found a large number of authentication exception logs http 401, The actual account authorization is normal

### Steps to Reproduce

You can shut down all cluster nodes and restart them to reproduce the HTTP 401 error. You can also switch the domain name from the primary cluster to the backup cluster to reproduce the HTTP 401 error.

### Logs (if relevant)

1、the service code log was Caused by: co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/search] failed: [security_exception] ation [indices:data/read/search] is unauthorized for user [jxsarvr_es]
2、The load layer log is { "_index": "nginx-es-2024.07.01","_type": "access","_id": "kfRcbJABRmWLQ4b-KHkM","_version": 1, "_score": null, "_source": { "scheme": "http", "upstream_addr": "10.28.101.135:9212", "body_bytes_sent": 687, "autolog_uri_prefix": "/syzy_vr_series_dealer/_search", "request_method": "POST", "type": "", "sent_http_cache_control": "-", "http_user_agent": "elastic-java/8.11.0 (Java/1.8.0_191)", "reqid": "-", "upstream_status": 401, "upstream_cache_status": "-", "request_time": "0.000", "auto_business_enname": "es", "host_addr": "jxs-zxdp-ha-es79.search.corpautohome.com", "remote_addr": "10.248.45.56", "autolog_real_ip": "10.248.45.56", "http_X_Forwarded_For": "-", "server_addr": "10.28.8.117", "request_uri": "/syzy_vr_series_dealer/_search?typed_keys=true", "date_pre": "2024.07.01", "@timestamp": "2024-07-01T03:34:56.000Z", "http_referer": "-", "upstream_response_time": 0, "cachezone": "", "status": 401 }

**Comment by DaveCTurner** [comment]
Thank you very much for your interest in Elasticsearch. Unfortunately the issue you have reported relates to Elasticsearch version 7.9.3 which is very old and has passed [end-of-life](https://www.elastic.co/support/eol). We will not investigate issues related to unsupported versions here on Github, so I am closing this to indicate that no action is needed from the Elasticsearch development team. It's possible that you will find a volunteer to help you with this issue on the [community forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), but our strong recommendation would be to upgrade to a supported version of Elasticsearch as a matter of some urgency. If you can reproduce your issue on a supported version then please open a fresh bug report.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.

**Comment by liqunlin** [comment]
Ok, thanks for your reply, I will try your suggestion
