### ISSUE TITLE
Configure elasticsearch logging to be NDJSON

### ISSUE THREAD

**Issue by pgomulka** [elastic/elasticsearch#110415]
### Description

elasticsearch logs are currently in JSON format, but can be split in multiple lines when an exception is being logged.
This might cause other parsing tools like `Fluentbit` to fail.
Filebeat is able to cope with those as per this test https://github.com/elastic/beats/blob/master/filebeat/module/elasticsearch/server/test/test-json.log 

can we add a node setting so that this behaviour can be configured and log lines are not split?
alternatively we should document that logs are **NOT** ndjson

**Comment by DaveCTurner** [comment]
> alternatively we should document that logs are NOT ndjson

I think we should do that right away, regardless of the outcome of this discussion item and its impact on future ES versions.
