### ISSUE TITLE
"key_as_string" keys in the percentile aggregation response

### ISSUE THREAD

**Issue by mattruzicka** [elastic/elasticsearch#11049]
I'm using version  "1.5.1"

By default, my percentile aggregations are returning like this, with "as_string" keys:
```
"aggregations": {
      "load_time_outlier": {
         "values" : {
            "1.0": 15,
            "1.0_as_string": "15",
            "5.0": 20,
            "5.0_as_string": "20",
            "25.0": 23,
            "25.0_as_string": "23",
            "50.0": 25,
            "50.0_as_string": "25",
            "75.0": 29,
            "75.0_as_string": "29",
            "95.0": 60,
            "95.0_as_string": "60",
            "99.0": 150,
            "99.0_as_string": "150",
         }
      }
   }
}
```
But the docs say:

"By default, the percentile metric will generate a range of percentiles: [ 1, 5, 25, 50, 75, 95, 99 ]. The response will look like this:"
```

"aggregations": {
      "load_time_outlier": {
         "values" : {
            "1.0": 15,
            "5.0": 20,
            "25.0": 23,
            "50.0": 25,
            "75.0": 29,
            "95.0": 60,
            "99.0": 150
         }
      }
   }
}
```
- http://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-aggregation.html

I don't believe I'm passing any format options, but it's possible the elasticsearch-ruby driver is without my knowledge. 

I'm thinking this might be a bug. Seems similar to https://github.com/elastic/elasticsearch/issues/6655

If it's not a bug, is there a way to disable the "as_strings" keys from returning in the percentile aggregation response? 

Thanks.

**Comment by gmarz** [comment]
Hey @mattruzicka this has been fixed in 1.5.2.

See https://github.com/elastic/elasticsearch/pull/10571 for details.
