### ISSUE TITLE
Security API endpoints still in beta?

### ISSUE THREAD

**Issue by ezimuel** [elastic/elasticsearch#110435]
I noticed, in the `rest-api-spec` folder that we still have 2 enpoints marked as beta in the specification:
- [security.update_cross_cluster_api_key](https://github.com/elastic/elasticsearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/api/security.update_cross_cluster_api_key.json)
- [security.create_cross_cluster_api_key](https://github.com/elastic/elasticsearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/api/security.create_cross_cluster_api_key.json)

Can we mark these as stable, using `"stability": "stable"` ? If yes, I can provide a PR if needed.
Thanks!

**Comment by n1v0lg** [comment]
@ezimuel good catch, these are indeed GA now 👍

**Comment by ezimuel** [comment]
@n1v0lg I created PR https://github.com/elastic/elasticsearch/pull/110862 to fix this.
