### ISSUE TITLE
Adapt /bin/elasticsearch to launch under windows (msys) bash

### ISSUE THREAD

**Issue by comdiv** [elastic/elasticsearch#11044]
Base OS for our team is Windows but we build cross-platform .net/mono applications so main host for our shell scripts is bash for windows (msys) not cmd.exe. So it's not much comfortable when bash scripts in bin are adapted only for Unix

**Comment by comdiv** [comment]
closed in d50d37c (comdiv fork)

**Comment by clintongormley** [comment]
Hi @comdiv 

Did you mean to close this, or would you like to send this as a PR?

**Comment by comdiv** [comment]
I close it my branch. Don't know you policy well. Here it's PR ).
What to do further?
