### ISSUE TITLE
Something may wrong when update the weight's of a doc to change the score of the result of complete suggestion when the doc size is large.

### ISSUE THREAD

**Issue by yuikns** [elastic/elasticsearch#11040]
Here is a mapping of index

````
{
    "settings": {
        "analysis": {
            "analyzer": {
                "name_analyzer": {
                    "type": "custom",
                    "tokenizer": "standard",
                    "filter": [ "standard", "lowercase" ]
                }
            }
        }
    },
    "mappings": {
        "doc": {
            "properties": {
                "suggest": {
                    "type": "completion",
                    "analyzer": "name_analyzer",
                    "payloads": true
                }
            }
        }
    }
}
````

Insert a doc : 
````
$ curl -XPUT localhost:9200/sample/doc/1 -d '{
"suggest" : {
 "output" : "1" ,
 "input" : [ "info" ],
 "weight" : 100
 }
}'
{"_index":"sample","_type":"doc","_id":"1","_version":1,"created":true}
````

And then , I try to query this doc, get result as follow : 
````
$ curl -X POST 'localhost:9200/sample/_suggest?pretty' -d '{
"sample-suggest" : {
"text" : "in",
"completion" : {
"field" : "suggest"
}}}'
{
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "sample-suggest" : [ {
    "text" : "in",
    "offset" : 0,
    "length" : 2,
    "options" : [ {
      "text" : "1",
      "score" : 100.0  # << this score equals the weight I had settted
    } ]
  } ]
}
````

And then, I update this doc's weight  from 100 to 3
````
$ curl -XPUT localhost:9200/sample/doc/1 -d '{
"suggest" : {
 "output" : "1" ,
 "input" : [ "info" ],
 "weight" : 3
 }
}'
{"_index":"sample","_type":"doc","_id":"1","_version":2,"created":false}
````

Let's check this doc again : 
````
$ curl http://localhost:9200/sample/doc/1
{"_index":"sample","_type":"doc","_id":"1","_version":2,"found":true,"_source":{
"suggest" : {
 "output" : "1" ,
 "input" : [ "info" ],
 "weight" : 3
 }
}}
````
It had also updated.

And then, I request a suggestion again.
````
$ cur-X POST 'localhost:9200/sample/_suggest?pretty' -d '{
"sample-suggest" : {
"text" : "in",
"completion" : {
"field" : "suggest"
}}}'
{
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "sample-suggest" : [ {
    "text" : "in",
    "offset" : 0,
    "length" : 2,
    "options" : [ {
      "text" : "1",
      "score" : 3.0
    } ]
  } ]
}
````
the score updated from 100 to 3.

------------------------------------

However, my index with 38M docs(with size about 64G Byte). When I update the doc as below.
I can also curl this doc, and found the weight had been changed, however, when I use the suggestion, It always give me the old score back.

I'm not sure is there something wrong when I  was trying to update those docs. Any replies are appreciated.

**Comment by clintongormley** [comment]
Hi @yuikns 

The completion suggester currently doesn't take deletions into account:

> The suggest data structure might not reflect deletes on documents immediately. You may need to do an Optimize for that. You can call optimize with the only_expunge_deletes=true to only cater for deletes or alternatively call a Merge operation.

An update is really a delete+index-new-doc, so the deletions hang around until they are garbage collected by the merge process.  The new suggester (https://github.com/elastic/elasticsearch/issues/10746) will take deletions into account

**Comment by yuikns** [comment]
@clintongormley  Thanks your your reply.
