### ISSUE TITLE
Overriding path.home with bin/elasticsearch causes ClassNotFoundExceptions 

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#11048]
With the addition of security manager, we now restrict reads/writes to anything within known paths. When path.home is overriden, `bin/elasticsearch` does not know about it. Instead the script uses the base dir of wherever `bin/elasticsearch` is located, and sets up the classpaths based on this. When the security policy is created with the overridden path.home, it does not know about this other path, and so any classes loaded after security manager is installed will fail to load.

We have a couple possible fixes:
* Don't allow overriding path.home. To do this properly, we need to check it in the startup scripts, or bootstrap (it is a little weird to be checking this outside environment, but maybe do it with a helper method in Environment? `Environment.validateSettings` or something?)
* Pass bin and lib as extra settings from the startup script. This might be a bit of a pain to fix for all the tests the create nodes (or maybe not, we set path.home now in all nodes).
* Pass a somehow smartly named "other home" that is where the software actually exists (just one setting instead of two for bin/lib).

**Comment by rjernst** [comment]
@tlrx @rmuir Interested in your thoughts here.

**Comment by rmuir** [comment]
What is the use case? Can we please start underengineering this stuff instead of overengineering it. All paths need to be in environment... very simple :)

**Comment by tlrx** [comment]
@rjernst not sure to understand the use case, can you please give an exemple (env var, jvm option, command line)? thanks :)

**Comment by rjernst** [comment]
@tlrx The "use case" is specifying path.home to relocate data/logs/etc without specifying path.data, path.logs, etc. This used to work, but no longer does. The first question is do we want to support this at all?

Here is how to reproduce (from within elasticsearch installation dir):
```
mkdir myhome
cp -R config myhome/
bin/elasticsearch -Des.path.home=myhome
```

**Comment by clintongormley** [comment]
@rjernst note your recreation isn't correct as it just copies the contents of the `config` dir to `myhome/` - that's not going to work.  If you copy `lib/`, `bin/`, `config/`, and `plugins/` there then it will work correctly.

I don't think we want to support reconfiguring `path.home`, but  `./bin/elasticsearch` sets this value automatically today.  Not sure that we actually need to prevent overriding it. If you do override it, and point to somewhere that is missing what you need, then things error anyway.

I think we can just close this.

**Comment by rjernst** [comment]
Well, they error in a way that is not obvious what went wrong. But I guess this is advanced enough (since most people override specific dirs like `path.conf`, etc) that it's not worth doing any fancy checking.
