### ISSUE TITLE
Limit multi fields to relevant settings

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#11053]
Multi fields are more limited than regular fields. They cannot be object or nested types. There are also other settings like `copy_to` or `include_in_all` (any others?) that should not work. We should enforce this by rejecting these settings when parsed within a multi field.

**Comment by clintongormley** [comment]
+1

**Comment by clintongormley** [comment]
`copy_to` no longer works but `include_in_all`, `fields` and probably others do work - for clarity these should throw an exception

**Comment by paregos** [comment]
It looks like copy_to and include_in_all no longer work, is there a list of other fields that shouldn't work? 
Sorry if I misunderstood your comment but did you mean if the propName is fields within a multiField it should be rejected like if the propName is include_in_all within a multiField?

**Comment by javanna** [comment]
@elastic/es-search-aggs

**Comment by jtibshirani** [comment]
It looks like almost all options that should be rejected now are:
- `object` and `nested` fields are rejected (#10745)
- `copy_to` is disallowed with a clear error message (#15213)
- `include_in_all` is no longer supported

The last one that we may want to reject is `fields`, which would mean the user is defining multifields within a multifield. Although it seems a bit unusual, this is currently allowed and appears to work as expected. I wonder if we should just continue to allow the `fields` option, as it gives some flexibility without adding much complexity.

**Comment by jtibshirani** [comment]
After discussing internally, we decided we'd like to deprecate + remove support for chained multifields. I filed #41267 to track the issue and will close out this one.
