### ISSUE TITLE
Order by sum aggregation throws error in elastic search

### ISSUE THREAD

**Issue by yaskamal** [elastic/elasticsearch#11059]
I am trying to sort the aggregated result by applying another aggregation that does the summing and then applying order by descending to that sum.

if I try like below, the aggregation result get sorted by doc count.

    "order": {
        "revrsenestedowners": "desc"
    }
Below code explains the problem am facing. (field names are changed just to illustrate the problem)

"machines" is my nested object but the "owners" is not nested and it belongs to parent object.

I need to get the top 10 machines name by owners machine count (require sum as the owners object are list and can have more than one value).

    {
      "query": {
        "range": {
          "createdDate": {
            "gte": "2015-04-28T00:00:00",
            "lte": "2015-05-01T23:59:59"
          }
        }
      },
      "aggs": {
        "nestedagg": {
          "nested": {
            "path": "machines"
          },
          "aggs": {
            "terms": {
              "terms": {
                "field": "machines.machineName",
                "size": 10,
                  "order": {
                      "sumowners": "desc"
                   }
              },
              "aggs": {
                "revrsenestedowners": {
                  "reverse_nested": {},
                  "aggs": {
                    "sumowners": {
                      "sum": {
                        "field": "owners.machinesCount"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

I require the sum ordering and not the doc count ordering.
for it to work I may require something like :

    "order": {
        "revrsenestedowners.sumowners": "desc"
    }

Is there a way to achieve what I'm looking for.

Or Is this the limitation with elastic search? or a bug?

I'm stuck and really appreciate any help

**Comment by clintongormley** [comment]
As explained in the documentation for `order`, the syntax is `revrsenestedowners > sumowners.value`.

See   http://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-order

**Comment by yaskamal** [comment]
Thanks. I got it. 
Sorry couldn't get to the correct document. Thanks for pointing to right document.
Appreciate your help.
