### ISSUE TITLE
Enforce meta fields are set through the api, not inside a document

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#11051]
Some meta fields are currently allowed to be set within a document's source:
* `_all`
* `_id`
* `_parent`
* `_routing`
* `_timestamp`
* `_ttl`

In #6730 the ability to set a custom path for `_id` and `_routing` was removed. We should go one step further and not allow setting any meta fields within a document. These are special fields that the system uses for special purposes. There should be one way to set them, through the api.

**Comment by clintongormley** [comment]
+1

**Comment by jpountz** [comment]
+1!
