### ISSUE TITLE
Scripting: API to check executability and existence of script

### ISSUE THREAD

**Issue by bradvido** [elastic/elasticsearch#11066]
This is driven by Kibana scripted fields, https://github.com/elastic/kibana/issues/3797 but would be useful for many situations.

It would be nice if ElasticSearch had an API that could be called for validating scripts:

The client would provide a dynamic script or the name of a script file in `config/scripts` as well as a "test query" if the client wan't to validate that the script executes successfully against the query.

ES would validate:

1. If the ES config settings allow execution of the script 
2. If the script is a file, it would check that the file exists.
3. That the script is executable in the test query provided. Note that if there is a way to validate script (syntax etc. that should always be done).

**Comment by jdconrad** [comment]
My question is what is the difference in expectation of output between this and just running a test query against a script right now, and checking what errors are returned?

**Comment by bradvido** [comment]
Running the test and processing exceptions would work, but it leaves something to be desired. It doesn't seem very clean to me and programatically determining the actual problem from the ES exception is difficult.

Also, an API method to validate scripts won't generate errors in the ES log that could be confused with actual errors that need action taken.  

It's a "check" as opposed to an "attempt and see if it fails".

**Comment by clintongormley** [comment]
Hi @bradvido 

Really there is no way to check the script properly without executing it with a real query, with real params, and against real docs, ie: execute a search

However, the new structured exceptions make debugging the problem a whole lot easier than before. For instance, the following buggy script:

    GET /_search
    {
      "script_fields": {
        "FIELD": {
          "script": "foo+bar",
          "lang": "expression"
        }
      }
    }

returns the much more readable exception:

    {
       "error": {
          "root_cause": [
             {
                "type": "expression_script_compilation_exception",
                "reason": "Unknown variable [foo] in expression"
             }
          ],
          "type": "search_phase_execution_exception",
          "reason": "all shards failed",
          "phase": "query",
          "grouped": true,
          "failed_shards": [
             {
                "shard": 1,
                "index": "test123",
                "node": "v8K5ojNHQ6e24vQTtrrDPg",
                "reason": {
                   "type": "search_parse_exception",
                   "reason": "Failed to parse source [{\n  \"script_fields\": {\n    \"FIELD\": {\n      \"script\": \"foo+bar\",\n      \"lang\": \"expression\"\n    }\n  }\n}\n]",
                   "line": 6,
                   "col": 5,
                   "caused_by": {
                      "type": "expression_script_compilation_exception",
                      "reason": "Unknown variable [foo] in expression"
                   }
                }
             }
          ]
       },
       "status": 400
    }

Also, we already have the `_validate/query` API, which does pretty much what you're asking for, eg:

    GET /_validate/query?explain
    {
      "query": {
        "function_score": {
          "script_score": {
            "lang": "expression",
            "script": "foo"
          }
        }
      }
    }

returns:

    {
       "valid": false,
       "_shards": {
          "total": 1,
          "successful": 1,
          "failed": 0
       },
       "explanations": [
          {
             "index": "test123",
             "valid": false,
             "error": "[test123] script_score the script could not be loaded; org.elasticsearch.script.expression.ExpressionScriptCompilationException: Unknown variable [foo] in expression"
          }
       ]
    }

**Comment by benbenwilde** [comment]
This is no good. I want to run a script during reindex, but I want to run it asynchronously. But I'm stuck with the version where there is a bug with the reindex task going away when it finishes (or fails). So essentially I need to at least validate that the script file exists before running. So I try to validate using a search or something but it seems to run in a different context throwing random errors. So I'm currently resorting to running the search and seeing which kind of error it returns to identify if the script exists or not. It's really not a great solution.

**Comment by nik9000** [comment]
That sucks! You are very likely better off running reindex with a size of 1
synchronously and then kicking it off asynchronously.

At this point even if no matter the outcome of this issue you'll get the
fix for your async status  problem first because that is in 5.0. Any new
feature would only be available in subsequent versions anyway.
