### ISSUE TITLE
Transport exception processing BigDecimal type from groovy script

### ISSUE THREAD

**Issue by bradvido** [elastic/elasticsearch#11071]
I'm using ElasticSearch 1.5.2.

I have a **groovy** script_file 
`disk_total_free_percent.groovy`:

```
def totalSize = doc['Machine.disk_total_size_(mb)'].value;
def freeSpace = doc['Machine.disk_total_free_space_(mb)'].value;
if(totalSize == 0) { 
	//none is free, since the disk has no size
	0.0 //percent
}else {
	freeSpace / totalSize	
}
```
When I execute a search with `script_fields` including the above script, I get an error from ES
`[indices:data/read/search[phase/fetch/id]]]; nested: IOException[Can't write type [class java.math.BigDecimal]];` 
This is generated by [this line of code in StreamOutput.java](https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/common/io/stream/StreamOutput.java#L402)

It's also interesting that the number of shards that fail with this exception varies (for the same query). Sometimes it's 1, sometimes 2 or 3.

---
For comparison, I installed the **javascript** scripting plugin and tried the same script (replacing `def` with `var`)
`disk_total_free_percent.js`:

```
var totalSize = doc['Machine.disk_total_size_(mb)'].value;
var freeSpace = doc['Machine.disk_total_free_space_(mb)'].value;
if(totalSize == 0) { 
	//none is free, since the disk has no size
	0.0 //percent
}else {
	freeSpace / totalSize	
}
```
And **it worked** without any exceptions. This makes me think it's a problem with the Groovy scripting module.

**Comment by clintongormley** [comment]
@bradvido I've tried various combinations of mappings etc to replicate this problem on 1.5.2, and it all seems to work just fine.  Could you add a small recreation?  

For some reason Groovy is converting one of those values to BigDecimal (which we don't support), but I can't see why it is doing that.  I found this bug which may be related? http://jira.codehaus.org/browse/GROOVY-7238

**Comment by bradvido** [comment]
I should mention I'm running ES on Windows -- maybe the bug is platform specific

**Comment by dakrone** [comment]
We automatically convert BigDecimal constants to floating-point, see here: https://github.com/elastic/elasticsearch/pull/6609

**Comment by bradvido** [comment]
Hmm, then it shouldn't make a difference if i use literal decimals in my script.  I'll try to find a simple way so others can reproduce this.

**Comment by fredrlx** [comment]
Hi! I've run into a similar issue (same "Can't write type [class java.math.BigDecimal]" exception on some shards). Our groovy script had this line:
```
s = round(s*100)/100; 
```
rewriting it to the following got rid of the exception:

```
s = round(s*100d)/100d; 
```

**Comment by bradvido** [comment]
@fredrlx what version of ES & Groovy are you using?  #6609 should have already take care of this, but I've seen similar results.

**Comment by fredrlx** [comment]
@bradvido We were using ES 1.5.1 when we had this issue. How do I check what version of Groovy I have ? I'll update ES to a more recent version, but the issue was solved with the "d" postfix on constants.

**Comment by clintongormley** [comment]
This should be fixed by #12288 - I'm going to close for now, but feel free to reopen if you see the same thing on 1.7.0 or later

thaks

**Comment by bradvido** [comment]
Thanks. Will test on 1.7.0

**Comment by mausch** [comment]
Just hit this issue in 1.7.2. I know this is an old issue and an old version of ES, just wanted to say for future reference that changing an expression from `xxx.sum(0)` to `xxx.sum(0d)` as suggested above did the trick.
Also, this only happened in a `script_fields` script. The same script did not crash as a `function_score`.
