### ISSUE TITLE
It's better to return all token attributes in _analyze response

### ISSUE THREAD

**Issue by comdiv** [elastic/elasticsearch#11076]
It allows to make remote TokenStream with full context.
For now _analyze returns just few of token's data, while Lucene operates with many.
May be it can be optional for ex. /myindex/_analyze?alldata=true

**Comment by johtani** [comment]
Hi, 
I develop https://github.com/johtani/elasticsearch-extended-analyze plugin.
I think this plugin will help you.

**Comment by comdiv** [comment]
May be it's much .net - like style, but I think that posibility of full reflection support is a concern of core of elastic search not for plugins. It's my opinion. So i have done own implementation in ES-fork itself.
But your plugin force me to add rendering of custom attributes along with lucene-defined.

**Comment by clintongormley** [comment]
Hi @comdiv 

We're trying to keep the Elasticsearch core small and manageable (see https://github.com/elastic/elasticsearch/issues/10368) so I agree completely with @johtani that these optional extras should be in a plugin.  @johtani nice work on the plugin - what do you think about making it an official plugin?

**Comment by johtani** [comment]
@clintongormley Wow, it is OK for me. I'd like to hear our colleague's opinions

**Comment by johtani** [comment]
Hi @comdiv ,

We discussed about this few weeks ago and we decided to move my plugin function to _analyze API.
I reopen this issue and I will make PR soon.
If you have any idea, please let me know on my PR.
