### ISSUE TITLE
Different page sizes result in distance sorting errors

### ISSUE THREAD

**Issue by wushimang886** [elastic/elasticsearch#110739]
### Elasticsearch Version

elasticsearch-8.14.2

### Java Version

_bundled_

### OS Version

windows-x86_64

### Problem Description

I would like to sort the search results by matching degree and distance on my end。
I use get as follows：

post index_1/_search 
{
  "_source": ["name", "nam1", "nam2"],
    "query": {
		"dis_max": {
			"queries": [
        {
				"match_phrase": {
					"name": {
					"query": "3"
		
					}}
				},
				{
				"match_phrase": {
					"nam1": {
					"query": "3"
		
					}}
				}
			]}
    },
	"sort": [
	  { "_score": { "order": "desc" }},
    {
      "_geo_distance": {
        "location": {
          "lat":  46.529781,
          "lon": 9.878587
        },
        "order":         "asc",
        "unit":          "m", 
        "distance_type": "plane"
      }
    }
  	],
  "explain": false,
  "from": 0,
  "size": 100
}

give the result as follows：

{
    "took": 63,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 10000,
            "relation": "gte"
        },
        "max_score": null,
        "hits": [
            {
                "_index": "index_1",
                "_id": "10298127",
                "_score": 20,
                "_source": {
                    "nam2": "",
                    "name": "Widnau",
                    "nam1": "3"
                },
                "sort": [
                    20,
                    97239.06075562857
                ]
            },

The top ranked data is 97KM away from me

When I adjust the size parameter to 200。

post index_1/_search 
{
  "_source": ["name", "nam1", "nam2"],
    "query": {
		"dis_max": {
			"queries": [
        {
				"match_phrase": {
					"name": {
					"query": "3"
		
					}}
				},
				{
				"match_phrase": {
					"nam1": {
					"query": "3"
		
					}}
				}
			]}
    },
	"sort": [
	  { "_score": { "order": "desc" }},
    {
      "_geo_distance": {
        "location": {
          "lat":  46.529781,
          "lon": 9.878587
        },
        "order":         "asc",
        "unit":          "m", 
        "distance_type": "plane"
      }
    }
  	],
  "explain": false,
  "from": 0,
  "size": 200
}

The result I obtained is indeed another data that ranks first：

{
    "took": 75,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 10000,
            "relation": "gte"
        },
        "max_score": null,
        "hits": [
            {
                "_index": "index_1",
                "_id": "135418336",
                "_score": 20,
                "_source": {
                    "nam2": "",
                    "name": "3",
                    "nam1": ""
                },
                "sort": [
                    20,
                    109213.56879010897
                ]
            },

This point is 109km away from me！

Why did I just increase the number of sizes. The result closest to me is different？

### Steps to Reproduce

mappings": {
"location": {
                "type": "geo_point"
  },
  "nam2": {
      "type": "text",
      "fields": {
          "keyword": {
              "type": "keyword",
              "ignore_above": 256
          }
      }
  },
 "nam1": {
      "type": "text",
      "fields": {
          "keyword": {
              "type": "keyword",
              "ignore_above": 256
          }
      }
  },
 "nam2": {
      "type": "text",
      "fields": {
          "keyword": {
              "type": "keyword",
              "ignore_above": 256
          }
      }
  }
}

**Comment by wushimang886** [comment]
When I only search for one field.  such as：
post here-weu-new-poi-search/_search 
{
  "_source": ["name", "nam1", "nam2", "RNA","pd", "PID"],
    "query": {
		"dis_max": {
			"queries": [
    
				{
				"match_phrase": {
					"nam1": {
					"query": "3"
		
					}}
				}
			]}
    },
	"sort": [
	  { "_score": { "order": "desc" }},
    {
      "_geo_distance": {
        "location": {
          "lat":  46.529781,
          "lon": 9.878587
        },
        "order":         "asc",
        "unit":          "m", 
        "distance_type": "plane"
      }
    }
  	],
  "explain": false,
  "from": 0,
  "size": 200
}

No matter how I modify the size parameter, it will not affect the results！
Therefore, I suspect that the problem was caused by dis_max searching for multiple fields

**Comment by carlosdelest** [comment]
Hi @wushimang886 !

From what I see on your queries, it seems that you're sorting first on relevance, and then on distance:

```json
  "sort": [
    {
      "_score": {
        "order": "desc"
      }
    },
    {
      "_geo_distance": {
        "location": {
          "lat": 46.529781,
          "lon": 9.878587
        },
        "order": "asc",
        "unit": "m",
        "distance_type": "plane"
      }
    }
  ]
```

When doing a dismax query, you'll be getting the maximum score from the wrapped queries for all docs matching them. dis_max does not take other signals for sorting, just scoring.

Once the best scores from both queries have been retrieved, you're sorting by distance - so from the docs retrieved, you'll be sorting on score first, distance second.

When you increase the `size` parameter, more results are coming from both queries. This means that, in case a lot of docs have the same score (which I think is the case, as your top hits have score 20), they will be reordered differently depending on the distance (as that is your secondary sort). Having more docs that tie on scoring will mean that you get the possibility of them being on different order by distance.

If you want to take into account both score and distance, I suggest you do a [script_score](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-script-score-query.html) to combine both signals in a way that makes sense.

I hope this helps - I'm closing this as I think this is expected behaviour from the dis_max query.
