### ISSUE TITLE
Something is wrong with template mapping

### ISSUE THREAD

**Issue by leo650** [elastic/elasticsearch#11080]
Hi,
   First of all, thank U for sharing the wonderful product ElasticSeach.
  These  days ,I have confronted some  confuses.I hope U can help me.
  When I execute the curl command as follows(I just wanna create an index):
  curl -XPUT 'http://localhost:9200/es4zq2/_mapping/netdepartment' -d '{"properties":{"MOBILEPHONE":{"analyzer": "ik","type": "string"},"MODIFYTIME": {"format": "dateOptionalTime","type": "date"},"trs_publish_month": {"format": "yyyy-MM","type": "date"},"DEPARTMENTID": {"type":"integer"},"CRTIME": {"format": "dateOptionalTime","type": "date"},"match_all": {"type": "object"},"DEPARTMENTDESC": {"analyzer": "ik","type": "string"},"ISVALIDITY": {"type": "integer"},"EMAIL": {"analyzer": "ik","type": "string"},"trs_global_version": {"type": "long"},"MODIFYUSER": {"analyzer": "ik","type": "string"},"CRUSER": {"analyzer":"ik","type": "string"},"SYSGROUPID": {"type": "integer"},"MODIFYFLAG": {"type": "integer"},"EVENTNOTIFY": {"type": "integer"},"DEPARTMENTORDER": {"type": "integer"},"DEPARTMENTTYPE": {"type": "integer"},"PRINCIPAL": {"analyzer": "ik","type": "string"},"trs_category_flag": {"type": "short"},"DEPARTMENTNAME": {"analyzer": "ik","type": "string"},"trs_publish_year": {"format": "yyyy","type": "date"},"trs_field_weight": {"type": "short"},"trs_global_category": {"type": "short"},"trs_publish_day": {"format": "yyyy-MM-dd","type": "date"},"PARENTDPMID": {"type": "integer"}}}'
But It fedbacked an error:
![1](https://cloud.githubusercontent.com/assets/5074423/7551226/ce7adbf4-f6b3-11e4-9102-9152d2a5398e.png)
as U can see,there is no field which is named title,dexcription,price,onSale and so on.
there is no template.
![2](https://cloud.githubusercontent.com/assets/5074423/7551227/e157a180-f6b3-11e4-86a0-9c9c401012c6.png)
there is no .json file in the mappings dir.
![3](https://cloud.githubusercontent.com/assets/5074423/7551228/e74e960c-f6b3-11e4-9dfc-0694078aa0f8.png)
PS:
I have put default.json on conf/mapping  many days ago. And then ,I deleted the mapping dir yestoday.and I have restart the elasticsearch.
default.json contains these fields(title,onSale,description...).
this is start info:
![4](https://cloud.githubusercontent.com/assets/5074423/7551230/ecc8c33c-f6b3-11e4-8e25-fe0c3d4d0b57.png)

Questions:
1.how  can I fix the error,why the error appeared?
2.If I delete the dymatic mapping file(json file in conf/mappings/index),does the mapping work on late index?
3.what can i do if I want to delete this template which is created by json file?
thank U very much.

**Comment by imotov** [comment]
@leo650 we are using github to keep track of bug reports and feature requests. So, our mailing list and [discussion forums](https://discuss.elastic.co/) are much better place to ask questions like this. Saying that, you [missed the name of the type](http://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html) in your mapping. It should be:

```
curl -XPUT 'http://localhost:9200/es4zq2/_mapping/netdepartment' -d '{
	"netdepartment": {
		"properties": {
			"MOBILEPHONE": {
				"analyzer": "ik",
				"type": "string"
			},
			..............
			"trs_publish_day": {
				"format": "yyyy-MM-dd",
				"type": "date"
			},
			"PARENTDPMID": {
				"type": "integer"
			}
		}
	}
}'
```

If you have any other questions, please don't hesitate to ask them on the mailing list of forum.

**Comment by leo650** [comment]
@imotov  THX a lot.   BTW, I can put the mapping to ES without the name "netdepartment". and ES feedback with "acknowledge:true"
