### ISSUE TITLE
Allow remove settings with PUT /index/_settings command

### ISSUE THREAD

**Issue by comdiv** [elastic/elasticsearch#11081]
It's very usefull because in development cycle we usually have index with data and experiment with analzer config on it. So we usually want to remove some filters, parameters and so on from settings.
And in current implementation we cannot. 

In my fork i have fix it and will send cherry-picked branch to pull request.

Our solution is to add spectial keyword ```"__REMOVE__"``` for this special case.

Usage.
POST /myindex/_close
PUT /myindex/_settings 
```javascript
{
     "settings" : {
           "analysis": {
                 "filter" : {
                      "very_deprecated_filter" : "__REMOVE__"
                 }
           }
     }
}
```

It  must completly remove "index.analysis.filter.very_deprecated_filter" and it's descendants for example "index.analysis.filter.very_deprecated_filter.type" from settings.

We choose from variants : 
1. ```"some" : null```               -- not good it may be treated as existed setting with null value
2. ```"some" : false```             -- not good for same reasones
3. ```"some" : { "remove" : true}``` -- more complex to handle and to read/write and can cause conflicts
4. ```"some" : { "__remove__" : true }``` --less conflictable but still unreadable
5. ```"some" : "__REMOVE__"```  -- has some chance to conflict but not great, simple to read/write

SO ```"some" :"__REMOVE__"``` syntax is our team choise.

**Comment by clintongormley** [comment]
Hi @comdiv 

Actually, we can probably support deleting settings with a `DELETE` request. But this is a bigger problem than just deleting settings. We also need to check for any references to the setting (eg deleting an analyzer that is in use by a field) and be able to reset the default value (eg when deleting `refresh_interval`).

This requires a much bigger settings rewrite, which we plan to do at some stage.  I'm going to close this ticket in favour of https://github.com/elastic/elasticsearch/issues/6732

**Comment by comdiv** [comment]
Hm. Much wrong is how it is now in main trunk.
For example:
_settings 
{
   "x" : {
          "a" : "b"
    }
}

and then 

_settings
{
      "x" : null
}

what doest cause?

{
    "x": null,
   "x.a" : "b"
}

It's invalid config i think.  My opinion is that if someone decide to delete some part of configuration he do it on his own risk and must have valid tools to accomplish it.
