### ISSUE TITLE
[CI] AD tests using SmbTestContainer failing on Rocky Linux 9

### ISSUE THREAD

**Issue by brianseeders** [elastic/elasticsearch#110840]
### CI Link

https://gradle-enterprise.elastic.co/s/jvmzopfxcpdos

### Repro line

./gradlew ':x-pack:qa:third-party:active-directory:test' --tests "org.elasticsearch.xpack.security.authc.ldap.MultiGroupMappingIT" -Dtests.seed=DD61CF1351486A12 -Dtests.locale=en-US -Dtests.timezone=UTC -Druntime.java=22

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

```
java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).
```

**Comment by brianseeders** [comment]
https://github.com/elastic/elasticsearch/blob/main/x-pack/test/smb-fixture/src/main/java/org/elasticsearch/test/fixtures/smb/SmbTestContainer.java#L15-L23

During `apt-get install` in this image, when running on Rocky 9, the `pycompile` process is extremely slow (which runs as part of the installation for multiple packages). It's so slow, that the suite eventually hits a timeout.

Locally, this does not happen.

This started occurring right after we published a new VM image for Rocky 9 for use in CI. That image contained a new Linux kernel: `5.14.0-427.24.1.el9_4.x86_64`

I can't find anything else major that would have changed at the same time... so this may be specific to this kernel. It would also explain why it's only happening on Rocky 9, despite being an operation happening inside a docker container.

**Comment by mark-vieira** [comment]
I haven't seen any instances of this in the past week. The only failure of this test task has been [this one](https://gradle-enterprise.elastic.co/s/lhpbnvkvykoca/tests/task/:x-pack:qa:third-party:active-directory:test/details/org.elasticsearch.xpack.security.authc.ldap.GroupMappingIT?top-execution=1) which is a different issue.

**Comment by mark-vieira** [comment]
All these failures happened in a three day period. Perhaps there was some kind of package update or something in that time that affected the test fixture image. Given we've stopped seeing this I'm going to close the issue for now.

![image](https://github.com/user-attachments/assets/5228d2e2-a5da-4084-99b2-2b7b5913f216)
