### ISSUE TITLE
termvector rest spec documentation for 1.5 out of date

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#11086]
https://github.com/elastic/elasticsearch/pull/7530 introduced support for artificial documents

I submitted a PR to both es [master](https://github.com/elastic/elasticsearch/pull/8868/files) and [1.4](https://github.com/elastic/elasticsearch/pull/8869/files) branches but they are no longer reflected in the `1.5` branches.

I need to update the `1.x` and `1.5` branches with these changes as well

**Comment by clintongormley** [comment]
Closed by #11087
