### ISSUE TITLE
elasticSearch7.17.3 i think Paging is a bit of a problem

### ISSUE THREAD

**Issue by YuanJie2001** [elastic/elasticsearch#110864]
### Description

As shown in the figure：
我想记录用户离线，群消息同步。当用户上线时，首先统计该群的文档数量，和在用户手机上记录的对比。 那么我使用了es的统计方法，他返回给我了 long类型的结果。但是我分页拉取消息时，from和size要求我传入integer类型。
I would like to record the user offline and the group messages are synchronized. When the user is online, first count the number of documents in the group, and compare it with what is recorded on the user's phone. Then I used es's count method and he returned me the result of type long. But when I paged to pull the messages, from and size asked me to pass in integer type.

![image](https://github.com/user-attachments/assets/0f2ed7f1-f6ab-45b9-b304-956766799b29)

**Comment by YuanJie2001** [comment]
Though I will admit that logging 3 months of data is probably not over the limit. But long to integer is still a bit ridiculous

**Comment by carlosdelest** [comment]
size() uses an integer as it's the page size - that is, the number of results to be actually retrieved on the request, not the offset for the page itself. 

Retrieving 2^31 results in one go should be enough for any use case, so using type integer for it makes sense here.

**Comment by dragan509** [comment]
Instead of trying to fetch a large number of results, you can fetch results in smaller batches.

Here is my code.
        
   List<GroupMessageDTO> results = new ArrayList<>();
        ...

        if (cloudOffset > groupMessageDTO.getLocalOffset()) {
            // Initial search request with a scroll context
            SearchResponse<GroupMessageDTO> searchResponse = elasticsearchClient.search(s -> s
                .index(idx)
                .query(query)
                .from(groupMessageDTO.getLocalOffset())
                .size(10000) // Fetch in batches of 10000
                .sort(so -> so
                        // your sorting criteria
                )
            );

            while (searchResponse.hits().hits().size() > 0) {
                for (Hit<GroupMessageDTO> hit : searchResponse.hits().hits()) {
                    results.add(hit.source());
                }
            } 
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return results;
}

**Comment by javanna** [comment]
Could you please move your question to our [forums](https://discuss.elastic.co/) ? We reserve github issues for bugs and feature requests.

**Comment by YuanJie2001** [comment]
You are right, I changed my mind. Use a time range query
