### ISSUE TITLE
Incorrect example in CamelCase tokenizer description

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#11099]
"pattern" on page http://www.elastic.co/guide/en/elasticsearch/reference/1.4/analysis-pattern-analyzer.html#_camelcase_tokenizer currently reads:" "([^\\\\p{L}\\\\d]+)|(?<=\\\\D)(?=\\\\d)|(?<=\\\\d)(?=\\\\D)|(?<=[\\\\p{L}&&[^\\\\p{Lu}]])(?=\\\\p{Lu})|(?<=\\\\p{Lu})(?=\\\\p{Lu}[\\\\p{L}&&[^\\\\p{Lu}]])"
  
should read:
"([^\\p{L}\\d]+)|(?<=\\D)(?=\\d)|(?<=\\d)(?=\\D)|(?<=[ \\p{L} && [^\\p{Lu}]])(?=\\p{Lu})|(?<=\\p{Lu})(?=\\p{Lu}[\\p{L}&&[^\\p{Lu}]])"

**Comment by nik9000** [comment]
I laughed so much at seeing this because my eyes just unfocus when I see a regex this long. Comparing them is something I can only do with great patience. I see the change from \\ to \ which feels right. Is that the only change?

**Comment by seang-es** [comment]
I miscopied the original source, wrong one on my clipboard.  Original source reads:

 "pattern":"([^\\\\p{L}\\\\d]+)|(?<=\\\\D)(?=\\\\d)|(?<=\\\\d)(?=\\\\D)|(?<=[\\\\p{L}&&[^\\\\p{Lu}]])(?=\\\\p{Lu})|(?<=\\\\p{Lu})(?=\\\\p{Lu}[\\\\p{L}&&[^\\\\p{Lu}]])"

Lots of extra backslashes.
