### ISSUE TITLE
Significant terms aggregation has pointless lookups if shard_min_doc_count set

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#11093]
Zipf's law tells us many terms occur very infrequently and so setting shard_min_doc_count to a value >1 can eliminate a lot of candidate terms from the analysis (assuming we are not interested in very low-frequency terms). 
This can be a significant performance gain but is not fully realised today because the existing code *always* looks up the background frequency of terms in the index
The logic should change to only lookup background frequencies for terms if they pass the shard_min_doc_count threshold.

**Comment by clintongormley** [comment]
@markharwood please put version labels on this PR

**Comment by clintongormley** [comment]
sorry, ignore me - it's not a PR :)
