### ISSUE TITLE
Relocation performing extra work?

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#11107]
The following is the reported scenario on 1.4.2 (have cat shards output if you would like to see it):

A node "6" was rebooted (unexpectedly), this node was hosting 4 shards, 2 primaries and 2 replicas.  When "6" stopped, 2 other nodes in the cluster had replicas promoted to primaries, and the 2 replicas that used to be on "6" were then allocated to another 2 nodes in the cluster - as expected.

When node "6" came back, cluster started to relocate 2 shards from 2 other nodes to it.  It decided to move 2 big 34Gb shards from 2 other nodes to "6".  Then shortly after, it seems like it then realized that the cluster was unbalanced and proceeded to move one of the 34Gb shard from "6" to a different node "4".  Note that at the time the 2 34Gb shards were relocating to "6", there were no other relocations going on and "4" was showing that it had room for one of the 34Gb shard.  It seems like it could have just relocated the 34Gb shard directly to "4" without first moving it to "6".

**Comment by nik9000** [comment]
In general the balance algorithm is "simple" in that it doesn't look into the future. It just tries to make the best decision it can at the time and it doesn't try to take a long view. I expect this kind of thing, unfortunately.

Note also that it doesn't take into account the size of the shards except to make sure that it doesn't fill up the disk.

**Comment by ppf2** [comment]
@nik9000 thx

**Comment by ppf2** [comment]
Does it try to balance the # of shards per index across the nodes as part of this "intermediate" move?  For this incident, the 2 34Gb shards that got moved to "6" in the beginning are 2 replica shards (different shard #s) for the same index.  And this index has 5 shards (1 replica) = 10 shards total, but the cluster has 15 data nodes.  Not sure if it decided to move one of the 2 shards immediately to another node because of the size imbalance, or the shards per index per node imbalance.

**Comment by nik9000** [comment]
I'm not sure why. Its sometimes difficult to be sure why the movement code
makes the decisions it makes. You should probably have a look at the
total_shards_per_node setting - it might be useful to prevent these large
shards from moving together.

**Comment by clintongormley** [comment]
This process has been greatly improved since 1.4. Closing
