### ISSUE TITLE
Search preference docs render incorrectly

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#111023]
Not sure why but the `tag::search-preference[]` bits are appearing in the rendered copy of the [docs for the `preference` parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-preference):

<img width="863" alt="image" src="https://github.com/user-attachments/assets/ba5c2810-c997-43f5-9229-95b114347bd3">

**Comment by leemthompo** [comment]
@DaveCTurner they should be commented right I guess that's it

**Comment by leemthompo** [comment]
Let's see if that PR works once URL preview is live
