### ISSUE TITLE
Hadoop Configuration setMapOutputValueClass method doesn't exists

### ISSUE THREAD

**Issue by gquintana** [elastic/elasticsearch#11102]
In http://www.elastic.co/guide/en/elasticsearch/hadoop/2.0/mapreduce.html#writing-json-new-api code exemple
```
Configuration conf = new Configuration();
conf.set("es.input.json", "yes");                 
conf.setMapOutputValueClass(BytesWritable.class); 
```
The `setMapOutputValueClass` method doesn't exist on class`Configuration`

**Comment by clintongormley** [comment]
Hi @gquintana 

Please could you reopen your issue here: https://github.com/elastic/elasticsearch-hadoop/issues
