### ISSUE TITLE
Add official support for Debian 12

### ISSUE THREAD

**Issue by xeraa** [elastic/elasticsearch#111176]
### Description

Add Debian 12 to the [support matrix](https://www.elastic.co/support/matrix) for 8.x — Kibana already has it listed since 8.12.

Looking at some stats for 8.10+ Elasticsearch clusters, it's one of the most widely used operating systems.

**Comment by ioraff** [comment]
Any updates?

**Comment by whyyouwannaknow** [comment]
Hello,
Do we have any news on when the Elastic Stack will officially be fully compatible to use Debian 12?

Thank you!

**Comment by ioraff** [comment]
Pinging @xeraa

**Comment by xeraa** [comment]
It will work — it's one of the most widely used deployment options. We just need to add it to the test matrix before adding it to the list of official options (I'm not sure where we're exactly with this on each repo though).

**Comment by jozala** [comment]
Debian 12 is now included in the Elasticsearch test matrix and it has been added to the [support matrix](https://www.elastic.co/support/matrix).
I will close this ticket, but let me know if you have any further questions.
