### ISSUE TITLE
Shard allocation should work harder to balance new shards across multiple path.data paths

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#11122]
In 2.0 as of #10461 we now allocate each shard on a node to whichever path.data has the most free space at the moment the shard is assigned to the node.

But in the case when a new node just started up, and suddenly gets a bunch of new shards assigned (new index), we will put all those shards onto a single path (the one with the most free space at that moment).

I saw this happen on a node that had 2 identically sized SSDs on the path.data, but on one of them I had installed ES so it had a wee bit less disk space, and then all 5 shards of my new index were assigned to the other SSD.

**Comment by s1monw** [comment]
@mikemccand I made this a blocker

**Comment by mikemccand** [comment]
> @mikemccand I made this a blocker

OK, I agree.  I can try to fix this ...

I think there are at least 2 cases here: 1) new index (shard) allocated to this node, and 2) shard relocated/recovered from another node.

For case 2), I think IndexService.createShard needs to be told how large the incoming shard will be (it's not today?), since we must already know this somewhere, but I don't know how to get this information in IndicesClusterStateService.applyInitializingShard when it calls createShard.

For case 1) we need to be a bit smarter when our node is allocated more than 1 shard for the same index, and use some heuristic e.g. "the size of the overall index will be 50% of total free space across all path.data paths", and budget each shard as 1/Nth of that.

Maybe there are other cases, e.g. restoring from a snapshot?

For both of these cases we need some way to record "reserved space" against each path.data, much like how a credit card company pre-charges you to "authorize" a purchase but not charge you until you actually need to pay.  Maybe this "tracking of disk space that will be consumed soon" needs to be in NodeEnvironment?

**Comment by dakrone** [comment]
> For case 2), I think IndexService.createShard needs to be told how large the incoming shard will be (it's not today?), since we must already know this somewhere, but I don't know how to get this information in IndicesClusterStateService.applyInitializingShard when it calls createShard.

I think we could average the shard sizes for all other shards in the cluster. This information can be retrieved from the `ClusterInfoService`, which will periodically fetch it (on the master node).

**Comment by mikemccand** [comment]
Thanks for the pointer @dakrone, I'll try to use that for the case when there are already some shards in the cluster.

**Comment by mikemccand** [comment]
At the end of the day, the fix here will be heuristicky, since we essentially must "guess" how big this shard will grow to in the future.  So, there will be adversarial cases which fill up one data path while others remain very empty...

Maybe we should (separately) make the separate path.datas on a given node visible to the cluster state?  I think we don't do this today?  E.g. DiskThresholdDecider looks at the net free bytes on a node, so it won't notice if one path is nearly full and another is very empty?  It will see that node has still having plenty of space?

If we did that, it would handle the adversarial cases where we "guessed wrong", and accidentally put N tiny shards on one path and N huge shards on another ... we'd be able to correct it later by relocating shards from the nearly full path.data ...

**Comment by s1monw** [comment]
I mean we have a general problem here that we don't know on which node we should put the shard if the index is freshly created. I wonder if we should do the same thing we do for shard allocation as well for disk allocaiton and make sure shards of an index are balanced across disks if there is enough space on all the disks and as a second heuristic use the number of shards in total on that node to balance. L
