### ISSUE TITLE
Filter and Export functions: MITRE ATT&CK® coverage

### ISSUE THREAD

**Issue by hsportel** [elastic/elasticsearch#111326]
### Description

Within Elastic Security Solution you have the MITRE ATT&CK® coverage dashboard (Detections and alerts). Which is a great feature.
But the current filter options are quite limited, and there is no export function. I literally must take screen captures to share this information for example to our sales department.

What i (we) really would like to see are the following:

- Filter options on rule tags, for example what is mitre mapping on rules with the tag "OS:linux"
- Export functions to image (png, jpeg etc) or pdf, or csv, etc

Thank you!
With regards
Herman

**Comment by nielsbauman** [comment]
Hi @hsportel, thank you for taking the time to open an issue. Since you're talking about a specific Solution, I'm going to have to redirect you to https://github.com/elastic/kibana. Could you please open up an issue over there?
