### ISSUE TITLE
FuzzyQueryBuilder is missing rewrite

### ISSUE THREAD

**Issue by adamhooper** [elastic/elasticsearch#11130]
FuzzyQueryBuilder is a MultiTermQueryBuilder, so it should support a `rewrite` parameter. Indeed, `rewrite` works when I specify a JSON `fuzzy` query. But I can't set it if I want to use a `FuzzyQueryBuilder`.

My workaround is to use `MatchQueryBuilder`.

**Comment by javanna** [comment]
Thanks @adamhooper good catch, fixed in master, 1.x and 1.5 branches.
