### ISSUE TITLE
Embeddings_SQL support 

### ISSUE THREAD

**Issue by trillionmonster** [elastic/elasticsearch#111391]
Look at this page :

https://github.com/neuml/txtai/blob/master/examples/30_Embeddings_SQL_custom_functions.ipynb

when to support  Embeddings_SQL  like this

`select
  text,
  translation(text, 'de', null) 'text (DE)',
  translation(text, 'es', null) 'text (ES)',
  translation(text, 'fr', null) 'text (FR)'
from txtai where similar('feel good story')
limit 1`

**Comment by astefan** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
