### ISSUE TITLE
Uptime Monitors Dashboard fails to reload after screen Power Cycle

### ISSUE THREAD

**Issue by TheoTelliez** [elastic/elasticsearch#111322]
### Elasticsearch Version

8.6.0

### Java Version

_bundled_

### OS Version

Win10

### Problem Description

When I turn off my monitoring screens at night and leave the browser tabs open, the Uptime Monitors dashboard under Observability > Uptime > Monitors fails to reload correctly the next morning. Instead of displaying the monitors, it shows an error message "Failed to fetch". This issue forces me to manually refresh the tab every morning, which is quite inconvenient.

### Steps to Reproduce

1- Open the Uptime Monitors dashboard in the browser (Observability > Uptime > Monitors).
2- Turn off the monitoring screens for the night.
3- Turn the screens back on the next morning.
4- Observe the Uptime Monitors dashboard.

**Comment by nielsbauman** [comment]
Hi @TheoTelliez, thank you for taking the time to open an issue with Elasticsearch. Since you're facing this issue in your browser, I'm going to have to ask you to open an issue over at https://github.com/elastic/kibana. Elasticsearch doesn't provide a UI for your browser.
