### ISSUE TITLE
Accept non-closed GeoJSON polygons

### ISSUE THREAD

**Issue by lababidi** [elastic/elasticsearch#11131]
@nknize I'm creating a new issue here based on a comment on issue #3909 

Twitter provides the following object. It is rejected by elasticsearch for only having 4 elements and not 5. This strict requirement is not consistent with GeoJSON. Please allow elasticsearch to accept this Object, out of the box, because technically it is legal GeoJSON. Currently I must write a middle-man to add a 5th-element (cue Bruce Willis jokes here) to this array of coordinates. This is a bit kludgy in terms of workflow:
```
"bounding_box": {
        "type": "Polygon",
        "coordinates": [
        [
        [
        -9.0915413,
        38.6713816
        ],
        [
        -9.0915413,
        38.9313732
        ],
        [
        -8.8102479,
        38.9313732
        ],
        [
        -8.8102479,
        38.6713816
        ]
        ]
        ]
        },

**Comment by dimroc** [comment]
+1. Got here from issue https://github.com/elastic/elasticsearch/issues/3909.

**Comment by gustin** [comment]
:+1: We're running into this storing data from gnip, their geo enrichment uses the same 4 point polygons.

**Comment by vsilva89** [comment]
Does this problem is solved ?  I have the same problem and need your help
