### ISSUE TITLE
[Community ID Processor] Handle events without a named network.transport

### ISSUE THREAD

**Issue by andrewkroh** [elastic/elasticsearch#111517]
### Elasticsearch Version

8.14.1

### Java Version

_bundled_

### OS Version

docker.elastic.co/elasticsearch/elasticsearch:8.14.1

### Problem Description

The community_id processor [assumes](https://github.com/elastic/elasticsearch/blob/c5da25754007af51029a676a8784b16be16d8995/modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/CommunityIdProcessor.java#L226) that it can always determine the transport name from the [IANA number](https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml). But this is not true and should not be required to compute a [community_id](https://github.com/corelight/community-id-spec?tab=readme-ov-file#technical-details).

It should be sufficient to know that the transport is not TCP / UDP / SCTP / ICMPv4 / ICMPv6, and then proceed to a computation using only the source ip, destination ip, and protocol number.

## Related

- https://github.com/elastic/integrations/issues/10678

### Steps to Reproduce

```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
    {
      "community_id" : {}
    }
    ]
  },
  "docs": [
    {
      "_source": {
        "source": {"ip":"192.168.1.2"},
        "destination": {"ip": "10.1.2.3"},
        "network": {"iana_number": "4"}
      }
    }
  ]
}
```

What I got:

```
{
  "docs": [
    {
      "error": {
        "root_cause": [
          {
            "type": "illegal_argument_exception",
            "reason": "unknown transport protocol number [4]"
          }
        ],
        "type": "illegal_argument_exception",
        "reason": "unknown transport protocol number [4]"
      }
    }
  ]
}
```

What I expected:

```json
{
  "destination": {
    "ip": "10.1.2.3"
  },
  "network": {
    "community_id": "1:KXQzmk3bdsvD6UXj7dvQ4bM6Zvw=",
    "iana_number": "4"
  },
  "source": {
    "ip": "192.168.1.2"
  }
}
```

**Comment by pkoutsovasilis** [comment]
@andrewkroh your expectations are now part of the CommunityIdProcessor unit-tests under the linked PR 😄
