### ISSUE TITLE
_size does not support doc_values

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#11153]
Currently, if you try to create a mapping that tries to set `"doc_values" : true`, then it will either ignore the `_size` field or ignore that setting:

```json
PUT /test
{
  "mappings": {
    "type": {
      "_size": {
        "enabled": true,
        "doc_values" : true,
        "store": true
      }, 
      "properties": {
        "field": {
          "type": "string"
        }
      }
    }
  }
}
```

This results in:

```
GET /test/_mapping
{
  "test": {
    "mappings": {
      "type": {
        "_size": {
          "enabled": true,
          "store": true
        },
        "properties": {
          "field": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

After adding some documents, then sorting on `_size`, you can see that it does indeed ignore the doc values setting (rather than just not showing it set, which was unlikely):

```json
PUT /test/type/1
{
  "field" : "value1"
}

PUT /test/type/2
{
  "field" : "value2"
}

GET /test/_search
{
  "fields": ["_size"],
  "sort": [
    {
      "_size": {
        "order": "desc"
      }
    }
  ]
}
```

Fielddata:

```
GET /_cat/fielddata?fields=*&v
id                     host        ip           node   total  _size 
2xF59inESXKOIkzK7GkavA my-hostname 192.168.1.31 Kl'rt 16.5kb 16.5kb 
```

This is not critical as `_size` must be enabled to even be used, but in that case, it would be useful to make use of doc values.

**Comment by rjernst** [comment]
In #8143 we locked down meta fields, so even `store` here is no longer possible to set (it is always stored). It is important the configuration of meta fields are managed, so that we can depend on them for features.  Now that doc values are enabled by default for 2.0, for non-tokenized and indexed fields, `_size` will have doc values when enabled.
