### ISSUE TITLE
multi_field "default" field not behaving as expected

### ISSUE THREAD

**Issue by marshall007** [elastic/elasticsearch#11151]
From the [Multi Field Type docs](http://www.elastic.co/guide/en/elasticsearch/reference/0.90/mapping-multi-field-type.html):

> With `multi_field` mapping, the field that has the same name as the property is treated as if it was mapped without a multi field. That’s the "default" field. It can be accessed regularly, for example using name or using typed navigation `tweet.name`.

Thus, given the following mapping, I would expect that querying `test.name` would be equivalent to `test.name.name` but this does not appear to be the case.

```json
{
  // ...
  "mappings": {
    "test": {
      "properties": {
        "name": {
          "type": "string",
          "fields": {
            "name": {
              "analyzer": "full_name",
              "type": "string",
              "index": "analyzed"
            },
            "partial": {
              "search_analyzer": "full_name",
              "index_analyzer": "partial_name",
              "type": "string",
              "index": "analyzed"
            }
          }
        },
        // ...
      }
    }
  }
}
```

I get different results from the following queries:

```
GET tests/_search
{
  "query": {
    "match": {
      "name": "rett syndrome"
    }
  }
}

GET tests/_search
{
  "query": {
    "match": {
      "name.name": "rett syndrome"
    }
  }
}
```

**Comment by rjernst** [comment]
First, you should make sure to use fully qualified field names in your queries, ie `test.name` and `test.name.name`. Second, I think you are confusing "old" multi-fields (pre 1.0) with current multi-fields.  See http://www.elastic.co/guide/en/elasticsearch/reference/1.5/mapping-core-types.html#_multi_fields_3.

**Comment by marshall007** [comment]
@rjernst ok so to get the behavior I'm looking for my mapping should instead look like this?

```json
{
  // ...
  "mappings": {
    "test": {
      "properties": {
        "name": {
          "type": "string",
          "analyzer": "full_name",
          "index": "analyzed",
          "fields": {
            "partial": {
              "search_analyzer": "full_name",
              "index_analyzer": "partial_name",
              "type": "string",
              "index": "analyzed"
            }
          }
        },
        // ...
      }
    }
  }
}
```

I still think if you define a multi-field with the same name as it's parent property that should override the default mapping for that field.

**Comment by rjernst** [comment]
> I still think if you define a multi-field with the same name as it's parent property that should override the default mapping for that field.
If you want to have different behavior for the original field, then change the settings for the original field? The name of sub fields should not matter. The `fields` behavior only means "copy the original value to some more fields, and access them as an offshoot of the original name".

**Comment by clintongormley** [comment]
> I still think if you define a multi-field with the same name as it's parent property that should override the default mapping for that field.

And, if you have a sub-field with the same name as its parent, it will just add a new field `my_field.my_field`
