### ISSUE TITLE
Refactoring confirmation for Combine enum with comparator

### ISSUE THREAD

**Issue by larjean89** [elastic/elasticsearch#111621]
Greetings,

I have a question regarding a refactoring on this [commit](https://github.com/elastic/elasticsearch/commit/1fae3e75017ab831eab5ff30029bc97ebd52fe82)

@DaveCTurner did you conduct the following refactoring?

 **Combine enum with comparator** where the refactoring moved the sort key enum to the top level and replaces one of the`switch` statements with a method on the enum instances.

Code snippet

```java
- allSnapshotsSorted(allSnapshotNames, repoName, GetSnapshotsRequest.SortBy.NAME, order, includeIndexNames),
         -   GetSnapshotsRequest.SortBy.NAME,
          +  allSnapshotsSorted(allSnapshotNames, repoName, SnapshotSortKey.NAME, order, includeIndexNames),
           + SnapshotSortKey.NAME,
            order
        ); 
```
  Thanks and will be looking forward to hearing from you.

**Comment by snicoll** [comment]
FTR, this is likely to be created by a bot. The "OP" created something similar in https://github.com/spring-projects/spring-framework/issues/33329

**Comment by DaveCTurner** [comment]
Thanks for the heads-up @snicoll, yeah even if this weren't bot-like activity it still wouldn't be acceptable here. Closing.
