### ISSUE TITLE
Cannot add filters to percolator from Java API

### ISSUE THREAD

**Issue by leourbina** [elastic/elasticsearch#11162]
When performing a percolator query from the java API, adding a filter to the percolate operation causes no results being returned. Runnable code reproducing this issue can be found [here](https://github.com/leourbina/ElasticSearchTests/blob/master/src/test/java/elasticsearch/ElasticSearchTests.java#L128). The relevant portion is the below:

We setup two `matchAll` queries and index them with some accompanying metadata (`userId`)

```java
MatchAllQueryBuilder query1 = QueryBuilders.matchAllQuery();
MatchAllQueryBuilder query2 = QueryBuilders.matchAllQuery();

client.prepareIndex(INDEX, PERCOLATOR_TYPE, "query1")
    .setSource(XContentFactory.jsonBuilder()
        .startObject()
        .field("query", query1)
        .field("userId", 1)
        .endObject())
    .execute().actionGet();

client.prepareIndex(INDEX, PERCOLATOR_TYPE, "query2")
    .setSource(XContentFactory.jsonBuilder()
        .startObject()
        .field("query", query1)
        .field("userId", 2)
        .endObject())
    .execute().actionGet();
```

Percolating a document yields both queries without filtering yields both queries, as expected:

```java
PercolateResponse result = client.preparePercolate()
    .setIndices(INDEX)
    .setDocumentType(type)
    .setSource(anyDoc)
    .execute().actionGet();
```
However, adding a term filter by `userId`, yields no results:

```java
PercolateResponse filteredResult = client.preparePercolate()
    .setIndices(INDEX)
    .setDocumentType(tweet.getType())
    .setSource(anyDoc)
    .setPercolateFilter(FilterBuilders.termFilter("userId", 1))
    .execute().actionGet();
```

Instead, I'm seeing the following shard failures being returned in the `PercolateResponse`.

```
[my-index-1][0] failed, reason [BroadcastShardOperationFailedException[[my-index-1][0] ]; nested: PercolateException[failed to percolate]; nested: ElasticsearchIllegalArgumentException[Nothing to percolate]; ]
```
I have verified that *it is* possible to perform filtering/querying on the percolator directly via the REST api. At this point I'm not sure whether this is a legitimate bug, or whether I'm somehow misusing the Java API (I must admit, the docs relevant docs/javadocs are [pretty light on the subject] (http://www.elastic.co/guide/en/elasticsearch/client/java-api/current/percolate.html)). Any ideas?

**Comment by leourbina** [comment]
The same is true for queries, although currently my tests don't include it.

**Comment by dadoonet** [comment]
Is "doc" different than "anyDoc" here?

**Comment by martijnvg** [comment]
@leourbina This is a bit confusing, but instead of using `PercolateRequestBuilder#source()` you should use the `PercolateRequestBuilder#setPercolateDoc()` method to set the document to be percolated.

The source method assumes that you build the source entirely yourself (via a string, map or bytes reference).

**Comment by leourbina** [comment]
Sorry, `doc` should have been `anyDoc`. Just making a point that since the percolated queries are `matchAll`, they should be returned as results unless filtered.

**Comment by leourbina** [comment]
Ah! That makes more sense. Changing the code to 

```java
PercolateResponse filteredResult = client.preparePercolate()
    .setIndices(INDEX)
    .setDocumentType(tweet.getType())
    .setPercolateDoc(new DocBuilder().setDoc(doc))
    .setPercolateFilter(FilterBuilders.termFilter("userId", 1))
    .execute().actionGet();
```

Actually works! The documentation doesn't seem to be clear that using setSource assumes that the end user needs to craft the whole source by hand, and there weren't many sources around the internet showcasing how to do filtering in percolate queries with the Java API. I would be happy to submit a PR with an updated version of [the percolate API](http://www.elastic.co/guide/en/elasticsearch/client/java-api/current/percolate.html) including an example of using filters. Thanks again!

**Comment by martijnvg** [comment]
@leourbina +1 I'd be happy to pull this in!

**Comment by clintongormley** [comment]
@leourbina a PR would be gratefully received :)  thanks
