### ISSUE TITLE
Elastic LLM service for AI Assistant

### ISSUE THREAD

**Issue by grabowskit** [elastic/elasticsearch#111605]
### Description

The biggest hurdle to get customers to use AI Assistant or any feature that utilizes an LLM is to get them to configure an LLM account and setup the Connector via API Key. If we provided an easy setup that they could on with a button, or have available by default, we expect to substantially increase the number of users that would have access to an LLM. This would allow many of our O11y features to use an LLM by default; including Onboarding data, continuously onboard entities, alerts, SLOs, anomaly detection. As well as integrated AI in root cause analysis, cases, and post mortem reporting.

There is work being done by Platform and Search team to create Inference Service (EIS) so this ticket can be used to specify the O11y requirements. [Slack conversation on solution-area requirements](https://elastic.slack.com/archives/C079G9FSQQN/p1722259053636439)

O11y Requirements include:
1. Function calling - Observability AI Assistant has several functions for getting dataset information, and relationships. 
2. Local Knowledge base - RAG with ELSER and/or E5 models
3. Speed similar (or within 100ms) of commercial LLMs

cc: @dgieselaar @vinaychandrasekhar @emma-raffenne

**Comment by mark-vieira** [comment]
@grabowskit this doesn't sound like something that would be implemented in Elasticsearch itself. Should this issue be routed elsewhere?
