### ISSUE TITLE
Aggregations: `change_point` agg does not return results when nested in `categorize_text` agg

### ISSUE THREAD

**Issue by walterra** [elastic/elasticsearch#111679]
### Elasticsearch Version

8.15.0-SNAPSHOT, build hash: 088fabe32d1baacd70e5a0b7e675045a67fd870a

### Installed Plugins

none

### Java Version

_bundled_

### OS Version

Darwin 23.6.0 Darwin Kernel Version 23.6.0: Fri Jul  5 17:56:41 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T6000 arm64

### Problem Description

When nesting a `change_point` agg within a `categorize_text` agg, the change point information is missing from the response. The same works when the outer `categorize_text` agg get replaced with for example a `terms` agg.

### Steps to Reproduce

I used the Kibana Sample Data Logs dataset with the following queries in Kibana Dev Tools.

Here's an example query where the change point agg results is missing from the response:

```
POST kibana_sample_data_logs/_search
{
  "size": 0,
  "aggs": {
    "my_categories": {
      "categorize_text": {
        "field": "message",
        "size": 100
      },
      "aggs": {
        "histogram": {
          "date_histogram": {
            "field": "@timestamp",
            "fixed_interval": "1d"
          }
        },
        "change_point_request": {
          "change_point": {
            "buckets_path": "histogram>_count"
          }
        }
      }
    }
  }
}
```

In the response, the histogram agg works, but there's not change point output on the same level:

```
...
              {
                "key_as_string": "2024-08-28T00:00:00.000Z",
                "key": 1724803200000,
                "doc_count": 88
              },
              {
                "key_as_string": "2024-08-29T00:00:00.000Z",
                "key": 1724889600000,
                "doc_count": 75
              }
            ]
          }
        },
        {
          "doc_count": 4700,
          "key": "GET HTTP/1.1 Mozilla/5.0 X11 Linux i686 AppleWebKit/534.24 KHTML like Gecko Chrome/11.0.696.50 Safari/534.24",
          "regex": """.*?GET.+?HTTP/1\.1.+?Mozilla/5\.0.+?X11.+?Linux.+?i686.+?AppleWebKit/534\.24.+?KHTML.+?like.+?Gecko.+?Chrome/11\.0\.696\.50.+?Safari/534\.24.*?""",
          "max_matching_length": 266,
          "histogram": {
            "buckets": [
...
```

Replacing `categorize_text` with `terms` works:

```
POST kibana_sample_data_logs/_search
{
  "size": 0,
  "aggs": {
    "my_terms": {
      "terms": {
        "field": "response.keyword",
        "size": 100
      },
      "aggs": {
        "histogram": {
          "date_histogram": {
            "field": "@timestamp",
            "fixed_interval": "1d"
          }
        },
        "change_point_request": {
          "change_point": {
            "buckets_path": "histogram>_count"
          }
        }
      }
    }
  }
}
```

The response shows up even when no change points get detected as `stationary`:

```
...
              {
                "key_as_string": "2024-08-29T00:00:00.000Z",
                "key": 1724889600000,
                "doc_count": 194
              }
            ]
          },
          "change_point_request": {
            "bucket": {
              "key": "2024-07-30T00:00:00.000Z",
              "doc_count": 162
            },
            "type": {
              "dip": {
                "p_value": 2.1175706308006788e-28,
                "change_point": 30
              }
            }
          }
...
             {
                "key_as_string": "2024-08-29T00:00:00.000Z",
                "key": 1724889600000,
                "doc_count": 3
              }
            ]
          },
          "change_point_request": {
            "type": {
              "stationary": {}
            }
          }
```

**Comment by benwtrent** [comment]
I am thinking this is due to : https://github.com/elastic/elasticsearch/pull/110261

That change reduces based on an `equals` check, relying on that to be overridden correctly. 

I am not sure categorize text is doing this, nor do I believe this is true for all aggs. 

we need to validate this.

**Comment by benwtrent** [comment]
OK, I was able to reproduce with the simple following API calls:

```
POST logs-manual-default/_doc
{
  "message": "test"
}

POST logs-manual-default/_search
{
  "size": 0,
  "track_total_hits": false,
  "aggs": {
    "categories": {
      "categorize_text": {
        "field": "message",
        "size": 1000
      },
      "aggs": {
        "histogram": {
          "date_histogram": {
            "field": "@timestamp",
            "fixed_interval": "1h",
            "extended_bounds": {
              "min": "now-2d",
              "max": "now"
            }
          }
        },
        "change": {
          "change_point": {
            "buckets_path": "histogram>_count"
          }
        }
      }
    }
  }
}
```

**Comment by benwtrent** [comment]
A very quick audit shows more than one agg does not override equals. This doesn't just seem like a categorize_text bug. We need to make sure all do and all check their bucket equality, I see some subclassing, but we need to make sure this aggs are overriding equals and checking their buckets.

For example:

 - CategorizeText & timeseries don't override at all
 - InternalRareStringTerms sub-classes a class that does override equals, but doesn't check for bucket equality.

@original-brownbear did you do an audit of aggs overriding equals and checking their sub-bucket equality when you made your original change?

**Comment by nik9000** [comment]
I'm going to spend the morning reproducing this with a debugger so I can describe the mechanism of action for the bug.

**Comment by nik9000** [comment]
Ok. I can reproduce this issue and it does look like it's related to [this](https://github.com/elastic/elasticsearch/pull/110261/files#diff-005547c90c34d3d0a232504d02049fc07827f83a7b331c969d1f51eac919a095R247) filter here. Just like @benwtrent says.

> A very quick audit shows more than one agg does not override equals.

This is critical, but for those following along at home, in java if you don't override `equals` things are *unequal* by default. I presume this is what @original-brownbear assumed would happen. Alas, we [flipped](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/search/aggregations/InternalAggregation.java#L256) this so aggs are considered equal to each other if their name and metadata are equal by default. I believe it's been like this since 2019 in #43214. Like Ben says, for Armin's change to work equality needs to be correct on all aggregations and you can forget that, given how things stand now.

I'll update when I know more.

**Comment by original-brownbear** [comment]
> this is what @original-brownbear assumed would happen.

Indeed that's what did assume :/

**Comment by nik9000** [comment]
OK! We're going to revert this (https://github.com/elastic/elasticsearch/pull/111758) and open an issue for making the equality harder to break (https://github.com/elastic/elasticsearch/issues/111757).

I'll update when I have a list of effected aggs.

**Comment by nik9000** [comment]
So there are two aggs that can lose pipeline aggs:
* `time_series`
* `categorize_text`

**Comment by nik9000** [comment]
I've reverted the troublesome PR in the 8.15 branch. 8.15.1, whenever we cut it, will contain this fix.
