### ISSUE TITLE
Fallback synthetic source produces wrong results in presence of object arrays

### ISSUE THREAD

**Issue by lkts** [elastic/elasticsearch#111694]
### Elasticsearch Version

8.15

### Java Version

_bundled_

### OS Version

all

### Problem Description

Synthetic source produced via fallback mechanism is not correct when using `subobjects: false` and using object arrays.

### Steps to Reproduce

```
PUT /my_index
{
  "mappings": {
    "_source": { "mode": "synthetic" },
    "subobjects": false,
    "properties": {
      "obj": {
        "properties": {
          "k": {
              "type": "keyword",
              "doc_values": false
          }
        }
      }
    }
  }
}
```

```
PUT my_index/_doc/1
{
  "obj": [{"k": "key1"}, {"k": "key2"}]
}
```

```
GET /my_index/_doc/1

// Produces
"_source": {
    "obj.k": "key2"
}
```

**Comment by lkts** [comment]
Expected is not entirely clear here for me.

Is it?
```
"_source": {
    "obj.k": ["key1", "key2"]
}
```

Or should it (can we make it) be identical to stored source?

**Comment by lkts** [comment]
This is actually a more generic problem, it reproduces without `subobjects: false` too.

**Comment by martijnvg** [comment]
> Or should it (can we make it) be identical to stored source?

I don't think we're able to sythetize to the original structure. I think the example result snippet is the best we can do here without storing additional information. This should be sufficient as both leaf values will be returned.
