### ISSUE TITLE
debug plugin failed

### ISSUE THREAD

**Issue by deanjo** [elastic/elasticsearch#111614]
### Elasticsearch Version

8.14.1

### Java Version

17

### OS Version

mac os

### Problem Description

Hello everyone, I am an elasticsearch developer. Due to business needs, I need to develop a plug-in. The logic of this plug-in is relatively complex. I need the degbug plug-in source code. I can debug the plug-in locally in elasticsearch6.8 through the following code,

### Steps to Reproduce

```
public class EmbeddedNode extends Node {

    private Version version;
    private Collection<Class<? extends Plugin>> plugins;

    public EmbeddedNode(Environment environment, Version version, Collection<Class<? extends Plugin>> classpathPlugins) {
        super(environment, classpathPlugins, true);
        this.version = version;
        this.plugins = classpathPlugins;
    }

    public Collection<Class<? extends Plugin>> getPlugins() {
        return plugins;
    }

    public Version getVersion() {
        return version;
    }

    @Override
    protected void registerDerivedNodeNameWithLogger(String nodeName) {

    }
}
```

Modify the startup class and load the custom plug-in org.elasticsearch.bootstrap.Bootstrap
```
//  Line 227 ExamplePlugin is the main class of the custom plugin
        Collection plugins = new ArrayList<>();
        Collections.addAll(plugins, ExamplePlugin.class);
        node = new EmbeddedNode(environment, Version.CURRENT, plugins) {
            @Override
            protected void validateNodeBeforeAcceptingRequests(
                final BootstrapContext context,
                final BoundTransportAddress boundTransportAddress, List<BootstrapCheck> checks) throws NodeValidationException {
                BootstrapChecks.check(context, boundTransportAddress, checks);
            }
        };
```

But in elasticsearch8.14, I can't find any way to degbug the plugin source code locally. Please help me. Thank you very much. 

I posted this question in the elasticsearch official community, but no one responded. I need your help. Thank you. Here is the official community question address. 

https://discuss.elastic.co/t/how-debug-custom-elasticsearch8-14-plugin-in-intellij/364269

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to keep these kinds of things on the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

As there's no change to Elasticsearch needed here, I hope you don't mind that I'm going to close this issue.

**Comment by deanjo** [comment]
This question is very important. I didn’t find any official documentation on how to debug the latest version of the plugin source code, and no one was interested in the question I posted in the official community. 
https://discuss.elastic.co/t/how-debug-custom-elasticsearch8-14-plugin-in-intellij/364269

**Comment by DaveCTurner** [comment]
Sorry, there's no official support for what you're trying to do, nor can we guarantee you'll get a response to questions on the community forum within a certain time limit. If you need a timely response, the best approach would be to engage with the consulting team - see https://www.elastic.co/consulting for more information about that. Otherwise, please see the [Community Code of Conduct](https://www.elastic.co/community/codeofconduct), particularly the bit that says **Be patient**.
