### ISSUE TITLE
Change the default for `http.cors.allow-origin`

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#11169]
We currently have CORS disabled by default since #7151 was merged, but once it is enabled we still allow any origin (`http.cors.allow-origin` defaults to `*`). This is a bad default as a user may just enable CORS without specifying the origins to allow, which means that any site can still issue requests to elasticsearch. We should probably default `http.cors.allow-origin` to `null` like @rashidkpc suggested in https://github.com/elastic/elasticsearch/issues/7151#issuecomment-53098415

**Comment by rmuir** [comment]
+1

**Comment by clintongormley** [comment]
+1
