### ISSUE TITLE
ESQL: no error message on missing index

### ISSUE THREAD

**Issue by alex-spies** [elastic/elasticsearch#111712]
```
curl -u elastic:password -H "Content-Type: application/json" "127.0.0.1:9200/test" -XPUT -d '{
  "mappings": {
        "properties": {
            "x": {
                "type": "long"
            },
            "y": {
                "type": "long"
            }
        }
  }
}'

from test, some_missing_index
```

This doesn't cause an `IndexNotFoundException` anymore, like it did in 8.15.

This is not the same as https://github.com/elastic/elasticsearch/issues/104987 because the index name does not use a wildcard, in which case it's reasonable to be more lenient.

**Comment by bpintea** [comment]
Same as #106805?
