### ISSUE TITLE
Simplify and validate features relying on _source

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#11172]
Today, we have some features that depend on `_source` being complete.  We now have the ability to know whether `_source` exists and has all original fields (no includes/excludes) with #11171.

We now need to add checks to features that rely on source and simplify them.  For example, highlighting currently has code to try and highlight based on stored fields if source does not exist.  We should not do this. As discussed in #8142, disabling source is an advanced feature, and comes with a cost. That cost is some features don't work, and we should simplify highlighting to reflect that.

**Comment by clintongormley** [comment]
also the new reindex API

**Comment by javanna** [comment]
@elastic/es-search-aggs

**Comment by mayya-sharipova** [comment]
The issue is still relevant, and we can improve the validation of the following APIs based how complete is source: 
- update
- update_by_query
- reindex 

For example, currently `reindex` API  only check if the source is available. We can add extra checks if the some fields are missing (`isComplete() == true`) or if reindex API is using only some fields for reindexing, we can add a check to make sure these fields are preset in the _source. If not, we can throw an error and don't proceed with reindexing.

**Comment by henningandersen** [comment]
It seems likely that in all 3 cases, some kind of opt-in would be necessary if we change the default to fail on excluded fields. It can be argued that going into a filtered source use case is advanced and with the current functionality you get what you asked for.

Reindex takes `_source` as is, runs it through an optional script and then indexes into destination. Failing if some fields are excluded from `_source`, would lead to an opt-in option to allow this for the cases where the excluded fields are not needed in target. The question is if this extra option is worth the confusion that such an option could cause for all the full `_source` cases/users.

Reindex supports source filtering. We could in principle fail if source filtering specifies an excluded field. However, source filtering supports wild cards and I think we would have to choose one of:

* Leave is, no failure
* Fail if any source filter expands to an excluded field
* Fail only if source filter does not expand to an included field
* Add an opt-in option.

For update, the update script could extract the excluded fields from doc-values and include them into the updated document (or live with the consequences). This means an opt-in option to avoid the error will be necessary.

Notice that all 3 APIs already fail if `_source` is disabled.

Labelled this discuss to discuss above.

**Comment by henningandersen** [comment]
We discussed this in FixitFriday and agreed not to fix this in order not to have to add an opt-in option for the probable cases where the current functionality (loosing the excluded fields during reindex and update) is what is wanted.
