### ISSUE TITLE
20 minutes and stop service

### ISSUE THREAD

**Issue by johnfelipe** [elastic/elasticsearch#11174]
274.9 MB of 2 GB Used / 1.73 GB Free

And each 20 minutes i need do this:

sudo /etc/init.d/elasticsearch start
curl -XGET 'localhost:9200'

Please give me instructions
Tnks

**Comment by johtani** [comment]
Hi @johnfelipe 
Please join us on https://discuss.elastic.co/ for troubleshooting help, we reserve github for confirmed bugs and feature requests.

**Comment by johnfelipe** [comment]
https://discuss.elastic.co/t/service-stop-each-15-or-20-minutes/765/4, no respond
