### ISSUE TITLE
Rename watcher.interval

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#11175]
This potentially conflicts with settings for the new Watcher plugin, but could be renamed to script.refresh.interval or similar to better reflect the actual use.

See http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html#_automatic_script_reloading for where this is in use

**Comment by jpountz** [comment]
We just discussed this issue and came up with `script.file.reload.interval` to make clear it only applies to script files. This would also need to leverage the deprecation infrastructure: https://github.com/elastic/elasticsearch/pull/11285

**Comment by uboness** [comment]
+1 on rename... `watcher` in the context of elasticsearch doesn't say much. `script.file.reload.interval` focuses on script reloading, while the watcher service in es has a broader function - it's basically a reload service for resources where a "resource" can be anything. So we need to be careful with the rename here and come up with an appropriate more generic name

**Comment by jpountz** [comment]
How about `resource.reload.interval` then? @imotov since you worked on this feature, do you have any opinions on this?

**Comment by imotov** [comment]
Indeed it was meant to be a generic file/url resource reloading mechanism, so I think `resource.reload.interval` would work better.
