### ISSUE TITLE
Descriptions of fuziness overlap

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#11186]
On https://www.elastic.co/guide/en/elasticsearch/reference/master/common-options.html#fuzziness the auto value for fuziness says that 0..1 character terms is no edits allowed and 1..5 is one edit allowed. I suspect its 0..1 character terms is no edits allowed and 2..5 is one edit allowed but I haven't checked.

**Comment by clintongormley** [comment]
Neither :) It's 0..2, 3..5

thanks, fixed

**Comment by nik9000** [comment]
Thanks!
