### ISSUE TITLE
[Discussion] OpenSearch searchable snapshot set-up in Glacier tier

### ISSUE THREAD

**Issue by Sweetnesh** [elastic/elasticsearch#111870]
Hi knowledgeable folks of the forum,

Searching for some guidance and assistance with an OpenSearch searchable snapshot set-up. The intent here is to store the searchable snapshot in one of the cheaper Glacier tiers for cost effective (but still searchable) archival. Performance is not a major consideration here.

Done so far to:

Created snapshot in an S3 bucket.
Restored snapshot using API : POST _snapshot///_restore with storage_type = remote_snapshot.
Index is restored and tested searchable.
Given the somewhat random nature of the data searches, cache has been minimizes as it would unlikely return any meaningful hits.
A few open items so far:

When doing a search for results contained within the searchable index, will the search process all of the snapshot?
Or is the search smart enough to jump directly to the matching blob units within the snapshot?
Would greatly appreciate any thoughts or ideas how to pursue this further.

Thanks!

**Comment by DaveCTurner** [comment]
OpenSearch shares some common ancestry with Elasticsearch but is now a totally separate product. This is not the right place to ask questions about it.
