### ISSUE TITLE
Elasticsearch 8.15 fails to start on Windows with bootstrap.memory_lock

### ISSUE THREAD

**Issue by cstack89** [elastic/elasticsearch#111847]
### Elasticsearch Version

8.15

### Java Version

_bundled_

### OS Version

Windows Server 2019

### Problem Description

When Elasticsearch is installed on Windows 2019 with bootstrap.memory_lock it fails to load with the error.

AssertionError: java.lang.invoke.WrongMethodTypeException: handle's method type (MemorySegment,long,long)MemorySegment but found (MemorySegment,MemorySegment,long,long)boolean
at org.elasticsearch.nativeaccess.jdk.JdkKernel32Library.SetProcessWorkingSetSize(JdkKernel32Library.java:228) elasticsearch-native-8.15.0.jar

### Steps to Reproduce

Install Elasticsearch on Windows and set bootstrap.memory_lock to true.

### Logs (if relevant)

AssertionError: java.lang.invoke.WrongMethodTypeException: handle's method type (MemorySegment,long,long)MemorySegment but found (MemorySegment,MemorySegment,long,long)boolean
at org.elasticsearch.nativeaccess.jdk.JdkKernel32Library.SetProcessWorkingSetSize(JdkKernel32Library.java:228) elasticsearch-native-8.15.0.jar

**Comment by gbanasiak** [comment]
This should get fixed in https://github.com/elastic/elasticsearch/pull/111866.
