### ISSUE TITLE
Making single bucket aggregations a special case of MultiBucket Aggregations

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#11182]
At the moment SingleBucketAggregator extends BucketAggregator and MultiBucketAggregation is a separate interface. This means that single bucket Aggregations are different from multi bucket aggregations which can lead to problems when traversing the aggregation response. The reason for this is that single bucket aggregations don't render the same way as multi-bucket ones and so while parsing a response you need to work out what type of aggregation you are looking at before you know how to parse it.

If would be better if SingleBucketAggregator was a multi-bucket aggregator which just happened to only have a single bucket. In the response there would still be a 'buckets' field but it would only contain a single entry for single-bucket aggregations. This would mean that single and multi bucket aggregation could be treated the same both by users of the REST API and users of the JAVA API.

**Comment by colings86** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/8510

**Comment by colings86** [comment]
Similar to https://github.com/elastic/elasticsearch/issues/8510

**Comment by javanna** [comment]
heya @colings86 should this be closed as a duplicate of #8510 ?

**Comment by colings86** [comment]
closed in favour of #8510
