### ISSUE TITLE
Bulk API returns the very big `took` value instead milliseconds  

### ISSUE THREAD

**Issue by tinder-igorsokolov** [elastic/elasticsearch#111854]
### Elasticsearch Version

8.15

### Java Version

_bundled_

### OS Version

GNU/Linux

### Problem Description

The Bulk API returns a huge took value in 8.15, example:
```json
{
    "errors": false,
    "took": 6641016797,
    "items": [
        {
            "index": {
                "_index": "index-abc17",
                "_id": "2323578",
                "_version": 5,
                "result": "updated",
                "_shards": {
                    "total": 3,
                    "successful": 3,
                    "failed": 0
                },
                "_seq_no": 79341,
                "_primary_term": 11,
                "status": 200
            }
        }
    ]
}
```
although according to the documentation it is integer (32 bit).  
> took
(integer) How long, in milliseconds, it took to process the bulk request.

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html

This causes the Jackson parse exception in our internal library (the official Elastic `ElasticsearchClient` uses `long` internally).
Even if I fix it to be `long` in our library the value seems to be odd: something completed within `6,641,016,797` ms? 

### Steps to Reproduce

In the DevConsole:

1.  
  ```
  PUT magic-index
  {
    "mappings": {
      "properties": {
        "user_number": {
          "type": "keyword"
        }, 
        "active_time": {
          "type": "date"
        }, 
        "keywords": {
          "type": "keyword"
        }
      }
    }
  }
  ```

2.
  ```
  POST _bulk
  {"index":{"_id":"32","_index":"magic-index"} }
  {"user_number": "213343334", "active_time": "2024-11-15T16:50:14.167-04:00", "keywords": "alpha"}
  ```

3. 
the result is 

  ```json
  {
    "errors": false,
    "took": 9430291,
    "items": [
      {
        "index": {
          "_index": "magic-index",
          "_id": "32",
          "_version": 1,
          "result": "created",
          "_shards": {
            "total": 2,
            "successful": 2,
            "failed": 0
          },
          "_seq_no": 0,
          "_primary_term": 1,
          "status": 201
        }
      }
    ]
  }
```

**Comment by DaveCTurner** [comment]
The fact that values like this may exceed the bounds of a 32-bit integer is [covered in these docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/api-conventions.html#_number_values):

> Integer-valued fields in a response body are described as integer (or occasionally long) in this manual, but there are generally no explicit bounds on such values. JSON, SMILE, CBOR and YAML all permit arbitrarily large integer values. Do not assume that `integer` fields in a response body will always fit into a 32-bit signed integer.

However it is indeed surprising to see such large values here. I think this is a bug introduced by https://github.com/elastic/elasticsearch/pull/109889.

**Comment by tinder-igorsokolov** [comment]
@DaveCTurner thank you for a very quick reply. 

>  Do not assume that integer fields in a response body will always fit into a 32-bit signed integer.

point taken! I will align our library with the spec. 

I updated the bug title to point to more critical issue for us: our bulk index metrics will be broken if we move to 8.15.

**Comment by masseyke** [comment]
Really sorry about that. The fix is in a PR now.
