### ISSUE TITLE
org.elasticsearch.simdvec.VectorScorerFactoryTests hit new Lucene assert in snapshot branch

### ISSUE THREAD

**Issue by ChrisHegarty** [elastic/elasticsearch#111885]
### Description

The test attempts to verify that the ES and Lucene vector scorers return the same scores, but hits a newly added assert for vectors with boundary values, specifically values of Float.MAX_VALUE.  Does this large value even make sense?

### Repro line

./gradlew ":libs:elasticsearch-simdvec:test" --tests "org.elasticsearch.simdvec.VectorScorerFactoryTests.testRandomScorerMax" -Dtests.seed=BF702AE3A9178E5 -Dtests.locale=hi-IN -Dtests.timezone=CTT -Druntime.java=22

### Does it reproduce?

Yes

### Applicable branches

lucene_snapshot

### Failure excerpt

```
  2> java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([BF702AE3A9178E5:D0A1149D97C1AD52]:0)
        at org.apache.lucene.util.quantization.ScalarQuantizer.quantize(ScalarQuantizer.java:117)
        at org.apache.lucene.codecs.hnsw.ScalarQuantizedVectorScorer.quantizeQuery(ScalarQuantizedVectorScorer.java:59)
        at org.elasticsearch.simdvec.VectorScorerFactoryTests.testRandomScorerImpl(VectorScorerFactoryTests.java:251)
        at org.elasticsearch.simdvec.VectorScorerFactoryTests.testRandomScorerMax(VectorScorerFactoryTests.java:222)
...
```

**Comment by benwtrent** [comment]
>     assert similarityFunction != VectorSimilarityFunction.COSINE || VectorUtil.isUnitVector(src);


The goal of this assertion is ensuring that vectors are normalized if they are COSINE. There was a bug in Lucene where they weren't actually being normalized at different quantization steps, and consequently ended up hurting recall.

**Comment by ChrisHegarty** [comment]
What is the upper bound limit on the set of values we expect to support in float vectors? For example, Float.MAX_VALUE causes a problem for this assertion.

**Comment by benwtrent** [comment]
> What is the upper bound limit on the set of values we expect to support in float vectors? For example, Float.MAX_VALUE indirectly causes the problem for this assertion.

I wouldn't expect `Float.MAX_VALUE` to be a normalized vector at all. Are we normalizing before calling?

**Comment by ChrisHegarty** [comment]
The test is just checking that the Native and Lucene implementation of the scorers return the same results. We had problems with boundary values in the past, at least for byte, so the test is just trying to check with the upper and lower boundary values that are possible. So the test creates a query vector whose values are all Float.MAX_VALUE. I think that this test doesn't make much sense now that I look at it. It used to pass, but likely not testing anything terribly useful.   

So that leads to the question, what is the max expected value that any particular `float` value of a query vector is expected to have? E.g between -1.0f and + 1.0f ?

**Comment by ChrisHegarty** [comment]
Ok, so I assume that the expectation is that the arithmetic on the vector values always returns a **finite value**, regardless of the input. Rather than any particular upper and lower bounds on the individual values.

**Comment by benwtrent** [comment]
> So the test creates a query vector whose values are all Float.MAX_VALUE. I think that this test doesn't make much sense now that I look at it. It used to pass, but likely not testing anything terribly useful.

I understand. For any similarity other than cosine, that makes sense. But for cosine, we have the assertion that all vector dimensions will sum up to 1. Usually, normalized vectors have dimensional values `-1, +1`.
