### ISSUE TITLE
External list of exclude values for terms aggregation filtering

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#11190]
Would be nice to be able to specify an external list of exclude values to read from (and not have to include all of them in the request in an array) when filtering values for use cases where they can be thousands of exclude values.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_filtering_values

**Comment by jpountz** [comment]
I'm a bit worried about making it easier to have large exclude lists. Do you have more information about the use-case?

**Comment by ppf2** [comment]
Use case is that the end user has some domain/industry specific stop words that they would like to exclude from the aggregated bucket values and would rather not index a separate analyzed field (lot of data) with a stop filter.  They are looking into other approaches now after realizing that the exclude feature may not perform well with large lists today until 2.x.

**Comment by clintongormley** [comment]
A query time solution is never going to perform as well as an index time solution.  This feels trappy to me.  I'd say a better solution for them would be to use the stopwords token filter, and maintain a "patch" list of extra terms which they pass to each aggregation.  Periodically, they could reindex their data in the background to update the stopwords list.

**Comment by jpountz** [comment]
+1
Closing
