### ISSUE TITLE
[Retrievers] Rerank retriever doesn't notify of / error on non-existant inference_id

### ISSUE THREAD

**Issue by maxhniebergall** [elastic/elasticsearch#111934]
### Elasticsearch Version

serverless

### Java Version

_bundled_

### OS Version

n/a

### Problem Description

when performing semantic search with reranking retriever, the retriever doesn't throw an error if the inference_id doesn't exist

```
client.search(
        index="characters-index",
        retriever={
            "text_similarity_reranker": {
                "retriever": {
                    "standard": {
                        "query": {"semantic": {"field": "infer_field", "query": "robinson"}}
                    }
                },
                "field": "titles",
                "inference_id": "fake_inference_endpoint",
                "inference_text": "robinson",
                "rank_window_size": 100,
            }
        },
    )

```

### Steps to Reproduce

perform a search on an index using reranking retriever with a non-existant inference endpoint

```
client.search(
        index="characters-index",
        retriever={
            "text_similarity_reranker": {
                "retriever": {
                    "standard": {
                        "query": {"semantic": {"field": "infer_field", "query": "robinson"}}
                    }
                },
                "field": "titles",
                "inference_id": "coherzfe_rerank",
                "inference_text": "robinson",
                "rank_window_size": 100,
            }
        },
    )
```

should return an error but no results are returned instead.

**Comment by maxhniebergall** [comment]
@Mikep86, do you know who should investigate this issue?

**Comment by maxhniebergall** [comment]
It also doesn't produce an error (just not no results) when the field name is wrong (non-existant).

**Comment by Mikep86** [comment]
@maxhniebergall I think this issue belongs to the search relevance team. I added it to the semantic reranking backlog. Thank you for reporting it!
