### ISSUE TITLE
8.14.1 KQL facing an index（message&event.original） that cannot display all characters

### ISSUE THREAD

**Issue by dobixu** [elastic/elasticsearch#111920]
### Elasticsearch Version

8.14.1

### Java Version

openjdk 22.0.1 2024-04-16

### OS Version

CentOS Linux release 7.9.2009 (Core)

### Problem Description

#  Problem Description
Kibana KQL query index "  internet-waf-access  ",only 1024 characters  displayed。When I edit message, I can see all characters when I try to preview can see  full characters

### index  internet-waf-access:
PROCESS: WAF > logstash >  es
message&event.original：1024 characters
PREVIEW:  full characters

### other index  full characters:     
PROCESS:filebeat > logstash >  es 
message&event.original：full characters

### index  internet-waf-access  :
PROCESS :   WAF  >  logstash >  es
message&event.original：full characters

###  other index:     
PROCESS:filebeat > logstash >  es 
message&event.original：full characters

## ELFK VERSION：8.14.1  Screenshot
<img width="1007" alt="8 14 1-1 edit preview" src="https://github.com/user-attachments/assets/5f4dc827-ef8c-456e-9390-0dc28beb365f">
<img width="1052" alt="8 14 1-2 edit preview full characters" src="https://github.com/user-attachments/assets/29747619-c647-4f4c-b791-e09771e46468">
<img width="1459" alt="8 14 1-3 kql 1024 characters" src="https://github.com/user-attachments/assets/27a93ebc-c05c-4441-b5ef-b7863a96c9a4">
<img width="1323" alt="8 14 1-4 count kql" src="https://github.com/user-attachments/assets/f7ac0248-1dc5-4830-b020-aad5428fc241">
![8 14 1-5 curl es](https://github.com/user-attachments/assets/8fd67cf1-c4cb-4070-b460-35bda96f2030)

 
## ELFK VERSION：8.0.0  Screenshot

<img width="1478" alt="8 0 0ksql" src="https://github.com/user-attachments/assets/dda904c5-2aa3-4aeb-b3ac-fd9002e74a2b">

### Steps to Reproduce

Check Problem Description

### Logs (if relevant)

Check Problem Description

**Comment by dobixu** [comment]
## ELFK VERSION：8.14.1 Screenshot
### Supplementary Image" 8.14.1-5
![8 14 1-5 curl es](https://github.com/user-attachments/assets/545a9616-e114-4d1e-b72e-4c688a384d32)

**Comment by henningandersen** [comment]
It is not entirely clear if you intend to file a bug in kibana or Elasticsearch. For Elasticsearch I would expect to see a clear explanation of the API that delivers a truncated result. This appears to be more of a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) or the [Kibana forum](https://discuss.elastic.co/c/elastic-stack/kibana/7). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by dobixu** [comment]
Got it .Sir
