### ISSUE TITLE
toReleaseVersion() returns the wrong value on released elasticsearch versions

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#111900]
`toReleaseVersion()` returns the wrong value for released elasticsearch versions. Instead of returning a single version number, it returns a range like so:

`8.13.5-snapshot[8505000]`

This is particularly egregious on minor version releases, where the text is a range with a snapshot version number.

This is because the current released version number is not included in the index/transport version lookup tables included in the release, so it doesnt know its own version number. The tables are updated as part of the release finalization, but the on-prem release is taken from the commit _before_ the release finalization step.

The fact that it has been like this for several releases, with no reported bugs, is a good indication that nothing serious is broken as a result of this. This string is just used in human-visible scenarios, nothing should be consuming these strings.

**Comment by thecoop** [comment]
This is a problem from 8.14.0+. Prior versions use the raw index version number

**Comment by thecoop** [comment]
@mark-vieira The release is generated from the commit **before** the finalize versions commit, yes? How tricky is it to add a commit before then to set these version numbers?

**Comment by mark-vieira** [comment]
> @mark-vieira The release is generated from the commit **before** the finalize versions commit, yes? How tricky is it to add a commit before then to set these version numbers?

So the bump would have to be two steps? Or would this change have to be included in the commit the release is done from?

**Comment by DaveCTurner** [comment]
> The most critical is the version number in snapshot metadata

I believe we hard-code the string representation of the version as "8.11.0" and use only the numeric ID:

https://github.com/elastic/elasticsearch/blob/cfbda244b81a47915f3ea1bedfd40287df2fe380/server/src/main/java/org/elasticsearch/repositories/RepositoryData.java#L782-L792

**Comment by thecoop** [comment]
> So the bump would have to be two steps? Or would this change have to be included in the commit the release is done from?

Yes - we would need a commit to update the version number tables, then we take that commit and generate the release from it, then we do a new commit to update all the version numbers for v.next. To prevent races we could push both at once, then check out the first commit and release from there.

**Comment by mark-vieira** [comment]
> Yes - we would need a commit to update the version number tables, then we take that commit and generate the release from it, then we do a new commit to update all the version numbers for v.next. To prevent races we could push both at once, then check out the first commit and release from there.

This is going to be difficult to accomplish because we don't know exactly what commit we are going to generate the release from. At any time we might have a new build candidate and these things could change.

**Comment by rjernst** [comment]
> we could update the files in the build directories instead?

This seems reasonable to me. So we would take the existing csv (which has all previous, finalized versions mapped), then amend it with the current release version we are building (in a temporary build file), and that is the file that actually gets adds to the jar.

Alternatively, could we figure this out dynamically? We know the latest version id, and we know the current version number. We could insert that into the runtime map after loading the csv.

**Comment by mark-vieira** [comment]
> This seems reasonable to me. So we would take the existing csv (which has all previous, finalized versions mapped), then amend it with the current release version we are building (in a temporary build file), and that is the file that actually gets adds to the jar.

Presumably there's be no reason to commit these to source control then? We'd just generate this on every build?

> Alternatively, could we figure this out dynamically? We know the latest version id, and we know the current version number. We could insert that into the runtime map after loading the csv.

If the we can infer all this from information we already has then yes, just generating this on every build, or at runtime seems to make a lot more sense than statically bumping a source controlled file periodically.

**Comment by rjernst** [comment]
> Presumably there'd be no reason to commit these to source control then?

No, the past releases are not inferable. But the latest (last transport version is equal to current version) is inferable. We still need to follow up with a commit adding the exact transport version that was released to the csv. But we can do so as part of release finalization. The release build, though, won't need a new commit.

**Comment by mark-vieira** [comment]
This plan sounds good to me. So we'll update when we do the version bump (as part of release finalization) but for the purposes of determining the transport version for the current stack version, we'll just use the current transport version.
