### ISSUE TITLE
Contributing to elasticsearch page has html all over "Bug Reports"

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#11206]
Have a look at https://www.elastic.co/contributing-to-elasticsearch under the bug reports section. I think that is supposed to be highlighted bash script but its all ```<pre>```ed now.

**Comment by nik9000** [comment]
Ping @clintongormley  I think this is yours?

**Comment by clintongormley** [comment]
thanks @nik9000 - fixed
