### ISSUE TITLE
delete es doc by _id

### ISSUE THREAD

**Issue by Jerry-yz** [elastic/elasticsearch#112047]
### Elasticsearch Version

7.13.2

### Java Version

_bundled_

### OS Version

linux

### Problem Description

when i delete es doc by _id and index, it failed Conflict 409

### Steps to Reproduce

i use golang and pkg github.com/olivere/elastic/v7
`	updateQuery := elastic.NewBoolQuery().
		Must(elastic.NewTermsQuery("_id", ids...)).
		Must(elastic.NewTermQuery(constant.KeywordAccount, account))

	// 执行删除刷新
	_, err := client.DeleteByQuery().Refresh("true").
		Index(index).
		Query(updateQuery).
		Do(context.Background())
	if err != nil {
		mylog.Error("delete alarm log failed", zap.Error(err))
		return err
	}`

**Comment by DaveCTurner** [comment]
Thank you very much for your interest in Elasticsearch. Unfortunately the issue you have reported relates to Elasticsearch version 7.13.2 which is very old and has passed [end-of-life](https://www.elastic.co/support/eol). We will not investigate issues related to unsupported versions here on Github, so I am closing this to indicate that no action is needed from the Elasticsearch development team. It's possible that you will find a volunteer to help you with this issue on the [community forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), but our strong recommendation would be to upgrade to a supported version of Elasticsearch as a matter of some urgency. If you can reproduce your issue on a supported version then please open a fresh bug report.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.
