### ISSUE TITLE
detect_noop doesn't work with null values

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#11208]
The `detect_noop` flag doesn't work if a field contains a `null` value:

    PUT t/t/1
    {
      "foo": "baz",
      "bar": "baz"
    }

This update request always returns the same version:

    POST t/t/1/_update
    {
      "doc": {
        "foo": "baz",
        "bar": "baz"
      },
      "detect_noop": true
    }

While this one always returns a new version:
    
    POST t/t/1/_update
    {
      "doc": {
        "foo": "baz",
        "bar": null
      },
      "detect_noop": true
    }

**Comment by nik9000** [comment]
Eww. I can have a look in a bit.

**Comment by nik9000** [comment]
low hanging fruit indeed.

**Comment by ppf2** [comment]
@nik9000 @clintongormley  Thx for the super quick turnaround on this :+1:
