### ISSUE TITLE
Snapshot/Restore: Add repository-level throttling to the snapshot and restore operations

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#11214]
In #4855 we added node-level throttling to snapshot and restore operation. While this helps to prevent an individual node from being overloaded, it doesn't protect overloading of the repository or the network that can be targeted by unpredictable load ranging from load from a single node to load from all data nodes in the cluster. See #11148 for an example of the issues that this is causing.

**Comment by ywelsch** [comment]
We have no immediate plans to work on this so I'm going to close the issue. Please feel free to comment or +1 here if you want to add your point of view.
