### ISSUE TITLE
Too many TCP Connection Issue - transport client

### ISSUE THREAD

**Issue by linuzvipin** [elastic/elasticsearch#11211]
Hi i use java transport client to connect to es- 1.4.2.
i use many connection configuration but i found that a single es query open more than 50 TCP connection , which never close until i stop tomcat.
connection increase on each query so if i query 4 times then more than 200 tcp connection is open and never close. so by this way i soon reached resource limit. and my tomcat kill by linux OOM ( out of memory ).
can anyone help me to figure it out , how to close a tcp connection after query?
i try many configuration but still no luck.

**Comment by clintongormley** [comment]
Hi @linuzvipin 

It sounds like you keep creating new transport clients instead of reusing existing ones.  I suggest you ask about the proper way to use the client on the forum rather than here: https://discuss.elastic.co/c/elasticsearch

thanks

**Comment by FriendyHua** [comment]
Hi @clintongormley
could you please tell me how to reuse the connection ? 

Thanks
