### ISSUE TITLE
ElasticSearch 1.5.2 Cluster name

### ISSUE THREAD

**Issue by sandesh2014** [elastic/elasticsearch#11219]
Cluster name is not being changed from default "Elasticsearch" to custom name.

ES Version 1.5.2

**Comment by jpountz** [comment]
Do you mean that changing the `cluster.name` setting in `elasticsearch.yml` has no effect?

**Comment by aanuprab** [comment]
I'm on 1.5.2 and it seems to be working fine. Any specifics you could add?

**Comment by clintongormley** [comment]
No more info provided. Most likely a config issue.  I suggest asking for advice in the forum instead: https://discuss.elastic.co/c/elasticsearch
