### ISSUE TITLE
"No such remote cluster" error message for non-CCS URL

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#112243]
### Description

Index with date math taken from [the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.15/api-conventions.html#api-date-math-index-names).
The URL below should decode to `POST /localhost:9200/-<logstash-{now/d{yyyy.MM.dd|+12:00}}>` (notice the minus sign before the date math index pattern).

```
POST /localhost:9200/-%3Clogstash-%7Bnow%2Fd%7Byyyy.MM.dd%7C%2B12%3A00%7D%7D%3E/_search

{
    "query":{"match_all":{}}
}
```

results in 

```
{
    "error": {
        "root_cause": [
            {
                "type": "no_such_remote_cluster_exception",
                "reason": "no such remote cluster: [-<logstash-{now/d{yyyy.MM.dd|+12]"
            }
        ],
        "type": "no_such_remote_cluster_exception",
        "reason": "no such remote cluster: [-<logstash-{now/d{yyyy.MM.dd|+12]"
    },
    "status": 404
}
```

If I remove the minus sign from the index pattern the query succeeds. Meaning `POST /localhost:9200/%3Clogstash-%7Bnow%2Fd%7Byyyy.MM.dd%7C%2B12%3A00%7D%7D%3E/_search`

**Comment by smalyshev** [comment]
The code handling this is from https://github.com/elastic/elasticsearch/pull/100646 but it doesn't account for the possibility of `-` prefix.

**Comment by smalyshev** [comment]
I don't think the expression with the pattern starting with the minus sign is valid though. There should be a preceding wildcard expression before `-` is used.

**Comment by smalyshev** [comment]
I notice however that the pattern with `*,-...` which is valid is also broken, so that needs to be fixed.
