### ISSUE TITLE
docker-compose.yml only es01 can connect es02 and es03 "unable to authenticate user [elastic] for REST request"

### ISSUE THREAD

**Issue by ygqygq2** [elastic/elasticsearch#112235]
### CI Link

xx

### Repro line

xx

### Does it reproduce?

Yes

### Applicable branches

8.15.0

### Failure excerpt

Test with https://github.com/elastic/elasticsearch/blob/8.15/docs/reference/setup/install/docker/docker-compose.yml 
Only es01 can connect properly, es02 and es03 can not，the error is

```
unable to authenticate user [elastic] for REST request
```

**Comment by ygqygq2** [comment]
I entered the es02 container to reset the password, the cluster becames normal.

```
elasticsearch-reset-password -u elastic
```

**Comment by slobodanadamovic** [comment]
@ygqygq2 Based on the info you provided it is hard to reproduce this. Could you provide us more information/logs on your setup?  

> Only es01 can connect properly, es02 and es03 can not

What do you mean by `can connect properly`? Do you mean you can authenticate with `elastic` user to es01 but not to es02 and es03? 

> I entered the es02 container to reset the password, the cluster becames normal.

What do you mean by `the cluster becames normal`? Have you made sure that your ELASTIC_PASSWORD is configured properly and that it does not contain any special characters ([as per our docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#:~:text=In%20the%20.env,alphanumeric%20characters.%20Example%3A))?

> _In the .env file, specify a password for the ELASTIC_PASSWORD and KIBANA_PASSWORD variables._
> _The passwords must be alphanumeric and can’t contain special characters, such as ! or @. The bash script included in the docker-compose.yml file only works with alphanumeric characters._

**Comment by slobodanadamovic** [comment]
Since this appears to be a user question, I'd appreciate if you could ask it on the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community on the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by ygqygq2** [comment]
@slobodanadamovic 
`docker-compose.yml`, I haven't changed anything. Reproduce this issue at any time.  Use curl change passowrd instead of `elasticsearch-reset-password -u elastic`.

![Image](https://github.com/user-attachments/assets/dfd8bc01-e01d-4112-8e73-abc6b468d779)

![Image](https://github.com/user-attachments/assets/4f9ae4ad-b970-49a9-9aab-a38d9cbdbe4b)

![Image](https://github.com/user-attachments/assets/79ac74df-fcac-4987-94e1-13edc47e490e)

![Image](https://github.com/user-attachments/assets/e76b32e6-bf13-4836-9c1f-dbdfce7446d9)

![Image](https://github.com/user-attachments/assets/ebb6ae68-7712-4418-abb5-7966412c2d93)

**Comment by slobodanadamovic** [comment]
@ygqygq2 Thanks for sharing steps to reproduce. I can confirm that this is indeed a bug in our docker-compose file. I will raise a PR shortly to fix this.
