### ISSUE TITLE
Endpoint to trigger loading shard info

### ISSUE THREAD

**Issue by ywelsch-t** [elastic/elasticsearch#11229]
Feature suggestion that complements #9502 #11101

Loading shard info during startup of a cluster can be quite slow. PR #11101 addresses one of the pain points by parallelizing the requests for loading shard state info. Still, data needs to be read from disk to compute checksums. Pre-warming the file system cache can dramatically speed this up.

I suggest an endpoint to load shard info that can be manually triggered before doing a full restart of a cluster (e.g. before upgrading). Depending on FS cache usage, the endpoint could also be regularly triggered (which would help in case of an unexpected master node failure).

A test on our production cluster (ES 1.4.5) shows that it takes approx. 3 minutes to load shard stores / states on one of the largest nodes with magnetic disk. With a warmed-up FS cache it takes only 3 seconds.

**Comment by clintongormley** [comment]
Hi @ywelsch-t 

I'm not really understanding why this should be an end point which you have to call manually.  The system has to do the work regardless (and if you don't have enough FS cache it might have to do the work twice).  Why not just let it happen when it needs to?

**Comment by ywelsch-t** [comment]
@clintongormley At the moment, the "loading shard info" operation is only triggered if a cluster starts up (or master failover). The longer it takes to read the shard info, the longer the cluster stays red. In a large cluster, it takes quite a while. The goal of this endpoint is to reduce downtime of a cluster in case of restart/failover/upgrade. It is realized by warming the filesystem caches before shutting down the cluster so that reading the shard info upon restart goes faster.

**Comment by clintongormley** [comment]
@ywelsch do you still think we need to do something here?
