### ISSUE TITLE
Found Elasticsearch with Aliased Index with Routing

### ISSUE THREAD

**Issue by dbhattacharjee** [elastic/elasticsearch#11227]
We have multiple organization having identical structure of records in Database. We are using ES with aliased index and routing features for each organization. Now, when we clear the ES index and start with clean state, then search records is coming properly from ES. But when we adding multiple organizations, ES is behaving strangely. Sometimes it is sending data of another organization or sometimes it just suppress data. Even more alarming, sometimes it is sending data of record which is not even searched ! "john" it is retuning "Ringo", searching via "Mick" returning "John".

BTW, we are using Symfony2 and FosElasticabundle for all of the above operations.

Further Investigations :

    Index only one org. Data is coming for that org.
    Index another one org. Data is coming for that org too.
    Index third org. Data is lost for first org !.

Images :

    Clean state : http://imageshack.com/i/idNW3QVCp
    With one org. being indexed: http://imageshack.com/i/f0zTd4YEp, http://imageshack.com/i/idKl1oQrp
    With another org. being indexed: http://imageshack.com/i/pbWP7YiNp, http://imageshack.com/i/p8eUMiDxp
    With third org. being index: http://imageshack.com/i/ipxfEXo3p, http://imageshack.com/i/eyeS46fGp
    Log from Sf2: http://imageshack.com/i/f03ZQ8IOp

ES Server status :
{
  "_shards" : {
    "total" : 10,
    "successful" : 5,
    "failed" : 0
  },
  "indices" : {
    "organizations" : {
      "index" : {
        "primary_size_in_bytes" : 54928,
        "size_in_bytes" : 54928
      },
      "translog" : {
        "operations" : 106
      },
      "docs" : {
        "num_docs" : 50,
        "max_doc" : 73,
        "deleted_docs" : 23
      },
      "merges" : {
        "current" : 0,
        "current_docs" : 0,
        "current_size_in_bytes" : 0,
        "total" : 0,
        "total_time_in_millis" : 0,
        "total_docs" : 0,
        "total_size_in_bytes" : 0
      },
      "refresh" : {
        "total" : 125,
        "total_time_in_millis" : 204
      },
      "flush" : {
        "total" : 0,
        "total_time_in_millis" : 0
      },
      "shards" : {
        "0" : [ {
          "routing" : {
            "state" : "STARTED",
            "primary" : true,
            "node" : "ficq9zDSRM2HJTGLk2BZ7g",
            "relocating_node" : null,
            "shard" : 0,
            "index" : "organizations"
          },
          "state" : "STARTED",
          "index" : {
            "size_in_bytes" : 15923
          },
          "translog" : {
            "id" : 1432033150513,
            "operations" : 42
          },
          "docs" : {
            "num_docs" : 21,
            "max_doc" : 21,
            "deleted_docs" : 0
          },
          "merges" : {
            "current" : 0,
            "current_docs" : 0,
            "current_size_in_bytes" : 0,
            "total" : 0,
            "total_time_in_millis" : 0,
            "total_docs" : 0,
            "total_size_in_bytes" : 0
          },
          "refresh" : {
            "total" : 25,
            "total_time_in_millis" : 114
          },
          "flush" : {
            "total" : 0,
            "total_time_in_millis" : 0
          }
        } ],
        "1" : [ {
          "routing" : {
            "state" : "STARTED",
            "primary" : true,
            "node" : "ficq9zDSRM2HJTGLk2BZ7g",
            "relocating_node" : null,
            "shard" : 1,
            "index" : "organizations"
          },
          "state" : "STARTED",
          "index" : {
            "size_in_bytes" : 123
          },
          "translog" : {
            "id" : 1432033150524,
            "operations" : 0
          },
          "docs" : {
            "num_docs" : 0,
            "max_doc" : 0,
            "deleted_docs" : 0
          },
          "merges" : {
            "current" : 0,
            "current_docs" : 0,
            "current_size_in_bytes" : 0,
            "total" : 0,
            "total_time_in_millis" : 0,
            "total_docs" : 0,
            "total_size_in_bytes" : 0
          },
          "refresh" : {
            "total" : 25,
            "total_time_in_millis" : 1
          },
          "flush" : {
            "total" : 0,
            "total_time_in_millis" : 0
          }
        } ],
        "2" : [ {
          "routing" : {
            "state" : "STARTED",
            "primary" : true,
            "node" : "ficq9zDSRM2HJTGLk2BZ7g",
            "relocating_node" : null,
            "shard" : 2,
            "index" : "organizations"
          },
          "state" : "STARTED",
          "index" : {
            "size_in_bytes" : 4782
          },
          "translog" : {
            "id" : 1432033150529,
            "operations" : 8
          },
          "docs" : {
            "num_docs" : 8,
            "max_doc" : 8,
            "deleted_docs" : 0
          },
          "merges" : {
            "current" : 0,
            "current_docs" : 0,
            "current_size_in_bytes" : 0,
            "total" : 0,
            "total_time_in_millis" : 0,
            "total_docs" : 0,
            "total_size_in_bytes" : 0
          },
          "refresh" : {
            "total" : 25,
            "total_time_in_millis" : 11
          },
          "flush" : {
            "total" : 0,
            "total_time_in_millis" : 0
          }
        } ],
        "3" : [ {
          "routing" : {
            "state" : "STARTED",
            "primary" : true,
            "node" : "ficq9zDSRM2HJTGLk2BZ7g",
            "relocating_node" : null,
            "shard" : 3,
            "index" : "organizations"
          },
          "state" : "STARTED",
          "index" : {
            "size_in_bytes" : 123
          },
          "translog" : {
            "id" : 1432033150518,
            "operations" : 0
          },
          "docs" : {
            "num_docs" : 0,
            "max_doc" : 0,
            "deleted_docs" : 0
          },
          "merges" : {
            "current" : 0,
            "current_docs" : 0,
            "current_size_in_bytes" : 0,
            "total" : 0,
            "total_time_in_millis" : 0,
            "total_docs" : 0,
            "total_size_in_bytes" : 0
          },
          "refresh" : {
            "total" : 25,
            "total_time_in_millis" : 0
          },
          "flush" : {
            "total" : 0,
            "total_time_in_millis" : 0
          }
        } ],
        "4" : [ {
          "routing" : {
            "state" : "STARTED",
            "primary" : true,
            "node" : "ficq9zDSRM2HJTGLk2BZ7g",
            "relocating_node" : null,
            "shard" : 4,
            "index" : "organizations"
          },
          "state" : "STARTED",
          "index" : {
            "size_in_bytes" : 33977
          },
          "translog" : {
            "id" : 1432033150546,
            "operations" : 56
          },
          "docs" : {
            "num_docs" : 21,
            "max_doc" : 44,
            "deleted_docs" : 23
          },
          "merges" : {
            "current" : 0,
            "current_docs" : 0,
            "current_size_in_bytes" : 0,
            "total" : 0,
            "total_time_in_millis" : 0,
            "total_docs" : 0,
            "total_size_in_bytes" : 0
          },
          "refresh" : {
            "total" : 25,
            "total_time_in_millis" : 78
          },
          "flush" : {
            "total" : 0,
            "total_time_in_millis" : 0
          }
        } ]
      }
    }
  }
}

It seems ES is overwriting data of existing aliases when another org. is being indexed. But that is deal breaker. Please advice.

**Comment by clintongormley** [comment]
Hi @dbhattacharjee 

This sounds like a misunderstanding of how to use Elasticsearch, but you haven't provided any curl statements to help recreate the issue.  I suggest you ask your question in the forum instead (https://discuss.elastic.co/c/elasticsearch) and that you provide a recreation demonstrating the problem in curl.  That way it'll be easy for others to figure out where you are going wrong.
