### ISSUE TITLE
Snapshot delete hangs forever

### ISSUE THREAD

**Issue by prog8** [elastic/elasticsearch#11232]
I hit strange issue on ES 1.4.1. When I started snapshot it hanged and I cannot see any progress. I use S3 plugin. The output from _snapshot API call is presented below.

```
  curl -XGET http:'//localhost:9200/_snapshot/aws-prod-elasticsearch-backup/snapshot-name?pretty'
  {
    "snapshots" : [ {
      "snapshot" : "snapshot-name",
      "indices" : [ ... list of indices ... ],
      "state" : "IN_PROGRESS",
      "start_time" : "2015-05-18T04:11:40.344Z",
      "start_time_in_millis" : 1431922300344,
      "failures" : [ ],
      "shards" : {
        "total" : 0,
        "failed" : 0,
        "successful" : 0
      }
    } ]
  }
```

When I try to delete the snapshot

```
curl -XDELETE 'http://localhost:9200/_snapshot/aws-prod-elasticsearch-backup/snapshot-name
```

the command hangs forever. I thought I can try to use the cleaning tool (https://github.com/imotov/elasticsearch-snapshot-cleanup) to make cleanup. It didn't help.

Then I modified source code (https://github.com/imotov/elasticsearch-snapshot-cleanup/blob/master/src/main/java/org/motovs/elasticsearch/snapshots/AbortedSnapshotCleaner.java) to cleanup all possible snapshots by removing this condition:

```java
if (shard.getValue().state() == SnapshotMetaData.State.ABORTED && clusterState.nodes().get(nodeId) == null) {
```

Does anyone also encountered similar issue?

**Comment by imotov** [comment]
@prog8 the hanging delete issue should be fixed by #9981. Did you restart the master node while the snapshot was running?

**Comment by prog8** [comment]
Hi @imotov  thanks for your reply. Yes master nodes were restarted. I hope upgrade to newer ES will resolve the issue.

**Comment by vanga** [comment]
@prog8 we had this issue, an upgrade to 1.5.0 resolved the issue.

**Comment by jpountz** [comment]
Closing due to lack of feedback
