### ISSUE TITLE
Elastic Agent: Not getting Data with 8.15.0

### ISSUE THREAD

**Issue by ncrnkr** [elastic/elasticsearch#112344]
### Elasticsearch Version

8.15.0

### Installed Plugins

Azure Logs

### Java Version

_bundled_

### OS Version

Windows 11

### Problem Description

We have now set up an Elastic Cloud. This receives its data from Azure and from the agent. The agent with version 8.15.0 is installed on the test VM via CMD. Elastic also receives the connection to the agent, but does not receive any data.

The first thing we found out was that we are not allowed to use a hyphen in the namespace. We have fixed this, but unfortunately this has not led to any improvement.
Only when we installed the namespace without the hyphen and the agent with version 8.14.3 did everything work and we got our data from the Azure Cloud and from the client.

### Steps to Reproduce

We use the “Azure Logs” extension and have installed the latest agent version 8.15.0.
The namespace connection string and storage connection string are stored in the policy.

**Comment by v1p3r0u5** [comment]
looks like it is linked to this one: https://github.com/elastic/beats/issues/40608

**Comment by zmoog** [comment]
> looks like it is linked to this one: [elastic/beats#40608](https://github.com/elastic/beats/issues/40608)

@v1p3r0u5, thank you for sharing the link!

**Comment by kingherc** [comment]
@zmoog this means we can close this ticket?

**Comment by gwbrown** [comment]
As it appears that 1) the issue addressed by this ticket has been addressed, and 2) is for Agent, rather than Elasticsearch, I'm going to close this ticket. Please do correct me if I've misunderstood.
