### ISSUE TITLE
copy_to needs top level object 

### ISSUE THREAD

**Issue by celesteking** [elastic/elasticsearch#11237]
You should specify that ```{"copy_to": "top.child"}```  needs ```top``` field defined first, otherwise it would throw an error when indexing.

Also, I'm completely dissatisfied with the documentation on the site.

**Comment by clintongormley** [comment]
Hi @celesteking 

I'd say this is a bug.  Recreation:

    PUT test 
    {
      "mappings": {
        "test": {
          "properties": {
            "foo": {
              "type": "string",
              "copy_to": "top.child"
            }
          }
        }
      }
    }
    
    PUT test/test/1
    {
      "foo": "bar"
    }

returns:

    {
       "error": "MapperParsingException[attempt to copy value to non-existing object [top.child]]",
       "status": 400
    }

> Also, I'm completely dissatisfied with the documentation on the site.

You're welcome to participate in this open source project by sending PRs to improve the documentation, or the code.

**Comment by rjernst** [comment]
There is actually a TODO in the code just before that exception is thrown, stating that we should create the parent object dynamically. I agree it is a bug.
