### ISSUE TITLE
ESQL: DATE_DIFF doesn't compute year correctly

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#112482]
### Description

`DATE_DIFF("year", "2024-04-01"::date, "2023-12-30"::date)` returns 1 which is incorrect - it should return 0.
The problem is the implementation looks at the years instead of the whole interval:
`end.getYear() - start.getYear()` - should be `ChronoUnit.YEARS.between(start, end)`

**Comment by bpintea** [comment]
> The problem is the implementation looks at the years instead of the whole interval:
`end.getYear() - start.getYear()` - should be `ChronoUnit.YEARS.between(start, end)`

That's true, but: ESQL's DATE_DIFF was "ported" from SQL's implementation, which was [implemented](https://github.com/elastic/elasticsearch/pull/47920) following MS SQL's spec and is supposed to return 1 in this case -- see [datepart boundaries section](https://learn.microsoft.com/en-us/sql/t-sql/functions/datediff-transact-sql?view=sql-server-ver16#datepart-boundaries). 
So not technically a bug, but still unexpected. We can part with that spec and use some `ChronoUnit.YEARS.between(start, end)` or stick with it, but document the fact that this function follows MS's implementation.
