### ISSUE TITLE
Better exception if array passed to `term` query

### ISSUE THREAD

**Issue by spyk** [elastic/elasticsearch#11246]
Example: in the query "term" : ["doc1", "doc2", "doc3"] only "doc3" will be searched. 

I think an error message would be more preferable in case of array, as this is not immediately obvious and might take some time to track down why the query is not returning the expected values (as it happened to me). The user probably meant to run a "terms" query. 

Steps to reproduce:

<pre>
curl -XDELETE localhost:9200/test 
curl -XPUT localhost:9200/test/test/1 -d ' { "title": "doc1"} '
curl -XPUT localhost:9200/test/test/2 -d ' { "title": "doc2"} '
curl -XPUT localhost:9200/test/test/3 -d ' { "title": "doc3"} '

// Query will only return doc3
curl -XGET localhost:9200/test/test/_search -d  '{"query":{"term":{"title": ["doc1", "doc2", "doc3"]}}}'
</pre>

**Comment by spyk** [comment]
Oops I actually gave a wrong example query. When "term" is used as a query it will throw an ElasticsearchParseException, but when used as a filter it will then actually filter only the last element of the array.

So the test case becomes:
<pre>
// ElasticsearchParseException[Expected field name but got VALUE_STRING \"null\"]; }]"
curl -XGET localhost:9200/test/test/_search -d  '{"query":{"term":{"title": ["doc1", "doc2", "doc3"]}}}'

// Query will only return doc3
curl -XGET localhost:9200/test/test/_search -d  {"query":{"filtered":{"query":{"match_all":{}}, "filter":{"term":{"title":["doc1", "doc2", "doc3"]}}}}}

</pre>

**Comment by clintongormley** [comment]
Hi @spyk 

Thanks for reporting.  The `term`  filter has been removed in master (all filters are now queries), but I have a sneaking suspicion that parsing of the `term` query goes haywire after it encounters the array. (eg the exception from this query indicates some other problem): 

    GET /_search
    {
      "query": {
        "bool": {
          "should": [
            {
              "term": {
                "foo": [
                  "two",
                  "one"
                ]
              }
            },
            {
              "term": {
                "foo": [
                  "two",
                  "one"
                ]
              }
            }
          ]
        }
      }
    }


Either way, a better exception would be nice.
