### ISSUE TITLE
http.max_content_length setting ignored if above 2^31-1 bytes (~2gb), fix or document

### ISSUE THREAD

**Issue by SergeyTsalkov** [elastic/elasticsearch#11244]
When doing very large bulk requests, increasing http.max_content_length from the default of 100mb is essential. But if you set it above 2gb or so, it'll just silently ignore the setting and default back to 100mb.

If this can't be fixed, the docs at https://www.elastic.co/guide/en/elasticsearch/reference/1.5/modules-http.html should mention it.

**Comment by dakrone** [comment]
Looks like we do this on purpose for anything over `Integer.MAX_VALUE`, see: https://github.com/elastic/elasticsearch/blob/a40ba3be5aecc00e9b0b7ef79a0220d09159e327/src/main/java/org/elasticsearch/http/netty/NettyHttpServerTransport.java#L191-L195

Are you doing bulk inserts over 2gb in size? That is definitely higher than recommended.

I'll add a commit to mention this in the documentation.

**Comment by kun-zhou** [comment]
But it is very common to have hundreds of gigabytes of data that needs to be migrated to elastic search during the migration period, how should we approach such task? This is clearly a problem every developer needs to deal with.

**Comment by dadoonet** [comment]
Reduce the size of the bulk. Like send 1000 documents per bulk request for example.
