### ISSUE TITLE
Licensing change

### ISSUE THREAD

**Issue by PlavorSeol** [elastic/elasticsearch#112419]
According to [this blog post](https://www.elastic.co/blog/elasticsearch-is-open-source-again) and the [licensing FAQ page](https://www.elastic.co/pricing/faq/licensing), Elasticsearch is now available under AGPL v3 in addition to two existing licenses. However, current [`LICENSE.txt`](https://github.com/elastic/elasticsearch/blob/main/LICENSE.txt) does not reflect this licensing change.
Please update `LICENSE.txt` to reflect the licensing change as announced. Thank you.

**Comment by captn3m0** [comment]
https://www.elastic.co/pricing/faq/licensing#versions says:

> The 2024 change, where we added AGPLv3 alongside SSPL, is expected to take place before the 8.16 release is generally available.

**Comment by mark-vieira** [comment]
This has been completed.
