### ISSUE TITLE
ES|QL: add mv_values function

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#112445]
### Description

Like many other aggregate functions, `values` must have a sister function: `mv_values`. This is needed for properly handling [aggregations over constants work](https://github.com/elastic/elasticsearch/pull/112392).

**Comment by ivancea** [comment]
Looks like we already have [MV_DEDUPE](https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-functions-operators.html#esql-mv_dedupe), which apparently does the same
