### ISSUE TITLE
Add the ability to change index settings on snapshot restore

### ISSUE THREAD

**Issue by kbourgoin** [elastic/elasticsearch#11245]
Currently, there's no way to change things like index shard allocation settings when restoring from a snapshot.  You can rename the index, but you can't do anything to change its settings until the restore is underway.

If a cluster's settings have diverged significantly since the snapshot was taken, it may initially put the shards on the wrong nodes, leading to cluster instability until the restore has finished and the shards reallocate.

**Comment by dakrone** [comment]
@kbourgoin this feature does exist, see: #9285

Feel free to re-open if I have misinterpreted the issue.

**Comment by kbourgoin** [comment]
Yup. I searched the issues but somehow managed to completely miss that. Thanks!
