### ISSUE TITLE
Plugins should be able to add content types

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#11242]
We've talked about moving ```token_count``` into a plugin but I'm a bit stumped as to how I'd plug a new type into Elasticsearch with a plugin. It looks like DocumentMapperParser has the list hard coded. There are method to modify the list after the DocumentMapperParser is built but I can't see the right place to hook into to actually call them.

**Comment by rjernst** [comment]
@nik9000 This is already possible, see the mapper attachment plugin as an example:
https://github.com/elastic/elasticsearch-mapper-attachments/blob/master/src/main/java/org/elasticsearch/plugin/mapper/attachments/AttachmentsIndexModule.java

**Comment by nik9000** [comment]
Thanks. I hadn't remembered that plugin or that technique.
