### ISSUE TITLE
Lucene 10s RegExp class doesn't support COMPLEMENT, tilde operator any more

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#112453]
While integrating the current Lucene 10 snapshot I found that the Lucenes RegExp class has [removed the COMPLEMENT flag](https://issues.apache.org/jira/browse/LUCENE-10010) and also support for the tilde operator ('~') seems to have been dropped.

We probably still need to support the [current syntax flags](https://www.elastic.co/guide/en/elasticsearch/reference/current/regexp-syntax.html), so we need at least a placeholder for the flag in [our own RegExpFlag class](https://github.com/elastic/elasticsearch/commit/a371a6bf0a6eaea50f3b15808abf62c3ddf56d16). 

It appears that the removal of the tilde operator also has side-effects on e.g. automata used for index name matching etc..., e.g. we have test failures in "MetadataCreateIndexServiceTests.testValidateDotIndex" that I think are due to this change in behavior.

**Comment by ChrisHegarty** [comment]
I could be mistaken, but I believe that the complement syntax is being used in indices permission authorisation, e.g. https://github.com/elastic/elasticsearch/blob/f3bc281978c2d529e6579914cded6f033f317a37/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStore.java#L868

It's the likely cause of these failures:
```
Tests with failures:
 - org.elasticsearch.xpack.core.security.authz.store.ReservedRolesStoreTests.testPredefinedEditorRole
 - org.elasticsearch.xpack.core.security.authz.store.ReservedRolesStoreTests.testPredefinedViewerRole
 - org.elasticsearch.xpack.core.security.authz.store.ReservedRolesStoreTests.testKibanaSystemRole
```

**Comment by ChrisHegarty** [comment]
With the advise from @rmuir [here][1] we can likely implement complement regex support directly in Elasticsearch, if we need to, by using a combination of parsing for `~` and `Operations.complement`.

[1]: https://github.com/apache/lucene/pull/13732#issuecomment-2334327127

**Comment by ChrisHegarty** [comment]
The complement syntax has been restores in RegExp, but as a deprecated feature. Elasticsearch can update its regex parsing to use it.

**Comment by cbuescher** [comment]
I have a strong feeling that the `CompositeRolesStoreTests#testXPackUserCanAccessNonRestrictedIndices" failures we are seeing with Lucene 10 atm are also due to the changes in the "complement" functionality since "IndicesPermissions#checkResourcePrivileges" makes heavy use of a fairly complex automaton construction. I'm marking it as "AwaitsFix" for now to see if it is resolved once we see the incoming Lucene changes.

**Comment by cbuescher** [comment]
I started using the new [RegExp.DEPRECATED_COMPLEMENT](https://github.com/apache/lucene/pull/13739) with https://github.com/elastic/elasticsearch/commit/8cb58a7aae354b99621bd3769f6a98e81e05a11c for now.
We will need to check if that unblocks our failing tests and create a longer-term issue for dealing with this deprecated functionality before closing this though.

**Comment by javanna** [comment]
@cbuescher Can this be closed?

**Comment by cbuescher** [comment]
Yes, we pulled in the changes enabling us to use the deprecated complement logic. This will serve us while we are using Lucene 10. We have https://github.com/elastic/elasticsearch/issues/113465 to remind us to eventually remove this before a future next Lucene mayor version.
