### ISSUE TITLE
[CI] MlJobIT.testOutOfOrderData failure

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#112510]
### CI Link

https://gradle-enterprise.elastic.co/s/mezvx5upopijw/tests/task/:x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest/details/org.elasticsearch.xpack.ml.integration.MlJobIT/testOutOfOrderData?top-execution=1

### Repro line

./gradlew ":x-pack:plugin:ml:qa:native-multi-node-tests:javaRestTest" --tests "org.elasticsearch.xpack.ml.integration.MlJobIT.testOutOfOrderData" -Dtests.seed=F4A8192DF88C27DE -Dtests.locale=en-ID -Dtests.timezone=Asia/Magadan -Druntime.java=22

### Does it reproduce?

No

### Applicable branches

main

### Failure excerpt

```
java.lang.AssertionError: 2 active tasks found: |  
-- | --
  | cluster:admin/xpack/ml/job/close    W3KDMe6QS3aPwlEowj3XVA:30980 -                            transport  1725448119727 11:08:39 5.3m        127.0.0.1 javaRestTest-1 |  
  | cluster:admin/xpack/ml/job/close[n] W3KDMe6QS3aPwlEowj3XVA:30987 W3KDMe6QS3aPwlEowj3XVA:30980 transport  1725448119733 11:08:39 5.3m        127.0.0.1 javaRestTest-1 |  
  | expected:<0> but was:<2> |  

at org.elasticsearch.xpack.ml.integration.MlJobIT.clearMlState(MlJobIT.java:1002)	
```

Failed on a branch off main, but is unrelated to the branch changes.

**Comment by edsavage** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/114553
