### ISSUE TITLE
Tests: replacement test for missing elements in the diff-serialized cluster state

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#11257]
The commit fd1954d74f79311e203315d62cdc5a25c9b9faab invalidated the assumption that if two cluster states are equal they must have the same binary serialized length. As a result our smoke test for cluster state diffs started to fail periodically and was removed by the commit 42ad6771277d7778a088db57fe512bb9ce885356. Therefore now we don't really have a test for a partially implemented elements in cluster state. In other words if a cluster state element is added to writeTo() but we forget to add it to equalTo and we don't json serialize it, we might miss this fact in this test. We need to come up with a better way to catch situations like this.

**Comment by jpountz** [comment]
I have plans to remove block compression as part of https://github.com/elastic/elasticsearch/pull/11279 which means that at least we should again get the same length of serialized cluster states. So if it gets in maybe it would be easiest to add the assertion back instead of working on other ways to compare cluster states.

**Comment by jpountz** [comment]
@imotov Given recent changes we made to how we perform compression, this assertion should be less of an issue now. Should we just add it back?

**Comment by imotov** [comment]
Yes, it would be great to add it back! Thanks!

**Comment by clintongormley** [comment]
@jpountz @imotov  is this fixed by https://github.com/elastic/elasticsearch/pull/11279?

**Comment by imotov** [comment]
@clintongormley Hmm, I don't think we ever added it back.
