### ISSUE TITLE
Newly turned on replicas don't honor same_shard.host

### ISSUE THREAD

**Issue by wkoot** [elastic/elasticsearch#11250]
I have set `cluster.routing.allocation.same_shard.host: true`, in a cluster setup with two nodes per server.
This is working correctly, as I cannot relocate shards to hosts that already have a shard (primary or replica) of the same index on either node of that server.

However, when I turn on replicas for an index, I often see that two replica shards are being assigned to the same server (but to the two nodes).

ES Version: 1.4.5

**Comment by markwalkom** [comment]
Can you provide the output from _cat/shards?

**Comment by wkoot** [comment]
Scratch this, I misunderstood `same_shard.host` as "shards from the same index". :-)

**Comment by markwalkom** [comment]
All good :)
