### ISSUE TITLE
Dentry cache bloating on ES instances

### ISSUE THREAD

**Issue by vanga** [elastic/elasticsearch#11253]
I had created a post in elasticsearch google group earlier
https://groups.google.com/forum/#!topic/elasticsearch/c8_BLOtFVhs

ES version 1.5.2
Arch Linux on Amazon EC2
of the available 16 GB, 8 GB is heap (mlocked). Memory consumption is continuously increasing (225 MB per day).
Total no of documents is around 800k, 500 MB.

```
cat /proc/meminfo has
    Slab: 3424728 kB 
    SReclaimable: 3407256 kB

curl -XGET 'http://localhost:9200/_nodes/stats/jvm?pretty'

    "heap_used_in_bytes" : 5788779888,
              "heap_used_percent" : 67,
              "heap_committed_in_bytes" : 8555069440,

slabtop
 OBJS ACTIVE  USE OBJ SIZE  SLABS OBJ/SLAB CACHE SIZE NAME                  
17750313 17750313 100%    0.19K 845253       21   3381012K dentry
```
I understand that the dentry cache isn't a bad thing and kernel can take back this memory if needed, but the unusual rate of increase is a bit worrisome. 

I have straced elasticsearch for a couple of minutes
strace -fp PID -o file.txt

out of the 40k+ events recorded
2.2k + events have resulted in errors like this
https://gist.github.com/vanga/55ca296f737b3c1fb9a2
Is this normal?

I think this is the reason for the dentry bloating, though I am not sure if there is some thing wrong with my cluster or not. 

Update: Is ES/lucene making requests to non existent files? or is it making requests to files which were there, but not any more? If yes why would it request to files which are not there? is there some thing wrong with the cluster?

Update: I see that access to a file which resulted in ENOENT succeeds at later point in time(based on strace output). 
Thanks.

**Comment by clintongormley** [comment]
@rmuir do you have any thoughts about what is going on here?

**Comment by rmuir** [comment]
Not a problem.
