### ISSUE TITLE
Investigate runtime field not working with LogsDB

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#112564]
### Elasticsearch Version

8.15 and above

### Java Version

_bundled_

### OS Version

all

### Problem Description

Security reported an issue using runtime fields while testing LogsDB integration. We need to investigate the issue. Our expectation is that runtime fields should work with LogsDB (and Synthetic Source).

### Steps to Reproduce

@YulNaumenko or @yctercero  can you provide a link or steps to reproduce the issue you mentioned?

**Comment by yctercero** [comment]
@salvatore-campagna thanks for the follow up. 

@vitaliidm was the one that did the research here for the Detection Engine (thank you!). I've asked him to follow up with reproduction steps to help test.

**Comment by vitaliidm** [comment]
```JSON
// Create index and mappings

PUT basic_new_alerts_synthetic

PUT basic_new_alerts_synthetic/_mapping
{
  "_source": {
    "mode": "synthetic"
  },
  "properties": {
    "@timestamp": {
      "type": "date"
    },
    "agent": {
      "properties": {
        "name": {
          "type": "keyword"
        }
      }
    },
    "source": {
      "properties": {
        "ip": {
          "type": "ip"
        }
      }
    },
    "destination": {
      "properties": {
        "ip": {
          "type": "ip"
        },
        "port": {
          "type": "keyword"
        }
      }
    },
    "event": {
      "properties": {
        "ingested": {
          "type": "date"
        }
      }
    }
  }
}

// index doc
POST basic_new_alerts_synthetic/_doc
{
 "@timestamp": "2024-07-27T10:26:30.425Z",
 "source.ip": "127.0.0.1",
 "destination.ip": "127.0.0.2",
 "destination.port": 100,
 "agent.name": "test-1"
}

// run query
POST /basic_new_alerts_synthetic/_search?allow_no_indices=true&ignore_unavailable=true
{
  "runtime_mappings": {
    "_test_field": {
      "type": "keyword",
      "script": {
        "source": """  emit(params._source['agent.name'] + "_____" + doc['agent.name'].value );          """
      }
    }
  },
    "fields": [
    {
      "field": "*",
      "include_unmapped": true
    }]
}




```

Result:

```JSON

{
  "took": 25,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "basic_new_alerts_synthetic",
        "_id": "oR4Nw5EBluhaSO8eRM4P",
        "_score": 1,
        "_source": {
          "@timestamp": "2024-07-27T10:26:30.425Z",
          "agent": {
            "name": "test-1"
          },
          "destination": {
            "ip": "127.0.0.2",
            "port": "100"
          },
          "source": {
            "ip": "127.0.0.1"
          }
        },
        "fields": {
          "source.ip": [
            "127.0.0.1"
          ],
          "agent.name": [
            "test-1"
          ],
          "@timestamp": [
            "2024-07-27T10:26:30.425Z"
          ],
          "destination.port": [
            "100"
          ],
          "destination.ip": [
            "127.0.0.2"
          ],
          "_test_field": [
            "null_____test-1"
          ]
        }
      }
    ]
  }
}

```

**Comment by vitaliidm** [comment]
At the same time if I use this code, it will work as expected.

```JSON

POST /basic_new_alerts_synthetic/_search?allow_no_indices=true&ignore_unavailable=true
{
  "runtime_mappings": {
    "_test_field": {
      "type": "keyword",
      "script": {
        "source": """  emit(params._source['agent']['name'] + "_____" + doc['agent.name'].value );          """
      }
    }
  },
    "fields": [
    {
      "field": "*",
      "include_unmapped": true
    }]
}


```

Seems it happens, because, dot notation property is getting transformed into nested object

**Comment by salvatore-campagna** [comment]
> At the same time if I use this code, it will work as expected.
> 
> POST /basic_new_alerts_synthetic/_search?allow_no_indices=true&ignore_unavailable=true
> {
>   "runtime_mappings": {
>     "_test_field": {
>       "type": "keyword",
>       "script": {
>         "source": """  emit(params._source['agent']['name'] + "_____" + doc['agent.name'].value );          """
>       }
>     }
>   },
>     "fields": [
>     {
>       "field": "*",
>       "include_unmapped": true
>     }]
> }
> 
> Seems it happens, because, dot notation property is getting transformed into nested object

LogsDB will adopt `subobjects: auto` by default. Adopting it as default is still not done but it will be done soon. @vitaliidm may I ask you to test this scenario using `subobjects: auto` applied at the (root) mapping level?

**Comment by vitaliidm** [comment]
@salvatore-campagna 

I have changed mapping to this

```JSON

PUT basic_new_alerts_synthetic/_mapping
{
  "_source": {
    "mode": "synthetic"
  },
  "subobjects": "auto",
  "properties": {
    "@timestamp": {
      "type": "date"
    },
    "agent": {
      "properties": {
        "name": {
          "type": "keyword"
        }
      }
    },
    "source": {
      "properties": {
        "ip": {
          "type": "ip"
        }
      }
    },
    "destination": {
      "properties": {
        "ip": {
          "type": "ip"
        },
        "port": {
          "type": "keyword"
        }
      }
    },
    "event": {
      "properties": {
        "ingested": {
          "type": "date"
        }
      }
    }
  }
}

```

But when I tried to index document:

```JSON
POST basic_new_alerts_synthetic/_doc
{
 "@timestamp": "2024-07-27T10:26:30.425Z",
 "source.ip": "127.0.0.1",
 "destination.ip": "127.0.0.2",
 "destination.port": 100,
 "agent.name": "test-1"
}


```


Only, timestamp field got indexed

```JSON

# request

GET basic_new_alerts_synthetic/_search


# response

{
  "took": 15,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 2,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "basic_new_alerts_synthetic",
        "_id": "gzxy1pEBSOaAMaVahb64",
        "_score": 1,
        "_source": {
          "@timestamp": "2024-07-27T10:26:30.425Z"
        }
      },
      {
        "_index": "basic_new_alerts_synthetic",
        "_id": "oDx31pEBSOaAMaVahtJk",
        "_score": 1,
        "_source": {
          "@timestamp": "2024-07-27T10:26:30.425Z"
        }
      }
    ]
  }
}


```


So, runtime field has failed completely and returns error

```JSON
{
  "error": {
    "root_cause": [
      {
        "type": "script_exception",
        "reason": "runtime error",
        "script_stack": [
          """emit(params._source['agent']['name'] + "_____" + doc['agent.name'].value );          """,
          "                   ^---- HERE"
        ],
        "script": """  emit(params._source['agent']['name'] + "_____" + doc['agent.name'].value );          """,
        "lang": "painless",
        "position": {
          "offset": 21,
          "start": 2,
          "end": 87
        }
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "basic_new_alerts_synthetic",
        "node": "dZmxAPxHQn-B4pfgULW15g",
        "reason": {
          "type": "script_exception",
          "reason": "runtime error",
          "script_stack": [
            """emit(params._source['agent']['name'] + "_____" + doc['agent.name'].value );          """,
            "                   ^---- HERE"
          ],
          "script": """  emit(params._source['agent']['name'] + "_____" + doc['agent.name'].value );          """,
          "lang": "painless",
          "position": {
            "offset": 21,
            "start": 2,
            "end": 87
          },
          "caused_by": {
            "type": "null_pointer_exception",
            "reason": "cannot access method/field [normalizeIndex] from a null def reference"
          }
        }
      }
    ]
  },
  "status": 400
}
```

**Comment by kkrik-es** [comment]
Right `subobjects: auto` is not yet complete. 

Thanks @vitaliidm for checking this, we'll take it from here.

**Comment by felixbarny** [comment]
Could you refactor your scripts to use the [field API](https://www.elastic.co/guide/en/elasticsearch/reference/current/script-fields-api.html)? It works with both nested and dotted field names. But I'm not entirely sure if it already supports falling back to _source.

> The field API handles missing values, and will evolve to abstract access to _source and doc_values.

You could do something like `emit($('agent.name', null));`. It should use doc_values, if available or fall back to _source. Again, not sure if the fallback has been implemented already.

**Comment by kkrik-es** [comment]
I verified that the following work:

- `"source": """  emit(params._source.agent.name + "_____" + doc['agent.name'].value ); """ `
- `"source": """  emit(params._source['agent']['name'] + "_____" + doc['agent.name'].value );  """`
-  `"source": """  emit(field('agent.name').get(null) + "_____" + doc['agent.name'].value ); """`  
- `"source": """  emit($('agent.name', null) + "_____" + doc['agent.name'].value ); """` 

The one case that doesn't work is:

- `"source": """  emit(params._source['agent.name'] + "_____" + doc['agent.name'].value );  """`

Still looking for an easy fix wrt the latter, but we do have alternatives.

**Comment by kkrik-es** [comment]
This is due to how synthetic source gets reconstructed. In regular mode, `_source` matches exactly what was provided at indexing:

```
"_source": {
          "@timestamp": "2024-07-27T10:26:30.425Z",
          "source.ip": "127.0.0.1",
          "destination.ip": "127.0.0.2",
          "destination.port": 100,
          "agent.name": "test-1"
}
```

Synthetic source is modelled after the mapping structure, where field `name` is nested within object `agent`.

```
"_source": {
          "@timestamp": "2024-07-27T10:26:30.425Z",
          "agent": {
            "name": "test-1"
          },
          "destination": {
            "ip": "127.0.0.2",
            "port": "100"
          },
          "source": {
            "ip": "127.0.0.1"
          }
}
```

There's no easy way for this to change, but the problem will mostly go away once we start using `subobjects: auto` in LogsDB mode. In the meantime, updating the scripts to use one of the more robust forms should be more failsafe and efficient - synthesizing source is an expensive operation.

**Comment by kkrik-es** [comment]
I've added a note to documentation about this issue:

https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping-source-field.html#synthetic-source-modifications-field-names
