### ISSUE TITLE
Change default locale of date processors to english

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#112692]
The default locale of ingest date processors is ROOT, contrary to the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/date-processor.html). This means that the long-form day and month names are changing with the CLDR locale database, which could break a lot of pipelines.

The `en` locale is not changing, so we should change the default to `en` (`Locale.ENGLISH`).

Any existing date processors that use the ROOT locale should be modified to use `en` on upgrade to 8.16. The differences between root on compat and en on compat/cldr are small enough that it shouldn't affect users

**Comment by thecoop** [comment]
@rjernst does it also make sense to do this with date mappers? Default the locale to english rather than root?

**Comment by dakrone** [comment]
Link to where the `ROOT` locale is used:
https://github.com/elastic/elasticsearch/blob/4ce661cc48a2d2ea75092dc21dc507456b2acb42/modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/DateProcessor.java#L100
