### ISSUE TITLE
Pattern Analyzer pattern default does not seem to be '\W+'

### ISSUE THREAD

**Issue by aochsner** [elastic/elasticsearch#11268]
I'm a bit confused by the documentation.  It seems that if I want an analyzer that tokenizes across non-word ([^a-zA-Z_0-9]) then pattern analyzer would do it by default w/ the pattern defaulting to '\W+'  However this does not seem to be the case.  I recently realized that the Simple analyzer does not produce number tokens.

```
DELETE /test
PUT /test
{
  "settings": {
    "analysis": {
      "analyzer": {
        "nonword": {
          "type": "pattern",
          "pattern": "\\W+" 
        }
      }
    }
  }
}

GET /test/_analyze?analyzer=pattern&text=33
# does NOT return 33 as a token
GET /test/_analyze?analyzer=nonword&text=33
# does return 33 as a token
```

**Comment by clintongormley** [comment]
Hi @aochsner 

The pattern analyzer in Lucene had a "fast path" when the pattern was set to `.\W` which used (if I remember correctly) `isLetter()`.  This was clearly a bug.  The PatternAnalyzer class has now been reused, and the `pattern_analyzer` in the master branch of Elasticsearch is implemented using the PatternTokenizer, which doesn't suffer from this issue.
