### ISSUE TITLE
Provide an HTTP API url, which will output all available API urls

### ISSUE THREAD

**Issue by astropanic** [elastic/elasticsearch#11267]
Ruby on Rails, and many other software has a nice feature of automatically listing all available urls. When somebody new comes in to the project, runs ```rake routes```, he/she gets a list of urls the application understands.

Elasticsearch is moving fast, and the http API is growing. It would be nice to have some HTTP endpoint which will list all available routes for each of the Elasticsearch APIs (Cluster API health/status, Nodes info API, indices API, Search API and every new feature too).

Instead of chasing the changelog and reading the changed documentation, you call something like ```http://localhost:9200/_api_routes``` and you will get a nice list of all API urls currently supported by the given Elasticsearch version.

Since this list is autogenerated, there is no risk of going out of sync between the correct urls and the documentation.

**Comment by clintongormley** [comment]
Hi @astropanic 

I know it isn't an API, but do you know about the REST API spec? https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/api

It is manually maintained, but we use this spec when updating the officially supported clients.  It is also used by a community Swagger plugin: see https://github.com/timschlechter/swagger-for-elasticsearch

**Comment by astropanic** [comment]
Hi @clintongormley,

Was not aware of this nice summary.

Thanks!

**Comment by clintongormley** [comment]
Glad to help @astropanic - I think your need is already served, so I'm going to close this issue.
