### ISSUE TITLE
Using a query in Percolate should implicitly enable track_scores

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#11264]
When using a percolator "metadata query", the desired behavior is almost always to use the query for sorting.  But the user needs to know that `track_scores` *also* needs to be toggled.

It would be more user-friendly if using a query implicitly toggled `track_scores`.  The option should still remain if the user doesn't actually want it, but the default should switch to make it more convenient to use.

So instead of this:

```shell
curl -XGET 'localhost:9200/news/item/_percolate' -d '{
    "doc" : {
		...
	},
	"query" : {
		...
	},
	"track_scores" : true
}'
```

A user would just specify the query:

```shell
curl -XGET 'localhost:9200/news/item/_percolate' -d '{
    "doc" : {
		...
	},
	"query" : {
		...
	}
}'
```

And scores are tracked implicitly unless changed.

**Comment by clintongormley** [comment]
+1

**Comment by camilojd** [comment]
I'd like to work on this issue.

Should `trackScores` be set after `PercolatorService.parseRequest()` in `percolate()`, or as part of `parseRequest()` itself?
