### ISSUE TITLE
Scroll search should return 4xx for unavailable target nodes

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#112727]
```
Caused by: java.lang.IllegalStateException: node [3_LFPWqYQg6fn3G2nzS88w] is not available
\tat org.elasticsearch.server@8.16.0/org.elasticsearch.action.search.SearchScrollAsyncAction.run(SearchScrollAsyncAction.java:132)
\t... 164 more
"
```

**Comment by DaveCTurner** [comment]
I don't agree, I think `503 Service Unavailable` is correct in this case. The client did nothing wrong, the problem is server-side.

**Comment by dnhatn** [comment]
Thanks David. That's a good point—I agree.  I'm closing the issue, but if it comes up again, we should investigate whether it's a user issue (e.g., using an outdated scroll_id) or not.
