### ISSUE TITLE
ES|QL: make use of FunctionInfo.preview on the documentation side

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#112755]
### Description

Functions' `FunctionInfo` annotation has a `preview` component for functions that are still in preview/snapshot. But, this is not reflected in how the documentation is generated (if a function is in preview/snapshot-only mode it should be in the docs) nor is how this part is [exposed to Kibana](https://github.com/elastic/elasticsearch/pull/106782). We should look into:
- do we need a snapshot-only component to `FunctionInfo` or `preview()` is enough?
- integrate either `preview()` or a snapshot-only component in the above mentioned places in code.

**Comment by luigidellaquila** [comment]
Snapshot functions are not in the docs (neither in Kibana JSON docs), so I guess the only information we need is the "preview".

Separately, if we also want Kibana to receive Snapshot functions, we can add another information, but they are two distinct things.

**Comment by luigidellaquila** [comment]
@astefan @drewdaemon https://github.com/elastic/elasticsearch/pull/113544 is merged, so now we have both "preview" and "snapshot_only" info exposed.
Is there anything still missing? Should we close this issue?
