### ISSUE TITLE
_nodes/stats can return host filesystem stats when running in a container

### ISSUE THREAD

**Issue by masseyke** [elastic/elasticsearch#112743]
The `_nodes/stats` API uses the `/proc/diskstats` file to get disk usage stats. If elasticsearch is running in a container, and if it is configured so that `/proc/diskstats` reports stats for the underlying host rather than the container, then the `_nodes/stats` API will return disk usage stats for the host machine rather than the container.

**Comment by lukewhiting** [comment]
I have put a call out to the cloud team to get a better understanding of their containers and what the correct method would be to get the required stats. Awaiting a response.

**Comment by lukewhiting** [comment]
After consulting with sp-stateful, beats team and SRE, we haven't determined a way that it's possible for us, using stock Docker's provided interfaces, to get these statistics in a way that is scoped to the current container.

For that reason, I'm going to close this ticket as a "Won't fix" as we don't believe there's a way to resolve the underlying issue via ES code changes.

**Comment by lukewhiting** [comment]
Re-opening this issue as, although there's no code fix, a note in the documentation would be a good idea.
