### ISSUE TITLE
In 2.0 detect_noop for updates should be on by default

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#11282]
We added ```detect_noop``` to updates a while back but left it defaulting to ```false``` because there are use cases where you'd want it to be false. Things like where you want timestamps to be updated even if the document didn't change. Anyway, while 2.0 is making breaking changes is probably the time to switch from defaulting to ```false``` to ```true```. Its worth switching because performing noop updates _are_ expensive.

**Comment by jpountz** [comment]
It's not clear to me yet how common it is to run updates that don't change anything, but this no-op detection looks cheap to me, so +1 if it can help certain use-cases, I don't think it would hurt anyone.

**Comment by nik9000** [comment]
> It's not clear to me yet how common it is to run updates that don't change anything, but this no-op detection looks cheap to me, so +1 if it can help certain use-cases, I don't think it would hurt anyone.

Yeah - I don't know how common it is either. If it weren't cheap I wouldn't recommend it but it seems cheap and I think folks _expect_ noops to be cheap.

**Comment by aanuprab** [comment]
+1 it's logical for noop to be defaulted true. There are many use cases where messages get repeated with just an updated timestamp. Helps with es performance too.

**Comment by jpountz** [comment]
@aanuprab I'm confused: If a timestamp field is updated then noop detection will not help since the document changed?

**Comment by aanuprab** [comment]
@jpountz for example we have thousands of sensor data that continually stream in. Lots of times the actually sensor readings don't change. But it's just the timestamp on the sensor message header. The data is all that we store in ES, excluding the timestamp header. So it will be a noop. Hope it helps.

**Comment by jpountz** [comment]
OK, got it, the timestamp is not part of your documents.

**Comment by nik9000** [comment]
I'm putting together a patch for this. I noticed that you've been collecting the breaking changes in the migrate_2.0.asciidoc file so I'll have a note in there too.
