### ISSUE TITLE
Inference request task timeout should not be 503

### ISSUE THREAD

**Issue by ChrisHegarty** [elastic/elasticsearch#112828]
Timeouts on the inference service should not result in a 503. The rest suppressed logger reported this. 

Interestingly the timeout is 10s, while the default is not 30s ? 

```
"error.stack_trace": "org.elasticsearch.ElasticsearchTimeoutException: Request timed out waiting to be sent after [10s]
  at org.elasticsearch.inference@8.16.0/org.elasticsearch.xpack.inference.external.http.sender.RequestTask.lambda$getListener$2(RequestTask.java:67)
 at org.elasticsearch.server@8.16.0/org.elasticsearch.action.support.ListenerTimeouts$TimeoutableListener.run(ListenerTimeouts.java:102)
 at org.elasticsearch.server@8.16.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:924)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
 at java.base/java.lang.Thread.run(Thread.java:1570)\n",
```

**Comment by javanna** [comment]
I marked this Search relevance to check the question about the timeout and also because the exception is thrown in the inference related code. Given a cause is not provided, the status code will be 503, which is trappy. We have recently made a similar change in some of the search code and moved to 504 instead, see SearchTimeoutException. We had a bit of back and forth and decided not to use 4xx for search timeout errors, not sure what this specific timeout exception means though in this context.

**Comment by pmpailis** [comment]
IIUC one place where we set the timeout to 10s is the `semantic_text` rewriting 
```
InferenceAction.Request inferenceRequest = new InferenceAction.Request(
                TaskType.ANY,
                inferenceId,
                null,
                List.of(query),
                Map.of(),
                InputType.SEARCH,
                InferModelAction.Request.DEFAULT_TIMEOUT_FOR_API,
                false
            );
```
but I can't trace the call from just the logged message.  Maybe the ML/Inference team might be in a better position to take a look at this (and change the exception if needed)

**Comment by benwtrent** [comment]
This should be a 408. We should propagate a timeout as a timeout. Why we are throwing a 503 at all?


As for increasing the timeout for semantic text, etc. do we know why 10 seconds was chosen? Just a random number?

**Comment by tteofili** [comment]
@maxhniebergall would it be possible to change the HTTP status code to 408?
this is causing muted 5xx alerts in serverless unnecessarily (as it doesn't seem as an internal server error or anything like that).

**Comment by maxhniebergall** [comment]
@tteofili I've created a PR (linked above) which should switch to 408 status.
