### ISSUE TITLE
JAVA_HOME added to $DEFAULTS

### ISSUE THREAD

**Issue by jzinner** [elastic/elasticsearch#11291]
Both rpm and dpkg versions of init.d/elasticsearch
src/packaging/deb/init.d/elasticsearch
src/packaging/rpm/init.d/elasticsearch
reference that JAVA_HOME can be set in the DEFAULT file (/etc/default/elasticsearch on debian systems) -- which keeps process specific environment variables for elasticsearch

JAVA_HOME is not currently a #'ed option.

Not clear how the file deployed to /etc/default/elasticsearch is being generated, probably from src/packaging/common/env/elasticsearch?

**Comment by clintongormley** [comment]
Related to https://github.com/elastic/elasticsearch/pull/11288

Suggestion is to add `# JAVA_HOME=...` to https://github.com/elastic/elasticsearch/blob/master/src/packaging/common/env/elasticsearch
and to add docs to https://github.com/elastic/elasticsearch/blob/master/docs/reference/setup/as-a-service.asciidoc

**Comment by clintongormley** [comment]
@jzinner you want to send this as a PR?
