### ISSUE TITLE
RESTART_ON_UPGRADE doesn't work in the Debian package

### ISSUE THREAD

**Issue by mgedmin** [elastic/elasticsearch#11298]
The postinst script in [elasticsearch-1.3.9.deb](http://packages.elasticsearch.org/elasticsearch/1.3/debian/pool/main/e/elasticsearch/elasticsearch-1.3.9.deb) does this:
```sh
	# if $2 is set, this is an upgrade
	if ( [ -n $2 ] && [ "$RESTART_ON_UPGRADE" = "true" ] ) ; then
		startElasticsearch
```
where `startElasticsearch` is defined in the same script as
```sh
startElasticsearch() {
	if [ -x "/etc/init.d/elasticsearch" ]; then
		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
			invoke-rc.d elasticsearch start || true
		else
			/etc/init.d/elasticsearch start || true
		fi
	fi
}
```

Meanwhile the init script has the following bit:
```sh
case "$1" in
  start)
	checkJava

	if [ -n "$MAX_LOCKED_MEMORY" -a -z "$ES_HEAP_SIZE" ]; then
		log_failure_msg "MAX_LOCKED_MEMORY is set - ES_HEAP_SIZE must also be set"
		exit 1
	fi

	log_daemon_msg "Starting $DESC"

	pid=`pidofproc -p $PID_FILE elasticsearch`
	if [ -n "$pid" ] ; then
		log_begin_msg "Already running."
		log_end_msg 0
		exit 0
	fi
```

As you can see, even if you set RESTART_ON_UPGRADE=true in /etc/default/elasticsearch, this won't restart ElasticSearch if it's already running.

**Comment by clintongormley** [comment]
Hi @mgedmin 

Thanks for reporting.  It looks like this is already fixed in 1.6 by https://github.com/elastic/elasticsearch/pull/10595: https://github.com/elastic/elasticsearch/blob/1.x/src/packaging/common/scripts/postinst#L76
