### ISSUE TITLE
otel-data: metric rejected when attribute contains data type long

### ISSUE THREAD

**Issue by gregkalapos** [elastic/elasticsearch#112945]
### Elasticsearch Version

main

### Installed Plugins

otel-data

### Java Version

_bundled_

### OS Version

-

### Problem Description

Part of the OTel effort.

No user impact, this is disabled by default.

```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Failed to parse mapping: Field [time_series_dimension] requires that [index] and [doc_values] are true"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping: Field [time_series_dimension] requires that [index] and [doc_values] are true",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "Field [time_series_dimension] requires that [index] and [doc_values] are true"
    }
  },
  "status": 400
}
```

That happens because [some dynamic mappings with `match_mapping_type`](https://github.com/elastic/elasticsearch/blob/73e7b737ac17db1bc0f57891674e0b5efdf3d484/x-pack/plugin/core/template-resources/src/main/resources/metrics%40mappings.json#L6-L12) set `index: false` - while those fields are set as dimension and `index: false` can't be set for dimensions.

Ideas so far: we move back the new metrics added into https://github.com/elastic/elasticsearch/blob/73e7b737ac17db1bc0f57891674e0b5efdf3d484/x-pack/plugin/core/template-resources/src/main/resources/metrics%40mappings.json into the `otel-data` plugin and if anything left, we can duplicate those and then leaving out the ones that set `index: false`. 

### Steps to Reproduce

```
POST metrics-generic.otel-test/_doc
{
  "@timestamp": "2024-09-06T13:52:20.000Z",
  "attributes": {
    "process.pid": 17
  }
}
```

**Comment by pxsalehi** [comment]
@gregkalapos which team in ES does this relate to?

**Comment by gregkalapos** [comment]
@pxsalehi it'd be the [data management team](https://github.com/orgs/elastic/teams/es-data-management). But we take care of this within the OTel program and will ask them for review once there is a PR. That's why I assigned it to myself.

**Comment by gwbrown** [comment]
Thanks, I've tagged this for the data management team. We just need an area team label on the thing for administrative purposes, even if it's assigned to an individual.
