### ISSUE TITLE
_update on documents with nested array of embeddings randomly triggers errors at times

### ISSUE THREAD

**Issue by Danouchka** [elastic/elasticsearch#113084]
### Elasticsearch Version

8.15.1

### Java Version

_bundled_

### OS Version

Elastic Cloud GCP Belgium

### Problem Description

The _update API does not work on documents which have nested array of embeddings 
The _update API works on documents which have simple embeddings (ie not in an array) 
The _update test was every time on fields that had nothing to do with the embeddings 

### Steps to Reproduce

TEST1_knn_inference_cache_on_update_embeddings.json : Steps to show that _update on documents that have embeddings work
TEST2_knn_inference_cache_on_update_nested_embeddings.json : Steps to show that _update on documents that have nested array of embeddings does not work 

[TEST1_knn_inference_cache_on_update_embeddings.json](https://github.com/user-attachments/files/17040358/TEST1_knn_inference_cache_on_update_embeddings.json)

[TEST2_knn_inference_cache_on_update_nested_embeddings.json](https://github.com/user-attachments/files/17040359/TEST2_knn_inference_cache_on_update_nested_embeddings.json)

In TEST2, the error thrown is 

> {
  "error": {
    "root_cause": [
      {
        "type": "document_parsing_exception",
        "reason": "[1:8223] failed to parse: Field [questions.vector.predicted_value] of type [dense_vector] doesn't support indexing multiple values for the same field in the same document"
      }
    ],
    "type": "document_parsing_exception",
    "reason": "[1:8223] failed to parse: Field [questions.vector.predicted_value] of type [dense_vector] doesn't support indexing multiple values for the same field in the same document",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "Field [questions.vector.predicted_value] of type [dense_vector] doesn't support indexing multiple values for the same field in the same document"
    }
  },
  "status": 400
}

**Comment by Danouchka** [comment]
I have made several other tests, sometime in case of nested array of embeddings, the update works and other times, does not work

**Comment by benwtrent** [comment]
Pipelines work with `_source`, so I am wondering if there is something weird with dot collapsing :/

**Comment by benwtrent** [comment]
A couple of concerns to begin with:

 - The pipeline is being ran on the EXISTING source, meaning it will infer again. Which is likely not wanted. Even if inference is cached, you don't want to thrash your cache with document updates where the inference results won't change from what was previously stored. Consequently, this should be guarded with an `if` statement
 - The ingest pipeline will `append` to an existing field, meaning you will end up with double the vectors and passages I think. You also don't want this. So, you should either have the pipeline delete the results field before inference, or, again, protect with an IF.

As for the bug, it SEEMS like the pipeline is appending to a different field on update. I am not 100% why that is happening. It may not an actually different field but the way the pipeline updates the _source breaks something. Definitely need to debug.

**Comment by Danouchka** [comment]
When updates work, the inference cache is also leveraged. 
Inference cache is also leveraged when you index a new document (new _id ) with same questions

**Comment by benwtrent** [comment]
@Danouchka I understand the cache is leveraged. I am saying in a real scenario, you likely won't have previously indexed values sitting in cache as they would have been removed due to OTHER things being put in the cache.

You usually want the cache for queries as that is where you typically see duplicate strings.
