### ISSUE TITLE
Microsoft recommendations to improve security and resilience in the elasticsearch service

### ISSUE THREAD

**Issue by sairinraychoudhury** [elastic/elasticsearch#113145]
### Description

Hi Everyone
Needed advice from community members. We have deployed elasticsearch 8.5.1 using helm in Microsoft Azure Kubernetes Service (AKS). Also during an assessment of our platform towards improved security & resilience angle received below recommendations from Microsoft experts to be implemented.

1. Privileged containers should be avoided.
2. The root access inside the service container should be avoided.

We are not sure if above actions when implemented will have an impact on elasticsearch since we used default elasticsearch configs which are in helm chart for elasticsearch.

Could anyone from the community please help or guide us  on below queries?
1. Have you tried implementing custom configs apart from default configs provided?
2. Do you have a view of the impact by any means if we go ahead and implement this?
3. Are there any other general recommendation towards achieving this?

**Comment by AI-IshanBhatt** [comment]
Thanks very much for your interest in Elasticsearch.
This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.
There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
