### ISSUE TITLE
new hardware profile for memory-optimized machines

### ISSUE THREAD

**Issue by thequinto** [elastic/elasticsearch#113197]
### Description

The [current offerings](https://www.elastic.co/guide/en/cloud/current/ec-gcp-configuration-choose.html) do not have an option for applications that need more memory over storage / CPU.

**Comment by gbanasiak** [comment]
Thanks very much for your interest in Elasticsearch.

The issues in this repository are about bugs or enhancements in Elasticsearch code while the above enhancement request is about Elastic Cloud offering. I think the best way to signal memory-optimized profile need would be to open Elastic Cloud support ticket. I'm closing this issue.
