### ISSUE TITLE
Snapshot/Restore: restart of a master node during snapshot can lead to hanging snapshots

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#11314]
When a snapshot operation on a particular shard finishes, the data node where this shard resides sends an update shard status request to the master node to indicate that the operation on the shard is done. When the master node receives the command it queues cluster state update task and acknowledges the receipt of the command to the data node. 

The update snapshot shard status tasks have relatively low priority, so during cluster instability they tend to get stuck at the end of the queue. If the master node gets restarted before processing these tasks the information about the shards can be lost and the new master assumes that they are still in process while the data node thinks that these shards are already done. 

This might be the root cause of #9924 and #10564

**Comment by cxxr** [comment]
This has happened to us a few times in production. We've added "check to make sure a snapshot is not running" during any maintenance we perform to our ES cluster.
