### ISSUE TITLE
ES Cluster on Openstack keeps going down on large indexing jobs

### ISSUE THREAD

**Issue by sandywater** [elastic/elasticsearch#11318]
I am trying to index 17k (~20KB JSON) docs into ES, these are heavily nested docs.  It seems to be doing fine, then the cluster will always go down and the index job with fail.  Is there any special way I should configure the ES nodes so that it can handle the indexing?  Once the cluster goes 'red' I have to 'Soft Reboot' all the nodes and after a short while the cluster is back to being 'green' and the files that it indexed before it went down are available and queries are VERY fast (from cli, not Kibana, Kibana is VERY slow)

Is there anything I can do?  I am using elasticsearch-py to index, should I be using Logstash instead?  Do I need to put a cache or river in front of ES to trickle it in with data assurance?

Please help.
___
1 - m1.large load balancer node
3 - m1.large master nodes
20 - m1.large data nodes
 - multicast discovery
 - 10 shards
 - 1 repilca set
 - 1 index_name
 - 3 doc_types
 - 10G network between nodes

**Comment by GlenRSmith** [comment]
Are you bulk indexing?

**Comment by sandywater** [comment]
Yes, but only in ~15-25 doc chunks.  Should I up that amount?

Update: I blew away my ES cluster and just replaced it with a single node.  With 2VCPU, 16GB RAM and set the HEAP to 15g.  This happily indexed my JSON, with only a few connection time outs.  Now I am really confused.

**Comment by GlenRSmith** [comment]
You gave 15G to heap out of 16G? Are you configuring your AWS data nodes similarly? You should have your heap set to about half your available RAM.
m1.large is pretty small for the data nodes, memory-wise.
https://www.elastic.co/guide/en/elasticsearch/guide/current/hardware.html
Try to use at least m3.xlarge.
The size of the bulk requests is just something you'll have to experiment with. The sweet spot is going to depend on the complexity of your docs and their analysis (along with the various resource capacities/configs). Maybe try some smaller sample sets under "time" to see wether, for example, 100 bulk calls with 10 docs each, 50 with 20, 20 with 50, or 10 with 100 work out best.

In any case, I think soon enough you'll get the job basically performing, and further optimization discussion can be pursued via the forums (https://discuss.elastic.co/), IRC (#elasticsearch), or stackoverflow.

Good luck!

**Comment by markwalkom** [comment]
As @GlenRSmith mentioned - Please join us in #elasticsearch on Freenode or at https://discuss.elastic.co/ for troubleshooting help, we reserve Github for confirmed bugs and feature requests :)
