### ISSUE TITLE
[CI] CCSTelemetrySnapshotTests.testEqualsAndHashcode

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#113264]
### CI Link

https://gradle-enterprise.elastic.co/s/wfr3ymfwqe44k/tests/task/:server:test/details/org.elasticsearch.action.admin.cluster.stats.CCSTelemetrySnapshotTests/testEqualsAndHashcode?top-execution=1

### Repro line

./gradlew ":server:test" --tests "org.elasticsearch.action.admin.cluster.stats.CCSTelemetrySnapshotTests.testEqualsAndHashcode" -Dtests.seed=20E3FD82C7E52278 -Dtests.locale=ps -Dtests.timezone=Japan -Druntime.java=22	

### Does it reproduce?

Yes

### Applicable branches

main, 8.x

### Failure excerpt

Happened on a PR, but also reproduces on main.

**Comment by smalyshev** [comment]
```
  2> java.lang.AssertionError: CCSTelemetrySnapshot mutation should not be equal to original
```
Ugh looks like I messed up the mutator method somehow. Will fix.
