### ISSUE TITLE
Documentation typo in precision_step for byte number type

### ISSUE THREAD

**Issue by haizaar** [elastic/elasticsearch#11329]
`precision_step` paragraph of [Number](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-core-types.html#number) section of Core Types says that number of generated terms for `byte` number type is 2147483647. This looks certainly wrong unless I completely misunderstood byte number type.

**Comment by clintongormley** [comment]
@haizaar it says it *influences*  the number of terms produced :)  That rather arcane setting actually means that it creates only 1 term for bytes. Hopefully, with https://issues.apache.org/jira/browse/LUCENE-5879, we won't ever need to set that value in the future.

**Comment by haizaar** [comment]
I understand... but why not to change 2147483647 to 1 in the current docs?

**Comment by clintongormley** [comment]
@haizaar Because MAXINT is the actual setting, not 1.  It results in 1 byte being stored.
