### ISSUE TITLE
Error when renaming logs on UNC path

### ISSUE THREAD

**Issue by dobariya** [elastic/elasticsearch#11327]
I have configured elastic search with log path pointing to UNC path.
I Keep on receiving below error

log4j:ERROR Failed to rename [//elasticmaster1/logs/cluster1.log] to [[//elasticmaster1/logs/cluster1.log.2015-05-21] .

I even confirmed with my network admin if in case there is some permission related issue for the log path but this is not the case.

we are using virtual environment with operating system WINDOWS SERVER 2008 R2 STANDARD

Am I missing anything to configure?

One more wired thing noticed when above error is received  I see increase in memory.
For example before receiving the error, memory consumption was 11.9 GB by master and after receiving the error it increased to 12.1 GB.

**Comment by markwalkom** [comment]
It definitely sounds like a permissions error, are you 100% sure that the user you are running ES as has can rename.

Why are you logging to a UNC path anyway?

**Comment by dobariya** [comment]
yes i evened tried renaming the logs but it throws error saying this file is in use by other process which makes sense its used by ES it self.
When i shut down ES then am able to rename the logs manually on the UNC path.

We are storing logs on UNC path because we want all logs logged centrally on one path

**Comment by clintongormley** [comment]
@dobariya are you sure that each of your nodes is using a different file name for their logs?

**Comment by dobariya** [comment]
No all nodes are using same log path.
Yes this is the issue i can say.The first node started will lock the log file and others will not able to write.

**Comment by clintongormley** [comment]
OK great - so renaming the log file should fix that. thanks for letting us know

**Comment by dobariya** [comment]
can i say this will get fix in next version or do i have to do set up anything else

**Comment by clintongormley** [comment]
@dobariya this is not a bug - you just need to configure your nodes to use different log file names
