### ISSUE TITLE
Mapping should throw when field names with dots are specified

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#11337]
This was previously reported by @brwe on https://github.com/elastic/elasticsearch/issues/5972 but closed in favour of this comment https://github.com/elastic/elasticsearch/issues/6736#issuecomment-48451854 on #6736. That issue is now closed however so opening this again as a separate ticket so it won't be buried in the field name/path resolution refactor.

Consider the following mapping:

```json
DELETE index123
PUT index123
{
  "mappings": {
    "people": {
      "properties": {
        "o.x.y": {
          "type": "string",
          "analyzer": "standard"
        },
        "o.x.z": {
          "type": "string",
          "boost": 2
        }
      }
    }
  }
}

POST index123/people
{
  "o" : {
    "x" : {
      "y" : "this is analyzed",
      "z" : "2015-05-25T22:13:04+02:00"
    }
  }
}
```

When we do a `GET index123/_mapping` we get the following mapping for people:

```json
{
  "people": {
    "properties": {
      "o": {
        "properties": {
          "x": {
            "properties": {
              "y": {
                "type": "string"
              },
              "z": {
                "type": "date",
                "format": "dateOptionalTime"
              }
            }
          }
        }
      },
      "o.x.y": {
        "type": "string",
        "analyzer": "standard"
      },
      "o.x.z": {
        "type": "string",
        "boost": 2
      }
    }
  }
}
```

The string mapping for `o.x.z` is ignored and it becomes a `date`. 

Interestingly if we had mapped it as an `integer` e.g

```json
"o.x.z": {
    "type": "integer",
    "ignore_malformed": false
}
```

and indexed the following document

```json
{
  "o" : {
    "x" : {
      "y" : "this is analyzed",
      "z" : "asdasda"
    }
  }
}
```

we DO get a `NumberFormatException[For input string: \"asdasda\"]`. Something is out of sync here. 

Regardless of the field name/path resolution fixes it would be very handy if we'd get a mapping exception whenever we try to map a field with dots in it to prevent ambiguous mappings.

**Comment by rjernst** [comment]
Is this issue encompassed by #9059?

**Comment by Mpdreamz** [comment]
yes and no that ticket makes no mention of validating field names during mapping.

Terminology wise i think there is a distinction between field paths and field names. #9059 makes no clear distinction between the two and what to do when an api expect field names but gets a field path. 

NEST models these separately for instance, mapping taking PropertyName's and e.g the query dsl taking PropertyPath's.

**Comment by jpountz** [comment]
Fixed via https://github.com/elastic/elasticsearch/pull/12068
