### ISSUE TITLE
MySQL LIKE syntax

### ISSUE THREAD

**Issue by JulienPalard** [elastic/elasticsearch#11330]
Clearly, nobody cares, but there is an error here in the poor man MySQL full text search:

https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-matching.html

```
    WHERE text LIKE "*quick*"
      AND text LIKE "*brown*"
      AND text LIKE "*fox*" 
```
It's not `*` but `%` in MySQL.

**Comment by nik9000** [comment]
https://github.com/elastic/elasticsearch-definitive-guide/pull/360

**Comment by JulienPalard** [comment]
TIL the doc is on github. ^-^

**Comment by nik9000** [comment]
Some of the docs are in the main  elasticsearch project but the ones in the
"guide" are in that other repository. Those are the source of the paper
book.

**Comment by clintongormley** [comment]
Fixed by https://github.com/elastic/elasticsearch-definitive-guide/pull/360
