### ISSUE TITLE
URI Search fails with parse error when query string contains slash

### ISSUE THREAD

**Issue by marko-asplund** [elastic/elasticsearch#11343]
I get an error message when including a slash in query string.

The query is of the following form:
http://localhost:9200/twitter/tweet/_search?q=user:/kimchy

Here's the response from ES:
```
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=UTF-8
Content-Length: 763

{"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[BvVKBbulQdinJXUAXqBoaQ][twitter][0]: SearchParseException[[twitter][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"query_string\":{\"query\":\"user:/kimchy\",\"lowercase_expanded_terms\":true,\"analyze_wildcard\":false}}}]]]; nested: QueryParsingException[[twitter] Failed to parse query [user:/kimchy]]; nested: ParseException[Cannot parse 'user:/kimchy': Lexical error at line 1, column 33.  Encountered: <EOF> after : \"/kimchy\"]; nested: TokenMgrError[Lexical error at line 1, column 33.  Encountered: <EOF> after : \"/kimchy\"]; }]","status":400}
```

This occurs with ES v1.4.4.

**Comment by clintongormley** [comment]
Yes - it is part of the query string syntax: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_regular_expressions

**Comment by marko-asplund** [comment]
IMO, the documentation ambiguous about this. The document just says

> Regular expression patterns can be embedded in the query string by wrapping them in forward-slashes ("/")

But I don't think this statement implies that
* by including `/` characters the query gets automatically interpreted as a regexp or
* you can't use `/` characters in the query without being escaped

If this is considered a feature, I think the documentation should be changed to unambiguously state the syntax.

**Comment by clintongormley** [comment]
@marko-asplund The documentation provides a list of reserved characters, which includes `/`.  See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters

It says:

> If you need to use any of the characters which function as operators in your query itself (and not as operators), then you should escape them with a leading backslash.

I think that is pretty unambiguous but, if you disagree, please send a PR to improve the wording.

**Comment by marko-asplund** [comment]
@clintongormley Thanks for the pointer. Yes, the list of reserved characters looks pretty unambiguous on this issue.

**Comment by rponnuru0518** [comment]
I am having a similar issue with - and /. I get the parse exception for only these two symbols.
