### ISSUE TITLE
[ES|QL] remove `META FUNCTIONS`

### ISSUE THREAD

**Issue by drewdaemon** [elastic/elasticsearch#113412]
### Description

One of the ideas behind `META FUNCTIONS` was to provide Kibana with the metadata it needed to validate functions client-side. Kibana is using the function definitions generated from unit tests instead.

Is there any other reason to keep `META FUNCTIONS` around?

The `META` command is not documented so its removal is possibly a non-breaking change.

**Comment by craigtaverner** [comment]
I believe this was already address in https://github.com/elastic/elasticsearch/pull/113967
