### ISSUE TITLE
script_id not working on update

### ISSUE THREAD

**Issue by ben-av** [elastic/elasticsearch#11341]
Hey,
Trying to use a groovy script to increase a counter.
I saw there is a security issue, which disables dynamic scripting by default.
So I created a script like it's mentioned here(https://www.elastic.co/blog/running-groovy-scripts-without-dynamic-scripting#_how_to_continue_to_use_scripting)

With the following http request:
```
POST http://localhost:9200/index/type/123/_update
{
    "script_id" : "update_counters"   
}
```

And I'm getting nested: ScriptException[dynamic scripting for [groovy] disabled].
Is it not supported for Update API?

Thanks,
Ben

**Comment by clintongormley** [comment]
Hi @ben-av 

Indexed Groovy scripts are also disabled by default because anybody with access to the API could create one.  You either need to change settings to allow indexed scripts (and lock down your APIs to ensure that nobody else can create an indexed script) or use files to add your scripts to `config/scripts/`

**Comment by ben-av** [comment]
Hi Clinton,
Forgot to mention it is a script under config/scripts.
How do I send it in the request?(though script_id searches there as well)

**Comment by clintongormley** [comment]
@ben-av depends on the version you are using... the script parameters are in the process of being standardised across the codebase.

Assuming your script is called `config/scripts/test.groovy`, then:
* In 1.4, do: `{ "script": "test" }`
* In 1.5, do: `{ "script": { "file": "test" }}`

**Comment by ben-av** [comment]
Awesome, thanks @clintongormley . 
Might be good updating https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html, it's really confusing at the moment.
