### ISSUE TITLE
Query timeouts can terminate query execution prematurely

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#11346]
Using 1.5.2, we see the following in about 1% of executed queries:

![screen shot 2015-05-26 at 12 46 49 pm](https://cloud.githubusercontent.com/assets/212252/7809823/bb366492-03a5-11e5-9f50-342974b7e416.png)

Where metric is the `took` from the search response, timedOut is `timed_out` and queryTimeout is the timeout value as requested from Elasticsearch. As you can see, in over 90% of cases Elasticsearch will bail out way too early in the query execution. Only about 10% of queries have the queryTimeout value closely bounding the actual time it took the query to run.

This seems like a bug in the code making the decision to return prematurely. In many cases it seems like the query returned in full but the timed_out value was still set incorrectly.

I should also mention we are using `_primary_first` in this search request as our search preference.

**Comment by clintongormley** [comment]
@markharwood could you investigate this please?

**Comment by synhershko** [comment]
Hey, has there been any progress on this? ideally we'd want to trust ES in timing out queries, but given these finding we just can't and do crazy things client-side instead.

**Comment by markharwood** [comment]
The timer has a default resolution which can be configured using the setting `thread_pool.estimated_time_interval`. The error margins for measuring elapsed time are therefore subject to +/- errors of this value. The default setting is 200ms so the results are as expected for the given request.

**Comment by synhershko** [comment]
Ok thanks @markharwood , we will run tests again with this in mind.
