### ISSUE TITLE
`keyword` field failure in synthetic source with `flattened` field

### ISSUE THREAD

**Issue by salvatore-campagna** [elastic/elasticsearch#113538]
### Elasticsearch Version

all

### Java Version

_bundled_

### OS Version

all

### Problem Description

The `yaml` test includes a test where a `keyword` field is not reconstructed correctly in synthetic source.
It looks like the issue happens only when a `flattened` field is mapped too. I could not reproduce the
issue without the flattened field.

See there is a commented line in the test

```
  #TODO: synthetic source field reconstruction bug (TBD: add link to the issue here)
  #- match: { hits.hits.0._source.keyword: ["foo bar", "the quick brown fox"] }
```

### Steps to Reproduce

Just execute the yaml test uncommenting the line under `TODO`.

**Comment by lkts** [comment]
This is due to this line https://github.com/elastic/elasticsearch/blob/4f666310c7dff24d3f7704635a8faf01dcc140c7/server/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java#L1096. Both `fieldType().ignoreAbove` and `ignoreAboveDefault` are 10 in this case.

**Comment by lkts** [comment]
https://github.com/elastic/elasticsearch/blob/4f666310c7dff24d3f7704635a8faf01dcc140c7/x-pack/plugin/src/yamlRestTest/resources/rest-api-spec/test/wildcard/30_ignore_above_synthetic_source.yml#L52

this tests is not right, _source should include values that are ignored meaning `"jumps over the lazy dog"` should be present
