### ISSUE TITLE
Installing plugins in logstash 1.5.0 ?

### ISSUE THREAD

**Issue by JohanGregoire** [elastic/elasticsearch#11353]
Hello,

I'm trying to install a custom plugin into my logstash 1.5.0.
According to the documentation i should be able to do so with this command: bin/plugin install logstash-filter-cidr

However when I try it I get this:

root@elky:/usr/local/logstash-1.5.0# bin/plugin install logstash-filter-cidr

/usrlocal/logstash-1.5.0/vendor/jruby/lib/ruby/shared/rubygems/specification.rb:102 warning: Unrecognized time zone: localtime
io/console not supported; tty will not be manipulated
Validating logstash-filter-cidr
Plugin logstash-filter-cidr does not exist
ERROR: Installation aborted, verification failed for logstash-filter-cidr

We are behind a proxy and I set this environment to get through it:
http_proxy=http://www:8080

Can anyone help me or point me in the right direction so I can get this plugin installed?

Thanks

Regards,
Johan Gregoire

**Comment by clintongormley** [comment]
Hi @JohanGregoire 

Please could you open this issue on the logstash issues list instead? https://github.com/elastic/logstash/issues

thanks

**Comment by JohanGregoire** [comment]
Hello,

I saw it too late that this was for elasticsearch indeed. I've opened it over at logstash.
My apologies.

Regards,
Johan Gregoire
