### ISSUE TITLE
Match query with wildcard

### ISSUE THREAD

**Issue by spajak** [elastic/elasticsearch#11357]
There is ``match``, ``match_phrase`` and ``match_phrase_prefix`` query. Why there is no ``match_prefix`` query? I need something like ``match_phrase_prefix`` but ignoring token position (ie no phrase search).

**Comment by clintongormley** [comment]
Hi @spajak 

The `query_string` and `simple_query_string` queries have support for wildcards, and the `wildcard` `prefix`, and `regexp` term-level queries allow for wildcards or pattern matching.  However, using wildcards at query time is not best practice.  These can produce very heavy queries indeed.  A better performing solution is to use ngrams or edge ngrams at index time.  

For this reason, we prefer not to make wildcards a "first-class" citizen in the `match` family. (The `match_phrase_prefix` is also a heavy query, combining phrase and wildcards, but it was added early on before we had functionality like the completion suggester).

I recommend reading about Partial Matching in the Definitive Guide for an explanation of the available options: https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-matching.html

**Comment by spajak** [comment]
Hi @clintongormley 

Thank You for the answer. ngrams is not an option for my data, as its mix of numbers, (money) nominals, codes, names, short descriptions. And the results must be very accurate. In a better world it should be separated into individual fields.
With the help of analyze api, I've constructed what I need using ``term`` and ``prefix`` queries. Its complicated, but gives me what I need.

**Comment by clintongormley** [comment]
@spajak if you're using prefix queries, then edge-ngrams may be the right solution for you

**Comment by spajak** [comment]
@clintongormley ngrams would give me a lot of false positives. 

I've decided to use ``*`` for explicit prefix search. 
So for example I have a query like ``50 zł ande*``. ``ande*`` is extracted and passed to ``prefix`` query without ``*``. The rest of the string is passed to the analyzer. Analyzed tokens are then used to feed the ``term`` queries. All queries are the merged with ``bool: must``.

If ``match`` query supports wildcards, that would be perfect solution for me.

**Comment by clintongormley** [comment]
@spajak i refer to EDGE-ngrams, not ngrams.  So instead of using the prefix query you could use the match query on a field indexed as edge-ngrams, ie `a`, `an`, `and`, `ande`,...

**Comment by spajak** [comment]
@clintongormley I will give it a try. Thank You for help
