### ISSUE TITLE
[otel-data] Set apm internal aggregation data streams to hidden

### ISSUE THREAD

**Issue by gregkalapos** [elastic/elasticsearch#113551]
With an OTel collector based APM setup we have a span metrics connector that generates aggregated metrics for APM.

These metrics will be stored in specific data streams. 

Here is the setup for apm - for OTel we'll follow a similar patterns (with `otel` in the name):

![Image](https://github.com/user-attachments/assets/e9c55c8e-c83e-41e7-b7dd-885a35f82e58)

The 10 and 60 minutes data streams are set to hidden.

Task: do the same for OTel - make sure those data streams are set to hidden.

Will be implemented by the OTel program.

**Comment by felixbarny** [comment]
Closed by #114042
