### ISSUE TITLE
autosense in documentation should output curl syntax

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#11352]
I see you are switching from hardcoded curl syntax in the documentation to an ```autosense``` macro. The "open in sense" links have a bit of a smell of the nasty parts of open core but what really bugs me is that the documentation is no longer copy-and-paste-able into a console. It takes away a lot from the "easy to start" nature of Elasticsearch and feels like its trying to lock you in to a non-free tool in the process.

Even if sense were open source it'd be weird to tell people that they have to file bugs with curl but give them documentation in sense.

**Comment by bleskes** [comment]
I believe the plan is to use the more terse syntax of sense for display and offer both copy as curl  and open in sense functionality via buttons/link. @clintongormley will surely have something to say ...

**Comment by clintongormley** [comment]
As @bleskes says, Sense examples are much easier to read than the curl clutter, and sense (and marvel) is free for dev use.  It also means that people can open examples directly in a console where they can run them, as opposed to having to copy to a text file and paste one by one.

Plus there are a number of things on the go:

* sense will be able to translate multiple curl statements to sense syntax on paste
* sense will be able to copy multiple statements as curl
* sense will be able to run multiple curl statements in sequence

Once we have the second point implemented, we can look at adding a copy-as-curl button to the code blocks on the website.

> Even if sense were open source it'd be weird to tell people that they have to file bugs with curl but give them documentation in sense.

I much prefer bugs filed in sense syntax.  It's the major reason that I want the multiple-curl-to-sense functionality implemented :)

**Comment by nik9000** [comment]
> sense will be able to copy multiple statements as curl

I'm sold if you replace "sense" in this sentence with "the autosense macro documentation macro". A button that copies the example to your clipboard as curl would be useful.

> I much prefer bugs filed in sense syntax. It's the major reason that I want the multiple-curl-to-sense functionality implemented :)

The bugs I write often want the expressive power (lol) of bash. For loops and things.

**Comment by clintongormley** [comment]
Given Sense is now open source, closing this
