### ISSUE TITLE
When ES Master leader node get restarted, all sharding slice back to "unassigned" status

### ISSUE THREAD

**Issue by shanling2004** [elastic/elasticsearch#11356]
I'm using ES 1.5.2 with 3 master node + 3 data node via discovery.zen.ping.unicast mode.
I encounter issue is when restart master coordinator node's ES service, first report MasterNotDiscover, then when check _cluster/health URL, all sharding is back to unassigned.
unassigned_shards: 20

And it takes long time to mark shading to "Started" status when checking "_cat/shards" URL even I enhancement recovery concurrency.
 "cluster.routing.allocation.node_initial_primaries_recoveries":20,
 "cluster.routing.allocation.node_concurrent_recoveries":4,
 "indices.recovery.concurrent_streams":10,
 "indices.recovery.concurrent_small_file_streams":10,
 "indices.recovery.max_bytes_per_sec":"100mb"

Also enable gateway policy.
gateway:
  expected_nodes: 5
  recover_after_time: 10m

Is it normal behavior to rebuild index slice eachtime master leader node get restarted?

**Comment by clintongormley** [comment]
HI @shanling2004 

No it is not normal for shards to become unassigned when a master is restarted.  It sounds like you have a misconfiguration somewhere.  I suggest asking your question in the forum https://discuss.elastic.co/c/elasticsearch and providing your full config for both master and data nodes.
