### ISSUE TITLE
configuration with include directory

### ISSUE THREAD

**Issue by Grummfy** [elastic/elasticsearch#11362]
Hi,
I think it could be usefull to have an include dir like apache or nginx have for the configuration.
Why?
Simply because it's very usefull and easy to configure (add/replace a file instead of editing), easier to keep the default configuration or .... and adding specific configuration.

Thanks

**Comment by jtharpla** [comment]
This would be a big help for using configuration management with multiple plugins

**Comment by Grummfy** [comment]
Yes or if you have some small configuration file this allows you to assemble them for each server. Since apache do that, there is less conflict in upgrade but also easier maintenance (and this applies to every package that are cut in short part).

**Comment by clintongormley** [comment]
I think we should do this.  The syntax needs to be YAML compatible, so I'd suggest something like this:

Include `config/my_conf.yaml`:

    include: my_conf.yaml

Include `config/my_conf_1.yaml` and `config/my_conf_2.yaml`

    include: [ my_conf_1.yaml, my_conf_2.yaml ]

Absolute paths can be specified as well

**Comment by rmuir** [comment]
Why do we need it? Configuration is already crazy-overengineered today. Do we need to be able to re-read all these include'd configuration files at a later time after bootstrap ever (this is the case for the linked logging PR at the least)

If anything, I think we should simplify this stuff, to have even less features than it has today, and be simpler.

**Comment by dadoonet** [comment]
@rmuir I'm not sure if it's really needed but one of the use case I can think about is when it comes to S3 credentials. May be extracting this part from `elasticsearch.yml` and have different settings for DEV, QA, PROD might make sense? 

Not a big deal to manage though.

**Comment by rmuir** [comment]
Rather than add a lot of complicated functionality, or here about specific implementations, i would rather hear about what the actual missing use cases are, and we can think about what the best idea is.

And ideally whatever PR is doing that is removing more lines of code than it is adding, or it is suspect!

**Comment by Grummfy** [comment]
In my idea is more adding something similar to what exist in other known and successful product by adding an include dir so you can have 
/etc/elasticsearch/main_config_file.yml (or the name you want)
/etc/elasticsearch/conf.d/someotherconfig.yml
/etc/elasticsearch/conf.d/an-extra-config.yml

the *.yml  in conf.d will be loaded after the main_config_file (that have a key like config_dir : [ conf.d/, ... ]

The idea is not to add complexity but to reflect what other product have added that permit a lot of more flexibility. When you need to deal with an nginx server nobody want a simple file with all the configuration. Why we should have the same on elastic? What's the problem with subfile : it's not a so big deal to load and it's a lot easier to maintain.

**Comment by dadoonet** [comment]
I think that there is not so much thing to configure in Elasticsearch as you are often configure things using API.

My 2 cents on this.

**Comment by clintongormley** [comment]
We've had a long discussion about this in our FixItFriday session.  Our feeling is that we're trying to remove complication from the code base.  Having one way to do things just makes it simpler to understand and debug.  So for now, we're going to close this PR.  We may revisit this in the future if there is popular demand and the change makes life easier for the majority of users.

thanks anyway

**Comment by serac** [comment]
@rmuir, here's a use case: Shield credentials. Our LDAP directory requires a bind_password and I don't want it sitting in cleartext in our configuration-controlled elasticsearch.yml file. I would like to include a file that contains credentials exclusively that is either:

1. External to our configuration management
2. Encrypted (e.g. ansible vault) and configuration controlled

Some things that could work but are not ideal:
1. Encrypting elasticsearch.yml makes it harder to manage everything else in the file.
2. Injecting credentials via -Des.shield.authc.realms.ldap1.bind_password is not ideal since it leaks the password in ps output.

Externalizing credentials in a separate file is the best solution.

**Comment by jcape** [comment]
Sorry to come into this years later, but another use case for this is ansibilized first-time setup with x-pack user authentication.

The docs for doing X-Pack for user authentication say to do this:

 1. Install X-Pack
 2. Set the elastic password to something other than "changeme"
 3. "Set xpack.security.authc.accept_default_password to false."

The "usual" way to do this with a config management tool is:

 1. Write the common elasticsearch.yml configuration
 1. Start elasticsearch
 1. If the include file doesn't exist, run a script which
    1. Sets the user creds
    1. Updates the included file to disable default creds
 1. Restart elasticsearch via notify

In this case, the script bits (calling curl to set user creds, creating the "disable default creds" config snippet), and the notification to restart es are all orchestrated via the tool.

Included files are the easy way to support configurations where some are created via config-management template, some are created by scripts, and an external tool is making decisions about what to do when.

Doing all this in a single pass with ansible (or puppet) is difficult without either allowing optional configuration overlays or simply abandoning the tool and writing a shell script to walk through the setup.
