### ISSUE TITLE
add alias with 'tags' like 'xxx-xxx' not working?

### ISSUE THREAD

**Issue by peteryj** [elastic/elasticsearch#11366]
Hi experts,

My elasticsearch version is 1.3.7. 
When i add a new alias for an index, with following parameters:
"aliases":{
"aaaa_alias":{
"filter":{
"term":{
"tags":["aaa","bbb","ccc-ddd"]}}}}}

when i use kibana to query string 'tags:"<each tag above>"', it could show results with tags 'aaa', 'bbb', but no 'ccc-ddd' found.

I'm not sure if newer version could resolve this issue...

Could we have any restrictions for writing a tag?

Thanks in advance. :)

**Comment by clintongormley** [comment]
Hi @peteryj 

Please ask questions like these in the forum https://discuss.elastic.co/c/elasticsearch - this issues list is for bug fixes and feature requests. Hint: your `tags` field needs to be `not_analyzed`.
