### ISSUE TITLE
InternalDateHistogram.Bucket type is not visible

### ISSUE THREAD

**Issue by sim1st** [elastic/elasticsearch#11365]
I process a response which includes datehistogram ,

so I made List<InternalDateHistogram.Bucket> but, this type is not visible,

I think this happens because  'org.elasticsearch.search.aggregations.bucket.histogram.InternalDateHistogram' -> inner class Bucket is defined as a static class (not a public);

What should I do?

Can I modify class file in elasticsearch-1.4.1.jar?

**Comment by colings86** [comment]
@sim1st Why do you want to access InternalDateHistogram.Bucket? This is an internal class and not part of the Java API. DateHistogram.Bucket is the public interface you need to use to access the buckets of a date histogram [1]. You should use that.

[1] https://github.com/elastic/elasticsearch/blob/1.4/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogram.java

**Comment by sim1st** [comment]
Thank you very much!
