### ISSUE TITLE
ESQL: Pin `now` on all data nodes

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#113709]
### Description

ESQL currently uses `system.currentTimeMillis` for the query start time but it really should pin that at query start. See: https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/Configuration.java#L163

**Comment by nik9000** [comment]
> We already have a "[now](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/session/Configuration.java#L39)" in the configuration, I guess we can use it right away

Oh oops. I guess what I really mean is `absoluteStartedTimeInMillis` - but to be honest those should probably be the same. I'm not sure why our `now` is Zoned. But that's a thing for another day.

**Comment by bpintea** [comment]
@luigidellaquila should this be closed after #113777?

**Comment by luigidellaquila** [comment]
I think so, thanks @bpintea, closing
