### ISSUE TITLE
bulk updates with groovy script leads to long gc pauses

### ISSUE THREAD

**Issue by adler** [elastic/elasticsearch#11371]
We are doing bulk updates for hundreds of thousands of documents. We are using a groovy script to avoid the default merging of defunct data in one field. After 5-10 thousand documents, taking only a minute or so, we see garbage collection on the old generation. It's very predictable. The old generation gc repeats while we are loading updates each hour (about 10 secs of old gen gc time per minute). After about a day or so (a few million documents), the stop the world pauses become untenable - 20-40 seconds of old gen gc per minute.

When we discovered that we were using a script for the update, we removed it and throughput immediately improved 10x. The old gen gc virtually disappeared.

OpenJDK 1.7.0_65, elasticsearch-1.4.2-1
5 data nodes using the standard gc params 
"-Xms7g -Xmx7g -Xss256k -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC"
bulk batch size is 100 documents. Using 10 or 20 concurrent threads.

We are looking for alternative ways to get the same semantics without a script. In the meantime, I thought I would share our experience. If nothing else, it would be great to see a note about gc in the scripting section of the docs and a note about scripting in the gc section of the docs. Let me know if you'd like any more information.

**Comment by adler** [comment]
It would be nice if there was a way to avoid merging some parts of the document on partial updates without having to resort to using groovy. We are going to fetch the existing fields to the client and then update all defunct fields we find to have a value of 0. This extra round trip allows us to avoid the unwanted semantics of default merging and the performance problems caused by gc pausing.

**Comment by dakrone** [comment]
This should be helped in 5.0 with the move to Painless. Can you try it again and see if it improves?

**Comment by colings86** [comment]
No further feedback. Please reopen if you still see this issue in 5.x
