### ISSUE TITLE
search by polygon can not get all result, can someone tell me why?

### ISSUE THREAD

**Issue by lmqwudi** [elastic/elasticsearch#11386]
HI all, I am sorry ,but I can not open https://discuss.elastic.co/,so I have to ask the problem here。when I search by polygon I can not get all result, I just get a part of result. can sb tell me why？

when I debug the code, I find that when my geoPoint is [38.90340748200646, 121.52986586093903], but 
filterBuilder is {
  "geo_polygon" : {
    "location" : {
      "points" : [ [ 121.52991950511932, 38.90357029204773 ], [ 121.52986586093903, 38.90340748200646 ] ]
    }
  }
}

**Comment by clintongormley** [comment]
Hi @lmqwudi 

Why can't you open  https://discuss.elastic.co/ ? It works for me (including in incognito mode).

Either way, this list isn't for questions about how to use the API. Happy to help you access the forum if there is a problem.
