### ISSUE TITLE
SSO Plugin for ElasticSearch

### ISSUE THREAD

**Issue by janbernhardt** [elastic/elasticsearch#11387]
Hi I'm a Apache Fediz Developer and I would like to build an authentication plugin for elasticsearch which would make it possible to use SSO based on WS-Federation. Until now I could not find any documentation on how to extend the shield plugin, with custom authentication styles. I could only find information about the realm concept with basic authentication. I would like integrate my solution with the features from the shield plugin. Will this be possible, or do I need to reinvent the wheel to make it work?

**Comment by uboness** [comment]
Currently it's not possible to extend Shield. That said, Shield realm infrastructure was built with that in mind. We're working on exposing the appropriate extension points in Shield such that you'll be able to write and plug in you own realm implementation. This option will be available in the one of the next few releases (targeted to this year).

As a side note, if you have more questions around this topic or Shield in general, please post them on our dedicated shield forum at https://discuss.elastic.co/c/shield (elasticsearch repo is not the best place for it... so I'll be closing this issue)

thx!
