### ISSUE TITLE
When will Elastic address CVEs within the official elasticsearch containers?

### ISSUE THREAD

**Issue by specterops-avongluck** [elastic/elasticsearch#113892]
### Elasticsearch Version

v8.15.2

### Java Version

_bundled_

### OS Version

Linux container

### Problem Description

A large number of CVE's have been present within the elasticsearch / kibana containers for quite some time. When does Elastic plan on addressing these?

If there are no plans to address these (or they are false positives), could Elastic document why?

### Steps to Reproduce

1. Obtain any Elasticsearch or Kibana container.
2. Scan with any container CVE scanning tool. (AquaSec, https://www.docker.elastic.co/r/elasticsearch/elasticsearch:8.15.0-amd64, trivy)

**Comment by DaveCTurner** [comment]
Thanks for getting in touch @specterops-avongluck. 

Elastic's security reporting guidelines are available at https://www.elastic.co/community/security. Per those guidelines, all reports of potential security issues or vulnerabilities should be sent via email to [security@elastic.co](mailto:security@elastic.co).

We are unable to discuss potential issues of this nature here, so I am closing this issue.
