### ISSUE TITLE
REST Test blacklist should not use PathMatcher

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#11391]
Currently we use `PathMatcher` to perform matching on REST test names against a blacklist. This is an abuse of the the `PathMatcher` class since it is intended to be used with a `Path`, which is intended for file based operations as the javadocs state:
> An object that may be used to locate a file in a file system.

While it may work right now, there are always special cases at play like #11389, which makes this brittle. We should think about another way to do the matching for blacklists. At the same time, there is another issue which is that we specify the blacklist as a comma separated list, but we also have tests with a comma in their name so this is problematic. A workaround exists, which is to use a glob pattern but this can blacklist more tests than necessary.

**Comment by javanna** [comment]
Seems like there is not much to discuss here, thanks Jay for raising it, it's a good point. I originally used the PathMatcher because I thought it was ok, didn't see all those issues coming to be honest and I didn't want to write my own path matcher at the time. Marking adoptme.

**Comment by danielmitterdorfer** [comment]
I had a look at it and I see basically these options:

1. We can implement our own globbing from scratch
2. We can use a copy of `com.google.common.jimfs.GlobToRegex` (licensed under ASL 2.0) and base our implementation on that, which would then match internally using a regex.
3. We can change the format of the property `tests.rest.blacklist` and allow only regexes

In case 1, I'm not sure whether we really need the whole set of globbing options or a subset is sufficient, I frown upon copying (case 2) and case 3 is obviously breaking and a tad more quirky to use. What do you think @javanna?

**Comment by danielmitterdorfer** [comment]
Just a quick update: After some discussion with different developers, we've decided to check with @jaymode when he's back again. I'll assign myself for now.

**Comment by jaymode** [comment]
thanks for taking this on. I think just supporting `*` would be enough as I think that's all we use now and hopefully we can also add a way to escape a `,` in the test names so we don't have to skip more tests than necessary
