### ISSUE TITLE
Suggest weights are silently bucketed

### ISSUE THREAD

**Issue by malthe** [elastic/elasticsearch#11392]
The positive integer ``weight`` provided to the ``completion`` type to allow custom results ranking seems to be converted to an approximate score, apparently using some bucket scheme.

The resulting scores are unevenly distributed which further skews the picture: 
```
weight 2144409647 => score 2144409600
weight 2144397647 => score 2144397700
```
The ordering of suggestions depends first on the score, second on alphabetical sorting. Hence, if two different weights are conflated into a single score, then alphabetical sorting takes over which is often not what you want.

The correct behavior is to use the assigned weight *as is*.

Note that a workaround seems to be to manually space out weights values by some constant, e.g. 1000.

**Comment by clintongormley** [comment]
what happens in the new suggester @areek?

**Comment by areek** [comment]
Hi @malthe,
Thanks for reporting this.
Internally, the integer `weight` is returned as a `float`. In Java, a `float` can represent values <= `2^23` without losing precision. Both `2144409647` and `2144397647` are > `2^23`, hence the loss in precision. You should not see the loss of precision if you use `weight` <= `2^23`.
One way to avoid this is to return `weight` as a `double` instead, I will open an issue for this.

@clintongormley this is not related to completion suggester, but how the scores are handled after.

**Comment by malthe** [comment]
@areek ah that's what's happening. Thanks for clarifying – *and fixing*.
