### ISSUE TITLE
Illegal state log entries

### ISSUE THREAD

**Issue by faxm0dem** [elastic/elasticsearch#11395]
I'm seeing this log message for random indices several times a day in my cluster:

```
[2015-05-28 15:19:49,092][WARN ][index.shard              ] [mynode] [index-foo][2] suspect illegal state: trying to move shard from primary mode to replica mode
```

Also, maybe unrelated, the cluster is relocating shards all the time, never stopping.

Other than that all seems normal in the cluster.

**Comment by s1monw** [comment]
what version of es are you running? can we have more info about your logs?

**Comment by faxm0dem** [comment]
1.5.2 on EL6 other close log entries only show a few unrelated (other index) parse failures

**Comment by bleskes** [comment]
Is there anything interesting in the master node logs? any idea why shards will be continuously relocated?

can you also check that all nodes report the same node via `GET _cat/master` ?

**Comment by faxm0dem** [comment]
* all 9 nodes see the same master
* nothing exciting in the master's logfile mainly:
  * `update_mapping [...] (dynamic)`
  * `creating index`
  * `now throttling indexing`
* I tried reindexing the indices that seem to have the most `suspect illegal state` messages. Let's see what happens

**Comment by faxm0dem** [comment]
## Update

I do not have any `suspect illegal state` messages anymore since reindexing all indices that used to trigger those in the past.
I guess you can close this if you like, but my feeling is this issue will pop up again, not necessarily on my account.

**Comment by clintongormley** [comment]
thanks for letting us know @faxm0dem - closing for now
