### ISSUE TITLE
[CI] MixedClusterClientYamlTestSuiteIT test {p0=indices.create/20_synthetic_source/object array in object with dynamic override} failing

### ISSUE THREAD

**Issue by Mikep86** [elastic/elasticsearch#114043]
### CI Link

https://gradle-enterprise.elastic.co/s/jgxvjoqov6v2u/tests/task/:qa:mixed-cluster:v8.15.3%23mixedClusterTest/details/org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT/test%20%7Bp0=indices.create%2F20_synthetic_source%2Fobject%20array%20in%20object%20with%20dynamic%20override%7D?page=eyJvdXRwdXQiOnsiMCI6NX19&top-execution=1

### Repro line

./gradlew ":qa:mixed-cluster:v8.15.3#mixedClusterTest" -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=indices.create/20_synthetic_source/object array in object with dynamic override}" -Dtests.seed=7202967CB7CD574C -Dtests.bwc=true -Dtests.locale=zh-HK -Dtests.timezone=America/Cuiaba -Druntime.java=22

### Does it reproduce?

Yes

### Applicable branches

8.x

### Failure excerpt

java.lang.RuntimeException: Failure at [indices.create/20_synthetic_source:569]: element was a list, but [some_int] was not numeric

**Comment by benwtrent** [comment]
I am not sure if we are missing a fix in 8x, or if the original failure was never fully addressed. but this will be muted again on 8x. Related to: https://github.com/elastic/elasticsearch/issues/113966

**Comment by kkrik-es** [comment]
Yeah we may've missed a node feature for this one..

**Comment by benwtrent** [comment]
@Mikep86 was running into this continually on his PRs even when updating to latest 8x. I will let me provide additional info. Maybe it was an over eager mute.

**Comment by lkts** [comment]
This fails because `"mapper.track_ignored_source` feature exists in 8.15 and behavior changed in 8.16 (it's a preview feature so the change itself is okay). We need to hide the test behind a feature that only exists in 8.16.
