### ISSUE TITLE
Problem occured with same name of cluster in different machines

### ISSUE THREAD

**Issue by mehmetozerr** [elastic/elasticsearch#11402]
Hello,

I have a weird issue today and it gives me lots of problem. I had two cluster different but unfortunatelly I gave them the same names by mistake; 

lets say;
test_cluster

- both cluster have had totaly different machines ( it was working well its been one month)
- today I added a machine in one of the cluster and I saw that all the machines were in the same cluster physically (it was not the case before adding the machine)
- I have chacked the unicast list; there were no machine in common

So someone can explain me how I had this problem and how I can seperate them ? 

Thank you

**Comment by clintongormley** [comment]
@mehmetozerr you should give them different cluster names and disable multicast (this is how the two clusters discovered each other)
