### ISSUE TITLE
Allow plugins to specify dependent plugins

### ISSUE THREAD

**Issue by ycombinator** [elastic/elasticsearch#11404]
Example use case: Installing the watcher plugin should automatically install the license plugin as well. At the very least, trying to install the watcher plugin should check if the license plugin is not installed and abort installation with an actionable error message.

Currently this check is performed at node startup but it would be even better UX if we could fail earlier.

**Comment by dadoonet** [comment]
IIRC @tlrx has something pending about it. The plugin manager has been refactored in another PR which needs to be pulled in.

**Comment by clintongormley** [comment]
Closing - see https://github.com/elastic/elasticsearch/issues/13823#issuecomment-143901597
