### ISSUE TITLE
SearchContext not released when search request is rejected

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#11400]
It seams that SearchContexts are not released in case the search requests fails due to a rejection (thread pool queue full). I have a test that fails each time here: https://github.com/brwe/elasticsearch/blob/open-search-contexts/src/test/java/org/elasticsearch/search/SearchWithRejectionsTests.java

**Comment by s1monw** [comment]
I think we should fix this for 1.6 if we can though

**Comment by brwe** [comment]
This only happens with dfs queries. I made a pull request to fix it here: https://github.com/elastic/elasticsearch/pull/11434
