### ISSUE TITLE
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []

### ISSUE THREAD

**Issue by premanandchandrasekar** [elastic/elasticsearch#11418]
I'm using version 1.9.4 , am getting the same error when i try to index.

I checked with cluster.name in elasticsearch.yml, which i'm providing the same. I checked in online i can't find any solution ..

**Comment by dadoonet** [comment]
This version does not exist.
You should open a thread on https://discuss.elastic.co/c/elasticsearch so we can help you there. Also provide details about what you did.
This space is reserved for bug reports which is I'm almost sure not the case here.

Closing for now. Let me know if you think it's really an issue in the code base.
