### ISSUE TITLE
Guidance Needed for Setting Up ELK Stack with NGINX Ingress and SSL in Kubernetes

### ISSUE THREAD

**Issue by anjanaprasd** [elastic/elasticsearch#114127]
Hi Team,
First, I'm new to ELK stack.

I am currently setting up the ELK stack in a Kubernetes cluster and have deployed it using a Helm chart. I have enabled ingress resources for both the Elasticsearch (ES) and Kibana services.

However, I am encountering a 502 error when I attempt to access the ES service via a curl command, despite the backend services functioning correctly when tested using port-forwarding.

I can successfully log in to the Kibana dashboard using port forwarding, both with a single Kibana pod and multiple pods. When the pod count is set to one, the ingress works fine.  

When pod count is more than 1, I am encountering an issue when trying to log in to the Kibana dashboard via a browser. After entering my credentials, I am repeatedly redirected back to the login page.

It appears there may be an issue with my ingress resource configuration. Could someone please assist me with this?

annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "elk"
    nginx.ingress.kubernetes.io/proxy-redirect-from: "/"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "/app/kibana"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/cookie-samesite: "None"
    nginx.ingress.kubernetes.io/cookie-secure: "true"

I appreciate your guidance and advice.

**Comment by pxsalehi** [comment]
@anjanaprasd could you please open your issue on the ECK repo under https://github.com/elastic/cloud-on-k8s?
