### ISSUE TITLE
[ES|QL] CCS index with quotes fails

### ISSUE THREAD

**Issue by stratoula** [elastic/elasticsearch#114201]
### Elasticsearch Version

8.16

### Java Version

_bundled_

### OS Version

Darwin Kernel Version 22.6.0

### Problem Description

When we are wrapping a CCS index with quotes it fails with "Invalid index name: <index> must not contain :"

![Image](https://github.com/user-attachments/assets/360a2e1a-ac37-484e-b905-67d3573cf665)

Wrapping a normal index with quotes works fine so this is a weird behavior. Also the error is confusing. CCS indexes are described with :

### Steps to Reproduce

1. Ensure that you have a CCS index
2. Use the esql api to query this index with quotes : `from "remote_cluster:index"`

**Comment by alex-spies** [comment]
@fang-xing-esql , this looks like it's related to https://github.com/elastic/elasticsearch/pull/112081; do you wanna take a look?

**Comment by bpintea** [comment]
From the [FROM docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/esql-commands.html#esql-from): 

```
Use enclosing double quotes (") or three enclosing double quotes (""") to escape index names that contain special characters:

FROM "this=that", """this[that"""
```

Whatever is in quotes in the FROM is considered an index pattern _only_ (i.e. excluding a remote cluster name). If one needs to quote the name of the index pattern, but use a remote cluster name, that would look like `FROM remoteCluster:"this=that"`.

So I think the failure is valid and correct.

**Comment by stratoula** [comment]
Hey Bogdan. I think that this was working before and I personally find this `FROM remoteCluster:"this=that"` a very confusing syntax 🤷‍♀

**Comment by bpintea** [comment]
> I think that this was working before

I see. That probably happened unintentional, though given that `:` can't be part of an index name, supporting it intentionally should be possible.
