### ISSUE TITLE
[CI] SearchSlowLogTests failures on CI

### ISSUE THREAD

**Issue by thecoop** [elastic/elasticsearch#114296]
### CI Link

https://gradle-enterprise.elastic.co/s/k6rcc5kvi4ke2/tests/task/:server:test/details/org.elasticsearch.index.SearchSlowLogTests/testLevelPrecedence?top-execution=1

### Repro line

./gradlew ":server:test" --tests "org.elasticsearch.index.SearchSlowLogTests" -Dtests.seed=56C15E1C1861AB28 -Dtests.locale=eo -Dtests.timezone=Europe/Kiev -Druntime.java=22	

### Does it reproduce?

No

### Applicable branches

main, 8.x

### Failure excerpt

More details in https://github.com/elastic/elasticsearch/pull/112183#issuecomment-2398021133

`SearchSlowLogTests.testTwoLoggersDifferentLevel` and `SearchSlowLogTests.testLevelPrecedence` fail intermittently.

There's a race between two test suites, when they both run in the same JVM.

**Comment by thecoop** [comment]
@rjernst the easiest thing might be to revert #112183 whilst we dig into this more?

**Comment by thecoop** [comment]
Both tests have been muted

**Comment by kkrik-es** [comment]
This keeps failing in 8.x: https://gradle-enterprise.elastic.co/s/rrrzy3q3h3kv6

**Comment by bcully** [comment]
https://github.com/elastic/elasticsearch/pull/114344 should fix this. I'll tag it for backport.
