### ISSUE TITLE
Synthetic Source Issue with Text Fields

### ISSUE THREAD

**Issue by gpop63** [elastic/elasticsearch#114235]
ES version: `8.15.2`

Tried installing an integration and its mappings via fleet.

An `illegal_argument_exception` occurs when trying to use `source_mode: synthetic` with fields of type `text`. This happens because `text` fields don't support synthetic source unless they are stored or have a keyword sub-field with doc_values.

```
illegal_argument_exception Root causes: illegal_argument_exception: field [panw.system.thermal.description] of type [text] doesn't support synthetic source unless it is stored or has a sub-field of type [keyword] with doc values or stored and without a normalizer
```

**Comment by tommyers-elastic** [comment]
it looks like this should have been resolved via https://github.com/elastic/elasticsearch/pull/106338, was something missed there?

**Comment by lkts** [comment]
In 8.17 this will work if using `index.mapping.source.mode` setting.
