### ISSUE TITLE
Logging Provider Selection

### ISSUE THREAD

**Issue by cleemansen** [elastic/elasticsearch#11423]
Hi,

Elasticsearch tries to [determine which logging "backend"](https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/common/logging/ESLoggerFactory.java#L33) is available on the classpath.

In my scenario I use the [slf4j-log4j-bridge](https://logging.apache.org/log4j/log4j-2.2/log4j-1.2-api/index.html). The comment at [L36](https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/common/logging/ESLoggerFactory.java#L36) indicates that in this scenario a NoSuchMethod should be thrown and the Slf4jESLoggerFactory should be used (if slf4j is present).

But the slf4j-log4j-bridge accepts the setLevel(org.apache.log4j.Level). See [org.apache.log4j.Logger](https://git-wip-us.apache.org/repos/asf?p=logging-log4j2.git;a=blob;f=log4j-1.2-api/src/main/java/org/apache/log4j/Logger.java;h=2e643a17c1de79fb56a49710797f046e162de289;hb=HEAD#l26) and [org.apache.log4j.Category](https://git-wip-us.apache.org/repos/asf?p=logging-log4j2.git;a=blob;f=log4j-1.2-api/src/main/java/org/apache/log4j/Category.java;h=25408e79f7ecb61176333df6cbcd9aced3d448ee;hb=HEAD#l190).

**Comment by spinscale** [comment]
is there another method you know that we could use? Havent looked at slf4j for some time. Hints appreciated.

**Comment by cleemansen** [comment]
No - I also don't know another method.
I'm not that java logging expert, but I looked at other 'common' frameworks and their selection process:

This is the most common order:
1. check weather log4j2 is present
2. check weather log4j1 is present
3. check weather slf4j is present
4. use jdk logging

- JBoss: [code](https://github.com/jboss-logging/jboss-logging/blob/master/src/main/java/org/jboss/logging/LoggerProviders.java), [dokumentation](http://docs.jboss.org/hibernate/orm/4.3/topical/html/logging/Logging.html)
- resteasy: [code](https://github.com/resteasy/Resteasy/blob/master/jaxrs/resteasy-jaxrs/src/main/java/org/jboss/resteasy/logging/Logger.java#L71)
- apache commons logging: [code](http://svn.apache.org/repos/asf/commons/proper/logging/trunk/src/main/java/org/apache/commons/logging/impl/LogFactoryImpl.java)

I hope this helps to make a decision!

**Comment by jasontedor** [comment]
As of #16703, we only support log4j for the logging back end.
