### ISSUE TITLE
TEXT fields should be converted to KEYWORD by any function that changes their values

### ISSUE THREAD

**Issue by craigtaverner** [elastic/elasticsearch#114333]
In ES|QL, many functions can take both KEYWORD and TEXT as input parameters, and change their values to strings. This change destroys the meaning of any analyzer associated with the original TEXT, and so the output should always be KEYWORD. But several functions mistakenly return TEXT (ie. return their input data type).

Functions known to have this issue:
* Explicitly returning `field.dataType`
  * ToUpper
  * ToLower
* Implicitly as a result of extending `UnaryScalarFunction`:
  * LTrim
  * RTrim
  * Trim
  * Reverse

Other functions that take TEXT but already are fixed to only return KEYWORD:
* ToString
* FromBase64
* ToBase64
* Replace
* Right
* Left

**Comment by drewdaemon** [comment]
This may also apply to `REVERSE`

**Comment by nik9000** [comment]
I think we should `assert` in the tests that no function ever spits out `text`. At some point we'll make an ANALYZE function that does and we can hack around the assertion for that one function. Otherwise they never should.
