### ISSUE TITLE
SearchSlowLogTests failing in CI

### ISSUE THREAD

**Issue by Mikep86** [elastic/elasticsearch#114359]
### CI Link

https://gradle-enterprise.elastic.co/s/66vootmsanz4o/tests/overview

### Repro line

./gradlew ":server:test" --tests "org.elasticsearch.index.SearchSlowLogTests.testTwoLoggersDifferentLevel" -Dtests.seed=5D0E74B4A7055BC8 -Dtests.locale=mas-TZ -Dtests.timezone=Asia/Rangoon -Druntime.java=22

### Does it reproduce?

Yes

### Applicable branches

8.x

### Failure excerpt

java.lang.AssertionError: (No message provided)

at org.junit.Assert.fail(Assert.java:87) 
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713) 
at org.junit.Assert.assertNotNull(Assert.java:723) |  
at org.elasticsearch.index.SearchSlowLogTests.testTwoLoggersDifferentLevel(SearchSlowLogTests.java:206)

**Comment by bcully** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/114349
