### ISSUE TITLE
Rescore windowing not repeatable

### ISSUE THREAD

**Issue by jostheim** [elastic/elasticsearch#11430]
I have a use case where I have a native custom scoring function that ignores the native ES score (vector space score) completely and replaces the native ES score with its own.  I am interested in returning both the native ES score and my custom score.  I haven't found a way to append 2 scores to the returned document so I went with doing a multi-search with 2 queries, the first using the native score and the second doing the same query as the first, but using a rescore that calls my custom scoring function.  I set the size:10 in both queries and the window_size:10 in the rescore section.

The bug (or confusing thing) I see is that I do not get back the same documents for both queries.  Since I set the size to 10 and window to 10 and use the exact same query in both the queries I expected to get the exact same documents back, just with my custom score instead of the native ES score.  Indeed the documentation describes the rescore as "executes a second query only on the Top-K results returned by the query and post_filter phases" which, to me at least, says it should only execute the custom scoring on the first 10 results in the original query.

So is this behavior expected?  Is there a way to append a second score to the document in a native custom_scoring function (which would be all I need but not fix this if it is a bug)?

**Comment by clintongormley** [comment]
Hi @jostheim 

Could you upload a small recreation of what you're doing and the results you're seeing. It'd be easier to investigate.

thanks

**Comment by jostheim** [comment]
I solved my problem by using scriptfields, it is a better, faster more scaleable solution for me.  Though I have to say I think something is still not right with rescoring.

**Comment by clintongormley** [comment]
@jostheim it would still be helpful to have more info about what wasn't working for you, so that we can investigate.
