### ISSUE TITLE
出台一个随着版本的迁移工具

### ISSUE THREAD

**Issue by lianmeng0** [elastic/elasticsearch#114465]
### Description

hi! 您的团队可以出一个可以随着es版本的升级的迁移工具吗？可以跨集群去迁移集群中索引，在不同版本之间。非常感谢！！

**Comment by AI-IshanBhatt** [comment]
Thanks very much for your interest in Elasticsearch. This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). 
If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.
There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
