### ISSUE TITLE
how to query sparse vector with version 8.11?

### ISSUE THREAD

**Issue by sheng49** [elastic/elasticsearch#114475]
I have elasticsearch with version 8.11,

I used query as follow:
   "query":{
      "sparse_vector": {
        "field": 'summary_sparse_vec',
        "query_vector": query_vector
      }
   }
however, I got error:
{"error":{"root_cause":[{"type":"parsing_exception","reason":"unknown query [sparse_vector]","line":1,"col":29}],"type":"parsing_exception","reason":"unknown query [sparse_vector]","line":1,"col":29,"caused_by":{"type":"named_object_not_found_exception","reason":"[1:29] unknown field [sparse_vector]"}},"status":400}

so, how to query sparse vector with version 8.11?

**Comment by AI-IshanBhatt** [comment]
Thanks very much for your interest in Elasticsearch.
This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.
There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
