### ISSUE TITLE
Arbitrary meta field in queries?

### ISSUE THREAD

**Issue by cmfatih** [elastic/elasticsearch#11448]
Can we add an arbitrary field to ES queries? Basically I would like to add a client information field ( for example: `"client":"api"` or `"client":"ui"` ) to ES queries so I could find/grep them in slow log queries.

**Comment by clintongormley** [comment]
Kinda.  You can use stats groups.  Assign each family of queries to a particular group, which you can then grep for in the logs.  As an added benefit, the indices stats API will give you stats per group.

See https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html#stats-groups

**Comment by cmfatih** [comment]
Got it, thanks...
