### ISSUE TITLE
Does the ES 8.5.3 version support join queries between two indices? It is a one-to-many relationship.

### ISSUE THREAD

**Issue by ddiy66** [elastic/elasticsearch#114494]
Hey, master，Now there are two indices, example and example_remind. The example index is the main index and contains fields {examples_id, title, user_id}. The example_remind index is a secondary index and contains fields {examples_id, user_id, remind_status, create_time}. Different users can have separate reminder records for the same data in the example index. For example, if user A (user_id=10001) marks an example with examples_id=12345, an entry will be added to the example_remind index: (examples_id=12345, user_id=10001, remind_status=1, create_time=2024-10-8 10:26:00). Similarly, if user B (user_id=10002) also marks the same example, another entry will be added to the example_remind index: (examples_id=12345, user_id=10002, remind_status=1, create_time=2024-10-10 18:26:00). When user A queries, they want the result set to include entries like [{examples_id=12345, title='test1', user_id=10001, remind_status=1, create_time=2024-10-8 10:26:00}, {examples_id=12000, title='test2', user_id=10001}, ... {}]. How can this be achieved?

**Comment by henningandersen** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

**Comment by ddiy66** [comment]
I'm grateful for your assistance.
