### ISSUE TITLE
[ES|QL] Aggregating high cardinality keyword fields returns` BytesStreamOutput cannot hold more than 2GB of data`

### ISSUE THREAD

**Issue by iverase** [elastic/elasticsearch#114599]
I index locally a few indices with a keyword field holding 100 million unique values and then execute the following query:

```
FROM test_index* | STATS x = count() BY keyword_high | SORT x DESC | LIMIT 10
```

This error out with the following stacktrace:

```
java.lang.IllegalArgumentException: BytesStreamOutput cannot hold more than 2GB of data
org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.common.io.stream.BytesStreamOutput.ensureCapacity(BytesStreamOutput.java:174)
org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.common.io.stream.BytesStreamOutput.writeBytes(BytesStreamOutput.java:85)
org.elasticsearch.server@9.0.0-SNAPSHOT/org.elasticsearch.common.util.BytesRefArray.writeTo(BytesRefArray.java:159)
org.elasticsearch.compute.aggregation.blockhash.BytesRefBlockHash.getKeys(BytesRefBlockHash.java:189)
org.elasticsearch.compute.aggregation.blockhash.BytesRefBlockHash.getKeys(BytesRefBlockHash.java:36)
org.elasticsearch.compute.operator.HashAggregationOperator.finish(HashAggregationOperator.java:194)
org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:272)
org.elasticsearch.compute.operator.Driver.run(Driver.java:189)
org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:378)
```

The issue is [here](https://github.com/elastic/elasticsearch/blob/0877633be2fc98e8ffa28adc28c9d244d33ca4a5/x-pack/plugin/esql/compute/src/main/generated-src/org/elasticsearch/compute/aggregation/blockhash/BytesRefBlockHash.java#L188) where we are trying to copy too much data into the BytesStreamOutput.

**Comment by nik9000** [comment]
Fun. We should totally slice.

I think it's pretty reasonable `BlockHash#getKeys` to be able to return an `Iterator<Page>` or `Iterator<Block[]>` or something like that. We have to figure out how to fetch the values in a sliced way from aggs, but such things are possible. Or we can skip it for now and slice the `Block`s that come back from the aggs after they are built.

All of this code comes from the `HashAggregatorOperator#finish` method. It might be simplest if we made `finish` make an `Iterator<Block[]>` from the `BlockHash` and then grab an entry from it in `getOutput`. Then merge the agg results into it *somehow*.

As far as the size of page to emit - it kind of depends. If we're in any `AggregatorMode#outputPartial` style mode we should do whatever is best for exchanges. Those'll typically be sent over the wire.

If we're not outputting partial then we generally try to respect a `maxPageSize` or a `targetPageSize`. There's an `estimatedRowSize` bit in the planner we can plug in here. But that's a lot of plumbing. So shooting for 20,000 rows in the page is a pretty reasonable rule of thumb. We ran some experiments showing that going a ton bigger didn't give much benefit.
