### ISSUE TITLE
heavy swap usage by elastic search even though plenty of ram is available

### ISSUE THREAD

**Issue by bauerstefan** [elastic/elasticsearch#11456]
"version" : {
    "number" : "1.4.2",
    "build_hash" : "927caff6f05403e936c20bf4529f144f0c89fd8c",
    "build_timestamp" : "2014-12-16T14:11:12Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.2"

The associated java processes consume quite a bit of swap even though plenty of ram is available:

![es1](https://cloud.githubusercontent.com/assets/10959745/7937345/d49f9fc6-093f-11e5-858b-7fddfb057ef6.PNG)

![es2](https://cloud.githubusercontent.com/assets/10959745/7937364/da223c06-093f-11e5-980a-94d3b7c2d5ee.PNG)

/etc/sysconfig/elasticsearch has the following settings:

ES_HOME=/usr/share/elasticsearch
ES_HEAP_SIZE=24g
MAX_OPEN_FILES=65535
MAX_MAP_COUNT=262144
LOG_DIR=/var/log/elasticsearch
DATA_DIR=/var/lib/elasticsearch
WORK_DIR=/tmp/elasticsearch
CONF_DIR=/etc/elasticsearch
CONF_FILE=/etc/elasticsearch/elasticsearch.yml
ES_USER=elasticsearch

/etc/sysconfig/elasticsearch2 - the second instance has identical settings.

**Comment by clintongormley** [comment]
Hi @bauerstefan 

Please read this documentation about how to stop swapping: https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html#setup-configuration-memory

Given that it looks like you are using one of the packages, you should also see the docs for setting MAX_LOCKED_MEMORY here: https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-service.html
