### ISSUE TITLE
3 Elasticsearch node cluster

### ISSUE THREAD

**Issue by HSVK** [elastic/elasticsearch#11451]
Hi, we were having 2 nodes one with master and data and the other with data and no master, now we have added an additional 3rd node into the cluster with data and no master. So what happened now is that the indices are currently writing the data only to the newly added third node and the first 2 nodes are not have any shards located. 
I want the data/shards to be allocated to all the 3 nodes, is there any issue with the configs? Can you please assist.

**Comment by markwalkom** [comment]
Please join us in #elasticsearch on Freenode or at https://discuss.elastic.co/ for troubleshooting help, we reserve Github for confirmed bugs and feature requests :)
