### ISSUE TITLE
Can't create repository

### ISSUE THREAD

**Issue by carlosvega** [elastic/elasticsearch#11463]
when I try to create a new repository for backups doing:

```
sudo curl -XPUT 'http://localhost:9200/_snapshot/es_backup' -d '{ "type": "fs", "settings": { "location": "/home/user/ES/", "compress": true } }'
```
after (and also without it) creating the folder and giving it 777 permissions I get this error:

> {"error":"RepositoryException[[es_backup] failed to create repository]; nested: CreationException[Guice creation errors:\n\n1) Error injecting constructor, org.elasticsearch.common.blobstore.BlobStoreException: Failed to create directory at [/home/user/ES]\n  at org.elasticsearch.repositories.fs.FsRepository.<init>(Unknown Source)\n  while locating org.elasticsearch.repositories.fs.FsRepository\n  while locating org.elasticsearch.repositories.Repository\n\n1 error]; nested: BlobStoreException[Failed to create directory at [/home/user/ES]]; ","status":500}

this is my cluster info:

> curl -XGET 'http://localhost:9200'
{
  "status" : 200,
  "name" : "ES Hele test",
  "cluster_name" : "es_test",
  "version" : {
    "number" : "1.5.2",
    "build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
    "build_timestamp" : "2015-04-27T09:21:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

**Comment by imotov** [comment]
@carlosvega That looks like a permission issue. What are permissions of /home/user? Can you do something like 
```
sudo -u elasticsearch touch /home/user/ES/test
```
where `elasticsearch` is the user name that you run elasticsearch under?

**Comment by carlosvega** [comment]
Mmm it's weird, I created the folder in /backup_es and now I'm able to do it.
Thanks !

**Comment by imotov** [comment]
The most likely reason for the original command to fail is that elasticsearch user wasn't able to list `/home/user` directory. I am going to close this issue since it doesn't look like a bug and we are trying to use github issue for bug reports and feature requests. If you have any additional questions about elasticsearch functionality or setup, please feel free to join us on https://discuss.elastic.co/
