### ISSUE TITLE
[ES|QL] Simplify syntax of named parameter for field names and patterns

### ISSUE THREAD

**Issue by fang-xing-esql** [elastic/elasticsearch#114673]
`ES|QL` supports named parameters for literal values, field names and field name patterns. The field names, field name patterns and some of the literal values are in string format. Today, the way to differentiate them is using the `kind` option explicitly in `params`, so that when a string is provided as a named parameter's value, parser won't be confused about whether it is a literal value, field or a pattern. However we'd like to simplify the syntax, and make it easier to use and more self-explained.

The proposed simplified syntax is combining the "value" and "kind" attributes into one attribute in `params`.

In the examples below, we'll explain why we need users to provide this information, and what the proposed simplified syntax looks like.

Example 1: 
In this query below, both literal values and field names are valid inputs to aggregate functions, `Group BY` clause and `SORT` commands. However different results will be returned from AVG("event.duration") and AVG(event.duration), and the same apply to `Group BY` and `SORT`. Today, they can be  differentiated by `kind`, `"kind" : "identifier"` means this is a field name, if `kind` is omitted or `"kind" : "value"`, it means this is a literal value.

```
POST /_query?format=txt
{
 "query": """
   FROM sample_data
   | STATS x = ?param1(?param2) by ?param3
   | SORT ?param3
   """,
 "params": [ 
     {"param1" : {"value" : "avg", "kind" : "identifier"}},
     {"param2" : {"value" : "event.duration", "kind" : "identifier"}}, 
     {"param3" : {"value" : "client.ip", "kind" : "identifier"}}
 ]
====Simplified====
 "params": [ 
     {"param1" : {"identifier" : "avg"}},
     {"param2" : {"identifier" : "event.duration"}}, 
     {"param3" : {"identifier" : "client.ip"}}
 ]
}
```

Example 2: 
In this query below, both literal values and field names are valid inputs to the equal predicate in `WHERE` clause. However, without knowing whether an input is a field name or literal value, we might end up in ambiguous situations like  `a == "a"`, `a == a`, or `"a"=="a"`, if a named parameter with value "a" is provided without being explicitly specified as a field name or a literal value.
Similarly, both field names and field name patterns are valid inputs to `KEEP` and `DROP` commands, and `*` is a valid character in the field names, without knowing whether it is a field name or pattern, we might end up in ambiguous situations as well.

```
POST /_query?format=txt
{
 "query": """
   FROM persons
   | WHERE ?param1.?param2 == ?param3
   | KEEP ?param4, ?param1.?param2, ?param1.?param5
   | SORT ?param6
   """,
   "params": [
       {"param1" : {"value" : "car", "kind" : "identifier"}}, 
       {"param2" : {"value" : "make", "kind" : "identifier"}}, 
       {"param3" : "tesla"}, 
       {"param4" : {"value" : "*name", "kind" : "pattern"}}, 
       {"param5" : {"value" : "model", "kind" : "identifier"}}, 
       {"param6" : {"value" : "first_name", "kind" : "identifier"}}
   ]
====Simplified====
   "params": [
       {"param1" : {"identifier" : "car"}}, 
       {"param2" : {"identifier" : "make"}}, 
       {"param3" : "tesla"},    or  {"param3" : {"value" : "Tesla"}}, 
       {"param4" : {"pattern" : "*name"}}, 
       {"param5" : {"identifier" : "model"}}, 
       {"param6" : {"identifier" : "first_name"}}
   ]
}
```

**Comment by luigidellaquila** [comment]
If we introduce a JSON data type, this syntax will become ambiguous, ie. we won't be able to distinguish between an identifier name and a JSON value with one of the fields called "identifier".

We could find other ways to simplify the syntax though, eg. (just brainsorming) with a different parameter placeholder (`?param` for literals, `??param` for identifiers?). That would also make the query string more clear and self explanatory.

In addition it will allow parse-time validation for cases where literals are not allowed (eg. for function names)

**Comment by fang-xing-esql** [comment]
> If we introduce a JSON data type, this syntax will become ambiguous, ie. we won't be able to distinguish between an identifier name and a JSON value with one of the fields called "identifier".

The name of the parameter is recognized at the outer most layer. For example, in `"" : [{"param1" : {"identifier" : "car"}}]`, `param1` is the name of the parameter, `car` is the value of it, and it is a field name(identifier), we don't take `identifier` as a name of parameter. If a parameter is defined as `"params" : [{"identifier" : "car"}]` or `"params" : [{"identifier" : {"value" : "car"}}]`, `identifier` will be recognized as the name of the parameter, and it is a literal value `car`.

> We could find other ways to simplify the syntax though, eg. (just brainsorming) with a different parameter placeholder (`?param` for literals, `??param` for identifiers?). That would also make the query string more clear and self explanatory.

Hmm, we thought about an approach similar to this before and it has been proposed in the google doc in the prior discussions, and it wasn't picked as the first choice :-). When I think about it again, it looks more self-explained to me when the identifier is specified explicitly in the `params`, comparing with coding `??` in the query text. If more than one option(literal, field name, pattern) is valid in a position in the query, users don't have to change the query text.

> In addition it will allow parse-time validation for cases where literals are not allowed (eg. for function names)

Yeah, there are places like function names, mv_expand, where we are sure that they can only be identifier, there is no ambiguity, we can simplify and don't need to classify them there. However there are some places where there are ambiguities, like mentioned in the problem description, that we do need to classify.

**Comment by luigidellaquila** [comment]
What I mean is that, in a world where we have a `DataType.JSON`, something like  `{"foo" : "bar"}` could be a parameter value, and so could be `{"identifier" : "car"}`, eg.

```
"params": [
       {"param1" : {"foo" : "bar"}},
       {"param2" : {"identifier" : "car"}}, 
]
```

in this case, `param1` is a literal, but what about `param2`? Is it a literal with value `{"identifier" : "car"}` or an identifier with value `car`?

We'll need something to disambiguate, eg. 

```
{"param2" : {"identifier" : "car"}, "type": "json"}, 
```

so we are back to the original problem.

Not an immediate problem of course, but it looks like a one way door.

**Comment by fang-xing-esql** [comment]
> What I mean is that, in a world where we have a `DataType.JSON`, something like `{"foo" : "bar"}` could be a parameter value, and so could be `{"identifier" : "car"}`, eg.
> 
> ```
> "params": [
>        {"param1" : {"foo" : "bar"}},
>        {"param2" : {"identifier" : "car"}}, 
> ]
> ```
> 
> in this case, `param1` is a literal, but what about `param2`? Is it a literal with value `{"identifier" : "car"}` or an identifier with value `car`?
> 
> We'll need something to disambiguate, eg.
> 
> ```
> {"param2" : {"identifier" : "car"}, "type": "json"}, 
> ```
> 
> so we are back to the original problem.
> 
> Not an immediate problem of course, but it looks like a one way door.

I see. Today `{"param1" : {"foo" : "bar"}}`is unsupported, only `value` and `kind` are recognized as valid attributes for a named parameter, json data type is not supported by named parameter yet.

In the future, one option(without specifying type explicitly) that I can think of to be able to support json data type is with this syntax `{"param1" : {"value" : {"foo" : "bar"}}}`, assuming that an identifier or pattern is not json type.

**Comment by ChrisHegarty** [comment]
For reference, linking the PR that added `Named parameter for field names and field name patterns` #112905

**Comment by astefan** [comment]
> If we introduce a JSON data type, this syntax will become ambiguous, ie. we won't be able to distinguish between an identifier name and a JSON value with one of the fields called "identifier".

That's a good point, @luigidellaquila. But, we will need some kind of differentiator (as you pointed out) even in that specific situation because right now we allow syntax like this ``row `{"a"="b"}` = 123`` where a "variable" can be named `{"a"="b"}` if it's escaped.
This means that a query like this

```
{
  "query": "row ?my_json = \"{\\\"a\\\":\\\"b\\\"}\", some_json_value = ?json_value",
  "params": [
      {"my_json":{"value":"{\"a\":\"b\"}","kind":"identifier"}},
      {"json_value":"{\"a\":\"b\"}"}
      ]
}
```

with output

```
   {"a":"b"}   |some_json_value
---------------+---------------
{"a":"b"}      |{"a":"b"}      
```

will need a `"kind":"json"` for the param `json_value` or the query is adjusted to `some_json_value = ?json_value::json` (that's preferred). And I see even more arguments in favor of this type of expressive params settings for your other example

> "params": [
>        {"param1" : {"foo" : "bar"}},
>        {"param2" : {"identifier" : "car"}}, 
> ]

There is no way in which ES|QL can identify  `{"identifier" : "car"}` as json. It has to be passed as a string, ie `"{\"identifier\" : \"car\"}`.


> We could find other ways to simplify the syntax though, eg. (just brainsorming) with a different parameter placeholder (`?param` for literals, `??param` for identifiers?). That would also make the query string more clear and self explanatory.
> 

There is still the question of `pattern`. What symbol would you use for that one?

**Comment by astefan** [comment]
@stratoula It would be ideal for users to define some values and then the query to incorporate those as a drop-in replacement.

Let's take a very simple example: `where ?my_field == ?my_value`. User provides these two params in UI as `my_field` -> `"first_name"` and `my_value` -> `"Andrei Stefan"`. If we would to blindly make the replacement, or **even Kibana making this replacement**, the command would become `where "first_name" == "Andrei Stefan"`. This is a syntactically correct query, but it **doesn't reflect the user intention**. The user intention here can be of multiple options:
- the plain text `first_name` equality to `Andrei Stefan` plain text
- the field name `first_name` equality to **field name** `Andrei Stefan`
- the field name `first_name` equality to `Andrei Stefan` plain text
- the plain text `first_name` equality to field name `Andrei Stefan`

The language (the parser) doesn't know which of these options the user intended to express. And even if Kibana would do a drop-in replacement, it wouldn't be aware of the user's intention and it would **either surround those values with double quotes or not**.

Not to mention that a valid query is also `where ?my_value == ?my_field` which means that, assuming the position of the "identifier" is first in the equality operator expression, we cannot determine if this was the true user's intention. ie `Andrei Stefan` can be the field name, its placement as the second argument doesn't make it a constant value.

**Comment by stratoula** [comment]
@astefan thanx a lot, as I say above I totally understand the technical constraints here. 

With my comment I just wanted to add to the loop @teresaalvarezsoler as the PM of the dashboard variables and highlight that the `Custom values` control type as described here https://github.com/elastic/elasticsearch/issues/114673#issuecomment-2410735584 won't work correctly if somehow we cant identify the user's intentions. 

So simplifying the syntax doesnt really help us here, as it doesnt change the UX. The user needs somehow to define that this is a field or a value.

**Comment by astefan** [comment]
> [@astefan](https://github.com/astefan) thanx a lot, as I say above I totally understand the technical constraints here.
> 
> With my comment I just wanted to add to the loop [@teresaalvarezsoler](https://github.com/teresaalvarezsoler) as the PM of the dashboard variables and highlight that the `Custom values` control type as described here [#114673 (comment)](https://github.com/elastic/elasticsearch/issues/114673#issuecomment-2410735584) won't work correctly if somehow we cant identify the user's intentions.
> 
> So simplifying the syntax doesnt really help us here, as it doesnt change the UX. The user needs somehow to define that this is a field or a value.

++
this was my intention with my previous comment, as well: the way we can understand the user's intention is paramount here.

**Comment by luigidellaquila** [comment]
> but you can also specify params as [{"rating": 7.5}, {"year": 2000}] and still refer them by position:

This is bad

> There is no way in which ES|QL can identify {"identifier" : "car"} as json. It has to be passed as a string, ie "{\"identifier\" : \"car\"}.

There is no way now, but it would make a lot of sense if we support JSON type. 
The idea of having to pass JSON as a string, with escapes and all the rest, makes me a bit uncomfortable, both because escapes are a big source of problems and because it would make it ambiguous (is it a string or a JSON? Do we need yet another way to distinguish them?)

**Comment by ioanatia** [comment]
> Can you come up with more concrete examples for "foo"? What would we think the language needs in terms of parameters extensibility? I don't think there are any concerns with BWC since foo is an addition, no?

I see that we changed the format in the meantime which alleviates my concerns - in the initial proposal it was `[{"func" : "count", "identifier" : true}]` which was not sustainable if we wanted to add more options. But changing it to `[{"func": {"value": "count", "identifier": true"}]` would not have the same issue - so it's all good, sorry for the red herring.

I do think @luigidellaquila makes a good point that passing JSON as a string is an interesting choice that maybe we should reconsider.
