### ISSUE TITLE
Cant create XContentParser from source field

### ISSUE THREAD

**Issue by CaoManhDat** [elastic/elasticsearch#11469]
I'm currently create a CustomQuery, i need to parse _source field to get some specific field. But it some time throw ElasticsearchParseException
```java
BytesArray bytes = new BytesArray(doc.getField("_source").binaryValue());
XContentParser parser = XContentFactory.xContent(bytes).createParser(bytes);
```
exception
```java
org.elasticsearch.ElasticsearchParseException: Failed to derive xcontent from org.elasticsearch.common.bytes.BytesArray@d94ffdcd
	at org.elasticsearch.common.xcontent.XContentFactory.xContent(XContentFactory.java:259)
```

**Comment by clintongormley** [comment]
Hi @CaoManhDat 

I suggest asking this question in the forum https://discuss.elastic.co/c/elasticsearch which is the place to ask questions.  We use github issue for bug reports and feature requests

thanks

**Comment by CaoManhDat** [comment]
Hi @clintongormley 
Thanks for your suggestion. I already posted a topic about this issue in elasticsearch forum. But i think this kinda a issue of XContentFactory.

thanks
