### ISSUE TITLE
Can not make requests via netcat/nc

### ISSUE THREAD

**Issue by heathtechnical** [elastic/elasticsearch#11466]
Although not particularly useful for many folk, this one had me scratching my head for a while, this does as expected:

    # echo -ne 'GET / HTTP/1.0\r\n\r\n' | nc localhost 9200 | head -1
    HTTP/1.0 200 OK

While this returns nothing:

    # echo -ne 'GET /_search HTTP/1.0\r\n\r\n' | nc localhost 9200 | head -1

I believe this is down to Netty 3.x not supporting tcp half-closed sockets which is what is happening here (nectat closes the sender half of the socket as soon as it's done reading stdin).  Incidentally, it's strange that the first request works as expected, but I assume the response is quick enough that it is received before the sender half is shutdown.

By the looks of it Netty 4.0 has support for half-closed sockets, in the meanwhile a rather clumsy workaround is to introduce a small delay before netcat finishes with stdin:

    (echo -ne 'GET /_search HTTP/1.0\r\n\r\n'; sleep 1) | nc localhost 9200 | head -1
    HTTP/1.0 200 OK

Does this seem a reasonable explanation?

**Comment by clintongormley** [comment]
@spinscale any ideas?

**Comment by spinscale** [comment]
Correct explanation. See the [netty 4.0 changes](http://netty.io/wiki/new-and-noteworthy-in-4.0.html#wiki-h3-23) and their mention of half-closed sockets. Not supported under netty 3.

A workaround might be to use the `-i` interval of netcat

**Comment by clintongormley** [comment]
thanks @spinscale. I don't think there is anything we need to change here, so I'll close this issue.  @heathtechnical feel free to reopen if i've missed something
