### ISSUE TITLE
Error while building 7.17.24 from source

### ISSUE THREAD

**Issue by hbh7** [elastic/elasticsearch#114631]
I'm having what looks to be the same issue as https://github.com/elastic/elasticsearch/issues/94446. 

Setup:
```
git clone https://github.com/elastic/elasticsearch.git && cd elasticsearch
git checkout tags/v7.17.24
./gradlew localDistro
```

This results in the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':x-pack:plugin:ml:bundlePlugin'.
> Could not resolve all dependencies for configuration ':x-pack:plugin:ml:nativeBundle'.
   > Could not find org.elasticsearch.ml:ml-cpp:7.17.24-SNAPSHOT.
     Searched in the following locations:
       - https://artifacts-snapshot.elastic.co/ml-cpp/7.17.24-SNAPSHOT/downloads/ml-cpp/ml-cpp-7.17.24-SNAPSHOT.zip
     Required by:
         project :x-pack:plugin:ml

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

BUILD FAILED in 47s
19 actionable tasks: 5 executed, 14 up-to-date
```

Seems the file at https://artifacts-snapshot.elastic.co/ml-cpp/7.17.24-SNAPSHOT/downloads/ml-cpp/ml-cpp-7.17.24-SNAPSHOT.zip is no longer available, and therefore the build cannot continue. Hoping there's a resolution that can be found. Thanks!

**Comment by as1605** [comment]
Find the latest version of ml-cpp and use it instead of 7.17.

Replace `${project.version}` with `8.15.2`
https://github.com/elastic/elasticsearch/blob/7.17/x-pack/plugin/ml/build.gradle#L93

**Comment by mark-vieira** [comment]
> Seems the file at https://artifacts-snapshot.elastic.co/ml-cpp/7.17.24-SNAPSHOT/downloads/ml-cpp/ml-cpp-7.17.24-SNAPSHOT.zip is no longer available, and therefore the build cannot continue. Hoping there's a resolution that can be found. Thanks!

These artifacts aren't kept indefinitely for already released versions, only the current in-development version which at the moment is 7.17.25.
