### ISSUE TITLE
Show human readable Elasticsearch version that created index

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#11484]
Currently, you can see the Version ID of Elasticsearch that created an index by checking the index's settings:

```
$ curl -XGET localhost:9200/test/_settings?pretty\&human
{
  "test" : {
    "settings" : {
      "index" : {
        "creation_date" : "1433353647548",
        ...
        "version" : {
          "created" : "1050299"
        },
        ...
      }
    }
  }
}
```

The value for `index.version.created` is not human readable. [It is exactly the value of `org.elasticsearch.Version.V_1_5_2_ID`](https://github.com/elastic/elasticsearch/blob/v1.5.2/src/main/java/org/elasticsearch/Version.java#L231). The value, `1050299`, is the same as `01050299`, [which maps to `XXYYZZAA` where](https://github.com/elastic/elasticsearch/blob/v1.5.2/src/main/java/org/elasticsearch/Version.java#L38):

```
// The logic for ID is (read from the right to avoid missing implied 0s):
// XXYYZZAA, where
// - XX is major version
// - YY is minor version
// - ZZ is revision,
// - AA is Beta/RC indicator
//   - values below 50 are beta builds
//   - values below 99 are RC builds
//   - exactly 99 indicates a release

XX=01
YY=05
ZZ=02
AA=99
```

It's great that we get a version, but it's not immediately readable. Moving into ES 2.0, when we enable doc values by default, it will be useful to be able to explain to users that indices created using prior to 2.0 will not have doc values by default, but those created afterward will have them. It will be helpful to have a way to see the version number akin to the `version.number` that appears when you hit the root endpoint:

```
$ curl -XGET localhost:9200/
{
  ...
  "version" : {
    "number" : "1.5.2",
    ...
    "lucene_version" : "4.10.4"
  },
  ...
}
```

... rather than having to check to see if it starts with a `2` _and_ it is 7 digits long (as opposed to 6 digits long, indicating `0.20`!).

**Comment by drewr** [comment]
:+1:

**Comment by colings86** [comment]
+1
