### ISSUE TITLE
IndicesStatsRequestBuilder is missing level parameter

### ISSUE THREAD

**Issue by marcmoe** [elastic/elasticsearch#11480]
The REST call for Indices stats provides a parameter for level, but the IndicesStatsRequestBuilder does not.

See also https://www.elastic.co/guide/en/elasticsearch/reference/1.5/indices-stats.html at the bottom. 

Quot: "The stats returned are aggregated on the index level, with primaries and total aggregations. In order to get back shard level stats, set the level parameter to shards"

and IndicesStatsRequestBuilder class https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/action/admin/indices/stats/IndicesStatsRequestBuilder.java

**Comment by colings86** [comment]
The IndicesStatsResponse has methods (`getIndices()` and `getShards()`) which return the different levels objects so a parameter on the request in the Java API is not needed.
