### ISSUE TITLE
Ability to monitor norms memory usage

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/elasticsearch#11495]
Been reading the Elasticsearch [reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-core-types.html#norms), which warns me each field in each document with norms uses ~1 byte of memory. However I've been looking in the stats, but I can't see where this memory is accounted for so I can see if it is biting me. Is it included in fielddata? Is it always used, or only after I've run a query?

**Comment by clintongormley** [comment]
Hi @jimmyjones2 

You can't get the norms memory usage all by itself, but the amount of memory that is used by Lucene for open segments (which includes norms, and things like the terms index) is available through the node stats or the indices stats under `segments.memory_in_bytes`.

As a side note, there is an open patch in Lucene to move norms fully on to disk, which will resolve the problem of heavy norms memory use.

**Comment by rmuir** [comment]
> However I've been looking in the stats, but I can't see where this memory is accounted for so I can see if it is biting me. Is it included in fielddata?

No, currently its included in the `segments` memory usage of the stats api:

    "segments" : {
        "count" : 4,
        "memory_in_bytes" : 13160 <-- there

But this statistic also includes other lucene datastructures. For 2.0, it is broken down more into categories like `norms_memory_in_bytes`, `terms_memory_in_bytes`, and so on:

    "segments" : {
        "count" : 4,
        "memory_in_bytes" : 13160
        ...
        "norms_memory_in_bytes" : 384 <-- there

Finally for 2.0 if you really want to know the gory details, pass `verbose=true` to the `_segments` api:

    "ram_tree" : [
      ...
      , {
                "description" : "norms [Lucene50NormsProducer(fields=4,active=1)]",
                "size_in_bytes" : 112,
                "children" : [ {
                  "description" : "field 'message' [table compressed]",
                  "size_in_bytes" : 72,
                  "children" : [ {
                    "description" : "ordinals [Packed64SingleBlock2(bitsPerValue=2,size=5,blocks=1)]",
                    "size_in_bytes" : 48
                  } ]
                } ]
              }

> Is it always used, or only after I've run a query?

Well you have to have norms for the field for them to be used. If you dont want them, then omit norms for fields where you dont care about scoring.

Today norms for a field are lazy-loaded on-demand, per-segment for the first query against the field. Additionally, background merges will cause norms for *all fields* to be loaded at once. So you can't rely on this laziness really: omit norms if you don't need them. For 2.0 merges will not do that.

**Comment by jimmyjones2** [comment]
@rmuir Thanks for the detailed response, that explains everything. I look forward to 2.0 that has already implemented exactly what I need.
