### ISSUE TITLE
Slow indexing in upgrade from 1.3.6 to 1.5.1

### ISSUE THREAD

**Issue by embark** [elastic/elasticsearch#11499]
Hi all,

I upgraded from 1.3.6 to 1.5.1. Indexing is significantly slower, and there are 10x more IO reads occurring. After noticing this issue, I ran `/_upgrade` and turned off `refresh` (setting `refresh_interval: -1`). I also tried restarting the cluster. Despite this, I did not see improvement. The bulk indexing threads seem to be spending a lot of time in `InternalEngine.loadCurrentVersionFromIndex`.

My JVM version is 1.8.0_25.

This is the hot threads snippet I'm observing:

```
Hot threads at 2015-06-03T21:26:54.112Z, interval=500ms, busiestThreads=3, ignoreIdleThreads=true:
   
    1.6% (8.1ms out of 500ms) cpu usage by thread 'PauseDetector'
     10/10 snapshots sharing following 8 elements
       java.lang.Thread.sleep(Native Method)
       java.lang.Thread.sleep(Thread.java:340)
       java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
       com.google.common.util.concurrent.Uninterruptibles.sleepUninterruptibly(Uninterruptibles.java:275)
       core.time.Clock.sleep(Clock.java:141)
       core.time.Clock.sleep(Clock.java:121)
   
    1.6% (7.8ms out of 500ms) cpu usage by thread '[flush][T#30]'
     10/10 snapshots sharing following 28 elements
       sun.nio.ch.FileDispatcherImpl.pread0(Native Method)
       sun.nio.ch.FileDispatcherImpl.pread(FileDispatcherImpl.java:52)
       sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:220)
       sun.nio.ch.IOUtil.read(IOUtil.java:197)
       sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:708)
       sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:694)
       org.apache.lucene.store.NIOFSDirectory$NIOFSIndexInput.readInternal(NIOFSDirectory.java:179)
       org.apache.lucene.store.BufferedIndexInput.refill(BufferedIndexInput.java:342)
       org.apache.lucene.store.BufferedIndexInput.readByte(BufferedIndexInput.java:54)
       org.apache.lucene.store.DataInput.readVInt(DataInput.java:122)
       org.apache.lucene.store.BufferedIndexInput.readVInt(BufferedIndexInput.java:221)
       org.apache.lucene.codecs.blocktree.SegmentTermsEnumFrame.loadBlock(SegmentTermsEnumFrame.java:152)
       org.apache.lucene.codecs.blocktree.SegmentTermsEnum.seekExact(SegmentTermsEnum.java:506)
       org.apache.lucene.index.BufferedUpdatesStream.applyTermDeletes(BufferedUpdatesStream.java:427)
       org.apache.lucene.index.BufferedUpdatesStream.applyDeletesAndUpdates(BufferedUpdatesStream.java:286)
       org.apache.lucene.index.IndexWriter.applyAllDeletesAndUpdates(IndexWriter.java:3312)
       org.apache.lucene.index.IndexWriter.maybeApplyDeletes(IndexWriter.java:3303)
       org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2989)
       org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3134)
       org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3101)
       org.elasticsearch.index.engine.InternalEngine.commitIndexWriter(InternalEngine.java:1214)
       org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:637)
       org.elasticsearch.index.engine.InternalEngine.flush(InternalEngine.java:593)
       org.elasticsearch.index.shard.IndexShard.flush(IndexShard.java:675)
       org.elasticsearch.index.translog.TranslogService$TranslogBasedFlush$1.run(TranslogService.java:203)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)
   
    0.8% (3.7ms out of 500ms) cpu usage by thread '[bulk][T#1]'
     10/10 snapshots sharing following 28 elements
       sun.nio.ch.FileDispatcherImpl.pread0(Native Method)
       sun.nio.ch.FileDispatcherImpl.pread(FileDispatcherImpl.java:52)
       sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:220)
       sun.nio.ch.IOUtil.read(IOUtil.java:197)
       sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:708)
       sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:694)
       org.apache.lucene.store.NIOFSDirectory$NIOFSIndexInput.readInternal(NIOFSDirectory.java:179)
       org.apache.lucene.store.BufferedIndexInput.refill(BufferedIndexInput.java:342)
       org.apache.lucene.store.BufferedIndexInput.readByte(BufferedIndexInput.java:54)
       org.apache.lucene.store.DataInput.readVInt(DataInput.java:122)
       org.apache.lucene.store.BufferedIndexInput.readVInt(BufferedIndexInput.java:221)
       org.apache.lucene.codecs.blocktree.SegmentTermsEnumFrame.loadBlock(SegmentTermsEnumFrame.java:152)
       org.apache.lucene.codecs.blocktree.SegmentTermsEnum.seekExact(SegmentTermsEnum.java:506)
       org.elasticsearch.common.lucene.uid.PerThreadIDAndVersionLookup.lookup(PerThreadIDAndVersionLookup.java:104)
       org.elasticsearch.common.lucene.uid.Versions.loadDocIdAndVersion(Versions.java:150)
       org.elasticsearch.common.lucene.uid.Versions.loadVersion(Versions.java:161)
       org.elasticsearch.index.engine.InternalEngine.loadCurrentVersionFromIndex(InternalEngine.java:1008)
       org.elasticsearch.index.engine.InternalEngine.innerIndex(InternalEngine.java:404)
       org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:362)
       org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:498)
       org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnReplica(TransportShardBulkAction.java:578)
       org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$ReplicaOperationTransportHandler.messageReceived(TransportShardReplicationOperationAction.java:249)
       org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$ReplicaOperationTransportHandler.messageReceived(TransportShardReplicationOperationAction.java:228)
       org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:277)
       org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       java.lang.Thread.run(Thread.java:745)
```

**Comment by clintongormley** [comment]
@mikemccand any thoughts about this?

**Comment by mikemccand** [comment]
Can you describe the docs you're indexing?  Do you pass your own IDs
or does ES generate them?  Do you ever replace docs or just index new ones?

How many segments are in the shard?  Do you use delete-by-query?

Any custom index settings?

**Comment by embark** [comment]
Thanks for following up @mikemccand 

In response:
* The docs are JSON blobs.
* Yes, I pass in my own IDs.
* Mostly new docs are indexed, but replacement can happen.
* Running `GET` on `_segments`, each shard has roughly `num_committed_segments: 231` and `num_search_segments: 229`
* There are no deletes.
* Custom index settings include the following:
```
index:
  cache:
    field.type: soft
    field.max_size: 1g
    filter.max_size: 1g
  merge:
    policy:
      max_merge_at_once: 8
      max_merged_segment: 2g
      segments_per_tier: 24
  compound_format: false
  compound_on_flush: false
  shard.check_on_startup: false
  translog.flush_threshold_ops: 50000
  store.distributor: random

indices.memory.index_buffer_size: 10%
indices.fielddata.cache.size: 40%
index.store.type: niofs
```

**Comment by mikemccand** [comment]
OK that's a rather high segment count, which then makes ID lookups more costly (it must visit every segment).

This is exacerbated by your high `segments_per_tier` setting and `max_merged_segment`; can you change that setting back to default?  And maybe put max_merged_segment back to its default (5g)?

Also, niofs gives worse performance for id-lookup heavy use cases; can you remove that setting (let ES use the default, which switches between niofs / mmap depending on which index file is being opened)?

Do you leave plenty of RAM (50% is recommended) to the OS for IO caching?

**Comment by mikemccand** [comment]
Another question: what do your IDs look like, e.g. how many bytes are they typically?  Longer IDs make things slower, and which ID you use can have an impact on performance: http://blog.mikemccandless.com/2014/05/choosing-fast-unique-identifier-uuid.html

**Comment by embark** [comment]
In followup, @mikemccand, 

I let the all merge policies for `segments_per_tier`, `max_merged_segment`, and `max_merge_at_once`  go back to the defaults as well as `index.store.type`. There should be plenty of RAM...

I let the changes soak a little, but sadly performance is still slow, and disk read IO is actually slightly higher now. 

My ID's are about 13 bytes long, but I'm afraid that that the ID length isn't very changeable. The ID length was the same before the upgrade as well.

**Comment by mikemccand** [comment]
Hmm that's odd that you see no improvement from those changes.

Can you confirm segments counts per shard came down to normal (~30-40) levels once you cut back to defaults for the merge policy?

13 byte IDs is not bad; I've seen much worse!

What IO system are you using?

Can you run the diagnostics plugin (https://github.com/elastic/elasticsearch-support-diagnostics) and post the results?

**Comment by embark** [comment]
@mikemccand Sorry for the delay! And thank you for all the help so far. 

The segments counts per shard are roughly 80-90 now, so a bit higher than what you expect, but still a lot lower.

Not totally sure what you mean by IO system. Do you mean filesystem?

Here is the diagnostic run: https://gist.github.com/embark/54ae58bdf9755ddd90ce

**Comment by mikemccand** [comment]
> Here is the diagnostic run:

Thanks, I see lots of time spent throttling.  Can you disable or increase store merge IO throttling?  https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-store.html#store-throttling

The default (20 MB/sec) is very low (in ES 2.0 this will auto-adapt).

> The segments counts per shard are roughly 80-90 now, 

That's still too high, I'm not sure why.  Was this taken while indexing was still running?  Could be there were merges in flight.

> I'm using spinny disks rather than SSD

OK, slow :)  Try setting `index.merge.scheduler.max_thread_count` to 1 which should net/net allow merges to complete faster.  Also see https://www.elastic.co/blog/performance-considerations-elasticsearch-indexing for more ideas.

You should probably upgrade from 1.8.0_25.

**Comment by embark** [comment]
> That's still too high, I'm not sure why. Was this taken while indexing was still running? Could be there were merges in flight.

Yes, indexing is constantly happening, so it was taking while indexing was running. However, I turned it off for a little and still saw around 80-90 segments.

So far nothing helps, but I'll take a look at the document!

**Comment by clintongormley** [comment]
Nothing more in the last 7 months - closing
