### ISSUE TITLE
[Bug] 'ignore_malformed' applied to a malformed (boolean) numeric field does not work 

### ISSUE THREAD

**Issue by angeleg** [elastic/elasticsearch#11498]
When I try to index a doc with a boolean field that's mapped as numeric, even with ìgnored_malformed`set to`true`, an exception is raised.

Repro steps:
##### Create a new index:

```
curl -XPUT localhost:9200/myindex
```

which yields `{ "acknowledged" : true }`
##### Create a mapping for a type in that index, with one integer field that has `ignore_malformed` set to true and coerce set to `true`

```
curl -XPUT localhost:9200/myindex/_mapping/mytype -d
'{
    "mytype": {
      "properties": {
        "foo": {
        "type": "integer",
        "ignore_malformed": true,
        "coerce": false
        }
      }
  }
}'
```

which yields `{ "acknowledged" : true }`
##### Index one document with a field whose value is false

```
curl -XPUT localhost:9200/myindex/mytype/one -d
'{
  a: 3,
  foo: false
}'
```

which yields an exception:

```
{
"error" : "MapperParsingException[failed to parse [foo]]; nested: JsonParseException[Current token (VALUE_FALSE) not numeric, can not use numeric value accessors at [Source: [B@3a98c595; line: 3, column: 13]]; ",
"status" : 400
}
```

According to `ignored_malformed: true`, even if false is not an integer, the doc should get indexed anyway.

**Comment by szroland** [comment]
This will not only fail with booleans, but with other non-numeric values as well, e.g.
```
{
  a: 3,
  foo: {
    value: []
  }
}
```
```
type: "json_parse_exception"
reason: "Current token (START_ARRAY) not numeric, can not use numeric value accessors at [Source: org.elasticsearch.common.io.stream.InputStreamStreamInput@2725adf1; line: 4, column: 13]"
```

Ignoring malformed values depends on the code throwing an `IllegalArgumentException` or `MapperParsingException` but here a `JsonParseException` is thrown. The solution would be to check the token type in `AbstractXContentParser.intValue()`, `shortValue()`, etc. after the String check, and if it is not numeric, do not even try parsing the value, throw an `IllegalArgumentException` immediately.

This touches the same area of code as #11513. Happy to take a stab if you all agree.

**Comment by clintongormley** [comment]
Closing in favour of #11513

**Comment by lwiskowski** [comment]
I changed AbstactXContentParser.java to address this issue. I will do a pull request with the updated code

**Comment by clintongormley** [comment]
Related to https://github.com/elastic/elasticsearch/issues/12366

**Comment by jpountz** [comment]
cc @elastic/es-search-aggs
