### ISSUE TITLE
Shadow replica documentation

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/elasticsearch#11497]
I think the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-shadow-replicas.html) could use some clarification:

* Suggest that node.enable_custom_paths: true has some security implications (according to #8819)
* In the example it sets the data_path for the my_index index to /var/data/my_index. I found this a bit misleading, as it implies the path should contain the index name, but Elasticsearch will already include this in subdirectories, ie. would create /var/data/my_index/*/my_index in the example

**Comment by dakrone** [comment]
Related to #12729 and #12776
