### ISSUE TITLE
Provide a way for rescore to periodically check for timeouts/cancellation

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#114955]
### Description

Plugin authors and us may be doing a ton of heavy compute work in rescore. However, there is no simple way to check if the original caller is still listening (e.g. did the parent task get cancelled), or if the search has timed out. 

We should provide a way to periodically check for cancellations and timeout. Additionally we should add such checks to our more compute intensive rescoring. 

 - [ ] Add ability to check if the request should be cancelled or timedout
 - [ ] Add periodic checks for the QueryRescorer when it scores documents (this might be slightly difficult and require us to wrap some Lucene related things).
 - [ ] Adjust `LearningToRankRescorer` to periodically check for this during is run

**Comment by benwtrent** [comment]
I am thinking one way to do this is to add something to `RescoreContext` something that Elasticsearch can call outside of the plugins and provide an `cancellationSupplier` check. Basically, the same thing that is sitting in `ContextIndexSearcher`

`RescoreContext::setCancellationSupplier(Supplier<void> checkIsCancelled)`

Then `RescoreContext` can check if something is cancelled or not periodically during its compute.

**Comment by dnhatn** [comment]
Could we periodically check for cancellations after rescoring each document in QueryRescorer? We could perform this check in the `combine` method.
