### ISSUE TITLE
Provide a list of all settings

### ISSUE THREAD

**Issue by salyh** [elastic/elasticsearch#11504]
Provide a comprehensive complete list of **all** settings for each es version like https://gist.github.com/jprante/7dccffa7f0c0c7576fa9 does for 1.2

**Comment by jpountz** [comment]
This would certainly be useful. One issue is that the way we manage settings makes it hard to have a centralized place with the list of all settings so this would require some refactoring...

**Comment by clintongormley** [comment]
Related to #6732

**Comment by clintongormley** [comment]
Also, I think that each setting should have an explanation next to it.  And we need to add a test to throw an exception if a new setting is not documented.

**Comment by j0hnsmith** [comment]
Django has a good example https://docs.djangoproject.com/en/1.8/ref/settings/

**Comment by clintongormley** [comment]
With #6732 on the verge of being finished (including the ability to return default settings), we're finally in a place where we can do this.

**Comment by dakrone** [comment]
This is available with the `?include_defaultls` option, but since that doesn't include documentation for the settings, it might be good to add it to the documentation.

**Comment by geekpete** [comment]
Some other things that'd be great to include in such docs might be:

- min value
- max value
- units that the values are in

**Comment by jasontedor** [comment]
We do not think we should do this. See discussion in #26251 and #33741. Closing.
