### ISSUE TITLE
./bin/elasticsearch M3 JDK ERROR

### ISSUE THREAD

**Issue by Changgf** [elastic/elasticsearch#115044]
### Elasticsearch Version

8.15.2

### Java Version

_bundled_

### OS Version

M3

### Problem Description

![Image](https://github.com/user-attachments/assets/cc8539ad-2860-44cc-8aa8-9a9a5ea01da8)

### Steps to Reproduce

 ./bin/elasticsearch

**Comment by pxsalehi** [comment]
Please provide more details, and what the issue is.

**Comment by pxsalehi** [comment]
I'll close this. Feel free to re-open with more details about where you've download ES from, and what the exact issue is.
