### ISSUE TITLE
ElasticsearchIllegalStateException when field's value is big integer.

### ISSUE THREAD

**Issue by thihy** [elastic/elasticsearch#11508]
In mapping, the type of  field `name` is `string` . I put a document:
```
{
  "name":123456789123456789123456789123456789123456789123456789
}
```

It's OK. 

But when I search and highlight:
```
{
  "query":{
     "match_all":{}
 },
  "highlight":{
     "fields:{
        "name":{}
    }
  }
}
```
I get a excepton: `ElasticsearchIllegalStateException[No matching token for number_type [BIG_INTEGER]]` .

The call chain is `AbstractXContentParser#map()` -> `AbstractXContentParser#readMap()` ->  `AbstractXContentParser#readValue()` -> `JsonXContentParser#numberType()` .

**Comment by eabovsky** [comment]
I am experiencing this issue, as well.

**Comment by megastef** [comment]
+1 
curl -XPOST 'localhost:9200/test_number/doc/1' -d '{
 "name" : "test document",
 "test_int" : 129813493927432849126469276498264619863246932642169846316469
}'

{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse"}],"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_state_exception","reason":"No matching token for number_type [BIG_INTEGER]"}},"status":400}
