### ISSUE TITLE
ESQL: Add example with triple-quotes under grok and dissect for easy escaping

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#115051]
### Description

A common issue for folks using dissect and grok is dealing with `\` and other characters in regular expressions.
ESQL already supports [triple quotes `"""` ](https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-syntax.html#esql-string-literals) for such scenarios.
Let's improve the grok/dissect documentation by pointing out this capabilities and show a few examples.

**Comment by luigidellaquila** [comment]
We'll need the same for LIKE/RLIKE
