### ISSUE TITLE
ESQL: Use filters by default when calling fields caps

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#115053]
### Description

Currently, calls to field caps API don't use a filter in order to get access to all data and not avoid false negatives - however this is expensive since the entire mapping has to be read.
To improve performance we can use an optimistic approach by invoking the API with an index filter and, in case not all fields are found issue a second call without a filter.
Overall this will be more expensive than one call however we're estimating that:
1. the first call will succeed more often than not
2. the first call will be cheaper
3. the delta between the first and second call, gives us insight around the fields that are excluded by the filter, information that can be used at planning time.

**Comment by astefan** [comment]
Implemented with https://github.com/elastic/elasticsearch/pull/116755
