### ISSUE TITLE
Worker-json.js not found

### ISSUE THREAD

**Issue by DigiAngel** [elastic/elasticsearch#11525]
Topic says it...when attempting to edit a Saved Search I get:

Error: Script file not found: worker-json.js (:0)

This is kibana-4.0.2-linux-x86.tar.gz downloaded just this morning.

**Comment by colings86** [comment]
@DigiAngel This is a Kibana issue so I have moved it to the Kibana issues list. You can track the new issue here: https://github.com/elastic/kibana/issues/4137
