### ISSUE TITLE
JVM running elasticsearhc gets stuck in GC loop on Haswell nodes

### ISSUE THREAD

**Issue by smorovic** [elastic/elasticsearch#11526]
Hi,

Our farm consists of ~ 900 Linux nodes with elasticsearch configured to use 1 GB heap, locked memory and these parameters (apart from enabling GC logging):
-XX:NewSize=500m -XX:MaxNewSize=600m" 

Roughly half of the cluster are recently purchased (Haswell architecture, 12x2 cores dual socket E5-2680 with 64 GB RAM). We are running Scientific Linux 6.6, which is a RHEL6 equivalent.

Only on these nodes we experience random lockups seen as very long GC where virtually all CPUs are spinning endlessly and never get out of that loop.

There is a way to get the process out of this by either attaching and detaching debugger (or runnning gstack against the process). Then the GC finally finishes, printing a very large elapsed time.
See for example:

2015-06-06T02:10:54.752+0200: 659391.663: [GC (Allocation Failure)  658250K->167958K(987136K), 0.0734349 secs]

2015-06-06T02:25:42.360+0200: 660279.271: [GC (Allocation Failure)  659441K->167230K(987136K), 25788.3097757 secs]

2015-06-06T09:35:41.052+0200: 686077.962: [GC (Allocation Failure)  658735K->202317K(987136K), 0.0538601 secs]

Elasticsearch version is 1.4.2, but I don't think that it is relevant in this case. Initially we used java-1.7.0-openjdk (v75). We now migrated to java-1.8.0-oracle-headless v45, and the problem persists.

We don't have much memory prssure on nodes, and no unusual patter appears with long GC as above.
Perhaps we are hitting JVM, or even Linux, or evne hardeware bug here?

ps -L shows many, usually O(10-30) threads using a lot of CPU, most likely in GC. 

Essentially we are posting it here to share out problem, in case someone else has seen this problem, or if we could be pointed to better methods to investigate (gdb is not very helpful since it "fixes" the problem).

**Comment by mikemccand** [comment]
Is it possible you are hitting http://www.infoq.com/news/2015/05/redhat-futex ?  Also a scary Linux, Haswell-only bug.

But, it doesn't sound like you can un-stick the process when that bug strikes...

**Comment by smorovic** [comment]
Hi,
Thanks for this info. It's possible that this is the case. I am not sure how SLC6 kernel version numbering corresponds to RedHat, but I will check this with sysadmins if we're affected (our kernel is 2.6.32-504.3.3.el6.x86_64).

Yes, unstacking always seem to work. In fact it is simpler (qucker) to do it using gstack. I supposed that it is a synchronisation problem, so if trapping threads enforces synchronisation, it gets them out of that loop. Also they actually use a lot of CPU (spin over the lock I guess..).

**Comment by clintongormley** [comment]
@smorovic have you managed to confirm whether this is the futex bug yet?

**Comment by smorovic** [comment]
Hi,
We suffer from exactly the same symptoms as described here, so apparently it is a futex bug (we will however update out machines with a new kernel next week). I'll close it. Thanks!
