### ISSUE TITLE
ESQL: ability to push down filter past `STATS` yields different result

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#115281]
Executing this query: `FROM employees | STATS v = VALUES(emp_no) by job_positions | WHERE job_positions == "Accountant" | MV_EXPAND v` returns:

```
       v       | job_positions 
---------------+---------------
10025          |Accountant     

```
In this case, the filter is pushed down to source, but through the `esql_single_query` query, so only SV `emp_no` matches (in this case the one doc with `emp_no` == 10025).

However, a semantically identical query: `FROM employees | STATS v = VALUES(emp_no) by job_positions | MV_EXPAND v | WHERE job_positions == "Accountant"` returns a different result:
```
       v       | job_positions 
---------------+---------------
10001          |Accountant     
10012          |Accountant     
10016          |Accountant     
10023          |Accountant     
10025          |Accountant     
10028          |Accountant     
10034          |Accountant     
10037          |Accountant     
10044          |Accountant     
10045          |Accountant     
10050          |Accountant     
10051          |Accountant     
10066          |Accountant     
10081          |Accountant     
10085          |Accountant     
10089          |Accountant     
10092          |Accountant     
10094          |Accountant     
```

The filter isn't pushed through `esql_single_query` and the agg will execute on SV and MV `emp_no`, so will yield different result.

**Comment by bpintea** [comment]
Related to https://github.com/elastic/elasticsearch/issues/115282, which exhibit the same result difference, but there due to the RENAME preventing the filter pushdown.

**Comment by alex-spies** [comment]
Nice find!

Maybe the correct way to push this down would use an `ANY` operator (which we don't have, yet):
```
FROM employees | STATS v = VALUES(emp_no) by job_positions | WHERE job_positions == "Accountant"

->

FROM employees | WHERE ANY job_positions == "Accountant" | STATS v = VALUES(emp_no) by job_positions | WHERE job_positions == "Accountant"
```
Then we'd have to push down `WHERE ANY job_positions == "Accountant"` in a way that permits multivalues.

**Comment by luigidellaquila** [comment]
Another option (yet suboptimal compared to a possible `ANY` operator), is to add an MV_EXPAND:

```
FROM employees 
| MV_EXPAND job_positions
| WHERE job_positions == "Accountant"
| STATS v = VALUES(emp_no) by job_positions 
```

**Comment by craigtaverner** [comment]
Since `BY job_positions` does an implicit `MV_EXPAND` on the grouping key, the option of adding the `MV_EXPAND job_positions` during predicate pushdown sounds like the correct solution. Supporting a hidden `ANY` sounds nice, but also feels like something we should do as part of true `ANY` operator support, so we know the complete scope and consequences.

**Comment by alex-spies** [comment]
I noticed that `BY job_positions` not only performs an expansion, but also deduplication.

So, without further knowledge about the single-valuedness of the field, the correct pushdown using `MV_EXPAND` also needs to use `MV_DEDUPE`:
```
FROM employees 
| EVAL job_positions = MV_DEDUPE(job_positions)
| MV_EXPAND job_positions
| WHERE job_positions == "Accountant"
| STATS v = VALUES(emp_no) by job_positions 
```

**Comment by WeiTanZzz** [comment]
Thanks for all solution, help me a lot!
