### ISSUE TITLE
Near Real Time Updates

### ISSUE THREAD

**Issue by rrphotosoft** [elastic/elasticsearch#11528]
Hi,
My question relates to the near real time nature for updates.

Assume that I set a refresh interval of 1 min.

I index a document with a single field of type integer, that looks like this:
{
  "age":10
}

I am returned the following id: 'AU3LAx8AleL5uDCGX0DQ'

I will not be able to see this document for 1 min for any search requests.

However, within this 1 min, suppose I do an update on this document, with the following script.

ctx._source.age += age_pr
Where age_pr is reference to an 'age' parameter = 3.

What should I expect to see after a minute?
10 or 13 or 3.

I ask because I plan to be deploy a relatively large cluster with multiple shards and indices(distributed) and do not know what I can expect in the above scenario.

Regards,
Bhargav.

**Comment by dadoonet** [comment]
Please ask this on the mailing list: discuss.elastic.co.

I think it should be 13. A GET will also give 13 before the end of this minute BTW.

Closing. Not an issue.
