### ISSUE TITLE
similarity model is not parsed at mappings

### ISSUE THREAD

**Issue by aimeida** [elastic/elasticsearch#11529]
Dear ES developers, I have been troubled by this issue for two days -- really need help
it's about use custom similarity module in ES. 
I wrote my own SimilarityProvider module as here, https://github.com/aimeida/tryES2/tree/master/src/main/java/com/unsilo/paysim
compiled it to a jar file and throw to ES lib path. 

then I try send the following index:

```javascript
PUT /test
{
  "settings" : {
  "similarity" : {
    "my_similarity1" : {
       "type": "com.unsilo.paysim.index.PayWeightSimilarityProvider"
      },
    "my_similarity2" : {
          "type" : "DFR",
          "basic_model": "g",
            "after_effect" : "l",
            "normalization" : "h2",
            "normalization.h2.c" : "3.0"
      }
  }
  }
}

PUT /test/docs/_mapping
{
      "properties" : {
        "content" : {
          "type": "string",
          "similarity" : "my_similarity2"
        }
      }
}
```

everything works fine. Now I want to see the mappings that has been parsed, 
```javascript
GET /test/_mappings
```
gives me the right results (note that my_similarity2 is part of the ES similarity modules)
```javascript
 {
   "test": {
      "mappings": {
         "docs": {
            "properties": {
               "content": {
                  "type": "string",
                  "similarity": "my_similarity2"
               }
            }
         }
      }
   }
}
```
However, when I try to set the mapping using my own similarity modules,
```javascript
PUT /test/docs/_mapping
{
      "properties" : {
        "content" : {
          "type": "string",
          "similarity" : "my_similarity1"
        }
      }
}
```
ES doesn't report any error, so I check the mapping again:
```javascript
GET /test/_mappings
```
It's obvious that my similarity setting is completely ignored!!
```javascript
 {
   "test": {
      "mappings": {
         "docs": {
            "properties": {
               "content": {
                  "type": "string"
               }
            }
         }
      }
   }
}
```
I really don't understand what happens... the settings seems to be right
```javascript
{
   "test": {
      "settings": {
         "index": {
            "creation_date": "1433694379354",
            "number_of_shards": "5",
            "number_of_replicas": "1",
            "version": {
               "created": "1050199"
            },
            "uuid": "0v33M9g5TYaKVWxymyhNLQ",
            "similarity": {
               "my_similarity1": {
                  "type": "com.unsilo.paysim.index.PayWeightSimilarityProvider"
               },
               "my_similarity2": {
                  "basic_model": "g",
                  "type": "DFR",
                  "normalization": "h2",
                  "normalization.h2": {
                     "c": "3.0"
                  },
                  "after_effect": "l"
               }
            }
         }
      }
   }
}
```
I haven't been able to run ES in debug mode yet, so can't figure out what is wrong. Moreover, I also tried writing the similarity module as a plugin, the same thing happens -- ES doesn't register(properly) or call my module at all...

Please share your opinions and ideas !

**Comment by brwe** [comment]
I think you are missing an @Assisted annotation here https://github.com/aimeida/tryES2/commit/b8e521846b1ddb3d71d7817719869f047722e10e#commitcomment-11582316 and therefore the name is not picked up. 
Can you confirm this fixes the problem?

I wonder if we can automatically check for unannotated parameters like in https://github.com/elastic/elasticsearch/pull/10763/ but need to understand guice better first.

**Comment by aimeida** [comment]
Thanks ! problem solved !
