### ISSUE TITLE
 there possible delete before the same field data in every week?

### ISSUE THREAD

**Issue by zcola** [elastic/elasticsearch#11530]
Insert one data, `" @ timestamp, score: 80, ip: 192.8.8.8 "`, later time insert multiple pieces of data, including one for, `" @ timestamp, score: 90, ip: 192.8.8.8 "`, and for the same week, there possible delete before the same week` "ip: 192.8.8.8" `record?

**Comment by clintongormley** [comment]
Hi @zcola 

Please ask questions like these on the forum instead: https://discuss.elastic.co/c/elasticsearch

thanks
