### ISSUE TITLE
Default english stemmer uses obselete algorithm from 1980

### ISSUE THREAD

**Issue by rboulton** [elastic/elasticsearch#11541]
I've just noticed https://github.com/elastic/elasticsearch/issues/6330 and the associated PR https://github.com/elastic/elasticsearch/pull/6452. I noticed this because on upgrading the install of elasticsearch on www.gov.uk searches including the word "news" started returning results containing only the word "new".

The changes between porter2 and porter are relatively small in terms of the number of words affected, but include changes to fix some pretty common problems like this based on observation of probems with the algorithm in 20 years of production systems.  In general the problems fixed are problems with over-stemming words - conflating too many different forms together.  I know that a lot of people end up using the "light_english" (an alias for "kstem") stemmer, which stems a lot less strongly, and I suspect part of the reason for that is that they've been using the "porter" stemmer initially instead of the "english" stemmer.

I'd encourage you to consider returning to "porter2" the default algorithm when people ask for english (perhaps at elasticsearch 2.0 for compatibility reasons), because it really is quite noticeably better for result quality.  We made "porter2" the algorithm returned when snowball is asked for an english stemmer for this reason.

Martin Porter's opinion last time I talked to him about this (and also my opinion) is that the "porter" algorithm is significantly worse than the "porter2" algorithm.  The only reason we kept the "porter" algorithm in snowball is that a lot of academic evaluations have historically been done using the "porter" stemmer, and it's convenient for them to be able to use the same algorithm for new tests for accurate comparison of results.  I would never deliberately use "porter" in a production system.

**Comment by rmuir** [comment]
> I'd encourage you to consider returning to "porter2" the default algorithm when people ask for english (perhaps at elasticsearch 2.0 for compatibility reasons), because it really is quite noticeably better for result quality.

Unfortunately, its also like twice as slow. Last time i benchmarked, the default porter (non-snowball, just the java impl) has a 2x overall indexing performance advantage, so overall I think we make the right tradeoff.

**Comment by rboulton** [comment]
The snowball stemmers do tend to have a significant speed overhead compared to hand-coded algorithms, yes - I can believe a 2x speed difference for the actual stemming call.  I wouldn't have expected the cost of stemming to be a significant part of the total indexing speed, though.

Perhaps a bit of work on improving the speed on the porter2 algorithm would be worthwhile.  I don't believe it's had any significant effort put in to performance tuning, so there's probably some very easy gains there.

**Comment by rmuir** [comment]
> I wouldn't have expected the cost of stemming to be a significant part of the total indexing speed, though.

Yeah, I did this a while ago and afterwards actually spent time with snowball and tried to speed it up (and had some success). So lucene's snowball code has already diverged from snowball repository itself: perhaps there must be different performance goals in mind? What other explanation for things like (https://github.com/snowballstem/snowball/blob/master/java/org/tartarus/snowball/SnowballProgram.java#L31-L37)? Sorry that kind of thing is just terrible for performance :)

To me, IR is like, the main reason you'd use a stemmer, I'd be happy to try to fold this stuff back into snowball and improve the performance. But IIRC there were some api changes needed too (maybe some stuff moved from string -> charsequence), and I am confused about the status of snowball.

**Comment by rmuir** [comment]
to me the most promising approach could be: take the current PorterStemmer.java and create a Porter2Stemmer.java (still hand-written, just reflecting the changes). Its not very sexy but currently the hand-written code just performs much better. And its easy to test it against the snowball compiled version for correctness.

**Comment by rboulton** [comment]
The reason for things like that which are terrible for performance is that those lines of code were written 11 years ago (when I readily admit I had little experience with trying to write performant Java) with an aim of getting something working, and never revisited to improve performance. Take a look at Lucene code from the same time and you'll find some similar shockers! As I say, I'm sure there's lots of scope for improving performance.

The approach of hand writing a Porter2Stemmer.java is reasonable, using the snowball code as a reference implementation. Though it would be nicer to improve the snowball code generator so that non-english stemmers got the benefit too, the code generator is rather hard to work with, being a translation of a code generator for C, and written in not-very clean C.

What _is_ well documented here is the algorithm, and in particular the differences between porter and porter2.

**Comment by rmuir** [comment]
Yeah, I guess to me given the stated differences of 5% of words impacted, and reading through the documentation, it just doesn't seem particularly crucial. I guess in my opinion, english is messy and exceptions like news can be handled with exceptions, which we let the user do easily independent of the stemmer. Any IR tests i have done have shown no significant difference, but the performance is pretty important.

**Comment by rboulton** [comment]
The 5% of words which are affected tend to be more frequently encountered words (because the changes were made based on frequently reported problems), so the changes have more effect than might be thought.  I agree that an exception list is a good idea (we have one for gov.uk here https://github.com/alphagov/rummager/blob/master/config/schema/stems.yml, for example); it just seems better to use the best starting point available.

Out of interest, have you done IR tests comparing something like kstem to porter (1 or 2), and have those shown any significant difference?  (Also, comparing to not stemming at all?)

In any case, I think your performance arguments are quite solid; I have different views of the relative importance of quality and speed (mainly because I'm currently working on a pretty small dataset, but one where result quality is paramount), so I'm probably not going to agree with your choice of default.

In order not to clog your tracker up with open issues, I'll close this ticket now - thank you for your feedback. If I ever get time to do performance improvements on the "porter2" stemmer (either to the code generator, or by hand-coding one), I'll try and push that into Lucene and open a new ticket, because other than the speed I think we've agreed on twitter that porter2 is better than porter (though agreeing whether either is good is a different question!).

**Comment by rmuir** [comment]
> Out of interest, have you done IR tests comparing something like kstem to porter (1 or 2), and have those shown any significant difference? (Also, comparing to not stemming at all?)

Yes. kstem has never done well in my tests. Porter does well. just removing plural/possessive also works reasonable too. I think the "weak porter" that terrier has is also interesting (but have not tested myself). Usually improvements are small (<= 15%) vs. not stemming with english: to me that's expected. I don't read too far into this stuff, but when i see consistent patterns across several corpora, i start to feel consensus :)

**Comment by rboulton** [comment]
Thanks for that datapoint; interesting.
