### ISSUE TITLE
Allow number_of_shards to be set via API

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#11548]
Currently the only way to set `index.number_of_shards` is via the elasticsearch.yml file, if you try to set this via the API it doesn't work;
```
$ curl -XPUT 0:9200/_cluster/settings -d '{ "persistent": { "index.number_of_shards": 5}}'
{"acknowledged":true,"persistent":{},"transient":{}}
$ curl 0:9200/_cluster/settings
{"persistent":{"discovery":{"zen":{"minimum_master_nodes":"1"}}},"transient":{}}
```
And this is reported in the log;
```
[2015-06-09 09:30:44,854][WARN ][action.admin.cluster.settings] [cluster] ignoring persistent setting [index.number_of_shards], not dynamically updateable
```

It seems like a bit of a gap between forcing a user to either set this on each node, which can potentially result in different values across nodes, or using a template, which may get confusing as well.

Is there any reason we cannot allow this to be set via a call to `_cluster/settings`?

**Comment by clintongormley** [comment]
To be clear, this is about setting the default number of shards in a new index, which currently is only settable in the config. You can already do this using index templates.

What we should actually do is remove this setting from the config.

**Comment by clintongormley** [comment]
The solution here is to set up an index template that matches all indices.
