### ISSUE TITLE
(Health API) Shard sizes above 50GB

### ISSUE THREAD

**Issue by stefnestor** [elastic/elasticsearch#115452]
### Description

👋 Elasticsearch recommends [aiming for shards 10-50GB](https://www.elastic.co/guide/en/elasticsearch/reference/current/size-your-shards.html#shard-size-recommendation). Kindly consider adding a [Health API](https://www.elastic.co/guide/en/elasticsearch/reference/current/health-api.html#health-api-response-details-shards-capacity) for shards (egregiously) falling above recommendation. 

For example, not flag `redacted-01`, maybe-but-probably-not flag `redacted-02`, but please flag `redacted-03`: 
```diff
# GET _cat/shards?v
index        shard prirep state       docs   store ip             node
redacted-01  0     r      STARTED 64990325  34.2gb 10.172.166.107 instance-0000000011
redacted-02  1     p      STARTED 62935614  53.2gb 10.174.10.53   instance-0000000012
- redacted-03  1     p      STARTED 96426187 117.7gb 10.174.10.53   instance-0000000012
```

Resolution was added into above linked doc via https://github.com/elastic/elasticsearch/pull/111254 so needed resolution content exists, we would just need Elastic to flag notice to users. 🙏

**Comment by DaveCTurner** [comment]
I don't think we should consider a 100+GiB shard as a _health_ problem, i.e. one that should trigger an alert requiring some level of urgent attention from the user. It's more of an advisory point related to fine-tuning the user's cluster, and the health API is not set up for identifying that sort of thing today.

**Comment by stefnestor** [comment]
Thanks for the response, @DaveCTurner ! ACK. Just cross-posting for future discussions: Stack Monitoring does alert this ballpark : https://github.com/elastic/kibana/issues/190663 .
