### ISSUE TITLE
failed action with response of 400, dropping action

### ISSUE THREAD

**Issue by PavelPolyakov** [elastic/elasticsearch#11543]
Today I've updated my ES cluster to the ES version 1.5.2 , as well I've updated the logstash to the 1.5.0 .
Ony of my logstash outputs is elasticsearch.

Java version is 1.8.0_45 .

And since today I'm spammed with this kind of messages:
> {:timestamp=>"2015-06-08T23:37:34.955000+0200", :message=>"failed action with response of 400, dropping action: [\"index\", {:_id=>nil, :_index=>\"logstash-2015.06.08\", :_type=>\"yyy\", :_routing=>nil}, #<LogStash::Event:0x36be02ca @metadata={\"retry_count\"=>0}, @accessors=#<LogStash::Util::Accessors:0x1191c365 @store={\"message\"=>\"iii\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-06-08T21:37:31.836Z\", \"host\"=>\"www\", \"type\"=>\"yyy\", \"client\"=>\"qqq\", \"country\"=>\"es\", \"level\"=>\"INFO\", \"data\"=>{\"userUuid\"=>\"zzz\", \"appUuid\"=>\"ppp\", \"tags\"=>#<Java::JavaUtil::ArrayList:0x6e500547>, \"sessionId\"=>\"63784859\", \"login\"=>\"xxx\", \"result\"=>{\"passwordMetadata\"=>{\"name\"=>\"ooo\", \"mask\"=>false}}}}, @lut={\"[message]\"=>[{\"message\"=>\"iii\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-06-08T21:37:31.836Z\", \"host\"=>\"www\", \"type\"=>\"yyy\", \"client\"=>\"qqq\", \"country\"=>\"es\", \"level\"=>\"INFO\", \"data\"=>{\"userUuid\"=>\"zzz\", \"appUuid\"=>\"ppp\", \"tags\"=>#<Java::JavaUtil::ArrayList:0x6e500547>, \"sessionId\"=>\"63784859\", \"login\"=>\"xxx\", \"result\"=>{\"passwordMetadata\"=>{\"name\"=>\"ooo\", \"mask\"=>false}}}}, \"message\"], \"[type]\"=>[{\"message\"=>\"iii\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-06-08T21:37:31.836Z\", \"host\"=>\"www\", \"type\"=>\"yyy\", \"client\"=>\"qqq\", \"country\"=>\"es\", \"level\"=>\"INFO\", \"data\"=>{\"userUuid\"=>\"zzz\", \"appUuid\"=>\"ppp\", \"tags\"=>#<Java::JavaUtil::ArrayList:0x6e500547>, \"sessionId\"=>\"63784859\", \"login\"=>\"xxx\", \"result\"=>{\"passwordMetadata\"=>{\"name\"=>\"ooo\", \"mask\"=>false}}}}, \"type\"], \"message\"=>[{\"message\"=>\"iii\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-06-08T21:37:31.836Z\", \"host\"=>\"www\", \"type\"=>\"yyy\", \"client\"=>\"qqq\", \"country\"=>\"es\", \"level\"=>\"INFO\", \"data\"=>{\"userUuid\"=>\"zzz\", \"appUuid\"=>\"ppp\", \"tags\"=>#<Java::JavaUtil::ArrayList:0x6e500547>, \"sessionId\"=>\"63784859\", \"login\"=>\"xxx\", \"result\"=>{\"passwordMetadata\"=>{\"name\"=>\"ooo\", \"mask\"=>false}}}}, \"message\"], \"[tags]\"=>[{\"message\"=>\"iii\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-06-08T21:37:31.836Z\", \"host\"=>\"www\", \"type\"=>\"yyy\", \"client\"=>\"qqq\", \"country\"=>\"es\", \"level\"=>\"INFO\", \"data\"=>{\"userUuid\"=>\"zzz\", \"appUuid\"=>\"ppp\", \"tags\"=>#<Java::JavaUtil::ArrayList:0x6e500547>, \"sessionId\"=>\"63784859\", \"login\"=>\"xxx\", \"result\"=>{\"passwordMetadata\"=>{\"name\"=>\"ooo\", \"mask\"=>false}}}}, \"tags\"], \"type\"=>[{\"message\"=>\"iii\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-06-08T21:37:31.836Z\", \"host\"=>\"www\", \"type\"=>\"yyy\", \"client\"=>\"qqq\", \"country\"=>\"es\", \"level\"=>\"INFO\", \"data\"=>{\"userUuid\"=>\"zzz\", \"appUuid\"=>\"ppp\", \"tags\"=>#<Java::JavaUtil::ArrayList:0x6e500547>, \"sessionId\"=>\"63784859\", \"login\"=>\"xxx\", \"result\"=>{\"passwordMetadata\"=>{\"name\"=>\"ooo\", \"mask\"=>false}}}}, \"type\"]}>, @data={\"message\"=>\"iii\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-06-08T21:37:31.836Z\", \"host\"=>\"www\", \"type\"=>\"yyy\", \"client\"=>\"qqq\", \"country\"=>\"es\", \"level\"=>\"INFO\", \"data\"=>{\"userUuid\"=>\"zzz\", \"appUuid\"=>\"ppp\", \"tags\"=>#<Java::JavaUtil::ArrayList:0x6e500547>, \"sessionId\"=>\"63784859\", \"login\"=>\"xxx\", \"result\"=>{\"passwordMetadata\"=>{\"name\"=>\"ooo\", \"mask\"=>false}}}}, @metadata_accessors=#<LogStash::Util::Accessors:0x777eb8cf @store={\"retry_count\"=>0}, @lut={}>, @cancelled=false>]", :level=>:warn}

I have no idea how to overcome that. Some messages are ok, and ES accepts them and indexes, but some lead to this message.

Any idea what should I check to make them pass thorough ES?
Why in the error message, the original message takes place several time?

The same topic takes place [inside the logstash ES plugin](https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/144#issuecomment-110072257), but I haven't found a solution there.

Why the ES is dropping the action?

Any hint is appreciated.

Regards,

**Comment by T0aD** [comment]
+1

**Comment by PavelPolyakov** [comment]
I have the next suggestion currently.

My logs doesn't have any mapped format in elasticsearch, they are dynamic.

The log could look like this:
```javascript
{
    message: "message",
    error: false
}
```

and like this

```javascript
{
    message: "message"
    error: {
        message: "Error"
    }
}
```

As soon as 1st log type would hit the elasticsearch, the error field would be mapped as string. Since that time, any of the 2nd type logs would not be accepted. And would produce the error from the topic heading.

Could anyone confirm this?

**Comment by clintongormley** [comment]
Hi @PavelPolyakov 

The `error` field can't be both a string (first example) and an object (second example).  Whichever format is seen first sets the field type, and all documents with the other format are rejected.

You'll need to add a rule to logstash to change the field name of one of the formats.

**Comment by clintongormley** [comment]
The alternative is to map the `error` field as:

    { "type": "object", "enabled": false }

With this mapping, it won't look at the contents of the `error` field at all.  Documents won't be rejected, but of course the `error` (and `error.message`) fields won't be indexed either, and so won't be searchable.

**Comment by BZen** [comment]
I was getting the same error message(failed with a response of 400). I was using json codec in my input. But after I removed it I din't get any errors. It worked fine. Is there a problem with the json codec?? Btw my error logs are so big and I dont think they will help.

**Comment by tlastowka** [comment]
@BZen 
Its probably still a mapping issue.  The first time I saw the 400 error was using the json codec, but it wasn't the codec at fault.  Pipe this through the json codec, and then output to elasticsearch.  First will be fine.  Second will cause an error:

--this will be fine--
{ "gets_mapped_as_string" : "string" }
{ "gets_mapped_as_string" : 1 }

--this will cause an error--
{ "gets_mapped_as_int" : 1 }
{ "gets_mapped_as_int" : "string" }

**Comment by raedsh** [comment]
What fixed my 400 error was changing the index name from all Upper case letters to lower case letters.
Works:
index => "snow-%{+YYYY.MM}"

Errors out:
index => "SNOW-%{+YYYY.MM}"
