### ISSUE TITLE
ESQL: unfolded counting fails with filtered agg

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#115522]
### Description

`FROM employees | STATS c1 = count(emp_no) WHERE emp_no < 10042` will incorrectly disregard the filter. 
(See [cause](https://github.com/elastic/elasticsearch/pull/113735#discussion_r1792685098).)

**Comment by jackpan123** [comment]
@bpintea I try your sql above in CsvTests, like below:
```

unfoldedCountingFails
FROM employees | STATS c1 = count(emp_no) WHERE emp_no < 10042;

c1:long
41
;
```
I tested it three times with c1 using three different values: [40, 41, 42]. The values 40 and 42 resulted in errors, while 41 was correct. Therefore, I believe this issue has been resolved.

**Comment by bpintea** [comment]
> I try your sql above in CsvTests

You'll need to run an IT ("qa") to experience the issue (like single-node). The unit test has some limitations in the way it can replicate a full execution and this particular query hits that, ...

> I believe this issue has been resolved

...which means, this is still open.

**Comment by jackpan123** [comment]
> You'll need to run an IT ("qa") to experience the issue (like single-node). The unit test has some limitations in the way it can replicate a full execution and this particular query hits that, ...

I am little confused about `run an IT ("qa") to experience the issue (like single-node)`, could you provide an example of how to execute it?

And I try another test way, I execute `./gradlew run -Dtests.es.xpack.security.enabled=false` to start local Elasticsearch in my machine and execute Reproducer step write by @alex-spies in your [cause](https://github.com/elastic/elasticsearch/pull/113735#discussion_r1792685098)
```
POST /test/_doc?refresh'
{"a" : 1}

POST /test/_doc?refresh'
{"a" : 2}

POST /test/_doc?refresh'
{"a" : 3}

POST /test/_doc?refresh'
{"a" : 4}

POST /_query
{"query": "from test | stats sum(1) where a > 3"}
```
The query show the result like  like below:
```
{"took":432,"columns":[{"name":"count(*) where a > 3","type":"long"}],"values":[[1]]}%
```
The query return 1 as only 1 row satisfies a > 3. Thus, I am uncertain whether it has been resolved or not.

**Comment by bpintea** [comment]
This no longer fails, adding tests for it in #117180.

**Comment by bpintea** [comment]
Still broken on 8.16.
