### ISSUE TITLE
Documentation Error in https://www.elastic.co/guide/en/enterprise-search/current/connectors-servicenow.html#connectors-servicenow-configuration

### ISSUE THREAD

**Issue by iamhowardtheduck** [elastic/elasticsearch#115587]
### Description

The service name for Change Request should be instead "Change request", using as our documentation describes results in an error and no documents are synced.

https://www.elastic.co/guide/en/enterprise-search/current/connectors-servicenow.html#connectors-servicenow-configuration

**Comment by astefan** [comment]
Hey @iamhowardtheduck, I will label this issue as Docs related, but I think a PR with the change you mentioned would likely speed things up. Would you mind opening a PR for this change?

**Comment by leemthompo** [comment]
Thanks for flagging @iamhowardtheduck! These docs will actually be moving to the Elasticsearch guide in 8.16.0 so they will be publicly editable. In the meantime I'll fix this one. :)
