### ISSUE TITLE
Always allocate primaries first during recovery

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#11550]
During recovery users can set `cluster.routing.allocation.enable` to only allow primaries to be allocated (recovered).

Currently if this is set to `all` we will do any primaries for an index, but in large clusters we have seen instances where instead of recovering the next unallocated primary, we work on the replica of a now allocated primary.

This obviously delays the progress in getting a cluster back to a green state and we should always be treating primaries as first class at all times. It'd be good if the default behaviour here was to recover all primaries first and then move to replicas as applicable.

**Comment by bleskes** [comment]
The master should allocate primaries first, based on the current allocation restrictions (maximum recoveries per node). Once all possible primaries are assigned (but not per-se started) it proceeds to allocate any replicas if possible. This repeats it self with any change to the current status (shard started/failed/node joined etc.). Can you give some more information about what happened?

**Comment by kimchy** [comment]
primaries today are allocated first, and only when the limit is reached (as per Boaz note) we will go and try and allocate replicas. I suspect that this came from the sync nature of remote listing of shards during allocation which is a problem with very slow file systems, so this will become a non issue in 1.6 (well, the file system will still be slow, but it won't cause perceived notions of hiccups on the master)

**Comment by markwalkom** [comment]
Great, thanks both for the comments :)
