### ISSUE TITLE
Fix argument parsing on startup

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#11552]
Currently our argument parsing on startup is very brittle, without the possibility to exit on problems (for example when including a space in a path, many other arguments might break as well and es still starts up)

The used `getopt` function fails on whitespaces, which is also mentioned in its manpage. There does not seem to be any fix for this. The alternative would be to call `getopts` (note the `s`) which has an improved parsing and is also supported by the common shells (even dash under ubuntu). However, the problem is our parsing is much more than simple getopt parsing. We support the following

* long options like `--network.host 127.0.0.1` must be supported and converted to a JVM system property `-Des.network.host=127.0.0.1`
* system properties like `-Dfoo.bar=spam` must be supported

The `getopts` parser does not support the last syntax, when spaces are involved, because the key is not supposed to be `foo.bar`, but `-D`. The `commons-cli` has support for this as well, and we already include it.

In order to simplify this handling and make it testable I think it makes sense to get rid of the parsing in the shell/bat scripts and do this in java. A couple of solutions come to mind here (one of the key features needs to be speed, calling `bin/elasticsearch -v` should still be fast.

* Have a very small class, that parses the getopts arguments and exits on parsing problems. If parsing is successful, call the `Bootstrap` class
* Put everything in the bootstrap class
* Have a small main class that parses all arguments, that then fires up another JVM (Tika is doing this, the call it a forked parser). The interesting approach about this one might be, that we could actually configure the heap size in the `elasticsearch.yml` file as well
* If we do not want to go this route, we may want to think about ditching a lot of our options...

**Comment by clintongormley** [comment]
It definitely sounds like the parsing should be done in java land.  I like the idea of being able to configure the heap size in the config file, but would be interested to hear what @rmuir thinks about this approach.

**Comment by rmuir** [comment]
I like the testability aspect, but keep in mind that executing processes from java has its own set of different problems. For example instead of whitespace being a problem, then it will be non-ascii paths from processbuilder (maybe only on windows) or whatever.

As far as bootstrap, personally i would prefer if "forking" was somewhere else. Or rather if we call this part bootstrap then if the current bootstrap logic was moved. Its already kind of a mess and really complicated stuff, if we can keep the forking part separate it would prevent it from being more confusing.

**Comment by clintongormley** [comment]
Argument parsing has been fixed and we've decided against the forking option. Closing
