### ISSUE TITLE
Sub Aggregations in parent-child relationship on field value

### ISSUE THREAD

**Issue by vineet85** [elastic/elasticsearch#11555]
Hi,

I have a parent child mapping in the following format:-
The children are linked to the parent based on the _id field in this case

Parent:-

    POST http://localhost:9200/_bulk
    { "index" :  {"_index":"estester","_type":"document","_id":"00005777b25343f0b7c03e54c0411c1b"} }
    {}

Children:-

    POST http://localhost:9200/_bulk
    {
        "index": {
            "_index": "estester",
            "_type": "documentmetadatavalue",
            "_parent": "00005777b25343f0b7c03e54c0411c1b"
        }
    }
    {
        "fieldid": "DOCUMENT_GUID",
        "fieldvalue": [
            "00005777b25343f0b7c03e54c0411c1b"
        ],
        "parent": "00005777b25343f0b7c03e54c0411c1b"
    },
    {
        "fieldid": "FILETYPE",
        "fieldvalue": [
            "PDF "
        ],
        "parent": "00005777b25343f0b7c03e54c0411c1b"
    },
    {
        "fieldid": "CREATEDDATE",
        "fieldvalue": [
            "06/08/2015"
        ],
        "parent": "00005777b25343f0b7c03e54c0411c1b"
    }

I'm trying to create sub-aggregations which are 2 levels deep based on the fieldid:- CREATEDDATE and FILETYPE.

However the aggregation below fails to create child buckets more than 1 level deep:-

    GET /estester/documentmetadatavalue/_search?search_type=count
    {
        "size": 100,
        "aggs": {
            "field_aggregation": {
                "filter": {
                    "term": {
                        "fieldid": "CREATEDDATE"
                    }
                },
                "aggs": {
                    "field_aggregation_values": {
                        "terms": {
                            "field": "fieldvalue.original",
                            "size": 0
                        },
                        "aggs": {
                          "field_aggregation": {
                              "filter": {
                                  "term": {
                                      "fieldid": "FILETYPE"
                                  }
                              },
                              "aggs": {
                                  "field_aggregation_values": {
                                      "terms": {
                                          "field": "fieldvalue.original",
                                          "size": 0
                                      }
                                  }
                              }
                          }
                        }
                    }
                }
            }
        }
    }

Response:-

    {
       "took": 8,
       "timed_out": false,
       "_shards": {
          "total": 5,
          "successful": 5,
          "failed": 0
       },
       "hits": {
          "total": 196,
          "max_score": 0,
          "hits": []
       },
       "aggregations": {
          "field_aggregation": {
             "doc_count": 4,
             "field_aggregation_values": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": [
                   {
                      "key": "02/27/2015",
                      "doc_count": 1,
                      "field_aggregation": {
                         "doc_count": 0,
                         "field_aggregation_values": {
                            "doc_count_error_upper_bound": 0,
                            "sum_other_doc_count": 0,
                            "buckets": []
                         }
                      }
                   },
                   {
                      "key": "05/15/2015",
                      "doc_count": 1,
                      "field_aggregation": {
                         "doc_count": 0,
                         "field_aggregation_values": {
                            "doc_count_error_upper_bound": 0,
                            "sum_other_doc_count": 0,
                            "buckets": []
                         }
                      }
                   },
                   {
                      "key": "06/08/2015",
                      "doc_count": 1,
                      "field_aggregation": {
                         "doc_count": 0,
                         "field_aggregation_values": {
                            "doc_count_error_upper_bound": 0,
                            "sum_other_doc_count": 0,
                            "buckets": []
                         }
                      }
                   },
                   {
                      "key": "06/09/2015",
                      "doc_count": 1,
                      "field_aggregation": {
                         "doc_count": 0,
                         "field_aggregation_values": {
                            "doc_count_error_upper_bound": 0,
                            "sum_other_doc_count": 0,
                            "buckets": []
                         }
                      }
                   }
                ]
             }
          }
       }
    }

**Comment by clintongormley** [comment]
Hi @vineet85 

You've uploaded half a recreation which is missing a bunch of stuff.  I can't tell where the problem is without a working example. Please could you update.

**Comment by vineet85** [comment]
Sorry - here is the complete mapping and steps to re-create:-

Mapping:-
{
  "settings": {
    "index": {
      "number_of_replicas": 1,
      "number_of_shards": 5,
      "analysis": {
        "analyzer": {
          "customfieldvalue": {
            "tokenizer": "whitespace",
            "filter": [
              "lowercase"
            ],
            "type": "custom"
          },
          "customfullText": {
            "tokenizer": "standard",
            "filter": [
              "lowercase",
              "porter_stem"
            ],
            "type": "custom"
          },
          "customfullTextExact": {
            "tokenizer": "whitespace",
            "type": "custom"
          }
        }
      }
    }
  },
  "mappings": {
    "document": {
      "_all": {
        "enabled": false
      },
      "properties": {}
    },
    "documentmetadatavalue": {
      "_source": {
        "enabled": true,
        "excludes": [
          "fulltext"
        ]
      },
      "_all": {
        "enabled": false
      },
      "_parent": {
        "type": "document"
      },
      "properties": {
        "fieldid": {
          "index": "not_analyzed",
          "doc_values": true,
          "type": "string"
        },
        "fieldvalue": {
          "type": "multi_field",
          "fields": {
            "fieldvalue": {
              "analyzer": "standard",
              "type": "string"
            },
            "original": {
              "index": "not_analyzed",
              "doc_values": true,
              "type": "string"
            },
            "stemmed": {
              "analyzer": "english",
              "type": "string"
            },
            "exact": {
              "analyzer": "customfieldvalue",
              "type": "string"
            },
            "date": {
              "index": "not_analyzed",
              "format": "date",
              "ignore_malformed": true,
              "type": "date"
            },
            "integer": {
              "index": "not_analyzed",
              "doc_values": true,
              "ignore_malformed": true,
              "type": "double"
            },
            "boolean": {
              "index": "not_analyzed",
              "type": "boolean"
            }
          }
        },
        "parent": {
          "type": "string"
        },
        "fulltext": {
          "type": "multi_field",
          "fields": {
            "fulltext": {
              "analyzer": "customfullText",
              "type": "string"
            },
            "exact": {
              "analyzer": "customfullTextExact",
              "type": "string"
            }
          }
        }
      }
    }
  }
}

Re-creation:-
POST estester/document/1
{
  
}
POST estester/document/2
{
  
}
POST estester/document/3
{
  
}

POST /estester/documentmetadatavalue/1?parent=1
{
  "parent": "1",
  "fieldid": "CREATEDDATE",
  "fieldvalue": "06/14/2015"
}

POST /estester/documentmetadatavalue/2?parent=2
{
  "parent": "2",
  "fieldid": "CREATEDDATE",
  "fieldvalue": "06/15/2015"
}

POST /estester/documentmetadatavalue/3?parent=3
{
  "parent": "3",
  "fieldid": "CREATEDDATE",
  "fieldvalue": "06/17/2015"
}

POST /estester/documentmetadatavalue/4?parent=1
{
  "parent": "1",
  "fieldid": "FILETYPE",
  "fieldvalue": "Microsoft Word"
}

POST /estester/documentmetadatavalue/5?parent=2
{
  "parent": "2",
  "fieldid": "FILETYPE",
  "fieldvalue": "PDF"
}

POST /estester/documentmetadatavalue/6?parent=3
{
  "parent": "3",
  "fieldid": "FILETYPE",
  "fieldvalue": "text"
}

GET /estester/documentmetadatavalue/_search?search_type=count
{
    "size": 100,
    "aggs": {
        "field_aggregation": {
            "filter": {
                "term": {
                    "fieldid": "CREATEDDATE"
                }
            },
            "aggs": {
                "field_aggregation_values": {
                    "terms": {
                        "field": "fieldvalue.original",
                        "size": 0
                    },
                    "aggs": {
                      "field_aggregation": {
                          "filter": {
                              "term": {
                                  "fieldid": "FILETYPE"
                              }
                          },
                          "aggs": {
                              "field_aggregation_values": {
                                  "terms": {
                                      "field": "fieldvalue.original",
                                      "size": 0
                                  }
                              }
                          }
                      }
                    }
                }
            }
        }
    }
}

**Comment by clintongormley** [comment]
Thanks @vineet85 - You're making a number of mistakes here, but none of them point to bugs in Elasticsearch. A better place to ask this question is in the forum: http://discuss.elastic.co/

thanks
