### ISSUE TITLE
add escaping for JSON response body filtering

### ISSUE THREAD

**Issue by djschny** [elastic/elasticsearch#11560]
Please add the ability to handle escaping for certain characters with the filter_path option. For example to allow the following to work for our common .marvel-* indices.

```
GET _stats?filter_path=indices.\.marvel*
```

**Comment by tlrx** [comment]
I think we should add escaping to the `filter_path` option. Index names or field names can include dots or comma so we need to handle escaping to filter responses on those names.

**Comment by djschny** [comment]
Sorry about the v1.6.0 label. How do we indicate that a particular bug is only for a certain version?

**Comment by javanna** [comment]
hey @djschny no worries! we use versions to indicate when things get fixed, rather than which versions are affected. We actually have no way at the moment to specify which version is affected by a bug.

**Comment by clintongormley** [comment]
Here's a regex that will tokenize properly:

    /(                 # capture either
        (?:            
            [^.,\\]    # any character except a comma, period, or backslash
          | \\.        # or a backslash followed by any character
        )+             # repeated as many times as possible
      | 
        [.,]           # or either a single comma or period
     )
    /x
    

So this string: `indices.\.marvel*.foo\,bar,indices.\.marvel*.\*` would result in the following tokens:

* `indices`
* `.`
* `\.marvel*`
* `.` 
* `foo\,bar`
* `,`
* `indices`
* `.`
* `\.marvel*`
* `.`
* `\*`

Then real asterisks should be separated from escaped asterisks, and then any other escapes should be removed.

**Comment by clintongormley** [comment]
Probably need to support `+` and `-` as well

**Comment by clintongormley** [comment]
Related to https://github.com/elastic/elasticsearch/issues/11334

**Comment by clintongormley** [comment]
In order to handle escaped wildcards, we either need a state machine, or to reuse Lucene's automaton (which creates a lot of objects).  Perhaps we just don't allow escaped wildcards, in which case we can use the simple pattern matching that we have today.
