### ISSUE TITLE
Update REST API documentation with valid examples

### ISSUE THREAD

**Issue by spapin** [elastic/elasticsearch#11571]
One example is cluster stats API:
https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-stats.html

Fields that were recently added do not show up in the sample json response.
Documentation should be up to date with the code.

**Comment by vineelyalamarthy** [comment]
Can I work on this bug, How to get started ?

**Comment by clintongormley** [comment]
@vineelyalamarthy of course - go for it.  See https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md

**Comment by vineelyalamarthy** [comment]
@clintongormley  Thank you so much, may be will ask you, if I have  some questions. Actually, I plan to start few easy ones(Low Hanging Fruit labelled ones), then get some familiarity with it and then get into core ones.
