### ISSUE TITLE
MoreLikeThis Query doesn't work with `just_path` option pre 2.0

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#11573]
the term vector API which is now used to build MLT queries get the term vector potentially from a different field (source) than it's executed against. This will result in empty queries and should be rewritten against it's index name field

**Comment by martijnvg** [comment]
Bumping the version up to 1.7.1 for the release today.

**Comment by clintongormley** [comment]
The `path` parameter has been removed.  Closing
