### ISSUE TITLE
RPM: Allow to create RPM with & without signing

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#11587]
In order to create an RPM for integration tests (as well as centos 5), we need to create an RPM that is not signed when it is built.

This can probably be sovled by having another maven profile with a different RPM configuration, that stores the RPM in a different path. This RPM should be used when uploading in the build release script to S3, the signed one should be used for the repositories.

**Comment by dadoonet** [comment]
@spinscale I think that it should be super easy to solve that once #11523 will be merged.
