### ISSUE TITLE
Remove the usage of the _source.mode mapping attribute from rest integration tests.

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#115860]
The `index.mapping.source.mode` index setting should be used instead.

**Comment by kkrik-es** [comment]
Since it's not clear when we'll remove `_source.mode` entirely, I'm keeping references in `x-pack/plugin/logsdb/src/yamlRestTest/resources/rest-api-spec/test/40_source_mode_setting.yml` to make sure we have testing coverage for it, in combination with `index.mapping.source.mode` index setting.
