### ISSUE TITLE
Must + Should combined in Bool : unexpected result

### ISSUE THREAD

**Issue by Henri85** [elastic/elasticsearch#11581]
I'm using ElasticSearch 1.6.0

I have to combine a must with a should in a bool.
The must filter results 1229 items. Combined with the should filter, I only get 1 result (the item with id 2). It seems that 'should' works as 'must'. But why?

    {
        "query": {
            "filtered": {
                "query": {
                    "match_all": []
                },
                "filter": {
                    "bool": {
                        "must": {
                            "range": {
                                "date": {
                                    "from": "2015-06-28",
                                    "to": "2015-08-08"
                                }
                            }
                        },
                        "should": [
                            {
                                "term": {
                                    "id": 2
                                }
                            }
                        ]
                    }
                }
            }
        }
    }

**Comment by clintongormley** [comment]
With a bool filter, at least one should clause must match (otherwise it is meaningless).  You only have one, so it has to match.

**Comment by Henri85** [comment]
Thanks. I was really confused between bool query and bool filter.

Documentation: https://www.elastic.co/guide/en/elasticsearch/guide/current/_most_important_queries_and_filters.html
