### ISSUE TITLE
ES waiting for observer timeout before failing consistency check

### ISSUE THREAD

**Issue by drewr** [elastic/elasticsearch#11582]
When consistency policy isn't satisfied, rather than bail out in the precheck, we are waiting the default cluster state observer timeout (60s) before sending the error response.  The only way to tell this is happening if you don't have the response is the timeout getting logged, in `DEBUG`:

```
[2015-06-10 09:44:35,628][DEBUG][action.index             ] [Scaleface] observer: timeout notification from cluster service. timeout setting [1m], time since start [1m]
```

On a busy cluster with lots of writes, you will start to see metadata operations slow down even though CPU and memory aren't necessarily getting any pressure.

To reproduce, start a single 1.5.2 node and create an index with more than one replica (so there isn't quorum):

```
curl -s -XPUT localhost:9200/foo -d'---
number_of_shards: 1
number_of_replicas: 2
'
```

Verify topology:

```
% es shards
foo 0 p STARTED    0 115b 10.0.1.200 Scaleface 
foo 0 r UNASSIGNED                             
foo 0 r UNASSIGNED                             
```

Index a doc:

```
curl -s -XPUT localhost:9200/foo/t/1 -d'{"f": 1}'
```

After a minute you'll get:

```
error: "UnavailableShardsException[[foo][0] Not enough active copies to meet write\
  \ consistency of [QUORUM] (have 1, needed 2). Timeout: [1m], request: index {[foo][t][1],\
  \ source[{\"f\":1}]}]"
status: 503
```

It looks like the great refactoring in 5bdfdc42d99b12e7999fb36c8f1a72d43d7b5606 may have switched the behavior?  If that's the correct behavior, maybe we can log something in `ERROR` after `N` indexing requests have failed consistency check?

Here's the same operation with `TRACE`:

```
[2015-06-10 10:08:39,271][TRACE][action.index             ] [Impossible Man] primary shard [[foo][0]] is not yet active or we do not know the node it is assigned to [null], scheduling a retry.
[2015-06-10 10:08:39,279][TRACE][action.index             ] [Impossible Man] observer: sampled state rejected by predicate (version [2], status [APPLIED]). adding listener to ClusterService
[2015-06-10 10:08:39,279][TRACE][action.index             ] [Impossible Man] observer: postAdded - predicate rejected state (version [2], status [APPLIED])
[2015-06-10 10:09:39,272][DEBUG][action.index             ] [Impossible Man] observer: timeout notification from cluster service. timeout setting [1m], time since start [1m]
[2015-06-10 10:09:39,274][TRACE][action.index             ] [Impossible Man] primary shard [[foo][0]] is not yet active or we do not know the node it is assigned to [null], scheduling a retry.
```

**Comment by bleskes** [comment]
> On a busy cluster with lots of writes, you will start to see metadata operations slow down even though CPU and memory aren't necessarily getting any pressure.

Can you clarify what you mean by slowing down? I can think of a scenario where many waiting indexing operations slow down cluster state processing (we try the indexing operation on every cluster state change and can be more efficient.)

> It looks like the great refactoring in 5bdfdc4 may have switched the behavior? If that's the correct behavior,

This behavior has been there from the beginning time, or something very close to it. The rational is that the needed replicas might be assigned soon and it's worth while waiting (think about a newly create index).   Can you sure more around why you think something changed?

> if you don't have the response is the timeout getting logged, in DEBUG
>  maybe we can log something in ERROR after N indexing requests have failed consistency check?


That log message should actually be TRACE as it's may be very high volume (like in your case). I think there is merit to have a logging infra that throttle logging but that would be a separate issue.

**Comment by celesteking** [comment]
started getting same message once server ran out of disk space.

I allocated more, but it didn't go away. Also, cluster is now in red health, which is just plain stupid as the source of problem has been rectified.

**Comment by kamakazikamikaze** [comment]
SImilar to celesteking but Java ran out of memory which required a restart. Logs are now full of this message and server fails to write even 30% of documents sent to it.

**Comment by bachkhoabk47** [comment]
>SImilar to celesteking but Java ran out of memory which required a restart. Logs are now full of this message and server fails to write even 30% of documents sent to it.

Hi Kamakazikamikaze and everybody. 
I'm Tan and I come from Vietnam.
You know, I would like to sent data from Syslog-ng to Elasticsearch with around 1 million message line, but in ES side, I just see 515,007 docs. It means ES just received and processed haft past of the number messages that sent from Syslog-ng.
Of course, I also checked the bandwidth, hdd, ram and cpu. They was working well and just used around 50% their capacity.

Mr.Kamakazikamikaze. I found your comment here and I would like you give me some your experience about that.
Does has any parameters that I have to config for tuning my system?

Thank you very much!

**Comment by clintongormley** [comment]
@bachkhoabk47 This sounds like a question for the forums (http://discuss.elastic.co/) not for the issues list.

**Comment by bachkhoabk47** [comment]
Hi Clintongormley!
Thanks for you feedback. 
I've posted my question to the forums.
Thank you so much

**Comment by bleskes** [comment]
I'm closing this as it isn't clear what actually happened and we've had no feedback for a while.
