### ISSUE TITLE
Support for Lucene Expression scripts in pipeline aggregators

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#11596]
At the moment Lucene Expressions scripts only implement SearchScript and throw an UnsupportedOperationException if you call ExpressionScriptService.executable() or ExpressionScriptService.execute(). The message in the exception says "Cannot use expressions for updates" which is understandable since the language is not built for update operations. However, in the pipeline aggregators we want to be able to use scripts to perform arbitrary calculations on the aggregations responses, which are outside of a search context since they are performed in the reduce phase. It would be great if we can update the ExpressionScriptService to be able to support this.

**Comment by jdconrad** [comment]
After looking at the code, this can't really be accomplished in the short-term.  Expressions is missing numerous features that are specified in the example here (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-scripted-metric-aggregation.html) including if/else blocks (though it does have conditionals), loops, variable assignment, and different types such as strings or ints.  The expressions architecture is built exclusively to support doubles with other numeric values being converted to doubles when used.  Expressions also have no notion of a long-term variable meaning that the variables passed between scripts would have to be coded in as well.  There are simply too many limitations to overcome before the upcoming beta for 2.0.

**Comment by jdconrad** [comment]
@colings86 Also, would you please provide an example aggregation that you're thinking of doing using expressions?  Thanks!

**Comment by jdconrad** [comment]
@colings86 It might be worth looking into what we do with multi-value fields where we allow them have member methods like sum, avg, median, min, and max.  If that could be provided for a single known variable, would that enough for what you're trying to do?

**Comment by jdconrad** [comment]
Just spoke with @colings86 -- My apologies for the misunderstanding, the goal is simply to be able to calculate numeric expressions through an executable script instead of a search script.  I believe this can be done now for the 2.0 beta.  I will always assume that the Objects in the map of vars passed in as <String, Object> will be doubles.
