### ISSUE TITLE
Request to change name of WrapperQueryBuilder (org.elasticsearch.index.query)

### ISSUE THREAD

**Issue by MattFriedmanAfilias** [elastic/elasticsearch#11591]
I spent a considerable time today looking for a query builder that would accept a JSON string query (as per the REST API).

I wonder if the term JSON could be incorporated into the name i.e. JsonWrapperQueryBuilder?

Not a big deal but it wasn't obvious to me despite numerous Google searches and lots of hunting, forum posts etc...

Thanks.

**Comment by javanna** [comment]
I agree that the name is not the best... not sure I would associate it with json specifically though, given that it allows to wrap binary content in general, which could be json, yaml or smile. Maybe XContentQueryBuilder or something along those lines?

**Comment by MattFriedmanAfilias** [comment]
Thanks for this. One idea is to create *alias* methods in QueryBuilders such as (or something like)

    QueryBuilders.jsonWrapperQuery(String)
    QueryBuilders.jsonWrapperQuery(bytes)
    QueryBuilders.yamlWrapperQuery(String)
    QueryBuilders.yamlWrapperQuery(bytes)

etc...

These methods would simply forward the input to the target method: `wrapperQuery()` so they would only exist for clarity.

If you can tolerate these extra convenience methods it might make it easier for someone to locate the method they need.

Or maybe there's a cleaner way someone will think of. Or maybe it is just a documentation thing; I found it hard to locate the method I needed. 

Thanks very much,
Matt

**Comment by clintongormley** [comment]
XContentQueryBuilder is probably no more meaningful than WrapperQuery.  The aliases imply that eg they would convert JSON or YAML into the right format for including in a query, where really this method just injects the raw string...

Probably the best solution is to just document the query builder here: https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/query-dsl-queries.html
