### ISSUE TITLE
Kibana Canvas error if esdocs sort property without sort direction

### ISSUE THREAD

**Issue by dolivanu** [elastic/elasticsearch#116004]
### Elasticsearch Version

8.15.3

### Java Version

_bundled_

### OS Version

Elasticsearch Cloud

### Problem Description

Checked againts Elasticsearch Cloud 8.15.3 and Elasticsearch Onprem 8.14.0. No initial data or configuration required, tested with a fresh Elasticsearch Cloud tenant with no data ingested or configuration applied.

On Kibana, Canvas, select _Create workpad_, _Add element_ : _Data table_, click on the table, click on _Expression editor_, change the default expression:

```
kibana
| selectFilter
| demodata
| table
| render

```
to:

```
esdocs index="metrics-*" count=10 sort="agent.type"
| table
| render

```
Click on _Run_, gives error _Unable to load page_, _Refresh_ loads the page again, but if click on table, raises the same error. Clicking on _Show details_ in the error page states:

```
TypeError: t.renderError is not a function
    at https://my-deployment-XXX.kb.eu-central-1.aws.cloud.es.io/XXXaa/bundles/plugin/canvas/1.0.0/canvas.chunk.12.js:16:13571
    at u (https://my-deployment-XXX.kb.eu-central-1.aws.cloud.es.io/XXXaa/bundles/plugin/canvas/1.0.0/canvas.chunk.7.js:3:17944)
    at la (https://my-deployment-XXX.kb.eu-central-1.aws.cloud.es.io/XXXaa/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:429:59212)
    at ec (https://my-deployment-XXX.kb.eu-central-1.aws.cloud.es.io/XXXaa/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:429:114853)
```
    
The problem is when editing the expression directly on the bottom panel and include a syntax error in `esdocs` property `sort` with only the property name, no including sort direction, `sort="agent.type"` versus `sort="agent.type, desc"`.

You can not edit the table anymore. To solve the issue, you can download the workpad JSON file, remove the sort property entirely and load the workpad again.

Expected behavior: The esdocs sort property with the syntax error should raise a controlled error when pressing _Run_, allowing the user to fix it on the _Expression editor_, as other syntax errors.

### Steps to Reproduce

On Kibana, Canvas, select _Create workpad_, _Add element_ : _Data table_, click on the table, click on _Expression editor_, change the default expression:

```
kibana
| selectFilter
| demodata
| table
| render

```
to:

```
esdocs index="metrics-*" count=10 sort="agent.type"
| table
| render

```
Click on _Run_, gives error _Unable to load page_.

### Logs (if relevant)

```
TypeError: t.renderError is not a function
    at https://my-deployment-XXX.kb.eu-central-1.aws.cloud.es.io/XXXaa/bundles/plugin/canvas/1.0.0/canvas.chunk.12.js:16:13571
    at u (https://my-deployment-XXX.kb.eu-central-1.aws.cloud.es.io/XXXaa/bundles/plugin/canvas/1.0.0/canvas.chunk.7.js:3:17944)
    at la (https://my-deployment-XXX.kb.eu-central-1.aws.cloud.es.io/XXXaa/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:429:59212)
    at ec (https://my-deployment-XXX.kb.eu-central-1.aws.cloud.es.io/XXXaa/bundles/kbn-ui-shared-deps-npm/kbn-ui-shared-deps-npm.dll.js:429:114853)
```

**Comment by kingherc** [comment]
Hi, if I'm not wrong, seeing the mentioned error, this question seems more relevant for Kibana than Elasticsearch, right? Could you re-open this issue in https://github.com/elastic/kibana ? I'm closing this for Elasticsearch.

**Comment by dolivanu** [comment]
Yes, it's related to Kibana, I didn't know where to place it, thanks a lot.
