### ISSUE TITLE
When no parent param is passed, partial update of  a child document removes the _parent value

### ISSUE THREAD

**Issue by ls-pluriels** [elastic/elasticsearch#11604]
PUT /myindex/anytype/?routing=rk&parent=daddy
```JSON
{
  "field":"value"
}
```
Everything works fine

PUT /myindex/anytype/?routing=rk
```JSON
{
  "field":"value"
}
```
The _parent field is removed. In a parent-child approach, you lose the link to your parent.
According to the documentation, you should not be able to update the `parent` value. (nor remove it ?)
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_parameters_3

ES version : 1.4.5

**Comment by clintongormley** [comment]
@ls-pluriels you linked to the update API docs, but you're not using `_update`, you're reindexing the document completely (which deletes the old doc and adds the new)
