### ISSUE TITLE
Partial text in Completion Suggester doesn't (immediately) matches with dataset

### ISSUE THREAD

**Issue by michielkraijkamp** [elastic/elasticsearch#11603]
Hi. We work on ElasticSearch 1.3.4. and have a very big set of data. 

Our completion field is configured as follows:
_suggest_company_by_name: {
max_input_length: 50
preserve_separators: true
payloads: true
analyzer: simple
preserve_position_increments: true
type: completion
}

Example of how we index:
_suggest_company_by_name: {
input: [
Trailburning
]
output: Trailburning
payload: {
company_identifier: 9f3974f8f10c4028b6ec2ccfcc67aaa6
}
}

We query the data as follows:
{
        "name" : {
            "text" : "<partial text>",
            "completion" : {
                "field" : "_suggest_company_by_name",
                "fuzzy" : {},
                "size" : 10,
            }
        }
    }

We experience the following problem. When entering a partial text (in this case a company name), there is a point where the partial text is already so specific it should respond with the exact name from the dataset matching it, but instead it gives results which are different. 

Example 1:
I search for the name 'Travel Rhythm'. As partial text I enter 'Travel R', but the system responds with the names 'Travel Distribution Systems', '1travel.gr' and 'Travel Agent CMS' (which obviously match with the 'Travel' part, but not with 'Travel<space>R'. Not untill the partial text is 'Travel Rhy' I get 'Travel Rhythm' as only result. 

Example 2
I search for the name iLost. As partial text I enter 'iLost' but the system responds with 'iGost Technologies' and 'iLastic'. Not untill I add a space in the partial text (so 'iLost<space>') I see 'iLost' in addition to the previous results.

What steps can we take to solve this? Thank you for your suggestions.

**Comment by clintongormley** [comment]
Hi @michielkraijkamp 

You're using fuzzy matching, so it produces a lot more matches.  I think, in the new suggester that we're implementing, that we can possibly favour exact matches over fuzzy matches.  @areek is that possible?

**Comment by michielkraijkamp** [comment]
Thanks for your quick reply @clintongormley 

It looks kind of fuzzy indeed :-) Showing suggestions if your partial text doesn't match data isn't so wrong, but if you look for something particular it is difficult if it's there but you need a workaround to find it.

**Comment by areek** [comment]
@michielkraijkamp @clintongormley with the new suggester implementation, the fuzzy matches that share the most number of characters with the user query would be ranked higher. For example, searching for 'iLost' will always yield 'iLost' higher than 'iLastic' or 'iGost'. (see https://github.com/elastic/elasticsearch/issues/10746)

**Comment by michielkraijkamp** [comment]
@clintongormley @areek That sounds perfect :-)

**Comment by clintongormley** [comment]
Closing in favour of #10746
