### ISSUE TITLE
Incorrect Aggregation count vs Search Query count

### ISSUE THREAD

**Issue by sumalatha87** [elastic/elasticsearch#116155]
### Elasticsearch Version

7.10.2

### Java Version

11

### OS Version

Windows 10

### Problem Description

When performing Aggregation on a query the count is mismatching with results coming from a simple search query.
The query used in Aggregation is same as the Search query.

The difference most of the times is always 1 count

### Steps to Reproduce

When performing Aggregation on a query the count is mismatching with results coming from a simple search query.
The query used in Aggregation is same as the Search query. The difference is mostly 1 count.

When aggregation is performed on a category, the count is coming around 19 but when the same query is executed separately with out performing aggregation the no of documents returned are 20.

When the query is executed directly using Elastic Search Dev tools, the correct no of documents returned are 20, then why there is less count when performed aggregation on the resultset.

**Comment by DaveCTurner** [comment]
Thank you very much for your interest in Elasticsearch. Unfortunately the issue you have reported relates to Elasticsearch version 7.10.2 which is very old and has passed [end-of-life](https://www.elastic.co/support/eol). We will not investigate issues related to unsupported versions here on Github, so I am closing this to indicate that no action is needed from the Elasticsearch development team. It's possible that you will find a volunteer to help you with this issue on the [community forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6), but our strong recommendation would be to upgrade to a supported version of Elasticsearch as a matter of some urgency. If you can reproduce your issue on a supported version then please open a fresh bug report.

Quoting the bug report form:

> Please also check your OS is [supported](https://www.elastic.co/support/matrix#show_os), and that the version of Elasticsearch has not passed [end-of-life](https://www.elastic.co/support/eol). If you are using an unsupported OS or an unsupported version then the issue is likely to be closed.
