### ISSUE TITLE
Plugin install broken in 1.6 when using JMX remote

### ISSUE THREAD

**Issue by Xylakant** [elastic/elasticsearch#11623]
Since #10721, the plugin script uses the system wide defaults file and thus inherits all JAVA_OPTIONS for the server process. We're using JMX to monitor our JVM with a remote port set. Since the plugin script uses the same defaults file it uses the same port and fails spectacularly since the port is already in use by the running ES process.

**Comment by Xylakant** [comment]
There are more entries in the defaults file which the plugin install script should not inherit:

* ES_GC_LOGGING
* ES_HEAP_SIZE
* ulimits

etc.

**Comment by clintongormley** [comment]
Fixed by #12801
