### ISSUE TITLE
How to detect the situation where nodes are offline but still receiving requests using k8s deployment in ES

### ISSUE THREAD

**Issue by smallemployees** [elastic/elasticsearch#116303]
### Description

The coordination node port is still available, but there is an error message when forwarding the request, and SVC cannot detect it

How to ensure the availability of coordination nodes by monitoring and checking the issue of node pseudo death detection

7.17.16

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
