### ISSUE TITLE
snapshot restore "failed to parse repository source" 

### ISSUE THREAD

**Issue by Judyccb** [elastic/elasticsearch#11633]
![image](https://cloud.githubusercontent.com/assets/12627595/8133988/55656c0a-115e-11e5-8338-4dd92a4f7fba.png)
I want to revise the parameter "shard_per_node"
My ES　version is 1.4.4.I copied the eg from es.co.Because of my version?

**Comment by imotov** [comment]
The ability to change index settings during restore was added in 1.5.0. It's not available in the version of elasticsearch that you are using.
