### ISSUE TITLE
Unable to install plugin in several paths

### ISSUE THREAD

**Issue by pierpaolocira** [elastic/elasticsearch#11639]
I would like to launch elasticsearch 1.6 on demand (not as service) inside a folder like

    /Users/me/Documents/99. Project/my_shared/tools/elasticsearch-1.6.0

(Please, note DOT+WHITESPACE after 99 in the fourth level of the path)

ElasticSearch works fine, but there is a problem if I go inside bin folder to install a plugin; for example:

    ./plugin -install mobz/elasticsearch-head

The enlgish translation of the error is:

>    Error: impossible to find or to load main class Project.my_shared.tools.elasticsearch-1.6.0.config

As you can see it starts reporting the path just after the WHITESPACE.

I'm using a MacOS system.

**Comment by clintongormley** [comment]
This has been fixed in recent versions.
