### ISSUE TITLE
Documentation: Search template docs use outdated syntax

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#11631]
The search syntax for pre-registered templates describes the deprecated syntax and not the new one: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html#pre-registered-templates

The template name should now be passed in a root-level `file` parameter and the docs describe the old syntax where it is nested under a `template` parameter.

**Comment by colings86** [comment]
The link references 1.6 branch. These changes were made in master only (v2.0). The following link (the master version of the same doc) looks to have correct syntax already:

https://www.elastic.co/guide/en/elasticsearch/reference/master/search-template.html#pre-registered-templates
