### ISSUE TITLE
Include global parameters in the REST spec

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch#11638]
Currently, global parameters like `source` and `filter_path` aren't included in the spec since it's implied that they exist on all APIs, and so defining them on all endpoints becomes unnecessarily repetitive/redundant.

However, I think it's useful to keep a definition of them somewhere other than the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html), since after all...they are still part of the REST API.  This is especially useful for the .NET client, since we rely on the spec to generate the respective C# methods for each query parameter.  Without them defined, we have to modify our code generator to include them manually.

I'm not sure how this would fit into the current spec since we define query parameters on a per endpoint basis...but we could think of something.  Maybe a  single `_global.json` file?

Just a thought.  If others agree that this is a good idea, I'd be happy to devise some solution.

**Comment by clintongormley** [comment]
+1

**Comment by javanna** [comment]
+1

**Comment by clintongormley** [comment]
@gmarz do you still want this?

**Comment by javanna** [comment]
I think we should do this, the `global.json` idea was ok with me. Does anybody at @elastic/es-clients have other ideas?

**Comment by gmarz** [comment]
I opened #22569.  I opted for `_global` rather than `global` to signal that it's not an actual endpoint.  Open to any suggestions.

**Comment by karmi** [comment]
What if, instead of `_global.json`, we had something like `_common.json` (or similar), which could list not only global URL parameters, but also other things like that in the future?

**Comment by javanna** [comment]
I have no opinion on global vs common, they both sound good to me.

**Comment by gmarz** [comment]
I'm also good with `_common.json`.  @karmi what other things do you see us adding in the future other than query params?

**Comment by karmi** [comment]
@gmarz, not really sure, probably just a case of my regular "just in case" condition :)

**Comment by gmarz** [comment]
@karmi 👍 I've updated the PR and renamed it to _common.
