### ISSUE TITLE
script debugging

### ISSUE THREAD

**Issue by celesteking** [elastic/elasticsearch#11648]
Currently, it's impossible to debug scripts in ES. I see no user-end documentation on that.

Can we get tools created for those who use something more complex than "2+2" one-line scripts?

**Comment by clintongormley** [comment]
The groovy console is a great tool for debugging groovy scripts: http://www.groovy-lang.org/groovyconsole.html

Any suggestions for what you'd like to see?

**Comment by celesteking** [comment]
How do I load ES environment in groovy console? ctx and all that.

I'd like to have at least println() immlemented/documented or something that would aid with debugging a complex script.

**Comment by nik9000** [comment]
Inject a logger into the script context?

**Comment by askaliuk** [comment]
Interested in the topic as well

**Comment by tomasaftalion** [comment]
Me too.

**Comment by clintongormley** [comment]
Closing in favour of #13084
