### ISSUE TITLE
Per Shard Optimize API

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#11645]
Currently, the `_optimize` API exists to optimize an entire index by merging segments in the background. In general, it's key to merge all segments to 1 (`max_num_segments=1`). However, if you have a very high workload, then it can be a very slow and expensive operation. Worse, optimizing an index that has replicas requires that both the primary and replica(s) be optimized separately.

It would be great if we could provide an improved optimize API that allows further control:

- Optimize specific shards of an index
    - This would be particularly helpful with routing scenarios where shards could be tuned as-needed without impacting the rest of the shards (note: for time based indices, it's still optimal to optimize all of them, but it may be easier to wait for the remaining shards)
    - It also has the added benefit that you can better predict its impact, both in terms of file capacity _and_ processing. Since you may have multiple shards per node, it also avoids running them in parallel.
- Choose to optimize a specific shard (not only the shard, but which node if replica shards exist)
- Offer the ability to optimize a single shard, then copy the optimized shard rather than duplicating the effort on its primary/replica peer.
    - This would allow people to choose to spend a little bit of short lived memory and network bandwidth rather than the current overhead associated (processing, longer lived memory, and more IO).

**Comment by rmuir** [comment]
I don't think we should overengineer optimize in this way.

Maybe it is slow/cumbersome in lucene 4.x but time to start looking at lucene 5, its been out for a long time.

**Comment by jpountz** [comment]
Closing for the reasons that Robert gave.
