### ISSUE TITLE
"plugin" script not named in a linux-friendly manner

### ISSUE THREAD

**Issue by proegssilb** [elastic/elasticsearch#11651]
I'd like to see the script named "es-plugin" or something similar so that it doesn't overlap with other programs that also have a plugin system (like LogStash, who also has a script named "plugin").

This would be particularly useful for the RPMs which, if I understand what's going on correctly, install "plugin" to /usr/share/bin.

I can submit a pull request if that helps speed things up.

**Comment by clintongormley** [comment]
Closing in favour of #11797
