### ISSUE TITLE
Shards in newly created dummy indices are not allocating

### ISSUE THREAD

**Issue by nithyanv** [elastic/elasticsearch#11654]
Hi,

I created an index using command
curl -XPUT http://135.250.193.206:9200/some-index

It doesn't get allocated. We are unable to insert data as it throws UnavailableShardsException

I have tried to set the allocation using the below command but the issue persists. 

curl -XPUT 'localhost:9200/_cluster/settings' -d '{
    "transient" : {
        "cluster.routing.allocation.enable" : "all"
    }
}'

I am using ES version 1.4.4

**Comment by markwalkom** [comment]
Do you have enough disk space? Have you checked your ES logs?

However please join us in #elasticsearch on Freenode or at https://discuss.elastic.co/ for troubleshooting help, we reserve Github for confirmed bugs and feature requests :)

**Comment by nithyanv** [comment]
Hi, 

I have 78% diskspace. 

curl -XGET 'http://localhost:9200/_cluster/health?pretty=true'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   277  100   277    0     0   8656      0 --:--:-- --:--:-- --:--:-- 17312
{
  "cluster_name" : "devteam",
  "status" : "red",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 217,
  "active_shards" : 217,
  "relocating_shards" : 0,
  "initializing_shards" : 4,
  "unassigned_shards" : 239
}

**Comment by s1monw** [comment]
please use the discuss list for those kind of questions as @markwalkom  suggested

> However please join us in #elasticsearch on Freenode or at https://discuss.elastic.co/ for troubleshooting help, we reserve Github for confirmed bugs and feature requests :)
