### ISSUE TITLE
Script_File support for NEST

### ISSUE THREAD

**Issue by vineet85** [elastic/elasticsearch#11652]
Hi,

ElasticSearch supports referencing a script which is stored in a file. Eg:-
GET /_search
{
    "script_fields": {
        "my_field": {
            "script_file": "my_script",
            "params": {
              "my_var": 2
            }
        }
    }
}

However the .NET NEST client does not have any support for this yet. Is this going to be added soon?

https://github.com/elastic/elasticsearch-net/blob/4fcecae93dcf16a4ff7e110135da81eed409dda5/src/Nest/DSL/Filter/ScriptFilterDescriptor.cs#L36

Thanks,
Vineet

**Comment by clintongormley** [comment]
This issue was moved to elastic/elasticsearch-net#1456
