### ISSUE TITLE
Number fields

### ISSUE THREAD

**Issue by dopesong** [elastic/elasticsearch#11650]
I found this explanation about my issue:

http://elasticsearch-users.115913.n3.nabble.com/Number-Format-Exception-td1474946.html
>Ahh, yes, this is a limitation in elasticsearch. Basically, all types are broken down into Lucene Documents, with their "typeness" added by elasticsearch. The limit to that is the fact that a field with the same name across different types *within the same index* must be of the same type (long/integer/string). The problem does not exists between indices.

So is this going to change? Because why one type field is realted to another?

**Comment by clintongormley** [comment]
Hi @dopesong 

No it isn't going to change. In fact we're getting stricter about enforcing this restriction.  See https://github.com/elastic/elasticsearch/issues/8870

A blog post will be coming soon to explain the problems, and the changes we've made to resolve them.
