### ISSUE TITLE
Problem with highlighting

### ISSUE THREAD

**Issue by litalk** [elastic/elasticsearch#11667]
##### Hi Guys,
I am using **elasticsearch 1.6.0** and having issues with highlighting.
When I use the following query:
```json
{
  "from" : 0,
  "size" : 10,
  "query" : {
      "query_string" : {
      "query" : "attachment:Y",
      "use_dis_max" : true,
      "analyzer" : "snowball"
    }
  },
  "highlight" : {
    "pre_tags" : [ "<span class=\"mark\">" ],
    "post_tags" : [ "</span>" ],
    "encoder" : "html",
    "order": "score",
    "require_field_match" : false,
    "fields" : {
       "*" : { }
      }
  }
 }
```

I get in the highlight response fields that I have not queried specifically about.
My query was: attachment:Y
and I got:
```json
 "highlight": {
               "fields.attachment": [
                  "<span class=\"mark\">Y</span>"
               ],
               "fields.reproducible": [
                  "<span class=\"mark\">Y</span>"
               ],
               "fields.has-linkage": [
                  "<span class=\"mark\">Y</span>"
               ],
               "fields.has-others-linkage": [
                  "<span class=\"mark\">Y</span>"
               ]
            }
```

Which is not the behavior I want...
I can't set `require_field_match=true` because I also want to query for free text without specifying any fields and I expect elasticsearch to highlight everything he finds matching the text, and if `require_field_match=true` nothing is highlighted when I query for any text like 
```json
"query" : {
      "query_string" : {
      "query" : "Y",
      "use_dis_max" : true,
      "analyzer" : "snowball"
    }
  }
```

Is there something else I can configure to get this to work?

Thanks in advance any help would be appreciated!

**Comment by clintongormley** [comment]
Hi @litalk 

You're looking for this option: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html#field-match

**Comment by litalk** [comment]
Hi @clintongormley,
Thanks for your answer, but as I said in my post I cannot use this option because sometimes I am searching for free text, not binded to any field and I would expect elasticsearch to highlight every field he finds with my text query. If I set require_field_match=true nothing is highlighted. 

Can you reopen my request?

**Comment by clintongormley** [comment]
Somehow I missed the whole section you wrote about `require_field_match`.  My apologies.

However, when you say:

> I am searching for free text, not binded to any field

... this is not what you are doing.  If you don't specify a field, then you are querying the `_all` field, which contains the values of all fields concatenated as one big string.   This is why various fields get highlighted.  Instead, try querying just the fields that you want to query, along with setting `require_field_match` to true.

**Comment by litalk** [comment]
But this is not my use case. 
I don't always know the specific fields in my application. I know I am searching for some phrase but I am not sure if it's in the name field or description,  or maybe in the comments...  This is just an example,  but the idea of the application is a global search and not always the specific field is known. In that case, highlighting does a great job. Bug in the case I do want  to filter by a specific field it does not work as expected...

**Comment by clintongormley** [comment]
then for the first use case you can use `_all`, and for the second use case you can specify the fields directly

**Comment by litalk** [comment]
But that requires me to parse the query, I don't want to do that... Sometimes I have combination of both use cases. E.G: '''fieldA:query AND sometext'''
And for that I can't use this solution even if I parse the query.
