### ISSUE TITLE
in case of scripted updates it would be good if we get the operation

### ISSUE THREAD

**Issue by vedil** [elastic/elasticsearch#11684]
is it possible to get the result.operation() in the UpdateResponse too, so that it is easy to determine if NONE/DELETE/UPSERT which of them actually happened?
because ctx.get("op") is after the execution of script, it would be good to know for the client whether actual update happened or not

**Comment by clintongormley** [comment]
Related to https://github.com/elastic/elasticsearch/pull/9736

**Comment by dakrone** [comment]
This has already been resolved in a different change, the API now returns "result": "updated" or "result": "noop" so I am closing this
