### ISSUE TITLE
"refresh" parameter is not honored in bulk request

### ISSUE THREAD

**Issue by niu-lin** [elastic/elasticsearch#11690]
According the documentation (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-refresh), there's a "refresh" parameter that can be used to force refresh after bulk operation and we have been using this parameter for a while. However, since 1.6.0, the parameter no longer works, with an exception thrown: 
{"error":"IllegalArgumentException[Action/metadata line [1] contains an unknown parameter [refresh]]","status":500}

I spent some time to dig into it, and found it's related to issue #10977 and  commit https://github.com/elastic/elasticsearch/commit/acb07c72b9d2fd6e21f9710ffbdf4573c01c9f22.

The issue is:
The "refresh" parameter is not checked in the source code before 1.6.0 which is simply ignored, began from 1.6.0, the unchecked "refresh" parameter will cause an exception. So I doubt the "refresh" parameter is never honoured.

The sample request is:
{"update":{"_id":"test", "refresh" : true}}
{"doc_as_upsert":true,"doc":{"testkey":"testvalue"}}

**Comment by bleskes** [comment]
The `refresh` paramater is one that can be set for the entire request. Refreshing is relatively expensive and therefore is only supported for the entire operation and is done while all items have been executed. I made a PR to improve the docs.

**Comment by niu-lin** [comment]
Thanks for your comment. So my understanding is I should write it as below:

POST /index_name/type_name/_bulk?refresh=true
blabla

Is that correct?

**Comment by niu-lin** [comment]
BTW, I understand it is very expensive, but since we are only use it for some special rare cases, we can afford that cost.

**Comment by bleskes** [comment]
yeah, that’s correct.

**Comment by niu-lin** [comment]
Boaz, thank you very much for clarifying! I'll close this issue then.
