### ISSUE TITLE
Stored script parameters

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#11698]
When script parameters are huge but reused several times it would be great to be able to store them and have them available at execution time without having to pass them with the search request.

Something like:

```
{
  "script_fields": {
    "label": {
      "script": "my_script",
      "stored_parameters": "many_and_huge_parameters"
    }
  }
}
```
where the "many_and_huge_parameters" are retrieved from somewhere inside elasticsearch.
My use case is a classifier. I train the model outside elasticsearch and then use the computed model parameters in es as a native script that implements the model. The model stays the same always but whenever I train it again the parameters change and I would like to not always pass them with the search request.

**Comment by imotov** [comment]
Maybe we can support storing the parameters as a record in another index and then refer to this record in the request similar to what we do with terms lookup? Something like:

```
{
  "script_fields": {
    "label": {
      "script": "my_script",
      "stored_parameters": {
        "index": "models",
        "type": "params",
        "id": "1234",
        "path": "something"
      }
    }
  }
}
```

You can do the same thing in the native script, but if this is a common use case, it might be worth supporting this functionality on the elasticsearch level.

**Comment by brwe** [comment]
@imotov thanks for the pointer to the workaround! (I assume you mean something like here: https://github.com/imotov/elasticsearch-native-script-example/blob/master/src/main/java/org/elasticsearch/examples/nativescript/script/LookupScript.java).We discussed this briefly and decided that we defer implementation of such a feature until more people actually need it. I can live with the workaround for now. @colings86 correct me if I am wrong.

**Comment by imotov** [comment]
@brwe yes, lookup script is one way to do it. Alternatively, if you don't want to deal with a cache (and it's invalidation and expiration) you can pull the parameters from the index and stash them in the "params" map. The params map is created once per execution per shard and then passed to all script instantiations for this shard. So, it will not be as efficient as with global cache but so much simpler. Basically you would have something like this:

```java
    public static class Factory extends AbstractComponent implements NativeScriptFactory {
   
        // ............ 

        @Override
        public ExecutableScript newScript(@Nullable Map<String, Object> params) {
            Map<String, Object> veryLargeParams = params.get("cached_params");
            if( veryLargeParams == null) {
                // This will be executed once per search for every shard
                veryLargeParams = loadVeryLargeParams(params);
                params.put("cached_params", veryLargeParams);
            }
            return new MyScript(veryLargeParams);
        }

        // ............ 

    }
```

**Comment by clintongormley** [comment]
Nothing further in the last 9 months - closing
