### ISSUE TITLE
Significant increase in CI timeouts "failed to wait for ports files after X MILLISECONDS"

### ISSUE THREAD

**Issue by benwtrent** [elastic/elasticsearch#116992]
### CI Link

https://gradle-enterprise.elastic.co/s/mk32qhvztzaye

### Repro line

N/A

### Does it reproduce?

No

### Applicable branches

main, 

### Failure excerpt

There are many more failures due to timeouts waiting for node start up. This has increased significantly in the last 2 months. 

Here are three such build scans:

https://gradle-enterprise.elastic.co/s/mk32qhvztzaye

https://gradle-enterprise.elastic.co/s/diyfle4d7iakq

https://gradle-enterprise.elastic.co/s/blgvt2vsr4n4u

In all the failures, there are some significant pauses during node start up. One REALLY weird one is this one:

```
[2024-11-18T10:50:52,999][INFO ][o.e.n.Node               ] [v8.17.0-0] node name [v8.17.0-0], node ID [ylfk6hsYQzu-W6xesR8Z1w], cluster name [v8.17.0], roles [ml, data_hot, transform, data_content, data_warm, master, remote_cluster_client, data, data_cold, ingest, data_frozen]
[2024-11-18T10:51:17,793][INFO ][o.e.c.u.FeatureFlag      ] [v8.17.0-0] The current build is a snapshot, feature flag [connector_secrets] is enabled
```

Between naming the node and printing its information, to the "connector_secrets" feature loading its 20-30 seconds. 

There are other various pauses. For example:

```
[2024-11-18T10:50:26,339][INFO ][o.e.c.u.FeatureFlag      ] [v8.17.0-0] The current build is a snapshot, feature flag [esql_inlinestats] is enabled
[2024-11-18T10:50:40,985][INFO ][o.e.p.PluginsService     ] [v8.17.0-0] loaded module [repository-url]
```

Starting to load the plugins after the ESQL inlinestats feature log also takes significant time.

I am tagging delivery & core infra, not for blame, but for aid in debugging.

**Comment by mark-vieira** [comment]
I did some experiments just to see startup time on a default cluster (security off). Things are pretty stable and then we see bump around 8.14. These are with nothing else running so I'd obviously expect these numbers to be higher when there's a lot of concurrent activity on the machine.

-- | --
v8.3.3 | 21.09 s
v8.6.2 | 21.88 s
v8.4.3 | 22.06 s
v8.9.2 | 22.11 s
v8.7.1 | 22.16 s
v8.8.2 | 22.19 s
v8.5.3 | 22.41 s
v8.2.3 | 23.18 s
v8.1.3 | 23.18 s
v8.0.1 | 23.20 s
v8.10.4 | 23.33 s
v8.11.4 | 23.40 s
v8.12.2 | 24.22 s
v8.13.4 | 24.61 s
v8.14.3 | 28.64 s
v8.16.1 | 29.41 s
v8.17.0 | 29.64 s
v9.0.0 | 30.15 s
v8.15.4 | 30.73 s

**Comment by mark-vieira** [comment]
Another run with similar results. Interesting that in both 8.15 is the worst.

version|time
-- | --
v8.3.3 | 21.45 s
v8.7.1 | 21.54 s
v8.5.3 | 21.79 s
v8.4.3 | 21.84 s
v8.8.2 | 22.04 s
v8.6.2 | 22.14 s
v8.2.3 | 22.37 s
v8.9.2 | 22.41 s
v8.1.3 | 22.74 s
v8.10.4 | 22.79 s
v8.0.1 | 23.06 s
v8.11.4 | 23.70 s
v8.13.4 | 24.05 s
v8.12.2 | 24.48 s
v8.14.3 | 28.39 s
v8.17.0 | 28.59 s
v9.0.0 | 28.80 s
v8.16.1 | 31.30 s
v8.15.4 | 32.86 s

**Comment by mark-vieira** [comment]
I think the simplest thing here might just be to increase this timeout for now. Thoughts @breskeby?

**Comment by mark-vieira** [comment]
Also cc @rjernst as this rising increase in node startup times might be something we want to get a handle on.

**Comment by mosche** [comment]
To investigate the source of the slowness we should better instrument node startup / construction. APM instruments will not necessarily available yet, we need a temporary place where to dump the data first ... Alternatively this could be logs, but it will be much harder to analyse.

Trouble will be that we won't have the data available for previous versions to figure out where we've added slowness in the past. Though it should help to better prevent future regressions.

Good candidate for KTLO

**Comment by mark-vieira** [comment]
I've opened a PR to bump the node startup timeout for now (https://github.com/elastic/elasticsearch/pull/117603). Let's observe these failures and see if that helps.

**Comment by mark-vieira** [comment]
Bumping the timeout has mitigated this problem for now. We've seen no failures in the last 5 days. We might want to do something about growing node startup time but that's outside the scope of this issue.
