### ISSUE TITLE
Try another node if retryable ClusterBlockException received for TransportClient

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#11709]
Currently if we hit a ClusterBlockException on a node we retry to the same node and then give up. Only on connection exceptions do we [retry a different node](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java#L231)

This sort of situation can happen if a users is doing a rolling restart of the nodes, due to an upgrade.

We could be smarter in the TransportClient to retry another node when we hit this ClusterBlockException.

**Comment by kimchy** [comment]
I have a simple pull request for this https://github.com/kimchy/elasticsearch/tree/retry_on_cluster_block_transport_client, but there is a problem that I am not sure how best to fix, see the commit note for it

**Comment by sathieu** [comment]
In the meantime, what is the current recommended way to fix a cluster in this situation?

**Comment by Inkromind** [comment]
We ran into this issue when one of our nodes was being restarted. It was receiving requests before it was fully initialized and so it threw a ClusterBlockException. The request was not retried with another node.

Is anything going to happen with @kimchy s changes (for which I couldn't find a pull request) or should we catch this exception ourselves and retry (with the possibility that our request is sent to the same node and the same exception occurs)? Or is there another better way to handle this kind of scenario?

**Comment by ScionOfBytes** [comment]
What's the status on this? I believe we've faced the same issue.

**Comment by tanero** [comment]
I receive the same error, when I have connected with TransportClient from java api,  If the node went down and start again, exception occurs.

**Comment by javanna** [comment]
Our language clients retry `5xx` errors, but not `4xx` responses as they are request errors which should be fixed on the client side. There are different cluster blocks, and they are associated with different response codes: 

|  Block type | response code  |
|---|---|
| CLUSTER_READ_ONLY_BLOCK  | 403  |
|  CLUSTER_READ_ONLY_ALLOW_DELETE_BLOCK | 403  | 
|  INDEX_CLOSED_BLOCK | 403  | 
|  INDEX_READ_ONLY_BLOCK | 403  | 
|  INDEX_WRITE_BLOCK | 403  | 
|  INDEX_METADATA_BLOCK | 403  | 
|  INDEX_READ_ONLY_ALLOW_DELETE_BLOCK | 403  | 
|  NO_MASTER_BLOCK_ALL | 503  | 
|  NO_MASTER_BLOCK_WRITES | 503  | 
|  STATE_NOT_RECOVERED_BLOCK | 503  | 

Based on the language clients retry logic, only the last three should be retried. For the transport client things are a bit different as it doesn't speak http, and it may not retry with the same logic. Transport Client is deprecated though , see #27085 . I just verified that the java REST client behaves properly when it comes to retries, hence I am closing this.
