### ISSUE TITLE
Synthetic source implementation for `constant_keyword` is inconsistent with stored source

### ISSUE THREAD

**Issue by lkts** [elastic/elasticsearch#117083]
Currently synthetic source for `constant_keyword` field is implemented to always write the constant value in `_source`. Most of the time such a value was not actually provided in the document (there is no reason to do that, it's constant) and therefore would not be in stored `_source`. This is problematic when using `constant_keyword` fields as a metadata fields that can be different between indices (f.e. reindexing an index into an index that has a different value of such a field). This scenario works with stored source since the values are never there but fails with synthetic source.

**Comment by lkts** [comment]
I think `constand_keyword` fields can be completely skipped in synthetic source. When reindexed they will have the expected value anyway.

**Comment by lkts** [comment]
Alternatively we can use fallback synthetic source which will preserve the value if it is ever present in document. I can't imagine a scenario when that is important but it is closer to stored source behavior.

**Comment by kkrik-es** [comment]
> Alternatively we can use fallback synthetic source which will preserve the value if it is ever present in document. I can't imagine a scenario when that is important but it is closer to stored source behavior.

Let's do that for now, the goal is to be on par with stored source.

**Comment by kkrik-es** [comment]
@lkts lemme know if you don't have cycles to fix this.
