### ISSUE TITLE
Allow _id field to be a tiebreaker instead of _doc

### ISSUE THREAD

**Issue by jamie-wilson88** [elastic/elasticsearch#117040]
### Description

The _doc field is used when sorting, but if there are duplicate _doc values can _id be used as a default tiebreaker?

**Comment by AI-IshanBhatt** [comment]
Thanks very much for your interest in Elasticsearch.
This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.
There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.

**Comment by AI-IshanBhatt** [comment]
Thanks very much for your interest in Elasticsearch.
This appears to be a user question, and we'd like to direct these kinds
of things to the [forums](https://discuss.elastic.co/). If you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.
There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
