### ISSUE TITLE
Add shortcut for match_all query in the Delete-By-Query plugin

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#11700]
In https://github.com/elastic/elasticsearch/pull/11516#discussion_r32312451 Simon suggest to add a shortcut when a `match_all` query is executed with the Delete-By-Query plugin:

> We should maybe also think about having a shortcut if there is a match all query passed to this. I think folks to this all the time so I wonder if we should have such a destructive operation as feature on this as well behind the scenes. Doesn't need to be added now but in general we can think about adding this to IndexShard / Engine since in lucene that is quite fast.

**Comment by dakrone** [comment]
Since it has been over two years with no movement on this issue, I am going to close it. If it's something others find useful please do speak up!
