### ISSUE TITLE
[ML] Deprecate unused ChunkingOptions

### ISSUE THREAD

**Issue by dan-rubinstein** [elastic/elasticsearch#117193]
## Description

We pass around ChunkingOptions through all of our `doChunkedInfer` functions ([example](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/services/openai/OpenAiService.java#L267)) but this object should no longer be in use as the new confiruable ChunkingSettings should be tracking all chunking configurations instead. This issue is to deprecate the ChunkingOptions object and remove it from the codebase.

**Comment by davidkyle** [comment]
Closed by #117235
