### ISSUE TITLE
highlight force_source have no effect on _source content field

### ISSUE THREAD

**Issue by ryanchou1991** [elastic/elasticsearch#11713]
When i set the highlight fields such likes

```
{
   "query": {},
   "highlight": {
   "fields": {"content": {"force_source": true} }
    }
}
```

There was no tags in the _source content field , and the text with highlighted tags still in highlight field? 
so did I use it in a wrong way? or the highlight force_source field option have no effect ?

**Comment by clintongormley** [comment]
I don't understand what your question is.  Could you provide more info please?

**Comment by clintongormley** [comment]
... with a complete (but simple) recreation

**Comment by ryanchou1991** [comment]
OK. Sorry for incomplete description. I re-describe the question again.
I have a amount of docs in indices in ES. e.g 
```
{
	'_source': {
	'title': 'Foo bar foobar foo barbar',
	'headers': 'HTTP/1.0 200 OK
Server: GeoHttpServer
Date: Thu, 18 Jun 2015 19:02:31 GMT
Content-type: text/html',
    'city': 'US'
	}
}
```
And the query with highlight option e.g.
```
{
   "query": {"match": {"title": "foo"}},
   "highlight": {
   "fields": {"title": {"force_source": true} }
    }
}
```
While the response result was 
```
{
	'_source': {
	'title': 'Foo bar foobar foo barbar',
	'headers': 'HTTP/1.0 200 OK
Server: GeoHttpServer
Date: Thu, 18 Jun 2015 19:02:31 GMT
Content-type: text/html',
    'city': 'US'
	}
    'highlight': [{'title': "Foo bar foobar <em>foo</em> barbar"}]
}
```
I set `force_source: true` in field highlight-option while the _source.title without the highlight tags <em></em>.  Did I misunderstand the `force_source` option? or the `force_source` have no effect?

**Comment by clintongormley** [comment]
OK - you've misunderstood the `force_source` option.  All it does is say "Use the `_source` field to get the field values to use for highlighting, instead of eg retrieving stored field values"

**Comment by ryanchou1991** [comment]
OK, I got it . Thanks a lot,  Clintongormley : )

**Comment by huey2672** [comment]
> OK. Sorry for incomplete description. I re-describe the question again.
> I have a amount of docs in indices in ES. e.g
> 
> ```
> {
>     '_source': {
>     'title': 'Foo bar foobar foo barbar',
>     'headers': 'HTTP/1.0 200 OK
> Server: GeoHttpServer
> Date: Thu, 18 Jun 2015 19:02:31 GMT
> Content-type: text/html',
>     'city': 'US'
>     }
> }
> ```
> 
> And the query with highlight option e.g.
> 
> ```
> {
>    "query": {"match": {"title": "foo"}},
>    "highlight": {
>    "fields": {"title": {"force_source": true} }
>     }
> }
> ```
> 
> While the response result was
> 
> ```
> {
>     '_source': {
>     'title': 'Foo bar foobar foo barbar',
>     'headers': 'HTTP/1.0 200 OK
> Server: GeoHttpServer
> Date: Thu, 18 Jun 2015 19:02:31 GMT
> Content-type: text/html',
>     'city': 'US'
>     }
>     'highlight': [{'title': "Foo bar foobar <em>foo</em> barbar"}]
> }
> ```
> 
> I set `force_source: true` in field highlight-option while the _source.title without the highlight tags `<em></em>`. Did I misunderstand the `force_source` option? or the `force_source` have no effect?
> The result i expected likes
> 
> ```
> {
>     '_source': {
>     'title': 'Foo bar foobar <em>foo</em> barbar',
>     'headers': 'HTTP/1.0 200 OK
> Server: GeoHttpServer
> Date: Thu, 18 Jun 2015 19:02:31 GMT
> Content-type: text/html',
>     'city': 'US'
>     }
>     'highlight': [{'title': "Foo bar foobar <em>foo</em> barbar"}]
> }
> ```

Hi! How did you make the field in _source with tags finally?

**Comment by LuckyWindsck** [comment]
> Hi! How did you make the field in _source with tags finally?

Isn't that the question of issue author?

**Comment by zDream** [comment]
> > 好的。抱歉描述不完整。我再次重新描述这个问题。
> > 我在 ES 的索引中有大量文档。例如
> > ```
> > {
> >     '_source': {
> >     'title': 'Foo bar foobar foo barbar',
> >     'headers': 'HTTP/1.0 200 OK
> > Server: GeoHttpServer
> > Date: Thu, 18 Jun 2015 19:02:31 GMT
> > Content-type: text/html',
> >     'city': 'US'
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 带有突出显示选项的查询例如
> > ```
> > {
> >    "query": {"match": {"title": "foo"}},
> >    "highlight": {
> >    "fields": {"title": {"force_source": true} }
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 虽然响应结果是
> > ```
> > {
> >     '_source': {
> >     'title': 'Foo bar foobar foo barbar',
> >     'headers': 'HTTP/1.0 200 OK
> > Server: GeoHttpServer
> > Date: Thu, 18 Jun 2015 19:02:31 GMT
> > Content-type: text/html',
> >     'city': 'US'
> >     }
> >     'highlight': [{'title': "Foo bar foobar <em>foo</em> barbar"}]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我`force_source: true`在字段中设置了highlight-option，而_source.title没有highlight标签`\<em\>\</em\>`。我误解了这个`force_source`选项吗？还是`force_source`没有效果？
> > 我期望的结果喜欢
> > ```
> > {
> >     '_source': {
> >     'title': 'Foo bar foobar <em>foo</em> barbar',
> >     'headers': 'HTTP/1.0 200 OK
> > Server: GeoHttpServer
> > Date: Thu, 18 Jun 2015 19:02:31 GMT
> > Content-type: text/html',
> >     'city': 'US'
> >     }
> >     'highlight': [{'title': "Foo bar foobar <em>foo</em> barbar"}]
> > }
> > ```
> 
> 你好！你最后是怎样在 _source 中用标签创建字段的？



> Hi! How did you make the field in _source with tags finally?

Hi! How did you make the field in _source with tags finally?

**Comment by zDream** [comment]
> > OK. Sorry for incomplete description. I re-describe the question again.
> > I have a amount of docs in indices in ES. e.g
> > ```
> > {
> >     '_source': {
> >     'title': 'Foo bar foobar foo barbar',
> >     'headers': 'HTTP/1.0 200 OK
> > Server: GeoHttpServer
> > Date: Thu, 18 Jun 2015 19:02:31 GMT
> > Content-type: text/html',
> >     'city': 'US'
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And the query with highlight option e.g.
> > ```
> > {
> >    "query": {"match": {"title": "foo"}},
> >    "highlight": {
> >    "fields": {"title": {"force_source": true} }
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > While the response result was
> > ```
> > {
> >     '_source': {
> >     'title': 'Foo bar foobar foo barbar',
> >     'headers': 'HTTP/1.0 200 OK
> > Server: GeoHttpServer
> > Date: Thu, 18 Jun 2015 19:02:31 GMT
> > Content-type: text/html',
> >     'city': 'US'
> >     }
> >     'highlight': [{'title': "Foo bar foobar <em>foo</em> barbar"}]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I set `force_source: true` in field highlight-option while the _source.title without the highlight tags `\<em\>\</em\>`. Did I misunderstand the `force_source` option? or the `force_source` have no effect?
> > The result i expected likes
> > ```
> > {
> >     '_source': {
> >     'title': 'Foo bar foobar <em>foo</em> barbar',
> >     'headers': 'HTTP/1.0 200 OK
> > Server: GeoHttpServer
> > Date: Thu, 18 Jun 2015 19:02:31 GMT
> > Content-type: text/html',
> >     'city': 'US'
> >     }
> >     'highlight': [{'title': "Foo bar foobar <em>foo</em> barbar"}]
> > }
> > ```
> 
> Hi! How did you make the field in _source with tags finally?

I also want to know how to do the last
