### ISSUE TITLE
Possible typo in the docs

### ISSUE THREAD

**Issue by johnament** [elastic/elasticsearch#11720]
If I look at the docs for [templates], there's a mention that the templates are stored in .scripts.  The API listing for them seems a bit off.  Is the URI really /_search/templates?  Is it supposed to be /.scripts/_search/templates or something like that?  If I want to update a template do I use /.scripts/_search/templates/{templateId} ?

[templates]: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html#pre-registered-templates

**Comment by clintongormley** [comment]
HI @johnament 

The docs are correct.  Use `GET|POST /_search/template/some_id` to index or retrieve a template.  And use `GET /_search/template` to perform a search with the template specified in the body of the search request (either inline, as a file name, or with `some_id` to retrieve an indexed template)
