### ISSUE TITLE
Script in terms aggregation that is not a value script should fail with descriptive failure message

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#11728]
When a script is not a value script in a terms aggregation then the request must not contain the "fields" parameter. 
However, there is no warning to the user if the request has the "fields" parameter anyway. The aggregation will just fail with cryptic error messages or even worse just silently not do the right thing.

This fails with an ArrayIndexOutOfBoundsException:

```
{
  "aggs": {
    "2": {
      "terms": {
        "field": "label",
        "script": "doc['label'].value"
      }
    }
  }
}
```

This silently just does not do the right thing (returns one bucket with key 0 and all docs in it):

```
{
  "aggs": {
    "2": {
      "terms": {
        "field": "label",
        "script": "_index['text']['the'].tf()"
      }
    }
  }
}
```

**Comment by luckywin** [comment]
I have same issue. Value script in terms aggregation breaks migration from terms facet (I've already posted question about such migration https://stackoverflow.com/questions/31006983/migration-from-terms-facet-to-terms-aggregation)

**Comment by brwe** [comment]
@luckywin just to be sure: you know that removing the "fields" parameter in the aggregation should make your script work?

**Comment by luckywin** [comment]
@brwe yes, I knew this, thank you. After removing "field" parameter, agg starts responding with "true" and "false" as a result of aggregation, and this is not expected result for me. I also tried to modify script to return field value (or null when I want to exclude value from agg), but it seems not works too.

**Comment by markharwood** [comment]
cc @elastic/es-search-aggs 
Some of the script examples in this old issue are outdated but master still accepts `field` and `script` params together when it should be one or the other.

**Comment by imotov** [comment]
In #31532 we decided not to deprecate "value scripts", which are still not very well documented. I am not getting cryptic failure messages anymore. The first example works as expected. We could add a deprecation warning on absence of `_value` in the script, but I am not sure that's the best approach here.

**Comment by imotov** [comment]
We discussed the issue and we would like to start sending warnings to users if `_value` is not present in the value script. It should be possible after #53702 is implemented and we can add a compiler pass to check if `_value` is present.

**Comment by wchaparro** [comment]
Closing as not planned, focus on ESQL development.  Painless has helped with this issue.
