### ISSUE TITLE
Replace deprecated methods readStringStringMap() and writeStringStringMap()

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#11742]
Lucene deprecated methods `IndexOutput#writeStringStringMap()` and `IndexInput#readStringStringMap()` but are still using them in elasticsearch 2.0.0 `Store` class:

* https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/store/Store.java#L865-865
* https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/store/Store.java#L1192-1192

**Comment by colings86** [comment]
The methods in those links are for LegacyChecksums. Do we not need to keep using those methods for backwards compatibility, to be able to read old indices/segments?

**Comment by clintongormley** [comment]
Closing for now

**Comment by nik9000** [comment]
I think in master we can just blast the legacy checksum support entirely.
