### ISSUE TITLE
init.d script does not stop currently running (old) process after upgrade

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#11747]
Using repository install on Ubuntu 14.04 LTS

Sequence to reproduce.
* Install 1.5.2
* Upgrade to 1.6.0
* Run ```service elasticsearch stop```

init.d script returns "[ OK ]" (indicates that process has been stopped), but process list shows process is still running.  If you manually kill the process, the init.d script then successfully start/stops

**Comment by clintongormley** [comment]
Closing in favour of #12649
