### ISSUE TITLE
Message not fully read warnings in logs on master

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#11748]
when I run `TermsAggregationSearchBenchmark` I get warnings like this: 
```
[2015-06-18 06:30:28,641][WARN ][org.elasticsearch.transport.netty] [node0] Message not fully read (request) for requestId [99], action [indices:data/write/bulk[s]], readerIndex [114711] vs expected [114717]; resetting
```

if I disable compression for bulk they go away so I suspect it's something related to message compression that does some kind of padding or so?

if disable bulk compression it goes away `"action.bulk.compress", false` the funny part is that the `readerIndex [114711]` is always the same when I get the message while `expected [114717];` varies +- 5

the message is in `org.elasticsearch.transport.netty.MessageChannelHandler#118`

**Comment by rmuir** [comment]
I tried disabling bulk compression but i still see it. Maybe i dont disable it correctly though.

**Comment by s1monw** [comment]
I did this to be sure:

```DIFF
diff --git a/core/src/main/java/org/elasticsearch/action/bulk/BulkAction.java b/core/src/main/java/org/elasticsearch/action/bulk/BulkAction.java
index 42d0c22..3554516 100644
--- a/core/src/main/java/org/elasticsearch/action/bulk/BulkAction.java
+++ b/core/src/main/java/org/elasticsearch/action/bulk/BulkAction.java
@@ -49,7 +49,7 @@ public class BulkAction extends Action<BulkRequest, BulkResponse, BulkRequestBui
     public TransportRequestOptions transportOptions(Settings settings) {
         return TransportRequestOptions.options()
                 .withType(TransportRequestOptions.Type.BULK)
-                .withCompress(settings.getAsBoolean("action.bulk.compress", true)
+                .withCompress(settings.getAsBoolean("action.bulk.compress", false)
                 );
     }
 }
```

**Comment by rmuir** [comment]
I'll try your patch and see.

**Comment by rmuir** [comment]
also i am confused, if this is a serious thing, why does it simply get logged and not fail tests and so on?

**Comment by rmuir** [comment]
Yeah, disabling the bulk compress works here too. I had fat finger'ed the option.
