### ISSUE TITLE
Querystring treats nonexistent wildcard fields as existing in AND expression

### ISSUE THREAD

**Issue by iravid** [elastic/elasticsearch#11750]
Hi, ran into a bug while working with the query_string query. Here's a sample of my data:

``` javascript
  {
    "name": "document1",
    "tags": {
      "source1": { "tag1A": "A", "tag1B": "B" },
      "source2": { "tag2A": "A", "tag2B": "B" }
    }
  },
  {
    "name": "document2",
    "tags": {
      "source1": { "tag1A": "A", "tag1B": "B" },
      "source2": { "tag2C": "C", "tag2D": "D" }
    }
  }
```

Here's the query I'm running:

``` javascript
GET test_index/test_type/_search
  {
    "query": {
      "filtered": {
        "filter": {
          "query": {
            "query_string": {
              "query": "name:document1 AND tags.\\*.tag1E:A"
            }
          }
        }
      }
    }
  }
```

For some reason, this query returns the `document1` document, even though it has no field that matches `tags.\\*.tag1E`.

The equivalent query that uses the "and" filter to combine the predicates works correctly and returns no documents:

``` javascript
GET test_index/test_type/_search
  {
    "query": {
      "filtered": {
        "filter": {
          "and": {
            "filters": [
              {
                "query": {
                  "query_string": {
                    "query": "name:document1"
                  }
                }
              },
              {
                "query": {
                  "query_string": {
                    "query": "tags.\\*.tag1E:A"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
```

Am I doing anything wrong here?

**Comment by clintongormley** [comment]
A wildcarded field path which maps to no fields gets excluded.  eg:

    GET _validate/query?explain
    {
      "query": {
        "query_string": {
          "query": "name:document1 AND tags.\\*.tag1E:A"
        }
      }
    }

returns:


      {
         "index": "t",
         "valid": true,
         "explanation": "name:document1"
      }

**Comment by iravid** [comment]
Hey Clinton, thanks for pointing that out. Does clear up things. I'd say
that a field path that maps to no fields should be evaluated as false in
the Boolean expression.
On Thu, Jun 18, 2015 at 22:40 Clinton Gormley <notifications@github.com>
wrote:

> A wildcarded field path which maps to no fields gets excluded. eg:
>
> GET _validate/query?explain
> {
>   "query": {
>     "query_string": {
>       "query": "name:document1 AND tags.\\*.tag1E:A"
>     }
>   }
> }
>
> returns:
>
>   {
>      "index": "t",
>      "valid": true,
>      "explanation": "name:document1"
>   }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch/issues/11750#issuecomment-113268318>
> .
>
-- 
Itamar

**Comment by javanna** [comment]
@elastic/es-search-aggs

**Comment by cbuescher** [comment]
> A wildcarded field path which maps to no fields gets excluded.

This is a fairly old issue, I just checked the current behaviour on 6.5 and the query seems to be handled now as expected, returning no documents for the above case:

```
GET test/_doc/_validate/query?explain
{
  "query": {
    "query_string": {
      "query": "name:document1 AND tags.\\*.tag1E:A"
    }
  }
}
```
gives
```
"explanations" : [
    {
      "index" : "test",
      "valid" : true,
      "explanation" : """+(+name:document1 +MatchNoDocsQuery("unmapped field [tags.*.tag1E]")) #*:*"""
    }
  ]
```

Because of that I will close this issue, please reopen if there is anything I'm missing.
