### ISSUE TITLE
Fields not searchable with subobjects: false and dynamic: false when sent as nested objects

### ISSUE THREAD

**Issue by flash1293** [elastic/elasticsearch#117544]
### Elasticsearch Version

main

### Java Version

_bundled_

### OS Version

Darwin Mac 24.1.0

### Problem Description

When `subobjects: false` and `dynamic: false` are used together in an index, fields are not searchable if the documents are sent as nested objects.

### Steps to Reproduce

Prepare:
```
PUT my-index
{
  "mappings": {
    "subobjects": false,
    "dynamic": false,
    "properties": {
      "my.keyword.field": {
        "type": "keyword"
      }
    }
  }
}

POST my-index/_doc
{
  "my": {
    "keyword.field": "abc"
  }
}
```

```
GET my-index*/_search
{
  "fields": [
    "*"
  ]
}
```

Returns 
```
        "fields": {
          "my.keyword.field": [
            "abc"
          ]
        }
```

so it looks like `my.keyword.field` is indexed properly.

However,

```
GET my-index/_search
{
  "query": {
    "match": {
      "my.keyword.field": "abc"
    }
  }
}
```

does not return any hits.

* When setting `dynamic: true`, the match-search works as expected (even though the mapping looks exactly the same)
* When setting `subobjects: true`, the match-search works as expected
* When sending the doc as `{ "my.keyword.field": "abc" }`, the match-search works as expected

**Comment by flash1293** [comment]
cc @martijnvg - maybe you have an idea

**Comment by lkts** [comment]
The result of `fields` parameter is misleading here, not sure why. There is no field `my.keyword.field` in Lucene document in this case. I think that object auto-flattening indirectly depends on dynamic updates somehow causing this bug.
