### ISSUE TITLE
Rescore script: aggregation from a main query

### ISSUE THREAD

**Issue by alexkuk** [elastic/elasticsearch#11775]
I wonder if there's is a way to solve my issue.
1. I have an int field visits_number, and I would like to use it as an additional factor in a score calculation
2. I have an outer query, and a rescore query. 
3. In a rescore query I have a groovy script, where I'd like to have something like avg(visits_number) available - an average visits_number calculated for an outer query results.

**Comment by clintongormley** [comment]
Hi @alexkuk 

I'm assuming you mean that you'd calculate the avg visits_number across all docs (or across all matching docs) and then use it in the score calculation?  If so, then no, there's no automatic way of doing this.  Essentially you'd require two requests: one to calculate the avg then another to apply that value to the search hits.

This is what Elasticsearch would have to do as well.  You can already do this today with two search requests. There's no real advantage to Elasticsearch doing it for you in this case.

thanks

**Comment by alexkuk** [comment]
Thx for the answer. 
Sure. I see your point and I already implemented it. But I thought that when ES does rescoring, it already has the data returned by the main query. So I thought probably it's possible to access this data from rescore scripts.
