### ISSUE TITLE
Incorrect casting in FielddataTermsFilter equality

### ISSUE THREAD

**Issue by rendel** [elastic/elasticsearch#11779]
Hi Adrien,

it looks like there is a small bug in the `equals` method implementation that has been introduced by #10728. Each subclass tries to cast to `BytesFieldDataFilter` the object passed as parameter to the equals method, instead of trying to cast to their own class. For example, the `LongsFieldDataFilter#equals` method should contain
```
return terms.equals(((LongsFieldDataFilter) obj).terms);
``` 
and not
```
return terms.equals(((BytesFieldDataFilter) obj).terms);
```

**Comment by jpountz** [comment]
Thanks @rendel  for the detailed bug report! I opened #11835
