### ISSUE TITLE
Missing docs for the `kuromoji_completion` filter

### ISSUE THREAD

**Issue by pakio** [elastic/elasticsearch#117807]
In the work of https://github.com/elastic/elasticsearch/pull/81858 `kuromoji_completion` filter was added but the documentation was not provided along with the change. To use this feature, users somehow figure out this feature on their own at the moment which is not ideal.

**Comment by PeteGillinElastic** [comment]
DM team, note that @pakio has kindly raised a PR for this: https://github.com/elastic/elasticsearch/pull/117808.
