### ISSUE TITLE
Provide warning in log files when shards cannot be allocated due to version differences

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#11781]
This is related to https://github.com/elastic/elasticsearch/issues/9471 previously filed.

This is to simulate a condition during rolling restart upgrade.  When performing rolling restart upgrade and there are nodes in the cluster running an older version (eg. 1.4, node1 below) and a newer version (eg. 1.5, node_name below).  If new indices are created repeatedly during this time, some of the replica shards can become unassigned (expected).  

![image](https://cloud.githubusercontent.com/assets/7216393/8259654/faedf854-1672-11e5-9949-57dc8dc4b70a.png)

And a reroute command (if you attempt to allocate the replicas manually: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-reroute.html) will return the following intuitive explanation:

```json
            {
               "decider": "node_version",
               "decision": "NO",
               "explanation": "target node version [1.4.2] is older than source node version [1.5.0]"
            },
```

This is great, except that the administrator has no way of telling from the logs unless they go and try to run the reroute command with explain directly because we don't appear to be logging anything into the log files indicating the reason (not even at cluster.service: TRACE level).

This is a request to provide this information right at the INFO or WARN level so that the admins will know that there is not enough (newer verison, eg. 1.5.0) to allocate those replicas at that point in time.

**Comment by s1monw** [comment]
I can see how this is useful but it's hard to distinguish between the cases when to log it and when not. I tried to think about a good way to log this by default but I can't come up with a good solution unfortunately

**Comment by clintongormley** [comment]
Could this exception be shown in the `store_exception` added in https://github.com/elastic/elasticsearch/pull/11545?

**Comment by bleskes** [comment]
@clintongormley that exception is indicative that the lucene index in the store can not be opened. Doesn't seem to be the right place to indicate that a shard is unassigned because there is no node that accommodate it. We need to find a more generic way to do report this and I think Pius was asking for a way that can be analyzed in retrospect.

**Comment by msimos** [comment]
+1 this message should be always logged when deciding to assign replicas.

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/14593
