### ISSUE TITLE
Open Murmur3Hasher#update

### ISSUE THREAD

**Issue by scampi** [elastic/elasticsearch#117883]
### Description

Murmur3Hasher is a great class as it allows to hash a stream of bytes. However, the `update` method that takes the slice of a byte array is private, thus limiting the usefulness of the class

https://github.com/elastic/elasticsearch/blob/b1412f65b90893c3d29756c921c32d39f3172a65/server/src/main/java/org/elasticsearch/common/hash/Murmur3Hasher.java#L43

Please consider making it public!

**Comment by dnhatn** [comment]
@scampi I have exposed this method in https://github.com/elastic/elasticsearch/pull/117961. Thanks very much for your interest in Elasticsearch.

**Comment by scampi** [comment]
Thanks for the change🙂
