### ISSUE TITLE
`series_arithmetic` aggregation throws `aggregation_execution_exception`

### ISSUE THREAD

**Issue by HammadH** [elastic/elasticsearch#11786]
Hi,

I am trying to use `series_arithmetic` aggregator ( I have cloned master ) to calculate a ratio from 2 buckets but I get `aggregation_execution_exception`. 

This is the mapping:
   
    {
    "listings": {
        "mappings": {
            "listing": {
                "_size": {
                    "store": true
                },
                "_timestamp": {
                    "store": false
                },
                "properties": {
                    "agencyName": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "agencyPhoneNumber": {
                        "type": "string"
                    },
                    "agentName": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "agentPhoneNumber": {
                        "type": "string"
                    },
                    "amenities": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "area": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "building": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "city": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "coordinates": {
                        "type": "geo_point"
                    },
                    "furnished": {
                        "type": "string"
                    },
                    "lastUpdate": {
                        "type": "date",
                        "format": "dateOptionalTime"
                    },
                    "listingCategory": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "noOfBathrooms": {
                        "type": "long"
                    },
                    "noOfBedrooms": {
                        "type": "long"
                    },
                    "price": {
                        "type": "long"
                    },
                    "rentalTerm": {
                        "type": "string"
                    },
                    "size": {
                        "type": "double"
                    },
                    "source": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "subarea": {
                        "type": "string",
                        "index": "not_analyzed"
                    },
                    "title": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string",
                        "index": "not_analyzed"
                    }
                }
            }
        }
    }}

And this is the query I'm running: 

    {
	"size":"0",
	"query":{
	"filtered":{
	"filter":{
	"and":[
	{"term":{"area":"X1"}}, {"term":{"listingCategory":"C1"}}, {"range":{"price":{"lte":"1000000"}}}
	]
	}
	}
	},
	"aggs":{
	"Sale":{"filter":{"term":{"type":"sale"}}, "aggs":{"price":{"percentiles":{"field":"price", "percents":[75]}}}}, 
	"Rent":{"filter":{"term":{"type":"rent"}}, "aggs":{"price":{"percentiles":{"field":"price", "percents":[75]}}}},
	"ROI":{"series_arithmetic":{"buckets_path":{"var1":"Sale>price", "var2":"Rent>price"}, "script":"var1/var2"}}
	}}

And this is the URL I'm requesting to, running elasticsearch locally

    http://localhost:9200/listings/listing/_search

And this is the error I'm getting:

    {
    "error": {
        "root_cause": [
            {
                "type": "aggregation_execution_exception",
                "reason": "Invalid pipeline aggregation named [ROI] of type [series_arithmetic]. Only sibling pipeline aggregations are allowed at the top level"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "listings",
                "node": "haHUkxYXQ_eKE1kAuNUhMw",
                "reason": {
                    "type": "aggregation_execution_exception",
                    "reason": "Invalid pipeline aggregation named [ROI] of type [series_arithmetic]. Only sibling pipeline aggregations are allowed at the top level"
                }
            }
        ]
    },
    "status": 500

Thank you.

**Comment by colings86** [comment]
The `series_arithmetic` aggregation is required to be used as a sub-aggregation to a multi-bucket aggregation (such as the `terms` aggregation or the `histogram` aggregation. Here you are trying to use it as a top-level aggregation, which is not supported.
