### ISSUE TITLE
PAMI Disconnect‏

### ISSUE THREAD

**Issue by qasimkhans** [elastic/elasticsearch#11784]
Hi,
       I am using PAMI to get Asterisk Manager Events. please see my code below. I wanted to get $event->getDialStatus() = 'ANSWER' of Dial  Event and as i get result disconnect the Asterisk Manager and read the remaining code. Thanks.

<?php 
use PAMI\Client\Impl\ClientImpl as PamiClient;

require_once 'PAMI/Autoloader/Autoloader.php';
PAMI\Autoloader\Autoloader::register();

$pamiClientOptions = array(
    'host' => '127.0.0.1',
    'scheme' => 'tcp://',
    'port' => 5038,
    'username' => 'ncs',
    'secret' => 'ncs',
    'connect_timeout' => 10000,
    'read_timeout' => 10000
);

$pamiClient = new PamiClient($pamiClientOptions);

// Open the connection
$pamiClient->open();

use PAMI\Message\Event\EventMessage;
use PAMI\Message\Event\DialEvent;

$pamiClient->registerEventListener(function (EventMessage $event) {
    print_r($event);
},
        function ($event) {

        $re = $event instanceof DialEvent && $event->getDialStatus() = 'ANSWER';

if ($re){
echo "Found Event\n";
}
  }
);

$running = true;

while($running) {
    $pamiClient->process();
    usleep(1000);
}

// Close the connection
#$pamiClient->close();

echo "Code Ended>>>>>>>>>>>>>>>>>>> Read This Line\n";
?>

**Comment by clintongormley** [comment]
Hi @qasimkhans 

please ask questions like these on the mailing list instead (and I advise explaining what the problem is, rather than just pasting your code and expecting them to figure it out).

https://discuss.elastic.co
