### ISSUE TITLE
Update ILM customization tutorial and screenshots

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#117925]
### Description

The documentation at https://www.elastic.co/guide/en/elasticsearch/reference/current/example-using-index-lifecycle-policy.html uses older language:

* It mentions "50gb" as the index size, rather than our current recommendation, which is the size of a single primary shard.
* The screenshots are of an older Kibana dashboard, for example the old version:

![image](https://www.elastic.co/guide/en/elasticsearch/reference/current/images/ilm/tutorial-ilm-hotphaserollover-default.png)

versus a newer version of the API:

![Image](https://github.com/user-attachments/assets/0862d3d5-3587-4d0a-b72e-ff4d9ea9d275)

**Comment by satyyam11** [comment]
Can I help?

**Comment by dakrone** [comment]
@satyyam11 certainly, feel free to open a PR for this, https://github.com/elastic/elasticsearch/blob/main/docs/reference/ilm/example-index-lifecycle-policy.asciidoc?plain=1 is the location of the file.

**Comment by satyyam11** [comment]
I have raised a PR 
but there ![Image](https://github.com/user-attachments/assets/3021a889-8ff1-45bb-b9cd-2211d6623429)
seems to be a issue with it can you help

**Comment by satyyam11** [comment]
At first the issue was that document wasn't signed but i did that now its showing this, should i start all over again?

**Comment by satyyam11** [comment]
Also I want to update the image and replace it with the new screenshot can you tell in which folder are they located? so that I can do that

**Comment by satyyam11** [comment]
Shalll I raise a PR for image change as well?

**Comment by satyyam11** [comment]
okay so you don't accept this PR 
I'll raise a new one with both the changes.
Is that okay?

**Comment by satyyam11** [comment]
I have raised a new PR #118148 and it has both text and image changes.

**Comment by dakrone** [comment]
Resolved by #118148
