### ISSUE TITLE
Fold `plugin` script into `elasticsearch` script with -plugin option

### ISSUE THREAD

**Issue by kimchy** [elastic/elasticsearch#11797]
Today, we highjack a generic script name called `plugin` to install plugins with ES. Other products might have this script name and it would be nice if we are better citizens of $PATH here. We should allow to install plugins using the `elasticsearch` script, and deprecate the `plugin` script.

**Comment by jimmyjones2** [comment]
Same as #11651?

**Comment by proegssilb** [comment]
Fixes the same problem as #11651, but different proposal. This approach would still make packaging on Linux a lot easier, unless a distro decides to replace the elasticsearch script (I don't work on distros, I don't know how likely it is).

**Comment by clintongormley** [comment]
We've decided against doing this as bin/elasticsearch should be run as the elasticsearch user, and bin/plugin as root

**Comment by jimmyjones2** [comment]
This is fine, but a bit unfortunate that downstream packagers will always have to use a different name to upstream. How about elasticsearch-plugin?

**Comment by Hubbitus** [comment]
In Fedora we already use name `elasticsearch-plugin`. But in any case as it should be compiled from source without network build procedure and start script significant than shipped upstream. Meantime it will be helpful if such distinguished name will appear in docs.

**Comment by clintongormley** [comment]
@Hubbitus this is happening in https://github.com/elastic/elasticsearch/pull/16022

**Comment by Hubbitus** [comment]
@clintongormley thank you.
