### ISSUE TITLE
SparseVectorQueryBuilderTests.testToQuery

### ISSUE THREAD

**Issue by masseyke** [elastic/elasticsearch#117998]
### CI Link

https://buildkite.com/elastic/elasticsearch-pull-request/builds/44598#01939200-5771-41d9-b062-2f317bffb9ea

### Repro line

./gradlew ":x-pack:plugin:core:test" --tests "org.elasticsearch.xpack.core.ml.search.SparseVectorQueryBuilderTests.testToQuery" -Dtests.seed=7E71170FE6E413E8 -Dtests.locale=cs -Dtests.timezone=Asia/Bahrain -Druntime.java=23

### Does it reproduce?

Yes

### Applicable branches

8.x

### Failure excerpt

> Task :x-pack:plugin:core:test
--
  |  
  | REPRODUCE WITH: ./gradlew ":x-pack:plugin:core:test" --tests "org.elasticsearch.xpack.core.ml.search.SparseVectorQueryBuilderTests.testToQuery" -Dtests.seed=7E71170FE6E413E8 -Dtests.locale=cs -Dtests.timezone=Asia/Bahrain -Druntime.java=23
  |  
  | SparseVectorQueryBuilderTests > testToQuery FAILED
  | java.lang.AssertionError
  | at __randomizedtesting.SeedInfo.seed([7E71170FE6E413E8:898A15319767D602]:0)
  | at org.junit.Assert.fail(Assert.java:87)
  | at org.junit.Assert.assertTrue(Assert.java:42)
  | at org.junit.Assert.assertTrue(Assert.java:53)
  | at org.elasticsearch.xpack.core.ml.search.SparseVectorQueryBuilderTests.testDoToQuery(SparseVectorQueryBuilderTests.java:235)
  | at org.elasticsearch.xpack.core.ml.search.SparseVectorQueryBuilderTests.testToQuery(SparseVectorQueryBuilderTests.java:225)

**Comment by davidkyle** [comment]
@kderusso `SparseVectorQueryBuilderTests` is failing on 8.x. 

Should https://github.com/elastic/elasticsearch/pull/117930 have been backported?

**Comment by kderusso** [comment]
https://github.com/elastic/elasticsearch/pull/118014
