### ISSUE TITLE
Make dev-tools and rest-api-spec projects depend on elasticsearch-parent

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#11798]
At the moment this have to depend on the sonatype parent pom because they are referenced in Elasticsearch-parent and so having elasticsearch-parent as their parent project creates a circular dependency.

Further comments about his can be found here: https://github.com/elastic/elasticsearch/pull/11752#issuecomment-113557238

**Comment by dadoonet** [comment]
@colings86 I'm unsure if we still have to fix that. WDYT?

**Comment by colings86** [comment]
@dadoonet both the projects still declare the sonatype parent pom as their parent but I have no opinion on whether that is actually an issue. Feel free to close if you think its ok as is

**Comment by dadoonet** [comment]
Thanks @colings86. Closing as your "eclipse" initial issue has been fixed.
