### ISSUE TITLE
GET _migration/deprecations doesn't show deprecations for hidden indices

### ISSUE THREAD

**Issue by valeriy42** [elastic/elasticsearch#118020]
### Elasticsearch Version

8.18

### Java Version

_bundled_

### OS Version

Linux

### Problem Description

The `GET _migration/deprecations` API in 8.18 no longer lists deprecations for hidden indices like `.ml-*` by default:
- if you run `GET _migration/deprecations` the deprecation warnings are not displayed
- if you run GET `.ml*/_migration/deprecations` they are displayed

This is a change from the previous behavior in 7.17, where `GET _migration/deprecations` would list the deprecation for `.ml*` indices in the `index_settings` part and the deprecation for ML model snapshots in the `ml_settings` part.

This change in the API behavior breaks the expected workflow in Kibana Update Assistant in 8.18 since now no ES deprecation warnings for `.ml-*` indices are shown before the major upgrade.

### Steps to Reproduce

1. Set up a cluster in 7.17
2. Create an anomaly detection job, e.g. using kibana flights data
3. Upgrade the cluster to 8.18
4. Run `GET _migration/deprecations` in Dev Console

**Comment by sophiec20** [comment]
This is blocking being able to test e2e migrations cc @leehinman

**Comment by dakrone** [comment]
I have been able to reproduce this, when I change https://github.com/elastic/elasticsearch/blob/ec27e20c80f402e09822f5e1b4ebc7b02fc6196d/x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/DeprecationInfoAction.java#L369 to include hidden indices, then it sees the hidden index. Hopefully it will be a simple fix in that case.
