### ISSUE TITLE
Retrieving `_ttl` rebases the expiration date against `now()` instead of the value of `_timestamp`

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#11809]
When you index a document with a `_ttl`, what we store/index internally is the expiration date, ie. the sum of `_timestamp` and `_ttl`. However when we retrieve the value of the `_ttl`, we return the difference between the expiration date and `now()`.

While this is useful to see in how long documents will be expired, it makes it impossible to reindex a document with the exact same expiration date. In my opinion, we should return the original value of the `_ttl` instead, since it is relative to the value of `_timestamp` anyway.

**Comment by jpountz** [comment]
It would be nice to have it fixed in 2.0 to make sure that all 2.0+ indices can be safely reindexed.

**Comment by s1monw** [comment]
++

**Comment by nithyanv** [comment]
+1

**Comment by nozari** [comment]
+1

**Comment by clintongormley** [comment]
Closing in favour of #18280
