### ISSUE TITLE
Add option to the search api to deal with unmapped fields

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#11806]
The way queries and aggregations deal with with unmapped fields is inconsistent. For example the `nested` query fails if the defined `path` doesn't point to an object field, but the `nested` aggregator doesn't fail and just returns an empty bucket. How the search api should deal with unmapped fields is application specific, so how ES should deal with unmapped fields should become controllable from the search api.

The idea is to add `unmapped_fields` top level field to the search api (and maybe also be settable via a query string parameter). All features that interact with the mapping (queries, aggregations) should take this setting into account and act accordingly.

The `unmapped_fields` field should support the following setting:
* `error`, returns a parse error if a field can't be resolved by the mapping. I think this should be the default.
* `ignore`, ignores the query or aggregation in question and returns no results.
* `warn`, like `ignore`, but also prints a warning in the log if a field can't be resolved.

I think initially we should support the `unmapped_fields` option for the following queries/aggregations:
* `nested` query.
* `has_child` query.
* `has_parent` query.
* `nested` aggregation.
* `reverse_nested` aggregation.
* `children` aggregation.
* Maybe also the features around geo point and geo shape?

See PR #9521 for the initial discussion.

**Comment by rjernst** [comment]
+1

But why have the parameter start with an underscore? I think it should just be `unmapped_fields`?

**Comment by martijnvg** [comment]
> But why have the parameter start with an underscore?

I copied this from the discussion in the pr... but yes, it should be without underscore.

**Comment by clintongormley** [comment]
Three questions:

* Should this be top-level or per query/agg?  (more control if the latter)
* Should the behaviour be configurable to include/exclude results (eg consider this a match if it doesn't have the field)
* Should the default be strict or lenient?

**Comment by martijnvg** [comment]
> Should this be top-level or per query/agg? (more control if the latter)

Initially the idea is to expose it as a top level option, we already have many options on aggs and queries. But if we really need to we can the option on the each query and agg.

> Should the behaviour be configurable to include/exclude results (eg consider this a match if it doesn't have the field)

Good question. I think think this should be configurable via an extra setting or extra `unmapped_fields` option next to `ignore`.

> Should the default be strict or lenient?

I prefer to be explicit about these kind of misconfigurations, so strict.

**Comment by clintongormley** [comment]
> Initially the idea is to expose it as a top level option, we already have many options on aggs and queries. But if we really need to we can the option on the each query and agg.

I'm not so sure. Practically, you probably want to target a specific field, rather than all fields everywhere, eg "if no geo-point is specified, then include or exclude those docs".

> I prefer to be explicit about these kind of misconfigurations, so strict.

In other words, this would break:

    PUT foo/user/1
    {
      "name": "joe bloggs"
    }
    
    PUT bar/user/1
    {
      "full_name": "joe bloggs"
    }
    
    GET _search?name=joe

I'm leaning towards defaulting to leniency, which is what we do for most fields today.

**Comment by clintongormley** [comment]
This is what we do with sorting today: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_ignoring_unmapped_fields

**Comment by rjernst** [comment]
> In other words, this would break:
```
PUT foo/user/1
{
  "name": "joe bloggs"
}
PUT bar/user/1
{
  "full_name": "joe bloggs"
}
GET _search?name=joe
```

That should not fail. It will find the `name` field type at the index level. It will simply not match any documents in the `bar` type.

**Comment by rjernst** [comment]
Bah, disregard my last comment, I mistook foo/bar for types... :/

**Comment by clintongormley** [comment]
@rjernst `foo` and `bar` are diffrent indices.  The equivalent of this will fail today for (eg) geo queries

**Comment by rjernst** [comment]
But regarding that, this seems like something a user should be made aware of? If they are trying to do a search across multiple indexes, in which the fields they are using don't exist, they should have to actively decide what to do, not just get some default behavior that they don't know exists? Being strict will ensure they are aware, while being lenient will continue to lead to users asking why they aren't matching documents when they eg mispelled a field name.

**Comment by clintongormley** [comment]
@rjernst We already have the `explain` API which will tell you why a document doesn't match.  I argue that being strict in this case makes every day use more onerous than it needs to be, while we already have tools to debug less frequent issues like the one you mention.

**Comment by rjernst** [comment]
I don't think you should need a tool to realize you mispelled a field name. It is no different to me than mispelling a parameter.

**Comment by martijnvg** [comment]
> I'm leaning towards defaulting to leniency, which is what we do for most fields today.

@clintongormley I didn't really think about regular fields, but about fields types like `nested` and `geo_shape`. In those cases I would like to be informed if I picked an incorrect field, since those fields allow to do somewhat more advanced search features instead of simple matching.

I'm unsure about simple term / match queries etc. and what to do if the field doesn't exist in the mapping. Today the parser just create a kind of a raw term query, instead of returning all or no results or fail. I think this behaviour is historic as mapping updates used to be async (in 1.x and before), so a field may not exist in the mapping yet will the document did successfully indexed.

**Comment by kmeiresonne** [comment]
> Should this be top-level or per query/agg? (more control if the latter)

I believe a top-level control should be possible. We're working extensively with dynamic templates, so in these cases when you create the index and mapping, and have no documents yet, all our built-in nested queries currently fail since the nested paths haven't been created in the mapping yet.
> Should the behaviour be configurable to include/exclude results (eg consider this a match if it doesn't have the field)

That would be nice to have, although I see little use cases to include a document in the result if it doesn't have the field.
> Should the default be strict or lenient?

In my (short) experience with elasticsearch, it has the tendency to be lenient against these type of things, so that would be my preference.

**Comment by clintongormley** [comment]
Closing in favour of #12016
