### ISSUE TITLE
Tophits aggregation for nested field ...

### ISSUE THREAD

**Issue by HemaAnusha** [elastic/elasticsearch#11819]
Hi,
Am using fields with nested type, in the mappings I kept for column1 and column2 as nested type fields..

I am using the following query to get the top hits:

GET partsfilter/partsfilter_type/_search
{
    "size": 10,
     "query" : {
        "match" : { "description" : "abc" }
    },
    "aggs" : {
        "column1" : {
            "nested" : {
                "path" : "column1"
            },
            "aggs" : {
               "col1_agg":
               {
                   "terms":
                   {
                       "field":"column1.@key",
                       "size":0
                   },
                   "aggs":
                   {
                       "top":
                       {
                           "top_hits":
                           {
                               "size":1
                           }
                       }
                   }
               }
            }
        }
    }
}

This is throwing  SearchPhaseExecutionException[Failed to execute phase [query]  exception. when am removing top_hits aggs it is working fine.
how to write a top_hits query to work for the above case..

**Comment by martijnvg** [comment]
@HemaAnusha What version of ES are you using and what exceptions are you in the response and log file?

**Comment by HemaAnusha** [comment]
Hi Mart,

Thanks for your response, I done the issue, problem is with version. Upgraded ES version from 1.4.2 to 1.5.2, now am able to use nested aggregations.

Thank you..
