### ISSUE TITLE
Elasticsearch /_nodes api vs OS for max_file_descriptors?

### ISSUE THREAD

**Issue by sinneduy** [elastic/elasticsearch#11813]
When I check the /_nodes/process API:

```
"process":{"refresh_interval_in_millis":1000,"id":14588,"max_file_descriptors":65535,"mlockall":false}}
```
 

But when I check the OS (Ubuntu 14.04) for max file descriptors, it shows 1024:

```
# ulimit -n
1024
```

I'm inclined to believe the OS over elasticsearch, and when I check the number in use, its <1024:

```
/proc/12799/fd# ls -l | wc -l
504
```

But why would elasticsearch misreport this?

```
# curl localhost:9200
{
  "status" : 200,
  "version" : {
    "number" : "1.5.2",
    "build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
    "build_timestamp" : "2015-04-27T09:21:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by sinneduy** [comment]
I just updated the file descriptor limit in the OS, but I find it very strange that you could see contradictory values like that.  Could someone clarify in documentation how the file descriptor total is determined by ES?

**Comment by clintongormley** [comment]
Presumably because the Ubuntu script sets it for you? https://github.com/elastic/elasticsearch/blob/1.6/src/packaging/common/packaging.properties#L18

**Comment by sinneduy** [comment]
I'm on 1.5.2 though, and the code you're referencing is 1.6?

Also, shouldn't a note be stated that this gets automatically set for ubuntu here: https://www.elastic.co/guide/en/elasticsearch/guide/current/_file_descriptors_and_mmap.html

**Comment by clintongormley** [comment]
@sinneduy also set in 1.5.2: https://github.com/elastic/elasticsearch/blob/1.5/src/deb/systemd/elasticsearch.service#L19

> Also, shouldn't a note be stated that this gets automatically set for ubuntu here:

This info is already provided here: https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-service.html

**Comment by sinneduy** [comment]
@clintongormley Do you think that it might be worth linking the page I referenced to yours?

**Comment by clintongormley** [comment]
@sinneduy I don't think so. The Definitive Guide has a different purpose from the Reference. I think that users who choose to use a package should read the reference docs for that package.
