### ISSUE TITLE
Upgrading 1.4.2 to 1.5.2 is not providing the data to 1.5.2 which was there in 1.4.2 

### ISSUE THREAD

**Issue by HemaAnusha** [elastic/elasticsearch#11821]
Hi,
Am upgrading elasticsearch 1.4.2 to 1.5.2 
For that I have done
1) copied the config file of 1.4.2 and pasted that in 1.5.2...

when am looking for the indexes in 1.5.2, I am unable to see the indexes which I have created in 1.4.2 .
So how to upgrade to higher version by keeping the indexes and data as it is which were there in old version

**Comment by markwalkom** [comment]
You will not lose data like this with an upgrade.

I'd recommend you join us in #elasticsearch on Freenode or at https://discuss.elastic.co/ for troubleshooting help, we reserve Github for confirmed bugs and feature requests :)
