### ISSUE TITLE
Correct Korean numeral format in ES document

### ISSUE THREAD

**Issue by getsolaris** [elastic/elasticsearch#118233]
PR: https://github.com/elastic/elasticsearch/pull/118232

The current ES document represents the number 1000006005001 as "조육백만오천일", which omits the standard usage of "일" in large numeral formats.

This issue aims to update the numeral representation to "일조육백만오천일", aligning with the standard and improving clarity for users.

**Comment by john-wagster** [comment]
Taking a look now!

**Comment by john-wagster** [comment]
PR merged.  Thanks much @getsolaris!
