### ISSUE TITLE
Rename cluster state uuid

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#11831]
The cluster state diffs introduced a concept of cluster state uuid that is uniquely identifying a particular iteration (version) of the the cluster state. This uuid is ephemeral and changes with each cluster state update, which causes confusion with other 2 uuids in the system - metadata uuid and index metadata uuid which are persistent. We need to rename cluster state uuid to reflect the difference in use and lifecycle.

**Comment by s1monw** [comment]
++

**Comment by imotov** [comment]
If somebody has a good name for it to renamed to, please let me know. Rejected proposals so far:
* `id` - too generic, can be perceived as a persistent identification the same way as uuid today
* `instanceId` - the term instance is used as a synonym for a node everywhere in documentation
* `updateId` - rejected by the reviewer 
* `diffId` - rejected by the reviewer
* `revision` - rejected by the reviewer
* `edition` - rejected by the reviewer
* `fingerprint` - rejected by the reviewer

**Comment by pickypg** [comment]
What about

- `clusterStateId`
- `clusterStateVersionId`
- `clusterStateDiffId`
- `stepId`

**Comment by imotov** [comment]
Thanks! In my mind, `clusterStateId` implies persistence. Since we are trying to find a name for a field of a cluster state I don't think clusterState prefix is very useful here. I don't really see how `clusterStateDiffId` is better than `diffId`, for example. But to move things forward I would be ok with `versionId`, `clusterStateVersionId`, `clusterStateDiffId` or `stepId`. @bleskes?

**Comment by bleskes** [comment]
My problem with all the diff/step related things is that the field is not related to the diff, but rather to the state. A diff has from and to .  The versionId related things are confusing w.r.t the existing version field.

I took a step back and I think this is may be difficult because we are trying to rename the wrong thing. Instead we should rename the uuid on the IndexMeta to indexUUID and the one on the MetaData to clusterUUID . I think things fall together nicely (https://github.com/elastic/elasticsearch/compare/master...bleskes:cs_uuid ) . @pickypg @imotov how would you feel about that?

**Comment by imotov** [comment]
I think renaming uuid in IndexMetaData and MetaData wouldn't hurt. However, I don't think that step, updated and revision has anything to do with diffs. They simply emphasize transient nature of this id as related to iterations, updates, or revisions (whatever you want to call them) of the cluster state without overloading term "instance" that is already used in several places.

**Comment by clintongormley** [comment]
`generation` or `generation_id`?

**Comment by imotov** [comment]
That would work for me as well.

**Comment by bleskes** [comment]
copying a comment from #11914 here, to have everything in one place:

> Sorry I misunderstood your proposal. I thought you want to rename MetaData.uuid into MetaData.metaDataUUID. In my opinion renaming MetaData.uuid into MetaData.ClusterUUID (persistent) while keeping ClusterState.uuid (transient) is extremely confusing and is much worse than what we have today. I don't think we should get this in until we fix #11831.

OK. Naming is hard :) . I'm going give it one last shot before letting this go for a week or so. How about

-> ClusterState.uuid -> stateUUID (transient)
-> MetaData.uuid -> clusterUUID (persistent)
-> IndexMetaData.uuid -> indexUUID (persistent).

(brace, brace)

**Comment by pickypg** [comment]
I like the "smurf" naming approach. Each field becomes much clearer and much simpler.

I might suggest making the transient ones more obvious though by calling them out as such: `transientStateUUID` (or if there will only be one, then maybe even `transientUUID`). Just to add more problems, "state" has a lot of potential associations (it's too generic), but as long as it's directly tied to the cluster state, then I'm okay with it.

**Comment by clintongormley** [comment]
I'm good with the proposal in https://github.com/elastic/elasticsearch/issues/11831#issuecomment-116717240

**Comment by imotov** [comment]
That works for me as well.
