### ISSUE TITLE
Request to use rescore with retriever for ES Query DSL

### ISSUE THREAD

**Issue by bobby-ohouse** [elastic/elasticsearch#118327]
### Description

First, I'm grateful for your work and SW and look forward to your new design of "retrievers".

However, currently, Elasticsearch does not support using rescore in conjunction with retrieve API. 
Even, a standard retriever, which has 'query', does not support rescore. 
That means, unfortunately, I realized if I'm not missing something, there is no way to migrate the previous Query DSL having rescored into the new design

Adding this rescore capability is required to enhance the flexibility and precision of search workflows significantly in our examples. 
Rescoring is a powerful tool to refine the ranking of top-k results after an initial retrieval query, and enabling this combination could address numerous real-world use cases, such as personalized ranking and boosting relevance based on secondary scoring logic.

## Feature Request

I propose enhancing Elasticsearch to allow rescore operations to be integrated seamlessly with retrieval queries. Specifically, the feature should support:

```bash
{
"retriever": {...},
"rescore": [{...}],
}
```

Hybrid Rescoring: Allowing rescoring over retrieval results generated by a combination of text-based queries, vector searches, or other retrieval methods.
Customizable Pipelines: Defining custom rescoring logic (e.g., script-based, machine learning model inference) post-retrieval.

## Expected Use Cases

Personalized Recommendations: Use retrieval for candidate selection and rescore using user-specific preferences or behavior data.
Semantic Search: Enhance the ranking of results retrieved through semantic or vector-based search with additional scoring layers.
E-commerce Applications: Rank products based on business-specific signals such as user reviews, sales data, or clickstream analysis.
Benefits
Improved Search Quality: Enable more precise ranking mechanisms to surface the most relevant results.
Flexibility: Combine multiple ranking signals for complex search scenarios.
Efficiency: Optimize workflows by allowing rescoring to target the top-k results instead of recalculating scores for the entire result set.

**Comment by benwtrent** [comment]
I think a better API would be:

- a rescore retriever 
- having "rescore" within particular retrievers (like standard).

But I agree, this is a gap in our feature and we want to fix it.

**Comment by bobby-ohouse** [comment]
@benwtrent 

Thank you for the response and for considering this feature!

I think, having a rescore retriever is a cleaner and more extensible API design. It would allow for better modularity and flexibility, especially in scenarios where multiple retrievers are used.

Allowing a rescore retriever to aggregate multiple retrievers and apply rescoring logic would be highly beneficial, especially for the below scenarios.

Layered Ranking Pipelines: The rescore retriever could take the results from one or more primary retrievers and apply additional logic (e.g., ML-based scoring, domain-specific scripts).
Hybrid Retrieval + Rescoring: Easily combine traditional text-based methods with dense vector search, then rescore based on contextual or user-specific data.
Interoperability: Encourages experimentation by allowing users to chain different retrievers in a flexible, reusable manner.

**Comment by jimczi** [comment]
> I think, having a rescore retriever is a cleaner and more extensible API design if it receives several retrievers like rrf.

Yes, that was the goal with the new retriever design, allowing retrievers to be added anywhere in the tree seamlessly. To enable this with `rescorer`, I opened [PR #118585](https://github.com/elastic/elasticsearch/pull/118585), which introduces a new generic retriever for rescorer. This is quite powerful, as it enables rescoring to be applied directly at the data source, regardless of the parent or child retrievers involved.
