### ISSUE TITLE
[DOC] Multi-level nested query syntax, add more clarity in docs.

### ISSUE THREAD

**Issue by RanadeepPolavarapu** [elastic/elasticsearch#11830]
Nested query on one level is working great, but after the second level onwards (nesting) the query returns no results.

Here is my example:

```
{
    "mappings": {
        "customers": {
            "properties": {
                "lastUpdated": {
                    "type": "long"
                },
                "isDeleted": {
                    "type": "boolean"
                },
                "person": {
                    "type": "nested",
                    "properties": {
                        "car": {
                            "type": "nested",
                            "properties": {
                                "model": {
                                    "type": "string"
                                },
                                "make": {
                                    "type": "string"
                                }
                            }
                        },
                        "last_name": {
                            "type": "string"
                        },
                        "first_name": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}
```

My documents:

```
{
    "person": {
        "first_name": "Zach",
        "last_name": "Foobar",
        "car": [
            {
                "make": "Saturn",
                "model": "SL"
            },
            {
                "make": "Subaru",
                "model": "Imprezza"
            }
        ]
    },
    "isDeleted": false,
    "lastUpdated": 1433257051959
}

{
    "person": {
        "first_name": "Bob",
        "last_name": "Doe",
        "car": [
            {
                "make": "Saturn",
                "model": "Imprezza"
            },
            {
                "make": "Honda",
                "model": "Accord"
            }
        ]
    },
    "isDeleted": false,
    "lastUpdated": 1433257051959
}
```

Lastly, my query and result:

```
{
    "query": {
        "nested": {
            "path": "person",
            "query": {
                "match": {
                    "person.car.make": "Honda"
                }
            },
            "inner_hits": {}
        }
    }
}

{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}
```

---

EDIT: So, It seems that this query works, but not the one above. 

```
{
    "query": {
        "nested": {
            "path": "person",
            "query": {
                "match": {
                    "person.car.make": "Honda"
                }
            },
            "inner_hits": {}
        }
    }
}
```

I would suggest adding more clarity in the docs for multi-level nested queries about the path and query path. The [doc](https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-query.html)  for nested query should be enhance for multi-level nesting.

**Comment by martijnvg** [comment]
Hey @RanadeepPolavarapu you need to use two `nested` queries to get this working correctly:

```json
{
    "query": {
        "nested": {
            "path": "person",
            "query": {
                "nested" : {
                    "path" :  "person.car",
                    "query" :  {
                       "match": {
                           "person.car.make": "Honda"
                        }
                    }
                }
            },
            "inner_hits": {}
        }
    }
}
```

**Comment by martijnvg** [comment]
ES should do a better job at failing your query here instead of just returning no results. Issue #9255 will implement `nested` query validation.

**Comment by RanadeepPolavarapu** [comment]
Hi @martijnvg ,

Thank You, your reply was very helpful.

I see both queries (mine and the one you provided) work, but which one is preferred? Is one better to use over the other? Does one adhere to the ES standard better than the other? One does two nested queries and the other accesses the nested object using I guess nested dot notation (for lack of a better term)?

    {
        "query": {
            "nested": {
                "path": "person",
                "query": {
                    "nested" : {
                        "path" :  "person.car",
                        "query" :  {
                           "match": {
                               "person.car.make": "Honda"
                            }
                        }
                    }
                },
                "inner_hits": {}
            }
        }
    }

    {
        "query": {
            "nested": {
                "path": "person",
                "query": {
                    "match": {
                        "person.car.make": "Honda"
                    }
                },
                "inner_hits": {}
            }
        }
    }

**Comment by martijnvg** [comment]
@RanadeepPolavarapu You should use the first query. The second query shouldn't work, because it is incorrect. Not sure why it works on your side, but I tried it out and the second query doesn't work here.

**Comment by syzspectroom** [comment]
is there any way to query nested fields using wildcard in path? 
my document:

    {
       "source": "forbes",
       "external_id": "1234",
       "versions": {
          "en": {
             "title": "title en",
             "content": "content en"
          },
          "localized_en": {
             "title": "title localized en",
             "content": "content localized en"
          },
          "fr": {
             "title": "title fr",
             "content": "content fr"
          }
       }
    }

and I need to do query like this:

    {
       "query": {
          "nested": {
             "path": "versions",
             "query": {
                "multi_match": {
                   "query": "content",
                   "fields": [
                      "versions.*.content"
                   ]
                }
             }
          }
       }
    }

but didn't get any results

**Comment by roxma** [comment]
If I have two nested fields, how do I perform a query on both of them?

```
{
    "mappings": {
        "customers": {
            "properties": {
                "lastUpdated": {
                    "type": "long"
                },
                "isDeleted": {
                    "type": "boolean"
                },
                "person": {
                    "type": "nested",
                    "properties": {
                        "car": {
                            "type": "nested",
                            "properties": {
                                "model": {
                                    "type": "string"
                                },
                                "make": {
                                    "type": "string"
                                }
                            }
                        },
                        "last_name": {
                            "type": "string"
                        },
                        "first_name": {
                            "type": "string"
                        }
                    }
                }
            }
            "person2": .......................
        }
    }
}
```

For example, How do I perform a query on person and person2 ?

**Comment by abhishek5678** [comment]
Hi Guys,
In this data when i am trying with one level nested data then it's working fine but when i am adding one more nested data then it's not working if anybody will be knows about that then please reply me.I am sending my document data and mapping file also.

POST /test_word14/doc/1
{
"name": "Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism (D50-D89)",
"depth": 1,
"children": [{
"name": "Nutritional anemias (D50-D53)",
"depth": 2,
"children": [{
"code": "D50",
"name": "Iron deficiency anemia",
"depth": 3,
"children": [{
"code": "D50.0",
"name": "Iron deficiency anemia secondary to blood loss (chronic)",
"depth": 4
}, {
"code": "D50.1",
"name": "Sideropenic dysphagia",
"depth": 4
}, {
"code": "D50.8",
"name": "Other iron deficiency anemias",
"depth": 4
}, {
"code": "D50.9",
"name": "Iron deficiency anemia, unspecified",
"depth": 4
}]
}]
}]
}

(mapping file)
PUT /test_word16
{
"mappings": {
"doc": {
"properties": {
"name": { "type": "string" },
"depth": {"type":"long"},
"children": {
"type": "nested",
"properties": {
"name": { "type": "string" },
"depth": { "type": "long" },
"children": {
"type": "nested",
"properties": {
"code": { "type": "string" },
"name": { "type": "string" },
"depth": { "type": "long" },
"children": {
"type": "nested",
"properties": {
"code": { "type": "string" },
"name": { "type": "string" },
"depth": { "type": "long" },
}
}
}
}
}
}
}
}
}
}

please tell me what is the query i am applying here.i applied the query like this:
GET /icd10_codes/doc/_search
{
"_source": false,
"query": {
"nested": {
"path": "children",
"query": {
"nested": {
"path": "children.children",
"query": {
"nested": {
"path": "children.children.children",
"query": {
"bool": {
"must": [
{
"match": {
"children.children.name": "Iron"
}
}
]
}
},
"inner_hits": {
"_source": {
"excludes":["name"]
}
}
}
}
}
}
}
}

**Comment by siddharth1199** [comment]
Hi guys, i have a query with 2 bool conditions as follows:

GET /resume/candidates/_search
{
    "query": {
        "nested" : {
            "path" : "sections",
            "query" : {
                "bool" : {
                    "should" : [
                    { "match:{"sections.skills": "CSS"} },
                    { "match:{"sections.education": "photography"} }
                    ]
                }
            }
        }
    }
}

When I run the 2 match queries independently, I get results pointing towards the same document. However, when i combine and run the, it does not return any result. Can anyone please help?

Mapping:

PUT /resume
{
"mappings" : {
  "candidates" : {
   "properties" : {
     "name": { "type" : "text" },
     "phone":{ "type" : "text" },
     "email":{ "type" : "text" },
     "sections": {
       "type": "nested",
       "properties": {
         "introduction":{"type":"text"},
         "summary":{"type":"text"},
         "awards":{"type":"text"},
         "achievements":{"type":"text"},
         "skills":{"type":"text","analyzer":"keyword"},
         "education":{"type":"text"},
         "work-experience": [],
         "projects":{"type":"text"},
         "extra-curricular":{"type":"text"}
  }}}}}


Data:

PUT /resume/candidates/2
{
  "name": "XXXXXXX",
  "phone": "XXXXXXXXXXXX",
  "email": "XXXXXXXXXXXXXXXXX",
  "sections": [
    {
      "introduction": "XXXXXXXXXXXXXXXi"
    },
    {
      "summary": ""
    },
    {
      "achievements": ["best photographer of the year: 2009"]
    },
    {
      "skills": [
        "APACHE",
        "CASSANDRA",
        "MYSQL",
        "CDN",
        "AMAZON CLOUD FRONT",
        "MS OFFICE",
        "HLS",
        "DASH",
        "CSS",
        "JSON",
        "RUBY"
      ]
    },
    {
      "education": [
        "XXXXXXXXXXXX Photography",
        "XXXXXXXXXXXXXXxx"
      ]
    },
    {
      "work-experience": [
        {
          "0": [
            {
              "company-name": "CREATIVE ARTISTS AGENCY, Beverly Hills, CA"
            },
            {
              "start-date": "2002"
            },
            {
              "end-date": "2004"
            },
            {
              "job-description": "XXXXXXXXXx"
            },
            {
              "designation": "Video Game Assistant"
            }
          ]
        },
        {
          
        },
        {
          "2": [
            {
              "company-name": "OC&C STRATEGY, New York, NY"
            },
            {
              "start-date": "2008"
            },
            {
              "end-date": "2009"
            },
            {
              "job-description": "XXXXXXXXXXXXXXXX"
            },
            {
              "designation": "Associate Consultant"
            }
          ]
        },
        {
          "3": [
            {
              "company-name": "XXXXXXXXXXXXX"
            },
            {
              "start-date": "2009"
            },
            {
              "end-date": "2011"
            },
            {
              "job-description": "XXXXXXXXXXXXXXXXxxx"
            },
            {
              "designation": "designer"
            }
          ]
        }
      ]
    },
    {
      "extra-curricular": ""
    },
    {
      "awards": ""
    },
    {
      "projects": [
        ""
      ]
    }
  ]
}

**Comment by lukas-gitl** [comment]
@siddharth1199 Not sure what your problem is. It looks like it should work. Formatting your json would help greatly with readability and encourage people to look at it more closely...

**Comment by Ganesh216** [comment]
when I am running this query 
{
    "query": {
        "nested": {
            "path": "person",
            "query": {
                "nested" : {
                    "path" :  "person.car",
                    "query" :  {
                       "match": {
                           "person.car.make": "Honda"
                        }
                    }
                }
            },
            "inner_hits": {}
        }
    }
}
I am getting exception 
"error": {
        "root_cause": [
            {
                "type": "query_shard_exception",
                "reason": "failed to create query: {\n  \"nested\" :......................} 
}
 "caused_by": {
                        "type": "illegal_state_exception",
                        "reason": "[nested] nested object under path [person] is not of nested type"
                    }

Any help would be appreciated.

**Comment by simlu** [comment]
@Ganesh216 Fix your schema?

**Comment by Ganesh216** [comment]
Hi. @simlu I am using same mapping file and document mentioned above in first comment by  @RanadeepPolavarapu still getting this issue.  Can it be version specific ?

**Comment by simlu** [comment]
@Ganesh216 If you suspect this is a version problem, try to use a previous es version. If this is version specific this should be a new ticket. Otherwise make sure you set up everything exactly as in the example. This should work.

**Comment by bragboy** [comment]
+1 - I am facing the same issue as Ganesh's, my ES version is 6.1.1

**Comment by NidhiChandak** [comment]
Hi. With respect to the first example, Is there a way for me to fetch the model only where "make" is "Honda"?

**Comment by cbuescher** [comment]
cc @elastic/es-search-aggs

**Comment by debadair** [comment]
At a minimum, we should add an example of multi-level nested queries to https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-nested-query.html. A higher level discussion of using nested objects would also be helpful.

**Comment by kat257** [comment]
Working on adding example. I do notice that Issue #9255, Add nested path validation, indicates that it would close this issue, but I think the need for an example is still valid.
