### ISSUE TITLE
Add support for JDK EA builds in -Druntime.java=xx

### ISSUE THREAD

**Issue by ChrisHegarty** [elastic/elasticsearch#118329]
Improve support for the runtime JDK so that one can specify a JDK EA build to automatically download and run tests with, e.g. `-Druntime.java=24`.  The URLs are the most awkward part of this! :-(

**Comment by breskeby** [comment]
@ChrisHegarty I addressed this here: https://github.com/elastic/elasticsearch/pull/119387

We had already some support for EA runtime java versions but we need to explicitly set the version we wanna support here.
