### ISSUE TITLE
Elasticsearch start, specify the path of logging.yml in elasticsearch.yml,could not resolve placeholder 'httpfs.log.dir'

### ISSUE THREAD

**Issue by Judyccb** [elastic/elasticsearch#11856]
![image](https://cloud.githubusercontent.com/assets/12627595/8334902/f90c4726-1acc-11e5-931f-b76abc56cb71.png)

**Comment by clintongormley** [comment]
Hi @Judyccb 

Your config file contains a placeholder that you are supposed to replace with a concrete value when you start Elasticsearch.  Elasticsearch complains because you are not setting this. This is your own custom local setup, not to do with Elasticsearch itself.

**Comment by Judyccb** [comment]
Hi,
Do you know which placeholder I need to replace? I just want to use the default value of the logging.yml, do not want to change anything. I do not find 'httpfs.log.dir' parameter in the logging.yml，which is as follow.
![image](https://cloud.githubusercontent.com/assets/12627595/8390376/ce8518fa-1cc2-11e5-9974-8f2bbe50ba80.png)
![image](https://cloud.githubusercontent.com/assets/12627595/8390378/e98ef8fa-1cc2-11e5-8160-08c1d6ddc7e4.png)

**Comment by clintongormley** [comment]
@Judyccb please use text, not images.  The error message tells you what to look for: `httpfs`.  Find out where that string appears in your setup.  A better place to ask questions like these is in the forum: https://discuss.elastic.co/
