### ISSUE TITLE
Highlight when query contains fields and text

### ISSUE THREAD

**Issue by effoeffi** [elastic/elasticsearch#11853]
Hello,

I'm using elasticsearch 1.6.0.
Assume having the following document indexed in elasticsearch:
```json
{
    "id" : 2,
    "user" : "jack",
    "message" : "I'm jack",
	"comment" : "my first tweet"
}
```
When query:
```json
{
  "from" : 0,
  "size" : 5,
  "query" : {
    "query_string" : {
      "query" : "user:jack first",
      "use_dis_max" : true
    }
  },
  "highlight" : {
    "pre_tags" : [ "<span class=\"mark\">" ],
    "post_tags" : [ "</span>" ],
    "order" : "score",
    "encoder" : "html",
    "require_field_match" : false,
    "fields" : {    
      "*" : {}
    }
  }
}
```
I'm using "query string query".
As you can see, my query combines field match (user:jack) and text (first).
As a result, elasticsearch will highlight the word jack in both user field and message.
But I query for user:jack, mean I want to highlight only user name jack and not jack in other fields.
I can't set require_field_match to true, because than elasticsearch will not highlight 'first'.

What should I do?

Thanks in advance,
Effi

**Comment by clintongormley** [comment]
Hi @effoeffi 

Please ask questions like these in the forum instead of on the issues list: http://discuss.elastic.co/
Also see this very similar issue: https://github.com/elastic/elasticsearch/issues/11667

thanks
