### ISSUE TITLE
_all field's analyzer is not used

### ISSUE THREAD

**Issue by nharraud** [elastic/elasticsearch#11851]
I just tried setting an analyzer for the `_all` field but it does not work. The field is still analyzed with the standard analyzer.

Here is the scenario:

```
DELETE myindex

POST myindex
{
  "settings": {
    "analysis": {
        "filter": {
          "title-synonym": {
            "type" : "synonym",
            "synonyms" : [
                "universe, cosmos"
            ]
          }
        },
        "analyzer": {
          "all-field-analyzer": {
            "tokenizer" : "whitespace",
            "filter" : ["title-synonym"]
          }
        }
    }
  },
  "mappings": {
    "record": {
        "properties": {
          "_all": {
            "type": "string",
            "analyzer": "all-field-analyzer"
          },
          "title": {
            "type": "string",
            "analyzer": "all-field-analyzer"
          }
        }
    }
  }
}

PUT myindex/record/1
{
  "title": "my big universe"
}

GET myindex/_search
{
  "query": {
    "match": {
      "title": "cosmos"
    }
  }
}

=> OK returns doc 1 thanks to synonyms.

GET myindex/_search
{
  "query": {
    "match": {
      "title": "Universe"
    }
  }
}

=> OK returns no doc because of the whitespace tokenizer

GET myindex/_search
{
  "query": {
    "match": {
      "_all": "cosmos"
    }
  }
}

=> KO returns no doc. The synonyms are not used.

GET myindex/_search
{
  "query": {
    "match": {
      "_all": "Universe"
    }
  }
}

=> KO returns doc 1 even though it should not match because of the character case.
```

Maybe I am doing something wrong. The documentation says that an analyzer can be specified for the `_all` field: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-all-field.html

```
The _all fields allows for store, term_vector and analyzer (with specific index_analyzer and search_analyzer) to be set.
```

I am using the elasticsearch 1.6 container from docker.io

**Comment by s1monw** [comment]
`whitespace` tokenizer doesn't lowercase so I think you also want a `lowercase` filter before the synonym filter to fix that... Please use the mailing list instead for questions like this.

**Comment by johtani** [comment]
Hi @nharraud ,

please ask questions like these on the mailing list instead.

https://discuss.elastic.co

And you should put `_all` section before `properties` and after `record` in mappings section. Your mapping put wrong place...

**Comment by nharraud** [comment]
Thank you. I know about the mailing but I just didn't see my mistake and after trying for some time assumed it was a bug. My bad.

However it seems to me that this shows another issue. Maybe creating a custom `_all` field without explicitly disabling the default `_all` field should return an error? Especially if the new field cannot be accessed.
Once I disable the default `_all` field with `"_all": { "enabled": false }`. I have a normal behavior, i.e. no result for the two last queries.

**Comment by clintongormley** [comment]
Relates to https://github.com/elastic/elasticsearch/issues/10456
