### ISSUE TITLE
Performance degradation after upgrading from 8.6.1 to 8.16.1

### ISSUE THREAD

**Issue by gregolsen** [elastic/elasticsearch#118623]
### Elasticsearch Version

8.16.1

### Java Version

_bundled_

### OS Version

6.1.112-124.190.amzn2023.aarch64

### Problem Description

After starting an upgrade from 8.6.1 to 8.16.1 we noticed that data nodes running new version are performing worse.
Their CPU was significantly higher than on the data nodes with the old version:
<img width="1594" alt="Image" src="https://github.com/user-attachments/assets/f5ca3899-ce46-49de-9587-9380e38bbefd" />

We also noticed that new version nodes have much higher flush rate:
<img width="1588" alt="Image" src="https://github.com/user-attachments/assets/d3cc7905-242e-42ae-8078-649831089b4d" />

It doesn't matter whether an old node is upgraded to 8.16.1 or a brand new node spun up with 8.16.1 - they all show same symptoms of higher CPU and much higher flush rate degrading performance of the cluster as a whole.

We added more data nodes with the new 8.16.1 version and now have a cluster with 35 "old" nodes and 36 "new" nodes.
New nodes are consuming twice more CPU and have much higher flush rate:
<img width="1587" alt="Image" src="https://github.com/user-attachments/assets/bfcc8d4b-eba9-47da-aaa1-7ab7a23253a4" />
<img width="1591" alt="Image" src="https://github.com/user-attachments/assets/b36c9483-028f-40da-a4f8-08ca44e10fe1" />

Another notable difference is how new nodes have higher cache size:
<img width="1174" alt="Image" src="https://github.com/user-attachments/assets/54ea3357-eeea-449f-9c6e-342050cf2ed9" />

The reason why we were upgrading to 8.16.1 is to mitigate [this issue](https://github.com/elastic/elasticsearch/issues/100755)

We are running Elasticsearch on EC2 with ephemeral instance store on c7gd.16xlarge. Elasticsearch version aside no changes were made to the cluster infrastructure, JVM/Elasticsearch options, etc.

### Steps to Reproduce

Upgrade a 8.6.1 data node to 8.16.1

### JVM options
```
## JVM configuration
-Xms30500m
-Xmx30500m
8-13:-XX:+UseConcMarkSweepGC
8-13:-XX:CMSInitiatingOccupancyFraction=75
8-13:-XX:+UseCMSInitiatingOccupancyOnly
8:-XX:+AlwaysPreTouch
8:-Xss1m
8:-Djava.awt.headless=true
8:-Dfile.encoding=UTF-8
8:-Djna.nosys=true
8:-XX:-OmitStackTraceInFastThrow
8:-Dio.netty.noUnsafe=true
8:-Dio.netty.noKeySetOptimization=true
8:-Dio.netty.recycler.maxCapacityPerThread=0
8:-Dlog4j.shutdownHookEnabled=false
8:-Dlog4j2.disable.jmx=true
8:-XX:+PrintGCDetails
8:-XX:+PrintGCDateStamps
8:-XX:+PrintTenuringDistribution
8:-XX:+PrintGCApplicationStoppedTime
8:-Xloggc:logs/gc.log
8:-XX:+UseGCLogFileRotation
8:-XX:NumberOfGCLogFiles=32
8:-XX:GCLogFileSize=64m
9-:-Djava.locale.providers=COMPAT
-Des.index.memory.max_index_buffer_size=10240m
14-:-XX:+UseG1GC
14-:-XX:G1ReservePercent=25
14-:-XX:InitiatingHeapOccupancyPercent=30
14-:-Djava.io.tmpdir=${ES_TMPDIR}
14-:-XX:+HeapDumpOnOutOfMemoryError
14-:-XX:HeapDumpPath=data
14-:-XX:ErrorFile=logs/hs_err_pid%p.log
-Dlog4j2.formatMsgNoLookups=true
```

### Elasticsearch static node config
```
cloud.node.auto_attributes: true
cluster.routing.allocation.awareness.attributes: aws_availability_zone
action.auto_create_index: false
indices.memory.index_buffer_size: 25%
network.host: 0.0.0.0
http.compression: true
action.destructive_requires_name: true
bootstrap.memory_lock: true
thread_pool.write.queue_size: 2500
script.max_compilations_rate: 30/1m
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.watcher.enabled: false
discovery.seed_providers: ec2
indices.breaker.request.limit: 1gb
indices.breaker.fielddata.limit: 1gb
xpack.security.enabled: true
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.client_authentication: required
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: elastic-certificates.p12
transport.compress: true
transport.compression_scheme: lz4
cluster.name: CLUSTER_NAME
discovery.ec2.tag.elasticsearch_cluster_name: CLUSTER_NAME
node.name: NODE_NAME
path.data: "/media/ephemeral"
path.logs: "/var/log/elasticsearch"
reindex.remote.whitelist: 10.0.*.*:9200
node.roles:
- data
```

### Elasticsearch cluster settings
```json
{
  "persistent": {
    "cluster": {
      "routing": {
        "allocation": {
          "cluster_concurrent_rebalance": "100",
          "node_concurrent_recoveries": "100",
          "disk": {
            "watermark": {
              "low": "75%",
              "high": "85%"
            }
          },
          "node_initial_primaries_recoveries": "114"
        }
      }
    },
    "indices": {
      "breaker": {
        "fielddata": {
          "limit": "1gb"
        },
        "request": {
          "limit": "1gb"
        }
      },
      "recovery": {
        "max_bytes_per_sec": "1000mb"
      }
    },
    "search": {
      "default_search_timeout": "120s",
      "default_allow_partial_results": "false",
      "max_open_scroll_context": "500000"
    },
    "ingest": {
      "geoip": {
        "downloader": {
          "enabled": "false"
        }
      }
    },
    "logger": {
      "org": {
        "elasticsearch": {
          "deprecation": "ERROR"
        }
      }
    }
  },
  "transient": {}
}
```

**Comment by gregolsen** [comment]
@javanna sorry - my bad!
Here's an example of a node that I upgraded to 8.16.1 in place (pause shard rebalancing, stop old ES, install new version, start ES, enable allocation)
<img width="471" alt="Image" src="https://github.com/user-attachments/assets/19695085-26ca-4022-8084-7ba3d9ab896a" />

After the upgrade node's search latency got worse and never settled back into its original value, while CPU was much higher:
<img width="470" alt="Image" src="https://github.com/user-attachments/assets/32f76e15-83fc-41e2-82e9-4674ba93ffb2" />

Here's how flush rate changed for that node:
<img width="474" alt="Image" src="https://github.com/user-attachments/assets/3eac371f-6f89-4f7b-bb2e-8044ca6a3100" />

But even if all the other metrics stayed the same I would consider CPU degradation a problem as nodes doing same amount of work but consuming significantly more CPU effectively means performance is degraded and I would have to scale up the cluster after the upgrade.

**Comment by gregolsen** [comment]
I also added ES and JVM config/settings to the issue description – none of those changed between the upgrades.

**Comment by gregolsen** [comment]
I wonder if this related to the improvements introduced here https://github.com/elastic/elasticsearch/pull/94607

**Comment by gregolsen** [comment]
Another indirect indication of how performance degraded on the upgraded node - active threads in search thread pool went up:
<img width="469" alt="Image" src="https://github.com/user-attachments/assets/7eac2c96-f76e-465f-9dfd-5fcc791e1ce2" />

**Comment by gregolsen** [comment]
Another observation which may or may not be relevant is the change in query cache behavior. Looks like the query cache became more effective judging by hit rate and size, but at the same time rate of evictions increased reducing overall memory footprint. Increased evictions where mentioned [here](https://github.com/elastic/elasticsearch/issues/100755#issuecomment-2095305438) too – and get the query cache memory overcounting issue fixed was our original intent behind the upgrade.
<img width="470" alt="Image" src="https://github.com/user-attachments/assets/da5fe820-33e8-4e13-8bca-6f4ca690f1b9" />
<img width="469" alt="Image" src="https://github.com/user-attachments/assets/8c78daa2-9e8a-450c-9b00-ef4e6d1e8183" />

**Comment by javanna** [comment]
What do your queries look like? Did you identify specific ones that are slowing down more than others? Could you run them with profile enabled so that we look where time is spent?

**Comment by gregolsen** [comment]
I wasn't able to pin-point a specific query shape. I guess I would need to complete the migration and get rid of the nodes running the old version. And then compare performance of the queries on old version vs. new one.
However, given how much higher the CPU utilization is, I will have to scale up the cluster. So it won't be a fair comparison of performance.

**Comment by gregolsen** [comment]
Upon comparing hot threads API output for 8.6.1 and 8.16.1 nodes I noticed that this stack shows a lot in 8.16.1 and is missing from 8.6.1:
```
   100.0% [cpu=97.6%, other=2.4%] (500ms out of 500ms) cpu usage by thread 'elasticsearch[es-data-i-022a7c6157cb44c54][search][T#84]'
     3/10 snapshots sharing following 43 elements
       java.base@23/java.lang.invoke.VarHandleGuards.guard_LJ_I(VarHandleGuards.java:1002)
       java.base@23/jdk.internal.foreign.AbstractMemorySegmentImpl.get(AbstractMemorySegmentImpl.java:765)
       app/org.apache.lucene.core@9.12.0/org.apache.lucene.store.MemorySegmentIndexInput.readShort(MemorySegmentIndexInput.java:247)
       app/org.apache.lucene.core@9.12.0/org.apache.lucene.util.compress.LZ4.decompress(LZ4.java:113)
```

Pointing towards LZ4.decompress being slowerer in Lucene 9.12.0.
I found this https://github.com/dacapobench/dacapobench/issues/264 and considering to try out
```
-Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false
```

**Comment by ChrisHegarty** [comment]
A couple of things to check.
1. What version of the JDK is being run? The bundled version in ES 8.16.1 is JDK 23, right?
2. Are the compiler directives from [113817](https://github.com/elastic/elasticsearch/pull/113817 ) being used? That is you should see in the log line when u start ES two lines similar to "CompileCommand=dontinline,java/lang/invoke/..."

**Comment by gregolsen** [comment]
1. Correct - bundled version:
```
{"@timestamp":"2024-12-12T19:23:00.661Z", "log.level": "INFO", "message":"version[8.16.1], pid[13171], build[rpm/ffe992aa682c1968b5df375b5095b3a21f122bf3/2024-11-19T16:00:31.793213192Z], OS[Linux/6.1.119-129.201.amzn2023.aarch64/aarch64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/23/23+37-2369]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"NODE_NAME","elasticsearch.cluster.name":"CLUSTER_NAME"}
```

2. No :-( Compiled directives are not used unfortunately:
```
{"@timestamp":"2024-12-12T19:23:00.661Z", "log.level": "INFO", "message":"JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"NODE_NAME","elasticsearch.cluster.name":"CLUSTER_NAME"}
{"@timestamp":"2024-12-12T19:23:00.662Z", "log.level": "INFO", "message":"JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -Djava.security.manager=allow, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=CLDR, --enable-native-access=org.elasticsearch.nativeaccess,org.apache.lucene.core, -XX:ReplayDataFile=/var/log/elasticsearch/replay_pid%p.log, -Des.distribution.type=rpm, -Xms30500m, -Xmx30500m, -Djava.locale.providers=COMPAT, -Des.index.memory.max_index_buffer_size=10240m, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Djava.io.tmpdir=/tmp/elasticsearch-14083829021415533146, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Dlog4j2.formatMsgNoLookups=true, -XX:MaxDirectMemorySize=15997075456, --module-path=/usr/share/elasticsearch/lib, --add-modules=jdk.net, --add-modules=ALL-MODULE-PATH, -Djdk.module.main=org.elasticsearch.server]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"NODE_NAME","elasticsearch.cluster.name":"CLUSTER_NAME"}
```

**Comment by gregolsen** [comment]
As per Chris's suggestion [here](https://github.com/elastic/elasticsearch/issues/118623#issuecomment-2545292578) I added those two compiler directives and it does seem that they produce the same outcome as disabling memory segments.
I guess I should have checked the default `jvm.options` to see what was added recently.

Thank you Chris and Luca for helping out here!

**Comment by ChrisHegarty** [comment]
@gregolsen happy that this has been resolved. It surprises me a little that this has happened. Does the customer have their own jvm.options config file overriding ours, or something else?  I just wonder how common this scenario may be, and if there is something more helpful, like a knowledge article or something, that may be warranted?

**Comment by gregolsen** [comment]
@ChrisHegarty we do have our own `jvm.options` file that overrides whatever comes with the bundle (content attached in the issue description above).
I vaguely remember we came up with it a few years ago based on some recommended settings.
Our assumption was that bundled `jvm.options` is just a template file w/o anything important set.
It was unexpected for us that new ES version came with those 3 very specific options (for memory segments issue and vector) in `jvm.options`.
In hindsight, we should have done what the file recommends in comments: leave it as-is and add our own config to `jvm.options.d` directory instead.

I think knowledge article would have been helpful to make it easier to diagnose the issue with memory segments.

In general, Elasticsearch does a really good job of having default cluster settings "baked" in. For example, even if `GET /_cluster/settings` is empty the one can still rely on safe defaults. Maybe there's an argument could be made to do the same with performance-critical JVM settings like the memory segments mitigation. Yet again, maybe it is just us that override the `jvm.options` file.

**Comment by gregolsen** [comment]
I'm hesitant to re-open the issue but we've faced another issue after upgrading other clusters to 8.16.1.
ES processes started to crash after the upgrade. I managed to find this in the logs:
```
java.io.IOException: Map failed: MemorySegmentIndexInput(path="/media/ephemeral/indices/fNsj-ck6R32iz7x7rJM-3w/13/index/_16sep_Lucene90
FieldsIndex-doc_ids_wq.tmp") [this may be caused by lack of enough unfragmented virtual address space or too restrictive virtual memory
 limits enforced by the operating system, preventing us to map a chunk of 49 bytes. Please review 'ulimit -v', 'ulimit -m' (both should
 return 'unlimited'), and 'sysctl vm.max_map_count'. More information: https://blog.thetaphi.de/2012/07/use-lucenes-mmapdirectory-on-64
bit.html]
```

```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 2097152 bytes. Error detail: AllocateHeap
# Possible reasons:
#   The system is out of physical RAM or swap space
#   This process has exceeded the maximum number of memory mappings (check below
#     for `/proc/sys/vm/max_map_count` and `Total number of mappings`)
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (allocation.cpp:44), pid=242040, tid=242144
```

Our system settings seems like are what is recommended:
```
[root@es-data-i-xxxx ec2-user]# ulimit -v
unlimited
[root@es-data-i-xxxx ec2-user]# ulimit -m
unlimited
[root@es-data-i-xxxx ec2-user]# sysctl vm.max_map_count
vm.max_map_count = 262144
```

While 8.6.1 node had ~15k mappings 8.16.1 nodes were exhausting `262,144` limit within an hour resulting in ES process crash

```
[ec2-user@es-data-i-old-version ~]$ sudo wc -l /proc/14074/maps
14770 /proc/14074/maps
[ec2-user@es-data-i-old-version ~]$ sudo wc -l /proc/14074/maps
14760 /proc/14074/maps
```

```
[root@es-data-i-new-version elasticsearch]# wc -l /proc/340641/maps
73202 /proc/340641/maps
[root@es-data-i-new-version elasticsearch]# wc -l /proc/340641/maps
73217 /proc/340641/maps
[root@es-data-i-new-version elasticsearch]# wc -l /proc/340641/maps
74437 /proc/340641/maps
[root@es-data-i-new-version elasticsearch]# wc -l /proc/340641/maps
75724 /proc/340641/maps
```

After I disabled Lucene memory segments completely with the option below the issue went away:
```
-Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false
```

The nodes have 100GB heap and on 246GB total RAM. Data nodes have 159 shards with the following segments stats:
```json
{
"segments": {
          "count": 3938,
          "memory_in_bytes": 0,
          "terms_memory_in_bytes": 0,
          "stored_fields_memory_in_bytes": 0,
          "term_vectors_memory_in_bytes": 0,
          "norms_memory_in_bytes": 0,
          "points_memory_in_bytes": 0,
          "doc_values_memory_in_bytes": 0,
          "index_writer_memory_in_bytes": 1675554396,
          "version_map_memory_in_bytes": 4484320,
          "fixed_bit_set_memory_in_bytes": 227062032,
          "max_unsafe_auto_id_timestamp": 1731413746593,
          "file_sizes": {}
        }
}
```

**Comment by gregolsen** [comment]
cc @uschindler as you worked on memory segments and the issue described [here](https://github.com/elastic/elasticsearch/issues/118623#issuecomment-2587085088) might be of interest to you

**Comment by uschindler** [comment]
Hi @gregolsen,
ES 8.16.x uses Lucene 9.12. This version has an optimization to
Memory Segemnts in general are used by Lucene for much longer time (not sure about older ES 8.6), but to get rid of the issues mentioned earlier found by dacapobench, Lucene 9.12 has the following change:

> [GITHUB#13570](https://github.com/apache/lucene/pull/13570), [GITHUB#13574](https://github.com/apache/lucene/pull/13574), [GITHUB#13535](https://github.com/apache/lucene/pull/13535): Avoid performance degradation with closing shared Arenas. Closing many individual index files can potentially lead to a degradation in execution performance. Index files are mmapped one-to-one with the JDK's foreign shared Arena. The JVM deoptimizes the top few frames of all threads when closing a shared Arena (see JDK-8335480). We mitigate this situation when running with JDK 21 and greater, by 1) using a confined Arena where appropriate, and 2) grouping files from the same segment to a single shared Arena. A system property has been added that allows to control the total maximum number of mmapped files that may be associated with a single shared Arena. For example, to set the max number of permits to 256, pass the following on the command line `-Dorg.apache.lucene.store.MMapDirectory.sharedArenaMaxPermits=256`. Setting a value of 1 associates a single file to a single shared arena.
>(Chris Hegarty, Michael Gibney, Uwe Schindler)

To me the amount of mapping looks like a leak of mappings which are not closed fast enough, because those are bulked together for multiple files.

To make sure that we are on the right track, please add `-Dorg.apache.lucene.store.MMapDirectory.sharedArenaMaxPermits=1` to disable grouping of multiple files into one shared segment. If this helps, we may have a problem with the grouping (e.g., all files of one large segment that only gets deletes over and over produces more and more files in the same shared arena group. The already deleted deletion files of previous generations may not have been released in time, so it sums up mappings).

If this is the case, we need to look into that grouping again and make sure that shared segments (and the associated mappings) are cleaned up faster. Possibly we shoudl exclude deletion of docvalues-update files from the grouping.

In general, with memory segments, the number of mappings should be smaller than with old ByteBuffers because we map in 16 Gigabyte chunks instead of chunks of 1 Gigabyte (due to the `2^31-1` size limitation of ByteBuffer makeing 1 Gigabyte the largest possible *aligned* chunk size to use). As normally the maximum file size in Lucene is by deafault 5 GiB the largest mapping is 5 Gib, so we should have approximately about the number of mappings as segment files in all indexes together.

Uwe

**Comment by uschindler** [comment]
You may also try to lower the `sharedArenaMaxPermits` to lower values. The default is 1024: https://github.com/apache/lucene/blob/d151e4aa69a28e6b6d847f9a8314320084ad48cb/lucene/core/src/java/org/apache/lucene/store/MMapDirectory.java#L504-L519

So it could be that per index segment it has 1024 mappings. With so many indexes you yave in your system, it can easily lead to a huge requirement of mappings.

So in that case lowering it to 16 or 32 may already let go the issue away, but at same time mitigates the slowdowns by highly concurrent closes as described by dacapobench.

You can start with 1 and then check how many mappings you have on your ES istance. Then raise to 16, 32, 64,... and still monitor the number of mappings with long runtimes.

With the results we can for sure make it better in future. There are some ideas to improve that like handling deletion files or docvalues files easier (e.g., those are read-once and can use confined segments). I haven't looked into the details.

With your finding you could also open an issue in Lucene.
