### ISSUE TITLE
Terms aggregation does not work with geo bounding box filter

### ISSUE THREAD

**Issue by spencerapplegate** [elastic/elasticsearch#11866]
I am trying to perform a terms aggregation with the context scoped by a geo_bouding_box filter. The search always returns no buckets in the aggregation when a geo_bouding_box filter is applied to attempt to scope the query to documents in a bounding box.

I have a `properties` index that have `property` documents with children `listing` documents. Listings have a `broker` attribute. I need to find distinct `broker` attributes and the number of their occurrences for 
all properties in a bounding box.

The query I am performing is as follows:
```json
{
    "query" : {
        "filtered": {
            "query": { "match_all": {} },
            "filter": {
                "geo_bounding_box" : {
                    "location" : {
                        "top_left" : {
                            "lat" : 40.73,
                            "lon" : -74.1
                        },
                        "bottom_right" : {
                            "lat" : 40.01,
                            "lon" : -71.12
                        }
                    }
                }
            }
        }
    },
    "aggs" : {
        "brokers" : {
            "terms" : {
                "field" : "listing.broker",
                "order" : { "_term" : "asc" }
            }
        }
    }
}
```

The result I get back is the following:
```json
{
  "took": 6,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 2179,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "brokers": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": []
    }
  }
}
```

The mapping of the index is as follows:
```json
{
  "properties": {
    "aliases": {},
    "mappings": {
      "property": {
        "properties": {
          "address": {
            "type": "string"
          },
          "city": {
            "type": "string"
          },
          "country": {
            "type": "string"
          },
          "location": {
            "type": "geo_point"
          },
          "id": {
            "type": "long"
          },
          "state": {
            "type": "string"
          },
          "street": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "zip_code": {
            "type": "string"
          }
        }
      },
      "listing": {
        "_parent": {
          "type": "property"
        },
        "_routing": {
          "required": true
        },
        "properties": {
          "broker": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      }
    }
  }
}
```

**Notes:**
* Replacing the `geo_bounding_box` with other filter types like a `term` filter works as expected
* I am expecting back buckets with the value of the broker attribute on a listing with the document count within the bounding box

**Comment by clintongormley** [comment]
Hi @spencerapplegate 

It sounds like you have no documents which match your geo filter.  I'd suggest choosing one document which you think SHOULD match and testing it against your query with the explain API: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-explain.html

Btw, a better place to ask questions like these is in the forum: http://discuss.elastic.co/.  This issues list is meant for bug reports and feature requests

thanks

**Comment by spencerapplegate** [comment]
@clintongormley I have 2179 documents that match my geo filter. When I remove the `search_type=count` parameter, they all appear in the hits section of the response. This is absolutely unexpected behavior

**Comment by clintongormley** [comment]
@spencerapplegate I missed that.  But your geo-point is in the `property` type and `broker` is in the `listing` type, so your matching docs (all of type `property`) don't have any values called `broker.listing`.  

You have a parent-child relationship between property and broker, so presumably the thing you're missing is a `children` aggregation.

**Comment by spencerapplegate** [comment]
@clintongormley when I change the filtered query to something more basic, like a terms filter, its works completely as expected. For instance, If I change the query to this:
```json
{
    "query" : {
        "filtered": {
            "query": { "match_all": {} },
            "filter": {
                "term": {
                    "broker": "CBRE"
                }
            }
        }
    },
    "aggs" : {
        "brokers" : {
            "terms" : {
                "field" : "listing.broker",
                "order" : { "_term" : "asc" }
            }
        }
    }
}
```

It returns the correct bucket with its counts:
```json
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1533,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "brokers": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "CBRE",
          "doc_count": 1533
        }
      ]
    }
  }
}
```
We have 1533 properties with listings with a broker of `CBRE`.

Its only when we try to use the geo_bounding_box filter that it will return `[]` for buckets. We have tried flipping top_right to top_left and vis-versa for the bottom bounds. We have also changed the bounding box to be all inclusive, but nothing will return in the buckets.

**Comment by clintongormley** [comment]
@spencerapplegate that's because your term query is matching the `broker` field in the `listing` type, and that's the same document type that you're aggregating on.  If you change your term query to check a field that only exists in the `property` type then you'll see that you get no aggregations from the `listing.broker` field, same as for geo.

Please take this to the forum - this is a problem with usage, not Elasticsearch.

**Comment by spencerapplegate** [comment]
@clintongormley thank you for the direction!
