### ISSUE TITLE
Dynamic mapping with automatic index creation

### ISSUE THREAD

**Issue by j0hnsmith** [elastic/elasticsearch#11877]
The docs suggest that it's possible to create a mapping for a type that doesn't yet exist.

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-creation
> The index operation automatically creates an index if it has not been created before (check out the create index API for manually creating an index), and also automatically creates a dynamic type mapping for the specific type if one has not yet been created (check out the put mapping API for manually creating a type mapping).

When I try this I get `IndexMissingException`.

    $ curl -XPUT 'http://elasticsearch:9200/log-*/_mapping/log_entry' -d '
    {
        "log_entry" : {
            "properties" : {
                "category" : {"type" : "string", "index": "not_analyzed"},
                "message" : {"type" : "string", "store" : true }
            }
        }
    }'

Every example of the Put Mapping api I can find in the docs includes a concrete index, how do you specify a dynamic type mapping without referencing a concrete index?

**Comment by dadoonet** [comment]
Please use discuss.elastic.co for questions.

If you want to add a mapping to an index, you need to create an index.
If you want to create a mapping as a template for the time an index is being created, then use an index template.
If you want to create an index and its mapping at the same time, have a look at the create index API.

Not an issue. Closing.

**Comment by j0hnsmith** [comment]
I've just found index templates in the docs after at least an hour reading through them specifically trying to find out how to do it. 

The bug is that the docs say you can do it but don't say how (or link anywhere that does). I read at least 10 pages of docs relating to mapping, not one of them mentioned index templates.

**Comment by dadoonet** [comment]
This? https://www.elastic.co/guide/en/elasticsearch/guide/current/index-templates.html
