### ISSUE TITLE
Improve mapping documentation

### ISSUE THREAD

**Issue by j0hnsmith** [elastic/elasticsearch#11878]
I've been trying to configure mapping, the docs are leading me round and round in circles. A quick search finds 9 different pages in the docs related to mapping (I'm sure there are more), information is spread out all over the place.

https://www.elastic.co/guide/en/elasticsearch/guide/current/custom-dynamic-mapping.html                                                                 
https://www.elastic.co/guide/en/elasticsearch/guide/current/default-mapping.html
https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-intro.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-dynamic-mapping.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-object-type.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-root-object-type.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html

**Comment by j0hnsmith** [comment]
Mapping for indices that don't yet exist can be configured via index templates, this is what I was looking for, I don't believe they're mentioned on any of those 9 pages.

**Comment by clintongormley** [comment]
I've completely rewritten the mapping docs in master - should be much easier to understand now.

https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping.html
