### ISSUE TITLE
How to modify the content of the field in source?

### ISSUE THREAD

**Issue by yoopaan** [elastic/elasticsearch#118822]
I want to process the query return value of the document in the source code and implement the following operations:

index:

```
{ "id": 1001,
"title":"abcd"
}
```

return:

```
{
"id": 1001,
"title": "bcde"
}

```
That is, replace the field, and the length of the string before and after the replacement is the same.

How to achieve this goal？

**Comment by iverase** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
