### ISSUE TITLE
Corrupted replica shards

### ISSUE THREAD

**Issue by bittusarkar** [elastic/elasticsearch#11883]
We're using Elasticsearch 1.3.4. Every now and then we run into corrupted replica shard issues on our production cluster. Below is one of the error messages we see in the log file.

    [MasterNode] [index10][1] received shard failed for [index10][1], node[BujRysY1Sh-g1ZCFjA5Nag], [R], s[INITIALIZING], indexUUID [SEEuraAWTwObNVug0lz4sA], reason [Failed to start shard, message [CorruptIndexException[[index10][1] Corrupted index [corrupted_2rbhI3j1SY-WsNsOgdsjug] caused by: CorruptIndexException[codec footer mismatch: actual footer=1291846144 vs expected footer=-1071082520 (resource: MMapIndexInput(path="<path to one of the .doc file>"))]]]]

The replica shard remains in the corrupted state indefinitely even when the corresponding primary shard is in `STARTED` state. Today we workaround this issue by setting the number of replica shards of the affected index to `0` and then back to the original number. Though this fixes the corruption, it has other non-trivial side-effects:

 - Replicas of even the unaffected shards get re-created but take a lot of time to get to the `STARTED` state.
 - As all replica shards are re-created, filter and fielddata caches for those shards is reset, causing slower queries.

I want to understand if there is a better way to fix such issues or is this fixed in higher versions of Elasticsearch.

Ideally, if a replica shard is corrupted and the primary shard is not, it should recover from the primary shard because the corruption will never self-heal, no?

If that is not possible, is it possible to delete the corrupted replica shard from file system and use the `_cluser/reroute` API to allocate it back? Even better, allocation with `_cluster/reroute` should first check if the shard is corrupted and if yes, delete it and finally allocate.

**Comment by clintongormley** [comment]
Hi @bittusarkar 

This and many other corruption issues have been fixed in later versions. I highly recommend that you upgrade.
