### ISSUE TITLE
Problem with cardinality count..

### ISSUE THREAD

**Issue by HemaAnusha** [elastic/elasticsearch#11888]
Hi,
Am using cardinality to get the count of unique values of a field...
Here is my Query..
GET hahn_pcdb/hahn_pcdb_type/_search
{
   "size": 0,
   "aggs": {
      "category_name": {
         "terms": {
            "field": "CATEGORY_NAME",
            "size": 0
         },
         "aggs": {
            "part_number": {
               "cardinality": {
                  "field": "PART_NUMBER"
               }
            }
         }
      }
   }
}

But when am checking the count of them in MySql getting variation in both distinct count..
Can anyone trace this...

And here are my mappings..

"hahn_pcdb_type": {
            "properties": {
               "BRAND_NAME": {
                  "type": "string",
                  "index": "not_analyzed",
                  "fields": {
                     "raw": {
                        "type": "string"
                     }
                  }
               },
               "CATEGORY_ID": {
                  "type": "string"
               },
               "CATEGORY_NAME": {
                  "type": "string",
                  "index": "not_analyzed",
                  "fields": {
                     "raw": {
                        "type": "string"
                     }
                  }
               },
               "GROUP_ID": {
                  "type": "string"
               },
               "GROUP_NAME": {
                  "type": "string",
                  "index": "not_analyzed",
                  "fields": {
                     "raw": {
                        "type": "string"
                     }
                  }
               },
               "LINE_CODE": {
                  "type": "string"
               },
               "PART_NUMBER": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "PART_TYPE_DESC": {
                  "type": "string",
                  "index": "not_analyzed",
                  "fields": {
                     "raw": {
                        "type": "string"
                     }
                  }
               },
               "PART_TYPE_ID": {
                  "type": "string"
               }
            }
         }
      }
   }

**Comment by marg51** [comment]
Hi @HemaAnusha 
Cardinality is approximate, the behaviour you're seeing is expected. 
See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html#_counts_are_approximate for more informations

**Comment by HemaAnusha** [comment]
Hi Marg,
Thanks for your response, I used the precision threshold: 40000 which is giving the accurate count, even that is also not the exact count but near to that, the accuracy increased.
So how can i achieve exact count of unique values, is there any way ?

**Comment by clintongormley** [comment]
Hi @HemaAnusha 

This issues list is for bug reports and features request. A better place to ask such questions is in the forum: https://discuss.elastic.co/

thanks
