### ISSUE TITLE
[CI] JdbcDocCsvSpecIT » test {docs.testFilterToday}

### ISSUE THREAD

**Issue by gmarouli** [elastic/elasticsearch#118846]
### CI Link

https://gradle-enterprise.elastic.co/s/7kt2ywywpijpw/tests/:x-pack:plugin:sql:qa:server:single-node:javaRestTest/org.elasticsearch.xpack.sql.qa.single_node.JdbcDocCsvSpecIT/test%20%7Bdocs.testFilterToday%7D

### Repro line

./gradlew ":x-pack:plugin:sql:qa:server:single-node:javaRestTest" --tests "org.elasticsearch.xpack.sql.qa.single_node.JdbcDocCsvSpecIT" -Dtests.method="test {docs.testFilterToday}" -Dtests.seed=145F6F28428E9F83 -Dtests.locale=os-Cyrl-GE -Dtests.timezone=America/Dawson -Druntime.java=23

### Does it reproduce?

Yes

### Applicable branches

main

### Failure excerpt

It failed in my branch but I was able to reproduce it locally on main too.

**Comment by astefan** [comment]
Fixed with https://github.com/elastic/elasticsearch/pull/118815
