### ISSUE TITLE
Issues with the json description of Snapshot Create API

### ISSUE THREAD

**Issue by szroland** [elastic/elasticsearch#11897]
In general, Rest test code picks the HTTP method and path randomly from the API json spec. Not sure what other uses of this specification exist, but this indicates an assumption that if there are multiple methods available, they are all available on all urls (that match the parameters) with the same semantics.

However, this breaks for snapshot create, where the POST and PUT URLs in the API are different, there is an extra `_create` for POST only:
```
        controller.registerHandler(PUT, "/_snapshot/{repository}/{snapshot}", this);
        controller.registerHandler(POST, "/_snapshot/{repository}/{snapshot}/_create", this);
```

The API spec in json:
```
    "methods": ["PUT", "POST"],
    "paths": [
      "/_snapshot/{repository}/{snapshot}", 
      "/_snapshot/{repository}/{snapshot}/_create"],
```

So if you tried to use this API in rest tests (which might explain why no such tests currently exist), sometimes RestClient actually picks the wrong combination and does a PUT to `/_snapshot/{repository}/{snapshot}/_create` which happens to get parsed as a create index request (and fails because of the invalid index name `_snapshot`, which could indicate some issue in the dispatch code as well).

So there are a couple of things that could be done:
 * Change the Snapshot Create API to have PUT and POST both on all the same paths, in line with other APIs (e.g. add PUT and POST to both, assuming request dispatching could support that, or drop "_create" from the POST path)
 * Change the json API spec format to allow the linking of method to path
 * Create 2 separate json files for snapshot create, one describing the PUT api and the other the POST api (you would lose the random selection between the methods in tests, and would pick e.g. between snapshot.create or snapshot.create.post in your test descriptor)

I guess the best course of action depends on what uses of the json specification there are, what it is really intended for.

Dropping POST/_create, at least from the spec file, seems to be an interesting option, since I see this has been done on other APIs as well (e.g. search_template and put_script), which have a POST/_create mapping in code but not in the json spec. I guess the issue might be that the path also matches the create index action path `/{index}/{type}/{id}/_create`, not sure if the dispatch logic deterministically considers the create index option last (e.g. prioritizes more specific paths over less specific ones).

**Comment by bleskes** [comment]
> Change the Snapshot Create API to have PUT and POST both on all the same paths, in line with other APIs (e.g. add PUT and POST to both, assuming request dispatching could support that, or drop "_create" from the POST path)

Let's do this. As you say it's consistent with other api (for example, search templates)

**Comment by clintongormley** [comment]
`.../_create` isn't even documented.  I'd go for just dropping that URL from the spec.

**Comment by bleskes** [comment]
@clintongormley works for me, but let's remove it from the code as well (2.0 only). We should still support POST (at least in the code level) for  `/_snapshot/{repository}/{snapshot}` .

**Comment by clintongormley** [comment]
To be clear: support PUT and POST, but drop the _create endpoint.

**Comment by szroland** [comment]
Added a pull request, please see #11928
