### ISSUE TITLE
Error : curl(56)  Recv failure: Connection reset by peer 

### ISSUE THREAD

**Issue by rpalsaxena** [elastic/elasticsearch#11899]
I am trying to load my ES db using bulk API, but I am getting this error
"curl: (56) Recv failure: Connection reset by peer"

The structure of json documents in my json file is correct 
But my file size is 750MB 

Please suggest me some solution 

Thanks

**Comment by dadoonet** [comment]
Please use discuss.elastic.co

Try to reduce your bulk size. I think I don't insert more than 10k docs per bulk (small docs). So, some mb at most per bulk.

**Comment by rpalsaxena** [comment]
But elasticsearch is made for handling big size data some GBs of data , even wiki and github are also using it .

I think reducing the input size is not a good solution , but I somehow managed to insert the data using python ..

Even then if someone can suggest me best possible solution then kindly comment

**Comment by dadoonet** [comment]
Yes. I can confirm that elasticsearch can handle billions of documents, trillions of documents.
It does not mean that you can pass all those docs within one single bulk request.

Have a look BTW at `http.max_content_length`. By default it's limited to 100mb (on purpose).

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html
