### ISSUE TITLE
Request Timeout Error after multiple search hits

### ISSUE THREAD

**Issue by imranm** [elastic/elasticsearch#11892]
Hi,

I have nodejs script in which I am using same es client instance to search for more than 50 times in a loop. After first 20 search the es client throws exception [Error: Request Timeout after 30000ms]

Any help would be highly appreciated.

Thanks in advance!

**Comment by imranm** [comment]
```javascript
var es = new elasticsearch.Client({ host: ES_HOST, requestTimeout: 30000, maxSockets: 20 });
```

**Comment by clintongormley** [comment]
This issue was moved to elastic/elasticsearch-js#230
