### ISSUE TITLE
ES eventually falls in timeouts

### ISSUE THREAD

**Issue by AndreyAfanasyev** [elastic/elasticsearch#11907]
I have server with 32Gb RAM under Windows Server 2012 R2 Standard.
I have installed on server:
1) ES 1.6.0 - takes 8Gb of RAM, configured as single node.
ES configuration:
```
cluster.name: xxxxx
bootstrap.mlockall: true
network.host: xxxxx
transport.tcp.port: xxxxx
http.port: xxxxx
index.search.slowlog.threshold.query.warn: 10s
index.search.slowlog.threshold.fetch.warn: 1s
index.indexing.slowlog.threshold.index.warn: 10s
monitor.jvm.gc.young.warn: 1000ms
monitor.jvm.gc.old.warn: 10s
script.inline: on
script.indexed: on
```
2) MS SQL Server 2008R2 - takes 16Gb of RAM.
When I just started ES - all is fine, works without any timeouts.
But after 3-4 days I'm starting get timeouts during different ES operations (search, msearch, bulk insert).
During getting timeouts BigDesk shows that do not exist any problems with HeapMemory (~5-6 Gb out of 8Gb is used), CPU (cpu usage ~30-40%), Search requests per second ( 50-80 requests per second).
I turned on slow logging and noticed that number of records in elasticsearch_index_search_slowlog.* files usually grows day by day and some queries are executed in 1-2 minutes.
The volume of indexed documents is the same in 3-4 days approximately, so I do not think that it could be a reason.
If I restart ES - it helps, but situation is repeated in 3-4 days.
Any hints what could it be?
On what should I pay attention in order to recognize possible problems?

**Comment by clintongormley** [comment]
Hi @AndreyAfanasyev 

The best place to ask questions like this is in the forum: https://discuss.elastic.co/. This list is for bug reports and feature requests.  That said, looking at your config, your slow GC warning level is way too high.  I'd expect slow GCs to be around 500ms, which leads me to think that you are suffering from slow GCs because you are not using mlockall.  

See https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html#setup-configuration-memory

**Comment by AndreyAfanasyev** [comment]
@clintongormley,
I already use mlockall setting:
```
bootstrap.mlockall: true
```
in my config.

Please see /_nodes/process?pretty response:
```
{
  "cluster_name" : "elasticsearch",
  "nodes" : {
    "suIdQ4kFRUWJ-gCaZRKTKA" : {
      "name" : "Xxxxx",
      "transport_address" : "inet[/xxxxxxxxxxxxxxxx]",
      "host" : "xxxxx",
      "ip" : "xxxxxxxxxxxxxxx",
      "version" : "1.6.0",
      "build" : "cdd3ac4",
      "http_address" : "inet[/xxxxxxxxxxxxxxx]",
      "process" : {
        "refresh_interval_in_millis" : 1000,
        "id" : 6548,
        "max_file_descriptors" : -1,
        "mlockall" : true
      }
    }
  }
}
```
What should I do else to setup mlockall properly under Windows Server?

**Comment by clintongormley** [comment]
OK.  The best place to ask these questions is still the forum
