### ISSUE TITLE
Support aliases for type 

### ISSUE THREAD

**Issue by msathis** [elastic/elasticsearch#11905]
If i'm not wrong, aliases are supported only at the index level now. It would be helpful in certain use cases like ours if alias can be made for type too.

For e.x our environment has 1000 of apps and each app has 100's of documents. Right now we are storing them as different types under same index. 

But while reindexing each app, We have to cleanup the documents first (because field mapping may change). Due to this we see zero results for a brief period of time.  Alias support for type would be useful here.

**Comment by markwalkom** [comment]
You can use an alias with a filter for this.

**Comment by msathis** [comment]
@markwalkom Filtering means you won't be able to change the mapping. To solve that, We may index into different type, but there is no way to rename it back to original name after indexing done. :(

**Comment by clintongormley** [comment]
@msathis we have removed the ability to delete type mappings in master because it can lead to corrupt data. (https://github.com/elastic/elasticsearch/pull/10231)  If you need to make changes like this, you need to reindex to a new index.

**Comment by msathis** [comment]
@clintongormley So your suggestion is to make 10,000 indexes, if i have 10,000 apps? Unfortunately you didn't point me to a convincing alternative solution before closing the issue.

**Comment by msathis** [comment]
Hi @clintongormley , You haven't cited a reason for closing this. I still feel, it's good to have feature as there are no efficient alternatives present. Let me explain my use case for this in few sentences,

1. We have ten thousands of apps. Each app has 100's of documents and indexed as a type.
2. Each app has differently structured documents and so different field mappings as well. These mapping may change at any time. When mapping changes, we have to reindex the app.

Right now we are deleting the type first and then reindexing to the same type. Due to this we see "zero results" or "fewer results" for one or two seconds (during indexing period). We want to avoid this.

If alias for type existed, i could've indexed into different type and then made alias for actual type name.

 Is there a better way to achieve this with current elasticsearch itself? 

Thanks.

**Comment by clintongormley** [comment]
Hi @msathis 

I've closed this ticket because: (1) we no longer support delete-mapping and (2) we're trying to simplify mappings, rather than make them more complicated (and thus more prone to bugs).

You can read more about the changes coming in mappings here: https://www.elastic.co/blog/great-mapping-refactoring along with some suggestions for modelling your data.

**Comment by msathis** [comment]
Thanks @clintongormley . This makes sense from elasticsearch point of view. Do you see any performance implications in having 10,000 indices compared to 10,000 types in one index?

**Comment by clintongormley** [comment]
@msathis yes :)  unless you have a LOT of nodes...  I'd suggest name-spacing your fields instead, eg `app1.foo` or something like that, but really depends on your needs.  Best place to discuss design issues like this is the forum: http://discuss.elastic.co/

**Comment by msathis** [comment]
Ok. Thanks @clintongormley. I will post a question there. :)
