### ISSUE TITLE
Rethink string versus not_analyzed string mappings and support

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#11901]
### Problem

In Elasticsearch, you can currently support indexing your string data as either `analyzed` strings, which is great for unstructured, full text search, or as `not_analyzed` strings, which is great for structured search (e.g., _exact_ matches). However, there is frequently an in-between where you want exact matches, but you want them to ignore case or accented characters (`AA == aa == Ââ`). This forces the use of analyzers for normalization.

### Partial Workaround

For those scenarios, you are currently forced to use the analyzed string variant with a specific analyzer. This generally leads to users forgetting to disable a lot of things like norms, positions, and frequencies. Even if you do happen to do all of that right, you simply cannot take advantage of doc values.

### Potential Solution

It would be interesting to potentially rethink strings and how they're mapped. In the case of analyzed strings, there really isn't much need for improvement except potentially the naming of it. For not\_analyzed strings, there's a lot of room for improvement.

#### Mockup

```json
PUT /my-index
{
  "mappings" : {
    "my-type" : {
      "properties" : {
        "full_text" : {
          "type" : "string",
          "analyzer" : "standard"
        },
        "constant_string" : {
          "type" : "constant_string",
          "filter" : [ "lowercase", "trim" ],
          "char_filter" : [ "..." ]
        }
      }
    }
  }
}
```

Note: the difference is that analyzed strings stay "string" and not_analyzed strings become "constant_string". It's unlikely that we could easily change from "string" for analyzed text, but if we could, then perhaps we could switch analyzed strings to be `text` and not\_analyzed strings to be just `string`.

This avoids a lot of questions and regular problems. It also provides the exact same functionality as we have today, if you choose to not supply a filter or char\_filter for constant\_strings, but it also provides more flexibility in that users can finally use doc values with filtered text that still can be reasonably sorted and aggregated in a normalized format, without the ability to confusingly tokenize the string and unnecessarily use norms, position, or frequency data.

**Comment by rmuir** [comment]
I think we should try prototyping a new mapper for `small_string` or whatever? We can figure out the naming afterwards and rename.

I think also it could have a bare minimum of options to start: it doesn't need to support `indexOptions` for frequencies, positions, offsets (and corresponding vector options), doesn't need an option to turn on norms, it doesn't need to support confusing options like `boost` that won't work, etc.

**Comment by nik9000** [comment]
Call it keyword? Token filter is still needed but i feel like the word
token isn't needed any more but don't know a better name.

Should elasticsearch default strings to this when automatically creating
the mapping in any case?  Like maybe if they are short?  Seems funky.

**Comment by rmuir** [comment]
i don't like keyword because thats not what is happening. the idea is this field can change, but in a restricted way: one token.

i dont think the defaults should change. no magic! this just makes not-analyzed strings a proper type of its own: gives you an option to normalize short strings (e.g. case-insensitive sorting and aggregations and other basic stuff). 

the real challenge here will be the bikeshedding of the naming...

keep in mind when painting your shed, that the current naming is horrible. Because having two radically different `string` configurations and defaults based on `not_analyzed` is totally counterintuitive.

**Comment by nik9000** [comment]
Yeah. It's only semi-intuitive if you're familiar with lucene. But bike
shedding is fun and I can do it on mobile to kill time.

Call it token? Like, instead of calling it string. As in "here is a token,
no need to tokenize that again. I already did."

I think both char and token filters could still be useful here but would
bring more confusion.

**Comment by rmuir** [comment]
yeah, personally i'd prefer `string` and `text` :)

I don't mind `token` or `small_string` or similar though. I think it helps the user understand its one token and not be surprised when they configure all the text of moby dick this way and indexwriter gets angry about it.

yeah, i don't have an opinion on charfilters. usually i just see it as a way to tweak the tokenizer. I do think the tokenizer should be limited to or implicitly `keyword` and that the filters should only generate one token. 

We annotate those "safe" analysis factories with an interface in lucene, so we could do some static checking, and of course we should check incrementToken() doesn't return true again at runtime.

**Comment by pickypg** [comment]
I like both `small_string` and `token`. From a new user's perspective, I feel like `small_string` may be easier to figure out, but I think `token` is much clearer in terms of its literal effect.

**Comment by clintongormley** [comment]
What about the path hierarchy tokeniser? I would think that a path field would still be a good candidate for doc values even though it produces multiple tokens?

On naming, I prefer `string` and `text` too, but we should probably abandon `string ` for bwc sanity. Another suggestion is `enum`.

Regarding OOB defaults, I agree that we should stick with analysing strings by default. Unfortunately this means that doc values are disabled by default. @jpountz made an intriguing suggestion:

For dynamically mapped string fields, should we add an analysed `text` field with field data losing disabled

**Comment by clintongormley** [comment]
Bah... Finger slipped on the mobile... To continue:

For dynamically mapped string fields, should we add an analysed text field with field data loading disabled, and a `_raw` multi field of type `enum` which is not analysed and has doc values enabled.

It'd mean indexing more data by default but would be a good OOB experience, and users can always specify more optimal mappings themselves. We'd need to make the `_raw` name reserved, but I doubt that'll cause many issues.

**Comment by rmuir** [comment]
personally i think the scope of this issue should be contained: to the simple case of one token initially.

Stuff like path tokenization starts to walk into the world of traps and more rare esoteric use cases. I don't see for example why someone would need to aggregate on this (sorry). And changing what dynamic mappings does could also be another followup issue? Again there are tradeoffs (like disk space).

This issue can be contained, at minimum to a new mapper type that lets you normalize (e.g. lowercase/asciifold) a string... and it has clear use cases like case-insensitive sort. It doesn't really have tradeoffs, its just an option you didnt have before. Personally I think this is enough to chew on at once.

**Comment by clintongormley** [comment]
Agreed ++

**Comment by clintongormley** [comment]
Discussed this in FixItFriday: Let's go with `keyword` (this string can only use a keyword analyzer) and deal with any confusion in the first line of the docs.

**Comment by colings86** [comment]
Can only use a keyword tokenizer you mean? They will need to use other token filters to support lowercasing etc.

**Comment by rjernst** [comment]
+1 to `keyword`! We can just not support the `tokenizer` setting, so it is always `keyword_tokenizer`. As for filters, how should we limit these to filters that do not produce new tokens? Should we start with a static list of supported filters?

**Comment by rmuir** [comment]
lucene already marks these filters with an interface. it needs to be used here.

**Comment by rjernst** [comment]
Ah right, perfect. I can take a shot at this new mapper then.

**Comment by nik9000** [comment]
Yup. It's pretty simple to check the token count on the way out of indexing
a document for that extra bit of sanity.

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/12394
