### ISSUE TITLE
The "size" and "from" of root of search JSON do not work with aggregation

### ISSUE THREAD

**Issue by rusboy** [elastic/elasticsearch#11916]
Hey,

I'm observing some strange behavior with aggregation. I'm using ES 1.6.
```
{
  "status" : 200,
  "name" : "Honey Lemon",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.6.0",
    "build_hash" : "cdd3ac4dde4f69524ec0a14de3828cb95bbb86d0",
    "build_timestamp" : "2015-06-09T13:36:34Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

I've built search JSON where I used "from", "size" and aggregation. So, it looks like following code:
```
{
  "from": 0,
  "size": 5,
  "sort" : [
       { "profile" : {"order" : "asc"}}
  ],
  "aggs": {
    "genders": {
      "terms": {
        "field": "custom_field",
        "order" : { "_term" : "asc" }
      },
      "aggs": {
                "my_top_hits": {
                    "top_hits": {
                       "from" : 0,
                        "sort": [
                            {
                                "count": {
                                    "order": "asc"
                                }
                            }
                        ],
                      "size" : 4  // I know, I can increase the value. But it's not solves issue anyway
                    }
                }
            }
    }
  }
}
```

My expectations are, only 5 first documents of index are used for aggregation... However, I was surprised.. Aggregation results include all documents from index.

I tried to add query tag in search JSON.. And I see, aggregation works only with part of documents that are "provided"/"filtered" by query..
I think, "from" and "size" of root search JSON should cut list of documents for aggregations, similar with 

Task that I'm trying to solve is grouping documents by some field. Something like GROUP BY of MySQL. Some example from extjs could be find here http://docs.sencha.com/extjs/4.2.3/extjs-build/examples/build/KitchenSink/ext-theme-neptune/#grouped-grid

My idea was, to use "from"/"size", for paging via aggregated data. In other words, I would be "ask" aggregation process only required for myself part of data. 
For example, now I could be use "size" of terms aggregation.. but it means, I'll have N buckets with length <= the "size". But it's worse way..Because to show table I 'll use only number required for site documents. But, also.. site will received a lot of data that are not required. It can impact customer's PC (I mean memory) and enforce to wait data foo long time if I use big data

Some questions are opened for myself:
1. Is it feature or bug? ( If it's bug I can take a look.. would be great if you recommend where in code I should start)
2. Possible, u know other way to group data by field.
3. Could be results of several metric aggregation are joined to one array ?

**Comment by rusboy** [comment]
hm.. seems I found workaround solution for myself..
it looks so, 
```
{
  "sort" : [
      { "custom-field1" : {"order" : "asc"}},
      { "count"   : {"order" : "asc"}}
  ],
  "aggs": {
      "group-by-custom-field1": {
          "terms": {
             "field": "custom-field1",
             "size" : 0
           },
           "aggs": {
              "group-by-count" : {
                  "terms": {
                      "field": "count",
                       "size" : 0
                   }
               }
           }
      }
  }
}
```
Sort rows by grouped fields and calculate by aggregation count of values in each group. The example for case when user groups results by 2 fields (custom-field1 and count)

Anyway, I would be interested to know answers on my question above.
Thanks!

**Comment by clintongormley** [comment]
Hi @rusboy 

It is a feature, not a bug.  The typical use case is: calculate analytics over all matching documents, and give me the top N documents as hits.

To achieve what you want (ie to only aggregate on the page of results returned in hits) you would need to do this in two steps:

* run a query with `from`/`size`
* run a second request with aggs, where the query matches just the doc ids from the first query
