### ISSUE TITLE
[Docs] Explain Error Handling in TransportClient

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#11920]
The handling of the internal transport connection needs to be clarified in the documentation while using the `TransportClient`. Specifically, it would be good to document what happens to connections:
- During the initial connection.
  - Connections are tried in parallel.
- When sniffing the connection.
  - The cluster state is fetched to find connections.
  - Does this happen more than once (e.g., to catch new nodes or nodes that were down)?
- When a connection fails.
  - There is an active/inactive list controlled by `client.transport.nodes_sampler_interval` (`5s` by default).
  - What does this mean for sniffed nodes?
- When a request fails.
  - If the connection fails, then it will automatically try the next node.

**Comment by clintongormley** [comment]
Agreed - want to send a PR?

**Comment by debadair** [comment]
Closing this as the Transport Client is on it's way out.
