### ISSUE TITLE
Elasticsearch 2.0 joins 1.6 cluster

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#11924]
Start a node with 1.6.0, then a node from master.

Check the cluster health on master - it reports two nodes.

**Comment by nik9000** [comment]
That's unlikely to work well....

**Comment by martijnvg** [comment]
I tried to reproduce this, but I couldn't get the 1.6 node to join the node from master. Maybe it just happened based on a particular commit? Regardless of this, it still feels good to have have validation during pinging that ignores ping responses (and log a warning) of nodes with a version lower than the minimum supported version. (in the case that ping requests/responses happen to serialize successfully between versions that shouldn't be compatible )

**Comment by martijnvg** [comment]
I managed to reproduce this with unicast discovery.
