### ISSUE TITLE
Query refactoring: improve query validation errors messages by providing more context

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#11939]
If you have a compound query composed of different levels of nested queries, which is very common, and one single query fails validation, we currently print out a generic validation error but it is hard to identify which query is the "broken" one from the error message. We should improve this, probably by keeping track of where a query is positioned in the query tree and outputting a more specific error message.

**Comment by cbuescher** [comment]
Since we're moving away from validate() method this can be closed.
