### ISSUE TITLE
smoketester should install ALL plugins/

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#11935]
`dev-tools/build_release.py` should install all the plugins from plugins/ into elasticsearch before it starts up. 

This will allow detection of packaging bugs (maven assembly logic) such as https://github.com/elastic/elasticsearch/issues/11647. If the plugin's zip has conflicting jars, they are detected as jar hell on startup.

It would be great if it also asserted that all the plugins expected to be loaded in fact were.

I'm not a python guru, but this should really prevent a lot of release bugs.
Then we can fix #11647 and have confidence in the packaging.

**Comment by mikemccand** [comment]
+1

**Comment by mikemccand** [comment]
@s1monw I have a rough start at this, as a standalone smoke_test_plugins.py tool ...

**Comment by s1monw** [comment]
@mikemccand feel free to take this!
