### ISSUE TITLE
Add jitter in AWS API retries

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#11934]
Currently if a large number of nodes need to hit the AWS endpoint for whatever reason (eg discovery), they can be impacted by [API throttling].(http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#api-request-rate).

We will [retry on a failure](https://github.com/elastic/elasticsearch-cloud-aws/blob/master/src/main/java/org/elasticsearch/cloud/aws/blobstore/S3BlobContainer.java#L86), but if there are a large number of nodes trying to hit the API again, they can be throttled for a second time.
Rinse. Repeat.
This could mean that for larger number of nodes, they end up in a loop as they can never get a response from the API and never actually form the cluster.

It'd be great if we could add a jitter aspect to the retry so the nodes don't all end up retrying at the same time.

**Comment by xuzha** [comment]
I don't think we need to add this jitter logic. The exponential backoff policy with max 3 times retry is already in default retry logic, which is the default configuration for S3 client and EC2 client.

**Comment by clintongormley** [comment]
Adding a bit of randomization is pretty easy, and certainly won't hurt. I think we should do it

**Comment by xuzha** [comment]
Do you mean we add extra randomization and plus exponential back-off latency? 

Please correct me if I'm wrong, I'm pretty to new to this. From my understanding, for right now we are using default exponential backoff policy, which is not configurable for our aws plugin users. But for S3 client, we make max number of retries configurable, and we also pass this number into our [S3 client] (https://github.com/elastic/elasticsearch/blob/4c981ff4bfc250080d521af105b5e8589c9fc517/plugins/cloud-aws/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java#L126) when we creating it ( I don't think we should do it )

So for example, if user put 3 for max number of tries into the setting, aws java client will do 3 times retries for us (hopefully) . AND PLUS, during doing snapshot, we would do another 3 times retries at our side if we got retryable exception, which is 9 times retryies (3 exponential retries ) * 3. 

I think we probably need make max number of retries configurable for our EC2 client.

**Comment by markwalkom** [comment]
We should add randomisation, yes.

**Comment by clintongormley** [comment]
> Do you mean we add extra randomization and plus exponential back-off latency?

The problem with the backoff is that all requests can be backed off and then retried at exactly the same time.  with a little randomization, it'll spread the retries out a bit.

**Comment by jpountz** [comment]
Actually, there is already some randomization happening with the default client configuration, see https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/retry/PredefinedRetryPolicies.java#L232

**Comment by petemounce** [comment]
https://www.awsarchitectureblog.com/2015/03/backoff.html is an interesting analysis on different retry strategies.

**Comment by yashdatre** [comment]
I could not find the jitter logic in .net SDK. I believe we should add it there too!
