### ISSUE TITLE
Excessive CPU Usage During HNSW Merging Causes Data Node Eviction

### ISSUE THREAD

**Issue by Hoyaspark** [elastic/elasticsearch#119333]
### Elasticsearch Version

8.13.4

### Java Version

_bundled_

### OS Version

aarch64 aarch64 aarch64 GNU/Linux

### Problem Description

In a Kubernetes environment with four data nodes, each configured with **14 cores and 26 GiB of memory**, consider the following scenario:

While indexing into Index A, the index.merge.scheduler.max_thread_count is set to its default value, and the embeddingVectorField is configured with m: 32 and ef_construction: 2000. The index has number_of_primary: 1 and number_of_replicas: 0. Once indexing is completed, the number of replicas is increased to 3.

During this process, as Lucene’s ConcurrentMergeScheduler begins merging segments, the kNN vector merges trigger significant CPU load. This is because the merging process involves reprocessing indexed documents and performing computationally intensive tasks such as graph construction. As a result, all available threads become overloaded. This excessive resource consumption prevents the data nodes from processing cluster state updates sent by the master node, ultimately leading to the eviction of the affected data nodes from the cluster.

This issue poses a significant challenge to maintaining a stable cluster, as the IO load generated by segment merging during this process can disrupt the cluster’s ability to serve search traffic reliably.

### Steps to Reproduce

1.	**Create an index with the following settings and mappings**
```
PUT test_doc
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0
  },
  "mappings": {
    "properties": {
      "embeddingVector": {
          "type": "dense_vector",
          "dims": 64,
          "element_type": "float",
          "index": true,
          "similarity": "max_inner_product",
          "index_options": {
            "type": "hnsw",
            "m": 32,
            "ef_construction": 1000
          }
       }
    }
  }
}
```

2. **Index Documents**
- Index 500,000 documents with embeddingVectorField values.

3. **Trigger replica creation**
- After completing the indexing, update the index settings to set number_of_replicas to 3
```
PUT test_doc/_settings
{
  "index": {
    "number_of_replicas": "3"
  }
}
```

4. **Observe the behavior**
- Monitor the cluster during the replica creation process.
- Note if data nodes experience high CPU usage, fail to process cluster state updates, and are evicted from the cluster
  - can see elasticsearch log with `logger.org.elasticsearch.cluster : "DEBUG"`
- Monitor Hot Threads named by Lucene Merge Thread

### Logs (if relevant)

**Attach related logs & metrics**

```
- Indexing Start Time : 15:55
- Indexing End Time : 16:04 
- Replica Creation Time: 16:04
```

- Data Node Cpu Usages (Red dot means 100%)
<img width="1184" alt="Image" src="https://github.com/user-attachments/assets/6593ce8e-d630-408c-be03-18ba77493f78" />

- Hot Threads Log
```
100.2% [cpu=100.2%, other=0.0%] (500.8ms out of 500ms) cpu usage by thread 'elasticsearch[xxx-3][[xxx][0]: Lucene Merge Thread #869]'
  10/10 snapshots sharing following 32 elements
    java.base@21.0.2/sun.nio.ch.UnixFileDispatcherImpl.pread0(Native Method)
    java.base@21.0.2/sun.nio.ch.UnixFileDispatcherImpl.pread(UnixFileDispatcherImpl.java:57)
    java.base@21.0.2/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:338)
    java.base@21.0.2/sun.nio.ch.IOUtil.read(IOUtil.java:306)
    java.base@21.0.2/sun.nio.ch.IOUtil.read(IOUtil.java:283)
    java.base@21.0.2/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:984)
    java.base@21.0.2/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:967)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.store.NIOFSDirectory$NIOFSIndexInput.readInternal(NIOFSDirectory.java:182)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.store.BufferedIndexInput.refill(BufferedIndexInput.java:356)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.store.BufferedIndexInput.readFloats(BufferedIndexInput.java:246)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.codecs.lucene95.OffHeapFloatVectorValues.vectorValue(OffHeapFloatVectorValues.java:65)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.codecs.lucene95.OffHeapFloatVectorValues$DenseOffHeapVectorValues.vectorValue(OffHeapFloatVectorValues.java:95)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.util.hnsw.RandomVectorScorerSupplier$FloatScoringSupplier$1.score(RandomVectorScorerSupplier.java:125)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.util.hnsw.HnswGraphSearcher.searchLevel(HnswGraphSearcher.java:237)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.util.hnsw.HnswGraphBuilder.addGraphNode(HnswGraphBuilder.java:247)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.util.hnsw.HnswGraphBuilder.addVectors(HnswGraphBuilder.java:179)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.util.hnsw.HnswGraphBuilder.addVectors(HnswGraphBuilder.java:187)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.util.hnsw.HnswGraphBuilder.build(HnswGraphBuilder.java:158)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.util.hnsw.IncrementalHnswGraphMerger.merge(IncrementalHnswGraphMerger.java:147)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.codecs.lucene99.Lucene99HnswVectorsWriter.mergeOneField(Lucene99HnswVectorsWriter.java:373)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.codecs.perfield.PerFieldKnnVectorsFormat$FieldsWriter.mergeOneField(PerFieldKnnVectorsFormat.java:122)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.codecs.KnnVectorsWriter.merge(KnnVectorsWriter.java:98)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.index.SegmentMerger.mergeVectorValues(SegmentMerger.java:255)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.index.SegmentMerger$$Lambda/0x0000005802813f88.merge(Unknown Source)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.index.SegmentMerger.mergeWithLogging(SegmentMerger.java:298)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:149)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:5252)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4740)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.merge(IndexWriter.java:6541)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:639)
    app/org.elasticsearch.server@8.13.4/org.elasticsearch.index.engine.ElasticsearchConcurrentMergeScheduler.doMerge(ElasticsearchConcurrentMergeScheduler.java:118)
    app/org.apache.lucene.core@9.10.0/org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:700)
```

- Master Node Kicked Data Node reason by lagging
```
node [{xxx-3}{xxx}{xxx}{xxx-3}{xxx}{xxx:9300}{dr}{8.13.4}{xxx}{xpack.installed=true, k8s_node_name=xxx, transform.config_version=10.0.0, ml.config_version=12.0.0, zone=ap-northeast-2a}] is lagging at cluster state version [46261], although publication of cluster state version [46262] completed [1.5m] ago
node [{xxx-1}{xxx}{xxx}{xxx-1}{xxx}{xxx:9300}{dr}{8.13.4}{xxx}{k8s_node_name=xxx, xpack.installed=true, transform.config_version=10.0.0, ml.config_version=12.0.0, zone=ap-northeast-2c}] is lagging at cluster state version [46261], although publication of cluster state version [46262] completed [1.5m] ago
node [{xxx-2}{xxx}{xxx}{xxx-2}{xxx}{xxx:9300}{dr}{8.13.4}{xxx}{xpack.installed=true, k8s_node_name=xxx, transform.config_version=10.0.0, ml.config_version=12.0.0, zone=ap-northeast-2a}] is lagging at cluster state version [46261], although publication of cluster state version [46262] completed [1.5m] ago

node-left[{xxx-1}{xxx}{xxx}{xxx-1}{xxx}{xxx:9300}{dr}{8.13.4}{xxx} reason: lagging, {xxx-2}{xxx}{xxx}{xxx-2}{xxx}{xxx:9300}{dr}{8.13.4}{xxx} reason: lagging], term: 12, version: 46264, delta: removed {{xxx-1}{xxx}{xxx}{xxx-1}{xxx}{xxx:9300}{dr}{8.13.4}{xxx}, {xxx-2}{xxx}{xxx}{xxx-2}{xxx}{xxx:9300}{dr}{8.13.4}{xxx}}
node-left[{xxx-3}{xxx}{xxx}{xxx-3}{xxx}{xxx:9300}{dr}{8.13.4}{xxx} reason: lagging], term: 12, version: 46263, delta: removed {{xxx-3}{xxx}{xxx}{xxx-3}{xxx}{xxx:9300}{dr}{8.13.4}{xxx}}
```

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

Specifically:

1. You're using 8.13.4 which is several versions behind the latest, and this area of the system has seen significant changes in the meantime. Please upgrade to the latest version.

2. A busy merge thread does not in itself explain a node leaving the cluster. This suggests your cluster is configured badly, or suffering from some kind of environmental issue, and that's not something we can address by changing anything in Elasticsearch. Please see [the troubleshooting guidance in the manual](https://www.elastic.co/guide/en/elasticsearch/reference/current/troubleshooting-unstable-cluster.html#troubleshooting-unstable-cluster-lagging) for further information about troubleshooting this situation, and note that newer versions typically have better troubleshooting support for things like this.

3. The stack dump of the busy merge thread suggests it's spending all the CPU time within the `pread0()` JVM function which is a thin wrapper around the `pread64` syscall. Pretty surprising to see so much CPU time spent here, again this seems like an environmental problem rather than something we can address in Elasticsearch.

There's an active community in the [forum](https://discuss.elastic.co/c/elasticsearch) that should be able to help get an answer to your question. As there's nothing to change in Elasticsearch at this time, I hope you don't mind that I close this issue.
