### ISSUE TITLE
(::regression from ES 1.3.5 ) Elasticsearch 1.6.0 - "unmapped_type"/"ignore_unmapped" does not work for Sorting with nested filter

### ISSUE THREAD

**Issue by navneet83** [elastic/elasticsearch#11931]
"unmapped_type"/"ignore_unmapped" does not work when used with sorting with nested filter. This example will make it clear:

Create two indexes - __testindex1__ and __testindex2__:
```json
curl -XPUT localhost:9200/testindex1 -d '{"mappings":{"type1":{"properties":{"firstname":{"type":"string"},"servers":{"type":"nested","properties":{"name":{"type":"string"},"location":{"type":"nested","properties":{"name":{"type":"string"}}}}}}}}}'

curl -XPUT localhost:9200/testindex2 -d '{"mappings":{"type1":{"properties":{"firstname":{"type":"string"},"computers":{"type":"nested","properties":{"name":{"type":"string"},"location":{"type":"nested","properties":{"name":{"type":"string"}}}}}}}}}'
```
The only difference between these two indexes is - __testindex1__ has "server" field and __textindex2__ has "computers" field. 
Now let's insert test data in both the indexes:
```json
curl -XPUT localhost:9200/testindex1/type1/1 -d '{"firstname":"servertom","servers":[{"name":"server1","location":[{"name":"location1"},{"name":"location2"}]},{"name":"server2","location":[{"name":"location1"}]}]}'
curl -XPUT localhost:9200/testindex1/type1/2 -d '{"firstname":"serverjerry","servers":[{"name":"server2","location":[{"name":"location5"}]}]}'
```
```json
curl -XPUT localhost:9200/testindex2/type1/1 -d '{"firstname":"computertom","computers":[{"name":"computer1","location":[{"name":"location1"},{"name":"location2"}]},{"name":"computer2","location":[{"name":"location1"}]}]}'
curl -XPUT localhost:9200/testindex2/type1/2 -d '{"firstname":"computerjerry","computers":[{"name":"computer2","location":[{"name":"location5"}]}]}'
```
Case 1 - Regular sort (without nested filter)  + "unmapped_type"/"ignore_unmapped" works fine. No issues here. This can be seen by following queries:
```json
curl -XPOST 'localhost:9200/testindex2/_search?pretty' -d '{"fields":["firstname"],"query":{"match_all":{}},"sort":[{"servers.location.name":{"order":"desc","unmapped_type":"string"}}]}'
curl -XPOST 'localhost:9200/testindex2/_search?pretty' -d '{"fields":["firstname"],"query":{"match_all":{}},"sort":[{"servers.location.name":{"order":"desc","ignore_unmapped": "true"}}]}'
```
Both the queries above run on __"testindex2"__ which does not have "servers.location.name" field.  Both the queries run fine as we have used - "unmapped_type"/"ignore_unmapped", however sort field has some integer value which is not expected:
```json
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : null,
    "hits" : [ {
      "_index" : "testindex2",
      "_type" : "type1",
      "_id" : "1",
      "_score" : null,
      "fields" : {
        "firstname" : [ "tom" ]
      },
      "sort" : [ -9223372036854775808 ]
    }, {
      "_index" : "testindex2",
      "_type" : "type1",
      "_id" : "2",
      "_score" : null,
      "fields" : {
        "firstname" : [ "tom" ]
      },
      "sort" : [ -9223372036854775808 ]
    } ]
  }
}
```
Case 2 - Nested filter sort on __testindex1__ works fine as  __"servers.location.name"__ field is present in this index:
```json
curl -XPOST 'localhost:9200/testindex1/_search?pretty' -d '{"fields":["firstname","servers.location.name"],"query":{"match_all":{}},"sort":[{"servers.location.name":{"order":"desc","unmapped_type":"string","nested_filter":{"term":{"servers.location.name":"location5"}},"nested_path":"servers"}}]}'
curl -XPOST 'localhost:9200/testindex1/_search?pretty' -d '{"fields":["firstname","servers.location.name"],"query":{"match_all":{}},"sort":[{"servers.location.name":{"order":"desc","ignore_unmapped": "true","nested_filter":{"term":{"servers.location.name":"location5"}},"nested_path":"servers"}}]}'
```

Case 3 - Nested filter sort on __testindex2__ doesn't work even if "unmapped_type"/"ignore_unmapped" is used. Following examples throw error:
```json
curl -XPOST 'localhost:9200/testindex2/_search?pretty' -d '{"fields":["firstname","servers.location.name"],"query":{"match_all":{}},"sort":[{"servers.location.name":{"order":"desc","unmapped_type":"string","nested_filter":{"term":{"servers.location.name":"location5"}},"nested_path":"servers"}}]}'
curl -XPOST 'localhost:9200/testindex2/_search?pretty' -d '{"fields":["firstname","servers.location.name"],"query":{"match_all":{}},"sort":[{"servers.location.name":{"order":"desc","ignore_unmapped": "true","nested_filter":{"term":{"servers.location.name":"location5"}},"nested_path":"servers"}}]}'
```

Surprisingly, Issue with "ignore_unmapped" example in Case 3 is not observed in older version of elasticsearch - 1.1.0 and the query works fine.

**Comment by navneet83** [comment]
I have tried this on ES 1.4 and 1.6

**Comment by navneet83** [comment]
Exception : ```[2015-06-29 23:18:46,442][DEBUG][action.search.type       ] [Smuggler] All shards failed for phase: [query]
org.elasticsearch.search.SearchParseException: [testindex2][4]: query[ConstantScore(*:*)],from[-1],size[-1]: Parse Failure [Failed to parse source [{"fields":["firstname","servers.location.name"],"query":{"match_all":{}},"sort":[{"servers.location.name":{"order":"desc","ignore_unmapped": "true","nested_filter":{"term":{"servers.location.name":"location5"}},"nested_path":"servers"}}]}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:735)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:560)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:532)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:294)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.query.QueryParsingException: [testindex2] [nested] failed to find nested object under path [servers]
	at org.elasticsearch.index.query.support.NestedInnerQueryParseSupport.setPath(NestedInnerQueryParseSupport.java:163)
	at org.elasticsearch.search.sort.SortParseElement.addCompoundSortField(SortParseElement.java:173)
	at org.elasticsearch.search.sort.SortParseElement.parse(SortParseElement.java:86)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:719)
	... 9 more
```

**Comment by clintongormley** [comment]
Hi @navneet83 

Thanks for the detailed reproduction!

> Both the queries above run on "testindex2" which does not have "servers.location.name" field. Both the queries run fine as we have used - "unmapped_type"/"ignore_unmapped", however sort field has some integer value which is not expected

`ignore_unmapped` is deprecated in favour of `unmapped_type` for this very reason: we need to know the datatype of the sort value up front.  Also see #9155 

> Case 3 - Nested filter sort on testindex2 doesn't work even if "unmapped_type"/"ignore_unmapped" is used. Following examples throw error:

Yes, this is a known issue with eg nested, parent-child, geo, function_score, which require the field to be mapped.  We're discussing what approach to take to solve this in #11806 

I think both issues are already covered in other tickets, so I'm going to close this one.  Thanks
