### ISSUE TITLE
Enable "Spatial Join" Aggregations Behavior

### ISSUE THREAD

**Issue by giaconiamark** [elastic/elasticsearch#11956]
Sorry for the horrible title. Since a geohash aggregation is not possible with geo_shape type items in an index (which makes sense), I would like to be able to produce a count of features (geoshapes) that intersect another "layer" of features (which can be in the form of another query or a different index).
Here is a sql equivalent to illustrate what I'm trying to do.

SELECT
a.id, 
a.thePolygonGeom,
COUNT(b.id) as cnt
FROM a 
INNER JOIN b
ON st_intersects(a.geom, b.geom) 
GROUP BY a.id,a.thePolygonGeom;

in this example, table A would be the geohash grid.

This way I could load an index with a pregenerated geohash grid shapefile, and dynamically intersect other geoshapes for stats at different levels.

let me know if this is a dumb idea, or if it's already possible.

**Comment by clintongormley** [comment]
Hi @giaconiamark 

An inner join like the one you describe would not perform well at all.  We don't support even simple term-based distributed joins because the performance would be terrible (and wouldn't scale).  That said, using a list of shapes in a "geo-terms" aggregation, with intersecting shapes collected in each bucket, might be an interesting idea.

@nknize @jpountz any thoughts?

**Comment by giaconiamark** [comment]
Yes, the ladder is something like I need... I need buckets with an itemid and count of shapes that intersected that shape, grouped by type. What I think it amounts to is a bucket aggregation, but with a collection of shapes as a filter, and it would return buckets containing the shape and id of each shape in the collection.
The purpose (use case) for this is to understand density of shapes.
I have a cluster with well over a billion shapes, and need to know basic things like "where are the most roads?" and "where do I not have buildings" etc.
I think each item in the returned json array would look something like this psuedo
"buckets:".....

"bucket":{
  "join_shape":{..polygon of coords...},
  "featureTypes:{   
    "road":234},   
    "river":190,
    "building":756,
    "etc...":869678}
}
an array of these would allow me to do very interesting visualizations across the globe of what I have where...likely wouldn't ever produce more than a few hundred polygons (it would be based on zoom level).

right now I accomplish this manually by generating my own grid of polygons, and doing a bbox intersects with each box to get a count of features that overlap on my webserver.
It should act very similar to what a geohash agg currently does, except this works off of another index of shapes or a query for shapes.

Hope this helps

**Comment by colings86** [comment]
@giaconiamark I think you should be able to achieve this already with the filters aggregation? You can create a filter containing geo polygon filter(s) for each of your 'layers' and use this to create buckets containing documents with geo_shape's that intersect each 'layer'.

**Comment by giaconiamark** [comment]
thanks guys, I'll give that a shot
