### ISSUE TITLE
Extraction of Log Messages

### ISSUE THREAD

**Issue by praveenaxxera** [elastic/elasticsearch#11968]
where and how to write the custom filters to extract required fields in syslog message: 

message:Jun 30 21:35:52 192.168.100.244 local3: Cloudera|Navigator|1|type="HDFS",allowed="true",time="1435725371265",service="hdfs",user="oozie",ip="127.0.0.1",op="listStatus",src="/user/oozie/share/lib"

@timestamp	 	July 1st 2015, 10:06:12.937
t@version	 	1
t_id	 	AU5H5p4MXChH4k1HWWib
t_index	 	logstash-2015.07.01
t_source	 	{"message":"Jun 30 21:35:52 192.168.100.244 local3: Cloudera|Navigator|1|type=\"HDFS\",allowed=\"true\",time=\"1435725371265\",service=\"hdfs\",user=\"oozie\",ip=\"127.0.0.1\",op=\"listStatus\",src=\"/user/oozie/share/lib\"","@version":"1","@timestamp":"2015-07-01T04:36:12.937Z","type":"cloudera","file":"/var/log/navigator.log","host":"syslogserver","offset":"7809436"}
t_type	 	cloudera
tfile	 	/var/log/navigator.log
thost	 	syslogserver
tmessage	 	Jun 30 21:35:52 192.168.100.244 local3: Cloudera|Navigator|1|type="HDFS",allowed="true",time="1435725371265",service="hdfs",user="oozie",ip="127.0.0.1",op="listStatus",src="/user/oozie/share/lib"
toffset	 	7809436
ttype	 	cloudera

i want to extract message field ,
please anyone suggest me where and how to write extraction logic,and where the default filters in logstash are located
-thanks

**Comment by dadoonet** [comment]
You are asking about logstash in an elasticsearch issue system.
Not the right place, definitely.

Join us on discuss.elastic.co where we and the community can help you!
