### ISSUE TITLE
handling queue ids vs message ids

### ISSUE THREAD

**Issue by HoppeT** [elastic/elasticsearch#11997]
hey mates,

maybe some of you could help me with a problem i'm acutally trying to solve.
we're using logstash in combination with logstash-forwarder and elasticsearch to store the data. 

we're trying to analyze our internal mail routing. so we've got about 5 different kinds of log types and so we have 5 different queue ids (each system gives the incoming mail a different id) for one message id which is equal over the different systems. so e.g. we have 10 entries with the queue id 1234 but only one entry with the queue id 1234 and the message id xyz. but we need to combine / match / map every of these entries with the correct message id over all of these different log types.

our problem now is to match the data correct to our dashboard. 

i would be deeply grateful if some of you guys could show us a solution to solve this problem

-cheers

**Comment by clintongormley** [comment]
Hi @HoppeT 

My initial thought would be to have a background job which pulls recent logs, groups them on message id, and the indexes a new log as a combined entry. I suggest asking this to the forum http://discuss.elastic.co/ as the github issues list is for bug reports and feature requests

thanks
