### ISSUE TITLE
Fast Vector Highlighter highlights only first 1024 terms for prefix query

### ISSUE THREAD

**Issue by zdeseb** [elastic/elasticsearch#12013]
**Fast Vector Highlighter** in combination with **prefix** query **highlights** only **first 1024** suitable **terms**.

**All next terms are ignored for highlighting !!!** :disappointed:

This fvh behavior differs from **plain highlighter** (which highlighted all 1346 terms in my testing index) and **prefix query** behavior and I didn't found any documented setting which could increase this limit.

**Comment by nik9000** [comment]
> Fast Vector Highlighter in combination with prefix query highlights only first 1024 suitable terms.

Its hard coded:
http://grepcode.com/file/repo1.maven.org/maven2/org.apache.lucene/lucene-highlighter/4.10.4/org/apache/lucene/search/vectorhighlight/FieldQuery.java#62

> This fvh behavior differs from plain highlighter (which highlighted all 1346 terms in my testing index) and prefix query behavior and I didn't found any documented setting which could increase this limit.

The [experimental highlighter](https://github.com/wikimedia/search-highlighter) has a fix for this: it highlights the automaton for the prefix query.


For the most part its better to do term lookups on edgeNGrams than it is to do prefix queries. Rather, its faster at query time.

**Comment by zdeseb** [comment]
Thanks for answer.

So I will try to use Experimental Highlighter instead of FVH (but it's name sounds little bit dangerously :smile:). I hope it will not be out of the frying pan into the fire :smile: 

But at least it will be better to add info about this incompatibility to [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html#fast-vector-highlighter) (if it is not possible to ensure consistent behavior)

**Comment by nik9000** [comment]
> But at least it will be better to add info about this incompatibility to documentation (if it is not possible to ensure consistent behavior)

You can totally update that document. Click on the edit button and replace the ```1.6``` in the url with ```master``` and github will walk you through making a pull request. I hope. You'd have to sign the CLA to get it merged but it'd be a great thing to do!

Ping @clintongormley - that link isn't working properly. See above.

> So I will try to use Experimental Highlighter instead of FVH (but it's name sounds little bit dangerously :smile:). I hope it will not be out of the frying pan into the fire :smile:

Yeah - the name is unfortunate. It was experimental nine months ago. Right now its doing all the highlighting on site search on wikipedia and is working fine. It had some interesting bugs at times but it gets lots of exercise so we found them and squashed them. Its newer than the other hihglighters and not as widely used so there are certainly some rough edges that we have yet to find though.

**Comment by clintongormley** [comment]
> Ping @clintongormley - that link isn't working properly. See above.

@nik9000 which link?

**Comment by nik9000** [comment]
The edit links in the docs open up a page that says your fork is out of
date... Or maybe that is just me.... If it is then its more a github bug
than a docs bug. I figured clicking the link would do the right thing
regardless of how up to date my fork is.

**Comment by clintongormley** [comment]
ok - that's a github thing then
