### ISSUE TITLE
Deprecate `indices` query in favour of making `_index` queryable

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12017]
The `indices` query allows the user to run different queries on different indices, eg to create a union of docs from different indices, where the conditions to be applied to each index are different.

A simpler way to write this query would be to make `_index` usable in the `term`, `terms`, `match`, `query_string`, and `simple_query_string`queries (see #3316).

However, this change also depends on the changes in #12016 to allow unmapped fields to be handled gracefully across all queries.

**Comment by jpountz** [comment]
+1

**Comment by colings86** [comment]
+1
