### ISSUE TITLE
Search for results based on aggregations

### ISSUE THREAD

**Issue by ptgamr** [elastic/elasticsearch#12024]
The use of aggregation is popular for the use case of **In this date range, how many visits we have in total?**

However, what should I do when I want something reverse: **On which days does I have the visits range from x to y?**

I can think of we still have to use Aggregation to compute total visits of each day, and from that result, we will do a Range Aggregation to filter the result. But I can not come up with a query. 

Thanks a lot for your help!

**Comment by markwalkom** [comment]
Please join us in #elasticsearch on Freenode or at https://discuss.elastic.co/ for troubleshooting and design help, we reserve Github for confirmed bugs and feature requests :)

**Comment by ptgamr** [comment]
thanks @markwalkom , here is the relevance link to the forum: https://discuss.elastic.co/t/search-for-results-based-on-aggregations/24888/1
