### ISSUE TITLE
Query Refactoring: Set default minimumShouldMatch for BoolQueryBuilder in filter context

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#12022]
In BoolQueryParser we currently set minimumShouldMatch to at least 1 (see #11915 for initial discussion), if there is no other value supplied in the JSON and the BoolQuery sits inside a filter. This should only happen when the first clause gets added to the should-clauses. 

Because we will only know if a QueryBuilder will generate a non-null query when calling its `toQuery` method later, this should happen in the BoolQueryBuilder. The problem with this is that currently now we are using the isFilter() state of the QueryParseContex, but we don't set this when traversing the query-tree when generating the lucene queries in `toQuery()` yet.

First we will need to dividing the context into a query parse context and a query context I think and then start setting  correct filter flag when entery subclauses in filter context like we now to in `parseInnerFilter()` in QueryParseContext.

This issue only affects the query refactoring feature branch.

**Comment by cbuescher** [comment]
Maybe it's also possible to handle the default setting for `minimumShouldMatch` similarly for filter context and query context. The conditional clause this was introduced as a result of merging BoolQueryParser and BoolFilterParser (a0af88e), maybe it is possible to remove this special case which would make it possible to set it on `toQuery` without having the filter context information available.

**Comment by javanna** [comment]
just so we don't forget, `isFilter` is used also in other queries while parsing (e.g. fuzzy query), this logic needs to move to the `toQuery` method, which means that we can probably get rid of this piece of state in the context.

**Comment by cbuescher** [comment]
Closing this, since it is addressed in #12731
