### ISSUE TITLE
Snapshots repo not found after upgrade to 1.6.0

### ISSUE THREAD

**Issue by vichargrave** [elastic/elasticsearch#12033]
I upgraded from 1.4.4 to 1.6.0 but now my snapshot repositories are can no longer be found via RESTful API.  I can see the repository attributes with this command:

GET _snapshot/twitter_backup3/

{
   "twitter_backup3": {
      "type": "fs",
      "settings": {
         "compress": "true",
         "location": "/media/snaps3"
      }
   }
}

But when I try to look at one of the snapshots I get the following error:

GET _snapshot/twitter_backup3/2015-07-01

{
   "error": "RemoteTransportException[[r5-9-37][inet[/10.202.245.1:9300]][cluster:admin/snapshot/get]]; nested: RepositoryMissingException[[twitter_backup3] missing]; ",
   "status": 404
}

The snapshot files are still visible on disk.  Also I'm not having this problem on 1.5.2.

**Comment by dadoonet** [comment]
I think it could be due because in 1.6, you need to add a new setting in `elasticsearch.yml`: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_shared_file_system_repository

Try to add: `path.repo: ["/media"]` and restart your node.

**Comment by vichargrave** [comment]
I tried this out on Elasticsearch on my MacOS.  It seems that I have to restart ES for these settings to take affect.  Is that correct?

**Comment by dadoonet** [comment]
Yes. I wrote "restart your node".

**Comment by clintongormley** [comment]
@vichargrave I assume @dadoonet 's advice fixed the issue, so I'll close

**Comment by vichargrave** [comment]
@dadoonet Right, sorry about that.  Thanks to the help.
