### ISSUE TITLE
Calculation of ES CPU Usage(in %) goes beyond 100%

### ISSUE THREAD

**Issue by shruthisantosh** [elastic/elasticsearch#12039]
Hi,

We have 3 Master, 2 Client and 19 Data nodes in our ES cluster. 
Each of the data nodes have 8 VCPUs . We are using the following Rest API URL to get the values of nodes.process.cpu.percent(A) and nodes.os.cpu.total_cores(B),
http://localhost:9200/_cluster/stats?human&pretty
We are trying to calculate ES CPU Usage in percentage

 using the formula, ((A / (100 *B)) * 100 . This computation is giving us values which go over 100%. 

We observed that the value of (B) as 8 since there are 8 VCPUs in each of the nodes and due to this  the value of (A) should be within 800. But we observed that the value of (A) goes beyond 800 which is causing the percentage to shoot up over 100.

![esstats](https://cloud.githubusercontent.com/assets/11938154/8512277/9a903a00-2359-11e5-8a24-0fa17278c2f9.jpg)

Please can you let us know if our calculations are correct and if so then is the value of (A) from the REST API having some issue.

Thanks 
Shruthi

**Comment by clintongormley** [comment]
Hi @shruthisantosh 

There are bugs in that statistic coming from sigar.  I'm going to close this issue as we have removed Sigar completely in master https://github.com/elastic/elasticsearch/pull/12010
