### ISSUE TITLE
where is default config mapping file

### ISSUE THREAD

**Issue by hy05190134** [elastic/elasticsearch#12048]
I just put a json file in config/mappings/_default directory, but I find it doesn't make sense, I just want to know where is the default mapping file, because I just using log stash to put data into ES.

**Comment by imotov** [comment]
@hy05190134 we are using github for bug reports and feature requests. Please use our support forums at https://discuss.elastic.co/ for questions like this. By the way, I think it might be easier to achieve what you are doing using an index template instead of overriding default mapping.
