### ISSUE TITLE
Script bin/plugin doesn't use different plugin path set in elasticsearch

### ISSUE THREAD

**Issue by radoondas** [elastic/elasticsearch#12046]
Hi,
my elasticsearch setup has set different path for plugin directory. 
When installing new plugin, binary "bin/plugin" does not check the different path I have set in config file and uses the default path. 
My first impression was that script will read config/elasticsearch.yml file to get the path but it is ignored.

Of course, it is possible to hack around this "bin/plugin" script, but my intention was to not to touch scripts coming with installation. I would prefer to pass argument to the script or simply accept config values in elasticsearch.yml.

Is this behavior as it suppose to be? Or I do something wrong. :)

Elasticsearch version. 1.6.

Thanks,
Rado

**Comment by clintongormley** [comment]
@radoondas is this using the Zip or tar.gz packages? or RPM/deb?

**Comment by radoondas** [comment]
I am using latest version of ES 1.6.0 and it is downloaded as zip. 
OS: SUSE Enterprise linux, 64bit

**Comment by clintongormley** [comment]
Have you moved the location of the `config` directory?

If so, try doing:

    CONF_DIR=/path/to/config/dir bin/plugin install pluginname

**Comment by radoondas** [comment]
Sorry for late answer. 

But, as you guessed correctly, I have changed the config directory too and did not mention it. 
As you suggested, this solution works and it is sufficient for all cases where also config directory is in different location.

Thanks.
