### ISSUE TITLE
A doc has many geo_point fileds

### ISSUE THREAD

**Issue by mouzt** [elastic/elasticsearch#12050]
would like to be able to sort based on the closest matching location in the document
mapper is:(stations is one array filed)

"stations":{
                "properties":{
                    "station_name":{"type":"string","index":"analyzed"},
                    "station_position":{"type":"geo_point","lat_lon": true},
                    "type":{"type":"integer"}
                }
            }

stations: 
[
{
    "station_name": "bla bla",
    "station_pos": {
        "lat": 39.985303,
       "lon": 116.313024
    },
    "type": 1
},
{
    "station_name": "bbbbb",
    "station_pos": {
        "lat": 34.97503,
       "lon": 117.313024
    },
    "type": 1
}
]

I got an Exception :
failed to find mapper for [station_pos] for geo distance based sort

how I sort them by distance?

**Comment by dadoonet** [comment]
Please use discuss.elastic.co for those questions.

Not an issue here.

BTW note that it seems you are mixing `station_position` and `station_pos `
