### ISSUE TITLE
try to improve integration tests setup/teardown

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#12063]
Integration test logic starts up ES with all defaults (and for plugins installs a plugin). the teardown phase basically does 'killall elasticsearch'. Currently this stuff is just done the same way the python release script did things.

Ideally these could be more fine-grained, maybe read from a PID file instead, maybe use a non-default port number, etc.

**Comment by spinscale** [comment]
I think we can we close, since `stop-external-cluster` uses the pid file for killing the process, see https://github.com/elastic/elasticsearch/blob/master/dev-tools/src/main/resources/ant/integration-tests.xml#L235-L251

**Comment by clintongormley** [comment]
@brwe please could you look at this TODO

**Comment by brwe** [comment]
todo has been taken care of in #12961. can we close this?

**Comment by clintongormley** [comment]
Looks like it, thanks @brwe
