### ISSUE TITLE
add simple rest tests for plugins where possible.

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#12062]
Currently only the delete by query plugin has any rest tests that verify the plugin works during integration tests. Other plugins just get installed and ES starts up but thats it as far as verification that they are "working". It would be better if e.g. the analyzer ones had very simple tests that ensured the plugin worked.

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/12091
