### ISSUE TITLE
plugin installation gives lots of logger warnings.

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#12064]
Try running `mvn verify` for a plugin and you will see that `bin/plugin` causes a lot of noise:

    [echo] Installing plugin elasticsearch-delete-by-query...
    [exec] -> Installing elasticsearch-delete-by-query/2.0.0-SNAPSHOT...log4j:WARN No appenders could be found for logger (org.elasticsearch.bootstrap).
    [exec] 
    [exec] log4j:WARN Please initialize the log4j system properly.Trying file:/home/rmuir/workspace/elasticsearch/plugins/delete-by-query/target/releases/elasticsearch-de......
    [exec] 
    [exec] log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.Downloading .DONE
    [exec] 
    [exec] Installed elasticsearch-delete-by-query/2.0.0-SNAPSHOT into /home/rmuir/workspace/elasticsearch/plugins/delete-by-query/target/integ-tests/elasticsearch-2.0.0-SNAPSHOT/plugins/2.0.0-SNAPSHOT

**Comment by dadoonet** [comment]
Sounds like log4j.properties is not in the classloader.
