### ISSUE TITLE
New node created after reboot

### ISSUE THREAD

**Issue by behindthefirewalls** [elastic/elasticsearch#12077]
Hi,

I have installed ELK in the same machine and there is no ES cluster configuration.

After rebooting the server a new node appeared. So now, I have Node0 and Node1. Node0 has all the previous logs but now, I can´t get access to it via Kibana. Node1 has the data since the server was restarted.

What can I do?

Regards

**Comment by dadoonet** [comment]
Please use discuss.elastic.co. We can help you there.

Closing. Not an issue.
