### ISSUE TITLE
field "xxx" was indexed without position data; cannot run PhraseQuery (term=storing)

### ISSUE THREAD

**Issue by PavelPolyakov** [elastic/elasticsearch#12079]
Hi,

I do the next query via Kibana:
```
_type:xxx-dev AND message:'Storing the yyy zzz' AND data.values:*test@email.com*
```

And receive the next response:
![image](https://cloud.githubusercontent.com/assets/839290/8544385/1e3c8efc-24a5-11e5-9766-e7347b6b07a7.png)

However, the message is analyzed, in the template:
![image](https://cloud.githubusercontent.com/assets/839290/8544392/30611274-24a5-11e5-8f81-8ee6ed2190c5.png)

(some time ago it was not_analyzed)
![image](https://cloud.githubusercontent.com/assets/839290/8544440/96bcc7f2-24a5-11e5-81ee-b43102b36b43.png)

If I put the message AND to the end of the query - it works well:
```
_type:xxx-dev AND data.values:*test@email.com* AND message:'Storing the yyy zzz'
```

How I can overcome this?

Regards,

**Comment by PavelPolyakov** [comment]
still interested in the answer

**Comment by jpountz** [comment]
Can you provide us with the mappings of this message field on all your types?

The query would look something like `GET /${index_name}/_mapping/field/message`. https://www.elastic.co/guide/en/elasticsearch/reference/1.6/indices-get-field-mapping.html

**Comment by PavelPolyakov** [comment]
@jpountz 

Here it is:

```
{
    "logstash-2015.07.08": {
        "mappings": {
            "zzz": {
                "message": {
                    "full_name": "message",
                    "mapping": {
                        "message": {
                            "type": "string",
                            "index": "not_analyzed"
                        }
                    }
                }
            },
            "yyy": {
                "message": {
                    "full_name": "message",
                    "mapping": {
                        "message": {
                            "type": "string",
                            "store": true
                        }
                    }
                }
            },
            "xxx": {
                "message": {
                    "full_name": "message",
                    "mapping": {
                        "message": {
                            "type": "string",
                            "store": true
                        }
                    }
                }
            }
        }
    }
}
```

Do you think it happens because of the zzz type?
I would update it, to see what happens tomorrow.

**Comment by jpountz** [comment]
@PavelPolyakov Indeed, it very likely happened because of zzz. Unfortunately this is a known issue on 1.x that all fields of the same index that have the same name need to have consistent mappings. In Elasticsearch 2.x this will be enforced and creating a type with different mappings will raise an error, which will be less trappy.
