### ISSUE TITLE
Import information from an Oracle database

### ISSUE THREAD

**Issue by antoniogarcez** [elastic/elasticsearch#12080]
Hi!

I read that the rivers plugins have been deprecated. How we import information from an Oracle database?

**Comment by colings86** [comment]
There is a jdbc importer plugin created by @jprante [1] and the Logstash project is working on a jdbc input too.

Please note that we try to keep the Github issues list for project issues such as bugs and feature requests. We have discussion forums available for asking questions like these and getting help using the software: https://discuss.elastic.co

[1] https://github.com/jprante/elasticsearch-jdbc
