### ISSUE TITLE
Precise and consistent MapperParsingException messages

### ISSUE THREAD

**Issue by f-s-p** [elastic/elasticsearch#12098]
The "error" field value that is returned for a MappingParserException is inconsistent and imprecise, which makes it difficult to programatically address.  This may be related to #7983.

For example:
```sh
# dynamically create a mapping
curl -XPOST 'http://localhost:9200/error_test/my_docs' -d '{ "complex_obj": { "data": { "value": { "data": { "name": "alice" } } } } }'
# violate it
curl -XPOST 'http://localhost:9200/error_test/my_docs' -d '{ "complex_obj": { "data": { "value": { "data": "alice" } } } }'
{"error":"MapperParsingException[object mapping for [my_docs] tried to parse field [complex_obj] as object, but got EOF, has a concrete value been provided to it?]","status":400}
# violate it in the same way but with an additional root field
curl -XPOST 'http://localhost:9200/error_test/my_docs' -d '{ "complex_obj": { "data": { "value": { "data": "alice" } } }, "data": "a simple string" }'
{"error":"MapperParsingException[object mapping for [complex_obj] tried to parse field [data] as object, but got EOF, has a concrete value been provided to it?]","status":400}
```

The two error messages returned are inconsistent.  The first square bracket'ed name is the document type in the first instance and in the other is a field name.

The messages also do not indicate the exact field causing the exception.  It is difficult to determine which field does the field name refer to if there are multiple fields with the same name.  It would be more helpful to provide the full dotted path of the field the caused the exception, such as ```complex_ob.data.value.data```.

**Comment by rjernst** [comment]
This has to do with how the mappings are structured internally (the type is a fake "root object" mapper). However, in 2.0, all field name references have been changed to use the full path (the dot notation you mention).

As for programatically addressing, I don't know that this can ever be possible. Dealing with mapping errors isn't something that is intended to be done programatically. The mappings try to give as much context information as they can, but the format of the exception message is not in any way stable, and may change at any time.

**Comment by clintongormley** [comment]
In master, both of the above requests return the same exception:

    "object mapping for [complex_obj.data.value.data] tried to parse field [data] as object, but found a concrete value"

closing
