### ISSUE TITLE
simple query  NullPointerException only on 1.6

### ISSUE THREAD

**Issue by Zincr0** [elastic/elasticsearch#12096]
This works on 1.5:

    GET _search
    {
      "query": {
        "query_string": {
          "query": "*",
          "fields": [
            "_id"
          ]
        }
      }
    }

returns:

    {
        took: 1
        timed_out: false
        _shards: {
            total: 5
            successful: 5
            failed: 0
        }
        hits: {
            total: 0
            max_score: null
            hits: [ ]
        }
    }

but in elasticsearch 1.6 returns:

{
    "error": "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[f97FCaZyRKiUQ5ApvqkldA][facebook][0]: SearchParseException[[facebook][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"*","fields":["_id"]}}}]]]; nested: NullPointerException; }{[f97FCaZyRKiUQ5ApvqkldA][facebook][1]: SearchParseException[[facebook][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"*","fields":["_id"]}}}]]]; nested: NullPointerException; }{[f97FCaZyRKiUQ5ApvqkldA][facebook][2]: SearchParseException[[facebook][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"*","fields":["_id"]}}}]]]; nested: NullPointerException; }{[f97FCaZyRKiUQ5ApvqkldA][facebook][3]: SearchParseException[[facebook][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"*","fields":["_id"]}}}]]]; nested: NullPointerException; }{[f97FCaZyRKiUQ5ApvqkldA][facebook][4]: SearchParseException[[facebook][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"query_string":{"query":"*","fields":["_id"]}}}]]]; nested: NullPointerException; }]",
    "status": 400
}

**Comment by Zincr0** [comment]
workaround: 
{"query": {"query_string": {"query": "*"}}}

**Comment by clintongormley** [comment]
Hi @Zincr0 

I'm unable to replicate this on 1.6.0.  What is the mapping of your `facebook` index?  Do you have the full stack trace from the logs?

Your workaround simply searches the `_all` field instead of the `_id` field.

**Comment by Zincr0** [comment]
facebook was an empty index. 
I'm using elasticsearch 1.5.2 now, so i can't replicate the bug anymore. 
I guess you can close this.

**Comment by clintongormley** [comment]
this is fixed in master

closing
