### ISSUE TITLE
Mappings: Restrict unexpected characters from field names

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#12094]
You can manage to slip unexpected characters into field names, like `\n`, `\0` (`\u0000`), `\t`, `\'`, `\"`, etc. I think that we should prevent this, but the change would create a backwards incompatible restriction.

Big caveat/counter argument: as long as they're escaped, these unexpected characters _are_ valid JSON.

**Comment by jpountz** [comment]
Duplicate of https://github.com/elastic/elasticsearch/issues/9059
