### ISSUE TITLE
Is there an analyzer for ancient greek? or anyway I extend the existing analyzer for it?

### ISSUE THREAD

**Issue by apanimesh061** [elastic/elasticsearch#12097]
I require an Ancient greek analyzer as the existing Greek analyzer is not compatible with the ancient greek.

Is there any analyzer or should I consider extending the analyzer with new language???

**Comment by clintongormley** [comment]
Hi @apanimesh061 

We don't have an analyzer for ancient greek - you may have to come up with something yourself.  Also, try the ICU plugin https://github.com/elastic/elasticsearch-analysis-icu
