### ISSUE TITLE
fix license verification on windows?

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#12118]
I had to disable license verification on windows so that `mvn verify` would work in #12117

I installed strawberry perl and unzip.exe in my path, but the script will consistently compute the wrong sha1 checksum for lucene-analysis-kuromoji jar (i was testing with plugins/analysis-kuromoji)... i've verified (with windows fciv) that the checksum is correct, so there is something not right there.

Not sure its critical to fix this, its just omitted on windows right now.

**Comment by s1monw** [comment]
for now I think it's fine to just run this on unix though. @clintongormley what do you think?

**Comment by rmuir** [comment]
we turned this on for windows in #12528
