### ISSUE TITLE
Can We Process English With Elasticsearch ?

### ISSUE THREAD

**Issue by LinhTruongVan** [elastic/elasticsearch#12113]
Hi,
Can we process English with Elasticsearch via Analyzer of something like that?

**Comment by dadoonet** [comment]
Please join us on discuss.elastic.co. We can help there.

BTW use the english analyzer. https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#english-analyzer

**Comment by LinhTruongVan** [comment]
Thanks you ^^
