### ISSUE TITLE
RangeQuery on date field doesn't work inside SpanMultiTermQuery

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#12122]
SpanMultiTermQuery should wrap around any MultiTermQuery, including all variations on RangeQuery. However, when used on a field that has a date mapping, RangeQueryParser will return a LateParsingQuery via DateFieldMapper#rangeQuery(). Unfortunately LateParsingQuery doesn't extend MultiTermQuery, causing the later type check in SpanMultiTermQueryParser to fail.

**Comment by cbuescher** [comment]
I have added an integration test to SearchQueryTests that triggers this behaviour which I will add in a separate PR.

**Comment by javanna** [comment]
good catch @cbuescher given that SpanMultiTermQueryBuilder used to be a simple marker interface, I wonder what happens if LateParsingQuery implements it (or extends from it)? Would that fix it or cause more problems?

**Comment by cbuescher** [comment]
LateParsingQuery is a Lucene query, so it's not part of the ES query builder hierarchy. It would have to extend org.apache.lucene.search.MultiTermQuery. Tried that but then a couple of things need to be changed, not sure about all the steps needed there and if that might be the right thing.

**Comment by cbuescher** [comment]
After revisiting this, I think that the current behaviour of the SpanMultiTermQuery parser of throwing a QueryParsingException when the wrapped query is a range query on a date field makes sense. As noted in #12123 even if we rewrite LateParsingQuery, the target date field does not contain positional data, so this kind of query shouldn't work. Closing this with as 'won't fix'
