### ISSUE TITLE
Synced flush not taking very well

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#12134]
I *think* we're talking about a bug here: https://discuss.elastic.co/t/synced-flush-causes-node-to-restart/24220

It could be that we're both just having trouble but it seems like for some shards synced flush just claims that there are pending operations all the time. Its like reference counting is off or something. I've turned up the logging to 11 and I'll let the system run overnight and then try another synced flush again and hopefully will have something more concrete.

In the mean time it'd be nice to be able to get more insight into the IndexWriter for a shard specifically which condition is causing it to say it has pending operations.

**Comment by s1monw** [comment]
I replied to the discuss list... I think it's a bug on 1.x though...  master should be ok here

**Comment by mikemccand** [comment]
LGTM

**Comment by nik9000** [comment]
Can we close this now that that pull request is merged?

**Comment by clintongormley** [comment]
Hmm github seems to not be closing issues properly..  Closed by #12146
