### ISSUE TITLE
Wrong Aggregation of uniq counts / sum

### ISSUE THREAD

**Issue by new-gen23** [elastic/elasticsearch#12144]
I analyse netflow data. Data is send to nprobe, which in turn writes it natively to elasticsearch. 
Elastic search version: 1.5.2
Kibana version: 4.0.2

I do a "uniq count" of "IPV4_SRC_ADDR" for a single destination address. 
X-Axis: 
Aggregation: Date Histogram
Interval: Minute
This give me around 10 to 20 uniq IP's in average. Now, when I switch to an "hourly" Intervall, I get an average of 100 !

This becomes FAR WORSE when I do a "sum in_bytes" aggregationover 2 days. While the system measures around 200 kb/s, kibana switches to an multi hour aggregation and reports 140m bytes. I assume that "m" stands for "million" ?  I can only get "realistic" information if I split the timeframe in much smaller pieces and push the interval to minutes / seconds. 

Why is there such a grave, misleading difference in aggregation when doing a "sum"? And why is the only hint for this problem the very tiny "info" icon above the interval?
I understand, that doing a "sum" on a timeframe of 2 hours will sum all available data to a single point in the graph. Is there any way to warn about the fact, that the aggregation has a "blur" factor of X? Where X is the Factor of the Interval?

![screen shot 2015-07-09 at 09 34 07](https://cloud.githubusercontent.com/assets/1741662/8590312/9ed3c28a-261f-11e5-80a2-e3590a40ce01.png)
![screen shot 2015-07-09 at 09 34 25](https://cloud.githubusercontent.com/assets/1741662/8590313/9ed451dc-261f-11e5-987e-958a0c59b08a.png)

**Comment by colings86** [comment]
Could you paste your mapping (curl -XGET 'http://localhost:9200/INDEX_NAME/_mapping/TYPE') in a gist and link it here. It might help us determine what might be going on.

**Comment by new-gen23** [comment]
Sorry, had no time to follow the problem. Data was logrotated and is gone. Can not replicate the issue. Please close this ticket.
