### ISSUE TITLE
hashCode function isn't consistent with Objects.hash

### ISSUE THREAD

**Issue by alexksikes** [elastic/elasticsearch#12145]
In the query refactoring branch, the way we compute AbstractQueryBuilder#hashCode is the following:

hasCode = 31 * Objects.hash(query_name, boost) + doHashCode(child_class)

= 31 * Objects.hash(A, B) + doHashCode(C)

= 31 * f(A, B) + f(C) where f = Objects.hash

= 31 * (31 * (31 + A) + B) + 31 * C

!= (31 * (31 * (31 + A) + B)) + C = f(A, B, C) = Objects.hash(A, B, C)

**Comment by MaineC** [comment]
Can you elaborate on the implications of this?

**Comment by alexksikes** [comment]
I don't think this is a bug, it is just a remark. Do we want to stay consistent with Objects.hash?

**Comment by javanna** [comment]
Closed by https://github.com/elastic/elasticsearch/commit/1cfe580cb7c9da5657efcaaf2513ff07bcf93a0d
