### ISSUE TITLE
how to make the query that looks  like "A|B"?

### ISSUE THREAD

**Issue by mlc0202** [elastic/elasticsearch#12140]
Hello ,I met a difficult problem when i import elasticsearch to my project , it exists  logical operation like "A|B" in my  requirements,so ,how to make the query that looks  like "A|B"  in ealsticsearch?

**Comment by dadoonet** [comment]
Please ask questions on discuss.elastic.co. We can help there.

Have a look at the query DSL (bool) or search using a query string with "A B".

**Comment by mlc0202** [comment]
Unfortunately ,I have tried it,but it didn't resolve my problem,i describe it  more serious   in #12226
