### ISSUE TITLE
Delete unused mappings

### ISSUE THREAD

**Issue by albertvaka** [elastic/elasticsearch#12167]
I want to delete the mappings for a type when all the elements of that type have been deleted, but I found no way of knowing if a type is being used or not. Do I need to keep track of its usage myself to then delete the mapping (so I can reuse the same type name for something else) or is there a way to do so within ES?

Also, I've read that in 2.0 you will remove the ability to delete mappings. If that's true, it would be awesome if you automatically delete mappings for unused types then :) Is that in the plans?

Thanks a ton!

**Comment by clintongormley** [comment]
Hi @albertvaka 

No, it is not in the plans, and we don't allow you to delete mappings because it can result in index corruption later on.
