### ISSUE TITLE
Dynamic templates

### ISSUE THREAD

**Issue by rob-tice** [elastic/elasticsearch#12169]
Using a dynamic template, I have a need to create multiple indexed fields on the same string field using different analysers , however I wish these fields to be siblings of the matched field as opposed to children.

So, if I am matching on a field called 'value' at the moment I can currently specify the output (using a dynamic template) as (for example) value.text and value.string - so in the case where value is a child of description I would get

description.value.text
description.value.string (for example)

what i wish is to be able to obtain is

description.value
description.value_text

This means that I can add alternate indexed fields in future without breaking any existing searches.

Thanks

Rob

PS - I also think it has a **slight** tie in with the unwieldy need to specify the full path on a copy-to, where a shorthand 'copy-as-sibling' type feature would help greatly.

**Comment by clintongormley** [comment]
Hi @rob-tice 

There are no plans to support this.  Why do you need this feature? What's the problem with `description.value.text` instead of `description.value_text`?

**Comment by rob-tice** [comment]
I need it because otherwise I need to structure my indexes as though every possible string value has another level of hierarchy just in case I want to index it twice in the future. I already have an index structure which is highly nested and this makes it more  unwieldy and seems like a hack : ) . It just seemed  a logical extension to me… with behaviour like copy-to.

 

Cheers

 

R

**Comment by clintongormley** [comment]
I don't really understand what you mean by the index structuring comment or breaking searches by adding future fields.  However, I think we should support the `{path}` parameter, which would work like the `{name}` parameter. Then you can do:

    PUT t
    {
      "mappings": {
        "t": {
          "dynamic_templates": [
            {
              "foo": {
                "match": "foo*",
                "mapping": {
                  "type": "string",
                  "copy_to": [
                    "{path}.bar-{name}"
                  ]
                }
              }
            },
            {
              "bar": {
                "match": "bar*",
                "mapping": {
                  "type": "string",
                  "index": "not_analyzed"
                }
              }
            }
          ]
        }
      }
    }
    
    PUT t/t/1
    {
      "stuff": {
        "foo": "bar"
      }
    }

**Comment by rob-tice** [comment]
Hi Clinton

 

That was what I was hoping you would say : ). It would also fix my existing issues with the unwieldy existing copy-to.

 

From my perspective if the path was the path minus the actual field name then it would work for my use case and yours.

 

e.g.

 

“match”:”foo*”

 

So in that case I could choose to use:

 

copy-to:{path}.name_text

 

or  for your example it would be

 

copy-to:{path}.{name}.bar

 

as a concrete example:

 

a.b.c.foo=”test”

 

          "foo": {
            "match": "foo*",
            "mapping": {
              "type": "string",
              "copy_to": [
                "{path}.{name}-bar"
              ]
            }
          }
 
This would result in the content appearing in
 
a.b.c.foo=”test”
a.b.c.foo-bar=”test”
 

whereas

 

"foo": {
            "match": "foo*",
            "mapping": {
              "type": "string",
              "copy_to": [
                "{path}.{name}.original","{path}.{name}.bar",
              ]
            }
          }

 

 

 
This would result in the content appearing in
 
a.b.c.foo.original=”test”
a.b.c.foo.bar=”test”
 
 
 
 
 

Does that make sense : )

 

 

 

 

Cheers

 

Rob

**Comment by jpountz** [comment]
The example confuses me a bit: it seems that we are trying to use `copy_to` for a `fields` use-case?

**Comment by rob-tice** [comment]
Not sure how fields would help in my example as described. Maybe it is a new feature in v 2 but it doesn't work in 1.7.3.

e.g.

I wish to be able to say the following:

wherever the field note appears

apply the following template

"note":
		{
			"properties": 
			{
				"type":{"type":"string","index":"not_analyzed","include_in_all" : false},
				"value":{"type":"string","index":"analyzed","analyzer":"standard"},
"value":{"type":"string","index":"analyzed","analyzer":"standard"},

			}
		},

**Comment by pk-picturepark** [comment]
+1 

It would be nice to use a {path} variable within copy_to just to avoid the necessity to provide full field paths. 

It would even be nicer to configure a relative path. See sample below. So in order to copy the values from Person.Name to Person.Names I won't have to provide the full path *Person.Names* in the copy_to field, but can use a relative syntax, e.g */Names*.

`PUT /my_index
{
  "mappings": {
    "my_type": {
      "properties": {
        "Person": {
			"properties": {
				"Name": {
				  "type": "string",
				**  "copy_to": "/Names" **
				},
				"Names": {
				  "type": "string"
				}
			  }
			}
		  }
		}
	}
}`

**Comment by jpountz** [comment]
We discussed it in FixitFriday. While we understand how it could help some use-cases, it also makes it too easy to generate unnecessarily complex mappings, which is something we do not want to encourage. Moreoven, dynamic mappings already have some complexity that we would rather not increase.
