### ISSUE TITLE
Lookup concrete indices and alias information via a single lookup

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#12173]
If a request is accepted by the coordination node we lookup the concrete indices, potential aliases and whether an alias has a filter up via several lookups from the cluster metadata. Also when checking for cluster blocks we do a lookup too.

All this can be done via a single lookup and if we change the transport action api we pass this information too all the places that need it.

Doing this via a single lookup cleans things up (no need for MetaData#filteringAliases(...) and MetaData#resolveSearchRouting(...) methods) but in cases where there are many aliases and indices this can speed things up too.

Follow up issue for #12058

**Comment by javanna** [comment]
I wonder if this is (at least partially) addressed by #40263. @jpountz what do you think?

**Comment by jpountz** [comment]
I was not aware of this issue. I think #40263 addresses the worst-case scenarios performance-wise, but @martijnvg's proposal would make things even better, and probably simpler as well I suspect.
