### ISSUE TITLE
Date parsing (now) bug when filtering in addition to percolation

### ISSUE THREAD

**Issue by zergin** [elastic/elasticsearch#12185]
This seems similar (albeit different) to #12179: there is an issue with "now" and percolator queries: when .percolator documents are filtered in addition to percolation. 

```json
POST /idx/type/_percolate
{
  "doc": {},
  "filter": {
    "range": {
      "$context.created": {
        "lte": "now"
      }
    }
  }
}
```
for .percolator:
```json
{
  "query": {
    "filtered": {
      "query": {
        "match_all": []
      }
    }
  },
  "$context": {
    "name": "test",
    "created": "2015-07-10T14:41:54+0000",
  }
}
```
The response is:

```
BroadcastShardOperationFailedException[[idx][0] ]; 
 nested: PercolateException[failed to percolate];  
 nested: ElasticsearchParseException[failed to parse request]; 
 nested: ElasticsearchParseException[Could not read the current timestamp];
 nested: UnsupportedOperationException;
```

**Comment by martijnvg** [comment]
@zergin Thanks for reporting this. There is a PR open for the missing support of resolving `now` in the percolate api: #12215

**Comment by zergin** [comment]
Splendid, thanks. Any ETA for this going live? I see it's scheduled for 1.6.1?

**Comment by martijnvg** [comment]
when the PR gets reviewed it will get merged and then I'll try to back port
it to 1.7 and 1.6 branches. So it should get into the 1.6.1 release.

On 14 July 2015 at 12:19, zergin <notifications@github.com> wrote:

> Splendid, thanks. Any ETA for this going live? I see it's scheduled for
> 1.6.1?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch/issues/12185#issuecomment-121192591>
> .
>



-- 
Met vriendelijke groet,

Martijn van Groningen

**Comment by martijnvg** [comment]
@zergin The change got backported to 1.6, so it is scheduled for 1.6.1
