### ISSUE TITLE
Timestamp isn't generated with mapping file

### ISSUE THREAD

**Issue by ymartel06** [elastic/elasticsearch#12186]
Hi,

I'm trying to create a timestamp thanks to the mapping.
It seems not working. I will try to explain what I did:

From a fresh ElasticSearch 1.6.0 on Windows, I created a file for the mapping:
*config\mappings\\_default\tweet.json*
```
{
    "tweet" : {
        "_timestamp" : {
            "enabled" : true,
            "path" : "post_date"
        }
    }
}
```
From my understanding, at the first document creation in tweet type, ES will create a timestamp date inside the field post_date.
So let's try to put something in tweet:
```
curl -XPOST http://localhost:9200/foo/tweet?pretty -d '
{
	"Message": "Hello"
}'
```
And the result is:
```
{
  "_index" : "foo",
  "_type" : "tweet",
  "_id" : "AU54jUpV_Q4fyYYVxweD",
  "_version" : 1,
  "created" : true
}
```
On ES, no error:  *[Moonstone] [foo] update_mapping [tweet] (dynamic)*

Let's check the mapping for tweet:
curl -XGET 'http://localhost:9200/foo/_mapping/tweet' 
```
{"foo":{"mappings":{"tweet":{"_timestamp":{"enabled":true,"path":"post_date"},"properties":{"Message":{"type":"string"}}}}}}
```
So it seems the timestamp is enabled for tweet type.

I will GET the first document:
curl -XGET http://localhost:9200/foo/tweet/AU54jUpV_Q4fyYYVxweD?pretty
```
{
  "_index" : "foo",
  "_type" : "tweet",
  "_id" : "AU54jUpV_Q4fyYYVxweD",
  "_version" : 1,
  "found" : true,
  "_source":
{
"Message": "Hello"
}
}
```
So finally, the field 'post_date' isn't generated. Maybe it's my bad and I did something wrong, but I've got no clue what.

Yohann

**Comment by dadoonet** [comment]
`_source` is never modified by elasticsearch. It does not mean that your `_timestamp` does not exist. Just that you don't see it in the source you provided.

But you'd better ask this on discuss.elastic.co.

Closing as I don't think it's an issue.
