### ISSUE TITLE
Term filter parser too lenient

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#12184]
The term filter parser does allow specifying more than one field without barfing and throwing an exception, resulting in a last one wins scenario.

Sample to reproduce

```
GET /foo/bar/_search
{
  "query": {
    "filtered": {
      "query": {
        "match_all": {}
      },
      "filter": {
        "term": {
          "field2": "bar",
          "field1": "foo"
        }
      }
    }
  }
}
```

This should throw an exception, once `field2` has been found and is tried to be overwritten.

**Comment by clintongormley** [comment]
@javanna is this still relevant with the query refactoring branch?

**Comment by javanna** [comment]
yes it is still relevant, it's a fix that could be applied on master independently
