### ISSUE TITLE
error to start elasticsearch as a service with elasticsearch-servicewapper

### ISSUE THREAD

**Issue by JasonBian** [elastic/elasticsearch#12191]
mac os 10.10.1
➜  ~  java -version
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

error information:
STATUS | wrapper  | 2015/07/11 14:10:52 | Launching a JVM...
ERROR  | wrapper  | 2015/07/11 14:10:52 | JVM exited while loading the application.
INFO   | jvm 1    | 2015/07/11 14:10:52 | Error: This Java instance does not support a 32-bit JVM.
INFO   | jvm 1    | 2015/07/11 14:10:52 | Please install the desired version.

**Comment by dadoonet** [comment]
Please use the mailing list on discuss.elastic.co

The service wrapper is deprecated and not maintained, many of the features have been added to Elastisearch itself, and purpose built deb, rpm packages, as well as windows service, are avaialble.
