### ISSUE TITLE
Can some let know about the use of ~ & ^ in below syntax

### ISSUE THREAD

**Issue by vaniaravinda** [elastic/elasticsearch#12198]
TITLE:"same old song and dance"^100 
 OR (
 TITLE:same~0.8 AND TITLE:old~0.8 AND TITLE:song~0.8 AND TITLE:and~0.8 AND TITLE:dance~0.8
 )^50 

Please explain about ^ & ~ in above query.

**Comment by dadoonet** [comment]
Please ask your questions on discuss.elastic.co.

We can help there.

**Comment by clintongormley** [comment]
And see the docs here: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax
