### ISSUE TITLE
Serial Diff aggregator problem

### ISSUE THREAD

**Issue by olivere** [elastic/elasticsearch#12197]
Hello!

I've been experimenting with the new [`serial_diff`](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-pipeline-serialdiff-aggregation.html) aggregator in master branch and get an error. Is this an error, or am I doing it wrong?

```sh
#!/bin/sh
curl -s -XPUT 'localhost:9200/test-es20' -d '{
  "mappings": {
    "order": {
      "properties": {
        "article": { "type": "string" },
        "price": { "type": "float" },
				"time": { "type":"date", "format": "YYYY-MM-dd" }
      }
    }
  }
}'

# Add some documents
curl -s -XPUT 'localhost:9200/test-es20/order/1' -d '{"article":"MacBook","price":1200,"time":"2015-01-02"}'
curl -s -XPUT 'localhost:9200/test-es20/order/2' -d '{"article":"Dell XPS","price":1600,"time":"2015-01-08"}'
curl -s -XPUT 'localhost:9200/test-es20/order/3' -d '{"article":"iPad","price":600,"time":"2015-02-01"}'

# Serial diff
curl -s -XGET 'localhost:9200/test-es20/_search?pretty' -d '{
  "aggregations": {
    "sales_per_month": {
      "aggregations": {
        "sales": {
          "sum": {
            "field": "price"
          }
        },
        "the_diff": {
          "serial_diff": {
            "buckets_path": "sales",
            "lag": 1
          }
        }
      },
      "date_histogram": {
        "field": "time",
        "interval": "month"
      }
    }
  },
  "query": {
    "match_all": {}
  }
}'
```

Result:

```json
{
  "error" : {
    "root_cause" : [ {
      "type" : "search_parse_exception",
      "reason" : "Could not find aggregator type [serial_diff] in [the_diff]",
      "line" : 11,
      "col" : 11
    } ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [ {
      "shard" : 0,
      "index" : "test-es20",
      "node" : "SvAbVOMMSp23QbSCyHFGQA",
      "reason" : {
        "type" : "search_parse_exception",
        "reason" : "Could not find aggregator type [serial_diff] in [the_diff]",
        "line" : 11,
        "col" : 11
      }
    } ]
  },
  "status" : 400
}
```

**Comment by colings86** [comment]
Your script works for me on the latest master. Is it possible you weren't on the latest master when you tried this? The `serial_diff` aggregation was only merged to master 2-3 days ago.

**Comment by olivere** [comment]
@colings86 Ha! Works fine now. I was inspecting the Java source for my Go client and `SerialDiffBuilder` was already there, so I thought that it might not be glued together appropriately. ;-)  Thanks!

**Comment by colings86** [comment]
@olivere no worries. By the way, I really like your issue descriptions, putting a reproduction script in all your issues is super helpful. Thanks.

**Comment by olivere** [comment]
@colings86 You guys should really have something like `play.elastic.co` (like http://play.golang.org/). It would make sharing scripts even easier :-)

**Comment by colings86** [comment]
@olivere you can use https://found.no/play to create these kinds of scripts, there is an export feature that will produce a shell script for you to be able to run. The Found team are looking to keep developing this to add features.

There is also the Sense tool in Marvel which lets you create scripts of commands in a easily readable format.

**Comment by olivere** [comment]
@colings86 Oh, didn't know about https://found.no/play. Exactly what I had in mind. Thank you!
