### ISSUE TITLE
Elasticsearch (2.0 master) not starting after os restart.

### ISSUE THREAD

**Issue by msathis** [elastic/elasticsearch#12196]
OS: Mac os 10.10.4
Java: 1.7.0_07-b10

It was running fine till the os restart. After that this log is thrown whenever i try to start elasticsearch.

```
{2.0.0-SNAPSHOT}: Initialization Failed ...
- IncompatibleClassChangeError[Found class org.elasticsearch.common.settings.Settings, but interface was expected]
Exception in thread "main" java.lang.SecurityException: exit(3) not allowed by system policy
	at org.elasticsearch.bootstrap.Security$1.checkExit(Security.java:67)
	at java.lang.Runtime.exit(Runtime.java:105)
	at java.lang.System.exit(System.java:960)
	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:304)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:28)
```

**Comment by clintongormley** [comment]
Sounds like you need to do a mvn clean before rebuilding.

**Comment by msathis** [comment]
@clintongormley I copied the master snapshot zip to different location and was running from there. Not directly from checkout code. The only suspicious thing was, while elasticsearch was running, the os crashed and rebooted. After that i couldn't start elasticsearch at all. I will try reproducing and post you the zip if i am able to.

**Comment by clintongormley** [comment]
It sounds like you have different versions in the classpath.

**Comment by s1monw** [comment]
do you have a plugin installed that is outdated? can you list the content of your plugins directory?

**Comment by msathis** [comment]
@s1monw I had marvel installed at that point of time. No other plugins.

**Comment by clintongormley** [comment]
marvel is not master compatible

**Comment by s1monw** [comment]
@msathis I guess that's the reason did you get a marvel snapshot build somehow for this? can you remove marvel and try again

**Comment by msathis** [comment]
@s1monw Yep. That is the issue. After removing marvel it works fine. Sorry for wasting your time. Please close the issue. :(
