### ISSUE TITLE
1.6.0's init scripts don't kill some older versions of Elasticsearch

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#12206]
Elasticsearch 1.6.0's init scripts don't shut down Elasticsearch 1.3.x and that caused me trouble.

I'm posting this here more for posterity than anything. Feel free to close if its not in scope.

My usual (pre 1.6.0) upgrade procedure for Elasticsearch is:
0. Install new plugin versions on all nodes
1. Install new version
2. Shut down allocation
3. Shut down Elasticsearch
4. Start Elasticsearch
5. Wait for Elasticsearch to reply to _cat/health
6. Reenable allocation
7. Wait a minute
8. Wait for the cluster to go green
9. Repeat 1-8 per node

We have steps 2-8 scripted. But since the init script doesn't shut down Elasticsearch 1.3.x we can't use the script. Sadness.

**Comment by spinscale** [comment]
Hey nik,

I assume, that you did not stop Elasticsearch, install the .deb, start Elasticsearch, but replaced the debian package first?

**Comment by nik9000** [comment]
> I assume, that you did not stop Elasticsearch, install the .deb, start Elasticsearch, but replaced the debian package first?

Yes. If you stop before you replace it works like it ought to.

**Comment by nik9000** [comment]
Getting irrelevant -closing.
