### ISSUE TITLE
Performance Issue when using ~ operator with Query String Query - ES 1.6

### ISSUE THREAD

**Issue by effoeffi** [elastic/elasticsearch#12201]
Hello,

When running a query like:
```json
POST /my-index/_search
{
  "from" : 0,
  "size" : 5,
  "query" : {
      "query_string" : {
      "fields" : ["field1","field2",...,"fieldn"],
      "query" : "flight~",
      "use_dis_max" : true
    }
  },
  "highlight" : {
    "pre_tags" : [ "<span class=\"mark\">" ],
    "post_tags" : [ "</span>" ],
    "order" : "score",
    "encoder" : "html",
    "require_field_match" : true,
    "fields" : {    
      "*" : {}
    }
  }
}
```
query_string contains n fields (in my case about 40 fields), and query contains ~ operator (in the example flight~), takes about 6 seconds.
If I run the same query (flight~), but remove the fields section from query_string section, it takes 10 milliseconds (no time).

Why does it happen?
Is there a solution for this performance penalty (I have to determine specific fields into *query_string* in order to solve highlight issue, see below)?

**Background:**
Using elasticsearch 1.6.
Run it on index that contains 1000 documents.
Determine specific fields into *query_string* in order to solve follow highlight issue:
https://discuss.elastic.co/t/highlight-when-query-contains-fields-and-text-es-1-6-0/24311/5

Thanks,
Effi

**Comment by colings86** [comment]
Please keep questions on the discuss forum, you already have a post for this question on there (https://discuss.elastic.co/t/query-string-query-performance-issue-when-using-operator-es-1-6/25126), the Github issues list is used for bug tracking only. Also on your post on discuss you indicated that your issue was solved
