### ISSUE TITLE
Debian init script should create pid directory on startup

### ISSUE THREAD

**Issue by Crote** [elastic/elasticsearch#12225]
Elasticsearch 1.6.0 creates a pidfile in /var/run/elasticsearch/, but does not make sure that this directory exists. On Ubuntu 14.04, and probably quite a few other OSes, the /var/run/ directory is re-created every boot, which causes elasticsearch to fail to start with `touch: cannot touch ‘/var/run/elasticsearch/elasticsearch.pid’: No such file or directory`.

This can probably be fixed by adding `$PID_DIR` to [this](https://github.com/elastic/elasticsearch/blob/master/core/src/packaging/deb/init.d/elasticsearch#L153) line.

**Comment by tlrx** [comment]
@Crote thanks for reporting.

This issue has been reported in #11594 and fixed in #11674, so I close this one. Feel free to reopen if needed.
