### ISSUE TITLE
How processes 'C|D' in elasticsearch?

### ISSUE THREAD

**Issue by mlc0202** [elastic/elasticsearch#12226]
I meet special requirements when I migrate elasticsearch into project,there is the SQL statement in my business that looks like "A='XX' and B='XX' and (C|D) ",for example,it will be "A='1' and B='2' and (0000032768|000000001)",when "C|D" is 1,it represents true ,otherwise ,it will be false,so,how to deal it in elasticsearch?
I am very grateful!

**Comment by colings86** [comment]
As stated in https://github.com/elastic/elasticsearch/issues/12140 please ask questions on discuss.elastic.co. We can help there.
