### ISSUE TITLE
Ambiguous docs for completion suggester "transpositions"

### ISSUE THREAD

**Issue by ankr** [elastic/elasticsearch#12228]
The docs says

> **transpositions** *Sets if transpositions should be counted as one or two changes, defaults to true*

It's not really clear whether or not setting it to `true` will make transpositions be counted as one or two changes.

Ref:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html & 
https://github.com/elastic/elasticsearch/blob/master/docs/reference/search/suggesters/completion-suggest.asciidoc

**Comment by clintongormley** [comment]
thanks @ankr 

@areek could you clarify in the docs please?
