### ISSUE TITLE
Add old script API use to the deprecations logging

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#12231]
We should add logs to the deprecations logging when users use the old script API syntax. The tricky bit here is not overloading the logs since a user could bulk ingest thousands of update requests per second and fill the deprecations log files very quickly, not only making the log files very hard to digest but also possibly quickly filling the disk

**Comment by clintongormley** [comment]
Given that we've moved to the new format a few versions ago, I'm going to close
