### ISSUE TITLE
Should 'from' parameter be changed from 'int' to 'long'?

### ISSUE THREAD

**Issue by aleph-zero** [elastic/elasticsearch#12245]
For paginating results we have a 'from' and 'size' parameter in SearchRequestBuilder. These are both 'int' fields. However, the total hits returned from a search, e.g. SearchHits.totalHits() is defined as a 'long'. 

Maybe I'm missing something, but it seems that it should be impossible to paginate an entire result set if the total hits is greater than Integer.MAX_VALUE. Those hits in the range (Integer.MAX_VALUE, Long.MAX_VALUE) would not be addressable.

**Comment by clintongormley** [comment]
Your system will die long before you get to the "long" range.  Either use scrolling for deep retrieval, or use a filter to exclude previously shown results.  Deep pagination using from/size is a bad idea.
