### ISSUE TITLE
allow inner_hits to work on `array type` properties of document

### ISSUE THREAD

**Issue by g00fy-** [elastic/elasticsearch#12246]
It would be awesome if `inner_hits` could also apply to properties of a document that are not `nested type` but simple `array type`. Currently in order to achieve similar thing a document attribute has to be "nested_type".

Currently following mapping won't work

```json
{
      "mappings": {
         "products": {
            "properties": {
               "keywords": {
                  "type": "string"
               },
               "name": {
                  "type": "string"
               }
            }
         }
      }
   }
```
for document of format

```json
{
  "name":"Samsung 42\" LED 4200UHD",
  "keywords":["tv","led","samsing"]
}
```

currently the only trick to get matching keywords is to transform the document into format that would artificially create nested type

```json
{
  "name":"Samsung 42\" LED 4200UHD",
  "keywords":[{"keyword":"tv"},{"keyword":"led"},{"keyword:":"Samsung"}]
}
```

**Comment by clintongormley** [comment]
Hi @g00fy- 

These work in a completely different way from nested documents.  To figure out which keywords matched, either use highlighting, or use a term query for each keyword and specify a `_name` for each term query.
