### ISSUE TITLE
Service.bat Windows Java version detection improvements

### ISSUE THREAD

**Issue by smflorentino** [elastic/elasticsearch#12256]
I have a PowerShell script to deploy Elasticsearch via PowerShell, I'm registering the service using service.bat during a PowerShell session. This is on a machine with 64GB of RAM. It was always defaulting to a 32 bit service, although no 32-bit service was installed on the machine. I traced the problem to be the fact that the default Java heap size with my JVM is 2GB. Here's the problem. The default memory limit for a PowerShell session is 1GB - so the JVM can't even start. But the service.bat file defaults to detecting a 32 bit JVM when in fact none exists. I'd like to add preferably two things - (1) a check to see that the JVM was able to initialize for the version check and (2) a reasonable heap maximum size for the check (-Xmx 2M) to avoid this type of problem.

I know this is probably a real specific problem, but what thoughts do you guys have? I have made changes locally and the script works perfectly now, and am more than willing to submit a PR.

**Comment by clintongormley** [comment]
Hi @smflorentino 

Probably the easiest way to move forward is for you to submit the PR?  Easier to follow what's going on when we can see the code changes.

thanks

**Comment by smflorentino** [comment]
I've just attached the PR. I can repro this on machines with large amounts of RAM, when service.bat is called within PowerShell.

**Comment by smflorentino** [comment]
PR #12274 merged to master.
