### ISSUE TITLE
Test Failures

### ISSUE THREAD

**Issue by 4ydx** [elastic/elasticsearch#12250]
In branch 1.6 running the following in ubuntu 14.04 (running on parallels desktop):

ES_TEST_LOCAL=true
mvn clean test

I am seeing errors like:

    1> REPRODUCE WITH  : mvn clean test -Dtests.seed=FC2ED73E5703D99E -Dtests.class=org.elasticsearch.cluster.MinimumMasterNodesTests -Dtests.method="multipleNodesShutdownNonMasterNodes" -Des.logger.level=INFO -Dtests.heap.size=512m -Dtests.locale=sv_SE -Dtests.timezone=US/Alaska -Dtests.processors=2
    1> Throwable:
    1> org.elasticsearch.discovery.MasterNotDiscoveredException: waited for [30s]
    1>     org.elasticsearch.action.support.master.TransportMasterNodeOperationAction$4.onTimeout(TransportMasterNodeOperationAction.java:164)
    1>     org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:231)
    1>     org.elasticsearch.cluster.service.InternalClusterService$NotifyTimeout.run(InternalClusterService.java:560)
    1>     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    1>     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    1>     java.lang.Thread.run(Thread.java:745)

I am wondering if this is expected or if I should be doing something differently when testing?

**Comment by jpountz** [comment]
Closing as there have been lots of changes since then, but if you have such issues again can you please open a ticket with the name of the test that failed as the title? Thanks.
