### ISSUE TITLE
index migration problem from elasticsearch1.5.2 to elasticsearch1.6.0

### ISSUE THREAD

**Issue by JoshuaZe** [elastic/elasticsearch#12259]
we have already generated many large index using elasticsearch1.5.2.
To use some new features (e.g. JSON response body filtering), we have to migrate to elasticsearch1.6.0. Are the index compatible in version 1.6.0 ?
Thanks

**Comment by s1monw** [comment]
please use the discuss forum for these kind of questions https://discuss.elastic.co/  in the future. The answer is YES it's compatible you can do a rolling restart.

**Comment by JoshuaZe** [comment]
Thank you very much.
