### ISSUE TITLE
_default_ mapping not created in most randomizedtesting cases

### ISSUE THREAD

**Issue by mikerott** [elastic/elasticsearch#12253]
I have a class that extends `ElasticsearchIntegrationTest` as part of our test infrastructure.  I've overridden `nodeSettings` and `indexSettings` methods in order to take back some control from the `RandomizedTest` class up the class hierarchy.  This worked well when we ran against ES 1.1.1.  Now, against 1.5.2, I'm hitting a blocker.  First, I had to explicitly add `plugin.types` to the `Settings` returned from `nodeSettings`, but that problem was only 30 minutes to find!  The blocker for me is that ES won't create the `_default_` mapping in roughly 90% of the times I run my unit test.

At this point, I've found which `@Seed` consistently passes, and which consistently fails, so it's clearly some randomization that's causing it.  Problem is, I don't know how to find which setting is causing the difference in behavior.  If I could only see what values the randomizer picked under each seed, I surely could spot the difference.

How can I make `RandomizedTest` be more verbose?  I can pause my test in a debugger and go poke around on port 9200, or use the Java API.  Anything will do.  In which case(s) will ES *not* create the `_default_` mapping?

I have a full (easy) re-create scenario for this that I can upload somewhere.

**Comment by bleskes** [comment]
I'm not sure exactly what you mean, but the testing infra will indeed randomly add a _default_ mapping. See https://github.com/elastic/elasticsearch/blob/master/core/src/test/java/org/elasticsearch/test/ElasticsearchIntegrationTest.java#L369 for the decision and  https://github.com/elastic/elasticsearch/blob/master/core/src/test/java/org/elasticsearch/test/ElasticsearchIntegrationTest.java#L450 for logging of it. 

the randomDynamicTemplates parameter to the ClusterScope annotation allows you to turn off the random behavior , giving you the option to add what ever template/default mapping you want.

Does this answer you question?

Out of curiosity  - what does it matter to you if the `_default_` mapping is added?

**Comment by mikerott** [comment]
That parameter does (mostly) answer my question.  I was also curious about how to print out the decisions RandomizedTest makes, but I can find that some other time.

As for the parameter, yes that helps!  I guess I missed all the params for ClusterScope annotation.

As for why it matters, it's actually not such a big deal, except that we want strict control over the mappings that are created into ES, and in 1.1.1 everything was perfectly deterministic.  In 1.5.2, it *appeared* initially like some undeterministic behavior.  Of course, it ultimately just came down to the (intentional) randomized behavior of the tests.

I think all is well now.  Thank you for the help!
