### ISSUE TITLE
ElasticSearch memory leaks

### ISSUE THREAD

**Issue by dennisgorelik** [elastic/elasticsearch#12255]
We have that pattern (below) long enough that guessing memory leaks in ElasticSearch seem to be the most likely explanation.
Summary: after running our ElasticSearch for about 5 days we start to get ~exponentially more timeouts with every passing day.
These timeouts go away after restarting ElasticSearch service... for another 5 days.

Details:
1) We saw that pattern in both Windows (Windows Server 2012 R2) and Linux (CentOs 7) environments.
We currently use ElasticSearch 1.6.0, but we observed similar "~5-days timebomb" pattern on previous versions such as ElasticSearch 1.4.3 on Windows).
2) We run about 200,000 ElasticSearch queries per day
3) We have timeouts at 100s mark.
4) Normally failing queries should execute in well below 1s (e.g. ~50ms).
5) Timeouts we are getting usually do not show on slowlog:
https://github.com/elastic/elasticsearch/issues/11919

**Comment by clintongormley** [comment]
@dennisgorelik please don't open another issue for this.  Continue the discussion in the previous issue.

**Comment by dennisgorelik** [comment]
These are two separate issues.
"Memory leaks" and "Timeouts missing in slowlog" may have the same or different underlying causes.

**Comment by clintongormley** [comment]
I think they are more than likely related, and i very much doubt there are memory leaks.  Let's continue on the other issue.
