### ISSUE TITLE
Spurious type created when initialising other types while using index template

### ISSUE THREAD

**Issue by MrHash** [elastic/elasticsearch#12265]
Two types are created when using index templates and one document is inserted:
```
curl -XPUT 'localhost:9200/_template/first-template' -d '
{
    "template": "myindex",
    "mappings": {
        "wtfirst": {
            "properties": {
                "name": { "type": "string" }
            }
        }
    }
}
'
curl -XPUT 'localhost:9200/myindex/first-type/first' -d '
{
    "name": "first"
}
'
```
This creates a `myindex` index and `first-type` type with a single document, but a `wtfirst` type is also created in the index. This unexpected type also has a dynamically derived explicit(?) mapping which is also unexpected.

If you add a more templates and documents in the same manner (using `wtsecond` and `second-type` etc.), the same thing continues to happen. However if you add a third or more in the same manner and `index.mapper.dynamic` is `false`, then a `TypeMissingException` is thrown on the third document creation.

The effect on mappings for types becomes unclear when later adding documents for the pre-created/not-created types. This problem appears on tested versions 1.4.0, 1.5.1 and 1.6.0.

**Comment by clintongormley** [comment]
> This creates a myindex index and first-type type with a single document, but a wtfirst type is also created in the index. This unexpected type also has a dynamically derived explicit(?) mapping which is also unexpected.

This isn't unexpected at all.  Elasticsearch is doing exactly what you told it to do: "when you see an index called `myindex`, create it with the following mapping"

> index.mapper.dynamic is false

This setting turns off dynamic mappings, so you have to add mappings manually, hence the TypeMissingException.

I think you've misunderstood how dynamic mapping works.  I suggest asking about what you're trying to achieve in the forums: https://discuss.elastic.co
