### ISSUE TITLE
QueryString ignores maxDeterminizedStates when creating a WildcardQuery

### ISSUE THREAD

**Issue by nomoa** [elastic/elasticsearch#12266]
This is a bug that has been fixed in lucene (https://issues.apache.org/jira/browse/LUCENE-6677) recently.
I don't know if it will be backported to lucene 4.10.x and thus have chance to get into elasticsearch 1.6.x.
Note that this fix could be backported in MapperQueryParser by overriding the newWildcardQuery method.

**Comment by clintongormley** [comment]
@nomoa This fix won't make it into 1.6.1 or 1.7.0 - too short notice.  I think it'll have to wait for 2.0

**Comment by clintongormley** [comment]
Will be fixed by the upgrade to Lucene 5.3

**Comment by clintongormley** [comment]
hah - just seen your PR and that mike's on it - you're in luck :)

**Comment by nomoa** [comment]
Yes, I guess it's my lucky day :)
This will be of great help to us to protect a cluster that was killed by a nasty wildcard query.

**Comment by mikemccand** [comment]
I merged to 1.6.2, 1.7.1, 2.0.  Thank you for fixing in both Lucene (5.3) and ES @nomoa!
