### ISSUE TITLE
Projection and De-normalization of nested relationships

### ISSUE THREAD

**Issue by roytmana** [elastic/elasticsearch#12275]
I find that it is quite often that we need to de-normalize (produce a cartesian join) on nested data and apply filter on the resulting data set (on both to parent and nested fields). We also need to support a case of multiple unrelated nested fields being de-normalized. It would need to go together with projections API because we would only want to include necessary parts of data avoiding repetition of complete parent or other nested (in case of multiple independent nested fields) data.

One of the main use cases is export of subsets of data by end users from our systems for further analysis and reporting. We have an engine that provides basic de-normalization and projection functionality but filtering of nested data is really challenging as we would have to replicate elastic filtering logic for that. So I was wondering if elastic team would find it to be a potentially interesting feature.

As an aspect of projection functionality (apart from denormalization) it would be nice to be able to apply nested filters to returned sources nested elements collection. That would go long way towards achieving complete goal as denormalization could be still done on client as long as filtering of nested collections in source is done in elastic

**Comment by clintongormley** [comment]
I'm sorry @roytmana but I don't have a clue what you're talking about from this issue description.  It is way too abstract.  Actual JSON examples would go a long way to making this comprehensible.

I think what you're describing may already be handled by the inner-hits functionality (https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html) possible combined with response filtering (https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#_response_filtering)

**Comment by roytmana** [comment]
What I am describing is essentially SQL like joins between parent table and its nested collections allowing joining of the parent with one or multiple nested fields at once. 
Multiple nested fields joining will produce all permutations of members of the nested fields. Think of nested fields as SQL tables implicetly connected on their parent object(s) and how SQL will return result

You can call it SQL Over Elastic but just "selection" and "joining" part without SQL query support

Say we have meeting between Customers and Staff

```json
{
  "meetingId": 123,
  "meetingDate": "2015-07-03",
  "customers": [
    {
      "id": 10,
      "name": "John Doe"
    },
    {
      "id": 20,
      "name": "Jane Smith"
    }
  ],
  "staff": [
    {
      "id": 10,
      "name": "Joe Brown"
    },
    {
      "id": 20,
      "name": "Kate Davis"
    }
  ]
}
```

Say I want return metting info and customer info in denormolazed manner to feed to my reporting or any orger tool that is geared towards relational data:
Here is the result

```json
[
  {
    "meetingId": 10,
    "meetingDate": "2015-07-03",
    "customers.id": 10,
    "customers.name": "John Doe"
  },
  {
    "meetingId": 10,
    "meetingDate": "2015-07-03",
    "customers.id": 20,
    "customers.name": "Jane Smith"
  }
]
```

"select statement" of the query will identify which parts to include and which nested collections to denormalize

if I want to return all my meeting data in denormalized form it'll be :

```json
[
  {
    "meetingId": 10,
    "meetingDate": "2015-07-03",
    "customers.id": 10,
    "customers.name": "John Doe",
    "staff.id": 10,
    "staff.name": "Joe Brown"
  },
  {
    "meetingId": 10,
    "meetingDate": "2015-07-03",
    "customers.id": 20,
    "customers.name": "Jane Smith",
    "staff.id": 10,
    "staff.name": "Joe Brown"
  },
  {
    "meetingId": 10,
    "meetingDate": "2015-07-03",
    "customers.id": 10,
    "customers.name": "John Doe",
    "staff.id": 20,
    "staff.name": "Kate Davis"
  },
  {
    "meetingId": 10,
    "meetingDate": "2015-07-03",
    "customers.id": 20,
    "customers.name": "Jane Smith",
    "staff.id": 20,
    "staff.name": "Kate Davis"
  }
]
```

**Comment by clintongormley** [comment]
OK - that's clearer, and that looks like something which is quite use case specific and can be done easily on the client side (using `inner_hits` to do the join filtering on the Elasticsearch side).

thanks for the idea @roytmana, but I don't think we should build a new API specifically for this.

**Comment by roytmana** [comment]
What about denormalization @clintongormley?
that could be rather useful for integration with millions of reporting, statistical, productivity and other packages built to work with relational databases. As it is there are very few, if any end user products capable reading elastic data.if elastic were capable of providing tabular data practically any product could read it

**Comment by kimchy** [comment]
there are 2 aspects here. Denormalize the JSON response to *another* json response that is denormalized for nested docs. I don't think ES should do it, as it is very use case dependent and the client app can easily denormalize the response using it's own logic.

There is another aspect of returning responses in a "tabular" format, that applies both for aggregations and nested docs within hits. This is an interesting question and requires thinking about how best to answer that, but we should definitely not implement like how it is purposed here, since it is somewhere "in the middle" and will cause too much confusion.

**Comment by roytmana** [comment]
@kimchy, while denormalizatuon itself can be done generically on an arbitrary json the combination of arbitrary query fultering and denormalizatuon is lot more complex on client side. also what's the usfulness of tabulating if you do not denormalize 1-N relations?  Flattening 1-1 nested json witin each collection is a trivial op.

Btw building an entirely generic data mart like solution on top of elastic made me wish nesting and filtering in aggs were smarter and did not have to introduce all this extra nodes in the outpit tree. I have quite a framework to automatically nest aggs when using nested aggs or filters and then un nest results to prrsent logical grouping to consumer apps entirely automatically. It should not be so labor intensive. Another thing is ability to flatten aggs results capturing bucket keys and metrics as you recurse the result tree

**Comment by kimchy** [comment]
but you are talking here about solving a point solution of flattening hits documents with nested elements in them, this is a point based "solution", it will complicate things without really solving anything

**Comment by roytmana** [comment]
I do not dispute it. It is really your call. I feel it is pretty generic and provides interface for millions of products that were developed with relational data in mind. I think it is huge for opening elastic to wider ad hoc and end user use.

**Comment by kimchy** [comment]
@roytmana I am 100% with you, I just think that if we want to provide this "tabular" format of response, we need to think about it in a broader context then just hits, or just aggregations. It is trickier, but I think it is the right way forward as it will incur less point solutions...

**Comment by roytmana** [comment]
That would be great! That and a smarter aggs that are not so assembly language like :-)
they could understand nesting relatuonships for a start :-)

**Comment by clintongormley** [comment]
@roytmana if you can think of a way to improve the API, please do suggest it (with JSON examples)
