### ISSUE TITLE
Elasticsearch, Logstash and AWS

### ISSUE THREAD

**Issue by AGirin** [elastic/elasticsearch#12276]
We are having interesting issues with ES, Logstash on AWS. 

When we stop Logstash instances and they disconnect from ES, ES cluster goes into a weird state where it reports that it is healthy but HEAD or Bigdesk plugins cannot connect to it. We are getting a lot of this messages in the logs:

[2015-07-15 15:01:04,010][DEBUG][action.admin.cluster.node.info] [NODE001] failed to execute on node [r9kifgqTQN2bufj3JMGRSA]
org.elasticsearch.transport.NodeDisconnectedException: [logstash-NODE012-1377-4420][inet[/xxx.xxx.xxx.xxx:9306]][cluster/nodes/info/n] disconnected
[2015-07-15 15:01:04,014][DEBUG][action.admin.cluster.node.info] [NODE001] failed to execute on node [r9kifgqTQN2bufj3JMGRSA]
org.elasticsearch.transport.NodeDisconnectedException: [logstash-NODE012-1377-4420][inet[/xxx.xxx.xxx.xxx:9306]][cluster/nodes/info/n] disconnected
[2015-07-15 15:01:04,014][DEBUG][action.admin.cluster.node.stats] [NODE001] failed to execute on node [r9kifgqTQN2bufj3JMGRSA]
org.elasticsearch.transport.NodeDisconnectedException: [logstash-NODE012-1377-4420][inet[/xxx.xxx.xxx.xxx:9306]][cluster/nodes/stats/n] disconnected
[2015-07-15 15:01:04,013][DEBUG][action.admin.cluster.node.info] [NODE001] failed to execute on node [r9kifgqTQN2bufj3JMGRSA]
org.elasticsearch.transport.NodeDisconnectedException: [logstash-NODE012-1377-4420][inet[/xxx.xxx.xxx.xxx:9306]][cluster/nodes/info/n] disconnected

Kibana also stops working since it cannot connect to Elasticsearch cluster. 

It takes about 10 minutes for everything to go back to normal without any intervention on our part. Does anybody have any ideas why would this be happening?

Thanks!

Andrew

**Comment by AGirin** [comment]
This actually happens in our own environment - not in AWS - as well. Shutdown Logstash node and Elasticsearch goes into strange state. Comes back after 10 min. 

ES version is 1.2.2

**Comment by clintongormley** [comment]
Hi @AGirin 

1.2.2 is very old now, and numerous connection bugs have been fixed.  Please upgrade and reopen this ticket if you see the same thing in a recent version.  

thanks

**Comment by AGirin** [comment]
Same happens with ES 1.7. Nothing really changed.
