### ISSUE TITLE
Searching in associated models using elasticsearch query dsl

### ISSUE THREAD

**Issue by pushkargarg** [elastic/elasticsearch#12287]
After indexing some child records using 'include' inside as_indexed_json method in the user model, what is the correct way to refer the fields of the child record. If a user has_many phone_numbers with number as a field, I am using the following query but it returns a syntax error on phone_numbers.number. Is there any known way of referring to the number field?
response = User.search query: {
        filtered: {
            filter: {
                bool: {
                    must:[
                        {term: {phone_numbers.number: "123-456-7890"}}
                    ]
                }
            }
        }
    }

**Comment by clintongormley** [comment]
Hi @pushkargarg 

Please ask questions like these on the forum instead: http://discuss.elastic.co/

the issues list is for bug reports and feature requests

thanks
