### ISSUE TITLE
Scheduled backups / Method for doing typical backup rotation weekly full, daily incremental, remove backups after a few months.

### ISSUE THREAD

**Issue by jwojcik** [elastic/elasticsearch#12297]
As an operations engineer, I want to be able to set up backups for my elasticsearch cluster and have them just work without causing any long term problems or huge bills from AWS S3 due to backups retained forever.

Is it a good practice to just do the initial full backup of an index, then do incremental snapshot ad infinitum? 

Is there some downside for doing all of those snapshots? 

If this is a constraint, I imagine one way to handle this is to create another repository every week and do the snapshots into that repository. One can then use S3 object expiry to get rid of old files and somehow use the API to delete the record of the old repository and the snapshots.

Is there anything on the roadmap to do something like that?

**Comment by clintongormley** [comment]
Hi @jwojcik 

Incremental backups just copy over the new segments, so there is no need to do a full backup on a regular basis.

> Is it a good practice to just do the initial full backup of an index, then do incremental snapshot ad infinitum?

Yes

> Is there some downside for doing all of those snapshots?

Only that your storage grows.  But you can just use a cronjob with curator to remove old snapshots.  See https://www.elastic.co/guide/en/elasticsearch/client/curator/current/snapshots-subcommand.html

**Comment by jwojcik** [comment]
Will curator remove the actual files from S3 when it removes the snapshot, or will I need to set an expiry on the s3 bucket to do this?
