### ISSUE TITLE
Item Query (the API)

### ISSUE THREAD

**Issue by alexksikes** [elastic/elasticsearch#12293]
## Introduction

In this issue we will present the API for [Item Query](https://github.com/elastic/elasticsearch/issues/11814). Item Query is a different implementation of More Like This (MLT) which is purely based on the [term vectors API](https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-termvectors.html). It could be described as a more powerful and generalized MLT. Item Query performs similarity search in three distinct steps. First, the user specifies a set of document input(s). Second, the documents are translated into vectors that best describe each of these documents. We call these vectors characteristic vectors, because they are sought to characterize each item. Third, a query is generated from the terms in the characteristic vectors and is executed. So to summarize, Item Query goes from documents (or items) to terms, and from terms to a query. The API gives the user complete control over each of these steps:

``` javascript
{
  "item_query": {
    "items": {
      ... how items are specified ...
    },
    "terms": {
      ... how terms are selected for every item ...
    }
    "query": {
      ... how the query is formed from the terms ...
    }
  }
}
```

We will describe each of these parameters in more detail in the following sections. But first let us mention that only `items`, also shorthanded `item` if there is only one item, is required. All the other parameters use sensible defaults. Following is an example query with some explanations.

``` javascript
{
  "item_query": {
    "items": {
      "item_1": {
        "_index": "index",
        "_type": "type",
        "_id": "1"
      },
      "item_2": {
        "_index": "index",
        "_type": "type",
        "_id": "2",
      }
    },
    "query": {
      "combination": "2*item_1 + item_2",
      "min_should_match": "30%"
    }
  }
}
```

Here the user has specified two items from which he would like to find similar items (or documents). To do so he has specified the `_index`, `_type` and `_id` of each item. He has additionally given them the name item_1 and item_2 respectively. From these items a characteristic vector is generated and combined according the rule "2*item_1 + item_2". We will describe the `combination` rule in more detail. But basically this lets us write any linear combination of the characteristic vectors, so we could model things like: "I like item_1 twice more than item_2", or "I like item_1 but dislike stuff from item_2". From the result of this operation, only the best terms are kept and then used to generate a boolean `OR` query with the given `min_should_match`. This query is then executed and the top matching documents are returned to the user as usual.

We now describe in more detail the `items`, `terms` and `query` parameters.
## The `items` parameter

The `items` parameter can be specified as an array of document inputs, or as an object of named document inputs to be used for combination. We can also use the shorthand notation `item` followed by a single document specification if there is only one item. Each document input correspond to the parameters of the [term vectors API](https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-termvectors.htm). The main parameters are:

| Parameter | Description | Required | Default |
| --- | --- | --- | --- |
| _index | index where to fetch item | if not in context | context |
| _type | type where to fetch or parse item | if not in context | context |
| _id | item id | if no `doc` | none |
| doc | artificial doc | if no `_id` | none |

Something important to mention is that like text queries (`like_text` in MLT) are supported with [artificial documents](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/docs-termvectors.html#docs-termvectors-artificial-doc). Other per item parameters include `fields`, `filter`, `dfs` or `per_field_analyzer` and are used to override the settings in the `terms` parameter if need be.
## The `terms` parameter

The `terms` parameter is optional. It specifies top level parameters as to how to generate the characteristic vectors of each item. It corresponds to the `parameters` of the [multi-term vectors API](https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-multi-termvectors.html). The main parameters are:

| Parameter | Description | Default |
| --- | --- | --- |
| fields | fields to fetch the terms from | * |
| filter | terms filtering parameter | MLT like |
| per_field_analyzer | overrides analyzer at the field | analyzer at the field |
| dfs | whether to use dfs for exact scoring | false |

By default the `filter` parameter selects the best term in a similar fashion to MLT, that is using the same defaults. Under the hood this uses the [terms filtering feature](https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-termvectors.html#_terms_filtering) of the term vectors API.
## The `query` parameter

The `query` parameter is optional. It corresponds to the same [query formation parameters](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-mlt-query.html#_query_formation_parameters) as MLT, with the same defaults.

| Parameter | Description | Default |
| --- | --- | --- |
| minimum_should_match | number of terms that must match | 30% |
| boost_terms | boost each term by score \* boost factor | 0 (deactivated) |
| include | include input documents | false |
| combination | linear combination of the characteristic vectors | sum of the vectors |

All the parameters are straight forward. The `combination` parameter requires more explanation and is probably best described with an example. Something to note though is that, like all the parameters of `query`, this parameter is optional and defaults to simply summing the entries of the resulting characteristic vectors. Let us go through an example to better explain this parameter.

From the previous query, suppose the characteristic vectors for item_1 and item_2 would look like this:

Vector for item_1:

| term_a | term_b | term_c |
| --- | --- | --- |
| 1 | 2.5 | 0.5 |

Vector for item_2:

| term_a | term_c | term_d |
| --- | --- | --- |
| 1 | 3 | 7 |

Under the combination rule "2*item_1 + item_2" this would give us:

| term_a | term_b | term_c | term_d |
| --- | --- | --- | --- |
| 2*1 + 1 = 3 | 2*2.5 = 5 | 2*0.5 + 3 = 4 | 7 |

Which would then subsequently result in the following final characteristic vector being chosen:

| term_b | term_c | term_d |
| --- | --- | --- |
| 5 | 4 | 7 |

We could also have written something like "2*item_1 - item_2" to model dislikes. In this case, the possibly negative entries are just ignored, and therefore will not be part of the final generated query.
## Conclusion

To summarize an item query could be as simple as:

``` javascript
{
  "item_query": {
    "item": {
      "_index": "index",
      "_type": "type",
      "_id": "1"
    }
  }
}
```

Or as complicated as:

``` javascript
{
  "item_query": {
    "items": {
      "item_1": {
        "_index": "index",
        "_type": "type",
        "_id": "1"
      },
      "item_2": {
        "_index": "index",
        "_type": "type",
        "_id": "2"
      },
      "item_3": {
        "_index": "index",
        "_type": "type",
        "doc": {
          "plot": "A human-looking indestructible cyborg is sent from 2029 to 1984 to assassinate a waitress"
        }
      }
    },
    "terms": {
      "fields": [
        "plot",
        "title"
      ],
      "filter": {
        "max_num_terms": 100,
        "min_doc_freq": 1
      }
    },
    "query": {
      "combination": "item_1 + item_2 - 3*item_3",
      "min_should_match": "30%"
    }
  }
}
```

The API gives complete control over each step from item specification to query generation. It is as simple to use as MLT, while at the same time powerful enough to perform sophisticated nearest neighbor type of searches.

**Comment by jpountz** [comment]
This looks easier to understand to me than MLT for multiple documents. However I think there are too many parameters here. I know we have them on MLT as well but I'm concerned we are investing time and energy in supporting these parameters while few people are using them. I would rather keep as few parameters as possible and invest time into making it work better out of the box?

**Comment by alexksikes** [comment]
Thanks for the quick feedback. 

The `items` and `terms` parameters are nothing more than the same parameters as the mTVs API. So in terms of support we are re-using these parsers and then simply making a call to the mTVs API. The only new code to be written is for the `query` parameter, but then it seems fairly straight forward to write the code to select the best terms from the characteristic vectors and generate a boolean OR query from these terms. The `combination` sub-parameter might be a little more tricky though, but we might not need to support this at first. 

If you think there are two many options, which can confuse the user, it is also possible to restrict them and keep it simple. But under the hood, it is term vectors code with terms filtering.

**Comment by rjernst** [comment]
Can we call it "documents" query instead of "items"? We index documents, documents are what the items query refers to (with _id and such) and we don't use the terminology "items" anywhere I know of? Since we are aiming for simplicity, I don't think we should reuse terminology from MLT where it doesn't make sense.

**Comment by mikemccand** [comment]
This looks like a nice generalization of MLT!  I agree "documents" seems better since it's a known name users all understand already.

Can you give some example real-world use cases?  I know you have a cool screen shot somewhere showing how to find similar movies :)

**Comment by alexksikes** [comment]
@mikemccand Thanks for the feedback.

There is a good reason why this is called item query instead of document query, but I still need to write the proposal on Features. Right now it is best to think of this as a generalized MLT, just more powerful and easier to understand.

Concerning the screen shot, I think that was for the [intensity highlighter](https://github.com/elastic/elasticsearch/issues/12326) which I think would be much needed in the context of MLT or Item Query.

**Comment by rjernst** [comment]
> There is a good reason why this is called item query as opposed to document query, but I still need to write the proposal on Features. Right now it is best to think of this as a generalized MLT, just more powerful and easier to understand.

Can you explain the reasoning for item query without referencing MLT? The point I was making is we shouldn't be stuck in naming simply because this is a "generalized MLT". Think of someone who has never used MLT: what makes sense to them, a query that you pass "documents" (a term already used throughout), or a query that you pass "items" (a term they haven't seen at all in our documentation)?

**Comment by clintongormley** [comment]
>  I would rather keep as few parameters as possible and invest time into making it work better out of the box?

I agree - I'd like to hear about the variety of use cases for this feature.  If there are one or two use cases which make up 95%, (eg query expansion) then perhaps we can provide something more specific which just works out of the box.

**Comment by alexksikes** [comment]
Sure let's take an example in the context of image search and computational biology. The [YRC Public Image Repository](http://images.yeastrc.org/imagerepo/searchImageRepoInit.do) is a large image collection of yeasts which have been genetically modified and studied. If you wanted to provide a "more like this" feature for that system, the first thing you may want to try is reduce each image to an histogram of intensities, turn these histograms into vectors and perform nearest neighbor search in that space. The hope is that images with similar histograms are probably related. 

The picture below shows more precisely how intensity histograms are computed. Here we simply go over each pixel, or neighborhood around that pixel, and count the intensity values.

![intensity_histograms](https://cloud.githubusercontent.com/assets/43475/8773190/a12af5ba-2ed2-11e5-9184-584e2a0b562e.png)

This just one type of features for images, but there are many others for all types of applications. For example, we could have further considered texture features or shape features. However, no matter what types of features we choose, the same process could be applied. The feature values are extracted from the item, and then put into a vector so that we can perform nearest neighbor search in that space.

How is this related to Item Query?

Our feature space is no longer tf-idf based, but rather intensity counts based. If we want to have decent results, we would need to change the default Lucene similarity to take these counts into account. We would also need a custom way to generate the characteristic vector for the image, which is no longer based of tf-idf. This later correspond to the `terms` parameter of item query which in the future should allow for scripting. 

I haven't mentioned how these feature vectors would be stored. There are different approaches, but we could for example imagine storing them as unique tokens with payloads corresponding to the intensity values, all in one field.

So the process has been to go from a document, which is not necessarily textual, that we call item, to a characteristic vector of terms or features, not necessarily based of tf-idf, and finally to an actual textual query.

**Comment by jpountz** [comment]
> Can we call it "documents" query instead of "items"?

+1 to documents, this looks more consistent to me

**Comment by cbuescher** [comment]
cc @elastic/es-search-aggs

**Comment by jimczi** [comment]
The linked [issue](https://github.com/elastic/elasticsearch/issues/11814) is closed so nothing further here, closing.
