### ISSUE TITLE
UpdateByQuery support AndFilterBuilder?

### ISSUE THREAD

**Issue by Praveen82** [elastic/elasticsearch#12295]
I need to update a document based on filter and query

=============
Context 
=============

I have many attributeId =100 and partnerId=10  in documents. 
I want to filter ( attributeId =100 AND  partnerId=10 ) then update all the documents based on the matched documents.

Example 1 : Works fine

The following code works fine based on filter ( andFilter and query ) combination.

	String rule="attributeId: 100";

QueryStringQueryBuilder query = QueryBuilders.queryString(rule);
AndFilterBuilder andqueryFilters = FilterBuilders.andFilter(); 
andqueryFilters.add(FilterBuilders.termFilter("partnerId", partnerId));

SearchResponse scrollResp=client.
.prepareSearch(props.getProperty("index"))
.setTypes(props.getProperty("type"))

.setSearchType(SearchType.SCAN).setScroll(new TimeValue(60000))
.setQuery(query)
.setPostFilter(andqueryFilters) 
.addFields("UserId")
.setSize(10000).execute()
.actionGet();

Example 2 : UpdateByQuery support AndFilterBuilder ? 

how to use PostFilter on  UpdateByQueryResponse????

String rule="attributeId: 100";

QueryStringQueryBuilder query = QueryBuilders.queryString(rule);
AndFilterBuilder andqueryFilters = FilterBuilders.andFilter(); 
andqueryFilters.add(FilterBuilders.termFilter("partnerId", partnerId));

UpdateByQueryClient updateByQueryClient = new UpdateByQueryClientWrapper(client);
			
			UpdateByQueryResponse response = updateByQueryClient.prepareUpdateByQuery().setIndices("index").setTypes("type")
					.setIncludeBulkResponses(BulkResponseOption.ALL)
	               .setScript("ctx._source.appId +="+appId).setScriptParams(scriptParams)
                     
                    .setPostFilter(andqueryFilters) --------- how to use PostFilter on  UpdateByQueryResponse
	                 .setQuery(query)
	                .execute()
	                .actionGet();

**Comment by Praveen82** [comment]
any update on this?

**Comment by clintongormley** [comment]
Hi @Praveen82 

Please ask questions like this on the forum instead: http://discuss.elastic.co/
