### ISSUE TITLE
Allow Elasticsearch logging into Elasticsearch

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#12305]
We do this [for Shield](https://www.elastic.co/guide/en/shield/current/configuring-auditing.html#audit-index) and it'd be rad if we could also do it for ES itself.

I know users can leverage Logstash for this, but for support to be able to export an index containing the logs from all nodes by simply enabling this sort of thing in the ES config would be super dooper helpful.

This will probably be reliant on #8786.

**Comment by khalighi** [comment]
+1

**Comment by lshunter** [comment]
ES logging into Elasticsearch, logstash logging into Elasticsearch, kibana logging into Elasticsearch, all wanted. Manage logs, manage yourself first.

**Comment by jasontedor** [comment]
I think that the right solution here is to use Filebeat, the same solution that we should eventually use for the audit logs too. This component of the stack already understands how to send logs to Elasticsearch, and we enable sending to a remote cluster too. The missing piece, as you say, is #8786. I will close this issue as I think this is the direction we should move towards.
