### ISSUE TITLE
fs stats empty

### ISSUE THREAD

**Issue by azerton** [elastic/elasticsearch#12301]
Hi all

Looking at _cluster/stats?human&pretty, I see stats for everything except for fs:

    "fs" : { },

Can anyone tell me what command ES is using in the background to fetch filesystem information? Or anywhere to look to easily debug? Thanks

**Comment by clintongormley** [comment]
Hi @azerton 

This is probably because the OS you're using is not supported by libsigar. We've removed sigar in 2.0 and will be relying on stats available from the JVM.
