### ISSUE TITLE
Test failure: IndicesShardStoreRequestTests.testBasic

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#12304]
This reproduced:
mvn test -Pdev -Dtests.seed=C1D4270765B2B237 -Dtests.class=org.elasticsearch.action.admin.indices.segments.IndicesShardStoreRequestTests -Dtests.method="testBasic" -Des.logger.level=DEBUG -Des.node.mode=network -Dtests.assertion.disabled=false -Dtests.heap.size=1024m -Dtests.locale=hu_HU -Dtests.timezone=America/Cancun

@areek can you take a look? I've disable the test for now.

**Comment by areek** [comment]
Thanks @rjernst. fixed https://github.com/elastic/elasticsearch/commit/98fd8d94fec3a376baf0bb3254cb928bc7c46951
