### ISSUE TITLE
Search template render API returns 500 error on malformed template

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#12315]
see https://github.com/elastic/elasticsearch/issues/12292

This should return a 400 error instead

**Comment by ammar27** [comment]
Hi, I am new to this project and would like to make this issue be the first I try to fix.

**Comment by hchokshi** [comment]
Hey, I'd like to work on this if it is still open

**Comment by andyb-elastic** [comment]
@elastic/es-search-aggs

**Comment by gauravmishra123** [comment]
Hi  i m a newbie, is this issue fixed? if not can i take this issue .

**Comment by cbuescher** [comment]
@gauravmishra123 the issue is being worked on, sorry. Take a look at issues labeled "adotme" and probably also "low hanging fruit", they should be relatively easy to get started with. In any case, pinging on the issue like you just did is a great idea and much appreciated!
