### ISSUE TITLE
Time zone parser throws illegal argument exception

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12317]
DELETE t
    
    POST /t/t/1
    {
        "name": "Prince George",
       "event-date": {
          "timestamp": "2015-07-15T00:00:00.000Z"
       }
    }
    
    POST /t/t/_search
    {
      "query": {
        "range": {
          "timestamp": {
            "gte": "now/d",
            "lte": "now/d",
            "time_zone": "-5:00"
          }
        }
      }
    }

returns:

    {
       "error": {
          "root_cause": [
             {
                "type": "illegal_argument_exception",
                "reason": "Invalid format: \"-5:00\" is malformed at \"5:00\""
             }
          ],
          "type": "search_phase_execution_exception",
          "reason": "all shards failed",
          "phase": "query",
          "grouped": true,
          "failed_shards": [
             {
                "shard": 0,
                "index": "t",
                "node": "l78GF4wCT1W8r2U-LSOrpA",
                "reason": {
                   "type": "illegal_argument_exception",
                   "reason": "Invalid format: \"-5:00\" is malformed at \"5:00\""
                }
             }
          ]
       },
       "status": 400
    }

**Comment by spinscale** [comment]
So this does not stem from the recent strict date changes, but from a refactoring far older in the `RangeQueryParser` which uses `DateTimeZone` instead of `DateMathParser`

```java
    public void testThatDateMathParserAndDateTimeZoneActDifferently() throws Exception {
        System.out.println(DateMathParser.parseZone("-05:00"));
        System.out.println(DateMathParser.parseZone("-5:00"));

        System.out.println(DateTimeZone.forID("-05:00"));
        // this fails always
        System.out.println(DateTimeZone.forID("-5:00"));
    }
```

This was introduced by [this commit](https://github.com/elastic/elasticsearch/commit/37287284e64a0e91ab400a16b187e719b55c8929)

**Comment by clintongormley** [comment]
thanks for investigating @spinscale 

@rjernst could you take a look please?

**Comment by rjernst** [comment]
@clintongormley The timezone offset you provided is not valid, it must be of the for [+-]\d\d:\d\d.

**Comment by clintongormley** [comment]
OK - this worked before.  Does it really need to be that strict here?

**Comment by clintongormley** [comment]
Plus the docs show an unsupported format currently:

* https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-range-query.html#_date_options
* https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-bucket-datehistogram-aggregation.html#_time_zone

**Comment by rjernst** [comment]
I don't think we should have our own timezone parsing method (which was removed in the referenced commit) just so we can allow a lenient format.

**Comment by rjernst** [comment]
This is a documented standard, let's stick to it.

**Comment by clintongormley** [comment]
OK - so the docs need updating then

**Comment by colings86** [comment]
Plus we should add a note to the braking changes in 2.0 doc

**Comment by rjernst** [comment]
@clintongormley @colings86 Docs updated for your review: #12357
