### ISSUE TITLE
geo_shape: getting IllegalArgumentException[Points of LinearRing do not form a closed linestring]

### ISSUE THREAD

**Issue by dimroc** [elastic/elasticsearch#12325]
When trying to index a Polygon into a geo_shape, I incorrectly get IllegalArgumentException[Points of LinearRing do not form a closed linestring]:

```
Elasticsearch::Transport::Transport::Errors::InternalServerError: [500] {"error":"PercolatorException[[development-geoevents-20150708-090828] failed to parse query [chicago,South Chicago]]; nested: IllegalArgumentException[Points of LinearRing do not form a closed linestring]; ","status":500}
```

The Polygon in question is a neighborhood in Chicago taken from a reliable source (foursquare)
neighborhood: https://gist.github.com/dimroc/6ddb159afa0b4507cc0a
original: https://github.com/blackmad/neighborhoods/blob/master/chicago.geojson

I've run this through QGIS and it returns no errors:

![check_geometry_validity_and_qgis_2_8_2-wien](https://cloud.githubusercontent.com/assets/635121/8762478/d0e54f94-2d47-11e5-97ee-177ca057dbce.jpg)

I've also verified that the start and end coordinates match.

My goal is to have this successfully indexed with no problems :+1: . Thanks for any feedback.

**Comment by dimroc** [comment]
Bug Repro Steps:

```
curl -XPUT http://127.0.0.1:9200/repro-bug -d '{"settings":{"number_of_shards":3},"mappings":{"geoevent":{"properties":{"geojson":{"type":"geo_shape"}}}}}'

curl https://gist.githubusercontent.com/dimroc/51e20d6f0b309f3ddca7/raw/de3fc24504c6b37f5f9c63bb9f25a409ee2feb3f/repro-bug-payload.json > /tmp/repro-bug.json

curl --data "@/tmp/repro-bug.json" -XPUT http://127.0.0.1:9200/repro-bug/geoevent/1
```

**Comment by komarserjio** [comment]
@dimroc Looks like your polygon is not fully valid (by [ISO 19107:2003](http://www.iso.org/iso/catalogue_detail.htm?csnumber=26012) standard).
I had the same issue when I was importing [Flickr Shapefiles Dataset] (http://code.flickr.net/2011/01/08/flickr-shapefiles-public-dataset-2-0/) files into elastic search.

You can repair/fix the polygon using this tool: https://github.com/tudelft3d/prepair
I did the trick with your repro-bug.json file and it helped - elastic search accepts fixed version.

Steps:
```bash
// fixed invalid polygon using tudelft3d/prepair tool
$ ./prepair --shpOut --ogr /tmp/repro-bug.json
// convert generated shape file back to geojson format
$ ogr2ogr -f GeoJSON  fixed-polygon.geojson out.shp

// ES accepts the fixed polygon now
$ curl --data "@/tmp/prepair/fixed-polygon.geojson" -XPUT http://localhost:9200/repro-bug/geoevent/1
{"_index":"repro-bug","_type":"geoevent","_id":"1","_version":1,"created":true}%
```

Hope it helps :)

**Comment by dimroc** [comment]
Thanks for the heads up @komarserjio, I'll be sure to check it out.

**Comment by bogensberger** [comment]
+1

I also verified that the shape is correct, using geojsonlint.com

**Comment by nknize** [comment]
@dimroc, hopefully you were able to resolve your issue. I was able to verify a closed loop at:
```json
[-87.530045, 41.742051],
[-87.530044, 41.742051],
[-87.530045, 41.742051],
``` 
Which violates the OGC SFA spec.

**Comment by nknize** [comment]
@bogensberger  

rome.json feature ```"OBJECTID" : 1``` also contains a closed loop at:
```json
[ 24.041199999999662, 38.212069999999528 ], 
[ 24.093430000000922, 38.270619999999326 ], 
[ 24.07726, 38.317940000000931 ],
[ 24.04028, 38.354170000000465 ],
[ 24.009260000000666, 38.394249999999374 ],
[ 23.96148, 38.377899999999613 ],
[ 23.91187, 38.384640000000218 ],
[ 23.862670000000378, 38.39394 ],
[ 23.810740000000862, 38.386249999999677 ], 
[ 23.806060000000912, 38.317409999999711 ], 
[ 23.858089999999777, 38.314169999999706 ],
[ 23.907110000000159, 38.298380000000293 ], 
[ 23.95579, 38.275229999999397 ], 
[ 24.001120000000753, 38.244950000000244 ], 
[ 24.041199999999662, 38.212069999999528 ],
```
Try out the wonderful suggestion posted above by @komarserjio and let us know if you were able to clean up the geometry.

**Comment by clintongormley** [comment]
No more feedback. Closing

**Comment by marcinn** [comment]
Wow.
