### ISSUE TITLE
Intensity Highlighting

### ISSUE THREAD

**Issue by alexksikes** [elastic/elasticsearch#12326]
## Introduction

On queries composed of many terms, for example when using More Like This (MLT) or an [Item Query](https://github.com/elastic/elasticsearch/issues/12293), it is often quite desirable to explain the results returned. This helps users form a mental model about the underlying matching algorithm, and subsequently removes some of the magic around these types of queries.

Currently, developers have two out of the box options in order to provide such a functionality: [explain](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-explain.html) and [highlighting](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-highlighting.html). Explain is useful for debugging, but has some unfortunate performance implications. Its output is also quite verbose. Highlighting is useful to show the matched keywords in context, but it only provides a partial understanding of scoring.

What we would need instead is something in between highlighting and explain. Something which would not only highlight the terms in context but also provide the level of importance that term had in scoring each document. This would provide a best of both worlds solution. In fact, the idea isn't new! Lucene already provides a GradientFormatter, though it is not used at the moment in Elasticsearch.

Let us further illustrate our point with an example.
## Example

In the example below, the user has asked for movies similar to the movie Terminator 2. Under the hood an MLT query was triggered which then generated a query composed of the salient terms in the requested document. The matching terms are then highlighted within each returned document, but with some additional hints as to their level of importance in scoring. The greater the intensity of the highlight, the more important that term is in computing the score of the document.

![itensity_highlighter2](https://cloud.githubusercontent.com/assets/43475/8762299/59560490-2d75-11e5-8ae8-16a89278e8d1.png)

In this example, we can see that the first movie has less terms matching the query than the second movie. However, these terms are highlighted with greater intensities, which explains why that movie is ranked higher in the result set. If the user did not have the intensity of the highlight, he could be puzzled as to why this is the case. For example, he could wrongly assume that more terms matching means greater scoring. Here we not only know why the document matched, but also how the score was probably computed (which terms participated in the scoring and to what extent). 
## API usage

We could return all the per-query-term scores, but maybe such an output would be too verbose, and too close to just using explain. Instead, and this is not set in stone, we could highlight the terms in context with style. In order to do so, we can introduce a `with_intensities` option which would take an integer representing the number of possible intensities.

Here is how the above example could have been generated:

``` json
GET /tmdb/movies/_search
{
  "query": {
    "more_like_this": {
      "like": {
        "_id": 280
      }
    }
  },
  "highlight": {
    "fields": {
      "plot": {
        "number_of_fragments": 0,
        "with_intensities": 4
      }
    }
  }
}
```

And the response:

``` json
{
  ...
  "hits": {
    "total": 3,
    "max_score": 10.2301,
    "hits": [
      {
        ...
        "highlight": {
          "plot": ["It's been 10 years since John <em class=\"hlt4\">Connor</em> saved Earth from
<em class=\"hlt3\">Judgment Day</em>, and he's now living under the radar, steering
clear of using anything <em class=\"hlt4\">Skynet</em> can trace. That is, until he
encounters T-X, a <em class=\"hlt1\">robotic</em> <em class=\"hlt2\">assassin</em> ordered
to finish what <em class=\"hlt4\">T-1000</em> started. Good thing <em class=\"hlt4\">Connor</em>'s
former nemesis, the <em class=\"hlt4\">Terminator</em>, is back to aid the now-adult
<em class=\"hlt4\">Connor</em> … just like he promised."]
        }
      },
      ...
    ]
  }
}
```
## Implementation Notes

As previously mentioned, Lucene does provide a GradientFormatter and a SpanGradientFormatter which can be used with the plain highlighter. Another possibility would include adding the option to retain the per-query-term scores to plain highlighter and/or to fast vector highlighter, that is retaining the scores which were used to compute the score given to each fragment. There are roughly the same term scores which were used to compute the score of the document before highlighting.

**Comment by nik9000** [comment]
It's not a bad idea. I always dislike highlighter things in es now because
you have to do everything three times.

**Comment by jimczi** [comment]
This feature request is an interesting idea but since its opening we have not seen enough feedback that it is a feature we should pursue. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).

**Comment by hilmiger** [comment]
Hey,

Acutally we are interested about this feature. 
But not for just scoring part, if it will be possible to add term vectors(positions, offsets etc.) to response, it would be wonderful.

We really liked if you reconsider to at least discuss this.
