### ISSUE TITLE
Elasticsearch, Logstash issues

### ISSUE THREAD

**Issue by AGirin** [elastic/elasticsearch#12321]
This is in relation to 
https://github.com/elastic/elasticsearch/issues/12276

We upgraded to ES 1.7 and same issue occurs. Shutdown Logstash server and ES locks - no connections are possible even though ES nodes report cluster state as green.

**Comment by clintongormley** [comment]
It sounds like you are using the node client in logstash. I'd advise moving to the http client instead.
