### ISSUE TITLE
Using FieldValueFactorFunction.Modifier.NONE results in malformed queries

### ISSUE THREAD

**Issue by alexclare** [elastic/elasticsearch#12327]
When constructing field value factor functions, using `.modifier(FieldValueFactorFunction.Modifier.NONE)` yields malformed requests.

Sample expected output:
```
{
  "function_score" : {
    "query" : {
      "simple_query_string" : {
        "query" : "foo"
      }
    },
    "functions" : [ {
      "field_value_factor" : {
        "field" : "test",
        "modifier" : "none"
      }
    } ]
  }
}
```
Or alternatively, no modifier property should be added at all.

Actual output:
```
{
  function_score" : {
    "query" : {
      "simple_query_string" : {
        "query" : "foo"
      }
    },
    "functions" : [ {
      "field_value_factor" : {
        "field" : "test",
        "modifier" : ""
      }
    } ]
  }
}
```

This ultimately results in a parsing error: `IllegalArgumentException[No enum constant org.elasticsearch.common.lucene.search.function.FieldValueFactorFunction.Modifier.]`

**Comment by brwe** [comment]
fixed via #12328
