### ISSUE TITLE
Make `_index` field non-configurable

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12329]
Since #12027 was merged, the `_index` field can be used in queries, aggregations, sorting, and scripting, even though it is not indexed.

I can't see any reason now why we would allow users to set:

    "_index": { "enabled": true }

**Comment by clintongormley** [comment]
@rjernst do you agree?

**Comment by rjernst** [comment]
I do agree. I opened #12356.

**Comment by JohnTian** [comment]
Soga.

**Comment by qyffWJ** [comment]
:)
