### ISSUE TITLE
logs should be under /var/logs/elasticsearch on linux, data under /var/elasticsearch...

### ISSUE THREAD

**Issue by ofir-petrushka** [elastic/elasticsearch#12337]
Currently everything is under the "product" directory /usr/share/elasticsearch "windows style", see:
https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-dir-layout.html

As with the config that is linked to /etc...
ls -l /usr/share/elasticsearch/
config -> /etc/elasticsearch

Should have 
logs - > /var/logs/elasticsearch
data -> /var/elasticsearch/data

Why?
This is standard linux structure and elasticsearch is the only big software that breaks it.

Many admin tools and procedures assume this structure.
Like doing log aggregation on all files in /var/log
Checking disk space etc.

Not to mention that the bin should bin in /bin...

**Comment by imotov** [comment]
What type of installation are you using and how do you start elasticsearch? If you are using DEB or RPM package the directory setup is different. Please see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-dir-layout.html#_deb_and_rpm for more information.

**Comment by ofir-petrushka** [comment]
Using elastic.co apt package for version 1.5, see and try:
https://github.com/rounds/10M-Docker-Images/blob/master/elastic_search/Dockerfile
https://registry.hub.docker.com/u/rounds/10m-elastic-search/

**Comment by imotov** [comment]
Yes, I see the issue with 1.5. However, it's no longer reproducible with 1.7.0.  @spinscale, could you comment on this?

**Comment by spinscale** [comment]
Hey,

this is indeed a bug in the 1.5 package. The problem is that in `/usr/lib/systemd/system/elasticsearch.service` we try to load data from the `/etc/default/elasticsearch` file, where usually everything is commented out and this leads to empty specified directories on startup.

You can either upgrade, or change your `.service` file to something like this

```
[Service]
Environment=ES_HOME=/usr/share/elasticsearch
Environment=CONF_DIR=/etc/elasticsearch
Environment=CONF_FILE=/etc/elasticsearch/elasticsearch.yml
Environment=DATA_DIR=/var/lib/elasticsearch
Environment=LOG_DIR=/var/log/elasticsearch
Environment=PID_DIR=/var/run/elasticsearch
EnvironmentFile=-/etc/default/elasticsearch

User=elasticsearch
Group=elasticsearch

ExecStart=/usr/share/elasticsearch/bin/elasticsearch \
                                                -Des.pidfile=$PID_DIR/elasticsearch.pid \
                                                -Des.default.path.home=$ES_HOME \
                                                -Des.default.path.logs=$LOG_DIR \
                                                -Des.default.path.data=$DATA_DIR \
                                                -Des.default.config=$CONF_FILE \
                                                -Des.default.path.conf=$CONF_DIR
```
