### ISSUE TITLE
Known issues / production deployments should mention keepalive kernel parameters

### ISSUE THREAD

**Issue by ofir-petrushka** [elastic/elasticsearch#12338]
Cluster might be rendered useless if deployed with some firewall or on some hosting providers.
For example GCE (Google Cloud Engine) has an internal FW that drops idle connection after 10 minutes.

These parameters in sysctl should have recommended values for production deployments: 
net.ipv4.tcp_keepalive_time
net.ipv4.tcp_keepalive_intvl
net.ipv4.tcp_keepalive_probes

Deep explanation here:
http://blog.trifork.com/2015/04/08/dealing-with-nodenotavailableexceptions-in-elasticsearch/

Bonus points for rethinking how this works and make it work out of the box.

**Comment by clintongormley** [comment]
Let's see if Frans Flippo would be up for sending a docs PR

**Comment by fransflippo** [comment]
I will work on a PR for amending the documentation (probably in https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-transport.html). If there's a production deployments page I'll see if I can add a comment about setting keepalive there as well.

**Comment by probakowski** [comment]
Closing as it is documented in https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-transport.html#_long_lived_idle_connections
