### ISSUE TITLE
Ability to specify specific buckets in Aggregation Path syntax

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#12336]
The syntax used in both the terms aggregation ordering and in the pipeline aggregations is at the moment limited to referencing numeric metric aggregations and single-bucket aggregations. We should extend the syntax so users are able to specify a specific bucket in a multi-bucket aggregation. So, for example you could do the following:

```json
{
  "aggs": {
    "fruits": {
      "terms": {
        "field": "fruit",
        "order": {
          "colours.yellow": "asc"
        }
      },
      "aggs": {
        "colours": {
          "terms": {
            "field": "colour"
          }
        }
      }
    }
  }
}
```

which would order the `fruits` terms by the number of `yellow` documents for each `fruit`.

We would need to decide what we would do if `yellow` didn't appear in the top 10 terms for a particular fruit. Do we just say the sort value is `0`?

Bonus Points:

We could also support very basic operators on the multi-bucket aggregation's buckets so you could do something like:

```json
"order": {
    "avg(colours)": "asc"
}
```

which would sort by the average (mean) document count value across all the colours for each fruit. and:

```json
"order": {
    "avg(colours>total_sales)": "asc"
}
```
which would sort by the average (mean) value of `total_sales` across all the colours for each fruit.

**Comment by clintongormley** [comment]
There does't seem to be much call for this syntax, so I'm going to close this issue for now.
