### ISSUE TITLE
Remove primaryAllocatedPostApi flag and use UnassignedInfo information 

### ISSUE THREAD

**Issue by kimchy** [elastic/elasticsearch#12334]
Conceptually, we can remove the need for the flag, which is tricky to manage and reason about, and just use the `UnassignedInfo` and reason of `INDEX_CREATED`.

**Comment by clintongormley** [comment]
@bleskes i assume this is still worth doing?

**Comment by bleskes** [comment]
yep and it has been removed  in 2.x and completely replaced in master with #14739
