### ISSUE TITLE
Custom default mapping partially overwritten by ES 

### ISSUE THREAD

**Issue by technosf** [elastic/elasticsearch#12348]
I am using mapping *.json* files in ES 1.7.0 applied to document types to modify the default *dynamic* mapping for *string* data so as **not** to store the *raw* field by using the definition *"fields" : {}*

I am finding, by querying the mapping, that although ES implements the mapping on the whole, it is redefining *raw* for string defaults.

Is this an issue or a feature? If a feature, how do I turn off *raw* for dynamic string fields?

Here is the *dynamic_templates* definition part put into ES for *message* and for *strings*, both with raw turned off:
```
        "dynamic_templates" : [ {
          "message_field" : {
            "mapping" : {
				"index" : "not_analyzed",
				"omit_norms" : true,
				"type" : "string",
				"fields" : {}
            },
            "match" : "message",
            "match_mapping_type" : "string"
          }
        }, {
          "string_fields" : {
            "mapping" : {
              "index" : "not_analyzed",
              "omit_norms" : true,
              "type" : "string",
			  "fields" : {}
            },
            "match" : "*",
            "match_mapping_type" : "string"
          }
        } ],
```

Here is the definition pulled from ES - notice that the *raw* definition is back in for *strings*, but *message* is still set correctly:
```
        "dynamic_templates" : [ {
          "message_field" : {
            "mapping" : {
              "index" : "not_analyzed",
              "omit_norms" : true,
              "type" : "string",
              "fields" : { }
            },
            "match" : "message",
            "match_mapping_type" : "string"
          }
        }, {
          "string_fields" : {
            "mapping" : {
              "index" : "not_analyzed",
              "omit_norms" : true,
              "type" : "string",
              "fields" : {
                "raw" : {
                  "index" : "not_analyzed",
                  "ignore_above" : 256,
                  "type" : "string"
                }
              }
            },
            "match" : "*",
            "match_mapping_type" : "string"
          }
        } ],
```

**Comment by rjernst** [comment]
`raw` fields are a feature of logstash. Are you using logstash? Do you have logstash configured to manage your index templates? Also, specifying mappings through on disk files has been removed in the upcoming ES 2.0. You should explicitly define your mappings, and/or use index templates (as it seems you are here, so I don't understand why you would be using mapping files).

**Comment by technosf** [comment]
I am using Config Mappings (per 1.7 doc), as *_default_* is inefficient for the data I'm putting in ES (yes via LS). 

testing this out, LS 1.4.3 is modifying the default for the mapping, whether "manage_template" is true or false. 

Looks like LS templates are the way to go - thanks for the pointer.
