### ISSUE TITLE
[CI] Failure: IndicesStoreIntegrationTests.testShardActiveElseWhere

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#12341]
Tests with failures:
  - org.elasticsearch.indices.store.IndicesStoreIntegrationTests.testShardActiveElseWhere

This failed a few times lately and seems to be reproducible, e.g.

http://build-us-00.elastic.co/job/es_g1gc_master_metal/12111/
http://build-us-00.elastic.co/job/es_feature_query_refactoring/5367/

I could reproduce it on master at ca3e0c6d4976b24c6b6a8f833603e92159271ba5 with the following:

mvn test -Pdev -Dtests.seed=2EC73F5447E49994 -Dtests.class=org.elasticsearch.indices.store.IndicesStoreIntegrationTests -Dtests.slow=true -Dtests.method="testShardActiveElseWhere" -Des.logger.level=DEBUG -Des.node.mode=network -Dtests.assertion.disabled=false -Dtests.heap.size=1024m -Dtests.locale=mt -Dtests.timezone=Asia/Brunei

**Comment by bleskes** [comment]
This should be fixed with https://github.com/elastic/elasticsearch/commit/068fae218f3c59fe6bc51adcd8d5f9b5a1dbccaf
