### ISSUE TITLE
Percentiles aggregation generates json field names containing dots

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#12359]
The percentiles aggregation can generate field names containing dots:

```json
"aggregations": {
  "percentiles": {
    "values": {
      "99.0": 4
    }
  }
}
```

The reason why it annoys me a bit is that we started rejecting documents that contain dots in field name, which means the result of a percentiles aggregation could not be added back to an elasticsearch index.

**Comment by colings86** [comment]
The `percentiles` and `percentiles_rank` aggregation have a `keyed` parameter which when set to `false` will change the response format to an array containing an object for each percentile with two fields `percentile` and `value`. This can be used to get around this issue
