### ISSUE TITLE
IndicesShardStoreRequestTests flaky

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#12354]
Suite: org.elasticsearch.action.admin.indices.segments.IndicesShardStoreRequestTests
  1> [2015-07-20 22:03:39,297][TRACE][action.admin.indices.shards] [node_t0] cluster state used to determine shards [version: 14
  1> state uuid: fLv4zaosRpSgl9raZAw-2Q
  1> from_diff: false
  1> meta data version: 5
  1> nodes: 
  1>    [node_t1][AyweLoM9SDuPdgv3kTB_EQ][beast][local[462]]{mode=local, enable_custom_paths=true}
  1>    [node_t2][q0NaofS5SGGHkn2DKmfKoA][beast][local[463]]{mode=local, enable_custom_paths=true}
  1>    [node_t0][sKWP13YWSHyhpJ8fUgdhJw][beast][local[461]]{mode=local, enable_custom_paths=true}, local, master
  1>    [node_t3][hfvftAiyS_yNlxicAGMhHQ][beast][local[464]]{mode=local, client=true, data=false, enable_custom_paths=true}
  1> routing_table (version 7):
  1> -- index [test]
  1> ----shard_id [test][0]
  1> --------[test][0], node[q0NaofS5SGGHkn2DKmfKoA], [P], v[4], s[STARTED], a[id=LRZukkcqQyKbTtaY9llqWA]
  1> --------[test][0], node[AyweLoM9SDuPdgv3kTB_EQ], [R], v[4], s[STARTED], a[id=S3MYag4yRDejlaG5VjXwTw]
  1> ----shard_id [test][1]
  1> --------[test][1], node[AyweLoM9SDuPdgv3kTB_EQ], [P], v[4], s[STARTED], a[id=eVreOkM2S5W6rqvDubvg5A]
  1> --------[test][1], node[sKWP13YWSHyhpJ8fUgdhJw], [R], v[4], s[STARTED], a[id=2hRWi2Y_QQujB4UlFRrkvw]
  1> 
  1> routing_nodes:
  1> -----node_id[q0NaofS5SGGHkn2DKmfKoA][V]
  1> --------[test][0], node[q0NaofS5SGGHkn2DKmfKoA], [P], v[4], s[STARTED], a[id=LRZukkcqQyKbTtaY9llqWA]
  1> -----node_id[AyweLoM9SDuPdgv3kTB_EQ][V]
  1> --------[test][1], node[AyweLoM9SDuPdgv3kTB_EQ], [P], v[4], s[STARTED], a[id=eVreOkM2S5W6rqvDubvg5A]
  1> --------[test][0], node[AyweLoM9SDuPdgv3kTB_EQ], [R], v[4], s[STARTED], a[id=S3MYag4yRDejlaG5VjXwTw]
  1> -----node_id[sKWP13YWSHyhpJ8fUgdhJw][V]
  1> --------[test][1], node[sKWP13YWSHyhpJ8fUgdhJw], [R], v[4], s[STARTED], a[id=2hRWi2Y_QQujB4UlFRrkvw]
  1> ---- unassigned
  1> ]
  1> [2015-07-20 22:03:39,299][TRACE][action.admin.indices.shards] [node_t0] cluster state used to determine shards [version: 14
  1> state uuid: fLv4zaosRpSgl9raZAw-2Q
  1> from_diff: false
  1> meta data version: 5
  1> nodes: 
  1>    [node_t1][AyweLoM9SDuPdgv3kTB_EQ][beast][local[462]]{mode=local, enable_custom_paths=true}
  1>    [node_t2][q0NaofS5SGGHkn2DKmfKoA][beast][local[463]]{mode=local, enable_custom_paths=true}
  1>    [node_t0][sKWP13YWSHyhpJ8fUgdhJw][beast][local[461]]{mode=local, enable_custom_paths=true}, local, master
  1>    [node_t3][hfvftAiyS_yNlxicAGMhHQ][beast][local[464]]{mode=local, client=true, data=false, enable_custom_paths=true}
  1> routing_table (version 7):
  1> -- index [test]
  1> ----shard_id [test][0]
  1> --------[test][0], node[q0NaofS5SGGHkn2DKmfKoA], [P], v[4], s[STARTED], a[id=LRZukkcqQyKbTtaY9llqWA]
  1> --------[test][0], node[AyweLoM9SDuPdgv3kTB_EQ], [R], v[4], s[STARTED], a[id=S3MYag4yRDejlaG5VjXwTw]
  1> ----shard_id [test][1]
  1> --------[test][1], node[AyweLoM9SDuPdgv3kTB_EQ], [P], v[4], s[STARTED], a[id=eVreOkM2S5W6rqvDubvg5A]
  1> --------[test][1], node[sKWP13YWSHyhpJ8fUgdhJw], [R], v[4], s[STARTED], a[id=2hRWi2Y_QQujB4UlFRrkvw]
  1> 
  1> routing_nodes:
  1> -----node_id[q0NaofS5SGGHkn2DKmfKoA][V]
  1> --------[test][0], node[q0NaofS5SGGHkn2DKmfKoA], [P], v[4], s[STARTED], a[id=LRZukkcqQyKbTtaY9llqWA]
  1> -----node_id[AyweLoM9SDuPdgv3kTB_EQ][V]
  1> --------[test][1], node[AyweLoM9SDuPdgv3kTB_EQ], [P], v[4], s[STARTED], a[id=eVreOkM2S5W6rqvDubvg5A]
  1> --------[test][0], node[AyweLoM9SDuPdgv3kTB_EQ], [R], v[4], s[STARTED], a[id=S3MYag4yRDejlaG5VjXwTw]
  1> -----node_id[sKWP13YWSHyhpJ8fUgdhJw][V]
  1> --------[test][1], node[sKWP13YWSHyhpJ8fUgdhJw], [R], v[4], s[STARTED], a[id=2hRWi2Y_QQujB4UlFRrkvw]
  1> ---- unassigned
  1> ]
  1> [2015-07-20 22:03:39,303][TRACE][action.admin.indices.shards] [node_t0] [test][0] fetching [shard_stores] from [sKWP13YWSHyhpJ8fUgdhJw, AyweLoM9SDuPdgv3kTB_EQ, q0NaofS5SGGHkn2DKmfKoA]
  1> [2015-07-20 22:03:39,304][TRACE][action.admin.indices.shards] [node_t0] [test][1] fetching [shard_stores] from [q0NaofS5SGGHkn2DKmfKoA, AyweLoM9SDuPdgv3kTB_EQ, sKWP13YWSHyhpJ8fUgdhJw]
  1> [2015-07-20 22:03:39,350][TRACE][action.admin.indices.shards] [node_t0] cluster state used to determine shards [version: 16
  1> state uuid: 46odQ1B4R0CbA_UCxM708Q
  1> from_diff: false
  1> meta data version: 6
  1> nodes: 
  1>    [node_t2][q0NaofS5SGGHkn2DKmfKoA][beast][local[463]]{mode=local, enable_custom_paths=true}
  1>    [node_t0][sKWP13YWSHyhpJ8fUgdhJw][beast][local[461]]{mode=local, enable_custom_paths=true}, local, master
  1>    [node_t3][hfvftAiyS_yNlxicAGMhHQ][beast][local[464]]{mode=local, client=true, data=false, enable_custom_paths=true}
  1> routing_table (version 9):
  1> -- index [test]
  1> ----shard_id [test][0]
  1> --------[test][0], node[q0NaofS5SGGHkn2DKmfKoA], [P], v[5], s[STARTED], a[id=LRZukkcqQyKbTtaY9llqWA]
  1> --------[test][0], node[null], [R], v[5], s[UNASSIGNED], unassigned_info[[reason=NODE_LEFT], at[2015-07-21T02:03:39.340Z], details[node_left[AyweLoM9SDuPdgv3kTB_EQ]]]
  1> ----shard_id [test][1]
  1> --------[test][1], node[sKWP13YWSHyhpJ8fUgdhJw], [P], v[6], s[STARTED], a[id=2hRWi2Y_QQujB4UlFRrkvw]
  1> --------[test][1], node[null], [R], v[6], s[UNASSIGNED], unassigned_info[[reason=NODE_LEFT], at[2015-07-21T02:03:39.340Z], details[node_left[AyweLoM9SDuPdgv3kTB_EQ]]]
  1> 
  1> routing_nodes:
  1> -----node_id[q0NaofS5SGGHkn2DKmfKoA][V]
  1> --------[test][0], node[q0NaofS5SGGHkn2DKmfKoA], [P], v[5], s[STARTED], a[id=LRZukkcqQyKbTtaY9llqWA]
  1> -----node_id[sKWP13YWSHyhpJ8fUgdhJw][V]
  1> --------[test][1], node[sKWP13YWSHyhpJ8fUgdhJw], [P], v[6], s[STARTED], a[id=2hRWi2Y_QQujB4UlFRrkvw]
  1> ---- unassigned
  1> --------[test][1], node[null], [R], v[6], s[UNASSIGNED], unassigned_info[[reason=NODE_LEFT], at[2015-07-21T02:03:39.340Z], details[node_left[AyweLoM9SDuPdgv3kTB_EQ]]]
  1> --------[test][0], node[null], [R], v[5], s[UNASSIGNED], unassigned_info[[reason=NODE_LEFT], at[2015-07-21T02:03:39.340Z], details[node_left[AyweLoM9SDuPdgv3kTB_EQ]]]
  1> ]
  1> [2015-07-20 22:03:39,350][TRACE][action.admin.indices.shards] [node_t0] [test][0] fetching [shard_stores] from [q0NaofS5SGGHkn2DKmfKoA, sKWP13YWSHyhpJ8fUgdhJw]
  1> [2015-07-20 22:03:39,350][TRACE][action.admin.indices.shards] [node_t0] [test][1] fetching [shard_stores] from [q0NaofS5SGGHkn2DKmfKoA, sKWP13YWSHyhpJ8fUgdhJw]
  2> REPRODUCE WITH: mvn test -Pdev -Dtests.seed=989A264CC8E20C32 -Dtests.class=org.elasticsearch.action.admin.indices.segments.IndicesShardStoreRequestTests -Dtests.method="testBasic" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=ja_JP -Dtests.timezone=Pacific/Easter
FAILURE 0.97s J1 | IndicesShardStoreRequestTests.testBasic <<<
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <0>
   >      but: was <2>
   > 	at __randomizedtesting.SeedInfo.seed([989A264CC8E20C32:33603B59173E8A1C]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.action.admin.indices.segments.IndicesShardStoreRequestTests.testBasic(IndicesShardStoreRequestTests.java:100)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> NOTE: leaving temporary files on disk at: /home/rmuir/workspace/elasticsearch/core/target/J1/temp/org.elasticsearch.action.admin.indices.segments.IndicesShardStoreRequestTests_989A264CC8E20C32-001
  2> NOTE: test params are: codec=Asserting(Lucene50): {_size=PostingsFormat(name=Asserting), field=PostingsFormat(name=Asserting), _field_names=PostingsFormat(name=Asserting), _type=PostingsFormat(name=Asserting), _uid=PostingsFormat(name=Asserting), _all=PostingsFormat(name=Asserting)}, docValues:{_version=DocValuesFormat(name=Asserting)}, sim=RandomSimilarityProvider(queryNorm=true,coord=yes): {}, locale=ja_JP, timezone=Pacific/Easter
  2> NOTE: Linux 3.19.0-15-generic amd64/Oracle Corporation 1.8.0_45 (64-bit)/cpus=8,threads=1,free=258551784,total=527433728
  2> NOTE: All tests run in this JVM: [FieldDataFilterIntegrationTests, IndexTemplateBlocksTests, JsonFilteringGeneratorTests, DynamicMappingTests, SimpleBlocksTests, SingleShardNoReplicasRoutingTests, MultiTermVectorsTests, AliasRoutingTests, SimpleCountTests, CommitStatsTests, DateBackwardsCompatibilityTests, GroovySecurityTests, ExplainableScriptTests, NaNSortingTests, BooleansTests, TimestampMappingTests, PluginsInfoTest, SimpleNodesInfoTests, ASCIIFoldingTokenFilterFactoryTests, RecoveriesCollectionTests, ShapeBuilderTests, MinDocCountTests, StopAnalyzerTests, SearchSourceBuilderTest, ClusterSettingsTests, PrimaryNotRelocatedWhileBeingRecoveredTests, MemoryCircuitBreakerTests, CircuitBreakerServiceTests, NetworkPartitionTests, HeadersAndContextCopyClientTests, DisabledFieldDataFormatTests, ExplainActionTests, FieldDataLoadingTests, ExistsMissingTests, ClusterBlockTests, ToAndFromJsonMetaDataTests, SimpleStringMappingTests, SnapshotBackwardsCompatibilityTest, SitePluginRelativePathConfigTests, NettyTransportMultiPortIntegrationTests, BlendedTermQueryTest, ShardsAllocatorModuleTests, GeoJSONShapeParserTests, FilterFieldDataTest, HotThreadsTest, WildcardExpressionResolverTests, PutWarmerRequestTests, CopyToMapperTests, ParentFieldLoadingTest, TransportClientTests, SuggestSearchTests, UpdateTests, SimpleNettyTransportTests, StartedShardsRoutingTests, ResourceWatcherServiceTests, DistanceUnitTests, CardinalityTests, SimpleAllMapperTests, IndexRequestBuilderTests, SettingsFilterTests, ExceptionRetryTests, CodecTests, CumulativeSumTests, CustomPostingsHighlighterTests, UpdateMappingIntegrationTests, IndexFieldTypeTests, ShardUtilsTests, SimpleValidateQueryTests, IndicesServiceTest, PreBuiltAnalyzerIntegrationTests, YamlFilteringGeneratorTests, ChildrenQueryTests, TribeUnitTests, AggregationsBinaryTests, AnalysisFactoryTests, BytesRestResponseTests, MustacheTest, StatsTests, HppcMapsTests, GeoShapeQueryBuilderTests, DuelScrollTests, SearchStatsUnitTests, BlobStoreTest, IndicesLifecycleListenerSingleNodeTests, GeoPointFieldTypeTests, LimitTokenCountFilterFactoryTests, MultiFieldTests, BytesStreamsTests, SignificantTermsBackwardCompatibilityTests, TransportTwoNodesSearchTests, BucketSelectorTests, Base64Test, SimpleMultiSearchTests, SimpleLuceneTests, HunspellServiceTests, SizeValueTests, DoubleNestedSortingTests, BigArraysTests, SearchScrollTests, SimpleRecoveryTests, UpdateByNativeScriptTests, UpdateNumberOfReplicasTests, IndexQueryParserFilterDateRangeTimezoneTests, PagedBytesStringFieldDataTests, PluginManagerTests, StemmerTokenFilterFactoryTests, IndexedScriptTests, FreqTermsEnumTests, WriteConsistencyLevelTests, AliasedIndexDocumentActionsTests, SearchServiceTests, NettyTransportTests, IdMappingTests, ScriptModesTests, Rest1Tests, UpgradeTest, Rest4Tests, NestedAggregatorTest, SimpleGetMappingsTests, CreateIndexRequestBuilderTest, InternalEngineIntegrationTest, TemplateQueryBuilderTest, TransportMessageTests, ChannelsTests, DedicatedClusterSnapshotRestoreTests, MoreLikeThisQueryTests, CancellableThreadsTest, BulkProcessorTests, RandomAllocationDeciderTests, FilterTests, RoundingTests, StoredNumericValuesTest, LongNestedSortingTests, MinBucketTests, AnalysisModuleTests, StartRecoveryRequestTest, DiscoveryWithServiceDisruptionsTests, IndexLifecycleActionTests, ItemSerializationTests, CircuitBreakerUnitTests, ConcurrentDynamicTemplateTests, MetaDataWriteDataNodesTests, IndexShardTests, ShardInfoTests, IndexRequestBuilderTest, PercolatorFacetsAndAggregationsTests, GeoDistanceTests, RecoveryWithUnsupportedIndicesTests, SyncedFlushUnitTests, ChildrenTests, CborXContentParserTests, UpdateSettingsTests, GeoLocationContextMappingTest, TemplateQueryTest, InnerHitsTests, OpenCloseIndexTests, SuggestStatsTests, TransportIndexFailuresTest, IndicesShardStoreRequestTests]

**Comment by areek** [comment]
I will take a look

**Comment by areek** [comment]
Test bug: after killing a data node, we have to wait till yellow state to ensure that the cluster state reflects the unassigned shards. pushed a fix https://github.com/elastic/elasticsearch/commit/ae750bca699495b93a1ecb46cc487de96bee1150
