### ISSUE TITLE
Imprecise field name matching with varying results

### ISSUE THREAD

**Issue by Lensi** [elastic/elasticsearch#12369]
Had a query with ever-changing results:
```
curl -XPOST localhost:9200/event/_search?size=0 -d '{
    "query": {
        "term": {
            "id": 31
        }
    }
}'
```
Only about half of the relevant documents were returned and it was changing by +-50% between requests on a stable index.
I realised that the real field name was `event.data.id` and changing the query fixed the problem. But the field shouldn't match at all, it should not match just a sub section, and it should not vary between requests.
I have a few documents indexed where the field name is `event.id`. It seems this is what is triggering the bug, since I can't reproduce on other `event.data.*` fields.

**Comment by jpountz** [comment]
@Lensi Totally agreed. As of 2.0 the full field name will be required, see https://github.com/elastic/elasticsearch/pull/9670
