### ISSUE TITLE
Distance Score query gives wrong sort order

### ISSUE THREAD

**Issue by Molenx** [elastic/elasticsearch#12370]
Using _geo_distance query gives me correct order by closest distance, geoCenter field is created using a transform in the mapping. 
```
{
  "from": 0,
  "size": 200,
  "sort": [
    {
      "_geo_distance": {
        "geoCenter": {
          "lat": 29.745703,
          "lon": -95.740514
        },
        "order": "asc",
        "unit": "mi",
        "distance_type": "plane"
      }
    }
  ]
}
```
However using Distance Score query on the same field gives wrong sort, every 4th item or so in the results gets lower score even though it closer, the deeper you go through the results the more wrong sorts I get, tried using different score functions and parameters but still getting same wrong sort consistently.
```
{
  "from": 0,
  "size": 100,
  "script_fields": {
    "MilesAway": {
      "script": "doc['geoCenter'].distanceInMiles(lat,lon)",
      "params": {
        "lat": 29.745703,
        "lon": -95.740514
      }
    }
  },
  "_source": {
    "include": [
      "doc.*"
    ]
  },
  "query": {
    "function_score": {
      "functions": [
        {
          "gauss": {
            "geoCenter": {
              "origin": {
                "lat": 29.745703,
                "lon": -95.740514
              },
              "scale": "500m",
              "offset": "1km",
              "decay": 0.99
            }
          }
        }
      ]
    }
  }
```

**Comment by brwe** [comment]
function score uses sloppy arc for distance computation and `distanceInMiles` in scripts uses "plane"  so I would expect results to be slightly different. Can you try `arcDistanceInMiles` instead in the script and see if results are as expected?

**Comment by Molenx** [comment]
That worked, thank you!

**Comment by clintongormley** [comment]
Closing
