### ISSUE TITLE
Create Memory Index with Elasticsearch.net 

### ISSUE THREAD

**Issue by serhattopkaya** [elastic/elasticsearch#12375]
Hi, 

I try to create memory index with following code but it creates regular index.
Any idea?
           
            var node = new Uri("http://localhost:9200");
            var settings = new ConnectionSettings(node);
            var client = new Elasticsearch.Net.ElasticsearchClient(settings);
            var js = JsonConvert.SerializeObject("{settings: { index.store.type: memory}");
            var index = client.IndicesCreate("sampleIndex", js);

**Comment by serhattopkaya** [comment]
Problem solved like that:

var js = new
                   {
                       settings = new
                       {
                           index = new
                           {
                               store = new
                               {
                                   type = "memory"
                               }
                           }
                       }
                   };

**Comment by clintongormley** [comment]
Be aware the memory indices have been removed in 2.0
