### ISSUE TITLE
XContentBuilder.writeValue() serializes java.math.BigDecimal as String

### ISSUE THREAD

**Issue by nickivanov** [elastic/elasticsearch#12385]
When adding documents to the index that are represented by `Map<String, Object>`, and the documents contain instances of `java.math.BigDecimal` or `java.math.BigInteger`, they are serialized as strings, and are subsequently mapped by Elasticsearch to string fields.
Although `java.math.BigDecimal` and `java.math.BigInteger` are supported by Jackson, `XContentBuilder.writeValue()` defaults to represent these data types as strings.

**Comment by clintongormley** [comment]
Lucene currently has no support for BigInteger/Decimal.

Closing in favour of https://github.com/elastic/elasticsearch/pull/5683
