### ISSUE TITLE
ElasticsearchIllegalArgumentException when _only_nodes is used as a search preference

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#12389]
I can reproduce this using REST and Java API + ES 1.7.0

The following works:

GET /_search?explain&preference=_only_node:6qdURxYySpCWugwxuvIH3g

The following throws the error:

GET /_search?explain&preference=_only_nodes:pod:A

```
{"error":"ElasticsearchIllegalArgumentException[no Preference for [_only_nodes]]","status":400}
```

I am able to workaround this by using the ENUM value from org.elasticsearch.cluster.routing.operation.plain.Preference directly:

The following works:
GET /_search?explain&preference=ONLY_NODES:pod:A

_only_nodes should work just like _only_node (and not require using the ONLY_NODES enum)?

**Comment by nirmalc** [comment]
its broken in 1.7 as "_only_nodes" is not parsed to right preference. (
Preference.java - parse )

Thanks
Nirmal

**Comment by clintongormley** [comment]
@nirmalc want to send a fix?

**Comment by nirmalc** [comment]
@clintongormley , will look at it today and send fix.  I think its minor  merge issue with 1.7 tree

**Comment by nirmalc** [comment]
@ppf2 - using enum directly doesnt actually work ; its considering preference as custom string value probably. we consider it as custom preference if preference value begins with "_"

**Comment by ppf2** [comment]
@nirmalc yah you are right, was testing with just 2 nodes, so it appeared that it worked with ONLY_NODES when switching the node attributes but in fact it was just treating them as custom routing values.  Thx for submitting the fix :+1:

**Comment by spinscale** [comment]
Closed by https://github.com/elastic/elasticsearch/commit/2fa7404c129b9406d98821acfc7dec7ab1e2a3a7
