### ISSUE TITLE
Leading space breaks YML parsing

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#12382]
If you accidentally manage to place a leading space in front of a YML setting in `elasticsearch.yml`, then all follow-on settings will be silently ignored.

```
 cluster.name: my-cluster
 other.setting: xyz

# The rest is ignored
name.node: my-node
```

If you turn around and start the node, then it fails to recognize the `node.name` without any error:

```bash
$ bin/elasticsearch
[2015-07-21 11:43:08,883][INFO ][node                     ] [Screaming Mimi] version[1.6.0], pid[35094], build[cdd3ac4/2015-06-09T13:36:34Z]
[2015-07-21 11:43:08,883][INFO ][node                     ] [Screaming Mimi] initializing ...
```

**Comment by clintongormley** [comment]
This should throw an inconsistent indentation error.  Not sure if this is our parsing or Jackson that has th issue

**Comment by jasontedor** [comment]
@clintongormley It's our issue. We parse until we reach an end object token. The YAML spec requires that all sibling nodes be at the same indentation level. Once the indentation is reduced in the example that @pickypg gave, a YAML parser that parses according to the spec will return an end object token and we will stop parsing. Therefore, to solve this we should just ensure that when we encounter an end object token while parsing settings, we are in fact at the end of the settings stream. I've submitted PR #12451 to do this.
