### ISSUE TITLE
 nested: ElasticsearchIllegalArgumentException[found no fielddata type for field [location]]

### ISSUE THREAD

**Issue by defineconst** [elastic/elasticsearch#12392]
{
   "geospatial": {
      "mappings": {
         "gis_basic": {
            "properties": {
               "id": {
                  "type": "string"
               },
               "location": {
                  "properties": {
                     "lat": {
                        "type": "double"
                     },
                     "lon": {
                        "type": "double"
                     }
                  }
               }
            }
         }
      }
   }
}

**Comment by defineconst** [comment]
rror": "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[LZphOkj4SpaJMTldwumuWw][sooilspatial][0]: SearchParseException[[sooilspatial][0]: query[ConstantScore(GeoBoundingBoxFilter(location, [40.8, -74.1], [40.4, -73.7]))],from[-1],size[-1]: Parse Failure [Failed to parse source [{



nested: ElasticsearchIllegalArgumentException[found no fielddata type for field [location]]; }{[LZphOkj4SpaJMTldwumuWw][sooilspatial][4]: SearchParseException[[sooilspatial][4]: query[ConstantScore(GeoBoundingBoxFilter(location, [40.8, -74.1], [40.4, -73.7]))],from[-1],size[-1]: Parse Failure [Failed to parse source [{\n  \"query\": {\n    \"filtered\": {\n      \"filter\": {\n        \"geo_bounding_box\": {\n          \"location\": {\n            \"top_left\": {\n              \"lat\": 40.8,\n              \"lon\": -74.1\n            },\n            \"bottom_right\": {\n              \"lat\": 40.4,\n              \"lon\": -73.7\n            }\n          }\n        }\n      }\n    }\n  },\n  \"aggs\": {\n    \"new_york\": {\n      \"geohash_grid\": {\n        \"field\": \"location\",\n        \"precision\": 5\n      }\n    }\n  }\n}\n]]]; nested: ElasticsearchIllegalArgumentException[found no fielddata type for field [location]]; }]",
   "status": 400
}

**Comment by defineconst** [comment]
Who Can Help Me

**Comment by dadoonet** [comment]
Please use discuss.elastic.co for such questions.

Probably you need to define a geo_point here: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-geo-point-type.html
