### ISSUE TITLE
Cryptic error message when mis-spelling a field in geo-distance aggregation

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#12391]
Request:
```js
GET _search
{
   "aggs": {
      "nested_geodistance": {
         "nested": {
            "path": "addresses"
         },
         "aggs": {
           "per_ring": {
             "geo_distance": {
               "field": "addresses.location",
               "unit": "km",
               "orgin": {
                 "lat": 56.78,
                 "lon": 12.34
               },
               "ranges": [
                 {
                   "from": 100,
                   "to": 200
                 }
               ]
             }
           }
         }
      }
   }
}
```

Note that `origin` field is mis-spelt as `orgin`. The error that comes back in the response is:

```
{
   "error": {
      "root_cause": [
         {
            "type": "search_parse_exception",
            "reason": "Unexpected token START_OBJECT in [per_ring].",
            "line": 11,
            "col": 28
         }
      ],
      "type": "search_phase_execution_exception",
      "reason": "all shards failed",
      "phase": "query",
      "grouped": true,
      "failed_shards": [
         {
            "shard": 0,
            "index": ".scripts",
            "node": "IzyWUpmzTbmgk1L8LDCRhQ",
            "reason": {
               "type": "search_parse_exception",
               "reason": "Unexpected token START_OBJECT in [per_ring].",
               "line": 11,
               "col": 28
            }
         }
      ]
   },
   "status": 400
}
```

This is very confusing and doesn't actually point to the error. We should improve this

**Comment by HarishAtGitHub** [comment]
FYI: Just now started working on this .... Will record my observations soon .

**Comment by HarishAtGitHub** [comment]
made a pull request : https://github.com/elastic/elasticsearch/pull/12971

Note : The problem will go away here  geo distance . But will be present in a number of other parsers.

may be  each other parser can be fixed as and when some one reports.(as the number of locations depending in token variable is huge)

**Comment by xuzha** [comment]
I think we just need to print fieldname to keep consistency with other exceptions.

**Comment by HarishAtGitHub** [comment]
Hi Friend @xuzha , 

that is what has been done ..
my PR takes care of 
1) what u said
2) REMOVING the unnecessary CRYTIC parts in the message that distracts users.
3) changing the message into a READABLE one
4) changing all the places in that Geo Distance where such error can occur in future. and changing all into readable one. (with a NOTE: in the commit msg stating wherelse it can occur)
5) also reusing some redundant code.


By the way,
comments or new opinions can be given as new review comments and not new PR's ....
this statement is made by me with the thinking that "We are all working as a team . So we should not allow wasting time working on issues others are already working on. If N people work on a project and N people raise PR's on the same issue I feel that it is a waste of time" .

Happy Learning,
Thanks, it was just my opinion given to my friend.
