### ISSUE TITLE
Bloom filter setting still recognized in post-ES 1.5

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#12390]
Even though bloom filters have been removed from product (https://github.com/elastic/elasticsearch/issues/8571) in 1.5.0, its setting is still recognized by index settings today (ES 1.7.0):

To repro:

Create an index "test"
Close the index

```
PUT /test/_settings
{
  "index": {
    "codec": {
      "bloom": {
        "load": "true"
      }
    }
  }
}
```

Open the index, and the setting is "accepted":

```
{
   "test": {
      "settings": {
         "index": {
            "creation_date": "1437518044482",
            "codec": {
               "bloom": {
                  "load": "true"
               }
            },
...
...
```

**Comment by colings86** [comment]
@ppf2 I think this is because the index settings are not validated so that plugins can add their own settings? So this setting is probably silently ignored.

Not necessarily saying that means it's ok, but it at least provides an explanation.

**Comment by ppf2** [comment]
Yah, I already checked with @mikemccand previously and he has confirmed that there is no such thing as enabling bloom filters post 1.5, so this is just for us to do some clean up on the settings side, thx!

**Comment by clintongormley** [comment]
Closing in favour of #6732
