### ISSUE TITLE
Term indexed as stemmed version but not available when searching

### ISSUE THREAD

**Issue by apanimesh061** [elastic/elasticsearch#12405]
I have term `accused` where during indexing I apply a `porter stemmer` which converts it to `accus`. But when I search this term I get zero hits! I know in which document `accused` occurs so I request a `term_vector` of that document and in that `term_vector` I had an entry of `accus`!!

Why is this happening?

**Comment by clintongormley** [comment]
Hi @apanimesh061 

You haven't provided any JSON so it is quite difficult to guess what you are doing.  This sounds like user error.  I suggest asking the question (with supporting JSON) on the forum: https://discuss.elastic.co/
