### ISSUE TITLE
Filtering on a deeper nested object within a nested aggregation

### ISSUE THREAD

**Issue by hisuwh** [elastic/elasticsearch#12410]
There might be some technical reason why this can't work.
But I feel like this is a bug.  For example:

```

{
   "aggs": {
      "nested_aggregation": {
         "nested": {
            "path": "Applications"
         },
         "aggs": {
            "deeper_nested_filter": {
               "filter": {
                   "nested": {
                      "path": "Applications.CheckItems",
                      "filter": {
                          "term": {
                             "Applications.CheckItems.CheckType": "somechecktype"
                          }
                      }
                   }
               }
            }
         }
      }
   }
}

```

I realise I could do another nested aggregation onto checkitems, filter on check type and reverse nest back up.  That works for this simple example.

What I actually want to do is filters where an application only has certain check types, and the only way to do this is from the context of the application.

**Comment by clintongormley** [comment]
I tend to agree with you.  @martijnvg what are your thoughts?

**Comment by martijnvg** [comment]
@hisuwh @clintongormley When developing  `nested` / `reverse_nested` agg my thoughts around nesting is that aggs should be used for this and not filters, it is aggs not query... but I've seen this usage before and I think we should change it, it makes the aggs itself easier.

There is an technical issue that needs to be fixed first and then these kinds of aggs should work:
https://github.com/elastic/elasticsearch/issues/11749#issuecomment-114034328

**Comment by hisuwh** [comment]
Any progress on this? Just ran up against this again.
Main problem is that I'm using the filters aggregation to create multiple filters.

The only other way to do this is to have multiple aggregatoins but this is going to get a lot more complicated.

**Comment by hisuwh** [comment]
What I have had to (which I personally think is horrible)

'''

{
   "aggs": {
      "applications": {
         "nested": {
            "path": "Applications"
         },
         "aggs": {
            "another_aggregation": {
               "filter": {
                  "term": {
                     "Applications.SomeFlag": true
                  }
               },
               "aggs": {
                  "checkitems": {
                     "nested": {
                        "path": "Applications.CheckItems"
                     },
                     "aggs": {
                        "adverseFinancial": {
                           "filter": {
                              "term": {
                                 "Applications.CheckItems.CheckTypeHierarchy": "adversefinancialcheck"
                              }
                           },
                           "aggs": {
                              "backToApplications": {
                                 "reverse_nested": {
                                    "path": "Applications"
                                 },
                                 "aggs": {
                                    "in_date_range": {
                                       "filter": {
                                          "range": {
                                             "Applications.FinishHistoryItem.When": {
                                                "lte": "2015-06-02T00:00:00.000",
                                                "gt": "2015-01-01T00:00:00.000"
                                             }
                                          }
                                       }
                                    }
                                 }
                              }
                           }
                        }
                     }
                  }
               }
            }
         }
      }
   }
}

'''
