### ISSUE TITLE
_search option limiting returned hits to only top scorers 

### ISSUE THREAD

**Issue by jeantil** [elastic/elasticsearch#12413]
Hello, 

I have tried searching for this feature through the doc, issues and mailing list but couldn't find it, I apologize if I missed something. 
The only parameter I could find to limit the number of returned hits is the size parameter but we can't know in advance how many hits will have the top score for a given query, 

In order to limit the amount of processing and network traffic for some of our requests I would like to only get the top scoring hits highlighted and returned, we discard anything which doesn't have the top score anyway. 

This new parameter can be either a boolean (only the top scoring hits) or maybe an int (the hits for the `n` top scores), not sure which param makes the most sense.

I am thinking of something like : 
````
GET index/type/_search
{
 "topScorers": true,
 "query": {"match": {
   "name": "the quick brown fox"
 }} 
} 
# OR
GET index/type/_search
{
 "topScorers": 3,
 "query": {"match": {
   "name": "the quick brown fox"
 }} 
} 
```

I am also definitely not sure about the parameter name

**Comment by clintongormley** [comment]
Hiya

We discussed this in our FixItFriday session and we're against adding this feature.  It feels very use case specific.  If the top 6 documents all have the same score and the 7th is 0.0001 less, is that sufficient to truncate the result list?  For you maybe, but somebody else will want a different behaviour.  You could of course get back a million top-scoring documents, so either way this needs to be limited by `size`.

You could write a custom plugin that does this for you, but I don't think this is a feature we want in core.

thanks

**Comment by jeantil** [comment]
Hello, 

Thanks for your answer. 
> If the top 6 documents all have the same score and the 7th is 0.0001 less, is that sufficient to truncate the result list
Yes, the idea was to select exactly the hits which have the exact score reported by the max_score property on hits.

A pointer on a plugin which interfaces/extends the same modules I would need to extend would be really nice.
I have a very shallow knowledge of the ES code base and have absolutely no idea where to start (apart from setting up the maven project with the couple property files for a plugin) 

Google hasn't been very forthcoming with such a pointer : lots of stuff around adding an analyzer, creating a REST endpoint or extending the infrastructure but not so much seems to extend the search result processing 

thanks

**Comment by jeantil** [comment]
I tried to have a look at the code base: 
I would need to extend the search context to add my custom property but it sounds like I would then have to reimplement all three of DefaultSearchContext, FilteredSearchContext and PercolateContext
once I have the property at hand in the context, I would need to create a custom QueryPhase override its execute method call the super then manipulate the  topdocs in the queryResult to limit the score docs to only the docs with the max score. 

is that viable ?

thanks

**Comment by clintongormley** [comment]
Hi @jeantil 

I suggest asking about this in the forum: http://discuss.elastic.co/
