### ISSUE TITLE
CI: testCorruptedShards fails sporadically 

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#12416]
http://build-us-00.elastic.co/job/es_core_master_metal/10479/testReport/junit/org.elasticsearch.action.admin.indices.shards/IndicesShardStoreRequestTests/testCorruptedShards/

```
expected null, but was:<ElasticsearchException[/home/jenkins/workspace/es_core_master_metal/core/target/J2/temp/org.elasticsearch.action.admin.indices.shards.IndicesShardStoreRequestTests_A587044FC4F41BF6-001/tempDir-003/data/TEST-slave19.build.ci.hetz.es.io-CHILD_VM=[2]-CLUSTER_SEED=[-6063786116933768492]-HASH=[715B7D4EEE90F3]-cluster/nodes/0/indices/test/4/_state/state-2.st]; nested: NoSuchFileException[/home/jenkins/workspace/es_core_master_metal/core/target/J2/temp/org.elasticsearch.action.admin.indices.shards.IndicesShardStoreRequestTests_A587044FC4F41BF6-001/tempDir-003/data/TEST-slave19.build.ci.hetz.es.io-CHILD_VM=[2]-CLUSTER_SEED=[-6063786116933768492]-HASH=[715B7D4EEE90F3]-cluster/nodes/0/indices/test/4/_state/state-2.st];>
```

**Comment by clintongormley** [comment]
@areek @bleskes is this still relevant?

**Comment by bleskes** [comment]
this is so long ago and we didn't research (or at least, not analysis here). I will close this and reopen when it and if it surfaces again. Please reopen if anyone disagrees

**Comment by DaveCTurner** [comment]
The offending test was marked `@AwaitsFix` in July 2015 so hasn't been running for a while. Can it be reinstated?

**Comment by jasontedor** [comment]
Let's remove the awaits fix and see what happens? And close this issue and open a new one if we find out there are problems.

**Comment by DaveCTurner** [comment]
Ok, I did so and saw no failures for ~30 iterations, so pushed it as 29c5540323.

**Comment by ywelsch** [comment]
.... and it's failing:
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu/1746/consoleFull
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/4888/console

**Comment by DaveCTurner** [comment]
Ok, I reverted 29c5540 in 1f89e9d94e69d9a1cd480aad3f8b0a2cf68a4217 and will have a deeper look.

**Comment by DaveCTurner** [comment]
I pushed 92a24de509f388df4f569fe9576d60f0697d3beb to get some more details of the failures.

**Comment by DaveCTurner** [comment]
This test failed in https://elasticsearch-ci.elastic.co/view/Elasticsearch/job/elastic+elasticsearch+master+intake/912/ with the new logging, so `@AwaitsFix` reinstated in 1e6bd99248.

**Comment by DaveCTurner** [comment]
Seems to be a race condition in the test. It seems to reliably fail locally with this addition: https://github.com/DaveCTurner/elasticsearch/commit/608b45275301de3ed73dd9bf2e842fac0c953685.

I think it's that `failAndRemoveShard` is called asynchronously...

https://github.com/elastic/elasticsearch/blob/95bcee56c42dc457c4157e51b7277d99d43a666a/core/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java#L707-L715

... and the test sometimes checks the shard state before this has completed.
