### ISSUE TITLE
Use underscores instead of camel-casing for date formats

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12429]
The date formats stand out as one of the few place we use camel casing, eg `strictDateOptionalTime`

These should be changed to `strict_date_optional_time` etc

**Comment by metadave** [comment]
@clintongormley It looks like the formats have been updated in the [Joda](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/joda/Joda.java#L55..L218) class already, is this simply changing tests and docs to reflect these changes?

**Comment by clintongormley** [comment]
@metadave It's the stringification which defaults to camelcase.  Try:

    PUT my_index/my_type/1
    {
      "date": "2007-01-01T01:00:00Z"
    }

    GET my_index/_mapping

Don't worry about the docs, I'm reworking those in a bigger change
