### ISSUE TITLE
setRoutingService change breaks discovery plugins in 1.7

### ISSUE THREAD

**Issue by mkliu** [elastic/elasticsearch#12428]
This change 

https://github.com/elastic/elasticsearch/commit/182c59f5b46d3a666d21ba369452844220736a72 

is breaking existing discovery plugins and may scare people away from upgrading to 1.7. I've put comments on that pull request too.

While the fix is easy but it worries me about ES's upgrading philosophy as I'm not expecting API changes in minor version upgrades. 

I've already fixed my plugin so I'm good now, just want to bring this up to your attention.

**Comment by bleskes** [comment]
As we already discussed on the commit, we don't guarantee BWC on the internal APIs. We do try, where possible to maintain it and way pros against the cons. This is such a minor change that I don't think it's a problem to upgrade any plugin. I'm going to close for now...
