### ISSUE TITLE
After disk allocation hi-watermark hit, freeing disk space does not cause automatic reallocation of new UNASSIGNED shards

### ISSUE THREAD

**Issue by nellicus** [elastic/elasticsearch#12422]
reproduced on 1.7.0

steps in short

1) start 2 nodes cluster on same host
2) create huge file to cause disk to be >95% full (high disk allocation watermark hit)
3) create new index with one doc
4) index is created with UNASSIGNED shards
5) remove huge file to go below disk allocation thresholds
6) shards sit in UNASSIGNED (waited 10m)
7) a manual reroute is required to have them reassigned

steps
https://gist.github.com/nellicus/8a7f5a70160346b76237

debug logs
https://gist.github.com/nellicus/c779113544c5f44f6d18

output of cat shards / cluster health during repro
https://gist.github.com/nellicus/b3744dfd85b1343fd944

**Comment by clintongormley** [comment]
When a node goes from high-watermark -> low-watermark, we should issue a reroute.
