### ISSUE TITLE
S3 client retry logic 

### ISSUE THREAD

**Issue by xuzha** [elastic/elasticsearch#12434]
From my understanding, we are using default exponential backoff policy for S3 client and we make max number of retries configurable, and we also pass this number into our S3 client when we creating it ( I don't think we should do it [here](https://github.com/elastic/elasticsearch/blob/4c981ff4bfc250080d521af105b5e8589c9fc517/plugins/cloud-aws/src/main/java/org/elasticsearch/cloud/aws/InternalAwsS3Service.java#L126).

So for example, if user put 3 for max number of tries into the setting, aws java client will do 3 times retries for us (hopefully) . AND PLUS, during doing snapshot, we would do another 3 times [retries](https://github.com/elastic/elasticsearch-cloud-aws/blob/master/src/main/java/org/elasticsearch/cloud/aws/blobstore/S3BlobContainer.java#L86) at our side if we got retryable exception, which is 9 retryies. If we put 5, the total number of retry would become 25? 

Personally, I think this is a bug.

**Comment by clintongormley** [comment]
As I understand it, S3 retries when there is a timeout, while our own retries happen if there is a 404.  So the only way you'd get 3 * 3 retries is if all 2 S3 requests timed out, then the third returned a 404, and the same pattern is repeated for the next 3 attempts.

**Comment by xuzha** [comment]
Yes. AWS client only do retry for their retryable task. 
That's why we shouldn't change the default 3 times retry setting when we init S3 client.

**Comment by clintongormley** [comment]
@dadoonet @imotov any thoughts on this?

**Comment by imotov** [comment]
I agree it looks like we have two essentially different settings (blob-level max retry count and client level max retry count) and we use the same that same repository setting to control both. I think should at least add an ability to specify them separately.

**Comment by tlrx** [comment]
Retries have been removed in #23952 so I'm closing this one.
