### ISSUE TITLE
support new `host_type=rdma` option

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#12449]
From https://github.com/elastic/elasticsearch-cloud-azure/issues/41 by @ppf2:

> Would like to see support for a `host_type` similar to what we have for the AWS plugin.  For azure, it can be one of the following types:
> - `private_ip`
> - `public_ip`
> - `RDMA` (http://blogs.technet.com/b/windowshpc/archive/2014/01/30/new-high-performance-capabilities-for-windows-azure.aspx)
> 
> It will also be nice for it to default to use the better performing RDMA connection and fall back to `private_ip` if none is provided.

**Comment by DaveCTurner** [comment]
@dadoonet I don't understand what, if any, action is needed here, particularly in terms of the `:Distributed/Discovery` label (which probably wasn't what it was called when you labelled it back in 2015). RDMA is an alternative to using TCP as the inter-node communications mechanism, so perhaps this should be `:Core/Network`?

**Comment by dadoonet** [comment]
If I understood correctly and my memory recalls it well, RDMA is like a specific network card which is available on some specific VMs on Azure (running on Windows only).

So the goal here was to use this specific card (and its associated IP address) and use it as the address we want to bound elasticsearch to. So we can benefit from a faster communication between nodes hopefully.

**Comment by DaveCTurner** [comment]
Ok, the address to which we bind is in scope for `:Core/Network` so I think it's right to add that label; @elastic/es-core-infra please feel free to remove or otherwise modify this issue.

**Comment by jasontedor** [comment]
I do not see a compelling case to add support for RDMA as the technology has limited acceptance and usage. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).

**Comment by Leaf-Lin** [comment]
+1
