### ISSUE TITLE
Delayed allocation "stuck" on 0 shards

### ISSUE THREAD

**Issue by alexbrasetvik** [elastic/elasticsearch#12456]
Upgraded from 1.6.1, a 1.7.0 node joins, we use allocation excludes to force data away from the nodes we intend to stop. When the 1.7.0 node has all the data, the old node is stopped.

1.7.0 becomes the master, then logs "delaying allocation for [66] unassigned shards, next check in [59.6s]". 22 *minutes* later, it then starts logging "delaying allocation for [0] unassigned shards, next check in [0s]" forever.

We had another cluster doing the same, which stopped logging it after two more nodes joined the cluster.

NTP enabled, clocks seem fine, drift not out of the ordinary.

**Comment by clintongormley** [comment]
@kimchy any ideas?

**Comment by dakrone** [comment]
@alexbrasetvik does this problem persist when the entire cluster is running 1.7.0, or does it only occur when the cluster is in a mixed-version state?

**Comment by alexbrasetvik** [comment]
It happens also for clusters created with 1.7.0.

**Comment by dakrone** [comment]
@alexbrasetvik I was able to reproduce this, still trying to figure out what causes it

**Comment by mkliu** [comment]
I see this multiple times too. Besides the logging itself, actually it never allocates my unassigned shards. I have a 20 machine cluster, all on 1.7 already. I shutdown a node via kopf. I see ~100 unassigned shards. The node then joins the cluster again, it's not initializing the unassigned shards. 

I manually reroute one unassigned shard, then i start seeing the cluster initializing the other unassigned shards.
