### ISSUE TITLE
Unable to open a node when you install marvel on the new beta version

### ISSUE THREAD

**Issue by vvalleru** [elastic/elasticsearch#12459]
I build the elasticsearch-2.0.0-beta1-SNAPSHOT using maven. I did start a node and it works fine. But when i do the same after installing marvel I get an exception.

I used ./bin/plugin -i elasticsearch/marvel/latest to install marvel. Please see the following screenshot for reference.
![screen shot 2015-07-24 at 11 06 18 pm](https://cloud.githubusercontent.com/assets/5770196/8887648/1c1ea472-3259-11e5-9833-f4ad635ff19c.png)

**Comment by markwalkom** [comment]
I don't think current Marvel releases are compatible with 2.0.
I'd expect that we will release a version to go with the GA.

**Comment by clintongormley** [comment]
Correct  - closing
