### ISSUE TITLE
Add new `public` option for containers

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#12450]
From https://github.com/elastic/elasticsearch-cloud-azure/issues/58:

> When we create a container using Java API, we can easily make it public:
> 
> ``` java
> BlobContainerPermissions containerPermissions = new BlobContainerPermissions();
> containerPermissions.setPublicAccess(BlobContainerPublicAccessType.CONTAINER);
> container.uploadPermissions(containerPermissions);
> ```
> 
> So we could add an option to the repository such as `"public": true` (default to `false`), so people would be able to share their data using a public read-only URL.

**Comment by tlrx** [comment]
We don't create Azure container anymore (see #22858)
