### ISSUE TITLE
Support field exclusion in alias

### ISSUE THREAD

**Issue by felipegs** [elastic/elasticsearch#12453]
Hi, I have same question of this user, why it not works?

http://stackoverflow.com/questions/26349705/how-to-create-elasticsearch-index-alias-that-excludes-specific-fields

**Comment by clintongormley** [comment]
Because it is not supported, and the documentation doesn't imply that it should work. You could use templated search requests to achieve something similar instead.

**Comment by felipegs** [comment]
This could be, in my opinion, a good feature, to secure some data with alias

Thanks
