### ISSUE TITLE
Rename `lat_lon` to `index` on geo-points

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12464]
The `lat_lon` option on geo-point indexes the lat and lon values in the inverted index.  For consistency's sake, it should be renamed to `index`.

**Comment by clintongormley** [comment]
@nknize what do you think?

**Comment by nknize** [comment]
I'm afraid it might add confusion once  the enhancement/LuceneGeoPointField_Integration feature branch is merged (was planning for 2.0_beta). This enhancement automatically indexes geo_point types using the new Lucene GeoPointFieldType. I had intended to keep the lat_lon option (for the time being) for bwc but eventually remove it. For consistency I can use the 'index' option to let users turn off the default indexing behavior?

**Comment by clintongormley** [comment]
This new field will still be `geo_point`?  If so, and you're planning on removing the `lat_lon` option anyway, then leave it as is.

**Comment by clintongormley** [comment]
No longer relevant
