### ISSUE TITLE
Add line feed to responses

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#12469]
There are a number of API responses that don't come back with a line feed, which messes up CLI actions. Here's one such example;
```
$ curl -uadmin 0:9200
Enter host password for user 'admin':
{"error":"AuthenticationException[unable to authenticate user [admin] for REST request [/]]","status":401}$
```
And it's pretty common.

Can we make sure we add a `\n` to everything to increase readability?

**Comment by dadoonet** [comment]
IIRC if you add ?pretty then a line feed is added. Would this work for you?

**Comment by clintongormley** [comment]
Agreed - API default outputs are for computers.  Use pretty for readable responses
