### ISSUE TITLE
Provide a script or command to recover red cluster after data loss

### ISSUE THREAD

**Issue by ofir-petrushka** [elastic/elasticsearch#12466]
Assuming a user can get into a red cluster after losing data, allow some easy way to accept the data loss and return the cluster into a working state.

Currently, it's done with some ugly scripts (or complete cluster destroy and rebuild) that take a long time and are sub-optimal like:
https://t37.net/how-to-fix-your-elasticsearch-cluster-stuck-in-initializing-shards-mode.html

Would be good if it's in an API that plugins like kopf, HQ etc will later allow one click fix.

**Comment by clintongormley** [comment]
Closing in favour of #4285
