### ISSUE TITLE
Wildcard searching on not analyzed fields

### ISSUE THREAD

**Issue by vineet85** [elastic/elasticsearch#12468]
Related to Issue #9973

I'm noticing wildcard searching is not working on not_analyzed fields or keyword analyzer analyzed fields

For Eg:-

PUT /exactsearchindex
{
    "mappings": {
        "my_type": {
          "properties": {
                "text": {
                  "type": "string",
                  "index": "not_analyzed"
          }
        }
    }
}
}

POST /exactsearchindex/my_type/_bulk
{ "index": { "_id": 1 }}
{ "text": "The quick fox jumping over the walls." }
{ "index": { "_id": 2 }}
{ "text": "Cats overboard casting." }

POST /exactsearchindex/_search
{
  "query": {
    "query_string": {
      "analyze_wildcard": true, 
      "query": "cats ov*",
      "fields": ["text"]
}
}
}

The above search does not return any results. Am I missing something?

**Comment by nik9000** [comment]
Maybe it's case getting to you. Try adding a lowercase filter after the
keyword.

**Comment by vineet85** [comment]
Tried the same search above with the keyword tokenizer and lowecase filter:-
PUT /exactsearchindex
{
  "settings": {
        "analysis": {
            "analyzer": {
                "keylower": {
                    "type": "custom",
                    "tokenizer": "keyword",
                    "filter": ["lowercase"]
                }
            }
        }
    },
    "mappings": {
        "my_type": {
          "properties": {
                "text": {
                  "type": "string",
                  "analyzer": "keylower"
          }
        }
    }
}
}

I am able to find Cats* as below
POST /exactsearchindex/_search
{
  "query": {
    "query_string": {
      "query": "Cats*",
      "fields": ["text"]
}
}
}

But the movement the whitespace is introduced it does not work:-
POST /exactsearchindex/_search
{
  "query": {
    "query_string": {
      "query": "Cats overboard*",
      "fields": ["text"]
}
}
}

**Comment by nik9000** [comment]
Ah! The trouble is query_string. It always always segments on spaces. Use
the prefix query instead.

Sorry about that!

**Comment by vineet85** [comment]
Figured out the problem. Thanks for your suggestions
