### ISSUE TITLE
Geohash is not indexed unless the precision is 12

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12467]
If the `geohash_precision` is set to anything except the default (12), and `geohash_prefix` is not true, the geohash is not indexed:

    PUT my_index
    {
      "mappings": {
        "my_type": {
          "properties": {
            "location": {
              "type": "geo_point",
              "geohash": true,
              "geohash_precision": 11
            }
          }
        }
      }
    }
    
    
    PUT my_index/my_type/1
    {
      "location": {
        "lat": 41.12,
        "lon": -71.34
      }
    }
    
    GET my_index/_search?fielddata_fields=location.geohash

**Comment by nknize** [comment]
This is a silly mappings refactor mistake... the bigger issue is that we didn't have a test for catching this. I'll backport and make sure there's sufficient test coverage.

**Comment by nknize** [comment]
Merged #13649
