### ISSUE TITLE
Empty results beyond 10 pages with rescore query

### ISSUE THREAD

**Issue by parthibane** [elastic/elasticsearch#12477]
Hi, 

we've recently implemented rescore to rank docs, I'm getting empty results when I go beyond 10 pages. if I remove rescore from my DSL query it's returning results. So something happening when paginating with rescore. 

For example,  let say my search DSL query has "size" is 1 and "from" is 0. It's returning results until "from"  is  10,  beyond 10 it's returning empty results. 

Elasticsearch version : 1.5.2 

Please check  this issue. 

My sample DSL query for 11th page 

{
  "_source": ["name","id"  ],
  "query": {
    "query_string": {
      "query": "any keyword",
      "fields": ["_all"]
    }
  },
  "from": 11,
  "rescore": {
    "query": {
      "rescore_query": {
        "function_score": {
          "script_score": {
            "script":"[my script]",
            "lang": "groovy"
          }
        }
      },
      "score_mode": "multiply"
    },
    "window_size": 300
  }, "size": 1
}

Sample result for 11th page 

{
"took": 21,
"timed_out": false,
"_shards": {
"total": 11,
"successful": 11,
"failed": 0
},
"hits": {
"total": 14021,
"max_score": 1,
"hits": [ ]
}
}

**Comment by nik9000** [comment]
You are going to have more luck if you can post a curl recreation.

**Comment by clintongormley** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/11342
