### ISSUE TITLE
Cleanup unit tests in GatewayMetaStateTests and add test for closed indices

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#12475]
In https://github.com/elastic/elasticsearch/pull/11666 we found a bug in GatewayMetaState when indices are closed and opened, see e44c5ff70384751bfa9bd5224183c1bc8c68daa0 . But we added no unit test for it. Also, GatewayMetaStateTests can probably be simplified. The current way to create a cluster state is a mess.

**Comment by brwe** [comment]
closed by #11666

**Comment by brwe** [comment]
no it is not...

**Comment by bleskes** [comment]
Closing as this is as a lot have changed around index deletion  and importing of deleted indices. I don''t think there's any point of chasing it down.
