### ISSUE TITLE
Add support for DFS_SCAN search type

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#12470]
If you use `track_scores=true` and `search_type=scan`, then there is no way to get the improved term frequencies for improved scoring like you can with `search_type=dfs_query_then_fetch`.

This is admittedly an uncommon use case, given that scores are disabled by default for scoring and sorting is always disabled, but for scenarios where granularity is important, then it is a small hole.

In terms of the proposed solution:

#### Problem

There is no `SearchType.DFS_SCAN` option.

#### Solution

Provide the option and perform the traditional DFS lookup. _If_ `track_scores` is not enabled, then revert to normal `SearchType.SCAN`.

#### Workaround

None that I am aware of.

**Comment by clintongormley** [comment]
Scanning doesn't support scoring, so the DFS option is meaningless.  If you need scoring, use scrolling without scanning.  It no longers suffers from the issues with deep paging that exists with high `from` values

**Comment by pickypg** [comment]
Related to #12486. Using scroll is definitely the way to achieve this and it can be combined with `dfs_query_then_fetch`.
