### ISSUE TITLE
Make hidden file detection not rely on the OS environment

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#12480]
We use Files.isHidden in some places already to detect hidden files, but this has the downside to depend on the operating system. Instead we should do something simple like startsWith(".").

See #12465 for more background.

**Comment by rmuir** [comment]
Using isHidden, might as well have a if (WINDOWS) in the code, because it will behave differently on the environment. It prevents simple unit testing, it means things will be harder to debug, etc.

**Comment by Helen-Zhao** [comment]
Should this issue be closed? The referenced PR #12465 references #12484 which appears to resolve the issue.

**Comment by jasontedor** [comment]
Closed by #12484
