### ISSUE TITLE
Elasticsearch shards sporadically failing when running queries against an alias that includes a filter

### ISSUE THREAD

**Issue by kristianholmsejersen** [elastic/elasticsearch#12483]
I am currently running an Elasticsearch v.1.6 setup with two nodes, and an index with 5 shards. To this index, I have added an alias that contains a reference to my index, as well as a Groovy script filter that helps avoiding documents with invalid start and end dates. The alias looks like this:
```JSON
"MyIndex" : {
   "aliases": { 
       "MyIndex_alias": { 
            "filter" : {
                "script":{ 
                    "script":
                        "\r\n entryDate = doc['availability.start'].date.getMillis();
                         \r\n exitDate =  doc['availability.end'].date.getMillis();
                         \r\n rightNow = DateMidnight.now().getMillis();
                         \r\n\r\n if (entryDate < rightNow && exitDate > rightNow)\r\n {
                                       \r\n return true;
                             \r\n }
                             \r\n return false;",
                        "lang":"groovy"}}}}}
```

When performing a simple query, such as term * (/MyIndex_alias/my_type/_search?request.q=*), a number of shards will fail the query returning the following message:

```JSON
"failed": 1,
"failures": [
    {
        "index": "MyIndex",
        "shard": 2,
        "status": 500,
        "reason": "RemoteTransportException[[MyESCluster][inet[/10.131.43.61:9301]][indices:data/read/search[phase/query]]]; nested: QueryPhaseExecutionException[[MyIndex][2]: query[ConstantScore(ScriptFilter(
        entryDate = doc['availability.start'].date.getMillis();
        exitDate = doc['availability.end'].date.getMillis();
        rightNow = DateMidnight.now().getMillis();

        if (entryDate < rightNow && exitDate > rightNow)
        {
             return true;
        }
        return false;))],from[0],size[10]: Query Failed [Failed to execute main query]]; nested: GroovyScriptExecutionException[ArrayIndexOutOfBoundsException[null]]; "
    }
]
```

I have already verified the following things:

1. All the documents in my index have valid start and end values, and none of them have a null value.
2. The filter does work on the shards that perform the query successfully
3. The cluster has a green health status
4. The error occurs randomly on shards both in the master and worker nodes
5. The errors do not occur if queries are directed to the index instead of the alias
6. Adding more nodes to the cluster seems to mitigate the problem. Running with 2 nodes usually leaves 2-3 shards failing, while 3 nodes limits the failure to 1-2 shards. Adding a final 4th node leaves the query only failing rarely on a single shard
7. Even when the query succeeds, I sometimes get fewer results than expected, again sporadically
Any help on the matter would be greatly appreciated!
8. Upgrading to Elasticsearch 1.7 doesn't have any effect on the issue

**Comment by clintongormley** [comment]
@martijnvg any ideas here?

**Comment by clintongormley** [comment]
Hi @kristianholmsejersen 

Sorry it has taken a long time to get back to you.  Is this something you're still seeing on ES 2 or ES 1.7.4?

**Comment by clintongormley** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
