### ISSUE TITLE
Feature : 409 option parameter to retrieve the last document version

### ISSUE THREAD

**Issue by jmorille** [elastic/elasticsearch#12482]
The feature request is to add an optional parameter  during document indexing (index, partial update, update) in order to retrieve if an http error 409: Conflict occur.

In the error, add the content of the last version of document in order to permit (without other request) the conflict resolution.

For Example during an update request
```shell
curl -XPUT localhost:9200/test/type1/1?version=24&getOnConflict -d '{
    "counter" : 1,
    "tags" : ["red"]
}'
```

the 409 error is completed by _document that contains the document server version
```shell
{
   "error":"VersionConflictEngineException[[test][2] [type1][1]: version conflict, current [25], provided [24]]",
  "status":409,
  "_document": {
       _id : 1,
      _version: 25,
     _source: {
            "counter" : 7,
            "tags" : ["red"]
     }
  }
}
```

**Comment by clintongormley** [comment]
Hi @jmorille 

Thanks for opening the issue, but this can be done very easily on the client side.   I don't think we should add yet-another-option to the these APIs
