### ISSUE TITLE
How to resolve "unassigned_shards" in elasticsearch

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch#12501]
Hi, 

Nowdays, the health of my cluster is red and my shards they are unasigned:

GET _cluster/health?pretty

and the request is:

{
   "cluster_name": "juan",
   "status": "red",
   "timed_out": false,
   "number_of_nodes": 10,
   "number_of_data_nodes": 9,
   "active_primary_shards": 88,
   "active_shards": 88,
   "relocating_shards": 0,
   "initializing_shards": 0,
   "unassigned_shards": 104
}
------------------------------------------
And I try to recollate the shards:

POST /_cluster/reroute
{
        "commands" : [ {
              "allocate" : {
                  "index" : "logstash-2015.07.28", 
                  "shard" : 2, 
                  "node" : "Robbie Robertson", 
                  "allow_primary" : true
              }
            }
        ]
    }

But I can not do it 

Could somebody giveme any solution?

**Comment by juandasgandaras** [comment]
Hi,

Nowdays, the health of my cluster is red and my shards they are unasigned:

GET _cluster/health?pretty

and the request is:
{
"cluster_name": "juan",
"status": "red",
"timed_out": false,
"number_of_nodes": 4,
"number_of_data_nodes": 3,
"active_primary_shards": 46,
"active_shards": 46,
"relocating_shards": 0,
"initializing_shards": 0,
"unassigned_shards": 136
}

and
GET _cat/allocation?v

shards disk.used disk.avail disk.total disk.percent host ip node

11 8.4tb 1.4tb 9.9tb 85 bc10-05 10.8.5.15 Albion

33 8.4tb 1.4tb 9.9tb 85 bc10-05 10.8.5.15 Mystique

0 0b l8a 10.8.0.231 logstash-l8a-5920-4018
2 8.4tb 1.4tb 9.9tb 85 bc10-05 10.8.5.15 Carolyn Trainer

136 UNASSIGNED

And I try to recollate the shards:

POST /_cluster/reroute
{
"commands" : [ {
"allocate" : {
"index" : "logstash-2015.07.28",
"shard" : 2,
"node" : "Albion",
"allow_primary" : true
}
}
]
}

But I can not do it

Could somebody giveme any solution?

Thanks in advance and sorry by the inconvenience.

**Comment by clintongormley** [comment]
Hi @juandasgandaras 

Please ask questions like these on the forum instead: https://discuss.elastic.co/

If you use the `explain` parameter with the reroute command, it will tell you why it was not possible to allocate the shard.

**Comment by juandasgandaras** [comment]
Thanks.
