### ISSUE TITLE
send_refresh_mapping not working?

### ISSUE THREAD

**Issue by sschepens** [elastic/elasticsearch#12516]
I have set `indices.cluster.send_refresh_mapping: false` to prevent data nodes to send mapping updates to masters.
This worked for a while, but now i have cluster task queue full of update mapping events.
The only thing I have done is upgrade elasticsearch version from 1.4.4 to 1.7.0

**Comment by clintongormley** [comment]
Hi @sschepens 

Sorry for the delay in getting to this.  Did you find a resolution for this issue?  Given the complete mapping rewrite in 2.0, I'm inclined to close this.

**Comment by clintongormley** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
