### ISSUE TITLE
bucket_script should allow user-defined params

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#12517]
Currently, the `bucket_script` pipeline only allows you to inject values that are derived from buckets.  It should also allow a generic `params` hash like other scripting functionality, so that the user can inject per-request variables which are independent of buckets.

E.g. something like this:

```json
"bucket_script": {
  "buckets_path": {
    "mean": "movavg_mean.value",
    "std": "movavg_std.value"
  },
  "params": {
     "sigma": 3
  },
  "script": "mean + (sigma * std)"
}
```

**/cc** @colings86

**Comment by colings86** [comment]
@polyfractal you can do this using the new scripts API in 2.0 try the following:

```json
"bucket_script": {
  "buckets_path": {
    "mean": "movavg_mean.value",
    "std": "movavg_std.value"
  },
  "script": {
    "inline": "mean + (sigma * std)",
    "params": {
       "sigma": 3
    }
  }
}
```

**Comment by polyfractal** [comment]
TIL.  Thanks, didn't realize it could do this!

![image](https://cloud.githubusercontent.com/assets/1224228/8941756/8408491a-353f-11e5-901c-24205e4ae148.png)
