### ISSUE TITLE
Make stats APIs pluggable

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12526]
The stats APIs should have a hook that allows plugins to inject their own statistics.

**Comment by tlrx** [comment]
How does this fit into the current stats APIs? Another stats entry (say `plugins`) similar to `indices`, `os` etc?

Anyway I'll be happy to take this one :)

**Comment by uboness** [comment]
@tlrx personally I don't think we need to have `plugins` or `plugin` as a category. Each plugin should define its own category... so plugin `foo` will register a stats/info source for `foo` category.

**Comment by clintongormley** [comment]
I don't think we need this anymore, so I'll close, for now at least.
