### ISSUE TITLE
can't set doc_values for _type field.

### ISSUE THREAD

**Issue by chenryn** [elastic/elasticsearch#12524]
The reference said that _type field "By default, the _type field is indexed (but not analyzed) and not stored. "
I has a terms aggregation for _type field. so I want to set _type to be doc_values to save fielddata memory. I wrote template as follow:

```
...
        },
        "@version" : {
          "index" : "not_analyzed",
          "doc_values" : true,
          "type" : "string"
        }
      },
      "_type" : {
        "index" : "not_analyzed",
        "doc_values" : true,
        "type" : "string"
      },
      "_all" : {
        "enabled" : true
      }
    }
  },
  "aliases" : { }
}
```

template POST ok, but when I create a new index and GET the mapping, I can't find the _type defination in the mapping. And after sometimes running, I saw the `_type` fielddata memory using grows.

**Comment by xuzha** [comment]
Which version are you using? I think _type is not configurable for now.

**Comment by chenryn** [comment]
@xuzha _type is not configurable for 2.0, I use version 1.6.0 now.

**Comment by xuzha** [comment]
If you are using 1.7 or older versions, that could be possible. As I mentioned before, we locked down meta-fields, details see # [8143](https://github.com/elastic/elasticsearch/issues/8143). And doc-values should be enabled by default for 2.0. I don't know if we should fix this.

**Comment by chenryn** [comment]
oh, I forgot doc_values will be enabled by default for 2.0. thanks.
