### ISSUE TITLE
rpm distribution generates artifact errors

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#12529]
See http://build-us-00.elastic.co/job/es_core_master_regression/2919/console

[ERROR] Failed to execute goal org.codehaus.mojo:rpm-maven-plugin:2.1.3:attached-rpm (attach-rpm) on project elasticsearch-rpm: Execution attach-rpm of goal org.codehaus.mojo:rpm-maven-plugin:2.1.3:attached-rpm failed: For artifact {org.elasticsearch.distribution:elasticsearch-rpm:2.0.0-beta1-SNAPSHOT:rpm}: An attached artifact must have a different ID than its corresponding main artifact. -> 

Looks like its angry that its elasticsearch and not elasticsearch-rpm?

**Comment by spinscale** [comment]
this is triggered by `mvn -Dpackage.rpm`, which in turn triggers a maven profile. As the RPM is now a primary artifact, there is no need to actually have the `release` profile in `distribution/rpm/pom.xml` anymore, that creates the RPM as a secondary artifact, according to http://www.mojohaus.org/rpm-maven-plugin/usage.html

will create a PR to remove that profile
