### ISSUE TITLE
re-enable license checker for RPM builds

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#12528]
The license checker has some issues on the RPMs... not really sure what is happening.

Snapshot publishing has been broken all week (http://build-us-00.elastic.co/job/es_core_master_regression/), so I will disable it temporarily, and leave this issue as a blocker to fix.

I hate to disable it, but not having any snapshots is worse.

**Comment by rmuir** [comment]
It seems this is the root cause:

[exec] sh: 1: rpm2cpio.pl: not found

**Comment by dakrone** [comment]
It does find `rpm2cpio` though, and tries to extract the RPM, then fails with this:

```
     [exec] cpio: premature end of archive
```

So either `rpm2cpio` is not working correctly, `cpio` is not working correctly, or the RPM is not being generated correctly.

**Comment by dakrone** [comment]
Worth mentioning from the `cpio` man page:

```
__WARNING__
       The cpio utility is considered LEGACY based on POSIX specification.  Users are encouraged to use other archiving tools for archive creation.
```

We should use something that does not have a big warning at the top of the man page about it being a "legacy" tool.

**Comment by rmuir** [comment]
I also see errors in RPM generation:

[INFO] error: Macro %__isa_name has empty body
[INFO] error: Macro %__isa_bits has empty body

**Comment by rmuir** [comment]
> We should use something that does not have a big warning at the top of the man page about it being a "legacy" tool.

Can we just extract with 'rpm' itself? This is already necessary to build the thing in the first place right?

I don't have RPM on my system, but looking at the manpage it seems it has the necessary options to "install" to a simple folder:

--dbpath DIRECTORY
    Use the database in DIRECTORY rather than the default path /var/lib/rpm 
--root DIRECTORY
    Use the file system tree rooted at DIRECTORY for all operations. Note that this means the database within DIRECTORY will be used for dependency checks and any scriptlet(s) (e.g. %post if installing, or %prep if building, a package) will be run after a chroot(2) to DIRECTORY.

**Comment by dakrone** [comment]
Looks like the macro error may be an upstream bug in RPM that was fixed: https://groups.google.com/forum/#!topic/linux.debian.bugs.dist/DeTpw_QtxW4 patch: http://rpm.org/gitweb?p=rpm.git;a=commitdiff;h=90dd51743200055f30d9e0e0337173118b4ae756

**Comment by dakrone** [comment]
> Can we just extract with 'rpm' itself?

I think this would be the best tool for extracting it.

**Comment by spinscale** [comment]
hey,

I have asked the infra folks to install rpm2cpio on the build machines. There does not seem  to be a native way using the `rpm` binary to extract its content, similar to what `dpkg -x` is doing.

**Comment by dakrone** [comment]
@spinscale it isn't because `rpm2cpio` isn't on the machines, the RPM package is not being generated properly.

**Comment by rmuir** [comment]
According to my investigation, the generated rpm works (https://github.com/elastic/elasticsearch/pull/12549). It is possible to do the extraction here with rpm itself, thats how those integration tests work. We can do the same for the license checking.

**Comment by clintongormley** [comment]
@rmuir with https://github.com/elastic/elasticsearch/pull/12549, you seem to be extracting all of the packages via maven.  Should I change the license checker script to just accept the directory where the package has been extracted, instead of extracting the package itself?

The only issue I see with that is that, for the `--update` option, the user needs to point the script at some source (currently one of the packages) but if we just use extracted directories then the user will need to extract the package themselves.  (Or we could just support zip extraction only)

**Comment by rmuir** [comment]
> @rmuir with #12549, you seem to be extracting all of the packages via maven. Should I change the license checker script to just accept the directory where the package has been extracted, instead of extracting the package itself?

I'd rather not change it to be the same directory, but, we can reuse the same logic. I don't want the license checker to fail because someone ran -DskipTests or something like that, it shouldnt really depend on integration tests. but it can just invoke the same logic from the same ant file :)

> The only issue I see with that is that, for the --update option, the user needs to point the script at some source (currently one of the packages) but if we just use extracted directories then the user will need to extract the package themselves. (Or we could just support zip extraction only)

I don't know know what this option is... I am lost here sorry. Is it some tool to update the license data in case its out of date? If thats the case, we can just tell people to do it from the zip, or whatever... try to keep this stuff simple, this build is already overwhelmed with crazy requirements (shading, plugins, different packaging systems, etc etc)

**Comment by rmuir** [comment]
@clintongormley if you can give the license checker script some option to just accept a directory, i can hook in the logic from https://github.com/elastic/elasticsearch/pull/12549. Basically it should look a lot like this in the target logic where it invokes the perl script:
```
    <target>
        <!-- invoke rpm extraction from integration tests file -->
        <ant antfile="${elasticsearch.integ.antfile}" target="setup-workspace-rpm"/>
        <exec ... current logic that calls perl script ...>
            <arg some logic passing ${integ.scratch}/rpm-extracted directory/>
        </exec>
    </target>
```

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/12631
