### ISSUE TITLE
Can't search a number longer than 16 charachters

### ISSUE THREAD

**Issue by Vehyla** [elastic/elasticsearch#12539]
We have a field in elasticsearch that is about 19 to 21 characters (All numbers).  If we open a document and click on the magnifying glass for that field.  We get 0 results.  If we copy the first 15 digits then place a * at the end.  We can find all results matching the first 15 digits.  I've tried this as a "long" and as a "string"  with and without "not_analyzed" in my templates.  With this as a "long" I can not even search using the 15 digits and a *.  As these are customer account numbers, I can't really change them.  Can someone let me know if I'm doing something wrong?  Or if there is a template I should be using to capture this.

**Comment by nik9000** [comment]
> Or if there is a template I should be using to capture this.

Its best if you can post an example of it not working that anyone can recreate with curl.  This describes how to do it: https://www.elastic.co/help

**Comment by Vehyla** [comment]
Sadly, these are customer account numbers.  So a search would probably need to have them indexed.  I can show my template though?

This is currently set to "long", but as mentioned we have tried "string" as well.
          "payLoad" : {
            "properties" : {
              "createTime" : {
                "type" : "string"
              },
              "accountId" : {
                "index" : "not_analyzed",
                "type" : "long"
              },
              "action" : {
                "type" : "string"
              },
              "revisionId" : {
                "type" : "string"
              }
            }

**Comment by nik9000** [comment]
> Sadly, these are customer account numbers. So a search would probably need to have them indexed. I can show my template though?

You don't have to recreate the problem with your data - just recreate it with similar enough data that it still happens. Also you might want to put code in three back ticks so the formatting sticks.

**Comment by clintongormley** [comment]
Hi @Vehyla 

Elasticsearch doesn't support BigIntegers.  You should map these fields as `strings`.  You'll find the forum http://discuss.elastic.co/ is a good source of help on questions like these

thanks
