### ISSUE TITLE
Packaging: mvn install renames artifacts when copying

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#12536]
From a recent `mvn install` run

```
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ elasticsearch-deb ---
[INFO] Installing /Users/alr/devel/elasticsearch/distribution/deb/target/releases/elasticsearch-2.0.0-beta1-SNAPSHOT.deb to /Users/alr/.m2/repository/org/elasticsearch/distribution/elasticsearch-deb/2.0.0-beta1-SNAPSHOT/elasticsearch-deb-2.0.0-beta1-SNAPSHOT.deb
[INFO] Installing /Users/alr/devel/elasticsearch/distribution/deb/pom.xml to /Users/alr/.m2/repository/org/elasticsearch/distribution/elasticsearch-deb/2.0.0-beta1-SNAPSHOT/elasticsearch-deb-2.0.0-beta1-SNAPSHOT.pom
```

The artifact is renamed back to `elasticsearch-deb-2.0.0-beta1-SNAPSHOT.deb`, which happens for all the packages. Not sure if this also happens with `mvn deploy`, if so, this needs to be fixed.

**Comment by dadoonet** [comment]
In my source PR I wrote :

                <configuration>
                    
                    <deb>${project.build.directory}/releases/elasticsearch-${project.version}.deb</deb>
                    <controlDir>${project.build.directory}/generated-packaging/deb/scripts</controlDir>
                </configuration>

HTH

**Comment by spinscale** [comment]
so, does this mean we can close this as `mvn deploy` is doing the right things or do we need to fix things?

**Comment by dadoonet** [comment]
Sounds like I misread your issue at first.

I think that mvn deploy would deploy using the same name as the one you have in .m2.

You can try it. It will simply deploy a SNAPSHOT version which does not hurt. 

IMO it would be better to rename elasticsearch artifact to elasticsearch-core and for distribution modules use elasticsearch as artifact id. So all defaults should be good.

Not sure what would be the impact of this.

IIRC I tried to use elasticsearch as the artifactId in distribution modules but it was not possible without renaming core module (circular dependency). But I'm AFK and can't really test this ATM.

**Comment by rmuir** [comment]
Removed blocker. The renames done with finalName aren't going to have any impact on the maven repository... this is just how maven works.
