### ISSUE TITLE
Elasticsearch's CPU usage rate lasts high when no search request even

### ISSUE THREAD

**Issue by Judyccb** [elastic/elasticsearch#12548]
The elasticsearch node's CPU usage rate lasts 60% for 3 weeks which  connects to kibana as a search node.In the meantime,there is no any request, so weird.

The hot thread is as follow,

curl XX:9200/_nodes/XX/hot_threads
::[RPRiDE6mRTOZclpQ8hTP9A][XX]]{data=false, master=false}
   
   100.2% (500.8ms out of 500ms) cpu usage by thread 'elasticsearch[][search][T#1]'
     7/10 snapshots sharing following 12 elements
       java.util.TreeMap.getEntryUsingComparator(TreeMap.java:376)
       java.util.TreeMap.getEntry(TreeMap.java:340)
       java.util.TreeMap.remove(TreeMap.java:595)
       java.util.TreeSet.remove(TreeSet.java:276)
       org.elasticsearch.common.collect.BoundedTreeSet.rebound(BoundedTreeSet.java:60)
       org.elasticsearch.common.collect.BoundedTreeSet.add(BoundedTreeSet.java:47)
       org.elasticsearch.search.facet.terms.strings.InternalStringTermsFacet.reduce(InternalStringTermsFacet.java:214)
       org.elasticsearch.search.controller.SearchPhaseController.merge(SearchPhaseController.java:314)
       org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction$2.run(TransportSearchQueryThenFetchAction.java:145)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       java.lang.Thread.run(Thread.java:745)
     3/10 snapshots sharing following 11 elements
       java.util.TreeMap.getLastEntry(TreeMap.java:1977)
       java.util.TreeMap.lastKey(TreeMap.java:292)
       java.util.TreeSet.last(TreeSet.java:401)
       org.elasticsearch.common.collect.BoundedTreeSet.rebound(BoundedTreeSet.java:60)
       org.elasticsearch.common.collect.BoundedTreeSet.add(BoundedTreeSet.java:47)
       org.elasticsearch.search.facet.terms.strings.InternalStringTermsFacet.reduce(InternalStringTermsFacet.java:214)
       org.elasticsearch.search.controller.SearchPhaseController.merge(SearchPhaseController.java:314)
       org.elasticsearch.action.search.type.TransportSearchQueryThenFetchAction$AsyncAction$2.run(TransportSearchQueryThenFetchAction.java:145)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       java.lang.Thread.run(Thread.java:745)
   
    0.1% (326.7micros out of 500ms) cpu usage by thread 'elasticsearch[][[transport_server_worker.default]][T#2]{New I/O worker #7}'
     10/10 snapshots sharing following 15 elements
       sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
       sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
       sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
       sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
       sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
       org.elasticsearch.common.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:68)
       org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.select(AbstractNioSelector.java:415)
       org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:212)
       org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
       org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
       org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
       org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       java.lang.Thread.run(Thread.java:745)
   
    0.0% (77.2micros out of 500ms) cpu usage by thread 'elasticsearch[][transport_client_timer][T#1]{Hashed wheel timer #1}'
     10/10 snapshots sharing following 5 elements
       java.lang.Thread.sleep(Native Method)
       org.elasticsearch.common.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:445)
       org.elasticsearch.common.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:364)
       org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
       java.lang.Thread.run(Thread.java:745)

**Comment by markwalkom** [comment]
Please join us in #elasticsearch on Freenode or at https://discuss.elastic.co/ for troubleshooting help, we reserve Github for confirmed bugs and feature requests :)

**Comment by Judyccb** [comment]
The URL you give can not be open in our area,any other way to discuss this problem?
