### ISSUE TITLE
Unable to perform a sorted search across indices that don't contain the sort field

### ISSUE THREAD

**Issue by webmstr** [elastic/elasticsearch#12545]
I have a daily index, e.g. "foo-YYYY.MM.DD".  Occasionally - but not every day - I have an event of type "bar" that has field called "enddate".  I would like to query for these events, and sort by the "enddate" field.

Unfortunately, elasticsearch is checking the mapping before it checks the data.  When the daily index contains no rows of this type, the "enddate" field doesn't appear in the mapping, and the query fails:

    Parse Failure [No mapping found for [enddate] in order to sort on]]

The work-arounds seem to be either to define a fixed mapping, or insert dummy records every day.  Both are bad.

**Comment by clintongormley** [comment]
Alternatively, you can read the documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_ignoring_unmapped_fields

**Comment by webmstr** [comment]
Thanks for the pointer.  How about referencing the exact error message on the doc page so that mortals can find it?

**Comment by clintongormley** [comment]
@webmstr would you like to send a docs PR to make the improvement?

Just click the "edit" button on the docs page and you can edit the source directly
