### ISSUE TITLE
Drop the `action.get.realtime` setting

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#12543]
The get, multi get, termvector and multi termvector apis have a `realtime` option. If the realtime option isn't specified then default depends on the api.

The get and multi get apis default is based on which has been defined in the `action.get.realtime` setting. The default of the `action.get.realtime` is `true`. But the term vector apis don't have a setting like this and the `realtime` option just default to `true`.

I don't think this setting is actually used a lot and I like to remove it. The main reason for that this cleans up to code and simplifies it. Secondly the behaviour is now inconsistent between apis. Also for the `realtime` and similar options, I think being able to set on a per request level is enough, there no need to have a node level default.

**Comment by alexksikes** [comment]
+1 The node level default seems to be overkill.

**Comment by nik9000** [comment]
Fine by me.

**Comment by clintongormley** [comment]
Agreed - let's remove this setting

**Comment by clintongormley** [comment]
@martijnvg you want to pick this up for 5.0?

**Comment by javanna** [comment]
Should this still be labelled deprecation given that the corresponding PR removes the setting? Did we deprecate the setting in 2.x or have we decided that deprecation is not needed?

**Comment by martijnvg** [comment]
@javanna I think this setting is not needed. I think the deprecation label should be removed.

**Comment by javanna** [comment]
I agree that it is not needed, wondering if there are users using it (hopefully not) and what the upgrade path is for them. A node would not startup with this setting in 5.0 I believe, which forces users to remove the non supported setting. Is that correct?

**Comment by martijnvg** [comment]
Yes, node startup would fail with a error message that it is a unknown setting. It is good that this will bubble up quickly.

**Comment by wedneyyuri** [comment]
Hi @martijnvg, there are plans to change the default behavior of `realtime` option? 

In our environment we are setting the refresh interval to 10 minutes to prevent cache invalidation and we can't guarantee passing the realtime option on every request.
