### ISSUE TITLE
Blocking writes to slf4j causing shards to be stuck in initializing state

### ISSUE THREAD

**Issue by autocracy** [elastic/elasticsearch#12542]
Two cases so far have occurred on 1.7 after making cluster settings to exclude a node by ip:
* A node is excluded; shards enter a migrating state with new target hosts selected. The state never advances.
* A node is excluded, then a node that the shard is migrating to is added to the exclusion list. The double-migrated shard gets stuck on the 2nd node and never complete migration.

**Comment by clintongormley** [comment]
Hi @autocracy 

Please could you spell out the scenarios with a few more details?  Would help us to understand what happened when.

**Comment by autocracy** [comment]
After some digging yesterday, it appears that the root cause for this is the slf4j logger in SocketAppender mode locking up the threads of ES because of blocked writes.

The lack of tooling to force this into a fixed mode is rough, but it's the same issue encountered with Cassandra when using remote logging. I think nobody expects logging to block like that.

**Comment by clintongormley** [comment]
We've just discussed this in FixItFriday and agree that logging across the network is a really bad idea for a busy Elasticsearch server, and not a configuration that we want to support.

There are plenty of tools available which can tail log files and ship them to a central server, including Logstash and [Filebeat](https://github.com/elastic/filebeat)
