### ISSUE TITLE
_only_nodes against a node attribute not shuffling requests between nodes

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#12546]
Reproducible using 1.7.1 and 5.0 Alpha 2.
https://gist.github.com/ppf2/a5a04d94cc7e0fc3859e

Not sure if `_only_nodes:pod:A` is the right way to specify the value, but it certainly complains about _only_nodes:bogus_name:A and _only_nodes:pod:bogus_value.  So far, not seeing it shuffle between the nodes sharing the same node attribute.

**Comment by nirmalc** [comment]
is it because explain() just picksup shardIterator.next() and does operation on first shard ? can you test with _search , set slow_query threshold to 1 ms or so and see if the query hits all nodes

**Comment by ppf2** [comment]
GET only_node_test/_search?explain=true
shows that it is hitting all shards (and it is populating slowlog for all nodes).

With _only_nodes:pod:A and slowlog at 0ms, only 1 "A" node is getting slowlog entries so it appears to be consistent with the explain output.

**Comment by ppf2** [comment]
Can we also fix this in the 2.x branch?
