### ISSUE TITLE
Extracting Date and time from timestamp in Elasticsearch and show in Kibana 4 

### ISSUE THREAD

**Issue by sauravmondallive** [elastic/elasticsearch#12552]
I have a "timestamp" field which is of date type format and stores the respective time in thlog files. Example "timestamp": "2015-07-13:09:20:34". My mapping is as follows

{
"sam": {
"mappings": {
"log_entry": {
"properties": {
"browser": {
"type": "string",
"index": "not_analyzed"
},
"timestamp": {
"type": "date",
"format": "yyyy-MM-dd:HH:mm:ss"
}
}
}
}
}
}

I want to extract the the date part as "yyyy-MM-dd" and time as "HH:mm:ss" so that i can plot a hits graph in which the time will be on x axis and there will be line for different days in Kibana 4 showing hits per hour of all the days i have. I am parsing the logs through java parser, hence splitting through logstash is not an option for me. as the code is already being deployed, i dont want to change in the java parser code(which is a very easy option).

I was thinking if there was a way to use query which i can use in filter and plot them in kibana 4

**Comment by clintongormley** [comment]
Hi @sauravmondallive 

The best place to ask these questions is in the forums: http://discuss.elastic.co/

The issues list is for bug reports and feature requests

thanks
