### ISSUE TITLE
cat.nodeattrs/10_basic/Test somtimes fails

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#12558]
FAILURE 0.14s | RestIT.test {p0=cat.nodeattrs/10_basic/Test cat nodes attrs output} <<<
   > Throwable #1: java.lang.AssertionError: field [$body] was expected to match the provided regex but didn't
   > Expected: ((\S+)\s+(\S+)\s+(\d{1,3}\.){3}\d{1,3}\s+(\S+)\s+(\S+)\s*)+

See http://build-us-00.elastic.co/job/es_core_master_regression/2933

**Comment by nik9000** [comment]
Ping @metadave.

**Comment by rmuir** [comment]
interestingly enough, it seems to only fail in integration test phase, not when run as unit test. This is the case where we startup bin/elasticsearch externally and run the tests against it... maybe its looking for something that is different in that case?

**Comment by metadave** [comment]
looks like an empty string is returned from `_cat/nodeattrs` in some cases.

**Comment by rmuir** [comment]
and these are the first test runs testing the .tar distribution (https://github.com/elastic/elasticsearch/pull/12549), so its possible something is screwy with tar distribution (or how we run it?) that causes this... but this is a mirror image of how we test the zip, just with untar instead of unzip.

**Comment by metadave** [comment]
I'm not sure if it's currently possible to make this test pass during the integration test phase. When I initially wrote the test, there appeared to be several node attributes already defined. Changing the regex suffix from `+` to `*` would partially work, but would mask errors if node attributes aren't showing up at all.

See also:
https://github.com/elastic/elasticsearch/pull/12520#issuecomment-125827569

**Comment by clintongormley** [comment]
@metadave changing it to `*` would definitely be the easiest fix.  Another possibility is the `skip` functionality. We can skip tests if some condition isn't met (the condition itself needs to be coded into the test runner).  For instance, we can skip the scripting tests if groovy scripting isn't enabled, by running a pre-check to determine whether a simple groovy script can execute. 

Could add the same thing to skip this test if no node attributes are defined.  Not sure it is worth it though.

**Comment by nik9000** [comment]
I'm just going to swap `*` in for `+` to handle those cases where there isn't one set. I'm also adding a test for the help. Its not perfect but better than leaving it disabled.
