### ISSUE TITLE
Rename position_offset_gap to position_increment_gap

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#12562]
The name "position_offset_gap" is confusing because Lucene has three similar sounding things:
* ```Analyzer#getPositionIncrementGap```
* ```Analyzer#getOffsetGap```
* ```IndexOptions.DOCS_AND_FREQS_AND_POSITIONS_AND_OFFSETS``` and ```FieldType#storeTermVectorOffsets```

Elasticsearch's ```position_offset_gap``` is mapped directly to ```Analyzer#getPositionIncrememntGap``` - its the gap in term positions between multiple values of the same field in the same document.

```Analyzer#getOffsetGap``` is the position gap between _tokens_ and shouldn't be messed with on the mapping level.

The word "offsets" ```IndexOptions.DOCS_AND_FREQS_AND_POSITIONS_AND_OFFSETS``` and ```FieldType#storeTermVectorOffsets``` refers to storing the offsets into the text of the field in either the postings list or the term vectors and are primarily used for highlighting.

I propose Elasticsearch renames ```position_offset_gap``` to ```position_increment_gap``` to line up with Lucene and reserves the work "offset" to talk about the offsets into the text of fields. I know Elasticsearch doesn't always have to line up with the Lucene names for things but in this case its quite confusing not to. We could always go with other names like ```multi_value_position_gap``` or ```multi_value_term_gap``` if we think they are more descriptive.

In reference to https://github.com/elastic/elasticsearch/pull/12544#issuecomment-126132622

**Comment by rmuir** [comment]
+1 for `position_increment_gap`: even if we have to deprecate the old name and all that, it will be so much less confusing: the name makes sense because offsets are not involved, and if someone does a google search on this, they will already find all kinds of documentation/explanations about what it does. 

changing the position gap is useful and important if you have multiple values per field and are doing prox queries. changing the offset gap will basically just break highlighters.

**Comment by nik9000** [comment]
What Elasticsearch policy on naming things like Lucene? I could think of lots of different ones:
0. "We strive to match the Lucene name for things where possible."
1. "We will name things like Lucene names them unless the Lucene name is silly and confusing."
2. "We will name things like Lucene names them unless we can think of a more descriptive name."
3. "Who cares what Lucene calls a thing? We are abstracting over it anyway and if we feel like we have to name something the same way our abstraction is leaking."


Personally I'd prefer 1 or 2 over the other options.

**Comment by clintongormley** [comment]
I'm good with `position_increment_gap`.  For the novice user it won't make much sense (but neither will the current name). Either way it needs good documentation.

> Personally I'd prefer 1 or 2 over the other options.

Agreed

**Comment by clintongormley** [comment]
Note: existing indices should have the position_offset_gap setting automatically changed to the new setting.

When you do this, please open an issue on http://github.com/elastic/elasticsearch-migration/issues

**Comment by xuzha** [comment]
Do we need this in 2.0?

**Comment by s1monw** [comment]
+1 for 2.0

**Comment by xuzha** [comment]
Thanks guys, merged the changes into master and 2.0.
