### ISSUE TITLE
Should Analyzer setting override search-analyzer for non-analyzed fields ?

### ISSUE THREAD

**Issue by keety** [elastic/elasticsearch#12563]
Analyzer  erroneously specified in mapping for a field of type non-analyzed  overrides the default  keyword search analyzer
Also the analyze api seems to suggest the index_analyzer is overridden even though it is not so

Example:
```json

PUT test
{
    "settings": {
        "analysis": {
            "analyzer": {
                "my_analyzer" : {
                    "tokenizer" : "keyword",
                    "filter" : "lowercase"
                }
            }
        }
    },
    "mappings": {
        "test" : {
            "properties" : {
                "data" : {"type" :"string" ,"index" : "not_analyzed","analyzer" : "my_analyzer"}
            }
        }
    }
}

GET  test/_analyze?field=data&text=IT IS ELASTIC

#Response gives the wrong impression that index-analyzer is overridden


PUT test/test/1 
{
    "data" : "it is elastic"
}

POST test/_search
{
    "query": {
        "match": {
           "data": "IT IS ELASTIC"
        }
    }
}
#Response indicates *search_analyzer* is overridden 
   "hits": {
      "total": 1,
      "max_score": 0.30685282,
      "hits": [
         {
            "_index": "test",
            "_type": "test",
            "_id": "1",
            "_score": 0.30685282,
            "_source": {
               "data": "it is elastic"
            }
         }
      ]
   }
```
Shouldn't analyzer setting be ignored for non-analyzed fields or at-least in the analyze api  for non-analyzed fields?

Tested in elasticsearch 1.6.0 and 2.0.0 beta snapshot

**Comment by clintongormley** [comment]
You are absolutely correct.  Weird that it has taken this long for this issue to show up for the first time.

I was going to put it up as a bug to be fixed, but then I remembered this change that we're planning for 2.0: https://github.com/elastic/elasticsearch/issues/12394

The `analyzed`/`not_analyzed` setting will be replaced by splitting the `string` type into `text` and `keyword` types, where `keyword` fields are not analyzed by default, but WILL support analyzers (as long as the tokenizer is  `keyword`).

So it will be acceptable to set an analyzer on a `keyword` field, which means this particular issue doesn't need fixing.

thanks for the good recreation.
