### ISSUE TITLE
cleanup plugin installation in bats tests

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#12564]
When reviewing #12508, I noticed that the plugin installation in the bats tests used the plugin name typically used when installing without specifying the url:

```
/tmp/elasticsearch/bin/plugin install elasticsearch/shield/latest -u "file://$SHIELD_ZIP"
``` 

typically we say to install with just `shield` as the name when specifying the URL. I think we should cleanup the installation to be more realistic.

**Comment by spinscale** [comment]
closing in favor of [#12651](https://github.com/elastic/elasticsearch/issues/12651)
