### ISSUE TITLE
Elasticsearch client nodes 

### ISSUE THREAD

**Issue by AGirin** [elastic/elasticsearch#12568]
Hi!

We are trying to see if we can introduce client nodes into our Elasticsearch cluster. I have yet to find any recommendations as far as memory requirements and Java settings for client nodes. Do they follow the same principles as data nodes? 50% of ram to heap and 50% to OS (not to exceed 32gb though)? 

What about CPU? Is it preferable to have a lot of cores for client nodes? 

Your insight is greatly appreciated!

Andrew

**Comment by colings86** [comment]
This was asked and answered on the dicuss forums: https://discuss.elastic.co/t/elasticsearch-client-nodes/26598
