### ISSUE TITLE
"mvn verify" should catch bugs in the docs

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#12583]
I'm not sure how to implement this but I think it's important for the quality of our docs.

In Apache Lucene, if I mess up javadocs, "ant compile" or "ant pre-commit" will catch it.

But for ES, I think (?) I must clone the docs repo (https://github.com/elastic/docs) and follow its steps to make sure all is good.

Can we make this easier somehow, e.g. fold it under "mvn verify"?

**Comment by colings86** [comment]
I think @clintongormley was working on making `mvn site` build the documentation but I'm not sure how far he got with it.

**Comment by rjernst** [comment]
+1 to having this done with `mvn verify`.  Can we use the maven asciidoc plugin? I know it won't do all the cross link checking to other parts of the docs, but can we at least get syntax checking?

**Comment by dadoonet** [comment]
See also https://github.com/elastic/elasticsearch-parent/issues/50

**Comment by rmuir** [comment]
one wierd thing is that site has some wacky separate lifecycle in maven, i dont think it would in fact get run during `verify` (which is the point of this PR).

Maybe an easier step / alternative is to either package up or fold in the perl scripts in the docs repo and invoke them in our build when we want and not use the site stuff for now?

**Comment by colings86** [comment]
Yeah so I think @clintongormley was working on just using the maven-exec-plugin to run the perl scripts, like we do for the license checking stuff. He was doing it in `mvn site` because I think at the time we were thinking it would be good to keep it in a separate lifecycle, but should be easy to move it to `mvn verify` instead.

**Comment by rmuir** [comment]
yeah I think `docs/` should just get a pom.xml and plug stuff in at all our normal phases.

**Comment by clintongormley** [comment]
I don't think we should package up the build scripts into core. Instead we can just rely on the fact that you have `build_docs.pl` in your command line.  The issue that I had when trying to do this was that the various books in docs/ don't map one to one to the other repos. I like the idea of having a pom.xml in the docs directory, then we can just build everything in that dir.

**Comment by rmuir** [comment]
How can we rely on that? Relying on anything on the commandline makes setting up a new developer very different: we should avoid that at all costs. Its too system specific.

If we are going to do that shit in our build, then please, open a separate issue for that 'Convert build system to make'. And I will take it seriously!

But no, i dont want requiring special setup *AND* thousands of lines of xml. thats the worst of both worlds.

**Comment by clintongormley** [comment]
Closing as won't fix
