### ISSUE TITLE
elasticsearch (again) adds CWD to classpath

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#12580]
This causes all kinds of bugs.

I fixed this already in #12001 but my code changes were *lost*

I will not allow this to happen again: I am going to make heavy changes to tests so that things fail if this is screwed up again. Expect them to break lots of functionality like IDE integration and other plugins tests: don't care.

**Comment by rmuir** [comment]
By the way thanks to @spalger for discovering this.

**Comment by rmuir** [comment]
Fixed.

**Comment by clintongormley** [comment]
Fixed by https://github.com/elastic/elasticsearch/commits/8d5b5ad862de589667211456f1e96c156412c90f
