### ISSUE TITLE
_geo_distance sort off by 2.5x with all distance_types

### ISSUE THREAD

**Issue by fbliss** [elastic/elasticsearch#12591]
I can't figure out why, but the distance between these two coordinates is roughly 75 miles

```
Origin:
42.587914999999995,
-72.5994104
Destination:
41.6913013, 
-72.8458687
```
[link to directions via google maps] (https://www.google.com/maps/dir/42.587914999999995,-72.5994104/41.6913013,-72.8458687)

however, my index which stores geo_point data shows the sort value as roughly 25 miles.  Here is the Query:

```json
{  
   "size":25,
   "from":0,
   "query":{  
      "filtered":{  
         "query":{  
            "match_all":{  

            }
         },
         "filter":{  
            "geo_distance":{  
               "distance":"500mi",
               "location":[  
                  42.587914999999995,
                  -72.5994104
               ]
            }
         }
      }
   },
   "sort":[  
      {  
         "_geo_distance":{  
            "location":[  
               42.587914999999995,
               -72.5994104
            ],
            "order":"asc",
            "unit":"miles",
            "distance_type":"arc"
         }
      }
   ]
}
```
The response is giving me a sort value of "25.020869790780612"

What could possibly account for this inaccuracy?

**Comment by clintongormley** [comment]
You're getting lat and lon mixed up.  Arrays take [`lon`,`lat`]. See:

    PUT test
    {
      "mappings": {
        "test": {
          "properties": {
            "location": {
              "type": "geo_point"
            }
          }
        }
      }
    }
    
    PUT test/test/1
    {
      "location": {
        "lat": 41.6913013,
        "lon": -72.8458687
      }
    }
    
    GET test/_search
    {
      "sort": [
        {
          "_geo_distance": {
            "location": {
              "lat": 42.587914999999995,
              "lon": -72.5994104
            },
            "order": "asc",
            "unit": "miles",
            "distance_type": "arc"
          }
        }
      ]
    }

**Comment by fbliss** [comment]
Ok... Why in the world is that?

**Comment by dadoonet** [comment]
@fbliss Read the end of https://www.elastic.co/guide/en/elasticsearch/guide/current/lat-lon-formats.html :)

**Comment by fbliss** [comment]
I still am getting incorrect results, namely, results that go to the other extreme like 8,000 miles to San Francisco.  I should note that my mapping has set the geo_point setting lat_lon to TRUE, so that is indicated in the docu as being a way to tell it to reverse the order in which you're storing the data.

'''
PUT test
{
  "mappings": {
    "test": {
      "properties": {
        "location": {
          "type": "geo_point",
          "lat_lon": true
        }
      }
    }
  }
}
'''

when i index my documents accordingly, I'm getting bad results.

**Comment by clintongormley** [comment]
>  I should note that my mapping has set the geo_point setting lat_lon to TRUE, so that is indicated in the docu as being a way to tell it to reverse the order in which you're storing the data.

No, you've completely misunderstood the `lat_lon` option :)

Normally the latitude and longitude values are not indexed, and distance calculations are done in memory.  By setting `lat_lon` to true, you are saying "also add the lat and lon values to the inverted index" as sometimes that can perform better.  Nothing to do with order.

**Comment by fbliss** [comment]
Thanks for clearing that up.  I did get it working.
