### ISSUE TITLE
Automate the packaging tests

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#12611]
Right now there are some packaging tests that run as [bats](https://github.com/sstephenson/bats) scripts. They are destructive to the system they run on and only work on certain operating systems. It doesn't make sense to test the RPM build on Debian, nor does it make sense to test the DEB build on CentOS.

I propose we automate some testing of these using vagrant or a similar technology. Vagrant sounds like a good place to start at least.

**Comment by electrical** [comment]
I do a lot of testing using Docker. Perhaps worth looking into that?
Although i personally don't like it, Kitchen-CI has a plugin to run bats tests. and together with the docker hypervisor plugin you can run it in a docker container.

**Comment by nik9000** [comment]
I've got vagrant mostly working actually. I can try docker from there too.
I'm weary as I've heard people say it doesn't work well for them but I'll
give it a shot.

**Comment by electrical** [comment]
I've been running puppet module tests on docker for over a year or so. It does require some tweaking and starting the docker containers slightly differently.
