### ISSUE TITLE
node.name: "Franz Kafka"

### ISSUE THREAD

**Issue by coderlol** [elastic/elasticsearch#12628]
Why is there a double quote?  Would it be ok not to have the double quote?

node.name: ${MY_NODE_NAME}

and MY_NODE_NAME=Franz Kafka would also work?

**Comment by markwalkom** [comment]
You should really set your own node name, it makes it easier to troubleshoot and monitor things.

However what do you want to know here? If double quotes can be used in `node.name`?

**Comment by spinscale** [comment]
Hey,

so the double quote in the config file is optional in this example, but might be useful, if you are using arrays (which is not the case for hostnames). Your example setting environment variables would work as well, but in this case you need to use quotes.

Also, please ask such questions in our [forums](https://discuss.elastic.co/), as we try to use github issues for bugs/features/etc. Thanks!

**Comment by coderlol** [comment]
Cool.  Thanks for the answer.  I did not realize you had a forum.
