### ISSUE TITLE
Packaging tests try to use watcher for 1.7 in 2.0

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#12637]
The packaging tests try to download watcher/latests in the master/2.0 branches and fail to install watcher. If you manually build watcher for 2.0 from source and dump it into the current working directory then they work but this is a pain for some and impossible for others because the watcher repository is private to the elastic organization.

**Comment by tlrx** [comment]
I think you're talking about Shield; also these tests have been added to test that plugins with custom configuration files were correctly installed when elasticsearch is installed through TAR, RPM or DEB packages.

I think we can safely removed this test if we have good qa test for plugins.

**Comment by dadoonet** [comment]
Agreed. IMO tests relying on private plugins should be run within private repos not within elasticsearch public project.

**Comment by nik9000** [comment]
> Agreed. IMO tests relying on private plugins should be run within private repos not within elasticsearch public project.

Yeah - I'll move the tests to using kuromoji or something.

**Comment by nik9000** [comment]
Lets resolve this by removing the watcher install entirely and install the plugins. And we have another issue for that that duplicates this, kind. Anyway, calling this one a dupe of #12717.
