### ISSUE TITLE
GeoShape data rejected while upgrading from 1.4.4 to 1.7.1

### ISSUE THREAD

**Issue by ml4spark** [elastic/elasticsearch#12644]
Hi there,
I am evaluating an upgrade to 1.7.1 for our 1.4.4 production cluster. We seem to be having some data that has geo shapes that 1.4.4 accepted and indexed but 1.7.1 is choking on. The message below is only a warning but it seems to be rejecting the whole shard to be moved to the newer versioned machine, right? Can I reduce the level of validation checking for geo locations?

Do we have  a breaking change in geo shape validator between these versions?
[2015-08-04 11:41:19,543][WARN ][cluster.action.shard ] [hostname] [indexname][5] received shard failed for [indexname][5], node[lxvTTQWSRDiBA9Se21hjHw], relocating [BRUHrGoBQnO9MzyssyMCoQ], [P], s[RELOCATING], indexUUID [d2E1eeDHRB6FOs57k0IxaA], reason [Failed to perform [indices:data/write/bulk[s]] on replica, message [RemoteTransportException[[hostname][inet[/10.10.10.220:9302]][indices:data/write/bulk[s][r]]]; nested: MapperParsingException[failed to parse [message.location.geo]]; nested: InvalidShapeException[Provided shape has duplicate consecutive coordinates at: (-88.097892, 37.771743, NaN)]; ]]

**Comment by eliranmoyal** [comment]
+1

**Comment by Ghost93** [comment]
+1

**Comment by ml4spark** [comment]
Hi Nick, have you had a chance to take a look? Our upgrade to a newer version (and security fixes) is blocked until we have this resolved. Thanks

**Comment by sergeant72** [comment]
+1

**Comment by nknize** [comment]
@ml4spark can you (or anyone else experiencing this behavior) provide an example shape that throws the exception? In short the behavior is related to #9511 where the ```ShapeBuilder``` formerly failed on valid interior rings, or constructed incorrect base polygons due to shape ambiguity (a nasty form of silent spatial data corruption).

To eliminate these issues (especially the latter), we made the ShapeBuilder more stringent by ensuring full compliance with the OGC SFA spec.  Since this was a change to 1.4.5, 1.5.2, and 1.6.0 we'll need to make sure your 1.4.4 indexed shapes were interpreted correctly.

> Can I reduce the level of validation checking for geo locations?

For safety reasons ```ignore_malformed``` is not yet supported for ```geo_shape``` fields.  We can certainly add support to accept non-compliant data (if the majority desires) so long as there is an understanding of the associated dangers.

**Comment by clintongormley** [comment]
> For safety reasons ignore_malformed is not yet supported for geo_shape fields. We can certainly add support to accept non-compliant data (if the majority desires) so long as there is an understanding of the associated dangers.

I think we should definitely add `ignore_malformed` (default `false'), however I think it should behave in a consistent manner with all other uses of it: don't throw an exception but ignore the invalid value completely.

Using it to paper over invalid data is trappy and leads to hard to debug problems later on.  Either the data is valid, in which case you can query it, or it isn't, in which case you can't.

**Comment by ml4spark** [comment]
Hi Guys, can you help me configure elasticsearch logging such that it provides the information about which document causes the issue. We have many TBs of data and it seems this issue is very seldom. I only know in which shard (~200GB) the issue was encountered based on the above message. We could modify/fix/delete the offending information if the log returned the document id of the offending document.

**Comment by thebabelfish** [comment]
I encountered the same issue using logstash to import some postgis data.   Wanted to note that the geojson data passed the postgis st_isvalid(<column>) despite having duplicate coordinates which I confirmed do exist in my data.

I then bypassed logstash and single indexed the document with the invalid geojson and elaticsearch took it without error.  It was only when I bulk indexed (whether through logstash or "myself") that the duplicate coordinate error was raised.

Bringing it to attention for elasticsearch as a possible bug and the users looking for a "workaround".

I am running elasticsearch v1.7.1.

**Comment by ml4spark** [comment]
Howdy elastic team,
just a brief note to let you know that we managed to avoid the issue by re-processing the offending data. We have upgraded all nodes to 1.7.1 now.
We do no longer require help with this issue.

**Comment by muka** [comment]
+1

**Comment by nknize** [comment]
Thanks to all for the discussion. I'm closing this as a non-issue. For future reference I am including excerpts from the [OGC SFA](http://www.opengeospatial.org/standards/sfa) and  [ISO 19107:2003](http://www.iso.org/iso/catalogue_detail.htm?csnumber=26012) standard that we use for processing ```geo_shape``` types. Not all geo processing packages interpret the spec the same, and adding leniency tends to introduce different bugs. Perhaps this presents the need for an Elasticsearch geo validator that can be used to preprocess the data.

> A Curve is simple if it does not pass through the same Point twice with the possible exception of the two end points (Reference [1], section 3.12.7.3):
> A Curve is closed if its start Point is equal to its end Point (Reference [1], section 3.12.7.3).
> A Curve that is simple and closed is a Ring.
> The boundary of a Polygon consists of a set of LinearRings that make up its exterior and interior boundaries;
