### ISSUE TITLE
Changed pid file path causes init script to fail to restart ES after upgrade

### ISSUE THREAD

**Issue by magnusbaeck** [elastic/elasticsearch#12649]
With RESTART_ON_UPGRADE disabled (default for at least 1.5.2), the init script of ES 1.7.x will be unable to restart ES after a Debian package upgrade from 1.5.x or earlier.

This is because the pid file path changed in 1.6.0 (IIRC), so when a user invokes e.g. `/etc/init.d/elasticsearch restart` after the package has been upgraded no pid file is found and ES is deemed to not be running. The subsequent start will then fail since it can't bind to any ports as they're still busy by the running ES process.

This broke my automated upgrade from 1.5.2 to 1.7.1, requiring a manual shutdown of ES on affected machines and/or a package rollback. Could we try a little harder to find the pid file by e.g. introducing a fallback pid file in the 1.7.x series? Perhaps migrating the old pid file with something as simple as

    LEGACY_PID_FILE="/var/run/elasticsearch.pid"
    if [ -f "$LEGACY_PID_FILE" -a "$LEGACY_PID_FILE" != "$PID_FILE" ] ; then 
            mv "$LEGACY_PID_FILE" "$PID_FILE" || exit 1
    fi

right after the PID_DIR creation in /etc/init.d/elasticsearch would do?

**Comment by tlrx** [comment]
@magnusbaeck I was thinking of something similar - it sounds a good idea to me.

**Comment by magnusbaeck** [comment]
Great. I'll look into a patch.

**Comment by magnusbaeck** [comment]
This is a duplicate of #11747. Keeping this one open for now since it's more descriptive and already has the "bug" label.

**Comment by clintongormley** [comment]
We no longer restart after upgrade.  Closing
