### ISSUE TITLE
Match phrase query fvh highlighter issue.

### ISSUE THREAD

**Issue by lifo888** [elastic/elasticsearch#12648]
All the results that are returned contain the words monkey and business within 5 slop of each other.  However,  some results did not result a highlight field.  When i checked those docs, i noticed that all of them have the words "monkey" and "business" in reserve order.  In another word, all those docs that didn't return a highlight have the word "business" appear before "monkey".  

If the match phrase query with slop is matching words regardless of position, shouldn't the highlight also follow that?  Seems like a bug to me.

Query:
{
    "highlight": {
        "fields": {
            "content": {
                "type": "fvh"
            }
        }, 
        "fragment_size": 100, 
        "number_of_fragments": 10
    }, 
    "query": {
        "filtered": {
            "filter": {
                "and": [
                    {
                        "range": {
                           "doc_date": {
                                "gte": "20150101t235959", 
                                "lte": "20150730t235959"
                            }
                        }
                    }
                ]
            }, 
            "query": {
                "match_phrase": {
                    "content": {
                        "query": "monkey business", 
                        "slop": 5
                    }
                }
            }
        }
    }
}

**Comment by nik9000** [comment]
Just so we have a complete bug report, do can you make a [curl recreation](https://www.elastic.co/help)? I think this is a bug from your description but it'd be nice to have a runnable example.

**Comment by guangchen06** [comment]
curl  '127.0.0.1:9200/my_index/my_type/_search?pretty' - d '
{
	"_source": ["doc_date"],
		"highlight" : {
		"fields": {"content": {"type": "fvh"}},
			"fragment_size" : 100,
			"number_of_fragments" : 10
	},
	"query" : {
			"filtered": {
				"filter": {
					"range": {
						"doc_date": {
							"gte": "20150101t235959",
								"lte" : "20150730t235959"
						}
					}
				},
					"query": {
					"match_phrase": {
						"content": {
							"query": "monkey business",
								"slop" : 5
						}
					}
				}
			}
		},
			"size": 100, "from" : 0
}
'

This is the full query.  Some of the entries in query result contain highlight and others done.

**Comment by guangchen06** [comment]
Any updates here?

**Comment by nik9000** [comment]
I'm still deep in non highlighting stuff and don't have much time to
contribute over the next week and a half anyway. Even when I do I'm not
sure if this will be my highest priority.

**Comment by satazor** [comment]
I'm hitting this issue too. @lifo888 did you find any workaround?

**Comment by clintongormley** [comment]
Closing in favour of #21621
