### ISSUE TITLE
Update API - versioning with upsert doesn't error when version passed is 0 and document already exists

### ISSUE THREAD

**Issue by chriswhite199** [elastic/elasticsearch#12659]
When not using scripted upserts, i would assume the pattern to ensure that two upserts arriving at the same time for a new document doesn't result in an undefined outcome would be to use the version query parameter - but setting this to 0 doesn't throw an error (maybe this is expected)?

Gists for ES 1.5.0:

```
curl -s -XPOST localhost/test/t1/abc/_update?version=0 -d '{ "doc" : { "count": 1 }, "doc_as_upsert" : true }'
{ "_index": "test", "_type": "blah", "_id": "abc", "_version": 1 }

curl -s -XPOST localhost/test/t1/abc/_update?version=0 -d '{ "doc" : { "count": 1 }, "doc_as_upsert" : true }'
{ "_index": "test", "_type": "blah", "_id": "abc", "_version": 2 }
```

I would have expected the second call to fail as calling again with version set to 2 does fail as expected:

```
curl -s -XPOST localhost/test/t1/abc/_update?version=2 -d '{ "doc" : { "count": 1 }, "doc_as_upsert" : true }'
{ "_index": "test", "_type": "blah", "_id": "abc", "_version": 3 }

curl -s -XPOST localhost/test/t1/abc/_update?version=2 -d '{ "doc" : { "count": 1 }, "doc_as_upsert" : true }'
{"error":"VersionConflictEngineException[[test][3] [blah][abc]: version conflict, current [3], provided [2]]","status":409}
```

Update API doesn't have the op_type query parameter like the Index API does, which would be another way to achieve this

**Comment by chriswhite199** [comment]
Some context - i previously had used a scripted upsert to achieve counter increments in ES 1.1.1, but moving to ES 1.5.0 and scripting being more frowned upon for security reasons i'm looking to do a document get, and then upsert (with incremented counter value or 1 where the document didn't exist in my get call) passing the version acquired from the previous get.

**Comment by clintongormley** [comment]
Hi @chriswhite199 

Version numbers start at 1, so a version of zero is ignored.  It doesn't make sense to use version numbers with upserts as a version number can never match a missing doc.  Really you want to use the create API here instead.

Regarding scripts, there is nothing to stop you from having the script saved in a file in config/scripts/ and using it in your update command. File scripts don't suffer from the same problems as inline scripts.
