### ISSUE TITLE
Throw An Error For Missing or Bad Config Values for AWS-Cloud Plugin

### ISSUE THREAD

**Issue by hjc1710** [elastic/elasticsearch#12657]
I ran into a stack trace today that referenced an [old issue](https://github.com/elastic/elasticsearch-cloud-aws/issues/31#issuecomment-127756166) related to the `aws-cloud` plugin. The issue basically boils down to this: I had `cloud.aws.secret` as my config value and not `cloud.aws.secret_key` (the latter is correct).

Now, elasticsearch failed to boot (as one would expect), but the main issue was the error message it gave me on boot failure did not clearly indicate that I had bad or missing config values. It just referenced proxy objects and circular references. It took me a good deal of tinkering in my config to figure out my root cause.

Now, what do I think can be done about this? In my opinion, a very nice feature to add to the AWS-Cloud plugin would be something that verifies that the given config values for the `cloud.aws` namespace are all present and correct. In my scenario, it would have noticed that `cloud.aws.access_key` was set, but `cloud.aws.secret_key` was not, and would have thrown an error indicating just that, which would have saved me 10-20 minutes.

However, I think this can be taken a step **further** and a new feature could be added to elasticsearch itself that would make this even easier. This new feature would basically amount to throwing an error any time an unknown config value is encountered. So, in my case, an error would be thrown because neither elasticsearch, or any of its installed plugins, has `cloud.aws.secret` listed as a valid config value. This would have alerted me to my issue almost immediately and would have been a wonderful user experience that would have made DevOps faster, and more pleasant. Basically, the way I envision this working, is that elasticsearch would have its own set of allowed config values and then all ES plugins installed are also allowed to have a set of allowed config values; upon boot, ES parses it's config file and references every key found with itself and its plugins, and then throws an error the second it finds an unknown key. 

To me, the former is merely an improvement to the `cloud-aws` plugin, but the latter is an actual elasticsearch improvement that should make DevOps management of elasticsearch easier in general (no more guessing about the validity of your config; if you put in a bum key name, elasticsearch just doesn't boot). Extrapolating on all of this, adding another runnable to `bin` that validates an elasticsearch config, ensuring all keys present are expected keys with valid values, would be pretty great too. That tool could then be integrated into more elaborate build systems, such as Jenkins, to verify the validity of any new ES configs before deploying them (though I'm not sure how many people regularly edit their ES configs and deploy those through some sort of CI process).

If any of this is unclear, or there are any questions, I am more than happy to answer them.

The comment that started this whole thing, and what prompted David to refer me to create this issue can be found [here](https://github.com/elastic/elasticsearch-cloud-aws/issues/31#issuecomment-127754817).

**Comment by clintongormley** [comment]
Splendidly explained, @hjc1710 - thank you

This is on our list of improvements to make, even though it has been hanging around for a long time.  Closing in favour of https://github.com/elastic/elasticsearch/issues/6732

**Comment by hjc1710** [comment]
Awesome, it's good to know that the ES team already saw this as an improvement that could be made and have it written down!

Hopefully someone will get the throughput to squash that older issue sometime soon. Regardless, you guys rock, keep up the great work!

Going to go to the other issue now and voice my support.
