### ISSUE TITLE
Make _version searchable without a script

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#12658]
Currently, the only way to search against the `_version` field is to create a script (preferably not dynamic, but this is just an example):

```json
{
  "query": {
    "filtered": {
      "filter": {
        "script": {
          "script": "doc['_version'].value > version",
          "params" : {
            "version" : 1
          }
        }
      }
    }
  }
}
```

However, like any script, this adds some unnecessary overhead. It would be ideal if we could use the field like other fields:

```json
{
  "query": {
    "filtered": {
      "filter": {
        "range": {
          "_version" : {
            "gt" : 1
          }
        }
      }
    }
  }
}
```

**Comment by drewr** [comment]
Does that work? I get `MissingPropertyException[No such property: _version for class: Script1]` when I try a script.

**Comment by pickypg** [comment]
Works in 1.6.0, which I am running locally.

**Comment by drewr** [comment]
Mine was on a 2.0 build from a few weeks ago, c315d54c.

**Comment by pickypg** [comment]
Also works with ES 1.7.1.

**Comment by drewr** [comment]
A lot changed with `_version` in 2.0, IIRC. Seems to be a byproduct of converting from a `Map` to `LeafDocLookup`. But searching on `_version` never was a good idea anyway since it's ephemeral. I don't think we've ever wanted to support that?

**Comment by rmuir** [comment]
Its not indexed, lets not try to search it

**Comment by asgs** [comment]
@rmuir is `_version` intended to be not indexed and not searchable?
