### ISSUE TITLE
elasticsearch how to partition data by day?

### ISSUE THREAD

**Issue by tzou** [elastic/elasticsearch#12663]
Hi:
es group guys!

I've used es for days.Recently i found a situation that how can i use es to partition my data by days.
Like sql "partitioned by day"
I find an es bolg about this : 
https://www.elastic.co/blog/what-is-an-elasticsearch-index
It says we can use like this:
$ curl -XGET localhost:9200/logs-2013-02-22,logs-2013-02-21/Errors/_search?query="q:Error Message"

But i'd like to use like this (e.g by sql): select * from esDB.table where day<=20150130 and day>=20150101 limit 50;
In addition,how can i use es to index data partitioned by day and search data by range of days? 

many thanks

**Comment by jpountz** [comment]
Please ask questions on the [forums](http://discuss.elastic.co), we want to keep Github issues for bugs and feature requests.
