### ISSUE TITLE
Provide Update details to Index Transform scripts

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#12662]
Currently, index transformers behave like triggers that allow you to mutate the incoming document without effecting the stored `_source`. It would also be useful if you could do other things, similar to the Update API, to block/log indexing operations based on selected criteria.

On the topic of blocking things, it would also be useful to pass in what the current operation is: a create or an update (since delete's aren't transformed, this can probably be a boolean). If not too unreasonable, as the document is on the same node and probably in memory already, it may be worthwhile to also pass in the previous version of the document so that old fields can be transformed (e.g., an indexed, trigger-based version field). This should allow true trigger-like manipulation.

**Comment by clintongormley** [comment]
@pickypg this makes me want to run away screaming.  why on earth would you want to add this complexity to Elasticsearch?  Honestly, I'd prefer to remove the source transform script altogether.

**Comment by pickypg** [comment]
The source transform is going away in ES 2.0 with #12674, so this is irrelevant.

If the transform reappears in a plugin, then I hope that it gains this feature because anyone using the source transformation as it is today should make changes on the client side to fix the data rather than writing scripts (that will slow things down!) to fix it on the other side. Adding trigger-like support adds support for use cases that aren't possible otherwise.
