### ISSUE TITLE
Completion field should be under multifield type

### ISSUE THREAD

**Issue by robertnadar** [elastic/elasticsearch#12672]
i believe the the completion field should be defined under CorePropertiesDescriptor.cs class since we should be able to define the completion type under multi-field type

e.g.
 "properties" : {
          "audience" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "author" : {
            "type" : "string",
            "fields" : {
              "raw" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "suggestive" : {
                "type" : "completion",
                "analyzer" : "simple",
                "payloads" : true,
                "preserve_separators" : true,
                "preserve_position_increments" : true,
                "max_input_length" : 50
              }
            }
          },

**Comment by clintongormley** [comment]
This issue was moved to elastic/elasticsearch-net#1512
