### ISSUE TITLE
Unable to update document

### ISSUE THREAD

**Issue by XDestination** [elastic/elasticsearch#12676]
Following scenario: We are updating (upserting) lots of documents into an index in elasticsearch-cluster (2 data nodes). Today we increased the volume of those updates by roughly a factor of 10. After a few minutes (I would say 10 to 20) we suddenly saw lots of errors returned by elasticsearch. All of those were like the following one:

`RemoteTransportException[[SERVER_NAME][inet[/SERVER_IP:9300]][update]]; nested: ElasticsearchIllegalArgumentException[failed to execute script]; nested: NoSuchElementException;`

The body of those requests always looks like that:
    {
    	script: 'ctx._source.FIELD_1 = PARAM_1; ctx._source.FIELD_2 = PARAM_2',
    	params: {
    	    	PARAM_1: "some string",
    	    	PARAM_2: 124
    	},
    	upsert: {
    	    	PARAM_1: "some string",
    	    	PARAM_2: 124
    	}
    }

I played around a bit with the update and it worked (at least in this case) once I removed the update for FIELD_2/PARAM_2.

Additionally I tried a couple of things to fix the issue:
* Repeating the requests after a few seconds
* Reducing/Increasing the value of retry_on_conflict
* Replacing retry_on_conflict by loop + loopcounter and a timeout

Nothing worked. In the end I restarted the data-node that was holding (at this time) all primary shards, which finally seemed to have solved it for now.

Any ideas why this happened? Any suggestions what to try, in case it happens again?

**Comment by clintongormley** [comment]
Hi @XDestination 

I assume your update uses "FIELD_1/2" and not "PARAM_1/2"?  What version of ES are you on? Are you using groovy or mvel? Inline scripts or file scripts? Anything else in the logs?

**Comment by XDestination** [comment]
Hi,
you are right. PARAM_1/2 is wrong of course, we are in fact using the same field name in the script and then in the params/upsert object.
This cluster is currently running on version 1.3.7
As scripting language we are using the default one: mvel
The scripts are sent with the request, so no file based scripts
Thats the weird thing. The logs actually show nothing at all :/

**Comment by clintongormley** [comment]
OK - this may well be an mvel bug with concurrency. I'd suggest moving to groovy and seeing what happens.

**Comment by XDestination** [comment]
Even if the update fails a couple of minutes later too (And therefore no other updates related to that document are being executed.)?

**Comment by clintongormley** [comment]
@XDestination that'd be my guess.  try it and see, the syntax should be pretty similar

We removed MVEL because of issues like this

**Comment by XDestination** [comment]
Okay. Thanks for the advice. I will give it a try :)

**Comment by clintongormley** [comment]
Nothing further. Closing
