### ISSUE TITLE
Boolean type coercion in multifields

### ISSUE THREAD

**Issue by roytmana** [elastic/elasticsearch#12679]
It would be very nice if for property of any type a multifield with type boolean was supported by coercing the property value to boolean using following logic
- Integer - missing/null/0 - false otherwise true
- Boolean - null/false - false otherwise true
- Any other type (string, date) missing/null - false otherwise true

it will allow to aggregate (as bucket or metric) or filter on presence of a value very simply without polluting _source with pre-calculated flags

**Comment by clintongormley** [comment]
This works already:

  PUT t
  {
    "mappings": {
      "t": {
        "properties": {
          "int": {
            "type": "integer",
            "fields": {
              "bool": {
                "type": "boolean",
                "null_value": false
              }
            }
          },
          "string": {
            "type": "string",
            "fields": {
              "bool": {
                "type": "boolean",
                "null_value": false
              }
            }
          },
          "date": {
            "type": "date",
            "fields": {
              "bool": {
                "type": "boolean",
                "null_value": false
              }
            }
          }
        }
      }
    }
  }
  
  PUT t/t/true
  {
    "int": 5,
    "string": "foo",
    "date": "2015-01-01"
  }
  
  PUT t/t/false
  {
    "int": 0,
    "string": ""
  }
  
  PUT t/t/null
  {
    "int": null,
    "string": null,
    "date": null
  }
  
  GET t/_search
  {
    "fielddata_fields": [
      "int.bool",
      "string.bool",
      "date.bool"
    ]
  }

**Comment by roytmana** [comment]
thank you @clintongormley 
Yes it does work. I also was trying this route last night. the only downside is that it requires sending null as field value. it will not handle missing values. I know it is a bigger issue (setting default value for missing values) than this use case and it probably does not make awful lot of sense in context of general default value for missing but in this case it would be very convenient as it will allow 100% transparently without any change of data add a boolean multifield for presence of value providing much simpler queries/aggregations and most likely better performance comparing with missing filter/agg

so I guess my question is would it make sense to consider support of default value for missing values the way it is done for nulls?

**Comment by clintongormley** [comment]
@roytmana I don't think we should add yet another option for this.  If you want to take missing values into account, make them null in your application.

**Comment by roytmana** [comment]
ok, thank you @clintongormley. I am doing it now. just wanted to check with you. thanks again for looking into it
