### ISSUE TITLE
ArrayIndexOutOfBoundsException when using 2-level terms aggregation 

### ISSUE THREAD

**Issue by zhangwei17** [elastic/elasticsearch#12685]
I have the following _mapping info for the type
{
    "viva26": {
        "mappings": {
            "2655c2d1a7abe320": {
                "properties": {
                    "1": {
                        "type": "double"
                    },
                    "2": {
                        "type": "double"
                    },
                    "3": {
                        "type": "double"
                    },
                    "4": {
                        "type": "double"
                    },
                    "5": {
                        "type": "long"
                    },
                    "6": {
                        "type": "string"
                    }
                }
            }
        }
    }
}

I can use the data in it instantly after get data into ES for normal aggregation request even 2-level aggregation request . But just after several requests, the ES return the following failure response:
"error": "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[TeuXtz7zQqaz9oO-CCDwCA][viva26][0]: RemoteTransportException[[Starr the Slayer][inet[/10.207.161.38:9300]][indices:data/read/search[phase/query]]]; nested: ElasticsearchException[java.lang.ArrayIndexOutOfBoundsException]; nested: UncheckedExecutionException[java.lang.ArrayIndexOutOfBoundsException]; nested: ArrayIndexOutOfBoundsException; }{[zfw_Dwl7Rm-N5-sepQ5vVA][viva26][1]: RemoteTransportException[[Auntie Freeze][inet[/10.207.161.36:9300]][indices:data/read/search[phase/query]]]; nested: ElasticsearchException[java.lang.ArrayIndexOutOfBoundsException]; nested: UncheckedExecutionException[java.lang.ArrayIndexOutOfBoundsException]; nested: ArrayIndexOutOfBoundsException; }{[vFyU6GyqRVubZh4twRVETQ][viva26][2]: RemoteTransportException[[Desmond Pitt][inet[/10.207.161.40:9300]][indices:data/read/search[phase/query]]]; nested: ElasticsearchException[java.lang.ArrayIndexOutOfBoundsException]; nested: UncheckedExecutionException[java.lang.ArrayIndexOutOfBoundsException]; nested: ArrayIndexOutOfBoundsException; }{[TfXlVgnORvueAqE4ewxr0g][viva26][3]: RemoteTransportException[[Tyr][inet[/10.207.161.34:9300]][indices:data/read/search[phase/query]]]; nested: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value (-59) in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value (-59) in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value (-59) in prefixCoded bytes (is encoded value really an INT?)]; }{[HfDT5WIpRGOFa9Rqq3oX-Q][viva26][4]: RemoteTransportException[[Fasaud][inet[/10.207.161.20:9300]][indices:data/read/search[phase/query]]]; nested: ElasticsearchException[java.lang.ArrayIndexOutOfBoundsException]; nested: UncheckedExecutionException[java.lang.ArrayIndexOutOfBoundsException]; nested: ArrayIndexOutOfBoundsException; }]",
    "status": 500

The request is 2-level aggregation like this:
{"aggs":{"sum":{"terms":{"field":"5","order":{"sum":"desc"}},"aggs":{"sum":{"sum":{"field":"1"}}}}}}

The version of ES is 1.5.1

How can I resolve the problem?

**Comment by Stabaoc** [comment]
maybe you should add some query or filter

**Comment by clintongormley** [comment]
This sounds very much like you have a mapping problem, eg fields with the same name, in the same type, but with different mappings (long vs string perhaps?).

Alternatively, if you are relying on dynamic mapping to add fields, you may find that the field has been mapped as a long on one shard and as a string on another shard, but the official mapping only accepts one of these types.  As soon as the "wrong" shard moves to another node, everything breaks.

These issues have been fixed in 2.0 with https://github.com/elastic/elasticsearch/issues/8870.

To resolve this now:

* make sure you have no conflicting field names (the migration plugin can help you to identify this problem: https://github.com/elastic/elasticsearch-migration)
* if that doesn't work, try putting your mapping explicitly (when you create the index) and reindex your data

**Comment by zhangwei17** [comment]
Thanks a lot!
Finally we found that the problem will appear when field names with different core types are defined in multi types within current index.
