### ISSUE TITLE
copy_to creates multiple terms for not_analyzed strings

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#12680]
In trying to create a simple aggregate Group By field, I was attempting to use `copy_to` to combine 3 fields into one.

```json
PUT /test
{
  "mappings": {
    "result" : {
      "properties": {
        "groupby" : {
          "type": "string",
          "index": "not_analyzed"
        },
        "school" : {
          "type" : "string",
          "index": "not_analyzed"
          , "copy_to": "groupby"
        },
        "grade" : {
          "type" : "integer",
          "copy_to": "groupby"
        },
        "student" : {
          "type" : "string",
          "index": "not_analyzed",
          "copy_to": "groupby"
        }
      }
    }
  }
}
```

However, the problem is that the result ends up creating multiple terms for the `groupby` field. If I were to index the document:

```json
{ "grade": 2, "school": "Arbitrary", "student": "Chris" }
```

Then the value indexed to `groupby` would be `[ "2", "Arbitrary", "Chris" ]`. This means that it cannot be used for this purpose.

You can workaround this issue by using the index transformation to concatenate the values directly, but this is going away in Elasticsearch 2.0.

**Comment by clintongormley** [comment]
This is correct behaviour.  It is the equivalent of passing an array of values to the field.  The `_all` field works in the same way.  Its purpose is to create a custom `_all` field (out of potentially large text fields) which can be searched as if it were one field, not to create a single field value.  Concatenation raises other questions like what should the concatenation character be?

If you want to do this, you should simply provide the concatenated field in your document.
