### ISSUE TITLE
Optimize AzureBlobStore#delete method

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#12697]
_From @dadoonet on February 17, 2015 22:16_

When we have to remove a lot of files, method `AzureBlobStore#delete` is called for each file and generates a Azure API call.

Would be nice to see if we can batch somehow those calls instead.

_Copied from original issue: elastic/elasticsearch-cloud-azure#66_

**Comment by dadoonet** [comment]
@imotov As far as I understand the core code, I don't really think that it's doable. We need to process file deletion one by one, right?

**Comment by dadoonet** [comment]
_From @imotov on July 29, 2015 15:25_

@dadoonet actually when we delete a lot of files, we have a list of blobs that should be deleted and we simply iterate through the list. We can easily modify the logic to pass entire list to the store.

**Comment by imotov** [comment]
The feature in core was implemented and merged #12587. Now we need to take advantage of it in the azure plugin.

**Comment by dadoonet** [comment]
I believe that we can close it as we merged #18813. We can revisit it if at some point we find some optimizations in Azure SDK.
