### ISSUE TITLE
Add "name" to the plugin descriptor file

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12715]
Add "name" to plugin descriptor file, not what user provides

To be sane, probably needs to *not* have `elasticsearch-`. Another painful artifact renaming? (think difficult build issues)

**Comment by spinscale** [comment]
possible solution here: open the zip archive of the specified location, peek into the descriptor file and extract the name out of it?

**Comment by cbuescher** [comment]
I opened #12775 that adds a new mandatory property `plugin.name` to the plugin descriptor file which will overwrite the name that gets passed to the plugin CLI as an argument. See PR for some open questions I have around the overall goal and what this means for using the command line tool.

**Comment by cbuescher** [comment]
Merged #12775 with master, @clintongormley let me know if an when this should go to the release branch. It should be backported together with #12879 in this case.

**Comment by cbuescher** [comment]
Also merged #12775 with 2.0 (d236192c49a8941525e201e01edc781e5fc13dae). @clintongormley I think I can close this? Otherwise please reopen.
