### ISSUE TITLE
Fix cloud plugins to have real mocks for tests

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12719]
- These only have shallow tests and are fragile. we rely on users to report bugs
- need disco test in qa/ with mock ec2
- need snapshot test in qa/ with mock s3
- ideally use proxy too for testing that

**Comment by clintongormley** [comment]
@jasontedor please could you try to tackle this one

**Comment by dadoonet** [comment]
@clintongormley @jasontedor FYI I'm currently working on ec2 mock

**Comment by s1monw** [comment]
@dadoonet can you sync with @jasontedor on this please

**Comment by dadoonet** [comment]
For the record, @ywelsch just added some new tests for EC2 with #17677 
@s1monw already added tests for GCE with #16881

**Comment by williamrandolph** [comment]
I believe this work has been handled in #31107 and #29315.
