### ISSUE TITLE
Install and test core plugins in vagrant tests

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12717]
Vagrant tests should install and use all core plugins.

**Comment by nik9000** [comment]
Ok -I have a pull request to install all the plugins in vagrant - after that is merged I could try starting with them all installed an running smoke tests __but__ I think we should think about time here - it already takes 7 minutes to go through these tests on two operating systems. Could we get away with just verifying that the plugin installer puts the files in the right spots and do some kind of amalgomated smoke test of all the plugins in another module in the qa module?

**Comment by nik9000** [comment]
> Ok -I have a pull request to install all the plugins in vagrant - after that is merged I could try starting with them all installed an running smoke tests but I think we should think about time here - it already takes 7 minutes to go through these tests on two operating systems. Could we get away with just verifying that the plugin installer puts the files in the right spots and do some kind of amalgamated smoke test of all the plugins in another module in the qa module?

Update: I opened #13258 to start Elasticsearch with all the plugins installed so we can verify that they are listed in `_cat/plugins` at least.

**Comment by nik9000** [comment]
> Update: I opened #13258 to start Elasticsearch with all the plugins installed so we can verify that they are listed in _cat/plugins at least.

And I merged that. So this is closed.
