### ISSUE TITLE
queried words highlighting in fvh

### ISSUE THREAD

**Issue by eugene-dm** [elastic/elasticsearch#12722]
We use fast vector highlighter

<pre><code>
POST test
{
  "mappings": {
        "test" : {
            "_source" : { "enabled" : false },
            "properties" : {
                 "content": {
                  "term_vector": "with_positions_offsets",
                  "index_options": "offsets",
                 "type": "string",
                 "store": true,
                 "include_in_all": false
               }
            }
        }
  }
}
</code></pre>

Then put a text:

<pre><code>
POST test/test
{
  "content": "But nice it . Were the words stay hungry . Stay Foolish . It was their farewell message . As they signed off . Stay hungry . Stay Foolish . And I've always wished that . For myself . And now . As you graduate to be ."
}
</code></pre>

Then search:

<pre><code>
GET test/test/_search
{
    "highlight": {
        "fields": {
            "content": {
                "number_of_fragments": 1000,
                "fragment_size": 30
            }
        },
        "pre_tags": ["<b>"],
        "post_tags": ["<\/b>"],
        "encoder": "html"
    },
    "query": {
        "filtered": {
            "query": {
                "query_string": {
                    "fields": [["content^1"]],
                    "default_operator": "AND",
                    "query": "\"stay\" OR \"foolish\""
                }
            }
        }
    }
}
</code></pre>

Result:

<pre><code>
"highlight": {
               "content": [
                  "words <b>stay</b> hungry . <b>Stay</b> Foolish",
                  "off . <b>Stay</b> hungry . <b>Stay</b> Foolish"
               ]
            }
</code></pre>

Last word "Foolish" don't have tags. I think a reason is in "fragment_size" algorithm. Elasticsearch founds snippets like "words stay hungry . Stay Fooli", then places tags, then extending to whole words and don't check, if new word is requested by query.

**Comment by nik9000** [comment]
> "fields": [["content^1"]],

Why an array in an array here?

**Comment by nik9000** [comment]
> I think a reason is in "fragment_size" algorithm

This is possibly the problem here. If this is the problem its not something we're going to fix quickly.... I think the [experimental highlighter](github.com/wikimedia/search-highlighter) has a higher chance of working properly here....

**Comment by nik9000** [comment]
Curl recreation: https://gist.github.com/nik9000/7c87e395d82565180390

**Comment by eugene-dm** [comment]
Experimental plugin works for this case, hanks

**Comment by eugene-dm** [comment]
Sorry, experimental plugin works like a charm.
Big thank you

**Comment by nik9000** [comment]
Sure!

I'm sorry you had trouble with the others.

**Comment by eugene-dm** [comment]
Unfortunately experimental highlighter doesn't work correctly with phrases search, so waiting for resolution of this bug in core of elasticsearch.

**Comment by clintongormley** [comment]
Closing in favour of #21621
