### ISSUE TITLE
Remove wares transport plugin

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12721]
We think that the transport-wares plugin is probably little used and doesn't have a real purpose, so we are thinking of removing this plugin.

Do you have a use case? If so, please tell us about it?

Pinging people who have starred the repo:  @allenhu, @aponb, @AshwinJay, @avengerpenguin, @boyce-ywr, @cabadsanchez, @carchrae, @ccw-morris, @cpliakas, @cwensel, @cythrawll, @d1rtym0nk3y, @davidmr001, @dlobue, @dmitrygusev, @egaumer, @gaurav46, @guanyum, @gustaveiffel, @jeffreyaikin, @ker2x, @ksclarke, @kyoken74, @lukas-vlcek, @maonsbatsis, @mhvenkat, @nedgot, @netconstructor, @paikan, @pfiled, @philshon, @pkadetiloye, @rseixas, @seralf, @ssp, @voodoorider, @whateverdood, @zepag

**Comment by seralf** [comment]
I've tested mainly for developing self-contained prototypes

Alfredo

2015-08-07 11:43 GMT+02:00 Clinton Gormley <notifications@github.com>:

**Comment by clintongormley** [comment]
@seralf so you're saying that you wouldn't miss it?

**Comment by seralf** [comment]
I didn't use it very often to be honest

but I think it could be extended for prototyping or to be used as an
example on how to create plugins in itself, I'm not sure about the benefit
of completely removing it, while it will continue work. Just an idea

2015-08-07 11:52 GMT+02:00 Clinton Gormley <notifications@github.com>:

**Comment by cpliakas** [comment]
Thanks for pinging. Plugin seemed cool to work ES in to an existing architecture, however that architecture has changed so we do not have a need for this plugin.

**Comment by SMUnlimited** [comment]
We currently use this to abstract away the elasticsearch configuration away into a utility webapp. This webapp contains all our business API logic for interacting with elasticsearch. We setup NodeServlet so that they can still make direct elasticsearch rest calls for any other logic we don't provide.

**Comment by carchrae** [comment]
a few years ago, i adapted this code to work on playframework (https://github.com/carchrae/elastic-play), it was very helpful to have this example of the elasticsearch processing api.   however, i'm not using that right now.  the motivation for that was being able to elasticsearch and a server on a heroku instance with S3 for persistent storage.

**Comment by roytmana** [comment]
@clintongormley is the plugin the same as transport-wares project that allows embedding elastic into a servlet application? I assume it is not the same but if it is, I would like to keep it very much as we and quite a few people I know use it for small embedded single node elastic deployments

**Comment by dadoonet** [comment]
@clintongormley What is the status on this?

**Comment by benoitdechateauvieux** [comment]
@clintongormley we use the transport-wares plugin to start our embedded ES instance when our application starts.
Is there another way to do it ? If not, could you plan to release a version of this plugin for ES 2.0 ?

**Comment by roytmana** [comment]
+1

**Comment by wasifaleem** [comment]
We use it to add strict role based authentication and authorization.

**Comment by apatrida** [comment]
We used it to proxy and limit or modify queries as they passed through while allowing others to invisible "just be handled"   but that code is old and in use, but not sure would continue in the same way in the future.

**Comment by HardyLoppmann** [comment]
Hi, I´m interested at these plugin, too but I´ve got another reason. We are implementing a full text search for a huge customer, which has a difficult approve process for products like elasticsearch. If you want to use a new product or self hosted service you have to fill about ~1000 documents ;-) If you use a already approved servlet engine like a tomcat, jboss or weblogic you can elasticsearch without any problems. At the moment I use ES 1.7.0

**Comment by roytmana** [comment]
Exactly the same here. Approved platforms and mountains of red tape and paperwork for anything else particularly security aspects

**Comment by ArunYokesh1** [comment]
Same here. Organisational procedures , get an elasticsearch cluster as a standalone app in my current organisation is big and hard to realise soon.

 Is there any plan to release a package supporting ES 2.0.0 ?

**Comment by thomasdelhomenie** [comment]
What is the status?
We are using this plugin to start our embedded ES instance when our application starts. We are using ES 1.7 and we plan to upgrade to 2.2.

**Comment by sDaniel** [comment]
"Introduce a new standalone technology? Sure lets discuss this for a year or two then maybe we'll think about it." But "Deploy yet another war? Fill out standard form and you are good to go." 

It can be a good way to get started and then later you can go "It really would be better to have normal  cluster setup."

This "plugin" could be a good starting point for some organisations that won't use ES otherwise but lacks documentation - see also a ready to use version of the plugin would help here: https://github.com/elastic/elasticsearch-transport-wares/pull/8

**Comment by manosbatsis** [comment]
We also use this plugin to embed an elasticsearch node to a number of apps for clients. Is this going to support 2.2.0?

**Comment by dakrone** [comment]
Given that we are moving towards a non-embeddable version of Elasticsearch (see: https://www.elastic.co/blog/elasticsearch-the-server), I am going to close this since it seems like we are not going to maintain elasticsearch-transport-wares.
