### ISSUE TITLE
Batch up cluster state events spawning from fault detection failures

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#12734]
Have a scenario where a large number of new nodes were added to a 1.4.1 cluster (allocation disabled so no data is allocated to them yet) but the networking rules have not yet been set up yet (?).  This is causing fault detection pings to fail against all of these nodes.  As a resulting the pending task list was showing 70+ immediate tasks like the following (with one being executed):

```
    {
      "insert_order": 3524021,
      "priority": "IMMEDIATE",
      "source": "zen-disco-node_failed([data76][weK5x8_yT6O7CWuRaDpNGQ][data76][inet[/10.130.0.19:9300]]{master=false}), reason failed to ping, tried [3] times, each with maximum [30s] timeout",
      "executing": true,
      "time_in_queue_millis": 72182,
      "time_in_queue": "1.2m"
    }
```

This causes other cluster state event tasks like put mapping, etc.. to fail due to a timeout.

Discussed briefly with @kimchy .  He noted that we should batch up the node-removals-due-to-ping-failures tasks.

**Comment by clintongormley** [comment]
Fixed in 2.2
