### ISSUE TITLE
Expose ClassloadingMXBean in stats

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#12738]
There are various scripting engines and caching and other complexity, I think we should expose basic stats about classes in the JVM to assist with debugging:

* number of currently loaded classes
* total number of loaded and unloaded classes ever.

http://docs.oracle.com/javase/7/docs/api/java/lang/management/ClassLoadingMXBean.html

**Comment by tlrx** [comment]
+1, I made a pull request for that.
