### ISSUE TITLE
Disk allocation with default settings allows the disk to fill up past 88%, ignoring the 85% low watermark

### ISSUE THREAD

**Issue by dmehra** [elastic/elasticsearch#12745]
I'm observing the following behavior in our 5-node ES cluster (1TB drive on each node): we run with default settings for the disk allocation policy (ie: we did not override the policy itself, or the 85%,90% default watermarks). I expect that, once disk utilization on a node goes above 85%, shards would no longer be allocated to that node, but this is not the case. When my cluster had 3 nodes, on 07/31 I saw the 85% watermark being hit:
```
[2015-07-31 23:06:06,291][INFO ][cluster.routing.allocation.decider] [node-ca575976-f63d-4380-a94e-fad3a9900aa6] low disk watermark [15%] exceeded on [j4BdtG8pSUCLiHlU4SVBWw]
[node-9895fc4e-afc6-4165-a136-638d57767537] free: 146.2gb[14.8%], replicas will not be assigned to this node
```
However, when I expanded the cluster first to 4 nodes on 08/01, then to 5 nodes on 08/05, and continued ingesting data such that disk utilization went back up past 85% on the original nodes, I didn't see them logging any messages about exceeding the watermark. I don't see the disk usage exceeding 90%, so at some point ES must be doing its reallocation magic, but there is no evidence of that in the logs; and disk usage routinely exceeds 85%. 

Current disk usage (from `df -h` on each node):
```
de0  985G  815G  121G  88% /mnt
de1  985G  810G  125G  87% /mnt
de2  985G  800G  135G  86% /mnt
de3  985G  739G  196G  80% /mnt
de4  985G  451G  484G  49% /mnt
```

We create a new ES index for each day, and set the number of shards equal to number of nodes in the cluster, so my older indices have 3 shards, then from 08/01 to 08/05 4 shards, and after 08/05 5 shards per daily index. I imagined that ES would place more shards on the empty-ish disk on node de4 that i added last, instead of continuing to put shards on de0, de1, de2 which are all over 85% full, but that is not happening. For the last full day 08/08, I see an index of size 17GB put on each of the 5 nodes; and the day of 08/09 that recently started is also getting data on all 5 nodes. 

I'm looking for help to understand how reallocation works on my cluster. If ES is doing the expected thing,  then I will think about the right settings for the watermarks, and for my app (we currently have a 90% "stop ingest" threshold at the layer above ES, and ES cluster behavior seems to take us dangerously close to hitting that limit). Or perhaps I'm hitting an allocation bug and that's why my disks are filling up beyond 85%? 

Happy to provide additional data if needed, here are some settings that I know how to read out. We run ES version 1.5.0.
```
curl -XGET 'http://localhost:9200/_cluster/health' |python -mjson.tool
{
    "active_primary_shards": 353,
    "active_shards": 353,
    "cluster_name": "campfire.production.local",
    "initializing_shards": 0,
    "number_of_data_nodes": 5,
    "number_of_nodes": 5,
    "number_of_pending_tasks": 0,
    "relocating_shards": 0,
    "status": "green",
    "timed_out": false,
    "unassigned_shards": 0
}
```
Settings for one recent index:
```
curl -XGET 'http://localhost:9200/events-default@2015.08.09/_settings' |python -mjson.tool 
{
    "events-default@2015.08.09": {
        "settings": {
            "index": {
                "analysis": {
                    "analyzer": {
                        "jut_analyzer": {
                            "filter": [
                                "lowercase",
                                "word_delimiter"
                            ],
                            "tokenizer": "standard",
                            "type": "custom"
                        }
                    }
                },
                "creation_date": "1439078400496",
                "number_of_replicas": "0",
                "number_of_shards": "5",
                "uuid": "J-Zm3XzpRLu4dxdD-luacQ",
                "version": {
                    "created": "1050099"
                }
            }
        }
    }
}
```

**Comment by dakrone** [comment]
This is related to https://github.com/elastic/elasticsearch/issues/11271, and happens because the DiskThresholdDecider averages out the usage for all the `path.data` disks, so the average is still below 85%

**Comment by clintongormley** [comment]
Closing in favour of #11271

**Comment by dmehra** [comment]
I read both the documentation at https://www.elastic.co/guide/en/elasticsearch/reference/current/disk.html, and the notes in https://github.com/elastic/elasticsearch/issues/11271, to mean that the disk usage calculation happens separately for each ES node (but gets averaged if there are multiple path.data disks on a node). In my case, there are 5 ES nodes in the cluster, so it is surprising that disk usage for the threshold is averaged across all of them. If this behavior is to remain, it would be good to update the documentation accordingly. 

Could I get a recommendation for how to get my cluster better rebalanced? To trigger reallocation of shards with my current state of de4 at 54% full and other disks at 84-89% full, I'm guessing I need to set the watermarks at something like 70% and 75%. Is this the advised way? Thank you.

**Comment by dakrone** [comment]
@dmehra I'm sorry, I misunderstood your original post, I saw the disk listing and thought that was from a single node with 5 data paths in the listing (in which case it would be averaged). ES doesn't average across all the nodes (as the documentation correctly states). I'll re-open this.

**Comment by dakrone** [comment]
@dmehra did you happen to notice for the nodes over 85% whether they had shards currently relocating away from them? When ES calculates the disk usage it tries to take relocating shards into account, so I'm wondering if maybe it thought it was only over the low threshold because of that.

**Comment by dmehra** [comment]
The ES logs on all nodes were completely quiet, so based on that, no there wasn't any relocation going on; is there a better way to check?

**Comment by dakrone** [comment]
@dmehra you can see it either in the cluster state, or the `/_cat/shards?v` output will tell you if a shard is relocating (the easiest to read human-wise)

**Comment by dakrone** [comment]
@dmehra you can also increase the logging level for the "cluster" package and you can see the calculations that ES does for the free disk on the nodes and how big each shard is, that would be quite helpful if you have that info.

**Comment by dmehra** [comment]
Ok, my nodes are now at 88%,89%,86%,88% and 73% full. On all of them, all shards report STARTED state according to `curl -XGET 'http://localhost:9200/_cat/shards?v'`, i don't see any relocating shards. 

However, I have figured out where the logs are; I now understand that only the ES master node logs about the watermark (not the nodes on which the watermark is in fact exceeded), and my master node has shifted to the newest node I added, so now I see it's been logging about the watermarks the whole time quite verbosely, every 30 seconds. Here is a sample of log messages:
```
[2015-08-11 18:09:56,508][INFO ][cluster.routing.allocation.decider] [node-e458c8ad-fdcf-46b0-b6d2-a1a0ec7175c7] low disk watermark [15%] exceeded on [VI3QaNWDQcC8bHZqSKDs5Q][node-ca575976-f63d-4380-a94e-fad3a9900aa6] free: 118.5gb[12%], replicas will not be assigned to this node
[2015-08-11 18:09:56,508][INFO ][cluster.routing.allocation.decider] [node-e458c8ad-fdcf-46b0-b6d2-a1a0ec7175c7] low disk watermark [15%] exceeded on [iZiQJM_JSvOiULq6tnJXTw][node-62be99da-c545-461e-8f85-f1d5ef679f9b] free: 134.6gb[13.6%], replicas will not be assigned to this node
[2015-08-11 18:09:56,508][INFO ][cluster.routing.allocation.decider] [node-e458c8ad-fdcf-46b0-b6d2-a1a0ec7175c7] low disk watermark [15%] exceeded on [If-K_WFWQ6G3sarNu5gk3Q][node-9895fc4e-afc6-4165-a136-638d57767537] free: 109.8gb[11.1%], replicas will not be assigned to this node
[2015-08-11 18:09:56,508][INFO ][cluster.routing.allocation.decider] [node-e458c8ad-fdcf-46b0-b6d2-a1a0ec7175c7] low disk watermark [15%] exceeded on [ty1fKrvZRoeyT6UqVlLRXw][node-03c4a439-bd99-4654-9f8d-8fd0718e844e] free: 121.5gb[12.3%], replicas will not be assigned to this node
```
The above is from current time; the reports of exceeding the watermark started on 08/06 when space usage was lower, here is the first instance for each node:
```
[2015-08-06 20:20:15,987][INFO ][cluster.routing.allocation.decider] [node-e458c8ad-fdcf-46b0-b6d2-a1a0ec7175c7] low disk watermark [15%] exceeded on [VI3QaNWDQcC8bHZqSKDs5Q][node-ca575976-f63d-4380-a94e-fad3a9900aa6] free: 147.3gb[14.9%], replicas will not be assigned to this node

[2015-08-08 00:01:20,360][INFO ][cluster.routing.allocation.decider] [node-e458c8ad-fdcf-46b0-b6d2-a1a0ec7175c7] low disk watermark [15%] exceeded on [iZiQJM_JSvOiULq6tnJXTw][node-62be99da-c545-461e-8f85-f1d5ef679f9b] free: 145.8gb[14.8%], replicas will not be assigned to this node

(for this node, we somehow hit the high watermark *first*, and then after some reallocation hit the low watermark, this strikes me as an odd timeline)
[2015-08-08 06:12:20,602][INFO ][cluster.routing.allocation.decider] [node-e458c8ad-fdcf-46b0-b6d2-a1a0ec7175c7] high disk watermark exceeded on one or more nodes, rerouting shards
[2015-08-08 06:12:20,647][WARN ][cluster.routing.allocation.decider] [node-e458c8ad-fdcf-46b0-b6d2-a1a0ec7175c7] After allocating, node [If-K_WFWQ6G3sarNu5gk3Q] would have less than the required 10% free disk threshold (9.8% free), preventing allocation
[2015-08-08 06:30:20,615][INFO ][cluster.routing.allocation.decider] [node-e458c8ad-fdcf-46b0-b6d2-a1a0ec7175c7] low disk watermark [15%] exceeded on [If-K_WFWQ6G3sarNu5gk3Q][node-9895fc4e-afc6-4165-a136-638d57767537] free: 146.4gb[14.8%], replicas will not be assigned to this node

[2015-08-09 16:53:21,985][INFO ][cluster.routing.allocation.decider] [node-e458c8ad-fdcf-46b0-b6d2-a1a0ec7175c7] low disk watermark [15%] exceeded on [ty1fKrvZRoeyT6UqVlLRXw][node-03c4a439-bd99-4654-9f8d-8fd0718e844e] free: 147.3gb[14.9%], replicas will not be assigned to this node
```
Given that final space usage on the nodes is higher than 85%, and the fact that I see shards with non-negligible space usage stored on days after we hit the low watermark, something seems funny. For example, on my node de0 which is [VI3QaNWDQcC8bHZqSKDs5Q] that exceeded the low watermark on 08/06, there are shards stored on 08/08-08/11, and at no time did disk usage on it drop back below 85%.
```
17G     /mnt/elasticsearch/campfire.production.local/nodes/0/indices/events-default@2015.08.08
16G     /mnt/elasticsearch/campfire.production.local/nodes/0/indices/events-default@2015.08.09
44G     /mnt/elasticsearch/campfire.production.local/nodes/0/indices/events-default@2015.08.10
35G     /mnt/elasticsearch/campfire.production.local/nodes/0/indices/events-default@2015.08.11
```
If you'd like me to upload the log from master node, I can do that; if additional logging is needed, please advise how to turn it on, ideally at runtime without restarting ES.

**Comment by dakrone** [comment]
@dmehra it looks to me like your servers are undergoing the desired behavior, once they get about 85% percent full, they won't allow any new shards to be allocated to the node (the low watermark) and if they get over 90% full (the high watermark), shards are relocated away from the node in order to prevent them from going over the disk limit.

It's totally possible for a node to be over 85% (as long as it's under 90%) because a shard can be relocated to a node, bringing it to 84.9% disk usage, then more documents can be indexed, increasing the size of the shard above the 85% low watermark (which is why we have two watermarks).

Does that make sense? If you want the disk to never go over 85% full, you need to set the **high** watermark to 85% instead of the default 90%.

**Comment by dmehra** [comment]
We did additional experiments on our end and validated that ES behaves as expected in our expansion scenario - thank you!
