### ISSUE TITLE
[Warning][Ubuntu] Warning abouy package quality.

### ISSUE THREAD

**Issue by SalahAdDin** [elastic/elasticsearch#12746]
See please:

```
The installation of any package that violate quality standards is not allowed. That could cause serious problems to your computer. Contact the person or organization who gave you this package file and include the details below.
```

This appears when i try install elasticsearch in Ubuntu with the debian package.
Please review this,

**Comment by clintongormley** [comment]
> and include the details below.

What were those details?

**Comment by SalahAdDin** [comment]
This warning comes when I went to install elasticsearch in ubuntu, I did not get more data, just told me it was better not to install the package. I ignored the warning and equal Elasticsearch installed.

**Comment by clintongormley** [comment]
Hi @SalahAdDin 

OK - without that other information, we can't do much about this ticket, so I'm going to close for now. If you manage to find it, please open a new ticket.

thanks

**Comment by nik9000** [comment]
I've been installing elasticsearch on ubuntu for a year and a half and not
seen that message. If you have exact reproduction steps I'd love to see
them. Including which elasticsearch youdownloaded and which ubuntu you ran
it on.

**Comment by SalahAdDin** [comment]
I see that will be for the new ubuntu release: 15.04, for the other versions i don't know.

**Comment by nik9000** [comment]
This is what I get:
```
vagrant@vagrant-ubuntu-vivid-64:~$ uname -a
Linux vagrant-ubuntu-vivid-64 3.19.0-23-generic #24-Ubuntu SMP Tue Jul 7 18:52:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
vagrant@vagrant-ubuntu-vivid-64:~$ sudo dpkg -i elasticsearch-1.7.1.deb 
Selecting previously unselected package elasticsearch.
(Reading database ... 69040 files and directories currently installed.)
Preparing to unpack elasticsearch-1.7.1.deb ...
Creating elasticsearch group... OK
Creating elasticsearch user... OK
Unpacking elasticsearch (1.7.1) ...
Setting up elasticsearch (1.7.1) ...
Processing triggers for systemd (219-7ubuntu6) ...
Processing triggers for ureadahead (0.100.0-19) ...
```
