### ISSUE TITLE
Plugin manager should verify that it can write to all directories

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12749]
The plugin manager needs to validate it can write to the appropriate directories before it starts. Pretty sure today (1.x at least) it will half install a plugin when it can't write to certain directions

**Comment by spinscale** [comment]
checked the code. There are no write permissions checks for `bin/$PLUGIN/` and `config/$PLUGIN/` - also you are right, we copy the plugin into the plugins directory and then try for `bin` and `config` directory, hoping all is fine...
