### ISSUE TITLE
License/SHA checker not running?

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12752]
I think the `check_license_and_sha.pl` script is not doing its job currently.  The `distribution/pom.xml` points to `${basedir}/../licenses` (see https://github.com/elastic/elasticsearch/blob/master/distribution/pom.xml#L111 and https://github.com/elastic/elasticsearch/blob/master/distribution/pom.xml#L119) while the licenses directory is actually in `${basedir}/licenses`, so the check just gets skipped as far as I can see.

Also, we're no longer using this script to check the plugins.

**Comment by rmuir** [comment]
It can't be lenient anymore: we have to require this `licenses` directory or something like that. There is too much confusion about when it runs and when it does not run.

Leniency is the root of all evil. It is why elasticsearch is so fucked up.

**Comment by clintongormley** [comment]
The only reason it was lenient was because it was in the parent pom, and so only ran for any project which contained a licenses directory.  Now that we're adding it only to specific poms then I think we're good.

**Comment by rmuir** [comment]
I think licenses directory should just be mandatory. If its supposed to be lenient: then non-existing licenses directory means "no dependencies". 

I know git is a broken version control system that eats shit on empty directories, but we have to keep our sanity regardless of that.

I think license checker should run for every single module we release, it is too important because it also validates that the jars we think should be in the package are in fact there.

**Comment by clintongormley** [comment]
I agree - it was in the parent pom so it was enabled for all modules, but some don't need license directories (eg dev-tools).  It's already in the distribution pom (i'll remove the skip clause) and i'll add it to the plugins pom so it runs for all plugins. (as part of the integration tests, or just normal mvn verify?)

**Comment by rmuir** [comment]
Lets move it back to the parent. I think the issue was it didn't have a ` <skip>${skip.integ.tests}</skip>` before. This is important for the silly "pom-only" packages and stuff like dev-tools. For those the build will set this variable automatically so things should "just work"

**Comment by clintongormley** [comment]
With the move to `distributions/` the paths to the licenses directory and which dir/zipfile to check changed, so the distributions are different from the plugins.  What I'll try doing is:

* put it in the parent pom
* store the path and target values in a var
* override these values in distribution/pom

that make sense?

**Comment by rmuir** [comment]
+1
