### ISSUE TITLE
CLI parsing no longer supports single-dash parameters

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12751]
It looks like no parameters of the form `-Des.xxx` are supported by bin/elasticsearch now, yet this form is still documented in various places:

    docs/reference//indices/shadow-replicas.asciidoc:`-Des.security.manager.enabled=false` with the parameters while starting
    docs/reference//migration/migrate_1_0.asciidoc:* Command line settings can now be passed without the `-Des.` prefix, for
    docs/reference//setup/as-a-service.asciidoc:`ES_JAVA_OPTS`::          Any additional java options you may want to apply. This may be useful, if you need to set the `node.name` property, but do not want to change the `elasticsearch.yml` configuration file, because it is distributed via a provisioning system like puppet or chef. Example: `ES_JAVA_OPTS="-Des.node.name=search-01"`
    docs/reference//setup/configuration.asciidoc:`-Des.max-open-files` set to `true`. This will print the number of open
    docs/reference//setup/configuration.asciidoc:$ elasticsearch -Des.network.host=10.0.0.4
    docs/reference//setup/configuration.asciidoc:$ elasticsearch -Des.config=/path/to/config/file
    docs/reference//setup/configuration.asciidoc:$ elasticsearch -Des.index.store.type=memory
    docs/reference//setup.asciidoc:$ bin/elasticsearch -Xmx2g -Xms2g -Des.index.store.type=memory --node.name=my-node

Also, the `-d` option only works if it is the first command line parameter, which isn't documented either.

Not sure if the right thing to do is to change CLI parsing or to document the changes?

**Comment by clintongormley** [comment]
@spinscale what do you think?

**Comment by rmuir** [comment]
It is super confusing to see *es* parameters being recommended to go in ES_JAVA_OPTS.

I'm gonna be completely honest here, I don't think ES should allow for -D as an argument at all: ES just is not robust enough for the task. Its totally confusing where JVM versus ES properties should go to the user, and if you do the wrong thing, its totally lenient and gives you no error message at all, just silently doesn't work.

**Comment by clintongormley** [comment]
@rmuir not understanding the issues with -D, I tend to agree just for consistency's sake.  This just requires documentation then, and for `-d` (ie daemonize) either it should be documented that it must appear first in the args, or the parsing should be changed to support it wherever

**Comment by spinscale** [comment]
Clinton, not sure I understand what you mean with not supported here?

```
# bin/elasticsearch -Des.node.name=mynode
[2015-08-10 08:00:02,011][INFO ][org.elasticsearch.node   ] [mynode] version[2.0.0-beta1-SNAPSHOT], pid[4934], build[cdad9e6/2015-08-10T05:58:54Z]

# bin/elasticsearch -Dnode.name=mynode
[2015-08-10 08:00:08,969][INFO ][org.elasticsearch.node   ] [mynode] version[2.0.0-beta1-SNAPSHOT], pid[4967], build[cdad9e6/2015-08-10T05:58:54Z]

# bin/elasticsearch -Dnode.name=mynode -d
# jps
5010 Elasticsearch

# curl localhost:9200/_cat/master
id                     host ip             node
S6yQ-kXAQGOnbTlRmZhpOQ orca 192.168.178.36 mynode
```

What does not work, is using the java arguments as part of the parameters now ` bin/elasticsearch -Xmx2g` - this must be documented.

**Comment by clintongormley** [comment]
@spinscale Turns out it is a problem with wildcards again:

    bin/elasticsearch -Des.http.cors.enabled=true --http.cors.allow-origin='*'  -d

Fails with: 

    ERROR: Parameter [-d]does not start with --

This isn't fixed by https://github.com/elastic/elasticsearch/pull/12710 

Closing in favour of #12710
