### ISSUE TITLE
OOM when too many expired documents?

### ISSUE THREAD

**Issue by thihy** [elastic/elasticsearch#12757]
I have put too many documents (with _ttl  '3d' ) to ES on 2015-08-06. 
Then I stopped ES on 2015-08-07. 
The GC Old Gen reached 100% when I start ES on 2015-08-10.
I dumped Java Heap, and  found there are **too many DocToPurge instances**.
In `ExpiredDocsCollector`, the size of `docsToPurge` list is unlimited. When there are too many documents, the size of `docsToPurge` list will be very large.

Can the size of `docsToPurge` list be limited?

**Comment by clintongormley** [comment]
Expiring docs with `_ttl` has been deprecated.  A better option is to use the delete-by-query plugin.
