### ISSUE TITLE
Startup CLI Parsing needs defined order of arguments

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#12758]
Due to the limited feature set of the CLI parser the following does not work and will return an error message

```
/bin/elasticsearch --http.cors.enabled=true --http.cors.allow-origin='*' -d -p /tmp/foo
```

The reason for this is, that the current implementation of the CLI parser will literally stop parsing as soon as it hits a dynamic parameter and add all the other parameters to the list of parameters that should be parsed dynamically with a special logic. So `-d` and `-p` will never be parsed regularly and added to the specific CLI parser options

**Workaround 1**: Document that "dynamic" arguments must come last in the list of arguments.

**Workaround 2**: Two a second parsing logic check for all the arguments, when doing the dynamic parsing for all the `--foo.bar` parameters...

**Long term workaround 1**: Treat configuration file settings as configuration file settings and add some specific switches for settings that should be changed via commandline (like node name, interface, cluster name), but make the parsing strict.

**Long term workaround 2**: Use a more powerful parsing library, which supports all of our needed features natively - which is also needed for subcommands, like `bin/elasticsearch plugin install`. [argparse4j](http://argparse4j.sourceforge.net/) comes into mind.

**Comment by clintongormley** [comment]
@spinscale I'd be ok with just documenting the requirement for now
