### ISSUE TITLE
[snapshot] support secondary repository

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#12760]
Marking this as `discuss` as I don't know if we want to support this.

In [this PR](https://github.com/elastic/elasticsearch-cloud-azure/pull/93), the need to support alternative repository was raised. I'm wondering if this is something we would like to implement whatever the repository type is.

I can imagine something like:

```json
// Create a first repo
PUT /_snapshot/repo_fs
{
  "type": "fs",
  "settings": {
    "location": "/mount/backups/my_backup"
  }
}

// Create a second repo
PUT /_snapshot/repo_azure
{
  "type": "azure",
  "settings": {
    "key": "my_key",
    "secret": "secret"
  },
  "secondary": "repo_fs"
}
```

So when we try to backup or restore to/from `repo_azure` if it fails, we try then `repo_fs`.

@imotov WDYT? Would this make sense to support what was asked in https://github.com/elastic/elasticsearch-cloud-azure/pull/93 but whatever the repositories are?

May be it's better to do this retry on a client level instead?

Thoughts?

**Comment by rjernst** [comment]
Why would this need to be built in? The user can already do this themselves. We shoudln't complicate things. They can push snapshots to multiple repos, try restoring from one, and on failure, try to restore from another.

**Comment by dadoonet** [comment]
@rjernst What is your position regarding the original feature request ([PR 93](https://github.com/elastic/elasticsearch-cloud-azure/pull/93)) then?

**Comment by clintongormley** [comment]
I agree with @rjernst's comment.  We should add support for multiple azure repositories in the same way as we do for AWS, etc.  I also agree with this comment from https://github.com/elastic/elasticsearch-cloud-azure/pull/93#issuecomment-113214013:

> I like the idea of specifying the account in the repository settings, but the key should be specified in the startup configuration. This follows the pattern and rationale set by the path.repo setting which ensures that ES only writes to pre-configured locations. Specifying the key in the repository settings would allow any azure storage to be written to.

**Comment by dadoonet** [comment]
So I added a comment to #12759. 

What about the original issue in [PR 93](https://github.com/elastic/elasticsearch-cloud-azure/pull/93)? Does it mean it won't be pulled in? So I can close this issue and the related PR?

**Comment by clintongormley** [comment]
> What about the original issue in PR 93? Does it mean it won't be pulled in? So I can close this issue and the related PR?

yes - I don't think that's the right solution for this.  The generic approach already provided by snapshot/restore works better here.

**Comment by dadoonet** [comment]
Azure now supports secondary settings. According to the comments on this issue, we can close this issue.
