### ISSUE TITLE
javascript API: client.msearch document reference is incorrect

### ISSUE THREAD

**Issue by aanuprab** [elastic/elasticsearch#12767]
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference-1-4.html#api-msearch-1-4
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference-1-3.html#api-msearch-1-3

client.msearch({
  body: [
    // match all query, on all indices and types
    {},
    { query: { match_all: {} } },

    // query_string query, on index/mytype
    { _index: 'myindex', _type: 'mytype' },
    { query: { query_string: { query: '"Test 1"' } } }
  ]
});

**Issue:** when index is defined as per reference document: '_index', elasticsearch returns query from all indexes, it does not set the index for the search.

It works if the field is set as "index": "myindex" removing the _

**Comment by dadoonet** [comment]
Thanks for reporting this! Can you open this issue at https://github.com/elastic/elasticsearch-js instead?

Thanks!
