### ISSUE TITLE
cluster.blocks.read_only set as a persistent setting

### ISSUE THREAD

**Issue by magnusbaeck** [elastic/elasticsearch#12763]
If you manage to set cluster.blocks.read_only=true as a persistent cluster setting it seems you get into a catch-22 since the cluster won't allow you to disable the setting when it's in read-only mode. I was eventually able to get out of it after a full cluster restart.

This raises a few questions:

* Should cluster.blocks.read_only even be settable as a persistent setting?
* If yes, how are you supposed to disable it?
* Regardless, can we improve [the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/cluster-update-settings.html#_metadata) to make the intended semantics clear? Right now it easily gives the impression that among metadata operations it's only index creation and deletion that's blocked which clearly isn't true.

I initially raised this at https://discuss.elastic.co/t/recovering-from-cluster-blocks-read-only-true-in-dynamic-settings and additional details can be found there.

This was on ES 1.7.1.

**Comment by clintongormley** [comment]
Hmmm - `cluster.blocks.read_only` can be set to `false` whether it is persistent or transient, including on 1.7.1.  In 3.0, you'll be able to unset this setting completely.
