### ISSUE TITLE
dynamic_templates not used when calling analyze API

### ISSUE THREAD

**Issue by Calardan** [elastic/elasticsearch#12772]
When defining dynamic templates, it is somewhat irritating to notice that any request to the analyze API will only consider said dynamic mappings when a document with the specific field has already been posted.

Example:
```
{
"mappings": {
    "assets": {
      "dynamic_templates": [
        {
          "de": {
            "path_match": "localizations.de-*.*",
            "match_mapping_type": "string",
            "mapping": {
              "type": "string",
              "analyzer": "ger"
            }
          }
        }
      ]
    }
  }
}
```
```
GET http://localhost:9002/assets/_analyze?field=localizations.de-DE.text?text=Dies%20ist%20ein%20beispielhafter%20Text
```
will only use the correct analyzer when a document with the exact same field 'localizations.de-DE.text' had already been posted. For me, this behaviour caused some irritations. A note in the documentation would have helped a lot. 

Thanks!

**Comment by clintongormley** [comment]
While I'm all for improving the documentation, cluttering it with too many notes actually makes it harder to read.  Honestly, i'm surprised that you thought it would work in the first place. If you saw something in the docs that implied it would work, I'd be happy to change that. You want to send a PR with a suggested edit?

btw, you can just specify `?analyzer=ger` in the analyze API and you'll see the effect it has.

**Comment by Calardan** [comment]
I knew it works with ```?analyzer=ger```. All I wanted to do is test my configuration if it works for the specified field.
I have to admit that afterwards it makes sense that any dynamic mapping would only work when it has actually been applied. But it was still very confusing before realizing this.

**Comment by clintongormley** [comment]
I don't think there's anything left to do here. Closing
