### ISSUE TITLE
Change RPM package to include "noarch"

### ISSUE THREAD

**Issue by electrical** [elastic/elasticsearch#12777]
In master branch we are missing the .noarch part in the resulting rpm name.

$ find . -name *.rpm
./distribution/rpm/target/releases/elasticsearch-2.0.0-beta1-SNAPSHOT.rpm
./distribution/rpm/target/rpm/elasticsearch/RPMS/noarch/elasticsearch-2.0.0-beta1_SNAPSHOT20150810154300.noarch.rpm

**Comment by dadoonet** [comment]
Do we agree that the final name in `target/releases` dir should be `elasticsearch-2.0.0-beta1_SNAPSHOT20150810154300.noarch.rpm`? 

It's what RPM maven plugin produces by default, which looks good to me but note the `underscore` in `_SNAPSHOTxxx`. I think I saw also that kind of substitution (using `~` IIRC) in `rpm` or `deb` packages. We should probably try to stick with all maven plugins defaults here?

**Comment by jordansissel** [comment]
With some of the recent unified build work, I think we can close this. All projects are converging on a consistent artifact naming scheme. That scheme is, if I recall correctly, what ES has been using for some time -- `project-version.rpm` and `project_version.deb` for platform-independent projects.

**Comment by clintongormley** [comment]
thanks @jordansissel
