### ISSUE TITLE
Groovy script update causes dynamic mapping update

### ISSUE THREAD

**Issue by Bondza** [elastic/elasticsearch#12795]
Hey!

My mapping is set as ```float``` but when I retrieve my document it is returned as a string and not a float. I have seen this on ```1.7.1``` and ```1.5.2```.

I have a groovy script which updates a document field like:
```groovy
ctx._source.clicks += click;
ctx._source.loads += load;
ctx._source.ctr = ctx._source.clicks / ctx._source.loads;
```

My template type is set to float:
```json
{"ctr":{"type":"float"},"clicks":{"type":"integer"},"loads":{"type":"integer"}}
```

I have updated the document using my script through curl:
```
curl -XPOST 'localhost:9200/docs/stats/a43ae07c6be014d843f77d07c587b1f926b31f7eb/_update?pretty' -d '{"script_id":"update","params":{"click":0,"load":2}}'
curl -XPOST 'localhost:9200/docs/stats/a43ae07c6be014d843f77d07c587b1f926b31f7eb/_update?pretty' -d '{"script_id":"update","params":{"click":1,"load":0}}'
```

I see a log message from Elasticsearch on the first update:
```
[2015-08-11 09:06:04,171][INFO ][cluster.metadata         ] [Scream] [ads] update_mapping [data] (dynamic)
```

The document is always created with ```ctr=0```. But after updating with the script it looks like:
```json
{"ctr":"0.5","clicks":1,"loads":2}
```

So I thought I'd try to do ```Float.parseFloat``` since it is returned as a string but that just gives me an  exception, because it isn't actually a string:
```json
{
  "error" : "ElasticsearchIllegalArgumentException[failed to execute script]; nested: GroovyScriptExecutionException[MissingMethodException[No signature of method: static java.lang.Float.parseFloat() is applicable for argument types: (java.math.BigDecimal) values: [0.3333333333]\nPossible solutions: parseFloat(java.lang.String)]]; ",
  "status" : 400
}
```

Seeing as other arithmetic operations seem to return a numeric type and not a string, I am guessing this should too?

It works fine when I use ```BigDecimal.floatValue()```:
```groovy
ctx._source.ctr = (ctx._source.clicks / ctx._source.loads).floatValue();
```

**Comment by clintongormley** [comment]
Hi @Bondza 

Groovy uses BigDecimal for these operations, which are cast to strings by Elasticsearch.  This will work too:

    ctx._source.ctr = (double) ctx._source.clicks / ctx._source.loads;

@dakrone Was #6609 supposed to fix this? if not, is it fixable?

**Comment by dakrone** [comment]
#6609 was only to fix constants (like `1.3`) being compiled as BigDecimals by Groovy, I think this is the Groovy math itself doing this on division.

I'm not sure if it's fixable, I can do some research to see if it is.

**Comment by Bondza** [comment]
I thought that it might have something to do with how Elasticsearch handles BigDecimal. Unfortunately it made my query scripts cause an exception later on.

It is a bit confusing though, since the field which it assigns is not of type string. It thought that would cause an exception since there is a mapping set for that field?

It would be awesome if it was fixable! :)

**Comment by masaruh** [comment]
Groovy returns `BigDecimal` for integer division (http://docs.groovy-lang.org/latest/html/documentation/core-syntax.html#integer_division) and it's serialized as `String` as described in #12385.

Best bet would be to cast/parse yourself...

**Comment by dakrone** [comment]
Yes, I tried to find a way where we could automatically change Groovy's integer division, but unfortunately it doesn't look like there's a programmatic way to do it from a Transformer (unlike the constant expressions where we can).

I think right now best bet is to cast to `(double)` as Clint mentioned.

**Comment by clintongormley** [comment]
thanks @dakrone . Closing

**Comment by Bondza** [comment]
Alright, casting works fine so I'll remember this the next time I need to do some scripting in Elasticsearch.

Thanks for the help!
