### ISSUE TITLE
simple query string: remove (not working) support for alternate formats

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#12794]
The simple_query_string supports the following main format properly:

```
{
  "simple_query_string": {
    "query": "foo bar",
    "fields": ["body^5","_all"]
  }
}
```

I noticed in the parser also an attempt of supporting the following, undocumented, untested and not working:

```
{
  "simple_query_string": {
    "query": "foo bar",
    "field": "body"
  }
}
```

What happens with the above query is that we query the `_all` field as `fields` is not present.

There's also another attempt of supporting the following, undocumented, untested and not working:

```
{
  "simple_query_string": {
    "body" : {
      "query": "foo bar"
    }
  }
}
```

What happens with the above query is again that we query the `_all` field as `fields` is not present.

Given that the last two variants never worked and are not documented I am wondering if it even makes sense to fix them. I personally don't like having so many different ways of specifying the same thing, so I would stick to the `fields` version that always worked and everybody is aware of, and remove the other attempts in the parser. What do others think?

**Comment by rjernst** [comment]
+1 to remove these broken variants

**Comment by s1monw** [comment]
++

**Comment by clintongormley** [comment]
++
