### ISSUE TITLE
Index "creation_date" not accurate when created with settings from another index

### ISSUE THREAD

**Issue by ajeis** [elastic/elasticsearch#12790]
When creating a new index using settings from an old index, the "creation_date" of new index is same as that of old index. Steps - 
1. Get settings of existing index using GetIndexRequestBuilder()
2. Create new index using CreateIndexRequestBuilder() by doing - 
a. copying the mappings getIndexResponse.getMappings()
b. copying the settings getIndexResponse.getSettings()
c. copying headers getIndexResponse.getHeaders()

Now the new index has same "creation_date" timestamp as old index. Version - 1.4

**Comment by clintongormley** [comment]
Hi @ajeis 

Thanks for reporting.  This is indeed a bug.  Confirmed on master with the REST api.  Also `version.created` should not be settable either:

    PUT x
    {
      "settings": {
        "index": {
          "creation_date": "1439300111000",
          "version": {
            "created": "2000123"
          }
        }
      }
    }
    
    GET x/_settings

Returns:

    {
       "x": {
          "settings": {
             "index": {
                "creation_date": "1439300111000",
                "uuid": "plte5zsHRwSTYzolfP537w",
                "number_of_replicas": "1",
                "number_of_shards": "5",
                "version": {
                   "created": "2000123"
                }
             }
          }
       }
    }

**Comment by rjernst** [comment]
`version.created` is set in tests (to check backcompat behavior) *a lot* (at least within mapping tests).

**Comment by ajeis** [comment]
Where would the fix for this be - IndexSettingsModule, InternalIndicesService, IndexSettingsService or somewhere else? I am still fairly new to the codebase.

**Comment by HarishAtGitHub** [comment]
Hi , I already started working on this issue. I am also a beginner (let's join hands)..
I think I spotted the issue ... 
I thinks it's [here](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataCreateIndexService.java#L331-L339) ...

Investigating why they are fetching it from settings
not sure if it was done intentionally for some purpose like migration where they need to maintain such information. I am just guessing ... Elasticsearch developers or experts can throw more light on this ...
I am almost there with the fix ...

```java
if (indexSettingsBuilder.get(SETTING_VERSION_CREATED) == null) {
                        DiscoveryNodes nodes = currentState.nodes();
                        final Version createdVersion = Version.smallest(version, nodes.smallestNonClientNodeVersion());
                        indexSettingsBuilder.put(SETTING_VERSION_CREATED, createdVersion);
                    }

                    if (indexSettingsBuilder.get(SETTING_CREATION_DATE) == null) {
                        indexSettingsBuilder.put(SETTING_CREATION_DATE, new DateTime(DateTimeZone.UTC).getMillis());
                    }
```

**Comment by HarishAtGitHub** [comment]
I fixed it and it started working ..
input settings 
```javascript
{
     'settings':  
          {  'index': 
                       {'number_of_replicas': '1', 
                         'version': {'created': '2000010'}, 
                         'creation_date': '1439384094544',
                         'number_of_shards': '5', 
                         'uuid': 'ayzHgwB3Sgey-Pk_Okgwyg'
                       }
          }
}
```

new index settings 
```javascript
{
    'settings': 
          {'index': 
                     {'number_of_replicas': '1', 
                      'version': {'created': '2000001'}, 
                      'creation_date': '1439456346424', 
                      'uuid': 'fddpIVxNTTKPzqDakLAL4A', 
                      'number_of_shards': '5'
                     }
         }
}
```

But the ramifications are something to be worried about ..... Now I understand what @rjernst
is talking about in https://github.com/elastic/elasticsearch/issues/12790#issuecomment-129989979
it caused 

> 474 suites, 2648 tests, <b> 43 errors, 22 failures </b>

**Comment by rjernst** [comment]
Well it is not just for tests, that setting is inserted so we know when the index was created for things like backcompat checks, and also feature behavior. For example, when the `_field_names` was added back in 1.3, that setting helped determine for which indexes the new field should be added (those created on or after 1.3).

**Comment by HarishAtGitHub** [comment]
This version.created seems like a bit dangerous entity to play with .
I just was playing with the version number and unfortunately I gave version. created as 1 ..
it accepted without any problem.. but then when I stopped it and restarted ... <b>it could not start</b> . It was throwing [errors](https://gist.github.com/HarishAtGitHub/6072670467d7d768ebf3) that I "The index [demo6] was created before v0.90.0 and wasn't upgraded. This index should be open using a version before 2.0.0-beta1-SNAPSHOT and upgraded using the upgrade API." ...

Hmm.. so dangerous ....

**Comment by HarishAtGitHub** [comment]
Pull request for date replication : https://github.com/elastic/elasticsearch/pull/12854

**Comment by HarishAtGitHub** [comment]
Ok .. what is the final take on version.created ?

apart from that is my comment https://github.com/elastic/elasticsearch/issues/12790#issuecomment-130609798 a valid one ?
Is it good to allow such a dangerous property out .
Why I am asking this is .. anything that can easily Fool/Trick/Ruin the system is dangerous and should be avoided ? So by that logic the comment seems valid ...

or can it be ignored as index creation is mostly carried out by admins ? (I saw most of the index creation,deletion api's inside admin) ? and you have left it knowingly based on the belief that admins are supposed to perform such an operation with discretion ?

**Comment by rjernst** [comment]
@HarishAtGitHub `version.created` is an internal setting. It is not meant to be set by a user (and thus not documented). In an ideal world, there would be some separate section of the settings (probably outside the `settings` key) which would be used for these internal settings. However, I think this is currently difficult to change. In the meantime, the answer may be something like a "clone" index metadata action? I don't know how this would look, but it could ignore the known internal settings. I'm curious to here what @jpountz @clintongormley and others think about either of these ideas.

**Comment by clintongormley** [comment]
I'd definitely like to see a list of "banned" settings, things that can only be set internally.

**Comment by HarishAtGitHub** [comment]
Ok ... seems like a critical thing ...
so why should the creation_date replication patch wait for this ?
can we review that patch and pull if it deserves a pull ?
and track the version.created separately ?

**Comment by HarishAtGitHub** [comment]
FYI: I just started to work on this on "version.created" part . I will update my progress in a day ....
what is the timeline for this issue completion(as I see 2.0 tag in this thats y asking this Q) ? 
Is it ok for a person(me) who has has a week experience in code base do this ?

If you want this to be done by experts I am fine , as I don't want to be a blocker . No worries ...
I am fine with any decision u take ...

**Comment by HarishAtGitHub** [comment]
May be this should also be removed from the docs [here](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/indices-create-index.html#_creation_date)

**Comment by HarishAtGitHub** [comment]
Hi,
    I  raised a PR for version.created problem : https://github.com/elastic/elasticsearch/pull/12854

Please give feedback and I can refactor the patch.

Note about Test case results:
*********************************

I built and all tests PASSED except the "Smoke test shaded jar"
see build log here: https://gist.github.com/HarishAtGitHub/aa8539a5c56cb4ad48b9
. and I hope this has nothing to do with my code.
and suspecting some other problem I resumed the build and I landed in https://gist.github.com/HarishAtGitHub/fcc519bd9863ab8a95af

which is reported in https://github.com/elastic/elasticsearch/issues/12791 .

**Comment by s1monw** [comment]
we decided to move this out to 2.1
