### ISSUE TITLE
Tribe node does not retry connection to clusters after startup

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#12804]
This issue was raised in a discuss.elastic.co topic: https://discuss.elastic.co/t/child-node-never-connected-if-offline-at-startup-of-tribe/27193

If a cluster is not started when the tribe node starts, it will fail to connect, log a warning and then never try to connect to that cluster again. Other clusters in the tribe work as expected but when the first cluster comes back online the tribe node will not try to connect to it

**Comment by espenwa** [comment]
Would it be possible to re-evaluate the 2.1.0-scheduling of this issue? A very simple timed retry every x minutes would do wonders for the usability of the tribe-feature.

**Comment by sherry-ger** [comment]
I could not reproduce this with both multicast and unicast on ES version 1.7.1

**Comment by TinLe** [comment]
I saw this issue on ES 1.4.5 and earlier.   I am in the process of
qualifying 1.7.1 in our environment.   It may have been fixed after 1.4.5.

Tin

**Comment by clintongormley** [comment]
This appears to be fixed at least in 2.2.0
