### ISSUE TITLE
Remove `cloud.account` and `cloud.key` settings

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#12809]
_From @dadoonet on February 27, 2015 15:21_

`cloud.account` and `cloud.key` settings are not documented as we use `cloud.aws.access_key` and `cloud.aws.secret_key` settings instead.

We can deprecated those settings in `es-1.4` branch and remove them in `master`.

_Copied from original issue: elastic/elasticsearch-cloud-aws#183_

**Comment by dadoonet** [comment]
@imotov WDYT?

**Comment by dadoonet** [comment]
_From @imotov on February 27, 2015 15:35_

Personally I like `cloud.account` and `cloud.key` more (mostly because they are shorter). But I can see how this can cause some confusion. Not sure.

**Comment by dadoonet** [comment]
Yeah. If we want to mix within a node azure settings and aws settings (let say backup in two places), I think it's better to prefix setting name.

**Comment by dadoonet** [comment]
_From @kimchy on February 27, 2015 15:43_

we do support both, right? I mean, sure, we can simplify and not provide too many options to configure things and be more explicit around the actual aws settings

**Comment by dadoonet** [comment]
we do support both today. But the simplest form `cloud.account` is not documented AFAIK.

**Comment by dadoonet** [comment]
_From @nikolay on February 27, 2015 20:17_

@imotov With AWS, "account" and "access key" are two different things, so, `cloud.account` will be misleading.

**Comment by xuzha** [comment]
Do we still need to discuss about this? If nobody objects,  I'm going to merge this change soon.
