### ISSUE TITLE
Synced flush missing from Java client API

### ISSUE THREAD

**Issue by shikhar** [elastic/elasticsearch#12812]

**Comment by s1monw** [comment]
@shikhar we did this on purpose since it's really a last resort API that should only be run by an admin manually ie. via rest. I think we should keep it like this, what's your usecase?

**Comment by shikhar** [comment]
@s1monw some of our indexing activity is periodical rather than NRT (e.g. every minute or every hour). We tend to bounce our clusters quite often so it'd be great to be synced as much as possible, and for the indexers that are running every minute the 5 min auto-sync is too long. For now I am thinking of adding a curl to perform the synced flush in the indexer script (they're cronned), but being able to use the Java client API would have met our needs better.
