### ISSUE TITLE
Add weight to AllocationDecider

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#12815]
AllocationDeciders (plural) currently take all the AllocationDecider instances in a set. While the order does not matter for a "yes" decision (because it must be unanimous), a "no" or "throttle" decision could be optimized if cheaper deciders were allowed to run first.

Adding a weight, with a default of 1.0 (easy since AllocationDecider is an abstract class), would allow expensive deciders to increase their weight and run later.

**Comment by dakrone** [comment]
@rjernst we do optimize the order of the AllocationDeciders to have the cheapest ones run first and short-circuit on "NO" answers, are you saying we should have the allocation deciders decide the weight themselves?

**Comment by s1monw** [comment]
@dakrone I think that is not true - it's a set so it order is undefined?

**Comment by rjernst** [comment]
Yeah, the injected AllocationDeciders ctor takes a set of AllocationDecider instances, so no order that I see. @dakrone Yes, I think the deciders should give their own weight. They are should be self aware of their expensiveness.

**Comment by dakrone** [comment]
Ahh okay, I thought I remembered a commit changing that. Frustrating that we can't inject an ordered list by default with Guice. +1 to weight then.

**Comment by dakrone** [comment]
Now that allocation deciders are de-guiced, I think we can do this with regular ordering instead of adding a weight, and it should be less complex to implement
