### ISSUE TITLE
Warn users when their bulk requests are too large

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#12811]
Its not super clear how many documents is the right number to send in a bulk request. I imagine its because it depends on lots of things - mapping, document size, lots of stuff. I imagine sometimes Elasticsearch can _tell_ when the user's sent too many documents. In those times we should log a warning or send a warning back to the user or something.

I'm not super clear on how this would work because I'm not super clear on what the problems are with sending too many documents in one bulk request.

**Comment by clintongormley** [comment]
Closing in favour of #16011
