### ISSUE TITLE
Java SDK: LongTerms.Bucket#getKeyAsText should return the string value for date aggregation

### ISSUE THREAD

**Issue by cooniur** [elastic/elasticsearch#12816]
`TL;DR;` For example, when querying for the following aggregation on field `createDate` (which is a Date field): 

    {
      "size": 0,
      "query": { "match_all": {} },
      "aggregations": {
        "DATE_TERMS": {
          "terms": {
            "field": "createDate",
            "size": 10
          }
        }
      }
    }

The response in JSON is:

    "DATE_TERMS": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": [
          {
            "key": 592444800000,
            "key_as_string": "10/10/88",
            "doc_count": 12
          },
          {
            "key": 646876800000,
            "key_as_string": "07/02/90",
            "doc_count": 7
          },
          {
            "key": 744940800000,
            "key_as_string": "08/10/93",
            "doc_count": 3
          }
        ]
      }

When I loop through the buckets in Java code, 

    Terms terms = response.getAggregations().get("DATE_TERMS");
    terms.getBuckets().stream.forEach( bucket -> {
      String keyAsString = bucket.getKeyAsText().string(); 
      System.out.println(keyAsString);
    })

The output is

    592444800000
    646876800000
    744940800000

I'm expecting `bucket.getKeyAsText().string()` would give me the actual date in string format (e.g. `10/10/88`, `07/02/90`, etc..), but currently it gives me the long value of the date (e.g. `592444800000`, `646876800000`, ...). This behavior in the SDK is inconsistent with the JSON response, where there is a field called `key_as_string`.

========
The workaround (as shown in the following code) would be first to check if `terms` is a `LongTerms` type, and if it is, during the loop, use `ValueFormatter.DateTime.DEFAULT.format()` to convert the long value to the actually date string, which is tedious. Moreover the default formatter doesn't give me the same string as in the JSON response either.

    Terms terms = response.getAggregations().get("DATE_TERMS");
    terms.getBuckets().stream.forEach( bucket -> {
      String keyAsString
      if (terms instanceof LongTerms)
        keyAsString = ValueFormatter.DateTime.DEFAULT.format(bucket.getKeyAsNumber().longValue());
      else
        keyAsString = bucket.getKeyAsText().string(); 
      System.out.println(keyAsString);
    })

The output is

    1988-10-10T00:00:00.000Z
    1990-07-02T00:00:00.000Z
    1993-08-10T00:00:00.000Z

which is fine, but I would expect the same output as in the JSON response:

    10/10/88
    07/02/90
    08/10/93

Moreover, it is not generally applicable. If the aggregation term is a number type (long, integer), the conversion to date will be wrong.

The SDK version I'm using is `1.7.1`.

I'm not sure whether I describe the problem clearly, but let me know if you need more elaboration.

Thanks!

**Comment by cooniur** [comment]
@colings86 Is anyone interested in this topic?

**Comment by clintongormley** [comment]
Closing in favour of #15146
