### ISSUE TITLE
SearchQueryIT#testIndicesQuerySkipParsing fails until we refactor nested

### ISSUE THREAD

**Issue by alexksikes** [elastic/elasticsearch#12822]
This is reminder issue to that SearchQueryIT#testIndicesQuerySkipParsing cannot be ran successfully until we have refactored nested queries. The test is marked as AwaitsFix for now.

**Comment by cbuescher** [comment]
This seems to work now that the HasChild/HasParent and Nested query are done. Re-enabled the test with 01ea426.
