### ISSUE TITLE
Mapping conflict exception not bubbling up to root cause

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12839]
A mapping conflict such as:

    PUT my_index
    {
      "mappings": {
        "type_one": {
          "properties": {
            "text": {
              "type": "string",
              "analyzer": "standard",
              "search_analyzer": "whitespace"
            }
          }
        },
        "type_two": {
          "properties": {
            "text": {
              "type": "string"
            }
          }
        }
      }
    }

throws an exception like:

        {
           "error": {
              "root_cause": [
                 {
                    "type": "mapper_parsing_exception",
                    "reason": "mapping [type_two]",
                    "stack_trace": "MapperParsingException[mapping [type_two]]; ... 6 more\n"
                 }
              ],
              "type": "mapper_parsing_exception",
              "reason": "mapping [type_two]",
              "caused_by": {
                 "type": "illegal_argument_exception",
                 "reason": "Mapper for [text] conflicts with existing mapping in other types:\n[mapper [text] has different analyzer, mapper [text] is used by multiple types. Set update_all_types to true to update [search_analyzer] across all types.]",
                 "stack_trace": "java.lang....\n"
              },
              "stack_trace": "MapperParsingException[mapping [type_two]]; nested: IllegalArgumentException[Mapper for [text] conflicts with existing mapping in other types:\n[mapper [text] has different analyzer, mapper [text] is used by multiple types. Set update_all_types to true to update [search_analyzer] across all types.]];...\n"
           },
           "status": 400
        }

The `error.root_cause.reason` should contain the text from `error.type.caused_by.reason`

**Comment by xuzha** [comment]
I'm not sure if this is a bug.
The root causes here block looks like correct. Inside of it, there could be a caused_by key-value pair like this:

```
          "root_cause": [
             {
                "type": "mapper_parsing_exception",
                "reason": "mapping [type_two]",
                "stack_trace": "MapperParsingException[mapping [type_two]]; ... 6 more\n"
                "caused_by": {.......} // skipped
             }

```

We skip it on purpose, [here] (https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/rest/BytesRestResponse.java#L130)

**Comment by rjernst** [comment]
I don't think it is a bug, but a choice that was made. The root_cause stops at a subclass of ElasticsearchException, I believe. Perhaps @s1monw can elaborate on why we don't go down to the original root cause (the IAE here)?

**Comment by jpountz** [comment]
+1 on improving exception rendering to try to better expose the actual root cause of the issue
