### ISSUE TITLE
Move free disk log entries to TRACE level when there is plenty of free disk space

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#12843]
For messages like the following where it is nowhere near the disk threshold, it will be nice to log them at the TRACE level.  Even at the DEBUG level, it is too noisy and can drown other important debug messages.  For example, I am looking at this single day log file that has 53K+ log entries like the one below:

```
[2015-08-11 11:41:54,600][DEBUG][cluster.routing.allocation.decider] [node_name] Node [Sa-w1xe8Q4Si4V30Tb_Vrg] has 94.62963991540137% free disk (2072797175808 bytes)
```

**Comment by navneet83** [comment]
I'll take this one and work on it.
