### ISSUE TITLE
stats aggregation returns 500 error when performed over an invalid field

### ISSUE THREAD

**Issue by djschny** [elastic/elasticsearch#12842]
Performing a stats aggregation over a string field throws 500 error with an exception as opposed to a simplified error stating the the field specified is not valid for a stats aggregation.

I would expect a 400 for example since the client to fix their request before retrying it. Additionally it would help if the error message was more indicative of the problem as opposed to a SearchPhaseExecutionException. I would hope we should be able to detect this prior to performing the actual search.

```
GET /stack/_search?search_type=count
{
  "aggs": {
    "dateAggTest": {
      "stats": {
        "field": "title"
      }
    }
  }
}
```

```
{
   "error": "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[hjvyPMaiTgewDbpd9j67_A][stack][0]: ClassCastException[org.elasticsearch.index.fielddata.plain.PagedBytesIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexNumericFieldData]}{[hjvyPMaiTgewDbpd9j67_A][stack][1]: ClassCastException[org.elasticsearch.index.fielddata.plain.PagedBytesIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexNumericFieldData]}{[hjvyPMaiTgewDbpd9j67_A][stack][2]: ClassCastException[org.elasticsearch.index.fielddata.plain.PagedBytesIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexNumericFieldData]}{[hjvyPMaiTgewDbpd9j67_A][stack][3]: ClassCastException[org.elasticsearch.index.fielddata.plain.PagedBytesIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexNumericFieldData]}{[hjvyPMaiTgewDbpd9j67_A][stack][4]: ClassCastException[org.elasticsearch.index.fielddata.plain.PagedBytesIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexNumericFieldData]}]",
   "status": 500
}
```

**Comment by clintongormley** [comment]
Agreed, should be a 400 - probably need a wider review of exceptions too

**Comment by xuzha** [comment]
We should have a better error message here.

And should we just treat every ClassCastException is a 400 rather than 500?  If user send correct request and get 400, OK, you find a bug we are going to fix it.

**Comment by jpountz** [comment]
> And should we just treat every ClassCastException is a 400 rather than 500? If user send correct request and get 400, OK, you find a bug we are going to fix it.

I don't think we can generalize that class-cast exceptions are user-input errors rather than internal errors. We should just better validate that fields have the expected type.

It might be harder with scripts as scripts can do pretty much anything, but I assume that if we can make it work well on fields, that would be a good start already.

**Comment by djschny** [comment]
+1 @jpountz, I would assume scripts to be out of scope. Not enough gain for the amount of work it would take to handle all cases, etc.
