### ISSUE TITLE
Highlighting and sub documents

### ISSUE THREAD

**Issue by AndreasTurowski** [elastic/elasticsearch#12841]
I need a tip, please! We append several attachments to our elastic document. Alle attachments are stored in an array of sub documents called "ANY_BLOB". This is mapped to the "attachment" type. Per mapping we add a Field "Reference" to the ANY_BLOB sub document mapping. This is stored and retrieved well. But if we use the "highlight"-feature, we got the highlighting of some of the "ANY_BLOB"s, no idea to which subdocument it belongs. Is there any way to assign the "Reference"-Field to the highlighting? In fact we have to know, which of the ANY_BLOB-Attachments caused the highlighting.

**Comment by nik9000** [comment]
If this is parent/child then I don't know the answer. If it is just that
you have a list of documents then you can look at the experimental
highlighter. It has a feature that will return sibling fields but there are
tons of caveats to how it works. Try it but be very careful to read the
docs.

**Comment by AndreasTurowski** [comment]
THX! You mean this one?
https://github.com/wikimedia/search-highlighter <https://github.com/wikimedia/search-highlighter>

**Comment by nik9000** [comment]
Yup. The docs I was describing are
https://github.com/wikimedia/search-highlighter/blob/master/docs/fetch_fields.md

**Comment by clintongormley** [comment]
This question is better suited to the forums: https://discuss.elastic.co/

Closing
