### ISSUE TITLE
Tests fail when building ES

### ISSUE THREAD

**Issue by focusme** [elastic/elasticsearch#12849]
I've checked out ES source with v1.7.2 tag and when I try to build tests fail with the following tests:

This happens on win7 with Java 8 + Maven 3.3.3

Tests with failures (first 3 out of 12):
  - org.elasticsearch.index.codec.postingformat.ElasticsearchPostingsFormatTest.testDocsAndFreqsAndPositionsAndOffsetsAndPayloads
  - org.elasticsearch.index.codec.postingformat.ElasticsearchPostingsFormatTest.testDocsOnly
  - org.elasticsearch.index.codec.postingformat.ElasticsearchPostingsFormatTest.testRandom

[INFO] JVM J0:     1.68 ..  1811.50 =  1809.81s
[INFO] JVM J1:     1.68 ..  1811.46 =  1809.78s
[INFO] JVM J2:     1.68 ..  1811.46 =  1809.78s
[INFO] Execution time total: 30 minutes 11 seconds
[INFO] Tests summary: 758 suites, 5083 tests, 12 errors, 69 ignored (60 assumptions)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30:30 min
[INFO] Finished at: 2015-08-13T16:10:10+08:00
[INFO] Final Memory: 23M/597M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.1.2:junit4 (tests) on project elasticsearch: Execution tests of goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.1.2:junit4 failed: D:\work\es\elasticsearch1.7.1\target\junit4-ant-3382632566736328075.xml:16: There were test failures: 758 suites, 5083 tests, 12 errors, 69 ignored (60 assumptions) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by s1monw** [comment]
please try running tests on master
