### ISSUE TITLE
Socket appender logging to unavailable Logstash node kills Elasticsearch node

### ISSUE THREAD

**Issue by HenrikOssipoff** [elastic/elasticsearch#12869]
We experienced an issue today in our production cluster, after a cluster upgrade from 1.6.x to 1.7.1.

(In all of the below, our "Elasticsearch cluster" is a 3 node setup running production data for our e-commerce platform, whereas our "Logstash cluster" is a different setup with other Elasticsearch nodes and the Logstash service)

Our whole Elasticsearch cluster is set to have a socket appender log option, to our Logstash cluster. Previously in 1.6.x when the Logstash service was unavailable on the cluster, nothing bad would happen (except missing log entries obviously), but after our upgrade to 1.7.x we yesterday experienced some weird behaviour.

It is as if about 5-10 minutes pass if the Logstash service dies, after which exactly one node in our Elasticsearch cluster will start to exhibit the following:

- Most of the times it will act as it's still part of the whole cluster, and will give cluster status and correct master response
- Some times, above _cat operations will give the 30sec timeout
- All queries, GETs, deleted, index operations and even a _cat/indices will result in a request that seems to never terminate

All other nodes in the cluster *seems* to work. Not entirely sure.

Before we identified the missing Logstash service as the culprit, we attempted a full cluster restart. Bringing node 1 and node 2 up, those worked for a while, but when about 5 minutes passed and we brought up node 3 (and it started recovery), node 1 started it's weird behaviour again -- resulting in the recovery on node 3 to hang, because it attempted to read data from node 1.

We also have file logging in place, and nothing seems to be in the logs around this issue, on either node.

I'm not entirely sure about all of this, but wanted to report it just in case. It seems weird that a missing log source should be able to bring the whole cluster down - and since we didn't see the same behaviour when we were running 1.6.x, it's tempting to believe this is something that is caused by the upgrade to 1.7.1, made only a few days ahead of all of this.

**Comment by clintongormley** [comment]
Hi @HenrikOssipoff 

Thanks for reporting.  Could you add the details about how you set up the socket appender logging? Wondering if this is related to #12542

**Comment by clintongormley** [comment]
We've just discussed this in FixItFriday and agree that logging across the network is a really bad idea for a busy Elasticsearch server, and not a configuration that we want to support.

There are plenty of tools available which can tail log files and ship them to a central server, including Logstash and [Filebeat](https://github.com/elastic/filebeat)
