### ISSUE TITLE
Unable to find a field mapper for field in nested query using field_value_factor

### ISSUE THREAD

**Issue by vrepsys** [elastic/elasticsearch#12871]
Here's the mapping:
```http
PUT books-index
{
  "mappings": {
    "books": {
      "properties": {
        "tags": {
          "type": "nested",
          "fields": {
            "name": {
              "type": "string"
            },
            "weight": {
              "type": "float"
            }
          }
        }
      }
    }
  }
}
```

Then doing a nested query using a field_value_factor fails with an error
```http
GET books-index/books/_search
{
  "query": {
    "nested": {
      "path": "tags",
      "score_mode": "sum",
      "query": {
        "function_score": {
          "query": {
            "match": {
              "tags.name": "world"
            }
          },
        "field_value_factor": {
            "field": "weight"
         }
        }
      }
    }
  }
}
```
The error: **"nested: ElasticsearchException[Unable to find a field mapper for field [weight]]"**

Interestingly, if there's one book in the index with tags - there's no error and the query works well.

**Why is this happening? how can I prevent the error when there are no books with tags in the index?**

Any ideas?

Thank you!

**Comment by jpountz** [comment]
I suspect this is because you gave `weight` instead of `tags.weight` as a field name. For such questions however, please use the [forums](https://discuss.elastic.co/) instead of creating a Github issue. We aim at using Github issues only for confirmed bugs and feature requests.

**Comment by vrepsys** [comment]
There's a related question on stackoverflow since a long time ago that gets upvotes, but nobody can answer: http://stackoverflow.com/questions/27274240/function-score-query-with-field-value-factor-on-not-yet-existing-field

Also this issue very similar to this: https://github.com/elastic/elasticsearch/issues/10948
But it is not clear if and how it's been resolved.

Are you sure this is not an issue with elastic?

P.S. "tags.weight" instead of "tags" makes no difference.

**Comment by clintongormley** [comment]
@vrepsys your mapping is incorrect.  You used `fields` instead of `properties`. 

    PUT books-index
    {
      "mappings": {
        "books": {
          "properties": {
            "tags": {
              "type": "nested",
              "properties": {
                "name": {
                  "type": "string"
                },
                "weight": {
                  "type": "float"
                }
              }
            }
          }
        }
      }
    }

At least in 2.0 (not sure about before), your mapping fails with an exception

**Comment by vrepsys** [comment]
Thank you!
