### ISSUE TITLE
Add Google Cloud Storage Repository

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#12880]
_From @dadoonet on January 28, 2014 21:18_

We want to have Snapshot and Restore available for Google Storage Repository.

_Copied from original issue: elastic/elasticsearch-cloud-gce#11_

**Comment by dadoonet** [comment]
_From @merrellb on April 17, 2014 17:42_

Is this the same as Google Cloud-Datastore (https://cloud.google.com/products/cloud-datastore/)?  Definitely would be a great addition (and add feature parity with the AWS plugin)

**Comment by dadoonet** [comment]
_From @dspiteself on June 7, 2014 17:29_

+1

**Comment by dadoonet** [comment]
_From @benjamin-smith on July 16, 2014 16:6_

+1 !!!

**Comment by dadoonet** [comment]
_From @danielschonfeld on July 21, 2014 0:2_

Is this in the works at all?

**Comment by dadoonet** [comment]
@tlrx Wanna take it?

**Comment by dadoonet** [comment]
_From @tlrx on October 24, 2014 13:21_

@merrellb this issue concerns Google Cloud Storage, which is a cloud based object storage service.

Google Datastore is more a NoSQL data storage service.

**Comment by dadoonet** [comment]
_From @tlrx on October 31, 2014 16:45_

@dadoonet @imotov @s1monw I'll be glad if you can review this

**Comment by dadoonet** [comment]
_From @vvasanth86 on February 18, 2015 17:28_

Would this be available soon? Thanks!

**Comment by dadoonet** [comment]
_From @pires on March 6, 2015 16:3_

+1

**Comment by dadoonet** [comment]
_From @thekantian on March 30, 2015 12:55_

What's blocking getting this in? Just spun up an ES cluster in GCE and right now I have 2 choices for backup (I think):

1) rsync files to GCS (the old way of backups, don't get any of the snapshot/restore goodies)
2) set up NFS shared folder on all machines and use as a target (tons of overhead that I don't want to deal with).

Given that GCS exists, would be a much better option... What's the roadmap for getting this merged? - 6 months seems like a long time to review...I'm happy to help with whatever work needs to be done!

**Comment by dadoonet** [comment]
_From @tlrx on March 30, 2015 13:0_

@thekantian I apologize for the time it takes but be sure it's still on the road. Some internal classes in elasticsearch have changed multiple times the last few months, making this difficult to test and merge. Now things are stabilized it should not take too much time to be merged.

As soon as it is merged we would be happy to have testers :)

**Comment by dadoonet** [comment]
_From @thekantian on March 30, 2015 13:5_

No apology necessary! Thanks for the update - I was just wondering if there was anything I could do to help move it along since I'm sure it will improve the Google Cloud platform experience for ES a lot for us all!

**Comment by dadoonet** [comment]
_From @pires on March 30, 2015 14:6_

Great news :+1:

**Comment by dadoonet** [comment]
_From @hussein-vastani on April 17, 2015 13:40_

+1 
Hoping to see this land soon! My current GCE project has a dependency on this. Thank you.

**Comment by dadoonet** [comment]
_From @soundofjw on May 5, 2015 23:26_

Who do we buy :beers: for to see this completed? @tlrx ? :)

**Comment by dadoonet** [comment]
_From @simonmorley on May 6, 2015 0:49_

+1

**Comment by dadoonet** [comment]
_From @ghost on July 1, 2015 19:18_

+1 !

**Comment by dadoonet** [comment]
_From @akleiman on July 1, 2015 19:20_

+1

**Comment by dadoonet** [comment]
_From @fvantin on July 1, 2015 19:57_

+1

**Comment by dadoonet** [comment]
_From @MaxDaten on July 11, 2015 12:39_

+1

**Comment by dadoonet** [comment]
_From @psychonaut on August 13, 2015 9:27_

+1

**Comment by dadoonet** [comment]
_From @vishalshah-org on August 14, 2015 12:12_

any updates on this, we are paying big time $$ to backup to S3 from our google cloud infrastructure :( any help appreciated!
thanks.

**Comment by dadoonet** [comment]
Note that there is a pending PR available here: https://github.com/elastic/elasticsearch-cloud-gce/pull/39

**Comment by omriiluz** [comment]
+1

**Comment by espeed** [comment]
Note Google Cloud Storage (GCE) is interoperable with S3 clients so you can use existing S3 clients:

- https://cloud.google.com/storage/docs/interoperability
- https://github.com/elastic/elasticsearch-mapper-attachments/blob/master/dev-tools/upload-s3.py

**Comment by 24601** [comment]
+1 to @espeed's comment. 

Is there an issue in using Google Cloud Storage's s3 compatibility? We are testing it as our repository for snapshots without an issue so far, turned on S3/HMAC compatibility, generated a key, set endpoint to the google storage API end point, and are simply using the s3 support. It works perfectly. 

Is there a long term/production use concern with this? Our testing reveals it works fine, would like to know if we are missing some issue here?

**Comment by dadoonet** [comment]
Using Google Storage with `cloud-aws` plugin is not part of our integration tests. So we can't say if it's safe for production usage. 
You could open a discussion on discuss.elastic.co to see if other users have already tested it?

**Comment by chrislovecnm** [comment]
It is my understand that Google Storage is not compatible with multipart uploads - so can anyone verify that the AWS plugin works?

Who do I need to bribe to get this fixed? Google is a partner with elastic...

**Comment by tlrx** [comment]
> Who do I need to bribe to get this fixed? Google is a partner with elastic...

We're talking about adding a new feature, not _fixing_ a bug, and partnerships do not influence anything here: there's good chance that elasticsearch 2.x has support for Google Storage. The latest pull request in https://github.com/elastic/elasticsearch/pull/13578 and we are in final review stages.

**Comment by cmoad** [comment]
I can verify that the AWS S3 backups work from a GCE cluster. We've been
using it that way for months.

**Comment by chrislovecnm** [comment]
@tlrx I understand that this is a new feature ;) good news, thanks

@cmod AWS s3 plugin -> google storage? Which version of the plugin?

**Comment by cmoad** [comment]
@chrislovecnm I deleted my comment. I misread the question.

**Comment by bndixit** [comment]
:+1:

**Comment by bndixit** [comment]
+1

**Comment by haizaar** [comment]
Can anyone please update on the progress of this feature?

**Comment by tlrx** [comment]
@haizaar Now #14050 has been merged, we need to add tests in this pull request. Once it's done, it should be able to be reviewed, hopefully soon.

**Comment by motinani** [comment]
+1

**Comment by haizaar** [comment]
Hi guys,

Can anyone please share progress update on this? At least I would like to understand if it will be available in the next 1-2 months or should I turn to alternatives.

P.S. Regardless, GCE users out there miss this feature big time!

**Comment by worroc** [comment]
+1

**Comment by tlrx** [comment]
A plugin for Google Cloud Storage has just been merged into master (see elastic/elasticsearch/pull/13578) and will be released with the next version of Elasticsearch.
