### ISSUE TITLE
Output PluginInfo only when in verbose mode

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12907]
When installing a plugin, the plugin manager outputs PluginInfo by default, which I think it should only do in verbose mode.  Extra points for formatting the info nicely:

    .........................................................................................................DONE
    PluginInfo{name='cloud-aws', description='The Amazon Web Service (AWS) Cloud plugin allows to use AWS API for the unicast discovery mechanism and add S3 repositories.', site=false, jvm=true, classname=org.elasticsearch.plugin.cloud.aws.CloudAwsPlugin, isolated=true, version='2.0.0-beta1'}

**Comment by jimhooker2002** [comment]
Got a fix for this.  I'll submit the pull request later today.
