### ISSUE TITLE
Ensure `localhost` works on IPv4 and IPv6

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#12906]
Today we use `localhost` in all of our curl examples, but Elasticsearch is binding to either `127.0.0.1` or `::1`, and `localhost` may not work.

We should try to bind to both.

**Comment by dakrone** [comment]
Related to https://github.com/elastic/elasticsearch/issues/12914 and https://github.com/elastic/elasticsearch/issues/12915

**Comment by rmuir** [comment]
I'm working on this: I've made progress but need a few more hours to have something to show.
