### ISSUE TITLE
Small code Refactor - shard variable dependency from processFirstPhaseResults as shard is no more needed

### ISSUE THREAD

**Issue by HarishAtGitHub** [elastic/elasticsearch#12918]
this is a small commit to remove the
shard variable dependency from processFirstPhaseResults as shard is no more
needed here . it only deals with the results obtained from the synchronous search on each shard.
It is [here](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/search/type/TransportSearchTypeAction.java#L361)

**Comment by HarishAtGitHub** [comment]
pull request : https://github.com/elastic/elasticsearch/pull/12917

**Comment by jpountz** [comment]
Fixed via #12917
