### ISSUE TITLE
Querying on a date range

### ISSUE THREAD

**Issue by icecrime** [elastic/elasticsearch#12912]
I'm quite new to Elastic Search, and trying to store and visualize time-series data. I've removed Kibana from the equation, and I'm down with the following behavior that I can't explain.

A document is indexed with what seems to be a proper timestamp:

```
# curl elasticsearch:9200/[redacted]/[redacted]/[redacted]?fields=_timestamp | jq .
{
  "_index": "[redacted]",
  "_type": "[redacted]",
  "_id": "[redacted]",
  "_version": 1,
  "found": true,
  "fields": {
    "_timestamp": 1439673273000
  }
}
```

Querying with a date range which does include this document:

```
# cat query
{
  "size": 0,
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "analyze_wildcard": true,
          "query": "*"
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "_timestamp": {
                  "gte": 1439660028476,
                  "lte": 1439674428476
                }
              }
            }
          ],
          "must_not": []
        }
      }
    }
  }
}
```
Gives me no result:

```
# curl -XGET elasticsearch:9200/[redacted]/[redacted]/_search -d @query | jq .
{
  "took": 3,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  }
}
```

Relevant timestamps:
- Query lower bound `1439660028476` (Sat, 15 Aug 2015 17:33:48 GMT)
- Query upper bound `1439674428476` (Sat, 15 Aug 2015 21:33:48 GMT)
- Document timestamp `1439673273000`  (Sat, 15 Aug 2015 21:14:33 GMT)

Elastic Search is 1.7.1, running in PST timezone.

**Comment by steeve** [comment]
does it work when you replace `query_string` with a `match_all` query ?

**Comment by icecrime** [comment]
@steeve Mmm good point but no, same result.

**Comment by icecrime** [comment]
Also something that might be relevant here: my mapping has

```
    "_timestamp": {
          "enabled": true,
          "store": true
        },
```

**Comment by steeve** [comment]
Try and remove `store` from you mapping

**Comment by dadoonet** [comment]
Please use discuss.elastic.co for questions. We'll be happy to help there.

Thanks!
