### ISSUE TITLE
[Docs] Provide List of Expected Exceptions

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#12946]
With the introduction of structured exceptions, it would be great if we could start to list all _expected_ exceptions and what they mean to the catcher (e.g., can they retry? should they retry?).

I think it should start simple with Search exceptions and Indexing exceptions, then build out from there. Perhaps we should even have an error code system to make looking them up easier?

**Comment by yazaddaruvala** [comment]
May I ask why this isn't getting prioritized?

Its really frustrating not knowing which exceptions can be caused, if they should be retried, or not. A list with explanations would be tremendously useful.

**Comment by jasontedor** [comment]
No interest in two-and-a-half years, closing.
