### ISSUE TITLE
multicast ping should work over ipv6

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#12945]
followup to #12942

Currently this is only going to work over ipv4, due to the address used. We should support a pure v6 environment: maybe it works today if you use a -D to change the address, but it sorta defeats the purpose of not requiring configuration:)

However, I think its best to get #12914 straightened out on the OS X first, to eliminate any confusion.

**Comment by clintongormley** [comment]
Multicast support has been removed. Closing

**Comment by rmuir** [comment]
Multicast has been removed? Why do i still see the plugin in master?

**Comment by clintongormley** [comment]
I was under the mistaken impression that it was deprecated when it was moved to a plugin.

**Comment by clintongormley** [comment]
See #16310

**Comment by clintongormley** [comment]
Multicast has been removed by #16326
