### ISSUE TITLE
Elasticsearch doesn't want to stop

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#12941]
I did a large-ish bulk load on my laptop over the weekend of about five million documents into Elasticsearch 1.7.1. They were large-ish so I set the refresh_interval to `-1` during the load process and to `1s` after it was finished. I also sent a `_flush` to the index after all the documents were loaded so I could send a `_count` and get accurate numbers.

Anyway, after that I tried to stop Elasticsearch so that I could shut it down and make a copy of the load for posterity. I hit `ctrl-c` in its window. It didn't die. I worked for an hour and came back. Still not dead. The only runnable threads are ConcurrentMergeScheduler [doing its thing](https://gist.github.com/nik9000/3dc4df2b97ced8c7d60b). It also had three threads that looked [parked](https://gist.github.com/nik9000/96d3ddc5408fbbda03fd) but in the middle of something.

These wait times seem to be a bit much. I get waiting for a minute to try to finish a merge but an hour is going to have people `kill -9`ing Elasticsearch pretty consistently.

**Comment by s1monw** [comment]
do you have a stack dump from this?

**Comment by nik9000** [comment]
> do you have a stack dump from this?

Those two links above are stack dumps of the threads that I think are the trouble. I can take a stack dump of the whole thing though.

**Comment by nik9000** [comment]
https://gist.github.com/nik9000/85b3172585a7a47e2ee5

**Comment by s1monw** [comment]
this helps I will update you with ideas later!

**Comment by s1monw** [comment]
I acutally think we always had that problem but since https://github.com/elastic/elasticsearch/pull/10833 it's showing. We forced -9 basically before. In master / 2.0 this issue is gone since we don't call maybeMerge

**Comment by mikemccand** [comment]
Thanks @nik9000, what's happening is merges are falling way behind (laptop hard drive), and in ES 1.x we let Lucene's CMS do hard throttling of new merges in this case.

But in 2.0 this should be fixed with the Lucene upgrade just before https://github.com/elastic/elasticsearch/pull/8643 ... if you can re-run your test with 2.0 beta that would be great :)

**Comment by nik9000** [comment]
> But in 2.0 this should be fixed with the Lucene upgrade just before #8643 ... if you can re-run your test with 2.0 beta that would be great :)

I'll do that.

I have two questions then:
1. Is it ok that 1.7-ish can get into a state where their init/systemd scripts won't kill them? I imagine its helpful to have this issue be google-able but is that enough?
2. In the case of my load going on right now can I safely `kill -9` elasticsearch? I suspect so, but it took a long time and I just want to make sure.

**Comment by s1monw** [comment]
> 2. In the case of my load going on right now can I safely kill -9 elasticsearch? I suspect so, but it took a long time and I just want to make sure.

by that time yes

> 1. Is it ok that 1.7-ish can get into a state where their init/systemd scripts won't kill them? I imagine its helpful to have this issue be google-able but is that enough?

it was always the case just hidden

**Comment by nik9000** [comment]
> But in 2.0 this should be fixed with the Lucene upgrade just before #8643 ... if you can re-run your test with 2.0 beta that would be great :)

Indeed - this problem doesn't happen in the 2.0 branch. Elasticsearch sits there for a few seconds after being killed, obviously trying to finish something off, and then dutifully dies. Sometimes it logs a nice error about jobs being submitted to killed thread pools. It still dies. Which is great.
