### ISSUE TITLE
Replicate Closed Indices

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#12963]
Closing an index is a good way to save memory and to remove unneeded indices from your cluster without deleting the data. It can also help to improve performance if you have an extremely long retention period where you rarely query the oldest info. This allows indices to be opened on-demand, then closed when you are done.

However, there's a small problem with closed indices: they aren't replicated in the case of data loss. This makes sense because the cluster gives up managing them, but it also can create surprise situations in normal shard loss scenarios (e.g., lost drives).

Without opening the closed indices, there needs to be some way to force them to be [re-]replicated or to somehow warn that they are not replicated.

**Comment by rjernst** [comment]
Isn't the way to do this to take a snapshot?

**Comment by pickypg** [comment]
Snapshots are always the ultimate disaster recovery scenario and they are absolutely the best solution, but you don't even know that you need to restore from the snapshot until opening the index fails due to missing shards for closed indices.

**Comment by bleskes** [comment]
I think there is merit to this issue (although it requires a big but doable conceptual change - closed shards). The main use case for closed indices is an easy-to-access archive. It’s good for the cluster to react if one the archived copies is lost (server blows up) and make sure we create a new copy of the data.

**Comment by rtoma** [comment]
Maybe its worth updating docs for Elasticsearch and Curator (offering an issue way of closing indices), so users will know what risks are involved?

**Comment by smford** [comment]
I second this request, we have worked around the issue by writing a script that re-opens an indices from which ES then replicates it across.  Once replicated the script then closes it again.
It would be nice if there was the ability to replicate the closed indices without this bodge.

**Comment by clintongormley** [comment]
Perhaps related to #12847

**Comment by prog8** [comment]
Are there any conclusions related to replicating and relocating closed indices? What kind of changes this requires in ES code? Maybe the first step could be a plugin which does something @smford has mentioned?

**Comment by bleskes** [comment]
@prog8 you are more than welcome to try - but the amount of changes are considerate - this is rooted deep in our infra strcuture and is definitely not a low hanging fruit.

**Comment by jasontedor** [comment]
> Maybe the first step could be a plugin which does something @smford has mentioned?

To be clear to what @bleskes said, a plugin implementation will not be possible. This requires fundamental changes inside of Elasticsearch.

**Comment by yackushevas** [comment]
Any news?

**Comment by chandlermelton** [comment]
Curious about this as well. @smford, would you be willing to link to/describe your script?

**Comment by smford** [comment]
@chandlermelton : Getting approval from work and the author to release the script. Will get back to you soon.  @jinnko

**Comment by jinnko** [comment]
This is the script we've used.  It's nothing special, simply a loop to get a list of indices, open the closed ones and wait for them to complete being verified or re-routed, then close them again.

https://gist.github.com/jinnko/78072a77c8302390ff0830963492e9f4

**Comment by chandlermelton** [comment]
Thanks guys!

**Comment by DaveCTurner** [comment]
I think this can be closed in favour of #30188.
