### ISSUE TITLE
detect_noop on index api

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#12969]
Currently you can send the same data over and over again to the index api and the document will be reindexed even if it hasn't changed. Maybe we should not reindex it? We're already looking to default detect_noop to true for the update api (#11282) so this isn't that big a change conceptually.

**Comment by jpountz** [comment]
I think the trade-off is more complicated than on the update API, since the index API never needs to fetch the source which is a costly operation (random seek) while the update API needs to do it anyway in order to patch the document.

**Comment by clintongormley** [comment]
I agree with @jpountz on this.  If you want this functionality you should use the update API instead

**Comment by nik9000** [comment]
> I think the trade-off is more complicated than on the update API, since the index API never needs to fetch the source which is a costly operation (random seek) while the update API needs to do it anyway in order to patch the document.

Fair enough.
