### ISSUE TITLE
Add /_cat/clusters for tribe nodes

### ISSUE THREAD

**Issue by TinLe** [elastic/elasticsearch#12975]
This is an enhancement request.  It would be nice to have something like a /_cat/clusters API for tribe nodes to return the list of clusters the tribe node know about.  Also good to know those that are connected and healthy vs those that are not connected/not healthy.

I am currently using /_cat/nodes?h='h,i,n' and look in node name for node name that has a '/' in it to figure out the tribe cluster it is in.

For example: 'lva1-app1234.prod_tribe/galene-tribe_ela4' mean that the tribe put it in the galene-tribe_ela4 cluster.

**Comment by markwalkom** [comment]
Great idea!

**Comment by javanna** [comment]
We did something similar (although not a cat api) for the newly introduced cross cluster search functionality (which will replace the tribe node): https://github.com/elastic/elasticsearch/issues/23925 .
