### ISSUE TITLE
Opening an index with a missing analyzer stopword file result in a node unavailability

### ISSUE THREAD

**Issue by Avricot** [elastic/elasticsearch#12987]
Is it ok that opening an index with a missing analyzer stopword file returns {"acknowledged":true} and enter in a loop searching/waiting for the missing file, resulting in a global node unavailability ?
I think it should just return an error, keep the index closed and the node healthy.

Test :

        echo "le\nla\nles\n" > /home/quentin/stopwords_fr.txt
        
        read -d '' POST <<EOF
        {"settings": {
           "analysis":{
             "filter":{
               "stop_francais":{
                 "type":"stop",
                 "stopwords_path": "/home/quentin/stopwords_fr.txt"
                }
              }
            }
          }
        }
        EOF
        curl -s -XPOST http://localhost:9200/test-crash -d "$POST";echo

Then delete file and try to close/open 
        
        rm /home/quentin/stopwords_fr.txt
        curl -XPOST "localhost:9200/test-crash/_close"
        curl -XPOST "localhost:9200/test-crash/_open"

Error in the logs

    Caused by: org.elasticsearch.env.FailedToResolveConfigException: Failed to resolve config path [/home/quentin/stopwords_fr.txt], tried file path [....], and classpath

**Comment by clintongormley** [comment]
Hi @Avricot 

Agreed - I've added a note to #9126 as i think this should be part of that change.  Closing in favour of #9126
