### ISSUE TITLE
Ability to set default geo_point value

### ISSUE THREAD

**Issue by kurtado** [elastic/elasticsearch#12998]
Spoke with @nknize about the possibility of setting a default geo_point lat/lon value, and he said it would be possible to add this feature.

**Comment by rjernst** [comment]
What do you mean by default? `null_value` like we have for other field types?

**Comment by ideadapt** [comment]
`null_value` is still not supported for geo_point fields. But its possible to use a [set processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/set-processor.html) as requested and implemented with #17659 (using `"override": false` option). Processors transform a document to be indexed, before it is given to the indexer.

@kurtado Does this new ability work for you?
