### ISSUE TITLE
Ordering Significant Terms aggregation

### ISSUE THREAD

**Issue by acassaignemondeca** [elastic/elasticsearch#12996]
Hello,

from a discussion on Elastic forum it seems impossible to order results from a Significant Terms aggregation, the 'order' parameter is not handled.

Is it possible to add 'order' as in the Terms aggregation ?

Best regards,
Arnaud

**Comment by clintongormley** [comment]
@markharwood could you comment on this?

**Comment by markharwood** [comment]
There are typically a huge number of "candidate" terms produced by significant terms. What determines the final set is the statistical significance of their frequencies. If we introduced another sort order then they would no longer be "significant" terms in the intended sense. 
It is possible to plug-in custom significance heuristics which alter the score but we [deliberately limited the scope] (https://github.com/elastic/elasticsearch/issues/10613#issuecomment-93948953) of how they compute scores to just dealing with the supplied frequencies.

**Comment by clintongormley** [comment]
thanks @markharwood  - makes sense. closing

**Comment by acassaignemondeca** [comment]
Thank you for your responses and sorry not to have responded earlier.

Actually I am using Kibana and the Significant Terms table is not sorted by descending number of occurrences. Without changing anything in the result and the way it is computed, my request is to have the result sorted by count of occurrences as a post-treatment step.

Here is my use case:

Kibana Significant Terms table:
![signterms](https://cloud.githubusercontent.com/assets/13748482/9445574/1a65bb2e-4a8d-11e5-9fa1-89e4579f16d2.png)

I see the doc_count field in the ES result, ideally result would be ordered by this field for the 10 result items. May be it is something that should be done at Kibana level.

Arnaud

**Comment by markharwood** [comment]
This indeed is a [Kibana issue] (https://github.com/elastic/kibana/issues/2018)
