### ISSUE TITLE
Some URLs in the reference docs prevent selecting the version of the docs you're viewing

### ISSUE THREAD

**Issue by trejkaz** [elastic/elasticsearch#13006]
If you search for "elasticsearch api" on Google, one of the hits you get back is this one:

![screen shot 2015-08-20 at 9 26 47 am](https://cloud.githubusercontent.com/assets/43236/9372068/b94d06e8-471d-11e5-8516-d9819b661987.png)

So I went there: https://www.elastic.co/guide/en/elasticsearch/reference/1.4//index.html

Then I tried to view the docs for 2.0 by changing the combo box. It reloads the page, but doesn't actually go to the 2.0 version of the docs.

This occurs on both Chrome and Firefox.

**Comment by dadoonet** [comment]
Agreed. Sounds like it's caused by the double `//` before `index.html`.
If you remove it, then you can change the version using the dropdown menu.

**Comment by trejkaz** [comment]
Yeah, figured that out after comparing with a colleague who said the problem wasn't happening for him. Sent him the link - happened for him. Removed the extra slash on mine, started working properly.

Still, the double-slash version is in the Google index now, and perhaps a 404 or a redirect would be a better treatment of it, rather than the page loading but then failing to work correctly.
