### ISSUE TITLE
API to show the number of index fields

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#13003]
I have seen a few issues where having a count of fields across indices would have been helpful to have for troubleshooting indexing performance, OOME, etc. Although this information can be gathered from mappings, it could be useful to show a count of index fields akin to what Lucene's CheckIndex tool displays per segment.
```
Segments file=segments_c numSegments=12 version=4.10.4 format= userData={translog_id=1434119476444, sync_id=AU9BzZeqTGo-78cobmuv}
  1 of 12: name=_v docCount=9873
    version=4.10.4
    codec=Lucene410
    compound=false
    numFiles=12
    size (MB)=16.177
    diagnostics = {os=Mac OS X, java.vendor=Oracle Corporation, java.version=1.8.0_25, lucene.version=4.10.4, mergeMaxNumSegments=-1, os.arch=x86_64, source=merge, mergeFactor=10, os.version=10.10.1, timestamp=1434119509593}
    no deletions
    test: open reader.........OK
    test: check integrity.....OK
    test: check live docs.....OK
>>> test: fields..............OK [27 fields] <<<
    test: field norms.........OK [6 fields]
    test: terms, freq, prox...OK [282439 terms; 2040942 terms/docs pairs; 2958473 tokens]
    test: stored fields.......OK [30542 total field count; avg 3.093 fields per doc]
    test: term vectors........OK [0 total vector count; avg 0 term/freq vector fields per doc]
    test: docvalues...........OK [1 docvalues fields; 0 BINARY; 1 NUMERIC; 0 SORTED; 0 SORTED_NUMERIC; 0 SORTED_SET]
```
Does this functionality exist in another API?

**Comment by clintongormley** [comment]
Hi @inqueue 

Given that this is a one-off (and seldom used) diagnostic which can be answered already via the mapping API, I'm not sure it is worth adding a dedicated API.  Probably something we could add to https://github.com/elastic/elasticsearch-support-diagnostics instead, no?

**Comment by inqueue** [comment]
Hi @clintongormley,

I suppose I am expecting to find a field count somewhere in the _cat API, maybe in _cat/indices or perhaps _cat/segments|shards. I could not find a clean way retrieve this information from mappings without parsing its output, which we can do with es-support-diagnostics.

To gather this information, would you suggest properties or something like ```GET */_mapping/field/*```? Other suggestions?

Thank you

**Comment by clintongormley** [comment]
Yes, the field mapping API would be the appropriate one.  Also, we're planning on adding a soft limit on the number of fields you can have an index, which will help here.  See https://github.com/elastic/elasticsearch/issues/11443
