### ISSUE TITLE
Question: Tribe node and search.queue?

### ISSUE THREAD

**Issue by cmfatih** [elastic/elasticsearch#13000]
I have a question... Let's say we have 3 tribe nodes, 10 data nodes and # of replicas is 1 for each shard. How tribe nodes balance requests? Or even does it balance requests? Sometimes I see that while one node over loaded by search queries, the other node (which has replica of that shard) just sits and do nothing. Would be using only one tribe node help in this case? Or they are not related at all?

ES v1.4.4

**Comment by clintongormley** [comment]
Hi @cmfatih 

Please use the forums for questions like this http://discuss.elastic.co/.  The tribe nodes behave like any other client nodes: they round-robin requests around all copies (primary and replicas) of a shard.
