### ISSUE TITLE
Remove support for address resolving in InetSocketTransportAddress

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#13014]
We shouldn't do any hostname resolving inside ES even though it's disabled by default we should't do it at all. it's simpler and more reliable to just use IPs. This will essentially remove `network.address.serialization.resolve` which is false by default.

this is a followup from #12999

**Comment by kenden** [comment]
Hi @s1monw,
Could you explain why we shouldn't do any hostname resolving inside ES?
What if we use for example AWS Route53 to point to the IPs of an Elasticsearch cluster?
(Ex: "myaddress.myserver. -> 10.0.10.51)
If the IP address is changed to, say 10.0.10.59, AWS clients will still be trying to access the old IP address and get a NoNodeAvailableException.

**Comment by s1monw** [comment]
> Could you explain why we shouldn't do any hostname resolving inside ES?
What if we use for example AWS Route53 to point to the IP of an Elasticsearch cluster?
(Ex: "myaddress.myserver. -> 10.0.10.51)
If the IP address is changed to, say 10.0.10.59, AWS clients will still be trying to access the old IP address and get a NoNodeAvailableException.

sorry I don't understand what you are referring to. This change disables the potential reverse lookup for IP -> hostname that we do to render nodestats etc. I don't think this will affect transport clients?

**Comment by kenden** [comment]
But don't we use InetSocketTransportAddress to set up a TransportClient?
https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html
Sorry if I'm getting this wrong.  This seems related to this issue:
https://github.com/elastic/elasticsearch/issues/10337

**Comment by s1monw** [comment]
> But don't we use InetSocketTransportAddress to set up a TransportClient?

so to be clear the change here is what is default in previous version of elasticsearch. We never lookup the hostname from the IP. for the transport client you should be all fine here but nodes in the cluster might be different. the node will likely drop out of the cluster and then rejoin with the new IP? to enable that host name resolution you had to enable an undocumented setting so I don't think it's really changing anything for you?
