### ISSUE TITLE
Move LocalTransport under `src/test` 

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#13015]
I am not sure why we have this sitting here in production code. We should be able to disable clustering without this etc. I think this stuff belongs under `src/test`

**Comment by rjernst** [comment]
+1

**Comment by jpountz** [comment]
+1

**Comment by s1monw** [comment]
I think the transport part is harder than expected since I think for the embedded case where you don't want anything to connect to ES you need this kind of transport. Yet, the discovery part I think should just go into src/test or maybe even should be deleted altogether. It's there today to speed things up but it would be awesome if we could make our default (zen) fast enough instead.

**Comment by nik9000** [comment]
I believe @s1monw got to this when he replaced `LocalTransport` with `MockTransport`.
