### ISSUE TITLE
Using enabled:false on document type throws exception in tests

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#13017]
In integration tests, using `enabled: false` on a root document type makes document indexing fails.

Here is the mapping I use:
```
"my_doc_type": {
  "enabled": false
}
```

But then indexing a document throws a MapperParsingException with the following stack:
```java
MapperParsingException[failed to parse]; nested: AssertionError;
	at __randomizedtesting.SeedInfo.seed([1B10B6999E316CD7:4AED1D00C8EC9444]:0)
	at org.elasticsearch.index.mapper.DocumentParser.innerParseDocument(DocumentParser.java:155)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:317)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:313)
	...
```

The assertion is located in the `DocumentParser` class:

```java
            // try to parse the next token, this should be null if the object is ended properly
            // but will throw a JSON exception if the extra tokens is not valid JSON (this will be handled by the catch)
            if (Version.indexCreated(indexSettings).onOrAfter(Version.V_2_0_0_beta1)
                && source.parser() == null && parser != null) {
                // only check for end of tokens if we created the parser here
                token = parser.nextToken();
                assert token == null; // double check, in tests, that we didn't end parsing early
            }
```

When assertion are disabled, everything is OK. I did a simple test to reproduce the issue here:
https://github.com/tlrx/elasticsearch/commit/94712121dd524c48f2dc40c787efd1eb6375d799

This assertion has been added recently and I don't know much about this part of code, maybe @rjernst can help here?

**Comment by rjernst** [comment]
This seems like a bug maybe? why are we not consuming the token there?

**Comment by tlrx** [comment]
Looks like it has been introduced by #11414

**Comment by rjernst** [comment]
I think you misunderstood. The assertion code is correct, it means there was leftover stuff at the end of parsing. But *why* is there leftover stuff in this case. what is the document you are sending, I only see the mapping in the original description? My hunch is, we need to fully consume the parser for mappings that are disabled.

**Comment by tlrx** [comment]
What I don't get is why I can create this mapping and index documents in elasticsearch but cannot do exactly the same thing in integration tests.

Here is the document I index: https://github.com/tlrx/elasticsearch/commit/94712121dd524c48f2dc40c787efd1eb6375d799#diff-82784da2187574da5398ae215c8a6795R276

This test fails on my computer and I don't get why.

**Comment by rjernst** [comment]
Assertions are enabled in tests, but not when running with bin/elasticsearch.

**Comment by rmuir** [comment]
Why isn't this a real check

**Comment by tlrx** [comment]
@rjernst Yes I know, but the test I linked to seems good to me and I don't see why this assertion throws up. Can you please have a quick look to the code and/or try to reproduce?

**Comment by clintongormley** [comment]
this is a bug.  The following fails with assertions enabled:

    PUT my_index
    {
      "mappings": {
        "my_type": {
          "enabled": false
        }
      }
    }
    
    PUT my_index/my_type/1
    {
      "foo": "bar"
    }

The whole type is disabled, which means the _source should be stored but nothing should be indexed.  It looks like we're just skipping parsing completely instead of consuming the tokens.

**Comment by rjernst** [comment]
I have a test reproducing the issue and am investigating.

**Comment by tlrx** [comment]
@rjernst Thanks for the work you have done :) Unfortunately I reopen this bug because indexing a document (like @clinton suggested) now fails with a `NullPointerException` (I tested on latest snapshot - build e8834cc78c13a507e2851908f8d51489e7888570).

As far as I understand the code it seems that your fix skips the document parsing when the type is disabled. So field mappers like `UidFieldMapper` are not used, resulting in a null `uid` thrown [here](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/shard/IndexShard.java#L515). 

I'm not familiar with this part of the code but if you don't have time to look further please let me know and I'll try to have a look.
