### ISSUE TITLE
Put a limit on type name length

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#13021]
Index names already have a character limit of 255 characters or less. This should also be applied to types.

```http
PUT /my-index/type-0airn7cyol1jfddmrzax5xzw8nue8qkcetnhux2apco8rpi1iztwwq1vp65skvnolmal7ruoabkqtl6xurr0gwivkpmpu6kmmarjeugijzvfugv8ly0nbtleytjeruistrtmthmqyiuvrtwwzzt8gburbpiu1jpqprktjf7swesbjjenxnmjmypygwktgifyo6gigbv8wgkjained5pbikd5whybj22tas60rncmefbwb4xuampjvxbo3lpndlsoy8AFSADtsywxgkxawdfsl9maue1nfqysepuokgrybvhskhwn/1
{
  "field" : "value"
}
```

I cannot think of a legitimate use case for obscenely large type names and using them as keys is a mistake. If a user were to actually want this, then they can add a `not_analyzed` string field (perhaps `keyword` field in the future!) to support this behavior without abusing the type mappings.

**Comment by s1monw** [comment]
+1

**Comment by s1monw** [comment]
`throw new InsanityException("what do you expect?")`

**Comment by rjernst** [comment]
There was a PR last year some time to limit lots of names in length and characters. @dakrone what ever happened to that?
