### ISSUE TITLE
need clarification for mmapfs?

### ISSUE THREAD

**Issue by lokeshhctm** [elastic/elasticsearch#13048]
How can we increase virtual memory on linux?
But if use mmapfs, how it works? In case we have 100 indexes and each of size like 2-3 GB.
In case we have memory up to like 20 GB and in such case will elasticsearch handle, how many will stay in memory and how memory will remain on disk and in this case, mmapfs is not an option?

**Comment by clintongormley** [comment]
Hi @lokeshhctm 

Please ask questions like these on the forum instead: http://discuss.elastic.co/
