### ISSUE TITLE
Explicitly mention applied dynamic mapping changes

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#13065]
When mapping is updated dynamically we get something like this;

```
[2015-08-24 11:50:03,383][INFO ][cluster.metadata         ] [mark] [index-2015.01.15] update_mapping [data] (dynamic)
```

It'd be super awesome if we provided a bit more information for the user to be aware of what is updated/had changed in their field structure. I am thinking something like this;

```
[2015-08-24 11:50:03,383][INFO ][cluster.metadata         ] [mark] [index-2015.01.15] update_mapping [data] (dynamic - field9 added => string, field2 updated => int)
```

**Comment by clintongormley** [comment]
There are people who add thousands of fields in a single document, which could make the logging a bit overwhelming.  Also, we don't currently have the infrastructure to do this - not a low hanging fruit.  We'd probably need to log all mapping changes.  This would need to be TRACE level as it could be way too much.

What is the problem that would be solved by adding this logging?  The log message doesn't identify a rogue document, and in fact it'd be easier to find rogue docs via the API (get mapping and field-exists query) than from the logs?

**Comment by markwalkom** [comment]
It's just an informational thing, keeping users aware of what's changed rather than having to figure out some other way of tracking this (eg VCS).

**Comment by bleskes** [comment]
I think this is a good request and we have had ways to deal with verbosity in the past (log the first X fields in debug, all in trace). The tricky part is the implementation as we don’t have the right information available at the right place at the moment (the mapping merge produces a new mapping without telling you what changed).

**Comment by jpountz** [comment]
> The tricky part is the implementation as we don’t have the right information available at the right place

@bleskes How about doing it from the merge method directly when mergeReason == UPDATE (rather than RECOVERY)? I believe we would have enough information there?

**Comment by jpountz** [comment]
cc @elastic/es-search-aggs

**Comment by bleskes** [comment]
@jpountz I'm not exactly sure how you see this happening (we need to somehow accumulate the actual changes made deeper in the object fields or compare the result at the end) but I'm sure you have an idea.  Looking forward to hear it

**Comment by colings86** [comment]
Since being raised there as not been any further feedback asking for this kind on functionality so we are going to close this for now. If there is significant feedback that the feature is desired we can look at reopening it.
