### ISSUE TITLE
Error NoMethodError: undefined method scoped'

### ISSUE THREAD

**Issue by alexander-st** [elastic/elasticsearch#13067]
Dear elastic community,

I tried to install elasticsearch with the plugin for Redmine some time ago. I retried yesterday following the instruction from https://github.com/Undev/redmine_elasticsearch1
Point 6. of the instruction is not working at my machinge. I get the following message:

C:\Bitnami\redmine-3.0.2-0\apps\redmine\htdocs>bundle exec rake redmine_elastics
earch:reindex_all RAILS_ENV=production --trace
Your Gemfile lists the gem kaminari (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of
just one of them later.
DL is deprecated, please use Fiddle
ansi: 'gem install win32console' to use color on Windows
Loading Rails environment for Resque
** Invoke redmine_elasticsearch:reindex_all (first_time)
** Invoke redmine_elasticsearch:logged (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine_elasticsearch:logged
** Execute redmine_elasticsearch:reindex_all
Recreate index for all available search types
rake aborted!
NoMethodError: undefined method scoped' for # C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.1/lib/ active_record/dynamic_matchers.rb:26:inmethod_missing'
C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/app
/models/parent_project.rb:57:in searching_scope' C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/lib /redmine_elasticsearch/indexer_service.rb:45:infor_each_parent_project'
C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/lib
/redmine_elasticsearch/indexer_service.rb:18:in reindex_all' C:/Bitnami/redmine-3.0.2-0/apps/redmine/htdocs/plugins/redmine_elasticsearch/lib /tasks/index.rake:18:inblock (2 levels) in '
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:240:in call' C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta sk.rb:240:inblock in execute'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:235:in each' C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta sk.rb:235:inexecute'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:179:in block in invoke_with_call_chain' C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/2.0.0/monitor.rb:211:inmon_synchroniz
e'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:172:in invoke_with_call_chain' C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta sk.rb:165:ininvoke'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:150:in invoke_task' C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap plication.rb:106:inblock (2 levels) in top_level'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:106:in each' C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap plication.rb:106:inblock in top_level'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:115:in run_with_threads' C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap plication.rb:100:intop_level'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:78:in block in run' C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap plication.rb:176:instandard_exception_handling'
C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:75:in run' C:/Bitnami/redmine-3.0.2-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/bin/rake:33 :in'
C:/Bitnami/redmine-3.0.2-0/ruby/bin/rake:23:in load' C:/Bitnami/redmine-3.0.2-0/ruby/bin/rake:23:in

'
Tasks: TOP => redmine_elasticsearch:reindex_all
Please any help!?!?

Or is everything working because the plugin is already in the plugin list of Redmine? How can I know if it is working or not?

Thank you for your time and help!!

**Comment by jpountz** [comment]
This error is not related to elasticsearch. You should ask this question to the elasticsearch-redmine project.

**Comment by alexander-st** [comment]
Thank you for your response!
I will try to get an answer from the plugin developers.
