### ISSUE TITLE
Same setting with different values in elasticsearch.yml should be an error

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#13079]
I hit this while smoke testing the 2.0.0 beta RC.

Today, if you have the same setting in `config/elasticsearch.yml` more than once, I think the last one silently "wins".

But I think this is too lenient/trappy?  E.g. someone may open the file, insert what they think is a new setting, but then it doesn't "take" because that setting already appears later in the file.

I think we should make this a hard error on startup instead.

**Comment by nik9000** [comment]
+1

**Comment by rjernst** [comment]
+1

Not only for different values, but the same setting twice should be an error too. We should fail early, before the user tries to change the setting (in just one place) and then hits the proposed error here.

**Comment by mikemccand** [comment]
> Not only for different values, but the same setting twice should be an error too. We should fail early, 

++
