### ISSUE TITLE
Make Bootstrap.java startup validation accessible for embedded use

### ISSUE THREAD

**Issue by nickminutello** [elastic/elasticsearch#13093]
Many of the methods are non-public.

Some of the startup validation is mixed with actually starting a node.

**Comment by clintongormley** [comment]
Hi @nickminutello 

Currently we don't test embedded Elasticsearch at all, which means that it is not a supported configuration.  We have just gone through a large number of changes to lock Bootstrap down, to simplify the code and configuration, and to make startup more reliable, so any changes that we make now will have to be carefully considered.

Could you be more specific about what you need changed and why? (and I assume you're referring to 2.0?)

**Comment by nickminutello** [comment]
I'm looking at master.

More specifically:
- make Bootstrap class public
- have a method called, say, prepare() which calls initializeNatives(), initializeProbes(), JarHell.checkJarHell(), JVMCheck.check(), clientJvmWarning()**, 
- setup() then just has to call prepare().
- all the startup/init/validation in 1 place.
- but also, those running elastic embedded, can perform the same.





\** this method doesnt exist - but its the if case checking if running in the client vm.

**Comment by clintongormley** [comment]
thanks @nickminutello

**Comment by s1monw** [comment]
> Currently we don't test embedded Elasticsearch at all, which means that it is not a supported configuration.

this is actually not true. We test that all over the place. Embedded ES doesn't have Boostrap as it's entry point. If you want to embed ES you should use `NodeBuilder.java` and start from there. Every Integration we run against `InternalTestCluster` test is basically embedding Elasticsearch an it works just fine without opening up bootstrap. Bootstrap should be private as much as possible it's basically our main method.

**Comment by rjernst** [comment]
@nickminutello Bootstrap is an internal implementation detail, and using it was never officially supported. As Clint mentioned, we don't (officially) test or support running Elasticsearch embedded. Can you elaborate on *why* you need to run it embedded? Is it to run node client? Are you running a single node standalone? Something else?
