### ISSUE TITLE
Generate list of built-in  plugins

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#13096]
we maintain a list of build-in plugins in multiple places like in the PluginsManager as well as in the `qa/smoke-test-plugins` project. We will soon add a third after #13078 is merged. We should try to generate it somehow from our build files.

**Comment by nik9000** [comment]
`qa/vagrant/pom.xml` has a list too. Sadly I don't think there is much we can do about automating the list in maven. @rjernst this is probably more fuel for the burn maven with fire movement.

**Comment by rjernst** [comment]
The static list of plugins has already been removed from the plugin installer a while ago, as well as from the build. The only remaining place is in the smoke tester, so there is one last cleanup needed for this issue.
