### ISSUE TITLE
"hostname -s" not available in at least Solaris 10

### ISSUE THREAD

**Issue by TwizzyDizzy** [elastic/elasticsearch#13107]
Hi folks,

I just encountered an issue with elasticsearch 1.7.1. I tried to upgrade from ES 1.4.4 to 1.7.1.

ES does run as unprivileged user.

Error output while starting:

> bin/elasticsearch: HOSTNAME=: is not an identifier

It seems that in contrast to 1.4.4 there is line 151 of

> elasticsearch-1.7.1/bin/elasticsearch

which tries to export the environment variable "HOSTNAME". The value is assigned via "hostname -s" which is not available in Solaris.

This feature seems to have been introduced in #8470. Since I have defined my node name via "node.name" this is not quite an issue with exporting the HOSTNAME variable but rather with the switch that is not supported on Solaris.

And yes. I apologize for still being forced to use Solaris, but that's the way it is ;)

Cheers
Thomas

**Comment by clintongormley** [comment]
Hi @TwizzyDizzy 

Any ideas what we could use instead on Solaris?

**Comment by nik9000** [comment]
Looks like we have a working patch so I removed feedback_needed. Then I thought better of it. @TwizzyDizzy, can you try `hostname | cut -d. -f1` on a solaris 10 box?

**Comment by TwizzyDizzy** [comment]
Hi @nik9000,

thanks for getting back to me that fast!

> hostname | cut -d. -f1

This should totally work, but let me check it at work tomorrow to be totally sure. I somehow remember some glitches with either the delimiter or the field number, when it comes to the exact syntax.

Will get back to you tomorrow :)

Cheers
Thomas

**Comment by jasontedor** [comment]
@TwizzyDizzy I've tested Elasticsearch with `hostname | cut -d. -f1` on a Solaris VM. You should be able to get by with replacing `hostname -s` with `hostname | cut -d. -f1` in the `elasticsearch` and `plugin` scripts in the `bin` subfolder of the Elasticsearch home. I've opened #13109 to get this into mainline.

**Comment by TwizzyDizzy** [comment]
Ah well, if you've tested it in a VM then I guess it's fine.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
Just for the full picture: the

> | cut -d. -f1

part works on my machine, too.

Cheers
Thomas

**Comment by nik9000** [comment]
> part works on my machine, too.

Thanks!
