### ISSUE TITLE
Prompted for 'tFormat' username when attempting to remove node from cluster

### ISSUE THREAD

**Issue by tomharrisonJG** [elastic/elasticsearch#13105]
Hi

I'm trying to remove a node from our cluster and have tried running the following curl command via windows powershell with curl installed.

      curl  -XPUT http://localhost:9200/_cluster/settings -d { 
           \"transient\":
        { \"cluster.routing.allocation.exclude._ip\":\"10.50.14.120\" }
    }

I run the command and then get 'Enter host password for user 'tFormat':

This isn't a user that has been setup by us so I'm not sure what this relates to?

Thanks

**Comment by clintongormley** [comment]
This isn't anything that we have in Elasticsearch. Either you have some proxy in front of Elasticsearch, or if you're using Shield then I'd suggest contacting your support team.
