### ISSUE TITLE
Allow validating that settings update doesn't produce invalid combinations

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#13103]
User can change their (dynamically updatable) cluster settings through the cluster settings API. To make sure the new settings make sense, we have an internal validation infra structure that can reject illegal values (for example, a negative value where a positive is expected). However, the current infrastructure only allows you to validate each entry of the new settings (in the context of the current cluster state) but doesn't not allow to validate it with respect to other settings in the update.

For example, say we have two settings `a` and `b` and we have the requirement that `a` is always smaller than `b` - we currently have now wait of making this request fail:

```
PUT _cluster/settings
{
  "persistent": {
    "a": 5,
    "b": 3
  }
}
```

**Comment by clintongormley** [comment]
@bleskes Do you have a concrete example of this?  Is there more to do here than has been done with the recent settings rewrite?

**Comment by bleskes** [comment]
Sadly I don't remember exactly anymore. Examples I can come up with now (though i wish I had a better one) is the commit_timeout (how long to wait for nodes to respond for the intial sending of a cluster state change) which has to be less than publishing timeout (total time for nodes to respond to both the initial send and the commit phase).  I'm sure there are better more concrete ones. 

The new infra does allow you to do this but it's non trivial at all. In the old system it was  easier (because we didn't have many of the rigorous checks and infra we have now) so I think it's an easy win. I'm going to close this for now. We can re-evaluate it when we need this.
