### ISSUE TITLE
Enable MLock By Default

### ISSUE THREAD

**Issue by gingerwizard** [elastic/elasticsearch#13116]
Ticket proposing having bootstrap.mlockall: true in the default configuration distributed with Elasticsearch.  Recommended setting for most production installations.

**Comment by clintongormley** [comment]
I don't think we should do this by default, as there are a couple of problems:

1. The ulimit needs to be set by the user to allow Elasticsearch to mlockall, which *could* be done in the RPM/deb but not in tar.gz/zip
2. We can easily cause an OOM on a box if we lock memory when the user is not expecting it.

**Comment by clintongormley** [comment]
Discussed in FixItFriday.  Setting mlockall by default when a user isn't expecting it could be dangerous.  Rather let them configure it, along with the heap size etc
