### ISSUE TITLE
Please add alias creation for snapshot _restore API

### ISSUE THREAD

**Issue by mkliu** [elastic/elasticsearch#13110]
The most frequent scenario for using _restore API is when something is wrong, and index needs to be restored. But in order to restore, we need to delete the old index.

What happens in most cases is the original index is
1. Old index in red state.
2. Old index was wiped out, data is repopulated and an index is created with the same name.

In this case, especially #2, it's actually not OK to delete the index as data will get lost. So what we normally do is restore to a different name and setup an alias with the original index name pointing to the newly restored index.

When we are restoring lots of indices, this is tedious and error prone. I propose to add a alias field for the _restore API, like below:

```
POST /_snapshot/my_backup/snapshot_1/_restore
{
    "indices": "index_1", 
    "rename_pattern": "index_(.+)", 
    "rename_replacement": "restored_index_$1",
    "alias": "$1"            <=== 
}
```

**Comment by clintongormley** [comment]
You can't create an alias with the same name as an index, so (if i understand scenario 2 above) you wouldn't be able to use the data from index `foo` plus the data from index `restored_index_foo` via an alias called `foo`.

Instead, you should **always** use aliases to point to the real index name.  That way you can restore your index and update the alias to point to both indices (and not have to change your application).  Of course, that is only one thing you may want to do.  You may also want to update the alias to point to just the restored index.

As soon as there are a number of paths to choose (different people will want to do different things at different times) then the number of options you have to add to support these use cases multiplies and becomes confusing.  

We have APIs to manage aliases which already provide the tools to support all the use cases.  It is pretty easy to write a script to suit your exact use case, certainly easier than trying to add a range of parameters to the snapshot/restore API.

For this reason I'm -1 on adding this.

**Comment by dadoonet** [comment]
Hi,

We discussed this today during our fixit friday meetup and this is something we won't support in elasticsearch itself.
You should always check if your index have been restored correctly before switching an alias.

If you are using curator, may be this is a feature which can be supported there?
