### ISSUE TITLE
Move from oss-parent to nexus-staging-maven-plugin

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#13120]
According to sonatype's [docs](http://central.sonatype.org/pages/apache-maven.html#deprecated-oss-parent) the oss-parent module is deprecated and they recommend you use nexus-staging-maven-plugin as documented on that page.

**Comment by nik9000** [comment]
@rjernst - there are [docs](http://central.sonatype.org/pages/gradle.html) for Gradle too. Just in case. You know.

**Comment by dadoonet** [comment]
++ i was not aware of that. Thanks Nik!

**Comment by nik9000** [comment]
> ++ i was not aware of that. Thanks Nik!

I wasn't either until this morning. It should be reasonably simple to do for anyone that is used to maven's maven-ness. You'll need access to sonatype's elasticsearch oss repository to test this though.

**Comment by nik9000** [comment]
Bumping to 2.1.0 - this isn't really important for releasing 2.0.0.

**Comment by clintongormley** [comment]
@rjernst can this be closed?

**Comment by nik9000** [comment]
We don't need either one in master. Closing.
