### ISSUE TITLE
How to building rpm  package for elasticsearch?

### ISSUE THREAD

**Issue by lygstate** [elastic/elasticsearch#13126]
I want to building my own rpm package for elasticsearch

**Comment by jasontedor** [comment]
@lygstate Only in case you are not aware [Elastic](https://www.elastic.co) does provide [repositories](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html#_yum) with prebuilt RPMs.

If that's not sufficient, do you want to build off of master, or some other branch of the elasticsearch source code repository?

**Comment by jpountz** [comment]
Closing as this is not an issue report.

**Comment by lygstate** [comment]
@jasontedor I wanna to building from the 2.0-beta1 branch, and I want to building it by my own.

**Comment by MaineC** [comment]
YMMV depending on the distribution you use. As a starting point I'd suggest reading the RPM HowTo of the Linux documentation project:

http://www.tldp.org/HOWTO/RPM-HOWTO/build.html 

Also the tool "alien" might help you with converting between rpm/tar/tar.gz formats.
