### ISSUE TITLE
Match phrase prefix query seems to ignore boost value.

### ISSUE THREAD

**Issue by mohittt8** [elastic/elasticsearch#13129]
There seems to be no effect on score on changing boost value on match_phrase_prefix query. 

My query is:
<pre><code> "query": {
        "bool": {
            "should": [
                {"match_phrase_prefix": {
                        "firstName": {
                            "query": "is", 
							"boost":2.0
                        }
                    }} ,
                    {"match_phrase_prefix": {
                        "userName.raw": {
                            "query": "Tiv", 
							"boost":4.0
                        }
                    }}
              ]
        }
    }</pre></code>

I am trying this on Elasticsearch-1.7

**Comment by clintongormley** [comment]
Boost does seem to be ignored by the match_phrase_prefix query:

    PUT t/t/1
    {
      "one": "foo",
      "two": "bar"
    }
    
    GET t/_search?explain
    {
      "query": {
        "bool": {
          "should": [
            {
              "match": {
                "one": {
                  "query": "foo",
                  "boost": 5
                }
              }
            },
            {
              "match_phrase_prefix": {
                "two": {
                  "query": "bar",
                  "boost": 50
                }
              }
            }
          ]
        }
      }
    }

**Comment by clintongormley** [comment]
This is also broken in master
