### ISSUE TITLE
deb package should register elasticsearch to start on restart

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#13123]
The default for DEB packages is to register the thing they install to start on restart. Elasticsearch should do that too.

**Comment by nik9000** [comment]
@clintongormley I'm not 100% sure this is new.

**Comment by nik9000** [comment]
> @clintongormley I'm not 100% sure this is new.

Ok - it is new. 1.7.1 doesn't auto start on restart. You have to add it to the runlevels yourself. The [reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html) even tells you how.

I've added the discuss label. It seems like for the most part deb packaged start their services on install but that isn't a super popular thing. Some packages don't do it and some people hate it when packages do that. I suspect the registration thing is similar.

**Comment by jasontedor** [comment]
I do not think that we should do this. It has the potential to expose un-configured or misconfigured instances of Elasticsearch. We provide the [instructions](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-service.html#_debian_ubuntu) in our setup page and that should be sufficient for those that are ready to configure this.

**Comment by clintongormley** [comment]
I'm with @jasontedor here - I don't think we should make ES autostart ourselves.  Up to the user.

**Comment by nik9000** [comment]
> I'm with @jasontedor here - I don't think we should make ES autostart ourselves. Up to the user.

I'm honestly with him too. I see that things like postgresql and mysql start on install and register themselves to start on restart and I wrinkle my nose. Apparently this is debian policy though. I can't find where in the [policy](https://www.debian.org/doc/debian-policy/) it says that but the internet seems to think its in there somewhere.

I'm fine with saying "We've thought this through. We know we're going against debian policy but we think this should be up to the installer to make the decision about when and if Elasticsearch should start after its installed."

**Comment by clintongormley** [comment]
Discussed in FixItFriday. Agreed that we shouldn't touch the run levels.
