### ISSUE TITLE
RPM build is broken and should be better tested

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#13138]
in the past we had so many problems with RPM and it building, testing verification etc. You have to have a specific OS to even build a valid package (at least that was the case but who knows until you install it) The maven task claims to sign the RPM but doesn't and `rpm -K` happily passes if the package is unsigned. To work around this we have to sign the rpm after the fact with some cryptic rpm command where I feel not happy with since it modifies the actual already build package that comes out of our mvn build. This means all the `.asc .md5 .sha1 `we produce in the build are useless and broken. 
We don't have tests for this package that run on a regular basis neither do we tests it on release.  This should either be fully tested like our tar and gz file and the signing must work out of the box or this format must go away. I don't care how many people would like to have it or not, it's untested and I rather ship nothing than an untested package.

**Comment by markwalkom** [comment]
We can't not offer RPM....

**Comment by electrical** [comment]
I tried out the rpm signing process and still works.
Will have to check how the release script is being called and if all required arguments are being passed.

**Comment by electrical** [comment]
The pre-release script sets `-Dgpg.keyname="%s"` which should be `-Dgpg.key="%s"`
because of this the signing didn't happen..

**Comment by electrical** [comment]
deb package is not signed either so will have to fix that as well. will update when i found all params / commands.

**Comment by s1monw** [comment]
folks this is too cumbersome I hate to say it but fixing the arguments is not fixing the problem it's just continuing to fool around.

**Comment by s1monw** [comment]
@electrical I wonder why it's `gpg.key` their documentation states otherwise: http://www.mojohaus.org/rpm-maven-plugin/adv-params.html

**Comment by electrical** [comment]
@s1monw `<keyname>${gpg.key}</keyname>`
this made me try out -Dgpg.key and works.

**Comment by electrical** [comment]
I was able to build rpm and deb packages signed and well with the following options:

`-Drpm.sign=true -Ddeb.sign=true -Dgpg.passphrase=password -Dgpg.key=key`

**Comment by electrical** [comment]
Validation commands:

RPM:
```
$ rpm -K ./distribution/rpm/target/releases/elasticsearch-2.1.0-SNAPSHOT.rpm
./distribution/rpm/target/releases/elasticsearch-2.1.0-SNAPSHOT.rpm: rsa sha1 (md5) pgp md5 OK
```

DEB:
```
$ dpkg-sig -c elasticsearch-2.0.0-beta1.deb
Processing elasticsearch-2.0.0-beta1.deb...
GOODSIG _gpgbuilder 46095ACC8548582C1A2699A9D27D666CD88E42B4 1440670973
```

**Comment by electrical** [comment]
Forgot to mention 1 thing. we also need to add the following to the `deb/pom.xml` at the signing part:

`<signRole>builder</signRole>`

**Comment by nik9000** [comment]
Not offering RPM or DEB packages would be a blow for adoption. I might not be here if it weren't for the deb package and from what I can tell these packages are widely used.

I'm with that its certainly a pain to build them though.

> We don't have tests for this package that run on a regular basis neither do we tests it on release.

Because no one has turned on the vagrant tests in Jenkins.... They are there and test the rpm but I don't think they'd check the gpg signing. We could certainly test against some self signed stuff.

> You have to have a specific OS to even build a valid package

We could work around that with vagrant if we really really wanted to. Right now you need either OSX via homebrew or Linux with rpmbuild installed. Certainly Centos/Fedora/RHEL/OEL would do there. There seem to be rpmbuild packages for Debian and Ubuntu but I don't know that they would work. They might.

**Comment by s1monw** [comment]
Let me clarify I do want to ship RPM and .deb but  the current state of affairs is not even near good. If we have test but they don't run and they apparently didn't even run on a RC then the are not an improvement in this situations. @electrical your comments regarding the commands are not fixing the issue. I had these commands ready as well but thanks anyway. I feel like the current state of these packages are not what I want folks to run in production. If we don't have tests that we run with realistic builds they we have to consider the packages broken. I don't want to ship any broken packages. Nobody should feel like I am finger-pointing since this is not the case at all. I do care about those packages a lot that's why I open these drastic packages.

> We can't not offer RPM....

this is just wrong. We can't offer potentially broken RPM... and I will not offer RPM if they are potentially broken. This must be rock solid but it isn't, we can't rely on manual testing here. Hence the blocker.

**Comment by nik9000** [comment]
I'm going to try to enumerate the issues so we can fix them:

1. We don't run the rpm and deb tests consistently. I've opened an issue with the Elastic infrastructure folks for this. And made sure its obvious that I consider it an important issue.
2. The deb/rpm tests don't cover artifact signing.
3. Artifact signing with maven is jangly and doesn't actually work properly right now.

Is that all?

**Comment by dhollinger** [comment]
@s1monw , while you are right in that you shouldn't offer broken packages, I can definitely tell you there are multiple organizations I have had involvement with that wouldn't even consider Elasticsearch if there are packages that can be installed and tracked using a package management system such as YUM or APT. 

Tracking installed software tends to be an audit requirement in many (but not all) organizations.

Not offering a broken RPM is great, not offering one at all would be unacceptable.

**Comment by s1monw** [comment]
@dhollinger I think you are not getting it right here at all I am sorry

> Not offering a broken RPM is great, not offering one at all would be unacceptable.

if you get something that wipes your entire data because we shipped it just for the sake of it I'd be very unhappy. I am listening to all the rants and dangerous statements here until this is either removed or properly tested then we can release again. This is the mindset we have to live to ship good software either it's tested or we don't ship it. Since this is RPM and .deb I am even more concerned for the reasons you mentioned. But it's black and white sorry! IF we can't fix it I will remove it myself.

**Comment by s1monw** [comment]
@nik9000 I think we should add to the list:
 - tests and/or release scripts must verify that packages are signed and fail if not.
 - test must verify that packages are cleanly un-installable
 - test must verify that packages can be upgraded from a previous version including the index if it already exists. (don't wipe any data)
 - test must verify that packages load all relevant user provided configurations 

not sure how much of this we already do but I think that would be a good start?

**Comment by nik9000** [comment]
[ ]  tests and/or release scripts must verify that packages are signed and fail if not. #13182
[x] test must verify that packages are cleanly un-installable - already done
[ ] test must verify that packages can be upgraded from a previous version including the index if it already exists. (don't wipe any data) #13183

**Comment by nik9000** [comment]
> test must verify that packages load all relevant user provided configurations

You mean like the user can modify /etc/elasticsearch/elasticsearch.yml and /etc/defaults/elasticsearch and things happen? They already do some of that.

**Comment by s1monw** [comment]
> You mean like the user can modify /etc/elasticsearch/elasticsearch.yml and /etc/defaults/elasticsearch and things happen? They already do some of that.

yeah pretty much - like provide a template / script on the FS and it's loaded ie. all paths are configured correctly.

**Comment by nik9000** [comment]
[ ] provide a template / script on the FS and it's loaded ie. all paths are configured correctly. #13184

**Comment by nik9000** [comment]
I believe all that is missing here is one final review on testing the signatures (#13354). I got a LGTM on it but it didn't merge cleanly with master and required some help so I'd like one more look there. Once that is in I'll feel much better about the RPM and deb builds.

**Comment by nik9000** [comment]
Ok - this is done except for #13354 which I think might have to be pushed to 2.1/2.0.1 or something. I'm going to close this and @s1monw can reopen if he feels strongly about it.
