### ISSUE TITLE
Add support for ICUTokenizerFactory and customizing the rule file in ICU tokenizer

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13146]
_From @rslinckx on October 21, 2014 10:35_

There has been a commit in lucene (http://svn.apache.org/viewvc?view=revision&revision=1416629) that adds a ICUTokenizerFactory which allows to create a ICUTokenizer with a special config argument enabling the customization of the rule based iterator by providing a custom rules files.

Is it possible to expose that argument in the elasticsearch icu plugin ? This would allow to define an elasticsearch tokenizer like:

    {
        "index" : {
            "analysis" : {
                "tokenizer" : {
                    "custom-icu-tokenizer" : {
                        "type" : "icu_tokenizer",
                        "rulefiles": "Latn:Latin-break-only-on-whitespace.rbbi"
                    }
                }
            }
        }
    }

This allows tailoring the output of the tokenization process (in this example, not splitting on hyphens in the latin script)

Also see the original solr discussion here: https://issues.apache.org/jira/browse/SOLR-4123

_Copied from original issue: elastic/elasticsearch-analysis-icu#42_

**Comment by dadoonet** [comment]
_From @d-claassen on August 27, 2015 11:32_

Is there any progress on this? This could also help us with keywords like c++, c# and R&D. With the current tokenizer, all these special characters are being removed.

**Comment by xuzha** [comment]
I put a PR for this.
I copied two RBBI files and borrowed a test cases from Lucene for testing, I'm not sure if this is appropriate.
