### ISSUE TITLE
Expose ICUCollationKeyAnalyzer

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13149]
_From @clintongormley on May 7, 2014 15:12_

The `icu_collation` filter is deprecated, and should be replaced by the ICUCollationKeyAnalyzer (exposed as the `icu_collation_key` analyzer).   However, I would recommend making some changes at the same time:

Use `locale` instead of `language`/ `country`/ `variant`, eg : 
- `en`
- `en_US`
- `de_DE@collation=phonebook`
- `zh_CN@collation=pinyin`

Keep `strength`, `rules`, `decomposition`, `alternate`, `case_level`, `case_first`, `numeric`, `variable_top`.

It looks like `hiraganaQuaternaryMode` is no longer used by ICU (but not sure about that)

If no locale is specified, then it should default to ULocale.ROOT (ie DUCET) rather than what it does currently, which is to default to the current locale active in the JVM.

Finally, it would be good to add the `truncate` token filter into the analyzer so that users can truncate a potentially long original string into (eg) the first 10 characters, so that it uses less memory.

NOTE: We need to check that binary sorting is supported correctly in Elasticsearch.  @jpountz thinks this is the case, but needs to be confirmed.

_Copied from original issue: elastic/elasticsearch-analysis-icu#28_

**Comment by dadoonet** [comment]
_From @clintongormley on May 7, 2014 15:45_

There is an issue with binary sort values. See http://github.com/elasticsearch/elasticsearch/issues/6077

**Comment by GlenRSmith** [comment]
@dadoonet @clintongormley Is this addressed with the release of ICU Collation Keyword Fields in v5.5.0?

**Comment by jpountz** [comment]
@GlenRSmith It is! Closing. For reference, https://github.com/elastic/elasticsearch/pull/24126 is the PR that introduced the ICU collation keyword fields.

However this issue had some good points, and I opened https://github.com/elastic/elasticsearch/issues/25587 to address the default locale issue.
