### ISSUE TITLE
Add icu_collation field type

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13148]
_From @clintongormley on May 7, 2014 15:40_

Collation fields are used just for sorting - they don't need to be indexed or stored.  

We can use a new `icu_collation_key` field type which accepts the same parameters as the ICUCollationKeyAnalyzer, and isn't indexed but stores its values as doc values, using  ICUCollationDocValuesField.

This field type would need to serialize its sort keys as base64 for inclusion in the JSON response.

_Copied from original issue: elastic/elasticsearch-analysis-icu#29_

**Comment by dadoonet** [comment]
_From @clintongormley on May 10, 2014 13:45_

Also, should throw an error if the named collation is not found.  Currently this is unchecked:

> If the search fails because no such key is present in any of ICU's locale data (e.g., "de@collation=funky"), the service returns a collator implementing UCA and the return UErrorCode is U_USING_DEFAULT_WARNING.

**Comment by dadoonet** [comment]
See also #6077

**Comment by mattweber** [comment]
Please close.

Closed via #24126.
