### ISSUE TITLE
migration_x_x.asciidoc never merges cleanly

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#13143]
I get lots of version conflicts around files like migration_x_x.asciidoc. It seems like this comes from people constantly tacking new things on the end. Could we, maybe, build this file by cating together a directory of scripts or something like that? Something where git is going to be able to merge easily.

**Comment by clintongormley** [comment]
I've just spent a long time rewriting the 2.0 migration docs and breaking them up into separate pages, see https://github.com/elastic/elasticsearch/tree/master/docs/reference/migration/migrate_2_0

This change may account for the conflicts, but it should make conflicts less likely in the future.

The migration docs need to be as readable as any other page in the docs, I really don't want some long disorganised list (which is pretty much what it was before the reorganisation).

**Comment by nik9000** [comment]
> The migration docs need to be as readable as any other page in the docs, I really don't want some long disorganised list (which is pretty much what it was before the reorganisation).

Yeah. I get that. I just find that whenever I have a pull request that's been sitting around for more than a few days it merges cleanly _except_ for migration_2_0 or migration_2_1. I remember you're work to move the change into multiple docs and it helped. But I'm seeing it again with 2.1. I'll poke this with a concrete example if it happens again.

**Comment by clintongormley** [comment]
Not always possible but perhaps adding the breaking change into a particular section, instead of just appending, will make conflicts less likely
