### ISSUE TITLE
ICU backwards compatibility

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13147]
_From @clintongormley on May 10, 2014 13:50_

Currently, if ICU changes, it could mean needing to reindex all your data.  The ICU docs have this to say:

Versioning

Sort keys are often stored on disk for later reuse. A common example is the use of keys to build indexes in databases. When comparing keys, it is important to know that both keys were generated by the same algorithms and weightings. Otherwise, identical strings with keys generated on two different dates, for example, might compare as unequal. Sort keys can be affected by new versions of ICU or its data tables, new sort key formats, or changes to the Collator. Starting with release 1.8.1, ICU provides a versioning mechanism to identify the version information of the following (but not limited to),

* The run-time executable
* The collation element content
* The Unicode/UCA database
* The tailoring table

The version information of Collator is a 32-bit integer. If a new version of ICU has changes affecting the content of collation elements, the version information will be changed. In that case, to use the new version of ICU collator will require regenerating any saved or stored sort keys. However, since ICU 1.8.1. it is possible to build your program so that it uses more than one version of ICU. Therefore, you could use the current version for the features you need and use the older version for collation.

_Copied from original issue: elastic/elasticsearch-analysis-icu#30_

**Comment by clintongormley** [comment]
The right solution here is to reindex your data.  Closing
