### ISSUE TITLE
2.0 java api changes

### ISSUE THREAD

**Issue by brackxm** [elastic/elasticsearch#13151]
Some not yet documented java api changes.

GetAliasesResponse.getAliases().keysIt() returns a guava UnmodifiableIterator iso a elasticsearch one

ImmutableSettings removed; use Settings.builder() iso ImmutableSettings.builder()

InetSocketTransportAddress(String, int) removed

**Comment by tarunsapra** [comment]
+1

**Comment by clintongormley** [comment]
@dadoonet could you add these to the java API docs and migration docs please?
