### ISSUE TITLE
2.0.beta1 - Exception "path.home is not configured" when starting ES in transport and client mode

### ISSUE THREAD

**Issue by stephane-bastian** [elastic/elasticsearch#13155]
Hi,
I just installed the new beta version 2.0.0-beta1 and ran some code that used to work with ES 1.7.0. 
I got an exception where it complained that "path.home is not configured". 
Is this something new? Why would I need to configure anything beside the cluster name in transport mode?

Thanks

```
Exception in thread "main" java.lang.IllegalStateException: path.home is not configured
	at org.elasticsearch.env.Environment.<init>(Environment.java:99)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareSettings(InternalSettingsPreparer.java:97)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareSettings(InternalSettingsPreparer.java:70)
	at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:114)
	at com.thesoftwarefactory.persistence.elasticsearch.DataConnection.open(DataConnection.java:62)
```

**Comment by clintongormley** [comment]
Discussed this on FixItFriday.  The client node is a real node, and should require everything that any other node requires.  (Need to add docs for this).

The transport client should be light weight and shouldn't require any config etc.  So let's not require path.home for the transport client, and not load any config by default.  If the user needs to load a config file, then that should be explicitly specified.

**Comment by bleskes** [comment]
as a temporary work around, if you are using the transport client, you can turn off config file loading by calling `TransportClient.Builder#loadConfigSettings(false)`

**Comment by bleskes** [comment]
bleh, it turns out I was wrong. Disabling loading the config settings still results in the exception (we throw it before checking the settings). Sorry for the noise.

**Comment by Andy-Peng** [comment]
service.bat also have the same problem.

**Comment by kimchy** [comment]
I chatted to @rjernst about it a bit, and he suggested something that I agree with. In the case of `TransportClient`, we can simply not bind or handle `Environment`. I like the simplicity of this approach, but we need to double check with our plugins to make sure that the ones that make sense in the context of a transport client will still work (/cc @jaymode).

There is a whole other question around Node(Client), but we should open a different issue where we properly define how things should work when "embedding"  a Node.

**Comment by kimchy** [comment]
@Andy-Peng service.bat should work unrelated to TransportClient, can you open a new issue with what fails for you in this context?

**Comment by rmuir** [comment]
service.bat problems might be related to https://github.com/elastic/elasticsearch/issues/13247

**Comment by Andy-Peng** [comment]
Sorry, I made a mistake.

**Comment by clintongormley** [comment]
@rjernst are you working on this?

**Comment by rjernst** [comment]
@clintongormley I just opened a PR for this: #13383

**Comment by jaskmar** [comment]
Is there any work around for this bug for now?

**Comment by sweetest** [comment]
I'm still seeing this with elasticsearch 2.0.0, Mac OS Yosemite.

maven dependency 

        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>2.0.0</version>
            <scope>compile</scope>
        </dependency>

code that triggers error

        node = NodeBuilder.nodeBuilder().data(true).settings(
                Settings.builder()
                        .put(ClusterName.SETTING, "test")
                        .put(IndexMetaData.SETTING_NUMBER_OF_SHARDS, 1)
                        .put(IndexMetaData.SETTING_NUMBER_OF_REPLICAS, 0)
                        .put(EsExecutors.PROCESSORS, 1)
                        .put("index.store.type", "memory")
        ).build();

error stack trace

    java.lang.IllegalStateException: path.home is not configured
	at org.elasticsearch.env.Environment.<init>(Environment.java:99)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:82)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)

**Comment by rjernst** [comment]
@sweetest That is expected since you are starting a node. The PR that closed this removed the need for `path.home` to be specified for `TransportClient`s. But any node needs to have `path.home`.

**Comment by jasontedor** [comment]
> `NodeBuilder.nodeBuilder().data(true)`

That's not building a client node, that's building a data node for which `path.home` *must* be configured (how else will the node where to put its data).

**Comment by jtal** [comment]
> how else will the node know where to put its data?
Doesnt it just use path.data to know where to put the data? 

How does one set path.home? When I google it I just find this thread and the directory layout docs.

Also, I am trying to create a client node and get the same error.

```Java
nodeBuilder()
.settings(Settings.settingsBuilder().put("http.enabled", false))
.client(true)
.node();
```

**Comment by jasontedor** [comment]
> Doesnt it just use path.data to know where to put the data?

Yes, and by default that is `${path.home}/data`.

> Also, I am trying to create a client node and get the same error.

Are you sure that you're using the released version of Elasticsearch 2.0.0?

**Comment by hudsonb** [comment]
I am having the same issue when creating a Node(Client):

```
NodeBuilder.nodeBuilder()
                    .settings(Settings.builder()
                                      .put("discovery.zen.ping.multicase.enabled")
                                      .put("discovery.zen.ping.unicast.hosts", hosts)
                                      .put("cluster.name", cluster)
                                      .put("node.name", nodeName)
                    .client(true)
                    .node();
```

Results in "path.home is not configured"

**Comment by rjernst** [comment]
Adding `path.home` when building a node would be done like this:
```
NodeBuilder.nodeBuilder()
    .settings(Settings.builder()
        .put("path.home", "/path/to/home/dir")
    .node();
```

**Comment by jtal** [comment]
Yes I'm fairly sure but is there a way I can have the client report what version it is from within the app?

Also, looking at the 2.0.0 source code constructor for Node (line 128) this happens:

        Environment tmpEnv = InternalSettingsPreparer.prepareEnvironment(pSettings, null);

Then Environment constructor requires path.home (line 96):

        if (settings.get("path.home") != null) {
            homeFile = PathUtils.get(cleanPath(settings.get("path.home")));
        } else {
            throw new IllegalStateException("path.home is not configured");
        }

Am I still misunderstanding something? If not, what should I set path.home to when I'm not storing data and how does one set path.home since its not in the client node doc example.

 https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/node-client.html

Thank you.

Server:
```
10:01:27-jtal~/pkg/elasticsearch-2.0.0$ ps aux | grep elasticsearch
jtal 18858  0.0  0.0  15940   944 pts/7    S+   10:01   0:00 grep --color=auto elasticsearch
jtal 20994  0.5  1.0 6751776 340708 pts/10 Sl   Nov05   8:13 /home/jtal/pkg/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Djna.nosys=true -Des.path.home=/home/jtal/pkg/elasticsearch-2.0.0 -cp /home/jtal/pkg/elasticsearch-2.0.0/lib/elasticsearch-2.0.0.jar:/home/jtal/pkg/elasticsearch-2.0.0/lib/* org.elasticsearch.bootstrap.Elasticsearch start -d

10:01:36-jtal~/pkg/elasticsearch-2.0.0$ sha1sum ~/pkg/elasticsearch-2.0.0.zip
13255b26a4d47d557a69fc85c24c117a1d9a33a5  /home/jtal/pkg/elasticsearch-2.0.0.zip
```

Client:
```
libraryDependencies ++= Seq(
  javaJdbc,
  javaEbean,
  cache,
  javaWs,
  "org.pac4j" % "play-pac4j_java" % "1.3.0",
  "org.pac4j" % "pac4j-cas" % "1.7.0",
  "org.elasticsearch" % "elasticsearch" % "2.0.0"
)
```

**Comment by dadoonet** [comment]
Yes the doc needs to be fix.

**Comment by rjernst** [comment]
> what should I set path.home to when I'm not storing data

Set it to any directory. If you are explicitly setting other dirs like path.logs, then nothing should be written to it.

**Comment by hrahal** [comment]
`sudo chown -R elasticsearch:elasticsearch /var/lib/elasticsearch/`

worked for me on ES 2.0.0

**Comment by zy840055899** [comment]
唉，还是没解决~

**Comment by jeyendranbalakrishnan** [comment]
Is there any fix for this? I am using the release version of elasticsearch 2.0.0 on my laptop, both for the running es server, and for the dependency in my source code where I use es as a client.
I set 
path.home: ${ES_HOME}
in my src/main/resources/elasticsearch.yml config file, and set 
ES_HOME=/path/to/my/es/install
in my environment. 
But running my client code on the laptop still gives the same "path.home is not configured" exception.
Funnily. I don't have a path.home setting in my running server config file (${ES_HOME}/config/elasticsearch.yml.
However, this does not prevent the server from starting up and running properly, responding correctly to curl commands.

**Comment by selfchanger** [comment]
path.home is not configured
i also have this problem,for details see https://github.com/elastic/elasticsearch/issues/15660
can someone help me?

**Comment by vinctzhang** [comment]
I am new to ES, and I also faced this problem, any suggested solutions?

**Comment by zy840055899** [comment]
use the 1.7.3 version.

**Comment by zy840055899** [comment]
use the 1.7.3 version,i know this solution is not the best .

**Comment by selfchanger** [comment]
solution:
add "-Des.path.home=D:\\elasticsearch-2.1.0" in your VM options,
see http://blog.csdn.net/jianjun200607/article/details/49821813#reply
