### ISSUE TITLE
[doc] Stempel: no information how to reimplement the analyzer

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13150]
_From @merito on June 11, 2015 8:16_

Hi,

I would like to reimplement the analyzer, for example add my synonyms, but there is no available filter list, for official language analyzers you can find it here - [elastic documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#english-analyzer). Could you add this to the docs?

_Copied from original issue: elastic/elasticsearch-analysis-stempel#43_

**Comment by dadoonet** [comment]
_From @mod3st on June 17, 2015 14:55_

+1

**Comment by dadoonet** [comment]
_From @jeanbelhache on July 16, 2015 7:42_

+1

**Comment by romseygeek** [comment]
cc @elastic/es-search-aggs
