### ISSUE TITLE
[doc] provide more examples for smartcn analysis

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13152]
_From @twn39 on August 14, 2015 8:14_

Hi, I'm from china, and recently learning the elasticsearch, but I found it's hard to configure the smartcn analysis.I google this but find little documents. Could you help me or give me some documents, thank you very much.

_Copied from original issue: elastic/elasticsearch-analysis-smartcn#44_

**Comment by dadoonet** [comment]
I agree we should add more doc. in the meantime, you can read this https://github.com/elastic/elasticsearch-analysis-kuromoji

**Comment by dadoonet** [comment]
_From @twn39 on August 14, 2015 12:23_

thanks

**Comment by romseygeek** [comment]
cc @elastic/es-search-aggs
