### ISSUE TITLE
_cat should not default to verbose

### ISSUE THREAD

**Issue by grantr** [elastic/elasticsearch#13156]
https://github.com/elastic/elasticsearch/pull/8927 changed _cat apis to be verbose by default in ES 2.0, based on motivation from https://github.com/elastic/elasticsearch/issues/8922.

The motivation for the change was easing the cluster state inspection experience for users unfamiliar with the command line and ES docs. A noble goal. I certainly empathize with these users.

The opposition argued that experience is quickly gained, and experienced users want the non-verbose behavior, such that over time the majority of users will become frustrated with the new, verbose default.

Despite my empathy for new users, I 100% agree with the opposition. I'd also like to point out that this is an api specifically designed for scripting (see its [introduction](https://www.elastic.co/blog/introducing-cat-api)) and every script that uses it will break in unpredictable ways when the behavior changes. Changing the default will generate a lot of unpleasant work and delay upgrades to 2.0.

The argument that every script should have used `v=false` to protect against future breakage is particularly galling, since this usage was undocumented. It demonstrates a cavalier attitude toward breaking changes that doesn't inspire trust.

Breaking changes, especially breaking changes in APIs (_cat is definitely an API) should only be considered when the original behavior was fundamentally broken. That isn't the case here.

A command-line, user-friendly state inspection tool would be very useful, but _cat is not that tool. Wow your users with a top-like dashboard shipped with the distribution. Don't discourage them by changing the _cat default.

/cc @dakrone @drewr @TwP

**Comment by nik9000** [comment]
I agree with @grantr on this one. The _cat API was built for computers and followed the grand unix tradition of the defaults being right for computers instead of people. We got used to `du -h` and `ls -lh` and, in our cranky unix way, love them. As we love the _cat api.

**Comment by grantr** [comment]
> It demonstrates a cavalier attitude toward breaking changes that doesn't inspire trust.

I should mention that in general breaking changes seem carefully considered, and I appreciate that. This is an unusual case.

**Comment by dakrone** [comment]
And FWIW, even though I authored the original breaking change, I'm okay with either direction as long as it is best for the general userbase

**Comment by kimchy** [comment]
I vote to default back to non verbose mode

**Comment by clintongormley** [comment]
It makes sense to have it default to verbose when typing ad-hoc commands, which is probably something we could change in Sense instead.

OK, let's revert this change.

**Comment by nik9000** [comment]
Fixed in master and 2.0 branches.
