### ISSUE TITLE
Recovery fails to handle truncated translog files on NTFS

### ISSUE THREAD

**Issue by pablocastro** [elastic/elasticsearch#13168]
As captured in #9699 the translog can get truncated during a power failure or a system crash. The actual details of what a partial write looks like depend on the filesystem among other things, and the fix to that bug addresses partial writes that are seen when this failure happens in ext4 (xfs seems to expose a similar behavior) .

In NTFS a partial write often looks different. If the failure happens in the middle of a FlushFileBuffers call (called by force() on Windows) it may catch the filesystem at a point where file size has been updated in metadata but no data has been written (or at least the valid data pointer has not been moved yet). For security reasons NTFS will return all 0s for content when reading past the last successfully written point after the system restarts. 

The end result is either a translog file that has only zeroes in it (when only the start of the translog was written) or more commonly a translog file that has a set of whole transaction records followed by one or more buffers worth of zeroes. In both cases the translog reading logic chokes on these files during recovery and doesn’t recover the shard (concretely, since there’s 0s at the translog record boundary, the translog record type is read as 0 and that causes Translog.Operation.fromId() to fail).

I discussed this with the NTFS folks here at Microsoft and they confirmed we can rely on the 0s for cases where metadata was updated but data wasn’t during a system failure.

In the context of the 1.7 codebase a relatively simple fix for this would be throw TruncatedTranslogException whenever we see a transaction record of type “0” since it's never a valid type. This covers both cases, one because 0s start at a record boundary and the other because a file that’s all 0s makes ES think it’s an old translog file, and the legacy translog file code skips the size (first 4 bytes) and goes straight for the first record. To be conservative the checking of 0s could be Windows only, although I’m not sure if that’s necessary since no healthy translog should have it. It could even be taken further by verifying that some of the subsequent bytes are 0s as well, although that might be too far. 

The 2.0 codebase has moved quite a bit and I’m less familiar with it, but somehow this would need to be factored in either by having a boundary where a check for 0s is a safe detection strategy or by growing the translog in known increments and placing markers at the previous page that can be used to detect partial writes. Happy to help explore/validate approaches if that would be useful.

I have a few truncated translog files if anyone wants to take a look (couldn't attach them here, github didn't like .binary files). I have a simple fix and tests for this implemented since we needed to address this quickly here, if a PR would help I can send one.

**Comment by clintongormley** [comment]
Hi @pablocastro 

The translog has changed dramatically in 2.0.  It is now fsynced after every request, and has checkpoints which are written and fsynced after the translog fsync.  The checkpoint file is designed to fit into a single block and so writing it should be atomic.  

See https://github.com/elastic/elasticsearch/pull/11143 and specifically https://github.com/elastic/elasticsearch/pull/11143/files#diff-775d4fc503b78c9a0ef6fd7d1a50f7a8R76 for more details.

In our testing (where we randomly kill the power to servers) we are no longer seeing translog corruptions.

**Comment by pablocastro** [comment]
Thanks for looking at this. 

For 1.7, given that most production users are still on it, would you consider a fix that's specific to this codebase? I would be happy to send a pull request if that helps. 

For 2.0, let me catch up on all the changes you guys did first so I can comment with appropriate context. 

In the meanwhile I'd love to see if we can make a 1.7 fix happen.

**Comment by s1monw** [comment]
> In the meanwhile I'd love to see if we can make a 1.7 fix happen.

the 2.0 code is pretty much a rewrite I don't think we should backport this and for a bugfix release such a change is too big anyway. We closed 1.x dev branches so not much is going to happen there. We have to move on and make sure folks move to 2.0 asap to get all the other goodies too. I don't think we should spend much time on fixing 1.7 but rather invest and test 2.0 instead.

**Comment by s1monw** [comment]
@pablocastro 2.0 has been well out there I am closing this
