### ISSUE TITLE
Param settings for tribe in elasticsearch.yml config

### ISSUE THREAD

**Issue by TinLe** [elastic/elasticsearch#13167]
It would be useful to have a bunch of knobs, settings we can set, specifically with tribe nodes.

Some settings that come to mind:

. how many indices we want to keep track of per downstream clusters.

. how "recent" the indices, e.g. we're only interested in last 2 days(48hrs) indices from each cluster.

. how often tribe node poll/query downstream for updates, how many tries before giving up, timeouts, etc.

. membreaker settings. e.g. if mem usage get above a certain percent, to flush for safety instead of falling over.

Feel free to add in other settings.

The idea is to help a tribe node deal with large clusters/large number of indices.

**Comment by javanna** [comment]
I don't think we want to extend the Tribe node given that we have a replacement for it: Cross Cluster Search. See https://www.elastic.co/blog/tribe-nodes-and-cross-cluster-search-the-future-of-federated-search-in-elasticsearch .
