### ISSUE TITLE
Snapshots not working.

### ISSUE THREAD

**Issue by theocincotta** [elastic/elasticsearch#13161]
Hello,

This could be a user issue, but I'm having issues creating snapshots. I've added the path to elasticsearch.yml.  Any ideas on who to fix this? 

Thanks!

#path
path.repo: ["/data/elasticsearch/backups"] 

#command
curl -XPUT 'http://localhost:9200/_snapshot/new_backup' -d '{
     "type": "fs",
     "settings": {
         "compress" : true,
         "location": "/data/elasticsearch/backups"
     }
 }'

#error
{"error":"RepositoryVerificationException[[.kibana] [XXXX, 'RemoteTransportException[[es03][inet[/192.168.0.3:9300]][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[.kibana] a file written by master to the store [/data/elasticsearch/backups] cannot be accessed on the node [[es03][XXXX][es03][inet[/192.168.0.1:9300]]]. This might indicate that the store [/data/elasticsearch/backups] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node]; '], [XXXX, 'RemoteTransportException[[es02][inet[/192.168.0.2:9300]][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[.kibana] a file written by master to the store [/data/elasticsearch/backups] cannot be accessed on the node [[es02][XXXX][es02][inet[/192.168.0.2:9300]]]. This might indicate that the store [/data/elasticsearch/backups] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node]; ']]]","status":500}

**Comment by theocincotta** [comment]
I'm running elasticsearch 1.6.2.

**Comment by imotov** [comment]
@theocincotta In order to register the shared file system repository it is necessary to mount the same shared filesystem to the same location on all master and data nodes. Please see [Snapshot and Restore](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_shared_file_system_repository) documentation for more information.

**Comment by theocincotta** [comment]
Thanks!

**Comment by theocincotta** [comment]
Is it possible to just backup one index from one node without dealing with
mounting a filesystem on all the nodes?

**Comment by imotov** [comment]
@theocincotta we are using github for bug reports and feature requests. A much better place to ask questions about Elasticsearch and get help with elasticsearch issues is our discussion forum https://discuss.elastic.co/. At the moment you have to either share a filesystem or use S3 or azure repository to backup to S3 or azure.

**Comment by theocincotta** [comment]
Gotcha. Thanks!
