### ISSUE TITLE
bad groovy script delete-by-query makes shard unrecoverable

### ISSUE THREAD

**Issue by jeremybmerrill** [elastic/elasticsearch#13160]
An index is now unrecoverable because I ran a Groovyscript delete-by-query against it, and the query errored out. That query is below.

````
curl -XDELETE 'http://my_elasticsearch_host/my_index_name/my_type/_query' -d '{
 "query": {
   "filtered": {
     "filter": {
       "script": {
         "script": "_source.body.length() == 0"
       }
     }
   }
 }
}
'````
My goal was to delete all records whose `body` field was an empty string. The error I get after restarting the elasticsearch server is:
````
[2015-08-27 18:30:11,309][WARN ][cluster.action.shard     ] [Schemer] [daily_worker][1] received shard failed for [daily_worker][1], node[6fa-STJgTT6z-uQbzIDErA], [P], s[INITIALIZING], unassigned_info[[reason=ALLOCATION_FAILED], at[2015-08-27T18:30:11.274Z], details[shard failure [failed recovery][IndexShardGatewayRecoveryException[[daily_worker][1] failed to recover shard]; nested: RefreshFailedEngineException[[daily_worker][1] Refresh failed]; nested: GroovyScriptExecutionException[NullPointerException[Cannot invoke method length() on null object]]; ]]], indexUUID [AmmH0azOQzOi2wkzy_H_lw], reason [shard failure [failed recovery][IndexShardGatewayRecoveryException[[daily_worker][1] failed to recover shard]; nested: RefreshFailedEngineException[[daily_worker][1] Refresh failed]; nested: GroovyScriptExecutionException[NullPointerException[Cannot invoke method length() on null object]]; ]]
````
Cluster status is 
````
{

    "status": "red",
    "number_of_shards": 5,
    "number_of_replicas": 1,
    "active_primary_shards": 0,
    "active_shards": 0,
    "relocating_shards": 0,
    "initializing_shards": 3,
    "unassigned_shards": 7
},````

Ideally I'd like to be able to recover the index. Please let me know what I can do to fix this; feel free to ask away if there's any more information I can give you about this to help you fix the problem.

Edit: Probably wouldn't hurt to note that I'm running ES 1.7.0. Lucene's CheckIndex command says there's no problems with any of the shards in my index.

**Comment by jeremybmerrill** [comment]
Workaround: Turn off scripting entirely in your elasticsearch.yml by adding `script.disable_dynamic: true` (or commenting out the `script.disable_dynamic: false`).

**Comment by s1monw** [comment]
hey @jeremybmerrill thanks for opening this. On the one hand this is a huge disaster and I am sorry for it. But this is exactly on of the reasons why we moved delete by query our of core and made is slowish but not prone to these problems. I will use this as an example in the future :)

as far as I can tell you recovered your index with your workaround, right?

**Comment by jeremybmerrill** [comment]
Hi @s1monw, thanks for your response. Yeah, saw it's deprecated, but didn't realize I'd end up in this sort of trouble... 

I'm not sure if, were I to re-enable dynamic scripting, my index would still be broken. But, yeah, I'm back up and running.

**Comment by s1monw** [comment]
@jeremybmerrill if you `_flush` your index all DBQ in your translog should be processed and you should be fine again.. I'd recommend you not running these kind of queries in DBQ

**Comment by jeremybmerrill** [comment]
I'll give that a try. POST to `/index/_flush`, right?

Yep, learned my lesson :) Will probably stay away from this DBQ thing from now on.

**Comment by s1monw** [comment]
> I'll give that a try. POST to /index/_flush, right?

correct!

I suggest if you need the functionality to use scan & scroll and delete by id using bulk. that's how the new plugin in 2.0 works

I am closing this for now...thanks!
