### ISSUE TITLE
discovery.zen.ping.unicast.hosts can't deal with an url?

### ISSUE THREAD

**Issue by yuz11** [elastic/elasticsearch#13175]
here's the deal:
I try to use the unicast function to organize a cluster.As I get 6 servers,so I try to write those ips to the /etc/hosts of all the servers by script(etc. 1.1.1.1 es.com),then config elasticsearch.yml " discovery.zen.ping.unicast.hosts: ["es.com"]".hoping es will find out the ips by this url.
of course,this action bring out no result.Then I have to config like "discovery.zen.ping.unicast.hosts: ["1.1.1.1","2.2.2.2"...etc]"
I really think if es unicast support url config will be better when dealing with a number of servers.
Will es unicast support config like " discovery.zen.ping.unicast.hosts: ["es.com"]" in the future?
Or any suggestion to deal with a number of servers supporting add/remove nodes.

**Comment by clintongormley** [comment]
I'm unclear on what you're asking here.  This seems to work for me. if I configure /etc/hosts to have, eg:

    1.2.3.4   abc.foo.com
    1.2.3.5   abc.foo.com
    1.2.3.6   abc.foo.com

and set `discovery.zen.ping.unicast.hosts` to `abc.foo.com`, then it tries all three IPs

**Comment by clintongormley** [comment]
Nothing further. Closing
