### ISSUE TITLE
Analyze issues with copy_to target fields

### ISSUE THREAD

**Issue by Shadocko** [elastic/elasticsearch#13174]
Hello,

I'm experiencing strange issues with analyze on fields used as targets for copy_to.
The analyze API always return trivial results but the analyzers from the copy_to origin field seem in some cases to be used either at index or query time, instead of the ones defined for the copy_to target.

Since I'm not 100% sure this is a bug, I opened a thread on SO with a simple test case showing the behavior that's bothering me but it didn't get much attention: http://stackoverflow.com/questions/32250332/

Any help would be greatly appreciated.
Oh, and by the way, elasticsearch is excellent software!

Regards,

**Comment by dadoonet** [comment]
The french analyzer seems to return another result then the one your are expecting:

```
DELETE test
PUT test
POST test/_analyze?text=clément&analyzer=french
```

Gives:

```json
{
   "tokens": [
      {
         "token": "cl",
         "start_offset": 0,
         "end_offset": 2,
         "type": "<ALPHANUM>",
         "position": 1
      },
      {
         "token": "ment",
         "start_offset": 3,
         "end_offset": 7,
         "type": "<ALPHANUM>",
         "position": 2
      }
   ]
}
```

That explains why it does not match your clement query.

So IMO it's not an issue with the "copy_to" feature here.

Closing for now. Feel free to reopen if you think it's an issue.

**Comment by dadoonet** [comment]
BTW, I tried to analyze `clement` and it gives:

```
{
   "tokens": [
      {
         "token": "cle",
         "start_offset": 0,
         "end_offset": 7,
         "type": "<ALPHANUM>",
         "position": 1
      }
   ]
}
```

**Comment by dadoonet** [comment]
I was expecting the standard tokenizer not to break `clément` at the first `é`. Reopening to make more tests.

**Comment by dadoonet** [comment]
Ok. My platform test is badly setup. If I use curl instead of running that from the browser, then I'm getting expecting results.

```sh
curl -XGET 'localhost:9200/_analyze?analyzer=french&pretty' -d 'clément'
```

```json
{
  "tokens" : [ {
    "token" : "clement",
    "start_offset" : 0,
    "end_offset" : 7,
    "type" : "<ALPHANUM>",
    "position" : 1
  } ]
}
```

And 

```sh
curl -XGET 'localhost:9200/_analyze?analyzer=french&pretty' -d 'clement'
```

Gives: 

```
{
  "tokens" : [ {
    "token" : "cle",
    "start_offset" : 0,
    "end_offset" : 7,
    "type" : "<ALPHANUM>",
    "position" : 1
  } ]
}
```

So no bug IMO with the `copy_to` feature but you probably need to adjust the `french` analyzer to meet your needs instead of using the default configuration: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lang-analyzer.html#french-analyzer

**Comment by Shadocko** [comment]
Sorry, I overlooked the fact that the default french analyzer did not yield the same results for "clément" and "clement". I'm having a slow week...
