### ISSUE TITLE
Percolator - Provide ability to not evaluate all queries when requesting N Hits

### ISSUE THREAD

**Issue by gingerwizard** [elastic/elasticsearch#13176]
Currently percolator allows you to control the number of matches with a size parameter.  However, it always reports the total number of matches and thus is forced to evaluate all queries irrespective of the size.  On larger percolator deployments, the total number of matches is sometimes not required and only the 

Request the addition of a total_hits parameter.  If true, all queries will be evaluated. If false, all queries will be evaluated only if no size parameter is provided - otherwise Percolator will simply drop out.

Introduces considerations with sorting that need discussion

**Comment by gingerwizard** [comment]
@martijnvg

**Comment by clintongormley** [comment]
For consistency, perhaps support the `terminate_after` parameter instead.  See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html

**Comment by clintongormley** [comment]
@martijnvg what do you think?

**Comment by martijnvg** [comment]
@clintongormley I think supporting `terminate_after` makes sense.
