### ISSUE TITLE
get the most critical messages in ELK stack

### ISSUE THREAD

**Issue by albarki** [elastic/elasticsearch#13191]
Hello 
i have an ELK stack up and running, all things is OK, but i need to move forward to send some alerts to the sysadmins to begin to work in the errors that comes from all servers.
SO i want to write a query to get top 10 critical unique messages stored in Elasticsearch, then i will send an alert regarding each messages.
I tryied this query but it give me a wrong data
```
{
  "size": 0,
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "analyze_wildcard": true,
          "query": "crit"
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gte": 1440712800000,
                  "lte": 1440799199999
                }
              }
            }
          ],
          "must_not": []
        }
      }
    }
  },
  "aggs": {
    "3": {
      "terms": {
        "field": "message",
        "size": 20,
        "order": {
          "_count": "desc"
        }
      }
    }
  }
}
```

Regards

**Comment by clintongormley** [comment]
Hi @albarki 

The place to ask questions like these is in the forums: https://discuss.elastic.co/

Also, when you do, I'd suggest providing some example data and explaining why you think the results are wrong and what results you expect instead.
