### ISSUE TITLE
how to change a existing analyzer in Elasticsearch?

### ISSUE THREAD

**Issue by h3idan** [elastic/elasticsearch#13200]
Now that's existing analyzer： 
```
"analyzer": {
  "xmap_analyzer": {
    "type": "custom",
    "char_filter": [ "html_strip"],
    "filter": [ "lowercase"],
    "tokenizer": "standard"
  }
}
```
I want to remove "filter", and it'll be this: 
```
"analyzer": {
"xmap_analyzer": {
    "type": "custom",
    "char_filter": [ "html_strip"],
    "tokenizer": "standard"
  }
}
```
I have tried to update the settings, like this: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html#update-settings-analysis

But it's invalid, how should I do? Is it a bug?

**Comment by dadoonet** [comment]
Please ask questions on discuss.elastic.co.

You can not change an existing analyzer and you basically need to reindex.
