### ISSUE TITLE
Position-increment-gap doc need to be updated

### ISSUE THREAD

**Issue by xuzha** [elastic/elasticsearch#13207]
After we changed default `position_increment_gap` to 100, the example below in this [doc](https://github.com/elastic/elasticsearch/blob/master/docs/reference/mapping/params/position-increment-gap.asciidoc) is outdated.

```
PUT /my_index/groups/1
{
    "names": [ "John Abraham", "Lincoln Smith"]
}

GET /my_index/groups/_search
{
    "query": {
        "match_phrase": {
            "names": "Abraham Lincoln" (1)
        }
    }
}
```

**Comment by nik9000** [comment]
@clintongormley did you start working on this?

**Comment by clintongormley** [comment]
@nik9000 not yet :) just added to my list

**Comment by nik9000** [comment]
> @nik9000 not yet :) just added to my list

I'm happy to grab it if you want.
