### ISSUE TITLE
Improvement of package/artifact deployment

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#13209]
We need to work on improving our artifact deployments. Collected several thoughts about this

* Should the RPM be signed or not as part of our deployment. If the RPM is not signed, older RPM based distributions will not have a problem to install. As we do sign our artifacts now as part of the mvn deployment (which adds an .asc file), this should not be a problem in terms of integrity. @electrical might chime in here, if we can drop this approach. If we need two artifacts, I am personally fine with having the unsigned one in the sonatype repo (which is also the one linked on elastic.co) and sign the RPM before putting it in the rpm repository (using the tools mentioned in the next bullet point)
* Smoothen out our RPM/DEB deployment process. There are tools like [deb-s3](https://github.com/krobertson/deb-s3) and [rpm-s3](https://github.com/crohr/rpm-s3), which dont require us to create all the additional meta files manually, but just push the package using that tool.
* Verify staging repository (the sonatype one), that it includes all the files... maybe this can be done by comparing it to the local mvn repo via a small script, that just checks via HTTP HEAD if the file exists (no need to check checksums, we should assume so things work)
* Verify signedness/unsignedness of artifacts on sonatype and the package repositories

**Comment by spinscale** [comment]
Took a first look at `deb-s3`. Like it so far. All you need is an unsigned debian package, specify this debian package on the command line, which upload its automatically, and then asks for the passphrase to sign the `Release` file. No need for complex syncing like done in our scripts right now.

Uploading works like this

```
deb-s3 upload --preserve-versions elasticsearch-2.0.0-beta1.deb -b $BUCKET --prefix alexr-repo-test/elasticsearch/deb --sign $GPG_KEY_ID --arch amd64
```

There are a couple of commands for verifying:

```
# deb-s3 show elasticsearch 1.7.1 amd64 -b test.elasticsearch.org --prefix alexr-repo-test/elasticsearch/deb
...
[lists packages contents]
...

# deb-s3 list -b test.elasticsearch.org --prefix alexr-repo-test/elasticsearch/deb
elasticsearch  1.7.1  all

# deb-s3 verify -b test.elasticsearch.org --prefix alexr-repo-test/elasticsearch/deb
>> Retrieving existing manifests
>> Checking for missing packages in: stable/main amd64
>> Checking for missing packages in: stable/main i386
```

Couple of things I tested

* replacing existing debian packages
* keeping the old packages in place, so people can do `apt-get install elasticsearch=X.Y.Z`
* upgrading debian packages after reinstalling

Installation works like this, as it is a gem. You need `libz-dev` installed for the `nokogiri` package

```
# install
GEM_PATH=/path/deb-s3 GEM_HOME=/path/deb-s3/ gem install deb-s3
# run, no need to specify paths it seems on run
/path/deb-s3/bin/deb-s3
```

Next stop: `rpm-s3`

**Comment by electrical** [comment]
Important thing is that both the repo it self and the packages are signed and that we also are able to have multiple versions of ES in the repo and available ( most tools don't allow for that )

As a side note; we will have the need soon for 2 different signed rpm's. one with the V3 signature ( centos5 / SLES ) and one with V4 signature ( Centos6+, opensuse, etc )
This will also need to be a separate repo ( centos5 ipv centos; for example )

**Comment by jordansissel** [comment]
@spinscale regarding apt/yum facilities, @drewr and I have been looking (as time permits) at some hosted repository options that may meet our needs (packagecloud, etc). I'd be cool if we used the same solution for all our hosting, but I would consider "where are the rpm/debs posted?" a separate problem from how the packages are constructed.

**Comment by spinscale** [comment]
@jordansissel absolutely, I think package construction will be hard to unify across projects, and at best switching the underlying repository should only replace a single call to a tool for each package. We can still go with the above tools and switch whenever needed to push things to packagecloud or whatever we opt for

**Comment by spinscale** [comment]
Spent some time testing [rpm-s3](https://github.com/crohr/rpm-s3) today

## Installation

* Prerequisites: `yum`, `deltarpm` and `boto`: `apt-get install yum python-deltarpm python-boto`
* Clone the github repo: `git clone https://github.com/crohr/rpm-s3 --recurse-submodules`
* Set env vars: `export AWS_ACCESS_KEY="key"` and `export AWS_SECRET_KEY="secret"`
* Change your `.boto` file (see issues with buckets with dots https://github.com/boto/boto/issues/2836) to this:
```
[s3]
calling_format = boto.s3.connection.OrdinaryCallingFormat
```

* Set your `~/.rpmmacros` file to be accordingly with your GPG key
```
%_signature gpg
%_gpg_name Test Example
```

Dont forget to import your key on the redhat test system before proceeding

```
rpm --import http://$BUCKET.s3.amazonaws.com/YOUR-KEY.gpg
```

```
rpm-s3/bin/rpm-s3 -v -b $BUCKET -p $PREFIX --sign elasticsearch-1.7.1.noarch.rpm --visibility public-read -k 0
rpm-s3/bin/rpm-s3 -v -b $BUCKET -p $PREFIX --sign elasticsearch-2.0.0-beta1.rpm --visibility public-read -k 0
```

Short explanation: Bucket and prefix define the path of the rpm, `visibility` must be `public-read` to make the uploads readable by anyone, `-k 0` instructs `rpm-s3` to not delete old packages, but just incrementally add them. Default is to remove packages older than two releases.

## Signing

Verifying the signature can be done via `rpm --checksig -v elasticsearch-1.7.1.noarch.rpm`

Manual signing can be done via `rpm --addsign elasticsearch-1.7.1.noarch.rpm`. Needs to be done currently as the built-in signing seems not to work

## Testing

Create a repo file in `/etc/yum.repos.d/elasticsearch.repo` 

```
[elasticsearch]
name=Elasticsearch repository for RPM packages
baseurl=http://s3.amazonaws.com/$BUCKET/$PREFIX
gpgcheck=1
gpgkey=http://$BUCKET.s3.amazonaws.com/$PREFIX/PUBKEY.gpg
enabled=1
metadata_expire=30
```

The expiration of metadata is just needed for testing as otherwise `yum update` will cache and reuse the local version for six hours.

We could create the above repo file as part of the deployment process, so automated tools can test the repository.

## Summary

* Pro: You only need the signed RPM and thats it, the tool handles the rest
* Pro: Adding new RPMs means just uploading them, thats it. No manual download and reconstruction of the repo structure like we do in the current shell script
* Contra: `rpm --addsign elasticsearch-1.7.1.noarch.rpm` needs to be called manually right now, looks like a bug, filed an issue

**Comment by spinscale** [comment]
Worked on a python script, that is using the local mvn repository and compares its contents to a remote destination (like a staging repo)

Script is doing the following steps

* Scans the local maven repo for all files in /org/elasticsearch
* Opens a HTTP connection to the staging repo
* Executes a HEAD request for each file found in step one
* Compares the content-length response header with the real file size
* Return an error if those two numbers differ

Output looks like this:

![Script while running](https://s3.amazonaws.com/uploads.hipchat.com/29251/250169/ZfCor5NQ00atVzF/output.gif)

This should fix the problem of incomplete deployments

**Comment by nik9000** [comment]
I'm about to pick up #13182 and this looks related. At least the signing part. I haven't read all of your notes yet but maybe we should talk some?
