### ISSUE TITLE
Adding path to path.data loses shards

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/elasticsearch#13210]
With a simple one node Elasticsearch 1.7.1 instance, with a few indicies, I added another directory to path.data. When I restarted Elasticsearch, a number of the indicies were unavailable. Is this expected behaviour?

**Comment by clintongormley** [comment]
Hmmm no it is not.  I managed to replicate this by creating 4 indices, then shutting down, adding a new data path and starting. One index wasn't assigned properly.  Restarting fixed the issue.

note: now is not a good time to switch to multi data paths as the implementation is changing completely in 2.0: a single shard will no longer be striped across multiple data paths, instead one shard will be written only to one path.

**Comment by clintongormley** [comment]
Tested this out in master and it works correctly.  Given that this config change (after creating indices) is probably not usual, and there is a workaround, i'm going to close this as won't fix.

**Comment by clintongormley** [comment]
(by master i meant 2.0 and above)

**Comment by haochun** [comment]
@clintongormley @jimmyjones2 i have a encountered the same problem now.i have two shards on one node,but,i found i have no enough space to _optimize.Then, i add a diver to the machine,and add a path to path.data in elasticsearch.yml.But,two shards are UNASSIGNED when i restart elasticsearch.My elasticsearch version is 1.7.3.How can i solve this problem?
