### ISSUE TITLE
improved backwards compatibility tests

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13216]
Now that 2.0beta1 is released, we could try to prototype some more realistic backwards compatibility testing.

Some scheme like this might work:
- qa/backwards-20beta1-rest: starts up bin/elasticsearch from current code, but runs the packaged rest suite from 2.0 beta1 against it (it is included in that test jar already). So its similar to what we do in distribution tests, just with different test dependencies.
- qa/backwards-20beta1-multinode: starts up bin/elasticsearch from current code, then starts up bin/elasticsearch from 2.0-beta1 code and verifies they can join a cluster. So its similar to smoke-test-multinode, with different integ depedencies.

**Comment by nik9000** [comment]
++

I wonder if we can have a policy to prevent combinatorial explosion?

**Comment by rmuir** [comment]
What do you mean by a policy? I don't see combinatorial explosion... this would be 2 scenarios for each version. Whatever versions we are supposed to be compatible with, I think we should test.

**Comment by s1monw** [comment]
++

**Comment by nik9000** [comment]
> What do you mean by a policy? I don't see combinatorial explosion... this would be 2 scenarios for each version. Whatever versions we are supposed to be compatible with, I think we should test.

I could see us doing:
* 2.0.0-beta1 + current
* 2.0.0 + current
* 2.0.0-beta1 + 2.0.0 + current
* 2.0.1 + current
* 2.0.0 + 2.0.1 + current
* 2.0.0-beta1 + 2.0.0 + 2.0.1 + current

And that list getting very long very quick. If we stick to just having two different versions at a time that is "policy" enough for me. Though we might want to have one rainbow test where we do all the versions or something horrible like that.

**Comment by rmuir** [comment]
> 2.0.0-beta1 + 2.0.0 + current

why would we do that? I don't think we need to support a cluster with a mix of 3 versions. What is the use case for that?

I only see this:
* 2.0.0-beta1 -> current
* 2.0.0 -> current
* 2.0.1 -> current

**Comment by nik9000** [comment]
> why would we do that? I don't think we need to support a cluster with a mix of 3 versions. What is the use case for that?

Its mostly a mistake to use three versions at once. People do it. I've heard of it happening in scenarios where people are using the java client and when people don't upgrade their dedicated master nodes properly.

I do get your point about only testing the two versions at once. You still get a lot of test cases but its not so bad as I was envisioning.

**Comment by rmuir** [comment]
> I do get your point about only testing the two versions at once. You still get a lot of test cases but its not so bad as I was envisioning.

You can even reduce this by just doing previous -> current. Its less thorough but better than nothing.

**Comment by nik9000** [comment]
> You can even reduce this by just doing previous -> current. Its less thorough but better than nothing.

I could see that as the normal thing to run before sending a pull request and the wider range being normal to run nightly or something.

**Comment by nik9000** [comment]
So #13477 makes a start on this - it moves the dependency resolution to maven and sets up a reasonably simple way to add new versions and things like that. It doesn't do the following things that we really should do:
* Launch all elasticsearch using `bin/elasticsearch` - no internal nodes at all.
* Run the rest tests against the mixed version cluster.
* Other stuff I haven't thought about much like running rest tests during a rolling restart.

The backwards compatibility tests as they stand now do the following:
* UnicastBackwardsCompatibilityIT forms a mixed version cluster and connect to it using the TransportClient and counts the data nodes to make sure they are all there as expected. This is the most basic backwards compatibility test.
* BasicBackwardsCompatibilityIT does some indexing, gets, deletes, searches, verifies that indexes can recover from older version to newer versions but not the other way around, rolling upgrades, and a whole bunch of other stuff. 
* Tests like NodesStatsBasicBackwardsCompatIT run the stats commands on a mixed version cluster and verify that what comes back makes sense. These stats APIs can change a lot in a major release so these are pretty important.


The tests as they stand now are import and useful even if they could do with some love to make them more real.

**Comment by atorok** [comment]
Given the age of the issue and how much things changed I'm going to close it. 
Please reopen if you think some of it is still relevant.
