### ISSUE TITLE
Allow plugins to be specified using NodeBuilder

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#13212]
With the removal of `plugin.types` in #13055, there is no longer a way to specify plugins to load for a node client other than creating a plugins directory and putting all of the plugins in that directory. We should add a `addPlugin` method to the `NodeBuilder` class so that plugins can be specified by their class.

**Comment by kimchy** [comment]
Agreed, seems like we missed this? @rjernst I think we should?

**Comment by clintongormley** [comment]
@kimchy @rjernst do we have a plan for this yet?

**Comment by s1monw** [comment]
@jaymode is this still relevant with the test framework?

**Comment by jaymode** [comment]
The test framework `MockNode` works for all cases as far as I know, except for testing plugins with a tribe node. The tribe service isn't able to pass down the plugins to the tribe nodes. The workaround for testing plugins with tribe nodes is to use `IT` style integration test with multiple external clusters.

**Comment by joschi** [comment]
It would be nice to (re-) introduce the possibility to programmatically add classpath plugins to an Elasticsearch node. My use case is running an embedded client node in a Java application which should load a plugin to listen to cluster state changes (e. g. nodes added/removed, indices added/removed) and share this information with the embedding application.

**Comment by clintongormley** [comment]
Closing.  See discussion in #15107
