### ISSUE TITLE
Behaviour different with custom _all

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/elasticsearch#13214]
With the following simple query, I get different results with a custom_all to the other cases:

``` json
GET /test*/_search
{
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "query": "*"
        }
      }
    }
  }
}
```

| test | description | result count |
| --- | --- | --- |
| test1 | custom _all | 1 |
| test2 | disabled_all | 2 |
| test3 | include_in_all | 2 |
| test4 | normal | 2 |

I thought this might be because one of the documents doesn't add anything to the custom _all field, but neither does one of the documents in the include_in_all example, yet that still returns both documents. I assume when _all is disabled the query is effectively converted to match_all. 
## test1: custom _all

``` bash
curl -XDELETE localhost:9200/test1
curl -XPUT localhost:9200/test1/ -d '
{
  "settings" : {
    "index" : {
      "query.default_field" : "_myall"
    }
  },
  "mappings" : {
    "test" : {
      "_all" : {
        "enabled" : false
      },
      "properties" : {
        "_myall" : {
          "type" : "string",
          "index" : "not_analyzed"
        },
        "test" : {
          "type" : "long",
          "copy_to" : "_myall"
        }
      }
    }
  }
}'
curl -XPOST localhost:9200/test1/test -d '{ "myid" : 4 }'
curl -XPOST localhost:9200/test1/test -d '{ "test" : 4 }'
```
## test2: disabled _all

``` bash
curl -XDELETE localhost:9200/test2
curl -XPUT localhost:9200/test2/ -d '
{
  "mappings" : {
    "test" : {
      "_all" : {
        "enabled" : false
      }
    }
  }
}'
curl -XPOST localhost:9200/test2/test -d '{ "myid" : 4 }'
curl -XPOST localhost:9200/test2/test -d '{ "test" : 4 }'
```
## test3: include_in_all

``` bash
curl -XDELETE localhost:9200/test3
curl -XPUT localhost:9200/test3/ -d '
{
  "mappings" : {
    "test" : {
      "properties" : {
        "myid" : {
          "type" : "long",
          "include_in_all" : true
        },
        "test" : {
          "type" : "long",
          "include_in_all" : false
        }
      }
    }
  }
}'
curl -XPOST localhost:9200/test3/test -d '{ "myid" : 4 }'
curl -XPOST localhost:9200/test3/test -d '{ "test" : 4 }'
```
## test4: default

``` bash
curl -XDELETE localhost:9200/test4
curl -XPUT localhost:9200/test4/ -d '
{
  "mappings" : {
    "test" : {
      "properties" : {
        "myid" : {
          "type" : "long"
        },
        "test" : {
          "type" : "long"
        }
      }
    }
  }
}'
curl -XPOST localhost:9200/test4/test -d '{ "myid" : 4 }'
curl -XPOST localhost:9200/test4/test -d '{ "test" : 4 }'
```

**Comment by clintongormley** [comment]
Hmmm, interesting finding... The reason for it is that `_all:*` and `foo:*` get rewritten as different queries:

    GET /test*/_validate/query?explain
    {
      "query": {
        "query_string": {
          "query": "*",
          "default_field": "_all"
        }
      }
    }

returns:

    "explanation": "ConstantScore(*:*)"

while:

    GET /test*/_validate/query?explain
    {
      "query": {
        "query_string": {
          "query": "*",
          "default_field": "foo"
        }
      }
    }

returns:

    "explanation": "ConstantScore(cache(BooleanFilter(_field_names:foo)))"

The latter translates to "return all documents that have any value in field `foo`".

For this query `*` it seems right to match all documents. For the `foo:*` query, it feels right to return documents that have a value in field `foo`.  However, in your example with query `*` which is rewritten to `foo:*`, we're doing the unexpected... Perhaps the rule should be: "if a wildcard is specified without a field: prefix, then match all docs"

**Comment by jimmyjones2** [comment]
Thanks @clintongormley. I originally found the issue when using Kibana, as when viewing all documents in Discover, I couldn't see all the documents!

**Comment by clintongormley** [comment]
Discussed in FixItFriday, we agree that:

* `"*"` always means match all documents
* `"field:*"` means find all documents that contain a non-null value in the field (incl empty string)

**Comment by wilofice** [comment]
Hi, may I start working on this one? This will be my first contribution to open source and elastic.

**Comment by dakrone** [comment]
@wilofice unfortunately since `_all` has been removed, this issue is no longer needed, hope you haven't started yet!

I'm going to close this since `_all` is removed and the way that queries are rewritten for `query_string` and `simple_query_string` is different now for `*` versus `field:*`

**Comment by wilofice** [comment]
Thanks @dakrone. Fortunately, I didn't start yet. I will check other issues where I can contribute.
