### ISSUE TITLE
ElasticSearch running query string query on multiple fields

### ISSUE THREAD

**Issue by vineet85** [elastic/elasticsearch#13220]
I have a mapping which consists of a parent child relationship between documents and fields. I want to write a query that matches the parent using the query string query only if 2 fields match the query. 

Quoting from the documentation on Multi Field (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_multi_field_2)

Is there any way to do a search using the query string query in this manner and still return results :
{
    "query_string": {
      "query": "(content:this AND content:that) AND (value:that AND value:this)"
    }
}

**Comment by clintongormley** [comment]
Hi @vineet85 

Please ask questions like these in the forum instead. https://discuss.elastic.co/

thanks
