### ISSUE TITLE
Allow merging shard replicas based on document versions

### ISSUE THREAD

**Issue by rbranson** [elastic/elasticsearch#1322]
Would it be possible to allow shard replicas to be merged together after a network partition based on the highest version numbers? 

Clearly this would be optional, as versions would collide or become out-of-sequence in a default configuration. However, for people who desire this functionality, it's easy to generate globally unique, sequential version numbers from the content that won't collide (microsecond timestamp + truncated hash of the doc) on the client side and feed these as version numbers into ElasticSearch.

The only caveat I can think of is that deletions aren't as straightforward. It seems like the system Cassandra uses, which replaces the stored value with a "tombstone" that represents the deletion. The tombstones get cleaned up after a configurable grace time  period. I believe the grace period in Cassandra is 10 days by default -- clearly a very conservative value. This system seems to work well. The delete API already takes a version number, so that could be used to version the tombstones. Again, I think this should be totally optional as keeping tombstones might effect the performance & data size of some existing use cases that don't need this feature. If it isn't optional or doesn't need to be, perhaps the default grace period could be very short, like an hour?

Mergeable replicas would allow the an ElasticSearch cluster to operate as an eventually consistent "AP" system and could make working with multiple datacenters very feasible out-of-the-box. Currently it works as a "CP" system, so the quorum side of a network partition takes precedence and the other side(s) become effectively read-only. It would be nice to be able to continue to receive writes on the non-quorum side(s) and merge these writes into the cluster once it is healed.

Currently my strategy involves building a completely isolated ES cluster at each datacenter and distributing index updates using a message queue / worker system. Each datacenter has it's own isolated MQ and worker group. Index updates get inserted into a fan-out exchange which inserts an update message in each individual datacenter's outbound queue, which the workers pick up and perform the index update. This is complicated and was error-prone to start, and also introduces adds non-trivial extra cost and latency to the process.

**Comment by clintongormley** [comment]
I've left this issue open for a long time awaiting discussion, and I've chatted about it internally a bit, but found little support for this.  I think we've gone firmly down our current path and are unlikely to change tack, especially with the added complexity this would require.

I'm going to close this issue.  Who knows, maybe in the future once our current plans are implemented, we might rethink this but for now I don't think it is going anywhere.
