### ISSUE TITLE
Issue with time_zone in date_histogram aggregations

### ISSUE THREAD

**Issue by colmaengus** [elastic/elasticsearch#13236]
Hi folks,

We are currently using the date_histogram pre_zone/post_zone parameters and would like to change to using time_zone since the others are deprecated.
However they produce different results when using an hour interval.

To see this I created an index with four documents
```javascript
[{"date": "2014-12-31T23:30:00.000Z"},
{"date": "2014-12-31T23:30:00.000Z"},
{"date": "2015-1-1T00:30:00.000Z"},
{"date": "2015-1-1T01:30:00.000Z"}]
```

Using the pre_zone parameters
```javascript
{
  "aggs": {
    "articles_over_time": {
      "date_histogram": {
        "field": "date",
        "interval": "hour",
        "pre_zone": "-01:00",
        "post_zone": "-01:00",
        "pre_zone_adjust_large_interval": true
      }
    }
  }
}
```
gives
```javascript
[
  {"key_as_string": "2014-12-31T22:00:00.000Z", "key": 1420063200000, "doc_count": 1},
  {"key_as_string": "2014-12-31T23:00:00.000Z", "key": 1420066800000, "doc_count": 1},
  {"key_as_string": "2015-01-01T00:00:00.000Z", "key": 1420070400000, "doc_count": 1},
  {"key_as_string": "2015-01-01T01:00:00.000Z", "key": 1420074000000, "doc_count": 1}
]
```

Using the time_zone parameter
```javascript
{
  "aggs": {
    "articles_over_time": {
      "date_histogram": {
        "field": "date",
        "interval": "hour",
        "time_zone": "-01:00"
      }
    }
  }
}
```

gives
```javascript
[
  {"key_as_string": "2014-12-31T23:00:00.000Z", "key": 1420066800000, "doc_count": 1},
  {"key_as_string": "2015-01-01T00:00:00.000Z", "key": 1420070400000, "doc_count": 1},
  {"key_as_string": "2015-01-01T01:00:00.000Z", "key": 1420074000000, "doc_count": 1},
  {"key_as_string": "2015-01-01T02:00:00.000Z", "key": 1420077600000, "doc_count": 1}
]
```

Changing the value of time_zone has no impact on the results.
It works fine with larger intervals (day, month, year) just not with hour.
I'm using Elasticsearch 1.7.0 on windows.

Regards

Colm A

P.S. Its not an issue but I wondering why the key_as_string is always returned in UTC even when using time_zone. The time part of the string is correct for the time zone just the lack of timezone in is unexpected.

**Comment by clintongormley** [comment]
@cbuescher could you take a look at this please?

**Comment by cbuescher** [comment]
@colmaengus thanks for pointing this out, you are right that in ES 1.7 changing `time_zone` doesn't have an impact on the bucket key yet. This was changes with https://github.com/elastic/elasticsearch/pull/9744 and will be working in the upcoming 2.0 release.

In 1.7. `time_zone` is basically still working like `pre_zone` in that it shifts bucket boundaries for day intervals and larger but doesn't affect the buckey keys. Unfortunately you still need to use `post_zone` if you want to affect the buckey keys. In 2.0 the bucket `key` will always be returned in UTC to avoid confusion with time zone issues, but the `key_as_string` will take the `time_zone` setting of the aggregation into account, giving you the behaviour you probably expected above. Let me know if this clarifies things or if you need more help with this.

**Comment by clintongormley** [comment]
I've updated the 2.0 documentation for `time_zone` in date histograms to demonstrate more clearly how it will work: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-aggregations-bucket-datehistogram-aggregation.html#_time_zone

We're not going to change this in 1.7, so I'm going to close this issue

**Comment by colmaengus** [comment]
Thanks for the clarification guys.
