### ISSUE TITLE
Deprecate eager/lazy norms loading

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#13237]
Given that norms become disk-based in Lucene 5.3, having the ability to eagerly or lazily load them doesn't make much sense anymore.

**Comment by rmuir** [comment]
or it could be implemented more appropriately, e.g. https://issues.apache.org/jira/browse/LUCENE-6549

**Comment by jpountz** [comment]
This was done in 5.0, and we now expose a preload setting to allow loading specific parts of the index into the fs cache.
