### ISSUE TITLE
Document all possible logging packages

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#13234]
In `logging.yml` you can set things like `gateway: DEBUG` or `discovery: TRACE`.

It'd be great if we could document all of these packages that ES exposes as there's quite a few that we don't mention.

**Comment by nik9000** [comment]
> It'd be great if we could document all of these packages that ES exposes as there's quite a few that we don't mention.

It'd be great if we could generate that documentation....

**Comment by markwalkom** [comment]
Gotta start somewhere :p

**Comment by markwalkom** [comment]
I just realised I had already raised this in #10211
