### ISSUE TITLE
Mask issues in /var/lib/elasticsearch/elasticsearch/

### ISSUE THREAD

**Issue by vacri** [elastic/elasticsearch#13231]
I have a fresh debian 8 system taking elasticsearch 1.7.1 from the repos, running on openjdk. Elasticsearch wouldn't start because it couldn't write to `/var/lib/elasticsearch/elasticsearch/`, which was owned by the ES user, but whose permissions were 655 - no executable bit for the user means that ES couldn't create the subdir `nodes`.

I fixed this with `chmod +x /var/lib/elasticsearch/elasticsearch/` to change the perms to 755, but ran into the same problem again when ES tried to write to `nodes/0`, which was fixed by chmodding `nodes`. At this point ES successfully started, and created the subdir `0`... which didn't have the missing directory execute bit.

I'm not very familiar with java or systemd, and have no idea why the first two directories might be missing the +x but the final directory wasn't. I was thinking it was a mask issue, but the third directory was created correctly. 

Elasticsearch is up and running at this point, but I thought I might mention the issue here (couldn't find a previous ticket)

```bash
root@mayfly:/etc/systemd# apt-cache policy elasticsearch
elasticsearch:
  Installed: 1.7.1
  Candidate: 1.7.1
  Version table:
 *** 1.7.1 0
        500 http://packages.elastic.co/elasticsearch/1.7/debian/ stable/main amd64 Packages
        100 /var/lib/dpkg/status

root@mayfly:/etc/systemd# java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

root@mayfly:/etc/systemd# journalctl -u elasticsearch.service
(--snip a bit--)
Sep 01 01:51:59 mayfly.aws-sydney.etaskr.com systemd[1]: Starting Elasticsearch...
Sep 01 01:51:59 mayfly.aws-sydney.etaskr.com systemd[1]: Started Elasticsearch.
Sep 01 01:52:00 mayfly.aws-sydney.etaskr.com elasticsearch[1530]: {1.7.1}: Initialization Failed ...
Sep 01 01:52:00 mayfly.aws-sydney.etaskr.com elasticsearch[1530]: - ElasticsearchIllegalStateException[Failed to created node environment]
Sep 01 01:52:00 mayfly.aws-sydney.etaskr.com elasticsearch[1530]: AccessDeniedException[/var/lib/elasticsearch/elasticsearch/nodes]
Sep 01 01:52:00 mayfly.aws-sydney.etaskr.com systemd[1]: elasticsearch.service: main process exited, code=exited, status=3/NOTIMPLEMENTED
Sep 01 01:52:00 mayfly.aws-sydney.etaskr.com systemd[1]: Unit elasticsearch.service entered failed state.
Sep 01 01:56:46 mayfly.aws-sydney.etaskr.com systemd[1]: Starting Elasticsearch...
Sep 01 01:56:46 mayfly.aws-sydney.etaskr.com systemd[1]: Started Elasticsearch.
Sep 01 01:56:47 mayfly.aws-sydney.etaskr.com elasticsearch[1755]: {1.7.1}: Initialization Failed ...
Sep 01 01:56:47 mayfly.aws-sydney.etaskr.com elasticsearch[1755]: - ElasticsearchIllegalStateException[Failed to created node environment]
Sep 01 01:56:47 mayfly.aws-sydney.etaskr.com elasticsearch[1755]: AccessDeniedException[/var/lib/elasticsearch/elasticsearch/nodes/0]
Sep 01 01:56:47 mayfly.aws-sydney.etaskr.com systemd[1]: elasticsearch.service: main process exited, code=exited, status=3/NOTIMPLEMENTED
Sep 01 01:56:47 mayfly.aws-sydney.etaskr.com systemd[1]: Unit elasticsearch.service entered failed state.
Sep 01 01:59:30 mayfly.aws-sydney.etaskr.com systemd[1]: Starting Elasticsearch...
Sep 01 01:59:30 mayfly.aws-sydney.etaskr.com systemd[1]: Started Elasticsearch.
```

I'd installed ES using this ansible ELK playbook (with some edits to update new repos), but there doesn't seem to be anything in it that might be related to this issue: https://github.com/bakhti/ansible-elk/blob/master/tasks/elasticsearch.yml

**Comment by vacri** [comment]
Closing ticket for now - the ansible playbook has custom config for managing ES. I need to look at that in more detail, sorry.

**Comment by conorsch** [comment]
@vacri Having the same directory mask problem you encountered with bakhti's role, but I'm completely unable to track down where the problem is slipping in. My best guess at this point is something to do with the `monit` service, so I'll try forking and ripping that out. Wouldn't hurt to test OSes other than Debian 8, as well.

**Comment by conorsch** [comment]
Bizarrely, testing in Ubuntu 14.04 rather than Debian 8 fixes the directory mask problem. No clue why that is. Looks like I'm in for some hair-pulling.
