### ISSUE TITLE
Scripts handle newline before a plus sign incorrectly

### ISSUE THREAD

**Issue by steinar** [elastic/elasticsearch#13248]
I would expected the following (unescaped) script to return `3`, but instead `2` is returned:
```
1
+
2
```

It appears everything before `\n+` is ignored. By removing newline before the plus sign, `3` is correctly returned:

```
1 +
2
```

This is undocumented and IMO incorrect behaviour. I assume this changed when we upgraded to *1.7.0*.

```json
"number": "1.7.0",
"build_hash": "929b9739cae115e73c346cb5f9a6f24ba735a743",
"build_timestamp": "2015-07-16T14:31:07Z",
"build_snapshot": false,
"lucene_version": "4.10.4"
```

**Comment by clintongormley** [comment]
@steinar could you tell us what script language you're using and provide a recreation please?

**Comment by steinar** [comment]
This is using the default Groovy language.

Example query which exhibits the described behaviour:
```json
{
  "query": {
    "function_score": {
      "functions": [
        {
          "script_score": {
            "script": "1+2\n+3"
          }
        }
      ],
      "boost_mode": "replace"
    }
  },
  "fields": "_score"
}
```

For the query above, all results have `"score": 3`.

If we remove the newline character `\n`, all documents have `"score": 6`.

**Comment by rjernst** [comment]
I don't think json allows line breaks within strings?

**Comment by rjernst** [comment]
At least not directly like that. I think it needs to be maybe `\\n`?

**Comment by steinar** [comment]
To clarify, the following query correctly returns `"score": 6` since it does not contain `\n<operator>`:
```
{
  "query": {
    "function_score": {
      "functions": [
        {
          "script_score": {
            "script": "\n1+\n2+\n3\n"
          }
        }
      ],
      "boost_mode": "replace"
    }
  },
  "fields": "_score"
}
```

**Comment by clintongormley** [comment]
Groovy doesn't require line terminators, so your script is being parsed as:

    1+2;
    return 3;

A trailing operator indicates that the line continues on the next line.  Alternatively, you can use `\` to indicate that the line continues:

    1+2 \
    +3;
