### ISSUE TITLE
Increasing filter cache size invalidates the cache

### ISSUE THREAD

**Issue by rayward** [elastic/elasticsearch#13261]
We're currently tuning our caches and I've noticed that when we increase it it causes the entire cache to get emptied out.

I would think this would only be necessary if the cache size was reduced, not increased.

This impacts performance of production environments while data gets re-cached again.

**Comment by jpountz** [comment]
@rayward This is true indeed, and necessary since the cache needs to make decisions at creation time based on the total amount of space that is available.

For this reason and a couple others, we removed the ability to configure the cache size in 2.x.
