### ISSUE TITLE
Adding back decommissioned nodes...

### ISSUE THREAD

**Issue by trekr5** [elastic/elasticsearch#13269]
Hello,

I'm hoping that someone can help me...

I've used the following command:- 
        curl -XPUT localhost:9200/_cluster/settings -d '{  "transient" : {        "cluster.routing.allocation.exclude._ip" : "10.0.0.1"
          }
         }'

to decommission a node from a cluster. That went fine with no problems and ES excluded it and didn't put any shards or replicas on it which is the expected behaviour. Cluster health was yellow when node was initially decommissioned and green when it was safe to now terminate the node as all the data had been reallocated.

I now had a need to add back the decommissioned node(what i hadn't terminated) and ran the following (on the next day):-

I've used the following command:- 
        curl -XPUT localhost:9200/_cluster/settings -d '{ "transient" : {
            "cluster.routing.allocation.include._ip" : "10.0.0.1"
           }
          }'

believing that this would add the excluded node back into the cluster and then ES would immediately begin to redistribute the shards and replicas across it. However what happened was that my ES cluster immediately went red, logstash stopped bringing messages through and looking at my cluster through the head plugin, I could see that allocation of shards had completely stopped and that messages had begun queuing in our message manager(Redis).

Can you please tell me what is the correct way to add back a decommissioned node ? 

Many thanks

**Comment by clintongormley** [comment]
Hi @trekr5 

This will do it for you:

    PUT /_cluster/settings
    {
      "transient": {
        "cluster.routing.allocation.exclude._ip": ""
      }
    }
