### ISSUE TITLE
Improve unit test coverage

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13260]
See the following coverage reports:
- Unit tests: http://people.apache.org/~rmuir/es-coverage/unit-tests/
- Integ tests: http://people.apache.org/~rmuir/es-coverage/integ-tests/
- Combined: http://people.apache.org/~rmuir/es-coverage/combined/

Unit tests are in sad shape (48%). We should improve this. Integ tests should be really simple and we should do all the heavy lifting with unit tests so things are easier to debug.

**Comment by rmuir** [comment]
See https://github.com/elastic/elasticsearch/commit/517f00b048cb4446665b3090fa12c7ec670bf6ab for how i generated these. 

Be careful to `clean` in between for now, or you will just keep appending sessions. You will see 4 sessions in the unit and integ reports respectively, thats because i run tests with 4 jvms. You see 8 in combined because it just appended the integ data after running the unit tests. 

In the future we can fix the build to make it a little better, by using separate coverage output files, and 'merge' so you could build all 3 reports with one command. But for now this is how to do it.

**Comment by javanna** [comment]
I think we all agree that we should improve test coverage and write many more unit tests. We've been doing that for a while and things have improved already quite a bit, yet there's always a lot to be done on this matter. Does it still make sense to keep this issue open? Seems like this is a common goal to keep in mind with each single PR that we open, nothing concrete that can be done at the moment to close this issue.

**Comment by s1monw** [comment]
any chance to get accurate numbers?

**Comment by javanna** [comment]
you bring up a very valid point, I just noticed that in our TESTING.asciidoc we still refer to maven in the coverage analysis section, I guess that won't work :)

**Comment by cbismuth** [comment]
Seems to be a good starting point for contributing :+1:

**Comment by colings86** [comment]
Assigning this to `:Core/Core` for now as I think there have been discussions there recently about get code coverage numbers

**Comment by danielmitterdorfer** [comment]
I am closing this ticket as it is not actionable as is. If we want to add coverage numbers to our build we should create a new ticket IMHO.
