### ISSUE TITLE
combine different query boost values

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#13272]
With #11744 we made sure that every query in our DSL supports the `boost` and `_name` fields, meaning that those fields always get parsed and applied to the corresponding lucene query (done in the query-refactoring branch). When dealing with a compound query though, there might be multiple boost values specified in the query like in the following case:

```
{
    "filtered" : {
        "query" : {
            "term" : {
                "field" : {
                    "query" : "value",
                    "boost" : 2
                }
            }
        },
        "boost": 3
    }
}
```

The example above contains for instance a single term query, so the final lucene query will simply be a term query (rather than a filtered query), but what should the boost be? At the moment we ignore the main boost (3) and apply 2 only to the resulting query (in master). Note that only a few amount of compound queries are affected by this "problem". For instance the bool query will always create a lucene boolean query, no matter how many clauses there are (even with a single one), so all the potential boost values are preserved and will be handled by lucene when running the query.

The query_string has a similar, yet a bit different behaviour:

```
{
    "query_string" : {
        "query" : "(field1:value1^3 field2:value2^2)^5",
        "boost" : 2
    }
}
```

In the above case we multiply whatever boost comes out of parsing the query string, with the main boost that gets explicitly set.

In the query_refactoring branch, having centralized where the boost gets applied to the final lucene query, we have the chance to standardize what we do in these few cases, while in master we handle it case by case. I can see at least three options:

- keep the inner query boost (even if 1.0 which is the default) and ignore the main one whatever that is
- keep the main boost (only if != 1.0 which is the default?) and ignore the inner one
- combine the two boost values, e.g. multiply them

I am leaning towards the last option to be honest, but I think this is worth some discussion. What do people think about this?

**Comment by rmuir** [comment]
I am a little confused about the example, is it because of the query/filter refactoring for 2.0?

Historically, setting boost on `filtered` should work as lucene's FilteredQuery supported that (and multiplied the boost into the inner weight itself).

But now filtered is really gone, its replaced by BooleanQuery. So IMO that boost on `filtered` should be applied to booleanquery which is the implementation of `filtered`

**Comment by jpountz** [comment]
> The example above contains for instance a single term query, so the final lucene query will simply be a term query (rather than a filtered query), but what should the boost be?

Why wouldn't it be a filtered query? (or rather a boolean query now) This is something that query rewriting will happily simplify when rewriting the query (single-clause boolean queries rewrite to the wrapped clause, and merge boosts by multiplying them) so I don't think we should try to optimize things at parsing time?

**Comment by javanna** [comment]
sorry the main example was around filtered query which is deprecated now, but this is not caused by the filter refactoring, it is not a lucene issue at all, it is something that we do in elasticsearch while parsing queries and converting them back to lucene queries... have a look [here](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/query/FilteredQueryParser.java#L97) for instance. From your answers I would say we should fix the filtered query to always create a boolean query under the hood. That sounds good to me.

query_string seems to behave correctly by manually multiplying the boost parsed from the query and the boost set to the query.

Other cases where we might have a similar problem are wrapper query (available only in the java api),  query filter (deprecated) and template queries. Those are all wrapper for queries, but they do allow to specify a boost (new in query-refactoring branch), so you might end up with the main boost and the boost of the inner query, which will become the actual lucene query. I don't know yet what we should do with those boosts, although I realize that this is an edge case and it doesn't make much sense to set the boost to some wrapper query...

**Comment by rmuir** [comment]
> sorry the main example was around filtered query which is deprecated now, but this is not caused by the filter refactoring, it is not a lucene issue at all, it is something that we do in elasticsearch while parsing queries and converting them back to lucene queries... have a look here for instance. From your answers I would say we should fix the filtered query to always create a boolean query under the hood. That sounds good to me.

ok I get it. Looks like we do a lot of "rewrite()" type logic in the parser itself and it has some bugs where it drops boosts. I just see that as a bug: in general for cases like that, multiply the boosts.

**Comment by jpountz** [comment]
@javanna Can it be closed now that #13312 is merged or is there more stuff to do?

**Comment by javanna** [comment]
@jpountz I have a little more things to do, will close when done

**Comment by javanna** [comment]
We can close this now.
