### ISSUE TITLE
Elasticsearch 2.0.0beta1 does not start if  ES_GC_LOG_FILE value is set in init file.

### ISSUE THREAD

**Issue by ajaybhatnagar** [elastic/elasticsearch#13277]
No logs generated for ES (in Debug mode) or system log. process does not start at all. Commenting the line , elasticsearch starts with no issues. Tried creating directory path and empty file with full permission on gc.log ES_GC_LOG_FILE=/var/log/elasticsearch/gc.log, still unable to start with no error message any where.

**Comment by dakrone** [comment]
@ajaybhatnagar when I specify it on the command line, I get this error:

```
» ES_GC_LOG_FILE=/tmp/foo/gc.log bin/elasticsearch
Invalid file name for use with -Xloggc: Filename can only contain the characters [A-Z][a-z][0-9]-_.%[p|t] but it has been "/tmp/foo/gc.log"
Note %p or %t can only be used once
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Which file are you putting it in? It could be the same error but just not being printed to the right place.

Note that even if I specify a super simple log filename ("foo"), I still get the same error, so I think this is a bug:

```
» ES_GC_LOG_FILE=foo bin/elasticsearch
Invalid file name for use with -Xloggc: Filename can only contain the characters [A-Z][a-z][0-9]-_.%[p|t] but it has been "foo"
Note %p or %t can only be used once
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
