### ISSUE TITLE
Use of queryString in Bool Filter docs

### ISSUE THREAD

**Issue by w33ble** [elastic/elasticsearch#13279]
In the [Bool Filter docs](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-bool-filter.html), the query string parameter is presented as `queryString`, but elsewhere in the docs ([query filter](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-query-filter.html), for example), the parameter is presented as `query_string`. Kibana also uses `query_string` to make sense of the filters.

This page should probably use `query_string` instead.

**Comment by jpountz** [comment]
Fixed via #13281
