### ISSUE TITLE
Searching multiple aliases using wildcard and ignore_unavailable=true throws index closed exception

### ISSUE THREAD

**Issue by bradvido** [elastic/elasticsearch#13278]
Each of my `logstash-YYYY.MM.DD` indices has a filtered alias added to it named `error_messages-YYYY.MM.DD`.  Any that are older than 30 days are closed.

I'm seeing strange behavior when trying to do a match_all query on `error_messages-*`.

This is using the Java  transport client. ES version 1.6.0.
```
SearchResponse sr = client.prepareSearch("error_messages-*")
  .setQuery(QueryBuilders.matchAllQuery())
  .execute().actionGet();
throws:
org.elasticsearch.indices.IndexClosedException: [logstash-2015.07.30] closed
```
So I set `IndicesOptions.lenientExpandOpen()` to ignore unavailable indices and got a different (but similiar) error.
```
SearchResponse sr = client.prepareSearch("error_messages-*")
  .setQuery(QueryBuilders.matchAllQuery())
  .setIndicesOptions(IndicesOptions.lenientExpandOpen())
  .execute().actionGet();
throws:
org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [FORBIDDEN/4/index closed]
```

Interestingly, this query works via HTTP API in Marvel:
```
POST error_messages-*/_search?ignore_unavailable=true
{
  "query": {
    "match_all": {}
  }
}
```

Also interesting is if I use the concrete index pattern `logstash-*`, the queries work in Java.

**Comment by clintongormley** [comment]
@javanna any ideas here?

**Comment by javanna** [comment]
sorry it took me a while to get to this, I confirm it's a bug, we don't look at the state of the aliases although we should after #9057. Need to dig deeper to see if this is a regression or just something that we never really covered.

**Comment by bradvido** [comment]
Nice, thanks for the confirmation

**Comment by oferbar** [comment]
I'm seeing the same issue. When can we expect a fix and in which version of es? (currently on 1.6)
Thx
