### ISSUE TITLE
fail if publish host is set to wildcard address

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13274]
or probably broadcast/multicast/etc.

In the case of wildcard (e.g. 0.0.0.0), this is ok as a *bind_host* for listening only. But for a publish_host these addresses will be problematic. we should just fail.

separately, If you specify `Des.network.bind_host=0.0.0.0` es will seemingly do the semi-right thing and pick a publish host like 127.0.0.1. But this should be special cased as well, because javadocs say (http://docs.oracle.com/javase/7/docs/api/java/net/NetworkInterface.html#getByInetAddress%28java.net.InetAddress%29);
```
If the specified IP address is bound to multiple network interfaces it is not defined which network interface is returned.
```

**Comment by rmuir** [comment]
I think we can do two cases. We can handle `0.0.0.0` just like we handle multiple addresses today, using the same logic we'd use if you picked a hostname that resolved to all the addresses on your machine. we pick by v4/v6 preference, then by reachability. 

For multicast and broadcast we should fail, thats just a misconfiguration.

**Comment by s1monw** [comment]
sounds good to me
