### ISSUE TITLE
Vagrant packaging tests should test uninstall, then reinstall

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#13286]
A user on IRC ran into a problem on debian where after doing an `apt-get purge` of the elasticsearch package, then re-installing it, debian complained loudly about being unable to remove/re-add the "elasticsearch" user.

For our vagrant tests, we already test installing the package, but we should test removing it, then re-installing so we can see these issues as part of packaging bugs.

**Comment by dakrone** [comment]
Here is an example of a failure during packaging: http://pastie.org/private/bhbxkdimbt10wkmed7pfw

**Comment by electrical** [comment]
fyi, i do installs and uninstalls ( purge ) with the puppet module and never ran into this issue.

**Comment by nik9000** [comment]
I can't reproduce the issue either - the `statoverride` thing makes me thing the user is seeing #12189.

**Comment by nik9000** [comment]
But I'll still add purge/reinstall to the tests just to verify that that works. It should and we don't do it in a single test run.
