### ISSUE TITLE
[Docs] Integration Testing Tips / Guidlines

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#13288]
If you are new to Elasticsearch, there are some subtle issues that can trip you up while writing integration tests:
- Need to wait for newly created indices to reach green before indexing/searching
- Should call explicit refresh after indexing but before searching
- DFS might be needed if you are checking scoring order or something similar
- Change cluster name to something unique
- How to completely clear cluster between tests (data, templates, settings, etc)

Probably more that I'm not thinking of.  

It doesn't need to be a large guide, just something that gives tips and explains some common exceptions to faciliate googling upon the page.  E.g. you might get `IndexShardMissingException` and `IllegalIndexShardStateException` if your index isn't green yet.  Without context, these exceptions lead you to much different problems when searching for a resolution (corruption indexes, missing nodes, etc)

I have no idea where this would actually go in the docs.

Issue prompted from a twitter convo: https://twitter.com/frgtn/status/639146742861201408

**Comment by clintongormley** [comment]
@polyfractal in TESTING.asciidoc?

https://github.com/elastic/elasticsearch/blob/master/TESTING.asciidoc

**Comment by janko-m** [comment]
I would also like to add that we've experienced a significant slowdown in our test suite when migrating from 1.4 to 2.4, and setting `index.translog.durability=async` sped up the tests ~3x. So perhaps this setting should be recommended for running tests.

**Comment by debadair** [comment]
[docs issue triage]

**Comment by mark-vieira** [comment]
The TESTING doc mentioned above contains a lot of this kind of information. Given the age of this issue I suspect a lot of these gotchas are either a) addressed in that doc or b) no longer an issue due to other changes in testing methodology/infrastructure in that time. Closing for now in favor of more focused issues to address specific concerns.
