### ISSUE TITLE
Tribe node initialisation issue

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#13292]
If the tribe node has started then sometimes api calls can fail for a while until the tribe node has finally all the information of all the other clusters it has been configured with. This can take a while sometimes.

Concrete scenario:
1) Start cluster
2) Create index and wait for yellow
3) Start cluster
4) Create index and wait for yellow
5) Start tribe node
6) Execute index call. This hangs sometimes, because the tribe node doesn't have collected all the cluster states from the cluster it has been configured with. This can take a while (until a cluster update from one of the cluster it is following comes in).

I think we can improve this by making sure that the cluster states have examined by the tribe node during startup.

**Comment by javanna** [comment]
Tribe node has been deprecated and removed, closing.
