### ISSUE TITLE
Better management of deletion for yellow/red indices

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#13298]
When an index that is red/yellow - perhaps due to the node that holds the other shards having an outage - is deleted we only delete the currently available shards along with the index. However if the missing node comes back we then recover whatever shards existed on it via dangling indices.

It seems that if a user requests an index to be deleted, having those other shards come back is aberrant  behaviour and instead we should make note that some shards are not available, and if/when they come back they are then also deleted (maybe add a timeout value to that as well?).

Sure, the user could turn dangling indices off, but that seems incomplete and still leaves the data on disk when it's obviously not wanted - presuming that node comes back of course.

**Comment by brwe** [comment]
I think this is the same issue as in https://github.com/elastic/elasticsearch/issues/10054 . Having a timeout would be a lot of hassle and seems dangerous to me. 
This should be documented better though.

**Comment by clintongormley** [comment]
The only way we could prevent these indices from being imported would be to remember every index that has ever been deleted in the cluster state, which could very quickly get out of hand.  If you delete an index while nodes are missing, then you should expect some weird behaviour.  ++ to mentioning explicitly in the docs.

**Comment by kkirsche** [comment]
@clintongormley why is that the case? Wouldn't during the connection process the existing cluster(s) state take priority? I would have assumed that the active config and indices would take priority during the sync process and the old indices would be trashed. I understand per @brwe's comment some of the reasoning behind not doing it this way regarding data safety, but why can't this be configurable?

**Comment by clintongormley** [comment]
@kkirsche imagine you start a new node, that didn't have the old cluster state, and it became master.  Any node that joined this new cluster would just delete all the data it had locally (because the new cluster state takes priority).  Instead, we prefer to err on the side of importing old (maybe irrelevant) data and letting the user decide what should be deleted.

**Comment by brwe** [comment]
@abeyad is this fixed by https://github.com/elastic/elasticsearch/pull/18250 ?

**Comment by abeyad** [comment]
@brwe yes, that's correct, the tombstones in the cluster state fixes this

**Comment by brwe** [comment]
Thank you!
