### ISSUE TITLE
Fail quick when executing master level write operations via a tribe node

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#13290]
If a master level write operation is executed via a tribe node then we should fail quick with a descriptive error instead of waiting for the master timeout the expire (1m).

It is clearly documented that master level write operations are not allowed to be executed via a tribe node, but failing how we do currently is not super clear.

Also when indexing into an index that does't exist yet an error is returned when the timeout has expired, which isn't really obvious, especially when you think the index does exist.

**Comment by clintongormley** [comment]
+1

**Comment by javanna** [comment]
Tribe node has been deprecated and removed, closing.
