### ISSUE TITLE
Deleting closed shadow replica index doesnt delete off disk

### ISSUE THREAD

**Issue by natefox** [elastic/elasticsearch#13297]
Using 1.7.1 and shadow replicas. When I close an index that was created with these settings `{"index.shadow_replicas": "true","index.data_path": "/data/es"}` the index and its data is not deleted.
If the index is open, the data is deleted off disk but the top most directory (eg: `/data/es/0/myindex-2015-09-01`) still exists.
Obviously 'normal' indices are completely deleted whether they've been closed or not.
Not sure if this is by design - if so, I think it should be documented.

Full steps taken to reproduce the issue are here: https://gist.github.com/natefox/306c3429825ce5eb182b
I made a Discuss thread here as well: https://discuss.elastic.co/t/deleting-indices-with-shadow-replicas/28261

**Comment by s1monw** [comment]
@dakrone  can you please take a look at this?

**Comment by dakrone** [comment]
@natefox I'm definitely able to reproduce this now, thanks for opening this, I'll take a look!
