### ISSUE TITLE
Unable to delete child documents by query that uses “has_parent”

### ISSUE THREAD

**Issue by ron-totango** [elastic/elasticsearch#13304]
Hi,

I'm using the query below in my search to find all users without parents.
The search works as expected, but delete by query fails with **has_parent] query and filter unsupported in delete_by_query api**

I've searched and it seems that it should be supported.

```
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "user.service_id": "12345"
          }
        },
        {
          "filtered": {
            "filter": {
              "not": {
                "filter": {
                  "has_parent": {
                    "query": {
                      "match_all": {}
                    },
                    "parent_type": "account"
                  }
                }
              }
            }
          }
        }
      ]
    }
  }
}
```

**Comment by martijnvg** [comment]
Parent child queries aren't supported in the delete by query api: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html#limitations

Also the delete by query api has been replaced with the delete-by-query plugin in 2.0:
https://www.elastic.co/blog/core-delete-by-query-is-a-plugin?q=delete%20by%20query
