### ISSUE TITLE
Mention node restart after plugin removal

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#13301]
[Here](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-plugins.html#_removing_plugins) we tell users the command to use to remove a plugin, but we should also mention that *most* plugins also require a restart of the node. Just as we do for the installation part :)

Via [the forums](https://discuss.elastic.co/t/removing-marvel-indices-from-elasticsearch/28488/3).

**Comment by dadoonet** [comment]
Indeed. It makes sense.

Do you plan to send a PR for this Mark?

**Comment by markwalkom** [comment]
Yeah. Just out at the minute :)

**Comment by markwalkom** [comment]
Have the docs changed here, I can't seem to find this any longer in master? (Or am I blind)

**Comment by dadoonet** [comment]
Here for example? 
https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/installation.html

Note that per plugin we already wrote that
https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/cloud-aws.html#cloud-aws-install
