### ISSUE TITLE
What is core/src/main/assemblies/common-bin.xml doing?

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13317]
Is this just dead stuff? what do we need this for. distribution logic is all in distribution/....

At least if we need to keep it for some screwed up reason, can we avoid listing all the dependencies again?

**Comment by dadoonet** [comment]
I probably forgot to remove it.

**Comment by rmuir** [comment]
cool, if we don't need it, lets nuke it. then its one less place when managing dependencies.

**Comment by dadoonet** [comment]
I'll remove it. I think it should be fixed in 2.0, 2.x and master.

**Comment by dadoonet** [comment]
Sounds like https://github.com/elastic/elasticsearch/blob/master/core/src/packaging/common/scripts/postrm does not make sense either...
