### ISSUE TITLE
DiscoveryWithServiceDisruptionsIT frequently hangs completely

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13316]
Looks like this:

HEARTBEAT J3 PID(22805@beast): 2015-09-03T12:01:58, stalled for  891s at: DiscoveryWithServiceDisruptionsIT.testReadOnPostRecoveryShards

Its a big time-waster when trying to get changes in, because it forces me to totally restart mvn verify.

**Comment by brwe** [comment]
I muted the test for now. sorry, I did not get around to it today.
