### ISSUE TITLE
old plugin repos need a note that they have moved into the main ES repo

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13329]
Stuff like https://github.com/elastic/elasticsearch-cloud-aws is confusing, because it doesnt mention that the plugin moved to main ES repository for the 2.0 release. Users only see "master: build from source" and probably think we have done nothing at all.

I think we should have at the very top of the README files for all the plugins we have moved in, some note that points you to their new location for 2.0+

**Comment by dadoonet** [comment]
I agree. I started this for analysis plugins (see https://github.com/elastic/elasticsearch-analysis-phonetic/commit/96bf53cb25c6accde96adc73e0295170d29d9b43) but I still need to do it for other repos...

Thanks for the heads up. Assigning this to me.

**Comment by clintongormley** [comment]
I think we should probably disable github issues on each plugin repo, once the "see core" notice has been added to the README

**Comment by dadoonet** [comment]
@clintongormley It makes sense. I'll do that.

**Comment by dadoonet** [comment]
I updated and disabled issues for:

* https://github.com/elastic/elasticsearch-analysis-icu
* https://github.com/elastic/elasticsearch-analysis-stempel
* https://github.com/elastic/elasticsearch-analysis-kuromoji
* https://github.com/elastic/elasticsearch-analysis-phonetic
* https://github.com/elastic/elasticsearch-analysis-smartcn
* https://github.com/elastic/elasticsearch-lang-javascript
* https://github.com/elastic/elasticsearch-lang-python
* https://github.com/elastic/elasticsearch-lang-groovy (project STOPPED)
* https://github.com/elastic/elasticsearch-lang-mvel (project STOPPED)
* https://github.com/elastic/elasticsearch-river-rabbitmq (project STOPPED)
* https://github.com/elastic/elasticsearch-river-wikipedia (project STOPPED)
* https://github.com/elastic/elasticsearch-river-couchdb (project STOPPED)
* https://github.com/elastic/elasticsearch-river-twitter (project STOPPED)
* https://github.com/elastic/elasticsearch-transport-thrift (project STOPPED)
* https://github.com/elastic/elasticsearch-transport-memcached (project STOPPED)

I did not disable issues when a lot of issues are still opened. We first need to look at them and move them to elasticsearch repo if it makes sense. Only documentation has been updated:

* https://github.com/elastic/elasticsearch-cloud-aws
* https://github.com/elastic/elasticsearch-cloud-gce
* https://github.com/elastic/elasticsearch-cloud-azure
