### ISSUE TITLE
license checker's update adds es jars then gets mad about them later

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13322]
e.g. if i run it for analysis-kuromoji:
```
Adding analysis-kuromoji-3.0.0-SNAPSHOT.jar.sha1
Adding lucene-analyzers-kuromoji-5.4.0-snapshot-1701068.jar.sha1
Deleting lucene-analyzers-kuromoji-5.3.0.jar.sha1
SHAs updated
```
Now it will later fail because of analysis-kuromoji itself... is there something we can improve here?

**Comment by dadoonet** [comment]
Thanks for raising that.

@clintongormley could we use the same ignore option as we have when checking files?
Is it only a documentation issue?

BTW may be we should add a new antrun job to help running that in an easier way than using the command line?

**Comment by clintongormley** [comment]
@rmuir I changed the output which says "run this command to update the SHAs" to include the prefix of jars to ignore, eg in this case it'd be:

    check_license_and_sha.pl --update plugins/analysis-kuromoji/licenses/ plugins/analysis-kuromoji/target/releases/analysis-kuromoji-2.0.0-beta2-SNAPSHOT.zip analysis-kuromoji

**Comment by rmuir** [comment]
thanks!
