### ISSUE TITLE
can't bind to all interfaces with some docker configurations?

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13327]
At least in one of our jenkins servers we have:
```
docker0
        inet 172.17.42.1 netmask:255.255.0.0 broadcast:0.0.0.0 scope:site
        hardware 56:84:7A:FE:97:99
        MULTICAST mtu:1500 index:3
```

Is this normal? The fact it has a broadcast address like that (which looks totally bogus), means that if the user configures 0.0.0.0, we will fail. I can fix the logic to deal with it in several ways (the interface is not marked up, we can not do the check explicitly for a wildcard address) but if anyone understands this I'd love to know why this docker interface looks like that.

**Comment by rmuir** [comment]
Relevant jenkins fail: http://build-us-00.elastic.co/job/es_g1gc_master_metal/16773/

**Comment by drewr** [comment]
It's not only `docker0`, might be an issue with LXC in general. This is on Ubuntu 15.05 Vivid:

```
lxcbr0    Link encap:Ethernet  HWaddr 9e:ee:28:2e:2e:85
          inet addr:10.0.3.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::9cee:28ff:fe2e:2e85/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:371713 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:29988240 (29.9 MB)
```

**Comment by rmuir** [comment]
ok, its just intended as a safety check to prevent the user from making a mistake. I'll remove the broadcast check completely since apparently these containers don't understand how networking works.
