### ISSUE TITLE
Expose lucene FingerprintFilter

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13325]
I felt bad leaving this one out (not adding a factory) in https://github.com/elastic/elasticsearch/pull/13324, but I figure @markharwood probably already has ideas about what he wants to do.

**Comment by markharwood** [comment]
Yep, I'd like to add a factory plus a pre-defined analyzer that chains fingerprint TokenFilter with lowercase, stopword filters etc as per [OpenRefine's fingerprint algo](https://github.com/OpenRefine/OpenRefine/wiki/Clustering-In-Depth)
