### ISSUE TITLE
create a script for lucene snapshot upgrades

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13323]
This is a little painful right now, as far as updating the sha's everywhere etc, which change every lucene snapshot.

I have the feeling it might cause a ton of jenkins fails etc if we don't make it a bit easier. i think it can just be a shell script that runs the correct maven commands (generate distribution/zip with `mvn package`, run license checker update, then for each plugin: generate its zip with `mvn package`, run license checker update), etc.

**Comment by rmuir** [comment]
Now that #13322 is fixed this one should be relatively straightforward. I'll try to look into it if nobody beats me to it.

**Comment by hub-cap** [comment]
This issue will be closed due to inactivity. If you feel it should be reopened, do not hesitate to comment on the issue.
