### ISSUE TITLE
[cloud-aws] signer type option does not work

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13332]
Reported at: 

* https://github.com/elastic/elasticsearch-cloud-aws/issues/242
* https://github.com/elastic/elasticsearch-cloud-aws/issues/223

This option does not work for EC2 like API or S3 like API.

We need to find a way to fix it and also to test it. A simple way for manually testing could be by using Google Storage S3 compatible API: https://cloud.google.com/storage/docs/migrating?hl=en

**Comment by xuzha** [comment]
@dadoonet  could we close this, is there any more work need to be done?

**Comment by dadoonet** [comment]
Sure. Next time in your commit message, add "Closes #XXXX" and Github will close it for you. :)
