### ISSUE TITLE
Problems with Apache reverse proxy and elasticsearch plugins

### ISSUE THREAD

**Issue by dfaropennetwork** [elastic/elasticsearch#13338]
I've problems with mi reverse proxy configuration, i need not open 9200 port to the outside.

I put my apache configuration for the kibana side:

<IfModule mod_proxy.c>

  ProxyRequests On
  ProxyPreserveHost On

/# Redireccion para kibana
  ProxyPass "/logs" http://serverhostname:5601
  ProxyPassReverse "/logs" http://serverhostname:5601

/# Redireccion para elasticsearch

  ProxyPass "/els"  http://serverhostname:9200
  ProxyPassReverse "/els"  http://serverhostname:9200

/# Redireccion para Bigdesk

  ProxyPass "/bigdesk"  http://serverhostname:9200/_plugin/bigdesk *(my problems is here)*
  ProxyPassReverse "/bigdesk" http://serverhostname:9200/_plugin/bigdesk  *(my problems is here)*

</IfModule>

/# Proxy options

<Proxy http://serverhostname:5601>
    Order Allow,Deny
    Allow from all
    AuthType Basic
    AuthName "LogServer"
    AuthUserFile /example/htpasswd.controlusers
    Require valid-user
</Proxy>

<Proxy http://serverhostname:9200>
    Order Allow,Deny
    Allow from all
    AuthType Basic
    AuthName "ELS Server"
    AuthUserFile /example/htpasswd.controlusers
    Require valid-user
</Proxy>

*I sustituded some parameters for the security og my company, don't worry.

When i try to open http://myserver/bigdesk  only works if i put the port :9200 but is just to need exclude, the other locations /els and /logs works correctly.

Thax so much.

**Comment by clintongormley** [comment]
Hi @dfaropennetwork 

Please ask questions like these on the forums instead http://discuss.elastic.co/

You don't actually say what the problem was, but possibly it is something to do with your CORS settings.  See the docs here https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html

**Comment by dfaropennetwork** [comment]
OK thx i'll see the CORS setting.

**Comment by dfaropennetwork** [comment]
Ok i resolved the problem thx so much.

**Comment by michellaporte** [comment]
Hey @dfaropennetwork  What did you do to get this working?
