### ISSUE TITLE
Problem with geo_point and script_fields/fielddata_fields

### ISSUE THREAD

**Issue by clement-tourriere** [elastic/elasticsearch#13340]
Hi,

Using fielddata_fields with geo_point raises an exception when running at least two instances of Elasticsearch.

To reproduce it : 

- run two instances of elasticsearch (on the same machine)
- run the gist : https://gist.github.com/clement-tourriere/8d06a0985f859666ae532
- You maybe need to run the search request twice to see the error

A patch could be : https://gist.github.com/clement-tourriere/2aa7219bd1da96393cbd

For more information, I have create a thread here (with another geo_point problem) : 
https://discuss.elastic.co/t/problems-with-geo-point-type-and-doc-values/28256.

**Comment by eskibars** [comment]
Hi @clement-tourriere the gist you provided in here provides a 404 (looks like you added an extra "2" at the end of the URL).  https://gist.github.com/clement-tourriere/8d06a0985f859666ae53 should be the correct URL. Correct me if I'm wrong here please :)

**Comment by clement-tourriere** [comment]
You're right, the correct link is the one without the '2' at the end. Sorry about that, I thank you for pointing this  out

**Comment by clintongormley** [comment]
Hi @clement-tourriere 

Thanks for the good recreation.  I can confirm that this is still broken in master.  Would you like to send a PR?

**Comment by temsa** [comment]
@clintongormley Would it be possible seeing this patch to land in 1.x ?

Some features just are not there in 2.x and some people, like me, need to keep 1.x while being affected by this bug (in fact it's not exactly the same one, it affect `scripted_fields`, but I do believe this patch fixes it too, for the moment my workaround is far from nice...)

**Comment by n0mer** [comment]
@clintongormley @temsa i'm also having this problem in ES 1.5.2
