### ISSUE TITLE
ES shards red status after old indices removing

### ISSUE THREAD

**Issue by iTonych** [elastic/elasticsearch#13347]
Hi guys. We was removed old indices files and now ES dont work properly.
In ES log we find:
"failed to fetch index version after copying it over"
And we find solution - https://github.com/elastic/elasticsearch/issues/4674
But it didnt helped:)
Some shards are red. Also ES log file growing and growing and growing.
I never worked with ES before and have no idea how to fix it. 
http://localhost:9200/_refresh show
{"_shards":{"total":1192,"successful":1058,"failed":0}}

**Comment by iTonych** [comment]
1.4.0 elasticsearch version 
1.4.2 logstash verison

**Comment by clintongormley** [comment]
Hi @iTonych 

The correct place to ask questions like these is in the forums: https://discuss.elastic.co/

It looks like the index is corrupt.  You should delete it.  Deleting via the API should work but failing that, just delete the shard on disk.  I also recommend upgrading.

**Comment by iTonych** [comment]
Thanks @clintongormley ! It works)
