### ISSUE TITLE
MLT with IDs and Aliases mismatch

### ISSUE THREAD

**Issue by truemped** [elastic/elasticsearch#13348]
Hi,

I have a question that could be a bug but I don't know if I am having the wrong expectation.

Suppose I have the following setup:

    IndexA
        Doc1 {'text': 'lucene beta'}
        Doc2 {'text': 'lucene release'}
    IndexB
        Doc3 {'text': 'elasticsearch beta'}
        Doc4 {'text': 'elasticsearch release'}
    Alias all -> IndexA, IndexB

When I query against the `all` alias like this:

```json
{"query": {"mlt": {"like_text": "lucene beta", "min_term_freq": 1, "min_doc_freq": 2}}}
```
Documents `Doc1`, `Doc2` and `Doc3` are returned. Fine. But when I use the `ids` parameter like this:

```json
{"query": {"mlt": {"ids": ["Doc1"], "min_term_freq": 1, "min_doc_freq": 2}}}
```
only `Doc2` is returned. The same happends when I am searching not with the `all` alias but with `test1,test2` as index.

I then tried to reproduce the issue as a MLT Integration test here: https://github.com/truemped/elasticsearch/commit/ba810e28d0c04d30ae584aa343a633aa730f6d3b which passes. So at this level the query returns both `Doc2` and `Doc3`.

Finally I created this Python script using the ES client that fails on `assert '3' in ids`:

```python
from elasticsearch import Elasticsearch

docs = {'1': {'text': 'lucene beta'},
        '2': {'text': 'lucene release'},
        '3': {'text': 'elasticsearch beta'},
        '4': {'text': 'elasticsearch release'}}

e = Elasticsearch()
index_settings = {'settings': {'number_of_shards': 1, 'number_of_replicas': 0}}

e.indices.delete('test1')
e.indices.delete('test2')

e.indices.create('test1', body=index_settings)
e.indices.create('test2', body=index_settings)
e.indices.put_alias(name='all', index='test1')
e.indices.put_alias(name='all', index='test2')

e.index('test1', 'test', docs['1'], '1')
e.index('test1', 'test', docs['2'], '2')
e.index('test2', 'test', docs['3'], '3')
e.index('test2', 'test', docs['4'], '4')

e.indices.refresh('test1')
e.indices.refresh('test2')

query = {'query': {'mlt': {'like_text': 'lucene beta',
                           'min_doc_freq': 1,
                           'min_term_freq': 1}}}

r = e.search('all', body=query)
ids = [hit['_id'] for hit in r['hits']['hits']]

assert len(ids) == 3
assert sorted(ids) == ['1', '2', '3']

del(query['query']['mlt']['like_text'])
query['query']['mlt']['ids'] = ['1']

r = e.search('all', body=query)
ids = [hit['_id'] for hit in r['hits']['hits']]

assert '3' in ids
assert len(ids) == 2
assert sorted(ids) == ['2', '3']
```

Bug? Or bad expectations? Or a bad test?

Thanks for any feedback. Daniel

**Comment by clintongormley** [comment]
Hiya @truemped 

Bad expectations and thus bad test :) (btw, providing the recreation in curl/sense syntax makes it easier to run).  To explain:

    
    PUT test1
    {
      "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 0
      }
    }
    PUT test2
    {
      "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 0
      }
    }
    
    PUT test1/test/1
    {
      "text": "lucene beta"
    }
    PUT test1/test/2
    {
      "text": "lucene release"
    }
    PUT test2/test/3
    {
      "text": "elasticsearch beta"
    }
    PUT test2/test/4
    {
      "text": "elasticsearch release"
    }
    
    GET test1,test2/_validate/query?explain&rewrite
    {
      "query": {
        "mlt": {
          "like_text": "lucene beta",
          "min_doc_freq": 1,
          "min_term_freq": 1
        }
      }
    }
    
returns:

    "explanations": [
      {
         "index": "test1",
         "valid": true,
         "explanation": "_all:lucene _all:beta"
      },
      {
         "index": "test2",
         "valid": true,
         "explanation": "_all:beta"
      }
    ]

note the use of the `_all` field.

the version with the IDs:

    GET test1,test2/_validate/query?explain&rewrite
    {
      "query": {
        "mlt": {
          "ids": ["1"],
          "min_doc_freq": 1,
          "min_term_freq": 1
        }
      }
    }

returns: 

    "explanations": [
      {
         "index": "test1",
         "valid": true,
         "explanation": "(text:lucene text:beta) -ConstantScore(_uid:test#1)"
      },
      {
         "index": "test2",
         "valid": true,
         "explanation": "() -ConstantScore(_uid:test#1)"
      }
    ]

In other words it tries get document `1` from each index, but `test2` doesn't return a doc and so nothing matches.  The `ids` syntax is deprecated in favour of the multi-get syntax:
    
    GET test1,test2/_validate/query?explain&rewrite
    {
      "query": {
        "mlt": {
          "docs": [
            {
              "_index": "test1",
              "_type": "test",
              "_id": "1"
            }
          ],
          "min_doc_freq": 1,
          "min_term_freq": 1
        }
      }
    }
    
the above request specifies the index and type for the document, so the correct document is used for both indices, returning:

    "explanations": [
      {
         "index": "test1",
         "valid": true,
         "explanation": "(text:lucene text:beta) -ConstantScore(_uid:test#1)"
      },
      {
         "index": "test2",
         "valid": true,
         "explanation": "text:beta -ConstantScore(_uid:test#1)"
      }
    ]

Note: it excludes document `1`, and runs the query on the `text` field, not the `_all` field

**Comment by truemped** [comment]
Hey Clinton,

thanks for the response. I don't really understand the difference between the `ids` and `multi get` query, even though the former one is deprecated now. My understanding of MLT in this case was a two phase algorithm, in which I ask ES to retrieve a certain document, create queries from it and search on the provided indices. Obviously it does so in the `multi get` version so I think this behavior is at least counter intuitive.

In my case for example the software querying ES might not even know in which index the document is stored. My use case for the `ids` or `multi get` is to save round trip time from the client. If I need to know the exact index in which the document is stored, the `ids/multi get` version is pretty useless to me?!

Does that make sense?

**Comment by clintongormley** [comment]
> My use case for the ids or multi get is to save round trip time from the client. If I need to know the exact index in which the document is stored, the ids/multi get version is pretty useless to me?!

get and multi-get don't work on aliases which point to multiple indices.  that's not get.  That's a search.  If you don't know which indices your documents are in, then you need to do a search instead. No way around it.

**Comment by markmacmahon** [comment]
This is an unfortunate limitation of the MLT API as it means that everywhere we store Ids in our system, we also have to store knowledge of the index from which the Id resides.

While this is not a showstopper, it does cause extra complications downstream when we want to things like re-indexing without any downtime.

This approach seems inconsistent with the description of aliases in this part of the [Elasticsearch Documentation](https://www.elastic.co/guide/en/elasticsearch/guide/current/index-aliases.html).

> An index alias is like a shortcut or symbolic link, which can point to one or more indices, 
> and can be used in any API that expects an index name

@clintongormley  Have you got any suggestions on how this could be avoided in an efficient way?

**Comment by clintongormley** [comment]
> This approach seems inconsistent with the description of aliases in this part of the Elasticsearch Documentation.

This limitation is documented here: https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html

> While this is not a showstopper, it does cause extra complications downstream when we want to do things like re-indexing without any downtime.

Actually, reindexing is just fine.  With bulk responses, you get back the original `_index`, `_type`, and `_id` of every document, which you can use when reindexing.

> Have you got any suggestions on how this could be avoided in an efficient way? 

If you don't know what index a document is in, then essentially you have to do a query for that document using the `_id` in a term filter.
