### ISSUE TITLE
Add a "conditional install" option to plugin for easier automation

### ISSUE THREAD

**Issue by morgango** [elastic/elasticsearch#13359]
I have been working with Docker quite a bit lately, and have found that there are some difficulties with using Elastic's commercial plugins within Docker.  Not any technical incompatibilities, per se.  But, here is the issue that comes up because of different operational assumptions.
1. The "[official Elasticsearch image](https://github.com/dockerfile/elasticsearch)" for Docker does not include plugins like Shield, Watcher, or Marvel.
2. Docker expects a single command to be run when a 
3.  You need to install these yourself, not a big deal.  
4. You can do this with a command like:

```
sh -c 'plugin -i elasticsearch/license/latest\
                && plugin -i elasticsearch/shield/latest\
                && plugin -i elasticsearch/marvel/latest\
                && plugin -i elasticsearch/watcher/latest\
                && elasticsearch'
```

Groovy, no problem.

**Except for The Problem**

The issue is that a Docker build will fail if a single command fails.  So, if your plugin command installs the plugins the first time it runs, the next time it runs it will fail, causing the entire build to fail.

What would be great is if there were a conditional installation option where I could try to install a plugin.  Something like:

`bin/plugin --install --conditional elasticsearch/shield/latest`

If the plugin were installed, or up-to-date then there wouldn't be any error thrown and we can continue on our merry way.  No error code returned, just a message to stdout that the plugin is already up-to-date.

BTW, I know that you _can_ create your own Dockerfile that does a lot of this for you with shell scripting logic.  However, the overwhelming majority of users are going to use the stock "official image" and don't want to build it themselves.

**Comment by dadoonet** [comment]
I understand. 

Would it be possible to run something like the following instead? (not tested)

```
sh -c 'plugin -i elasticsearch/license/latest || true \
                && plugin -i elasticsearch/shield/latest || true \
                && plugin -i elasticsearch/marvel/latest || true \
                && plugin -i elasticsearch/watcher/latest || true \
                && elasticsearch'
```

Could this work in your case?

**Comment by nik9000** [comment]
This seems like a fine thing to do. Can we just make plugin WARN if you try to install a plugin you already have?

As a workaround can you try to something like:
```bash
sh -c '(find /usr/share/elasticsearch/plugins | grep license || plugin -i elasticsearch/license/latest)
  & (find /usr/share/elasticsearch/plugins | grep shield || plugin -i elasticsearch/shield/latest) 
  & (find /usr/share/elasticsearch/plugins | grep marvel || plugin -i elasticsearch/marvel/latest) 
  & (find /usr/share/elasticsearch/plugins | grep watcher || plugin -i elasticsearch/watcher/latest)'
```

**Comment by rjernst** [comment]
The plugin cli was reworked a while ago, and since 2.0 plugins must be built for a specific version of elasticsearch.  I don't think this issue is relevant anymore, as plugins must be removed and then reinstalled upon upgrading elasticsearch.
