### ISSUE TITLE
Distance from [lon,lat] to geo_shape

### ISSUE THREAD

**Issue by eskibars** [elastic/elasticsearch#13351]
Currently, we can do distance math for filter (geo_distance) and sort (_geo_distance) from a given [lon,lat] to a geo_point.  We cannot do this currently for a [lon,lat] to the surface of a geo_shape object (distance "N").  There's a bit of a workaround for the geo_distance filter: you can create a circle of a specified radius M and check for an "intersects" relation.  However, there are some cases where this does not work (e.g. if M > (N + [span of geo_shape]) it's now "within").  

A few examples:
- A vehicle is supposed to follow an indexed LineString / MultiLineString path and we want to find when it has deviated from the path by more than 100 meters [filter]
- Find the nearest landmark (geo-shape) to my present location [sort]

**Comment by Ghost93** [comment]
Hi,
any news on this?

We also need ```geo_distance``` to support ```geo_shape``` fields.

**Comment by clintongormley** [comment]
@nknize any thoughts on this?

**Comment by nknize** [comment]
This will likely follow the Lucene 5.5 release which includes the API and performance improvements needed to make this perform at scale.

**Comment by akamanocha** [comment]
+1 for this. I guess es is now on 5.5 any plan to do this. 

Or suggested architecture/ workaround please?

**Comment by imalygin** [comment]
Do you have any updates for this by any chance?

**Comment by jfitz1** [comment]
+1

**Comment by kaxil** [comment]
+1

**Comment by riconegri** [comment]
+1

**Comment by juanpujol** [comment]
👍

**Comment by akamanocha** [comment]
Anything on this?

**Comment by publicaddm** [comment]
+1

**Comment by lukas-gitl** [comment]
+1

**Comment by TomerGold1998** [comment]
+1 any update ??

**Comment by radeno** [comment]
I dont want to be troll but even javascript (i work with it) has awesome library https://github.com/Turfjs/turf but high-scalabe technology doesn't.

**Comment by MGerasimchuk** [comment]
+1

**Comment by christianonrails** [comment]
+1

**Comment by imotov** [comment]
Depends on #32039

**Comment by salvob41** [comment]
Any update on this ?

**Comment by blkbltjns** [comment]
We could really use this as the new BKD index methodology does not work with circles, and intersecting with circles by converting to polygons is wasteful and inaccurate.

**Comment by talevy** [comment]
> and intersecting with circles by converting to polygons is wasteful and inaccurate.

I am not sure this issue is the right place to have this discussion. but could you explain your use-case a bit more and what type of distance queries you are interested in doing?

**Comment by blkbltjns** [comment]
> > and intersecting with circles by converting to polygons is wasteful and inaccurate.
> 
> I am not sure this issue is the right place to have this discussion. but could you explain your use-case a bit more and what type of distance queries you are interested in doing?

Sure, and my apologies if this is the wrong thread for this. My use case is querying for arbitrary shapes at a certain distance from a point. Due to geo_distance only working point-to-point, the workaround way to do this used to intersect a circle shape with the relevant index. However, due to 6.8’s BKD indexing methodology not working with circles and geoshape intersection, I am left with using the deprecated geohash or prefixtree indexing or turning the circles into polygons and intersecting those. Both these workarounds are not good in my opinion, and are really just backwards ways to do a basic distance filter between a point and a shape, which geo_distance currently doesn’t support.
