### ISSUE TITLE
Terms Agg filtering values using array of values works but not documented

### ISSUE THREAD

**Issue by nezda** [elastic/elasticsearch#13352]
#6782 which I think was fixed in 1.5 series is not reflected in the current docs of https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-aggregations-bucket-terms-aggregation.html#_filtering_values.  Could borrow content from https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-facets-terms-facet.html#_excluding_terms

**Comment by clintongormley** [comment]
@markharwood looks like your doc changes in https://github.com/elastic/elasticsearch/pull/7529 got lost somehow?

**Comment by markharwood** [comment]
@clintongormley Don't think I dropped anything here?

The opening paragraph says ` based on regular expression strings or arrays of exact values.`
I'm not sure we need to provide an example of what an array of strings looks like here?

**Comment by nezda** [comment]
Mea culpa - I didn't read text carefully and was looking for the example in separate section from regexes like it was in Facet docs (which I personally prefer).

**Comment by clintongormley** [comment]
@markharwood turns out it was my fault - i removed the example you had from the 1.x docs.  Added back here: https://github.com/elastic/elasticsearch/commit/63f4af5090bd77c77b3cde0bc46df360d88107dc
