### ISSUE TITLE
SearchResponse question

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#13367]
SearchResponse has a method called getTookInMillis()
I'd like to ask how this timecost is calculated?
I mean if it is the timecost between it hits the server and leaves the server with timecost when it is waited in queue if search worker thread is full or only the timecost between query and fetch without queue time?
if it is the later, how to get the complete search timecost?

**Comment by jpountz** [comment]
Please use [the forums](http://discuss.elastic.co) to ask questions.

**Comment by makeyang** [comment]
@jpountz 
as I mentioned in https://github.com/elastic/elasticsearch/issues/13172, I can't visit discuss.elastic.co. before I can, can you help to answer this question?

**Comment by jpountz** [comment]
@makeyang when the coordinating node receives the request, it stores the current timestamp. Later, after the coordinating node got all required data from all shards, it computes the delta between the current timestamp and the start time. So the only things that it does not contain are the time it takes to send the initial request to elasticsearch and serialize the response back to the client.

**Comment by makeyang** [comment]
@jpountz 
thank you very much.
