### ISSUE TITLE
[cloud-aws] Remove duplicated cloud.aws settings

### ISSUE THREAD

**Issue by xuzha** [elastic/elasticsearch#13363]
As we split cloud-aws plugin into two separate plugins, I think we don't need to keep both `cloud.aws` and `cloud.aws.[s3|ec2]` settings in two separate settings.

For example we have both `cloud.aws.protocol` and `cloud.aws.ec2.protocol` for ec2, they are totally same now.

**Comment by dadoonet** [comment]
I don't think so.

From a end user perspective, giving only once my settings should be enough. And it could apply to s3 and ec2 (most of the cases).

But would love to hear also what others think.

**Comment by xuzha** [comment]
Looks like no need to do any change, closing this issue.
