### ISSUE TITLE
number_of_pending_tasks keeps increasing indefinitely

### ISSUE THREAD

**Issue by Unitech** [elastic/elasticsearch#13361]
I had to restart the master elasticsearch, the status was red, then after some time the status went yellow (I guess primary shards went assigned).

Now when I'm doing the query `curl http://x.x.x.x/_cluster/health?pretty` I can see that **the "number_of_pending_tasks" keeps increasing (now it is at 200k)**

I had a look at the pending tasks and I can see that it is mainly this tasks that get buffered:

```
    , {
        "insert_order" : 58176,
        "priority" : "NORMAL",
        "source" : "indices_store",
        "executing" : false,
        "time_in_queue_millis" : 619596,
        "time_in_queue" : "10.3m"
      },
```

In the meantime I get the error about a rejected execution due to the queue capacity:

```
Caused by: org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution (queue capacity 200) on org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler@34c87ed9
```

How can I solve this?

**Comment by bleskes** [comment]
> I had a look at the pending tasks and I can see that it is mainly this tasks that get buffered:

This is the task that gets executed when deleting shard copies that are no longer assigned to the node. Can you check what the currently executing task is? it's marked with `executing: true`. 

Also - what is the max time in queue? are thy all low-ish (10m)?

> In the meantime I get the error about a rejected execution due to the queue capacity:

The task queue is unbound. What operations due you get this error from? by the queue capacity , I would guess that these are indexing requests.

Anything else of interest in the node logs?

**Comment by bleskes** [comment]
and of course, what version of ES are you using?

**Comment by Unitech** [comment]
After that all shards got assigned, 10minutes after the `number_of_pending_tasks` went from 2 millions to around 50k automatically :)

Sometimes using ES without deep knowledge about it can be quite stressful in case of outage, but it so performant!

I'm using elasticsearch 1.6,

I think I can close the issue, thanks for your help

**Comment by bleskes** [comment]
thanks for coming back with the info. If you don't mind I would like to know more- what you describe shouldn't happen under normal circumstances. How many shards & nodes do you have in your cluster? Do you run on local disks or shared file system? I also understand you don't have dedicated master nodes at the moment. Is that correct?

**Comment by iravid** [comment]
Hi @bleskes, I'd like to chime in since I'm seeing the same issue. I'm running a cluster of 5 nodes on AWS, with around 28k shards. We're running on EBS volumes. ES version is 1.5.2.

The issue started after adding the 5th node (due to the shard rebalancing, I assume). During debugging, I noticed that pending tasks rises indefinitely; counting the tasks by type using _cat/pending_tasks resulted in a large number of indices_store tasks. When setting cluster.routing.allocation.cluster_concurrent_rebalance to 0, the tasks quickly disappear (as @Unitech mentioned).

**Comment by Unitech** [comment]
> what you describe shouldn't happen under normal circumstances. 

My setup is one master (with data) and 2 slaves. I've approximately 24k shards.

The ES master was not responding to some queries (/_cat/indices for example). So I stopped the 2 slaves and then I restarted the master. I put back online the 2 slaves and I waited about 2hours but the shard assignement was taking too much time, so I tuned some recovery configuration options and it was faster.

I know I made some mistakes. I then followed this tutorial [Full Cluster restart upgrade](https://www.elastic.co/guide/en/elasticsearch/reference/master/restart-upgrade.html#restart-upgrade)

> How many shards & nodes do you have in your cluster? 

25k

> Do you run on local disks or shared file system?

Local disk on bare metal servers (SSD)

> I also understand you don't have dedicated master nodes at the moment. Is that correct?

Yes I have one dedicated master

**Comment by bleskes** [comment]
@iravid those task are expected. They are the last protection in a set of checks we do before deleting data from disk. More specifically, when a shard is moved from node A to B, node A will not delete it's copy until it get's a confirmation from B and all other nodes that have a copy of the shard (typically, 1 node if you have 1 replica) that they shard is active is OK. I can see how in the case of 25K shards ( a lot for such a small cluster, you should look at reducing this number for other reasons too- it's typically inefficient) these can accumulate when a lot of other things happen (they don't have high priority) but they are really light and the node should process them super quickly.

@Unitech I see thx. there are a couple of issues in your config file (though I don't see yet how it explains what you were seeing).:

1) setting node.master: true , doesn't make a node a dedicated master node. To do so you also need to make the node not hold data by setting node.data: false
2) recovery settings (gateway.recover_after_nodes, gateway.expected_nodes) suggest you expect 1 node, but I think it should be two (or three, depending whether you want data on your master).
3) discovery.zen.ping.timeout: 30s  - why is this so high?
4) discovery.zen.minimum_master_nodes: 1 - this is the default and can be removed (see point about running with one master later on)
5) Unless you had a very reason (which I would be curious to hear), I would remove all the thread pool settings. The default should be good. Also index.store.type: mmapfs can be removed (we have a smart default of using this where it helps).

Last - are you sure you want to run with a single dedicated master? if so, when the master dies, the cluster will not except writes until a new master is brought back to life.
