### ISSUE TITLE
Python Module Access

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13369]
_From @theNewFlesh on February 18, 2015 22:23_

It would great if you could implement either:
1) The ability to specify a Python file (that may import other modules) which is executed with the 
     relevant Elasticsearch variables (doc, _doc, _source, etc) instead of a Python expression.  This will
     involve invoking the exec function instead of the eval function.
OR 
2) Python expressions to have access to modules/objects specified outside of the default Python
    environment.  This will likely mean a configuration option specifying a python function for setting up
    the globals dictionary passed to the eval statement.

_Copied from original issue: elastic/elasticsearch-lang-python#28_

**Comment by clintongormley** [comment]
Given all of the changes that have gone into locking elasticsearch down, this one sounds like a nonstarter.  Closing
