### ISSUE TITLE
Use only one way of specifying routing, version and version_type

### ISSUE THREAD

**Issue by alexksikes** [elastic/elasticsearch#13377]
Today we have a couple of ways of specifying the routing, version, and version
type of a given document request.

Beyond camelCase, we use:

`_routing` or `routing`
`_version` or `version`
`_version_type` or `version_type`

This makes the use of ParseField difficult for these parameters, as the camelCase of say `_routing` isn't `routing`. We should probably settle on using only one, or make ParseField handle this case.

Relates to #8988

**Comment by jpountz** [comment]
> or make ParseField handle this case

Please no. :-)

+1 on settling on just one

**Comment by clintongormley** [comment]
Let's settle on a single form (I don't really care if it is `_foo` or `foo`) and deprecate the other form (with depr logging), but only remote it in 6.0.

**Comment by mariha** [comment]
I was thinking of working on this issues, isn't it already fixed though? https://github.com/elastic/elasticsearch/pull/27040#issuecomment-339733991

**Comment by jpountz** [comment]
Good catch @mariha it has been addressed indeed.
