### ISSUE TITLE
Trying to remove filtering on cluster but isn't working...

### ISSUE THREAD

**Issue by trekr5** [elastic/elasticsearch#13378]
Hi,

I'm seeking assistance with this question.

I'm trying to force shards onto a node but first performed a cluster api settings call with the following response:-

    {"persistent":{},"transient":{"cluster":{"routing":{"allocation":{"require":{"*":" "," *":" "},"exclude":{"_ip":""}, "include":{"_ip":""}}}}}}        

This filtering is preventing the force allocation of shards occurring.

How do I remove filtering from the cluster so that I can now proceed with this operation?

Thanks

**Comment by clintongormley** [comment]
Hi @trekr5 

I'm afraid you're stuck...  Currently there is no way to unset these settings, you have to override them with new settings.  Fortunately, you made them transient settings instead of persistent settings, so a full cluster restart will remove them.
