### ISSUE TITLE
failed action with response of 400, dropping action

### ISSUE THREAD

**Issue by angel-smile** [elastic/elasticsearch#13371]
Hi,

For the following log:

Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None

When I trim ':' with logstash kv filter, the log can be passed to ES, but then the walltime becomes '160000'. 

kv {
          trim => "<>:"
          field_split => " "
          prefix => "job_"
}

If I don't trim ':' I get the following error and the log is dropped. Any idea why this happens? I'm running logstash 1.5.4 and ES 1.4.5 on a CentOS 6.6 server.

{:timestamp=>"2015-09-07T17:33:30.017000+1000", :message=>"failed action with response of 400, dropping action: [\"index\", {:_id=>nil, :_index=>\"logstash-2015.09.07\", :_type=>\"program\", :_routing=>nil}, #<LogStash::Event:0x6af14eac @metadata={\"retry_count\"=>0}, @accessors=#<LogStash::Util::Accessors:0x6ad72e6f @store={\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, @lut={\"[pbs_object_type]\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"pbs_object_type\"], \"pbs_object\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"pbs_object\"], \"tags\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"tags\"], \"[pbs_program]\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"pbs_program\"], \"[message]\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"message\"], \"message\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"message\"], \"job_user\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"job_user\"], \"pbs_user\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"pbs_user\"], \"rnt651@raijin1\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"rnt651@raijin1\"], \"job_cpu_hrs\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"job_cpu_hrs\"], \"job_ncpus\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"job_ncpus\"], \"[type]\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"type\"], \"[program]\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"program\"], \"[tags]\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"tags\"], \"type\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"type\"], \"[syslog_severity]\"=>[{\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, \"syslog_severity\"]}>, @data={\"host\"=>\"r-man2\", \"message\"=>\"Job Start Summary: jobid=2291646.r-man2 project=p08 user=rnt651@raijin1 queue=express-node ncpus=16 mem_requested=8gb walltime=16:00:00 cpu_hrs=768.0 jobfs_local=8gb jobfs_global=None\", \"offset\"=>253322067, \"path\"=>\"/var/spool/PBS/server_logs/20150907\", \"program\"=>\"pbs_server\", \"type\"=>\"program\", \"@version\"=>\"1\", \"@timestamp\"=>\"2015-09-07T07:33:08.000Z\", \"pbs_timestamp\"=>\"09/07/2015 17:33:08\", \"pbs_event_class\"=>\"job\", \"pbs_node\"=>\"Server@r-man2\", \"pbs_object_type\"=>\"job\", \"job_id\"=>\"2291646.r-man2\", \"received_from\"=>\"r-man2\", \"pbs_host\"=>\"r-man2\", \"pbs_program\"=>\"pbs_server\", \"received_at\"=>\"09/07/2015 17:33:08\", \"tags\"=>[\"pbs_production\", \"pbs_job\"], \"job_jobid\"=>\"2291646.r-man2\", \"job_project\"=>\"p08\", \"job_user\"=>\"rnt651@raijin1\", \"job_queue\"=>\"express-node\", \"job_ncpus\"=>16, \"job_mem_requested\"=>\"8gb\", \"job_walltime\"=>\"16:00:00\", \"job_cpu_hrs\"=>768.0, \"job_jobfs_local\"=>\"8gb\", \"job_jobfs_global\"=>\"None\", \"pbs_user\"=>\"rnt651@raijin1\"}, @metadata_accessors=#<LogStash::Util::Accessors:0x2b8f1a3f @store={\"retry_count\"=>0}, @lut={}>, @cancelled=false>]", :level=>:warn}

Any hint is much appreciated.

**Comment by clintongormley** [comment]
Hi @angel-smile 

It sounds like you have a mapping issue somewhere, which should be visible in the elasticsearch log.  That said this doesn't sound like a bug.  You should ask this (with more details, eg the log message) in the forums instead: http://discuss.elastic.co/
