### ISSUE TITLE
CI: BulkIT.testBulkUpdate_largerVolume fails one of its GetRequests

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#13379]
http://build-us-00.elastic.co/job/es_core_2x_strong/28/

The issue is reproducible most of the time running this seed (on osx), further parameters having no influence already removed:

```
mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch:elasticsearch -Dtests.seed=872FF07FDDFBCB -Dtests.class=org.elasticsearch.document.BulkIT -Dtests.method="testBulkUpdate_largerVolume" -Des.logger.level=DEBUG -Des.node.mode=local
```

When not running in `local` mode, this does not occur, also adding `waitForRelocations` makes it vanish, but I am not sure, if this is the underlying issue here.

**Comment by brwe** [comment]
I think this is a bug in `InternalEngine.flush()`. When we flush we call `refresh()` and `translog.commit()` in the wrong order here: https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L759
This leaves a short gap in which we can't get a document from translog and index. 
The test fails reliable for me but when I switch the order it passes.
I will work on a unit test and make a pr.

**Comment by s1monw** [comment]
> I think this is a bug in InternalEngine.flush(). When we flush we call refresh() and translog.commit() in the wrong order here:

whoa!!! good catch we need a get and commit stress test... that reproduces this problem in isolation
