### ISSUE TITLE
Some stats for deleted indices shouldn't be accumulated

### ISSUE THREAD

**Issue by masaruh** [elastic/elasticsearch#13386]
For example, `open_contexts`. When there are open search contexts when an index is being deleted, the count is accumulated in `OldShardsStats` and it keeps growing.
(It looks it's because [freeing context](https://github.com/elastic/elasticsearch/blob/4173b00241cf9522427eeb81e9451619fe334c76/core/src/main/java/org/elasticsearch/search/SearchService.java#L175-L189) is called after [it collects old shard stats](https://github.com/elastic/elasticsearch/blob/8a06fef019a608153cc22b3ba6d29b5943348ead/core/src/main/java/org/elasticsearch/indices/IndicesService.java#L458-L469))

Another example is `current*` in merge stats. If an index is deleted while it's merging segment(s), those stats are accumulated.

I think those point-in-time stats shouldn't be accumulated.

**Comment by ppf2** [comment]
Also, applies to closing indices.  eg. start with a node restarted with no contexts outstanding, create a scroll, close index, reopen index, _stats api will show that contexts are cleared, but node stats api will show that there are still open contexts.
