### ISSUE TITLE
elasticsearch pings other hosts on its own port

### ISSUE THREAD

**Issue by tstibbs** [elastic/elasticsearch#13395]
I have two elasticsearch nodes, one of which is a client node (called `nodeA`, running on `serverA`), and one of which is a master (called `nodeB`, running on `serverB`). NodeA has tcp port `9317` and nodeB uses port `9310`.

I have noticed that when the client node (nodeA) starts up, it tries to contact nodeB, but it uses nodeA's port. This seems very strange to me, just because one node is running on a particular port, why does it assume all other nodes will be? I have checked that the firewall is not blocking any of the pings.

I wouldn't care about this except that the port it's trying to contact is blocked by the firewall, which results in a `NoRouteToHostException`, which appears as a WARN in the log file - having an exception which is 'normal behaviour' makes it harder to spot actual issues when they occur.

-----

nodeA's elasticsearch.yml:

    discovery.zen.ping.unicast.hosts: [serverA, serverB]
    node.master: false
    node.client: true
    transport.tcp.port: 9317

nodeB's elasticsearch.yml:

    discovery.zen.ping.unicast.hosts: [serverA, serverB]
    transport.tcp.port: 9310

extract from my firewall log on serverB demonstrating that it was iptables that blocked the connection from serverA to serverB on port 9317:

    Sep  8 11:34:02 serverB kernel: IPTABLES_REJECT: IN=eth7 OUT= SRC=serverA DST=serverB LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=49165 DF PROTO=TCP SPT=52202 DPT=9317 WINDOW=14600 RES=0x00 SYN URGP=0

This is elasticsearch 1.7.1 running on sun java 1.7.0_67 on CentOS 6.4.

**Comment by clintongormley** [comment]
Hi @tstibbs 

Given that serverA knows nothing about serverB (other than its IP address), why do you think it would try to ping on any port other than the locally configured `transport.tcp.port`?

I think it finally succeeds in connecting thanks to multicast (which you appear not to have disabled).

If you want it to use unicast to connect to a node which is running on a different port, then you should specify the port in the hosts list:

     discovery.zen.ping.unicast.hosts: [serverA:9317, serverB:9310]

**Comment by tstibbs** [comment]
Thanks @clintongormley for the quick response. For some reason I thought that missing out the port in the hosts list caused it to do something like a multicast ping but directed to a specific host. It sounds from your response like missing out the port simply causes it to use the locally-configured port number, is that correct?

**Comment by clintongormley** [comment]
Correct.  I'll close this issue as it seems resolved
