### ISSUE TITLE
[Feature Request] Add NoMatchQuery to support better templating experience

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#13406]
Consider the following query, which is constructed using Mustache on the client side:

```
                            {
                                "bool": {
                                    "minimum_should_match":1,
                                    "should":[
                                        {{#someCondition}}
                                        {"terms": {
                                            "field1": {{vals1}}
                                        }},
                                        {{/someCondition}}
                                        {{#hasIp}}
                                        { "terms": {
                                            "ips": {{ips}}
                                        }}
                                        {{/hasIp}}
                                    ]
                                }
                            }
```

When hasIp && someCondition or !hasIp && !someCondition everything works as expected (because `minimum_number_should_match` causes empty should clause to effectively be a NoMatchQuery). For the case where !hasIp && someCondition, this Mustache template is going to render invalid JSON (trailing comma right before a closing bracket).

A possible solution works something like this:

```
                            {
                                "bool": {
                                    "minimum_should_match":1,
                                    "should":[
                                        {{#someCondition}}
                                        {"terms": {
                                            "field1": {{vals1}}
                                        }},
                                        {{/someCondition}}
                                        {{#hasIp}}
                                        { "terms": {
                                            "ips": {{ips}}
                                        }},
                                        {{/hasIp}}
                                        {"term": {
                                            "emails": "no-such-email:a-match-none-query"
                                        }}
                                    ]
                                }
                            }
```

Adding a query that translates to definitive no-match. It can be domain specific (e.g. looking for inexistent email) or an empty boolean clause that translates to no results.

It will be really useful to have a NoMatchQuery type to complement MatchAllQuery, this will allow writing templates like the one above much easier, and without resorting to query types that actually cost in index lookups.

As always, I'll be happy to provide a PR once all required details have been agreed upon.

**Comment by synhershko** [comment]
@eskibars this is not just a search templates requirement  - it's a general one related to the query DSL, although our use case is as described

**Comment by eskibars** [comment]
@synhershko fair enough although I can't think of any real use case outside of templating

**Comment by synhershko** [comment]
A no-op query for example - it will be more syntactically correct to issue one with NoMatchQuery than with a hack build around boolean should's.

A no-op query is sometimes needed when you have no way in your system to avoid the query but need no results back.

**Comment by javanna** [comment]
heads up, while working on refactoring queries so that we can parse them on the coordinating node and stream them to the data nodes, the same requirement came up internally. We went ahead and added the `match_none` query then. It is currently in the query-refactoring branch which will be merged to master soon. That means that elasticsearch 3.0 will include this query.

**Comment by synhershko** [comment]
@javanna hurray! any chance for backporting this to ES 2.0 GA ? :)

**Comment by s1monw** [comment]
@synhershko 2.0 GA is frozen

**Comment by synhershko** [comment]
Ok, back-porting this to 2.x will be highly appreciated

**Comment by clintongormley** [comment]
@synhershko why not just replace:

    {{#hasIp}}
    { "terms": { "ips": {{ips}}}},
    {{/hasIp}}

with:

    { "terms": { "ips": {{ips}}}},


Any empty terms list acts as a no-match query already

I don't think there is any more to do here, so closing
