### ISSUE TITLE
Remove intellij jar hell leniency

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13404]
Its confusing to people that we are lenient to jar hell when running under intellij: thats totally an intellij bug, but by allowing it, people think that jar hell check is "optional" or that we don't execute it in tests, which we totally do in maven and jenkins.

This leniency needs to be removed.

**Comment by s1monw** [comment]
+1 I think it makes sense to run tests in IDEs the same way as we run in maven. I will try to figure out how to fix intellij and post a guide here.

**Comment by mikemccand** [comment]
+1

**Comment by rjernst** [comment]
+1

**Comment by s1monw** [comment]
running this patch with IntelliJ 14 passes without a jarhell. 
```patch
diff --git a/core/src/test/java/org/elasticsearch/bootstrap/BootstrapForTesting.java b/core/src/test/java/org/elasticsearch/bootstrap/BootstrapForTesting.java
index a7b9043..d942cc2 100644
--- a/core/src/test/java/org/elasticsearch/bootstrap/BootstrapForTesting.java
+++ b/core/src/test/java/org/elasticsearch/bootstrap/BootstrapForTesting.java
@@ -61,13 +61,7 @@ public class BootstrapForTesting {
         try {
             JarHell.checkJarHell();
         } catch (Exception e) {
-            if (Boolean.parseBoolean(System.getProperty("tests.maven"))) {
-                throw new RuntimeException("found jar hell in test classpath", e);
-            } else {
-                Loggers.getLogger(BootstrapForTesting.class)
-                    .warn("Your ide or custom test runner has jar hell issues, " +
-                          "you might want to look into that", e);
-            }
+            throw new RuntimeException("found jar hell in test classpath", e);
         }
```

I think we are good to go

**Comment by davireis** [comment]
Is there a way to disable the jar hell check? I am using elasticsearch with several other libraries, and there are no simple solutions to completely get rid of jar hell in all my dependencies.  It seems that the way things are implemented, I can't even swallow the exception and move along.

**Comment by rmuir** [comment]
No.
