### ISSUE TITLE
Windows service doesn't stop properly

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch#13401]
After addressing the issues in #13247 and getting the service to start.  Stopping the service in 2.x/master no longer works either and fails with the following error:

```
2015-09-08 09:38:56 Commons Daemon procrun stderr initialized
java.lang.NoSuchMethodError: close
```

[Apache Commons Daemon procrun](http://commons.apache.org/proper/commons-daemon/procrun.html) requires a stop method (`--StopMethod`), [which use to exist](https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/bootstrap/Elasticsearch.java#L27) but has been removed.

Can this be added back?

**Comment by rmuir** [comment]
I think its fine, as long as we add comments about how its used? There were tons of methods like this in bootstrap: I probably removed a bunch of them. Technically, this one just needs to call Bootstrap.INSTANCE.stop() I think.

**Comment by gmarz** [comment]
Thanks @rmuir, I've updated #13398 to include this as well.
