### ISSUE TITLE
org.apache.lucene.util missing from elasticsearch-2.0.0.beta1 jar

### ISSUE THREAD

**Issue by fakeh** [elastic/elasticsearch#13415]
Hi,
I'm not sure what the intention is regarding wrapping Lucene packages, but the util package (at least?), which is used by Environment is missing from the jar.
Best, Dan.

**Comment by dadoonet** [comment]
I don't understand. 

Environment class uses `org.apache.lucene.util.Constants` which is part of Lucene core.

In which context are you seeing an error? Can you describe what you are doing?

**Comment by fakeh** [comment]
Hi dadoonet, 
elasticsearch-2.0.0-beta1.jar shades most of the packages from org.apache.lucence except util. Since Environment references Constants, the ES jar is insufficient on its own to deploy (so what's the point in shading the Lucene dependencies?).

Specifically, I'm trying to load the ES Java client in Karaf 4.0.1 (an OSGi container) and am encountering:
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.env.Environment
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareSettings(InternalSettingsPreparer.java:97)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareSettings(InternalSettingsPreparer.java:70)
	at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:114)

I hoped that it was because Environment wasn't able to load the Constants class, which it references statically, but even after providing the util package the class still does not load.

Best, Dan.

**Comment by dadoonet** [comment]
Are you using the shaded version of elasticsearch 2.0.0-beta1? What is exactly your dependency?

Note that we won't provide a shaded version anymore in 2.0.0: https://github.com/elastic/elasticsearch/pull/13252

**Comment by fakeh** [comment]
I wasn't aware there was an unshaded version. From Maven Central, as per the blog about the beta:

		<dependency>
			<groupId>org.elasticsearch</groupId>
			<artifactId>elasticsearch</artifactId>
			<version>2.0.0-beta1</version>
		</dependency>

If you're not shading future releases then this issue shouldn't continue to be a problem :) If I can't figure out this NoClassDefFoundError then I'll make a separate issue.

Do you have some documentation of the dependencies? There's rather a lot of them and when constructing an OSGi environment it can be painful to figure out which are required and which are optional.

PS hopefully the ServiceMix wizards will pick up ES 2.0.0 ASAP!

Best, Dan.

**Comment by dadoonet** [comment]
The version you are using is not the shaded version. So it should work fine. I think you have another issue here.

**Comment by fakeh** [comment]
Here's the jar in central: http://search.maven.org/remotecontent?filepath=org/elasticsearch/elasticsearch/2.0.0-beta1/elasticsearch-2.0.0-beta1.jar 

It's got org.apache.lucene (except util) and joda.time packages in it.

Dan

**Comment by dadoonet** [comment]
I understand now what you are saying. This won't change in 2.0.0.

Yes we have specific versions of some Lucene classes in our repository.
But you still need to add Lucene and other dependencies by yourself.

If you are using maven, depending on elasticsearch-2.0.0-beta1 should pull lucene-core where the class you are looking for is located.

I think your classpath is incorrect here.

I don't see that as an issue on our side.

**Comment by fakeh** [comment]
As I said initially, I'm not sure of your intentions regarding bundling these packages. I wonder why it's beneficial to have specific packages included if the resultant jar is not then independent from requiring the source jars in addition?

```I think your classpath is incorrect here.```

Absolutely. But I do think that Elastic are in the best position to help issues when moving from Maven dependency resolution to other systems (production, CI, etc).

PS Is there some other meaning of shading packages, hence our confusion?

**Comment by dadoonet** [comment]
> PS Is there some other meaning of shading packages, hence our confusion?

We used to shade some dependencies such as JODA, guava, jackson... and relocate all packages.
That's what we call "shading".

> But I do think that Elastic are in the best position to help issues when moving from Maven dependency resolution to other systems (production, CI, etc).

I'd like to understand what the fix would look like for you. Is there anything wrong with OSGi if a project has classes located either in org.apache.lucene and ore.elasticsearch?
Do we need to add any META information?

**Comment by fakeh** [comment]
> I'd like to understand what the fix would look like for you.

Ideally, ES would be built with OSGi manifest headers from source! This isn't terribly hard as part of the bundle's release cycle but does require some understanding of tooling and some testing, but can be burdensome for us third parties to keep up with releases, reorganising the jars and make some assumptions and guesses about the original intention of the library's organisation. ServiceMix has been doing this for you for [some time](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.apache.servicemix.bundles%22%20AND%20a%3A%22org.apache.servicemix.bundles.elasticsearch%22) and looking at their POMs would be a great place to start if you were to take this route.

In lieu of OSGi support at source, I would recommend not including third party libraries within your jars at all giving us the flexibility to supply our own versions via OSGi resolution.

> Is there anything wrong with OSGi if a project has classes located either in org.apache.lucene and ore.elasticsearch?

Whilst it is not an insurmountable problem, having resolution of some org.apache.lucene packages within the jar and some without just seems conceptually weird given that the one(s?) without are still required.

More generally, keeping the dependencies minimal would be appreciated, perhaps by splitting ES into sub-functionalities?

I'm in a rush to be elsewhere so this isn't a super-informative post, but if you're interested in more I can try to be of help again later.

Best, Dan.

**Comment by rmuir** [comment]
-1 to OSGI. I don't even need to explain why.

**Comment by fakeh** [comment]
> -1 to OSGI. I don't even need to explain why.
I think this issue has become a bit side-tracked with OSGi's involvement. The more general question, I think, is whether to include lucene's .util or not.
I would, as above, love to see ES distribute OSGi compatible libraries, but it wasn't the original intent of the issue.

Dan.

**Comment by dadoonet** [comment]
lucene .util package is available in lucene core lib as far as I know. You should add it as a dependency in your project.

If it's not possible, then I think you have no other choice to shade yourself elasticsearch and its dependencies within the same final jar as it was done by ServiceMix if I read correctly their pom file.

I documented in the issue (https://github.com/elastic/elasticsearch/pull/13252) how to do that.

Back to the original question: we are not going to include lucene .util in elasticsearch jar.

Closing. But feel free to add other comments here or on discuss.elastic.co where other members of the community could also share other solutions/ideas around that.

**Comment by fakeh** [comment]
Having explored more, I see that you're not selecting packages to include, but using the class path to allow you to override individual classes in Lucene and in Joda.

At least that's that question answered.
