### ISSUE TITLE
Get count of values of field.

### ISSUE THREAD

**Issue by rakesh91** [elastic/elasticsearch#13419]
I want to get the count of the values for a given field. Assuming I have logs index, and  field "response_code" will have different values 200,404,502,503. Is there a way to get the number of values for response_code, i.e. a query which will say 4 different values for response_code.

Thank you

**Comment by eskibars** [comment]
I believe what you're looking for is the [cardinality aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html).  Does that get you what you're looking for?

**Comment by rakesh91** [comment]
@eskibars Thanks a lot. I was looking for the same.
