### ISSUE TITLE
Provide the ability to search an index in the context of another

### ISSUE THREAD

**Issue by gingerwizard** [elastic/elasticsearch#13427]
Proposing providing the ability to specify a list of indexes to search, but use the term weights from only one - similar to how cross fields blends weights.

This may have applications in multi language search, where the requirement is to return mixed language results (each doc is only 1 language) i.e. the user doesn't specify a language.  This typically results in poor quality results, as TF-IDF favours the where the language terms are rare.

This feature may have other applications beyond languages.  I appreciate this has challenges aligning token streams due to some terms not appearing in all indexes and being stemmed differently.  Possibly provide different blending mechanisms.

@markharwood @polyfractal may have additional thoughts.

**Comment by markharwood** [comment]
Would [DFS Query then fetch](https://www.elastic.co/blog/understanding-query-then-fetch-vs-dfs-query-then-fetch) search mode provide what is required?

**Comment by clintongormley** [comment]
Given the esoteric nature of this request, and the fact that it hasn't garnered any interest so far, I'm going to close this issue for now.
