### ISSUE TITLE
Remove GeoDistanceQuery in preference to GeoDistanceRangeQuery

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#13423]
Today we have GeoDistanceRangeQuery which allows you to define a from and to distance away from a point to match documents. We also have GeoDistanceQuery which does exactly the same thing except the from is fixed to 0. This is confusing as we have two query type which do almost the same thing and are easily confused.

I think we should remove GeoDistanceQuery since it is the only range query we have (correct me if I am wrong) where we have a special veriant for fixing one end of the range. I think over time we should then rename GeoDistanceRangeQuery to GeoDistanceQuery.

**Comment by nknize** [comment]
We went the other way and removed `geo_distance_range` query in https://github.com/elastic/elasticsearch/pull/22835.  Closing
