### ISSUE TITLE
ask a node to move all its shards away

### ISSUE THREAD

**Issue by jpparis-orange** [elastic/elasticsearch#13453]
In planned maintenance, I have to remove a node from my cluster. If I have replica at least 1 for all my indices, no problem. But without replica, it could be interesting to instruct a node that it should move away all the shards it stores. With this functionality, I just have to wait that the shards move on another node, and then I can safely remove the node.

**Comment by bleskes** [comment]
Heya,

You can use the exclude option of the [shard allocation filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-allocation.html#shard-allocation-filtering) to move the shards away (using the node name or an IP).

I'm closing the issue as I think this covers your request. Feel free to open if it doesn't.

**Comment by jpparis-orange** [comment]
Yeah! Will take a look at it in the next week!
I'll also have to RTFM a bit more ;-)
