### ISSUE TITLE
[test] plugins simple RestIT tests don't work from IDE

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13479]
When running a RestIT test from the IDE, you actually start an internal node with many mock plugins.

But REST test suite for cloud plugins basically checks if the plugin is running by checking the output of NodesInfo API.

And we check:

```yml
    - match:  { nodes.$master.plugins.0.name: cloud-azure  }
    - match:  { nodes.$master.plugins.0.jvm: true  }
```

But in that case, this condition is certainly false as we started also `mock-transport-service`, `mock-index-store`, `mock-engine-factory`, `node-mocks`, `asserting-local-transport`, `mock-search-service`.

Also, for all plugin Rest tests we are missing the fact we need to load the plugin when running from the IDE:

```java
    @Override
    protected Collection<Class<? extends Plugin>> nodePlugins() {
        return Collections.singletonList(PLUGIN_HERE.class);
    }
```

Everything works fine when running from maven because each test basically:

* installs elasticsearch
* installs one plugin
* starts elasticsearch with this plugin loaded
* runs the test

**Comment by rjernst** [comment]
AFAIK these were never intended to run from the IDE. These are integration tests that run against a real cluster, not like the integ tests that the RestTestCase class is based on. To run these integration tests, you must use an external cluster.

**Comment by dadoonet** [comment]
That's easy to fix though and the PR is almost ready.

But if what you said is true, then we don't need to make RESTtest depends on ESIntegTestCase IMO.

**Comment by rjernst** [comment]
The integ tests use the rest test framework, as it already existed. If we want to refactor it so that when run within core it still gets an integ cluster, and everywhere else it uses an external cluster, great!
