### ISSUE TITLE
Add backwards compatibility test for index failed stats

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#13474]
We added index failed stats in #13130 but didn't add any backwards compatibility tests because the backwards compatibility tests were broken (#13425). Once they are fixed we should add one for index failed stats.

**Comment by andrestc** [comment]
I have something already started for this, waiting on #13425 so I can try and submit the PR

**Comment by nik9000** [comment]
> I have something already started for this, waiting on #13425 so I can try and submit the PR

Cool! I'll get back to the backwards compatibility tests ASAP. They are mind numbing because they take sooooo long to fail. I'm to the point where I'm just going to make the failing ones as `@AwaitsFix` and move on. At least that way you'll be able to start on this.

**Comment by nik9000** [comment]
We've lived without these for a long time, I think we're safe closing this. If anyone is interested in doing this feel free to have another look!

The backwards compatibility tests have changed a *ton* since this was written.
