### ISSUE TITLE
Unable to start elastic search in RHEL 7

### ISSUE THREAD

**Issue by PandiyanCool** [elastic/elasticsearch#13473]
I have installed JDK and also elastic search 1.4.5.

when I tried to start it using 'sudo systemctl start elasticsearch.service' I faced the below error.

>elasticsearch.service - Starts and stops a single elasticsearch instance on this system
>   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled)
>   Active: failed (Result: exit-code) since Thu 2015-09-10 09:51:13 EDT; 8s ago
>     Docs: http://www.elasticsearch.org
>  Process: 2456 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -d -p >/var/run/elasticsearch/elasticsearch.pid -Des.default.config=$CONF_FILE ->Des.default.path.home=$ES_HOME -Des.default.path.logs=$LOG_DIR ->Des.default.path.data=$DATA_DIR -Des.default.path.work=$WORK_DIR ->Des.default.path.conf=$CONF_DIR (code=exited, status=1/FAILURE)

Helps much appreciated :)

**Comment by eskibars** [comment]
You're going to want to have a look at the LOG_DIR ([defaults to /var/log/elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-service.html)) for information.  You may need to bump up your [logging level](https://www.elastic.co/guide/en/elasticsearch/guide/current/logging.html) temporarily

**Comment by eskibars** [comment]
Also, I'm going to insert a plug for https://discuss.elastic.co/ here :smile: It's where general questions/help are provided (we largely use github for specific bugs and feature requests)

**Comment by eskibars** [comment]
I'm going to go ahead and close this issue at this time.  If you still think there's a bug after talking through the forums, please reopen it!

**Comment by PandiyanCool** [comment]
sure thanks
