### ISSUE TITLE
[test] RoutingServiceTests.testDelayedUnassignedScheduleReroute fails every second day or so

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#13485]
Last failure here: http://build-us-00.elastic.co/job/es_core_master_oracle_6/2285/consoleText
Does not reproduce for me.

**Comment by dakrone** [comment]
I pushed additional logging for this as I was unable to reproduce it, hopefully if it fails again I can determine why.

**Comment by dakrone** [comment]
Another failure with the extra logging here: http://build-us-00.elastic.co/job/es_g1gc_master_metal/17107/consoleText I'll look into it.

**Comment by s1monw** [comment]
fixed by https://github.com/elastic/elasticsearch/commit/5098dcaf96744fbc9f1ae5179e530453e9654de0
