### ISSUE TITLE
Backwards compatibility tests should be run with the security manager

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#13484]
Right now the backwards compatibility tests disable the security manager entirely or the external nodes won't run. We should fix that.

**Comment by rmuir** [comment]
I know these tests want to execute which is not an option for any code. I suggest a different approach: https://github.com/elastic/elasticsearch/issues/13216

**Comment by nik9000** [comment]
I've resolved this particular issue using a service that runs inside maven to do the forking. I've started using #13216 to collect all issues and ideas for improvement for the backwards tests. I believe that the backwards tests need to be able to fork so they can perform rolling restarts. The tests could really do more but I'm collecting those things in #13216.

**Comment by clintongormley** [comment]
@nik9000 sounds like this one can be closed?
