### ISSUE TITLE
[test] IndicesSegmentsRequestTests.testVerbose failure 

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#13483]
It is a very short test so there is not much to say: IndicesSegmentResponse misses a result.
http://build-us-00.elastic.co/job/es_core_master_regression/3241/consoleText
This one actually reproduces every 5th run or so!

**Comment by dakrone** [comment]
This one is still failing, see: http://build-us-00.elastic.co/job/es_core_2x_metal/343/consoleText

@rjernst I believe you added the verbose segments API? Can you take a look?

**Comment by rjernst** [comment]
This was fixed a while ago:
18ffb63
