### ISSUE TITLE
How to index heterogeneous JSON Array as value in Elastic Search

### ISSUE THREAD

**Issue by abtpst** [elastic/elasticsearch#13499]
Can Elastic search index fields like

"key": [
            14.0,
            "somestring"
        ]

if i try to ingest this data, i get this error
org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: Found unrecoverable error [Bad Request(400) - [WriteFailureException; nested: MapperParsingException[failed to parse [FIXMessage.key]]; nested: NumberFormatException[For input string: "somestring"]; ]]; Bailing out..

Please also refer to 

http://stackoverflow.com/questions/32513043/elastic-search-json-stringjsonobject-indexing/32514161#32514161

**Comment by dadoonet** [comment]
No. If a field is mapped as a number, you can not write a String in it.

Please ask questions on discuss.elastic.co.
