### ISSUE TITLE
[ec2/azure] discovery does not work anymore from 2.0.0-beta1

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13492]
Discovery does not work anymore in azure and ec2.

It's caused by the following commit which does not call anymore `addUnicastHostProvider`.

* AWS: https://github.com/elastic/elasticsearch/commit/40f119d85a4eaa39d0a6e594e46f70de725557f0#diff-767ee396aa86de938ebb72b4c2f359a0L35
* Azure: https://github.com/elastic/elasticsearch/commit/40f119d85a4eaa39d0a6e594e46f70de725557f0#diff-56a7239bf69dfcd365858d333edca510L43

@rjernst Could you have a look at it please?

cc @drewr

**Comment by rjernst** [comment]
This should be simple to fix. The `onModule(DiscoveryModule)` methods in the aws and azure plugins just need to add the provider there (the discovery module has this method now). This is what I intended, but missed it since all tests pass without this! We really need some tests here...

**Comment by rmuir** [comment]
I still think some mocks for integs that listen on a socket is the way to go. means something on a socket in pre-integration-test and the code really treats it like AWS X service or azure Y service.

**Comment by dadoonet** [comment]
Definitely. I started playing with [this lib](https://github.com/treelogic-swe/aws-mock) (running that in a Jetty container to simulate AWS calls). Was working fine at the beginning but at the end I was missing some important methods.
I started to contribute a bit but then started something else...

**Comment by dadoonet** [comment]
Reopening as the fix for Azure was wrong. 
Reverted with https://github.com/elastic/elasticsearch/commit/163c34127f877c70a0cb5bf95c64c6efada484eb
Tests are now failing.
