### ISSUE TITLE
Run Vagrant tests on OpenSUSE 13.2

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#13507]
Since OpenSUSE 13.2 is officially supported we should run the Vagrant tests on it

**Comment by nik9000** [comment]
We almost certainly should have it in the list but I couldn't find an opensuse box in vagrant atlas that I trusted.

**Comment by tlrx** [comment]
Yes, I saw your comment in TESTING.asciidoc after. I just keep this issue as a reminder
