### ISSUE TITLE
Random free text search from a collection from multiple fields Elastic Search

### ISSUE THREAD

**Issue by abhaygarg** [elastic/elasticsearch#13513]
we are using Elastic Search , MongoDB , mongoosastic

suppose
User:{
username:String,
city : String,
country:String 
 etc 
}
this type of document stores in Elastic Search , now if user search abhay sikandrabad then first it try to find abhay and sikandrabad both. abhay,sikandrabad may be present in any of these thing username , city , country . So basically it search from every fields and if it didnot match then try to match abhay and if data with abhay not found then try to find sikandrabad

Is this type of things already implement in Elastic Search or I have to code for this ?

**Comment by jpountz** [comment]
This is mostly what will happen if you search on the `_all` field with a higher boost on `abhay` than `sikandrabad`. Please use [the forums](http://discuss.elastic.co) for questions in the future, github issues are for bugs and feature requests.
