### ISSUE TITLE
How to ignore a filed in elastic search mapping

### ISSUE THREAD

**Issue by abtpst** [elastic/elasticsearch#13516]
Hello,

In my data, i want to ignore a field. How should i create a mapping for this? For example,

{
   "key1":"value1",

   "key2":"value2"
}

i want to ignore key2, so how should i create my mapping?

thanks

**Comment by eskibars** [comment]
It depends on what you mean by "ignore," but your question will likely be answered on the [core types](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-core-types.html) reference docs.  For example:

* You can add `"store":false` to the key2 mapping to not store it in the index
* You can add `"include_in_all":false` to the key2 mapping to make it not included in the `_all` field (which means it won't be included in a text search unless you search explicitly on the key2 field)
* You can set `"index":"no"` to the key2 mapping to make it not searchable at all

FYI, we have a [great discussion forum](https://discuss.elastic.co/c/elasticsearch) where questions like these can be asked!

**Comment by abtpst** [comment]
thanks, i tried to include everything like
"key2":{
                     "type" : "object",
                      "enabled" : false,
                       "store":false,
                       "include_in_all":false,
                       "index":"no"
}

but still, when i try to ingest the data,, it is not ignored. i will post the question on the forum as well.

thanks

**Comment by eskibars** [comment]
Discussion continued [here](https://discuss.elastic.co/t/elastic-search-how-to-ignore-a-field-in-mapping/29145/2) for anybody that wants to track this.  It looks like a relatively simple misconfiguration at this time
