### ISSUE TITLE
Document the meanings of the field_value_factor modifiers

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#13511]
This was brought up on a discuss post: https://discuss.elastic.co/t/need-definition-of-log1p-log2p-ln1p-and-ln2p-of-field-value-factor-modifier/29101

The documentation on the modifier parameter for the field_value_factor says:
```
Modifier to apply to the field value, can be one of: none, log, log1p, log2p, ln, ln1p, ln2p, square, sqrt, or reciprocal. Defaults to none.
```

While this state what the valid values are it is not so helpful since it doesn't define what mathematical operations they map to. Specifically the `log*` options should be explicitly defined

**Comment by jpountz** [comment]
I'd also be interested to know what benefits it brings compared to using a plain script. I guess the motivation was speed, but now that we support lucene expressions, maybe this is a more flexible option that is equally fast?

**Comment by nik9000** [comment]
> I'd also be interested to know what benefits it brings compared to using a plain script. I guess the motivation was speed, but now that we support lucene expressions, maybe this is a more flexible option that is equally fast?

+1

We should probably test it and see but if they are fast enough we should deprecate them in 2.0 and just consider them a stopgap between groovy and expressions?

**Comment by jpountz** [comment]
+1 sounds like a plan

**Comment by raphi** [comment]
+1
