### ISSUE TITLE
Add disk used by ES to _cat/allocation

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#13529]
Currently disk.used in cat/allocation shows the full disk usage on the node (including non-ES usage).  It will be helpful to add another column that shows disk usage by ES on the node (eg. adding up disk usage by ES indices, translogs and state files, etc.., or even just disk usage by ES indices on the node will be nice too)

**Comment by clintongormley** [comment]
I wonder how heavy this would be to calcuate?

**Comment by bleskes** [comment]
I think pius means the store section of the nodes stats

**Comment by ppf2** [comment]
Yes, we have users getting confused when looking at disk.used and not realizing that it includes non-ES usage (even though it is documented in the ?help of the api call).  If it is easy to get to the store section of node stats and show that as well it will be helpful.

**Comment by clintongormley** [comment]
ah ok, sure, let's add it

**Comment by inqueue** [comment]
I was confused by disk.used until I found this issue. Can we also document field descriptions? Perhaps that should be a separate enh request.
