### ISSUE TITLE
Documentation does not specify whether "_cache" option is valid

### ISSUE THREAD

**Issue by mjohnst** [elastic/elasticsearch#13528]
For the `exists` and `missing` filters, the documentation mentions
> The result of the filter is always cached.

It does not mention that providing a `_cache` option will result in a failure.
The documentation should specify (like `has_child` and `has_parent` do):
>  The _cache and _cache_key options are a no-op in this filter.

For the following filters, I am uncertain as to whether they support `_cache`. The documentation should be updated to specify for them as well:

* `geo_distance_range`
* `ids`
* `indices`
* `limit`
* `match_all`
* `nested`

If someone replies with which of these filters support `_cache` I can update the documentation.

The generic page about filter caches should also contain filters where the option is invalid: https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-cache.html

**Comment by clintongormley** [comment]
Thanks @mjohnst - in fact in 2.0, the `_cache` key is ignored as filters are cached automatically when it makes sense to do so.

You're welcome to send a PR for 1.7 if you like, but I think I'd be happy just moving forward here. I'm going to close this issue (but feel free to send a PR)

thanks

**Comment by mjohnst** [comment]
Thanks for the response :)

I can submit a PR for updated docs.

For the below filters, is `_cache` an acceptable option? Also, are they cached automatically? 
* `geo_distance_range`
* `ids`
* `indices`
* `limit`
* `match_all`
* `nested`
