### ISSUE TITLE
Jvm registry string not updated after Java was updated

### ISSUE THREAD

**Issue by samshteinman** [elastic/elasticsearch#13521]
Hello,

There is an issue with elasticsearch-service if we update Java and we do not reinstall the elasticsearch-service.

In this key:
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Apache Software Foundation\Procrun 2.0\elasticsearch-service-x64\Parameters\Java

There is a Jvm string value which points to for example: C:\Program Files\Java\jdk1.8.0_45\jre\bin\server\jvm.dll

If you uninstall java u45 and update to a newer java, elastic search service stops working because it has an outdated reference.

**Comment by rauanmaemirov** [comment]
I've just had similar issue on Linux. init.d service script forces you to set JAVA_HOME in /etc/default/elasticsearch even if you had set it globally. Otherwise it will use one from the predefined list.

**Comment by clintongormley** [comment]
@Mpdreamz is this something we can solve?

**Comment by samshteinman** [comment]
Hey guys doesn't looking for an upgrade for what's going on with this bug?

Cheers!

**Comment by skwasjer** [comment]
I have quickfixed this for myself on Windows (64-bit) with:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Apache Software Foundation\Procrun 2.0\ES_test\Parameters\Java]
"Jvm"="%JAVA_HOME%\\bin\\server\\jvm.dll"
```

Note that **`ES_test`** in the registry path must be replaced by your service instance name.

**Comment by gmarz** [comment]
I think we should be able to set the Jvm key using %JAVA_HOME% rather than hard coding it (similar to @skwasjer's fix above).  Will open a PR for this soon.

**Comment by AlexKovynev** [comment]
Guys, you have to return everything as it was. Otherwise, the service does not start.

JAVA_HOME returned as "c:\Program Files\Java\jdk1.8.0_91" With quotes!!! And if we add dll path get an error "file not found".

**Comment by gmarz** [comment]
@AlexKovynev I can't reproduce this.  If you edit your environment variables, does the value of JAVA_HOME contain quotes?  If so, they should be removed.

**Comment by AlexKovynev** [comment]
Nope JAVA_HOME does not contains quotes, as i understand Windows return quotes if path contains spaces as "Program Files". Maybe only in .bat. I don't know. For me error disappears if i change path in registry (Windows 10).

**Comment by gmarz** [comment]
@AlexKovynev would you mind opening a new issue for this and providing the elasticsearch and service log files if you have them? Also, include the value that's stored in the registry when the service is installed.

**Comment by staufour** [comment]
If the JAVA_HOME is not defined in environment variable it's now impossible to run the service.
We have in production Server JRE without global JAVA_HOME.
The JAVA_HOME is defined only on application scope (for Elasticsearch before executing service install and until now working great... pity.)
