### ISSUE TITLE
Feature Request: Re-sort terms aggregation result by key after size truncation

### ISSUE THREAD

**Issue by sigpwned** [elastic/elasticsearch#13536]
I'm currently using ElasticSearch aggregations to perform frequency analysis on large groups of cases (10Ks) for variables with many categorical values (100Ks) using a terms aggregation. It's working great!

## Use Case

I'd like to add a feature where I compare the frequency distributions of these variables across two different groups of people. In order to minimize the memory requirements and avoid the use of temporary files, here was my plan:

1. Run a terms query against group A that returns the top N (for N <<100K) hits sorted by key value
2. Run a terms query against group B that returns the top N (for N <<100K) hits sorted by key value
3. Merge the results from (1) and (2) in a streaming fashion, computing a score describing the difference in the two frequencies for the two groups for each pair
4. Iterate until both streams (1) and (2) are exhausted, retaining the top N biggest differences in memory
5. Return these results to the user

This approach would work fine, except that I can't sort the top N by count subsequently by key! I can do the following:

* Sort the entire terms aggregation by document count and take the top N
* Sort the entire terms aggregation by term and take the top N

But I *can't* do the following:

* Sort the entire terms aggregation by document count, take the top N, and the sort the truncated result by term

This "post truncate sort" would be a very useful feature for me! I imagine that it may be useful for others too.

## Possible Implementations

Here are a couple of additions to the aggregations DSL that would address this use case.

### Post-Truncate Sort in Terms Aggregation

One fairly self-contained fix would be to add a second sort to the terms aggregation that is a NOP by default, but provides a second sort like the `order` feature already in the terms aggregation that is performed after truncation. Purely for illustration, the syntax might look something like this:

    {
      "aggregations" : {
        "name" : {
          "terms" : {
            "field" : "categorical",
            "size" : 10000,
            "postorder" : { "_term" : "asc" }
          }
        }
      }
    }

### A New Order Aggregation

A more general fix might be to add a new aggregation type called something like "resort" that simply applies a new sort to its child aggregation(s). Purely for illustration, the syntax might look something like this:

    {
      "aggregations" : {
        "name" : {
          "resort" : {
            "order" : {
              "name2" : { "_bucket" : "asc" }
            },
            "aggregations" : {
              "name2" : {
                "terms" : {
                  "field" : "categorical",
                  "size" : 10000,
                  "postorder" : { "_term" : "asc" }
                }
              }
            }
          }
        }
      }
    }

This would allow users to perform arbitrary resorting on their aggregations whenever they needed. This approach may require some thought regarding what options for sorting are available, but would give people a lot more flexibility on their sorts.

## Workarounds

There are some fairly good workarounds for now. Here are a few options I see open to me at the moment:

* Streaming the untruncated terms result for both groups sorted by term
* Pulling the entire truncated result for both groups into memory and working on them directly
* Write sorted results for both groups to temporary files, then stream the results from the files

Regardless, ElasticSearch is great, and a joy to work with! :)

**Comment by clintongormley** [comment]
@colings86 a sorting pipeline agg may be an answer here. What do you think?

**Comment by colings86** [comment]
@clintongormley I agree, we have talked about this before. I think a resorting pipeline aggregation would be useful

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/14928

**Comment by sigpwned** [comment]
Thank you for the triage @clintongormley! Always thrilled to see how responsive the ElasticSearch team is to feedback!
