### ISSUE TITLE
[test] RelocationIT.testMoveShardsWhileRelocation

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#13542]
http://build-us-00.elastic.co/job/es_core_master_centos/7200/

This is a problem with recovery settings being applied on the nodes at different times. 

We throttle recovery in the test and in this case we set it to 1byte/s. At the same time we set the chunk size for sending files to 1byte too. This way we can delay recovery. Later, while recovery is still ongoing, we speed it up again so that the test does not take so long. 
The throttling happens on the target and source node but the chunks are chopped on the source node. 

Unfortunately the settings are applied on each node at different times, depending on when the cluster state arrives. So when we speed up recovery again the source node might send a chunk of 130 bytes (in this case) because it has already processed a new cluster state which allows for greater chunks but the target node is still on the old state and applies an old throttling of 1byte/s. It therefore delays the recovery by 130s and that is why the check that recoveries have finished times out.

@bleskes proposed to fix this by blocking relocation completely with a Tracer instead of relying on the recovery settings. I'll see how far I get. I will mute the test for now.

**Comment by brwe** [comment]
Discussed with @martijnvg and we think the test can be deleted. It does not actually test the scenario it was written for anyway. I will delete it in a week from now if no one intervenes. ( ping @bleskes just in case).

**Comment by bleskes** [comment]
I'm ok with removing it.
