### ISSUE TITLE
Support for es-1.7

### ISSUE THREAD

**Issue by robertsmarty** [elastic/elasticsearch#13554]
It is not obvious which versions of elasticsearch this plugin supports. How should this plugin be installed?

**Comment by robertsmarty** [comment]
This is relating to the AWS plugins

**Comment by dadoonet** [comment]
For elasticsearch < 2.0, please refer to https://github.com/elastic/elasticsearch-cloud-aws

The plugin version you should use for 1.7 is 2.7.1.
