### ISSUE TITLE
Make it easier to retrieve the resolved node name in unit tests

### ISSUE THREAD

**Issue by beiske** [elastic/elasticsearch#13553]
A plugin class injected with a Settings object fails to retrieve the ```node.name``` unless this has been explicitly set through the settings object.

```
    @Inject
    public ZooKeeperPaths(Settings settings, ClusterName clusterName) {
        String instanceName = settings.get("node.name");
        if (instanceName == null) {
            throw new IllegalStateException("Instance name cannot be null");
        }
    }
```

Able to reproduce this when running tests for the found-plugin that use ESIntegTestCase. Workaround is to simply set a specific node.name and not rely on auto generated node names.

**Comment by clintongormley** [comment]
This isn't a bug: if the node name is not specified in the settings, then the settings shouldn't be updated to reflect the resolved node name.  Currently you would need to get the ClusterService and retrieve the local node name.

Perhaps there is a way of making this easier/lighter for use in unit tests?  The alternative would be to just specify node names explicitly.

**Comment by beiske** [comment]
The current way to retrieve the autogenerated node name (the one used if no node name is given in the settings) is to depend on ```ClusterService``` and then do ```clusterService.localNode().getName()```. The problem with this is that the ClusterService is relatively high in the dependency hierarchy. This results in unnecessary complexity for tests and can cause challenges with circular dependencies. 

My suggestion is to extract the instance name property into it's own class so that it may be depended on directly, like ClusterName. 

Maybe it is also be possible to do something generic? Are there more properties like this? I guess the distinctive feature in this regard is that it is a property of the running instance that is not necessarily defined in the settings and, unlike most settings, the default value is not static. Had it been a dynamic property that could change at runtime I would consider it justified to depend on the ClusterService.

**Comment by jasontedor** [comment]
The property to get when you are relying on randomly generated names is `name`, not `node.name`. You can see this if you inspect what happens in [`InternalSettingsPreparer#finalizeSettings`](https://github.com/elastic/elasticsearch/blob/bd025080c4feb4b0cd941d007bb5d2113ef0d411/core/src/main/java/org/elasticsearch/node/internal/InternalSettingsPreparer.java#L165).
