### ISSUE TITLE
[CI] Failure: org.elasticsearch.search.aggregations.bucket.GeoHashGridIT.simple

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#13560]
Saw this on the query-refactoring branch today, since we did some changes in Geo recently we need to check if this is only on the feature branch and what changed here:

http://build-us-00.elastic.co/job/es_feature_query_refactoring/8998/

Geohash w has wrong centroid  expected:<[27.677337714038913, 119.06734793896817]> but was:<[27.677337303757668, 119.06734686344862]>

Stacktrace

java.lang.AssertionError: Geohash w has wrong centroid  expected:<[27.677337714038913, 119.06734793896817]> but was:<[27.677337303757668, 119.06734686344862]>
	at __randomizedtesting.SeedInfo.seed([8282B3A257119F6E:1EB05A4306CC780]:0)
	[...]

**Comment by dakrone** [comment]
@cbuescher I already opened an issue for this, closing this one as a duplicate of https://github.com/elastic/elasticsearch/issues/13558

**Comment by cbuescher** [comment]
@dakrone thanks, so I guess it fails on master too.
