### ISSUE TITLE
Remove duplicate code in QueryBuilders and Parsers

### ISSUE THREAD

**Issue by alexksikes** [elastic/elasticsearch#13564]
Many queries duplicate code when it comes to:

- resolving field to their index names
- handling regex patterns in fields
- handling boost in fields
- setting up the Analyzer from a string
- serializing enums

We should consolidate these functions in a support class instead. This should
also ease adding those functionalities to the other queries.

**Comment by javanna** [comment]
I can't think of anything that is left to do here, @cbuescher what do you think?

**Comment by cbuescher** [comment]
@javanna I think can remove code duplications now that we merged with master as we go along and re-open more specific issues for that.

**Comment by ronghuaxiang** [comment]
`{
  "aggs":{
    "dedup" : {
      "terms":{
        "field": "user_id"
       },
       "aggs":{
         "dedup_docs":{
           "top_hits":{
             "size":1
           }
         }
       }    
    }
  }
}`
