### ISSUE TITLE
Bucket Selector Aggregation does not accept script file as input

### ISSUE THREAD

**Issue by adimasuhid** [elastic/elasticsearch#13567]
Using elasticsearch 2.0.0-beta1 with the following search parameters:

```
{ some_filter:
      bucket_selector:
          buckets_path:
              some_variable: "some_index>some_index_value.value"
          script: "bucket-selector"
}
```

The `script` attribute treats `bucket-selector` as an inline/indexed script which causes the ff error:
```
{"type":"script_exception","reason":"scripts of type [inline], operation [aggs] and lang [groovy] are disabled"}
```

And `script_file` may not yet be implemented with the bucket selector aggregation:
```
{"type":"search_parse_exception","reason":"Unknown key for a VALUE_STRING in [some_filter]: [script_file] }
```

**Comment by clintongormley** [comment]
Hi @adimasuhid 

The syntax for scripts has changed in 2.0.  See https://www.elastic.co/guide/en/elasticsearch/reference/2.0/_scripting_changes.html

You need to specify a file script as:

    "script": {
        "file": "name-of-file"
    }

**Comment by adimasuhid** [comment]
Got it thanks!
