### ISSUE TITLE
ES returns a pair for lat and lon fields

### ISSUE THREAD

**Issue by marfago** [elastic/elasticsearch#13571]
Hi,

I've recently upgraded ES from version 1.4.4 to 1.7.1 and now I have an issue with lat and lon indexed fields for geo_point.
In my index I have a field defined as follows:

```
"geolocation": {
    "lat_lon": true,
    "geohash_prefix": true,
    "type": "geo_point",
    "geohash": true
}
```
When issuing the query
```
{
"fields":["geolocation.lat","geolocation.lon","geolocation"],
  "query": {
    "filtered" : {
        "query" : {
            "match_all" : {}
        },
        
        "filter" : {
            "geo_distance" : {
                "distance" : "20km",
                "geolocation" : {
                    "lat" : 37.9174,
                    "lon" : -122.3050
                }
            }
        }
    }
  }
}
```

this is the response

```
"hits": {
    "total": 3995,
    "max_score": 1,
    "hits": [
        {
            "_index": "idx",
            "_type": "event",
            "_id": "466201666890120",
            "_score": 1,
            "fields": {
                "geolocation": [
                    "37.768991279975,-122.41938924477"
                ],
                "geolocation.lon": [
                    "37.768991279975,-122.41938924477"
                ],
                "geolocation.lat": [
                    "37.768991279975,-122.41938924477"
                ]
            }
        }
```

In other words geolocation.lat and geolocation.lon contain the pair and not just the single value.
Version 1.4.4 worked properly as expected.

**Comment by clintongormley** [comment]
Hi @marfago 

I've tried out what you say on 1.4.4 and I think you're incorrect about this having changed.  It depends entirely on how you index your geopoints.  For instance:

    PUT t
    {
      "mappings": {
        "t": {
          "properties": {
            "geolocation": {
              "lat_lon": true,
              "geohash_prefix": true,
              "type": "geo_point",
              "geohash": true
            }
          }
        }
      }
    }
    
    PUT t/t/1
    {
      "geolocation": "37.768991279975,-122.41938924477"
    }
    
    PUT t/t/2
    {
      "geolocation": {
        "lat": 37.768991279975,
        "lon": -122.41938924477
      }
    }
    
    GET _search
    {
      "fields": [
        "geolocation.lat",
        "geolocation.lon",
        "geolocation"
      ]
    }

returns the following:

      "hits": [
         {
            "_index": "t",
            "_type": "t",
            "_id": "1",
            "_score": 1,
            "fields": {
               "geolocation": [
                  "37.768991279975,-122.41938924477"
               ],
               "geolocation.lon": [
                  "37.768991279975,-122.41938924477"
               ],
               "geolocation.lat": [
                  "37.768991279975,-122.41938924477"
               ]
            }
         },
         {
            "_index": "t",
            "_type": "t",
            "_id": "2",
            "_score": 1,
            "fields": {
               "geolocation.lon": [
                  -122.41938924477
               ],
               "geolocation.lat": [
                  37.768991279975
               ]
            }
         }
      ]

The `fields` parameter is trying to extract the value from the `_source` field.  However, if you use the  fielddata_fields` parameter instead, then you get the actual lat/lon values consistently:

    GET _search
    {
      "fielddata_fields": [
        "geolocation.lat",
        "geolocation.lon",
        "geolocation"
      ]
    }

Returns:

      "hits": [
         {
            "_index": "t",
            "_type": "t",
            "_id": "1",
            "_score": 1,
            "_source": {
               "geolocation": "37.768991279975,-122.41938924477"
            },
            "fields": {
               "geolocation": [
                  {
                     "lat": 37.768991279975,
                     "lon": -122.41938924477
                  }
               ],
               "geolocation.lon": [
                  -122.41938924477
               ],
               "geolocation.lat": [
                  37.768991279975
               ]
            }
         },
         {
            "_index": "t",
            "_type": "t",
            "_id": "2",
            "_score": 1,
            "_source": {
               "geolocation": {
                  "lat": 37.768991279975,
                  "lon": -122.41938924477
               }
            },
            "fields": {
               "geolocation": [
                  {
                     "lat": 37.768991279975,
                     "lon": -122.41938924477
                  }
               ],
               "geolocation.lon": [
                  -122.41938924477
               ],
               "geolocation.lat": [
                  37.768991279975
               ]
            }
         }
      ]
