### ISSUE TITLE
DiskAllocationDecider should take custom data paths for shadow replicas into account

### ISSUE THREAD

**Issue by jinahn** [elastic/elasticsearch#13583]
Trying to manually relocate a shard returns the following error. We are using shadow replicas in our setup.

{
  "error": "ElasticsearchIllegalArgumentException[[move_allocation] can't move [accesslogging_hawthorne-2015-09-01][1], from [Sputnik][28AZOAhAQV6ThZyCB5oP4g][halitods4.datacenter.automotive.com][inet[/10.1.68.42:9300]]{site=hawthorne, tag=shadowcopy, enable_custom_paths=true, master=false}, to [Thirty-Three][NWA5D0HIRAe-7XaHtfiq7g][halitods5.datacenter.automotive.com][inet[/10.1.68.43:9300]]{site=hawthorne, tag=shadowcopy, enable_custom_paths=true, master=false}, since its not allowed, reason: [YES(shard is not allocated to same node or host)][YES(node passes include/exclude/require filters)][YES(shard is primary)][YES(below shard recovery limit of [2])][YES(allocation disabling is ignored)][YES(allocation disabling is ignored)][YES(no allocation awareness enabled)][YES(total shard limit disabled: [-1] <= 0)][YES(target node version [1.7.1] is same or newer than source node version [1.7.1])][NO(after allocation more than allowed [85.0%] used disk on node, free: [0.9657585087747922%])][YES(no snapshots are currently running)]]",
  "status": 400
}

**Comment by dakrone** [comment]
@jinahn the relocation actually failed because you are over the [disk watermark](https://www.elastic.co/guide/en/elasticsearch/reference/current/disk.html), as you can see from:

```
NO(after allocation more than allowed [85.0%] used disk on node, free: [0.9657585087747922%])
```

**Comment by jinahn** [comment]
The actual disk usage for the drive the indices are is actually only 20% used

**Comment by dakrone** [comment]
@jinahn see #13582, the DiskThresholdDecider does not currently know about custom data paths when calculating the disk usage.

**Comment by bleskes** [comment]
Shadow replicas have been [removed](https://github.com/elastic/elasticsearch/pull/23906) and making DiskThresholdAllocator custom path aware is tracked in https://github.com/elastic/elasticsearch/issues/13583, so I think we can close this one.
