### ISSUE TITLE
nodes don't see each others without setting network.host

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13589]
With 2.0, we now bind to `localhost` by default instead of binding to the network card and use its IP address.

When the discovery plugin gets from AWS API the list of nodes that should form the cluster, this list is pinged then. But as each node is bound to `localhost`, ping does not get an answer and the node elects itself as the master node.

**Comment by dadoonet** [comment]
See also #13589, #13590, #13591

**Comment by s1monw** [comment]
isn't this a configuration issue? I mean can / do we want to do anything about this?

**Comment by dadoonet** [comment]
It's at least a documentation issue. 

EC2 supports indeed other settings: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/modules-network.html

So you can bind to `_ec2_`. May be this should be a default option when ec2 plugin is loaded?
