### ISSUE TITLE
Range filter with relative date does not use specified time zone

### ISSUE THREAD

**Issue by Lande24** [elastic/elasticsearch#13607]
I'm trying to query all documents containing a date which has passed (less than now). My query is:
{
"query": {
   "filtered": {
     "query": {
       "match_all": {}
     }
     "filter": {
       "range": {
         "date_field": {
            "lt": "now"
         }
       }
     }
   }
 }
}

The problem is that I'm in a UTC+3 time zone, and this query returns only documents with a date field of up to 3 hours before the current time (probably because it assumes the time in the document is in UTC).
I tried to add "time_zone" : "+3:00"
to the range query but it didn't work (in fact it didn't matter which value I entered into the time_zone - it didn't affect the result)

I need a way to make the "now" value independent of time zone or simply force it to be in the UTC time zone.

**Comment by clintongormley** [comment]
This is indeed a bug, easily demonstrated as follows:

    PUT t/t/1
    {
      "date": "2015/01/01"
    }
    
    GET _validate/query?explain&rewrite
    {
      "query": {
        "bool": {
          "should": [
            {
              "range": {
                "date": {
                  "lt": "now",
                  "time_zone": "-10:00"
                }
              }
            },
            {
              "range": {
                "date": {
                  "lt": "now"
                }
              }
            },
            {
              "range": {
                "date": {
                  "lt": "now",
                  "time_zone": "+10:00"
                }
              }
            }
          ]
        }
      }
    }

This returns the following explanation:

             "date:[* TO 1442666506311} date:[* TO 1442666506311} date:[* TO 1442666506311}"

**Comment by andrestc** [comment]
I'll take a shot at this one!

**Comment by andrestc** [comment]
@clintongormley, I believe i have this fixed, but when I was writing a test for it I came across [this one](https://github.com/elastic/elasticsearch/blob/e713bf215193c48d03c164aaf1143666f30ee1ff/core/src/test/java/org/elasticsearch/common/joda/DateMathParserTests.java#L142):

```java
// timezone does not affect now
assertDateMathEquals("now/m", "2014-11-18T14:27", now, false, DateTimeZone.forID("+02:00"));
```
This test seems specific for this case. Are we sure this is a bug?

Thanks!

**Comment by clintongormley** [comment]
@andrestc Ah good point!  Dates should be stored as UTC, so `time_zone` shouldn't affect `now()` (which is calculated in UTC).

OK, so we should (a) document it and (b) possibly add an exception when `time_zone` is used with `now`?

**Comment by Lande24** [comment]
In that case, how am I supposed to overcome my problem?

**Comment by clintongormley** [comment]
@Lande24 Make sure your dates are stored in UTC, which you can do by specifying your time zone in the date itself

    "date": "2015-01-01T13:00:00+03:00"  # indexed in UTC as "2015-01-01T10:00:00"

See https://twitter.com/alicemazzy/status/646219411754483712

**Comment by andrestc** [comment]
@clintongormley great, I'll draft this and PR it.
