### ISSUE TITLE
Identical jars are not detected by jar hell

### ISSUE THREAD

**Issue by jprante** [elastic/elasticsearch#13604]
When I try to run gradle integration tests to test a plugin by unpacking the zip, the jar hell detection is unable to recognize the same jar on the class path at two (or more) different locations.

I assume this is not intended. It would make gradle classpath setups (maybe other build tools too) to compile and test ES plugins "in-place" very difficult to specify.

My suggestion is to skip jar URLs that point to a jar with a checksum of a jar that has been already checked.

Example:

```
Caused by: java.lang.IllegalStateException: jar hell!
class: org.xbib.elasticsearch.http.HttpModule$_configure_closure1
jar1: /Users/joerg/.gradle/caches/modules-2/files-2.1/org.xbib.elasticsearch.plugin/elasticsearch-webapp/2.0.0-beta1.0/c735bc9b3e05b37a2d553ddda7d76fefc5e817e5/elasticsearch-webapp-2.0.0-beta1.0.jar
jar2: /Users/joerg/Projects/github/jprante/elasticsearch-webapp-example/plugins/webapp/elasticsearch-webapp-2.0.0-beta1.0.jar
	at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:210)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:128)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:346)
	... 52 more
```

```
shasum /Users/joerg/.gradle/caches/modules-2/files-2.1/org.xbib.elasticsearch.plugin/elasticsearch-webapp/2.0.0-beta1.0/c735bc9b3e05b37a2d553ddda7d76fefc5e817e5/elasticsearch-webapp-2.0.0-beta1.0.jar
c735bc9b3e05b37a2d553ddda7d76fefc5e817e5  /Users/joerg/.gradle/caches/modules-2/files-2.1/org.xbib.elasticsearch.plugin/elasticsearch-webapp/2.0.0-beta1.0/c735bc9b3e05b37a2d553ddda7d76fefc5e817e5/elasticsearch-webapp-2.0.0-beta1.0.jar
```

```
shasum /Users/joerg/Projects/github/jprante/elasticsearch-webapp-example/plugins/webapp/elasticsearch-webapp-2.0.0-beta1.0.jar
c735bc9b3e05b37a2d553ddda7d76fefc5e817e5  /Users/joerg/Projects/github/jprante/elasticsearch-webapp-example/plugins/webapp/elasticsearch-webapp-2.0.0-beta1.0.jar
```

**Comment by rmuir** [comment]
The failure is intentional. Why should we be lenient about this? it is still a form of jar hell!

**Comment by jprante** [comment]
If the duplicate class files exist inside the same class loader, and the two duplicate class files are exactly identical then it does not matter which one gets chosen first - this situation is not dangerous.

**Comment by s1monw** [comment]
> If the duplicate class files exist inside the same class loader, and the two duplicate class files are exactly identical then it does not matter which one gets chosen first - this situation is not dangerous.

having the same file twice is a problem we can't work around this and add leniency on that level - we are just enforcing things to be setup properly.

**Comment by vchekan** [comment]
@s1monw correct me if I am wrong, but jar hell conflict can happen not just between a plugin and elasticsearch, but between 2 plugins.

As a plugin author, I can not "setup things properly" because this would require me to know target server's list of plugins at my plugin compile time. In other words, it is impossible for a plugin author to make their plugin compatible with all existing and all future plugins.

To make it even worse, if I exclude a conflicting jar from my plugin, it will break if the other plugin gets uninstalled, because now my plugin could not find needed jar. What should I do as a plugin author?

**Comment by nik9000** [comment]
> As a plugin author, I can not "setup things properly" because this would require me to know target server's list of plugins at my plugin compile time. In other words, it is impossible for a plugin author to make their plugin compatible with all existing and all future plugins.

I believe plugins run in isolated classloaders so two plugins can define the same class without this being an issue.

**Comment by vchekan** [comment]
@nik9000 hmm, I think I understood. I am actually doing bulk insert, and pointing to ES install with some plugins already installed. Perhaps, jar isolation works differently when bulk node is registered. I will solve it by pointing bulk node at "clean" ES install, without any plugins.
