### ISSUE TITLE
Get wrong node ip address through host:9200/_cat/nodes

### ISSUE THREAD

**Issue by tuxknight** [elastic/elasticsearch#13601]
I just set up the elasticsearch with one node, and it's ip address is 10.1.5.72
But the ip address returned from  curl 10.1.5.72:9200/_cat/nodes?v is 10.1.5.110.
Here is the result
```
[root@sh-elk-svr01 elasticsearch]# curl 10.1.5.72:9200/_cat/nodes?v
host         ip         heap.percent ram.percent load node.role master name       
sh-elk-svr01 10.1.5.110           10          28 0.00 d         *      Sea Urchin
```

And I noticed that the information in elasticsearch.log was correct
```
[2015-09-16 13:59:24,376][INFO ][http] [Sea Urchin] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/10.1.5.72:9200]}
```

**Comment by clintongormley** [comment]
Hi @tuxknight 

I believe this is fixed in 2.0, although I can't find the PR.  Could you try out 2.0.0-beta2 and confirm please?

**Comment by tuxknight** [comment]
@clintongormley  Sorry ! Found the reason.
wrong IP address was set in /etc/hosts .

```
$ cat /etc/hosts
10.1.5.110   sh-elk-svr01
```

**Comment by clintongormley** [comment]
thanks @tuxknight
