### ISSUE TITLE
Automatically set project-id and zone

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13618]
The project id can be retrieved from the running instance by calling  `http://metadata.google.internal/computeMetadata/v1/project/project-id`.

Same for the default zone: `http://metadata.google.internal/computeMetadata/v1/project/attributes/google-compute-default-zone
`

No need then to force them in `elasticsearch.yml`.

**Comment by dadoonet** [comment]
> The first point sounds like that a value for cloud.gce.project_id could be obtained from the GCE metadata service (presumably still allowing a manual override), right?

Yes.

> I see that there's a cloud.gce.zone setting, but this seems to want to be a list of all zones to search for nodes, not just the default zone?

Indeed but if not set we can just fill that list with the current zone only which is I believe what users are doing most of the time I guess: deploying in one single zone.

**Comment by DaveCTurner** [comment]
Ah right. I was thinking more about AWS availability zones of which it's best to use more than 1, but if that's a common way to use GCE then that makes sense.

**Comment by vladimirdolzhenko** [comment]
[com.google.cloud.ServiceOptions#getDefaultProjectId ](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-clients/google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java#L333) tries to resolve project based on
* system property `GOOGLE_CLOUD_PROJECT` (or legacy system property `GCLOUD_PROJECT`) 
* environment variable `GOOGLE_CLOUD_PROJECT` or `GCLOUD_PROJECT` 
* from `http://metadata.google.internal/computeMetadata/v1/project/project-id`

ES assumes system properties as unsafe while environment variables could be predefined on the environment (could it be different from value returned from `http://metadata.google.internal/computeMetadata/v1/project/project-id`? )

Are we going to use only last method ?
