### ISSUE TITLE
Add 16-bit float data type

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#13626]
Sometimes you just want fewer bits :)

Would be great if we supported half-precision 16 bit floats.  Robert mentioned that Java doesn't support these newer floats yet, so we'd have to do the conversion in software.  But perhaps someday Java will support it and we can switch over to the intrinsics.

Quoting [wiki](https://en.wikipedia.org/wiki/Half-precision_floating-point_format):

> The minimum strictly positive (subnormal) value is 2<sup>−24</sup> ≈ 5.96 × 10<sup>−8</sup>. The minimum positive normal value is 2<sup>−14</sup> ≈ 6.10 × 10<sup>−5</sup>. The maximum representable value is (2−2<sup>−10</sup>) × 2<sup>15</sup> = 65504.

Half-floats would mainly be useful for doc-value metrics that don't need the fully 32bit float, but need a larger dynamic range than an equivalent fixed-point (#13625)

Usual disclaimer about floating point accuracy issues applies, although it is noticed much sooner due to the limited range. :)

**Comment by jpountz** [comment]
+1

**Comment by jpountz** [comment]
I have been playing with it at https://issues.apache.org/jira/browse/LUCENE-7289.

**Comment by polyfractal** [comment]
Closed via #18887 (Yay!)
