### ISSUE TITLE
geo_shape points_only not working

### ISSUE THREAD

**Issue by Eschon** [elastic/elasticsearch#13650]
I downloaded the 2.0-beta2 and decided to try out the `points_only` option for `geo_shapes` that was added in #12893 but I couldn't get it to work.

Here is the mapping that I tried to use: 
```JSON 
{
  "properties": {
    "name": {
      "index": "not_analyzed",
      "type": "string"
    },
    "location": {
      "type": "geo_shape",
      "points_only": true
    }
  }
}
```

When I try it I get the following error:
```JSON
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Mapping definition for [location] has unsupported parameters:  [points_only : true]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Mapping definition for [location] has unsupported parameters:  [points_only : true]"
  },
  "status": 400
}
```

**Comment by eskibars** [comment]
First, thanks for trying out beta2!  I tried as well and can confirm this isn't working as expected.  @nknize can you have a look?

**Comment by clintongormley** [comment]
Bah, #12893 was mislabelled... it's actually in 2.1.0

Sorry for the confusion - i've updated the changes list and blog post

**Comment by Eschon** [comment]
Too bad, I was really looking forward to trying it out. Well I guess I'll just have to wait for 2.1.0 then.
You also might want to remove it from the documentation for now https://www.elastic.co/guide/en/elasticsearch/reference/2.0/geo-shape.html

**Comment by clintongormley** [comment]
Bah again :)  So it WAS merged into the 2.0 branch, but after 2.0.0-beta2 was built.  Good news is it will be in the next release of 2.0.0.  I've added a "coming" tag to the docs.

thanks @Eschon

**Comment by alakhdeveloper** [comment]
Hello  Guys,
I need some help in elasticsearch(2.3) mapping in magento 2.1.  

I need to mapp geo_shape.
my code in xml elasticsuite_indices.xml: 
<field name="hyperlocal.sellerid" type="integer" nestedPath="hyperlocal" />
<field name="hyperlocal.coordinates" type="geo_shape" nestedPath="hyperlocal" />

When i try to index it throwing error message: 
mapper_parsing_exception: Mapping definition for [coordinates] has unsupported parameters:  [norms : {enabled=false}] [doc_values : true]

what i am missing in mapping xml code.

**Comment by alakhdeveloper** [comment]
Thanks @dadoonet 

Please help me at https://discuss.elastic.co/t/geo-shape-mapping-issue/137107
