### ISSUE TITLE
Missing methods for array params

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13652]
_From @dsernst on September 16, 2015 21:23_

If I pass in an array like:

```js
script_file: 'myScript',
lang: 'javascript',
params: {
  myParam: [3, 4, 5]
}
```

Then trying any of these from within `myScript.js` will fail with a `has no method` error:

```
myParam.slice()
myParam.reduce()
myParam.push()
```

`reason: 'EcmaError[TypeError: Cannot find function slice in object [3, 4, 5]. (Script23.js#15)]' },`

_Copied from original issue: elastic/elasticsearch-lang-javascript#42_

**Comment by clintongormley** [comment]
Arrays are passed to the script as objects of type [ArrayList](https://docs.oracle.com/javase/8/docs/api/java/util/ArrayList.html), which doesn't support the slice() method.  Converting it to an array works:

      "script": {
        "inline": "foo.toArray().slice()",
        "lang": "js",
        "params": {
          "foo": ["1","2"]
        }
      }

So the question is: is an ArrayList the right object to use here?

**Comment by clintongormley** [comment]
Given this workaround, i'm going to close.
