### ISSUE TITLE
Geo context suggestion fail using path option with nested object

### ISSUE THREAD

**Issue by silvestrelosada** [elastic/elasticsearch#13666]
I want to create a completion suggester with a geo type context. The geo_type information is stored under a nested object, the configuration seems ok, it is indexing well, however it always put the default values in geo type. Here is the configuration.

```   
 suggest: {
               type: "completion",
                 context: {
                     sector: {
                       type: "category",
                       default: "TECH",
                       path: "sector"
                     },
                     location: {
                       type:"geo",
                       precision: ["2km","20km","30km"],
                       path: "shops.location",
                       default:{
                          lat:0.0,
                          lon:0.0
                       }
                    }
                  },
             shops: {
               type: 'nested',
               properties: {
                   shop_aggregation_string: { type: "string", index: "not_analyzed" },
                   id:   { type: 'long' },
                   name:       { type: 'string', index: 'not_analyzed' },
                   address:    { type: 'string', index: 'not_analyzed' },
                   chain_id:   { type: 'long' },
                   chain_name: { type: 'string', index: "not_analyzed" },
                   location:   { type: "geo_point"},
                   stock:      { type: 'integer' },
                   sale:       { type: 'boolean' },
                   price:      { type: 'double' },
               }
             }
```

For each document there is multiple shops. 

Kind regards

**Comment by clintongormley** [comment]
Hi @silvestrelosada 

Nested objects are stored in separate documents from the main object, so the suggester doesn't have access to the values in the nested object (unless you use the include_in_root option to also store the nested values in the top-level object).

**Comment by silvestrelosada** [comment]
Thanks for response an explanation.

**Comment by silvestrelosada** [comment]
Hi again,

I tried your recommendation,

  shops: {
               type: 'nested',
               include_in_root: true,
               properties: {
                   location:   { type: "geo_point"},
               }
             }

The location appears in root object however it cannot be used in path for completion suggester, I guess that the issue is that it does not exist physically on the JSON.

I also tried with include_in_parent and no result.

**Comment by clintongormley** [comment]
then perhaps you want to use `copy_to` instead

**Comment by silvestrelosada** [comment]
I'll try but i guess it wont work, because is not present on JSON document, I mean in _source
