### ISSUE TITLE
Documentation improvement: cloud.aws.region required for ec2 discovery in non-default regions?

### ISSUE THREAD

**Issue by mnylen** [elastic/elasticsearch#13668]
Just spent four hours figuring out why the ec2 discovery isn't working.

It appears that `cloud.aws.region` must be set, or otherwise the describe instances call won't find anything. After adding `cloud.aws.region: eu-west-1` to elasticsearch configuration, it magically started working.

Could documentation be improved regarding this setting a bit? Maybe highlight that if you are not running in default region it is required for discovery to work?

**Comment by dadoonet** [comment]
Agreed. Do you want to contribute a doc update?
