### ISSUE TITLE
Elasticsearch won't recover after OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by foresightyj** [elastic/elasticsearch#13664]
I am running an ES instance (4GB RAM, single node) in production. There are not so many concurrent requests usually but occasionally a query could exceed the RAM available and `OutOfMemoryError` occurs. I've never seen the ES node being able to recover from such tragic state, until I do a manual restart. I have to do so once or twice per month.

Is this the behavior by design? When an OutOfMemoryError occurs, ES will enter a undefined state and not be able to recover?

Here is a typical log: http://pastebin.com/3KdP81EC
Here is my `/_nodes` result: http://pastebin.com/kmPzw5KY

Note, it is a single node ES setup so no split-brain issues..

**Comment by rmuir** [comment]
You hit heap problems such that oom happens inside lucene indexwriter. When this happens it does not try to be a superhero and just take it to the face and keep on trucking, it closes itself for data safety.

**Comment by clintongormley** [comment]
@foresightyj as @rmuir said, after an OOM you have to restart. No way around it.  What you should do though is to figure out what is causing the OOM and fix that.  The place to get help for that is the forum: http://discuss.elastic.co/.  If you find a problem with some protection mechanism (eg circuit breakers etc) then feel free to open a bug report.

**Comment by foresightyj** [comment]
@clintongormley Thanks for the clear answer. I also realized that discuss.elastic.co is a better place for such questions. I will post future questions there. At the time I came out with this question, discuss.elastic.co was unavailable (maybe it was taken offline for maintenance). I experience that quite frequently in China during day time (which is roughly night time in the western countries)
