### ISSUE TITLE
Cloud AWS client side encryption

### ISSUE THREAD

**Issue by GlenRSmith** [elastic/elasticsearch#13673]
See elasticsearch-cloud-aws PR 118 from @NicolasTr
https://github.com/elastic/elasticsearch-cloud-aws/pull/118

**Comment by NicolasTr** [comment]
Thanks for creating this @GlenRSmith

I'll port the code as soon as I can. Hopefully this month, more realistically somewhere in November.

Did the structure of the project change when the cloud aws plugin was moved to elasticsearch?

@dadoonet

**Comment by xuzha** [comment]
@NicolasTr  we split the cloud-aws plugin into two plugins : repository-s3 and discovery-ec2. I think this PR is only related to Repository-s3.

**Comment by dadoonet** [comment]
@NicolasTr IIRC you told us that you want to port your changes to this repository. Is it still your plan? Thanks!

**Comment by samcday** [comment]
It's kinda a bummer that by the looks of things @NicolasTr had a totally functional, reviewed, tested PR that was even run through the CLA gauntlet, and it didn't end up making it into the project! :(

**Comment by xuzha** [comment]
The PR has been reverted, reopen this

**Comment by dchang-novotec** [comment]
Any chance that this will be making it into the next release?

**Comment by jasontedor** [comment]
> Any chance that this will be making it into the next release?

I can tell you right now that the answer to that is definitively "no".

**Comment by dchang-novotec** [comment]
+1  Will definitely like to see this feature soon

**Comment by dchang-novotec** [comment]
Any updates on this feature going in?  There is a lot of interest in this feature making it in expressed in this PR: https://github.com/elastic/elasticsearch/pull/16843

**Comment by tlrx** [comment]
We don't have immediate plan to add client side encryption to the S3 repository plugin but we understand that many users required it. The pull request that has been proposed here has been reverted and would need a major refactoring to be added to new versions of elasticsearch.

We're tracking the client side encryption for all the cloud-based repository plugins in #11128 so I'm going to close this one in order to avoid duplicates.
