### ISSUE TITLE
exceptions from native search scripts are no longer propagated to client

### ISSUE THREAD

**Issue by drallax** [elastic/elasticsearch#13674]
In ES-2.0.0-beta2 (and also in ES-2.0.0-beta1), when an exception in thrown from a native 
search script, Java node clients no longer seem to receive any indication that something went wrong.

For example, we have a native sort script that takes a parameter and throws an exception in case it is missing:
```java
    private static class MyFactory implements NativeScriptFactory {
        @Override
        public ExecutableScript newScript(final Map<String, Object> params) {
            if (params.get("field")== null) {
                throw new ScriptException("missing parameter: field");
            }
            ...
        }

        @Override
        public boolean needsScores() {
            return false;
        }
    }
```

however, the following integration test, that used to work with ES-1.7.1, now fails:
```java
public abstract class MyScriptIT extends ESIntegTestCase {
    @Rule
    public ExpectedException _exception = ExpectedException.none();

    @Test
    public void testMissingFieldFails() throws Exception {
        createIndex(...);
        ensureGreen(...);

        _exception.expect(SearchPhaseExecutionException.class);
        _exception.expectMessage("missing parameter: field");

        final Map<String, Object> params = new HashMap<>();
        final Script script = new Script("my-script", ScriptType.INLINE, "native", params);
        final ScriptSortBuilder script = SortBuilders.scriptSort(script, "number");
        return _client.prepareSearch(...).addSort(script).execute().actionGet();
    }
}
```

in fact, no exception at all is thrown
```
java.lang.AssertionError: Expected test to throw (an instance of org.elasticsearch.action.search.SearchPhaseExecutionException and exception with message a string containing "missing parameter: field")
...
```

in addition, it appears that 
- scripted fetch fields, scripted metrics also don't propagate any thrown exceptions.
  e.g. AggregationBuilders.sum("sum").script(...)
  e.g. AggregationBuilders.scriptedMetric(...)

- update scripts on the other hand still do return exceptions. 
  e.g. return _client.prepareUpdate("test", "test", id).setScript(...);
  However, the returned message always is "failed to execute script", 
  while it used to contain the message that was generated by our native script.

**Comment by nik9000** [comment]
>         createIndex(...);
>         ensureGreen(...);

In this particular case my guess is that the native script isn't being executed at all because there are no results. If there are results then I'm wrong here.

Is there any chance you could post a gist or even a small reproduction project?

If you happen to still be around and want a faster conversation you can reach out to me in #elasticsearch on freenode. I'm `manybubbles` there.

**Comment by nik9000** [comment]
> Is there any chance you could post a gist or even a small reproduction project?

It'd probably be even better if you could reproduce this with a bash script and curl - but I'll take what I can get.

> scripted fetch fields, scripted metrics also don't propagate any thrown exceptions.
> e.g. AggregationBuilders.sum("sum").script(...)
> e.g. AggregationBuilders.scriptedMetric(...)

Hmmm. These _could_ be consistent with my theory about no hits not triggering it. Or not. 

> however, the following integration test, that used to work with ES-1.7.1, now fails

Hmmm. Curiouser and curiouser.

**Comment by drallax** [comment]
Thanks for getting back on this so quickly.
The source code I posted was a reduced down sketch of what is actually happening, and yes, in reality we do hit documents, so I expect there is a regression somewhere.
I'll see if i can get you some fully working examples (probably as ES integration tests) of the oddities we're seeing here

**Comment by nik9000** [comment]
> I'll see if i can get you some fully working examples (probably as ES integration tests) of the oddities we're seeing here

Thanks!

**Comment by drallax** [comment]
found the problem:
the search response that ES-2.0 server-side returns looks like this (perfectly fine):
```
{
  "took" : 108,
  "timed_out" : false,
  "_shards" : {
    "total" : 3,
    "successful" : 2,
    "failed" : 1,
    "failures" : [ {
      "shard" : 2,
      "index" : "test",
      "node" : "jsoxbkP9QDGnl5lSIHYBvQ",
      "reason" : {
        "type" : "script_exception",
        "reason" : "missing parameter: field"
      }
    } ]
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "sum" : {
      "value" : 0.0
    }
  }
}
```

However, our tests fail since
```
_client.prepareSearch().....execute().actionGet()
```
behaves differently from before
in ES-1.7.1 and earlier, it would throw an exception,
in ES-2.0.0-beta1/2, it will NOT throw an exception anymore,
but we end up with a SearchResponse in our hands that we can check for failed shards.
(The same difference exists when adding an Actionlistener to the SearchRequest:
in ES-1.7.1 ActionListener.onFailure() is triggered,
in ES-2.0.0 ActionListener.onResponse() is called instead
)

I am not sure if this qualifies as a bug or intended behaviour?
If the latter, it would be nice if the release notes/migration guide 
would mention that in the Java API (all?) responses now have to be checked for failed shards.

**Comment by nik9000** [comment]
That makes sense to me.

@clintongormley - I think we have our answer to why.

I don't think we can call this a bug - it was probably intentional and being relied on for node to node communication - but it is a pain. It certainly should be in the list of breaking changes.

I've been thinking a lot about how a real Java API for elasticsearch (compared to coopting the internode communications API like we do now) would behave lately and I'm not sure what the right thing to do in this situation is. There was a failure and so the user should know about it so an exception makes sense. But the failure wasn't complete and you can learn _something_ from the response so throwing an exception feels a bit like throwing the baby out with the bathwater. Maybe throwing an exception the contains a reference to the original request....

**Comment by drallax** [comment]
Sounds great :)

**Comment by nik9000** [comment]
I've taken this one. For now I'll see about getting it documented. I'll make sure to bring this up against the Java API when that gets started.
