### ISSUE TITLE
Allow aliases to be renamed upon _restore

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#13681]
Currently, upon restoring an index, it's possible to rename one or more indices using the pattern/replacement properties.

It is often the case where aliases exist alongside indices with similar names. While less common, it's sometimes desirable to rename the _alias_ as well as the index to match (not identically, of course, but following similar results and patterns).

The annoying aspect is that this requires a secondary rename/replacement field and it needs to be distinctly different from the existing one.

I would propose:

``` json
"rename_alias_pattern": "audit_hist_(.+)",
"rename_alias_replacement": "audit_history_$1",
"ignore_global" : false
```

**Comment by clintongormley** [comment]
Hmmm... I wonder if we should restore aliases at all, or just always strip them on restore?

**Comment by pickypg** [comment]
@clintongormley I think by default, when you don't rename, that it makes a lot of sense to restore them. If you do rename them, then I agree that it makes things a bit murkier.

**Comment by apatrida** [comment]
We run into issues a lot with restoring temporary indexes that have aliases, would be good to have an option saying whether you want aliases restored or not for an index, and renaming them if you want (rename is less necessary if you have one index, but do make sense when you have unknown group of indexes that have the alias you want to rename)

**Comment by clintongormley** [comment]
My vote is simply to remove aliases during restore.  @imotov what do you think?

**Comment by imotov** [comment]
@clintongormley I think we should improve documentation and make `include_aliases` flag more visible.

**Comment by clintongormley** [comment]
Ah I didn't even know that option existed. Thanks @imotov

**Comment by ywelsch** [comment]
Discussed with @tlrx: It's documented in the same way as the other S/R options. We don't think this requires an extra open issue.
