### ISSUE TITLE
scrolled searches silently ignore 'from' search parameter

### ISSUE THREAD

**Issue by drallax** [elastic/elasticsearch#13684]
Our application happily creates scrolled search requests with a 'from' parameter > 0.
It looks like the value of 'from' is silently ignored, as the following test, demonstrates:
- indexes some documents
- request sorted results with from > 0, e.g. 4
- search normally: the first four matches are skipped, as expected
- search with scroll enabled: the first four matches are not skipped, this is not expected

reproduceable testcase (for ES-1.7.1, it seems to fail in ES-2.0.0-beta2 too)
```java
@Seed("1")
@ClusterScope(scope = ElasticsearchIntegrationTest.Scope.SUITE, numDataNodes = 1, numClientNodes = 1, transportClientRatio = 0, randomDynamicTemplates = false)
public class ESScrollIT extends ElasticsearchIntegrationTest {
    @Override
    protected Settings nodeSettings(final int nodeOrdinal) {
        return ImmutableSettings.settingsBuilder()
            .put("path.home", "target/es")
            .put("path.data", "target/es/data")
            .put("path.logs", "target/es/logs")
            .put(super.nodeSettings(nodeOrdinal))
            .build();
    }

    @Test
    public void testSortFromScroll() throws Exception {
        //index some documents
        createIndex("test");
        final Client client = dataNodeClient();
        client.prepareIndex("test", "test", "0").setSource("{ name: \"0\"}").execute().actionGet();
        client.prepareIndex("test", "test", "1").setSource("{ name: \"1\"}").execute().actionGet();
        client.prepareIndex("test", "test", "2").setSource("{ name: \"2\"}").execute().actionGet();
        client.prepareIndex("test", "test", "3").setSource("{ name: \"3\"}").execute().actionGet();
        client.prepareIndex("test", "test", "4").setSource("{ name: \"4\"}").execute().actionGet();
        client.prepareIndex("test", "test", "5").setSource("{ name: \"5\"}").execute().actionGet();
        refresh();
        ensureGreen("test");

        //sort by name and return the 5th result, once with scrolling, once without
        final SearchResponse normal = client.prepareSearch("test")
            .setTypes("test")
            .addSort("name", ASC)
            .setFrom(4)
            .setSize(1)
            .execute()
            .actionGet();
        final SearchResponse scroll = client.prepareSearch("test")
            .setTypes("test")
            .addSort("name", ASC)
            .setFrom(4)
            .setSize(1)
            .setScroll(timeValueMinutes(1))
            .execute()
            .actionGet();

        //make sure we get the same results from normal & scrolled searches
        assertEquals(6, normal.getHits().getTotalHits());
        assertEquals(6, scroll.getHits().getTotalHits());
        assertEquals(1, normal.getHits().getHits().length);
        assertEquals(1, scroll.getHits().getHits().length);
        assertEquals("4", normal.getHits().getHits()[0].id());

        //the next assertion fails with "expected <[4]> but was:<[0]"
        //setFrom(4) has silently been ignored?
        assertEquals("4", scroll.getHits().getHits()[0].id());
    }
}
```

I would have expected either
1) the same result for scrolled searches vs non scrolled 'normal' searches, or alternatively
2) an error message indicating that 'from' is not supported for scrolled searches

**Comment by clintongormley** [comment]
> I would have expected either
> 1) the same result for scrolled searches vs non scrolled 'normal' searches, or alternatively
> 2) an error message indicating that 'from' is not supported for scrolled searches

I agree with choosing from one of your two options.  I'm leaning towards option 2, because I'm not sure that `from` is useful in a scroll request and also, having a high `from` value may make the intial request very heavy.

**Comment by drallax** [comment]
For us, a scrolled search that supports `from` would be a useful thing to have.

It would allow us to return arbitrary slices of large result sets, or at least slices whose beginning is not too far removed (say 10,000 or 100,000 documents) from the first result.
In practice, i expect only moderately sized slices (of say a 1000 documents) when `from`  increases, 
but since our documents can be largish, it would be nice if we can use scrolled searches,
to process e.g. 100 documents at a time to prevent running out of memory.

I suppose we can work around this ourselves by either
- adjusting the ES query to return from+size results and skipping the first `from` results ourselves, or
- performing an initial search that finds the `uid` of the `from`'th result and then perform a scrolled search with an adapted query that only matches documents with larger uid's.

But it would probably be much more efficient if ES could do something like this internally?

**Comment by clintongormley** [comment]
It sounds like the newly added search_after parameter would be a better solution. See https://github.com/elastic/elasticsearch/issues/8192

**Comment by drallax** [comment]
after reading the search_after docs, i am not sure how it would help retrieving documents
starting from the n'th hit, without first consuming the n previous unwanted documents, 
which would be slow?

(i am probably missing something here, but i wonder what search_after is actually 
useful for since ES already has a range query that can be used to search after some term?)

**Comment by jimferenczi** [comment]
> after reading the search_after docs, i am not sure how it would help retrieving documents
starting from the n'th hit, without first consuming the n previous unwanted documents, 
which would be slow?

Unfortunately there is no magic and retrieving documents starting from the n'th hit is heavy in terms of memory and the scroll API is not designed for that (it is designed to scroll a query from the start efficiently). So what @clintongormley is saying is that you could:

- do an initial request with from=N and a sort compatible with `search_after`
- ... and then use `search_after` to scroll the results from the N'th hit.
`search_after` is much faster than using a range query, it is used to sort the top documents and not to match documents.
