### ISSUE TITLE
More Lucene suggesters

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#13692]
Lucene has a few available suggesters that would be nice to expose in Elasticsearch:
- [AnalyzingInfixSuggester](https://lucene.apache.org/core/5_3_0/suggest/org/apache/lucene/search/suggest/analyzing/AnalyzingInfixSuggester.html) (see #17029)
- [BlendedInfixSuggester](https://lucene.apache.org/core/5_3_0/suggest/org/apache/lucene/search/suggest/analyzing/BlendedInfixSuggester.html)
- [FreeTextSuggester](https://lucene.apache.org/core/5_3_0/suggest/org/apache/lucene/search/suggest/analyzing/FreeTextSuggester.html)

Any others?

**Comment by dbgrey44** [comment]
Any update on this ?
I wanted to use AnalyzingInfixSuggester for my auto complete needs. 

Is there some way by which I can use some analyzers or filters to achieve a similar behavior with the completion suggester. Any help will be greatly appreciated.

**Comment by jimczi** [comment]
cc @elastic/es-search-aggs

**Comment by coder-yuan** [comment]
+1 for infix suggester. And the alternative for now would be 
(1) completion suggester + term(or) phrase suggester?
or (2) edge ngram?

**Comment by javanna** [comment]
We have no concrete plans on adding more suggesters implementations to Elasticsearch at this time, closing for now.
