### ISSUE TITLE
Netty excption will index data

### ISSUE THREAD

**Issue by waldemarnt** [elastic/elasticsearch#13697]
Hello guys, hope you guys are fine.
I have a problem when i'll index some data in my elastic server this returns this error

**[2015-09-21 17:38:08,331][WARN ][http.netty               ] [Marvel Girl] Caught exception while handling client http traffic, closing connection [id: 0x92405db8, /127.0.0.1:38750 => /127.0.0.1:9200]
java.lang.IllegalArgumentException: invalid version format: TOOL/DOCUMENTS/33 HTTP/1.1**

I just downloaded the elastic from website and started, no have plugins or other kind of different things.
I see a lot of issue like that over the web but have no clear solution.
Waiting for you guys.
Thanks for the attention!

**Comment by clintongormley** [comment]
Hi @waldemarnt 

Something on your network is sending malformed requests to Elasticsearch.  Nothing to do with Elasticsearch.
