### ISSUE TITLE
some files have no license headers

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13703]
I noticed this when cleaning up javadocs.

The rules for "core" are too damn lenient. There should be no exclusions.

**Comment by markharwood** [comment]
Quick grep of all .java files missing "Licensed to Elasticsearch" produces this:

* guice: 
./main/java/org/elasticsearch/common/inject/*

	* Copyright (C) 2007 Google Inc.
	* Licensed under the Apache License

* Netty pipelining code
./main/java/org/elasticsearch/http/netty/pipelining/HttpPipeliningHandler.java
./main/java/org/elasticsearch/http/netty/pipelining/OrderedDownstreamChannelEvent.java
./main/java/org/elasticsearch/http/netty/pipelining/OrderedUpstreamMessageEvent.java

	* @author Christopher Hunt
	(Apache license listed here: https://github.com/typesafehub/netty-http-pipelining/blob/master/LICENSE)


* Joda-related
./main/java/org/joda/time/base/BaseDateTime.java
./main/java/org/joda/time/format/StrictISODateTimeFormat.java

	*  Copyright 2001-2011 Stephen Colebourne
	*  Licensed under the Apache License

So these exclusions all look to be where we have incorporated Apache-licensed code built for non-elasticsearch-related projects and hence not had a CLA.
I didn't manage to run the maven check-license plugin.

**Comment by jpountz** [comment]
> I didn't manage to run the maven check-license plugin. 

The license check is hooked to the compile phase, so just running "mvn compile" will check licenses. I think one reason why we can't run the license plugin at the moment is that we declare two license plugins (the codehaus and the mycila ones) that use the same namespace.

**Comment by jpountz** [comment]
I was looking at this issue as well and I can't find how to check for multiple licenses within the same source tree.

**Comment by jpountz** [comment]
We made some progress towards this on #14020 by checking all java files in the source tree instead of just those from the org.elasticsearch package. However there doesn't seem to be any way to check for multiple licenses in the same source tree with the license plugin, so I'm bumping this issue to 2.2, maybe the new build would help address this issue?

Another open question is whether we want to check licenses on other files such as ant/maven/gradle files?

**Comment by rmuir** [comment]
> However there doesn't seem to be any way to check for multiple licenses in the same source tree with the license plugin, so I'm bumping this issue to 2.2, maybe the new build would help address this issue?

This is fixed by using rat: https://github.com/elastic/elasticsearch/pull/15545
