### ISSUE TITLE
Leaky PatternTokenizer

### ISSUE THREAD

**Issue by achow** [elastic/elasticsearch#13721]
Analyzer component reuse does not interact well with `PatternTokenizer` (and possibly other tokenizers, but I haven't looked into them). https://github.com/elastic/elasticsearch/pull/6792 changed the `PatternAnalyzer` from lucene's deprecated version (that packaged its own `PatternTokenizer`) to a standalone `PatternTokenizer`. Under the hood, lucene uses `StringBuilder` to store field values during tokenization but never reclaims storage (e.g. with `trimToSize()`). This causes PatternTokenizer to grow to the largest field the Tokenizer encounters.

The use case we're encountering this issue with is using a custom `PatternTokenizer` for indexing logs, creating indices corresponding to log timestamp. We're running 1.6.2, but so far I don't see anything that this has been fixed in later versions. This really hurts with a large number of indices.

I was looking into closing Analyzers when indices go inactive, but it's been a bit rough trying to find the right place to put it. I'm sure there's probably a better solution as well. Reverting https://github.com/elastic/elasticsearch/pull/6792 is an option if lucene's PatternAnalyzer can be vendored (was removed in 5.x).

In the meantime, are there any short term solutions to explicitly freeing up Analyzers? `index.blocks.read_only` looked promising, but from what I can tell, it only causes requests to be rejected and doesn't release Analyzers (though I might be mistaken). Closing and reopening indices isn't a particularly good option for our use case either.

**Comment by achow** [comment]
Looking at this again, I think it's actually caused by https://github.com/elastic/elasticsearch/pull/6792. Lucene's `PatternAnalyzer.PatternTokenizer` didn't keep a `StringBuilder` around. Instead, it instantiated a `String` for whatever it was tokenizing.

Either way, reusing the TokenStreamComponent with that particular `PatternTokenizer` ends up being leaky.

**Comment by clintongormley** [comment]
Closing in favour of https://issues.apache.org/jira/browse/LUCENE-6814

**Comment by achow** [comment]
@clintongormley, that fix is only going 5.4 so only available for 2.0. I'd like to get a fix into 1.x as well.

**Comment by achow** [comment]
@clintongormley I've opened https://github.com/elastic/elasticsearch/pull/13804 to try to get a fix into 1.x. Could you please take a look?

**Comment by achow** [comment]
@mikemccand What's the status of forward porting this to 2.x?

**Comment by mikemccand** [comment]
@achow https://github.com/elastic/elasticsearch/pull/14571 was pushed to ES 2.0.x and 2.1.x, and ES 2.2.0 will use Lucene 5.4.x which already has the fix from https://issues.apache.org/jira/browse/LUCENE-6814 so I think all is good?

**Comment by achow** [comment]
@mikemccand Fantastic. Thank you!
