### ISSUE TITLE
Feature Request: Allocation setting to disable new shard allocation on a node

### ISSUE THREAD

**Issue by lb425** [elastic/elasticsearch#13723]
The request is for an allocation setting that can be used to prevent new shards from being allocated on a node while still allowing for rebalancing. 
A use case for this setting is when adding a new node. Should new indexes be created before the cluster has balanced the new node could end up with a disproportionate amount of new shards. In a heavily loaded cluster this could cause stability issues.   It would be preferable to have a setting that would allow the node to participate in rebalancing while not being allocated new shards.

**Comment by clintongormley** [comment]
I'm not really sure this is an issue..  For example, I created a whole bunch of indices on 5 nodes, disabled allocation and rebalancing, created a new index (which wasn't allocated), then added a new node.

I reenabled rebalancing. No rebalancing or allocation of the new index occurred until I allowed at least allocation of new primaries, all of which were allocated to the new node.  

Then I enabled allocation all allocation (which allowed the replicas to be allocated).   Shards from the new node were moved to other nodes, but it preferred the smaller shards.  This seems OK to me?

As soon as you start adding special rules and exclusions you run into situations where shards can't be properly allocated, which is a much bigger concern for me.

**Comment by lb425** [comment]
I'm sorry if there was confusion. I'm not trying to report a bug or an issue, because I believe everything is working how it's supposed to, I'm just trying to make a feature request.

On your 5 node cluster were you ingesting data?  The issue we have is that the new shards are all allocated to one, or a small number of nodes, which then are indexing all the incoming data as well as having shards balanced to them. 

What I'm seeing is that when a new indices are created for our time series data they are all allocated to the single newly added node. These indices are immediately indexing documents since they were created in response to time series data which continues until the time that another index is created (usually a day). (If this is the incorrect way to handle time series data then perhaps I could change that instead of ask for this feature)

In this case one node does the work of 8 nodes (since all shards are allocated to it). Should this have been the behavior I wanted I would have created indexes with just one shard and would probably be ok with whats going on. 

Unfortunately in my environment this causes issues, the worst being timeouts that cause nodes to drop out. To handle it now I create a large number of empty indexes that are allocated to the new nodes. I then slowly delete them allowing new shards to be allocated in a more uniform manner.

The feature request is for a cluster setting that prevents new shards from being allocated to a node while still allowing shards to be relocated to it as part of balancing. Something similar can be done be setting allocation rules on all the new indexes, but it would be preferable to have one cluster setting instead of a confusing mess of index level rules.

Some information about my environment:
16 Nodes, split into 2 groups
3600 indices
300GB of time series data per day (sometime being written to just one node in a group)

**Comment by ldimans** [comment]
+1

**Comment by lb425** [comment]
Here is a screen capture from Kopf showing how shards were allocated on an unbalanced cluster. The columns are Indices and the rows are nodes.

<img width="1281" alt="unbalancedclusterallocation" src="https://cloud.githubusercontent.com/assets/2752044/10265554/df214b94-69f1-11e5-89aa-64625eb4feb0.png">

**Comment by lb425** [comment]
Accidentally closed.

**Comment by wilsonlindelof** [comment]
+1

**Comment by clintongormley** [comment]
I've been thinking about this again.  I'm just not sure this is possible. How do you know when a node is new (or still new), what happens if you can't allocate new shards to any other nodes, etc.

I think a better approach would be to play with the [`total_shards_per_node` setting](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/allocation-total-shards.html) which would prevent all of the shards being allocated to the same node.

**Comment by iwasnobody** [comment]
@lb425 Do you find any workaround?
