### ISSUE TITLE
Drop old template syntax BWC

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#13729]
today we have a gazilion ways to specify templates and the parsing is a nightmare. We should drop the 1.x syntax in 3.0 but it might have implications on scripts store in the `.script` indes. We should find out if we need to `upgrade` those scripts in 2.x

**Comment by MaineC** [comment]
We discussed this yesterday - @colings86 @s1monw I think the conclusion was that this is not an issue as only the template itself is stored in the index, but not the rest of the request. Correct?

**Comment by clintongormley** [comment]
@MaineC has the bwc layer already been removed in master? If not, then this issue should still be open.

**Comment by colings86** [comment]
I think this should still be open. The PUT index script API is unaffected by the old/new style of specifying scripts, but the APIs that use scripts (aggs, update, template search etc.) still have code in the parser to parser the old style. I think that is what we need to remove the resolve this issue?

**Comment by clintongormley** [comment]
Related to https://github.com/elastic/elasticsearch/issues/14837

**Comment by clintongormley** [comment]
Related to #16651

**Comment by martijnvg** [comment]
When upgraded to 5.x, the indexed scripts have to be [re-added manually](https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_scripting.html#_python_migration_script) already. So if we just drop the 1.x syntax now, that wouldn't be a big of a deal?
