### ISSUE TITLE
Embedded node on-demand thread creation leaks caller context

### ISSUE THREAD

**Issue by mbechler** [elastic/elasticsearch#13736]
For the local node requests get directly submitted to a TheadPoolExecutor which, if not exhausted, will create new Workers/Threads on demand. Thread initialization leaks the original callers TCCL, AccessControlContext and InheritableThreadLocals. Depending on the environment this is a first class classloader leak.
As the worker can be reused from a totally different context I don't think there is any legitimate use for this context, but this might be different for the server threads.

For this usage pattern, the ThreadFactory should make sure not to leak any caller context. The first two leaks can be circumvented by unsetting or setting the TCCL, running in doAsPrivileged with a new AccessControlContext. Unfortunately there is no API to reset InheritableThreadLocals, that can only be achieved using reflection.

As I'm not sure about potential side effects compatability and performance-wise, what I would suggest is making the thread factory configurable.

**Comment by clintongormley** [comment]
Hi @mbechler 

Which version are you referring to?

**Comment by clintongormley** [comment]
@rmuir this sounds like your territory?

**Comment by rmuir** [comment]
there is no plan to allow permissions to setContextClassLoader anywhere in elasticsearch at the moment, it is denied, given that createClassLoader is also allowed. Maybe it changes in the future, but the combination of the two is too much.

**Comment by mbechler** [comment]
I'm not really sure I understand what you mean. This is not about the standalone server (where the described issue most certainly does not matter at all) but an embedded instance. Also it's not about having the ability to set a context classloader for some piece of code but about not leaking one from calling code. Also it's not only the context classloader that is a problem.

As I said, I was not really aware of the side-effects, if standalone is running with a SecurityManager (as I understand your comment) doing so generally is certainly out of the question.

But, right now I do have to wrap all my calls into the node client with a construct that drops TCCL, ACC and InheritableThreadLocals or otherwise I end up with massive classloader leaks. Scenario is OSGI where I'm running an elasticsearch node and a webapp container side-by-side - admittedly exotic - but the current code is conceptually wrong (one might very well argue this is a design flaw in the standard library - but fixing that will probably take years). 

If one was able to override the ThreadFactory this could be fixed for environments where it matters in just a few lines of code (one might even ship an alternative ThreadFactory implementation).

**Comment by rmuir** [comment]
Standalone is running with security manager and that is certainly the case we are trying to improve.

Honestly we don't test running any other way (container or anything) and I do not even know if it is possible or works anymore at all. 

I don't think the code is "wrong" because I don't think elasticsearch should be this wonder-do-it-all-jar-file, that is a standalone server to some people, a java client to other people, and then N exotic cases (like embedded servers) to others. It is too many pressures tugging at too many directions and it causes the server to be too flaky, too lenient, and too complicated. This is just my opinion.

**Comment by mbechler** [comment]
Well, embedded node is the mode of operation suggested by the docs for java clients, so that cannot be too exotic. Everything else it takes to get hit by this is client code that is more short-lived (e.g. get redeployed) than the node.

I'd still argue that the code is wrong, it is only correct by accident if there is a single calling context. Processing one callers requests with the AccessControlContext, TCCL, ... of another caller most certainly sounds not correct to me.

Again, I would already be very happy if I'm able to fix this for myself more easily which can be achieved by making the ThreadFactory configurable. I would even be willing to provide a patch, given it generally would be considered for merging.
