### ISSUE TITLE
function_score's score_mode of `avg` doesn't seem to work as expected

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#13732]
The `avg` `score_mode` for a `function_score` that has a single `function` with only a `filter` doesn't seem to actually compute the average.

If I replace the `avg` `score_mode` with `sum` I get the expected result.

This is a gist demonstrating the issue: https://gist.github.com/astefan/cb200eab777ded2b25df
Tested with ES 1.7.1.

**Comment by brwe** [comment]
At first I thought it is a bug too but this is actually expected. The avg is not computed as the avg of the scores like

```
(x1*w1 + x2*w2 + ... + xn*wn)/(n)
```

but instead we compute the weighted average:

```
(x1*w1 + x2*w2 + ... + xn*wn)/(w1 + w2 + ... + wn)
```


This was changed here: https://github.com/elastic/elasticsearch/pull/9004
The weighted average in a way computes the regular average of the `x`s without the weights but _pulls_ it a little closer to values that have a high weight.

I drew an image to explain what the weighted average does:

![avg-explain](https://cloud.githubusercontent.com/assets/4320215/10306908/7e259de6-6c2a-11e5-8ff9-12bb05f542c8.jpg)

It seems counterintuitive at first but it seems to make more sense and so far we only had a request for the weighted average but none for plain average. Do you need something different?

**Comment by clintongormley** [comment]
No further feedback. Closing
