### ISSUE TITLE
More Endless refresh-mappings

### ISSUE THREAD

**Issue by blackhole-em** [elastic/elasticsearch#13746]
As per https://github.com/elastic/elasticsearch/issues/10318 i'm seeing endless refresh-mappings happening as a result of ordering issues vs the master mapping.  The aforementioned article provides a work around (that says, should not be used in newer releases of ES).  On 1.7.2 the cluster stopped thrashing once the data nodes had the 'indices.cluster.send_refresh_mapping: false.

Please advise.

**Comment by clintongormley** [comment]
@blackhole-em please provide us with a copy of your mapping - something isn't being serialized properly.  It may already have been fixed in 2.0

**Comment by clintongormley** [comment]
No more feedback. Closing
