### ISSUE TITLE
`-` command line arguments must be passed before `--`

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#13741]
It looks like right now `-` command line arguments must be passed before `--` but that is confusing. Things like `ls` don't impose an order on the arguments so people aren't used to there being an order and it trips them up. Can Elasticsearch just allow them in any order?

**Comment by dakrone** [comment]
I believe this is fixed with the refactor of CLI parameters so I am closing this, feel free to re-open if I'm mistaken.
