### ISSUE TITLE
Indexing reserved fields inconsistent

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#13740]
If I create an index by indexing a document which contains a reserved field (eg `_source`, `_id`) then I get an exception.  However, indexing the same document again works, eg:

    DELETE t

    PUT t/t/1
    {
      "_id": 12345
    }

returns:

        {
            "type": "illegal_argument_exception",
            "reason": "Mapper for [_id] conflicts with existing mapping in other types:\n[mapper [_id] cannot be changed from type [_id] to [long]]"
         }

But indexing into an existing index works:

    PUT t/t/1
    {
      "_id": 12345
    }

This means that the following bulk request would throw an exception for the first document, but accept any following documents:

    DELETE t
    POST t/t/_bulk
    {"create": {}}
    {"_id":12345}
    {"create": {}}
    {"_id":12345}

Related to #10456

**Comment by markharwood** [comment]
Is it ever legal to pass a metadata field (_id,_version, _ttl etc) in the body of a doc?

**Comment by clintongormley** [comment]
No, not any more.

**Comment by markharwood** [comment]
OK. Trying out a patch that checks MapperService.isMetadataField() for legal fieldnames in the doc body. Anything else we need to tighten up in naming?

**Comment by markharwood** [comment]
I added a simple check in DocumentParser:

	if (MapperService.isMetadataField(currentFieldName)) {
		throw new MapperParsingException("Reserved field name [" + currentFieldName + "] passed in document body");
	}

The tests that failed were mainly "testIncludeInObjectBackcompat".
  - org.elasticsearch.index.mapper.ttl.TTLMappingTests.testIncludeInObjectBackcompat
  - org.elasticsearch.index.mapper.parent.ParentMappingTests.testParentNotSet
  - org.elasticsearch.index.mapper.parent.ParentMappingTests.testParentSetInDocBackcompat
  - org.elasticsearch.index.mapper.all.SimpleAllMapperTests.testIncludeInObjectBackcompat
  - org.elasticsearch.index.mapper.routing.RoutingTypeMapperTests.testIncludeInObjectBackcompat
  - org.elasticsearch.index.mapper.timestamp.TimestampMappingTests.testIncludeInObjectBackcompat
  - org.elasticsearch.index.mapper.id.IdMappingTests.testIncludeInObjectBackcompat

They look to check metadata-fields-in-the-body are safely ignored i.e have a comment like this:

            // _routing in a document never worked, so backcompat is ignoring the field

So do we break backcompat and now no longer tolerate these metadata fields by throwing exceptions?

**Comment by rjernst** [comment]
@markharwood No, we should not break backcompat. Here is the original PR that was supposed to block this: #11074. Prior to that PR, each meta field could override `includeInObject()` to return `true`, which would cause the mapper for that meta field to be added to the rest of the mappers for document types. Thus when encountering the field while parsing the document, it would find the metadata mapper, and parse. There was also logic inside the metadata mapper that allowed this parsing.

For backcompat, I kept the parsing logic in metadata mappers that supported it before. This can be removed in master, as well as the backcompat check to add select metadata fields to the regular mappers.  What must be happening here is the metadata mappers are still getting added to the regular mappers map. This shouldn't be happening on a new index. I'm still investigating why that is happening...

**Comment by rjernst** [comment]
One thing I notice is we should have an extra check similar to what you propose (but the impl of isMetadataField needs to be updated, because the list of metadata fields should no longer be static, because they can be added by plugins, as _size is now a plugin). So we should add your check, but guard with a backcompat check.

**Comment by rjernst** [comment]
This will block the action earlier, since right now, from the "good" case in Clint's example, you can see the field was actually parsed and it is trying to add the field to the mappings. This is too late.

**Comment by rjernst** [comment]
Note that fixing `isMetadataField` will require a little plumbing. This should not be a static method, which means passing down the metadata fields list when creating `GetResult`, and then doing the check before creating `GetField` (so get field should have a flag, instead of the current `isMetadataField()` which calls the static `MapperService` method.

**Comment by rjernst** [comment]
I have a change I'm testing that is minimally invasive for backport to 2.0. I will make a followup to cleanup `isMetadataField` to work with metadata fields added by plugins, but that requires a larger change to how metadata fields are added.

**Comment by clintongormley** [comment]
Closed by #14003
