### ISSUE TITLE
[Docs] System properties trump settings

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#13751]
For clients, it can sometimes be the case that users will specify their own system properties that happen collide with Elasticsearch's settings. In at least one case, I've come across the scenario when client-side code was attempting to talk to two separate clusters (one feeding from another).

On the client-side, a system property was being generically set like `elasticsearch.cluster.name` (or `es.cluster.name`) because the application's property management made it easier to do this and decouple from the data store. This led to the problem where the secondary cluster's `cluster.name` setting was being silently ignored.

To counter this problem, it's as easy as telling the Elasticsearch settings to ignore system properties by setting `config.ignore_system_properties` to `false`. It would be better to not have system properties sneaking into your settings as well, but this is rarely an intentional problem so it can go unnoticed for awhile unless something actually stops working entirely.

I'd be happy to make the PR myself, but I am not sure where it should go, so I'm hoping that someone will have a good suggestion.

Also, perhaps we should warn within the settings builder if a property gets overwritten for any reason? It seems like a bad approach for someone to set, then reset a setting _intentionally_.

**Comment by rjernst** [comment]
Loading system properties are specifically meant to allow overrides. Why would we warn on that? This sounds like a user problem.

**Comment by pickypg** [comment]
I agree that it's a user problem, especially with clients (where it's far less expected in my opinion), but perhaps "warn" should be translated to "DEBUG".

**Comment by dakrone** [comment]
This was fixed in 5.0 with https://github.com/elastic/elasticsearch/pull/18198
