### ISSUE TITLE
filter data by using @timestamp field of  elasticsearch query dsl ,but it dont work, please help

### ISSUE THREAD

**Issue by adastudy** [elastic/elasticsearch#13760]
mapping info of index
=======================================================
{
"test_php_log-2015.09.23": {
"aliases": { },
"mappings": {
"php_error": {
"properties": {
"@timestamp": {
"type": "date",
"format": "dateOptionalTime"
},
"@version": {
"type": "string"
},
"host": {
"type": "string"
},
"message": {
"type": "string"
},
"path": {
"type": "string"
},
"type": {
"type": "string"
}
}
},
"php_fpm": {
"properties": {
"@timestamp": {
"type": "date",
"format": "dateOptionalTime"
},
"@version": {
"type": "string"
},
"host": {
"type": "string"
},
"message": {
"type": "string"
},
"path": {
"type": "string"
},
"type": {
"type": "string"
}
}
}
},

and this is my elasticsearch query dsl ,but seem in result ,it is dont work

curl -XGET http://192.168.9.99:9200/meipai_php_log-2015.09.23/php_error/_search/ '
{
    "query" : {
        "filtered" : {
            "filter" : {
                "range" : {
                    "@timestamp" : {
                        "gt": "now - 2h"
                    }
                }
            }
        }
    }
}'

===there are part of result =====

{
"took": 6,
"timed_out": false,
"_shards": {
"total": 5,
"successful": 5,
"failed": 0
},
"hits": {
"total": 54592,
"max_score": 1,
"hits": [
{
"_index": "test_php_log-2015.09.23",
"_type": "php_error",
"_id": "I7ver7QFQk2XZPN8_CvNQg",
"_score": 1,
"_source": {
"message": "[23-Sep-2015 10:19:01 Asia/Shanghai] PHP Warning: PDOStatement::execute(): Error reading result set's header in /www/xxxx.com/libraries/Db.php on line 484",
"@version": "1",
"@timestamp": "2015-09-23T02:19:01.483Z",
"type": "php_error",
"host": "xxx72",
"path": "/www/log/php_error.log"
}
}
,

**Comment by dadoonet** [comment]
Please join us on https://discuss.elastic.co/ 
We will help you there.
