### ISSUE TITLE
ElasticSearch doesn't provide any query by which you can get distinct documents based on a field value

### ISSUE THREAD

**Issue by temaniarpit27** [elastic/elasticsearch#13767]
There is no query in ElasticSearch by which we can remove some documents from a set of documents which have same key value pair.

**Comment by clintongormley** [comment]
There are many many definitions of what is considered to be a duplicate document.  You could use a top_hits aggregation to find duplicates, or perhaps a more-like-this query, or the [carrot2](https://github.com/carrot2/elasticsearch-carrot2) or [Entity Resolution](https://github.com/YannBrrd/elasticsearch-entity-resolution) plugins
