### ISSUE TITLE
Not Query: Investigate if we can deprecate short version

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#13761]
Currently the Not Query can have two version, either directly starting with the inner query or nesting it in an additinal `filter` element:

```
"not" : {
                "range" : {
                    "postDate" : {
                        "from" : "2010-03-01",
                        "to" : "2010-04-01"
                    }
                }
          }
```
or 
```
"not" : {
                "filter" :  {
                    "range" : {
                        "postDate" : {
                            "from" : "2010-03-01",
                            "to" : "2010-04-01"
                        }
                    }
                }
          }
```

The current NotQueryParser supports both versions, but it would be beneficial to be able to remove one version, so this issue is here to discuss whether and how we can deprecate the short version.

**Comment by clintongormley** [comment]
The only purpose of `not` these days is as a short cut for `bool.must_not`.  I'd keep the short version and remove the long version.

**Comment by jpountz** [comment]
I think we should deprecate all versions of `not`. I remember some people arguing that `not` was important for the query DSL so that you could do things like:

```java
{
  "query": {
    "filtered": {
      "query": /* some_query */
      "filter": {
        "not": { /* some filter */ }
      }
    }
  }
}
```

However in the meantime we deprecated the `filtered`, `and` and `or` queries and `bool` is now the only way to combine several filters together, so all uses of the `not` filter can be replaced with a `must_not` clause (which will also execute faster). For instance the above query becomes:

```java
{
  "query": {
    "bool": {
      "must": /* some_query */
      "must_not": { /* some filter */ }
    }
  }
}
```

**Comment by clintongormley** [comment]
I'm good with that

**Comment by cbuescher** [comment]
So are we good with deprecating the complete `not` query from 2.x on and delete in 3.0 like with `and` and `or`? I can start with that.

**Comment by javanna** [comment]
+1

**Comment by cbuescher** [comment]
@jpountz @javanna opened PR against 2.1 for deprecation, mind to take a look if this needs additional changes in the docs? Otherwise I'll also do PR for deletion on master.
