### ISSUE TITLE
Indexed scripts can't be used for sorting by using the Java API due to hardcoded parameter name

### ISSUE THREAD

**Issue by mmelitzer** [elastic/elasticsearch#13763]
ScriptSortBuilder uses the hardcoded String "script" for the script/script_id/file parameter when using a script to sort query responses.
"script" works for both an inline/dynamic script and when referring to a script file name.
"file" works for referring to a script file name.
"script_id" NEEDS to be used when referring to an indexed script.

When using the SortBuilders.scriptSort it uses ScriptSortBuilder which always sets the "script" parameter name, this makes it impossible to use an indexed script as the parameter would have to be "script_id".

**Comment by clintongormley** [comment]
Hi @mmelitzer 

This has been fixed in 2.0
