### ISSUE TITLE
Custom plugin can no longer access parseObject method in 2.0 beta

### ISSUE THREAD

**Issue by bwsawyer** [elastic/elasticsearch#13775]
While updating our elasticsearch plugin to support the upcoming 2.0 release, we noticed that the parseObject method which used to be publicly accessible, has become package-private in a package-private class (DocumentParser.java) See #10802. 

Any reason this can't be public anymore?

**Comment by clintongormley** [comment]
@rjernst any ideas?

**Comment by rjernst** [comment]
I would need to know more about what the plugin is trying to do. @bwsawyer can you explain your intended use of parseObject?

**Comment by bwsawyer** [comment]
The plugin adds fuzzy name matching (for more info see the slides posted here http://www.meetup.com/Elasticsearch-Boston/events/222682277/)
We have a custom Mapper that generates additional fields based on the indexed name string.  These get indexed as a nested object. Currently in 1.x this is a simple matter of creating an ObjectMapper and calling parse, but in 2.0 this no longer seems possible.

**Comment by rjernst** [comment]
> a simple matter of creating an ObjectMapper
@bwsawyer Could you elaborate on this? Were you somehow overriding ObjectMapper? 

Part of the refactorings were to decouple parsing for a single field type, from parsing the entire document. Before, parsing the document was mixed back and forth between "object" parsing, and concrete fields. This decoupling meant moving part of ObjectMapper to a new class, DocumentParser, which was dedicated to parsing the actual document.

While there is still work left to do with mappings, have you considered moving this logic out of mappings altogether? This seems like something that belongs more at the document construction before sending to elasticsearch, or perhaps with a custom sub-plugin in the future of the upcoming ingest plugin (#14049).

**Comment by clintongormley** [comment]
No further feedback. Closing
