### ISSUE TITLE
Rename `_doc` to `_any`?

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#13789]
This sort option has no practical interest besides being the fastest sort option. Renaming to `_any` would allow to have more flexibility in the future and eg. return shards sequentially instead of in parallel, ...

**Comment by clintongormley** [comment]
What about `_disable` or `_disabled`?

**Comment by jpountz** [comment]
I'm fine with it.

**Comment by clintongormley** [comment]
Actually, I'm good with `_doc` - let's leave this as is.
