### ISSUE TITLE
Elasticsearch is deleting some documents by itself 

### ISSUE THREAD

**Issue by jorgadan** [elastic/elasticsearch#13807]
I'm having a real hard issue, elasticsearch on a production server is deleting a lot of documents, when the index pass over 1.4 GB begins deleting a lot of documents, until now 2477 documents, help please!

**Comment by jpountz** [comment]
@jorgadan Can you give more information about the issue you are seeing (elasticsearch version, what the actual symptoms are, etc.)

**Comment by jorgadan** [comment]
Ok, I had an index and I created a copy for fixing some mapping errors and then I reindex from the copy to the original with the reindex plugin, but when I do localhost:9200/_cat/indices/v my original index is 1.4 GB and my copy is 1.7 GB, and the original says that there are 2270 deleted documents but I haven't deleted any doc.

**Comment by mikemccand** [comment]
Did you replace any already previously indexed document?  This is a delete + add under the hood.

Or, did you hit any exceptions while indexing some documents?  In some cases this results in marking the failed document as deleted.

**Comment by clintongormley** [comment]
@jorgadan this sounds like simple misunderstanding.  The best place for discussions like this is in the forum.  http://discuss.elastic.co/

if you find a bug, feel free to reopen
