### ISSUE TITLE
can NOT do template query on updated search template

### ISSUE THREAD

**Issue by blingwang** [elastic/elasticsearch#13803]
Use ElasticSearch 1.5.
Create a search template, then update it.
Confirm the search template is updated by retrieving it: GET /_search/template/myTemplate
We can find that the search template is correctly updated.
However, when we try to do template query using 'myTemplate', ES still uses the old template.

**Comment by clintongormley** [comment]
Fixed in https://github.com/elastic/elasticsearch/pull/10526
