### ISSUE TITLE
Elastic Search cluster not auto repairing (1.7.2)

### ISSUE THREAD

**Issue by trikosuave** [elastic/elasticsearch#13808]
I have es 1.7.2 and have a cluster of 10 nodes. I wanted to scale down to ten, so I terminated one of the boxes and watched hte cluster status change from green to yellow. Before the upgrade to 1.7.2 from 1.4.5, it will automatically relocate all the shards.
Now it sits with a bunch of unassigned_shards forever. I found a fix where I run the following:

curl -XPUT 'localhost:9200/_cluster/settings' -d '{
    "transient" : {
        "cluster.routing.allocation.enable" : "all"
    }
}'

This fixed my issue and my cluster went back to green. However, I need to run that command every time I teardown a node on my way down to 5. Before I never had to run that command and I could safely destroy one node, one by one, going from green to yellow back to green on its own. 

I would eventually like this to autoscale, but cannot do that if I need to enable allocation each time i drop a node. 

Any thoughts? 

Thanks

**Comment by clintongormley** [comment]
@trikosuave please ask these questions on the forum instead: http://discuss.elastic.co/

Presumably you had allocation disabled for some reason (maybe you set it during the upgrade). Once you reset it to `all`, things work as expected.

**Comment by trikosuave** [comment]
Yes, I when I set it to 'all', it started assigning the unassigned shards. However, the next time a node went down, its shards went to unassigned where they stayed until I set it to 'all' again. Hence the *issue*. I won't always be there when a node goes down to "manually" tell it to assign all the unassigned shards. I should only have to set it once and have it take care of itself from then on. 

I'm not treating github/issues as a forum. I am reporting an issue I have that I did not have before the upgrade to 1.7.2

Thank you.

**Comment by bleskes** [comment]
@trikosuave just double checking - how long did you wait for shard to be allocated after a node went down? In 1.7.2 we wait for 1m to give the node a chance to come back up (and avoid unneeded recoveries on start up). See [documentation here](https://www.elastic.co/guide/en/elasticsearch/reference/current/delayed-allocation.html?q=node%20left%20allocation#delayed-allocation).
