### ISSUE TITLE
Unreproducible failure of MinimumMasterNodesIT#simpleMinimumMasterNodes

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#13810]
`MinimumMasterNodesIT` failed for me today but I wasn't able to reproduce the failure by rerunning it. Here is the rerun command:
```shell
mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch:elasticsearch -Dtests.seed=A956287610A0C2F7 -Dtests.class=org.elasticsearch.cluster.MinimumMasterNodesIT -Dtests.method="simpleMinimumMasterNodes" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=lv -Dtests.timezone=America/Costa_Rica
 ```

[This](https://gist.github.com/nik9000/f7e02c84da51eab18c51) is the output of the failure. When I compare it to a test run that passes it looks like the cluster isn't able to connect to itself properly. The only other difference I see is the port numbers - the passes connect on `94xx` but the failures try `99xx`.

**Comment by bleskes** [comment]
@nik9000 it's hard to tell what's going on - it looks like the log are cut off in half, I don't see any of the logs in the test (info level). Als I'm not sure I follow what you mean with the `94xx`. I presume you don't have a complete dump lying somewhere/this is what the test produced?

**Comment by nik9000** [comment]
> @nik9000 it's hard to tell what's going on - it looks like the log are cut off in half

That was the output that mvn logged for the failure.

> Also I'm not sure I follow what you mean with the 94xx

The port were different.

**Comment by clintongormley** [comment]
This failure is old. Closing
