### ISSUE TITLE
Elasticsearch 2.0.0-beta2 does not accept field names with periods

### ISSUE THREAD

**Issue by vichargrave** [elastic/elasticsearch#13818]
I set up an instance of Elasticsearch 1.7.2 that has an index where many of the field names contain periods, e.g. "field.a.x", "field.b.x", etc.  I was able to index and retrieve data from this index with no trouble. When updated to 2.0.0-beta2, Elasticsearch failed to start giving me an error message indicating that the 1.7.2 index could not be upgraded because the field names have periods.

**Comment by xuzha** [comment]
I think this is on purpose. See more in this commit: https://github.com/elastic/elasticsearch/commit/aed1f68e494c65ad50b98a3e0a7a2b6a794b2965

**Comment by vichargrave** [comment]
As far as I'm concerned it is a bug.  However, if that is the way it is going to be then I'll have to live with it.  Thanks for the response.

**Comment by dadoonet** [comment]
Yes. See here the documentation: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/_mapping_changes.html#_field_names_may_not_contain_dots

I think that the migration plugin would tell you that.

**Comment by clintongormley** [comment]
> As far as I'm concerned it is a bug. 

Allowing them in the first place was a bug.  It was impossible to distinguish between objects and fields with embedded dots.
