### ISSUE TITLE
Delete scroll returns empty response

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#13817]
When calling delete scroll api (eg. curl -XDELETE localhost:9200/_search/scroll/_all or against individual scroll ids), the api response (using 1.7.1) returns an empty response.  It will be more user friendly to provide some information on whether the scroll deletion is successful, etc..

**Comment by eskibars** [comment]
When deleting an individual scroll ID, ES does produce a 200 in the header if successful and a 404 if the scroll ID wasn't found (doesn't exist, was already deleted)

**Comment by ppf2** [comment]
Yah it does, it will be nice to provide something in the response body though just to be consistent with our other apis :)
