### ISSUE TITLE
sum aggregation got wrong answer

### ISSUE THREAD

**Issue by caipeichao** [elastic/elasticsearch#13822]
I'm using `1.3.4`. Java version `1.7.0_71-b14`.
Sum aggregation goes wrong in my production environment.

The mapping is:

``` json
{
  "activity": {
    "date_detection": false,
    "properties": {
      "partnerCode": {
        "type": "string",
        "fields": {
          "raw": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      }
      "payAmount": {
        "type": "long"
      }
    },
    ...
  }
  ...
}
```

When I send a aggregation query:

``` json
{
        "query":{
                "filtered":{
                        "filter":{
                                "bool":{
                                        "must":[
                                                {"term": {"activity.partnerCode.raw":"xxx"}}
                                        ]
                                }
                        }
                }
        },
        "aggs": {
                "a": {
                        "sum": {
                                "field": "activity.payAmount"
                        }
                }
        },
        "size": 0
}
```

I got the response:

``` json
{
    "took":9562,
    "timed_out":false,
    "_shards":{"total":2,"successful":2,"failed":0},
    "hits":{"total":1911,"max_score":0.0,"hits":[]},
    "aggregations":{
        "a":{"value":5.083666008154969E20}
    }
}
```

The `payAmount` stores how much money was spend in a trade. No customer had that much money.

I use scan&scroll to export documents, and sum `payAmount' getting 15094439.

It seems index is corrupted and I don't know how to fix it.

**Comment by clintongormley** [comment]
@caipeichao hmmm.. i'd check the values of the payAmount field that is being used for this calculation.  Perhaps something like using a comma instead of a period for numbers?

if you think the index is corrupted, can you reindex?

**Comment by caipeichao** [comment]
@clintongormley Thanks.

The payAmount is really integers like 10000, 12000, 1999. no comma no decimal.

I have reindexed but not working: I read from the index and write back to the same index. some indexes is corrected, but some indexes is still.

**Comment by justjico** [comment]
@caipeichao I faced a similar issue once, my problem was at least one mapping in one of the indices was wrong. You should verify that across all your indices there's no other field named "payAmount" that has a  different type than "long", it doesn't matter if it's a different type, or is nested differently, if it's the same name it will cause something like this.

**Comment by clintongormley** [comment]
@justjico good thinking - most likely the cause

**Comment by caipeichao** [comment]
Thanks! I would check the mapping these days and give you a feedback.

**Comment by caipeichao** [comment]
I checked the mapping, there is only one `payAmount` in my mapping.

**Comment by caipeichao** [comment]
So, that's likely a index corruption. Then I will try to reindex and check whether fixed.

**Comment by caipeichao** [comment]
OK, I confirm it's index corruption. Because I reindexed by copy data to another index, and sum aggregation goes correct.

**Comment by clintongormley** [comment]
thanks for letting us know @caipeichao
