### ISSUE TITLE
Add doc match score support to percolate api

### ISSUE THREAD

**Issue by ncolomer** [elastic/elasticsearch#13827]
The [percolate API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-percolate.html#_percolate_api) documentation mentions `track_scores` and `sort` options in the *Additional request body options* section. More precisely, we can read the following notes, respectively:
> The _score is based on the query and represents how the query matched the **percolate query’s metadata, not** how the document (that is being percolated) matched the query.
> [...]
> Like `track_score` the score is based on the query and represents how the query matched to the percolate query’s metadata and **not** how the document being percolated matched to the query.

I'm wondering why there is nothing in the API about the score of the document itself (being percolated) among the various percolator queries?

I read somewhere that this would be due to hit score being relative to its resultset, and that in a percolator query, we only consider one document at a time, so the score on each percolator query is not really relevant.

I was expecting #3506 to be the solution, but it's not related after having a look. Such a feature is also mentioned [here](http://elasticsearch-users.115913.n3.nabble.com/Percolate-Query-Scoring-and-Fields-td4050649.html) in the mailing list but there is no technical answer.

Can you confirm? Is there any way/plan to get a percolation score?

**Comment by martijnvg** [comment]
@ncolomer Scoring how percolator queries match with the document being percolated requires different scoring then exists today in search which is based tf/idf. But this feature is interesting and I think this should be made possible in the percolate api. I think the score should be based on proximity, how close the matches are in the document being percolated.

**Comment by ncolomer** [comment]
@martijnvg thanks for your answer!

You mean that, the way percolation is implemented today, it does not benefit from internal scoring tools (that the regular search API does for instance)?

Actually, this score would be useful to compare 2 consecutive docs being percolated: if they both match the same percolation query, it might be interesting to give them a score (ie. how well they match the query) to compare them.

**Comment by martijnvg** [comment]
> You mean that, the way percolation is implemented today, it does not benefit from internal scoring tools (that the regular search API does for instance)?

Right now there is just no scoring on how a query matches with the document being percolated. So I think this should be added at some point. The score that is being returned by the percolate api is just how the percolator query in the percolate api matches with the metadata on the percolator query.

**Comment by martijnvg** [comment]
Now that the core percolator has been refactored to be a Lucene query adding scoring to the percolator has been made much easier. And with the upcoming refactoring in #16349 (replacing the percolate api with percolator query in query dsl) exposing the scores from how queries match with the MemoryIndex becomes a low hanging fruit. (right now the percolator just ignores that score)

**Comment by ncolomer** [comment]
Thanks a lot @martijnvg! :+1:
