### ISSUE TITLE
bin/plugin should be able to resolve dependencies

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#13823]
If you have one plugin that depends on another you have to install both of them now. It'd be nice if you could just install the one you want and both come down and be installed. 

I admit this is a bit weird with classloader isolation for plugins, but its still certainly possible. Imagine a plugin that does dictionary based analysis and each language dictionary is another plugin. Or the watcher and license plugins.

**Comment by dadoonet** [comment]
Is it the same as #11404 ?

**Comment by rjernst** [comment]
This simply won't work right now. We should get the ability for isolated plugins to communicate working before we think about dependencies at all.  Skipping isolation for plugins is deprecated (it was immediately when it was added), and it needs to be removed before doing anything else with this.

**Comment by rmuir** [comment]
its too complex for plugins to have hard dependencies on each other, we are straining as is to support it, it needs to be removed ASAP.

**Comment by nik9000** [comment]
I agree its a dupe.
