### ISSUE TITLE
_score value doesn’t match the return value of a script_score

### ISSUE THREAD

**Issue by cldsnchz** [elastic/elasticsearch#13833]
When the following `script_score` is executed the explain shows a different _score value than the one returned by the script

```
{
  "query":{
    "function_score":{
      "functions":[
        { "script_score":{ "script":"1443150000000" } }
      ]
    }
  }
}
```

This is what the explain shows:

```
value: 1443150040000
description: "script score function, computed with script:"1443150000000"
```

**Comment by clintongormley** [comment]
`_score` is a floating point.  Your number is too high to be represented accurately by a floating point

**Comment by cldsnchz** [comment]
Is there any plan to change `_score` from float to double? That will allow to use timestamps as scores (I'm working on a use case that needs that feature).
