### ISSUE TITLE
Invalid json

### ISSUE THREAD

**Issue by osallou** [elastic/elasticsearch#13839]
Hi,
I face an invalid JSON answer with elasticsearch 1.4.5 with agregations. Without aggregation, query is fine.

My query:

    curl -XGET 'http://localhost:9200/toxsign/signature/_search' -d '{
    "query" : {
    "term" : { "contributors" : "osallou" }
    },
    "aggs": {
          "organism": {
              "terms": {
                 "field": "title"
              }
          }
     }
    }
    '

    {"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"toxsign","_type":"signature","_id":"560a38bf2e71a81fb95bccfb_1414e60a-a2bb-40ce-959e-7e67b4eaff92_48dae30e-3524-4a3e-8185-2486ebf35b95","_score":1.0,"_source":{"submission_date": 1443503263, "status": "private", "confidence": "", "last_updated": 1443503263, "description": "data1", "contributors": "osallou", "title": "test2", "treatments": [{"title": "treat2", "signatures": [{"genomic": [{"tissue": "genomic1", "id": "08cde85f827848e0a3f7a997a4c5db1c"}], "physio": [{"tissue": "tissue1", "id": "4c62413a7232455c948a7ba723795527"}], "id": "48dae30e-3524-4a3e-8185-2486ebf35b95"}], "organism": "human", "description": "sample", "id": "1414e60a-a2bb-40ce-959e-7e67b4eaff92"}], "dataset": "560a38bf2e71a81fb95bccfb", "owner": "xxx"}{ "index" : { "_index" : "toxsign", "_type": "signature" , "_id" : "560a38bf2e71a81fb95bccfb_1414e60a-a2bb-40ce-959e-7e67b4eaff92_d8560884-9fa3-431f-9739-04228dc728cb" } }}]},"aggregations":{"organism":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"test2","doc_count":1}]}}}

The problem is here:

    "owner": "xxx"}{ "index" : {

The following is added directly in the hit answer, with an invalid json structure

    { "index" : { "_index" : "toxsign", "_type": "signature" , "_id" : "560a38bf2e71a81fb95bccfb_1414e60a-a2bb-40ce-959e-7e67b4eaff92_d8560884-9fa3-431f-9739-04228dc728cb" } }

**Comment by clintongormley** [comment]
Hi @osallou 

You have indexed a document with invalid JSON, and that is exactly what you are getting back. 

This should be caught by https://github.com/elastic/elasticsearch/pull/11414 in 2.0, but apparently this is still broken: https://github.com/elastic/elasticsearch/issues/13855
