### ISSUE TITLE
Change logging settings dynamically

### ISSUE THREAD

**Issue by vad1m** [elastic/elasticsearch#13841]
Hello,

it would be nice to have possibility to dynamically change logging settings without restarting elasticsearch (like watchdog on logger config).

Here is some hints about log4j:

http://www.theserverlabs.com/blog/2010/04/22/dynamically-changing-log-level-with-weblogic-log4j-jmx-and-wlst/
http://stackoverflow.com/questions/4598702/dynamically-changing-log4j-log-level

**Comment by polyfractal** [comment]
Changing the logging level dynamically at run-time is available through cluster-wide settings: https://www.elastic.co/guide/en/elasticsearch/guide/current/logging.html

If you want to change the root logger (e.g. to change all the loggers at once), the syntax is `_root`:

```
PUT /_cluster/settings
{
    "transient" : {
        "logger._root" : "DEBUG"
    }
}
```
