### ISSUE TITLE
Test distributions against SLES 11 SP3/4

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#13850]
In order to be sure that packages (tar.gz, RPM does not work at the moment, same issues as with CentOS 5), we should add SLES 11 to the list of tested distributions with vagrant.

However there does not seem to be a working SLES11 distro available. The only existing and working one is SP1, which is really old (SP is Service Pack and kind of a release).

In order to run the tests we first need a SP3 vagrant image and then run the tests against it. @jjfalling offered to take a look here. After this we can run the tests on SLES, first the tar.gz distribution and later, once we decide to create a second RPM supporting older distros, we could run that one against the image.

**Comment by jasontedor** [comment]
Closing in favor of #17690.
