### ISSUE TITLE
When setting multi zone configuration, elasticsearch fails to start

### ISSUE THREAD

**Issue by ajaybhatnagar** [elastic/elasticsearch#13852]
Settings in elasticsearch.yml  : 

cluster.routing.allocation.awareness.attributes: zone
cluster.routing.allocation.awareness.force.zone: zone1,zone2
node.zone: zone1

Once these lines were commented out in config, it started properly.

Error reported in logs : 

[2015-09-29 14:43:30,693][ERROR][org.elasticsearch.bootstrap] Exception
org.elasticsearch.common.inject.CreationException: Guice creation errors:

1) Error injecting constructor, SettingsException[Failed to get setting group for [cluster.routing.a
llocation.awareness.force.] setting prefix and setting [cluster.routing.allocation.awareness.force.z
one] because of a missing '.']
  at org.elasticsearch.cluster.routing.allocation.decider.AwarenessAllocationDecider.<init>(Unknown
Source)
  while locating org.elasticsearch.cluster.routing.allocation.decider.AwarenessAllocationDecider
    for parameter 1 at org.elasticsearch.cluster.routing.OperationRouting.<init>(Unknown Source)
  while locating org.elasticsearch.cluster.routing.OperationRouting
    for parameter 2 at org.elasticsearch.cluster.service.InternalClusterService.<init>(Unknown Sourc
e)

**Comment by ajaybhatnagar** [comment]
This is for beta 2 release.

**Comment by jpountz** [comment]
You should replace `cluster.routing.allocation.awareness.force.zone`with `cluster.routing.allocation.awareness.force.zone.values`

**Comment by jasontedor** [comment]
You need to use

    cluster.routing.allocation.awareness.force.zone.values

Your setting is missing `values` on the end.
