### ISSUE TITLE
Make floating-point numbers dynamically mapped as floats instead of doubles by default

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#13851]
For numbers around 1, precision is about 1e-7. My sentiment is that it would be enough for 99% of use-cases so maybe we should switch to floats to cut disk requirements by half when using the default configuration.

**Comment by rjernst** [comment]
+1

**Comment by rmuir** [comment]
+1

**Comment by polyfractal** [comment]
+1!
