### ISSUE TITLE
Trailing JSON object should throw invalid JSON exception

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#13855]
The following document is accepted with throwing an invalid json exception:

    PUT t/t/1
    {
      "foo": "bar"
    }{}

Apparently this is not being caught by the changes in https://github.com/elastic/elasticsearch/pull/11414

**Comment by xuzha** [comment]
@clintongormley , I just tested this against 2.0, seems changes in #11414 do catch this and throw `mapper_parsing_exception` [here](https://github.com/elastic/elasticsearch/blob/6885ab96805990d83e57dd0baded83252d7a2e0e/core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java#L142):

**Comment by clintongormley** [comment]
This is very curious.  #11414 was merged into beta1, but beta1 still fails to catch this malformed document.  However beta2 does throw an exception.  Not sure what else changed, but this appears to be fixed so I'll close
