### ISSUE TITLE
Add warning on cluster.routing.allocation.balance settings

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#13866]
https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-update-settings.html#_balanced_shards

Have yet to see a successful usage of these balance settings.  On the contrary, have seen end users from different deployments trying to alter these from the defaults and ended up causing more unbalancing issues in their cluster and had to revert to the defaults as the resolution.

Can we add a warning on these settings and discourage users from changing them?

**Comment by dakrone** [comment]
> Can we add a warning on these settings and discourage users from changing them?

I think they should be removed from the documentation (ie, expert-only settings!)

**Comment by ppf2** [comment]
+1 :)

**Comment by debadair** [comment]
Removed as of 2.0.
