### ISSUE TITLE
compile-time scan for accessibility issues on 2.x

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13867]
Simon solved most of this with java 8 method references in trunk, but we need another solution for java 7. There are two things ideally to check:
- `@Inject`ed methods/constructors are public and their classes are public.
- subclasses of `TransportRequest` are public and have a public no-arg constructor

I tried to make sure those things delivered good exceptions when fixing the code this way initially. I also used grep and IDE class hierarchy and stuff, and spent a lot of time. But 2.x is a different codebase, which will change too, and it would be nicer if the build failed with a static scan somehow. It could be a separate evil tool we launch from ant even. :)

Here is the meat of my changes so you get the idea:

https://github.com/elastic/elasticsearch/commit/e1efd5f6baf8dec1c23c79b346b8a29f234a98bb

**Comment by jasontedor** [comment]
I do not think this is a problem any longer.
