### ISSUE TITLE
elasticsearch service not starting on Debian 8.2 boot

### ISSUE THREAD

**Issue by gfairchild** [elastic/elasticsearch#13865]
Elasticsearch 1.7.2 is installed (using the Debian repo you guys provide) and works properly. When I run `sudo service elasticsearch start`, it starts up and runs as expected. I've set it up to start on boot by issuing `sudo update-rc.d elasticsearch defaults 95 10`. `elasticsearch` exists in both `/etc/init.d` and `/etc/rc[0-6].d`. Every time I boot my server, though, it doesn't start; I have to boot it manually. The only thing that exists in `/var/log/elasticsearch/elasticsearch.log` is this:

```
[2015-09-29 17:27:10,696][INFO ][node                     ] [Changeling] stopping ...
[2015-09-29 17:27:10,748][INFO ][node                     ] [Changeling] stopped
[2015-09-29 17:27:10,748][INFO ][node                     ] [Changeling] closing ...
[2015-09-29 17:27:10,754][INFO ][node                     ] [Changeling] closed
```

What might be causing this? I'm not sure where to look. I've grepped the log files in `/var/log/` without success.

**Comment by tlrx** [comment]
Debian 8 uses systemd to manage services, can you please use systemd commands (see https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-service.html#_using_systemd) instead to check if it works better?

**Comment by gfairchild** [comment]
That was indeed the problem! Thanks very much! You might want to see about updating the documentation to clarify that. The "Debian/Ubuntu" header doesn't give any indication that the new versions of Debian don't use update-rc.d.
