### ISSUE TITLE
Vagrant tests: Non-reactor builds breaks bats tests

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#13871]
Running full vagrant tests like `mvn clean verify` from the root results in copying this dependency

```
[INFO] Copying elasticsearch-3.0.0-SNAPSHOT.deb to /Users/alr/devel/elasticsearch/qa/vagrant/target/testroot/elasticsearch-3.0.0-SNAPSHOT.deb
```

where as running mvn with the `-pl` or the `-rf` parameter copies the debian package with a timestamp at the end, like this

```
[INFO] Copying elasticsearch-3.0.0-SNAPSHOT.deb to /Users/alr/devel/elasticsearch/qa/vagrant/target/testroot/elasticsearch-3.0.0-20150930.001002-241.deb
```

this leads to the debian package not being found, because we check for the strict version

```
     [exec] trusty: # dpkg: error processing archive elasticsearch-3.0.0-SNAPSHOT.deb (--install):
     [exec] trusty: #  cannot access archive: No such file or directory
```

The bug is in `./src/test/resources/packaging/scripts/30_deb_package.bats` and `./src/test/resources/packaging/scripts/40_rpm_package.bats` because we refer to the packages like this: `elasticsearch-$(cat version).deb`

Also we could upgrade to beta2 for the upgrade test

**Comment by brwe** [comment]
I cannot reproduce this. I tried 
`mvn clean install -DskipTests`
`mvn -Dtests.vagrant -pl qa/vagrant pre-integration-test`
`mvn -Dtests.vagrant=all -pl qa/vagrant verify` 
and all works as expected.
Can you give the exact order of commands you execute?

**Comment by spinscale** [comment]
I did not run `mvn install`, which makes this fail reliably for me

**Comment by spinscale** [comment]
closing this due to gradle switch
