### ISSUE TITLE
RangeQueryBuilder format in 1.7

### ISSUE THREAD

**Issue by olivere** [elastic/elasticsearch#13885]
Hi there!

I noticed something strange today with `RangeQueryBuilder` with regard to the `format` parameter in 1.7.

Although [`format` is documented here](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-range-query.html#_date_options), there is no sign of it in the [Java source of 1.7](https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/index/query/RangeQueryBuilder.java). However, it [exists in 2.0](https://github.com/elastic/elasticsearch/blob/2.0/core/src/main/java/org/elasticsearch/index/query/RangeQueryBuilder.java#L39).

Is it possible that the `format` parameter is silently ignored in 1.7? Am I missing something?

Thanks for your time,
Oliver

**Comment by clintongormley** [comment]
Yeah, it likes like it was only exposed via the REST API in 1.7.  This commit added it to the builder: https://github.com/elastic/elasticsearch/commit/23cf9af495ef5066c6a5d88218ed3bf4ceca9db3#diff-73c1518c0dd10aebabe2bc79b2587a14
