### ISSUE TITLE
ExtendableQueryParser equivalent in ElasticSearch?

### ISSUE THREAD

**Issue by tad9ab** [elastic/elasticsearch#13895]
I have a usecase to intercept a Lucene query from a user, then do query manipulation for certain fields so that we can make their query a bit more "smart".  For example, if they send us an IPv4 CIDR, we want to convert this to a numeric range.

We tried using the ExtendableQueryParser, then using the subsequent query in the QueryStringQueryBuilder.  This works for the most part, but gets tricky once special characters are introduced.  Lucene will "drop" these once the toString is called on the Query object that is created from parsing the string query.  When we feed this in to the QueryStringQueryParser, the query that is generated causes ES to fail because things aren't escaped properly anymore (because Lucene's QueryParser's toString removed them).

My hope is that if ExtendableQueryParser (or equivalent) was built into ES, we could just modify specific key/values in the query, and let everything else pass through.

I can provide more info if needed, please let me know.

Edit: we are using ES 1.7.2

Thanks!

**Comment by clintongormley** [comment]
Hi @tad9ab 

We've discussed this in FixItFriday and we're not keen to add these hooks.  This feels like it should be handled in a query pre-processing phase before sending the query to Elasticsearch.

For the concrete example of converting the CIDR to a range, there is this issue that has been open for a while https://github.com/elastic/elasticsearch/issues/7464. Nobody has implemented it yet, but we'd be in favour of implementing it if you'd like to send a PR.
