### ISSUE TITLE
Simplify reading sets, maps, and lists

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#13893]
While working on removing `ImmutableMap` and `ImmutableSet` I've seen a ton of different fun ways to read immutable maps, sets, and lists. If we're willing to use Java 8's function pointer things we could remove lots of duplicated code by creating `readMap`, `readSet`, and `readList` in `StreamInput`. We could probably also do something similar for writing these but I haven't thought as much about it.

**Comment by jpountz** [comment]
+1

**Comment by tomcallahan** [comment]
Those methods exist, and we're unlikely to tie an issue to going on a large deduplication effort.  Closing.
