### ISSUE TITLE
Bug with simple_query_string, multiple fields and prefix query

### ISSUE THREAD

**Issue by LeonardGC** [elastic/elasticsearch#13899]
## Abstract
-- Adding a '*' after the query is the difference between an error and a search
-- Tested on v1.7.2. and v2.0.0.beta2

### Delete the index
    curl -XDELETE localhost:9200/testing

### Add data
    curl -XPUT 'http://localhost:9200/testing/test/1' -d '{"name":"test1","list":{"id":1,"color" : "orange"}}'

### 1) First working query
    curl -XPOST 'http://localhost:9200/testing/test/_search' -d '{
      "_source":true,
          "query":{
            "simple_query_string":{
              "fields":[
                "list.color"
              ],
              "query":"orange"
            }
          }
    }'

### 2) This query gives error: "...nested: NumberFormatException[For input string: \"orange\"]..."
    curl -XPOST 'http://localhost:9200/testing/test/_search' -d '{
      "_source":true,
          "query":{
            "simple_query_string":{
              "fields":[
                "list.*"
              ],
              "query":"orange"
            }
          }
    }'

### 3) but this works again?!?
    curl -XPOST 'http://localhost:9200/testing/test/_search' -d '{
      "_source":true,
          "query":{
            "simple_query_string":{
              "fields":[
                "list.*"
              ],
              "query":"orange*"
            }
          }
    }'

## Notes
Notice that the only change between 2) and 3) is that I put a `*` after the "orange" => "orange*"
The error mentions nesting, but there's no nesting in the mapping?!?

**Comment by clintongormley** [comment]
The prefix query (`orange*`) is a term level query which attempts no analysis, and so can be run on a numeric field (without finding any results).  The first query tries to analyze `orange` but that doesn't work with a numeric field.

You're looking for the `lenient` option, which will ignore fields of the wrong type.
