### ISSUE TITLE
processors setting is not reflected in nodes info API ("os.available_processors")

### ISSUE THREAD

**Issue by FestivalBobcats** [elastic/elasticsearch#13917]
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html#processors

The end of that page seems to imply the `processors` value passed in settings will be displayed in the nodes info API with the `os` flag. However, it seems to always display information retrieved from the OS.

I know the setting is going through due to the change in thread pool values.

Should the "available_processors" value display what is passed in settings, or is it assumed to be actual OS information?

(on 1.7.1)

**Comment by clintongormley** [comment]
I think we should keep the `available_processors` key as it is today, but that we should include an `allocated_processors` key which shows actual number of processors that we are using.

**Comment by FestivalBobcats** [comment]
Definitely agree with that approach.
