### ISSUE TITLE
Make weighted centroid an optional parameter for geohash_grid aggregator

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#13912]
#13433 added a weighted centroid to the ```geohash_grid``` aggregator.  #13846 adds a stand alone ```geo_centroid``` metric aggregator for combining with other aggregations (e.g., terms aggregator). This enhancement adds an optional ```compute_centroid``` parameter (default to ```false```) to the ```geohash_grid``` aggregator to provide a shortcut for computing the weighted centroid on geohash grids without requiring ```geo_centroid``` as a separate sub-aggregation.

**Comment by jpountz** [comment]
Adding a sub aggregation is so easy, why should we have this `compute_centroid` parameter?

**Comment by nknize** [comment]
Everything's already available in GridAggregator leafCollector and doReduce to compute the weighted centroid while accumulating each bucket without having to create separate GeoCentroidAggregator objects and make a second pass per bucket. Maybe negligible savings?

**Comment by jpountz** [comment]
OK I see your point. I would be in favour of not having this `compute_centroid` option for now, and then potentially reconsider our options in the future if we identify `geo_centroid` under `geohash_grid` as a frequent source of out-of-memory errors.

**Comment by nknize** [comment]
+1 I'm good w/ the "lets fix it if its broke".

Just a quick observation from the singleValueFieldAsSubAggToGeohashGrid() test which indexes 2K documents. Using ```geo_centroid``` as a subaggregator makes 2*numDocs calls to ```collect``` (one for the GeoGrid and one for the Centroid) where as accumulating centroid as a part of GeoHashGrid makes numDocs calls to ```collect```.  I don't suspect we'll have OOM issues?  But do we think this savings is worth it as index size grows?  Or a non issue with a good shard configuration?

**Comment by jpountz** [comment]
I think this is expected? We create a tree of aggregators that delegate the collect method. So the framework calls collect `numDocs` times on the `geohash_grid` aggregation, and part of what collect() on the `geohash_grid` aggregator does is calling collect() on the `geo_centroid` aggregator.

**Comment by nknize** [comment]
Right, I'm just wondering if adding this centroid option to the grid aggregator is worth it at the moment for cutting this process in half.  I can either leave the issue open and address later or close and reopen if it becomes a problem?

**Comment by nknize** [comment]
Closing for now as a non-issue.
