### ISSUE TITLE
Suggestion is not refreshing index

### ISSUE THREAD

**Issue by vi3k6i5** [elastic/elasticsearch#13915]
ES: Version: 1.7.2, Build: e43676b/2015-09-14T09:49:53Z, JVM: 1.7.0_79

I created an index like this:

curl -XDELETE 'http://localhost:9200/my_db.index_map/'
curl -XPUT 'http://localhost:9200/my_db.index_map/' -d '
{
  "settings": {
    "analysis": {
      "analyzer": {
        "case_insensitive": {
          "tokenizer": "keyword",    
          "filter":  [ "lowercase" ] 
        }
      }
    }
  }
}'

curl -XPUT 'http://localhost:9200/my_db.index_map/string/_mapping/' -d '
{
  "string" : {
    "properties" : {
      "keywords_tags" : {
        "type": "completion"
      }
    }
  }
}'

Then i added document with keywords_tags as "jabalpur". Later i removed it. 

Now in my search i am not getting jabalpur as results

curl -X GET http://127.0.0.1:9200/my_db.index_map/_search?pretty=true -d '{
    "query": {
        "match": {
            "keywords_tags": "jabalpur"
        }
    }
}'

Response:

{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}

But if i make a suggest query like this:
curl -X GET http://127.0.0.1:9200/my_db.index_map/_suggest?pretty=true -d '{
    "suggestions" : {
        "text" : "jabalpur",
        "completion" : {
            "field" : "keywords_tags"
        }
    }
}'

{
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "suggestions" : [ {
    "text" : "jabalpur",
    "offset" : 0,
    "length" : 8,
    "options" : [ {
      "text" : "jabalpur",
      "score" : 1.0
    } ]
  } ]
}

why is the suggest index not getting updated and how can i fix this ??

**Comment by clintongormley** [comment]
Hi @vi3k6i5 

This is a documented limitation of the current completion suggester.  The new completion suggester coming in 2.1 doesn't have this limitation

**Comment by vi3k6i5** [comment]
@clintongormley : Thanks for the update.

Is there any way around this? any temporary solution that might work?

Btw, Where can i track release plans ? and by when will 2.1 be released?

Thanks,
Vikash

**Comment by sudheendrach** [comment]
:+1: @clintongormley would like to know the release plans for 2.1

**Comment by clintongormley** [comment]
@vi3k6i5 optimizing the shard with expunge_deletes would remove the deleted (updated) documents.  

We don't announce release dates ahead of time.

**Comment by vi3k6i5** [comment]
@clintongormley Thanks this helps. :+1:

**Comment by Alex1sz** [comment]
@clintongormley according to the documentation for 2.2 https://www.elastic.co/guide/en/elasticsearch/reference/2.2/search-suggesters-completion.html#querying[](url)  this isn't fixed for 2.2 (see: "The suggest data structure might not reflect deletes on documents immediately. You may need to do an Optimize for that. You can call optimize with the only_expunge_deletes=true to only target deletions for merging.") Did the 'new completion suggester' not make it into 2.2 or is it new in 2.2 and this problem has still not been fixed?

**Comment by clintongormley** [comment]
@Alex1sz We backed it out of 2.2 as it was a breaking change, so it will only arrive in 5.0 unfortunately

**Comment by trompx** [comment]
Hello @clintongormley,

I use the completion-suggester to display data that are returned with a payload updated every hour. But with the current suggester the update are not showing up, only the first version of the document is returned which is really annoying. So the only solution is to optimize the whole index to just update a value ? Or is it possible to force an update just for a specific document ?

Will the new suggester correct this problem ?

Thank you
