### ISSUE TITLE
more consistency with IDE configuration for tests.

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13914]
People want to be able to run tests from their IDE (and maybe use the debugger and so on). I get it.

But tests behave differently depending on how you run them, and its a huge hassle to deal with this stuff.

The problem is we have to support too many runtime environments:
* bin/elasticsearch (aka running for real). distribution and plugin REST tests go against an external server in this environment. They are the most realistic tests.
* "unit test environment from maven". in this situation, things are less realistic. We have multiple nodes within the same jvm, and we just do our best to approximate reality. With maven there are even differences depending on whether its in a "reactor build" or not.
* Intellij IDE. There might even be multiple environments, depending on how people configure it (e.g. mvn idea:idea versus something within the IDE itself). This is less realistic even than unit tests.
* Eclipse IDE. Currently this is the least realistic of all.

Having to make all these configurations "work" or "kind of work" is incredibly frustrating and complex. In many cases I throw out designs completely, or push back against changes, because it won't work in all these scenarios. Instead, I think we should put a little work into the IDE configuration to make it easier.

For example, eclipse puts *all generated classes* piled together in `eclipse/build`. Instead of:
```
<classpathentry kind="src" path="src/main/java"/>
<classpathentry kind="src" path="src/test/java"/>
```

We can do:
```
<classpathentry kind="src" path="src/main/java" output="eclipse-build/target/classes"/>
<classpathentry kind="src" path="src/test/java output="eclipse-build/target/test-classes"/>
```

See how now its closer to the maven build? For example when testing lang-groovy plugin it means test-framework can assign src/main/java all the scary permissions groovy needs, but not src/test/java code. This means tests will fail in the IDE if security logic is wrong.

I'm setting adopt me: folks come to me with questions if their IDE does not do what they want, but I basically have to throw up my hands until we simplify some stuff: improve these IDE configs.

**Comment by rmuir** [comment]
I also wonder if these IDEs can be closer to unit tests as far as which system properties are provided to tests and things like that.

**Comment by clintongormley** [comment]
i think this has been resolved going forward, so I'll close for now.
