### ISSUE TITLE
Elastic search master branch test case failures

### ISSUE THREAD

**Issue by ketan22584** [elastic/elasticsearch#13926]
Hi,

I have been to to build elastic search from source from the following master branch
https://github.com/elastic/elasticsearch.git

Without test cases the build is sucessfull .. following is teh instruction to build
mvn install -DskipTests=true

With test cases there are failures and i am unable to figure out the cause 
mvn test -Pdev -pl org.elasticsearch:elasticsearch -Dtests.seed=93CDDBA6C9651B87 -Dtests.class=org.elasticsearch.index.similarity.SimilarityTests -Dtests.method="testResolveSimilaritiesFromMapping_DFR"

Requesting your inputs to resolve this
Below are the debug logs

Debug LOgs

Suite: org.elasticsearch.index.similarity.SimilarityTests
  2> REPRODUCE WITH: mvn test -Pdev -pl org.elasticsearch:elasticsearch -Dtests.seed=93CDDBA6C9651B87 -Dtests.class=org.elasticsearch.index.similarity.SimilarityTests -Dtests.method="testResolveSimilaritiesFromMapping_DFR" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=es_DO -Dtests.timezone=America/Argentina/ComodRivadavia
FAILURE 31.2s | SimilarityTests.testResolveSimilaritiesFromMapping_DFR <<<
   > Throwable #1: java.lang.AssertionError:
   > Expected: a value less than or equal to <YELLOW>
   >      but: <RED> was greater than <YELLOW>
   >    at __randomizedtesting.SeedInfo.seed([93CDDBA6C9651B87:79B60E8EF528003F]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.test.ESSingleNodeTestCase.createIndex(ESSingleNodeTestCase.java:212)
   >    at org.elasticsearch.test.ESSingleNodeTestCase.createIndex(ESSingleNodeTestCase.java:192)
   >    at org.elasticsearch.test.ESSingleNodeTestCase.createIndex(ESSingleNodeTestCase.java:181)
   >    at org.elasticsearch.index.similarity.SimilarityTests.testResolveSimilaritiesFromMapping_DFR(SimilarityTests.java:104)
   >    at java.lang.Thread.run(Thread.java:745)
  2> NOTE: leaving temporary files on disk at: /home/elasticsearch/core/target/J0/temp/org.elasticsearch.index.similarity.SimilarityTests_93CDDBA6C9651B87-005
  2> NOTE: test params are: codec=Asserting(Lucene53): {}, docValues:{}, sim=RandomSimilarityProvider(queryNorm=false,coord=no): {}, locale=es_DO, timezone=America/Argentina/ComodRivadavia
  2> NOTE: Linux 3.10.0-229.1.2.el7.s390x s390x/Oracle Corporation 1.8.0_60 (64-bit)/cpus=1,threads=1,free=390243056,total=518979584
  2> NOTE: All tests run in this JVM: [SimilarityTests]
Completed [1/1] in 42.91s, 1 test, 1 failure <<< FAILURES!

[WARNING] JVM J0: stderr was not empty, see: /home/elasticsearch/core/target/junit4-J0-20151005_074526_147.syserr

Tests with failures:
  - org.elasticsearch.index.similarity.SimilarityTests.testResolveSimilaritiesFromMapping_DFR

Ketan Kunde

**Comment by jpountz** [comment]
This test failure suggests that there is something that prevented the index to be created on some nodes resulting in a red state. Do you have local modifications of elasticsearch? If not can you try to pull latest changes and run "mvn clean" before trying to build the package again?

**Comment by ketan22584** [comment]
Thanks for the reply
I do not have local changes made to the source

I went by your suggestion to checkout fresh source  clean it and build it still the build fails
pasting the logs below

this are the instructions i followed to build it
Also just want to add that i am using jdk 1.8 and maven 3.3.3
mvn clean
mvn install

Your inputs will be helpful to get this test cases passing

Thanks in advance


Tests with failures:
  - org.elasticsearch.test.rest.Rest7IT.test {yaml=index/10_with_id/Index with ID}


[INFO] JVM J0:     0.50 .. 10861.16 = 10860.66s
[INFO] Execution time total: 3 hours 1 minute 1 second
[INFO] Tests summary: 287 suites (1 ignored), 2108 tests, 1 error, 57 ignored (57 assumptions)
[INFO]
[INFO] --- maven-antrun-plugin:1.8:run (integ-tests-top-hints) @ elasticsearch ---
[INFO] Executing tasks

main:
 [tophints] 681.82s | org.elasticsearch.recovery.RecoveryWhileUnderLoadIT
 [tophints] 540.89s | org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT
 [tophints] 509.27s | org.elasticsearch.index.engine.InternalEngineMergeIT
 [tophints] 452.84s | org.elasticsearch.cluster.ClusterStateDiffIT
 [tophints] 415.85s | org.elasticsearch.cluster.allocation.ClusterRerouteIT
[INFO] Executed tasks
[INFO]
[INFO] --- maven-failsafe-plugin:2.18.1:verify (verify) @ elasticsearch ---
[INFO] Failsafe report directory: /home/elasticsearch/core/target/failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Build Tools and Resources .......................... SUCCESS [ 20.128 s]
[INFO] Rest API Specification ............................. SUCCESS [  3.493 s]
[INFO] Elasticsearch: Parent POM .......................... SUCCESS [05:42 min]
[INFO] Elasticsearch: Core ................................ FAILURE [  04:08 h]
[INFO] Distribution: Parent POM ........................... SKIPPED
[INFO] Distribution: TAR .................................. SKIPPED
[INFO] Distribution: ZIP .................................. SKIPPED
[INFO] Distribution: Deb .................................. SKIPPED
[INFO] Plugin: Parent POM ................................. SKIPPED
[INFO] Plugin: Analysis: ICU .............................. SKIPPED
[INFO] Plugin: Analysis: Japanese (kuromoji) .............. SKIPPED
[INFO] Plugin: Analysis: Phonetic ......................... SKIPPED
[INFO] Plugin: Analysis: Smart Chinese (smartcn) .......... SKIPPED
[INFO] Plugin: Analysis: Polish (stempel) ................. SKIPPED
[INFO] Plugin: Cloud: Google Compute Engine ............... SKIPPED
[INFO] Plugin: Delete By Query ............................ SKIPPED
[INFO] Plugin: Discovery: Azure ........................... SKIPPED
[INFO] Plugin: Discovery: EC2 ............................. SKIPPED
[INFO] Plugin: Discovery: Multicast ....................... SKIPPED
[INFO] Plugin: Language: Expression ....................... SKIPPED
[INFO] Plugin: Language: Groovy ........................... SKIPPED
[INFO] Plugin: Language: JavaScript ....................... SKIPPED
[INFO] Plugin: Language: Python ........................... SKIPPED
[INFO] Plugin: Mapper: Murmur3 ............................ SKIPPED
[INFO] Plugin: Mapper: Size ............................... SKIPPED
[INFO] Plugin: Repository: Azure .......................... SKIPPED
[INFO] Plugin: Repository: S3 ............................. SKIPPED
[INFO] Plugin: Store: SMB ................................. SKIPPED
[INFO] Plugin: JVM example ................................ SKIPPED
[INFO] Plugin: Example site ............................... SKIPPED
[INFO] QA: Parent POM ..................................... SKIPPED
[INFO] QA: Smoke Test Plugins ............................. SKIPPED
[INFO] QA: Smoke Test Multi-Node IT ....................... SKIPPED
[INFO] QA: Smoke Test Client .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:14 h
[INFO] Finished at: 2015-10-07T14:53:13+00:00
[INFO] Final Memory: 69M/247M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:verify (verify) on project elasticsearch: There are test failures.
[ERROR]
[ERROR] Please refer to /home/elasticsearch/core/target/failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :elasticsearch

**Comment by ketan22584** [comment]
Hi can anyone give me any inputs on the above issue

**Comment by dadoonet** [comment]
Not really an answer but you could skip the tests if your goal is just to build a version.

**Comment by ketan22584** [comment]
Thanks for the reply .. yes on skipping test my build is sucess but i need to get the test cases passing .
I see that some of you have been able to get it passing .. i just want to know is there something that i have been missed to get this test cases passed?

**Comment by javanna** [comment]
I've seen this `index/10_with_id/Index with ID` failure before, it was due to the characters that are used as part of the index name. I think the fix was to export encoding related environment variables: `LANG=en_US.UTF-8` and `LC_ALL=en_US.UTF-8`. Have also a look at this similar issue: #8548 .

**Comment by clintongormley** [comment]
No more feedback.  Closing
