### ISSUE TITLE
How to create Location object in Groovy/Java

### ISSUE THREAD

**Issue by rajeshdommati** [elastic/elasticsearch#13925]
I am getting latitude and longitude values from a rest API and i want to create a location object in groovy/java(may be using double arrays) and store it to Elasticsearch with other parameters. I know how to do this through logstash and wondering how to achieve it from groovy/java..

how to created the below object using groovy/java.
"location": {
"lat": "50.68262437",
"lon": "7.5592885"
}

Thanks in advance!!

**Comment by dadoonet** [comment]
Please join us on discuss.elastic.co for questions.

Not an issue. Closing.
