### ISSUE TITLE
Test failure: org.elasticsearch.indices.recovery.RecoverySourceHandlerTests.testHandleCorruptedIndexOnSendSendFiles

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#13929]
This test failure is reproducible: `mvn test -Pdev -pl org.elasticsearch:elasticsearch -Dtests.seed=E325370F88FD9068 -Dtests.class=org.elasticsearch.indices.recovery.RecoverySourceHandlerTests -Dtests.method="testHandleCorruptedIndexOnSendSendFiles" -Des.logger.level=DEBUG -Dtests.assertion.disabled=false -Dtests.heap.size=1024m -Dtests.locale=sr -Dtests.timezone=America/Porto_Velho`.

See http://build-us-00.elastic.co/job/es_g1gc_master_metal/20088/testReport/junit/org.elasticsearch.indices.recovery/RecoverySourceHandlerTests/testHandleCorruptedIndexOnSendSendFiles/

**Comment by s1monw** [comment]
fixed by https://github.com/elastic/elasticsearch/pull/13923
