### ISSUE TITLE
Shall we remove the count api?

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#13928]
The count api is currently a shortcut to the search api with `size` set to `0`. We should discuss whether it makes sense to remove it given that one can simply use the `_search` api instead and set `size` to `0`.

When it comes to the REST layer, the lines of code required to maintain the shortcut to search are not many, but the java api requires a bit more, it would be nice to get rid of that and simplify things.

I see a few disadvantages on the client side:
- it's handy to have the _count endpoint for ease of use, although it is super easy to move to `_search?size=0`
- if you forget to set the `size` to `0` everything works, but more work is done under the hood
- last I can think of is the different response:

```
{
    "count" : 1,
    "_shards" : {
        "total" : 5,
        "successful" : 5,
        "failed" : 0
    }
}
```

compared to the search api response which is a bit more convoluted:

```
{
    "_shards":{
        "total" : 5,
        "successful" : 5,
        "failed" : 0
    },
    "hits":{
        "total" : 1
    }
}
```

**Comment by clintongormley** [comment]
The `_count` API can be replaced easily by `_search?size=0`.  Removing it from the REST layer would remove some comvenient simple sugar, but removing it from the Java API really doesn't impact convenience.

Let's remove from the Java API and leave the REST endpoint in place, and keep the response the same as today.
