### ISSUE TITLE
dumps to elasticsearch from ntopng have incorrect timestamp

### ISSUE THREAD

**Issue by kthkaya** [elastic/elasticsearch#13936]
Only 3 out of 400.000 dumped flows have the correct timestamp. 
I dont know why specifically 28th of August as it does not relate to any milestone (i.e installing something or starting a service etc)

root@nTop:/etc/ntopng# cat ntopng.conf
-w=3000
-W=0
-m="192.168.0.0/24"
-F=es;flows;ntopng-%Y.%m.%d;http://localhost:9200/_bulk;password
-d=/storage/ntopng
-G=/var/tmp/ntopng.pid
-i=tcp://127.0.0.1:5556

Some dumped flows

October 5th 2015, 02:45:17.000 @timestamp:October 5th 2015, 02:45:17.000 type:flows IPV4_SRC_ADDR:140.205.159.56 L4_SRC_PORT:0 IPV4_DST_ADDR:0.0.0.0 L4_DST_PORT:0 PROTOCOL:6 TCP_FLAGS:0 IN_PKTS:5 IN_BYTES:405 OUT_PKTS:0 OUT_BYTES:0 FIRST_SWITCHED:1,440,789,636 LAST_SWITCHED:1,440,789,636 json.5:0 json.9:0 json.10:0 json.13:0 json.14:0 json.15:0.0.0.0 json.16:0 json.17:0 json.42:531762 CLIENT_NW_LATENCY_MS:0 SERVER_NW_LATENCY_MS:0 _id:AVA1dbrJKInKjCg_uSAI _type:flows _index:ntopng-2015.10.05

October 5th 2015, 02:15:05.000 @timestamp:October 5th 2015, 02:15:05.000 type:flows IPV4_SRC_ADDR:121.214.55.2 L4_SRC_PORT:0 IPV4_DST_ADDR:0.0.0.0 L4_DST_PORT:0 PROTOCOL:17 L7_PROTO:0 L7_PROTO_NAME:Unknown IN_PKTS:36 IN_BYTES:1,779 OUT_PKTS:0 OUT_BYTES:0 FIRST_SWITCHED:1,440,789,635 LAST_SWITCHED:1,440,789,636 json.5:0 json.9:0 json.10:0 json.13:0 json.14:0 json.15:0.0.0.0 json.16:1221 json.17:0 json.42:258897 SRC_IP_COUNTRY:AU SRC_IP_LOCATION:144.967, -37.817 _id:AVA1Wg8kKInKjCg_tfu9 _type:flows _index:ntopng-2015.10.05

October 5th 2015, 02:05:09.000 @timestamp:October 5th 2015, 02:05:09.000 type:flows IPV4_SRC_ADDR:62.210.205.156 L4_SRC_PORT:0 IPV4_DST_ADDR:0.0.0.0 L4_DST_PORT:0 PROTOCOL:6 L7_PROTO:0 L7_PROTO_NAME:Unknown TCP_FLAGS:0 IN_PKTS:104 IN_BYTES:146,553 OUT_PKTS:0 OUT_BYTES:0 FIRST_SWITCHED:1,440,789,635 LAST_SWITCHED:1,440,789,635 json.5:0 json.9:0 json.10:0 json.13:0 json.14:0 json.15:0.0.0.0 json.16:12876 json.17:0 json.42:170919 CLIENT_NW_LATENCY_MS:0 SERVER_NW_LATENCY_MS:0 SRC_IP_COUNTRY:FR SRC_IP_LOCATION:2.333, 48.867 _id:AVA1UPf4KInKjCg_tPkX _type:flows _index:ntopng-2015.10.05

August 28th 2015, 21:20:36.000 @timestamp:August 28th 2015, 21:20:36.000 type:flows IPV4_SRC_ADDR:46.188.121.201 L4_SRC_PORT:0 IPV4_DST_ADDR:0.0.0.0 L4_DST_PORT:0 PROTOCOL:17 IN_PKTS:1 IN_BYTES:99 OUT_PKTS:0 OUT_BYTES:0 FIRST_SWITCHED:1,440,789,636 LAST_SWITCHED:1,440,789,636 json.5:0 json.9:0 json.10:0 json.13:0 json.14:0 json.15:0.0.0.0 json.16:0 json.17:0 json.42:965 _id:AVA1QBnEKInKjCg_sw0B _type:flows _index:ntopng-2015.10.04

August 28th 2015, 21:20:36.000 @timestamp:August 28th 2015, 21:20:36.000 type:flows IPV4_SRC_ADDR:203.215.120.85 L4_SRC_PORT:0 IPV4_DST_ADDR:0.0.0.0 L4_DST_PORT:0 PROTOCOL:17 IN_PKTS:1 IN_BYTES:48 OUT_PKTS:0 OUT_BYTES:0 FIRST_SWITCHED:1,440,789,636 LAST_SWITCHED:1,440,789,636 json.5:0 json.9:0 json.10:0 json.13:0 json.14:0 json.15:0.0.0.0 json.16:6648 json.17:0 json.42:724 SRC_IP_COUNTRY:PH SRC_IP_LOCATION:121.05, 14.633 _id:AVA1QBnsKInKjCg_sw0T _type:flows _index:ntopng-2015.10.04

**Comment by clintongormley** [comment]
I'm afraid I have no idea what you're talking about, and this doesn't seem to be the right place to ask the question.
