### ISSUE TITLE
Provide custom logging appender that supports time based rolling and maxbackupindex

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#13953]
As part of https://github.com/elastic/elasticsearch/issues/7927, we implemented RollingFileAppender in log4j.  However, this is implemented via log4j-extras and the RollingFileAppender there does not support MaxBackupIndex for time based rolling.  

```
log4j:WARN No such property [maxBackupIndex] in org.apache.log4j.rolling.TimeBasedRollingPolicy.
log4j:WARN No such property [maxBackupIndex] in org.apache.log4j.rolling.RollingFileAppender.
```

This is a request for an out of the box appender that supports all of the following features commonly requested by administrators out there:

- Time based rolling (eg. logs rolled daily)
- Compression on logs
- Ability to define the max number of logs to retain (i.e. MaxBackupIndex), eg. retain the last N days of logs.

Also see discussion [here](https://github.com/elastic/puppet-elasticsearch/issues/34)

**Comment by tomchlee** [comment]
Hi,

By updating ES to log4j 2, I think all of the features indicated in this request will be supported and with many more options via RollingFileAppender and DefaultRolloverStrategy:

https://logging.apache.org/log4j/2.x/manual/appenders.html

Thanks.

**Comment by haiguo** [comment]
+1

**Comment by jasontedor** [comment]
Closing in favor of #17697.
