### ISSUE TITLE
Scripting: JsonEscapingMustacheFactory does not escape HTML

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#13959]
According to the [mustache docs](https://mustache.github.io/mustache.5.html) all input is HTML escaped by default, unless you use the triple mustache `{{{foo}}}`. However with our own `JsonEscapingMustacheFactory` we break this convention.

Test to reproduce:

``` java
@Test
public void testEscaping() throws Exception {
    HashMap<String, Object> scopes = new HashMap<>();
    scopes.put("foo", "<b>FOO</b>");

    // DefaultMustacheFactory works as expected
    //MustacheFactory f = new DefaultMustacheFactory();
    MustacheFactory f = new JsonEscapingMustacheFactory();

    String template = "This is spartaaaa or html: {{foo}}";
    Mustache mustache = f.compile(new StringReader(template), "example");
    StringWriter writer = new StringWriter();
    mustache.execute(writer, scopes);
    writer.flush();
    assertThat(writer.toString(), is("This is spartaaaa or html: &lt;b&gt;FOO&lt;/b&gt;"));
}
```

Original source of the issue: https://discuss.elastic.co/t/watchers-mustache-implementation-does-not-appear-to-html-escape-values/31427

**Comment by aochsner** [comment]
I'd suppose that for the 99% case in ElasticSearch, you don't want to html escape because the content is normally JSON.  I thought about it some more, and I think it's more of an issue with Watcher & the HTML body in an email.  In that case, I want/need to html-escape by default (or use triple mustache if I don't).

**Comment by spinscale** [comment]
As mustache was introduced for the search template feature, it makes sense to have the `JsonEscapingMustacheFactory` - but think about scripted fields or scripted metrics etc, where people still might be confused, when mustache does not follow the expected default behaviour. Let's see if we can find a solution in core two support both ways or alternatively ensure this works in watcher.

**Comment by aochsner** [comment]
Awesome!  Looking forward to it.  Thanks!

**Comment by jdconrad** [comment]
@spinscale Is this still relevant?

**Comment by spinscale** [comment]
aged out. closing.
