### ISSUE TITLE
TransportNode ensureNodesAreAvailable() doesn't make sense

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#13957]
In https://github.com/elastic/elasticsearch/blob/6885ab96805990d83e57dd0baded83252d7a2e0e/core/src/main/java/org/elasticsearch/client/transport/TransportClientNodesService.java

```java
    private void ensureNodesAreAvailable(List<DiscoveryNode> nodes) {
        if (nodes.isEmpty()) {
            String message = String.format(Locale.ROOT, "None of the configured nodes are available: %s", nodes);
            throw new NoNodeAvailableException(message);
        }
    }
```

If `nodes` is empty, what's the point in reporting it in the error message?

I'd expect the configured nodes - the ones provided to the TransportNode - and not the ones that we were actually been able to connect to (none of them)

**Comment by javanna** [comment]
makes sense to me... would you be up for sending a PR? ;)

**Comment by synhershko** [comment]
There you go https://github.com/elastic/elasticsearch/pull/14007
