### ISSUE TITLE
2.0.0-beta2 fails to start using shield with access denied java.io.FilePermission

### ISSUE THREAD

**Issue by robertsmarty** [elastic/elasticsearch#13966]
Hi,

I've just recently updated all my ansible scripts to use all the available 2.0.0-beta2 files, including shield. I'm now receiving the following error on startup...

Exception in thread "main" ElasticsearchException[failed to initialize a TrustManagerFactory]; nested: AccessControlException[access denied ("java.io.FilePermission" "/apps/_elk_assets/certs/xxxxx.jks" "read")];

This was working fine prior to updating packages.

Any ideas?

Cheers,

Marty

**Comment by jaymode** [comment]
Hi @robertsmarty,

Is your JKS file stored in a directory outside of the elaticsearch config directory? If so, you will need to move it to a location within the elasticsearch configuration directory for 2.0.0-beta1 and newer. This is necessary since we use a security manager to limit the directories that the elasticsearch process can read from and write to.

**Comment by robertsmarty** [comment]
Thanks for the answer! Moving the files under the config directory worked. I tried a symbolic link however that didn't seem to work.

**Comment by sumitsengar** [comment]
HI,
I also faced a similar issue while testing ssl security with Shield. I understand ES's limitations in accessing files outside its config directory, but do we also have to live with this constraint in a production deployment scenario? I am using elastic 2.2.0 with same Shield version. Is there a way to override this behaviour?

**Comment by jaymode** [comment]
Hi @sumitsengar,

I think your question will be better answered in our [Shield specific discussion forum ](https://discuss.elastic.co/c/shield). Please join us there so we can learn more about what you need.
