### ISSUE TITLE
Watcher mail body with mustache file template not working

### ISSUE THREAD

**Issue by ompanda** [elastic/elasticsearch#13965]
I am trying to load mail body of a watcher from mustache file placed in script folder. Elasticsearch is reading the file ,when i checked in log. if i am trying to give file name test_mail_body or test_mail_body.mustache, then getting error , test_mail_body file not found.

**Comment by clintongormley** [comment]
Hi @ompanda 

Best place for help on watcher is https://discuss.elastic.co/c/watcher or your support contact
