### ISSUE TITLE
Build test failure - Jython exceptions cause encoding error

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#13968]
Build failure here: http://build-us-00.elastic.co/job/es_g1gc_master_metal/20291/

If you call toString() of a python exception, jython tries to "render" it in a pythonisque way, but it seems to have localization problems, if the default locale uses a different number system.

As a workaround we can remove the toString in the assert of PythonSecurityTests.assertFailure() - that will stop build failures, until we have time to dig into jython's problems here.

**Comment by rmuir** [comment]
I opened https://github.com/elastic/elasticsearch/issues/13967 for this and pushed workarounds. I can look into it later, my guess is we want to look into the streams we give jython (this is configurable), really these scripts should not be printing to system.out/system.err anyway :) But this might not be the only problem there.

**Comment by markharwood** [comment]
Thanks, @rmuir 
Closing as duplicate.
