### ISSUE TITLE
default network.host to _ec2_ when using discovery.type:ec2

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13970]
We should come with good defaults when using `discovery.type: ec2` and bind network.host to `_ec2_` (which is the private IP address).

Related to #13969

**Comment by dadoonet** [comment]
Closing for the same reasons as exposed in https://github.com/elastic/elasticsearch/issues/13969#issuecomment-146203970

**Comment by peterskim12** [comment]
@dadoonet What do you think about logging a warning message suggesting that the user may want to consider changing network.host to _ec2_ if discovery.type: ec2? I gave some feedback to the doc team asking them to better call out the need to set network.host appropriately, but it's easy to miss.

**Comment by dadoonet** [comment]
@peterskim12 Can you open a new issue for this so others can comment?
