### ISSUE TITLE
More documentation around how snapshots are incremental

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#13974]
I see about one question a day on the forums, irc, etc about incremental snapshots. I think it might be worth reworking the documentation so its more obvious that the unit of reuse is files. Like with pictures.

**Comment by dadoonet** [comment]
++ :)

**Comment by imotov** [comment]
+1

**Comment by debadair** [comment]
The Snapshot & Restore info was reworked in 6.0, but not with pictures.

**Comment by ywelsch** [comment]
addressed by @debadair
