### ISSUE TITLE
default network.host to _non_loopback_ when using discovery.type:azure

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#13972]
We should come with good defaults when using `discovery.type: azure` and bind `network.host` to `_non_loopback_` (which is the private IP address - needed to be checked).

Related to #13969

**Comment by rmuir** [comment]
I dont think we should ever default to this, its far too heuristicy and hacky. Really it should be deprecated, its totally arbitrary depending on interface ordering. Azure should have its own pseudo names like ec2 and the others... How we resolve them is an impl detail of that plugin.

Moreover i guess i missed where we again start binding to non local interfaces by default, but ill be damned if we leave it to luck with non loopback. If azure is not explicit like ec2 then we should add `_site_local_` or something safer.

**Comment by dadoonet** [comment]
Yeah. I agree with you Robert. That's why I wrote `which is the private IP address - needed to be checked`. I thought it was. May it's not or too lenient.

I'll try first to see if we can implement `_azure_` interface easily or not which is too me the best option.

**Comment by rmuir** [comment]
I have the same concerns about the gce value in the referenced pr, it seems just as arbitrary, interface zero. If we want to bind to site local addresses for these plugins, then i would rather have a pseudo value that only binds to site local addresses. It seems to solve both these problems and we know it will not bind to anything crazy.

**Comment by dadoonet** [comment]
Closing for the same reasons as exposed in https://github.com/elastic/elasticsearch/issues/13969#issuecomment-146203970
