### ISSUE TITLE
Add more sort fields to _percolate

### ISSUE THREAD

**Issue by colmaengus** [elastic/elasticsearch#13978]
Hi,

I would like to use the percolator but need to be able to perform a multi-level sort using fields in the .percolator queries.
For example sort matches first by a priority field then by a date-time field.
The documentation says that only sorting by _score is currently supported.
Are there plans to allow sorting on other fields ?

Regards

Colm A

**Comment by clintongormley** [comment]
@colmaengus in the meantime you could fake it by using the function score query to combine the fields you need into a `_score`.

**Comment by colmaengus** [comment]
I was thinking of doing that but was wondering how best to mimic the multi level sort.
Is there a plan to add sorting on other    fields ? If so any idea as to the timeline?
