### ISSUE TITLE
Add numeric sort order field to sorted results

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#13980]
A customer has requested the ability to add an optional field to sorted results that will show the order of the results. They're doing some operations on the sorted results that are breaking the sorting, and would like to be able to reconstruct them easily with their own systems. A field that shows the original order of the sort would help here.

**Comment by jpountz** [comment]
Maybe I'm not understanding the use-case correctly, but isn't it something that would be trivial to do on client side? Ie. when they get the results, they first attach an ordinal to each of them before doing their reordering on client-side?

**Comment by clintongormley** [comment]
besides what @jpountz has suggested, results are already returned with a `sort` array including the values that were used for sorting.  Resorting on the client side would also be trivial.

**Comment by clintongormley** [comment]
Nothing further. Closing
