### ISSUE TITLE
Why does the ScriptedMetricBuilder not have an explicit generic type parameter?

### ISSUE THREAD

**Issue by kufi** [elastic/elasticsearch#13986]
I just noticed a problem when using the elastic4s API, which seems to be a problem with the core elastic API.

It basically boils down to the problem that the ScriptedMetricBuilder class does not set the generic type parameter of the MetricsAggregationBuilder.

The MetricsAggregationBuilder class definition:
    
    public abstract class MetricsAggregationBuilder<B extends MetricsAggregationBuilder<B>> extends AbstractAggregationBuilder { ... }

A the moment, the ScriptedMetricBuilder is defined as follows:

    public class ScriptedMetricBuilder extends MetricsAggregationBuilder  { ... }

There is also the ValuesSourceMetricsAggregationBuilder class which is defined as follows:

    public abstract class ValuesSourceMetricsAggregationBuilder<B extends ValuesSourceMetricsAggregationBuilder<B>> extends MetricsAggregationBuilder<B> { ... }

Any subclass of the ValueSourceMetricsAggregationBuilder has the following definition:

    public class StatsBuilder extends ValuesSourceMetricsAggregationBuilder<StatsBuilder> { ... }
    public class SumBuilder extends ValuesSourceMetricsAggregationBuilder<SumBuilder> { ... }
    ...

They correctly set the generic type parameter of the MetricsAggregationBuilder class to themself. Only the ScriptedMetricBuilder, for some reason, does take over the more generic `B extends MetricsAggregationBuilder<B>` definition of it's parent.

Is there a reason the ScriptedMetricBuilder is not defined as follows?

    public class ScriptedMetricBuilder extends MetricsAggregationBuilder<ScriptedMetricBuilder>  { ... }

As this would be more consistent with any other definition of builders there are?

**Comment by clintongormley** [comment]
@colings86 any idea?

**Comment by colings86** [comment]
Yep, this is a bug. Thanks @kufi for raising this

**Comment by kufi** [comment]
Shall I create a pull request for it?

**Comment by colings86** [comment]
@kufi that would be great, thanks
