### ISSUE TITLE
put jvm crash logs in logs/

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#13982]
This would be a great improvement over what probably happens today. See issues like https://github.com/elastic/elasticsearch/issues/13600 where the jvm crashes and people are unaware of the log file (most likely in many cases its going to /tmp which is unexpected).

It would be better if we set `-XX:ErrorFile` explicitly...

**Comment by rjernst** [comment]
+1

**Comment by jpountz** [comment]
+1

**Comment by nik9000** [comment]
I'll have a look.

**Comment by clintongormley** [comment]
Closed by #14006

**Comment by rjernst** [comment]
I don't think this issue was fixed? The linked PR was closed without merging. The problem, IIRC, is the location must be set when starting the jvm, but we have too many ways to set the log dir location, so determining that from the elasticsearch shell script is problematic.

**Comment by jasontedor** [comment]
@clintongormley I don't think #14006 was integrated, and I still think that this is something that we should do.

**Comment by clintongormley** [comment]
ah thanks - missed that

**Comment by rjernst** [comment]
I wonder if we could set the ErrorFile in the same way we set HeapDumpPath? In rpm/deb, we put it under /var/lib/elasticsearch, and for zip/tar, we have a commented out line in jvm.options.

**Comment by jasontedor** [comment]
I opened #29028.
