### ISSUE TITLE
paramters as command line args handled differently by plugin and elasticsearch script

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#13991]
`./bin/plugin` accepts parameters with a space between name and value like "-Des.path.conf ./path/to/conf" but `./bin/elasticsearch` does not. Seems to me like the two should do the same thing? This goes also for the windows scripts. see also #13989

**Comment by rjernst** [comment]
See my comment on the related issue. We should remove this functionality from `bin/plugin`. The jvm does not take sysprops like that, we are doing some magic to make it happen.

**Comment by ywelsch** [comment]
+1 for removing the functionality that transforms `-Dfoor bar` into `-Dfoo=bar` in `plugin[.bat]`.

Note that the reason as for why system properties get special handling in `plugin[.bat]` is that when you invoke `plugin[.bat]` (in contrast to `elasticsearch[.bat]`) you not only want to specify system properties but also parameters to the main method (such as `install some-plugin -v`). The implementation of `plugin[.bat]` thus has to separate the former from the latter when passing it to the java process.

**Comment by vivek120794** [comment]
Attach files by dragging & dropping,  Choose Files selecting them, or pasting from the clipboard.

**Comment by jasontedor** [comment]
Closed by #18207
