### ISSUE TITLE
Restrict document ID values

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#14009]
It seems that there are some chars that are not ideal in document IDs, things such as `/`, probably others.
This is being discussed on a different level in #9059 and I thought I'd also raise this specific one.

From [this](https://discuss.elastic.co/t/getting-document-by-document-id/31806) forum post.

**Comment by jpountz** [comment]
+1

**Comment by clintongormley** [comment]
Actually, I think doc ID values can be pretty much unlimited.  As pointed out in the forum post, they just need to be properly encoded in the URL, which all the official clients handle correctly.

**Comment by jpountz** [comment]
I don't think encoding is enough. For instance we allow documents to have `_search` as an id but then you can't GET them.

**Comment by clintongormley** [comment]
You can always fall back to using mget in these cases.

Related to https://github.com/elastic/elasticsearch/issues/9059

**Comment by dr0i** [comment]
> Actually, I think doc ID values can be pretty much unlimited. As pointed out in the forum post, they just need to be properly encoded in the URL 

Right! If it happen that a value of an `_id` field is already percent encoded (e.g. `a%2Fb`) the lookup-query would be  `.../a%252Fb`).
Doing an ID lookup, maybe it would be save  to say: 
"*always*  percent-encode the ID in an ID-query (take the value in `_id` , percent-encode it and query that) ".

**Comment by dnhatn** [comment]
Any document id will be handled correctly with a proper url encoding.
