### ISSUE TITLE
Document ES_CLASSPATH changes

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#14008]
In 2.0.0 we are changing the way we handle this and it needs to be adequately documented in breaking changes.

@rjernst mentioned the reasoning here is that if it wasn't specified our shell handling would still add it to the classpath and Java would then see an empty string on the classpath and just add $cwd.
It was decided that it just wasn't worth this because, moving forward plugins should be how things are added to ES. If someone needs to add something to the classpath, they can add it to the ES lib dir manually.

**Comment by rjernst** [comment]
FYI, we have a check already in the code so the user gets a "nice message" if they try starting ES with `ES_CLASSAPTH`.

**Comment by clintongormley** [comment]
@rjernst Does #14026 correctly reflect the changes to ES_CLASSPATH?
