### ISSUE TITLE
More detail on cause of allocation failure / unassigned shards

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#14001]
I have done a few tests in difference scenarios, in order to find the reason why shards are unassigned.   It seems as if there could be some improvements by providing the real, human readable reason why a shard is in unassigned state.

Possible end reasons (for failed allocation) would include 
- more replicas than nodes
- low disk watermark
- corruption
- forced allocation awareness
- bad routing

In the scenarios that I was able to reproduce, the *Unassigned Reason*, and *Unassigned Details* did not assist in learning the real cause.  

In **Allocation Awareness** and **Low Disk Watermark** tests, no *unassigned.details* were available, and the *unassigned.reason* was not helpful in learning the user error.  Both tests had similar results:

```
GET /_cat/shards?h=node,index,shard,prirep,state,unassigned.reason,unassigned.details
Wolverine test-index 4 p STARTED                       
          test-index 4 r UNASSIGNED CLUSTER_RECOVERED  
...or...
Hazard newone3    4 p STARTED                       
       newone3    4 r UNASSIGNED INDEX_CREATED    
```

A **Node Left** test resulted in a useful *reason* and a *unassigned.details* string, but the latter was not human-friendly:

```
Cecelia Reyes test-index 4 p STARTED                                                
              test-index 4 r UNASSIGNED NODE_LEFT node_left[tHfFXWxGS4ao-xGjvkJQAg] 
Cecelia Reyes test-index 3 p STARTED                                                
              test-index 3 r UNASSIGNED NODE_LEFT node_left[tHfFXWxGS4ao-xGjvkJQAg] 
```

**Comment by haiguo** [comment]
+1

**Comment by clintongormley** [comment]
The Unassigned Reason indicates why a shard was marked as unassigned, as opposed to what is preventing it from being assigned (which could be a combination of multiple factors).  

These issues can be diagnosed using the cluster reroute API with the `explain` parameter.

I agree it would be nice to present all of this info a clear human (and machine) readable way.  Any suggestions?

**Comment by clintongormley** [comment]
Discussed in FixitFriday:  We think the biggest thing that is missing here is an explanation of what the unassigned reason codes actually mean.  Rather than trying to include that info in an API, the easiest solution is to just document them.

For the reason a shard cannot BE assigned, we already have human readable output in the cluster reroute API.  

However, it would also help to add documentation to explain how to diagnose these issues.

**Comment by fforbeck** [comment]
Hi @clintongormley,
I've included the description for the reason codes as we have in the UnassignedInfo.java. 
Please, let me know if it is fine.
Thanks!

**Comment by PhaedrusTheGreek** [comment]
This is addressed in 5.x with the [Cluster Allocation Explain API](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/cluster-allocation-explain.html)
