### ISSUE TITLE
2.0.0-beta2 bin/plugin --help has cloud-aws as official plugin but not available + fails

### ISSUE THREAD

**Issue by robertsmarty** [elastic/elasticsearch#14013]
bin/plugin install cloud-aws fails to install with the following error...

Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/cloud-aws/2.0.0-beta2/cloud-aws-2.0.0-beta2.zip ...
ERROR: failed to download out of all possible locations

I managed to find the file here...

https://oss.sonatype.org/content/repositories/releases/org/elasticsearch/plugin/cloud-aws/2.0.0-beta2/

Installing from this location seems to work ok however when I start elasticsearch I receive the following error...

[2015-10-08 15:28:11,674][WARN ][com.amazonaws.jmx.SdkMBeanRegistrySupport]
java.security.AccessControlException: access denied ("javax.management.MBeanServerPermission" "findMBeanServer")

A couple of questions...

I thought this plugin was for < v2. Should I be using it?
Is this potentially an issue caused by tighter v2 java permissions?

Cheers,

Marty

**Comment by clintongormley** [comment]
I think you're using the wrong install command, and trying to install the old version.  This works:

    ./bin/plugin install cloud-aws

**Comment by Cidan** [comment]
I can confirm this happens to me as well with RC1 -- cloud-aws gives me the same error (while installing properly with plugin install)

Ideas?

**Comment by rmuir** [comment]
> Installing from this location seems to work ok however when I start elasticsearch I receive the following error...
> 
> [2015-10-08 15:28:11,674][WARN ][com.amazonaws.jmx.SdkMBeanRegistrySupport]
> java.security.AccessControlException: access denied ("javax.management.MBeanServerPermission" "findMBeanServer")

That isn't an error, your logging configuration must be incorrect or outdated. Do you have a custom file?

https://github.com/elastic/elasticsearch/blob/master/distribution/src/main/resources/config/logging.yml#L13-L15

**Comment by robertsmarty** [comment]
This works fine for me with rc1. Got a feeling it was not available for beta2.
