### ISSUE TITLE
[GEO] Elasticsearch generates InvalidShapeException for geometry it finds invalid but GEOS does not

### ISSUE THREAD

**Issue by danni** [elastic/elasticsearch#14015]
Elasticsearch generates an InvalidShapeException error for a shape that passed GEOS' own validation before being indexed.

```
MapperParsingException[failed to parse [catchment_mpoly]]; nested: InvalidShapeException[Self-intersection at or near point (153.1233139135, -27.587310564, NaN)]; 
```

Could this be related to the precision parameter?

**Comment by nknize** [comment]
@danni same for this issue if you could, version, field mapping, and source geojson.

**Comment by danni** [comment]
Running on 1.7.2-1.

```
GEO_SHAPE = {
    'type': 'geo_shape',
    'tree': 'quadtree',
    'precision': '15m',
}
```

Having trouble outputting the full polygon due to buffer sizes. I'll need to add a utility that outputs the full shape for me.

**Comment by nknize** [comment]
Closing as non-issue, further discussion can continue on #12325
