### ISSUE TITLE
Seccomp tests fail on some ES Jenkins runs

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#14025]
The seccomp tests fail pretty consistently on es_feature_geo_point_field_v2 builds:
http://build-us-00.elastic.co/job/es_feature_geo_point_field_v2/2491/console
http://build-us-00.elastic.co/job/es_feature_geo_point_field_v2/2490/console
http://build-us-00.elastic.co/job/es_feature_geo_point_field_v2/2489/console

**Comment by nik9000** [comment]
It looks like this branch has the same version of the test.

**Comment by nik9000** [comment]
The tests pass in both branches on my ubuntu machine when I run:
```
mvn test -Pdev -pl org.elasticsearch:elasticsearch -Dtests.class=org.elasticsearch.bootstrap.SeccompTests -Dtests.security.manager=false
```

Note that you have to disable the security manager for these test to run at all.

**Comment by nik9000** [comment]
Note: that branch doesn't always fail with seccomp test failures. The tests pass here:
http://build-us-00.elastic.co/job/es_feature_geo_point_field_v2/2482/consoleFull
http://build-us-00.elastic.co/job/es_feature_geo_point_field_v2/2481/consoleFull

**Comment by rmuir** [comment]
You need to merge master to it.

**Comment by nik9000** [comment]
The two builds that passed that I linked to were run on 
http://build-us-00.elastic.co/computer/ubuntu-14-64-12-metal
but the failing builds were run on
http://build-us-00.elastic.co/computer/opensuse-13-64-0-metal
http://build-us-00.elastic.co/computer/ubuntu-14-64-7-metal

**Comment by nik9000** [comment]
> You need to merge master to it.

Fair enough. I didn't see what changed with seccomp tests. Could you link me to the change so I can improve my git-search-foo?

**Comment by rmuir** [comment]
No. i shouldnt have to fix bugs N times because of feature branches.

**Comment by nik9000** [comment]
> No. i shouldnt have to fix bugs N times because of feature branches.

No but if you could help me to find where you fixed it in master then I'd have a better time solving this problem again when it comes up again.

I'll just ignore these failures from here on out.

**Comment by rmuir** [comment]
the whole process is broken here. A little pushing back from me is totally warranted.
