### ISSUE TITLE
Remove @Test annotation

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#14028]
I vaguely remember a discussion about Elasticsearch preferring tests who's names start `test` rather than using the `@Test` annotation. I've been removing the annotations as I touch test files and remember it and folks seem pretty happy with that approach. The trouble with that approach is that it relies on communication and consistency both of which I think people are bad at. I know I am.

If we don't like the annotation I think we should ban it using forbidden apis and I should just remove them all. If we do like the annotation then we should just close the issue.

**Comment by rjernst** [comment]
+1 to remove. I also remove it anytime I touch a file that has it. It is just an extra line per test for no reason.

**Comment by s1monw** [comment]
+1

**Comment by mikemccand** [comment]
+1

**Comment by jpountz** [comment]
+1

**Comment by martijnvg** [comment]
+1

On 9 October 2015 at 10:31, Adrien Grand <notifications@github.com> wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch/issues/14028#issuecomment-146796378>
> .
>



-- 
Met vriendelijke groet,

Martijn van Groningen

**Comment by nik9000** [comment]
I'll take it!

I'll just do it in master unless anyone has objections.

**Comment by nik9000** [comment]
Lol
```
Scanned 2206 (and 3144 related) class file(s) for forbidden API invocations (in 8.72s), 3145 error(s).
```

**Comment by nik9000** [comment]
*3145*
