### ISSUE TITLE
[pre-2.0.0] Order of analyzer/index_analyzer/search_analyzer is unpredictable

### ISSUE THREAD

**Issue by ankon** [elastic/elasticsearch#14023]
*This only applies to pre-2.0.0 ES!*

While reviewing the changes in ES 2.x I noticed the removal of the `index_analyzer` in favor of just `analyzer` and `search_analyzer` in a mapping. 
We actually use `index_analyzer` and `search_analyzer`, so I looked for documentation for pre-2.0.0 to tell me which order is used if I just replaced `index_analyzer` with `analyzer` - this way I can use a 2.0.0-compatible mapping already in the application, and decouple the actual update of the ES cluster from the application development cycle.

From my reading of the code that isn't actually possible: pre-2.0.0 ES parses the three settings in whatever order they appear in the map of settings, so when I use `analyzer` and `search_analyzer` in those versions it can happen that the `search_analyzer` setting gets ignored (if the parser first finds `search_analyzer` and then `analyzer`).

afcedb94 (from #9371) fixes that while removing the `index_analyzer` by only applying the settings after having processed the whole map.

It would be really helpful to backport just that part to pre-2.0.0, so that migration doesn't depend on changing both the application code and the ES version at the same time.

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/14060
