### ISSUE TITLE
fresh install ES 1.7.2 bin/plugin fails on El Capitan

### ISSUE THREAD

**Issue by dblado** [elastic/elasticsearch#14034]
In trying to confirm if another issue still exists on 1.7.2, I got the following error while trying to install a plugin:

$ ./bin/plugin 
./bin/plugin: line 108: /Library/Internet: is a directory

I resolved the issue for now w/ a symlink /Library/Internet -> /Library/Internet Plug-Ins/ and reset $JAVA_HOME. Guessing this is related to #12610, #12504.

**Comment by clintongormley** [comment]
Agreed.  This has been fixed in 2.0 by moving param parsing to Java from shell.

Seems a bit odd that your JAVA_HOME was pointing to /Library/Internet Plug-Ins/ though?  Mine contains: `/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home`

**Comment by dblado** [comment]
@clintongormley Odd -- I don't recall changing my JAVA_HOME but apparently I had...thanks!
