### ISSUE TITLE
Some searches are not returning all the documents

### ISSUE THREAD

**Issue by malinir123** [elastic/elasticsearch#14032]
We have configured Elastic Search to have 3 nodes, 3 shards 1 primary and 2 replica shards.
Elastic search health shows that all shards are assigned and running and in green state.
But some searches returns Fetch Failed [Failed to fetch doc id [241839]]]; nested: EOFException[seek past EOF: MMapIndexInput(path=\"/data/elasticsearch/clusterdata/data/abcj/nodes/0/indices/csv1/0/index/_1f9s.fdt\")]; "

error and not all the documents are returned.

Any Idea why I am seeing this? Is the data corrupted?

Thanks

**Comment by clintongormley** [comment]
Hi @malinir123 

It looks like you have a corrupt index.  Given that you haven't had any corruption exceptions, I'm guessing that you're on an old version.  I'd recommend upgrading.

**Comment by malinir123** [comment]
I am using elasticsearch-1.1.1.

How do we fix the corrupted index?

**Comment by clintongormley** [comment]
You have to reindex
