### ISSUE TITLE
Restore an index not working

### ISSUE THREAD

**Issue by malinir123** [elastic/elasticsearch#14039]
I have  set up back up of my elastic search index. I am trying to  restore the index but to a new name.
I am running the following command

curl -XPOST 'localhost:9200/_snapshot/backup_snapshots_backup/backup_snapshot_1/_restore
{
    "indices": "csv1", 
    "rename_pattern": "csv(.+)", 
    "rename_replacement": "csv2" 
}'

I keep getting
{"error":"SnapshotRestoreException[[backup_snapshots_backup:backup_snapshot_1] cannot restore index [csv1] because it's open]","status":500}

even after closing the index csv1.

Any ideas what I am doing wrong?

**Comment by clintongormley** [comment]
This works fine for me on 1.7.1.   Any more information that you can provide, eg ES version, anything in the logs, etc?

**Comment by ywelsch** [comment]
no feedback -> close

**Comment by cyrilcyril70** [comment]
curl 'localhost:9200/_cat/indices?v'

health status index      uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   assessment Us4-9BieRZWfPjfJzsbpgA   5   1       3314          120      1.1mb          1.1mb
yellow open   users      lwqbt16TTmSE1CCd5HfweQ   5   1       7088           21      7.5mb          7.5mb
yellow open   calendar   eOOGR3FBSLucl-mNjgoAqw   5   1         64            0    191.1kb        191.1kb


So this worked:
curl -XPOST "localhost:9200/assessment/_close"
curl -XPOST "localhost:9200/users/_close"
curl -XPOST "localhost:9200/calendar/_close"

appa!!! found solution atlast ...
