### ISSUE TITLE
Feature request : Closed index 

### ISSUE THREAD

**Issue by onthefloorr** [elastic/elasticsearch#14043]
Dear Elasticsearch,

It would be nice, if there would be an option that specifies whether the indices which are closed  would be working as deleted indices. By this I mean that if an index has been closed, it shoud not be listed by _aliases or _stats api.  I know blocked indices can be asked by "_cluster/state/blocks" but unfortunatelly my collegaues using open and close function for starting elasticsearch faster. I mean when they start elasticsearch they close each index after they opening them one by one manually. I told them the best solution would be if more machines being used for elasticsearch as cluster, but they stick to their "method". However, they want to search in indices which are closed because the _aliases api got indicies back which are closed (however they are unusable). I know the closed indices are blocked for read write operations, and they can not be used any operation so it would be great if it were an option to use (automatically) closed/blocked indices as deleted indices till they will not be recovered. Could you help me ?  I really don't want to check the indices status before each operation.

I hope this is the right place to solve my issue.

Thank you in advance for any help you can provide.

**Comment by clintongormley** [comment]
Hi @onthefloorr 

I'm a bit confused as to what you are wanting.  Are you saying that what you want to do is to be able to search on an alias which points to multiple indices, and just ignore the closed indices instead of throwing an exception?

Or is there more to this?

**Comment by onthefloorr** [comment]
Hi @clintongormley ,

By default, an  (I don't know what kind of type at this moment) exception is occured if I try to do any (read/write) operation on index which are closed.  Here's where my problem comes in, my application is using indices which are returned in the JSON response body of "_aliases" (of course the number of investigated indexes is limited but I check the existence of index by this way) . For instance, the result of "_aliases" includes indices that are closed, and my application tries to search in these indexes, but an exception will be occurred because the "alias"/"index" is closed.  Basically yes, I would like if it were an option (which would be specified in the elasticsearch.ini) to ignore/skip the closed indices instead of throwing an exception.

**Comment by clintongormley** [comment]
@onthefloorr This is implemented in 2.0.  The `_aliases` end point doesn't return closed indices by default.

**Comment by onthefloorr** [comment]
Thank you very much for the quick reply and the quick help!
