### ISSUE TITLE
wrong network interface taking when using number networks and bonding

### ISSUE THREAD

**Issue by ozlevka** [elastic/elasticsearch#14045]
Our cluster is running on redhat 6.
We have 2 networks in our cluster. Primary network and backup network. Backup network it's not network for emergency this network used by backup system.
The primary network is using bonding (using bond0 where its slaves are
eth0 & eth1). The backup network is using eth2 .
The issue we are facing is :  when running "get localhost:9200/_nodes the "primary_network" is
eth2 and not bond0. When we try to change the parameter "network.host: _bond0_" we got errors :
"closing connection java.nio.channels.UnresolvedAddressException"
Right now we solve problem by insert bond0 IP address to network.host parameter in yml configuration, but this is pure solution because IP address will be change from time to time. And this is confusing when we see primary_network one IP address and in transport section bound and publish another IP with different mask.

**Comment by jasontedor** [comment]
Can you confirm that you are attempting this with `_bond0` instead of `_bond0_` (it should be the latter)? If so, would you be able to try `_bond0_`?

**Comment by ozlevka** [comment]
Sorry, this is only printing mistake. Of course we use _bond0_ as parameter.
If it can help we use version 1.4.4, but I not find some different between
1.4.4 and current stable version.

On Fri, Oct 9, 2015 at 2:23 PM, Jason Tedor <notifications@github.com>
wrote:

> Can you confirm that you are attempting this with _bond0 instead of
> _bond0_ (it should be the latter)? If so, would you be able to try _bond0_
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch/issues/14045#issuecomment-146838237>
> .
>



-- 
Best regards
Ozeryansky Lev

**Comment by clintongormley** [comment]
Hi @ozlevka 

The networking binding code has been extensively rewritten in 2.0.  Could you try the 2.0.0-rc1 release and see if it suffers from the same problem please?

**Comment by jasontedor** [comment]
@ozlevka I setup a CentOS installation with a bonded interface and Elasticsearch 1.4.4, and I'm not able to reproduce into the issue that you describe.

    [vagrant@localhost ~]$ ifconfig bond0
    bond0     Link encap:Ethernet  HWaddr 08:00:27:6B:E2:E2
              inet addr:192.168.33.12  Bcast:192.168.33.255  Mask:255.255.255.0
              inet6 addr: fe80::a00:27ff:feff:1c2a/64 Scope:Link
              UP BROADCAST RUNNING MASTER MULTICAST  MTU:1500  Metric:1
              RX packets:15 errors:0 dropped:0 overruns:0 frame:0
              TX packets:31 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:0
              RX bytes:918 (918.0 b)  TX bytes:2382 (2.3 KiB)

The bonding status:

    [vagrant@localhost ~]$ cat /proc/net/bonding/bond0
    Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)
    
    Bonding Mode: fault-tolerance (active-backup) (fail_over_mac active)
    Primary Slave: None
    Currently Active Slave: eth3
    MII Status: up
    MII Polling Interval (ms): 100
    Up Delay (ms): 200
    Down Delay (ms): 200
    
    Slave Interface: eth3
    MII Status: up
    Speed: 1000 Mbps
    Duplex: full
    Link Failure Count: 0
    Permanent HW addr: 08:00:27:6b:e2:e2
    Slave queue ID: 0
    
    Slave Interface: eth2
    MII Status: up
    Speed: 1000 Mbps
    Duplex: full
    Link Failure Count: 0
    Permanent HW addr: 08:00:27:ff:1c:2a
    Slave queue ID: 0

The only change that I made to the default configuration is:

    [vagrant@localhost ~]$ cat /etc/elasticsearch/elasticsearch.yml | grep network.host
    network.host: _bond0_

and I forced IPv4 by adding 

    ES_JAVA_OPTS="-Djava.net.preferIPv4Stack=true"

to `/etc/sysconfig/elasticsearch`.

From the startup logs:

    [2015-10-13 22:49:25,150][INFO ][transport                ] [Quentin Quire] bound_address {inet[/192.168.33.12:9300]}, publish_address {inet[/192.168.33.12:9300]}
    [2015-10-13 22:49:25,200][INFO ][discovery                ] [Quentin Quire] elasticsearch/f8-Z5kcKQsaz5uRImrXB8g
    [2015-10-13 22:49:29,009][INFO ][cluster.service          ] [Quentin Quire] new_master [Quentin Quire][f8-Z5kcKQsaz5uRImrXB8g][localhost][inet[/192.168.33.12:9300]], reason: zen-disco-join (elected_as_master)
    [2015-10-13 22:49:29,048][INFO ][http                     ] [Quentin Quire] bound_address {inet[/192.168.33.12:9200]}, publish_address {inet[/192.168.33.12:9200]}

And:

      [vagrant@localhost ~]$ curl -XGET 192.168.33.12:9200
      {
        "status" : 200,
        "name" : "Quentin Quire",
        "cluster_name" : "elasticsearch",
        "version" : {
          "number" : "1.4.4",
          "build_hash" : "c88f77ffc81301dfa9dfd81ca2232f09588bd512",
          "build_timestamp" : "2015-02-19T13:05:36Z",
          "build_snapshot" : false,
          "lucene_version" : "4.10.3"
        },
        "tagline" : "You Know, for Search"
      }

As for a get on `_nodes` returning a `primary_interface` of `eth2` on your box, ignore that; that is due ot the Sigar library that this depends on and is happening outside of Elasticsearch; it does not mean that Elasticsearch is even using this interface at all.

So, where this leaves us is that we're not concerned by the `primary_interface` reporting, and we are not able to reproduce the issue that you describe. If you're able to provide additional information that will help us reproduce the issue, we would be happy to investigate further.

**Comment by ozlevka** [comment]
I'll ask system team when I can process upgrade. I think we can wait to GA
version of 2.0

Thank you

On Tue, Oct 13, 2015 at 10:43 AM, Clinton Gormley <notifications@github.com>
wrote:

> Hi @ozlevka <https://github.com/ozlevka>
>
> The networking binding code has been extensively rewritten in 2.0. Could
> you try the 2.0.0-rc1 release and see if it suffers from the same problem
> please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch/issues/14045#issuecomment-147632054>
> .
>



-- 
Best regards
Ozeryansky Lev

**Comment by ozlevka** [comment]
Thank you Jason
About: "get on _nodes returning a primary_interface of eth2 on your box,
ignore that". This is exactly what we do.
I hope it's will be fixed in 2.0 GA version.

Thank you

On Wed, Oct 14, 2015 at 5:34 AM, Jason Tedor <notifications@github.com>
wrote:

> @ozlevka <https://github.com/ozlevka> I setup a CentOS installation with
> a bonded interface and Elasticsearch 1.4.4, and I'm not able to reproduce
> into the issue that you describe.
>
> [vagrant@localhost ~]$ ifconfig bond0
> bond0     Link encap:Ethernet  HWaddr 08:00:27:6B:E2:E2
>           inet addr:192.168.33.12  Bcast:192.168.33.255  Mask:255.255.255.0
>           inet6 addr: fe80::a00:27ff:feff:1c2a/64 Scope:Link
>           UP BROADCAST RUNNING MASTER MULTICAST  MTU:1500  Metric:1
>           RX packets:15 errors:0 dropped:0 overruns:0 frame:0
>           TX packets:31 errors:0 dropped:0 overruns:0 carrier:0
>           collisions:0 txqueuelen:0
>           RX bytes:918 (918.0 b)  TX bytes:2382 (2.3 KiB)
>
> The bonding status:
>
> [vagrant@localhost ~]$ cat /proc/net/bonding/bond0
> Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)
>
> Bonding Mode: fault-tolerance (active-backup) (fail_over_mac active)
> Primary Slave: None
> Currently Active Slave: eth3
> MII Status: up
> MII Polling Interval (ms): 100
> Up Delay (ms): 200
> Down Delay (ms): 200
>
> Slave Interface: eth3
> MII Status: up
> Speed: 1000 Mbps
> Duplex: full
> Link Failure Count: 0
> Permanent HW addr: 08:00:27:6b:e2:e2
> Slave queue ID: 0
>
> Slave Interface: eth2
> MII Status: up
> Speed: 1000 Mbps
> Duplex: full
> Link Failure Count: 0
> Permanent HW addr: 08:00:27:ff:1c:2a
> Slave queue ID: 0
>
> The only change that I made to the default configuration is:
>
> [vagrant@localhost ~]$ cat /etc/elasticsearch/elasticsearch.yml | grep network.host
> network.host: _bond0_
>
> and I forced IPv4 by adding
>
> ES_JAVA_OPTS="-Djava.net.preferIPv4Stack=true"
>
> to /etc/sysconfig/elasticsearch.
>
> From the startup logs:
>
> [2015-10-13 22:49:25,150][INFO ][transport                ] [Quentin Quire] bound_address {inet[/192.168.33.12:9300]}, publish_address {inet[/192.168.33.12:9300]}
> [2015-10-13 22:49:25,200][INFO ][discovery                ] [Quentin Quire] elasticsearch/f8-Z5kcKQsaz5uRImrXB8g
> [2015-10-13 22:49:29,009][INFO ][cluster.service          ] [Quentin Quire] new_master [Quentin Quire][f8-Z5kcKQsaz5uRImrXB8g][localhost][inet[/192.168.33.12:9300]], reason: zen-disco-join (elected_as_master)
> [2015-10-13 22:49:29,048][INFO ][http                     ] [Quentin Quire] bound_address {inet[/192.168.33.12:9200]}, publish_address {inet[/192.168.33.12:9200]}
>
> And:
>
>   [vagrant@localhost ~]$ curl -XGET 192.168.33.12:9200
>   {
>     "status" : 200,
>     "name" : "Quentin Quire",
>     "cluster_name" : "elasticsearch",
>     "version" : {
>       "number" : "1.4.4",
>       "build_hash" : "c88f77ffc81301dfa9dfd81ca2232f09588bd512",
>       "build_timestamp" : "2015-02-19T13:05:36Z",
>       "build_snapshot" : false,
>       "lucene_version" : "4.10.3"
>     },
>     "tagline" : "You Know, for Search"
>   }
>
> As for a get on _nodes returning a primary_interface of eth2 on your box,
> ignore that; that is due ot the Sigar library that this depends on and is
> happening outside of Elasticsearch; it does not mean that Elasticsearch is
> even using this interface at all.
>
> So, where this leaves us is that we're not concerned by the
> primary_interface reporting, and we are not able to reproduce the issue
> that you describe. If you're able to provide additional information that
> will help us reproduce the issue, we would be happy to investigate further.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch/issues/14045#issuecomment-147906543>
> .
>



-- 
Best regards
Ozeryansky Lev
