### ISSUE TITLE
Rename discovery.zen.minimum_master_nodes

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#14058]
This setting works irrespective of the discovery method, so it should be named differently.

As it is it could lead to some confusion.

**Comment by clintongormley** [comment]
Agreed.  I'd say that this is not urgent, and should be done when we have a proper mechanism to alert the user to renamed or deprecated settings, ie #6732

**Comment by javanna** [comment]
seems like we want to do this, do we want to deprecate the setting and introduce its replacement in 6.0?

**Comment by jasontedor** [comment]
I would strongly prefer that we not do this for 6.0.0 (if at all, but that's a separate matter). It's a cosmetic change that has BWC concerns that we do not need to be taking on right now.

**Comment by jasontedor** [comment]
Also, related, we have deeper issues with `discovery.minimum_master_nodes` to explore anyway.

**Comment by ywelsch** [comment]
The confusion stems from bad naming. The notion of "discovery" is used in two ways:
1) determining the list of nodes that is used for nodes to initially find each other.
2) the implementation that does cluster forming (master election and cluster state publishing).

For 1) we have plugins for GCE, EC2, Azure etc.
For 2) we have a single implementation, called Zen Discovery.

Zen Discovery does both 1) and 2) and allows a pluggable `hosts_provider` implementation that provides the nodes that are used for pinging, i.e., the process of finding other nodes. What we call GCE, EC2, or Azure discovery is nothing more than Zen Discovery with a customized `host_provider`.

One could argue that `minimum_master_nodes` falls into the realm of master election and cluster state publishing and should hence carry the name `zen` as it is specific to that implementation.

**Comment by jasontedor** [comment]
Thanks @ywelsch, your elaboration is exactly what I was thinking when I said "if at all, but that's a separate matter" and was going to elaborate when I had more time. ❤️

**Comment by jasontedor** [comment]
I feel that we can close this now as won't fix.

**Comment by bleskes** [comment]
+1 to close. We don't have enough info now to make the right call. I tend to agree that min master nodes is a zen discovery property and that the plugins are nothing but a host providers. In fact we currently expect people to use the `discovery.zen.hosts_provider` setting for that. I will open a separate issue to remove the BWC logic that still accepts `discovery.type` as a way to configure EC2/GCE/Azure specific unicast host list.

**Comment by bleskes** [comment]
issue opened: https://github.com/elastic/elasticsearch/issues/24543
