### ISSUE TITLE
GC problems in ES 1.4.4

### ISSUE THREAD

**Issue by rushirajchavan** [elastic/elasticsearch#14061]
Frequent full GC even if the memory utilization is 30-40%.
** We have not changed the default JVM settings

Below are the cluster details -
1. A master node
2. Two data nodes

** All the replicas are allocated on one node and all the primaries are on the other node. It should not be a problem, right? Also frequent full GC is observed on one of the 2 data nodes.

Shards - 
We have around 75 shards with replication as 1. I guess the problem is because of shard over allocation.
Most of the queries we hit are aggregation queries.

Thanks,
Rushiraj

**Comment by clintongormley** [comment]
Hi @rushirajchavan 

I think the proper place to discuss this is in the forums http://discuss.elastic.co/

Also, check that you have properly disabled swap: https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html
