### ISSUE TITLE
 1.7.1 GROOVY_SCRIPT_BLACKLIST_PATCH /  java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by coderlol** [elastic/elasticsearch#14077]
nodeBuilder().clusterName("elasticsearch").client(true).data(false).node();

I use elasticsearch 1.7.1 and Java 8.  This used to work, not sure if that was before Java 8 or a recent upgrade to 1.7.1

Gives the below....pls help why ...

?thrown.cause.localizedMessage	  	  GROOVY_SCRIPT_BLACKLIST_PATCH
?thrown.cause.message	  	  GROOVY_SCRIPT_BLACKLIST_PATCH
?thrown.cause.name	  	  java.lang.NoSuchFieldError

{
  "class": "org.elasticsearch.cluster.settings.ClusterDynamicSettingsModule",
  "method": "<init>",
  "file": "ClusterDynamicSettingsModule.java",
  "line": 105,
  "exact": false,
  "location": "org.elasticsearch-elasticsearch-1.7.1.jar",
  "version": "?"
},
{
  "class": "org.elasticsearch.cluster.ClusterModule",
  "method": "spawnModules",
  "file": "ClusterModule.java",
  "line": 64,
  "exact": false,
  "location": "org.elasticsearch-elasticsearch-1.7.1.jar",
  "version": "?"
},
{
  "class": "org.elasticsearch.common.inject.ModulesBuilder",
  "method": "add",
  "file": "ModulesBuilder.java",
  "line": 44,
  "exact": false,
  "location": "org.elasticsearch-elasticsearch-1.7.1.jar",
  "version": "?"
},
{
  "class": "org.elasticsearch.node.internal.InternalNode",
  "method": "<init>",
  "file": "InternalNode.java",
  "line": 190,
  "exact": false,
  "location": "org.elasticsearch-elasticsearch-1.7.1.jar",
  "version": "?"
},
{
  "class": "org.elasticsearch.node.NodeBuilder",
  "method": "build",
  "file": "NodeBuilder.java",
  "line": 159,
  "exact": false,
  "location": "org.elasticsearch-elasticsearch-1.7.1.jar",
  "version": "?"
},
{
  "class": "org.elasticsearch.node.NodeBuilder",
  "method": "node",
  "file": "NodeBuilder.java",
  "line": 166,
  "exact": false,
  "location": "org.elasticsearch-elasticsearch-1.7.1.jar",
  "version": "?"
},

**Comment by dadoonet** [comment]
I don't have a clear picture of what you did.
I feel like you mixed different versions/jars in the same classloader.

**Comment by coderlol** [comment]
Well, I suspected classloader, but this is the line of code that caused it: nodeBuilder().clusterName("elasticsearch").client(true).data(false).node();

and, the stack trace (in original post) points toward the same jar...

**Comment by dadoonet** [comment]
Sorry. I have absolutely no context. Are you doing that from groovy, Java, Scala?
What is your server version? Is it exactly the same version for the client?

This field exists in 1.7: https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/script/groovy/GroovyScriptEngineService.java#L62

**Comment by coderlol** [comment]
Oh, I am using Java on Java 8 ;)  The client version is 1.7.1  I've a feeling this may be related to Java 8 unless somehow an incompatible Groovy jar got in the way.

**Comment by coderlol** [comment]
I had the below in my dependency list.  Strange, once upon a time, I had to declare it.  Going to remove the below and see how that goes.

        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch-lang-groovy</artifactId>
            <version>2.2.0</version>
        </dependency>

**Comment by dadoonet** [comment]
Indeed. As you can read on the plugin home page: https://github.com/elastic/elasticsearch-lang-groovy

> Important: This plugin is not needed anymore from elasticsearch 1.4 and is not maintained.

Closing. Feel free to reopen if you think we have an issue.
