### ISSUE TITLE
Tribe node compatibility

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#14075]
We don't document this, but there are [some users](https://discuss.elastic.co/t/tribe-node-compatibility/32015) that are federating clusters of different version.

It'd be great if we could document any version restrictions that this has.

**Comment by TinLe** [comment]
+1

We've run into compatibility issues and other problems mixing versions.   As a rule of thumb, it seem safer to use tribe node that lag versions to the clusters it is talking to.

E.g. downstream clusters are running versions M, N and O.   Tribe versions should be < lowest(M,N,O)

**Comment by ppf2** [comment]
+1  esp. since node clients are not compatible between 1.x and 2.x versions.

**Comment by vivekyaji** [comment]
Does this apply for 2.x and 5.x versions? I'm running into issues trying to connect tribe node (2.x) to cluster nodes running on 5.x (Received message from unsupported version: [2.0.0] minimal compatible version is: [5.0.0])
Also tried vise-versa 5.x tribe and 2.x cluster only to get transport error. 
I guess there is no compatibility for tribe nodes between major versions.

**Comment by vivekyaji** [comment]
Does this apply for 2.x and 5.x versions? I'm running into issues trying to connect tribe node (2.x) to cluster nodes running on 5.x (Received message from unsupported version: [2.0.0] minimal compatible version is: [5.0.0])
Also tried vise-versa 5.x tribe node and 2.x cluster nodes only to get transport error.
I guess there is no compatibility for tribe nodes between major versions.

**Comment by jasontedor** [comment]
> I guess there is no compatibility for tribe nodes between major versions.

There is none.

**Comment by javanna** [comment]
Tribe node has been deprecated and removed, I don't think we want to pursue this anymore, closing.
