### ISSUE TITLE
Long gc pause happened on es1.7.0 plus jdk8u40

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#14076]
https://discuss.elastic.co/t/long-gc-pause-happened-on-es1-7-0-plus-jdk8u40/31949
I answered in the discussion forum, but it seems one one can share insight. so I post the problem here to see if can get any help. 
problem:
es1.7.0 plus jdk8u40 and has a very long gc pause in minor gc:
22042 2015-10-10T10:36:44.751+0800: 1954567.631: [GC (Allocation Failure) 1954567.631: [ParNew: 1606667K->41270K(1763584 K), 1221.6222148 secs] 5895406K->4332232K(16581312K), 1221.6230128 secs] [Times: user=11780.20 sys=0.00, real=1221 .44 secs]

cluster description:
doc count: 4,695,567
index siez:4.7GB(primary shard + replicas)
index setting:
"number_of_shards": "10"
"number_of_replicas": "1"
node count: 4, 3 of them as master and data node, the other 1 is data node
heap commited: 16GB
GC affect only one node
system load:write with 500tps and search with 300tps
system hardware:256GB ram, 32 core Xeon 2.6GHZ, 1TB spin disk
here is another ES instance with same memory config running on that machine
swap been disabled

**Comment by clintongormley** [comment]
Hi @makeyang 

Let's keep the conversation in one place.  If you find a bug, then we can reopen an issue here. 

thanks
