### ISSUE TITLE
[Geo] Question about Geopoint hashCode/equals contract

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#14083]
Hi @nknize, some thing I noticed when working on the Geo-related queries was that the implementation of GeoPoint.hashCode() and equals() does not seem to follow the usual contract that when two objects are equal(), they should return the same hashCode. 
From the current implementation (https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/geo/GeoPoint.java#L133) it looks like when two points are very close (below the given lat/lon tolerance), they are considered equal, but they will return different hashCode() values. Since we rely on the GeoPoints hashCode/equals implementation in the geo queries, I'm curious about the reasons behind this and wondering if the class should be adapted so the contract holds.

**Comment by javanna** [comment]
this sounds like a bug, there shouldn't be any reason for the equals/hashcode contract to be broken other than a bug, maybe the two methods simply got out of sync at some point :)

**Comment by nknize** [comment]
Thanks for the catch @cbuescher! @javanna you're absolutely right, the methods diverged when cutting over to the Lucene Geo encoding which required the tolerance. I'll open a PR to resync the hashCode method.
