### ISSUE TITLE
shard relocation might leave files behind if deletion unsuccessful

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#14094]
When we delete shard content after is has been relocated away from a node and this deletion fails then it will just stay on disk until the whole index is deleted. There seems to be no additional mechanism to delete it later like we have for indices (PendingDelete). In case anyone likes to check, I wrote a test here for WindowsFS: https://github.com/brwe/elasticsearch/commit/b3598ac123f9d9e20726410e221fade6e4905d99
I think this is problematic?

**Comment by clintongormley** [comment]
FixItFriday agrees with you :)

**Comment by bleskes** [comment]
Agreed this is not nice - but just to make sure I get the scope - the shard will be delete with the next cluster state update, right?

**Comment by brwe** [comment]
Indeed, the description was misleading. The shard content is deleted with next cluster state update but the index directory and the metadata is not. It stays until the whole index is deleted.

**Comment by DaveCTurner** [comment]
Closing this in favour of https://github.com/elastic/elasticsearch/issues/104735
