### ISSUE TITLE
add instrumentation for sparse index detection

### ISSUE THREAD

**Issue by djschny** [elastic/elasticsearch#14095]
One current item to watch out for with doc values is the notion of "sparse indices". This is the situation where there is a disproportionate ratio of documents that have a value for a field versus those that do. For example if you have 1 million docs but only 1,000 have a particular field actually present in them, the amount of disk consumed will still be large.

In order to help detect this and other such situations, enhancing the instrumentation APIs to help report this on a field by field basis is probably helpful. Similar to what was done for fielddata on a field by field breakdown.

As requested after discussing with @jpountz yesterday while talking about this, suggested adding an issue here to discuss/track. Please any information I may have missed.

**Comment by clintongormley** [comment]
What would these APIs look like?

**Comment by jpountz** [comment]
For indexed fields, Lucene stores metadata about how many documents have a given field (`Terms.getDocCount()`). One issue however is that this metric is optional, some codecs might not store it. And also it wouldn't work if a field is mapped with doc values only.

Alternatively, monitoring tools could iterate over fields in the mapping and count how many documents contain this field using the `exists` query, which would work for any field that is either indexed or has doc values enabled.

However I'm not sure this is something that could be run on a regular basis as it might be costly if you have many shards or fields, so I think there should be a button in the monitoring UI to run such checks explicitly.

**Comment by clintongormley** [comment]
This sounds like an aggregation with an exists filter per field which can be run by Marvel.  Moving to Marvel
