### ISSUE TITLE
Search returns wrong results after Updated. "Slow update"

### ISSUE THREAD

**Issue by rodrigograca31** [elastic/elasticsearch#14098]
Hi!

I have the following code:
```bash
curl -XGET 'http://localhost:9200/INDEX/MAP/_search?pretty=true&q=active:1'
```
That returns something like this:

```json
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 4,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "INDEX",
      "_type" : "MAP",
      "_id" : "AVBDF16ioVCdFXKZcj8T",
      "_score" : 1.0,
      "_source":{"name":"Rodrigo 3","number":133,"active":1}
    }, {
      "_index" : "INDEX",
      "_type" : "MAP",
      "_id" : "AVBDGTnjoVCdFXKZcj8U",
      "_score" : 1.0,
      "_source":{"name":"Rodrigo 4","number":134,"active":1}
    }, {
      "_index" : "INDEX",
      "_type" : "MAP",
      "_id" : "AVBDFYIOoVCdFXKZcj8R",
      "_score" : 1.0,
      "_source":{"name":"Rodrigo 2","number":132,"active":1}
    } ]
  }
}
```

As you can see all of the "hits" have the key "active" set to 1....

So, let's update for example the second "hit" and set "active" to 0.
```bash
curl -XPOST 'http://localhost:9200/INDEX/MAP/AVBDGTnjoVCdFXKZcj8U/_update' -d '{
    "doc" : {
        "active": 0
    }
}'
```
Now, if I search again, how many results should be returned? 2 right?
```bash
curl -XGET 'http://localhost:9200/INDEX/MAP/_search?pretty=true&q=active:1'
```

```json
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 4,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "INDEX",
      "_type" : "MAP",
      "_id" : "AVBDF16ioVCdFXKZcj8T",
      "_score" : 1.0,
      "_source":{"name":"Rodrigo 3","number":133,"active":1}
    }, {
      "_index" : "INDEX",
      "_type" : "MAP",
      "_id" : "AVBDGTnjoVCdFXKZcj8U",
      "_score" : 1.0,
      "_source":{"name":"Rodrigo 4","number":134,"active":1}
    }, {
      "_index" : "INDEX",
      "_type" : "MAP",
      "_id" : "AVBDFYIOoVCdFXKZcj8R",
      "_score" : 1.0,
      "_source":{"name":"Rodrigo 2","number":132,"active":1}
    } ]
  }
}
```

**BUT IT RETURNS 3! WHAT?**
How's this possible?
It returns 2 if I wait some time, like 1 second...

What am I doing wrong? Or is a elasticsearch bug?

Note: My index is not called "INDEX", neither the mapping name is "MAP"....

Thanks!

**Comment by s1monw** [comment]
you have to call `_refresh` to make changes visible, it's called periodically every second by default. in the future for questions like this use https://discuss.elastic.co/ rather than the bug / issue tracker

**Comment by dadoonet** [comment]
It's because of the refresh which happens after 1s

You can force a refresh for test purpose

**Comment by rodrigograca31** [comment]
So, between the update and the last search I should run this?
```bash
curl -XPOST 'http://localhost:9200/INDEX/_refresh'
```
This doesn't make any sense...

**Comment by s1monw** [comment]
> This doesn't make any sense...

this is how ES and all lucene based systems work. They operate on point in time snapshots of the data that makes them very very efficient for fast reads etc. It's not a relational database that makes changes visible once the _transaction_ returns. It makes a boat load of sense if you look how this stuff is used in production and on the technical level. I hope this helps you to understand this.
