### ISSUE TITLE
discovery-ec2 plugin needs to throttle itself if it gets a RequestLimitExceeded exception

### ISSUE THREAD

**Issue by rtkmhart** [elastic/elasticsearch#14099]
Occasionally when building a cluster things go into a funny state (not ES's fault) and the discovery plugin (using https://github.com/elastic/elasticsearch-cloud-aws) tries to find the master. If the master can't be found, it appears that the plugin starts spamming the EC2 API with as many lookups per second as it can, which quickly ends with EC2 throwing RequestLimitExceeded exceptions. The proper behaviour in this case is for the plugin to backoff but it doesn't appear to do so. When this occurs, the EC2 console becomes unusable, affecting every EC2 api call for that AWS account.

Unfortunately I can't replicate the issue easily (we caught this when stumbling over a CloudFormation bug) and the CloudFormation stack would eventually roll back or we'd have to destroy the stack manually to try bring it under control. In either case we couldn't get any logs off the instances in time. I can share the CloudTrail logs if that will help. 

This issue was raised here: https://github.com/elastic/elasticsearch-cloud-aws/issues/229

With a PR against that repo: https://github.com/elastic/elasticsearch-cloud-aws/pull/231

**Comment by gmoskovicz** [comment]
Does elastic/elasticsearch-cloud-aws#231 fixes this?

**Comment by OTTERPUP333** [comment]
easy to reproduce: (discovered by accident)
in your yaml config, set ec2-discovery for some tag (any non-existent tag) and watch es thrash your EC2 console into non-responsiveness

**Comment by dadoonet** [comment]
I think that we can close it now as #14155 has been merged.
