### ISSUE TITLE
mapping lookup order issue

### ISSUE THREAD

**Issue by rob-tice** [elastic/elasticsearch#14100]
When searching across multiple types, the result of the query changes with the order the types are specified in the URL.  

e.g. 

the field autocomplete exists in 'type a' but not 'type b'.

index/type a,type b/_search?q=autocomplete:Xyx

 query works and returns the correct results from type a

index/type b,type a/_search?q=autocomplete:=Xyx - This fails with no hits - (looks like the query is not correctly analysed).

I can see a whole set of issues here but this does seems odd behaviour.

Thanks

Rob

**Comment by clintongormley** [comment]
@rob-tice I can't replicate your exact issue in 1.7.2, but it sounds like you're running into some of the issues with ambiguous mappings that exist in 1.x.  These problems have been solved in 2.0 but it is not possible to backport the changes.

To work around it, you can try prefixing the field with the type name: `?q=type_a.autocomplete:Xyx`

**Comment by rob-tice** [comment]
Thanks for the reply.  That is what I have done. Roll on 2.0!

Cheers

Rob
