### ISSUE TITLE
_close?ignore_unavailable=true doesn't seem to work

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#14102]
[Here](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/indices-open-close.html) mentions you can use `ignore_unavailable=true` to ignore any index that may not exist when closing an index. But if I have a cluster that doesn't have the `test` index and I try `POST /test/_close?ignore_unavailable=true` I get;
```
{
   "error": "IndexMissingException[[test] missing]",
   "status": 404
}
```
Which makes no sense. Not sure if it's the code or the docs that are wrong here.

Via [here](https://discuss.elastic.co/t/close-index-api-does-not-seem-to-provide-option-to-ignore-missing-indexes/31998)

**Comment by s1monw** [comment]
did you try this with 2.0 / latest master it seems like an old version of ES?

**Comment by clintongormley** [comment]
The situation is a bit complicated.  For instance:

    PUT test1
    {}


    # this throws an exception because no matching index was found
    POST test2/_close?ignore_unavailable

    # this succeeds, because it ignores test2 and still finds test1
    POST test1,test2/_close?ignore_unavailable

    # repeating the above command now fails, because test2 doesn't exist and test1 is closed
    # so no indices are found to operate on

We need to rethink these index options to figure out what the best defaults should be, and how requests with concrete names (or a single concrete name) should behave differently from requests with wildcards

Closing in favour of #9438

**Comment by stevenmwade** [comment]
This problem seems to still exist in 6.4 except it returns a 400 instead of a 404.

**Comment by javanna** [comment]
heya @stevenmwade I believe you get that error in case you have not specified any index, while this issue is a about some behaviour when specifying indices.

**Comment by stevenmwade** [comment]
@javanna Fou are correct. It looks like it ended up being a concurrency issue where we had something close them as we were checking them and it ended grabbing an empty list of indices. Our fault! Thanks for the reply!
