### ISSUE TITLE
Cluster get settings does not return settings set in elasticsearch.yml

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#14110]
If I put the following in my `elasticsearch.yaml`

```
cluster.routing.allocation.enable: none
indices.breaker.total.limit: 50%
discovery.zen.minimum_master_nodes: 1
```

Start my 1 node cluster and do a `GET /_cluster/settings` i'm seeing:

```
HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 32

{"persistent":{},"transient":{}}
```

Is this by design? Only if i `PUT /_cluster/settings` these values do they get returned by the get cluster settings.

**Comment by clintongormley** [comment]
@Mpdreamz settings in the config file are per node (and may be different on different nodes).  The cluster settings API today only returns settings set via the API.

We'd like to fix this in #6732
