### ISSUE TITLE
Java API _timeout + _msearch returns no aggregations

### ISSUE THREAD

**Issue by zackehh** [elastic/elasticsearch#14118]
It appears that when I add a timeout to an `_msearch` request in the Java client, all my aggregations are ignored and the filtering doesn't take place.

### Without Timeout

**request**

```java
MultiSearchRequestBuilder builder = esClient
    .prepareMultiSearch()
    .setIndicesOptions(IndicesOptions.lenientExpandOpen());

SearchRequest req = esClient
                .prepareSearch(req.getIndices())
                .setTypes(req.getType())
                .setSource(mySearchString)
                .setSearchType(SearchType.COUNT)
                .request();

builder.add(req);

MultiSearchResponse response = esClient
                .multiSearch(builder.request()).actionGet();

System.out.println(response.toString());
```

**response**

```
{
  "responses" : [ {
    "took" : 176,
    "timed_out" : false,
    "_shards" : {
      "total" : 12,
      "successful" : 12,
      "failed" : 0
    },
    "hits" : {
      "total" : 4,
      "max_score" : 0.0,
      "hits" : [ ]
    },
    "aggregations" : {
      "agg_name" : {
          "buckets": [
              // etc
          ]
      }
    }
  } ]
```

### With Timeout

**request**

```java
MultiSearchRequestBuilder builder = esClient
    .prepareMultiSearch()
    .setIndicesOptions(IndicesOptions.lenientExpandOpen());

SearchRequest req = esClient
                .prepareSearch(req.getIndices())
                .setTypes(req.getType())
                .setSource(mySearchString)
                .setSearchType(SearchType.COUNT)
                .setTimeout(TimeValue.timeValueSeconds(60))
                .request();

builder.add(req);

MultiSearchResponse response = esClient
                .multiSearch(builder.request()).actionGet();

System.out.println(response.toString());
```

**response**

```
{
  "responses" : [ {
    "took" : 43,
    "timed_out" : false,
    "_shards" : {
      "total" : 12,
      "successful" : 12,
      "failed" : 0
    },
    "hits" : {
      "total" : 38,
      "max_score" : 0.0,
      "hits" : [ ]
    }
  } ]
}
```

As far as I know, this should work and I can confirm there is no difference in the query being sent (this is in a unit test). Simply adding the timeout changes the response as above. Maybe I'm being stupid, but this looks like it has to be an ES bug?

I'm using ES 1.7.2, both the node and client lib.

**Comment by clintongormley** [comment]
Hi @zackehh 

Your call to `setTimeout()` is wiping out the source set by `setSource()`.  Move `setSource()` to the end and it will work.  This annoying behaviour will be fixed by a big search refactoring that is going into 3.0.

**Comment by javanna** [comment]
I am not sure inverting the order of the `setSource` and `setTimeout` helps. The main problem here is that you are specifying the search request as a string. After that you set the timeout, which is under the hood creating a new SearchSourceBuilder which wins against the one provided as a string. You should rather use the SearchSourceBuilder only, to set the timeout, and avoid providing the request as a string, which is also something that will go away in 3.0.

**Comment by zackehh** [comment]
Hey @clintongormley thanks for the reply - I'll try this out today. 

@javanna unfortunately I can't do that at the moment because everything we have focuses on building the Strings, so it'd be a nightmare to strip out just for this. I'll get back to you on whether the inverting works.

**Comment by javanna** [comment]
I think what might work instead then, as a temporary solution, is using the `setExtraSource` for your string request. That one won't be overridden I believe. Keep in mind that all this is going away in 3.0 though.

**Comment by zackehh** [comment]
Ok @clintongormley reversing didn't help, but @javanna's tip of `setExtraSource` did work.

What exactly is the different between `setSource` and `setExtraSource`? I've never seen the latter used anywhere. 

I'll keep in mind that this is going in 3.0 (that's pretty far off though, right?), so I'll set it in motion to move to not using Strings. Thanks for your help guys.

**Comment by javanna** [comment]
Glad you found a solution! extra source is something that we use internally for stuff that can come from both the request body and query_string parameters (e.g. the `query`, `size` etc.). It effectively allows to add additional parameters without touching the original source, handy given that the original source might be a bytes array that would require parsing to be modified.

The reason why this is all going away is that we are moving all the parsing to the coordinating node, while at the moment (2.x too) we still stream json between the different nodes and parse it multiple times, on each data node. At that point once a request is parsed to java objects it is fully represented as a java object (no bytes array or strings, so no parsing needed anymore).

**Comment by zackehh** [comment]
@javanna sweet! Since it's internal, I guess I shouldn't abuse it too much? 

Thank you for the extra info, and for your help with getting me going :)
