### ISSUE TITLE
Size/from limits should be per-request not per-index

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#14116]
The change in https://github.com/elastic/elasticsearch/pull/13188 added a per-index setting to limit the maximum number of search results that can be requested.  However, it would still be possible to request too many results by querying multiple indices.

Instead, this should be a dynamic cluster-level setting which applies to each search request, regardless of the number of indices involved.

**Comment by jpountz** [comment]
Do you mean you want to limit `${size} x ${number of shards involved in the search request}` instead of just the value of `${size}`?

**Comment by clintongormley** [comment]
OK - appears I misunderstood the current implementation.  I thought that a limit of 10,000 per index when searching 100 indices could result in 1,000,000 hits being returned.  Actually, it will return a max of 10,000.  Closing this issue
