### ISSUE TITLE
Aggregation counts mismatch

### ISSUE THREAD

**Issue by PandiyanCool** [elastic/elasticsearch#14128]
Hi Team,

I'm seeing something different in the aggregation functionality.

I have done a search as follows

    POST myindex/mytype/_search
    {
      "size": 0,
      "aggs": {
        "my_agg": {
          "terms": {
            "field": "myfield.mysubfield",
            "size": 200
          }
        }
      }
    }

I have got the following count in the result set

    {
           "key": "Engineer",
           "doc_count": 16199
    }

but expected count is **16388**

When i did something like the following, I'm getting the expected count which is 16388

    POST myindex/mytype/_search
    {
      "size": 0, 
      "query": {
        "match": {
          "myfield.mysubfield": "Engineer"
        }
      }, 
      "aggs": {
        "my_agg": {
          "terms": {
            "field": "myfield.mysubfield",
            "size": 200
          }
        }
      }
    }

Am I doing something wrong in the first query?

I have experimented one more case in the first query, when i changed size part in the query as follows(**2000**) I'm getting the expected count

    POST myindex/mytype/_search
    {
      "size": 0,
      "aggs": {
        "my_agg": {
          "terms": {
            "field": "myfield.mysubfield",
            "size": 2000
          }
        }
      }
    }

And I'm saying Boom!!!

Is this expected?

**Comment by dadoonet** [comment]
Yes. Read this: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html?q=terms%20aggrega#search-aggregations-bucket-terms-aggregation-approximate-counts
