### ISSUE TITLE
Document _cluster/health?local

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#14125]
[Here](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/cluster-health.html) we make no mention of the `?local` flag, but it seems that [in the code](https://github.com/elastic/elasticsearch/blob/v1.7.2/src/main/java/org/elasticsearch/rest/action/admin/cluster/health/RestClusterHealthAction.java#L52) and also [in the API spec](https://github.com/elastic/elasticsearch/blob/v1.7.2/rest-api-spec/api/cluster.health.json#L21-L24) it's available.

Plus if you tack it onto  a call to nodes in your cluster it returns a valid response.

**Comment by fforbeck** [comment]
local:
    If `true` returns the local node information and does not provide
    the state from master node. Default: `false`.

@markharwood, Is this description good enough?

**Comment by clintongormley** [comment]
@fforbeck looks good, want to send a PR?

**Comment by clintongormley** [comment]
ah, I see you have: https://github.com/elastic/elasticsearch/pull/15403
