### ISSUE TITLE
Implement "interesting terms" in More Like This handler

### ISSUE THREAD

**Issue by dcramer** [elastic/elasticsearch#1412]
Solr implements the "interesting terms" for MLT queries: http://wiki.apache.org/solr/MoreLikeThisHandler

"One of: "list", "details", "none" -- this will show what "interesting" terms are used for the MoreLikeThis query. These are the top tf/idf terms. NOTE: if you select 'details', this shows you the term and boost used for each term. Unless mlt.boost=true all terms will have boost=1.0"

**Comment by alexksikes** [comment]
closed by https://github.com/elastic/elasticsearch/pull/10147

**Comment by sabi0** [comment]
Sorry for bringing this old issue up.
I couldn't find a way to determine "interesting terms" for MLT query with an ad-hoc document.
`_validate/query?explain=true` returns just "filtered(like:[...here goes my text...]))". Is such feature available?
