### ISSUE TITLE
Support numeric/max values for force awareness settings

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#14122]
For some environments (like Azure), force awareness is desirable to handle fault domains and update domains.  The fault and update domain specifications in Azure are in the form of numbers (eg. 0, 1, 2, 3, etc..):

Currently, using force awareness, we will have to specify:

```
    "cluster.routing.allocation.awareness.attributes":"updateDomain,faultDomain",
    "cluster.routing.allocation.awareness.force.updateDomain.values": "0,1,2,3,4"
    "cluster.routing.allocation.awareness.force.faultDomain.values": "0,1"
```

It will be helpful to provide a way for the force awareness settings to handle numeric values.   In this case, it will be nice to be able to just list the maximum number of fault and update domains. That way, when nodes come and go, we will always have the maximum list – even when we add nodes after the deployment which might use update domains not used yet in that deployment.

**Comment by clintongormley** [comment]
Hi @ppf2 

I'm not sure I see the benefit of what you're suggesting here.  The `values` always have to be explicitly listed.  If values are missing then we assume there are nodes missing and take the appropriate action, so there is no auto-adjustment if nodes come and go.  

So then it comes down to having an alternate syntax for a short list of values that happen to be numeric.  This is so easy to handle client side, i don't understand why we would possibly add more complex settings in Elasticsearch to handle this one particular use case that doesn't apply to most users, who will use descriptive values instead (`zone_1`, `region_x`).

Closing as won't fix.
