### ISSUE TITLE
ghosts of discovery-ec2 in 2.x branches

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#14127]
Looks like a test that should be in cloud-aws instead?

https://github.com/elastic/elasticsearch/tree/2.0/plugins/discovery-ec2/src/test/java/org/elasticsearch/discovery/ec2

**Comment by dadoonet** [comment]
Argh! Indeed! That's what happens when you cherry pick from a branch which have been refactored! :p 

Will fix. Thanks for catching it!

**Comment by dadoonet** [comment]
fixed by #14314
