### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#14129]
please add a disable option for cluster.routing.allocation.allow_rebalance for some usecase.

**Comment by makeyang** [comment]
usecase:
disable rebalance and then move all shard from one node to another now, and then shutdown the old one

**Comment by clintongormley** [comment]
you can use shard allocation filtering to do that. see https://www.elastic.co/guide/en/elasticsearch/reference/2.0/allocation-filtering.html
