### ISSUE TITLE
2.0.0~rc1 not available in the relevant APT repo

### ISSUE THREAD

**Issue by tianon** [elastic/elasticsearch#14142]
When using `deb http://packages.elasticsearch.org/elasticsearch/2.0/debian stable main`, the latest available version is still `2.0.0~beta2` -- did something change in the deployment scripts for `rc1`?

**Comment by clintongormley** [comment]
Yes, the repo is now `2.x` instead of `2.0`.  See https://www.elastic.co/guide/en/elasticsearch/reference/2.0/setup-repositories.html

**Comment by tianon** [comment]
Ahhhh, thanks @clintongormley; sorry for the bother!
