### ISSUE TITLE
How to switch default HttpServerTransport?

### ISSUE THREAD

**Issue by ruria** [elastic/elasticsearch#14148]
Hi, I´m migrating a plugin from 1.5 to 2.0, it switch default NettyHttpServerTransport to add some sort of securiity, but I confused, since 40f119d85a4eaa39d0a6e594e46f70de725557f0 it seems to me that "http.type" parm doesn´t work (see HttpServerTransport.java)

I´m right? Is there any other way to do that? How is supossed I can call setHttpServerTransport?

**Comment by clintongormley** [comment]
@rjernst any ideas?

**Comment by rjernst** [comment]
I think we should add `http.type` back (as a parallel to `transport.type`), and remove `setHttpServerTransport`. I'll try to get that done, not sure when I will get to it though.

**Comment by ruria** [comment]
maybe I can help with this.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by ruria** [comment]
I´m trying to solve this, but little stuck. Please, see my commit here bbbcc528081a9235146474169ff094291ee8d356  

This works, but my plugin tries to startup a tomcat instance instead netty, so I need to include tomcat (and others) .jar in ES classpath, because by default, this files are included in child plugin class loader when loading my plugin, not in the main thread one.  Is there a way to fix this?

**Comment by rjernst** [comment]
@ruria There were some issues with your commit and some more general cleanup that needed to happen anyways. I opened a PR: #15434

**Comment by rjernst** [comment]
Also, to answer your original question on how to do this: with my PR, you will need to create a plugin that implements `onModule(NetworkModule module)` and then calls `module.registerHttpTransport("awesomeNameOfYourImpl", YourHttpTransportImpl.class)`. You would then set `http.type: awesomeNameOfYourImpl` in either your elasticsearch.yml, or in `additionalSettings()` for your plugin.
