### ISSUE TITLE
Parent/child reference "cache" cleared when deleting mapping

### ISSUE THREAD

**Issue by kuseman** [elastic/elasticsearch#14156]
Hi,

A small disaster "happend" yesterday when I removed some non used mappings which had parent type set on their mappings. What happend was that all queries that made use of **has_child** with the same parent type as the mapping that was removed returned zero result.

Example
```
{
   "mappings":{
      "child1":{
         "properties":{
            "value":{
               "type":"string"
            }
         },
         "_parent":"parent"
      },
      "child2":{
         "properties":{
            "value":{
               "type":"string"
            }
         },
         "_parent":"parent"
      }
   }
}
```
Queries are made:
```
POST host:port/index/parent/_search
{
   "filter":{
      "has_child":{
         "type":"child1",
         "filter":{
            .....
         }
      }
   }
}
```
And a delete request is made to **DELETE host:port/*/child2** and suddenly the query above starts to return zero results.

Is this a expected behavior? To me this seems like a bug.
I read that in elasticsearch 2.x.x, delete a mapping will not be supported so this might be a no issue.

**Comment by clintongormley** [comment]
Hi @kuseman 

Yes it looks like a bug, but one we won't fix as you can no longer delete mappings in 2.0, which should stop this bug from being triggered.

From my testing you can recover from this situation by clearing the caches:

    curl -XPOST "http://localhost:9200/_cache/clear"
