### ISSUE TITLE
Elasticsearch 2.0.0-rc1 displaying strange data

### ISSUE THREAD

**Issue by robertsmarty** [elastic/elasticsearch#14154]
I have logstash 2.0.0-beta2 sending AWS detailed billing data into elasticsearch 2.0.0-rc1 so I can test my setup. I've setup a template so all fields are doc_values.

Logstash rubydebug output looks great. Data is as expected. Elasticsearch dynamic mappings look great. Data types look great. Fields are not analysed. All good.

Then I look at the data. Weird, here's a small sample. Hopefully it'll make sense to someone...

            {
                "_index": "aws_billing-2015.08.31",
                "_type": "detailed_with_resources_and_tags",
                "_id": "\"60012830\",\"588738232867\",",
                "_score": 1,
                "_source": {
                    "@version": "1",
                    "@timestamp": "2015-08-31T23:00:00.000Z",
                    "host": "PBNEELK4001",
                    "type": "detailed_with_resources_and_tags",
                    "InvoiceID": "\"6001283",
                    "PayerAccountId": "\"60012830\",\"",
                    "LinkedAccountId": "\"60012830\",\"",
                    "RecordType": "\"6001283",
                    "RecordId": "\"60012830\",\"588738232867\",",
                    "ProductName": "\"60012830\",\"588738232867\",",
                    "RateId": "\"600128",
                    "SubscriptionId": "\"60012830",
                    "PricingPlanId": "\"60012",
                    "UsageType": "\"60012830\",\"58873823286",
                    "Operation": "\"600128",
                    "AvailabilityZone": "",
                    "ReservedInstance": "N",
                    "ItemDescription": "\"60012830\",\"588738232867\",\"128881676082",
                    "UsageQuantity": 0.00138889,
                    "BlendedRate": 1,
                    "BlendedCost": 0.00138889,
                    "UnBlendedRate": 1,
                    "UnBlendedCost": 0.00138889,
                    "ResourceId": null,
                    "aws_cloudformation_logical_id": null,
                    "aws_cloudformation_stack_id": null,
                    "aws_cloudformation_stack_name": null,
                    "user_Env": null,
                    "user_Environment": null,
                    "user_Name": null,
                    "user_Project": null,
                    "user_Purpose": null,
                    "user_Role": null,
                    "user_User": null,
                    "user_Workspace": ""
                }

This is what rubydebug looks like (it's not the same record though)...

{
                         "@version" => "1",
                       "@timestamp" => "2015-09-07T08:00:00.000Z",
                             "host" => "HOST4001",
                             "type" => "detailed_with_resources_and_tags",
                        "InvoiceID" => "xxx830",
                   "PayerAccountId" => "xxx867",
                  "LinkedAccountId" => "xxx944",
                       "RecordType" => "LineItem",
                         "RecordId" => "40214935098354950258880757",
                      "ProductName" => "Amazon Simple Storage Service",
                           "RateId" => "3510841",
                   "SubscriptionId" => "112242859",
                    "PricingPlanId" => "505699",
                        "UsageType" => "APS2-DataTransfer-Out-Bytes",
                        "Operation" => "ReadBucketPolicy",
                 "AvailabilityZone" => "",
                 "ReservedInstance" => "N",
                  "ItemDescription" => "$0.140 per GB - up to 10 TB / month data transfer out",
                    "UsageQuantity" => 1.16e-06,
                      "BlendedRate" => 0.13724872926531,
                      "BlendedCost" => 1.6e-07,
                    "UnBlendedRate" => 0.14,
                    "UnBlendedCost" => 1.6e-07,
                       "ResourceId" => "w-001006-emr-admin",
    "aws_cloudformation_logical_id" => nil,
      "aws_cloudformation_stack_id" => nil,
    "aws_cloudformation_stack_name" => nil,
                         "user_Env" => nil,
                 "user_Environment" => nil,
                        "user_Name" => nil,
                     "user_Project" => nil,
                     "user_Purpose" => nil,
                        "user_Role" => nil,
                        "user_User" => nil,
                   "user_Workspace" => ""
}

This worked perfectly on logstash 1.5 and elasticsearch < 2.x

**Comment by clintongormley** [comment]
This isn't an Elasticsearch issue. Moving to Logstash

**Comment by clintongormley** [comment]
This issue was moved to elastic/logstash#4048
