### ISSUE TITLE
Add hint for Array mappings (simple and complex types)

### ISSUE THREAD

**Issue by jeffsteinmetz** [elastic/elasticsearch#14151]
It seems like a "hint" would be helpful to projects like elasticsearch-hadoop / spark if the mappings exposed when a json **array** is expected.
https://github.com/elastic/elasticsearch-hadoop/issues/484
https://github.com/elastic/elasticsearch-hadoop/issues/482

It may also be useful for tools like Kibana.
A hint such as `"array": true`

* (side note, this hint is unrelated to nested object mapping via `"type: "nested"`:  Similar to but really more of a hint vs. a nested mapping that actually changes how it is indexed.)

such as 
```
  "mappings": {
    "foo": {
      "properties": {
        "bar": {
          "array": true, 
          "properties": {
            "name":    { "type": "string"  },
            "scores":   { "type": "string", "array": true }
          }
        }
      }
    }
  }
}
```

which would provide hints to json documents such as
```
{"foo" : { "bar" : ["name": "jeff", "scores": [10,20,30], "name" : "bob", "scores" : [5,10] ] } }
```

**Comment by clintongormley** [comment]
Hi @jeffsteinmetz 

Any field in Elasticsearch can be an array or a single value, so I don't like adding the `array` parameter as a hint.  However, this kind of application specific extra mapping info can be stored in the mapping in the [_meta field](https://www.elastic.co/guide/en/elasticsearch/reference/master/mapping-meta-field.html).
