### ISSUE TITLE
Getting document by ID with '/' slash in the id

### ISSUE THREAD

**Issue by andrejserafim** [elastic/elasticsearch#14177]
Trying to insert or get a document with path "/twitter/tweet/a%2Fe" results in a "No handler found for uri [/twitter/tweet/a%2Fe] and method [GET]" response. Response code 400.

It seems it's a regression of previous behaviour unless I'm missing something.

This is running against es-2.0.0-rc1.

**Comment by javanna** [comment]
Hi @andrejserafim thanks a lot for reporting this, it was as you said a regression in 2.0.0-rc1 which will be fixed in 2.0.0 GA.

**Comment by andrejserafim** [comment]
Thanks!
