### ISSUE TITLE
Setup cluster for multiple subscriptions [Azure]

### ISSUE THREAD

**Issue by yellow1912** [elastic/elasticsearch#14175]
I currently have machines in more than 1 subscriptions connecting via VirtualNetwork. 
As of now this plugin seems to support only 1 single subscription so it would be nice if it does allow a collection of subscription instead

Issue from old plugin repo:
https://github.com/elastic/elasticsearch-cloud-azure/issues/106

**Comment by dadoonet** [comment]
Just to be sure. It's for discovery, right? Not for snapshot and restore? I mean that azure repositories already [allow multiple accounts](https://www.elastic.co/guide/en/elasticsearch/plugins/current/cloud-azure-repository.html#cloud-azure-repository).

**Comment by DaveCTurner** [comment]
Since https://github.com/elastic/elasticsearch/pull/19186 deprecates the `discovery-azure` plugin, I think this can be closed. Something to bear in mind when working on the new ARM-based discovery.

**Comment by DaveCTurner** [comment]
(Linking #19146)
