### ISSUE TITLE
Rename QueryBuilder objects as they are not builders 

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#14192]
With the query refactoring we refactored all of our query objects. As a result, they are not builders anymore although we kept the `Builder` suffix to avoid making too many changes at the same time and dealing with merge conflicts. Now that all queries are refactored and everything is in master, it is time to settle on new naming and rename them all. One tricky aspect could be that removing the `Builder` suffix would result in many cases to the same class name as the corresponding lucene query, which sits though in another package. Shall we just remove the suffix or can anybody come up with some better name convention for our own query objects? :)

**Comment by s1monw** [comment]
oooh fun! I am all for it but what are we doing with things like `TermQuery` it will have name clashes? I know it's a pain but I already spend a lot of time on this without a good solution so lets see if other can come up with something good?

**Comment by s1monw** [comment]
We can come up with better names ie `KeywordQuery` ?

**Comment by javanna** [comment]
Quick question, given that the package names would differ, what would be the actual problems if we have name clashes with lucene in practice?

**Comment by MaineC** [comment]
Simple things first: big +1 on removing the builder suffix - no matter what the final names will look like, these classes aren't builders anymore so they shouldn't be named builders.

As for final names (aka here are my bikeshedding arguments): Just dropping the suffix means that users who are already familiar with our Java API have an easier time switching. Also current names being close to the original Lucene names means that knowing Lucene already helps when adopting Elasticsearch (not sure though whether those knowing Lucene already is still the majority of newcomers to Elasticsearch). Only downside: You have to look closer which class you open in your IDE from a search to not open the wrong one (For me personally that isn't much of a problem, might be different for others). 

Switching to different names looses the link to the original Lucene query - this can be both good and bad: Might make things clearer (after tons of arguments on which name to select), it potentially gives us an option to switch the underlying implementation without confusing users, might make things more complicated for those trying to apply their Lucene knowledge to Elasticsearch.


IMHO: I'd stick with the current names w/o the builder suffix.

**Comment by clintongormley** [comment]
Is this issue now resolved?

**Comment by javanna** [comment]
not resolved, needs to be done.

**Comment by javanna** [comment]
I wonder if this should be doen for 6.0. That way we could stay with what we have in 5.0 and cause less upgrade pain to java api users. We plan to make java api an internal only thing in 6.0 so renaming is going to be much less problematic at that point. I will label 6.0.0 rather than 5.0.0

**Comment by nik9000** [comment]
I'm comfortable waiting until 6 for this.

**Comment by MaineC** [comment]
Sounds like a good plan to me as well.

**Comment by javanna** [comment]
Given that this issue has been opened for a long time, I wonder if we really want to pursue this. Once transport client is removed (it is currently deprecated) this will become a high-level REST client issue only, as query builders are only a client thing. And we've been using the `Builder` suffix also for other similar classes like `AggregationBuilder`, `SuggestBuilder`. I am not sure that it's worth changing this at this point, with all the breaking changes that it would cause. Closing, we can always reopen if we change our mind.
