### ISSUE TITLE
Partial update of an index in Elasticsearch

### ISSUE THREAD

**Issue by malinir123** [elastic/elasticsearch#14199]
I have the following mapping with category as an array.

curl -XPUT http://localhost:9200/cstest/ -d '
{
    "mappings": {
	    "csproducts" : {
	        "properties" : {	         
	         	
	        	  "productid":{
	        	   	"type" : "String"	        	
	        	  },  
	        	  "productnumber":{
	        	   	"type" : "String"	        	
	        	  },       	
	        	  "category":{
	        		"type": "string",
			    	"null_value" : "N/A"	        	  
	        	  }
	        	
	         } //end properties
	      } //end csproducts
	      
        
    } //end mapping

}
'
Added 1 product to the index.

curl -XPUT 'http://localhost:9200/cstest/csproducts/1' -d '
{
    "productid":"1",
       "productnumber":"123",
    "category":"software"
}'

When I run the update to add another category,
curl -XPOST 'http://localhost:9200/cstest/csproducts/1/_update' -d'
{
   "script" : "ctx._source.category+=new_category",
   "params" : {
      "new_category" : "engineering"
   }
}'

Category is not indexed as an array of categories for that product. 
What is the command to run the partial updates?

H
curl -XGET 'http://localhost:9200/cstest/csproducts/1?pretty=true'
{
"_index" : "cstest",
"_type" : "csproducts",
"_id" : "1",
"_version" : 4,
"found" : true, "_source" : {"productid":"1","productnumber":"123200","category":"softwaredevelopment"}
}

**Comment by clintongormley** [comment]
Hi @malinir123 

Please ask questions like these in the forum http://discuss.elastic.co/

If `category` is a string, the `+` operator is going to perform an append operation.  You'd need to make `category` an array in the original document, or detect this case in your script.
