### ISSUE TITLE
Cat API uses Content-Type to determine response type 

### ISSUE THREAD

**Issue by Crassirostris** [elastic/elasticsearch#14195]
Right now _cat API uses Content-Type header to determine response type, instead of Accept header. Therefore GET request should contain Content-Type, but it cannot contain any content, because, well, it's GET request =) I think using Accept header would be much more consistent with http standard.

Example:

```
GET /_cat/nodes HTTP/1.1
Accept: application/json
Content-Type: application/json

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
```

but

```
GET /_cat/nodes HTTP/1.1
Accept: application/json

HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
```

**Comment by clintongormley** [comment]
I had absolutely no idea that this worked!  And I agree that it should be an Accept header instead of Content-Type.

Btw, you can also just add '?format=json'  to achieve the same thing.

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/14421
