### ISSUE TITLE
Document breaking changes introduced with #13752

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#14191]
With #13752 we introduced quite some breaking changes to the java api. We should review what we did and properly document those breaking changes in the migration guide for 3.0. Also, we should consider deprecating in 2.x some the methods that we have removed from `SearchRequest` and `SearchRequestBuilder` etc.

**Comment by javanna** [comment]
Also #14384 and #14270 made the same changes to `ExplainRequest`, `ExplainRequestBuilder`, `ValidateQuery` and `ValidateQueryRequestBuilder`. These should be documented the same way as we do it for the search request.

**Comment by clintongormley** [comment]
@javanna / @colings86 has this been done yet?

**Comment by colings86** [comment]
Not yet no. There are still some small changes being made to the search request so I was waiting for it to settle more.
