### ISSUE TITLE
Elasticsearch 502s when 

### ISSUE THREAD

**Issue by joshusre** [elastic/elasticsearch#14196]
I was able to complete this tutorial successfully: https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-4-on-centos-71 which let me set up an ELK stack on one box. Now, I'm trying to set up ES / Kibana / nginx on one box and ES / Logstash on another.

On server A, with minimal config (naming the ES cluster, making the ES network.host the server IP, and setting the ES url and host to the server IP), things work. But, when I try to follow this tutorial:
 https://www.elastic.co/guide/en/kibana/current/production.html to load balance across multiple nodes, I get a 502 when changing things to node.data = false OR node.master = false as instructed from curling IP:9200 instead of 200 before the change.

I also don't have much to go on in way of errors. I've tried preloading ES on server A with test data, because I noticed that without some data in ES, kibana4 502s.  Other than that,  I'm not really sure of what else to share.

**Comment by markwalkom** [comment]
Please join us in #elasticsearch on Freenode or at https://discuss.elastic.co/ for troubleshooting help or general questions. 

We reserve Github for confirmed bugs and feature requests :)

**Comment by joshusre** [comment]
I'll pass.  Good talk, bro :\
