### ISSUE TITLE
Elasticsearch return same score for documents with different freq count

### ISSUE THREAD

**Issue by lifo888** [elastic/elasticsearch#14198]
In the result of one of my searches, Elasticsearch gave two documents the same score, even though one doc has the word appear 3 times vs 12 times in the other doc.  I understand term frequency is only one part of the score calculation, but i don't understand how two docs with such different term frequency got identical score.  I know scores are only relative to the query, for my search, i'm hitting one index, one shard.

Document 1:
{
    "_shard" : 1,
    "_node" : "_BEa2e4ERfaoImOTCR5XMg",
    "_index" : "my_test_index",
    "_type" : "0000000003-nid",
    "_id" : "0001262463-15-000642-1",
    "_score" : 0.020258121, "_source" : {"story_datetime":"20151016T105524"},
    "sort" : [ 1444992924000 ],
    "_explanation" : {
        "value" : 0.020258121,
        "description" : "max of:",
        "details" : [ {
            "value" : 0.020258121,
            "description" : "weight(body:profit in 282422) [PerFieldSimilarity], result of:",
            "details" : [ {
                "value" : 0.020258121,
                "description" : "score(doc=282422,freq=3.0 = termFreq=3.0\n), product of:",
                "details" : [ {
                    "value" : 0.29820275,
                    "description" : "queryWeight, product of:",
                    "details" : [ {
                        "value" : 5.0203834,
                        "description" : "idf(docFreq=135277, maxDocs=7538025)"
                    }, {
                        "value" : 0.0593984,
                        "description" : "queryNorm"
                    } ]
                }, {
                    "value" : 0.06793405,
                    "description" : "fieldWeight in 282422, product of:",
                    "details" : [ {
                        "value" : 1.7320508,
                        "description" : "tf(freq=3.0), with freq of:",
                        "details" : [ {
                            "value" : 3.0,
                            "description" : "termFreq=3.0"
                        } ]
                    }, {
                        "value" : 5.0203834,
                        "description" : "idf(docFreq=135277, maxDocs=7538025)"
                    }, {
                        "value" : 0.0078125,
                        "description" : "fieldNorm(doc=282422)"
                    } ]
                } ]
            } ]
        } ]
    }
}

Document 2:
{
    "_shard" : 1,
    "_node" : "_BEa2e4ERfaoImOTCR5XMg",
    "_index" : "my_test_index",
    "_type" : "my_test_doc",
    "_id" : "0001413507-15-000005-1",
    "_score" : 0.020258121, "_source" : {"story_datetime":"20151016T060653"},
    "sort" : [ 1444975613000 ],
    "_explanation" : {
        "value" : 0.020258121,
        "description" : "max of:",
        "details" : [ {
            "value" : 0.020258121,
            "description" : "weight(body:profit in 463036) [PerFieldSimilarity], result of:",
            "details" : [ {
                "value" : 0.020258121,
                "description" : "score(doc=463036,freq=12.0 = termFreq=12.0\n), product of:",
                "details" : [ {
                    "value" : 0.29820275,
                    "description" : "queryWeight, product of:",
                    "details" : [ {
                        "value" : 5.0203834,
                        "description" : "idf(docFreq=135277, maxDocs=7538025)"
                    }, {
                        "value" : 0.0593984,
                        "description" : "queryNorm"
                    } ]
                }, {
                    "value" : 0.06793405,
                    "description" : "fieldWeight in 463036, product of:",
                    "details" : [ {
                        "value" : 3.4641016,
                        "description" : "tf(freq=12.0), with freq of:",
                        "details" : [ {
                            "value" : 12.0,
                            "description" : "termFreq=12.0"
                        } ]
                    }, {
                        "value" : 5.0203834,
                        "description" : "idf(docFreq=135277, maxDocs=7538025)"
                    }, {
                        "value" : 0.00390625,
                        "description" : "fieldNorm(doc=463036)"
                    } ]
                } ]
            } ]
        } ]
    }
}

**Comment by jpountz** [comment]
This is expected: doc 1 has a factor of 1.7320508 thanks to its doc freq and 0.0078125 because of its length, and doc 2 has a contribution of 3.4641016 for the freq and 0.00390625 for its length. When you multiply contributions, you get 0.0135 in both cases.

So in short, doc 2 is not more relevant because it's longer than doc 1 and gets penalized because of that.
