### ISSUE TITLE
Java api: revise SearchRequest and SearchRequestBuilder object structure

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#14190]
Once we are done with the search refactoring, we should revise the `SearchRequest` object structure, since it has a few problems:
- there are multiple ways to do the same thing e.g. `client.prepareSearch().addSort(sort)` and `client.prepareSearch().setSource(new SearchSourceBuilder().sort(sort)`. Some arguments can be provided directly to the builder, but they become part of the inner source object. 
- confusing behaviour (especially after #13859) e.g. in `client.prepareSearch().addSort(sort).setSource(source)` the setSource wipes the sort criteria that was added in the first place.

After #13859 we parse queries on the coordinating node, but the rest of the `SearchSourceBuilder` is still streamed as json bytes array to the data nodes and parsed once per data node. Once we have refactored all of the search sections (listed in #10217) all of the parsing will happen on the coordinating node, and it will be the right time to revise the `SearchRequest` object structure. It might very well be that the `SearchSourceBuilder` object is not needed anymore and all of its getters/setters can be collapsed to the `SearchRequest`/`SearchRequestBuilder`. Anyways we should have a single consistent way of settings things to the `SearchRequestBuilder` rather than the confusing multiple options that we have now.

**Comment by clintongormley** [comment]
@javanna @cbuescher is this still relevant?

**Comment by javanna** [comment]
yes still needs to be done.

**Comment by javanna** [comment]
I am looking into this. I would love to remove all of the `SearchRequestBuilder` setter methods that end up setting stuff to the `SearchSourceBuilder` object, which should rather be set explicitly using `setSource` only and using `SearchSourceBuilder` directly to provide query, size etc.

This would remove all the inconsistencies mentioned in this issue, but it turns out to be a huge change for java api users, very breaking as most people are using `client.prepareSearch().setQuery(query)` which would have to become `client.prepareSearch().setSource(new SearchSourceBuilder().query(query))`.  I don't think we should break every single java application at the moment. Also once transport client is going to be deprecated, this will not be a problem anymore. What do people think?

**Comment by javanna** [comment]
I am closing this, considering that the high level client only supports requests, not request builders. These inconsistencies will go away once transport client is removed, and request builders are as well.
