### ISSUE TITLE
dynamic:strict mapping, not validating fields if value of field is null.

### ISSUE THREAD

**Issue by Bkahler** [elastic/elasticsearch#14236]
It appears that this issue was brought up here [here](https://github.com/elastic/elasticsearch/issues/9444), and closed, however I am still seeing the same behavior in 1.7.3. 
As mentioned in the issue from the link, after creating an index with a mapping that includes `"dynamic":"strict"`, Elasticsearch will reject fields not specified in the mapping, only if the fields have a value. Passing a field with a `null` value will not be subject to any validation. Also see my stackoverflow post [here](http://stackoverflow.com/questions/33266982/elasticsearch-strict-mapping-not-working-for-fields-with-null-values)

**Comment by clintongormley** [comment]
It ignores fields with value `null`, because essentially they contain no values.  Not sure if we can do any more here, so marking this as "discuss"

**Comment by clintongormley** [comment]
Really there is nothing to do here - a field with a null value won't create a field, and so can't be rejected. Going to close this
