### ISSUE TITLE
Acknowledged: false for successful index settings operation

### ISSUE THREAD

**Issue by ilmerovingio** [elastic/elasticsearch#14248]
In a cluster of ~25 nodes running ES 1.7.1, ~900 indices, ~20k shards and ~1TB of data, when I run some "expensive" API call involving all indexes (example: set index allocation delay) I get `{ "acknowledged" : false }` even though the setting is applied properly. 

This API inconsistency block me to orchestrate automated operations without implementing some hack like splitting the calls to subset of indexes, retries and so on.

This issue seems to be related to #10607

**Comment by bleskes** [comment]
if your operation is expensive and takes longer than the default ack timeout of 30s, you should increase it using the `timeout` parameter to whatever makes sense. I'm closing this for now, please reopen if you have any more issues.

**Comment by ilmerovingio** [comment]
Hi @bleskes thanks for the suggestion but unfortunately I still see it as a workaround.  

I think that ES should provide API consistency.

**Comment by bleskes** [comment]
I'm afraid I don't follow you. What do you mean exactly with consistency? can you give a concrete example?

**Comment by ilmerovingio** [comment]
For consistency I mean: 

* if an operation fails API should return '{ "acknowledged" : false }'
* if an operation doesn't fail API should return '{ "acknowledged" : true }'

Right now the operation doesn't fail and the API returns fail. 

Do you suggest something like use a timeout parameters to an infinite number? In that case you'll probably wait forever but the response should be consistent, right?

**Comment by bleskes** [comment]
I see. We communicate failures using http status codes and an error indication. The acknowledgement indicates a time out - it means the master have done the requested operation (updated index settings) but waiting on the nodes timed out (because one of the nodes took too long to respond).

**Comment by ilmerovingio** [comment]
What about having a 'wait_for' flag similar than what we have for the cluster api? 

Example:
```
curl -XPUT 'http://localhost:9200/_all/settings?wait_for_ack=ALL&timeout=50s' -d '{something}'

wait for completion
Will wait (until the timeout provided) until the operation is acknowledge successfully by X nodes. Use 'all' for all the nodes.

timeout
A time based parameter controlling how long to wait if one of the wait_for_XXX are provided. Defaults to 30s.
```
This could be a useful improvement. What do you think about it?

**Comment by git-cambridge** [comment]
I am running into this issue too. Did you find any workaround for it? Maybe I shall just wait for the operation to conclude, then I will definitely know that the process was successful.

**Comment by ZiYou87** [comment]
Hello,

I am not familar with Elassandra and I get the mentioned problem too. I am tryping to create at first a index for the Cassandra keyspace, to be able to "search" on Elassandra.  When executing

curl -XPUT -H 'Content-Type: application/json' 'http://localhost:9200/obj_4_es' -d '{
    "settings": { "keyspace":"obj_4"},
    "mappings": {
        "netzobj" : {
            "discover":".*"
        }
    }
}'

I received the message ( after 30 seconds): {"acknowledged":false,"shards_acknowledged":false,"index":"obj_4_es"}

In Elassandra where are 13813564 rows - which means that the timeout is not enough. 

How could I increase it? Could I define it in elassandra.yml? oder somthing like this:

curl -XPUT -H 'Content-Type: application/json' 'http://localhost:9200/obj_4_es' -d '{
    "settings": { "keyspace":"obj_4", "timeout" : "60s" },
    "mappings": {
        "netzobj" : {
            "discover":".*"
        }
    }
}'

Using this, this error occurs:

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"unknown setting [index.timeout] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"}],"type":"illegal_argument_exception","reason":"unknown setting [index.timeout] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"},"status"

Thank you for helping.
