### ISSUE TITLE
No documentation of response from a bulk index request

### ISSUE THREAD

**Issue by evanphx** [elastic/elasticsearch#14257]
The docs simply say that the response is JSON and don't include any examples or schema.

**Comment by dadoonet** [comment]
Did you see this? https://www.elastic.co/guide/en/elasticsearch/guide/current/bulk.html?q=Bulk

**Comment by polyfractal** [comment]
This was my doing (twitter convo with @evanphx, I prompted him to submit a ticket). :) 

I agree that we should add an example response to the reference docs similar to what we have in the guide, just so it's clear. 

(Amusingly, I forgot we had an example in the Guide.  We could probably even steal the same example to put in the ref docs)

**Comment by dadoonet** [comment]
Yes or cross-link?

**Comment by evanphx** [comment]
Nope, I did not see the guide page since they're not linked to from the docs at all.

**Comment by clintongormley** [comment]
I'm going to close both PRs #14444 and #14449 which both just link to the guide.  Instead, let's just copy the relevant text into the ref docs.

**Comment by dakrone** [comment]
We have this now in the 5.x+ documentation, see: https://www.elastic.co/guide/en/elasticsearch/reference/5.x/docs-bulk.html
