### ISSUE TITLE
Recommended Heap - Documentation Error?

### ISSUE THREAD

**Issue by Rylon** [elastic/elasticsearch#14254]
Hi,

Just a quick one, I was reviewing the notes on recommended maximum heap sizes, but noticed one document states 32GB where another states 30.5GB. I assume it's 30.5GB since that is the latest recommendation from Oracle?

https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html
https://www.elastic.co/guide/en/elasticsearch/guide/current/_limiting_memory_usage.html

Thanks!

**Comment by clintongormley** [comment]
This issue was moved to elastic/elasticsearch-definitive-guide#426

**Comment by clintongormley** [comment]
It depends on the JVM - some cut over to uncompressed pointers at different heap sizes.  30.5GB is likely to be safe

**Comment by Rylon** [comment]
Yeah, that makes sense. I just thought it was worth raising so that the docs are consistent.

**Comment by clintongormley** [comment]
@Rylon Agreed - I just moved the issue to the right repository

**Comment by Rylon** [comment]
Thanks! :)
