### ISSUE TITLE
Delete document type in index with routing in 2.0.0

### ISSUE THREAD

**Issue by damienbod** [elastic/elasticsearch#14260]
How can you delete a document type from a index which uses routing in version 2.0.0 or later. I can delete a single document or the whole index, but not the type, when routing (or parent) is used.

Greetings Damien

**Comment by dadoonet** [comment]
Was removed. See https://www.elastic.co/guide/en/elasticsearch/reference/2.0/_mapping_changes.html#_types_may_no_longer_be_deleted

Please ask questions on discuss.elastic.co

**Comment by dottilotti** [comment]
Thanks
