### ISSUE TITLE
min_doc_freq missing suggester

### ISSUE THREAD

**Issue by Ard-Jan** [elastic/elasticsearch#14261]
I have an index(1 shard 0 replica's) with the following 6 documents:

<pre>
<code>
POST /test_suggest/type
{
  "word": "laptop"
}
POST /test_suggest/type
{
  "word": "laptop"
}
POST /test_suggest/type
{
  "word": "laptop"
}
POST /test_suggest/type
{
  "word": "laptup"
}
POST /test_suggest/type
{
  "word": "laptup"
}
POST /test_suggest/type
{
  "word": "laptip"
}
</code>
</pre>

When i do the following suggest query:

<pre>
<code>
GET /test_suggest/_suggest
{
  "Suggest": {
    "term": {
      "field": "word",
      "suggest_mode": "missing",
      "size": 5,
      "min_doc_freq": "0",
      "prefix_len": 0,
      "analyzer": "default",
      "sort": "frequency"
    },
    "text": "laptep"
  }
}
</code>
</pre>

I get the following suggestions:

<pre>
<code>
{
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "Suggest": [
      {
         "text": "laptep",
         "offset": 0,
         "length": 6,
         "options": [
            {
               "text": "laptop",
               "score": 0.8333333,
               "freq": 3
            },
            {
               "text": "laptup",
               "score": 0.8333333,
               "freq": 2
            },
            {
               "text": "laptip",
               "score": 0.8333333,
               "freq": 1
            }
         ]
      }
   ]
}
</code>
</pre>

That's exactly what i expected to get back. When i change the minimum document frequency to 1, it filters out the last document with "laptip".

But when i do the following query:

<pre>
<code>
GET /test_suggest/_suggest
{
  "Suggest": {
    "term": {
      "field": "word",
      "suggest_mode": "missing",
      "size": 5,
      "min_doc_freq": "1",
      "prefix_len": 0,
      "analyzer": "default",
      "sort": "frequency"
    },
    "text": "laptip"
  }
}
</code>
</pre>

I do not get any suggestions back. Normally it's logical that there are no suggestions because sugest_mode missing is used. But in this case i added the option min_doc_freq = 1, so i expected the following response:

<pre>
<code>
{
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "Suggest": [
      {
         "text": "laptep",
         "offset": 0,
         "length": 6,
         "options": [
            {
               "text": "laptop",
               "score": 0.8333333,
               "freq": 3
            },
            {
               "text": "laptup",
               "score": 0.8333333,
               "freq": 2
            }
         ]
      }
   ]
}
</code>
</pre>

Is this something that can be added to the functionality of the min_doc_freq parameter, or as a new option of the suggester?

**Comment by jimczi** [comment]
The suggester will generate suggestions for terms on shards that do not contain them no matter what the min frequency is:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-phrase.html#_direct_generators
You should use another mode and filter the results with the `confidence` option which is more fine grain. I am closing this issue because the suggester is working as expected and I don't think we should change the `missing` mode depending on the value of other options.
