### ISSUE TITLE
Geo Location Context suggester misses entities within the precision distance

### ISSUE THREAD

**Issue by lakshmithyagarajan** [elastic/elasticsearch#14271]
Hi,

We use the Completion/context suggester with geo hashes to power our autocomplete experience. ES client and server version is 1.3.4. We use 3 precisions: 4, 5 and 6. Neighbours are also enabled. 

However we noticed that some entities within the precision distance are not returned by the suggester. 

Eg: Precision 5 is approx. 3 miles x 3 miles.
We make a suggestion request from this lat/lng: 37.297304, -122.044645, for a safeway that is located at 37.281433, -122.031138. But it does not show up for precision 5 suggestion request.

The safeway shows up for precisions 4 and 5 requests from a lat/lng very close to it. So it is a a valid entity.
 
This is consistently noticeable for all 3 precisions. Since neighbours are enabled we expect this to work correctly.

Is this a known issue? Has this been fixed in the newer versions?

Here is the completion suggester definition:

{
  "entity" : {
    "properties" : {
      "name_suggest" : {
        "type" : "completion",
        "index_analyzer" : "standard_synonym_analyzer",
        "search_analyzer" : "standard_synonym_analyzer",
        "context": {
          "location": {
            "type": "geo",
            "precision": [4,5,6],
            "neighbours": true
          },
          "type" : {
            "type" : "category",
            "path" : "radius_type",
            "default" : ["local"]
          }
        }
      }
    }
  }
}

Thanks,
Lakshmi

**Comment by clintongormley** [comment]
Hi @lakshmithyagarajan 

Could you give us some concrete data points, ie some docs to index, and the completion requests that aren't working correctly?

thanks

**Comment by clintongormley** [comment]
Nothing further. Closing
