### ISSUE TITLE
Disk Based Allocation by Node/Node Tag

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#14289]
Currently today, we have disk based allocation that supports a cluster wide setting. This works great for most deployments where heterogeneous hardware is common, but it often fails when you have a hot/cold deployment with vastly different hardware for the two segments.

For example, if you have hot nodes with 3 TB of super fast storage and cold nodes with 20 TB of slower storage, then you may want to have very different rules for how much space should be available between the two groups.

Depending on your deployment, you may also be able to take advantage of certain properties. For example, the cold nodes may never have to deal with merging due to forced merges occurring on the hot nodes. Conversely, hot nodes then do have to deal with normal and final merging to a single segment. And cold nodes may also benefit in some setups where "summary" indices get created in the place of full data sets at a dramatically reduced size.

For this to work, either the setting would have to allow any node to override the cluster-wide setting, or to allow it to be set based on node tags, just as nodes get grouped that way already.

**Comment by clintongormley** [comment]
And using percentages isn't sufficient?

**Comment by pickypg** [comment]
Any percentage on 3 TB versus 20 TB is going to be a massive difference in absolute terms, when generally you can get by with a smaller percentage on such large drives.

**Comment by DaveCTurner** [comment]
This is an interesting idea, but since its opening we have not seen enough feedback that it is something we should work on. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback (including +1s).

**Comment by ebuildy** [comment]
It's a good feature, this could be achieved by using ``remote clusters`` (https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-remote-clusters.html) I believe ?

A perfect use-case is to design hot/warm architecture (as wrote here https://www.elastic.co/fr/blog/hot-warm-architecture-in-elasticsearch-5-x)
