### ISSUE TITLE
Use NFS as FsRepository for snapshot meet java.nio.file.NoSuchFileException

### ISSUE THREAD

**Issue by xuanyuanking** [elastic/elasticsearch#14298]
My ES version is 1.5.2.
When I use NFS as FsRepo for snapshot, while different shards of same index in different host and username(or even same username but in diffrent uid\gid), 
I got the partial error:
>{
>   "snapshots": [
>      {
>         "snapshot": "test",
>         "repository": "test_snapshot",
>         ...
>         "indices": {
>            "demo": {
>               "shards_stats": {
>                  "initializing": 0,
>                  "started": 0,
>                  "finalizing": 0,
>                  "done": 3,
>                  "failed": 2,
>                  "total": 5
>               },
>               ...
>               "shards": {
>                  "0": {
>                     "stage": "FAILURE",
>                     "stats": {
>                        "number_of_files": 0,
>                        "processed_files": 0,
>                        "total_size_in_bytes": 0,
>                        "processed_size_in_bytes": 0,
>                        "start_time_in_millis": 0,
>                        "time_in_millis": 0
>                     },
>                     "reason": "IndexShardSnapshotFailedException[[demo][0] Failed to perform snapshot (index files)]; nested: FileNotFoundException[/home/nfs/test_snapshot/indices/demo/0/__0 (Permission denied)]; "
>                  },
>                  "1": {
>                     "stage": "DONE",
>                     "stats": {
>                        "number_of_files": 4,
>                        "processed_files": 4,
>                        "total_size_in_bytes": 2712,
>                        "processed_size_in_bytes": 2712,
>                        "start_time_in_millis": 1445929403979,
>                        "time_in_millis": 9
>                     }
>                  },
>                  ...

java.nio.file.NoSuchFileException below in ES log:

> Caused by: java.nio.file.NoSuchFileException: /home/nfs/test_snapshot/indices/demo/2
>       at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
>        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
>        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
>        at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:426)
>        at java.nio.file.Files.newDirectoryStream(Files.java:411)
>        at java.nio.file.Files.newDirectoryStream(Files.java:468)
>        at
> org.elasticsearch.common.blobstore.fs.FsBlobContainer.listBlobsByPrefix(FsBlobContainer.java:65)
>        at org.elasticsearch.common.blobstore.fs.FsBlobContainer.listBlobs(FsBlobContainer.java:56)
>        at org.elasticsearch.index.snapshots.blobstore.BlobStoreIndexShardRepository$SnapshotContext.snapsh>ot(BlobStoreIndexShardRepository.java:438)

Should we need a write permission for other users to free user set the NFS user id mapping or make sure both client and server has same username.

Thanks

**Comment by dadoonet** [comment]
Unless you set the repository to read only, then you need a permission to access it in write mode on every node.

**Comment by xuanyuanking** [comment]
default permission of ${index_name}/${shard_num} is 775, should we add a attr param in FsBlobStore createDirectories?

**Comment by dadoonet** [comment]
I don't think so. May be we should document that in https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html?

@imotov WDYT?

**Comment by imotov** [comment]
@dadoonet it seems to be a common problem with NFS mounts. Not really sure how to deal with it though. This problem is now detected during repository validation, but it's still somewhat confusing.

**Comment by xuanyuanking** [comment]
@imotov @dadoonet 
My solution of this problem in production is only give all the ${index_name}/${shard_num} dir 777 permission in FsBlobStore, that make different shards in different user can write BlobStoreRepo.
Should we add a config item like "repositories.fs.open_write_permission" and control this? If you think this is nessisary, I want to give a PR on it.
