### ISSUE TITLE
Remove query_binary, filter_binary & aggs_binary 

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#14308]
We support `query_binary`, `filter_binary` and `aggs_binary` so a query, filter (post_filter actually) or aggregations can be provided in binary base64 format as part of the search request (plus other apis that support those sections).

This feature is undocumented and untested, at the point that we partially ended up removing it as part of the search refactoring (we currently don't parse query_binary anymore on the coordinating node).

I am opening this up for discussion, I never saw this feature used in real life, but maybe it is effectively used, anyways we should figure out whether we want to remove it or maintain it (then document it and test it too).

**Comment by dakrone** [comment]
+1 to remove (I also haven't ever seen it and this is first time I've ever heard of it as well)

**Comment by jpountz** [comment]
+1

**Comment by javanna** [comment]
I did some more digging and I think this binary thing is only used internally for situations where we don't parse on the coordinating node and the request source is streamed as a bytes array. This is all going away with the search refactoring so we can safely remove. The query and filter part is already almost obsolete (last usage is in validate query but I am working on it), the aggs_binary will stay around till the aggs refactoring is completed I believe.

**Comment by javanna** [comment]
`query_binary` and `filter_binary` have been removed as part of #14433. Only `aggs_binary` is left, which will be removed as part of the aggs refactoring that is being worked on. assigning @colings86 who is on it.

**Comment by colings86** [comment]
Done in https://github.com/elastic/elasticsearch/pull/14136
