### ISSUE TITLE
Stopwords are ignored in aggregation

### ISSUE THREAD

**Issue by Eightyplus** [elastic/elasticsearch#14307]
Hi,
I have setup my index with the following setting and afterwards aggreations on the index. But the settings seems to be ignored, is that how it should be?

```JSON
{
    "settings": {
        "analysis": {
            "analyzer": {
                "my_stop": {
                    "type":       "stop",
                    "stopwords":  "_danish_"
                }
            }
        }
    },
    "mappings": {
        "job": {
            "dynamic_templates": [ 
                {
                    "template_1": {
                        "match": "*",
                        "match_mapping_type": "string",
                        "mapping": {
                            "type": "string",
                            "analyzer": "my_stop"
                        }
                    }
                }
            ]
        }
    }
}
```

**Comment by Eightyplus** [comment]
Added with dynamic templates

```
{
    "settings": {
        "analysis": {
            "analyzer": {
                "my_stop": {
                    "type":       "stop",
                    "stopwords":  "_danish_"
                }
            }
        }
    },
    "mappings": {
        "job": {
            "dynamic_templates": [ 
                {
                    "template_1": {
                        "match": "*",
                        "match_mapping_type": "string",
                        "mapping": {
                            "type": "string",
                            "analyzer": "my_stop"
                        }
                    }
                }
            ]
        }
    }
}
```

**Comment by Eightyplus** [comment]
I tried adding a stopword filter to my "aggs" query and it that didn't work either.

A way to obtain what I want, but certainly not optimal:
("content" has to be replace with the field I'm doing aggs on)

´´´JSON
       "query": {
			"filtered": {
				"query": {
					"match_all": {}
				},
				"filter": {
					"bool": {
						"must_not": [
							{ "term": { "content": "a"}},
							{ "term": { "content": "s"}},
							{ "term": { "content": "k"}},
							{ "term": { "content": "og"}},
							{ "term": { "content": "v"}},
						]
					}
				}
			}
		}
´´´

**Comment by clintongormley** [comment]
Hi @Eightyplus 

Please join us in the forums instead: http://discuss.elastic.co/.  This issues list is for bug reports and feature requests.

**Comment by mpenet** [comment]
Did you find a solution? I hit the same wall, this was feasible on 1.x using `exclude` in the terms aggregation (using a list of words). However you can no longer mix `exclude` and `include` of different types (`include` in my case has to be a regex).

**Comment by clintongormley** [comment]
@mpenet just convert the list of words to a regex:

    [ foo,bar,baz ]  -> (foo|bar|baz)

**Comment by Eightyplus** [comment]
No I did not find a solution. I realized that the filter removes any document match which contain a "not" word and thought it would require either
1) new code to handle the filter (add request in discuss.elastic.co ..)
2) filter the words before indexing (the text could still be indexed as "not analyzed" to be able to query the entire text)

I thought it was to much trouble and have since moved on.
/Morten

**Comment by mpenet** [comment]
@clintongormley that's what I have at the moment, but it's super slow compared to the 1.x mixed regex + list in include exclude. I am thinking about inverting the logic to mitigate the problem since exclude are executed first, but I doubt I ll reach the perf of 1.x with that.

**Comment by mpenet** [comment]
to give you an idea, on the same dataset, same query (minus the change for exclude + new aggreg format)
1.7    : 0.7s 
2.1.2 : 2.8s 

There are 500ish terms in the "exclude" clause
