### ISSUE TITLE
Field stats query

### ISSUE THREAD

**Issue by pjcard** [elastic/elasticsearch#14301]
Currently, I use a pattern based indices in order to segregate my data. I use one per day per data set, and when searching supply the set of indices I want either as an index query (as a filter) or on the URL. This can be a little unwieldy with large non-month-aligned ranges due to the simple nature of the pattern matching available.

The fields API would allow me to index based on something other than a date pattern, but would mean I now required two lookups instead of one, i.e.
1/ Use field API to ascertain which indices I need for a given query
2/ Pass the index names in the URI for the search or within an indices query in the DSL.

What would be great would be if there was a field stats query that could be used as a filter in a search DSL order to perform the above steps within a single query. That would mean I neither had to rely on patterns nor pass index names in URLs or Filters. (My assumption is that the field stats api call to ascertain the minimum set of indices is far cheaper than searching without limiting the set of indices in the first place). I would have thought this might represent a useful approach for Kibana to use internally, too, unless it's caching the results for the field stats api requests separately to elasticsearch.

This suggestion was based upon a discussion in #10523

**Comment by clintongormley** [comment]
Hi @pjcard 

Elasticsearch would need to perform two requests, just like the client does today.  In fact, this is what Kibana does as well.  The field stats request is very fast, so I believe that Kibana doesn't cache the results but issues a fresh call before each search request (I may be mistaken here though).

Sorry, but i don't want to further complicate the already complicated search API by adding more options for what is essentially sugar.

**Comment by pjcard** [comment]
Hi @clintongormley,

Thanks for your reply. On reading about it, it was a slight surprise to me that the implication of it was that the default way to use elasticsearch has changed to making two RESTful calls, instead of one; or to put it another way, that the only part of the process of searching that has to be performed separately is the initial step of ascertaining which indices should be queried. (Given that it is fast, could it be applied implicitly based on the search DSL, instead? Or explicitly as a filter without options?)

In any case, thanks for the response. The information is much appreciated.
Paul
