### ISSUE TITLE
Java API: aggregations are not supported with search_type=scan

### ISSUE THREAD

**Issue by montyhall** [elastic/elasticsearch#14305]
Hi

I am getting an 

`elasticsearchIllegalArgumentException aggregations are not supported with search_type=scan`

error when using the java API. 

```
SearchResponse searchResponse = client.prepareSearch(_INDEX)
        .setSearchType(SearchType.SCAN)
  	.setTypes(_TYPE)
        .setQuery(qb)
        .setScroll(ScrollTimeout.createScrollTimeoutValue(wait,tu))
        .setSize(SCROLL_SIZE)
        .execute()
        .actionGet();
```
I understand this is a feature that is coming in release 2. In the meantime, is there an interim solution someone can recommend? The number of docs I need to process are in order of 50MM and growing at rate of 1MM/day. The solution I can think of right now is to use scan and create a gazetter (on disc) using Lucene's FST. 

Any help would be much appreciated

**Comment by clintongormley** [comment]
Aggs are not supported with scan in 2.0.  In 1.x, they were supported, but were recalculated for each subsequent request and returned incorrect values.  Aggs results are calculated over ALL hits, not just the hits that are returned in a single request.

Why are you wanting to use aggs with scanning?  I suggest you make two requests: one with size zero for the aggs, and another with scroll/scan to scroll through all the docs.
