### ISSUE TITLE
Strange limits when using Java API (array of objects) (SOLVED)

### ISSUE THREAD

**Issue by ane18s** [elastic/elasticsearch#14322]
It seems that there is some kind of limit in ES when creating an array of objects. 

I created a small example which you can easily try. Just don't forget to set the correct cluster name.

import org.elasticsearch.ElasticsearchException;
import org.elasticsearch.action.admin.indices.create.CreateIndexRequest;
import org.elasticsearch.action.admin.indices.delete.DeleteIndexRequest;
import org.elasticsearch.client.Client;
import org.elasticsearch.client.transport.TransportClient;
import org.elasticsearch.common.settings.ImmutableSettings;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.common.transport.InetSocketTransportAddress;
import org.elasticsearch.common.xcontent.XContentBuilder;
import org.elasticsearch.common.xcontent.XContentFactory;

public class ESTests {

    public static final String INDEX = "tempindex";
    public static final int SIZE1 = 3;
    public static final int SIZE2 = 3;

    public static void main(String[] args) throws Exception {

        Client client = new TransportClient(ImmutableSettings.builder().put("cluster.name", "ncluster").build())
                .addTransportAddress(new InetSocketTransportAddress("localhost", 9300));
        System.out.println("Client initialized.");
        try {
            //first delete the old index, if exists.
            client.admin().indices().delete(new DeleteIndexRequest(INDEX)).actionGet();
            System.out.println("Index deleted.");
        } catch (ElasticsearchException e) {
            //ignore
        }

        Settings settings = ImmutableSettings.settingsBuilder().build();
        System.out.println("Settings built.");
        //Then create a new-clean index.
        client.admin().indices().create(new CreateIndexRequest(INDEX, settings)).actionGet();
        System.out.println("Index created.");

        XContentBuilder cb = XContentFactory.jsonBuilder();
        int id = 1;
        cb.startObject();
        cb.field("name", "test document");
        
        {
            

            cb.startArray("testArray");
            String str = "";
            for(int i = 0; i < SIZE1; i++) str += "0";
            
            for(int i = 0; i < SIZE2; i++) {
                cb.startObject();
                cb.field("counter", i);
                cb.field("str", str);
                cb.endObject();
            }
            cb.endArray();
            
        }
        
        
        cb.endObject();

        client.prepareIndex(INDEX, "document", Integer.toString(id)).setSource(cb.string()).execute();

    }
}

When I change the constants SIZE1 and SIZE2, to values 100 and 1000 respectively, the document is not being created! Though, you might need to try bigger numbers on your pc.

To retrieve the document, I use the Sense plugin for Chrome and the following command: 
POST /tempindex/document/_search?pretty=1
{
     "query" : {
        "match_all" : {}
    }
}

I have posted a similar question here: https://discuss.elastic.co/t/strange-limits-when-using-java-api/32914 but nobody answered so far.

I am under a deadline so you reply soon, it will help me a lot.

Thanks!

**Comment by cbuescher** [comment]
Hi @ane18s,
sorry but I cannot reproduce this. Assuming you use ES 1.7, I can reliably create large arrays of objects with large fields (just tried it with 10000 array entries, 10000 chars), although Sense for me freezes on such large documents, but curl works just fine. I think there are two problems with the test code:
* just calling `execute()` on the IndexRequestBuilder will return a Future, but that only starts the index operation. If your test now aborts, the cluster might not have received it. Instead, like when issuing an index request via REST, you should wait for the response using `execute().actionGet()`. there's even a handy shortcut for this with the `get()` method on all ActionRequestBuilders. 
* also close the client after you are done with it

**Comment by ane18s** [comment]
THANK YOU!!! The "execute().actionGet()" solved the problem. Again, THANK YOU!
