### ISSUE TITLE
[Ingest] Add support for array/list access in path 

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#14324]
The ingest plugin's [Data](https://github.com/elastic/elasticsearch/blob/feature/ingest/plugins/ingest/src/main/java/org/elasticsearch/ingest/Data.java#L46-L53) class currently supports retrieval of a value using a path to a field specified in dot-notation (e.g. `foo.bar`). For more complex insertions, updates, and retrievals of nested fields within the document, it would be useful to be able to access fields through array/list typed fields.

The notation proposed here is to introduce a path element in the specified path that is an integer and is to be evaluated as an index into the parent array/list object.

```
# example paths
foo.bar.1.first
foo.4
foo.4.3.6.last
```

Here is an example: 
```
data = new Data("index", "type", "id",
                new HashMap<String, Object>() {{
                    put("foo", Arrays.asList("a", "b", "c");
                    put("fizz", new HashMap<String, Object>() {{
                        put("buzz", "hello world");
                    }});
                }});
assertThat(data.getProperty("foo.1"), equalTo("b"))
```

`addField` is also meant to support this behavior. more functions will have to be introduced to distinguish between an append to an array, and a full replace.

**Comment by javanna** [comment]
Read operations are clear in terms of syntax and expected results. The syntax for setting values to lists remains to be figured out. At the moment the add/set processor doesn't support appending values, if we set `"list":"item"` it will simply replace the list with a string `"item"`. Shall we move to adding by default (through set processor) if we find a list? Or shall we have a specific append processor?
And what if we get `{ "set" : {"list.1" : "value"}}`?

**Comment by martijnvg** [comment]
@javanna I lean towards having a separate `append` processor. Embedding the append a value into the `set` processor complicates things. For example your example, what if there is a field name with a `.` in it (`list.1` field name)? I also considered using an array syntax like this: `"list" : ["value"]`, but then I thought what if someone just wants to replace an array field field an array with a single element. 

If we would have a separate `append` processor then we have more control over how it can be used and certain behaviour in specific scenarios. For example an option to tell in what slot of the array a value needs to be appended. If the field doesn't exits yet when can just append an array with a single element and if the field already exists but isn't array we can fail with a clear error or maybe be lenient and append the existing value and new value into a new array. 

Downside is that we end up with another extra processor to kind of do what `set` processor does, but just for arrays...

**Comment by javanna** [comment]
@mvg I think the dot within a field name is not a concern as not supported anymore in es, but I totally agree that we should have a specific processor to deal with arrays explicitly.

**Comment by uboness** [comment]
I think setting a value in a specific index within an array is taking things a bit too far for the moment. I understand that this scenario theoretically exists, but I would love to hear an example for it. IMO, in the vast majority of use cases, ppl simply want the following three basic ops:

- set a field value (completely override)
- set a field value if doesn't already exist
- set a field value if doesn't exist or append/add it to an array if already exists.

I might be complete off with my assessment, but if I'm not, I think this should vold into a simple `set` processor. (would love to hear @talevy's opinion here)

**Comment by javanna** [comment]
With #15078 we have added the support for specifying indices of items within list. What's left to do is decide how to expose the append semantics. We now have an `IngestDocument#appendFieldValue` but it's not exposed to any processor yet. We have to discuss if we want to add a new append processor, or add an option to the set processor. Do we also need the "set if it doesn't exist" semantic? We don't have that at the moment, so that would be an additional "feature" to implement. Also, when we say "append it to the existing one/s" we mean only for arrays right? 
@clintongormley what do you think this should look like in terms of api?

**Comment by clintongormley** [comment]
Hmmm  I'd say that if somebody is OK with having a list of items, then it probably makes sense to always make it a list (even if it doesn't already exist).  So i'd have a dedicated `append` or `push` processor which will:

* append the specified value(s) to an existing array
* create an array with the specified value(s) if the field doesn't exist
* convert an existing scalar to an array then append the specified value(s)

It should be possible to specify multiple values as well:

    { "push": { "tags": "my_tag" }}
    { "push": { "tags": ["one", "two", "three" }}

For the option of: set-scalar-if-doesn't-exist, i think that is unlikely to be a common use case, but it could be implemented as a `create` processor if we really want to.

**Comment by uboness** [comment]
just an idea... now that we have `set` support paths like `field.0`, what if we added support for `field._last` that effectively indicates:

- if there's no field, create an array and add the value
- if there's an array, push/append it to the the end
- if there's a single value, create an array with that single value and push/append the new value to it

we could also support `field._first` in which case it'll prepend the value instead of append. The advantage is that we're still using a single processor (`set`) for this as it already handles random access to arrays.

**Comment by clintongormley** [comment]
`_last` to me means the last element, not the last element plus one.  I find it confusing.  I'd much rather have a simple clean dedicated processor.  Also, I don't think we need to support a prepend operation as values in an array in ES are essentially unordered.

**Comment by uboness** [comment]
> _last to me means the last element, not the last element plus one. I find it confusing. I'd much rather have a simple clean dedicated processor. 

fair enough. I personally feel we're starting to have a bit of a proliferation of processors with semi-overlapping goals. I'd much rather have a single processor that handles setting values. Now we have 2:

- one is to set single values on scalar **and** array fields, but if they don't exist it actually adds the value
- another one to add values to existing scalars and turn them into arrays, or add values to existing arrays, but if the field doesn't exist it adds the values into a single array.

that ^ I find a bit messy and confusing. Personally, I much rather have a single processor with simple rules that enable you to customize behaviour based on exceptions (and its defaults need to apply to +90% of the use cases.

> Also, I don't think we need to support a prepend operation as values in an array in ES are essentially unordered.

yes and now... in the source they're still ordered... and `set` does take order into account as it allows to set items in specific indices (a la `field1.array.3`). Though I agree... I've yet seen a real use case for this random access into arrays and as mentioned in other tickets... would love to get @talevy's opinion here.

**Comment by clintongormley** [comment]
> one is to set single values on scalar and array fields, but if they don't exist it actually adds the value
> another one to add values to existing scalars and turn them into arrays, or add values to existing arrays, but if the field doesn't exist it adds the values into a single value array.

No.  One (`set`) sets the value of a scalar variable, whether that variable is named `foo`, or `foo.bar`, or `foo.0`, or `foo.0.bar`.  The other (`push`) appends values to an array.   (It can also upgrade a scalar to an array if it needs to, although typically people will just use `push` and so the variable will be an array from the outset)

**Comment by martijnvg** [comment]
I'm kind of leaning towards having the `if_exists` option in the `set` processor instead of new processor, because now `set` processor only operates on one field and they the settings are specified. So it would look like this:

```
{
   "set" : {
       "field" : "_field",
       "value" : "_value", // this can also be an array or an object
       "if_exists" : "append|overwrite|skip"
   }
}
```

**Comment by javanna** [comment]
After discussing this internally, we went for adding a specific processor as described by Clint above:

>append the specified value(s) to an existing array
create an array with the specified value(s) if the field doesn't exist
convert an existing scalar to an array then append the specified value(s)

Opened #15577 for it.

**Comment by javanna** [comment]
Closed https://github.com/elastic/elasticsearch/commit/46f99a11a02db3ddedc86f92f13ad33d4d2acf7e
