### ISSUE TITLE
Circuit breaker to manage native script plugin memory usage

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#14325]
Not sure if this goes into #11070 or not. 
Users can pretty do anything in native script plugins (for various reasons), eg. building large arraylists, using java's regex pattern matcher, etc.. that can end up using a ton of memory.  It will be difficult for the request circuit breaker to estimate the amount of memory the native plugin will use and prevent it from running.  So it can be useful to provide a circuit breaker that allows for a memory cap that kills off queries that may have a native plugin using a lot of heap once it hits a user defined memory limit.

**Comment by dakrone** [comment]
@ppf2 I'm not sure this is feasible right now, with the way the circuit breakers work there is a requirement that requests for additional memory are funneled through a single point (where we can track usage and freeing), we already have this for fielddata and requests (ie BigArrays), but for native scripts, they are allocating memory directly on the JVM heap, so I don't think there is a hook we can use to increment/decrement memory for.

Native scripts could always use our circuit-breaking BigArrays instance, however, to generate new arrays of different types, in which case it will go through the requests breaker.

**Comment by clintongormley** [comment]
Once users are in native script territory, it's pretty much up to them what they do.  I don't think we can provide any limits here.  Closing

**Comment by ppf2** [comment]
Ok sounds good, thanks for the tip on BigArrays btw @dakrone !
