### ISSUE TITLE
unable to start elasticsearch on btrfs subvolume

### ISSUE THREAD

**Issue by briner** [elastic/elasticsearch#14337]
Hello,

When I start elasticsearch, the logs give:
```
Oct 28 09:17:18 lunielkes03 elasticsearch[1305]: {1.7.3}: Initialization Failed ...
Oct 28 09:17:18 lunielkes03 elasticsearch[1305]: - ElasticsearchIllegalStateException[Failed to obtain node lock, is the following location writable?: [/srv/elasticsearch/lunielkes]]
Oct 28 09:17:18 lunielkes03 elasticsearch[1305]: IOException[failed to obtain lock on /srv/elasticsearch/lunielkes/nodes/49]
Oct 28 09:17:18 lunielkes03 elasticsearch[1305]: IOException[Mount point not found]
Oct 28 09:17:18 lunielkes03 systemd[1]: elasticsearch.service: main process exited, code=exited, status=3/NOTIMPLEMENTED
Oct 28 09:17:18 lunielkes03 systemd[1]: Unit elasticsearch.service entered failed state.
```

It says that it cannot find the mountpoint. I was wondering if this was not related to the fact that:
 * / is mounted as a btrfs
 * /srv/elasticsarch is a subvolume of /
```
df -h /srv/elasticsearch/
Filesystem      Size  Used Avail Use% Mounted on
-               100G  2.4G   96G   3% /srv/elasticsearch
```
```
btrfs subvol list /
ID 260 gen 3050 top level 5 path srv/elasticsearch
ID 264 gen 3046 top level 260 path srv/elasticsearch/.snapshots
ID 265 gen 1147 top level 264 path srv/elasticsearch/.snapshots/1/snapshot
ID 270 gen 1634 top level 264 path srv/elasticsearch/.snapshots/6/snapshot
ID 271 gen 1731 top level 264 path srv/elasticsearch/.snapshots/7/snapshot
…
```

**Comment by clintongormley** [comment]
Hi @briner 

Did you manage to resolve this issue?  One thing that is curious is that you failed to obtain a lock on `/srv/elasticsearch/lunielkes/nodes/49` which implies that you were running 50 nodes on this box?

**Comment by briner** [comment]
Hi @clintongormley,
I did remove btrfs and use instead a ext4 filesystem.

**Comment by clintongormley** [comment]
Thanks @briner - not sure we have enough info to take this any further.  Closing

**Comment by torrancew** [comment]
FYI I was able to reproduce this issue precisely. As far as I know, I'm only running a single node on this box, via systemd. However, all attempts to run it, interactively, via the systemd unit, etc, result in precisely the error the OP received. In my case, /var is a BTRFS subvolume, and my data path is /var/lib/elasticsearch/data.

**Comment by torrancew** [comment]
I have found at least one workaround so far: mounting the subvolume directly. In my case, this I was able to mount the subvolume at exactly its original path, which is either **really** hacky or **really** elegant, depending on your perspective.

**Comment by TJC** [comment]
Can we re-open this? It's still an issue.
