### ISSUE TITLE
SearchContextMissingException: No search context found | Node Shutting down

### ISSUE THREAD

**Issue by piyushGoyal2** [elastic/elasticsearch#14330]
I know this issue has been raised lot many times. Referring  to issue #9726 where in @clintongormley mentioned that if one of the shard takes a longer time to respond, the search context gets expired on other shards which results in this exception. The reason for slower shard could be gc running on that particular node.

Firstly ours is not a scan and scroll request and this is a normal search request. 
We have a 3 node cluster and the exception stack trace was found on the master node where first SearchContextMissingException exception we got was for the master node itself and then within same second we got another exception for the 3rd node.

The master node printed this exception for 15-20 times and after that logs vanished. Somewhere nearly 12 hours the master got shut down with other nodes in the cluster reporting error "reason: zen-disco-master_failed".

The logs are currently in the debug mode and none of the node reported any kind of garbage collection. 
Its been nearly 2 years since we are using ES in production. This issue of node shutting down is very frequent in past one month.

**Comment by piyushGoyal2** [comment]
> this is

**Comment by s1monw** [comment]
> I know this issue has been raised lot many times. Referring to issue #9726 where in @clintongormley mentioned that if one of the shard takes a longer time to respond, the search context gets expired on other shards which results in this exception. The reason for slower shard could be gc running on that particular node.

we are talking about 5 minutes here I don't think this is what's happening here....


> The master node printed this exception for 15-20 times and after that logs vanished. Somewhere nearly 12 hours the master got shut down with other nodes in the cluster reporting error "reason: zen-disco-master_failed".

does the exception happen when the node is shutting down? Why is your node shutting down at all? Which version are you using and are you using the shutdown API anywhere? Is it possible that you are shutting down the cluster via the _shutdown API due to some developer using it locally?

**Comment by piyushGoyal2** [comment]
If it's not the above stated issue, then what could be the cause of the Exception. My Java client asks for lot of documents from a single query. And this query is fired after approximately 10 seconds each with different parameters. All I can see in my logs are these exceptions for different ID's that ES is trying to locate at the very same instance of time.
For the other questions of yours
does the exception happen when the node is shutting down?
The exception does not happen at the time of node shut down. In fact, there are actually no logs registered on the node which is getting shut down at the time of shutting down. Other nodes just mention that a node has been removed from cluster.

Why is your node shutting down at all? 
That is what a million dollar question for us why ES process running on the node gets itself killed when nothing is reported.

Which version are you using?
1.3.2
 you using the shutdown API anywhere? Is it possible that you are shutting down the cluster via the _shutdown API due to some developer using it locally?
No, we are not using shutdown API anywhere using the java API. It's a production instance where in we have blocked all these API through sense so no case of some developer shutting it down via _shutdown API. And always it's a random node which gets shutdown and not a specific node.

**Comment by s1monw** [comment]
> Which version are you using?
> 1.3.2

I strongly recommend to upgrade there are millions of bugs fixed since they. Please report back if the issue still exists on the latest release

**Comment by piyushGoyal2** [comment]
We are waiting for the stable release of 2.0. I guess it would be better for me to reopen the defect if it still persist on the newer version of ES. Thanks for the help @s1monw meanwhile . :)

**Comment by clintongormley** [comment]
@piyushGoyal2 you're in luck! https://www.elastic.co/downloads/past-releases/elasticsearch-2-0-0 :)

I'm going to close this for now, but please feel free to reopen if you see the same thing in 2.0

**Comment by OnlyGit** [comment]
The ElasticSearch version we use is 2.4.1, this issue also appears, but we don't use the scan or scroll request
