### ISSUE TITLE
XContent Builder doesn't check for null keys in maps. It should raise an exception

### ISSUE THREAD

**Issue by andrewvc** [elastic/elasticsearch#14346]
There should be a null check in https://github.com/elastic/elasticsearch/blob/148265bd164cd5a614cd020fb480d5974f523d81/core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java#L1237

It should probably raise a unique exception in this event. We encountered this in Logstash with some users running custom plugins.

Jackson also does not perform a null check, leading to a confusing NPE in some Jackson codes.

**Comment by clintongormley** [comment]
@javanna could you look at this one please

**Comment by andrewvc** [comment]
@javanna mind taking a look here?
