### ISSUE TITLE
Elasticsearch 2.0 fails to start after install Marvel 2.0

### ISSUE THREAD

**Issue by projx** [elastic/elasticsearch#14347]
Hi

I've got an odd issue, I'm running a vanilla install on Elasticsearch 2.0 pulled from the deb repository, it start after the initial installation, but then I installed Marvel and now seeing the following

[2015-10-28 23:11:13,025][INFO ][bootstrap                ] es.default.config is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed.

The only config file I have for Elasticsearch is /etc/elasticsearch/elasticsearch.yml, I've also tried uninstall Marvel and still seeing the same issue.

Cheers

**Comment by tlrx** [comment]
I can't reproduce the issue on Ubuntu 14.04, can you please tell us which OS you use?

Also, this message indicates that a deprecated setting `es.default.config` has been configured but elasticsearch 2.0 does not use it anymore and will refuse to start. Maybe a `grep` on your configuration files (/etc/elasticsearch/elasticsearch.yml /etc/default/elasticsearch)may help to locate where this setting comes from.

**Comment by vandinhchuong** [comment]
Hi, I have also the same issue, I use Ubuntu 15.04 and elasticsearch 2.0.
Another question: I don't see node.master & node.data in config/elasticsearch.yml, Can I use them in elasticsearch 2.0?

**Comment by clintongormley** [comment]
@vandinhchuong @projx It sounds like you have some legacy configuration files lying around.

> Another question: I don't see node.master & node.data in config/elasticsearch.yml, Can I use them in elasticsearch 2.0?

Yes.  We just reduced the config file to show only the most important bits.

**Comment by dcalixto** [comment]
i got the same issue:
es.config is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed.
after update to 2.0 version. i'm using homebrew

**Comment by ssoulless** [comment]
Hi I just can't start elastic search, I did a new fresh install with home-brew and when I try to start with the command:

```
elasticsearch --config=/usr/local/opt/elasticsearch/config/elasticsearch.yml
```
it show the message: es.config is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed.

Is there a quick fix I can use for just run elasticsearch?? I need it quickly help.

**Comment by tlrx** [comment]
You can use 
```
bin/elasticsearch --path.conf=/tmp/config/
```

where `--path.conf` refers to a directory that contains the `elasticsearch.yml` file and all other  logging,plugins etc configurations files.

With elasticsearch 1.x, it is possible to start elasticsearch and set the configuration *file* with parameters like `--config`, `-Des.config`, `-Delasticsearch.config` but it is also possible to configure the configuration *directory* with `--path.conf`, '-Des.path.conf` or `CONF_DIR`... It required a complex logic to manage with parameter takes the precedence and often leads to mistakes.

That's why it has been removed in 2.0. If you want to know more, you can take a look at #13772.


relates to #12712 and #12954 closes #5329 closes #13715

**Comment by ericsync** [comment]
Hi, we have a Elasticsearch (v1.7) cluster with  multiple nodes instances on each physical machines (3 box). We're under CentOS 7. Each ES instances had its own configuration file and environments variables. The conf file to use is specified in the service section of each instances startup script (/usr/lib/systemd/system/elasticsearch-node1.service, node2.service, etc.) by using the es.config parameter. We had to tweak a bit the systemd scripts but it does the job.

Now ,we are settings up a test environment to migrate under 2.0. How can we have multiple instances running on the same system with different conf files with 2.0 if we cannot specify a conf file? Does it mean that only one instance of ES is supported on a single box? At this point, it sounds that our migration is compromised. Thanks you for any help!

**Comment by rjernst** [comment]
> Does it mean that only one instance of ES is supported on a single box?

No, it means that you need to have separate config dirs for each instance.

**Comment by ericsync** [comment]
Thank you for the answer. It works.
I now have a /etc/elasticsearch-node{n} and /var/log/elasticsearch-node{n} directories for each instances.
Had to chown elasticsearch. on these directories and create a service startup script for each instances in /usr/lib/systemd/system, and tweak the service startup scripts settings to point on the right dir.
Trivial actually. 
Sorry for not thinking about using different directory. It's the end of the day, I'm getting tired I guess...

**Comment by rjernst** [comment]
@ericsync No problem!

**Comment by coreation** [comment]
@clintongormley my error was (after adding a log_daemon in the init.d file for elasticsearch) was that apt-get apparently had updated my elasticsearch from 2.3.2 to 2.3.3 which broke my delete-by-query plugin. At this point I'd think that "just doing an apt-get update" is kind of dangerous in this regard? What's the best way to handle updates in this situation?
