### ISSUE TITLE
Rename the `allow_primary` param of the _reroute API

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#14352]
The allocate command of the [_reroute API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-reroute.html?q=rero#cluster-reroute) takes an `allow_primary` parameter, which allows to force assign a primary shard. Using this parameter is dangerous as it will always result in data loss and the new shard will be created empty. This is well documented, but I still see people use it in an attempt to recover from a scenario where ES does not assign the primary to a node that *has* shard data on disk. The hope there is that that will trigger an allocation and the data will be salvaged. Sadly this means the data is deleted and any hope of salvaging it in another way (something *is* wrong with it) is lost.

I suggest we rename the parameter to something that makes the weight of the decision clearer. I can't come up with a concise name though. Some suggestions I had is 'assign_primary_as_empty`, `force_clean_primary` .

**Comment by clintongormley** [comment]
A suggestion made in FixItFriday was to remove the parameter entirely.  Essentially, you have lost a shard, and the only thing to do is to reindex.

Looking for opinions on this: when is it useful to assign an empty primary shard?

**Comment by bleskes** [comment]
If people find themselves in the unhappy place where a shard is red, they can't index into that index any more because of the missing shard. Even if you don't need to index into that index any more, the cluster status is red which means you have to disable monitoring of it until the index is deleted. The allow primary flag allows you to accept your loss and go back to normal. I see it used frequently after multi nodes failures where primary and replica are gone.

**Comment by dakrone** [comment]
What about `force_empty_primary` to indicate that the newly created shard will in fact be empty?

**Comment by nik9000** [comment]
`accept_data_loss`?

**Comment by bleskes** [comment]
I like the fact that `force_empty_primary` takes ownership of the implication and is clear about what's going to happen. `accept_data_loss` is more lenient and says I'm willing, if needed to run the risk. IMHO it's too subtle.

**Comment by clintongormley** [comment]
Closed by #15708
