### ISSUE TITLE
Bad git tag for version 2.0.0

### ISSUE THREAD

**Issue by raphz** [elastic/elasticsearch#14350]
it seems that the git tag for the v2.0.0 release is bad. After a git clone and checkout, the pom.xml indicates 2.0.0-SNAPSHOT as you can see in https://github.com/elastic/elasticsearch/blob/v2.0.0/pom.xml

Is the root directory has changed in this version ? This is bad because I have a build system using directly the sources from github.

**Comment by dakrone** [comment]
+1, it seems bad that we never actually had a commit on the 2.0 branch where the version was 2.0.0, it went from 2.0.0-SNAPSHOT to 2.0.01-SNAPSHOT.

@clintongormley I feel like this should be part of the release process, to actually have a "Release 2.0.0" commit that immediately precedes the tagging. Someone should always be able to do `git checkout v2.0.0` and build elasticsearch-2.0.0.tar.gz

**Comment by clintongormley** [comment]
These days we do an internal release candidate before putting the release live. While we're checking it, the (eg) 2.0 branch can move on.  I think what we can do is to add a commit with the new version and tag that, even though it will be one commit off the (eg) 2.0 branch.

**Comment by raphz** [comment]
There is always a release problem. The same thing has occured again with the version 2.1.0 the version is still 2.1.0-SNAPSHOT instead of 2.1.0.

**Comment by clintongormley** [comment]
Why is this a problem?  Part of the release process is to update the version to not include -SNAPSHOT (which happens in dev-tools/prepare_release_candidate.py).  So we're tagging the SHA that is used to build the internal release candidate which gets chosen to be made public.  

What we could do is to extract the code which changes the version into a standalone script.

**Comment by dadoonet** [comment]
It is a problem to me. If you want to build yourself a version you basically get the tagged version and build.
Here you end up getting a -SNAPSHOT version which is incorrect.

**Comment by clintongormley** [comment]
@dadoonet not if part of the build process is to do the version change.

**Comment by dadoonet** [comment]
As a end user, building a version is running mvn package. 

It generates here a wrong artifact (wrong name).

**Comment by sibay** [comment]
Any news?
I have the same problem. I wanted to build the source jar of version 2.0.0. 
```
git checkout vx.y.z
mvn clean source:jar install
```
works flawless for (eg) v1.7.3 but not for v2.0.0. I can remove the SNAPSHOT from the version number manually, but still don't know if i am building the 2.0 release or something "near" this release.

When i do a 
```
git checkout v2.0.0 
```
what is the next step to build the 2.0.0 version?

**Comment by clintongormley** [comment]
> but still don't know if i am building the 2.0 release or something "near" this release.

This is exactly the problem.  Even if you build from exactly the same commit (including the version changes) you cannot be sure that you are building Elasticsearch in the same way.  You may have some significant differences in your build environment which changes the end result.

We will not longer be committing the non -SNAPSHOT versions to the repository.  Dropping -SNAPSHOT is part of the release process only, and all it does is:

* update the POM's to remove -SNAPSHOT
* update Version.java to set the snapshot flag to false on the appropriate version
