### ISSUE TITLE
elasticsearch integration tests are not run in gradle

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#14361]
cd distribution
gradle check

does nothing... we need to get the rest tests going ASAP or the risk of breaking ES via refactorings in such a way we cannot recover is very high. 

plugin integ tests are working already, i will take a look at distribution/zip and see if i can figure out how to fix it as a first step. any help is appreciated.

**Comment by nik9000** [comment]
@rmuir - do you want some help looking at this? I assigned it to you because you said you were looking at it but if you haven't yet I can grab it.

**Comment by rmuir** [comment]
please!

**Comment by nik9000** [comment]
Ryan told me he'd grab this so I'm assigning it to him.
