### ISSUE TITLE
.gitignore needs to be updated for gradle

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#14364]
running gradle check dirties up my checkout with tons of stuff.

**Comment by rmuir** [comment]
I think we should just backport the gradle changes to all 2.x branches, whether or not they are using gradle. And the ignores used by maven need to be in master too (even though master does not use maven).

Otherwise, changing git branches is a disaster.

**Comment by nik9000** [comment]
> Otherwise, changing git branches is a disaster.

++++
