### ISSUE TITLE
bin/plugin install [url] unable to validate cert path for local https repos

### ISSUE THREAD

**Issue by robertsmarty** [elastic/elasticsearch#14373]
Hi,

Our deployment automation has an internal repo for all elasticsearch related artifacts. I'm currently receiving a "unable to find valid certification path to requested target" when accessing this internal repo over https.

Is there any way to configure a trust store for plugin downloads?

**Comment by robertsmarty** [comment]
I'm using elasticsearch 2.0.0

**Comment by s1monw** [comment]
can you try passing the truststore as a cmd argument like this:
```
-Djavax.net.ssl.trustStore=path/to/trustStore.jks
```

I didn't try this out though just an idea

**Comment by robertsmarty** [comment]
Works perfectly!

**Comment by s1monw** [comment]
awesome! @clintongormley should we add this to some documentation

**Comment by clintongormley** [comment]
@s1monw added in https://github.com/elastic/elasticsearch/commit/fe473ed24ed240f2edbe7c71b3f3b5e8e5f58f7d

**Comment by s1monw** [comment]
awesome thanks @clintongormley
