### ISSUE TITLE
startup scripts should pass jvm -Djava.io.tmpdir=$ES_HOME/tmp

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#14372]
Today we use the system tempdir, but this can cause several problems (e.g. https://discuss.elastic.co/t/elasticsearch-2-0-warning-jna-is-not-available/33320/1). It would also just be better in general as far as isolating the elasticsearch process.

Instead we should just set our own: scripts should also create it, if it does not exist. It should not and cannot be configurable: it needs to be passed to the jvm initially and not set after-the-fact. Otherwise we end out with a mess (e.g. 2 temp directories to contend with).

**Comment by nik9000** [comment]
> Instead we should just set our own: scripts should also create it, if it does not exist. It should not and cannot be configurable: it needs to be passed to the jvm initially and not set after-the-fact. Otherwise we end out with a mess (e.g. 2 temp directories to contend with).

I suspect there are plenty of distros that'd be upset if we didn't let them override that to dump it where they want it. If its just something that defaults to $ESHOME/tmp but can be changed with a shell variable that'd be fine.

**Comment by rmuir** [comment]
Yeah: shell variable is fine. Its more that it wont really work as a e.g. typical elasticsearch.yml configuration option. 

We need to pass java.io.tmpdir into the JVM up front, in JAVA_OPTS, otherwise it only works "partially" and we will be stuck with two temporary directories, which is bad.

**Comment by nellicus** [comment]
another user hit this today

**Comment by rmuir** [comment]
Thats's ok: Like i said its essentially unfixable until we decide to cleanup how elasticsearch configuration works.

**Comment by jasontedor** [comment]
We are not going to set the temporary directory to ES_HOME/tmp with our default packaging as that is not sufficiently private. With #27609 a user can set `ES_TMPDIR` to override `java.io.tmpdir` and we default this to a private temporary directory.
