### ISSUE TITLE
_cat/indices: JSON output

### ISSUE THREAD

**Issue by j0hnsmith** [elastic/elasticsearch#14380]
The `_cat/indices` api seems to only output plain text, JSON output would be nice, eg instead of

```
health status index                       pri rep docs.count docs.deleted store.size pri.store.size 
yellow open   my_index_1               5   1      10179            0      8.4mb          8.4mb 
yellow open   my_index_2               5   1       5111          344      5.1mb          5.1mb
```
it would be nice to get
```
[  
    {  
        "health": "yellow",
        "status": "open",
        "index": "my_index_1",
        "pri": 5,
        "rep": 1,
        "docs_count": 10179,
        "docs_deleted": 0,
        "store_size": "8.4mb",
        "pri_store_size": "8.4mb"
    },
    {  
        "health": "yellow",
        "status": "open",
        "index": "my_index_2",
        "pri": 5,
        "rep": 1,
        "docs_count": 5111,
        "docs_deleted": 344,
        "store_size": "5.1mb",
        "pri_store_size": "5.1mb"
    }
]
```

**Comment by ywelsch** [comment]
Try adding `?format=json` , for example `_cat/indices?format=json`.

@clintongormley This should probably be documented.

**Comment by j0hnsmith** [comment]
Hmm, `?format=json` works (thanks for letting me know). 

My original request was made with with `Accept: application/json`, this returns `Content-Type: text/plain; charset=UTF-8`, is there a reason why the `Accept` header is ignored?

**Comment by ywelsch** [comment]
Yes, the Accept header is currently ignored, which is a bug.
There is an open issue for that (#14195).
