### ISSUE TITLE
Cluster doesn't scale beyond ~400 requests/sec

### ISSUE THREAD

**Issue by johnament** [elastic/elasticsearch#14381]
I raised a question on the forums, didn't get much input, so raising an issue to see if it catches any input from others.

I have a 3 node cluster, 8gb each.  It maxes out at ~400 requests per second, regardless of what query we give it. We add a 4th node, still it maxes out in the same area (I think we get an extra 20 req/s tops).

Is this normal? Any settings we can look at to tweak this further? We're on ES 1.5.2.

**Comment by clintongormley** [comment]
Hi @johnament 

This is definitely a question for the forums.  Please continue the conversation there, perhaps by providing more info.

**Comment by johnament** [comment]
Please do let me know what more info I could provide, as best as we can tell with a default install this issue is happening: https://discuss.elastic.co/t/query-not-scaling/33032
