### ISSUE TITLE
Script_field returns different array value in the 2.0 version

### ISSUE THREAD

**Issue by mediaon** [elastic/elasticsearch#14397]
This behaviour is reproducible in v1.7.3 and 2.0.0.
Request:
    GET /my_index/object/_search
    {
      "script_fields": {
        "last_updates": {
          "script": "list=[];list.push(key:'test');list"
        }
      }
    }

Response:
1.7.3
  "fields": { "last_updates": [[ {"key": "test"}]]}
2.0
  "fields": {"last_updates": [ {"key": "test"}]}

**Comment by clintongormley** [comment]
This looks to me like something that changed in Groovy, but leaving it open for further comments.

**Comment by clintongormley** [comment]
No further comments. Closing
