### ISSUE TITLE
Find file containing the keyword

### ISSUE THREAD

**Issue by jst2cu** [elastic/elasticsearch#14395]
Is there any module in elasticsearch to find the file containing the search keyword and get the contents of the file with the keyword

**Comment by ksujeet** [comment]
Take a look at this, 
https://www.elastic.co/guide/en/elasticsearch/reference/1.4/mapping-attachment-type.html
https://github.com/elastic/elasticsearch-mapper-attachments

**Comment by dadoonet** [comment]
+1 and ask questions on discuss.elastic.co
