### ISSUE TITLE
Expose ClusterInfo in nodes' stats

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#14405]
Currently the only way to diagnose/debug issues with the gathered cluster info (disk and shard sizes) is to turn on verbose logging for the `cluster` namespace.

We should expose this in the nodes stats API so people can see the amount of free/used disk that is measured by Elasticsearch.

**Comment by clintongormley** [comment]
Are you still planning on exposing disk usage stats somewhere?

**Comment by dakrone** [comment]
@clintongormley I'm on the fence about this, on one hand, it'd be nice to have whatever the calculated disk usage is available in the cluster state, on the other hand, I'm not sure it's worth creating a new cluster state every 30 seconds due to the disk changing every time. I wonder if this is less necessary now that the cluster allocation explain API will hopefully give more information about disk usage when a shard fails to be assigned.

What do you think? Is it worth trying to add this even though it will cause new cluster states to be sent every thirty seconds?

**Comment by ywelsch** [comment]
@dakrone Why is exposing disk usage and shard size related to cluster state? `/_nodes/stats` just queries each node directly to gather stats?

**Comment by dakrone** [comment]
@ywelsch this would be exposing the master node's idea of the disk state by adding the `InternalClusterInfoService`'s `ClusterInfo` to the state, not the actual disk used (which you are right, could be gathered from the nodes directly)

**Comment by ywelsch** [comment]
@dakrone If we're interested in what the master node thinks, we can use an action that fetches it from the master (`TransportMasterNodeAction`). Still doesn't require to add it to the cluster state ;-)

**Comment by bleskes** [comment]
@ywelsch @dakrone I'm a bit confused - the ticket isn't about adding the disk usage to the cluster state but rather expose them through an API? I'm -1 on adding the to the cluster state internals - they have nothing to do with it and it will be indeed a shame to publish it for nothing.

Since we only use those for allocations, how about adding a flag/section to the allocation explain API to return the current cluster info in it's entirety?

**Comment by dakrone** [comment]
> I'm a bit confused - the ticket isn't about adding the disk usage to the cluster state but rather expose them through an API? I'm -1 on adding the to the cluster state internals

Sorry, there's some history here that wasn't communicated clearly, this comes from things like https://github.com/elastic/elasticsearch/pull/11643 where the cluster info was available to all the nodes as part of the state, which would allow them to make judgments about which path to put a shard on, or shard weight, etc. For what it's worth I'm -1 on adding it to the cluster state also (which is why that PR was closed and not merged).

> Since we only use those for allocations, how about adding a flag/section to the allocation explain API to return the current cluster info in it's entirety?

This does sound reasonable to me and would be very easy to do, what do you think @ywelsch?

**Comment by ywelsch** [comment]
>> Since we only use those for allocations, how about adding a flag/section to the allocation explain API to return the current cluster info in it's entirety?

> This does sound reasonable to me and would be very easy to do, what do you think @ywelsch?

sounds good to me!
