### ISSUE TITLE
/_field_stats returns date values as strings

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch#14404]
The `max_value` and `min_value` provided by the `/_field_stats` api currently provide strings values for date fields rather than milliseconds from epoch.

This feels like a bug to me, I expect them to resemble the results of a `max` or `min` aggregation:

`/_field_stats`
```js
{
  // ...
  max_value: "2015-10-29T23:58:20.015Z"
  // ...
}
```

max aggregation:
```js
{
  value: 1446163100015
  value_as_string: "2015-10-29T23:58:20.015Z"
}
```

**Comment by rashidkpc** [comment]
This is really important for post request sorting. ISO8601 will sort fine, but users that have alternative formats may find their strings don't sort as expected

**Comment by martijnvg** [comment]
@spalger @rashidkpc Right, the data format being returned depends on the configuration in the date field in the mapping, but that isn't good for sorting, so lets change the format slightly to also include the milliseconds from epoch.
