### ISSUE TITLE
ES 2.0.0. Marvel not found

### ISSUE THREAD

**Issue by marcinkubica** [elastic/elasticsearch#14417]
Yes there was #14349 for ES 2.0.0-rc1 however it's identical for ES 2.0.0

# curl localhost:9200
{
  "name" : "Deadpool",
  "cluster_name" : "kibanadev",
  "version" : {
    "number" : "2.0.0",
    "build_hash" : "de54438d6af8f9340d50c5c786151783ce7d6be5",
    "build_timestamp" : "2015-10-22T08:09:48Z",
    "build_snapshot" : false,
    "lucene_version" : "5.2.1"
  },
  "tagline" : "You Know, for Search"
}

[root@vm000530 bin]# ./plugin install marvel --verbose
-> Installing marvel...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/marvel/2.0.0/marvel-2.0.0.zip ...
Failed: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/marvel/2.0.0/marvel-2.0.0.zip]; nested: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/marvel/2.0.0/marvel-2.0.0.zip];

**Comment by tlrx** [comment]
You should run:
```
bin/plugin install license
bin/plugin install marvel-agent
```

The documentation may help you: https://www.elastic.co/guide/en/marvel/current/getting-started.html

**Comment by marcinkubica** [comment]
Cheers mate.

**Comment by efr4k** [comment]
Maybe update official docs?
