### ISSUE TITLE
Deduplicate search sections parsing code

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#14413]
When we moved query parsing on the coordinating node (see #10217), we added a new `SearchSourceBuilder#fromXContent` method that given an `XContentParser` and the current `QueryParseContext` parses and creates a new `SearchSourceBuilder` object. The parse code ends up duplicating what we already have in our `SearchParseElement` classes. We made a choice not to refactor these initially as they depend on `SearchContext` and there are still apis that use them to parse lucene queries straight-away and set them to the search context rather than going through our intermediate query representation.

This solution can only be temporary though, as we are currently duplicating parsing code. What we should do ideally instead, is move over parsing code to the new solution (either `SearchSourceBuilder#fromXContent` or an updated version of `SearchParseElement` that doesn't depend on `SearchContext`) and get rid of the previous parsing code. I realize how this becomes hard to do given that we have not moved yet all of the search sections over. Maybe we should wait till the search refactoring is completed, but after that  we should clean this up and have only one way to parse search sections, with code in one single place, otherwise it becomes hard to understand how each api parses search sections.

**Comment by clintongormley** [comment]
@javanna @cbuescher does this still need to happen?

**Comment by javanna** [comment]
I don't know anymore, better ask @colings86  :)

**Comment by colings86** [comment]
The `ParseElement` classes should be obselete now as all the search request parsing happens on the coordinating node and doesn't use `ParseElement` so we should now be able to remove `ParseElement` and all its subclasses from the codebase.

**Comment by javanna** [comment]
> The ParseElement classes should be obselete now as all the search request parsing happens on the coordinating node and doesn't use ParseElement so we should now be able to remove ParseElement and all its subclasses from the codebase.

I double checked and I think we are not using `SearchParseElement` ourselves as each of our search sections has its own `fromXContent` method now, but plugins still need the interface to provide their parsing code for the ext section. We may want to revise a bit this code though and make it clear that it's needed only for plugins.

**Comment by colings86** [comment]
Yep, the `SearchParseElement` is now only used for plugins which add a custom fetch sub phase. We should work on a way to replace this with the builder system we have for the rest of the search request. When I looked at doing that before I think it got tricky but unfortunately I don't remember what made it tricky

**Comment by javanna** [comment]
I opened #20382 to clean things up a bit. Closing this one then.
