### ISSUE TITLE
Elasticsearch not accessed via publicIP:9200

### ISSUE THREAD

**Issue by harpreetsb** [elastic/elasticsearch#14422]
hi, we have setup new server, the version 1.7.2 was working perfect and was accessible from public IP address as well.
After upgrading to  version 2.0 i can do
curl -X GET 'http://localhost:9200' vai SSH but 
http://<public-IP>:9200 gives me "unable to connect"

**Comment by dadoonet** [comment]
Elasticsearch now binds on localhost so you can only access it from the local machine.

See network.host settings.

**Comment by harpreetsb** [comment]
could you guide me in specific direction, Links.

**Comment by dadoonet** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/modules-network.html

**Comment by harpreetsb** [comment]
can you tell me the specific settings. i did
'network.host : PUBLIC IP'
but did not work

**Comment by dadoonet** [comment]
What did you do exactly? I'd suggest that you open a thread on discuss.elastic.co with all details and logs.

**Comment by harpreetsb** [comment]
solution found
```
network.host : 0.0.0.0
```
