### ISSUE TITLE
Update node.(other) docs

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#14429]
[Here](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/modules-node.html) we only list `node.data` when there is `.master` as well.

We should reflect this in the docs as a I've seen a few people ask about this just recently.

**Comment by arinto** [comment]
+1. Original discussion thread is [here](https://discuss.elastic.co/t/dedicated-master-nodes-in-elasticsearch-2-0/33485).
