### ISSUE TITLE
Starting checked out elasticsearch cluster

### ISSUE THREAD

**Issue by andrejserafim** [elastic/elasticsearch#14423]
According to https://github.com/elastic/elasticsearch/blob/master/TESTING.asciidoc it can be done by running [run.sh](../blob/master/run.sh) or [run.bat](../blob/master/run.bat), but those guys use mvn.

I see there's been a push to move from maven: #13930. And there's an item there to create a gradle task for this.

I'm new to gradle and the build of elasticsearch, but could folks explain how they startup a node for a little poking around locally - maybe I can script it up. I'm trying to start a node run a few REST calls to get the output for examples in the docs.

My workaround has been to run 
    gradle assemble

Then extract distribution/tar/build/distributions/elasticsearch-3.0.0-SNAPSHOT.tgz and run ./elasticsearch

Thanks

**Comment by nik9000** [comment]
We should certainly fix run.sh and run.bat but in what you are doing is
fine.

If you import the project in eclipse you should be able to use the run
configuration sitting in dev-tools. It night also be broken by the move to
gradle, as that was just a few days ago and we had a bazillion things to
make work and certainly missed a few, like run.sh.

Untaring the distribution is the most real thing you can do. In prod you
are more likely to use the deb or rpm but they don't differ much from the
tar save for startup and permissions things.
