### ISSUE TITLE
Feature request: Update nested objects directly with the HTTP API

### ISSUE THREAD

**Issue by giovannibonetti** [elastic/elasticsearch#14426]
I have searched during some time for a practical way to update nested objects without having to touch the parent ones. The best I could find so far in the official docs was this link that explains how to [use scripts to make partial updates](https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-updates.html#_using_scripts_to_make_partial_updates). This approach has a few downsides:
- You have to enable scripting, which sometimes isn't an option if you are relying on a (cheap) hosted solution (my case), since shared environments aren't reliable enough;
- You have to learn Groovy, which is not so similar to, say, JS, when you are doing something that involves more than a ternary operator.

On the other hand, I think most web developers are so used to REST APIs that something like this would be common sense:
PUT .../index_name/parent_type/123/nested_type/456
- If both the parent object (with ID 123) and the nested object (with ID 456) exist, update the nested object with the request body;
- If only the parent object (with ID 123) exists, insert the nested object (with ID 456) in the array with the other nested objects (in the parent document);
- Otherwise, if the parent object doesn't exist, raise an error

So, what do you think of the idea? Has anyone else proposed something like that before? I would love to contribute myself, but unfortunately Java is not my thing... Do you accept PRs in Scala or Kotlin?

**Comment by clintongormley** [comment]
Hi @giovannibonetti 

Unfortunately, your proposal would be too limited to be generically useful.  We've had discussion about something like this before in #7030, but it hasn't made any progress yet.  Btw, you can store scripts as files in your config directory and use those without enabling dynamic/inline scripting (and going from JS to groovy is not too hard :) )
