### ISSUE TITLE
check-invalid-patterns in 2.x maven builds should ignore build/

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#14438]
Otherwise switching git branches from master (on gradle) is very annoying, since some ant build reports in build/reports will have problems.

I'm not sure this task should really be running on `${basedir}` anyway: at least in a blanket way and then excluding build files and stuff. Maybe it is enough to only explicitly run on a few things like `src` and `*.xml` to ensure there are not any nocommits. But otherwise we should add `build/` to the ignore patterns.

**Comment by clintongormley** [comment]
Closed by #14492
