### ISSUE TITLE
[DOCS] Possible typo Apache Spark vs. Apache Storm

### ISSUE THREAD

**Issue by lukas-vlcek** [elastic/elasticsearch#14439]
May be it is just a typo, but why the first paragraph here refers to Apache Spark while it is inside Apache Storm part?
https://www.elastic.co/guide/en/elasticsearch/hadoop/current/requirements.html#requirements-storm

**Comment by girirajsharma** [comment]
The following PR https://github.com/elastic/elasticsearch-hadoop/pull/588 fixes above issue.

**Comment by clintongormley** [comment]
This issue was moved to elastic/elasticsearch-hadoop#600
