### ISSUE TITLE
Limit the maximum queue_size for fixed thread pools?

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#14448]
Dynamically adjustable `queue_size`s for thread pools can in general be a useful feature for users to tune depending on their cluster utilization. However, as `queue_size` tends to `Integer.MAX_VALUE`, the value of this turns negative. So perhaps we should set a upper bound on `queue_size` beyond which it can not be set?

Relates #11511, relates #14367 (cf. [comment](https://github.com/elastic/elasticsearch/pull/14367#discussion_r43549359) from @dakrone)

**Comment by bleskes** [comment]
I thinks makes sense.

**Comment by s1monw** [comment]
there is another issue I closed lately related to this: https://github.com/elastic/elasticsearch/issues/3890
I think we can do much better by computing some sensible limit based on the throughput and make that the default?

**Comment by s1monw** [comment]
but hey we maybe should do both.... Lets just do 1024 and be done with it

**Comment by ppf2** [comment]
+1 on at least setting an upper bound.  have seen quite a few cases in the field where users have set queue sizes to unlimited or some ridiculous number like 1 million+

**Comment by nik9000** [comment]
If you set the queue size to less than 0 on a fixed thread pool you'll get an unbounded queue.

**Comment by jasontedor** [comment]
Closed in favor of #18613
