### ISSUE TITLE
DOCFIX:  Shield reference docs list all privileges, but do not define all of them

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#14446]
https://www.elastic.co/guide/en/shield/current/reference.html

Some items, such as 'exists' are listed as part of 'manage' and are in the complete list of privileges, but do not have specific definitions of their own.  All listed privileges should have definitions as well to avoid ambiguity.

**Comment by clintongormley** [comment]
@jaymode could you take a look at this?

**Comment by clintongormley** [comment]
This should be on the shield repo
