### ISSUE TITLE
ElasticSearch 2.0 install

### ISSUE THREAD

**Issue by langjai0** [elastic/elasticsearch#14458]
Anyone getting problems installing the new elastic search 2.0?

I'm getting the "Exception in thread "main" java.lang.Runtimeexception: don't run as root"

**Comment by dadoonet** [comment]
Sounds like you are trying to run elasticsearch as root user which is forbidden, security wise?

**Comment by mingfang** [comment]
How do I run elasticsearch as root?
I understand the security considerations.

**Comment by dadoonet** [comment]
You can't run elasticsearch as root.

**Comment by mingfang** [comment]
Why don't you let me decide what I can and can not do.

**Comment by dadoonet** [comment]
Why do you want to run elasticsearch as root?

**Comment by mingfang** [comment]
That's not the point.
If I wanted to run as root then I should be able to.

**Comment by dadoonet** [comment]
That's exactly the point. If you have a problem, we will be happy to understand it and solve it...
We try to protect our users from external attacks. We don't allow to run a query for example with size=1000000000 because you will blow up your memory and cluster.

**Comment by mingfang** [comment]
I do have a problem with you telling me what I can and can not do.

**Comment by rmuir** [comment]
The issue is, although we work hard to improve defaults and security, there are still some very serious traps (like dynamic scripting). 

So its very important that we have at least some basic facilities of the operating system: different user, filesystem permissions, etc.

**Comment by sasauz** [comment]
I would like to start elasticsearch with Linux as autostart and it's means that the elasticseach should be start as root. or? You also write on your site (https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-service.html) that we should do something like this for autostart:

sudo /sbin/chkconfig --add elasticsearch
sudo service elasticsearch start

in this case it will be start as root! What should I do in this case?

**Comment by jasontedor** [comment]
> in this case it will be start as root!

@sasauz You need superuser privileges so that the process can be started and daemonized under the `elasticsearch` user, but the service is in fact started under the `elasticsearch` user which you can see from

```
    daemon --user $ES_USER...
```

or

```
   start-stop-daemon -d $ES_HOME --start -b --user "$ES_USER -c "$ES_USER"...
```

depending on your system (where in both cases, the default is for `ES_USER` to be set to `elasticsearch`).

**Comment by nik9000** [comment]
For the most part you should be able to use the deb or rpm distribution if
you want fancy service things. If you can't use those it might be simpler
to see what they do and clone it then to rebuild from first principles.

**Comment by sasauz** [comment]
@jasontedor and @nik9000 Thank you!
