### ISSUE TITLE
Elasticsearch not accessible after moving from 1.4.4 to 2.0.0

### ISSUE THREAD

**Issue by nithyanv** [elastic/elasticsearch#14465]
Hi,

I removed  elasticsearch 1.4.4. using rpm. (It was installed using rpm package)

> $rpm -e elasticsearch-1.4.4-1.noarch

Then installed 2.0.0 using rpm again and started it as below. 

> $rpm -ivh elasticsearch-2.0.0.rpm
> $sudo chkconfig --add elasticsearch
> $sudo service elasticsearch start

Logs show no error or exceptions

> [2015-11-03 12:12:47,903][INFO ][node                     ] [Atalon] version[2.0.0], pid[4194], build[de54438/2015-10-22T08:09:48Z]
> [2015-11-03 12:12:47,916][INFO ][node                     ] [Atalon] initializing ...
> [2015-11-03 12:12:48,315][INFO ][plugins                  ] [Atalon] loaded [], sites []
[2015-11-03 12:12:48,781][INFO ][env                      ] [Atalon] using [1] data paths, mounts [[/ (/dev/mapper/vg01-LogVol00)]], net usable_space [37.2gb], net total_space [90.6gb], spins? [possibly], types [ext4]
> [2015-11-03 12:12:59,073][INFO ][node                     ] [Atalon] initialized
> [2015-11-03 12:12:59,073][INFO ][node                     ] [Atalon] starting ...
> [2015-11-03 12:12:59,474][INFO ][transport                ] [Atalon] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}, {[::1]:9300}
> [2015-11-03 12:12:59,567][INFO ][discovery                ] [Atalon] elasticsearch/RNomvPO4TyyGpRdInlKZ7A
> [2015-11-03 12:13:02,804][INFO ][cluster.service          ] [Atalon] new_master {Atalon}{RNomvPO4TyyGpRdInlKZ7A}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
> [2015-11-03 12:13:02,931][INFO ][gateway                  ] [Atalon] recovered [0] indices into cluster_state
> [2015-11-03 12:13:02,952][INFO ][http                     ] [Atalon] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}
> [2015-11-03 12:13:02,953][INFO ][node                     ] [Atalon] started

However, the curl command gives no response from elasticsearch. 

> curl -XGET http://localhost:9200

> <HTML><HEAD><TITLE>Network Error</TITLE></HEAD>
> <BODY>
> <FONT face="Helvetica"><big><strong></strong></big><BR></FONT>
> <blockquote>
> <TABLE border=0 cellPadding=1 width="80%">
> <TR><TD>
> <FONT face="Helvetica"><big>Network Error (dns_unresolved_hostname)</big><BR><BR></FONT>
> </TD></TR><TR><TD><FONT face="Helvetica">Your requested host "localhost" could not be resolved by DNS.</FONT></TD></TR><TR><TD>
> <FONT face="Helvetica"></FONT></TD></TR><TR><TD><FONT face="Helvetica" SIZE=2><BR>For assistance, contact your network support team.</FONT></TD></TR>
> </TABLE>
> </blockquote>
> </FONT>
> </BODY></HTML>

**Comment by dadoonet** [comment]
Try `curl -XGET http://127.0.0.1:9200`

And join us on discuss.elastic.co for questions.

**Comment by nithyanv** [comment]
I tried curl -XGET http://127.0.0.1:9200 and got below 

><HTML>
><HEAD><TITLE>Redirection</TITLE></HEAD>
><BODY><H1>Redirect</H1></BODY>

**Comment by nithyanv** [comment]
There are no changes in the log. No connection seems to be getting established there.

**Comment by dadoonet** [comment]
Try with `curl -XGET http://127.0.0.1:9200/`

**Comment by nithyanv** [comment]
@dadoonet Still the same :-(

**Comment by dadoonet** [comment]
Any chance elasticsearch is not running anymore?
May be you have firewall weird setup?

**Comment by nithyanv** [comment]
I checked that 
>service elasticsearch status
>elasticsearch (pid  4194) is running...

Will check with my team about any firewall issue.

**Comment by dadoonet** [comment]
There is absolutely no reason if elasticsearch is running and if elasticsearch tells `publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}, {[::1]:9200}` that nothing is answering at http://127.0.0.1:9200 (you can run that in a browser BTW)

**Comment by nithyanv** [comment]
I know! This is so strange. It is running fine as a test, in a local windows installation. Already tried through browser.

**Comment by nithyanv** [comment]
We have set up ETC hosts as well. 
>127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
>::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

**Comment by bondalapati** [comment]
Any fix to this issue? I am running into a similar problem.
