### ISSUE TITLE
Wildcard search for field does not return all fields if store:false

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#14470]
If fields are not stored (`"store":false` in mapping), it is still possible to query fields using the `"fields":[ "foo", "bar" ]` query syntax as the fields are taken from the `_source`.
If however you use a wildcard : `"fields": [ "*" ]` then no fields are returned.

**Comment by tlrx** [comment]
I think we should update the documentation to make it more explicit that `"fields":["*"]` only returns stored fields and won't extract all fields (stored or unstored) from `_source`.
