### ISSUE TITLE
Non java bin plugins on 2.0

### ISSUE THREAD

**Issue by jjfalling** [elastic/elasticsearch#14478]
The existing support plugin is a bin plugin in bash and powershell. It the plugin-descriptor.properties allows for either site plugins (which require a _site folder) or java plugins with need to provide classes to load. So it appears this breaks the ability to use non-java pin plugins.

**Comment by rmuir** [comment]
Is there really a fourth type of plugin (we already have site, jvm, site+jvm)?

or can maybe this plugin just have a simple site folder that has a single file that says "please use the shell scripts for diagnostic functionality"

**Comment by jjfalling** [comment]
The _site folder would be a potential workaround. In the long term are
moving away from having the diagnostics tool as a plugin so this won't
affect us. However I was under the impression that we intended to have
a bin type of plugin in 1.x.

**Comment by rmuir** [comment]
I am not sure where that impression came from, but i can tell you that adding that folder is 1000x safer and easier than adding another plugin type and complicating all those codepaths.

We already have unnecessary types to support today (e.g. jvm+site) and I don't think we need add any more for any reason.

**Comment by jjfalling** [comment]
Sounds reasonable.
