### ISSUE TITLE
Delete only a particular field and value

### ISSUE THREAD

**Issue by 208rishabh** [elastic/elasticsearch#14480]
Hi,

I want to delete only one particular field and value in elasticsearch using elastic4s library. However, all I see everywhere is different mechanisms to delete the whole document. Can anyone help? is this supported?

**Comment by jpountz** [comment]
This can be achieved by running a scripted update. It would look something like this:

```
curl -XPOST 'localhost:9200/index/type/id/_update' -d '{
    "script" : "ctx._source.remove(\"name_of_the_field_to_remove\")"
}' 
```

See https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html for more information.
