### ISSUE TITLE
Elasticsearch 2.0 tar.gz Not in gzip format

### ISSUE THREAD

**Issue by dgriff20** [elastic/elasticsearch#14487]
Hi,

I just downloaded 2.0.0 as per the instructions in Elasticsearch Reference [2.0] » Getting Started » Installation. When I go to unzip the file with tar -xvf elasticsearch-2.0.0-rc1.tar.gz, I get the response "tar: This does not look like a tar archive

gzip: stdin: got in gzip format
tar: Child returned status 1
tar: Error is not recoverable:exiting now"

Any idea what might be going wrong?

**Comment by reflection** [comment]
I think you might be missing a 'z' option:
```tar -xzvf elasticsearch-2.0.0-rc1.tar.gz```

**Comment by nik9000** [comment]
The link over on https://www.elastic.co/guide/en/elasticsearch/reference/2.0/_installation.html is wrong.

**Comment by dgriff20** [comment]
reflection -  Tried it with the z added and unfortunately, I receive the same error.

**Comment by dgriff20** [comment]
nik9000 - Do you know the correct link? The one provided did download an elasticsearch-2.0.0-rc1.tar.gz file.

**Comment by nik9000** [comment]
[This](https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.0.0/elasticsearch-2.0.0.tar.gz) should do. What does the file you have look like? I tried it using the link there and it downloaded a little xml file.

**Comment by dgriff20** [comment]
I'll give that version a shot. Closer inspection shows the same for me. Seems like an XML renamed to tar.gz. Strange. Thanks for the help!
