### ISSUE TITLE
Refuse to load fields from _source when using the `fields` option

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#14489]
Spin-off from #14474. The `fields` option is intended to load stored fields. However it will try to load these fields from the source if they are not stored. This causes confusion because then eg. wildcards don't work.

We should deprecate the ability to load fields from _source and remove it in 3.0.

**Comment by bleskes** [comment]
+1

**Comment by nik9000** [comment]
> We should deprecate the ability to load fields from _source and remove it in 3.0.

It was a great backwards compatibility step when going from 0.90.x to 1.x but I agree, it can go in 3.0.
