### ISSUE TITLE
v2.0.0 security manager with groovy scripts

### ISSUE THREAD

**Issue by federico-peralta-schaffner** [elastic/elasticsearch#14488]
Please see this question:
http://stackoverflow.com/questions/33503890/elasticsearch-2-0-0-security-manager-with-groovy-script#

When using `JsonOutput.toJson()` in an update (inside an inline groovy script), I'm getting a security exception:

    Caused by: java.security.AccessControlException: access denied ("java.util.PropertyPermission" "groovy.json.faststringutils.write.to.final.fields" "read")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1294)
        at java.lang.System.getProperty(System.java:753)
        at groovy.json.internal.FastStringUtils.<clinit>(FastStringUtils.java:37)
        ... 42 more

The problem is that the new 2.0.0 security manager does not allow to read the `groovy.json.faststringutils.write.to.final.fields` system property that is used by Groovy's `FastStringUtils` class in its line 37.

I don't want to change or disable the new security manager, but I do need to serialize an object to a JSON string inside my groovy script.

NOT: I've set the following options to allow inline groovy scripting:

    script.inline: on 
    script.indexed: on

To reproduce, just invoke `JsonOutput.toJson(someObject)` inside an inline groovy script, such as in an update command.

**Comment by rmuir** [comment]
on the side: you don't want to enable write to final fields (see https://github.com/elastic/elasticsearch/issues/8175)

> but I do need to serialize an object to a JSON string inside my groovy script.

Can you elaborate more on this? It seems strange for a script to have to do this serialization.

**Comment by federico-peralta-schaffner** [comment]
@rmuir Thanks for the prompt reply!

I don't want to enable writes to final fields. The problem is that the `FastStringUtils` Groovy class attempts to check the `groovy.json.faststringutils.write.to.final.fields` system property (this is Groovy code, not mine, please check `FastStringUtils` line 37). There the security error occurs, since the current security policy is not allowing to read system properties, whatever its value is. My point is that this seems to be a bug, since any Groovy class that internally uses the `FastStringUtils` class fails with a security exception (such as `JsonOutput`, which I'm using in my script).

>> but I do need to serialize an object to a JSON string inside my groovy script

>Can you elaborate more on this? It seems strange for a script to have to do this serialization.

Sure, I have an array of objects in my document and my script serializes this array to a string, which is then stored in a new field of type `string`. But this is required as per the functional specifications. Anyways, even if I could change the requirements or implement some work-around, it wouldn't take too long before someone else attempts to indirectly use the Grovvy's `FastStringUtils` class.

**Comment by rmuir** [comment]
Hi, thanks for the report. I opened a PR for this: https://github.com/elastic/elasticsearch/issues/14500

Separately, I'm not sure its the best to do json serialization like this inside a script... but it is not dangerous to allow the properties in question to be read.
