### ISSUE TITLE
Awkward Load Average on ES

### ISSUE THREAD

**Issue by mehmetgunturkun** [elastic/elasticsearch#14495]
Hello everyone,

I have already created couple of threads on discuss.elastic.co but nobody replied and still couldn't find the main reason of that much high load average.

Threads are as follows, you can check all scenerio:
https://discuss.elastic.co/t/ngram-analyzer-and-huge-cpu-usage-under-50-req-sec/32797
https://discuss.elastic.co/t/many-slow-queries-and-high-cpu-load-on-load-test-50req-sec/32624

However to explain briefly I have two fields one is analyzed with standard tokenizer with ngram filter and other is only standard tokenizer. 

The problem is revelaed during load test.
When I run a load test on the field with standard tokenized it can reach to 600-700 rps
However, when I tested on with field which is analyzed with ngram filtering I cannot evet see 70 rps.

I was expecting decrease on query performance but load average and cpu load is awkward or I am missing something.

I have 24 cores on the server and when I ran "top" command I can see that %CPU is around 2200.
Is that normal? If not the possible reasons I can think:
1. Mistaken configuration.
2. Complex Query
3. Wrong architecture and Scaling 

**Btw, that is really huge problem that blocks us to make production deploy. I mean due to the fact that I am not sure if query causes this awkward behaviour, I cannot start using that on production. If any additional information is required I can create.**

Mehmet-

**Comment by clintongormley** [comment]
hi @mehmetgunturkun 

Let's keep this discussion in https://discuss.elastic.co/t/many-slow-queries-and-high-cpu-load-on-load-test-50req-sec/32624/8 for the moment.  We can open an issue here if we find a bug
