### ISSUE TITLE
Issues with retrieving a long with more that 16 digits.

### ISSUE THREAD

**Issue by bijaybisht** [elastic/elasticsearch#14506]
Using Elasticsearch version 1.5.2.

1. Create an document.
curl -XPOST "http://localhost:9200/sports2/_bulk" -d'
{"index":{"_index":"sports2","_type":"athlete"}}
{"name":"Michael", "birthdate":"1989-10-1", "sport":"Baseball", "rating": ["5", "4"],  "location":"46.22,-68.45", "long": 111111111111111111}

2. Query it
curl -XGET "http://localhost:9200/sports2/_search" -d '
{
    "query": {
        "query_string": { "query": "*" }
    }
}'

3. Notice the field "long" in the response. One the first 16 significant digits match. The Java API interface (9300) gets the correct value.
{
   "took": 9,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 1,
      "hits": [
         {
            "_index": "sports2",
            "_type": "athlete",
            "_id": "AVDP5hc0KF0ooNLJ55I6",
            "_score": 1,
            "_source": {
               "name": "Michael",
               "birthdate": "1989-10-1",
               "sport": "Baseball",
               "rating": [
                  "5",
                  "4"
               ],
               "location": "46.22,-68.45",
               "long": *111111111111111100*
            }
         }
      ]
   }
}

**Comment by dakrone** [comment]
@bijaybisht I'm unable to reproduce this:

    DELETE /sports2
    {}
    
    POST /sports2/athlete?refresh
    {
      "birthdate": "1989-10-1",
      "location": "46.22,-68.45",
      "long": 111111111111111111,
      "name": "Michael",
      "rating": [
        "5",
        "4"
      ],
      "sport": "Baseball"
    }

    {"acknowledged":true}
    {"_index":"sports2","_type":"athlete","_id":"AVDTaRHyF0ooKpQMJExk","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"created":true}

----------------

    GET /sports2/_search?pretty
    {}

    {
      "took" : 20,
      "timed_out" : false,
      "_shards" : {
        "total" : 5,
        "successful" : 5,
        "failed" : 0
      },
      "hits" : {
        "total" : 1,
        "max_score" : 1.0,
        "hits" : [ {
          "_index" : "sports2",
          "_type" : "athlete",
          "_id" : "AVDTaRHyF0ooKpQMJExk",
          "_score" : 1.0,
          "_source":{
      "birthdate": "1989-10-1",
      "location": "46.22,-68.45",
      "long": 111111111111111111,
      "name": "Michael",
      "rating": [
        "5",
        "4"
      ],
      "sport": "Baseball"
    }
        } ]
      }
    }

What version of Elasticsearch are you using?

**Comment by bijaybisht** [comment]
1.5.2

**Comment by dakrone** [comment]
> 1.5.2

Sorry, I see now that you had it in the original post, my bad for missing it.

I retried the same reproduction (same as above) with 1.5.2, however, the field comes back as `"long": 111111111111111111,`, do you have a client or anything that may be interfering with it?

**Comment by bijaybisht** [comment]
I also have 1.7.3 version installed on the server and I see the same behavior.  I have tried curl, kibana and chrome plugin to retrieve; all exhibit the same thing.

**Comment by dakrone** [comment]
I am testing with a version of your script:

```bash
# delete index if exists
echo "Deleting..."
curl -XDELETE "http://localhost:9200/sports2"
echo

echo '{"index":{"_index":"sports2", "_type":"athlete", "_id": "1"}}' > /tmp/bulk.json
echo '{"name":"Michael", "birthdate":"1989-10-1", "sport":"Baseball", "rating": ["5", "4"], "location":"46.22,-68.45", "long": 111111111111111111}' >> /tmp/bulk.json

echo "File:"
cat /tmp/bulk.json

echo "Indexing..."
curl -XPOST "http://localhost:9200/_bulk" --data-binary @/tmp/bulk.json
echo

echo "Refreshing..."
curl -XPOST "http://localhost:9200/sports2/_refresh"
echo

echo "Retrieving..."
curl -XGET "http://localhost:9200/sports2/_search?pretty" -d '
{
    "query": {
        "query_string": { "query": "*" }
    }
}'
echo
```

And here is the output I am getting with 1.7.3:

```
» ./repro.sh
Deleting...
{"acknowledged":true}
File:
{"index":{"_index":"sports2", "_type":"athlete", "_id": "1"}}
{"name":"Michael", "birthdate":"1989-10-1", "sport":"Baseball", "rating": ["5", "4"], "location":"46.22,-68.45", "long": 111111111111111111}
Indexing...
{"took":133,"errors":false,"items":[{"index":{"_index":"sports2","_type":"athlete","_id":"1","_version":1,"status":201}}]}
Refreshing...
{"_shards":{"total":10,"successful":5,"failed":0}}
Retrieving...
{
  "took" : 20,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "sports2",
      "_type" : "athlete",
      "_id" : "1",
      "_score" : 1.0,
      "_source":{"name":"Michael", "birthdate":"1989-10-1", "sport":"Baseball", "rating": ["5", "4"], "location":"46.22,-68.45", "long": 111111111111111111}
    } ]
  }
}
```

If you run this exact script, do you see the same issue?

**Comment by bijaybisht** [comment]
This works, I don't see the issue. My bad that I mentioned curl. It also works when I do a get from the browser it works well. I think the issue is related with Kibana (Both on safari and chrome)
<img width="1239" alt="screen shot 2015-11-04 at 10 49 20 am" src="https://cloud.githubusercontent.com/assets/4120848/10948292/c750775c-82e1-11e5-8c4b-626400cb130a.png">
 and the chrome plugin.

**Comment by bijaybisht** [comment]
I also notice that the response from the server is fine (developer tools in chrome), its just the display which is an issue in the case of the chrome plugin, guess both the chrome plugin and the kibana are using the same library.

**Comment by bijaybisht** [comment]
Raised an issue on kibana. Closing this one.
