### ISSUE TITLE
ElasticSearch API is not RESTful 

### ISSUE THREAD

**Issue by marcinn** [elastic/elasticsearch#14507]
As mentioned in #2688 Elasticsearch HTTP API is not RESTful, but ES manual says something else: https://www.elastic.co/guide/en/elasticsearch/reference/current/api-conventions.html

An example of adding index alias:

This is NOT a restful call:
```
curl -XPOST 'http://localhost:9200/_aliases' -d '
{
    "actions" : [
        { "remove" : { "index" : "test1", "alias" : "alias1" } }
    ]
}'
```

But this could be RESTful:
```
curl -XPUT 'http://localhost:9200/_aliases/alias1' -d '
{
    "index" : "test1"
}'
```

or something like that could be RESTful too (but we known URI while creating new resource, so example with PUT is far better):

```
curl -XPOST 'http://localhost:9200/_aliases' -d '
{
    "index" : "test1",
    "alias" : "alias1"
}'
```

I know that API can't be changed easily, so please correct documentation by removing "RESTful" adjective. ElasticSearch provides HTTP API based on JSON documents as a content-type, but this is not a REST. Thanks!

**Comment by bleskes** [comment]
When you say it's restfull, I presume you refer to the url structure. Agreed that for the example you gave the structure of the API is not the simplest construction. The reason is that the aliases API is capable of executing multiple API swaps in an *atomic* fashion. This is important to do stuff like index version where you want switch the alias from the older version your index to the new one with now down time to the external application using the alias.

```
POST _aliases
{
  "actions": [
    {
      "add": {
        "index": "index_name_v2",
        "alias": "index_name"
      }
    },
    {
      "remove": {
        "index": "index_name_v1",
        "alias": "index_name"
      }
    }
  ]
}
```

**Comment by marcinn** [comment]
I understand that. Maybe just RESTful principles does not fit ES API requirements. ES API does not have to be RESTful, and then shouldn't be named like that.

On the other side there is room for atomic and RESTful operations. Just create resource with representation of these operations, for example `http://localhost:9200/alias-operations` and PUT a collection of AliasOperation entities, defined as `{action: '<action>', index: '<name>', 'alias': '<name>'}`. ActionOperation may have own unique ID and state of execution, and I should be able to get details about batch via `alias-operations/<id>`. This would be RESTful and ActionOperation will be a kind of transaction.

Thanks.

**Comment by bleskes** [comment]
@marcinn I don't think I follow you and see where this will be structurally different than the current API (also adding IDs to these action is an overkill - these are one off and are executed immediately ). Can you describe more complete requests/interactions?

**Comment by marcinn** [comment]
I didn't expect following a RESTful principles. I'm just asking to remove "RESTful" adj. from website and documentation. ES API is not RESTful and probably never be.

**Comment by clintongormley** [comment]
@marcinn Providing a description that most people will understand is a lot more important than being 100% semantically accurate.  Closing

**Comment by marcinn** [comment]
So, @clintongormley, are you trying to say that people (or maybe only ElasticSearch users) are too dumb to see the difference? Is it o.k. when you're calling the bike a motorcycle? Have you heard about HATEOAS?

Just write "JSON over HTTP". It will be enough and more accurate. If you're not familiar with RESTful please read some about RESTful principles and architecture first, or maybe ask Roy Fielding.  

I've tried to built a RESTful client for ElasticSearch, but this is impossible due to ES API design. 

Thanks. Marcin.

**Comment by marcinn** [comment]
ElasticSearch 5.x still has no REST API. It breaks many REST constraints. Please read carefully these great articles - http://t-code.pl/blog/2016/02/rest-misconceptions-0/

Please update documentation and web pages. Please write clearly that ES uses HTTP/JSON API. You don't need to explain anybody the differences. Just write truth. Thanks.

**Comment by ibnesayeed** [comment]
Roy Fielding, one of the principal authors of the HTTP specification and the originator of the Representational State Transfer (REST) architectural style, wrote on his blog in 2008:

> I am getting frustrated by the number of people calling any HTTP-based interface a REST API. Today’s example is... ([Read full post](http://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven))
