### ISSUE TITLE
Ubuntu init script fails to start the instance

### ISSUE THREAD

**Issue by carlitux** [elastic/elasticsearch#14501]
I had to change this line in /etc/init.d/elasticsearch:114

```bash
DAEMON_OPTS="$DAEMON_OPTS -Des.max-open-files=true"
```
To

```bash
DAEMON_OPTS="$DAEMON_OPTS --Des.max-open-files=true"
```

Maybe not the best solution but now I have it working

**Comment by nik9000** [comment]
Which version of Elasticsearch and which version of Ubuntu?

**Comment by carlitux** [comment]
elasticsearch 2.0.0 and ubuntu trusty 14.04.3

**Comment by nik9000** [comment]
I just checked it again and it works for me. I don't have that line in /etc/init.d/elasticsearch. 114 is a blank line. Is there any chance this is a leftover from a previous install?

**Comment by carlitux** [comment]
@nik9000 sorry I doble checked and it is added by ansible.

**Comment by clintongormley** [comment]
@carlitux btw, changing that option to `--Des...` is just ignoring the option.  A `-Des` option needs to appear at the beginning of the command line.  Alternatively, use `--max-open-files true`.

That is a one-off test anyway, which these days can be replaced by examining the nodes info API.
