### ISSUE TITLE
Unable to set query options when using QueryBuilder.setSource(String)

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#14511]
(Using the Java client version 1.5.2)

```Java
        return client.prepareSearch(INDEX_NAME)
                .setSource(query)
                .setExplain(debugMode)
                .setVersion(true)
                ;
```

Will render essentially to a MatchAllQuery. This happens because the code paths for the two usages differ. If any of `setExplain`, `setVersion` or the rest of the methods for setting query options are called, the code in `SearchSourceBuilder.innerToXContent(XContentBuilder, Params)` is called and as a consequence invalidates the query that was passed via setSource.

This means there is currently no way of loading a query via setSource while setting up query options (those options that could be passed along with the URL, and I'd expect to be able to set also outside of the context of the actual query).

**Comment by javanna** [comment]
In 1.x or 2.x, the way to achieve what you need is via the `extraSource`, which is what we use internally to pass along options that have been provided as part of the URL.

This is a bit of a flaw of the current java api when it comes to search, as it allows you to provide the whole source as a bytes array (or string, or map). At that point you can't really ask also for it to be modified by providing additional options. In master (3.0) we removed support for setting the source as string or bytes array, you always have to provide a structured `SearchSourceBuilder` object. We did this because parsing happens now on the coordinating node, and if you provide a request using the java api, no parsing should happen anymore as you already provide proper java objects.

**Comment by synhershko** [comment]
Thanks Luca.

Just to make sure, you mean:

```java
        return client.prepareSearch(INDEX_NAME)
                .setExtraSource(query)
                .setExplain(debugMode)
                .setVersion(true)
                ;
```

Right?

With regards to your plans for 3.0, we do need to have support to load queries from JSON files. This has many use cases, for example allowing other teams to submit PRs for query changes of various parts of the system and only teaching them JSON and a subset of the DSL. Or an easier way to maintain and track changes. Or using Mustache locally for performance reasons. Etc etc. And no, search templates don't really cut it for most of those.

Please provide a way to parse a string query into a SearchSourceBuilder, this is a critical feature I've seen used to many times to want to see it go away. Would be happy to jump on a call to discuss further.

**Comment by javanna** [comment]
Yes @synhershko your code snippet looks good, that is what I meant. Note that the source is not just the query but the whole search request which supports also other sections than the query  (e.g. aggs, highlighting etc.).

As for your request to parse json as part of the java api, there might be a way in the future, we will discuss that but to me it is yet another reason why we should have a java REST client. The Java api should only deal with proper java objects that can be natively serialized over the wire, thus if parsing had to happen there, it would need to happen on the client before sending the request to any node, but for that to happen the parser would need to be aware of all the supported queries, certainly possible for a node client, but it would make less sense for a transport client. /cc @clintongormley 

That said there are a couple of outliers, like the template query, their parsing will still happen on the coordinating node, and the wrapper query, which does allow you to move the parsing to the data nodes by providing the inner query as bytes, but they are only two very particular queries.
