### ISSUE TITLE
Jboss initiated client node not killed off in Elasticsearch 1.4.4

### ISSUE THREAD

**Issue by nithyanv** [elastic/elasticsearch#14519]
Hi,

My web application is using an ES Node client. The ES server is a single node. Since we are in development stage, it was noticed that when we restarted JBoss for any reason the previous instance of ES Node client still appears in that ES server's cluster view.

Is there a time out that we can set? 

What happens if I use multiple JBoss Instances in a cluster using the same cluster? Do the virtual client nodes then need to know each other as well?

**Comment by clintongormley** [comment]
Hi @nithyanv 

This sounds like a question for the forums: http://discuss.elastic.co/
