### ISSUE TITLE
Add information about index status (open/closed/etc) to the "Get Index" API

### ISSUE THREAD

**Issue by karmi** [elastic/elasticsearch#14516]
Since the "Index Status" API has been deprecated in #4854, there is not a convenient way to check whether the index exists, and is closed or open (coming from discussion in the Ruby's client repository, elastic/elasticsearch-ruby#224).

It would be nice to add the information to the ["Get Index"](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-index.html) API, so the user would have a succint way how to check for and existing and open in an expressive language (eg. `client.indices.get(index: 'closed', ignore_unavailable: true)['status'] == ''open`).

**Comment by clintongormley** [comment]
You can use the cluster state API instead:

    GET _cluster/state/metadata/my_index

or even:

    GET _cluster/state/metadata/my_index?filter_path=metadata.indices.*.state
