### ISSUE TITLE
Exceptions in general

### ISSUE THREAD

**Issue by designermonkey** [elastic/elasticsearch#14528]
Hi guys,

I'm using the elasticsearch-php library to build applications with, and there is one thing that really bugs me; Exceptions.

Now @polyfractal and the other contributors have done an exceptional job there, but they can't be blamed for poor exception output. What I mean is that the main exception I get is a `BadRequest400Exception`, which is pretty generic, and has to be because the value returned from elasticsearch itself is as the following:

```json
{
	"error": "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[5gPjjrRuSxiYzNBtadLr3Q][live][0]: SearchParseException[[live][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"match_all\":[]},\"filter\":{\"bool\":{\"must\":[{\"nested\":{\"path\":\"hierarchy\",\"filter\":{\"bool\":{\"must\":[{\"term\":{\"hierarchy.level\":1}},{\"term\":{\"hierarchy.path\":\"\\/tips\"}}]}}}},{\"nested\":{\"path\":\"schedule\",\"filter\":{\"bool\":{\"must\":[],\"must_not\":{\"terms\":{\"schedule.type\":[\"withheld\"]}}}}}}]}}}},\"sort\":{\"schedule.start\":{\"order\":\"desc\",\"nested_filter\":{\"term\":{\"schedule.type\":\"published\"}}}},\"from\":0,\"size\":12}]]]; nested: QueryParsingException[[live] [nested] failed to find nested object under path [hierarchy]]; }{[5gPjjrRuSxiYzNBtadLr3Q][live][1]: SearchParseException[[live][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"match_all\":[]},\"filter\":{\"bool\":{\"must\":[{\"nested\":{\"path\":\"hierarchy\",\"filter\":{\"bool\":{\"must\":[{\"term\":{\"hierarchy.level\":1}},{\"term\":{\"hierarchy.path\":\"\\/tips\"}}]}}}},{\"nested\":{\"path\":\"schedule\",\"filter\":{\"bool\":{\"must\":[],\"must_not\":{\"terms\":{\"schedule.type\":[\"withheld\"]}}}}}}]}}}},\"sort\":{\"schedule.start\":{\"order\":\"desc\",\"nested_filter\":{\"term\":{\"schedule.type\":\"published\"}}}},\"from\":0,\"size\":12}]]]; nested: QueryParsingException[[live] [nested] failed to find nested object under path [hierarchy]]; }{[5gPjjrRuSxiYzNBtadLr3Q][live][2]: SearchParseException[[live][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"match_all\":[]},\"filter\":{\"bool\":{\"must\":[{\"nested\":{\"path\":\"hierarchy\",\"filter\":{\"bool\":{\"must\":[{\"term\":{\"hierarchy.level\":1}},{\"term\":{\"hierarchy.path\":\"\\/tips\"}}]}}}},{\"nested\":{\"path\":\"schedule\",\"filter\":{\"bool\":{\"must\":[],\"must_not\":{\"terms\":{\"schedule.type\":[\"withheld\"]}}}}}}]}}}},\"sort\":{\"schedule.start\":{\"order\":\"desc\",\"nested_filter\":{\"term\":{\"schedule.type\":\"published\"}}}},\"from\":0,\"size\":12}]]]; nested: QueryParsingException[[live] [nested] failed to find nested object under path [hierarchy]]; }{[5gPjjrRuSxiYzNBtadLr3Q][live][3]: SearchParseException[[live][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"match_all\":[]},\"filter\":{\"bool\":{\"must\":[{\"nested\":{\"path\":\"hierarchy\",\"filter\":{\"bool\":{\"must\":[{\"term\":{\"hierarchy.level\":1}},{\"term\":{\"hierarchy.path\":\"\\/tips\"}}]}}}},{\"nested\":{\"path\":\"schedule\",\"filter\":{\"bool\":{\"must\":[],\"must_not\":{\"terms\":{\"schedule.type\":[\"withheld\"]}}}}}}]}}}},\"sort\":{\"schedule.start\":{\"order\":\"desc\",\"nested_filter\":{\"term\":{\"schedule.type\":\"published\"}}}},\"from\":0,\"size\":12}]]]; nested: QueryParsingException[[live] [nested] failed to find nested object under path [hierarchy]]; }{[5gPjjrRuSxiYzNBtadLr3Q][live][4]: SearchParseException[[live][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"match_all\":[]},\"filter\":{\"bool\":{\"must\":[{\"nested\":{\"path\":\"hierarchy\",\"filter\":{\"bool\":{\"must\":[{\"term\":{\"hierarchy.level\":1}},{\"term\":{\"hierarchy.path\":\"\\/tips\"}}]}}}},{\"nested\":{\"path\":\"schedule\",\"filter\":{\"bool\":{\"must\":[],\"must_not\":{\"terms\":{\"schedule.type\":[\"withheld\"]}}}}}}]}}}},\"sort\":{\"schedule.start\":{\"order\":\"desc\",\"nested_filter\":{\"term\":{\"schedule.type\":\"published\"}}}},\"from\":0,\"size\":12}]]]; nested: QueryParsingException[[live] [nested] failed to find nested object under path [hierarchy]]; }]",
	"status": 400
}
```

This is a very small Json object with a message string that is a mix of strings and Json objects. How is this ever supposed to be parsed into useful information for an API to use to create more specific exceptions?

As elasticsearch is a Json outputting application, then surely some better responses can come from it's exceptions? I'd like to be able to better ascertain what went wrong in my applications, without having to do some expensive string matching to figure this out.

I'm not trying to just moan, believe me, as 90% of the time this stuff works a charm, but when it doesn't (even if it's my stupid fault) I'd like some better information.

**Comment by designermonkey** [comment]
And on a slight tangent, the exception above is because of a missing mapping, yet elasticsearch never even tells me that, it balks on the fact it can't use a nested path. Surely, the missing mapping is the issue, not the path?

**Comment by dakrone** [comment]
@designermonkey what version of ES are you using? With 2.0 REST exceptions are now rendered in a structured way, to make it easier to extract useful information out of them. Additionally, we are working on parsing queries on the coordinating node, which will reduce the amount of shard failures (only a single exception instead of an exception for each shard)

**Comment by designermonkey** [comment]
I'm on 1.7 and not sure about upgrading yet. Any breaking changes to know about? Can an existing index be upgraded?

**Comment by polyfractal** [comment]
BTW, this is what the exception would look like under 2.0:

```json
{
   "error": {
      "root_cause": [
         {
            "type": "query_parsing_exception",
            "reason": "[nested] failed to find nested object under path [hierarchy]",
            "index": "test",
            "line": 14,
            "col": 25
         }
      ],
      "type": "search_phase_execution_exception",
      "reason": "all shards failed",
      "phase": "query",
      "grouped": true,
      "failed_shards": [
         {
            "shard": 0,
            "index": "test",
            "node": "R33m3wHNSbGW8mkHcJwlpQ",
            "reason": {
               "type": "query_parsing_exception",
               "reason": "[nested] failed to find nested object under path [hierarchy]",
               "index": "test",
               "line": 14,
               "col": 25
            }
         }
      ]
   },
   "status": 400
}
```


There are indeed breaking changes, specifically around mappings which might cause some trouble.  You can read about them here:  https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking-changes-2.0.html

The new [Migration Plugin](https://github.com/elastic/elasticsearch-migration) should help identify potential issues before upgrading, at least on the index structure / mapping / analysis side of things.  Won't be able to help with changes to query or response syntax.

**Comment by designermonkey** [comment]
That is so much better :) Thanks for the info guys.

@polyfractal would this require an upgrade of the php lib to v2 as well?

**Comment by polyfractal** [comment]
Nope, no upgrade required.  The ES-PHP 1.x branch never tried to deserialize the error response, since sometimes ES would send back non-JSON exceptions (mostly with older versions of ES iirc).  So you'll just get back a blob of (structured) JSON using the ES-PHP 1.x branch. 

If you know you're always querying a 2.x branch of Elasticsearch, you should be able to safely `json_decode()` the exception message all the time.

So with ES-PHP 1.x you'll get something like this:

```php
print_r($e->getMessage())
  {"error":{"root_cause":[{"type":"query_parsing_exception","reason":"[nested] failed to find nested object under path [hierarchy]","index":"test","line":14,"col":35}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"test","node":"PHHrUvTRQbuiTaAtGsESvA","reason":{"type":"query_parsing_exception","reason":"[nested] failed to find nested object under path [hierarchy]","index":"test","line":14,"col":35}}]},"status":400}

print_r($e->getCode())
  400

print_r($e->getPrevious()->getMessage())
  Client error response
  [status code] 400
  [reason phrase] Bad Request
  [url] http://localhost:9200/_search
```

Whereas with the ES-PHP 2.x branch you'd see:

```php
print_r($e->getMessage())
  query_parsing_exception: [nested] failed to find nested object under path [hierarchy]

print_r($e->getCode())
  400

print_r($e->getPrevious()->getMessage())
  {"error":{"root_cause":[{"type":"query_parsing_exception","reason":"[nested] failed to find nested object under path [hierarchy]","index":"test","line":14,"col":35}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"test","node":"PHHrUvTRQbuiTaAtGsESvA","reason":{"type":"query_parsing_exception","reason":"[nested] failed to find nested object under path [hierarchy]","index":"test","line":14,"col":35}}]},"status":400}
```

I'm actually working on the exception handling right now (in part spurred by your exception ticket, in part by working ES 2.0 itself).  PHP exceptions can only accept a string as their error message, which means we decode the exception into a nice PHP array to build the "english reason"...then throw it away.  Which is not terribly friendly.

So I'm working right now to add a `getStructured()` method to the exceptions so you can get the full ES structured exception in array form.

**Comment by designermonkey** [comment]
Thanks for the feedback. I really do wish I had time to help you out there, family and heavy work commitments leave me with no time :(
