### ISSUE TITLE
delete-by-query failing with Shield enabled

### ISSUE THREAD

**Issue by hub-cap** [elastic/elasticsearch#14527]
On Found we are testing the delete-by-query plugin in 2.0.0. I have enabled the plugin and when I issue a delete via _query, I get the following response.

```
{"error":{"root_cause":[{"type":"security_exception","reason":"action [indices:data/read/search] is unauthorized for user []"}],"type":"security_exception","reason":"action [indices:data/read/search] is unauthorized for user []"},"status":403}
```

**Comment by tlrx** [comment]
Helpful quote from @javanna :
> Delete by query should pass to original request to the inner search request, so that headers are copied over. Same with any other sub-request
