### ISSUE TITLE
No 'status' response in 2.0.0-beta2

### ISSUE THREAD

**Issue by luke3141** [elastic/elasticsearch#14523]
In ES 1.7 & earlier, a standard request curl `localhost:9200` would return something like:

    {
      "status" : 200,
      "name" : "Svarog",
      "cluster_name" : "elasticsearch",
      "version" : {
        "number" : "1.7.3",
        "build_hash" : "xxx",
        "build_timestamp" : "2015-10-15T01:01:01Z",
        "build_snapshot" : false,
        "lucene_version" : "4.10.4"
      },
      "tagline" : "You Know, for Search"
    }

the 'status' field appears to be dropped in 2.0:

    {
      "name" : "Svarog",
      "cluster_name" : "elasticsearch",
      "version" : {
        "number" : "2.0.0-beta2",
        "build_hash" : "xxx",
        "build_timestamp" : "2015-09-1401:01:01Z",
        "build_snapshot" : false,
        "lucene_version" : "5.2.1"
      },
      "tagline" : "You Know, for Search"
    }

Was this intentional, or unintentional?
If unintentional, will it be reinserted?

**Comment by dadoonet** [comment]
You should rely on HTTP status code instead.
That's the reason it was removed as it tells the same thing.
