### ISSUE TITLE
Clarify recovery vs. relocation in documentation

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#14539]
Somewhere in our documentation, it will be nice to clarify that relocation is a form/type of recovery, so that the [recovery settings](https://www.elastic.co/guide/en/elasticsearch/reference/master/recovery.html#recovery) actually apply to both shard recoveries and relocations (even though the parameter name of these settings refers to "recovery" only).

**Comment by bleskes** [comment]
@debadair is this something you or team plan to work on?

**Comment by jrodewig** [comment]
@bleskes I'll be picking this one up.
