### ISSUE TITLE
The package is of bad quality

### ISSUE THREAD

**Issue by JulioV** [elastic/elasticsearch#14532]
I'm getting the message "The package is of bad quality" after trying to install elasticsearch in a 64-bit Elementary OS 0.3.1 Freya distribution with the latest elasticsearch deb package. The error has the following details:

Lintian check results for /home/user/Downloads/elasticsearch-2.0.0.deb:
E: elasticsearch: dir-or-file-in-var-run var/run/elasticsearch/

**Comment by dakrone** [comment]
I looked into this: https://lintian.debian.org/tags/dir-or-file-in-var-run.html

"/var/run may be a temporary filesystem, so any directories or files needed there must be created dynamically at boot time."

@electrical thoughts?

**Comment by nik9000** [comment]
I believe we create the directories we need in `/var/run` on startup. So its not telling us anything we didn't already know, at least.

**Comment by electrical** [comment]
@JulioV Lintian it self follows a set of very arbitrary rules that are set by Debian that have no impact it self on the package.

An other discussion was a while ago about the Logstash packages at https://github.com/elastic/logstash/issues/2011

If there are real operational issues with the packages we can look at those and fix them of course.

**Comment by JulioV** [comment]
There are some problems. Apparently, the deb package create several directories:

- /etc/default/elasticsearch
- /etc/init.d/elasticsearch
- /etc/elasticsearch
- /run/elasticsearch
- /usr/share/doc/elasticsearch
- /usr/share/lintian/overrides/elasticsearch
- /usr/share/elasticsearch
- /usr/share/elasticsearch/bin/elasticsearch
- /var/lib/elasticsearch
- /var/log/elasticsearch

When I try to run  "/usr/share/elasticsearch/bin/elasticsearch" there are two exceptions: 

Failed to configure logging...
ElasticsearchException[Failed to load logging configuration]; nested: NoSuchFileException[/usr/share/elasticsearch/config];

And..

Exception in thread "main" java.lang.IllegalStateException: Unable to access 'path.conf' (/usr/share/elasticsearch/config)
Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config

If I try to run it using sudo I got the message "don't run elasticsearch as root".

**Comment by electrical** [comment]
Hi,

Those errors are indeed expected since the init script + defaults file set different values with the bin/elasticsearch script to give the right paths to the config file at /etc/elasticsearch
See https://github.com/elastic/elasticsearch/blob/master/distribution/deb/src/main/packaging/init.d/elasticsearch#L101-L102 for those details.

If none of those options are given then it uses indeed the config directory you got the error for.

**Comment by JulioV** [comment]
Should I look to "/etc/init.d/elasticsearch"? Because is empty as well.

**Comment by electrical** [comment]
Not sure if "Elementary OS" does anything funky. I just did a test install on Ubuntu 14.04 and works fine including init script.

**Comment by JulioV** [comment]
Maybe, it is supposed to be based on Ubuntu but it might be an internal issue. Either way, I just downloaded the ES zip file and ran it without problems.

**Comment by s1monw** [comment]
thanks for reporting this issue. We don't officially support this OS but if you feel like submitting a PR for this please go ahead. I will close this issue for now since we don't have the resources to work on it any time soon.
