### ISSUE TITLE
Builds don't include the build_hash or build_timestamp

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch#14534]
Builds of master don't include the build_hash or build_timestamp that usually are available. Is it possible to get this info back?

Output of `http://localhost:9200/`
![image](https://cloud.githubusercontent.com/assets/1329312/10951721/a439a70c-8304-11e5-8111-af5dddbc57a2.png)

**Comment by jasontedor** [comment]
Didn't see this before but I saw similar behavior and opened and integrated #14564. Does that work for you @spalger?

**Comment by spalger** [comment]
@jasontedor is it possible to use a standard date format for the build_date? What was wrong with ISO 8601?

**Comment by jasontedor** [comment]
> is it possible to use a standard date format for the build_date?

@spalger It's possible. That build timestamp is put into the jar manifest by a Gradle plugin. So to keep it simple, we just grab the timestamp directly out of the manifest (as a string). If you have a need for ISO 8601, we can certainly do that.

> What was wrong with ISO 8601?

Nothing. Frankly, I was surprised that the Gradle plugin that we are using wasn't putting it into that format.

**Comment by spalger** [comment]
Cool, it would be much appreciated :)

**Comment by jasontedor** [comment]
> Cool, it would be much appreciated :)

@spalger I opened #14751 on our side to change the formatting. Note that the plugin we are using to get this information into the manifest in the first place does not include timezone information so without some hoops the best that we have right now is a local date time. I also opened nebula-plugins/gradle-info-plugin#22 to see if we can get that included in the basic info.

**Comment by spalger** [comment]
Awesome, thanks @jasontedor

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/14764 and https://github.com/elastic/elasticsearch/pull/14564

**Comment by spalger** [comment]
:dancer:
