### ISSUE TITLE
Bad docs for installing marvel with offline

### ISSUE THREAD

**Issue by aanm** [elastic/elasticsearch#14545]
The following steps:
```
bin/plugin install license file:///path/to/file/license-2.0.0.zip
bin/plugin install marvel-agent file:///path/to/file/marvel-agent-2.0.0.zip
bin/kibana plugin --install marvel --url file:///path/to/file/marvel-2.0.0.tar.gz
```
don't work on elasticsearch:2.0.0 docker image
source: https://www.elastic.co/guide/en/marvel/current/installing-marvel.html#offline-installation

Output:
```
-> Installing license...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/license/2.0.0/license-2.0.0.zip ...
Downloading .......DONE
Verifying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/license/2.0.0/license-2.0.0.zip checksums if available ...
Downloading .DONE
Installed license into /usr/share/elasticsearch/plugins/license
-> Installing marvel-agent...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/marvel-agent/2.0.0/marvel-agent-2.0.0.zip ...
Downloading .........DONE
Verifying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/marvel-agent/2.0.0/marvel-agent-2.0.0.zip checksums if available ...
Downloading .DONE
Installed marvel-agent into /usr/share/elasticsearch/plugins/marvel-agent
exec: "/usr/share/elasticsearch/bin/kibana": stat /usr/share/elasticsearch/bin/kibana: no such file or directory
```

Expecting:
* license and marvel-agent to NOT be downloaded
* bin/kibana to be present

**Comment by dadoonet** [comment]
To run marvel Kibana application you need to have Kibana! :)

May be we should add a line telling that to users?

**Comment by aanm** [comment]
@dadoonet So this doesn't work with docker where you have a container for kibana and a container for elasticsearch?

**Comment by aanm** [comment]
@dadoonet ah, it means for kibana I need to install marvel on its container. But still the `bin/plugin install license file:///path/to/file/license-2.0.0.zip` should be `bin/plugin install file:///path/to/file/license-2.0.0.zip`.
Thanks

**Comment by dadoonet** [comment]
Agreed. Same for marvel-agent BTW

**Comment by tlrx** [comment]
Documentation has been fixed, thanks

**Comment by jalpeshshelar** [comment]
How to install Marvel on Kibana in windows ?

bin/kibana plugin --install marvel --url file:///path/to/file/marvel-2.0.0.tar.gz
