### ISSUE TITLE
RecoveryWhileUnderLoadIT#recoverWhileRelocating test failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#14544]
These fails sometime on CI on 2.x and 2.0 branches only:
* http://build-us-00.elastic.co/job/es_core_2x_metal/428/ (most recent)
* http://build-us-00.elastic.co/job/elasticsearch-20-oracle-jdk6/1477/
* http://build-us-00.elastic.co/job/elasticsearch-20-centos/397/

In the last part of the test, after bumping up the number of replicas the the expected number of documents seem not to be the same on all shards.

**Comment by clintongormley** [comment]
Old test report. Closing

**Comment by imotov** [comment]
Failed again on Mar 21 and again today. See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.x+multijob-os-compatibility/os=centos/58/console and https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.2+multijob-os-compatibility/os=ubuntu/29/console

**Comment by bleskes** [comment]
I pushed some [changes](https://github.com/elastic/elasticsearch/commit/ba4b321af33e73d6f933a7bde9a5f3b1c8d29a7b) to hopefully help debug when it happens again.
