### ISSUE TITLE
Phrase suggester collate doesn’t work in search template

### ISSUE THREAD

**Issue by buinauskasevaldas** [elastic/elasticsearch#14558]
First of all, I'm using Elasticsearch 1.7.3

I'm facing issues with `collate` in Phrase Suggester.

Please see this reproduction:

    PUT /test/test/1
    {
      "CompanyName": "coca-cola"
    }
    
    POST /test/_search
    {
      "size": 0,
      "suggest": {
        "DidYouMean": {
          "text": "coce",
          "phrase": {
            "field": "_all",
            "size": 50,
            "direct_generator": [
              {
                "field": "_all",
                "suggest_mode": "popular",
                "min_word_length": 3
              }
            ],
            "collate": {
              "query": {
                "match": {
                  "CompanyName": {
                    "query": "{{suggestion}}",
                    "operator": "and"
                  }
                }
              },
              "prune": true
            }
          }
        }
      }
    }

It brings me this result with `"collate_match": true`:

    {
       "took": 4,
       "timed_out": false,
       "_shards": {
          "total": 5,
          "successful": 5,
          "failed": 0
       },
       "hits": {
          "total": 1,
          "max_score": 0,
          "hits": []
       },
       "suggest": {
          "DidYouMean": [
             {
                "text": "coce",
                "offset": 0,
                "length": 4,
                "options": [
                   {
                      "text": "coca",
                      "score": 0.6531368,
                      "collate_match": true
                   },
                   {
                      "text": "cola",
                      "score": 0.5476822,
                      "collate_match": true
                   }
                ]
             }
          ]
       }
    } 

But when I create a template using this query:

    PUT /_search/template/suggest
    {
      "template": {
        "size": 0,
        "suggest": {
          "DidYouMean": {
            "text": "{{SearchPhrase}}",
            "phrase": {
              "field": "_all",
              "size": 50,
              "direct_generator": [
                {
                  "field": "_all",
                  "suggest_mode": "popular",
                  "min_word_length": 3
                }
              ],
              "collate": {
                "query": {
                  "match": {
                    "CompanyName": {
                      "query": "{{suggestion}}",
                      "operator": "and"
                    }
                  }
                },
                "prune": true
              }
            }
          }
        }
      }
    }

And call it using this:

    POST /test/_search/template
    {
      "template": {
        "id": "suggest"
      },
      "params": {
        "SearchPhrase": "coca cole"
      }
    }

I'm getting false results:

    {
       "took": 6,
       "timed_out": false,
       "_shards": {
          "total": 5,
          "successful": 5,
          "failed": 0
       },
       "hits": {
          "total": 1,
          "max_score": 0,
          "hits": []
       },
       "suggest": {
          "DidYouMean": [
             {
                "text": "coca cole",
                "offset": 0,
                "length": 9,
                "options": [
                   {
                      "text": "coca cola",
                      "score": 0.4727091,
                      "collate_match": false
                   },
                   {
                      "text": "coca coca",
                      "score": 0.39638618,
                      "collate_match": false
                   }
                ]
             }
          ]
       }
    }

Issue seems to be {{suggestion}} itself. I'm suspecting that when I call a template, it expects `suggestion` parameter from my template query, so it can pass a value. However - it's empty.

As a workaround, I modified template like this:

    {
      "collate" : {
        "prune" : true,
        "query" : {
          "match" : {
            "_all" : {
              "query" : "{{=<% %>=}}{{suggestion}}<%={{ }}=%>"
            }
          }
        }
      }
    }

Query was expecting a parameter, which was not supplied. Special characters (braces) had to be escaped, now it seems to perform right.

Can anyone confirm it's correct approach?

**Comment by clintongormley** [comment]
That's one approach.  Another is simply to escape the `{}` as:

    "query": "\\{\\{suggestion\\}\\}",
