### ISSUE TITLE
remove transport profiles and the 87 ways to configure network settings

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#14553]
Transport profiles:

These are really complicated, its hard for anyone to digest NettyTransport, and they lead to bugs like https://github.com/elastic/elasticsearch/pull/14535 (i think that is damage from the last time they were touched).

Overengineered and unnecessary, in a place where simplicity is key: no brainer.

Other network settings:

Every other setting looks like this:
        this.maxChunkSize = settings.getAsBytesSize("http.netty.max_chunk_size", settings.getAsBytesSize("http.max_chunk_size", new ByteSizeValue(8, ByteSizeUnit.KB)));

why do we need 2 ways to do it? It just makes things more complicated and there are far too many settings even if there is only one way for each.

**Comment by rmuir** [comment]
I recommend just having this as a breaking change for 3.0: I will work on removing this stuff. Its a new major release and thats why we have the ability to introduce breaking changes.

This stuff is really bad and causing a lot of problems.

**Comment by jasontedor** [comment]
I am not sure if we can consider removing transport profiles at this time and these settings have otherwise been greatly simplified.
