### ISSUE TITLE
Add Dedicated Backward Compatibility Testing to GeoPointV2

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#14562]
This issue is to add testing which ensures that geopoint doc values work correctly under the following scenarios:

* pre-2.2 index with only pre 2.2 segments
* pre 2.2 index with a mix of pre and post 2.2. segments
* post 2.2 index

**Comment by clintongormley** [comment]
@nknize can this be closed now?

**Comment by nknize** [comment]
Completed in #14667
