### ISSUE TITLE
Cluster discovery does not work if plugins are not identical

### ISSUE THREAD

**Issue by benjfield** [elastic/elasticsearch#14567]
In this scenario:

A cluster with plugins installed (in this case license and marvel), appears to be working correctly. When a node without these plugins trys to connect to the cluster, the connection does not work correctly. Here is the logs:

http://pastie.org/private/bokrdcgsjncicplwzm0rg

Here is a trace log:

https://gist.github.com/benjfield/87f19d8c6c5afec124cc

From the nodes with the plugins it appears to be connected:

https://gist.github.com/benjfield/3706b893f42d8701f698

However from the broken node:

{"error":{"root_cause":[{"type":"master_not_discovered_exception","reason":"waited for [30s]"}],"type":"master_not_discovered_exception","reason":"waited for [30s]"},"status":503}

**Comment by clintongormley** [comment]
Yes, you need to install the licensing plugin on all nodes.  The transport client doesn't require licensing though.

**Comment by benjfield** [comment]
Can this error message be improved to tell you this? Me and a guy on IRC spent the best part of the day working through potential issues on this before we discovered this problem. I'm also not sure this is documented on the website.

**Comment by clintongormley** [comment]
Yes, there's already an issue open for that: https://github.com/elastic/elasticsearch/issues/13445

sorry, should have linked to it

**Comment by crickes** [comment]
This one just caught me out too.

**Comment by filipegmiranda** [comment]
Does this happen to all plugins we install in Elasticsearch?
