### ISSUE TITLE
date parse error on range query in es 2

### ISSUE THREAD

**Issue by jillesvangurp** [elastic/elasticsearch#14565]
I have a weird problem where Java 8 adds a plus sign to iso dates if the year is more than 4 characters

```
LocalDateTime.of(10000, 01, 01, 0, 0).toString()
produces "+10000-01-01T00:00:00.000Z"
LocalDateTime.of(9999, 01, 01, 0, 0).toString()
produces "9999-01-01T00:00:00.000Z"
```

Before Elasticsearch 2.0 passing this into a range query on a date field was no problem either way but this started breaking during the migration to es 2:

This filter:

```
{
    "range":{
        "event_at":{
            "from":"0000-01-01T00:00:00.000Z",
            "to":"+10000-01-01T00:00:00.000Z"
        }
    }
}
```

Now generates the following error:

```
{
    "shard":0,
    "index":"inbot_activities_v29",
    "node":"4pFF0w30RO6ahMk9OEvqWQ",
    "reason":{
        "type":"parse_exception",
        "reason":"failed to parse date field [+10000-01-01T00:00:00.000Z] with format [strict_date_optional_time||epoch_millis]",
        "caused_by":{
            "type":"illegal_argument_exception",
            "reason":"Invalid format: \"+10000-01-01T00:00:00.000Z\" is malformed at \"-01-01T00:00:00.000Z\""
        }
    }
}
```

The workaround is obvious and already implemented on my side (-1 to 9999).

But this error was sufficiently weird that I wanted to report it. Maybe it can be fixed by moving from joda to java 8's new date API as I think has been debated already. Alternatively the date pattern used by default could be adapted to allow the + sign.

**Comment by lynneker7** [comment]
I have similar problem but a little different. In ElasticSearch 2.0 latest. 

Document:
<pre>
<code>
{
    "date": "2015-11-05T05:33:54.431Z",
    "product_id": "27d898e783a16492cafc25a0f9a415d67970b811"
 }
</code>
</pre>
Query
<pre>
<code>
{
  "query": {
    "bool": {
      "must": [
        {
          "match_all": {}
        }
      ],
      "filter": [
        {
          "terms": {
            "product_id": [
              "27d898e783a16492cafc25a0f9a415d67970b811"
            ]
          }
        },
        {
          "range": {
            "date": {
              "lte": "2015-11-05"
            }
          }
        }
      ]
    }
  }
}
</code>
</pre>
Result:
<pre>
<code>
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}
</code>
</pre>

**Comment by jillesvangurp** [comment]
@lynneker7 that looks like the problem is with your query. Change lte to gte and you should see the document since the timestamp is after the queried timestamp.

**Comment by lynneker7** [comment]
@jillesvangurp Sorry you're absolutely right. Thanks

**Comment by javanna** [comment]
@spinscale any comments on this? cc @elastic/es-search-aggs

**Comment by rjernst** [comment]
ISO 8601 prescribes to use a 4 digit year, supporting years 0000 to 9999. It has an optional portion that uses +/- for years outside that range. It appears joda does not adhere to this part of the spec.  We are currently converting joda time uses to java time (see https://github.com/elastic/elasticsearch/issues/27330). I'm going to close this as there is no reason to investigate and try of fix joda when it is going away.
