### ISSUE TITLE
multi_explain

### ISSUE THREAD

**Issue by ericjohnston1989** [elastic/elasticsearch#14570]
Would it be possible to have an API to request an explain response for multiple document ids at once? There is a bulk API, a multi_get API, and a multi_search API already. From what I can tell, the only options I have right now are

a) Issue multiple explain requests at once
b) Perform a search with explain=true and an additional ID filter

Neither of these are ideal.

Thanks!

**Comment by clintongormley** [comment]
Hi @ericjohnston1989 

The options you list are correct.  We won't add a bulk explain API as it signals the wrong intent.  Explain is a heavy operation and is intended for debugging only, not for use in production at scale.
