### ISSUE TITLE
same field names may raise confliction with different type and analyzer

### ISSUE THREAD

**Issue by hawkwang** [elastic/elasticsearch#14575]
Here is the statement about how this happens, see as follows:
=============================================================
curl -XPUT 'localhost:9200/company?pretty' -d '
{
  "mappings": {
    "basic": {
      "properties": {
        "id" : {"type" : "string", "index" : "not_analyzed"},
        "title" : {
            "type" : "string",
            "fields": {
                "raw": { 
                  "type":  "string",
                  "index": "not_analyzed"
                }
            }
        },
        "djjg" : {"type" : "string", "index" : "not_analyzed"}
      }
    },
    "investor": {
      "_parent": {
        "type": "basic" 
      },
       "properties": {
          "title" : {"type" : "string", "index" : "not_analyzed"},
          "type" : {"type" : "string", "index" : "not_analyzed"}
       }
    }
  }
}'
======================================================
The following error messages occurs:
======================================================
{
  "error" : {
    "root_cause" : [ {
      "type" : "mapper_parsing_exception",
      "reason" : "mapping [investor]"
    } ],
    "type" : "mapper_parsing_exception",
    "reason" : "mapping [investor]",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "Mapper for [title] conflicts with existing mapping in other types:\n[mapper [title] has different [index] values, mapper [title] has different [doc_values] values, cannot change from disabled to enabled, mapper [title] has different [analyzer], mapper [title] is used by multiple types. Set update_all_types to true to update [omit_norms] across all types., mapper [title] is used by multiple types. Set update_all_types to true to update [search_analyzer] across all types., mapper [title] is used by multiple types. Set update_all_types to true to update [search_quote_analyzer] across all types.]"
    }
  },
  "status" : 400
}
======================================================

I guess this error is raised due to same "title" fields used in parent and child mode :-)
Of cause, I can change the second one to "name", and that is fine.
But I think it should be not a big problem.
Any hint???

Regards,
Hawk

**Comment by s1monw** [comment]
> I guess this error is raised due to same "title" fields used in parent and child mode :-)
Of cause, I can change the second one to "name", and that is fine.

yes that's the reason, even though they seem to be isolated they are not. You have to either specify the same analyzer and type or use a different name.

**Comment by TwentyOneSolutions** [comment]
Is there a blog post or some article explaining this?  I'm trying to upgrade from ES1.7.1 to ES2.0.0 and I'm getting this error, and I don't understand what `Set update_all_types to true` means.  Where do I set `update_all_types`?

**Comment by clintongormley** [comment]
Yeah during upgrade you can't specify that option (see https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#merging-conflicts for where you can use it).  

Essentially you need to fix or delete this index before upgrading.  The [migration plugin](https://github.com/elastic/elasticsearch-migration/) will help you to spot problematic indices before upgrading.

**Comment by biancazzurri** [comment]
Please somebody explain why is this an expected behavior? To me it seems that its a non correct one. To my understanding there should be no connection between fields in different type

**Comment by dadoonet** [comment]
Please ask your question on discuss.elastic.co where we can certainly help.
