### ISSUE TITLE
Wrong matched query in inner hits

### ISSUE THREAD

**Issue by lipixun** [elastic/elasticsearch#14574]
hi, all

I found the matched query in inner hits is not correct in some cases.

Suppose we have two documents: P for parent document, C for child document. A query looks like:

    {
        "or": [    
       {
            "has_child": {
                "type": "C",
               "query": {
                   A query named q1
               },
               "name": "xxx"
           },
           {
               "has_child": {
                   "type": "C",
                   "query": {
                      A query named q2
                   },
                  "name":  "yyy"
               }
           }
    }

Searching for doc_type P.

__It's possible for a single document C that satisfies both q1 and q2.__

So, I wanna parse the es result to figure out which query is hitted by the matched query, what am I doing is:

* Find the inner object by xxx or yyy
* Find the matched query in the inner hits

What I expected is finding q1 in xxx or q2 in yyy, but actually I found both q1 and q2 in xxx (Actually q1 and q2 may be the same query except the name), but the named query q2 isn't defined in has_child query xxx.

==== More ====

The version of elasticsearch is 2.0.0 Release.

**Comment by clintongormley** [comment]
It'd be much easier to answer your question if you provided a complete example demonstrating exactly what you're doing.

I've come up with my own example which demonstrates that it works correctly:

    PUT test 
    {
      "mappings": {
        "parent": {
          
        },
        "child": {
          "_parent": {
            "type": "parent"
          }
        }
      }
    }
    
    PUT test/parent/1
    {}
    
    PUT test/child/2?parent=1
    {
      "foo": "bar"
    }
    
    PUT test/child/3?parent=1
    {
      "foo": "baz"
    }
    
    PUT test/child/4?parent=1
    {
      "foo": "bar baz"
    }
    
    GET test/parent/_search
    {
      "query": {
        "bool": {
          "should": [
            {
              "has_child": {
                "type": "child",
                "inner_hits": {
                  "name": "bar"
                },
                "query": {
                  "match": {
                    "foo": "bar"
                  }
                }
              }
            },
            {
              "has_child": {
                "type": "child",
                "inner_hits": {
                  "name": "baz"
                },
                "query": {
                  "match": {
                    "foo": "baz"
                  }
                }
              }
            }
          ]
        }
      }
    }

**Comment by lipixun** [comment]
All right, here is a complete query which I sent to es:

```
{
    "query": {
        "bool": {
            "must": [
                {
                    "has_child": {
                        "query": {
                            "bool": {
                                "must": [
                                    {
                                        "match": {
                                            "text": {
                                                "operator": "and",
                                                "query": "avalue",
                                                "_name": "q1"
                                            }
                                        }
                                    },
                                    {
                                        "term": {
                                            "doc_type": {
                                                "value": "XXX"
                                            }
                                        }
                                    }
                                ]
                            }
                        },
                        "inner_hits": {
                            "highlight": {
                                "fields": {
                                    "text": {}
                                }
                            },
                            "name": "child1",
                            "size": 1
                        },
                        "type": "es_emr",
                        "_name": "child1"
                    }
                },
                {
                    "has_child": {
                        "query": {
                            "bool": {
                                "must": [
                                    {
                                        "match": {
                                            "text": {
                                                "operator": "and",
                                                "query": "avalue",
                                                "_name": "q2"
                                            }
                                        }
                                    },
                                    {
                                        "term": {
                                            "doc_type": {
                                                "value": "YYY"
                                            }
                                        }
                                    }
                                ]
                            }
                        },
                        "inner_hits": {
                            "highlight": {
                                "fields": {
                                    "text": {}
                                }
                            },
                            "name": "child2",
                            "size": 1
                        },
                        "type": "es_emr",
                        "_name": "child2"
                    }
                }
            ]
        }
    }
}
```

We have a document type es_emr which is the child document of es_visit and we are searching the es_visit by the above query.

It's obviously that the q1 and q2 are exactly the same query in this case, but they're searched with a different term query in each has_child query.

q1 is searched with doc_type == 'XXX' and q2 is searched with doc_type == 'YYY' and there's no way for the field doc_type to match both XXX and YYY in one document.

The strange thing I found is that I got matched query [ "q1", "q2" ] in child1, but q2 is not defined in child1.

**Comment by lipixun** [comment]
The returned es raw result:

```
"child1": {
	"hits": {
	    "hits": [
		{
		    "_type": "es_emr",
		    "_routing": "someid",
		    "_index": "indexname",
		    "_score": 4.782811,
		    "_source": { ... },
		    "_parent": "The parent id",
		    "highlight": {
			"text": [
			    ....
			]
		    },
		    "_id": "The document id",
		    "matched_queries": [
			"q1",
			"q2"
		    ]
		}
	    ],
	    "total": 1,
	    "max_score": 4.782811
	}
}
```

**Comment by clintongormley** [comment]
@lipixun you're really going to need to provide a full recreation so that I don't have to guess about anything and can just run it.
