### ISSUE TITLE
delete-by-query plugin usage inside a plugin

### ISSUE THREAD

**Issue by eliranmoyal** [elastic/elasticsearch#14585]
Hey,
I'm having trouble upgrading my plugin to support elasticsearch 2.0.0
The plugin used deleteByQuery so i referenced the delete-by-query from maven and everything compiled well. even worked on tests.

But, after installing the plugin , calling a function that used deletebyQuery caused an exception:
no_class_def_found_error
org/elasticsearch/action/deletebyquery/DeleteByQueryRequestBuilder

so I used maven-dependency-plugin with the copy goal and added the delete-by-query jar to my zip .
			```<artifactItem>
                                    <groupId>org.elasticsearch.plugin</groupId>
                                    <artifactId>delete-by-query</artifactId>
                                    <overWrite>true</overWrite>
                                    <outputDirectory>${project.build.directory}</outputDirectory>
                                    <destFileName>deleteByQuery.jar</destFileName>
                                </artifactItem>```

But now I'm getting the weirdest error:
org.elasticsearch.action.deletebyquery.DeleteByQueryRequest cannot be cast to org.elasticsearch.action.deletebyquery.DeleteByQueryRequest

when  calling .get() on DeleteByQueryRequestBuilder

Help please!

**Comment by s1monw** [comment]
this is not supported. Plugins can't depend on other plugins. the delete by query functionality is only available via the rest layer at this point. I will need to discuss this with others how we can make stuff like this work but at this point it's not supported

**Comment by eliranmoyal** [comment]
hey , I thought that on elastisearch5.0 this will work , but I'm still getting this error.
there is still no way for another plugin to use delete-by-query java api?

**Comment by nik9000** [comment]
> there is still no way for another plugin to use delete-by-query java api?

Right. We've not worked on this.
