### ISSUE TITLE
On Backup and Restore can I filter terms on Index?

### ISSUE THREAD

**Issue by tearsakura** [elastic/elasticsearch#14581]
Something like:

curl -XPUT 'http://xxxxxx:9200/_snapshot/20151106/snapshot_3' -d '{
  "indices": "metrics-*",
  "query": "env=pro",
  "ignore_unavailable": "true",
  "include_global_state": false
}'

**Comment by s1monw** [comment]
please use our discuss list for questions like this https://discuss.elastic.co/ this is only for feature requests and bugs. 

the answer to your question is no you can't
