### ISSUE TITLE
Connection refused after upgrading to elasticsearch-2.0

### ISSUE THREAD

**Issue by noamgal** [elastic/elasticsearch#14606]
Hi
After upgrading to elasticsearch-2.0 I'm failing to connect to the cluster.
When I do 
```
curl 'http://my-new-elasticsearch-dns:9200'
```
I get 
```
curl: (7) Failed to connect to my-new-elasticsearch-dns port 9200: Connection refused
```

If i do the same with some other elasticsearch cluster ver. 1.7.0 I get
```
{
  "status" : 200,
  "name" : "elasticsearch-node",
  "cluster_name" : "elasticsearch-cluster,
  "version" : {
    "number" : "1.7.0",
    "build_hash" : "929b9739cae115e73c346cb5f9a6f24ba735a743",
    "build_timestamp" : "2015-07-16T14:31:07Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

tried other actions such as ``` curl 'my-new-elasticsearch-dns:9200/_cat/indices/' ```
and got same failure result.

Also the cluster (one single node) is up, but having some problems with the log:
```
log4j:WARN No appenders could be found for logger (bootstrap).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
don't know how to fix that.

any help?
thanks,
Noam

**Comment by dadoonet** [comment]
Probably because you did not set network.host so it's bound to localhost only.

**Comment by noamgal** [comment]
@dadoonet 
Thanks, working.
Afaik it wasn't mandatory on elasticsearch 1.7.
Are there any more changes required for ever. 2.0.
If yes - where can I find the list of all things? thanks

**Comment by dadoonet** [comment]
In the breaking changes documentation I guess ?
