### ISSUE TITLE
function score gauss min score 

### ISSUE THREAD

**Issue by whybangbang** [elastic/elasticsearch#14613]
we have use es in many case,and gauss function is our love,but gauss function don't have the min score,if the score_mode is multiply(default) ,one score is zero,and the doc's score will be zero

**Comment by clintongormley** [comment]
@whybangbang I'm afraid I don't understand what you mean.  Perhaps an example will help? `min_score` is not per function, it is per function-score query

**Comment by whybangbang** [comment]
we don't know why time gauss function'score is 0 sometimes, 
for example(the example enlarge the problem )
  {
          "gauss": {
            "updated_at": {
              "origin": 2440060781,
              "scale": "172800"
            }
          }
        },

explain is 
{
"value": 0,
"description": "Function for field updated_at:",
"details": [
{
"value": 0,
"description": "exp(-0.5*pow(MIN[Math.max(Math.abs(1.44621567E9(=doc value) - 2.440060781E9(=origin))) - 0.0(=offset), 0)],2.0)/2.1539321544868954E10)"
}
]
}

gauss'score == 0 and this document ' score = 0

**Comment by shenzhun** [comment]
@clintongormley I guess @whybangbang means that does gauss function of ES have default value function, when the output score is 0, then default value could be used instead of 0.

**Comment by clintongormley** [comment]
@brwe can you shed any light on this?

**Comment by brwe** [comment]
The document is simply too far away from origin and hence the number is too small to fit into a float. That is why it is 0.
If I understand correctly you do not want the documents to be scored with 0 in that case? 
In that case you have to apply an additional filter to the function that only scores documents that are not too far away and another one that gives documents outside this range a "default" value. In you example this would mean something like:

```
{
  "query": {
    "function_score": {
      "functions": [
        {
          "filter": {
            "range": {
              "date": {
                "lt": 2440579181,
                "gt": 2439542381
              }
            }
          },
          "gauss": {
            "date": {
              "origin": 2440060781,
              "scale": 172800
            }
          }
        },
        {
          "filter": {
            "range": {
              "date": {
                "gte": 2440579181
              }
            }
          },
          "weight": 0.1
        },
        {
          "filter": {
            "range": {
              "date": {
                "lte": 2439542381
              }
            }
          },
          "weight": 0.1
        }
      ]
    }
  }
}
```

Let me know if that is what you meant.

**Comment by clintongormley** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by hartuvofir** [comment]
Hi!
We having the same problem (0 score of distance, and the doc's score will be zero)
what should we do?
