### ISSUE TITLE
[Ingest] Dealing with ingest load

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#14616]
Pipelines will have different performance characteristic depending on the number of processors, what processors have been configured and the type of documents are being enriched (a log or a complex document with many fields).

A pipeline should be able to use a different thread pool than the default ingest thread pool. Also it should be possible to run pipelines on specific nodes (or _not_ on specific nodes) based on node metadata.

**Comment by clintongormley** [comment]
Ingest processors now run on the index or bulk threads.
