### ISSUE TITLE
ElasticSearch index unix timestamp

### ISSUE THREAD

**Issue by RicherdLee** [elastic/elasticsearch#14615]
Hi team~
My data  containing a timestamp field whose value is an integer representing the number of seconds since epoch (php unix timestamp),like 1440494956
I've been reading ES docs and have found this:

http://www.elasticsearch.org/guide/reference/mapping/date-format.html

But it seems that if I want to submit unix timestamp and want them stored in a 'date' field (integer field is not useful for me) I have only two options:

Implement my own date format
Convert to a supported format at the sender

Is there any other option I missed?

Thanks!

**Comment by dadoonet** [comment]
Please post user questions on discuss.elastic.co. We can better help you there.

**Comment by clintongormley** [comment]
In 2.0, you can use `epoch_second`.  See https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_date_fields_and_unix_timestamps

**Comment by RicherdLee** [comment]
@dadoonet ,thanks ,I will post my questions on discuss.elastic.co next time.

**Comment by RicherdLee** [comment]
@clintongormley ,thanks for your help,it works for me
