### ISSUE TITLE
BulkProcessor should have OOB support for handling EsRejectedExecutionException

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#14620]
The [BulkProcessor](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/bulk/BulkProcessor.java) is handy wrapper around the bulk API. It aggregates incoming requests and sends them in one bulk once enough requests have been accumulated, or some time have passed. At the moment it passes any failures to the user via a listener. 

It would be great if have a default listener implementation that deals with EsRejectedExecutionException correctly - I.e., backs off for a while and retries.

**Comment by mikemccand** [comment]
+1

**Comment by jpountz** [comment]
+1

**Comment by ESamir** [comment]
+1

**Comment by s1monw** [comment]
+1

**Comment by danielmitterdorfer** [comment]
I'd like to tackle this. However, I have a couple of questions:

I have not understood why a listener is needed. Would it also be ok if we made `BulkProcessor` itself capable of backing off and retrying? I think this could simplify usage.

Btw, I have also two questions about this part of `BulkProcessor#execute()`:

```
} catch (InterruptedException e) {
    Thread.interrupted();
    listener.afterBulk(executionId, bulkRequest, e);
}
```

I think `Thread.interrupted()` should be `Thread.currentThread().interrupt()`. Also does it make sense to notify the listener of interruption (might make sense but the listener needs to be aware of this)?

**Comment by danielmitterdorfer** [comment]
Just as a quick update. I've extracted everything related to the handling of interrupts to a separate issue (see #14798).
