### ISSUE TITLE
Disruption rules in MockTransportService should match all bound addresses of a node

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#14625]
Currently, disruption rules apply only to the main bound address of a node. As consequence, integration tests that use Network Partitions must currently ensure that nodes are bound to a single local interface (e.g. 127.0.0.1 / IPv4) in order to correctly work. This is ugly as it requires setting `network.host` explicitly to `127.0.0.1` in all such tests.

Implementation details:
UnicastZenPing creates fake DiscoveryNode for each local network interface. If multiple interfaces are active, it creates one for IPv4 and one for IPv6 for each node. To add disruptions, MockTransportService provides methods that take as parameter a node to disrupt, but this only adds disruptions rules that match on the main bound address `DiscoveryNode.address()` of the node. This means that no rules exist to intercept connections trough other bound addresses.

Solution:
Disruption rules in MockTransportService should match all bound addresses of a node.

As future enhancement, the interface of MockTransportService / NetworkPartition could also be expanded so that disruptions can be specified directly on a per TransportAddress level. This provides more fine-granular testing possibilities (where connection over one interface works but the other not).

**Comment by bleskes** [comment]
Thanks for digging @ywelsch . Makes sense.
