### ISSUE TITLE
Timeout waiting for connection from pool

### ISSUE THREAD

**Issue by xuzha** [elastic/elasticsearch#14633]
We have a few Found customers met this issue, and has the following error log: 
```
Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: Timeout waiting for connection from pool
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:473)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:297)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3672)
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1079)
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1042)
```
I suspect this is because `repository-s3` plugin doesn't close s3 objects. According to the [AWS SDK document] 
(http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3.html#getObject(com.amazonaws.services.s3.model.GetObjectRequest)), we should execute `object.close()` in order to liberate that connection. `S3Object` opens a connection for each object. That are not liberated even if the object is garbage collected.

**Comment by dadoonet** [comment]
@xuzha I totally agree with your findings.

**Comment by dadoonet** [comment]
I looked at the code but apparently there is no real way today to close the `S3Object`. Actually `BlobContainer` interface needs an `InputStream` with:

```java
    /**
     * Creates a new InputStream for the given blob name
     */
    InputStream readBlob(String blobName) throws IOException;
```

When we use it for example in BlobStoreRepository class we call:

```java
    /**
     * Reads snapshot index file
     * <p>
     * This file can be used by read-only repositories that are unable to list files in the repository
     *
     * @return list of snapshots in the repository
     * @throws IOException I/O errors
     */
    protected List<SnapshotId> readSnapshotList() throws IOException {
        try (InputStream blob = snapshotsBlobContainer.readBlob(SNAPSHOTS_FILE)) {
            BytesStreamOutput out = new BytesStreamOutput();
            Streams.copy(blob, out);
            ArrayList<SnapshotId> snapshots = new ArrayList<>();
            try (XContentParser parser = XContentHelper.createParser(out.bytes())) {
                if (parser.nextToken() == XContentParser.Token.START_OBJECT) {
                    if (parser.nextToken() == XContentParser.Token.FIELD_NAME) {
                        String currentFieldName = parser.currentName();
                        if ("snapshots".equals(currentFieldName)) {
                            if (parser.nextToken() == XContentParser.Token.START_ARRAY) {
                                while (parser.nextToken() != XContentParser.Token.END_ARRAY) {
                                    snapshots.add(new SnapshotId(repositoryName, parser.text()));
                                }
                            }
                        }
                    }
                }
            }
            return Collections.unmodifiableList(snapshots);
        }
    }
```

There is no way here to call `S3Object#close`. I think we should may be add a `closeInputStream()` method or something like this in `BlobContainer` interface. @imotov WDYT?

**Comment by xuzha** [comment]
@dadoonet I took another look this morning

I think this is fine in master, in `Streams.copy(blob, out)` we do close inputstream after use. `S3object.close()` is just close the `inputstream`, so I think this issue is fine in 3.0.

But in 2.x and 2.1 `google.common.io.ByteStreams` do not close the streams. That are not liberated after `readSnapshotList()`

**Comment by dadoonet** [comment]
Interesting. Indeed we found with @imotov today when looking at the code that calling actually `S3object.close()` is useless and won't fix the issue but we did not look at 2.x branch I guess! Awesome. Do you think you'll have time for a PR or do you want me to look at it on tuesday?

**Comment by xuzha** [comment]
Thanks @dadoonet, I could make a PR for this later today.

**Comment by xuzha** [comment]
@dadoonet, we do close the stream in 2.x,  within the `try {}` block. 

I double checked. This should be a false alarm. I'm sorry, closing the issue.
