### ISSUE TITLE
bin/kibana plugin --install marvel --url [url] unable to validate cert path for local https

### ISSUE THREAD

**Issue by robertsmarty** [elastic/elasticsearch#14638]
Hi,

Our deployment automation has an internal repo for all elasticsearch related artifacts. I'm currently receiving...

Error: self signed certificate in certificate chain
Plugin installation was unsuccessful due to error "Not a valid url."

when accessing this internal repo over https. Is there any way to configure a trust store for kibana plugin downloads?

This is similar to https://github.com/elastic/elasticsearch/issues/14373 which has been resolved however I'm not sure how to get around this one due to kibana not being a java app.

**Comment by dadoonet** [comment]
Could you open this in kibana github repository ?
