### ISSUE TITLE
Output test failure log to a file

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#14649]
When running the test suite I sometimes put the output into a file, so I can grep / less it later. Here is what I tried to do with the new gradle build:

```
gradle test integTest > ~/test.txt
```

Sadly, the test file only contains the fact that a test failed, but not the log output nor the reproduction line.

```
Tests with failures:
  - org.elasticsearch.recovery.RecoveryWhileUnderLoadIT.testRecoverWhileRelocating
```

Please educate me if I'm doing this wrong. O.w. it would be great if we can come up with a way to do this.

**Comment by rjernst** [comment]
@bleskes Have you tried redirecting stdout and stderr? Gradle outputs its stuff to stderr (this is why tasks can do `println` and the output is not caught). It should detect the output is not to a terminal and omit the progress line.

**Comment by rmuir** [comment]
I think its confusing too though fwiw, i expect stdout to go to stdout. is it possible to not use gradle logging here?

**Comment by rjernst** [comment]
AFAIK, gradle logging goes to stderr (or maybe it is error logs go to stderr and info logs go to stdout?). I'll do some more testing to see for sure..

**Comment by rmuir** [comment]
but can we skip gradle logging all together and just send it directly to stdout?

**Comment by bleskes** [comment]
the screen is long gone, but if memory serves, there was indeed some gradle output there but not the failed logs...

**Comment by rjernst** [comment]
@bleskes Are you saying the test file only had that single summary statement of the test failures, and your screen had nothing else for tests at all?

**Comment by bleskes** [comment]
@rjernst It had more things like the test summary (so many tests run etc.), but nothing about the failure (it had the stalled test messages)

**Comment by rjernst** [comment]
@bleskes I ran the same command in core as you, with an fake error in that test. The only difference being I captured both stderr and stdout.
https://gist.github.com/rjernst/e412ec16001e6acf6141

When I run the same command as you, I see the actual error go to my console still (including the repro line). So, the answer to this issue is, you need to capture both stderr and stdout. Without the ability to reproduce what you saw, I don't know what else to do here.

**Comment by bleskes** [comment]
Thanks @rjernst for taking a look. I'll try that and reopen the issue if something doesn't work.
