### ISSUE TITLE
Problematic numbers using regex for numeric fields

### ISSUE THREAD

**Issue by Robitx** [elastic/elasticsearch#14648]
Using regex query for a numeric field (eg. long type) fails for certain numbers (eg. 34).
 
{"query":{"query_string":{"query":"some_numeric_field:/34/"}}}

Non regex query works fine.

{"query":{"query_string":{"query":"some_numeric_field:34"}}}

It might be connected to ASCII (34 is ").

**Comment by clintongormley** [comment]
Nice catch :)

You can't use the regexp query on numeric fields.  I've opened https://github.com/elastic/elasticsearch/issues/14782 to improve the exception
