### ISSUE TITLE
Sum aggregation hangs on a random shard

### ISSUE THREAD

**Issue by SHSE** [elastic/elasticsearch#14657]
The aggregation query stucks on a random shard (different each time we restart the cluster). There is no errors in logs. It just doesn't return anything (hanging until you close connection).

BUT, if you replace `field: foo` by `script: doc['foo'].value` everything works fine.

Iterating over the shards (settings `preference=_shards:X`) show that the query hangs only on one particular shard.

ElasticSearch Version: 1.7.4
Number of documents: 11
Mapping: 
```json
"foo": {
  "index": "not_analyzed",
  "norms": {
     "enabled": false
  },
  "doc_values": true,
  "type": "integer"
}
```
Query:
```json
{
   "query": { // some query which returns ZERO documents },
   "aggs": {
      "broken_sum": { "sum": { "field": "foo" } }
   }
}
```

**Comment by SHSE** [comment]
It looks like the reason was `mlockall = true` and two ElasticSearch instances per host. 

After setting `mlockall` to `false` everything works fine.

**Comment by clintongormley** [comment]
That sounds like you are trying to assign too much heap to each Elasticsearch instance.  Disabling mlockall will cause severe problems with slow garbage collection later on.

**Comment by SHSE** [comment]
@clintongormley the server has 256 GB RAM and the `ES_HEAP_SIZE` is set to 30GB.
