### ISSUE TITLE
`copy_to` does not work for nested objects

### ISSUE THREAD

**Issue by EECOLOR** [elastic/elasticsearch#14659]
I am trying to copy a field from the parent object into a nested object in order to perform a filtered sort. This however seems to have no effect.

A complete description can be found here: http://stackoverflow.com/questions/33618467/how-to-add-properties-from-a-root-object-in-a-nested-object-for-sorting

**Comment by clintongormley** [comment]
Hiya

I understand your use case (took a while to figure out). I don't think we should add functionality to copy_to every nested doc, or allow access to the parent doc during sorting.  I think the right solution here is to just add the parent field to each nested document before indexing.
