### ISSUE TITLE
Migrate elasticsearch-native-script-example to the main repo

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#14662]
I am currently maintaining a separate project that demonstrates how to build different native scripts for [elasticsearch-native-script-example](https://github.com/imotov/elasticsearch-native-script-example). I think it would make sense to add this project to the main repo similarly to [jvm-example](https://github.com/elastic/elasticsearch/tree/master/plugins/jvm-example). We just need to makes sure that the added project (as well as jvm-example itself) can be built as a stand-alone project.

**Comment by dadoonet** [comment]
++

**Comment by imotov** [comment]
See discussion in #19334.
