### ISSUE TITLE
Category completion suggestion -- support "and" instead of "or"

### ISSUE THREAD

**Issue by rcoh** [elastic/elasticsearch#14664]
Currently if you have a completion context mapping defined, you can search for mappings that fall into `category_a` OR `category_b`, eg. `red` or `blue`
```
....
    "context": {
                "color": ["red", "blue"]
            }
```
However, I want to be able to find keys that are both `red` _and_ `blue`. Is there something fundamentally different about this, or is it a relatively simple change?

**Comment by rcoh** [comment]
Nevermind, turns out you can do:
```
{ 
  "color": "red",
  "color": "blue"
}
``` 
and it works! a bit surprising, but I'm not complaining :-)

**Comment by clintongormley** [comment]
Hi @rcoh 

> Is there something fundamentally different about this, or is it a relatively simple change?

There is something fundamentally different about this: a context is basically added as a prefix to all the suggestions in that context, so the only way to do "and" is to combine both tags into a single tag (and thus a single prefix), something you can do manually yourself: 

    color: ["red", "blue", "blue_red"]

**Comment by rcoh** [comment]
Also, is the FST per shard or is it global for the index?

**Comment by areek** [comment]
> Interesting. Does that mean having a context with a high cardinality is potentially very inefficient?

Yes the higher the cardinality of (index-time) contexts the more inefficient the FST becomes in terms of memory. Using multiple contexts at query-time will not have a significant impact on query performance.

> Also, is the FST per shard or is it global for the index?

FST is a shard-level data structure.
