### ISSUE TITLE
remove hacks in 2.1 branch fixed by lucene 5.3.1

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#14673]
Followup to https://github.com/elastic/elasticsearch/pull/14669

There is a TODO in IndexShard.java that should be dealt with (I think its a workaround for some bad behavior of caching around MatchAllDocsQuery that is fixed in this 5.3.1 upgrade)

**For the future, I would greatly prefer if we did not add version-based asserts to IndexShard.java like this** 

This class masks all exceptions completely, so nobody ever sees your assert. Instead all tests hang, and when they finally fail its just stuff like "expected: GREEN, got: YELLOW" which does not help the guy trying to do the upgrade.

See #13319 for more information about that.

**Comment by rmuir** [comment]
I marked this as a blocker, i think its a better solution than adding those asserts? This way, the cleanup still takes place, but its easier since you can iterate (e.g. upgrade lucene, without having to also make a bunch of other scary changes all at once, just to make tests pass)

**Comment by jpountz** [comment]
Closed via #14797
