### ISSUE TITLE
Shard relocation happens while cluster is yellow

### ISSUE THREAD

**Issue by masaruh** [elastic/elasticsearch#14670]
This is _cluster/health output after one of nodes restarted:

```
{
  "cluster_name" : "<cluster_name>",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 14,
  "number_of_data_nodes" : 10,
  "active_primary_shards" : 1022,
  "active_shards" : 1839,
  "relocating_shards" : 2,
  "initializing_shards" : 0,
  "unassigned_shards" : 205,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0
}
```

It says cluster is in `yellow` status but it is relocating shards.
This cluster doesn't have custom `cluster.routing.allocation.allow_rebalance` configuration. So, it should be using `indices_all_active`.

No relocation should happen in this case?

**Comment by dakrone** [comment]
@masaruh all the shards have initialized, so there isn't a reason why relocation wouldn't be allowed. Also, just because the cluster is yellow doesn't mean that the particular index relocating isn't green?

**Comment by masaruh** [comment]
All primaries have initialized but not all shards are, right?

It says:
```
        /**
         * Re-balancing is allowed only once all shards on all indices are active. 
         */
        INDICES_ALL_ACTIVE;
```

I expect relocation happens only when cluster state is green.

**Comment by dakrone** [comment]
@masaruh ahh okay, I see what you are saying, my mistake for misinterpreting it :)
