### ISSUE TITLE
Watcher/License plugins killed Elasticsearch cluster

### ISSUE THREAD

**Issue by rhealitycheck** [elastic/elasticsearch#14686]
So we've been having issues with watcher, which we installed to test out alerting on our Staging cluster. And this week we've had our Staging cluster completely die, unable to connect to any master node for longer than 5 mins at a time. Looking through the logs we found:

    [2015-11-10 16:48:28,531][INFO ][license.plugin.core      ] [CHIVLXSTG045] license for [watcher] - valid
    [2015-11-10 16:48:28,536][ERROR][watcher.license          ] [CHIVLXSTG045]
    #
    # Watcher license will expire on [Wednesday, December 09, 2015]. All configured actions on
    # all registered watches are throttled (not executed) on Watcher license expiration.
    # Watches will continue be evaluated and watch history will continue being recorded.
    # Have a new license? please update it. Otherwise, please reach out to your support contact.
    #

But this shouldn't be an issue for a month, however uninstalling the watcher and license plugins allowed the cluster to get back to a healthy state. Seems like this is a pretty large bug.

**Comment by clintongormley** [comment]
Hi @rhealitycheck 

That message is normal when you have an autogenerated license, and shouldn't affect anything else until it actually expires.  It is just telling you that your trial license will expire on that date, and what will happen once it expires.

I think you have another issue going on.  Any other details?

**Comment by rhealitycheck** [comment]
The only error messages we received was that a master node could not be found. There were no errors in the data nodes' logs. Our client nodes couldn't connect to the data nodes because a master could not be found. You could not query directly to the cluster because a master could not be found all the while in the logs you could see a master had been elected. The cluster returned to a normal state after uninstallinge the license plug-in with no other changes made to the cluster.

**Comment by clintongormley** [comment]
Are you sure you had the license plugin installed on all nodes (including client nodes)?

**Comment by rhealitycheck** [comment]
I'm pretty sure we had it on all nodes but I honestly don't remember right now. The strangest part of this behavior was that we had the Watcher and License plugins installed for about a month and a half after which we saw this strange behavior.

**Comment by clintongormley** [comment]
Either you should have seen it immediately, or after one month, no?  Something else must have changed.  I wonder if another node joined the cluster without the license plugin?

**Comment by rhealitycheck** [comment]
So this would be expected if the license plugin was not installed on a node that joined the cluster but as long as all of them have the plugin it should be fine, correct? I can try and replicate and see if the issue is reproduced if we have it installed on all nodes.

**Comment by clintongormley** [comment]
@rhealitycheck i think so.  See https://github.com/elastic/elasticsearch/issues/13445 for more

**Comment by rhealitycheck** [comment]
Sure I'll try to reproduce. 

But just to be clear none of the data nodes had issues joining to the cluster unlike #13445, so I find it strange that even directly querying those nodes returned that no master was available. I can see how the client nodes wouldn't be able to talk to the data nodes if they didn't have it installed but for the entire cluster to be unresponsive seems extreme.

**Comment by clintongormley** [comment]
@rhealitycheck sure, which is why i think that this is a red herring and there is something else at play.  perhaps another trawl through the logs, esp for stack traces?

**Comment by clintongormley** [comment]
No further feedback. Closing
