### ISSUE TITLE
Ordering aggregation buckets by script

### ISSUE THREAD

**Issue by antmat** [elastic/elasticsearch#14680]
Hi!
It would be great if we can order aggregation buckets by some sort of scripting, because it seems, that metric aggregation is not enough. My case is - I need to group documents by buckets, then determine in each bucket maximum and minimum timestamp and sort buckets by this difference. I could manage to do it if substract min aggregation result from max_aggregation result or even using 0 and 100 percentile, but it seems that now it is impossible.
Thanks in advance!

**Comment by AlexMiroshnikov** [comment]
+1, I find it useful too.

**Comment by jpountz** [comment]
I'm a bit on the fence as such a feature would increase the accuracy issues of the terms aggregations. Maybe we should consider only keeping the ability to sort by term or doc count on the terms aggregation and then deal about all other sort options with pipeline aggregations. I think the would make the trade-off clearer? (ie. terms are selected first and only sorted afterwards)

**Comment by thao6626** [comment]
+1, sometimes, we need the value of the bucket_script in pipeline aggregations, and also,we need to sort the value

**Comment by clintongormley** [comment]
Closing in favour of #14928
