### ISSUE TITLE
lang-javascript plugin cannot find script files on Ubuntu

### ISSUE THREAD

**Issue by BorisKozo** [elastic/elasticsearch#14683]
I am trying to run a script from a file within a query and get the following error:
````ElasticsearchIllegalArgumentException[Unable to find on disk script my_script];````

I have the file my_script.js in the scripts directory. If I change the lang to groovy and create a file called my_script.groovy the query works as expected.

The same query works fine on a windows machine with lang='js'.

I tried changing the file extension to .javascript and the lang to javascript but get the same error.

````
              "estimated_cost": {
                "sum": {
                  "field": "estimated_cost",
                    "script_file": "my_script",
                    "lang": "js",
                    "params":{
                        "time_column":"calendar_time"
                    }
                }
````

I am using ElasticSearch 1.7.3 with the 2.7.0 plugin.

As a sidenote it would be great if the exception would actually write the full path to the actual file it tries to find.

**Comment by clintongormley** [comment]
It is likely that you have a compilation error, which you can see in your log file.

**Comment by BorisKozo** [comment]
Well, clearly you ignored the statement that the same query (obviously with the same file!) works on my Windows machine.

But I worked around the problem by sending the script with a POST statement which allows me to use the script ID in the query. Needless to say I sent the content of the exact same file you claim to have a compilation error.

**Comment by clintongormley** [comment]
@BorisKozo i did miss that.  But is there anything in the logs?  It should try to compile the script when you start ES, and will throw an exception if it was unable to do so.

**Comment by BorisKozo** [comment]
The log only has the error I pasted in my original post.

**Comment by clintongormley** [comment]
Something is weird then, because I tried it out on 1.7.3 and it worked just fine for me.  Any more info you can provide to debug this? Are you using a package instead of the zip? Any other settings?

**Comment by BorisKozo** [comment]
I think you were right in the first place.
There was something wrong with the file. I deleted the entire content and replaced with just return 0; and it worked. 
I cannot figure out what was wrong with it, maybe some line ending issue moving it from Windows to Linux. 

In any case I am sticking with the script_id way for now.

Thanks for your help.

**Comment by clintongormley** [comment]
thanks for letting us know
