### ISSUE TITLE
Master can get stuck AsyncFetching forever

### ISSUE THREAD

**Issue by jolynch** [elastic/elasticsearch#14697]
While trying to upgrade our clusters to 1.7.3 I came across a fun issue with the async shard fetch mechanism, namely that the [cache](https://github.com/elastic/elasticsearch/blob/05d4530971ef0ea46d0f4fa6ee64dbc8df659682/src/main/java/org/elasticsearch/gateway/AsyncShardFetch.java#L64) can get poisoned by nodes that change IDs. The basic issue is that [``processAsyncFetch``](https://github.com/elastic/elasticsearch/blob/05d4530971ef0ea46d0f4fa6ee64dbc8df659682/src/main/java/org/elasticsearch/gateway/AsyncShardFetch.java#L270) passes ``response.getNodes()`` instead of ``nodesIds``. This means that if the master thinks it is talking to node 1234 and the response comes back with "I'm node 3456" we [continue](https://github.com/elastic/elasticsearch/blob/05d4530971ef0ea46d0f4fa6ee64dbc8df659682/src/main/java/org/elasticsearch/gateway/AsyncShardFetch.java#L178) and poison the cache in the process as the master will never get a response from node 1234.

Nodes should never change IDs, but I think they actually can when they first start up because of something like [LocalDiscovery](https://github.com/elastic/elasticsearch/blob/05d4530971ef0ea46d0f4fa6ee64dbc8df659682/src/main/java/org/elasticsearch/discovery/local/LocalDiscovery.java#L110-L111) which sets the localNode to one name and then [InternalClusterService](https://github.com/elastic/elasticsearch/blob/05d4530971ef0ea46d0f4fa6ee64dbc8df659682/src/main/java/org/elasticsearch/cluster/service/InternalClusterService.java#L162-L163) sets it to something different. More generally it seems like one node shouldn't trust that it will get a response back from a node with the same ID that it sent to (I can't actually come up with a real world situation where the node both is still in the cluster and the id changes ... but ...). My understanding of Zen is that this can't happen (and nodes really _shouldn't_ ever change IDs) but if they do the master gets a poisoned cache and it will be stuck forever in [fetchData](https://github.com/elastic/elasticsearch/blob/05d4530971ef0ea46d0f4fa6ee64dbc8df659682/src/main/java/org/elasticsearch/gateway/AsyncShardFetch.java#L121).

I think that passing the ``nodesIds`` instead of ``response.getNodes()`` is not a particularly good solution because it defends against something that should never happen, but it does seem like a [NodeEntry](https://github.com/elastic/elasticsearch/blob/05d4530971ef0ea46d0f4fa6ee64dbc8df659682/src/main/java/org/elasticsearch/gateway/AsyncShardFetch.java#L333) "fetching" state really should expire after some amount of time to be robust. If I were to submit a PR that expired the async fetch cache after 20s or added some equivalent bookeeping, would you be opposed to that?

**Comment by bleskes** [comment]
Answering in another order:

> Nodes should never change IDs

Node ids actually change all the time. You can think of a node ID as an equivalent of a process id - every time the node is restarted and we have a new process, the id changes and the node joins the cluster again. This allows us to make sure that network connections are re-opened to the node etc.


> I think that passing the nodesIds instead of response.getNodes() is not a particularly good solution because it defends against something that should never happen, 

We are making sure that we use the information based on where it come from, not where we thought we sent it to. I think this is safer.

> and poison the cache in the process as the master will never get a response from node 1234.

It's true that we do not populate the cache with the response and we keep on waiting for an answer from 1234. However, the [node fault detection will discover that a new node was started on the same port](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/discovery/zen/fd/NodesFaultDetection.java#L245) and will remove the node from the cluster. At the point the cache is [cleaned](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/gateway/AsyncShardFetch.java#L234) and the master will nog longer wait for a response. 

> While trying to upgrade our clusters to 1.7.3 I came across a fun issue with the async shard fetch 

Do you have any more information about what you saw? Logs or similar will be great.

**Comment by bleskes** [comment]
> That being said I can conceive of fun network partitions that could maybe make it possible, and it's pretty simple to make the async shard fetch mechanism as robust to such issues as the sync method was before so why not.

Looking forward to a PR :)

>  (note the "ignoring already fetching" lines):

I think that this is just working as we discussed/designed? If so, can we close the ticket?

**Comment by jolynch** [comment]
Sure thing, and I can work on a PR if you think it's worth having some kind of expiration mechanism. I'm also fine with saying "this shouldn't happen and if it does it's a bug elsewhere". Either way feel free to close this, thank you for the feedback!

**Comment by bleskes** [comment]
yeah, I don't think an expiration mechanism is something to add here. We already have the node FD pinging from the same node. Closing for now then. Thanks!
