### ISSUE TITLE
Support Accessing Parent Document Values in Aggregations from Scripts

### ISSUE THREAD

**Issue by gingerwizard** [elastic/elasticsearch#14692]
Provide the ability to access values from parent documents in child aggregations, specifically in aggregation scripts.

**Comment by gingerwizard** [comment]
@colings86 used to track the work we discussed.

**Comment by jpountz** [comment]
I'm having trouble understanding how such a feature could be implemented in a scalable way.

**Comment by clintongormley** [comment]
Yeah, this just doesn't sound doable in any way that doesn't suck. 

Still difficult but at least within the realms of possibility would be a `parent` aggregation: https://github.com/elastic/elasticsearch/issues/14692
