### ISSUE TITLE
real numbers from aggregation ?

### ISSUE THREAD

**Issue by sonenko** [elastic/elasticsearch#14708]
Hello guys.
A. Is there any way to fetch real numbers from aggregations (terms, cardinality) ?
At moment we have have almost 3 000 000 flat records and aggregated values with relative error.

B. how can I apply LIMIT(from, to) to aggregation? It possible for plain query, But I was not able to do that with aggregations.

Thanks.

**Comment by clintongormley** [comment]
Hi @sonenko 

Please use the forums to ask questions like these: http://discuss.elastic.co/
