### ISSUE TITLE
Documentation issue in License management section

### ISSUE THREAD

**Issue by tarunsapra** [elastic/elasticsearch#14709]
In the license management section, 
https://www.elastic.co/guide/en/shield/current/license-management.html

The curl request given as example is -
curl -XPUT -u admin 'http://[host]:[port]/_license?acknowledge=true' -d @license.json

The index name used is *license* it should have been *licenses* instead. It's a small typo but can be frustrating for someone starting new with ELK stack.

**Comment by clintongormley** [comment]
Hi @tarunsapra 

In 1.x, it used to be `PUT /_licenses` but in 2.0 it is `PUT /_license`
