### ISSUE TITLE
geo_shape contains support

### ISSUE THREAD

**Issue by bogensberger** [elastic/elasticsearch#14713]
In elasticsearch the relation between a query shape and an indexed shape can be `within`, `intersect` or `disjoint`. The underlying lucene would also support `contains`:
https://lucene.apache.org/core/5_3_1/spatial3d/org/apache/lucene/geo3d/GeoArea.html

Are there some special reasons why `contains` is not supported yet or was it just omitted because it's not important for the most usecases? I would appreciate the possibility to use the `contains` relation.

**Comment by nknize** [comment]
Hi @bogensberger,

Thanks for the question. A few points to help answer your question:
* ES doesn't currently use the spatial3d package as its performance is not yet ready for integration.
* Lucene spatial now supports ```CONTAINS``` and it is extremely low hanging fruit to add. So I'll actually open a PR shortly to add this functionality to 2.2+.
