### ISSUE TITLE
[Before 2.0.0] QueryParsingException - not of nested type

### ISSUE THREAD

**Issue by JustinHook** [elastic/elasticsearch#14714]
The below steps cause a query to fail with a `QueryParsingException` that seems to be fixed by either restarting elasticsearch or reindexing the data.

I've tested on all versions from 1.4.2 to 2.0.0. Only on version 2.0.0 does step 4 not throw an exception.

**1. Create mappings (2 nested fields)**
```
curl -XPOST 'http://127.0.0.1:9200/product' -d '
{
  "mappings": {
    "release": {
      "properties": {
        "formats": {
          "type": "nested",
          "properties": {
            "format_id": {
              "type": "integer"
            }
          }
        },
        "prices": {
          "type": "nested",
          "properties": {
            "supplier_short_name": {
              "type": "string",
              "index": "not_analyzed"
            }
          }
        }
      }
    }
  }
}'
```
`{"acknowledged":true}`

**2. Insert document**
```
curl -XPUT 'http://127.0.0.1:9200/product/release/MUS-REL-0003017001' -d '
{
    "formats": [
        {
            "format_id": 17
        }
    ],
    "prices": [
        {
            "supplier_short_name": "digital"
        }
    ]
}'
```
`{"_index":"product","_type":"release","_id":"MUS-REL-0003017001","_version":1,"created":true}`

**3. Try to update nested `formats` field with a string**
Update will fail which is expected as we are trying to update a nested field with a string.
```
curl -XPOST 'http://127.0.0.1:9200/product/release/MUS-REL-0003017001/_update' -d '
{
  "doc": {
    "formats": "MP3 320",
    "prices": [
      {
        "supplier_short_name": "digital"
      }
    ]
  }
}'
```
`MapperParsingException[object mapping for [release] tried to parse as object, but got EOF, has a concrete value been provided to it?]`

**4. Run the query**
Step 3 causes this query to fail which is not expected. To get the query to run you can restart elasticsearch or reindex the data.
```
curl -XPOST 'http://127.0.0.1:9200/product/release/_search' -d '
{
  "query": {
    "filtered": {
      "filter": {
        "and": [
          {
            "nested": {
              "path": "prices",
              "filter": {
                "and": [
                  {
                    "exists": {
                      "field": "prices"
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}'
```

`nested: QueryParsingException[[product] [nested] nested object under path [prices] is not of nested type]`

**Comment by clintongormley** [comment]
Hi @JustinHook 

Yes, this is a bug in the mappings.  Unfortunately, it is a really hard one to fix in 1.x  A lot of the changes in 2.0 were about cleaning up this kind of stuff.

We wouldn't be able to fix this in 1.x without backporting half of 2.0, so I'm going to close this as won't fix.

thanks for the good recreation
