### ISSUE TITLE
url params parsing should not be lenient

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#14719]
If you use eg the `_analyze` api, and mispell the `tokenizer`, it will happily go on using the standard *analyzer* (if you have filters specified, it will ignore them as well).

We should remove all leniency from url param parsing, it does not help anyone, but only causes confusion. Rest actions should remove parameters as they are parsed, and fail when there are extras left (eg `Unknown parameter "tokenzier" for _analyze`)

**Comment by dadoonet** [comment]
++

**Comment by martinstuga** [comment]
I would be happy to implement this change.

May I go ahead?

**Comment by rjernst** [comment]
@martinstuga Please do! Note that it is a large task. It means handling every rest handler (although doing in a series of smaller PRs would be just fine and easier to review).

**Comment by martinstuga** [comment]
This validation must be implemented on every single RestHandler?

I think that we can do it on a generic and less error prone way by checking if all passed params are used in the handleRequest method. Sounds good?

**Comment by rjernst** [comment]
Yes, what I mean is, right now I believe each reat handler just does a get on the params they use. They will need to do a remove, and then have a check at the end (in shared code) that there are no params left.

**Comment by martinstuga** [comment]
I think there is a way to do everything with shared code. I'll implement it and then you check if it's correct.
Ok?

**Comment by rjernst** [comment]
Sure, please do.

**Comment by martinstuga** [comment]
I have a few questions, in the case there're wrong parameters, which behaviour should we implement?

Throw an Exception?
Send a warning message in the response?

In order to keep backward compatibility, don't you think we should add an parameter to enable/disable this feature?

**Comment by nik9000** [comment]
> Throw an Exception?

Yes. Make sure the exception is translated into a 400 level error.

> In order to keep backward compatibility, don't you think we should add an parameter to enable/disable this feature?

Do it in master and add it to the breaking changes list I think. I'm not personally a huge fan of silently ignoring parameters even in 2.x but I think it'd be quite uncontroversial to do it in 3.0.

**Comment by martinstuga** [comment]
I've already created a PR just with the validation do GET rest requests.
Please, validate if everything is OK and let me know.

Thanks.

**Comment by martinstuga** [comment]
Please, anybody can give me some feedback about the PR #15323?

I'm waiting for this feedback to ahead with the other rest services (PUT, DELETE,...)

Thanks.
