### ISSUE TITLE
memory leak in tribe node

### ISSUE THREAD

**Issue by yanjunh** [elastic/elasticsearch#14725]
This happens when incoming documents have inconsistent type that causes replica shard allocation failure. While the cluster keeps trying to allocate the failed shards, tribe node memory usage grows unbounded. Eventually GC can't reclaim any space and tribe node hangs.  

![image](https://cloud.githubusercontent.com/assets/1834562/11138364/f5202b74-8975-11e5-80e1-f610ee3a15cc.png)

**Comment by bleskes** [comment]
Thank for reporting.

>  causes replica shard allocation failure

Can you clarify some more about actually fails?

Any chance you can share a heap dump of the tribe node? you can reach me privately on first name at elastic.co

**Comment by yanjunh** [comment]
The failure is [cluster.action.shard     ]. Here is part of the log message 

at[2015-11-12T17:03:45.861Z], details[Failed to perform [indices:data/write/bulk[s]] on replica, message [RemoteTransportException[[elk][inet[/10.29.22.33:9300]][indices:data/write/bulk[s][r]]]; nested: IllegalArgumentException[cannot change DocValues type from SORTED_NUMERIC to SORTED_SET for field "msg_.log_events.sql_query_args"]; ]]]
The cluster keeps trying to assign the shard, fail and then try to assign it again.

I took a heap histogram. there are large number of org.elasticsearch.cluster.routing.MutableShardRouting and it's super class ImmutableShardRouting. I suspect that large number of MutableShardRouting objects were created due to shard allocation thrashing. After we fixed the shard allocation thrashing, the tribe node heap usage eventually dropped. Seems there is a cleanup thread somewhere to remove reference to these object so GC can reclaim the space eventually. But when the heap is completely full, the cleanup thread can't run and the process hangs. Interestingly, this only affects tribe nodes. This is just a guess, I havent got time to trace deep into the code.


num     #instances         #bytes  class name
----------------------------------------------
   1:        301316     2863097560  [B
   2:      58282801     2373602544  [Ljava.lang.Object;
   3:      30699477     2210362344  org.elasticsearch.cluster.routing.MutableShardRouting
   4:      84192914     2020629936  org.elasticsearch.common.collect.SingletonImmutableList
   5:      29040738     1847249696  [C
   6:      26343947     1686012608  org.elasticsearch.cluster.routing.ImmutableShardRouting
   7:      40972736     1311127552  org.elasticsearch.common.collect.RegularImmutableList
   8:      44864300     1076743200  org.elasticsearch.index.shard.ShardId
   9:      13255026      848321664  org.elasticsearch.cluster.routing.IndexShardRoutingTable
  10:      44864300      717828800  org.elasticsearch.index.Index

**Comment by bleskes** [comment]
I see thanks. The shard issues caused many clusters state to be published (with each failure and allocation). The tribe node at the moment doesn't have batching support when processing the changes and it seems the cluster state just piled up waiting to be processed. We are working to add batch (see #13627). Normal nodes have this already. 

I'm going to close this as it seems to be already covered by the PR I referenced.

**Comment by yanjunh** [comment]
Cool. Thanks! I will take a look at the diff, just for my education.
