### ISSUE TITLE
Gradle should check for jarhell of test classpath before running tests

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#14721]
When we have jarhell in tests, we get the jarhell exception for the first class that was run, and then often class not found for every other suite (because we did not load the given jar). We could make this a little nicer, and easier to notice, by having a gradle task call JarHell independently before running test (as a final dependsOn for the test task). It would have the exact classpath the test would use.

**Comment by rmuir** [comment]
+1, it has a main method for this.
