### ISSUE TITLE
spatial_stats aggregation

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#14727]
This feature intends to add a `spatial_stats` metric aggregator designed for computing the most basic descriptive statistics for Exploratory Spatial Data Analysis. Much like the `extended_stats` aggregator for basic numerical analysis on non-spatial data sets, the `spatial_stats` aggregator will be specially designed for spatial data sets - specifically operating on `geo_point` fields. The aggregator will provide the following:
- Morans I - A measure of global spatial auto-correlation
- Geary's C - A measure of localized spatial auto-correlation (inversely related to Morans I)
- Getis-Ord - Hot spot analysis
- LISA - Indicators of local spatial association

**Comment by cmk1523** [comment]
I love this idea. I’ve been wanting to analyze movement and I think this could really help. For example, if the “standard deviation” of a bunch of points over time is “large”, one could say that something has moved a certain amount. Anyone have thoughts on this?

**Comment by nknize** [comment]
Since this depends on multi pass aggregations I'm marking this as stalled.

**Comment by wchaparro** [comment]
This is not something we plan to implement in the near future in aggregations, and has been superceded by our focus on ESQL. Closing as not planned. If your feel strongly about this one, please let us know.
