### ISSUE TITLE
Missing compress-lzf dependency causes silent error

### ISSUE THREAD

**Issue by MagmaRules** [elastic/elasticsearch#14734]
When migrating an old installation from 0.90 to 2.0 got stuck in a strange behaviour where the client could not obtain masters. It would connect to the cluster, show up in the cluster but would timeout on getting the masters.

Turns out that on a default installation if you don't include compress-lzf as a dependency the client node will fail silently. 

I would suggest it should throw an error or at least warn in the logs.

**Comment by jasontedor** [comment]
Closing as stale.
