### ISSUE TITLE
StatsAggegator has a missing character.

### ISSUE THREAD

**Issue by HowookJeong** [elastic/elasticsearch#14730]
This is a minor issue or is not issue.

is it right StatsAggegator? (https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/metrics/stats/StatsAggegator.java)
I think that StatsAggegator will be StatsAggregator.

Thanks.

**Comment by clintongormley** [comment]
@colings86 we should probably fix this :)

**Comment by martinstuga** [comment]
Submited a PR to fix this.
