### ISSUE TITLE
Aggregation on scripts does not deal with `null` correctly

### ISSUE THREAD

**Issue by klahnakoski** [elastic/elasticsearch#14740]
Using version 1.7.1

I have one record in my index, with two nested records:  One is to establish a schema, the other is empty.

	{
		"_index":"testing_631cd59d7020151113_135108",
		"_type":"test_result",
		"_id":"9BDA12F08CF9D63CD48994EF1E11966C256203AE",
		"_version":1,
		"_score":1,
		"_source":{"a":{"_b":[{"a":0,"b":0},{}]}}
	}

My query is aggregating over a script, which just happens to return `null`.

	{
		"aggs":{"_nested":{
			"aggs":{"_missing":{
				"aggs":{"t":{"stats":{"script":"doc[\"a._b.a\"].value"}}},
				"filter":{"missing":{"field":"a._b.a"}}
			}},
			"nested":{"path":"a._b"}
		}},
		"size":0
	}

The aggregate over `"script":"doc[\"a._b.a\"].value"` is not the same as the aggregate over `"field": "a._b.a"`

	{
		"took":1,
		"timed_out":false,
		"_shards":{"total":3,"successful":3,"failed":0},
		"hits":{"total":1,"max_score":0,"hits":[]},
		"aggregations":{"_nested":{
			"doc_count":2,
			"_missing":{
				"doc_count":1,
				"t":{"count":1,"min":0,"max":0,"avg":0,"sum":0}
			}
		}}
	}

I would expect a count of zero (with `null` stats) instead:

	"t":{"count":0,"min":null,"max":null,"avg":null,"sum":null}

I highly suspect the code responsible for aggregating script results is not discounting `nulls`

**Comment by klahnakoski** [comment]
It would appear this problem can be mitigated with a more complicated script:

    "script":"(doc[\"a._b.a\"].isEmpty() ? null : doc[\"a._b.a\"].value)"

**Comment by clintongormley** [comment]
@klahnakoski yes, nulls need to be handled by your script as appropriate for your needs.
