### ISSUE TITLE
Allow continuing failed build, which skips already successful test tasks

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#14747]
When running `gradle check` from the root of elasticsearch, if a failure occurs say in a a plugin, fixing that then requires either knowing which plugins were left and running for those explicitly, or taking the hit of running an entire `gradle check` again.

Gradle tests normally are run only if "output changes". We currently explicitly disable this for all tests, since we have randomized tests. However, we could tweak this slightly to allow a flag which identifies the build run you were previously running. Then the logic of whether to run the test could be based on this (we can write a marker when each test task succeeds, with the name of the unique build id). We would still want to make sure the test runs if the inputs change (ie to fix your plugin, you had to change core code). But if nothing changed, then we could skip eg core tests and quickly get back to running the plugins that had not run yet.

I'm thinking something like:

```
$ gradle check
...
Failed `gradle check`. You can continue your build after fixing errors with:
gradle check -Dtests.buildid=abcdefg
```

**Comment by rmuir** [comment]
I agree this would be nice, I'm on my fourth run of `mvn verify`, and each time restarting because of a straggler here or there in a plugin or QA test.

At the same time, we shouldn't do it unless it can be done safely.

**Comment by rjernst** [comment]
> At the same time, we shouldn't do it unless it can be done safely.

I completely agree. Even if a buildid is passed in, and eg the core tests passed for that build id, we should still run core tests if core code changed, otherwise we are potentially hiding issues, where you could pass tests and think everything was ok. This is super important, otherwise there could be huge confusion on "my tests passed" but the code is totally broken.

**Comment by clintongormley** [comment]
@rjernst has this been implemented yet?

**Comment by atorok** [comment]
Much has changed since the initial issue, but the fact that most of the up-to-date checks are thrown off by the testing seed is still relevant. 

I think we could cache the testing seed by default and have a `cleanSeed` task that `clean` would depend on to be able to blow it away. we could then simply rely on up-to-date functionality to have the build pick up from where it left off. The seed will then be an input for the testing task. The meta info we add to jars might also play a role here because of hashes and timestamps that we add ad the generated jars serve as input for others tasks  and we will likely have to do something about those as well.

**Comment by rjernst** [comment]
@atorok Instead of storing the seed in a file, I think it can just be set as a property on TaskInputs? Then there is no need tohave a `cleanSeed` task, it would still be passed as a sysprop.

**Comment by atorok** [comment]
Yes, I think that would work and make sense. 
It will hover require deliberate action so one will have to explicitly pass in a seed, but it's a good start for experimentation.

**Comment by atorok** [comment]
We now implemented what @rjernst suggested, and have build caching enabled, so as long as one passes in the same seed and has build cache enabled, the build will skip everything that didn't change ( pull it from the cache).
It took close to 4 years but we are there :) 
Please feel free to re-open if you disagree.
