### ISSUE TITLE
1.5 - relocate on local disks

### ISSUE THREAD

**Issue by shaharmor** [elastic/elasticsearch#14767]
Hi,

I have multiple ES (1.5) servers with multiple disks.
I have added an additional disk to all of the servers and i want ES to relocate the shards so that the new disk will take an equal % of current storage usage.

For example:
before:
disk1 - 75%
disk2 - 75%

after:
disk1 - 50%
disk2 - 50%
disk3 - 50%

Preferably by smartly moving shards (I.E not have multiple replicas on same disk, moving equal # of primaries to all disks).

Is that possible?

**Comment by dadoonet** [comment]
Please keep your question on discuss only: https://discuss.elastic.co/t/relocated-shard-in-local-disks/34612

This space is for issues only.
