### ISSUE TITLE
max_determinized_states in regexp filter not working ES 2.0

### ISSUE THREAD

**Issue by damienbod** [elastic/elasticsearch#14768]
If I set the max_determinized_states in a regexp filter, the search result is incorrect. Without this set, the filter returns the correct amount of Hits:

Test data
------

POST http://localhost:9200/_bulk HTTP/1.1
Content-Type: application/json
Host: localhost:9200
Content-Length: 877
Expect: 100-continue

{"index":{"_index":"searchtests","_type":"searchtest","_id":1}}
{"id":1,"name":"one","details":"This is the details of the document, very interesting","circletest":{"type":"circle","coordinates":[45.0,45.0],"radius":"100m"},"location":[45.0,45.0],"lift":2.9,"dateofdetails":"2015-10-26T19:19:38.5961045Z"}
{"index":{"_index":"searchtests","_type":"searchtest","_id":2}}
{"id":2,"name":"two","details":"Details of the document two, leave it alone","circletest":{"type":"circle","coordinates":[46.0,45.0],"radius":"50m"},"location":[46.0,45.0],"lift":2.5,"dateofdetails":"2015-04-20T19:19:38.5961045Z"}
{"index":{"_index":"searchtests","_type":"searchtest","_id":3}}
{"id":3,"name":"three","details":"This data is different","circletest":{"type":"circle","coordinates":[37.0,42.0],"radius":"80m"},"location":[37.0,42.0],"lift":2.1,"dateofdetails":"2015-10-12T19:19:38.5961045Z"}

Incorrect
------

POST http://localhost:9200/searchtests/searchtest/_search HTTP/1.1
Content-Type: application/json
Host: localhost:9200
Content-Length: 78
Expect: 100-continue

{"filter":{"regexp":{"name":{"value":"o.*"},"max_determinized_states":20000}}}

OK
------

POST http://localhost:9200/searchtests/searchtest/_search HTTP/1.1
Content-Type: application/json
Host: localhost:9200
Content-Length: 46
Expect: 100-continue

{"filter":{"regexp":{"name":{"value":"o.*"}}}}

---------

Greetings Damien

**Comment by clintongormley** [comment]
You're specifying `max_determinized_states` at the wrong level.  It should be at the same level as `value`.  In 3.0 the parsing has been improved to throw an exception instead of silently swallowing the error.
