### ISSUE TITLE
2.0 won't start - es.default.config is no longer supported

### ISSUE THREAD

**Issue by johnarnold** [elastic/elasticsearch#14763]
OS: Ubuntu 15.04
ES Version:  Upgrade from 2.0 Beta2 to 2.0 GA  from repo.

Full log error:
[2015-11-14 16:28:46,587][INFO ][bootstrap                ] es.default.config is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed.

I searched for previous issues and found that the CONF_FILE variable was eliminated in the latest release and only CONF_DIR is to be used.  

I verified that I'm using the latest /etc/init.d/elasticsearch startup script, with no CONF_FILE defined:

    root@flowmaster1:/etc/elasticsearch# grep -i conf /etc/init.d/elasticsearch
    # Elasticsearch configuration directory
    CONF_DIR=/etc/$NAME
    # CONF_FILE setting was removed
    if [ ! -z "$CONF_FILE" ]; then
        echo "CONF_FILE setting is no longer supported. elasticsearch.yml must be placed in the config     directory and cannot be renamed."
    DAEMON_OPTS="-d -p $PID_FILE --default.path.home=$ES_HOME     --default.path.logs=$LOG_DIR --default.path.data=$DATA_DIR --default.path.conf= CONF_DIR"

I verified my /etc/default/elasticsearch  variable file has CONF_DIR line commented out:

    root@flowmaster1:/etc/elasticsearch# grep -i conf /etc/default/elasticsearch
    # Elasticsearch configuration directory
    #CONF_DIR=/etc/elasticsearch
    # Elasticsearch configuration file
    #CONF_FILE=$CONF_DIR/elasticsearch.yml
    # Configure restart on package upgrade (true, every other setting will lead to not restarting)
    # the configured user can read and write into the data, work, plugins and log directories.
    # For systemd service, the user is usually configured in file 
    /usr/lib/systemd/system/elasticsearch.service
    #     property is set at boot time in /usr/lib/sysctl.d/elasticsearch.conf

I don't see any reference to CONF_FILE or es.default.config anywhere in /etc.  I'm at a loss as to why this is failing.   I tried setting the CONF_DIR in both the startup script and the default variable file and no joy.

**Comment by johnarnold** [comment]
I found root cause -- the CONF_FILE references were in /usr/lib/systemd/system/elasticsearch.service  (and thus why they didn't show up when searching /etc)

When upgrading from beta2 to GA, the elasticsearch.service file did not get overwritten, instead a secondary file was created:   elasticsearch.service.dpkg-dist

copying this over elasticsearch.service file allows the service to start.

I used ansible apt module to install 2.0 package -- is there an apt option to force the files to the right places?

**Comment by johnarnold** [comment]
Also, confirmed that removing the -old- /usr/lib/system/system/elasticsearch.service and leaving the new elasticsearch.service.dpkg-dist in place works too.  So probably the pre-inst script for the debian packaging should remove the old elasticsearch.service file if it exists.

**Comment by johnarnold** [comment]
I also discovered that with "interactive" install, apt package manager prompts to overwrite the .service file -- it's just on non-interactive that it defaults to creating a new one which is not used.  E.g. via Ansible apt module.  I think defaulting to overwrite the .service file may be a better option for most users.

**Comment by clintongormley** [comment]
I don't think we should overwrite a file that has been edited, but the real problem is that, today, we require you to edit the `elasticsearch.service` file to uncomment `LimitMEMLOCK`.  Instead we should change the docs to recommend using a custom config file as suggested here: https://github.com/elastic/elasticsearch/issues/9357#issuecomment-172880212

Closing in favour of #9357

**Comment by PhaedrusTheGreek** [comment]
As redundant as it might be to say - It's worth noting that it's the ` --default.config` flag that causes this on the CLI.  e.g.:

```
$ bin/elasticsearch --default.config=/etc/elasticsearch.yml
[2016-12-16 15:42:37,143][INFO ][bootstrap                ] es.default.config is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed.
```
