### ISSUE TITLE
Execution Mode in Terms filter ES 2.0

### ISSUE THREAD

**Issue by damienbod** [elastic/elasticsearch#14769]
What happened the execution mode in the terms filter in es 2.0? It runs still but does not effect the search result.
Greetings Damien

**Comment by clintongormley** [comment]
Essentially all filters are now really queries.  For bwc, we don't throw an exception on execution mode, but it is ignored as it is no longer supported.

**Comment by clintongormley** [comment]
See https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_query_dsl_changes.html#_queries_and_filters_merged
