### ISSUE TITLE
What port used to remote debugging

### ISSUE THREAD

**Issue by feuyeux** [elastic/elasticsearch#14772]
From the office doc(https://github.com/elastic/elasticsearch/blob/master/TESTING.asciidoc), 

> Debugging from an IDE
>
If you want to run elasticsearch from your IDE, you should execute gradle run It opens a remote debugging port that you can connect with your IDE.

I found the only to debug ES is execute ```gradle run```, and invoke remote debug in IDE. But, it didn't tell about what the port open, or how to set a port to debug.

**Comment by dakrone** [comment]
> I think we should add a --debug option to it, and print the info to add to your debugger (as well as configure the server to suspend until the debugger is connected).

+1

**Comment by whateverblake** [comment]
does es has options like hadoop has  that i can use eclipse debug it

**Comment by whateverblake** [comment]
i have figure it out . add parameter  -D "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=port" when you start elastic
