### ISSUE TITLE
Decide whether to back port #14678 to 1.7.4 (ignored unallocated shards & making allocation decision)

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#14776]
#14678 ( Take ignored unallocated shards into account when making allocation decision ) fixes #14670 ( Shard relocation happens while cluster is yellow ) but is non-trivial to back port to 1.7.4  . It's possible but will take some careful work. Opening this issue to make sure we re-evaluate if it's needed.

**Comment by s1monw** [comment]
closed by #15195
