### ISSUE TITLE
Order not working inside a date_histogram aggs ES 2.0

### ISSUE THREAD

**Issue by damienbod** [elastic/elasticsearch#14771]
POST http://localhost:9200/searchaggtests/searchaggtest/_search?&search_type=count HTTP/1.1
Content-Type: application/json
Host: localhost:9200
Content-Length: 289
Expect: 100-continue

{"aggs":{"testHistogramBucketAggregation":{"date_histogram":{"field":"dateofdetails","interval":"1M","format":"yyyy-MM-dd","offset":"1d","time_zone":"+02:00","order":{"dateofdetails":"desc"},"min_doc_count":2,"extended_bounds":{"min":0,"max":1000000}},"aggs":{"tophits":{"top_hits":{}}}}}}
## Result:

HTTP/1.1 503 Service Unavailable
Content-Type: application/json; charset=UTF-8
Content-Length: 293

{"error":{"root_cause":[],"type":"reduce_search_phase_exception","reason":"[reduce] ","phase":"query","grouped":true,"failed_shards":[],"caused_by":{"type":"illegal_argument_exception","reason":"Invalid order path [dateofdetails]. Cannot find aggregation named [dateofdetails]"}},"status":503}

Greetings Damien

**Comment by clintongormley** [comment]
This is weird for a few reasons...  

* you can't sort on fields, only on the result of aggregations so the exception is correct
* it shouldn't be returning a 503 response though
* when I try it (full example below) on 2.0, I don't get this exception, which i should

    POST _bulk
    {"index":{"_index":"searchtests","_type":"searchtest","_id":1}}
    {"id":1,"name":"one","details":"This is the details of the document, very interesting","circletest":{"type":"circle","coordinates":[45,45],"radius":"100m"},"location":[45,45],"lift":2.9,"dateofdetails":"2015-10-26T19:19:38.5961045Z"}
    {"index":{"_index":"searchtests","_type":"searchtest","_id":2}}
    {"id":2,"name":"two","details":"Details of the document two, leave it alone","circletest":{"type":"circle","coordinates":[46,45],"radius":"50m"},"location":[46,45],"lift":2.5,"dateofdetails":"2015-04-20T19:19:38.5961045Z"}
    {"index":{"_index":"searchtests","_type":"searchtest","_id":3}}
    {"id":3,"name":"three","details":"This data is different","circletest":{"type":"circle","coordinates":[37,42],"radius":"80m"},"location":[37,42],"lift":2.1,"dateofdetails":"2015-10-12T19:19:38.5961045Z"}
    
    POST searchtests/_search?search_type=count
    {
      "aggs": {
        "testHistogramBucketAggregation": {
          "date_histogram": {
            "field": "dateofdetails",
            "interval": "1M",
            "format": "yyyy-MM-dd",
            "offset": "1d",
            "time_zone": "+02:00",
            "order": {
              "dateofdetails": "desc"
            },
            "min_doc_count": 2,
            "extended_bounds": {
              "min": 0,
              "max": 1000000
            }
          },
          "aggs": {
            "tophits": {
              "top_hits": {}
            }
          }
        }
      }
    }

@colings86 any ideas?

**Comment by colings86** [comment]
I get the same as @clintongormley.

This is a bug because an exception should be thrown and the status code returned should be 400 (bad request).

**Comment by qwerty4030** [comment]
As of #22343 `histogram` and `date_histogram` aggregation order will now be validated at the shard search phase. We now get the same validation errors as the `terms` agg when an invalid sub-aggregation is given in the order.
```
PUT i

POST i/_search
{
  "aggs": {
    "a": {
      "date_histogram": {
        "field": "f", 
        "interval": "day", 
        "order": {
          "wrong": "asc"
        }
      }
    }
  }
}

response:
{
  "error": {
    "root_cause": [
      {
        "type": "aggregation_execution_exception",
        "reason": "Invalid aggregator order path [wrong]. Unknown aggregation [wrong]"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "i",
        "node": "jUa3xSiEQTayFeYCYHt2jg",
        "reason": {
          "type": "aggregation_execution_exception",
          "reason": "Invalid aggregator order path [wrong]. Unknown aggregation [wrong]"
        }
      }
    ]
  },
  "status": 500
}
```
The `order` code was refactored in #22343 so it will now be easier to move order validation for all aggregations to the query parsing phase as a follow up PR.

**Comment by polyfractal** [comment]
@elastic/es-search-aggs

**Comment by polyfractal** [comment]
Actually, closing in favor of #20003

Sorry for the noise :)
