### ISSUE TITLE
_type not using doc_values in ES 2.0

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#14781]
```
POST /_cache/clear
DELETE testfd
POST testfd/type/1
{
  "test":"test"
}
GET testfd/_search
{
  "size": 0, 
  "aggs": {
    "NAME": {
      "terms": {
        "field": "_type",
        "size": 10
      }
    }
  }
}

GET /_cat/fielddata?v
```

Testing on ES 1.7 and ES 2.0, the above loads the same amount of fielddata into the fd cache.

On ES 1.7, put mapping api's change of _type to use doc_values or disable fd options do not throw an error, but they are not honored.

On ES 2.0, we explicitly throw an error when someone tries to modify the _type.  However, it also appears that we do not use doc_values for _type by default in ES 2.0.

If this is the expected behavior, it will be nice to document accordingly.  We do have use cases in the field where users are aggregating against the _type field.  Workaround is to tag each document with a custom "type" field and educate users to aggregate against this field instead of _type, though it will be helpful to provide a way to disable fielddata loading for _type as well.

**Comment by pickypg** [comment]
A workaround to this problem is to _not_ use `_type` at all. Have a single `_type` and add another field that represents the "type" of a document, then work against it. This has the added benefit that it simplifies the mapping.
