### ISSUE TITLE
Confusing exception when `regexp` query used on numeric field

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#14782]
PUT t/t/1
    {
      "num": 34
    }
    
    GET /_search
    {
      "query": {
        "regexp": {
          "num": {
            "value": "34"
          }
        }
      }
    }
    
returns:

   "error": {
      "root_cause": [
         {
            "type": "illegal_argument_exception",
            "reason": "expected '\"' at position 11"
         }
      ],

**Comment by camilojd** [comment]
Hi, I created a fix for this in the referenced PR, that I believe does the right thing.

All tests pass.
