### ISSUE TITLE
Thread interrupt flag is not properly restored after an InterruptedException

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#14798]
I've spotted multiple instances across the code base where we catch `InterruptedException` and call `Thread.interrupted()` afterwards.  The problem is that `Thread.interrupted()` queries and *clears* the interrupted status (see also [Javadoc](http://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#interrupted--)) which is contrary to what should happen, namely to *set* the interrupt flag again so code higher up the call stack can check the flag and act accordingly. This is done by calling `Thread.currentThread().interrupt()` (see [Javadoc](http://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#interrupt--)).

**Comment by mtraynham** [comment]
It'd be nice to have [BulkProcessor#L348](https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/action/bulk/BulkProcessor.java#L348) fixed back in 1.7.  I just ran into this today, as I have multiple data source threads running (using ExecutorService), all which populate a single BulkProcessor.  We `cancel` the source thread in some cases, which triggers an interrupt and thus the BulkProcessor may sometimes swallow it (more often than not).

It does look like the error is returned back to the BulkListener, so maybe I can check if it's an InterruptedException and re-interrupt?  Thoughts?

**Comment by danielmitterdorfer** [comment]
> It'd be nice to have BulkProcessor#L348 fixed back in 1.7.

We only fix critical bugs (e.g. ones that lead to data loss) in 1.7 and I'd not consider this one critical enough.

> It does look like the Throwable is returned back to the BulkListener, so maybe I can check if it's an InterruptedException and re-interrupt? Thoughts?

Admittedly, this is just a workaround but this should work. Just don't forget to remove it once you upgrade. ;) It won't hurt calling `Thread.currentThread().interrupt()` again in your listener but it is not necessary on newer versions of Elasticsearch (starting with Elasticsearch 2.2.0)

**Comment by mtraynham** [comment]
Seems to work ok.  Thanks for the feedback @danielmitterdorfer !
