### ISSUE TITLE
most fields in geopoint is error

### ISSUE THREAD

**Issue by whybangbang** [elastic/elasticsearch#14792]
we use the most fields in many case,title,name and so on,and it run very well,there is a geopoint field in our mapping ,we find geohash cell have a good performance, so we update the mapping 
PUT
{
  "item": {
    "properties": {
      "location": {
        "type": "geo_point",
        "fields": {
          "location_cell": {
            "type": "geo_point",
            "geohash": true,
            "geohash_prefix": true,
            "geohash_precision": 5
          }
        }
      }
    }
  }
}

the same operation have be used in string type many times,but geo point most fields is error
ERROR: TransportError(400, u'MapperParsingException[failed to parse]; nested: ElasticsearchParseException[geo_point expected]; ')

es version 1.5.2

**Comment by clintongormley** [comment]
Hi @whybangbang 

Your mapping works fine, and you haven't provided sufficient information to figure out what you are doing when you get that error.  Either way, this sounds like a question that would be better asked in our forums: https://discuss.elastic.co/
