### ISSUE TITLE
elastic.co search performance bad

### ISSUE THREAD

**Issue by whybangbang** [elastic/elasticsearch#14793]
we know there are many difference in elasticsearch 2.0, but i think 1.x is the main version in produce,we can't find many function by the search,if we can search in difference version?

**Comment by markwalkom** [comment]
Thanks for mentioning this. I have raised an internal issue with the website team to see if we can make the search version contextual.

That way when you pick (eg) 1.7 docs, any searches will only look there.

**Comment by whybangbang** [comment]
thank you
