### ISSUE TITLE
ES gets stuck throwing thousands of errors per second

### ISSUE THREAD

**Issue by travisbell** [elastic/elasticsearch#14805]
We're having an issue where a bad query is sending ES into an endless error loop of ~5,000 errors being logged per second. This is with ES 1.7.2 on a 3 node cluster.

The error that triggers it can be any legit error (this is from a popular web service and our user input can be all kinds of crap 😉), but once it gets one of these in a loop, it's the same error over and over and the only way to stop them is to restart each node. And just for clarity, when I say it logs over and over, these are no longer requests coming into ES. It's ES doing this all on its own internally.

Here's examples: [es_errors.txt](https://github.com/elastic/elasticsearch/files/36942/es_errors.txt)

![log_search](https://cloud.githubusercontent.com/assets/24766/11218447/4eb5d158-8d12-11e5-8b4a-6caafc9b5ce8.png)

Have you guys ever seen this before?

**Comment by nik9000** [comment]
> It's ES doing this all on its own internally.

Sure! For lots of things you'll see one copy of the error per shard. I've also seen this when I had my retry logic on my appserver too permissive.

Are you _sure_ it Elasticsearch making echo errors? Can you try running the same query with the same mappings on a local index with curl?

**Comment by travisbell** [comment]
Hey @nik9000!

> Are you sure it Elasticsearch making echo errors?

I am pretty sure. There is no spike in app server requests, or in traffic between the app servers and ES nodes.

We have never been able to replicate this problem locally, only under a real production load. And even then, it will be fine for 12 hours (with some errors here and there no big deal) and then all of a sudden she fires up (like in the graph above) and we see CPU usage spike. Restart nodes, rinse wash and repeat.

**Comment by clintongormley** [comment]
Hi @travisbell 

I see no further info here, but looking at the error logs, it appears they are not the same errors but lots of different malformed queries/requests.  It looks like some misbehaving bot is targeting your site.
