### ISSUE TITLE
IntelliJ - Gradle Integration broken

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#14809]
I'm using the [Gradle IntelliJ integration](https://www.jetbrains.com/idea/help/working-with-gradle-projects.html) for Elasticsearch. When I refresh the linked Gradle projects in the Gradle Tool window, the folder `.idea` gets deleted (with all my settings) and I end up in an unrecoverable state (need to completely reimport the whole project from scratch with all my settings gone).

I see that as part of commit f327beac49a7a5097dad64adcb3e43c03980f122 the following lines were introduced:

```
tasks.cleanIdea {
    delete '.idea'
}
```

Can we undo this?

**Comment by dadoonet** [comment]
Ha thanks! It happened to me today as well. I thought I did something stupid. :)

**Comment by javanna** [comment]
I have the same problem and end up needing to reimport the project from scratch every day...

**Comment by rjernst** [comment]
Please remove the lines Yannick mentioned above (or I can do it in the morning). I didnt realize it woukd have this impact. I will find another way to address the issue I was having.
