### ISSUE TITLE
when upgrade es from v1.1 to v1.7 . The has_parent  include prefix  Query  slow  200ms。What is the cause of the problem？

### ISSUE THREAD

**Issue by z-star** [elastic/elasticsearch#14819]
shards: 10 * 2 | docs: 71,991,873 | size: 54.95GB

query:

  "filter" : {
      "has_parent" : {
        "filter" : {
          "prefix" : {
            "treecode" : "1#55#57#58#682#jieying.cheng@"
          }
        },
        "parent_type" : "treecode"
      }
    }

**Comment by clintongormley** [comment]
Hi @z-star 

Parent-child has been completely rewritten in 2.0, so I would suggest trying it out there instead.
