### ISSUE TITLE
Filtered query using elasticsearch API

### ISSUE THREAD

**Issue by malinir123** [elastic/elasticsearch#14816]
How to write the following filtered query using elasticsearch java api?

{
  "query": { 
    "bool": { 
      "must": [
        { "match": { "title":   "Search"        }}, 
        { "match": { "content": "Elasticsearch" }}  
      ],
      "filter": [ 
        { "term":  { "status": "published" }}, 
        { "range": { "publish_date": { "gte": "2015-01-01" }}} 
      ]
    }
  }
}

**Comment by rjernst** [comment]
Please ask questions like this on http://discuss.elastic.co. We use github for bug reports and feature requests.
