### ISSUE TITLE
Visualization - Mouse over details

### ISSUE THREAD

**Issue by holeunlee** [elastic/elasticsearch#14825]
Hello all,

I've been wondering if it is possible to change the mouseover details on for example a vertical barchart?
At the moment during a mouseover on a bar, it shows "filter" and "@timestamp" which is not very useful.
A combination of a custom field "status" or combination of a "@timestamp" + "status" + "host" is the result i'm looking for.

**Comment by dadoonet** [comment]
Please ask questions on discuss.elastic.co and if you need to ask for a feature request about Kibana, please open it in Kibana project.

This repository is about elasticsearch only.
