### ISSUE TITLE
elasticsearch java class path for 1.7.1 uses 0.90.5 jar path

### ISSUE THREAD

**Issue by mnikhil-git** [elastic/elasticsearch#14822]
this is incorrect

```
# ps -aef | grep -i elasticsearch | grep -i --color 0.90.5
.... /usr/java/jdk1.7.0_55/bin/java..... -Delasticsearch -Des.foreground=yes -Des.path.home=/opt/elasticsearch/1.7.1 -cp :/opt/elasticsearch/1.7.1/lib/elasticsearch-0.90.5.jar:/opt/elasticsearch/1.7.1/lib/*:/opt/elasticsearch/1.7.1/lib/sigar/* -Des.config=/srv/etc/elasticsearch/elasticsearch.yml org.elasticsearch.bootstrap.Elasticsearch
```

looks like 0.90.5.jar is hard coded?

**Comment by dadoonet** [comment]
It sounds like your update is wrong and that you have old jars remaining in `/opt/elasticsearch/1.7.1/lib/` dir.

Check for it.

**Comment by mnikhil-git** [comment]
got it, it was because of elasticsearch.in.sh was from old installation was stil lurking around.. I had to reinstall the package to get it removed and it is working fine. thanks for the attention. this can be closed.
