### ISSUE TITLE
allow to define own JAVA_OPTS to use another garbage collector

### ISSUE THREAD

**Issue by mnikhil-git** [elastic/elasticsearch#14821]
I would like to use a different garbage collector other than CMS which is enforced in elasticsearch script. current script does not let me, please update the script so there is a flexibility at the user side to do that.

JAVA_OPTS should not be updated with in the script unless the user wants.

thanks.

**Comment by clintongormley** [comment]
See https://github.com/elastic/elasticsearch/issues/5823#issuecomment-59782959
