### ISSUE TITLE
script_fields with filtered query

### ISSUE THREAD

**Issue by luizamboni** [elastic/elasticsearch#14820]
I already try to put script_fields inside filtered, inside query inside filtered, nothing works an i m not found any quote of how use the 2 features together...

```{
  "fields": [
    "_source"
  ],
  "script_fields": [
    {
      "status": {
        "script": "return 1;"
      }
    }
  ],
  "query": {
    "filtered": {
      "query": {
        "bool": {
          "must": [
            {
              "term": {
                "seller_id": 1
              }
            }
          ],
          "must_not": []
        }
      },
      "filter": {
        "script": {
          "script": "if(_source.concurrents.findAll{ it.new_price < _source.new_price && concurrent_ids.contains(it.seller_id) }.size == 0 && _source.concurrents.findAll{ it.new_price > _source.new_price  && concurrent_ids.contains(it.seller_id) }.size > 0 ){ return true; }",
          "params": {
            "concurrent_ids": [
              2,
              3
            ]
          }
        }
      }
    }
  },
  "size": 500,
  "from": 0
}
```

the error message is :
{
"error": "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[II2sctcxR2eIZdEBEoBj-g][4ninjas_products_test][0]: SearchParseException[[4ninjas_products_test][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"fields":["_source"],"script_fields":[{"status":{"script":"return 1;"}}],"query":{"filtered":{"query":{"bool":{"must":[{"term":{"seller_id":1}}],"must_not":[]}},"filter":{"script":{"script":"if(_source.concurrents.findAll{ it.new_price < _source.new_price && concurrent_ids.contains(it.seller_id) }.size == 0 && _source.concurrents.findAll{ it.new_price > _source.new_price && concurrent_ids.contains(it.seller_id) }.size > 0 ){ return true; }","params":{"concurrent_ids":[2,3]}}}}},"size":500,"from":0}]]]; nested: NullPointerException; }{[II2sctcxR2eIZdEBEoBj-g][4ninjas_products_test][1]: SearchParseException[[4ninjas_products_test][1]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"fields":["_source"],"script_fields":[{"status":{"script":"return 1;"}}],"query":{"filtered":{"query":{"bool":{"must":[{"term":{"seller_id":1}}],"must_not":[]}},"filter":{"script":{"script":"if(_source.concurrents.findAll{ it.new_price < _source.new_price && concurrent_ids.contains(it.seller_id) }.size == 0 && _source.concurrents.findAll{ it.new_price > _source.new_price && concurrent_ids.contains(it.seller_id) }.size > 0 ){ return true; }","params":{"concurrent_ids":[2,3]}}}}},"size":500,"from":0}]]]; nested: NullPointerException; }{[II2sctcxR2eIZdEBEoBj-g][4ninjas_products_test][2]: SearchParseException[[4ninjas_products_test][2]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"fields":["_source"],"script_fields":[{"status":{"script":"return 1;"}}],"query":{"filtered":{"query":{"bool":{"must":[{"term":{"seller_id":1}}],"must_not":[]}},"filter":{"script":{"script":"if(_source.concurrents.findAll{ it.new_price < _source.new_price && concurrent_ids.contains(it.seller_id) }.size == 0 && _source.concurrents.findAll{ it.new_price > _source.new_price && concurrent_ids.contains(it.seller_id) }.size > 0 ){ return true; }","params":{"concurrent_ids":[2,3]}}}}},"size":500,"from":0}]]]; nested: NullPointerException; }{[II2sctcxR2eIZdEBEoBj-g][4ninjas_products_test][3]: SearchParseException[[4ninjas_products_test][3]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"fields":["_source"],"script_fields":[{"status":{"script":"return 1;"}}],"query":{"filtered":{"query":{"bool":{"must":[{"term":{"seller_id":1}}],"must_not":[]}},"filter":{"script":{"script":"if(_source.concurrents.findAll{ it.new_price < _source.new_price && concurrent_ids.contains(it.seller_id) }.size == 0 && _source.concurrents.findAll{ it.new_price > _source.new_price && concurrent_ids.contains(it.seller_id) }.size > 0 ){ return true; }","params":{"concurrent_ids":[2,3]}}}}},"size":500,"from":0}]]]; nested: NullPointerException; }{[II2sctcxR2eIZdEBEoBj-g][4ninjas_products_test][4]: SearchParseException[[4ninjas_products_test][4]: from[-1],size[-1]: Parse Failure [Failed to parse source [{"fields":["_source"],"script_fields":[{"status":{"script":"return 1;"}}],"query":{"filtered":{"query":{"bool":{"must":[{"term":{"seller_id":1}}],"must_not":[]}},"filter":{"script":{"script":"if(_source.concurrents.findAll{ it.new_price < _source.new_price && concurrent_ids.contains(it.seller_id) }.size == 0 && _source.concurrents.findAll{ it.new_price > _source.new_price && concurrent_ids.contains(it.seller_id) }.size > 0 ){ return true; }","params":{"concurrent_ids":[2,3]}}}}},"size":500,"from":0}]]]; nested: NullPointerException; }]",
"status": 400
}

**Comment by luizamboni** [comment]
is more readable here
https://gist.github.com/luizamboni/aac0dda810eebeb44fd0

**Comment by clintongormley** [comment]
Hi @luizamboni 

Please ask questions like these in the forums instead: http://discuss.elastic.co/

I'd also advise checking the documentation - script fields need to be a named hash, not an array
