### ISSUE TITLE
2.0 does not handle -Des.config

### ISSUE THREAD

**Issue by runningman84** [elastic/elasticsearch#14826]
We used to run mutiple instances of elasticsearch on the same machine. Our startup script would look like
```
-Des.config=/data/es_instance1/conf/elasticsearch.yml
```
This is the error message
```
[2015-11-18 12:00:14,913][INFO ][bootstrap ] es.config is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed. 
```

Is this a known problem? I do not want to install elasticsearch binaries mutiple times on a single machine...

**Comment by dadoonet** [comment]
It's a known feature. Not a known problem ;)

You can define a `path.conf` which points to a dir containing an `elasticsearch.yml` file.

**Comment by electrical** [comment]
@runningman84 With the ES puppet module we handle this by creating a directory per instance.
via `-Des.path.conf` you can set the path to the config directory.

**Comment by bstascavage** [comment]
What a horrible step backwards.  I don't understand why, in 2015, you'd go from being able to specify a config file to specifying a directory that HAS to have a config file named a certain way.  

This broke our deployment and is a ridiculous omission

**Comment by Jestar342** [comment]
As above. This is a total regression.
