### ISSUE TITLE
Terms Query doesn't support minimum_should_match without info in breaking changes

### ISSUE THREAD

**Issue by zdeseb** [elastic/elasticsearch#14830]
**minimum_should_match** parametr is not supported in Terms Query in ES 2.0 version and **there is no such info in ES 2.0 Breaking Changes** document.

Following query works on ES 1.7.3 but doesn't work on ES 2.0 - [terms] query does not support [minimum_should_match]
```javascript
GET _all/_search
{
  "query": {
    "terms": {
      "FIELD": [
        "VALUE1",
        "VALUE2"
      ],
      "minimum_should_match": 1
    }
  }
}

**Comment by xzer** [comment]
use bool query's should clause instead.

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html

**Comment by zdeseb** [comment]
I think Issue is, that info about this change is missing in ES 2.0 Breaking Changes document
