### ISSUE TITLE
Can we replace the field stats API with search/aggs?

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#14832]
Most information that the field stats API returns can also be computed with our search API:
- min value (min aggregation)
- max value (max aggregation)
- density (total hits of an exists query divided by the total hits of a match_all)

So for instance, you could get the min/max values of a field called `@timestamp` on all indices with the following aggregation:

``` javascript
{
  "aggs": {
    "by_index": {
      "terms": {
        "field": "_index"
      },
      "aggs": {
        "min_ts": {
          "min": {
            "field": "@timestamp"
          }
        },
        "max_ts": {
          "min": {
            "field": "@timestamp"
          }
        }
      }
    }
  }
}
```

The field stats also has field constraints, which could be implemented on top of the previous aggregations by adding a `bucket_selector` pipeline on the `by_index` aggregation:

``` javascript
{
  "aggs": {
    "by_index": {
      "terms": {
        "field": "_index"
      },
      "aggs": {
        "min_ts": {
          "min": {
            "field": "@timestamp"
          }
        },
        "max_ts": {
          "min": {
            "field": "@timestamp"
          }
        },
        "range_filter": {
          "bucket_selector": {
            "buckets_path": {
              "min_ts": "min_ts",
              "max_ts": "max_ts"
            },
            "script": "max_ts >= 1447718400000 && min_ts <= 1447804800000"
          }
        }
      }
    }
  }
}
```

As-is this would perform more slowly than the field stats API because it would collect all documents. But I think not having the support this new field stats API is compelling. Moreover in case there are no deletions, we could have similar optimizations as the one we have when couting matches on a match_all when we can just leverage index stats.

**Comment by rashidkpc** [comment]
The reason Kibana needs _field_stats is speed alone. Currently aggregations don't perform fast enough for Kibana to use them for pre-flight requests in determining which indices to search. On my very small data set I get 138ms for an aggregation, and 23ms for _field_stats.

**Comment by jpountz** [comment]
Wouldn't the request cache already help from that perspective?

Separately I think we can work on making such aggs less naive and use index statistics when applicable. I opened #14835

**Comment by rashidkpc** [comment]
The request would cache, but only if the data and time ranges that are not changing right? Most Kibana users have constantly updating data sets and are using `[now-1M TO now]` style time ranges. We need to re-lookup the index list whenever the time range or underlying data changes.

**Comment by jpountz** [comment]
Good point about caching, the script from the bucket selector will change all the time, which is a pity since shards (where the caching is done) don't care about pipeline aggs, which are executed on the coordinating node.

**Comment by jpountz** [comment]
As a side note, the caching would work if the bucket filtering was performed on Kibana side.

**Comment by clintongormley** [comment]
Discussed this in FixItFriday.  Aggregations could be a viable replacement for field stats if:

* The min/max aggs can be optimized to use the field stats to return values from the index stats instead of running the full aggregation (requires a match all query and no deleted docs)
* A pipeline agg is used to filter down the result set to the interesting indices (and can still be cached in the results cache even with the moving boundary)
* The new dimensional format for date fields coming in Lucene 6 can expose the min/max values.

**Comment by jpountz** [comment]
This surfaced again in today's Fixit Friday when discussing whether to remove the experimental tag in the field stats API (#19798) as we would really like for the field stats API to not be necessary for Kibana cc @s1monw .

**Comment by jpountz** [comment]
The field stats API is getting replaced by field caps, which do not expose stats. Closing.
