### ISSUE TITLE
[DOCS] Document firewall/network configuration requirements

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#14848]
This is commonly available in other enterprise software product documentation.  There is generally a network configuration page/guide that tells network administrators what ports and if it's 1 way or bi-directional (eg. 9300 for transport, 9200 http) that they will have to open up for inter-node and client-cluster communications.  It will be helpful to have this information documented in our guide (on the network settings page, or an administration guide, etc..).

**Comment by tbrooks8** [comment]
@debadair - Is this issue still in progress? Or have the docs been updated since this was created?

**Comment by debadair** [comment]
This recently came up again. There is some information like this for Cloud, but we should also document it for the stack.

**Comment by andrershov** [comment]
I've referenced #45081 because firewall settings and TCP keep-alive settings are related.

**Comment by jrodewig** [comment]
[docs issue triage]

**Comment by original-brownbear** [comment]
We have documentation on the ports and things like connection stability/keep-alive now, closing this as done.
