### ISSUE TITLE
Incorrect license header

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#14857]
While refactoring I found the following:

https://github.com/elastic/elasticsearch/blob/148265bd164cd5a614cd020fb480d5974f523d81/core/src/main/java/org/elasticsearch/common/Base64.java

states in the license header the file to be licensed to Elastic, given the class comment this seems bogus. Maybe there are other files with the same issue in our code base, need to check.

**Comment by clintongormley** [comment]
@MaineC why do you think this license header is incorrect? It says:

> Licensed to Elasticsearch under one or more contributor license agreements

that covers public domain surely?

**Comment by jasontedor** [comment]
The author of the code in question has the following comment on the [SourceForge page](http://iharder.sourceforge.net/current/java/base64/):

> I have released this software into the Public Domain. That means you can do whatever you want with it. Really. You don't have to match it up with any other open source license &em; just use it. You can rename the files, move the Java packages, whatever you want. If your lawyers say you have to have a license, contact me, and I'll make a special release to you under whatever reasonable license you desire: MIT, BSD, GPL, whatever.

**Comment by clintongormley** [comment]
Sounds like we're good
