### ISSUE TITLE
elasticsearch master head is not working with V1.7.3

### ISSUE THREAD

**Issue by ashitpupu** [elastic/elasticsearch#14859]
Hi 

I have upgraded my elasticsearch from v1.4 to v1.7.3. The index service is up but I am unable to view in elasticsearch master head. Is it a know issue ??
If resolved already can you provide the solution .

Thanks

**Comment by dadoonet** [comment]
Please ask your questions on discuss.elastic.co. We can help there.

You are asking here support about the head plugin which is not part of this repository but a community plugin.
