### ISSUE TITLE
SearchHit should not contains _routing and _timestamp fields in its iterator

### ISSUE THREAD

**Issue by xzer** [elastic/elasticsearch#14853]
version: 2.0, Java client.

I am migrating my program to elasticsearch 2.0 now, and I got failed when I tried to retrieve fields data via SearchHit.

At first, I use hit.iterator() to retrieve an iterator to access the fields which I specified in the query, and I got error because there are two unexpected fields named "_routing" and "_timestamp" contained in the iterator.

Then I checked the returned map from hit.fields() or hit.getFields(), which shows that the map actually contains the extra two fields.

As mentioned in the elasticsearch's guide, the new 2.0 will return meta information by default, but I believe the _routing and _timestamp fields should be considered as meta rather than the "fields" of query at client query api side.

So please remove the two fields from the fields of SearchHit and make them accessible via other meta-like methods.

**Comment by clintongormley** [comment]
@jpountz what do you think?

**Comment by jpountz** [comment]
+1 I think this is a good point

**Comment by xzer** [comment]
@clintongormley  I noticed that you tagged this issue as enhancement, but I think it is actually a bug which cause different data structure between java api and the raw json response format.

**Comment by fltiago** [comment]
@xzer so, in your opinion those fields `_routing` and `_timestamp` should be in a `metaFields` attribute?

**Comment by xzer** [comment]
@fltiago, yes, I think the _routing and _timestamp should be as meta fields rather than common fields of the query result since the responsed raw json format also does not include them in result fields.

to clarify, assume I performed the following query,

```javascript
{
  "from": 0,
  "size": 10,
  "query": {
    "bool": {
      "must": {
        "terms": {
          "someIds": [
            788,
            2510,
            2534,
            3158
          ]
        }
      }
    }
  },
  "fields": "oneField",
}
```

then I got the following result:

```javascript
"hits": [

    {
        "_index": "some_index",
        "_type": "some_type",
        "_id": "4108260_1991",
        "_score": 16.746162,
        "_routing": "1991",
        "_timestamp": 1445431608007,
        "fields": {
            "oneField": [
                4108260
            ]
        }
    }
    ,
    {
        "_index": "some_index",
        "_type": "some_type",
        "_id": "421549_2002",
        "_score": 16.746162,
        "_routing": "2002",
        "_timestamp": 1445450850478,
        "fields": {
            "oneField": [
                421549
            ]
        }
    }
```

On the java side, when the developer tries to iterate all the queried fields from SearchHit, he should never expect that there are other unknown fields except those are specified  by "fields" in the query.

I am agree with that for most cases which does not cause problems even there are two extra fields, but for some cases, like mine, it broke my program.

**Comment by clintongormley** [comment]
Closing in favour of #18280
