### ISSUE TITLE
Improve documentation about query DSL range query

### ISSUE THREAD

**Issue by dedemorton** [elastic/elasticsearch#14865]
Feedback from user:
"...a lot of our product revolves around Elasticsearch. we find a lot of our customers have a really hard time understanding the Elasticsearch documentation about the query DSL, because the segments described don't provide context on where they seem to fit in. ie:
                      https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html It shows you a helpful segment, but doesn't provide an easy way to jump from there to "ok how do I use this in an actual query"

**Comment by javanna** [comment]
This is a pretty old issue, from the description I am not sure what we should change in the range query docs. Maybe that docs page already improved over time since this issue was opened. I am closing this, feel free to open a PR to address the initial concerns if you have ideas on it.
