### ISSUE TITLE
Current CIDR parsing will silently parse invalid CIDRs

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#14862]
I noticed this while reviewing #14773. Namely, the code that exists today in IPv4RangeBuilder.java and modifications proposed in #14773 will silently parse invalid IPv4 address/mask combinations. This is due to a regex pattern

```java
private static final Pattern MASK_PATTERN = Pattern.compile("(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,3})");
```

that will match strings that do not represent valid combinations. For example, it will match "256.512.256.512/33".

The code then proceeds to capture these potentially invalid octets/mask and parse them.

```java
int addr = (( Integer.parseInt(matcher.group(1)) << 24 ) & 0xFF000000)
  | (( Integer.parseInt(matcher.group(2)) << 16 ) & 0xFF0000)
  | (( Integer.parseInt(matcher.group(3)) << 8 ) & 0xFF00)
  | ( Integer.parseInt(matcher.group(4)) & 0xFF);

int mask = (-1) << (32 - Integer.parseInt(matcher.group(5)));
```

While there are regex patterns to match IPv4 address/masks, I think that a simple state machine would be vastly simpler.

**Comment by jpountz** [comment]
Thanks for opening this issue. Let's fix this leniency!
