### ISSUE TITLE
Improve stability of UpdateIT

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#14877]
`UpdateIT#testConcurrentUpdateWithRetryOnConflict()` has caused some trouble recently, especially on Windows. The test often times out and the build guard infrastructure kills the test. The root cause of the problem is that the test is performing an excessive number of index updates (currently up to 10.000).

We want to improve two things in this ticket:

1. Reduce the number of updates to at most 500. This is still enough to spot problems.
2. Improve logging so we know that the test is still making progress

**Comment by dadoonet** [comment]
Sounds like it failed today again on 2.1 branch: http://build-us-00.elastic.co/job/es_core_21_debian/342/consoleFull

**Comment by danielmitterdorfer** [comment]
@dadoonet It's not yet merged. I'll merge it soon.
