### ISSUE TITLE
Odd Primary Shard Distribution

### ISSUE THREAD

**Issue by kaanbasal** [elastic/elasticsearch#14879]
Hello,
Using version **2.0**, with **3 nodes, 9 shards, 2 replicas** with default settings. 
At the beginning all of the primary shards were distributed over all 3 nodes evenly. After restarting some of the nodes, all of the primary shards are located on the same node, and even restarting the node which full of primary shards, not changed this distribution.
Here some screenshots from kopf plugin:
**After Index Created:**
<img width="412" alt="screen shot 2015-11-20 at 12 05 28" src="https://cloud.githubusercontent.com/assets/3204601/11297126/0695ac4e-8f7f-11e5-916f-5f123274fa5e.png">
**After node-3 and node-1 restarted: (one by one)**
<img width="408" alt="screen shot 2015-11-20 at 11 42 45" src="https://cloud.githubusercontent.com/assets/3204601/11296630/ea62767c-8f7b-11e5-8fff-e90004c4c13a.png">
**After node-2 restarted:**
<img width="417" alt="screen shot 2015-11-20 at 12 00 43" src="https://cloud.githubusercontent.com/assets/3204601/11297035/5d60c6ea-8f7e-11e5-872c-3ff7016a6a0e.png">
I tried to use "cluster.routing.allocation.balance.primary" config but it's deprecated and not working on version 2.0.
So my questions are there is any way to distribute primary shards over all of the nodes evenly or there is any known downside about this behaviour?

**Comment by bleskes** [comment]
What happens is that as you restart nodes other replicas are elected as primaries. Since Elasticsearch does sync replication, all shard copies do the same work except for extreme cases (like a lot of document rejections, or extremely heavy update scripts). As such the location of the primaries shouldn't matter much (and we are working on those extreme cases where it still does).

Do you see any odd behavior due to those primaries?

**Comment by kaanbasal** [comment]
I made some tests about the behaviour of primary shard distribution based on the other users mentioned. I find that there is no CPU or RAM overhead on the node full of primary shards when making query or inserting new documents, on the other side the only thing I found odd is when a new node added to the cluster, the only node sending the data to the newly created node is that node which is full of primary shards and this behaviour makes Network and CPU overhead on that machine.

**Comment by bleskes** [comment]
> the only node sending the data to the newly created node is that node which is full of primary shards

That is correct for indexing. Searches how ever should round robin and hit the new node as well.

> behaviour makes Network and CPU overhead only on that machine.

which of two machines do you mean? I presume the one with primary, in which case I can see the network argument (but not the cpu). Is network a bottle neck for you?

**Comment by kaanbasal** [comment]
Your assumption is right about the machine, it's the one with primary. For now network is not a bottle neck but I just wanted you to know this situation. 
For the CPU argument, I made some queries/inserts while indexing the new node, and the node with primary had a lot of CPU usage than the other nodes.

**Comment by bleskes** [comment]
ok. Are you using update scripts? as I mentioned, those are run on the primary only, but are typically light weight. If not, can you run [the _hot_threads API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-hot-threads.html?q=hot%20thre#cluster-nodes-hot-threads) and report what the node with the primary says?

**Comment by kaanbasal** [comment]
I don't know which info do you need from the hot threads api response. Do you want me to send all of the  response or any specific value?

**Comment by bleskes** [comment]
If you gist them it would be great (with an indication of which node is the one with the primaries. That will tell us what it does.

**Comment by kaanbasal** [comment]
Ok, you can check it here: [Hot Threads] (https://gist.github.com/kaanbasal/ebaffd30567435c142b5)

[Hot_Thread_Primary_Only_Indexing] (https://gist.github.com/kaanbasal/ebaffd30567435c142b5#file-hot_thread_primary_only_indexing) is only primary node, while indexing to newly added node. (before making query/insert)

The others are while indexing & querying/inserting at the same time.

**Comment by bleskes** [comment]
@kaanbasal sorry for taking so long to respond. The hot thread seem to suggest that the replicas are still recovering and pull data from the node with the primary. Specifically the hot threads show compression code, compressing the data before it is being sent. It is correct that when the index is going from yellow to green the primary has more to do then replicas. However, this period is temporary. The tricky part is that moving the primaries around for this purpose will create more traffic than letting the replicas finish recovering. I'm going to close this for now as it feels like the right tradeoff. Feel free to reopen if it doesn't add up.

Note that in master we're going to reduce the CPU spent compressing lucene files during recovery. They are already compressed.
