### ISSUE TITLE
MissingValues don't work inside sub aggregations ()

### ISSUE THREAD

**Issue by DavidHauger** [elastic/elasticsearch#14882]
`missing` values are great to work with - but they do not work within more complex queries.

Here a simple example to reproduce the bug.
Let's say, we have some index, with optional fields:

    PUT /missing-values/test/1_with_my_field
    {
      "someField": "optionalField_is_present",
      "optionalField": "present"
    }
    PUT /missing-values/test/1_without_my_field
    {
      "someField": "optionalField_is_missing"
    }

Now I want to use the fields in some term aggregation. I want information on all items; even if the optional field is missing, so I can use this code:

    GET /missing-values/test/_search
    {
      "aggregations" : {
        "test": {
          "terms" : {
            "field" : "optionalField",
            "missing": "n/a"
          },
          "aggregations" : {
            "test": {
              "terms" : {
                "field" : "someField"
              }
            }
          }
        }
      }
    }

That works fine as long as the `missing` stuff is applied on the outer level only.
If I change the order of the fields:

    GET /missing-values/test/_search
    {
      "aggregations" : {
        "test": {
          "terms" : {
            "field" : "someField"
          },
          "aggregations" : {
            "test": {
              "terms" : {
                "field" : "optionalField",
                "missing": "n/a"
              }
            }
          }
        }
      }
    }

I receive an exception due to internally used ordinals:
`org.elasticsearch.search.aggregations.support.MissingValues$6 cannot be cast to org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals$FieldData`

**Comment by dam0vm3nt** [comment]
I can confirm di bug in `2.1.1` version of `ES`
