### ISSUE TITLE
SecurityManager policy for ES 2.0.0

### ISSUE THREAD

**Issue by jimmidyson** [elastic/elasticsearch#14880]
tl;dr Is there any way to provide a plugin security policy in 2.0.0?

Trying to update the [Kubernetes discovery plugin](https://github.com/fabric8io/elasticsearch-cloud-kubernetes) to ES 2.0.0 & can only get it to run by disabling security manager.

The plugin needs to read certain files from the filesystem outside of the normal ES paths & I've written a policy that works with a normal Java main running with a security manager. However I can see no way to apply this by packaging in the plugin, although I do see this is possible in master.

**Comment by nik9000** [comment]
Maybe have a look at what lang-groovy does in 2.x:
https://github.com/elastic/elasticsearch/blob/2.x/plugins/lang-groovy/src/main/plugin-metadata/plugin-security.policy

**Comment by jimmidyson** [comment]
That's what I thought I was doing... Does this work for 2.0.0 or only an unreleased 2.x version?

**Comment by rmuir** [comment]
We already document how to this in the plugin author's guide for 2.2+ (https://github.com/elastic/elasticsearch/pull/14108)

https://www.elastic.co/guide/en/elasticsearch/plugins/2.x/plugin-authors.html#_java_security_permissions

**Comment by jimmidyson** [comment]
Yeah I've seen that but is that supported in 2.0?

**Comment by rmuir** [comment]
No, it is coming in 2.2.

**Comment by jimmidyson** [comment]
OK thanks for feedback.

**Comment by pires** [comment]
This doesn't seem to be working. Here's a plug-in installation:
```
- Plugin information:
Name: cloud-kubernetes
Description: Elasticsearch Kubernetes cloud plugin
Site: false
Version: 2.2.1
JVM: true
 * Classname: io.fabric8.elasticsearch.plugin.discovery.kubernetes.KubernetesDiscoveryPlugin
 * Isolated: true
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission <<ALL FILES>> read
* java.net.NetPermission getProxySelector
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
Installed cloud-kubernetes into /elasticsearch/plugins/cloud-kubernetes
```

Here's one error when running it:
```
[2016-03-17 16:17:17,992][WARN ][io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider] [Chloe Tran] Exception caught during discovery: access denied ("java.net.NetPermission" "getProxySelector")
java.security.AccessControlException: access denied ("java.net.NetPermission" "getProxySelector")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.net.ProxySelector.getDefault(ProxySelector.java:94)
```

Any hints?

**Comment by pires** [comment]
Nevermind, got it to work. Missing the change in the code to run a privileged action.
