### ISSUE TITLE
Shell scripts should source elasticsearch.in.sh

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#14898]
Right now `bin/elasticsearch` sources a version of `elasticsearch.in.sh` - the first version it finds in a list of directories. All of our scripts should do that - including `bin/plugin` and any scripts we package as into plugins. I don't know that we should go so far as to automatically add it as part of the build process, but we should really make an effort to source the file in all the scripts.

This would allow:
1. We could move all the `/etc/sysconfig` et al handling into it rather than the init scripts and `bin/plugin`.
2. External packages could have a single place to stick their version of the `/etc/sysconfig` handling. See #14870 for FreeBSD wanting to do exactly this.

**Comment by rmuir** [comment]
Seems like we can do a nice refactoring here to ensure all of our scripts act in a consistent way. +1

**Comment by tlrx** [comment]
+1

**Comment by jasontedor** [comment]
Closed by #25815 and #25958
