### ISSUE TITLE
Require root-cause exception to ESLogger methods

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#14905]
This is a spinoff of #14867 where we failed to log the root cause exception in a catch clause that could have shed light on #14866.

I think we should require root cause exceptions to our logger methods to 1) fix the remaining places that swallow exceptions (I've hit maybe 2 dozen or so), and 2) reduce the chances of swallowing exceptions in new code going forward.

It means that those times when there is no exception, we'd have to pass null, but I think that's a fair tradeoff so we don't repeat #14866.

I had started to work on this for all except `trace`, but then came across at least one place that was trace-logging an exception (and I'm pretty sure we `debug` and `info` exceptions in quite a few places) so I decided to just make this a required argument for all `ESLogger` methods, but this is apparently controversial so let's discuss it here.

I could only do this for `error` and `warn` but I'm not sure how many places we are swallowing exceptions are using the other levels ...

Just to get a sense of the things I'm finding ... some are wrong-order-of-arguments, e.g.:

```
try {
  failReplicaIfNeeded(request.internalShardId.getIndex(), request.internalShardId.id(), t);
} catch (Throwable unexpected) {
  logger.error("{} unexpected error while failing replica", request.internalShardId.id(), unexpected);
} finally {
  responseWithFailure(t);
}
```

others do a catch but then do nothing with the exception:

```
} catch (Throwable t) {
  logger.warn("[{}] failed to refresh-mapping in cluster state, types [{}]", index, refreshTask.types);
}
```

Others only include `getMessage` from the exception but should (usually?) include the full exception ... the message by itself can be ... tantalizing:

```
if (cause instanceof ConnectTransportException) {
  logger.debug("delaying recovery of {} for [{}] due to networking error [{}]", recoveryStatus.shardId(), recoverySettings.retryDelayNetwork(), cause.getMessage());
```

**Comment by bleskes** [comment]
I'm +1 on chasing those places that catch an exception and log something without it and/or suppress the stack trace. This is bad and we should fix it I'm also +1 on preventing the sad but common mistake of putting the exception in the wrong place in the parameter list.

To that fact I'm +1 on requiring a throwable parameter to the error and warn log methods. Those are typically used in an error context and I feel that's the right trade off there.

However, when it comes to info/debug/trace that are used in many places which has nothing to do with an exception/error it feels like a big overkill and an unnatural restriction. To me it goes a step too far.

> Others only include getMessage from the exception but should (usually?) include the full exception ... the message by itself can be ... tantalizing

I think Robert wants to put `getMessage` on the forbidden list. This will prevent this as well, right?

**Comment by mikemccand** [comment]
OK I'll explore only requiring an exception for error and warn levels.  But we do unfortunately handle exceptions with info/debug/trace in places (not sure howe often, hopefully it's rare-ish) which means we lose enforcing those cases...

> I think Robert wants to put getMessage on the forbidden list. This will prevent this as well, right?

And also `.toString()` ... I'll try that too.

**Comment by bleskes** [comment]
Thanks Mike.

>  But we do unfortunately handle exceptions with info/debug/trace in places (not sure howe often, hopefully it's rare-ish) which means we lose enforcing those cases...

I'm happy to help going through the list and review/fix the current things you found...

**Comment by luizamboni** [comment]
i m using 1.7 version, i do the exactly ando not appears in my elasticsearch.log file

**Comment by luizamboni** [comment]
import org.elasticsearch.common.logging.*;
import java.text.SimpleDateFormat;

```groovy
sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");

product_prices_gt_than_min = _source.product_prices.findAll{ 	
	sdf.parse(it["created_at"]).time.toInteger() >= min_date_in_millis
}

product_prices_gt_than_max_too = product_prices_gt_than_min.findAll{ 	
	sdf.parse(it["created_at"]).time.toInteger() <= max_date_in_millis
}

ESLogger logger = ESLoggerFactory.getLogger('product_prices_count_aggs');
println "#############################################";
logger.debug("#############################################");
logger.debug(product_prices_gt_than_min.size);
logger.debug(product_prices_gt_than_max_too.size);


return product_prices_gt_than_max_too;
```

**Comment by s1monw** [comment]
I think we should start simple and make sure (assert) that any of the var args is not an exception. This will not catch all the places (only the once we exercise in our tests and it will not blow up in production but it's a good start I think.

**Comment by luizamboni** [comment]
its not throws any error, the script woks...but not white log in anywhere...what make me more blind about what is happening...whithout any message that i can understand
the script product_prices_gt_than_max_too;

**Comment by jasontedor** [comment]
@luizamboni The issue that you are working through is unrelated to the issue under discussion here. May I suggest reaching out on #elasticsearch, or on the [forums](https://discuss.elastic.co)?

**Comment by dakrone** [comment]
I think this might be something we are no longer able to do, since we moved to not having `ESLogger` and use Log4j2's methods now instead, so it can be closed. Feel free to re-open if I'm mistaken.
