### ISSUE TITLE
Retrieve parent id from the request

### ISSUE THREAD

**Issue by ayushsangani** [elastic/elasticsearch#14907]
Support to retrieve parent id once set through any request, irrespective of routing is set or not.
According to current codebase you can only retrieve parent id if it's not overwritten by routing.
As child documents can have same or different routing and parent id, depending on whether routing is enabled or not.

For example: GetRequest API
Let me know if I can help.

**Comment by clintongormley** [comment]
This works today:

    PUT t
    {
      "mappings": {
        "grandparent": {},
        "parent": {
          "_parent": {
            "type": "grandparent"
          }
        },
        "child": {
          "_parent": {
            "type": "parent"
          }
        }
      }
    }
    
    PUT t/grandparent/1
    {}
    
    PUT t/parent/2?parent=1
    {}
    
    PUT t/child/3?parent=2&routing=1
    {}
    
    GET t/child/3?fields=_parent,_routing&routing=1
    
The search request returns all stored meta fields by default

    GET t/_search
