### ISSUE TITLE
Add circuit breaker and/or cap for fixedbitset

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#14919]
Some users in the field have nodes that are running out of memory due fixedbitset cache using the majority of the heap.  See #10224.  Some of them are already on 1.7.x which means that they have the fixes that will help reduce the amount of fixedbitset loaded (#8440 and #8454).  It will be helpful to add protection to the product to prevent OOM scenarios.  Users are currently working around this by disabling eager loading of fixedbitsets (#14903) - and hoping that it will not eventually lazy load enough fixedbitset to hit the OOM again.

**Comment by jpountz** [comment]
Discussed in Fixit Friday: there is a broader issue that nested fields are often abused, and fixedbitset memory usage is only one of the symptoms. The soft limit for nested fields that is proposed on #14983 should help avoid this issue most of the time.

Separately, we should work on ways to not have to load things into memory at all for nested. One obvious option would be to use numeric doc values, but there might be even better options.

**Comment by schlosna** [comment]
It is a bit concerning that any unbounded "cache" exists which can grow and take nodes down due to OutOfMemoryError. Is it not feasible to provide reasonable bounds and circuit breakers to prevent this from occurring? Should we not also be able to flush the fixed bitset cache independently from other caches?

**Comment by jpountz** [comment]
I don't like the memory usage of these bitsets either, hence my comment to move to disk-based data-structures.

Currently it is implemented as a cache, but it should really be part of the index. Every query that needs to load one entry in this cache is doomed to run in linear time with the number of documents in the index (like a linear scan), which is something that we usually try to avoid by all means.

I suspect that if these bitsets are an issue for memory usage, most of the time it means that there are many nested mappings, in which case memory usage of these bitsets is only one of the problems. Nested fields increase the sparsity of the index, which makes things less efficient in terms of disk, cpu and memory usage.

**Comment by rmuir** [comment]
what happened to the idea to disable the dynamic generation of these? I think thats the root cause.
