### ISSUE TITLE
Sort and truncate pipeline aggregation

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#14928]
This would be a parent pipeline aggregation which would take the following option:
- Sort - a bucketsPath that defines the aggregation(s) in each bucket to use to sort the buckets in the parent aggregation. If this is not provided no sorting is done on the buckets
- Offset - all buckets before this index in the sorted buckets list will be removed. Defaults to 0 (i.e. don't remove any buckets from the beginning of the list)
- Size - all buckets after `offset + size` index in the sorted buckets list will be removed. Defaults to `buckets.size()` (i.e. don't remove any buckets from the end of the list)

**Comment by eskibars** [comment]
+1

**Comment by taowen** [comment]
+1

**Comment by davyfeng** [comment]
+1

**Comment by appasahebs** [comment]
+1

**Comment by bibinbin** [comment]
+1

**Comment by soulne4ny** [comment]
+1

It is quite surprising that `bucket_script` is so much different from other aggregations that ordering aggregation buckets by `bucket_script` is impossible. `order` clause just does not see a `bucket_script` name.

**Comment by dizzzyroma** [comment]
+1

**Comment by waiter** [comment]
+1

**Comment by dizzzyroma** [comment]
Any ideas when this will be in production?

**Comment by gqy2468** [comment]
+1

**Comment by xavigonz** [comment]
+1

**Comment by SimonKlausLudwig** [comment]
+1

**Comment by developerworks** [comment]
+1

**Comment by thao6626** [comment]
+1

**Comment by smarsico** [comment]
+1

**Comment by 54ebb** [comment]
+1

**Comment by claudiuolteanu** [comment]
+1
