### ISSUE TITLE
documentation error - Offline update 

### ISSUE THREAD

**Issue by gadin** [elastic/elasticsearch#14924]
https://www.elastic.co/guide/en/marvel/current/installing-marvel.html#offline-installation

Says bin/plugin install file:///...
the right command and what plugin install -h says:  bin/plugin install file:/...

**Comment by clintongormley** [comment]
@gadin the existing instructions work for me.  Why do you think it is incorrect?

**Comment by clintongormley** [comment]
no further feedback. closing
