### ISSUE TITLE
Mapping 

### ISSUE THREAD

**Issue by mabodo** [elastic/elasticsearch#14929]
I just started learning elasticSearch.

I don't know anything about previous versions of elasticSearch, so my first inputs has been with elastic 2.0.

I used the "official" documentation in order to understand how does it work and how to interact.
I must say that for me was quite strange, that the Search APIs was explained much before the Mapping.

While trying examples of the Search API on local, i was wondering why the endpoints where not working.

I hope this feedback can help improve the Doc's.

DAVID

P.S: not sure if this is the right place to put this feedback.

**Comment by clintongormley** [comment]
thanks for the feedback @mabodo - it's tricky to get this right.  For instance, very often you can rely entirely on dynamic mappings.  We try to introduce these subjects in a more useful order for the beginnger in the [Definitive Guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html)
