### ISSUE TITLE
Create multi nodes on single cluster into ES 2.0

### ISSUE THREAD

**Issue by cirot87** [elastic/elasticsearch#14930]
Hi, is possible to create a multi nodes on a single cluster into ES 2.0?
I've tried the common config and some console commands but both don't work.
I known that some console commands are disabled but i can't create a second node on my db.

Someone can help me???

**Comment by dadoonet** [comment]
Please join us on discuss.elastic.co.

We can help you better there.

We use this only for bug reports.
