### ISSUE TITLE
more_like_this doesn't understand index alias in doc reference

### ISSUE THREAD

**Issue by leonid-s-usov** [elastic/elasticsearch#14944]
After upgrading from 1.7 to 2.0 I have got a problem with my more_like_this query, which stopped returning results. 

Playing around with the query I was surprised to know that if I set a "like" document "_index" to an alias, no results are returned. When set to the real index name matches are found.

```
GET /_cat/aliases?v&h=alias,index

alias    index         
traits   traits_1123   
analysis analysis_1123 
catalog  catalog_1123  
```

```
POST /traits/library/_search
{
    "filter": {
        "query": {
            "more_like_this": {
                "min_doc_freq": 1, 
                "fields": ["data.packages"], 
                "min_term_freq": 1, 
                "docs": [
                    {
                        "_type": "packages", 
                        "_id": "1_401f94", 
                        "_index": "analysis"
                    }
                ]  
            }    
        }
    }
}

{
   "took": 12,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 0,
      "max_score": null,
      "hits": []
   }
}
```

```
POST /traits_1123/library/_search
{
    "filter": {
        "query": {
            "more_like_this": {
                "min_doc_freq": 1, 
                "fields": ["data.packages"], 
                "min_term_freq": 1, 
                "docs": [
                    {
                        "_type": "packages", 
                        "_id": "1_401f94", 
                        "_index": "analysis_1123"
                    }
                ]  
            }    
        }
    }
}

{
   "took": 23,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 12,
      "max_score": 1,
      "hits": [
         {
            "_index": "traits_1123",
            "_type": "library",
...
```

**Comment by adnansel** [comment]
Same here with v2.1.0. The "more_like_this" doesn't return values if an alias is provided.

**Comment by leonid-s-usov** [comment]
I even looked at the latest code, but found nothing suspicious.. I am far from knowing the code well, but it seems that the semantics of getting the termvectors from the document is the same as in the _mtermvectors action, which does work with the same format of document specification, both when using alias and concrete name. We definitely need tome attention from the elasticsearch source guru

**Comment by leonid-s-usov** [comment]
Rolled back to 1.7 eventually :/
Hopefully this will get fixed soon

**Comment by mstockerl** [comment]
I might found the problem at hand, but I need some help to fix it. 

As @leonid-s-usov pointed out, the problem occurs after the termvectors were fetched. 
[The responses from the **MultiTermVectorsRequest** are filtered for the given indices of the client call.](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/query/MoreLikeThisQueryBuilder.java#L931)
As the responses contain the actual index and _not_ the alias name, every response gets filtered out. 

I think this check should also consider the alias of the indices. 
Can someone give me a hint, how to resolve this issue? I'm not sure, where to best fetch the information about the alias -> index mappings. 

Thanks in advance.

**Comment by brwe** [comment]
Had a brief discussion with @jpountz who agrees that the decrease in performance is probably negligible. Backported to 2.x 2.3 and 2.2 (e4c20ab, 884ad25 and 4dcdd95). Thanks again @mstockerl !
