### ISSUE TITLE
Could elasticsearch highlight wildcard query search term?

### ISSUE THREAD

**Issue by ryanchou1991** [elastic/elasticsearch#14943]
I haven't find the way to highlight my wildcard query term. as following steps

* Create index

```
curl -XPUT 'http://127.0.0.1:9200/foo' -d '{
    "settings" : {
        "index" : {
            "number_of_shards" : 1
        }
    }}'
```

* Create mapping 

```
curl -XPOST http://127.0.0.1:9200/foo/_mapping/test -d '
{
    "test" : {
        "properties" : {
            "content" : {"type" : "string", "store" : true, "index": "not_analyzed", "doc_values": true}
        }
    }
}
'
```

* Index Some documents

```
curl -XPUT http://127.0.0.1:9200/foo/test/1 -d '{"content": "this is a foobar documents"}'
```

* Search in wildcard query (with highlight)

```
{
  "query": {
    "bool": {
      "should": [
        {
          "wildcard": {
            "content": "*foo*"
          }
        }
      ]
    },
"highlight": {
    "fields": {
      "content": {}
    }
  }
  }
```

While I try another highlight options from the highlight referrences https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html
such as `{"term_vector" : "with_positions_offsets"}` ... those options don't make any sense. 

Those responses were like that

```
"highlight": {"content": "<em>this is a foobar documents</em>"} 
```

While the final highlight result I expected was  

```
"highlight": {"content": "this is a <em>foo</em>bar documents"} 
``` 

Just only highlight `foo` term

Could anyone help me this issue? 
Did I miss some options which could get the expected results or elasticsearch doesn't provided highlight wildcard query term?

**Comment by nik9000** [comment]
> Could anyone help me this issue? 

It doesn't support what you want sadly. Highlighting is on the terms and wildcard queries expand to a list of matching terms. As much as I'd love to support the thing you are asking for I don't see that happening any time soon.

**Comment by ryanchou1991** [comment]
@nik9000 Thanks for your ˙help. Is there any measure I could take for getting my expected results?
Or would elasticsearch plan to provide highlight wildcard term option to support this? I thought it could be a normal requirement  and not to hard to implement : ) 

or I just only highlight it in the front-end.

**Comment by nik9000** [comment]
> I thought it could be a normal requirement and not to hard to implement : )

The trouble is that not much work is going on in highlighting _and_ wildcard queries are generally a bad way to do full text search anyway. They are orders of magnitude slower than getting the analysis chain right for your use case. *and* that the way that it currently works does a better job of explaining what is happening during search. And that is one of the goal of highlighting.

So, yeah, the supported way to do all this is to make the analyses spit out the terms you want to find and do match queries. For that read more about analysis. And if you need to do some kind of analysis that isn't built in then file an issue around that.

**Comment by ryanchou1991** [comment]
OK, I was so appreciated for your help and suggestions : ). I have read the chapter about the analysis. and known the reason why it isn't better to highlight in wildcard query.Thanks so much for your answer. :+1:

**Comment by Durisvk** [comment]
I needed this feature.. now I have to go through the all hits and do it by myself....

**Comment by xiaoshua** [comment]
I have the same problem as you. My temporary solution is as follows:
```java
    /**
     * assume the origin content has no "<em>" and "</em>".
     */
    public static String adjust(String content, String searchKey) {
        if (searchKey.length() >= 10) {
            return content;
        }
        content = StringUtils.replace(content, "<em>", "");
        content = StringUtils.replace(content, "</em>", "");
        content = StringUtils.replace(content, searchKey, "<em>" + searchKey + "</em>");
        return content;
    }
```
