### ISSUE TITLE
Failed to start elasticsearch in IT for tar distribution on windows

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#14941]
This seems to happen on windows only:

http://build-us-00.elastic.co/job/es_core_master_window-2008/2574/console

```
:distribution:tar:integTest#wait FAILED
:distribution:tar:integTest#wait (Thread[main,5,main]) completed. Took 30.087 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':distribution:tar:integTest#wait'.
> Failed to start elasticsearch
```

**Comment by colings86** [comment]
This is happening fairly regularly on the windows builds. Today there are 3 failures like this in 2 hours this morning. Example of one of the failures: http://build-us-00.elastic.co/job/es_core_master_window-2008/2595

**Comment by rmuir** [comment]
These are fixed by @rjernst commit https://github.com/elastic/elasticsearch/pull/15098
