### ISSUE TITLE
Terms Aggregation Include/Exclude RegEx does not work in case multi-region matches, look ahead groups etc

### ISSUE THREAD

**Issue by roytmana** [elastic/elasticsearch#14942]
RegEx like ```(?=.*elastic)``` will match nothing. I it is because java Matcher.matches() may be used in elastic to implement it and it would not work with multi region scenarios. I think Matcher.find() should be used instead. I did not look in Elastic code for this but simulated exact behavior with using matches() vs find()

**Comment by clintongormley** [comment]
Correct - we use the more limited but safer and faster Lucene FST regexes, not Java regexes here.  We're not planning on changing this
