### ISSUE TITLE
Concurrent calls to scroll API scrambles results

### ISSUE THREAD

**Issue by TheDeveloper** [elastic/elasticsearch#14954]
I'm not sure whether this is by design or not, but it appears that calling the scroll API with multiple requests to the same scroll ID concurrently will return mixed up results, whereby the meta fields (`_index`, `_type`, `_id` etc) get put together with the wrong document `_source`.

I've written a JS [migration script](https://gist.github.com/TheDeveloper/e91f7b7044d4f3a33b2f) for node which uses redis to parallelise scroll requests across multiple workers / machines. The idea is to scale the number of fetches on the scan/scroll ID to speed up migration. If it changes, the new ID is picked up by the workers via Redis.

It works fine when running a single worker, which procedurally calls scroll, receives the documents then bulk inserts them to the new cluster before performing another scroll request. However, as soon as I start up a further one or more parallel workers, which will start issuing multiple requests to the scroll API at the same time, I start seeing weird results coming back, whereby the meta fields are being mixed up with `_source` bodies from other documents as mentioned above.

Is this expected behaviour when multiple scroll requests are reading from the same scroll ID at the same time?

The script uses the official elasticsearch-js client node module, v8.2.0. I don't think there should be anything in the client causing this given that all it does is streams the http response and JSON decodes it.

I'm seeing this on a 10-node cluster running ES 1.7.1. There are thousands of type mappings and hundreds of millions of documents in 2 indexes split into a dozen shards each.

**Comment by bleskes** [comment]
The scroll API is indeed intended to be consumed by a single thread. You can open multiple scrolls concurrently. That's not a problem.

**Comment by TheDeveloper** [comment]
Ok, makes sense. Thanks for clarifying.

Would it be worth considering responding with an error to clients if they try to read from the scroll API from more than one request at the same time? Despite it being incorrect usage I am still able to do it and it results in broken behaviour. I'm thinking this'd be particularly helpful preventing async clients from accidentally overlapping their requests.

Also, perhaps a note could be added to the docs [https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-request-scroll.html](docs) about this.
