### ISSUE TITLE
Handle missing logging.yml better

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#14953]
If you start Elasticsearch and use a custom configuration directory (eg. --path.conf) and do not copy over the logging.yml file, the node will start up but with no log files generated and the following message written to standard out:

```
log4j:WARN No appenders could be found for logger (bootstrap).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

The log4j link will take you to a generic faq page:

```
Why do I see a warning about "No appenders found for logger" and "Please configure log4j properly"?
This occurs when the default configuration files log4j.properties and log4j.xml can not be found and the application performs no explicit configuration. log4j uses Thread.getContextClassLoader().getResource() to locate the default configuration files and does not directly check the file system. Knowing the appropriate location to place log4j.properties or log4j.xml requires understanding the search strategy of the class loader in use. log4j does not provide a default configuration since output to the console or to the file system may be prohibited in some environments. Also see FAQ: Why can't log4j find my properties in a J2EE or WAR application?.
```

Not sure if there is a way for us to catch this and report a more Elasticsearch specific warning to the log indicating that the logging.yml file cannot be found at <location>, etc..

**Comment by dadoonet** [comment]
++ I think we should try to fallback to a default one available in the classloader or fail starting elasticsearch if this file is mandatory.

I'd prefer the former.

**Comment by rjernst** [comment]
@dadoonet Don't we ship our distributions with a logging.yml? I don't think we should be lenient. Otherwise, the user may not realize that their configuration is not getting picked up, for example, with a misnamed file or the file in the wrong location.

**Comment by kimchy** [comment]
note that this is not required when someone embeds us, and it is their responsibility to configure logging external to us.

**Comment by aodj** [comment]
Whats the fix for this? I'm currently trying to upgrade from 1.7 to 2.0 and the (previously working) argument of `-Des.default.path.conf=...` just leaves me with no logs.

**Comment by rmuir** [comment]
I agree the warning is not helpful, it is the worst to get with a java application. I understand people use this as a client library too, but it would be great, when running as a server to fail with a simple `NoSuchFileException("/wherever/conf/logging.yml")`. Then the user has a chance to correct it without reading a bunch of confusing logging FAQ etc.

**Comment by aodj** [comment]
As a further point of discussion: this error presents even when the `logging.yml` file is present, but incorrectly configured. I was trying to debug an issue whilst trial running the upgrade between 1.7 and 2.0 and ran into this problem. As a result I stumbled upon  this Github issue and concluded that the problem lay with the `logging.yml` file not being found, only to later discover that this same error message is displayed if the logging system fails to initialise properly. 

You can read more [here](https://discuss.elastic.co/t/logging-not-initialised-properly-after-upgrade-to-2-0/35542/4?u=aodj) including [diffs](https://www.diffnow.com/?report=k2hax) between the shipped (and working `logging.yml`) and the one that I was using (which worked with 1.7)

**Comment by clintongormley** [comment]
Closing in favour of #16585
