### ISSUE TITLE
Cannot configure AsyncAppender in logging.xml

### ISSUE THREAD

**Issue by sweetest** [elastic/elasticsearch#14956]
In our team, we tried to configure AsnycAppender in ES version 1.7.3 and 2.0.0, we tried bunch of stuffs but finally found out that it is not possible from the beginning.

In the below source codes, ES reads logging.* file and make it as java properties, pass it to PropertyConfigurator of log4j 1.2.17

https://github.com/elastic/elasticsearch/blob/v1.7.3/src/main/java/org/elasticsearch/common/logging/log4j/LogConfigurator.java
https://github.com/elastic/elasticsearch/blob/v2.0.0/core/src/main/java/org/elasticsearch/common/logging/log4j/LogConfigurator.java

but in the links below it says this.
https://github.com/apache/log4j/blob/v1_2_17/src/main/java/org/apache/log4j/PropertyConfigurator.java
```
   <p>The <code>PropertyConfigurator</code> does not handle the
   advanced configuration features supported by the {@link
   org.apache.log4j.xml.DOMConfigurator DOMConfigurator} such as
   support custom {@link org.apache.log4j.spi.ErrorHandler ErrorHandlers},
   nested appenders such as the {@link org.apache.log4j.AsyncAppender
   AsyncAppender}, etc.
```

How about using DOMConfigurator when logging configuration is set in logging.xml?

**Comment by jasontedor** [comment]
Closing in favor of #17697.
