### ISSUE TITLE
Make Java Client API composable

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#14961]
### Background / High Level Goal

While working on #14620 I noticed that the current listener-based client API does not compose, i.e. I cannot build processing pipelines based on a response future.

For example, in the Java client implementation classes, I want to write code like:

```
// 'X' is some not yet specified interface potentially extending ActionFuture 
// for backwards compatibility
public X<BulkRequest> bulk(BulkRequest request) {
   return Retry.withBackoff(() -> client.bulk(request))
     // not important here what #doCleanup does exactly
    .onCompletion((response) -> doCleanup()) 
    .onException((ex) -> doCleanup());
}
```

And I want to do all that without knowing what any potential caller of the Java client API is doing. The caller should just be able to add its operations on top, i.e. we want to build a pipeline of operations, e.g.:

```
client()
  .bulk(request)
  .onCompletion((response) -> updateUI())
  .onException((ex) -> showErrorMessage(ex));
```

### Current Status

Chaining of listeners is currently also doable but listeners need to delegate explicitly and the code gets very tightly coupled and ugly.

### Possible Solution Approach

Starting with Java 8, the JDK provides `CompletableFuture` which allows to create processing pipelines. However, the `CompletableFuture` API is very hard to understand and I doubt we need its whole complexity for our use case.

Nevertheless, it could be worthwhile to base the internal implementation on `CompletableFuture` and just expose parts the API.

### Necessary Steps

1. Start investigating whether `CompletableFuture` is a good fit for our requirements and flesh out an updated client API (ideally without breaking backwards compatibility, even on master)
2. Deprecate `ActionListener` and all methods in the Java client API that take one as parameter (to be removed with next major version)
3. Add new methods to `ActionFuture` to allow for chaining. This way, the current API methods that return an `ActionFuture` will stay but we can get rid of all `ActionListener` methods. Deprecated methods based on `ActionListener` can be simply reimplemented internally on top of the new API.
4. Revisit implementations of ActionFuture (whether we still need them at all) and provide a new default implementation that delegates to `CompletableFuture`
5. Update the client documentation with hints on how to migrate the API
6. (As separate PRs) Adapt internal implementation to take advantage of pipelining.

**Comment by javanna** [comment]
I think we need to make up our minds on whether and when we are going to have a java REST client that will ideally replace the java api for users, so that the java api becomes mainly internal. And whether the REST client should implement the same `Client` interface or not. Also this proposal makes me think about #9201 which is about changing the java api too, but if we are going to have a REST client, seems like these changes are relevant only if we need things internally.

**Comment by danielmitterdorfer** [comment]
@javanna Thanks for the pointer to the other issue, I wasn't aware of that. As the other one already touches this topic (and even in a broader context), I sense it would be best to keep the discussion in #9201 and close this one.

**Comment by danielmitterdorfer** [comment]
I'm closing this now as Luca has already pointed to #9201 and to me this is just a duplicate of that ticket.
