### ISSUE TITLE
Crating index with setting and mapping  v2.0

### ISSUE THREAD

**Issue by 1amirjalai** [elastic/elasticsearch#14978]
Crating index with setting and mapping  in version 2.0 throws following error while in version 1.7 everything is fine. the same command

```
"error": {
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "malformed, expected settings to start with 'object', instead was [VALUE_STRING]"
      }
    ],
```

**Comment by dadoonet** [comment]
Well you need at least to explain what you did.

**Comment by 1amirjalai** [comment]
I send a request like this 

Url: http://xxxxxxx:9200/xxxxxx, 
	Request: {
  "settings": {
       "index": {
      "analysis": {
        "analyzer": {
          "autocomplete": {
            "tokenizer": "standard",
            "filter": [
              "lowercase",
              "autocompletefilter"
            ],
            "type": "custom"
          },
.
.
.
.
.

.
.

.
"mappings": {
    "ppppp": {
      "properties": {
        "productId": {
          "type": "integer"
        },

.
...
.
.
.
.

**Comment by dadoonet** [comment]
It sounds good. But I can't really tell if I can not reproduce with a concrete example.
I totally understand that you don't want to send all details which is perfect but could create a reproduction script which would help to understand what is happening?

In case you missed it, also read https://www.elastic.co/guide/en/elasticsearch/reference/2.1/breaking-changes-2.0.html. May you are doing something which is not allowed anymore.

**Comment by clintongormley** [comment]
We are now stricter about not ignoring malformed JSON or incorrect parameters.  Without the actual request that you sent, this will be difficult to diagnose.

**Comment by clintongormley** [comment]
No further feedback. Closing
