### ISSUE TITLE
fix gradle to populate plugin list for bats tests?

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#14972]
I always forget this one when adding/backporting a plugin: latest instance https://github.com/elastic/elasticsearch/pull/14970

One of the pain points with maven was adding plugins/jars, you had to modify the build in like 87 different places to update various lists. I think we should try to reduce this in general. I know we can improve it, since for example qa/smoke-test-plugins no longer has a hardcoded list and instead just "includes all plugins".

There are a few other places with this redundancy too: the help file for pluginmanager, also one of its tests has the same list of plugins and we should think about those too.

As far as the bats test goes, one trick i see is that it needs to behave differently if the plugin is just a site plugin.

**Comment by nik9000** [comment]
We could certainly be more automatic here, yeah.

**Comment by hub-cap** [comment]
This issue will be closed due to inactivity. If you feel it should be reopened, do not hesitate to comment on the issue.
