### ISSUE TITLE
Does NodeJS client support(Node Client) like Java client ?

### ISSUE THREAD

**Issue by sunchanras** [elastic/elasticsearch#14985]
Hi,
Does NodeJS client support automatically traffic routing to the node need to process the request like, Java client does (node client).
In Java client, application know which node need to process the request, so reduce network hop from two to only one. Does this feature exist in NodeJS client ?

Thank.

**Comment by clintongormley** [comment]
This is the right repo for the JS client: https://github.com/elastic/elasticsearch-js
