### ISSUE TITLE
Set soft limit on the number of nested fields per index

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#14983]
Today dynamic templates can be used to eg. dynamically map objects to "nested" fields. This is quite dangerous as nested fields limit the scalability of indices. For instance an index that has 1M docs with 100 nested docs each requires as much resources as a 100M docs index. By forbidding dynamic mappings on object fields, we would at least ensure that all the nested mappings are explicit.

**Comment by clintongormley** [comment]
Discussed in FixItFriday, decided:

* Need to add documentation explaining the costs incurred by nested fields
* Add a per-index soft limit (safeguard, see #11511) on the number of nested fields

**Comment by ywelsch** [comment]
I discussed this with @jpountz, and the current implementation of mappings would need this check to be baked into the implementation of simulating the merging of mappings, which makes it unnecessarily complicated. At the moment, work is under way to make this easier (separate merge and update of mappings, see #15313), so we would only need to check the limit on the merged mapping before updating it.
