### ISSUE TITLE
Snapshot API: Use local time zone in _snapshot output

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#14987]
In the Snapshot API, would it be possible to show local time instead of Zulu time?

```
GET _snapshot/woodfield-repo/_all

{
  "snapshots": [
    {
      "snapshot": "snapshot_1",
      "version_id": 1070399,
      "version": "1.7.3",
      "indices": [
        "logstash-2015.11.10"
      ],
      "state": "SUCCESS",
      "start_time": "2015-11-10T22:09:42.135Z",
      "start_time_in_millis": 1447193382135,
      "end_time": "2015-11-10T22:09:42.884Z",
      "end_time_in_millis": 1447193382884,
      "duration_in_millis": 749,
      "failures": [],
      "shards": {
        "total": 3,
        "failed": 0,
        "successful": 3
      }
    }
  ]
}
```

**Comment by inqueue** [comment]
customer feature request

**Comment by clintongormley** [comment]
Of course, a client in Europe requesting info from a server in the US may well want the client's local time zone, instead of the server's time zone.  Perhaps time zone could be passed in as a parameter instead.

**Comment by bleskes** [comment]
If we do anything here we should be indeed be explicit and allow the user to specify the time zone we will to use to render date fields. That said IMO we should just stick to using UTC for everything and let any client layer/UI  do the translation, at least for the moment. This a rabbit hole as we all know.

**Comment by ywelsch** [comment]
Discussed with @tlrx: This would affect all our APIs, not only snap/restore. This would be a major change, and we agree with @bleskes that this is not worth pursuing at this time.
