### ISSUE TITLE
Better documentation for enabling slowlogs

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#14980]
Currently we mention that slowlogs can be enabled dynamically, and we have an example of how to enable them in the configuration. However it is much useful to have an example to how to enable it dynamically per index.

Looks like we have added more information that this is a **per index settings** which is great, but having examples for this will be better since for production environment we don't wan't to stop nodes to enable it.

**Comment by mahdibh** [comment]
It would also be great to clarify what exactly is the latency that the slow log reports. Is that total time since the query was received (ie, including time sitting in the queue) or is that purely the time it took once a search thread picked up the request from the queue

**Comment by jasontedor** [comment]
I do not think that we need additional documentation here above what these settings are (which are documented) and how to update dynamic index settings (which is documented). Closing.
