### ISSUE TITLE
What is the best way to compress a snapshot data?

### ISSUE THREAD

**Issue by notxcain** [elastic/elasticsearch#14984]
We have a lot of data in our daily indexes (like 200GB), so what is the best way to compress a daily index snapshot. As we need to store some of them up to 6 month due to legal issues.

May be it worth adding snapshot data compression along with metadata?

**Comment by clintongormley** [comment]
Hi @notxcain 

The best place to ask questions like these is the forum: http://discuss.elastic.co/

**Comment by notxcain** [comment]
Ok! Here it is https://discuss.elastic.co/t/what-is-the-best-way-to-compress-a-snapshot-data/35990
