### ISSUE TITLE
##如何对aggregations聚合结果在进行条件查询，过滤出符合条件的buck，针对es2.0

### ISSUE THREAD

**Issue by zqr688** [elastic/elasticsearch#14995]
例如
**一、数据源**
curl -XPUT 'http://localhost:9200/order/static_type/1' -d '{  "orderid": "00001","time":1,"f1":"A" }'
curl -XPUT 'http://localhost:9200/order/static_type/2' -d '{  "orderid": "00001","time":2,"f2":"B1" }'
curl -XPUT 'http://localhost:9200/order/static_type/3' -d '{  "orderid": "00001","time":3 ,"f2":"B2","f3":"C1"}'
curl -XPUT 'http://localhost:9200/order/static_type/4' -d '{  "orderid": "00001","time":4 ,"f3":"C2"}'
curl -XPUT 'http://localhost:9200/order/static_type/5' -d '{  "orderid": "00001","time":5 ,"f4":"D"}' 
curl -XPUT 'http://localhost:9200/order/static_type/6' -d '{  "orderid": "00001","time":6 ,"f5":2}'
curl -XPUT 'http://localhost:9200/order/static_type/7' -d '{  "orderid": "00002","time":1 ,"f1":"E"}'
curl -XPUT 'http://localhost:9200/order/static_type/8' -d '{  "orderid": "00002","time":3 ,"f1":"A","f2":"B"}'
**二、按orderid做aggregations聚合**
{
  "aggregations": {
    "orderid": {
      "terms": {
        "field": "orderid"
      },
      "aggregations": {
        "f2s": {
          "terms": {
            "field": "f2"
          }
        },
        "f1s": {
          "terms": {
            "field": "f1"
          }
        },
        "tmax": {
          "max": {
            "field": "time"
          }
        },
        "tmin": {
          "min": {
            "field": "time"
          }
        }
      }
    }
  }
}
**三、结果两条记录：**
![image](https://cloud.githubusercontent.com/assets/4476265/11390685/66fee60c-9387-11e5-9755-7f8f7cdfe162.png)

**四、想要的结果就是，对三中的两条聚合结果记录集合能够根据orderid，f1s,f2s 作为查询条件，如果不符合查询条件的对应整条不要。**
相当于将聚合结果作为第二次查询的数据源，例如，**筛选f1s=e  AND f2s =b的结果，想得到的是上述三中00002 这一行数据**。
**请问需要怎样在上述json上加上筛选条件，谢谢！**
{
  "aggregations": {
    "orderid": {
      "terms": {
        "field": "orderid"
      },
      "aggregations": {
        "f2s": {
          "terms": {
            "field": "f2"
          }
        },
        "f1s": {
          "terms": {
            "field": "f1"
          }
        },
        "tmax": {
          "max": {
            "field": "time"
          }
        },
        "tmin": {
          "min": {
            "field": "time"
          }
        }
      }
    }
  }
}

**Comment by xzer** [comment]
这里不是寻求帮助的地方，这里是报告bug的地方，如果你需要帮助，应该去论坛而不是这里。而且，这里的交流语言是英语，而不是中文。

This place is for bug reporting rather than usage help, if you need help, you should go to the forum. And also the communication language of this place is English rather than Chinese.

**Comment by dadoonet** [comment]
Yes. Please use https://discuss.elastic.co/c/in-your-native-tongue and choose your favorite language there :)

**Comment by zqr688** [comment]
OK，Thank you!
