### ISSUE TITLE
[Ingest] Pipeline template usage 

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#14990]
This issue's purpose is to collect ideas on mustache template usage in pipelines. The mustache initial template support will be added via the `meta` processor (#14991), but it leaves adoption of templates by other processors open. 

Open questions:
* What other processors and settings should be templatable? If some options are just strings and some are templates then how should ingest know this at pipeline parse time? Do we need a template json object that distinguish between a template or regular string? Or any string that contains `{{` and `}}` is considered a template. The latter makes things less verbose IMO.
* How should we refer to the original document in the pipeline? Right now in the meta processor the source of the document being processed is directly accessible in the moustache template, but maybe we want to make the the source available under the `_source` prefix? (e.g. `_source.field1` or `_source.field1.field2` etc.) This allows to for example put metadata attributes of document being processed under a different prefix. Also do we want like the update api use the `ctx` prefix in front of `_source`?
* It isn't possible the access array/list elements in the current mustache implementation. I think we want to add support for that?

**Comment by martijnvg** [comment]
About how to refer to _source and metadata: There should be no need to add special variable prefixes in templates like: `ctx.*` or `ctx._source.*`. A regular field name in ES can't with an underscore and that is only reserved for meta data fields.

So referring to routing can just be done like this: `some string {{_routing}}` and a normal field  is just `some string {{my_field}}`. We can just use the convention that already exists in ES' mapping.

For ingest specific pipeline variables we can add a special `_ingest` field to document while it is in the pipeline. So the ingest timestamp can just be accessed like this in templates: `some string {{_ingest.ingest_timestamp}}`. The `_ingest` field will only be available during the pipeline execution and will not end up in the actual index request that is being send to the ES. (only ES metadata will end up being added to the index request send to the index / bulk api)

**Comment by martijnvg** [comment]
The plan forward with templating:
* Since many processors will allow templating for a subset of settings there should be template infrastructure for this. The idea is now that `IngestDocument` will accept a value type instead of a map of maps. This value type can be a simple string, map of maps, templated string or a map of maps with a bunch of templated values. A processor implementation is responsible for providing the right value type implementation. So if tempating is allowed for an specific setting and an templated string is provided then the value type impl makes sure that when the value type is going to be resolved into its native representation the templates string gets resolved too.
* Both template config keys and values can be temptable, but this is up to the processor. 
* The syntax in previous comment will be used. There is a conflict with the `_ingest` field that will hold pipeline specific variables, because there can also be a field in the _source named `_ingest`. In ES only meta data fields are disallowed to be used in the source of a document. In any case if `_ingest.*` is being used in a template then we will assume is referred to pipeline metadata. If there is also a field with the name `_ingest` it has to be prefixed with `_source`. In all cases the `_source` prefix can be prepended to refer to any field in the source. Since `_source` is also a meta field in ES this can never be used as a field in the source itself. So we can safely use it as prefix for referencing fields in the source of a document.

**Comment by javanna** [comment]
This has been implemented
