### ISSUE TITLE
Pipeline config changes should be updated to all ingest nodes in a sync manner

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#14998]
Based on the review item: https://github.com/s1monw/elasticsearch/commit/042ef8c20476459f92ea1c2ea12bc1950211e693#diff-c69f941ab536509edea2ed0715c9a0adR169

Right now changes that are made to pipelines via the put pipeline api are not immediately picked up by all ingest nodes. Each ingest node periodically polls the .ingest index in the background and if there are changes it updates the in-memory representation of the pipelines.

If changes made to a pipeline via the put pipeline api would also trigger that all ingest nodes update their pipelines then things becomes much more predictable. This process isn't heavy, so I think we shouldn't be concerned about performance if we trigger a reload after each call the put pipeline api.

This should make using node ingest easier and also would make testing easier. (no need to wrap assertions inside assertBusy(...) blocks).

If we were to add an internal pipeline refresh api then the put and delete pipeline apis would you invoke that after each modification. The internal refresh api should trigger a reload of all ingest nodes and return when all the reloads have been completed.

**Comment by martijnvg** [comment]
There is a complication with only relying on the sync push mechanism. Changes can be missed, for example when ingest node is starting up and hasn't yet read all ingest documents from the .ingest index and another node is pushing the latest update of a pipeline, which the current node isn't ready to accept yet.

So instead we should keep the current async pipeline loading and as an addition to that we should add the sync refresh of pipelines on all other nodes if a node accepts a put or delete pipeline request. This way we're sure that we never ever miss pipelines on nodes (even during restarts) and because of the sync refresh all ingest nodes that are currently started are guaranteed to have the latest changes made to pipelines after a put or delete pipeline call. So this still makes testing easier and we don't have to rely on `assertBusy(...)` snippets in tests.

**Comment by javanna** [comment]
This has been implemented.
