### ISSUE TITLE
_ttl filed document a configure line is error

### ISSUE THREAD

**Issue by whybangbang** [elastic/elasticsearch#14994]
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-ttl-field.html

default TTL this chapter
PUT my_index
{
  "mappings": {
    "my_type": {
      "_ttl": {
        "enabled": true,
        "defaut": "5m"
      }
    }
  }
}

default is writed "defaut"
please update it ,thank you

**Comment by jasontedor** [comment]
Thanks for noticing and reporting this. This has been fixed in b6da075505e656e0944807b0025af68a32eb61ed.
