### ISSUE TITLE
ZenFaultDetectionTests:testMasterFaultDetectionConnectOnDisconnect doesn't check throwable causing failure

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#15004]
This is a followup to #14827 - after adding the Throwable causing the failure as an input parameter to MasterFaultDetection.Listener:onMasterFailure in addition to checking failure node and exception message information we should also check the correct Throwable was thrown.

https://github.com/elastic/elasticsearch/blob/473b19400f5f379c7c33e5afb70a3a8e1e258680/core/src/test/java/org/elasticsearch/discovery/ZenFaultDetectionTests.java#L196 is the method that now gets more information than before.

**Comment by bleskes** [comment]
@MaineC can you elaborate on the plan ? right now we check this (or similar) before calling the listener. See https://github.com/elastic/elasticsearch/blob/473b19400f5f379c7c33e5afb70a3a8e1e258680/core/src/main/java/org/elasticsearch/discovery/zen/fd/MasterFaultDetection.java#L257

**Comment by MaineC** [comment]
@bleskes No concrete plan, just a potential left over of #14827 where I introduced the additional parameter to the interface but in this particular test didn't do anything with it.

Happy to close this issue as "no change needed - the checking we have in place is sufficient". I'm just not familiar enough with this particular test to make the judgement call myself.

**Comment by bleskes** [comment]
why did you add the parameter to the throwable?

**Comment by MaineC** [comment]
To be able to add it to log messages we create in non-test implementations of the same interface. See also full changes here: #14827

**Comment by clintongormley** [comment]
@bleskes @MaineC anything further to do here?

**Comment by bleskes** [comment]
I think we can close this (and do so ;) ). @MaineC if you still see something here, please feel free to reopen...
