### ISSUE TITLE
when filtering after a 'terms_stats' sort query isnt applied v1.5.0

### ISSUE THREAD

**Issue by BarryGr** [elastic/elasticsearch#15022]
Hi All

I am having an issue with using terms_stats in Kibana, I am not on current version due to problems with the new Kibana interface. 

This is the first time I have come across this, I am trying to get back a very small section of data however only the date filters seem to get applied before the data is returned. this means a large response is returned but the data is null. I have tried changing "should" to "Must" and it still doesnt work.

I have tried

Has this already been addressed?

does anyone know a fix for this ?

Many thanks 

Barry

{
	"facets": {
		"terms": {
			"terms_stats": {
				"value_field": "AverageSeconds.raw",
				"key_field": "Machine.raw",
				"size": 2,
				"order": "term"
			},
			"facet_filter": {
				"fquery": {
					"query": {
						"filtered": {
							"query": {
								"bool": {
									"should": [{
										"query_string": {
											"query": "type:S_Agent AND SourceName.raw:S_Averages"
										}
									}]
								}
							},
							"filter": {
								"bool": {
									"must": [{
										"range": {
											"@timestamp": {
												"from": 1447860850443,
												"to": 1448465650443
											}
										}
									}]
								}
							}
						}
					}
				}
			}
		}
	},
	"size": 0
}'

**Comment by clintongormley** [comment]
Hi @BarryGr 

Facets have been removed.  Closing
