### ISSUE TITLE
indexed script with terms aggregation not working.

### ISSUE THREAD

**Issue by luizamboni** [elastic/elasticsearch#15030]
hi peoble, i` m have problems with terms aggregation in scripts, indexed scripts..

Here is a ES website link about this use:

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-script

It is saying that all script types are accepted, and shows an example for inline and file script. Under the file example it explains if want use indexed script need change key "file" in json by "id" key.

inline example
```javascript
{
    "aggs" : {
        "genders" : {
            "terms" : {
                "script" : "doc['gender'].value"
            }
        }
    }
}
```

file example
```javascript
{
    "aggs" : {
        "genders" : {
            "terms" : {
                "script" : {
                    "file": "my_script",
                    "params": {
                        "field": "gender"
                    }
                }
            }
        }
    }
}
```

and tip under file example in website explains if must need change key "file" in json by "id" key to use indexed script.

ok...all fine here.

i have a groovy indexed script named "test_field", for test.
it code is

```groovy
 return "test field";
```

well...then not are any doubt about script error becouse the simplicity of it.

when in a query i use this script in script_fields it works perfect

```javascript
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "seller_id": 1
          }
        }
      ]
    }
  },
  "script_fields": {
    "statuses": {
      "id": "test_field",
      "params": {
        "concurrent_ids": [
          1,
          2,
          3,
          4
        ]
      }
    }
  }
}
```

when i use the same script in aggs how describe in use of indexed scripts

```javascript
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "seller_id": 1
          }
        }
      ]
    }
  },
  "aggs": {
    "statuses": {
      "terms": {
        "script": {
          "id": "test_field",
          "params": {
            "concurrent_ids": [
              1,
              2,
              3,
              4
            ]
          }
        }
      }
    }
  }
}
```

receive the error: 

```javascript
{
  "error": "SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[5j_srZt-TDatRuMytEMuQA][4ninjas_products_development][0]: SearchParseException[[4ninjas_products_development][0]: query[+ConstantScore(seller_id: \u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001)],from[-1],size[-1]: Parse Failure [Failed to parse source [{\n  \"query\": {\n    \"bool\": {\n      \"must\": [\n        {\n          \"term\": {\n            \"seller_id\": 1\n          }\n        }\n      ]\n    }\n  },\n  \"aggs\": {\n    \"statuses\": {\n      \"terms\": {\n        \"script\": {\n          \"id\": \"test_field\",\n          \"params\": {\n            \"concurrent_ids\": [\n              1,\n              2,\n              3,\n              4\n            ]\n          }\n        }\n      }\n    }\n  }\n}]]]; nested: SearchParseException[[4ninjas_products_development][0]: query[+ConstantScore(seller_id: \u0001\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001)],from[-1],size[-1]: Parse Failure [Unknown key for a START_OBJECT in [statuses]: [script].]]; }]",
  "status": 400
}
```

when i change to inline script

```javascript
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "seller_id": 1
          }
        }
      ]
    }
  },
  "aggs": {
    "statuses": {
      "terms": {
        "script": "return \"test status\";",
        "params": {
          "concurrent_ids": [
            1,
            2,
            3,
            4
          ]
        }
      }
    }
  }
}
```

it works perfect...

what gone wrong ?

* Indexed scripts is activated
* sandboad for indexed scripts is "off"
* Indexed scripts works perfect in filters and script_fields
* in aggregation scripts using "file" make the same error too... 

the version of Elasticseach is:
```javascript
version: {
	number: "1.7.1",
	build_hash: "b88f43fc40b0bcd7f173a1f9ee2e97816de80b19",
	build_timestamp: "2015-07-29T09:54:16Z",
	build_snapshot: false,
	lucene_version: "4.10.4"
}
```

I search in internet, google, discus...and no find any similar example. Can be a bug. Please can you help me if not ? I had much work to explain exactly the point end formating this question me better display, and better understanding in github format.

**Comment by luizamboni** [comment]
I search about this a little more, it is a problem of diferente versions with diferente APIs....

https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-aggregations-bucket-terms-aggregation.html

i use the instructions here and works... 
"god ! give me patience, becouse if you give me power, i will broke alll"

**Comment by thomasmodeneis** [comment]
Always bad documentation + bad examples. With breaking changes every major release (5.0). Here we go on Elasticsearch purgatory 👎

**Comment by clintongormley** [comment]
@thomasmodeneis thanks for the encouraging words.  I notice that you haven't sent any PRs to improve the situation https://github.com/elastic/elasticsearch/pulls/thomasmodeneis

This is an open source project, feel free to get involved to improve the experience for all.
