### ISSUE TITLE
problems with Marvel plugin

### ISSUE THREAD

**Issue by dfaropennetwork** [elastic/elasticsearch#15032]
Hi,

i've problems with marvel and reverse proxy.

My apache conf for this terms:

  ProxyPass /app/marvel  http://**********:5601/app/marvel
  ProxyPassReverse /app/marvel http://**********:5601/app/marvel

  ProxyPass http://********:5601/api/marvel
  ProxyPassReverse http://********:5601/api/marvel

I see the cluster info correct:

![image](https://cloud.githubusercontent.com/assets/13537268/11414645/1c461fec-93f8-11e5-9676-1017a166366d.png)

But the nodes or other options give me errors:

![image](https://cloud.githubusercontent.com/assets/13537268/11414714/e94488a8-93f8-11e5-8ca6-d518ac3c71e2.png)

I try with the rewrite options but i did not lucky, any ideas?

Thx for the support

**Comment by tlrx** [comment]
Hi,

I saw you already asked your question on https://discuss.elastic.co/ [here](https://discuss.elastic.co/t/problems-with-apache-and-marvel-plugin/35623), which is the right place for such questions. We try to keep Github issues for real issues. 

Please feel free to reopen (or I will) if it ends up being a real bug.

**Comment by uboness** [comment]
https://discuss.elastic.co/c/marvel is the right place for this.. also for bugs

**Comment by dfaropennetwork** [comment]
Ah ok,  sorry tlex :D
