### ISSUE TITLE
Shards mapping inconsistency 

### ISSUE THREAD

**Issue by segalziv** [elastic/elasticsearch#15045]
Hi guys, 

I'm using elasticsearch 1.7.3 and encountered a strange case where 2 data nodes return a different result set for the exact same query. The queried index have 1 primary shard and 1 replica shard.

Debugging it I see that the mapping of that same index is different in the 2 relevant nodes. one of the nodes have more fields in the mapping, although both have the same doc count.

Can you please help? How can this happen? is there any indexing config I can apply to prevent these sort of thing? I've scanned the issues here and couldn't find a relevant issue.

* Not sure it is related, but the elasticsearch cluster I'm using have many indices/shards, but this is the first time it happens.

Thanks!

**Comment by rjernst** [comment]
Are you using dynamic mappings?

**Comment by segalziv** [comment]
hi @rjernst, thanks. yes I'm using dynamic mapping with doc-values by default.

**Comment by rjernst** [comment]
Thanks @segalziv. This was fixed in 2.0. Dynamic mapping updates were previously sent to the master asynchronously, so updates could get out of sync on failures or conflicts across nodes. We now send the update to the master before applying the update.

**Comment by segalziv** [comment]
Thanks.
