### ISSUE TITLE
Update API allows conflicting mappings

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#15049]
The update API allows conflicting field mappings to be introduced which can then bring a cluster down as it keeps trying and failing to sync the mappings.  Recreation:

    PUT t
    {
      "mappings": {
        "one": {
          "properties": {
            "foo": {
              "type": "nested",
              "properties": {
                "bar": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
    
    PUT t/two/1
    {}
    
    POST t/two/1/_update
    {
      "doc": {
        "foo": {
          "bar": 5
        }
      }
    }

    GET t/_mapping

returns:

    {
      "t": {
        "mappings": {
          "one": {
            "properties": {
              "foo": {
                "type": "nested",
                "properties": {
                  "bar": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "two": {
            "properties": {
              "foo": {
                "properties": {
                  "bar": {
                    "type": "long"
                  }
                }
              }
            }
          }
        }
      }
    }

From: https://discuss.elastic.co/t/cluster-keeps-becoming-unresponsive/35677

**Comment by jpountz** [comment]
This is a more general issue of our mapping API. I haven't figured out the cause yet, but here is a minimal recreation that reproduces the issue all the time:

```
PUT t
{
  "mappings": {
    "one": {
      "properties": {
        "foo": {
          "type": "string"
        }
      }
    }
  }
}

PUT t/two/_mapping
{
  "two": {
    
  }
}

PUT t/two/_mapping
{
  "two": {
    "properties": {
      "foo": {
        "type": "long"
      }
    }
  }
}

PUT t/two/_mapping
{
  "two": {
    "properties": {
      "foo": {
        "type": "long"
      }
    }
  }
}

GET t/_mapping
```
