### ISSUE TITLE
IndicesService.canDeleteShardContent() takes a lot of CPU and time because of regex that is executed against the Settings

### ISSUE THREAD

**Issue by centic9** [elastic/elasticsearch#15059]
When analyzing some high CPU that we encountered when working with many indices on an Elasticsearch 2.0 clusters. We tried to use 600 indexes with 12 shards here to see where we max out the system.

We saw that quite some time is spent running regex-matches in the Settings-Builder on the IndicesStore.clusterChanged() event. 

It seems this is executed many times during cluster-change events, as this is run in a loop over all entries in the ShardRoutingsTable:

        for (IndexRoutingTable indexRoutingTable : event.state().routingTable()) {
            for (IndexShardRoutingTable indexShardRoutingTable : indexRoutingTable) {
                if (shardCanBeDeleted(event.state(), indexShardRoutingTable)) {

See the following extract when using Dynatrace to do some performance analysis, out of the 19 seconds spent in the clusterChanged() method, nearly 6 are needed just for constructing the IndexSettings again and again:

<img width="774" alt="elasticsearch_candeleteshardcontent_highcpu_2015-11-27_09-05-42" src="https://cloud.githubusercontent.com/assets/548322/11438382/bffdbcd8-94f4-11e5-831f-7f3a9dc305a9.png">

I checked the code to ensure this is still the same on newer branches for 2.1, 2.x and master.

**Comment by bleskes** [comment]
I just looked and we can optimize some minor things, like only construct the setting once per index and not once per shard as we do now. That said, even 7200 operations shouldn't take 6s. How big are your settings?

**Comment by centic9** [comment]
The cluster was in a bit of stress at that time, that might have added some lag to the overall processing. Unfortunately I do not see how many times it was actually called with this type of CPU analysis. But I will do a more detailed sampling to get better numbers to rule out that other threads did steal most of the time here actually...

**Comment by centic9** [comment]
Ok, the overall time is not that high on a healthy cluster, but the percentage is still quite high. In a quick test the 6 calls of a cluster-state-change to the 6 cluster-nodes with take 3795 ms combined (aprox 630ms on each node), the re-building of the Settings takes 1091ms or 182ms on each node.

This is with 620 indices and 6978 primary as well as replica shards (not productive, just testing where ES breaks :) )

**Comment by bleskes** [comment]
@centic9 OK, fair enough. I've opened a PR with the small optimization (more of simplification in my mind). I think we're good here.

**Comment by centic9** [comment]
Great, looks nice, that should reduce the number of calls from 14000 to 700 in my case, which should provide quite a noticeable improvement. Thanks!
