### ISSUE TITLE
active directory auth ignoring url setting, possibly?

### ISSUE THREAD

**Issue by robertsmarty** [elastic/elasticsearch#15054]
Hi,

Could you please confirm the active directory auth process?

I have the following config...

      active_directory:
        type: active_directory
        order: 0
        domain_name: moon.corp
        url: ldaps://adldaps.moon.corp:636

We have a few domain controllers sitting behind a load balancer which resolves to adldaps.moon.corp and I would have expected shield to authenticate users to one of these load balanced domain controllers however it appears that shield is looking up ldap services in DNS instead.

Is this expected behavior?

**Comment by clintongormley** [comment]
Hi @robertsmarty 

The correct place to ask about Shield is here: https://discuss.elastic.co/c/shield
