### ISSUE TITLE
REST API Spec inconsistent use of url parts required field

### ISSUE THREAD

**Issue by apatrida** [elastic/elasticsearch#15063]
In some cases like `indices.put_mappings.json` the url.parts[].required field is set to `true` ... in this example only for `type` part.  But why wouldn't `index` part also have `required: true` in this case?

Is there some implied rule when required is assumed `true`?

**Comment by clintongormley** [comment]
@apatrida the `put_mapping` API also accepts this format `/_mapping/{type}`, so `index` isn't required.

**Comment by clintongormley** [comment]
to clarify: in this case the put mapping request applies to all indices
