### ISSUE TITLE
Testing classpath plugins in a node has become cumbersome in ES 2.1

### ISSUE THREAD

**Issue by jprante** [elastic/elasticsearch#15060]
Testing classpath plugins in a single temporary node has become cumbersome in ES 2.1.

In ES 2.0 it was easy to use a NodeBuilder. The node started and picked up the plugins. 

With ES 2.1, the NodeBuilder has been rendered useless, since it does no longer provides
the necessary control to load plugins from classpath.

Even worse, plugin authors have to write an auxilliary class in package org.elasticsearch.node
to be able to use the new Node class constructor to pass the classpath plugins to be tested.
The new class constructor has to be used in addition to the `plugin.types` setting in 
the node settings or the plugins do not load. 

These wrinkles make code longer and hard to understand/maintain for plugin authors.

I suggest to enhance NodeBuilder to be able to test plugins from classpath easily, without 
the auxilliary `MockNode` class, and without double declaration of plugins, as it was the case in ES 2.0

ES 2.0

```
Settings nodeSettings = Settings.settingsBuilder()
		.put("path.home", System.getProperty("path.home"))
		.put("plugin.types", MyPlugin.class.getName())
		.put("index.number_of_shards", 1)
		.put("index.number_of_replica", 0)
		.build();
Node node = NodeBuilder.nodeBuilder().settings(nodeSettings).local(true).build().start();
node.start();
return node;
```

ES 2.1

```
Settings nodeSettings = Settings.settingsBuilder()
		.put("path.home", System.getProperty("path.home"))
		.put("plugin.types", MyPlugin.class.getName())
		.put("index.number_of_shards", 1)
		.put("index.number_of_replica", 0)
		.build();
// ES 2.1 renders NodeBuilder as useless
//Node node = NodeBuilder.nodeBuilder().settings(nodeSettings).local(true).build().start();
Set<Class<? extends Plugin>> plugins = new HashSet<>();
plugins.add(MyPlugin.class);
Node node = new MockNode(nodeSettings, plugins);
node.start();
return node;
```

```
package org.elasticsearch.node;

import org.elasticsearch.Version;
import org.elasticsearch.common.settings.Settings;
import org.elasticsearch.plugins.Plugin;

import java.util.Collection;

public class MockNode extends Node {

    public MockNode(Settings settings, Collection<Class<? extends Plugin>> classpathPlugins) {
        super(settings, Version.CURRENT, classpathPlugins);
    }

}
```

**Comment by s1monw** [comment]
why are you starting a node yourself? Can't u use the testing framework?

**Comment by jprante** [comment]
I just want to write 8 lines of code to start a node with a classpath plugin. Testing framework is nice, but not an option, too heavy for my test code.

**Comment by jprante** [comment]
My NodeBuilder suggestion is already brought in by https://github.com/elastic/elasticsearch/issues/13212

**Comment by s1monw** [comment]
> I just want to write 8 lines of code to start a node with a classpath plugin. Testing framework is nice, but not an option, too heavy for my test code.

that is the supported way to test things with es. I don't see why this is too heavy.

**Comment by clintongormley** [comment]
Closing in favour of #13212
