### ISSUE TITLE
fix extraConfigFile to not check for the file, until runtime

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#15068]
Currently gradle checks for this at compile-time, but this prevents you from generating configuration files in the build itself. Can we move the check to runtime?

**Comment by rjernst** [comment]
I already attempted to do this here:
https://github.com/elastic/elasticsearch/commit/52f31ee14a8c07ab1e2592abd855dc0dc05497d4

And it works for me locally (with a separate clean before running check). Not sure why its not working on jenkins...
