### ISSUE TITLE
REST API Spec preferred URL paths does not match documentation preferred URL paths

### ISSUE THREAD

**Issue by apatrida** [elastic/elasticsearch#15064]
In the REST API Spec, for exmpale `indices.put_mapping.json` the URL path in the JSON is:

```
"path": "/{index}/{type}/_mapping",
```

and all flavours are present in the `paths` as:

```
"paths": ["/{index}/{type}/_mapping", 
              "/{index}/_mapping/{type}", 
              "/_mapping/{type}", 
              "/{index}/{type}/_mappings", 
              "/{index}/_mappings/{type}", 
              "/_mappings/{type}"],
```

But the preferred form is not obvious.  In the documentation it is `/{index}/_mapping/{type}` (https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html) 

Shouldn't the REST API Spec make it clear the order of preference?   Is the `url.path` element supposed to mark the preferred item from `url.paths`?  It doesn't in this case either. 

Are all the forms in `url.paths` really valid?  Some are not documented.  Are they old deprecated forms?  If so, marking them deprecated would be useful as well.

**Comment by apatrida** [comment]
I think that the REST API spec should have the paths in priority order, you take the first one that matches the available path segment variables you have on hand, and validate that all required fields are present and any in the path before them must also be present.

**Comment by clintongormley** [comment]
Those are indeed deprecated forms and I've just opened an issue to get them removed (https://github.com/elastic/elasticsearch/issues/15077).  

Yes, it'd be nice to list the URLs in order of priority but given that this is manually maintained, I think it is quite likely that errors will creep in.
