### ISSUE TITLE
Gradle does not define `-ea` for tests 

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#15076]
Not sure where this is coming from.

Tests in IntelliJ are not working anymore as they were when using Maven. It sounds like that a default option `-ea` is not set by default.

```
Assertions mismatch: -ea was not specified but -Dtests.asserts=true

java.lang.Exception: Assertions mismatch: -ea was not specified but -Dtests.asserts=true
	at __randomizedtesting.SeedInfo.seed([1691FDB8DE3F3A10]:0)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:48)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:65)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:55)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at java.lang.Thread.run(Thread.java:745)

REPRODUCE WITH: gradle null -Dtests.seed=1691FDB8DE3F3A10 -Dtests.class=org.elasticsearch.cloud.azure.storage.AzureStorageServiceTest -Dtests.locale=fr_FR -Dtests.timezone=Europe/Paris
NOTE: test params are: codec=null, sim=null, locale=null, timezone=(null)
NOTE: Mac OS X 10.11.1 x86_64/Oracle Corporation 1.8.0_60 (64-bit)/cpus=4,threads=1,free=102234880,total=128974848
NOTE: All tests run in this JVM: [AzureStorageServiceTest]

Process finished with exit code 255
```

Workaround: add manually `-ea` as a VM Option for the test. Would be fantastic to have that out of the box.

**Comment by rjernst** [comment]
For me this is a default that I set up in IntelliJ long ago (vm options for JUnit). I don't think there was something special that did this for Maven.

**Comment by dadoonet** [comment]
I just ran a test from scratch:

* git clone in a new dir
* checkout 2.x
* import in IntelliJ (maven based version): `-ea` is added as a VM option
* checkout master branch
* run `gradle idea`
* import in IntelliJ (gradle based version): no default `-ea` VM option.

If I then reimport the 2.x project, `-ea` option is not anymore here.
If I remove `elasticsearch.ipr` file and import again the maven 2.x project, `-ea` is back again as a default option.

So my first guess is that this file `.ipr` which is only generated when using gradle, introduce something which breaks the "default" behavior.

Once again, not a big deal as there is a workaround. So feel free to close it if you think we can't really fix that.

**Comment by clintongormley** [comment]
@rjernst can this be closed?

**Comment by rjernst** [comment]
I don't know of any settings for a project which can set the default. Anyone using intellij should set this as the default for the entire IDE. Closing.
