### ISSUE TITLE
Regexp on the _index does not work in 2.0

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#15070]
Currently, some queries work on the special `_index` field, as an example:

* Input
```
POST trial/doc
{
  "text": "this is text"
}

GET trial/_search
{
  "query": {
    "filtered": {
      "filter": {
        "term": {
          "_index": "trial"
        }
      }
    }
  }
}
```

* Response
```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "trial",
        "_type": "doc",
        "_id": "AVFKXPURmqplIqGCgb_z",
        "_score": 1,
        "_source": {
          "text": "this is text"
        }
      }
    ]
  }
}
```

**However**, wildcards are not supported for querying this field:

* Input
```
GET trial/_search
{
  "query": {
    "filtered": {
      "filter": {
        "regexp": {
          "_index": "tri*"
        }
      }
    }
  }
}
```

* Response (No results)

```
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}
```

**Comment by clintongormley** [comment]
The `_index` field is not indexed - it is exposed in queries as a fake field (https://github.com/elastic/elasticsearch/pull/12027), which means that it can only work with term/match queries, not with wildcards, fuzzy, regexp, etc.

It should be possible to set the `_index` field to `enabled: true` to index the index name with each doc, in which case all queries would work normally, but this appears to be broken currently (#15081).

Once #15081 is fixed, the docs should be updated to explain the above.

**Comment by clintongormley** [comment]
Actually, the ability to enable the index field was removed in #12329.

I've updated the docs accordingly
