### ISSUE TITLE
Is there any way to de-duplicated documents based on the field?

### ISSUE THREAD

**Issue by ryanchou1991** [elastic/elasticsearch#15074]
The following were the use cases

1. http://stackoverflow.com/questions/25448186/remove-duplicate-documents-from-a-search-in-elasticsearch

2. http://stackoverflow.com/questions/29886477/how-to-remove-duplicate-search-result-in-elasticsearch

I need to de-duplicate the documents based on a specified field. Meanwhile I noticed the post filter which could filter the search results on hits, while it seems doesn't make any sense to my case.

Could anyone could offer me some suggestions on it? or Elasticsearch plan to provide some solutions on that?

**Comment by clintongormley** [comment]
Hi @ryanchou1991 

The best place to ask questions like these is in the forums: https://discuss.elastic.co/

**Comment by ryanchou1991** [comment]
OK
