### ISSUE TITLE
Kubernetes discovery plugin

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#15073]
Is it worth including [this](https://github.com/fabric8io/elasticsearch-cloud-kubernetes) [here](https://www.elastic.co/guide/en/elasticsearch/plugins/current/discovery.html#_community_contributed_discovery_plugins)?

It was mentioned in [this](https://discuss.elastic.co/t/elasticsearch-2-0-unicast-discovery-via-load-balancer/35210/5) forum post from @jimmidyson and I can see that @dadoonet has also contributed to the plugin.

**Comment by jimmidyson** [comment]
I added it to master docs in #15013. There are versions for the plug plugin supporting es back to 1.5 so would be good to add docs for all versions.

**Comment by markwalkom** [comment]
Ahh nice work :D
