### ISSUE TITLE
Remove deprecated `/{index}/{type}/_mapping` endpoints

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#15077]
Since 1.0, the preferred URL format for mappings has been: `/{index}/_mapping/{type}`, but the old `/{index}/{type}/_mapping` format is still supported for bwc.

i think it is time to remove the bwc support.

**Comment by rjernst** [comment]
Why is `/{index}/_mapping/{type}` the "preferred" way? `/{index}/{type}/_mapping` matches with other endpoints we have, eg `/{index}/{type}/_search`

**Comment by dakrone** [comment]
@clintongormley yeah, where did we decide the preferred way? I agree with @rjernst that `/{index}/{type}/_search` matches our other APIs better (it's my preference)

**Comment by clintongormley** [comment]
We decided this in v1.0.0.RC1 https://github.com/elastic/elasticsearch/issues/4071

**Comment by clintongormley** [comment]
Superseded by #15613
