### ISSUE TITLE
The `_index` field mapping does not accept `enabled`

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#15081]
According to #9870, the `_index` field mapping should accept the `enabled` parameter, but it throws an exception:

    PUT trial
    {
      "mappings": {
        "doc": {
          "_index": {
            "enabled": true
          }
        }
      }
    }

Returns:

    {
       "error": {
          "root_cause": [
             {
                "type": "mapper_parsing_exception",
                "reason": "Mapping definition for [_index] has unsupported parameters:  [enabled : true]"
             }
          ],
          "type": "mapper_parsing_exception",
          "reason": "mapping [doc]",
          "caused_by": {
             "type": "mapper_parsing_exception",
             "reason": "Mapping definition for [_index] has unsupported parameters:  [enabled : true]"
          }
       },
       "status": 400
    }

**Comment by rjernst** [comment]
We removed this setting, as it is no longer necessary: #12329.

I think we just need to update the docs?

**Comment by clintongormley** [comment]
@rjernst I'd completely forgotten about that.  Thanks for the reminder. I've updated the docs accordingly
