### ISSUE TITLE
3.0.0 tar tests having lots of trouble on windows

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#15084]
http://build-us-00.elastic.co/job/es_core_master_window-2012/2067/console

Not sure if this is a windows issue or what.

**Comment by rmuir** [comment]
I don't think these tests have ever worked on windows since we moved to gradle.

**Comment by rmuir** [comment]
ES is definitely not getting even close to starting up. I can reproduce the fail easily, there is nothing in logs/ folder or even a logs/ at all, so I don't think bin/elasticsearch.bat is ever invoked.

Maybe its a bug with spaces/windows integ logic in the build. I'll try to dig.

**Comment by rmuir** [comment]
This code is just super broken and messy. E.g. 'esArgs' is not even being used.

Time to ditch all the useless closures and just have a simple if (Windows) in one place that does the right thing there.
