### ISSUE TITLE
Update all "official" plugins with a single command

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#15083]
Follow up for #15072 

It could be super handy to update all plugins with a single command.
Basically as when you upgrade elasticsearch you must upgrade all plugins, it could make sense to support a command like:

```sh
bin/plugin update _all
```

This would internally:

* list existing plugins
* for each plugin
   * remove it
   * install it

**Comment by mfn** [comment]
Naming suggestion: `update-all` instead of some magic `_all` "package?

**Comment by dadoonet** [comment]
Yeah I thought about this as well. I was wondering to support _all for remove as well but as there is almost no interest doing this, using update-all is definitely better.

**Comment by dadoonet** [comment]
As https://github.com/elastic/elasticsearch/issues/15000 won't be merged, this issue is not relevant anymore.
