### ISSUE TITLE
Ingest Attachment Processor use of platform-dependent newline is harmful

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#15095]
Mapper-attachments extraction (somewhere in our code, or tika itself, who knows), uses the newline of the operating system running elasticsearch during extraction.

This means extracted bytes differ on windows vs unix, which at first sounds harmless, but its really not, because it can have a snowball effect, causing a different character set to be detected and so on down the road.

We should see if there is a way to fix this... for now I disabled exact bytes checks in the tests (see #15094)

**Comment by clintongormley** [comment]
@spinscale could you please check if this is still the same in the new ingest attachment plugin?

**Comment by dakrone** [comment]
@spinscale ping on this, if it's still present in 5.0 for ingest node we should probably document it somewhere prior to the release.

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
