### ISSUE TITLE
Documentation incorrect - reference/2.0/modules-scripting.html

### ISSUE THREAD

**Issue by nicksanders** [elastic/elasticsearch#15096]
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/modules-scripting.html

Documentation example below causes "script_score query does not support [file]" error

         "script_score": {
            "lang": "groovy",
            "file": "calculate-score",
            "params": {
              "my_modifier": 8
            }
          }

Should be 

"script_file": "calculate-score"

**Comment by clintongormley** [comment]
The `script_score` in function score still uses the old scripting syntax.  Must have been missed in the script cleanup in https://github.com/elastic/elasticsearch/pull/11164

@colings86 could you take a look please?

**Comment by clintongormley** [comment]
whoops - i tested the wrong syntax, `script_score` works as intended.

@nicksanders presumably you're not using Elasticsearch 2.0.  You should look at the documentation for the version you're using

**Comment by nicksanders** [comment]
@clintongormley I was using Elasticsearch 2.0 and got the following error

script_score query does not support [file]

It is possible I was doing something else wrong but when I changed "file" to "script_file" it worked ;)

**Comment by clintongormley** [comment]
@nicksanders you're missing one layer (and so you're using the undocumented bwc syntax). Should be:

    "script_score": {
      "script": {
        "lang": "groovy",
        "file": "calculate-score",
        "params": {
          "my_modifier": 8
        }
      }
    }

See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#function-script-score

**Comment by nicksanders** [comment]
@clintongormley the example on https://www.elastic.co/guide/en/elasticsearch/reference/2.0/modules-scripting.html is missing one layer too ;)

**Comment by clintongormley** [comment]
thanks @nicksanders - fixed
