### ISSUE TITLE
gradle needs to print out every single commandline it executes

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#15092]
The maven build does this, it prints ENV and parameters for every commandline. This makes it easy to reproduce problems and debug issues.

But gradle is too succinct, it makes it impossible to debug e.g. why integration tests don't work on windows.

It really needs to print every command being executed.

**Comment by clintongormley** [comment]
@rjernst can this be closed yet?

**Comment by rjernst** [comment]
We added LoggedExecTask for this purpose and use it, so I think so.
