### ISSUE TITLE
Loads mapping from backup/temp files

### ISSUE THREAD

**Issue by vijicools** [elastic/elasticsearch#15106]
I had a mapping file named test.json under 
**config>mappings>_default>test.json**
Now I changed some of the properties in my json file and my editor creates a backfile named test.json~
**config>mappings>_default>test.json~**

Now when I restart elastic search it loads both files and when I dump documents with type *"test"* unfortunately the mapping under *"test.json~"* is used.

**Comment by clintongormley** [comment]
File based mappings are no longer supported in 2.0
