### ISSUE TITLE
allow to reboot cluster without reallocation

### ISSUE THREAD

**Issue by sweetest** [elastic/elasticsearch#15104]
While rebooting entire cluster to upgrade elasticsearch version or so, even though I use the same configuration, stopped data flow for a while, and reboot the exactly same nodes, it takes several hours to become 'green' after cluster reboot, reallocating every shard I have.

It might help ensuring data consistency, but as an end user I would be glad if there is a way to somehow 'finalize' es cluster before reboot, and then elasticsearch quickly gets 'green' after restart, using the same data of shards in the same nodes.

**Comment by clintongormley** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/14652
