### ISSUE TITLE
gradle is still hiding errors when commands fail

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#15116]
You have no idea what failed when a commandline execution fails, it just says "failed". at info level it gives more information, but this is wrong to do.

if we are executing a command, it is important, we need to see all the output, always, just like integ tests.

**Comment by rmuir** [comment]
The worst is gradle hiding the IOException from Runtime.exec(), that is most critical to debugging things.

**Comment by clintongormley** [comment]
@rjernst can this be closed yet?

**Comment by rjernst** [comment]
I'm not sure. The situation was improved with LoggedExecTask, but I dont remember the circumstances of the IOException being hidden.

**Comment by clintongormley** [comment]
@rmuir do you know if this can be closed?

**Comment by javanna** [comment]
I would go for closing this for now, we can always reopen whenever we find the same problem.
