### ISSUE TITLE
What's the best way to run REST integration tests?

### ISSUE THREAD

**Issue by andrejserafim** [elastic/elasticsearch#15124]
https://github.com/elastic/elasticsearch/blob/master/TESTING.asciidoc suggests 

```
gradle integTest -Dtests.filter="@Rest"
```

but that matches no tests, I've had some success with 
```
gradle integTest -Dtests.class="*.Rest*IT"
```

Is that the recommended way to run these?

**Comment by jasontedor** [comment]
You can do something like this:

```
gradle :distribution:tar:integTest \
  -Dtests.class=org.elasticsearch.test.rest.RestIT \
  -Dtests.method="test {p0=cat.shards/10_basic/Help}"
```

to run, for example, the REST test named "Help" in the `10_shards.yaml` file under `cat.shards`.
