### ISSUE TITLE
Inconsistency: keyAsString for terms aggregation on boolean field

### ISSUE THREAD

**Issue by DavidHauger** [elastic/elasticsearch#15146]
Just a minor thing, but still...
When performing a terms aggregation on a boolean field via sense, I get something like this for the `false` bucket
```
    ...
    "key": 0,
    "key_as_string": "false",
    ...
```
When using Java, `bucket.getKey()` returns `0L` (I would rather expect a Boolean than a Long as the returned Object - something that is true for both APIs), but at least it is the same.
However, `bucket.getKeyAsString()` returns `"0"` instead of `"false"` (as the Long is converted and not a Boolean).

In my Opinion, `"key_as_string"` and `getKeyAsString()` should return the same result.

**Comment by clintongormley** [comment]
@colings86 what do you think?

**Comment by colings86** [comment]
@clintongormley I agree that `"key_as_string"` and `getKeyAsString()` should be returning the same result. Maybe we should properly support Boolean fields in the Terms Aggregation and have is return `true` and `false` for `"key"` and `getKey()` and `"true"` and `"false"` for `"key_as_string"` and `getKeyAsString()`? /cc @jpountz

**Comment by jpountz** [comment]
+1 on returning "true"/"false" in getKeyAsString. However I think getKey should still return 0/1. This is consistent with how we handle other numeric-based types such as ipv4 addresses or dates.

**Comment by colings86** [comment]
Discussed in FixItFriday and decided that we should fix the inconsistency here, and maybe we will add support for Boolean later so the key is returned as a Boolean rather than 0/1

**Comment by jimferenczi** [comment]
The same reasoning can be made for date field where key_as_string contains the date and getKeyAsString returns the number of milliseconds since epoch in a string. The downside (for both date and boolean) is that getBucketByKey relies on getKeyAsString so any change here would affect this function.

**Comment by jimferenczi** [comment]
Closed via https://github.com/elastic/elasticsearch/pull/15393

**Comment by clintongormley** [comment]
@jimferenczi does that PR also deal with dates?

**Comment by jimferenczi** [comment]
@clintongormley booleans and dates yes.

**Comment by clintongormley** [comment]
thanks @jimferenczi

**Comment by qiuranke** [comment]
date type not fixed
