### ISSUE TITLE
Kibana not showing indices screen after new install

### ISSUE THREAD

**Issue by haium** [elastic/elasticsearch#15140]
I'm new to ELK. 
I installed ELK on Ubuntu. All seems to be up and running (ES, nginx, Kibana, Logstash) 
But, when I browse to Kibana, after authenticating on nginx, the browser displays only the upper header: Kibana logo + Discover / Visualize / Dashboard / Settings , without the indices info (sse attachment.)
Any idea what went wrong?

![kibana ui](https://cloud.githubusercontent.com/assets/16098342/11498031/8b99d7b8-9825-11e5-9af3-0e2f501a27f8.jpg)

**Comment by dadoonet** [comment]
Please join us on discuss.elastic.co. We can help you there.
