### ISSUE TITLE
Average seems to be wrong

### ISSUE THREAD

**Issue by bigl0af** [elastic/elasticsearch#15169]
I seem to be getting the wrong result when performing average aggregations via Kibana 4. As you can see, the values being returned for the are steadily right around 8,500,000,000. 
![screenshot from 2015-12-01 21-38-22](https://cloud.githubusercontent.com/assets/3859825/11520754/5665d390-9874-11e5-93d5-7d15b8e3aa58.png)

Yet, somehow, I get an average around 4,755,736,842,123,345,920! 
![screenshot from 2015-12-01 21-37-56](https://cloud.githubusercontent.com/assets/3859825/11520761/603d9286-9874-11e5-87f5-3b0d415408d6.png)

![screenshot from 2015-12-01 21-42-30](https://cloud.githubusercontent.com/assets/3859825/11520767/6db9d9ce-9874-11e5-9488-ca2da29b1970.png)

Running ES 1.7.2, JVM 1.8.0_31

**Comment by clintongormley** [comment]
Hi @bigl0af 

It looks like you have an index which has conflicting mappings between shards. In other words, the same field has been mapped differently on different shards, resulting in this weird calculation.  The only thing to do here is to reindex the data with the correct mappings.

This issue has been fixed (along with many others) in the great mapping cleanup in 2.0 (see #8870)
