### ISSUE TITLE
Facing errors in ES 2.1.0

### ISSUE THREAD

**Issue by vg15** [elastic/elasticsearch#15170]
Hi Experts,

I have downloaded new version of ES. I am getting the following errors while starting ES.
1) It says Unable to install syscall filter as it not supported for OS windows 8
![image](https://cloud.githubusercontent.com/assets/11420150/11521220/56c44522-98d0-11e5-8fa1-dc0ef27e9b30.png)
2) Getting a huge java error message 
![image](https://cloud.githubusercontent.com/assets/11420150/11521257/9d35846c-98d0-11e5-9c1f-d131c6443323.png)

Please help me to understand how I can rid off with the above 2 problems in new ES

Thanks 
VG

**Comment by dadoonet** [comment]
Please ask questions on discuss.elastic.co.
We can help there.
Instead of doing screen capture, copy and paste the full text. You can also look at this in logs/ dir.

The first warn is just a warn. You can ignore it. 
The second line is incomplete. Can't comment.
