### ISSUE TITLE
create index accept "filters" but it will be ignored

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#15183]
If you create an index specifying settings which contain a custom analyzer, and you specify its filters, you need to use the singular it seems (`filter` is the way to go, but is not enforced). Otherwise the filters will get accepted but won't be used.

```
PUT test
{
  "settings" : {
    "analysis": {
      "analyzer": {
        "my_analyzer" : {
          "tokenizer" : "whitespace",
          "filters" : ["lowercase"]
        }
      }
    }
  }
}

GET test/_analyze?text="This is my text"&analyzer=my_analyzer
```

Note that the filters element ends up in the cluster state, returned by the get index api, but it won't have any effect. I assume that whatever not supported element will not be rejected and be silently ignored, we should make this stricter when parsing. Same happens if you misspell e.g. char_filters .

**Comment by clintongormley** [comment]
This is not just to do with analysis - any index settings are lenient. Closing in favour of https://github.com/elastic/elasticsearch/issues/6732
