### ISSUE TITLE
analyze api accepts "filters" while create index relies on "filter"

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#15189]
The analyze api seems to accept a `filters` element, which makes sense, but create index only knows about `filter` instead (singular) when creating a custom analyzer. Can we make the two consistent?

**Comment by rjernst** [comment]
+1

**Comment by dakrone** [comment]
+1

**Comment by clintongormley** [comment]
Same goes for `char_filters`/`char_filter`.

@johtani want to take a look?

**Comment by johtani** [comment]
I am planning to delete `filters`/`char_filters from` `_analyze` API  in master, and deprecated them in 2.x.
Does it make sense?

**Comment by clintongormley** [comment]
+1
