### ISSUE TITLE
Support for user to set watcher metadata mapping 

### ISSUE THREAD

**Issue by CTJyeh** [elastic/elasticsearch#15199]
Is there a way for user to set metadata mapping for watcher?  
I want to set all properties in metadata to not_analyzed strings.

Related discuss posts:  
https://discuss.elastic.co/t/is-it-possible-to-modify-the-default-watch-history-mapping/29431
https://discuss.elastic.co/t/customize-watch-and-or-watch-history-index-template/28539/2

**Comment by clintongormley** [comment]
Hi @CTJyeh 

The place to discuss watcher is in the forums, where you linked to.
