### ISSUE TITLE
Plugin installation fails with: "ERROR: /usr/share/elasticsearch/plugins/migration/plugin-descriptor.properties"

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#15197]
When an 1.x plugin (such as the migration plugin) exists in the plugins directory, new plugin installations fail with this error:

```
[root@max elasticsearch]# bin/plugin install license --verbose
-> Installing license...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/license/2.1.0/license-2.1.0.zip ...
Downloading .......DONE
Verifying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/license/2.1.0/license-2.1.0.zip checksums if available ...
Downloading .DONE
ERROR: /usr/share/elasticsearch/plugins/abest/plugin-descriptor.properties
```

The problem can be recreated in ES >= 2.0 by simply making some empty directory within the plugins directory, and then attempting installation of any plugin.

**Comment by rjernst** [comment]
This is expected. Beginning with 2.0, you need to remove any plugins that are not built for the version of elasticsearch that you are running.

**Comment by dadoonet** [comment]
If the plugin manager has to check all existing plugins when installing plugin X Y or Z, then it should do this at first before downloading anything.

Here I think it's not the expected behavior for the install command of the plugin manager but expected behavior for plugin service (when elasticsearch starts).

I might be wrong though.

**Comment by rjernst** [comment]
This is the expected behavior always: we don't want to install a plugin that would later (possibly) fail when starting elasticsearch. This is why we unzip to a temp directory before actually "installing" (ie copying into the plugins dir). However, we can improve the error message.

**Comment by dadoonet** [comment]
I agree that we check the plugin we are trying to install and fail in that case. Totally expected.

Here if I'm not mistaken we fails on plugin A when installing plugin X. I will check tomorrow.

**Comment by rjernst** [comment]
> Here if I'm not mistaken we fails on plugin A when installing plugin X

That is correct. Due to the ability to disable isolation for a plugin, we must load info about all plugins when installing a new plugin.

**Comment by clintongormley** [comment]
This confusion has been noted a few times (ie installing plugin A then failing because of plugin B).  Perhaps it is as simple as adding a "Checking all plugins..." line to the output
