### ISSUE TITLE
Move repository-hdfs plugin from ES-Hadoop to Elasticsearch core

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#15191]
With the pluggable security in ES 2.2, the `repository-hdfs` plugin (from https://github.com/elastic/elasticsearch-hadoop) can be moved in the core as it does not require any extra changes.

Will raise a PR with the code rebased on master. Hopefully it will pass the review and be ported to 2.2 as well.

**Comment by clintongormley** [comment]
This plugin has been merged into core for v5.  Closing
