### ISSUE TITLE
empty '_source' with exist = true for documents

### ISSUE THREAD

**Issue by naivefun** [elastic/elasticsearch#15206]
We deployed ES 2.0 on 3 nodes as a cluster, for this index we have 5 shards and 2 replica.

However for some of the documents, when we execute 'get' or 'search' request through http:9200 or transport client:9300, it only return _source field with result one out of 3 times, the other two simple has this:

```json
{
   "_index": "business-1",
   "_type": "business",
   "_id": "5605e65dd7d77897cbaa4a29",
   "_version": 2,
   "_routing": "business",
   "found": true
}
```
What could possibly cause this? Really lost, thanks.

**Comment by clintongormley** [comment]
@naivefun I have no idea what your question is about.  Please provide a full recreation of what you are doing, what you expect, and what you're getting instead?

My best guess would be that you're using custom routing, and you're not providing the same routing when you try to GET the document.

**Comment by clintongormley** [comment]
No further feedback. Closing
