### ISSUE TITLE
Configuring HTTP module in ec2 to be talked to from browser

### ISSUE THREAD

**Issue by kylegalbraith** [elastic/elasticsearch#15218]
This seems like an incredibly basic question, but I am a bit stuck so hopefully someone can quickly unblock me. I have an ec2 linux machine in AWS that is running ElasticSearch. It is running on port 9200, and if I hit ```localhost:9200``` with curl I get the expected response. However, if I am outside the linux box, and try to hit the ec2 address in a browser it comes back with nothing. I have the security group on the box wide open right now so that I can hit it from the outside.

I suspect that I have something configured wrong in terms of the http module. The settings I have currently (and yes they will need to be filtered down once I get this scenario working) are as follows:
```
http.enable: true
http.cors.enable: true
http.cors.allow-origin: "*"
```

Clearly I believe I am missing something basic as it is not clear to me why this fails to work.

**Comment by davidcai19840412** [comment]
elastic search stop binding all ip address from v2.0.
Edit the elasticsearch config file,and change the value of network.publish_host and network.bind_host as follows:
network.publish_host: xxx.xxx.xxx.xxx //publish ip
network.bind_host: 0.0.0.0 //bind all ips

**Comment by kylegalbraith** [comment]
@davidcai19840412 thank you for the quick reply. Is ```network.publish_host``` for inter node communication? What should this be set to? It appears that bind_host is for outward facing communication correct?

**Comment by dadoonet** [comment]
Please ask your questions on discuss.elastic.co. More users might help you there.
Thanks.

This space is for confirmed issues.

Does not sound like an issue. Closing.
