### ISSUE TITLE
QueryBuilders.QueryString Not Considering Boost If Only One Field is provided.

### ISSUE THREAD

**Issue by vishnuchilamakuru** [elastic/elasticsearch#15214]
Hi,

We are using ElasticSearch 1.6.0.
QueryBuilders.QueryString Not Considering Boost If only One Field is provided. But if i repeat the same field with same boost multiple times it considers the boost value.

QueryString With Single Field : 

                {
                  "query_string": {
                    "query": "samsung mobiles",
                    "fields": [
                      "title^100.0"
                    ],
                    "auto_generate_phrase_queries": true,
                    "minimum_should_match": "100%"
                  }

Explain : true

{"value": 0.013228737,"description": "sum of:","details": [{"value": 0.008120831,"description": 

"weight(title:samsung in 74534) 

[PerFieldSimilarity], result of:","details": [{"value": 0.008120831,"description": "score(doc=74534,freq=1.0), product of:","details": [{"value": 0.0027710546,"description": "queryWeight, product of:","details": [{"value": 4.6889477,"description": "idf(docFreq=7708, maxDocs=308381)"},{"value": 0.0005909758,"description": "queryNorm"}]},{"value": 2.9305923,"description": "fieldWeight in 74534, product of:","details": [{"value": 1,"description": "tf(freq=1.0), with freq of:","details": [{"value": 1,"description": "termFreq=1.0"}]},{"value": 4.6889477,"description": "idf(docFreq=7708, maxDocs=308381)"},{"value": 0.625,"description": "fieldNorm(doc=74534)"}]}]}]},{"value": 0.005107906,"description": "weight(title:mobil in 74534) [PerFieldSimilarity], result of:","details": [{"value": 0.005107906,"description": "score(doc=74534,freq=1.0), product of:","details": [{"value": 0.0021976894,"description": "queryWeight, product of:","details": [{"value": 3.7187467,"description": "idf(docFreq=20339, maxDocs=308381)"},{"value": 0.0005909758,"description": "queryNorm"}]},{"value": 2.3242166,"description": "fieldWeight in 74534, product of:","details": [{"value": 1,"description": "tf(freq=1.0), with freq of:","details": [{"value": 1,"description": "termFreq=1.0"}]},{"value": 3.7187467,"description": "idf(docFreq=20339, maxDocs=308381)"},{"value": 0.625,"description": "fieldNorm(doc=74534)"}]}]}]}]}

QueryString With Same Field Twice : 

                {
                  "query_string": {
                    "query": "samsung mobiles",
                    "fields": [
                      "title^100.0",
                      "title^100.0"
                    ],
                    "auto_generate_phrase_queries": true,
                    "minimum_should_match": "100%"
                  }

Explain : true

{"value": 1.2471766,"description": "sum of:","details": [{"value": 0.7656144,"description": "max of:","details": [{"value": 0.7656144,"description": 

"weight(title:samsung^100.0 in 74534) [PerFieldSimilarity],

 result of:","details": [{"value": 0.7656144,"description": "score(doc=74534,freq=1.0), product of:","details": [{"value": 0.26124904,"description": "queryWeight, product of:","details": [{"value": 100,"description": "boost"},{"value": 4.6889477,"description": "idf(docFreq=7708, maxDocs=308381)"},{"value": 0.0005571592,"description": "queryNorm"}]},{"value": 2.9305923,"description": "fieldWeight in 74534, product of:","details": [{"value": 1,"description": "tf(freq=1.0), with freq of:","details": [{"value": 1,"description": "termFreq=1.0"}]},{"value": 4.6889477,"description": "idf(docFreq=7708, maxDocs=308381)"},{"value": 0.625,"description": "fieldNorm(doc=74534)"}]}]}]},{"value": 0.7656144,"description": "weight(title:samsung^100.0 in 74534) [PerFieldSimilarity], result of:","details": [{"value": 0.7656144,"description": "score(doc=74534,freq=1.0), product of:","details": [{"value": 0.26124904,"description": "queryWeight, product of:","details": [{"value": 100,"description": "boost"},{"value": 4.6889477,"description": "idf(docFreq=7708, maxDocs=308381)"},{"value": 0.0005571592,"description": "queryNorm"}]},{"value": 2.9305923,"description": "fieldWeight in 74534, product of:","details": [{"value": 1,"description": "tf(freq=1.0), with freq of:","details": [{"value": 1,"description": "termFreq=1.0"}]},{"value": 4.6889477,"description": "idf(docFreq=7708, maxDocs=308381)"},{"value": 0.625,"description": "fieldNorm(doc=74534)"}]}]}]}]},{"value": 0.48156232,"description": "max of:","details": [{"value": 0.48156232,"description": "weight(title:mobil^100.0 in 74534) [PerFieldSimilarity], result of:","details": [{"value": 0.48156232,"description": "score(doc=74534,freq=1.0), product of:","details": [{"value": 0.20719339,"description": "queryWeight, product of:","details": [{"value": 100,"description": "boost"},{"value": 3.7187467,"description": "idf(docFreq=20339, maxDocs=308381)"},{"value": 0.0005571592,"description": "queryNorm"}]},{"value": 2.3242166,"description": "fieldWeight in 74534, product of:","details": [{"value": 1,"description": "tf(freq=1.0), with freq of:","details": [{"value": 1,"description": "termFreq=1.0"}]},{"value": 3.7187467,"description": "idf(docFreq=20339, maxDocs=308381)"},{"value": 0.625,"description": "fieldNorm(doc=74534)"}]}]}]},{"value": 0.48156232,"description": "weight(title:mobil^100.0 in 74534) [PerFieldSimilarity], result of:","details": [{"value": 0.48156232,"description": "score(doc=74534,freq=1.0), product of:","details": [{"value": 0.20719339,"description": "queryWeight, product of:","details": [{"value": 100,"description": "boost"},{"value": 3.7187467,"description": "idf(docFreq=20339, maxDocs=308381)"},{"value": 0.0005571592,"description": "queryNorm"}]},{"value": 2.3242166,"description": "fieldWeight in 74534, product of:","details": [{"value": 1,"description": "tf(freq=1.0), with freq of:","details": [{"value": 1,"description": "termFreq=1.0"}]},{"value": 3.7187467,"description": "idf(docFreq=20339, maxDocs=308381)"},{"value": 0.625,"description": "fieldNorm(doc=74534)"}]}]}]}]}]}

**Comment by clintongormley** [comment]
In the one field case, the boost is normalized away as it only makes sense to boost one field in comparison with another.
