### ISSUE TITLE
search problem with query_string and special characters

### ISSUE THREAD

**Issue by david-tejedor** [elastic/elasticsearch#15220]
Searching with AND operator and special characters with query_string it returns more results than it should.

Having two documents with one field called "searchField", with the next values:
- First document, value: AAA{BBB}CCC
- Second document, value: AAA{BBB}DDD

First case: Returns both documents searching for the value: AAA{BBB}CCC.
Second case: Returns only the first document searching for the value: AAA BBB CCC.

I guess both queries should return only the first document as the search is done with AND operator.

The query used in the first case (which I guess is the wrong one) is the following:
"query":{
    "filtered":{
        "query":{
            "bool":{
                "must":[{
                    "query_string":{
                        "query":"AAA\\{BBB\\}CCC*",
                        "fields":["searchField"],
                        "analyze_wildcard":true,
                        "default_operator":"and"
                    }
                }]
            }
        }
    }
}

Note: Using Java with JestClient client.
The reason why I use the bool query is that is created dynamically so it could have more parameters.

This "issue" happens with several special characters. Not sure if I could be doing something wrong.

Thank you very much!

**Comment by dadoonet** [comment]
Mostly because of analysis process.
Read the user guide about it. Really helpful.

Please ask questions on discuss.elastic.co.

Not an issue. Closing.
