### ISSUE TITLE
_analyze API fails if char_filters is set in body.

### ISSUE THREAD

**Issue by masaruh** [elastic/elasticsearch#15257]
If it's passed as URL parameter, it works.

It looks _analyze API sets char_filters as token_filters:
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/rest/action/admin/indices/analyze/RestAnalyzeAction.java#L132

**Comment by clintongormley** [comment]
@johtani want to take a look?

**Comment by johtani** [comment]
@clintongormley Yes. And I will fix in #11660.

**Comment by johtani** [comment]
Closed by master : fab44398d9d48f12319bc018d4b436f723b6508e 
2.x : f427cf4ae459b864894c8ba1a3eff589ad5248a0
