### ISSUE TITLE
S3 Snaphot via Corporate Proxy

### ISSUE THREAD

**Issue by berniemoran** [elastic/elasticsearch#15268]
Currently unable to access S3 for snapshot using a proxy that requires authentication.
Cloud-AWS plugin does not include options proxy_username proxy_password.
See the following thread:
https://discuss.elastic.co/t/snapshot-to-s3-via-corporate-proxy/36431

**Comment by dadoonet** [comment]
I was looking at it this morning and I think it's easy to implement it using [ClientConfiguration#setProxyHost](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#setProxyHost(java.lang.String)).
Same for `setProxyPort`, `setProxyUsername` and `setProxyPassword`.

I'll look at it later unless anyone else would like to contribute this "small" change.

**Comment by dadoonet** [comment]
Actually we support `cloud.aws.s3.proxy_host` and `cloud.aws.proxy_port`. Just missing `username` and `password`.

I'd suggest BTW to: 

* rename `cloud.aws.s3.proxy_host` to `cloud.aws.s3.proxy.host`
* rename `cloud.aws.proxy_port` to `cloud.aws.proxy.port`
* add `cloud.aws.proxy.username`
* add `cloud.aws.proxy.password`
