### ISSUE TITLE
ES 2.x doc: Minimum required java version is incorrect

### ISSUE THREAD

**Issue by au78** [elastic/elasticsearch#15261]
On https://www.elastic.co/guide/en/elasticsearch/reference/2.x/setup.html#jvm-version, first line says that minimum java requirement is version 8. The next line says that it is works with version 7 update 55 as well (although recommended version is 8). 

First line should be fixed to say that ES 2.x minimum required Java is version 7 and not 8.

**Comment by jasontedor** [comment]
Thanks for reporting this!
