### ISSUE TITLE
Hidden files should be ignored by the ScriptsService

### ISSUE THREAD

**Issue by nizsheanez** [elastic/elasticsearch#15269]
I do store ES configs in git repo.
It required to have `scripts` sub folder, but i can't commit to git empty folder, need to put there .gitkeep file. 
I got this exception:

```
es_data_1     | java.lang.IllegalArgumentException: script file extension not supported [gitkeep]
es_data_1     | 	at org.elasticsearch.script.ScriptService.getScriptEngineServiceForFileExt(ScriptService.java:221)
es_data_1     | 	at org.elasticsearch.script.ScriptService.access$1200(ScriptService.java:83)
es_data_1     | 	at org.elasticsearch.script.ScriptService$ScriptChangesListener.onFileInit(ScriptService.java:537)
es_data_1     | 	at org.elasticsearch.watcher.FileWatcher$FileObserver.onFileCreated(FileWatcher.java:256)
es_data_1     | 	at org.elasticsearch.watcher.FileWatcher$FileObserver.init(FileWatcher.java:166)
es_data_1     | 	at org.elasticsearch.watcher.FileWatcher$FileObserver.createChild(FileWatcher.java:173)
es_data_1     | 	at org.elasticsearch.watcher.FileWatcher$FileObserver.listChildren(FileWatcher.java:188)
es_data_1     | 	at org.elasticsearch.watcher.FileWatcher$FileObserver.onDirectoryCreated(FileWatcher.java:299)
es_data_1     | 	at org.elasticsearch.watcher.FileWatcher$FileObserver.init(FileWatcher.java:162)
es_data_1     | 	at org.elasticsearch.watcher.FileWatcher$FileObserver.access$000(FileWatcher.java:75)
es_data_1     | 	at org.elasticsearch.watcher.FileWatcher.doInit(FileWatcher.java:65)
es_data_1     | 	at org.elasticsearch.watcher.AbstractResourceWatcher.init(AbstractResourceWatcher.java:36)
es_data_1     | 	at org.elasticsearch.watcher.ResourceWatcherService.add(ResourceWatcherService.java:133)
es_data_1     | 	at org.elasticsearch.watcher.ResourceWatcherService.add(ResourceWatcherService.java:126)
es_data_1     | 	at org.elasticsearch.script.ScriptService.<init>(ScriptService.java:192)
es_data_1     | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
es_data_1     | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
es_data_1     | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
es_data_1     | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
```

**Comment by nik9000** [comment]
It looks like you can work around this by creating a file without any extension - those are ignored by the ScriptsService.

I'll let someone more opinionated than I am decide if this is a bug or a feature. I will say that it wouldn't be a ton of work to ignore hidden files in this directory. To declare them "not a script" and just log a WARNING or something.

**Comment by nik9000** [comment]
I'm guessing this just showed up in 2.0. @nizsheanez, can you confirm when you first saw it?

**Comment by rjernst** [comment]
We check for this with plugins, we should use the same utility: `FileSystemUtils.isHidden`

**Comment by nik9000** [comment]
> We check for this with plugins, we should use the same utility: FileSystemUtils.isHidden

Yeah. Also it feels wrong that we should ever be ok running hidden scripts. That just screams "abuse me!"

**Comment by nik9000** [comment]
@nizsheanez I've changed the title to make it more obvious what behavior you were relying on before and marked this as a bug.

**Comment by rjernst** [comment]
>  Also it feels wrong that we should ever be ok running hidden scripts. 

I don't think this would actually happen, because the "hidden script" would have an empty string for a name (and I assume, maybe incorrectly, that the script service checks for an empty string when a file script is specified)

**Comment by fforbeck** [comment]
Hey,
I was looking at the ScriptService.java, mainly in the inner class ScriptChangesListener.
We could ignore the hidden files on the **onFileInit(Path file)** method if we add the check that was suggested above: *FileSystemUtils.isHidden*, then add some warning as well. 
If you guys agree, can I take this one?

**Comment by rjernst** [comment]
@fforbeck Please do!

**Comment by fforbeck** [comment]
@rjernst 
Alright! I sent a PR. 
Could you please take a look when possible?

Thanks

**Comment by mostolog** [comment]
Is there any chance this being backported to 2.3.x ?

**Comment by jasontedor** [comment]
> Is there any chance this being backported to 2.3.x ?

That is very unlikely.
