### ISSUE TITLE
PUT `index/_mapping` doesn't work atm

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#15275]
At the moment we define an endpoint which takes a PUT verb and `{index}/_mapping` as path. How every, when you try to use it, it fails:

```
PUT index/_mapping
{
  "type": {
    "properties": {
      "field": { "type": "string"}
    }
  }
}
```

Results in:

```
{
   "error": {
      "root_cause": [
         {
            "type": "action_request_validation_exception",
            "reason": "Validation Failed: 1: mapping type is missing;"
         }
      ],
      "type": "action_request_validation_exception",
      "reason": "Validation Failed: 1: mapping type is missing;"
   },
   "status": 400
}
```

Sniffing in the code it seems one has to supply a type in the URL, i.e., `PUT index/_mapping/type` and in which case you can omit or keep the type in the body (both works). However, trying to use two types, silently drops second type (if the first one matches the url pattern), or gets annoyed:

```
PUT index/_mapping/type
{
  "type2":{
    "properties": {
      "field": { "type": "string"}
    }
  },
  "type":{
    "properties": {
      "field": { "type": "string"}
    }
  }
}
```

resulting in

```
{
   "error": {
      "root_cause": [
         {
            "type": "mapper_parsing_exception",
            "reason": "Root mapping definition has unsupported parameters:  [type2 : {properties={field={type=string}}}] [type : {properties={field={type=string}}}]"
         }
      ]
}
```

Imho we should support multiple types in one request, or alternatively disable the endpoint.

/dd @pmusa

**Comment by alicia-c** [comment]
+1

**Comment by clintongormley** [comment]
I'm going to close this in favour or removing types altogether (https://github.com/elastic/elasticsearch/issues/15613)
