### ISSUE TITLE
CircuitBreaker Issue  /flow of data from  types  to  heap size 

### ISSUE THREAD

**Issue by justies** [elastic/elasticsearch#15272]
incase if  I have a diffferent types  and having a common name of  a field created by.When  I querying  with that field with respect to a particular type , will it load  the data from  all type to the heap memory  or only from the type which i have refered. due to this  frequent circuitbreaker exception  occuring

**Comment by dakrone** [comment]
Hi @justies,

Please ask future questions on https://discuss.elastic.co , Github is used for communication about bugs and enhancements to Elasticsearch. To answer your question, all types' fielddata will be loaded. You should switch to [doc values](https://www.elastic.co/guide/en/elasticsearch/guide/current/doc-values.html#doc-values) to alleviate frequent circuit breaking exceptions.
