### ISSUE TITLE
es 2.X Start time，load average very high

### ISSUE THREAD

**Issue by z-star** [elastic/elasticsearch#15276]
es version 2.1
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
top - 16:21:05 up 121 days, 21:04,  2 users,  load average: 22.55, 7.90, 3.23
2322 tomcat    20   0 24.6g  19g  14m S 100.4 15.7   1:10.81 java

**Comment by clintongormley** [comment]
@z-star i suggest asking in the forums: http://discuss.elastic.co/
