### ISSUE TITLE
Replace MovingAvgModel.Streams with NamedWriteable

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#15279]
At the moment MovingAvgModels are written and read to the wire format by the MovingAvgModel.Streams class. This pre-dated the NamedWritable interface but we should now move it over to this framework as its the preferred method of serializing named implementations to the wire format

Relates to #10217

**Comment by clintongormley** [comment]
@colings86 has this been addressed yet?

**Comment by colings86** [comment]
Not yet. This is a non-urgent issue since there is no bug here it would just be cleaner if it used the NamedWritable infrastructure. It will at least need to wait until the agg refactoring is merged into master

**Comment by nik9000** [comment]
I did it!
