### ISSUE TITLE
PHP Elastica Client v3.1.6 has error on indexing after upgrade from ES 1.1.1 to 1.7.3

### ISSUE THREAD

**Issue by jackiekhuu-work** [elastic/elasticsearch#15273]
I have just upgrade ES version from 1.1.1 to 1.7.3. Followed this guide: https://www.elastic.co/guide/en/elasticsearch/reference/1.7/setup-upgrade.html#rolling-upgrades

Everything is fine, except that PHP Elastica Client (version 3.1.6) show errors when indexing documents into new Elasticsearch 1.7.3 (This error didn't happen in version 1.1.1 before upgrading):

[message] => Error in one or more bulk request actions:
update: /indexname/type/5078 caused EsRejectedExecutionException[rejected execution (queue capacity 50) on org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1@6ec548ff]

Is there any difference on default queue capacity of bulk indexing between 2 version of Elasticsearch (1.1.1 - 1.7.3)?

**Comment by clintongormley** [comment]
Hi @jackiekhuu-work 

Lots has changed between 1.1 and 1.7.  It looks like you are flooding ES with too many bulk requests without waiting for responses.  If you have further questions, I'd ask them in the forum instead: http://discuss.elastic.co/
