### ISSUE TITLE
Add Collections#shuffle(List) to forbidden APIs

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#15287]
Several tests are using [`Collections#shuffle(List)`][1] which uses a default source of randomness rather than using [`Collections#shuffle(List, Random)`][2] which enables a reproducible source of randomness. This prevents reproducible build failures. One example is [NodeJoinControllerTests](https://github.com/elastic/elasticsearch/blob/0c2c7e7ef527393b23fe211f0617e1c2b006cc6c/core/src/test/java/org/elasticsearch/discovery/zen/NodeJoinControllerTests.java#L247) but there are many others. 

The method [`Collections#shuffle(List)`][1] should be added to forbidden APIs.

[1]: https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#shuffle-java.util.List-
[2]: https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#shuffle-java.util.List-java.util.Random-

**Comment by javanna** [comment]
+1

**Comment by nik9000** [comment]
> The method Collections#shuffle(List) should be added to forbidden APIs.

The list for tests or the list for all classes?

**Comment by jasontedor** [comment]
> The list for tests or the list for all classes?

I intend to completely forbid it.

**Comment by rmuir** [comment]
its the only way. if something is non-test and uses random behavior, give it an optional setting like initialSeed and set it in the test framework.

**Comment by nik9000** [comment]
> its the only way. if something is non-test and uses random behavior, give it an optional setting like initialSeed and set it in the test framework.

I figured as much but its nice to have it confirmed. IIRC its used in a few places.

**Comment by jasontedor** [comment]
This method is also used inside [ESTestCase#randomSubsetOf][1] greatly increasing the surface area of non-reproducible tests.

[1]: https://github.com/elastic/elasticsearch/blob/0c2c7e7ef527393b23fe211f0617e1c2b006cc6c/test-framework/src/main/java/org/elasticsearch/test/ESTestCase.java#L569
