### ISSUE TITLE
command line parameters like --help and -p pidfile broken on windows

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#15284]
The bat script is broken on windows. The parameters `!newparams!` should be placed at the ned of the line in bat script here: https://github.com/elastic/elasticsearch/blob/master/distribution/src/main/resources/bin/elasticsearch.bat#L46 as @spinscale pointed out.

We need a test for that too. This was not caught because currently we only test for the `-Des.pidfile` parameter: https://github.com/elastic/elasticsearch/blob/2.x/dev-tools/src/main/resources/ant/integration-tests.xml#L169 (have not looked at master yet). 

I can do that just want to open the issue in case someone else is dying to do that...

**Comment by rjernst** [comment]
We do the same (set the `pidfile` setting) in master:
https://github.com/elastic/elasticsearch/blob/70107c5c3cf6958ad4c38a15fc33d25e66673610/buildSrc/src/main/groovy/org/elasticsearch/gradle/test/ClusterFormationTasks.groovy#L206

**Comment by clintongormley** [comment]
Fixed by #15320
