### ISSUE TITLE
guava18 of ex2.x conflicts with guava12 of hbase

### ISSUE THREAD

**Issue by arronli** [elastic/elasticsearch#15298]
guava versions conflict if i use hbase and es2.x java client together ,  then i have to keep the 1.x version of es

**Comment by rjernst** [comment]
guava has been removed as a dependency from the master branch. You will need to shade either hbase or ES until the next major release.

Please ask questions like this (assuming question was "what should I do?") on http://discuss.elastic.co

**Comment by arronli** [comment]
thx !

**Comment by roycehaynes** [comment]
@arronli - Did you have solve this issue? If so, what was the solution?

**Comment by arronli** [comment]
@roycehaynes   
using hive external table  or 
read from hbase using mapreduce  api
hope helpful
