### ISSUE TITLE
Plugin install failure exit codes are not unique

### ISSUE THREAD

**Issue by w33ble** [elastic/elasticsearch#15295]
I was just debugging a problem in libesvm where installations failed to download, and was using the exit code (74) to handle that case.

This was fine until I ran it several times and the plugin was already installed, since that exit code was the same (74). 

This meant that I needed to write a workaround to parse stdout, which isn't ideal. It would be great if these (and perhaps other) errors used different exit codes so that scripts that consume the plugin tool could more easily react differently based on the reason for failure.

**Comment by nik9000** [comment]
> This meant that I needed to write a workaround to parse stdout

Bleh. Makes sense to me.
