### ISSUE TITLE
Geolocation sorting inaccurate

### ISSUE THREAD

**Issue by sudhanne** [elastic/elasticsearch#15297]
Problem:
    When using the geolocation sorting functionality to sort based on distance from a point (lat, lon), we are observing inaccurate distance computations.  In some cases these are off by a little bit, but in others they are wildly off.  Changing the sort accuracy to ARC does not seem to help much.
    When we switch to using a Groovy script to calculate these values we get completely accurate results.  We are trying to understand where the differences could come from, and how such fundamental functionality could be broken.

Elasticsearch version: 
    1.5.1

Type Mapping:

{
 "lms_event": {
            "dynamic": "strict",
            "_all": {
               "enabled": false
            },
            "properties": {
               "acl": {
                  "properties": {
                     "ou_with_subs": {
                        "type": "integer"
                     },
                     "ou_without_subs": {
                        "type": "integer"
                     },
                     "user_with_subs": {
                        "type": "integer"
                     },
                     "user_without_subs": {
                        "type": "integer"
                     }
                  }
               },
               "event_id": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "rating": {
                  "type": "integer",
                  "doc_values": true
               },
               "session": {
                  "type": "nested",
                  "properties": {
                     "date_end": {
                        "type": "date",
                        "format": "dateOptionalTime"
                     },
                     "date_start": {
                        "type": "date",
                        "format": "dateOptionalTime"
                     },
                     "location": {
                        "type": "geo_point",
                        "doc_values": true
                     },
                     "location_ou_id": {
                        "type": "integer"
                     },
                     "schedule_id": {
                        "type": "string",
                        "index": "not_analyzed"
                     },
                     "session_id": {
                        "type": "string",
                        "index": "not_analyzed"
                     }
                  }
               },
               "subject_id": {
                  "type": "integer",
                  "doc_values": true
               }
            }
}

Query 1 (default ES geolocation sorting):

GET /dev.devrelease/lms_event/_search
{
   "_source": [
      "event_id"
   ],
   "query": {
      "filtered": {
         "query": {
            "match_all": {}
         },
         "filter": {
            "bool": {
               "must": [
                  {
                     "term": {
                        "event_id": "54231e7d-e725-480f-a66d-4358fa31ba46"
                     }
                  },
                  {
                     "nested": {
                        "path": "session",
                        "filter": {
                           "geo_distance": {
                              "distance": "1mi",
                              "location": {
                                 "lon": -118.486974,
                                 "lat": 34.01956
                              }
                           }
                        },
                        "inner_hits": {
                           "size": 1000,
                           "sort": [
                              {
                                 "_geo_distance": {
                                    "session.location": {
                                 "lon": -118.486974,
                                 "lat": 34.01956
                                    },
                                    "order": "asc",
                                    "unit": "mi"
                                 }
                              },
                              {
                                 "date_start": {
                                    "order": "asc"
                                 }
                              }
                           ]
                        }
                     }
                  }
               ]
            }
         }
      }
   }
}
}

Query 1 Result (inaccurate)

        {
                           "_index": "dev.devrelease.3034",
                           "_type": "lms_event",
                           "_id": "54231e7d-e725-480f-a66d-4358fa31ba46",
                           "_nested": {
                              "field": "session",
                              "offset": 11
                           },
                           "_score": null,
                           "_source": {
                              "session_id": "940c8051-3b9f-45e4-8d2c-b85168c0eaad",
                              "schedule_id": "4ca2b22e-ebf4-4188-8ecb-0217bab50a69",
                              "location": {
                                 "lon": -118.486974,
                                 "lat": 34.01956
                              },
                              "date_start": "2016-06-28T16:00:00.0000000",
                              "date_end": "2016-06-28T17:05:00.0000000",
                              "location_ou_id": 764362
                           },
                           "sort": [
                              2.553454168690986,
                              1467129600000
                           ]
                        }

Query 2 (groovy script)

{
GET /dev.devrelease/lms_event/_search
{
   "_source": [
      "event_id"
   ],
   "query": {
      "filtered": {
         "query": {
            "match_all": {}
         },
         "filter": {
            "bool": {
               "must": [
                  {
                     "term": {
                        "event_id": "54231e7d-e725-480f-a66d-4358fa31ba46"
                     }
                  },
                  {
                     "nested": {
                        "path": "session",
                        "filter": {
                           "geo_distance": {
                              "distance": "1mi",
                              "location": {
                                 "lon": -118.486974,
                                 "lat": 34.01956
                              }
                           }
                        },
                        "inner_hits": {
                           "size": 1000,
                           "sort": [
                              {
                                 "_script": {
                                    "lang": "groovy",
                                    "script": "doc['session.location'].arcDistanceInMiles(34.01956, -118.486974)",
                                    "type": "number",
                                    "order": "asc"
                                 }
                              },
                              {
                                 "date_start": {
                                    "order": "asc"
                                 }
                              }
                           ]
                        }
                     }
                  }
               ]
            }
         }
      }
   }
}
}

Query 2 Results (accurate)

         {
                           "_index": "dev.devrelease.3034",
                           "_type": "lms_event",
                           "_id": "54231e7d-e725-480f-a66d-4358fa31ba46",
                           "_nested": {
                              "field": "session",
                              "offset": 8
                           },
                           "_score": null,
                           "_source": {
                              "session_id": "d54e485b-9e3d-42fc-a23a-e36dffb59fe9",
                              "schedule_id": "957d7df0-98d8-4318-93cf-3bedb9aa70b4",
                              "location": {
                                 "lon": -118.473667,
                                 "lat": 34.028449
                              },
                              "date_start": "2016-06-30T16:00:00.0000000",
                              "date_end": "2016-06-30T17:05:00.0000000",
                              "location_ou_id": 764360
                           },
                           "sort": [
                              0.9787904132112273,
                              1467302400000
                           ]
                        }

**Comment by clintongormley** [comment]
It is really helpful if you add a recreation that I can just copy and paste.  I've spent about an hour trying to replicate your example, without any luck.  Here's a demonstration of this working correctly:

    PUT test
    {
      "mappings": {
        "test": {
          "properties": {
            "loc": {
              "type": "geo_point"
            },
            "session": {
              "type": "nested",
              "properties": {
                "location": {
                  "type": "geo_point",
                  "doc_values": true
                }
              }
            }
          }
        }
      }
    }
    
    PUT test/test/1
    {
      "session": {
        "location": {
          "lon": -118.473667,
          "lat": 34.028449
        }
      },
      "loc": {
        "lon": -118.473667,
        "lat": 34.028449
      }
    }
    
    PUT test/test/2
    {
      "session": {
        "location": {
          "lon": -118.486974,
          "lat": 34.01956
        }
      },
      "loc": {
        "lon": -118.486974,
        "lat": 34.01956
      }
    }
    
    GET /test/test/_search?_source=false
    {
      "query": {
        "filtered": {
          "filter": {
            "bool": {
              "must": [
                {
                  "nested": {
                    "path": "session",
                    "filter": {
                      "geo_distance": {
                        "distance": "1mi",
                        "session.location": {
                          "lon": -118.486974,
                          "lat": 34.01956
                        }
                      }
                    },
                    "inner_hits": {
                      "sort": [
                        {
                          "_geo_distance": {
                            "location": {
                              "lon": -118.486974,
                              "lat": 34.01956
                            },
                            "order": "asc",
                            "unit": "mi"
                          }
                        }
                      ]
                    }
                  }
                }
              ]
            }
          }
        }
      },
      "sort": [
        {
          "_geo_distance": {
            "loc": {
              "lon": -118.486974,
              "lat": 34.01956
            },
            "order": "asc",
            "unit": "mi"
          }
        },
        {
          "_script": {
            "lang": "groovy",
            "script": "doc['loc'].arcDistanceInMiles(34.01956, -118.486974)",
            "type": "number",
            "order": "asc"
          }
        }
      ]
    }
    
You will see that all geo sort values (nested, top-level, groovy) are the same.  Tested on 1.5.1 and 1.7.3.  note: when I had to change the nested sort field from `session.location` to just `location`, otherwise it didn't find the field.

**Comment by sudhanne** [comment]
Hi Clinton,

Try this:

```javascript
PUT test1
{
  "mappings": {
    "test": {
      "properties": {
        "id": {
          "type": "integer"
        },
        "session": {
          "type": "nested",
          "properties": {
            "location": {
              "type": "geo_point",
              "doc_values": true
            }
          }
        }
      }
    }
  }
}
```

```javascript
PUT test1/test/1
{
   "id": 1,
   "session": {
      "location": {
         "lon": -118.486974,
         "lat": 34.01956
      }
   }
}
```

```javascript
PUT test1/test/2
{
   "id": 2,
   "session": {
      "location": {
         "lon": -118.486974,
         "lat": 34.02956
      }
   }
}
```

```javascript
GET /test1/test/_search
{
   "query": {
      "filtered": {
         "filter": {
            "bool": {
               "must": [
                  {
                     "nested": {
                        "path": "session",
                        "filter": {
                           "geo_distance": {
                              "distance": "1mi",
                              "location": {
                                 "lon": -118.486974,
                                 "lat": 34.01956
                              }
                           }
                        },
                        "inner_hits": {
                           "size": 1000,
                           "sort": [
                              {
                                  "_script": {
                                    "lang": "groovy",
                                    "script": "doc['session.location'].arcDistanceInMiles(34.01956, -118.486974)",
                                    "type": "number",
                                    "order": "asc"
                                  }                                  
                              },
                              {
                                 "_geo_distance": {
                                    "session.location": {
                                       "lon": -118.486974,
                                       "lat": 34.01956
                                    },
                                    "order": "asc",
                                    "unit": "mi"
                                 }
                              }
                           ]
                        }
                     }
                  }
               ]
            }
         }
      }
   }
}
```

```javascript
{
   "took": 1,
   "timed_out": false,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "hits": {
      "total": 2,
      "max_score": 1,
      "hits": [
         {
            "_index": "test1",
            "_type": "test",
            "_id": "1",
            "_score": 1,
            "_source": {
               "id": 1,
               "session": {
                  "location": {
                     "lon": -118.486974,
                     "lat": 34.01956
                  }
               }
            },
            "inner_hits": {
               "session": {
                  "hits": {
                     "total": 1,
                     "max_score": null,
                     "hits": [
                        {
                           "_index": "test1",
                           "_type": "test",
                           "_id": "1",
                           "_nested": {
                              "field": "session",
                              "offset": 0
                           },
                           "_score": null,
                           "_source": {
                              "location": {
                                 "lon": -118.486974,
                                 "lat": 34.01956
                              }
                           },
                           "sort": [
                              0,
                              1.7976931348623157e+308
                           ]
                        }
                     ]
                  }
               }
            }
         },
         {
            "_index": "test1",
            "_type": "test",
            "_id": "2",
            "_score": 1,
            "_source": {
               "id": 2,
               "session": {
                  "location": {
                     "lon": -118.486974,
                     "lat": 34.02956
                  }
               }
            },
            "inner_hits": {
               "session": {
                  "hits": {
                     "total": 1,
                     "max_score": null,
                     "hits": [
                        {
                           "_index": "test1",
                           "_type": "test",
                           "_id": "2",
                           "_nested": {
                              "field": "session",
                              "offset": 0
                           },
                           "_score": null,
                           "_source": {
                              "location": {
                                 "lon": -118.486974,
                                 "lat": 34.02956
                              }
                           },
                           "sort": [
                              0.6909863387230968,
                              1.7976931348623157e+308
                           ]
                        }
                     ]
                  }
               }
            }
         }
      ]
   }
}
```

Notice that the inner hit sorting by geolocation does not appear to work properly unless I use custom Groovy script.  Thanks.

-Sudheer

**Comment by clintongormley** [comment]
@sudhanne Did you see this line in my previous comment?

> note: I had to change the nested sort field from `session.location` to just `location`, otherwise it didn't find the field.

In 2.0, you should use `session.location` in the geodistance sort, but in 1.x, you leave out the nested path.
