### ISSUE TITLE
elastic search edit distance logic seems wrong  [ and the documentation is bad ]

### ISSUE THREAD

**Issue by parcompute** [elastic/elasticsearch#15301]
the query is 
```json
{
    "query" : {
         "bool" : {
             "must" : [
                 {
                     "match" : {
                        "full_name" : {
                             "query" : "meena mishra",
                             "fuzziness" : 2,
                             "operator" : "and"
                        }
                     }
                 },
                 ...
             ]
         }
    } 
}
```

the document has  

{ 
   "full_name" :  "Mina MISHRA" 
}

document was indexed using standard analyzers. All default.
edit distance should be <= 2 and the document should match.
I have tried several queries and figured that , the "query" value "mna mishra"  succeeds.
"mina mishra", unsurprisingly succeeds. however as soon I change it to "mena mishra", it starts failing.

Is this related to the uncontrollable parameter *min_similarity* which prevents this match?
How to debug the already done analysis of a document in an index?

version : 1.7
platform : centos

thanks.

**Comment by cbuescher** [comment]
@parcompute works for me, so could you check your analyzer settings. Closing this for now since I doubt this is an issue with the query. Please feel free to ask any questions regarding debugging options in the [forums](https://discuss.elastic.co/c/elasticsearch).
