### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by rferrante1966** [elastic/elasticsearch#15316]
I'd like to see functionality added to Elasticsearch that specifically supports transaction reporting, and I'd like to see that exposed for Kibana visualizations.  

"Stitching together" transactions from a set of Elasticsearch documents  isn't presently well-supported by existing aggregations and the Kibana visualization interface.   What I think is missing is:
1.  an aggregation for the Duration (min - max) timestamp of a group. 
2.  more specific options for inclusion in the group:
* starts_with field=value or field=regex_pattern
* ends_with field=value  or field=regex_pattern
* contains field=value or field=regex_pattern ## to report on subset of transactions that took a particular path or went through a particular host, etc.

Kibana's Visualization editor would need:
* An Additional Data Constraints section (in addition to metrics and buckets) which would solicit the starts_with, ends_with, and contains field and value.
* the metrics Aggregation lookup would need to include "Duration"

With these added I think ELK users would be in a much better position to report on business transactions across complex heterogeneous stacks out of the box (without custom development). 

Thoughts?

**Comment by gmoskovicz** [comment]
@rferrante1966 

Currently i think that this can be done by Scripted Metric Aggregations. However they are expensive and i don't think that we support them in Kibana yet.

A new aggregation can be useful to provide the insight of the data in a pretty straight forward way. But i am not sure if this is too specific to a "Transactions" user case.

@clintongormley  any thoughts?

**Comment by jpountz** [comment]
I can't find them but I think we had other issues related to that topic. In short it is not something that we can implement efficiently at query time. The best option today would be to index in an entity-centric way so that components of a transaction are already grouped together in a single document in the index and ready to be aggregated.

**Comment by gmoskovicz** [comment]
Thanks @jpountz i do think that having them grouped using nested or parent child can work. For this a reindex is needed so then you can change the mapping and structure.

**Comment by rferrante1966** [comment]
It may not be easy to implement at query time, but it may worth considering as demand for cross stack transaction reporting is huge and looks to only be growing. ...   

Without this feature, I was thinking along the same lines as @jpountz  that the best we could do was create transaction records outside of Elasticsearch (the single document @jpountz referenced) and insert them as a basis for reporting.

**Comment by jpountz** [comment]
@rferrante1966 If you already have transaction ids in your events, you might be able to use them as document ids in elasticsearch and use the upsert capabilities to either create the document if it does not exist or append to it otherwise.

**Comment by gmoskovicz** [comment]
@jpountz @rferrante1966  I think that for a regular indexing use case, that can work, however for a logging use case, this is not straight forward. Also, using upsert can impact the cluster for too many updates, i think that the best option is to pull the documents and re-index them in a way that you can actually perform some operations that gives you the result. Other than than, Scripted Metric Aggregation can be expensive, but depending how many times per day you want to run this, it can be an option.

**Comment by clintongormley** [comment]
@rferrante1966 Have a look at @markharwood 's talk about entity centric indexing https://www.youtube.com/watch?v=yBf7oeJKH2Y , where he goes into the whys and hows of doing what you're after.  This is not something we can do efficiently at query time, but we are thinking about how we can make it easier to do at index time, possibly using the changes API(https://github.com/elastic/elasticsearch/issues/1242)

**Comment by rferrante1966** [comment]
Mark's presentation is certainly on target.  I hope to spend some time looking at the example he provided in which he routinely processes the raw events and creates session (transaction) records for optimized search. Thanks.

**Comment by gmoskovicz** [comment]
@rferrante1966 this was one of the ideas that we had at the beginning of this thread. Some times we need to change the way that the data is represented to be able to query in a simpler way. However, for this we should:

1. Change the data, create new mapping, create new structures.
2. Change how the data is stored: Index and Documents.
3. Change the way that we think about logs: Log Centric vs Profile/Transaction Centric.

While this will require extra work, you should be able to decrease the amount of time spend in writing queries or thinking about aggregation, for time of extracting the data and adding to the `profile` or the information that you need.

Thanks @clintongormley for pasting the youtube video, i think that it clarifies more how this can be done!
