### ISSUE TITLE
Deprecate geo_shape orientation parameter

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#15317]
`geo_shape` `orientation` was originally added to handle polygonal ambiguity issues by complying with the right-hand rule defined by the OGC specification. The parameter adds leniency by enabling users to explicitly override the specification for backward compatibility with existing data. Unfortunately this leniency propogates "bad" (non-compliant) data.  Since the spec strictly requires the right-hand rule, ES should comply with the specification. Issues regarding "bad data" should be directed toward offline data repair tools prior to indexing - perhaps I will provide a tool bundled with ES.

**Comment by clintongormley** [comment]
+1 We should follow the spec.  Potentially we could add a processor to the ingest node that would support reordering points to follow the spec.

**Comment by imotov** [comment]
It might be simpler to address after #32039
