### ISSUE TITLE
path.home is not configured

### ISSUE THREAD

**Issue by YunchaoGongSC** [elastic/elasticsearch#15325]
Hey

I am trying to do unit tests for ES, and tried to setup a local node using the following code.

 Node server = nodeBuilder()
                .node();

But I got the following error when I try to create this

java.lang.IllegalStateException: path.home is not configured
	at org.elasticsearch.env.Environment.<init>(Environment.java:99)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:81)
	at org.elasticsearch.node.Node.<init>(Node.java:135)
	at org.elasticsearch.node.Node.<init>(Node.java:129)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:152)

Then I tried the following without luck

Settings settings = Settings.settingsBuilder().put("es.path.home", "").build();
Node server = nodeBuilder().settings(settings).node();

Do you guys have any idea? Thanks!

**Comment by socurites** [comment]
How about trying this one: 
```java
NodeBuilder.nodeBuilder()
    .settings(Settings.builder()
        .put("path.home", "/path/to/elasticsearch/home/dir")
    .node();
```
Reference:
[#13155] 2.0.beta1 - Exception "path.home is not configured" when starting ES in transport and client mode

**Comment by YunchaoGongSC** [comment]
Thanks! I think I also tried "path.home" and an empty string as input, but with no luck. Will try the real elasticsearch home dir and see what happens.

**Comment by YunchaoGongSC** [comment]
Please note I am using ES version 2.1.0

**Comment by YunchaoGongSC** [comment]
Another question, it seems by using nodeBuilder, we still need a local copy of ES. If we only want to setup a local in memory test server in our unit tests, when we develop stuff using ES's Java API, what is the best setting for this? Thanks!

**Comment by dadoonet** [comment]
Please ask your questions on discuss.elastic.co.
We keep this space only for confirmed issues.

**Comment by TannerMoore** [comment]
I have had more of my problems solved by Github than discuss.elastic.co. Not sure if that is Google's fault, GitHub's fault, or the community's fault.
