### ISSUE TITLE
Windows service installer doesn't escape file path in 2.x

### ISSUE THREAD

**Issue by kstachowiak-kcura** [elastic/elasticsearch#15349]
When installing the Windows service for Elasticsearch 2.x, some part of the batch file breaks when the ES_HOME path contains parentheses. This behavior is not present in 1.7.

Example:
>C:\Program Files (x86)\elasticsearch-2.1.0> bin\service.bat install
Installing service      :  "elasticsearch-service-x64"
Using JAVA_HOME (64-bit):  "C:\Program Files\Java\jdk1.8.0_45"
\elasticsearch-2.1.0/lib/elasticsearch-2.1.0.jar was unexpected at this time.

**Comment by clintongormley** [comment]
@gmarz could you take a look at this please

**Comment by kstachowiak-kcura** [comment]
It looks like this originates from the new if statement around setting ES_CLASSPATH in elasticsearch.in.bat

**Comment by gmarz** [comment]
@kstachowiak-kcura that looks like it may be part of the issue, but the service also fails to start even after properly escaping the path in the bat file.  I'll dig into this further tomorrow.

**Comment by tundrax** [comment]
In my case, the problem occurs when the path where ES is installed contains `)` - closing parantheses. In this case `Program Files (x86)`. Just tested with different patterns, like: `Program Files (x86`, `Program Files x86` all work fine. The closing parentheses is causing the problem.

**Comment by mazogi** [comment]
This problem is still (or again?) happening in v 5.6.2
