### ISSUE TITLE
Function score with scrip score multiplies the query score twice

### ISSUE THREAD

**Issue by keikha** [elastic/elasticsearch#15346]
When I use function score that has a script_score and a main query and has the boost_mode as multiplication. The ES calculates the score for the main query and multiplies it to the script_score twice. Once as part of the script_score and once as part of the final score. If you use the explain mode and dig into the scores, you can see the behavior.

**Comment by brwe** [comment]
Can you please add the query that you use? What does the script look like? Also, what version of elasticsearch are you using?

**Comment by clintongormley** [comment]
Only if you actually include `_score * ` in the script and leave the `boost_mode` as `multiply`, but for eg this doesn't do what you describe:

    PUT t/t/1
    {
      "foo": "bar"
    }
    
    GET t/_search?explain
    {
      "query": {
        "function_score": {
          "query": {
            "match": {
              "foo": "bar"
            }
          },
          "functions": [
            {
              "script_score": {
                "script": "2.0"
              }
            }
          ]
        }
      }
    }


This sounds like a question that would be better answered in the forums: https://discuss.elastic.co/

**Comment by keikha** [comment]
You are right. 
The confusion came from the fact that "log" function in the script calculates "Ln" not "Log base 10".  And in my tests, the number seemed very close to log*score.
