### ISSUE TITLE
[FEATURE REQUEST]: Standalone indexer for very large bulk indexing

### ISSUE THREAD

**Issue by BrunoBonacci** [elastic/elasticsearch#15341]
## The problem

Indexing (or reindexing) large amount of data (10xTB) it is a very painful process. Some of the index level changes requires a re-indexing of the data and there is no other solution that go through a full index reload. In very large clusters or very large amount of data this is a huge burden.

## The proposed solution

Most people who use ElasticSearch have another source of the data. This it can be another database such as Cassandra or raw documents stores in deep storage such as S3 or HDFS.
When processing several TB of data it is common to use BigData solutions such as Hadoop and Spark.
Loads of other frameworks which work on top of these allow arbitrary data processing.
Now let's assume that the ElasticSearch indexing, as currently available via the REST API, was also available as separate standalone function, this could be used as a lambda over the data to index.

The standalone indexer would need only a index name or configuration object and some mappings or index templates,
and accept a document in the form of a JSON object or JSON string.
Such indexer combined with the power of Hadoop & Spark could be used to create the Lucene indexes in the exact same way of a full ElasticSearch cluster, but without having to worry about ELS installations, configuration, replication, cluster load etc.

In fact in such solution a query capability wouldn't be necessary, and the standalone indexer could focus on building the indices without having to merge segments, refresh indexes etc.
The standalone indexer would require that all records for a particular index must be indexed by the same instance of the indexer. This can be easily achieved by a logical GROUP-BY the index name in the scripts which process the data and deliver all records to the reducers with the specific index.

Once the indexing is complete a finalisation function such as `optimize()` could merge/compact the index to be performant.
Now to make the newly created indices available to the cluster we could simply use the ElasticSearch repository function. For example each index could be uploaded to a deep storage (S3 or HDFS) and then restored by the main ELS cluster from the same location.

## Advantages

Advantages are:
  - very high indexing throughput via high parallelism of Hadoop/Spark
  - no need to setup ELS in the Hadoop cluster
  - no HTTP requests required for the indexing path
  - no cluster overhead while indexing

Current solutions which involve the installation of a ELS node tend to be brittle and fail very easily.

Bruno

**Comment by clintongormley** [comment]
Sorry @BrunoBonacci but this is a complete non-starter. We'd have to rip out so much of the code that makes Elasticsearch Elasticsearch, then deal with the multitude of bugs that would crop up in such a refactoring, then deal with all of the feature requests for people wanting to add back things they need but aren't supported in this locked down indexer.

We have customers doing 1m docs/s.  There are plenty of things you can do to increase indexing throughput in ES, such as disabling refreshes, or disabling replicas until the data is fully indexed.

I'd much rather focus on this comment:

> Current solutions which involve the installation of a ELS node tend to be brittle and fail very easily.

Why?  What can be done to improve this situation instead?

**Comment by BrunoBonacci** [comment]
I understand the challenges behind a Standalone Indexer, I would assume that most of the are derived by the concurrency management, which in the case of this type of indexer, as described above, it wouldn't be necessary.
Every indexer would fall in the Single Writer Principle, so no need to handle queues of requests etc, and document index operation is executed in a single thread environment (reducer).
The idea is just to wrap lucene with the ELS substratum which produces indices which are in the same format as the online version.

> We have customers doing 1m docs/s. 
On how many nodes? and what type of hardware? what size of documents?

The issue with having hadoop indexing directly into ELS via the API are:
  - online users request are impacted by high volume high throughput indexing activities (eg: you don't wan't your production users not being able to query the cluster because the capacity is fully utilised by the indexers). Ensuring that such activities don't have negative impact on the live usage it is paramount.
  - alternatively need to setup dedicated cluster for indexing (which is overhead)
  - even in this case the overall throughput is still much less that what it can be achieved with a standalone indexer (no remote call, just I/O bound indexing)
  -  a standalone indexer wouldn't require to "rip things apart", but just to provide a wrapper class inside the same elasticsearch.jar distribution. The extent of refactoring would be limited to the ability of the wrapper to reach the information it needs to index the same field with the same format into lucene.
   - I think that conceptually having the indexer producing fully optimized immutable segments, which are uploaded to a repository (S3) and having the cluster just to restore them as a normal backup/restore operation it is a much nicer design that having to hammer a cluster and contend the resources with users who have latency sensitive queries. It's just bytes copying at this point, and it is a nice separation of writes from reads.

Other systems, such as druid.io, provide similar feature and it is much easier to re-index several TB of data with new mapping configuration or index/shard configuration.
I'm sure that if you ask your larger users they will agree that such feature would be a great feature for them too.

**Comment by clintongormley** [comment]
This isn't something we have any plans to support, so I'm going to close this issue.
