### ISSUE TITLE
Getting error while connecting to kibana after configuring SearchGuard

### ISSUE THREAD

**Issue by balubollam** [elastic/elasticsearch#15355]
Hi Everyone

 I Have Implemented  “search-guard” Elasticsearch
-->
*First i have created a “SearchGuard” Index
*Then I have Installed and Configured it in logging.yml and Elasticsearch.yml 
*In elasticsearch.yml i have given a user name:admin and password:admin
note:I have given all permissions to admin user in “searchguard” index
**HERE is my index

curl -XPUT 'http://localhost:9200/searchguard/ac/ac' -d '{
    "acl": [
    {    
        "__Comment__": "By default no filters are executed and no filters a by-passed. In such a case an exception is thrown and access will be denied.",
        "filters_bypass": [],
        "filters_execute": []
     },
     {
           "__Comment__": "For role *admin* all filters are bypassed (so none will be executed). This means unrestricted access.",
           "roles": [
               "admin"
           ],
           "filters_bypass": [],
           "filters_execute": [“actionrequestfilter.kibanaUser”]
     }
     ]
}'

**Here is my elasticsearch.yml
searchguard.enabled: true
searchguard.rewrite_get_as_search: true
searchguard.allow_all_from_loopback: true
searchguard.config_index_name: searchguard
searchguard.key_path: /var/lib/elasticsearch/searchguard_node.key
##User settings
searchguard.authentication.settingsdb.user.admin: admin
searchguard.actionrequestfilter.names: ["kibanaUser","admincopy"]
searchguard.actionrequestfilter.kibanaUser.allowed_actions:["indices:admin/get","indices:data/read/*", "*monitor*"]

--->Here iam getting “timeout” Error.
As i am new to this concept.Not getting.Please someone help me out in this??  

Thanks And Regards
Balaji

**Comment by sarwarbhuiyan** [comment]
You may want to post this on the search guard GitHub

**Comment by balubollam** [comment]
Ya Sure
