### ISSUE TITLE
thread_pool unconsistency issue

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#15359]
when config thread pool in confi file, there is size parameter
when GET _nodes/thread_pool, there are min and max
when GET _nodes/stats/thread_pool, there is threads
can it be unifinied to cause less confuse?

**Comment by abeyad** [comment]
In this case, the thread pool reporting for the two different endpoints is intended to report different things:

GET _nodes/thread_pool is meant to show how the node is configured with regards to each thread pool.  This is static information on the node, and 'min' and 'max' here indicate the core pool size and max thread pool size with respect to the ThreadPoolExecutor.

GET _nodes/stats/thread_pool is meant to show the current state of each thread pool, where 'threads' in the latter is showing a dynamic reporting of the current number of live threads for the given thread pool (based on ThreadPoolExecutor's getPoolSize()).
