### ISSUE TITLE
improve pluginmanager permissions output

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#15365]
For 2.2, we let plugins define their own permissions. `/bin/plugin` lists the permissions, points you to Oracle documentation, and asks you to confirm Y/N.

It would be better to output the current stuff only in verbose mode and give simpler information otherwise. For the multicast plugin, instead of:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.net.SocketPermission localhost:1024- listen,resolve
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]
```

something like:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* Bind to network ports
Specify the -v option for more details.

Continue with installation? [y/N]
```

We don't need fine-grained explanation of every single permission in java. We can bucket many of them into categories, e.g. "Access Java internals", "Modify JVM-wide settings", "Violate system boundaries", and so on.

**Comment by nik9000** [comment]
> We don't need fine-grained explanation of every single permission in java. We can bucket many of them into categories, e.g. "Access Java internals", "Modify JVM-wide settings", "Violate system boundaries", and so on.

More and more like android every day.... Its a good idea.

Do we trust plugins to define these buckets themselves in a config file or something or should just just all live in core and when we don't recognize one we bounce the user to Oracle's docs? I think the latter? I'd prefer to give users cryptic but exact permissions rather than allow a malicious plugin to tuck a permission away somewhere were it shouldn't.

**Comment by rmuir** [comment]
I'm only recommending changing plugin manager's output. That is all.

**Comment by clintongormley** [comment]
+1

**Comment by skearns64** [comment]
+1

**Comment by djschny** [comment]
Additionally a command line option or something similar to bypass the prompt for stdin (user input) is really helpful, as these prompts make automated installs very difficult if not possible.

**Comment by rmuir** [comment]
It would not be helpful at all. there is already one, but you didn't bother to look?

**Comment by djschny** [comment]
I did, because I pulled up the class to make sure it was Elasticsearch code and not JVM code:

https://github.com/elastic/elasticsearch/blob/5f3d0067f8ef0c1216ec47c7c360d018355f58ee/core/src/main/java/org/elasticsearch/plugins/PluginSecurity.java

But I missed the batch flag option. My bad.
