### ISSUE TITLE
node setting update api request

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#15361]
nowsday, we can update cluster setting through API, like this:
PUT _cluster/settings
{
    "persistent" : {
        "threadpool.search.size" : 128
    }
}
is it possible to make it can update node like this:
PUT _cluster/nodename/settings
{
    "persistent" : {
        "threadpool.search.size" : 128
    }
}

**Comment by rjernst** [comment]
Cluster settings are cluster settings. This issue has remained open for over 2 years with no support. I'm going to close as this is such a high hanging fruit that I do not see it as a priority any time soon.
