### ISSUE TITLE
Space on begin of line in elasticsearch.yml keeps service from starting

### ISSUE THREAD

**Issue by widhalmt** [elastic/elasticsearch#15374]
Hi,

In Elasticsearch 2.1 on CentOS 7 I hit some weird behaviour that took me some time to figure out.

While testing I only have 2 lines of configuration in `elasticsearch.yml` (and the comments that are in it per default)

    network.host: "_non_loopback:ipv4_"
    discovery.zen.ping.unicast.hosts: ["192.168.56.101"]

When I add a Space to the second line the daemon won't start and doesn't write any log to `/var/log/elasticsearch`. 

    network.host: "_non_loopback:ipv4_"
     discovery.zen.ping.unicast.hosts: ["192.168.56.101"]

Only in `/var/log/messages` there are some cryptic hints about errors in the syntax.

Since an extra space is something that might happen easily when un-commenting one of the examples, I'm quite sure this might hit some other users too. Could you please make Elasticsearch a little bit less picky or at least add a check that writes something helpful about this issue into the standard logfile?

Thanks in advance,

**Comment by clintongormley** [comment]
Elasticsearch is throwing an exception on STDERR when it discovers the bad YAML.   (which is correct behaviour).  We can't log the message to the log file, because we haven't yet parsed the settings to find out where the log file should be.

I don't think there is anything we can do here?

**Comment by jasontedor** [comment]
> Could you please make Elasticsearch a little bit less picky

We parse according to the YAML spec; since [indentation](http://www.yaml.org/spec/1.2/spec.html#id2777534) is important in YAML, there is no room for leniency here.
