### ISSUE TITLE
Error on ElasticSearch 1.0.3 EndWithValue

### ISSUE THREAD

**Issue by elliswood** [elastic/elasticsearch#15384]
This has been driving me crazy for 2 weeks now. I have an elastic search on my dev machine that is working great but when I shove it up to LIVE I get this error whenever I sort by relevancy i.e. use script_score:

{
"error": "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[Gy8DKMvoQKO5rousUfhQsw][modernrugs_3][1]: QueryPhaseExecutionException[[modernrugs_3][1]: query[function score (filtered(ConstantScore(*:*))->+cache(_type:models.Product) ++cache(all_sizes.lt:[85 TO 100]) ++cache(all_sizes.price:[0.0 TO 1000000.0]) +cache(BooleanFilter(relevancy_scores.162:[* TO *])) +cache(BooleanFilter(relevancy_scores.176:[* TO *])),function=script[if (!relevancyIds.isEmpty()) {cnt=0;x = relevancyIds.split(',');if (x.length>0) {for (i=0;i<x.length;i++) {p=x[i];if (!doc['relevancy_scores.'+p].isEmpty()) {relsProd=doc['relevancy_scores.'+p];if ((relsProd != null) && (!relsProd.empty&&relsProd.values.length>0)) {for (y=0;y<relsProd.values.length;y++) {cnt+=(int)relsProd.values[y];}}}}return cnt;} else {return _score}} else {return _score};], params [{_PAYLOADS=4, _FREQUENCIES=8, _source=org.elasticsearch.search.lookup.SourceLookup@5c7519d9, _fields=org.elasticsearch.search.lookup.FieldsLookup@bf424fb, _doc=org.elasticsearch.search.lookup.DocLookup@49a7e0de, _index=org.elasticsearch.search.lookup.IndexLookup@2c9c3499, doc=org.elasticsearch.search.lookup.DocLookup@49a7e0de, _CACHE=32, _score=1.0, _OFFSETS=2, relevancyIds=162, _POSITIONS=16}])],from[0],size[40]: Query Failed [Failed to execute main query]]; nested: EndWithValue; }{[Gy8DKMvoQKO5rousUfhQsw][modernrugs_3][0]: QueryPhaseExecutionException[[modernrugs_3][0]: query[function score (filtered(ConstantScore(*:*))->+cache(_type:models.Product) ++cache(all_sizes.lt:[85 TO 100]) ++cache(all_sizes.price:[0.0 TO 1000000.0]) +cache(BooleanFilter(relevancy_scores.162:[* TO *])) +cache(BooleanFilter(relevancy_scores.176:[* TO *])),function=script[if (!relevancyIds.isEmpty()) {cnt=0;x = relevancyIds.split(',');if (x.length>0) {for (i=0;i<x.length;i++) {p=x[i];if (!doc['relevancy_scores.'+p].isEmpty()) {relsProd=doc['relevancy_scores.'+p];if ((relsProd != null) && (!relsProd.empty&&relsProd.values.length>0)) {for (y=0;y<relsProd.values.length;y++) {cnt+=(int)relsProd.values[y];}}}}return cnt;} else {return _score}} else {return _score};], params [{_PAYLOADS=4, _FREQUENCIES=8, _source=org.elasticsearch.search.lookup.SourceLookup@12baae0f, _fields=org.elasticsearch.search.lookup.FieldsLookup@1df96464, _doc=org.elasticsearch.search.lookup.DocLookup@602df09b, _index=org.elasticsearch.search.lookup.IndexLookup@680f8171, doc=org.elasticsearch.search.lookup.DocLookup@602df09b, _CACHE=32, _score=1.0, _OFFSETS=2, relevancyIds=162, _POSITIONS=16}])],from[0],size[40]: Query Failed [Failed to execute main query]]; nested: EndWithValue; }]",
"status": 500
}

My query is as follows:

{
  "from": 0,
  "size": 40,
  "query": {
    "function_score": {
      "query": {
        "filtered": {
          "query": {
            "bool": {
              "should": {
                "match_all": {}
              }
            }
          },
          "filter": {
            "and": {
              "filters": [
                {
                  "or": {
                    "filters": [
                      {
                        "type": {
                          "value": "models.Product"
                        }
                      }
                    ]
                  }
                },
                {
                  "and": {
                    "filters": [
                      {
                        "range": {
                          "all_sizes.lt": {
                            "from": 85,
                            "to": 100,
                            "include_lower": true,
                            "include_upper": true
                          }
                        }
                      }
                    ]
                  }
                },
                {
                  "and": {
                    "filters": [
                      {
                        "range": {
                          "all_sizes.price": {
                            "from": 0,
                            "to": 1000000,
                            "include_lower": true,
                            "include_upper": true
                          }
                        }
                      }
                    ]
                  }
                },
                {
                  "or": {
                    "filters": []
                  }
                },
                {
                  "or": {
                    "filters": [
                      {
                        "or": {
                          "filters": [
                            {
                              "exists": {
                                "field": "relevancy_scores.162"
                              }
                            }
                          ]
                        }
                      }
                    ]
                  }
                },
                {
                  "or": {
                    "filters": [
                      {
                        "or": {
                          "filters": [
                            {
                              "exists": {
                                "field": "relevancy_scores.176"
                              }
                            }
                          ]
                        }
                      }
                    ]
                  }
                },
                {
                  "or": {
                    "filters": []
                  }
                },
                {
                  "or": {
                    "filters": []
                  }
                },
                {
                  "or": {
                    "filters": []
                  }
                },
                {
                  "or": {
                    "filters": []
                  }
                }
              ]
            }
          }
        }
      },
      "script_score": {
        "script": "if (!relevancyIds.isEmpty()) {cnt=0;x = relevancyIds.split(',');if (x.length>0) {for (i=0;i<x.length;i++) {p=x[i];if (!doc['relevancy_scores.'+p].isEmpty()) {relsProd=doc['relevancy_scores.'+p];if ((relsProd != null) && (!relsProd.empty&&relsProd.values.length>0)) {for (y=0;y<relsProd.values.length;y++) {cnt+=(int)relsProd.values[y];}}}}return cnt;} else {return _score}} else {return _score};",
        "params": {
          "relevancyIds": "162"
        }
      },
      "boost_mode": "replace"
    }
  },
  "fields": "_id",
  "sort": [
    {
      "_score": {
        "order": "desc"
      }
    }
  ],
  "facets": {
    "modelType": {
      "terms": {
        "field": "_type",
        "size": 10
      }
    },
    "relevancyId": {
      "terms": {
        "field": "all_relevancies.id",
        "size": 10
      }
    }
  }
}

Like I say it works fine on DEV but not on LIVE with the same code version. At the moment I am thinking its down to the actual data having something missing but I did a compare (using es mashup) and the object are identical :( :( :(

I am quickly losing hair so if anyone can help that would be awesome

**Comment by clintongormley** [comment]
Hi @elliswood 

This appears to be coming from MVEL https://github.com/mvel/mvel/blob/master/src/main/java/org/mvel2/compiler/EndWithValue.java

MVEL has had problems with recent JVMs and we no longer support it.  I can't offer much more advice than: it's time to upgrade...

**Comment by elliswood** [comment]
Cheers ClintonGormley..good to know but we are kinda stuck with what we got :)
