### ISSUE TITLE
Remove the object notation for string fields

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#15388]
When specifying a string field, you can either do:

```
{
  "foo": "bar"
}
```

or

```
{
  "foo": {
    "value": "bar",
    "boost": 42
  }
}
```

The latter option is not documented anymore but I think it used to. However I have some doubts that many users are using it, and we tend to not recommend index-time boosting anyway so maybe it should go away?

**Comment by clintongormley** [comment]
+1

**Comment by jimferenczi** [comment]
The object definition with boost and value is not working with multi fields (see #4320) so +1 on this.
