### ISSUE TITLE
Documentation about translog fsync is a bit confusing

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#15387]
From https://www.elastic.co/guide/en/elasticsearch/reference/2.x/index-modules-translog.html#_translog_settings

```
By default, Elasticsearch fsyncs and commits the translog every 5 seconds and at the end of every index, delete, update, or bulk request. 
```

I think the interval-based fsync is only useful in case you disable the per-write fsync, so it's a bit confusing to say that elasticsearch does both as it implies that the interval-based fsync is still useful when you already fsync after every write operation?

**Comment by mikemccand** [comment]
Can we just remove the "every 5 seconds and"?  Also, maybe remove the "fsync" ... this is an impl detail?  So just say:

```
By default, Elasticsearch commits the translog after every index, delete, update or bulk request.
```

**Comment by s1monw** [comment]
++ to what mike said @jpountz do you just wanna make that change and push it?

**Comment by jpountz** [comment]
+1

**Comment by nik9000** [comment]
> ++ to what mike said @jpountz do you just wanna make that change and push it?

+!

**Comment by clintongormley** [comment]
Fixed
