### ISSUE TITLE
Config `index.mapper.dynamic: false` is not honored.

### ISSUE THREAD

**Issue by zamblauskas** [elastic/elasticsearch#15381]
Even with `index.mapper.dynamic: false` in the config file, automatic mapping is being created.
[Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-creation) states that:
> Automatic mapping creation can be disabled by setting index.mapper.dynamic to false in the config files

steps to reproduce
==================

step 1.  Make sure setting exists:
```
cat config/elasticsearch.yml | grep mapper
index.mapper.dynamic: false
```
step 2.  Make sure no mapping or template exists:
```
curl http://localhost:9200/_mapping
{}
curl http://localhost:9200/_template
{}
```
step 3. Create an index:
```
curl -XPUT http://localhost:9200/myindex/mytype/1 -d '{
   "myfield": 1
}'
{"_index":"myindex","_type":"mytype","_id":"1","_version":1,"_shards":{"total":1,"successful":1,"failed":0},"created":true}
```
step 4. Notice, that a mapping was automatically created:
```
curl http://localhost:9200/_mapping
{"myindex":{"mappings":{"mytype":{"properties":{"myfield":{"type":"long"}}}}}}
```

expected
========
No mapping should be automatically created at step 4.

other info
========
```
curl http://localhost:9200
{
  "name" : "master",
  "cluster_name" : "traveltime",
  "version" : {
    "number" : "2.1.0",
    "build_hash" : "72cd1f1a3eee09505e036106146dc1949dc5dc87",
    "build_timestamp" : "2015-11-18T22:40:03Z",
    "build_snapshot" : false,
    "lucene_version" : "5.3.1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by clintongormley** [comment]
It appears that this parameter is ignored during the index creation process, eg:

    PUT t 
    {
      "settings": {
        "index.mapper.dynamic": false
      }
    }

This throws an exception correctly:

    PUT t/x/1
    {}

But start a node with `--index.mapper.dynamic false`, then:

    DELETE t

This creates the `t` index with the `x` type:

    PUT t/x/1
    {}    

And this then fails with the correct exception:

    PUT t/y/2
    {}

**Comment by davidvgalbraith** [comment]
I took a stab at this one: https://github.com/elastic/elasticsearch/pull/15424. Had a little trouble with the test setup so could use some input.
