### ISSUE TITLE
Change docs on "node client" to not use an in-memory node

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#15383]
Currently we suggesting users create a Node (using NodeBuilder in 2.x) to have a client that is capable of keeping up-to-date information. This is generally a bad idea as it means elasticsearch has no control over eg max heap size or gc settings, and is also problematic for users because they must deal with dependency collisions (and in 2.x+ dependencies of elasticsearch itself).

A better alternative, and what we should document, is to run a local elasticsearch server using bin/elasticsearch, and then use the transport client to connect to that local node. This local connection is virtually free, and allows the client code to be completely isolated from the elasticsearch process. Plugins are then also easy to deal with: just install them in elasticsearch as usual.

**Comment by javanna** [comment]
+1

**Comment by clintongormley** [comment]
The node docs have been significantly rewritten. https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html Closing.

**Comment by clintongormley** [comment]
Actually, the Java docs need updating: https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/node-client.html
