### ISSUE TITLE
LM Similarity returns all zero scores

### ISSUE THREAD

**Issue by keikha** [elastic/elasticsearch#15397]
When I use the LMDirichlet similarity I get back are all zero scores. Here is the steps to reproduce the problem:
1) Created the index:

{ "settings": { "similarity": { "LMSimilarity": { "type": "LMDirichlet", "mu": 2500 } } }, "mappings": { "item": { "properties": { "title": { "type": "string", "similarity": "LMSimilarity" } } } } }

2) Indexed two documents:

{"title":"This is a test for search similarity when we search by other search options."}
{"title”:”Search looks weird when use other search possibilities. Numbers are not clear. Just adding new stuff to make the document longer. Document norm looks weird."}

3) Run a simple query:

{ "explain": "true", "query": { "match": { "title": "search" } } }

If you look at the returned scores, there are multiple weird numbers:
1) The score for all documents is zero
2) The collection probability, a term property that is independent from individual documents, is different for each document. I expect this number to be the same for all documents for a given term.
3) Document norm has a negative value, probably it's the log of another number, but I can't match these numbers to the LM formula.

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/15345
