### ISSUE TITLE
 Recover the old indices after restarting Elasticsearch

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch#15392]
I have an elasticsearch cluster with three nodes and with this configuration:
```
cluster.name: my_cluster_name

bootstrap.mlockall: true

indices.recovery.max_bytes_per_sec: 100mb
discovery.zen.minimum_master_nodes: 2
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["ip_node_1", "ip_node_2"]

path.logs: elasticsearch/logs
path.data: elasticsearch/data
path.work: elasticsearch/work
path.plugins: elasticsearch/plugins

http.cors.enabled: true
http.cors.allow-origin: /.*/
http.cors.allow-credentials: true 

index.routing.allocation.disable_allocation: false
```

This cluster was restarted and in the path
```
/elasticsearch/data/my_cluster_name/nodes/0/indices
```
Where elasticsearch save the indices I can see:
```
ls -las

total 24
4 drwxr-xr-x 6 jdiazg group 4096 Dec 11 09:01 .
4 drwxr-xr-x 4 jdiazg group 4096 Dec 10 14:19 ..
4 drwxr-xr-x 7 jdiazg group 4096 Dec  8 09:29 index_1
4 drwxr-xr-x 5 jdiazg group 4096 Dec  1 03:15 index_2
4 drwxr-xr-x 5 jdiazg group 4096 Nov 20 15:34 index_3
4 drwxr-xr-x 6 jdiazg group 4096 Dec  3 03:42 index_4
```
and with
```
du -sh  * 

514M    index_1
48M     index_2
420K    index_3
332K    index_4
```
in the three nodes, but if I execute:
```
curl localhost:9200/_cat/indices?v
```
I am not able to see this old indices and elastic_search don´t recognice when the name of the cluster after restarting is the same.

**Comment by clintongormley** [comment]
What's in the logs?

**Comment by juandasgandaras** [comment]
In the logs from the cluster node I can see that the the module gateway try to recover the one index but it is not able to  recognize the oldest indices in the directory although they appear in the directory 

```
/elasticsearch/data/my_cluster_name/nodes/0/indices
```

The logs are:
```
[2015-12-14 16:28:38,305][INFO ][http                     ] [Jacqueline Falsworth] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/10.8.5.15:9200]}
[2015-12-14 16:28:38,305][INFO ][node                     ] [Jacqueline Falsworth] started
[2015-12-14 16:28:38,764][INFO ][cluster.service          ] [Jacqueline Falsworth] added {[Mary Jane Parker][sJRJICsiQcO2T3YL3m7bQw][bc10-07][inet[/10.8.5.17:9300]],}, reason: zen-disco-receive(join from node[[Mary Jane Parker][sJRJICsiQcO2T3YL3m7bQw][bc10-07][inet[/10.8.5.17:9300]]])
[2015-12-14 16:28:38,780][INFO ][gateway                  ] [Jacqueline Falsworth] delaying initial state recovery for [5m]. expecting [3] nodes, but only have [2]
[2015-12-14 16:30:19,035][INFO ][cluster.service          ] [Jacqueline Falsworth] added {[Hindsight Lad][ONuKxehCQz-ty-L5_2Mn6Q][bc10-03][inet[/10.8.5.13:9300]],}, reason: zen-disco-receive(join from node[[Hindsight Lad][ONuKxehCQz-ty-L5_2Mn6Q][bc10-03][inet[/10.8.5.13:9300]]])
[2015-12-14 16:30:19,886][INFO ][gateway                  ] [Jacqueline Falsworth] recovered [1] indices into cluster_state
[2015-12-14 16:52:22,694][INFO ][cluster.service          ] [Jacqueline Falsworth] removed {[Mary Jane Parker][sJRJICsiQcO2T3YL3m7bQw][bc10-07][inet[/10.8.5.17:9300]],}, reason: zen-disco-node_left([Mary Jane Parker][sJRJICsiQcO2T3YL3m7bQw][bc10-07][inet[/10.8.5.17:9300]])
[2015-12-14 16:55:26,961][INFO ][cluster.service          ] [Jacqueline Falsworth] added {[Ringmaster][rfnlKtTiQa6yEuwgkg6hag][bc10-07][inet[/10.8.5.17:9300]],}, reason: zen-disco-receive(join from node[[Ringmaster][rfnlKtTiQa6yEuwgkg6hag][bc10-07][inet[/10.8.5.17:9300]]])
```

And in the directory we can see:

```
pwd

/tmp/elasticsearch/data/my_cluster_name/nodes/0/indices

ls -las

total 24
4 drwxr-xr-x 6 jdiazg group 4096 Dec 11 09:01 .
4 drwxr-xr-x 4 jdiazg group 4096 Dec 10 14:19 ..
4 drwxr-xr-x 7 jdiazg group 4096 Dec  8 09:29 index_1
4 drwxr-xr-x 5 jdiazg group 4096 Dec  1 03:15 index_2
4 drwxr-xr-x 5 jdiazg group 4096 Nov 20 15:34 index_3
4 drwxr-xr-x 6 jdiazg group 4096 Dec  3 03:42 index_4
```

**Comment by bleskes** [comment]
> ```
4 drwxr-xr-x 7 jdiazg group 4096 Dec  8 09:29 index_1
4 drwxr-xr-x 5 jdiazg group 4096 Dec  1 03:15 index_2
4 drwxr-xr-x 5 jdiazg group 4096 Nov 20 15:34 index_3
4 drwxr-xr-x 6 jdiazg group 4096 Dec  3 03:42 index_4
```

Thanks. Can you also list the directories bellow the index directory? I'm looking to see if there is a valid `_state` folder with a state file.

**Comment by juandasgandaras** [comment]
```
tree index_1/

index_1/
├── 0
│   ├── index
│   ├── _state
│   │   └── state-8
│   └── translog
├── 2
│   ├── index
│   ├── _state
│   │   └── state-5
│   └── translog
├── 3
│   ├── index
│   ├── _state
│   │   └── state-6
│   └── translog
└── 4
    ├── index
    ├── _state
    │   └── state-6
    └── translog

tree index_2/
index_2/
├── 1
│   ├── index
│   ├── _state
│   │   └── state-8
│   └── translog
├── 3
│   ├── index
│   ├── _state
│   │   └── state-6
│   └── translog
└── 4
    ├── index
    ├── _state
    │   └── state-6
    └── translog

 tree index_3/
new_gompute_history_ldap/
├── 1
│   ├── index
│   └── translog
├── 2
│   └── index
├── 3
│   ├── index
│   └── translog
└── 4
    └── index

tree index_4/

tree index_4/
index_4/
├── 0
│   ├── index
│   │   ├── segments_5
│   │   ├── segments.gen
│   │   └── write.lock
│   ├── _state
│   │   ├── state-21
│   │   └── state-3
│   └── translog
│       └── translog-1449847248888
├── 2
│   ├── index
│   │   ├── segments_5
│   │   ├── segments.gen
│   │   └── write.lock
│   ├── _state
│   │   └── state-16
│   └── translog
│       └── translog-1449847248515
├── 3
│   ├── index
│   │   ├── segments_5
│   │   ├── segments.gen
│   │   └── write.lock
│   ├── _state
│   │   └── state-13
│   └── translog
│       └── translog-1449847248888
├── 4
│   ├── index
│   │   ├── segments_6
│   │   ├── segments.gen
│   │   └── write.lock
│   ├── _state
│   │   └── state-18
│   └── translog
│       └── translog-1449847249266
└── _state
    └── state-3

```

The last index the index_4 I can see it but I after I inserted new data over it ot test and I try to do do a  snapshot to restore all the data without success.

Do you want to see more information?

**Comment by bleskes** [comment]
Thanks @juandasgandaras this makes it clear. You'll notice only index_4 has a `_state` folder, which is why it's the only one that's imported. The question is what happened to the _state folder of the other indices. Were the indices delete at some point in time? also what ES version are we talking about?

**Comment by juandasgandaras** [comment]
Hi,

This is because I modified the index_4 to test and after I tried to save all the indices but only one (the index_4) was saved.

I have never deleted the indices in Elasticsearch. The problem was that the diferent host over elasticsearch was running were shotdowned.

After this I tried to restart the Elasticsearch cluster with the same cluster name and the same parameters, but when I restart elasticsearch, this cluster doesn´t find this folders. 

The elasticsearch version that I am using is 1.4.4

**Comment by clintongormley** [comment]
@juandasgandaras So much has changed since 1.4.4, I highly recommend upgrading.

**Comment by shortdudey123** [comment]
@clintongormley any update on this? having this issue on 1.7.2

**Comment by bleskes** [comment]
@ShirlinYiu not sure what kind of update you are expecting. The index folders you mention also do not contain the index state file, which means you were probably running with dedicated master nodes. I presume you had some problem and lost the master nodes' data folders. With 1.7 that would mean the index data can not be used as we miss all the meta data associated with it. With 2.x this is no longer the case as we store a redundant copy (it's not used) of the meta data on all data nodes as well.

**Comment by shortdudey123** [comment]
@bleskes assuming you meant me

I was expecting there to be a resolution to this issue since you had said `So much has changed since 1.4.4`.  I ended up having to blow the cluster away with complete data loss.

**Comment by bleskes** [comment]
@shortdudey123 yeah, sorry I meant you indeed...  I suspect the problem is cause by the loss of all master nodes which in 1.x will indeed cause indices not to be re-imported (as designed, ...) . In 2.x we add a safety net for this kind of cases by adding a backup file into each index folder. In that sense, this issue is solved, but you need to upgrade.

**Comment by shortdudey123** [comment]
gotcha, thanks!

**Comment by nxycdl** [comment]
I have some quest , and a delete some old indices ,and is becoming ok 
```
curl -X DELETE 'localhost:9200/filebeat-2018*' 
```
