### ISSUE TITLE
Possible regression in highlighting - highlight_query ignored if is different than highlight field

### ISSUE THREAD

**Issue by sicarrots** [elastic/elasticsearch#15407]
I'm indexing simple document with three fields:
`text_content_0: "Skrzydła samolotu"`
`text_content_1: "Wyposażenie samolotu"`
`text_content: "Skrzydła samolotu. Wyposażenie samolotu".``

text_content* fields have `"index_options": "offsets"`.

Then i'm querying:
```
{
  "highlight": {
    "fields": {
      "text_content_*": {
        "type": "postings",
        "highlight_query": {
          "match": {
            "text_content": "Skrzydła"
          }
        }
      }
    }
  }, 
  "query": {
   "filtered": {
      "filter": {
        "ids": {
          "values": [1]
        }
      }
    }
  }
}
```
In ES < 2.0 (1.7.3) i'm getting proper results: one document is returned, field _text_content_0 is highlighted with word "skrzydło". In ES > 2.0 (i've tried 2.0.1, 2.1.0) highlight is not returned. I've found  #10627 but adding `require_field_match: false` does not working. Changing `highlight_query.match` to 
```
"text_content_0": "Skrzydła"
``` 
or
to muliti_match:
```
"fields": ["text_content_*"],
 "query": "Skrzydła"
```
works fine - highlights are returned.

**Comment by clintongormley** [comment]
Correct: Require-field-match is no longer supported by the postings highlighter: https://github.com/elastic/elasticsearch/pull/11077
