### ISSUE TITLE
Systemd - Template, This process can't be executed

### ISSUE THREAD

**Issue by clems09** [elastic/elasticsearch#15406]
I, 

I haved a work to do in my class with systemd templates. 

I need to make a service that will erase log fill in a log directory at boot time. For exemple /var/log/squid/.

I need to erase logs of 3 differents directory. And I need one systemd file.

i have create my "rmlog@.service" file in "/etc/systemd/system". 

my "rmlog@.service" look like that : 

                [Unit]
                Description=Suppressions des fichiers contenus dans /var/log/X

                [Service]
                Type=oneshot
                ExecStart=/etc/TP/%i.sh

                [Install]
                WantedBy=default.target

My logs says "this process /etc/TP/%i.sh can't be executed"

Anyone can help me ? 

Thanks

**Comment by jasontedor** [comment]
Closing as this does not seem to be specific to Elasticsearch.
