### ISSUE TITLE
Grouping - getting error

### ISSUE THREAD

**Issue by SriramanK** [elastic/elasticsearch#15414]
POST logstash-*\Win32-EventLog-*\_search
{
  "aggregations": {
    "group_by_type": {
      "terms": {
        "field": "EventType"
      }
    }
  }
}

Got the response as 
{
   "error": {
      "root_cause": [
         {
            "type": "exception",
            "reason": "java.lang.IllegalStateException: Field data loading is forbidden on EventType"
         }
      ],
      "type": "search_phase_execution_exception",
      "reason": "all shards failed",
      "phase": "query",
      "grouped": true,
      "failed_shards": [
         {
            "shard": 0,
            "index": "logstash-2015.12.09",
            "node": "E1fNPBJVSi6mg09orkNsJg",
            "reason": {
               "type": "exception",
               "reason": "java.lang.IllegalStateException: Field data loading is forbidden on EventType",
               "caused_by": {
                  "type": "unchecked_execution_exception",
                  "reason": "java.lang.IllegalStateException: Field data loading is forbidden on EventType",
                  "caused_by": {
                     "type": "illegal_state_exception",
                     "reason": "Field data loading is forbidden on EventType"
                  }
               }
            }
         }
      ]

Sample available data
{
   "took": 63,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 70,
      "max_score": 1,
      "hits": [
         {
            "_index": "logstash-2015.12.09",
            "_type": "Win32-EventLog-Application",
            "_id": "AVGF_qw84BUvtVRjtnfx",
            "_score": 1,
            "_source": {
               "host": "Sriraman",
               "Logfile": "Application",
               "message": "CoId={4462F43E-1262-4AD1-99CD-9BC92C6D914A}: The user SRIRAMAN\\Toshiba has started dialing a Dial-up connection using a all-user connection profile named airtel. The connection settings are: \nDial-in User = \nVpnStrategy =Not Applicable\nDataEncryption = Requested\nPrerequisiteEntry = \nAutoLogon = No\nUseRasCredentials = Yes\nAuthentication Type = CHAP \nIpv4DefaultGateway = Yes\nIpv4AddressAssignment = By Server\nIpv4DNSServerAssignment = By Server\nIpv6DefaultGateway = No\nIpv6AddressAssignment = By Server\nIpv6DNSServerAssignment = By Server\nIpDnsFlags = \nIpNBTEnabled = Yes\nUseFlags = Private Connection\nConnectOnWinlogon = No.",
               "Category": 0,
               "ComputerName": "Sriraman",
               "EventIdentifier": 20221,
               "EventType": "information",
               "RecordNumber": 31962,
               "SourceName": "RasClient",
               "TimeGenerated": "2015-12-09 14:37:14 +0530",
               "TimeWritten": "2015-12-09 14:37:14 +0530",
               "Type": "information",
               "User": null,
               "InsertionStrings": [
                  "{4462F43E-1262-4AD1-99CD-9BC92C6D914A}",
                  "SRIRAMAN\\Toshiba",
                  "Dial-up",
                  "all-user",
                  "airtel",
                  "\nDial-in User = \nVpnStrategy =Not Applicable\nDataEncryption = Requested\nPrerequisiteEntry = \nAutoLogon = No\nUseRasCredentials = Yes\nAuthentication Type = CHAP \nIpv4DefaultGateway = Yes\nIpv4AddressAssignment = By Server\nIpv4DNSServerAssignment = By Server\nIpv6DefaultGateway = No\nIpv6AddressAssignment = By Server\nIpv6DNSServerAssignment = By Server\nIpDnsFlags = \nIpNBTEnabled = Yes\nUseFlags = Private Connection\nConnectOnWinlogon = No"
               ],
               "@version": "1",
               "@timestamp": "2015-12-09T09:07:14.991Z",
               "type": "Win32-EventLog-Application",
               "user_id": "100",
               "guid": "83e65e43-3ddd-454f-a9c1-c27be7ac36b9"
            }
         },

Elasticsearch Version - 2.1.0
Java Version jdk1.7.0_65

**Comment by dadoonet** [comment]
Please use discuss.elasti.co

I guess you are using logstash so probably you should use EventType.raw

Open a thread on discuss and also provide your mapping.

**Comment by SriramanK** [comment]
I am using logstash. 
GET logstash-2015.12.09\Win32-EventLog-Application\_mapping
Enclosed Mapping
   "logstash-2015.12.09": {
      "mappings": {
         "Win32-EventLog-Application": {
            "_all": {
               "enabled": true,
               "omit_norms": true
            },
            "dynamic_templates": [
               {
                  "message_field": {
                     "mapping": {
                        "index": "analyzed",
                        "omit_norms": true,
                        "fielddata": {
                           "format": "disabled"
                        },
                        "type": "string"
                     },
                     "match": "message",
                     "match_mapping_type": "string"
                  }
               },
               {
                  "string_fields": {
                     "mapping": {
                        "index": "analyzed",
                        "omit_norms": true,
                        "fielddata": {
                           "format": "disabled"
                        },
                        "type": "string",
                        "fields": {
                           "raw": {
                              "index": "not_analyzed",
                              "ignore_above": 256,
                              "doc_values": true,
                              "type": "string"
                           }
                        }
                     },
                     "match": "*",
                     "match_mapping_type": "string"
                  }
               },
               {
                  "float_fields": {
                     "mapping": {
                        "doc_values": true,
                        "type": "float"
                     },
                     "match": "*",
                     "match_mapping_type": "float"
                  }
               },
               {
                  "double_fields": {
                     "mapping": {
                        "doc_values": true,
                        "type": "double"
                     },
                     "match": "*",
                     "match_mapping_type": "double"
                  }
               },
               {
                  "byte_fields": {
                     "mapping": {
                        "doc_values": true,
                        "type": "byte"
                     },
                     "match": "*",
                     "match_mapping_type": "byte"
                  }
               },
               {
                  "short_fields": {
                     "mapping": {
                        "doc_values": true,
                        "type": "short"
                     },
                     "match": "*",
                     "match_mapping_type": "short"
                  }
               },
               {
                  "integer_fields": {
                     "mapping": {
                        "doc_values": true,
                        "type": "integer"
                     },
                     "match": "*",
                     "match_mapping_type": "integer"
                  }
               },
               {
                  "long_fields": {
                     "mapping": {
                        "doc_values": true,
                        "type": "long"
                     },
                     "match": "*",
                     "match_mapping_type": "long"
                  }
               },
               {
                  "date_fields": {
                     "mapping": {
                        "doc_values": true,
                        "type": "date"
                     },
                     "match": "*",
                     "match_mapping_type": "date"
                  }
               },
               {
                  "geo_point_fields": {
                     "mapping": {
                        "doc_values": true,
                        "type": "geo_point"
                     },
                     "match": "*",
                     "match_mapping_type": "geo_point"
                  }
               }
            ],
            "properties": {
               "@timestamp": {
                  "type": "date",
                  "format": "strict_date_optional_time||epoch_millis"
               },
               "@version": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "Category": {
                  "type": "long"
               },
               "ComputerName": {
                  "type": "string",
                  "norms": {
                     "enabled": false
                  },
                  "fielddata": {
                     "format": "disabled"
                  },
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed",
                        "ignore_above": 256
                     }
                  }
               },
               "EventIdentifier": {
                  "type": "long"
               },
               "EventType": {
                  "type": "string",
                  "norms": {
                     "enabled": false
                  },
                  "fielddata": {
                     "format": "disabled"
                  },
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed",
                        "ignore_above": 256
                     }
                  }
               },
               "InsertionStrings": {
                  "type": "string",
                  "norms": {
                     "enabled": false
                  },
                  "fielddata": {
                     "format": "disabled"
                  },
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed",
                        "ignore_above": 256
                     }
                  }
               },
               "Logfile": {
                  "type": "string",
                  "norms": {
                     "enabled": false
                  },
                  "fielddata": {
                     "format": "disabled"
                  },
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed",
                        "ignore_above": 256
                     }
                  }
               },
               "RecordNumber": {
                  "type": "long"
               },
               "SourceName": {
                  "type": "string",
                  "norms": {
                     "enabled": false
                  },
                  "fielddata": {
                     "format": "disabled"
                  },
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed",
                        "ignore_above": 256
                     }
                  }
               },
               "TimeGenerated": {
                  "type": "string",
                  "norms": {
                     "enabled": false
                  },
                  "fielddata": {
                     "format": "disabled"
                  },
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed",
                        "ignore_above": 256
                     }
                  }
               },
               "TimeWritten": {
                  "type": "string",
                  "norms": {
                     "enabled": false
                  },
                  "fielddata": {
                     "format": "disabled"
                  },
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed",
                        "ignore_above": 256
                     }
                  }
               },
               "Type": {
                  "type": "string",
                  "norms": {
                     "enabled": false
                  },
                  "fielddata": {
                     "format": "disabled"
                  },
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed",
                        "ignore_above": 256
                     }
                  }
               },
               "geoip": {
                  "dynamic": "true",
                  "properties": {
                     "city_name": {
                        "type": "string",
                        "norms": {
                           "enabled": false
                        },
                        "fielddata": {
                           "format": "disabled"
                        },
                        "fields": {
                           "raw": {
                              "type": "string",
                              "index": "not_analyzed",
                              "ignore_above": 256
                           }
                        }
                     },
                     "continent_code": {
                        "type": "string",
                        "norms": {
                           "enabled": false
                        },
                        "fielddata": {
                           "format": "disabled"
                        },
                        "fields": {
                           "raw": {
                              "type": "string",
                              "index": "not_analyzed",
                              "ignore_above": 256
                           }
                        }
                     },
                     "coordinates": {
                        "type": "double"
                     },
                     "country_code2": {
                        "type": "string",
                        "norms": {
                           "enabled": false
                        },
                        "fielddata": {
                           "format": "disabled"
                        },
                        "fields": {
                           "raw": {
                              "type": "string",
                              "index": "not_analyzed",
                              "ignore_above": 256
                           }
                        }
                     },
                     "country_code3": {
                        "type": "string",
                        "norms": {
                           "enabled": false
                        },
                        "fielddata": {
                           "format": "disabled"
                        },
                        "fields": {
                           "raw": {
                              "type": "string",
                              "index": "not_analyzed",
                              "ignore_above": 256
                           }
                        }
                     },
                     "country_name": {
                        "type": "string",
                        "norms": {
                           "enabled": false
                        },
                        "fielddata": {
                           "format": "disabled"
                        },
                        "fields": {
                           "raw": {
                              "type": "string",
                              "index": "not_analyzed",
                              "ignore_above": 256
                           }
                        }
                     },
                     "ip": {
                        "type": "ip"
                     },
                     "latitude": {
                        "type": "float"
                     },
                     "location": {
                        "type": "geo_point"
                     },
                     "longitude": {
                        "type": "float"
                     },
                     "real_region_name": {
                        "type": "string",
                        "norms": {
                           "enabled": false
                        },
                        "fielddata": {
                           "format": "disabled"
                        },
                        "fields": {
                           "raw": {
                              "type": "string",
                              "index": "not_analyzed",
                              "ignore_above": 256
                           }
                        }
                     },
                     "region_name": {
                        "type": "string",
                        "norms": {
                           "enabled": false
                        },
                        "fielddata": {
                           "format": "disabled"
                        },
                        "fields": {
                           "raw": {
                              "type": "string",
                              "index": "not_analyzed",
                              "ignore_above": 256
                           }
                        }
                     },
                     "timezone": {
                        "type": "string",
                        "norms": {
                           "enabled": false
                        },
                        "fielddata": {
                           "format": "disabled"
                        },
                        "fields": {
                           "raw": {
                              "type": "string",
                              "index": "not_analyzed",
                              "ignore_above": 256
                           }
                        }
                     }
                  }
               },
               "guid": {
                  "type": "string",
                  "norms": {
                     "enabled": false
                  },
                  "fielddata": {
                     "format": "disabled"
                  },
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed",
                        "ignore_above": 256
                     }
                  }
               },
               "host": {
                  "type": "string",
                  "norms": {
                     "enabled": false
                  },
                  "fielddata": {
                     "format": "disabled"
                  },
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed",
                        "ignore_above": 256
                     }
                  }
               },
               "hostip": {
                  "type": "string",
                  "norms": {
                     "enabled": false
                  },
                  "fielddata": {
                     "format": "disabled"
                  },
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed",
                        "ignore_above": 256
                     }
                  }
               },
               "message": {
                  "type": "string",
                  "norms": {
                     "enabled": false
                  },
                  "fielddata": {
                     "format": "disabled"
                  }
               },
               "query": {
                  "properties": {
                     "term": {
                        "properties": {
                           "EventType": {
                              "type": "string",
                              "norms": {
                                 "enabled": false
                              },
                              "fielddata": {
                                 "format": "disabled"
                              },
                              "fields": {
                                 "raw": {
                                    "type": "string",
                                    "index": "not_analyzed",
                                    "ignore_above": 256
                                 }
                              }
                           }
                        }
                     }
                  }
               },
               "tags": {
                  "type": "string",
                  "norms": {
                     "enabled": false
                  },
                  "fielddata": {
                     "format": "disabled"
                  },
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed",
                        "ignore_above": 256
                     }
                  }
               },
               "type": {
                  "type": "string",
                  "norms": {
                     "enabled": false
                  },
                  "fielddata": {
                     "format": "disabled"
                  },
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed",
                        "ignore_above": 256
                     }
                  }
               },
               "user_id": {
                  "type": "string",
                  "norms": {
                     "enabled": false
                  },
                  "fielddata": {
                     "format": "disabled"
                  },
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed",
                        "ignore_above": 256
                     }
                  }
               }
            }
         }
      }
   }
}

On using EventType.raw
POST logstash-*\Win32-EventLog-*\_search
{
  "aggregations": {
    "group_by_type": {
      "terms": {
        "field": "EventType.raw"
      }
    }
  }
}
Output is 
{
   "took": 81,
   "timed_out": false,
   "_shards": {
      "total": 10,
      "successful": 10,
      "failed": 0
   },
   "hits": {
      "total": 0,
      "max_score": null,
      "hits": []
   },
   "aggregations": {
      "group_by_type": {
         "doc_count_error_upper_bound": 0,
         "sum_other_doc_count": 0,
         "buckets": []
      }
   }
}

But this is not expected

**Comment by dadoonet** [comment]
fielddata is disabled on analyzed String fields. So your error message is expected.
Please follow up on discuss.

**Comment by SriramanK** [comment]
Can you help me with any link to solve this issue.
