### ISSUE TITLE
ATLEAST  query 

### ISSUE THREAD

**Issue by ESamir** [elastic/elasticsearch#15417]
Customer will like a new type of query 

We can call it "ATLEAST" query it will look for all documents which contain at least N times a specific term 
 
like find all the document that Atleast contain the term Paris 5 times .

**Comment by clintongormley** [comment]
This can be done very easily today. 

    PUT t/t/1
    {
      "text":"Paris is Paris and so is Paris"
    }
    
 The first method is a bit of a hack using the phrase query:

    GET t/_search
    {
      "query": {
        "constant_score": {
          "filter": {
            "match_phrase": {
              "text": {
                "query": "Paris Paris Paris",
                "slop": 1000
              }
            }
          }
        }
      }
    }
    
The second method using scripting will probably perform better:

    GET t/_search
    {
      "query": {
        "constant_score": {
          "filter": {
            "script": {
              "script": {
                "inline": "_index[field][term].tf() >= required",
                "params": {
                  "field": "text",
                  "term": "paris",
                  "required": 3
                }
              }
            }
          }
        }
      }
    }

**Comment by ESamir** [comment]
@clintongormley 

When testing with phrase query   was faster then using the script 

* phrase query: run in around 1.5s with 78 947 documents matching
* the script  run in around 40s with 82 documents matching

**Comment by jpountz** [comment]
Note that the script query example will examine all documents, including those that don't have the term. This can be made faster by intersecting it with a term query:

```
GET t/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "text": "paris"
          }
        },
        {
          "script": {
            "script": {
              "inline": "_index[field][term].tf() >= required",
              "params": {
                "field": "text",
                "term": "paris",
                "required": 3
              }
            }
          }
        }
      ]
    }
  }
}
```
