### ISSUE TITLE
Replica stuck at initializing (CorruptedIndexException)

### ISSUE THREAD

**Issue by Rok89** [elastic/elasticsearch#15419]
Hey,

We are using elasticsearch 1.4.2. We have a cluster with 4 nodes and two indices, each split into 5 shards and 1 replica per shard. After performing a necessary reboot on both servers, the cluster is stuck at yellow, because one replica in the first index is stuck at initializing (second index is fine). It looks as follows:

logs          2 p STARTED       9187625   1.7gb 127.0.1.1 node21_1 
logs           2 r STARTED       9187625   1.7gb 127.0.1.1 node22_2 
logs           0 r STARTED      56009065    11gb 127.0.1.1 node21_2 
logs           0 p STARTED      56009065    11gb 127.0.1.1 node21_1 
logs           3 p STARTED      56013686    11gb 127.0.1.1 node22_1 
logs           3 r INITIALIZING                                127.0.1.1 node21_2 
logs           1 r STARTED      56012034    11gb 127.0.1.1 node21_2 
logs           1 p STARTED      56012036    11gb 127.0.1.1 node21_1 
logs           4 p STARTED      56018956    11gb 127.0.1.1 node22_1 
logs           4 r STARTED      56018956    11gb 127.0.1.1 node22_2 

I checked the logs and I see the following exception keeps poping up:

[2015-12-14 12:34:18,689][DEBUG][action.admin.indices.stats] [node22_1] [logs][3], node[KfPAznKQRqu3QzTPRcQOTA], [R], s[INITIALIZING]: failed to execute [org.elasticsearch.action.admin.indices.stats.IndicesStatsRequest@644c3543]
org.elasticsearch.transport.RemoteTransportException: [node21_2][inet[/10.11.11.21:9301]][indices:monitor/stats[s]]
Caused by: org.elasticsearch.ElasticsearchException: io exception while building 'store stats'

I'd appreciate any tips on this. Thanks!

**Comment by clintongormley** [comment]
Hiya @Rok89 

Whatever is causing that exception, it's coming from a stats request, not from recovery.  You need to look elsewhere in your logs.  I'd suggest taking this to the forums instead: http://discuss.elastic.co/
