### ISSUE TITLE
Cannot create stubs of CreateIndexResponse and PutMappingResponse for testing with dummy data.

### ISSUE THREAD

**Issue by KoenDG** [elastic/elasticsearch#15411]
Since the constructors for CreateIndexResponse.java and PutMappingResponse.java have no access modifiers defined, they are "package-only" and cannot be extended or instantiated outside the package.

The files:

https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/action/admin/indices/create/CreateIndexResponse.java

https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/action/admin/indices/mapping/put/PutMappingResponse.java

That means that in code like this:

```
final ActionFuture<CreateIndexResponse> creatureFuture = client.admin().indices().create(new CreateIndexRequest("index_name"));

boolean acknowledged = createFuture.actionGet().isAcknowledged();
```

The actionGet() method cannot be overriden, because you can't extend or override CreateIndexResponse.

You could create a class that extends `ActionFuture<CreateIndexResponse>`, but the moment you do

```
@Override
public CreateIndexResponse actionGet() throws ElasticsearchException {
    return new CreateIndexResponse() {
        // override code
    };
}
```

You'll get exceptions because the class cannot be instantiated outside the package.

Meaning you can't write a stub for unit testing with dummy data, without actually running ElasticSearch.

Is there a way to overcome this? Or is this by design?

I'm working with ES 1.7.3.

**Comment by javanna** [comment]
hi @KoenDG sorry it has taken ages to get back to you. This is kind of by design, we usually increase visibility of classes and methods only when we really need to. These two classes can be subclassed now though and they have protected constructors, so this specific issue is solved.

**Comment by KoenDG** [comment]
Oh man, I had forgotten all about this. I got around this issue by using an in-memory cluster and setting that as the Client in dev and test mode.

I should have closed this ticket when I had a working solution, my bad.

**Comment by javanna** [comment]
no worries @KoenDG !
