### ISSUE TITLE
cluster.routing.allocation.node_concurrent_recoveries doesn't work as expected

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#15416]
GET _cluster/settings
{
  "transient": {
    "cluster": {
      "routing": {
        "allocation": {
          "node_concurrent_recoveries": "20"
        }
      }
    }
  }
}

but each time 
GET _recovery?active_only
{
  "2015-12-14": {
    "shards": [
      {
        "id": 14,
        "type": "REPLICA",
        "stage": "TRANSLOG",
        "primary": false,
      },
      {
        "id": 9,
        "type": "RELOCATION",
        "stage": "TRANSLOG",
        "primary": true,
      }
    ]
  }
}

only 2 shards are recoverying

**Comment by makeyang** [comment]
version: 2.1

**Comment by clintongormley** [comment]
There are a number of different settings.  one which may be hitting you is `cluster.routing.allocation.cluster_concurrent_rebalance`.  See https://www.elastic.co/guide/en/elasticsearch/reference/current/shards-allocation.html for more
