### ISSUE TITLE
Document 1.6 breaking change for snapshot "path.repo" requirement

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#15427]
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-1.6.html?q=breaking

Starting in ES 1.6, for shared file repositories, we require the setting of "path.repo" as part of a security fix.  If users have defined their snapshot repositories in versions < 1.6 and perform an upgrade to 1.6+, they will encounter this breaking change.

This change is currently documented [here](https://www.elastic.co/blog/elasticsearch-1-6-0-released#fs-config), but it is missing from the breaking changes documentation

**Comment by debadair** [comment]
No longer updating 1.x docs.
