### ISSUE TITLE
node info does not contain os arch and name

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#15422]
These two parameters are not serialized (https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/monitor/os/OsInfo.java#L107), although they are build in the json response (https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/monitor/os/OsInfo.java#L82). Consequently, when I start two nodes on one machine I get for one node

```
"os": {
        "refresh_interval_in_millis": 1000,
        "name": "Linux",
        "arch": "amd64",
        "version": "3.13.0-39-generic",
        "available_processors": 12,
        "allocated_processors": 12
      },
```
and

```
"os": {
        "refresh_interval_in_millis": 1000,
        "available_processors": 12,
        "allocated_processors": 12
      },
```

for the one that did not handle the request.
Is there any reason for it or should I fix it?

**Comment by jpountz** [comment]
+1 to fix

**Comment by nik9000** [comment]
Seems worth fixing.
