### ISSUE TITLE
Provide option to also delete files when deleting repository

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#15426]
Currently, when deleting a snapshot repository (by design), we leave the actual files in place so that one can recreate the repository at a later time and it will automatically pick up existing snapshots.  It will be nice to provide an option for those who would like the delete snapshot repository to also delete the underlying snapshot files (eg. the "start over" scenario).  This is helpful for the case where there are many snapshots in the repository and it will take a while to run individual delete snapshot api calls.

**Comment by dadoonet** [comment]
++

Or may be a purge API? So you can remove all files in a given repository without having to delete the repo itself?

**Comment by tlrx** [comment]
We talked about this issue today with @ywelsch and while we understand why this feature could be needed, we think that a total deletion must be made at the filesystem level. We changed the documentation in #29206 to emphases that "deleting" a repository in not _real_ a deletion but it unregisters the repository in the cluster state only.
