### ISSUE TITLE
Elasticsearch 2.1.0 does not bind to multiple interfaces

### ISSUE THREAD

**Issue by kjelle** [elastic/elasticsearch#15435]
Hello.

I have just upgraded from Elasticsearch 1.7.3 to Elasticsearch 2.1.0. I have a interface on my nodes, bond1, which relates to an ip 192.168.112.3. It seems I am unable to bind to multiple interfaces in 2.1.0.

(part of) elasticsearch.yaml
```
network:
  bind_host:
           - _bond1:ipv4_
           - localhost
  publish_host: _bond1:ipv4_
```
(Also, transport.tcp.port is 9301 and http.port is 9201)

In the boot, I get the following logline;
```
publish_address {192.168.112.3:9301}, bound_addresses {127.0.0.1:9301}, {[::1]:9301}
```
**Where is my bond1 in the bound_addresses?**

Netstat;
```
tcp6       0      0 ::1:9301                :::*                    LISTEN      30793/java       off (0.00/0/0)
tcp6       0      0 127.0.0.1:9301          :::*                    LISTEN      30793/java       off (0.00/0/0)
tcp6       0      0 ::1:9201                :::*                    LISTEN      30793/java       off (0.00/0/0)
tcp6       0      0 127.0.0.1:9201          :::*                    LISTEN      30793/java       off (0.00/0/0)
```

If I change my network.bind_host to only '_bond1:ipv4_' it all works perfectly;
```
publish_address {192.168.112.3:9301}, bound_addresses {192.168.112.3:9301}
```

Netstat;
```
tcp6       0      0 192.168.112.3:9301      :::*                    LISTEN      31194/java       off (0.00/0/0)
tcp6       0      0 192.168.112.3:9201      :::*                    LISTEN      31194/java       off (0.00/0/0
```

The Manual (https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html) spesifically states you can have multiple bind_host, and one publish_host (as we did in elasticsearch 1.7.3).

**Comment by dadoonet** [comment]
Fixed in 2.2.0 by #13954
