### ISSUE TITLE
Elasticsearch logging problems are unfriendly

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch#15430]
Our logging abstraction is weird.

We can override our default logging configuration by adding extra files in the configuration directory with a name starting with `logging.` and ending with `.yml`. 

So consider when I add the following extra logging configuration file, `logging.whoops.yml`:

```
logger.index.search.slowlog : WARN
logger.index.indexing.slowlog : WARN
```

Whoops, I just broke slow logging.  When a slow log entry is attempted to be logged I get the following unhelpful errors:

```
log4j:WARN No appenders could be found for logger (index.search.slowlog.query).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
log4j:WARN No appenders could be found for logger (index.search.slowlog.query).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

 For our handling of slow logs, the above lines don't really make sense, but it appears to trip users up, see #7461.  

It doesn't look like we do any syntax checking or warn when a user adds logging configuration that could break our abstraction.   Should we be doing that?

**Comment by ppf2** [comment]
Similar issue here (https://github.com/elastic/elasticsearch/issues/14953).  The "log4j:WARN No appenders could be found for logger" warnings can be improved.

**Comment by colings86** [comment]
Discussed in FixItFriday: We should fix this by adding validation in our code that picks up the logging file that only allows the file to be called 'logging.yml' (as in errors if there is an extra logging file) and also errors if the logging file is missing.

**Comment by joshuar** [comment]
@colings86 so we're taking away the functionality of overriding the base `logging.yml` with your own custom `logging.something.yml`?  That's a nice feature, almost equivalent to the `*.d` config directory used by many *nix applications.

**Comment by clintongormley** [comment]
Closing in favour of #16585
