### ISSUE TITLE
Allow build system to start a separate process for during integration testing

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#15439]
When doing integration testing for third party libraries, it is fairly common to have to deal with an external service/process/port which could be spawned during integration testing, _separately_ from ES.
This has the benefit of being more close to real world and it doesn't clash with the security manager for ES (giving it a more real feel).
It would be great to have this available in 2.x as well.

**Comment by costin** [comment]
relates #15192

**Comment by clintongormley** [comment]
@costin @rjernst has this issue been dealt with already?

**Comment by rjernst** [comment]
Yes, this was addressed when we added fixtures.
