### ISSUE TITLE
Allow a different bundlePlugin to be specified in integTest task

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#15440]
Currently, the `bundlePlugin` configuration for `integTest` is locked down and cannot be changed since, the [task](https://github.com/elastic/elasticsearch/blob/4e80a5e0994f25caa19c3e78573bdc9fa6bcc4c6/buildSrc/src/main/groovy/org/elasticsearch/gradle/plugin/PluginBuildPlugin.groovy#L40) relies on `project.afterEvaluate` which means whatever configuration is added, the plugin comes in last and overrides it.

This is not a common case however for plugins (like hdfs) which publish multiple artifacts (one for hadoop1, one for hadoop2), this would allow testing out all published zips not just the `bundlePlugin` which might not be representative.

**Comment by rmuir** [comment]
Do we really need multiple artifacts? I think we should just drop the hadoop1 support, for snapshot-restore, we really need synchronization, so people do not lose data.

**Comment by rjernst** [comment]
Even if we do have multiple artifacts, they should be separate plugins (ie gradle projects). This means each would have its own integration tests. But I agree we should simplify here and just do "hadoop2".

**Comment by clintongormley** [comment]
@costin I believe this is no longer needed?
