### ISSUE TITLE
Require rest tests to run via gradle

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#15459]
Some time ago, we added "real integration tests" that run in a separate phase of the build (mvn verify, gradle integTest) after the unit test phase. These tests work differently in that we setup and teardown external test fixtures before it runs: allows for real integration tests with a bin/elasticsearch, and use the rest test framework to perform actions and checks against that server.

In order to properly test many of our plugins and qa scenarios, we need the ability to have external test fixtures other than bin/elasticsearch. For example, testing repository-s3 should be using an external mock s3 server which responds to the s3 requests the plugin would make, so that the ES server can do a real s3 snapshot and restore.  But in order for this to work, we must shed the fantasyland requirement: rest integ tests will no longer work from the IDE, since they need this external process to be managed (which is done by gradle). Other examples could be hdfs minicluster, email server, http proxy server, ec2 service, ldap/directory service, etc.

This issue is to remove the hack that was added to make rest integ tests "work" from the IDE, in preparation for more external test fixtures beyond bin/elasticsearch.  Unit tests will continue to work from the IDE, and should definitely be improved for all of these plugins to use mocks. Rest integ tests will not be runnable from the IDE, but they should only be testing small parts (ie the integration of ES and s3), not that the code deep inside a plugin works at all.

See #15439 for the issue to add these external test fixtures.

**Comment by rjernst** [comment]
Note that for debugging purposes, with gradle we have "gradle run --debug-jvm" which allows you to attach an external debugger.

**Comment by nik9000** [comment]
> `gradle run --debug-jvm`

You can run REST tests with `--debug-jvm` too. Its pretty classy.

**Comment by rjernst** [comment]
@nik9000 indeed, that is what I meant to write!

**Comment by rjernst** [comment]
`gradle integTest --debug-jvm`

**Comment by nik9000** [comment]
You can just stick --debug-jvm on the end of the reproduction lines and it'll pause the jvm that you need to debug. Which is better than it did in maven-times iirc.

**Comment by jpountz** [comment]
+1
