### ISSUE TITLE
`--debug-jvm` should wait forever

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#15460]
Right now gradle takes a long time to start and I typically alt-tab away rather than stare intently at the screen for 30 seconds while everything gets ready. Then I get distracted and do email or something. Anyway, I typically come back to gradle having given up waiting for me, terminated the build, and left a JVM sitting around. It should just wait forever.

**Comment by nik9000** [comment]
If we're going to do #15459 this would really make life easier.

**Comment by clintongormley** [comment]
@nik9000 can this be closed now?

**Comment by nik9000** [comment]
I mean, we aren't doing it and it would be good to do it.

**Comment by dakrone** [comment]
@nik9000 doing `gradle run --debug-jvm` waits forever`*` currently, so I'm going to close this.

`*`: I did not actually wait for "forever" to test this manually.
