### ISSUE TITLE
Update scripting documentation to provide examples using true/false vs. on/off

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#15469]
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_setting_changes.html#migration-script-settings

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html#enable-dynamic-scripting

```
script.inline: on
script.indexed: on
```

It may be nicer to provide examples using true/false vs. on/off for the new script options to be consistent with the other boolean settings that we have.

**Comment by clintongormley** [comment]
@ppf2 It is not a boolean setting, it is a ternary: `on`, `off`, `sandbox`.  See https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html#enable-dynamic-scripting

That said, we no longer have any sandboxed scripting engines.  Wondering if we should change this to boolean?

**Comment by rmuir** [comment]
I would love it if we defaulted to 'off', and 'on' acted like 'sandbox'.

**Comment by clintongormley** [comment]
Discussed in FixItFriday:  switch to `true` / `false`, where `true` means sandbox if there is one.
