### ISSUE TITLE
rename minimum_master_nodes

### ISSUE THREAD

**Issue by djschny** [elastic/elasticsearch#15463]
Currently when explaining and talking about `minimum_master_nodes` setting, we always clarify that it is really minimum number of __eligible__ master nodes. In the spirit of self-documenting settings, this is a suggestion to rename the setting to `minimum_eligible_master_nodes` and deprecate the current setting name.

**Comment by dakrone** [comment]
perhaps `minimum_electable_nodes` would be a consideration also?

**Comment by ywelsch** [comment]
I think this should go hand in hand with renaming the setting `node.master` to `node.master_eligible`. Also the `zen` prefix should be removed from `discovery.zen.minimum_master_nodes`.

**Comment by markharwood** [comment]
Also the comments in the elasticsearch.yml talks about "nodes" not "master-eligible nodes"

    # Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):

**Comment by jasontedor** [comment]
I discussed this in person with a few people. My thoughts are that we should *not* make any changes here. Yes, the name could be better but the reason is because we lose search engine history if we change the name. This is an *extremely* important setting with a long history and if the name is changed than the past literature on the setting will not appear in searches. For a setting like this, I think that is far more valuable than a semantically perfect name.

**Comment by djschny** [comment]
That's a good point that I had not thought of. Based upon that how about a hybrid approach?
* update comments in the default 
* instead of renaming and making it a breaking change, accept both properties
* update `elasticsearch.yml`to have the new property name in by default
* on the document page, make sure the old value stays on the page so that google search history is maintained

Just brainstorming ways to have the cake and eat it too.

**Comment by jasontedor** [comment]
> Based upon that how about a hybrid approach?

I'm afraid that it still has the risk of fracturing the knowledge base. People have to be aware to search for both settings, and if you only search for the new setting that you don't see the accumulated knowledge for the old setting.

> instead of renaming and making it a breaking change, accept both properties

Unfortunately I think this has the potential to cause more harm then good. What if both settings are present, and the value is different? Well, of course we should probably throw an exception, but why are we are adding all this extra code?

> Just brainstorming ways to have the cake and eat it too.

I admire the effort, but the fractured knowledge base concerns me, and I've seen too many times when trouble arises when we try to support more than one way to do thing. See #17124 for a recent example.
