### ISSUE TITLE
integration tests doc example out of date

### ISSUE THREAD

**Issue by martin-a** [elastic/elasticsearch#15466]
[Documentation about changing node settings](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/integration-tests.html#changing-node-settings) in integration tests need some update.
the `settingsBuilder()` method is not accessible from ESIntegTestCase child classes.

Here is a workaround to add some custom node settings that work with 2.1 sourcecode
```
public class Mytests extends ESIntegTestCase {
  @Override
  protected Settings nodeSettings(int nodeOrdinal) {
      return Settings.settingsBuilder().put(super.nodeSettings(nodeOrdinal))
             .put("node.mode", "network")
             .build();
  }

}
```

**Comment by martin-a** [comment]
Note: above workaround does not seems to work. Could not find any way to change node settings in integration tests ...

**Comment by clintongormley** [comment]
@rjernst could you take a look at this please?

**Comment by rjernst** [comment]
I pushed a fix, the docs were assuming `Settings.setttingsBuilder` was statically imported. We should also really just get rid of `settingsBuilder()`, as it is the exact same as `builder()`...

Master: 2093ea5
2.x: f545b6d
2.1: c9d765f
2.0: 1c094d3
