### ISSUE TITLE
shingle filter apparently requires a declared tokenizer, but probably shouldn't

### ISSUE THREAD

**Issue by willf** [elastic/elasticsearch#15490]
The following should, I think, produce equivalent results, since the `standard` tokenizer is the default. But they do not:

```
GET _analyze
{
  "text": "i like search",
  "filters" : ["shingle"]
}
GET _analyze
{
  "text": "i like search",
  "tokenizer": "standard",
   "filters" : ["shingle"]
}
```
The second call does the right thing, but the first only produces 'shingles' of length 1.

**Comment by clintongormley** [comment]
The default behaviour is to use the default analyzer, if no tokenizer is specified, so in your first example, the `filters` are just being ignored.

@johtani Perhaps we can throw an exception if `filter`/`char_filter` is specified without `tokenizer`?
