### ISSUE TITLE
Error message failure when analyzer created without tokenizer

### ISSUE THREAD

**Issue by willf** [elastic/elasticsearch#15492]
```
POST /analyzertest
{
  "settings": {
    "analysis": {
      "analyzer": {
        "my_analyzer": {
          "filter": ["lowercase","stop", "shingl"],
          "char_filter": ["html_strip"]
        }
      }
    }
  }
}
```

Returns error:
```
{
   "error": {
      "root_cause": [
         {
            "type": "index_creation_exception",
            "reason": "failed to create index"
         }
      ],
      "type": "illegal_argument_exception",
      "reason": "Analyzer [my_analyzer] must have a type associated with it"
   },
   "status": 400
}
```
reason should probably be: "Analyzer [my_analyzer] must have a declared tokenizer associated with it"

**Comment by clintongormley** [comment]
Analyzers are configurable, so you can specify a `type` and a number of parameters to configure that base analyzer.  Alternatively, if you specify a `tokenizer`, then `type` defaults to `custom`.  Perhaps we could change the error to `... must specify either an analyzer type, or a tokenizer`
