### ISSUE TITLE
Fix cyclic dependency issues

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#15504]
In certain places we inject the `Client` or `ScriptService` as a dependency to plugin services/components. There is a cyclic dependency issue when one of these classes is used in a plugin node service/component and this service/component is also used as a dependency in either a transport action or transport action filter. In this case were then unable to start the node and a big guice cyclic dependency error is printed.

The workaround is to provide `Client` or `ScriptService` via setter instead of constructor. This isn't ideal. I think there is just a mismatch on we think services/components depend on each other and how things are really wired up together with Guice. Specially the only Client in a node is `NodeClient` and that indirectly requires all services/components, but if another services is then having a dependency on `Client` things get tricky and it creates a dependency mess. I'm not sure how to fix this.

In certain cases the setter workaround doesn't suffice and in order to avoid cyclic dependencies a Guice `Provider` or directly using the Guice injector is used to fetch the `Client` or `ScriptService`. This is hack is just dirty and event worse then the setter workaround.

**Comment by rjernst** [comment]
@martijnvg Can you list out the cycle in initialization ordering?

**Comment by martijnvg** [comment]
@rjernst There are many cyclic dependency issues. Basically no transport action can't be constructed. 

Here is one problematic initialisation order when `Client` is added as constructor parameter to `Ingestbootstrapzper ` in the ingest plugin:
  * IngestBootstrapper
  * Client
  * NodeClient
  * java.util.Map\<org.elasticsearch.action.GenericAction, org.elasticsearch.action.support.TransportAction\>
  * TransportAction 
  * TransportOpenIndexAction
  * MetaDataIndexStateService
  * AllocationService
  * AllocationDeciders
  * AllocationDecider
  * InternalClusterInfoService
  * DiskThresholdDecider
  * ClusterInfoService
  * ActionFilters
  * TransportNodesStatsAction
  * ActionFilter
  * IngestActionFilter
  * IngestBootstrapper

Other problematic initialisation orderings are similar. If `ScriptService` is added as constructor parameter then the only difference is that between the first and second component initialisation is `ScriptsService` since that relies on `Client` too.

What currently is done in ingest and other plugins as workaround is to supply `Client` and `ScriptsService ` lazily via a setter or use Guice's `Provider` mechanism.

**Comment by martijnvg** [comment]
Update: If `ScriptService` is used as a dependency, it no longer causes cyclic dependency issues, because it no longer depends on `Client` since indexed scripts have been replaced with stored scripts.

**Comment by javanna** [comment]
I think this has been recently solved in master. Can we close it already or is there work left to do?

**Comment by nik9000** [comment]
I think we'll get to this as we de-guice the code base and work on the plugin interface. I think it is safe to close this because of that. So I'm closing it.

We've broken one of the larger cycles lately by making `NodeClient` not depend on the actions, instead they are set on it after it is constructed. We did that because guice was unable to do whatever synthetic magic it does to break the dependency in some case so we *had* to to move forward.
