### ISSUE TITLE
Searching range not work, why?

### ISSUE THREAD

**Issue by 117111302** [elastic/elasticsearch#15502]
I can't query data by date range after I upgrade ES version from 1.7 to 2.1.
Searching range json: {"range":{"CreateTime":{"gt":"2015-12-17 00:21:20","lte":"2015-12-17 12:21:10"}}.
It seems range is not work and the data exist in the range.

Thank you!

**Comment by jpountz** [comment]
How is your `CreateTime` field mapped? I suspect it doesn't work because it got indexed as a string instead of a date?

**Comment by 117111302** [comment]
Yep! I forgot field mapping. It's my mistake. Thank you very much for your help!
Close it!
