### ISSUE TITLE
close inactive index in certain times and become active again when there is operation on it.

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#15505]
config:
index.close.after_time_inactive: 30m

action:
when an index is inactive for 30m, then close it and reclam its occupied memory for active index to use.
when there is a operation on it later, open it first and then operate it.

**Comment by makeyang** [comment]
any update?

**Comment by eskibars** [comment]
Hey @makeyang, I'm sorry for this having sat for so long with no real interaction with you.  We were discussing it today as a team and I feel there's a possibility it's related to some ongoing work we've been doing, but I don't want to presume so much about your use case.  I realize it's been a while, but curious if you're still around and if we could hear more about what you're thinking of in terms of operations here.  For example, for your use case are you concerned mostly with search or also with indexing operations?  Are there other operations that you're also considering?  And are you sensitive to performance of the close/open index rotation?

**Comment by jasontedor** [comment]
No additional feedback, closing.

**Comment by makeyang** [comment]
sorry for the delay due to some personal reason.
question:your use case are you concerned mostly with search or also with indexing operations
answer: my use case is rolling log with heavy write, and search is mainly for current log event. so close inactive index is trying to release memory to reduce memory pressure then make indexing performance better.
question:Are there other operations that you're also considering? 
answer:
1) make only 1 shard without replica for index for being writing(we use time rolling way)
2) close auto rebalance during peek time
3) move clod data into some sata disk machine with large capacity and leave ssd disk for hot index and etc
question:And are you sensitive to performance of the close/open index rotation?
answer: very much. so we create index ahead at off peak time and then close index auto rebalance
question:And are you sensitive to the search performance on such indices? 
answer: since it is log use case, so search latency is second level and mostly for very recently. And most urgent search traffic is not very high since it is only visited when exceptions happen. other regular search and statistic query will be left to off peak time.
question:Would it be acceptable if when these indices are searched, the performance is degraded.
 answer: yes, from 1 seconds to 5/6 seconds is acceptable
