### ISSUE TITLE
Mutliple nested types in the same query

### ISSUE THREAD

**Issue by lengoyvaerts** [elastic/elasticsearch#15503]
Hi

I have a question to which I can't seem to find an answer anywhere. 

Let's say I have an Index type with a mapping that contains two or more nested types (parallel, not deeply nested). 

<pre>
...
"field1": {  
  "type": "nested", 
  "properties": {
    "subfield1": { "type": "string" },
    "subfield2": { "type": "integer" }
  }
},
"field2": {  
  "type": "nested", 
  "properties": {
    "subfield1": { "type": "string" },
    "subfield2": { "type": "integer" }
  }
}				  
...
</pre>

Is it possible to use those two fields in the same query?

**Comment by jpountz** [comment]
It depends how you want to query these fields, can you be more specific about what you are trying to do?

Also we try to use this bug tracker for confirmed bugs and features requests, please ask such questions as http://discuss.elastic.co instead.
