### ISSUE TITLE
post_filer and script_file

### ISSUE THREAD

**Issue by coldlamper** [elastic/elasticsearch#15517]
Using this syntax:
```
"post_filter": { 
	"script": {
		"lang": "groovy",
		"file": "min_distance_comparison",
		"params": {
			"lat": 29.201168,
			"lon": -81.037071
		}
	}
}
```
throws [script] query does not support [file]

Replacing 'file' with 'script_file' works but the docs say to use 'file'
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_scripting_changes.html

**Comment by jpountz** [comment]
@coldlamper I think you are missing one level of script and it should be (not tested):

```
"post_filter": { 
    "script": {
        "script": {
            "lang": "groovy",
            "file": "min_distance_comparison",
            "params": {
                "lat": 29.201168,
                "lon": -81.037071
            }
        }
    }
}
```

The outer `script` object tells elasticsearch to use the `script` query while the inner `script` object gives the script definition. See https://www.elastic.co/guide/en/elasticsearch/reference/2.1/query-dsl-script-query.html
