### ISSUE TITLE
Elasticsearch tests use deprecated API when being very slow

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#15515]
```
16:58:57.609 java[45366:25547260] 16:58:57.609 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
```

Really this is not acceptable, what's the justification for calling such an API here. This spams my console, it's almost like guice going down hard in loops causing out of disk errors. Who is responsible for calling such an API. We have to be more carful here really :8ball:

**Comment by rmuir** [comment]
What is your version of java? Maybe its not the latest? If the latest java still reports this, we should open a bug at openjdk!

**Comment by s1monw** [comment]
```
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```

**Comment by rmuir** [comment]
What is your mac os? Maybe it only happens on El Capitan? 

Personally I am not running this one, because I am not ready to do battle with my operating system about who should or should not be `root` (short answer: me not them). It nags me to upgrade almost every day and i am waiting for my older version to really annoy me before considering any upgrade, as usual.

**Comment by s1monw** [comment]
@jasontedor runs it on el captoROOTio and it apparently works fine :bomb:

**Comment by jasontedor** [comment]
This is an OpenJDK issue binding against API calls that were deprecated in El Capitan; it looks like there is a fix slated for Java 9.

**Comment by clintongormley** [comment]
Is there anything for us to do here?

**Comment by s1monw** [comment]
closing as won't fix
