### ISSUE TITLE
In elasticsearch , How to modify mapping, and  influence the existing data.

### ISSUE THREAD

**Issue by rfyiamcool** [elastic/elasticsearch#15524]
Now,  I say the method I use now.

1. delete elasticsearch' type , then delete all data
2. put  my mapping, this mapping config is my own definition.
3. push data again .

Can you better idea?  or  elasticsearch  support dynamic to modify mapping and existing data online?

Waiting for your answer.  Thanks You  !

**Comment by dadoonet** [comment]
Please join us on discuss.elastic.co.

We can help you there.

Not an issue. Closing.
