### ISSUE TITLE
/etc/init.d/elasticsearch stop sleeps for 86400 seconds

### ISSUE THREAD

**Issue by paulv-dell** [elastic/elasticsearch#15520]
elasticsearch wasn't restarting correctly. I investigated and found:

    # ps auxwwwf
    [...]
    root      3034  0.0  0.0 106364  1652 pts/4    S+   11:43   0:00      \_ /bin/sh /etc/init.d/elasticsearch stop
    root      3049  0.0  0.0 100908   568 pts/4    S+   11:43   0:00          \_ sleep 86400

Line 129 of /etc/init.d/elasticsearch appears to be the culprit.

This machine is running RHEL 6.4.

**Comment by jasontedor** [comment]
This is intentional so that shards can be closed; see #10680 for details and #11248 is the pull request that ultimately closed that issue.

**Comment by satoshi-kimura** [comment]
I think so elasticsearch have to confirm os version.
Because elasticsearch can not restart on RHEL6.x , it sleep 86400 in stop.
RHEL7.x is no probrem.
