### ISSUE TITLE
doc() array size error

### ISSUE THREAD

**Issue by YunchaoGongSC** [elastic/elasticsearch#15525]
Hello

I tried to index an double array {1, 2, 3, 4, 5} and let ES automatically detect the type. Then I wrote a plugin to get the value as follows

ScriptDocValues docHashValues = (ScriptDocValues) doc().get("array");
final List<Double> tmp = ((ScriptDocValues.Doubles) docHashValues).getValues();

However I found the tmp size is always <= 4. Is this a bug or there are some limitations for array size in ES? Thanks!

**Comment by YunchaoGongSC** [comment]
The data is indexed as 

int[] tmp = {1, 3, 5, 7, 5};
XContentBuilder doc = XContentFactory.jsonBuilder().startObject()
                   .field("feature", tmp)
.endObject();

And in head, checking the content, I do find 1 3 5 7 5. But in the code, I can only get first 4 values.

**Comment by YunchaoGongSC** [comment]
To be more specific, I found in the source() method, it did contain the right number of values in each array, but in doc(), it only contains <= 4 values.

**Comment by jpountz** [comment]
This is expected if your field does not have doc values enabled as fielddata does not retain duplicates. To fix this problem you would have to reindex your data in an index that has doc values enabled on this field (default on and after 2.0).
