### ISSUE TITLE
install head plugin error

### ISSUE THREAD

**Issue by kys1230** [elastic/elasticsearch#15523]
[root@localhost bin]# ./plugin -install mobz/elasticsearch-head -v
-> Installing mobz/elasticsearch-head...
Trying https://github.com/mobz/elasticsearch-head/archive/master.zip...
Failed: SSLException[java.security.ProviderException: java.security.KeyException]; nested: ProviderException[java.security.KeyException]; nested: KeyException; 
Failed to install mobz/elasticsearch-head, reason: failed to download out of all possible locations..., use --verbose to get detailed information

**Comment by eskibars** [comment]
I recommend you open this up for discussion over at https://discuss.elastic.co/ .  I just successfully tested installing the head plugin myself and I suspect you have an issue specific to your system.  I'm going to close this here, but if a discussion there reveals a real bug, feel free to open an issue back here.
