### ISSUE TITLE
minimum_should_match ignored when number of `should` clauses smaller 

### ISSUE THREAD

**Issue by navneet-lyra** [elastic/elasticsearch#15521]
For programmatically-generated queries, you sometimes want to apply min-match constraints on your bool should clauses. Is there thinking behind why minimum_should_match is ignored when the number of should clauses is lesser than it?

To be clear, I'm looking for the behavior where the following query returns 0 results:
```
{
	"query": {
		"bool": {
			"should": [{
				"match": {
					"_all": "elizabeth"
				}
			}, {
				"match": {
					"_all": "smith"
				}
			}],
			"minimum_should_match": 3
		}
	}
}
```

We're using a query-understanding pipeline which should get 0 results from one of the programmatically generated queries if there isn't enough support in the query to make the match. However, that is not currently happening right now.

Any way I can resolve this in the current set up? Or would this be a feature/bug request?

**Comment by jpountz** [comment]
I agree this is a bug and this query should return no hits. The issue seems to stem from Queries.calculateMinShouldMatch which returns the number of optional clauses in case minimum_should_match gets higher.
