### ISSUE TITLE
Sharing the searched log with a person outside organization

### ISSUE THREAD

**Issue by prraina1** [elastic/elasticsearch#15528]
What facility elastic gives if we need to share a section of log(or a searched log) to a person who does not have any of elastic product or does not have access to it?

A common usecase - sharing the log with a product support team for a PMR.

I did some thought over this on how to enable this, but would like to hear if there is an inbuilt/available way to do this.

**Comment by clintongormley** [comment]
I don't know if you are referring to the application logs from elasticsearch, or log documents indexed in elasticsearch.  If the latter, then maybe you want to use Kibana for this.  Application logs are just text files, so share them as you would any other text files.
