### ISSUE TITLE
what's the meaning for 'pretty' in {curl -XPUT 'localhost:9200/customer/external/2?pretty' -d ' {   "name": "Jane Doe" }'}

### ISSUE THREAD

**Issue by selfchanger** [elastic/elasticsearch#15531]
hi,I am learning elasticsearch,i don't understand what's the meaning for 'pretty',can someone tell me?thanks,the curl cmd is :
curl -XPUT 'localhost:9200/customer/external/2?pretty' -d ' {   "name": "Jane Doe" }'

**Comment by dadoonet** [comment]
Please ask your questions on discuss.elastic.co.

And read https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#_pretty_results?q=pretty

**Comment by selfchanger** [comment]
I am sorry,i am new,thank you very much
