### ISSUE TITLE
Provide item-based listener API in BulkProcessor

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#15530]
This ticket originates from a discussion in #14829. Currently, `BulkProcessor` provides a bulk-based listener API. A listener gets notified before a bulk request is issued and after a response came back. But clients should not need to care about the internal handling of bulk requests and can just work on individual items. Hence we want to introduce a new listener interface `ItemListener` sketched below:

``` java
interface ItemListener {
    void beforeExecute(ActionRequest request);
    void afterExecute(ActionRequest request, ActionWriteResponse response);
    void afterExecute(ActionRequest request, Throwable failure);
}
```

This interface is simpler: There is no need to know about bulk requests and how bulk processor handles them internally. Also request / response correlation is straightforward (the current API uses an execution id for that). Consequently, in case a bulk request fails completely, the callback method will be invoked for each `ActionRequest`.

Bulk-based listeners are considered to be the exception rather than the rule. Bulk-based listening will still be supported but the idea is to subclass `BulkProcessor` and implement the callback methods in a subclass (i.e. the base class `BulkProcessor` should implement a template method).

**Comment by martijnvg** [comment]
Closing since no progress has been made and no further requests for changing this have been made for a long time.
