### ISSUE TITLE
Having a type and a field in a different type with the same name seems to break analyzers

### ISSUE THREAD

**Issue by tarnacious** [elastic/elasticsearch#15540]
In tracking down a bug in an application, I found this behaviour in elasticsearch which is not what I would expect. 

It seems that adding a new mapping type somehow breaks the analyzers in another type. I see the behaviour in elasticsearch 1.4.4 which we are using and in 1.7.4.

Here is a script to to reproduce the behaviour:

    ELASTICSEARCH=localhost:9200
    INDEX=text-index

    # Clear the index
    curl -XDELETE $ELASTICSEARCH/$INDEX/
    echo 

    # Create and index
    curl -XPUT -H "Content-Type: json" $ELASTICSEARCH/$INDEX/ -d '
        {
            "settings": {
                "index": {
                    "number_of_shards": 1,
                    "analysis": {
                        "filter": {
                            "stemmer": {
                                "type": "snowball",
                                "language": "English"
                            }
                        },
                        "analyzer": {
                            "custom": {
                                "type": "custom",
                                "tokenizer": "standard",
                                "filter": "stemmer"
                            }
                        }
                    },
                    "number_of_replicas": 0
                }
            },
            "mappings": {
                "user": {
                    "dynamic": "strict",
                    "properties": {
                        "address": {
                            "properties": {
                                "description": {
                                    "type": "string",
                                    "analyzer": "custom",
                                    "store": "yes"
                                }
                            }
                        }
                    }
                }

            }
        }
    }'
    echo 

    # Index a document
    curl -XPOST -H "Content-Type: json" $ELASTICSEARCH/$INDEX/user -d '
        {
            "address": 
                {
                    "description": "Walked"
                }
            
        }'
    echo 

    sleep 1
    # Search, should find something
    curl -XPOST -H "Content-Type: json" $ELASTICSEARCH/$INDEX/user/_search -d '
    {
        "query": {
            "filtered": {
                "query": {
                    "simple_query_string": {
                        "default_operator": "AND",
                        "fields": [
                            "user.address.description"
                        ],
                        "query": "Walk"
                    }
                }
            }
        }
    }'
    echo 

    # Add a mapping called address, which happens to be the name of field a nested datatype
    curl -XPUT -H "Content-Type: json" $ELASTICSEARCH/$INDEX/_mapping/address -d '
    { 

        "dynamic": "strict"
    }'
    echo

    sleep 1
    # Search, now returns no results!
    curl -XPOST -H "Content-Type: json" $ELASTICSEARCH/$INDEX/user/_search -d '
    {
        "query": {
            "filtered": {
                "query": {
                    "simple_query_string": {
                        "default_operator": "AND",
                        "fields": [
                            "user.address.description"
                        ],
                        "query": "Walk"
                    }
                }
            }
        }
    }'
    echo

Which produces this:

    {"acknowledged":true}
    {"acknowledged":true}
    {"_index":"text-index","_type":"user","_id":"AVG0hasF-Z9PaJz0rP2W","_version":1,"created":true}
    {"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":1,"max_score":0.30685282,"hits":[{"_index":"text-index","_type":"user","_id":"AVG0hasF-Z9PaJz0rP2W","_score":0.30685282,"_source":
        {
            "address": 
                {
                    "description": "Walked"
                }
            
        }}]}}
    {"acknowledged":true}
    {"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}

I would expect the last search request to return the same results as the first one:

    {"acknowledged":true}
    {"acknowledged":true}
    {"_index":"text-index","_type":"user","_id":"AVG0hasF-Z9PaJz0rP2W","_version":1,"created":true}
    {"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":1,"max_score":0.30685282,"hits":[{"_index":"text-index","_type":"user","_id":"AVG0hasF-Z9PaJz0rP2W","_score":0.30685282,"_source":
        {
            "address": 
                {
                    "description": "Walked"
                }
            
        }}]}}
    {"acknowledged":true}
    {"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":1,"max_score":0.30685282,"hits":[{"_index":"text-index","_type":"user","_id":"AVG0hasF-Z9PaJz0rP2W","_score":0.30685282,"_source":
        {
            "address": 
                {
                    "description": "Walked"
                }
            
        }}]}}

I guess I can work around this by renaming some things, but I would like to know if I am doing something wrong in my script or if this is something that is a bit broken in elasticsearch.

Thanks

**Comment by dadoonet** [comment]
I think you are talking about this: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_conflicting_field_mappings

Which won't be possible anymore in 2.0.

**Comment by tarnacious** [comment]
That certainly looks related, thanks for the link. It's not exactly that same as this is a conflict between a type and a field with the same name, but hopefully 2.0 also won't start on this condition and until we start using 2.0 I'll just be more careful about naming conflicts.

Thanks for looking into my issue!

**Comment by dadoonet** [comment]
Ok thanks. I guess we can close your issue right? If not, feel free to reopen.
