### ISSUE TITLE
HTML Strip Char Filter documentation

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#15543]
There are at least two configuration examples of using the HTML Strip Char Filter (char filter type `html_strip`) found in Elasticsearch documentation.
- [Analysis >> Analyzers >> Custom Analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-custom-analyzer.html)
- [Analysis >> Token Filters >> Lowercase Token Filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-lowercase-tokenfilter.html)

```
char_filter :
    my_html :
        type : html_strip
        escaped_tags : [xxx, yyy]
        read_ahead : 1024
```

[HTML Strip Char Filter documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-htmlstrip-charfilter.html) should indicate what `escaped_tags` and `read_ahead` parameters do. According to `org.apache.lucene.analysis.charfilter.HTMLStripCharFilter` documentation:

> escapedTags - Tags in this set (both start and end tags) will not be filtered out.

For example, `escaped_tags` could be configured to ignore `a` and `title` tags:

```
escaped_tags : [a, title]
```

Incidentally, I am not seeing any support for the `read_ahead` parameter. How does it work?

**Comment by npthl2** [comment]
[commit 16cd159](https://github.com/elastic/elasticsearch/commit/16cd159a381979e9d92288d6c9bada8483fea520)
(look at 8th file)

according to this, I think it is just buffer size, and it removed in quite long before.

**Comment by romseygeek** [comment]
The HTMLStripCharFilter now only has a single parameter, `escaped_tags`, and this is now documented.
