### ISSUE TITLE
Restrict index names to ASCII

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#15553]
Index names are currently used as folder names to store data. On some systems this can lead to issues when index names contain characters outside the ASCII range. We currently already forbid special characters in index names such as '\\', '/', '*', '?', '"', '<', '>', '|', ' ', ','.

Relates to #15552

**Comment by jpountz** [comment]
+1

**Comment by nik9000** [comment]
> Index names are currently used as folder names to store data.

I'd be just as happy to break that relationship.

**Comment by jpountz** [comment]
Relates to #9059 as well.

**Comment by nik9000** [comment]
> I'd be just as happy to break that relationship.

Actually the more I think about the more I'd prefer to break that relationship. I'd like us to be able to atomically rename an index and leave behind an alias pointing to the new index one day. And that'd require breaking the relationship between index name and directory name.

**Comment by ywelsch** [comment]
@nik9000 I'm very much in favour of breaking that relationship as well (Index UUIDs play a key role in this). I added the discussion label as we should probably come up with a plan when and how to tackle this and related issues (e.g. #13265 , #14932). I also wonder whether we should strive for a short term solution (restrict index names) and, at the same time, start thinking about more concrete plans for changing the representation on disk.

**Comment by clintongormley** [comment]
Closing in favour of #16442
