### ISSUE TITLE
failed to run inline script | No such property: for class

### ISSUE THREAD

**Issue by oktarahadian** [elastic/elasticsearch#15554]
I'm trying to use function_score->script_score and calculate with doc value i got error
<pre class="source">
curl -XGET "localhost:9200/my_ipod/song_properties/_search?pretty=true&size=3" -d'
{
  "query": {
    "function_score": {
      "query": {"simple_query_string": 
            {
                "query": "dewa satu"
            }
        },
      "script_score": {
        "script": "_score * doc['score_boost']"
      }
    }
  }
}'

{
  "error" : {
    "root_cause" : [ {
      "type" : "groovy_script_execution_exception",
      "reason" : "failed to run inline script [_score * doc[score_boost]] using lang [groovy]"
    } ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [ {
      "shard" : 0,
      "index" : "my_ipod",
      "node" : "BFIXhyPyR46cyzRES7E0Dw",
      "reason" : {
        "type" : "groovy_script_execution_exception",
        "reason" : "failed to run inline script [_score * doc[score_boost]] using lang [groovy]",
        "caused_by" : {
          "type" : "missing_property_exception",
          "reason" : "No such property: score_boost for class: 383d17d583550b6f5b92342d7059da6add45f3aa"
        }
      }
    } ]
  },
  "status" : 400
}

</pre>

But if i change doc['score_boost'] to 1 it work, ip pretty sure if 'score_boost' is there and all doc have that value. bellow is sample result of my doc type item
<pre class="source">
curl -XGET "localhost:9200/my_ipod/song_properties/_search?pretty=true&size=3" -d '{
  "query": {
    "function_score": {
      "query": {"simple_query_string": 
            {
                "query": "dewa satu"
            }
        },
      "script_score": {
        "script": "_score * 1"
      }
    }
  }
}
</pre>
result is fine
<pre class="source">
{
  "took" : 310,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1124,
    "max_score" : 25.883312,
    "hits" : [ {
      "_index" : "my_ipod",
      "_type" : "song_properties",
      "_id" : "100000086",
      "_score" : 25.883312,
      "_source":{"doc": {"artist_name": "Dewa 19", "song_name_origin": "Satu Sisi", "album_name": "Pandawa Lima", "artist_name_origin": "Dewa 19", "song_id": "100000086", "album_name_origin": "Pandawa Lima", "genre_name": "Rock", "song_name": "Satu Sisi", "score_boost": 1.002098104639327}}
    }, {
      "_index" : "my_ipod",
      "_type" : "song_properties",
      "_id" : "100000116",
      "_score" : 25.883312,
      "_source":{"doc": {"artist_name": "Dewa", "song_name_origin": "Satu", "album_name": "Laskar Cinta", "artist_name_origin": "Dewa", "song_id": "100000116", "album_name_origin": "Laskar Cinta", "genre_name": "Rock", "song_name": "Satu", "score_boost": 1.0129150221711472}}
    }, {
      "_index" : "my_ipod",
      "_type" : "song_properties",
      "_id" : "100000066",
      "_score" : 25.718107,
      "_source":{"doc": {"artist_name": "Dewa 19", "song_name_origin": "Satu Hati", "album_name": "Terbaik - Terbaik", "artist_name_origin": "Dewa 19", "song_id": "100000066", "album_name_origin": "Terbaik - Terbaik", "genre_name": "Rock", "song_name": "Satu Hati", "score_boost": 1.004947400036952}}
    } ]
  }
}
</pre>

and i try to enable all setting about scripting it does't work too :( pls help

<pre class="source">
script.inline: on
script.indexed: on
script.engine.groovy.inline.aggs: on
script.engine.groovy.inline.mapping: on
script.engine.groovy.inline.search: on
script.engine.groovy.inline.update: on
script.engine.groovy.inline.plugin: on
</pre>

**Comment by oktarahadian** [comment]
http://stackoverflow.com/questions/28551634/elasticsearch-sort-error-using-script

I think this issue with escaping in shell, by changing to doc['"'"'score_boost'"'"'].value, not error but still, not calculate score correction (all score is 0)

<pre class="code">
curl -XGET "localhost:9200/my_ipod/song_properties/_search?pretty=true&size=3" -d'
{
  "query": {
    "function_score": {
      "query": {"simple_query_string":
            {
                "query": "dewa satu"
            }
        },
      "script_score": {
        "script": {
            "lang": "groovy",
            "inline": "_score * doc['"'"'score_boost'"'"'].value"
            }

        }
    }
  }
}'
{
  "took" : 365,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1124,
    "max_score" : 0.0,
    "hits" : [ {
      "_index" : "langitmusik",
      "_type" : "song_properties",
      "_id" : "110004712",
      "_score" : 0.0,
      "_source":{"doc": {"song_name_origin": "Lelaki Yang Kumau (Jazz Up Your Life)", "artist_name": "Ratu", "album_name": "No. Satu", "score_boost": 1.0004258090311626, "song_name": "Lelaki Yang Kumau (Jazz Up Your Life)", "album_name_origin": "No. Satu", "genre_name": "Pop", "song_id": "110004712", "artist_name_origin": "Ratu"}}
    }, {
      "_index" : "langitmusik",
      "_type" : "song_properties",
      "_id" : "110004717",
      "_score" : 0.0,
      "_source":{"doc": {"song_name_origin": "Teman Tapi Mesra", "artist_name": "Ratu", "album_name": "No. Satu", "score_boost": 1.001438722822439, "song_name": "Teman Tapi Mesra", "album_name_origin": "No. Satu", "genre_name": "Pop", "song_id": "110004717", "artist_name_origin": "Ratu"}}
    }, {
      "_index" : "langitmusik",
      "_type" : "song_properties",
      "_id" : "110004827",
      "_score" : 0.0,
      "_source":{"doc": {"song_name_origin": "Hanya Satu", "artist_name": "Shitta Devi", "album_name": "Berikan Dia Cinta", "score_boost": 1, "song_name": "Hanya Satu", "album_name_origin": "Berikan Dia Cinta", "genre_name": "Pop", "song_id": "110004827", "artist_name_origin": "Shitta Devi"}}
    } ]
  }
}

</pre>

**Comment by clintongormley** [comment]
Hi @oktarahadian 

This sounds like a question for the forums http://discuss.elastic.co/ rather than a bug report.
