### ISSUE TITLE
"simple_query_string" vs. "query_string" field analysis

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch#15550]
Recently we discovered that, since we aren't sanitizing search terms as they come into our system, we would get occasional parsing exceptions in ES when special characters such as / (forward slash) , etc. were used w/ "query_string".  So, we decided to switch to "simple_query_string".  However, we discovered that the same analyzers are not being used for each.  I reviewed "When Analyzers Are Used" (https://www.elastic.co/guide/en/elasticsearch/guide/current/analysis-intro.html?q=analy#_when_analyzers_are_used) to see if it indicated there would be a difference between simple and regular query string but it did not, so I'm wondering if this is a bug.  For example:

`"query_string": {
   "query": "sales",
   "fields": [
      "title"
   ]
}`

will use the analyzer for the "title" field which is the en_analyzer and properly stem "sales" to "sale" and find the matching documents.  Simply changing "query_string" to "simple_query_string" will not.  We have to search for "sale" or add an analyzer to the query, like so:

`"simple_query_string": {
   "query": "sales",
   "fields": [
      "title"
   ],
   "analyzer": "en_analyzer"
}`

Of course, not all our fields are analyzed the same way and the default behavior described in the documentation reference above makes perfect sense.  Is this a bug or does "simple_query_string" not behave the same way w/ respect to field analysis during query?  We are using ES 1.7.2.

**Comment by tdoman** [comment]
Sorry, forgot to include our definition for "en_analyzer":
`"en_analyzer": {
   "type": "custom",
   "tokenizer": "icu_tokenizer",
   "filter": [
      "icu_normalizer",
      "en_stop_filter",
      "en_stem_filter",
      "icu_folding",
      "shingle_filter"
     ],
    "char_filter": [
       "html_strip"
     ]
}`

**Comment by dakrone** [comment]
So I looked into this, the way that the `SimpleQueryParser` from Lucene works is
that it takes a single `Analyzer` to analyze the terms.

I think from the ES side we might be able to expand a `SimpleQueryParser` parser
into multiple queries (passing a different analyzer for each field) that can be
combined into a single boolean query. It does sound like it would be worthwhile
however, instead of tying the query to a single analyzer.

**Comment by rmuir** [comment]
> So I looked into this, the way that the SimpleQueryParser from Lucene works is
> that it takes a single Analyzer to analyze the terms.

Because no method should ever take anything else: if you want per-field behavior, pass e.g. PerFieldAnalyzerWrapper! It is really just that simple

**Comment by dakrone** [comment]
> if you want per-field behavior, pass e.g. PerFieldAnalyzerWrapper! It is
> really just that simple

That's great, thanks for the pointer @rmuir!

**Comment by tdoman** [comment]
Thanks guys, I just read issue #15634, we need that also.  Which versions of ES might we be able to get a fix for this?  As I stated above, we're using 1.7.2 currently.

**Comment by dakrone** [comment]
@tdoman I've been looking more into this to try and fix it, however, I can't
reproduce the issue you are seeing, here is my full reproduction:

```json
DELETE /myindex
{}

POST /myindex
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0,
    "index": {
      "analysis": {
        "analyzer": {
          "en_analyzer": {
            "type": "custom",
            "tokenizer": "icu_tokenizer",
            "filter": ["icu_normalizer",
                       "en_stop_filter",
                       "en_stem_filter",
                       "icu_folding",
                       "shingle" ],
            "char_filter": [ "html_strip" ]
          }
        },
        "filter": {
          "en_stop_filter": {
            "type": "stop",
            "stopwords": [ "_english_" ]
          },
          "en_stem_filter": {
            "type": "stemmer",
            "name": "minimal_english"
          }
        }
      }
    }
  },
  "mappings": {
    "doc": {
      "properties": {
        "title": {
          "type": "string",
          "analyzer": "en_analyzer"
        }
      }
    }
  }
}

POST /myindex/doc/1?refresh
{
  "title": "sale"
}

POST /myindex/doc/_search?pretty
{
  "query": {
    "query_string": {
      "query": "sales",
      "fields": ["title"]
    }
  }
}

POST /myindex/doc/_search?pretty
{
  "query": {
    "simple_query_string": {
      "query": "sales",
      "fields": ["title"]
    }
  }
}
```

Both the `query_string` and `simple_query_string` versions of the query return
the single hit.

Is there a difference I am missing for reproducing this?

**Comment by dakrone** [comment]
Closing this as I haven't heard back, feel free to comment if it's still an issue.

**Comment by tdoman** [comment]
Yes thanks Lee, I still need to get back to this one and figure out why you can't reproduce w/ the mapping you gave.  I must be missing some detail.  I'll definitely ping you if I can get to the bottom of it.
