### ISSUE TITLE
[Suggestion] Major version upgrades should be rolling upgrade 

### ISSUE THREAD

**Issue by felipegs** [elastic/elasticsearch#15567]
Hi,

For us, here, elasticsearch is very critical component, and is very painful to torn off the cluster for upgrade to use new features.

So for us is very important rolling upgrades.

Thanks

**Comment by nik9000** [comment]
For what its worth I agree that all upgrades _should_ be rolling but I don't think that is in the cards, at least for a while. I don't know how long "a while" is though. Sorry!

Also for what its worth, if you have a disaster recovery site you could probably get away with failing over to it for the upgrade. Its less than idea but its better than a total outage of the things that depend on Elasticsearch.

**Comment by felipegs** [comment]
Yes, failling over for the upgrade may be a reasonable option.

But it will be very nice if the new major version is designed with this goal.

**Comment by felipegs** [comment]
I think that is another people that use elasticsearch which has same problem..

**Comment by makeyang** [comment]
better add this

**Comment by eskibars** [comment]
We'll have to treat this on a case-by-case basis.  I think everybody would love to keep rolling upgrades as often as possible, but sometimes it's just not going to be possible.

**Comment by clintongormley** [comment]
Exactly what @eskibars has said. We'd love to make major version upgrades were rolling, but it's just not something we can provide at this point in time. It is something we aspire to.
