### ISSUE TITLE
Packages in the APT repository do not install any JRE

### ISSUE THREAD

**Issue by crispygoth** [elastic/elasticsearch#15569]
When installing the elasticsearch DEB package from the http://packages.elastic.co/ apt repository, the system doesn't automatically bring in any JRE package. This means the package is unusable until this is manually resolved (which causes issues with automated config systems such as Puppet).

The easiest way to get a JRE installed on Debian is to add ```default-jre-headless | java6-runtime-headless``` to the "Depends" line in the package control file. This tells APT to install Debian's default JRE  if no JRE is currently installed, and the second part tells APT that the dependency can be satisfied by any JRE package that provides at least a version 6-level Java (both the 7.x and 8.x JRE packages provide this).

**Comment by nik9000** [comment]
I remember a similar issue to this one but don't recall the resolution. @tlrx, do you remember?

**Comment by jpountz** [comment]
@nik9000 Maybe it was this one? https://github.com/elastic/elasticsearch/pull/3105

**Comment by tlrx** [comment]
And #6163

**Comment by clintongormley** [comment]
Yes - in #6163 we decided not to require a specific version of java, and leave it up to the user.
