### ISSUE TITLE
Highlight on more_like_this query not working in 2.0+, it was in 1.7.2

### ISSUE THREAD

**Issue by andreip** [elastic/elasticsearch#15560]
I'll give some examples with `curl` to prove my point, I have both `elasticsearch-2.1.1` and `elasticsearch-1.7.2` on my local to test with. I've also tested with all releases after 2.0 and all behave the same.

### Index setup

```bash
curl -XDELETE 'http://localhost:9200/test'
curl -XPOST localhost:9200/test -d '{
    "mappings" : {
        "test" : {
            "properties" : {
                "text" : { "type" : "string", "index_options": "offsets" }
            }
        }
    }
}'

curl -XPOST localhost:9200/test/test/1 -d '{
 "text": "Once upon a time there was a pretty little princess. And then the time changed."
}'
```

### Query ES 1.7.2

```
curl -XGET localhost:9200/test/test/_search?pretty -d '{
    "highlight": {
        "fields": {
            "text": {}
        }
    },
    "query": {
        "more_like_this" : {
            "fields" : ["text"],
            "like_text" : "time",
            "min_term_freq" : 1,
            "max_query_terms" : 12,
            "min_doc_freq": 1
        }
    }
}'
```

gives 
```
{
  "took" : 14,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.10848885,
    "hits" : [ {
      "_index" : "test",
      "_type" : "test",
      "_id" : "1",
      "_score" : 0.10848885,
      "_source":{
 "text": "Once upon a time there was a pretty little princess. And then the time changed."
},
      "highlight" : {
        "text" : [ "Once upon a <em>time</em> there was a pretty little princess.", "And then the <em>time</em> changed." ]
      }
    } ]
  }
}
```

### Query ES 2.0.x, 2.1.0 and 2.1.1 give same result

```
curl -XGET localhost:9200/test/test/_search?pretty -d '{
    "highlight": {
        "fields": {
            "text": {}
        }
    },
    "query": {
        "more_like_this" : {
            "fields" : ["text"],
            "like" : "time",
            "min_term_freq" : 1,
            "max_query_terms" : 12,
            "min_doc_freq": 1
        }
    }
}'
```

gives

```
{
  "took" : 48,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.10848885,
    "hits" : [ {
      "_index" : "test",
      "_type" : "test",
      "_id" : "1",
      "_score" : 0.10848885,
      "_source":{
 "text": "Once upon a time there was a pretty little princess. And then the time changed."
}
    } ]
  }
}
```

notice above doesn't include `highlight` in response. Is this intended? I saw [this PR](https://github.com/elastic/elasticsearch/pull/11077), thinking it might be related?

Is there another way to achieve the highlighting in newer versions? I've tried indexing with term vectors for `text` and that works for all ES versions, but I don't want to do that, since I'd rather keep the returned results in highlight on a sentence level to be easier to understand the context, so `postings` highlighting is the best choice for me. Plus it takes less space. Any recommendations to achieve highlighting, or am I doing sth wrong? Thank you!

**Comment by dtran320** [comment]
+1

**Comment by andreip** [comment]
can someone check this out? I did provide easy curl setup for the issues, just get two ES versions and try it out. Thanks!

**Comment by clintongormley** [comment]
@javanna could  you take a look at this please?

**Comment by andreip** [comment]
ping

**Comment by javanna** [comment]
I checked this out (sorry it took me a while!) and I can confirm this is due to the move to the lucene postings highlighter. Our own postings highlighter used to rewrite the query against the real index reader, which is a no-go performance wise. The lucene postings highlighter rewrites against an empty reader, the downside being that any query relying on the content of the reader it is rewritten against will not be highlighted. A more like this query does depend on what's in the index as the corresponding boolean query that is executed depends on frequencies of indexed terms. I am not sure the lucene postings highlighter can support the more like this query to be honest, maybe @rmuir can comment on whether that is technically possible without doing crazy rewrites. For now I would suggest to either provide a different query to highlight, if possible at all, or move to a different highlighter, for instance the plain one.

**Comment by rmuir** [comment]
I'm gonna be honest: I do not think highlighting even makes sense for this query.

I also don't know why MoreLikeThisQuery is being used (vs MoreLikeThis directly), as its an odd thing to expose via a query. MoreLikeThisQuery documents it mainly exists as a way to wedge MoreLikeThis into certain circumstances like custom queryparsers. It does strange things like set a 30% minShouldMatch by default (this is random, and does not make sense to me, probably a hack around the shitty query expansion happening here, e.g. no term frequency normalization).

**Comment by andreip** [comment]
> I also don't know why MoreLikeThisQuery is being used (vs MoreLikeThis directly),

@rmuir I don't think I understood that. What's the alternative of MLTQuery? There's another thing called [MLT API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-more-like-this.html) but it's been removed and it's said to use MLTQuery instead. Can you detail a bit? Thanks

**Comment by rmuir** [comment]
I am talking in lucene terms. I think ES exposes MLT in the wrong way.

**Comment by andreip** [comment]
@javanna Thanks for looking into this and for the thorough explanation! Indeed, using `plain` works for highlight, I'm not sure how fast this will be for our case, will try. Just as a fallback, is there a way to bypass MLT and still get highlighting? e.g. getting top K tf-idf terms extracted from text provided via a different query? since after that, I'd use those top-K and do an or-based search query with highlight on.

**Comment by javanna** [comment]
If the problem is speed, I would recommend to test it before declaring it a problem, it might very well be that it's ok. There may be alternatives using the terms vectors api to extract the top K terms and create the boolean query yourself based on those terms, but it would make things slower than using the plain highlighter I suspect.

**Comment by andreip** [comment]
We tested with plain and it seems fine. Issue is solved, thanks for looking
into this and providing an alternative!

**Comment by javanna** [comment]
thank you for getting back to us @andreip . Good to hear the plain highlighter works well for you.
