### ISSUE TITLE
Gradle's run task should pick up extra stuff used in integ tests

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#15608]
`lang-groovy` uses

```
integTest {
  cluster {
    systemProperty 'es.script.inline', 'on'
    systemProperty 'es.script.indexed', 'on'
  }
}
```

to setup super permissive configuration for testing but when you run it with `gradle plugins:lang-groovy:run` you get the standard configuration which makes testing one-offs more complicated. It'd be more friendly to pick up the integTest config and just use it for run. Or maybe to have a separate config for run so it could define stuff just in case it wanted to be different.

```
run {
  cluster {
    systemProperty 'es.script.inline', 'on'
    systemProperty 'es.script.indexed', 'off'
  }
}
```

This came up while I was working on #15125, reindex and update-by-query. update-by-query is very difficult to test without a scripting language so I enable `lang-groovy` to both tasks.

**Comment by clintongormley** [comment]
@rjernst can this be closed yet?

**Comment by rjernst** [comment]
Nothing directly has been done for it. We do support setting run settings, just like with integ tests, but they must be set separately. So to fix the issue originally mentioned here, you would add:

```
run {
  systemProperty 'es.script.inline', 'on'
  systemProperty 'es.script.indexed', 'off'
}
```

**Comment by clintongormley** [comment]
Actually:

    run {
      systemProperty 'es.script.inline', 'true'
      systemProperty 'es.script.indexed', 'false'
    }

`on` and `off` are no longer supported

**Comment by clintongormley** [comment]
Is this still an issue?

**Comment by hub-cap** [comment]
No longer an issue
