### ISSUE TITLE
Remove the warmer API

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#15607]
With time, warmers have become less and less useful: we got doc values by default in 2.0 and disk-based norms in 2.1. Instead of fixing the warmer-related bugs (#5155, #15590 or #15194) that we have, I'd like to suggest that we remove the warmer API entirely.

The migration strategy would be the following:
 - deprecate the warmer API in 2.x,
 - remove warmers and the warmer API entirely in 3.0, and ignore warmer definitions when upgrading from 2.x.

**Comment by kimchy** [comment]
++ for this plan, I love the fact that we don't need warmers anymore

**Comment by Mpdreamz** [comment]
I was just looking at taking a stab at #5155 but this is even better :+1:

**Comment by bpicolo** [comment]
@jpountz  How are we expected to take care of the use case of pre-building filter caches now?
