### ISSUE TITLE
Distance sorting and calculation incorrect and inaccurate

### ISSUE THREAD

**Issue by antondachauer** [elastic/elasticsearch#15606]
I'm using elasticsearch for a search functionality on a website. The search must provide a search by distance from a location in an - for example - 25km radius.

That's no problem, I'm using the following elasticsearch query array:

	{
	    "index": "kasd9i9021profiles",
	    "type": "profile",
	    "size": 30,
	    "from": 0,
	    "body": {
		"query": {
		    "bool": {
		        "filter": {
		            "geo_distance": {
		                "distance": "25km",
		                "distance_type": "sloppy_arc",
		                "_cache": true,
		                "location": {
		                    "lat": 48.136833417046,
		                    "lon": 11.570900696682
		                },
		                "unit": "km"
		            }
		        },
		        "must": [
		            {
		                "term": {
		                    "published": "1"
		                }
		            },
		            {
		                "match": {
		                    "country": "DE"
		                }
		            },
		            {
		                "match": {
		                    "category_id": "1"
		                }
		            }
		        ]
		    }
		},
		"script_fields": {
		    "distance": {
		        "lang": "groovy",
		        "params": {
		            "lat": 48.136833417046,
		            "lon": 11.570900696682
		        },
		        "script": "doc['location'].distanceInKm(lat,lon)"
		    }
		},
		"sort": [
		    {
		        "upgrade_sort": {
		            "order": "desc"
		        }
		    },
		    {
		        "has_siegel": {
		            "order": "desc"
		        }
		    },
		    {
		        "_geo_distance": {
		            "location": {
		                "lat": 48.136833417046,
		                "lon": 11.570900696682
		            },
		            "order": "asc",
		            "unit": "km"
		        }
		    }
		]
	    },
	    "fields": [
		"_source",
		"distance"
	    ]
	}

The value of "upgrade_sort" can be between 0 and 3. The value of "has_siegel" can be true or false.

The problems are:

    The results are not sorted by distance
    The distance in the result is between 0 and ~30km, not between 0 and 25km.

Is that a bug or a wrong query?

Also postet on stackoverflow.com: http://stackoverflow.com/questions/34372194/elasticsearch-distance-sorting-and-calculation

**Comment by antondachauer** [comment]
I've published more details about my mapping and the results on stackoverflow: http://stackoverflow.com/questions/34372194/elasticsearch-distance-sorting-and-calculation-incorrect-and-inaccurate

**Comment by jpountz** [comment]
The groovy script and the geo filter don't use the same method to compute the distance (the groovy script assumes a plane). Can you try to run `doc['location'].arcDistanceInKm(lat,lon)` instead of your current script to see if it gives different results?

**Comment by antondachauer** [comment]
It works, thanks! I could'nt find this solution or any hint in the documentation and so I tried for two weeks... :(

**Comment by jpountz** [comment]
I agree it's confusing that there are several ways to compute geo distances (and I had to look up the code to see which one distanceInKm is using). I opened an issue for it: #15616.

**Comment by antondachauer** [comment]
Thanks! :)

Am 22.12.2015 um 20:04 schrieb Adrien Grand:
>
> I agree it's confusing that there are several ways to compute geo 
> distances (and I had to look up the code to see which one distanceInKm 
> is using). I opened an issue for it: #15616 
> <https://github.com/elastic/elasticsearch/issues/15616>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/elastic/elasticsearch/issues/15606#issuecomment-166704365>.
>

-- 
Anton Dachauer
web developer | freelancer

sicher kommunizieren: https://www.antondachauer.de/kommunikation/

t: 0911 - 927 85 805
m: mail@antondachauer.de
w: http://www.antondachauer.de
t: https://twitter.com/antondachauer
x: https://www.xing.com/profile/Anton_Dachauer
