### ISSUE TITLE
Turn off stemming and stop words for phrase searches only

### ISSUE THREAD

**Issue by imranazad** [elastic/elasticsearch#15604]
I am using the query_string so that my users may be able to run boolean queries mixed with phrase queries such as:

"the mouth" OR the cancerous cells AND drugs AND "heart attacks"

The stop words and stemming should not be removed from the phrases but it should be removed from the non-phrase searches so:

drugs = > drug
cells => cell

The key issue I have discovered when trying to work around this is with the highlighting. So for example take the following query which queries two fields, one with stems and one without:

"the mouth"

it returns a document with two highlighted fields:

"the mouth"
"mouth"

"I think" what I really need is the ability to merge the two so that there is only one highlight field that gets returned with all the keywords and phrases highlighted if they exist within those fields.

Could this feature be implemented?

**Comment by jpountz** [comment]
I believe this could be implemented by having two fields: one that has stemming and stop words enabled, another one that has them disabled, and then redirecting to one field or the other from the query parser depending on whether a phrase is being parsed.

I'll leave this issue open to let others chime in, but in my opinion, this is a too specific feature for inclusion into elasticsearch.

**Comment by nik9000** [comment]
> I believe this could be implemented by having two fields: one that has stemming and stop words enabled, another one that has them disabled, and then redirecting to one field or the other from the query parser depending on whether a phrase is being parsed.

That is how I've done it in the [past](https://en.wikipedia.org/w/index.php?title=Special:Search&search=%22i+like+cats%22&cirrusDumpQuery). The query_string usage there was a mistake but the analysis was a good idea, I believe.

**Comment by nik9000** [comment]
> Could this feature be implemented?

Its called `matched_fields` and I implemented it to solve exactly the problem you describe above. Play around with that link in my last comment so how its used on wikipedia. Its certainly not perfect but it works pretty well.

**Comment by imranazad** [comment]
> and then redirecting to one field or the other from the query parser depending on whether a phrase is being parsed.

This sounds like an excellent idea but how would I parse the phrases only to redirect them to fields when I'm using the query_string and my query is mixed with terms and phrases including booleans?

**Comment by imranazad** [comment]
@nik9000 matched_fields looks very promising and I have it working now where the results are merged however I'm still obviously getting documents being returned with highlights just for "mouth" how can I filter these out since it's a phrase search and I should only be getting documents back with "the mouth".

**Comment by nik9000** [comment]
Right. I think the only way to do that is to issue the "right" query. See if you can define a `search_quote_analyzer` on the field and see if that works. It might. Otherwise its up to you to change the query, sadly.

**Comment by imranazad** [comment]
@nik9000 You are a legend man! That works! I'm quite amazed I've managed to get this to work, I really do think Elastic shines in this regard, this is a major issue with full-text search and the documentation doesn't really do a good job of selling the features already available in Elastic to make this happen.

**Comment by nik9000** [comment]
Hurrray!

I don't remember seeing _any_ documentation on search_quote_analyzer. Do you happen to be interested in sending a pull request? The documentation is right there in the source tree. I should have done it when I found it but I didn't. You can be better than I am and save the next person the trouble you went through!

**Comment by imranazad** [comment]
@nik9000  Sure thing, I'd love to, I can make my first contribution to Elastic! So what do I do exactly? You'll have to bear with me I've not done this before. Shall I create a new pull request? What do I do after that?

**Comment by nik9000** [comment]
> So what do I do exactly? You'll have to bear with me I've not done this before. Shall I create a new pull request? What do I do after that?

I believe the simplest way is to go to the page you wan to edit and click the "edit" pencil that is to the right of every heading. That should let you make a pull request without too much fuss. I don't know what page to edit. Maybe [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/string.html?q=string#string-params) one?

The other thing is that you'll have to sign a CLA - there are links to it on the top of the page about making a pull request. We need everyone who's sent a pull request, no matter how small to fill it out. I don't fully understand that reasoning behind it but I'm not a lawyer.

I'm just excited that you are happy and excited about making a contribution. Its how I got started and its fun and worthwhile!

**Comment by imranazad** [comment]
@nik9000 I'm very excited and happy to be contributing so much so I've documented the `search_quote_analyzer` on the page you suggested but I've also gone one step further and created a new page on how to actually use it to stop stemming and stop words for phrases as a potential use case. However I'm unsure how to get these changes committed. Since I needed to add a new page I thought the easiest option for me would be to clone master, create a branch, push and then issue a pull request but when I try to push my branch I'm getting a 403. I'm keen to get this in and see my first contribution go live! :-)

**Comment by nik9000** [comment]
Yeah, if you want to make a new page the best thing to do is to fork and clone like you did. Have a look at https://help.github.com/articles/fork-a-repo/ and see if that makes it make more sense.

**Comment by clintongormley** [comment]
It seems there is nothing more to do here, so I'm clsoing this issue

**Comment by mlissner** [comment]
This ticket is a few years old, but I'm a newbie to Elastic Search. I'm curious if anybody has thoughts about the pros/cons of the `matched_fields` approach mentioned here vs. the `multi-field` approach that appears in the documentation: 

https://www.elastic.co/guide/en/elasticsearch/reference/current/mixing-exact-search-with-stemming.html

I know this isn't the ideal place for this question, but I thought I'd put it here, since this is what comes up when you Google how to disable stemming per query.
