### ISSUE TITLE
Data inconsistency with different queries

### ISSUE THREAD

**Issue by pseverino** [elastic/elasticsearch#15600]
Hi guys,

I was doing some work with Kibana and I got some inconsistent results in my data, after that I did some more digging around with queries using REST and I discovered some problems with ES.

So I have some millions of events in my index and I get completely different results from different queries,  I think the problem is when I use aggregations inside of another aggregation. Let me show you the queries and the results:

Aggs 1:

```
"aggs" : {
  "3" : {
    "filter" : { "term" : { "type" : "type1" } },
    "aggs" : {
      "1" : { 
        "filter" : { "term" : { "domain" : "X" } },   
        "aggs" : {
          "distinct" : { "cardinality" : { "field" : "remote_addr" } }
        }
      }
    }
  }
}
```

Result 1:

```
"hits" : {
  "total" : 13785806,
  "max_score" : 0.0,
  "hits" : [ ]
},
"aggregations" : {
  "3" : {
    "doc_count" : 617159,
    "1" : {
      "doc_count" : 617159,
      "distinct" : {
        "value" : 293193,
        "value_as_string" : "0.4.121.73"
      }
    }
  }
}
```

Aggs 2:

```
"aggs" : {
  "3" : {
    "filter" : { "term" : { "type" : "type1" } },
    "aggs" : {
      "distinct" : { "cardinality" : { "field" : "remote_addr" } }
    }
  }
}
```

Result 2:

```
"aggregations" : {
  "3" : {
    "doc_count" : 617159,
    "distinct" : {
      "value" : 293193,
      "value_as_string" : "0.4.121.73"
    }
  }
}
```

Aggs 3:

```
"aggs": {
 "2": {
   "terms": {
     "field": "domain",
     "size": 5,
     "order": {
       "2-orderAgg": "desc"
     }
   },
   "aggs": {
     "3": {
       "terms": {
         "field": "type",
         "size": 1,
         "order": {
           "1": "desc"
         }
       },
       "aggs": {
         "1": {
           "cardinality": {
             "field": "remote_addr"
           }
         }
       }
     },
     "2-orderAgg": {
       "cardinality": {
         "field": "remote_addr"
       }
     }
   }
 }
}
```

Result 3:

```
"aggregations" : {
  "2" : {
    "doc_count_error_upper_bound" : -1,
    "sum_other_doc_count" : 6767717,
    "buckets" : [ {
      "key" : "X",
      "doc_count" : 617159,
      "3" : {
        "doc_count_error_upper_bound" : 0,
        "sum_other_doc_count" : 0,
        "buckets" : [ {
          "key" : "type1",
          "doc_count" : 617159,
          "1" : {
            "value" : 368688,
            "value_as_string" : "0.5.160.48"
          }
        } ]
      },
      "2-orderAgg" : {
        "value" : 283687,
        "value_as_string" : "0.4.84.39"
      }
    }
    ...
    } ]
  }
}
```

So something is going wrong inside ES by this results.
We can conclude:
- The index has 13785806 documents
- 617159 documents have domain with value "X"
- 617159 documents have the type with value "type1"
  ? We can see with aggs3 that the document with domain="X" and type="type1" are the same, so how can we have different cardinalities for this sets in aggs3? Notice that the cardinality in the inner set is even bigger that the one on the outside set...

Do you have any ideas about this? I think this really is an ES bug, but could be any kind of error from my part? (I know comparing filters and eggs could be misleading, but the results are too different...)

Other info:
- I experienced the error with ES 2.1.0 and after I upgraded to 2.1.1 the error persists
- About the data types
  -  Domain is a string, not analyzed, doc values active
  -  Type is a string, not analyzed, doc values active
  -  Remote_addr  is an ip, not analyzed, doc values active

**Comment by clintongormley** [comment]
Besides the issues you see, the `value_as_string` should not be returned as an IPv4 address.

**Comment by pseverino** [comment]
@clintongormley that behavior happens in more of my queries if I'm not mistaken, if you need more about about that just ask. I will see if that behavior really happens in other queries

**Comment by polyfractal** [comment]
There could be a number of explanations here that aren't bugs.  For example, `cardinality` counts distinct _values_, not documents.  So documents that have multiple `remote_addr` will overinflate the cardinality relative to doc count.  Similarly, documents that don't have a `remote_addr` will under-report the cardinality.

Then there's the fact that the cardinality aggregation is an approximate algorithm, and it's possible for it to produce results that are not entirely accurate (both over or under the true value).

It's hard to know from the above snippets, but terms-agg approximations could be playing a role here too.

Unfortunately, I don't think we have a hope of debugging this without a more minimal reproduction.  @pseverino if you can provide a smaller dataset that exhibits this behavior we can take a look.  I'm going to close this ticket in the mean time.
