### ISSUE TITLE
Add support for "quarter" ranges in date math for filtering by date range. 

### ISSUE THREAD

**Issue by javadevmtl** [elastic/elasticsearch#15612]
It would be nice if we could add "quarter" date math for date range filters.

Some examples: now/q (this quarter), 2015-01-01||-1M/q (previous quarter from 2014)

``` javascript
{
    "from": 0,
    "size": 10,
    "query": {
        "bool": {
            "must": {
                "range": {
                    "my_date": {
                        "gte": "now-1q/q",
                        "lte": "now-1q/q"
                    }
                }
            }
        }
    }
}
```

**Comment by monkeyboy64** [comment]
We are running into this to. We can programmatically figure out the dates, but that isn't as easy has just have a quarter time unit.

**Comment by paixaop** [comment]
Any news on this issue? Quarters are terribly important to analyze sales data.

**Comment by jpountz** [comment]
@paixaop No news, this hasn't been worked on. We are in the process of changing the framework that we use to manipulate dates, so this might not get attention until this is finished, even though we understand how important this change is to our users. Sorry about that.

**Comment by jpountz** [comment]
cc @elastic/es-search-aggs

**Comment by rudyamid** [comment]
Now that Elastic is chugging along with 7.x, is this improvement still considered?  I would hate to use ruby codes to get things done, when I don't have to.

**Comment by nemhods** [comment]
> @paixaop No news, this hasn't been worked on. We are in the process of changing the framework that we use to manipulate dates, so this might not get attention until this is finished, even though we understand how important this change is to our users. Sorry about that.

Is there any way that with that new framework we'd be able to flexibly define rounding fractions, like "now/3h"? This way, quarters can be simply implemented as "now/3M"

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
