### ISSUE TITLE
Multiple types in one index caused to ES collapsed

### ISSUE THREAD

**Issue by panda87** [elastic/elasticsearch#15619]
Hi

A few days ago I started to use the _type meta as part of my data modeling conventions.
The convention defined that I have one index and under this index many accounts + product name.
The mappings that I created in a /_template is using only one default without any exceptions between the types since I expect that all the types will have the same fields but the _type meta.

I started to ran some tests and create tons of accounts and my jvm throw out of memory, which means the ES instance collapsed.  
When I GET the template of this index, I realized that it creates nested object for each account and the file reached the 1M lines!

My question is how i can avoid this behaviour? that the mapping file is so big? What I need to do so the file will remain short as I build it from the beginning, because I want to keep using the _type but not with so many resources from my machine.

Thanks

**Comment by jpountz** [comment]
Right, each type holds its own mapping. So having many types can make the cluster state really large. I would advise to put all your accounts into the same index and only use a field to differentiate them (which is what types do as well) and filter at search time.

Please use https://discuss.elastic.co in the future for such questions and use github issues for bugs / feature requests. Thanks!

**Comment by panda87** [comment]
Thanks @jpountz
