### ISSUE TITLE
grep -E used in elasticsearch startup script causes error on Solaris

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#15628]
Since Elasticsearch 2.1.1 the elasticsearch startup script has contained this line:

    daemonized=`echo $* | grep -E -- '(^-d |-d$| -d |--daemonize$|--daemonize )'`

This means Elasticsearch 2.1 doesn't start on Solaris.  Changing grep -E to egrep makes it work on all of Solaris, Linux and Mac OS X:

    daemonized=`echo $* | egrep -- '(^-d |-d$| -d |--daemonize$|--daemonize )'`

On Solaris:

    $ echo -d -x -g --hello | grep -E -- '(^-d |-d$| -d |--daemonize$|--daemonize )'
    grep: illegal option -- E
    Usage: grep [-c|-l|-q] -bhinsvw pattern file . . .
    $ echo -d -x -g --hello | egrep -- '(^-d |-d$| -d |--daemonize$|--daemonize )'
    -d -x -g --hello

On Linux and Mac OS X:

    $ echo -d -x -g --hello | grep -E -- '(^-d |-d$| -d |--daemonize$|--daemonize )'
    -d -x -g --hello
    $ echo -d -x -g --hello | egrep -- '(^-d |-d$| -d |--daemonize$|--daemonize )'
    -d -x -g --hello

However, I am not sure if there are other platforms where egrep wouldn't work, so if there are any others you want to support you might want to check them too.

**Comment by dakrone** [comment]
The linux man page for grep states that egrep is deprecated, but provided for
backgrounds compatibility.

Since, however, I know of no GNU/Linux distribution where they are *not*
provided, I think it's reasonable to switch to using them in the script.

@droberts195 would you be interested in submitting a pull request for this?

**Comment by droberts195** [comment]
Sure, I can submit a pull request.

One way to fix it without using the deprecated egrep invocation on Linux would be to do something like this:

    if [ -x /usr/xpg4/bin/grep ]; then
        GREP=/usr/xpg4/bin/grep
    else
        GREP=`which grep`
    fi
    daemonized=`echo $* | "$GREP" -E -- '(^-d |-d$| -d |--daemonize$|--daemonize )'`

That might avoid the chance of somebody who knows that egrep is deprecated on Linux from changing back to grep -E in the future, but obviously the downside is that it's quite a bit more verbose than changing grep to egrep.

Do you have a preference for which way to fix it?

**Comment by dakrone** [comment]
I think I'd prefer the `egrep` method rather than hardcoding paths into the script.
