### ISSUE TITLE
Querying nested objects with query_string

### ISSUE THREAD

**Issue by imranazad** [elastic/elasticsearch#15627]
It would be useful to be able to query nested objects with the query_string.

For example consider the following document structure:

@graph
------------- @drug
 ------------------- @value

The query could look like this:
         "query": { 
                    "query_string" : {
                        "fields" : ["@graph\*"]
                        "query" :"\*@value:paracetamol"
                    }
         }
It can be laborious to explicitly specify nested fields when the document is heavily nested.
What do you think?

**Comment by clintongormley** [comment]
Do you mean fields of type `nested` or fields of type `object`?  Either way, `@` is a legal character in a field name, so you couldn't use it to mean something else.

**Comment by clintongormley** [comment]
Duplicate of #16551
