### ISSUE TITLE
how to access _score in script_fields

### ISSUE THREAD

**Issue by q11112345** [elastic/elasticsearch#15632]
im trying to access _score in script_fields, but got error message:
"reason": "GroovyScriptExecutionException[MissingPropertyException[No such property: _score for class: Script170]]",

when i use doc['_score'] to access the _score, i got  error message:
No field found for [_score] in mapping with types [fulltext]

so, can i access _score in script_fields?

**Comment by jpountz** [comment]
script_fields don't support reading the score. This is only supported on search scripts.
