### ISSUE TITLE
Mark node as disconnected

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#15643]
Is it possible for us to list a node as disconnected for a period after it has timed out/left the cluster? It seems that this would be helpful for admins looking to see which node has recently left, due to either intentional or otherwise reasons.

The idea came from [this tweet convo](https://twitter.com/kellabyte/status/679722874039603201).

**Comment by clintongormley** [comment]
@bleskes what do you think about this?

**Comment by bleskes** [comment]
The information of nodes historically being part of the cluster is covered by our monitoring efforts. I feel such an analysis is better done there.
