### ISSUE TITLE
Bad indexing performance of elasticsearch

### ISSUE THREAD

**Issue by talentzxf** [elastic/elasticsearch#15656]
Currently, I'm using elastic search to store and query some logs. We set up a five node elastic search cluster. Among them two indexing nodes and three query nodes. In the indexing node, we have redis, logstash and elasticsearch on both two servers. The elasticsearch uses NFS storage as data store. Our requirement is to index 300 log entries/second. But the best performance I can get from elasticsearch is only 25 log entries/second!
Here's the detailed information in StackOverflow: http://stackoverflow.com/questions/34449405/bad-indexing-performance-of-elasticsearch

My question is:
Can anyone tell me what is elastic search doing and why the indexing is so slow? And is it possible to improve it?

**Comment by spinscale** [comment]
Please use our [discuss forum](http://discuss.elastic.co/) for questions like these, we try to use github issues for bugs/features only. 

Important side note: Do not use NFS with Elasticsearch, see [this post](https://www.elastic.co/blog/performance-considerations-elasticsearch-indexing) by Mike McCandless or [The definitive guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-performance.html)

**Comment by talentzxf** [comment]
I have moved this post to https://discuss.elastic.co/t/bad-indexing-performance-of-elasticsearch/37962
