### ISSUE TITLE
It's a way to create lucene index, and load to elasticsearch directly?

### ISSUE THREAD

**Issue by kewn21** [elastic/elasticsearch#15659]
I have 1 billion rows to write into elasticsearch every day,so i used bulk api to write data,but the performance was unacceptable.
Can i create lucene index, and load to elasticsearch directly,who has idea?

**Comment by jpountz** [comment]
This is a bit surprising that you can load data much faster in a lucene index than in elasticsearch. Did you verify it?

In any case this is not a scenario that we want to support as it prevents us to enforce any structure of the index.

**Comment by kewn21** [comment]
I'm thinking of feasibility,i heard two people say they realized, they use lucene api to create index in mapreduce,but performance is not good.

**Comment by clintongormley** [comment]
Thanks for the feedback @kewn21. This is not a work flow that we intend to support.

**Comment by kewn21** [comment]
Because our hadoop cluster has sufficient resource to create elasticsearch index,especial we would create more than one index in concurrent,so that it can create index by lucene api in mapreduce,then push them to elasticsearch nodes and create elasticsearch metadatas,the throughput may be bigger than using elasticsearch bulk api.
