### ISSUE TITLE
elasticsearch index not analyzed

### ISSUE THREAD

**Issue by yqguodataman** [elastic/elasticsearch#15654]
I have a message, example:
    a    b
this message beginning with multiple spaces and more than one space between this message.
My mapping set no_analyzed,when search this message,This message has only one space, example:
a b
I don't know why this is.

**Comment by spinscale** [comment]
Please use our [discuss forum](http://discuss.elastic.co/) for questions like these, we try to use github issues for bugs/features only. You may want to use the [analyze API](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/indices-analyze.html) to test things out and provide a full-blown example there, so other people can reproduce your problem. Thanks!
