### ISSUE TITLE
Threshold coloring based on time interval

### ISSUE THREAD

**Issue by patjlm** [elastic/elasticsearch#15658]
Would it be possible to have a threshold list of values using templates and especially $interval ?

Values in the graph are highly based on the time interval used: we do not have the same number of errors during 1second or during 1 hour. It would be nice to be able to use $interval in the threshold values list for coloring tables or single stats.

    Threshold: 0,100*$interval,500*$interval

That would mean always providing the interval in the same unit. So maybe $interval_ms (as I saw in some other issues) might be more relevant.

**Comment by nik9000** [comment]
I believe you've posted this issue in the wrong github project. Sorry about that!

**Comment by nik9000** [comment]
Did you mean to post this in https://github.com/elastic/kibana ?

**Comment by patjlm** [comment]
sorry, wrong project indeed... need some sleep...
