### ISSUE TITLE
how to import a folder

### ISSUE THREAD

**Issue by wanghaisheng** [elastic/elasticsearch#15652]
if i have a folder contains 1000 files which i want to import to elasticsearch ,which api or tools should i use?
right now  i only find 
```
curl -XPOST 'http://192.168.27.236:9200/test/test/1' -d @lane.json
 curl -s -XPOST http://192.168.27.236:9200/_bulk --data-binary @requests
```

**Comment by jpountz** [comment]
Please use the forums for such questions: http://discuss.elastic.co

For only 1000 documents both approaches would probably be fine (assuming docs are small)
