### ISSUE TITLE
Getting Different Index Mapping when creating Index using Node Client in ES 2.1

### ISSUE THREAD

**Issue by ersushantsood** [elastic/elasticsearch#15666]
Hi All,
I am trying to create an index using NodeClient/TransportClient in ES 2.1 by calling client.index(request).get() and when the index gets created it is having a different Mapping created and does not match with the source

My Source which i provided to Index api : 
"title":{"type":"string"},"description":{"type":"string"},"hits":{"type":"integer"},"columns":{"type":"string"},"sort":{"type":"string"},"version":{"type":"integer"}}"
:
Mapping Generated by ES :
create_mapping [type] with source [{"search":{"properties":{"columns":{"properties":{"type":{"type":"string"}}},"description":{"properties":{"type":{"type":"string"}}},"hits":{"properties":{"type":{"type":"string"}}},"sort":{"properties":{"type":{"type":"string"}}},"title":{"properties":{"type":{"type":"string"}}},"version":{"properties":{"type":{"type":"string"}}}}}}]

As you see every field is converted to PROPERTIES json object . I want it to remain as is the way i added in request . Can you please let me know if its a bug or i have to set any additional value in the request to that mapping should get generated as per the source I provided.

**Comment by ersushantsood** [comment]
Please respond to the issue as it is blocking my implementation, meanwhile I have done the workaround that I am not storing this mapping for the index and let elastic search dynamically create mapping for me

**Comment by jasontedor** [comment]
For anyone to diagnose your issue, they would need the [minimal and exact steps](https://en.wikipedia.org/wiki/Minimal_Working_Example) you went through (including code) that reproduces the issue, combined with a statement of what you expect to be happening and what is actually happening.

Armed with that information, it will be easier to determine if your expectations have a bug, if your code has a bug, or if Elasticsearch has a bug.

**Comment by rjernst** [comment]
It looks like you are indexing the mapping as a document. The reason you see "properties" is because the field names that you want are seen as object fields, which contain a field "type", and each type field is then a string.

See the put mapping api:
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html
