### ISSUE TITLE
How to check cluster settings is worked after update?

### ISSUE THREAD

**Issue by kewn21** [elastic/elasticsearch#15669]
I execute 
```
curl -XPUT localhost:9200/_cluster/settings -d '{
    "transient" : {
    		"index.translog.interval" : "10s"
    }
}'
```
it returns```{"acknowledged":true,"persistent":{},"transient":{}}```
It seems no worked, and i use ```curl -XGET localhost:9200/_cluster/settings``` to check it,but the same things returns as above,How can i to check it?

**Comment by GlenRSmith** [comment]
@kewn21 [index.translog.interval](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-translog.html) is an [index setting](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html), not a [cluster setting](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-update-settings.html).

[The Elastic Discuss forums](https://discuss.elastic.co/) or the elasticsearch IRC channel are the preferred places to seek this type of assistance. Github issues should be reports of erroneous behavior, preferably those that have already been investigated sufficiently to be certain they aren't user errors.
