### ISSUE TITLE
License upgrade issues

### ISSUE THREAD

**Issue by jhush** [elastic/elasticsearch#15677]
Running elasticsearch 2.1.1 on ox s 10.11.2 : 
issues：
[ERROR][license.plugin.core      ] [Baroness Blood] 
#
# License will expire on [Wednesday, January 27, 2016]. If you have a new license, please update it.
# Otherwise, please reach out to your support contact.
# 
# Commercial plugins operate with reduced functionality on license expiration:
# - marvel
#  - The agent will stop collecting cluster and indices metrics

Updating license:
curl -XPUT -u myusername 'http://localhost:9200/_license' -d @license.json

{
	”error":{
		"root_cause"[{
			"type":"parse_exception",
			"reason":"Failed to derive xcontent"
		}],
			"type":"parse_exception",
			"reason":"Failed to derive xcontent"
	},
	"status":400
}

**Comment by markwalkom** [comment]
I've raised this against our internal Marvel issue tracker, I can't provide a link though sorry.

**Comment by GlenRSmith** [comment]
@jhush can you please paste the contents of license.json **with the obviously unique bits redacted**?

**Comment by harictengazel** [comment]
Any update ?

**Comment by clintongormley** [comment]
@harictengazel given that we haven't received the contents of the license file that we asked for above, no, no update.  Make sure that the json file actually contains the license.  

Try using `curl --trace-ascii - -XPUT...`  to debug

**Comment by clintongormley** [comment]
No further feedback.  Closing
