### ISSUE TITLE
Add documentation and specs for _msearch/template

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch#15674]
Issue: https://github.com/elastic/elasticsearch/issues/10885
PR: https://github.com/elastic/elasticsearch/pull/12414

It was merged with no documentation, no specs and no rest integration tests, it is unclear whether it's a separate API or how the client implementation should look like.

**Comment by clintongormley** [comment]
@MaineC could you take care of this please

**Comment by MaineC** [comment]
Makes sense, will do.

**Comment by fedotovalex** [comment]
Bump. Any progress on this one? It would be nice to see this feature available in the clients.

**Comment by MaineC** [comment]
@HonzaKral It's been quite a while since last I touched our REST spec/tests -

**Comment by MaineC** [comment]
Wrong button - sorry for the noise.

**Comment by karmi** [comment]
Is there any news here? I have an issue submitted for the Ruby client (https://github.com/elastic/elasticsearch-ruby/issues/328), and would like to use the JSON specs and YAML tests for implementing the feature in the client.

**Comment by javanna** [comment]
@karmi as far as I can see spec and docs were committed, I guess this issue should have been closed. @MaineC can you comment on this?

**Comment by MaineC** [comment]
@karmi What other than what was merged in #17382 do you need? I'd appreciate feedback from those using the feature.

**Comment by javanna** [comment]
one more thing, I wonder if the spec and rest tests should move to the mustache module, which is where the code now is.

**Comment by karmi** [comment]
@MaineC, sorry, I have overlooked the #17382 issue, seeing it now!

**Comment by karmi** [comment]
@HonzaKral, should we close this?

**Comment by HonzaKral** [comment]
Closed via #17382

My apologies for taking so long, it completely slipped. My bad and thanks @MaineC !
