### ISSUE TITLE
ES java very high CPU usage

### ISSUE THREAD

**Issue by tommoholmes10** [elastic/elasticsearch#15673]
My CPU usage 120~, it's so high. How to reduce my CPU usage
my server have 2 Gb 
I run elasticsearch 2.1

**Comment by jasontedor** [comment]
I recommend taking this question to the [Elastic Discourse forums](https://discuss.elastic.co) and only opening an issue here if the dicussion there reveals an issue in Elasticsearch. When you do post there, you'll want to provide more detail.
