### ISSUE TITLE
Type name is highlighted when searching in specific type

### ISSUE THREAD

**Issue by kweima** [elastic/elasticsearch#15689]
I have a `restaurant` index, and a type named `japanese`. So I use the following URL for searching:
`http: //localhost:9200/restaurant/japanese/_search`

And my query body is:

```
{
    "query": {
        "match": {
            "title": {
                "query": "sushi"
            }
        }
    },
    "highlight": {
        "fragment_size": 70,
        "no_match_size": 70,
        "number_of_fragments": 1,
        "require_field_match": false,
        "fields": {
            "title": {},
            "description": {}
        }
    }
}
```

It just search through the title field with 'sushi', but the type name 'japanese' is highlighted as well.
Is this a BUG, or did I do something wrong?

ES version is 2.0.0.

**Comment by toyama0919** [comment]
me too.
I use Elasticsearch-2.1.1.

**Comment by nik9000** [comment]
I imagine that its a bug. I haven't tried it myself but it looks like it from your description. Can you work around it by specifying a `highlight_query`?

**Comment by nik9000** [comment]
Confirmed as a bug:
```
curl -XDELETE localhost:9200/test?pretty
curl -XPOST 'localhost:9200/test/japanese?pretty&refresh' -d'{"foo": "japanese sushi"}'
curl -XPOST localhost:9200/test/japanese/_search?pretty -d'{
  "query": {
    "match": {
      "foo": "sushi"
    }
  },
  "highlight": {
    "require_field_match": false,
    "fields": {
      "foo": {}
    }
  }
}'
```

Spits out:
```
        "foo" : [ "<em>japanese</em> <em>sushi</em>" ]
```

Which it really shouldn't.

**Comment by nik9000** [comment]
I've confirmed you can work around this by setting require_field_match to true or by supplying the original query as a highlight_query.
