### ISSUE TITLE
Remove guice from Rest*Action

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#15685]
If we're going to remove `@Inject` from the node level stuff we have to start somewhere. I will start with `Rest*Action` classes because it looks reasonably easy.

**Comment by aanchal9** [comment]
Is this still an issue or is it resolved?

**Comment by nik9000** [comment]
I believe this is resolved. I'll double check but I believe we can close
it.

**Comment by aanchal9** [comment]
Ok thanks.

**Comment by ideadapt** [comment]
@nik9000 Did you find anything? I think this issue can be closed …

**Comment by nik9000** [comment]
I @ideadapt you are right! Sorry I didn't verify this earlier.
