### ISSUE TITLE
Change in meaning of network.host

### ISSUE THREAD

**Issue by digitalrinaldo** [elastic/elasticsearch#15683]
It is common for a setting of 0.0.0.0 to mean bind to all hosts.  The latest release of Elasticsearch 2.1.1 is treating 0.0.0.0 a an error condition and it binds to the first address or some other odd approach in the list of interfaces returned by ifconfig on linux and solaris.

It also doesn't appear to support a non ip name. If I use a hostname i get an error. if I use a dns name I get an error. It only worked with an IP address.

**Comment by eskibars** [comment]
Can you provide a bit more detail?  Post your config (or the relevant networking bits), the system information+versions (OS, java), and what you're seeing vs what you're expecting?  I just successfully tested 2.1.1 using network.host set to 0.0.0.0 and separately as an explicit hostname with no problems.  Note that we don't support Solaris (https://www.elastic.co/support/matrix).  Also, this may be a question of setup better suited for our forums at https://discuss.elastic.co/ .  If that's the case, we can close this one once you open a thread there.

**Comment by clintongormley** [comment]
No further feedback, plus the docs for networking have been greatly improved.  Closing
