### ISSUE TITLE
Appending data in Elasticsearch indexes

### ISSUE THREAD

**Issue by aakash21** [elastic/elasticsearch#15680]
I have 2 servers where Elasticsearch Indexes are stored with same index name but different data on both the indexes, now there is requirement of putting that data into one server, so I want to append the data of both the indexes(present on 2 different servers) into single index, how i can do that.
Currently, I am using this configuration for appending the data.

input {
  elasticsearch {
   hosts => "server1:9200"
   index => "logstash-2015.12.16"
  }
}
filter {
 mutate {
  remove_field => [ "@version", "@timestamp" ]
 }
}
output {
 elasticsearch {
   host => "localhost"
   port => 9200
   protocol => "http"
   manage_template => false
   index => "logstash-2015.12.16"
 }
}

**Comment by s1monw** [comment]
please use our discuss forum https://discuss.elastic.co/  for questions like this, the issue tracker is only for bugs, improvements or feature tracking
