### ISSUE TITLE
Run scripts for solaris are using -E option

### ISSUE THREAD

**Issue by digitalrinaldo** [elastic/elasticsearch#15682]
The solaris scripts are using grep with the -E option. This option is not supported in the default distribution.

[ Dec 28 15:11:22 Disabled. ]
[ Dec 28 15:12:11 Enabled. ]
[ Dec 28 15:12:11 Executing start method ("/scratch/elasticsearch/bin/elasticsearch"). ]
grep: illegal option -- E

**Comment by eskibars** [comment]
This is a duplicate of https://github.com/elastic/elasticsearch/issues/15628 .  I'm closing this in favor of that one.

For the time being, we don't support Elasticsearch on Solaris: https://www.elastic.co/support/matrix
