### ISSUE TITLE
clean up test-framework dependencies in 2.x

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#15697]
master is ok, but 2.x really needs some love here:

* elasticearch tests jar depends on `lucene-test-framework` but uses  a *different* `randomized-testing` version for no good reason, its just outdated. 
* there are complicated maven exclusions that are really unnecessary, and I'm not sure they are complete, possibly dragging in an ant.jar or similar at the moment.

we should upgrade lucene (https://issues.apache.org/jira/browse/LUCENE-6953) and just depend on `lucene-test-framework` and use its version.

**Comment by s1monw** [comment]
+1

**Comment by clintongormley** [comment]
this appears to have been done. closing
