### ISSUE TITLE
boost parameter in match_all query doesn't work

### ISSUE THREAD

**Issue by socurites** [elastic/elasticsearch#15694]
It said, "The _score can be changed with the boost parameter:", but it's not.

According to MatchAllDocsQuery.sumOfSquaredWeights(), it just returns boost * boost.
```java
public float sumOfSquaredWeights() {
      queryWeight = getBoost();
      return queryWeight * queryWeight;
    }
````
hence, queryNorm is just 1.0 / boost,
and score is always 1.0, since boost * queryNorm is 1.0.

**Comment by clintongormley** [comment]
The queryNorm isn't always 1.0.  For instance, try the following and change the `boost` parameter from 1 to 10:

    PUT t/t/1
    {
      "foo": "one"
    }
    
    PUT t/t/2
    {
      "foo": "two"
    }
    
    
    GET t/_search
    {
      "query": {
        "bool": {
          "should": [
            {
              "match_all": {
                "boost": 1
              }
            },
            {
              "match": {
                "foo": "one"
              }
            }
          ]
        }
      }
    }
