### ISSUE TITLE
When use dynamic scripts or how use dynamic scripts better?

### ISSUE THREAD

**Issue by ihaolin** [elastic/elasticsearch#15704]
Hello,

I am using **dynamic scripts** in elasticsearch **1.5.2**，but I discover the **dynamic scripts** query is so slow, like this:
  
    ...
    scriptParams.put("shopId", 789);
    script("doc['shopId'].value == shopId", scriptParams);
    ...
It will costs almost **1000+ms**，but if i use **filter query**，only need **40~60ms**。

What's the mistake? When or How use **dynamic scripts** rightly? 

Thanks && Regards.

**Comment by nik9000** [comment]
This is more a question for the forums so I'm going to close it but I'll answer it any way.

A query/filter will use the index. A dynamic script will visit each do and run the check. Even though `doc` uses a column store its going to be much slower than using the index. Dynamic scripts are useful for lots of stuff. Say you wanted to run a one-off report and wanted to get all of the `shopId`s that had a length of 10 or something. Or you wanted to do a scripted aggregation or something. They have their use, but a filter is always going to be faster.
