### ISSUE TITLE
what is the total score for each query?can it be in a range? or at least i can calculate the range myself

### ISSUE THREAD

**Issue by q11112345** [elastic/elasticsearch#15703]
ive got a problem when im trying to custom the score processing.
im going to use "(_score/TotalScore)CustomTotalScoreweight" to calculate my own score.
i think this can map the _score to a controllable score space.

TotalScore should be the max score the elasticsearch could give in one query.
CustomTotalScore is the max score i set. it could be 100, 50 or any other scores that i give.

the finally score could be the sum of the result of this full formula and the result of other formula.

but now, i cant find the TotalScore the elasticsearch give.

so, what is the totalscore in query?
::: ive analysed the "explain" from elasticsearch to the query, im finding that, the total score is calculated with the score of each term. im wondering, if i can caculate the total score myself of each query when i know the term number and the total score for each term.

so, i think the term number of each query can be easily obtained, but still, what could the total score of each term be in one query?

**Comment by clintongormley** [comment]
You can't rely on the score being in any particular range. it just doesn't work that way.  You could use a function score query to do what you want though

**Comment by q11112345** [comment]
i think i can figure out the total score now.
i disable tf and fieldNorm calculation. the score is only calculated by idf

and idf = (log(1 + total_document/term_documents))^2

if i know total_documents and set term_documents to 1, then i will get the max value of idf.

just like idf=log(1+300/1) ^2, maybe this could be max_idf=log(1+total_document) ^2
and the total idf above will be 2.478...

the question is , how can i get the total_document from es.

it seems that the total_document in the calculation does not equal to the total document stored in  es.
