### ISSUE TITLE
Show fetch_count[152] for Fetch Slowlog

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#15719]
Currently the fetch slowlog and the query slowlog show the same detail, which is generally extremely useful.

However, when debugging slow fetches, it's hard to judge just how many documents were coming from a given shard. As a result, it would be great to know how many documents are actually being fetched from the shard when it's marked as slow.

As a workaround, it is possible to supply the relevant shard as a shard preference in order to get the relevant count, but it may be out of date when a human checks.

**Comment by jasontedor** [comment]
This issue has been open for two years without attracting any additional interest. I am going to close this issue. We can open a new issue or reopen this one if a compelling case is made for this functionality.
