### ISSUE TITLE
[Ingest] Simulate api should also work if the document id or type is omitted

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#15711]
The id and type of sample documents provided in the simulate api should be optional, so that it is easy to just paste in sample logs without having to think about id, type or any other document metadata.

**Comment by Bargs** [comment]
This is critical for allowing first time users to interactively build a pipeline in the new ingest UI using some sample log data before indexing any real data.

**Comment by Bargs** [comment]
@BigFunger you'll need this for the pipeline step you're working on eventually.

**Comment by martijnvg** [comment]
Added via #15747
