### ISSUE TITLE
Debian init script exits with success if Elasticsearch binary is missing

### ISSUE THREAD

**Issue by martinb3** [elastic/elasticsearch#15712]
We've had [an issue filed](https://github.com/elastic/cookbook-elasticsearch/issues/416) on the chef cookbook for Elasticsearch describing a problem [with this line](https://github.com/elastic/elasticsearch/blob/master/distribution/deb/src/main/packaging/init.d/elasticsearch#L112) of the Debian init script:

```
# Check DAEMON exists
test -x $DAEMON || exit 0
```

In short, if a user picks the wrong path for the binary, the init script exits 0 / success. I don't see the same problem with the RHEL/CentOS init script.

**Comment by clintongormley** [comment]
Hmm so this has been there since Dec 2011.  @spinscale any idea why we do this?

**Comment by spinscale** [comment]
no, looks like indeed like a bug. I think LSB defines what should be returned. There is a "program not running" error code, that should be returned here...

**Comment by martinb3** [comment]
Based on https://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/iniscrptact.html, it seems like 3 would be reasonable.

**Comment by martinb3** [comment]
It looks like this test was removed in the latest master, FYI. We can probably close this.

**Comment by clintongormley** [comment]
thanks @martinb3
