### ISSUE TITLE
Client API should use java collections APIs instead of HPPC's

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#15729]
Follow-up of https://github.com/elastic/elasticsearch/pull/15727: consumers of the Java client API have to get familiar with hppc (and its cursors for instance) while the same information could be exposed with regular Java collections.

**Comment by dadoonet** [comment]
++

**Comment by nik9000** [comment]
I wonder if its important that the actual `Client` interface in Elasticsearch do this. There ought to be a REST based java client and **it** certainly should do this.

**Comment by jpountz** [comment]
Yeah when I write "client API" this should read "what users use to communicate with elasticsearch". Which is the Client interface today, but may well change in the future. It is totally fine to use HPPC in internal code when appropriate.

**Comment by javanna** [comment]
I think we can close this as we are developing the Java high level REST client. There we won't have any hppc dependency. The java api will become internal as soon as the high level REST client is mature enough to replace it.

**Comment by jpountz** [comment]
Hurray!
