### ISSUE TITLE
Requests.putMappingRequest(index).type(index).source(builder);type must use the same value index?

### ISSUE THREAD

**Issue by selfchanger** [elastic/elasticsearch#15721]
when i create mapping using java api like this:
PutMappingRequest mapping = Requests.putMappingRequest(index).type(indexType).source(builder);
        PutMappingResponse putMappingResponse = client.admin().indices().putMapping(mapping).actionGet();

if i use "Requests.putMappingRequest(index).type(indexType)" instead of "Requests.putMappingRequest(index).type(index)." ,it reports error like this:

MapperParsingException[Root mapping definition has unsupported parameters:  [mpapercms : {properties={id={type=integer, store=yes}, kw={type=string, store=yes, analyzer=ik, searchAnalyzer=ik}, edate={type=date, store=yes, analyzer=ik, searchAnalyzer=ik}}}]]

so i wonder why i can't use indexType, shouldn't i use indexType instead of index?

**Comment by jpountz** [comment]
Please use the forums to ask questions: http://discuss.elastic.co. I suspect your problem is that you put the name of your index instead of your type at the root of your mapping definition.

We try to only use github for confirmed bugs and feature requests.

**Comment by dadoonet** [comment]
@selfchanger Adding to @jpountz's answer that we just added some documentation in 2.x and master branches with an example: https://www.elastic.co/guide/en/elasticsearch/client/java-api/2.x/java-admin-indices.html#java-admin-indices-put-mapping

**Comment by selfchanger** [comment]
@jpountz @dadoonet sorry for asking in github,i didn't know how to ask at  http://discuss.elastic.co before,so i asked here,now i know,thanks
