### ISSUE TITLE
Delete documents with matching query

### ISSUE THREAD

**Issue by ddes** [elastic/elasticsearch#15749]
Hi, 

Prior to 2.0 I used to execute this kind of request to delete documents with specific content:

curl -XDELETE 'http://localhost:9200/logstash-*/_query?pretty' -d '
{
"query": { "match": { "Message": "My test message" } }
}'

Since ES 2.0, I followed the documentation and notice that DELETE has been moved to plugin, well, but the syntaxt seems the same as : 
https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/delete-by-query-usage.html

But now i've got response like that:

No handler found for uri [/logstash-*/_query?pretty] and method [DELETE]

I've tried a lot of things, adding filters an so on, the GET is ok but can't suppress any documents.

Is something else to know about the new plugin or any bugs ?

Thanks a lot for help

**Comment by dadoonet** [comment]
Please ask your questions on discuss.elastic.co.

Did you install the plugin, restart all nodes?

**Comment by ddes** [comment]
Plugin installed but nodes not restarted.

I'll ask on discuss.elastic.co. thanks,

I was just wondering if any known bugs on this.

**Comment by dadoonet** [comment]
So yes you need to restart the nodes.
