### ISSUE TITLE
is it possible to patch index.max_result_window config and feature into 1.7?

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#15742]
it's really helpful for es memory issue, so I'd like to ask if it is possible to patch index.max_result_window config and feature into 1.7

**Comment by nik9000** [comment]
I'm not sure there will be another release of 1.7 and if there is I'm not sure its a good idea to add something like this to it. I understand your motivation though! I just don't think it'd be ok to add something that'd break existing behavior to a patch level release. I'm going to close this with that reasoning. Sorry!

**Comment by makeyang** [comment]
fully understand. thanks for reply.
