### ISSUE TITLE
Client API should use String instead of Text

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#15750]
For similar reasons to #15729, our client API should use the well-known String class where it today uses Text.

**Comment by Jordanwmk** [comment]
Hi, I am new to OSS but I would like to have a go at resolving this issue

**Comment by nik9000** [comment]
Since we're moving away from the `TransportClient` in general I don't think this is a good on. Honestly we should probably close this one in anticipation of https://github.com/elastic/elasticsearch/issues/23331

**Comment by nik9000** [comment]
@jpountz, what do you think about closing this?

**Comment by javanna** [comment]
I think that this is still valid given that the Java high level REST client is reusing the java api classes. Would be nice to not use anything that depends on lucene in there.

**Comment by nik9000** [comment]
I agree. We should do this. I wonder if we should wait on doing this for a while because it is another breaking change. At some point we'll be asking people to shift to the high level REST client and that is enough breaking change.

**Comment by dakrone** [comment]
I'm going to close this one, as we've removed the high level rest client in favor of the Java client.
