### ISSUE TITLE
Percolate api shouldn't be allowed to dynamically add fields to mapping

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#15751]
Today if a document is percolated and a field in the document being percolated doesn't exist in the mapping then that missing field is dynamically added to the mapping. To use case for this is that a skeleton document could be used to generate a mapping, but since this just adds fields with default settings this isn't doing correctly in many scenarios and percolator queries end up not being matched.

This "dynamically adding of fields" feature should be removed.

**Comment by jpountz** [comment]
+1

**Comment by martijnvg** [comment]
I started to look at this and it is a bit harder then I though. Basically during parsing of the percolate document we use a reference to an existing DocumentMapper and during parsing if a new field is discovered that DocumentMapper is updated. For the percolator (and term vectors api) we kind of want a read only copy of the DocumentMapper and if the document being parsed holds unknown fields it should thrown an exception.

We could change the `dynamic` property on the root mapper, because that option is updatable, but that isn't really an option, because DocumentMapper instances are being shared.

**Comment by jpountz** [comment]
> during parsing of the percolate document we use a reference to an existing DocumentMapper and during parsing if a new field is discovered that DocumentMapper is updated

Hmm I don't think this is correct. Document parsing returns a parsed document and a mapping update, so we would just have to ignore the mapping update I think?

```diff
diff --git a/core/src/main/java/org/elasticsearch/percolator/PercolateDocumentParser.java b/core/src/main/java/org/elasticsearch/percolator/PercolateDocumentParser.java
index 6733ebd..bdea794 100644
--- a/core/src/main/java/org/elasticsearch/percolator/PercolateDocumentParser.java
+++ b/core/src/main/java/org/elasticsearch/percolator/PercolateDocumentParser.java
@@ -49,14 +49,12 @@ public class PercolateDocumentParser {
     private final HighlightPhase highlightPhase;
     private final SortParseElement sortParseElement;
     private final AggregationPhase aggregationPhase;
-    private final MappingUpdatedAction mappingUpdatedAction;
 
     @Inject
-    public PercolateDocumentParser(HighlightPhase highlightPhase, SortParseElement sortParseElement, AggregationPhase aggregationPhase, MappingUpdatedAction mappingUpdatedAction) {
+    public PercolateDocumentParser(HighlightPhase highlightPhase, SortParseElement sortParseElement, AggregationPhase aggregationPhase) {
         this.highlightPhase = highlightPhase;
         this.sortParseElement = sortParseElement;
         this.aggregationPhase = aggregationPhase;
-        this.mappingUpdatedAction = mappingUpdatedAction;
     }
 
     public ParsedDocument parse(PercolateShardRequest request, PercolateContext context, MapperService mapperService, QueryShardContext queryShardContext) {
@@ -98,9 +96,6 @@ public class PercolateDocumentParser {
                         if (docMapper.getMapping() != null) {
                             doc.addDynamicMappingsUpdate(docMapper.getMapping());
                         }
-                        if (doc.dynamicMappingsUpdate() != null) {
-                            mappingUpdatedAction.updateMappingOnMasterSynchronously(request.shardId().getIndex(), request.documentType(), doc.dynamicMappingsUpdate());
-                        }
                         // the document parsing exists the "doc" object, so we need to set the new current field.
                         currentFieldName = parser.currentName();
                     }
```

**Comment by martijnvg** [comment]
@jpountz right this change is straight forward. I do wonder if we should fail the percolate request if the document to be percolated contains unmapped fields to avoid unexpected behaviour? If so, should have an `ignore_unmapped` setting like we have with sorting?

**Comment by jpountz** [comment]
I am wondering that this should not be necessary: since we require that fields are mapped when indexing queries, then we would only get dynamic mapping updates for fields that are not used by queries and thus do not matter for matching?

**Comment by martijnvg** [comment]
Agreed, we shouldn't worry about unused fields.
