### ISSUE TITLE
Types filter doesn't work for multiple types (EDIT - with nested fields)

### ISSUE THREAD

**Issue by TheHound** [elastic/elasticsearch#15757]
Client and Server on 2.1.0
This is superficially similar to https://github.com/elastic/elasticsearch/issues/2218.

I have an index called index1 with many types.
curl 'http://127.0.0.1:9200/index1/type1/_search?q=test
returns one result
curl 'http://127.0.0.1:9200/index1/type2/_search?q=test
returns one result.
These are different results with the correct type.
curl 'http://127.0.0.1:9200/index1/foo,bar,whatever/_search?q=test
returns both results
curl 'http://127.0.0.1:9200/index1/type1,foo/_search?q=test
returns results of type1 and type2 (both results)

This index and its mappings were created using the Java API. I cannot recreate this issue when using curl with a new index and mappings.

**Comment by eskibars** [comment]
Can you reproduce consistently with the Java API?  If so, can you provide an example snippet in a gist or the like?

**Comment by TheHound** [comment]
Hi, apologies for the misleading issue above I have finally reproduced with curl (I had missed something from my mapping previously). This seems to be cause by nested fields. In the last step outlined below there are 2 results. If the mapping for entityContent is removed then there are no results (this is correct)

Steps:
```
#Create Index
curl -XPUT "http://localhost:9200/index1"

#Create mappings
curl -XPUT --data @index1.type1.json "http://localhost:9200/index1/type1/_mapping"
curl -XPUT --data @index1.type2.json "http://localhost:9200/index1/type2/_mapping"

#Add Data
curl -XPUT --data @index1.data.json "http://localhost:9200/index1/type1/2"
curl -XPUT --data @index1.data.json "http://localhost:9200/index1/type2/2"

#Creates 2 hits
curl "http://localhost:9200/index1/a,b/_search?q=test"
```

Files:
index1.type1.json
```
{
	"type1" : {
		"properties" : {
			"content" : {
				"type" : "string"
			},
			"entityContent" : {
				"type" : "nested",
				"properties" : {
					"field1" : {
						"type" : "string"
					}
				}
			}
		}
	}
}
```
index1.type2.json
```
{
	"type2" : {
		"properties" : {
			"content" : {
				"type" : "string"
			}
		}
	}
}
```
index1.data.json
```
{
	"content" : "This is a Test."
}
```

**Comment by TheHound** [comment]
Having a quick read through the elasticsearch code base I assume this is going wrong on line 534 of 
https://github.com/elastic/elasticsearch/blob/1a47226d9af373e4627cd360ad8a8a7b93ea7882/core/src/main/java/org/elasticsearch/index/mapper/MapperService.java though not familiar enough to say for certain.

**Comment by clintongormley** [comment]
Hi @TheHound 

I don't understand this issue at all, or how what you see is different from what you expect.  The example you give above returns two documents, which is what I'd expect to get.  You're searching the `_all` field for the word `test`, which matches both documents.

**Comment by TheHound** [comment]
Hi @clintongormley 

I would expect the path part of the URL /a,b/ to act as a type filter. Since those types do not exist I would expect no results.

So:
```
curl 'http://127.0.0.1:9200/index1/type1/_search?q=test
```
Only returns 1 hit. I would therefore expect this to only return 1 hit:
```
curl 'http://127.0.0.1:9200/index1/type1,type3/_search?q=test
```
But instead returns 2, 1 for type1 and 1 for type2.

**Comment by clintongormley** [comment]
OK gotcha, here's a recreation:

    PUT index1
    
    PUT index1/type1/_mapping
    {
      "type1": {
        "properties": {
          "entityContent": {
            "type": "nested",
            "properties": {
              "field1": {
                "type": "string"
              }
            }
          }
        }
      }
    }
    
    PUT index1/type1/1
    {
        "content" : "This is a Test."
    }
    
    PUT index1/type2/2
    {
        "content" : "This is a test."
    }
    
   
Querying with a known type plus an unknown type returns both documents incorrectly:

    GET index1/type1,type3/_search?q=test
    
The explanation for this query (when there is a nested document mapped):

    GET index1/type1,type3/_validate/query?q=test&explain
    
is:

    "+_all:test #ConstantScore(+ConstantScore(ConstantScore(_type:type1) _type:type3 +(+*:* -_type:__*)))"

However, if you repeat the explanation without the nested doc mapping, you get:

    "+_all:test #ConstantScore(+ConstantScore(ConstantScore(_type:type1) _type:type3))"

**Comment by martijnvg** [comment]
@TheHound Thanks for reporting this issue! I'll back port it to all 2.x branches.
