### ISSUE TITLE
segment memory usage control[feature request]

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#15764]
let's say I have many many indeces, nowsdays all of term dictonaries are loaded into memory and thus cost lots of memory. so my request is if we can use a fixed size memory pool to manage this part of memory.

**Comment by jpountz** [comment]
I don't see how this would help?

**Comment by jpountz** [comment]
> nowsdays all of term dictonaries are loaded into memory

By the way this is not correct. Only a tiny portion of it is loaded into memory.

**Comment by makeyang** [comment]
my cluster has 50 data nodes and more than 1000 indices. 
when I execute:
GET _cat/nodes?v&h=port,sm
below is the response:
port       sm 
9300    1.1gb 
9300  963.9mb 
9300    1.1gb 
9300      1gb 
9300  934.3mb 
9300      1gb 
9300  885.9mb 
9300    1.1gb 
9300      1gb 
9300      1gb 
9300      1gb 
9300  973.9mb 
9300    1.1gb 
9300  941.4mb 
9300  964.3mb 
9300    894mb 
9300  933.2mb 
9300    1.1gb 
9300 1000.6mb 
9300  886.1mb 
9300    1.1gb 
9300      1gb 
9300 1019.3mb 
9300   1003mb 
9300    1.3gb 
9300  989.1mb 
9300 1022.6mb 
9300  945.8mb 
9300  986.5mb 
9300    1.2gb 
9300  893.7mb 
9300  938.5mb 
9300      1gb 
9300      1gb 
9300  966.5mb 
9300  944.1mb 
9300  915.8mb 
9300  925.3mb 
9300      1gb 
9300      1gb 
9300      1gb 
9300  919.6mb 
9300      1gb 
9300      1gb 
9300      1gb 
9300  896.4mb 
9300    1.2gb 
9300      1gb 
9300  879.9mb 
9300  819.9mb 

as our indices are becoming more and more, sm part will cost more and more memory. so this feature is make this part of memory consumption predictable and controable.

**Comment by makeyang** [comment]
@jpountz  any updates?

**Comment by clintongormley** [comment]
As @jpountz said: 

> I don't see how this would help?

You can see how much memory is being used by each segment with:

    GET _stats/segments

or in detail:

    GET _segments?verbose

You will see that the term dictionary doesn't actually use that much memory.
