### ISSUE TITLE
Remove fuzzy query

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#15760]
**Note**: This is the original comment stating some alternatives when it was not yet clear on how to proceed. As you can read below, we decided on option 1

As a term-level query, a fuzzy query will not run through the analysis stage. This can produce surprising results and I'd like to put this up for discussion whether we can do something about it. 

Consider this example:

```
PUT /people
{
   "mappings": {
      "person": {
         "properties": {
            "name": {
                "type": "string"
            }
         }
      }
   }
}
```

```
POST /_bulk
{"index":{"_index":"people","_type":"person"}}
{"name":"Marcy"}
{"index":{"_index":"people","_type":"person"}}
{"name":"Darcy"}
```

```
GET /_search
{
   "query": {
      "fuzzy": {
         "name": {
            "term": "Marcy",
            "fuzziness": "1"
         }
      }
   }
}
```

One could expect that this query returns "Marcy" and "Darcy" as the Levenshtein distance to the search term "Marcy" is 0 and 1 respectively. However, as person names are analyzed fields, the index contains "marcy" and "darcy", which explains why we just match one document with the provided fuzziness.

There are multiple options how we could tackle this.
### Option 1: Remove fuzzy query

The docs already state that [fuzzy queries are not that useful](https://www.elastic.co/guide/en/elasticsearch/guide/master/fuzzy-scoring.html). So one option could be to remove support for fuzzy queries and just expose them only indirectly e.g. in suggesters.
### Option 2: Analyze fuzzy query terms

We _could_ run search terms of a fuzzy query through an analyzer. While it will work out in the example case above, there are other cases where this will lead to really strange results. Consider this case:

```
GET /books/_analyze?analyzer=english
{
    "field": "content",
    "text": "atypical"
}
```

which produces the token `atyp`. Now a user might do a fuzzy search on this field, searching for "typical". Would we run this through the same analyzer, this would produce the token `typic` which obviously will not fuzzy-match. This is even more puzzling.

The above case has already shown that analyzing query terms can also produce unexpected results. I think it boils down to the fact that there is an imbalance between what's indexed and what's searched.
### Option 3: Improve docs

The [Term Query docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html) already point out the problem but this is maybe too disconnected from the fuzzy query docs so users don't see that this warning also applies to fuzzy queries.

So we could add specific examples that demonstrate this case and link back to the term query docs for the explanation.

**Comment by jimferenczi** [comment]
The fuzzy query is a sort of term query, it generates all possible matching terms that are within the maximum edit distance of the specified term. There is no analysis involved. If you want to do a fuzzy query with an analyzer you can already use the match query with the fuzziness parameter: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html#query-dsl-match-query-fuzziness
Though I agree that analysis and fuzziness can produce strange things, some warnings in the docs (of the match query) could be useful.

**Comment by jimferenczi** [comment]
... and the Levenshtein distance of "darcy" and "Marcy" is 1 so your example should return both results ;)

**Comment by danielmitterdorfer** [comment]
Ah, changing the example strings really bit me. If you index "Trezy" and "Trezi" and search for "Trezy" you will get back only one hit: "Trezy".

**Comment by danielmitterdorfer** [comment]
So based on the discussion so far I'd suggest we improve the docs for fuzzy queries.

**Comment by danielmitterdorfer** [comment]
We discussed this issue on FixItFriday and decided to go for option 1.

The current plan is to deprecate fuzzy queries in 2.x. and to remove them in 3.0. We should clearly state in the docs we still support fuzziness in match queries and the completion suggester.

**Comment by danielmitterdorfer** [comment]
Changed the ticket title to reflect our decision in FixItFriday.

**Comment by danielmitterdorfer** [comment]
We deprecate fuzzy query with 3.0.0 (see #16211) and will remove it with 4.0.0.

**Comment by rjernst** [comment]
Why did this switch from deprecation in 2.x to 3.0?

**Comment by danielmitterdorfer** [comment]
The original intent was to deprecate it with 2.3 and remove it with 3.0 (which would have required two separate PRs) but Adrien suggested we remove it with 4.0 in #16121. To do this consistently with our development model, I redid the change on master for 3.0 in #16211. Before backporting it I approached Clint and he suggested that a deprecation period of a complete major version cycle is long enough. Hence, I did not backport to 2.x.

**Comment by dmr** [comment]
I like the fuzzy query but I understand the reasons to drop it. Will there be a plugin with that functionality or how can the functionality be achieved without fuzzy query?

**Comment by danielmitterdorfer** [comment]
Hi @dmr,

currently, we have not planned to reimplement this is a plugin. The [fuzzy query docs for 3.0](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-fuzzy-query.html) are already available online, but I reproduce it here as a summary:

* There will be no exact replacement for string fields but note that we still support [fuzziness for match queries](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-match-query.html#query-dsl-match-query-fuzziness)
* For date and numeric fields you can use [range queries](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-range-query.html).

Does that help?

**Comment by dmr** [comment]
Thank you for the quick reply. You answer helps in the sense that I understand that there is no replacement but we have a few customers who started to like that feature.

I plan to keep up with elasticsearch versions so I need a replacement that I can offer our clients.

**Comment by clintongormley** [comment]
@dmr the replacement is the match query with the `fuzziness` parameter.  What functionality do you think will be missed?

**Comment by dmr** [comment]
I just didn't know about this parameter, thank you, fuzziness is perfect for me!

**Comment by cbuescher** [comment]
@danielmitterdorfer since you are assigned to this, is there already an open PR for this? If not, I can open one, I just started removing `fuzzy` on master because it has some deprecation comments and came across this issue.

**Comment by danielmitterdorfer** [comment]
@cbuescher No, I didn't start with this yet. Go ahead. :)

**Comment by javanna** [comment]
I came up with a PR for this, but it turns out that we may have to discuss it again. See https://github.com/elastic/elasticsearch/pull/21851#issuecomment-263559249 . Marking for discussion. We have to go back and un-deprecate if we want to keep this query around.

**Comment by danielmitterdorfer** [comment]
@javanna As Clint has mentioned in https://github.com/elastic/elasticsearch/pull/21851#issuecomment-263576787, we only considered `fuzzy` queries (on top-level) in our original discussion but did not think about `fuzzy` queries as part of `span` queries. IIRC within the scope that we discussed, we did not find compelling reasons to keep `fuzzy` around and that's why we decided to remove it. If we want to keep the functionality mentioned in the review of #21851, then we should undeprecate it. I hope that sheds some light on this issue.

**Comment by clintongormley** [comment]
The `fuzzy` query today falls under the section called [Term level queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/term-level-queries.html) which explains that the queries in that section are all low level term-based queries that don't use analysis.
We could possibly reiterate that point on the fuzzy query page itself, and point people to the match query with fuzziness instead.

But given that the match query can't be used in span queries where the fuzzy query CAN be used, I think we have no option but to keep it.

**Comment by danielmitterdorfer** [comment]
We discussed this again in Fix-It Friday and will it un-deprecate it for the reasons that Clint has stated above.
