### ISSUE TITLE
"french" pre-configured language analyzer wrong about elision

### ISSUE THREAD

**Issue by damienalexandre** [elastic/elasticsearch#15774]
Elasticsearch come with pre-configured language analyzer and I think [the :fr:  french one](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/analysis-lang-analyzer.html#french-analyzer) is wrong.

Filters are in this order:

- "french_elision" (configured with "d", "c", "jusqu", "lorsqu", "puisqu"...)
- "lowercase"
- "french_stop"
- "french_stemmer"

But, as "french_elision" is not case insensitive, prefix may be ignored if they have an uppercase letter.

- So the sentence `Jusqu'où aller ?` gives two tokens: `jusqu'ou` and `aler`.
- If we inverse "french_elision" and "lowercase", we get: `où` and `aler`.

Here is a gist to play: https://found.no/play/gist/27c387bf6e6e7e064b1b#analysis

I can't think of any good reason behind this order, but I'm no expert in language analysis :neckbeard: 
I wish I had reported this issue before 2.0, but anyway, hope it can be fixed in the future. 

Cheers!

**Comment by jpountz** [comment]
+1

**Comment by jpountz** [comment]
Actually I think we need to fix the docs to replace:

```
        "french_elision": {
        "type":         "elision",
            "articles": [ "l", "m", "t", "qu", "n", "s",
                          "j", "d", "c", "jusqu", "quoiqu",
                          "lorsqu", "puisqu"
                        ]
        }
```
with
```
        "french_elision": {
        "type":         "elision",
            "articles": [ "l", "m", "t", "qu", "n", "s",
                          "j", "d", "c", "jusqu", "quoiqu",
                          "lorsqu", "puisqu"
                        ],
            "articles_case": true
        }
```
which is how this analyzer is defined in Lucene.

**Comment by damienalexandre** [comment]
Right! Just tested on a fresh ES 2.1, the core "french" analyzer is fine :tada: 

Glad it's only a documentation issue :relaxed: Didn't notice before the core "french" was ok because I  always tweak analyzers (to add come icu filters / tokenizer, etc) using the doc as a bootstrap.

I would be glad to send a PR if you want :+1:

**Comment by jpountz** [comment]
@damienalexandre that would be great!
