### ISSUE TITLE
Creating a snapshot of a single index does not work properly from node

### ISSUE THREAD

**Issue by exinferis** [elastic/elasticsearch#15770]
I try to create a snapshot of a single index using the ```indices``` parameter within the official node.js module, but I always end up with getting a complete snapshot of the cluster.

```coffeescript
@es.snapshot.create( 
   { snapshot: "#{uid}", indices: index, repository: @config.esrepo, include_global_state: false }
   ( err, created ) -> 
      ...
      ...
)
```

The above coffeescript transiling to something like this:

```javascript
_this.es.snapshot.create({
            snapshot: uid,
            indices: index,
            repository: _this.config.esrepo,
            include_global_state: false
          }, function(err, created) {
              .....
          });
```

Is this due to a bug or missing feature in the es client? The ```indices``` parameter is being described within the [API](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/modules-snapshots.html#_snapshot), but no within the [JS client API](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-snapshot-create) ...?

**Comment by clintongormley** [comment]
It looks like you are missing the `body` parameter in your JS request
