### ISSUE TITLE
Deleted document count and total space usage is growing

### ISSUE THREAD

**Issue by binishabraham** [elastic/elasticsearch#15778]
Elastic search version elasticsearch-1.7.0

Before executing optimization
GET _cat/indices?v
health status index               pri rep docs.count   docs.deleted store.size pri.store.size
green  open   indexname       5   1   12451854      3122422    101.6gb         50.5gb

After executing the following command 

POST indexname/_optimize?only_expunge_deletes=true
health status index                pri rep docs.count   docs.deleted store.size pri.store.size
green  open   indexname       5   1   12451854      575567    68.6gb         34.5gb

Why the space reclaiming is not happening while deleting it?

I am using JDBC importer (elasticsearch-jdbc-1.7.0.0) to recreate the document instead of updating. It recreates around 1500000 documents in  a day.

I was able to get much better performance after the executing the above step for optimization

**Comment by jasontedor** [comment]
The handling of deletes in Elasticsearch is covered well in [Lucene's Handling of Deleted Documents](https://www.elastic.co/blog/lucenes-handling-of-deleted-documents) on the Elastic engineering blog.
