### ISSUE TITLE
3.0 Mapping API field wildcard not working?

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch#15782]
I'm surprised by the difference between the output of these two commands. Is that a bug?

```sh
curl 'http://localhost:9200/logstash-*/_mapping?pretty' # returns all fields
curl 'http://localhost:9200/logstash-*/_mapping/field/*?pretty' # returns nothing
```

**Comment by jpountz** [comment]
It looks like one. I'll dig.

**Comment by jpountz** [comment]
@spalger I could not reproduce the issue on a fresh master build, do you have steps that I could follow to reproduce it?

**Comment by spalger** [comment]
Hmm, I suppose it's possible that the reason I wasn't seeing any fields is because I didn't have any documents indexed... That's the only way that I can reproduce that now....

**Comment by jpountz** [comment]
@spalger Then may I close?

**Comment by spalger** [comment]
Thanks @jpountz
