### ISSUE TITLE
High heap usage on get field mapping API

### ISSUE THREAD

**Issue by Mogztter** [elastic/elasticsearch#15789]
Environment:

 * 62 indices
 * 50+ types
 * Java 7.0_67
 * JVM arguments `-Xms8G -Xmx8G`
 * Elasticsearch version 1.7.5 (branch 1.7)

Steps:

 1. Start Elasticsearch
 2. Execute the following query `http://localhost:9200/logstash/_mapping/field/*` (produced by Kibana)
 3. Wait the response
 4. Run the same query again

Here is the result (screenshot from JVisualVM);
![mapping-memory-leak-confirmed](https://cloud.githubusercontent.com/assets/333276/12142867/b68a64c0-b47b-11e5-9f04-5fefbe9b6754.JPG)

As you can see the first execution of the query took about 1G of memory and the second execution of the query took about 2.5G (more than 2 times more memory than the first execution).
I tried to force GC but no memory is free up.

Using MAT, I can see that the memory is filled with `FieldMappingMetaData`.
I'm not sure if this is intended but I `GetFieldMappingsResponse` keeps a reference of the mapping: https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/action/admin/indices/mapping/get/GetFieldMappingsResponse.java#L39

I didn't try on Elasticsearch 2.x but the code is more or less the same.

**Comment by jpountz** [comment]
> I tried to force GC but no memory is free up.

This could be because elasticsearch disables explicit GCs. What happens if you keep calling this API, does Elasticsearch run out of memory?

**Comment by Mogztter** [comment]
> This could be because elasticsearch disables explicit GCs. What happens if you keep calling this API, does Elasticsearch run out of memory?

Yes, if I execute the query one more time, Elasticsearch hangs forever. Most of the time when there's activity on the node, Elasticsearch terminates abruptly (OutOfMemory).

**Comment by Mogztter** [comment]
If you want I can upload a heap dump

**Comment by jpountz** [comment]
That might help, thanks.

**Comment by Mogztter** [comment]
Here's a hprof file: https://drive.google.com/file/d/0B7t8xIk1T8NjejFLVzY1Z1ZzTDg/view?usp=sharing (~ 3Go)

**Comment by Mogztter** [comment]
I removed all breakpoints on Intellij and now the graph looks like this:
![mapping-memory-garbage](https://cloud.githubusercontent.com/assets/333276/12197649/2399269e-b609-11e5-9439-9e305104f8d0.JPG)
_somehow the debugging on Intellij blocked the garbage collection_

Still the memory usage is huge and can threaten the stability of the cluster with big spike of heap used and concurrents queries can achieve the same result (ie. Elasticsearch hangs forever or becomes unresponsive for minutes):

![mapping-memory-unresponsive](https://cloud.githubusercontent.com/assets/333276/12197843/fc143a62-b60a-11e5-8ad8-061b6f8be46f.JPG)
_Elasticsearch was unresponsive between 13:17 and 13:22_

Is there a circuit breaker available to prevent this operation from causing an `OutOfMemoryError` ?

**Comment by s1monw** [comment]
@Mogztter thanks for the heapdump I looked at it and found on JNI Global references holding on to the memory, any chance you are running your JVM in debug mode? I also wonder if you can run with ` -Xcheck:jni` and separately can you try running this with the latest JVM ie a java 8 JVM? Are you using any kind of native plugins or something like this?

**Comment by s1monw** [comment]
ooh nevermind then I didn't see your latest reply!!!

**Comment by s1monw** [comment]
I looked at this again  with @jpountz and we found a smoking gun... @jpountz will take care of a fix. Thanks for opening this @Mogztter

**Comment by jpountz** [comment]
The issue appears to be that we over-allocate the data-structure that we use to store the serialized representation of the field mappings, which can become an issue if there are many fields. I'll look into it.

**Comment by s1monw** [comment]
@clintongormley I think we should make this a release blocker as well? @jpountz WDYT? this is 1.7.5

**Comment by jpountz** [comment]
We already need to make a 1.7.5 anyway because of the bitset cache bug so that works for me.

**Comment by s1monw** [comment]
@Mogztter once @jpountz has pushed #15864 to 1.7 can you give it a try just to confirm the situation is better after that?

**Comment by Mogztter** [comment]
@jpountz Thanks for the quick fix :+1: 
@s1monw Sure, unfortunately I won't be able to confirm the improvement before Tuesday.

**Comment by s1monw** [comment]
> @s1monw Sure, unfortunately I won't be able to confirm the improvement before Tuesday.

Tuesday is more than soon enough :) thanks

**Comment by jpountz** [comment]
The fix has been propagated to all branches.

**Comment by Mogztter** [comment]
@jpountz Thanks!
@s1monw Yes the situation is *way* better:

![heap-after](https://cloud.githubusercontent.com/assets/333276/12258694/c89e80a8-b910-11e5-81fe-2550b2ced052.JPG)

Now the memory taken is about 250 Mo and stable on each call :+1:

**Comment by jpountz** [comment]
:+1:  Thanks a lot for confirming.

**Comment by s1monw** [comment]
awesome! thanks for reporting @Mogztter

**Comment by Mogztter** [comment]
@jpountz Hello Adrien, I saw that all `v1.7.5` issues are closed :+1: any ETA for Elasticsearch 1.7.5 ? thanks

**Comment by jpountz** [comment]
I can't promise anything but it should go out next week.

**Comment by Mogztter** [comment]
Yay 1.7.5 is out, upgrading now, thanks :smile:

**Comment by s1monw** [comment]
@Mogztter thank YOU!
