### ISSUE TITLE
IndexShardRoutingTable#activeShards should include relocation targets

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#15798]
Currently `IndexShardRoutingTable#activeShards` does not include relocation targets. This means that when a relocation target is needed (e.g., [in `TransportReplicationAction`](https://github.com/elastic/elasticsearch/blob/3b192cfc7488a02387501a598fe177234d4149ae/core/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java#L851)) we have to create the target relocation shard object. Instead, if `IndexShardRoutingTable#activeShards` included relocation targets, that could be cached and we can simplify places where the relocation target is needed.

Relates #15791 via a [comment](https://github.com/elastic/elasticsearch/pull/15791/files#r48978243) from @bleskes.

**Comment by ywelsch** [comment]
The relocation target shard is now auto-cached by the relocation source object.
