### ISSUE TITLE
Allow Filter Cache to be disabled by index

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#15802]
For most users, having the filter cache being specified across the nodes makes a ton of sense, particularly for hot/cold architectures.

However, at extreme scales, this is sometimes not enough unless you go the extra mile with your cluster to setup a hot/warm/cold (ad nauseam) setup to allow an extra tier(s) of nodes to setup. For a lot of use cases, this extra level of node management adds a lot of complexity that only grows with the size of the cluster.

With that in mind, it would be useful to restrict (on/off only) the memory caches that get used by any index. This would enable curation to disable caches for any given index as it ages, thereby reducing its overall burden as a step before closing them.

**Comment by clintongormley** [comment]
I understand each word individually, but I have no idea what they mean together :)  What exactly are you suggesting?

**Comment by pickypg** [comment]
Allow an index to disable explicitly disable caching, so that old indices can avoid caching.

**Comment by clintongormley** [comment]
Discussed in FixItFriday - we should add an index-level setting allowing the query cache to be disabled per index.

**Comment by jpountz** [comment]
This is actually already possible to do by setting `index.queries.cache.type: none` in the index settings. Should we just document it?

**Comment by pickypg** [comment]
Yeah, I think that covers it pretty well. :)

**Comment by jpountz** [comment]
Finally we decided to go with `index.queries.cache.enabled: false`.
