### ISSUE TITLE
Installation Elasticsearch 2.1.1 as root 

### ISSUE THREAD

**Issue by satapsa** [elastic/elasticsearch#15804]
I installed Elasticsearch 2.1.1 as root  and getting error

"Exception in thread "main" java.lang.RuntimeException: don't run elasticsearch as root"

If I create a ES_USER=esuser  - what should be the group permission etc it should have so that I can start od Elasticsearch as a ES_USER.

Can someone provide a sample ES_USER ?

**Comment by jpountz** [comment]
Please ask such questions at http://discuss.elastic.co (with more details if possible, in particular how you installed elasticsearch). We only use github issues for bugs / feature requests.
