### ISSUE TITLE
Dynamic Analyzer in Search

### ISSUE THREAD

**Issue by rrecacharedk** [elastic/elasticsearch#15818]
Dear ElasticSearch Team,

I have a custom analyzer ( custom_asciifolding is "mapping" type => ["á=>a", "é=>e" ... etc] ): 

... "analyzer": {
   "standard_custom": {
        "type": "custom",
        "char_filter": ["custom_asciifolding"],
        "filter": ["lowercase"],
        "tokenizer": "standard"
} ...

I have a contact register indexed with name property (value: Rubén Recacha)

When I put analyzer parameter in query string, does not work correctly:

{
  "query": {
    "query_string": {
      "query": "ruben*",
      "analyzer": "standard_custom"
    }
  }
}

==> 0 results

{
  "query": {
    "query_string": {
      "query": "rubén*",
      "analyzer": "standard_custom"
    }
  }
}

==> 1 results

It is a bug?

How I could to do a query changing the analyzer dynamically?

Thank you very much,

Best Regards,
Rubén Recacha.

**Comment by rrecacharedk** [comment]
I use the version 1.4.4 but I think is not relevant in this case.

Regards.

**Comment by dadoonet** [comment]
Please use discuss.elastic.co.

Wildcards are not analyzed. Have a look at https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html and `analyze_wildcard` option in case it helps.

If you have any other question, please join us on discuss.
