### ISSUE TITLE
Remove support for GET _aliases

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#15817]
`GET /{index}/_aliases/{name}` is supposed to filter aliases by index and/or by name.

But if you want to filter only by alias `name`, it gives you back all indices:

```sh
curl -XDELETE localhost:9200/foo,bar?pretty
curl -XPUT localhost:9200/foo?pretty
curl -XPUT localhost:9200/bar?pretty
curl -XPOST localhost:9200/_aliases?pretty -d '{
    "actions" : [
        { "add" : { "index" : "foo", "alias" : "myalias" } }
    ]
}'

# Correct
curl -XGET localhost:9200/_aliases?pretty
# {
#   "bar" : {
#     "aliases" : { }
#   },
#   "foo" : {
#     "aliases" : {
#       "myalias" : { }
#     }
#   }
# }

# Correct
curl -XGET localhost:9200/foo/_aliases?pretty
# {
#   "foo" : {
#     "aliases" : {
#       "myalias" : { }
#     }
#   }
# }

# Incorrect
curl -XGET localhost:9200/_aliases/myalias?pretty
# {
#   "bar" : {
#     "aliases" : { }
#   },
#   "foo" : {
#     "aliases" : {
#       "myalias" : { }
#     }
#   }
# }


# Correct
curl -XGET localhost:9200/_alias?pretty
# {
#   "bar" : {
#     "aliases" : { }
#   },
#   "foo" : {
#     "aliases" : {
#       "myalias" : { }
#     }
#   }
# }

# Correct
curl -XGET localhost:9200/foo/_alias?pretty
# {
#   "foo" : {
#     "aliases" : {
#       "myalias" : { }
#     }
#   }
# }

# Correct
curl -XGET localhost:9200/_alias/myalias?pretty
# {
#   "foo" : {
#     "aliases" : {
#       "myalias" : { }
#     }
#   }
# }
```

We don't document `GET _aliases` anymore so may be we should remove its support as we can do the same thing with `GET _alias` API.

Might be related to https://github.com/elastic/elasticsearch/issues/4743
Related to https://github.com/elastic/elasticsearch-js/issues/331

**Comment by clintongormley** [comment]
There used to be a difference between GET _alias and GET _aliases (the details of which escape me) which Kibana depended on, but I think this has been resolved.  @rashidkpc could you confirm?

**Comment by rashidkpc** [comment]
@spalger you were looking at this the other day. Where did we decide to go with it?

**Comment by spalger** [comment]
I was looking at this from the perspective of removing it from the client, not sure how it relates to Kibana.

**Comment by javanna** [comment]
this appears to be a duplicate of #13906. +1 for removing asap!

**Comment by dadoonet** [comment]
Thank you @javanna. For whatever reason I did not find this issue. Closing this then.
