### ISSUE TITLE
Correct documentation of discovery.zen.ping.unicast.hosts regarding support for port ranges

### ISSUE THREAD

**Issue by drekbour** [elastic/elasticsearch#15816]
The documentation of discovery.zen.ping.unicast.hosts explicitly mentions port-ranges but fails to mention that they are _not supported_ and only the first port is checked.
There are several Issues/PRs relating to changing this but none have made it yet so please document that port-range format is allowed but not supported and that if a user wishes to address multiple ports they must do explicitly

```
server1:9300,server1:9301
```

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-zen.html
#8833 will allow the first two ports to be scanned. Older items relating to this are #99, #7561, #7090, #12999, elastic/elasticsearch-cloud-aws#197

**Comment by dadoonet** [comment]
@drekbour Thanks for opening this issue. Do you want to contribute a doc PR to fix that?

**Comment by clintongormley** [comment]
We should probably also throw an exception when a user specifies a port range.

**Comment by clintongormley** [comment]
I've updated the documentation, but we should still throw an exception when the user specifies a port range.

**Comment by clintongormley** [comment]
@nikhilchudekar I can't assign to people outside the organisation, but you're welcome to work on it and to submit a PR referencing this issue eg `closes #15816` in the description

**Comment by nikhilchudekar** [comment]
will do, thanks.

**Comment by nikhilchudekar** [comment]
I see a PR that's already addressing this (though it is way back in April 2017). Looks like it has been reviewed, and all that is left is pushing the fix to the repo. @clintongormley I'll move on to something else.

**Comment by tbrooks8** [comment]
We are going to open a separate issue for the "throwing an exception". This issue shows that there are related PRs that have been merged. But non of those PRs appear to have been merged into the `elastic/elasticsearch` repository.

**Comment by DaveCTurner** [comment]
The docs are long-fixed, resolving the headline part of this issue, and I've opened https://github.com/elastic/elasticsearch/issues/40786 for the remaining part.
