### ISSUE TITLE
Remove deprecated ec2 proxy settings

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#15829]
The following settings have been deprecated for a while and can likely be removed in 3.0:

* cloud.aws.proxy_host --> cloud.aws.proxy.host
* cloud.aws.proxy_port --> cloud.aws.proxy.port
* cloud.aws.ec2.proxy_host --> cloud.aws.ec2.proxy.host
* cloud.aws.ec2.proxy_port --> cloud.aws.ec2.proxy.port

**Comment by dadoonet** [comment]
These settings have been deprecated in 2.2.0 which has not been released yet. See #15352

That being said, I agree that we can potentially remove these settings in master branch.
