### ISSUE TITLE
When using a whitespace tokenizer the stop words filter doesn't work

### ISSUE THREAD

**Issue by imranazad** [elastic/elasticsearch#15835]
When using the whitespace tokenizer, the stop words filter doesn't work. Here are the CURL commands to replicate:

			PUT /my_index
			{
			  "settings": {
				"index": {
				  "number_of_shards": 1,
				  "analysis": {
					  "analyzer": {
						 "fulltext":{
						"type":"custom",
						"tokenizer":"whitespace",
						"filter": ["english_stop"]
					  }
					  },
					 "filter":{
						"english_stop":{
						   "type":"stop",
						   "stopwords":"_english_"
						}
					  }
					 }
				  }
				}
			  }
			}

I need to be able to use the whitespace tokenizer because I'm also using the word_delim filter which turns terms like "wi-fi" to wifi, if I use the standard tokenizer, I will lose this ability.

**Comment by s1monw** [comment]
please use our discuss forum for questions like this - https://discuss.elastic.co/

**Comment by imranazad** [comment]
@s1monw I think this is a technical issue, the stop words filter just simply will not work when using the whitespace tokenizer.

**Comment by s1monw** [comment]
it works as expected, whitespace tokenizer doesn't lowercase and stopwords are lowercased. please ask these questions on the discuss forjum

**Comment by imranazad** [comment]
@s1monw The issue isn't that the stopwords aren't lower cased the issue is that the stop words are not filtered when using the whitespace tokenizer.

**Comment by dakrone** [comment]
@imranazad what @s1monw is saying is that it may appear that stopwords are not being removed because the english stopwords list only includes words that are lowercase:

# Create an index

    DELETE /ws
    {}

    POST /ws
    {
      "settings": {
        "index": {
          "number_of_shards": 1,
          "number_of_replicas": 0,
          "analysis": {
            "analyzer": {
              "wsplusstop":{
                "type":"custom",
                "tokenizer":"whitespace",
                "filter": ["english_stop"]
              }
            },
            "filter":{
              "english_stop":{
                "type":"stop",
                "stopwords":"_english_"
              }
            }
          }
        }
      },
      "mappings": {
        "doc": {
          "properties": {
            "body": {
              "type": "string",
              "analyzer": "wsplusstop"
            }
          }
        }
      }
    }

# Index docs

    POST /ws/doc/1
    {"body": "bill the bat"}

    POST /ws/doc/2
    {"body": "Bob The Builder"}

    POST /ws/_refresh
    {}

Results:

    {"_index":"ws","_type":"doc","_id":"1","_version":1,"_shards":{"total":1,"successful":1,"failed":0},"created":true}
    {"_index":"ws","_type":"doc","_id":"2","_version":1,"_shards":{"total":1,"successful":1,"failed":0},"created":true}
    {"_shards":{"total":1,"successful":1,"failed":0}}

# See how the data is analyzed with `fielddata_fields`

    GET /ws/_search?pretty
    {
      "query": {
        "match_all": {}
      },
      "fielddata_fields": ["body"]
    }

    {
      "took" : 40,
      "timed_out" : false,
      "_shards" : {
        "total" : 1,
        "successful" : 1,
        "failed" : 0
      },
      "hits" : {
        "total" : 2,
        "max_score" : 1.0,
        "hits" : [ {
          "_index" : "ws",
          "_type" : "doc",
          "_id" : "1",
          "_score" : 1.0,
          "_source":{"body": "bill the bat"},
          "fields" : {
            "body" : [ "bat", "bill" ]
          }
        }, {
          "_index" : "ws",
          "_type" : "doc",
          "_id" : "2",
          "_score" : 1.0,
          "_source":{"body": "Bob The Builder"},
          "fields" : {
            "body" : [ "Bob", "Builder", "The" ]
          }
        } ]
      }
    }

Notice the lowercase `the` was removed but the capitalized `The` was not.

In the future though, as @s1monw mentioned, please ask these types of questions
in the discussion forums.

**Comment by imranazad** [comment]
@dakrone Ah I see. Thank you, yes of course, absolutely.
