### ISSUE TITLE
Proposal: Use -Xlint:-serial everywhere

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#15847]
So far as I can tell `-Xlint:serial` warns you about not defining `serialVersionUID` on classes that implement `Serializable`. For the most part for us that is just `Exception`s since we don't use Java serialization. I think we're ok with not implementing `serialVersionUID` so I think we should just turn that one off on all projects rather than on a case by case basic like we do now.

A third option is to `@SuppressWarnings` about it on every exception but I don't like that idea much.

**Comment by jasontedor** [comment]
+1 to use `-Xlint:-serial`.

**Comment by bleskes** [comment]
Exceptions don't use java serialization anymore as well.  It looks like we only use Seriazlizable in injection code now. Does that fail linting? I also wonder if we should add serializable to the fobidden API..

**Comment by s1monw** [comment]
++
