### ISSUE TITLE
[Ingest] Move pipelines from .ingest index to cluster state?

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#15842]
Right now the pipelines are stored in the .ingest index, but maybe we can move the pipeline configuration to the cluster state? This does have advantages:
* The whole configuration management we have to pushes the pipelines to nodes can be removed and instead ingest can rely on cluster state updates.
* No need to ensure that mapping/settings are applied when the ingest index is created  or manage an index template. Because we are in control what goes into the cluster state via the put and delete pipeline apis.

Beyond the source of the pipeline nothing else is stored (inverted index or docvalues) and the cluster state can hold that too. Also it is likely that there will not be many pipelines (>1000).

Before this was tricky because how ingest was designed: 
* pipelines changes were propagated asynchronously to other ingest nodes. 
* ingest was a plugin and may not be installed on the elected master node.

**Comment by martijnvg** [comment]
After discussing this question there is another requirement that should be taken into account, namely security. Not all pipelines may be used by everyone and if pipeline configuration would be moved to the cluster state there wouldn't be a mechanism how security can easily be enforced. If pipeline configuration is in an index security can be enforced.

**Comment by clintongormley** [comment]
Discussing this online we decided not to move pipelines to the cluster state

**Comment by martijnvg** [comment]
Reopening, using the cluster state to store pipelines makes the ingest code much cleaner and simpler. If security is needed at some point then this can be achieved by adding this to the cluster state infrastructure.
