### ISSUE TITLE
licence-2.1.1.zip FileNotFound

### ISSUE THREAD

**Issue by SpaceShipDev** [elastic/elasticsearch#15840]
`./bin/plugin install -v licence`

> -> Installing licence...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/licence/2.1.1/licence-2.1.1.zip ...
Failed: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/licence/2.1.1/licence-2.1.1.zip]; nested: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/licence/2.1.1/licence-2.1.1.zip];
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information

Nested link reveals: -
This XML file does not appear to have any style information associated with it.

**Comment by djschny** [comment]
It appears license is misspelled. Try rerunning as:

`./bin/plugin install -v license`

**Comment by SpaceShipDev** [comment]
This is horrific, lets pretend this never happened.
