### ISSUE TITLE
Switch from MSOffice to Office properties

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#15843]
The mapper attachement plugin uses `MSOffice` properties which are apparently deprecated and have been replaced by Tika's `Office` properties. I'm not sure why, but whatever. Anyway, we should figure out the new right way before we suffer from more bit rot.

**Comment by talevy** [comment]
This has been updated in Ingest Node. As of this commit for Ingest Node https://github.com/elastic/elasticsearch/commit/0d4711c2fcff8fa1076f4631c036a0efdebb6a9f#diff-2887f6c836caf14693b187e9f9d09c00R64. 

Closing since this is not relevant to Ingest Node
