### ISSUE TITLE
Remove deprecated script parsing

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#15849]
The notes in the code say that the script parsing will go in 2.0 but its still there. I mean `SCRIPT_LANG`, `SCRIPT_FILE`, `SCRIPT_ID`, and `SCRIPT_INLINE`.

**Comment by nik9000** [comment]
@colings86 I see your name coming up in git-blame on this code. Is this something you can do easily? Like, if its not that much work.

**Comment by clintongormley** [comment]
Related to https://github.com/elastic/elasticsearch/issues/13729

**Comment by clintongormley** [comment]
Duplicate of https://github.com/elastic/elasticsearch/issues/13729
