### ISSUE TITLE
Migrate from RandomizedTest.isNightly()

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#15844]
Nightly looks like it is [going away](https://github.com/randomizedtesting/randomizedtesting/issues/218). We should migrate away from it before it disappears out from under us.

**Comment by javanna** [comment]
I first looked into adapting to this change, but it turns out the method is staying after all. See https://github.com/randomizedtesting/randomizedtesting/issues/218#issuecomment-252193168 .
