### ISSUE TITLE
Minimum_should_match for one word query

### ISSUE THREAD

**Issue by jzbahrai** [elastic/elasticsearch#15858]
The following is a search query. The term full_name uses a synonym analyzer. 
The synonym expand file has the synonym: rice,arroz. 
Now if we run the validate query we get the below results:

    GET /products_v2/product/_validate/query?explain
    {
      "query": {
        "bool": {
          "must": [
            {
              "match": {
                "full_name": {
                  "query": "rice",
                  "fuzziness": 1,
                  "minimum_should_match": "3<90%"
                }
              }
            }
          ],
          "should": [
            {
              "match_phrase": {
                "name": {
                  "query": "rice",
                  "slop": 50
                }
              }
            }
          ]
        }
      }
    }

    {
       "valid": true,
       "_shards": {
          "total": 1,
          "successful": 1,
          "failed": 0
       },
       "explanations": [
          {
             "index": "products_v2",
             "valid": true,
             "explanation": "filtered(+((full_name:arroz~1 full_name:rice~1)~2) (name:arroz name:rice))->cache(_type:product)"
          }
       ]
    }

Both rice and arroz are position 1. The minimum_should_match doesn't get applied to the position but the number of words in position 1.

Let's say the synonym file has another synonym :  Brown Sugar, brownsugar.
The following is the result of the validate query calling brownsugar

    {
       "valid": true,
       "_shards": {
          "total": 1,
          "successful": 1,
          "failed": 0
       },
       "explanations": [
          {
             "index": "products_v4",
             "valid": true,
             "explanation": "filtered(+(((full_name:brownsugar~1 full_name:brown~1) full_name:sugar~1)~2) name:\"(brownsugar brown) sugar\"~50)->cache(_type:product)"
          }
       ]
    }

In this case the minimum to match is applied based on positions. brownsugar and brown are position 1, sugar is position 2. The minimum_should_match gets applied as 2.

If minimum_should_match gets applied based on the number of positions there are, I believe the above example for rice should have minimum_should_match should be 1 and not 2. This is a problem in the way ES handles minimum_should_match for one word synonyms.

**Comment by clintongormley** [comment]
Simpler recreation here:

    PUT t
    {
      "settings": {
        "analysis": {
          "analyzer": {
            "syns": {
              "tokenizer": "standard",
              "filter": [
                "lowercase",
                "syns"
              ]
            }
          },
          "filter": {
            "syns": {
              "type": "synonym",
              "synonyms": [
                "arroz,rice",
                "brown sugar,brownsugar"
              ]
            }
          }
        }
      },
      "mappings": {
        "t": {
          "properties": {
            "full_name": {
              "type": "string",
              "analyzer": "syns"
            }
          }
        }
      }
    }
    
    GET t/_validate/query?explain
    {
      "query": {
        "match": {
          "full_name": {
            "query": "rice",
            "minimum_should_match": 2
          }
        }
      }
    }
    
    GET t/_validate/query?explain
    {
      "query": {
        "match": {
          "full_name": {
            "query": "brown sugar",
            "minimum_should_match": 2
          }
        }
      }
    }
    
Not sure what can be done for the second multi-word synonym example (as multi-word synonyms are really problematic) but it does feel like the first example should not apply the min-should-match to stacked tokens.

@mikemccand @jpountz what do you think=

**Comment by jpountz** [comment]
+1

**Comment by jimferenczi** [comment]
@clintongormley I changed the behavior of minimum should match to fix this issue: https://github.com/elastic/elasticsearch/issues/15521. In 2.2 and master we always honor the value even if the final number of optional clauses (after expansion) is smaller. This is why your first example returns no result. For the multi word synonym example the problem is similar but the resolution would be different simply because the generated query is wrong:
````
"explanation": "((full_name:brown full_name:brownsugar) full_name:sugar)"
````

**Comment by jpountz** [comment]
@jimferenczi Maybe I'm the one confused but I think the issue is different here: we want the number of SHOULD clauses to be equal to the number of unique positions instead of the number of tokens?

**Comment by jzbahrai** [comment]
I am also a little unsure as to what @jimferenczi is saying. I want the minimum_should_match for rice,arroz to be equal to 1 as it should be based on the number of positions (in this case 1), but it is 2. It is correct for the multiword brown sugar, brownsugar as it is 2 and the number of positions in that case is 2.

**Comment by jimferenczi** [comment]
@jzbahrai @jpountz I just answered regarding @clintongormley's recreation where the minimum should match is statically set to 2. I agree that there is a bug with the example used by @jzbahrai where minimum should match is set with "3<90%". I'll take a look.

**Comment by jimferenczi** [comment]
The bug is when there is only one position but multiple clauses in this position. it is related to a small optimization that is done to reduce the number of clauses when there is only one position. In such case we build only one level of boolean query and the optional clauses are all at the root level, this level is then used to compute the number of optional clauses in the query. For instance the query "rice" is expanded into:
(rice arrow) => 2 optional clauses at the root level.
but to correctly compute the number of positions we should generate another level to indicate that the query contains only one position:
((rice arrow)) => 1 optional clause at the root level and 2 optional clauses at the inner level.
I'll work on a fix tomorrow.

**Comment by jimferenczi** [comment]
The bug/problem is at the Lucene level. I opened https://issues.apache.org/jira/browse/LUCENE-6972, @jpountz can you take a look ?
