### ISSUE TITLE
RED in Elasticsearch status

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch#15878]
Why Elasticsearch in a determinated moment pass to red state whithout an aparent problem?

I have the heap size well dimensionated and after I have three nodes that they are communicating between them with Unicast.

It was working for a month without any problem and it was indexing all time.

**Comment by clintongormley** [comment]
The place to look for the answer is in the logs.  Questions like these should be asked on the forum http://discuss.elastic.co/
