### ISSUE TITLE
Scripting plugin guidance seems out of date

### ISSUE THREAD

**Issue by NDevox** [elastic/elasticsearch#15883]
The links currently point to deprecated repositories (they are noted to only receive bugfixes).

example:

https://www.elastic.co/guide/en/elasticsearch/reference/2.1/modules-scripting.html

Python points to:
https://github.com/elastic/elasticsearch-lang-python

which in turn tells you to look at:
https://github.com/elastic/elasticsearch/tree/master/plugins/lang-python

I appreciate the links might still point there due to the guidance for installing the plugins being held there. But if they are deprecated isn't it better to move the guidance and redirect the links to the current folder?

As an aside, MVEL is still on the master branch despite being removed from 2.0 onwards. Should this be kept?

**Comment by NDevox** [comment]
First PR failed the CLA check so signed and opened another.

**Comment by NDevox** [comment]
Worth noting that the readme at the deprecated repo (https://github.com/elastic/elasticsearch-lang-python) talks about building from source and points to out-of-date resources so is fairly misleading. Especially considering this repo hasn't seen development for 4 months whereas the up-to-date repo has seen development in the last few days.

**Comment by clintongormley** [comment]
I'd remove the MVEL link as well - it's long gone :)

thanks

**Comment by NDevox** [comment]
removed in pull #15885

**Comment by NDevox** [comment]
Closed by #15885
