### ISSUE TITLE
Elasticsearch windows service crashes when stopping it

### ISSUE THREAD

**Issue by famini** [elastic/elasticsearch#15889]
When stopping Elasticsearch 2.1 windows service on windows 2008 R1, windows 2008 R2' windows 2012 and windows10, the following Application Error is logged in the Windows event log indicating an access violation in Java. I stopped it both using the service.bat file, and from services.msc. 
As you can see below I am using jdk 8 update 45.
From what I have seen Elasticsearch keeps working fine when starting it again, but this crash is still not supposed to happen.

There is also an open question about it in stackoverflow - http://stackoverflow.com/questions/28966966/elasticsearch-shutdown-crash-when-run-as-windows-service

Faulting application name: elasticsearch-service-x64.exe, version: 1.0.15.0, time stamp: 0x51543b9d
Faulting module name: jvm.dll, version: 25.45.0.2, time stamp: 0x55428cbf
Exception code: 0xc0000005
Fault offset: 0x0000000000213298
Faulting process id: 0x2b7c
Faulting application start time: 0x01d14c83385f6463
Faulting application path: C:\temp\elasticsearch-2.1.1\elasticsearch-2.1.1\bin\elasticsearch-service-x64.exe
Faulting module path: c:\Program Files\Java\jdk1.8.0_45\jre\bin\server\jvm.dll
Report Id: 860f851d-b5d6-46ff-8a83-c05f54445d92
Faulting package full name: 
Faulting package-relative application ID:

**Comment by clintongormley** [comment]
Based on http://www.oracle.com/technetwork/java/javase/crashes-137240.html this sounds like a bug in the JVM.  I can only suggest upgrading the JVM, and if this issue persists, reporting the issue to Oracle.

**Comment by prabhurajreddy** [comment]
The issue still persists in the latest elastic search 5.2.2 and jdk1.8.0_91. It crashes during the service stop. 
Below is the windows error 

Faulting application name: elasticsearch-service-x64.exe, version: 1.0.15.0, time stamp: 0x51543b9d
Faulting module name: jvm.dll, version: 25.71.0.1, time stamp: 0x56fe319b
Exception code: 0xc0000005
Fault offset: 0x0000000000215498
Faulting process id: 0xad38
Faulting application start time: 0x01d29341d48a1bf5
Faulting application path: C:\temp\elasticsearch-5.2.2\bin\elasticsearch-service-x64.exe
Faulting module path: C:\Program Files\Java\jdk1.8.0_91\jre\bin\server\jvm.dll
Report Id: 5c68cf80-260c-4f9c-a8fb-e4b6dc0dc69f
Faulting package full name: 
Faulting package-relative application ID:

**Comment by mgruben** [comment]
Ditto:

```
Faulting application name: elasticsearch-service-x64.exe, version: 1.0.15.0, time stamp: 0x51543b9d 
Faulting module name: jvm.dll, version: 24.65.0.4, time stamp: 0x53d28874 
Exception code: 0xc0000005 
Fault offset: 0x00000000001d0128 
Faulting process id: 0x610 
Faulting application start time: 0x01d27e5ae4eb53d3 
Faulting application path: C:\Program Files\AccessData\ElasticSearch\bin\elasticsearch-service-x64.exe 
Faulting module path: C:\Program Files\AccessData\ElasticSearch\jdk\jre\bin\server\jvm.dll 
Report Id: cb60e70b-0aec-11e7-8103-000e1eb547e0 
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by jasontedor** [comment]
@mgruben You're using a Java 7 runtime (I can tell from the Hotspot version 24.65.0.4). Also, it's best to post topics on the [forum](https://discuss.elastic.co) for general help and questions rather than posting on closed issues.

**Comment by mgruben** [comment]
@jasontedor Noted, I'll work with our vendor to see if we can upgrade to the most current JVM (currently 8u121).  
Thanks!

**Comment by hordemark** [comment]
@mgruben  I encountered this issue, 
My elasticsearch is 1.7.3 and JRE is 1.8.131. 
But still have problem. Do you have a workaround?
Thanks!

**Comment by clintongormley** [comment]
> My elasticsearch is 1.7.3 and JRE is 1.8.131.
But still have problem. Do you have a workaround?

Upgrade
