### ISSUE TITLE
histogram query results a deadlock in elasticsearch

### ISSUE THREAD

**Issue by puneetjaiswal** [elastic/elasticsearch#15902]
ElasticSearch version 1.7.3 running with Oracle Java 8.

When ran this query 
```
 {
  "size" : 1000,
  "query" : {
    "range" : {
      "eventTimestamp" : {
        "from" : 1452543896208,
        "to" : 1452544796208,
        "include_lower" : true,
        "include_upper" : true
      }
    }
  },
  "aggregations" : {
    "/series(eventtimestamp)" : {
      "date_histogram" : {
        "field" : "eventTimestamp",
        "interval" : "10ms",
        "min_doc_count" : 0,
        "order" : {
          "_key" : "asc"
        },
        "extended_bounds" : {
          "min" : 0,
          "max" : 1452544262018
        }
      }
    }
  }
}
```
ElasticSearch froze and observed a possible deadlock using yourkit. Filter is selected for 15 mins on a interval of 10ms. 
<img width="1380" alt="screen shot 2016-01-11 at 12 51 11 pm" src="https://cloud.githubusercontent.com/assets/1412516/12246831/96db4156-b865-11e5-9dce-670d5f87012e.png">

Although min/max diff is unrealistically huge, ES should simply timeout.

Now I replaced min max diff to reasonably low value but not within the filter range. ES still freezes. 
```
 {
  "size" : 1000,
  "query" : {
    "range" : {
      "eventTimestamp" : {
        "from" : 1452552455074,
        "to" : 1452552755074,
        "include_lower" : true,
        "include_upper" : true
      }
    }
  },
  "aggregations" : {
    "/series(eventtimestamp)" : {
      "date_histogram" : {
        "field" : "eventTimestamp",
        "interval" : "10ms",
        "min_doc_count" : 0,
        "order" : {
          "_key" : "asc"
        },
        "extended_bounds" : {
          "min" : 210,
          "max" : 1000
        }
      }
    }
  }
}
``` 
![heapusage](https://cloud.githubusercontent.com/assets/1412516/12249272/89c2371e-b873-11e5-9cf4-e8a732e7b192.png)
<img width="589" alt="cpuusage" src="https://cloud.githubusercontent.com/assets/1412516/12249279/96c3ebe2-b873-11e5-9dbf-f81ad977e1e0.png">
[es_deadlock_histogram_stackdump.txt](https://github.com/elastic/elasticsearch/files/86527/es_deadlock_histogram_stackdump.txt)

Ideally elasticsearch should only return buckets with overlapping range from filter (or range present in output result set) and input min/max bounds.

**Comment by clintongormley** [comment]
You are creating 145255275507 buckets... which is using up all your memory.  The threads are frozen because garbage collection is thrashing.  We will be dealing with this by limiting the number of buckets that can created.  Closing in favour of https://github.com/elastic/elasticsearch/issues/14046
