### ISSUE TITLE
[DOCS] Document node.max_local_storage_nodes setting

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#15903]
`node.max_local_storage_nodes` is an extremely useful setting that prevents more than the defined number of nodes (e.g., `1`) from sharing the same `path.data`.

I'm open to suggestions on where it should be documented.

**Comment by clintongormley** [comment]
Thanks for volunteering.  I'd put it on this page: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html
