### ISSUE TITLE
mpercolate does not function properly in elasticsearch 2.1.1

### ISSUE THREAD

**Issue by rabx88** [elastic/elasticsearch#15908]
The mpercolate call appears to be broken in 2.1.1 in clusters with more than one node. The following sequence works perfectly on my laptop but fails in two separate three node clusters (in "green" state). Sometimes the call succeeds on one of the three machines but not on the others. I could not find any errors in the logs.
PUT http://localhost:9200/test
[mapping.txt](https://github.com/elastic/elasticsearch/files/86558/mapping.txt)
POST http://localhost:9200/test/.percolator/Certificate_Expiration_Warning_Medium
[percolator.txt](https://github.com/elastic/elasticsearch/files/86560/percolator.txt)
POST http://localhost:9200/test/_mpercolate
[mpercolate.txt](https://github.com/elastic/elasticsearch/files/86562/mpercolate.txt)
Expected Output:
[output.txt](https://github.com/elastic/elasticsearch/files/86566/output.txt)
Actual Output:
[actual.txt](https://github.com/elastic/elasticsearch/files/86577/actual.txt)

**Comment by clintongormley** [comment]
Simple recreation: 

Start two nodes, run this:

    PUT test
    {  
       "settings":{  
          "number_of_shards":1,
          "number_of_replicas":1
       },
       "mappings":{  
          "cert_localmachine_my":{  
             "properties":{  
                "cert_localmachine_my":{  
                   "properties":{  
                      "NotAfter":{  
                         "type":"date",
                         "format":"strict_date_optional_time||epoch_millis"
                      }
                   }
                }
             }
          }
       }
    }
    POST /test/.percolator/Certificate_Expiration_Warning_Medium
    {  
       "query":{  
          "bool":{  
             "filter":{  
                "range":{  
                   "cert_localmachine_my.NotAfter":{  
                      "lt":"now+90d"
                   }
                }
             }
          }
       }
    }
    
  
    POST test/_mpercolate
    {"percolate":{"type":"cert_localmachine_my"}}
    {"doc":{"cert_localmachine_my":{"NotAfter":"2015-07-21T10:28:01-07:00"}}}
    
Then restart one node and run the mpercolate command a few times.  Sometimes it matches sometimes it doesn't.

**Comment by martijnvg** [comment]
The problem is not related to the node restart. It also doesn't match before the restart. The problem is that the mpercolate api doesn't serialise the start time of the request to other nodes that participate in mpercolate execution. I'll open a pr for that. 

@rabx88 Can you confirm that this problem only occurs with range query/filters that use `now`?

**Comment by rabx88** [comment]
That is correct. We tried a few other examples using combinations of term filters and it worked as expected.
