### ISSUE TITLE
master node can not rejoin cluster after restart on es2.0.0. but other nodes can rejoin cluster after restart

### ISSUE THREAD

**Issue by wisre** [elastic/elasticsearch#15916]
i have a es cluster with ten nodes  five  dedicated master[A,B,C,D,E] and five datanode,when i retsart
the master A ,other dedicated master elect another master B,but when the A start,it cannot find master B.but B can find A,and put A into the cluster.

the error like this
===
> [2016-01-12 11:39:45,812][DEBUG][action.admin.cluster.state] [efe-es-03] no known master node, scheduling a retry
[2016-01-12 11:39:45,891][DEBUG][action.admin.cluster.state] [efe-es-03] no known master node, scheduling a retry
[2016-01-12 11:39:46,490][INFO ][rest.suppressed          ] /.kibana/config/_search Params: {index=.kibana, type=config}
ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];]
        at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:154)
        at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedRaiseException(ClusterBlocks.java:144)

the new master add A into cluster
===
> [2016-01-12 10:57:49,394][INFO ][cluster.service          ] [efe-es-03] added {{efe-es-01}{9H7bnUbASVerOMdEOlWikg}{10.39.128.30}{10.39.128.30:9300}{rack=10.39.128.30, max_local_storage_nodes=1, master=true},}, reason: zen-disco-join(join from node[{efe-es-01}{9H7bnUbASVerOMdEOlWikg}{10.39.128.30}{10.39.128.30:9300}{rack=10.39.128.30, max_local_storage_nodes=1, master=true}])

but A can't get nodes info others can get nodes info including A
===
> curl localhost:8080/_cat/nodes

**Comment by wisre** [comment]
my discover config like this
====
> 
 discovery.zen.ping.unicast.hosts: ["A", "B","C","D","E"]
 discovery.zen.minimum_master_nodes: 3
 discovery.zen.ping.multicast.enabled: false

**Comment by dadoonet** [comment]
Please join us on discuss.elastic.co. We can help there.

Also provide your full logs there.
