### ISSUE TITLE
AccessControlException in JarHell#checkJarHell when running embedded for testing purposes

### ISSUE THREAD

**Issue by trejkaz** [elastic/elasticsearch#15918]
Our tests are run with a security manager enabled.

Another developer (who apparently disabled the security manager instead of reporting this) added a test which tries to start an elasticsearch node, which then tries to load plugins. Turns out that this calls `JarHell#checkJarHell`, which then pokes around the classpath in some fashion. The resulting `AccessControlException` is then presumably caught, but the code appears to then assume that there is "jar hell", rather than assuming that there isn't, which could possibly be the source of the issue.

This is occurring in v2.0.1.

Stack trace:

    java.lang.IllegalStateException: failed to load bundle [] due to jar hell
    	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:342)
    	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:113)
    	at org.elasticsearch.node.Node.<init>(Node.java:144)
    	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
    	at org.elasticsearch.node.NodeBuilder.node(NodeBuilder.java:152)
    	at ElasticSearchTestUtils.createNode(ElasticSearchTestUtils.java:62)
    	at ElasticSearchTestUtils$1.<init>(ElasticSearchTestUtils.java:75)
    	at ElasticSearchTestUtils.createClient(ElasticSearchTestUtils.java:73)
    	at TestElasticSearchTextAnalysisService.setUp(TestElasticSearchTextAnalysisService.java:337)
    	(omitting JUnit frames)
    Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/Applications/IntelliJ IDEA 15 CE.app/Contents/lib/idea_rt.jar" "read")
    	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
    	at java.security.AccessController.checkPermission(AccessController.java:884)
    	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
    	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
    	at java.util.zip.ZipFile.<init>(ZipFile.java:211)
    	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
    	at java.util.jar.JarFile.<init>(JarFile.java:166)
    	at java.util.jar.JarFile.<init>(JarFile.java:103)
    	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:173)
    	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:340)
    	... 18 more

**Comment by clintongormley** [comment]
@rjernst could you take a look at this?

**Comment by trejkaz** [comment]
I'm guessing that's a no?

**Comment by s1monw** [comment]
I think you have to fix your classpath to not include this jar file otherwise you won't get passed the security manager.

**Comment by trejkaz** [comment]
I'm not sure it's possible, but I guess I could file a bug with IDEA to see if they will take their runtime off there, but I'm not confident that they will cooperate.

Surely from the elasticsearch side there is a way to implement that check without using JarFile directly, but I couldn't find a way when I did a quick check (JarURLConnection#getJarFile throws the same exception.)

**Comment by s1monw** [comment]
I run in idea as well and it's totally possible

**Comment by trejkaz** [comment]
I'm not finding the option... I have dug pretty deep.

**Comment by jasontedor** [comment]
> I'm not finding the option... I have dug pretty deep.

Start by removing everything but the bare minimum from the SDKs (File -> Project Structure -> Platform Settings -> SDKs -> Classpath). There is no reason for an IntelliJ jar to be on the classpath. Take a look at the PR #13465 that removed the leniency in this situation and specifically a [minimal set of jars](https://github.com/elastic/elasticsearch/pull/13465#issuecomment-142124441) provided there.

**Comment by trejkaz** [comment]
At the moment, the jars for the SDK are:

    jdk1.8.0_51.jdk/Contents/Home/jre/lib/charsets.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/jce.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/jfr.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/jsse.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/management-agent.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/resources.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/rt.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/cldrdata.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/dnsns.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/localedata.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/morelocales.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/nashorn.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/resourcebundlefix.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/sunec.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar
    jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/zipfs.jar

Which is bigger than their list, but most of what we have extra is actually in use. (I'm not sure about management-agent. We use management heavily, so I'm scared to remove it, but maybe it's a particular thing we don't specifically use.)

So idea_rt.jar was never explicitly on the classpath. But when I run from IDEA, it magically gets added on the front of the classpath anyway.

Supposedly, adding idea.no.launcher=true to idea.properties stops it doing this, but I'm finding that it doesn't work. I still get it on the front of the classpath.

That aside, what if our security policy said you weren't allowed to read from rt.jar? Surely you would be handling that situation incorrectly as well, so I still assert that the correct handling for a SecurityException is that you are supposed to catch it and proceed in a sensible fashion. The current behaviour is not really acceptable.

**Comment by jasontedor** [comment]
Your Java won't work if you try to forbid rt.jar, it is *the* Java runtime. I'm sorry, but the security policy is not going to be made lenient.

**Comment by trejkaz** [comment]
False.

Only dodgy code which tries to scrape the classpath for jar files and then open each one directly would fail in such a scenario. Well-behaved code which looks up resources the proper way from the classpath still works. Elasticsearch's `JarHell` class is far from well-behaved code, which is why it is causing problems here.

Learn how Java does things, and then fix your shit.

**Comment by trejkaz** [comment]
Demonstration, for anyone interested in learning how things actually work.

`build.sh`:

    #!/bin/bash

    COMPILE_CLASSPATH=elasticsearch-2.2.0.jar
    RUNTIME_CLASSPATH=${COMPILE_CLASSPATH}:lucene-core-5.4.1.jar

    javac -classpath ${COMPILE_CLASSPATH} WellBehavedDemo.java

    # Deliberately uses == to be extra restrictive.
    java -classpath .:${RUNTIME_CLASSPATH} \
     -Djava.security.manager \
     -Djava.security.policy==my.policy \
     WellBehavedDemo

`WellBehavedDemo.java`:

    import org.elasticsearch.bootstrap.JarHell;

    class WellBehavedDemo {
        public static void main(String[] args) throws Exception {
            ClassLoader classLoader = WellBehavedDemo.class.getClassLoader();

            System.out.print("Loading classes from JRE...");
            classLoader.loadClass("java.lang.String");
            System.out.println(" works!");

            System.out.print("Reading resources from JRE...");
            classLoader.getResources("/java/lang/String.class");
            System.out.println(" works!");

            System.out.print("Loading classes from extra jars...");
            classLoader.loadClass("org.apache.lucene.util.Version");
            System.out.println(" works!");

            System.out.print("Reading resources from extra jars...");
            classLoader.getResources("/META-INF/services/org.apache.lucene.codecs.Codec");
            System.out.println(" works!");

            System.out.print("Running JarHell... ");
            JarHell.checkJarHell();
            System.out.println(" works!");
        }
    }

Notice that this loads both classes and resources, and uses getResources() for this, which can return multiple. This can be used for classfiles too, the only catch being that JarHell wants a way to list the directories. I'm not sure there is a good way to do that without breaking rules.

I was hoping to demonstrate this with a minimal (1-line) policy file, but it turns out Elasticsearch also behaves badly when you reject its access to system properties as well, and additionally is using system properties for things which it should be using public APIs for instead. Please consider all these as appended to the bug report and feel free to come up with worthless excuses for why you won't fix those bugs either.

`my.policy`:

    grant {

      // Elasticsearch doesn't cope well with denials to read system properties either, so we'll just humour
      // it to get it through to the specific failure I reported. It turns out many libraries have this particular
      // issue, so we already granted it to everything.

      // So here's a summary of ES's transgressions up to the issue I actually reported.

      // via org.elasticsearch.common.logging.Loggers.<clinit>
      // Should have caught the SecurityException and treated it as if the property wasn't set.
      permission java.util.PropertyPermission "es.logger.prefix", "read";

      // via org.elasticsearch.bootstrap.JarHell.parseClassPath
      // Should have looked at the ClassLoader instead, because java.class.path sometimes only contains the classpath for the container.
      permission java.util.PropertyPermission "java.class.path", "read";

      // via org.elasticsearch.bootstrap.JarHell.parseClassPath
      // Should have used File.pathSeparator instead.
      permission java.util.PropertyPermission "path.separator", "read";

      // via org.elasticsearch.bootstrap.JarHell.parseClassPath
      // Should have used File.separator instead.
      permission java.util.PropertyPermission "file.separator", "read";

      // via org.elasticsearch.bootstrap.JarHell.checkJarHell
      // I'm not sure what they're smoking here. It should not be necessary to read the location of Java!
      permission java.util.PropertyPermission "java.home", "read";

      // via org.elasticsearch.bootstrap.JavaVersion.<clinit>
      // Should have caught the SecurityException and treated it the same as the property being missing.
      permission java.util.PropertyPermission "java.specification.version", "read";

      // via org.elasticsearch.bootstrap.JarHell.checkJarHell
      // Current directory is probably fine, as long as it's only reading.
      // In real situations we use absolute paths anyway, which removes this issue.
      // Could possibly just modify the shell script to get around it, actually.
      permission java.util.PropertyPermission "user.dir", "read";
      permission java.io.FilePermission "${user.dir}", "read";

      // via org.elasticsearch.bootstrap.JarHell.checkJarHell
      // This next one is exactly the idea_rt.jar issue.
      // It just happens to be the first thing in the classpath that isn't Elasticsearch itself, whereas when running from IDEA,
      // idea_rt.jar is always first.
      //permission java.io.FilePermission "${user.dir}/lucene-core-5.4.1.jar", "read";
    };

Output:

    bucket:security_demo tester$ ./well_behaved_demo.sh 
    Loading classes from JRE... works!
    Reading resources from JRE... works!
    Loading classes from extra jars... works!
    Reading resources from extra jars... works!
    Running JarHell... Exception in thread "main" java.security.AccessControlException: access denied ("java.io.FilePermission" "/Users/tester/test/security_demo/lucene-core-5.4.1.jar" "read")
    	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
    	at java.security.AccessController.checkPermission(AccessController.java:884)
    	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
    	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
    	at java.util.zip.ZipFile.<init>(ZipFile.java:211)
    	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
    	at java.util.jar.JarFile.<init>(JarFile.java:166)
    	at java.util.jar.JarFile.<init>(JarFile.java:103)
    	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:174)
    	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:87)
    	at WellBehavedDemo.main(WellBehavedDemo.java:24)

Notice how the way `JarHell` is doing things is rejected by the security policy, even though accessing the same things using the proper APIs works fine.

**Comment by clintongormley** [comment]
@trejkaz Instead of just insulting us, why not send a PR instead?

**Comment by trejkaz** [comment]
The pull request I would have submitted (removing the JarHell checker in its entirety) presumably wouldn't be accepted anyway.

**Comment by clintongormley** [comment]
Clearly not.  But you said you had ways to improve it, so submit that instead.

**Comment by pshirshov** [comment]
Hm. Why this is closed? In fact the problem still persists )

**Comment by vaughnd** [comment]
I'm still working through jar hell. In some cases it's not at all relevant, e.g. when using jcl-over-slf4j to override commons-logging. Now I have to try exclude commons-logging in each and every dependency, instead of just letting jcl-over-slf4j do what it was designed to do. I'm very close to just overriding JarHell...

**Comment by rjernst** [comment]
@vaughnd This is a closed issue. If you think you have encountered a bug (eg jarhell when using the test framework), then please open a new issue and detail how to reproduce.
