### ISSUE TITLE
Support for loading a plugin in a client node is missing

### ISSUE THREAD

**Issue by dbaggott** [elastic/elasticsearch#15927]
In 2.1.1 (and, I think, all 2.X versions), there's no support for loading plugins to a client-only node.

For example, there's no (obvious) way to load plugins when doing something like:

```java
Node node = NodeBuilder.nodeBuilder()
        .clusterName("my-cluster")
        .settings(settings)
        .client(true)
        .build();
```

An `addPlugin` method on NodeBuilder along the lines of `TransportClient.addPlugin` would be helpful.

The work-around is to override Node, duplicate the environment/version constructor logic, and provide your custom list of plugins to load:

```java
private static class PluginEnabledNode extends Node {
    public PluginEnabledNode(Settings settings, Collection<Class<? extends Plugin>> plugins) {
        super(InternalSettingsPreparer.prepareEnvironment(settings, null),
                Version.CURRENT,
                plugins);
    }
}
```

And then you can directly instantiate a `PluginEnabledNode` (being careful to set "node.client" and "cluster.name" in your settings)

```java
Node node = new PluginEnabledNode(settings, ImmutableList.<Class<? extends Plugin>>of(CloudAwsPlugin.class)).start()
```

Note to anyone attempting this work-around -- my initial attempt resulted in a very large number of Guice related injection errors when the Node was initializing.  These were due to a library version conflict between what was used by my project and what was used by the plugin I was adding.  In my case, I had an older version of Jackson and the plugin was using a new version that relied on methods that didn't exist in the older version.

**Comment by dbaggott** [comment]
Also [discussed here](https://discuss.elastic.co/t/cloud-aws-for-es-2-1-1-in-maven/38924/5).

**Comment by jprante** [comment]
@dbaggott `NodeBuilder` has become unusable for plugins.

See https://github.com/elastic/elasticsearch/issues/15060
and https://github.com/elastic/elasticsearch/issues/13212
and https://github.com/elastic/elasticsearch/pull/15107
and https://discuss.elastic.co/t/add-plugins-from-classpath-in-embedded-elasticsearch-client-node/36269

**Comment by dadoonet** [comment]
I think this is important in cases where users want to use a Client Node to connect to AWS or Azure for example. Those users need to add a cloud plugin.
We should either support it out of the box, either document how they can do it, either remove support for Client Node...

Thoughts?

**Comment by clintongormley** [comment]
A client only node is just a node, with a config directory etc.  What's the issue with installing the plugin into the `plugins` directory like you'd do on any other node?

**Comment by dadoonet** [comment]
Because you are starting a Node programmatically which is in Maven/Java:

* add dependencies to `elasticsearch`, `cloud-aws`.
* start the node in Java.

As a Java developper I would not expect having to run a single command like `bin/plugin` when I want to use a Java client.

**Comment by clintongormley** [comment]
Then use a transport client, not a client node.

**Comment by dadoonet** [comment]
So we should deprecate Client Node and don't document it in the Java API doc anymore IMO.

**Comment by dbaggott** [comment]
@jprante, thanks for all the pointers!  I spent some time searching closed issues but didn't manage to find those.  The context is very helpful, I didn't realize the history that I was stumbling into and it's helpful in understanding where everyone is coming from and why the discussion is so heated!

@dadoonet, thanks for clarifying the use case!

@clintongormley, w/r/t your first suggestion, I'll look into that.  As @dadoonet alluded to, the mechanics of doing that are very cumbersome.  But I'm gathering that it's the only "officially supported" mechanism?

@clintongormley, if one were to switch from a client node to a transport node aren't there important functional ramifications in turns of "smart load balancing" etc that are being lost?

@clintongormley, @jprant, @dadoonet, (the yuckiness of pushing internal ES details into my app aside), is the "extend a Node" hack fundamentally broken?  And apologies if that's already discussed in one of the links, I'm still working through the discussions.

I realize you all are very deep into the 2.X series but for someone who is just coming at it and upgrading from 1.7 to 2.X, the "right thing" to do in this situation is *very opaque*.  As a user of ES, I'm very motivated to do the right thing, I'm just still working through what that is/how to do it!  So, a strong +1 for providing guidance on what the right thing is and a strong +1 for making it practical to do the right thing.  Of all the breaking changes in 2.X that we're dealing with, this is the one that's the least documented and that I'm spending the most time on.  I realize that it's only a subset of users so (understandably) not a top priority but for anyone who is in this situation, it's painful.

**Comment by dbaggott** [comment]
(And, I forgot to say, @clintongormley, thanks for the suggestions!)

**Comment by clintongormley** [comment]
@dbaggott You're right that things have changed a lot in this area in the 2.x series, and that this has been discussed in a number of places, and also that the change can be quite painful (for which i apologise).  Just know that it isn't a change we made lightly.

i tried to explain the reasoning behind it here: https://discuss.elastic.co/t/add-plugins-from-classpath-in-embedded-elasticsearch-client-node/36269/5?u=clinton_gormley

> if one were to switch from a client node to a transport node aren't there important functional ramifications in turns of "smart load balancing" etc that are being lost?

The transport client still handle load balancing. It's slightly dumber in that it doesn't have the cluster state and so sends requests to "The Cluster" rather than directly to the node which holds the relevant data, so yes, there can be an extra network hop.  This is the same way that all of the HTTP clients work.

Previously we recommended embedding a node client into your application but we have moved away from this recommendation - it is fraught with issues.  Really, the only way to use a node client (if at all) is to run a standalone (not embedded) one on your local app server. Your application uses the transport client to talk to the node client on localhost, and the node client then sends the request to the right node in the cluster.

Honestly, I'm not convinced that this setup is worth it.  One of the issues is: let's say you have 1,000 app servers... suddenly you have 1,000 extra nodes in your cluster, all of which need to receive cluster state updates!  Cluster state updates wait for acknowledgement, so suddenly you are subject to the latency of the slowest node out of an extra 1,000.

**Comment by dbaggott** [comment]
@clintongormley, thanks for the helpful reply and for the link which I had read (and now read again).  Your caveat about large numbers of apps aside, running a local node client and talking to it on localhost is the most practical suggestion I've heard (at least for our development/deployment ecosystem).  I also see that that's a variation on [what's recommended in the 2.1 docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/modules-node.html).  Our use of a Node-based client over a TransportClient is entirely motivated by the perceived benefits of being cluster-intimate.  If I can find the bandwidth, I'll test how much of a difference it actually makes for us.

Preface: I'm not trying to argue for any course of action or convince anyone to do anything differently, I'm just trying to understand:  On the surface of things, it doesn't *seem* entirely coherent to 1. have a library api that provides facilities for building a transport client with any arbitrary 3rd party plugin; 2. have that same api only support building client nodes without plugins.  In short, what would be the fundamental difference between running these two lines of code from an external application?

```java
TransportClient.builder().settings(settings).addPlugin(MaliciousPlugin.class).build();
NodeBuilder.nodeBuilder().settings(settings).addPlugin(MaliciousPlugin.class).build().client();
```

In either case, the malicious plugin code running in the external app could represent itself as a node and join the cluster with malicious intent, no?  Ie, just because it's being loaded by a TransportClient, doesn't prevent the plugin from acting with evil intent.  And the issues w/r/t JarHell and class loaders apply to both?  Or am I missing something in my assumptions or thinking?

Again, thank you for taking the time to respond!

**Comment by clintongormley** [comment]
> In either case, the malicious plugin code running in the external app could represent itself as a node and join the cluster with malicious intent, no? 

No, that's the difference.  A transport client is **not** a node. It doesn't join the cluster. It is just a lightweight client that talks to the cluster.

**Comment by dbaggott** [comment]
I get that distinction -- I was trying to suggest that, from a security perspective, the malicious plugin is malicious and so will, by definition, do things it's not supposed to do (like open up ports to emulate a node and join the cluster).

I'm guessing what I'm missing is the assumption that the ES cluster is completely locked down from a network perspective and you expect that a client application that's only running a TransportClient would *only* have access the cluster's http port whereas a client application running an embedded node would necessarily have broader network access to the cluster...  In the former case, it's considered "safe" *for the ES cluster* to allow loading of a 3rd party plugin since they can only interact with the cluster via the http protocol which is hardened.  That, of course, provides no guarantees for the security of the *client application/server* itself in the face of a malicious plugin that was loaded via the TransportClient.

In the perfect world, am I correct in thinking that a transport client should ideally support loading of plugins using a similarly secure security mechanism as the standard `bin/plugin install` mechanism?  I appreciate that that is probably a low priority and might contain difficulties that make it unattractive and/or impractical.  But, if that were the case, then loading a plugin via the TransportClient would be safer and loading plugins via embedded nodes would then be a non-issue...

**Comment by rjernst** [comment]
@dbaggott Malicious code is malicious code. With it, from a TransportClient, it could do anything that your app allows code to do. We can't lock down your jvm with SecurityManager as we do in Elasticsearch when you build a transport client. If you wish to run your own SecurityManager, please do, it is highly encouraged! Note that this has nothing to do with what a Node can do within the cluster.

As for the issue here, in master, the Node ctor that takes plugins is now public (and NodeBuilder has been removed). If you *really* must do so, you can use the Node ctor as you did NodeBuilder before, but this is essentially unsupported, may break in any release, and for the reasons that have already been listed in this issue, is highly discouraged. It is much better to use a client, whether talking with a remove cluster, or a local node that is connected to the cluster.

**Comment by denov** [comment]
the docs on - https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/client-connected-to-client-node.html  don't seem to line up with this discussion.   i'm in the process of doing a 1.4 to 2.3 upgrade and have found the docs a bit confusing.

**Comment by rjernst** [comment]
@denov See the docs for the upcoming 5.0 release, maybe that clarifies?
https://www.elastic.co/guide/en/elasticsearch/client/java-api/master/client-connected-to-client-node.html

**Comment by denov** [comment]
@rjernst thanks for the link, but no.  I'm just looking on how to load the cloud-aws https://www.elastic.co/guide/en/elasticsearch/plugins/current/cloud-aws.html for my app can discover the nodes running ES.

in 1.x  i just needed the plugin in the classpath and it was all good.  now that's not the case.

**Comment by rjernst** [comment]
@denov Please ask questions like this on https://discuss.elastic.co. There are multiple past discussions there that should help.
