### ISSUE TITLE
Simplify MapperService#searchFilter(...)

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#15924]
This method has a lot of logic that deals with the fact if type field isn't indexed. Since the the type field is locked down (like other meta fields), the type field is now always indexed. So it is time to clean this up.

It also has logic if only one type has been specified, which can be removed because BooleanQuery optimises when there is only one clause.

There is also logic to hide percolator queries. In order to further simplify this method I think we should not do this anymore? A percolator query is just a document and should be returned like other documents. If it percolator queries shouldn't be returned then the query defined in the search request should just be modified to do so. We should implicitly exclude these docs from the search results any more.

**Comment by rjernst** [comment]
+1
