### ISSUE TITLE
How to install scripting plugins from source

### ISSUE THREAD

**Issue by NDevox** [elastic/elasticsearch#15925]
Looking at docs here: https://www.elastic.co/guide/en/elasticsearch/plugins/current/lang-python.html

This assumes you have access to the internet. The server I need to install this on does not have access to anything outside our local network (company security measures). 

Can we get instructions on how to build from source?

It's hinted at in the old repository: https://github.com/elastic/elasticsearch-lang-python although not actually explained.

Is it still possible with the new location of the plugins?

**Comment by dadoonet** [comment]
In 2.x branches:

```sh
git clone https://github.com/elastic/elasticsearch.git
git checkout v2.1.1
cd elasticsearch/plugins/lang-python
mvn install
```

The plugin is built in `target/releases`.

But you don't need that to install the plugin. You can also download a packaged version from our download service.

For example here: https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/lang-python/2.1.1/lang-python-2.1.1.zip

**Comment by NDevox** [comment]
@dadoonet do you think it is worth adding this to the docs?

**Comment by dadoonet** [comment]
I don't know. Running `bin/plugin -v` gives the exact URL which is used to download the file locally.
Also note that maven central has also those files: http://search.maven.org/#search%7Cga%7C1%7Clang-python

@clintongormley WDYT? Should we document how is organized our download service for such a case?
Or add a `--do-not-install` / `--just-download` option to the plugin manager?

**Comment by clintongormley** [comment]
Perhaps we can add a line to the docs for each plugin saying "This plugin can be downloaded for offline install from xxxxx", and just use an asciidoc `:plugin_url:` replacement to keep the URLs up to date.
