### ISSUE TITLE
date format field comparing problem..

### ISSUE THREAD

**Issue by q11112345** [elastic/elasticsearch#15930]
here is my xshell log.
the problem is gte and lte does not have the same behivor in comparing using two different date format

[BEGIN] 2016/1/12 22:01:27
[root@4-216 ~]# curl -XDELETE 192.168.4.216:9280/test_red/t6
{"error":"TypeMissingException[[_all] type[[t6]] missing: No index has the type.]","status":404}[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XPUT 192.168.4.216:9280/test_red/t6/_mapping -d '
>               {
>                   "t6":{
>                       "_all":{
>                           "auto_boost" : true,
>                           "index_analyzer" : "ik"
>                       },
>                       "properties" : {
>                           "start_time" : {
>                             "type" : "date",
>                             "format" : "YYYY-MM-dd"
>                           }
>                       }
>                   }
>               }'
{"acknowledged":true}[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_mapping?pretty
{
  "test_red" : {
    "mappings" : {
      "t6" : {
        "_all" : {
          "auto_boost" : true,
          "index_analyzer" : "ik"
        },
        "properties" : {
          "start_time" : {
            "type" : "date",
            "format" : "YYYY-MM-dd"
          }
        }
      }
    }
  }
}
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XPOST 192.168.4.216:9280/test_red/t6/1 -d '{
>                 "start_time":"2016-01-02"
>             }'
{"_index":"test_red","_type":"t6","_id":"1","_version":1,"created":true}[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XPOST 192.168.4.216:9280/test_red/t6/2?pretty -d '{
>                 "start_time":"2016-01-03"
>             }'
{
  "_index" : "test_red",
  "_type" : "t6",
  "_id" : "2",
  "_version" : 1,
  "created" : true
}
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XPOST 192.168.4.216:9280/test_red/t6/3?pretty -d '{
>                 "start_time":"2016-01-04"
>             }'
{
  "_index" : "test_red",
  "_type" : "t6",
  "_id" : "3",
  "_version" : 1,
  "created" : true
}
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 3,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "1",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-02"
            }
    }, {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "2",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-03"
            }
    }, {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "3",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-04"
            }
    } ]
  }
}
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# # ive had three document indexed just now
[root@4-216 ~]# # now i will  try to make some filter test
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# ^C
[root@4-216 ~]# ^C
[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
>                 "filter":{
>                     "range":{
>                         "start_time":{
>                             "format": "YYYY-MM-dd",
>                             "lte": "2016-01-03"
>                         }
>                     }
>                 }
>             }'
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "1",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-02"
            }
    }, {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "2",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-03"
            }
    } ]
  }
}
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
>                 "filter":{
>                     "range":{
>                         "start_time":{
>                             "format": "YYYY-MM-dd",
>                             "gte": "2016-01-03"
>                         }
>                     }
>                 }
>             }'
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "2",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-03"
            }
    }, {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "3",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-04"
            }
    } ]
  }
}
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# ############# see, 2016-01-03 is matched in the two filter query, one is lte filter, and anther is gte filter
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# #### the date format in filter is YYYY-MM-dd
[root@4-216 ~]# #### now lets see what will i get with filter format YYYY-MM-dd HH:mm:ss
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
>                 "filter":{
>                     "range":{
>                         "start_time":{
>                             "format": "YYYY-MM-dd HH:mm:ss",
>                             "lte": "2016-01-03 00:00:00"
>                         }
>                     }
>                 }
>             }'
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "1",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-02"
            }
    }, {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "2",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-03"
            }
    } ]
  }
}
[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
>                 "filter":{
>                     "range":{
>                         "start_time":{
>                             "format": "YYYY-MM-dd HH:mm:ss",
>                             "lte": "2016-01-03 01:00:00"
>                         }
>                     }
>                 }
>             }'
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "1",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-02"
            }
    }, {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "2",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-03"
            }
    } ]
  }
}
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
>                 "filter":{
>                     "range":{
>                         "start_time":{
>                             "format": "YYYY-MM-dd HH:mm:ss",
>                             "gte": "2016-01-03 14:00:00"
>                         }
>                     }
>                 }
>             }'
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "3",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-04"
            }
    } ]
  }
}
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
>                 "filter":{
>                     "range":{
>                         "start_time":{
>                             "format": "YYYY-MM-dd HH:mm:ss",
>                             "gte": "2016-01-03 00:00:00"
>                         }
>                     }
>                 }
>             }'
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "2",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-03"
            }
    }, {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "3",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-04"
            }
    } ]
  }
}
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# #### do you see the difference ? 
[root@4-216 ~]# #### when i use lte filter to match less and equal to 2016-01-03 01:00:00, the date 2016-01-03 is matched
[root@4-216 ~]# #### when i use gte filter to match greater and equal to 2016-01-03 14:00:00, the date 2016-01-03 is not matched
[root@4-216 ~]# 
[root@4-216 ~]# #### when i use gte filter to match greater and equal to 2016-01-03 00:00:00, the date 2016-01-03 is  matched
[root@4-216 ~]# 
[root@4-216 ~]# #### now lets see gte filter to match greater and equal to 2016-01-03 01:00:00.   which can be compared with the lte filter  to match less and equal to 2016-01-03 01:00:00
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
>                 "filter":{
>                     "range":{
>                         "start_time":{
>                             "format": "YYYY-MM-dd HH:mm:ss",
>                             "gte": "2016-01-03 01:00:00"
>                         }
>                     }
>                 }
>             }'
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "3",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-04"
            }
    } ]
  }
}
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# #### see, it doesnt match
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# ### its still has the problem after i update the date filed format from "YYYY-MM-dd" to "YYYY-MM-dd HH:mm:ss"
[root@4-216 ~]# ### is this regular????????
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# ####### now lets update the format
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XPUT 192.168.4.216:9280/test_red/_mapping/t6 -d '
>             {
>                 "_all":{
>                     "auto_boost" : true,
>                     "index_analyzer" : "ik"
>                 },
>                 "properties" : {
>                     "start_time" : {
>                       "type" : "date",
>                       "format" : "YYYY-MM-dd HH:mm:ss"
>                     }
>                 }
>             }'
{"acknowledged":true}[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XPUT 192.168.4.216:9280/test_red/_mapping/t6 -d '
            {
                "_all":{
                    "auto_boost" : true,
                    "index_analyzer" : "ik"
                },
                "properties" : {
                    "start_time" : {
                      "type" : "date",
                      "format" : "YYYY-MM-dd HH:mm:ss"
                    }
                }
[root@4-216 ~]# ####### now lets update the format

[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
                "filter":{
                    "range":{
                        "start_time":{
                            "format": "YYYY-MM-dd HH:mm:ss",
                            "gte": "2016-01-03 01:00:00"
                        }
                    }
                }
[root@4-216 ~]# #### now lets see gte filter to match greater and equal to 2016-01-03 01:00:00.   which can be compared with the lte filter  to match less and equal to 2016-01-03 01:00:00

[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
                "filter":{
                    "range":{
                        "start_time":{
                            "format": "YYYY-MM-dd HH:mm:ss",
                            "gte": "2016-01-03 00:00:00"
                        }
                    }
                }
                            "gte": "2016-01-03 14:00:00"
                        }
                    }
                }
                            "lte": "2016-01-03 01:00:00"
                        }
                    }
                }
                            "lte": "2016-01-03 00:00:00"
                        }
                    }
                }
[root@4-216 ~]# #### now lets see what will i get with filter format YYYY-MM-dd HH:mm:ss

[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
                "filter":{
                    "range":{
                        "start_time":{
                            "format": "YYYY-MM-dd HH:mm:ss",
                            "lte": "2016-01-03 00:00:00"
                        }
                    }
                }
[root@4-216 ~]# #### now lets see what will i get with filter format YYYY-MM-dd HH:mm:ss

[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
                "filter":{
                    "range":{
                        "start_time":{
                            "format": "YYYY-MM-dd",
                            "gte": "2016-01-03"
                        }
                    }
                }
                            "lte": "2016-01-03"
                        }
                    }
                }
[root@4-216 ~]# # now i will  try to make some filter test

[root@4-216 ~]# curl -XPOST 192.168.4.216:9280/test_red/t6/3?pretty -d '{
                "start_time":"2016-01-04"
[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty

[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
                "filter":{
                    "range":{
                        "start_time":{
                            "format": "YYYY-MM-dd",
                            "lte": "2016-01-03"
                        }
                    }
                }
            }'
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "1",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-02"
            }
    }, {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "2",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-03"
            }
    } ]
  }
}
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
                "filter":{
                    "range":{
                        "start_time":{
                            "format": "YYYY-MM-dd",
                            "lte": "2016-01-03"
                        }
                    }
                }
                            "gte": "2016-01-03"
                        }
                    }
                }
            }'
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "2",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-03"
            }
    }, {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "3",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-04"
            }
    } ]
  }
}
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# ######### we got 2016-01-03 both
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
                "filter":{
                    "range":{
                        "start_time":{
                            "format": "YYYY-MM-dd",
                            "gte": "2016-01-03"
                        }
                    }
                }
                            "lte": "2016-01-03"
                        }
                    }
                }
[root@4-216 ~]# curl -XPUT 192.168.4.216:9280/test_red/_mapping/t6 -d '
            {             
                "_all":{
                    "auto_boost" : true,
                    "index_analyzer" : "ik"
                },                             
                "properties" : {
                    "start_time" : {
                      "type" : "date",
                      "format" : "YYYY-MM-dd HH:mm:ss"
                    }
                }
[root@4-216 ~]# ####### now lets update the format

[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
                "filter":{
                    "range":{
                        "start_time":{
                            "format": "YYYY-MM-dd HH:mm:ss",
                            "gte": "2016-01-03 01:00:00"
                        }
                    }
                }
[root@4-216 ~]# #### now lets see gte filter to match greater and equal to 2016-01-03 01:00:00.   which can be compared with the lte filter  to match less and equal to 2016-01-03 01:00:00

[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
                "filter":{
                    "range":{
                        "start_time":{
                            "format": "YYYY-MM-dd HH:mm:ss",
                            "gte": "2016-01-03 01:00:00"
                        }
                    }
                }
[root@4-216 ~]# #### now lets see gte filter to match greater and equal to 2016-01-03 01:00:00.   which can be compared with the lte filter  to match less and equal to 2016-01-03 01:00:00

[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
                "filter":{
                    "range":{
                        "start_time":{
                            "format": "YYYY-MM-dd HH:mm:ss",
                            "gte": "2016-01-03 00:00:00"
                        }
                    }
                }
                            "gte": "2016-01-03 14:00:00"
                        }
                    }
                }
                            "lte": "2016-01-03 01:00:00"
                        }
                    }
                }
            }'
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "1",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-02"
            }
    }, {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "2",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-03"
            }
    } ]
  }
}
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
                "filter":{
                    "range":{
                        "start_time":{
                            "format": "YYYY-MM-dd HH:mm:ss",
                            "lte": "2016-01-03 01:00:00"
                        }
                    }
                }
[root@4-216 ~]# ######### we got 2016-01-03 both

[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
                "filter":{
                    "range":{
                        "start_time":{
                            "format": "YYYY-MM-dd",
                            "gte": "2016-01-03"
                        }
                    }
                }
                            "lte": "2016-01-03"
                        }
                    }
                }
[root@4-216 ~]# curl -XPUT 192.168.4.216:9280/test_red/_mapping/t6 -d '
            {             
                "_all":{
                    "auto_boost" : true,
                    "index_analyzer" : "ik"
                },                             
                "properties" : {
                    "start_time" : {
                      "type" : "date",
                      "format" : "YYYY-MM-dd HH:mm:ss"
                    }
                }
[root@4-216 ~]# ####### now lets update the format

[root@4-216 ~]# curl -XGET 192.168.4.216:9280/test_red/t6/_search?pretty -d '{
                "filter":{
                    "range":{
                        "start_time":{
                            "format": "YYYY-MM-dd HH:mm:ss",
                            "gte": "2016-01-03 01:00:00"
                        }
                    }
                }
            }'
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test_red",
      "_type" : "t6",
      "_id" : "3",
      "_score" : 1.0,
      "_source":{
                "start_time":"2016-01-04"
            }
    } ]
  }
}
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# #### we got 2016-01-03 only once...
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 
[root@4-216 ~]# 

[END] 2016/1/12 22:16:50

**Comment by clintongormley** [comment]
Hi @q11112345 

First, could you tell us what version of ES you are using? Second, could you reformat your post to provide a simple runnable example that I can copy and paste to try out, rather than having to recreate everything you did?

**Comment by dadoonet** [comment]
Question was asked here: https://discuss.elastic.co/t/how-does-the-updating-put-mapping-api-works-to--all-field/38803

I suggest we follow up on discuss instead?

**Comment by clintongormley** [comment]
Makes sense. btw @q11112345, deleting mappings is no longer supported, and may be involved with the issue you have.

**Comment by q11112345** [comment]
ok. im sorry. i cant open gist.github.com. im in china.
how about give me a email-address.
version im using is 1.5.0. i forget telling you.

**Comment by clintongormley** [comment]
@q11112345 A number of issues have been fixed around dates and ranges since then.  You should upgrade

**Comment by q11112345** [comment]
alright. thank you. this is not a urgent.  i have to discuss with my leader about upgrading.
