### ISSUE TITLE
Nonunique terms are being accounted multiple times in terms aggregation of child/nested documents

### ISSUE THREAD

**Issue by serj-p** [elastic/elasticsearch#15945]
My domain is the following: a parent doc has some child docs with some string field. I want to calculate a frequency of parents having particular field in the child doc. When this particular field doesn't have duplicates amond same parent - results of query below are OK. But when some parent has multiple children with same value of the field, calculation sums this duplicates and gives wrong results. When I perform equal search query it gives me right count of parent docs. 

        curl -XPUT 127.0.0.1:9200/test_index -d '
        {
          "mappings": {
            "test_parent": {
                "properties": {
                    "test_filter_field": {
                        "type": "string"
                    }
                }
            },
            "test_child": {
              "_parent": {
                "type": "test_parent"
              },
              "properties": {
                  "test_non_nested_field": {
                      "type": "string"
                  },
                  "test_nested_field": {
                      "type": "nested",
                      "properties": {
                        "nested_filter_field": {
                            "type": "string"
                        },
                        "nested_term_field": {
                            "type": "string"
                        }
                      }
                  }
              }
            }
          }
        }'
        
        curl -XPUT 127.0.0.1:9200/test_index/test_parent/parent1 -d '
        {
            "test_filter_field" : "1"
        }'
        
        curl -XPUT 127.0.0.1:9200/test_index/test_child/child4?parent=parent1 -d '
        {
            "test_non_nested_field": "non_nested_term_field11"
        }'
        
        curl -XPUT 127.0.0.1:9200/test_index/test_child/child5?parent=parent1 -d '
        {
            "test_non_nested_field": "non_nested_term_field11"
        }'
        
        curl -XPOST 127.0.0.1:9200/test_index/test_parent/_search?pretty=true -d '
        {
          "aggs": {
            "top": {
              "filter": {
                "term": {
                  "test_filter_field": "1"
                }
              },
              "aggs": {
                "children.nested.filter": {
                  "children": {
                    "type": "test_child"
                  },
                  "aggs": {
                    "field": {
                      "terms": {
                        "field": "test_child.test_non_nested_field"
                      }
                    }
                  }
                }
              }
            }
          }
        }
        '

It gives me 

        "aggregations" : {
        "top" : {
          "doc_count" : 1,
          "children.nested.filter" : {
            "doc_count" : 2,
            "field" : {
              "doc_count_error_upper_bound" : 0,
              "sum_other_doc_count" : 0,
              "buckets" : [ {
                "key" : "non_nested_term_field11",
                "doc_count" : 2  <------ I expect it here to give me 1
              } ]
            }
          }
        }
        }

Here is equal search query, which gives correct result

        curl -XPOST 127.0.0.1:9200/test_index/test_parent/_search?pretty=true -d '
        {
            "query": {
                "has_child": {
                    "query": {
                        "multi_match": {
                            "query": "non_nested_term_field11",
                            "fields": [
                                "test_non_nested_field"
                            ]
                        }
                    },
                    "type": "test_child"
                }
            }
        }

response

        {
        
          "hits" : {
            "total" : 1,  <--- obviously correct
            "max_score" : 1.0,
            "hits" : [
                {
                  "_index" : "test_index",
                  "_type" : "test_parent",
                  "_id" : "parent1",
                  "_score" : 1.0,
                  "_source": {
                        "test_filter_field" : "1"
                  }
                }
            ]
          }
        }

**Comment by clintongormley** [comment]
Hi @serj-p 

The right place to ask questions like these is in the forums: http://discuss.elastic.co/

We reserve the github issues list for bug reports and feature requests

thanks
