### ISSUE TITLE
[Ingest] Add De-dot Processor

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#15944]
Since fields with dots in the name are disallowed from being indexed, it is useful to have an ingest processor that can help replace those `.`s into some other character (e.g. `_`).

**Comment by talevy** [comment]
@martijnvg @javanna 
I started the work for this here: https://github.com/elastic/elasticsearch/compare/feature/ingest...talevy:ingest-dedot-processor?expand=1
but I have a few questions about its functionality.

should this recursively search and replace across all fields? should we supply a list of fields?

I left it to only search and replace across top-level fields. I also noticed some behavior that I thought was unexpected within the mustache templating against documents with dots in them. I added two tests to demonstrate the existing behavior.

**Comment by javanna** [comment]
I left a couple of comments on your commit. I think we should look for fields that contain dots recursively. I had a look at the mustache tests and left comments about those too.

**Comment by eskibars** [comment]
+1 to doing this recursively

**Comment by talevy** [comment]
processor merged into `feature/ingest` branch. closing.

**Comment by animageofmine** [comment]
What happened to dedot processor? Was this removed or replaced with something else?
