### ISSUE TITLE
Misleading error message for geo_point parse failure

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#15965]
Even without enabling `geohash` functionality for the `geo_point` type, if it fails to parse a string in the format of `"<lat>,<lon>"`, then it throws a misleading error:

```
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: the character '.' is not a valid geohash character
```

It would be extremely useful to show the:
- Name of the malformed field
- The value of the malformed field (in addition to the reason the field failed to parse)

In my case, a field was accidentally mapped as a `geo_point` when it was meant to be an IP address, which made it hard to determine which field was the cause.

``` json
{
  "ipv4_src_addr" : "127.0.0.1"
}
```

**Comment by mortonsykes** [comment]
Hi i am new to Elastic Search and would be interested in taking this issue.

**Comment by imotov** [comment]
It looks like the situation is a bit better now. We are now getting `unsupported symbol [.] in geohash [127.0.0.1]` but I think we can improve it by adding the field name and type as well.
