### ISSUE TITLE
Does one Index and one type support multiple types or formates?

### ISSUE THREAD

**Issue by yzprofile** [elastic/elasticsearch#15960]
Does one Index and one type support multiple types or formates?

For example:

```json
POST /maptest/
{
  "mappings": {
    "_default_": {
      "properties": {
        "time": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss.SSS",
          "format": "yyyy-MM-dd HH:mm:ss"
        }
      }
    }
  }
}
```

There is a field has two formats under one index/type.

**Comment by jasontedor** [comment]
You can specify multiple formats using `||` since #169.

For future reference, questions are best asked on [discuss](https://discuss.elastic.co); GitHub is for filing feature requests and bug reports.
