### ISSUE TITLE
_recovery api shows negative metrics after translog replay

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#15974]
Tested on 2.1.1:

```
      "translog" : {
        "recovered" : 13,
        "total" : -1,
        "percent" : "-1.0%",
        "total_on_start" : -1,
        "total_time_in_millis" : 340
      },
```

I have 13 entries in the translog for a shard, once it is done replaying on startup, if I hit the _recovery api and look at the translog section for the shard, it shows 13 recovered.  But the percent and total metrics are negative which is misleading.

**Comment by micpalmia** [comment]
I also have recently seen this, on 2.1.0, on three shards stuck in `TRANSLOG` stage after an unfortunate index `_open`/`_close` procedure went bad.

Unfortunately, I did not fully understand what happened, but seeing those negative metrics in the `translog` section lead me to think the the index must have been corrupted.

**Comment by durera** [comment]
I've been seeing similar since we moved to 2.1 along with length recovery times when we hit translog stage
```
translog: {
  recovered: 16207,
  total: -1,
  percent: "-1.0%",
  total_on_start: -1,
  total_time_in_millis: 1511096
}
```

**Comment by robison** [comment]
Same. Been seeing exceptionally long recovery times for just a handful of not incredibly large shards.

`  "translog": {
    "recovered": 2413666,
    "total": -1,
    "percent": "-1.0%",
    "total_on_start": -1,
    "total_time": "4.5h",
    "total_time_in_millis": 16535797
  },`
