### ISSUE TITLE
fuzziness=auto doesn't work in query string query

### ISSUE THREAD

**Issue by masaruh** [elastic/elasticsearch#15972]
https://gist.github.com/masaruh/55deca377b6ade5847de
(on 1.x, it's always `~2`)

Probably because it always uses fixed value https://github.com/elastic/elasticsearch/blob/v2.1.1/core/src/main/java/org/apache/lucene/queryparser/classic/MapperQueryParser.java#L141

Probably it should be something like?
```
        if (fuzzySlop.image.length() == 1) {
            return getFuzzyQuery(qfield, termImage, settings.getFuzziness().asDistance(termImage));
        }
```

**Comment by clintongormley** [comment]
We should probably change the default fuzziness ( eg `foo~`) to use `AUTO` instead of `2`
