### ISSUE TITLE
Java Client ES 2.1 Java Hash Map key removal

### ISSUE THREAD

**Issue by serxhio** [elastic/elasticsearch#15980]
In my java project i use several java objects which contain java HashMaps among other fields. All serialization is performed correctly up the java client comunication with the node but something goes wrong upon key removal.  Everytime i remove a key from a java HashMap the key removal is not reflected on the stored document. Adding or updating keys on the java HashMap is performed correctly. Furthermore, interacting directly with the ES APIs won't result in this bug. Everything is ok.

So my best guess is that the java client detects a NoOp on the update request after i remove i json property although this happens only for properties derived from hashmaps. I'd exclude the Jackson Object Mapper fault since the generated json is correct.

What am i doing wrong?

I wrote a simple java testcase to show this behaviour

```java


	   	//create an object mapper
	   	mapper = new ObjectMapper();
	   	mapper.configure(Feature.WRITE_DATES_AS_TIMESTAMPS, true);
	   	mapper.configure(DeserializationConfig.Feature.FAIL_ON_UNKNOWN_PROPERTIES, false);
	   	mapper.configure(SerializationConfig.Feature.REQUIRE_SETTERS_FOR_GETTERS, true);

	   	//create a hashmap with one key
		Map<String,String> map = new HashMap<String,String>();
		map.put("key", "value");
		
		//index the document
		//sent json is: '{"key":"value"}'
		this.client.prepareIndex("restaurants", "Restaurant", "id1")
        .setSource(mapper.writeValueAsString(map)).execute().actionGet();
		
		//remove the key from map and update the document
		//sent json is: '{}'
		map.remove("key");
		this.client.prepareUpdate("restaurants", "Restaurant", "id1")
        .setDoc(mapper.writeValueAsString(map)).execute().actionGet();
		
		//retrieve the document, no key expected  
		//returned json is: '{"key":"value"}'
		GetResponse response = this.client.prepareGet("restaurants", "Restaurant", "id1").execute()
        .actionGet();
		
		//test fails
		Map<String,String> updatedMap = mapper.readValue(response.getSourceAsString(), new HashMap<String,String>().getClass());
		assertTrue(!updatedMap.containsKey("key"));
```

**Comment by clintongormley** [comment]
@nik9000 could you have a look at this please?

**Comment by javanna** [comment]
@serxhio I don't think noop is a problem here. You cannot remove fields when providing a partial document with the update api. You can only add new ones or replace existing ones. The existing document is merged with the partial one, so if you provide an empty map, it doesn't mean that the existing document should become empty after the update. The only way to do what you need is to use a script, as shown in our docs [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_scripted_updates). Closing as this is the expected behaviour of the update api, feel free to reopen if there's anything I missed.

**Comment by serxhio** [comment]
Ah ok. I think i misunderstood the docs. I though the update would completely replace the existing json with the updated json. In my real project, i do the following steps:
retrieve the original json
deserialize it in a java object
remove a field from the hashmap
serialize it back in json
update the existing json with the new. 

So, i don't understand why my update whould be considered a partial update since i'm providing the whole document with just one single field removed. The thing is that the update-REST-API is performing a full update while the java client performs a partial update (assuming the same jsons are used). Maybe there is an unkown setting for the client?

Thank you very much for your support by the way  :)

**Comment by javanna** [comment]
If you use the index api instead, the existing doc will get completely replaced with the new one, seems like this is what you need given that you already load the old document and modify it. The update api works the same on the REST layer and java layer (in fact the REST layer uses the java api underneath). If you see some difference there, sounds like a bug so please post a recreation but I do hope that is not the case.

**Comment by serxhio** [comment]
That's awesome, so i can use the IndexRequest in order to perform a full update. That will work for me.
Thank you all very much, if fixes some troubles for me.

**Comment by javanna** [comment]
you are welcome @serxhio . if you have other questions you can join us at https://discuss.elastic.co/ .

**Comment by serxhio** [comment]
Hello, i remembered i measured the differences between the java client and the rest apis by hand. In order to bring evidences i managed (i'm sorry, i was really in a hurry) to quickly create a test case that shows these difference in updates. I hope i'm wrong  :)

There are two tests that perform the same tasks: index,update,get.
The java client returns a different result respect to the rest apis.

[ESPartialUpdates.zip](https://github.com/elastic/elasticsearch/files/90712/ESPartialUpdates.zip)

**Comment by javanna** [comment]
please join us on [discuss](https://discuss.elastic.co/), this doesn't seem like a bug but more questions on how to use the elasticsearch apis. Thank you!
