### ISSUE TITLE
Mapping for alphabetical order with location

### ISSUE THREAD

**Issue by antondachauer** [elastic/elasticsearch#15986]
I have a bug in combination with symfony2, distance search and alphabetical sorting. Please take a look on the description on stackoverflow: http://stackoverflow.com/questions/34725089/elasticsearch-mapping-for-alphabetical-order-with-location

Thanks for helping!

**Comment by clintongormley** [comment]
Hi @antondachauer 

The best place to ask questions like these is in the forum: http://discuss.elastic.co/

thanks
