### ISSUE TITLE
Use Azure Storage emulator for integration tests

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#15987]
If available on the machine we are running our tests (which is something we can detect by checking `storageConnection` system property), we can use the [Azure Storage emulator](https://azure.microsoft.com/en-us/documentation/articles/storage-use-emulator/) to run snapshot and restore tests which are closer to the test we run today.

According to the [source code](https://github.com/Azure/azure-storage-java/blob/master/microsoft-azure-storage-test/src/com/microsoft/azure/storage/TestHelper.java#L277-L293) and the [documentation](https://azure.microsoft.com/en-us/documentation/articles/storage-configure-connection-string/), the `storageConnection` should contain something like:

```
Account name: devstoreaccount1
Account key: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
```

**Comment by ywelsch** [comment]
Thanks @dadoonet, the emulator looks interesting. We'll relay this to the infra team, and check if we can make this part of our snapshot/restore integration tests. I'll close this issue here, because there's no need to track it in this repository.
