### ISSUE TITLE
Disabling _source prevents any further updates to mapping

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#15997]
It seems that if you disable the `_source` when first creating the index, and subsequent updates to the mapping will fail with `Merge failed with failures {[Cannot update enabled setting for [_source]]}`, even if the update doesn't change `_source` at all.

Tested on ES 2.1

```json
{
   "name": "Domo",
   "cluster_name": "elasticsearch",
   "version": {
      "number": "2.1.0",
      "build_hash": "72cd1f1a3eee09505e036106146dc1949dc5dc87",
      "build_timestamp": "2015-11-18T22:40:03Z",
      "build_snapshot": false,
      "lucene_version": "5.3.1"
   },
   "tagline": "You Know, for Search"
}
```

### Example

```js
DELETE /data

PUT /data
{
    "mappings": {
        "data": {
            "_source": {
                "enabled": false
            },
            "properties": {
                "float": {
                    "type": "float"
                },
                "double": {
                    "type": "double"
                }
            }
        }
    }
}

GET /data/_mapping
```
```json
{
   "data": {
      "mappings": {
         "data": {
            "_source": {
               "enabled": false
            },
            "properties": {
               "double": {
                  "type": "double"
               },
               "float": {
                  "type": "float"
               }
            }
         }
      }
   }
}
```

All good, but if we try to update the mapping:

```js
PUT /data/_mapping/data
{
   "properties": {
      "long": {
         "type": "long"
      }
   }
}
```
```json
{
   "error": {
      "root_cause": [
         {
            "type": "merge_mapping_exception",
            "reason": "Merge failed with failures {[Cannot update enabled setting for [_source]]}"
         }
      ],
      "type": "merge_mapping_exception",
      "reason": "Merge failed with failures {[Cannot update enabled setting for [_source]]}"
   },
   "status": 400
}
```

If you repeat the process without touching `_source`, everything works as expected:

```js
DELETE /data

PUT /data
{
    "mappings": {
        "data": {
            "properties": {
                "float": {
                    "type": "float"
                },
                "double": {
                    "type": "double"
                }
            }
        }
    }
}

GET /data/_mapping

PUT /data/_mapping/data
{
   "properties": {
      "long": {
         "type": "long"
      }
   }
}

GET /data/_mapping
```
```json
{
   "data": {
      "mappings": {
         "data": {
            "properties": {
               "double": {
                  "type": "double"
               },
               "float": {
                  "type": "float"
               },
               "long": {
                  "type": "long"
               }
            }
         }
      }
   }
}
```

And it doesn't seem to matter if you enable or disable _source, both cases will cause the error.  It seems to be the presence of specifying _source that breaks future updates.

**Comment by polyfractal** [comment]
I should note, if you explicitly set `_source` in your update it works as expected:

```js
PUT /data/_mapping/data
{
   "_source": {
      "enabled": false
   },
   "properties": {
      "long": {
         "type": "long"
      }
   }
}
```

**Comment by rjernst** [comment]
It looks to me like this would also be an issue with some other metadata mappers, eg `_timestamp`. The issue is currently when initializing the builder for a type (eg when parsing mappings), we use the current fieldtype for each current metadata mapper to get a metadata mapper for that specific type (so that by default it will match the metadata mapper used by other document types). However, we really need the entire metadata mapper, since there are settings like this that are not part of the field type. Also, SourceFieldMapper does not even use the existing field type (although that does not matter in this case).

**Comment by clintongormley** [comment]
Same thing goes for `_parent`:

    PUT t 
    {
      "mappings": {
        "parent": {},
        "child": {
          "_parent": {
            "type": "parent"
          }
        }
      }
    }
    
    PUT t/_mapping/child
    {
      "properties": {}
    }

Returns:

    {
      "error": {
        "root_cause": [
          {
            "type": "illegal_argument_exception",
            "reason": "The _parent field's type option can't be changed: [parent]->[null]"
          }
        ],
        "type": "illegal_argument_exception",
        "reason": "The _parent field's type option can't be changed: [parent]->[null]"
      },
      "status": 400
    }
