### ISSUE TITLE
Querying by boolean nested value doesn't work

### ISSUE THREAD

**Issue by manioc2015** [elastic/elasticsearch#16007]
When querying a collection that has a nested type, the following exception gets thrown:

 Exception: {"error":{"root_cause":[{"type":"query_parsing_exception","reason":"[nested] nested object under path [catalogs] is not of nested type","index":"products","line":1,"col":259}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"products","node":"yQ55LabWQiiYmw2bUP041Q","reason":{"type":"query_parsing_exception","reason":"[nested] nested object under path [catalogs] is not of nested type","index":"products","line":1,"col":259}}]},"status":400}

Here is the JSON query:

{"from":0,"size":0,"sort":[{"name.raw":{"order":"asc","ignore_unmapped":true}}],"aggregations":{"manufacturers":{"terms":{"field":"manufacturer.id","size":40000}},"category":{"terms":{"field":"category.id","size":40000}}},"query":{"bool":{"must":[{"nested":{"path":"catalogs","query":{"bool":{"must":[{"match":{"catalogs.id":"55cdeece0a41216c008b4584"}},{"match":{"catalogs.status":"visible"}}]}}}}]}}}

Here is the index mapping:

                'catalogs'     => array(
                    'type'       => 'nested',
                    'include_in_parent' => true,
                    'properties' => array(
                        'id'     => array('type' => 'string'),
                        'status' => array('type' => 'string')
                    )
                )

**Comment by clintongormley** [comment]
Hi @manioc2015 

You have provided only snippets of the example, not a full recreation, so it is difficult to guess exactly where you are going wrong, but here's a recreation that shows that things do work correctly:

    PUT t
    {
      "mappings": {
        "t": {
          "properties": {
            "catalogs": {
              "type": "nested",
              "include_in_parent": true,
              "properties": {
                "id": {
                  "type": "string"
                },
                "status": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
    
    PUT t/t/1
    {
      "manufacturer": {
        "id": "xxx"
      },
      "category": {
        "id": "yyy"
      },
      "catalogs": {
        "id": "55cdeece0a41216c008b4584",
        "status": "visible"
      }
    }
    
    GET _search
    {
      "from": 0,
      "size": 0,
      "sort": [
        {
          "name.raw": {
            "order": "asc",
            "ignore_unmapped": true
          }
        }
      ],
      "aggregations": {
        "manufacturers": {
          "terms": {
            "field": "manufacturer.id",
            "size": 40000
          }
        },
        "category": {
          "terms": {
            "field": "category.id",
            "size": 40000
          }
        }
      },
      "query": {
        "bool": {
          "must": [
            {
              "nested": {
                "path": "catalogs",
                "query": {
                  "bool": {
                    "must": [
                      {
                        "match": {
                          "catalogs.id": "55cdeece0a41216c008b4584"
                        }
                      },
                      {
                        "match": {
                          "catalogs.status": "visible"
                        }
                      }
                    ]
                  }
                }
              }
            }
          ]
        }
      }
    }

It sounds like you have something incorrect, rather than there being a bug. Please ask these questions (with more details, and the version of ES that you're using) in the forums: http://discuss.elastic.co/
