### ISSUE TITLE
Shadow Replicas require path.shared_data on every node

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#16006]
Instead of requiring the setting to exist on just the data nodes, it is required to be set on every node.

https://github.com/elastic/elasticsearch/blob/c50b22f95f48119213156bdb634925e1be91b794/core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataCreateIndexService.java#L465

``` java
String customPath = settings.get(IndexMetaData.SETTING_DATA_PATH, null);
List<String> validationErrors = new ArrayList<>();

if (customPath != null && env.sharedDataFile() == null) {
    validationErrors.add("path.shared_data must be set in order to use custom data paths");
}
```

The code just checks for the lack of existence for the relevant settings, but it doesn't confirm that _it_ is a data node before causing a validation error.

**Comment by dakrone** [comment]
Shadow replicas have been removed and this is no longer applicable
