### ISSUE TITLE
[Ingest] Documentation needs updating

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#16009]
After ingest was moved into core, its `docs/plugins/ingest.md` was not updated to reflect some of the changes.

This issue is here to track the progress of documentation for the Ingest Node.

**Comment by talevy** [comment]
Here are some docs around `on_failure` handling that was missing from the asciidoc

https://github.com/elastic/elasticsearch/pull/16203

**Comment by talevy** [comment]
a PR for some cleanup action items we discussed: https://github.com/elastic/elasticsearch/pull/16216

**Comment by martijnvg** [comment]
@debadair @dedemorton We have updated the docs and added missing information:
* https://github.com/elastic/elasticsearch/blob/master/docs/reference/ingest/ingest.asciidoc
* https://github.com/elastic/elasticsearch/blob/master/docs/plugins/ingest-geoip.asciidoc

The docs are ready for a review.

**Comment by inqueue** [comment]
Updates needed:

Grok 
* `match_fields` should be `fields`
* `match_pattern` should be `pattern`

All pipelines can be listed using `*`.
```
GET _ingest/pipeline/*
```

**Comment by talevy** [comment]
thanks @inqueue, I'll update these tomorrow! I also need to update the failure responses that we introduced to both PUTpipeline and _simulate

**Comment by martijnvg** [comment]
I think the docs are in a good shape now. @debadair I think we can close this issue?

**Comment by dedemorton** [comment]
@martijnvg I still have some changes that I want to make to the documentation this week. I don't need this issue to track the changes, though, so you can close this now if you'd like.
