### ISSUE TITLE
Invalid JSON from mapped index

### ISSUE THREAD

**Issue by elbow-jason** [elastic/elasticsearch#16003]
We were pushing geodata to an recently mapped experimental index with `uuid` as a `string`, and `location` as a `geo_point` and we received the following response. The response in invalid JSON. Any ideas what is going on?

```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 3,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "experiment",
      "_type" : "heartbeat",
      "_id" : "AVIyEFGLc78HWEmcNWkB",
      "_score" : 1.0,
      "_source":{
    "uuid": "C5115D54-3EB0-409C-86C4-B36584F9D352",
    "location": [-111.6319810041340, 33.23192642539100]
  }
}

    }, {
      "_index" : "experiment",
      "_type" : "heartbeat",
      "_id" : "AVIyEDjZc78HWEmcNWkA",
      "_score" : 1.0,
      "_source":{
    "uuid": "C5115D54-3EB0-409C-86C4-B36584F9D352",
    "location": [-111.6319810041335, 33.23192642539100]
  }
}

    }, {
      "_index" : "experiment",
      "_type" : "heartbeat",
      "_id" : "AVIyEACJc78HWEmcNWj_",
      "_score" : 1.0,
      "_source":{
    "uuid": "C5115D54-3EB0-409C-86C4-B36584F9D352",
    "location": [-111.6319810041335, 33.23192642539109]
  }
}

    } ]
  }
} 

```

**Comment by eskibars** [comment]
Can you provide a mapping & set of documents that can reproduce this?

**Comment by elbow-jason** [comment]
the mapping from `/experiment/heartbeat`:

```
{
  "experiment" : {
    "mappings" : {
      "heartbeat" : {
        "properties" : {
          "location" : {
            "type" : "geo_point"
          },
          "uuid" : {
            "type" : "string"
          }
        }
      }
    }
  }
}
```

**Comment by elbow-jason** [comment]
and the index/root info:
```
{
  "status" : 200,
  "name" : "Wyatt Wingfoot",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.5.2",
    "build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
    "build_timestamp" : "2015-04-27T09:21:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by eskibars** [comment]
Can you provide a full dump of an example query+response that fails using `curl`?

**Comment by elbow-jason** [comment]
elbow-jason@Jasons-MacBook-Pro-1781 ~/g/s/g/a/dashboard>
curl -XGET 'http://super.secret.host.com:9200/experiment/heartbeat/_search'
{"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":3,"max_score":1.0,"hits":[{"_index":"experiment","_type":"heartbeat","_id":"AVIyEFGLc78HWEmcNWkB","_score":1.0,"_source":{
    "uuid": "C5115D54-3EB0-409C-86C4-B36584F9D352",
    "location": [-111.6319810041340, 33.23192642539100]
  }
}
},{"_index":"experiment","_type":"heartbeat","_id":"AVIyEDjZc78HWEmcNWkA","_score":1.0,"_source":{
    "uuid": "C5115D54-3EB0-409C-86C4-B36584F9D352",
    "location": [-111.6319810041335, 33.23192642539100]
  }
}
},{"_index":"experiment","_type":"heartbeat","_id":"AVIyEACJc78HWEmcNWj_","_score":1.0,"_source":{
    "uuid": "C5115D54-3EB0-409C-86C4-B36584F9D352",
    "location": [-111.6319810041335, 33.23192642539109]
  }
}
}]}}

**Comment by clintongormley** [comment]
Before 2.0, Elasticsearch would accept invalid JSON without complaining, and just store it in the `_source` field.  Then, when returning the `_source`, you'd get back the same invalid JSON that you had indexed.

This looks like what happened here.
