### ISSUE TITLE
[Ingest] Add more descriptive pipeline factory errors in _simulate and PUT pipeline/id

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#16010]
When someone issues the following request to `_simulate`, The pipeline factory will error out while 
attempting to construct the supplied pipeline. The reason for this is that the `date` processor is not configured correctly, `locale` is invalid. The exception is thrown in the processor's `create` here: https://github.com/elastic/elasticsearch/blob/feature/ingest/core/src/main/java/org/elasticsearch/ingest/processor/DateProcessor.java#L130.

```json
{
            "pipeline": {
              "description": "_description",
              "processors": [
                {
                  "date" : {
                  "processor_tag" : "date_processor",
                  "match_field" : "date_source_field",
                  "target_field" : "date_target_field",
                  "match_formats" : ["dd/MM/yyyy"],
                  "locale": "UNDEFINED"
                  }
                },
                {
                  "set" : {
                    "field" : "field3",
                    "value" : "third_val"
                  }
                }
              ]
            },
            "docs": [
              {
                "_index": "index",
                "_type": "type",
                "_id": "id",
                "_source": {
                  "foo": "bar"
                }
              }
            ]
          }
```

The response from this is an internal server error. This makes it difficult to know which processor was incorrectly configured within the pipeline definition. What would be nicer is a response object that is similar to this:

```
{
 "pipeline_configuration_error": [
   {
     "errors": [
       {
         "processor_tag": "date_processor",
         "error": {
           "root_cause": [
             {
               "type": "illegal_argument_exception",
               "reason": "Invalid language tag specified: UNDEFINED"
             }
           ],
           "type": "illegal_argument_exception",
           "reason": "Invalid language tag specified: UNDEFINED"
         }
       }
     ]
   }
 ]
}
```

It would be great if we can return this processor-level configuration error to all processors that are improperly configured, instead of just the first one. This would require extra logic in the pipline factory to record exceptions and collect them into one large exception instead of throwing the first one it receives.

@martijnvg @javanna what do you think?

@BigFunger, let me know if this is what you meant? The actual response object is still up in the air.

**Comment by martijnvg** [comment]
I'm on the fence about returning all errors for misconfigured processors. I prefer to just fail immediately on the first pipeline construction error. This keeps the logic simple. I think that if there are several misconfigurations across multiple processors that having several put pipeline / simulate requests to fix the the pipeline is okay.

I'm +1 on adding more structured information (like tag) to exception we throw so that it easy to figure out what processor has been misconfigured.

**Comment by javanna** [comment]
I tend to agree with Martijn, let's do this at least in two steps: first make each single error better and descriptive, then see about cumulating errors, which can come later.

**Comment by martijnvg** [comment]
Talked about this during the weekly meeting. There is some confusion because the ingest api does two things: create a temporary pipeline and simulate how documents are processed by this pipeline.

We agreed that we should do the following:
* Errors that occur during pipeline construction should have more context. It should clear what the misconfigured processor is. This should be sufficient for anyone integrating with simulate api.
* Processors that fail badly or with a meaningless error message should be addressed on a case by case basis via separate issues.

On the ingest side we should introduce a PipelineBuildException that encapsulate the context of the failure, so that both the simulate and put pipeline api can render helpful error messages.

**Comment by Bargs** [comment]
Is there currently any documentation for the structure of the error in the JSON response, and what type of errors each endpoint is capable of throwing? That might help us better understand the difference between pipeline build errors and document processing errors, and how we should handle each in Kibana.

**Comment by talevy** [comment]
@Bargs we are still working on beefing up the docs. I'll start writing docs for this now. the error structure that we speak of here is only for the `_simulate`. all other errors will just return an internal http error with an arbitrary exception that is thrown (this is processor dependent and would be documented on a per processor basis).

**Comment by talevy** [comment]
@martijnvg cool! sounds great. I agree with the two-phase approach that @javanna mentioned. Firstly, we'll set up a `PipelineBuildException` that will provide a more structured representation of the error. I'd imagine this would include structured fields for which field of the config caused the exception, as well as a processor tag, etc.

**Comment by talevy** [comment]
I have started hacking on this here: https://github.com/talevy/elasticsearch/commit/2e351e0d97277b9ae45939f280050ecb72e357fd

I have a very clear idea on how to finish up this commit now. just need to clean up some of the factory code for containing the error and pipeline object. then update `WritePipelineResponse` to reflect the new pipeline factory error response.

didn't get a chance to finish up my thought today, will continue and should finalize it tomorrow!

**Comment by talevy** [comment]
I have updated this commit, it is super close I think.

https://github.com/talevy/elasticsearch/commit/07c5981fe4959a7ee393a462cb8fb692b4cb8fa5

a few todos/questions

* the objects holding the exception information are slightly flexible for my liking, and capture too much at times, I am open for changing them. It is just weird since sometimes pipeline errors are due to specific processor configuration fields, or they are general pipeline syntax issues. Mostly left that as a low-hanging-fruit todo item once all the transport/action layers are finalized.
* finishing up the `_simulate` support for this structured response is still incomplete: https://github.com/talevy/elasticsearch/commit/07c5981fe4959a7ee393a462cb8fb692b4cb8fa5#diff-d88dde11b6d6c66bb9acd6bbe7fadecfR61 The idea is to re-use the error object as much as possible without dirtying up the simulation response code we already have
* I have chosen to leave `WritePipelineResponse` as an `AcknowledgedResponse`, this makes the changes there pretty nice I think. All the previous code worked as is since this was the case. I simply override the `AcknowledgedRestListener` to appropriately add the additional structured error fields.

Still slightly rough around the edges. I would love to hear what aspects of ES I am not leveraging and/or suggestions on how this strategy should be changed @martijnvg @javanna.

thanks!
