### ISSUE TITLE
The total number of results in the query response is the number of documents that matched the query minus the number of documents that were post-filtered. 

### ISSUE THREAD

**Issue by jimferenczi** [elastic/elasticsearch#16021]
Simple recreation:
````
PUT t/t/0
{
    "field": "foo"
}

PUT t/t/1
{
    "field": "bar"
}

GET t/_search?size=0
{
    "query": {
        "match_all": {}
    }
}
`````
... match_all search returns the expected number of results: `total: 2`.
But with a post_filter the search returns the number of result for the query minus the ones that were were post-filtered:

````
GET t/_search?size=0
{
    "query": {
        "match_all": {}
    },
    "post_filter": {
        "term": {
            "field": "foo"
        }
    }
}
````
... so here total hits equals 1.
I don't know if it's expected, I guess it's good for the pagination but bad if you compare this number with the aggregations count (which are not exact anyway so maybe not relevant). 
I wonder if we should return the total results without the post_filter and the number of post filtered documents  like below:
````
"hits": {
      "total": 2,
      "post_filtered": 1
      "max_score": 0,
      "hits": []
}
````

**Comment by clintongormley** [comment]
This is expected.  Aggregations are run on the results of the query, and post-filters are applied to the search results AFTER aggregations are calculated.  So eg if the user searches on "red" t-shirts, you could run a query for t-shirts, with a terms agg on popular "brands" across t-shirts of all colours, then post-filter the results down to just red t-shirts.

I don't think we need to change anything here, it's working as designed.

**Comment by jimferenczi** [comment]
@clintongormley here https://github.com/elastic/elasticsearch/issues/15994 you're saying that the count should be the same and now you're saying that it's expected ? I understand that the post filter is only applied to the query part and not the aggregations but the count in the response are different.
''''
Without postfilter:
"hits":{"total":2

With postfilter:
"hits":{"total":1
''''
So my question is "should the total number of hits returned in the response be the same with and without postfilter". If the answer is yes then there is a bug and we should reopen this ticket.

**Comment by jimferenczi** [comment]
@clintongormley I am totally wrong here, sorry. If the post_filter is replaced with a filter inside the query then the number of result must be the same like you said here: https://github.com/elastic/elasticsearch/issues/15994. 
So the answer to my question in the previous comment is that it's expected. 
Closing this and moving on ;).
