### ISSUE TITLE
Match query on IP requires CIDR notation

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch#16058]
Consider the following Sense script:

```sh
DELETE /test-index

POST /test-index
{
  "mappings": {
    "test-type": {
      "properties": {
        "ip": {
          "type": "ip"
        }
      }
    }
  }
}

GET test-index/_mapping/field/ip

POST /test-index/test-type/1
{
  "ip": "192.168.0.1"
}

POST test-index/test-type/_search?size=1

POST logstash-0/apache/_search
{
  "query": {
    "match": {
      "clientip": "192.168.0.1"
    }
  }
}
```

This executes just fine in 2.x but fails at the final step in master. Since https://github.com/elastic/elasticsearch/pull/14874 the `match` query now requires that IP addresses use valid CIDR notation (`"192.168.0.1"` must be `"192.168.0.1/32"`). The pr seems clear on the point that ES shouldn't be lenient when it comes to parsing CIDR notation, but should the match query on IP address fields really only accept CIDR notation? It seems like it should accept a single IPV4 address as well.

**Comment by jpountz** [comment]
Agreed that it should.
