### ISSUE TITLE
ElasticSearch 1.7 explain API seems doesn't work

### ISSUE THREAD

**Issue by CaredduMattia** [elastic/elasticsearch#16052]
In according with documentation (https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-explain.html) i'm trying to use explain API.

curl -XGET 'localhost:9200/index/type/1/_explain?q=surname:mattia'

The result is : 
```{"_index":"neen","_type":"cliente","_id":"_explain","_version":1,"found":true,"_source":```

and not sometihng like this : 
```{
  "matches" : true,
  "explanation" : {
    "value" : 0.15342641,
    "description" : "fieldWeight(message:search in 0), product of:",
    "details" : [ {
      "value" : 1.0,
      "description" : "tf(termFreq(message:search)=1)"
    }, {
      "value" : 0.30685282,
      "description" : "idf(docFreq=1, maxDocs=1)"
    }, {
      "value" : 0.5,
      "description" : "fieldNorm(field=message, doc=0)"
    } ]
  }
}```

like documentation say.
Why it doesn't work?

**Comment by clintongormley** [comment]
This works for me:

    PUT index/type/1
    {
      "surname": "mattia"
    }
    
    GET /index/type/1/_explain?q=surname:mattia

or:

    curl -XPUT "http://localhost:9200/index/type/1" -d'
    {
      "surname": "mattia"
    }'
    
    curl -XGET "http://localhost:9200/index/type/1/_explain?q=surname:mattia"

Not sure what you're doing wrong. Maybe something with shell escaping?  Best place to ask is in the forums: http://discuss.elastic.co/
