### ISSUE TITLE
Inconsistent scoring on unscored queries

### ISSUE THREAD

**Issue by micpalmia** [elastic/elasticsearch#16050]
Checked against **Elasticsearch 2.1.1**.

An unscored query placed directly in the `query` element assign a score of 1, while the same query placed in the `filter` section of a `bool` query assigns 0s.

```bash
curl -XPOST localhost:9200/test/test/1 -d '
{
   "rank": 3
}'

# this assigns score 0 to each document
curl -XPOST /test/_search -d '
{
   "query": {
      "bool": {
         "filter": {
            "range": {
               "rank": {
                  "gte": 2
               }
            }
         }
      }
   }
}'

# this assigns score 1 to all documents
curl -XPOST localhost/test/_search -d '
{
   "query": {
      "range": {
         "rank": {
            "gte": 2
         }
      }
   }
}'
```

While, as discussed in https://github.com/elastic/elasticsearch/issues/15921, I understand that using a `constant_score` query solves the 0-score issue, I believe this behavioral difference is more a bug than a feature.

**Comment by clintongormley** [comment]
If you use a query, you get scores. If you only use filters, you don't get scores. That seems consistent to me.

**Comment by clintongormley** [comment]
Note: this is not a breaking change as it wasn't possible to specify only filters before 2.0.

**Comment by clintongormley** [comment]
@micpalmia Why do you think we should change this behaviour? How does it affect you?

**Comment by micpalmia** [comment]
You wrote:
> If you use a query, you get scores. If you only use filters, you don't get scores.

The documentation says
> Queries and filters have been merged — **all filter clauses are now query clauses**

Also, you do get scores anyways - `score` is not an optional part of the json output.

To me, those are both unscored queries - they are complete equivalents - why would they produce different scores? I understand one `range` query is in *filter context* and one is in *query context*, but what's the rationale behind query context defaulting to score 1 and filter context defaulting to score 0?

This does not affect me when writing software on top of ES, but (as already happened in the issue linked above) can be confusing. 

Obviously feel free to close if deemed irrelevant :)

**Comment by micpalmia** [comment]
Also, it seems to me that having the default score for *filter context* set to 1 could only be beneficial (in terms of consistency, least expectation, etc.).

**Comment by rmuir** [comment]
It must be the case that `filter`'d queries do not modify the score at all, that is why it is 0.

If you dont want queries to change the score, use `filter` to indicate that. Otherwise, they will.

**Comment by micpalmia** [comment]
> It must be the case that filter'd queries do not modify the score at all, that is why it is 0.

My observation was very far from suggesting that `filter`ed queries should modify the score.
The fact that filtered queries cannot modify the score, *thus* they score documents 0 does not really makes much sense to me.

**Comment by micpalmia** [comment]
I still find this mildly annoying but it seems like it's not something that people in general find problematic. Thank you for taking the time to discuss this :)
