### ISSUE TITLE
Attachment mapper plugin: configuring sub-fields per documentation results in "ClassCastException: java.lang.Integer cannot be cast to java.lang.String"

### ISSUE THREAD

**Issue by dminkovsky** [elastic/elasticsearch#16069]
Re: Attachment mapper plugin

Migrating this issue from [elastic/elasticsearch-mapper-attachments](https://github.com/elastic/elasticsearch-mapper-attachments/issues/202):

Regarding sub-field mappings, [documentation says](https://www.elastic.co/guide/en/elasticsearch/plugins/master/mapper-attachments-usage.html):

> The other fields map to their respective metadata names, but there is no need to specify the type (like string or date) since it is already known.

This is either incorrect or misleading because when I set

```
"content_length" : { "store" : true }
```

in my mapping, `content_length` was not indexed. Instead, I got (with errors ignored):

```
[2016-01-18 17:33:46,053][DEBUG][mapper.attachment        ] Ignoring MapperParsingException catch while parsing content_length: [failed to parse [data.content_length]]: [55]
```

or (with errors not ignored):

```
[2016-01-18 17:38:54,660][DEBUG][action.index             ] [Red Ronin] [live][3], node[4-sneDHnRr-n_I9iZpGmEA], [P], v[8], s[STARTED], a[id=HRjjSSzORZKvyrsV3DlDHQ]: Failed to execute [index {[live][attac
hment][1], source[{ "data": "IkdvZCBTYXZlIHRoZSBRdWVlbiIgKGFsdGVybmF0aXZlbHkgIkdvZCBTYXZlIHRoZSBLaW5nIg==" }]}]
MapperParsingException[failed to parse [data.content_length]]; nested: ClassCastException[java.lang.Integer cannot be cast to java.lang.String];
        at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:339)
        at org.elasticsearch.index.mapper.attachment.AttachmentMapper.parse(AttachmentMapper.java:605)
```

This happened because in the resulting mapping, `type` of `content_length` is `string`.

```
"content_length" : {
    "type" : "string",
    "store" : true
}
```

It appears that if you specify any properties of a subfield and omit `type`, type is `string`. So in order to store `content_length` and have it work, it must be specified completely as 

```
"content_length" : {
    "type" : "integer",
    "store" : true
}
```

This appears to be the opposite of what the documentation states.

**Comment by dadoonet** [comment]
Thanks for raising it. Do you want to contribute a doc fix?

**Comment by dminkovsky** [comment]
This looks like a wonderful opportunity to get acquainted with a simple aspect of the codebase and to contribute, but I simply have no time at all right now :(. Thank you, but I cannot.

**Comment by clintongormley** [comment]
The mapper attachment plugin is deprecated in favour of the ingest attachment plugin, so I'm going to close this issue
