### ISSUE TITLE
index.engine.internal  exception  and many full gc

### ISSUE THREAD

**Issue by tianzongqi** [elastic/elasticsearch#16079]
my ES cluster version is 1.4.2. 

print so many excption like this:

[2016-01-19 18:05:30,882][INFO ][index.engine.internal    ] [es_culrs [es_culrs.index][0] now throttling indexing: numMergesInFlight=6, maxNumMerges=5

and so many full gc. 

what's the problem?

**Comment by clintongormley** [comment]
Hi @tianzongqi 

Please ask questions like these on the forum instead: https://discuss.elastic.co/

The issues list is for bug reports and feature requests.

thanks
