### ISSUE TITLE
Sorting by _id field is bouncing

### ISSUE THREAD

**Issue by serj-p** [elastic/elasticsearch#16076]
I have a problem with consistency of ES sorting. When I order for example by date, ES gives different orderings from one query to another because of duplicate dates. To fix this we usually perform sorting by date + sorting by _id, which meant to be unique, but it isn't. Sorting by _id field only acts the same, it is bouncing. We have config of ES 1.4.1, 1 shard + 1 replica per index. When I disable replica it seems that sorting bouncing stops.

**Comment by clintongormley** [comment]
Correct - the `_id` field is neither indexed nor stored by default.  You will see that its entry in the `sort` array is `null`.  You can sort on `_uid` instead.
