### ISSUE TITLE
Thread hangs while Bulk Insert Operations

### ISSUE THREAD

**Issue by adhamelia** [elastic/elasticsearch#16074]
Hi, ES Team

we have an analytic application which uses underneath ES. our application collects various info. from diff sources and push into ES for further processing. we are using bulk insert operation to gain the optimal performance and throughput. but frequently our threads get hang or stuck while doing bulk insert operation.

can you please throw some lights on  this ??? or do we need to create some watcher that monitors the thread and if  bulk operations does not get finished within x time then watcher would kill or interrupt the thread which gets stuck or hang ??? 

it's a show stopper issue for us.

**Comment by adhamelia** [comment]
we are using 1.7.3 ES having Linux and Windows OS

**Comment by danielmitterdorfer** [comment]
Hi Alpesh,

can you describe your situation in more detail? Some questions to ponder:

* Are you using the Java client or do you use another language client?
* How do you perform bulk operations? I see you are using the 1.7 line. Starting with 2.0 we provide a helper class, called `BulkProcessor` (see [docs](https://www.elastic.co/guide/en/elasticsearch/client/java-api/master/java-docs-bulk-processor.html)). I'd be best to upgrade to the 2.x line of Elasticsearch but if this is not an option you can base your implementation on our `BulkProcessor` class. Then there is no need to manage those low level details by yourself.

If all of this does not help you, can you please provide an isolated example project that demonstrates the problem?

**Comment by adhamelia** [comment]
Thanks Daniel for your prompt response.

we are using java api [Node Client] with following bulk processor settings.

 .setBulkSize(new ByteSizeValue(TraceOrgServerConstants.ES_BULK_REQUEST_FLUSH_SIZE_IN_MB, ByteSizeUnit.MB))
                        .setFlushInterval(TimeValue.timeValueSeconds(TraceOrgServerConstants.ES_BULK_REQUEST_FLUSH_TIME_IN_SECOND))
                        .setConcurrentRequests(1)
                        .build();


ES_BULK_REQUEST_FLUSH_SIZE_IN_MB =100

ES_BULK_REQUEST_FLUSH_TIME_IN_SECOND =30

**Comment by adhamelia** [comment]
Our  Testing System Conf

1 DATA NODE [8 GB RAM/6 CORE CPU] [VIRTUAL MACHINE] [CENT OS 6.6]

1 SHARD

0 REPLICATION

**Comment by adhamelia** [comment]
if we migrate from 1.x to 2.x then will require so much time and resources :(

there is an huge api changes in 2.x

**Comment by s1monw** [comment]
> there is an huge api changes in 2.x

I do apologize for this but that's the right time to add breaking improvements. I highly recommend you to go to 2.x asap.

**Comment by danielmitterdorfer** [comment]
How did you arrive at a bulk index size of 100MB? You can have a look at the section [Using and Sizing Bulk Requests](https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-performance.html#_using_and_sizing_bulk_requests) in the docs. A few thoughts:

* You should look where the bottleneck is: network, CPU usage, I/O
* You could benefit from a smaller bulk size
* You may also increase the number of concurrent requests (depending on the outcome of your investigation of the bottleneck)

For future reference, we have a [discussion forum](https://discuss.elastic.co/) for such questions.

**Comment by adhamelia** [comment]
Thanks guys !!!

ya, I know 100 MB is too large. in past,we tried on 10-15 MB bulk size but still it did not work.

for concurrency, if  we increase it,  ES behaves strange.

right now we are using  concurrent request = 1 and it works for  a while but if load gets increased then bulk index eats our all threads.

we are definitely thinking about 2.x but right now, we are looking for a cheaper alternative by tweaking some ES conf.

**Comment by danielmitterdorfer** [comment]
> ya, I know 100 MB is too large. in past,we tried on 10-15 MB bulk size but still it did not work.

What happened, when you used a smaller bulk size?

> for concurrency, if  we increase it,  ES behaves strange.

Can you describe what type of strangeness you experience then?

> right now we are using  concurrent request = 1 and it works for  a while but if load gets increased then bulk index eats our all threads.

Have you looked resource usage? There must be something causing blocked threads. I suggest you go through these guides:

* [Indexing Performance Tips](https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-performance.html)
* [Performance Considerations for Elasticsearch Indexing](https://www.elastic.co/blog/performance-considerations-elasticsearch-indexing)

**Comment by adhamelia** [comment]
thanks guys ... finally the issue has been fixed... :)

we stopped sharing bulk processor instance across threads. now,each thread has own copy of bulk processor 

5k docs/sec achieved !!!

**Comment by danielmitterdorfer** [comment]
Hi, Alpesh,

good to hear that you've resolved your problem. Nevertheless, this sounds to me that you have (or had?) a problem elsewhere in your code. You should also get decent throughput if you have just one bulk processor instance so you might want to take a second look at your code. Did you lock on the bulk processor instance previously, i.e. did you have something like this in your code?

```java
synchronized (bulkProcessor) {
  // ... do something here
}
```
This shouldn't be necessary and would explain why you had problems with throughput previously.

**Comment by adhamelia** [comment]
no we did not do that.. we never block our akka actor ...

even i am surprised when came to know that threads were blocking on bulk processor method 

private synchronized void internalAdd(ActionRequest request, @Nullable Object payload) {
        bulkRequest.add(request, payload);
       executeIfNeeded();
   }

**Comment by danielmitterdorfer** [comment]
Well, it seems we have found your contention point. Yes, bulk processor is blocking, so your other actors will not be able to make progress in case the bulk request limit is hit (if you share the bulk processor instance). The usage model for bulk processor is just not a good fit for actors.

With your solution you have eliminated this contention point. Another idea you could try is to create a dedicated actor that owns the sole bulk processor instance and just send messages to this actor. To me this feels more natural than giving each actor its own bulk processor instance and I think it's also easier to test.

**Comment by bleskes** [comment]
> The usage model for bulk processor is just not a good fit for actors.

Just a note that the bulk processor still gives you nice retry properties and back pressure logic from ES. You can use async handling and set the semaphore limiting concurrent requests to something that's high enough to fit your need. Also, having one processor means that data will be sent faster to ES as messages from all actors count towards the quota to send a bulk
