### ISSUE TITLE
Reduce scroll timeout in example

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#16075]
[Here](https://www.elastic.co/guide/en/elasticsearch/client/java-api/2.1/java-search-scrolling.html) we have `60000ms` as the timeout, but [here](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/search-request-scroll.html#scroll-search-context) we state;
> Its value (e.g. 1m, see the section called “Time unitsedit”) does not need to be long enough to process all data — it just needs to be long enough to process the previous batch of results

Which seems at opposites.

I'd suggest we update the java docs and reduce the figure in the example.

(Reported via twitter - https://twitter.com/xavierfacq/status/689116646124957696)

**Comment by jasontedor** [comment]
60000ms is 1m.

**Comment by xavierfacq** [comment]
The first TimeValue is well setted to 1 minute (60000ms) but the second, in the while-loop is setted to 600000ms = 10 minutes.

**Comment by jasontedor** [comment]
@xavierfacq Thanks for clarifying.
