### ISSUE TITLE
ability to have init script for scripted fields or scripted filters

### ISSUE THREAD

**Issue by yehosef** [elastic/elasticsearch#16080]
I have have a set of documents which have a field of dates when a user did an action.  I want to look through and count the number of dates they have in a specified range. I was  make the requests with string dates like "2015-12-01" and using a `SimpleDateFormat` to convert the string to a Long for conversion.  The groovy script is:

    sdf = new java.text.SimpleDateFormat('yyyy-MM-dd');
    sdf.setTimeZone(TimeZone.getTimeZone('GMT+0')); 
    start = sdf.parse(start_date).getTime();
    end = sdf.parse(end_date).getTime();
    dates = doc['dates'].values.findAll { it>=start && it<=end  }; 
    return dates.size()>limit

The performance is actually pretty good - this runs on around 3 seconds for 1.5M documents on a 3 machine cluster.

But really on each document I'm creating a new SimpleDateFormat and parsing the string dates, even though it's the same for each document.

If I instead convert this to a timestamp before, the script becomes

    dates = doc['dates'].values.findAll { it>=start_ts && it<=end_ts}}  }; 
    return dates.size()>limit ;

and it runs in less than half the time.  This works and is fine, but it loses the convenience of having an easy to read date like `2015-12-01` and instead uses `1448928000000`.  It also would be nice to be able to specify the range with single date and number of days before - if I had a script that could run first and then setup the variables, this would be easy and fast.

My particular case is using templated queries, so perhaps it could even been added as a script to modify the variables before the template (I need to run this type of query with other permutations so the time savings add up.)  But even for simple scripted fields queries this can be valuable when I need have a common setup.  

I currently feel this most with dates - but it could have implications for other queries where I want need to build a common situation for comparison.

**Comment by clintongormley** [comment]
Hi @yehosef 

I understand what you're asking for and I can see the benefits, but it would end up making the scripting API horribly over complicated.  I think, if you need to do this, then the right approach would be to make a native (ie Java) script which already supports this kind of initialization.

**Comment by yehosef** [comment]
I've been considering making a native script.   I hear what you're saying about making the API complicated since it might be different per scripted application (eg, scripted filters vs fields vs aggregations).  Would it be possible to allow such an approach with either indexed or file-based scripts.  

Would that simplify things at all?  It seems unfortunate that I need to resort to writing and compiling a java class in order to initialize some variables.

**Comment by jpountz** [comment]
We discussed this issue in fixit friday and agreed with @clintongormley's analysis: we understand the need for such a feature but don't want to make the scripting API more complicated in order to support an initialization phase.
