### ISSUE TITLE
Still getting "high disk watermark exceeded on one or more nodes, rerouting shards"

### ISSUE THREAD

**Issue by najamss** [elastic/elasticsearch#16082]
With reference to #15919, I have changed the share path to SAN volume instead of NAS but still getting the same error. Is there any issue with Elasticsearch if path.data is shared volume?

**Comment by dakrone** [comment]
@najamss do you mean this warning?

```
 [WARN ][cluster.routing.allocation.decider] [Desmond Pitt] high disk watermark [0b] exceeded on [O2-Ef7fET9S_MJNAL-q_yA][Desmond Pitt] free: -1b[100%], shards will be relocated away from this node
```

If so, that means that your JVM is still not reporting disk numbers for that mount

**Comment by najamss** [comment]
Well, I got the same reply before as well. What can I do to fix it?

**Comment by dakrone** [comment]
@najamss you can disable the disk-based allocation using ` cluster.routing.allocation.disk.threshold_enabled `, see https://www.elastic.co/guide/en/elasticsearch/reference/2.1/disk-allocator.html

In the future though, these questions should be opened on https://discuss.elastic.co

**Comment by najamss** [comment]
In fact, I opened this question over there but they asked me to open here. To disable the setting, is this command correct?

curl -XPUT localhost:9200/_cluster/settings -d '{"persistent" : {"cluster.routing.allocation.disk.threshold_enabled": False}}'

Second, if these warnings are being generated, will it stop dumping the logs to disk because this is what happening right now?

**Comment by tscung** [comment]
I think it should be curl -XPUT localhost:9200/_cluster/settings -d '{"persistent" : {"cluster.routing.allocation.disk.threshold_enabled": false}}'

**Comment by dami95** [comment]
```curl -XPUT mymenu_elasticsearch:9200/_cluster/settings -H "Content-Type: application/json" -d '{"persistent" : {"cluster.routing.allocation.disk.threshold_enabled": false}}'`` :)
