### ISSUE TITLE
Elastic search not recognizing --cluster.name and --node.name parameter

### ISSUE THREAD

**Issue by harishkannarao** [elastic/elasticsearch#16086]
Hi Team,

I had downloaded elasticsearch-2.1.1.zip and tried to change the node name through command line as given in the following documentation page:
https://www.elastic.co/guide/en/elasticsearch/reference/current/_installation.html

>elasticsearch.bat --cluster.name my_cluster_name --node.name my_node_name

I get the following error:
Unrecognized option: --cluster.name

**Comment by brwe** [comment]
This is a bug. Pull request to fix it is here: https://github.com/elastic/elasticsearch/pull/15320

**Comment by clintongormley** [comment]
Closed by #15320

**Comment by chandankmr** [comment]
@brwe this bug persists in version 5.5.1 as well. i have tested it on ubuntu 15.04 .Please suggesst a fix for this.

**Comment by jasontedor** [comment]
@chandankmr The short answer to your question is that parameters of the form expressed here are not supported in Elasticsearch 5.x. This is covered in the [migration docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_settings_changes.html#_removed_using_double_dashes_to_configure_elasticsearch) and elsewhere in the docs. If you require additional general help, please ask on the [forum](https://discuss.elastic.co).
