### ISSUE TITLE
document classloader whitelisting

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#16094]
As of 2.0, we restrict groovy scripts to run with minimal permissions

For 2.2 we apply same restrictions to python and javascript (https://github.com/elastic/elasticsearch/pull/13924), and we whitelist classloaders for all scripting engines by default (https://github.com/elastic/elasticsearch/pull/15262)

I expect a long tail of issues opened (e.g. crazy things happening in scripts), but the whitelisting is customizable for extreme cases via java's security configuration, as friendly as I could make it (e.g. supports wildcards), just not documented. 

I can provide some examples (e.g. disable whitelisting completely, add classes/packages, whatever). The whitelisting also doesn't happen if security manager is disabled.

**Comment by s1monw** [comment]
good call @rmuir thanks for picking this up @clintongormley can you take a look at this and maybe come up with some good way of documenting it?

**Comment by clintongormley** [comment]
@rmuir if you could provide some examples, i'd be happy to write it up as docs and find somewhere to put it.  thanks

**Comment by rmuir** [comment]
Do you think the simplest solution is to just document disabling security manager if you are unhappy with the whitelisting? Its easier to think about, less risky as far as breaking everything in confusing ways (e.g. invalid syntax or whatever in security configuration).

I really think we should avoid using it as a cop-out, but we have a new scripting language as a long term solution?

**Comment by clintongormley** [comment]
I think most people would prefer to run with the security manager enabled, unless they really can't make things work, so it is probably worth the effort documenting whitelisting.  I'm assuming it's not too hard to do, and it'll be for the minority of users.

**Comment by rmuir** [comment]
ok, i was just thinking if you were security-conscious at all, you wouldn't be wanting scripts to do even more :) And enable/disable security manager completely would be simpler than changing java security config.

if someone wants to tweak this in a fine-grained way, then they need to add lines to their policy file, either system wide (`$JAVA_HOME/lib/security/java.policy`), or in their user's home directory (`~/.java.policy`), or from a file specified via commandline (`-Djava.security.policy=someURL`). See http://docs.oracle.com/javase/7/docs/technotes/guides/security/PolicyFiles.html for more information.

grant entries would look like this:

```
grant {
    permission org.elasticsearch.script.ClassPermission "java.util.Base64"; // allow class
    permission org.elasticsearch.script.ClassPermission "java.util.*"; // allow package
    permission org.elasticsearch.script.ClassPermission "*"; // allow all (disables filtering basically)
};
```

See https://github.com/elastic/elasticsearch/blob/01ce49e94ee7dcd9a8696b53a84e2a0184284a93/core/src/main/java/org/elasticsearch/script/ClassPermission.java#L31-L73 for more details of that.

**Comment by clintongormley** [comment]
thanks @rmuir - i'll give it a shot in a pr
