### ISSUE TITLE
bulk api: opt out individual item responses

### ISSUE THREAD

**Issue by mrkamel** [elastic/elasticsearch#16102]
Is it possible to hide the individual item responses from the bulk response via some param? Often i'm just interested into the all or nothing response, such that checking errors: true/false is enough, but i have to parse the full json response just to do that.

**Comment by nik9000** [comment]
Have you tried [response filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#_response_filtering)? I've not tried it myself but I imagine it should work at shrinking the response. You should be careful and make sure that you keep enough information so you can be sure that the data made it and one of the responses wasn't some kind of error.

**Comment by mrkamel** [comment]
perfect, thx, didn't know about that.
