### ISSUE TITLE
multi-fields query could not match any document

### ISSUE THREAD

**Issue by robin820224** [elastic/elasticsearch#16106]
I have created an index naming "test1", which included a msg property. The msg property used  smartcn analyzer, it was include an field naming "original" that was not analyzed.  And then inserted an document. The command likes following:

PUT http://localhost:9200/test1
{
  "mappings": {
    "my_type": {
      "properties": {
        "msg": {
          "type": "string",
		  "analyzer" :"smartcn",
          "fields": {
            "original": { 
              "type":  "string",
              "index": "not_analyzed"
            }
          }
        }
      }
    }
  }
}

PUT http://localhost:9200/test1/mytype/1
{
	"msg" : "我是中国人"
}

When I used the prefix query to match msg.original field, I could not match my document.  How could I match this document using prefix query for msg.original field? The commend like this:

POST http://localhost:9200/test1/_search?pretty
{
    "query": {
        "prefix": {
            "msg.original": "我"
        }
    }
}

**Comment by johtani** [comment]
@robin820224  You create `my_type` mapping, but you register the data to `mytype`.

Please ask these questions in the forums: http://discuss.elastic.co/

**Comment by selfchanger** [comment]
说中国话就是：你的my_type是个映射，不是索引，你应该往索引里存数据

**Comment by robin820224** [comment]
yes, it works when I re-register the data to my_type.
