### ISSUE TITLE
Reroute and replica shards that return

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#16113]
The warning at the bottom of [this page](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-reroute.html] states;

> The allow_primary parameter will force a new empty primary shard to be allocated without any data. If a node which has a copy of the original primary shard (including data) rejoins the cluster later on, that data will be deleted: the old shard copy will be replaced by the new live shard copy.

If there are no applicable replicas to promote and a user force allocates the primary, we will then create a new replica containing the same amount of data as this new primary (ie probably empty).

But if we had a copy of the replica on another unavailable node - eg if we had multiple nodes drop out that happened to have the primary and replica of the same shard - I presume we also ignore the old replica? Should we update this warning to include this?

**Comment by bleskes** [comment]
I'm not sure I follow you...

>  if we had multiple nodes drop out that happened to have the primary and replica of the same shard 

In this case we wait for the nodes to come back. If someone force allocate an empty primary in that period the same thing will happen indeed - a new empty primary will be created, and all future copies will be identical (i.e., empty).

How would you suggest adapting the text?

Note that this has changed in master [where this flag has been replaced with explicit commands](https://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-reroute.html).

**Comment by markwalkom** [comment]
> In this case we wait for the nodes to come back. If someone force allocate an empty primary in that period the same thing will happen indeed - a new empty primary will be created, and all future copies will be identical (i.e., empty).

Yeah, which means that if a node that had the original replica shard came back, we'd delete that as we have an existing one (that is empty).
That's what I mean - by force allocating a primary and recreating it empty, we also do the same for the corresponding replicas.

**Comment by bleskes** [comment]
oh, I see now. I made #16116. Is that what you mean?

**Comment by debadair** [comment]
The topic has been reworked in https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-reroute.html, but it looks like we could make additional clarifications regarding the implications for the replicas.

**Comment by bleskes** [comment]
@debadair I think this covers it:

> . If a node which has a copy of the data rejoins the cluster later on, that data will be deleted! 

Would you agree?

**Comment by bleskes** [comment]
@debadair ping..
