### ISSUE TITLE
Upgrading elastic search from 0.90.x to 1.x

### ISSUE THREAD

**Issue by SummerSun** [elastic/elasticsearch#16112]
Both [breaking changes page](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes.html) and  [Upgrading](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html) sections miss the guide or breaking changes about upgrading from 0.90.x to 1.x. Could somebody please add this related info?
Thank you.

**Comment by jpountz** [comment]
To have this information you need to go to the 1.x docs: https://www.elastic.co/guide/en/elasticsearch/reference/1.7/breaking-changes-1.0.html
