### ISSUE TITLE
EC2 discovery docs point to old repo

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#16111]
[Here](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/modules-discovery-ec2.html) we point to https://github.com/elastic/elasticsearch-cloud-aws, instead of https://www.elastic.co/guide/en/elasticsearch/plugins/current/cloud-aws.html

**Comment by dadoonet** [comment]
+1 same for azure and GCE
