### ISSUE TITLE
Memory Leak using InternalSearchHit.sourceAsMap

### ISSUE THREAD

**Issue by timothysoehnlin** [elastic/elasticsearch#16128]
I'm experiencing an odd behavior in a project I'm currently working on. What I'm seeing is that when I reference an InternalSearchHit.sourceAsMap directly I'm experiencing a memory leak. The code is doing some graph traversal and so there are references to other InternalSearchHit.sourceAsMap documents as well.

I'm currently writing groovy code, and so part of what I'm seeing is:

    def docMap = hit.sourceAsMap() 
    //Add data into hash map
    //Add other InternalSearchHit.sourceAsMap as child of map
   I end up with a memory leak.

If I copy the map using the HashMap constructor:

    def docMap = new HashMap(hit.sourceAsMap())
    //Add data into hash map
    //Add other InternalSearchHit.sourceAsMap as child of map

Then the memory leak goes away.

I took a look at the source for InternalSearchHit and I didn't see anything glaring. At best what I can guess, is that referencing the sourceAsMap object retains a hold on the SearchHit which in turn retains a hold on something else.

**Comment by clintongormley** [comment]
@dakrone any idea what might be happening here?

**Comment by dakrone** [comment]
@timothysoehnlin when you say you are writing groovy code, do you mean you are using the Groovy ES client to interact with Elasticsearch, or are you talking about using the ES scripting API (which is also Groovy)? It *sounds* like the former so please correct me if I'm mistaken.

**Comment by timothysoehnlin** [comment]
I am writing Groovy code that is leveraging the Java Elasticsearch client (nothing do to with scripting inside of an ES query).

I also posted a question on discuss.elastic.co at https://discuss.elastic.co/t/memory-leak-using-internalsearchhit-sourceasmap/39668 which has a bit more information.  As I'm not certain this is an ES issue I thought it might be useful to cross post.

**Comment by jasontedor** [comment]
@timothysoehnlin Do you have a small script that reliably reproduces the issue, preferably a script that works on a bare installation of Elasticsearch?

**Comment by jasontedor** [comment]
I'm closing this since we haven't heard from you; if you do have a script that reproduces the situation, please feel free to attach and reopen.
