### ISSUE TITLE
Node stats api shows both query_cache and request_cache

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#16138]
Is this expected?  Looking at the node stats api output for 2.1.1, it shows both query_cache and request_cache sections.  For a query with request_cache enabled, it increments the request_cache section (expected).  

Is the query_cache section obsolete now that we have renamed [query_cache to request_cache](https://github.com/elastic/elasticsearch/pull/12478)?

```
"query_cache" : {
          "memory_size_in_bytes" : 0,
          "total_count" : 832147,
          "hit_count" : 29390,
          "miss_count" : 802757,
          "cache_size" : 0,
          "cache_count" : 1943,
          "evictions" : 1943
        }

        "request_cache" : {
          "memory_size_in_bytes" : 3395,
          "evictions" : 0,
          "hit_count" : 30,
          "miss_count" : 25
        }
```

**Comment by javanna** [comment]
I believe the query cache is now the previous filter cache, given that filters became queries... will wait for others to confirm though before closing, just to make sure.

**Comment by ppf2** [comment]
Oh makes sense, for this query_cache is sitting between warmer and fielddata, where filter_cache and id_cache used to be located.  Just got confused because of the naming :)  Thanks for the pointer.  Closing.
