### ISSUE TITLE
Aggs with fielddata disabled fails inconsistently

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch#16135]
> Reported by @jimmyjones2 in https://github.com/elastic/kibana/issues/3335#issuecomment-168061914

While indexing a small amount of data to test https://github.com/elastic/kibana/issues/3335 we discovered a strange inconsistency with how elasticsearch validated aggregations. What we observed:

After creating a fresh index (two shards and a `nofielddata` field) any aggregation using the `nofielddata` field can be sent to the index and responses will come back as "successful". As shards start to get documents these shards will start to fail with `"java.lang.IllegalStateException: Field data loading is forbidden on nofielddata"`, but responses will still be formatted as partial successes. Once the final shard has a document requests will start to actually fail (response with a top level "error" property).

This feels like a serious edge-case, but I figured there isn't any harm in reporting it. 

---

Here is a sense script to replicate this:

```sh
DELETE /test?ignore_unavailable=true

POST /test
{
  "settings": {
    "number_of_shards": 2
  },
  "mappings": {
    "test" : {
      "properties": {
        "nofielddata" : {
          "type": "string",
          "fielddata" : { "format" : "disabled" }
        }
      }
    }
  }
}

POST /test/test
{ "noindex" : "foo", "nofielddata" : "foo" }

GET /test/test/_search
{
  "query": {
    "match": {
      "_id": "AVJhGARbdsS1hY8oBX1Z"
    }
  },
  "aggs" : {
    "test" : {
      "terms" : { "field" : "nofielddata" }
    }
  }
}

POST /test/test
{ "noindex" : "bar", "nofielddata" : "bar" }

GET /test/test/_search
{
  "query": {
    "match": {
      "_id": "AVJhGARbdsS1hY8oBX1Z"
    }
  },
  "aggs" : {
    "test" : {
      "terms" : { "field" : "nofielddata" }
    }
  }
}
```

**Comment by jpountz** [comment]
Agreed this is a bug.
