### ISSUE TITLE
Remove option to fsync translog on every operation (index.translog.sync_interval: 0)

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#16152]
We still have the option to sync the translog after every operation by setting `index.translog.sync_interval` to 0. This kills performance and does not seem to add any value. We had a few test failures because of that too on 2.1, like http://build-us-00.elastic.co/job/es_core_21_metal/338/ It should be sufficient to sync the translog on each request.

If we want to remove this option we should also think about how to schedule the translog fsyncing. We probably want a lower limit to the interval and decide what that should be. Then we also need a way to handle settings in already created indices that are lower that the chosen lower limit and how to handle old templates that have that.

**Comment by mikemccand** [comment]
+1

**Comment by jpountz** [comment]
+1

**Comment by brwe** [comment]
> Then we also need a way to handle settings in already created indices that are lower that the chosen lower limit and how to handle old templates that have that.

will be easier on master once #16156 is in
