### ISSUE TITLE
Third level of aggregation sometimes results in missing sub-bucket data

### ISSUE THREAD

**Issue by zdrummond** [elastic/elasticsearch#16164]
When I ask ES for an aggregation, by time, of the sum of a size by ID; I get a result where some events work correctly (end up in bucket with the correct term key), but other data, seemingly randomly, ends up with a blank term key

For example, with this as my aggs

```
 "aggs": {
    "2": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "1m",
        "time_zone": "America/Los_Angeles",
        "min_doc_count": 1,
        "extended_bounds": {
          "min": 1452209723842,
          "max": 1452214986379
        }
      },
      "aggs": {
        "3": {
          "terms": {
            "field": "collection_id.raw",
            "size": 0,
            "order": {
              "1": "desc"
            }
          },
          "aggs": {
            "1": {
              "sum": {
                "field": "size"
              }
            }
          }
        }
      }
    }
  }
```

I get the the following result 
...
```
 "aggregations": {
    "2": {
      "buckets": [
        {
          "3": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
----->      "buckets": []         <---- NOTE: This is where the data is missing
          },
          "key_as_string": "2016-01-07T15:38:00.000-08:00",
          "key": 1452209880000,
          "doc_count": 1
        },
        {
          "3": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "1": {
                  "value": 140355866
                },
                "key": "19488",
                "doc_count": 43
              }
            ]
          },
          "key_as_string": "2016-01-07T16:59:00.000-08:00",
          "key": 1452214740000,
          "doc_count": 43
        },
        {
          "3": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
              {
                "1": {
                  "value": 63037240
                },
                "key": "19488",
                "doc_count": 8
              }
            ]
          },
          "key_as_string": "2016-01-07T17:01:00.000-08:00",
          "key": 1452214860000,
          "doc_count": 8
        }
      ]
    }
  }
```

Note that I get three buckets. Two of them have a value in their "sub" `buckets`, one of them does not. 

If i dig into the Event data, I see nothing odd about them, Here is a snippet for an event that does get into a well defined bucket, 

```
@timestamp	  	January 7th 2016, 16:59:32.000
t@version	  	1
t_id	  	AVIevu0_l2HWhQn5VZHu
t_index	  	logstash-2016.01.08
... 	
collection_id	  	19488
```

and one that does not. Note they have all the same keys, and very similar values. 
```
@timestamp	  	January 7th 2016, 15:38:33.000
t@version	  	1
t_id	  	AVIedMH2l2HWhQn5U0QH
t_index	  	logstash-2016.01.07
...
collection_id	  	19456
```

No idea what is going on, and what makes some data special and others not so much.

**Comment by clintongormley** [comment]
Hi @zdrummond 

You're using extended bounds, so there may well be buckets with no data in them.  Are you absolutely sure that there are docs that should be in that bucket?  Could you post a simple curl recreation showing: the create index/put mapping command, indexing some docs, then running the agg which shows the problem?

Also, what version of ES are you on?

**Comment by zdrummond** [comment]
Thanks @clintongormley for the quick response.

We are on 2.1.0

Unfortunately I can not reliable reproduce the problem, I wish I could.

As for the ' absolutely sure that there are docs that should be in that bucket'.. as sure as I can be. If you note above my aggs are on **timestamp** by **sum(size)** by **collection_id**. The **timestamp** By **size** always works. The **collection_id** is the item that sometimes works and sometimes does not. 

The example above also shows two events I picked from the same time range. Their keys are all the same (but values differ). They both have collection_id. Yet one ends up in a bucket, and the other ends up in a null bucket. 

Note: this is at a high level ELK... I have a chart that has missing data, but i was able to narrow down the issue to the empty bucket issue with aggs in ES.

**Comment by clintongormley** [comment]
Hiya @zdrummond 

Is there any chance that you could provide us (privately) with a copy of the index and the full query that is being sent?

**Comment by zdrummond** [comment]
I think so. How would I get it to you?

**Comment by clintongormley** [comment]
You could put it in dropbox or S3 and send me the link?  clinton at elastic dot co

**Comment by colings86** [comment]
@zdrummond I took a look at the data you provided us. It looks like there are documents that have a `collection_id` field but do not have a `collection_id.raw` field. You can see this if you add a missing aggregation alongside `"3"` looking at the field `collection_id.raw`.

Did you add the multifield for `collection_id.raw` after you have done some indexing into 07-01-2016? Or maybe the template mapping for your logstash indices is not being applied correctly anymore?

**Comment by zdrummond** [comment]
So the good news is, removing `.raw` in fact makes the query return the correct results. 

The bad news is, we have made no any mapping changes, and the issue is persistent, not just on that date. Also, if there is a mapping issue, I would understand it across different sources, but this is coming from the same source (a single server responsible for one job)

That said, we have pretty much just set up ELK and started sending it data. We likely need to clean up the mappings holistically. Maybe if we nail down the mappings across all sources this issue would clear up.

**Comment by colings86** [comment]
Do you use a custom template in your logstash output at all?

**Comment by pmorton** [comment]
@colings86 We allowed logstash to use the default dynamic template. We did not specify a mapping we have logstash setup to tag these messages as the same type so they should share the same schema.

**Comment by clintongormley** [comment]
I wonder if the docs with the missing `.raw` field are all from the first documents in the index, ie whether there was some race condition.  Or alternatively, whether all the documents missing the `.raw` field are on the same shard.

A number of mapping bugs have been cleaned up in 2.2.0 - also wonder if this problem has already been solved.  @zdrummond any chance you can upgrade and see if the issue disappears on new indices?

**Comment by zdrummond** [comment]
Sure. We will plan a roll out of 2.2

**Comment by zdrummond** [comment]
@clintongormley and @colings86 We upgraded to 2.2 and we also did some hand mapping of data types and now the issue is resolved. Thanks!

**Comment by clintongormley** [comment]
thanks @zdrummond
