### ISSUE TITLE
Malformed multi-match query doesn't throw exception

### ISSUE THREAD

**Issue by kaplun** [elastic/elasticsearch#16169]
In our installation, based on Elasticsearch 2.1.1, the number of results depends on the position of the 'size' key in the request.
e.g.

```
curl -XPOST localhost:9200/hep/_search -d '{
    "size": 25,
    "query": {
        "multi_match": {
            "message": {
                "fields": [
                    "title^3",
                    "title.raw^10",
                    "abstract^2",
                    "abstract.raw^4",
                    "author^10",
                    "author.raw^15",
                    "reportnumber^10",
                    "eprint^10",
                    "doi^10"
                ],
                "operator": "or",
                "query": "ellis ",
                "zero_terms_query": "all"
            }
        }
    }
}' -o /tmp/size
```
Vs.
```
curl -XPOST localhost:9200/hep/_search -d '{
    "query": {
        "multi_match": {
            "message": {
                "fields": [
                    "title^3",
                    "title.raw^10",
                    "abstract^2",
                    "abstract.raw^4",
                    "author^10",
                    "author.raw^15",
                    "reportnumber^10",
                    "eprint^10",
                    "doi^10"
                ],
                "operator": "or",
                "query": "ellis ",
                "zero_terms_query": "all"
            }
        }
    },
    "size":25
}' -o /tmp/size2
```
Gives two different results:
```
wc /tmp/size*
0 2293415 24129993 /tmp/size
0 697658 7396394 /tmp/size2
```

Somehow when `size` is last, it is ignored (and default value of 10 is used).

Note that on ES 2.0.0 the `size argument` is respected in both cases.

cc: @jalavik, @jmartinm

**Comment by clintongormley** [comment]
Hi @kaplun 

Your multi_match query is malformed. It shouldn't have the `message` level.  The bug is that we should throw an exception when we see a malformed multi_match query.

**Comment by kaplun** [comment]
Hi @clintongormley,

but would that explain the fact that we still obtain results, and the number of them depends on where `size` is placed?

**Comment by clintongormley** [comment]
@kaplun yes - the parser for multi-match is stepping into the `message` section, but then isn't stepping out of it properly, so it ignores everything after that.

**Comment by cbuescher** [comment]
@clintongormley Just checked, we catch this kind of error on master already. Does it make sense to fix this on the 2.x branch? It's a small fix I think.

**Comment by clintongormley** [comment]
@cbuescher it's been like this since 0.x - i think it is ok to leave it as it is. thanks for checking
