### ISSUE TITLE
Warn user when mapper attachments has to extract an unknown format

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#16189]
With this change: https://github.com/elastic/elasticsearch-mapper-attachments/issues/163 we removed support for many formats.

For example, we don't extract text from XML anymore. See https://discuss.elastic.co/t/search-attachment-content/39559/7

We should warn the user (either in logs) or reject the document is such a case. The end user has no way to know if the parsing has been done correctly or no.

For example:

``` js
DELETE /test
PUT /test
PUT /test/type/_mapping
{
  "type": {
    "properties": {
      "file": {
        "type": "attachment",
        "fields": {
          "content": {
            "type": "string",
            "store": true
          }
        }
      }
    }
  }
}
PUT /test/type/1?refresh=true
{
  "file": "PD94bWwgdmVyc2lvbj0iMS4wIj8+PGNhdGFsb2c+PGJvb2sgaWQ9ImJrMTAxIj48YXV0aG9yPlBhY288L2F1dGhvcj48dGl0bGU+U3ByaW5nLUJvb3Q8L3RpdGxlPjwvYm9vaz48Ym9vayBpZD0iYmsxMDEiPjxhdXRob3I+QXV0aG9yIFRlc3Q8L2F1dGhvcj48dGl0bGU+VGl0bGUgVGVzdDwvdGl0bGU+PC9ib29rPjxib29rIGlkPSJiazEwMSI+PGF1dGhvcj5QYWNvPC9hdXRob3I+PHRpdGxlPkVsYXN0aWMgU2VhcmNoPC90aXRsZT48L2Jvb2s+PGJvb2sgaWQ9ImJrMTAxIj48YXV0aG9yPk5vYm9keTwvYXV0aG9yPjx0aXRsZT5Ob3RoaW5nPC90aXRsZT48L2Jvb2s+"
}
GET /test/type/_search
{
  "fields": [ "file.content" ]
}
```

Gives no content at all. Although the source text is:

``` xml
<?xml version="1.0"?><catalog><book id="bk101"><author>Paco</author><title>Spring-Boot</title></book><book id="bk101"><author>Author Test</author><title>Title Test</title></book><book id="bk101"><author>Paco</author><title>Elastic Search</title></book><book id="bk101"><author>Nobody</author><title>Nothing</title></book>
```

But this:

``` js
DELETE /test
PUT /test
PUT /test/type/_mapping
{
  "type": {
    "properties": {
      "file": {
        "type": "string",
        "store": true
      }
    }
  }
}
PUT /test/type/1?refresh=true
{
  "file": "<?xml version=\"1.0\"?><catalog><book id=\"bk101\"><author>Paco</author><title>Spring-Boot</title></book><book id=\"bk101\"><author>Author Test</author><title>Title Test</title></book><book id=\"bk101\"><author>Paco</author><title>Elastic Search</title></book><book id=\"bk101\"><author>Nobody</author><title>Nothing</title></book>"
}
GET /test/type/_search
{
  "fields": [ "file" ]
}
```

Works as expected.

**Comment by pakkk** [comment]
Many thanks for your help @dadoonet :)

Yes, it is strange, the Base64 string comes from:

MongoDB (GridFS field) -> mongo-connector plugin -> attachment plugin -> ES

For us, it is impossible to have an XML String in MongoDB because it is too large (> 16 MB ***), so we need to store it as Binary (using GridFS) and then, we use ES to do indexed search onto this XML.

Many thanks again!

Regards,
Paco.

*** MongoDB has a maximum document size of 16 MB.

**Comment by dadoonet** [comment]
I think you should create a batch which extracts your docs then parse them with logstash or whatever to have structured data.

**Comment by pakkk** [comment]
Or...before inserting to MongoDB, we parse the data and convert to one of the expected:

MS Office docs: .doc, .docx, .xls, .xlsx, .ppt, .pptx
TXT docs: .rtf, .txt, .csv
oOo docs: .odt, .sxw, .ods, .sxc, .odp, .sxi
PDF docs: .pdf

...And then inserts it as GridFS.

Do you agree with this other way?

Many thanks again!

**Comment by dadoonet** [comment]
But then why would you need to use the mapper plugin? 

Just send the data as a string to elasticsearch as I explained:

```js
PUT /test/type/1?refresh=true
{
  "file": "<?xml version=\"1.0\"?><catalog><book id=\"bk101\"><author>Paco</author><title>Spring-Boot</title></book><book id=\"bk101\"><author>Author Test</author><title>Title Test</title></book><book id=\"bk101\"><author>Paco</author><title>Elastic Search</title></book><book id=\"bk101\"><author>Nobody</author><title>Nothing</title></book>"
}
```

**Comment by pakkk** [comment]
Hello,

Mapper plugin is the only component which can upload elements from MongoDB to ES when the field content is binary. The following project "mongo-connector":

https://github.com/mongodb-labs/mongo-connector/wiki/Usage%20with%20ElasticSearch

It interacts between MongoDB and ElasticSearch when there is any change in the database. So, when the field type is binary (GridFS), "mongo-connector" needs any plugin to convert to "readable" field in ES (this is your attachment plugin).

As I explained previously, our problem is because the size of the XML is greater than 16 MB, so we are forced to convert to GridFS (binary type).

Finally, we thought we could use ES for all the fields because we have a problem with this strange case, so we could take it to do the search for all the fields in ES, and not only for one specific field like that.

Do you agree with my comment?

Many thanks again.

Regards,
Paco.

**Comment by clintongormley** [comment]
Let's add logging for failure cases, and possibly for partial failures (eg truncation) and leave it at that.  When we move this functionality to node ingest we can be more flexible. #16303

**Comment by clintongormley** [comment]
Moving to the ingest attachment plugin, given the mapper attachment plugin is deprecated

**Comment by pozhidaevak** [comment]
I modified this example to work with Ingest plugin
And in the case of invalid XML (as in the example) I receive parsing error, so the user is warned.
```HTTP
PUT /_ingest/pipeline/attachment HTTP/1.1
{
  "description" : "Extract attachment information",
  "processors" : [
    {
      "attachment" : {
        "field" : "data"
    }
    }
  ]
}

PUT /my_index/my_type/my_id?pipeline=attachment
{
  "data": "PD94bWwgdmVyc2lvbj0iMS4wIj8+PGNhdGFsb2c+PGJvb2sgaWQ9ImJrMTAxIj48YXV0aG9yPlBhY288L2F1dGhvcj48dGl0bGU+U3ByaW5nLUJvb3Q8L3RpdGxlPjwvYm9vaz48Ym9vayBpZD0iYmsxMDEiPjxhdXRob3I+QXV0aG9yIFRlc3Q8L2F1dGhvcj48dGl0bGU+VGl0bGUgVGVzdDwvdGl0bGU+PC9ib29rPjxib29rIGlkPSJiazEwMSI+PGF1dGhvcj5QYWNvPC9hdXRob3I+PHRpdGxlPkVsYXN0aWMgU2VhcmNoPC90aXRsZT48L2Jvb2s+PGJvb2sgaWQ9ImJrMTAxIj48YXV0aG9yPk5vYm9keTwvYXV0aG9yPjx0aXRsZT5Ob3RoaW5nPC90aXRsZT48L2Jvb2s+PC9jYXRhbG9nPg=="
}
```


If XML is valid I receive next answer
```json
{
  "_index": "my_index",
  "_type": "my_type",
  "_id": "my_id",
  "_version": 1,
  "result": "created",
  "_shards": {
    "total": 2,
    "successful": 1,
    "failed": 0
  },
  "created": true
}
```

If it is not valid (as in this issue) then the parse error will be received: 
```json
{
  "error": {
    "root_cause": [
      {
        "type": "exception",
        "reason": "java.lang.IllegalArgumentException: ElasticsearchParseException[Error parsing document in field [data]]; nested: TikaException[XML parse error]; nested: SAXParseException[XML document structures must start and end within the same entity.];",
        "header": {
          "processor_type": "attachment"
        }
      }
    ],
    "type": "exception",
    "reason": "java.lang.IllegalArgumentException: ElasticsearchParseException[Error parsing document in field [data]]; nested: TikaException[XML parse error]; nested: SAXParseException[XML document structures must start and end within the same entity.];",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "ElasticsearchParseException[Error parsing document in field [data]]; nested: TikaException[XML parse error]; nested: SAXParseException[XML document structures must start and end within the same entity.];",
      "caused_by": {
        "type": "parse_exception",
        "reason": "Error parsing document in field [data]",
        "caused_by": {
          "type": "tika_exception",
          "reason": "XML parse error",
          "caused_by": {
            "type": "s_a_x_parse_exception",
            "reason": "XML document structures must start and end within the same entity."
          }
        }
      }
    },
    "header": {
      "processor_type": "attachment"
    }
  },
  "status": 500
}
```
The behaviour seems to be correct. So, I'd suggest to close this issue. 

PS
Sorry if misunderstood something. This is my first triage :)

**Comment by dadoonet** [comment]
Agreed.
