### ISSUE TITLE
Increasing `path.data` causes problems

### ISSUE THREAD

**Issue by klahnakoski** [elastic/elasticsearch#16198]
It seems that changing the *.yml file from

    path.data: /data1, /data2, /data3

to

    path.data: /data1, /data2, /data3, /data4

Causes primary shards on the node to never get assigned.  Reverting the *.yml file solves this problem, for most nodes.

I would expect adding to the `path.data` would not cause data loss

[1]  https://discuss.elastic.co/t/how-to-get-back-my-primary-shards/39954

**Comment by rjernst** [comment]
@klahnakoski Which version of elasticsearch?

**Comment by klahnakoski** [comment]
version 1.7.1

**Comment by rjernst** [comment]
This was fixed in 2.0, where we now maintain a shard must exist on a single data path.  Upgrading to 2.0 or after will reorganize the shard data so it satisfies the new behavior.
