### ISSUE TITLE
Where is boolFilter().cache, hasParentFilter() and includeFlags in ES 2.x?

### ISSUE THREAD

**Issue by apanimesh061** [elastic/elasticsearch#16191]
Following is a snippet that is compatible with ES 1.x:
`BoolFilterBuilder boolFilterBuilder = boolFilter().cache(true);`

This is a function present in `FilterBuilders.java`:
`hasParentFilter(String parentType, QueryBuilder query)`

How can I find `includeFlags` that was in Elasticsearch `TermBuilders`?
This is only present in `SignificantTermBuilders`!!

How do I change the syntax to make it compatible with ES 2.x?
I could not find any examples?

**Comment by jpountz** [comment]
> boolFilter().cache(true)

Caching is not configurable anymore, see https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_query_dsl_changes.html#_filter_auto_caching

> This is a function present in FilterBuilders.java: hasParentFilter(String parentType, QueryBuilder query)

Queries and filters have been merged, you should now use QueryBuilders.hasParentQuery. https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_query_dsl_changes.html#_queries_and_filters_merged

> How can I find includeFlags that was in Elasticsearch TermBuilders?

The `terms` aggregation moved to a different regex engine that allows to run such aggregations more efficiently.
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_aggregation_changes.html#_including_excluding_terms
