### ISSUE TITLE
Elasticsearch 2.1 - Multi field issue?

### ISSUE THREAD

**Issue by kevkon3** [elastic/elasticsearch#16190]
Prior to upgrading to ES 2.1, we have been using multi fields to store strings in multiple ways:

https://www.elastic.co/guide/en/elasticsearch/reference/master/_multi_fields.html
https://www.elastic.co/guide/en/elasticsearch/guide/current/multi-fields.html

To access the "raw" version of the field, we simply use "field.raw".

However, in ES 2.1, I get an exception:

```
MapperParsingException[Field name [first_name.raw] cannot contain '.']
```

Is it possible to use multi fields in ES 2.1? Is there some other way I should be trying to call the multi field?

**Comment by kevkon3** [comment]
Looks related to https://github.com/elastic/elasticsearch/issues/14957 which was closed without a resolution. Which led me to https://github.com/elastic/elasticsearch-mapper-attachments/issues/169

**Comment by kevkon3** [comment]
It looks like this should be fixed as of ES 2.2. Is there a release date plan for 2.2?

**Comment by jpountz** [comment]
The 2.2 release should happen soon. I can't promise anything but we are in the process of resolving the last blockers for this release.

**Comment by kri5** [comment]
@kevkon3 is it fixed for you? i am experiencing the same issue.

**Comment by kevkon3** [comment]
@kri5 We haven't tried out elasticsearch 2.2 yet. We tabled the upgrade for now, waiting on 2.2. I imagine we will try it out in about a week?
