### ISSUE TITLE
Translog replay is very slow because indexing buffer is stuck at 500 KB (inactive)

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#16206]
#13918 caused this issue, by having a shard start up in "inactive" state and only activating once it receives indexing operations.

However, translog replay happens at a lower level (directly, by the `InternalEngine`) and bypasses the `active` boolean on the shard, meaning when a translog is replaying, Lucene is only using a tiny (`500 KB`) indexing buffer the whole time, making translog replay take far too long!

**Comment by mikemccand** [comment]
I updated the title: I think this issue also affects replaying ops from a peer's translog.

**Comment by ywelsch** [comment]
yes, the same applies for peer recovery (That was the initial scenario David saw).

**Comment by makeyang** [comment]
any plan or schedule when 2.1.2 will be released?

**Comment by mikemccand** [comment]
Fixed in #16209
