### ISSUE TITLE
Get the type of aggregation result in java api

### ISSUE THREAD

**Issue by hardvain** [elastic/elasticsearch#16205]
Hi, I am querying elastic search using a java client. I am able to get the result but how do know the type of the aggregation result so that I can cast accordingly and get the values?

**Comment by dadoonet** [comment]
Well I guess that when you send a request, you know which kind of aggregation you are asking for?

You could otherwise may be use `instanceof` before casting?

But please can you ask this kind of question on discuss.elastic.co? We keep this place for confirmed issues.

**Comment by hardvain** [comment]
@dadoonet I was not aware of discuss.elastic.co. I wanted a better solution than instanceof. I will ask there.
