### ISSUE TITLE
Allow deletion of document types from an index

### ISSUE THREAD

**Issue by bharvidixit** [elastic/elasticsearch#16207]
This is in the reference of issue https://github.com/elastic/elasticsearch/issues/8877
@clintongormley I agree that there are internal issue of deleting types but it is one of the widely used feature too. Since, if an index contains more than one type and you are not allowing the users to delete a single type from it, users are forced to re-index complete data of other types first in a new index. I think this features should be enabled with putting some constraints rather than completely removing it from elasticsearch. In any data store one should be able to delete a collection/table/type at any time.

**Comment by jpountz** [comment]
The reason why we removed the ability to delete types is that Lucene does not support removing fields. We could potentially add it back if we divorced mappings from types (as mentioned on #15613), but I suspect this would just change your problem from "Allow deletion of types" to "Allow deletion of fields", which we can't solve: it is a natural limitation of the data-structures that Lucene is using to store data.

**Comment by clintongormley** [comment]
Instead we're adding a reindex API which will make it easier for you to do the right thing.  See https://github.com/elastic/elasticsearch/issues/15201

**Comment by jasontedor** [comment]
> In any data store one should be able to delete a collection/table/type at any time.

The analogy to database tables, while one that has been made in the past, breaks down. See [Index vs. Type](https://www.elastic.co/blog/index-vs-type).
