### ISSUE TITLE
Expensive include regex is not captured by the circuit breaker logic in ES 1.7.1

### ISSUE THREAD

**Issue by Asimov4** [elastic/elasticsearch#16201]
If we run this type of query with an expensive regex (think 10 000 eventIds), it takes 10 minutes to process and is not caught by the circuit breaker.

`"aggs":{"terms":{"terms":{"field":"eventId","include":"123|456|789|...|987|654|321"}}}`

**Comment by jpountz** [comment]
I am confused by your bug report: the circuit breaker provides (limited) protection against out-of-memory errors, while the problem your are noticing here is a long processing time, which should rather be solved by setting a timeout?

**Comment by Asimov4** [comment]
You are right. That said, a circuit breaker as a concept does not necessarily imply that memory should be the only trigger. Is there an opportunity to also trip the circuit breaker on CPU?
I did a bit more research and found this: https://github.com/elastic/elasticsearch/issues/9156

**Comment by jpountz** [comment]
This is related indeed and that would probably apply to this issue as well: I suspect that this will be less of an issue with elasticsearch 2.x.
