### ISSUE TITLE
Top level inner hits override query level inner hits

### ISSUE THREAD

**Issue by zygfryd** [elastic/elasticsearch#16218]
In the presence of top level inner hits query level inner hits are missing from the result, even if there are no name collisions. This necessitates rewriting query level inner hits as top level inner hits with a duplicate of the main query, which I assume is suboptimal.

ES 2.1.1.

**Comment by martijnvg** [comment]
@zygfryd Thanks for reporting this. This is indeed suboptimal and not expected behaviour.

Simple reproduction:

```
PUT index
{
  "mappings": {
    "parent" : {
    },
    "child" : {
      "_parent": {
        "type": "parent"
      }
    }
  }
}

PUT /index/parent/1
{ 
}

PUT /index/child/1?parent=1
{ 
}

GET /index/_search
{
  "query": {
    "has_child": {
      "type": "child",
      "query": {
        "match_all": {}
      },
      "inner_hits" : {}
    }
  },
  "inner_hits" : {
    "my-inner-hits" : {
      "type" : {
        "child" : {
          
        }
      }
    }
  }
}
```

Two inner hits are expected here, but instead only the top level inner hit is returned.
