### ISSUE TITLE
Analysis API doesn't respect node level default analyzer setting

### ISSUE THREAD

**Issue by medcl** [elastic/elasticsearch#16219]
Hi,
I tried to set the default analyzer at node level by config the `elasticsearch.yml`, but without success, here is the config i used to test, under elasticsearch version 2.0 and 2.1.*
```
index :
  analysis :
    analyzer :
      default :
        tokenizer : keyword
````
and 
```
index.analysis.analyzer.default.type: keyword
```

**Comment by clintongormley** [comment]
Hi @medcl 

I tested this in 2.1.0 and 2.2.0 and it works as expected.  Try this:

    PUT t/t/1
    {
      "name": "Foo Bar"
    }
    
    GET _search
    {
      "fielddata_fields": ["name"]
    }


It also works for the `_all` field.

**Comment by medcl** [comment]
@clintongormley  here is the method what i tried 
```
curl http://localhost:9200/_analyze\?text\=medcl+test1234
{"tokens":[{"token":"medcl","start_offset":0,"end_offset":5,"type":"<ALPHANUM>","position":0},{"token":"test1234","start_offset":6,"end_offset":14,"type":"<ALPHANUM>","position":1}]}
```

**Comment by clintongormley** [comment]
@medcl ah ok - that's a different issue, it's a bug in the analyze API and has never worked..  I'll change the title and reopen

**Comment by johtani** [comment]
Note: The `standard` is specified the request without index.
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/admin/indices/analyze/TransportAnalyzeAction.java#L234

**Comment by clintongormley** [comment]
@johtani perhaps it should look for that setting first, before defaulting to standard.

**Comment by johtani** [comment]
@clintongormley Agreed

**Comment by johtani** [comment]
Noted: In 5.0, we can't set node level default analyzer. See: https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_settings_changes.html#_index_level_settings

**Comment by clintongormley** [comment]
agreed - closing
