### ISSUE TITLE
issue starting elasticsearch on windows 

### ISSUE THREAD

**Issue by Ij888** [elastic/elasticsearch#16213]
I am running Windows10 and have Java 1.8.0.71 installed. On clicking the `elasticsearch.bat` file in the freshly extracted elasticsearch 2.1.1 folder, the window flashes for the briefest instant and disappears. Any thoughts would be appreciated.

**Comment by dadoonet** [comment]
Run it from the command Line and it Will tell what's wrong.

Also please ask questions on discuss.elastic.co


We can help there...
