### ISSUE TITLE
Elasticsearch get stuck while indexing a few record

### ISSUE THREAD

**Issue by dam0vm3nt** [elastic/elasticsearch#16224]
I have an embedded instance of an `elasticsearch` node (no tcp) used to provide a fast indexed search engine on a big and complex relational database.

The index is kept aligned with the db by a background thread (this is a very common usage pattern for ES).

The problem is that after a while we start seeing exception like the following, and we have to stop and restart the server to make it work again:

    Caused by: EsRejectedExecutionException[rejected execution of org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1@1133ea1 on EsThreadPoolExecutor[index, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@1ff3ea[Running, pool size = 2, active threads = 2, queued tasks = 200, completed tasks = 5]]]
    at org.elasticsearch.common.util.concurrent.EsAbortPolicy.rejectedExecution(EsAbortPolicy.java:50)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
    at org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor.execute(EsThreadPoolExecutor.java:85)
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.routeRequestOrPerformLocally(TransportReplicationAction.java:444)
    at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:386)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    at org.elasticsearch.action.support.replication.TransportReplicationAction.doExecute(TransportReplicationAction.java:120)
    at org.elasticsearch.action.index.TransportIndexAction.innerExecute(TransportIndexAction.java:135)
    at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:119)
    at org.elasticsearch.action.index.TransportIndexAction.doExecute(TransportIndexAction.java:66)
    at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70)
    at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:58)

No other exception are visibile in the logs except this one. Seams like something il locked inside ES and when it reaches the fatal number of 200 stuck "things" it will stop working.

Elastic search is version : 2.1.1

**Comment by jasontedor** [comment]
This is the index thread pool inside Elasticsearch rejecting requests because its task queue is full. The `EsRejectedExecutionException` is a way of communicating to your client thread that it needs to back off. It sounds like your client thread is not properly handling these exceptions.

1. You need to catch and handle requests that fail from an `EsRejectedExecutionException`; this means that you need to back off, and retry your request later (this is true whether you're asynchronously or synchronously firing off indexing requests).
2. Investigate increasing the size of the index queue, but only within reason. Increasing queue size is not a panacea for constantly-full queues.
3. Are you sure that you have sufficient hardware here? Are your disks and CPU fast enough? Are the database and the embedded Elasticsearch on the same box competing for resources?

> Seams like something il locked inside ES and when it reaches the fatal number of 200 stuck "things" it will stop working.

I'm interpreting this statement as you saying that Elasticsearch locks up (i.e., no longer responding to requests) when this happens. This shouldn't be the case, but if you do in fact have evidence that Elasticsearch is locking up here (thread dumps would be great!), that would be helpful.

**Comment by dam0vm3nt** [comment]
Hello, thank you for the response.

We have recreated the index with `number_of_replicas=1` and it seams to work on a test machine. Can it be that using the default value of 2 replicas with 1 single node can cause timeout happening on the indexing phase making the queue grow until it explodes ?

Other than that none of the points you enilisted seams to apply :

1. As I have said no exception are thrown while indexing until that one indicating the queue is full. Is there something else we can do to check if something fails ?

2.  I agree that resizing queue is not the answer because eventually it will fill up no matter the size

3. We tryied even indexing 1 record every 5 secs and it will explode. The hardware is not a problem (4 - core i7 + 8 gb ram)

**Comment by dam0vm3nt** [comment]
As for point 1: after reading twice I understood what you mean, sorry. We can back off but this problem seams to happen way to often and with very little loads so there should be something else.

Can it be the `number_of_repilcas` value as written in my previous answer ?

**Comment by jasontedor** [comment]
> We have recreated the index with number_of_replicas=1 and it seams to work on a test machine. 

If you have a single embedded node, you should have `number_of_replicas` set to zero. Positive replicas are not helpful when you only have a single node because there is no home for the replica.

> Can it be that using the default value of 2 replicas

The default is one replica. To be clear, the default is one replica meaning that every shard will by default have a primary copy and a replica copy. However, in the case of a single embedded node, there is no home for the replica copy so just set it to zero (if you need backups of your indices, take a snapshot using the snapshot API).

> with 1 single node can cause timeout happening on the indexing phase making the queue grow until it explodes ?

No, the replica will just be unassigned and have no impact on the indexing.

> Is there something else we can do to check if something fails ?

You have to check the index response (if you're doing synchronous calls) or handle the failure callback (if you're doing asynchronous calls).

> We tryied even indexing 1 record every 5 secs and it will explode. 

Can you provide more details? How are you doing the indexing? What is the size of the request? 

> The hardware is not a problem (4 - core i7 + 8 gb ram)

What is the disk situation, and is it sharing the same hardware with the database? How much heap have you allocated to the Elasticsearch process?

**Comment by jasontedor** [comment]
> Can it be the number_of_repilcas value as written in my previous answer ?

Nope. There is something else going on.

**Comment by dam0vm3nt** [comment]
ouch! I was so hopefull! 

Ok then we will set `number_of_replicas` to 0 according to your suggestion (obviously you're right about the default value beiing 1).
At the moment we will implement a back-off policy and see what's happening.

Disks are a bit slow and shared with the db so that may be the cause. 

For now thanks for your help.

**Comment by dam0vm3nt** [comment]
I forgot to mention one important thing : at the moment we have a single thread that will index the data.

It is indexing syncronously one record at a time.

In this situation I expect the indexer task queue should be always almost empty. 

Is this assumption of mine wrong ?

**Comment by jasontedor** [comment]
> Disks are a bit slow and shared with the db so that may be the cause.

That definitely won't help performance, but given your later statements about indexing synchronously one record at at time, it's not the cause of the issue.

> It is indexing syncronously one record at a time.

> In this situation I expect the indexer task queue should be always almost empty.

> Is this assumption of mine wrong ?

Given your stated setup, this assumption is not wrong. Can you share more detail about how exactly you're executing the indexing requests synchronously?

**Comment by dam0vm3nt** [comment]
This is what I am doing in the indexer:

     client.prepareIndex("elys", "history", String.valueOf(record.getId()))
                .setSource(objectMapper.writeValueAsBytes(record)).get(new TimeValue(5,TimeUnit.SECONDS));

The node is started like this:

    node = NodeBuilder.nodeBuilder()
        .settings(settings)
        .clusterName(ELYS_ES_CLUSTER)
        .data(true).local(true).node();

        node.start();

        client = node.client();

**Comment by jasontedor** [comment]
At a very quick glance, that looks correct, but can you also share the `settings` that you're passing in?

**Comment by dam0vm3nt** [comment]
Of course here they are:
   // Start indexer
        Settings.Builder settings = Settings.settingsBuilder();

        settings.put("node.name", ELYS_ES_CLUSTER);

        settings.put("path.data", configuratorBridge.getProperty("es.data.dir"));
        settings.put("path.home", configuratorBridge.getProperty("es.home.dir"));
        settings.put("logger._root","DEBUG");
        settings.put("threadpool.index.queue_size",INDEX_QUEUE_SIZE);

        settings.put("http.enabled", false);
        // Init log if missing
        try {
            java.io.File h = new File(configuratorBridge.getProperty("es.home.dir"));
            java.io.File f = new File(h, "config");
            f = new File(f, "logging.yml");
            if (!f.exists()) {
                f.getParentFile().mkdirs();
                FileWriter fw = new FileWriter(f);
                fw.write("file:\n" +
                        "    type: org.apache.log4j.rolling.RollingFileAppender\n" +
                        "    file: ${path.home}/logs/es.log\n" +
                        "    rollingPolicy: org.apache.log4j.rolling.TimeBasedRollingPolicy\n" +
                        "    rollingPolicy.FileNamePattern: ${path.home}/logs/es.log.%d{yyyy-MM-dd}.gz\n" +
                        "    layout:\n" +
                        "      type: pattern\n" +
                        "      conversionPattern: \"%d{ISO8601}[%-5p][%-25c] %m%n\"");
                fw.close();

                f = new File(h, "logs");
                f.mkdirs();
            }


            LogConfigurator.configure(settings.build(), true);
        } catch (Exception e) {
            e.printStackTrace();
        }

Recentlly we have added the `INDEX_QUEUE_SIZE` that's now set to `2000`. This is to stabilize production but it's only a temporary solution.

Another info I have to add is that we had to "osgify" ES to avoid class collition (our framework was already using an older version of lucene). For the same reason we had to `shade` the `guava` library. Having said that, no class loading problem or exception are ever thrown.

**Comment by jasontedor** [comment]
> I have a jstack dump of a "locked" jvm if this can help.

Can you share this?

**Comment by dam0vm3nt** [comment]
In a few day we are going to reproduce the event and see if in the
meanwhile something has changed (we fixed some issues and changed some
parameters). I'll let you know how it has gone.
Thanks,

Il giorno gio 25 feb 2016 alle ore 15:25 Jason Tedor <
notifications@github.com> ha scritto:
