### ISSUE TITLE
How to filter duplicate field?

### ISSUE THREAD

**Issue by robin820224** [elastic/elasticsearch#16221]
I have created a "test1" index, and then inserted two document to index. This two documents have the same "name" value:

{
  "_index": "test1",
  "_type": "type",
  "_id": "2",
  "_score": 1,
  "_source": {
    "name": "相声广播"
  }
}

{
  "_index": "test1",
  "_type": "type",
  "_id": "1",
  "_score": 1,
  "_source": {
    "name": "相声广播"
  }
}

If I want to query the distinct result for the "name" field, how should I to filter duplicate document using query statement?

**Comment by dadoonet** [comment]
Please use discuss.elastic.co for questions.

You can't really de duplicate data when searching. I'd try if possible to do that at index time.

But let's follow up on discuss...

Not an issue. Closing.
