### ISSUE TITLE
java mget is much slower than http mget when in high concurrency environment

### ISSUE THREAD

**Issue by henghanan** [elastic/elasticsearch#16233]
Hi, when i test the performance of mget method with HP Loadrunning, i found that java's mget method is much slower than http's mget method, java's mget method is almost 5 times slower than http's mget method.

here is my test method.
```java
MultiGetResponse multiGetResponse = client.prepareMultiGet()
                .add(index, type, ids)
                .execute()
                .actionGet();
```

curl -XGET 'http://127.0.0.1:9200/test/test/_mget' -d '{
    "ids" : ["1", "2", "3", ...]
}'

But the weird thing is that i send a single request respectively, their average time spent is the same.

**Comment by clintongormley** [comment]
Hi @henghanan 

They use the same mechanism internally so I can only assume that you're doing something incorrect (and we'd need more information to figure out what that is).  The right place to ask questions like this is in the forum: http://discuss.elastic.co/

If, after discussing there, you find a bug then please reopen.
