### ISSUE TITLE
Deprecate node.mode in favour of node.local

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#16234]
The `node.mode` setting supports two values: `local` or `network`and was introduced by #3713. The `node.local` setting is a boolean. We read both as part of `DiscoveryNode#localNode` static method which gives the precedence to `node.local`, then reads `node.mode`, if none of the two is set it returns `false`.

I am not sure why we have `node.mode` anymore, I think these two settings have the same effect and result in controlling which transport impl (local or netty) and which discovery impl (local or zen) is used. Unless I am overlooking something, we can deprecate one of the two. The boolean one seems the simpler the keep, what do people think about this?

**Comment by bleskes** [comment]
+1 on just have node.local . I think long term we want this to be a test only setting anyway. Maybe we can get rid of it and just set both network and discovery type from the test framework as we want them…

**Comment by s1monw** [comment]
+1 @javanna
