### ISSUE TITLE
Align the regex implementation in SignificantTermsBuilder and TermsBuilder

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#16231]
In TermsBuilder we switched from `java.util.Regex` to `org.apache.lucene.util.automaton.RegExp` but `SignificantTermsBuilder` still uses `java.util.Regex`. We should align both implementations and use `org.apache.lucene.util.automaton.RegExp` consistently.

**Comment by colings86** [comment]
This should be done once the agg refactoring has been merged. Marking as stalled for now until that is complete

**Comment by ideadapt** [comment]
@colings86 & @danielmitterdorfer The aggregation refactoring has changed namings and structure  of code. [SignificantTermsAggregationBuilder](https://github.com/elastic/elasticsearch/blob/3a5a54e83ede8fb7e89e7e985b03a1cc9469b574/core/src/test/java/org/elasticsearch/search/aggregations/bucket/SignificantTermsTests.java) uses `org.apache.lucene.util.automaton.RegExp`. I could not find any Terms related class that uses `java.util.Regex`. 
Has this issue become obsolete?

**Comment by polyfractal** [comment]
It does indeed look like this issue is obsolete, I can't find any `java.util.Regex` either.  Closing! :)
