### ISSUE TITLE
Documents are not returned after disk full

### ISSUE THREAD

**Issue by rathir** [elastic/elasticsearch#16249]
Hi,
      I am seeing this issue where query doesn't return any documents after disk full and cluster state is red. This is a single node cluster. Is this expected when disk full condition is reached ?

Here is the relevant info. 

[admin@CentOS7 log]$ curl '172.31.193.192:9200/_cat/indices?v'
health status index  pri rep docs.count docs.deleted store.size pri.store.size
red    open   monkey   5   1

[admin@CentOS7 log]$ curl '172.31.193.192:9200/_cat/shards?v'
index  shard prirep state        docs store ip             node
monkey 3     p      INITIALIZING            172.31.193.192 Mad Jack
monkey 3     r      UNASSIGNED
monkey 4     p      UNASSIGNED
monkey 4     r      UNASSIGNED
monkey 1     p      UNASSIGNED
monkey 1     r      UNASSIGNED
monkey 2     p      UNASSIGNED
monkey 2     r      UNASSIGNED
monkey 0     p      UNASSIGNED
monkey 0     r      UNASSIGNED

 Please find attached  ES log file as well.

I see this in the log file.

[2016-01-25 19:54:56,312][INFO ][cluster.routing.allocation.decider] [Mad Jack] rerouting shards: [high disk watermark exceeded on one or more nodes]
[2016-01-25 19:55:01,507][ERROR][index.engine             ] [Mad Jack] [monkey][0] failed to merge
java.io.IOException: No space left on device

[elasticsearch.log-2016-01-25.txt](https://github.com/elastic/elasticsearch/files/105755/elasticsearch.log-2016-01-25.txt)

[admin@CentOS7 log]$ curl '172.31.193.192:9200'
{
  "name" : "Mad Jack",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.1.1",
    "build_hash" : "40e2c53a6b6c2972b3d13846e450e66f4375bd71",
    "build_timestamp" : "2015-12-15T13:05:55Z",
    "build_snapshot" : false,
    "lucene_version" : "5.3.1"
  },
  "tagline" : "You Know, for Search"
}

Let me know if any other info is needed.

Thanks,
Ravindra

**Comment by clintongormley** [comment]
Hi @rathir 

If your disk is full and you try to write more documents, writing will fail, which will fail the shards, so yes, you will get no search results until you find more disk space and your shards can recover.
