### ISSUE TITLE
min_score doesn't work with query string?

### ISSUE THREAD

**Issue by SkateFreak** [elastic/elasticsearch#16262]
{
        min_score: 0.2,
        query_string: {
            query: {
                ...
            }
        }
    }

doesn't seem to work...
am i missing something?

thanks!

**Comment by clintongormley** [comment]
Hi @SkateFreak 

I tried it and it works just fine.  Please ask questions like these in the forums: https://discuss.elastic.co/ and i suggest that you provide more information when you do.

thanks
