### ISSUE TITLE
Test Failure: org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests.testUpdateSettingsCanNotChangeThreadPoolType

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#16277]
Test Failure:
org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests.testUpdateSettingsCanNotChangeThreadPoolType

Repro:
gradle :core:test -Dtests.seed=F06F5C97649014C1 -Dtests.class=org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests -Dtests.method="testUpdateSettingsCanNotChangeThreadPoolType" -Des.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=552m -Dtests.jvm.argline="-server -XX:+UseSerialGC -XX:-UseCompressedOops" -Dtests.locale=sr-BA -Dtests.timezone=Europe/Chisinau

Build:
http://build-us-00.elastic.co/job/es_core_master_small/6738/

Description:
http://build-us-00.elastic.co/job/es_core_master_small/6738/testReport/junit/org.elasticsearch.threadpool/UpdateThreadPoolSettingsTests/testUpdateSettingsCanNotChangeThreadPoolType/

**Comment by nik9000** [comment]
@s1monw says he pushed a fix for this. Probably https://github.com/elastic/elasticsearch/commit/7ef762c8f0758d08fb136a4fbecf873f0fdb95ec
