### ISSUE TITLE
can not set default analyzer except those which are builtin

### ISSUE THREAD

**Issue by denghongcai** [elastic/elasticsearch#16282]
log
```
IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [ik] for [default]]
```
I'm using Elasticsearch 2.1.1,

config in
`elasticsearch.yml`
is only have
```
index.analysis.analyzer.default.type: ik
```

```
root@xxx:/opt/elasticsearch-jdbc-2.1.1.2/bin# /usr/share/elasticsearch/bin/plugin list
Installed plugins in /usr/share/elasticsearch/plugins:
    - elasticsearch-analysis-mmseg-1.7.0
    - elasticsearch-analysis-pinyin-1.5.2
    - elasticsearch-analysis-stconvert-1.6.1
    - elasticsearch-analysis-ik-1.7.0
```

if i set config using cluster setting api
```
GET /xxx/_analyze
{
    "text": "你好",
    "analyzer": "ik"
}
```

it works fine.

**Comment by clintongormley** [comment]
It looks to me like the analyzer is called either `ik_smart` or `ik_max_word` (see https://github.com/medcl/elasticsearch-analysis-ik)

Either way, i tried this with the smartcn analysis plugin and it works as expected.  The `ik` plugin is not maintained by elasticsearch so if my suggestion doesn't work, you should open an issue there.

**Comment by medcl** [comment]
actually you have already set the default analyzer to `ik`, but the _analyze api is broken,see the issue here: https://github.com/elastic/elasticsearch/issues/16219
