### ISSUE TITLE
omit_norms: true PUT _mapping exception

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch#16298]
When using the PUT \_mapping api in 1.x builds (tested with 1.5.2, 1.6.0, 1.6.1, 1.6.2, 1.7.4.  Does not repo with 2.1.1) and

```{
"_default_": {
  "_all": {
     "enabled": true,
     "omit_norms": true
  }
 }
}```

is set (logstash template: https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/e4590a2315b23fb9e94638534b62e49a779532d1); adding a mapping for a new field of an existing type will throw the following error:

```{
   "error": "MergeMappingException[Merge failed with failures {[mapper [_all] cannot enable norms (`norms.enabled`)]}]",
   "status": 400
}```

Steps to reproduce:
```
PUT logstash-example

PUT logstash-example/_mapping/_default_
{
"_default_": {
  "_all": {
     "enabled": true,
     "omit_norms": true
  }
 }
}

PUT logstash-example/_mapping/syslog
{
   "syslog": {
  }
}

PUT logstash-example/_mapping/syslog
{
  "properties": {
    "tags": {
      "type": "string"
    }
  }
}
```

**Comment by clintongormley** [comment]
Hi @jpcarey 

Yes, this is a bug which has been fixed by the great mapping rewrite (#8870) in 2.x.  These changes are way too big to backport (and break bwc).  As a workaround, specify the `_all` mapping again:

    PUT logstash-example/_mapping/syslog
    {
      "_all": {
        "enabled": true,
        "omit_norms": true
      },
      "properties": {
        "tags": {
          "type": "string"
        }
      }
    }
