### ISSUE TITLE
index if not deleted / non-partial updates / index if doc exists / consistency

### ISSUE THREAD

**Issue by mrkamel** [elastic/elasticsearch#16296]
Hi,

a) for the sake of consistency, it would be super awesome if ES could permanently store a list of IDs of deleted docs, such that one could ensure to not re-index already deleted docs. E.g. PUT /.../_create?if_not_deleted=true. It seems the only current possible way to achieve consistency regarding deleted records is to not really delete these docs but instead mark them as deleted and exclude them from search queries,

b) Similarly, i don't find a way to do non-partial updates, i.e. use the update api without merging the already existing attributes into the provided ones. E.g.

```
PUT /my-index/my-type/1/_update
{
  "full_doc": {
    ...
  }
}
```

I could of course use the index api, but for the sake of consistency i want to be sure to not re-index already deleted documents. Something like

```
PUT /my-index/my-type/1?if_not_exists=true
{
  ...
}
```

Thanks

**Comment by mrkamel** [comment]
the last one should of course be

```
PUT /my-index/my-type/1?if_exists=true
{
  ...
}
```

**Comment by clintongormley** [comment]
Hi @mrkamel 

If you want this behaviour, then you need to do exactly what you're doing: use "soft" deletes by adding a flag to the document instead of deleting it.  The semantics we have are way too baked in to support this change.
