### ISSUE TITLE
inner_hits returns "ip" type values in strange (byte?) format

### ISSUE THREAD

**Issue by abulhol** [elastic/elasticsearch#16290]
I am running nested queries like this:
```
body={
    "query" : {
        "nested" : {
            "path" : "network.http.packet",
            "query" : {
                "match" : {"network.http.packet.dstip" : "184.28.188.99"}
            },
            "inner_hits" : {"_source":False,"fielddata_fields":["network.http.packet.dstip"]} 
        }
    }
}
```

The query returns the fielddata_fields in some strange (byte?) representation instead of ip, like this:
`{u'network.http.packet.dstip': [386205091, 386205091, 386205091, 386205091, 386206491, 386206491,....
` 

I have set include_in_root to true for network.http.packet, and if I query a document with 
`_source="network.http.packet.dstip"`
the IPs are returned as expected (Dot-decimal notation).

Looks like a bug to me.

**Comment by jpountz** [comment]
This is  caused by the use of `fielddata_fields`, not inner hits, which return the internal representation of the data in fielddata. And ip addresses happen to be backed by 32-bits numerics.

**Comment by abulhol** [comment]
This is good to know - I suggest to also explain it in detail in the reference guide. 
The other question is: how can I return the dot-decimal notation for inner_hits instead?
I can see that I could use Source filtering probably like this:
` "inner_hits" : {"_source":["network.http.packet.dstip"]} `
and to NOT return the _source for the containing document, I have to set 
`"_source":["network.http.packet.*"]`
or so for the whole query. Will give that a try tomorrow. 
In any case, the reference guide could be improved here.

**Comment by abulhol** [comment]
No solution found so far, have posted this in the ES forum: 
https://discuss.elastic.co/t/return-ip-field-from-inner-hit-in-dot-decimal-format/40452
