### ISSUE TITLE
Lucene version check prevents people updating Lucene to get bugfixes

### ISSUE THREAD

**Issue by trejkaz** [elastic/elasticsearch#16301]
Lucene 5.3.2 came out, so we updated it to get the fix.

Elasticsearch then stopped working, because there is this check in `Version.java`:

            assert CURRENT.luceneVersion.equals(Lucene.VERSION) : "Version must be upgraded to [" + Lucene.VERSION + "] is still set to [" + CURRENT.luceneVersion + "]";

This basically prevents us updating Lucene to get any bugfixes at all unless we turn off assertions to work around it, which is probably the better option, but still irritates me somehow.

If Elasticsearch does depend on 5.3.1 specifically then it should probably be using Version.LUCENE_5_3_1 and not checking Version.LATEST and then complaining if it happens to be newer.

**Comment by bleskes** [comment]
> If Elasticsearch does depend on 5.3.1 specifically then it should probably be using Version.LUCENE_5_3_1 and not checking Version.LATEST and then complaining if it happens to be newer.

This is exactly how it's set up. The goal of this assertion to make sure we run on the lucene version we expect to be there, so we will not forget to update the pinned lucene version.

I'm not sure what exactly you are trying to do. It seems you are replacing the lucene jars in the elasticsearch lib folder? If so this is not supported as many times it requires code changes as well. I'm going to close this assuming, I understood it correctly. If not feel free to reopen.

**Comment by s1monw** [comment]
> I'm not sure what exactly you are trying to do. It seems you are replacing the lucene jars in the elasticsearch lib folder? If so this is not supported as many times it requires code changes as well. I'm going to close this assuming, I understood it correctly. If not feel free to reopen.

I think we should make this even a hard check instead of an assertion maybe in Bootstrap.java?

**Comment by bleskes** [comment]
+1

**Comment by s1monw** [comment]
there is a PR for this here #16305

**Comment by trejkaz** [comment]
We use Lucene in the same application and we are now trying to add in Elasticsearch.

If Elasticsearch wants to use a specific version, Lucene's Version class does allow it to do that. Checking that LATEST is equal to a specific version just hinders people updating Lucene. I do understand that some updates to Lucene require code changes, but this was a bugfix release and we wanted the fix. You are now depriving us from getting that fix.

I wouldn't mind so much if Elasticsearch were to release a corresponding bugfix update which uses the same updated Lucene, but there was no such update.

If your goal is to inconvenience people who want to use your library, you might also consider aiming for the maximum score and locking down the version of Java you run against, so that people are forced to run an out of date JRE as well.
