### ISSUE TITLE
Deprecate and remove the multicast plugin

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#16310]
Multicast has some serious issues (eg see https://github.com/elastic/elasticsearch/issues/12993 and https://github.com/elastic/elasticsearch/issues/12914) which are JDK and OS dependent, and essentially unfixable.  In https://github.com/elastic/elasticsearch/pull/12999 we changed to default to using unicast for discovery and in https://github.com/elastic/elasticsearch/issues/13019 we moved multicast to a plugin to give users a chance to migrate their code.

We are not seeing many downloads of the multicast plugin which indicates that almost everybody has switched to unicast.  I think we should deprecate this plugin in 2.3 and remove it in 3.0.

**Comment by rmuir** [comment]
+1

**Comment by djschny** [comment]
Since the 2.0 adoption rate is low still, I don't believe a small of amount of downloads of the multicast plugin can be used as good indication that "almost everybody has switched to unicast". I proceed very very cautiously here.

**Comment by dadoonet** [comment]
For the record, I met someone today at BigDataParis who is deploying elasticsearch in Google cloud, within a private network, and they are using multicast and are happy with it (ES < 2.0).
I told about the multicast plugin and that it will be removed in 5.0. Does not seem to be a big deal. Just complicates a bit the deployment.

**Comment by macdjord** [comment]
Uh, this is a problem for us. We use Dockerized elasticsearch, and the way our deployments are set up makes giving our nodes fixed IP addresses non-trivial. We depend on multicast discovery to allow our nodes to connect under those conditions.

We will probably not be upgrading to 5.0 until this is fixed.

(We were aware of the deprecation, but were under the impression that it meant the multicast-discovery _core module_ was being deprecated in favour of the multicast-discovery _plugin_ - not that muticast support was being dropped entirely.)

**Comment by nik9000** [comment]
> We will probably not be upgrading to 5.0 until this is fixed.

I don't know anyone who plans on bringing it back.

**Comment by jasontedor** [comment]
> I don't know anyone who plans on bringing it back.

It's not coming back, but there are solutions to this problem. I suggest opening a topic on the [Elastic Discourse forum](https://discuss.elastic.co).
