### ISSUE TITLE
which operation has more priority in query_string?  AND or OR 

### ISSUE THREAD

**Issue by gm06041** [elastic/elasticsearch#16328]
i tested query_stirng like script below attached.(test ES version: 1.7.2)
but, i don't know why this result happened.

(1) age:13 OR type:1 AND age:35 OR type:1       <strong>result=>  {"name":"Paul", "age":35, "type":1} </strong>
(2) ((age:13 OR type:1) AND age:35) OR type:1   <strong>result=>  {"name":"Paul", "age":35, "type":1},{"name":"Paul", "age":13, "type":1}</strong>
(3) age:13 OR (type:1 AND age:35) OR type:1     <strong>result=>  {"name":"Paul", "age":35, "type":1},{"name":"Paul", "age":13, "type":1}</strong>
(4) (age:13 OR type:1) AND (age:35 OR type:1)     <strong>result=>  {"name":"Paul", "age":35, "type":1},{"name":"Paul", "age":13, "type":1}</strong>

'(1)' query's result is different from '(2)', '(3)', '(4)'.
if operation order is left to right, '(1)' query's result needes to be equal to be '(2)'.
and if AND opeation has more priority,  '(1)' query's result needes to be equal to be '(3)'.
but nothing is matched. any reason?

<pre>[root@hadoop1 bin]# curl -XPUT http://127.0.0.1:9200/test
{"acknowledged":true}
[root@hadoop1 bin]# curl -XPUT http://127.0.0.1:9200/test/mytype/1 -d '{"name":"Paul", "age":35, "type":1}'
{"_index":"test","_type":"mytype","_id":"1","_version":1,"created":true}
[root@hadoop1 bin]# curl -XPUT http://127.0.0.1:9200/test/mytype/2 -d '{"name":"Paul", "age":13, "type":1}'
{"_index":"test","_type":"mytype","_id":"2","_version":1,"created":true}
[root@hadoop1 bin]# curl -XPUT http://127.0.0.1:9200/test/mytype/3 -d '{"name":"Paul", "age":35, "type":2}'
{"_index":"test","_type":"mytype","_id":"3","_version":1,"created":true}
[root@hadoop1 bin]# curl -XPOST localhost:9200/test/_search?pretty=true -d '{
  "query": {
    "query_string": {
      "query": "age:13 OR type:1 AND age:35 OR type:1"
    }
  }
}'
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.125,
    "hits" : [ {
      "_index" : "test",
      "_type" : "mytype",
      "_id" : "1",
      "_score" : 1.125,
      "_source":{"name":"Paul", "age":35, "type":1}
    } ]
  }
}
[root@hadoop1 bin]# curl -XPOST localhost:9200/test/_search?pretty=true -d '{
>   "query": {
>     "query_string": {
>       "query": "((age:13 OR type:1) AND age:35) OR type:1"
>     }
>   }
> }'
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.25,
    "hits" : [ {
      "_index" : "test",
      "_type" : "mytype",
      "_id" : "1",
      "_score" : 1.25,
      "_source":{"name":"Paul", "age":35, "type":1}
    }, {
      "_index" : "test",
      "_type" : "mytype",
      "_id" : "2",
      "_score" : 0.25,
      "_source":{"name":"Paul", "age":13, "type":1}
    } ]
  }
}
[root@hadoop1 bin]# curl -XPOST localhost:9200/test/_search?pretty=true -d '{
  "query": {
    "query_string": {
      "query": "age:13 OR (type:1 AND age:35) OR type:1"
    }
  }
}'
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "test",
      "_type" : "mytype",
      "_id" : "1",
      "_score" : 1.0,
      "_source":{"name":"Paul", "age":35, "type":1}
    }, {
      "_index" : "test",
      "_type" : "mytype",
      "_id" : "2",
      "_score" : 0.6666667,
      "_source":{"name":"Paul", "age":13, "type":1}
    } ]
  }
}
[root@hadoop1 bin]# curl -XPOST localhost:9200/test/_search?pretty=true -d '{
  "query": {
    "query_string": {
      "query": "(age:13 OR type:1) AND (age:35 OR type:1)"
    }
  }
}'
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.25,
    "hits" : [ {
      "_index" : "test",
      "_type" : "mytype",
      "_id" : "1",
      "_score" : 1.25,
      "_source":{"name":"Paul", "age":35, "type":1}
    }, {
      "_index" : "test",
      "_type" : "mytype",
      "_id" : "2",
      "_score" : 1.25,
      "_source":{"name":"Paul", "age":13, "type":1}
    } ]
  }
}</pre>

**Comment by jasontedor** [comment]
A [query string query](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/query-dsl-query-string-query.html#query-string-syntax) is effectively a wrapper to classic [Lucene query parser syntax](http://lucene.apache.org/core/5_4_1/queryparser/org/apache/lucene/queryparser/classic/package-summary.html#package_description). There are some [notoriously tricky](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/query-dsl-query-string-query.html#_boolean_operators) issues surrounding the precedence rules (cf. [LUCENE-1823](https://issues.apache.org/jira/browse/LUCENE-1823) and [`BooleanQuerySyntax`](https://wiki.apache.org/lucene-java/BooleanQuerySyntax) for historical background) and so if there's any possible confusion for precedence, you should just use [grouping](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/query-dsl-query-string-query.html#_grouping) so as to remove all such confusion.

For future reference, questions like this are best asked on the [Elastic Discourse forums](https://discuss.elastic.co) whereas bug reports and feature requests are best reported here. If you do have a followup question, please open a discussion there and the community will be very happy to engage with you. :)
