### ISSUE TITLE
when set "index.max_result_window" to Long.MAX_VALUE get error "Failed to parse int setting"

### ISSUE THREAD

**Issue by arman1371** [elastic/elasticsearch#16331]
When set `index.max_result_window` to `Long.MAX_VALUE` there is no problem.
index settings: 
```json
    "settings" : {
      "index" : {
        "number_of_shards" : "5",
        "max_result_window" : "9223372036854775807",
        "creation_date" : "1454230598724",
        "number_of_replicas" : "0",
        "uuid" : "xSkP-DuMTdOE7tIvSpAnlw",
        "version" : {
          "created" : "2010199"
        }
      }
    }
```

but when i want to search in that index i get this error
```json
{
  "error": {
    "root_cause": [
      {
        "type": "settings_exception",
        "reason": "Failed to parse int setting [index.max_result_window] with value [9223372036854775807]"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "alarm-2016-01-31",
        "node": "Z-Zz7yE_RJ6dnO3Uezo4og",
        "reason": {
          "type": "settings_exception",
          "reason": "Failed to parse int setting [index.max_result_window] with value [9223372036854775807]",
          "caused_by": {
            "type": "number_format_exception",
            "reason": "For input string: \"9223372036854775807\""
          }
        }
      }
    ]
  },
  "status": 500
}
```

If user can't set this value to `Long.MAX_VALUE`, don't set the value.

**Comment by nik9000** [comment]
Sorry about that! This is already fixed in master as part of the great setting rewrite (allows resetting settings to default, listing them along with their default, atomically applying changes, etc). Keep the value under Integer.MAX_VALUE and you should be fine.

**Comment by clintongormley** [comment]
While @nik9000 is technically correct, setting this setting to MAXINT is really damaging to your system.  Expect it to fall over.  This is why we added this limit in the first place.

**Comment by nik9000** [comment]
> While @nik9000 is technically correct, setting this setting to MAXINT is really damaging to your system. Expect it to fall over. This is why we added this limit in the first place.

Right. When I wrote "you should be fine" I meant, "the setting won't break anything" but @clintongormley is right, it is a bad idea to set it that high.
