### ISSUE TITLE
GroovyScriptIT fails with SIGSEGV

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#16339]
We've encountered a segment violation in [build 663 for ES 2.0](http://build-us-00.elastic.co/job/elasticsearch-20-medium/663) in `GroovyScriptIT`:

```
[ERROR] ERROR: JVM J0 ended with an exception: Forked process returned with error code: 134. Very likely a JVM crash.  See process stdout at: /mnt/jenkins/workspace/elasticsearch-20-medium/core/target/junit4-J0-20160131_224721_430.sysout
```
- JDK: 8.0_60-b27 (build 1.8.0_60-b27)
- OS: Ubuntu 12.04.3 LTS (Kernel 3.2.0-52)
- VM Args: -Xmx512m -Xms512m -XX:MaxDirectMemorySize=512m -Des.logger.prefix= -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/jenkins/workspace/elasticsearch-20-medium
- Variables: -Dtests.prefix=tests -Dtests.seed=7C91414F00CB3DCD -Des.logger.level=DEBUG -Des.node.local= -Des.node.mode=local -DhaltOnFailure= -Djava.awt.headless=true -Djava.io.tmpdir=./temp -Dtests.appendseed= -Dtests.assertion.disabled=false -Dtests.awaitsfix= -Dtests.badapples= -Dtests.bwc= -Dtests.bwc.path= -Dtests.bwc.version= -Dtests.class= -Dtests.client.ratio= -Dtests.cluster= -Dtests.compatibility= -Dtests.config= -Dtests.enable_mock_modules= -Dtests.failfast= -Dtests.filter= -Dtests.heap.size=512m -Dtests.iters= -Dtests.jvm.argline= -Dtests.locale=random -Dtests.maven=true -Dtests.maxfailures= -Dtests.method= -Dtests.network=true -Dtests.nightly= -Dtests.project=org.elasticsearch:elasticsearch -Dtests.rest= -Dtests.rest.blacklist=cat.recovery/10_basic/\* -Dtests.rest.load_packaged= -Dtests.rest.spec= -Dtests.rest.suite= -Dtests.security.manager=true -Dtests.showSuccess= -Dtests.thirdparty= -Dtests.timeoutSuite=500000 -Dtests.timezone=random -Dtests.verbose=false -Dtests.verify.phase=true -Dtests.version=2.0.3-SNAPSHOT -Dtests.weekly= -Djunit4.childvm.cwd=/mnt/jenkins/workspace/elasticsearch-20-medium/core/target/J0 -Djunit4.childvm.id=0 -Djunit4.childvm.count=1

Core dumps were disabled on the build machine. Find attached stdout ([junit4-J0-20160131_224721_430.sysout](https://github.com/elastic/elasticsearch/files/112030/junit4-J0-20160131_224721_430.sysout.txt)) and the JVM crash log ([hs_err_pid3786.log](https://github.com/elastic/elasticsearch/files/112031/hs_err_pid3786.log.txt)).

**Comment by danielmitterdorfer** [comment]
The Groovy scripting language was deprecated in 5.0 and removed in 6.0 with #21607 so I'd keep this ticket open at most as long as we run scheduled builds for ES 5.x.

**Comment by jasontedor** [comment]
Can we just close it? It doesn't look it's a recurring issue, and I don't think anyone is/is going to dig into this unless it recurs frequently?

**Comment by danielmitterdorfer** [comment]
Sure, I'm fine with closing it; I was just conservatively adding a comment instead of closing it preliminary. :)
