### ISSUE TITLE
https://maven.elasticsearch.org certficate expired

### ISSUE THREAD

**Issue by brackxm** [elastic/elasticsearch#16343]
The certificate from https://maven.elasticsearch.org/releases is expired.

**Comment by danielmitterdorfer** [comment]
Thanks for reporting the certificate expiry. Where working on it.

**Comment by mrsolo** [comment]
Fixed

<img width="1419" alt="art cert" src="https://cloud.githubusercontent.com/assets/96771/12726528/f0e76d38-c8cc-11e5-823b-9b0a341eb0e9.png">
