### ISSUE TITLE
Field stats API raises index_closed_exception

### ISSUE THREAD

**Issue by erik-stephens** [elastic/elasticsearch#16351]
The fact that I can't find anyone else with this problem suggests the problem is on my end, but based on the docs and the response I get, [this looks like a bug](https://discuss.elastic.co/t/index-closed-exception/38424).  1451407412544 is roughly Dec 29 09:43:32 MST 2015 and 1452012212544 is roughly Jan  5 09:43:32 MST 2016.  My first thought was that maybe I have documents in the closed indices that fall with this range.  If that were the case, shouldn't the field stats response include those indices in its reply after I open them?

**Comment by martijnvg** [comment]
What is the exact ES version that you're using? 
Are you by any chance specifying indices that are closed in the field stats api?

Closed indices are never queried if field stats executes of all indices, so this is weird if you're seeing these exceptions. I quickly tries to re-create a scenario with a closed index, but the field stats api just skips that closed index.

**Comment by erik-stephens** [comment]
The version is 2.1.1.  Took me a while, but I was finally able to reproduce on a test cluster with test data.  Looks like my problem is that I have lingering aliases for closed indices.  Now I'm seeing unexpected results around aliases but that's maybe for another thread.  Thanks for the reply - it helped me narrow it down.
