### ISSUE TITLE
Accessing parent properties in script_fields seems no more possible in 2.x

### ISSUE THREAD

**Issue by temsa** [elastic/elasticsearch#16368]
I have a request running on ES 1.4.5 which does not work at all on ES 2.x (tested on 2.1.2, but I guess it's more a 2.x problem) : 
- given a parent `parent` with a property `foo` in the mapping
- given a child `child`with a property `bar` in the mapping
- given a mapping linking the `child` with the `parent`
- given a search query on `child` with a `has_parent` filter

With ES 1.4.5, I could use in groovy `script_fields`, use query function_score functions `script_score` and use filter script `script` code like `doc['parent.foo'].value` as well as `doc['child.bar'].value` and it worked very well.

Whith ES 2.1.2, I have a script error with both `doc['parent.foo'].value` and `doc['child.bar'].value` refering to 'parent.foo' or 'child.bar' not existing in the mapping. The same request would work perfectly on 1.4.5.

So, I've then changed it to, `doc['foo'].value` and `doc['bar'].value` so it would run the scripts without an error :
-  `doc['bar'].value` is ok ( the child value )
-  `doc['foo'].value` is always null ( the parent value )

As I need such a feature, how do I fix this ?

**Comment by clintongormley** [comment]
You can no longer use type names as a prefix for field paths.  And you can't access a child document's values when you're in the context of the parent (and vice versa).  They are completely separate documents.

**Comment by temsa** [comment]
@clintongormley I need this feature... If not I will be stuck with a ES 1.x ?

Should I be able to create a plugin to support accessing parent document ? I could maybe add `parent['foo'].value` in the scripts, the same way there is `doc['bar'].value`, is it achievable ? Will there be a huge cost in term of performance or should it be not too far from 1.x performances?

Where should I start to add something available inside scripts ? I've been reading the source of elasticsearch core for about an hour and the source of 2 plugins too, I'm on the way but I did not really found where to start for now...

**Comment by temsa** [comment]
@clintongormley  ?

**Comment by clintongormley** [comment]
@temsa the parent is in a completely separate document. accessing it will perform horribly. this is why we don't support it.  Denormalise your data instead.

**Comment by temsa** [comment]
@clintongormley it would mean updating about ~500 000 documents rather than ~500 every ~30s. I'm not sure it would perform that much less horribly, are you ?

**Comment by clintongormley** [comment]
@temsa if it worked on 1.x, it was by chance, and only sometimes.  this was never supported

**Comment by temsa** [comment]
@clintongormley okay, I guess I have a lot of chance as it worked for several versions (1.4.5 up to 1.7x with no issue but something totally unrelated concerning geopoint mapping in script_fields, which seems fixed in 2.x, and not backported to 1.x ...).

From an external point of view it does not look like that it is much different from `inner fields`, is that ?

BTW, your only role here seems to be telling me explicitly its an abuse of ElasticSearch, that this is bad, and this is not a feature, just something incidental, like a bug, etc. Ok, understood, really.

Maybe you can albeit redirect me to someone else or some documentation, or even some code to look at ? This would be a bit more helpful, and would answer a bit to my questions, so I can make this horribly performing plugin, at least for myself ? or give me an alternative to this plugin ?

**Comment by clintongormley** [comment]
@temsa here's an example demonstrating what i'm talking about.  This works in exactly the same way on 1.7.5 and 2.2.0:

    PUT test
    {
      "mappings": {
        "parent": {},
        "child": {
          "_parent": {
            "type": "parent"
          }
        }
      }
    }
    
    PUT test/parent/1
    {
      "parent": 5
    }
    
    PUT test/child/2?parent=1
    {
      "child": 10
    }
    
Now we run a `has_parent` query - the main query only returns values in the child document (as only child documents have a parent, while inner hits in the `has_parent` clause returns only values in the parent document:

    GET test/_search
    {
      "script_fields": {
        "parent": {
          "script": "doc['parent'].value"
        },
        "child": {
          "script": "doc['child'].value"
        }
      },
      "query": {
        "has_parent": {
          "type": "parent",
          "inner_hits": {
            "script_fields": {
              "parent": {
                "script": "doc['parent'].value"
              },
              "child": {
                "script": "doc['child'].value"
              }
            }
          },
          "query": {
            "match_all": {}
          }
        }
      }
    }
    
And the reverse is true when running a `has_child` query:

    GET test/_search
    {
      "script_fields": {
        "parent": {
          "script": "doc['parent'].value"
        },
        "child": {
          "script": "doc['child'].value"
        }
      },
      "query": {
        "has_child": {
          "type": "child",
          "inner_hits": {
            "script_fields": {
              "parent": {
                "script": "doc['parent'].value"
              },
              "child": {
                "script": "doc['child'].value"
              }
            }
          },
          "query": {
            "match_all": {}
          }
        }
      }
    }

So unless you are talking about something else (which would have been instantly apparent had you provided a curl example of what you were doing) then your statement that you could access parent and child values within the same query context seems to be false.
