### ISSUE TITLE
Field name missing from invalid mapping error

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch#16378]
When trying to create a mapping for master I got the error:

```
Failed to parse mapping [_default_]: Can't parse [index] value [not_analyzed], expected [true] or [false]
```

It took a while to track down that this was being caused by numeric fields with the `index: not_analyzed` setting. It would have been much easier to debug if the error message contained the field name.

**Comment by spalger** [comment]
ping

**Comment by spalger** [comment]
A new variation on this error message that showed up today, it doesn't list the expected values but does mention the field.

```
Failed to parse mapping [_default_]: wrong value for index [true] for field [lastname]
```

**Comment by s1monw** [comment]
@spalger I will take a look at these problems

**Comment by clintongormley** [comment]
@spalger `index` now takes `true`/`false`:  https://github.com/elastic/elasticsearch/pull/16161

What did you do to get the second message? You sure that was on master?

**Comment by clintongormley** [comment]
Ah, I see this is about the exception message, rather than this change. OK

**Comment by s1monw** [comment]
> A new variation on this error message that showed up today, it doesn't list the expected values but does mention the field.

i think this one is stale - I can't fine it anymore.... I will have a fix for the others.
