### ISSUE TITLE
_type has no mapping properties

### ISSUE THREAD

**Issue by johncollaros** [elastic/elasticsearch#16389]
This has come up in the context of kibana:
#https://github.com/elastic/kibana/issues/5684

For new indicies created in ES 2.x, kibana sees _type as unindexed.
It looks like the mapping properties are empty. This seems to affect Kibana's ability to properly discover the mapping.

I have a feeling this is to do with the change not allowing mapping options for metafields like _type, _id etc.

I have provided examples below using the mapping API against a pre 2.x index and a post 2.x index both running inside ES 2.1

Pre 2.x index
/oldindex-2014.12.28/_mapping/logs/field/_type?include_defaults=true

```
{
  "oldindex-2014.12.28": {
    "mappings": {
      "logs": {
        "_type": {
          "full_name": "_type",
          "mapping": {
            "_type": {
              "store": false,
              "index": "not_analyzed"
            }
          }
        }
      }
    }
  }
}
```

New 2.x index:
/newindex_2-2015.01.01/_mapping/logs/field/_type?include_defaults=true

```
{
  "newindex_2-2015.01.01": {
    "mappings": {
      "logs": {
        "_type": {
          "full_name": "_type",
          "mapping": {

          }
        }
      }
    }
  }
}

**Comment by clintongormley** [comment]
The metadata fields have been locked down and (mostly) are no longer configurable.  Mappings emitted by this API can't be roundtripped (ie used to configure the mapping for a new index) because the metadata fields won't accept these parameter.

I think the solution is for kibana to hard code the mapping for metadata fields.

**Comment by johncollaros** [comment]
That's a bit of a shame because it breaks discovery of mappings.
How hard is it to have the mapping settings to be read-only for these meta-fields?

**Comment by rashidkpc** [comment]
@clintongormley I'm not sure I agree here:

```
I think the solution is for kibana to hard code the mapping for metadata fields.
```

The problem is if the mappings for those fields ever change in any way, or the names change, or new ones are added. Kibana would have to keep the same list that Elasticsearch is already keeping, but do it manually.

**Comment by brwe** [comment]
> Mappings emitted by this API can't be roundtripped (ie used to configure the mapping for a new index) because the metadata fields won't accept these parameter.

Do people use the field mapping api for round tripping mappings or do they use regular mappings api? Because if Kibana uses field mapping api to get this kind of information but for round tripping people use mapping api then there is no conflict anyway.

**Comment by rashidkpc** [comment]
I was under the impression that the field mapping API was read-only anyway

**Comment by GlenRSmith** [comment]
Couldn't there be either a metadata API or an include_metadata parameter? Or some other method of exposure? "Self documenting" would be a good thing in general.

**Comment by clintongormley** [comment]
While not changing the output for metadata fields, this change will solve the issue for Kibana: https://github.com/elastic/elasticsearch/issues/17750
