### ISSUE TITLE
"fields" is missing in hit if script field returns a null value

### ISSUE THREAD

**Issue by pierrre** [elastic/elasticsearch#16408]
I use Elasticsearch 2.2 & 1.7.

With this query:
```json
{
  "script_fields": {
    "test": {
      "script": "return null"
    }
  }
}
```

Elasticsearch 1.7 returns:
```json
{  
  "_index":"xxx",
  "_type":"yyy",
  "_id":"51a79adcb5d07a18fc522160",
  "_score":1,
  "fields":{  
    "test":[  
      null
    ]
  }
}
```

Elasticsearch 2.2 returns:
```json

{  
  "_index":"xxx",
  "_type":"yyy",
  "_id":"51a79adcb5d07a18fc522160",
  "_score":1
}
```

Is it a bug or a feature?

**Comment by rjernst** [comment]
This is the result of #8592. If we want to support `null` as a valid return value from scripts, we would need to remove the first `if` condition added there. @jpountz thoughts?

**Comment by jpountz** [comment]
@rjernst Sounds good to me.
