### ISSUE TITLE
Document network changes in 2.2.0

### ISSUE THREAD

**Issue by jlecour** [elastic/elasticsearch#16406]
Hi,

I have a 2.1 cluster, with default `network.host` configuration and a custom `network.publish_host`.

After upgrading to `2.2.0` the cluster didn't start.

I've had to change from : 

```
network.publish_host: 123.456.789.123
```

to

```
network.host: ["127.0.0.1", "123.456.789.123"]
network.publish_host: ["123.456.789.123"]
```

It'd be great it this were documented : 
- in the changelog, with instruction for upgrading
- in the documentation

That said, congratulations for this release. Elasticsearch is awesome. :clap:

**Comment by schmorgs** [comment]
Hi, I have the exact same problem.  Settings worked in 2.1.0 but broke in 2.2.0

I tried your suggestion but in my case, I only want ES to listen on loopback as we have it behind a reverse proxy.  When I add both interfaces to network.host, it means the port is open externally as well.

If I then override network.bind_host to 127.0.0.1 only, it breaks the cluster again.

This breaks : 
```
network.host: ["127.0.0.1","1.2.3.4"]
network.publish_host: ["1.2.3.4"]
transport.bind_host: 1.2.3.4
network.bind_host: 127.0.0.1
http.port: 9200
```

This works but means ES listens on external interface which is less secure (in our case) : 
```
network.host: ["127.0.0.1","1.2.3.4"]
network.publish_host: ["1.2.3.4"]
transport.bind_host: 1.2.3.4

http.port: 9200
```

**Comment by clintongormley** [comment]
Hi @jlecour 

The breaking change is documented in the breaking changes list: https://www.elastic.co/guide/en/elasticsearch/reference/2.2/breaking_20_network_changes.html and the network setup docs have been greatly improved here: https://www.elastic.co/guide/en/elasticsearch/reference/2.2/modules-network.html#advanced-network-settings

What do you think is still missing?

**Comment by clintongormley** [comment]
@schmorgs you seem to have misunderstood these settings (if i understand you correctly).  If Elasticsearch binds only to localhost, then it is unable to communicate with nodes on other servers.

**Comment by schmorgs** [comment]
Maybe I have, but the intention is that ES will only listen on loopback for incoming http requests. I then then sit ES:9200 behind a reverse proxy to control incoming access.
In 2.1.0 it worked as desired but in 2.2.0 won't start up. I've been given a potential solution elsewhere which is to set http.publish_host and I haven't tried that yet but will update if it works


Trevor

**Comment by clintongormley** [comment]
@schmorgs in which case you want to set `http.host`: https://www.elastic.co/guide/en/elasticsearch/reference/2.2/modules-http.html

**Comment by clintongormley** [comment]
No further feedback. Closing
