### ISSUE TITLE
Elasticsearch 2.2 : Cant install marvel plugin

### ISSUE THREAD

**Issue by abtpst** [elastic/elasticsearch#16416]
I am trying to install the marvel sense plugin for ES and Kibana on windows. I have ES version 2.2.0 and Kibana version 4.4.0

Here is what i tried to do

For ES

    plugin install license

i get

    -> Installing license...
    Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugi
    n/license/2.2.0/license-2.2.0.zip ...
    ERROR: failed to download out of all possible locations..., use --verbose to get
     detailed information

i also tried

    plugin install marvel-agent

but i get

    -> Installing marvel-agent...
    Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugi
    n/marvel-agent/2.2.0/marvel-agent-2.2.0.zip ...
    ERROR: failed to download out of all possible locations..., use --verbose to get
     detailed information

For Kibana, i knew it wasn't going to work but still

i tried

    plugin --install elasticsearch/marvel/latest

and i get

    Installing marvel
    Attempting to transfer from https://download.elastic.co/elasticsearch/marvel/mar
    vel-latest.tar.gz
    Error: Client request error: connect ETIMEDOUT
    Plugin installation was unsuccessful due to error "Client request error: connect
     ETIMEDOUT"

has anyone faced similar issues? Any help would be appreciated. I did not face these problems for ES 2.1 and Kibana 4.3

I downloaded everything from the ES website.

**Comment by dadoonet** [comment]
https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/marvel-agent/2.2.0/marvel-agent-2.2.0.zip actually exists. May be you are running behind a proxy?

Note that if you want SENSE, you don't need to install Marvel at all.

Feel free to join us on discuss.elastic.co where we can provide a better support for questions like this one.

**Comment by abtpst** [comment]
thanks, i am behind a proxy but i was able to perform the same operations for ES 2.1 and Kibana 4.3. moreover, i have the proxy env variables defined. By the way, how do i use SENSE without installing sense? when i go to

http://localhost:5601/app/sense

i get

{"statusCode":404,"error":"Not Found","message":"Unknown app sense"}

**Comment by dadoonet** [comment]
I said that you don't need to install MARVEL.
