### ISSUE TITLE
Indices cat API doesn't list closed indices when filtered

### ISSUE THREAD

**Issue by jlecour** [elastic/elasticsearch#16419]
Hi,

With the `indices` cat API, I can list my indices, either *open* or *close*.

```
→ curl http://127.0.0.1:9200/_cat/indices
       close partner_results-20150930
yellow open  partner_requests-20150929     1 1     17     0 230.3kb 230.3kb
yellow open  partner_results-20151102      5 1   4311     0   1.5mb   1.5mb
yellow open  search_requests-20150902      5 1     10     0  51.3kb  51.3kb
```

If I filter my results, I no longer see *close* indices : 

```
→ curl http://127.0.0.1:9200/_cat/indices/\*_results-\*
yellow open  partner_results-20151102      5 1   4311     0   1.5mb   1.5mb
```

I didn't find the documentation about that so I don't know if it a bug or an undocumented behavior.

I thought there might be an argument for `/_cat/indices` to show `all/open/close` indices, but I haven't found anything.

**Comment by debarshiraha** [comment]
I would like to start contributing by fixing this one, if this can be assigned to me!

**Comment by nik9000** [comment]
> I would like to start contributing by fixing this one, if this can be assigned to me!

Grumble grumble it looks like you can't assign non-"elastic members" to issues. I was wrong! Anyway, consider it claimed.

**Comment by dadoonet** [comment]
@nik9000 In such a case, I think we can remove the `adoptme` label. I just updated the issue.

**Comment by nik9000** [comment]
> @nik9000 In such a case, I think we can remove the adoptme label. I just updated the issue.

Thanks!
