### ISSUE TITLE
Kibana : How to create interactive searchbar in dashboard

### ISSUE THREAD

**Issue by abtpst** [elastic/elasticsearch#16429]
I want to create an interactive search bar in Kibana. Lets say i have a field that has 5 values
    
    Field_A
    a
    b
    c
    d
    e

is it possible to have a searchbar in a Kibana dashboard that allows a user to type in a query like

    Field_A="a"

and then all of the records for the query results show up

It would be even better if i can have a dropdown list that gives me all of the values in the Field_A, possibly sorted, and then the user can select a particular value and see all the records that have that value.

I know this is possible in splunk.

**Comment by jasontedor** [comment]
Sorry if I'm missing something here, but this sounds like it would get better attention on the [Kibana repository](https://github.com/elastic/kibana)?
