### ISSUE TITLE
Upsert needs better version collision between new and existing docs

### ISSUE THREAD

**Issue by rnagappan** [elastic/elasticsearch#16438]
We have the situation where different users can write to the same ES instance from different client applications so there is no central application layer where we can enforce write consistency - we're relying on ES as a distributed store to do that for us.

So consider two different users on two different clients that try to write the same document to ES using the same deterministic ID (e.g. the document's name). User A sets their document to version 1 because ES requires a minimum of version 1 to store, and then the upsert request happily indexes this as a new document. But then user B on a completely different client also creates what they think is a new document with the same ID and sets it's version to 1 also, and they submit an upsert request for it. ES happily accepts it as an update instead and overwrites the document that user A just submitted under the same ID. What should have happened in this case is a version collision instead. Upsert has no way to differentiate between a new document and the first update to an existing document, because they both have version 1.

It would be better for us if upsert could accept version 0 for a new document. One workaround is that on our client we can test for it, but then we are using create and update, not upsert.

**Comment by jasontedor** [comment]
Maybe I'm misunderstanding, but it sounds like you want the semantics of create not upsert, and you want the second creation attempt to fail? That is, you want the loser of the race to fail. Elasticsearch provides this is with the [index API if you use `_create` on the request](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#operation-type).

For future reference, questions like this are best asked on the [Elastic Discourse forums](https://discuss.elastic.co). GitHub is reserved for bug reports and feature requests.

**Comment by rnagappan** [comment]
Ok thanks. But upsert still has that weakness that when two different clients both submit version 1, the first one will eventually get their data overwritten by the second one. This seems like a failure of the version semantics to me.

**Comment by jasontedor** [comment]
But you shouldn't use upsert for create semantics. And *after* the document is created, you can use [optimistic concurrency control](https://www.elastic.co/guide/en/elasticsearch/guide/current/optimistic-concurrency-control.html) to ensure that the scenario that you describe can't happen. That is, if a user thinks they are creating a new document, use the index API with `_create` and the request will fail if the document already exists. And if the user is updating a document, use the update API with the expected version on the update which will fail if that version is wrong (i.e., two users grab version 1 of the document, they both submit upserts with expected version 1, only one of the upserts will win and the second will fail).

**Comment by rnagappan** [comment]
Thanks, I am familiar with that page. I guess what I'm saying is that insert/create is safe for concurrent usage, and update is also safe for concurrent usage. But upsert is not always safe for concurrent usage because the "update" and "insert" parts of it can conflict with each other. I was hoping to raise this as a bug so that two clients could safely upsert at the same time, but you seem to saying that they can't - that they can only safely use the update part of the upsert at the same time. Maybe I am missing something here. Anyway, no matter, thanks for your help.

**Comment by jasontedor** [comment]
> But upsert is not always safe for concurrent usage because the "update" and "insert" parts of it can conflict with each other.

Can you you provide a reproduction exhibiting what you think is a bug with a complete explanation of what you observe happening and what you think should be happening? What I *think* you're saying should not be possible because of an internal versioning mechanism that's in place; a reproduction should help disambiguate the discussion.

**Comment by rnagappan** [comment]
If two users on two different clients both try to create a new doc with the same ID and version 1, one will fail, this is expected. If two users on two different clients both try to update an existing doc with the same ID and version 1, one will fail, this is expected. 

But if two users on two different clients both try to upsert a _new_ doc with the same ID and version 1, _both_ will succeed, but the second user's upsert will just overwrite the first user's upsert. Compared to the fail fast concurrency semantics of create and update above, this behaviour seems wrong to me. 

The problem is that version 1 is doing double duty as both the initial insert version and the first update version. In my opinion if you are going to offer a combined insert/update operation then version 1 should not have this dual conflicting duty.

I can get around this in my client code by writing "if new doc then call create API else call update API" but I thought that is what the upsert API is supposed to be!

**Comment by jasontedor** [comment]
But can you provide a minimal reproduction exhibiting what you think is a bug? It will really help disambiguate this discussion. I *think* that in master (after #13955), the situation that you're describing will produce a `VersionConflictException` but code will help clarify the discussion.

**Comment by clintongormley** [comment]
@rnagappan Have you actually tried this?

If I set `?version=1` for a non-existent doc, I get a conflict failure:

    POST t/t/1/_update?version=1
    {
      "doc": {
        "foo": 2
      },
      "upsert": {
        "foo": 1
      }
    }

Returns:

    {
      "error": {
        "root_cause": [
          {
            "type": "version_conflict_engine_exception",
            "reason": "[t][1]: version conflict, current [-1], provided [1]",
            "shard": "3",
            "index": "t"
          }
        ],
        "type": "version_conflict_engine_exception",
        "reason": "[t][1]: version conflict, current [-1], provided [1]",
        "shard": "3",
        "index": "t"
      },
      "status": 409
    }

**Comment by rnagappan** [comment]
Apologies for my absence, I was snowed under with other work.

Yes, if I set version 1 for the insert part of an upsert query then I get a version conflict error.

Here is a test that I just wrote to illustrate the problem:

    @org.junit.Test
    public void testSomething() throws Exception
    {
        Settings settings = Settings.builder().put("cluster.name", "minions").build();
        TransportClient client = TransportClient.builder()
                                                .settings(settings)
                                                .build()
                                                .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("localhost"), 9300));
        try
        {
            // Part 1: the first client thinks they have a new document and they try to upsert it
            XContentBuilder source1 = XContentFactory.jsonBuilder()
                                                     .startObject()
                                                     .field("minionese", "banana!")
                                                     .endObject();
            IndexRequest indexRequest1 = new IndexRequest("minion-language", "sayings", "10")
                .version(-3)
                .source(source1);
            UpdateRequest updateRequest1 = new UpdateRequest("minion-language", "sayings", "10")
                .version(1)
                .doc(source1)
                .upsert(indexRequest1);
            client.update(updateRequest1).get();

            // Part 2: meanwhile, the second client also thinks they have a new document and they try to upsert it too
            XContentBuilder source2 = XContentFactory.jsonBuilder()
                                                     .startObject()
                                                     .field("minionese", "bee do bee do")
                                                     .endObject();
            IndexRequest indexRequest2 = new IndexRequest("minion-language", "sayings", "10")
                .version(-3)
                .source(source2);
            UpdateRequest updateRequest2 = new UpdateRequest("minion-language", "sayings", "10")
                .version(1)
                .doc(source2)
                .upsert(indexRequest2);
            client.update(updateRequest2).get();

            client.admin().indices().prepareRefresh("minion-language").get();
        }
        finally
        {
            client.close();
        }
    }

When I run this test as-is both parts 1 and 2 succeed. So the resulting data in ES is:

    {
      "took": 2,
      "timed_out": false,
      "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
      },
      "hits": {
        "total": 1,
        "max_score": 1,
        "hits": [
          {
            "_index": "minion-language",
            "_type": "sayings",
            "_id": "10",
            "_version": 2,
            "_score": 1,
            "_source": {
              "minionese": "bee do bee do"
            }
          }
        ]
      }
    }

What I want is a pattern where part 1 succeeds but part 2 fails - because both clients think they are upserting a totally new document. But I want to be able to do this using the upsert API rather than have to switch between create and update manually.

**Comment by clintongormley** [comment]
> But if two users on two different clients both try to upsert a new doc with the same ID and version 1, both will succeed, but the second user's upsert will just overwrite the first user's upsert. Compared to the fail fast concurrency semantics of create and update above, this behaviour seems wrong to me.

I don't think this is what is happening at all.  The first request's upsert succeeds, then the second request's partial doc update succeeds, resulting in version 2 of the document.  

Note: setting the version on the `upsert` portion of the request is not possible via the REST api, so the `version` of the update request (ie `1`) is applied instead, which means that an upsert cannot be combined with a specified version.

Using versions for concurrency control only makes sense if you first GET the current document, then update it passing in the same version as was retrieved.  What you are doing is not the same.  As @jasontedor said you are looking for create semantics instead.

**Comment by rnagappan** [comment]
> Using versions for concurrency control only makes sense if you first GET the current document, then update it passing in the same version as was retrieved. What you are doing is not the same.

I can sort of see what you are saying, but if I were to depend on calling Get first, that makes it an update operation, not an upsert.

**Comment by bleskes** [comment]
I think we can improve things here by making request validation stricter. IMO the following do not make sense and should be rejected:

- The version on an update request is a syntactic sugar for get of a specific version, doc merge and a version index. We should reject requests with both upsert and a version.
- If the upsert index request is versioned, we should reject the op. As Clint said, it's not possible through the rest layer, but Java clients can do so.

**Comment by clintongormley** [comment]
I've opened https://github.com/elastic/elasticsearch/issues/16671 to get the above changed

**Comment by rnagappan** [comment]
Excellent. More clarity is always better :)
