### ISSUE TITLE
Backwards incompatibility: _cache is disallowed for Or Filters

### ISSUE THREAD

**Issue by MHova** [elastic/elasticsearch#16441]
I'm using ElasticSearch v2.1.

The 2.0 [docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/breaking_20_query_dsl_changes.html#_filter_auto_caching) state that the `_cache` field is deprecated and will be ignored, but not rejected, if present in any Filters. This holds true for some filters like And Filters and Terms Filters, but for some reason ElasticSearch rejects a search request if an Or Filter contains the `_cache` field.

**Comment by Tarotato** [comment]
Hi, I'm new to this project and wanted to contribute, is this still available to fix?

**Comment by colings86** [comment]
Or filters have been removed in 5.0 so I think this issue can be closed
