### ISSUE TITLE
Unify the result interfaces from get and search in Java client

### ISSUE THREAD

**Issue by rnagappan** [elastic/elasticsearch#16440]
We are using the Java client, and we have some custom code to inflate Java objects from the returned doucments. The get and search APIs seem to return completely different interfaces and object trees, even though they both contain the same underlying information. This is a problem for us because our inflation code is then duplicated which introduces possible bugs. Can the get and search APIs on the Java client be refactored so they use the same data structures for each hit returned?

**Comment by clintongormley** [comment]
could you give us some examples?

**Comment by rnagappan** [comment]
This first example is from a Get query:

`       GetResponse getResponse = new GetRequestBuilder(...).get();
        GetField getField = getResponse.getField("some field");
        Map<String, GetField> getFields = getResponse.getFields();
        Object value = getField.getValue();// not an interface method
        MyClass myGetObject = ... // custom deserialization code on GetField objects
`

And this second example is from a search query for the same document

`
        SearchResponse searchResponse = new SearchRequestBuilder(...).get();
        SearchHits hits = searchResponse.getHits();
        SearchHit searchHit = hits.getAt(0);
        SearchHitField searchHitField = searchHit.field("some field");
        Map<String, SearchHitField> searchHitFields = searchHit.getFields();
        Object value = searchHitField.getValue(); // not an interface method
        MyClass mySearchObject = ... // custom deserialization code on SearchHitField objects
`

So both code snippets are finding the same document in ES and both are deserializing to the same java Object in the end. However, they have to go through completely different code paths to get from the same original data to the same end result. 

This is really inconvenient, and prone to bugs, because I have to write almost identical two copies of that custom deserialization code - one to deal with SearchHit and SearchHitField, and the other to deal with GetResponse and GetField - and always remember to keep them in sync with each other. It would be far better if both of these ES class structures implemented a common interface structure so I can write one common deserization method that does not care whether the document given to it came from a Get request or Search request. My deserialization code should not have to be tied to the type of request that generated the data, or even aware of it.

**Comment by javanna** [comment]
I agree that this is odd. `SearchHitField` and `GetField` hold the same members and could be unified.

**Comment by rnagappan** [comment]
Thanks for fixing this :)
