### ISSUE TITLE
Manual script reload from disk

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#16458]
Currently, scripts are scanned periodically for changes via a reload feature (https://www.elastic.co/guide/en/elasticsearch/reference/2.2/modules-scripting.html#_automatic_script_reloading).  For users who are concerned about security and turn off script reloading, it can be helpful to provide a way to trigger a manual reload of the script directory.  So that they can push a change and issue a manual reload themselves.

**Comment by clintongormley** [comment]
Given that reload would have to be a protected API, how would this differ from using indexed scripts and making those APIs protected instead?

**Comment by ppf2** [comment]
True, indexed scripts can be the alternate option here :)
