### ISSUE TITLE
Running Elasticsearch on Windows: expand service configuration doc

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#16455]
Please add more detail around configuring necessary service settings on Windows. [Running as a Service on Windows](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-service-win.html) is a great foundation, though it should be expanded to include:

* _specific_ steps for configuring minimum and maximum heap size
* any/all other service options documented in [Running as a Service on Linux](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-service.html#setup-service) relevant to Windows. Mostly, how and where to configure environment variables.
* other Windows specific considerations

For most of these, it just means launching `bin/service manager` and adding configurations to the Java tab. 

The Linux doc is a good example of how the Windows version should be. Whether ES uses init.d or systemd, it is clear where and how to configure the service.

**Comment by gmoskovicz** [comment]
+1 on this!

**Comment by gmarz** [comment]
+1 we'll jump on this asap

/cc @elastic/microsoft
