### ISSUE TITLE
try / catch failing in groovy scripts

### ISSUE THREAD

**Issue by hulu1522** [elastic/elasticsearch#16464]
I assume this is because of the new 'whitelist' in ES 2.2.0 but why would a try / catch not be allowed?  Here is the code we are using:

```groovy
str = doc[field].value.toString();

try {
  if (element == "before") {
    sub = str.substring(0, str.indexOf(character)).trim()
  } else {
    sub = str.substring(str.indexOf(character) +1).trim()
  }
} catch (e) {
  sub = null;
}; 

return sub;
```

Here is the ES response:

```json
{
  "took": 19,
  "timed_out": false,
  "_shards": {
    "total": 12,
    "successful": 5,
    "failed": 7,
    "failures": [
      {
        "shard": 0,
        "index": "<index>",
        "node": "WxYFZTjlT52MpvBRQPm_1Q",
        "reason": {
          "type": "no_class_def_found_error",
          "reason": "java/lang/Throwable",
          "caused_by": {
            "type": "class_not_found_exception",
            "reason": "java.lang.Throwable"
          }
        }
      }
    ]
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "panel_filter": {
      "doc_count": 0,
      "group_list": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": []
      }
    }
  }
}
```

**Comment by jasontedor** [comment]
This is covered in the [breaking changes for 2.2.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-2.2.html#_scripting_and_security); in particular, see [Scripting and the Java Security Manager](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/modules-scripting-security.html). You probably just need to whitelist `java.lang.Throwable`.

**Comment by hulu1522** [comment]
I followed that and it doesn't work.  I put this file in the elasticsearch users home directory and root's just to be sure.  I have not yet put it in the JAVA_HOME location yet but this way should work.

Locations:
`/home/elastic/.java.policy`
`/root/.java.policy`

```java
//
//
//     This File is Managed by Chef!
//
//  Any modifications will be overwritten.
//
//


grant {
  permission org.elasticsearch.script.ClassPermission "java.lang.Throwable";
};
```

Neither of them work.

**Comment by clintongormley** [comment]
Your policy file needs to contain the following:

    grant {
      permission org.elasticsearch.script.ClassPermission "java.lang.Throwable";
      permission org.elasticsearch.script.ClassPermission "java.lang.Exception";
      permission org.elasticsearch.script.ClassPermission "groovy.lang.GroovyException";
    };
