### ISSUE TITLE
How do master elections work

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#16463]
We should document this, cause why not!
At the moment you need to read [the code](https://github.com/elastic/elasticsearch/tree/master/core/src/main/java/org/elasticsearch/discovery/zen) to understand it.

Via [this thread](https://discuss.elastic.co/t/which-nodes-should-participate-in-election/40788/5) on discuss.

**Comment by jasontedor** [comment]
At a high-level, this is covered in the [Zen Discovery documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-zen.html#master-election) and at a low-level the source code is the best documentation. Do you see it differently @markwalkom?

**Comment by markwalkom** [comment]
That the process of how nodes talk about the election, but we don't explain
how the "election" itself is done, ie which node they figure out to elect.

**Comment by rjernst** [comment]
> but we don't explain how the "election" itself is done, ie which node they figure out to elect.
That is an implementation detail? No user should be depending on that?

**Comment by markwalkom** [comment]
Sure it doesn't impact userspace, but I don't see the harm in explaining how it works.

**Comment by clintongormley** [comment]
@markwalkom PRs welcome ;)

**Comment by jasontedor** [comment]
> Sure it doesn't impact userspace, but I don't see the harm in explaining how it works.

If there is no benefit to userspace (as we all seem to agree?), but there is a real cost to writing and maintaining such docs, I'm not sure if I see the point.

**Comment by patrickconant** [comment]
Thanks for the pointer to the code that performs leader election. It was useful to me in answering this question: Does leader election prefer master-only nodes to master-and-data nodes? 

I was wondering whether a cluster with 1 master-only node and several master-eligible data nodes would reliably elect the master-only node as their master. The answer from the code appears to be 'no'. 

It follows that having one or two master-only nodes is unwise. If you really want to push cluster-master responsibilities off of your data nodes, you ought to have three master-only nodes and make your data nodes ineligible to be master.

**Comment by jasontedor** [comment]
> I was wondering whether a cluster with 1 master-only node and several master-eligible data nodes would reliably elect the master-only node as their master. The answer from the code appears to be 'no'.

**Comment by jasontedor** [comment]
Correct.

> It follows that having one or two master-only nodes is unwise. If you really want to push cluster-master responsibilities off of your data nodes, you ought to have three master-only nodes and make your data nodes ineligible to be master.

Yes, you got it, with one caveat: set `discovery.zen.minimum_master_nodes` to two.
