### ISSUE TITLE
Java Client: Reference to org.apache.lucene.util.Version in org.elasticsearch.Version drags in lots of Lucene classes

### ISSUE THREAD

**Issue by centic9** [elastic/elasticsearch#16475]
We tried to exclude some of the large list of transitive dependencies when using the Java Client of Elasticsearch to avoid having the complete Elasticsearch server part of the client application.

Some of the transitive dependencies use other licenses than Apache-2.0, so it is currently hard to verify license status of a product when it tries to use the Elasticsearch Java Client.

The thinking is that it should be possible to not include most of lucene as it is not really used on the client and this way avoid some more dependencies further down, like spatial4j and others.

One of the first stumbling blocks is that there is a constant in org.elasticsearch.Version which drags in a lot of Lucene classes simply by referencing org.apache.lucene.util.Version. 

Hopefully removing this reference would allow to exclude some more transitive dependencies here.

Any interest in PRs or a list of references that can be excluded on the client-side?

**Comment by nik9000** [comment]
The trouble is that the Java client is the client Elasticsearch uses for node to node communication. So anything you do on the Java client is has to make sense in the node to node context.

Lots of folks have talked about making a Java client that isn't the internode client. Like one with minimal dependencies. I think this is the right thing to do.

> spatial4j

This is being worked on from the other end - getting spatial4j as not a dependency at all. It is a long process. More than one major version off.

**Comment by centic9** [comment]
FYI, the following things can be excluded in Gradle builds when only the client-side of Elasticsearch is used:

configurations {
    // exclude some unneded Elasticsearch parts 
    all*.exclude group: 'org.apache.lucene', module: 'lucene-backward-codecs'
    all*.exclude group: 'org.apache.lucene', module: 'lucene-expressions'
    all*.exclude group: 'org.apache.lucene', module: 'lucene-highlighter'
    all*.exclude group: 'org.apache.lucene', module: 'lucene-join'
    all*.exclude group: 'org.apache.lucene', module: 'lucene-memory'
    all*.exclude group: 'org.apache.lucene', module: 'lucene-queries'
    all*.exclude group: 'org.apache.lucene', module: 'lucene-queryparser'
    all*.exclude group: 'org.apache.lucene', module: 'lucene-spatial'

    all*.exclude group: 'org.hdrhistogram'
    // needed by TransportClient: all*.exclude group: 'com.twitter'
    // needed by BulkProcessor: all*.exclude group: 'com.carrotsearch'
    // needed by TransportClient: all*.exclude group: 'com.tdunning'
    all*.exclude group: 'commons-cli'
}

**Comment by nik9000** [comment]
Thanks for that.

I've *wanted* to remove dependencies from the Client but it just feels like a better idea to build a java client. On the other hand I'm not actively doing that right now either. So I don't really know what to say.

**Comment by javanna** [comment]
This was brought in other issues as well, and recently discussed in https://github.com/elastic/elasticsearch/issues/23331#issuecomment-286830030 . We have released a low level REST client that allows to communicate with Elasticsearch via http and requires minimal dependencies. We are working on a high level REST client that helps with building requests and reading responses, but that one will still depend on Elasticsearch, at least in the beginning.
See https://www.elastic.co/blog/state-of-the-official-elasticsearch-java-clients .

We would like to minimize the dependencies needed by the high level REST client as well, but we are now focussing on getting out the high level REST client and have its requests and responses compatible with the java API that many users have used up until now. Later, we will work on further improvements, but it will take time to have the high level client completely independent and with a minimal set of dependencies.
