### ISSUE TITLE
Pipeline aggregations do not return metadata

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch#16484]
https://www.elastic.co/guide/en/elasticsearch/reference/2.2/agg-metadata.html

This works fine for bucket and metrics aggregations, but for pipeline aggregations the supplied metadata isn't returned with the result.

This is a blocker for the .NET client as we're trying to leverage aggregation metadata for deserialization.

**Comment by colings86** [comment]
@gmarz which pipeline aggregation are you seeing this with? (or is it all of them?) Do you have a recreation script I can run to show the bug?

**Comment by colings86** [comment]
Actually never mind, didn't see you already have a fix

**Comment by gmarz** [comment]
Yea, sorry I wasn't clear enough originally, it's with all pipeline aggregations.
