### ISSUE TITLE
Unable to parse time with CET as the Time Zone

### ISSUE THREAD

**Issue by digitalrinaldo** [elastic/elasticsearch#16486]
I am using 2.1.1 with Java 8

This unit test fails and it fails in Elasticsearch also.  What am I missing

        String parseThis = "Thursday January 28, 2016 00:16:37 CET";
        DateTimeFormatter fmt = DateTimeFormat.forPattern("EEE MMM d, yyyy HH:mm:ss zzz");
        DateTime dateTime = fmt.parseDateTime(parseThis);

        This one passes

        String parseThis = "Thursday January 28, 2016 05:19:43 UTC";
        DateTimeFormatter fmt = DateTimeFormat.forPattern("EEE MMM d, yyyy HH:mm:ss zzz");
        DateTime dateTime = fmt.parseDateTime(parseThis);

**Comment by jasontedor** [comment]
[Time zone abbreviations](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations) are ambiguous. For example `CST` is the abbreviation for five different time zones: 

```
CST	Central Standard Time (North America) UTC−06
CST	China Standard Time                   UTC+08
CST	Central Standard Time (Australia)     UTC+09:30
CST	Central Summer Time (Australia)       UTC+10:30
CST	Cuba Standard Time                    UTC−05
``` 

This is why the [`DateTimeFormat` docs](http://joda-time.sourceforge.net/apidocs/org/joda/time/format/DateTimeFormat.html) says:

> Zone names: Time zone names ('z') cannot be parsed.
