### ISSUE TITLE
Missing Suite and Origin in ElasticSearch Release file

### ISSUE THREAD

**Issue by ThomasdOtreppe** [elastic/elasticsearch#16488]
I've been using Ubuntu automatic updates on my servers and it has been working fine for a few years. I'd like to be able to do the same with ElasticSearch. I found a [post on askubuntu.com explaining](https://askubuntu.com/questions/87849/how-to-enable-silent-automatic-updates-for-any-repository) how to do it.

It tells to look into `/var/lib/apt/lists/` directory and at the files ending with 'Release'. I'm checking elasticsearch (2.x) repo file and unfortunately, it doesn't contain `Origin` and `Suite` is empty which is a problem.

Logstash doesn't have this problem, it has both `Origin` and `Suite` and they both contain values.

**Comment by jasontedor** [comment]
> I've been using Ubuntu automatic updates on my servers and it has been working fine for a few years. I'd like to be able to do the same with ElasticSearch.

I'm interpreting this to mean that you want automatic and unattended *upgrades* to the Elasticsearch installation. I advise *very* strongly against this, or any other course of action that does not involve testing that an upgrade is not to going to break your dependencies of Elasticsearch. An unattended upgrade for a server process is *very* risky and such an upgrade should be performed deliberately. There is such an incredible variety of things that can cause issues including plugins not working, performance regressions, deprecated APIs being removed, etc. Even for a patch upgrade with the rigorous testing processes that we have in place, we can not account for every setup and use case. Computers are hard.

> I'm checking elasticsearch (2.x) repo file and unfortunately, it doesn't contain Origin and Suite is empty which is a problem.

The above disclaimer out of the way, I do not see a reason for this to not be fixed. Can you take a look @drewr?

**Comment by ThomasdOtreppe** [comment]
Could you elaborate why you don't see a reason to fix the file?

**Comment by jasontedor** [comment]
> Could you elaborate why you don't see a reason to fix the file?

I'm truly sorry that the double negative was confusing. To be perfectly clear, I think that it *should* be fixed and I am unable to come up with any reasons why it should not be fixed. :)

**Comment by ThomasdOtreppe** [comment]
You have a good point, that's a bad idea. It's not much of a problem for Logstash (it has been pretty stable and there only has been 2 breaking changes since the first time I used it and now and those were easily fixed)

**Comment by clintongormley** [comment]
@rjernst does the new gradle build add these values?

**Comment by jasontedor** [comment]
@clintongormley I think these are properties on the actual repository, not on the packages themselves.

**Comment by clintongormley** [comment]
@jasontedor ok - however, these repositories are created by our own release scripts, not something @drewr is responsible for.

**Comment by ThomasdOtreppe** [comment]
Any update on this?

**Comment by jasontedor** [comment]
> Any update on this?

This is a very low-priority task.

**Comment by rjernst** [comment]
This was fixed around the 5.0 release.
