### ISSUE TITLE
Sense output truncated

### ISSUE THREAD

**Issue by wsw70** [elastic/elasticsearch#16480]
When using Sense (2.0.0-beta2), the output window is truncated (i.e. the displayed output is as high as the query on the left):

![image](https://cloud.githubusercontent.com/assets/1345886/12851600/1332a28e-cc2b-11e5-9b72-8cb230e2164e.png)

**Comment by jasontedor** [comment]
There is a [repository](https://github.com/elastic/sense) for Sense that would be a better place to report this issue.

**Comment by wsw70** [comment]
Thanks. [Done](https://github.com/elastic/sense/issues/109).
