### ISSUE TITLE
search_analyzer without analyzer, and/or docvalues with analyzer

### ISSUE THREAD

**Issue by pweerd** [elastic/elasticsearch#16512]
When a field is not analyzed on index time, it is not possible to specify a search_analyzer.
I get a "analyzer on field [xxx] must be set when search_analyzer is set" exception.

To me this does not make sense. I can set a keyword analyzer on the field to circumvent this exception, which does exactly the same thing. However, while doing that, I cannot enable doc_values.

I find myself duplicating fields many times because of this limitations.
Those limitations are:
- docvalues don't work on analyzed fields
- search_analyzer cannot be specified on non-analyzed fields.

I presume ES is trying to protect me, but I *know* what I'm doing.
Is it possible to make this behavior more lenient?

**Comment by bleskes** [comment]
>  I know what I'm doing.

I believe you :) . Can you give a concrete example? I think it will help understanding the need for the request / perhaps offer an alternative?

**Comment by pweerd** [comment]
Trying to index TV shows.
First attempt:

curl -XPUT localhost:9200/tv_shows -d'
{
   settings: {  
      "analysis" : {
         "analyzer" : {
             "lc_text" : {
                "tokenizer" : "keyword",
                "filter": ["lowercase", "asciifolding"]
             }
          }
      }   
   },
   "mappings": {
      "doc": {
         "properties": { 
            "tv_show": {"type": "string", "analyzer" : "lc_text"}
         }
      }
   }
}'
curl -XPOST localhost:9200/tv_shows/doc -d '{ "tv_show":"3-2-1 Tučňáci" }'
curl -XPOST localhost:9200/tv_shows/doc -d '{ "tv_show":"3-2-1 Tucnaci" }'
curl -XPOST localhost:9200/tv_shows/doc -d '{ "tv_show":"3-2-1 tucnaci" }'

curl -XPUT localhost:9200/_search -d'
{
   "aggs": {
      "tv_show": {
         "terms": {
            "field": "tv_show"
         }
      }
   }
}'

Everything works fine, but fielddata is used, and common sense is that we should move to doc_values.
OK, trying that:

Second attempt:
curl -XPUT localhost:9200/tv_shows -d'
{
   "mappings": {
      "doc": {
         "properties": { 
            "tv_show": {"type": "string", "index" : "not_analyzed"}
         }
      }
   }
}'

But now the previous query obviously returns 3 different shows in the aggregation.
So, I have to do the normalization in my code. I'll do that. Though not beautiful, because it is a-symmetric)

Using the same mapping, I do:
curl -XPOST localhost:9200/tv_shows/doc -d '{ "tv_show":"3-2-1 tucnaci" }'
curl -XPOST localhost:9200/tv_shows/doc -d '{ "tv_show":"3-2-1 tucnaci" }'
curl -XPOST localhost:9200/tv_shows/doc -d '{ "tv_show":"3-2-1 tucnaci" }'
 
And we won: the query returns only 1 aggregation.
However, when users are copy-pasting the real TV show nam,e into the query box, they find nothing (of course).
So, I tried to use a search analyzer:

curl -XPUT localhost:9200/tv_shows -d'
{
   settings: {  
      "analysis" : {
         "analyzer" : {
             "lc_text" : {
                "tokenizer" : "standard",
                "filter": ["lowercase", "asciifolding"]
             }
          }
      }   
   },
   "mappings": {
      "doc": {
         "properties": { 
            "tv_show": {"type": "string", "index" : "not_analyzed", "search_analyzer": "lc_text"}
         }
      }
   }
}'

However, this is not accepted by ES, it states: "analyzer on field [tv_show] must be set when search_analyzer is set"
That is somewhat strange, because putting a keyword analyzer there (which is semantically the same as having no analyzer), would fix this exception.


curl -XPUT localhost:9200/tv_shows -d'
{
   settings: {  
      "analysis" : {
         "analyzer" : {
             "lc_text" : {
                "tokenizer" : "keyword",
                "filter": ["lowercase", "asciifolding"]
             }
          }
      }   
   },
   "mappings": {
      "doc": {
         "properties": { 
            "tv_show": {"type": "string", "index" : "no", "copy_to": ["tv_show_a", "tv_show_s"]}
            "tv_show_a": {"type": "string", "index" : "not_analyzed"}
            "tv_show_s": {"type": "string", "analyzer": "lc_text"}
         }
      }
   }
}'

This will work, but now I have to educate people to use tv_show_a for aggregations and tv_show_s for searching.
I know, doing this makes it even possible to use the standard tokenizer and let the user search for words in the show.
However, that is currently not the use case.

Whishes:
It would be great to have the ability to specify an analyzer specific for doc_values. Something like "docvalues_analyzer": "lc_keyword".
Furthermore, is it possible to make a search_analyzer work on a not-analyzed field?

**Comment by rjernst** [comment]
> It would be great to have the ability to specify an analyzer specific for doc_values. Something like "docvalues_analyzer": "lc_keyword".

Doc values doesn't have anything directly to do with analysis, but anything that is analyzed (ie broken up into multiple terms) cannot be stored in doc values. However, we would like to allow simple normalization like you want to do here on keyword fields, see this issue that is in progress: #12394.

> Furthermore, is it possible to make a search_analyzer work on a not-analyzed field?

You can set the search analyzer on any string field, but it is required to specify the analyzer. This is to make the user understand that the index time analysis still happens with a different analyzer. In your case, I would allow searching with your normalized field, but aggregate with a non analyzed multi field:

```
"mappings": {
      "doc": {
         "properties": { 
            "tv_show": {
                "type": "string",
                "analyzer": "lc_text",
                "fields": {
                    "original" : {
                        "type": "string",
                        "index": "not_analyzed"
                    }
                }
            }
         }
      }
   }
```

Now with this you would still search using your `lc_text` analyzer, but you should specify `tv_show.original` for doing aggregations.

**Comment by pweerd** [comment]
> Doc values doesn't have anything directly to do with analysis, but anything that is analyzed (ie broken up into multiple terms) cannot be stored in doc values. However, we would like to allow simple normalization like you want to do here on keyword fields, see this issue that is in progress: #12394

I partially agree. It can be dangerous to let the user put multiple terms in the index. But, suppose that we have a field with a few comma-separated values... Then it makes sense. 
Analyzing was of course tied to the Lucene indexed fields. But why not broadening that, and make it available for doc-values as well?

> You can set the search analyzer on any string field, but it is required to specify the analyzer. This is to make the user understand that the index time analysis still happens with a different analyzer.
I did understand what was going on here. But for the sake of 'understanding' we make things impossible? Hmm :-(

> Now with this you would still search using your lc_text analyzer, but you should specify tv_show.original for doing aggregations.
That solution is equivalent to my last attempt. But I consider that far from perfect, even artificial.

**Comment by clintongormley** [comment]
As @rjernst said, the new `keyword` field is being introduced specifically for this case where you want to use doc values for aggregations (possibly with case normalization) and have the field available for search as well with a `text` field.

Also note that you can set the `not_analyzed` version to `{"index": false, "doc_values": true}` so that it ONLY has doc values, and doesn't take up space in the index.

The third option that you have is to specify an analyzer at query time.

Closing in favour of https://github.com/elastic/elasticsearch/issues/12394
