### ISSUE TITLE
Newer snapshot shards may be allocated on older nodes

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#16519]
In a mixed cluster with a newer master node and a mixture of older and newer data nodes, shards from a snapshot compatible with newer data nodes might be randomly assigned to older data nodes where they cannot be restored.

The problem is reproducible using SnapshotBackwardsCompatibilityIT.testBasicWorkflow with the following command line in 2.x branch

```
mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch.qa.backwards:2.1 -Dtests.seed=A8C99BB8980117DF -Dtests.class=org.elasticsearch.bwcompat.SnapshotBackwardsCompatibilityIT -Dtests.method="testBasicWorkflow" -Des.logger.level=DEBUG -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=512m -Des.node.mode=local -Dtests.locale=fr-BE -Dtests.timezone=Asia/Thimphu
```

This test fails because it tries to allocated shards from the snapshot created on 2.x to nodes that are running 2.1.

**Comment by clintongormley** [comment]
Might a better solution be to disallow restores in a mixed cluster of master/data nodes?

**Comment by imotov** [comment]
@clintongormley I don't think we can guarantee that an old nodes will not join the cluster later on - after we performed an initial check and allowed the restore to start. So, checking the state at the beginning of the restore will not be a complete solution.
