### ISSUE TITLE
Return IP type for inner hits in IP format (dot decimal)

### ISSUE THREAD

**Issue by abulhol** [elastic/elasticsearch#16515]
Data of type IP is returned in decimal equivalent of 32bit for inner hits (as fielddata_fields). 
I have not found a way to return them in dot decimal format (x.x.x.x). 

I have put this question up for discussion in the forum a while ago:
[https://discuss.elastic.co/t/return-ip-field-from-inner-hit-in-dot-decimal-format/40452/3](url)
but nobody seems to have an idea how to solve it.

**Comment by jasontedor** [comment]
Duplicates #16290

**Comment by abulhol** [comment]
Hi Jason,
I know that I reported this before, but I do not see any real solution to this issue.
It may look trivial, but once you need to look at IP addresses, it is crucial.
Any suggestions welcome.

**Comment by abulhol** [comment]
Hi again, 
I have found the solution to this problem, see here: 
https://discuss.elastic.co/t/return-ip-field-from-inner-hit-in-dot-decimal-format/40452

**Comment by clintongormley** [comment]
@abulhol thanks for posting the solution - i think requiring the relative path is inconsistent, and i've opened https://github.com/elastic/elasticsearch/issues/16653 to get this changed
