### ISSUE TITLE
Highlighting for top hits aggregations

### ISSUE THREAD

**Issue by pkphlam** [elastic/elasticsearch#16526]
According to the documentation for top hits aggregations (ES 2.1), there is support for highlighting of the hits returned. Is there an example of how to implement this? 

I've tried the following (bucket agg combined with top hits agg) and it doesn't seem to return any highlighted fields:

```
{'aggs': {
    'dup_groups': {
        'aggs': {
            'first_doc': {
                'top_hits': { 
                    'highlight': {'fields': {'text.stemmed': {}}},
                    'size': 1,
                    'sort': 'date'}}},
    'terms': {'field': 'dup_parent', 'size': 0}}},
 'query': {'query_string': {'query': 'world'}}}
```

**Comment by martijnvg** [comment]
How is `text.stemmed` field mapped in your mapping?

**Comment by pkphlam** [comment]
```
{'mappings': {'documents': {'text.stemmed': {'full_name': 'text.stemmed',
     'mapping': {'stemmed': {'analyzer': 'doc_analyzer_stemmed',
       'term_vector': 'with_positions_offsets',
       'type': 'string'}}}}}}}
```

I should note that highlighting on `text.stemmed` works perfectly fine in a regular search (not in an aggregation).

**Comment by pkphlam** [comment]
Hmm okay so for future reference, the answer to this is that highlight must be defined BOTH outside and inside the aggregation for it to work, not just one or the other.

```
{'aggs': {'dup_groups': {'aggs': {'first_doc': {'top_hits': {'highlight': {'fields': {'text.stemmed': {}}},
      'size': 1,
      'sort': 'date'}}},
   'terms': {'field': 'dup_parent', 'size': 100}}},
 'highlight': {'fields': {'text.stemmed': {'number_of_fragments': 0}}},
 'query': {'query_string': {'default_field': 'text.stemmed',
   'query': 'world'}},
 'sort': [{'_score': {'order': 'desc'}}]}
```

**Comment by martijnvg** [comment]
This is unexpected. Highlighting specified inside a `top_hits` agg should work irregardless if normal highlighting is specified.

**Comment by clintongormley** [comment]
This appears to work just fine. Tested on 2.1.0. and 2.2.0:

    PUT t
    {
      "mappings": {
        "documents": {
          "properties": {
            "text": {
              "type": "string",
              "fields": {
                "stemmed": {
                  "term_vector": "with_positions_offsets",
                  "type": "string",
                  "analyzer": "english"
                }
              }
            }
          }
        }
      }
    }
    
    PUT t/documents/1
    {
      "dup_parent": "foo",
      "text": "hello world",
      "date": "2001-01-01"
    }
    
    GET t/_search
    {
      "size": 0,
      "aggs": {
        "dup_groups": {
          "aggs": {
            "first_doc": {
              "top_hits": {
                "highlight": {
                  "fields": {
                    "text.stemmed": {}
                  }
                },
                "size": 1,
                "sort": "date"
              }
            }
          },
          "terms": {
            "field": "dup_parent",
            "size": 100
          }
        }
      },
      "query": {
        "query_string": {
          "default_field": "text.stemmed",
          "query": "world"
        }
      },
      "sort": [
        {
          "_score": {
            "order": "desc"
          }
        }
      ]
    }

Please reopen if you can provide a curl recreation like the above which demonstrates the problem.

thanks
