### ISSUE TITLE
Loading templates via templates/ directory is not working

### ISSUE THREAD

**Issue by prashanttct07** [elastic/elasticsearch#16523]
Loading templates via templates/ directory is not working with elastic 2.x , so is this feature removed or its a bug?

That is I placed my templates in $HOME/config/templates/abc.json

But it was not taken while index creation in 2.x, where as its working with 1.7.1

**Comment by dadoonet** [comment]
Removed. See https://github.com/elastic/elasticsearch/pull/11052
