### ISSUE TITLE
Problem with dynamic multifields

### ISSUE THREAD

**Issue by raunakb94** [elastic/elasticsearch#16570]
# All the fields that are being added to the index does not have a corresponding analyzed mapping.
I am using a template mapping for my indexes as 
`{
  "template": "log",
  "settings": {
    "number_of_shards": 20,
    "number_of_replicas": 1,
    "refresh_interval": "30s"
  },
  "mappings": {
    "error": {
      "_all": {
        "enabled": false
      },
      "dynamic_templates": [{
        "strings": {
          "match_mapping_type": "string",
          "path_match":"*",
          "mapping": {
            "type": "multi_field",
            "fields": {
              "analyzed": {
                "type": "string"
              }
            }
          }
        }
      }],
      "_ttl": {
        "enabled": true,
        "default": "7d"
      },
      "properties": {
        "browserName": {
          "type": "string",
          "index": "not_analyzed"
        },
        "browserVersion": {
          "type": "string",
          "index": "not_analyzed"
        },
        "category": {
          "type": "string",
          "index": "not_analyzed"
        },
        "event": {
          "type": "string",
          "index": "not_analyzed"
        },
        "ip": {
          "type": "string","index": "not_analyzed"
        },
        "osName": {
          "type": "string",
          "index": "not_analyzed"
        },
        "referer": {
          "type": "string","index": "not_analyzed"
        },
        "userAgent": {
          "type": "string","index": "not_analyzed"
        }

      }
    }
  }
}
`
The expectation was to keep all the string fields as analyzed and also as raw in order to support both terms and search query.
On inserting documents into the indexes this resulted in the following mapping in the indexe -> 

`{
  "log" : {
    "mappings" : {
      "error" : {
        "_all" : {
          "enabled" : false
        },
        "_ttl" : {
          "enabled" : true,
          "default" : 604800000
        },
        "dynamic_templates" : [ {
          "strings" : {
            "mapping" : {
              "type" : "multi_field",
              "fields" : {
                "analyzed" : {
                  "type" : "string"
                }
              }
            },
            "match_mapping_type" : "string",
            "path_match" : "*"
          }
        } ],
        "properties" : {
          "browserName" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "browserVersion" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "category" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "data" : {
            "properties" : {
              "text" : {
                "type" : "string",
                "index" : "no",
                "fields" : {
                  "analyzed" : {
                    "type" : "string"
                  }
                }
              },
              "version" : {
                "type" : "string",
                "index" : "no",
                "fields" : {
                  "analyzed" : {
                    "type" : "string"
                  }
                }
              }
            }
          },
          "event" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "ip" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "osName" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "osVersion" : {
            "type" : "string",
            "index" : "no",
            "fields" : {
              "analyzed" : {
                "type" : "string"
              }
            }
          },
          "referer" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "timestamp" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "type" : {
            "type" : "string",
            "index" : "no",
            "fields" : {
              "analyzed" : {
                "type" : "string"
              }
            }
          },
          "userAgent" : {
            "type" : "string",
            "index" : "not_analyzed"
          }
        }
      }
    }
  }
}`

**Comment by raunakb94** [comment]
One of the payloads was 

{
    "userAgent": "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36",
    "osVersion": "8.1",
    "osName": "Windows",
    "timestamp": "2016-02-08T14:17:43Z",
    "event": "Storage frame sent failed status [un-false] [ls-false] [v4-true] M0",
    "referer": "https://www.****.com/",
    "ip": "45.126.204.12",
    "type": "exception",
    "browserName": "Chrome",
    "category": "*******",
    "browserVersion": "48.0.2564.103",
    "data": {
      "version": "4.0",
      "text": "[we.co] load 0.204s\n[v4] load 0.028s"
    }
  }'

**Comment by rjernst** [comment]
Dymamic templates are used for dynamic mappings, but it looks like you are explicitly creating mappings. You will need to set up the multi field yourself, for example, using setting up your `browserField`:

```
"browserVersion": {
    "type": "string",
    "index": "not_analyzed",
    "fields": {
        "analyzed": { "type": "string" }
    }
},
```

Note that the format for how multi fields are specified was change very long ago:
https://www.elastic.co/guide/en/elasticsearch/reference/current/_multi_fields.html
