### ISSUE TITLE
simple_query_string gives java.lang.IllegalArgumentException: Illegal shift value, must be 0..63; got shift=2147483647

### ISSUE THREAD

**Issue by harishkannarao** [elastic/elasticsearch#16577]
Hi Team,

I have got the following error when using simple_query_string with multiple fields containing numeric field.
Version: 2.2.0
OS: Windows

**Sample data:**
`curl -XPUT http://localhost:9200/blog/post/1 -d '{"foo":123, "bar":"xyzzy"}'`
`curl -XPUT http://localhost:9200/blog/post/2 -d '{"foo":456, "bar":"xyzzy"}'`

**Use simple_query_string with multiple fields**
`curl -XGET http://localhost:9200/blog/post/_search?pretty=1 -d '{"query":{"simple_query_string":{"query":"123","fields":["foo","bar"]}}}'`

**Error**
`{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Illegal shift value, must be 0..63; got shift=2147483647"
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "blog",
                "node": "6jVhZCw3Tau3cP5VtEg8Tw",
                "reason": {
                    "type": "illegal_argument_exception",
                    "reason": "Illegal shift value, must be 0..63; got shift=2147483647"
                }
            }
        ]
    },
    "status": 400
}`

**multi_match query works with the same fields**
`curl -XGET http://localhost:9200/blog/post/_search?pretty=1 -d '{"query":{"bool":{"must":[{"multi_match":{"query":"123","type":"cross_fields","fields":["foo","bar"],"operator":"and"}}]}}}'` 

Issue similar to #15860

**Comment by rjernst** [comment]
I think what happens is the string value is handled by the hidden analyzer for long fields, which expects a Long.  We should be using the field type for each field to call the `value` function, which in the case of `long` field type will call `Long.parseLong`. @dakrone thoughts?

**Comment by dakrone** [comment]
@rjernst yeah, I think that is a good idea. I will look into fixing this.

**Comment by dakrone** [comment]
Pushed a fix for this to the 2.2 branch that will be in 2.2.1, and it has been fixed in Lucene 5.5, which will be in the 2.3+ releases of ES
