### ISSUE TITLE
Data loss due to unassigned shard status on restarting application.

### ISSUE THREAD

**Issue by hemraj-sharma** [elastic/elasticsearch#16578]
Hi...

I am using play-java framework and also implemented elastic in my code. Its working fine till the application is in running mode. But when i restart application some shards get unassigned due to which data loss occurs. 

Way to get client>>>>>>

public class ElasticConfig {
private static  Node node =null;
 static private Node getNode(){
        return nodeBuilder().settings(Settings.builder()
			    				.put("path.home", "/home/user"+"/elasticData")
			    				.put("node.name", "elastic")
			    				.put("cluster.name", "elasticCluster")
			    				.put("number_of_replicas", 0)
			    				//.put("http.port",9200)
			    				//.put("index.number_of_shards", "1")
			    				.put("index.routing.allocation.include.size", "big"))
			    		.node();
}
public static Client getElasticNodeClient(){
	if(node == null){
		node = getNode();
	}
			return node.client();
	}}

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

**How should i prevent shard unassigning on restarting application.**

I searched a lot, not get proper and final solution.

**Comment by bleskes** [comment]
An unassigned shard means the master can not find any shard copies after the restart. Can you check your data folder and see what's in it? Do you see any errors in the ES logs? 

PS. you run with no replicas which means that if something goes wrong with the single copy you have  - there is no backup replica to replcae it

**Comment by hemraj-sharma** [comment]
as in the data folder under the folder of the name with index name, usually there are folders named 0,1,...,4. But when I get unassigned shard status. I find folders corresponding to the unassigned shards missing. And I didnot get any thing in the ES logs.

   I changed replica to "0". as I found a suggestion on stackoverflow for the same.

**Comment by bleskes** [comment]
>  find folders corresponding to the unassigned shards missing.

I think this is the source of your problem. If the data folder is missing, shard can not be assigned - which means ES does the right thing here.. I suggest your research what can cause this in your application or environment. At the moment it doesn't like ES was doing it, so I'm going to close this issue - if you do find any evidence that ES is deleting the shards please do reopen the ticket.

**Comment by hemraj-sharma** [comment]
Okey thanks.

**Comment by hemraj-sharma** [comment]
Sir I am new to the elastic search. I need  help from your side  to identify the problem that why it is happening. 

when I execute my application with the above configuration, 

I find the nodes directory as follows:
nodes:
           0:
           1:
           2:
and increasing, along with this the the folders(0,1,2,3,4) under the index name get deleted.
"http://localhost:9200/_nodes" 
gives the complete detail of the nodes. But I need to keep only single node in the cluster.
I think there is issue with my configuration but unable to figure out, Can you help me.
Thanks a lot.

**Comment by bleskes** [comment]
@hemraj-sharma we will need more details to know exactly. However, we reserve github to track issues with the software. Can you take this discussion to http://discuss.elastic.co ? we can then continue there..

**Comment by hemraj-sharma** [comment]
sure sir, Thanks for your support.
