### ISSUE TITLE
'size' parameter ignored when executing a function_score query

### ISSUE THREAD

**Issue by ryanmcilmoyl** [elastic/elasticsearch#16583]
It seems that the order of the keys in the search body matter when executing a function_score query.  Consider these 2 cURL requests:
```
    curl -d '{
        "query":{
            "function_score":{
                "random_score":{},
                "query":{
                    "bool":{
                        "must":{"match":{"location":"London"}}},
                        "filter":{"bool":{
                            "must":[
                                {"match":{"location":"London"}},
                                {"term":{"state":"approved"}},
                                {"range":{"num_reviews":{"gte":3}}}
                            ]
                        }
                    }
                }
            }
        },
        "size": 1
        }' "http://localhost:9200/agent_profiles_development/_search?pretty"

In this case, size is ignored and the default of 10 is used.  If we move the `size` key as so:
```
    curl -d '{
        "size": 1,
        "query":{
            "function_score":{
                "random_score":{},
                "query":{
                    "bool":{
                        "must":{"match":{"location":"London"}}},
                        "filter":{"bool":{
                            "must":[
                                {"match":{"location":"London"}},
                                {"term":{"state":"approved"}},
                                {"range":{"num_reviews":{"gte":3}}}
                            ]
                        }
                    }
                }
            }
        }
        }' "http://localhost:9200/agent_profiles_development/_search?pretty"

Then it works as expected.

**Comment by rjernst** [comment]
This works fine for me (with a simple match all query). Can you give a recreation (putting documents and running the two queries)? Do you see the same problem when using a simple query like `match_all`?

**Comment by ryanmcilmoyl** [comment]
Just tested with match_all, works as expected.  Also works when just doing the `bool` query, without the `function_score`.  Seems to be the combination of the 2.

I'll build out a test case and post it.

**Comment by javanna** [comment]
I was able to reproduce this. The query is malformed, the first must clause ends up closing the whole bool query (one too many curly brackets). Our parsers should throw an error though instead of going ahead. As a result, the second bool query replaces the previous query as part of the function score, and size gets ignored. I will work on making parsing stricter so that an error is thrown instead.

**Comment by ryanmcilmoyl** [comment]
Ha, so I was doing something wrong in there :).  

Thanks for checking that out!
