### ISSUE TITLE
Regression: cannot change default similarity for all fields

### ISSUE THREAD

**Issue by gpstathis** [elastic/elasticsearch#16594]
One should be able to change the default similarity for all fields by putting the following setting into `elasticsearch.yml` (see [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html#default-base)):

```
// Should it be index.similarity.classic.type now?
index.similarity.default.type: BM25
```

While debugging #16550 I realized this is currently broken in `master`. See following `curl` statements for reproducing:

```
echo "Delete previous tests"
curl -XDELETE 'http://localhost:9200/test/?pretty=true'
sleep 1

echo " "
echo "Create settings and mappings"
curl -XPUT 'http://localhost:9200/test/?pretty=true' -d '{
  "settings" : {
    "index" : {
      "number_of_shards" : 1,
      "number_of_replicas" : 0,
      "similarity.classic.type": "BM25",
      "similarity.custom.type": "classic"
    }
  },
  "mappings": {
    "type1": {
      "properties": {
        "field1": { "type": "string" },
        "field2": { "type": "string", "similarity": "custom" }
      }
    }
  }
}'
sleep 1

echo " "
echo "Add sample data"
curl -XPUT 'http://localhost:9200/test/type1/1?pretty=true' -d '{
  "field1": "the quick brown fox jumped over the lazy dog",
  "field2": "the quick brown fox jumped over the lazy dog"
}'
sleep 1

echo " "
echo "Search against Classic similarity field"
curl -s 'http://localhost:9200/test/type1/_search?pretty=1' -d '{
  "query" : {
    "match" : {
      "field2" : "quick brown fox"
    }
  }
}' | grep '"_score"'

echo " "
echo "NOTE!!! Classic similarity field yields a score of 0.16608897"

echo " "
echo "Search against BM25 similarity field"
curl -s 'http://localhost:9200/test/type1/_search?pretty=1' -d '{
  "query" : {
    "match" : {
      "field1" : "quick brown fox"
    }
  }
}' | grep '"_score"'

echo " "
echo "NOTE!!! BM25 field should yield a score of 0.8169974. Instead it yields 0.16608897 which is the same score as the Classic similarity field above"
```

I think the issue is with the `SimilarityService.addSimilarities()` method overwriting any `providers` configured via index settings. Working on a PR.

**Comment by gpstathis** [comment]
@s1monw see commit af0e07a above in my repo. Happy to open a PR if it looks ok to you.

**Comment by s1monw** [comment]
@gpstathis I think there is more wrong here than just that. Af far as I can tell you should not be able to overwrite this similarity that's why it's applied afterwards. To change the default you can define `similarity.base` but this seems broken too. Since default is used instead of base in lots of places. I think we need to fix all of this? Do you wanna take a look at it? 

I think in `PerFieldSimilarity` we should only use `defaultSimilarity` and the `baseSimilarity` member should go away and be assigned to `defaultSimilarity` if it's present. I also think we need to throw an exception if a build-in similarity is changed? This can be a different change. Regarding your commit I think this should all be done in a unittest which I can provide you with and example if you wanna take this on you?

**Comment by gpstathis** [comment]
@s1monw yes, a unit test for what you would like the end behavior to be would be helpful. Also, I'm a bit unclear on a few things now:

- Are we saying that one will no longer be able to define an alternative similarity that applies to all fields without going into the schema field-by-field and adding it? I.e. is this no longer desirable: 

```
index.similarity.default.type: BM25
```

- Regarding `similarity.base`, I thought it only applied to `coord()` and `queryNorm()` and was there for expert use per the [comment in the code](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/similarity/SimilarityService.java#L82). Would consolidating with `defaultSimilarity` introduce regressions elsewhere?

I can take a stab at a fix but only after #16550 which is a blocker for us at the moment and already present since 2.0. At least this bug is only on `master` and there is a workaround which is to overwrite every field in our schema with our custom similarity, field-by-field.

**Comment by s1monw** [comment]
regarding `similarity.base` I agree I misread that part. 

What I am saying is that I think nobody should be able to change the `index.similarity.classic` similarity nor any similarity that is built-in. I think we should add a dedicated `index.similarity.default.type` that can be defined by the user?

**Comment by gpstathis** [comment]
@s1monw got it now. Thanks for clarifying.

**Comment by gpstathis** [comment]
@s1monw see PR. Not sure if this is what you had in mind. The commit adds the ability to define a `index.similarity.default.type` and prevents users from redefining any built-in similarity types. The only thing I am unclear on though is the use of the `SimilarityService.DEFAULT_SIMILARITY` constant across the code and the effects this may have. `FieldMapper`, `TypeParsers` and `AllFieldMapper` reference that constant directly.
