### ISSUE TITLE
Compress entire data portion of snapshot

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#16591]
The idea is straight forward:

When creating a snapshot, gzip (or otherwise compress) the entire snapshot, then upload it to the repository.

Upside:

- Storage may be reduced for upload, download, and storage itself.

Downsides:

- Processing time, memory, and _local_ temp storage to compress segments.
- Processing time, memory, and _local_ temp storage to decompress the snapshot.
- Incremental snapshots, which is what snapshots are, would require downloading entire previous compressed snaphots (or forgoing incremental snapshots entirely), thereby increasing the workload necessary to _restore_ from snapshots.
- For compressed containers to work with incremental snapshots, an additional file that describes its contents (the segments) would need to be created, thus creating another potential source for issues.

**Comment by pickypg** [comment]
I wanted to create this issue so that it was re-openable incase we ever decide to change our minds on it. However, currently we see this as an undesirable problem rather than a benefit.

As a workaround, if you do want this effect, you _can_ force merge your index down to a single segment and snapshot afterward. In doing so, then you get the same effect and you only have to download a single file that does not need to be decompressed at the end.

**Comment by s1monw** [comment]
> Storage may be reduced for upload, download, and storage itself.

this might not be as much as you wish it would be... The lucene index is compressed pretty well I don't think it would buy us a lot.
