### ISSUE TITLE
Similarity of field cannot be changed if index contains more than one type with same field

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#16606]
The [guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/changing-similarities.html) states that if you want to change the similarity of a field you can close the index, update the mapping and then open it again. This is useful for example if someone wants to update parameters of BM25.

It does not seem to work currently if an index has more than one type which contains the field. The error message is `"Mapper for [text] conflicts with existing mapping in other types:\n[mapper [text] has different [similarity]]"`. Setting the `update_all_types` parameter does not help either.

Full reproduction below.

A workaround is to define a custom similarity for each field when the index is created and then later update the settings when the index is closed instead of the mapping. But I still think this is a bug?

```
PUT test
{
  "mappings": {
    "type1": {
      "properties": {
        "text": {
          "type": "string",
          "similarity": "BM25"
        }
      }
    },
    "type2": {
      "properties": {
        "text": {
          "type": "string",
          "similarity": "BM25"
        }
      }
    }
  }
} 

POST test/_close

POST test/_mapping/type1?update_all_types
{
  "properties": {
    "text": {
      "type": "string",
      "similarity": "default"
    }
  }
}

```

**Comment by brwe** [comment]
forgot to mention that this is on 2.2 release @jpountz says this works on master.

**Comment by jpountz** [comment]
Also closing since we are moving towards a single type.
