### ISSUE TITLE
Problem with Dis Max Query

### ISSUE THREAD

**Issue by WhiteTrashLord** [elastic/elasticsearch#16607]
Let's say I have this documents:

{
	"field1" : "Friend"

}

{
	"field1" : "Dear Friend",
	"field2" : "Dear Friend"
}

I want to perform a search for the word 'Friend' on each field. But only the best field of a document should set the score.
I tried it with Dis Max Query.
My problem is that the second document always gets a boost because the word 'Friend' is in both fields and gets a higher score than document 1 because of this.
Setting tie_breaker to 0 has no big impact.

How can I disable this boost for words in multiple fields?
I am using Elasticsearch 2.1.1.

**Comment by cbuescher** [comment]
This looks like a question better asked in our forums at https://discuss.elastic.co. We'll help you better there.
