### ISSUE TITLE
Change reindex default retry time

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#16608]
Right now reindex's smallest retry time when it receives task rejections is 50ms and it does 10 retries for a total (exponential) backoff of about 25 seconds. @bleskes suggested changing the defaults to 500ms with the goal of about a minute total backoff. The reasoning is that 50ms is super duper fast and unlikely to be long enough for the node to become less congested. 500ms is better while still being pretty soon.

**Comment by clintongormley** [comment]
Closed by #16614
