### ISSUE TITLE
document (pdf or doc) containing quotes are not well parsed or queried

### ISSUE THREAD

**Issue by rodrigueLeopold** [elastic/elasticsearch#16604]
Hello, I've got a little problem. I'm indexing documents (PDF or Word) in french using the excellent plugin "mapper-attachment". We are using elastic-search version 2.7 and have installed the plugin corresponding to the right version (at least I hope)
The plugin has been installed like that: sudo /usr/share/elasticsearch/bin/plugin install elasticsearch/elasticsearch-mapper-attachments/2.7.0
Everything works fine except for words with quotes. In french we need to separate words using quotes for exemple " the attention " is translated as " l'attention ". When I index an attachment having the words " l'attention " and when I search for "attention", it doesn't match.
When I index a regular String using the same analyzer it works fine. " l'attention " matches with "attention". The french elision filter works fine on regular Strings but not on attachment.
I hope someone will be able to help me.
If needed I can provide you a testcase that shows exactly the problem.

**Comment by javanna** [comment]
Hi @rodrigueLeopold please join us on [discuss.elastic.co](https://discuss.elastic.co/) so we can discuss your problem and help you. We use github issues for actual bugs or feature requests only.
