### ISSUE TITLE
Marvel 2.2.0 URL is not working 

### ISSUE THREAD

**Issue by devheroo** [elastic/elasticsearch#16621]
I am new to ElasticSearch, I just installed ES 2.2.0 and it is working fine.
I am trying to get Marvel to work but without any luck.
I installed it like this:
bin/plugin install license
bin/plugin install marvel-agent 

but when I try to browse: http://localhost:5601/app/marvel
I get an error message : Unable to connect
as if there is nothing is running on this url

this happened in both Windows and Ubuntu , using v 2.2.0 for both ES and Marvel.

please advise.

Thanks

**Comment by allenmchan** [comment]
Marvel is a kibana plugin now. You will need to install kibana and the marvel plugin in order to see the marvel stats. 
https://www.elastic.co/guide/en/marvel/current/installing-marvel.html

**Comment by devheroo** [comment]
Thanks so much for your help.
I will look into kibana installation.

**Comment by allenmchan** [comment]
Also please visit https://discuss.elastic.co/ for general help. There is a huge community there.
Github is for bugs and feature requests.
