### ISSUE TITLE
Problem __ToString() when populate, can help please? Is important

### ISSUE THREAD

**Issue by avito22** [elastic/elasticsearch#16635]
php app/console fos:elastica:populate  --index=en --type=article --batch-size=100....

Populating en/article, 8.1% (377000/4626642), 507 objects/s (RAM : current=205Mo peak=206Mo)
Populating en/article, 8.2% (377100/4626642), 511 objects/s (RAM : current=205Mo peak=206Mo)
PHP Fatal error:  Method MongoDBODMProxies\__CG__\Vavel\SearchBundle\Document\Article::__toString() must not throw an exception in /usr/share/nginx/html/search/vendor/friendsofsymfony/elastica-bundle/Transformer/ModelToElasticaAutoTransformer.php on line 0
PHP Stack trace:
PHP   1. {main}() /usr/share/nginx/html/search/app/console:0
PHP   2. Symfony\Component\Console\Application->run() /usr/share/nginx/html/search/app/console:27
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /usr/share/nginx/html/search/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124
PHP   4. Symfony\Component\Console\Application->doRun() /usr/share/nginx/html/search/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
PHP   5. Symfony\Component\Console\Application->doRunCommand() /usr/share/nginx/html/search/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:193
PHP   6. Symfony\Component\Console\Command\Command->run() /usr/share/nginx/html/search/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:894
PHP   7. FOS\ElasticaBundle\Command\PopulateCommand->execute() /usr/share/nginx/html/search/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:252
PHP   8. FOS\ElasticaBundle\Command\PopulateCommand->populateIndexType() /usr/share/nginx/html/search/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php:89
PHP   9. FOS\ElasticaBundle\Doctrine\AbstractProvider->populate() /usr/share/nginx/html/search/vendor/friendsofsymfony/elastica-bundle/Command/PopulateCommand.php:154
PHP  10. Vavel\SearchBundle\Elastica\ObjectPersister->insertMany() /usr/share/nginx/html/search/vendor/friendsofsymfony/elastica-bundle/Doctrine/AbstractProvider.php:79
PHP  11. FOS\ElasticaBundle\Persister\ObjectPersister->transformToElasticaDocument() /usr/share/nginx/html/search/src/Vavel/SearchBundle/Elastica/ObjectPersister.php:23
PHP  12. FOS\ElasticaBundle\Transformer\ModelToElasticaAutoTransformer->transform() /usr/share/nginx/html/search/vendor/friendsofsymfony/elastica-bundle/Persister/ObjectPersister.php:191
PHP  13. FOS\ElasticaBundle\Transformer\ModelToElasticaAutoTransformer->normalizeValue() /usr/share/nginx/html/search/vendor/friendsofsymfony/elastica-bundle/Transformer/ModelToElasticaAutoTransformer.php:92
PHP  14. FOS\ElasticaBundle\Transformer\ModelToElasticaAutoTransformer->FOS\ElasticaBundle\Transformer\{closure}() /usr/share/nginx/html/search/vendor/friendsofsymfony/elastica-bundle/Transformer/ModelToElasticaAutoTransformer.php:147

**Comment by dadoonet** [comment]
Please ask on discuss.elastic.co.

Sounds like a PHP error here. May be you should report your problem at https://github.com/FriendsOfSymfony/FOSElasticaBundle ?

**Comment by avito22** [comment]
Done
