### ISSUE TITLE
Alternate to aggregationContext.ensureScoreDocsInOrder()

### ISSUE THREAD

**Issue by rkalhans** [elastic/elasticsearch#16636]
I am writing a custom Aggregation. For my requirements, I need the doc Ids to be received in ascending order in the overridden collect() method. To ensure this we were using we were using `aggregationContext.ensureScoreDocsInOrder()` which seems to have been was removed in ES 2.X. How can I ensure the same behavior in 2.x

**Comment by clintongormley** [comment]
@jpountz @colings86 any ideas?

**Comment by jpountz** [comment]
Out of order collection has been removed in Lucene 5.0 / Elasticsearch 2.0. So you are now guaranteed to always collect documents in doc id order. See https://issues.apache.org/jira/browse/LUCENE-6179 for more information.
