### ISSUE TITLE
Support http_proxy environment variable for the plugin manager

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#16633]
As previously discussed in #11001, I think we should support `http_proxy` system variable which seems pretty standard in Linux world.

Should not be hard to implement in the plugin manager.

Unsure if we need that elsewhere though.

**Comment by rjernst** [comment]
I don't think the http_proxy environment variable is typical for java applications. Instead, you would add `-Dhttp.proxyHost` and `-Dhttp.proxyPort` to the java command (which can be done by setting JAVA_OPTS env var). Unfortunately this does not support authenticated proxies out of the box, but it looks fairly easy for us to add this by setting the default authenticator in eg the plugin cli main when we see `-Dhttp.proxyUser` and `-Dhttp.proxyPassword`.

**Comment by clintongormley** [comment]
> I don't think the http_proxy environment variable is typical for java applications. 

But it is typical for most linux applications.  Any downside to supporting it?

**Comment by rjernst** [comment]
Just the complexity. We would need to parse the env var in our bash scripts, and split it into those sysprops. Having users specify proxies with the sysprops seems a much simpler and less error prone path.

**Comment by hulu1522** [comment]
@rjernst Will this help?

```bash
#Automaticly import system proxy settings
if [ -n "$http_proxy" ] ; then
    echo $http_proxy | grep "@"
    if [ $? -eq 0 ]; then # If variable has username and password, its parse method different
        PROXY_HOST=$(echo $http_proxy | sed 's/http:\/\/.*@\(.*\):.*/\1/')
        PROXY_PORT=$(echo $http_proxy | sed 's/http:\/\/.*@.*:\(.*\)/\1/' | tr -d "/")
        USERNAME=$(echo $http_proxy | sed 's/http:\/\/\(.*\)@.*/\1/'|awk -F: '{print $1}')
        PASSWORD=$(echo $http_proxy | sed 's/http:\/\/\(.*\)@.*/\1/'|awk -F: '{print $2}')
    else # If it doesn't have username and password, its parse method this
        PROXY_HOST=$(echo $http_proxy | sed 's/http:\/\/\(.*\):.*/\1/')
        PROXY_PORT=$(echo $http_proxy | sed 's/http:\/\/.*:\(.*\)/\1/' | tr -d "/")
    fi
fi
```

**Comment by hulu1522** [comment]
Also... is there a change of supporting a 'quiet' (`-y, --yes`) flag which will allow us to answer yes to the plugin installation?  With Elasticsearch 2.2.0 and the Java security updates, plugins are asking me to agree before finishing installation.  This does not play nice with provisioning applications like Chef or Puppet and causes them to hang and timeout.

**Comment by jasontedor** [comment]
I'm with @rjernst here, we do not need to be managing this in our startup script when `http_proxy` and related environment variables are *not* standard in the Java world.

**Comment by rjernst** [comment]
> Also... is there a change of supporting a 'quiet' (-y, --yes) flag which will allow us to answer yes to the plugin installation?

There is a "batch" mode which skips confirmation that is enabled by default if there is no console (ie should work automatically from automation tools). If you want to force it, you can use the `-b` flag.

**Comment by jasontedor** [comment]
I think that the regexes [provided](https://github.com/elastic/elasticsearch/issues/16633#issuecomment-183737580) prove the point. But that's not even the beginning of it as there are other environment variables at play here such as `HTTPS_PROXY`, `ALL_PROXY`, and `NO_PROXY`. At the end of this we will just have added a lot of complexity to our startup script that is *much* easier for the end-user to manage.

**Comment by clintongormley** [comment]
Point taken :)

**Comment by jasontedor** [comment]
I closed this as I think we have consensus that we should not do this; the end-user can manage using the Java-specific properties. Please feel free to leave a comment if you have a good argument for why we should support this.

**Comment by rjernst** [comment]
We still need an issue to track adding support for basic auth, so we could reopen this for that purpose, or have another describing specifically what we need there in plugin cli.

**Comment by muelli** [comment]
FWIW: It may help to set `java.net.useSystemProxies` to true. At least that's what both [Oracle](https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html) and [OpenJDK](https://github.com/srisatish/openjdk/blob/6ffc2d1/jdk/src/share/lib/net.properties#L10-L18) advertise.

**Comment by hulu1522** [comment]
@muelli +1

That is a lot easier to implement and very little maintenance of the code.  Essentially:
```bash
if [ -n "$http_proxy" ] ; then
    $JAVA_OPTS = $JAVA_OPTS + " -Djava.net.useSystemProxies=true"
fi
```

**Comment by jasontedor** [comment]
@muelli: That property only applies on Windows and Gnome desktop systems. The same answer given before applies here too: the user can manage these proxy settings as they need for their specific system and proxy setup.

**Comment by clintongormley** [comment]
> We still need an issue to track adding support for basic auth, so we could reopen this for that purpose, or have another describing specifically what we need there in plugin cli.

@rjernst I've opened https://github.com/elastic/elasticsearch/issues/17046

**Comment by c33s** [comment]
it should be implemented simply because of the DX/UX (developer/user experience), simply because it then works out of the box and i don't have to get it running.

it is a better choice to solve this one time in the app by a few people, than having every proxy user ran into this problem and made him google and solve this problem for only himself.

even a lot of my windows app (even java apps) respect my `http_proxy` env variable.

please add support for this

**Comment by zicklag** [comment]
I am having issues right now because I need to build Elasticsearch in a Docker image and I need a way to build it behind a proxy. Almost every other tool I have used in my containers work just fine if I pass in the `http_proxy` environment variables. It is a lot cleaner than having to build my container specifically to allow building behind a proxy.

If you don't handle the environment variables in the tool, you make everybody who has to use the tool behind a proxy work to get it running. If you *do* handle it in the tool you fix the issue once and for all. I understand that it complicates a script, but IMHO it is better to fix it once instead of having your users work around the fact that it isn't supported.
