### ISSUE TITLE
query_string errors as Caused by: java.lang.NumberFormatException: For input string

### ISSUE THREAD

**Issue by harishkannarao** [elastic/elasticsearch#16638]
Hi Team,

I have got the following error when using simple_query_string with multiple fields containing numeric field.
Version: 2.2.0
OS: Windows

**Sample data:**
`curl -XPUT http://localhost:9200/blog/post/1 -d '{"id":123,"name":"name_123","relatedDocs":[{"id":12301,"name":"related1"},{"id":12302,"name":"related2"}]}'`

`curl -XPUT http://localhost:9200/blog/post/2 -d '{"id":124,"name":"name_124","relatedDocs":[{"id":12401,"name":"related2"},{"id":12402,"name":"related3"}]}'`

**Query String query:**
`curl -XGET http://localhost:9200/blog/post/_search?pretty=1 -d '{"query":{"query_string":{"default_operator":"AND","query":"12301 OR related2","fields":["relatedDocs.*","name"]}}}'`

**Error**
`{
    "error": {
        "root_cause": [
            {
                "type": "number_format_exception",
                "reason": "For input string: \"related2\""
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "blog",
                "node": "Ys1vmRrzT5SdSEYmfrEfYQ",
                "reason": {
                    "type": "number_format_exception",
                    "reason": "For input string: \"related2\""
                }
            }
        ]
    },
    "status": 400
}`

**Comment by clintongormley** [comment]
Hi @harishkannarao 

If you look at the [docs for the query string query](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/query-dsl-query-string-query.html), you'll find the `lenient` option.  Please ask questions like these on the forum instead: https://discuss.elastic.co/

**Comment by harishkannarao** [comment]
Hi @clintongormley , Thanks for your inputs, setting lenient parameter has solved the issue. In future I will post my question as suggested before raising an issue. Cheers..
