### ISSUE TITLE
[docs] Does index.codec best_compression still need to be experimental?

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#16644]
It's supported by core Lucene, so can we really call it an experimental feature?  If it is experimental and we were to remove it in the future, how would users access data stored using the best_compression codec?  This seems to be something we have to commit to one way or the other.

**Comment by clintongormley** [comment]
@jpountz what do you think?

**Comment by jpountz** [comment]
I wish we kept it experimental so that we could remove it some day if it becomes irrelevant. But maybe we should be more explicit about the fact that it will be supported in terms of bw compat even if it ever gets removed?

**Comment by clintongormley** [comment]
I think that, if it becomes irrelevant one day, then removing it would be an enhancement, no?  eg replacing facets with aggregations, or replacing binary doc values with numeric.  We're allowed to remove things that aren't experimental. I think your statement about bwc indicates that this is a feature we will continue to support as long as it makes sense.

**Comment by jasontedor** [comment]
Related Discourse post ["Use “best_compression” index setting in 2.1.1?"](https://discuss.elastic.co/t/use-best-compression-index-setting-in-2-1-1/40169).

**Comment by jpountz** [comment]
@clintongormley fine with me
