### ISSUE TITLE
Deprecate Mapper Attachment Plugin

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#16650]
Now that we have the ingest-attachment plugin (https://github.com/elastic/elasticsearch/pull/16490)  we should deprecate the mapper-attachment plugin.

The mapper-attachment plugin needs to remain deprecated for the life of 3.0, and can only be removed in 4.0.

**Comment by dadoonet** [comment]
+1. I can take it. It's basically just a question of documentation, right?
