### ISSUE TITLE
ES 2.2 Highlight is not working anymore

### ISSUE THREAD

**Issue by raffaeu** [elastic/elasticsearch#16652]
We worked on ES 1.4 for about 2 years, more or less. Deployed the product on the customer side and everyone was happy.

Now, we decided to upgrade to 2.2, recode all APIs changes and the highlight is not working anymore. It is not even returned.

Example of a query:

http://localhost:9200/index/Persons/_search
```
{
    "query": {
    "match": {
      "_all": "pippo"
    }
  },
    "highlight" : {
        "fields" : {
            "*" : {}
        }
    }
}
```

Results are returned but the Highlight node is gone, I tried all possible options and it seems that ES 2.2 doesn't return highlights at all but I look at the backlog and you didn't mention drastic changes under the highlight feature. 

```
{
  "took": 6,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": 0.83263576,
    "hits": [
      {
        "_index": "myindex",
        "_type": "Persons",
        "_id": "8701653d-261c-4c67-b59c-9b7aac2df3b6",
        "_score": 0.83263576,
        "_source": {
          "Full_name": "Disney, Pippo",
          "Email": "pippomproof@gmail.com"
        }
      }
    ]
  }
}
```

Am I doing something wrong or simply ES 2.2 removed highlights?

**Comment by raffaeu** [comment]
And of course highlight is mentioned in my mapping

```
{
  "myindex": {
    "mappings": {
      "Persons": {
        "properties": {
          "Email": {
            "type": "string"
          },
          "Full_name": {
            "type": "string"
          },
          "highlight": {
            "properties": {
              "fields": {
                "properties": {
                  "content": {
                    "type": "object"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by clintongormley** [comment]
Hi @raffaeu 

It's in the breaking changes docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_search_changes.html#_only_highlight_queried_fields

**Comment by raffaeu** [comment]
Thank you for pointing it out
