### ISSUE TITLE
Inner hits _source shouldn't use relative paths

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#16653]
In 2.0 we switched to requiring full paths whenever referring to a field.  However, the `_source` parameter for inner hits requires the relative path (even though the query requires a full path).

This is inconsistent and should be changed.

Example:

    PUT t
    {
      "mappings": {
        "t": {
          "properties": {
            "foo": {
              "type": "nested",
              "properties": {
                "bar": {
                  "type": "object",
                  "properties": {
                    "baz": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    
    PUT t/t/1
    {
      "foo": {
        "bar": {
          "baz": "xxx"
        }
      }
    }
    
    GET t/t/_search
    {
      "_source": false,
      "query": {
        "nested": {
          "path": "foo",
          "inner_hits": {
            "_source": "bar.*"
          },
          "query": {
            "match": {
              "foo.bar.baz": "xxx"
            }
          }
        }
      }
    }

**Comment by clintongormley** [comment]
Related to #16515

**Comment by martijnvg** [comment]
The reason that the _source is relative here, is that each inner hit only has part of the source (the json object) it is referring to. The fetch phase splits the source up in smaller source instances (json objects) before executing the fetch operations for the inner hits.

**Comment by clintongormley** [comment]
@martijnvg OK, I understand the why now, but its inconsistency with all other uses of path is annoying. Anything we can do to fake it?

**Comment by martijnvg** [comment]
@clintongormley Yes, I think we can fake it, by taking the provided `path` into account. So each time we do something with the nested source we remove the nested path prefix from the source field names.
