### ISSUE TITLE
elasticsearch-plugin script does not work on cygwin environment

### ISSUE THREAD

**Issue by jorgediaz-lr** [elastic/elasticsearch#16666]
elasticsearch-plugin script does not work on cygwin environment, following error is thrown because there are spaces at JAVA_HOME:
````
Jorge@JorgeDiaz /mnt/d/ElasticSearch/elasticsearch-2.1.1/bin
$ ./plugin install lang-javascript
./plugin: line 122: C:Program: command not found
````
Without spaces, another error is also thrown, because Java doesn't recognize cygwin paths:
````
Jorge@JorgeDiaz /mnt/d/ElasticSearch/elasticsearch-2.1.1/bin
$ ./plugin install lang-javascript
Error: Could not find or load main class org.elasticsearch.plugins.PluginManagerCliParser
````

*Solution:* Apply same path validations than *elasticsearch* script

**Comment by jorgediaz-lr** [comment]
@jasontedor is removing cygwin code at elasticsearch script at https://github.com/elastic/elasticsearch/pull/16871 so I am closing this issue.

If anybody needs to patch scripts for cygwin, see following changes:
  - elasticsearch-plugin: https://github.com/jorgediaz-lr/elasticsearch/commit/6d381c51644cc12f52fe73bca57c3b3a06aaa39c
  - elasticsearch: https://github.com/elastic/elasticsearch/commit/58bcd7f8e71a282d534f570a39f0c05270568935

**Comment by jasontedor** [comment]
I know that this is not the outcome that you wanted, but thank you for your understanding @jorgediaz-lr.
