### ISSUE TITLE
top-level inner_hits syntax confusing

### ISSUE THREAD

**Issue by rpedela** [elastic/elasticsearch#16664]
I was very confused by the top-level `inner_hits` syntax. I spent an entire day tracking down why some search results would return inner hits and others didn't even though they should have. What was my confusion?

Here was the original request I used which would return inner hits some of the time.

``` js
{
    query: {
        has_child: {
            type: 'child_docs',
            score_mode: 'max',
            query: {
                bool: {
                    should: [
                        {
                            query_string: { query: 'google' }
                        },
                        {
                            has_child: {
                                type: 'grand_child_docs',
                                score_mode: 'max',
                                query: { query_string: { query: 'google' } }
                            }
                        }
                    ]
                }
            }
        }
    },
    inner_hits: {
        child_documents: {
            type: {
                child_docs: {
                    query: { 
                        query_string: { query: 'google' }
                    },
                    inner_hits: {
                        grand_child_documents: {
                            type: {
                                grand_child_docs: {
                                    query: {
                                        query_string: { query: 'google' }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

Here is the request with the correct syntax where inner hits were always returned.

``` js
{
    query: {
        has_child: {
            type: 'child_docs',
            score_mode: 'max',
            query: {
                bool: {
                    should: [
                        {
                            query_string: { query: 'google' }
                        },
                        {
                            has_child: {
                                type: 'grand_child_docs',
                                score_mode: 'max',
                                query: {
                                    query_string: { query: 'google' }
                                }
                            }
                        }
                    ]
                }
            }
        }
    },
    inner_hits: {
        child_documents: {
            type: {
                child_docs: {
                    query: {
                        bool: {
                            should: [
                                {
                                    query_string: { query: 'google' }
                                },
                                {
                                    has_child: {
                                        type: 'grand_child_docs',
                                        score_mode: 'max',
                                        query: {
                                            query_string: { query: 'google' }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    inner_hits: {
                        grand_child_documents: {
                            type: {
                                grand_child_docs: {
                                    query: {
                                        query_string: { query: 'google' }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

If you notice, the difference is the child query in the `inner_hits` section. By repeating the original query in the `inner_hits` section for the child, everything works correctly. However I did not do that initially. Here was my thought process: 
1. Since the server already knows the search results, I don't have to repeat the query. Hmm that didn't give me the correct results.
2. I see `query` mentioned in the  [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html) and it says it must be specified otherwise all inner docs are returned.
3. I assume I need to define the child's query and grandchild's query separately similar to how nested `inner_hits` works. That is what the first example does. It never returns inner hits that are in grandchildren only.
4. Start trying random things because I don't know what I am missing. Eventually try copying the original query to the child's `inner_hits` section and that finally works.

I think the root of the confusion is that `inner_hits` is not consistent with other parts of the ES syntax. It doesn't work like the nested `inner_hits` nor does it work like other things like highlighting. By default, the highlighters assume you want to highlight based on the original query. They only highlight using a different query if you override it.

I think two things would have helped me:
1. Make it clear you need to repeat the original query in the `inner_hits` section.
2. Make the default to use the original query rather than returning all inner hit docs. Then have some sort of special field/value to say you want all the inner hit docs. This would also make more sense given the name "inner_hits" which I would assume to mean "inner search hits".

**Comment by talevy** [comment]
This feature request is an interesting idea but since its opening we have not seen enough feedback that it is a feature we should pursue. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).
