### ISSUE TITLE
Adding a Index & Filter not working

### ISSUE THREAD

**Issue by matiasdecarli** [elastic/elasticsearch#16663]
Hi guys, im trying this

```
curl -XPOST localhost:9200/_aliases -d '{
    "actions": [{
        "add": {
            "index": "common",
            "alias": "alias_test",
            "filter": {"term": {"customer_id": 1}},
            "routing": "alias_test"
        }
    }]
}'
```

And getting this result 

```
$ curl -XGET 'localhost:9200/common/_alias/*?pretty'

{
  "common" : {
    "aliases" : {
      "alias_test" : {
        "index_routing" : "alias_test",
        "search_routing" : "alias_test"
      },
      "dolores98141" : {
        "filter" : {
          "term" : {
            "orgId" : "dolores98141"
          }
        },
        "index_routing" : "dolores98141",
        "search_routing" : "dolores98141"
      }
    }
  }
}
```

Where `dolores98141` was a previously created index (with a filter).

The issue here: I'm not seeing any filter associated with the new `alias_test` index. Is this a bug or am I using the API in the wrong way? 

Apparently the `filter` is only added at index creation and not when we are editing an alias

Thans in advance

Im using `elasticsearch:2.2.0`

**Comment by jasontedor** [comment]
Duplicates #16547, closed by #16553

**Comment by matiasdecarli** [comment]
Thanks @jasontedor :clap:

**Comment by matiasdecarli** [comment]
As a workaround, and for further reference: Im using the [putAlias](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference-2-2.html#api-indices-putalias-2-2) method

**Comment by jasontedor** [comment]
> As a workaround, and for further reference: Im using the [putAlias](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference-2-2.html#api-indices-putalias-2-2) method

@matiasdecarli That will work; thanks for posting the workaround for others here until the next patch release includes the fix.
