### ISSUE TITLE
ES2.2 Indexing latency is slower than ES1.7.4

### ISSUE THREAD

**Issue by sombut** [elastic/elasticsearch#16668]
Hi,

I have performed a quick test on indexing latency comparing between ES2.2 and ES1.7.4 on the same spec of hardware (16GB of JVM on a single node on both cluster with no replica)

Posting the data below in ES2.2 that always took > 20ms and sometime jump to 600ms to index data but when switch to ES1.7.4 it took < 5 ms

Are you able to replicate this in your lab? 

I might be missing something so any suggestions in the configuration below are welcome.

[elasticsearch.yml.zip](https://github.com/elastic/elasticsearch/files/130552/elasticsearch.yml.zip)

Regards,
Sombut
```
POST /_bulk
{"index":{"_index":"logstash-2015.10.17","_type":"roles","_id":"1"}}
{"role":"ADMIN","permission":[{"http_method":"*","template":"/**"}]}
```

ES2.2
```
{
  "took": 61,
  "errors": false,
  "items": [
    {
      "index": {
        "_index": "logstash-2015.10.17",
        "_type": "roles",
        "_id": "1",
        "_version": 104,
        "_shards": {
          "total": 2,
          "successful": 2,
          "failed": 0
        },
        "status": 200
      }
    }
  ]
}
```

ES1.7.4
```
{
  "took": 2,
  "errors": false,
  "items": [
    {
      "index": {
        "_index": "logstash-2015.10.17",
        "_type": "roles",
        "_id": "1",
        "_version": 14,
        "status": 200
      }
    }
  ]
}
```

**Comment by dadoonet** [comment]
There are some differences between 2.x and 1.x indeed. Doc values are enabled by default. The transaction log is fsync'ed after every request.
That's probably the reason you have differences.

Note that your test should have a lot more data to really measure what the real cost is.
Also, those differences play not a great role at search time and memory wise.

Please ask questions like this on discuss.elastic.co.

**Comment by sombut** [comment]
Thanks @dadoonet. I'll  put my question on discussion page instead.
