### ISSUE TITLE
ClusterHealthResponse is always red

### ISSUE THREAD

**Issue by hakdogan** [elastic/elasticsearch#16678]
I came across an interesting situation while testing some scenarios with Java API version 2.2.0

ClusterHealthResponse returns always red when I want to get the status of the cluster(immediately after the node starts) that has one or more indices but If you get the status of the cluster after creating an index the state of the cluster does not return red in the next request even if execute immediately after the node starts.

Please look at the [simple gist.](https://gist.github.com/hakdogan/e541e52a96b0e16ea8f9)

When you run this standalone application sequentially you will get the following log:

> 2016-02-15 18:18:11,150 [main] INFO  com.kodcu.JavaAPIMain - *************\* GREEN **************
> 2016-02-15 18:18:11,153 [main] INFO  com.kodcu.JavaAPIMain - Index does not exist. Creating...
> 
> 2016-02-15 18:22:18,500 [main] INFO  com.kodcu.JavaAPIMain - *************\* RED **************
> 2016-02-15 18:22:18,502 [main] INFO  com.kodcu.JavaAPIMain - Index already exists.

Afterwards, delete the data path directory and comment the line 67 and then run this code. The result will be as below:

> 2016-02-15 18:28:43,049 [main] INFO  com.kodcu.JavaAPIMain - *************\* GREEN **************
> 2016-02-15 18:28:43,055 [main] INFO  com.kodcu.JavaAPIMain - Index does not exist. Creating...
> 2016-02-15 18:28:43,910 [main] INFO  com.kodcu.JavaAPIMain - *************\* YELLOW **************
> 
> 2016-02-15 18:29:28,472 [main] INFO  com.kodcu.JavaAPIMain - *************\* YELLOW **************
> 2016-02-15 18:29:28,475 [main] INFO  com.kodcu.JavaAPIMain - Index already exists.

What could be the source of this inconsistency?

**Comment by colings86** [comment]
Are you still seeing this issue on you Elasticsearch cluster? If so, do you know the steps to reproduce the bug?

**Comment by hakdogan** [comment]
Hi.

> Are you still seeing this issue on you Elasticsearch cluster?

Yes in the same version`(2.2.0)`

> If so, do you know the steps to reproduce the bug?

Please run the above code I'm sharing: [code](https://gist.github.com/hakdogan/e541e52a96b0e16ea8f9)

If you run the standalone application sequentially, you will always see red the state of the cluster after the second time. However, for example, you will see the green the state when you are refresh to the created index after creating.

**Comment by abeyad** [comment]
In 2.x and prior, when an index was initially created, the cluster would temporarily go `RED` while shards are being allocated and created.  Once all the primary shards have been created on their respective nodes for the newly created index, then the cluster moved to `YELLOW`.  We changed this behavior in the 5.x series so that when an index is created, instead of temporarily going to `RED` while its primary shards are being allocated, we move straight to the `YELLOW` state for that index.

**Comment by hakdogan** [comment]
@abeyad Thanks for the explanation

**Comment by colings86** [comment]
Sounds like this has been resolved. If I have that wrong please reopen
