### ISSUE TITLE
Update API and versions

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#16671]
From https://github.com/elastic/elasticsearch/issues/16438:

I think we can improve things here by making request validation stricter. IMO the following do not make sense and should be rejected:
- The `version` on an update request is a syntactic sugar for get of a specific version, doc merge and a version index. We should reject requests with both upsert and a version.
- If the upsert _index request_ is versioned, we should reject the op. As Clint said, it's not possible through the rest layer, but Java clients can do so.

**Comment by lewischen1123** [comment]
i want to pick it up and have a try thx

**Comment by nik9000** [comment]
@kunal642 wrote the validation which really closed this issue. I just pushed some breaking changes documentation to mark the issues closed.

@clintongormley, I don't think it is worth pushing a "Deprecated version in upsert requests" change to 5.x. What do you think?

**Comment by clintongormley** [comment]
@nik9000 no i don't think that's required
