### ISSUE TITLE
Observing 6x slowdown while indexing documents on upgrading from 1.7 to 2.2

### ISSUE THREAD

**Issue by sacheendra** [elastic/elasticsearch#16681]
The slowdown occurred while doing a benchmark of index rate of documents with a single string field. 

example doc: '{ "message": "this is a random sentence" }'

The benchmark is for a single node(AWS EC2 c4.2xlarge). The index has 1 shard and no replicas. The mapping is generated automatically. A 250GB general purpose SSD EBS volume was used for data. 

On 1.7, I observed an index rate of 2.2k/sec, but on 2.2 I just see a rate of around 360/sec. 

The code used for the benchmark is here: [https://github.com/sacheendra/es_benchmark](https://github.com/sacheendra/es_benchmark)
The master branch is for 2.2 and the 1.7 branch is for 1.7. The benchmark script was run on a separate machine. (EC2 c3.8xlarge)

Elasticsearch was deployed using docker with data volume mapped to disk. 

The CPU usage is around 10%. About 5GB/250GB is used after an 8hr run. The RAM usage is as seen in the chart below. 

<img width="857" alt="screen shot 2016-02-15 at 11 51 47 pm" src="https://cloud.githubusercontent.com/assets/5353969/13057037/7b7689b6-d43f-11e5-9ad2-e872ac936cb7.png">

What could be the reason for this slowdown? 

Also any idea on why the memory usage id increasing so fast?

**Comment by s1monw** [comment]
this is very likely the same as https://github.com/elastic/elasticsearch/issues/16676

**Comment by sacheendra** [comment]
Thank you, that seems to be the change causing the slowdown. Didn't know that es fsynced on every request. Using bulk requests, performance looks good.
