### ISSUE TITLE
BUG: CORS only works with valid User-Agent

### ISSUE THREAD

**Issue by qoomon** [elastic/elasticsearch#16689]
CORS only works with valid User-Agent. 
This is kind of a problem for special/unknown Browser Types.
![image](https://cloud.githubusercontent.com/assets/3963394/13074653/3bb4bb06-d4a6-11e5-988e-e633daf736ed.png)

**Comment by jlroettger** [comment]
I just spent several hours troubleshooting why I couldn't get CORS to work correctly behind AWS CloudFront. This bug was the problem.

Turns out "Amazon CloudFront" is not a valid User-Agent string when it comes to Elasticsearch wanting to respond with an "Access-Control-Allow-Origin" header. Dang :(

**Comment by nikoncode** [comment]
Not repeatable in 5.0.0-alpha2.

<pre>
$ curl -H "User-Agent: Mozilla" -H "Origin: http://example.com" -i localhost:9200
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=UTF-8
Content-Length: 288

{
  "name" : "Arsenic",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "5.0.0-alpha2",
    "build_hash" : "c2c4ed3",
    "build_date" : "2016-04-27T19:55:30.279Z",
    "build_snapshot" : true,
    "lucene_version" : "6.0.0"
  },
  "tagline" : "You Know, for Search"
}

$ curl -H "Origin: http://example.com" -i localhost:9200
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=UTF-8
Content-Length: 288

{
  "name" : "Arsenic",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "5.0.0-alpha2",
    "build_hash" : "c2c4ed3",
    "build_date" : "2016-04-27T19:55:30.279Z",
    "build_snapshot" : true,
    "lucene_version" : "6.0.0"
  },
  "tagline" : "You Know, for Search"
}
</pre>

**Comment by qoomon** [comment]
I used version 2.x
Looking forward for 5.x release

**Comment by nikoncode** [comment]
Not reproduces in 2.3.2 release. Please update to void described problems.
<pre>
$ curl -H "User-Agent: Mozilla" -H "Origin: http://example.com" -i localhost:9200
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=UTF-8
Content-Length: 317

{
  "name" : "Enforcer",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.2",
    "build_hash" : "b9e4a6acad4008027e4038f6abed7f7dba346f94",
    "build_timestamp" : "2016-04-21T16:03:47Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}

$ curl -H "Origin: http://example.com" -i localhost:9200
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=UTF-8
Content-Length: 317

{
  "name" : "Enforcer",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.2",
    "build_hash" : "b9e4a6acad4008027e4038f6abed7f7dba346f94",
    "build_timestamp" : "2016-04-21T16:03:47Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
</pre>

**Comment by qoomon** [comment]
Was 1.7.1 sorry my bad
