### ISSUE TITLE
cloud-aws plugin not working and seem to be an older version 

### ISSUE THREAD

**Issue by Gmanweb** [elastic/elasticsearch#16680]
I have Elasticsearch 1.7.x running with aws cloud plugin 2.7.1 in the Elk Stack, everything works fine. I wanted to upgrade so I decided to put it on a new instance to make sure all is working ok. I cannot seem to get it working and the version of the cloud-aws plugin seem to be older than 2.7.1? I would have though keeping with [convention it would be higher](https://github.com/elastic/elasticsearch-cloud-aws). 

the plugin doesn't seem to work can you check if I am doing something wrong, here is the set up commands for each.

Set-up for Elasticsearch1.7.2
```
sudo su
yum update -y && cd /root
wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.7.2.noarch.rpm
yum install elasticsearch-1.7.2.noarch.rpm -y
rm -f elasticsearch-1.7.2.noarch.rpm
cd /usr/share/elasticsearch/
./bin/plugin -install mobz/elasticsearch-head
./bin/plugin -install lukas-vlcek/bigdesk
./bin/plugin install elasticsearch/elasticsearch-cloud-aws/2.7.1
cd /etc/elasticsearch
cp elasticsearch.yml elasticsearch.yml.bak
nano elasticsearch.yml
```
Set-up for Elasticsearch 2.2.0
```
sudo su
yum update -y
cd /root
wget  https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/rpm/elasticsearch/2.2.0/elasticsearch-2.2.0.rpm
yum install elasticsearch-2.2.0.rpm -y
rm -f elasticsearch-2.2.0.rpm
cd /usr/share/elasticsearch/
bin/plugin install mobz/elasticsearch-head
bin/plugin install lukas-vlcek/Bigdesk
bin/plugin install cloud-aws 
cd /etc/elasticsearch
cp elasticsearch.yml elasticsearch.yml.bak
nano elasticsearch.yml
```

see a [screen shot](https://www.dropbox.com/s/b1tlejuc8tnaugl/cloud-aws.jpg?dl=0) from installing ànd the difference in the version for the cloud-aws plugins

I had to revert back to the working Elasticsearch 1.7.2 with the `elasticsearch-cloud-aws/2.7.1` but would love to know if i'm doing something wrong or this is a bug.

G

**Comment by dadoonet** [comment]
It's not an older version. We changed the Maven groupId.

**Comment by clintongormley** [comment]
The groupId is now `org.elasticsearch.plugin`
