### ISSUE TITLE
make EngineConfig.INACTIVE_SHARD_INDEXING_BUFFER configurable for ES-1.7.x

### ISSUE THREAD

**Issue by Dieken** [elastic/elasticsearch#16688]
In my use case, I setup hourly index for ELK, unluckily the logs come from everywhere and don't have consistent pace,  often hours ago old logs suddenly comes in, that leads to big trouble due to 500kb index buffer size for inactive shard.

For example, my machines have 32 CPUs,  "index.concurrency" is max(8, 0.65*cpus), that's 20 Lucene thread states, also means 20 concurrent segment flushes.  And "indices.memory.interval" is 30s by default (this is 5s in ES-2.x),  so if a single shard has 10MB/s documents suddenly being ingested, that will produce a lot of (500kb/20)=25kb tiny segments:

30s / (500kb / 10240 kb) * 20 concurrency = 12288 segments.

The huge amount of small segments will trigger many merging, exceed the max_merge_count limit, thus indexing is throttled, unluckily this throttling is 100% stop, not  base on some probability,  then ES data node will accumulate a lot of IndexRequest or ReplicatedIndexRequest, the ES gateway also accumulates a lot of Request,  they will run out of memory and just hang,  the ES cluster will be down.

If I pre-create ES indices for future hours, this issue also kicks in,  the inactive future ES index will suddenly become active and produce a lot of segment,  but this scenario is less critical than old logs suddenly goes into old indices because the volume of new log usually gradually increases.

I made a rude patch to increase INACTIVE_SHARD_INDEXING_BUFFER to 120MB (I set min_shard_index_buffer_size to 128MB),   it works well for me, I don't worry the memory waste because Lucene allocates  memory lazily.

I also checked ES-2.x code,  it totally removes the logic of inactive buffer size and doesn't average total index buffer among active shards,  this is much better, but I'm not sure whether it's easy to port that change to ES-1.7.x.

My rude patch against ES-1.7.5, just FYI:
```
diff --git a/src/main/java/org/elasticsearch/index/engine/EngineConfig.java b/src/main/java/org/elasticsearch/index/engine/EngineConfig.java
index d907082..9504a89 100644
--- a/src/main/java/org/elasticsearch/index/engine/EngineConfig.java
+++ b/src/main/java/org/elasticsearch/index/engine/EngineConfig.java
@@ -138,11 +138,15 @@ public final class EngineConfig {
      */
     public static final String INDEX_VERSION_MAP_SIZE = "index.version_map_size";
 
+    /**
+     * The indexing buffer size reserved for inactive shard.
+     */
+    public static final String INDEX_INACTIVE_SHARD_INDEX_BUFFER_SIZE = "index.inactive_shard_index_buffer_size";
 
     public static final TimeValue DEFAULT_REFRESH_INTERVAL = new TimeValue(1, TimeUnit.SECONDS);
     public static final TimeValue DEFAULT_GC_DELETES = TimeValue.timeValueSeconds(60);
     public static final ByteSizeValue DEFAUTL_INDEX_BUFFER_SIZE = new ByteSizeValue(64, ByteSizeUnit.MB);
-    public static final ByteSizeValue INACTIVE_SHARD_INDEXING_BUFFER = ByteSizeValue.parseBytesSizeValue("500kb");
+    public static ByteSizeValue INACTIVE_SHARD_INDEXING_BUFFER = ByteSizeValue.parseBytesSizeValue("500kb");
 
     public static final String DEFAULT_VERSION_MAP_SIZE = "25%";
 
@@ -182,6 +186,7 @@ public final class EngineConfig {
         failOnMergeFailure = indexSettings.getAsBoolean(INDEX_FAIL_ON_MERGE_FAILURE_SETTING, true);
         gcDeletesInMillis = indexSettings.getAsTime(INDEX_GC_DELETES_SETTING, EngineConfig.DEFAULT_GC_DELETES).millis();
         versionMapSizeSetting = indexSettings.get(INDEX_VERSION_MAP_SIZE, DEFAULT_VERSION_MAP_SIZE);
+        INACTIVE_SHARD_INDEXING_BUFFER = indexSettings.getAsBytesSize(INDEX_INACTIVE_SHARD_INDEX_BUFFER_SIZE, ByteSizeValue.parseBytesSizeValue("500kb"));
         updateVersionMapSize();
     }
 
diff --git a/src/main/java/org/elasticsearch/index/shard/IndexShard.java b/src/main/java/org/elasticsearch/index/shard/IndexShard.java
index 4ff1b06..27354fa 100644
--- a/src/main/java/org/elasticsearch/index/shard/IndexShard.java
+++ b/src/main/java/org/elasticsearch/index/shard/IndexShard.java
@@ -1073,7 +1073,7 @@ public class IndexShard extends AbstractIndexShardComponent {
             // its inactive, make sure we do a refresh / full IW flush in this case, since the memory
             // changes only after a "data" change has happened to the writer
             // the index writer lazily allocates memory and a refresh will clean it all up.
-            if (shardIndexingBufferSize == EngineConfig.INACTIVE_SHARD_INDEXING_BUFFER && preValue != EngineConfig.INACTIVE_SHARD_INDEXING_BUFFER) {
+            if (shardIndexingBufferSize.equals(EngineConfig.INACTIVE_SHARD_INDEXING_BUFFER) && ! preValue.equals(EngineConfig.INACTIVE_SHARD_INDEXING_BUFFER)) {
                 logger.debug("updating index_buffer_size from [{}] to (inactive) [{}]", preValue, shardIndexingBufferSize);
                 try {
                     refresh("update index buffer");
```

**Comment by Dieken** [comment]
During the investigation,  I found ES-1.7 doesn't throttle request according to response,  and ES strangely has many net I/O threads:  
* "http_server_worker" thread pool (2 * cpus threads)
* "http_server_worker.default" thread pool(2 * cpus threads)
* "transport_client_worker" thread pool (2* cpus threads)
* "transport_client_worker.default" thread pool (2 * cpus threads)

I explicitly set "http.port" and "transport.tcp.port" in  elasticsearch.yml,  no idea why ES-1.7 creates two thread pool for http and transport.

If ES is blocked or just slow on indexing,  those I/O threads will still crazily receive requests and lead to OOM (Notice replicated index request doesn't follow the bulk.queue size limit),  this makes me feel ES is a little fragile.

**Comment by clintongormley** [comment]
Hi @Dieken 

While we're still releasing bug fixes for 1.7, this particular change feels way too big to backport to a stable branch which is supposed to see maintenance releases only.

I would suggest that it is time to upgrade.

I'll leave this open for now in case anybody else disagrees.  @mikemccand ?

**Comment by mikemccand** [comment]
Thanks @Dieken ... what you hit is actually a bug (that it takes up to 30s for ES to increase the indexing buffer off of INACTIVE).  It was fixed in 2.x releases in #13918.

Also, in 3.0, we've completely changed how we manage indexing buffer heap, so it's a single shared pool across all shards: #14121.

+1 to upgrade.

**Comment by Dieken** [comment]
Yes, we have just upgraded to 2.2.0 yesterday,  maybe it's worth to document this issue in 1.7.x reference manual.

The new strategy in 3.0 looks perfect,  it's a great pity not in 2.x  :-)

Thank you for the information!

**Comment by clintongormley** [comment]
Looks like nothing left to do here.  Closing
