### ISSUE TITLE
Path not working when using Context Suggester with Geo

### ISSUE THREAD

**Issue by mikemad** [elastic/elasticsearch#16694]
// CREATE INDEX
curl -X PUT -d '{
    "number_of_shards" : 1,
    "number_of_replicas" : 1
}' "http://localhost:9200/services"

// MAPPING
curl -X PUT -d '{
  "service": {
    "properties": {
      "name": {
        "type": "string",
        "index": "not_analyzed"
      },
      "pin": {
        "type":"geo_point"
      },
      "currentstatus": {
        "type": "string",
        "index": "not_analyzed"
      },
      "suggest_field": {
        "type": "completion",
        "context": {
          "status": {
            "type": "category",
            "default": "bad",
            "path": "currentstatus"  
          },
          "location": {
            "type": "geo",
            "precision": "100km",
            "neighbors": true,
            "path":"pin",
            "default": {
                "lat": 0.0,
                "lon": 0.0
            }
          }
        }
      }
    }
  }
}' "http://localhost:9200/services/service/_mapping"

// Insert record
curl -X PUT -d '{
  "name": "knapsack",
  "pin": {
      "lat": 47.620499,
      "lon": -122.350876
  },
  "currentstatus" : "good",
  "suggest_field": {
    "input": [
      "knacksack",
      "backpack",
      "daypack"
    ]
  }
}' "http://localhost:9200/services/service/1"

// Suggest
curl -X POST -d '{
  "suggest": {
    "text": "k",
    "completion": {
      "field": "suggest_field",
      "size": 10,
      "context": {
        "location": {
            "lat": 47.482880,
            "lon": -122.217064,
            "precision":"100km"
        },
        "status": "good"
      }
    }
  }
}' "http://localhost:9200/services/_suggest"

You'd expect that we'd get a suggestion here. When I do the category completion alone, it works correctly but it doesn't seem to get the lat/lon from the path but rather always uses the default. I don't want to have to duplicate data and this is not working as expected. What is going wrong here?

**Comment by clintongormley** [comment]
Hi @mikemad 

I'm afraid the current context suggester has a long list of bugs.  It has been completely rewritten in 5.0 and I've checked that it works correctly there. Sorry we're not going to fix the existing suggester, but it'd be a bit like putting lipstick on a pig :)

**Comment by mikemad** [comment]
LOL. At least getting an answer is better than not knowing if I was going crazy!!! Thanks!

**Comment by vandanachadha** [comment]
I am using ES version 5.5.2 and for me also the geo context is not working. 
Details are added to:
https://github.com/elastic/elasticsearch/issues/32202

Please help.
