### ISSUE TITLE
s3 support for ceph radosgw

### ISSUE THREAD

**Issue by bilsch** [elastic/elasticsearch#16693]
I would like to see the s3 archive support the s3 as implemented in ceph / radosgw.

Not sure what all is involved however I was not able to make it work

**Comment by dadoonet** [comment]
I'm unsure if we can have it but may be you could tell more about the error you are seeing.

**Comment by clintongormley** [comment]
> Not sure what all is involved however I was not able to make it work

@bilsch neither am I.  You want to start by doing some research?

**Comment by bilsch** [comment]
@clintongormley sorry for going quiet there. Yes I do want to help out and dig in wrt research. I will look in to a few things and at least collect notes of what is / is not working and at least attempt to understand why. I'm less strong on dev sides of things but reading APIs and such to get a general understanding should be within my ability.

**Comment by bilsch** [comment]
For reference, radosgw [api](http://docs.ceph.com/docs/master/radosgw/s3/). I'll have to figure out how to dissect the packets to see what is going on. I'll get the plugin set up and dump the debug output and post that back Probably later today, maybe tomorrow.

**Comment by bilsch** [comment]
Request
```
curl -XPUT -u admin 'https://elshost.foo.net:9200/_snapshot/s3_repository' -d '{
    "type": "s3",
    "settings": {
        "bucket": "foo_bucket",
        "endpoint": "https://radosgw.foo.net/foo_bucket",
        "access_key": "xxxx",
        "secret_key": "xxxx",
        "compress": true
    }
}' | python -m json.tool
```

Response

```
Enter host password for user 'admin':
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1144  100   858  100   286     98     32  0:00:08  0:00:08 --:--:--   125
{
    "error": {
        "caused_by": {
            "caused_by": {
                "caused_by": {
                    "reason": "foo_bucket.xxxx.foo",
                    "type": "unknown_host_exception"
                },
                "reason": "Unable to execute HTTP request: foo_bucket.xxxx.foo",
                "type": "amazon_client_exception"
            },
            "reason": "Guice creation errors:\n\n1) Error injecting constructor, com.amazonaws.AmazonClientException: Unable to execute HTTP request: foo_bucket.xxxx.foo\n  at org.elasticsearch.repositories.s3.S3Repository.<init>(Unknown Source)\n  while locating org.elasticsearch.repositories.s3.S3Repository\n  while locating org.elasticsearch.repositories.Repository\n\n1 error",
            "type": "creation_exception"
        },
        "reason": "[s3_repository] failed to create repository",
        "root_cause": [
            {
                "reason": "[s3_repository] failed to create repository",
                "type": "repository_exception"
            }
        ],
        "type": "repository_exception"
    },
    "status": 500
}
```

We are looking to use [path style](http://docs.aws.amazon.com/AmazonS3/latest/API/APIRest.html) s3 resources. It looks like the s3 client is trying to use bucket named host aliasing. Is there a toggle option to honor the endpoint path?

**Comment by bilsch** [comment]
Also, reference the ceph [bucket and hostname](http://docs.ceph.com/docs/master/radosgw/s3/commons/#bucket-and-host-name)

**Comment by bilsch** [comment]
Looking over the java docs, [S3ClientOptions](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/S3ClientOptions.html) - setting `withPathStyleAccess` to true should do it. I believe somewhere in [onModule ](https://github.com/elastic/elasticsearch/blob/master/plugins/repository-s3/src/main/java/org/elasticsearch/plugin/repository/s3/S3RepositoryPlugin.java#L92) but exposed through a config toggle somewhere/somehow.

Hope this helps - not sure what else I can research here

**Comment by tlrx** [comment]
This feature request is interesting but since its opening we have not seen enough feedback that it is a feature we should pursue. We prefer to close this issue as a clear indication that we are not going to work on at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).
