### ISSUE TITLE
Separate logging streams for tribe node clients

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#16696]
Suggestion from the field.  If a tribe node is connected to many clusters, it will be helpful to separate the tribe node client logging for each cluster into different files. That will help isolate issues not having to review one large file.

**Comment by clintongormley** [comment]
Hmm I'm not sure this makes sense.  Separating the logging then means you have to mentally combine perhaps several files to see things that were happening across several clusters at the same time... Perhaps we just need to make these logs more easily grep'able.

**Comment by javanna** [comment]
Tribe node has been deprecated and removed, closing.
