### ISSUE TITLE
Running multiple instances as a service on one linux server?

### ISSUE THREAD

**Issue by zhuqunzhou** [elastic/elasticsearch#16697]
Before `es 2.0`,i can use `servicewrapper` to run an instances as a service.But now,`servicewrapper` don't support `es 2.*`

I want to run multiple instances on one server,so i can't use `RPM package`.And i want to set `java opts` on each instance.

**Comment by nik9000** [comment]
> I want to run multiple instances on one server,so i can't use RPM package.And i want to set java opts on each instance

If you want to run multiple instances on one server you'll either have to use RPM and hack together a second init script/systemd descriptor or use the TAR distribution and build your own init scripts. The rpm and deb don't support more than one Elasticsearch instance per server, sadly.
