### ISSUE TITLE
Template mapping Default index Analyzer not respected

### ISSUE THREAD

**Issue by xavierfacq** [elastic/elasticsearch#16699]
Hi,

I'll try to explain as well as possible the problem.
Since I migrate from 1.7.5 to 2.2.0, I have troubles with default analyzers.

1°/ I have template mapping with analysis : 

```
                "human": {
                    "type": "custom",
                    "tokenizer": "standard",
                    "filter": [ "lowercase", "asciifolding", "bypath-words" ]
                },
                "default": {
                    "type": "custom",
                    "tokenizer": "standard",
                    "filter": [ "lowercase", "asciifolding", "bypath-words", "bypath-elision", "bypath-synonyms" ]
                },

```

Some fields have the "human" analyzer specified, else others have the "default" one. No problem here. Everything works well.

2°/ Before the migration in 2.2.0 I had queries like this : 

`QueryBuilders.matchQuery(fieldname, s).operator(Operator.AND).analyzer("default_search");
`

As specifications changed, I modifed analyzer's names to "default" , so in my code have now : 

`QueryBuilders.matchQuery(fieldname, s).operator(Operator.AND).analyzer("default");
`

3°/ Here is the problem !

The .analyzer("default") produce this json : 

```
          "match": {
            "roles_hierarchy": {
              "query": "assistante",
              "type": "boolean",
              "operator": "AND"
              "analyzer": "default"
            }
          }

```

But the query **do not use my "default" analyzer**, it seems to use another "default" one, because I don't have the good analyzing. If I remove the "analyzer": "default", it's OK, the result is good and the term "assistante" is well analyzed.

So I have to remove .analyzer("default") every where in my code because there is a big side effect. 
I think there is a little problem here.

Xavier

**Comment by clintongormley** [comment]
Hi @xavierfacq 

The `default_index` setting has been removed. Now we have `default` and `default_search` which, if set, overrides the `default` at search time.

You don't actually have to specify these analyzers - they are used as defaults. I've tested out various configurations and all seem to work as expected.  Could you provide a simple recreation (preferably with curl) that demonstrates the problem?

**Comment by xavierfacq** [comment]
Hi @clintongormley

I tried to reproduce many times on a fresh new instance, but I can't have the problem again. Maybe there was something misconfigured after the migration from 1.7.x to 2.x.

You can close this issue.

**Comment by clintongormley** [comment]
thanks @xavierfacq
