### ISSUE TITLE
Expose total number of unique terms per field in field stats api

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#16704]
It can be useful to report on the total number of unique terms per field in the field stats api, this can be used to get a sense of which fields tend to use more FTSs in memory.  Discussed briefly with @mikemccand earlier, he mentioned that Lucene does record this, so it will be nice for ES to expose this in the field stats api as well.

**Comment by rmuir** [comment]
This can only be provided per-segment in an efficient way: aggregation of this is expensive.

**Comment by javanna** [comment]
The field stats API has been removed, closing.
