### ISSUE TITLE
marvel show nodes Incorrectly.

### ISSUE THREAD

**Issue by zhuqunzhou** [elastic/elasticsearch#16719]
I have five nodes in my cluster.

Firstly,marvel show the number of nodes correctly,But when i restart a node,marvel will add an offline  node. For example,if i restart a node(named `es-1`) N times,then marvel will show N+1 nodes named `es-1`,only one node's state is online,others are offline.

**Comment by clintongormley** [comment]
Hi @zhuqunzhou 

This problem is fixed in v2.3.0 (correct @tlrx ?)

**Comment by tlrx** [comment]
Yes, it has been fixed and will be released in v2.3.0
