### ISSUE TITLE
Tribe node does not fall back if `on_conflict_ is set to prefer

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#16724]
I was reported an issue that if a tribe node is connected to two clusters, and if `tribe.on_conflict` is configured to prefer a cluster for a particular index, then if this cluster is down, the tribe node fails to fall back to the other cluster and the tribe node just fails search requests with a shard-not-available exception.

**Comment by javanna** [comment]
Tribe node has been deprecated and removed, closing.
