### ISSUE TITLE
Enforce limits like max file descriptors and fail to start if node is using non-localhost network

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#16727]
today we only log messages if certain limits like max number of file-descriptors is too low. This is critical in several production environments and we do the non-strict check only to not punish the out of the box experience. Today we only listen to the localhost by default which is a good indicator that we are not running in production. If we run in production ie. there is actually some non-default network interface configured we should enforce limits and also require minimum master nodes set etc. This can happen case by case but the OOB experiences should not punish the users running in production.

**Comment by clintongormley** [comment]
Great idea

**Comment by jasontedor** [comment]
:heart:

**Comment by jasontedor** [comment]
This is tricky because of situations where the node is bound to localhost but publishes to an external interface and sits behind a reverse proxy.

**Comment by s1monw** [comment]
@jasontedor this is what I had in mind https://github.com/s1monw/elasticsearch/commit/1109e29004002e30bc0cfaacdb5f4f838722db5e

**Comment by bleskes** [comment]
> This is tricky because of situations where the node is bound to localhost but publishes to an external interface and sits behind a reverse proxy.

Our protection may not work in this case but treating non-localhost bound ES as production will improve things for most (if not almost all) of the deployments. I think we should do this? (And also the other thing we discussed - i.e., requiring minimum master nodes , in a follow up change).

**Comment by jasontedor** [comment]
> Our protection may not work in this case but treating non-localhost bound ES as production will improve things for most (if not almost all) of the deployments. I think we should do this?

@bleskes Note my earlier :heart; I'm 100% in agreement we should do this and other similar checks, and only pointing out there are cases that we won't catch.
