### ISSUE TITLE
Why es cluster stop to work until i delete the old index?

### ISSUE THREAD

**Issue by zhuqunzhou** [elastic/elasticsearch#16729]
In [es document][1],it introduce that,`If we restart Node 1,If Node 1 still has copies of the old shards, it will try to reuse them, copying over from the primary shard only the files that have changed in the meantime`.

So I did an experiment.

Here are 5 nodes in my cluster,Primary shards `1` is saved in node `1`,and replica shards `1` is saved in node `2`.When i restart node `1` and node `2`,Primary shards `1`'s state become `UNASSIGNED`,and replica shards `1`'s state become `UNASSIGNED` too,the health of the cluster become `red`,and the health never become `green`.And the cluster stop to work until i delete the old index.

  [1]: https://www.elastic.co/guide/en/elasticsearch/guide/master/_coping_with_failure.html

**Comment by astefan** [comment]
This kind of issue should best be handled in our [forum](https://discuss.elastic.co/c/elasticsearch), or in [stackoverflow](http://stackoverflow.com/questions/35496113/why-es-cluster-stop-to-work-until-i-delete-the-old-index) (where I see you already asked the same question).
