### ISSUE TITLE
NullPointerException in InternalClusterService.add() using TransportClient

### ISSUE THREAD

**Issue by EdHowe** [elastic/elasticsearch#16723]
We are using a TransportClient to connect to ES 2.2.0, and getting the following NullPointerException:

! java.lang.NullPointerException: null
! at org.elasticsearch.cluster.service.InternalClusterService.add(InternalClusterService.java:281) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:154) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.cluster.ClusterStateObserver.waitForNextChange(ClusterStateObserver.java:99) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.retry(TransportMasterNodeAction.java:190) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:164) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.start(TransportMasterNodeAction.java:121) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:93) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:50) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:70) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:45) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:41) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:244) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) ~[netty-3.10.5.Final.jar:na]
! at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75) ~[elasticsearch-2.2.0.jar:2.2.0]
! at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.5.Final.jar:na]
! at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) ~[netty-3.10.5.Final.jar:na]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_65]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_65]
! at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_65]

We can reproduce this fairly often in our system tests, which starts an ES instance right before starting our client application.  The client application will create a TransportClient, then immediately do a health status check and wait for a yellow status.  If we put a sleep() between creating the TransportClient and the health check, the problem doesn't manifest.

InternalClusterService has an updateTasksExecutor that gets populated by the doStart() method.  The InternalClusterService, however, only appears to be started via Node.start(), which is started via Bootstrap.start(), which is only called by Elasticsearch.main().  In other words, the updateTasksExecutor is only populated when the ES server is run, not when an ES client is used.

The stacktrace above appears to be related to the Transport starting up and not finding a master node.  It then creates a listener to watch for changes to the master node, and tries to add this to the updateTasksExecutor of InternalClusterService, which based on the above paragraph, is null.

I believe we are running into this because we are starting ES immediately before starting our client app, and connecting before a master node has been determined.

Regards,
Ed Howe
Nexidia, Inc.

**Comment by bleskes** [comment]
The problem doesn't lie in the transport client, but rather at the node that first receives the request. This stems from the problem that the cluster service is only started after the transport service, meaning that the node accepts requests before it is fully ready to receive them.  

I've opened #16746 . Thanks for reporting.
