### ISSUE TITLE
Is there a way to find avg without outliers?

### ISSUE THREAD

**Issue by liorg2** [elastic/elasticsearch#16736]
I think that it can be s great feature

**Comment by jpountz** [comment]
Closing: this looks too specific to me for us to have a dedicated aggregation.

As a side-note, you can already do it with two requests:
 - a first one with a percentiles aggregation to figure out what the outliers are
 - a second one that would filter outliers out and run an average aggregation on the desired field

**Comment by liorg2** [comment]
Outliers detection has several algorithms, and percentiles filtering can be
naive..
In my opinion it can be really cool and usable feature

https://en.m.wikipedia.org/wiki/Outlier
