### ISSUE TITLE
More powerful index pattern matching

### ISSUE THREAD

**Issue by pemontto** [elastic/elasticsearch#16735]
Was speaking to @rashidkpc at the AMA booth at Elastic{ON} about the deprecation of date stamped index matching in Kibana. To allow more granular filtering of indices it would be great if index pattern matching supported more than just `*` wildcards. Rashid mentioned using a `?` for single character matching but basic regex patterns would also be awesome. He also said there could be and existing issue for this but I wasn't able to find it.

See also: https://discuss.elastic.co/t/index-filtering-on-more-than-a-wildcard/40802

**Comment by clintongormley** [comment]
Hi @pemontto 

Given that we're moving away from index names with date stamps, what kind of matching would you like to do?

**Comment by pemontto** [comment]
Using the example from discuss, we have users that append tags to their index names for various reasons e.g.
```
finance-logs-2016.02.03
finance-logs-2016.02.03-temp
finance-logs-2016.02.03-pre-change
````

Not having the ability to specify a pattern that can exclude trailing characters means they're matching our generic wildcard patterns and giving us incorrect documents and document counts in Kibana. Not to mention it would useful wherever we use the multi-index syntax like snapshots.

**Comment by clintongormley** [comment]
@pemontto Date math support in index names may be sufficient for your use case? See https://www.elastic.co/guide/en/elasticsearch/reference/current/date-math-index-names.html

**Comment by pemontto** [comment]
Thanks Clinton! That must be new in ES 2?
For this use case it works perfectly, though I can still see basic regex being very beneficial.

Heading on over to Kibana issues to get this supported.

**Comment by pemontto** [comment]
Perhaps jumped the gun a little bit there, I didn't realise the date math is for specific dates/times not actual pattern matching so it won't easily work with Kibana's index pattern setup.

Also I tried the examples and wasn't able to get it working on my 2.2 cluster, am I missing something?
```shell
[root@dev-logstore1 ~]# curl localhost:9200
{
  "name" : "es2beta-1",
  "cluster_name" : "es2beta",
  "version" : {
    "number" : "2.2.0",
    "build_hash" : "8ff36d139e16f8720f2947ef62c8167a888992fe",
    "build_timestamp" : "2016-01-27T13:32:39Z",
    "build_snapshot" : false,
    "lucene_version" : "5.4.1"
  },
  "tagline" : "You Know, for Search"
}
[root@dev-logstore1 ~]# date
Thu Mar  3 12:45:51 AEDT 2016
[root@dev-logstore1 ~]# curl -XPUT localhost:9200/logstash-2015.03.03
{"acknowledged":true}[root@dev-logstore1 ~]# curl -XPUT localhost:9200/logstash-2015.03.02
{"acknowledged":true}[root@dev-logstore1 ~]# curl -XPUT localhost:9200/logstash-2015.03.01
{"acknowledged":true}[root@dev-logstore1 ~]# curl -XPUT localhost:9200/logstash-2015.02.29
{"acknowledged":true}[root@dev-logstore1 ~]# curl -XPUT localhost:9200/logstash-2015.03.04
[root@dev-logstore1 ~]# curl -XGET 'localhost:9200/<logstash-{now%2Fd-2d}>,<logstash-{now%2Fd-1d}>,<logstash-{now%2Fd}>/_mapping'
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"logstash-now/d-2d","index":"logstash-now/d-2d"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"logstash-now/d-2d","index":"logstash-now/d-2d"},"status":404}
```

**Comment by clintongormley** [comment]
@pemontto there are a few things wrong:

1. You created indices for 2015 but we're in 2016
2. Your date formats are not default, so you have to specify them
3. You have to turn off globbing in curl because of the curlies

    curl -XPUT "http://localhost:9200/logstash-2016.02.29"
    curl -XPUT "http://localhost:9200/logstash-2016.03.01"
    curl -XPUT "http://localhost:9200/logstash-2016.03.02"
    curl -XPUT "http://localhost:9200/logstash-2016.03.03"
    curl -XPUT "http://localhost:9200/logstash-2016.03.04"


    curl -g -XGET "http://localhost:9200/<logstash-{now%2Fd-2d{yyyy.MM.dd}}>,<logstash-{now%2Fd-1d{yyyy.MM.dd}}>/_mapping?pretty"

Returns (today):

    {
      "logstash-2016.03.02" : {
        "mappings" : { }
      },
      "logstash-2016.03.01" : {
        "mappings" : { }
      }
    }

**Comment by clintongormley** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
