### ISSUE TITLE
Add experimental geo field

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#16749]
The [JTS](https://www.locationtech.org/projects/technology.jts) license changed from LGPL to dual BSD/EDL and Lucene 6 introduces the new BKD tree structure. With these updates, `geo_point` and `geo_shape` functionality can now be combined, and BKD geo support can be added, to a new experimental `geo` field.

**Comment by imotov** [comment]
Depends on #32039

**Comment by nknize** [comment]
I think we're at consensus to close this and keep the explicit `geo_shape` and `geo_point` fields? The only outstanding discussion item is whether or not to add a companion `point` field for the cartesian `shape` type.

**Comment by iverase** [comment]
Closing this issue. Currently the API for geo_shape as geo_point is the same except for sorting which is missing for geo_shape: https://github.com/elastic/elasticsearch/issues/68953
