### ISSUE TITLE
Remove obsolete optimize_single_shard settings

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#16759]
I just bumped into some settings that I didn't know existed, which also slipped out the settings migration to the new settings infra. As part of the search api execution we have an optimization in place for executions against a single shard, that allow to execute query and fetch in one go (#547), as well as sorting. Both optimization are on by default but can disabled through static `action.search.optimize_single_shard` & `search.controller.optimize_single_shard` settings. I couldn't find any docs around those, and I think these optimizations are always useful and should never be disabled, thus I am proposing to remove support for these settings.

**Comment by jpountz** [comment]
Agreed. I opened #15978 for it a while ago to remove this option.

**Comment by javanna** [comment]
sorry I had missed the PR, will review, thanks @jpountz
