### ISSUE TITLE
How should I optimize cardinality aggregation usage using v2.1?

### ISSUE THREAD

**Issue by jeanLGr** [elastic/elasticsearch#16760]
I only more than 7000 data, the deployment of four nodes, cardinality aggregation query will be down.

Here's an example of my  aggs:
{
	"from": 0,
	"size": 0,
	"aggregations": {
		"CreateDay": {
			"terms": {
				"field": "CreateDay",
				"size": 200
			},
			"aggregations": {
				"PV": {
					"value_count": {
						"field": "_index"
					}
				},
				"UV": {
					"cardinality": {
						"field": "DeviceID",
						"precision_threshold": 40000
					}
				},
				"IpCount": {
					"cardinality": {
						"field": "IPAddress",
						"precision_threshold": 40000
					}
				}
			}
		}
	}
}

**Comment by jasontedor** [comment]
GitHub is reserved for bug reports and feature requests, but it looks like you just have an end-user question. Can you please repost this on the [Elastic Discourse forums](https://discuss.elastic.co)?
