### ISSUE TITLE
Missing format parameter in RangeFilterBuilder

### ISSUE THREAD

**Issue by seallison** [elastic/elasticsearch#16768]
The 1.7 documentation for Range Filter states that it accepts a 'format' parameter: https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-range-filter.html#_date_options_2

However, the format parameter cannot be found on the RangeFilterBuilder:  https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/index/query/RangeFilterBuilder.java

**Comment by cbuescher** [comment]
@seallison thanks for bringing this up. The `format` parameter is supported by the json parser in 1.7, so using the query DSL should work here. The 2.x branch also already has a setter for the `format` parameter in the RangeQueryBuilder (FilterBuilders are merged with QueryBuilders starting with 2.x). @clintongormley I'm don't think we still add non-critical changes to the 1.7 branches, so I think this can be closed, but please reopen if I'm missing something.

**Comment by clintongormley** [comment]
@cbuescher agreed - thanks for looking at it
