### ISSUE TITLE
Recollocation shard is not working

### ISSUE THREAD

**Issue by juandasgandaras** [elastic/elasticsearch#16762]
Hello, 

I have a problem with Elasticsearch, one of my nodes failed and after this I wake up it and it is my cluster again and it is recognized by the other nodes inside the cluster. 

Aparently all is working correctly but the problem is that the shards don´t allocate in the new node so in this way I only have two of three nodes in my cluster with data, and the cluster state is yellow because I have a replica shard that it is initializing all time and it is not posible to allocate in any node. 

-------------------------                  ------------------------        ------------------------------
| Node 1  with data |                 |  Node 2 with data |       | **Node 3 NO DATA** |
-------------------------                  ------------------------         ----------------------------   

I have a replica shard that it is initializing too and It is imposible for me recollocate in any node with the directive reroute for the replica shard that it is initializing:

```
curl -XPOST 'localhost:9200/_cluster/reroute' -d '{
     "commands": [
        {
            "allocate": {
                "index": "'$INDEX'",
                "shard": '$SHARD',
                "node": "'$NODE'",
                "allow_primary": true
          }
        }
    ]
  }'
```

The configuration file that I have in this cluster for all nodes is:

```
cluster.name: elastic_16/12/2015

bootstrap.mlockall: true

gateway.type: local
gateway.recover_after_nodes: 1
gateway.recover_after_time: 5m
gateway.expected_nodes: 3


indices.recovery.max_bytes_per_sec: 100mb
discovery.zen.minimum_master_nodes: 2

discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["IP  node 1", "IP  node 2"]


path.logs: elasticsearch/logs
path.data: elasticsearch/data
path.work: elasticsearch/work
path.plugins: elasticsearch/plugins

http.cors.enabled: true
http.cors.allow-origin: /.*/
http.cors.allow-credentials: true 


index.routing.allocation.disable_allocation: false


```

The elasticsearch version that I have is the 1.4.4.

**Comment by eskibars** [comment]
Hi @juandasgandaras a ton has changed since 1.4.4, especially with respect to resiliency.  I really recommend you upgrade.  Additionally, feel free to open a thread over on our forums https://discuss.elastic.co/ if you want to discuss your specific current cluster issues, which is better suited for that type of situation
