### ISSUE TITLE
min_doc_freq overwritten in direct generator for phrase suggester

### ISSUE THREAD

**Issue by micpalmia** [elastic/elasticsearch#16764]
The direct generator part of the phrase suggester documentation states that it's possible to define a `min_doc_freq` parameter in order to "improve quality by only suggesting high frequency terms". This makes a lot of sense as a direct generator is simply a term suggester that generate suggestions for the phrase suggester.

Unfortunately, though, this value is overwritten when invoking the underlying Lucene `DirectSpellChecker` from [DirectCandidateGenerator](https://github.com/elastic/elasticsearch/blob/2.2/core/src/main/java/org/elasticsearch/search/suggest/phrase/DirectCandidateGenerator.java#L115):

```
spellchecker.setThresholdFrequency(this.suggestMode == SuggestMode.SUGGEST_ALWAYS ? 0 : thresholdFrequency(frequency, dictSize));
```

ignoring the parameter provided by the user.

To add to the confusion, the other frequency parameter `max_term_freq` works as expected.

It seems to be wrong to overwrite the `thresholdFrequency` on the spellchecker because the spellchecker is provided with the `suggest_mode` and already contains the logic to return the right terms according to the mode's rules.

**Comment by clintongormley** [comment]
@cbuescher has this already been dealt with in the suggester refactoring?

**Comment by cbuescher** [comment]
@clintongormley no, this is internal logic in the DirectCandidateGenerator that hasn't been changes by the refactoring, so it should be treated as a separate issue. The line pointed out was added by this commit (8235b89e9cd4f222ee689d47ca2ef4686b7a6971), so I assume there is a reason in overwriting the threshold when the suggest mode is ALWAYS.

**Comment by micpalmia** [comment]
The line has been *edited* in the commit to have a separate logic when the suggest mode is `ALWAYS`, but shouldn't have been there in the first place, because whatever the suggest mode, that logic is already implemented at Lucene level.

**Comment by cbuescher** [comment]
@micpalmia you are right. Looking at the code, the spellchecker inside DirectCandidateGenerator seems to get reused to calculate suggestions for each term in the phrase. To me it looks like the overwrite of the original value is needed to take into account the different term frequencies of all tokens in the phrase. The original `min_doc_freq` still comes into play via `frequencyPlateau`, so I'm not sure this is a bug. Maybe @s1monw can help here. Do you experience a particular problem with the `min_doc_freq` parameter for a particular setting?

**Comment by micpalmia** [comment]
Yes, I noticed a problem trying to tune a phrase suggester (that's why I realized something was fishy). I'm going to try producing a working sample showing the issue.

**Comment by s1monw** [comment]
@micpalmia we store the original frequency in the `DirectSpellchecker` ctor and then use it as the `frequencyPlateau` which is then in-turn returned from `thresholdFrequency(frequency, dictSize)` so it looks fine to me?

**Comment by kaglowka** [comment]
I've been playing around with a perfectly usual suggester case and no matter what value I use as min_doc_freq (either ridiculously high integer or any float value), I get equal results.

I'm rather new to ElasticSearch so I don't exactly understand its inner mechanisms, but if the way min_doc_freq works is much subtler than that, maybe the documentation should be improved?

I'm quoting my exact query so all parameters are explicitly set, but the same occurs for default parameters.

```

{
  "query": {
    "match_all": {}
  },
  "suggest": {
    "simple_phrase": {
      "phrase": {
        "field": "text_bigram",
        "confidence": 2.0,
        "smoothing": {
          "stupid_backoff": {
            "discount": 0.1
          }
        },
        "gram_size": 3,
        "direct_generator": [
          {
            "min_doc_freq": "1000000",
            "max_term_freq": 0.0001,
            "field": "text_raw",
            "suggest_mode": "always",
            "min_word_length": 1,
            "max_edits": 2
          }
        ],
        "real_word_error_likelihood": 0.95,
        "max_errors": 2,
        "size": 3
      },
      "text": "some text"
    }
  }
}
```

**Comment by s1monw** [comment]
as said above with `"suggest_mode": "always",` the `"min_doc_freq": 1000000,` will be ignored since we always suggest!

**Comment by azhuchkov** [comment]
I use `"suggest_mode": "missing"` and it seems that `min_doc_freq` is totally ignored.
Played with `accuracy` which i couldn't find documentation for: for values greater `0.9` the suggester stops advise anything.
I'm using Elasticsearch `v2.4.4` .

**Comment by andyb-elastic** [comment]
This still occurs in master - phrase suggester will return a suggestion for a term that has a document frequency lower than `min_doc_freq`, regardless of `suggest_mode`

```
PUT doc-freq
{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 0,
      "analysis": {
        "analyzer": {
          "trigram": {
            "type": "custom",
            "tokenizer": "standard",
            "filter": ["standard", "shingle"]
          }
        },
        "filter": {
          "shingle": {
            "type": "shingle",
            "min_shingle_size": 2,
            "max_shingle_size": 3
          }
        }
      }
    }
  },
  "mappings": {
    "_doc": {
      "properties": {
        "message": {
          "type": "text",
          "fields": {
            "suggest": {
              "type": "text",
              "analyzer": "trigram"
            }
          }
        }
      }
    }
  }
}

PUT doc-freq/_doc/1
{
  "message": "potato vodka"
}

PUT doc-freq/_doc/2
{
  "message": "potato chips"
}

PUT doc-freq/_doc/3
{
  "message": "potato head"
}


GET doc-freq/_search
{
  "suggest": {
    "text": "potayo bread",
    "small_potatoes": {
      "phrase": {
        "field": "message.suggest",
        "direct_generator": [
          {
            "field": "message.suggest",
            "min_doc_freq": 5,
            "suggest_mode": "popular"
          }
        ]
      }
    }
  }
}
```

Suggest result

```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  },
  "suggest": {
    "small_potatoes": [
      {
        "text": "potayo",
        "offset": 0,
        "length": 6,
        "options": [
          {
            "text": "potato",
            "score": 0.57332504
          }
        ]
      }
    ]
  }
}
```

@elastic/es-search-aggs

**Comment by xrammit** [comment]
I experience the same issue as @andyb-elastic. Is there a solution, workaround or fix to get min_doc_freq working with the phrase suggester?
