### ISSUE TITLE
Allow to delete the document from script

### ISSUE THREAD

**Issue by bra-fsn** [elastic/elasticsearch#16765]
According to [this discussion](https://discuss.elastic.co/t/is-it-possible-to-delete-a-document-from-a-script/42343), elasticsearch currently doesn't support deleting the document from the script, which is called on it.
It would make some stuff easier (just like scripts do, without the hassle of handling versions, changes and retries on the client side), so I create this issue, hoping that somebody will find this eventually useful enough to implement.
Thanks.

**Comment by clintongormley** [comment]
Actually it is possible to delete a document from an update script, and it is documented:

    PUT t/t/1
    {}
    
    POST t/t/1/_update
    {
      "script": "ctx.op='delete'"
    }
    
    GET t/t/1  # returns 404
