### ISSUE TITLE
2.2 posting highlighter does not work when highlighting fields different than searched

### ISSUE THREAD

**Issue by roytmana** [elastic/elasticsearch#16778]
**Elasticsearch version**:2.2

**JVM version**:1.7

**OS version**:Win10

**Description of the problem including expected versus actual behavior**: I search on a composite field populated with copy_to while highlight in individual fields contributing to my composite field. I use posting highlighter and set `require_field_match` to false. It used to work with 1.7 and it still works with plain highlighter in 2.2 but not with posting highlighter. My individual fields which I am highlighting have `"index_options": "offsets"` while my composite field do not. 

Postings highlighter works if I highlight and search the same field

Here is an example of my highlight options on a query:
```javascript
{
  "number_of_fragments": 0,
  "require_field_match": false,
  "type": "postings",
  "fields": {
    "additionalInfo": {},
    "advisor.team.acronym": {},
    "comments": {},
    "description": {},
    "engagements.title": {},
    "summary": {},
    "teams.team.acronym": {}
  }
}
```

**Comment by javanna** [comment]
can you please post your queries, what works and what doesn't?

**Comment by roytmana** [comment]
@javanna here is one query that used to work in 1.x but does not work now. 

```javascript
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "search": {
              "query": "fraud",
              "operator": "and"
            }
          }
        }
      ],
      "should": [
        {
          "match": {
            "search": {
              "query": "fraud",
              "type": "phrase",
              "slop": 1,
              "boost": 1.2
            }
          }
        },
        {
          "match": {
            "search_shingle": {
              "query": "fraud",
              "operator": "or",
              "boost": 1.2
            }
          }
        },
        {
          "match": {
            "search_keys": {
              "query": "fraud",
              "operator": "or",
              "boost": 10
            }
          }
        }
      ]
    }
  },
  "from": 0,
  "size": 20,
  "highlight": {
    "number_of_fragments": 0,
    "type": "postings",
    "require_field_match": false,
    "fields": {
      "additionalInfo": {},
      "advisor.team.acronym": {},
      "comments": {},
      "description": {},
      "engagements.jobCode.text": {},
      "engagements.title": {},
      "engagements.productNumber.text": {},
      "mandateAuthority.authorityNumber.text": {},
      "mandateAuthority.title": {},
      "notes.content": {},
      "parties.position.member.name": {},
      "parties.position.orgUnit.acronym": {},
      "parties.position.orgUnit.compositeName": {},
      "sourceIdentifier.text": {},
      "summary": {},
      "teams.stakeholders.appointment.team.acronym": {},
      "teams.team.acronym": {}
    }
  },
  "suggest": {
    "text": "fraud",
    "phrase": {
      "phrase": {
        "field": "search_shingle",
        "size": 4,
        "max_errors": 3,
        "gram_size": 2,
        "direct_generator": [
          {
            "field": "search",
            "suggest_mode": "popular",
            "min_word_length": 3
          }
        ],
        "highlight": {
          "pre_tag": "<em>",
          "post_tag": "</em>"
        }
      }
    }
  },
  "sort": [
    {
      "_score": {
        "order": "desc",
        "missing": "_last"
      }
    },
    {
      "sourceDate": {
        "order": "desc",
        "missing": "_last"
      }
    },
    {
      "id": {
        "order": "desc",
        "missing": "_last"
      }
    }
  ]
}
```

if I switch to `plain` highlighter it works
if is switch field in first match statement from `search` (my composite copy_to field without offsets) to `summary` (one of the fields contributing to the `search` field) it will highlight that one field

is it possible that postings does not honor `require_field_match`?

please let me know if it all looks fine to you and you pinpoint the issue and I will try to find time to have a recreation today (pain too do on windows with curl parameters not working properly)

Alex

**Comment by javanna** [comment]
> is it possible that postings does not honor require_field_match?

Yes that is definitely the problem. Here is the original PR that caused this breaking change: https://github.com/elastic/elasticsearch/pull/11077#issuecomment-102494447 . We also listed the breaking change in the migration guide here: https://github.com/elastic/elasticsearch/blob/master/docs/reference/migration/migrate_2_0/search.asciidoc#postings-highlighter-doesnt-support-match_phrase_prefix .

I suggest either searching and highlighting the same fields, or providing a specific highlight query that differs from the search one. Otherwise use the plain highlighter instead, which still supports `require_field_match`.

**Comment by roytmana** [comment]
@javanna I created a recreation https://gist.github.com/roytmana/a2d6efd307c5aa86210e but I see it is a feature not a bug :-( Any chance it will be relaxed on Lucene side or it is pretty much done deal and I need to look for a work around? I guess I could add these fields to should portion of my query using fastest type of match query keeping everything else intact

this is such a common case when searching "most" of your data :-( when you need to search over dozens of fields and combine it with shingles etc queries get very heavy and keeping track of all fileds involved labor intensive and spread across several layers. 

plain highlighter is good deal slower 

not being able to highlight make copy_to even less useful (no boosting of contributing fields, no control over offset gaps for contributing fields, no highlighting ...)

**Comment by javanna** [comment]
hi @roytmana I am sorry to bring you bad news, but I don't see `require_field_match` being supported by the lucene postings highlighter. I think it was wrong to support in the first place in the elasticsearch postings highlighter, it made things slow and a lot more complicated. There are easy workarounds though, either search and highlight the same fields, or provide a specific highlight query against the fields that need to be highlighted. Can you let us know if these are good enough please?

**Comment by roytmana** [comment]
Thank you @javanna I am closing it then...
