### ISSUE TITLE
CANON_EQ - PatternSyntaxException

### ISSUE THREAD

**Issue by GokGokalp** [elastic/elasticsearch#16779]
Hi all.

I have a problem about CANON_EQ.
When i using CANON_EQ flag in aggregation with Turkish character like : "öğretmen"
I always get this error: "nested: PatternSyntaxException[Unclosed group near index 34\n(?:ög|ög|og̈(?:ğr|ğr|gr̆)etmen"

This is my agg:
      "aggs": {
        "JobCategory_original": {
          "terms": {
            "field": "jobCategories.nameWithId",
            "size": 3,
            "include": {
              "pattern": ".*öğretmen.*",
              "flags": "CANON_EQ|CASE_INSENSITIVE|UNICODE_CASE"
            }
          }
        }
      }

If a delete CANON_EQ in flags then everything's ok. Because this character ")" is missing and i think that reason i get this error. How can i handle this issue?

**Comment by eskibars** [comment]
I tried a very basic case with ES 2.2 and wasn't able to replicate.

To help isolate this, can you:

1. Identify what version you're using
2. Post a gist `curl` example with a document and full query that has the issue?

**Comment by GokGokalp** [comment]
Thanks for reply. 
We're currently using 1.7.1. 
We started to upgrade process yesterday. I hope this issue and others will fix with 2.2.

**Comment by eskibars** [comment]
OK, I'm going to go ahead and close the issue.  If you're having issues after your upgrade, we can reopen.  Just post your `curl` reproduction at that time if that's the case.
