### ISSUE TITLE
Consider adding a quorum_timeout setting

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#16772]
The functionality of this setting will cover the use cases where one would like for the indexing operation to fail faster in case of shards quorum not being met: `Not enough active copies to meet write consistency of [QUORUM] (have X, needed Y)`.

In a case when most of the shards are allocated with their replicas most of the documents can be indexed immediately. But the documents that go to the shards without replicas allocated (there is no quorum) just have to wait for the general timeout to expire which makes it hard on the client side to manage the indexing process.

Setting `timeout=1ms` on the indexing request will potentially interfere with a normal, slower indexing process and could timeout sooner for nothing.

**Comment by astefan** [comment]
Similar discussion:  https://github.com/elastic/elasticsearch/issues/4739

**Comment by bleskes** [comment]
The timeout parameter actually controls how long you wait for the quorum  to be available.  We do not have a timeout on the request to the replicas/primary. Can you elaborate a bit more ?

**Comment by astefan** [comment]
Ok for now to use the `timeout` parameter with a very low value. Thanks.
