### ISSUE TITLE
Three data nodes die

### ISSUE THREAD

**Issue by jqsl2012** [elastic/elasticsearch#16780]
**Elasticsearch version**:v1.7.3

**JVM version**:v1.7.0_55

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

hs_err_pid27639.log：https://github.com/jqsl2012/helloGit/blob/master/es_die_log.zip

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00002b233569732b, pid=22429, tid=47464825222912

 JRE version: Java(TM) SE Runtime Environment (7.0_55-b13) (build 1.7.0_55-b13)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (24.55-b03 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 J  org.apache.lucene.codecs.blocktree.SegmentTermsEnumFrame.loadBlock()V

 Core dump written. Default location: /home/yimr/lamp/elasticsearch/bin/core or core.22429 (max size 1 kB). To ensure a full core dump, try "ulimit -c unlimited" before starting Java again

**Describe the feature**:

**Comment by jasontedor** [comment]
JVM crashes are almost always due to JVM bugs. I took a look at your logs, I see the segfaults and nothing jumps out at me as far as dangerous JVM flags or the like. I recommend upgrading your JVM at a minimum, at least to the latest 7u release but preferably to the latest 8u release.

**Comment by jqsl2012** [comment]
Thanks for your help

**Comment by PKFresher** [comment]
https://community.appian.com/support/w/kb/715/kb-1435-crashes-related-to-apache-lucene-library
https://issues.apache.org/jira/browse/LUCENE-6943    same question.

use MmapDirectory

**Comment by AlixMu** [comment]
[ index.store.type: mmapfs ]
this setting can crash server io ?
