### ISSUE TITLE
CorruptIndexException

### ISSUE THREAD

**Issue by rgolab** [elastic/elasticsearch#16789]
**ELK version**: 
Elasticsearch: 2.2.0
Logstash: 2.2.2-1
Kibana: 4.4.1

**JVM version**:
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

**OS version**:
Debian 8.3 Jessie (clean install)

**Description of the problem**:
I have problem with my new elasticsearch, my instance crash after few minutes (http://pastie.org/10735193). I tried use lucane manually like here: https://github.com/elastic/elasticsearch/issues/16083 but no problems were detected with this index (http://pastie.org/10735194).

**Comment by s1monw** [comment]
your checkindex says there are no segments in this index, can you check that you are running this on the right datapath / node?

**Comment by rgolab** [comment]
I think i'm running it on the right datapath / node. List of files in that index directory: http://pastie.org/10736728

**Comment by clintongormley** [comment]
Could you upload the corrupted file please?

**Comment by clintongormley** [comment]
Or even the whole directory

**Comment by s1monw** [comment]
you have to call commit first before you run checkindex I guess otherwise it will not be able to check it.

**Comment by s1monw** [comment]
> you have to call commit first before you run checkindex I guess otherwise it will not be able to check it.

err... I mean `_flush` sorry

**Comment by clintongormley** [comment]
No further feedback. Closing
