### ISSUE TITLE
Implement stronger external versioning scheme

### ISSUE THREAD

**Issue by koenoki** [elastic/elasticsearch#16783]
Per https://www.elastic.co/guide/en/elasticsearch/guide/current/optimistic-concurrency-control.html: "Elasticsearch checks that the current _version is less than the specified version". This still leaves room for concurrency issues. Eg:

1. Client A reads a document with version V0
2. Client B reads the same document, version V0
3. Client A writes back the document as version V1
4. Client B writes back the document as version V2

In the above example, the last write can overwrite the change made by client A. This does not happen with the regular (non-external) versioning scheme. In order to do full versioning check, the system needs to know both the previous version and the new version. 

So, can we allow optionally specifying the previous version in the PUT request? Eg:

PUT /website/blog/2?version=5&prev_version=3&version_type=external

If prev_version is unspecified then ES behaves as it does today. But if it is specified then ES should check if the current _version matches the specified prev_version, as opposed to checking if the current _version is less than the new version.

**Comment by jpountz** [comment]
Maybe this means you should not use external versioning? External versioning helps with keeping elasticsearch in sync with another system that is responsible for producing the version numbers. So overriding a document whenever the version increases is the right thing to do.

**Comment by koenoki** [comment]
Thinking about this some more, what you wrote makes sense. In the scenario that I had in mind, the last write was data transformation which didn't increment the version in the master DB, so the last write should continue to use V0.
