### ISSUE TITLE
GetMappingsResponse dosn't work with alias

### ISSUE THREAD

**Issue by AndreVirtimo** [elastic/elasticsearch#16795]
**Elasticsearch version**: 2.2

**JVM version**: 1.7

**OS version**: Linux

**Description of the problem including expected versus actual behavior**:

Read a mapping from GetMappingsResponse failed when using the alias instead of the index name. Because the index-name is used as key, not the alias name.

**Steps to reproduce**:

GetMappingsResponse response = client.admin().indices()
                .prepareGetMappings(esIndex) //use an alias here
                .setTypes(esType)
                .execute().actionGet();

response.mappings().get(esIndex); //return null when using alias, here are only index-names available

Using REST API it works fine:
.../esIndex/_mapping/esType/

When using an alias name, I got a response with the alias-name instead of the real index name.

**Comment by javanna** [comment]
Hi @AndreVirtimo I am trying to reproduce this with no luck. I always get the index name back on both java api and REST layer, which is the expected behaviour as aliases get resolved to concrete indices as part of api execution. It is expected that with the java api the lookup for the alias in the map fails, better to iterate over the map entries instead. Can you double check your REST api output and post any output that may contain the alias name in it rather than the index name?

**Comment by AndreVirtimo** [comment]
Hey @javanna , I'm sorry. I have tested again the REST Call via alias and I get the index-name in the response.

But never the less I would expect the alias name, because the usage of an alias should be transparent.

**Comment by javanna** [comment]
No problem @AndreVirtimo . As for your comment:

> But never the less I would expect the alias name, because the usage of an alias should be transparent.

This is how all the elasticsearch apis work, responses contain the resolved concrete indices, not the alias (or aliases) used in the request. That said I am marking this issue for discussion so we can discuss this internally and see whether we want to change this or not.

**Comment by clintongormley** [comment]
> This is how all the elasticsearch apis work, responses contain the resolved concrete indices, not the alias (or aliases) used in the request. That said I am marking this issue for discussion so we can discuss this internally and see whether we want to change this or not.

We can't change this as an alias may point to multiple indices, which may have different mappings.
