### ISSUE TITLE
Elasticsearch : Filter does not work with wildcard query

### ISSUE THREAD

**Issue by abtpst** [elastic/elasticsearch#16797]
**Elasticsearch version**:2.2

**JVM version**:1.8

**OS version**:Win 7

Here is my query

    POST indexName/test/_search
    {
      "fields" : ["Col1"],
      "query":{
    	    				"filtered":{
    	    				  
    	    				"query":{
    	    				  
    	    				
    	    				"wildcard": {
    	    				  
    	    					"Col1": {
    	    					  
    	    				          "value": "*zxc*"
    	    				       }
    	    				    }
    	    				  
    	    				  },
    	    				"filter":
    	            {
    	  	          "term": { 
    	  	            
    	  	            "Col2": "val" 
    	  	            
    	  	          }
    	            }
    	    			}
    	    				    
    	    	}
    }

so i want to do a wildcard on `Col1` for the value `*zxc*` and i want only those values where `Col2` is `val` this returns 0 hits. is there anything wrong with my syntax?

The wildcard query works independently if i remove the filter.

**Edit**

this works

    POST indexName/test/_search
    {
      "fields" : ["Col1"],
      "query":{
    	    				"filtered":{
    	    				  
    	    				
    	    				"filter":
    	            {
    	  	          "term": { 
    	  	            
    	  	            "Col2": "val" 
    	  	            
    	  	          }
    	            }
    	    			}
    	    				    
    	    	}
    }

sample document returned

    {
            "_index": "indexName",
            "_type": "test",
            "_id": "oainfubgvwurebetrnjt",
            "_score": 1,
            "fields": {
              "Col1": [
                "uyiwebvybg iuowenbgubnrwev  uirbgvuire3bv  vuirbg"
              ]
            }
          }

and so does this

    POST indexName/test/_search
    {
      "fields" : ["Col1"],
      "query":{
    	    				"wildcard": {
    	    				  
    	    					"Col1": {
    	    					  
    	    				          "value": "*zxc*"
    	    				       }
    	    				    }
    	    				    
    	    	}
    }

sample document returned

    {
            "_index": "indexName",
            "_type": "test",
            "_id": "aofnhuiwegbnweu",
            "_score": 1,
            "fields": {
              "Col1": [
                "idasihid huwbgbuiwb iuohfuweb zxc oifjhwgbu"
              ]
            }
          }

so both of these queries work independently. How do i combine them?
 
Is this a bug in elasticsearch?

**Steps to reproduce**:
 1. Create sample dataset with two columns
 2. Run wildcard and filter queries separately to check if everything works 
 3. Combine wildcard and filter queries

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by clintongormley** [comment]
Hi @abtpst 

This works for me:

    PUT t/t/1
    {
      "Col1": "idasihid huwbgbuiwb iuohfuweb zxc oifjhwgbu",
      "Col2": "val"
    }
    
    POST t/t/_search
    {
      "query": {
        "filtered": {
          "query": {
            "wildcard": {
              "Col1": {
                "value": "*zxc*"
              }
            }
          },
          "filter": {
            "term": {
              "Col2": "val"
            }
          }
        }
      }
    }

But I think you are using Elasticsearch in a very efficient way.  A wildcard query with a leading wildcard leads to a full index scan which is very inefficient.

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
