### ISSUE TITLE
Forbid settings index level settings on a node level

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#16799]
Today we allow to set all kinds of index level settings on the node level which is error prone and difficult to get right in a consistent manner. For instance if some analyzers are setup in a yaml config file some nodes might not have these analyzers and then index creation fails. For settings that should have node level defaults like the default codec we should add dedicated settings.

**Comment by rjernst** [comment]
+1

**Comment by johtani** [comment]
+1
