### ISSUE TITLE
sharing parsed documents

### ISSUE THREAD

**Issue by edvorg** [elastic/elasticsearch#16792]
**Describe the feature**:

While reviewing elasticsearch code I noticed that documents are parsed twice.
1) in prepareIndexOnPrimary
2) in prepareIndexOnReplica
I understand that two different document mapper instances are used for parsing process. But isn't it possible to refactor it out, so document mappers would have a shared parsed document instance somehow? The cause for this change is simple - parsing of documents maybe twice faster than it is now. More than that, we currently use luwak percolator on our project and it uses same lucene Documents so we'd like to share these parsed documents even for outside world and this could be a good addition. These documents seems to be immutable so it shouldn't be difficult. Please let me know, what do you think about this.
Thank, Edward.

**Comment by bleskes** [comment]
prepareIndexOnPrimary & prepareIndexOnReplica are never called on the same node. The reason being that a primary shard is never on the same node as a replica node. As such, I don't believe this is a problem and I'm going to close the issue. If I missed something please reopen.
