### ISSUE TITLE
plugin install script not honouring JAVA_OPTS anymore

### ISSUE THREAD

**Issue by schlitzered** [elastic/elasticsearch#16790]
**Elasticsearch version**: 2.2.0.1 (yum repo)

**JVM version**: openjdk version "1.8.0_71"

**OS version**: CentOS 7.2

**Description of the problem including expected versus actual behavior**:

The elasticsearch plugin install script is not honouring the JAVA_OPTS environment variables anymore. this is needed to provide a http proxy for puppet runs.

**Steps to reproduce**:
 1. export JAVA="-Dhttp.proxyHost=contentproxy.example.com -Dhttp.proxyPort=3128 -Dhttps.proxyHost=contentproxy.example.com -Dhttps.proxyPort=3128"
 2.  /usr/share/elasticsearch/bin/plugin install lmenezes/elasticsearch-kopf
 3. -> timeout

please change the last line of the plugin script from:

```
eval "$JAVA"  -client -Delasticsearch -Des.path.home="\"$ES_HOME\"" $properties -cp "\"$ES_HOME/lib/*\"" org.elasticsearch.plugins.PluginManagerCliParser $arg
```

to

```
eval "$JAVA" $JAVA_OPTS -client -Delasticsearch -Des.path.home="\"$ES_HOME\"" $properties -cp "\"$ES_HOME/lib/*\"" org.elasticsearch.plugins.PluginManagerCliParser $arg
```

**Comment by jasontedor** [comment]
Relates #17121. We will support `ES_JAVA_OPTS` for this script.
