### ISSUE TITLE
use elasticsearch 2.2.0 and Create NativeScript in java and  install successfully but when restart or start elasticsearch it show error

### ISSUE THREAD

**Issue by kingaj** [elastic/elasticsearch#16803]
**Elasticsearch version**: 2.2.0

**JVM version**:1.8

**OS version**:Linux Mint 17.2 Cinnamon 64-bit (Cinnamon 2.6.13)

**Description of the problem including expected versus actual behavior**:
Hi,
      i created nativescript in java and create .zip file with (jar and plugin-descriptor.properties) and install it but when i restart or start elasticsearch then it show error 

**Steps to reproduce**:
 1.create nativescript in java
 2.install nativescript as plugin 
 3.restart or start elasticsearch

**Provide logs (if relevant)**:

**this is log for successfully install nativescript as plugin in elasticsearch 2.2.0**

-> Installing from file:/home/ajay/Desktop/DEVAJAY/Untitled Folder/CustomScriptFactory1.0.zip...
Trying file:/home/ajay/Desktop/DEVAJAY/Untitled Folder/CustomScriptFactory1.0.zip ...
Downloading .DONE
Verifying file:/home/mindarray/Desktop/DEVAJAY/Untitled Folder/CustomScriptFactory1.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
Installed CustomScriptFactory1.0 into /home/mindarray/Desktop/elasticsearch-2.2.0/plugins/CustomScriptFactory1.0

**when restart or start the elasticsearch it show error** 

Exception in thread "main" java.lang.ClassCastException: class org.spacevatican.elasticsearchexample.CustomScriptFactory
	at java.lang.Class.asSubclass(Class.java:3404)
	at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:463)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:431)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
	at org.elasticsearch.node.Node.<init>(Node.java:146)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

**Describe the feature**:

![elasticsearcherror-02-25145717](https://cloud.githubusercontent.com/assets/2405218/13315578/7eab302a-dbd1-11e5-8eba-14fede94d5a2.jpg)

**Comment by dadoonet** [comment]
Sounds like your class `CustomScriptFactory` does not extend `Plugin`.

Can you ask such questions on discuss.elastic.co please? We keep this place only for confirmed issues.

**Comment by kingaj** [comment]
https://discuss.elastic.co/ take lot of time to open
can you please tell me the way how to solve my problem please

**Comment by kingaj** [comment]
and its possible to use elasticserach 1.7 index into 2.2.0 elasticsearch

**Comment by vivekmehta40432** [comment]
yes we have already extended Plugin class.

Here is the code overview:

public class TraceOrgCustomScriptFactory extends Plugin implements NativeScriptFactory
{


    public ExecutableScript newScript(@Nullable Map<String, Object> params)
    {
        return new CustomScript(params);
    }

    public boolean needsScores() {
        return true;
    }

    @Override
    public String name() {
        return "es-plugin";
    }

    @Override
    public String description() {
        return "es-plugin description";
    }
}


--------------------------


public class CustomScript extends AbstractSearchScript
{
    public static final short SCRIPT_UPPER_CASE =0;

    public static final short SCRIPT_LOWER_CASE =1;

    public static final short SCRIPT_REPLACE =2;

    public static final short SCRIPT_SUBSTRING =3;

    public static final short SCRIPT_FORMAT_DATE =4;

    public static final short SCRIPT_ROUND_VALUE =5;

    private final Map<String,Object> m_params;

    public CustomScript(@Nullable Map<String,Object> params)
    {
        m_params =params;
    }

    public Object run()
    {
        Object result =null;

        short scriptType = Short.parseShort(m_params.get("type").toString());

        String field = m_params.get("field").toString();

        ScriptDocValues<Object> value = (ScriptDocValues<Object>) doc().get(field);

        if (value != null && !value.isEmpty())
        {

            switch (scriptType)
            {
                case SCRIPT_UPPER_CASE:

                    result =value.get(0).toString().toUpperCase();

                    break;

               
            }
        }

        return  result;
    }
}

**Comment by vivekmehta40432** [comment]
please provide a proper comment otherwise I have to create another same issue.

**Comment by jasontedor** [comment]
> please provide a proper comment otherwise I have to create another same issue.

A proper comment was given. Your issue is neither stating that there is a bug in Elasticsearch nor is it a feature request. GitHub issues are reserved for bug reports or feature requests; you were directed to the [Elastic Discourse forums](https://discuss.elastic.co) where there is a community that would be more than delighted to help you; this was made clear in the issue template when you filed this issue.

There are unit tests in the Elasticsearch codebase that install native script plugins and those tests pass on the 2.2 branch and the v2.2.0 tag. I note further that your stack trace states that `CustomScriptFactory` can not be cast to an instance of `Plugin` but the code that you pasted here doesn't even show the `CustomScriptFactory` class. It seems clear that you're trying to load a plugin that is not a `Plugin`.

I'm sorry to tell you that there is no evidence of a bug in Elasticsearch here. If you have additional questions, please use the [Elastic Discourse forums](https://discuss.elastic.co) and only use GitHub if you uncover evidence of an actual bug in Elasticsearch.

**Comment by kingaj** [comment]
i change the class and also extend plugin you can see the error which i put above

and my**#  elasticsearch.yml file **


# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please see the documentation for further information on configuration options:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html>
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
 cluster.name: dev-ajay-cluster
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
# node.name: node-1
#
# Add custom attributes to the node:
#
# node.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
# path.data: /path/to/data
#
# Path to log files:
#
# path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
# bootstrap.mlockall: true
#
# Make sure that the `ES_HEAP_SIZE` environment variable is set to about half the memory
# available on the system and that the owner of the process is allowed to use this limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
# network.host: 192.168.0.1
#
# Set a custom port for HTTP:
#
# http.port: 9200
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
# discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):
#
# discovery.zen.minimum_master_nodes: 3
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery.html>
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
# gateway.recover_after_nodes: 3
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html>
#
# ---------------------------------- Various -----------------------------------
#
# Disable starting multiple nodes on a single system:
#
# node.max_local_storage_nodes: 1
#
# Require explicit names when deleting indices:
#
# action.destructive_requires_name: true

 script.inline: on

 script.indexed: on
 
 script.file: true

 script.default_lang: native

 resource.reload.interval: 120s

**Comment by jasontedor** [comment]
Please note that dramatically editing your initial post like you have done just creates confusion.

It looks to me like you are overriding `Plugin#additionalSettings` and returning null and that's why you're getting the NPE.

Finally, unless you have a bug or a feature request, please take any future conversation to the [Elastic Discourse forums](https://discuss.elastic.co).

**Comment by kingaj** [comment]
i create native search plugin in java and try to use as plugin
@jasontedor  sir you have any example or any link which i follow to create native script and use it 
please sir.

**Comment by dadoonet** [comment]
Please @kingaj

> Finally, unless you have a bug or a feature request, please take any future conversation to the Elastic Discourse forums.

**Comment by kingaj** [comment]
thank you my script working
