### ISSUE TITLE
use elasticsearch 2.2.0 and Create NativeScript in java and install successfully but when restart or start elasticsearch it show error

### ISSUE THREAD

**Issue by vivekmehta40432** [elastic/elasticsearch#16806]
**Elasticsearch version**: 2.2.0

**JVM version**:1.8

**OS version**:Linux Mint 17.2 Cinnamon 64-bit (Cinnamon 2.6.13)

**Description of the problem including expected versus actual behavior:**
Hi,
i created nativescript in java and create .zip file with (jar and plugin-descriptor.properties) and install it but when i restart or start elasticsearch then it show error

Steps to reproduce:
1.create nativescript in java
2.install nativescript as plugin
3.restart or start elasticsearch

**Provide logs (if relevant):

this is log for successfully install nativescript as plugin in elasticsearch 2.2.0**

-> Installing from file:/home/ajay/Desktop/DEVAJAY/Untitled Folder/CustomScriptFactory1.0.zip...
Trying file:/home/ajay/Desktop/DEVAJAY/Untitled Folder/CustomScriptFactory1.0.zip ...
Downloading .DONE
Verifying file:/home/mindarray/Desktop/DEVAJAY/Untitled Folder/CustomScriptFactory1.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
Installed CustomScriptFactory1.0 into /home/mindarray/Desktop/elasticsearch-2.2.0/plugins/CustomScriptFactory1.0

**when restart or start the elasticsearch it show error**

Exception in thread "main" java.lang.ClassCastException: class org.spacevatican.elasticsearchexample.CustomScriptFactory
at java.lang.Class.asSubclass(Class.java:3404)
at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:463)
at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:431)
at org.elasticsearch.plugins.PluginsService.(PluginsService.java:129)
at org.elasticsearch.node.Node.(Node.java:146)
at org.elasticsearch.node.Node.(Node.java:128)
at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

**Describe the feature:**

![7eab302a-dbd1-11e5-8eba-14fede94d5a2](https://cloud.githubusercontent.com/assets/5938907/13320321/10b64b46-dbee-11e5-9ec9-7be1bfb343c2.jpg)

**Comment by vivekmehta40432** [comment]
yes we have already extended Plugin class.

Here is the code overview:

public class TraceOrgCustomScriptFactory extends Plugin implements NativeScriptFactory
{

public ExecutableScript newScript(@Nullable Map<String, Object> params)
{
    return new CustomScript(params);
}

public boolean needsScores() {
    return true;
}

@Override
public String name() {
    return "es-plugin";
}

@Override
public String description() {
    return "es-plugin description";
}

}

public class CustomScript extends AbstractSearchScript
{
public static final short SCRIPT_UPPER_CASE =0;

public static final short SCRIPT_LOWER_CASE =1;

public static final short SCRIPT_REPLACE =2;

public static final short SCRIPT_SUBSTRING =3;

public static final short SCRIPT_FORMAT_DATE =4;

public static final short SCRIPT_ROUND_VALUE =5;

private final Map<String,Object> m_params;

public CustomScript(@Nullable Map<String,Object> params)
{
    m_params =params;
}

public Object run()
{
    Object result =null;

    short scriptType = Short.parseShort(m_params.get("type").toString());

    String field = m_params.get("field").toString();

    ScriptDocValues<Object> value = (ScriptDocValues<Object>) doc().get(field);

    if (value != null && !value.isEmpty())
    {

        switch (scriptType)
        {
            case SCRIPT_UPPER_CASE:

                result =value.get(0).toString().toUpperCase();

                break;


        }
    }

    return  result;
}

}

**Comment by vivekmehta40432** [comment]
please guide me. do not close issue directly. it was working with ES1.7 but not working with ES2.2.0

give at least a proper reply and guide us.

**Comment by jasontedor** [comment]
Duplicates #16803

**Comment by vivekmehta40432** [comment]
it's duplicate because you closed old one without any proper answer
