### ISSUE TITLE
Unexpected `array_index_out_of_bounds_exception`

### ISSUE THREAD

**Issue by klahnakoski** [elastic/elasticsearch#16812]
**Elasticsearch version**: 2.2.0

**JVM version**: 8.0.???

**OS version**: CentOs

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

    PUT t/t/_bulk
    {"index":{}}
    {"a":"x","b":"m","v":2}
    {"index":{}}
    {"a":"x","b":"n","v":3}
    {"index":{}}
    {"a":"x","b":null,"v":5}
    {"index":{}}
    {"a":"y","b":"m","v":7}
    {"index":{}}
    {"a":"y","b":"n","v":11}
    {"index":{}}
    {"a":"y","b":null,"v":13}
    {"index":{}}
    {"a":null,"b":"m","v":17}
    {"index":{}}
    {"a":null,"b":"n","v":19}
    {"index":{}}
    {"a":"x","b":"m","v":27}
    {"index":{}}
    {"a":"y","b":"n","v":39}
    
    GET t/t/_search
    {
      "aggs": {
        "_match": {
          "aggs": {
            "_missing": {
              "aggs": {
                "v": {
                  "extended_stats": {
                    "field": "v"
                  }
                }
              },
              "missing": {
                "field": "a"
              }
            }
          },
          "terms": {
            "field": "b",
            "size": 10
          }
        }
      },
      "size": 0
    }

Get an error (and some results)
```
{
	"took":1,
	"timed_out":false,
	"_shards":{
		"total":3,
		"successful":1,
		"failed":2,
		"failures":[{
			"shard":0,
			"index":"testing_e18cf562b420160225_183510",
			"node":"QlVbQTlvT5O_fe9x4LxvWQ",
			"reason":{
				"type":"array_index_out_of_bounds_exception",
				"reason":null
			}
		}]
	},	
	// results clipped
```
The `stats` aggregate does not have this problem.

**Comment by scrotty** [comment]
Our team has run into this issue too (ES 2.2, RedHat). In one of the failure modes the entire ES cluster operation is impaired and requires the cluster be fully stopped and restarted to recover. The workaround on our end has been to drop the batch size dramatically (to 25!).
