### ISSUE TITLE
Failed to deserialize exception response from stream

### ISSUE THREAD

**Issue by mukeshkdangi** [elastic/elasticsearch#16814]
**Getting following error - **
```
failed to get node info for [#transport#-1][MY-Lap.local][inet[localhost/127.0.0.1:9300]], disconnecting...
org.elasticsearch.transport.RemoteTransportException: Failed to deserialize exception response from stream
Caused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize exception response from stream
...................
and 	... 23 more
Exception in thread "main" org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
```

**I'm getting this error while running this command .**

  `  java -Dfile.encoding=utf-8 -jar foxtrot-server/target/foxtrot-server-0.1.jar initialize config/local.yml
`
**Here is my local.yml - **

> http:
>   port: 17000
>   adminPort: 17001
>   connectorType: nonblocking
> 
> elasticsearch:
>   hosts:
>   - localhost
>   cluster: foxtrot
> 
> hbase:
>   secure : false
>   tableName: foxtrot
> 
> cluster:
>   name: foxtrot
>   disableMulticast: true
>   members: ["localhost:9201", "localhost:9200"]
> 
> logging:
>   level: ERROR
> 
> deletionconfig:
>   active: true
>   interval: 86400
>   initialdelay: 60

**and http://localhost:9200/_nodes/jvm?pretty output - ** all versions are same

> {
> cluster_name: "elasticsearch_mukesh",
> nodes: {
> CySFQu8vRg2_FRcohq_csA: {
> name: "Scarlet Spiders",
> transport_address: "127.0.0.1:9300",
> host: "127.0.0.1",
> ip: "127.0.0.1",
> version: "2.2.0",
> build: "8ff36d1",
> http_address: "127.0.0.1:9200",
> jvm: {
> pid: 98584,
> version: "1.8.0_60",
> vm_name: "Java HotSpot(TM) 64-Bit Server VM",
> vm_version: "25.60-b23",
> vm_vendor: "Oracle Corporation",
> start_time_in_millis: 1456407783249,
> mem: {
> heap_init_in_bytes: 268435456,
> heap_max_in_bytes: 1038876672,
> non_heap_init_in_bytes: 2555904,
> non_heap_max_in_bytes: 0,
> direct_max_in_bytes: 1038876672
> },
> gc_collectors: [
> "ParNew",
> "ConcurrentMarkSweep"
> ],
> memory_pools: [
> "Code Cache",
> "Metaspace",
> "Compressed Class Space",
> "Par Eden Space",
> "Par Survivor Space",
> "CMS Old Gen"
> ],
> using_compressed_ordinary_object_pointers: "true"
> }
> },
> 5Wl3g25MStKUGt8ECnDLVg: {
> name: "Quasar",
> transport_address: "127.0.0.1:9301",
> host: "127.0.0.1",
> ip: "127.0.0.1",
> version: "2.2.0",
> build: "8ff36d1",
> http_address: "127.0.0.1:9201",
> jvm: {
> pid: 2525,
> version: "1.8.0_60",
> vm_name: "Java HotSpot(TM) 64-Bit Server VM",
> vm_version: "25.60-b23",
> vm_vendor: "Oracle Corporation",
> start_time_in_millis: 1456427039800,
> mem: {
> heap_init_in_bytes: 268435456,
> heap_max_in_bytes: 1038876672,
> non_heap_init_in_bytes: 2555904,
> non_heap_max_in_bytes: 0,
> direct_max_in_bytes: 1038876672
> },
> gc_collectors: [
> "ParNew",
> "ConcurrentMarkSweep"
> ],
> memory_pools: [
> "Code Cache",
> "Metaspace",
> "Compressed Class Space",
> "Par Eden Space",
> "Par Survivor Space",
> "CMS Old Gen"
> ],
> using_compressed_ordinary_object_pointers: "true"
> }
> }
> }
> }

any help please ?

**Comment by jasontedor** [comment]
Sorry, but we do not support foxtrot.
