### ISSUE TITLE
Ingest: Small documentation problem for grok processor

### ISSUE THREAD

**Issue by jettro** [elastic/elasticsearch#16819]
**Elasticsearch version**:
3.0.0-SNAPSHOT

The documentation for grok processor in ingest documentation has an error in the sample:
```
{
  "description" : "...",
  "processors": [
    {
      "grok": {
        "match_field": "message",
        "match_pattern": "%{IP:client} %{WORD:method} %{URIPATHPARAM:request} %{NUMBER:bytes} %{NUMBER:duration}"
      }
    }
  ]
}
```
The fields match_field and match_pattern should be _field_ and _pattern_

The _Table 6. Grok Options_ has the same problem, the field names need to be changed the same way.

This is the file I am talking about:
https://github.com/elastic/elasticsearch/blob/master/docs/reference/ingest/ingest-node.asciidoc

**Comment by martijnvg** [comment]
@jettro Thanks for raising this documentation error. It is fixed now.
