### ISSUE TITLE
Elasticsearch logging improvements

### ISSUE THREAD

**Issue by Revan007** [elastic/elasticsearch#16820]
Hello,

Right now if you enable Elasticsearch slow log from config - elasticsearch.yml or through api call, it will generate the logs on the data node for queries that take more then 1 second (if set like this) in ES_index_search_slowlog.log.
The problem is that it will generate these logs on the data nodes where the query hits, so you have to check each nodes to see them If you have 50 data nodes this can be quite painfully.
What we need is for the these logs to be generated at the node the request is sent to ( client node for example)  and the logs should also include the ip of the machine the call was made from.

I believe this should be implemented as it will make it much easier to debug.

***I know you could manually collect all the logs and use nginx proxy in front to catch the ip and then concatenate all of them.  But why do all of this ? ****

**Comment by jasontedor** [comment]
Duplicates #9669

**Comment by Revan007** [comment]
If you could please read my issue you will see that I ask more than in the topic you pointed me to.  I have also sent you an e-mail 10 days go and still have not received an answer ...

**Comment by clintongormley** [comment]
@Revan007 please do not email people directly.  It is really bad form
