### ISSUE TITLE
transport client document insert with version 1.5  string is splitting with space.

### ISSUE THREAD

**Issue by Shashi-GS** [elastic/elasticsearch#16823]
elastic search transport client document insert is splitting the word with space.
e.g., Sachin Tendulkar is splitted as Sachin and Tendulkar two words. When we query I am getting the first word only.

Please let me know how to avoid this?

**Comment by javanna** [comment]
Please join us on our [discuss forum](https://discuss.elastic.co/) where we can properly answer any question you might have. We like to keep github reserved for bugs or feature requests rather than questions. Thanks for your cooperation!

**Comment by Shashi-GS** [comment]
Sure, thank you.
