### ISSUE TITLE
Investigate removing interning in ESLoggerFactory

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#16831]
**Describe the feature**:
While reviewing #16703 we noticed that ESLoggerFactory interns the logger name and prefix. We're not quite sure why because it didn't have any comments. It probably doesn't hurt anything but it doesn't seem all that useful either. This is a note that we should look into removing that interning.

**Comment by jasontedor** [comment]
This interning had a place previously. Now however, we associate with the prefix a marker. All that matters here is that we share the same marker across loggers with the same prefix. As such, the interning is no longer needed. I opened #29031.
