### ISSUE TITLE
Refuse to start if logging doesn't configure

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#16836]
Right now if Elasticsearch fails to configure logging log4j just outputs some message and we plow ahead. We need to notice this and fail hard. We've already removed some code that allows us to move forward if we fail to configure log4j (https://github.com/elastic/elasticsearch/commit/9c259aca413f904fcc31d959ab54a6ea8432404a) but we need tests that Elasticsearch dies when the log configuration is totally broken. Without a test that we run consistently we're as likely as not to still allow some broken log configuration to make it through. This feels like a fairly strait forward thing to test in the vagrant infrastructure or in some smoke test.

**Comment by jasontedor** [comment]
We do this now since #24076, failing startup if we detect any error messages on the status logger.

Relates #24076, relates #26209
