### ISSUE TITLE
Query on a field that is also the index type name can search on any other field

### ISSUE THREAD

**Issue by ebuildy** [elastic/elasticsearch#16855]
**Elasticsearch version**: 1.7.* (seem fixed from 2)

**JVM version**: Java 1.8

**OS version**: Any

**Description of the problem including expected versus actual behavior**: If you do a query against a field (term, match) that is also the type name of the index, another field is matched. Query on a multi-field field. (Hard to explain, see the gist)

**Steps to reproduce**: I made a simple gist: https://gist.github.com/ebuildy/72fade2e26dea91256d6
 1. Create an index, with a multi-field field (https://www.elastic.co/guide/en/elasticsearch/reference/current/_multi_fields.html)
 2. Add a document with a single field
 3. Query against a field that is the index type name (in my GIST: "title", I query against title.simple)
 4. The document is matched but does not contain any field "title"

**Provide logs (if relevant)**:

Explains debug shows "weight(alias.simple:coca in 0)" whereas I specify the field "title" in the query.

It seems fixed from 2.0, but I am curious to know the reason!

**Comment by rjernst** [comment]
In 1.x, there was a feature that attempted to disambiguate fields of the same name in different types. That is the feature you are hitting here, and it was removed in 2.0. See #8872.
