### ISSUE TITLE
ElasticSearch date rangequery affected by TimeZone

### ISSUE THREAD

**Issue by sosoda** [elastic/elasticsearch#16879]
I tried for several times,but still confused.
At first the mapping of date field is 
{
    "createdAt" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss"
          },
}
when I query with java, I use SimpleDateFormat like 

    SimpleDateFormat smf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
    String format = smf.format(date);

the result is affected by TimeZone.
And I try store the date field with format like "yyyy-MM-dd hh:mm:ss Z"  and without format.In this time , I get the correct result. So what happend in the format thing?

**Comment by jasontedor** [comment]
This is neither a bug report nor a feature request which is what Elasticsearch GitHub issues reserved for. There is a community of people at the [Elastic Discourse forums](https://discuss.elastic.co) that would be happy to help you.
