### ISSUE TITLE
Deprecated stuff should show up as deprecated in the index

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#16888]
Right now the index on the right hand side of the docs page contains all the deprecated stuff on the same level as the non-deprecated stuff. It should really be marked as deprecated somehow in the index. See https://imgur.com/qiDPRcn for a nice picture of it.

It'd be nice for someone who is just coming to Elasticsearch for the first time to be able to skip the deprecated stuff entirely but I don't see how that is possible without a crazy maintenance burden. Maybe it is enough to just mark the deprecated stuff in the index as deprecated and sort it to the bottom of the lists. Or something. I dunno.

Reported [here](https://www.reddit.com/r/elasticsearch/comments/48h34n/elasticsearch_rest_api_inconsistent/).

**Comment by debadair** [comment]
Opened as a doc infra issue: https://github.com/elastic/docs/issues/325
