### ISSUE TITLE
Port delete by query to reindex's infrastructure

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#16883]
We should port delete by query to reindex's infrastructure. It'll "automatically" get support for cancelation and reading it's status. Since the status includes enough data to calculate a completion percentage, I think this is a win. It will remove support for the timeout parameter, I think. It isn't really needed when you can just cancel the request with task management though.

This also means it'll move into the reindex module and be available in a standard installation.

Sound like a good idea?

**Comment by s1monw** [comment]
I think this sounds like a good idea to me

**Comment by dadoonet** [comment]
++

**Comment by tlrx** [comment]
+1

I'd like to give it a try

**Comment by nik9000** [comment]
Have at it!

**Comment by yehosef** [comment]
+1
