### ISSUE TITLE
Limit query's docs use filtered query

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#16887]
The filtered query is deprecated but it is still used in the docs for the limit query:
https://imgur.com/mZSsN0r

I suspect this is a leftover from the great filter/query merged of 2.0.

Reported [here](https://www.reddit.com/r/elasticsearch/comments/48h34n/elasticsearch_rest_api_inconsistent/).

**Comment by nik9000** [comment]
Filtered is actually used all over the docs - I imagine we should remove it everywhere but it's page.

**Comment by clintongormley** [comment]
Actually, it is used only on limit/and/or, all of which are deprecated.  In master, these are gone.
