### ISSUE TITLE
Add Triangle and Hex Grid Encoding for GeoGridAggregator

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#16895]
A triangular tessellation based `geo_point` encoding supports aggregating on grids other than basic geohash (e.g., triangular, hex). These aggregations provide better spatial visualization but are also commonly used in GIS analysis applications due to their equal area characteristics. This feature issue adds a `grid_type` parameter to `GeoHashGridParams` (which will likely need to be refactored to `GeoGridParams`) to allow users to specify different grid types such as `geohash`, `triangular`, `hexagonal`. We should also investigate generalizing `geohash_grid` aggregation to a more general `geo_grid` aggregation so we can provide different grid definitions.

**Comment by djminkus** [comment]
Is a solution for this still desired?

**Comment by thomasneirynck** [comment]
Would this include also quad_keys, similar to Bing Maps (https://msdn.microsoft.com/en-us/library/bb259689.aspx)?

The tile-pyramids employed by most mapping services (Web Mercator, 2x2 division) are easier to work with from a front-end perspective than geohash-grids due to the uniform scaling horizontal/vertical across zoom levels.

So something like https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geohashgrid-aggregation.html, but bucketing by tile in the quad-tree.

**Comment by jpountz** [comment]
FWIW I got a user asking for this to me in person recently, the main motivation being to have equally-sized cells.

**Comment by DaveCTurner** [comment]
Relates https://github.com/elastic/elasticsearch/issues/28121

**Comment by nyurik** [comment]
I just submitted a pull request #30231 with [plus code](https://plus.codes/) support - I think that PR can be used as a step towards multi-hashing support.

**Comment by consulthys** [comment]
It would definitely be a good idea to support hexagonal partitioning.
See Uber's open-sourced h3 project (Hexagonal Hierarchical Geospatial Indexing System): https://github.com/uber/h3

Explanations with examples here: https://eng.uber.com/h3/

**Comment by talevy** [comment]
Update here:

> We should also investigate generalizing `geohash_grid` aggregation to a more general `geo_grid` aggregation so we can provide different grid definitions.

Recently, changes were made to make geogrid aggregations really easy to create. This was done in favor of building one mega-geo-grid aggregation with different types due to concerns over overloading of the `precision` field, since precision means something different bucketing algorithm.

geotile_grid was introduced for support for web-xyz-tiling of geopoints.

**Comment by nyurik** [comment]
From a discussion, there is a [geohex.net](http://geohex.net/) and a related
[java port](https://github.com/chsh/geohex4j/blob/master/src/main/java/org/geohex/geohex4j/GeoHex.java).  Also, per @talevy above, i think we should update the issue's main description, e.g. summarize the changes required, benefits, and relevant libraries/specifications as individual sections to avoid digging through comments.

**Comment by zakjan** [comment]
Hexagonal geo aggregation (Uber H3) support in ES would be a great feature, equal area buckets help with data visualization UX.

**Comment by consulthys** [comment]
> From @consulthys:
> It would definitely be a good idea to support hexagonal partitioning.
> See Uber's open-sourced h3 project (Hexagonal Hierarchical Geospatial Indexing System): https://github.com/uber/h3
> 
> Explanations with examples here: https://eng.uber.com/h3/

> From @zakjan:
> Hexagonal geo aggregation (Uber H3) support in ES would be a great feature, equal area buckets > help with data visualization UX. Is it on roadmap?

For those who are interested, I've created an Ingest Processor plugin for generating H3 indexes at specified resolutions out of geo-location fields.

The repo is available here: https://github.com/consulthys/elasticsearch-ingest-h3
It works on Elastic Cloud as well!

**Comment by nyurik** [comment]
I did a bit of QGIS-based prototyping to see what it would actually look like as one would pan/zoom:
[![hex grid](https://img.youtube.com/vi/cSC3cHMmrqk/0.jpg)](https://www.youtube.com/watch?v=cSC3cHMmrqk)

**Comment by consulthys** [comment]
Nice @nyurik !!
You can also try it out live on https://www.tophap.com/ and see how it looks like ;-)
<img width="1071" alt="tophap_h3" src="https://user-images.githubusercontent.com/1280019/71152947-2277a200-2238-11ea-8f2f-309b50a7d60e.png">

**Comment by nyurik** [comment]
Thanks for the link! The site looks really nice.  One of the primary reasons I did it is to see what it would look like on low zooms - how much of a tile warp would happen if someone attempted to analyze planet-scale data.

**Comment by wchaparro** [comment]
Completed GeoGridAggregation on H3 hex grid - we'll open a new issue if we want to support a new grid.
