### ISSUE TITLE
failed create index on 2.2.0

### ISSUE THREAD

**Issue by HowookJeong** [elastic/elasticsearch#16897]
**Elasticsearch version**: 2.2.0

**JVM version**:
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

**OS version**:
Darwin imac-2.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:
I just create index by rest api.
[Failed Index name]
$ curl -XPUT "http://localhost:9200/bulk-indexer-config" -d'
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 1,
    "index": {
      "refresh_interval": "5m"
    }
  },
  "mappings": {
    "default": {
      "_all": {
        "enabled": false
      }
    }
  }
}'
and then i got some error.
But It is ok that I changed name of index which is bulk_indexer_config from dash to under bar.

[Successful Index name]
$ curl -XPUT "http://localhost:9200/bulk_indexer_config" -d'
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 1,
    "index": {
      "refresh_interval": "5m"
    }
  },
  "mappings": {
    "default": {
      "_all": {
        "enabled": false
      }
    }
  }
}'

**Steps to reproduce**:
 1. If you create index with my script, you can show the error.
 2.
 3.

**Provide logs (if relevant)**:
==== error logs ====
{
  "error" : {
    "root_cause" : [ {
      "type" : "invalid_type_name_exception",
      "reason" : "mapping type name [_all] can't start with '_'"
    } ],
    "type" : "mapper_parsing_exception",
    "reason" : "Failed to parse mapping [_all]: mapping type name [_all] can't start with '_'",
    "caused_by" : {
      "type" : "invalid_type_name_exception",
      "reason" : "mapping type name [_all] can't start with '_'"
    }
  },
  "status" : 400
}

**Describe the feature**:
I think, This is error for meta field mapper.
Would you solve this problem?

Thanks.

**Comment by clintongormley** [comment]
Hi @HowookJeong 

Your recreation of the problem works just fine - it happily creates the index.  The error message you show indicates that your request was incorrect and you had the `_all` field just under `mappings` instead of where you show it in your request.

Please try again and, if you can still create the issue, paste the actual requests that you ran.

**Comment by HowookJeong** [comment]
I tried create index.

Case 1) failure
$ curl -XPUT "http://localhost:49200/hello-world?pretty" -d'
> {
> "settings": {
> "number_of_shards": 1,
> "number_of_replicas": 1,
> "index": {
> "refresh_interval": "5m"
> }
> },
> "mappings": {
> "_all":{
> "enabled":false
> },
> "default": {
> }
> }
> }
> }'
{
  "error" : {
    "root_cause" : [ {
      "type" : "invalid_type_name_exception",
      "reason" : "mapping type name [_all] can't start with '_'"
    } ],
    "type" : "mapper_parsing_exception",
    "reason" : "Failed to parse mapping [_all]: mapping type name [_all] can't start with '_'",
    "caused_by" : {
      "type" : "invalid_type_name_exception",
      "reason" : "mapping type name [_all] can't start with '_'"
    }
  },
  "status" : 400
}

Case 2) success
$ curl -XPUT "http://localhost:49200/hello-world?pretty" -d'
> {
> "settings": {
> "number_of_shards": 1,
> "number_of_replicas": 1,
> "index": {
> "refresh_interval": "5m"
> }
> },
> "mappings": {
> "default": {
> }
> }
> }
> }'
{
  "acknowledged" : true
}

Would you explain how i set _all configure or where i can set it?
Thanks.

**Comment by clintongormley** [comment]
@HowookJeong I copied and pasted your curl commands and they worked correctly on 2.2.0.  I am unable to recreate this problem

**Comment by clintongormley** [comment]
if you are trying to disable the `_all` field by default for all future types in the same index, the syntax is:

    curl -XPUT "http://localhost:9200/hello-world" -d'
    {
      "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 1,
        "index": {
          "refresh_interval": "5m"
        }
      },
      "mappings": {
        "_default_": {
          "_all": {
            "enabled": false
          }
        }
      }
    }'

To disable it for a particular type (eg `some_type`) then it'd be:

    curl -XPUT "http://localhost:9200/hello-world" -d'
    {
      "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 1,
        "index": {
          "refresh_interval": "5m"
        }
      },
      "mappings": {
        "some_type": {
          "_all": {
            "enabled": false
          }
        }
      }
    }'

**Comment by clintongormley** [comment]
You should head over to the forum to ask questions like these: https://discuss.elastic.co/ - there's a great community of people who will help.

The github issues list is reserved for bug reports and feature requests only.

thanks
