### ISSUE TITLE
Glossary should contain query and filter

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#16891]
The [glossary](https://www.elastic.co/guide/en/elasticsearch/reference/current/glossary.html) should contain the terms `query` and `filter`. Both of these are used extensively in the documentation and folks who wander to the glossary aren't going to know the difference. [This](https://www.elastic.co/guide/en/elasticsearch/guide/current/_queries_and_filters.html) page in the guide is helpful but I get the sense people don't always find their way there.

**Comment by jasontedor** [comment]
@refactormyself The PR (#26353) that you reference was never merged. If you want to reopen yours, someone will review it.

**Comment by refactormyself** [comment]
PR #29127 now openend

**Comment by cbuescher** [comment]
Closed by #29127, thanks @refactormyself
