### ISSUE TITLE
Can we avoid calling File.exists for every green shard on every routing table change?

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#16892]
When shard a relocated away from nodes, we need to delete the local copy. This is done by the `IndicesStore` class and it's super careful for obvious reasons.

The current logic is to go through the following for every cluster state published with a routing table change (for every shard):
1) If the shard is not green, skip.
2) If the shard is assigned locally, skip.
4) If the shard is green call file.exist to see if there is a local copy. If not skip.
5) Send requests to all nodes holding the shard and ask them if they still have it open.
6) When all nodes respond with no error _and_ nothing has happened in the mean time (i.e. no new cluster state was process), delete the shard after acquiring  the local shard lock.

It turns out that (3) can taking serious time (>30s in aggregate) for people with lots of shards (we saw 13K primaries). This delays cluster state processing and brings the cluster into trouble.

To fix this we can't simply check if the published CS in question actually removes a shard from the local node, because of (6) which relies on any new CS to trigger a new check.

We can be more relaxed in 6 and delete anyway _if_ we can get the lock (we already do it on the cluster state thread).

An alternative is to have a local in memory map that remembers whether a shard was checked locally and no folder was found. That map can be reset whenever a shard is introduced to the node.

Thoughts?

**Comment by dakrone** [comment]
@bleskes can you link to where in the code we do the check you want to remove?

**Comment by bleskes** [comment]
@dakrone I meant [this](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/indices/store/IndicesStore.java#L253) . Note that it's not just removing this check but also checking that there was a change in allocation of the current node (o.w. will keep doing that file exists check).

**Comment by ywelsch** [comment]
Fixed by #21438
