### ISSUE TITLE
Reindex should support throttling

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#16912]
The last big feature in the "initial" phase of reindex is throttling. This ticket should track it. Right now I have no idea how to implement it or what form it'll take. But we'll need it.

**Comment by nik9000** [comment]
This just missed being closed by the relevant PRs. These are the hashes in master:
da96b6e41d1b44eec8bfa170d8d0d8647e57dfef - basic throttling support
78ab6c5b7ff82da7f7d3c059b4a43d80bad188fb - dynamic rethrottling

**Comment by clintongormley** [comment]
@nik9000 This can be closed then, no?
