### ISSUE TITLE
Scroll docs don't mention that scroll is cleared once exhausted

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch#16929]
The documentation for `clear_scroll` [0](or scroll in general) doesn't mention that the scroll is cleaned up automatically when scroll is exhausted leading to some confusion whther a call to `clear_scroll` is required after iterating over all documents.

0 - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html#_clear_scroll_api

**Comment by jimferenczi** [comment]
The scroll is not cleaned up automatically, it will be removed when the timeout is reached. So `clear_scroll` is not mandatory but it can help to call it explicitly. 
@jpountz  any reason why the scroll is not cleared automatically (I tested on 2.x only) ?

**Comment by jpountz** [comment]
@jimferenczi I think it makes it more user-friendly: it is easier to remember that the scroll should be always cleared than that the scroll should only be cleared if not all documents were retrieved?

**Comment by nik9000** [comment]
The rule reindex and I follow is "if the last request returned a scroll ID you need to clear it". If the last request didn't return one we wouldn't clear it. I suspect this is pretty common.

**Comment by HonzaKral** [comment]
Well, the purpose of the scroll is to iterate over all the documents so, if all goes well, it should be exhausted in majority of cases. Making it so it is cleared automatically is then definitely more user friendly and should conserve resources.

**Comment by jasontedor** [comment]
> I think it makes it more user-friendly: it is easier to remember that the scroll should be always cleared than that the scroll should only be cleared if not all documents were retrieved?

I like that way that @jpountz is looking at it here. To add, closing automatically upon completion of the scroll would be in opposition to other resources that require explicit close whether or not you exhaust them (file handles, result sets in JDBC, etc.). This is just something that developers should be use to and I do not think that we should go against convention here.

**Comment by rjernst** [comment]
Thinking about it from a developers perspective, it is also easier and less error prone to always clear. Having a clear in something like a finally block is simpler than a user having to check "did i exhaust? if not, also send this clear".

**Comment by HonzaKral** [comment]
That might be so for Java and for interacting with a database over a low-level API, where you could also argue it is very common to prepare statements/queries etc.

Vast majority of elasticsearch users interact with it using the http api where the conventions are dramatically different and very seldom do you care about server-side resources, assuming the server is a black box. Not to mention that many languages people use with elasticsearch don't have a super easy try/finally construct like you are used to.

I see no reason not to clear automatically assuming we have the information we have reached the end of a scroll, we can still recommend it as a best practice to always clear, but it seems a bit weird to not do something that helps the users just to force them to do the right thing.

**Comment by clintongormley** [comment]
> The scroll is not cleaned up automatically, it will be removed when the timeout is reached. So clear_scroll is not mandatory but it can help to call it explicitly. 

Actually, this is not quite correct.  Scrolls ARE cleared automatically when `search_type=scan`, they are not cleared automatically for non scanning searches including `sort:_doc` (the replacement for scanning).

I think that all scrolls should be automatically expired once they are exhausted.  From a client perspective, why should I need to send an extra request over the network after I've finished retrieving all my docs, and wait for the response?  It just slows things down for me.

Clients using scroll helpers (available in some/most? of the clients) don't need to think about whether they should clear the scroll or not - the scroll helper should handle these things automatically.  And if not using a helper, all they need to do is to always send the clear scroll request and ignore 404 responses.

**Comment by kjendrzyca** [comment]
> Scrolls ARE cleared automatically when search_type=scan

I think this info should be added to the `scroll` documentation. This issue is the only place where I could find the infromation why I'm getting `Not Found` when trying to close the scoll.

**Comment by debadair** [comment]
The scan search_type is obsolete.
