### ISSUE TITLE
Es.index.read.missing.as.empty is not working with multiple indices

### ISSUE THREAD

**Issue by DynamicScope** [elastic/elasticsearch#16924]
**Elasticsearch version**: 2.2.0

**JVM version**: 1.8.0_73

**OS version**: Linux 4.1.17-22.30.amzn1.x86_64

**Description of the problem including expected versus actual behavior**:
This Issue has been discussed [here](https://discuss.elastic.co/t/es-index-read-missing-as-empty-seems-not-working-with-multiple-indices/42612/1).

**Comment by javanna** [comment]
Wrong project, I think the issue should be raised here instead: https://github.com/elastic/elasticsearch-hadoop . Thanks!
