### ISSUE TITLE
hi,t meet a problem

### ISSUE THREAD

**Issue by lmx1989219** [elastic/elasticsearch#16947]
![image](https://cloud.githubusercontent.com/assets/9464485/13520251/b8cd9d26-e219-11e5-9168-e1aa831200e5.png)
why es parse log level as a int value?
if i change the log level to int value and this problem is resolved,but not my need.

**Comment by javanna** [comment]
HI @lmx1989219 please join us at https://discuss.elastic.co/ so we can properly answer any of the questions you might have. We'd like to keep github reserved for bugs and feature requests. Thanks!
