### ISSUE TITLE
Add `T` (on top of `:`, `-`, and `/`) as a way to pre detect of a string is a date for dynamic date formats

### ISSUE THREAD

**Issue by kimchy** [elastic/elasticsearch#1694]

**Comment by jpountz** [comment]
Removing the stalled label as #6277 is fixed now.

**Comment by jpountz** [comment]
Discussed in FixitFriday: we might want to remove this list of characters entirely and test the list of dynamic date formats on every unmapped field. This sould fix #10961 as well. Performance is not a concern as mappings are expected to converge quickly as mode documents are added.
