### ISSUE TITLE
Installing river-jdbc via command line fails, file not found on elastic's servers.

### ISSUE THREAD

**Issue by GeorgeL9** [elastic/elasticsearch#16957]
**Elasticsearch version**:
2.2.0
**JVM version**:
8
**OS version**:
10.11.2 El Capitan
**Description of the problem including expected versus actual behavior**:
Installing plugin river-jdbc fails. 
**Steps to reproduce**:
 1. Run command ./bin/plugin install river-jdbc --verbose

**Provide logs (if relevant)**:
```
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/river-jdbc/2.2.0/river-jdbc-2.2.0.zip ...
Failed: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/river-jdbc/2.2.0/river-jdbc-2.2.0.zip]; nested: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/river-jdbc/2.2.0/river-jdbc-2.2.0.zip]; 
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information
```

**Comment by jasontedor** [comment]
Rivers were deprecated and removed from Elasticsearch 1.5.0 to Elasticsearch 2.0.0 in #10345. Can I suggest the [Logstash JDBC input plugin](https://github.com/logstash-plugins/logstash-input-jdbc) as an alternative?
