### ISSUE TITLE
Option to remove indices from target cluster for previously deleted indices upon snapshot restore

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#16958]
**Describe the feature**:

Provide an option for target cluster to be aware of previously deleted indices when restoring snapshots so that deleted indices from the source cluster will cause the target cluster to also remove its indices upon restoring.   This is helpful when attempting to "mirror" clusters without having to keep track of deleted indices outside of the snapshot restore process.  The following is one such use case:

```
1. Take snapshot 1 in Active cluster

2. Close all indices in Passive cluster

3. Passive cluster restores from snapshot 1

4. Remove index1 from alias1 in Active cluster

5. Delete index1 from Active cluster

6. Take snapshot 2 in Active cluster

7. Close all indices in Passive cluster

8. Passive cluster restores from snapshot 2
```

The result is that index1 is closed and remains in alias1 in the Passive cluster after step 8, which would cause problem when the Passive cluster becomes the Active cluster (DR) for if someone then tries to query using alias1 (this will result in an IndexClosedException).  The obvious workaround here will be to manually manage deleted indices by keeping track of what indices have been deleted from Active and delete same indices from the Passive cluster.

The request here is to provide a configurable option for admins to specify whether they want the snapshot restore to automatically remove previously-deleted indices from the target cluster.

**Comment by clintongormley** [comment]
In other words, an option to delete all indices that aren't in the snapshot currently being restored.

**Comment by ywelsch** [comment]
This feature request is interesting but since its opening we have not seen enough feedback that it is a feature we should pursue. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).
