### ISSUE TITLE
Document index.merge.scheduler.max_thread_count again?

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#16961]
**Elasticsearch version**: 2.x

**Description of the problem including expected versus actual behavior**:

It looks like we are still recommending `index.merge.scheduler.max_thread_count: 1` to be set for HDDs even with the auto merge throttling functionality in 2.x.  Since we have removed the "merge" module section from the docs completely starting in 2.0, it will be nice to add this particular recommendation back to the reference guide (somewhere). 

>index.merge.scheduler.max_thread_count
The maximum number of threads that may be merging at once. Defaults to Math.max(1, Math.min(3, Runtime.getRuntime().availableProcessors() / 2)) which works well for a good solid-state-disk (SSD). If your index is on spinning platter drives instead, decrease this to 1.

**Comment by clintongormley** [comment]
Makes sense to me.  @mikemccand ?

**Comment by mikemccand** [comment]
+1

But can we perhaps put it on a new doc page "If you use spinning disks..." instead of bringing "merge settings" page back to life for just this one setting?
