### ISSUE TITLE
Update groovy api docs to not mention node client

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#16960]
I noticed while working on the `node.client` removal, that the groovy api docs mention as the only way to create a client, the use of a node client, which we just took out of the java api docs. We should fix that, hopefully the groovy api can make use of the transport client instead.

**Comment by clintongormley** [comment]
@pickypg can this be closed?

**Comment by pickypg** [comment]
Yep. Deleted the file entirely with 3ca02d647eafcd875802109fcbd009e80d37e5bb
