### ISSUE TITLE
Cannot filter on _parent field

### ISSUE THREAD

**Issue by mesztam** [elastic/elasticsearch#16969]
Hi,

in 2.2, I cannot filter on the _parent field anymore. E.g. the query:

```js
 "query": {
    "bool": {
      "filter": [
              { "terms": { "_parent": [ [ "0#2998", "0#3029" ] ] }}
            ]
          }
        }
```

does not return anything for me, while the same with `_routing` instead of `_parent` does.
In the result I can clearly see, that the content of the `_parent` field is correct (in this case, has the same value as `_routing`). Also, in 1.x filtering on `_parent` worked.

Regards,
Tamas

**Comment by clintongormley** [comment]
Hi @mesztam 

It works for me in 2.2:

    PUT t 
    {
      "mappings": {
        "parent": {},
        "child": {
          "_parent": {
            "type": "parent"
          }
        }
      }
    }
    
    PUT t/parent/1
    {}
    
    PUT t/child/2?parent=1
    {}
    
    GET t/_search
    {
      "query": {
        "terms": {
          "_parent": ["parent#1"]
        }
      }
    }
    


However, you shouldn't rely on this working in the future. This behaviour will be removed in 5.0.  See https://github.com/elastic/elasticsearch/issues/5399#issuecomment-156814603 for more

Use a `has_parent` query instead

**Comment by martijnvg** [comment]
@mesztam Or from 5.0 you can use the new `parent_id` query, to find child documents with a specific parent id value.

**Comment by Ragazzo** [comment]
@martijnvg can you given an example of such query? would be very usefull, since docs are very unclear about it.

**Comment by martijnvg** [comment]
@Ragazzo The `parent_id` query is described here: https://www.elastic.co/guide/en/elasticsearch/reference/5.4/query-dsl-parent-id-query.html

**Comment by Ragazzo** [comment]
@martijnvg I saw that, but how can I query all childs by several parents ids? I mean `parent_id IN (1,2,3,4,5)`? Docs only describe 1 to 1 match.

**Comment by martijnvg** [comment]
@Ragazzo You can wrap multple `parent_id` queries in the should clause of a `bool` query:
https://www.elastic.co/guide/en/elasticsearch/reference/5.4/query-dsl-bool-query.html

**Comment by Ragazzo** [comment]
@martijnvg but I am quering by parent table, all what I want to do is get parents and childs, based on childs parent_id. Is it possible?
