### ISSUE TITLE
Built-in sorting in _cat APIs

### ISSUE THREAD

**Issue by bobrik** [elastic/elasticsearch#16975]
While using `sort(1)` is great and all, more often than not I find myself using browser for `_cat` APIs. It's easy to bookmark and reuse.

Unfortunately, `/_cat/indices?v` and similar endpoints have undefined order of rows and it is not always convenient. Moreover, `?v` makes using `sort(1)` less convenient, since header is sorted too.

I suggest adding another parameter to sort on any column list. It would accept the same thing as `h`. Example request to sort on index time:

```
curl -s 'http://127.0.0.1:9200/_cat/indices?v&h=index,pri,docs,indexing.index_time&s=indexing.index_time'
```

**Comment by clintongormley** [comment]
Nice idea.  Sort should be ascending by default, and accept `:desc` to invert the order.
