### ISSUE TITLE
Cluster/Index Shard Allocation Filtering Docs should mention you can use comma-separated values for cluster.routing.allocation.exclude.*

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch#16997]
To remove all ambiguity, it should be mentioned that the `cluster.routing.allocation.exclude.*` settings also accept comma-separated values in addition to a single-value or a wildcard expression.

**Comment by clintongormley** [comment]
The docs say:

> Assign the index to a node whose {attribute} has none of the comma-separated values.

How would you suggest improving it?  Want to send a PR?

**Comment by joshuar** [comment]
I completely missed that because I see an example first thing using a non-pluralised term `_ip` and a single IP address, hence the assumption is it is single valued.  Maybe we should start with what values are supported, then put both the examples at the end?

Can submit a PR for this if that sounds good?

**Comment by clintongormley** [comment]
With pleasure

**Comment by joshuar** [comment]
Merged #20958
