### ISSUE TITLE
Next scroll id and number of hits in response headers for search/scroll api

### ISSUE THREAD

**Issue by epixa** [elastic/elasticsearch#16993]
**Describe the feature**:

If the next scroll id and total number of hits in the current response were included as response headers, it would make consuming the scroll api without buffering entire responses much simpler.

This is useful when using the scroll api to retrieve a large number of documents without buffering each response from elasticsearch in memory.  At the moment, if you want to do this, you have to extract the next scroll id and determine if there are any hits in the current response while parsing the json body as a stream.  This is exactly what we're doing with the Kibana csv export functionality, but there's additional complexity in the implementation as we need to make sure to properly manage backpressure while extracting three different pieces of data from the json stream.

We don't want to buffer entire pages of responses in memory in case the documents are particularly large, but we're comfortable only buffering the response headers in memory to decide whether we need to keep scrolling after each request.  Then we just need to pipe the response body through a single transform stream to extract each hit.  I suspect the csv export implementation would be half the size with considerably less moving parts if this information were available as headers.

**Comment by clintongormley** [comment]
sounds like a good idea.  

One gotcha to be aware of: with `search_type: scan`, the first response you get back has no hits.  Scanning is deprecated in favour of `sort: "_doc"` which DOES return hits with the first response.

**Comment by epixa** [comment]
Thanks for the heads up. I wasn't even aware of the `search_type: scan` feature, so I guess I started doing this recently enough to avoid the old behavior.

**Comment by kubum** [comment]
Do you have any ideas about possible conventions for this type of response headers?

**Comment by epixa** [comment]
I don't know if there's any precedent of hypermedia api behaviors in elasticsearch, but how about this: instead of returning scroll id and hit counts in headers, what if each request returned the next scroll/search url (including scroll id parameter) in the "link" header? http://tools.ietf.org/html/rfc5988

I've seen this same convention in other rest-like https apis, like github's: https://developer.github.com/guides/traversing-with-pagination/

**Comment by epixa** [comment]
To clarify, in order to not return the current request's hit count as a header, I think it would need to only include the `link` header if there were actually more results to query.

**Comment by clintongormley** [comment]
I like the idea of using the `Link:` header.  It would need to be a relative URL, but that's allowed by the spec.

**Comment by epixa** [comment]
Actually, I gave it a little more thought, and I don't know if the `link` header is the best option for this.  The scroll id itself is actually used for *two* different api requests: retrieving the next results and clean up, so I think it would be best if the scroll id itself were returned as header rather than built into a url.

**Comment by epixa** [comment]
Unless we returning a clean up link as well...

**Comment by epixa** [comment]
As an alternative, this would work *very* nicely for us:

Response contains `ES-Scroll-Id` header if there are more results to retrieve.  It does not contain that header if there are no results.  Then we'd just grab that header whenever we see it and add a search function to the queue.

**Comment by lucianogreiner** [comment]
+1 on this feature.

We would like to have hits counting under Http Response Headers section to be able to perfom internal tracking on requester limits.

Was there any development on this issue? What would be the best place to start to create a plugin to support this feature?

Best regards

**Comment by burtonator** [comment]
+1 ... we really need the number of documents present in the current search result.. we need it for accounting on our end.

**Comment by alexbernotas** [comment]
+1 this is definetly a needed solution, it is really costly to iteerate and process results into memory if you want to paginate through 100mil+ results

is there an indication on someone accepting or starting to work on this feature? or is this posisble with count API?

**Comment by burtonator** [comment]
Thanks @clintongormley ... I opened this bug because we need this for production here at http://spinn3r.com ... 

We now have a custom plugin where we change the ES endpoints and have our own adapter to respond to HTTP results with the header.

**Comment by alexbernotas** [comment]
+1 this is definetly a needed solution, it is really costly to iteerate and process results into memory if you want to paginate through 100mil+ results

is there an indication on someone accepting or starting to work on this feature? or is this posisble with count API?

**Comment by dimitris-athanasiou** [comment]
+1 This has also made our lives harder while developing at prelert. I'll be happy to give it a go once we agree on the solution.

**Comment by clintongormley** [comment]
> Response contains ES-Scroll-Id header if there are more results to retrieve. It does not contain that header if there are no results. Then we'd just grab that header whenever we see it and add a search function to the queue.

@epixa this wouldn't be enough as we still need the scroll ID to clear the scroll.

Perhaps the Link header is the right one, we can provide one link for `next`, and use an [extension relation type](http://www.rfc-editor.org/rfc/rfc5988.txt) for the clear link.

One potential problem: scroll IDs which target many shards can be too long for the max header length on requests, I'm not sure if the same limit might apply on responses?

**Comment by dimitris-athanasiou** [comment]
> One potential problem: scroll IDs which target many shards can be too long for the max header length on requests, I'm not sure if the same limit might apply on responses?

Oh, right. Yes. Putting the scroll id in the header is just not going to work. The HTTP protocol does not specify a max size but most servers implement one, usually choosing either 8KB or 16KB. Both extremely low to accommodate a fat, juicy scroll ID. Forgot about that and how badly I've been bitten.

**Comment by epixa** [comment]
Ah, nuts!  I hadn't thought of that.  Total number of hits could still be useful, but the gain here is significantly diminished without being able to access both up front.

**Comment by talevy** [comment]
@epixa @clintongormley do we want to continue with this?

looks like this issue was opened requesting the doc-count to be easily accessed from within a plugin ( https://github.com/elastic/elasticsearch/issues/18312)

Since there is a concern that scroll-ids have the ability to grow larger than max-header-size, we 
are left with discussing the benefits of just adding the hit count to the response header.

Since adding the hits-count in the header seems trivial, should we just do it? It would potentially 
reduce the need to parse the body only to find out there are no hits?

**Comment by epixa** [comment]
@talevy I don't have strong opinions about this anymore. Without the scroll id, the utility of the feature is diminished a lot, since you really need to parse the body anyway. The hit count alone does make it a little easier to consume even still, but I leave it to the ES team to decide whether that is valuable enough to introduce.

**Comment by talevy** [comment]
ok, thanks @epixa.

Closing due to the outcome of our discussion above. If this request comes up again, always 
welcome to re-discuss!
