### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#17007]
Lucene now has sandbox support for IPv6 ([LUCENE-7043](https://issues.apache.org/jira/browse/LUCENE-7043)).  

> InetAddressPoint is 1-dimensional by nature: of course you can have multiple values per field, thats different. Since we prefix-compress values, we can just map IPv4 addresses to IPv6 space and it works for both types. This is consistent with what InetAddress does itself anyway.

We should look at what needs to be done to support IPv6 in Elasticsearch. We should add a new `ipv6` field which handles both IPv4 and IPv6.  

The only problem I can see is that users might expect to get an IPv4 address back (eg `192.168.1.5`) and instead it'd be returned as `0:0:0:0:0:ffff:c0a8:105`. Perhaps we should have an `ipv4` field as well that handles only IPv4 addresses, or add some option to render as IPv4 when possible?

**Comment by rmuir** [comment]
> The only problem I can see is that users might expect to get an IPv4 address back (eg 192.168.1.5) and instead it'd be returned as 0:0:0:0:0:ffff:c0a8:105. Perhaps we should have an ipv4 field as well that handles only IPv4 addresses, or add some option to render as IPv4 when possible?

That is not true. This is only something that happens internally in a BKD tree. Users do not see it. You do not "get things back" from that API. 

Also note: if you follow the RFC correctly, then calling https://docs.oracle.com/javase/7/docs/api/java/net/InetAddress.html#getByAddress%28byte[]%29 with a 128-bit mapped IPv4 address returns back a 32-bit Inet4Address: it does this round tripping for you. That is why all Query.toString()'s and so on work intuitively with the lucene support.

**Comment by jpountz** [comment]
While we don't have this issue with the bkd tree, I think it's something we will have to think about for doc values, eg. for computing the top ip addresses that hit a web server.

**Comment by rmuir** [comment]
its really not at all. just encode the same way, and use InetAddress to decode for any presentation form.

**Comment by rmuir** [comment]
Its this part that is super-important: calling https://docs.oracle.com/javase/7/docs/api/java/net/InetAddress.html#getByAddress%28byte[]%29 with a 128-bit mapped IPv4 address returns back a 32-bit Inet4Address: it does this round tripping for you

so if you want to display to the user in any way, make an InetAddress from the bytes. it does the right thing. 

Please don't make ipv4 vs ipv6 types or any other craziness when this all works exactly as the user expects using basic java apis!

**Comment by jpountz** [comment]
I agree there should not be two types and I'm not concerned about the Java API. The question was more about what we do on the rest layer eg. is it ok for aggs to render ip addresses differently from the way they were formatted at index time. I think it is, but it did not happen with the v4-only field so I think it's also important that we raise the question and document the behaviour.

**Comment by rmuir** [comment]
I don't think you guys get how the transition mechanism works inside the java InetAddress class. I encourage you to play with it.

**Comment by clintongormley** [comment]
> Please don't make ipv4 vs ipv6 types or any other craziness when this all works exactly as the user expects using basic java apis!

Relax, Rob.  The only reason I suggested it was because I was unaware of the information that you have provided. Thanks for the link.

Isn't it true though that if a user indexes an IPv4 address in IPv6 format, doc values will return the address in IPv4 format? (ie not what they indexed?).

**Comment by rmuir** [comment]
If someone supplies an ipv4 address (mapped or not), its an ipv4 address. thats what that reserved space in the ipv4 region is for. If someone supplies an ipv6 address, its an ipv6 address.

note that ipv6 addresses can be represented in many ways. i recommend emitting canonical representations. So if someone supplies `0:0:0:0:0:0:0:1` they can expect to get it back as `::1`.

Its always "what they indexed". its the same address. Its like returning `16.0` vs returning `16`. 

Please, lets not try to overcomplicate this. Its not complicated.

**Comment by clintongormley** [comment]
> Please, lets not try to overcomplicate this. Its not complicated.

I wasn't trying to overcomplicate it, I was trying to understand it.  Thank you for explaining.

**Comment by rmuir** [comment]
as far as docvalues, i would just use SortedSetDocValues class for internet addresses. This is critical for ipv6 data because (like the BKD tree) it will provide prefix compression. 

For network addresses, "range" operations are a common operation (e.g. cidr/prefix operations), so having ordinal indirection is not useless, and can speed things up.

**Comment by rmuir** [comment]
And for that to work, docvalues needs a little tweak before the compression will happen: we currently always 'bail' on prefix-compression for fixed-length data: https://github.com/apache/lucene-solr/blob/master/lucene/core/src/java/org/apache/lucene/codecs/lucene54/Lucene54DocValuesConsumer.java#L423-L425

that is not always the best tradeoff...

**Comment by rmuir** [comment]
We may even want to turn that logic off completely. basically that logic was originally added to "save space" (= save on addresses) before we had prefix compression at all...

Unfortunately, we really need to solve this to avoid "my ip address field quadrupled in size!"

**Comment by rmuir** [comment]
I opened https://issues.apache.org/jira/browse/LUCENE-7081
