### ISSUE TITLE
Consider adding RFC822 file type (email files) parser to the Tika processor

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#17004]
As a consequence of the clean up in the mapper attachments plugin (https://github.com/elastic/elasticsearch-mapper-attachments/issues/163) only few basic file types parsers have been kept around and for a good reason, as Tika tries to parse a very wide range of types.

I believe the .eml (rfc822) file type parser to be one of the basics and, if possible, to be added back on the list of allowed types (https://github.com/elastic/elasticsearch/blob/v2.2.0/plugins/mapper-attachments/src/main/java/org/elasticsearch/mapper/attachments/TikaImpl.java#L57-L71).

Attached is a sample email file that is using base64 already to encode the content of the file itself. With ES 2.1.2 (and mapper attachments plugin 3.1.2) using the following [gist](https://gist.github.com/astefan/3e4d357ebf472b6709af) and [taking a look at the indexed content and content_type](https://gist.github.com/astefan/ee3d71d029911adfe31e) would reveal the following:

```
            "fields": {
               "indexedBody.content_type": [
                  "message",
                  "rfc822"
               ],
               "indexedBody.content": [
                  "as",
                  "awesome",
                  "elasticsearch",
                  "is",
                  "lucene",
                  "well"
               ]
            }
```

With ES 2.2.0 and mapper attachments plugin, the same setup and query shows that the file type is not properly recognized anymore, the already base64 encoded text is not decoded properly and the .eml file is considered a simple text file:

```
            "fields": {
               "indexedBody.content_type": [
                  "1252",
                  "charset",
                  "plain",
                  "text",
                  "windows"
               ],
               "indexedBody.content": [
                  "1.0",
                  "6003.1",
                  "8",
                  "_part_0_663220121.1456846121442",
                  "alternative",
                  "base64",
                  "bcc",
                  "boundary",
.....
                  "multipart",
                  "plain",
                  "rwxhc3rpy3nlyxjjacbpcybhd2vzb21liq",
                  "subject",
                  "test",
                  "test.com",
...
               ]
            }
```

[test_mail_01.eml.txt](https://github.com/elastic/elasticsearch/files/163248/test_mail_01.eml.txt)

**Comment by clintongormley** [comment]
An email can of course contain files of any type, but we can restrict the parsing of email attachments to just known types.

**Comment by talevy** [comment]
@dadoonet do you know why we dropped support for this? Looks like there is an RFC822Parser present in Tika

**Comment by dadoonet** [comment]
I think it was probably due to some JarHell issues or may be Security Manager problems. Can t recall exactly.

**Comment by rjernst** [comment]
Adding tiki backends in the attachment processor has a non zero maintenance cost, especially when there are security manager permission hacks necessary. Given that cost, and the lack of additional interest in this after 2 years, I'm closing this issue.
