### ISSUE TITLE
Getting a null_pointer_exception when executing a distributed multi-term vector query

### ISSUE THREAD

**Issue by crjackso** [elastic/elasticsearch#17014]
**Elasticsearch version**:
2.2.0
**JVM version**:
1.8.0_72
**OS version**:
Ubuntu 14.04.4 LTS
**Description of the problem including expected versus actual behavior**:
I'm running the following query on a 3-node ES cluster running ES 2.2.0 on Microsoft Azure. When dfs is set to true, I get a null_pointer_description (demonstrated below). However, if I set dfs to false, I get term vectors. I'd really like to set dfs to true because I'd like to get term statistics for the entire index.

``` javascript
{  
    "ids" : ["AVM0c1e8FqhBZ7YfiHM8"],
    "parameters": {
        "fields": ["LongDescription"],
        "term_statistics": true,
        "field_statistics": true,
        "dfs": true
    }
}
```
The response I'm getting is:
``` javascript
{
  "docs": [
    {
      "_index": "my_index",
      "_type": "my_type",
      "_id": "AVM0c1e8FqhBZ7YfiHM8",
      "error": {
        "root_cause": [
          {
            "type": "exception",
            "reason": "failed to execute term vector request"
          }
        ],
        "type": "exception",
        "reason": "failed to execute term vector request",
        "caused_by": {
          "type": "null_pointer_exception",
          "reason": null
        }
      }
    }
  ]
}
```

**Provide logs (if relevant)**:

The original question, along with relevant logs, can be found [here](https://discuss.elastic.co/t/getting-a-null-pointer-exception-when-executing-a-distributed-multi-term-vector-query/43606/3).

**Comment by clintongormley** [comment]
Hi @crjackso 

DFS support has been removed from the termvector API.  See https://github.com/elastic/elasticsearch/pull/16452
