### ISSUE TITLE
Provide a way to tune the number of most frequently used filters in query cache

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#17016]
**Describe the feature**:

> The way it works is that Elasticsearch keeps track of the 256 most recently used filters, and only caches those that appear 5 times or more in this history. 

We currently tracks 256 in the history and caches only those that appear 5 times or more in the history, so it will end up caching maybe 50 or so distinct filters.  In a multitenant environment, there can easily be more than 50 distinct filters for each customer id, so it will be nice to provide a way to tune this based on the use case.

**Comment by polyfractal** [comment]
/cc @jpountz 

I skimmed LUCENE-6077 and see the frequency is slightly different depending on query type:  freq = 2 for "expensive to build" and "cheap to cache", while freq = 5 for everything else.  What kinds of queries fall into the freq=2 category?

**Comment by jpountz** [comment]
freq=2 is used for all queries that need to evaluate the documents that they match on the whole index regardless of whether they are intersected with a selective filter or not. So this includes for instance range, wildcard and prefix queries.

> In a multitenant environment, there can easily be more than 50 distinct filters for each customer id

I agree that we might want to consider increasing the size of the history, but I don't think caching term queries on customer ids would be very helpful: by nature an inverted index is a already a cache of matching documents for every possible term and Lucene makes sure that they can be decoded efficiently. Loading term queries in the query cache only duplicates parts of the inverted index in memory.

**Comment by colings86** [comment]
Is this issue still relevant?

**Comment by talevy** [comment]
Closing this since there has not been much feedback given in over a year. despite this issue being closed please feel free to leave feedback on the proposal (including +1s).
