### ISSUE TITLE
Wrong boost is applied when using query time boosting in the mapping

### ISSUE THREAD

**Issue by jimferenczi** [elastic/elasticsearch#17011]
Field boost mapping is now applied at query time. See https://github.com/elastic/elasticsearch/pull/16900

This causes problem when boost values of the same field within two types of the same index are different.
The following mapping:
````
PUT test?update_all_types=true
{
   "mappings": {
      "test1": {
         "properties": {
            "text": {
               "type": "string",
               "boost": 1
            }
         }
      },
      "test2": {
         "properties": {
            "text": {
               "type": "string",
               "boost": 2
            }
         }
      }
   }
}
```
... will always pick the first boost value for queries containing the text field no matter what types is queried:

````
GET test/test1/_validate/query?explain
{
   "query": {
     "match": {
         "text": "foo bar"
     }
   }
}

GET test/test2/_validate/query?explain
{
   "query": {
     "match": {
         "text": "foo bar"
     }
   }
}

GET test/_validate/query?explain
{
   "query": {
     "match": {
         "text": "foo bar"
     }
   }
}
`````

In order to fix this discrepancy we have two options:
- Remove the ability to define different boost values on the same field.
- Apply the boost depending on the type of the request. If no or multiple types are defined then the boost is ignored.

IMO we should go with the first option because it's the closest to what we had before with the index time boost even though we forbid a valid use case.

**Comment by rjernst** [comment]
boost should be on the MappedFieldType and the same across all document types.

**Comment by jimferenczi** [comment]
After chatting with @rjernst I realized that update_all_types updates all the types with the new value. This means that having multiple boosts for the same field name within the same index is not allowed.
Another thing that came up from the chat is that update_all_types should not be allowed on index creation.

**Comment by rjernst** [comment]
Just a note on `update_all_types` for index creation: IIRC, we allowed this because of the case where you are setting metadata mappers on index creation. Due to how document type mappings are parsed, we always start out with the defaults, and anything we parse is merged with the default. What we need is to not add the default metadata mappers until after parsing, when we are creating a new mapping type. It used to be difficult, but I think with recent changes this may be possible now.
