### ISSUE TITLE
date_detection not working with not_analyzed fields

### ISSUE THREAD

**Issue by palmerabollo** [elastic/elasticsearch#17012]
**Elasticsearch version**: 2.2.0

**JVM version**: Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

**OS version**: OSX 10.11.1

**Description of the problem including expected versus actual behavior**:

If you enable both `date_detection: true` and `index: not_analyzed` in a dynamic template, dates are not detected.

**Steps to reproduce**:
 1. Create a template with a PUT to `_template/reproducebug` and the following body (`date_detection: true` and `index:not_analyzed`):

```
{
    "template": "*",
    "mappings": {
        "_default_": {
            "date_detection": true,
            "_all": {
                "enabled": false
            },
            "dynamic_templates": [
                {
                    "template1": {
                        "mapping": {
                            "index": "not_analyzed",
                            "type": "{dynamic_type}"
                        },
                        "match": "*"
                    }
                }
            ],
            "properties": {
                "msg": {
                    "type": "string",
                    "index": "analyzed"
                }
            }
        }
    }
}
```

 2. Index the following document, that contains a ISO8601 date: `{"foo":"bar", "time":"2016-03-08T09:52:09.097Z"}`

 3. Check that the field time is indexed as a not_analyzed string.

**Provide logs (if relevant)**:
No relevant logs.

**Comment by clintongormley** [comment]
You're running into this: https://github.com/elastic/elasticsearch/issues/2401

If you change your template to use `"match_mapping_type": "*"` instead of `"match": "*"` it will work

**Comment by palmerabollo** [comment]
Yes, it worked. Thanks.
