### ISSUE TITLE
Add bytes and files progress to cat recovery

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#17022]
The cat recovery API does not output fields showing the in-progress bytes and files recovered (it only shows bytes and files percent). These fields should be added to the cat recovery API. Additionally, there is some inconsistency in the naming of the fields. Today we have:

`bytes`: bytes to be recovered
`total_bytes`: total bytes on disk
`bytes_percent`: percent of bytes to be recovered that have been recovered

`files`: files to be recovered
`total_files`: total files on disk
`files_percent`: percent of files to be recovered that have been recovered

`translog`: translog ops recovered
`translog_total`: total translog ops to be recovered
`translog_percent`: percent of translog ops to be recovered that have been recovered.

This means that:

`translog_percent = translog / translog_total`

but that

`bytes_percent != bytes / bytes_total`

and

`files_percent = files / files_total`.

Thus, we should add `bytes_recovered` and `files_recovered`, rename `translog` to `translog_ops_recovered` and rename `translog_total` to `translog_ops` and then it will be

`bytes_percent = bytes_recovered / bytes`,
`files_percent = files_recovered / files`

and

`translog_ops_percent = translog_ops_recovered / translog_ops`.

**Comment by bobrik** [comment]
Another little inconsistency: in `_cat/indices` sizes are human-readable by default and can be switched to bytes, in `_cat/recovery` it's always bytes.

**Comment by clintongormley** [comment]
@jasontedor note that this is a breaking change, so let's do it in 5.0

**Comment by jasontedor** [comment]
Closed by #17064
