### ISSUE TITLE
Multi-index expressions not respecting excludes

### ISSUE THREAD

**Issue by sergfed** [elastic/elasticsearch#17027]
**Elasticsearch version**:

2.2.0

**JVM version**:

1.8.0_73

**OS version**:

windows

**Description of the problem including expected versus actual behavior**:

Why multiple index request (https://www.elastic.co/guide/en/elasticsearch/reference/2.2/multi-index.html) behaviour is different for elastic v1.7 and elastic v2.x?

I have sevetal indexes test1, test2...
All my indexes have sata allocation, but one has ssd. So i make 
```
PUT http://localhost:9200/test10/_settings
{"index.routing.allocation.require.hdd_type" : "ssd"}
```
and then do
```
PUT http://localhost:9200/*,-test10/_settings
{"index.routing.allocation.require.hdd_type" : "sata"}
```
So in elastic v1.7 all worked right for me - all indexes except one have sata allocation,
But elastic v2.x makes ALL indexes sata allocation.

Documentation has not been changed from v1.x. But behaviour is different.

**Comment by clintongormley** [comment]
Confirmed bug from 2.0.0 onwards.  Simple recreation:

    PUT test1
    PUT test2
    PUT test10
    
The following expression resolves to all three indices:

    GET -test10,*/_validate/query?explain

While this expression resolves to `test1` and `test2` only.
    
    GET -test10/_validate/query?explain
