### ISSUE TITLE
Feature request: term prefix suggester

### ISSUE THREAD

**Issue by andrenarchy** [elastic/elasticsearch#17029]
**Describe the feature**: The term suggester should allow prefix suggestions in order to display suggestions for a partially written word.
## Example

Let's assume the following data is indexed:

```
{title: 'Krylov subspace methods'},
{title: 'SUPG methods for finite differences'},
```
- If a user types `su` we would like to display the suggestions `subspace` and `SUPG`.
- If a user types `subs` we would like to display the suggestion `subspace`.

Note 1: returning single terms is _not_ supported by the completion suggester – it returns the full title (or a configurable but fixed output).

Note 2: others tried to implement this with the `highlight` feature; see [here](https://discuss.elastic.co/t/need-advice-for-my-term-completion-feature/43683/3) and [here](http://stackoverflow.com/questions/23256635/elasticsearch-phrase-prefix-search-how-do-i-get-the-matched-phrase). Obviously, parsing the highlights is just a workaround. Maybe there exists another (less hacky) way to retrieve the matched terms from elasticsearch?

**Comment by basiclaser** [comment]
+1 !

**Comment by s1monw** [comment]
@mikemccand infix suggester on es anybody? :)

**Comment by clintongormley** [comment]
As I understand it, the analyzing infix suggester requires the index to be sorted in "score" order, ie best matches first.  This could clash with our plans to sort the index by _type to reduce sparsity.

**Comment by jimferenczi** [comment]
But the analyzing infix suggester could be on a dedicated index. I don't understand why we should always mix suggest and regular search in the same index. Most of the time the suggestions are pushed separately (from the query logs for instance) and having a separate index to handle the high throughput of suggest query is highly desirable (small indices with a lot of replicas for instance). 
Or we could use another type for the suggest, sort the index by types first and use a secondary sort that depends on the type ?

**Comment by mikemccand** [comment]
Lucene's `AnalyzingInfixSuggester` currently uses its own private index ...

**Comment by s1monw** [comment]
> But the analyzing infix suggester could be on a dedicated index. I don't understand why we should always mix suggest and regular search in the same index. Most of the time the suggestions are pushed separately (from the query logs for instance) and having a separate index to handle the high throughput of suggest query is highly desirable (small indices with a lot of replicas for instance). 
Or we could use another type for the suggest, sort the index by types first and use a secondary sort that depends on the type ?


I agree so much with you - this all size fits one stuff it just not applicable to something so specialized.

**Comment by andrenarchy** [comment]
Thanks for your feedback! Do I understand correctly that Lucene's `AnalyzingInfixSuggester` accomplishes the task but it needs to be made available in es? If so: would an implementation require a lot of work? (I'm not very experienced with the way es works behind the scenes)

If this gets implemented, I'd vote for a solution that can be configured easily via the mapping (in contrast to the [completion suggester](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html) where the indexed documents are enriched with `suggest` objects). Is this possible?

**Comment by andrenarchy** [comment]
Is there any update on this? I'd still love to use such a feature. 😉

**Comment by andyb-elastic** [comment]
@elastic/es-search-aggs

**Comment by pachanta** [comment]
Anyone has an ES plugin for this feature?

**Comment by javanna** [comment]
There is no progress on this and we have no plans to work on this feature. Closing this issue for the time being.
