### ISSUE TITLE
_cat/recovery API reports bytes always equal to total_bytes

### ISSUE THREAD

**Issue by bobrik** [elastic/elasticsearch#17020]
**Elasticsearch version**:

```
# elasticsearch --version
Version: 2.2.0, Build: 8ff36d1/2016-01-27T13:32:39Z, JVM: 1.8.0_72-internal
```

**JVM version**:

```
# java -version
openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)
```

**OS version**: Debian Jessie on kernel 4.1.3.

**Description of the problem including expected versus actual behavior**:

I was trying to understand why recover is happening much slower than I expect it to happen with `indices.recovery.max_bytes_per_sec=512mb` and `indices.recovery.concurrent_streams=8`. While doing so (unsuccessfully so far), I realized that `bytes` is always equal to `total_bytes` in `_cat/recovery` API. This doesn't seem logical, since `bytes_percent` is not 100%.

```
# curl -s http://myhost/_cat/recovery?v | fgrep -v done
index                        shard time    type       stage source_host target_host repository snapshot files files_percent bytes       bytes_percent total_files total_bytes translog translog_percent total_translog
aaa-2016.03.08               0     560663  relocation index 10.36.11.8  10.36.11.4  n/a        n/a      268   95.1%         45476478773 78.8%         268         45476478773 0        0.0%             791066
aaa-2016.03.08               5     560665  relocation index 10.36.11.7  10.36.11.4  n/a        n/a      238   91.6%         45083552298 79.3%         238         45083552298 0        0.0%             665251
```

I'd love to see any pointers on how to debug slower than expected recoveries, since CPU, IO and network don't seem to be saturated.

**Comment by jasontedor** [comment]
There is not a bug here:

`bytes` is the size to recover in bytes
`total_bytes` is the total number of bytes in the shard

The two are equal if its a full recovery, but they can be not equal in the case of a partial recovery (from local files first).

`bytes_percent` is the percent of bytes that need to be recovered

**Comment by bobrik** [comment]
This is a bit confusing.

* `translog_percent = translog / total_translog`
* `bytes_percent != bytes / total_bytes`
* `files_percent != files / total_files`

Any chance to make it consistent?

**Comment by jasontedor** [comment]
I agree it's confusing. It's like this:

`bytes_percent * bytes = bytes_recovered` (which does not have a column, but that can be added)
`files_percent * files = files_recovered` (which does not have a column, but that can be added)

The translog must always be fully recovered, however.

> Any chance to make it consistent?

I think that we can do something like this: add `bytes_recovered`, and `files_recovered`, rename `translog` to `translog_ops_recovered` and rename `translog_total` to `translog_ops`. Then it will be

`bytes_percent = bytes_recovered / bytes`
`files_percent = files_recovered / files`
`translog_percent = translog_ops_recovered / translog_ops`

What do you think @bobrik?

**Comment by bobrik** [comment]
That would be great. Will you file an issue then?

**Comment by jasontedor** [comment]
> That would be great. Will you file an issue then?

@bobrik Sure, I opened #17022.
