### ISSUE TITLE
Highlighting docs do not warn about the use of _all field

### ISSUE THREAD

**Issue by nick-giles** [elastic/elasticsearch#17034]
**Describe the feature**:

The highlighting docs do not help people whose query is using the _all field explain why they are getting no highlighting. Given that the docs on the _all field page do, it would seem sensible to at least link to that information from the highlighting page. Arguably the information may be better located on the highlighting page than the _all page.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html

**Comment by debadair** [comment]
The _all field is deprecated.
