### ISSUE TITLE
Deprecate "reverse" option for sorting

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#17047]
There are three ways of specifying sort order in our REST API:

Implicitly which uses the sort element specific default, like e.g.:

    "sort": [
       {
          "_score": {    }}]

Semi-implicit by requesting to reverse sort order:

    "sort": [
       {
          "_score": {  "reverse": "true"  }}]

Explicitly by setting sort order:

    "sort": [
       {
          "_score": {  "order": "asc"  }}]

After reviewing #17035 and going over the docs here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html which states that "Each sort can be reversed as well." I was confused about what "reverse" actually does. If used in combination with order, what happens depends on the order (no pun intended) of the order and reverse parameters in the search request. Simple reproduction below tested on ***2.2.0***:

    PUT /twitter/tweet/1
    {
        "message" : "trying out Elasticsearch"
    }
    PUT /twitter/tweet/2
    {
        "message" : "trying trying out Elasticsearch"
    }

Then issue the following searches for illustration (score based searches, default ordering is descending):

    GET /twitter/tweet/_search
    {
        "query": {"match": {
           "message": "trying"
        }},
        "sort": [
           {
              "_score": {
                  "order": "desc",
                  "reverse": "false"}}]}

... results in descending order.

    GET /twitter/tweet/_search
    {
        "query": {"match": {
           "message": "trying"
        }},
        "sort": [
           {
              "_score": {
                  "order": "desc",
                  "reverse": "true"}}]}

... results in ascending order.

All good so far. Now lets switch the order of the parameters:

    GET /twitter/tweet/_search
    {
        "query": {"match": {
           "message": "trying"
        }},
        "sort": [
           {
              "_score": {
                  "reverse": "true",
                  "order": "desc"}}]}

... results in descending order.

    GET /twitter/tweet/_search
    {
        "query": {"match": {
           "message": "trying"
        }},
        "sort": [
           {
              "_score": {
                  "reverse": "false",
                  "order": "desc"}}]}

... results in descending order.

I'd like to propose to deprecate "reverse" for 2.x and remove it in the next major release in favour of using the explicit "order" parameter only.

@clintongormley maybe I've mis-understood something, any clarifications welcome.

**Comment by cbuescher** [comment]
+1 on deprecating "reverse" parameter and removing it on master.

**Comment by clintongormley** [comment]
+1 on deprecating and removing.  it's the first i've heard of its existence and i doubt it was ever documented

**Comment by MaineC** [comment]
Awesome - thanks for the green light @clintongormley - wrt. to documentation: The only hint I found doing a quick google search is an example on the page on sorting in the ES guide linked above.

**Comment by MaineC** [comment]
Both, deprecation and removal done. Closing the related issue.
