### ISSUE TITLE
cloud-aws plugin is not working for new AWS region (Seoul, ap-northeast-2)

### ISSUE THREAD

**Issue by bezalel** [elastic/elasticsearch#17040]
I'm using Elasticsearch 1.5.2 version and cloud-aws plugin 2.5.1 version.
cloud-aws plugin is not working for new AWS region (Seoul, ap-northeast-2)

https://github.com/elastic/elasticsearch-cloud-aws/tree/v2.5.1/#version-251-for-elasticsearch-15
'Region' part of above document does not contain ap-northeast-2 region (Seoul)
plz update old version of cloud-aws plugin to support new AWS regions

**Comment by dadoonet** [comment]
Actually it has been added from elasticsearch 2.2.0 with #16167.
So it's already there.

Closing.

**Comment by bezalel** [comment]
How about ES 1.x plugins?
I'm using ES 1.5.2 and below 'cloud-aws' plugin.
https://github.com/elastic/elasticsearch-cloud-aws/tree/v2.5.1

I hope new AWS region support should be merged to old version plugins :D

**Comment by dadoonet** [comment]
I don't believe we will do it. We only fix bugs in old versions.
BTW I really encourage to at least upgrade to 1.7.

That being said, you could define the endpoint manually using s3.endpoint
