### ISSUE TITLE
extend ip-type mapper with ability to use long value as ip address

### ISSUE THREAD

**Issue by lizhenmxcz** [elastic/elasticsearch#17051]
I want to index the long value to the ip type. The data has stored in the relational database or hdfs. In order to save storage space, I save the ip address use the long value.  But now, i want to use the elasticsearch to search it. I must convert the long to ip type before index it, and it is inconvenient.

**Comment by jpountz** [comment]
I think we should stick to the usual representations of ip addresses, so -1 on my end.
