### ISSUE TITLE
Shard balancing model for throttled shards does not satisfy allocation deciders

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#17050]
The shard balancer allocates / relocates shards to nodes based on allocation deciders as well as a weight function. Allocation deciders represent hard constraints. If the deciders say NO then a shard cannot be allocated to that node. The weight function is a soft constraint and can be seen as more of a preference (This is the true "balancing" part of the balancer). The shard balancer allocates / relocates shards to the node with the lowest weight that satisfies the allocation deciders. This is not necessarily the node with the lowest overall weight.

Allocation deciders do not only provide a YES / NO answer but also have a concept of throttling. If an allocation decider returns THROTTLE as result, it means that the shard can be allocated to the node after other shards are finished being allocated / relocated. The shard balancer has special handling for throttling when calculating the weights for nodes. The reason for this is that it wants to optimize the balance for the full allocation of all shards (i.e. it does not optimize the balance for the shards that are allocated in this round but the best balance after all (throttled) shards have been allocated). In order to do that the shard balancer creates a separate predictive model of nodes with their allocated shards to simulate the balancing of shards in the context of throttling.

The issue lies in the way this model is constructed. The main difference in allocating / relocating shards on this predictive model versus the actual allocation is the following. If the node with lowest weight is found where allocation deciders say YES, then the shard is allocated on the predictive model as well as the actual allocation. If, however, the node with lowest weight is found and allocation deciders say THROTTLE, then the shard is allocated only on the predictive model but not on the actual allocation. This means that with each throttled allocation the model diverges more and more from the actual allocation. Allocation deciders calculate their decisions however only based on the actual allocation. The predictive model is never checked if it satisfies any of the constraints. This means that the model does not represent any real future allocation anymore as it does not satisfy the allocation deciders.

Example demonstrating the issue:
https://github.com/ywelsch/elasticsearch/commit/c320581c9c2b7c1773949d1e52cdfe9f2392038e shows a test run where the predictive model contains multiple replicas of the same shard on the same node which does not reflect any realistic situation allowed by the allocation deciders.

**Comment by nik9000** [comment]
Neat! I thought this was going to go into shard weighting functions but really this is orthogonal/prerequisite. Neat!

**Comment by dakrone** [comment]
@ywelsch do you think it's worth removing the predictive model entirely? Only using the actual allocation and relying on the next cluster state assigning "real" shards with the model?

**Comment by ywelsch** [comment]
@dakrone yes, I think we should just use the actual allocation model (RoutingNodes). This requires quite some work, though, and has only little benefit, so I'm closing this for now as an indicator that we're not going to work on this anytime soon.
