### ISSUE TITLE
Unable to install kafka plugin

### ISSUE THREAD

**Issue by 7AC** [elastic/elasticsearch#17056]
**Elasticsearch version**: 2.2.0

**JVM version**: 1.8.0_60

**OS version**: Mac OS 10.11.3

**Description of the problem including expected versus actual behavior**:
```
Giuseppes-Mac:libexec gvalente$ pwd
/usr/local/Cellar/elasticsearch/2.2.0_1/libexec
Giuseppes-Mac:libexec gvalente$ bin/plugin install --verbose kafka
-> Installing kafka...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/kafka/2.2.0/kafka-2.2.0.zip ...
Failed: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/kafka/2.2.0/kafka-2.2.0.zip]; nested: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/kafka/2.2.0/kafka-2.2.0.zip]; 
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information
```
**Steps to reproduce**:
 1. `cd /usr/local/Cellar/elasticsearch/2.2.0_1/libexec`
 2. `bin/plugin install --verbose kafka`

**Comment by jasontedor** [comment]
There is no plugin named "kafka" that is maintained as part of the Elasticsearch repository which what the steps that you executed above are attempting to install.

**Comment by 7AC** [comment]
Thank you, I just assumed that was the way to install log stash plugins as well:

https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html

**Comment by jasontedor** [comment]
No, you have to install logstash plugins using [logstash](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html). For example:

```bash
$ ./bin/logstash-plugin install logstash-input-kafka
```
