### ISSUE TITLE
disable HeapDumpOnOutOfMemoryError

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#17058]
When HeapDumpOnOOME is enabled and a heap dump occurs, it can result in the node remaining hung for significant time while it attempts to dump out the heap.  We'd like to see an environment variable that could be set to disable the automatic heap dump on OOME if desired.  The default behavior should still be to dump heap on OOME, but the ability to optionally disable it could be useful in some situations.

**Comment by jasontedor** [comment]
This can already be done today with `ES_JAVA_OPTS`:

```
$ ES_JAVA_OPTS="-XX:-HeapDumpOnOutOfMemoryError" ./bin/elasticsearch
```

Let's verify:

```
$ ./bin/elasticsearch
```

Then from another shell:

```
$ curl -sS -XGET localhost:9200/_nodes | jq '.. | .pid? | select(. != null)'
39947
$ jcmd 39947 VM.flags | tr ' ' '\n' | grep HeapDumpOnOutOfMemoryError
-XX:+HeapDumpOnOutOfMemoryError
```

showing that `HeapDumpOnOutOfMemoryError` is enabled. Now with `ES_JAVA_OPTS`:

```
$ ES_JAVA_OPTS="-XX:-HeapDumpOnOutOfMemoryError" ./bin/elasticsearch
```

and from another shell:

```bash
$ curl -sS -XGET localhost:9200/_nodes | jq '.. | .pid? | select(. != null)'
40671
$ jcmd 40671 VM.flags | tr ' ' '\n' | grep HeapDumpOnOutOfMemoryError
-XX:-HeapDumpOnOutOfMemoryError
```

showing that `HeapDumpOnOutOfMemoryError` is disabled.

Using `ES_JAVA_OPTS` just causes the flag to be on the command line twice, but the `ES_JAVA_OPTS` flags come last so they win.

I must say this though: if the heap is dumping so frequently that the heap dumping taking a long time is an issue, this is just a *symptom* of a problem, not the true problem. The true problem is that the heap is dumping all the time, and that is what should be solved, not that the heaps take a long time to dump. And if you want to solve the heap dumping all the time, it helps having heap dumps to look at to find out why! So, using this flag is taking away information that can be used to solve the true problem.
