### ISSUE TITLE
Features request: Passing Request list into RequestBuilder

### ISSUE THREAD

**Issue by pradeepg-telsiz** [elastic/elasticsearch#17063]
It's good to have a feature where we pass a list of BulkRequest. Currently we need to iterate to get all the documents need to be deleted and another set of iteration is need to build a bulk query.  Rather it will be efficient if we pass the list of delete requests. 

**Elasticsearch version**:

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by danielmitterdorfer** [comment]
`BulkProcessor` already provides a simplified API that allows you to add individual requests as follows:

```java
bulkProcessor.add(new IndexRequest("twitter", "tweet", "1").source(/* your doc here */));
bulkProcessor.add(new DeleteRequest("twitter", "tweet", "2"));
```

For more details, please see the [docs on `BulkProcessor`](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-docs-bulk-processor.html).

If you instead want to delete multiple documents that match a query you can use the [delete-by-query plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugins-delete-by-query.html).

I am closing the ticket for now. In case this doesn't cover your needs just reopen it.
