### ISSUE TITLE
Allow range aggregation to use lt, lte, gt, and gte

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#17079]
The `range` aggregation is awesome, but it currently limits you to defining buckets based on non-obvious inclusive/exclusive terms:

```json
{
  "to" : "2015-01-01"
},
{
  "from" : "2015-01-01",
  "to" : "2016-01-01"
},
{
  "from" : "2016-01-01"
}
```

It would be great if we changed this to be more along the lines of what we do with the range query:

```json
{
  "lt" : "2015-01-01"
},
{
  "gte" : "2015-01-01",
  "lt" : "2016-01-01"
},
{
  "gte" : "2016-01-01"
}
```

At the very least, it's more explicit about what's happening, but it also has the added benefit of matching the behavior of the query _and_ it gives a smidgen more flexibility.

**Comment by jasontedor** [comment]
Duplicates #5249 and #15198, which were closed as won't fix.

**Comment by pickypg** [comment]
@jasontedor Good catch on those. I did search, but I apparently used the wrong words. :)

I do wonder if perhaps we should deprecate the `range` aggregation and suggest what @jpountz suggested: use the `filters` aggregation in its place? I don't like suggesting that when there's a `range` agg, but if it's the replacement -- then so be it. It could be deprecated in 2.3 and a breaking change in 5.0.

**Comment by jasontedor** [comment]
> Good catch on those. I did search, but I apparently used the wrong words. :)

@pickypg I had a hard time finding it via search too, I only persisted it because I knew I had seen it before. :smile:

**Comment by pickypg** [comment]
@clintongormley What do you think about deprecating `range` agg in 2.3, then remove it in 5.0 as described above?

**Comment by clintongormley** [comment]
@pickypg i think the `range` agg is very useful. I don't see any reason to remove it.  @jpountz's suggestion of using the `filters` agg instead is only for those people who need behaviour other than the default.

**Comment by jpountz** [comment]
Another point is that the range agg has an optimization in order to quickly find the appropriate bucket, while the filters aggregation needs to evaluate all filters against incoming documents. If you have many buckets, I believe you could see a difference.

**Comment by pickypg** [comment]
@jpountz: If it's optimized, then it makes me want to have `gt`, `gte`, `lt`, and `lte` even more than. :)
