### ISSUE TITLE
Replace score_mode `total` with `sum`

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#17083]
In https://github.com/elastic/elasticsearch/pull/16045 the `sum` score mode was replaced with `total` to line up with the naming used in Lucene.  However, we use `sum` in many other similar places in Elasticsearch, eg sorting, function score query, nested scoring, etc.

To be consistent, we should use `sum` instead of  `total`. I also prefer it as it is more obvious how the total is calculated.

**Comment by s1monw** [comment]
can we just stick with total, it seems more widely used?

**Comment by clintongormley** [comment]
On the contrary, we use `sum` everywhere, not `total`.
