### ISSUE TITLE
Should we continue to use PROTOTYPE objects with Writeable?

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#17085]
Should we use something else? Is declaring a constructor that takes a StreamInput and referencing that constructor where we need it good enough? Better?

**Comment by s1monw** [comment]
I am not sure we really started doing this or somebody just did it without thinking about if it's necessary. I think it initially came up during the clusterstate diffs where is was necessary in some places but not meant as best practice or a pattern. Especially with Java 8 where we can just pass `SomeWriteable::new` as an `Writeable.IOFunction` is a much better pattern where it's needed

**Comment by nik9000** [comment]
Now that we can make the constructor references I wonder if we can drop `readFrom` from `Writeable` and declare that by conventions `Writeable`s always have a constructor that takes a stream input. We could enforce the convention with tooling like we do the test class hierarchy if we like.

**Comment by s1monw** [comment]
you can do that however, I don't like the fact that the compiler doesn't require you to do so...

**Comment by s1monw** [comment]
@nik9000 maybe we can make it an abstract class?

**Comment by nik9000** [comment]
> @nik9000 maybe we can make it an abstract class?

That doesn't really force the implementer to actually use the StreamInput constructor. It is more of a "reminder", I guess". And it could mess with class hierarchy. I don't really like it.

I think it wouldn't be too hard to make NamingConvetionsCheck check that implementers declare the constructor. It isn't the compiler, but it is a build time thing. I like that better than the abstract class I think.

**Comment by colings86** [comment]
For my part I wouldn't like having this as a build time only check as it makes development annoying since I can have a new fix/feature/enhancement compiling and ready to go and then find when I run the build that there are problems. I personally think we should limit the build time checks as much as possible and prefer compile time errors instead.

**Comment by nik9000** [comment]
I'm going to have a go at this. It is large and I'll do it in stages. I suspect I'll be able to do it without any extra checks simply because all Writeables want to be read and they'll need a StreamInput constructor for that to work.
