### ISSUE TITLE
es2.1.0 keep throw failed to execute ttl exception

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#17089]
Elasticsearch version: 2.1.0
JVM version:8u40
OS version: linux 2.6

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.create mapping below:
  "op_logs_2016-02-29": {
    "mappings": {
      "_default_": {
        "_ttl": {
          "default": 2592000000,
          "enabled": true
        },
        "_all": {
          "enabled": false
        },
        "properties": {
          "domainType": {
            "index": "not_analyzed",
            "type": "string"
          },
          "venderId": {
            "index": "not_analyzed",
            "type": "string"
          },
          "invokeClassName": {
            "index": "not_analyzed",
            "type": "string"
          },
          "uploadTime": {
            "format": "yyyy-MM-dd HH:mm:ss",
            "type": "date"
          },
          "operatorName": {
            "index": "not_analyzed",
            "type": "string"
          },
          "uuid": {
            "index": "not_analyzed",
            "type": "string"
          },
          "createTime": {
            "format": "yyyy-MM-dd HH:mm:ss",
            "type": "date"
          },
          "clientSystemIP": {
            "index": "not_analyzed",
            "type": "string"
          },
          "operateDesc": {
            "analyzer": "ik",
            "type": "string"
          },
          "outputParamDesc": {
            "analyzer": "ik",
            "type": "string"
          },
          "clientSystemName": {
            "index": "not_analyzed",
            "type": "string"
          },
          "invokeMethodName": {
            "index": "not_analyzed",
            "type": "string"
          },
          "inputParamDesc": {
            "analyzer": "ik",
            "type": "string"
          }
        }
      }
}
}
 2.put some data

then log keep throw below:
[2016-03-14 13:36:56,626][WARN ][indices.ttl ] [172.20.130.67] failed to execute ttl purge:java.lang.NullPointerException

**Comment by clintongormley** [comment]
Hi @makeyang 

I've tried your recreation but it doesn't work for me.  Everything works as it should.  Could you provide more information, eg the stack trace that accompanies the NPE?  Also note that the TTL field is deprecated.

**Comment by clintongormley** [comment]
No further feedback. Closing
