### ISSUE TITLE
Newline missing from console output

### ISSUE THREAD

**Issue by lolzoloz9** [elastic/elasticsearch#17099]
After executing a curl command, given output missing a newline character.  This keeps command line prompt on the same line as output.  Both aesthetically annoying and affects command line history being cut off and broken.

<img width="1234" alt="screen shot 2016-03-14 at 2 12 23 pm" src="https://cloud.githubusercontent.com/assets/9092131/13758436/198e37d8-e9ef-11e5-99c0-0dca30e4f8e9.png">

Command line prompt is default config.
System: OSX El Capitan

**Comment by dadoonet** [comment]
Newline is added when you add ?pretty
