### ISSUE TITLE
Regexp Query Cannot Accept Escaped '+'

### ISSUE THREAD

**Issue by tebriel** [elastic/elasticsearch#17098]
**Elasticsearch version**: 2.2.0

**JVM version**: 1.8.0_72-internal

**OS version**: debian-jessie

**Description of the problem including expected versus actual behavior**:

I have a lot of data in E.164 format in a field called data.cid_info.e164. These are internationally standardized phone numbers. I want to find all phone numbers that start with +44 (UK prefix). As this is a string field, a regexp query seems sufficient. So I issue a search as follows:

```json
{
  "query": {
    "regexp": {
      "data.cid_info.e164": "^+44.*"
    }
  },
  "fields": ["data.cid_info.e164"],
  "size": 10
}
```

I expect 343 hits for today (will explain how I know this in a second) but I get 0 instead.

Oh, but you say, + is not an allowed character and must be escaped. Sure, so let's try that using the docs. It states that to escape a special character, precede it with a `\`.

```json
{
  "query": {
    "regexp": {
      "data.cid_info.e164": "^\+44.*"
    }
  },
  "fields": ["data.cid_info.e164"],
  "size": 10
}
```

Sense immediately throws an exception, but let's ignore sense's exception for a second and carry on.

```json
{
   "error": {
      "root_cause": [
         {
            "type": "query_parsing_exception",
            "reason": "Failed to parse",
            "index": "logstash-2016.03.14"
         }
      ],
      "type": "search_phase_execution_exception",
      "reason": "all shards failed",
      "phase": "query",
      "grouped": true,
      "failed_shards": [
         {
            "shard": 0,
            "index": "logstash-2016.03.14",
            "node": "YOEgLqVGSbGgIgbXJJqSNg",
            "reason": {
               "type": "query_parsing_exception",
               "reason": "Failed to parse",
               "index": "logstash-2016.03.14",
               "caused_by": {
                  "type": "json_parse_exception",
                  "reason": "Unrecognized character escape '+' (code 43)\n at [Source: [B@1dfa7073; line: 4, column: 33]"
               }
            }
         }
      ]
   },
   "status": 400
}
```

Now, because I know my data, and I know it conforms to the E.164 format for the field, I know I can safely suggest that the + is optional, and it will return me the right counts (good for troubleshooting this bug, not a good general practice).

```json
{
  "query": {
    "regexp": {
      "data.cid_info.e164": "^+?44.*"
    }
  },
  "fields": ["data.cid_info.e164"],
  "size": 0
}
```

Resulting in:

```
{
  "_shards": {
    "failed": 0,
    "successful": 2,
    "total": 2
  },
  "hits": {
    "hits": [],
    "max_score": 0.0,
    "total": 343
  },
  "timed_out": false,
  "took": 2
}
```

Hey, it's the right number!

I believe this is due to the [JSON spec](http://www.json.org/) not allowing escaped characters that aren't control characters.

> char
> any-Unicode-character-
>     except-"-or-\-or-
>     control-character
> \"
> \\
> \/
> \b
> \f
> \n
> \r
> \t
> \u four-hex-digits

So I'm not sure that there is a way to do a web request with an escaped character in the JSON body.

Note that escaping the \ doesn't work either, as that returns 0 results `"^\\+44.*"` for reference. 

**Steps to reproduce**:
 1. Issue a regex query with an escaped `+` sign (data which has a literal plus in it), see examples above
 2. Note that no results were returned

**Comment by nik9000** [comment]
> Note that escaping the \ doesn't work either, as that returns 0 results "^\\+44.*" for reference.

Could you try `^[+]44.*`? That'll at least be a work around if it works.

A couple of other thoughts:

1. A prefix query should also work.
2. I'd normalize the `+` out of the phone number on the way in.
3. You will get better performance if you extract the area code to it's own field. A prefix or a regex query has to walk through lots of terms but if you extract the country code to a field it'll be a single term lookup. Depending on your use case you might also want to extract stuff like npa for NANPA numbers as well.

**Comment by tebriel** [comment]
@nik9000:

### Character Class ###

```json
{
  "query": {
    "regexp": {
      "data.cid_info.e164": "^[+]44.*"
    }
  },
  "fields": ["data.cid_info.e164"],
  "size": 0
}
```

0 hits still


### Prefix Query ###

```json
{
  "query": {
    "prefix": {
      "data.cid_info.e164": "+44"
    }
  },
  "fields": ["data.cid_info.e164"],
  "size": 10
}
```

Oddly also 0 hits.
```
{
  "_shards": {
    "failed": 0,
    "successful": 2,
    "total": 2
  },
  "hits": {
    "hits": [],
    "max_score": null,
    "total": 0
  },
  "timed_out": false,
  "took": 1
}
```

### Reworking of how data is stored ###

Yeah, totally get that. I could go back and reindex the 5b docs, but that's not really feasible right now. I may add a logstash pattern to split up and extract things like NPA/NXX from the e164 data.

Thanks for your help.

**Comment by tebriel** [comment]
### Example Query + Docs ###

I thought this might be helpful too. Here's a query that gets back a few documents and the resulting docs.

I also looked and the e164 string field is analyzed, and has no non-standard analyzers or tokenizers on it.

```
{
  "query": {
    "regexp": {
      "data.cid_info.e164": "^+?44.*"
    }
  },
  "fields": ["data.cid_info.e164"],
  "size": 5
}
```

```
{
  "_shards": {
    "failed": 0,
    "successful": 2,
    "total": 2
  },
  "hits": {
    "hits": [
      {
        "_id": "AVNzLldsnx4nT5Yl6NJi",
        "_index": "logstash-2016.03.14",
        "_score": 1.0,
        "_type": "api",
        "fields": {
          "data.cid_info.e164": [
            "+441202629580"
          ]
        }
      },
      {
        "_id": "AVNzNVhNYwYqX587IL4a",
        "_index": "logstash-2016.03.14",
        "_score": 1.0,
        "_type": "api",
        "fields": {
          "data.cid_info.e164": [
            "+441908410653"
          ]
        }
      },
      {
        "_id": "AVNzQAZTYwYqX587IR9q",
        "_index": "logstash-2016.03.14",
        "_score": 1.0,
        "_type": "api",
        "fields": {
          "data.cid_info.e164": [
            "+441202629580"
          ]
        }
      },
      {
        "_id": "AVNzTiLGnx4nT5Yl6tYt",
        "_index": "logstash-2016.03.14",
        "_score": 1.0,
        "_type": "api",
        "fields": {
          "data.cid_info.e164": [
            "+441908410653"
          ]
        }
      },
      {
        "_id": "AVNzVuqOYwYqX587Icxb",
        "_index": "logstash-2016.03.14",
        "_score": 1.0,
        "_type": "api",
        "fields": {
          "data.cid_info.e164": [
            "+441908410653"
          ]
        }
      }
    ],
    "max_score": 1.0,
    "total": 357
  },
  "timed_out": false,
  "took": 3
}
```

**Comment by jimferenczi** [comment]
> I also looked and the e164 string field is analyzed, and has no non-standard analyzers or tokenizers on it

If your field is analyzed then there is a big chance that the tokenizer removes the '+' automatically. I tried your example on a non-analyzed string field and it works as expected (for regexp and prefix queries). The fact that the prefix query does not work on your deployment is also a good indicator that something is wrong in your mapping. Are you using the default/standard analyzer ? For a phone number I would use a non-analyzed string field, why would you need an analyzer for this field?

**Comment by tebriel** [comment]
@jimferenczi If the tokenizer removed the + automatically, then wouldn't `"^44.*"`return results? As for why it's analyzed, it shouldn't be, you're right, but reindexing all the docs right now isn't feasible. It's added to the list of tech debt for this project. It's an auto-created field, so it took on whatever analyzer and tokenizer defaults there were.

**Comment by jimferenczi** [comment]
@tebriel sorry I forgot to explain how I transformed your query into a "valid" Lucene pattern. As explained here https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html#_standard_operators Lucene’s patterns are always anchored. Thus you do not need to use "^".

**Comment by tebriel** [comment]
@jimferenczi Oh I see. Thanks, but it's still necessary for a regexp query, right? I mean, my issues aside (I have a workaround) the bigger issue here is I don't think you can issue a valid regexp query using what is documented for Elasticsearch.

**Comment by jimferenczi** [comment]
Sorry I don't understand what you mean by "but it's still necessary for a regexp query". 
The character "^" is not reserved so if you use it in a regexp query it will be considered as a character to match in the string.
"44.*" => starts with 44 followed by any character sequence.
".*44" => starts with any character sequence and ends with 44.
"^44.*" => starts with the character "^" followed by 44 and ends with any character sequence (match the exact string "^44787" and no match for "44787")

**Comment by tebriel** [comment]
@jimferenczi Oh yes, duh. Sorry, I read the docs wrong. You do not need the anchor, you are correct.

But the docs (hopefully I'm reading right this time) state that you must escape `. ? + * | { } [ ] ( ) " \ ` as they are "reserved characters" and json does not allow you to escape `+`. So that's still a problem, regardless of how my document is indexed, yes?

**Comment by jimferenczi** [comment]
No it's not. You can "escape" the character '+' but it has nothing to do with json. I tried the regexp query "\+44.\*" on a non analyzed string and it works as expected. I am going to close the issue as solved. Feel free to reopen if I missed anyhting.

**Comment by tebriel** [comment]
@jimferenczi Am I hold it it wrong? Can you issue a successful query escaping the `+`?

Issuing this query returns an exception for me:
```
{
  "query": {
    "regexp": {
      "data.cid_info.e164": "\+44.*"
    }
  },
  "fields": ["data.cid_info.e164"],
  "size": 10
}
```

**Comment by jimferenczi** [comment]
You can try with double escaping like this "\\+44.\*" or surrounded with double quotes: "\"+44\".\*" which has the same meaning.

**Comment by tebriel** [comment]
@jimferenczi Okay, thanks for all your help!
