### ISSUE TITLE
byte / time values without units in templates cause Guice errors on ES 2.X upgrade

### ISSUE THREAD

**Issue by mfussenegger** [elastic/elasticsearch#17093]
It seems the setting upgrade code is only run on index settings but not on templates.

If a template is created pre 2.0 which contains byte or time values without units and an index is created in >= 2.0 it will create an index with invalid values causing contructors fail due to settings parse failure.

Steps to reproduce: Create template with 1.7

```
http://localhost:9200
POST /_template/t1
{
    "template": "te*",
    "settings": {
        "index": {
            "translog": {
                "interval": "8000"
            }
        }
    }
}
```

Stop 1.7 and start 2.1

Create new index:

```
http://localhost:9200
POST /test/default/1
{
    "x": "y"
}
```

This results in errors like this:

```
[test][[test][4]] ElasticsearchException[failed to create shard]; nested: ElasticsearchParseException[Failed to parse setting [index.translog.interval] with value [8000] as a time value: unit is missing or unrecognized];
	at org.elasticsearch.index.IndexService.createShard(IndexService.java:372)
```

The [migration checker](https://github.com/elastic/elasticsearch-migration) also doesn't detect this.

**Comment by mfussenegger** [comment]
I made a PR against our fork and can also make a PR against this repo if you'd like me to. Just let me know (and also tell me against which branch I should make that PR)

**Comment by s1monw** [comment]
> I made a PR against our fork and can also make a PR against this repo if you'd like me to. Just let me know (and also tell me against which branch I should make that PR)


please do! and this should be against 2.x

**Comment by mikemccand** [comment]
Fixed with https://github.com/elastic/elasticsearch/pull/17095
