### ISSUE TITLE
we can use term aggregation with  moving average aggregation

### ISSUE THREAD

**Issue by kingaj** [elastic/elasticsearch#17109]
we can use term aggregation with  moving average aggregation

in elasticsearch 2.2.0

please help it is possible   

ajay.rathod39@gmail.com

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by kingaj** [comment]
yes i know but so many time i open  https://discuss.elastic.co/ but it can show any thing
