### ISSUE TITLE
Remove the ability to register custom suggesters and custom highlighters

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#17100]
We discussed briefly whether to remove the ability to register custom suggesters and custom highlighters via `SearchModule#registerSuggester` and `SearchModule#registerHighlighter`.  This issue is to open the floor for discussion and capture the reasoning behind whatever decision is made.

This discussion came about through the search refactoring effort and attempting to clean up unused parts of the code base.  We will need feedback from the user community as well to gauge to what extent the feature is used.

**Comment by abeyad** [comment]
This is a project that uses custom suggesters: https://github.com/meltwater/es-prefix-suggester

**Comment by abeyad** [comment]
@s1monw @clintongormley ^^ FYI

**Comment by nik9000** [comment]
> SearchModule#registerHighlighter

And [this](https://github.com/wikimedia/search-highlighter) is a custom highlighter. No one has gotten it working with 2.x yet, but it sees fairly heavy use.

**Comment by sikoried** [comment]
I think having custom highlighters is a great feature.  Along with custom Tokenizers and Analyzers, I'm using this functionality to support a proprietary data format which needs to undergo a fairly sophisticated highlighting process before it can be rendered to the client.

Basically, the trio of customized Tokenizer, Analyzer and Highlighter allows to fully support custom data fields.

**Comment by abeyad** [comment]
@sikoried Thank you for your feedback!

**Comment by javanna** [comment]
I am not familiar with custom suggester implementations, but I am sure there are other custom highlighter implementations out there. I think we should definitely keep that extension point.

**Comment by irothschild** [comment]
Has support for custom highlighters been removed in ES 5? 

Here https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_search_changes.html it says

```
Removed support for multiple highlighter names, the only supported ones are: plain, fvh and postings.
```

**Comment by nik9000** [comment]
Custom highlighters are still supported. That change is about removing the
alternative names for the built in highlighters.

**Comment by clintongormley** [comment]
Looks like we should keep custom highlighters and suggesters.  Closing
