### ISSUE TITLE
503 Timeout errors on PUT request to update mapping during cluster rebalancing

### ISSUE THREAD

**Issue by vineet85** [elastic/elasticsearch#17117]
Could be related to #8193 and #9323

Elasticsearch version: 1.7.3.3

I'm noticing PUT requests to update mapping are failing with a 503 error on the cluster when re-balancing occurs and re-locating shards are present on the cluster. Is this because the 30 second timeout is being reached? This is ha-penning even if the cluster is not restarted and occasional re-balancing of shards occurs.

Eg: 
PUT https://localhost:9200/Indexname/documenthighlight/_mapping
{
}

error=RemoteTransportException[[c383nha-master-9200][inet[/10.204.160.10:9300]][indices:admin/mapping/put]]; nested: ProcessClusterEventTimeoutException[failed to process cluster event (put-mapping [documenthighlight]) within 30s]; 
status=503

**Comment by clintongormley** [comment]
Hi @vineet85 

It sounds like you have a very large mapping, possibly with some less-than-responsive nodes.

Time to upgrade! (and reconsider why your mappings are so large)

**Comment by vineet85** [comment]
Thanks, think of it the mapping update we are making is significantly large. We need to re-think our mapping.
