### ISSUE TITLE
Remove "sandbox" option from script settings

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#17114]
Today you can set, eg, `script.inline: sandbox`  which means "enable inline scripting for all languages which are considered to be sandboxed".

Given that this is the default, and the user would typically want to disable scripting, I think that the "sandbox" option just muddies the water, and the script settings should only accept `true` or `false`.

Closes #10548

**Comment by rashidkpc** [comment]
Really need this to add support for other scripting languages to Kibana. We really just need to know what languages exist, and if inline scripting is enabled on them. `sandbox` basically means "maybe", so we really need the true/false.

**Comment by clintongormley** [comment]
@dakrone would you mind working on this?
