### ISSUE TITLE
Remove unofficial support for JAVA_OPTS

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#17121]
Today, we permit JVM arguments to be passed via both `JAVA_OPTS` and `ES_JAVA_OPTS`. The JVM [officially supports](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/envvars002.html) `JAVA_TOOL_OPTIONS` for this purpose, but we [officially do not support that](https://github.com/elastic/elasticsearch/pull/13813) because it is broken on certain platforms. The environment variable `JAVA_OPTS` is supported in some projects (most notably Tomcat) but it is not officially supported and does not have widespread support (e.g., `mvn` does not support it). Notably, we [document `ES_JAVA_OPTS`](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-service.html) but do not document `JAVA_OPTS`. There is no need to support both. Since we won't support `JAVA_TOOLS_OPTIONS`, and we do not document `JAVA_OPTS` but document `ES_JAVA_OPTS`, we should just remove support for `JAVA_OPTS` and keep `ES_JAVA_OPTS` only.

**Comment by jasontedor** [comment]
Went on another JVM code sleuthing adventure, and found that oddly enough there [is an environment variable `_JAVA_OPTIONS`](http://hg.openjdk.java.net/jdk8/jdk8/hotspot/file/tip/src/share/vm/runtime/arguments.cpp#l3265) that is also parsed by the JVM on startup. Moreover, because of the [order](http://hg.openjdk.java.net/jdk8/jdk8/hotspot/file/tip/src/share/vm/runtime/arguments.cpp#l2449) in which the options are parsed, any flags in this environment variable *trump* both command line flags and options passed in the `JAVA_TOOL_OPTIONS` environment variable. Yet, this environment variable appears to be completely undocumented!

**Comment by jasontedor** [comment]
This demonstrates the above observation regarding the order of precedence:

```
18:39:14 [jason:~] $ _JAVA_OPTIONS="-Xmx4g" JAVA_TOOL_OPTIONS="-Xmx2g" java -Xmx3g -XX:+PrintFlagsFinal -version | grep MaxHeapSize
Picked up JAVA_TOOL_OPTIONS: -Xmx2g
Picked up _JAVA_OPTIONS: -Xmx4g
    uintx MaxHeapSize                              := 4294967296                          {product}
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
18:40:08 [jason:~] $ JAVA_TOOL_OPTIONS="-Xmx2g" java -Xmx3g -XX:+PrintFlagsFinal -version | grep MaxHeapSize
Picked up JAVA_TOOL_OPTIONS: -Xmx2g
    uintx MaxHeapSize                              := 3221225472                          {product}
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
18:40:12 [jason:~] $ JAVA_TOOL_OPTIONS="-Xmx2g" java -XX:+PrintFlagsFinal -version | grep MaxHeapSize
Picked up JAVA_TOOL_OPTIONS: -Xmx2g
    uintx MaxHeapSize                              := 2147483648                          {product}
java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
```

**Comment by clintongormley** [comment]
Actually, we do document JAVA_OPTS in two places:

* https://github.com/elastic/elasticsearch/blob/master/docs/reference/setup/configuration.asciidoc
* https://github.com/elastic/elasticsearch/blob/master/docs/plugins/plugin-script.asciidoc

I'm good with standardising on `ES_JAVA_OPTS` though.  Bonus points for warning if `JAVA_OPTS` is set and `ES_JAVA_OPTS` is not.

**Comment by s1monw** [comment]
just linking https://github.com/elastic/elasticsearch/pull/17160 and this issue since whichever is committed first must adopt

**Comment by clintongormley** [comment]
#17160 was closed with https://github.com/elastic/elasticsearch/commit/bd059b8cc3c8e28a5a9866621f96e3c36f9a8ee7
