### ISSUE TITLE
constant_score should throw a parse exception if more than one filter is supplied

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#17126]
The `constant_score` query will accept multiple clauses in its `filter` clause, but it appears to only run the last query.  I believe the intention is for it to only accept a single clause, so multiple query objects should raise a parse exception.

E.g.

```js
POST /test/test/
{
    "foo": "a"
}

POST /test/test/
{
    "foo": "b"
}

POST /test/test/
{
    "foo": "a b"
}

GET /test/_search
{
   "query": {
      "constant_score": {
         "filter": [
            { "term": { "foo": "x" } },
            { "term": { "foo": "a" } }
         ]
      }
   }
}
```

Which yields both documents which have `"a"`:

```json
{
   "hits": {
      "total": 2,
      "max_score": 1,
      "hits": [
         {
            "_index": "test",
            "_type": "test",
            "_id": "AVN8hy3XgPMxNnYnA0TX",
            "_score": 1,
            "_source": {
               "foo": "a"
            }
         },
         {
            "_index": "test",
            "_type": "test",
            "_id": "AVN8h2TygPMxNnYnA0Tr",
            "_score": 1,
            "_source": {
               "foo": "a b"
            }
         }
      ]
   }
}
```

Swapping the order returns zero documents, because nothing matches `"x"`:

```js
GET /test/_search
{
   "query": {
      "constant_score": {
         "filter": [
            { "term": { "foo": "a" } },
            { "term": { "foo": "x" } }
         ]
      }
   }
}
```
```json
{
   "hits": {
      "total": 0,
      "max_score": null,
      "hits": []
   }
}
```

This is especially confusing because the `bool` filter clause *does* support multiple clauses, and by default AND's them together.

**Comment by cbuescher** [comment]
I agree, unfortunately there are many places in the query parsers where specifying the same parameter twice won't throw an error but silently drops the first one. I'll add a check for this. btw, the array notation only works because those tokens get silently ignored as well.

**Comment by polyfractal** [comment]
Thanks @cbuescher!
