### ISSUE TITLE
Cannot run exists query on field with thousands of nested fields

### ISSUE THREAD

**Issue by merito** [elastic/elasticsearch#17131]
**Describe the feature**: I've got some documents with field A and inside A are thousands of nested fields. I would like to run exists query to get documents with field A presents
```json
{
  "query": {
    "bool": {
      "must": {
        "exists": {
          "field": "A"
        }
      }
    }
  }
}
```
but then I've got an error
```json
"type": "too_many_clauses",
"reason": "maxClauseCount is set to 1024"
```
In my case there is one nested field exists in every A, so I can query for A.B, but what can I do if there is no common fields in A and I want to see all docs with A?

**Comment by clintongormley** [comment]
Do you mean `nested` fields or inner `object` fields?  Either way, having thousands of fields is costly, especially if those fields are sparse.  We are currently working on adding various [soft limits](https://github.com/elastic/elasticsearch/issues/11511) to things like the [number of fields](https://github.com/elastic/elasticsearch/issues/11443) you can have in an index, plus the [number of nested fields](https://github.com/elastic/elasticsearch/pull/15989) you can have in an index.

Usually your data model can be reworked to use fewer fields by specifying whatever you are using for a field name today as a value instead, eg:

    { "foo": "bar"}

could be better represented as:

    { "key": "foo", "value": bar" }

An alternative, with your current model, is to use a single field within `A` to identify documents that have an `A.*` field, eg:

    { "A": {
        "some_val": "foo",
        "exists": true
    }}

Then you could just query on `A.exists`.  This will be much more efficient than querying for thousands of potential terms.

**Comment by merito** [comment]
Yes, I mean inner objects. But still even if there is not thousands of fields I think it will be useful to have a feature to check if only the outer object exists without checking all inner objects, like in my case.

**Comment by clintongormley** [comment]
@merito see https://github.com/elastic/elasticsearch/pull/17186
