### ISSUE TITLE
Path hierarchy tokenizer doc could be a bit more helpful

### ISSUE THREAD

**Issue by kix** [elastic/elasticsearch#17138]
**Elasticsearch version**: current

**JVM version**: irrelevant

**OS version**: irrelevant

**Description of the problem including expected versus actual behavior**:

The [official documentation for path hierarchy tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pathhierarchy-tokenizer.html) lacks usecase descriptions, as well as examples on performing filtering or aggregations on such fields. There is no explanation on why would anyone use this tokenizer.

Expected: the doc should explain why would I be using the tokenizer, and how do I aggregate/filter/etc. for the fields that use it.

**Steps to reproduce**:
Doc issue, so no steps here.

**Comment by clintongormley** [comment]
It can certainly be improved.  In the meantime, have a look at this: https://www.elastic.co/guide/en/elasticsearch/guide/master/denormalization-concurrency.html

**Comment by s1monw** [comment]
@kix may I ask you to reword the title and description of this issue and use less aggressive words. I'd appreciate if you could use terminology like _Path hierarchy tokenizer doc is_ `not helpful`, `needs to be improved`, `misses usecase`. We are trying hard to get docs out there that are helpful as much as we try to continuously improve communication, please help me! :)

**Comment by kix** [comment]
@s1monw, done :)

**Comment by s1monw** [comment]
@kix thanks man!

**Comment by kix** [comment]
@s1monw, sorry for being a bit harsh, but sometimes when you're looking for a solution, you certainly hope that the doc will help.

**Comment by s1monw** [comment]
@kix not a big deal description looks much better and I can tell you there is suddenly more motivation to fix that :)

**Comment by debadair** [comment]
Need to pull relevant information into the ref from the Definitive Guide.

**Comment by mayya-sharipova** [comment]
Closing as this is addressed

**Comment by mitoihs** [comment]
I think it might be improved further. There's only an example of how to use that field to filter. I would be interested in:

1. Is it possible to tokenize path hierarchy into a "keyword" type field? The example shows the "text" field but I don't want to run full-text searches on my tokens.
2. How to aggregate on such a field? I would like to e.g. create a Pie Chart / Treemap that uses hierarchy. So it could look like a WinDirStat treemap: 
![](https://windirstat.net/images/windirstat.jpg)
3. How to use a specific level in the hierarchy to filter/aggregate? (e.g.: I have a known number of levels each document will have and just want to filter on level 2)
