### ISSUE TITLE
Add auto detection to convert processor

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#17139]
The `ingest` processor is able to convert string values to either a boolean, integer or float value.
This processor needs to be configured in a strict manner. For example `field_a` need to be converted to an integer. If the field doesn't exist or can't be its value can't converted to an integer this processor fails.

The idea is here the add an `auto` convert type option that tries to convert strings to either a integer/float or a boolean value based on simple rules:
* true | false -> boolean 
* [-+]?[0-9] -> integer
* [-+]?[0-9]*\.?[0-9]* -> float

If the `auto` convert type is unable to convert than it just does nothing and leaves that field untouched.

In order to auto detect a number fields it would be helpful if the `field` option would support wildcards too. 
For all fields that match the convert processor will convert the values based on the configured convert type. If no fields match with the wildcard pattern than the `convert` processor does nothing.

I think if this gets implemented then this can supersede number detections in mappings?

**Comment by kimchy** [comment]
another potential option for this is to to create a new field when converting, only if we manage to convert it. So, if you have `field1`, and we try to convert it to numeric, we will create `field1_num` with the numeric value, but if we can't convert, we can let ingest still work, just not create the `field1_num` field.

**Comment by martijnvg** [comment]
Maybe we can add `target_field` option? Any conversion done by this processor will be put in that field.

**Comment by talevy** [comment]
^^^ kind of solves this.

I wanted to get something cleared away with `target_field` first. How should List-valued fields behave with this target field? I am ok with treating it just as another type and setting a whole new field with the new list value.

**Comment by martijnvg** [comment]
> How should List-valued fields behave with this target field? 

I think like any other field, only here multiple conversions will take place and all the these converted values are placed into the new target field which will be an array too.

**Comment by talevy** [comment]
that's what I thought, just wanted to double check. will update PR shortly
