### ISSUE TITLE
Enable RequestCache by default if shard is inactive

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#17134]
To fully leverage #16870 we should enable the request cache by default. This has show to improve aggregations and search results dramatically on static indices. A good indicator if a shard / index is static is if it has received writes within a certain time interval which we also used to adjust indexing buffers in the past or use for issuing synced flushes. We should check`IndexShard#isActive()` and if it's not active we should allow request caching by default.

Relates to #16870

**Comment by bleskes** [comment]
+1 :)
