### ISSUE TITLE
Add option to disable doc_count for aggregations

### ISSUE THREAD

**Issue by mpskovvang** [elastic/elasticsearch#17141]
**Describe the feature**:
Sometimes you don't need the count value for aggregations and I guess omitting the count might improve performance?

Also have you considered an option for checking if a field with a specific value is present in the filtered query. This might be in relating with the above suggestion.

E.g. if you wanna know if the query contains a field 'color' with the value 'red' - just as a boolean. Maybe even provide an array of values.

**Comment by clintongormley** [comment]
> Sometimes you don't need the count value for aggregations and I guess omitting the count might improve performance?

The code path for checking if we should collect the count will probably be more expensive than just collecting it.

> Also have you considered an option for checking if a field with a specific value is present in the filtered query. This might be in relating with the above suggestion.
>
> E.g. if you wanna know if the query contains a field 'color' with the value 'red' - just as a boolean. Maybe even provide an array of values.

Sorry, I have no idea what this means, but it seems unrelated to the doc_count issue so I'm going to close this.  If you want to provide more details of your suggestion please open another issue.

**Comment by enriquesaou** [comment]
Hello,
In cases with very high counts (> 1 000 000 000 occurrences) this feature would be extremely useful. In this specific case, we only need the values and not the counts, and removing the counting process would probably cut computing times by 3 (at least, in the case I have experienced).
