### ISSUE TITLE
Allow access to the rest of the document from inside ingest foreach processor

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#17147]
It would be convenient if access to the root object was possible when using an ingest `foreach`.  The most useful would be a `_root` scope, but perhaps `_parent` might also be useful in the case of deeply nested objects?  I'd be happy with `_root` to start :)

For example:

```js
POST _ingest/pipeline/_simulate
{
   "pipeline": {
      "description": "test",
      "processors": [
         {
            "foreach": {
               "field": "values",
               "processors": [
                  {
                    "append": {
                       "field": "_root.values_flat",
                       "value": "{{_value.key}}_{{_value.value}}"
                    }
                 }
               ]
            }
         }
      ]
   },
   "docs": [
      {
         "_index": "index",
         "_type": "type",
         "_id": "id",
         "_source": {
            "values": [
               {
                  "level": 1,
                  "key": "foo",
                  "value": "bar"
               },
               {
                  "level": 2,
                  "key": "foo",
                  "value": "baz"
               }
            ]
         }
      }
   ]
}
```

Which would yield the documents:

```js
"docs": [
      {
         "_index": "index",
         "_type": "type",
         "_id": "id",
         "_source": {
            "values_flat": [ "foo_bar", "foo_baz" ],  // <-- new
            "values": [
               {
                  "level": 1,
                  "key": "foo",
                  "value": "bar"
               },
               {
                  "level": 2,
                  "key": "foo",
                  "value": "baz"
               }
            ]
         }
      }
   ]
```

/cc @martijnvg

**Comment by clintongormley** [comment]
Why do we need the `_root` notation? Wouldn't just specifying `values_flat` be sufficient?

**Comment by clintongormley** [comment]
This looks like a bug to me - the append processor doesn't work inside the foreach processor:

    POST _ingest/pipeline/_simulate
    {
      "pipeline": {
        "description": "test",
        "processors": [
          {
            "foreach": {
              "field": "values",
              "processors": [
                {
                  "append": {
                    "field": "flat",
                    "value": [
                      "foo"
                    ]
                  }
                }
              ]
            }
          }
        ]
      },
      "docs": [
        {
          "_index": "index",
          "_type": "type",
          "_id": "id",
          "_source": {
            "values": [
              "one",
              "two"
            ]
          }
        }
      ]
    }

**Comment by martijnvg** [comment]
The `foreach` processor was build to only access the fields form the the current json object being processed. Only `_value` key is available in all processors under the `foreach` processor. This context variable changes whenever this processor moves the next json object in the array.

The `foreach` processor should be changed to have the rest of document in its context as well. (`_value` remains to be a special key)
