### ISSUE TITLE
SortBuilderParser.fromXContent is only called by tests

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#17153]
I was looking into https://github.com/elastic/elasticsearch/issues/17085 and I saw that SortBuilderParser.fromXContent is only called by tests. Should it be removed?

**Comment by nik9000** [comment]
I feel like I have to be missing some invocation....

**Comment by cbuescher** [comment]
@nik9000 SortBuilderParser is a new interface we introduced for the ongoing sort builder refactoring. The method will be used once we cut over to use the refactored sort builders in SearchSourceBuilder. So no, we will need it ;-)
