### ISSUE TITLE
doc discrepancy: the scroll_id parameter does not change between scrolled pgaes

### ISSUE THREAD

**Issue by JoeZ99** [elastic/elasticsearch#17151]
**Elasticsearch version**:
2.2.0
**JVM version**:
1.7.0
**OS version**:
fedora 21
**Description of the problem including expected versus actual behavior**:
at https://www.elastic.co/guide/en/elasticsearch/reference/2.2/search-request-scroll.html

it states that 

>>"The initial search request and each subsequent scroll request returns a new _scroll_id — only the most recent _scroll_id should be used."

But the scroll_id parameter never changes. it's given on the first scrolling request (The one which doesn't have scroll_id in their body), and then it's never returned. 

If you keep using the same scroll_id you move forward through the scrolled results pages

That's not very API, because the same GET request with the same `scroll_id` parameter produces different results

**Steps to reproduce**:
 1.
make an initial scroll request

```
curl localhost:9200/twitter/tweet/_search?scroll=1m
```

The results come with the `_scroll_id` key

 2.

make a second request of the scrolled results

```
curl http://localhost:9200/_search/scroll?scroll_id={{scroll_id}}
```
- the results correspond to the scroll second page
- no `_scroll_id` key is present
 3.
keep doing the same rqeuest

it keeps returning different results

**Provide logs (if relevant)**:

**Comment by clintongormley** [comment]
You're missing the `scroll=1m` parameter.  The scroll expiry time needs to be refreshed on every scroll request

**Comment by JoeZ99** [comment]
well, yes, sorry I skipped that, and there is indeed a `_scroll_id` key returned in every rrequest. But the issue (doc discrepancy) remain the same. 

  - At the doc, it says
  "The initial search request and each subsequent scroll request returns a new _scroll_id — only the most recent _scroll_id should be used."

  - There is a scroll_id present in any response, **but it's always the same scroll_id**, so you get different results with exactly the same GET request.

**Comment by clintongormley** [comment]
> There is a scroll_id present in any response, but it's always the same scroll_id, so you get different results with exactly the same GET request.

Yes? What's the problem with that?

**Comment by clintongormley** [comment]
The scroll ID will change when a shard exhausts its result set.

**Comment by JoeZ99** [comment]
no problem at all, just wanted to be sure. I was under the impression that a good GET request should provide exactly the same result when exactly the same resource is asked (I think I read it somewhere from RESTfull theorists). Anyway, maybe in the doc could be stated that scroll_id "may" be different and then the last one should be used.

Ok, txs again!

**Comment by TimHeckel** [comment]
I echo the sentiment that the documentation should change from:

`The initial search request and each subsequent scroll request returns a new _scroll_id — only the most recent _scroll_id should be used.`

to something like:

`The initial search request and each subsequent scroll request returns a _scroll_id that may be different from the previous one — only the most recent _scroll_id should be used.`

**Comment by PiotrPapala-awin** [comment]
+1 for @TimHeckel last comment. 

I spotted the same problem tonight on 1.7.3. Got 5 scroll ids which are the same. It is kind of misleading. Would be great to update docs accordingly.

**Comment by clintongormley** [comment]
@PiotrPapala-awin @TimHeckel Fancy sending a pull request to fix the docs?

**Comment by salar-khan-symc** [comment]
Agreed with @TimHeckel . I wasted 4 hours on this.

**Comment by seuzyl** [comment]
hello everybody, what does "the most recent _scroll_id" mean? if one scroll fails,  what will happen if  retry with the same scroll_id?
