### ISSUE TITLE
Feature request: Automatically install plugins

### ISSUE THREAD

**Issue by abtpst** [elastic/elasticsearch#17155]
So if i want to install any plugins, i have to run the `kibana plugin` command. Its a bit cumbersome as i have to install each plugin individually. Can i specify just the names of the plugins somewhere and when `kibana` starts up, it will automatically install these plugins. I remember that in Kibana 4.1.x, i could add the following to the `kibana.yml` file

    bundled_plugin_ids:
     - plugins/dashboard/index
     - plugins/discover/index
     - plugins/doc/index
     - plugins/kibana/index
     - plugins/markdown_vis/index
     - plugins/metric_vis/index
     - plugins/settings/index
     - plugins/table_vis/index
     - plugins/vis_types/index
     - plugins/visualize/index

is this for already installed plugins? Or is it a way to specify auto install of plugins? Can we do something similar for Kibana 4.4.x?

How would we do this for Elastic?

**Comment by makeyang** [comment]
add if it supports hot install, that would be great.

**Comment by clintongormley** [comment]
You should open this issue in the kibana issues list

**Comment by abtpst** [comment]
thanks, but can we also do something similar for elastic? auto install the plugins?

**Comment by clintongormley** [comment]
No we can't.  Plugins need to be installed before starting Elasticsearch.  If you have lots of plugins to install, then it would be better to do this with puppet or chef or some other automation tool.
