### ISSUE TITLE
ES 2.2.0: different scrolling response depending on a deprecated search_type=scan parameter.

### ISSUE THREAD

**Issue by JoeZ99** [elastic/elasticsearch#17150]
**Elasticsearch version**:
2.2.0
**JVM version**:
1.7.0

**OS version**:
Fedora 21
**Description of the problem including expected versus actual behavior**:

When making an initial scroll request, if `search_type=scan` parameter is included, the response only contains scroll data. If not, it also contains the first page of results. According to the doc, `search_type=scan` is deprecated and shouldn't have any effect on that regards.

**Steps to reproduce**:
 1
.
```
curl localhost:9200/twitter/tweet/_search?scroll=1m
```

```
{
    "_scroll_id": "cXVlcnlUaGVuRmV0Y2g7MjszOTp1NHA1TXF4dFJIT0lwbVBTSkE5TThROzQwOnU0cDVNcXh0UkhPSXBtUFNKQTlNOFE7MDs=",
    "took": 1,
    "timed_out": false,
    "_shards": {
        "total": 2,
        "successful": 2,
        "failed": 0
    },
    "hits": {
        "total": 999,
        "max_score": null,
        "hits": [
            {..},{..}
         ]
     }
}
```
 2.
```
curl localhost:9200/twitter/tweet/_search?scroll=1m&search_type=scan
```

```
{
    "_scroll_id": "c2NhbjsyOzQxOnU0cDVNcXh0UkhPSXBtUFNKQTlNOFE7NDI6dTRwNU1xeHRSSE9JcG1QU0pBOU04UTsxO3RvdGFsX2hpdHM6OTk5Ow==",
    "took": 1,
    "timed_out": false,
    "_shards": {
        "total": 2,
        "successful": 2,
        "failed": 0
    },
    "hits": {
        "total": 999,
        "max_score": 0,
        "hits": []
    }
}
```
 3.

see how the two results are different
**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jasontedor** [comment]
> According to the doc, `search_type=scan` is deprecated and shouldn't have any effect on that regards.

Scans have [always](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-request-scroll.html#scroll-scan) behaved in this fashion.

> The response of the initial search request will not contain any results in the `hits` array. The first results will be returned by the first scroll request.

Instead of using a scan, you should use a scroll with sort on `_doc`:

```
GET /twitter/tweet/?scroll=1m
{
    "sort": [
        "_doc"
    ]
}
```

The deprecation just means that the feature will be removed, not that its behavior changed.

**Comment by JoeZ99** [comment]
oops. I really got wrong the meaning of "deprecated". Sorry and thank you.

**Comment by jasontedor** [comment]
> Sorry and thank you.

No need to be sorry at all, I'm glad that we could help clear it up. :smile:
