### ISSUE TITLE
Regression Metric Aggregator

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#17154]
This feature will extend #16817 by adding a single pass [Regression](https://en.wikipedia.org/wiki/Linear_regression) metric aggregator for computing a [Simple Linear Regression](https://en.wikipedia.org/wiki/Simple_linear_regression). (Single pass Multiple Linear Regression can be added as a follow on enhancement). The purpose is to compute and report the slope/intercept of the simple OLS trendline between each variable. 

Example usage (analyzing US Census data with mortality rates):

``` javascript
"my_regression" : {
    "regression" : {
        "field" : [ "poverty", "mortality", "income", "crime", "doctors"],
    }
}
```

**Comment by k2xl** [comment]
Gets pushed back and back - this would be really useful especially considering prelert just joined elastic team

**Comment by markharwood** [comment]
cc @elastic/es-search-aggs

**Comment by wchaparro** [comment]
Closing as not planned, focus on ES|QL development
