### ISSUE TITLE
Field alias

### ISSUE THREAD

**Issue by carlosvega** [elastic/elasticsearch#17163]
I found that, despite fields with parentheses are valid on Kibana, timelion do not allow it even if they are escaped or enclosed into quotation marks. I opened an issue in the Timelion github but, I thought, what about alias of fields?, sometimes there are long fields with details about the metric (like if it's on ms or seconds) and could be quite useful to have field alias on elasticsearch or kibana. Like the index alias.

**Comment by clintongormley** [comment]
Hi @carlosvega 

This seems relevant to Kibana only.  I'd suggest opening this issue in the Kibana issues list instead.

**Comment by carlosvega** [comment]
No it is relevant to Elasticsearch the same way the index aliases are. This could be useful in general for the REST API of elastic as well.

**Comment by clintongormley** [comment]
> sometimes there are long fields with details about the metric (like if it's on ms or seconds)

that is kibana only, nothing to do with elasticsearch.  

if you're talking about adding an alias from eg `foo(bar)` to `foo_bar`, I don't really see the point of cluttering your mappings (and the cluster state) with this.  Instead, you could use an ingest pipeline to rename the field, or the `copy_to` mapping parameter to do something similar.

**Comment by carlosvega** [comment]
In fact, it is a Timelion issue (already done that issue), but I thought it would be an interesting suggest for elasticsearch. 

I know I could add a new field with the same value to all my documents but that could take too long. I will do that now, but it could be a nice feature to avoid this.
