### ISSUE TITLE
CI: QueryProfilerIT.testProfileMatchesRegular failures

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#17164]
This fails reproducibly on 2.3 branch:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+2.3+multijob-os-compatibility/os=amazon/4/
Revision: a1f927d293c08ea1620fb87ad4f58602b9069dc7

mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch:elasticsearch -Dtests.seed=C45E4C78F8107B36 -Dtests.class=org.elasticsearch.search.profile.QueryProfilerIT -Dtests.method="testProfileMatchesRegular" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=en-AU -Dtests.timezone=America/Tortola

**Comment by cbuescher** [comment]
@polyfractal would this be something you can look into?

**Comment by polyfractal** [comment]
@cbuescher On it, thanks for the ping.
