### ISSUE TITLE
Feature: Configuration paremeter for rejecting operation immediately when there is no master node

### ISSUE THREAD

**Issue by pedro-dlfa** [elastic/elasticsearch#17170]
**Describe the feature**:

Currently, when there is no master node, read operations over an index works as usual. 
However, index or update operations returns 503 after 60 seconds:

```
REQUEST:
curl -X PUT -H "Cache-Control: no-cache" -H "Postman-Token: d7f328a2-0f41-2189-15cf-9fc2af3dc2b3" -d '{"field" : "valueMocoloco1"}' "http://AAA.BBB.CCC.DDD:9200/index1/type1/document1"

RESPONSE:
{
  "error": {
    "root_cause": [
      {
        "type": "cluster_block_exception",
        "reason": "blocked by: [SERVICE_UNAVAILABLE/2/no master];"
      }
    ],
    "type": "cluster_block_exception",
    "reason": "blocked by: [SERVICE_UNAVAILABLE/2/no master];"
  },
  "status": 503
}
```

A similar case happens with cluster status request (cat indices, aliases or cluster health), returning after 30 seconds

```
REQUEST:
curl -X GET -H "Cache-Control: no-cache" -H "Postman-Token: 4e2c6bc1-1c55-59f3-3160-7f44d9a41375" "http://AAA.BBB.CCC.DDD:9200/_cluster/health"

RESPONSE:
{
  "error": {
    "root_cause": [
      {
        "type": "cluster_block_exception",
        "reason": "blocked by: [SERVICE_UNAVAILABLE/2/no master];"
      }
    ],
    "type": "cluster_block_exception",
    "reason": "blocked by: [SERVICE_UNAVAILABLE/2/no master];"
  },
  "status": 503
}
```

As all the elasticsearch nodes know the cluster state, the desired feature is to include a configuration value for allowing to have immediate answer from an elasticsearch node (with the appropiate error) in case there is no master node in the cluster.

**Comment by s1monw** [comment]
why don't you just check the status periodically? Serving read requests is fine only updates are not possible in such a case?

**Comment by pedro-dlfa** [comment]
Indeed, what I would like also is to check the status periodically, but without having to wait such long timeout.

I could check that elasticsearch allows a "timeout" parameter in the requests. E.g: 

`curl -X GET -H "Cache-Control: no-cache" -H "Postman-Token: 4e2c6bc1-1c55-59f3-3160-7f44d9a41375" "http://AAA.BBB.CCC.DDD:9200/_cluster/health?timeout=5s"`

However, it would be cleaner and simpler to have a general configuration value instead of having to include that "timeout" parameter in every request.

**Comment by s1monw** [comment]
we have the main action for this. you can just periodically poll `localhost:9200/` or whatever your rest endpoint is and it will respond with `503` immediately

**Comment by pedro-dlfa** [comment]
Right now I'm checking the status of a specific index by checking that a specific alias is linked to an index, and then check the index health.

Calling `localhost:9200/` would mean an extra call, and also "understand" that the `503` would mean that something in the cluster is wrong, but also read operations works, but not the others.

But, could there be any other scenario where `localhost:9200/` returns `503` but read operations doesn't work?

**Comment by bleskes** [comment]
if you are interested in monitoring no master specifically, you can also use `GET _cat/master` and see whether it gives a value. Also, each indexing operation takes a timeout parameter which you can reduce if the default 60s.

**Comment by clintongormley** [comment]
I'm also curious as to why you see no master so frequently that you want to add an option to cope with it?

**Comment by bleskes** [comment]
Another option that might help is to set the timeout on the indexing request to 0, which will make it fail immediately if there is no master (or no primary available):

```
curl -XPUT "http://localhost:9201/index/type/1?timeout=0" -d'
{
  "f": 1
}'
```

Note though that you will need to create all your indices in advance if you do this and not rely on them to be created automatically. 

I'm closing this now as I think we covered all the possible options. Let me know these don't cover what you want to do.
