### ISSUE TITLE
Non-deterministic ordering of nodes in _cat APIs

### ISSUE THREAD

**Issue by samcday** [elastic/elasticsearch#17178]
**Elasticsearch version**: 2.2.0

**JVM version**: 1.8.0_65

**OS version**: Ubuntu 15.04

**Description of the problem including expected versus actual behavior**: When hitting any Cat APIs that deal with the list of nodes, the ordering of the nodes is non-deterministic, so depending on which node handles the request, the ordering will be different.

The following APIs are affected:
 * _cat/nodes
 * _cat/allocation
 * _cat/nodeattrs

I'm inclined to raise this as a bug, since the ordering used to be deterministic in 1.7.

**Steps to reproduce**:

0. Setup a cluster with at least two nodes
1. Hit _cat/nodes and note the ordering of entries
2. Hit _cat/nodes on a different node in the cluster and note the ordering is different

**Comment by jasontedor** [comment]
Duplicates #16575, duplicates #16975

**Comment by samcday** [comment]
@jasontedor I'm not sure this is necessarily a duplicate of those issues. This seems like a regression because in Elasticsearch 1.x the ordering had some kind of determinism. #16975 talks about some kind of user-controlled sorting. While that would be nice, I would just be content with deterministic sorting again :)

**Comment by jasontedor** [comment]
> I'm not sure this is necessarily a duplicate of those issues.

@samcday I understand where you're coming from, but I think that the outcome for this issue will be the same as the outcome for #16975. Either sorting will be implemented, or it won't but I don't think we will do an in-between measure just to get deterministic ordering. Does that make sense?

**Comment by samcday** [comment]
Yeah that makes sense, but my fear is that something like a sorting option in the Cat API might be considered a low priority feature request. Whereas in this case I think the new behaviour is a regression that actually has a surprisingly negative #UX impact when trying to investigate a large cluster with 30-40+ nodes.

**Comment by jasontedor** [comment]
> Yeah that makes sense, but my fear is that something like a sorting option in the Cat API might be considered a low priority feature request.

@samcday That statement is *not* incorrect, and I totally understand you here.

> Whereas in this case I think the new behaviour is a regression that actually has a surprisingly negative #UX impact when trying to investigate a large cluster with 30-40+ nodes.

Is there a reason that you can't pipe the output through `sort`?

**Comment by samcday** [comment]
There's no reason I can't do that, but more often than not I prefer to hit the cat APIs from a browser when doing ad-hoc investigations. This is because we use Shield, and the browser will remember my auth across multiple requests. Whereas if I use curl I have to mess with my `.netrc` or fiddle around with putting my password in each request.

**Comment by jasontedor** [comment]
@samcday That is a 100% valid observation; thanks for putting it in my mind.

**Comment by excalq** [comment]
This would make working with ES in Postman so much better, especially when doing Ops work with numerous log indices...

**Comment by clintongormley** [comment]
See https://github.com/elastic/elasticsearch/pull/20658
