### ISSUE TITLE
Ubuntu 14 complaining that the deb package is bad quality

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#17185]
While installing the DEB package downloaded from here on Ubuntu 14.04:
https://www.elastic.co/thank-you?url=https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.2.1/elasticsearch-2.2.1.deb

> The package is of bad quality
> 
> The installation of a package which violates the quality standards
> isn't allowed. This could cause serious problems on your computer.
> Please contact the person or organisation who provided this package
> file and include the details beneath.
> 
> Lintian check results for /home/user/Setups/elasticsearch-2.2.1.deb:
> E: elasticsearch: dir-or-file-in-var-run var/run/elasticsearch/

This has been reported previously in https://github.com/elastic/elasticsearch/issues/2515 and https://github.com/elastic/elasticsearch/issues/14532 and was previously resolved in https://github.com/elastic/elasticsearch/commit/a5f9173e14ae1f96ad786b81d8639a30693d9c9a

It looks like we need to revisit the lintian overrides

**Comment by jordansissel** [comment]
I think this is due to using the Ubuntu App Center (or something?) to install the package.

`dpkg` and `apt-get` do not complain about this:


Example using dpkg:

```
root@ubuntu-2gb-sfo1-01:~# lsb_release -d
Description:    Ubuntu 14.04.4 LTS

root@ubuntu-2gb-sfo1-01:~# wget https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.2.1/elasticsearch-2.2.1.deb

2016-03-18 07:31:28 (8.63 MB/s) - ‘elasticsearch-2.2.1.deb’ saved [29307500/29307500]

root@ubuntu-2gb-sfo1-01:~# dpkg -i elasticsearch-2.2.1.deb
Selecting previously unselected package elasticsearch.
(Reading database ... 86823 files and directories currently installed.)
Preparing to unpack elasticsearch-2.2.1.deb ...
Creating elasticsearch group... OK
Creating elasticsearch user... OK
Unpacking elasticsearch (2.2.1) ...
Setting up elasticsearch (2.2.1) ...
Processing triggers for ureadahead (0.100.0-16) ...
```

**Comment by clintongormley** [comment]
Yes, apparently the App Center does a Lintian check.  That said, we added Lintian overrides to work around this previously, but it looks like we need to update them.

**Comment by nik9000** [comment]
I guess it is just more stuff to add to the bats tests....

**Comment by LeeDr** [comment]
Do we know the steps to reproduce this?  I've only used dpkg and apt-get to install.  We likely have the same issue across our other products?

**Comment by nik9000** [comment]
> Do we know the steps to reproduce this?

We can likely run the same linting the App Center does. I haven't made sure of it but I'm 99% sure we can reproduce if we want.

**Comment by jakommo** [comment]
Looks like it's https://lintian.debian.org/tags/dir-or-file-in-var-run.html

**Comment by jasontedor** [comment]
> It looks like we need to revisit the lintian overrides

I don't think that we should override this one; I think that we should move the creation of `/var/run/elasticsearch` to the init script (instead of when the package is installed), and destroy it when the service stops (instead of when the package is removed).

**Comment by nik9000** [comment]
I'm ok with that.
