### ISSUE TITLE
[feature request]smart routing detection when search

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#17184]
**Describe the feature**:
if mapping of a index has routing field:
 "_routing": {
          "path": "XXX",
          "required": true
        },

when search without explicit set rouing field but has term XXX, ES better detect it and add routing parameters

**Comment by clintongormley** [comment]
`path` is no longer supported in `_routing`, and search by default goes to all shards so routing isn't required.  If you want to limit search to specific shards then you need to specify the routing yourself

**Comment by makeyang** [comment]
you don't get my point at all, do u?

**Comment by clintongormley** [comment]
No
