### ISSUE TITLE
Marvel doesn't load (Cannot read property 'cluster_name')

### ISSUE THREAD

**Issue by calexicoz** [elastic/elasticsearch#17189]
**Elasticsearch version**: 2.2.1

**JVM version**: OpenJDK 1.7.0.95

**OS version**: Debian 7, Kernel 3.10

**Description of the problem including expected versus actual behavior**:

Hi there,

I just installed Marvel for the first time on a production cluster running  Kibana 4.4.2, ES 2.2.1. Followed the installation instructions, but when I try to load Marvel, I get:

```
Marvel: Error 400 Bad Request: Cannot read property 'cluster_name' of undefined
```

Calling `/api/marvel/v1/clusters` returns the same:

```
{
  statusCode: 400,
  error: "Bad Request",
  message: "Cannot read property 'cluster_name' of undefined"
}
```

`cluster.name` is defined in `elasticsearch.yml` and shows (as `cluster_name`) with a `curl localhost:9200`.

So I'm not quite sure what's going on. The Marvel agent is definitely running, and I have the Marvel indices created (I already tried deleting them and recreating them):

```
.marvel-es-2016.03.16
.marvel-es-2016.03.17
.marvel-es-data
```

I also tried  stopping all the nodes and restarting them. Ideas?

Thanks!

PS: I also filed this [in the forum](https://discuss.elastic.co/t/marvel-refusing-to-load-cannot-read-property-cluster-name-of-undefined/44640) but got no response. I'm not sure whether this is an actual bug or some mistake on my part. Either way, any help debugging the issue will be welcome.

**Comment by clintongormley** [comment]
Looks like the issue has been discussed in the forum already, so I'll close this
