### ISSUE TITLE
accessing matched term in script score function

### ISSUE THREAD

**Issue by q11112345** [elastic/elasticsearch#17180]
i have some problem with script score.
i want to caculate the score with matched term.
in most situation,  i just need the count of matched term. 
but i want to know what term are the matched terms, and i can do some adjusting to different terms.

for query string "test A B C"
terms analyzed by index's analyzer will be: "test" "A" "B" "C"

if i just know the count of matched terms to one document, the score will be  4, 3, 2, 1 or 0.
but i want to have some extra points to term "A", 
the point will be like this:  A*10 + B * 1 + C * 1

someone has asked for the same problem before, but his has a little different from mine.

https://github.com/elastic/elasticsearch/issues/13806

i need the query string analyzed by indexer's analyzer.  the query string are always given by user input, i thinks its better be analyzed by es, i just have to make some policy to the terms analyzed by es.

**Comment by clintongormley** [comment]
Hi @q11112345 

If you want to implement custom scoring like this, then you need to use more structured queries than just a high level match or query string query, eg use the function score query.

The right place to ask questions like these in the forum instead: https://discuss.elastic.co/

thanks

**Comment by q11112345** [comment]
what will the "more structured queries" looks like?
like the example given in  issue 13806? 
i understand the example you have replied to the author in issue 13806.
my problem is , i cant analyze the "query string" to terms myself, or i dont want to analyze the "query string" to terms myself.
i want all the string in querying to behave the same way, processed by es all the time. i just need to controll the scoring in script score.



there is always no response to my problems in discuss.elastic.co ...so i have to ask here. and i find someone getting the same problem and getting the answer here.

thanks anyway.
