### ISSUE TITLE
plugin_name.enabled: false should prevent loading of the plugin

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#17192]
Currently, it's up to a plugin to recognize that it has been disabled and avoid initializing its parts.

We should enforce this at the ES level instead and simply avoid even loading the plugin entirely. Now that we require the plugin to have its name provided in the plugin descriptor, we can use that to automatically discover:

``` yaml
plugin_name.enabled: false
```

In that case, we should skip any handling of the plugin and log that it was disabled explicitly.

**Comment by rjernst** [comment]
I don't think this is the job of ES. If a user doesn't want a plugin to run, they can remove it. I don't see any advantages to this functionality, only additional settings and behavior to maintain.

**Comment by pickypg** [comment]
I think that's the right operational strategy.

However, I find that I will sometimes disable different plugins for different use cases -- especially in development -- and it would be good to know that they're not even on the classpath to get the opportunity to change things.

**Comment by dadoonet** [comment]
I agree with Ryan here and actually I don't understand the use case. Is it for debugging reason? Like I want to test elasticsearch without a plugin but then re-enable it again?

Could you explain a bit more why you would like to have this @pickypg ?

**Comment by pickypg** [comment]
Debugging with the intent to re-enable.

**Comment by rjernst** [comment]
While I understand the intent, I don't think it is worth the complexity. If we were to have such a flag built in, plugins might want a way to disable such a flag (so they can maintain their own flag or even flags for multiple features of the plugin).  I'm closing this for now.  We can reopen in the future if new stronger use cases come to mind.
