### ISSUE TITLE
[bug report]transport_address shows wired

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#17207]
**Elasticsearch version**:1.7.0

**JVM version**:8u40

**OS version**:CentOS 6.6

when I execute _nodes/stats for my cluster, all nodes shows:
most nodes show: inet[/ipaddress:port]
but the only one show: inet[/ipaddress/ipaddress:port]
is this a minor bug of ES?

**Comment by jasontedor** [comment]
Can you please give an example and elaborate on what is that you're expecting?

**Comment by makeyang** [comment]
I can't show u the exact ip address. thing is: when execute _nodes/stats, most nodes show below:
"transport_address": "inet[/172.0.0.1:9300]",but there is one node shows:
"transport_address": "inet[172.0.0.2/172.0.0.2:9300]",
I guess the format shoud be ip:port, but why this one shows ip/ip:port

**Comment by jasontedor** [comment]
It's not a bug. The `InetSocketTransportAddress` wraps a `InetSocketAddress` which will print `hostname/addr:port` if both `hostname` and `addr` are available but otherwise just `/addr:port`. I suspect this is due to your configuration.

**Comment by makeyang** [comment]
@jasontedor  
can you help to be more specified?
how did es get hostname?
how did es get addr ?

**Comment by jasontedor** [comment]
I can't because I'm certain this i highly dependent on your configuration.

**Comment by makeyang** [comment]
will, which key in config/enviromemnt variable decide hostname and which decide addr?

**Comment by jasontedor** [comment]
The unicast host list, and *your* local DNS configuration *all* play a rôle here in the 1.x line (and maybe some other network settings too, perhaps bind hosts and publish hosts).

**Comment by makeyang** [comment]
maybe and perhaps, which are not good.
by the way, can you just give a certain way to reproduce it? for one node to shows "transport_address": "inet[172.0.0.2/172.0.0.2:9300]"?

**Comment by jasontedor** [comment]
> maybe and perhaps, which are not good.

Why? I'm sorry, but I'm completely missing why this is such a big deal. 

> for one node to shows "transport_address": "inet[172.0.0.2/172.0.0.2:9300]"?

For that node, you need to look at your network settings (`network.host`, `*.publish_host`, etc.) and all relevant DNS configuration. Are you using a cloud provider with a custom resolver?

I do not see an issue here, and the best place for any future discussion on this is on the [Elastic Discourse forums](https://discuss.elastic.co).
