### ISSUE TITLE
painful!!! postgres-->logstash-->elasticsearch  mapper_parsing_exception!!

### ISSUE THREAD

**Issue by wharstr9027** [elastic/elasticsearch#17202]
hi, I am so sorry to  bother you, but now I am painful and rage about a problem. the problem has spent more that one weeks. and so sad I cann't find any useful information, even if I sent an email to nicerobot because I saw his questions linked  https://github.com/elastic/elasticsearch/issues/6492. but no response.  anyone any comments and suggestions, I really appreciate that.

The exception information is(when I start the logstash) : 
"@version"=>"1", "@timestamp"=>"2016-03-19T06:13:00.399Z", "coordinates"=>[[#<BigDecimal:4b06d615,'0.1194470174E3',10(12)>, #<BigDecimal:6f1f846d,'0.303230396E2',9(12)>], [#<BigDecimal:5cb7510d,'0.1194470149E3',10(12)>, #<BigDecimal:2d385b32,'0.303229822E2',9(12)>], [#<BigDecimal:50f396fe,'0.1194470161E3',10(12)>, #<BigDecimal:43dc4c61,'0.303229168E2',9(12)>], [#<BigDecimal:2585422e,'0.1194470219E3',10(12)>, #<BigDecimal:4a8b6c67,'0.303228748E2',9(12)>], [#<BigDecimal:60357ae,'0.119447031E3',9(12)>, #<BigDecimal:271dac4b,'0.303228477E2',9(12)>], [#<BigDecimal:28861eb4,'0.1194470463E3',10(12)>, #<BigDecimal:39ffb797,'0.303228234E2',9(12)>], [#<BigDecimal:255d2921,'0.1194470789E3',10(12)>, #<BigDecimal:6f68a635,'0.30322786E2',8(12)>], [#<BigDecimal:778366d2,'0.1194471988E3',10(12)>, #<BigDecimal:330434ba,'0.303227042E2',9(12)>], [#<BigDecimal:7fdc07da,'0.1194472167E3',10(12)>, #<BigDecimal:55af4f1a,'0.303226957E2',9(12)>]]}, "id"]}>>], :response=>{"index"=>{"_index"=>"dataservice-search", "_type"=>"dataservice-search", "_id"=>"28323", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [geometry]", "caused_by"=>{"type"=>"parse_exception", "reason"=>"shape must be an object consisting of type and coordinates"}}}}, :level=>:warn}
--------------------------------------------------------------------------
Firstly: logstash is used to export data from postgres. and my cocnfiguration file is : 

input {
    jdbc {
        # Postgres jdbc connection string to our database, mydb
        jdbc_connection_string => "jdbc:postgresql://**.**.**.**:5432/handle_service"
        # The user we wish to execute our statement as
        jdbc_user => "user"
        jdbc_password => "******"
        # The path to our downloaded jdbc driver
        jdbc_driver_library => "/home/admin/dataservice-search/elasticsearch-2.1.1/lib/postgresql-9.3-1102-jdbc41.jar"
        # The name of the driver class for Postgresql
        jdbc_driver_class => "org.postgresql.Driver"
        parameters => { "favorite_artist" => "Beethoven" }
        schedule => "* * * * *"
        # our query
        statement => " select st_asgeojson(st_makevalid(geom)) As geometry_offset_geo ,* from t_delete_road limit 20"
        type => "datasearch"
    }

}
output {
    stdout {codec => rubydebug }
        elasticsearch {
        index => "datasearch"
        document_type => "datasearch"
        document_id => "%{id}"
        hosts => [ "**.**.**.**:9200" ]
    }
}

second, I created the index in the elasticsearch:
curl -XPOST http://**.**.**.**:9200/datasearch/datasearch/_mapping  -d '{"datasearch":{"properties" : {"geometry_offset_geo":{"type":"geo_shape","tree":"quadtree","precision": "1m"}}}} '

third, I start the logstash. and then something was wrong.

But it's works when I use 
curl -XPOST 'http://**.**.**.**:9200/datasearch/datasearch/1' -d '{"geometry":{
"type":"Polygon",
"coordinates":[
[[-85.0018514,37.1311314],
[-85.0016645,37.1315293],
[-85.0016246,37.1317069],
[-85.0016526,37.1318183],
[-85.0017119,37.1319196],
[-85.0019371,37.1321182],
[-85.0019972,37.1322115],
[-85.0000002,37.1317672]]]
}
}'

I really wonder what happen among those steps. so I come here and ask for some help, please.
It's so important to me to solve this problem.

thank you so much!

**Comment by jasontedor** [comment]
Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions.

> third, I start the logstash. and then something was wrong.

When you do reach out to the community for help, you should provide more details about what you *expected* to happen, and what *actually* happened. Maybe your expectations are wrong, maybe what actually happened is not what we intended, but either way we can not assess the situation without understanding what you think should have happened, and what actually happened.

**Comment by wharstr9027** [comment]
ok, I see. thank you.
