### ISSUE TITLE
Groovy module not included in 2.2.0 maven package

### ISSUE THREAD

**Issue by anuraaga** [elastic/elasticsearch#17200]
**Elasticsearch version**: 2.2.0

**JVM version**: 1.8.0

**OS version**: Mac OS X

**Description of the problem including expected versus actual behavior**:

It seems the latest elasticsearch published artifact does not contain the groovy module.

When depending on the elasticsearch 2.2.0 jar using a maven dep like this

```xml
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch</artifactId>
  <version>2.2.0</version>
</dependency>
```
the GroovyScriptEngineService class is not on the classpath. Notably, this means that when trying to run putIndexedScript using a node client, it fails with "groovy" not a valid script_lang.

When depending on the elasticsearch 2.1.2 jar, GroovyScriptEngineService exists and the putIndexedScript command works fine (after adding groovy-all as a dependency per https://github.com/elastic/elasticsearch/issues/15867

**Comment by jasontedor** [comment]
The `lang-groovy` module is provided as a separate artifact with coordinates `org.elasticsearch.module:lang-groovy:2.2.0`.

**Comment by anuraaga** [comment]
Thanks for the pointer to the artifact, I could find GroovyScriptEngineService on the classpath now! But it seems with the separation of the modules something has changed in initialization - just having the dependency doesn't seem to be enough to enable groovy support, I still get script_lang not supported [groovy].

I have come up with this weird hack but is their an official way of loading the groovy plugin? Also all the docs indicate that groovy works out of the box, but since it doesn't seem to be true for node clients, it would be nice to mention the appropriate settings in the documentation to avoid issues filed like this one :)

```java
// HACK: Define this class to expose a protected constructor that let's use
  // initialize GroovyPlugin.
  private static class PluginLoadingNode extends Node {

    private PluginLoadingNode(Settings preparedSettings) {
      super(InternalSettingsPreparer.prepareEnvironment(preparedSettings, null),
          Version.CURRENT,
          ImmutableList.<Class<? extends Plugin>>of(GroovyPlugin.class));
    }
  }
```

**Comment by jasontedor** [comment]
> just having the dependency doesn't seem to be enough to enable groovy support

> Also all the docs indicate that groovy works out of the box, but since it doesn't seem to be true for node clients

Correct, when a regular Elasticsearch node starts we look for the `lang-groovy` module (among others) but otherwise do not.

> I have come up with this weird hack but is their an official way of loading the groovy plugin? 

Yes. Note that this is what Elastiscearch does for its tests that depend on plugins. Also see the discussion on #15927.
