### ISSUE TITLE
Fast Vector Highlighter doesn't work on phrase searches

### ISSUE THREAD

**Issue by jacool** [elastic/elasticsearch#17215]
When searching with **simple_query_string** or **match_phrase** on a field defined with `"term_vector":"with_positions_offsets"` the highlighter doesn't produce a fragment despite the document being found. This happens when a stop-word appears in the query.

Easily reproducible:

```
PUT /test
{
  "mappings" : {
    "doc" : {
      "properties" : {
        "text" : {
          "analyzer" : "english",
          "term_vector" : "with_positions_offsets",
          "type" : "string"
        }
}}}}

PUT /test/doc/1
{
  "text" : "All humans are mortal. Socrates is human. Thus, Socrates is mortal."
}

GET /test/doc/_search
{
  "query" : {
    "simple_query_string" : { "query" : "\"humans are mortal\"", "fields" : ["text"] }
  },
  "highlight" : { "fields" : { "text" : {} }  },
  "_source" : false
}
```

The issue is reproducible in v1.6 and v2.2.1

At some point it has been claimed the issue can be worked around by setting `"enable_position_increments": false`, unfortunately this option is no longer accepted by ElasticSearch.

**Comment by clintongormley** [comment]
Agreed, this is a bug.  All I can offer you at the moment is to use a slop value, which results in highlighting.

**Comment by jacool** [comment]
It fails the same with slops, just replace my query above with this:
"query" : "\"humans are mortal thus\"~3"

**Comment by clintongormley** [comment]
Closing in favour of #21621
