### ISSUE TITLE
Plugins listed by different name to install name not automation friendly

### ISSUE THREAD

**Issue by gingerwizard** [elastic/elasticsearch#17228]
**Elasticsearch version 2.2.1**:

Installation of community plugins is achieved by using the command plugin install <plugin name> e.g. 

./plugin install lmenezes/elasticsearch-kopf

However, post install the plugins are typically listed by a name e.g. the above when is listed as simple "kopf"

./plugin list
Installed plugins in /opt/elastic/elasticsearch-2.2.1/plugins:
    - kopf

Any automation framework relies on being able to identify a delta between what is installed and what is requested.  The above requires a custom rule which seems both undocumented and alittle inconsistent e.g. it doesn't seem dropping the owner prefix ( lmenezes for the above) is sufficient.

This maybe out of the control of Elastic and a product of the packaging poor community plugins.  I therefore request that we simply store with the plugin a file indicating its install name e.g. in the same directory.

**Comment by rjernst** [comment]
That logic has been removed in 5.0. Whatever the name of the plugin in the plugin descriptor, that is the name we use as the installation directory and what is listed.

**Comment by gingerwizard** [comment]
@rjernst thankyou for this. It makes the automation work alot simpler.
