### ISSUE TITLE
Feature request: Garbage collection stats in _cluster/stats

### ISSUE THREAD

**Issue by McStork** [elastic/elasticsearch#17224]
Hello,
I couldn't find any ticket relating to this. Could it be possible to have stats about the garbage collector at the cluster level?
Right now, such data is only available in ```_nodes/stats``` but missing in ```_cluster/stats```.

**Comment by jasontedor** [comment]
@McStork I don't think that these metrics make sense at the cluster level, they are meaningful at the node level. Imagine if these were collected at the cluster level, but a node restarts. This means that the cluster-wide collection count and collection time would decrease and as such I don't see these metrics being useful at the cluster level.

**Comment by jasontedor** [comment]
No feedback, closing.
