### ISSUE TITLE
Update Warmer API documentation to indicate it is deprecated

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#17229]
The Warmer API has been deprecated in 2.x and will be removed in 5.0 (#15607). Please update product documentation to indicate status.

**Comment by jasontedor** [comment]
This is covered in the [migration docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_index_apis.html#_warmers) and redirects which say:

> Warmers have been removed. There have been significant improvements to the index that make warmers not necessary anymore.

The pull request #15614 shows additional changes to the docs. Do you think that this isn't enough?

**Comment by inqueue** [comment]
There are a lot of good changes to the future docs. Do you think we need something in 2.x documentation to indicate it is deprecated and going away entirely?

**Comment by jasontedor** [comment]
> Do you think we need something in 2.x documentation to indicate it is deprecated and going away entirely?

Yeah, I don't see anything there and you're right that something should be added. Thanks for raising this.

**Comment by jpountz** [comment]
OK I will add a deprecation warning.

**Comment by jpountz** [comment]
Done.
