### ISSUE TITLE
Check that S3 setting `buffer_size` is always lower than `chunk_size`

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#17244]
`chunk_size` is a Snapshot setting whatever the implementation is.
`buffer_size` is an S3 implementation setting.

Let say that you are snapshotting a 500mb file. If you set `chunk_size` to `200mb`, then Snapshot service will call S3 repository to snapshot 3 files with the following sizes:

* `200mb`
* `200mb`
* `100mb`

If you set `buffer_size` to `100mb` (AWS maximum size recommendation), the first file of `200mb` will be uploaded on S3 using the multipart feature in 2 chunks and the workflow is basically the following:

* create the multipart request and get back an `id` from AWS S3 platform
* upload part1: `100mb`
* upload part2: `100mb`
* "commit" the full upload using the `id`.

We should definitely check that the `buffer_size` setting is always lower than `chunk_size`. Otherwise, setting this value is useless.

May be we should also change the default values for `chunk_size` and `buffer_size` in the context of S3 plugin and define respectively them to `5tb` and `100mb`?

**Comment by dadoonet** [comment]
@imotov @tlrx WDYT?

**Comment by imotov** [comment]
Having specialized defaults from S3 makes perfect sense to me. `100mb` as a default for `buffer_size` looks reasonable. I am not sure about `5tb` though. I am a bit concerned that it might be too big considering S3 flakiness that we saw before and our default retry settings.
