### ISSUE TITLE
Dynamic mappings doesn't work for the keyword type

### ISSUE THREAD

**Issue by tsg** [elastic/elasticsearch#17241]
**Elasticsearch version**: 5.0.0-alpha1 snapshot bf98a44
**JVM version**: "1.8.0_45"
**OS version**: OS X

In topbeat we're using a dynamic mapping template like this:

```
      "dynamic_templates": [
        {
          "template1": {
            "mapping": {
              "doc_values": true,
              "ignore_above": 1024,
              "index": "not_analyzed",
              "type": "{dynamic_type}"
            },
            "match": "*"
          }
        }
```

The full template is here: https://gist.github.com/tsg/904710ed2514ffc7eed6

The template loads fine but I get an error at index time, saying "[text] fields do not support doc values". The full logs are here: https://gist.github.com/tsg/2119de476698f1228520

@jpountz explained that "now that string has been splitted into text and keyword, we made ${dynamic_type} be "text" for string fields so it is not possible to build mappings that have a dynamic type for keywords anymore." and we agreed to open this ticket to look for a solution together.

I tried to change "type" to "keyword" in the dynamic template, but that didn't help. Is there a way in the template to say "Fields are of type 'keyword' unless I explicitly define them"?

**Comment by jpountz** [comment]
Even though the `index=(not_)analyzed` trick can't be used anymore, the above template can be replaced with the following:

```
      "dynamic_templates": [
        {
          "template1": {
            "mapping": {
              "ignore_above": 1024,
              "type": "keyword"
            },
            "match_mapping_type": "string"
          }
        }
```

Since the use-case can still be addressed, I will close this issue. For the record, we did some related documentation efforts in #17413 to show how to address common problems that can be fixed with templates.
