### ISSUE TITLE
PluginManager: Use -E for system properties like Bootstrap

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#17250]
We should take the work done in #17088 and apply it to the PluginManager for consistency.

/cc @jasontedor

**Comment by rjernst** [comment]
It will be a little difficult, given how the plugin cli is structured. The environment is created in the main, before we've tried parsing any command line parameters. I'm not saying it's not possible, I'm just saying it will require some refactoring, it is not a couple line change.

**Comment by jasontedor** [comment]
> Use -E for system properties like Bootstrap

@pickypg Do you really mean `-E` for system properties? System properties should be passed as arguments to the JVM via `ES_JAVA_OPTS`, not via command-line arguments to Elasticsearch. A goal with the CLI parsing is to eventually remove the translation of the `-E` command-line arguments to system properties, and that's the primary driver for changing from `-D` to `-E` (to make it clear that `-D` arguments need to be passed as arguments to the JVM and the `-E` arguments need to be passed as arguments to Elasticsearch).

**Comment by pickypg** [comment]
I mean it as a replacement. Specifically, I want to remove https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java#L185 system property usage.

I suppose we can just come up with another way, unless we want to live with it being a system property. My whole driver is consistency since you just worked so hard to remove `-Des.*` it would be sad to see it live on here.

**Comment by rjernst** [comment]
I don't think we should replace that system property. It is specifically meant to be a system property. It is not a setting for elasticsearch.

**Comment by jasontedor** [comment]
@pickypg To be clear, it's okay if system properties live on, even system properties that are specific to Elasticsearch. What is not okay is the mixing of system properties with settings, and the mixing of the command-line flag used for setting system properties and settings.

**Comment by pickypg** [comment]
Fair enough. I think that finishes this one off.

> It is specifically meant to be a system property. It is not a setting for elasticsearch.

I don't totally agree with the semantics of that, but I think it's fine to disagree on it since it's not doing any harm.
