### ISSUE TITLE
[feature request]es config parameters are so mess. better clean them up

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#17266]
1. any parameters related to cluster level shoud have prefix cluster., like cluster.action.auto_create_index, even include cluster name
2. any parameters related to cluster level better config through API rather than config file
3. any parameters related to indices should make them cluster related and therefore, start with cluster., like cluster.indices.shards

**Comment by rjernst** [comment]
This issue never had any discussion come out of it. I'm going to close because reorganizing setting name hierarchy would be a massive undertaking that is simply not a priority.
