### ISSUE TITLE
Installation of Ingest Attachment

### ISSUE THREAD

**Issue by kan1207** [elastic/elasticsearch#17269]
I am new to the EKL tools and have installed Elasticsearch 2.2, but could not find ways to install the plugin ingest attachment processor as a substitute of mapper attachment.

Would anyone know any ways to do that?

**Comment by spinscale** [comment]
ingest is a feature of 5.0 only and not part of the 2.x releases... we intend to release a first alpha soon, so you can test it either then, or - if you cant wait - you could just build an elasticsearch distribution from the source itself.

**Comment by kan1207** [comment]
So a possible solution will be go back to an older version of ES and use mapper-attachment plugin?

**Comment by kan1207** [comment]
Thanks for the advice
