### ISSUE TITLE
Use Released Logstash and Beats templates to improve BWC testing

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#17275]
These templates are a good user of the template API and we should make sure we support them at least across major version. It won't be perfect in terms of testing but it can be a simple unit/integ test that just makes sure the dynamic mapping works

**Comment by tsg** [comment]
For your convenience, here  are the links to the Beats templates:

Topbeat: https://github.com/elastic/beats/blob/master/topbeat/etc/topbeat.template.json
Packetbeat: https://github.com/elastic/beats/blob/master/packetbeat/etc/packetbeat.template.json
Filebeat: https://github.com/elastic/beats/blob/master/filebeat/etc/filebeat.template.json
Winlogbeat: https://github.com/elastic/beats/blob/master/winlogbeat/etc/winlogbeat.template.json

I can also provide sample documents for each if it helps.
