### ISSUE TITLE
Can't highlight across has_child

### ISSUE THREAD

**Issue by chrisboyle** [elastic/elasticsearch#17283]
**Elasticsearch version**: 2.1.1

**JVM version**: 1.8.0_65 x86_64

**OS version**: Fedora Core 22

**Description of the problem including expected versus actual behavior**:
Using a top-level `inner_hits` to highlight a `nested` object in a child document produces hits with no highlighting.

This was alluded to on #14999 (martijnvg, 27 Jan) but seemingly isn't the focus of that issue or any other open one.

**Steps to reproduce**:
```
POST temporary
{
}

POST temporary/bunch/_mapping
{
  "_parent" : {
      "type" : "tree"
   },
  "properties": {
    "banana": {
      "type": "nested"
    }
  }
}

POST temporary/tree/1
{
}

POST temporary/bunch/1?parent=1
{
  "banana": [
    {
      "description": "a tasty banana"
    }
  ]
}

GET temporary/tree/_search
{
  "query": {
    "has_child": {
      "type": "bunch",
      "query": {
        "nested": {
          "path": "banana",
          "query": {
            "match": {
              "banana.description": "tasty"
            }
          }
        }
      }
    }
  },
  "inner_hits": {
    "children": {
      "type": {
        "bunch": {
          "inner_hits": {
            "some_highlight_name": {
              "path": {
                "banana": {
                  "highlight": {
                    "fields": {
                      "banana.description": {}
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

Expected: `inner_hits` to contain a highlighted `description` property like `"a <em>tasty</em> banana"`

Actual: `hits` object is present but no `highlights` object.

**Comment by clintongormley** [comment]
@martijnvg can you have a look at this?  Between https://github.com/elastic/elasticsearch/issues/16664 and https://github.com/elastic/elasticsearch/issues/16653 I'm not sure if the syntax is right or not.

**Comment by martijnvg** [comment]
@chrisboyle The reason that there is no highlight object in the response is because no query has been specified inside each inner hit. Unlike inner hits defined in the query, top level inner hits don't know about the inner query that has been used in the main query and therefor you need to redefine this. Like this:

```
curl -XGET "http://localhost:9200/temporary/tree/_search" -d'
{
  "query": {
    "has_child": {
      "type": "bunch",
      "query": {
        "nested": {
          "path": "banana",
          "query": {
            "match": {
              "banana.description": "tasty"
            }
          }
        }
      }
    }
  },
  "inner_hits": {
    "children": {
      "type": {
        "bunch": {
          "query": {
            "nested": {
              "path": "banana",
              "query": {
                "match": {
                  "banana.description": "tasty"
                }
              }
            }
          },
          "inner_hits": {
            "some_highlight_name": {
              "path": {
                "banana": {
                  "query": {
                    "match": {
                      "banana.description": "tasty"
                    }
                  },
                  "highlight": {
                    "fields": {
                      "banana.description": {}
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}'
```

This is confusing. Inner hits inlined with the query don't need this because these inner hit definition know about the context there have been specified in. At the moment multiple level of inner query inner hits don't work, but this will be fixed. Once this has been fixed top level inner hits will be deprecated (in 5.0) and eventually removed.

**Comment by chrisboyle** [comment]
@martijnvg Thanks, this solves our problem.

Note that it still works if you remove the query at inner_hits/children/type/bunch/query (as opposed to inner_hits/.../inner_hits/.../query).

**Comment by abhishek5678** [comment]
Hello @martijnvg This is not work for me.when i am running this query it's shows like that:
 "type": "parsing_exception",
            "reason": "Unknown key for a START_OBJECT in [inner_hits]

Please help me to resolve this problem and reply me as soon as possible

**Comment by martijnvg** [comment]
@abhishek5678 Please ask these questions on the forum instead of an issue that has been closed for more than a year. I'm happy to help you there.
