### ISSUE TITLE
Remove ability to specify arbitrary node attributes with `node.` prefix

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#17280]
Today the basic node settings like `node.data` and `node.master` can't really be fully validated since we allow to specify custom user attributes on the node level. We have to, in order to support that, add a wildcard setting for `node.*` to let these setting pass validation. Instead we should require a more contraint prefix like `node.attribute.` that defines a namespace that is reserved for user attributes. 
This can be breaking since validation will kick in and provide an error message accordingly.

**Comment by dadoonet** [comment]
+1

**Comment by uboness** [comment]
++ not critical but wondering if `node.metadata` would be a more appropriate namespace for it?

**Comment by s1monw** [comment]
> not critical but wondering if node.metadata would be a more appropriate namespace for it?

I am not sure since we call them `attributes`?

**Comment by clintongormley** [comment]
I prefer `attributes` as it is more concrete than metadata.  That said, personally I'd go for `node.attr.` instead.
