### ISSUE TITLE
Test Failure in Build: testScrollResponseBatchingBehavior

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#17299]
Unable to reproduce locally.

Build Failure (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=ubuntu/111/)

Suite: org.elasticsearch.index.reindex.AsyncBulkByScrollActionTests
  2> REPRODUCE WITH: gradle :modules:reindex:test -Dtests.seed=8701CF7C189CEEC2 -Dtests.class=org.elasticsearch.index.reindex.AsyncBulkByScrollActionTests -Dtests.method="testScrollResponseBatchingBehavior" -Des.logger.level=WARN -Dtests.security.manager=true -Dtests.locale=es-SV -Dtests.timezone=Pacific/Enderbury
FAILURE 0.01s J0 | AsyncBulkByScrollActionTests.testScrollResponseBatchingBehavior <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<{xssqpcyr=cauigsh}> but was:<null>
   > 	at __randomizedtesting.SeedInfo.seed([8701CF7C189CEEC2:3149B2EA2E7B5676]:0)
   > 	at org.elasticsearch.index.reindex.AsyncBulkByScrollActionTests.testScrollResponseBatchingBehavior(AsyncBulkByScrollActionTests.java:181)
   > 	at java.lang.Thread.run(Thread.java:745)
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-os-compatibility/os/ubuntu/modules/reindex/build/testrun/test/J0/temp/org.elasticsearch.index.reindex.AsyncBulkByScrollActionTests_8701CF7C189CEEC2-001
  2> NOTE: test params are: codec=Asserting(Lucene60), sim=RandomSimilarity(queryNorm=false,coord=crazy): {}, locale=es-SV, timezone=Pacific/Enderbury
  2> NOTE: Linux 3.13.0-83-generic amd64/Oracle Corporation 1.8.0_72-internal (64-bit)/cpus=8,threads=1,free=457043872,total=514850816
  2> NOTE: All tests run in this JVM: [UpdateByQueryWithScriptTests, ReindexScriptTests, AsyncBulkByScrollActionTests]
Completed [6/17] on J0 in 0.66s, 23 tests, 1 failure <<< FAILURES!

**Comment by nik9000** [comment]
Hey! This reproduces for me!

**Comment by nik9000** [comment]
This was a threading issue I think. I could reproduce it by putting the reproduction line in a bash while loop. It'd fail about 1/3 times for me. I pushed a fix and it hasn't failed since.

**Comment by s1monw** [comment]
@nik9000 thx I looked at it but didn't get what's wrong :)

**Comment by jdconrad** [comment]
@nik9000 Thanks for fixing this.  I admit I only ran the test a few times as there were a lot of other build failures to look into, but a bash loop seems like a great way to do this next time.
