### ISSUE TITLE
CI: MultiMatchQueryIT.testDefaults() fails reproducibly on master

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#17301]
This failed on CI today at: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/181

I was able to reproduce on master (d7874d9) with

REPRODUCE WITH: gradle :core:integTest -Dtests.seed=7722FDB11A68170E -Dtests.class=org.elasticsearch.search.query.MultiMatchQueryIT -Dtests.method="testDefaults" -Des.logger.level=WARN -Dtests.security.manager=true -Dtests.locale=th-TH -Dtests.timezone=America/Glace_Bay

Also fails with:
gradle :core:integTest -Dtests.seed=1DB8E9A029573C5C -Dtests.class=org.elasticsearch.search.query.MultiMatchQueryIT -Dtests.method="testDefaults" -Des.logger.level=WARN -Dtests.security.manager=true -Dtests.locale=th-TH -Dtests.timezone=America/Glace_Bay

**Comment by cbuescher** [comment]
Did some git bisect, looks like this started with e91a141.

**Comment by s1monw** [comment]
I think this is misleading - that PR changed some stuff in the base-class that intorduces some more random calls. I think that's why

**Comment by s1monw** [comment]
I am pretty sure this is caused by the new similarity in lucene 6

**Comment by cbuescher** [comment]
Looks like eed885e fixed this.
