### ISSUE TITLE
Document allowed and disallowed settings for the tribe node

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#17309]
**Elasticsearch version**: 2.2.1

As part of the [PR](https://github.com/elastic/elasticsearch/pull/16893#issuecomment-193349345) we changed the way (or fixed) how settings are passed through from the ES node to the tribe clients in the tribe node configuration.  There is a good suggestion in the PR to document the settings that are passed through to the tribe node clients, settings that are no longer allowed in the tribe client configurations, and settings that can be overridden in the tribe client's configuration.  But it doesn't look like this has been documented yet.  The following is what I have gathered - not sure if it's 100% correct. 

Passthroughs from ES node:

- node.name
- network.host
- network.bind_host
- network.publish_host
- transport.host
- transport.bind_host
- transport.publish_host
- path.home
- path.conf
- path.plugins
- path.logs
- path.scripts
- shield.* (for those using Shield)

Settings no longer allowed for the tribe clients (eg. t1, t2, etc..):

- path.*

Settings that are allowed for tribe clients (can override):

- network.host
- network.bind_host
- network.publish_host
- transport.host
- transport.bind_host
- transport.publish_host
- cluster.name
- discovery.zen.ping.unicast.hosts

Will be helpful to document this (or similar) for tribe node users.

**Comment by clintongormley** [comment]
@rjernst could you confirm this list of settings please?

**Comment by rjernst** [comment]
Technically any node settings can be set on the tribe client, it is only the ones we disallow that can't (ie path.*). The passthrough settings look correct (although note I would not mention path.home as this is not something a user ever sets). Also, node.name is not passed through, it is used to generate the name of the tribe client node.

**Comment by clintongormley** [comment]
thanks @ppf2
