### ISSUE TITLE
Move the percolator from core to a module

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#17317]
I think it is good to isolate the percolator from core. Many of its components (PercolatorFieldMapper, PercolatorQueryBuilder) allow for this. 

Two additional tasks need to be done to make this possible:
* Make IndexWarmers pluggable. The percolator has its own index warmer that loads the percolator queries.
* Allow for modules and plugins to add metrics to the node stats api. The percolator reports on the number of percolator queries loaded into memory.

**Comment by nik9000** [comment]
I like this idea! The nicest thing about the proposal is that you can run the tests for the percolator in isolation when all you've done is change percolator code. Much faster testing cycle. I did that with reindex and was very happy that I made it a module.

**Comment by javanna** [comment]
Question: besides that it is technically possible and it makes testing easier, what are the advantages of having percolator as a module? We generally use modules for things that we want to keep isolated because of dependencies, security policies etc. does the percolator have anything like this? or maybe there are other good reasons to use modules that I may have missed?

**Comment by nik9000** [comment]
> what are the advantages of having percolator as a module?

Technically you could ship Elasticsearch without percolation if you wanted but I don't see that as super compelling. Maybe it lets us cut the lucene-memory dependency from core? That isn't a big deal either, I don't think.

Beyond the testing speed improvement (which is mighty!) the most compelling argument for moving it out of core is that we can point to core and say "this is very extensible. we've moved core features into modules to demonstrate that you can too!"

So, yeah, I don't see a reason to work really hard on this but if it isn't particularly hard I think it is worth it.

**Comment by martijnvg** [comment]
@javanna I think the general goal is to make core slimmer? With that in mind moving the percolator to a module make sense.

**Comment by martijnvg** [comment]
@nik9000 The 'fast vector' highligher also relies on the `lucene-memory` memory dependency, so we still would need to have this dependency in core. (until we modularise highlighters too :) )

and I think the testing benefit you mentioned is important.

**Comment by nik9000** [comment]
> and I think the testing benefit you mentioned is important.

It takes about a minute for me to test reindex if I don't modify core. If I do I really should rerun the core tests and that takes 20 minutes. And testing reindex starts Elasticsearch twice - once with just reindex and once with groovy and reindex so it can play with them together.

**Comment by martijnvg** [comment]
Closed via #18511
