### ISSUE TITLE
MergeScheduler settings are not dynamically set

### ISSUE THREAD

**Issue by mkelkarbv** [elastic/elasticsearch#17326]
**Elasticsearch version**: 2.2.0

**JVM version**: 1.8

**OS version**: Mac OSX 10.10.5

**Description of the problem including expected versus actual behavior**: According to https://github.com/elastic/elasticsearch/blob/2.2/docs/reference/index-modules/merge.asciidoc, the merge scheduler supports "dynamic" setting of "index.merge.scheduler.max_thread_count". But when I try to set it dynamically, ES emits a warning which says the setting is ignored.

**Steps to reproduce**:
 1. start ES 2.2.0.
 2. issue this update -

curl -XPUT 'localhost:9200/_cluster/settings' -d '{
    "transient" : {
    	"index.merge.scheduler.max_thread_count": 1
    }
}'
 3. ES ignores the setting and emits this warning -

[2016-03-24 10:16:00,069][WARN ][action.admin.cluster.settings] [Dougboy] ignoring transient setting [index.merge.scheduler.max_thread_count], not dynamically updateable

**Provide logs (if relevant)**:

present in steps to reproduce.

**Describe the feature**:
The docs explicitly mentions that the setting is "dynamic", which to me means its can be set through the rest API. If the setting is not available through the REST API, then the docs need to clarify it.

**Comment by s1monw** [comment]
this is a per-index setting you have to use the index settings update API 

```json
curl -XPUT 'http://localhost:9200/your_index_name/_settings' -d '{
    "index" : {
        "merge.scheduler.max_thread_count": 1
    }
}
```
