### ISSUE TITLE
Kibana 5 error with ES 5.0-snapshot

### ISSUE THREAD

**Issue by palecur** [elastic/elasticsearch#17339]
**Elasticsearch version**: 5.0-snapshot

**JVM version**:

**OS version**: MacOS Yosemite

**Description of the problem including expected versus actual behavior**:

Upon loading data into Elasticsearch, the Discover tab displays an error (screenshot attached).

**Steps to reproduce**:
 1. On a fresh Kibana 5/Elasticsearch 5.0-snapshot install, load the tutorial datasets from https://www.elastic.co/guide/en/kibana/current/getting-started.html.
 2. Define the three index patterns
 3. Open Visualize.

**Provide logs (if relevant)**:

![screen shot 2016-03-24 at 14 41 52](https://cloud.githubusercontent.com/assets/1779279/14032280/ddb42cf8-f1ce-11e5-8ae6-64cec2fbeec0.png)

**Comment by jasontedor** [comment]
I think this should be opened in the [Kibana repository](https://github.com/elastic/kibana) until there is a verified bug in Elasticsearch here, no?
