### ISSUE TITLE
Are rescorers an extension point

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#17331]
Right now Elasticsearch only support one kind of rescorer: the query rescorer. But the code looks like we intended to support other rescorers. This feels like a place where Elasticsearch could expose an extension point and plugins could register additional rescorers the same way they can register additional queries. That doesn't work right now, but it wouldn't be too hard. If we did that we'd want to make an "example rescorer plugin" and all that.

By the same token, if we don't want to make rescorer an extension point we can clean up the class hierarchy and the parsing, including the public API.

**Comment by nik9000** [comment]
@brwe, I get the sense that you might have opinions on this.

**Comment by javanna** [comment]
I have the feeling that this was supposed to be extensible but we have broken it while refactoring things, maybe as part of the search refactoring. In fact the serialization bits are good, the parsing part needs some adapting though.

**Comment by cbuescher** [comment]
Looking at the 2.x branch, the RescoreParseElement was never able to parse more than the QueryRescorer (apropriately named `"query"`), so this seems like it was never supported, but we could certainly think about adding it (similar to suggesters). But I'm not sure it would be a widely used feature, since you can already do a lot with query rescoring. Might be mistaken on that part though.

**Comment by s1monw** [comment]
I think having the ability to implement a different rescorer is good and we should keep it. I also think this doesn't necessarily need to extend the search request parsing ie. when somebody want to pass something to the rescorer can they use `ext`? or maybe we just don't support it until somebody wants to do it and we add it laster. I think  we should maybe allow to register a different `Rescorer` but make the parse element not extendable?

**Comment by javanna** [comment]
Given that this extension point was never really there, and there was no much activity on this issue either, I would go for leaving things as they are (no extension point) and eventually add what we need to add later when needed. Closing.
