### ISSUE TITLE
Provide created flag to IndexingOperationListener#postCreate

### ISSUE THREAD

**Issue by oillio** [elastic/elasticsearch#17333]
I am working on a plugin that provides an IndexingOperationListener.  It would be very helpful if there was a way to tell if an indexing operation created or updated a document during the postCreate call.

**Describe the feature**:  The easiest way I see to provide this information would be to add a "created" field to the Engine.Index class.  This would be set during the index operation, just after the version is updated on this object ([here](https://github.com/elastic/elasticsearch/blob/e50eeeaffb33d7eaa0f7c2ebc71f1208460f4fcd/core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L368-L376)).

I would be happy to submit a PR for this, if it is an acceptable solution.

**Comment by s1monw** [comment]
I think this is useful but I think we should rather change the `    default void postIndex(Engine.Index index) {}` to be `default void postIndex(Engine.Index index, boolean created) {}` in `IndexingOperationListener` since it might be different on the primary and the replica? But please go ahead and submit a PR

**Comment by oillio** [comment]
PR submitted.  While looking through the code on master, it looks like the application of IndexingOperationListener has been changed significantly compared to 2.x.

From what I can tell, there is no longer any way for a plugin to register an IndexingOperationListener on a shard.

**Comment by s1monw** [comment]
> From what I can tell, there is no longer any way for a plugin to register an IndexingOperationListener on a shard.

yeah that is true, I trashed in a refactoring and planned to add it back later... I guess I dropped the ball... 
do you wanna open another PR and add it back similar to `IndexModule#addIndexEventListener(IndexEventListener listener)` there are also tests for this in `IndexModuleTests`. Your other PR looked awesome, I would be looking forward to you adding that missing API back too?

**Comment by s1monw** [comment]
FYI - nI was working on a similar functionality for search and added a register method on master for the `IndexingOperationListener` in https://github.com/elastic/elasticsearch/pull/17398
