### ISSUE TITLE
documentation - 2.2 breaking change - ClusterHealthStatus

### ISSUE THREAD

**Issue by brackxm** [elastic/elasticsearch#17346]
a breaking change for the java client:
in 2.2 ClusterHealthStatus moved to another package

**Comment by dadoonet** [comment]
Is it the same change as documented here? https://www.elastic.co/guide/en/elasticsearch/reference/current/float.html#_java_client

**Comment by danielmitterdorfer** [comment]
@dadoonet No, this is related but not the same change. I've created a mini PR for this. Can you please have look at #17444?

**Comment by danielmitterdorfer** [comment]
Fixed with #17444
