### ISSUE TITLE
ObjectParser and builders with required arguments

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#17352]
Many of our builders have required arguments: TermQueryBuilder, FieldValueFactorFunctionBuilder, etc. Normally when we use ObjectParser we have it call setter methods on pre-built objects. But that doesn't work for these objects. ObjectParser is much nicer than walking the xcontent on your own so we should figure out a way to overcome this. Ideas?

1. We could remove all the required parameters and/or create a constructor just for the ObjectParser. We already have static methods for lots of these builders anyway.
2. We could make `BuilderBuilder`s :scream:
3. We could dump everything in a map and pull it back out and build the object. Seems heavy.
???

**Comment by dakrone** [comment]
As an addition to this, it would be nice if ObjectParser could handle empty objects correctly, for example, If I define an `ObjectParser` with three fields and then send `{}`, I expect to get an object with the 3 vars in their default variable, however, ObjectParser blows up on this.

This is related to the comment I left about ObjectParser not working in https://github.com/elastic/elasticsearch/pull/17305

**Comment by nik9000** [comment]
> ObjectParser blows up on this

If you make a failing test I'll fix it. Deal?

**Comment by nik9000** [comment]
I'm fiddling with a solution for this.
