### ISSUE TITLE
Problems with searching documents with mapper-attachments plugin

### ISSUE THREAD

**Issue by jaxx** [elastic/elasticsearch#17359]
I have a problem with searching indexed documents with newest ES and mapper-attachment plugin. Longer discussion is located here https://discuss.elastic.co/t/problems-with-searching-from-document-contents-with-mapper-attachments-plugin/45534.

Elasticsearch version: 2.2.1 (only 1 node)
JVM version: 1.8.0u74
OS version: Windows 10 64-bit

You can reproduce the issue:

* Create index

```
PUT test_index
{
    "settings": {
        "number_of_shards": 2,
        "number_of_replicas": 0
    },
    "mappings": {
        "testfile": {
            "dynamic": "strict",
            "_source": {
                "enabled": true
            },
            "properties": {
                "fileId": {
                    "type": "integer",
                    "store": true
                },
                "contents": {
                    "type": "attachment"
                }
            }
        }
    }
}
```

* Index document with phrase "hello world"
* Check if document is indexed with match_all query

```
{
   "took": 2,
   "timed_out": false,
   "_shards": {
      "total": 2,
      "successful": 2,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 1,
      "hits": [
         {
            "_index": "test_index",
            "_type": "testfile",
            "_id": "AVO3TKC2-BSsruK6CY8T",
            "_score": 1,
            "_source": {
               "fileId": 101,
               "contents": "aGVsbG8gd29ybGQ="
            }
         }
      ]
   }
}
```

* Try to search the document with phrase query (no results)

```
POST test_index/_search
{
  "from": 0,
  "size": 1000,
  "fields": [
    "fileId"
  ],
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "contents": {
              "query": "hello",
              "type": "phrase"
            }
          }
        }
      ]
    }
  }
}
```

* Try to search  the document with query_string (1 result)

```
POST /test_index/_search
{
  "query": {
    "query_string": {
      "query": "hello"
    }
  }
}
```

This is unexpected behaviour because all this worked fine with ES 1.7.3. It feels like something is happened with match or match_phrase queries.

**Comment by GlenRSmith** [comment]
Possibly relevant:

After changing index to have only 1 shard

v2.2.1 throws an exception when attempting to load fielddata on a search result.

Using the query_string query that does succeed, the error is returned.

```
POST /test_index/_search
{
  "fielddata_fields": ["contents"], 
  "query": {
    "query_string": {
      "query": "hello"
    }
  }
}

{
   "error": {
      "root_cause": [
         {
            "type": "illegal_argument_exception",
            "reason": "failed to find field data builder for field contents, and type attachment"
         }
      ],
      "type": "search_phase_execution_exception",
      "reason": "all shards failed",
      "phase": "query_fetch",
      "grouped": true,
      "failed_shards": [
         {
            "shard": 0,
            "index": "test_index",
            "node": "NSripkQmT9qAZCuoTdzR9w",
            "reason": {
               "type": "illegal_argument_exception",
               "reason": "failed to find field data builder for field contents, and type attachment"
            }
         }
      ]
   },
   "status": 400
}
```

With v1.7.3, the fielddata is populated and returned.

```
POST /test_index/testfile/_search
{
  "fielddata_fields": ["contents"], 
  "query": {
    "query_string": {
      "query": "hello"
    }
  }
}
```

returns

```
{
   "took": 2,
   "timed_out": false,
   "_shards": {
      "total": 2,
      "successful": 2,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 0.095891505,
      "hits": [
         {
            "_index": "test_index",
            "_type": "testfile",
            "_id": "AVO7NoVgsHxrzUVsaSN9",
            "_score": 0.095891505,
            "_source": {
               "fileId": 101,
               "contents": "aGVsbG8gd29ybGQ="
            },
            "fields": {
               "contents": [
                  "hello",
                  "world"
               ]
            }
         }
      ]
   }
}
```

**Comment by eskibars** [comment]
query_string defaults to index.query.default_field (which is _all by default).  That's why the query_string is working as expected.

You can get your match_phrase query to work by searching field contents.content, which is mapper-attachments dumps the document content to (https://www.elastic.co/guide/en/elasticsearch/plugins/2.2/mapper-attachments-usage.html)

**Comment by jaxx** [comment]
We usually not store file content in index. We have

```
"_source": {
    "enabled": false
}
```
in mapping.

**Comment by jaxx** [comment]
If I'm building my queries with NEST and using expressions to get field names from properties, how do I know which field is meant for full-text search???

**Comment by dadoonet** [comment]
In your case it should be contents.content

**Comment by jaxx** [comment]
I understand, but if I have a class

```
public class ESFile
{
    public int Id { get; set; }
    public string Contents { get; set; }
}
```
And I'm building my queries like 
```
builder.Build<ESFile>(x => x.Id).Add(x => x.Contents);
```
How can I know which field is content field? Why this functionality changed compared to earlier versions?

**Comment by dadoonet** [comment]
I don't really remember why it changed. I think it was cleaner to not modify what the user entered and generate the content in another field.

So you send:

```js
{
  "foo": "base64"
}
```

It generates behind the scene:

```js
{
  "foo": {
     "foo": "base64",
     "content": "bar" 
  }
}
```

If you search in `foo`, it uses `foo.foo` (default behavior for multi fields). If you want to search in extracted text, you have to search in  `foo.content`.

But you have to know that it will change again in the future as mapper attachments plugin will be replaced by an ingest pipeline. See https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html

**Comment by jaxx** [comment]
Thank you for your answer.
