### ISSUE TITLE
Add link to snapshot builds in README.md

### ISSUE THREAD

**Issue by LeeDr** [elastic/elasticsearch#17364]
Please add links to elasticsearch snapshot builds to the README.md so people can easily download and try elasticsearch.  This would make it consistent with Kibana which lists snapshot builds in it's README.md (the README.md of each branch has the links to the builds of that branch).

I think people can get to a link now, if they knew where it was.

**Comment by hub-cap** [comment]
After discussion w a few people, we have decided that it is fine for other teams to have this, but we don't want to maintain yet another thing to bump when we update versions. It would make more sense as a real landing page on the web, rather than in our readme.

**Comment by mattkime** [comment]
@hub-cap Has any progress been made on making this info available? Its necessary for Kibana developers to download different versions including snapshots but no info is available on how to do this. (at least that I'm aware of)

**Comment by mattkime** [comment]
@tvernum and I had a good discussion. I was looking for the wrong thing. Instead of working with snapshots in my dev environment I should work with the most recent major/minor version which _are_ published.
