### ISSUE TITLE
Expose whether a task is cancellable in the _tasks list API

### ISSUE THREAD

**Issue by eskibars** [elastic/elasticsearch#17369]
**Describe the feature**:
Currently, the _tasks API produces a list of tasks e.g.

    ZXY-Y-NJThmuoBcL1idCjg:117243: {
      node: "ZXY-Y-NJThmuoBcL1idCjg",
      id: 117243,
      type: "direct",
      action: "indices:data/write/bulk[s][p]",
      status: {
        phase: "primary"
      },
      description: "BulkShardRequest to [mynewindex] containing [100] requests",
      start_time_in_millis: 1459182369761,
      running_time_in_nanos: 6699254,
      parent_task_id: "ZXY-Y-NJThmuoBcL1idCjg:117242"
    }

However, there's no good way for a client to tell which task is eligible for cancellation from the API.  It would be nice to see that, ideally in the task list response.

**Comment by nik9000** [comment]
@imotov I think it'd be pretty simpler to add a `cancellable: true`/`cancellable: false` I think.

**Comment by imotov** [comment]
@nik9000 we would need to propagate it through TaskInfo. So, a task will need to somehow notify TaskInfo about its capabilities, and I would like to make this mechanism more generic if I can, so we have a way to notify that a task is throttle-able, for example. Need to think about it.

**Comment by nik9000** [comment]
Something along the lines of `Set<String> capabilities()` on the Task level? TaskInfo can call it and sort it. I guess you could even use `capabilities().contains` in BaseTasksRequest.  Right now we really only have cancel and, after https://github.com/elastic/elasticsearch/pull/17262, throttle.

**Comment by imotov** [comment]
I had a chance to thing about it more and and play a bit with implementing the generic way of indicating task capabilities. While I still think we need a generic way to do it, the cancellation process is very special case, it affects that way TaskManager works with tasks and probably deserves a dedicated property in TaskInfo. So, if nobody opposes, I am going to implement it the way @nik9000 has originally suggested.
