### ISSUE TITLE
Document analyzer option for keyword type

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#17373]
Per the [PR](https://github.com/jpountz/elasticsearch/blob/14abfe9c1d95ff396880bc3cdac7346aaee0db88/core/src/test/java/org/elasticsearch/index/mapper/core/KeywordFieldMapperTests.java#L205), the analyzer option has been implemented for the keyword type.  Currently, the doc for keyword type does not mention `analyzer` being an [option](https://www.elastic.co/guide/en/elasticsearch/reference/master/keyword.html#keyword-params).  Would be nice to document the analyzer option along with the allowable fields once we have come up with the predefined allowable subset of analyzers for keyword.

**Comment by jpountz** [comment]
@ppf2 This is referring to code of a pull request that has not been merged: https://github.com/elastic/elasticsearch/pull/16934. Supporting an `analyzer` option is planned but will likely not be available in 5.0 yet.
