### ISSUE TITLE
Apply index template updates automatically

### ISSUE THREAD

**Issue by sewi-cpan** [elastic/elasticsearch#17375]
**Assume the following situation:**
1. Create index template
2. Create index based on the template
3. Modify the template

**Current behavior:**
The existing index isn't changed.

**Requested feature:**
The template modifications should be (optionally) applied to all matching indices.
This feature is limited: Some values (like existing fields, number of shards) can't be changed. Changes to these values should trigger an error if existing indices should be updated. Introduction of new fields is no problem, especially when dynamic mapping is set to strict mode.

**Comment by jpountz** [comment]
I think the fact that modifying templates would have side effects on existing indices is trappy. The current behaviour is easier to understand/explain to me.

**Comment by s1monw** [comment]
I agree with @jpountz the template should only have effect on index creation this won't work both ways. you can do the same thing with a settings update already?

**Comment by sewi-cpan** [comment]
The documentation isn't clear on "templates only have effect on index creation".

Maintaining a template **and** keeping the existing indices at the same level adds additional maintenance and error possibilities. Keep both at the same level should be an option - and you're still free not to use it.

**Comment by clintongormley** [comment]
Most mapping settings and many index settings (eg number of shards) can't be changed on an existing index, so making existing indices depend on templates would severely limit the usefulness of a template, as you wouldn't be able to change much.

Instead, the way things are today, you can adjust your template as you go forward to take into account eg changes of data size, changes you want to make in your mappings etc.

I have added documentation (18c5ea8599978f2aee657997c33af1f2b743071c)  to clarify that templates are only applied at index creation time.
