### ISSUE TITLE
Don't store response in request cache if it is over a certain percentage of the cache size

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#17380]
For very large responses storing the response in the request cache may evict large numbers of other cached responses and take up most of the cache size. We should not store responses in the request cache which are over a certain percentage of the total request cache size. We already do something similar to this for the filter cache,

**Comment by jpountz** [comment]
+1

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
