### ISSUE TITLE
Rename _reindex and _update_by_query's size parameter to max_docs

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#17381]
The `size` parameter in reindex is confusing, mostly because reindex involves scroll and scrolls already have a size parameter. We should rename the parameter to `max_docs`. Also, the parameter is only documented in `reindex.asciidoc`, not in `update-by-query.asciidoc`. It needs to be documented in both places.

**Comment by jpountz** [comment]
I am not sure if `size` is that confusing? On my end I think I like it better than `max_docs`.

**Comment by nik9000** [comment]
@clintongormley this is something you'd talked to me about.

**Comment by clintongormley** [comment]
I'm coming around to prefering `size` over `max_docs`... it is consistent with what we do elsewhere, but...

We have `size` and `scroll_size` (doc'ed in update-by-query but not in reindex), but invalid values for `scroll_size` are reported as a problem with `size`.  I'm also not crazy about the fact that later, when we make the reindexing job distributed, there will be no way of guaranteeing an exact `size`.

**Comment by nik9000** [comment]
> but invalid values for scroll_size are reported as a problem with size.

Yeah, that is a bigger problem I think.

**Comment by nik9000** [comment]
> Yeah, that is a bigger problem I think.

I added a test for scroll_size and some documentation to reindex for it as well in the linked pull request. I believe the issue with it complaining about "size" when there is really a problem with scroll_size is symptom of the hackery I used to backport it. So the test wouldn't pass if I backported it to 2.x.
