### ISSUE TITLE
Rename LinearInterpoatingScorer to LinearInterpo**l**atingScorer

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#17384]
Class is just plain spelled wrong.

**Comment by jpountz** [comment]
+1 No need for a pull request for such a trivial change. Let's just rename, test and push.

**Comment by nik9000** [comment]
I thought maybe it is a good thing for a starting contributor?

**Comment by jasontedor** [comment]
I took this while waiting for some test VMs to bootstrap.
