### ISSUE TITLE
Error "Field name cannot contain dot" trying to update a nested date field format

### ISSUE THREAD

**Issue by peteradh** [elastic/elasticsearch#17404]
**Elasticsearch version**: 2.2.1

**JVM version**: 1.8.0_66

**OS version**: Ubuntu 12.04.5 LTS

**Description of the problem including expected versus actual behavior**:
After migrating ES from 1.6.0 to 2.2.1 I want to update the field format for my date fields from dateOptionalTime to strict_date_optional_time. This works fine for 'normal' (here: my_field1) fields, but fails for nested fields (here: my_field2.my_subfield).

Sample mapping:
```
{
  "my_index": {
    "mappings": {
      "my_type": {
        "properties": {
          "my_field1": {
            "type": "date",
            "format": "strict_date_optional_time||epoch_millis"
          },
          "my_field2": {
            "properties": {
              "my_subfield": {
                "type": "date",
                "format": "epoch_millis||dateOptionalTime"
              }
            }
          }
        }
      }
    }
  }
}

```
Im am trying to update the field format for the nested date field my_subfield like this:

```
PUT /my_index/_mapping/my_type?update_all_types 
{
  "properties": {
    "my_field2.my_subfield": {
      "type": "date",
      "format": "strict_date_optional_time||epoch_millis"
    }
  }
}
```
and receive this error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Field name [my_field2.my_subfield] cannot contain '.'"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Field name [my_field2.my_subfield] cannot contain '.'"
  },
  "status": 400
}
```
I understand that from 2.0 onwards, field names may no longer contain a dot in their name - but this is no field with a dot in the name but a nested field.

**Comment by JD557** [comment]
I believe that right now, you have to write the full mapping, i.e.:

```
PUT /my_index/_mapping/my_type?update_all_types 
{
  "properties": {
    "my_field2": {
      "properties": {
        "my_subfield": {
          "type": "date",
          "format": "strict_date_optional_time||epoch_millis"
        }
      }
    }
  }
}
```

You might be interested in following issue https://github.com/elastic/elasticsearch/issues/15951

**Comment by peteradh** [comment]
Thanks a lot, João! This solved the issue.
