### ISSUE TITLE
PATH.DATA  Failed to obtain node lock, is the following location writable? 

### ISSUE THREAD

**Issue by renweijun** [elastic/elasticsearch#17401]
**Elasticsearch version**:2.2.1

**JVM version**:1.8.0_73

**OS version**:Ubuntu 12.04.3 LTS

**Description of the problem including expected versus actual behavior**:
I want set path.data in elasticsearch.yml  like 
"
path.data: /mnt/disk1/elasticsearch-data,/mnt/disk1/elasticsearch-data,/mnt/disk3/elasticsearch-data,/mnt/disk4/elasticsearch-data,/mnt/disk5/elasticsearch-data,/mnt/disk6/elasticsearch-data,/mnt/disk7/elasticsearch-data,/mnt/disk8/elasticsearch-data,/mnt/disk9/elasticsearch-data,/mnt/disk10/elasticsearch-data,/mnt/disk11/elasticsearch-data,/mnt/disk12/elasticsearch-data
" 
then run 
./elasticsearch -d
user@24110:/data/elk/elasticsearch/bin$ Exception in thread "main" java.lang.IllegalStateException: Failed to obtain node lock, is the following location writable?: [/mnt/disk1/elasticsearch-data/elasticsearch, /mnt/disk1/elasticsearch-data/elasticsearch, /mnt/disk3/elasticsearch-data/elasticsearch, /mnt/disk4/elasticsearch-data/elasticsearch, /mnt/disk5/elasticsearch-data/elasticsearch, /mnt/disk6/elasticsearch-data/elasticsearch, /mnt/disk7/elasticsearch-data/elasticsearch, /mnt/disk8/elasticsearch-data/elasticsearch, /mnt/disk9/elasticsearch-data/elasticsearch, /mnt/disk10/elasticsearch-data/elasticsearch, /mnt/disk11/elasticsearch-data/elasticsearch, /mnt/disk12/elasticsearch-data/elasticsearch]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:199)
        at org.elasticsearch.node.Node.<init>(Node.java:153)
        at org.elasticsearch.node.Node.<init>(Node.java:128)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
i don't know  path.data  is sure ?

**Comment by clintongormley** [comment]
I'm wondering if your data paths are being taken as though they were one single path, but I've tried to replicate this and can't.

Could you upload your full config file please?

**Comment by renweijun** [comment]
cluster:
    name:elasticsearch
node:
    name: "elk24110"
    master: true
    data: true
index:
    number_of_shards: 5
    number_of_replicas: 2
path:
    data: /mnt/disk1/elasticsearch-data,/mnt/disk1/elasticsearch-data,/mnt/disk3/elasticsearch-data,/mnt/disk4/elasticsearch-data,/mnt/disk5/elasticsearch-data,/mnt/disk6/elasticsearch-data,/mnt/disk7/elasticsearch-data,/mnt/disk8/elasticsearch-data,/mnt/disk9/elasticsearch-data,/mnt/disk10/elasticsearch-data,/mnt/disk11/elasticsearch-data,/mnt/disk12/elasticsearch-data
    conf: /data/elk/elasticsearch/config
    work: /data/elk/elasticsearch/work
    logs: /data/elk/elasticsearch/logs
    plugins: /data/elk/elasticsearch/plugins
bootstrap:
    mlockall: true
network.bind_host: 192.168.241.10
network.publish_host: 192.168.241.10  
transport.tcp.port: 9300  
transport.tcp.compress: true  
http.port: 9200  
discovery.zen.minimum_master_nodes: 1  
discovery.zen.ping.timeout: 10s  
discovery.zen.ping.multicast.enabled: false  
discovery.zen.ping.unicast.hosts: ["192.168.241.10:9300","192.168.241.11:9300","192.168.241.12:9300","192.168.241.13:9300","192.168.241.14:9300"]

**Comment by renweijun** [comment]
I later modified the configuration file is as follows, run successfully, do not know whether it is bug
![qq 20160331153610](https://cloud.githubusercontent.com/assets/3645697/14168744/9eb941ae-f756-11e5-9057-6d9f7fba1522.png)

**Comment by liuzhenji** [comment]
renweijun,任卫军？

**Comment by rjernst** [comment]
This issue is very old, and I don't think it was actually a bug. The later example that worked converted path.data to be yaml list, which is what the setting expects. The original description looks like it was a single string.
