### ISSUE TITLE
Update `pom.xml` needed changes when using Java client 5.0.0.alpha1

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#17415]
When we are using a Lucene Snapshot version, the generated `pom.xml` does not refer at all to our internal Lucene snapshot.

So in our `pom.xml` we depend on:

```xml
<dependency>
  <groupId>org.apache.lucene</groupId>
  <artifactId>lucene-core</artifactId>
  <version>6.0.0-snapshot-f0aa4fc</version>
  <scope>compile</scope>
</dependency>
```

But our users won't be able to find this version and won't be able to basically use our Java client.

They need to find where this repo lives (and TBH I did not find it yet...).

When we depend on an internal Lucene version like this, could it be possible to generate the link to this repo within the generated `pom.xml`? Like:

```xml
    <repositories>
        <repository>
            <id>lucene-snapshot-f0aa4fc</id>
            <name>Lucene Snapshot repo</name>
            <url>http://download.elastic.co/xxxx</url>
        </repository>
    </repositories>
```

**Comment by dadoonet** [comment]
@rjernst WDYT? Is that doable?

**Comment by jpountz** [comment]
Do we need to do anything here? It would only be an issue for some alpha releases that we publish while Lucene is not out yet? Maybe it is fine to say that you have to wait until the first beta to test with the transport client?

**Comment by dadoonet** [comment]
I'm fine with that as well. Just that it's need to be documented somewhere for early testers using the Java client.

**Comment by rjernst** [comment]
While it is doable (here is patch which does it: https://gist.github.com/rjernst/65b13310c01e42d35bbbf12432ac5859), I agree with @jpountz that maybe it is not worthwhile to have this code for such an edge case that only applies during alpha releases. I actually think gradle should be doing it themselves (they should never generate a "broken" pom).

**Comment by spinscale** [comment]
+1 for less magic and tell people to add it explicitely as long as we need

**Comment by clintongormley** [comment]
agreed - i can add the required info to the blog post, if somebody can tell me what needs to be said?  @rjernst @dadoonet ?

**Comment by dadoonet** [comment]
@clintongormley To use the Java client in a maven project, users have to add:

```xml
<repositories>
    <repository>
        <id>lucene-snapshot</id>
        <name>Lucene Snapshot repo</name>
        <url>http://download.elastic.co/lucenesnapshots/f0aa4fc</url>
    </repository>
</repositories>
```

And also adds this dependency as it fails otherwise (needs a confirmation if it's intended or a bug though):

```xml
<dependency>
    <groupId>log4j</groupId>
    <artifactId>log4j</artifactId>
    <version>1.2.17</version>
</dependency>
```

Hope this helps. I changed the label for this issue and changes the title.

**Comment by centic9** [comment]
Note that this is now elevated a bit by the [pioneer-program](https://www.elastic.co/blog/elastic-pioneer-program) as through this more people will likely try an alpha and stumble into this, at least I did...

**Comment by nik9000** [comment]
> Note that this is now elevated a bit by the pioneer-program as through this more people will likely try an alpha and stumble into this, at least I did...

Not that it really helps that much, but 5.0.0-alpha-2 won't need this because it uses Lucene 6.0.0.

**Comment by clintongormley** [comment]
It was doc'ed in the blog post, and alpha2 is out now, so I'm closing
