### ISSUE TITLE
Dynamic templates ignore analyzers on keyword fields silently

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#17411]
The following:

```
PUT t
{
  "mappings": {
    "t": {
      "dynamic_templates": [
        {
          "strings": {
            "match_mapping_type": "string",
            "mapping": {
              "analyzer": "english",
              "type": "keyword"
            }
          }
        }
      ]
    }
  }
}

PUT t/t/1
{
  "foo": "bar"
}
```

creates a `keyword` field without an analyzer, which is good.  However, I would have expected it to throw an exception about the presence of the analyzer setting.

**Comment by jpountz** [comment]
This is an old bug apparently: dynamic templates do not check for unknown parameters, they simply ignore them. While it could be easy to fix this, this would break lots of existing templates. For instance if you have a template that matches everything and adds `store: true`, then it would fail on all objects since objects do not support the `store` property.

**Comment by clintongormley** [comment]
Should we fix this or leave it be?

**Comment by jpountz** [comment]
I'd be willing to fix it. But the backward compatibility is not going to be easy.

**Comment by jpountz** [comment]
cc @elastic/es-search-aggs

**Comment by rjernst** [comment]
We discussed in FixItThursday and I have a couple suggestions:

* Bwc should be easy, I believe, as it is really about ensuring existing users have a period where they can be informed about these problems without failing. This is exactly what the deprecation logger is for, and there should be exactly one place where this validation occurs (`RootObjectMapper.findTemplateBuilder`).
* The case of match all is interesting, and does present something we at least don't want to break outright. However, I think it is a special case, and if the template contains a `type` for the mapper, then we should apply strictness, at least as a start to remove some level of trappiness?

@jpountz wdyt?
