### ISSUE TITLE
Block new index creation

### ISSUE THREAD

**Issue by rishabhmaurya** [elastic/elasticsearch#17418]
**Block create index**: Block new index creation at cluster level. One way to achieve this is to enable "cluster.blocks.read_only" but it blocks all write operations on cluster whereas we just want to block new index creation and allow other operations. Let me know the possibilities. 

I tried to implement above configuration in 1.5 branch which can be found [here](https://github.com/rishabhmaurya/elasticsearch/commit/dcbfbe3e4edb8506b543e8f2ffd800431c6d549e).

**Comment by clintongormley** [comment]
This can be done today by:

* Setting `action.auto_create_index` to `false`
* Blocking access to the `PUT /index` API

**Comment by rishabhmaurya** [comment]
Yes, this should work but I forgot to describe one use case, we want to trigger this setting dynamically. 
As `action.auto_create_index: false` is a configurable from `elasticsearch.yml`, so do you think the solution you suggested will work ?

**Comment by clintongormley** [comment]
> As action.auto_create_index: false is a configurable from elasticsearch.yml, so do you think the solution you suggested will work ? 

As you note, this is not yet a dynamic setting.  See https://github.com/elastic/elasticsearch/issues/7513

> Also, is there some way in elasticsearch to restrict access to API ?

By putting a proxy in front of Elasticsearch, which you should have anyway, or by installing the Shield plugin

**Comment by rishabhmaurya** [comment]
@clintongormley do you think its good to introduce block create index setting with #7513 ? We are not much comfortable in putting these setting in proxy or using shield plugin as it would add overhead to all requests.

**Comment by rishabhmaurya** [comment]
@clintongormley  As changes are in `TransportClusterUpdateSettingsAction `and `TransportCreateIndexAction `, do you think its possible to write plugin for [this ](https://github.com/rishabhmaurya/elasticsearch/commit/dcbfbe3e4edb8506b543e8f2ffd800431c6d549e)change and is it normally a good practice to override these classes in plugin ?

**Comment by rishabhmaurya** [comment]
@clintongormley Tried to write plugin for this setting. Looks like we cannot modify existing actions(in this case TransportCreateIndexAction) from es plugin(see https://github.com/elastic/elasticsearch/issues/2311).
We don't have any solution now other then to contribute it back to elasticsearch. This setting might be useful for others too. Scenarios where it can be useful - 
1.  If there is high memory consumption because of disk writes
2.  Running low disk space
One can trigger circuit breakers on exceeding memory/disk usage thresholds. Blocking new index creation will help in above cases.
Let me know what do you think in this regard ?
Thanks

**Comment by DaveCTurner** [comment]
Since #7513 was closed by #20274 I think this can be closed too.

**Comment by Bukhtawar** [comment]
I see a usecase here. If all the nodes have disk utilization beyond(92% across all nodes) the high waterwark(90%) wouldn't an index creation cause the primary to be unassigned causing the cluster to go RED(may not mean data loss necessarily). If we could block index creation the moment all nodes hit the high waterwark we should be able to prevent a RED cluster

**Comment by DaveCTurner** [comment]
If all the nodes are above the high watermark then you're right that we cannot allocate new primaries and the cluster health will report RED, but that seems appropriate: this cluster is rather unhealthy and needs immediate attention.

**Comment by Bukhtawar** [comment]
Thanks @DaveCTurner but the only concern here would be to differentiate an actual data loss from unallocated empty primaries.  If we could apply an index creation block we could possibly avoid a RED cluster while failing any customer index creation request like we do for index writes at flood stage which would be an indication for the customer to scale up

**Comment by Bukhtawar** [comment]
@DaveCTurner Please let me know your thoughts on this. Will be more than happy to work on the PR

**Comment by DaveCTurner** [comment]
I do not think that reporting GREEN health but refusing to create new indices is an improvement on how we react today. Even if I did think that, I do not think we should put effort into improving how we react to every node being over the high watermark.

There are also questions like how to deal with the case where only some of the nodes are over the watermark, but the other nodes cannot accept a new primary for some other reason (e.g. shard allocation filtering). I think your proposal would enormously complicate the job of an administrator trying to understand the behaviour of their cluster.

**Comment by Bukhtawar** [comment]
The problem we are trying to solve is most common as disks are more likely to go beyond high watermark up until the writes are blocked. Cases like allocation filtering or for that matter any other decider failing to allocate could be rare. 
Once index creation is BLOCKED the client should see a 403 `FORBIDDEN` if index creates are failing. The administrator can check for blocks in the `/_cluster/settings` as the block is at a cluster level to confirm the same. I think figuring this out is quite simple and blocking index creation should effectively bring down cases on unassigned primaries.
@DaveCTurner let me know what you think.

**Comment by DaveCTurner** [comment]
I've raised this with the team and we again concluded that this is not something we'd want to proceed with, effectively for the reasons I raised above. If your clusters are exceeding the high watermark frequently enough for this to be a concern then _that_ is the thing you should be trying to address.

If, despite this strong recommendation, you remain convinced that this is the path you wish to follow, it's possible you will be able to do so with a plugin.

**Comment by Bukhtawar** [comment]
Thanks @DaveCTurner do you think it would make sense to have a separate cluster health status for unassigned primaries with empty store indicating there is no data loss

**Comment by DaveCTurner** [comment]
For the first idea I think you are misunderstanding the three levels of health. `RED` does not imply data loss, whether the primary has previously been allocated or not. Quoting [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html):

> The cluster health status is: `green`, `yellow` or `red`. On the shard level, a `red` status indicates that the specific shard is not allocated in the cluster, `yellow` means that the primary shard is allocated but replicas are not, and `green` means that all shards are allocated.

Thus `RED` is the appropriate level of health when a primary shard is not allocated, whether it is empty or not.

I will raise the second idea with the team.

**Comment by Bukhtawar** [comment]
Thanks @DaveCTurner I was referring to this [doc](https://www.elastic.co/guide/en/elasticsearch/guide/current/_cluster_health.html)
>red
At least one primary shard (and all of its replicas) is missing. This means that you are missing data: searches will return partial results, and indexing into that shard will return an exception.

Please let me know what the team concludes on and if there is a obvious consequence to the second approach

**Comment by jasontedor** [comment]
@Bukhtawar That is referring to a situation such as /*/_search. Ignoring security, that is a search request that would expand to all indices and hit all shards. If your cluster is red, Elasticsearch will return partial results rather than failing the request. That is what is meant by "data is missing". Assuming there is a valid shard copy out there but currently unassigned, that data is not permanently lost, there is no data loss here as we mean by the term.

**Comment by Bukhtawar** [comment]
Thanks @jasontedor for the clarification. I think as a customer I would also like to know by just looking at a RED cluster if I actually lost data and whether or not that's recoverable. Anyways the proposals that I'm trying to make is to minimize the possibility of a `RED` cluster if there isn't an obvious data loss. So if the cluster beyond high disk watermark continues to assign empty primaries(newly created) probably we avoid a pretty common scenario where a cluster goes `RED`
