### ISSUE TITLE
repository-s3 is not available

### ISSUE THREAD

**Issue by passkey1510** [elastic/elasticsearch#17427]
**Elasticsearch version**: 2.3

**JVM version**: 1.8.0_77

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:
Installation of repository-s3 failed
**Steps to reproduce**:
 1. Follow documentation on https://www.elastic.co/guide/en/elasticsearch/plugins/master/repository-s3.html
 2. Run /usr/share/elasticsearch/bin/plugin install repository-s3 --verbose
 3. ERROR: failed to download out of all possible locations..., use --verbose to get detailed information

**Provide logs (if relevant)**:
-> Installing repository-s3...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/repository-s3/2.3.0/repository-s3-2.3.0.zip ...
Failed: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/repository-s3/2.3.0/repository-s3-2.3.0.zip]; nested: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/repository-s3/2.3.0/repository-s3-2.3.0.zip]; 
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information

**Comment by jasontedor** [comment]
The functionality of this plugin is available in the 2.x series in the cloud-aws plugin (it is, however, split out in master as repository-s3 versus discovery-ec2). You should be able to install the plugin with

```
$ ./bin/plugin install cloud-aws
```

and accepting the additional security permissions.
