### ISSUE TITLE
Repo path should be 2.x not 2.3

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#17423]
Looks like a typo has snuck into the docs with 2.3, [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html), as we have moved away from specific minor version repos;
```
echo "deb http://packages.elastic.co/elasticsearch/2.3/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-2.3.list
```

And also;
```
baseurl=https://packages.elastic.co/elasticsearch/2.3/centos
```

The `2.3` needs to be replaced with `2.x` for both. 

Reported [here](https://discuss.elastic.co/t/elasticsearch-2-3-installation-with-apt-fails-404/45848).

**Comment by clintongormley** [comment]
Fixed by e559ecaaf8d9836404d4b2c53a222ad7c560d239

**Comment by s123klippel** [comment]
How does one then upgrade to a specific minor version to retain certain plugin compatibility? This move seems counter intuitive in conjunction with the 2.x move toward strict minor version plugin compatibility.

**Comment by jasontedor** [comment]
> How does one then upgrade to a specific minor version to retain certain plugin compatibility?

@s123klippel Your package manager will let you specify a version that you want to upgrade to. Specifically for `apt-get` (assuming that you've updated your cache):

```
$ sudo apt-get install elasticsearch=2.2.2
```

**Comment by s123klippel** [comment]
Thank you, I'm not an everyday linux user and didn't know that existed.

**Comment by jasontedor** [comment]
> Thank you, I'm not an everyday linux user and didn't know that existed.

You're welcome. :smile:
