### ISSUE TITLE
_rename index feature request for a read-only index

### ISSUE THREAD

**Issue by awick** [elastic/elasticsearch#17426]
Now that we have _reindex could we get a _rename for a closed index? 

Then I could do
_reindex a->b
_close b
DELETE a
_rename b->a
_open a

Yes this can kind of be done with aliases, but there are still some weirdness with aliases that this would make so much easier.

**Comment by clintongormley** [comment]
I'll go one better.  I think that, with the work done in https://github.com/elastic/elasticsearch/pull/16442, https://github.com/elastic/elasticsearch/pull/17001, https://github.com/elastic/elasticsearch/pull/16217, and https://github.com/elastic/elasticsearch/pull/17048, we can now work on atomically renaming an open read-only index.

**Comment by DrHyde** [comment]
I too would find it Really Useful to be able to rename an index

**Comment by clintongormley** [comment]
Update on this: the index name is way too entwined with the current code to let us do this easily.  We're going to work on moving the reliance on index names to index UUIDs instead, then maybe we can reconsider this change.  But this is a massive effort, so don't hold your breath :)

**Comment by awick** [comment]
Ok what is the next best thing? :)

I know that I can shutdown ES, rename the directories and restart and it seems to work.  Is there anything in between?

Will _close, rename on disk, _open work?

If not, what about _close, rename on disk, rolling bounce, _open?

**Comment by clintongormley** [comment]
> I know that I can shutdown ES, rename the directories and restart and it seems to work. Is there anything in between?

This will no longer work in 5.0 because we now use the index UUID as the folder name, instead of the index name.

> Ok what is the next best thing? :)

Use aliases.  They can be switched atomically.

**Comment by awick** [comment]
> (We will probably provide a command line tool which allows you to rename an index before starting the node)

+1 

> Use aliases. They can be switched atomically.

Ya, but they have some annoying properties.  Such as the _index returned is not the alias asked for, so you have to map them back, which is impossible if multiple aliases point to the same index.  This can be especially annoying in _stats where you ask for foo but the key into the map is bar.  (At least in 2.3, maybe this has all changed in 5)

**Comment by clintongormley** [comment]
> Ya, but they have some annoying properties. Such as the _index returned is not the alias asked for, so you have to map them back, which is impossible if multiple aliases point to the same index. This can be especially annoying in _stats where you ask for foo but the key into the map is bar. (At least in 2.3, maybe this has all changed in 5)

Agreed.  We've been thinking of making the index name just an alias, but marking it as the "main" alias somehow, so that it works as expected for stats, index apis, and logging.

**Comment by rpedela** [comment]
@clintongormley Will renaming an open read/write index be possible after all the index UUID changes? If not, why not?

**Comment by clintongormley** [comment]
@rpedela it won't, unfortunately.  There are way too many places in the codebase where the index name is used instead of the UUID, and it is extremely difficult to be sure that we've managed to get them all.  It's still something we'd love to do, but it would require an enormous effort and mean sacrificing other features that we'd prefer to deliver instead.

**Comment by clintongormley** [comment]
This is unlikely to happen in the foreseeable future.  I'm going to close for now

**Comment by awick** [comment]
What about the original ask of renaming a closed index?
