### ISSUE TITLE
Shard listener registration

### ISSUE THREAD

**Issue by oillio** [elastic/elasticsearch#17421]
The merge #17398 adds back in the ability to register IndexingOperationListeners in a plugin.  However, the semantics are different and doesn't provide the same functionality as the 2.x implementation.

In 2.x a plugin would register a listener directly with an IndexShard after creation.  I have a 2.x plugin that uses information about the IndexShard when handling events in the listener.

In the new implementation, there is a single instance of a given listener used for all IndexShards for an Index.  I don't see a way to get the calling IndexShard in the listener anymore.

Was this an intentional change, or can we get this functionality back in?
I can provide a PR...
If you would like a PR for this, I see two ways to solve.  Register a listener factory in IndexModule, build and attach the listeners just after IndexShard creation.  Or pass the calling IndexShard to the listener on each event call.

**Comment by s1monw** [comment]
what kind of infos are you using, I don't really think we should open up too much on this level of the system so I am hesitating here to bring back the large openness we had in 2.x

**Comment by oillio** [comment]
Yeah, I was afraid of that.  I should be able to get what I need at the Index level, I didn't want to re-write it if I didn't have to.  Thanks for the quick reply.
