### ISSUE TITLE
Provide a configuration option:  routing=my-local-shards-only

### ISSUE THREAD

**Issue by sachingsachin** [elastic/elasticsearch#17420]
**Describe the feature**: Provide a configuration **routing: my-local-shards-only**

**Some background**: We have a 40 node storm cluster that runs 40 kafka-spouts and 80 ES-Bolts with LOCAL_OR_SHUFFLE_GROUPING. ES-cluster has 10 shards with 1 replica each and they run on 10 powerful machines with 100+GB RAM and 32 cores each.

**Problem**: Field-based routing has been removed in 2.x version and the latest elasticsearch-hadoop does not provide a way to route the messages yet ([ES-Hadoop-issue-715](https://github.com/elastic/elasticsearch-hadoop/issues/715)).

So the bulk request (we have 10k messages batch currently, each message is 0.7 kb roughly) from each bolt is distributed equally among all the shards and that makes it roughly ~1k messages / shard. This is killing the performance. If batch-size is made larger, number of failures increase in storm.

Even if ES-Hadoop implements routing and the bolts start appending a routing-value in their URLs, it **seems** unlikely (I am not sure though) that every bolt will be able to figure out an exact value of routing such that the ES-server that receives the requests process it locally only. This is so because currently the custom-routing is used in the following formula as per [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html):

```
 shard_num = hash(_routing) % num_primary_shards
```

So to make the ES-server process the bulk request locally, the routing-field value must be such that the _shard_num_ value comes out to be the same value as the current shard (ES-Hadoop sends data to primary shards only if its not configured for client-nodes.) This is difficult to achieve IMO (especially when there are several writers like storm's ES-Bolts).

An alternative could be to have a configuration **routing: my-local-shards-only** in elastic-search itself which makes ES-servers consume the entire bulk-request locally. On doing so, the clients need not implement any routing and just by ensuring that their request goes to the correct primary, they can achieve a good load balance. Benefits of this approach:
1. Client need not **guess** an exact value of the _routing_ field such that its consumed locally.
2. We are sure that there would never be a hop of bulk request from one primary-shard to another primary-shard because it's guaranteed to be consumed locally.
3. For several clients (like storm/hadoop), there is no code change to implement routing.

IMHO, the load-balancing achieved in this way is no different than the load-balancing achieved by specifying the routing field in the URL (I could be wrong though) because client is responsible to either provide a good routing-field or select the right primary-shards (latter seems to be easier).

One drawback I do see in the **routing: my-local-shards-only** approach is that lookup-by-ID becomes mostly impossible because clients would not know what routing-field to specify. But for many systems, this is not a concern because they will never do a lookup-by-ID (Example: log search use-case) and even for those cases, one can always search for ID like all other regular fields (scatter-gather)

Sorry for the long description :)

**Elasticsearch version**: 2.x

**Comment by clintongormley** [comment]
Hi @sachingsachin 

> Sorry for the long description :)

Not at all.  Helps to understand the context.

> One drawback I do see in the routing: my-local-shards-only approach is that lookup-by-ID becomes mostly impossible because clients would not know what routing-field to specify. But for many systems, this is not a concern because they will never do a lookup-by-ID (Example: log search use-case) and even for those cases, one can always search for ID like all other regular fields (scatter-gather)

This is the problem I see with your suggestion. It's important for us at Elasticsearch to keep things consistent, to not introduce feature X which doesn't work with feature Y unless condition Z.... These things end up producing a lot of confusion and complexity, which makes Elasticsearch harder to understand and use.  I'm very much against adding non-generic changes like this, especially when we have a generic mechanism specifically for managing such issues, ie custom routing.

I think the solution needs to be implemented at a higher level, eg each bolt specifies a custom routing value on each message, which limits all of the messages in that bolt to a single shard.

> So to make the ES-server process the bulk request locally, the routing-field value must be such that the shard_num value comes out to be the same value as the current shard (ES-Hadoop sends data to primary shards only if its not configured for client-nodes.) This is difficult to achieve IMO (especially when there are several writers like storm's ES-Bolts).

Actually it is pretty easy to figure out routing values that map to individual shards.  Here's what I did to come up with a list for 10 shards:

    PUT t 
    {
      "settings": {"number_of_shards":10}
    }
    
    POST t/t/_bulk
    {"index": {"_routing": "01"}}
    {}
    {"index": {"_routing": "02"}}
    {}
    {"index": {"_routing": "03"}}
    {}
    {"index": {"_routing": "04"}}
    {}
    {"index": {"_routing": "05"}}
    {}
    {"index": {"_routing": "06"}}
    {}
    {"index": {"_routing": "07"}}
    {}
    {"index": {"_routing": "11"}}
    {}
    {"index": {"_routing": "13"}}
    {}
    {"index": {"_routing": "17"}}
    {}
    
    
    GET _stats?level=shards&filter_path=**.shards.**.docs.count

Give one of each of these values to 4 kafka spouts and all 4 will then map to a single shard.

**Comment by sachingsachin** [comment]
Thank you @clintongormley 

> Here's what I did to come up with a list for 10 shards.

The JSON response I got from the above requests is as follows:

    {
       "indices": {
          "t": {
             "shards": {
                "0": [
                   {
                      "docs": {
                         "count": 1
                      }
                   },
                   {
                      "docs": {
                         "count": 1
                      }
                   }
                ],
                "1": [
                   {
                      "docs": {
                         "count": 1
                      }
                   },
                   {
                      "docs": {
                         "count": 1
                      }
                   }
                ],
                ... 8 more blocks like the above
              }
            }
      }
    }


> Give one of each of these values to 4 kafka spouts and all 4 will then map to a single shard.

I think you meant 80 EsBolts and not 4 kafka spout.
But even if you meant EsBolt, I do not understand the above JSON response or how it can help my case.

For other indices I have, I get a pretty similar response without making any of the above POST requests.
For example, the stats on my storm index look very similar:

    {
       "indices": {
          "storm": {
             "shards": {
                "0": [
                   {
                      "docs": {
                         "count": 14467774
                      }
                   },
                   {
                      "docs": {
                         "count": 14467774
                      }
                   }
                ]
             }
          }
      }
    }

So what is the difference made by the above POST calls (sorry, I have only a few months experience with ES).

> it's important for us at Elasticsearch to keep things consistent, to not introduce feature X which doesn't work with feature Y unless condition Z

I am inclined to think that this is how options work in general.
All features do not work with all the options.
For example, if someone uses custom routing (putting it in the URL of a client request), he is aware that lookup-by-ID will not work unless a correct routing value is not specified.

A quote from [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html):

> When indexing documents specifying a custom _routing, the uniqueness of the _id is not guaranteed across all of the shards in the index. In fact, documents with the same _id might end up on different shards if indexed with different _routing values.
> 
> It is up to the user to ensure that IDs are unique across the index.

Thus, the user would be aware what he is doing.
If he chooses routing in the URL (feature X), he will not get unique results when doing a lookup-by-ID (feature Y) unless he ensures uniqueness of bulk requests to shards (condition Z).
Similarly, if a user chooses the feature requested here, I would assume that he knows what he is doing and a good documentation (or an answer on SO) should clarify this even further.

Also, I would appreciate your thoughts on the other benefits of the proposed option (listed in my first comment).

Thank you @clintongormley

**Comment by clintongormley** [comment]
> I think you meant 80 EsBolts and not 4 kafka spout.
> But even if you meant EsBolt, I do not understand the above JSON response or how it can help my case.

What I meant by the above was that here you have a list of routing values, each of which maps to a **single** shard (when you're using 10 shards).  This is the answer to:

> it seems unlikely (I am not sure though) that every bolt will be able to figure out an exact value of routing such that the ES-server that receives the requests process it locally only.

 So you can assign one routing value to 4 kafka spouts, or to 8 EsBolts and they will target a single Elasticsearch shard.

> Also, I would appreciate your thoughts on the other benefits of the proposed option (listed in my first comment).

While I see the benefits you mention, the problem I have with the proposal as a whole is as stated in 
https://github.com/elastic/elasticsearch/issues/17420#issuecomment-203879027.

I've left this open for discussion in case somebody has some better idea.

**Comment by sachingsachin** [comment]
Thanks for leaving it open for others to comment @clintongormley .
If more votes are skewed towards the benefits introduced by this option and lesser towards the problems, then we could try to implement the same.

Is there a way to seek opinion from couple more folks?
A quicker closure would be better than an indefinite one.

**Comment by fmyblack** [comment]
I have a nearly-like problem.
**my background**: I have about 350GB data need write in `es2.3` using `elasticsearch-hadoop` before 6:00am each day. Every doc is about a single user profile (with a uuid and multi-tags) . 
**The problem**: The only thing I want is increasing index performance cause there be a cache api in query client. I want one partition data can be indexed in same shard, though I'm not care about if the route path is uuid.

I find the hash function in `es2.3` is `Murmur3HashFunction`, 
and in `elasticsearch-hadoop`:
```
int bucket = currentInstance % targetShards.size();
Shard chosenShard = orderedShards.get(bucket);
Node targetNode = targetShards.get(chosenShard);
```
thats means `partitionid % totalshards == chosenshard`, so if the data is in the same partition, is will send to same shard, I want the chosen shard will be the routing shard, So I create a Partitioner like this:
```
public class EsPartitioner extends Partitioner {

	int numPartitions;
	
	public EsPartitioner(int numPartitions) {
		this.numPartitions = numPartitions;
	}
	
	@Override
	public int getPartition(Object row) {
		// TODO Auto-generated method stub
		int hash = Murmur3HashFunction.hash("" + row) % this.numPartitions;
		if(hash < 0) {
			hash += this.numPartitions;
		}
		return hash;
	}
	
	@Override
	public int numPartitions() {
		// TODO Auto-generated method stub
		return numPartitions;
	}

	/**
	 * Hash function based on the Murmur3 algorithm, which is the default as of
	 * Elasticsearch 2.0.
	 */
	static class Murmur3HashFunction {...// same like in es}
}
```

In my rdd, key is uuid:
```
int partitionNum = 10 * shardNum;
JavaPairRDD<String, Profile> users...;
users.partitionBy(new EsPartitioner(partitionNum));
```

last, I set `es.mapping.routing` --> 'uuid' to make the es and spark use same hash function and same route field.

**Comment by tomcallahan** [comment]
@jbaiera can you take a look at this one?

**Comment by jbaiera** [comment]
I don't think there's much appetite for adding in an option for ES to accept writes to the local node only. As stated above, the easiest option would be to assign a stable routing id to each document as it is written, and while it is not guaranteed to result in the documents being immediately persisted by the node handling the request, it does ensure that at most one hop will be used to persist all documents to a single node that the routing value corresponds to.

Another course of action that we think will result in better performance for ingestion pipelines is that of a "best-effort routing" partitioner to be added to ES-Hadoop to be used with different integrations (https://github.com/elastic/elasticsearch-hadoop/issues/1130). This feature would do two things: Expose the hashing algorithm to a partitioner implementation that can determine a document's shard number by extracting an id or routing from it, and batching writes to the cluster on the outputformat/bolt/sink by referencing a locally cached view of the cluster's routing table. We wont be able to ensure that any external system will have a perfectly synchronized view of the cluster state, so this optimization will fall back to relying on Elasticsearch to forward requests that are incorrectly routed, with the Hadoop side periodically refreshing its view of the cluster state.

With these points in mind, I'm going to close this issue out.
