### ISSUE TITLE
Merge multiple searches on aliases pointing to the same index

### ISSUE THREAD

**Issue by KlavsKlavsen** [elastic/elasticsearch#17438]
**Describe the feature**:
Most of my searches are on the last day or two.. so I use daily indexes (for logs - from logstash).

But I get 100 mill. + logs easily per day.. and some have the insane idea that they want to be allowed to search for f.ex. 1 year.. That eats up a lot of memory in index space.

So I'd like to be able to merge older indexes into larger indexes.. with the new reindex api and alias'es - thats easy.

Only issue left, is that kibana will still search on every daily index.. even though they would now be an alias for the same weekly (or monthly) index.. meaning I would get 30 searches run on the same index.. instead of just 1.. I asked on irc and Warkholm stated that ES does not in fact recognize when this happens..

I would like ES to actually detect this fact, when searching on aliases.. so 30 searches are merged into one in this case :)

**Comment by clintongormley** [comment]
Hi @KlavsKlavsen 

> Only issue left, is that kibana will still search on every daily index.. even though they would now be an alias for the same weekly (or monthly) index.. meaning I would get 30 searches run on the same index.. instead of just 1.. I asked on irc and Warkholm stated that ES does not in fact recognize when this happens..

I'm not sure where @markwalkom got that idea... aliases are reduced to a unique list of the corresponding indices

    PUT t/t/1
    {}
    
    PUT t/_alias/x
    PUT t/_alias/y
    
    GET x,y/_validate/query?explain

returns:

    "explanations": [
      {
        "index": "t",
        "valid": true,
        "explanation": "*:*"
      }
    ]

It even knows how to combine filtered aliases on the same index correctly
