### ISSUE TITLE
CASE_INSENSITIVE not working in ElasticSearch > 1.7

### ISSUE THREAD

**Issue by Filirom1** [elastic/elasticsearch#17437]
**Elasticsearch version**: 2.2 and 2.3 (it was working in ES 1.7)

**JVM version**: openjdk version "1.8.0_77"

**OS version**: centos 7.2

**Description of the problem including expected versus actual behavior**:CASE_INSENSITIVE flags in aggregation is not working

**Steps to reproduce**:

```
curl -XPOST -d '{"mappings":{"type":{"properties":{"name":{"type":"string", "index": "not_analyzed"}}}}}' localhost:9200/toto

curl -XPOST -d '{"name": "g1"}' localhost:9200/toto/type/1
curl -XPOST -d '{"name": "g2"}' localhost:9200/toto/type/2
curl -XPOST -d '{"name": "G3"}' localhost:9200/toto/type/3

curl  -XPOST localhost:9200/toto/_search?pretty -d '{
"size": 0,
  "aggs": {
    "2": {
      "terms": {
        "field": "name",
        "include": {
          "pattern": "g[0-9]",
          "flags": "CASE_INSENSITIVE"
        }
      }
    }
  }
}'
```

```
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 4,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "2" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [ {
        "key" : "g1",
        "doc_count" : 1
      }, {
        "key" : "g2",
        "doc_count" : 1
      } ]
    }
  }
}
```

G3 is not displayed

**Comment by jimferenczi** [comment]
Thanks @Filirom1. This is documented in the breaking 2.0 aggregation changes here:
https://www.elastic.co/guide/en/elasticsearch/reference/2.3/breaking_20_aggregation_changes.html#_including_excluding_terms
The `flags` parameter is no longer supported but we have some leniency in the aggregation parsers.

**Comment by tom10271** [comment]
The last comment is not very clear. Originally we set "CANON_EQ|CASE_INSENSITIVE" as flag, and it is no longer supported now. Do these handled already by aggregation parser? If not what should I do to keep the result returned consistent?

Thank you for answering
