### ISSUE TITLE
IndexingMemoryController settings are not registered settings

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#17442]
All settings in `IndexingMemoryController` are not registered settings but should be. Missing settings are:

 * `indices.memory.min_index_buffer_size`
 * `indices.memory.index_buffer_size`
 * `indices.memory.max_index_buffer_size`
 * `indices.memory.shard_inactive_time`
 * `indices.memory.interval`

**Comment by mikemccand** [comment]
Nice catch, I'll tackle this ...

**Comment by s1monw** [comment]
thanks @mikemccand
