### ISSUE TITLE
Elasticsearch 2.0 scripting: Invoke custom script from plugin

### ISSUE THREAD

**Issue by haingo-kenshjn** [elastic/elasticsearch#17448]
If we defined native script in plugin: com.test.nativescript.TestScript, can we invoke that package inside another groovy script and create new instance ?

Ex: 
inside config/scripts/test.groovy:

```
import  com.test.nativescript.TestScript;

def testScript = new TestScript();
```

> Result: "startup failed:\r\nc78a82bc96ca7751e83e256b4ee0c322cda13bea: 1: unable to resolve com.test.nativescript.TestScript"

**Comment by clintongormley** [comment]
Hi @haingo-kenshjn 

No, you can't, and allowing this would open up a security hole.  Scripts are meant to be relatively simple.  Anything more and you should consider writing a native script in java.
