### ISSUE TITLE
Elasticsearch : Cannot create a client node

### ISSUE THREAD

**Issue by abtpst** [elastic/elasticsearch#17450]
**Elasticsearch version**: 2.2.0

**JVM version**: 1.8

**OS version**: windows 7

**Description of the problem including expected versus actual behavior**:

I am trying to create a client node for my Elastic cluster, which has elasticsearch version 2.2.0. I have 4 nodes in my cluster and each of them can be data or master nodes. Now, i want to create a client node that will ping one of my other 4 nodes. My intention is that even if one of my 4 main nodes goes down, my client will be able to get data from some node that is functional.

Here is my elasticsearch.yml for client

    cluster.name: myCluster
    node.name: myClient
    node.master: false
    node.data: false
    discovery.zen.ping.unicast.hosts: ["box1:9300","box2:9300","box3:9300","box4:9300"]
    discovery.zen.fd.ping_timeout: 30s
    discovery.zen.minimum_master_nodes: 3
    discovery.zen.ping.multicast.enabled: false

each of the above boxes are configured as

    cluster.name: myCluster
    node.name: n2
    path.data: /asd/thth/jtjut/elastic
    path.logs: /var/log/eslogs
    network.host: box2
    node.master: true
    node.data: true
    index.number_of_replicas: 1
    discovery.zen.ping.unicast.hosts: ["box1:9300","box2:9300","box3:9300","box4:9300"]
    discovery.zen.fd.ping_timeout: 30s
    discovery.zen.minimum_master_nodes: 3
    discovery.zen.ping.multicast.enabled: false
    
    action.disable_delete_all_indices: true
    
    http.cors.enabled: true
    http.cors.allow-origin: "*"

but when i start the elasticsearch service on the client, i get

    [2016-03-31 10:24:07,576][INFO ][discovery.zen            ] [myClient] failed
    to send join request to master [{n2}{5vlJHDZaQhGttqZsD5gVvA}{34.87.98.213}{34.87.98.213:9300}{master=true}], reason [RemoteTransportException[[n2] 34.87.98.213:9300][internal:discovery/zen/join]]; nested:ConnectTransportException[[myClient][127.0.0.1:9300] connect_timeout[30s]]; nested: NotSerializableExceptionWrapper[Connection refused: /127.0.0.1:9300]; ]

why am i getting connection refused exception? is there anything missing from my configurations?

**Steps to reproduce**:
 1. Install elasticsearch on client machine
 2. Update elasticsearch.yml to create client node
 3. Run elasticsearch on client machine

**Comment by clintongormley** [comment]
Your client node needs `network.host` configured as well.  At the moment, it is bound to localhost.
