### ISSUE TITLE
Kstem filter doesn't work for "dogs" word

### ISSUE THREAD

**Issue by sdiwu** [elastic/elasticsearch#17452]
**Elasticsearch version**: 2.2.2

**JVM version**: 1.8.0_45

**OS version**: Windows 7 SP1 64 bit

**Description of the problem including expected versus actual behavior**:
kstem filter doesn't work for "dogs" word.

**Steps to reproduce**:
1) Create an index with custom analyzer with kstem filter
```
curl -XPUT "http://localhost:9200/test" -d'
{
    "settings": {
        "analysis": {
            "analyzer": {
				"my_analyzer": {
					"type": "custom",
					"tokenizer": "standard",
					"filter": [ "kstem" ]
				}
			}
        }
    }
}'
```

2) Test the analyzer
`curl -XGET "http://localhost:9200/test/_analyze?analyzer=my_analyzer&pretty=true" -d"dogs" | grep "token"`

3) The result token is still "dogs" rather than "dog". But if I try with another words like "birds", "cats", it works fine.

So what's wrong with the dogs?

**Comment by cbuescher** [comment]
Unfortunately Stemmers never work perfect, KStem tends to be less agressive than e.g. Porter Stemmer, so if you really need "dogs" stemmed, you could try that one. I just quickly dug this up for comparison. https://mail-archives.apache.org/mod_mbox/lucene-java-user/201211.mbox/%3C96A3937D727B4011B77FC7C6B6FAB829@JackKrupansky%3E
Also, please ask very use-specific questions like this in the form at https://discuss.elastic.co/ in the future?
