### ISSUE TITLE
yum install command for older 2.x releases

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#17455]
All of the 2.x releases (all the way back to 2.0) have the same step for installing ES using yum:

https://www.elastic.co/guide/en/elasticsearch/reference/2.2/setup-repositories.html#_yum_dnf
https://www.elastic.co/guide/en/elasticsearch/reference/2.3/setup-repositories.html#_yum_dnf

> [elasticsearch-2.x]
> name=Elasticsearch repository for 2.x packages
> baseurl=http://packages.elastic.co/elasticsearch/2.x/centos
> gpgcheck=1
> gpgkey=http://packages.elastic.co/GPG-KEY-elasticsearch
> enabled=1
> 
> And your repository is ready for use. You can install it with:
> yum install elasticsearch

But to install an older release, the yum command should be different, eg.

yum install elasticsearch-2.2.0
yum install elasticsearch-2.1.2

Maybe we can change the documentation to say something like:
- To install the latest 2.x version, use `yum install elasticsearch`.
- To install a specific (older) 2.x version, use `yum install elasticsearch-<version>`, eg. yum install elasticsearch-2.2.0
- You can use `yum list elasticsearch --showduplicates` to retrieve a list of available versions for the elasticsearch repo.

**Comment by rjernst** [comment]
We now have a new yum repository per major version, and the instructions are updated per major version, so I'm going to close this.
