### ISSUE TITLE
Native script invoke file script

### ISSUE THREAD

**Issue by haingo-kenshjn** [elastic/elasticsearch#17461]
From: https://github.com/elastic/elasticsearch/issues/17448. It's impossible to retrieve native from plugin because of security problem.

Can I invoke groovy script from native ?
```
@Inject
public Factory(Settings settings, GroovyScriptEngineService service) {
    super(settings);
    this.service = service;
}
```

then in constructor : 
```
    @Override
    public Object run() {
        GroovyScriptEngineService abc = TestScript.Factory.service;
        CompiledScript combined = new CompiledScript(ScriptType.FILE, "init", "groovy", abc.compile("init"));
        logger.info(combined.getClass().toString());
        return abc.execute(combined, params);
    }
```
Result:

> "reason": {
>             "type": "script_exception",
>             "reason": "failed to execute file script [init] using lang [groovy]",
>             "caused_by": {
>             "type": "missing_property_exception",
>             "reason": "No such property: init for class: fd62812fbd9ec4c7f99aa4f6253fead2388eb238"
>    }
> }

**Comment by javanna** [comment]
some more explanation [here](https://discuss.elastic.co/t/elasticsearch-scripting-invoke-custom-script-from-plugin/45835/6)
