### ISSUE TITLE
Error in decay function-score picture

### ISSUE THREAD

**Issue by pmusa** [elastic/elasticsearch#17479]
The picture for the decay function score is old and has **reference** instead of **origin**.

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#_supported_decay_functions

https://www.elastic.co/guide/en/elasticsearch/reference/current/images/decay_2d.png

![decay_2d](https://cloud.githubusercontent.com/assets/361280/14208628/b3ed4732-f7f6-11e5-8c5a-78d718fe356f.png)

**Comment by clintongormley** [comment]
@brwe could you correct this image please?

**Comment by pmusa** [comment]
<img width="404" alt="screen shot 2016-04-19 at 2 49 27 pm" src="https://cloud.githubusercontent.com/assets/361280/14641467/53e0514e-063e-11e6-97e8-1bfcd037aa56.png">

**Comment by clintongormley** [comment]
thanks @pmusa - fixed
