### ISSUE TITLE
Problems with http.cors.allow-methods

### ISSUE THREAD

**Issue by pciccarese** [elastic/elasticsearch#17483]
**Elasticsearch version**: 2.3.0
**JVM version**: 1.8.0_31
**OS version**: MAC OS X 10.10.5
**Description of the problem including expected versus actual behavior**:
Definition of an accepted a custom header does not seem to work.

**Steps to reproduce**:
 1. Add the following lines to the configuration file
```
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length, X-User"
```

 2. Ran an ajax POST request with X-User header.
 3. Getting response "Request header field x-user is not allowed by Access-Control-Allow-Headers in preflight response."

**Comment by pciccarese** [comment]
I am really sorry, but after more investigation, a Chrome update and some tries with Firefox. That does not seem to be an issue anymore.

**Comment by pciccarese** [comment]
I am afraid I will need to reopen this.

**Elasticsearch version**: 2.3.0
**JVM version**: 1.8.0_31
**OS version**: MAC OS X 10.10.5
**Description of the problem including expected versus actual behavior**:

Use of custom header does not seem to work reliably.

Here is the CORS section of my configuration (elasticsearch.yml) file:
```
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length, X-User"
```

The client code is performing the following call:
```
jQuery.ajax({
    url: requrl,
    data: reqdata,
    type: 'POST',
    headers: {"X-User": user},
    success: function (result, status, xhr) {
        resolve(result);
    },
    error: function (xhr, status, error) {
        reject(error);
    }
});

```

Now, that request always goes through with Firefox 45.0.1.
However, with Chrome Version 49.0.2623.110 (64-bit) I get:
```
XMLHttpRequest cannot load http://localhost:9200/myindex/mytype/_search. 
Request header field x-user is not allowed by Access-Control-Allow-Headers in preflight response.
```

**The very same configuration, index and client code works reliably in 2.2.0**.
After seeing in the release notes the entry: “More robust handling of CORS HTTP Access Control” I am wondering if that has anything to do with it.

**Comment by skundrik** [comment]
I have experienced same issue which now breaks Grafana UI.

**Comment by skundrik** [comment]
The problem appears to be in `NettyHttpServerTransport.buildCorsConfig()` where first parameter to the `getAsArray()` function should be the setting name and not the value of the setting.
```
        String[] strMethods = settings.getAsArray(settings.get(SETTING_CORS_ALLOW_METHODS, DEFAULT_CORS_METHODS), new String[0]);
        HttpMethod[] methods = new HttpMethod[strMethods.length];
        for (int i = 0; i < methods.length; i++) {
            methods[i] = HttpMethod.valueOf(strMethods[i]);
        }
        return builder.allowedRequestMethods(methods)
                      .maxAge(settings.getAsInt(SETTING_CORS_MAX_AGE, DEFAULT_CORS_MAX_AGE))
                      .allowedRequestHeaders(settings.getAsArray(settings.get(SETTING_CORS_ALLOW_HEADERS, DEFAULT_CORS_HEADERS), new String[0]))
                      .shortCircuit()
                      .build();
```
should say
```
        String[] strMethods = settings.getAsArray(SETTING_CORS_ALLOW_METHODS, DEFAULT_CORS_METHODS);
        HttpMethod[] methods = new HttpMethod[strMethods.length];
        for (int i = 0; i < methods.length; i++) {
            methods[i] = HttpMethod.valueOf(strMethods[i]);
        }
        return builder.allowedRequestMethods(methods)
                      .maxAge(settings.getAsInt(SETTING_CORS_MAX_AGE, DEFAULT_CORS_MAX_AGE))
                      .allowedRequestHeaders(settings.getAsArray(SETTING_CORS_ALLOW_HEADERS, DEFAULT_CORS_HEADERS))
                      .shortCircuit()
                      .build();

```

**Comment by abeyad** [comment]
Thank you for reporting the issue.  We have PRs open to fix them for different versions.

#17523 #17524 #17525
