### ISSUE TITLE
Docs: Move Repositories section to be with Installation section

### ISSUE THREAD

**Issue by LeeDr** [elastic/elasticsearch#17486]
Installing our whole stack from the docs would be a lot easier if we were consistent in our docs.

I like that there's an "Installation" section in the "Getting Started" section of Elasticsearch reference.

But having another "Setup" section and "Repositories" under that is confusing.

The simplest improvement would just be to add a "Repositories" heading and link on https://www.elastic.co/guide/en/elasticsearch/reference/current/_installation.html to https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html

A better change would be to agree on a template across all products and get just the installation sections consistent.

I think the Beats docs are laid out pretty nice;
![installationscreens](https://cloud.githubusercontent.com/assets/13542669/14220002/0ae21e1a-f823-11e5-8ff2-4cf49c56706d.png)

**Comment by clintongormley** [comment]
These docs have been completely rewritten in https://github.com/elastic/elasticsearch/commit/06604708d4bfc56eb397c6003567886bb1ce0114
