### ISSUE TITLE
ElasticSearch 2.2.0 memory dump and node goes out of cluster

### ISSUE THREAD

**Issue by lokeshhctm** [elastic/elasticsearch#17494]
ElasticSearch version: 2.2.0

JVM version: 1.8

OS version: AWS Linux C3.4xlarge

Description of the problem including expected versus actual behavior: 

After we restart ElasticSearch run fine like for 2-3 days and then suddenly one of node in cluster goes out of cluster and on node it show ElasticSeach running  but leaves a memory dump on disk. 
It doesn't come back to cluster unless we restart this.

Memory dump is about 13 GB so let me know where i can keep so keep for you to watch.

**Comment by lokeshhctm** [comment]
Please find the memory dump location:
http://admarvel.s3.amazonaws.com/uploads/lokesh1/java_pid26509.hprof.zip

**Comment by clintongormley** [comment]
Hi @lokeshhctm 

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only, and this sounds very much like misconfiguration or misuse, rather than a bug.

thanks
