### ISSUE TITLE
Document the Elasticsearch GC slow log

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#17491]
Elasticsearch has a built-in JVM GC monitoring service that logs slow GC activity in the main Elasticsearch log. The log lines produced by this monitoring service pack a lot of useful information but it's not immediately obvious what all of it means. The meaning of these log lines should be documented.

**Comment by samy-deghou** [comment]
Are you talking about all the classes from the package org.elasticsearch.monitor.jvm or specifically about the class org.elasticsearch.monitor.jvm.JvmGcMonitorService ?
Should the additional doc be part of the the main Elasticsearch log ?

**Comment by jasontedor** [comment]
> Are you talking about all the classes from the package org.elasticsearch.monitor.jvm or specifically about the class org.elasticsearch.monitor.jvm.JvmGcMonitorService ?

I'm referring to documenting the log lines that are put into the main Elasticsearch log by the JVM GC monitor service.

> Should the additional doc be part of the the main Elasticsearch log ?

Possibly, or perhaps on its own separate page linked to from other logging documentation.

**Comment by gmoskovicz** [comment]
++ on documenting this. The configuration is already shown in https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/monitor/jvm/JvmGcMonitorService.java but we need to document the defaults and the format to be user friendly.

**Comment by debadair** [comment]
The information from the 6.2 breaking changes should be rolled into the GC Logging topic.

**Comment by jrodewig** [comment]
[docs issue triage]

Closing as a stale issue. Please re-open if further action or discussion is needed. Thanks.
