### ISSUE TITLE
Add bootstrap check for ES_HEAP_SIZE

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#17490]
Would it be possible to add a bootstrap check to ensure that ES_HEAP_SIZE has been configured?  This should be a required setting when moving to production.

**Comment by jasontedor** [comment]
@clintongormley There are other ways to set the heap (for example, via `ES_JAVA_OPTS`). Do you think the check should be for `ES_HEAP_SIZE` or just that the heap is not set to the current defaults (`Xms256m` and `Xmx1g`)?

**Comment by clintongormley** [comment]
Yeah, tricky.  99% of users will use ES_HEAP_SIZE, but there's probably somebody out there using java opts for some custom reason.  If there is, I'd like to hear about why they're doing it.
