### ISSUE TITLE
Can't use org.elasticsearch.common.geo.GeoDistance.ARC anymore in scripts: class is not public

### ISSUE THREAD

**Issue by pierrre** [elastic/elasticsearch#17506]
**Elasticsearch version**: 2.3.0

**JVM version**: openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)

**OS version**: https://github.com/docker-library/elasticsearch/blob/bceef593300c241757fe93737f0e4502a269f122/2.3/Dockerfile

**Description of the problem including expected versus actual behavior**:
In my scripts, I NEED to use `org.elasticsearch.common.geo.GeoDistance.ARC`.
For various reasons, I can't use the Groovy "document field distance" methods.

_It works with Elasticsearch 1.7 or 2.2._

**Steps to reproduce**:
Do this search:

```
{
  "script_fields": {
    "test": {
      "script": "return org.elasticsearch.common.geo.GeoDistance.ARC.calculate(0, 0, 1, 1, org.elasticsearch.common.unit.DistanceUnit.METERS)"
    }
  }
}
```

**Provide logs (if relevant)**:

```
{
"took": 6,
"timed_out": false,
"_shards": {
"total": 5,
"successful": 4,
"failed": 1,
"failures": [
{
"shard": 0,
"index": "xxx",
"node": "Fnsq89X8R8m7aeO8jqUjgw",
"reason": {
"type": "script_exception",
"reason": "failed to run inline script [return org.elasticsearch.common.geo.GeoDistance.ARC.calculate(0, 0, 1, 1, org.elasticsearch.common.unit.DistanceUnit.METERS)] using lang [groovy]",
"caused_by": {
"type": "groovy_bug_error",
"reason": "BUG! UNCAUGHT EXCEPTION: class is not public: org.elasticsearch.common.geo.GeoDistance$3.calculate(double,double,double,double,DistanceUnit)double/invokeSpecial, from org.codehaus.groovy.vmplugin.v7.IndyInterface",
"caused_by": {
"type": "illegal_access_exception",
"reason": "class is not public: org.elasticsearch.common.geo.GeoDistance$3.calculate(double,double,double,double,DistanceUnit)double/invokeSpecial, from org.codehaus.groovy.vmplugin.v7.IndyInterface"
}
}
}
}
]
},
"hits": {
"total": 147356,
"max_score": 1,
"hits": [ ]
}
}
```

**Comment by pierrre** [comment]
By the way, my Elasticsearch config:
```yaml
script.inline: on
```

And my java policy file:
```
grant {
    permission org.elasticsearch.script.ClassPermission "*"; // allow all (disables filtering basically)
};
```

**Comment by pierrre** [comment]
I can "fix" the issue with `security.manager.enabled: false` in my Elasticsearch config, but it's deprecated....

**Comment by clintongormley** [comment]
@nknize can you suggest anything?

**Comment by spideyfusion** [comment]
Can we get some more feedback regarding this? I'm running into the exact same issue. As @pierrre mentioned everything works fine on version **2.2**.

**Comment by nknize** [comment]
Sorry for the delay @spideyfusion and @pierrre. I'll dig today and see what, if any, security manager changes might have caused this. Its unrelated to any of the geo changes.

**Comment by coldlamper** [comment]
I have the same problem after upgrading to 2.3.2 from 2.2.1.

``` javascript 
{"took":543,"timed_out":false,"_shards":
{"total":5,"successful":0,"failed":5,"failures":     [{"shard":0,"index":"1457361018254","node":"T8SYOug2RemSSDCLclwGog","reason":{
"type":"script_exception",
"reason":"failed to run file script [closest_listing] using lang [groovy]",
"caused_by":{"type":"groovy_bug_error",
"reason":"BUG! UNCAUGHT EXCEPTION: class is not public: org.elasticsearch.common.geo.GeoDistance$3.calculate(double,double,double,double,DistanceUnit)double/invokeSpecial, from org.codehaus.groovy.vmplugin.v7.IndyInterface","caused_by":{
"type":"illegal_access_exception",
"reason":"class is not public: org.elasticsearch.common.geo.GeoDistance$3.calculate(double,double,double,double,DistanceUnit)double/invokeSpecial, from org.codehaus.groovy.vmplugin.v7.IndyInterface"}}}}]},"hits":{"total":4443,"max_score":6.40699,"hits":[]}}
```

My policy file looks like
```
grant {
    permission org.elasticsearch.script.ClassPermission "*"; // allow all (disables filtering basically)
};
```

Maybe this helps. If I change the policy file to 
```
grant {
      permission java.security.AllPermission;    
};
```
then everything works.

**Comment by rjernst** [comment]
The problem here is a combination of groovy craziness with the GeoDistance class and how java handles enums.  Each enum value is a pkg protected anonymous class. Due to how groovy handles grabbing stuff when loading, it tries to get at this class, and that is where the error comes from.  In order to fix this, the GeoDistance class needs to not be so crazy. We shouldn't be doing crazy things like this with an enum. /cc @nknize

**Comment by pierrre** [comment]
I confirm, it works with:
```
grant {
      permission java.security.AllPermission;    
};
```
in java policy file and without modifying `security.manager.enabled`.

Thank you @coldlamper :+1:

**Comment by spideyfusion** [comment]
@coldlamper @pierrre Loosening the security policy like that is definitely something I wouldn't even consider doing in a production environment.

**Comment by pierrre** [comment]
@spideyfusion I understand, but:
- my Elasticsearch server is not publicly available (ports 9200/9300 are not open)
- I don't run untrusted scripts

Is there a security issue that I don't see?

**Comment by spideyfusion** [comment]
@pierrre You're basically crippling the security manager this way:

https://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html#AllPermission

**Comment by pierrre** [comment]
@spideyfusion 
```
This permission should be used only during testing, 
in extremely rare cases where an application or applet is completely trusted
and adding the necessary permissions to the policy is prohibitively cumbersome.
```

- `where an application or applet is completely trusted` I "trust" Elasticsearch, and I don't run unstrusted scripts in my queries
- `adding the necessary permissions to the policy is prohibitively cumbersome` I just want to use the `GeoDistance` class. Do you know a safer way to use it?

**Comment by rjernst** [comment]
@pierrre Have you tried using the distance methods available for fields?

```
{
  "script_fields": {
    "test": {
      "script": "doc['mygeofield'].arcDistance(someLat, someLon)"
    }
  }
}
```

However, as I alluded to in my previous comment here, this is a "bug" in that something about the craziness of how GeoDistance is implemented causes this problem. Pinging @nknize one more time to look into refactoring so it doesn't try to be so fancy, but I've also marked this as adoptme.

**Comment by pierrre** [comment]
@rjernst I can't use `arcDistance()` because I have several geopoints in my document, and I want to sort/extract data with these geopoints.

My mapping looks like this (PHP representation of my JSON):
```php
        return [
            'title' => [
                'type' => 'string',
                'analyzer' => 'plyce_french',
            ],
            'priority' => [
                'type' => 'integer',
            ],
            'stores' => [
                'type' => 'nested',
                'include_in_parent' => true,
                'properties' => [
                    'id' => [
                        'type' => 'string',
                        'index' => 'not_analyzed',
                    ],
                    'location' => [
                        'type' => 'geo_point',
                    ]
                ],
            ],
        ];
```

My sort script:
```php
        $script = <<<'EOT'
import org.elasticsearch.common.unit.DistanceUnit;
import org.elasticsearch.common.geo.GeoDistance;
distanceMin = null;
for (storeLocation in doc["stores.location"].values) {
    distance = GeoDistance.ARC.calculate(location.lat, location.lon, storeLocation.lat, storeLocation.lon, DistanceUnit.METERS);
    if (distanceMin == null || distance < distanceMin) {
        distanceMin = distance;
    }
}
if (distanceMin == null) {
    distanceMin = 1000000000;
}
prioritySort = pow(2, doc.priority.value);
return distanceMin / (_score * prioritySort);
EOT;
        return [
            [
                '_script' => [
                    'script' => $script,
                    'type' => 'number',
                    'params' => [
                        'location' => $this->getParamLocation($params)->toArray(true),
                    ],
                    'order' => 'asc',
                ],
            ],
            '_uid', // stable sort
        ];
```
I could use `arcDistance()` if I was able to iterate over stored values instead of the document's values.

And my script field:
```php
        $script = <<<'EOT'
import org.elasticsearch.common.unit.DistanceUnit;
import org.elasticsearch.common.geo.GeoDistance;
nearestStore = null;
distanceMin = null;
for (store in _source.stores) {
    distance = GeoDistance.ARC.calculate(location.latitude, location.longitude, store.location.lat, store.location.lon, DistanceUnit.METERS);
    if (distanceMin == null || distance < distanceMin) {
        distanceMin = distance;
        nearestStore = store.id;
    }
}
return nearestStore;
EOT;
        return [
            'script' => $script,
            'params' => [
                'location' => $this->getParamLocation($params)->toArray(),
            ],
        ];
```
This script is very ugly, because it uses the (inefficient) `_source`.
But it's actually very fast, because it's only called to process a script field.

**Comment by clintongormley** [comment]
@pierrre You know that we provide this functionality for you out of the box?

    PUT t 
    {
      "mappings": {
        "t": {
          "properties": {
            "location": {
              "type": "geo_point"
            }
          }
        }
      }
    }
    
    PUT t/t/1
    {
      "location": [
        {
          "lat": 0,
          "lon": 0
        },
        {
          "lat": 1,
          "lon": 0
        },
        {
          "lat": 2,
          "lon": 0
        },
        {
          "lat": 3,
          "lon": 0
        }
      ]
    }
    
    GET _search
    {
      "sort": [
        {
          "_geo_distance": {
            "location": {
              "lat": 0,
              "lon": 1
            },
            "order": "asc",
            "unit": "km",
            "mode": "min",
            "distance_type": "sloppy_arc"
          }
        }
      ]
    }

The distance which you're calculating in your script field is available to you in the `sort` parameter.

**Comment by pierrre** [comment]
@clintongormley yes I know.
But I don't sort by distance.
I use a combination of: "minimum distance", "_score" and "priority"

**Comment by rjernst** [comment]
@pierrre You can use `org.apache.lucene.util.SloppyMath.haversinMeters` (that is what GeoDistance.ARC uses).

**Comment by Korikulum** [comment]
@rjernst Have you actually tried if this works? I tried it & got the following error:
`No signature of method: static org.apache.lucene.util.SloppyMath.haversinMeters() is applicable for argument types: (java.lang.Double, java.lang.Double, java.lang.Double, java.lang.Double)`.

When I listed the available methods of the class (using `getMethods()`) I only got `haversin(double, double, double, double)`. As far as I can tell this is cause [Lucene 5](https://lucene.apache.org/core/5_0_0/core/org/apache/lucene/util/SloppyMath.html#haversin(double, double, double, double)) is being used while the method you mentioned is in [Lucene 6](https://lucene.apache.org/core/6_0_0/core/org/apache/lucene/util/SloppyMath.html#haversinMeters-double-double-double-double-).

So, I'm I doing something wrong here? Did `haversinMeters()` work for you?

**Comment by nknize** [comment]
> I'm using Elasticsearch v2.3.4.

Then, yes, you need to use `SloppyMath.haversin()`

**Comment by clintongormley** [comment]
@nknize did you see @rjernst 's comment about the problem with using enums in the GeoDistance class?  https://github.com/elastic/elasticsearch/issues/17506#issuecomment-215590155

What about adding distance methods to GeoPoints to make it easier to calculate distances on the GeoPoints returned by `doc['loc'].values`, or perhaps `doc['loc'].values` should return a wrapped GeoPoint with the extra functionality?  (no idea of the consequences here, just suggesting things)

**Comment by nknize** [comment]
@clintongormley I did see the comment. Since we've deprecated `SloppyArc` and fixed up haversine in Lucene, I'd actually like to remove the `GeoDistance` class altogether. I like the idea of wrapping the GeoPoint with the extra functionality but I'll need to have a look at the side effects.

**Comment by imotov** [comment]
I have discussed this issue with @jdconrad. It looks like the most optimal way to deal with this issue is to address it as part of #24946. So, I am going to close it.

Superseded by #24946

**Comment by cryptic-mystic** [comment]
Thanks for not addressing this.
