### ISSUE TITLE
Check for default date format breaking change in migration plugin

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#17517]
**Elasticsearch version**: 1.7.x

**Description of the problem including expected versus actual behavior**:

There is a breaking change related to default date formats: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/breaking_20_mapping_changes.html#_date_fields_and_unix_timestamps

While the migration plugin cannot tell what data values users will actually pass into the date field, it will still be nice to warn users about this breaking changes or as an advisory note for this can become a breaking change at runtime.

**Comment by clintongormley** [comment]
This issue was moved to elastic/elasticsearch-migration#54
