### ISSUE TITLE
Very large windows_size can cause node to run OOM

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#17522]
**Elasticsearch version**: 2.1.x, 2.3.1 (not reproducible using 2.0.x)

**Steps to reproduce**:
 1.  Create an empty index (eg. curl -XPUT http://localhost:9200/foo)
 2.  Then run the query:

```
curl -XGET "http://localhost:9200/foo/_search" -d' 
{
  "rescore": {
    "window_size": 10000000,
    "query": {
      "match_all": {}
    }
  }
}'
```

On 2.0.x, the query will return immediately.  On 2.1x and above (including 2.3.1), the query will go to town and use CPU and memory until it OOM.

**Comment by ppf2** [comment]
Might be a good candidate for the [safeguards](https://github.com/elastic/elasticsearch/issues/11511) we are adding to the product as well.

**Comment by chrismwendt** [comment]
I loaded the heap profile and found lots of objects of type `org.apache.lucene.search.ScoreDoc`:

![image](https://cloud.githubusercontent.com/assets/1387653/14261982/1235d642-fa68-11e5-87a8-1132584c95d6.png)

![image](https://cloud.githubusercontent.com/assets/1387653/14261996/2380b6b0-fa68-11e5-86cd-6ccec5a77e4a.png)
