### ISSUE TITLE
Verbose mode no longer works in elasticsearch-plugin

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#17529]
Although `elasticsearch-plugin` claims to support verbose mode, adding `-v` doesn't seem to do anything. In particular, it no longer prints out the URL of the plugin it is about to install, which is needed for offline installation.

**Comment by rjernst** [comment]
This isn't a bug with `-v`, it is simply something that is no longer printed. Here's a PR to add it: #17662
