### ISSUE TITLE
Specifying the search type dfs_query_then_fetch has no effect on nested queries

### ISSUE THREAD

**Issue by kvnlte** [elastic/elasticsearch#17535]
**Elasticsearch version**: 2.3.0
**JVM version**: 1.7.0_80
**OS version**: Windows 10

**Description of the problem including expected versus actual behavior**:
Specifying [search_type=dfs_query_then_fetch](https://www.elastic.co/blog/understanding-query-then-fetch-vs-dfs-query-then-fetch) does not work for nested queries; the scores returned are still based on local information in each shard.

**Steps to reproduce**:
Please check the gist [here](https://gist.github.com/kvnlte/6e9dc23e98f4845db0b69316b95b636a).

**Comment by clintongormley** [comment]
@martijnvg could you take a look please?

**Comment by martijnvg** [comment]
@kvnlte @clintongormley This is because the `ToParentBlockJoinQuery` which the `nested` query uses doesn't implement query extraction, which the dfs phase uses to extract terms from the query to compute distributed idf. This needs to be fixed in Lucene.

**Comment by clintongormley** [comment]
thanks @martijnvg - is there a lucene issue we can link to?

**Comment by martijnvg** [comment]
@clintongormley https://issues.apache.org/jira/browse/LUCENE-7187

**Comment by sfcgeorge** [comment]
Just bit me. Spent ages figuring why queryNorm was varying widely between documents, found dfs_query_then_fetch which fixed it, then using nested docs broke it again so I guess I'll have to run on 1 shard :(

It looks like the Lucene issue was fixed just a week ago :) So I guess this could be fixed in ES now (and "stalled" label can be removed)?

**Comment by martijnvg** [comment]
@sfcgeorge yes, it can be removed. It is already fixed in the upcoming alpha4 release, so it can be closed too.
