### ISSUE TITLE
Check for EmptyQueryBuilder at parse time

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#17541]
At the moment if `{}` is specified as a query we convert it to an `EmptyQueryBuilder` object and expect whatever calls `QueryBuilder#toQuery` to check for null and handle it appropriately. There are bugs such as https://github.com/elastic/elasticsearch/issues/17518 where we did not realise/remember to add this check. Depending on the outcome of https://github.com/elastic/elasticsearch/issues/17540 and at the very least during the deprecation period if it is accepted, it would be good to improve the handling by moving this check to the parsing stage.

When parsing compound queries and when parsing the top level query object we should check whether the inner query is an instance of `EmptyQueryBuilder` and ignore it, convert it or throw an exception at that point. We should also then make `EmptyQueryBuilder#toQuery()` throw an `UnsupportedOperationException` with an appropriate message so it is easy to see what the problem is if it does get called

**Comment by javanna** [comment]
+1 as I said in the other issue this seems logical and I am now wondering why we didn't do it in the first place. Let's see what we find on our way when trying again.

**Comment by cbuescher** [comment]
Handling empty clauses at parse time was added with https://github.com/elastic/elasticsearch/pull/17624. This includes deprecation logging and throwing an exception for empty clauses when parsing is strict. This gives us the ability to remove empty clauses in 6.0 as discussed in https://github.com/elastic/elasticsearch/issues/17540.
