### ISSUE TITLE
Deprecate empty query bodies

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#17540]
The EmptyQueryBuilder deals with the case where a query is specified in JSON as `{}`. This is not actually a valid query and we handle it differently depending on what context it is used (it may be ignored, converted to MatchAllQuery, convert to MatchNoneQuery, or an exception thrown. 

IMO we should consider `{}` an invalid query and throw an exception when parsing to prevent the hacky logic we have that creates this placeholder object and forces the parent to decide what to do with it (creating issues like https://github.com/elastic/elasticsearch/issues/17518 when we forget to add the hack to handle it). So the following search request would be deprecated:

```
GET _search
{
    "query": {
    }
}
```

as would: 

```
GET _search
{
    "query": {
        "boolean": {
            "must": [
                {}
            ]
        }
    }
}
```

@javanna and @cbuescher mentioned that they thought it was included in the first place because of clients using templates which add a query object to the JSON without first checking if they have any query to put into it. I would have thought this can be easily fixed in most templating languages so it can check if there is an object to put inside the query object before creating it.

I would like to deprecate the EmptyQueryBuilder (which actually isn't part of the Java API anyway) and the use of `{}` as a query, but wanted to open the discuss up to see what others thought and if there are any other known reasons for keeping the EmptyQueryBuilder around

**Comment by javanna** [comment]
Thanks for opening this, I am +1 on deprecating on 5.0 and removing on 6.0. We can introduce a deprecation warning (or fail in strict mode) when using `{}`. That still would leave us needing to better handle these situations for the 5.x series as the current behaviour is trappy. We discussed with Colin and Christoph that we could convert the empty brackets to something else at parse time already, so that we wouldn't have to serialize this weird query and keep track of the fact that there were empty brackets all the way to the shards where the query is converted to a lucene query. I am now wondering though why we didn't do that in the first place, maybe there were other obstacles...

**Comment by nik9000** [comment]
I remember #13406 being similar to this discussion.

**Comment by cbuescher** [comment]
I took a first look at this, it's going to be a bit more complicated but I think at this point we can get rid of the EmptyQueryBuilder while still beeing able to support the empty objects syntax `{ }` until we deprecate that at some point in the future. When we added EmptyQueryBuilder we were still on Java 7, with Java 8 we have Optional, which I think is very apropriate here. We can replace EmptyQueryBuilder by an empty Optional I think and then handle all we need to handle at parse time.

**Comment by javanna** [comment]
@nik9000 note that `{}` currently means either match_all, match_none or ignore, which we don't have a query for, it all depends on the context.

**Comment by nik9000** [comment]
> means either match_all, match_none or ignore

Sounds crazy. I vote that people with weird templating concerns just emit match_all or match_none where appropriate. I believe those are always rewritten such that they are free. If they aren't then we should fix that.

**Comment by colings86** [comment]
Discussed in FixItFriday and agreement was we should remove this but we wanted to get opinions form @rashidkpc (in terms of Kibana) and @clintongormley as well. We should also decide if we want to make this a hard break in 5.0 (since it leads to a fair few bugs) or deprecate in 5.0 and remove in 6.0.

**Comment by javanna** [comment]
I think removing in 5.0 is too much for users, although it's bad practice `{}` is probably used in lots of applications out there. I would emit deprecation warnings instead (and fail on strict mode like we do in other cases) when using `{}` in 5.0, then remove support for it everywhere in 6.0.

**Comment by rashidkpc** [comment]
As far as I know, we don't do this anywhere in kibana, however I agree with @javanna, deprecate and log warnings in 5.0, remove in 6.0

**Comment by clintongormley** [comment]
I'm actually leaning towards keeping this, as it makes building up the DSL easier on the client side, eg you start with:

    { 
      "bool": {
        "must": [],
        "should": [],
        "must_not": [],
        "filter": [],
      }
    }

And then you can just push clauses onto (eg) `bool.must` or `bool.filter'  as needed.

**Comment by javanna** [comment]
@clintongormley I think your example would still work, the behaviour you describe with empty arrays is very specific to the bool query. What we want to get rid of is the fact that an empty query has a meaning, which actually depends on where it is placed. For instance bool query will ignore the empty must clause completely when presented as follows:

```
{ 
  "bool": {
    "must": [
      {}
    ]
  }
}
```

We would like to instead return an error at all times when receiving `{}`. Makes sense?

**Comment by cbuescher** [comment]
Also things like `"constant_score" : { "filter" : { } }` shouldn't work, this doesn't really make sense and is unnecessary. In each of these cases we should decide and document properly what an empty clause like this means (in this case maybe `match_all` ?) instead of having to delay and bubble up that decision to the parent query.

**Comment by clintongormley** [comment]
Makes sense

**Comment by cbuescher** [comment]
@colings86 @clintongormley if we lean towards keeping empty claues or deprecation in 5.0 + removal in 6.0, I'd like to propose to get https://github.com/elastic/elasticsearch/pull/17624 in. It removes the need for representing the empty clause internally but still keeps the empty clause syntax in the DSL, adding a way for looging or throwing errors if we want to deprecate it.

**Comment by clintongormley** [comment]
@cbuescher sounds good to me

**Comment by javanna** [comment]
The deprecation of empty query bodies went in with #17624 . We can close this.
