### ISSUE TITLE
Remove BulkIndexByScrollResponseContentListener

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#17548]
Its causes the reindex and update_by_query to be the only API that returns a body on errors thats not a  structured error.

It also tries to do the right thing by setting the status code to the highest statuscode of all the individual failures which I don't think is terribly useful to consumers either. 

It be nicer if these API's behaved like the `_bulk` and return a 200 if the request was received properly and each response has to handle individual failures (whether conflicts=proceed or not) with an `errors` boolean.

**Comment by nik9000** [comment]
> Its causes the reindex and update_by_query to be the only API that returns a body on errors thats not a structured error.

This I'm happy to fix but I don't really understand.

> It also tries to do the right thing by setting the status code to the highest statuscode of all the individual failures which I don't think is terribly useful to consumers either.

This I really really really want to keep. Not only does it handle important cases like "your query failed for some reason" but I really like returning a REST status code when the request terminated early that explains why. Returning 200 when we bailed early isn't cool.

**Comment by Mpdreamz** [comment]
Most responses on a bad status code (400, 409, 500 etcetera) will return the throwable as structured `error` instead of the same response as on a 200.

> Returning 200 when we bailed early isn't cool.

But is exactly what we do for `_bulk`, `_mget` `_msearch` and the likes. They return a `200` with a `valid json response strucure` with`"errors": true`. Not doing this for `reindex` and `update by query` makes it the odd man out and also the only ones that returns a `valid json response structure` when the http status code is not 200. 

I personally agree that a status code indicating something is fishy with **all** of these requests would be an improvement but we'd need to settle on a single status code (e.g 400) rather then stealing a status code from one of the individual sub request failures.

**Comment by nik9000** [comment]
I don't think `_reindex` and `_update_by_query` can just be like `_bulk`, _`mget`, and `_msearch`. The latter APIs still attempt all the things you asked them to do even if there was a failure. The former don't. Personally I'm not happy that we return 200 when those APIs only partially succeed but that is a battle for another time.

Is the trouble the reindex doesn't return a single error field like the other APIs? If it did that would it make everything work better? We could cook up something like "aborted due to other errors error" if it'd make things fit.

I think it is a good thing reindex returns its progress when it aborts due to an error because that data is useful. Well, not all of it is, but stuff like the total hits and how many of each operation in performed is.

**Comment by clintongormley** [comment]
Discussed in Fix it Friday.  A bulk or mget operation is a wrapper of individual items, so it makes sense for a bulk operation with errors to return 200 (with errors listed in the body) because the coordinating node has done its job correctly.

Reindex on the other hand aborts when it encounters an error, and should return an error code.  I agree with @Mpdreamz that this should be a `400` or a `500` (depending on the error that was thrown) but it shouldn't just choose the highest error code.  These error codes have meaning for the clients (eg should i retry this request) and just because one error code happens to be `429` or `503` doesn't mean that the client should retry the reindexing request.

Regarding the structured body...  I think the information that is passed back is useful, but it is inconsistent with some responses (eg bulk) but inconsistent with others.  I considered wrapping the info inside a structured `error` body, but that feels forced.

My Perl client looks for a structured `error` but, failing that, falls back to including the whole body in the exception.  I'm not sure what other clients do here.

**Comment by nik9000** [comment]
So what is the change you want? Change the response code calculations to be "return the code if all errors have the same code, if two errors have different codes and any are 500-level then return 500. Otherwise return 400?"

**Comment by clintongormley** [comment]
No, return 500 if any errors are 500, or 400 otherwise.  (open to discussion here).

**Comment by nik9000** [comment]
Ok, so:
0. If there are no errors return 200.
1. If there are any 500 level statuses then return 500.
2. Return 400.

**Comment by clintongormley** [comment]
i think this makes sense.  @Mpdreamz ?

**Comment by nik9000** [comment]
@Mpdreamz, do you like my proposal in https://github.com/elastic/elasticsearch/issues/17548#issuecomment-231410889 ?

**Comment by Mpdreamz** [comment]
+1 my main remaining concern is that the response in case of an error (500/400) will not be in the form of a serialized exception as all the requests:

https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/search/SearchPhaseExecutionException.java#L137

That exception also attaches useful data, is there anyway we can introduce a general `ReindexFailedException` of some sorts that gets thrown that also sets all the related useful data? 

That would bring the behaviour in line with existing API's

**Comment by clintongormley** [comment]
@Mpdreamz what would this exception look like?

I tried to reorganise the response to be a structured exception while maintaining the useful info that is returned, but didn't like what I ended up with.  Can you suggest something?

**Comment by Mpdreamz** [comment]
How individual bulk items failures response looks like (409 lifted from failures)

```json
{
  "took" : 654,
  "timed_out" : false,
  "total" : 2,
  "updated" : 0,
  "created" : 0,
  "deleted" : 0,
  "batches" : 1,
  "version_conflicts" : 2,
  "noops" : 0,
  "retries" : {
    "bulk" : 0,
    "search" : 0
  },
  "throttled_millis" : 0,
  "requests_per_second" : "unlimited",
  "throttled_until_millis" : 0,
  "failures" : [
    {
      "index" : "nest-09ffd83a-clone",
      "type" : "test",
      "id" : "1",
      "cause" : {
        "type" : "version_conflict_engine_exception",
        "reason" : "[test][1]: version conflict, document already exists (current version [1])",
        "index_uuid" : "dwwlqnkfTfaq1zefjq0XnA",
        "shard" : "3",
        "index" : "nest-09ffd83a-clone"
      },
      "status" : 409
    },
    {
      "index" : "nest-09ffd83a-clone",
      "type" : "test",
      "id" : "2",
      "cause" : {
        "type" : "version_conflict_engine_exception",
        "reason" : "[test][2]: version conflict, document already exists (current version [1])",
        "index_uuid" : "dwwlqnkfTfaq1zefjq0XnA",
        "shard" : "2",
        "index" : "nest-09ffd83a-clone"
      },
      "status" : 409
    }
  ]
}
```

vs reindexing into the same index (400)

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "action_request_validation_exception",
        "reason" : "Validation Failed: 1: reindex cannot write into an index its reading from [nest-9aced9c5];"
      }
    ],
    "type" : "action_request_validation_exception",
    "reason" : "Validation Failed: 1: reindex cannot write into an index its reading from [nest-9aced9c5];"
  },
  "status" : 400
}
```

vs making a script error (400)

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "action_request_validation_exception",
        "reason" : "Validation Failed: 1: reindex cannot write into an index its reading from [nest-6893097f];"
      }
    ],
    "type" : "action_request_validation_exception",
    "reason" : "Validation Failed: 1: reindex cannot write into an index its reading from [nest-6893097f];"
  },
  "status" : 400
}
```

Now for all elasticsearch requests we can shortcircuit bad http status codes to a generic error handling mechanism e.g pseudo code

```F#
type elasticsearch_response = error | response
let response = match status
| bad_response -> error
| _ -> response
```

In our client `response` can be a fully deserialized type but folks can even request the unititialized response stream as `response` so this short circuiting on status code is very very useful.

Except for this special case within the `_reindex` we'd now have to peek wether it has an `error` and if not still return a `response`. Something which for us would be expensive because we deserialize straight from a forward readonly (tcp) stream and can not seek backwards forcing us to do a double read on this API.

Going back on my original +1 for setting a fixed 400 or 500 and still maintain aligning it with bulk would be better, personal preference and agreement that https://github.com/elastic/elasticsearch/issues/17548#issuecomment-231410889 is sementically sound aside.

The only other alternative would be to wrap it in an exception and attach all the data as metadata (which we already do in some other cases as linked earlier. 

```json
{
  "error" : {
    "root_cause" : [
      {
        "type" : "reindex_conflict_exception",
        "reason" : "Reindexing some items failed"
      }
    ],
    "type" : "reindex_conflict_exception",
    "reason" : "Reindexing some items failed"
    "status" : 400
    "took" : 654,
    "timed_out" : false,
    "total" : 2,
    "updated" : 0,
    "created" : 0,
    "deleted" : 0,
    "batches" : 1,
    "version_conflicts" : 2,
    "noops" : 0,
    "retries" : {
      "bulk" : 0,
      "search" : 0
    },
    "throttled_millis" : 0,
    "requests_per_second" : "unlimited",
    "throttled_until_millis" : 0,
    "failures" : [
      {
        "index" : "nest-09ffd83a-clone",
        "type" : "test",
        "id" : "1",
        "cause" : {
          "type" : "version_conflict_engine_exception",
          "reason" : "[test][1]: version conflict, document already exists (current version [1])",
          "index_uuid" : "dwwlqnkfTfaq1zefjq0XnA",
          "shard" : "3",
          "index" : "nest-09ffd83a-clone"
        },
        "status" : 409
      },
      {
        "index" : "nest-09ffd83a-clone",
        "type" : "test",
        "id" : "2",
        "cause" : {
          "type" : "version_conflict_engine_exception",
          "reason" : "[test][2]: version conflict, document already exists (current version [1])",
          "index_uuid" : "dwwlqnkfTfaq1zefjq0XnA",
          "shard" : "2",
          "index" : "nest-09ffd83a-clone"
        },
        "status" : 409
      }
    ]
  },
}
```

Which I agree @clintongormley feels very icky :/ 

Returning `200` ala bulk introduce an `errors: false|true` seems like the less of two *evils* in this case and unifies error handling for these related multi document requests.

As mentioned my personal preference would actually also be for the bulk and the likes to return a 400/500 in case of individual item failures. Having to check for `errors: true` is often forgotten but not sure if too open that can of worms on this ticket :smile:

**Comment by dakrone** [comment]
@Mpdreamz since this has been untouched for so long, is this still something you need?

**Comment by Mpdreamz** [comment]
This would introduce a breaking change in `6.x` now so not immediately. I definitely want to reopen this discussion for `7.x` but more than happy to kick off a new ticket then.

cc @elastic/es-clients
