### ISSUE TITLE
Java API: Scroll search still uses deprecated SCAN search type

### ISSUE THREAD

**Issue by consulthys** [elastic/elasticsearch#17555]
In the Java client API documentation, when [using scrolls in Java](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-search-scrolling.html), the sample code still uses `SearchType.SCAN` even though this was [deprecated in 2.1](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_21_search_changes.html#_literal_search_type_scan_literal_deprecated).

I guess the sample code needs to be revised to match what the [REST documentation on scrolling](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-request-scroll.html) states, namely that a sort on `_doc` should simply be added instead of using the `SCAN` search type.

```
SearchResponse scrollResp = client.prepareSearch(test)
        .setScroll(new TimeValue(60000))
        .setQuery(qb)
        .setSize(100)
        .addSort("_doc", SortOrder.ASC)
        .execute().actionGet(); //100 hits per shard will be returned for each scroll
```

**Comment by javanna** [comment]
Thanks for bringing this up @consulthys . Would you be up for sending a PR that fixes the docs?

**Comment by consulthys** [comment]
Sure thing, I will do that today.
