### ISSUE TITLE
Incomplete results when using geo_distance for large distances

### ISSUE THREAD

**Issue by jweber** [elastic/elasticsearch#17578]
**Elasticsearch version**: 2.2.2, 2.3.1, 5.0.0-alpha1

**JVM version**: 1.7.0_95 (Ubuntu 14.04), 1.8.0_77 (Windows 8.1)

**Description of the problem including expected versus actual behavior**:
Starting with version 2.2.2, using the _geo_distance_ query does not appear to be accurate when using large distance values. In the included reproduction, documents are added that are placed from 1 to 10,000 miles away from the point at _47.60621, -122.33207_. Executing a query for matches up to 10,000 miles away only returns the documents from 1 to 5,000 miles away.

If I profile the query, it appears that somewhere around a 6,000mi distance, the bounding box generated by the GeoPointDistanceQueryImpl query maxes out at Lower Left: [-180.0,-37.181370025500655] Upper Right: [180.0,90.0]. It also appears that the max distance in the _geo_distance_ query becomes less the closer to a pole that you get.

Running the same test with 2.1.2 returns all expected results up to 10,000 miles away.

```bash
curl -XDELETE localhost:9200/distance-test

curl -XPUT localhost:9200/distance-test -d '{
    "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 0,
        "index.queries.cache.type": "none"
    }
}'

curl -XPUT localhost:9200/distance-test/document/_mapping -d '{
    "properties": {
        "name": {
            "type": "string"
        },
        "location": {
            "type": "geo_point",
            "lat_lon": true
        }
    }
}'

curl -XPUT localhost:9200/distance-test/document/_bulk -d '{ "index": { "_id": 1 } }
{ "name": "1 mile", "location": "47.606208, -122.310628" }
{ "index": { "_id": 2 } }
{ "name": "10 miles", "location": "47.60601, -122.117647" }
{ "index": { "_id": 3 } }
{ "name": "100 miles", "location": "47.586236, -120.188375" }
{ "index": { "_id": 4 } }
{ "name": "1000 miles", "location": "45.654944, -101.405702" }
{ "index": { "_id": 5 } }
{ "name": "2000 miles", "location": "40.275895, -83.006558" }
{ "index": { "_id": 6 } }
{ "name": "3000 miles", "location": "32.469747, -67.847419" }
{ "index": { "_id": 7 } }
{ "name": "4000 miles", "location": "23.156323, -55.315033" }
{ "index": { "_id": 8 } }
{ "name": "5000 miles", "location": "12.986677, -44.486196" }
{ "index": { "_id": 9 } }
{ "name": "6000 miles", "location": "2.40577, -34.530192" }
{ "index": { "_id": 10 } }
{ "name": "7000 miles", "location": "-8.24639, -24.729009" }
{ "index": { "_id": 11 } }
{ "name": "8000 miles", "location": "-18.648019, -14.38816" }
{ "index": { "_id": 12 } }
{ "name": "9000 miles", "location": "-28.413215, -2.7355" }
{ "index": { "_id": 13 } }
{ "name": "10000 miles", "location": "-36.996556, 11.128372" }
'
```

Search query:
```http
GET localhost:9200/distance-test/document/_search 
{
	"size": 0,
	"from": 0,
	"profile": true,
	"_source": ["name"],
	"query": {
	    "geo_distance": {
			"distance": "10000mi",
			"location": "47.60621, -122.33207"
		}
	},
	"sort": [{
		"_geo_distance": {
			"location": "47.60621, -122.33207",
			"order": "desc",
			"unit": "mi"
		}
	}]
}
```

**Comment by clintongormley** [comment]
@nknize please could you take a look?

**Comment by jweber** [comment]
I just tried this out in 5.0.0-alpha2 and it's still showing the same behavior.

**Comment by nknize** [comment]
> it appears that somewhere around a 6,000mi distance, the bounding box generated by the GeoPointDistanceQueryImpl query maxes out

hmmm... This sounds like could be a units issue with `maxRadialDistance`?  I'll try to reproduce and see what's going on.

**Comment by jweber** [comment]
If I shift the query origin further north then the max distance become less before the bounding box stops growing. For example, when using location _71.284992,-156.9219567_ (Barrow, AK) the bounding box stops changing at a query distance of around 2,600 miles.

I'm also assuming that the _Lower Left: [x,y], Upper Right: [x,y]_ being reported by the GeoPointDistanceQueryImpl lucene query when running the query profiler is the bounding box. Hopefully I'm not wrong on that!

**Comment by nknize** [comment]
Ah. This was a radius restriction bug that was fixed in https://issues.apache.org/jira/browse/LUCENE-7137.

**Comment by jweber** [comment]
@nknize: Any chance of that fix getting applied to a 2.3.x release?

**Comment by nknize** [comment]
Possibly 2.3.x, that might be a stretch. At minimum it should really make 5.0 but as it stands right now the fix isn't available until Lucene 6.1 which means 5.x. I'll dig and keep this issue updated.

**Comment by jweber** [comment]
@nknize I noticed that alpha4 is using Lucene 6.1 so I re-ran this test. It's still exhibiting the same unexpected behavior.

**Comment by nknize** [comment]
@jweber I still had the radial restriction in ES. I just pushed a fix that will be in the next release.

**Comment by bubchi89** [comment]
Do you guys have any suggestions for a workaround for this in 2.3.x? Or is the best we can do is validate the user's query before passing it along to ES? Does it sound reasonable to validate that GeoUtils.maxRadialDistance() doesn't shrink the input distance?
