### ISSUE TITLE
Reindex and Update by Query tests fail due to in flight contexts

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#17582]
Build URL: 
http://build-us-00.elastic.co/job/es_core_master_window-2008/3478/

Failed tests:
org.elasticsearch.index.reindex.BulkByScrollTaskTests.testDelayAndRethrottle
org.elasticsearch.index.reindex.BulkByScrollTaskTests.testBasicData
org.elasticsearch.index.reindex.BulkByScrollTaskTests.testProgress
org.elasticsearch.index.reindex.BulkByScrollTaskTests.testStatusHatesNegatives
org.elasticsearch.index.reindex.ReindexFailureTests.testResponseOnSearchFailure
org.elasticsearch.index.reindex.ReindexFailureTests.testFailuresCauseAbortDefault
org.elasticsearch.index.reindex.ReindexFailureTests.testSettingTimestampIsValidationFailure
org.elasticsearch.index.reindex.ReindexFailureTests.testAbortOnVersionConflict
org.elasticsearch.index.reindex.UpdateByQueryMetadataTests.testTTL
org.elasticsearch.index.reindex.UpdateByQueryMetadataTests.testTimestampIsCopied
org.elasticsearch.index.reindex.UpdateByQueryMetadataTests.testRoutingIsCopied
org.elasticsearch.index.reindex.UpdateByQueryWithScriptTests.testChangeSource
org.elasticsearch.index.reindex.UpdateByQueryWithScriptTests.testScriptAddingJunkToCtxIsError
org.elasticsearch.index.reindex.UpdateByQueryWithScriptTests.testModifyingCtxNotAllowed

**Comment by colings86** [comment]
@nik9000 would you be able to take a look at these?

**Comment by nik9000** [comment]
I'm tired and this hasn't reproduced for that I've seen so I'm probably going to leave this for the morning.

**Comment by nik9000** [comment]
Reproduces with `gradle :modules:reindex:test -Dtests.seed=5A143CB0A60E2250`. You can't run any of the individual reproduction lines though.

**Comment by nik9000** [comment]
Er - I lied. It doesn't reproduce. But if I add a delay in the right spot I can get it to reproduce.

**Comment by nik9000** [comment]
I've opened a PR to get more information the next time this happens but I can't reproduce locally.

**Comment by nik9000** [comment]
I think the right thing is to close this and wait until it happens again on CI?

**Comment by colings86** [comment]
I think we should add information to debug this and wait for it to happen again (as you have done, thanks :) ) but I don;t think it's right to close this issue. This was a valid test failure and hasn't been fixed so IMO the issue should remain open. We should then add further information to this issue when it fails again on CI.

**Comment by nik9000** [comment]
Reopening but marking stalled as we're waiting for another failure of this kind so we can use the extra information we added to the failure message to debug it.

**Comment by nik9000** [comment]
I think we tracked this one down a while back. Closing. If we see it again we can reopen.
