### ISSUE TITLE
No correct phrase highlighting with plain highlighter

### ISSUE THREAD

**Issue by schoch** [elastic/elasticsearch#17581]
**Elasticsearch version**: 2.3.2

**JVM version**: Java(TM) SE Runtime Environment (build 1.8.0_40-b27)

**OS version**: OSX 10.11.3

**Description of the problem including expected versus actual behavior**:
The plain highlighter highlights single terms of phases that do not completely match. My expected behavior would be that a given search phrase must completely match, before it is used for highlighting.

**Steps to reproduce**:
 1. Create a new document
`PUT sample/doc/1
{
 "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed hendrerit ante." 
}`
 2. Do a query_string query with a quoted phrase
`GET sample/doc/_search
{
 "query": {
   "filtered": {
     "query": {
       "query_string": {
         "default_field": "content",
         "query": "\"lorem something\" OR ipsum" 
       }
     }
   }
 },
 "highlight": {
   "fields": {
     "content": {}
   }
 }
}`
_lorem_ gets highlighted, but I do not expect that since the phrase _lorem something_ does not exist in the document

 3. Do an equivalent bool query
`GET sample/doc/_search
{
 "query": {
   "bool": {
     "should": [
       {
         "match_phrase": {
           "content": "lorem something" 
         }
       },
       {
         "match": {
           "content": "ipsum" 
         }
       }
     ]
   }
 },
 "highlight": {
   "fields": {
     "content": {}
   }
 }
}`
Same result.
 4. Switch the elements of the bool query
`GET sample/doc/_search
{
 "query": {
   "bool": {
     "should": [
        {
         "match": {
           "content": "ipsum" 
         }
       },
       {
         "match_phrase": {
           "content": "lorem something" 
         }
       }
     ]
   }
 },
 "highlight": {
   "fields": {
     "content": {}
   }
 }
}`

Whats that? Just _ipsum_ gets highlighted (as expected). That seems like a bug to be. I did not try to reproduce that with the other highlighters.

**Comment by jimferenczi** [comment]
The bug is in Lucene and has been fixed for the 6.x series here:
https://issues.apache.org/jira/browse/LUCENE-7112

@jpountz should we backport the fix for Elasticsearch 2.x ?

**Comment by clintongormley** [comment]
thanks for looking @jimferenczi.  Let's not backport - the fix is already in 5.0

**Comment by havran** [comment]
Seems this bug is fixed in Lucene 5.5.1 but Elasticsearch 2.x still use Lucene 5.5.0. No plans for using Lucene 5.5.1?
