### ISSUE TITLE
Remove min_doc_count option on histogram aggregations

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#17589]
Always assume min_doc_count=0.

**Comment by colings86** [comment]
@rashidkpc @rashidkpc Am I right in saying Kibana now uses `min_doc_count: 1`?

**Comment by rashidkpc** [comment]
Kibana does use `min_doc_count: 1`, though I'm fine getting rid of this setting and switching back to min_doc_count: 0 as it lets us get rid of some 0 filling code. Just log a ticket in Kibana with a reference to this one when you do it so we know to re-introduce `extended_bounds`.

I don't honestly see much reason to dump this though. From what I understand from @colings86 we can't take advantage of certain caching strategies with `extended_bounds`. Getting rid of the ability to strip empty buckets from the middle of the set, thus reducing response size, while still requiring users to manually fill to the edges of their desired range feels odd? Maybe the caching thing can be fixed?

**Comment by markharwood** [comment]
cc @elastic/es-search-aggs

**Comment by polyfractal** [comment]
We chatted about this in the team meeting.  There's still debate about if `min_doc_count` should be removed, but we agreed that the caching issue should be fixed before we even consider removing it.

I've opened an issue here to track the `extended_bounds` caching problem: https://github.com/elastic/elasticsearch/issues/31561

@elastic/kibana-discovery Assuming we fix the extended bounds issue, how much would removing `min_doc_count` affect Kibana?  Minor code changes?  Widespread refactoring?

**Comment by Bargs** [comment]
I don't think we use it explicitly on Discovery, but it looks like a lot of other teams do. I did a quick search of the code base and I see 101 occurrences of `min_doc_count` across visualize, ML, APM, TSVB and some other random stuff. I'm not sure how many of these are histogram aggs. It's probably worth casting a wider net, sending a mail that includes everyone who works in Kibana.

**Comment by wchaparro** [comment]
Closing as not planned, focus on ES|QL development
