### ISSUE TITLE
Stop returning additional HTTP headers on exceptions

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#17593]
When an `ElasticsearchException` is bubbled up to HTTP, there are additional headers being returned.

``` bash
# curl -X DELETE localhost:9200/test
{"acknowledged":true}

# curl -X PUT localhost:9200/test -v
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9200 (#0)
> PUT /test HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=UTF-8
< Content-Length: 21
<
* Connection #0 to host localhost left intact
{"acknowledged":true}


# curl -X PUT localhost:9200/test -v
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9200 (#0)
> PUT /test HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< es.index: test
< Content-Type: application/json; charset=UTF-8
< Content-Length: 203
<
* Connection #0 to host localhost left intact
{"error":{"root_cause":[{"type":"index_already_exists_exception","reason":"already exists","index":"test"}],"type":"index_already_exists_exception","reason":"already exists","index":"test"},"status":400}
```

If those headers are not needed on HTTP, maybe it does not make any sense to return them? All the information looks available to me in the HTTP response body, but I am possibly missing some cases.

**Comment by jpountz** [comment]
@clintongormley do you know if this feature is used by the clients?

**Comment by clintongormley** [comment]
@jpountz i'm unaware of anybody using this feature.

**Comment by clintongormley** [comment]
Let's remove these headers

**Comment by javanna** [comment]
These headers are printed out as part of the response body already, I don't think there's any need to send them back as response headers too. They were introduced to prevent having to add custom exceptions to our codebase whenever we need to throw an exception that has to hold some additional metadata that ElasticsearchException doesn't support. Maybe the headers naming should be changed as well to something like metadata? @s1monw @tlrx  what do you think?
