### ISSUE TITLE
Range or bucket defining pipeline aggregation

### ISSUE THREAD

**Issue by cwurm** [elastic/elasticsearch#17590]
Let's say the data set is transactions made by users and the question we want to ask is "Which users have transactions totalling between 100 - 200, 200 - 300, etc.?"

At the moment, there doesn't seem to be a way to do this in one query.

Given documents like this:

```
"user": user1,
"credit": 50
```

we can answer questions such as "Show me only the users that have transactions totalling more than 100" by using a `bucket_selector` like this:

```
"aggs": {
  "users": {
    "terms": {
      "field": "user"
    },
    "aggs": {
      "sum_credit": {
        "sum": {
          "field": "credit"
        }
      },
      "the_pipeline_agg": {
        "bucket_selector": {
          "buckets_path": {
            "sumCredit": "sum_credit"
          },
          "script": "sumCredit > 100"
        }
      }
    }
  }
}
```

And now we could form ranges on the client side by running several of these queries in parallel.

But to answer the original question we would need some form of range pipeline aggregation like:

```
"bucket_range": {
  "buckets_path": {
    "sumCredit": "sum_credit"
  },
  "ranges": [
    { "to": 100 },
    { "from": 100, "to": 200 }
  ]
}
```

Or maybe even a more generic "bucket defining" pipeline agg, e.g.:

```
"bucket_definer": {
  "buckets_path": {
    "sumCredit": "sum_credit"
  },
  "bucket_script": "floor(sumCredit / 100)"
}
```

This would define automatically define buckets for 0-100, 100-200, and so on.

**Comment by colings86** [comment]
We discussed this in FixItFriday and thought it could be quite a useful aggregation but we would want to implement it in a generic way (so it can be used to pivot on any aggregation rather than alway producing ranges). This will make the API possibly fairly tricky so will need some thinking about

**Comment by phoenixgao** [comment]
Any updates on this topic?

**Comment by hisuwh** [comment]
What is happening with this?  I really need something like this

**Comment by yadnesh-aaxis** [comment]
We need this feature as well.

**Comment by markharwood** [comment]
>"Which users have transactions totalling between 100 - 200, 200 - 300, etc.?"

If I understand the requirement correctly the idea is to take the results of a `terms:user>sum:credit` agg tree and invert it into a `range:credit>terms:user` tree. I can see this works for the `sum` leaf but it sounds complex (for users and implementors) if we have other sibling or grandparent aggs to worry about as well.
Putting aside the complexity, I worry about the accuracy issues in the example use case and question if we should encourage this style of reporting where data is fused unreliably at query time on high-cardinality keys and then fed into further reporting. Given a bank with many users (most of them do) then a query on an event-based transaction store to find high-spend individuals would yield only the top N users that can be carried back in one shard response. The true high-spend users may be under-valued or completely missing. A user making many small payments across many indices/shards may not appear in the final N users who more-than-likely consist of users making single large payments. 

Currently our error-margin reporting on terms aggs only accounts for _numbers_ of documents - not the value of those documents. This financial error margin is unbounded. Building ever-higher aggregation constructs on shaky foundations is perhaps not a good idea. If we offer this feature perhaps it should only work for terms aggs where the reported error-bound for number of docs is zero?
Compare this with an entity-centric index where data is fused at index time and each user has a single value and a regular histogram can group users into high-spend/low-spend ranges etc without accuracy concerns. Too much query-time fusion is a bad thing.

Thoughts, @cwurm?

**Comment by markharwood** [comment]
@cwurm - closing because this was long-standing "high hanging fruit" in terms of implementation complexity and with the accuracy concerns this looks undesirable. We can always re-open if we decide to revisit this.
