### ISSUE TITLE
Additional "moving" pipeline aggregations 

### ISSUE THREAD

**Issue by kurtado** [elastic/elasticsearch#17607]
Similar to the "moving average" pipeline agg, it could be useful to be able to calculate moving max, moving min, moving variance, etc. Possibly allowing the user to configure which metric agg contributed to the moving value (min, max, avg, etc).

(This arose in the context of a moving median pipeline, although calculating median in the first place can be difficult).

**Comment by l8liu** [comment]
Moving standard deviation is useful

**Comment by colings86** [comment]
@elastic/es-search-aggs

**Comment by polyfractal** [comment]
Closed by #29594
