### ISSUE TITLE
Loosing file.content on _update

### ISSUE THREAD

**Issue by ptrussart** [elastic/elasticsearch#17618]
Hi,

I have a problem linked on the mapping I use : 
```
PUT documents/myDoc/_mapping
{
    "myDoc": {
        "_source": {
            "excludes": [
                "file"
            ]
        },
        "properties": {
           "title": {
                  "type": "string"
           },
            "file": {
                "type": "attachment",
                "fields": {
                    "content": {
                        "type": "string",
                        "term_vector": "with_positions_offsets",
                        "store": true
                    }
            }
       }
}
```
I'm doing this in order to not storing the file content and to be able to retrieve highlighted text from the extracted text. 
I set the `file._content` with the document content and then I can query on the extracted text with `file.content`. It works fine.

However, I have an issue when I try to update an entry. If I do, for instance
```
POST documents/myDoc/123456789/_update
{
  "doc": { "title": "my new title"}
}
```
After this update, I will have an empty value for `file.content`. From what I have understood, this is the standard behavior as the `file` is excluded from the `_source` and because file.content is also not in the `_source`. On partial updates, Elasticsearch looses the properties which are not on the `_source`.

I know I can re-upload the document on every update but it is not convenient at all. My question is : Is there a way to force the `file.content` (the extracted text) to be part of the `_source`, so I will not loose the extracted text on a partial update ?

Thanks in advance for your answer.

Elasticsearch version : 2.2
JVM version : 1.7.0_71
OS version : Windows 2012 RC2

**Comment by dadoonet** [comment]
Comment I put on https://github.com/elastic/elasticsearch-mapper-attachments/issues/209#issuecomment-207363491

> And for now I don't believe the update API could work with attachments.

For the very least, we don't have any test to cover this use case.

**Comment by clintongormley** [comment]
What is for sure is that the update API can't work as expected when fields are excluded from the `_source`.  The  `_source` is the only source of data - what you are doing is the equivalent of creating a new document without passing the `file` field.

This is documented here: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html#include-exclude
