### ISSUE TITLE
Better IPv6 support for installing plugins

### ISSUE THREAD

**Issue by aholen** [elastic/elasticsearch#17611]
**Elasticsearch version**: elasticsearch-2.2.1

**JVM version**: openjdk version "1.8.0_71"

**OS version**: CentOS Linux release 7.1.1503 (Core)

**Description of the problem including expected versus actual behavior**:
Having problems installing plugins on a server with a private IPv4 address and a global/public IPv6 address - because bin/plugin probably tries IPv4 first, then IPv6. If the server has a AAAA-record, the plugin-installer should try IPv6 first (if not link-local), then IPv4, or at least provide configuration-options for use IPv4 or IPv6, or prefer IPv6 over IPv4 and vice versa.

https://tools.ietf.org/html/rfc3484

**Steps to reproduce**:
 1. Install Elasticsearch 2.2.1 on a system with private IPv4 address and a public IPv6 address
 2. Install a plugin ```/usr/share/elasticsearch/bin/plugin install --batch discovery-multicast```
 3. Fails with ```Failed: ConnectException[Network is unreachable]```

**Provide logs (if relevant)**:
````
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 192.168.100.20/24 scope global ens160
       valid_lft forever preferred_lft forever
    inet6 yyyy:yyy:yyyy:yyyy:yyy::yy/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:xxxx:xxxx:952c/64 scope link
       valid_lft forever preferred_lft forever
```

````
dig download.elastic.co AAAA
...
;; ANSWER SECTION:
download.elastic.co.    60      IN      CNAME   dualstack.download-colb-770446651.us-east-1.elb.amazonaws.com.
dualstack.download-colb-770446651.us-east-1.elb.amazonaws.com. 60 IN AAAA 2406:da00:ff00::b848:f489
dualstack.download-colb-770446651.us-east-1.elb.amazonaws.com. 60 IN AAAA 2406:da00:ff00::b849:ab32
dualstack.download-colb-770446651.us-east-1.elb.amazonaws.com. 60 IN AAAA 2406:da00:ff00::b849:ba57
...
````
<!--
If you are filing a feature request, please remove the above bug
report block and provide responses for all of the below items.
-->

**Comment by jasontedor** [comment]
@aholen I think that you can solve this already with

```
$ ./bin/plugin -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true install marvel-agent
```

Would you be able to try this and report back?

**Comment by aholen** [comment]
@jasontedor Thanks for the tip - that didn't work, but this worked on both Oracle's 1.8.0_40 and openjdk 1.8.0_71:
```
./bin/plugin install -Djava.net.preferIPv6Addresses=true  --batch discovery-multicast
```

**Comment by jasontedor** [comment]
I don't think that that should make any different, but I would like to understand if and why it does. The reason that I do not think it should make any difference is because the -D parameters are parsed by the plugin script and passed as arguments when starting the JVM.

```bash
$ bash -x ./bin/plugin install -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true --batch discovery-multicast
.
.
.
/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin/java -client -Delasticsearch -Des.path.home=/usr/local/Cellar/elasticsearch/2.3.1/libexec -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true -Des.default.path.conf=/usr/local/Cellar/elasticsearch/2.3.1/libexec/config -cp '/usr/local/Cellar/elasticsearch/2.3.1/libexec/lib/*' org.elasticsearch.plugins.PluginManagerCliParser install --batch discovery-multicast
-> Installing discovery-multicast...
.
.
.
```

and

```bash
$ bash -x ./bin/plugin -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true install --batch discovery-multicast
.
.
.
/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin/java -client -Delasticsearch -Des.path.home=/usr/local/Cellar/elasticsearch/2.3.1/libexec -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true -Des.default.path.conf=/usr/local/Cellar/elasticsearch/2.3.1/libexec/config -cp '/usr/local/Cellar/elasticsearch/2.3.1/libexec/lib/*' org.elasticsearch.plugins.PluginManagerCliParser install --batch discovery-multicast
-> Installing discovery-multicast...
.
.
.
```

Showing that they both cause exactly the same JVM arguments to be used. As far as `-Djava.net.preferIPv4Stack=false`, that is the default value but I included it to be explicit.

**Comment by aholen** [comment]
My mistake @jasontedor - I didn't see your ```-Djava.net.preferIPv6Addresses=true``` in your first post, and tried only with ```-Djava.net.preferIPv4Stack=false``` - naturally that didn't make any difference. I agree with you that the order of the parameteres don't make any difference, it is the ```-Djava.net.preferIPv6Addresses=true```  that is the vital part here.

**Comment by jasontedor** [comment]
@aholen Perfect, thank you for clarifying! 😄 

> it is the ```-Djava.net.preferIPv6Addresses=true```  that is the vital part here.

Yes.
