### ISSUE TITLE
Rename reindex's timeout to shard_timeout or something less missleading

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#17620]
**Describe the feature**:
Reindex and update_by_query support a `timeout` parameter. It is just piped through to the bulk requests that they make. So it isn't a timeout on the reindex at all - it is a timeout on shards to become available for each individual bulk request. So the name is confusing.

**Comment by Helen-Zhao** [comment]
Would be keen to pick this up, what would you suggest is a good name to rename timeout to? For example `individual_shard_timeout`?

**Comment by dakrone** [comment]
We haven't touched this in a year and it's received no +1s, so I believe this can be closed.
