### ISSUE TITLE
Packaging tests fail and package installation is dependent on user's umask

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#17634]
When running the packages on my development machines, they fail due to incorrect expected permissions, for example, my `umask` permissions are 002, which means that directories are created with 775 permissions, however, our tests compare the directories from the *user* with the ones generated by a *root* install, which has a different umask (022).

Thus, you get:

```
# Expected privileges: 775, found 755
not ok 10 [TAR PLUGINS] install jvm-example plugin with a custom CONFIG_DIR
# (from function `assert_file' in file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/packaging_test_utils.bash, line 181,
#  from function `install_jvm_example' in file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/plugins.bash, line 87,
#  in test file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/25_tar_plugins.bats, line 143)
#   `CONF_DIR="$ESCONFIG" install_jvm_example' failed
```

And

```
# Expected privileges: 644, found 664
not ok 27 [TAR PLUGINS] check lang-expression module
# (from function `assert_file' in file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/packaging_test_utils.bash, line 181,
#  from function `assert_module_or_plugin_file' in file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/packaging_test_utils.bash, line 208,
#  from function `check_module' in file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/modules.bash, line 35,
#  from function `check_secure_module' in file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/modules.bash, line 43,
#  in test file /elasticsearch/qa/vagrant/src/test/resources/packaging/scripts/25_tar_plugins.bats, line 242)
#   `check_secure_module lang-expression antlr4-runtime-*.jar asm-5.0.4.jar asm-commons-*.jar asm-tree-*.jar lucene-expressions-*.jar' failed
# Should exist: /tmp/elasticsearch/modules/lang-expression
```

(and many others)

I think there are multiple options for fixing this:

1. Set the umask bats will expect in the tests before these tests are run
2. Change the tests to hardcode the correct "expected" permissions instead of
   inferring them from the user's directory
3. Change our packaging to set the permissions correctly instead of relying on
   umask

Personally, I think we should go with number 3.

Number 1 I'm not actually sure would work, I haven't tested it, but we would be
fooling ourselves if anyone actually changed their umask in the field.

Number 2 would be semi-okay, but again, if the umask changes or a user installs
the package as non-root (yes, with `dpkg --force-not-root`) the permissions will
be different because root's umask will not be used.

I really don't like the variance of number 1 and number 2, we have a lot of
checks to tell users when their settings may be wrong, this is a situation where
we should set the permissions to the exact values they should be to prevent
unintended errors. Hence, I believe we should go with number 3.

**Comment by jasontedor** [comment]
I think that we should set the permissions to what we think they should be rather than relying on the end-user umask. If the end-user has their umask wrong, we could expose permissions on directories that we don't want to exposed. While a valid claim can be made that it is the end-users responsibility, and that going against the umask possibly violates the principle of least astonishment, I would rather us choose the more secure option here. Thus, I favor option 3.

**Comment by nik9000** [comment]
> I think that we should set the permissions to what we think they should be rather than relying on the end-user umask.

I think we should set the permissions to what we think they should be. To me the experience with the deb and rpm is paramount - all the permissions should "just work". 644, root owned, whatever. Just set the permissions to what we think they should be. If the user doesn't like them I expect they'll change them with puppet/chef/ansible/bash scripts/duct tape/bubblegum.
