### ISSUE TITLE
shard cannot be allocated on same node [3OedVZN9QVKU9Hw7tn2h2w] it already exists on

### ISSUE THREAD

**Issue by hearntho** [elastic/elasticsearch#17636]
**Elasticsearch version**: 1.7.5

**JVM version**:

**OS version**: CentOS 7.2.1511

**Description of the problem including expected versus actual behavior**:  I have been working on this for a few days now, and found similar issues, but nothing that matched what I am seeing.  Every time I restart elasticsearch the shards begin to initialize until this point via _cluster/health

{
  "cluster_name": "elasticsearch",
  "status": "red",
  "timed_out": false,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "active_primary_shards": 5458,
  "active_shards": 5458,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 5574,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0
}

I then attempt to manually reroute shards, which fails.  I have run reroute?explain and receive the following:

 "explanations": [
    {
      "command": "allocate",
      "parameters": {
        "index": "logstash-2016.03.11-mr",
        "shard": 0,
        "node": "loggy",
        "allow_primary": true
      },
      "decisions": [
        {
          "decider": "same_shard",
          "decision": "NO",
          "explanation": "shard cannot be allocated on same node [3OedVZN9QVKU9Hw7tn2h2w] it already exists on"
        },
        {
          "decider": "filter",
          "decision": "YES",
          "explanation": "node passes include/exclude/require filters"
        },
        {
          "decider": "replica_after_primary_active",
          "decision": "YES",
          "explanation": "primary is already active"
        },
        {
          "decider": "throttling",
          "decision": "YES",
          "explanation": "below shard recovery limit of [4]"
        },
        {
          "decider": "enable",
          "decision": "YES",
          "explanation": "allocation disabling is ignored"
        },
        {
          "decider": "disable",
          "decision": "YES",
          "explanation": "allocation disabling is ignored"
        },
        {
          "decider": "awareness",
          "decision": "YES",
          "explanation": "no allocation awareness enabled"
        },
        {
          "decider": "shards_limit",
          "decision": "YES",
          "explanation": "total shard limit disabled: [-1] <= 0"
        },
        {
          "decider": "node_version",
          "decision": "YES",
          "explanation": "target node version [1.7.5] is same or newer than source node version [1.7.5]"
        },
        {
          "decider": "disk_threshold",
          "decision": "YES",
          "explanation": "only a single node is present"
        },
        {
          "decider": "snapshot_in_progress",
          "decision": "YES",
          "explanation": "shard not primary or relocation disabled"
        }
      ]
    }
  ]

I have a single node cluster and also attempted to adjust the number of replicas to 0 per another post I found, which did not resolve the issue.  Physically inspecting the file system also doesn't appear to have duplicates.  This started about a week ago, and as far as I know nothing major changed on the system.  I do think we hit a limit as I also had to adjust the fs filemax, but this issue is still not correct after multiple attempts to restart and re-index.

I have also enabled routing allocation.  My current _cluster/settings are:

{
  "acknowledged": true,
  "persistent": {},
  "transient": {
    "cluster": {
      "routing": {
        "allocation": {
          "enable": "true"
        }
      }
    }
  }
}

Running _cat/nodes?v only returns a single node as I would expect.  

_cat/allocation?v returns 20% free space:
shards disk.used disk.avail disk.total disk.percent host                               ip            node  
  5458   315.2gb     77.3gb    392.6gb           80 vcosdevlog01.[SNIPPED] [X.X.X.X] loggy  
  5574                                                                                               UNASSIGNED 

Any help would be greatly appreciated!

**Comment by patroqueeet** [comment]
+1

**Comment by DJRickyB** [comment]
Closing this 5-year-old issue as it applies to an EOL Elasticsearch version
