### ISSUE TITLE
installing plugin fails with java.net.MalformedURLException in ES 5.0 alpha 1

### ISSUE THREAD

**Issue by rtznprmpftl** [elastic/elasticsearch#17637]
Hello, i just deployed ES 5 alpha 1 on my test machine an ran into this error:

**Elasticsearch version**:

{
  "name" : "magrathea",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "5.0.0-alpha1",
    "build_hash" : "7d4ed5b",
    "build_date" : "2016-04-04T10:39:25.841Z",
    "build_snapshot" : false,
    "lucene_version" : "6.0.0"
  },
  "tagline" : "You Know, for Search"
}

**JVM version**:
[root@magrathea elasticsearch]# java -version
openjdk version "1.8.0_77"
OpenJDK Runtime Environment (build 1.8.0_77-b03)
OpenJDK 64-Bit Server VM (build 25.77-b03, mixed mode)

**OS version**:
[root@magrathea elasticsearch]# cat /etc/redhat-release 
Fedora release 23 (Twenty Three)

**Description of the problem including expected versus actual behavior**:
Plugin installation fails, the steps are taken from https://www.elastic.co/guide/en/elasticsearch/plugins/master/installation.html  

[root@magrathea elasticsearch]# bin/elasticsearch-plugin install lmenezes/elasticsearch-kopf
-> Downloading lmenezes/elasticsearch-kopf
Exception in thread "main" java.net.MalformedURLException: no protocol: lmenezes/elasticsearch-kopf
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:219)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:214)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:175)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:163)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.Command.main(Command.java:53)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:57)

**Comment by dadoonet** [comment]
Thank you for reporting.
We need to update the guide.

Note that from 5.0, site plugins are not supported anymore.

**Comment by clintongormley** [comment]
Closed in https://github.com/elastic/elasticsearch/commit/098b2e03b54054e1df53a47d33be6fc6e6f6e082

**Comment by rajasekaran07** [comment]
Still I am seeing this issue. 

I am using elasticsearch 5.1.1 and java 1.8

when i am trying to install license plugin i am getting below message.

root@treselle-VirtualBox:/usr/share/elasticsearch# bin/elasticsearch-plugin install https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/marvel-agent/2.4.4/marvel-agent-2.4.4.zip
-> Downloading https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/marvel-agent/2.4.4/marvel-agent-2.4.4.zip
[=================================================] 100%Â Â 
ERROR: `elasticsearch` directory is missing in the plugin zip

-Raja

**Comment by dadoonet** [comment]
@rajasekaran07 Ask questions on discuss.elastic.co.

Marvel 2.4.4 is not compatible with elasticsearch 5.x. Read about x-pack now.

**Comment by rajasekaran07** [comment]
@dadoonet thanks for your response may I know how to get access logs for my elasticsearch.

Regards,
Raja

**Comment by dadoonet** [comment]
@rajasekaran07 Ask questions on discuss.elastic.co.

**Comment by muthhus** [comment]
Hi dadoonet,  Would you please provide me a right direction to get the solution for the above issue rather just not support 5.x version9(i.e Note that from 5.0, site plugins are not supported anymore.). 

I am getting issue when i am installing plugin license ;;

/usr/share/elasticsearch# bin/elasticsearch-plugin install file:///usr/share/elasticsearch/license-2.4.6.zip 
-> Downloading file:///usr/share/elasticsearch/license-2.4.6.zip
[=================================================] 100%?? 
ERROR: `elasticsearch` directory is missing in the plugin zip

**Comment by dadoonet** [comment]
@muthhus Sure but not here. Please ask on discuss.elastic.co and provide all details about what you did, where did you download zip from...
