### ISSUE TITLE
Index not removed from the alias after snapshot restore.

### ISSUE THREAD

**Issue by JeffreyZZ** [elastic/elasticsearch#17635]
Elasticsearch version : 1.7.2

1. Create two cluster : A and B
2. Add index i1 in A
3. Add an alias i for i1 in A
4. Then take a full snapshot of A with default settings 
5. Add index i1 and index i2 in B
6. Add an alias i for both i1 and i2 in B
7. Delete i1 and i2 in B
8. Restore the snapshot of A in B with default settings

**Expected **
Alias i should only contain i1 in B after restore.

**Actual  **
Alias i contains i1 and i2 in B, even though i2 didn't exist in B.

**Comment by clintongormley** [comment]
Hi @JeffreyZZ 

I've tried this out and am unable to replicate this, which makes sense given that aliases are stored per index.  So if `i2` existed in B after the restore, then the index i2 must either be in the snapshot or in the cluster (or imported as a dangling index from a node joining later).

Here's what I did:

On cluster A:

    DELETE *
    
    PUT i1
    
    PUT i1/_alias/i
    
    PUT /_snapshot/my_backup
    {
      "type": "fs",
      "settings": {
        "location": "/Users/clinton/workspace/servers/foo/"
      }
    }
    
    PUT /_snapshot/my_backup/snapshot_1?wait_for_completion=true
    
On cluster B:

    
    PUT i1
    
    PUT i2
    
    PUT i1,i2/_alias/i
    
    GET _alias
    
    DELETE i1,i2
    
    PUT /_snapshot/my_backup
    {
      "type": "fs",
      "settings": {
        "location": "/Users/clinton/workspace/servers/foo/"
      }
    }
    
    POST /_snapshot/my_backup/snapshot_1/_restore
    
    GET _alias
    
this returns: 

    {
      "i1": {
        "aliases": {
          "i": {}
        }
      }
    }

**Comment by clintongormley** [comment]
Feel free to reopen if you can come up with a recreation

**Comment by JeffreyZZ** [comment]
Sorry. For Step 7, instead of deleting the i1 and i2 in B, please close i1 and i2 in B. 

7. Close i1 and i2 in B

**Comment by clintongormley** [comment]
Hi @JeffreyZZ 

This is expected.  index i2 is not removed during the restore process, and aliases are stored in the index metadata, so alias `i` ends up pointing to the existing `i2` and the newly restored `i1`
