### ISSUE TITLE
Inconsistent dynamic default depending on how a field gets added

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#17644]
**Elasticsearch version**:
1.x, 2.x and master

**Description of the problem including expected versus actual behavior**:
Create an index and specify `dynamic: false` (or `strict`) for the only type it holds. Create a subfield of type object and specify `dynamic: true` for it. When creating a new object field under the dynamic one, it gets a different dynamic default depending on whether it was added via put mapping api (apparently taken from the main dynamic behaviour of the type) or dynamically created through index api (`true`, maybe ok because it was created dynamically). I would expect the new field to get the same default regardless of how it got added in the first place. I am not sure if its default value should be taken from the type of from its ancestor field.

**Steps to reproduce**:

- Create the index

```
curl -XPUT localhost:9200/index1 -d '{
    "mappings": {
      "strict_type": {
        "dynamic": "strict",
        "properties": {
          "dynamic_field": {
            "dynamic": "true",
            "type": "object"
          }
        }
      }
    }
}'
```

- Add a new field under `dynamic_field` using the put mapping api:

```
curl -XPOST localhost:9200/index1/strict_type/_mapping -d '{
    "properties": {
        "dynamic_field": {
            "properties": {
                  "subobject": {
                    "type" : "object"
                  }
            }
        }
    }
}
'
```

- Retrieve the mapping and verify that `subobject` gets the default dynamic behaviour of the type.

```
curl localhost:9200/_mapping?pretty

{
  "index1" : {
    "mappings" : {
      "strict_type" : {
        "dynamic" : "strict",
        "properties" : {
          "dynamic_field" : {
            "dynamic" : "true",
            "properties" : {
              "subobject" : {
                "type" : "object"
              }
            }
          }
        }
      }
    }
  }
}
```

- Also try and index a document with a new field under `subobject`, it gets rejected due strict mapping:

```
curl -XPUT localhost:9200/index1/strict_type/1 -d '{
	"dynamic_field" : {
	    "subobject" : {
              "field2" : 123 
	    }
	}
}
'

{"error":"StrictDynamicMappingException[mapping set to strict, dynamic introduction of [field2] within [dynamic_field.subobject] is not allowed]","status":400}
```

- Index a new document containing a new subobject field under `dynamic_field`:

```
curl -XPUT localhost:9200/index1/strict_type/1 -d '{
	"dynamic_field" : {
	    "subobject2" : {
	    }
	}
}
'
```

- Retrieve the mapping and verify that `subobject2` has `dynamic` set to `true`, omitting its `dynamic` behaviour

```
curl localhost:9200/_mapping?pretty

{
  "index1" : {
    "mappings" : {
      "strict_type" : {
        "dynamic" : "strict",
        "properties" : {
          "dynamic_field" : {
            "dynamic" : "true",
            "properties" : {
              "subobject" : {
                "type" : "object"
              },
              "subobject2" : {
                "type" : "object",
                "dynamic" : "true"
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by jpountz** [comment]
I suspect this is done on purpose since 99% of the time, if you add a dynamic object to your mappings, you will have a field below it.

That said I agree it is confusing that the default depends on the root as opposed to the parent.

**Comment by clintongormley** [comment]
However the sub-object gets added, if `dynamic` is not explicitly specified at the sub-object level, it should inherit from its direct parent.

**Comment by clintongormley** [comment]
This raises another problem...  The `dynamic` setting is updatable.  If we update the setting for a parent, the children should inherit the new setting.  I think this will not work today as the inherited dynamic setting is resolved when the field is added.

**Comment by jpountz** [comment]
>  The dynamic setting is updatable. If we update the setting for a parent, the children should inherit the new setting. I think this will not work today as the inherited dynamic setting is resolved when the field is added.

I think that could work actually. The way that the dynamic setting is resolved is the following:
 1. if `dynamic` is set on the object, then use it
 2. otherwise if `dynamic` is set on the root object, then use it
 3. otherwise use the default which is `true`

So if we replace (2) with "otherwise recursively check if `dynamic` is set on the parent object, and use it" and dynamically add objects with `null` values for `dynamic` then things should work?

**Comment by javanna** [comment]
Just tested this on master, it is fixed. No inconsistency anymore depending on how the field gets added. We look at the parent and take the `dynamic` value from it. Closing.
