### ISSUE TITLE
[5.0.0~alpha1] package installed path

### ISSUE THREAD

**Issue by changsijay** [elastic/elasticsearch#17647]
**Elasticsearch version**:5.0.0~alpha1

**JVM version**:1.8.0_77-b03

**OS version**:ubuntu 14.04 64bits

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.dpkg -L elasticsearch | grep elasticsearch-plugin
 2.dpkg -L kibana | grep kibana-plugin
 3.dpkg -L logstash | grep logstash-plugin

**Provide logs (if relevant)**:

**Describe the feature**:
Refering to https://www.elastic.co/downloads/x-pack 
we can use `elasticsearch-plugin` and `kibana-plugin` to install x-pack.

I use `dpkg -i *.deb` to install ELK stack.
However these commands are installed in, `opt` and `/usr/share`, separately
Would it be better to install ELK stack in consistent path and link bin files to `/usr/bin`?
Moreover, the steps in https://www.elastic.co/downloads/x-pack seems only good for tar file users now.

**Comment by clintongormley** [comment]
Thanks for reporting a 5.0 bug!  I'm adding the [Pioneer Program](https://www.elastic.co/blog/elastic-pioneer-program) label to the issue to make you eligible for a gift pack.

> Would it be better to install ELK stack in consistent path and link bin files to /usr/bin?

Agreed - we should be consistent, and we have a separate internal issue to track this cross-stack.

> Moreover, the steps in https://www.elastic.co/downloads/x-pack seems only good for tar file users now.

Agreed - I'll open a ticket to get that page updated.

thanks

**Comment by clintongormley** [comment]
Issue opened - closing this one
