### ISSUE TITLE
Remove XGeoPointDistanceRangeQuery in favor of GeoPointDistanceSort

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#17658]
[LUCENE-7126](https://issues.apache.org/jira/browse/LUCENE-7126) removes XGeoPointDistanceRangeQuery due to its inability to support multi-valued points but ES still requires this Query. This issue will remove `XGeoPointDistanceRangeQuery` in favor of  `GeoPointDistanceSort`, from [LUCENE-7180](https://issues.apache.org/jira/browse/LUCENE-7180), with `searchAfter`.

**Comment by clintongormley** [comment]
@nknize is this still required?

**Comment by nknize** [comment]
This is no longer required. Closing as FAKENEWS
