### ISSUE TITLE
Remove phrase prefix query

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#17655]
I see several issues with this query:
 - It feels like the right way to run auto completion when in fact the completion suggester should be used instead.
 - It behaves non intuitively: for instance it seems reasonable to assume that "new y" would match more doruments than "new yo" but since the match prefix query only takes the first 50 (default) terms that start with `y` in the first case, it is quite likely that `york` is not part of these terms, so the first query will probably try to match on "new yacht" but not on "new york".

**Comment by nik9000** [comment]
> It behaves non intuitively:

this is why I don't like it.

**Comment by mattweber** [comment]
-1 this is really one of the only queries that do simple analyzed wildcards (not a fan of `query_string`).

Maybe replace with a  "match_span" query that generates spans from analyzed terms?  I personally would love a simple analyzed query that generates spans. Something like this (trailing wildcard) could easily be an ordered `span_near` with no slop and the last term and/or any wildcards being represented with a `span_multi`.

**Comment by clintongormley** [comment]
> It feels like the right way to run auto completion when in fact the completion suggester should be used instead.

The completion suggester has a very different purpose from `match_phrase_prefix`, which people use as a poor-man's autocomplete with phrases which can appear anywhere within a text field, not just the beginning.

I'm not a huge fan of the query, but it is really easy for the newbie to get going with it, without having to understand what analyzers and edge ngrams are and how to set them up etc.  Later, when the user knows more and wants to improve their search, they can move on to more complex setups.

If we had a simpler way to provide the auto-complete experience, I'd be for it but currently...

**Comment by jpountz** [comment]
Discussed in Fixit Friday: we agreed to keep it but will add a warning to the docs about the behaviour of this query discussed above.
