### ISSUE TITLE
Default value for a field

### ISSUE THREAD

**Issue by eskibars** [elastic/elasticsearch#17659]
**Describe the feature**:
Currently, we have null_value, which works fine as long as the value is declared to be null at index time.  The `set` processor overwrites values if they already exist.  It'd be nice to have the ability to have the ability to set a value in the missing case.  To me, it seems like it'd be nice to add to the ingest processors (perhaps a simple `no_override` field in `set`?) so we can have different defaults depending on the pipeline

Related to https://github.com/elastic/elasticsearch/issues/12998.  Has been requested on discuss as well a few times:
https://discuss.elastic.co/t/is-it-possible-to-index-a-default-value-when-a-document-property-is-undeclared/9849
https://discuss.elastic.co/t/setting-missing-field-to-default-value-based-on-a-master-template/39317
https://discuss.elastic.co/t/setting-a-default-value-for-missing-fields-during-indexing/45021
https://discuss.elastic.co/t/field-null-value-doesnt-seem-to-have-any-effect/22015

**Comment by clintongormley** [comment]
I can definitely see this being useful as an ingest processor.  Let's do it
/cc @talevy @martijnvg

**Comment by talevy** [comment]
@clintongormley, I can get on that. I think it would be nice as well.
