### ISSUE TITLE
ES 1.4.1 indexing with few errors when index can't be created

### ISSUE THREAD

**Issue by serj-p** [elastic/elasticsearch#17664]
Hello,

I experienced the following issue. I use file index templates. I moved file with synonyms to other directory and forgot to update the config, then I deleted the index and started indexing to a new index which should have been created. I expected that indexing process will fall down and no doc will be reported as indexed. Surprisingly only **part** of requests fallen down with error like this

       {
        'index': {
        '_id': '5660f26e5d47ea351743a6bc', '_index': 'contacts_v3.0__1', '_type': 'contact',
        'error': 'RemoteTransportException[[Sprite][inet[/10.0.102.142:9300]][indices:admin/create]]; nested: IndexCreationException[[contacts_v3.0__1] failed to create index]; nested: FailedToResolveConfigException[Failed to resolve config path [templates/synonym.txt], tried file path [templates/synonym.txt], path file [/etc/elasticsearch/templates/synonym.txt], and classpath]; ',
        'status': 500
        }
    }

I index in butches of 1k docs using bulk api of pyes lib. From 300000 indexed only 7000 were reported as failed.

**Comment by serj-p** [comment]
I've checked, ES responses with 200, so this is not lib problem

**Comment by clintongormley** [comment]
Hi @serj-p 

I've tested this out on 1.4.1 and, as expected, every entry in the bulk response reported the same exception.  (a 200 response is expected for the bulk API - you have to check the responses to the individual items to know whether they succeeded or not).

I suggest checking the successful responses to see what index they went to.

Either way, 1.4.1 is very old and we won't be doing any further releases of that branch.  If you do find something that looks like a bug, please could you try to confirm this in a more recent version.

thanks
