### ISSUE TITLE
Add rewrite phase to Aggregations

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#17676]
It would be useful to have a rewrite phase on aggregations so we can:
1. optimise an aggregation to make it run better (e.g. rewrite the `QueryBuilder`s in the filter/filters aggregation to enable better request caching)
2. Add syntactic sugar around aggregations (see https://github.com/elastic/elasticsearch/issues/17631 for an example)

We could add a rewrite method to `AggregationBuilder` which would be called from the `SearchSourceBuilder#rewrite` method.

**Comment by jpountz** [comment]
This looks like an easy win to me.
