### ISSUE TITLE
Allow opting out of strict JSON field names

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#17674]
Since https://github.com/elastic/elasticsearch/pull/15351, Elasticsearch will now throw an exception if field names are unquoted.  This will break a number of APIs for users who have documents without quotes around their field names.

We should add a setting to disable the requirement for strict quoting, and log to the deprecation logs when this setting is enabled.

**Comment by jpountz** [comment]
Since this code is statically configured, we might want to go with a system property rather than a setting.

**Comment by jasontedor** [comment]
> Since this code is statically configured, we might want to go with a system property rather than a setting.

Yeah, this is one of those rare cases when a system property is the best option. If #17675 gets in, it will be easy to ship with a commented out configuration of this property.

**Comment by kimchy** [comment]
we could also have a setting, and Bootstrap reads the setting and set the system property that is being read. I know it is a hack, but since it is something that we plan to remove down the road, it might be simplest.
