### ISSUE TITLE
Documentation - Glossary misunderstandings

### ISSUE THREAD

**Issue by khakulov** [elastic/elasticsearch#17673]
In official [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/glossary.html#glossary):

> **index**
> An index is like a database in a relational database. 

> **type**
> A type is like a table in a relational database.

I think, this definition is wrong. Because every type in elasticsearch index shares fields.
Since ES 2.0 an index is a big table and type is an restricted view of bit table. You cannot update field types or delete fields from table. You have to create new index(table) and reindex your index.

**Comment by clintongormley** [comment]
I've opened https://github.com/elastic/elasticsearch/pull/17704 - what do you think?
