### ISSUE TITLE
Switch registration to key first

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#17679]
We've been reworking registration of things (query, score function, other stuff) so you register a ParseField, a parser, and reader. Right now the order is `reader, parser, parseField`. It'd be more like a map if it were `parseField, reader, parser`. Should we do that?

**Comment by javanna** [comment]
++

**Comment by ldematte** [comment]
Yes, the order is odd, and nowadays you can probably refactor this quickly with Intellij. We are not going to do that thought cause we don't feel strongly about it, but if you do you are free to re-open or submit a PR.
