### ISSUE TITLE
Documentation is not informative

### ISSUE THREAD

**Issue by nasht00** [elastic/elasticsearch#17672]
I am trying to learn Elastic, and in many places the documentation does not explain anything.

Simple example: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-request-fielddata-fields.html

> Allows to return the field data representation of a field for each hit.

After reading this, I know absolutely nothing about what a "field data representation" is...

**Comment by jasontedor** [comment]
This is [covered](https://www.elastic.co/guide/en/elasticsearch/guide/current/fielddata-intro.html) in the [definitive guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/fielddata.html) and in the [reference docs](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/fielddata.html). Does that help?

**Comment by nasht00** [comment]
Yes thank you, that's better.

My suggestions:
- Add a link from that page (https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-request-fielddata-fields.html).
- Add an example of a result set. That's in general. When you give an example request, it is very useful to see an example response.

Thanks!
