### ISSUE TITLE
Proposal: make StreamInput#readNamedWriteable and StreamOutput#readNamedWriteable public

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#17682]
Now that we have NamedWriteable we keep finding things that had little implementations of it like `AllocationCommand`s and aggregation's streams. Each time we convert those to a named writeable we create new methods in StreamInput and StreamOutput to write those objects. The methods are really simple, like:
```java
    public SuggestionBuilder<?> readSuggestion() throws IOException {
        return readNamedWriteable(SuggestionBuilder.class);
    }
```

So, why do we make these methods rather than just use `readNamedWriteable` directly? I mean, now `readNamedWriteable` is protected so we **can't**. But why not just make it public?

The argument for keeping it protected is that it forces us to be intentional about each new named writable. You can't make a new type of NamedWriteable in a plugin because you'd have to modify StreamInput and StreamOutput.

The argument for making it public is that we can drop all of the `readFooBar` methods and StreamInput and StreamOutput no longer need to know about all of the classes that they are reading.

So let's discuss! Regardless of the outcome this issue will be closed by a PR - either one that makes the methods public or one that adds some javadoc summarizing the outcome of the conversation.

**Comment by javanna** [comment]
+1 on making the readNamedWriteable method public

**Comment by cbuescher** [comment]
+1 I think I already wanted to do this back when we added Shapes to the family ReadWriteable but was voted down at that point: https://github.com/elastic/elasticsearch/pull/16312. Might be worth considering the objections in that issue again though, but things might have changed since then.

**Comment by jpountz** [comment]
+1 I suspect we just did not foresee that we would end up wanting to serialize thatmany different classes.

**Comment by ywelsch** [comment]
(Repeating my comment from #17661 here):
+1 on removing these specialized methods and making write/readNamedWriteable public. We should  strive to modularize our code better.

**Comment by jpountz** [comment]
Discussed in FixitFriday and we agreed to make these methods public.

**Comment by nik9000** [comment]
Since no one else's grabbed this and I'm in the neighborhood.....
