### ISSUE TITLE
Create a random aggregation builder method for tests

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#17684]
This was originally a comment in SearchSourceBuilderTests that in #17622 we decided to have a separate issue for. This is it.
https://github.com/elastic/elasticsearch/blob/9567f154e6fe470b7a4fa34a1784db493cd4e55f/core/src/test/java/org/elasticsearch/search/builder/SearchSourceBuilderTests.java#L434

**Comment by cbuescher** [comment]
@colings86 I think we can close this, it's not really necessary to randomize everything in SearchSourceBuilderTests and we have ranomization for aggregation trees elsewhere I think. We already removed the commend linked here I think. Wdyt?

**Comment by colings86** [comment]
Agreed.
