### ISSUE TITLE
Grok processor documentation is incorrect or out of date

### ISSUE THREAD

**Issue by Bargs** [elastic/elasticsearch#17692]
The docs say the default grok patterns can be found in a file at `$ES_HOME/config/ingest/grok/patterns`, but I'm not seeing that file in the alpha1 distribution. This might be extra confusing if the user goes to add their own custom patterns and the directory doesn't exist.

**Comment by martijnvg** [comment]
@Bargs That should have been removed. Custom patterns can only be defined inside the processor under `pattern_definitions` setting.

**Comment by Bargs** [comment]
Thanks @martijnvg. I noticed there's one other mention of it too: https://github.com/elastic/elasticsearch/blame/0f00c14afc8428a2a72c0b766d2171029dc8f6e1/docs/reference/ingest/ingest-node.asciidoc#L917

**Comment by martijnvg** [comment]
@Bargs you're right! I removed that too: https://github.com/elastic/elasticsearch/commit/16fa3e546e172d3d194c2711654824d4851d69f8

**Comment by Bargs** [comment]
Thanks!
