### ISSUE TITLE
Dynamic setting of “cluster.routing.allocation.same_shard.host: true” is not working

### ISSUE THREAD

**Issue by anhlqn** [elastic/elasticsearch#17693]
**Elasticsearch version**: 2.3.0

**JVM version**: jre1.8.0_73

**OS version**: Windows Server 2012 R2

**Description of the problem including expected versus actual behavior**:
Update "cluster.routing.allocation.same_shard.host": "true" successfully in Sense, but when doing a GET cluster settings, the "cluster.routing.allocation.same_shard.host": "true" does not show up in either persistent or transient section, so I have no idea if the settings are working or not.
More details: https://discuss.elastic.co/t/dynamic-setting-of-cluster-routing-allocation-same-shard-host-true-is-not-working/45644
**Steps to reproduce**:
 1. curl -XPUT http://localhost:9200/_cluster/settings -d '{ "persistent" : {"cluster.routing.allocation.same_shard.host": "true"}}'
 2. curl -XGET http://localhost:9200/_cluster/settings

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by dakrone** [comment]
Hi @anhlqn,

The reason for this is that is `"cluster.routing.allocation.same_shard.host"` is not a dynamic setting, it needs to be set at startup time currently. The settings infrastructure in 5.0.0 will help with identifying settings like these

**Comment by anhlqn** [comment]
@dakrone does it mean I have to put the setting in elasticsearch.yml of all ES nodes including master and data?

**Comment by dakrone** [comment]
@anhlqn yes that's correct

**Comment by Sartner** [comment]
@dakrone 
Can I only update master node config and rolling restart (only the masters)?
Because restart all nodes will take a long time

Or how to do it with out restart?
