### ISSUE TITLE
InternalTestCluster.getRandomNodeAndClient is not random

### ISSUE THREAD

**Issue by bbrutman** [elastic/elasticsearch#17699]
**Elasticsearch version**: 2.2.1

**JVM version**: 1.7.0_25

**OS version**: OS X 10.9.5 (13F34)

**Description of the problem including expected versus actual behavior**:
Expected: `InternalTestCluster.getRandomNodeAndClient` randomise the `NodeAndClient`
Actual: `InternalTestCluster.getRandomNodeAndClient` is not random. When calling this method in a test the same `NodeAndClient` is returned (since the nodes are sorted and the last one is always the last one)

**Steps to reproduce**:
 1. Run an ESIntegTestCase test with few nodes
 2. Call `internalTestCluster.smartClient()` many times
 3. Always get the same `NodeAndClient`

**Comment by nik9000** [comment]
I just checked the code in master and 2.2 - the implementation looks a bit strange but I believe it should return a random entry from the list of nodes that satisfies the predicate. It picks a random number between 0 and the size of the list of nodes that pass the predicate and then walks the list. I haven't tried running it and checking the debugger but it sure looks random to me. Are you sure you are getting the same node when you have more than one node that matches the predicate?
