### ISSUE TITLE
Support Java 8's Streams API in Groovy restrictions

### ISSUE THREAD

**Issue by bsideup** [elastic/elasticsearch#17709]
Hi! 

Currently, the only one way to process collections in scripts is to use Groovy's extension methods for collections - but they are not lazy - each invocation will create an intermediate collection. This is where Java 8's Streams API might be very useful, but currently they fail because of java.util.Function usage + Collectors class is restricted. 

Would be great if these classes will be whitelisted by default!

Thanks

**Comment by jpountz** [comment]
@rmuir Do you have any opinions?

**Comment by rmuir** [comment]
Well i'd start with the use case. What kind of collection processing is being done in scripts that requires e.g. streams api? This does not sound efficient whatsoever to be doing per-document.

In general creating/processing collections per-doc just seems very trappy to me.  I think things should be organized so this is not necessary: hell, I think even arrays are trappy, e.g. why even whitelist Arrays.sort?

Separately, if the decision is made to just allow more horribly trappy performance here, fine, but be careful. Some of these APIs (like parallelStreams) try to create/interact with threads and stuff. That is never ok :)

**Comment by bsideup** [comment]
Hey @rmuir,

Generally: our use case - replace **existing**, **non-efficient** Groovy collection-based methods with Streams. That said, **existing** ones :)

Of course we know about performance and memory impact of such operations. But there are some rare cases where we really need to do scripted aggregations.

Also, we're not processing collections per-doc, we process them in combine and reduce scripts ( https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-scripted-metric-aggregation.html ). 

Even example from that page might be replaced:
`IntStream.of(_aggs).sum()`
instead of
`profit = 0; for (a in _aggs) { profit += a }; return profit`


in fact, for some heavy computations, even parallelStream will make sense, and actually will be faster than sequential processing. Of couse we will not use it everywhere, but parallelStream **was** designed to handle parallel computation of non-IO stuff.

**Comment by rmuir** [comment]
parallelstream is not an option for scripts. that is why i said it is never ok. you can whitelist it all you want: it will fail.

**Comment by jasontedor** [comment]
There's no difference between your two sums examples other than the brevity of the code but they have the same effect.

Regarding the parallel streams, I think what is missing from this conversation is that to execute in parallel, threads are needed. Those threads have to come from a fork-join pool. We aren't going to provide one, so they will come from the common fork-join pool but we aren't going to allow that either. This is what @rmuir was getting at.
