### ISSUE TITLE
IP range aggregation will not work anymore once points are integrated

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#17700]
The ip range aggregation uses the numeric representation of ip addresses to compute the ranges. However once points are integrated, ip addresses will be stored in doc values using a SORTED_SET (binary) representation. So we have two options:
 - remove the ip range aggregation and tell users to use filters aggregations instead
 - add support for range aggregations on SORTED_SET doc values

**Comment by clintongormley** [comment]
I've never heard of anybody using the ip range agg.  @rashidkpc I see that this is supported in kibana, but do you have any idea if it is actually used?

**Comment by rashidkpc** [comment]
It was asked for, so I assume someone needed it. I can certainly see its use it operations applications.

**Comment by jpountz** [comment]
Discussions on #17746 also suggest that we might want to implement it. This will also be useful for big integers.
