### ISSUE TITLE
Error installing elasticsearch plugin 

### ISSUE THREAD

**Issue by philipskokoh** [elastic/elasticsearch#17708]
**Elasticsearch version**: 5.0.0-alpha1

**JVM version**: 1.8.0_51

**OS version**: CentOS 6.6

**Description of the problem including expected versus actual behavior**:
I try to install elasticsearch plugin such as elasticsearch-head and elasticsearch-kopf. The example below occurs on both elasticsearch-head and elasticsearch-kopf.

I run `./bin/elasticsearch-plugin install mobz/elasticsearch-head`, and I got MalformedURLException: no protocol. It seems that elasticsearch-5.0.0-alpha1 asking for full URL.

If I supply another full URL to install: 
```./bin/elasticsearch-plugin install https://github.com/mobz/elasticsearch-head```
I got this error message:
```ERROR: `elasticsearch` directory is missing in the plugin zip```

Looks like there are some changes in the elasticsearch plugin module. Is this a bug or expected behavior? Does the package require specific folder or specific stuffs to be compatible to elasticsearch-5.0.0-alpha1?

Thanks!

**Comment by jasontedor** [comment]
Duplicates #17637.

**Comment by dadoonet** [comment]
Site plugins are not supported anymore. See https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_plugins.html#_site_plugins_removed

**Comment by bonzofenix** [comment]
Working link: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_plugins.html#_site_plugins_removed

**Comment by jasontedor** [comment]
That link will grow stale as new versions are released and current is incremented. A permanent link is https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_plugins.html#_site_plugins_removed

**Comment by UppalaPreetham** [comment]
I tried bin\elasticsearch.bat

giving me the fallowing error 
The system cannot find the path specified.

**Comment by Whally01** [comment]
**OS: Windows 10** 
With all of the version I have an error:
- `ERROR:Unknown plugin mobz/elasticsearch-head` (+:ver) 
OR if use
 - `bin> elasticsearch-plugin install https://github.com/mobz/elasticsearch-head `

`ERROR: elasticsearch directory is missing in the plugin zip`

**Comment by nik9000** [comment]
> Site plugins are not supported anymore.

**Comment by yao23** [comment]
the documentation states that this plugin is intended to be installed on ES 2.3.x, not on ES 5.x. It's a checkup BEFORE you upgrade to 5.x

https://github.com/elastic/elasticsearch-migration/issues/64

**Comment by jemacom** [comment]
I find a work around which is build the plugin locally into a zip file. Then push that file somwhere in your github. 
In order to installed you need the raw github url somthing like this ```https://raw.githubusercontent.com/*****.zip```.
You can get the raw link also by using [Rawgit](https://rawgit.com/) web site. 

* Run  ```bin/elasticsearch-plugin install https://raw.githubusercontent.com/*****.zip```

Hope this help some of you. 
Cheerrs !!
