### ISSUE TITLE
Terms aggregations parse failure for date and ip fields

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#17705]
The `include` clause on the `terms` and `significant_terms` aggregations has a parse failure for string values provided for date and ip field types.
Steps to reproduce:

	PUT test
	{
	   "settings": {
		  "number_of_replicas": 0,
		  "number_of_shards":1
	   },
	   "mappings": {
		  "test": {
					
			 "properties": {
				"stringField": {
				   "type": "string"
				},
				"dateTimeField": {
				   "type": "date",
					"format": "date_time"
				},
				"ipField": {
				   "type": "ip"
				}
			 }
		  }
	   }
	}

	POST test/test
	{"stringField":"bar","ipField":"192.168.1.0", "dateTimeField":"2016-04-11T14:02:39.593Z"}

	GET test/_search
	{
		"size":0,
	   "aggs": {
		  "this_works": {
			 "terms": {
				"field": "stringField",
				"include":["bar"]            
			 }
		  }
	   }
	}
	GET test/_search
	{
		"size":0,
	   "aggs": {
		  "this_does_not_work": {
			 "terms": {
				"field": "ipField",
				"include":["192.168.1.0"]
			
			 }
		  }
	   }
	}
	GET test/_search
	{
		"size":0,
	   "aggs": {
		  "this_does_not_work": {
			 "terms": {
				"field": "dateTimeField",
				"include":["2016-04-11T14:02:39.593Z"]
			
			 }
		  }
	   }
	}

The error returned is of the following type

	{
	   "error": {
		  "root_cause": [
			 {
				"type": "number_format_exception",
				"reason": "For input string: \"2016-04-11T14:02:39.593Z\""
			 }
		  ],
		  "type": "search_phase_execution_exception",
		  "reason": "all shards failed",
		  "phase": "query_fetch",
		  "grouped": true,
		  "failed_shards": [
			 {
				"shard": 0,
				"index": "test",
				"node": "Qz_UtnGzTOeYEDLeOgTQLw",
				"reason": {
				   "type": "number_format_exception",
				   "reason": "For input string: \"2016-04-11T14:02:39.593Z\""
				}
			 }
		  ]
	   },
	   "status": 400
	}

**Comment by markharwood** [comment]
As part of fixing this I've also discovered that the formatting of IP bucket keys for terms agg has changed in master. Previously we had a `key` value that was a long and a formatted 'key_as_string' - now we just have a single `key` value with an ugly encoding as can be seen in this screenshot:
![sense - a json aware interface to elasticsearch](https://cloud.githubusercontent.com/assets/170925/14748517/0d379772-08b2-11e6-8f35-35af68740675.jpg)
This is a side-effect of switching over to byte representations for IPV6 I expect and consequently the shift to StringTerms for the buckets.
I'm not sure how much of a problem the ugly `key` is is but I will add back a friendlier "key_as_string" addition for readable IP addresses.

**Comment by clintongormley** [comment]
@jpountz only ip address fields still return `key_as_string` but this seems to be missing for point fields.

**Comment by jpountz** [comment]
@clintongormley @markharwood I opened #18003.

**Comment by markharwood** [comment]
I started this work on formatting include/exclude agg criteria appropriately but it's in the same areas Adrien is currently fixing with formatting agg results appropriately in https://github.com/elastic/elasticsearch/pull/18003

So blocked on 18003 for now.
