### ISSUE TITLE
phrase prefix query returns different results when it is used in a query filter.

### ISSUE THREAD

**Issue by aliakb** [elastic/elasticsearch#17736]
**Elasticsearch version**: 1.3.2

**JVM version**: Java HotSpot(TM) 64-Bit Server VM (build 24.55-b03, mixed mode)

**OS version**: Ubuntu 12.04.5 LTS

**Description of the problem including expected versus actual behavior**: the same phrase prefix search returns different results depending on whether it is used in a query or in a query filter. We expect the same number of hits in both cases because the search condition is the same, although expressed in a different form.

**Steps to reproduce**:
1. `client.search index: my_index, search_type: 'count', body:{query:{match:{_all:{query:'construction document', type: :phrase_prefix}}}}`
2. `client.search index: my_index, search_type: 'count', body:{query:{filtered:{query:{match_all:{}},filter:{query:{match:{_all:{query:'construction document',type: :phrase_prefix}}}}}}}`

Expected: counts should match
Observed: counts do not match

**Comment by clintongormley** [comment]
Hi @aliakb 

I'm afraid you haven't given nearly enough information here.  I've tried to reproduce this and failed.  here's what I tried:

    DELETE *
    
    POST t/t/_bulk
    {"index": {}}
    {"text": "foo bar construction baz document"}
    {"index": {}}
    {"text": "foo bar construction document baz"}
    {"index": {}}
    {"text": "foo bar construction baz document"}
    {"index": {}}
    {"text": "foo bar construction document baz"}
    {"index": {}}
    {"text": "foo bar construction baz document"}
    {"index": {}}
    {"text": "foo bar construction document baz"}
    {"index": {}}
    {"text": "foo bar construction baz document"}
    {"index": {}}
    {"text": "foo bar construction document baz"}
    {"index": {}}
    {"text": "foo bar construction baz document"}
    {"index": {}}
    {"text": "foo bar construction document baz"}
    {"index": {}}
    {"text": "foo bar construction baz document"}
    {"index": {}}
    {"text": "foo bar construction document baz"}
    
    GET _search?search_type=count
    {
      "query": {
        "match": {
          "_all": {
            "query": "construction document",
            "type": "phrase_prefix"
          }
        }
      }
    }
    
    GET _search?search_type=count
    {
      "query": {
        "filtered": {
          "query": {
            "match_all": {}
          },
          "filter": {
            "query": {
              "match": {
                "_all": {
                  "query": "construction document",
                  "type": "phrase_prefix"
                }
              }
            }
          }
        }
      }
    }

Both queries produce the same results.  I don't know which of your queries is correct and which incorrect, if you get consistent results when running the queries multiples times (maybe you're seeing a different number of docs on different shards?), etc.

Also, 1.3.2 is really old and won't be seeing any further releases.  I'm going to close this ticket, but if you manage to recreate the problem on a newer version, please open a new issue with the recreation

thanks
