### ISSUE TITLE
Use `µs` as unit for microseconds instead of `micros`

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#17755]
Use `µs` (or `mu`) as unit for microseconds instead of `micros`

**Comment by nik9000** [comment]
I'm worried `µs` will break some consoles and these units are all over the _cat APIs.

**Comment by BobChao87** [comment]
To be clear, the suggestion is `µs` or `mus`, or is it `µs` or `mu`. Because I would find `mu` very confusing. It is not uncommon for the use of `us` in situation where the µ character isn't readily available.

**Comment by nik9000** [comment]
> `us`

I'd prefer that by default. 2016 or not, _cat API shouldn't depend on you having a decent font.

**Comment by dadoonet** [comment]
We decided to close this issue as it does not bring really value and might be more confusing for users.
It would also be a non needed breaking change.
