### ISSUE TITLE
Groovy Module's IndicesRequestTests.testSuggest fails on Windows

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#17806]
There are several test failures for `org.elasticsearch.messy.tests.IndicesRequestTests.testSuggest` that seem specific to Windows on 2.x, for example: http://build-us-00.elastic.co/job/es_core_2x_window-2008/853/

Reproduces With:
`mvn test -Pdev -pl org.elasticsearch.module:lang-groovy -Dtests.seed=307485C36A7BB178 -Dtests.class=org.elasticsearch.messy.tests.IndicesRequestTests -Dtests.method="testSuggest" -Des.logger.level=DEBUG -Dtests.nightly=false -Dtests.client.ratio=0.0 -Dtests.heap.size=512m -Des.node.mode=network -Dtests.jvm.argline="-server -XX:+UseParallelGC -XX:-UseCompressedOops -Djava.net.preferIPv4Stack=true" -Dtests.locale=lv-LV -Dtests.timezone=Etc/GMT-9`

**Comment by rjernst** [comment]
Groovy is removed in master, and this test has been refactored in 5.x.
