### ISSUE TITLE
Elasticsearch scoring

### ISSUE THREAD

**Issue by rfyiamcool** [elastic/elasticsearch#17809]
I'm using elasticsearch to find similar documents to a given document using the "more like this" query.

Is there an easy way to get the elasticsearch scoring between 0 and 1 (using cosine similarity) ?

Thanks!

**Comment by clintongormley** [comment]
Hi @rfyiamcool 

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by olalonde** [comment]
@rfyiamcool wondering the same here... did you figure this out?
