### ISSUE TITLE
Lucene dependency can't be automatically downloaded in maven

### ISSUE THREAD

**Issue by lijuan8** [elastic/elasticsearch#17803]
**Elasticsearch version**: 5.0.0-alpha1

**JVM version**: 1.8.0_65-b17

**OS version**: OS X Yosemite 10.10.5 (14F1605)

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. in my pom.xml, I included elasticsearch 5.0.0. alpha-1: 
               <dependency>
			<groupId>org.elasticsearch</groupId>
			<artifactId>elasticsearch</artifactId>
			<version>5.0.0-alpha1</version>
		</dependency>
 2. when I do a maven build, I got the following error:

[ERROR] Failed to execute goal on project pdfprototype: Could not resolve dependencies for project com.tina.index:pdfprototype:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.apache.lucene:lucene-core:jar:6.0.0-snapshot-f0aa4fc, org.apache.lucene:lucene-join:jar:6.0.0-snapshot-f0aa4fc, org.apache.lucene:lucene-queryparser:jar:6.0.0-snapshot-f0aa4fc, org.apache.lucene:lucene-misc:jar:6.0.0-snapshot-f0aa4fc, org.apache.lucene:lucene-highlighter:jar:6.0.0-snapshot-f0aa4fc, org.apache.lucene:lucene-sandbox:jar:6.0.0-snapshot-f0aa4fc, org.apache.lucene:lucene-spatial3d:jar:6.0.0-snapshot-f0aa4fc, org.apache.lucene:lucene-backward-codecs:jar:6.0.0-snapshot-f0aa4fc, org.apache.lucene:lucene-spatial-extras:jar:6.0.0-snapshot-f0aa4fc, org.apache.lucene:lucene-grouping:jar:6.0.0-snapshot-f0aa4fc, org.apache.lucene:lucene-analyzers-common:jar:6.0.0-snapshot-f0aa4fc, org.apache.lucene:lucene-memory:jar:6.0.0-snapshot-f0aa4fc, org.apache.lucene:lucene-queries:jar:6.0.0-snapshot-f0aa4fc, org.apache.lucene:lucene-spatial:jar:6.0.0-snapshot-f0aa4fc, org.apache.lucene:lucene-suggest:jar:6.0.0-snapshot-f0aa4fc: Failure to find org.apache.lucene:lucene-core:jar:6.0.0-snapshot-f0aa4fc in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

I have to manually add all the lucene library into my pom file to get rid of this compiling error. 
 3.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
You need to add a repository, something like this:

```xml
<repositories>
    <repository>
        <id>Lucene snapshots</id>
        <url>https://download.elasticsearch.org/lucenesnapshots/f0aa4fc</url>
    </repository>
</repositories>
```

**Comment by lijuan8** [comment]
thanks!

**Comment by jasontedor** [comment]
> thanks!

You are most welcome.
