### ISSUE TITLE
Dis Min Query

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#17820]
Elasticsearch query DSL has Dis Max query https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-dis-max-query.html

We could also use a "Dis Min query", as for some specialized scoring scenarios we are interested in giving the query the score of the lowest scoring sub-query. Yup.

As always, will be happy to send a PR with this addition.

**Comment by clintongormley** [comment]
Hi @synhershko 

Could you expand on why a dis-min query would be useful?

**Comment by david206** [comment]
Hi @clintongormley 

I am using boosting-query as one of the sub-queries, and in case there is a match on the boosting-query I want to return its score as the query score - the other sub-queries have different logic which is score i want to get if the boosting query doesn't match.

**Comment by clintongormley** [comment]
Hi @david206 

From your description, it doesn't sound like `dis_min` will do what you want.  It'll return the lowest score from whichever clause, it won't just choose the score from the boosting query if it has matches.

I'm still not seeing the use case for `dis_min`.

**Comment by synhershko** [comment]
@clintongormley correct, the lowest score from whichever clause is exactly what we are after. We build our queries in a way that will make the boosting query the lowest scoring bit.

**Comment by clintongormley** [comment]
@synhershko this seems awfully use-case specific.  I'm struggling to understand how this would be generically useful.

**Comment by jpountz** [comment]
Discussed in Fixit Friday. This feels too specific indeed. Closing in favour of the more generic #17116.

**Comment by synhershko** [comment]
Sounds good (albeit more complicated than just a dis_min, which essentially shared the same code as dis_max but with a polarity change).

One question though - IIRC dis_max has some performance gains associated with it in terms of parallel execution and query termination. If that indeed is the case - would function score query benefit from the same?
