### ISSUE TITLE
Inconsistency with index time between _stats api and the _bulk respone api

### ISSUE THREAD

**Issue by SKumarMN** [elastic/elasticsearch#17842]
When I do a bulk indexing and look at the return response, the "took" attribute in the response I believe is the time taken to index the given set of documents. The "took" time doesn't match the index time in _stats api

Below is a sample response and _stats api data for it
_bulk response
{
### took: 67,
  errors: false,
  items: [..]
}

_stats api

indexing: {
index_total: 10,
**index_time_in_millis: 220**,
index_current: 0,
delete_total: 0,
delete_time_in_millis: 0,
delete_current: 0,
noop_update_total: 0,
is_throttled: false,
throttle_time_in_millis: 0
}

**Elasticsearch version**: 2.0.2

**JVM version**:1.8

**OS version**: Windows 7

**Comment by clintongormley** [comment]
The `took` time measures how long the request took.  The index time measures how much time was spent in indexing threads. Threads can execute in parallel, so two threads in parallel which take 10ms each would result in 20ms of indexing time.

**Comment by SKumarMN** [comment]
@clintongormley  Thanks. How to find out the exact time of indexing activity. We are interested in finding the exact time taken for indexing millions of documents we have. Based on this we want to see how we can fine tune any indexing params

**Comment by danielmitterdorfer** [comment]
@SKumarMN I am not sure what you mean by "exact time". There are two possibilities:

* You want to know how many documents / second you can index, meaning you are interested in throughput. Then you should look at "took" (although this is only the time spent in request processing in ES. It does not and cannot include the time for the whole roundtrip. For that you have to measure on the client).
* You want to know how much time Elasticsearch spends during indexing in total (this is *not* Wall clock time but a sum of the time spend in all indexing threads as explained by @clintongormley earlier). Then you need to look at `index_time_in_millis`

**Comment by SKumarMN** [comment]
@danielmitterdorfer thanks for your response. If I want to find out the wall clock time then I need to consider "took" + "round trip" at client side right ? Using stats API is there a way to get it after certain time period? . Also how do we measure if the indexing is optimal in our cluster . Do I need to concentrate on index rate number of docs/index_time_in_millis ?

**Comment by danielmitterdorfer** [comment]
@SKumarMN The "+" sign is implying that you want to sum up these values. "took" is the time it took Elasticsearch to process your request. The round trip time is something you have to measure yourself (Elasticsearch cannot know this time). You basically need to start a timer, when you issue the request and stop it when you get the response. The difference is the round trip time.

The stats API just tells you the total indexing time but not Wall clock time AFAIK.

The [Indexing Performance Tips](https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-performance.html) section of the Elasticsearch Definitive Guide should get you started on measuring. You should concentrate on the documents / second that you can add to the index. I think that [Rally](https://github.com/elastic/rally) could also help you if you don't have the necessary test infrastructure yet. But keep the following caveats in mind:

* You need a Unix machine for Rally (I see you mention Windows 7 in the ticket). It's ok to benchmark a Windows machine though
* You need to add your own benchmark data to Rally. It's doable but I work on simplifying this over the coming weeks.
* You want to vary the bulk request size. That is also doable but also not well supported currently.
