### ISSUE TITLE
Script_sort using "_score" alone is not valid

### ISSUE THREAD

**Issue by 4onni** [elastic/elasticsearch#17847]
**Elasticsearch version 2.3.1**:

**JVM version 1.8.0_65**:

**OS version CentOS 6.5**:

**Steps to reproduce**:
1. Using only _score variables
 ```json
"sort": [
    {
      "_script": {
        "script": {
          "inline": "_score"
        },
        "type": "number",
        "reverse": true
      }
    }
  ]
```
result : 
```json
"_score": null,
"_source": { },
"sort": [
     0
],
```

2.Using _score variables and score-sort
```json 
"sort": [
    {
      "_script": {
        "script": {
          "inline": "_score"
        },
        "type": "number",
        "reverse": true
      }
    },
    "_score"
  ]
```
result:
```json
"_score": 1.6844505,
"_source": { },
"sort": [
          1.6844505071640015,
          1.6844505
]
```

**Comment by clintongormley** [comment]
Scores are not calculated unless they're actually going to be used.  Your first example doesn't explicitly use scores, so score calculation is disabled.  You can force the score to be calculated anyway by adding `?track_scores` to your search request.

The question is: can we detect that `_score` is being used inside the script automatically?

**Comment by 4onni** [comment]
Thanks for your reply, adding  `track_scores` has been solved. What I don't understand is how to use it explicitly. Is "_score + 1" this way? Through my experiments, I still can't do it. For example:
```json
"sort": [
    {
      "_script": {
        "script": {
          "inline": "_score + 1"
        },
        "type": "number",
        "reverse": true
      }
    }
  ]
```
result:
```json
"_score": null,
        "_source": { },
        "sort": [
          1
        ],
```

**Comment by clintongormley** [comment]
> What I don't understand is how to use it explicitly. Is "_score + 1" this way?

No.  Scripts don't count.  Your original example showed how to use it explicitly: by sorting by `_score`.

**Comment by 4onni** [comment]
Thank you, I understand.
