### ISSUE TITLE
Appending object to an existing array of objects

### ISSUE THREAD

**Issue by sachinbrraj** [elastic/elasticsearch#17850]
**Elasticsearch version**:2.2.1

**JVM version**: 7

**OS version**: CentOS 6.5

**Description of the problem including expected versus actual behavior**: I am trying to append a new object to an existing array of objects, but instead of appending, the whole array is replaced with the new value.

    POST temp1
    {
      "mappings": {
        "conv": {
          "properties": {
            "name": {
              "type": "string"
            },
            "participants": {
              "type": "nested",
              "properties": {
                "name": {
                  "type": "string"
                },
                "nick": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }

    POST /temp/conv/1/_update
    {
      "script": "ctx._source.participants += new_creator",
      "params": {
        "type": "object",
        "new_creator": [
          {
            "name": "a",
            "nick": "nick-c"
          }
        ]
      }
    }
    
Could you pls let me know whether this is a bug or am I doing it wrongly?

**Comment by clintongormley** [comment]
This works just fine, as long as the original document (which you didn't provide) already has an array for `participants`:

    PUT temp/conv/1
    {
      "participants": [
        {
          "name": "a",
          "nick": "nick-a"
        }
      ]
    }
    
    POST /temp/conv/1/_update
    {
      "script": "ctx._source.participants += new_creator",
      "params": {
        "type": "object",
        "new_creator": {
          "name": "b",
          "nick": "nick-b"
        }
      }
    }
    
    GET /temp/conv/1
