### ISSUE TITLE
Query in upgrading from 1.7.1 to 2.3.1version of ElasticSearch

### ISSUE THREAD

**Issue by kannansamp** [elastic/elasticsearch#17869]
Currently we are using ElasticSearch 1.7.1, we have planned to upgrade to 2.3.1 and we have done all of the steps as mentioned in the ES 2.3.1 upgrading help documentations.

After we initiated the upgrade, 2.3.1 cluster started and nodes are connected properly, but pending_tasks are increasing consistently. It took more than 4 hours, but still pending_tasks are increasing and those tasks are refresh-mapping [index] fyi. 

If anyone done the upgrade to 2.3.1or 2.x versions then can anyone please share your experience about this? Its an usual behaviour?

**Comment by eskibars** [comment]
It looks like you opened this up over at https://discuss.elastic.co/t/query-in-upgrading-from-1-7-1-to-2-3-1version-of-elasticsearch/47831 which seems like a better place for this troubleshooting.  I'm going to close here for now.  If that discuss thread points to a real bug in ES, then we can reopen here.
