### ISSUE TITLE
Disable Disk Allocation Watermarks On Localhost Binding

### ISSUE THREAD

**Issue by NathanZamecnik** [elastic/elasticsearch#17867]
**Describe the feature**:  Would it be possible to turn off watermarks for nodes that are bound to localhost?  I ask because some users download Elasticsearch and can't get things going because their disk doesn't have much space left.  Many may not realize they need to change this setting and may get frustrated early on.

**Comment by dakrone** [comment]
@NathanZamecnik they are already ignored when there is only a single data node, are you running into situations where this is problematic?

**Comment by NathanZamecnik** [comment]
In the Ops course we have students set up 3 nodes and some of them run into this issue.  Honestly, it may be good they do as they should understand this setting and what to do about it.

I didn't realize a single node ignores it already - I'd say that's good enough.

**Comment by dakrone** [comment]
Cool, will close this then, we can always re-open!
