### ISSUE TITLE
Update arithmetic script save result as string when field is mapped as double

### ISSUE THREAD

**Issue by joseantonomh** [elastic/elasticsearch#17860]
**Elasticsearch version**: 2.2.1

**JVM version**: 1.8.0.45

**OS version**: Windows 7 Ultimate SP1

**Description of the problem including expected versus actual behavior**:

A field mapped as "double", can accept numbers as number or as strings. This creates some problems when I retrieve the documents by using the NEST CLIENT.

But NEST is not the issue here.

When I execute a scripted update, which makes a arithmetic operation, explodes when the value to read from Elastic is a string.

The original value is in ES is a number and we execute the update, the result is written as String. Then,  when I execute it again, crashes because cannot perform arithmetic operations over a string.

I would expect that in ES a number is always represented as a number, not as string.

**Steps to reproduce**:
 1- Create index with mappings:

`
PUT index1 
{ "mappings": { "Report": { "properties": { "workingTime": { "type": "double" } } } } }
`

 2- Create demo document:

`POST index1/Report/1
{
    "workingTime": 9996
  }`

 3- Update the document

`
POST index1/Report/1/_update
{
  "script": {
      "inline": "ctx._source.workingTime = ctx._source.workingTime/1000"    
  }
}
`

 4- Update (again) the document

`
POST index1/Report/1/_update
{
  "script": {
      "inline": "ctx._source.workingTime = ctx._source.workingTime/1000"
      }
}
`

5- Illegal argument exception comes

`
{
   "error": {
      "root_cause": [
         {
            "type": "remote_transport_exception",
            "reason": "[Yeti][127.0.0.1:9300][indices:data/write/update[s]]"
         }
      ],
      "type": "illegal_argument_exception",
      "reason": "failed to execute script",
      "caused_by": {
         "type": "script_exception",
         "reason": "failed to run inline script [ctx._source.workingTime = ctx._source.workingTime/1000] using lang [groovy]",
         "caused_by": {
            "type": "missing_method_exception",
            "reason": "No signature of method: java.lang.String.div() is applicable for argument types: (java.lang.Integer) values: [1000]\nPossible solutions: is(java.lang.Object), drop(int), wait(), trim(), any(), size()"
         }
      }
   },
   "status": 400
}
`

6- (extra) 

When we use as document

`POST index1/Report/1
{
    "workingTime": 999.6
  }
`

, the problem does not happen.

**Provide logs (if relevant)**:

**Describe the feature**:

Mapping Issues / Scripting issues

**Comment by clintongormley** [comment]
That's because Groovy uses BigDecimal, which gets serialised as a string.  Cast it to a `double` instead:

    "inline": "ctx._source.workingTime = (double) ctx._source.workingTime/1000"

**Comment by joseantonomh** [comment]
Thanks, that worked out! :)

**Comment by nik9000** [comment]
> That's because Groovy uses BigDecimal, which gets serialised as a string.

It is nice that there is a workaround but this is kind of lame. I'm fine with living with the work around if we're sure that painless is better? I suspect it is.

**Comment by clintongormley** [comment]
> It is nice that there is a workaround but this is kind of lame. I'm fine with living with the work around if we're sure that painless is better? I suspect it is.

Well, in this example, `9996/1000` in painless returns the integer `9`.  You still have to use casting to get it to return a float.  Perhaps later we can use the field mapping to cast automatically /cc @jdconrad
