### ISSUE TITLE
How many disks are used by one shard?

### ISSUE THREAD

**Issue by zhuqunzhou** [elastic/elasticsearch#17884]
[question1](http://stackoverflow.com/questions/36737023/elasticsearchhow-to-make-a-balance-of-the-usage-of-disk?noredirect=1#comment61059094_36737023) tells me: the shards' files are all allocated on one path only and not spread on all paths. And ES will not try to balance the files between paths.

[question2](http://stackoverflow.com/questions/36709408/elasticsearchper-shard-per-node-vs-multiple-shards-per-node) tells me:if you define more than one location (one per disk for example) it will use both disks and will benefit from the increased IOPS.

I am confused..

I just want to make the usage of the disk are almost equal.

**Comment by jpountz** [comment]
Please ask at https://discuss.elastic.co. We use these github issues for bugs and feature requests only.
