### ISSUE TITLE
Migrate facet from 1.x to aggregation 2.x

### ISSUE THREAD

**Issue by nikoncode** [elastic/elasticsearch#17888]
I have a custom facet implementation: *InternalFacet, *Builder, *Executor and *Parser classes.
What are equivalent of this classes I should use to migrate my facet to aggregation?

**Comment by clintongormley** [comment]
Hi @nikoncode 

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
