### ISSUE TITLE
**dynamic false** doesn't ignore the new fields

### ISSUE THREAD

**Issue by cnwarden** [elastic/elasticsearch#17880]
**Elasticsearch version**:1.7.3

**JVM version**:1.7.0_45

**OS version**:Oracle Linux Server release 7.1

**Description of the problem including expected versus actual behavior**:
**dynamic false** doesn't ignore the new fields

**Steps to reproduce**:
 1.
`PUT _template/mytest
{
    "template": "std_content*", 
    "settings": {
        "number_of_shards": "1",
        "number_of_replicas": "0",
        "refresh_interval": "10s"
    },
    "mappings": {
        "comment":{
            "dynamic": "false",
            "properties": {
                "author":{
                    "properties":{
                        "user_id":{
                            "type": "long"
                        },
                        "screen_name":{
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`
 2.
`PUT std_content_2016-4`
 3.
`POST std_content_2016-4/xueqiu/1
{
    "author":{
        "screen_name": "999999",
        "should_be_ignored":"no"
    }
}`

I expect ignoring the field "test", but it created document. if with "dynamic=strict", it throws exception, it works as expectation.
**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jpountz** [comment]
How did you check that the field is not ignored?

**Comment by colings86** [comment]
In your example above your mappings are for the type `comment` but the document you add has the type `xueqiu`. If I replace the type in the template with `xueqiu` the fields should be ignored
