### ISSUE TITLE
regression: cannot index dates with a year >= 10000

### ISSUE THREAD

**Issue by drallax** [elastic/elasticsearch#17887]
**Elasticsearch version**: 2.3.1
**JVM version**: JDK 7, JDK 8
**OS version**: linux

**Description of the problem including expected versus actual behavior**:
when indexing a document with a date field and the date is after the year 10000,
the index operation fails with the following exception:

MapperParsingException[failed to parse [document/datefield]]; nested: IllegalArgumentException[Invalid format: "28910-05-16T19:52:39.000Z" is malformed at "0-05-16T19:52:39.000Z"];

The error does not occur with ES 1.7.2 or earlier

**Steps to reproduce**:
1. use the java api
2. assign a java.util.Date after the year 10,000 to a document's field of type "date"
3. index the document

**Cause**:
I believe the issue is with StrictISODateTimeFormat, which seems to be an edited copy of joda's ISODateTimeFormat.
as the following unit test demonstrates:

```
    @Test
    public void testLargeDate() {
        final DateTimeFormatter joda = StrictISODateTimeFormat.dateOptionalTimeParser();
        assertEquals(9999, joda.parseLocalDate("9999-01-02T03:04:05").year().get());
        assertEquals(10000, joda.parseLocalDate("10000-01-02T03:04:05").year().get()); //BROKEN
    }
```

the second assert fails with the same exception as when indexing a document with a date after the year 10,000.
When using joda's ISODateTimeFormat instead of ES's StrictISODateTimeFormat, the test works correctly.

**Provide logs (if relevant)**:
MapperParsingException[failed to parse [document/datefield]]; nested: IllegalArgumentException[Invalid format: "28910-05-16T19:52:39.000Z" is malformed at "0-05-16T19:52:39.000Z"];

**Comment by clintongormley** [comment]
Yes - the strict date format was mostly added to improve dynamic date detection.  Why not just set the date format on your field to `date_optional_time` instead of `strict_date_optional_time`?

**Comment by drallax** [comment]
actually we define all our date fields without an explicit format, just using the default, which turns out to be `strict_date_optional_time` as seen here:
```
public class DateFieldMapper extends NumberFieldMapper {
    ...
    public static class Defaults extends NumberFieldMapper.Defaults {
        public static final FormatDateTimeFormatter DATE_TIME_FORMATTER = Joda.forPattern("strict_date_optional_time||epoch_millis", Locale.ROOT);
```
where it used to be `date_optional_time` <ES-2.0

Also note that we're using the Java api here, and that we offer a java.util.Date, not some ISO string.
So it is surprising to see an error that complains about the textual representation of that Date as soon as the year exceeds 10,000

The javadoc on top of `StrictISODateTimeFormat` includes  the following quote:
```
 * However there has been done one huge modification in several methods, which forces the date
 * year to be at least n digits, so that a year like "5" is invalid and must be "0005"
```
which leads me to believe that the intention was to support at least 4 digits for a year, 
not exactly 4 digits, so failing to parse a year of 10,000 or greater seems to be an actual bug?

**Comment by buzzdeee** [comment]
not sure if I'm hitting the same issue, I use ES 2.3.1 as well as LS 2.3.1. In LS I use date filter like this:

```
                 date {
                   match => [ "timestamp", "MMM dd HH:mm:ss", "MMM d HH:mm:ss", "MMM  d HH:mm:ss" ]
                   add_tag => [ "dated" ]
                 }
```

for a couple of log files, mainly syslog like. 

When LS tries to output to ES I get in ES logs:

MapperParsingException[failed to parse [timestamp]]; nested: IllegalArgumentException[Invalid format: "Apr 20 23:52:35"];

Other dates, that contain a year, don't seem to be problematic.

Sebastian

**Comment by jpountz** [comment]
Closing in favour of #29014. @buzzdeee This is a different issue.
