### ISSUE TITLE
Nested Type in mapping does not work

### ISSUE THREAD

**Issue by qitang** [elastic/elasticsearch#17893]
Hi, 
 When I insert data into ES. I have this error:
 **Mapper for [restaurants] conflicts with existing mapping in other types[object mapping [restaurants] can't be changed from nested to non-nested]**

Here is the mapping I am using:

```javascript
{
  "couchbase": {
    "properties": {
      "id": {
        "type": "string",
        "index": "not_analyzed"
      },
      "start_time": {
        "type": "date",
        "format": "date_time"
      },
      "time_placed": {
        "type": "date",
        "format": "date_time"
      },
      "restaurants": {
        "type": "nested",
        "properties": {
          "id": {
            "type": "string",
            "index": "not_analyzed"
          },
          "name": {
            "type": "string"
          }
        }
      },
      "state": {
        "type": "string",
        "index": "not_analyzed"
      },
      "order_number": {
        "type": "string",
        "index": "not_analyzed"
      }
    }
  }
}
```
Thanks!

**Comment by clintongormley** [comment]
You're getting a mapping conflict because you're passing a `restaurants` field that isn't an object or an array of objects

**Comment by qitang** [comment]
@clintongormley 
this is the json I am using
```javascript
{
  "group_id": null,
  "payments": {
    "total": 1605,
    "payments": [
      {
        "id": "6954",
        "type": "CREDIT_CARD",
        "amount": 1605
      }
    ],
    "transactionId": null
  },
  "restaurants": [
    {
      "id": "296787",
      "name": "White Castle"
    }
  ],
  "state": "COMPLETED",
  "order_numbers": "900006749",
  "order_tracking": {
    "enabled": false,
    "type": null
  },
  "system_of_record": "bullrat",
  "group": false,
  "asap": true
}
```

**Comment by rjernst** [comment]
@qitang You have `restaurants` set as `nested` in your existing mappings. Based on the error, it sounds like you are dynamically creating a new type. We don't allow created nested types through dynamic mappings, so the dynamic code views `restaurants` in this new type as `object`, which conflicts with the other document type mapping.

/cc @jpountz

**Comment by relicmelex** [comment]
so with that in mind, what would have to change here to fix it? As I understand what you said, but I don't know how that effects these json blobs... @rjernst

**Comment by wangyuxiangnn** [comment]
thanks
