### ISSUE TITLE
Do we need custom allocation commands?

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#17894]
As part of #17802 we are taking into account the fact that a plugin could potentially plug in custom allocation commands. That has always been untested, hence got broken in master till it got fixed a few days ago as part of Nik's refactorings.

I now wonder if we should test this extension point so that we can claim we support it, or if we can instead simply remove it as it is not needed. Is there any custom allocation command out there? Anybody can think of why this extension point would be needed?

**Comment by javanna** [comment]
I did some digging and it looks like allocation commands were made pluggable as part of this commit: https://github.com/elastic/elasticsearch/commit/e530f03b9445e98728b5fbf203c57ab774928ff3 . @kimchy maybe you want to comment on this? ;)

**Comment by jpountz** [comment]
Discussed in Fixit Friday: we do not think that it should be possible to plug in custom allocation commands, but would like to hear @kimchy 's opinion before closing to make sure we did not miss anything.

**Comment by javanna** [comment]
I removed the discuss label as #17802 will remove the ability to plug in custom allocation commands when it gets in.
