### ISSUE TITLE
Move templates out of the search api to its own dedicated api.

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#17906]
At the moment mustache templating is baked into the search API. It would be cleaner to break this out of the search API and move its into its own search template API. This api would template any incoming request body and delegate to the search API. I believe this approach is much cleaner.

On the rest layer this can be done in a non breaking manner, since there is already a dedicated endpoint for it (`/_search/template`), which now delegates to the search API.

Also I think we can move this API to the `lang-mustache` module, since templating is hardcoded to use mustache anyway. If do this we can also move the other template related APIs to `lang-mustache` module.

**Comment by s1monw** [comment]
this is a great idea @martijnvg lets move it out in a module and fix the API part!!
