### ISSUE TITLE
Add ability to match one of many provided patterns to the grok processor.

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#17903]
**Describe the feature**:

Add ability to specify multiple grok patterns to match in the grok-processor.

example update to the grok-processor syntax:
```
{
  "grok" : {
    "field": "message",
    "patterns": [ "%{CISCOFW106001}", "%{CISCOFW106006_106007_106010}",  "%{CISCOFW106014}"]
  }
}
```

The first pattern in `patterns` that matches will be the one being used for that specific IngestDocument.

ref: https://discuss.elastic.co/t/multiple-grok-rules-in-ingest-node-processor-definition/47902

> ...
> In the ingest node, I was able to define a grok processor, but some log types need multiple grok rules (e.g. firewall logs). In Logstash, you'd simply specify an array of match definitions. If one matches, it the line is parsed, for example:

>   grok {
     match => [
      "cisco_message", "%{CISCOFW106001}",
      "cisco_message", "%{CISCOFW106006_106007_106010}",
      "cisco_message", "%{CISCOFW106014}"
   ...
For the ingest node, if a grok processor fails, it throws and exception. So the only way I could find to add in multiple rules is to chain multiple such processors via on_failure. If there are multiple rules, the pipeline definition gets pretty hairy:

>        "grok": {
          "field": "cisco_message",
          "pattern": "%{CISCOFW106001}",
          "on_failure": [
            {
              "grok": {
                "field": "cisco_message",
                "pattern": "%{CISCOFW106006_106007_106010}",
                "on_failure": [
                  {
                    "grok": {
                      "field": "cisco_message",
                      "pattern": "%{CISCOFW106014}"
                      ...
Would a pattern array make sense, to emulate Logstash's behavior? Should I open an issue on GitHub or is there a better way to handle this already?

>Also, I'm not sure how Logstash implements this but performance degrades quite nicely with multiple rules. In this particular case, I've seen 1.5x slower throughput with 23 rules compared to one rule. With the ingest node and the on_failure approach described here, I'm getting 9x slower throughput with 23 rules. That said, Ingest node is faster in both cases, so maybe Logstash behaves better proportionally because it's heavier to begin with.
...

**Comment by talevy** [comment]
please ignore the `breaking` tag, meant to signify a change in API. This change is only breaking between 5.0alpha1 and 5.0, so the tag is a bit extreme.

**Comment by javanna** [comment]
this could be done with an `on_failure` section for grok, that contains another grok with the second pattern and so on. Too verbose?

**Comment by talevy** [comment]
@javanna I will try and see how often I run into this use-case from the Logstash side.

From what I remember, this happens enough that I think it would be too verbose to be handled in many nested `on_failure` blocks.
