### ISSUE TITLE
Elasticsearch 2.3.2

### ISSUE THREAD

**Issue by IdanAdar** [elastic/elasticsearch#17904]
The elasticsearch label for 2.3.2 has no more open issues, however the .zip for v2.3.2 is not available.
Will this be available for downloading?

2.3.2 contains fixes for CORS which are required...

**Comment by jasontedor** [comment]
Please regard the note that Elastic reserves GitHub for verified bug reports and feature requests and that for general questions you can use the [Elastic Discourse forums](https://discuss.elastic.co).

**Comment by IdanAdar** [comment]
I did. None is replying there either.
https://discuss.elastic.co/t/elastic-2-3-2/47953
