### ISSUE TITLE
geo_shape indexing slowdown in v2.3

### ISSUE THREAD

**Issue by mekanixdk** [elastic/elasticsearch#17907]
**Elasticsearch version**:

```
{
  "name" : "Ani-Mator",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.1",
    "build_hash" : "bd980929010aef404e7cb0843e61d0665269fc39",
    "build_timestamp" : "2016-04-04T12:25:05Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
```

**JVM version**:

```
openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)
```

**OS version**:

```
#uname -or
4.1.12-boot2docker GNU/Linux
#more /etc/debian_version
8.4
```

In short I am using the official elasticsearch Docker image.

**Description of the problem including expected versus actual behavior**:

We are bumping our elasticsearch servers from v1.5.3 to v2.3 and indexing of geo_shapes have slowed downed an order of magnitude of *100* across the board. Fx. we have a geo_shape of Sweden that in v1.5.3 took < 10 s and now takes 8+ minutes.

We are seeing this in both development with Docker and AWS (not using docker).

**Steps to reproduce**:
 1. Install official Docker image of v2.3
 2. 
```
curl -XPUT localhost:9200/test -d '{
   "mappings": {
     "dist":{
       "properties": {
         "areas": {
           "type": "geo_shape",
           "precision": "100m"
         }
       }
     }
   }
 }'
```
 3.
`curl -XPUT localhost:9200/test/dist/1 -d GIST_CONTENT` where `GIST_CONTENT=` https://gist.github.com/mekanixdk/8b0178e12161375b1e8a76e16842bc0a 

**Provide logs (if relevant)**:

**Comment by clintongormley** [comment]
@nknize is this due to changes in precision level?

**Comment by mekanixdk** [comment]
Omitting `precision` from mappings (aka staying with default) will index the area in a blink.

**Comment by nknize** [comment]
@mekanixdk so in your case using `100m` precision is reducing performance?

**Comment by mekanixdk** [comment]
Yes, very.

If I read the documentation correctly (https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-geo-shapes.html) the default is something like `9` which equates to 5x5 meters geohashes. If I stay with this default (ie. not setting the `precision` parameter.

We don't need this kind of precision so we go with `100m`. In the case of Sweden it goes from almost instantly (5x5m) to ~10 minutes (100x100m). It is as if the `m` is lost and elasticsearch interpret it as precision `100`.

**Comment by mekanixdk** [comment]
Stumbled over https://discuss.elastic.co/t/unable-to-index-large-geo-shapes-in-2-0/38196

And reading https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html closely it appears that I have been bitten by a change I had not noticed.

Adding `distance_error_pct=0.025` we get the performance back.

**Comment by clintongormley** [comment]
Looks like this is documented under `distance_error_pct` here: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/geo-shape.html so I'm going to close this issue
