### ISSUE TITLE
Remove custom thread pools

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#17915]
Today, we allow the creation of arbitrary custom thread pools. I'm not convinced this is a useful feature and do think that it is a dangerous one. I propose that we remove the capability for custom thread pools.

**Comment by jpountz** [comment]
This would mean that plugins could not have dedicated thread pools anymore. They could use the `generic` threadpool instead, but this has the drawback that it is unbounded. Another option that was mentioned was to create a bounded thread pool that all plugins could share when they need a bounded thread pool. There were diverging opinions and we would like to hear @s1monw 's opinion before moving forward.

**Comment by jasontedor** [comment]
> They could use the generic threadpool instead, but this has the drawback that it is unbounded.

The generic thread pool will be bounded after #17017.

**Comment by s1monw** [comment]
I think we should remove that option but need to be careful with the consequences. If plugins have long running tasks they might need a different infrastructure? Something like an internal long task pool we can only use from internal?

**Comment by s1monw** [comment]
@uboness what do you think ^^ I think it can be bound and rejects quickly such that we don't have too many long running tasks going on at the same time?

**Comment by s1monw** [comment]
removed the discuss label @uboness can you please comment

**Comment by jasontedor** [comment]
Closed in favor of #18613
