### ISSUE TITLE
Use epoch seconds in `to` and `from` fields of date range aggregation `ranges` objects.

### ISSUE THREAD

**Issue by hrfuller** [elastic/elasticsearch#17920]
**Describe the feature**:

When aggregating documents with a date field mapping using `format: epoch_seconds` I would like to use epoch seconds in the `to` and `from` fields of a date-range aggregation. At present dates passed in `to` and `from` are not converted to milliseconds before the date-range aggregation.

This seems inconsistent with how dates are converted from the mapping format to the internal usage format when PUTing documents when the date-field format is specified.

**Comment by clintongormley** [comment]
@hrfuller the `format` parameter in the agg is for the display format only.  For input formats, you can add `epoch_seconds` to your field mapping, eg:

    "mappings": {
      "t": {
        "properties": {
          "date": {
            "type": "date",
            "format": "strict_date_optional_time||epoch_millis"
          }
        }
      }
    }

**Comment by hrfuller** [comment]
@clintongormley My mapping has a date property formatted as `epoch_seconds`. When using a date-range aggregation and passing a date in `epoch_seconds` as the value of the `to` and `from` fields.
I.e
```python
'date_range': {
    'field': 'dims.time',
    'ranges': [
        {
            'from': 1454463970,
            'to': 1455150295,
        }
    ]
},
```
 the date-range aggregator interprets the timestamps as `epoch_millis`. Of course I can easily convert the `epoch_seconds` to `epoch_millis`.

This was a feature request because it seems like it would improve the consistency of the elasticsearch API if date ranges were query-able/aggregate-able using the date input format specified in the date mapping.

```
"version" : {
    "number" : "2.3.1",
    "build_hash" : "bd980929010aef404e7cb0843e61d0665269fc39",
    "build_timestamp" : "2016-04-04T12:25:05Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
```

**Comment by clintongormley** [comment]
Sorry, I completely misread the original description.  I thought you were setting the format in the agg, not in the mapping.  This is a bug.

**Comment by rnagulapalle** [comment]
does it support `unbounded range`. For example `gt` : 'unix-timestamp`
