### ISSUE TITLE
"Past releases" page has invisible pagination

### ISSUE THREAD

**Issue by adamMo** [elastic/elasticsearch#17925]
Hello, 

I noticed that page [https://www.elastic.co/downloads/past-releases](https://www.elastic.co/downloads/past-releases) has invisiblepagination on Chrome on Windows (version 50.0.2661.87 m) and IE 10.

Chrome:
![image](https://cloud.githubusercontent.com/assets/18612366/14738063/d5731348-087f-11e6-9baf-cbb3187461d6.png)

IE:
![image](https://cloud.githubusercontent.com/assets/18612366/14738023/8587ae0c-087f-11e6-9bd4-8e96cea5d54b.png)

**Comment by girirajsharma** [comment]
@adamMo It doesn't seems to be invisible. It auto shifts left or right depending on whether you move forward or backward. Its just a specific type of UI/UX unlike the normal bootstrap one.

**Comment by adamMo** [comment]
@girirajsharma Now I compared with other PC's in my office and it must be something with chrome addons I use or with my screen contrast because it works well for others - I just don't see other digits than currently selected. 

I'm closing this unfair issue and wish you a good day!

**Comment by girirajsharma** [comment]
@adamMo No problem at all. I too observed the pagination numbers turn invisible on a higher contrast.

**Comment by sylvie777** [comment]
@girirajsharma @adamMo Hi there! By "invisible", do you mean the font color is too light? I can see the page numbers in the screenshots provided above.

**Comment by adamMo** [comment]
@sylvie777 hello, I would have to make a photo of my screen to show you how I see it but it looks like I've been given a display with preset high contrast, so the screenshots looked the same for me. 

I'm replying on the phone and now I see that I was wrong :)
