### ISSUE TITLE
How to create a child type when its parent type is already exist in Elasticsearch 2.X?

### ISSUE THREAD

**Issue by yuemaoxing** [elastic/elasticsearch#17922]
I know parent/child has been rewritten in ES2.X, and the mapping for the parent type can be added at the same time as the mapping for the child type, but cannot be added before the child type.

But I think it's not logical. In my situation, I cannot create all children types with their parent type mapping at the same time. I really need to create a child type when its parent type is already exist.

Please give some suggestions.

**Comment by jasontedor** [comment]
Elastic reserves GitHub for bugs and feature requests. Please use the [Elastic Discourse forums](https://discuss.elastic.co) for general questions.
