### ISSUE TITLE
Delete archived cluster settings with `null`

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#17929]
You should be able to delete archived cluster settings with the following:

    PUT _cluster/settings
    {
      "persistent": {
        "archived": null
      }
    }

It returns OK, but the settings aren't deleted.

**Comment by mstockerl** [comment]
Is it really desired to delete with a PUT request? Sounds like a mistake to me.

**Comment by abeyad** [comment]
The proper way to delete these settings as https://github.com/elastic/elasticsearch/blob/master/docs/reference/cluster/update-settings.asciidoc indicates is:

`PUT _cluster/settings
{
  "persistent": {
    "archived.*": null
  }
}`
