### ISSUE TITLE
Improve how the multi search api concurrently executes

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#17926]
Today the multi search api executes all search requests in parallel without any limiting. So a multi search requests that holds many search requests can easily flood the search thread pool on nodes.

A better approach would if the multi search api works like the multi get api. We pick a shard copy for all shards that are going to be queried and send all search requests to nodes holding these shard copies to execute the query phase. Each node returns shard level results for all these search requests and the node that is coordinating the multi search request is then bulk reducing these shard level responses and after that the coordinating node will send requests for the fetch phase in the same way it did that for the query phase. The main point is that at the shard level we use only one thread to execute the shard level operations for all requests a node has received.

**Comment by rnagappan** [comment]
This would be enormously helpful to us. Often we have to do lots of independent searches in a batch and the round-trip latency waiting for each one to complete costs us an awful lot of time. It would improve our throughput enormously if we could send say 1000 searches a single batch and not have the cluster reject them all. So basically something like the bulk API but for search.

**Comment by clintongormley** [comment]
We should add a concurrency parameter to limit the number of searches from an msearch that are run in parallel.
