### ISSUE TITLE
Feature: Add visitor pattern on Aggregations

### ISSUE THREAD

**Issue by jeusdi** [elastic/elasticsearch#17923]
**Describe the feature**:
I've realized it could be usefull provide a visitor pattern on aggregations.
When I get a `SearchResponse`, I get the aggregations' response using `getAggregations()`.

Taking in mind that, every `Aggregation (MultiBucketsAggregation)` has `buckets` and each `bucket` could have internal Aggregations, I think it could be useful to provide an `accept(AggregationVisitor)` method on `Aggregation` interface and an `AggregationVisitor` interface providing methods like:

- `visit(Aggregation)`
- `visit(MultiBucketsAggregation)`
- `visit(StringTerms)`
- and so on...

**Comment by s1monw** [comment]
Given the fact that we are moving away from a Java based API towards HTTP based clients we decided to not further explore this path. We can still reopen if it becomes more relevant in the future
