### ISSUE TITLE
Remove support for fallback settings

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#17931]
Follow-up of #17917. The ability to have fallback settings makes things complicated when eg. you want to get a value from several Settings instances. I think call sites should handle the fall back themselves in an explicit way rather than relying on the Settings class to do so.

**Comment by nik9000** [comment]
Do you want to remove `Setting#get(Settings, Settings)`. Or the fallback `fallbackSetting` support? I think we could keep them if we were willing to spend a bit more time on them and we were willing to overhaul how settings are built. I think we should do the second thing anyway because there are too many constructors and constructor like things on Setting.

**Comment by jpountz** [comment]
> Or the fallback fallbackSetting support?

Yes this one.

**Comment by probakowski** [comment]
As I saw rather increase in use of fallbackSetting over the years, I guess we stick to it.
I'll close this issue as stalled. Feel free to reopen if you think it's still relevant

**Comment by rjernst** [comment]
I think this issue is still relevant. IMO the original purpose was to remove essentially multiple ways to specify the same setting. The one case where this is legitimately used is with deprecated settings, but we could ensure the mechanism is only used in that case.

**Comment by gwbrown** [comment]
This would be a good thing to do, but here's what we would need to do to follow through:
- Prepare a list of settings which use fallback settings and post it to this issue
- Emit deprecation warnings when a fallback setting is used in [next minor]
- Remove fallback settings in [next major]

Per the last comment on this issue, it would be best if we could adjust the code to *automatically* emit a deprecation warning when a fallback setting is used, and change the parameter name to indicate that the fallback is deprecated. However, not all of the uses of fallback settings are deprecated - for example, `http.tcp.send_buffer_size` falls back to `network.tcp.send_buffer_size`, which is not deprecated, either in the code or [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/modules-network.html#tcp-settings), and is also used as the default for `transport.tcp.send_buffer_size`.

While I agree with the argument that there shouldn't be multiple places to set a given setting, it does make sense to have a general "network" configuration which can be overridden for certain cases. I'm going to tag this team-discuss to make sure we're still on the same page and to find an owner for this.

**Comment by jaymode** [comment]
The core/infra team discussed this today. The discussion included issues with fallback settings such as making the actual configuration in use harder to reason about while also weighing the cost of doing this. The work to remove this is likely going to be extensive and also could result in breaking changes. Given the age of this issue and the cost vs benefit of fixing this, the team has made a decision to close this issue for now. We can always revisit this item in the future if fallback settings continue to cause issues.
