### ISSUE TITLE
GC metrics using /_cat API

### ISSUE THREAD

**Issue by amitranjan-fk** [elastic/elasticsearch#17939]
**Elasticsearch version**: 1.5.2

Is it possible to use /_cat API to get gc metrics ? If yes, what is the API ?

**Comment by jasontedor** [comment]
Please note that Elastic reserves GitHub for verified bug reports and feature requests. You can use the [Elastic Discourse formus](https://discuss.elastic.co) to ask general questions.

**Comment by McStork** [comment]
@amitranjan-fk Pretty sure it's not possible right now. See feature request https://github.com/elastic/elasticsearch/issues/17224.
