### ISSUE TITLE
how to disable elasticsearch default log？

### ISSUE THREAD

**Issue by rfyiamcool** [elastic/elasticsearch#17946]
##always stdout,  I want to get it .
```
Starting new HTTP connection (1)
POST http://xx.xx.xx.xx:6700/_bulk [status:200 request:0.024s]
```

my python settting:
```
logging.basicConfig(filename = os.path.join(os.getcwd(), 'migrate_pipe.log'),\
    level = logging.INFO, filemode = 'a', format = '%(asctime)s - %(process)s - %(levelname)s:\
    %(message)s')
logging.getLogger('elasticsearch.trace').setLevel(logging.CRITICAL)
logging.getLogger('requests').setLevel(logging.CRITICAL)
logging.getLogger("urllib3").setLevel(logging.CRITICAL)
```

thanks U

**Comment by jasontedor** [comment]
Please note that Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions. Additionally, there is a repository for the [Elasticsearch Python client](https://github.com/elastic/elasticsearch-py).
