### ISSUE TITLE
v5 Aggregations Documentation inaccurate or bug

### ISSUE THREAD

**Issue by viztastic** [elastic/elasticsearch#17941]
**Elasticsearch version**:
v5 alpha 1
**JVM version**:
8
**OS version**:
Mac OS X El Capitan
**Description of the problem including expected versus actual behavior**:
https://www.elastic.co/guide/en/elasticsearch/reference/master/_executing_aggregations.html

That tutorial suggests that running this code:
``{
  "size": 0,
  "aggs": {
    "group_by_state": {
      "terms": {
        "field": "state"
      }
    }
  }
}``

should return an aggregated, result, instead, we receive this:

``
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_state_exception",
        "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [state] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory."
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "bank",
        "node": "101piinIR-Wpum7j28_RPg",
        "reason": {
          "type": "illegal_state_exception",
          "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [state] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory."
        }
      }
    ],
    "caused_by": {
      "type": "illegal_state_exception",
      "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [state] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory."
    }
  },
  "status": 500
}
``
**Steps to reproduce**:
see above

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by thomasmodeneis** [comment]
Oh guys, really bad breaking change that is still not clear on docs.
Not nice.

**Comment by clintongormley** [comment]
@thomasmodeneis you'll find this documented in the breaking changes section: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_aggregations_changes.html#_literal_size_0_literal_on_terms_significant_terms_and_geohash_grid_aggregations
