### ISSUE TITLE
ES 2.3 doesn't encode Cyrillic symbols in search URIs

### ISSUE THREAD

**Issue by nicky1038** [elastic/elasticsearch#17954]
I am using Sense and just browser search line to GET results of search URI whose query consist of a Russian word, "тест", for example. But null is always returned. When I search for English words, everything is perfect.
The following command in cURL works fine:
`curl -XGET -G 'http://localhost:9200/test-index/_search' —data-urlencode "q=text:тест"`
So the problem is that ES itself doesn't encode Cyrillic symbols anymore (I remember it did in 1.x).

**Comment by clintongormley** [comment]
works for me:

    curl -XGET -G 'http://localhost:9200/t/_search' --data-urlencode "q=text:тест"


    {
      "took": 1,
      "timed_out": false,
      "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
      },
      "hits": {
        "total": 1,
        "max_score": 1,
        "hits": [
          {
            "_index": "t",
            "_type": "t",
            "_id": "1",
            "_score": 1,
            "_source": {
              "text": "тест"
            }
          }
        ]
      }
    }

Looks like you have an encoding problem somewhere.

**Comment by nicky1038** [comment]
@clintongormley Please re-read my message again. I've said that the variant with cURL works fine. But URI search in Sense (i.e. test-index/_search?q=text:тест) returns null.

**Comment by dadoonet** [comment]
May be you should open the issue in Sense then? https://github.com/elastic/sense

That being said, may be your browser is not in "UTF-8" so characters are not encoded in a proper way?
FWIW it's not an issue in elasticsearch as you already guessed.
