### ISSUE TITLE
Get and MultiGet inconsistency with date math expressions

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#17957]
When using index name date math expressions `<logstash-{now/M}>`, the Get API works and is able to resolve the index. However, if you try to get the same value using the MultiGet API it fails as it treats the index name as a concrete index name rather than allowing for the possibility that it could be an expression. I think the behavior of the APIs should be consistent.

I tend to question the usefulness of the date math expression in a get request. I could see one scenario where you know the id of a document (the id is consistent) and want to get the "current" one using a date math expression.

**Comment by clintongormley** [comment]
> I tend to question the usefulness of the date math expression in a get request. 

Agreed

> I could see one scenario where you know the id of a document (the id is consistent) and want to get the "current" one using a date math expression.

That's very much an edge case.  On the other hand, support date math expressions everywhere doesn't cost much...  That said, I think I'm leaning more towards "why would you do that?"

**Comment by clintongormley** [comment]
Looks like there is a bug in multiget, which may impact alias lookup too - let's just make multiget consistent with get (and fix the bug)
