### ISSUE TITLE
indices.breaker.request.limit not increasing trip count

### ISSUE THREAD

**Issue by kuramae** [elastic/elasticsearch#17952]
Elasticsearch version: 1.7.5
JVM version: 1.8.0_60
OS version: Ubuntu 3.11.0-26-generic

indices.breaker.request.limit is probably not working as expected. As shown in the attached image, I tried setting indices.breaker.request.limit=8Mb whilst debugging a load issue that might have been linked to the size of the documents. I expected to see the trip count increase as the request estimated size passed the 8Mb threshold but that didn't occur. We didn't see an increased rate of rejection so Marvel it most likely reporting truthful data. 
indices.breaker.request.overhead was left set to 1.

It might be a misunderstanding of the documentation but in that case I'd recommend reviewing the page
https://www.elastic.co/guide/en/elasticsearch/reference/current/circuit-breaker.html

![screen shot 2016-04-25 at 12 51 12](https://cloud.githubusercontent.com/assets/506458/14783160/b5e27254-0ae5-11e6-96c5-c453f3189766.png)

**Comment by clintongormley** [comment]
@dakrone any ideas?

**Comment by dakrone** [comment]
@kuramae I just tested locally with 1.7.5 and the request breaker trip count does increment when the breaker is tripped. Are you sure you are seeing the request breaker trip at all? Perhaps you are thinking of something limiting the size of the request bodies themselves? In that case, you will need to use either 2.4.0 or 5.0.0 when they are released, see: https://github.com/elastic/elasticsearch/pull/17133

**Comment by kuramae** [comment]
Thanks for having a look. Possibly nothing wrong here if the trip count increments. The thing that confuses me a bit is that from the Marvel plots you can see the breaker limit being set to 8Mb, the request trip count staying at 0, and the request estimated size passing the limit. The way I interpreted the documentation makes it look like the memory allocated per request is higher than 8Mb but the requests are not failed and reported in the stats.

**Comment by dakrone** [comment]
Okay, thanks for checking @kuramae, I'm going to close this now, but feel free to comment/re-open if you see CircuitBreakingExceptions that don't increment the counter!
