### ISSUE TITLE
Cluster with "hot-warm" architecture: hot index shards not assigned when restarting service

### ISSUE THREAD

**Issue by danling** [elastic/elasticsearch#17961]
**Elasticsearch version**: 
Elasticsearch version is 1.7.1
**JVM version**:
Java version is
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**OS version**:
OS is RHEL 7.1
**Description of the problem including expected versus actual behavior**:
The Elasticsearch cluster has 3 data nodes. The cluster is configured using "hot-warm" architecture based on the instructions in https://www.elastic.co/blog/hot-warm-architecture. One node is configured as "hot" and two nodes are configured as "warm".  Hot indices are changed to warm and moved to warm nodes every 3 days. 
The problem is that when restarting elasticsearch service on either a host or warm node, the cluster status stays in "yellow" state because shards for hot indices are unassigned. I have manually update the index settings to change from "hot" to "warm"
curl -XPUT 'localhost:9200/<indexName>/_settings' -d '{ "index.routing.allocation.require.box_type" : "warm" }'
When indices are changed to warm, the shards are assigned immediately and the cluster status becomes "green".

I would expect that the shards of hot indices be assigned when restarting the elasticsearch service just like the warm indices. 

Does anyone know if elasticsearch 2.x has the same behavior or is it the 1.7 only issue?

**Steps to reproduce**:
 1. Configure a cluster using the instructions in  https://www.elastic.co/blog/hot-warm-architecture. 
 2. Set at least one index to hot.
 3. restart elasticsearch service and check the cluster health status 
     curl -XGET 'http://localhost:9200/_cluster/health?pretty=true'

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by clintongormley** [comment]
@danling when you're in this situation, please could you try to assign the shard manually with the cluster reroute API, and include the `?explain` query string param (see https://www.elastic.co/guide/en/elasticsearch/reference/1.7/cluster-reroute.html)

That will tell you why the shard can't be assigned (or it'll go ahead and assign the shard).  There may have been bugs fixed in this area even in 1.7, so worth upgrading to 1.7.5 (and even better, upgrade to 2.3.2)

**Comment by danling** [comment]
Thanks for the suggestion. Here is the information I got from the reroute API:
The unassigned index is a "hot" index and has setting:
 "index" : {
        "routing" : {
          "allocation" : {
            "require" : {
              "box_type" : "hot"
            }   }   },
The unassigned index is on the "hot" node (the cluster has 1 hot node and 2 warm nodes).  
First, I tried to allocate the index to the hot node:
curl -XPOST 'localhost:9200/_cluster/reroute?explain&pretty=true' -d '{
    "commands" : [    {
          "allocate" : {
              "index" : "logstash-test-20160426", "shard" : 0, "node" : "data1_hot_node"
          } }    ] }'
It failed with 
"explanation" : "shard cannot be allocated on same node [_FNsW1arSDip4ymYPNu5Ng] it already exists on".  
Second, I tried to allocate the hot index to one of the warm nodes, and got 
 "explanation" : "node does not match index required filters [box_type:\"hot\"]". 
I assume the 2nd try failed is because a warm node can have only warm indices. 
It seems that the hot index exists on the hot node but ElasticSearch is not able to assign its shards.

**Comment by danling** [comment]
I noticed this morning that when a new "hot" index was created, the shards were not assigned as well, and the cluster status became "yellow". So the problem is not just when restarting elasticsearch service.

**Comment by danling** [comment]
I found the reason for unassigned shards of hot indices. The cluster is configured to have 1 replica, but it has only 1 hot node. By adding a second hot node, it solves the problem.

**Comment by dakrone** [comment]
Yes, as the output shows above ("shard cannot be allocated on same node [_FNsW1arSDip4ymYPNu5Ng] it already exists on"), you'll need to either set the number of replicas to 0, or increase the number of nodes
