### ISSUE TITLE
Access file-based stored index template through API

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#17968]
**Describe the feature**:

Currently (and as documented), index templates added via config/templates are not included in the _template api output. This can be confusing to admins.  It is more user friendly if we can return all index templates including ones defined on disk via the API - and add a metadata field to tag index templates created on disk in the api output so users can tell which ones are set in the API vs. on disk (and maybe disallow changes via the template api for the ones that are managed on disk).

**Comment by cnwarden** [comment]
:+1:

**Comment by ppf2** [comment]
Per @rjernst 's (thx!) comment (https://github.com/elastic/elasticsearch/issues/10910#issuecomment-214828977), file based index templates have actually been [removed from the product](https://github.com/elastic/elasticsearch/pull/11052) starting in 2.x, so I will close this ticket :)
