### ISSUE TITLE
top hits subaggregation  not working as expected.

### ISSUE THREAD

**Issue by abhishekguruvayya** [elastic/elasticsearch#17962]
**Elasticsearch version**: 2.1.1

**JVM version**: 
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.20-b23, mixed mode)

**OS version**:
CentOS release 6.7 (Final)

**Description of the problem including expected versus actual behavior**:
Top hits subaggregation setSize(1) not returning one top hit/per bucket instead it is returning more than one document even though the size is set to one. Below is the query i am trying to execute.

```
SearchResponse sr=client.prepareSearch(versionIndexName).setTypes(versionIndexType).setQuery(Quer 
yBuilders.boolQuery().must(QueryBuilders.rangeQuery("indexDate").lte(givenTime))) 
.addAggregation(AggregationBuilders.terms("form.id").field("form.id").size(0) 
.subAggregation(AggregationBuilders.topHits("top").setExplain(true).setSize(1) 
.setFrom((size*index)).addSort(SortBuilders.fieldSort("indexDate") 
.order(SortOrder.DESC)).setFetchSource(true))).execute().actionGet();
```

STEPS in the query:
Filter by indexDate less than or equal to a given date.
aggregate based on formId. Forming buckets per formId.
Sort in descending order on versionDate filed and return top hit result per bucket.

	
I have two versions (v1 and v2) for form.id=1 with indexDate field set to  2016-04-22T16:02:32.738-07:00 for v1 and 2016-04-22T16:02:33-07:00 for v2. If i search by date 2016-04-22T16:02:33-07:00 i expect to see a bucket with only v2 returned in it because that is the closest to the searched date. But the bucket has both the versions.

**Steps to reproduce**:
 1. Index two documents with version field as v1 and v2, indexDate filed set to 2016-04-22T16:02:32.738-07:00 for v1 and 2016-04-22T16:02:33-07:00 for v2, id field is set to 1 and 2.
 2. Run the above query with givenTime= 2016-04-22T16:02:33-07:00.
 3. Retrieve the buckets and values.

Expected result: 1 bucket with one version(v2) in it. Because that is the top hit for that bucket after sorting.
Actual result: 1 bucket with both the version(v1 and v2).

**Comment by clintongormley** [comment]
The equivalent written for the REST api works just fine:

PUT t/t/1
    {
      "form": {
        "id": "1"
      },
      "version": "v1",
      "indexDate": "2016-04-22T16:02:32.738-07:00"
    }
    
    PUT t/t/2
    {
      "form": {
        "id": "2"
      },
      "version": "v2",
      "indexDate": "2016-04-22T16:02:33-07:00"
    }
    
    GET t/t/_search?size=0
    {
      "query": {
        "bool": {
          "must": [
            {
              "range": {
                "indexDate": {
                  "lte": "2016-04-22T16:02:33-07:00"
                }
              }
            }
          ]
        }
      },
      "aggs": {
        "form.id": {
          "terms": {
            "field": "form.id",
            "size": 0
          },
          "aggs": {
            "top": {
              "top_hits": {
                "size": 1
              }
            }
          }
        }
      },
      "sort": {
        "indexDate": {
          "order": "desc"
        }
      }
    }


My suspicion is that either the way you're using the Java API isn't correct, or there is something fishy about your docs.

Could you provide your docs as curl statements, and use toXContent on your query to output what it looks like in JSON - that'll help figure out why this isn't working.

**Comment by clintongormley** [comment]
No further feedback.  Closing
