### ISSUE TITLE
Fix error message `script.inline: on`

### ISSUE THREAD

**Issue by bluepuma77** [elastic/elasticsearch#17977]
Incorrect error message when setting wrong script parameters.

**Elasticsearch version**: 2.3.1
docker pull elastic:latest

**OS version**: Linux 05932458a9d5 4.2.0-35-generic #40~14.04.1-Ubuntu SMP Fri Mar 18 16:37:35 UTC 2016 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Incorrect error message when setting wrong script parameters in elasticsearch.yml

According to [current documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html) it should be ```script.inline: true```and not ```script.inline: on```

**Steps to reproduce**:
 1. echo "script.disable_dynamic: false" >> config/elasticsearch.yml
 2. Restart elastic
 3. Elastic crashes

Note: I know that the parameter is wrong but the error message is wrong, too.

**Provide logs (if relevant)**:
```
Exception in thread "main" java.lang.IllegalArgumentException: script.disable_dynamic is not a supported setting, replace with fine-grained script settings.
Dynamic scripts can be enabled for all languages and all operations by replacing `script.disable_dynamic: false` with `script.inline: on` and `script.indexed: on` in elasticsearch.yml
```

**Comment by jasontedor** [comment]
In 2.x, `on` can be used as a synonym for `true` when setting the script mode. In fact, any of `true`, `1`, `on`, or `yes` can be used. This has been removed in 5.0.0 and only `true` will be accepted.
