### ISSUE TITLE
Dubious equality test in RoutingNodes.java

### ISSUE THREAD

**Issue by xiemaisi** [elastic/elasticsearch#17982]
The following equality check in [core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java](https://github.com/elastic/elasticsearch/blob/543b27f4cda099966879a192b019418f94fd379b/core/src/main/java/org/elasticsearch/cluster/routing/RoutingNodes.java#L400) (line 400) looks a bit fishy:

```java
if (unassignedShard.index().equals(index)) {
```

Note that `unassignedShard.index()` is of type `Index`, while `index` is of type `String`, so I don't think this test can ever evaluate to `true`.

**Comment by jasontedor** [comment]
This method is invoked in tests only, and none of the tests ever invoke the method with `state` containing `ShardRoutingState.UNASSIGNED`. Thus, this code is currently never triggered. That said, this code should be fixed now in case it ever is triggered. Thanks for noticing this. I'll push a fix.
