### ISSUE TITLE
When backing up to NFS snapshots get stuck indefinately

### ISSUE THREAD

**Issue by dforste** [elastic/elasticsearch#17991]
**Elasticsearch version**: 2.2.1

**JVM version**: Oracle jdk1.8.0_60

**OS version**: Red Hat Enterprise Linux Server release 7.2 (Maipo) 
Linux hostname.example.com 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Intermittently elasticsearch will never complete the snapshot in progress. The only way to fix it is to do a rolling restart of all data nodes. The "stuck" nodes will take longer to restart under systemd and will leave a zombie java process like this: 
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
elastic+ 13067 35.4  0.0      0     0 ?        Zl   Apr16 5407:11 [java] <defunct> 

They will also abandon the normal working directory and startup under a new node directory like 
cluster/nodes/1/ instead of cluster/nodes/0/ 

The only way to get elasticsearch to start up under the correct node directory is to restart the server which is not desirable. 

**Steps to reproduce**:
 1. Install elasticsearch on multiple nodes with a shared nfs volume. 
 2. Run snapshots (Our snapshots are usually backing up about 3 TB with about 100 GB new data each day ) Snapshots fail within 2 weeks to a month usually. 

I have also seen larger one time snapshots fail in this same manner.

**Comment by clintongormley** [comment]
@ywelsch any ideas?

**Comment by ywelsch** [comment]
@dforste Are there any warnings in the logs? Can you provide thread dumps of the nodes that are stuck? What happens if you delete the snapshot that is stuck? Does that unblock the nodes?

**Comment by dforste** [comment]
@ywelsch I have tried deleting it before but that doesn't work either. Only rebooting/restarting the nodes tells me which one is stuck via the defunct java process. I cant find my thread dumps from before so I will have to wait a bit and I will try to get you some. 

Elasticsearch continues doing everything else while this is happening. Only seems like snapshot and restore are affected.

**Comment by ywelsch** [comment]
How is the nfs volume mounted? It could be that the mount options are at fault: See e.g. `soft` vs. `hard` mount options here:
http://unix.stackexchange.com/questions/31979/stop-broken-nfs-mounts-from-locking-a-directory

> hard or soft — Specifies whether the program using a file via an NFS connection should stop and wait (hard) for the server to come back online, if the host serving the exported file system is unavailable, or if it should report an error (soft).

> If hard is specified, the user cannot terminate the process waiting for the NFS communication to resume unless the intr option is also specified.

> If soft is specified, the user can set an additional timeo=<value> option, where <value> specifies the number of seconds to pass before the error is reported.

**Comment by clintongormley** [comment]
No further feedback.  Closing

**Comment by dforste** [comment]
Sorry for not responding earlier. I had an issue where stdout was going to dev/null. Also adjusting snapshots to only snapshot the last week helped tremendously. I am attaching threadumps for the data nodes involved with the snapshot and the current master. 

[threadump-6-3-2016.tar.gz](https://github.com/elastic/elasticsearch/files/298217/threadump-6-3-2016.tar.gz)

Here are all the nfs mount options set in fstab: 
``` auto,rw,bg,vers=3,intr,soft,noatime,actimeo=300,nosuid,bg,rsize=32768,wsize=32768 ```

**Comment by schonfeld** [comment]
@dforste did you ever resolve this? I believe we're seeing something similar in v2.4.1... Any insight would be great!

**Comment by dforste** [comment]
@schonfeld I did not ever get it fully resolved. I did however minimize how often it happened by minimizing the amount we snapshot to just the previous week. I was doing all the indexes in one job but that is a bit too much.

**Comment by schonfeld** [comment]
@dforste got it, thanks! fwiw, we just setup a [minio](https://www.minio.io/) instance, and are using Elasticsearch's standard S3 snapshot plugin. Seems to be working very well!
