### ISSUE TITLE
Allow defining settings values to `null` when updating settings

### ISSUE THREAD

**Issue by Wedjaa** [elastic/elasticsearch#17995]
The idea is that right now when you update a setting that has multiple attributes you have no way of removing the old values - since ES ignores null values when updating settings. In practice:

```
{
   "settings": {
      "analysis": {
         "filter": {
             "lowercase_filter": {
                "type": "lowercase",
                "language": "greek"
             }
         }
      }
   }
}
```

these will create a lowercase filter for the `greek` language. If I want to go back to using the standard language if I try and `PUT` the following settings:

```
{
   "settings": {
      "analysis": {
         "filter": {
             "lowercase_filter": {
                "type": "lowercase"
             }
         }
      }
   }
}
```

the resulting settings in ES will not have changed - the missing `language` attribute would be simply merged from the previous version of the settings.

Explicitly setting the value to `null`

```
{
   "settings": {
      "analysis": {
         "filter": {
             "lowercase_filter": {
                "type": "lowercase",
                "language": null
             }
         }
      }
   }
}
```

has no effect - since the parses is currently simply ignoring null values. 

At the core of this there is the issue that currently the settings are being held in an immutable map that doesn't accept null values.

I have a PR that does the following:

* Create a `Setting` object that holds a setting value; I could have used an Optional - but I wanted to be  compatible with JDKs < 1.8;
* The Settings map will contain a map of Setting, allowing the loading of `null` values;
* The loader will correctly load null values into the settings;
* In the `Settings` builder there are two main changes: putting in settings will do a merge with the following logic: if the new value is `null` and an old value exists the key will be removed - and all the subkeys - otherwise we will insert the null in the settings.

Is there any other person interested in this PR?

Fabio

**Comment by clintongormley** [comment]
closing - see https://github.com/elastic/elasticsearch/pull/17996#issuecomment-215019511
