### ISSUE TITLE
Repository instance settings should not appear in cluster settings when using include_defaults

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#18008]
In elasticsearch 5.0, we now register settings which could be set within a cluster.

For example, when you want to define `access_key` in S3 repositories, you have multiple choices:

* In `elasticsearch.yml`, set `cloud.aws.access_key` or `cloud.aws.s3.access_key`
* In `elasticsearch.yml`, set `repositories.s3.access_key`
* When you create a Repository using `PUT /snapshot/repo`, you can pass a `access_key` setting:

```
PUT _snapshot/my_s3_repository
{
  "type": "s3",
  "settings": {
    "access_key": "mykey"
  }
}
```

Until now we registered all settings when [the plugin starts](https://github.com/elastic/elasticsearch/blob/master/plugins/repository-s3/src/main/java/org/elasticsearch/plugin/repository/s3/S3RepositoryPlugin.java#L132-L146).

The problem with that is when you call `GET _cluster/settings?include_defaults`, all those settings are returned, including `access_key` without any namespace.

If we don't register the repository level settings anymore, it will work **but** when we do a `GET _snapshot/repo` the credentials which are supposed to be hidden will be returned as they are not filtered anymore.

**Comment by s1monw** [comment]
why is `access_key` in the settings at all? shouldn't this be private to the repository? This setting should not be registered since the repository settings still do their own thing and therefor can't be filtered since they use a different infrastructure?

**Comment by dadoonet** [comment]
@s1monw I believe it's because we want to define credentials only once an not per repository?

Let say I'm an admin and I defined S3 credentials for repositories.
Then anyone could create a repository without having to know the credentials.

**Comment by s1monw** [comment]
it still makes no sense, the only way this can be returned is if you set it in you yaml files. but it can only be set in the `PUT /snapshot/repo` command so why the hack since it's private to the repo is it merged with node settings? I think you confuse things? can you provide a reproduction or a testcase?

**Comment by s1monw** [comment]
@dadoonet any updates?

**Comment by dadoonet** [comment]
@s1monw I'm sorry but I don't understand your comment. I'll try to ping you later next week to talk about it.

**Comment by dadoonet** [comment]
@s1monw I can confirm your opinion. What I described can not happen.

Closing.
