### ISSUE TITLE
ES 2.3.1 delete by parent id throw id is missing

### ISSUE THREAD

**Issue by andykai** [elastic/elasticsearch#18006]
Hi ,
I want to delete childs documents by parent.
My java codes is 
``` java
client.prepareDelete().setIndex("care").setType("CareServiceType").setParent("19448").execute().actionGet();
```
But throw exception  
org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: id is missing;

**Comment by clintongormley** [comment]
You can't do that with a delete command.  You need to use delete-by-query with a has_parent query

**Comment by andykai** [comment]
Yes, I know .But delete-by-query is a plugin now,But i can not find java api of delete-by-query plugin.
