### ISSUE TITLE
This one weird trick will make your query crash.

### ISSUE THREAD

**Issue by matthuhiggins** [elastic/elasticsearch#18029]
This fails on ES v2.3.2:
```
curl -XPUT http://127.0.0.1:9200/twitter/

curl http://127.0.0.1:9200/twitter/tweat/_search -d '
{
  "query": {
    "filtered": {
      "filter": {
        "terms": {
          "and": [
            {
              "terms": {
                "favorite_color": [
                  "green"
                ]
              }
            },
            {
              "not": {
                "and": [
                  {
                    "query": {
                      "terms": {
                        "favorite_color": ["blue"]
                      }
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    }
  }
}'
```

With the error:

`{"reason":"[_na] query malformed, must start with start_object"}`

The query works when any feature of the query is removed. For example, it works when the "not" is removed.

**Comment by clintongormley** [comment]
Love the clickbait.  Your query is malformed :)  Here:

      "filter": {
        "terms": {
          "and": [

The `terms` filter requires a field name

**Comment by matthuhiggins** [comment]
Arg, I pasted the wrong query. Here is the distilled problem:
```
curl -XPUT http://127.0.0.1:9200/twitter/

# This query crashes with "query malformed, must start with start_object":
curl http://127.0.0.1:9200/twitter/tweat/_search -d '
{
  "query": {
    "filtered": {
      "filter": {
        "not": {
          "and": [
            {
              "terms": {
                "favorite_color": ["blue"]
              }
            }
          ]
        }
      }
    }
  }
}'

# Removing the "not" filter works
curl http://127.0.0.1:9200/twitter/tweat/_search -d '
{
  "query": {
    "filtered": {
      "filter": {
        "and": [
          {
            "terms": {
              "favorite_color": ["blue"]
            }
          }
        ]
      }
    }
  }
}'

# Keeping the "not" filter and removing the "and" filter works
curl http://127.0.0.1:9200/twitter/tweat/_search -d '
{
  "query": {
    "filtered": {
      "filter": {
        "not": {
          "terms": {
            "favorite_color": ["blue"]
          }
        }
      }
    }
  }
}'
```

**Comment by clintongormley** [comment]
Not sure why, but in this case the `not` filter requires a `filter` parameter:

    GET /_search
    {
      "query": {
        "filtered": {
          "filter": {
            "not": {
              "filter": {
                "and": [
                  {
                    "terms": {
                      "favorite_color": [
                        "blue"
                      ]
                    }
                  }
                ]
              }
            }
          }
        }
      }
    }

Either way, the `not` clause is deprecated and has been removed in 5.0.  Use a `bool.must_not` instead

**Comment by matthuhiggins** [comment]
Is this the shortest way to write `NOT(city:Portland AND state:Oregon)`?:

```
{
  "bool": {
    "must_not": {
      "bool": {
        "must": [
          {
            "term": {
              "city": "Portland"
            }
          },
          {
            "term": {
              "state":"Oregon"
            }
          }
        ]
      }
    }
  }
}
```

**Comment by s1monw** [comment]
```
{
    "query_string" : {
        "query" : "NOT(city:Portland AND state:Oregon)"
    }
}
```
works too :)

**Comment by clintongormley** [comment]
You can use a single `bool`:

    {
      "bool": {
        "must_not": [
          {
            "term": {
              "city": "Portland"
            }
          },
          {
            "term": {
              "state": "Oregon"
            }
          }
        ]
      }
    }

**Comment by matthuhiggins** [comment]
Right. A single bool is equivalent to `NOT(city:Portland OR state:Oregon), which is the same as `NOT(city:Portland) AND NOT(state:Oregon)`. We have sorted out what to change in our application - only commenting here for the record.
