### ISSUE TITLE
"Too many open files" exception when running from Docker

### ISSUE THREAD

**Issue by fauria** [elastic/elasticsearch#18022]
**Elasticsearch version**: 2.3.2 (Dockerfile elasticsearch:latest)

**JVM version**: openjdk version "1.8.0_72-internal"

**OS version**: Docker image: https://hub.docker.com/_/elasticsearch/

**Description of the problem including expected versus actual behavior**: 
Expected behavior: An elasticsearch docker container successfully started.
Actual behavior: An elasticsearch docker container fails to start.

**Steps to reproduce**:
1. Run ```docker pull elasticsearch``` 
2. Run ```docker run -i -t --rm -v /srv/elasticseach/data:/usr/share/elasticsearch/data -v /srv/elasticseach/config:/usr/share/elasticsearch/config elasticsearch```
3. A java.nio.file.FileSystemException is raised with message "Too many open files". 

**Provide logs (if relevant)**:
http://pastebin.com/raw/kf0LDGxD

**Comment by jasontedor** [comment]
The problem is your max file descriptors are too low. There's even a warning in your logs:

> `[2016-04-27 19:08:27,576][WARN ][env                      ] [Box IV] max file descriptors [4096] for elasticsearch process likely too low, consider increasing to at least [65536]`

**Comment by fauria** [comment]
Im running elasticsearch from the official docker image: https://hub.docker.com/_/elasticsearch/

On my host environment, both hard and soft limits are greater than 65536:

```ulimit -Hn && ulimit -Sn```
```
98304
98304
```

However inside the container:

```docker run -i -t --rm elasticsearch bash```
```ulimit -Hn && ulimit -Sn```
```
4096
1024
```

**Comment by jasontedor** [comment]
There is not an official Docker image that is affiliated with Elastic. To be clear, the "official" Docker image on Docker Hub is not affiliated with Elastic.

**Comment by fauria** [comment]
I would never have thought that... Already submitted to https://github.com/docker-library/elasticsearch/issues/102 thank you!

**Comment by fauria** [comment]
Fixed!

If anyone has the same problem, try running the container with ```--ulimit nofile=98304:98304```command line option, i.e.:

```docker run -d --ulimit nofile=98304:98304 --name elasticsearch ... ```

**Comment by hcm007** [comment]
there is still same problem, when I use docker stack deploy -c in swarm @fauria

**Comment by chovy** [comment]
how do i do this with docker-compose?

**Comment by eugenweissbart** [comment]
Hi @chovy, I know it's probably too late, but the [official docs](https://docs.docker.com/compose/compose-file/#ulimits) on docker-compose files say it's pretty straightforward:
```
ulimits:
  nofile:
    soft: 98304
    hard: 98304
```
This should be done in your desired service's section.
