### ISSUE TITLE
Filtered Query Match on Document Contents Not Working

### ISSUE THREAD

**Issue by guikeller** [elastic/elasticsearch#18034]
Hello guys,

Following below a link with the steps / setup / etc with what I am trying to achieve with no success:
https://discuss.elastic.co/t/unable-to-find-document-searching-contents-mapper-attachments-plugin/48500

Thank you very much in advance.

Cheers,
Gui

**Comment by dadoonet** [comment]
Please keep the discussion on discuss unless we found out it's an issue.
