### ISSUE TITLE
List custom thread pools in _cat/thread_pool

### ISSUE THREAD

**Issue by avlukanin** [elastic/elasticsearch#18033]
**Describe the feature**:

It is easy to create a custom thread pool in elasticsearch.yml, e.g.:

```
threadpool.asdf.type: fixed
threadpool.asdf.size: 10
```

But this thread pool is not listed, when you use `_cat/thread_pool?v=asdf` command, because only `SUPPORTED_NAMES` can be listed in `org.elasticsearch.rest.action.cat.RestThreadPoolAction#getTableWithHeader`

**Comment by clintongormley** [comment]
We've been talking about adding a class which is responsible for creating threads.  Any other class that needs a thread pool should register its requirements with this class, and they should be available in the stats.

Related to #17915 and #12666

**Comment by avlukanin** [comment]
The stats is already collected for custom thread pools, but not shown. I had to patch `RestThreadPoolAction` to add my custom thread pool name to `SUPPORTED_NAMES` and `SUPPORTED_ALIASES` to show it.

Can you confirm, that the stats for custom thread pools will not only be collected, but shown as well, when the new paradigm is implemented?

**Comment by martijnvg** [comment]
This was fixed in #19721.
