### ISSUE TITLE
Add org.apache.lucene.search.MatchNoDocsQuery to forbiddenApi

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#18030]
In #17780 we introduced our own MatchNoDocsQuery that comes with an explanation of why no documents were matched. We switched to using that one in #17981 

Turns out there is another MatchNoDocsQuery in Lucene itself. To avoid confusion over which one to use, should we add the Lucene one as forbiddenApi? Another thing I thought about - @jimferenczi would it make sense to work with the Lucene project to make the support for explanations available in their original MatchNoDocsQuery?

**Comment by jimferenczi** [comment]
Let's try to merge the MatchNoDocsQuery in Lucene directly. I'll open a ticket.

**Comment by MaineC** [comment]
@jimferenczi Would be nice if you could post a link to said ticket here once it's open (didn't find it after searching for it in the Lucene issue tracker for 5min, possible I overlooked it).

**Comment by jimferenczi** [comment]
That was my intention @MaineC:
https://issues.apache.org/jira/browse/LUCENE-7276
Sorry for the confusion.

**Comment by pickypg** [comment]
FYI, the Lucene side got merged into Lucene 6.2.

**Comment by jimferenczi** [comment]
Closing since org.elasticsearch.common.lucene.search.MatchNoDocsQuery has been removed and we now use the new Lucene version with the explanation inside (https://github.com/elastic/elasticsearch/commit/c80a563a71706a135fa478c4899b58697471f382)
