### ISSUE TITLE
Debian package/config file descriptor count inconsistency

### ISSUE THREAD

**Issue by abraxxa** [elastic/elasticsearch#18040]
**Elasticsearch version**: 2.3.2

**JVM version**: openjdk-7-jre-headless:amd64   7u101-2.6.6-1~deb8u1

**OS version**: Debian 8 64bit

**Description of the problem including expected versus actual behaviour**:
The number of file descriptors set by the Debian systemd service file mismatches Elasticsearches' startup check triggering a WARNing.

**Steps to reproduce**:
 1. Install elasticsearch package on Debian 8
 2. Start elasticsearch
 3. Watch the elasticsearch logfile

**Provide logs (if relevant)**:
[2016-04-28 13:03:53,452][WARN ][env                      ] [node-1] max file descriptors [65535] for elasticsearch process likely too low, consider increasing to at least [65536]

**Comment by jasontedor** [comment]
Duplicates #17430, but the fix was only applied to master and never backported. I will backport.

**Comment by jasontedor** [comment]
The fix did not backport cleanly so the fix should go through proper review. I opened #18041.

**Comment by abraxxa** [comment]
Sorry for opening another issue, I only searched the open ones.
Thanks for the fix!

**Comment by jasontedor** [comment]
Closed by #18041.
