### ISSUE TITLE
Translog buffer is not configurable

### ISSUE THREAD

**Issue by prog8** [elastic/elasticsearch#18045]
Even though translog config has buffer size parameter in constructor and also IndexConfig it always uses default size of buffer. The default size is pretty small: 8KB. Why not to make it bigger or just configurable? It may turn out that translog generates a lot IO operations, even when it is configured to be "async".

**Comment by dakrone** [comment]
> The default size is pretty small: 8KB. Why not to make it bigger or just configurable?

An 8k buffer avoids the JVM having to malloc/free on every write, this is the same reason that Lucene writes in 8kb chunks

**Comment by prog8** [comment]
JVM having malloc/free? I think I don't get it. Why bigger buffer cannot be used?

**Comment by dakrone** [comment]
> JVM having malloc/free?

The JVM is written in C/C++, writes to a filesystem larger than 8kb require a `malloc()` and `free()` instead of allocating the buffer on the stack. Additionally, I don't believe we have any plans to make this buffer configurable.

**Comment by jasontedor** [comment]
I agree with everything @dakrone has said here and I also do not think this should be configurable.

**Comment by prog8** [comment]
> The JVM is written in C/C++, writes to a filesystem larger than 8kb require a malloc() and free() instead of allocating the buffer on the stack.

Sure. I don't mean it is not written in C/C++. I just didn't see connection between malloc and why buffer size for translog cannot be configurable. I was using default buffer size (8KB) and async translog. Java Mission Control showed me a lot of write operations to disk, which means a lot of IOPS. After I changed the buffer size to 512KB JMC shows much less write operations but they are 512KB instead of 8KB. This is why I don't see a reason why the buffer size cannot be configurable.

**Comment by otisg** [comment]
@prog8 are you able to quantify the change in write ops when you changed the buffer from 8KB to 512KB?  Maybe if that change is large and there are no negative side-effects this would be worth reconsidering @dakrone @jasontedor ?

**Comment by prog8** [comment]
I was just looking at Java Mission Control. Before the change I saw plenty of write operations in JMC. After changing it to 512KB the number was much smaller. I cannot quantify the change in number of write operations per second. I was just surprised that many parameters are configurable in ES - even translog sync_interval but it is not possible to change translog buffer size so it is not easy to find out how changing the buffer size impacts the number of write operations.

**Comment by s1monw** [comment]
> I agree with everything @dakrone has said here and I also do not think this should be configurable.

+1
