### ISSUE TITLE
Ability to list available (supported) plugins from the plugin command line

### ISSUE THREAD

**Issue by geekpete** [elastic/elasticsearch#18056]
Provide the ability to list (at least supported) plugins from the elasticsearch-plugin command line.

This would be an easy way to show a list or filtered list of available plugins then install the ones you want without ever having to go to the documentation page to see what's available.

Might get hard to maintain possibly, but start with the officially supported plugins should be fine.

A further feature could be also listing all available versions of a plugin

**Comment by rjernst** [comment]
`elasticsearch-plugin` shows the official plugins:

```
$ bin/elasticsearch-plugin install --help
Install a plugin

The following official plugins may be installed by name:
  analysis-icu
  analysis-kuromoji
  analysis-phonetic
  analysis-smartcn
  analysis-stempel
  delete-by-query
  discovery-azure
  discovery-ec2
  discovery-gce
  ingest-attachment
  ingest-geoip
  lang-javascript
  lang-python
  mapper-attachments
  mapper-murmur3
  mapper-size
  repository-azure
  repository-hdfs
  repository-s3
  store-smb
  x-pack

Non-option arguments:
plugin id

Option         Description
------         -----------
-b, --batch    Enable batch mode explicitly,
                 automatic confirmation of security
                 permission
-h, --help     show help
-s, --silent   show minimal output
-v, --verbose  show verbose output
```

**Comment by jasontedor** [comment]
> Might get hard to maintain possibly, but start with the officially supported plugins should be fine.

For exactly this reason I do no think that we will ever add non-official plugins here.

> A further feature could be also listing all available versions of a plugin

The official plugins are always version-locked to the version of Elasticsearch.

**Comment by geekpete** [comment]
Perfect!

Thanks.
