### ISSUE TITLE
Reindex API dedicated pool?

### ISSUE THREAD

**Issue by jrots** [elastic/elasticsearch#18059]
I'm using the reindex api to create a daily new index, that's optimised to only contain certain docs etc.
There are crons running every hour that could increase the amount of searches and if the reindex is running in the meanwhile it would abort whenever the search thread pool capacity is reached : 

```
	curl -XPOST "http://elastic26:9200/_reindex?wait_for_completion=true" -d '
			 {
			    "conflicts": "proceed",
				"source" : {
					"index": "prod_users_v5",
					"type": "person",
					"query" : { "constant_score" : { "query" : { "bool" : { "filter" : [ { "term" : { "accountstatus" : "active" } }, { "range" : { "lastlogindate" : { "gte" : "2015-04-29 02:00", "lte" : "2016-04-29 02:00" } } }, { "range" : { "birthdate" : { "gte" : "1989-04-29", "lte" : "1993-04-29" } } } ] } } } }
				},
				"dest": {
					"index": "prod_users_v1611902_last_year",
					"op_type" : "create"
				}
			}' 2>/dev/null
```
```
{"took":984897,"timed_out":false,"total":2451467,"updated":0,"created":730574,"batches":7315,"version_conflicts":926,"noops":0,"retries":0,"failures":[{"shard":-1,"index":null,"reason":{"type":"es_rejected_execution_exception","reason":"rejected execution of org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler@4f66670b on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@5eab79c7[Running, pool size = 49, active threads = 49, queued tasks = 1000, completed tasks = 1351110446]]
```

resulting in a "semi completed" state at the end, 
I know it's not good to have a full search queue.. but I rather have a few searches failing then a reindex process that aborts, 
can't there be dedicated queue for reindex?

**Comment by nik9000** [comment]
> can't there be dedicated queue for reindex?

It is possible but I think that'd be difficult. Reindex already has logic to backoff and retry when the bulk queue is full. Applying that logic to the search and scroll portions would be much simpler by comparison and ought to work for this. Would you mind if I repurposed this issue to track that?

**Comment by jrots** [comment]
Sure, retry logic for searches sounds good too 
Think also having the ability to bump the search/ scroll limit to f.e. 15000 instead of default 100 would help avoiding having these issues.
