### ISSUE TITLE
Backwards compatibility tests for 5.0

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#18065]
**Describe the feature**:
The 2.x branch has a bunch of backwards compatibility tests and we need to examine each one and decide if we need to port it to the master branch (and then 5.x branch, if we've cut such a branch before doing this issue.)

Many of them just want to run features against a mixed version cluster. We should get good enough coverage for those by running all the REST tests. Right now we run the core REST tests. I think all we have to do is run all the plugin REST tests for those tests.

Others assert that things work **during** a rolling restart. Those are going to be harder to port.

**Comment by clintongormley** [comment]
Closing in favour of #14406

**Comment by s1monw** [comment]
do we wanna close this @clintongormley @nik9000
