### ISSUE TITLE
BWC tests for Logstash/Beats

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#18061]
Users need to be able to upgrade Elasticsearch to the next major version before they upgrade Logstash/Beats.  In other words, we need to provide bwc for:

* the `bulk` API
* index templates
* the index APIs used by these projects

We should add tests to confirm that this upgrade process continues to work.

**Comment by clintongormley** [comment]
Related to https://github.com/elastic/elasticsearch/issues/17275

**Comment by s1monw** [comment]
with https://github.com/elastic/elasticsearch/pull/20491 committed I think we can remove the blocker label here or maybe even close?
