### ISSUE TITLE
String with index:false results in keyword with index:true

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#18062]
Putting this mapping:

    PUT t 
    {
      "mappings": {
        "t": {
          "properties": {
            "foo": {
              "type": "string",
              "index": false
            }
          }
        }
      }
    }

Results in:

    {
      "t": {
        "mappings": {
          "t": {
            "properties": {
              "foo": {
                "type": "keyword"
              }
            }
          }
        }
      }
    }

**Comment by jpountz** [comment]
I suspect the parser gets confused by the fact that it mixes new/old syntax (`index:false` instead of `index:no` on a legacy `string` field).

**Comment by jpountz** [comment]
What is the expected behaviour? I think it should throw an error?

**Comment by clintongormley** [comment]
I'm ok with throwing the error, as at least it doesn't fail silently.  The alternative would probably be more complex
