### ISSUE TITLE
plugin-descriptor.properties error for offline installation of Marvel

### ISSUE THREAD

**Issue by jasonmclose** [elastic/elasticsearch#18070]
Installed new ES version 2.3.2, and installed the license and marvel-agent plugins according to the offline installation instructions located [here](https://www.elastic.co/guide/en/marvel/current/installing-marvel.html#offline-installation)

Received the following error:

```
/opt/elasticsearch/bin$ ./plugin install file:///home/user/marvel-2.3.2.tar.gz 
-> Installing from file:/home/user/marvel-2.3.2.tar.gz...
Trying file:/home/user/marvel-2.3.2.tar.gz ...
Downloading ................DONE
Verifying file:/home/user/marvel-2.3.2.tar.gz checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

```

And FYI, I am only doing this offline because the Marvel build is missing the zip file location.  When you run 
`./bin/plugin install marvel`
An error shows up, because the zip file does not exist on the ES server.  Something is wrong with the build.

**Elasticsearch version**: 2.3.2

**JVM version**: 1.7.0_91

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**: Marvel plugin will not install online or offline

**Steps to reproduce**:
 1. Try plugin install marvel
 2. Try to install offline with the tar.gz file using plugin install file:///path/to/marvel-2.3.2.tar.gz
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by rjernst** [comment]
I think you have the steps mixed up, marvel is a kibana plugin, not elasticsearch.  You should be installing marvel-agent.

> When you run `./bin/plugin install marvel` An error shows up

Again, marvel is not a plugin for elasticsearch, it is called marvel-agent. And the instructions you link use file installation, not name based installation, so I'm not sure where the confusion came from?

**Comment by jasonmclose** [comment]
You are absolutely correct.  Sorry for the trouble.  Thanks for catching that.
