### ISSUE TITLE
TermsQueryBuilderTests.testToQuery CI Failure due to rewritten TermsLookup Query

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#18071]
Test failure replicates for me with:

```
gradle :core:test -Dtests.seed=84A9BC00947C2198 -Dtests.class=org.elasticsearch.index.query.TermsQueryBuilderTests -Dtests.method="testToQuery" -Des.logger.level=WARN -Dtests.security.manager=true -Dtests.locale=bg-BG -Dtests.timezone=Europe/Kiev
```

Several related failures:

- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=amazon/342/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=fedora/342/console

It looks like the test is generating a TermsLookup query:

```json
{
  "terms" : {
    "TofcQn" : {
      "type" : "UJdzjobcpF",
      "id" : "bHARfpgRnh",
      "path" : "PFQXDKsBkU",
      "routing" : "bELufARfhy"
    },
    "boost" : 0.13333334,
    "_name" : "dkTVvamG0"
  }
}
```

But it get's rewritten into a MatchNoDocs query:

```
(MatchNoDocsQuery["No terms supplied for "terms" query."])^0.13333334
```

This causes the test to fail, because the test sees that `termslookup() != null`, so it skips past the check for MatchNoDocs and fails because the query is not actually a BooleanQuery

```java
if (queryBuilder.termsLookup() == null && (queryBuilder.values() == null || queryBuilder.values().isEmpty())) {
    assertThat(query, instanceOf(MatchNoDocsQuery.class));
} else {
    assertThat(query, instanceOf(BooleanQuery.class));
     ....
```

It feels like a test error, but I wasn't sure if the correct fix is to just change the conditional here, or something else.  I dont' quite understand how the lookup process happens in relation to rewrites. 

/cc @jimferenczi @MaineC @cbuescher  since you all worked on MatchNoDocs recently.

**Comment by cbuescher** [comment]
I found the problem and will push the corrected test shortly.
