### ISSUE TITLE
ES 5 wont start with config setting index.number_of_shards

### ISSUE THREAD

**Issue by mubinn** [elastic/elasticsearch#18073]
ES 5.0.0 apha1 fails to start with  setting "index.number_of_shards: 1" in elasticsearch.yml. However, same config file for version elasticsearch-2.2.0 and elasticsearch-2.3.2 works fine.

As per documentation in Configuration section it says it should work
https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html
"Index level settings can be set on the node level as well, for example, within the elasticsearch.yml file...."

Exception in log file:
curl -XPUT 'http://localhost:9200/_all/_settings?preserve_existing=true' -d '{
  "index.number_of_shards" : "1"
}'
*************************************************************************************

[2016-04-29 16:13:59,193][ERROR][bootstrap                ] Exception
java.lang.IllegalArgumentException: node settings must not contain any index level settings
	at org.elasticsearch.common.settings.SettingsModule.configure(SettingsModule.java:113)
	at org.elasticsearch.common.inject.AbstractModule.configure(AbstractModule.java:60)
	at org.elasticsearch.common.inject.spi.Elements$RecordingBinder.install(Elements.java:233)
	at org.elasticsearch.common.inject.spi.Elements.getElements(Elements.java:103)
	at org.elasticsearch.common.inject.InjectorShell$Builder.build(InjectorShell.java:148)
	at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:99)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:46)
	at org.elasticsearch.node.Node.<init>(Node.java:229)
	at org.elasticsearch.node.Node.<init>(Node.java:161)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:189)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:263)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:111)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:106)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:88)
	at org.elasticsearch.cli.Command.main(Command.java:53)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:74)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)

Issue found on:
Elasticsearch version: elasticsearch-5.0.0-alpha1
OS version: Windows 10
Java version 1.8.0_77

**Comment by rjernst** [comment]
The exception message tells you the problem. Index settings can no longer be set through `elasticsearch.yml`. You need to actually set these in your index (or indirectly by creating indexes with templates).

**Comment by clintongormley** [comment]
The error message in 5.0.0-alpha2 is much nicer and tells you exactly what needs doing:

    *************************************************************************************
    Found index level settings on node level configuration.

    Since elasticsearch 5.x index level settings can NOT be set on the nodes
    configuration like the elasticsearch.yaml, in system properties or command line
    arguments.In order to upgrade all indices the settings must be updated via the
    /${index}/_settings API. Unless all settings are dynamic all indices must be closed
    in order to apply the upgradeIndices created in the future should use index templates
    to set default values.

    Please ensure all required values are updated on all indices by executing:

    curl -XPUT 'http://localhost:9200/_all/_settings?preserve_existing=true' -d '{
      "index.number_of_shards" : "3"
    }'
    *************************************************************************************

**Comment by t3chn0m4g3** [comment]
Could you please clarify why that is the case? What are the pros / cons?

**Comment by mitchswaldman** [comment]
Is there a new file to declare index level settings in? Or must you update each index's settings through an API call?

**Comment by jasontedor** [comment]
> Is there a new file to declare index level settings in? Or must you update each index's settings through an API call?

You can use [index templates](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-templates.html).

**Comment by mitchswaldman** [comment]
@jasontedor  I'm actually having a little bit of an issue with my index templates in 5.0.0-alpha3. #19163 Maybe you can help me out with that too ;)

**Comment by jasontedor** [comment]
> Maybe you can help me out with that too ;)

It's likely that someone else will get to it before I have a chance to.

**Comment by s1monw** [comment]
> Could you please clarify why that is the case? What are the pros / cons?

sure - lemme iterate some of the points:

 * the yaml file is for node level configurations. The settings can be different from node to node ie. if a node has more CPU than another you might want different settings on the threadpool or you have repository configured or you have some nodes with more than one disk etc.
 * all settings that start with `index.` are index level setting and must be configured in a way that whatever node is the master when the index is created the result is the same. We can't guarantee this with node level settings. (yet there is one exception `index.codec` since this is really a node level setting in the way it's used)
 * our construct to set defaults for an index are index templates that can hold default configurations, supporting this on the yaml file is yet another source of defaults which causes a bigger level of complexity since all these settings must be consequently merged together. 
 * not allowing these settings in a yaml file reduces the chance of inconsistent configuration - this is now also guaranteed for users not useing a package manager (you would be suprised!!)
 * using templates streamlines the way default settings are passed to ES
 * also there are way less surprises, lets say you create an index with a template and the template sets `index.number_of_replicas: 2` but in your yaml you have `index.number_of_replicas: 0` the latter will never have any effect since templates are superseding node configurations. 

> Is there a new file to declare index level settings in? Or must you update each index's settings through an API call?

you can user templates for this so it's a single API call and it's persistent across restarts. You don't need to update existing indices since the settings in the yaml file are just defaults.

**Comment by t3chn0m4g3** [comment]
@s1monw Thank you for sharing a much appreciated and detailed answer!
I think it makes a lot of sense, however for me it complicates things. I am using an ELK stack within a docker container, storing all information outside the container on the host. Is there any best practice on how to tell elasticsearch to use `index.number_of_shards: 1` and `index.number_of_replicas: 0`? I could use the `curl` method of course, but I can only do so after the image is built and the container is running on the host; resulting in Xputting the settings at every container start.
Maybe I am just blindsided and you see a different approach?

**Comment by s1monw** [comment]
no you have to set this through an index template. I am sorry that this complicates things for you but there is no way to preset index values on a node level anymore.

**Comment by t3chn0m4g3** [comment]
Thanks for the update. I have not worked with templates yet. Can you link a good starting point / how to?

**Comment by s1monw** [comment]
@t3chn0m4g3 here you go https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html

the template is stored in the cluster state and that is persistent. If you do this:

1. start node
2. put template with `index.number_of_replicas=0`
3. stop node
4. start node
5. create index 

the index will have `0` replicas, maybe that simplifies your scenario? The good thing is if that node joins a cluster it gets the right templates form the cluster instead.

**Comment by t3chn0m4g3** [comment]
Thank you!

**Comment by forewarned** [comment]
If we have to apply settings on an index level, is there a default template somewhere for documents that do not already match a template in Elastic? If so, how do we access and modify it?

**Comment by clintongormley** [comment]
You can create a template which matches `*`

**Comment by zhangtanzhang** [comment]
index.analysis.analyzer.default: "analyzer-ik" ，how to configer it in elasticsearch.yml

**Comment by zhangtanzhang** [comment]
thank  you

**Comment by bleskes** [comment]
@zhangtanzhang see message above:

> Index settings can no longer be set through elasticsearch.yml. You need to actually set these in your index (or indirectly by creating indexes with templates).

If you have any more questions please ask at discuss.elastic.co . We keep github for issues and feature requests. thx!

**Comment by DimDroll** [comment]
By going through documentation here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html
I've noticed that you can set number_of_replicas in there as well, quote:
> The REST endpoint is **/_settings (to update all indices)** or {index}/_settings to update one (or more) indices settings. The body of the request includes the updated settings, for example:
```
PUT /twitter/_settings
{
    "index" : {
        "number_of_replicas" : 2
    }
}
```

However when I do the same for global settings:
```
curl -XPUT http://localhost:9201/_settings -d '{
  "index": {
    "number_of_replicas": 0
  }
}'
```
I got:
> {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"_all"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_expression","resource.id":"_all"},"status":404}

So I have to use templates. Am I missing something or documentation is a bit outdated there?

**Comment by clintongormley** [comment]
> p.s. there are no indices in the aforequeried stand-alone server

You are misunderstanding.  The `PUT _settings` form applies to all existing indices, it doesn't change defaults anywhere.  For that you need to use templates

**Comment by jasontedor** [comment]
> Imo this isn't made clear anywhere, and there doesn't seem to be a simple way of updating a single setting anymore?

Templates overwrite indeed, and this has always been the behavior.

> Maybe the easiest way is to GET the current template, change the settings you like and then PUT back the template.

Yup, you figured it out!

**Comment by rrader** [comment]
It would be really useful if there was a way to configure the default template via file and not REST - for quick start of some applications in kubernetes for example
