### ISSUE TITLE
TransportClient "Could not initialize class" Exception in Google Cloud Yarn cluster.

### ISSUE THREAD

**Issue by random-thoughts** [elastic/elasticsearch#18083]
**Elasticsearch version**:2.2.0

**JVM version**:penjdk version "1.8.0_72-internal"

**OS version**:Debian 3.16.7

**Description of the problem including expected versus actual behavior**:
I am using Spark on Google Cloud, and I need to get data from an ElasticSearch database. I am  using the following code to connect to ElasticSearch

     import org.elasticsearch.action.search.SearchResponse;
     import org.elasticsearch.client.transport.TransportClient;
     import org.elasticsearch.common.settings.Settings;
     import org.elasticsearch.common.transport.InetSocketTransportAddress;
     import org.elasticsearch.index.query.QueryBuilders;
     import org.elasticsearch.search.SearchHit;

     public  TransportClient openConnection(String ipAddress, int ipPort) throws UnknownHostException {

        Settings settings = Settings.settingsBuilder().put("cluster.name", "elasticsearch").build();
        TransportClient client = TransportClient.builder().settings(settings).build().
                addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName(ipAddress), ipPort));

        return client;

    }

When I run it locally, i.e. `spark-submit --master local[*]` everything runs OK. When I run it in a google cloud spark cluster I get the following Exception: 

     java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.threadpool.ThreadPool at 
    org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:133) at 
    javaTools.ElasticSearchConnection.openConnection(ElasticSearchConnection.java:24)

The last referred method (`openConnection`) is the connection described above. 

The code is uploaded to the google cloud using a fat jar created using sbt asssembly, so all libraries used are common.

**Comment by bhdrk** [comment]
+1

**Comment by ryandonglin** [comment]
also met the same problem in my project, Some people said because of lacking guava dependency, but after import the guava repository, still the same problem

**Comment by ryandonglin** [comment]
already solve the problem, just import guava-18.0 dependency to your project, hete is the pom:

<dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>18.0</version>
        </dependency>

**Comment by clintongormley** [comment]
thanks for letting us know @ryandonglin

**Comment by bjkonglu** [comment]
I also met the same question in my project.But I already import guava-18.0 dependency in my project.here is my pom:
```
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>${guava.version}</version>
</dependency>
```
In my cluster, I replace spark-lib's guava-14.0.1 jar with guava-18.0. Then it worked. But I wonder there will some potential question in this action? some one can tell me , please!

Note: 
- spark:2.1.1
- elasticsearch:2.4.1
