### ISSUE TITLE
Can't set dates to null

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#18085]
PUT t 
    {
      "mappings": {
        "t": {
          "properties": {
            "date": {
              "type": "date"
            }
          }
        }
      }
    }
    
    PUT t/t/1
    {
      "date": null
    }
    
Returns:

    {
      "error": {
        "root_cause": [
          {
            "type": "mapper_parsing_exception",
            "reason": "failed to parse [date]"
          }
        ],
        "type": "mapper_parsing_exception",
        "reason": "failed to parse [date]",
        "caused_by": {
          "type": "illegal_state_exception",
          "reason": "Can't get text on a VALUE_NULL at 2:11"
        }
      },
      "status": 400
    }

**Comment by nikoncode** [comment]
Not reproduces in 5.0.0-alpha1 release.

**Comment by jpountz** [comment]
@nikoncode indeed, this is related to a change that only made it to alpha2
