### ISSUE TITLE
jQuery library does not work when minified. 

### ISSUE THREAD

**Issue by nasht00** [elastic/elasticsearch#18081]
When using **elasticsearch.jquery.js**, everything works fine.

When using **elasticsearch.jquery.min.js** I get the following errors:

![screen shot 2016-05-02 at 10 11 31 am](https://cloud.githubusercontent.com/assets/329834/14948938/5035c078-104e-11e6-9d5a-41f7bb8b5a7d.png)

**Comment by dadoonet** [comment]
I think that you should report that here: https://github.com/elastic/elasticsearch-js

**Comment by nasht00** [comment]
I think they already opened it: https://github.com/elastic/elasticsearch-js/issues/369
