### ISSUE TITLE
Enhance even more the ignore_above settings documentation

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#18086]
Just a suggestion, we can add more information on how the `ignore_above` settings works. It is much better now how it explains the way to work with it, but i would enhance this in order to add even more information about searching:

The analyzer will ignore strings (tokens from analyzed strings or entire single-token non-analyzed strings) larger than this size, storing them in the document but making them non-searchable, if they are longer than this parameter. For example, if ignore_above is set to 5, then the non-analyzed string or token output from an analyzed string “12345” would be searchable for exact match and for partial matches using the regex operator or the glob match, but “123456” would not be searchable.

**Comment by clintongormley** [comment]
@gmoskovicz the `ignore_above` setting is not accepted by the new `text` field type, so it has nothing to do with analysis any more.

This page (https://www.elastic.co/guide/en/elasticsearch/reference/master/ignore-above.html) gives a full example of how `ignore_above` works, which I think covers the rest of the info you mention
