### ISSUE TITLE
`gradle eclipse` should set `-ea` if possible

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#18087]
Eclipse has a flag that enabled `-ea` when it sets up any tests. Elasticsearch's tests fail immediately if they aren't run with `-ea`. So `gradle eclipse` should set that flag if at all possible. It is kind of a mystery to me what `gradle eclipse` is allowed to set but it is worth looking into. At a minimum we need something in CONTRIBUTING.md about it.

**Comment by dadoonet** [comment]
Similar to #15076

**Comment by jasontedor** [comment]
> At a minimum we need something in CONTRIBUTING.md about it.

Setting this is not possible for IntelliJ with Gradle so I think that the most straightforward approach here is a simple note in the CONTRIBUTING.md about how this is a required setting if developers want to run tests inside their IDE. I opened #18087.
