### ISSUE TITLE
Refering to neighbor function score for further calculation?

### ISSUE THREAD

**Issue by RobGThai** [elastic/elasticsearch#18084]
**Describe the feature**:

When using Function score. Should we be able to name the function then use the function result in other functions.

For example, 

I have one function which perform a calculation using document fields. With that calculation, I want to use the result to determine two different values. Without ability to refer to calculated function, I have to do the same calculation twice to get the result.

Plus, naming thing seems to be a standard way for Elasticsearch structured it's query. Why having it differently for function score?

**Comment by clintongormley** [comment]
Hi @RobGThai 

Your description is somewhat fuzzy - there are some things we can support and some we can't.  eg we have this issue https://github.com/elastic/elasticsearch/issues/17116 open to support naming scripts which can then be used together to calculate a score.

however, storing the value from functions score scripts to be returned later on with hits is a no-go.  We could potentially have to cache billions of calculations just to return 10 of them.

Closing in favour of https://github.com/elastic/elasticsearch/issues/17116
