### ISSUE TITLE
String Column Aggregation Will Stops Working Elasticsearch-2.3.2

### ISSUE THREAD

**Issue by ervivekmehta** [elastic/elasticsearch#18080]
**Elasticsearch version**: 2.3.2

**JVM version**: 1.8

**OS version**: Cent OS

**Description of the problem including expected versus actual behavior** AND **Steps to reproduce**: 
actually we have one large application and in that the indexing always going on around min 500-1000 logs per second, and we have our defined syntax for users to execute searching in elasticsearch. 
    But now we have one biggest issue after elastic version 2.3.2 that while indexing is going on and our user try to get aggregation on data like sum, min, max etc.. on that time customer doesn't know that the column is string or numeric so. Elasticsearch throws Error (SERVER_ERROR) that need numeric field but found string field. 
   In this case Elasticsearch is right and scenario is perfect but after this happens more then two times Elasticsearch stop working It's not even responding in any plugin. It's also not even give status by http://localhost:9200  so Please resolve my problem and reply me as soon as possible.

We have very big work with Elasticsearch and then we stuck over here.

**Comment by jasontedor** [comment]
This looks like a general question more than it does a bug report in Elasticsearch. Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions.

**Comment by ervivekmehta** [comment]
Brother I know Issues are only going to post over here. And this is seriously biggest issue for us. Elasticsearch stop working after this aggregation Exception occurs.
[: Expected numeric type on field [severity], but got [string]]

You must dig in to this brother. It is a bug. I think Elasticsearch throw and error it's a perfect way but it's stop working after throwing this exception, I think this bug must be resolved bro. because from client side we cant even able to predict that which column client will select for aggregation. and if any other way then please post here or we can communicate through mail.

**Comment by nik9000** [comment]
It is kind of the client responsibility not to send bogus aggregations. Elasticsearch should certainly reply with 400-level responses when it does which does sound like a bug but ultimately you are responsible for understanding the schema of your data. You can have the client look at the mappings before giving the user the list of things they can aggregate on. https://github.com/elastic/elasticsearch/pull/17980 also should help with that in 5.0 too.
