### ISSUE TITLE
Inner Hits sometimes missing "_index" key

### ISSUE THREAD

**Issue by mattweber** [elastic/elasticsearch#18091]
**Elasticsearch version**: 2.2.0

**JVM version**: Oracle Corporation 1.8.0_45 (64-bit)

**OS version**:  Mac OS X 10.11.4 x86_64

**Description of the problem including expected versus actual behavior**:

I am running tests using your integration test framework (`ESIntegTestCase`), however, I am only using it to setup a cluster and index some documents.  I have it configured so the http is enabled on a random port, and then I use the rest api for my tests.  

I am currently running a test that uses the inner hits functionality and I have found that one of my asserts on the index name of an inner hit fails.  After inspecting the json response, I can see that the _index key on the inner hit is missing.  Every time it fails it looks like the test framework has sets a test locale that result in non-english text in the logs.  I don't know if that has anything to do with it or not, however, this is the only consistent thing I have noticed.

The inner hits are only against nested documents and the request that fails has multiple levels of nested objects.  All levels of the nested response are missing the _index key.  My search request is only using the top-level inner hits request structure since I need multiple levels of inner hits.

I know there has been changes to inner hits lately so I am not sure this is even relevant in versions greater than 2.2. 

**Provide logs (if relevant)**:  

https://gist.github.com/mattweber/614e45ce0ab9a0487400fa69400a4131

**Comment by clintongormley** [comment]
@martijnvg could you take a look at this please?

@mattweber any chance you could add the test you're running?

**Comment by mattweber** [comment]
@clintongormley It has some code that belongs to a client I am working with so I can't post it directly.  I will work on writing an isolated test that essentially does the same thing though.

**Comment by mattweber** [comment]
@clintongormley @martijnvg 

https://gist.github.com/mattweber/19c37d9b8a01fd305afa782bc38f9d2f

Here is a quick and dirty test.  Add this file as `core/src/test/java/org/elasticsearch/search/innerhits/InnerHitsIssueIT.java` to a checkout of the 2.2 branch.  The test failure reproduces for me consistently with:

`mvn clean verify -Pdev -Dskip.unit.tests -pl org.elasticsearch:elasticsearch -Dtests.seed=C293056A17C37DCE -Dtests.class=org.elasticsearch.search.innerhits.InnerHitsIssueIT -Dtests.method="testIssue18091" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=sv_SE -Dtests.timezone=Portugal`

**Comment by clintongormley** [comment]
thanks @mattweber

**Comment by mattweber** [comment]
Reproducible against `2.x` with following:

`mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch:elasticsearch -Dtests.seed=7AA0546C9A7151D7 -Dtests.class=org.elasticsearch.search.innerhits.InnerHitsIssueIT -Dtests.method="testIssue18091" -Des.logger.level=ERROR -Dtests.assertion.disabled=false -Dtests.security.manager=true -Dtests.heap.size=512m -Dtests.locale=mk -Dtests.timezone=Etc/GMT+9`

**Comment by mattweber** [comment]
Also reproducible against current master (5.x) using the new multi-level inner hit functionality inside of the nested queries vs. a top-level request. 

Here is the test for master:
https://gist.github.com/mattweber/578c77e1c5f148e13a3a9c238d169fea

Here is my reproduce command:
`gradle :core:integTest -Dtests.seed=98F2AB350B0F5BF2 -Dtests.class=org.elasticsearch.search.innerhits.InnerHitsIssueIT -Dtests.method="testIssue18091" -Des.logger.level=WARN -Dtests.security.manager=true -Dtests.locale=zh-CN -Dtests.timezone=Etc/GMT-8`

Note, I run this test in a loop until it fails.  It usually takes less than 5 runs before I hit the failure.

**Comment by martijnvg** [comment]
@mattweber @clintongormley If I recall correctly during node to node serialization the `_index` key was not included for nested inner hits, since it isn't really needed, because the `_index` key is always the same as the parent search hit. The inconsistency here is that when search hits aren't serialized then the `_index` key is included. (which happens in test with a single node)

I think the inconsistency should be fixed or the `_index` key should always be included in inner hits.

**Comment by mattweber** [comment]
Thanks @martijnvg!  Is index/type/id even needed here?  It will always be the same as the parent document right?  Plus we have the `_nested` object that gives us the offsets inside source nested array.

**Comment by martijnvg** [comment]
@mattweber I agree. index/type/id are not needed for nested inner hits.
