### ISSUE TITLE
Elasticsearch Integration Test Never Finishes

### ISSUE THREAD

**Issue by winstonewert** [elastic/elasticsearch#18098]
**Elasticsearch version**: Works on 2.1.2 fails on 2.2.0 and later

**JVM version**: 1.8

**OS version**: Ubuntu 15.10

**Description of the problem including expected versus actual behavior**: Test never finishes. The actual body of the test run normally, but appears to infinitely wait for something to shutdown.

**Steps to reproduce**:
 1. git clone git@github.com:winstonewert/broken-es-test.git
 2. cd broken-es-test
 3. ./gradlew test

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by winstonewert** [comment]
This is a bug report. An empty subclass of ESIntegTestCase doesn't terminate after a certain release of elasticsearch. That seems like a bug to me. 

If you insist I can take it to the form, but I'm pretty sure this is a bug.

**Comment by jasontedor** [comment]
> If you insist I can take it to the form, but I'm pretty sure this is a bug.

Since our tests run, I don't think there's a bug here but rather an issue with how you've set up your build.

**Comment by winstonewert** [comment]
Updating this issue in case someone ends up here from Google trying to track down the same issue.

Elasticsearch 2.2.0 started enabling a security manager by default which breaks gradle's test runner. 

See: https://issues.gradle.org/browse/GRADLE-2170, which has a workaround.
