### ISSUE TITLE
Provide an option to skip score explanation computation for explain api

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#18095]
**Describe the feature**:  

The explain api is not only useful for score explanations, but it also provides debugging information on what node(s)/shards(s) were used when returning documents for a request.  It will be nice to provide an option to skip the score explanation computation for those who are only interested in the node/shard information.

**Comment by jasontedor** [comment]
The main point of the explain API is to provide scoring. However, scoring is calculated locally to a shard (because of how IDF is computed unless using `dfs_query_then_fetch`) so showing the shard is important. But I'm generally not sure how valuable it is to know what shard handled a request outside the context of scoring? I'm -1 on adding this.

**Comment by ppf2** [comment]
Sometimes, we use the explain api as one of the tools to determine if a query causing hotspots is due to an unbalanced number of documents being routed to specific shards when not using the default routing.  And it is also useful for confirming if search preference options and things like prefer-local-shards for shard allocation awareness are working.

**Comment by jasontedor** [comment]
> Sometimes, we use the explain api as one of the tools to determine if a query causing hotspots is due to an unbalanced number of documents being routed to specific shards when not using the default routing. 

This is done more appropriately with the count API:

```bash
POST /_count?routing=custom_routing
{
  "query": {
    .
    .
    .
  }
}
```

> And it is also useful for confirming if search preference options and things like prefer-local-shards for shard allocation awareness are working.

We have unit tests to validate this. I don't think we should add features to Elasticsearch to validate other features of Elasticsearch.

**Comment by ppf2** [comment]
ok fair enough :)
