### ISSUE TITLE
Circuit Breaker Settings are not working 

### ISSUE THREAD

**Issue by adhamelia** [elastic/elasticsearch#18105]
**Elasticsearch version**: 2.3.1

**JVM version**: 1.8

**OS version**: Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: 

we have applied the following settings to prevent OOM error.

none the settings are working, it was working for ES 1.7 but not 2.3.1

even, we tried indices.breaker.request.limit : 10% but no luck.

indices.fielddata.cache.size:  30%

index.cache.field.type: soft

indices.memory.index_buffer_size: 30%

indices.breaker.request.limit : 60%

**Steps to reproduce**:
 1. open elasticsearch.yml
 2. add the following block
 indices.fielddata.cache.size:  30%

index.cache.field.type: soft

indices.memory.index_buffer_size: 30%

indices.breaker.request.limit : 60%
 
3. try to execute a big query to test circuit breaker settings 

**Provide logs (if relevant)**:

**Comment by clintongormley** [comment]
For a start, 30% + 30% + 60% = 120% of heap, never mind all the other data that needs to fit into the same heap.  Second, why are you using so much fielddata on 2.3?  You should be using almost entirely doc values.  Third, soft caches are no longer supported.

I'm not sure why you're changing these settings from the defaults, but you should really understand what you're doing before making changes like this.  I suggest asking questions like these in the forum instead: https://discuss.elastic.co/

**Comment by adhamelia** [comment]
thanks we figured out

**Comment by bkandanoor** [comment]
what was the issue why circuit breaker was not working which you figured it out. i am having hte same issue where i am trying to test the circuit breaker and it does not do anything.
