### ISSUE TITLE
Sort by numeric distance

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#18111]
Today, I'm able to define a point (lat, lon) and sort my documents based on the distance from this point. This is super handy.

[Someone asked for a similar feature](http://stackoverflow.com/questions/37005785/how-to-find-the-nearest-closest-number-using-query-dsl-in-elasticsearch) but for numerical values.

For example, let say I want to find a product and sort it by the closest price I set.

Obviously as explained [here](http://stackoverflow.com/a/37006104/1432281) you could use a script for that but I think that it would be nice if can support a similar feature out of the box.

Something like:

```js
{
    "sort" : [
        {
            "_distance" : {
                "price" : 10.0,
                "order" : "asc"
            }
        }
    ]
}
```

WDYT?

**Comment by litong01** [comment]
@dadoonet I think that will be a very nice feature.

**Comment by clintongormley** [comment]
Honestly, this is so easy to do with a script (including a Lucene expression script, which is really fast) that I don't see the point, especially given that this is not a common need.

    POST t/t/_bulk
    {"index": {}}
    { "num": 1 }
    {"index": {}}
    { "num": 2 }
    {"index": {}}
    { "num": 3 }
    {"index": {}}
    { "num": 4 }
    {"index": {}}
    { "num": 5 }
    {"index": {}}
    { "num": 6 }
    
    GET t/_search
    {
      "sort": {
        "_script": {
          "type": "number",
          "order": "asc",
          "script": {
            "inline": "abs(target - doc['num'])",
            "lang": "expression",
            "params": {
              "target": 3
            }
          }
        }
      }
    }

**Comment by litong01** [comment]
will it become more complex when queries are nested? like in aggregation?
