### ISSUE TITLE
Build Failure: org.elasticsearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT.testScriptScore

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#18120]
Unable to replicate, but I do not have a Windows machine for testing.

REPRODUCE WITH: gradle :core:integTest -Dtests.seed=4DA46F7D8DF8CF05 -Dtests.class=org.elasticsearch.search.aggregations.bucket.SignificantTermsSignificanceScoreIT -Dtests.method="testScriptScore" -Des.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=1024m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:-UseCompressedOops -XX:+AggressiveOpts" -Dtests.locale=sr-Latn-RS -Dtests.timezone=Asia/Chongqing

Build Failure: (http://build-us-00.elastic.co/job/es_core_master_window-2008/3699/testReport/junit/org.elasticsearch.search.aggregations.bucket/SignificantTermsSignificanceScoreIT/testScriptScore/)

**Comment by markharwood** [comment]
Ditto - wouldn't replicate on OSX here. Any chance of a quick Windows test @costin ?

**Comment by javanna** [comment]
This fails around 3/4 times a month in our CI. @jpountz pushed https://github.com/elastic/elasticsearch/commit/cad959b to ease debugging which fields are null.

It does not only fail on Windows. 

As far as I can see the null field is not always the same: I've seen `_superset_size` being null, and also  `_subset_freq`. Here is the latest failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/1601/console .

@markharwood would you mind taking another look? maybe @colings86 would like to check as well?

**Comment by clintongormley** [comment]
@markharwood is this still a problem?

**Comment by markharwood** [comment]
I've not seen any examples of failures in the available history:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/311/testReport/junit/org.elasticsearch.search.aggregations.bucket/SignificantTermsSignificanceScoreIT/history/?start=25

**Comment by javanna** [comment]
This is still a problem, last failure was two days ago: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/328/console . Still happens a few times a month.

**Comment by markharwood** [comment]
OK, thanks. Will take a look

**Comment by markharwood** [comment]
Could not reproduce with that seed over many iterations.

The debug code that Adrien added shows that the very first parameter it tries to retrieve (subset_freq) is null.
This is also the first of many non-null parameters set in ScriptHeuristic.initialize():

    public void initialize(ExecutableScript executableScript) {
        this.executableScript = executableScript;
        this.executableScript.setNextVar("_subset_freq", subsetDfHolder);
        this.executableScript.setNextVar("_subset_size", subsetSizeHolder);
        this.executableScript.setNextVar("_superset_freq", supersetDfHolder);
        this.executableScript.setNextVar("_superset_size", supersetSizeHolder);
    }

I notice elsewhere that there is a reference to the fact that the test framework can sometimes invoke script.run() before initialization is complete:

    @Override
    public double getScore(long subsetFreq, long subsetSize, long supersetFreq, long supersetSize) {
        if (executableScript == null) {
            //In tests, wehn calling assertSearchResponse(..) the response is streamed one additional time with an arbitrary version, see assertVersionSerializable(..).
            // Now, for version before 1.5.0 the score is computed after streaming the response but for scripts the script does not exists yet.
            // assertSearchResponse() might therefore fail although there is no problem.
            // This should be replaced by an exception in 2.0.
            ESLoggerFactory.getLogger("script heuristic").warn("cannot compute score - script has not been initialized yet.");
            return 0;
        }
        subsetSizeHolder.value = subsetSize;
        supersetSizeHolder.value = supersetSize;
        subsetDfHolder.value = subsetFreq;
        supersetDfHolder.value = supersetFreq;
        return ((Number) executableScript.run()).doubleValue();
    }

If this is possible/acceptable then maybe we should reverse the order of the operations in the initialize method - set the script variables up _and only then_ set this.executableScript to the fully initialized object. Any failure to set the variables properly will result in a null script which when getScore() is called will log the appropriate error message "script has not been initialized yet".

**Comment by colings86** [comment]
I remember talking to @brwe about that warning when she created the script score but I don't remember exactly why we needed it. @brwe do you remember?

**Comment by cbuescher** [comment]
Here's another one: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.0+java9-periodic/367/console

**Comment by markharwood** [comment]
Added what could be a fix in master: https://github.com/elastic/elasticsearch/commit/4a815bf6654b5e271942a62d3f2b0dc04c408de9

Will push to other branches if we conclude that this makes the difference

**Comment by brwe** [comment]
@colings86 I do not remember all of it but believe this was an < 2.0 problem and we should really replace the log message for script = null with an assertion. 
@markharwood I do not think that changing the order is a fix here but also do not fully understand what is going on yet. I will dig.

**Comment by brwe** [comment]
I think the problem is that the ScriptHeuristic object is reused and hence accessed from different threads concurrently. How exactly this happens and if it is a problem of our tests only I cannot say yet because I am struggling to navigate aggregations. Will continue Monday.

**Comment by brwe** [comment]
If a coordinating node routes search requests to local shards they will not be streamed but the same aggregations builder object will be used for each individual shards that the request is executed on. When the aggregation is build significant terms heuristic is reused and hence several shards can end up with the same ScriptHeuristic object and also modify it concurrently. Instead the builders should make a copy and pass these to the aggregators. Hope I got the nomenclature right. I can work on a fix.

**Comment by colings86** [comment]
@brwe that makes sense, we have to do something similar for the Scripted Metric Aggregation

**Comment by brwe** [comment]
One correction to what I wrote above: The script must be be reused either because we set variables in it. We need one instance per shard.
