### ISSUE TITLE
query_phase_execution_exception

### ISSUE THREAD

**Issue by kalwar** [elastic/elasticsearch#18124]
**Elasticsearch version**: 2.3.1

**JVM version**: 1.8

**OS version**: CentOS 6.7

**Description of the problem including expected versus actual behavior**:[query_phase_execution_exception] Result window is too large, from + size must be less than or equal to: [10000] but was [45120]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.

**Comment by jasontedor** [comment]
You specified to large of a result window, the default is 10000. You can increase this with the setting `index.max_result_window`. But large result windows are deadly for your system, that's why this soft limit is in place. Instead you should use the scroll API.
