### ISSUE TITLE
Vagrant Test Failure: qa:vagrant:vagrantFedora22#up

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#18122]
Build:
(https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/344/console)

Failure:
:qa:vagrant:vagrantFedora22#up (Thread[main,5,main]) started.
:qa:vagrant:vagrantFedora22#up
Executing task ':qa:vagrant:vagrantFedora22#up' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Starting process 'command 'vagrant''. Working directory: /var/lib/jenkins/workspace/elastic+elasticsearch+master+packaging-tests/qa/vagrant Command: vagrant up fedora-22 --provision --provider virtualbox
Successfully started process 'command 'vagrant''
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
:qa:vagrant:vagrantFedora22#up FAILED
:qa:vagrant:vagrantFedora22#up (Thread[main,5,main]) completed. Took 50.772 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qa:vagrant:vagrantFedora22#up'.
> Process 'command 'vagrant'' finished with non-zero exit value 1

BUILD FAILED

Total time: 21 mins 5.763 secs
Stopped 0 compiler daemon(s).
* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.
<<<<<<<<<<<< SCRIPT EXECUTION END <<<<<<<<<<<<
DURATION: 1274811ms
STDOUT: 180704 bytes
STDERR: 1069 bytes
WRAPPED PROCESS: FAILURE (1)
BUILD: https://5086a1f436ee16623a447bdf25881bbc.us-east-1.aws.found.io:9243/build-1453259317148/t/20160503184620-1C840FDD
NOTIFYING SLACK
MAILING: dev+build-elasticsearch@e***.co
Build step 'Execute shell' marked build as failure
Sending e-mails to: infra-root+build@elastic.co
Finished: FAILURE

**Comment by clintongormley** [comment]
Closing as old
