### ISSUE TITLE
When searching or creating a document with a fields content with a forward slash followed by a capital F causes a json parse exception

### ISSUE THREAD

**Issue by imranazad** [elastic/elasticsearch#18123]
**Elasticsearch version**: 2.3

**JVM version**:

**OS version**: UBUNTU

**Description of the problem including expected versus actual behavior**:
When running an exact phrase match  or creating a document with a forward slash followed by a capital F causes elastic to throw an exception, however if it is lower cased the query works fine.

**Steps to reproduce**:
 1.
PUT /movies/movie/5
{
    "title": "The God\Father",
    "director": "Francis Ford Coppola",
    "year": 1972,
    "genres": ["Crime", "Drama"]
}

 2.

GET /movies/_search
{
"query": {
  "query_string": {
    "fields" : ["title"],
    "query": "\"The God\Father\""
   }
  }
}

**Comment by jasontedor** [comment]
A character preceded by a single backslash is an escape sequence. For example, `\n` represents a newline. However, `\F` is not a valid escape sequence and that's why you will get a JSON parse exception. The reason that you do not get such an exception with `\f` is due to this being a valid escape sequence representing the form-feed character.

**Comment by imranazad** [comment]
Thank you I'm aware that it's an escape sequence however how would I do an exact phrase match for the \"The God\Father\"" I have tried escaping the back slash with a forward slash like so \"The God\/Father\"" but I'm still not getting any results. Thanks.

**Comment by jasontedor** [comment]
You escape the backslash by adding another backslash: `\\F`. And you probably want a match phrase query:

```
GET /movies/_search
{
  "query": {
    "match_phrase": { "title": "The God\\Father" }
  }
}
```

Please take and further questions to the [Discourse forum](https://discuss.elastic.co) or [IRC channel](https://www.elastic.co/community). Elastic reserves GitHub for bug reports and feature requests.

**Comment by imranazad** [comment]
@jasontedor Thank you. :+1:

**Comment by jasontedor** [comment]
> Thank you. :+1: 

You're welcome.
