### ISSUE TITLE
Incorrect behavior with long index names on some systems

### ISSUE THREAD

**Issue by tzima** [elastic/elasticsearch#18146]
**Elasticsearch version**: 1.7.1

**JVM version**: OpenJDK 1.7.0_91

**OS version**:
* Linux Mint 17 Qiana (based on Ubuntu 14.04)
* kernel 3.13.0-24
* **ext4 filesystem with eCryptfs** (important!)

**Description of the problem including expected versus actual behavior**:
As per #8158, maximal length for index name was changed to 255. When using eCryptfs (and probably some other filesystem-level encryptions), file names that long are not allowed.

When creating an index with name too long for my filesystem, Elasticsearch fails on any try to search this index (because, in fact, it was never created). I would expect it to directly reject the request with index creation.

**Steps to reproduce**:
 1. Configure Elasticsearch so it stores its data in folder encrypted with eCryptfs. It would probably behave the same on any other system where maximal allowed file name is less than 255.
 2. Create index with name of length 255:

        POST /aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
        {
            "number_of_replicas": 0
        }

    This results with:

        {
           "acknowledged": true
        }

 3. Index is now red, even though `number_of_replicas` is set to zero:

        GET /_cat/indices

    Results with:

        red open aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 5 0     

    It's possible to retrieve information about index:

        GET /aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

    Results with:

		{
		   "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa": {
			  "aliases": {},
			  "mappings": {},
			  "settings": {
				 "index": {
				    "creation_date": "1462403349650",
				    "uuid": "LrwgZOXaSPqFlbeBqnsArQ",
				    "number_of_replicas": "0",
				    "number_of_shards": "5",
				    "version": {
				       "created": "1070199"
				    }
				 }
			  },
			  "warmers": {}
		   }
		}

 4. Try to search the index:

		GET /aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/_search

    Results with:

		{
		   "error": "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed]",
		   "status": 503
		}

 5. See that data directory with indices, in fact, doesn't contain the index:

	        $ ls indices # no output

    And yes, it is the correct directory:

        POST /foo
        POST /bar

		$ ls indices/
		bar  foo

What I would consider to be the correct behavior is a response like "Index name is too long." directly to the POST request that tries to create such index. In fact, that's how it responds when index name  exceeds the length of 255:

	POST /aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

Results with:

	{
	   "error": "InvalidIndexNameException[[aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa] Invalid index name [aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa], index name is too long, (256 > 255)]",
		   "status": 400
	}

**Conclusion**:
If it's not possible to create the index directory at hand and verify it succeeded prior to answering to the client, I think a sufficient solution to this would be to make a maximal allowed index name configurable.

BTW: This is not a real-world case. I figured this out by accident when running some tests on my workstation.

**Comment by jasontedor** [comment]
> I think a sufficient solution to this would be to make a maximal allowed index name configurable.

In master, index names are no longer tied to the name of the directory (we've separated name from identity). The directory name is now just a uuid.

I note that you're on 1.7.1. I don't think we will do anything about this in 1.x nor 2.x.

**Comment by tzima** [comment]
> In master, index names are no longer tied to the name of the directory (we've separated name from identity). The directory name is now just a uuid.

That's much better solution!
