### ISSUE TITLE
auto indexing off

### ISSUE THREAD

**Issue by arafay696** [elastic/elasticsearch#18149]
**Elasticsearch version**: 2.1

**JVM version**: latest

**OS version**: windows 8

**Description of the problem including expected versus actual behavior**:

i am creating index using php-client with 6lac of data by reading CSV file with bulk indexing.
I have several issues in it:

1: when i run script from browser and then stop the script even close the browser, request is running on background. how its working? and how can i stop request?
2: After completion of 6 lac, index updating documents automatically and it goes to 12 lac and so on... how can i create documents with unique ID.
3: can i pass multiple parameters to $client->bultk() methods: like $client->bultk($params,$params2....) ;??

my script:
it takes 6lac record and process it.

**$presona_arr = array(
                    'index' => 'amplify4',
                    'type' => 'persona',
                    'body' => array(
                        'persona_email' => $pemail,
                        'company_id' => 18,
                        'date_added' => date("Y-m-d")
                    )
                );
                $response_per = $client->index($presona_arr);
                $persona_insert_id = $response_per['_id'];

                $bulkParamsDemo['body'][] = [
                    'index' => [
                        '_index' => indexName,
                        '_type' => 'demo',
                        '_id' => $i,
                        'routing' => $persona_insert_id
                    ]
                ];
                $bulkParamsDemo['body'][] = array(data);

                $bulkParamsTrans['body'][] = [
                    'index' => [
                        '_index' => indexName,
                        '_type' => 'trans',
                        '_id' => $i,
                        'routing' => $persona_insert_id
                    ]
                ];
                $bulkParamsTrans['body'][] = array(data);

                $bulkParamsGeo['body'][] = [
                    'index' => [
                        '_index' => indexName,
                        '_type' => 'geo',
                        '_id' => $i,
                        'routing' => $persona_insert_id
                    ]
                ];
                $bulkParamsGeo['body'][] = $geoData;

                $bulkParamsPhy['body'][] = [
                    'index' => [
                        '_index' => indexName,
                        '_type' => 'phy',
                        '_id' => $i,
                        'routing' => $persona_insert_id
                    ]
                ];
                $bulkParamsPhy['body'][] = array(data);

                unset($demoData);
                unset($transData);
                unset($geoData);
                unset($phyData);

                $count = $i;
               if ($i % 2800 == 0) {
                    $responses = $client->bulk($bulkParamsDemo);
                     $responses = $client->bulk($bulkParamsTrans);
                  $responses = $client->bulk($bulkParamsGeo);
                 $responses = $client->bulk($bulkParamsPhy);
                // erase the old bulk request
                    $bulkParamsDemo = ['body' => []];
                    $bulkParamsTrans = ['body' => []];
                    $bulkParamsGeo = ['body' => []];
                    $bulkParamsPhy = ['body' => []];

                    // unset the bulk response when you are done to save memory
                    unset($responses);
                }**

**Comment by jasontedor** [comment]
Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) for general questions.
