### ISSUE TITLE
custom discovery ping error handler

### ISSUE THREAD

**Issue by amreshakim** [elastic/elasticsearch#18143]
Export `MasterFaultDetection.retryCount`/`NodeFD.retryCount` as a part of stats or allow injecting a custom `MasterPinger`/`NodeFD` into `MasterFaultDetection`/`NodesFaultDetection`.

I think it is important to monitor ping timeouts proactively instead of relying on ping_timeout and ping_retries configuration settings to kick out a node that stops responding. From my experience if the ping timeout is not a completely isolated hardware/networking issue, it is often an indication of a more fundamental problem which might get only worse by resharding process.

Hence, I think it would be very beneficial to include ping failures/retries as a part of collecting stats. I am aware that it is possible to build your own discovery plugin that would be a copy of the existing zen discovery mechanism + needed changes. However, I think it would be an overkill if one merely wants to collect additional information and do not change the actual behavior of the discovery mechanism.

**Comment by jasontedor** [comment]
The retry counts get reset to zero on every successful reply from a node that is answering a fault detection request but I guess that you mean monitoring when it increases from zero? But then aggregated stats are not what you would want because it doesn't tell you which nodes the master failed to reply to (for `MasterFaultDetection`), and it doesn't tell you which nodes failed to reply to the master (for `NodeFaultDetection`). It also doesn't tell you which side of the partition a node is on (i.e., if the master fails to reply to a node, is it because the master is partitioned away, or is it because the node is partitioned away?). So I question the usefulness of this. I'm especially cautious about adding an endpoint that dives down into the discovery layer (especially since different discovery implementations might not even have a notion of pings). I'm -1 but I await feedback that could convince me otherwise?

**Comment by ashakimov** [comment]
Jason,

Thanks for the reply and I agree it is not easy to make these stats useful. But I hope I don't have to argue about usefulness of having this information proactively.

> I'm especially cautious about adding an endpoint that dives down into the discovery layer (especially since different discovery implementations might not even have a notion of pings)

Agreed w.r.t. exposing specifics of the implementations. How about just a mechanism to register a listener able to subscribe to generic events (similar to ShardBitsetFilterCache)?

**Comment by jasontedor** [comment]
> Thanks for the reply and I agree it is not easy to make these stats useful. But I hope I don't have to argue about usefulness of having this information proactively.

I wouldn't call it an argument as much as a discussion. 😄

But we do need to discuss it because of my thoughts above (and especially since you seem to agree the stats aren't immediately useful), I don't see the point?

> How about just a mechanism to register a listener able to subscribe to generic events (similar to ShardBitsetFilterCache)?

Yeah, that's roughly how we'd do it *if* there is a good reason for doing it.

**Comment by amreshakim** [comment]
Here is why I would love to have an ability to expose ping related stats/events from the discovery module. This is based solely on my experience with using ES 1.7 on AWS.

Kicking a machine out of cluster (and moving shards around as a consequence) is useful only if the issue is completely isolated and has nothing to do with ES itself, e.g., hardware, network. However, in many cases ping failures are just an indication of a bigger problem (CPU spikes, Java GC stalls, OOM), and there is no one-size-fits-it-all policy to handle it. Sometimes, it is enough to shutdown the misbehaving machine but often it requires a more comprehensive involvement. More importantly, moving shards as a reaction is (1) already too late and (2) will most likely aggravate the problem. I believe, human would be in a much better position to make an appropriate action to such failures and minimize potential outages (red cluster state).

In our production setup we have increased ping_retries to a much higher value to prevent a default reaction to ping failures. And it would have been very useful to get notified on these events as soon as possible.

We are quite happy with zen discovery in general and would consider implementing our own discovery plugin (which would be a pretty much copy&paste of the existing one + ping failures listener) as our last resort.

**Comment by jasontedor** [comment]
> Kicking a machine out of cluster (and moving shards around as a consequence) is useful only if the issue is completely isolated and has nothing to do with ES itself, e.g., hardware, network.

[Delayed allocation](https://www.elastic.co/guide/en/elasticsearch/reference/current/delayed-allocation.html) can help you here.

> However, in many cases ping failures are just an indication of a bigger problem (CPU spikes, Java GC stalls, OOM), and there is no one-size-fits-it-all policy to handle it.

A broad alert (a node missed a ping) where the first step is checking these metrics likely to be less useful than just having fine-grained alerting on these specific metrics.

> In our production setup we have increased ping_retries to a much higher value to prevent a default reaction to ping failures.

This is generally not a good idea. This will allow hung or dead nodes to stick around far longer than is ideal which will impact querying and indexing.
