### ISSUE TITLE
Rest tests need to clean up snapshots

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#18159]
**Elasticsearch version**:
5.0.0

**Description of the problem including expected versus actual behavior**:
Right now the rest tests wipe snapshots by deleting all of the repositories. This doesn't really work because if you recreate a repository with the same name it'll still contain the snapshots. The tests should actually wipe all of the snapshots.

**Comment by nik9000** [comment]
I've started poking at this but not really got all the way to fixing it. I'll come back to it in a few days if no one else wants it first.

**Comment by javanna** [comment]
@nik9000 this is still valid right?

**Comment by nik9000** [comment]
I *think* so. I just forgot about it. I can pick it up again soon though.
