### ISSUE TITLE
[CI] org.elasticsearch.index.query.InnerHitBuilderTests.testFromAndToXContent failure

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#18166]
This asserts that the inner hits is equal to the parsed inner hits:

```
assertThat(innerHit, equalTo(secondInnerHits));
```

Failure here: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=debian/360/consoleText

It does reproduce with:

```
gradle :core:test -Dtests.seed=D38C14AF123CA974 -Dtests.class=org.elasticsearch.index.query.InnerHitBuilderTests -Dtests.method="testFromAndToXContent" -Des.logger.level=WARN -Dtests.security.manager=true -Dtests.locale=lv-LV -Dtests.timezone=Australia/Currie
```

**Comment by jasontedor** [comment]
I marked this test as awaits fix in 1199cd8e2a1343ba74f208c96d6798ab0da4bdfd.
