### ISSUE TITLE
elasticsearch doesn't support backquote?

### ISSUE THREAD

**Issue by qpily** [elastic/elasticsearch#18178]
Hi, I met a problem these days that I cannot query backquote in elastic.
My setting included letter, digit, symbol and punctuation. But it seems that ` is not included. I tried version 1.6, 2.2 and 2.3 either. It seems the same.
Did anybody meet this problem?

**Comment by clintongormley** [comment]
Hi @qpily 

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
