### ISSUE TITLE
 rfc3986, html 4.01 spec: support semicolons as well as ampersand?

### ISSUE THREAD

**Issue by LaszloHont** [elastic/elasticsearch#18175]
I noticed that this works:

`curl http://localhost:9200/_cluster/health?level=indices&pretty=true`

but this doesn't work:

`curl http://localhost:9200/_cluster/health?level=indices;pretty=true`

Using the ampersand as separator seems to be pretty standard, see:
* https://www.w3.org/TR/html401/appendix/notes.html#h-B.2.2
* https://tools.ietf.org/html/rfc3986
* https://en.wikipedia.org/wiki/Query_string#Structure

**Comment by clintongormley** [comment]
Semi-colons are reserved sub-delimiters in query strings, meaning that semi-colons in keys/values should be percent encoded.  This means we could support them without risk
