### ISSUE TITLE
Documentation claims "index.translog.sync_interval" is dynamic, but it can not be set dynamically

### ISSUE THREAD

**Issue by paullovessearch** [elastic/elasticsearch#18199]
**Elasticsearch version**: 2.3.2

**JVM version**: 1.8

**OS version**: Windows 10 Enterprise

**Description of the problem including expected versus actual behavior**:

The documentation (https://www.elastic.co/guide/en/elasticsearch/reference/2.3/index-modules-translog.html) claims that "index.translog.sync_interval" is a dynamic setting, but it can not be set dynamically.

When I try to set it dynamically, I get the following error message:

"Can't update non dynamic settings[[index.translog.sync_interval]] for open indices [[twitter-20160417000000]]"

**Steps to reproduce**:
 1. Send the following to /<<your index>>/_settings:

{
  "index": {
    "refresh_interval": "-1",
    "number_of_replicas": "0",
    "blocks": {
      "read": "true"
    },
    "translog": {
      "durability": "async",
      "sync_interval": "5m",
      "flush_threshold_size": "1gb",
      "flush_threshold_ops": "-1",
      "interval": "15s"
    }
  }
}

 2. Get the error

**Provide logs (if relevant)**:

**Comment by clintongormley** [comment]
Closed by ca4cc273ba41dbb1058153e56e1223c7671e6c14
