### ISSUE TITLE
Support combined highlights with indirect reference to nested fields

### ISSUE THREAD

**Issue by chvndb** [elastic/elasticsearch#18206]
I have a smart-case sensitive indexing setup in place as described in my [question on stackoverflow](http://stackoverflow.com/questions/36960683/smartcase-searches-highlights-with-elasticsearch/36972516) .

**tl;dr**
I created a smart-case indexing setup that allows the user to perform smart-case partial matching on dynamic text fields. I.e. I do not know up-front what the structure of documents to be ingested wil be. 

Everything works, except for the highlighting. I am capable of getting individual highlights back, but not combined as one. The **"matched_fields"** option enables the behaviour that I would need, but it requires to know which fields would be highlighted. In our case, we use the wildcard "*" to get back the matches. However, this has no meaning in the matched_fields field. 

**feature request**
I would like to be able to write something similar to:
```
  "highlight": {
    "number_of_fragments": 0,
    "require_field_match": false,
    "fields": {
      "*": {
        "matched_fields": [ "*.case_sensitive", "*.case_insensitive" ]
      }
    }
  }
```
or
```
  "highlight": {
    "number_of_fragments": 0,
    "require_field_match": false,
    "fields": {
      "*": {
        "nested_matched_fields": [ "case_sensitive", "case_insensitive" ]
      }
    }
  }
```
which for each field would return a combined highlight created from their nested case_sensitive and case_insensitive fields. In other words, if ingested documents only have two fields: **description** and **title**, then this would translate to:
```
  "highlight": {
    "number_of_fragments": 0,
    "require_field_match": false,
    "fields": {
      "title": {
        "matched_fields": [ "title", "title.case_sensitive", "title.case_insensitive" ]
      },
      "description": {
        "matched_fields": [ "description", "description.case_sensitive", "description.case_insensitive" ]
      }
    }
  }
```

**Comment by clintongormley** [comment]
Highlighting works on a single field.  What logic would you expect would be applied to combine the highlighting results from multiple fields, and why can't the same logic be applied application aside by simply highlighting on (eg):

    "highlight": {
      "fields": {
        "*.case*": {}
      }
    }

**Comment by chvndb** [comment]
[My post on stackoverflow](http://stackoverflow.com/questions/36960683/smartcase-searches-highlights-with-elasticsearch/36972516) explains that I currently make use of:
```
"highlight": {
  "fields": {
    "*": {}
  }
}
```
which works great. However, it returns highlights on the same field as separate highlights. From the example I gave there I would get back as a response:
```
"highlight": {
  "text.case_sensitive": [
    "<em>tHis</em> .is a! Test"
  ],
  "text.case_insensitive": [
    "tHis .is a!<em> Test</em>"
  ]
}
```
This is indeed correct, but requires me to merge both highlights manually in my application as I don't want to expose this logic to the user. What I would prefer to get as a result is:
```
"highlight": {
  "text": [
    "<em>tHis</em> .is a!<em> Test</em>"
  ]
}
```
The feature added as a result of https://github.com/elastic/elasticsearch/issues/3750 provides the **matched_fields** field to combine highlights from multiple fields into one. This is ideal for multi-fields that index the same field in different ways, just like the setup I have. The only issue with this feature is that it requires to know which fields will contain the highlights and state them in the matched_field field. I do not know up front which text fields my documents will have. Therefore, I use dynamic templates. I only know that each text field will be mapped as a multi-field with two nested fields (**case_sensitive** and **case_insensitive**) that index the field in a different [(in-depth details here)](http://stackoverflow.com/questions/36960683/smartcase-searches-highlights-with-elasticsearch/36972516).

Therefore, I can not write:
```
"highlight": {
  "fields": {
    "whateverfield": {
      "matched_field": [ "whateverfield.case_sensitive", "whateverfield.case_insensitive" ]
    }
  }
}
```
as I do not know which fields the ingested documents consist of from within my application. Therefore, I want to be able to write:
```
"highlight": {
  "fields": {
    "*": {
      "nested_matched_field": [ "case_sensitive", "case_insensitive" ]
    }
  }
}
```

**Comment by nik9000** [comment]
> #3750 provides the matched_fields

I follow what you want. You want the matched fields to derive from the field name so it is properly compatible with `*`. I'm worried about features like this because

> I do not know which fields the ingested documents consist of from within my application

Often works great for small numbers of documents but starts to come apart at the seams if you have enough documents to have made thousands of fields. I mean, you'll get the right results but it'll be super slow and consume tons of resources. In general Elasticsearch's creating fields on the fly is useful but if you don't keep the number of these fields in check in some way you are asking to exhaust resources.

If you know that you are only going to have a dozen fields then you should just list them with the matched_fields. If you might have lots more I'm worried it is a recipe for disaster!

So, yeah, that is my 2c. Sorry I don't have a happier 2c.

**Comment by chvndb** [comment]
I agree about the performance issue, but this is an inherent consequence of using the `*` wildcard or trying to support searches/linking over heterogeneous and unstructured data, as I am trying to do. IMO, It is up to the developer to not mis-use this and/or to understand that response times are dramatically increased and resources are being exhausted because of this. This might also be perfectly fine depending on the application, infrastructure and amount of data. E.g. highlighting might be enabled/disabled from the UI allowing the user to understand how a hit was matched. This would imply only 1 document being highlighted, thus the overhead is limited.

This is crucial in my case, understanding is a big part of the application, while it is also mandatory to support heterogeneous (possibly unstructured, i.e. only one field) data and be able to search and find matches across indexes/types. So, yes this might be slow, but that is the unavoidable to the nature of some applications. Luckily, we are not working with big data. However, having to list fields requires me to introduce configurations that can be updated at run-time which become very cumbersome and are not very user friendly. Especially when data becomes temporary, i.e. the user can ingest data, do some searches and then remove it again.

ps. I do not mind contributing this, we only need to figure out the specifications.

**Comment by markharwood** [comment]
> So, yes this might be slow, but that is unavoidable to the nature of some applications. Luckily, we are not working with big data

We try to avoid providing core features that, while useful for small datasets, can have catastrophic effects when used on larger production systems. For this reason we would be unlikely to adopt something that didn't have performance as a priority.
Highlighting is always a "best-efforts" solution as it cannot ever hope to fully represent the full complexity of all user queries while also doing things like summarizing docs, working with multiple analyzers etc.
Given the small dataset and specialized analysis I suggest adapting an existing highlighter to meet your needs.
