### ISSUE TITLE
Elasticsearch 2.3.1 ignores default_lang

### ISSUE THREAD

**Issue by orweinberger** [elastic/elasticsearch#18200]
**Elasticsearch version**: 2.3.1

**JVM version**: 1.8.0

**OS version**: Ubuntu

These are my configuration values:

```
script.inline: on
script.indexed: on
script.file: on
script.default_lang: javascript
script.engine.javascript.inline: on
script.engine.javascript.indexed: on
script.engine.javascript.file: on
```

I have loaded the lang-javascript plugin and I can confirm I can see it in the log when loading the cluster (on all nodes of the cluster)

However, when I try to define a custom field on Kibana that reads:

`new Date(doc['timestamp'].value).getHours()`

I get this exception:

```
unexpected token 'Date' on line (1) position (4) was expecting one of <EOF>
```

I can also see it tries to render this using 'expression' instead of 'javascript':

```
[Failed to compile inline script [new Date(doc['timestamp'].value_.getHours()] using lang [expression]
```

**Comment by clintongormley** [comment]
Hi @orweinberger 

This works just fine in Elasticsearch 2.3.1.  `expression` is not the default lang, that's `groovy`.  I think you'll find that Kibana sets the `lang` parameter to `expression` as it is the only language that is guaranteed to be enabled for `inline` scripts.

**Comment by orweinberger** [comment]
I can't find any references to this in the Kibana repository or issues, do you have any ideas how I can change the language to Javascript instead of expression?

**Comment by clintongormley** [comment]
You'd be better off asking in the Kibana list, but I don't think you can separately.  Kibana is waiting for this issue to be fixed so that they can detect which languages are available: https://github.com/elastic/elasticsearch/issues/17114
