### ISSUE TITLE
ES 1.7, _optimize merges froze up..

### ISSUE THREAD

**Issue by Robitx** [elastic/elasticsearch#18235]
I'm trying to reduce the number of deleted documents in our indices, since we reindex most of the stuff ("real time" indexation directly to es and hourly reindexation from hadoop) the deleted documents takes about 40-50 percent of the total.

expunge_deletes_allowed to 1% isn't effective as I would expect, so I've tried _optimize?only_expunge_deletes=true on some index

_optimize?only_expunge_deletes=true initiates merges for this index, but the command eventually times out and the active merges in this index froze up (leading to the crashing cluster).

**Comment by clintongormley** [comment]
Hi @Robitx 

Usually it is best to just leave Elasticsearch to manage its own merges, unless you have an index which will no longer receive any updates.  You're missing a lot of information here eg size of segments, number of segments, any merge throttling, free disk space, etc etc.

I suggest starting out by providing the above information in a question in the forum instead: https://discuss.elastic.co/

If you identify an actual bug (which hasn't been resolved in a newer release) then open a ticket here.

thanks
