### ISSUE TITLE
Feature request: search highlight pagination

### ISSUE THREAD

**Issue by rpedela** [elastic/elasticsearch#18248]
##### Use case
I am building a searchable document viewer with the primary goal of providing a significantly better search experience than CTRL+F. When the user searches, it jumps to the most relevant fragment rather than the first one (like CTRL+F). And there is a sidebar which lists all search results within the document ordered by relevance. When the user clicks a result, the viewer jumps to that fragment.

##### Problem
Some documents are 100s of pages long therefore a search can return 1000s of results. In order to get all results within a document currently, I can either set ```number_of_fragments``` to zero or a very large number. The problem with setting to zero is that I lose all scoring information. The problem with setting a very large number is that it is inefficient.

##### Solution
I think search highlight pagination would solve the problem.

**Comment by clintongormley** [comment]
@rpedela the right solution is to index your very long document as individual pages (perhaps as parent child)

**Comment by rpedela** [comment]
It isn't one document that is 100s of pages. I have millions of them. Tika (or any tool I have tried) doesn't give page numbers when extracting raw text so I don't really see how that is a solution.
