### ISSUE TITLE
CORS filtering applied for same origin requests

### ISSUE THREAD

**Issue by mchv** [elastic/elasticsearch#18256]
**Elasticsearch version**: `2.3.2`
**JVM version**: `1.8`
**OS version**: not relevant

**Description of the problem including expected versus actual behavior**:

- Actual behavior

Following [CORS implementation refactoring changes](https://github.com/elastic/elasticsearch/pull/16436) when a request contains an `Origin` header, it is considered as a cross-origin request and `CORS` filtering is applied based on configuration. 

This prevents the [head plugin](https://github.com/mobz/elasticsearch-head), if `CORS` is not enabled or not configured to enable a specific origin, to work with `Chrome` or `Safari` as [they add an origin header for every POST request](http://stackoverflow.com/a/15514049) 

More specifically `POST requests` from those browsers will be returned `403` (`Forbidden`)  

- Expected behavior 

According to [RFC 6454](https://tools.ietf.org/html/rfc6454#section-7.3):
> The user agent MAY include an Origin header field in any HTTP request.

[CorsHandler](https://github.com/elastic/elasticsearch/blob/2.3/core/src/main/java/org/elasticsearch/http/netty/cors/CorsHandler.java) should check the `Host` header, and if it matches the domain in the `Origin` header, don't treat the request as a cross-origin request, and so allow it to be performed. 

**Steps to reproduce**:

*  1 - Disable `CORS` in elasticsearch configuration
```yaml
http.cors.enabled: false
```
* 2 - Send a `same origin POST` request with an `Origin` header  
```
curl -H "Origin: http://localhost:9200" -X POST http://localhost:9200/_all/_search
```

**Comment by abeyad** [comment]
@mchv thank you for reporting!  Fixed by commit https://github.com/elastic/elasticsearch/commit/d3f205b4a2c6e61810e818de3be83164cd2b69a0

It will be part of 2.3.3
