### ISSUE TITLE
_validate/query's rewrite=true output seems wrong

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#18254]
**Steps to reproduce**:
Run this:

```
curl -XPUT localhost:9200/twitter/tweet/1?refresh -d'{
  "user" : "kimchy",
  "post_date" : "2009-11-15T14:12:12",
  "message" : "trying out Elasticsearch"
}'
curl -XPUT localhost:9200/twitter/tweet/2?refresh -d'{
  "user" : "kimchi",
  "post_date" : "2009-11-15T14:12:13",
  "message" : "My username is similar to @kimchy!"
}'
curl -XPUT localhost:9200/twitter/tweet/3?refresh -d'{
  "user" : "notkimchi",
  "post_date" : "2009-11-15T14:12:13",
  "message" : "My username is not similar to @kimchy!"
}'

curl -XGET 'localhost:9200/twitter/tweet/_validate/query?rewrite=true&pretty' -d'{
  "query": {
    "match": {
      "user": {
        "query": "kimchy",
        "fuzziness": "auto"
      }
    }
  }
}'
```

The output of the last bit is:

```
{
  "valid" : true,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "explanations" : [ {
    "index" : "twitter",
    "valid" : true,
    "explanation" : "+() #(ConstantScore(_type:tweet))^0.0"
  } ]
}
```

`+()` isn't right at all. It should be more like `+(user:kimchy user:kimchi^0.75)` or something.

This came up when I was trying to add `// CONSOLE` to validate.asciidoc. I'm going to disable some of the tests that generates and mark them with this issue.

**Comment by camilojd** [comment]
I gave it a shot. When querying `_validate`, the operation is performed against an unique random shard as specified by `TransportValidateQueryAction#shards`.

All possible results are:

	"explanation" : "+() #(ConstantScore(_type:tweet))^0.0"
	"explanation" : "+user:kimchy #(ConstantScore(_type:tweet))^0.0"
	"explanation" : "+(user:kimchi)^0.8333333 #(ConstantScore(_type:tweet))^0.0"

The `+()` is a BooleanQuery with 0 clauses, a result of a query rewrite in an shard with no hits for the original fuzzy query. 

I'm now sure if would be worthy to hit all shards and somehow pick the most relevant explanation... or maybe remove irrelevant strings from the description.

Thoughts?

**Comment by clintongormley** [comment]
Ah thanks for digging @camilojd - perhaps all that is needed here is some documentation about the rewrite parameter.

**Comment by nik9000** [comment]
> Ah thanks for digging @camilojd - perhaps all that is needed here is some documentation about the rewrite parameter.

Maybe, but right now the rewrite parameter just picks a shard for the rewrite so you end up with different results. The inconsistency makes it pretty hard to use. If this is just a docs problem then we should document it as "only useful for multi-term queries if all shards are exactly the same" or something.

**Comment by clintongormley** [comment]
> "only useful for multi-term queries if all shards are exactly the same" or something.

just explaining that it chooses a shard at random should be sufficient.  this reflects the actual query being run on one shard.  it's the same issue as indexing two docs in 5 shards then wondering why relevance is off.

**Comment by imotov** [comment]
I think we can consider this one done. We have mentioned it in documentation and #23697 makes it possible to get response from all shards if needed. Please feel free to reopen if you don't agree.
