### ISSUE TITLE
Fingerprint analyzer asciifolds AFTER deduplication

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#18266]
As currently implemented, the `fingerprint` analyzer performs asciifolding after terms have been deduplicated.  In other words, the following:

    POST my_index/_analyze
    {
      "analyzer": "fingerprint",
      "text": "Yes Godel yes, Gödel said this sentence is consistent and."
    }

produces the token `and consistent godel godel is said sentence this yes`

I realise that this is as described in [OpenRefine](https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/clustering/binning/FingerprintKeyer.java#L68) but I'm wondering if it makes sense?

We have the `preserve_original` option to the parameter which results in two terms: one with extended characters and one without:

    PUT my_index
    {
      "settings": {
        "analysis": {
          "analyzer": {
            "my_fingerprint_analyzer": {
              "type": "fingerprint",
              "preserve_original": true
            }
          }
        }
      }
    }

    POST my_index/_analyze
    {
      "analyzer": "my_fingerprint_analyzer",
      "text": "Yes Godel yes, Gödel said this sentence is consistent and."
    }

This currently produces: 

* `and consistent godel godel is said sentence this yes`
* `and consistent godel gödel is said sentence this yes`

I'm thinking it would make more sense to:

* asciifold
* dedupe
* then concatenate

In which case the standard output would be: `and consistent godel is said sentence this yes` and with `preserve_original`:

* `and consistent godel is said sentence this yes`
* `and consistent godel gödel is said sentence this yes`

@markharwood @polyfractal what do you think?

**Comment by polyfractal** [comment]
Yep, I raised this issue in the PR too.  It seemed odd to me as well, but @markharwood seemed to think it was acceptable since this will (usually?) be used for algorithmic purposes.

**Comment by markharwood** [comment]
I misunderstood the problem - I thought it was about the choice of a single output token being folded or not. I now see it's about having both versions in the output. Agree with @clintongormley - it would make seem to make sense to change the order.

**Comment by polyfractal** [comment]
Ah oops, I explained poorly then :)  PR sent!
