### ISSUE TITLE
Remove fields from URI Search doc

### ISSUE THREAD

**Issue by gquintana** [elastic/elasticsearch#18268]
https://www.elastic.co/guide/en/elasticsearch/reference/master/search-uri-request.html#_parameters_3

In 5.0A2, this doesn't work anymore:
```
GET book/_search?fields=title
```

**Comment by dadoonet** [comment]
It works but only with stored fields:

```
PUT test
{
  "mappings": {
    "doc": {
      "properties": {
        "name": {
          "type": "text",
          "store": true
        }
      }
    }
  }
}
PUT test/doc/1
{
  "name": "david"
}
GET test/_search?fields=name
```

The documentation mentions that: https://www.elastic.co/guide/en/elasticsearch/reference/master/search-uri-request.html

> The selective **stored** fields of the document to return for each hit, comma delimited. Not specifying any value will cause no fields to return.

I'm closing. Feel free to reopen if you think I'm missing something.
