### ISSUE TITLE
[bug report]file descriptor leak

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#18265]
**Elasticsearch version**:
1.7.0
**JVM version**:
jdk1.8.0_60
**OS version**:
CentOS Linux release 7.1.1503
**Description of the problem including expected versus actual behavior**:
1. use lsof |wc -l to check es process and found out that it use 785334 file descriptor
2. lsof to check more and lots of lucene files, but cat those files, those files doesn't exits.

lsof -p pid:
java    26400 admin  875r      REG                8,3      5285 2148641170 /export/Data/elasticsearch/jiesi-13-bak/jiesi-13-bak/nodes/0/indices/serialnumberindex/2/index/_1t64l.cfs
java    26400 admin  876r      REG                8,3  37509255 2148680299 /export/Data/elasticsearch/jiesi-13-bak/jiesi-13-bak/nodes/0/indices/serialnumberindex/2/index/_16d1_Lucene410_0.d
vd
java    26400 admin  877r      REG                8,3 117618112 2148651284 /export/Data/elasticsearch/jiesi-13-bak/jiesi-13-bak/nodes/0/indices/serialnumberindex/2/index/_26gh_Lucene41_0.do
c
java    26400 admin  878r      REG                8,3 195296325 2148651286 /export/Data/elasticsearch/jiesi-13-bak/jiesi-13-bak/nodes/0/indices/serialnumberindex/2/index/_26gh_Lucene41_0.ti
m
java    26400 admin  879r      REG                8,3 766023672 2148651289 /export/Data/elasticsearch/jiesi-13-bak/jiesi-13-bak/nodes/0/indices/serialnumberindex/2/index/_26gh.fdt
java    26400 admin  880r      REG                8,3   7468533 6443429245 /export/Data/elasticsearch/jiesi-13-bak/jiesi-13-bak/nodes/0/indices/.node_monitor-2016.05.06/0/index/_boa_Lucene4
1_0.doc
java    26400 admin  881r      REG                8,3      3406 6443478173 /export/Data/elasticsearch/jiesi-13-bak/jiesi-13-bak/nodes/0/indices/.node_monitor-2016.05.06/0/index/_ff2.nvd
java    26400 admin  882r      REG                8,3  33891307 2148651283 /export/Data/elasticsearch/jiesi-13-bak/jiesi-13-bak/nodes/0/indices/serialnumberindex/2/index/_26gh_Lucene410_0.d
vd

cat these files, they doesn't exit.
**Steps to reproduce**:
 1. start es process
 2.running for a long time

**Comment by jimferenczi** [comment]
github is for bug reports only, can you open a discussion on the forum instead:
https://discuss.elastic.co/c/elasticsearch

My first 2c is that you have a lot of SearchContext open that keep those files alive. Please open a discussion on the forum so we can dig into your problem.
