### ISSUE TITLE
throwing exception if use constant_score & bool together at the same level of query object

### ISSUE THREAD

**Issue by hbakhtiyor** [elastic/elasticsearch#18275]
only if use with `bool` together

```json
{
  "query": {
    "bool": {
      "must": [{ "term": { "slug": "awe2ome" } }],
      "must_not": [{ "term": { "slug": "not_awe2ome" } }],
      "should": [],
      "minimum_should_match": 1
    },
    "constant_score": {
      "filter": {
        "bool": {
          "must": [{ "term": { "is_deleted": false } }]
        }
      }
    }
  }
}
```

```
Error: [parse_exception] failed to parse search source. expected field name but got [START_OBJECT]
```

official docker image elasticsearch:2.1.1

**Comment by clintongormley** [comment]
Your query is malformed.

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by hbakhtiyor** [comment]
hmm, what's wrong with the query?

**Comment by clintongormley** [comment]
You can't do ` { "query": { "bool": {...}, "something_else: {....}}`

**Comment by hbakhtiyor** [comment]
how to re-write with the right format?

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
