### ISSUE TITLE
Combining a score plugin with a filter results in empty documents in the java plugin

### ISSUE THREAD

**Issue by roelandvanbatenburg** [elastic/elasticsearch#18290]
**Elasticsearch version**: 1.7.5

**JVM version**:
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**OS version**: OS X 10.11.4

**Description of the problem including expected versus actual behavior**:
When combining our score plugin with a filter we have empty documents in the java plugin.
```
  "query": {
        "function_score": {
            "functions": [{
                "script_score": {
                    "script": "native-score",
                    "lang": "native",
                    "params": {}
                }
            }],
            "query": {
                "bool": {
                    "must_not": [{
                        "term": {
                            "field1": "A"
                        }
                    }, {
                        "term": {
                            "field1": "B"
                        }
                    }]
                }
            },
            "boost_mode": "replace",
            "min_score": 0
        }
    }
```

And then in the Script
```
  @Override
  public double runAsDouble() {
    if (source().size() == 0) {
      logger.warn("empty document"); 
    }
}
```

Then in the log files we have this
```
...
[2016-05-12 11:33:55,633][WARN ][com.enrise...Script$Factory] [Yuriko Oyama] empty document
```

This message disappears when we remove the filter. It seems that instead of filtering the documents they are somehow emptied and then passed to the script

**Steps to reproduce**:
 1. create a simple plugin
 2. add some data
 3. filter part of the data
 4. see the empty documents

**Comment by clintongormley** [comment]
You are replacing (`boost_mode: replace`) the score from the query with nothing, which is returned by your script.  Also, accessing the source field in a query will result in horrendous performance.  Don't do that.

**Comment by roelandvanbatenburg** [comment]
I know source() is bad, but this is just to show that the doc is empty.
The runAsDouble actually returns a number in our code, but for these cases it can not determine the score as it has no fields to work with.
