### ISSUE TITLE
Sense UI - Playbutton can move whole frames

### ISSUE THREAD

**Issue by Norlo** [elastic/elasticsearch#18291]
**OS version**: 
Win7

**Description of the problem including expected versus actual behavior**:
Sense UI is no more fixed inside its browser window.

**Steps to reproduce**:
 1. Write some requests into request frame, that you'll get the frames scoll bar.
 2. Select the request on the bottom
 3. Scroll up
 4. The Play-Button will shift your whole screen up
 5. Below the request and response frames you'll have some empty useless space

Testet in Mozilla Firefox as well Google Chrome

![bug_sense](https://cloud.githubusercontent.com/assets/19325590/15213272/8dc7d67e-1846-11e6-8502-7232802f6167.JPG)

**Comment by jasontedor** [comment]
There is a [dedicated repository](https://github.com/elastic/sense) for Sense.
