### ISSUE TITLE
unable to index trivial dataset without entering GC hell

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#18309]
Followup to https://github.com/elastic/elasticsearch/pull/16334

In previous releases, elasticsearch would use up to 1GB of ram by default. With this change, it will only use 512MB. The problem is, elasticsearch is not ready for this, and our own benchmarks show it: https://benchmarks.elastic.co/index.html#gc_time

You can easily see the ~ **25x** increase in old GC time with this change, for this trivial dataset.

There are two ways to fix this:
1. go back to using a 1GB heap by default
2. fix ES to not waste so much RAM.

I don't care which one we do, but the defaults should support indexing a trivial dataset. I've indexed this dataset enough times with lucene to know exactly how trivial it is, disputing that point will not be productive.

The way I see it, ES isn't ready for a 512mb default heap for a number of reasons:
* explosive bombs like fielddata still exist in some shape or form
* trappy RecylingXYZPools of this form or another hogging RAM
* use of netty as a library for networking
* creation of far too many threads, beyond the point of being wasteful.

This list could go on and on. Most of these are simply bad tradeoffs. It may be easier to just go back to a 1GB heap for 5.0 than to try to address these things. But lets not blame @jasontedor for trying to reduce the memory, it is a good goal.

**Comment by jasontedor** [comment]
> You can easily see the ~ 25x increase in old GC time with this change, for this trivial dataset.

For what it's worth, I was only able to reproduce a 5x increase in GC time with the decrease from a 1g to a 512m heap. I do not want this comment to distract from the issue though.

> 1. go back to using a 1GB heap by default

I think we should go to 2g and I opened #18311. The work in #16334 shows that at 2g we stop getting returns from increasing the heap. Namely: allocations in the TLABs, allocation rates and GC pause times do not change above 2g. 

> 2. fix ES to not waste so much RAM.

But of course, we should do this too, but that's a larger effort. :smile:

**Comment by rmuir** [comment]
I am fine with your analysis. If you think 2GB is what we need, +1

We may not _like_ that it is an increase from 1GB, but reality is reality. I think we should size the defaults to be really functional defaults, ones that actually work, and then separately open an issue to reduce the ram usage so we can lower this number. I don't like the number myself, but that is the number we have.

**Comment by jasontedor** [comment]
Closed by #18311
