### ISSUE TITLE
Loop through comma-separated data directories and create them in init.d startup script

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#18307]
We run `mkdir` on the $DATA_DIR in the deb init.d script (and with https://github.com/elastic/elasticsearch/pull/17419 don't run it at all if it has commas in it), but it would be good to loop through all the directories and create them if there is a comma in the list.

**Comment by dakrone** [comment]
So, ES itself will create the data directories if they don't exist when it starts, therefore, should the init script do this? I would say it's not necessary since it would just be duplicating the logic already in ES' bootstrapping.

Thoughts?

**Comment by jasontedor** [comment]
> So, ES itself will create the data directories if they don't exist when it starts, therefore, should the init script do this? I would say it's not necessary since it would just be duplicating the logic already in ES' bootstrapping.

Sounds reasonable.

> Thoughts?

I wonder if we should remove the "optimization" for a single directory then?

**Comment by dakrone** [comment]
> I wonder if we should remove the "optimization" for a single directory then?

That might be a good idea, I'll leave this open for a little bit longer (overnight at least) and see if anyone has a reason to keep it around

**Comment by clintongormley** [comment]
Discussed in FixItFriday - just rely on Elasticsearch to create the directories, so remove the `mkdir` completely.
