### ISSUE TITLE
Function score queries in must_not bool clauses producing incorrect results

### ISSUE THREAD

**Issue by rusnyder** [elastic/elasticsearch#18315]
**Elasticsearch version**: 1.7.5 (Tested against 2.0.2, 2.1.2, 2.2.2, and 2.3.2 as well and this is not an issue in any of those releases)

**JVM version**: 1.8.0_45

**OS version**: OSX 10.11.4

**Problem**:

When running a function score query as a must_not bool clause, approximately half of the expected documents are being returned. I've been playing around with replicas, number of shards, optimizing, and refreshing on insert which all have minimal to no impact, so for the sake of testing an demonstration and to eliminate variables, the example focuses on 1 shard with no replicas.  I also played around with different score functions and found this same behavior with all functions I tested.

**Steps to reproduce**:

```shell
# Create the sample index with a single shard
curl -XPUT http://localhost:9200/fnscore-test-index -d '{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 0
    }
  }
}'

# Index some documents.  Two should be enough to demonstrate the issue 
# in a single-shard index, but I saw some inconsistencies around how many documents
# failed to match appropriately in smaller sample sizes, so crank up the sample size
# until you see the query count mismatches
for i in {1..2}; do
  curl -XPUT "http://localhost:9200/fnscore-test-index/event/$i" -d "{\"field\":\"value-$i\"}"
done

# Run the must_not function score query, sticking with a simple function
# score script that SHOULD match every document, therefore making the
# must_not match zero documents
curl -XPOST http://localhost:9200/fnscore-test-index/event/_count -d '{
   "query": {
      "bool": {
         "must_not": [
            {
               "function_score": {
                  "functions": [
                     {
                        "script_score": {
                           "script": "-1",
                           "lang": "expression"
                        }
                     }
                  ],
                  "score_mode": "sum",
                  "boost_mode": "replace",
                  "min_score": 0
               }
            }
         ]
      }
   }
}'
# ...which returns...
{
   "count": 1, # This should be 2 
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   }
}
```

Since the function score query should match zero documents, the must_not should (in theory) return ALL documents, but it's really only returning somewhere around half.  Note that small sample sizes have (greater sample sizes )

**Interesting (maybe) notes**:

* Adding a refresh after each insert changes how many documents fail to match the query criteria in small samples, but with an increased sample size, that difference diminishes as the sample size increases, more/less completely vanishing in the 80-100 document range
* Using a `not` filter instead of a bool query `must_not` "fixes" the problem and returns all expected results (this requires the function score query to be wrapped in a query filter, of course)
* Adding `must` and `should` clauses to the bool query has no impact on the result

Note that this is only an issue in 1.7.5 and below, which I totally understand makes it way lower priority.  I've tested with all of the most recent 2.x point releases and have been unable to reproduce with those releases.  I'm putting in this report more because I'm not super familiar w/ bool internals and wanted to make sure this wasn't something systemic that may cause future issues.

**Comment by clintongormley** [comment]
Hi @rusnyder 

I've tried out your replication and it seems to work just fine on 1.7.5.  This is what I did:

    PUT /fnscore-test-index
    {
      "settings": {
        "index": {
          "number_of_shards": 1,
          "number_of_replicas": 0
        }
      }
    }
    
    PUT /fnscore-test-index/event/1
    {"field":"value-1"}
    PUT /fnscore-test-index/event/2
    {"field":"value-2"}
    
    POST /fnscore-test-index/event/_count
    {
      "query": {
        "bool": {
          "must_not": [
            {
              "function_score": {
                "functions": [
                  {
                    "script_score": {
                      "script": "-1",
                      "lang": "expression"
                    }
                  }
                ],
                "score_mode": "sum",
                "boost_mode": "replace",
                "min_score": 0
              }
            }
          ]
        }
      }
    }
    
> Adding a refresh after each insert changes how many documents fail to match the query criteria in small samples, but with an increased sample size, that difference diminishes as the sample size increases, more/less completely vanishing in the 80-100 document range

This makes me think you have changed the refresh interval on this index?  I think if you try this on a clean cluster with default settings, you'll find it working just fine.

**Comment by rusnyder** [comment]
I'm seeing the same behavior when executing the same commands as you on a fresh cluster, but am still able to reproduce my issue by replacing the independent index requests with either a for loop in bash OR (newly discovered) with a bulk request:

_NOTE: I'll switch to using sense-like syntax for sharing queries - sorry for the bash!_

```shell
DELETE /fnscore-test-index

PUT /fnscore-test-index
{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 0
    }
  }
}

POST /fnscore-test-index/_bulk
{"index":{"_type":"event","_id":"1"}}
{"field":"value-1"}
{"index":{"_type":"event","_id":"2"}}
{"field":"value-2"}

POST /fnscore-test-index/event/_count
{
  "query": {
    "bool": {
      "must_not": [
        {
          "function_score": {
            "functions": [
              {
                "script_score": {
                  "script": "-1",
                  "lang": "expression"
                }
              }
            ],
            "score_mode": "sum",
            "boost_mode": "replace",
            "min_score": 0
          }
        }
      ]
    }
  }
}
```

Since both a for loop of individual index requests and a bulk request are able reproduce the issue (for me, anyway - the verdict is out for yourself!), it leads me to believe the lack-of-delay between insert statements is closely tied to the underlying issue.  It also makes me feel like it's not a fun one.

**Comment by clintongormley** [comment]
And if you do:

    POST fnscore-test-index/_refresh

before your count?

**Comment by rusnyder** [comment]
Adding a refresh doesn't change the count.  I then also tried to optimize, just for kicks and giggles, since that fixed similar (yet unrelated) issues in another cluster to no avail:

```
POST /fnscore-test-index/_optimize?max_num_segments=1
```

I added the explain param to the "failing" query and even the explain results indicate that the hit that is being returned shouldn't, in fact, be returned since it's not actually a search hit (either that or I'm not reading the explain output correctly, which is possible):

```javascript
POST /fnscore-test-index/event/_search?explain
{
  "query": {
    "bool": {
      "must_not": [
        {
          "function_score": {
            "functions": [
              {
                "script_score": {
                  "script": "-1",
                  "lang": "expression"
                }
              }
            ],
            "score_mode": "sum",
            "boost_mode": "replace",
            "min_score": 0
          }
        }
      ]
    }
  }
}

// Note that value/description indicate that this shouldn't have hit:

{
   "took": 1,
   "timed_out": false,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 1,
      "hits": [
         {
            "_shard": 0,
            "_node": "nvCXAPZoS3OImOn5X0l72A",
            "_index": "fnscore-test-index",
            "_type": "event",
            "_id": "1",
            "_score": 1,
            "_source": {
               "field": "value-1"
            },
            "_explanation": {
               "value": 0,
               "description": "Failure to meet condition(s) of required/prohibited clause(s)",
               "details": [
                  {
                     "value": 0,
                     "description": "match on prohibited clause (function score (ConstantScore(*:*),function=script[-1], params [null]))",
                     "details": [
                        {
                           "value": -1,
                           "description": "function score, product of:",
                           "details": [
                              {
                                 "value": -1,
                                 "description": "Math.min of",
                                 "details": [
                                    {
                                       "value": -1,
                                       "description": "script score function, computed with script:\"-1",
                                       "details": [
                                          {
                                             "value": 1,
                                             "description": "_score: ",
                                             "details": [
                                                {
                                                   "value": 1,
                                                   "description": "ConstantScore(*:*), product of:",
                                                   "details": [
                                                      {
                                                         "value": 1,
                                                         "description": "boost"
                                                      },
                                                      {
                                                         "value": 1,
                                                         "description": "queryNorm"
                                                      }
                                                   ]
                                                }
                                             ]
                                          }
                                       ]
                                    },
                                    {
                                       "value": 3.4028235e+38,
                                       "description": "maxBoost"
                                    }
                                 ]
                              },
                              {
                                 "value": 1,
                                 "description": "queryBoost"
                              }
                           ]
                        }
                     ]
                  },
                  {
                     "value": 1,
                     "description": "ConstantScore(*:*), product of:",
                     "details": [
                        {
                           "value": 1,
                           "description": "boost"
                        },
                        {
                           "value": 1,
                           "description": "queryNorm"
                        }
                     ]
                  }
               ]
            }
         }
      ]
   }
}
```

**Comment by clintongormley** [comment]
> I'm seeing the same behavior as you (as in, not broken) when executing the same commands as you on a fresh cluster, but am still able to reproduce my issue by replacing the independent index requests with either a for loop in bash OR (newly discovered) with a bulk request:

Do you mean that you're able to replicate this on a fresh cluster of 1.7.5? Or only on your existing cluster?

I've run your recreation many times without seeing it fail once.

**Comment by rusnyder** [comment]
My apologies - I mean in a fresh cluster.  Perhaps it's something machine or JVM specific.  I'll try reproducing this with a few more combinations of machine + JVM version and get back with more info.

**Comment by rusnyder** [comment]
I've gotten a few other devs here to reproduce the issue w/ fresh ES 1.7.5 installs and fresh clusters on some different OS's and Java versions (combinations of Fedora, Ubuntu, and OS X with Java 1.8 updates 45, 60, and 91).  I've also created a now-failing test that reproduces the issue (sorry I didn't lead with this!): https://github.com/rusnyder/elasticsearch/commit/554e36c5855ab5a314f1d32d968d57493f1f617a

I can inline a patch for that test, if desired, but otherwise will just spend some time this weekend trying to figure out what's happening.

**Comment by rusnyder** [comment]
I think I figured out what the issue is, but I haven't quite worked out a solution yet.

During the query phase of the aforementioned queries (`must_not` wrapping a `function_score`), this internally gets scored using Lucene's [`ReqExclScorer`](https://github.com/apache/lucene-solr/blob/branch_4x/lucene/core/src/java/org/apache/lucene/search/ReqExclScorer.java) wrapping an effective match all as the required scorer (more specifically, a `ConstantScore(*:*)` and a [`CustomBoostFactorScorer`](https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/common/lucene/search/function/CustomBoostFactorScorer.java) as the exclusion scorer.  When using the `min_score` parameter of the function score query, the `CustomBoostFactorScorer` delegates advancement through the document set to its inner class, [`MinScoreNextDoc`](https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/common/lucene/search/function/CustomBoostFactorScorer.java#L92)

The problem is that `MinScoreNextDoc.advance(int)` and `ReqExclScorer.nextDoc` are stepping on each other's toes, because both are advancing (calling `nextDoc()`) on the underlying scorer but`ReqExclScorer` is more/less expecting to be the only thing doing the advancement while marking exclusions.

I'll walk through the code path of concern here (all info on variables was found by and can reproduced by stepping through the test case I linked in the previous comment):

[`org.apache.lucene.search.Weight.DefaultBulkScorer#scoreAll(Collector, Scorer)`](https://github.com/apache/lucene-solr/blob/branch_4x/lucene/core/src/java/org/apache/lucene/search/Weight.java#L190)
```java
public abstract class Weight {
  ...
  static class DefaultBulkScorer extends BulkScorer {
    /* [rusnyder] This field, in our test case, is set to the ReqExclScorer of concern */
    private final Scorer scorer;
    ...
    static void scoreAll(Collector collector, Scorer scorer) throws IOException {
      int doc;
      /* [rusnyder] scorer.nextDoc() -> see next snippet */
      while ((doc = scorer.nextDoc()) != DocIdSetIterator.NO_MORE_DOCS) {
        collector.collect(doc);
      }
    }
    ...
  }
}
```

[`org.apache.lucene.search.ReqExclScorer#nextDoc()`](https://github.com/apache/lucene-solr/blob/releases/lucene-solr/4.10.4/lucene/core/src/java/org/apache/lucene/search/ReqExclScorer.java#L46)
```java
class ReqExclScorer extends Scorer {
  ...
  public int nextDoc() throws IOException {
    if (reqScorer == null) {
      return doc;
    }
    /* [rusnyder] This is the first of 2 document advancements in the ReqExclScorer */
    doc = reqScorer.nextDoc();
    if (doc == NO_MORE_DOCS) {
      reqScorer = null; // exhausted, nothing left
      return doc;
    }
    if (exclDisi == null) {
      return doc;
    }
    /* [rusnyder] toNonExcluded() -> see next snippet */
    return doc = toNonExcluded();
  }
  ...
}
```

[`org.apache.lucene.search.ReqExclScorer#toNonExcluded()`](https://github.com/apache/lucene-solr/blob/releases/lucene-solr/4.10.4/lucene/core/src/java/org/apache/lucene/search/ReqExclScorer.java#L72)
```java
class ReqExclScorer extends Scorer {
  ...
  private int toNonExcluded() throws IOException {
    int exclDoc = exclDisi.docID();
    int reqDoc = reqScorer.docID(); // may be excluded
    do {  
      if (reqDoc < exclDoc) {
        return reqDoc; // reqScorer advanced to before exclScorer, ie. not excluded
      } else if (reqDoc > exclDoc) {
        /* [rusnyder] exclDisi is an instance of 
           FunctionScoreQuery.FunctionFactorScorer here, but that class 
           inherits CustomBoostFactorScorer which is where the 
           pertinent logic is */
        /* [rusnyder] exclDisi.advance(reqDoc) -> see next snippet */
        exclDoc = exclDisi.advance(reqDoc);
        if (exclDoc == NO_MORE_DOCS) {
          exclDisi = null; // exhausted, no more exclusions
          return reqDoc;
        }
        if (exclDoc > reqDoc) {
          return reqDoc; // not excluded
        }
      }
    /* [rusnyder]: The function score query from the test should result in
        all documents being added to the exclusion set, whereas this nextDoc()
        is only invoked for sparse exclusion sets (i.e. - our test never hits this) */
    } while ((reqDoc = reqScorer.nextDoc()) != NO_MORE_DOCS);
    reqScorer = null; // exhausted, nothing left
    return NO_MORE_DOCS;
  }
  ...
}
```

[`org.elasticsearch.common.lucene.search.function.CustomBoostFactorScorer.MinScoreNextDoc#aadvance(int)`](https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/common/lucene/search/function/CustomBoostFactorScorer.java#L112)

```java
abstract class CustomBoostFactorScorer extends Scorer {
    ...
    public class MinScoreNextDoc implements NextDoc {
        ...
        public int advance(int target) throws IOException {
            int doc = scorer.advance(target);
            if (doc == NO_MORE_DOCS) {
                return doc;
            }
            currentScore = innerScore();
            if (currentScore < minScore) {
                /* [rusnyder] This is the advancement that conflicts with
                   the advancements made above */
                return scorer.nextDoc();
            }
            return doc;
        }
    }
    ...
}
```

The conflict is in between the call `scorer.nextDoc()` from within the `CustomBoostFactorScorer` (Elasticsearch) and the `reqScorer.nextDoc()` call from the ReqExclScorer (Lucene).  I tried increasing the number of documents that I indexed in my test, and what I saw made lots of sense: For a contiguous sequence of documents within a single segment that all match the "exclusion" criteria (the code path I outlined is within the context of a single `AtomicReader` on a single segment), every other document from such a sequence is being returned.  This makes plenty of sense when looking at the code because for each document that "hits" the exclusion set in the code path above, the `nextDoc()` function gets invoked twice which ultimately results in the following document within that sequence to be skipped.

I'm new to this part of the codebase and am still rationalizing where exactly the breakdown is and which part of the code is responsible for sorting this out.  My instinct leads me to believe that the onus is either on Elasticsearch's `CustomBoostFactorScorer` to stop advancing the underlying scorer or on Lucene's `ReqExclScorer` to better handle the case where the exclusion scorer needs to advance through multiple docs at a time to build the exclusion set.

Anyway, I'll see if I can pull something together that makes sense, and in the meantime, and if there's any useful info you have in the meantime, I'd love to hear it!

**Comment by clintongormley** [comment]
Awesome work @rusnyder !!!  Thank you for diving into this.

@jpountz please could you take a look?

**Comment by jpountz** [comment]
@rusnyder Thanks for digging! Base on the description of the issue, I think all that is needed to fix the bug is the following?

```patch
diff --git a/src/main/java/org/elasticsearch/common/lucene/search/function/CustomBoostFactorScorer.java b/src/main/java/org/elasticsearch/common/lucene/search/function/CustomBoostFactorScorer.java
index bcc785a..ded96e8 100644
--- a/src/main/java/org/elasticsearch/common/lucene/search/function/CustomBoostFactorScorer.java
+++ b/src/main/java/org/elasticsearch/common/lucene/search/function/CustomBoostFactorScorer.java
@@ -116,7 +116,7 @@ abstract class CustomBoostFactorScorer extends Scorer {
             }
             currentScore = innerScore();
             if (currentScore < minScore) {
-                return scorer.nextDoc();
+                return nextDoc();
             }
             return doc;
         }

```

**Comment by rusnyder** [comment]
Wow @jpountz - that was easy.  It's like you guys know what you're doing...

That worked like a charm!  I'm happy to put out a PR w/ the test and the fix, but I'll leave that decision up to you!

Thanks again!!

**Comment by rusnyder** [comment]
Of note, I went back and tested this in 2.0.2, 2.1.2, 2.2.2, and 2.3.3 now that I had a better understand of what was going on and the test case more honed in, and there is a similar issue in 2.02, 2.1.2, and 2.2.2, except that all three of those versions consistently return zero documents for the "must not(function score(match no docs))" query when they should be returning all.  2.3.3 returns the right results for the query.

I haven't had much time to dig in on those, but I took a look to see what would happen if I applied the same patch to those versions and this patch does NOT fix the 2.x versions.  I'll dig more later, but since the `ReqExclScorer` more/less received an overhaul in Lucene 5.x, it'll take a bit more exploring for me to track down.

**Comment by jpountz** [comment]
Thanks for the PR!

>  return zero documents for the "must not(function score(match no docs))" query when they should be returning all of the docs

I could not replicate this bug, can you share the query you are running?

**Comment by rusnyder** [comment]
Sure thing.  It's the same as the original steps to reproduce the 1.7 bug, but I added an optimize to guarantee all documents are on the same segment first:

```
PUT /fnscore-test-index
{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 0
    }
  }
}

POST /fnscore-test-index/_bulk
{"index":{"_type":"event","_id":"1"}}
{"field":"value-1"}
{"index":{"_type":"event","_id":"2"}}
{"field":"value-2"}

POST /fnscore-test-index/_refresh
POST /fnscore-test-index/_optimize?max_num_segments=1

POST /fnscore-test-index/event/_search?explain
{
  "query": {
    "bool": {
      "must_not": [
        {
          "function_score": {
            "functions": [
              {
                "script_score": {
                  "script": "-1",
                  "lang": "expression"
                }
              }
            ],
            "score_mode": "sum",
            "boost_mode": "replace",
            "min_score": 0
          }
        }
      ]
    }
  }
}
```

I hope I'm not going crazy, but that sequence is causing the query to return 0 events on fresh installs of the three aforementioned versions for me.

**Comment by jpountz** [comment]
The default query for a function_score is a match_all query, so I think returning no hits in this case is the expected behoviour?

**Comment by rusnyder** [comment]
I assumed that was the default behavior was a `match_all` if no function was specified, not if a function was specified that matched no events.  As per the [function score docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html):

> If no query is given with a function this is equivalent to specifying `"match_all": {}`

Since we _are_ specifying a function here that should be matching zero events, I'd think the docs from that `match_all` would all get filtered out by that function.  To add to my expected behavior, with the index setup and documents as indexed in the previous comment, running just the function score query without the `must_not` _also_ provides 0 results, which is the behavior that I would expect:

```
POST /fnscore-test-index/_search
{
   "query": {
      "function_score": {
         "functions": [
            {
               "script_score": {
                  "script": "-1",
                  "lang": "expression"
               }
            }
         ],
         "score_mode": "sum",
         "boost_mode": "replace",
         "min_score": 0
      }
   }
}
```

**Comment by jpountz** [comment]
@rusnyder Function score takes two kinds of queries: one that defines the matching docs, and then one per function that defines the documents to apply the function to (which is effectively just a filter since its score is never used). The sentence you are quoting is about the latter. Maybe we should reuse the parameter name and rewrite it to `If no _filter_ is given with a function this is equivalent to specifying "match_all": {}` to be clearer.
