### ISSUE TITLE
Min and max heap size must be equal to start ES 5.0.0-alpha2

### ISSUE THREAD

**Issue by anhlqn** [elastic/elasticsearch#18318]
**Elasticsearch version**: 5.0.0-alpha2

**JVM version**: jre1.8.0_91

**OS version**: Windows 10

**Description of the problem including expected versus actual behavior**:
ES 5.0.0 require same min and max heap size
```
initial heap size [268435456] not equal to maximum heap size [1073741824]; this can cause resize pauses and prevents mlockall from locking the entire heap```
```
Why don't we just set
```
-Xms1g
-Xmx1g
```
instead of having in the default options
```
-Xms256m
-Xmx1g
```

**Steps to reproduce**:
 1. Run ES with default JVM options

**Provide logs (if relevant)**:

**Comment by danielmitterdorfer** [comment]
We think so too and this is already addressed in a couple of tickets, the latest one being #18309 and the related PR is #18311. Closing this now in favor of the already existing tickets.
