### ISSUE TITLE
Return number of documents in the result counts as HTTP header or in JSON

### ISSUE THREAD

**Issue by burtonator** [elastic/elasticsearch#18312]
Elasticsearch version: 2.3.2

JVM version: 1.8.0_91

**OS version**: Linux dev 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Describe the feature**:

We're a SaaS provider of social media data via Elasticsearch.  We have a large ES of about 150 machines and about 6 months of social media content.

You can check our our service at:

http://spinn3r.com

We need the ability to throttle customers based on the number of documents they have returned.  We have a piece of HTTP proxy middleware that sits between the Internet and our ES boxes which allows us to provide authorization, logging, etc.

We REALLY need the ability to easily keep track of the number of documents fetched.  

What we've done so far is developed an internal ES plugin with new _search and _msearch endpoints that exposes these as HTTP headers.

The headers just include the number of documents returned in the search request.

This prevents us from having to parse the documents to find out the number returned.

We would LOVE for this functionality to be integrated into stock elasticsearch.

**Comment by clintongormley** [comment]
Hi @burtonator 

I can definitely see the utility for you of doing this. There's a related request here https://github.com/elastic/elasticsearch/issues/16993

The questions this raises for me are:

* What if somebody else wants a different value returned in a header
* What if others don't want the headers

I'm struggling to come up with a different value for the search API that users might want as a header, and there could probably be a setting to disable headers, but i'll leave this here for discussion

**Comment by burtonator** [comment]
Well the headers don't impose that much overhead.  Maybe 10 bytes per request.  There are already a ton of headers there anyway.  

X-result-count: 150 

would be fine.

**Comment by s1monw** [comment]
@burtonator I think we can work on making the search and msearch rest actions simpler such that you can override the response handler and set the headers yourself? This would make your plugin trivial and future proof? Would that help you as a first step?

**Comment by clintongormley** [comment]
No further feedback. Closing

**Comment by burtonator** [comment]
Can we reopen this.  I think the header should just be a STANDARD part of Elasticsearch. It seems reasonable to have the document response count easily parsed.  Right now it's not.

**Comment by clintongormley** [comment]
>  I think the header should just be a STANDARD part of Elasticsearch.

You do, for your application.  I neither need it nor want it.  Hence, @s1monw's offer to extend the REST api to make your plugin simpler, which was waiting for a response.

**Comment by colings86** [comment]
No further feedback.
