### ISSUE TITLE
how can I put parameters in ElasticSearch curl post

### ISSUE THREAD

**Issue by JackWang917** [elastic/elasticsearch#18316]
The following is my linux shell code for insert one record to ElasticSearch:

username="Tom"
curl -XPOST 'http://192.168.0.1:9200/userdb/info/1' -d '{"user":"$username"}'
But it didn't work, it treated $username is a string not a variable. How can I fix this please?

**Comment by danielmitterdorfer** [comment]
Hi @JackWang917,

we have a discussion forum for these type of question: https://discuss.elastic.co/c/elasticsearch

Can you please post your question there. Closing now as this is not an issue with Elasticsearch.
