### ISSUE TITLE
Don't ignore allocation settings with cluster reroute

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#18321]
The cluster reroute command ignores the allocation deciders for index/cluster allocation settings, which makes it hard to debug why shards are not being assigned (see https://github.com/elastic/elasticsearch/issues/18294#issuecomment-218967378)

**Comment by dakrone** [comment]
I believe it should be an option to disable the allocation deciders when running reroute commands. I've disabled allocation and then manually allocated shards to be where I want them to be before in order to reproduce a specific cluster allocation

**Comment by clintongormley** [comment]
While that may be useful from a debugging perspective, it sounds very trappy for users. The least we should do is report them as ignored in the explain output

**Comment by s1monw** [comment]
> Update: I was missing the context. I'm +1 on providing a flag to allow disabled allocation to be overridden with the cluster reroute command

+1 for now but in general we should really try to get away from providing this API alltogether

**Comment by clintongormley** [comment]
The flag should also allow overriding of the `index.allocation.max_retry` counter, which is being added in https://github.com/elastic/elasticsearch/pull/18467

**Comment by bleskes** [comment]
heads up to whoever implements this - some allocation deciders should never be overridden - for example `ReplicaAfterPrimaryActiveAllocationDecider` and `SameShardAllocationDecider`. These are so essential to how the code works, that I wonder if we should give them a special place/hard code them.

**Comment by DaveCTurner** [comment]
> which makes it hard to debug why shards are not being assigned

We think this is now covered sufficiently well by the allocation explain API.
