### ISSUE TITLE
Enable transposition for fuzzy search in multi match query

### ISSUE THREAD

**Issue by bittusarkar** [elastic/elasticsearch#18320]
**Describe the feature**: 
Apparently, `transpositions` are disabled for `fuzzy` `multi_match` queries. Is there any reason for the same? Can it be made configurable?

**Comment by clintongormley** [comment]
@bittusarkar It's not:

    PUT t/t/1
    {
      "foo": "one two three",
      "bar": "one two three"
    }
    
    GET t/_search 
    {
      "query": {
        "multi_match": {
          "query": "trhee",
          "fields": ["foo","bar"],
          "fuzziness": "AUTO"
        }
      }
    }

**Comment by bittusarkar** [comment]
@clintongormley Thank you for your reply. Thing is I don't want to use `AUTO`. I want to limit the maximum value of `fuzziness` to `1` and also enable transpositions. Can that be achieved without changing Elasticsearch code?

**Comment by s1monw** [comment]
transpositions are enabled by default but can't be disabled on multi match query @clintongormley should we add that switch?

**Comment by clintongormley** [comment]
> Thing is I don't want to use AUTO. I want to limit the maximum value of fuzziness to 1 and also enable transpositions. Can that be achieved without changing Elasticsearch code?

Yes, transpositions are enabled by default so just set `fuzziness` to `1`.

> transpositions are enabled by default but can't be disabled on multi match query @clintongormley should we add that switch?

I've opened  https://github.com/elastic/elasticsearch/issues/18348

**Comment by clintongormley** [comment]
Added docs for `fuzzy_transposition` to `match` query in bfc826003bf7db97f852c8f74e74bc11946917b6

**Comment by bittusarkar** [comment]
Sorry for the confusion guys. I should've mentioned I am using Elasticsearch 1.7.1 in which `transposition` is not enabled. Is that intentional? I see that in Elasticsearch 2.1.1, `transposition` is enabled by default. Looks like I need to upgrade Elasticsearch.

**Comment by s1monw** [comment]
> I see that in Elasticsearch 2.1.1, transposition is enabled by default. Looks like I need to upgrade Elasticsearch.

agreed

**Comment by sschwell** [comment]
I see that this was closed but I don't see a transpositions() method on MultiMatchQueryBuilder in 5.5.1
Am I missing something?
Is it possible to turn off transpositions on a MultiMatchQuery?

**Comment by teddis** [comment]
I see this is an old post, but in ES 6.4.3 it doesn't appear transpositions are enabled by default and can't specify that property for multi-field queries. So for example, a search for misspelled "ceasar" return no results and "caesar" does. Query snippet:

```{
  "query": {
    "bool": {
      "should": [
        {
          "multi_match": {
            "query": "ceasar",
            "operator": "and",
            "fuzziness": "AUTO",
            "prefix_length": 3,
            "fields": [
              "name",
              "catName^4"
            ],
            "boost": 1000
          }
        }
      ]
    }
  }
}
```

Of course I get `"[multi_match] query does not support [transpositions]"` when trying to specify transpositions. Any way to solve this?

**Comment by dduqueti** [comment]
@sschwell Having the same question here. Any findings?
