### ISSUE TITLE
_size doesn't support doc values

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#18334]
The documentation for the `mapper-size` plugin claims you can use `_size` in sorts, aggregations, and in scripts but I don't imagine any of those work because it doesn't support doc_values. Is it intentional that it doesn't?

**Comment by clintongormley** [comment]
This worked in 2.x because it fell back to loading fielddata.  @jpountz what do you think? should we at least allow enabling doc values on `_size`?

@dakrone how were you guys using `_size`?  Did you need to run aggs on them?

**Comment by dakrone** [comment]
> how were you guys using `_size`? Did you need to run aggs on them?

Yep, usually min/max/average were the metrics we cared about in terms of document size.

**Comment by clintongormley** [comment]
@jimferenczi could you take this one please?
