### ISSUE TITLE
index.query.bool.max_clause_count can not be set

### ISSUE THREAD

**Issue by jimyoo1** [elastic/elasticsearch#18336]
Index level setting is not allowed in elastic search.yml with 5.0.0-alpha2.

And with _setting or _template API I got:
{
"error": {
"root_cause": [
{
"type": "illegal_argument_exception",
"reason": "unknown setting [index.query.bool.max_clause_count]"
}
],
"type": "illegal_argument_exception",
"reason": "unknown setting [index.query.bool.max_clause_count]"
},
"status": 400
}

Is this a bug? Any work-around?

**Comment by s1monw** [comment]
this is a bug - this setting has not been registered! good catch thanks for reporting this!!!
