### ISSUE TITLE
Expose `fuzzy_transpositions` in fuzzy queries

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#18348]
The `fuzzy_transpositions` parameter is supported by the `match` query (`true` by default) but not by the `multi_match`, `query_string`, `simple_query_string`, or `fuzzy` queries, nor by the completion suggester.

We should add this parameter to all of the above.

**Comment by cihati** [comment]
@clintongormley I see that `fuzzy_transpositions` is being mentioned in https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-match-query.html but not in https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-multi-match-query.html -- does MultiMatchQuery have this parameter too? If so, can the documents be updated please?

**Comment by Helen-Zhao** [comment]
First time contributor - I would like to pick this up and have a try if that's okay. Thanks.

**Comment by nikolayisaev** [comment]
I am new to GitHub public projects, so if possible I would like to make this my first fix on the project.
