### ISSUE TITLE
Slow Query Log - Ability to specify data to be added to log lines

### ISSUE THREAD

**Issue by paullovessearch** [elastic/elasticsearch#18354]
**Describe the feature**:

We would like to be able to link slow queries back to the user or application which caused the slow query.

Therefore we recommend adding a "logData" parameter to the search API which is simply copied from the request directly into the slow query log. We can then put identifiers (user ID, application ID, query ID, etc.) and what-not into this field to provide the linkages necessary to perform traceback to the application / systems which caused the slow query.

We realize that we could possibly do this with the "stats" parameter (stats groups), but we are concerned that there may be many IDs (thousands, millions) and that the stats-groups structure may not support such a large number of groups (i.e. it would likely use up memory maintaining stats for millions of entries).

Thank you.
Paul

**Comment by jasontedor** [comment]
Duplicates #9669
