### ISSUE TITLE
copy_to not working as expected with the mapper plugin

### ISSUE THREAD

**Issue by sikron** [elastic/elasticsearch#18361]
**Elasticsearch version**:
2.3.2

**JVM version**:
1.7.0_101 x64

**OS version**:
Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:
Hi,
i am using Elasticsearch 2.3.2 with the Mapper Attachments Plugin. I try to copy the extracted content to another field, as described [here](https://github.com/elastic/elasticsearch-mapper-attachments#copy-to-feature)
This is not working for me, though.

I also found a closed bug here #14946. But the discussion does it not make clear, whether the bug has been resolved or not.

Therefore i would be happy, if you could give me a definitive answer, whether this is possible or not.

**Steps to reproduce**:
curl -XPOST 'http://localhost:9200/test' -d '{
  "entry": {
    "properties": {
      "file": {
        "type": "attachment",
        "fields": {
          "content": {
            "type": "string",
            "copy_to": "fulltext_en"
          }
        }
      },
      "fulltext_en": {
        "type": "string",
        "analyzer": "english"
      }
    }
  }
}'

curl -XPOST 'http://localhost:9200/test/entry' -d '{
  "file": "TG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQ="
}'
// the base64 is "Lorem ipsum dolor sit amet"

curl -XPOST 'http://localhost:9200/test/_search' -d '
{
  "query": {
    "match": {
      "fulltext_en": "ipsum"
    }
  }
}'

the result of the search is then empty, which is wrong, as "ipsum" is contained in the base64.

**Comment by clintongormley** [comment]
Hi @sikron 

Yes, `copy_to` is no longer allowed on multi-fields as of https://github.com/elastic/elasticsearch/pull/10802.  In fact, for field types other than `attachment`, we throw an exception if you try to add `copy_to` to a multi-field (https://github.com/elastic/elasticsearch/pull/15213).  This isn't something we can fix in mappings, without introducing a lot of complexity which is likely to carry bugs with it.  

The mapper-attachment plugin is deprecated in favour of the [ingest-attachment plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/master/ingest-attachment.html), so this is not something that we're going to fix, but I will remove the docs claiming that we support `copy_to`.

**Comment by sikron** [comment]
hi, thx for clarification!
