### ISSUE TITLE
Add regex flags to pattern-replace character filter

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#18362]
In the `pattern` tokenizer, we allow setting regex flags via the `flags` parameter.  The same support should be added to the `pattern_replace` character filter.

**Comment by gfyoung** [comment]
Hi!  I'm a first time contributor this repository and am trying to find my way around.  IINM but doesn't `pattern_replace` already accept `flags` (see <a href="https://github.com/elastic/elasticsearch/blob/0f00c14afc8428a2a72c0b766d2171029dc8f6e1/core/src/main/java/org/elasticsearch/index/analysis/PatternReplaceTokenFilterFactory.java#L44">here</a>)?

**Comment by gfyoung** [comment]
Hi!  I'm a first time contributor trying to find my way around.  Is <a href="https://github.com/elastic/elasticsearch/blob/0f00c14afc8428a2a72c0b766d2171029dc8f6e1/core/src/main/java/org/elasticsearch/index/analysis/PatternReplaceCharFilterFactory.java">this</a> the correct file to add the changes?

**Comment by clintongormley** [comment]
@gfyoung yes, that's the one
