### ISSUE TITLE
can not install service correctly on windows using "service.bat"

### ISSUE THREAD

**Issue by zhiaixuexi** [elastic/elasticsearch#18373]
**elasticsearch-2.3.2**:

**jdk1.8**:

**windows 7**:

**Can not install service correctly on windows using "service.bat", startup service after execute "service install" , you will get an error "can not find %java_home%/jre/bin/server/jvm.dll" **:

**Steps to reproduce**:
 1.unzip the elasticsearch, setting environment variables well
 2.run service install [yourservicename]
 3.service start [yourservicename]

**Provide logs (if relevant)**:

**Well, i guess the error is caused by a small mistake in service.bat, function - doInstall, --Jvm "%%JAVA_HOME%%%JVM_DLL%" , a couple of more percent sign added around JAVA-HOME here  **:

**Comment by jasontedor** [comment]
There is no bug here, you just don't have Java set up correctly. In particular, those forward slashes are probably causing trouble.

Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions.

**Comment by zhiaixuexi** [comment]
thanks a lot

**Comment by zhiaixuexi** [comment]
@jasontedor  Thanks a lot.

**Comment by jasontedor** [comment]
@zhiaixuexi You're welcome.

**Comment by zhiaixuexi** [comment]
@jasontedor 
I don't know where i made mistake but it still not work .by execute service manager command and i got this
![image](https://cloud.githubusercontent.com/assets/11385718/15293696/ce85c8a6-1bbb-11e6-9b29-8986ba23a158.png)
This is the error log below.
![error log](https://cloud.githubusercontent.com/assets/11385718/15294168/c1e5ea5c-1bbd-11e6-918b-7744db123bdb.png)
everything goes well untill i changed 
"%%JAVA_HOME%%%JVM_DLL%" to "%JAVA_HOME%%JVM_DLL%".

**Comment by jasontedor** [comment]
That `Jdk1.8` looks out of place. You should have `JAVA_HOME` set to something like `C:\Program Files\Java\jdk1.8.0_92` (or whatever update you have) and that value of that "Java Virtual Machine" property should just be `%JAVA_HOME%\jre\bin\server\jvm.dll`.

**Comment by zhiaixuexi** [comment]
oh, i am sorry i given an error information that mislead you,now env variable on my computer as below
![image](https://cloud.githubusercontent.com/assets/11385718/15294892/b61685e4-1bc0-11e6-83df-dc714fd074ed.png).
but it still shows the error.
But the strange thing is that, i found other services bind with env var likes `%JAVA_HOME%` on my PC are work well, i think i need to carefully check it again.
It is so kind of you to help me ^_^

**Comment by jasontedor** [comment]
Your image shows that you have a user-level environment variable named `%JAVA_HOME%`. Can you remove that? Also, how are you starting the service? From a command prompt? What's the value of `%JAVA_HOME%` there (`echo "%JAVA_HOME%"` in that command prompt)?

**Comment by zhiaixuexi** [comment]
@jasontedor 
That's it!  everything worked well after i move the `%JAVA_HOME%` from user-level to system-level.
anyhow i start the service by command prompt or via windows services.msc.
This has already perplexed me for a long time. You‘ve done me a big favor ^_^

**Comment by jasontedor** [comment]
You're welcome; I'm happy to have helped.
