### ISSUE TITLE
more control shard allocation by node?

### ISSUE THREAD

**Issue by sshling** [elastic/elasticsearch#18383]
**Elasticsearch version**:  1.7 or 2.x

**JVM version**: 1.8

**OS version**: centos 6.5

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:
can make some nodes  only allocation primary shard ,and other nodes only allow allocation replica shards-----just for backup

and more , if index have two replica shard,can config it some node allow allocation one sets replica,one some nodes allow allocation one sets，

for example :have a index name "demo",have 2 shards
node1,node2:   demo-0-p   demo-1-p
node3,node4:   demo-0-r1  demo-1-r1
node5,node6:   demo-0-r2  demo-1-r3

**Comment by jasontedor** [comment]
What do you think should happen if, for a given shard, all the nodes that you've marked as eligible for hosting a primary shard have died?

**Comment by sshling** [comment]
yes .  
In Multi machine room ， one for all normal use ,primary + replicate  process client request，but in a  accident  , this room all nodes power failure，so  another room with a sets replicate can be continue process client request , thanks .

**Comment by s1monw** [comment]
this is what [allocation awareness](https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-awareness.html) is for. 

please ask questions first on the [discuss list](https://discuss.elastic.co)
