### ISSUE TITLE
Elastic search missing modifier symbol in symbol matcher.

### ISSUE THREAD

**Issue by qpily** [elastic/elasticsearch#18388]
Last week I got a problem that elastic search didn't support back quote and I found out the reason. It seems that elastic missed 'modifier symbol' in symbol matcher. I found code in CharMatcher.java:
`SYMBOL {`
`@Override`
            `public boolean isTokenChar(int c) {`
                `switch (Character.getType(c)) {`
                `case Character.CURRENCY_SYMBOL:`
                `case Character.MATH_SYMBOL:`
                `case Character.OTHER_SYMBOL:`
                    `return true;`
                `default:`
                     `return false;`
                `}`
           `}`
        `}`
Appearently Character.MODIFIER_SYMBOL is missing here. I think it should be a bug.

**Comment by clintongormley** [comment]
@jpountz could you look at this please?
