### ISSUE TITLE
Ignoring deleted stopwords while generating shingles

### ISSUE THREAD

**Issue by vchalmel** [elastic/elasticsearch#18391]
Hi ! 
I have the same issue that the one exposed here : [#12819 ](https://github.com/elastic/elasticsearch/issues/12819) (before closing due to the lack of feedback asked by @clintongormley to the author @apanimesh061)

I discussed it here [on stackoverflow](http://stackoverflow.com/questions/37205478/how-to-prevent-duplicate-tokens-with-same-start-pos-but-different-end?noredirect=1#comment61964513_37205478) because I thought I made a mistake in my parameters

When using a shingle token filter after removal of stopwords why don't we have a parameter to completely ignore stopwords ?
There would be two huge benefits for me :
- Even with "filler_token":"" (or "filler_token":" " then a "trim" token filter) there are duplicated shingles generated, with the same text, "pos" and "start" but only differing by "end" that might tweak the queries scores for the duplicated words as seen [here :](http://i.stack.imgur.com/nboTe.png)
- If a word is surrounded by stopwords, no shingles would be generated associating it with other words around, several (deleted) stopwords away...

I shall add that those duplicated tokens are not removed by a "unique" token filter... and that I don't understand why.

Here is my analysis (I only kept the "test" analyzer which I used to generate examples but I have a few others ):
```json
"settings": {
	"index": {
		"analysis": {
			"filter": {
				"fr_stop": {
					"ignore_case": "true",
					"remove_trailing": "true",
					"type": "stop",
					"stopwords": "_french_"
				},
				"fr_worddelimiter": {
					"type": "word_delimiter",
					"language": "french"
				},
				"fr_snowball": {
					"type": "snowball",
					"language": "french"
				},
				"custom_nGram": {
					"type": "ngram",
					"min_gram": "3",
					"max_gram": "10"
				},
				"custom_shingles": {
					"max_shingle_size": "4",
					"min_shingle_size": "2",
					"token_separator": " ",
					"output_unigrams": "true",
					"filler_token":"",
					"type": "shingle"
				},
				"custom_unique": {
					"type": "unique",
					"only_on_same_position": "true"
				},
				"fr_elision": {
					"type": "elision",
					"articles": [
						"l",
						"m",
						"t",
						"qu",
						"n",
						"s",
						"j",
						"d",
						"c",
						"jusqu",
						"quoiqu",
						"lorsqu",
						"puisqu",
						"parce qu",
						"parcequ",
						"entr",
						"presqu",
						"quelqu"
					]
				}
			},
			"charfilter": "html_strip",
			"analyzer": {
				"test": {
					"filter": [
						"asciifolding",
						"lowercase",
						"fr_stop",
						"fr_elision",
						"custom_shingles"
						"trim",
						"custom_unique",
					],
					"type": "custom",
					"tokenizer": "standard"
				}
			},
			"tokenizer": {
				"custom_edgeNGram": {
					"token_chars": [
						"letter",
						"digit"
					],
					"min_gram": "3",
					"type": "edgeNGram",
					"max_gram": "20"
				},
				"custom_nGram": {
					"token_chars": [
						"letter",
						"digit"
					],
					"min_gram": "3",
					"type": "nGram",
					"max_gram": "20"
				}
			}
		}
	}
}
```

**Comment by clintongormley** [comment]
Hi @vchalmel 

Could you provide a complete (and minimal) curl recreation showing exactly what you're doing, the results you're getting, and how they differ from what you expect?

**Comment by vchalmel** [comment]
Hi @clintongormley 
I would be glad to... but I'm afraid I don't know how to get the detail of generated token using curl, I always use kopf to test my analysis...

**Comment by clintongormley** [comment]
Just use the analyze API:
https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-analyze.html

**Comment by vchalmel** [comment]
Hi @clintongormley 

```
curl -XGET 'localhost:9200/test_marches_publics/_analyze' -d '
{
"analyzer":"test",
"text" : "Scandale au pays de Candy"
}
```
give me, with default "filler_token"
```
{"tokens":[{"token":"scandale _","start_offset":0,"end_offset":12,"type":"shingle","position":0},{"token":"scandale _ pays","start_offset":0,"end_offset":16,"type":"shingle","position":0},{"token":"scandale _ pays _","start_offset":0,"end_offset":20,"type":"shingle","position":0},
{"token":"_ pays","start_offset":12,"end_offset":16,"type":"shingle","position":1},
{"token":"_ pays _","start_offset":12,"end_offset":20,"type":"shingle","position":1},
{"token":"_ pays _ candy","start_offset":12,"end_offset":25,"type":"shingle","position":1},
{"token":"pays _","start_offset":12,"end_offset":20,"type":"shingle","position":2},
{"token":"pays _ candy","start_offset":12,"end_offset":25,"type":"shingle","position":2},
{"token":"_ candy","start_offset":20,"end_offset":25,"type":"shingle","position":3}]}
```
and with "filler_token":""
{"tokens":[{"token":"scandale","start_offset":0,"end_offset":8,"type":"<ALPHANUM>","position":0},{"token":"scandale ","start_offset":0,"end_offset":12,"type":"shingle","position":0},
{"token":"scandale  pays","start_offset":0,"end_offset":16,"type":"shingle","position":0},{"token":"scandale  pays ","start_offset":0,"end_offset":20,"type":"shingle","position":0},
{"token":" pays","start_offset":12,"end_offset":16,"type":"shingle","position":1},
{"token":" pays ","start_offset":12,"end_offset":20,"type":"shingle","position":1},
{"token":" pays  candy","start_offset":12,"end_offset":25,"type":"shingle","position":1},{"token":"pays","start_offset":12,"end_offset":16,"type":"<ALPHANUM>","position":2},
{"token":"pays ","start_offset":12,"end_offset":20,"type":"shingle","position":2},
{"token":"pays  candy","start_offset":12,"end_offset":25,"type":"shingle","position":2},
{"token":" candy","start_offset":20,"end_offset":25,"type":"shingle","position":3},{"token":"candy","start_offset":20,"end_offset":25,"type":"<ALPHANUM>","position":4}]}

**Comment by vchalmel** [comment]
N.b. I had a mistake (now edited) in my first post, in "custom_unique", "only_on_same_position" is set to true.
If this parameter is false, the "trim"/"custom_unique" get rid of the duplicated tokens, but I don't want to delete identical tokens from distinct parts of the original text.

**Comment by clintongormley** [comment]
@vchalmel positions are used for phrase queries, offsets are used for highlighting. It's a mistake to try to use a shingled field for either of these purposes.  A shingled field is used for finding associated words, and that's it.  You should use a shingled field in a bool.should clause to boost the relevance of docs with matching fields.

Also, having min=max shingle of 2 is usually all you need. Remove the unigrams.

**Comment by vchalmel** [comment]
I don't understand your objection... Is it only a usecase scenario issue ?
- If I remove the unigrams and search on a unique word, will it match ?
- If "pays" is duplicated three times here, are you saying that a search on "pays" won't get a higher score on this document than on a document where it is not surrounded by stopwords and hence is not duplicated ?

You seem also to consider that shingles should only be used in a complementary field to boost score in queries if associated words are found, but that is simply not my use case... I want an index with all these tokens, both unigrams and shingles up to three words at least, because i will use them in a text-mining algorithm

On the other hand if min=max shingle=2 in that case "fox to be quick" won't generate the shingle "fox quick"
And what about the issue with the extras spaces ?

**Comment by clintongormley** [comment]
> If I remove the unigrams and search on a unique word, will it match ?

No.  But if you're using shingles as a secondary field for boosting, then the single word will match in the primary field you're searching on.

> If "pays" is duplicated three times here, are you saying that a search on "pays" won't get a higher score on this document than on a document where it is not surrounded by stopwords and hence is not duplicated because tokens differing only by positions and offset are only affecting highlighting and phrase queries ?

Yes it will get a higher score.  But then it is used more frequently, so it should get a higher score.  If you don't want it to match when it is combined with different stopwords, then leave the stopwords there (or use a different filler token).

> You seem also to consider that shingles should only be used in a complementary field to boost score in queries if associated words are found, but that is simply not my use case... I want an index with all these tokens, both unigrams and shingles up to three words at least, because i will use them in a text-mining algorithm...

Ok...  then perhaps your requirements are different, but I don't understand what your exact requirements are.  All I'm saying is that this is working correctly as is.  Token filters are not allowed to change positions or offsets. That jobs belongs solely to the tokenizer.  This comes directly from Lucene and isn't something we can change in Elasticsearch.

**Comment by vchalmel** [comment]
Thanks for your explanations !

> Token filters are not allowed to change positions or offsets. That jobs belongs solely to the tokenizer.

Oh that is something I failed to take into account... 
That would prevent us to re-calculate the size of the shingle to ignore deleted stopwords with the current formula, am I right ?... But how about a parameter to prevent the creation of a shingle starting or ending with a deleted stopword like these : ```
{"token":"pays","start_offset":12,"end_offset":16,"type":"shingle","position":1}, /* start with deleted stopword "au"*/
{"token":"pays  candy","start_offset":12,"end_offset":25,"type":"shingle","position":1},/* start with deleted stopword "au"*/
{"token":"pays","start_offset":12,"end_offset":16,"type":"<ALPHANUM>","position":2}, /*duplicate with first token because due to stopwords I have shingles of size 2 containing only 1 word*/
{"token":"pays  candy","start_offset":12,"end_offset":25,"type":"shingle","position":2}, /*duplicate with second token 
```
How could the size of a stopword being different of the count of words effectively existing in it be "working correctly as is" ?

**Comment by fhinze** [comment]
Hi,

you can remove the redundant whitespaces by using the pattern replace char filter like so:

`"whitespace_remove": {
        "type": "pattern_replace",
        "pattern": " +",
        "replacement": " "
        }`

However, you'll still have the same issue @vchalmel has.

**Comment by alejandro-marques** [comment]
Thanks for the suggestion @fhinze. I would still prefer something like the "preserve_position_increments=false" from completion suggester, but the "pattern_replace" filter combined with a "trim" one worked perfectly in order to remove those whitespaces left by stopwords.

**Comment by amateurCoder** [comment]
@vchalmel Were you able to find a workaround for this issue? I am facing the same issue when using shingles and stop_words together and want to dedupe shingles based on start_offset.

**Comment by ABDULAZIZALQATAN** [comment]
Dear All 
I am facing the same issue >>>> I need to remove all of the shingles with fillers >>> How can I do this ?

**Comment by Sanket-Valani** [comment]
That multiple spaces problem can be solved using pattern_replace filter
```
"space_filter": { 
  "type": "pattern_replace", 
  "pattern": "  *", 
  "replacement": " " 
}
```
 This will replace multiple spaces with one space

**Comment by sagarpatel07** [comment]
I am facing the same issue when using shingles and stop_words together and want to highligh field with match phrase prefix query. This issue should reopen.
