### ISSUE TITLE
Maybe we should make our REST test examples visible in our docs?

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#18397]
With #18075 merged we now have the option to execute our doc snippets through the REST test infrastructure.

Many of the small parts of original REST tests I've read look like great stories around how to use our REST API. I have no idea how much overlap there is between our docs and the REST test-suite, however I would imagine that one could convert several REST tests into nice pieces of documentation showing the complete story from indexing data to using the API under test.

I'm wondering if it would make sense to consolidate what we are now (or in the hopefully near future) testing from within our docs and what is covered in the REST tests. (Intentionally not adding any version label to this issue - currently this is really just a vague question instead of a hard and fast proposal to move any specific way.)

**Comment by clintongormley** [comment]
I'm very wary of docs that are not optimally docs because they're trying to be tests instead.  I'd much rather write the best possible docs and test the snippets used within as a secondary goal.

**Comment by nik9000** [comment]
> I'd much rather write the best possible docs and test the snippets used within as a secondary goal.

I think any snippets in the docs that aren't part of a test are prone to bit rot. One day I'd like to fail the build if there are any docs that aren't tested.

I agree with @clintongormley that docs should be docs first though. If they happen to be tests second that is a bonus. There might be duplication in test coverage that way but that seems less bad than having bad docs because they are really tests. OTOH I bet we could do something. I just don't think it is as urgent as getting the snippets tested.

**Comment by MaineC** [comment]
> > I'm very wary of docs that are not optimally docs because they're trying to be tests instead.

I think this is exactly the kind of input needed to put the original idea into perspective.

> I think any snippets in the docs that aren't part of a test are prone to bit rot. 

+1 There's one more argument for having these under test:

When making changes to existing features (adding deprecations, changing meaning, deleting parameters etc.) right now I can think of at least five locations in our code base that should be touched:
* the original code itself
* the tests the code hopefully ships with
* the migration docs
* potentially the REST tests
* the example in the docs
At least for myself I can state that it's fairly easy to forget one or more locations to update. Having the build tell me automatically instead of getting this feedback from a human reviewer and going through an added round of code review might save some time.


> I agree with @clintongormley that docs should be docs first though.

+1

> If they happen to be tests  second that is a bonus. There might be duplication in test coverage 
> that way but that seems less bad than having bad docs because they are really tests. OTOH I 
> bet we could do something. I just don't think it is as urgent as getting the snippets tested.

+1 Yeah sure - if github had some way of sorting issues by priority IMHO this one should be waaay below the one about putting existing snippets under test.

I guess my initial question is based on two thoughts:

* As we have support for both, request execution and result validation in the snippet testing, instead of writing both, a REST test and a comprehensive doc entry, maybe it would make sense to have only the doc (this assumes all that should be tested actually does fit nicely into the documentation itself).
* Because I know that at least I am myself prone to missing stuff if for any given change I need to touch more than a very limited number of locations in the code I'm leaning towards trying to eliminate duplication.

**Comment by clintongormley** [comment]
I think there isn't anything more to discuss, so I'll close this.
