### ISSUE TITLE
Using nested agg after reverse_nested shows higher count than expected

### ISSUE THREAD

**Issue by chevin99** [elastic/elasticsearch#18409]
**Elasticsearch version**: 2.2.0
**JVM version**:
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)

**OS version**: OSX Yosemite 10.10.2

I am doing this:

1. Grouping by a nested field: `nested_path.nested_field`
2. Using a reverse_nested agg so I can apply this filter: `non_nested_field == "yay"`
3. Using a nested agg so I can then get a count of the nested field I am grouping by: `nested_path.nested_field`

Problem: By using the reverse_nested agg I am getting a higher doc_count than I would expect.

Here is the mapping and docs I am indexing:

```
PUT /my_index
{
   "mappings": {
      "my_type": {
         "properties": {
            "nested_path": {
               "type": "nested",
               "properties": {
                  "nested_field": {
                     "type": "string"
                  }
               }
            },
            "non_nested_field": {
               "type": "string"
            }
         }
      }
   }
}

POST /my_index/my_type/1
{
  "non_nested_field": "whoray",
  "nested_path": [
    {
      "nested_field": "yes"
    },
    {
      "nested_field": "yes"
    },
    {
      "nested_field": "no"
    }
  ]
}

POST /my_index/my_type/2
{
  "non_nested_field": "yay",
  "nested_path": [
    {
      "nested_field": "maybe"
    },
    {
      "nested_field": "no"
    }
  ]
}
```

Search request:
```
POST my_index/my_type/_search
{
   "aggs": {
      "nested_option": {
         "nested": {
            "path": "nested_path"
         },
         "aggs": {
            "group_list": {
               "terms": {
                  "field": "nested_path.nested_field",
                  "size": 100
               },
               "aggs": {
                  "level_1": {
                     "reverse_nested": {},
                     "aggs": {
                        "level_2": {
                           "filter": {
                              "term": {
                                 "non_nested_field": "yay"
                              }
                           },
                           "aggs": {
                              "level_3": {
                                 "nested": {
                                    "path": "nested_path"
                                 },
                                 "aggs": {
                                    "stat": {
                                       "value_count": {
                                          "field": "nested_path.nested_field"
                                       }
                                    }
                                 }
                              }
                           }
                        }
                     }
                  }
               }
            }
         }
      }
   },
   "size": 0
}
```

Part of the response I get is this:
```
{  
  "aggregations": {
    "nested_option": {
      "doc_count": 5,
      "group_list": {
        "buckets": [
          {
            "key": "no",
            "doc_count": 2,
            "level_1": {
              "doc_count": 2,
              "level_2": {
                "doc_count": 1,
                "level_3": {
                  "doc_count": 2,
                  "stat": {
                    "value": 2
                  }
                }
              }
            }
          }
          //.... 
        ]
      }
    }
  }
}
```

In the first element of the buckets array in the response, `level_1.level_2.doc_count` is 1, and this is correct, because there's only one of the two docs indexed where `nested_path.nested_field == "no"` and `non_nested_field == "yay"`. But `level_1.level_2.level_3.doc_count` in the response is 2. It should only be 1. This seems like a bug to me.

**Comment by clintongormley** [comment]
This is working correctly. As soon as you step up with `reverse_nested`, you lose any context you had in the nested documents.  You can see this if you change your `stat` agg to repeat the terms agg:

    POST my_index/my_type/_search
    {
      "aggs": {
        "nested_option": {
          "nested": {
            "path": "nested_path"
          },
          "aggs": {
            "group_list": {
              "terms": {
                "field": "nested_path.nested_field",
                "size": 100
              },
              "aggs": {
                "level_1": {
                  "reverse_nested": {},
                  "aggs": {
                    "level_2": {
                      "filter": {
                        "term": {
                          "non_nested_field": "yay"
                        }
                      },
                      "aggs": {
                        "level_3": {
                          "nested": {
                            "path": "nested_path"
                          },
                          "aggs": {
                            "group_list": {
                              "terms": {
                                "field": "nested_path.nested_field",
                                "size": 100
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "size": 0
    }
