### ISSUE TITLE
Add tests for URL Repository

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#18407]
The `org.elasticsearch.repositories.uri.URLRepository` class does not have any tests written for it.  It needs tests to exercise its functionality, probably by connecting it to a webserver, so it will require some thought.

`SharedClusterSnapshotRestoreIT` contains two tests related to the URL repository:
1. `testUrlRepository`
2. `testReadOnlyRepository`

However, it would be helpful to have more comprehensive, unit level tests that prove the semantics and guarantees of the URL repository.

**Comment by nik9000** [comment]
We can use a fixture for this I think! See `:test:fixtures`.

**Comment by tlrx** [comment]
Closed by #29355
