### ISSUE TITLE
 Support for azure credential settings within repository settings

### ISSUE THREAD

**Issue by damianpfister** [elastic/elasticsearch#18416]
**Describe the feature**:
Allow the [Azure Cloud Repo](https://www.elastic.co/guide/en/elasticsearch/plugins/current/cloud-azure-repository.html) to have configuration settings such as credentials added via an API call rather than in `elasticsearch.yml`. This will standardise on what is already in place for [Amazon S3](https://www.elastic.co/guide/en/elasticsearch/plugins/current/cloud-aws-repository.html).

**Comment by damianpfister** [comment]
Example would be something like:
```
PUT _snapshot/my_backup2
{
    "type": "azure",
    "settings": {
        "credentials.account": "AZUREACCOUNT",
        "credentials.key": "AZUREKEY"
    }
}
```

**Comment by siddharthlatest** [comment]
@damianpfister Second adding this. Does this have any ETA?

**Comment by dadoonet** [comment]
It does not. Wanna contribute some code?

**Comment by liketic** [comment]
@dadoonet Seems like the latest s3 plugin has removed those apis?

**Comment by dadoonet** [comment]
@liketic Yes. I don't think we will support that in the short term but I think that @rjernst has some ideas for the future for "hot reload" or addition of credentials like this.

**Comment by darinhoward** [comment]
I'd like to add this feature - but seems like Secure Settings pattern may not allow for it 6.x - https://www.elastic.co/guide/en/elasticsearch/reference/6.2/secure-settings.html. 

Thoughts ?

**Comment by tlrx** [comment]
@darinhoward Right, starting from 6.0 we don't allow credentials or sensitive information to be specified in the elasticsearch configuration files or at the repository settings level. All secret information like credentials must be store in the Elasticsearch keystore as a secure setting.

If you look at the documentation (https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-azure-usage.html), the right way to go is to configure client settings in the keystore and then define the client name in the repository settings.
