### ISSUE TITLE
Clarification on filtered nested aggregation operation

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#18412]
Some clarification would be of use in mixing nested filters with nested aggregations.  

Here is an example of how the confusion might arise:

```
POST /my_index
{
   "mappings": {
      "my_type": {
         "properties": {
            "NESTED_FIELD": {
               "type": "nested",
               "include_in_parent": true,
               "properties": {
                  "SOME_FIELD": {
                     "type": "integer",
                     "doc_values": true
                  }
               }
            }
         }
      }
   }
}
```

Post some sample data:

```
POST /my_index/my_type/
{
   "NESTED_FIELD": [
      {
         "SOME_FIELD": 1718570
      }
   ]
}


POST /my_index/my_type/
{
   "NESTED_FIELD": [
      {
         "SOME_FIELD": 1718567
      },
      {
         "SOME_FIELD": 1718565
      },
      {
         "SOME_FIELD": 1718571
      },
      {
         "SOME_FIELD": 1718568
      },
      {
         "SOME_FIELD": 1718570
      },
      {
         "SOME_FIELD": 1718569
      },
      {
         "SOME_FIELD": 1718566
      }
   ]
}
```

This query looks like it should filter aggs by  `"NESTED_FIELD.SOME_FIELD": "1718565"`, but the filter has no effect.

```
GET my_index/_search?size=0
{
  "aggs": {
    "baseFilterAggs": {
      "filter": {
        "nested": {
          "path": "NESTED_FIELD",
          "filter": {
            "term": {
              "NESTED_FIELD.SOME_FIELD": "1718565"
            }
          }
        }
      },
      "aggs": {
        "nestedLocId": {
          "nested": {
            "path": "NESTED_FIELD"
          },
          "aggs": {
            "locIdTerms": {
              "terms": {
                "field": "NESTED_FIELD.SOME_FIELD",
                "size": 0
              }
            }
          }
        }
      }
    }
  }
}
```

When written like this, it works as expected:

```
GET my_index/_search?size=0
{
  "aggs": {
    "nestedAggs": {
      "nested": {
        "path": "NESTED_FIELD"
      },
      "aggs": {
        "hhhhhhh": {
          "filter": {
            "term": {
              "NESTED_FIELD.SOME_FIELD": "1718565"
            }
          },
          "aggs": {
            "locIdTerms": {
              "terms": {
                "field": "NESTED_FIELD.SOME_FIELD",
                "size": 0
              }
            }
          }
        }
      }
    }
  }
}
```

to quote @jpountz :

> In the first query, the filter keeps root documents that have at leas one nested document that matches the query. Since the 2nd root document has one nested document that matches, it is selected. Then we run the nested aggregation, which can see all nested docs of this root document.
> 
> On the other hand the second query first goes to the nested documents, and then only keeps those that match the filter, so there is only one bucket: the one that matches the filter.

**Comment by markharwood** [comment]
cc @elastic/es-search-aggs

**Comment by dinamic** [comment]
@PhaedrusTheGreek what happened with this bug? Have you got any feedback?

**Comment by PhaedrusTheGreek** [comment]
@dinamic this is not a bug so much as a DSL / Documentation inconsistency.   Feel free to open a discussion at https://discuss.elastic.co/c/elasticsearch

**Comment by jrodewig** [comment]
[docs issue triage]

leaving open as this is still relevant.

**Comment by polyfractal** [comment]
I'm going to close this issue.  I agree it's a tricky subject... but I'm really not sure how to best modify the docs to convey the information.  It's a relatively specific situation to try and explain, and I think hard to generalize for the docs.  If someone has a better idea how to move this information into the docs I'm all ears, but I think this issue is stale otherwise.
