### ISSUE TITLE
Platform enablement request: Please add s390x to the supported platforms and build targets.

### ISSUE THREAD

**Issue by vmorris** [elastic/elasticsearch#18429]

**Comment by clintongormley** [comment]
Sorry but we don't have the hardware to test on, so we can't support it. On top of that, there isn't an OpenJDK based JVM for s390x

**Comment by vmorris** [comment]
@clintongormley There are a few ways developers can gain access to s390x hardware for free or very little cost. One is through the [IBM Dallas Innovation Center](http://dtsc.dfw.ibm.com/MVSDS/%27HTTPD2.DSN01.PUBLIC.SHTML%28LNXTD%29%27).
Another is through the [LinuxONE Community Cloud](https://developer.ibm.com/linuxone/).

There are OpenJDK based JVM installation packages for RHEL, SUSE, and Ubuntu.
