### ISSUE TITLE
Clarify description of search timeout parameter

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#18421]
**Elasticsearch version**: 2.3.x

It will be nice to clarify the description of the search timeout parameter (https://www.elastic.co/guide/en/elasticsearch/guide/current/_search_options.html#_timeout_2):

>The timeout parameter tells the coordinating node how long it should wait before giving up and just returning the results that it already has. It can be better to return some results than none at all.

The search timeout parameter actually gets pushed down to the shards and the coordinating node just async waits for responses from the shards. The shards themselves do a best-effort (since things like document collection can be aborted but not highlighting, re-writing, etc..) to abort the query phase if it runs out of time.

**Comment by clintongormley** [comment]
This issue was moved to elastic/elasticsearch-definitive-guide#536
