### ISSUE TITLE
Rescoring as documented in reference guide broken on master

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#18439]
**Elasticsearch version**: 5.x/ current master

**JVM version**: Oracle Corporation 1.8.0_60 [Java HotSpot(TM) 64-Bit Server VM 25.60-b23]

**OS version**: Fedora release 23 (Twenty Three)

**Description of the problem including expected versus actual behavior**:

Running the rescore query as documented against a current master built fails to parse the query json. See #18424 for original discussion.

**Steps to reproduce**:
 1. Clone repository, build the source and start elasticsearch
 2. Submit the following query:

  `GET /_search{`

      "query" : {
            "match" : {
                "field1" : {
                    "operator" : "or",
                    "query" : "the quick brown",
                    "type" : "boolean"
                 }
              }
           },
          "rescore" : {
            "window_size" : 50,
            "query" : {
               "rescore_query" : {
                "match" : {
                   "field1" : {
                      "query" : "the quick brown",
                      "type" : "phrase",
                      "slop" : 2
                   }
                }
             },
             "query_weight" : 0.7,
             "rescore_query_weight" : 1.2
          }}}

Which essentially is a plain copy of the example here: https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-rescore.html

Error message I get:

    {
       "error": {
          "root_cause": [
             {
                "type": "parsing_exception",
                "reason": "Unknown key for a START_OBJECT in [rescore].",
                "line": 11,
                "col": 16
             }
          ],
          "type": "parsing_exception",
          "reason": "Unknown key for a START_OBJECT in [rescore].",
          "line": 11,
          "col": 16
       },
       "status": 400
    {
       "error": {
          "root_cause": [
             {
                "type": "parsing_exception",
                "reason": "Unknown key for a START_OBJECT in [rescore].",
                "line": 11,
                "col": 16
             }
          ],
          "type": "parsing_exception",
          "reason": "Unknown key for a START_OBJECT in [rescore].",
          "line": 11,
          "col": 16
       },
       "status": 400
    }

Found thanks to the lovely doc snippet testing by @nik9000 - hunch about what's going wrong thanks to analysis by @cbuescher

**Comment by cbuescher** [comment]
We are currently only parsing the array-syntax for the `rescore` part in SearchSourceBuilder (`"rescore" : [ {...}, {...} ]`) . We also need to support `"rescore" :  {...}`
