### ISSUE TITLE
unable to install the logstash-filter-grok plugin

### ISSUE THREAD

**Issue by superhobbit** [elastic/elasticsearch#18431]
when I install the grok,it shows this error:
`ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core-plugin-api":
In snapshot (Gemfile.lock):
logstash-core-plugin-api (= 1.10.0)

In Gemfile:
logstash-filter-geoip (>= 0) java depends on
logstash-core-plugin-api (~> 1.0) java
logstash-filter-geoip (>= 0) java depends on
  logstash-core-plugin-api (~> 1.0) java

logstash-filter-geoip (>= 0) java depends on
  logstash-core-plugin-api (~> 1.0) java

logstash-filter-geoip (>= 0) java depends on
  logstash-core-plugin-api (~> 1.0) java

logstash-filter-geoip (>= 0) java depends on
  logstash-core-plugin-api (~> 1.0) java

logstash-filter-grok (= 3.0.1) java depends on
  logstash-core-plugin-api (~> 2.0) java

logstash-core-plugin-api (= 1.10.0) java
Running bundle update will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
`

Anyone have any ideas ?
Thanks !

**Comment by clintongormley** [comment]
Please open this issue on the logstash issues list
