### ISSUE TITLE
Add Transport Profile configuration for TransportClients

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#18447]
When using the TransportClient with Sniffing, the Java application is using any of the profiles that you configure internally in the nodes. That way, is hard to separate the ports that the TransportClient uses to connect to the cluster, and the connections between the node.

Using a static pool resolves the issue, because you just use a fixed list of Ips+Hosts.

We should consider adding a new setting to the TransportClient to define a (set) of profiles (or default) so we don't use non-permitted endpoints when sniffing.

**Comment by clintongormley** [comment]
Discussed in FixItFriday. Transport profiles were added as a way to distinguish internal traffic from external traffic for security purposes, however the code introduces a lot of complexity.  Given that our goal is to remove the transport client entirely and to expose just the HTTP interface, we've decided against fixing this (and adding even more complexity).

**Comment by alehane** [comment]
Hi Clinton,

Given that the aim is to remove the transport client, does that mean that java clients will only be able to use the Node client?

Will this have the same issues with the network separation? (i.e. one network for data node interconnect connections and another for client connections).

Given that one of the stated advantages of using the Transport Client over the Node Client is that it's more adept at handling large numbers of connections, does this mean that the node client is going to be refactored? (although that page I got this information from states that it's currently being reworked :)

Thanks in advance,

Andy

**Comment by javanna** [comment]
Hi @alehane , 
as Clint said our goal is to remove the transport client entirely and to expose just the HTTP interface. That means that the node client will no longer be exposed either. In fact the whole java api will be replaced with a new REST client whici will become the only way to connect to elasticsearch in Java, as it already is the case with any other language. See #7743 .

**Comment by alehane** [comment]
Hi @javanna, 

Apologies, I read that initially, then starting doing a little more research and completely forgot that statement!

So, will elastic provide a java client, which uses the underlying REST interface but looks like the existing java api?

We make heavy usage of the java api and this would mean that we would need to make changes to our application. It would also have implications on any possible migration path, Although neither of these issues are insurmountable, they are inconvenient and they do present us with cost and planning implications.

We would also need to figure out how this would work with our custom shield realm, where the we use the java api to pass a kerberos style token and optional environment id to elastic (although, I assume this would be via the http headers) for authorisation and authentication.

Cheers,

Andy

**Comment by javanna** [comment]
Hi @alehane we will take all this into account but changes will for sure be required to migrate. Yet looking at all the changes to keep up with when using the java api (due to the fact that we use it internally), that would be the last time that we require changes, cause the REST layer comes with much stronger backwards compatibility guarantees.
