### ISSUE TITLE
Scrolling in Multi-Search

### ISSUE THREAD

**Issue by collinsauve** [elastic/elasticsearch#18454]
**Describe the feature**:

We would like to perform multiple searches at once that may contain more than 1 page of results.  From and Size are not reliable methods of paging results.

The [Multi-Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html) feature currently does not support [scrolling](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html).    If it did we would be able to page the results properly.

**Comment by jpountz** [comment]
I don't think this would play nicely given that all requests would not have the same number of pages. I think it is ok to require users to use the regular search API when scrolling.

**Comment by clintongormley** [comment]
Agreed with @jpountz- multi-search doesn't add anything useful here except complexity
