### ISSUE TITLE
Creating an index on ES 2.2.0 with mapping containing "version": { "created": "1070299" } leads to odd results (records disappear)

### ISSUE THREAD

**Issue by almico** [elastic/elasticsearch#18459]
**Elasticsearch version**: 2.2.0

**JVM version**: java version "1.8.0_92"

**OS version**: 4.2.0-35-generic #40~14.04.1-Ubuntu SMP x86_64

**Description of the problem including expected versus actual behavior**:
A mapping was uploaded to ES.
This mapping contained the following settings:
`        "settings": {
                "index": {
                        "creation_date": "1447768297037",
                        "number_of_shards": "6",
                        "uuid": "1vDn3klzQ6uWj3mxLmXxaA",
                        "version": {
                                "created": "1070299"
                        },
                        "number_of_replicas": "0"
                }
        }
`

Then the index was created by bulk inserting records using LogStash.

At the end of the insertion process, a quick look at the "settings" for the index showed what was expected, but after stopping and restarting ES, the "settings" were updated and contained the following:
`settings: {
index: {
legacy: {
routing: {
hash: {
type: "org.elasticsearch.cluster.routing.DjbHashFunction"
},
use_type: "false"
}
},
number_of_shards: "6",
creation_date: "1447768297037",
number_of_replicas: "0",
uuid: "LaCy5xaQRAyvtgC9WHLpBw",
version: {
created: "1070299",
upgraded: "2020099"
}
}
}`

If we searched for a specific record prior to restarting ES, using
`http://ourhost/ourindex/outype/d0f1124e2a98`
we got the correct record returned.

After ES restart, the very same request returns
`{
_index: "ourindex",
_type: "ourtype",
_id: "d0f1124e2a98",
found: false
}`

If we issue the following request:
`http://ourhost/ourindex/outype/d0f1124e2a98?routing=5`
we get the correct record.

**Steps to reproduce**: read above

**Provide logs (if relevant)**: none

**Comment by clintongormley** [comment]
@almico So what happens here is:

* You create an index with the incorrect version setting (you should never set the version yourself and won't be able to do so in ES 5.0 onwards)
* The new index uses the current routing scheme
* You index docs into it
* When your restart the cluster, it finds what it thinks is an old index, which it then upgrades and adds the setting to use the old hash function.

Never set the version yourself.  Like I say, you won't be able to do this in 5.0, but it's much harder to prevent in 2.x.

To fix your existing index, first close it, then set the following setting, then reopen it:

    PUT ourindex/_settings
    {
      "index.legacy.routing.hash.type": "org.elasticsearch.cluster.routing.Murmur3HashFunction"
    }
