### ISSUE TITLE
Swift support for snapshot/restore

### ISSUE THREAD

**Issue by eskibars** [elastic/elasticsearch#18452]
**Describe the feature**:
There has been a community plugin for this (https://github.com/wikimedia/search-repository-swift) but it's become out-of-date (last update: 1.7)

**Comment by clintongormley** [comment]
@nik9000 is this something we can support and test? you were involved with the wikimedia plugin

**Comment by s1monw** [comment]
The plugin has been updated to 2.3.3 I think we are good here?

**Comment by eskibars** [comment]
It certainly helps as a stop-gap.  The second question is whether we want to bring this type of functionality into Elasticsearch (so we can support it, as we have people asking for that) or be happy with it as a community plugin (which we can't support and which will certainly always lag behind)

**Comment by clintongormley** [comment]
Given that there are only 14 watchers on the github repo, perhaps it isn't yet worth us supporting this in core.  I think I'm going to close for now, but we can reopen if demand grows.
