### ISSUE TITLE
Deprecate (or remove?) the Delete-By-Query plugin

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#18469]
Now the Delete-By-Query feature has been re implemented in core (in the reindex module actually) we must decide what to do with the plugin we created for 2.0.

I'm in favor of removing it completely for 5.0 and document it as a breaking change but one might have a different opinion.

As @nik9000 commented in https://github.com/elastic/elasticsearch/pull/18329#issuecomment-220160894 :

> Remove the delete-by-query plugin. Should we just remove it in 5.0.0, call it a breaking change, and tell people to use the version in the reindex module? Is that ok because we're kind of just moving the API? It is losing some small functionality (timeouts) but it is gaining cancel, throttle, and rethrottle.

**Comment by rjernst** [comment]
+1

**Comment by clintongormley** [comment]
Remove!
