### ISSUE TITLE
Unable to start elasticsearch 2.3.2 as a service in Windows

### ISSUE THREAD

**Issue by sureshkm** [elastic/elasticsearch#18460]
**Elasticsearch version**: 2.3.2 and 2.3.3

**JVM version**: 1.7.0_55

**OS version**: Linux Mint 15 MATE 64-bit

**Description of the problem including expected versus actual behavior**:
Unable to start elasticsearch as a service. In service.bat file, the jvm parameter to executable is configured with %%JAVA_HOME%% which does not resolve the path properly. As a result, the service gets registered with invalid JAVA_HOME and fails to start elasticsearch.

"%EXECUTABLE%" //IS//%SERVICE_ID% --Startup %ES_START_TYPE% --StopTimeout %ES_STOP_TIMEOUT% --StartClass org.elasticsearch.bootstrap.Elasticsearch --StopClass org.elasticsearch.bootstrap.Elasticsearch --StartMethod main --StopMethod close --Classpath "%ES_CLASSPATH%" --JvmMs %JVM_MS% --JvmMx %JVM_MX% --JvmSs %JVM_SS% --JvmOptions %ES_JAVA_OPTS% ++JvmOptions %ES_PARAMS% %LOG_OPTS% --PidFile "%SERVICE_ID%.pid" --DisplayName "%SERVICE_DISPLAY_NAME%" --Description "%SERVICE_DESCRIPTION%" --Jvm "%%JAVA_HOME%%%JVM_DLL%" --StartMode jvm --StopMode jvm --StartPath "%ES_HOME%" %SERVICE_PARAMS%

**Steps to reproduce**:
 1. Install elasticsearch. >service.bat install
 2. Open service manager. >service.bat manager
 3. Goto JAVA tab and check the value under "Java Virtual Machine" field. The path to jvm.dll is not correct.

**Provide logs (if relevant)**:
[error] [11372] Failed creating java %JAVA_HOME%\jre\bin\server\jvm.dll
[error] [11372] The system cannot find the path specified.
[error] [11372] ServiceStart returned 1
[error] [11372] The system cannot find the path specified.

**Comment by jasontedor** [comment]
You need to set a system-level environment variable named `JAVA_HOME` that points to your Java installation. Please see the discussion on #18373 for why it is `%JAVA_HOME%` and not the value of `JAVA_HOME` when you installed the service.

Please note that Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions (should you have additional questions).
