### ISSUE TITLE
Help Aggregations Elasticsearch Curl

### ISSUE THREAD

**Issue by gleberrl** [elastic/elasticsearch#18472]
Hi,

I need to build the query below in ElasticSearch but I can not. Can someone help me? I need to use curl or other linux tool.

**Elasticsearch version**: 2.3

![image](https://cloud.githubusercontent.com/assets/19476780/15404635/cf05ae8e-1dd4-11e6-913f-d84e06864328.png)

**Comment by jasontedor** [comment]
Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions.
