### ISSUE TITLE
pkg remove fails: bogus prerm script

### ISSUE THREAD

**Issue by jelmd** [elastic/elasticsearch#18474]
**Elasticsearch version**:
2.3.0

**OS version**:
Ubuntu 15.04

**Description of the problem including expected versus actual behavior**:
`apt-get purge elasticsearch` fails because the used `prerm` script is bogus: The pure existence of the `systemctl` does not imply, that any message bus/systemd instance is installed or even running! So that's clearly a bug - if the script wanna use a certain service, it should make sure, that the service is up and running - in case of systemd `[[ -d /run/systemd/system ]]` might be a cheap test - but I'm not sure (using systemd) - please read the related documentation!

**Steps to reproduce**:
Use a ubuntu systemd "in theory capable" distro like vivid or wily, make it use upstart, i.e. install upstart,upstart-sysv and purge systemd-sysv packages, (perhaps reboot to see that upstart works wrt. to its parameters) and finally run `apt-get purge elasticsearch`.

**Provide logs (if relevant)**:
```
> + apt-get purge elasticsearch
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  elasticsearch*
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 30.8 MB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 35831 files and directories currently installed.)
Removing elasticsearch (2.3.0) ...
Stopping elasticsearch service...Failed to get D-Bus connection: Operation not permitted
dpkg: error processing package elasticsearch (--purge):
 subprocess installed pre-removal script returned error exit status 1
### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
### You can start elasticsearch service by executing
 sudo systemctl start elasticsearch.service
Errors were encountered while processing:
 elasticsearch
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

And as you see, even the suggested actions are plain wrong!

**Comment by jasontedor** [comment]
We do not support upstart, so switching away from one of the two supported init daemons (systemd or System V init) is of course going to break that assumption. We do have tests that removal on these two init systems works.

**Comment by jelmd** [comment]
Nope - you are plain wrong! Just installing upstart packages does **NOT** mean, the traditional init.d stuff isn't working anymore, it just adjusts the systemd crap, so that it doesn't any harm to the system anymore and makes the traditional init.d stuff beside upstart work.

And having a look at the mentioned script should have given you a clear hint, that the bug has nothing to do with upstart!

**Comment by jasontedor** [comment]
>> We do not support upstart[.]

This is a true statement. 

>> [S]o switching away from one of the two supported init daemons (systemd or System V init) is of course going to break that assumption.

This is also a true statement.

>> We do have tests that removal on these two init systems works.

And this is also a true statement.

By installing upstart and *not* removing systemd, you are violating the assumption that we make that only one of systemd or System V init is installed on the system. This is not an unreasonable assumption. If you remove systemd, the script is fine.

```bash
$ sudo apt-get -y install upstart upstart-sysv > /dev/null
$ sudo shutdown -r now
[ after reboot ]
$ sudo apt-get purge -y systemd > /dev/null
$ sudo apt-get install -y elasticsearch > /dev/null
$ sudo apt-cache policy elasticsearch | grep Installed
  Installed: 2.3.3
$ sudo apt-get purge elasticsearch
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  cgmanager systemd-shim
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  elasticsearch*
0 upgraded, 0 newly installed, 1 to remove and 97 not upgraded.
After this operation, 30.8 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 63497 files and directories currently installed.)
Removing elasticsearch (2.3.3) ...
Stopping elasticsearch service... * Stopping Elasticsearch Server
   ...done.
 OK
Purging configuration files for elasticsearch (2.3.3) ...
$ echo $?
0
```

**Comment by jelmd** [comment]
That's what I'm saying, your assumption is plain wrong, buggy!
You can't say, the car is red and thus the driver of it is a firefighter, always an every time!
You can't say, just because there is a /bin/ls, the OS is Linux.
You can't say, just because there is a /bin/mysqld, a MySQL DB is running on the system.
You need more examples?
 Again, what the script assumes/deduces, is _plain wrong_ and needs to be fixed!

**Comment by jasontedor** [comment]
Your analogies are poor. You didn't cleanly systemd, that is the mistake that is violating a reasonable assumption that only one of systemd or System V init is installed.

**Comment by jelmd** [comment]
Pardon? I don't want to remove the systemd package at all! And your conclusion, that systemd wasn't cleanly removed, is wrong again. And again, your assumption is plain wrong! Don't you have an expert, which is able to understand this issue?

**Comment by jasontedor** [comment]
I've tried to explain to you what we support, and the assumptions that we make. You're falling outside of that, and if you choose to say outside of that then that is your prerogative.

I like helping our users, I know that is true of the vast majority of our community, and I would still like to help you, but you're making it difficult.

I take this very seriously, and despite your poor choice of language, I've read through various [sources](http://unix.stackexchange.com/questions/196166/) [tonight](http://unix.stackexchange.com/questions/18209/detect-init-system-using-the-shell) and I've been thinking about the problem. I remain unconvinced that we should do anything differently than we are doing. Having both systemd and upstart installed so that it is compatible with System V init is just not common enough of a problem that we are going to engineer around it. And we are not going to start supporting upstart, [that ship has sailed](http://www.markshuttleworth.com/archives/1316).

> Don't you have an expert, which is able to understand this issue?

Most communities, especially open communities and *especially* open-source communities, are funded in ❤️ not 😡. You're more likely to be heard if you're constructive, which you haven't been. *Hugs*.

**Comment by jelmd** [comment]
No, what you have done is to defend the buggy implementation by repeating lame non-sense, right from the start and being disrespectful by closing this issue without waiting for an answer. You also have shown with every comment incl. with the last one, that you obviously have no clue from what you are talking about and that improving the software, reading documentation, learning new things or to investigate a little bit deeper, even so hints were already given!!!, is not your intention at all.

Sorry, but I didn't expect to have to discuss such a trivial issue with a windows user, who is obviously not qualified to work on it and thus to waste a lot of my valuable time. So you can be sure, I'll not make this mistake again ...

**Comment by clintongormley** [comment]
> So you can be sure, I'll not make this mistake again ...

Appreciated
