### ISSUE TITLE
Allow empty on_failure processor definitions

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#18493]
If an empty `on_failure` definition is defined it should basically ignore any processor related failures and just continue with next processor.

For example if not all documents have an `ip` field then these documents fail in ingest and are not be indexed. In many cases this isn't the desired behaviour. Adding an empty `on_failure` definition should fix this:

```
{
  "processors" : [
    ...
    {
      "geoip" : {
        "field" : "ip",
        "on_failure" : []
      }
    }
    ....
  ]
}
```

Currently an empty `on_failure` definition behaves the same as no `on_failure` definition and index requests with no `ip` fields fail.

**Comment by rjernst** [comment]
I think this is really trappy. It would be better to have an explicit `ignore` value, or something like that.

**Comment by bleskes** [comment]
+1 to make an explicit "ignore" command.
