### ISSUE TITLE
Move all ingest processors in core to a module?

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#18490]
This module should only contain the common processors that have external dependencies or require additional security permissions.

Not sure what the name should be. Maybe `ingest-common` or `ingest-processors`.

The main benefit would be that during development of common ingest processors, running tests becomes much quicker. Like @nik9000 mentioned [here](https://github.com/elastic/elasticsearch/issues/17317#issuecomment-200809490) as a good reason to move the percolator to a module.

**Comment by s1monw** [comment]
I think that's fine as long as we don't build modules for 20 lines of code? I think it's worth moving things out like this!
