### ISSUE TITLE
epoch_millis should accept more than 13 character digits

### ISSUE THREAD

**Issue by rbellamy** [elastic/elasticsearch#18507]
**Describe the feature**:
Currently `epoch_millis` has what appears to be an arbitrary 13 character upper limit on what can be parsed. The [date format documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html) indicates that the year range is between 1653 and 2286, and that you should use a different formatter if your values exceed that range.

Because `epoch_seconds` is a subset of the `epoch_millis` format, it too has a strange upper limit of 10 characters.

We commonly receive (incorrect) data with epoch millisecond values with more than 13 characters.

For `epoch_millis`, one might assume this low number of digits is an attempt to prevent 32 signed int overflow, but that doesn't compute.

Max signed 32 bit int is 2147483647, which is 10 digits.

The underlying library used by Elasticsearch for Date parsing is Joda Time, and uses `DateTime(millis, DateTimeZone.UTC)` to construct an immutable DateTime value from `epoch_millis` , where `millis` is a Java Long value. `millis` can certainly accept more than 13 chars of digits.

Cross-post alert:
I've asked this question in the [discussion forums](https://discuss.elastic.co/t/epoch-millis-has-a-maximum-of-13-digits-joda-time-accepts-a-long/50508) as well.

I have a PR ready to submit, pending the outcome of this discussion.

**Comment by jasontedor** [comment]
Duplicates #17936
