### ISSUE TITLE
Non descriptive enough error when reindexing incorrect data

### ISSUE THREAD

**Issue by marclop** [elastic/elasticsearch#18515]
**Elasticsearch version**: 2.3.1
**JVM version**: 1.7.0_95
**OS version**: Amazon Linux 2015.09

**Description of the problem including expected versus actual behaviour**:

Reindexing an index fails (when reindexing for the second time) because inserted types are wrong from the mapping (Field value is `""` (`string` type) when it should be `null`(`date` type), error thrown is: `mapper_parsing_exception`. The thrown error should be something like: _Failed inserting `""` into a `date` field_, I spend quite some time until I realised what was wrong, full error is:

``` json
{
  "took": 294944,
  "timed_out": false,
  "total": 16852802,
  "updated": 0,
  "created": 40,
  "batches": 7190,
  "version_conflicts": 718959,
  "noops": 0,
  "retries": 0,
  "failures": [
    {
      "index": "logstash-2016.05.06",
      "type": "syslog",
      "id": "AVSE8LgGhfFJ1TNSUrWP",
      "cause": {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse [path.field_name]",
        "caused_by": {
          "type": "illegal_argument_exception",
          "reason": "Invalid format: """
        }
      },
      "status": 400
    }
  ]
}
```

The thing is, on the first instance, it should have told me this error (indexing time), then if that did not pop up, it should have let me know about the problem on the first reindex operator (from `logstash-2016.05.06` to `logstash-new` and thrown a more descriptive error) not on the 2nd time I reindexed (from `logstash-new` to `logstash-2016.05.06` which was deleted and recreated again with proper index templates and mappings and no data)

**Steps to reproduce**:
1. Have a `date` field with a `""` value
2. Reindex index A to index B
3. Reindex index B to index C

**`_reindex` operation run**

``` json
{
  "conflicts": "proceed",
  "source": {
    "index": "logstash-new",
    "type": "syslog"
  },
  "dest": {
    "index": "logstash-2016.05.06",
    "op_type": "create"
  }
}
```

**Comment by s1monw** [comment]
this seems like a reasonable request, `Joda.java` does this and we should maybe put more context into the error message here!

**Comment by mortonsykes** [comment]
Hi all , 
I am new to ElasticSearch and I am interested in picking this one up.

**Comment by nik9000** [comment]
Sure! I'm not 100% sure this is a reindexing issue as much as it is an
indexing issue. But you can figure that out as you work on it.

**Comment by mortonsykes** [comment]
Hi i've been looking into this , It appeears this issue has already been fixed? . I have been trying to replicate the bug however I always recieve a mapper_parsing_exception ,       "type": "illegal_argument_exception",
      "reason": "Invalid format: \"\""  

I tried PUT my_index
{
  "mappings": {
    "my_type": {
      "properties": {
        "date": {
          "type": "date" 
        }
      }
    }
  }
}
then 
PUT my_index/my_type/1
{ "date": "" }

**Comment by mortonsykes** [comment]
Hi i've been looking into this , It appears this issue has already been fixed? . I have been trying to replicate the bug however I always receive a mapper_parsing_exception , "type": "illegal_argument_exception",
"reason": "Invalid format: """

`PUT my_index
{
"mappings": {
"my_type": {
"properties": {
"date": {
"type": "date"
}
}
}
}
}`

then 

`PUT my_index/my_type/1
{ "date": "" }`

**Comment by jasontedor** [comment]
No interest in almost two years, closing.
