### ISSUE TITLE
index.mapper.dynamic: false prevents automatic index creation

### ISSUE THREAD

**Issue by n3ziniuka5** [elastic/elasticsearch#18513]
Elasticsearch version: 2.3.3

JVM version:
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

OS version: Arch Linux kernel 4.5.4

**Description of the problem including expected versus actual behavior**:
if you set `index.mapper.dynamic: false` in `elasticsearch.yml` automatic index creation no longer works. That was not the case in ES 2.1, broke the upgrade from 2.1 to 2.3.

**Steps to reproduce**:
 1. Add `index.mapper.dynamic: false` to your config
 2. Add the following index template:
```json
{
  "order": 0,
  "template": "trace_*",
  "settings": {},
  "mappings": {
    "trace": {
      "dynamic": "false",
      "_source": {
        "includes": [
          "@timestamp",
          "host",
          "file",
          "message"
        ]
      },
      "properties": {
        "@timestamp": {
          "type": "date"
        },
        "file": {
          "index": "not_analyzed",
          "type": "string"
        },
        "host": {
          "index": "not_analyzed",
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    }
  },
  "aliases": {}
}
```
 3. Attempt to index a document `POST trace_20160524/trace`
```json
{
  "message": "test"
}
```

Receive the following error:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_expression",
        "resource.id": "trace_20160524",
        "index": "trace_20160524"
      }
    ],
    "type": "index_not_found_exception",
    "reason": "no such index",
    "resource.type": "index_expression",
    "resource.id": "trace_20160524",
    "index": "trace_20160524"
  },
  "status": 404
}
```

If I remove `index.mapper.dynamic: false` from config file, then index is created automatically. However, I want to keep the option, so that index is automatically created only if the mapping template was defined.

**Comment by s1monw** [comment]
maybe I misunderstand, you want the index to be created even if you send an invalid document?

**Comment by n3ziniuka5** [comment]
What do you mean? How is the document invalid? It has a single field `message` and the index mapping was defined before inserting that document, but instead I get an error that the index does not exist when it should be created automatically. If I remove the `index.mapper.dynamic: false` option, then it creates the index.

**Comment by clintongormley** [comment]
Actually, the setting in the config file has never worked correctly, see https://github.com/elastic/elasticsearch/issues/17561#issuecomment-217098396

Also, this setting can no longer be set in the config file as of 5.0, so I'm going to close this issue.
