### ISSUE TITLE
Replace aggregation `key` with formatted values

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#18518]
Many aggregations provide two representations of aggregated values, such as `key` and `key_as_string` in terms/histogram aggregations. This is annoying because this is duplicate information and the `key` return value leaks the internal representation of data in doc values. For instance this forced us to break the response of terms or range aggregations on `ip` fields when we added ipv6 support since we do not store ip addresses in a number anymore. We should return a single `key` parameter and drop `key_as_string`.

**Comment by cbuescher** [comment]
As a note, `key_as_string` however is currently used for formatting utc keys for date histograms according to the time zone specified for rounding in the query. We introduced this back in #9710, if we remove this every bucket key needs to be converted to the appropriate time zone on the user side to display the correct local time on the buckets.

**Comment by colings86** [comment]
@jpountz is this still something you think we should do?

/cc @elastic/es-search-aggs

**Comment by nik9000** [comment]
@jpountz reviving this, maybe, do you think we should just return the string valued keys? Not the "native" keys?

**Comment by jpountz** [comment]
@nik9000 Yes, we shouldn't leak the internal representation of the data to our users. It makes the API look ugly and makes changing the way our field types are implemented breaking. Ideally we would make keys go through `MappedFieldType#docValuesFormat` like we do with `docvalue_fields`?

**Comment by nik9000** [comment]
Got it.

**Comment by not-napoleon** [comment]
Related (possibly a dup of) #63898

**Comment by mitar** [comment]
I thin it would be better if one could choose between internal representation, `key_as_string`, or some other formatting. For us, we prefer internal representation and as little of changes to the key as possible. (We use then key values to construct filters and so we can pass values as-is.)

**Comment by wchaparro** [comment]
closing as not planned.
