### ISSUE TITLE
Duplicate value/getValue in Max aggregation

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#18517]
`org.elasticsearch.search.aggregations.metrics.max.Max` has both a `value` and a `geValue()` methods. It should only have one of them. Other single-metric aggs seem to be impacted as well.

cc @colings86

**Comment by kartiksomani** [comment]
I was thinking of changing value to getValue in SingleValue interface. But the metrics Cardinality and ValueCount return long, while others including SingleValue interface. 

any suggestions?

**Comment by sudheesh001** [comment]
I don't think this issue exists anymore and can be closed. `Max` only contains `getValue()` now,

**Comment by clintongormley** [comment]
thanks @sudheesh001
