### ISSUE TITLE
Enable Scrolling from a defined position

### ISSUE THREAD

**Issue by bbeda** [elastic/elasticsearch#18521]
**Describe the feature**:

At the moment, adding a scroll parameter will ignore the From parameter. This means that you cannot start scrolling from a specific offset. This could be useful in scenarios where you have a large data set and you want to jump to a specific position and load a big chunk of data.
Examples:
1. Paginated results where the scroll context expired
2. Data exports with predefined windows

**Comment by clintongormley** [comment]
Hi @bbeda 

We've discussed this already here: https://github.com/elastic/elasticsearch/issues/13494#issuecomment-217368934

Closing in favour of #13494
