### ISSUE TITLE
Remove redundant writeBlob methods in BlobContainer interface

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#18528]
The `BlobContainer` interface, used by snapshots, contains two `writeBlob` methods:

1. `void writeBlob(String blobName, InputStream inputStream, long blobSize)`
2. `void writeBlob(String blobName, BytesReference bytes)`

There is no reason for the second one that takes a `BytesReference`, as a `BytesReference` can easily be converted to an `InputStream` to be used by the first method.  We should look into removing the second method signature for `writeBlob` in favor of a simpler API.

**Comment by s1monw** [comment]
can we maybe trash it altogether and make it a reasonable interface ie `public IndexOutput createOutput()`?

**Comment by abeyad** [comment]
@s1monw
