### ISSUE TITLE
Remove multiple variations of deleting blobs from BlobContainer interface

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#18529]
Currently in the `BlobContainer` interface, there are three types of delete blob methods:

1. void deleteBlob(String blobName)
2. void deleteBlobs(Collection<String> blobNames)
3. void deleteBlobsByPrefix(String blobNamePrefix)

These methods are again redundant and present confusing semantics.  Having just one `deleteBlob(String blobName)` is the only method that can be truly atomic (can not atomically delete a collection of blobs) and it avoids complex exception handling (what do we do if some of the blobs exist, but not others?).

**Comment by tlrx** [comment]
I agree it's confusing. The `deleteBlobs(Collection blobNames)` can be useful for backends that support batched deletions (like Google Cloud Storage or S3) but there's still some complex exception handling to do... so +1, maybe we should move everything to `deleteBlob(String blobName)`.

**Comment by s1monw** [comment]
> so +1, maybe we should move everything to deleteBlob(String blobName).

++
