### ISSUE TITLE
BlobContainer's deleteBlob method should not be lenient

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#18530]
Currently, several implementations of `BlobContainer#deleteBlob(String blobName)` are lenient - if the blob does not exist, it silently does nothing.  Instead, we should throw an IOException if the blob does not exist.  This is in accordance with `BlobContainer`'s contract as stated in https://github.com/elastic/elasticsearch/pull/18157.

Current implementations that do not conform (and silently do nothing if the blob does not exist):

1. `FsBlobContainer`
2. `HdfsBlobContainer`
3. `S3BlobContainer`
4. `AzureBlobContainer`

**Comment by gfyoung** [comment]
`S3BlobContainer`conforms <a href="https://github.com/elastic/elasticsearch/blob/e7eb664c78dce2451dbeb55db0c0b761a65b295b/plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/blobstore/S3BlobContainer.java#L114">here</a>.
`AzureBlobContainer`conforms <a href="https://github.com/elastic/elasticsearch/blob/c4d3bf472bc5eaa18a1f1ffac727110a33f89b42/plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/blobstore/AzureBlobContainer.java#L123">here</a>.
The other two implementations do not though.

**Comment by abeyad** [comment]
@gfyoung Actually, the `S3BlobContainer` does not yet conform, because this [line](https://github.com/elastic/elasticsearch/blob/e7eb664c78dce2451dbeb55db0c0b761a65b295b/plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/blobstore/S3BlobContainer.java#L112) calls `S3BlobStore.client()#deleteObject`.  The `S3BlobStore.client()` returns an instance of `AmazonS3`.  If you look at the javadoc for `AmazonS3#deleteObject`, they say that the absence of the object will not throw an exception:

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3.html#deleteObject(java.lang.String,%20java.lang.String)

The exception handling [line](https://github.com/elastic/elasticsearch/blob/e7eb664c78dce2451dbeb55db0c0b761a65b295b/plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/blobstore/S3BlobContainer.java#L114) you linked to only gets triggered if there are actual errors during deleting the object in S3, not if the object itself does not exist.

I believe its the same with `AzureBlobContainer`.  

Instead, in both S3 and Azure, we should first check for the presence of the object and if it does not exist, throw an `IOException` before deleting.

**Comment by jasontedor** [comment]
> `S3BlobContainer`conforms <a href="https://github.com/elastic/elasticsearch/blob/e7eb664c78dce2451dbeb55db0c0b761a65b295b/plugins/repository-s3/src/main/java/org/elasticsearch/cloud/aws/blobstore/S3BlobContainer.java#L114">here</a>, and `AzureBlobContainer`conforms <a href="https://github.com/elastic/elasticsearch/blob/c4d3bf472bc5eaa18a1f1ffac727110a33f89b42/plugins/repository-azure/src/main/java/org/elasticsearch/cloud/azure/blobstore/AzureBlobContainer.java#L123">here</a>.
The other two implementations do not conform though as you pointed out.

This is not correct. The documentation for `AmazonS3#deleteObject` specifies:

```
     * If attempting to delete an object that does not exist,
     * Amazon S3 returns
     * a success message instead of an error message.
```

**Comment by jasontedor** [comment]
Also, it's important to note that some exceptions that are being wrapped into `IOException`s probably should not be, for example, general client exceptions and URI syntax exceptions.

**Comment by gfyoung** [comment]
@abeyad : Hmmm...okay I see, so the correct fix would to call `blobExists` first **before** deleting.

@jasontedor : With regards to exceptions, where do we draw the line with regards to the statement <a href="https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/blobstore/BlobContainer.java#L98">here</a> in the contract?  I can agree that URI syntax errors should be excluded, but others are not as clear in my mind (e.g. exceptions associated with `Files.deleteIfExists`)

**Comment by abeyad** [comment]
> Hmmm...okay I see, so the correct fix would to call blobExists first before attempting the actual deletion.

@gfyoung yes that's correct

**Comment by tlrx** [comment]
> It's not clear what the Azure service does as it's not specified in the docs, it would have to be tested.

Same for Google Cloud Storage, I don't see any documentation about what it does.

**Comment by javanna** [comment]
Reopening as the commit was reverted, see https://github.com/elastic/elasticsearch/pull/18815#issuecomment-229898122
