### ISSUE TITLE
Unable to insert document using alias in Java API

### ISSUE THREAD

**Issue by pradeepg-telsiz** [elastic/elasticsearch#18536]
Inserting document using alias works in CLI but not from Java API

Below is the example.

From CLI:
**Create index:**
curl -XPUT 'http://localhost:9200/test1'

**Add alias:**
curl -XPOST 'http://localhost:9200/_aliases' -d '
{
    "actions" : [
        { "add" : { "index" : "test1", "alias" : "alias1" } }
    ]
}'

curl -XPOST 'http://localhost:9200/_cat/indices'
yellow open test1                                                     5 1      1  0   4.1kb   4.1kb  

curl -XGET 'http://localhost:9200/test1?pretty'

{
  "test1" : {
    "aliases" : {
      "alias1" : { }
    },
    "mappings" : {
      "indexType" : {
        "properties" : {
          "message" : {
            "type" : "string"
          },
          "post_date" : {
            "type" : "date",
            "format" : "strict_date_optional_time||epoch_millis"
          },
          "user" : {
            "type" : "string"
          }
        }
      }
    },
    "settings" : {
      "index" : {
        "creation_date" : "1464054657698",
        "number_of_shards" : "5",
        "number_of_replicas" : "1",
        "uuid" : "ZcUjvMkGSUS9FkaYjvlnxw",
        "version" : {
          "created" : "2020099"
        }
      }
    },
    "warmers" : { }
  }
}

**Add document using alias**

curl -XPUT 'http://localhost:9200/alias1/indexType/1' -d '{
    "user" : "kimchy",
    "post_date" : "2009-11-15T14:12:12",
    "message" : "trying out Elasticsearch"
}'

This will create a document inside the index.

But if I repeat the same steps from Java API it will create its own index with alias name rather than inserting document into the corresponding index.

**1. Create index**

CreateIndexRequest indexRequest = new CreateIndexRequest("test1");
        CreateIndexResponse response = client.admin().indices().create(indexRequest).actionGet();
        if (response.isAcknowledged()) {
            System.out.println("Index Created: {" + indexName + "}");
        } else {
            System.out.println("Failed to create Index: {" + indexName + "}");
        }

**Add alias**
IndicesAliasesResponse indAliasesResponse = getClient().admin().indices().prepareAliases().addAlias("test1" "alias1").execute().actionGet();

**Add document** 
JsonObject object = {}

 IndexResponse response = client
                .prepareIndex("alias1", + "testtype", 1)
                .setSource(object.toString()).execute().actionGet();

But this creates separate index with name alias1.

**Elasticsearch version**:

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by javanna** [comment]
Hi @pradeepg-telsiz this sounds weird given that the REST layer uses the java api internally. That means that if the java api cannot add a document to an alias, it is very likely that the REST layer doesn't work either. Are you working against a single cluster? Is is possible that those java api commands get sent to different clusters, one has the alias but the cluster where you index the document doesn't have it?

Your code snippets have some problems (e.g. a missing comma when you add the alias). Could you please post a complete recreation with exactly the code you are using?

**Comment by s1monw** [comment]
we have a test that verifies this works from the java API https://github.com/elastic/elasticsearch/blob/master/core/src/test/java/org/elasticsearch/aliases/IndexAliasesIT.java#L86

I can see you use `getClient()` and `client` in your code maybe you talk to different clusters?

**Comment by pradeepg-telsiz** [comment]
I am able to figure out the problem. Below is the program to reproduce.

```
public class AliasTest {

    private TransportClient client;
    String indexName = "testindex";
    String aliasName = "testIndex_alias"; // Create different index
    //String aliasName = "testindex_write_alias"; // Create record in same

    public void createTransportClient() throws UnknownHostException {

        Settings.Builder settings = Settings.settingsBuilder();
        settings.put("cluster.name", "elastic-cluster").put("client.transport.nodes_sampler_interval", "30s")
                .put("client.transport.ping_timeout", "30s").put("client.transport.ignore_cluster_name", false)
                .put("client.transport.sniff", true).put("client.transport", "TRACE");
        TransportClient client = TransportClient.builder().settings(settings).build();
        client = client.addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("localhost"), 9300));
        this.client = client;

    }

    public static void main(String[] args) throws UnknownHostException {
        AliasTest aliasTest = new AliasTest();
        aliasTest.createTransportClient();
        aliasTest.buildIndex();
        aliasTest.addAlias();
        aliasTest.addDocumnetUsingAlias();
    }

    private String source(String id, String nameValue) {
        return "{ \"id\" : \"" + id + "\", \"name\" : \"" + nameValue + "\" }";
    }

    private void addDocumnetUsingAlias() {

        IndexResponse response = client.prepareIndex(aliasName.toLowerCase(), "sometype", "1")
                .setSource(source("1", "test")).execute().actionGet();
        if (!response.isCreated())
            client.admin().indices().prepareRefresh().execute().actionGet();
        if (response.isCreated()) {
            System.out.println("Document Created");
        } else {
            System.out.println("Failed to create document");
        }
    }

    private void buildIndex() {
        CreateIndexRequest indexRequest = new CreateIndexRequest(indexName);
        CreateIndexResponse response = client.admin().indices().create(indexRequest).actionGet();
        if (response.isAcknowledged()) {
            System.out.println("Index Created: {" + indexName + "}");
        } else {
            System.out.println("Failed to create Index: {" + indexName + "}");
        }
    }

    private void addAlias() {
        IndicesAliasesResponse indAliasesResponse = client.admin().indices().prepareAliases()
                .addAlias(indexName, aliasName).execute().actionGet();
        if (indAliasesResponse.isAcknowledged()) {
            System.out.println("Alias Created: {" + aliasName + "}");
        } else {
            System.out.println("Failed to create alias: {" + aliasName + "}");
        }
    }

}
```




So index name is not case sensitive. I added the alias with camel case but while inserting I was using lower case. This was causing new index creation. Is this the expected behavior?

**Comment by s1monw** [comment]
index names are case-sensitive!

**Comment by javanna** [comment]
seems like you have found the problem @pradeepg-telsiz , this is the expected behaviour, index names are case sensitive.
