### ISSUE TITLE
Missing path.repo config in default elasticsearch.yml config file

### ISSUE THREAD

**Issue by wiibaa** [elastic/elasticsearch#18542]
Hi,

reporting live from lab of Operation course :)

The lab instructs me to setup path.repo, so I would expect that the [Path section of elasticsearch.yml](https://github.com/elastic/elasticsearch/blob/master/distribution/src/main/resources/config/elasticsearch.yml#L29-L39)  already contains it with short explanation  and commented out as it is for all others main configuration.
What do you think ?

**Comment by clintongormley** [comment]
We intentionally keep the config file limited to the most important options only.  The instructions for setting `path.repo` are in the docs which explain how to setup a file system repo.

thanks anyway
