### ISSUE TITLE
Upsert with automatic id generation failed with exception : Validation Failed: 1: id is missing;

### ISSUE THREAD

**Issue by bhernout** [elastic/elasticsearch#18541]
**Elasticsearch version**: 2.3.3

**JVM version**: 1.8

**OS version**:windows

**Description of the problem including expected versus actual behavior**:
When I try an upsert with java client without id in the insert the exception occured, but i want to create an automatic id generation.

**Steps to reproduce**:

I want to not place id in the prepareIndex method

`prepareIndex(indexName, indexType);`

The full method is :

```
public UpdateRequest createUpsertRequest(byte[] content, Offer offer){
		IndexRequestBuilder indexRequestBuilder = getElasticsearchClient().prepareIndex(indexName, indexType);
		indexRequestBuilder.setSource(content);
		IndexRequest indexRequest = indexRequestBuilder.request();
		
		UpdateRequestBuilder updateRequestBuilder = getElasticsearchClient().prepareUpdate(indexName, indexType, offer.getGuid());
		updateRequestBuilder.setDoc(content);
		UpdateRequest updateRequest = updateRequestBuilder.request();
		updateRequest.upsert(indexRequest);
		
		return updateRequest;
	}
```

**Comment by clintongormley** [comment]
You can't run an update with an automatically generated ID.  That's just a create request.

**Comment by bhernout** [comment]
Thank you for your response, but for me the problem is on the insert.

If I understand the process, the Upsert request will try to do the insert request first. And after if the insert does not work the update request will be launched.

I don't understand why I could do the insert with automatic id generation, and it does not work with inside the upsert ?

**Comment by clintongormley** [comment]
It tries to retrieve the document first, in order to update it.  If it doesn't find a document with that ID, then it inserts it (with the same ID). Using autogenerated IDs make no sense here.

**Comment by bhernout** [comment]
Thank you for you responses
