### ISSUE TITLE
Index restore overwrites index template

### ISSUE THREAD

**Issue by dhaworth** [elastic/elasticsearch#18559]
**Elasticsearch version**: 2.3.1

**JVM version**: 1.8.0_91

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:
Moving from a 1.7.1 cluster to a 2.3.1 cluster I set up a new index template in 2.3.1 through the API with the intention of restoring indexes from the 1.7.1 cluster and reindexing them to use the new template. However, whenever I restore an index from a snapshot it clobbers my new index template and replaces it with what seems to be the template of the index that was restored. I would expect that the template that I set up would be maintained instead of being overwritten. When I re-update the template it works fine (until I restore another index).

**Steps to reproduce**:
 1. Back up an index on a 1.7 cluster
 2. Add an index template with some modification of that index's template to a 2.3 cluster (change shard count, set doc_values on a field, etc.)
 3. Restore 1.7 index onto 2.3 cluster
 4. Check index template on 2.3 cluster

**Provide logs (if relevant)**:
This was in the logs at about the same time that the index finished restoring:
[_node-id_] [_index-name_] re-syncing mappings with cluster state because of types [[_type_]]

**Comment by dhaworth** [comment]
As an update to this, if I rename the index template before restoring the index it does not get overwritten, but instead I end up with two templates. I guess I would expect the settings and mappings to travel with the index through the snapshot/restore process, but I wouldn't expect a template to.

**Comment by clintongormley** [comment]
@dhaworth A template is a completely distinct entity from an index.  The index has no link to the template, it just uses it as a template when it is first created.  If you want to preserve the templates that you have in the new cluster, you should set `include_global_state` to `false`.

In fact, I think `include_global_state` should default to `false`, so I've opened https://github.com/elastic/elasticsearch/issues/18569

**Comment by dhaworth** [comment]
@clintongormley - Ah, I see. I was not aware of that setting. Thank you for pointing me in the right direction.

I was just looking into it and found this case as well, which also recommends what you're suggesting for the reasons I encountered:
https://github.com/elastic/elasticsearch/issues/15260

**Comment by clintongormley** [comment]
ah thanks @dhaworth
