### ISSUE TITLE
Potential race condition with snapshot naming

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#18551]
In very rare cases, it is possible to have two snapshots of the same name exist in a repository, one found in the cluster state as a snapshot in progress, and the other found in the repository.  This can happen when a snapshot (lets call it `snap`) exists in the repository, and we try to create another snapshot with the same name `snap`.  When trying to create the second `snap`, `SnapshotsService#createSnapshot` first updates the cluster state to include the second 'snap' snapshot as a snapshot in progress, and then calls `SnapshotsService#beginSnapshot`, which checks if a snapshot by the same name already exists.  If a snapshot by the same name does exist, an exception is thrown, which results in calling `SnapshotsService#removeSnapshotFromClusterState`.  However, this call to remove the snapshot from the cluster state simply submits a cluster state update task for the cluster service to execute in its own update thread, and so there is a tiny window when the cluster state could have a snapshot in progress with the name `snap` and the repository could have the original snapshot named 'snap' in its storage.

This affects the `SnapshotsService#deleteSnapshot` call, which looks through both the current snapshots and the snapshots in the repository storage, and it also affects `TransportGetSnapshotsAction` and `TransportSnapshotsStatusAction`, which have a very tiny window of time in which its possible to return two snapshots of the same name, or to return the current (soon-to-be-removed from the cluster state) snapshot when the snapshot in the repository storage is what was meant.

For those wondering why we don't check if the snapshot name already exists before adding the new snapshot to the cluster state's snapshots in progress, the reason is because it can present race conditions of its own.  If two requests arrive to create a snapshot of the same name at the same time, because neither has yet to be added to the cluster state, it is possible that both pass the check and subsequently both eventually get created by the snapshots service.

**Comment by clintongormley** [comment]
@abeyad is this still valid?

**Comment by abeyad** [comment]
The `deleteSnapshot` call is now safe (https://github.com/elastic/elasticsearch/pull/22313), but we still have potential issues with getting snapshots and snapshot status as outlined above.  I believe we can solve the issue of create snapshots temporarily creating a duplicate entry in the cluster state by maintaining some internal data structures on the master node containing the current snapshots, and that list is updated in a synchronized manner.  During master failover, the new master will populate its own internal data structures with the snapshot info.  This will be tricky to get right with various edge cases, but its an option for solving this issue.

**Comment by original-brownbear** [comment]
This is not an issue anymore for creating snapshots either now. We look into the repository's `index-${N}` blob before submitting any task to create a snapshot now. If we have two concurrently arriving requests only one will succeed in updating the cluster state and only after getting added to the cluster state will anything be written to the repository.
All the various efforts that eventually resulted in `org.elasticsearch.snapshots.SnapshotResiliencyTests` (and it passing) got us here -> closing.
