### ISSUE TITLE
Rename ThreadContext Persistent Headers to Request Headers

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#18555]
This change will be exposed to consumers of the `ThreadContext` after https://github.com/elastic/elasticsearch/pull/17804 is merged.

The change:
- put/get Header methods will include `Request` in the name so that the type of header is clear.

Splitting the two makes #17804 easier to backport.

**Comment by clintongormley** [comment]
@pickypg is this still relevant?

**Comment by pickypg** [comment]
@clintongormley Yeah, I'll push out a PR soon for this one. It's definitely a minor change though (just function names for clarity).
