### ISSUE TITLE
I couldn't install ICU plugin .

### ISSUE THREAD

**Issue by Tenzil** [elastic/elasticsearch#18568]
curl -XGET 'localhost:9200' 
{
  "name" : "D'Spayre",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.1",
    "build_hash" : "bd980929010aef404e7cb0843e61d0665269fc39",
    "build_timestamp" : "2016-04-04T12:25:05Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
webonise@webonise-Desktop:/usr/share/elasticsearch$ sudo /etc/init.d/elasticsearch stop
[sudo] password for webonise: 
 * Stopping Elasticsearch Server                                                                                                                                   [ OK ] 
Desktop:/usr/share/elasticsearch$ sudo bin/plugin install elasticsearch/elasticsearch-analysis-icu/2.7.0
-> Installing elasticsearch/elasticsearch-analysis-icu/2.7.0...
Trying https://download.elastic.co/elasticsearch/elasticsearch-analysis-icu/elasticsearch-analysis-icu-2.7.0.zip ...
Downloading ..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://download.elastic.co/elasticsearch/elasticsearch-analysis-icu/elasticsearch-analysis-icu-2.7.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip
-Desktop:/usr/share/elasticsearch$ sudo bin/plugin --install elasticsearch/elasticsearch-analysis-icu/2.7.0
ERROR: unknown command [--install]. Use [-h] option to list available commands

**Comment by dadoonet** [comment]
Please prefer https://discuss.elastic.co/ for questions.

read https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu.html
