### ISSUE TITLE
Allow Other methods of s3 server-side encryption

### ISSUE THREAD

**Issue by tylerfontaine** [elastic/elasticsearch#18561]
**Describe the feature**: 

Currently, by setting server_side_encryption to true, the only method that is allowed is aes256. It would be great if we could specify other s3 encryption methods, e.g. aws:kms.

For aws:kms, if the bucket has a default key, it's just a matter of including the correct header, so one possibility may be an additional parameter to specify the value of the `x-amz-server-side-encryption` header to get sent with requests. But the ability to specify an ams key to use would also be great.

**Comment by dadoonet** [comment]
Related doc: http://docs.aws.amazon.com/AmazonS3/latest/dev/client-side-using-kms-java.html

**Comment by smarks** [comment]
I would like to work on this.

**Comment by original-brownbear** [comment]
Closing here as a duplicate of https://github.com/elastic/elasticsearch/issues/41196
