### ISSUE TITLE
span_first gives unexpected results on a multi-value field

### ISSUE THREAD

**Issue by mcuelenaere** [elastic/elasticsearch#18570]
**Elasticsearch version**:
2.3.1

**JVM version**:
1.8.0_77

**OS version**:
Ubuntu 14.04.1 LTS

**Description of the problem including expected versus actual behavior**:
When performing a `span_first` query on a string field containing multiple strings, it will only match on the first element in the string array and not on any of the following strings.

Most probably this is due to [an implementation detail](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/position-increment-gap.html).

As a user, I expect span_first to work on each element of a multi-value field and not on the concatenation of all these values.

**Steps to reproduce**:
https://www.found.no/play/gist/5f69f3eea73502a78d407764f7dbb23b

**Comment by mcuelenaere** [comment]
A workaround is to create multiple string fields, one for each entry in the array of strings. However this would only work for a relatively fixed amount of array entries.

Is there another way of achieving this?

**Comment by clintongormley** [comment]
> Most probably this is due to an implementation detail.

Yes and no...  without the position increment gap the first word of each value would be indexed as synonyms (ie both in position 0), and same for the second words etc. It's just how Lucene works.

I think the only way to work around this is to use `nested` fields.

**Comment by mcuelenaere** [comment]
Yes, I just came to the same conclusion. Thanks.
