### ISSUE TITLE
Enforce that minimum_master_nodes is set to a quorum of master-eligible nodes

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#18573]
The setting minimum_master_nodes is crucial to avoid split brains in a cluster. With PR #15625 we log a warning if minimum_master_nodes is set to less than a quorum of master-eligible nodes.

In the future we could not only log a warning but also add some checks to enforce that minimum_master_nodes is properly used. Updating the setting to a value that brings it down to less than a quorum of master-eligible nodes could for example be prohibited. (Note that this might need special care for the case where the cluster is down-scaled from two to one master-eligible node).

Long term we could even think about preventing a node from joining a cluster and fail elections if it will bring minimum_master_nodes to an illegal value (and we're in production mode).

**Comment by DaveCTurner** [comment]
Closing this as it is superseded by the changes we have planned in the Zen 2 project.
