### ISSUE TITLE
Compile each Groovy script in its own classloader

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#18572]
From @rmuir: 

Creating many groovy scripts effectively creates tons of java class instances that will never be released (cached classloader in GroovyScriptEngineService = disaster).

The only way this classloader ever gets "released" is if you close() the entire GroovyScriptEngineService and then that gets garbage collected.

On the other hand, lucene expressions don't work this way. Instead we create a classloader for each script, that just has that one generated java class and nothing else, ensuring sane garbage collection, and no problems if you do this :) 

But for groovy? I think the current way we integrate groovy basically equates to a permanent memory leak for every single unique script that ever gets compiled.

**Comment by jprante** [comment]
>The only way this classloader ever gets "released" is if you close() the entire GroovyScriptEngineService and then that gets garbage collected.

You can unload Groovy classes from a `GroovyClassLoader` by

```
for (Class<?> groovyClass : groovyClassLoader.getLoadedClasses()) {
    GroovySystem.getMetaClassRegistry().removeMetaClass(c);
}
```
