### ISSUE TITLE
Build Failure: org.elasticsearch.search.aggregations.bucket.IpRangeIT.testUnmapped

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#18584]
Unable to reproduce with

gradle :core:integTest -Dtests.seed=E6A306CD108A9C82 -Dtests.class=org.elasticsearch.search.aggregations.bucket.IpRangeIT -Dtests.method="testUnmapped" -Dtests.es.logger.level=DEBUG -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=512m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:+UseCompressedOops -XX:+AggressiveOpts" -Dtests.locale=da -Dtests.timezone=Antarctica/Syowa

Build failure on windows: (http://build-us-00.elastic.co/job/es_core_master_windows-2012-r2/3179/testReport/junit/org.elasticsearch.search.aggregations.bucket/IpRangeIT/testUnmapped/)

**Comment by clintongormley** [comment]
@dakrone this looks like a timing or test issue with shadow replicas?  Could you have a look please
