### ISSUE TITLE
[feautre request]_recovery API add some userful info

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#18598]
**Describe the feature**:
GET _recovery?active_only
"name": {
    "shards": [
      {
        "stage": "INDEX",
        "translog": {
          "total_on_start": 0,
          "recovered": 0,
          "total": 0,
          "total_time_in_millis": 0,
          "percent": "100.0%"
        },
        "total_time_in_millis": 802265,
        "verify_index": {
          "total_time_in_millis": 0,
          "check_index_time_in_millis": 0
        },
        "index": {
          "size": {
            "total_in_bytes": 10796323018,
            "reused_in_bytes": 0,
            "percent": "4.6%",
            "recovered_in_bytes": 499692769
          },
          "total_time_in_millis": 802265,
          "files": {
            "total": 147,
            "recovered": 114,
            "percent": "77.6%",
            "reused": 0
          },
          "target_throttle_time_in_millis": 0,
          "source_throttle_time_in_millis": 18
        },
        "start_time_in_millis": 1464274726291,
        "id": 14,
        "source": {
          "transport_address": "ip:9323",
          "ip": "ip",
          "host": "ip",
          "name": "name:9223",
          "id": "id"
        },
        "type": "RELOCATION",
        "primary": true,
        "target": {
          "transport_address": "ip2:9323",
          "ip": "ip2",
          "host": "ip2",
          "name": "name2",
          "id": "id2"
        }
      }

is it possible to add max_bytes_per_sec size so that we can get the transfer speed?

**Comment by clintongormley** [comment]
@makeyang We don't provide rates like max-bytes-per-sec in our stats as these numbers can easily be derived from the totals we do provide, with a simple monitoring tool.
