### ISSUE TITLE
Instructions from README.textile fail

### ISSUE THREAD

**Issue by sajmmon** [elastic/elasticsearch#18597]
**Elasticsearch version**: 
elasticsearch-5.0.0-alpha2

**JVM version**: 
jdk1.8.0_65

**OS version**: 
Red Hat Enterprise Linux Workstation release 6.8 (Santiago)

**Description of the problem including expected versus actual behavior**:
 I follow instructions in README.textile and get an error.

**Steps to reproduce**:
 1. Just follow instructions 
2. Fails with: curl -XGET 'http://127.0.0.1:9200/twitter/_search?pretty=true' -d '

**Provide logs (if relevant)**:
```
[chojnasm@beechams elasticsearch-5.0.0-alpha2]$ curl -XGET 'http://127.0.0.1:9200/twitter/_search?pretty=true' -d '
 {
     "query" : {
         "matchAll" : {}
     }
 }'
```

```
{
  "error" : {
    "root_cause" : [ {
      "type" : "parsing_exception",
      "reason" : "no [query] registered for [matchAll]",
      "line" : 4,
      "col" : 22
    } ],
    "type" : "parsing_exception",
    "reason" : "no [query] registered for [matchAll]",
    "line" : 4,
    "col" : 22
  },
  "status" : 400
}
```

**Comment by nik9000** [comment]
> matchAll

I don't believe that is in the README any more.

**Comment by sajmmon** [comment]
I go forward with README And also get:

curl -XPUT http://127.0.0.1:9200/another_user/ -d '
> {
>     "index" : {
>         "numberOfShards" : 1,
>         "numberOfReplicas" : 1
>     }
> }'
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"unknown setting [index.numberOfReplicas] did you mean [index.number_of_replicas]?"}],"type":"illegal_argument_exception","reason":"unknown setting [index.numberOfReplicas] did you mean [index.number_of_replicas]?"},"status":400}

**Comment by clintongormley** [comment]
It looks like we have two READMEs:

* https://github.com/elastic/elasticsearch/blob/master/README.textile
* https://github.com/elastic/elasticsearch/blob/master/core/README.textile

It's the latter which is out of date.  Can gradle use the top level one instead?

**Comment by rjernst** [comment]
Doh, I kept misunderstanding what you meant by "can gradle use" because all I saw was this extra readme file. Until I realized there were *THREE* readme files, because the distribution also has its own copy. I'll open a PR shortly to make that use the files from the root (including notice and license).
