### ISSUE TITLE
Query string query and analyze_wildcard: true => tokenizer doesn't respect default_operator: AND

### ISSUE THREAD

**Issue by mrkamel** [elastic/elasticsearch#18592]
**Elasticsearch version**: 2.3.3
**JVM version**: openjdk 8
**OS version**: debian 8

Hi,

i'm using a custom pattern tokenizer for an email field:

```
index:
  analysis:
    tokenizer:
      alnum:
        type: pattern
        pattern: '[^a-zA-Z0-9_/]+'
```

I search via:

```
{
  "query": {
    "query_string": {
      "query":"email:email@example.com*",
      "analyze_wildcard":true,
      "default_operator":"AND"
    }
  }, "from":0,"size":30
}
```

This returns all docs having ANY of the tokens "email", "example" or "com", even though default_operator: AND is specified. It should return only docs having ALL the tokens.

This issue is only present when using the wildcard plus analyze_wildcard: true, as

```
{
  "query": {
    "query_string":{
      "query":"email:email@example.com",
      "default_operator":"AND"
    }
  },"from":0,"size":30
}
```

returns correct results. However, i of course need the wildcard for my use case (autocomplete of email addresses).

**Comment by clintongormley** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/17711

**Comment by mrkamel** [comment]
ah, perfect!

... and sry, didn't find that.
