### ISSUE TITLE
Upgrade of index to Lucene 4 fails.

### ISSUE THREAD

**Issue by alexspurling** [elastic/elasticsearch#18591]
**Elasticsearch version**: 1.7.4

**JVM version**: 1.8.0_25

**OS version**: OSX 10.11.5

**Description of the problem including expected versus actual behavior**: When upgrading an index from version 0.2 -> 1.7 -> 2.3. It appears the upgrade fails and I get the following error when loading my index in 2.3:

`The index [policy] was created before v0.90.0 and wasn't upgraded. This index should be open using a version before 2.0.0 and upgraded using the upgrade API.`

I would expect that running the upgrade process while running ES 1.7.4 would upgrade my index to a version that is compatible with ES 2.3.

**Steps to reproduce**:

I started with an index created with version 0.2. I then switched to version 1.7.4 and performed an upgrade of my index `policy`:

```
$ curl -XPOST 'http://localhost:9200/policy/_upgrade'
{"_shards":{"total":10,"successful":5,"failed":0},"upgraded_indices":{"policy":"3.6.0"}}
```

Then I start up ES 2.3.3 (using the same data location) and I see the error:

`Exception in thread "main" java.lang.IllegalStateException: The index [policy] was created before v0.90.0 and wasn't upgraded. This index should be open using a version before 2.0.0 and upgraded using the upgrade API`

Note how after doing the "upgrade", the policy version is 3.6.0. I would expect this version to be at least 4.0.0 as that is what is required by ES >2.0.

**Comment by clintongormley** [comment]
Do you have some empty shards?  I tried your recreation and had the same problem, until I reduced the number of shards to one and indexed a document.

As a workaround, and AFTER upgrading the index, you could close the index and change that setting:

    POST policy/_close
    PUT policy/_settings
    {
      "index.version.minimum_compatible": "4.0.0"
    }
    POST policy/_open

**Comment by alexspurling** [comment]
Could you point me to some documentation for how to check the number of shards I have and how to reduce the number to 1?

**Comment by clintongormley** [comment]
@alexspurling you can just look at the index settings for `number_of_shards`:

    GET policy/_settings

You can't change this value though - it is fixed at index creation time.  

If you want to see if you have any empty shards in the index, try:

    GET policy/_stats/docs?level=shards

**Comment by clintongormley** [comment]
No further feedback. Closing
