### ISSUE TITLE
Elasticsearch 5.0 alpha 2 does not starts and hangs on at heap size and quits after some time 

### ISSUE THREAD

**Issue by prashanttct07** [elastic/elasticsearch#18619]
I downloaded the tar.gz files of elasticsearch and when running the same as ./bin/elasticsearch I am not able to start the same as it gets terminated after some time : 
Below is the stack trace for same:

> [ec2-user@ip-172-31-56-201 ELK_5.alpha2]$ ./elasticsearch-5.0.0-alpha2/bin/elasticsearch
[2016-05-27 12:59:44,538][INFO ][node                     ] [Impulse] version[5.0.0-alpha2], pid[30414], build[e3126df/2016-04-26T12:08:58.960Z]
[2016-05-27 12:59:44,540][INFO ][node                     ] [Impulse] initializing ...
[2016-05-27 12:59:45,427][INFO ][plugins                  ] [Impulse] modules [lang-mustache, lang-painless, ingest-grok, reindex, lang-expression, lang-groovy], plugins []
[2016-05-27 12:59:45,470][INFO ][env                      ] [Impulse] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [19.6gb], net total_space [24.9gb], spins? [unknown], types [rootfs]
[2016-05-27 12:59:45,471][INFO ][env                      ] [Impulse] heap size [1015.6mb], compressed ordinary object pointers [true]
Killed
[ec2-user@ip-172-31-56-201 ELK_5.alpha2]$
![capture](https://cloud.githubusercontent.com/assets/6836305/15615270/e978037a-245a-11e6-99a8-f3b4fd866de4.JPG)

**Comment by jasontedor** [comment]
Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions.

A vanilla install of Elasticsearch 5.0.0-alpha2 is known to start. You might find help working through this issue if you post on the [Elastic Discourse forum](https://discuss.elastic.co).

**Comment by jasontedor** [comment]
@prashanttct07 Were you able to get this resolved? I looked for a topic on Discuss but couldn't find one. Let me know, I would be happy to help. :smile:

**Comment by prashanttct07** [comment]
Hi jason,
I was not able to get the same run on my aws instance... As I got busy with
2.3 for some task so was not able to get it posted on forum.. Also didn't
get any forum question over there for the same.

Just a question is there any memory requirement for 5.0 as I am running on
aws micro instance with 1 GB memory, so there I can run the 2.3 but not 5.0

Thanks,
Prashant Agrawal

**Comment by jasontedor** [comment]
@prashanttct07 The defaults out of the box for alpha2 are to use a 1 GB heap. You can tune this in the jvm.options file down to 512 MB (just change `-Xmx1g` to `-Xmx512m`).

**Comment by prashanttct07** [comment]
Ohh Oki,

I was considering the same as 256 as default . Thanks for the info I will
check the same and let you know in case of any issue.

Regards:
Prashant Agrawal
+91 8097606642
Skype : prashanttct07
www.futurepathfinder.com

**Comment by jasontedor** [comment]
@prashanttct07 Depending on what you're doing, 256 MB might be fine, or it might be a little light. We typically recommend half of the machine RAM for the Elasticsearch heap leaving the other half for the filesystem cache. This is assuming that you're only running Elasticsearch on the machine. If you're running other applications, you will have to adjust accordingly.
