### ISSUE TITLE
InternalEngineTests failures

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#18623]
I have found two test failures in `InternalEngineTests` that consistently fail:

1) `testDocStats`

Reproduces with:
```gradle :core:test -Dtests.seed=19501DA878395CCF -Dtests.class=org.elasticsearch.index.engine.InternalEngineTests -Dtests.method="testDocStats" -Dtests.security.manager=true -Dtests.locale=ar-SY -Dtests.timezone=Europe/Helsinki```

Seems related to the change done in https://github.com/elastic/elasticsearch/pull/18587

2) `testTranslogReplay`

I have not been able to get this to reproduce, though it has failed numerous times on the date of the creation of this issue, for example see: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/668/console

The reproduce line, FWIW:

```gradle :core:test -Dtests.seed=95E0E2968BF16DDB -Dtests.class=org.elasticsearch.index.engine.InternalEngineTests -Dtests.method="testTranslogReplay" -Dtests.security.manager=true -Dtests.locale=da -Dtests.timezone=US/Pacific```

**Comment by jasontedor** [comment]
The `testTranslogReplay` failure was addressed by #18611.
