### ISSUE TITLE
FieldSortBuilder.DOC_FIELD_NAME not available < 5.x

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#18622]
[The 2.3 docs](https://www.elastic.co/guide/en/elasticsearch/client/java-api/2.3/java-search-scrolling.html ) suggest using `FieldSortBuilder.DOC_FIELD_NAME` for `"_doc"`, but that constant doesn't seem to exist in [the 2.3 FieldSortBuilder class](https://github.com/elastic/elasticsearch/blob/2.3/core/src/main/java/org/elasticsearch/search/sort/FieldSortBuilder.java)

**Comment by cbuescher** [comment]
@PhaedrusTheGreek it appears the code snippet was backported in https://github.com/elastic/elasticsearch/pull/17579 to 2.x and 2.3 without changing the constant which should probably be `SortParseElement.DOC_FIELD_NAME` on the 2.x branches. I will correct that in the docs for 2.3 and 2.x accordingly

**Comment by cbuescher** [comment]
Corrected on 2.x and 2.3 via 3011dfd561 and 732be802514.
