### ISSUE TITLE
Add Ansible playbook to Integrations

### ISSUE THREAD

**Issue by cwurm** [elastic/elasticsearch#18636]
We have https://github.com/elastic/ansible-elasticsearch, but it's not listed in https://www.elastic.co/guide/en/elasticsearch/plugins/master/integrations.html#_supported_by_elasticsearch_2, although Puppet and Chef are.

It probably should be.

**Comment by clintongormley** [comment]
Sure.  Want to send a PR?

**Comment by cwurm** [comment]
@clintongormley sure, but I'm not sure: Does it fall under "Supported by Elasticsearch" or "Supported by community"?
