### ISSUE TITLE
How to show cluster settings "default" values ?

### ISSUE THREAD

**Issue by thechile** [elastic/elasticsearch#18645]
Using `indices.recovery.max_bytes_per_sec` as an example, it defaults to `40mb`. If i make no change to this setting via the API and it's not defined in the `.yaml` then trying to view this value using something like `curl -XGET "http://localhost:9200/_cluster/settings?pretty"` just gives me 

```
{
  "persistent" : { },
  "transient" : { }
}
```

Is there anyway to show these default values pragmatically, instead of having to reference the documentation ? I wasn't able to find a way to query cluster settings, and return all current active settings. Not just those that have been user modified from their defaults, which i assume what `_cluster/settings` returns.

It would be nice if it also included settings that have been set via `elasticsearch.yml` and not just transient/persistent cluster settings changed via the API. 

Thanks
Scott

**Comment by s1monw** [comment]
Closed by #16054 - in 5.0 you can specify `?include_defaults=true` to get all settings including node defaults
