### ISSUE TITLE
Add a `_rollover` API to simplify time-based indexing

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#18647]
Today a lot of users make use of `time-based` indices to implement usecases like logging. The main reasons why this is desirable are:

 * retention policies (certain data should be available for N days or weeks and can easily be deleted if entire indices can simply be dropped)
 * indexing performance is important such that indices with a large amount of shards are created and rolled over on a daily or weekly basis.
 * an index can not grow infinitely  (the number of shards can't be changed) and therefore the number of shards is picked to be sufficient for the time period.

Yet, this has several problems and the foremost is known as `shard-explosion` ie. to achieve the required indexing speed `12` shards are used with `1` replica each. These indices are _rolled over_ every day such that with a retention period of _1 year_ the user ends up with `24 * 365 = 8760` shards. In an ideal world we would be able to provide a system that allows to _fan out_ for indexing (have 20 shards) and roll the index over when the index is big enough to be optimal for a single shard to contain all docs but still be able to provide  desired search experience. Let's say a single shard is fine with up to _100M_ documents. That means we can sustain an indexing speed of _~12k doc/sec_ and end up with a single shard after _24h_ of constant indexing.  (all these number are just examples)
It's also common that these indices have peak times which can cause shards to fill up much quicker or there are certain days in the week where indexing is almost quite. At the end of the day the user would end up with a large number of shards that are far from ideal something like time is used to roll over indices. 

With the addition of `_shrink` API in #18270 going from X shards to 1 is easily possible such that users should be able to define their _ideal_ shard size and move from _N_ shards for fast indexing into 1 to prevent shard explosion. While making this entire process fully automatic is desired, it's also tricky since it requires state management of long running tasks. Instead, this issue proposes encapsulated  and stateless building blocks like a `_rollover` endpoint. Such an endpoint is basically just syntactic sugar that executes certain actions give some predicates, for instance:

the user creates an index with 2 aliases, one for search and one for indexing.
```
PUT logs
{
  "settings": {
    "number_of_shards": 5,
    "routing.allocation.include.box": "hot"
  },
  "aliases": {
    "logs_index": {},
    "logs_search": {}
  },
  "mappings": {}
}
```

the user then periodically calls the `_rollover` endpoint to potentially check if we need to flip the alias and roll over to a new index:

```
# creates copy of old index, templates can override 
POST logs_index/_rollover/{logs_search} # logs_index must be an alias with one index {logs_search} is optional where we add the index too
{
  "conditions": {
    "max_docs": 1000,
    "max_age": "7d",
    "max_size": "1g"
  }
}

# Response
{
  "old_index": "logs",
  "new_index": "logs-001"
}
```

The naming of the indices can either be determined by the rollover API or can be user provided which hasn't been decided yet. I personally would just append a numeric value to each index name like `logs_1, logs_2` etc. to simplify control with index templates to change `# of shards` etc. we can still add more complex solutions to the API later.  
Together with the `_shrink` API users can then move the index to a _shrink node_ and merge it to one shard.

In addition we  can also support a delete action to implement retention policies
```
DELETE logs_search/_rollover/ # logs_search must be an alias we go and check if it contains indices with a certain retention policy and take them out of the search alias and delete them
{
  "conditions": {
    "max_age": "1m"
  }
}
```

**Comment by chenryn** [comment]
There is a problem for the rollover API with time-based indices: we can search the just one `-yyyy.MM.dd` index by calculate the time-range of query. Would it be slower if we must search the whole indices through the alias because the indices name don't contain the datetime?

**Comment by clintongormley** [comment]
@chenryn you can use the field stats API (https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-field-stats.html) to figure out which indices should be queried.  Also, we've added an optimization on range queries which will check the min and max values against each shard and either (a) rewrite the range to a match_all if all documents fall within the range, (b) rewrite the range to a match_none if no documents fall into the range or (c) leave the range as is.

This will provide a big performance improvement.

**Comment by chenryn** [comment]
@clintongormley tks for your reply. The optimization on range queries was implemented in es2.3 too?

**Comment by clintongormley** [comment]
@chenryn no, only in 5

**Comment by untergeek** [comment]
Using `_rollover` in Watcher is awesome.  I will add this functionality to Curator as well.
