### ISSUE TITLE
Recovery throttling does not properly account for relocating non-primary shards

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#18640]
Relocation of non-primary shards is realized by recovering from the primary shard. `RoutingNodes` wrongly equates non-primary relocation as recovering a shard from the non-primary relocation source, however. This invalidates the checks in the `ThrottlingAllocationDecider` where the number of concurrent incoming/outgoing recoveries are bound using the settings `cluster.routing.allocation.node_concurrent_recoveries`, `cluster.routing.allocation.node_concurrent_incoming_recoveries` and `cluster.routing.allocation.node_concurrent_outgoing_recoveries`.

**Comment by s1monw** [comment]
+1 good find

**Comment by jonaf** [comment]
@ywelsch What version(s) of Elasticsearch does this bug affect?

**Comment by ywelsch** [comment]
@jonaf This only affects v5, previous versions used other mechanisms to throttle recoveries (see https://www.elastic.co/guide/en/elasticsearch/reference/2.3/recovery.html and in particular `indices.recovery.concurrent_streams`)
