### ISSUE TITLE
how to set doc a score(boost)

### ISSUE THREAD

**Issue by Fly365** [elastic/elasticsearch#18655]
Use solr to set the boost, but ES did not find can set boost, please help about this question。

bulkRequest.add(client.prepareIndex("twitter", "tweet", "8")
		        .setSource(XContentFactory.jsonBuilder()
		                    .startObject()
		                        .field("user", "tom")
		                        .field("postDate", new Date())
		                        .field("message", "score")
		                    .endObject()));

SolrInputDocument solrDoc = new SolrInputDocument();
					//solrDoc.setDocumentBoost(documentBoost);

**Comment by cbuescher** [comment]
Hi @Fly365, please use the forums at https://discuss.elastic.co/ to ask generall questions about usage.
