### ISSUE TITLE
Increasing Number of Replicas - RecoveryFailedException and RemoteTransportException and NotSerializableExceptionWrapper

### ISSUE THREAD

**Issue by cragun** [elastic/elasticsearch#18660]
**Elasticsearch version**:
  "version" : {
    "number" : "2.3.2",
    "build_hash" : "b9e4a6acad4008027e4038f6abed7f7dba346f94",
    "build_timestamp" : "2016-04-21T16:03:47Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },

**JVM version**:
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**OS version**:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04

**Description of the problem including expected versus actual behavior**:

I have a 5 node cluster. 50 indices.   110 shards.
I had previously set the number of replicas to 0 to bulk load about 5 TB of data.  Now that all the indexing is complete and all nodes are green, all shards are STARTED, I would like to, obviously, increase the number of replicas to at least 1.   

I issued the PUT to increase number_of_replicas for just one index, but the new shard gets stuck in INITIALIZING.  Upon examining the logs, I find a serious of exceptions, ranging from RecoveryFailedException, RemoteTransportException and NotSerializableExceptionWrapper. 

Logs are included below.   

**Steps to reproduce**:
increase the number of replicas for the index ( in my case from 0 to 1 )
{
    "index" : {
        "number_of_replicas" : 1
    }
} 

**Provide logs (if relevant)**:

33604	RecoveryFailedException[[d-0516-ak][0]: Recovery failed from {AVES2}{GJq4BB0NQqepIogVu94eCQ}{172.31.32.129}{172.31.32.129:9300}{master=true} into {AVES1}{an91GFrhRXKhICZMgPKRJg}{172.31.35.8}{172.31.35.8:9300}{master=true}]; nested: RemoteTransportException[[AVES2][172.31.32.129:9300][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [100] files with total size of [8gb]]; nested: RemoteTransportException[[AVES1][172.31.35.8:9300][internal:index/shard/recovery/file_chunk]]; nested: NotSerializableExceptionWrapper[i_o_exception: Input/output error];
 33605		at org.elasticsearch.indices.recovery.RecoveryTarget.doRecovery(RecoveryTarget.java:258)
 33606		at org.elasticsearch.indices.recovery.RecoveryTarget.access$1100(RecoveryTarget.java:69)
 33607		at org.elasticsearch.indices.recovery.RecoveryTarget$RecoveryRunner.doRun(RecoveryTarget.java:508)
 33608		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
 33609		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 33610		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 33611		at java.lang.Thread.run(Thread.java:745)
 33612	Caused by: RemoteTransportException[[AVES2][172.31.32.129:9300][internal:index/shard/recovery/start_recovery]]; nested: RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [100] files with total size of [8gb]]; nested: RemoteTransportException[[AVES1][172.31.35.8:9300][internal:index/shard/recovery/file_chunk]]; nested: NotSerializableExceptionWrapper[i_o_exception: Input/output error];
 33613	Caused by: [d-0516-ak][[d-0516-ak][0]] RecoveryEngineException[Phase[1] phase1 failed]; nested: RecoverFilesRecoveryException[Failed to transfer [100] files with total size of [8gb]]; nested: RemoteTransportException[[AVES1][172.31.35.8:9300][internal:index/shard/recovery/file_chunk]]; nested: NotSerializableExceptionWrapper[i_o_exception: Input/output error];
 33614		at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:135)
 33615		at org.elasticsearch.indices.recovery.RecoverySource.recover(RecoverySource.java:126)
 33616		at org.elasticsearch.indices.recovery.RecoverySource.access$200(RecoverySource.java:52)
 33617		at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:135)
 33618		at org.elasticsearch.indices.recovery.RecoverySource$StartRecoveryTransportRequestHandler.messageReceived(RecoverySource.java:132)
 33619		at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
 33620		at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
 33621		at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:300)
 33622		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
 33623		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 33624		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 33625		at java.lang.Thread.run(Thread.java:745)
 33626	Caused by: [d-0516-ak][[d-0516-ak][0]] RecoverFilesRecoveryException[Failed to transfer [100] files with total size of [8gb]]; nested: RemoteTransportException[[AVES1][172.31.35.8:9300][internal:index/shard/recovery/file_chunk]]; nested: NotSerializableExceptionWrapper[i_o_exception: Input/output error];
 33627		at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:453)
 33628		at org.elasticsearch.indices.recovery.RecoverySourceHandler.recoverToTarget(RecoverySourceHandler.java:133)
 33629		... 11 more
 33630	Caused by: RemoteTransportException[[AVES1][172.31.35.8:9300][internal:index/shard/recovery/file_chunk]]; nested: NotSerializableExceptionWrapper[i_o_exception: Input/output error];
 33631		Suppressed: RemoteTransportException[[AVES1][172.31.35.8:9300][internal:index/shard/recovery/file_chunk]]; nested: NotSerializableExceptionWrapper[i_o_exception: Input/output error];
 33632		Caused by: NotSerializableExceptionWrapper[i_o_exception: Input/output error]
 33633			at sun.nio.ch.FileDispatcherImpl.force0(Native Method)
 33634			at sun.nio.ch.FileDispatcherImpl.force(FileDispatcherImpl.java:76)
 33635			at sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:388)
 33636			at org.apache.lucene.util.IOUtils.fsync(IOUtils.java:392)
 33637			at org.apache.lucene.store.FSDirectory.fsync(FSDirectory.java:288)
 33638			at org.apache.lucene.store.FSDirectory.sync(FSDirectory.java:232)
 33639			at org.apache.lucene.store.FileSwitchDirectory.sync(FileSwitchDirectory.java:170)
 33640			at org.apache.lucene.store.FilterDirectory.sync(FilterDirectory.java:78)
 33641			at org.apache.lucene.store.FilterDirectory.sync(FilterDirectory.java:78)
 33642			at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
 33643			at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:419)
 33644			at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
 33645			at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
 33646			at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:300)
 33647			at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
 33648			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 33649			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 33650			at java.lang.Thread.run(Thread.java:745)
 33651		Suppressed: RemoteTransportException[[AVES1][172.31.35.8:9300][internal:index/shard/recovery/file_chunk]]; nested: NotSerializableExceptionWrapper[i_o_exception: Input/output error];
 33652		Caused by: NotSerializableExceptionWrapper[i_o_exception: Input/output error]
 33653			at sun.nio.ch.FileDispatcherImpl.force0(Native Method)
 33654			at sun.nio.ch.FileDispatcherImpl.force(FileDispatcherImpl.java:76)
 33655			at sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:388)
 33656			at org.apache.lucene.util.IOUtils.fsync(IOUtils.java:392)
 33657			at org.apache.lucene.store.FSDirectory.fsync(FSDirectory.java:288)
 33658			at org.apache.lucene.store.FSDirectory.sync(FSDirectory.java:232)
 33659			at org.apache.lucene.store.FileSwitchDirectory.sync(FileSwitchDirectory.java:170)
 33660			at org.apache.lucene.store.FilterDirectory.sync(FilterDirectory.java:78)
 33661			at org.apache.lucene.store.FilterDirectory.sync(FilterDirectory.java:78)
 33662			at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:468)
 33663			at org.elasticsearch.indices.recovery.RecoveryTarget$FileChunkTransportRequestHandler.messageReceived(RecoveryTarget.java:419)
 33664			at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
 33665			at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
 33666			at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:300)
 33667			at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
 33668			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 33669			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 33670			at java.lang.Thread.run(Thread.java:745)

**Comment by jasontedor** [comment]
> i_o_exception: Input/output error

I think that you have a hardware issue.

**Comment by cragun** [comment]
hey Jason.. thanks for the quick input..

ya.. I would think too that an IO error would be hardware... yet the system shows no signs thereof.   I can index new docs.. individually and in bulk.  Across all nodes and shards.  So ES, at least parts of ES, seemly have no issues with the drives.   

The OS sees no issues with the drive array either. (see log below).

Any other thoughts... ?






ubuntu@ip-172-31-35-8:~$ sudo mdadm --detail /dev/md127
/dev/md127:
        Version : 1.2
  Creation Time : Tue May 24 03:47:38 2016
     Raid Level : raid0
     Array Size : 2097149952 (2000.00 GiB 2147.48 GB)
   Raid Devices : 4
  Total Devices : 4
    Persistence : Superblock is persistent

    Update Time : Mon May 30 19:58:18 2016
          State : clean 
 Active Devices : 4
Working Devices : 4
 Failed Devices : 0
  Spare Devices : 0

     Chunk Size : 512K

    Number   Major   Minor   RaidDevice State
       0     202       96        0      active sync   /dev/xvdg
       1     202      112        1      active sync   /dev/xvdh
       2     202      128        2      active sync   /dev/xvdi
       4     202       80        3      active sync   /dev/xvdf

**Comment by jasontedor** [comment]
> yet the system shows no signs thereof.

It is showing a sign, this I/O error that is coming from inside the JVM. I think that you need to run full diagnostics on your machine. Since this is in an fsync, it's likely a failing disk so maybe check the SMART status but I wouldn't rule out other components as well.

> Any other thoughts... ?

Nope, this is really the tell-tale sign of a hardware failure.

**Comment by cragun** [comment]
cool.  On it.  Ill update my results when I have some.  thanks for the insight.

**Comment by cragun** [comment]
Hey, one more thought though that I think works in contrary to the prevailing theory...

I have tried initiating a replica from every combination of Nodes, to every combination of nodes.
A->B, B->A, A->C,C->B,C->A   etc...  To keep things simple, i particularly tested indices with single shards.  So adding a simple replica would only affect one targeted machine.

yet, they all fail with the same error.  I do find it very improbably that all machines are failing with the same error.  

would you disagree?

**Comment by jasontedor** [comment]
That is definitely suspicious, but I've seen bum batches of hardware before. The string "Input/output error" comes from Linux and is passed all the way back up to the application when the `fsync` calls returns with error. Have you checked the SMART status? How about `dmesg` or `/var/log/kern.log`? I'm not ruling out that there is something else going on, but since this is still screaming hardware issue to me I think we should continue pursuing that path until going down another.

**Comment by cragun** [comment]
OK,... we are on to something  ( and it probably points to me making a newbie error.. but not sure yet )...

kern.log is chock full of "bio too big device..."

Im reading up on how to solve this... but I thought Id post where Im at in the interim...



May 31 16:05:30 ip-172-31-35-8 kernel: [240732.201722] bio too big device xvdf (1024 > 256)
May 31 16:05:30 ip-172-31-35-8 kernel: [240732.204391] bio too big device xvdg (1024 > 256)
May 31 16:05:30 ip-172-31-35-8 kernel: [240732.207031] bio too big device xvdh (1024 > 256)
May 31 16:05:30 ip-172-31-35-8 kernel: [240732.209817] bio too big device xvdi (1024 > 256)
May 31 16:05:30 ip-172-31-35-8 kernel: [240732.212528] bio too big device xvdf (736 > 256)
May 31 16:05:31 ip-172-31-35-8 kernel: [240732.819248] bio too big device xvdf (288 > 256)
May 31 16:05:31 ip-172-31-35-8 kernel: [240732.821968] bio too big device xvdg (1024 > 256)
May 31 16:05:31 ip-172-31-35-8 kernel: [240732.824635] bio too big device xvdh (1024 > 256)
May 31 16:05:31 ip-172-31-35-8 kernel: [240732.827323] bio too big device xvdi (1024 > 256)
May 31 16:05:31 ip-172-31-35-8 kernel: [240732.830035] bio too big device xvdf (1024 > 256)
May 31 16:05:31 ip-172-31-35-8 kernel: [240732.832698] bio too big device xvdg (1024 > 256)
May 31 16:05:31 ip-172-31-35-8 kernel: [240732.835400] bio too big device xvdh (1024 > 256)
May 31 16:05:31 ip-172-31-35-8 kernel: [240732.838107] bio too big device xvdi (1024 > 256)

**Comment by s1monw** [comment]
@cragun can we close this - seems like a HW issue on your end?

**Comment by cragun** [comment]
Yup. It does.  Thanks.

**Comment by jasontedor** [comment]
Thanks @cragun. Good luck!

**Comment by skyrocknroll** [comment]
In aws i3 instances switch to `sudo apt install linux-aws`
