### ISSUE TITLE
Why is lucene query execution time more than query's "took" value, according to Profile API?

### ISSUE THREAD

**Issue by apanimesh061** [elastic/elasticsearch#18693]
There is a query that was taking 3 seconds so I thought of profiling it using the `Profile API`.
You can see the result below:
```
{
  "took": 125241,
  "timed_out": false,
  "_shards": {
    "total": 24,
    "successful": 24,
    "failed": 0
  },
  "hits": {
    "total": 265076,
    "max_score": 3,
    "hits": [...]
  },
  "profile": {
    "shards": [
      {
        "id": "[klNxl8HWTyqF-f8BRBbiiA][index][0]",
        "searches": [
          {
            "query": [
              {
                "query_type": "BooleanQuery",
                "lucene": "...",
                "time": "247695.9417ms",
.
.
.
.
            "rewrite_time": 505668,
            "collector": [
              {
                "name": "SimpleFieldCollector",
                "reason": "search_top_hits",
                "time": "110.2805510ms"
              }
            ]
          }
        ]
      }
    ]
  }
}
```
I cannot understand when the value of `took` is `125241 ms`, how come the top-level Lucene query and the rewrite time are greater than this value? Am I missing something here?

ES Version: 2.3.3
Java: 1.8

**Comment by clintongormley** [comment]
@polyfractal any ideas?

**Comment by polyfractal** [comment]
@apanimesh061 Could you gist up somewhere the full output of the profiler response?  The short answer is I'm not sure.  It might be a recursive-style bug where timings are recorded multiple times, or perhaps one of the leaf components in your query isn't behaving correctly.

Note: the `rewrite` time is in nanoseconds, so that's only 0.5ms.  But the rest of the time looks strange, I agree :)

**Comment by apanimesh061** [comment]
@polyfractal I have added the whole output [here](https://gist.github.com/apanimesh061/49ae3208287ced5d7ca33b125b2fbd27).

**Comment by polyfractal** [comment]
Thanks @apanimesh061, that helped a bunch!

@jpountz, it looks like my assumptions about method invocation order/dependence may be wrong?  Timings assume that the `breakdown` for each component are "independent" and do not include their children times.  E.g. the `score()` of a boolean query does not include the timing of `score()` for the children.

But looking closer, I think this is wrong.  For example, I'm looking at `ConjunctionScorer`, and it's `score()` method calls the `score()` of all it's children.  I imagine this is similar for the other methods (nextDoc, etc)...and it makes sense, as the Boolean would need to call down to all of it's children.

So I think the `breakdown` timings are actually inclusive of children already.  This seems to be backed up by the timings:

```
"query_type": "GlobalOrdinalsQuery",
"lucene": "GlobalOrdinalsQuery{joinField=_parent#influencer}",
"time": "17080.18500ms",
"breakdown": {
  "score": 4154770,
  "create_weight": 19246,
  "next_doc": 25930,
  "match": 3595232475,
  "build_scorer": 31100,
  "advance": 9849058759
},
"children": [
  {
    "query_type": "TermQuery",
    "lucene": "_type:post",
    "time": "3631.662722ms",
    "breakdown": {
      "score": 0,
      "create_weight": 15276,
      "next_doc": 9534,
      "match": 0,
      "build_scorer": 23276,
      "advance": 3631614636
    }
  }
]
```

- `TermQuery`:  breakdown == 3631.662722 == reported time
- `GlobalOrdinalsQuery`: breakdown == 13448.52228 != reported time

But if you add the child's time to the breakdown (13448.52228 + 3631.662722) you get the reported time of 17080.18500.

Further, the top-level breakdown comes out to 101,065ms, which is suspiciously close to the took time of 116,727ms (minus some non-profiled overhead).  Whereas the reported time is over double that.

So I think we can just [remove the recursive part of the calculation](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/profile/query/InternalQueryProfileTree.java#L234-L237) and everything should work?

Simple change, but I'm afraid I've over-simplified how Lucene works, would be interested in hearing what you think. :)

**Comment by apanimesh061** [comment]
@polyfractal 
So, basically you mean to say is that the time on a single node is already inclusive of the times of its children but due to that recursive function they are being added again?

**Comment by polyfractal** [comment]
@apanimesh061 Yep, that's correct.  

The `breakdown` timings of a node is the node + the timing of children.  But when the `"time"` summary is calculated, it recursively adds the `breakdown` + the `breakdown` of the children, so it's essentially counting the times twice.

You should be able to use just the `breakdown` time for now and get an accurate profile (although it'll be in nanoseconds, which is less pleasant to work with).

I'm out this week and part of the next, but I'll work on this as soon as I get back :)

**Comment by polyfractal** [comment]
Quick note (and reminder to self): I'm back from my traveling extravaganza and will fix this imminently.
