### ISSUE TITLE
 feature request - same field different type auto rename filed

### ISSUE THREAD

**Issue by huaoguo** [elastic/elasticsearch#18697]
**Describe the feature**:
I know elasticsearch couldn't process same field with different type. I want to let the elasticsearch auto rename the field name, then it could be processed.

Ex:
{ name: 'elasticsearch' }
{ name: { first: 'elastic', last: 'search' } }

process first log is ok, when process the second, the name is not string type, but object. Could elasticsearch auto rename the second name filed to 'name_object', then process it?

This is a big problem we met currently, if this feature could not be implement, we could just use plain text codec, not json codec.

**Comment by huaoguo** [comment]
rename field to old_field_name + 'typeof old_field_name'

**Comment by clintongormley** [comment]
@huaoguo we can't do things like this automatically, but you will be able to with the ingest pipelines coming in 5.0
