### ISSUE TITLE
Make constant score queries eligible for caching

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#18700]
I see users using `range` and other constant score queries under `bool.must` rather than under `bool.filter`, which means that they currently aren't considered for filter caching.

Would it make sense to rewrite (during the coordinating node rewrite process) eg `range` queries as `constant_score: { filter: { range...` so that users get the benefit of caching regardless?

**Comment by jpountz** [comment]
If we want to do this, we don't even need to add a rewrite phase, we could just make the parser wrap the query inside of a ConstantScoreQuery.

**Comment by rpeddacama** [comment]
I am interested in working on this ticket. Could you please let me know the next steps to proceed further. Thanks.

**Comment by jpountz** [comment]
There are two ways to tackle this: either modify RangeQueryBuilder.toQuery to wrap the produced query in a ConstantScoreQuery, or modify the `rangeQuery` method of the MappedFieldType implementations to wrap the produced query in a ConstantScoreQuery. I think I like the latter better. @rjernst Do you have an opinion?

**Comment by mayya-sharipova** [comment]
@rpeddacama Do you still like to work on this issue? Thanks

**Comment by mayya-sharipova** [comment]
cc @elastic/es-search-aggs

**Comment by javanna** [comment]
We have no concrete plans on addressing this, closing.
