### ISSUE TITLE
Field stats API returns results for _all when specific indices are requested

### ISSUE THREAD

**Issue by Bargs** [elastic/elasticsearch#18706]
**Elasticsearch version**: 2.3.3

**Description of the problem including expected versus actual behavior**:

This came up while debugging a [Kibana issue](https://github.com/elastic/kibana/issues/5739). On the Discover page in Kibana we do a field stats request to figure out which indices to query for a certain time range before pulling back actual results. A couple of users have reported that they're seeing documents from *all* of their indices in Discover instead of just their index pattern. I asked them to provide an example of the field stats request/response, and this is what I got:

URL:
`https://xxx/elasticsearch/logstash-*/_field_stats?level=indices`

Request Payload:
```
{"fields":["@timestamp"],"index_constraints":{"@timestamp":{"max_value":{"gte":1464883025215,"format":"epoch_millis"},"min_value":{"lte":1464883925215,"format":"epoch_millis"}}}}
```

Response Payload:
```
{"_shards":{"total":80,"successful":80,"failed":0},"indices":{"_all":{"fields":{"@timestamp":{"max_doc":200008,"doc_count":200008,"density":100,"sum_doc_freq":800032,"sum_total_term_freq":-1,"min_value":1463589044264,"min_value_as_string":"2016-05-18T16:30:44.264Z","max_value":1464883879721,"max_value_as_string":"2016-06-02T16:11:19.721Z"}}}}}
```

So you can see, despite requesting `logstash-*` in the URL, the API is returning results for `_all`. I couldn't find anything in the docs or existing issues about this, so I thought it might be a bug.

@lifeofguenter If there are any additional details you can provide about your setup that might help reproduce the issue, please add them here.

**Comment by lifeofguenter** [comment]
This was a problem with my nginx setup modifying the request - not a problem with kibana or es. Thanks again @Bargs for helping out a lot!

**Comment by Bargs** [comment]
Thanks for the follow up @lifeofguenter !
