### ISSUE TITLE
searching on fields one by one

### ISSUE THREAD

**Issue by tarun-oodles** [elastic/elasticsearch#18716]
Hello ,
I am using elastic search in my project .I want to search on fields one by one. means if i want to search fortis hospital  then search in first field  than search in second field and so on.

then i need output like :  show all record according first field then show all record according second field and so on.

Please Help Me

Thank You.
Tarun Tyagi

**Comment by dadoonet** [comment]
Please use discuss for questions.

I saw you did. It's the best place for that.

**Comment by tarun-oodles** [comment]
Ok sorry for this i will remember next time

On Fri, Jun 3, 2016 at 3:42 PM, David Pilato <notifications@github.com>
wrote:

> Closed #18716 <https://github.com/elastic/elasticsearch/issues/18716>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elastic/elasticsearch/issues/18716#event-680948905>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AN3anAMqWjWQI8riKhqndxguABjzA7dLks5qH_4kgaJpZM4ItTx->
> .
>



-- 


[image: Oodles Technologies Pvt Ltd] <http://www.oodlestechnologies.com/>

Tarun Tyagi Java Developer, Oodles Technologies Pvt Ltd
Phone:   +91 124 4368 395
Mobile:   +91 9873552515 <http:///>
Email:     tarun.tyagi@oodlestechnologies.com
Website:  http://www.oodlestechnologies.com/
Skype:     tarun-oodles
Address: Unit No 951-955 , Tower B1, Spaze I-Tech Park , Sector 49 , Sohna
Road , Gurgaon , India , 122001
[image: Twitter] <https://twitter.com/oodlestech> [image: Facebook]
<https://www.facebook.com/OodlesTech> [image: Google +]
<https://plus.google.com/+Oodlestechnologies/posts> [image: LinkedIn]
<https://www.linkedin.com/company/oodles-technologies-pvt-ltd>

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Oodles
Technologies is not responsible for errors or omissions in this message and
denies any responsibility for any damage arising from the use of e-mail.
Any opinion and other statement contained in this message and any
attachment are solely those of the author and do not necessarily represent
those of the company
