### ISSUE TITLE
5.0 java api change - ImmutableOpenMap

### ISSUE THREAD

**Issue by brackxm** [elastic/elasticsearch#18718]
a minor breaking change in the 5.0 java api:
ImmutableOpenMap.keysIt() returns an Iterator iso a UnmodifiableIterator

this is not yet documented

**Comment by clintongormley** [comment]
thanks @brackxm - we tend not to crowd the breaking changes docs with small changes to the java API which will be highlighted by your IDE, but thanks for trying out 5.0!

**Comment by jpountz** [comment]
This reminds me of the fact that we should probably avoid leaking hppc collections into the client API and try to only use java.util collections instead.

**Comment by nik9000** [comment]
Probably, but I think we're probably better off spending effort on http client things. I'd *love* for us to say "Client is an internal interface" one day. Might be years away, but yeah.

**Comment by nik9000** [comment]
> Probably, but I think we're probably better off spending effort on http client things. I'd love for us to say "Client is an internal interface" one day. Might be years away, but yeah.

Update on this statement: we're reusing the "response" classes as part of the high level rest client so we still should do this.

**Comment by javanna** [comment]
let's close this. The leak of hppc collections is as bad as leaking lucene etc. we may address these at some later stage but not now. We are currently adding support for all the needed API to the high level REST client, focusing on feature parity with the transport client.
