### ISSUE TITLE
Using fuzziness parameter in multi_match query interferes with per field boosting

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#18710]
To reproduce, we start with an index with default settings containing two records in different shards and a query that boosts one of the fields:
```
DELETE test

PUT test/doc/1
{
  "title": "bar",
  "body": "foo"
}

PUT test/doc/2
{
  "title": "foo",
  "body": "bar"
}

GET test/doc/_search
{
  "query": {
    "multi_match": {
      "query": "foo",
      "fields": ["title^100", "body"]
    }
  }
}
```
We get back a reasonable result: 
```
{
  "took" : 98,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "tests",
      "_type" : "test",
      "_id" : "2",
      "_score" : 1.0,
      "_source" : {
        "title" : "foo",
        "body" : "bar"
      }
    }, {
      "_index" : "tests",
      "_type" : "test",
      "_id" : "1",
      "_score" : 0.0059061614,
      "_source" : {
        "title" : "bar",
        "body" : "foo"
      }
    } ]
  }
}
```

Now, add the `fuzziness` parameter to the query (the value doesn't matter as long as it doesn't interfere with matches):
```
GET test/doc/_search
{
  "query": {
    "multi_match": {
      "query": "foo",
      "fields": ["title^100", "body"],
      "fuzziness": 0
    }
  }
}
```
the result is both records are scored the same:
```
{
  "took" : 17,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "tests",
      "_type" : "test",
      "_id" : "2",
      "_score" : 1.0,
      "_source" : {
        "title" : "foo",
        "body" : "bar"
      }
    }, {
      "_index" : "tests",
      "_type" : "test",
      "_id" : "1",
      "_score" : 1.0,
      "_source" : {
        "title" : "bar",
        "body" : "foo"
      }
    } ]
  }
}
```
However, the same experiment repeated on a single shard index produces reasonable results. It looks like if the fuzziness parameter is present, queryNorm is correctly applied only on shards where the boosted field matched at least one record.

I was able to reproduce the issue on both 2.3.3 and the latest master.

The issue was originally reported on the [discussion forum](https://discuss.elastic.co/t/ne-rabotaet-boost-v-zaprosah/51648).

**Comment by clintongormley** [comment]
I thought that this might be a query norm thing which might change with BM25, but I'm seeing the same on master.  @cbuescher is this something we're doing when rewriting queries, or is this lucene level?

**Comment by imotov** [comment]
@clintongormley yes, in my experiments BM25 was affecting only the numeric value of the score but not dropping queryNorms. The strange thing is that the problem only affects shards where the boosted field doesn't match anything, which makes it look like some sort of shortcut in execution. My first thought was, maybe it's somehow related to two-phase execution. However, I was able to reproduce it on v0.90.7, v1.7.5, v2.3.3 and the current master. So it must be something else.

**Comment by cbuescher** [comment]
From looking at how we create the lucene queries, I can't see anything obvious where we might ignore the boost when fuziness is set, but I will have a closer look at it. Most of the query creation happens in MatchQuery/MultiMatchQuery but I'm not too familiar with that code yet, but I will take a look at this starting from your examples.

**Comment by cbuescher** [comment]
@imotov yes, I also suspect something on the execution level for the query. If I use one or two shards for the minimal example above, the scores for both docs are different. As soon as a third shard gets added, the scores for the query with the added "fuzziness" are the same.

**Comment by imotov** [comment]
@cbuescher yes, the 2 shard case is the same as 1 shard case, because when you have 2 shards, both records will be on the shard 1, so you are basically searching a single shard.

**Comment by cbuescher** [comment]
I wrote a test to see how the lucene query using the `fuzziness = 0` parameter gets rewritten. If the two docs reside on two different shards, the original fuzzy query `(body:foo~0 | (title:foo~0)^100.0)` gets rewritten to `(() | (title:foo)^100.0)` on one shard and to `(body:foo | ()^100.0)` on the other where no doc has the `title`field. In that case both doc scores are the same. 
In the case the docs are on the same shard, the query gets rewritten to (body:foo | (title:foo)^100.0) and doc2 scores higher, as expected. At this point I would like to know how the expectations for rewrites and scoring for these two cases are in theory on the lucene level. Maybe @jpountz or @jimferenczi have an idea where to look next?

**Comment by jimferenczi** [comment]
This 2 queries: `(() | (title:foo)^100.0)` and `(body:foo | ()^100.0)` are supposed to be normalized the same way but it doesn't work as expected because the clause `()^100` is ignored. It's the problem with queries that are expanded on the shard directly. The normalization factor for the first query is 10,000 (100*100) and the norm is equal to 0.01. This is why we have a score of 1 for hits that match this query (100 *0.01). 
The normalization factor and the norm for the second query should be the same and the score should be divided by the norm. Though the normalization factor and the norm are set to 1 because the empty boolean query `()^100` is ignored. 
I opened a ticket on Lucene land:
https://issues.apache.org/jira/browse/LUCENE-7337
