### ISSUE TITLE
minimum_should_match ignored on more_like_this query

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#18712]
Seems that while `"minimum_should_match": "99%"`, we shouldn't hit here, but we do:

```
PUT /test/docs/1 
{ 
"message": "Ge's. Japan's. Business seize. Power. What. Said. Session. An unlikely. Greatest hits of the sixties seventies and eighties this whose fourteen sixty C. jail why gw elf A Chorus radio station. Sterling, and brown. Data because. Yeah. Well. Or. She doesn't get. Last, year, it's. Actually works. Going to die for. With. That. Is. Fields. The touch of. Class. One. Gone. This. Overall. This is also. Mystery new release. Fantasy. Six. Once. So how will the. Cold. This feel. Now. Think that a. Person. Once. Was." 
}
​
PUT /test/docs/2 
{ 
"message": "One person was killed and two others sustained injuries in a collision between a tractor and a car on National Highway near foo area of bar district on Tuesday. According to the force, the spiritual leader namely doogie along with two colleagues was on its way in a car when a rashly driven tractor hit the vehicle. As a result, they died on the spot while two other sustained injuries. The injured were rushed to nearby hospital. doogie's force has registered a case." 
}
​

POST /test/_search
{
   "query": {
      "bool": {
         "must": [
            {
               "more_like_this": {
                  "fields": [
                     "message"
                  ],
                  "docs": [
                     {
                        "_index": "test",
                        "_type": "docs",
                        "_id": "1"
                     }
                  ],
                  "minimum_should_match": "99%",
                  "min_term_freq": 1,
                  "min_doc_freq": 1
               }
            }
         ]
      }
   }
}
```

**Comment by clintongormley** [comment]
@PhaedrusTheGreek please provide the ES version you're on and some description of the actual problem, without making me try to guess.

**Comment by Bonfondp** [comment]
Given the document 1 & 2 inserted in an index. When running the "morelikethis" query, we retrieve document 2 as a candidate but both document are very different and we did specified a 99% for minimum_should match.

Hope this clarify the problem.

**Comment by Bonfondp** [comment]
And @clintongormley we are using version 1.7.3

**Comment by clintongormley** [comment]
This is just a misunderstanding of how MLT works.  First, it extracts the K terms with the highest inverse doc frequency (ie the best relevance), then it applies min-should-match to those K terms.

You have two documents, one on each shard.  The query is run independently on each shard.  So it looks at the shard that holds ONLY document 2 and finds the terms on that shard with the highest IDF.  By definition, ALL of these terms are in document 2, so all of them match.

MLT works with term statistics, so having so few docs makes for meaningless tests.  Btw, if you index both docs in an index with a single shard, then this particular test passes.

**Comment by Bonfondp** [comment]
Thank you for clarifying and for providing an alternative for our tests by using only 1 shard.
