### ISSUE TITLE
Further shard / index placement control by node/racks

### ISSUE THREAD

**Issue by apatrida** [elastic/elasticsearch#18723]
For scalability sometimes you have a read heavy index you want to replicate onto other nodes, but no other indexes.  Use cases that benefit from this control:
- a batch system starts, wants access to the cluster, but wants some heavy read indexes replicated locally.  so collocate a node on the batch shard that starts with the node, replicates, then runs batches and stays up to date automatically.  You don't want any other indexes residing on this node but a full copy of the desired indexes replicated.
- a web app is running and doing really high QPS on something such as a recommendation engine or percolation, so wants a local full copy of some of the indexes, that are live and up to date, while accessing the rest of the system at the same time.
- use cases where you have write-little/read-a-billion and want a local copy per reading process, but kept up to date at all times with the writes coming in.

You can solve these by having two clusters, but that means either more machines or more processes on the same machines, and trying to balance CPU and memory usage between competing clusters that are not coordinated.

Trying to do this in one cluster, is almost possible with rack awareness, but the settings never allow real control over the behavior.  You cannot say "I want my webapp nodes to have full copies of only indexes X,Y,Z and nothing else, ever, not even on accident".  If you try this, there is always some disappointment, such as:
- you cannot do it with rack awareness on its own, that only means shards and replicas won't appear on same rack.
- you cannot do it with forced rack because that doesn't play well with auto expand replicas and each rack needs to be present so you end up with error conditions that are false and you can't safely set the replica count on the indexes without endangering the state of the cluster (yellow/red)... and some times auto expand and forced rack just don't seem to work at all together.
- you cannot do it exclude/include/require settings because the minute you do this, you break auto expand replicas which doesn't consider the correct count of nodes after considering these settings so you end up in bad error states.
- exclude/include/require is hard to use if you have old systems creating new daily indexes that do not set the exclude flag for your nodes to which you do not want the index to propagate, so is hard to fend of accidental indexes jumping onto nodes that may not be able to handle them.

So what I would propose is these settings:
- a per node setting that says "only accept indexes/replicas I specifically approve to be on my node"
- a per index setting "this index is approved for nodes with attribute X" (using attributes as allowed by shard allocation awareness) 
- the previous setting (or additional) would indicate if it is a full or balanced copy.  A full copy meaning the node receives a copy of all shards.  A balanced copy indicates that all nodes matching the approval receive some portion of one copy of the shards.

These do not require replica count to be increased or auto-expand, it basically says "I need more replicas to cover these conditions" and if the nodes all die, or one vanishes, it is not an error condition just as auto-expand wouldn't have caused it to be an error condition.

Therefore no indexes created would ever go to these nodes on accident, only approved indexes.

**Comment by clintongormley** [comment]
surely all you need is eg an attribute `pool` with values `general` and `dedicated`.

You set  `index.routing.allocation.require.pool` to `general` for all indices except for the ones you want on these special nodes, which have it set to `dedicated` instead.

> you cannot do it exclude/include/require settings because the minute you do this, you break auto expand replicas which doesn't consider the correct count of nodes after considering these settings so you end up in bad error states.

You break auto-expand-replicas `0-all`, sure, but that's a bug which we will fix (https://github.com/elastic/elasticsearch/issues/2869).  In the meantime you can just set an upper limit of the number of nodes you have in your `dedicated` pool, eg `0-5`.

> exclude/include/require is hard to use if you have old systems creating new daily indexes that do not set the exclude flag for your nodes to which you do not want the index to propagate, so is hard to fend of accidental indexes jumping onto nodes that may not be able to handle them.

Just have an index template like this:

    PUT _template/general_pool
    {
      "template": "*",
      "settings": {
        "index.routing.allocation.require.pool": "general"
      }
    }

Other than the auto-expand bug which needs fixing, I'm unclear as to what problems the above leaves unsolved?

**Comment by apatrida** [comment]
The template solves the new index creation danger, and your upper limit on auto expand doesn't really completely help.  Because you want safety in the core cluster that there are enough index replicas to be happy, and every node has one (maybe), and then also an unknown number of dedicate machines popup and vanish and want a copy of the full index while there.   Your upper bound would have to be coordinated with the dedicated machines add/remove. 

So the fix for #2869 (I read that before, seemed in doubt, and no scheduled) would help this, until then you still have risk if you set the upper bound too high and lose a machine that really is "optional"

I've also seen that auto-expand is not reliable, sometimes it just never kicks in when the setting is changed.  Maybe that is another bug somewhere else, was was some other interplay I wasn't aware of when seeing it fail.  

So trying to more or less FORCE a copy of each shard of an index into a node AND BE SURE you never have a primary there, unless there is a way I don't see to limit the shard allocation of primaries by attribute already.

see #18729 for a bigger idea covering more use cases.

**Comment by apatrida** [comment]
@clintongormley #2869 still is marked "discuss" so this whole issue remains a problem.

**Comment by clintongormley** [comment]
> #2869 still is marked "discuss" so this whole issue remains a problem.

oh I absolutely agree.  we need to improve things here.

**Comment by DaveCTurner** [comment]
This is an interesting idea, but since its opening we have not seen enough feedback that it is something we should work on. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback (including +1s).
