### ISSUE TITLE
Settings in elasticsearch.yml don't show up in /_cluster/settings API call 

### ISSUE THREAD

**Issue by hartfordfive** [elastic/elasticsearch#18724]
Currently, any cluster settings in elasticsearch.yml are not visible when doing a `GET /_cluster/settings` API call.   Without any prior setting of values via this API call, the response is simply:

```
{"persistent":{},"transient":{}}
```

It would be great to have this api call return all the current settings, including those set in the elasticsearch.yml config and even any non-defined default values.

**Comment by clintongormley** [comment]
Already fixed in 5.0.  Just add '?include_defaults' to the GET request.
