### ISSUE TITLE
What version should the low level http client have?

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#18741]
https://github.com/elastic/elasticsearch/pull/18735 proposes versioning the http client in lock step with elasticsearch, meaning the first release is going to be 5.0.0-alpha-4 or 5.0.0-beta-1. But the API is super experimental and new and we expect to change it. semver would have it be 0.something. It is compatible with pre-5.0 versions of Elasticsearch as well.

What should we do with the version? I'm labeling this a release blocker because releasing it as proposed sort of commits us to one course of action. You can't un-release code. And you shouldn't go backwards in numbers either.

**Comment by clintongormley** [comment]
The HTTP client will be a dependency of Elasticsearch and the supported API (ie the rest specs) will be tied to the Elasticsearch version, so it should live in the main repo and have the same version as ES core.

**Comment by nik9000** [comment]
> the supported API (ie the rest specs) will be tied to the Elasticsearch version,

The whole point of the REST client is that it'll work across major versions though! As it stands the low level rest client should work as far back as you are willing to try it because it is fairly un-opinionated.

> HTTP client will be a dependency of Elasticsearch

Very pedantic quibble: it'll be a dependency of Elasticsearch's tests and of at least one of Elasticsearch's modules. It probably won't be a dependency of Elasticsearch's core.

**Comment by s1monw** [comment]
> The whole point of the REST client is that it'll work across major versions though! As it stands the low level rest client should work as far back as you are willing to try it because it is fairly un-opinionated.


true - it will still have the same release cycle as ES. Here is why, there are 2 reasons to do a release on a high level:
 * bug fixes
 * new features (new APIs added to ES that we have to support)

With the time based releases we release bugfixes frequently so users of the http client can get bugfixes through that. If there is a new API that needs to be supported ES need to be release anyways so things should be consistent and just come together.

Now to the practical aspects:

 * having a different version number is confusing we have to explain which version we support in both directions.
 * using the same version as anything else in the stack (other clients taken aside - they should move too) has the advantage that it's clear what our supported version is on the upper end. 
 * the location of the client is irrelevant for BWC
 * the location of the client is extremely relevant in development and should therefor be inside the ES project. if it's not in side we need to code against snapshots again and all the trouble starts from the beginning.
