### ISSUE TITLE
Creating array of IPs

### ISSUE THREAD

**Issue by esamudio** [elastic/elasticsearch#18740]
**Elasticsearch version**: 2.3.3

**JVM version**: 1.8.0_91

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:

At first, I'm not sure if I misread the docs and this is not expected behavior, in which case, please look at this as an issue instead. Arrays of IPs don't seem to be able to be made. Whenever one pre-defines the mapping, and tries to create one, a type mismatch happens.

**Steps to reproduce**:
I'm following the ones someone suggested I follow on [the discussion board](https://discuss.elastic.co/t/how-to-store-array-of-ip/51461/2). Credit to msimos.
 1. I created a dummy index following the steps above. My dummy index is called "com".
```
curl -XPUT 'http://localhost:9200/com' -d '{
	"mappings": {
		"type": {
			"properties": {
				"ips": {
					"type": "ip"
				}
			}
		}
	}
}'
```
 2. I then indexed the sample ip array into the "com" index in the "anytype" type with id "1".

```
curl -XPOST 'http://localhost:9200/com/anytype/1' -d '{
	"ips": ["123.123.123.123", "10.0.0.1"]
}'
```
 3. This gave me a type mismatch error:
```
{
	"error": {
		"root_cause": [{
			"type": "mapper_parsing_exception",
			"reason": "failed to parse"
		}],
		"type": "mapper_parsing_exception",
		"reason": "failed to parse",
		"caused_by": {
			"type": "illegal_state_exception",
			"reason": "Mixing up field types: class org.elasticsearch.index.mapper.core.LongFieldMapper$LongFieldType != class org.elasticsearch.index.mapper.ip.IpFieldMapper$IpFieldType on field ips"
		}
	},
	"status": 400
}
```

**Comment by clintongormley** [comment]
Note, this is fixed in master

**Comment by esamudio** [comment]
Thanks for the reply! How can I upgrade to master? I understand its not an official release but I was wondering what would be the cleanest way of upgrading to that version. I could really use not having that type mismatch. Thanks again!

**Comment by jpountz** [comment]
OK I found the bug, this is unrelated to the use of arrays and is indeed fixed in master. What is happening here is that `ips` is already defined in `type` but not in `anytype`. For that cases, we have some logic that tries to borrow the mapping definitions from existing types, but it only works for types that are supported in templates currently (numbers, date and string), so it fails with ip addresses.

I will open a PR soon, but you can work around the problem by defining your ip field in the `_default_` mapping so that it will be used by all types.

**Comment by jpountz** [comment]
Actually this was fixed by #17882 so I just backported it.

**Comment by jpountz** [comment]
This will be addressed in the upcoming 2.4.0 release.

**Comment by esamudio** [comment]
@jpountz  Thanks for the update! How do I go about defining the ip field in the _default_ mapping?

**Comment by esamudio** [comment]
Is it just a PUT request with:?

{
	"_default_": {
		"_all": {
			"type": "ip"
		}
	}
}

**Comment by jpountz** [comment]
That would be something like this:

```
curl -XPUT 'http://localhost:9200/com' -d '{
    "mappings": {
        "_default_": {
            "properties": {
                "ips": {
                    "type": "ip"
                }
            }
        }
    }
}'
```

**Comment by esamudio** [comment]
thank you very much!

**Comment by esamudio** [comment]
@jpountz I think I might have found a problem as a result of the quick fix from above. It doesn't give me the "Mixing up field types" error anymore but it tells me that the IPs are not valid:

> source[{"@version":"1","@timestamp":"2016-06-27T21:16:52.085Z","domain_name":"2667500489.MARS.ORDERBOX-DNS.COM.","type":"A","ip_address":"162.251.82.124,162.251.82.125,162.251.82.252,162.251.82.253","domain_name_exact":"2667500489.MARS.ORDERBOX-DNS.COM.","domain_name_length":33,"ip_address_exact":"162.251.82.124,162.251.82.125,162.251.82.252,162.251.82.253","domain_name_segmented":["2667500489mars","order","box","dns"],"last_registered":"2016-05-01T10:00:00.000-0500"}]} MapperParsingException[failed to parse [ip_address]]; nested: IllegalArgumentException[failed to parse ip [162.251.82.124,162.251.82.125,162.251.82.252,162.251.82.253], not a valid ip address]; at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:329) at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:309) at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:436) at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:262) at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:122) at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309) at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:580) at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:559) at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:212) at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:224) at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:326) at org.elasticsearch.action.bulk.TransportShardBulkAction.shardUpdateOperation(TransportShardBulkAction.java:389) at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:191) at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68) at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639) at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279) at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271) at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75) at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376) at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.IllegalArgumentException: failed to parse ip [162.251.82.124,162.251.82.125,162.251.82.252,162.251.82.253], not a valid ip address at org.elasticsearch.index.mapper.ip.IpFieldMapper.ipToLong(IpFieldMapper.java:84) at org.elasticsearch.index.mapper.ip.IpFieldMapper.innerParseCreateField(IpFieldMapper.java:351) at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:241) at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:321) ... 23 more

Here's the mapping:

> 
> {
>     "settings": {
>         "number_of_shards": {{ num_shards }},
>         "number_of_replicas": 2,
>         "index":{
>             "analysis":{
>                "analyzer":{
>                   "keylower":{
>                      "tokenizer":"keyword",
>                      "filter":"lowercase"
>                   }
>                }
>             }
>         }
>     },
>     "mappings": {
>         "_default_": {
>             "properties": {
>                 "ip_address":{
>                     "type":"ip"
>                 }
>             }
>         },
>         "NS": {
>             "properties": {
>                 "domain_name": {
>                     "type": "string",
>                     "index": "analyzed",
>                     "analyzer":"keylower"
>                 },
>                 "domain_name_exact": {
>                     "type": "string",
>                     "index":"not_analyzed"
>                 },
>                 "domain_name_length": {
>                     "type": "integer"
>                 },
>                 "type": {
>                     "type": "string",
>                     "index": "not_analyzed"
>                 },
>                 "is_registered": {
>                     "type": "boolean"
>                 },
>                 "last_registered": {
>                     "type":   "date"
>                 },
>                 "last_deregistered": {
>                     "type":   "date"
>                 },
>                 "registered_history": {
>                     "type":   "date"
>                 },
>                 "deregistered_history": {
>                     "type":   "date"
>                 },
>                 "name_servers": {
>                     "type": "string",
>                     "index": "analyzed"
>                 },
>                 "name_servers_exact": {
>                     "type": "string",
>                     "index":"not_analyzed"
>                 },
>                 "past_name_servers": {
>                     "type": "string",
>                     "index": "analyzed"
>                 },
>                 "past_name_servers_exact": {
>                     "type": "string",
>                     "index":"not_analyzed"
>                 },
>                 "domain_name_segmented": {
>                     "type": "string",
>                     "index": "not_analyzed"
>                 },
>                 "domain_name_exact_pronounceability": {
>                     "type": "integer"
>                 },
>                 "domain_name_segmented_pronounceability": {
>                     "type": "integer"
>                 }
>             }
>         },
>         "A": {
>             "properties": {
>                 "domain_name": {
>                     "type": "string",
>                     "index": "analyzed",
>                     "analyzer":"keylower"
>                 },
>                 "domain_name_exact": {
>                     "type": "string",
>                     "index":"not_analyzed"
>                 },
>                 "domain_name_length": {
>                     "type": "integer"
>                 },
>                 "type": {
>                     "type": "string",
>                     "index": "not_analyzed"
>                 },
>                 "ip_address": {
>                     "type": "ip"
>                 },
>                 "ip_address_exact": {
>                     "type": "string",
>                     "index": "not_analyzed"
>                 }
>             }
>         }
>     }
> }

I'm not sure if this is unrelated but I've exhausted the docs and discussion at this point. I'm dealing with 20 shards(also 20 nodes), 2 replicas, 16GB of ram(8GB to heap), mlockall set to true, ran "sudo swapoff -a" on all the machines and still have problems with the GB not doing its job and nodes becoming unresponsive. Looking at the logs, I was getting errors like the one above before the GC warnings appeared, can they be related?
