### ISSUE TITLE
Elasticsearch is using deleted tmp files

### ISSUE THREAD

**Issue by karlosmid** [elastic/elasticsearch#18749]
**Elasticsearch version**: 2.3.3

**JVM version**:
`java version "1.7.0_101"
OpenJDK Runtime Environment (rhel-2.6.6.4.el6_8-x86_64 u101-b00)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)`

**OS version**: CentOS release 6.8 (Final)

**Description of the problem including expected versus actual behavior**:

Deleted temporary files are used by running elasticsearch instance

**Steps to reproduce**:
 1. Start elasticsearch
 2. Run `lsof -n | grep DEL`
 
**Expected**
No deleted files should be used by elasticsearch process

**Actual**

`java      41306 elasticsearch  DEL       REG               8,32              131176 /tmp/jna--1985354563/jna8161339909284970871.tmp`

`java      41306 elasticsearch  DEL       REG               8,32              131178 /tmp/ffidsWZY1`

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
`DEL` means a map file that has been deleted. This is okay. The first of these is the jnidispatch native dispatch library that is loaded by JNA. This is intentionally deleted after loading by JNA, and you can verify this if you start Elasticsearch with the system property `jnidispath.preserve=true`. Similarly, the `ffi` file is the remnants of JNA loading its foreign function interface library.
