### ISSUE TITLE
error when performing the sum aggregation on integer field on ES v1.7.0

### ISSUE THREAD

**Issue by david-ts** [elastic/elasticsearch#18764]
Elasticsearch version: 1.7.0

`"error": "SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[k9c_iGB6TM-myDJQElFHDA][bucketname][0]: ElasticsearchException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: UncheckedExecutionException[java.lang.NumberFormatException: Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; nested: NumberFormatException[Invalid shift value in prefixCoded bytes (is encoded value really an INT?)]; }`

I'm running into the above error when executing the "sum" aggregation on a field that is defined as integer.  However, when I changed the mapping from integer to long, the "sum" aggregation worked without any issue.

I can change the mapping from integer to long to work around my issue but is the "sum" aggregation on integer type field not supported on ES v1.7.0? I couldn't find any documentation regarding this restriction/limitation.

Thanks.

**Comment by clintongormley** [comment]
Hi @david-ts 

This sounds like you've run into a mapping bug, where the field mapping is different either in different types (visible via the mappings API) or different per shard (not visible via the mapping).

When you specified the mapping explicitly and reindexed, it would have fixed the mapping conflict.  I suggest upgrading - we no longer have these issues in ES 2.3
