### ISSUE TITLE
Mapping changes in elasticSearch 2.3.

### ISSUE THREAD

**Issue by sgc445** [elastic/elasticsearch#18760]
**Elasticsearch version:2.3.3

**JVM version**:1.7.0_55"

**OS version**:ubuntu 14.04

**While upgrading ES to 2.2.0 from 1.4.0 ,it says"analyzer on field [contains] must be set when search_analyzer is set" although i had changed "index_analyzer" to "analyzer"?Same changes was working on other record. What was i missing? 
**:

**{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"analyzer on field [contains] must be set when search_analyzer is set"}],"type":"mapper_parsing_exception","reason":"analyzer on field [contains] must be set when search_analyzer is set"},"status":400}**:

**Comment by dadoonet** [comment]
Could you provide the mapping you are sending?

**Comment by sgc445** [comment]
Mapping is given below:
"xyz": {
           "type": "multi_field",
           "fields": {
             "xyz": {
               "type": "string",
               "index": "not_analyzed"
             },
             "contains": {
               "type": "string",
               "analyzer": "containsAnalyzer",
               "search_analyzer": "standardAnalyzer"
             }
           }
        },

Thanks,

**Comment by dadoonet** [comment]
Multifield format changed.
Look at the guide.

Not an issue IMO. Closing.

Please use discuss.elastic.co if you need more help about this.
