### ISSUE TITLE
elasticsearch removing black slash when running plugin command

### ISSUE THREAD

**Issue by mhkim91** [elastic/elasticsearch#18770]
**Elasticsearch version**: 2.3.3

**JVM version**: 1.7.0_71-b14

**OS version**: Windows 7

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Add an environment variable called JAVA_HOME, and set D:\Java7u71\jdk.
 2. Set %JAVA_HOME%\bin in the PATH variable
 3. Go to the directory path of where the elasticsearch folder is. And run the following command: ./bin/plugin -i elasticsearch/marvel/latest [This is from the "Get Started" video]
4. I see the following error: ./bin/plugin: line 113: D:Java7u71jdk/bin/java: No such file or directory
5. I did change my path to forward slash and it worked, but I felt it should have worked either way.

**Provide logs (if relevant)**:

**Describe the feature**: I am just getting started with Elastic Search. I am following the video from the link: https://info.elastic.co/2016-03-AB-Test-Getting-Started-ES_Video.html?aliId=43138086 and I am currently running into an issue where the elasticsearch plugin is not properly getting the environment variable name correctly where it is removing all the blackslash. D:\Java7u71\jdk\bin. I would like to also note that the command to install the plugin no longer works and feels like there should have been some kind of comments left below the video or something.

**Comment by jasontedor** [comment]
Something does not seem right here. For example `./bin/plugin` should immediately error in a traditional Windows command prompt because `/` is not a valid path separator there. It should say something to the effect of `bin` not being recognized as a command.

So, my question for you is what terminal are you attempting to use?

> ./bin/plugin -i elasticsearch/marvel/latest

Ignoring the oddity with the slashes, this is old syntax; it should be `bin\plugin install elasticsearch marvel-agent`.

**Comment by mhkim91** [comment]
@jasontedor Sorry. I forgot to point out that I am using MINGW32 or Git Bash shell on my window machine.

**Comment by jasontedor** [comment]
> Sorry. I forgot to point out that I am using MINGW32 or Git Bash shell on my window machine.

That is as I suspected; I'm sorry, but we do not support that and it's not going to work. For example, the `plugin` script is going to check for the existence of `$JAVA_HOME/bin/java` but on Windows it should be `java.exe` because Windows.
