### ISSUE TITLE
[feature request]scroll search

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#18777]
currently there is scroll/scan mechinsm, which maintain a context for interator overall documents. 
this request is the same thing: maintain a context for search overall documents and comquer memory issue for deep paginate.

**Comment by jimferenczi** [comment]
You need to be more specific. From what I understand you're asking for something that already exists.
Closing.

**Comment by clintongormley** [comment]
Perhaps this is what you're after? https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-search-after.html#search-request-search-after

**Comment by makeyang** [comment]
@clintongormley  yeah, this is exactly what I need
