### ISSUE TITLE
Consider making the `*_bytes_per_sec` settings for a repository dynamically updateable

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#18785]
At the moment these settings can only be specified when the repository is created and changing them requires stopping any on-going (and possibly too slow) restore/snapshot, deleting the repository and adding it back again.

It could be useful for these settings to be dynamically changeable (to make the most of the hardware at hand - disks, cpu, network) and not needing to lose the data already transferred and the already spent time with.

**Comment by ywelsch** [comment]
@tlrx and I discussed this. Implementing this feature is not easy, as it requires both changes to the way repository-level settings integrate with our settings infrastructure as well as the way that the rate limiter is hooked into the snapshotting / restore process. We are still interested in such a feature but we don't have immediate plan to work on it. As such, I'm going to close the issue. If anyone is interested in revived it please feel free to comment or +1.
