### ISSUE TITLE
Enormous number of file descriptors for translog file

### ISSUE THREAD

**Issue by alon-argus** [elastic/elasticsearch#18781]
Sorry, but I couldn't reproduce this bug(?). I'm just wondering if someone else has encountered that and if is fixed. Thanks.

**Elasticsearch version**:
2.0 (elasticsearch docker image)

**JVM version**:
openjdk 1.8.0_72-internal (elasticsearch docker image)

**OS version**:
Ubuntu 14.04.3 LTS

**Description of the problem including expected versus actual behavior**:
Around 1 million of file descriptors for the translog file.

**Steps to reproduce**:
 Sorry, didn't find how.

**Provide logs (if relevant)**:

```
...
java    3897 pollinate *297r   REG              202,1 210700529 3035985 /usr/share/elasticsearch/data/elasticsearch/nodes/0/indices/logstash-2016.05.18/3/translog/translog-1.tlog
java    3897 pollinate *298r   REG              202,1 210700529 3035985 /usr/share/elasticsearch/data/elasticsearch/nodes/0/indices/logstash-2016.05.18/3/translog/translog-1.tlog
java    3897 pollinate *299r   REG              202,1 210700529 3035985 /usr/share/elasticsearch/data/elasticsearch/nodes/0/indices/logstash-2016.05.18/3/translog/translog-1.tlog
java    3897 pollinate *300r   REG              202,1 210700529 3035985 /usr/share/elasticsearch/data/elasticsearch/nodes/0/indices/logstash-2016.05.18/3/translog/translog-1.tlog
... (around 1M of this lines)
```

**Comment by s1monw** [comment]
it might be this: https://github.com/elastic/elasticsearch/pull/15762

can you please upgrade I am sure this is fixed now. If you can reproduce in a newer version please reopen. 

btw. there is no official (elasticsearch docker image)
