### ISSUE TITLE
Make transport port config more flexible in discovery-aws plugin

### ISSUE THREAD

**Issue by xavi-** [elastic/elasticsearch#18790]
As a follow up for http://stackoverflow.com/q/37668141

Ultimately the proposal was to add something similar to Google Cloud Engineer's [`--metadata=es_port`](https://github.com/elastic/elasticsearch-cloud-gce#changing-default-transport-port)  to discovery-aws.

This change will help support ES in containerized environment.

**Comment by danielmitterdorfer** [comment]
I am against adding this, as the typical solution in containerized environments is to use a cluster manager (see also [my answer in the related Discuss thread](https://discuss.elastic.co/t/overriding-tcp-publish-port-breaks-clustering-when-elasticsearch-is-in-a-container/52135/2?u=danielmitterdorfer)).

**Comment by dadoonet** [comment]
@danielmitterdorfer So we should remove support for this in GCE as well? Basically remove those lines: https://github.com/elastic/elasticsearch/blob/master/plugins/discovery-gce/src/main/java/org/elasticsearch/discovery/gce/GceUnicastHostsProvider.java#L227-L236

**Comment by danielmitterdorfer** [comment]
This would be consistent IMHO.

**Comment by dadoonet** [comment]
I'm going to close this issue as per @danielmitterdorfer answer. I'll going to open a PR to remove this "feature" in GCE then.

**Comment by xavi-** [comment]
Sorry lost track of this thread.  Posted a reply here: https://discuss.elastic.co/t/overriding-tcp-publish-port-breaks-clustering-when-elasticsearch-is-in-a-container/52135/2

**Comment by xavi-** [comment]
In case my reply on elastic.co wasn't clear, I feel the GCE changes are a bad idea.
