### ISSUE TITLE
gradle/intellij import build Fail

### ISSUE THREAD

**Issue by sjyun** [elastic/elasticsearch#18795]
**Elasticsearch version**:
   2.3.3
**JVM version**:
   1.8
**OS version**:
   windows 8
**Description of the problem including expected versus actual behavior**:
   1. checkout elasticsearch source code 
   2. make empty project in intellj
   3. import module from exist source
   4. you must gradle idea from the root of elasticsearch before importing into intellij
   5. cmd + gradle clean idea
**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:
=======================================
Elasticsearch Build Hamster says Hello!
=======================================
  **Gradle Version        : 2.8**
  OS Info               : Windows 8 6.2 (amd64)
  JDK Version           : Oracle Corporation 1.8.0_77 [Java HotSpot(TM) 64-Bit
erver VM 25.77-b03]
  JAVA_HOME             : C:\Program Files\Java\jdk1.8.0_77

* What went wrong:
A problem occurred evaluating project ':build-tools'.
> Failed to apply plugin [id 'elasticsearch.build']
   > **Gradle 2.13 or above i**s required to build elasticsearch

**Describe the feature**:

**Comment by danielmitterdorfer** [comment]
Well, the output says that you use Gradle 2.8 but Gradle 2.13 is required to build Elasticsearch. Can you please update to Gradle 2.13 and retry?

Also, I think the Elasticsearch version that you have provided in your report is not correct. Gradle has been introduced only on master (that is 5.0-SNAPSHOT).

**Comment by sjyun** [comment]
clear
i have been confused elasticSearch branch version
 https://www.elastic.co/downloads/elasticsearch
final release version is 2.3.3 so i think master version 2.3.3 cause i use master branch only for release 

thanks
