### ISSUE TITLE
Table with Elasticsearch static and dynamic settings

### ISSUE THREAD

**Issue by hartfordfive** [elastic/elasticsearch#18796]
It would be great to have a very simple page to sum up all cluster settings (static and dynamic). I know you can currently see all available cluster settings here although you have to go through each sub page and read through to see if the setting is static or dynamic. For example, adding a table similar to this on the modules page would be very convenient:

| Setting | Module | Type | Documentation URL |
| --- | --- | --- | --- |
| indices.fielddata.cache.size | Indices | static | https://www.elastic.co/guide/en/elasticsearch/guide/current/_limiting_memory_usage.html |

**Comment by s1monw** [comment]
I agree we should do something like this. I think the except of the doc link we have all of it avaliable.. maybe we can make it a CAT API?

**Comment by hartfordfive** [comment]
@s1monw, having it part of the CAT API could also be a great idea, probably even better than my last suggestion. 👍

**Comment by s1monw** [comment]
I removed the discuss label and added adopt me. I think we should not make the doc link a requirement for the first iteration but get a CAT API out there, users can still put the setting into the serach interface to find it.

**Comment by synhershko** [comment]
+1

**Comment by jrodewig** [comment]
[docs issue triage]

Closing this as a stale issue.

It seems like a CAT API for cluster settings is preferred and not primarily a documentation initiative (though if created, it should be documented too).

The ES tech writing team has discussed creating a settings page and decided not to move forward. Many settings make more sense when presented in the context of particular features (such as [ILM settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/ilm-settings.html). A single page documenting every setting would be of limited use.

Our overall setting documentation could be improved, but I think that's a separate issue.
