### ISSUE TITLE
Clarify that using time zones for date rounding (e.g. histograms) can lead to buckets that are not equally sized 

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#18805]
I think we should clarify in our documentation that when using arbitrary time intervals together with time zones (e.g. in `date_histogram`), we cannot guarantee that the resulting buckets have exactly the specified interval width when DST changes (or other time zone offset changes) happen. 

As a simple example, when you specify an `interval` like e.g. 12h in a `date_histogram` together with a time zone (e.g. "CET") and then use extended bounds, we get nice buckets that align with 00:00 and 12:00 in local time in that time zone:

```
GET test/doc/_search
{
  "query": { "match": {
    "foo": "some_text"
  }}, 
  "aggs" : {
        "my_hist" : {
            "date_histogram" : {
                "field" : "event_date",
                "interval" : "12h",
                "time_zone": "CET",
                "extended_bounds" : {
                    "min" : "2016-03-26",
                    "max" : "2016-03-29"
                }
            }
        }
    }
}
```

```
"buckets": [
        {
          "key_as_string": "2016-03-26T00:00:00.000+01:00",
          "key": 1458946800000,
          "doc_count": 0
        },
        {
          "key_as_string": "2016-03-26T12:00:00.000+01:00",
          "key": 1458990000000,
          "doc_count": 0
        },
        {
          "key_as_string": "2016-03-27T00:00:00.000+01:00",
          "key": 1459033200000,
          "doc_count": 0
        },
        {
          "key_as_string": "2016-03-27T12:00:00.000+02:00",
          "key": 1459072800000,   <--- note: 1459072800000 - 1459033200000 = 39600000ms, thats 11h
          "doc_count": 0
        },
        {
          "key_as_string": "2016-03-28T00:00:00.000+02:00",
          "key": 1459116000000,
          "doc_count": 0
        },
        {
          "key_as_string": "2016-03-28T12:00:00.000+02:00",
          "key": 1459159200000,
          "doc_count": 0
        }
```

However, this example covers the day DST starts in CET (27 Mar 2016, +1h at 02:00) so the "2016-03-27T00:00:00.000+01:00" bucket is only 11h "wide". On DST start we would have the reverse situation where the bucket covers 13h. 

This is something that cannot be avoided when at the same time we want e.g. 6h/12h intervals to align nicely with local time, but I think it is not really clear for every user and they might (incorrectly) rely on the assumption that buckets are equal-sized in their further processing. Maybe this should just be stated in the docs clearly, at least for these relatively simple cases. Otherwise we can only really guarantee fixed-size buckets for fixed UTC offset time zones (like +01:00, -06:00).

**Comment by jpountz** [comment]
Agreed this is something we should address with documentation.

**Comment by cbuescher** [comment]
We discussed this on FF and think we should write some documentation about it.
