### ISSUE TITLE
Unable to connect to ElasticSearch on a remote server

### ISSUE THREAD

**Issue by arunkumar987** [elastic/elasticsearch#18801]
**Elasticsearch version**: 5.0

**JVM version**: 1.8

**OS version**: Windows Server 2012 R2

**Description of the problem including expected versus actual behavior**: 
After googling I made some changes to the logging.yml file like changing the network.host: 0, setting http.port, network.bind_host: 0 and also set the max and min heap size to be the same. But still ES works locally and refuses any remote connections.

**Comment by jasontedor** [comment]
@arunkumar987 Sorry for the trouble, if you head over to the [Elastic Discourse forums](https://discuss.elastic.co) it's likely that someone from the community can help you. Elastic reserves GitHub for verified bug reports and feature requests, and this looks like a configuration issue. Note that it would be really helpful if you provided some logging and more detail about exactly what you did and are trying to do.
