### ISSUE TITLE
[Shield] Exists Filter Does Not Work when Field Level Security is On

### ISSUE THREAD

**Issue by yana2301** [elastic/elasticsearch#18814]
Sorry if it's not the right place for shield-related tickets, but I haven't found any other place to submit issues on shield. 
Exists query does not work if I turn on field level security in Shield. 
Steps to reproduce:

Shield role setting: 
 
     test_index_user:
           cluster: monitor
          indices:
           'test_index':
              privileges: read,manage
              fields:
               - Date
               - Sales
               - product_group
               - year
               - product_category
               - sku

Example data:
     {
          "Sales": 148850,
          "year": 2001,
          "product_group": "Books",
          "sku": "KA111115",
          "Date": "2013-09-17T05:07:00.000Z",
          "product_category": "Arts"
        }, 
   {
          "Sales": 148850,
          "year": 2015,
          "product_group": "Books",
          "sku": "KA111115",
          "Date": "2013-09-17T05:07:00.000Z",
          "product_category": "Arts"
        }
If I sent  this query -- I see groups by year: 
{
   "aggs" : {
        "years" : {
            "terms" : { "field" : "year" }
        }
    }
}
If I add exists filter -- I get empty result

{
  "query": {
    "bool": {
      "must": [
        {
          "exists": {
            "field": "year" 
          }
        }
      ]
    }
  },
   "aggs" : {
        "years" : {
            "terms" : { "field" : "year" }
        }
    }
}
Could you please advice if it's expected behavior or shield issue that should be fixed.

**Comment by martijnvg** [comment]
@yana2301 Thanks for reporting! This is indeed a bug, which will be fixed in the next release. 

As a workaround for now, if you add `_field_names` to the `fields` section in the `elasticseach.yml` then I expect the `exists` filter/query to work again.

**Comment by clintongormley** [comment]
Nothing further to do here. Closing
