### ISSUE TITLE
Safeguard: limit number of terms in TermsQuery

### ISSUE THREAD

**Issue by jonaf** [elastic/elasticsearch#18829]
**Describe the feature**: I have seen a lot of cases where an application will generate some long list of terms for a `TermsQuery` and pass it off to Elasticsearch. In general, `TermsQuery` performance degrades quickly as more terms are added, and once you get into hundreds (or thousands), you can pretty much forget it. (Unless there's a way to do a terms query with hundreds or thousands of terms and I just don't know the secret.) I think we should consider short-circuiting on the number of terms if it goes beyond some threshold unless some overriding argument is given. Additionally, it might be a good idea for Elastic.co documentation to warn users that many terms can have a substantial impact on latency, and of course point out the default limit/safeguard (supposing it is decided that the number of terms should be limited).

Relates #11511

**Comment by jpountz** [comment]
+1 on adding a soft limit to discourage having too many terms in terms queries. However I don't think we should let the query execute with a partial list of terms in that case, we should fail the entire request.

**Comment by jonaf** [comment]
Sorry, by "short-circuiting," I meant abandoning the entire query, not truncating the list of terms.

**Comment by jpountz** [comment]
Cool, thanks for clarifying. +1 then!

**Comment by jpountz** [comment]
@jonaf In case you would like to work on a PR that fixes this issue, feel free to ping me for review.

**Comment by hluu** [comment]
+1

**Comment by jonaf** [comment]
@jpountz Happy to. I just had to get authorization to sign the CLA. Should this contribution be destined for master only, or 2.x as well? (Based on reading contribution guidelines, it looks like I need to open a separate PR for each branch and reference this issue from the PR's?)

**Comment by jpountz** [comment]
@jonaf Awesome! In general we build PRs for master first and only consider backporting when the change is ready for master.

**Comment by antonvs2** [comment]
>  In general, TermsQuery performance degrades quickly as more terms are added, and once you get into hundreds (or thousands), you can pretty much forget it.

Would this be applied in case of a Terms Query using the [lookup](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html#query-dsl-terms-lookup) mechanism as well?

In the above link it says:
> When it’s needed to specify a terms filter with a lot of terms it can be beneficial to fetch those term values from a document in an index.

But not sure how much is that `a lot`.

**Comment by jpountz** [comment]
> Would this be applied in case of a Terms Query using the lookup mechanism as well?

Yes, the `terms` lookup mechanism even adds an additional phase since the terms need to be fetched from the index while in the regular case they are provided in the query.

> But not sure how much is that a lot.

The terms lookup mechanism allows you to make your requests smaller at the expense of more processing on the server side. So the trade-off will depend on how many terms you have vs. how slow the connection is between your client and the Elasticsearch cluster that you are querying. I suspect the terms lookup rarely buys much.

**Comment by fzyzcjy** [comment]
Hi! I wonder what will be the suggest number of terms? For instance, 100/200/500/1000? (I see the MAX limit is set to 2000, but I think that is a high upper bound and we should not reach that...?)
