### ISSUE TITLE
Delete multiple ES indexes in one go

### ISSUE THREAD

**Issue by temaniarpit27** [elastic/elasticsearch#18826]
**Describe the feature**:
There is no inbuilt command for deleting multiple ES indexes in one go. Its a good to have feature

**Comment by dadoonet** [comment]
Yes you can. `DELETE index1,index2`. Read https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html

Please use discuss.elastic.co where we can better discuss that kind of things.
