### ISSUE TITLE
Painless: Should } be a delimiter?

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#18821]
I'm porting reindex's tests from groovy to painless. Yay. One thing I found is that a statement like
```
if (ctx._source.bar != 1) {ctx._source.foo = 1}
```
doesn't compile. It needs to be
```
if (ctx._source.bar != 1) {ctx._source.foo = 1;}
```
with the semicolon between the `1` and the `}`.

Is it worth making that work?

**Comment by rmuir** [comment]
I think so if it creates no ambiguity in the grammar. The missing semicolons create too much ambiguity and, at the moment, the only place you can have it missing is EOF. But maybe } works.

**Comment by nik9000** [comment]
Cool! I might give that a shot this evening if I get a chance. I've wanted an excuse to play with painless's guts.
