### ISSUE TITLE
Search preference _prefer_node enhancement 

### ISSUE THREAD

**Issue by dev-head** [elastic/elasticsearch#18822]
**Describe the feature**:

* Allow the search preference for ```_prefer_node``` to use the node name or the node id. 
* Allow the search preference for ```_prefer_node``` to accept a csv of values (round robin the preferred nodes)

Currently we can only prefer a single node and that single node must be the node's id. The node id is dynamically generated which does not allow this feature to be used with out much effort to maintain it. 

Use case: 
I have a single cluster across multiple data centers and need to force client nodes in data center A to only send search queries to data nodes in data center A. With this proposed enhancement I will be able to automate the preference routing.

**Comment by jasontedor** [comment]
> Currently we can only prefer a single node and that single node must be the node's id. The node id is dynamically generated which does not allow this feature to be used with out much effort to maintain it.

Nodes will be getting a persistent node IDs in Elasticsearch 5.0.0 (it will be generated the first time a node starts up, persisted to disk, and used forever after that). I don't think that this is the solution to your problem, see below.

> I have a single cluster across multiple data centers

We generally recommend against this.

> force client nodes in data center A to only send search queries to data nodes in data center A

Use the `_only_nodes` preference? You can specify a common attribute on the nodes and use that attribute for the client? This seems to me to be the best option?

**Comment by dev-head** [comment]
```_only_nodes``` would cause an error if the nodes are offline for whatever reason, i do want it to be able to fall back, which is why ```_prefer_node``` is more helpful in our case. We need to have 99.9999% up time and sub second global latency all while handling an ever growing data set and user base. 

A persistent node id would make life easier but it still means ES is in charge where I want to be in charge of it, mainly for automation needs. 

My use case may not be the normal one, but it does seem to be pretty commonly run into by the community. I need to provide the same data across the globe and ES can do that, right now there just isn't much to support this type of use case for one reason or another. 

We could have multiple clusters running, but it is a bit over kill to have to mange feeding the same data into each cluster and then manage all the collisions it can cause because each cluster has it's own view of the data.

**Comment by nik9000** [comment]
> We need to have 99.9999% up time

> I have a single cluster across multiple data centers

I don't think these statement work well together.

If you need sub-second global latency you'll need a couple of distinct clusters and a system that forks writes to all of them. This is far superior to a single cluster because you can shoot one of the clusters and have your application fail over to the other DC temporarily. Fully separate clusters are what a truly paranoid administrator should want. And you can't have that kind of uptime without massive paranoia. I'm [told](http://uptime.is/99.9999) six nines is 31.6 seconds of downtime a year. So you'll need stuff like automatic failover across DCs too.

I haven't formed an opinion on `_prefer_node`, though.

**Comment by jasontedor** [comment]
> ```_only_nodes``` would cause an error if the nodes are offline for any reason, i do want it to be able to fall back, which is why ```_prefer_node``` is more helpful in our case.

Note that you did say

> force client nodes in data center A to *only* send search queries to data nodes in data center A

but I appreciate the clarification (emphasis added).

> We need to have 99.9999% up time and sub second global latency all while handling an ever growing data set and user base.

This is not going to happen with a single *cluster*, sorry.

**Comment by dev-head** [comment]
There is a need to be able to use that preference to give routing control to the search queries. This is the reason that the preference exists today. Is this feature enhancement, to prefer more than one node and to identify that preference by a node name, a reasonable request, on it's own outside of my use case?

----
> This is not going to happen with a single cluster, sorry.
> I don't think these statement work well together.

challenge accepted. 👍

**Comment by bleskes** [comment]
> I have a single cluster across multiple data centers and need to force client nodes in data center A to only send search queries to data nodes in data center A.

A short note that if you take away the need to "force" and make it "prefer", you get it all out of the [allocation awareness feature](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/allocation-awareness.html) by default:

> When executing search or GET requests, with shard awareness enabled, Elasticsearch will prefer using local shards — shards in the same awareness group — to execute the request. This is usually faster than crossing racks or awareness zones.

**Comment by clintongormley** [comment]
I agree that running a cluster across two data centres (not availability zones) it very likely to end in tears.  Also, that using allocation awareness provides what @dev-head is after.

That said, I think adding `_prefer_nodes` as an adjunct  to `_only_nodes` makes sense.  I'd even consider removing `_only_node` and `_prefer_node`.

**Comment by jasontedor** [comment]
> That said, I think adding `_prefer_nodes` as an adjunct  to `_only_nodes` makes sense.  I'd even consider removing `_only_node` and `_prefer_node`.

I agree, and opened two little pieces: #18872 and #18875.
