### ISSUE TITLE
Previous Versions of a doc

### ISSUE THREAD

**Issue by temaniarpit27** [elastic/elasticsearch#18825]
**Describe the feature**: There is no inbuilt feature of ElasticSearch which gives previous versions of a particular doc. Sometimes it becomes difficult to see the new changes. So we can have a version control system (VCS) for each doc so that we can look at different versions of a doc

**Comment by dadoonet** [comment]
You need to do that by yourself.
For example, add after the doc id its version number, like `doc1-v1`. Then when you add a new version, send a new doc with `_id` `doc1-v2`.
