### ISSUE TITLE
Remove mapper attachments plugin

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#18837]
We now have in 5.0.0 `ingest-attachment` plugin.
We should remove `mapper-attachments` plugin in the future.

I propose doing that either in 6.0 or from 5.1. Labelling for now as `6.0.0`.

**Comment by jpountz** [comment]
+1

**Comment by clintongormley** [comment]
Let's add deprecation logging in 5.0

**Comment by dadoonet** [comment]
@clintongormley Deprecation logging is already done with #16948. So we are ready to remove the plugin for 6.0.
