### ISSUE TITLE
JBoss Module doc needs updating

### ISSUE THREAD

**Issue by johnament** [elastic/elasticsearch#18848]
I can probably provide some edits, once I get it working.

https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/_deploying_in_jboss_eap6_module.html

Needs to be updated for 2.3.3.  The page shows 2.0 even on the 2.3.3 release.  Also considering the new structure, probably needs to reflect:
- Jackson upgrade (Wildfly ships w/ 2.5.4 which is not compatible)
- New dependencies on modules (since ES is no longer shaded)
- Updated lucene JARs.

**Comment by clintongormley** [comment]
@johnament a PR would be greatly appreciated!

**Comment by clintongormley** [comment]
btw, you can define variables in the index.asciidoc file, like:

    :major-version: 2

To use that variable inside a code block, you need something like this:

    ["source","sh",subs="attributes,callouts"]
    --------------------------------------------------
    echo "deb https://packages.elastic.co/elasticsearch/{major-version}/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-{major-version}.list
    --------------------------------------------------

**Comment by javanna** [comment]
We have recently removed this page from our docs as it was outdated and we had no plans to maintain it. See #26902 .
