### ISSUE TITLE
ESIntegTestCase not documented in compatibility guides

### ISSUE THREAD

**Issue by johnament** [elastic/elasticsearch#18846]
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_java_api_changes.html

When reviewing this page, the rename of `ElasticsearchIntegrationTest` to `ESIntegTestCase` is not documented.

**Comment by jasontedor** [comment]
We usually do not document minor Java API changes as your IDE will assist you here. This is especially true for the test framework.
