### ISSUE TITLE
[indices:data/read/field_stats[s]]]; nested: IllegalArgumentException[field [@timestamp] doesn't exist]

### ISSUE THREAD

**Issue by DreadPirateRob** [elastic/elasticsearch#18841]
First time user of ELK. 

In my /var/log/elasticsearch/logstashTesting.log file, all I have are entries that begin with this. 
[indices:data/read/field_stats[s]]]; nested: IllegalArgumentException[field [@timestamp] doesn't exist]

**Elasticsearch (ELK) version**:
[root@logstash ~]# yum list installed | grep -E '(elasticsearch|logstash|kibana)'
elasticsearch.noarch   2.3.3-1          @elasticsearch-2.x                      
kibana.x86_64          4.5.1-1          @kibana-4.5                             
logstash.noarch        1:2.3.2-1        @logstash-2.3   

**JVM version**:
[root@logstash ~]# java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
[root@logstash ~]# 

**OS version**:
[root@logstash ~]# cat /etc/redhat-release 
CentOS release 6.7 (Final)
[root@logstash ~]# 

**Provide logs (if relevant)**:
`RemoteTransportException[[logstash][<ip_redacted>:9300][indices:data/read/field_stats[s]]]; nested: IllegalArgumentException[field [@timestamp] doesn't exist];
Caused by: java.lang.IllegalArgumentException: field [@timestamp] doesn't exist
	at org.elasticsearch.action.fieldstats.TransportFieldStatsTransportAction.shardOperation(TransportFieldStatsTransportAction.java:166)
	at org.elasticsearch.action.fieldstats.TransportFieldStatsTransportAction.shardOperation(TransportFieldStatsTransportAction.java:54)
	at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:282)
	at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:278)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-06-13 10:51:40,146][DEBUG][action.fieldstats        ] [logstash] [.kibana][0], node[o3rmPA87QB2R7bDSvUD9Fw], [P], v[4], s[STARTED], a[id=9YqIdu6LQguolACS17Bo1g]: failed to execute [org.elasticsearch.action.fieldstats.FieldStatsRequest@4b00875d]
RemoteTransportException[[logstash][<ip_redacted>:9300][indices:data/read/field_stats[s]]]; nested: IllegalArgumentException[field [@timestamp] doesn't exist];
Caused by: java.lang.IllegalArgumentException: field [@timestamp] doesn't exist
	at org.elasticsearch.action.fieldstats.TransportFieldStatsTransportAction.shardOperation(TransportFieldStatsTransportAction.java:166)
	at org.elasticsearch.action.fieldstats.TransportFieldStatsTransportAction.shardOperation(TransportFieldStatsTransportAction.java:54)
	at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:282)
	at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:278)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-06-13 10:52:17,348][DEBUG][action.fieldstats        ] [logstash] [.kibana][0], node[o3rmPA87QB2R7bDSvUD9Fw], [P], v[4], s[STARTED], a[id=9YqIdu6LQguolACS17Bo1g]: failed to execute [org.elasticsearch.action.fieldstats.FieldStatsRequest@616f19c]
RemoteTransportException[[logstash][<ip_redacted>:9300][indices:data/read/field_stats[s]]]; nested: IllegalArgumentException[field [@timestamp] doesn't exist];
Caused by: java.lang.IllegalArgumentException: field [@timestamp] doesn't exist
	at org.elasticsearch.action.fieldstats.TransportFieldStatsTransportAction.shardOperation(TransportFieldStatsTransportAction.java:166)
	at org.elasticsearch.action.fieldstats.TransportFieldStatsTransportAction.shardOperation(TransportFieldStatsTransportAction.java:54)
	at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:282)
	at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:278)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**logstash config file** 
`input {
  beats {
    port => 5044
  }
}

filter {
  date {
    locale => "en"
    match => ["mytimestamp", "YYYY-MM-dd HH:mm:ss"]
    target => "@timestamp"
  }
  grok {
    match => [ "message", "%{GREEDYDATA:message}"]
  }
}

output {
  stdout {
    codec => rubydebug
  }
  elasticsearch {
    hosts => "<ip_redacted>:9200"
    manage_template => false
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    document_type => "%{[@metadata][type]}"
  }
  if "OMG" in [message] {
   email {
    from => "logstash@oracle.com"
    subject => "logstash alert"
    to => "robert.m.morris@oracle.com"
    via => "sendmail"
    body => "Here is the event line that occured: %{message}"
   }
 }
}
`

**elasticsearch config file** 
`[root@logstash ~]# cat /etc/elasticsearch/elasticsearch.yml 
/# ======================== Elasticsearch Configuration =========================

/#

/# NOTE: Elasticsearch comes with reasonable defaults for most settings.

/#       Before you set out to tweak and tune the configuration, make sure you

/#       understand what are you trying to accomplish and the consequences.

/#

/# The primary way of configuring a node is via this file. This template lists

/# the most important settings you may want to configure for a production cluster.

/#

/# Please see the documentation for further information on configuration options:

/# <http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html>

/#

/# ---------------------------------- Cluster -----------------------------------

/#

/# Use a descriptive name for your cluster:

/#

cluster.name: logstashTesting

/#

/# ------------------------------------ Node ------------------------------------

/#

/# Use a descriptive name for the node:

/#

node.name: ${HOSTNAME}

/#

/# Add custom attributes to the node:

/#

/# node.rack: r1

/#

/# ----------------------------------- Paths ------------------------------------

/#

/# Path to directory where to store the data (separate multiple locations by comma):

/#

path.data: /var/data/elasticsearch

/#

/# Path to log files:

/#

path.logs: /var/log/elasticsearch

/#

/# ----------------------------------- Memory -----------------------------------

/#

/# Lock the memory on startup:

/#

/# bootstrap.mlockall: true

/#

/# Make sure that the `ES_HEAP_SIZE` environment variable is set to about half the memory

/# available on the system and that the owner of the process is allowed to use this limit.

/#

/# Elasticsearch performs poorly when the system is swapping the memory.

/#

/# ---------------------------------- Network -----------------------------------

/#

/# Set the bind address to a specific IP (IPv4 or IPv6):

/#

network.host: <ip_redacted>

/#

/# Set a custom port for HTTP:

/#

/# http.port: 9200

/#

/# For more information, see the documentation at:

/# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>

/#

/# --------------------------------- Discovery ----------------------------------

/#

/# Pass an initial list of hosts to perform discovery when new node is started:

/# The default list of hosts is ["127.0.0.1", "[::1]"]

/#

/# discovery.zen.ping.unicast.hosts: ["host1", "host2"]

/#

/# Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):

/#

/# discovery.zen.minimum_master_nodes: 3

/#

/# For more information, see the documentation at:

/# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery.html>

/#

/# ---------------------------------- Gateway -----------------------------------

/#

/# Block initial recovery after a full cluster restart until N nodes are started:

/#

/# gateway.recover_after_nodes: 3

/#

/# For more information, see the documentation at:

/# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html>

/#

/# ---------------------------------- Various -----------------------------------

/#

/# Disable starting multiple nodes on a single system:

/#

/# node.max_local_storage_nodes: 1

/#

/# Require explicit names when deleting indices:

/#

/# action.destructive_requires_name: true
`

**kibana log file**
`[root@logstash ~]# cat /opt/kibana/config/kibana.yml 
/# Kibana is served by a back end server. This controls which port to use.
/# server.port: 5601

/# The host to bind the server to.
/# server.host: "0.0.0.0"

/# If you are running kibana behind a proxy, and want to mount it at a path,
/# specify that path here. The basePath can't end in a slash.
/# server.basePath: ""

/# The maximum payload size in bytes on incoming server requests.
/# server.maxPayloadBytes: 1048576

/# The Elasticsearch instance to use for all your queries.
elasticsearch.url: "http://<ip_redacted>:9200"

/# preserve_elasticsearch_host true will send the hostname specified in `elasticsearch`. If you set it to false,
/# then the host you use to connect to *this* Kibana instance will be sent.
/# elasticsearch.preserveHost: true

/# Kibana uses an index in Elasticsearch to store saved searches, visualizations
/# and dashboards. It will create a new index if it doesn't already exist.
/# kibana.index: ".kibana"

/# The default application to load.
/# kibana.defaultAppId: "discover"

/# If your Elasticsearch is protected with basic auth, these are the user credentials
/# used by the Kibana server to perform maintenance on the kibana_index at startup. Your Kibana
/# users will still need to authenticate with Elasticsearch (which is proxied through
/# the Kibana server)
/# elasticsearch.username: "user"
/# elasticsearch.password: "pass"

/# SSL for outgoing requests from the Kibana Server to the browser (PEM formatted)
/# server.ssl.cert: /path/to/your/server.crt
/# server.ssl.key: /path/to/your/server.key

/# Optional setting to validate that your Elasticsearch backend uses the same key files (PEM formatted)
/# elasticsearch.ssl.cert: /path/to/your/client.crt
/# elasticsearch.ssl.key: /path/to/your/client.key

/# If you need to provide a CA certificate for your Elasticsearch instance, put
/# the path of the pem file here.
/# elasticsearch.ssl.ca: /path/to/your/CA.pem

/# Set to false to have a complete disregard for the validity of the SSL
/# certificate.
/# elasticsearch.ssl.verify: true

/# Time in milliseconds to wait for elasticsearch to respond to pings, defaults to
/# request_timeout setting
/# elasticsearch.pingTimeout: 1500

/# Time in milliseconds to wait for responses from the back end or elasticsearch.
/# This must be > 0
/# elasticsearch.requestTimeout: 30000

/# Time in milliseconds for Elasticsearch to wait for responses from shards.
/# Set to 0 to disable.
/# elasticsearch.shardTimeout: 0

/# Time in milliseconds to wait for Elasticsearch at Kibana startup before retrying
/# elasticsearch.startupTimeout: 5000

/# Set the path to where you would like the process id file to be created.
/# pid.file: /var/run/kibana.pid

/# If you would like to send the log output to a file you can set the path below.
/# logging.dest: stdout

/# Set this to true to suppress all logging output.
/# logging.silent: false

/# Set this to true to suppress all logging output except for error messages.
/# logging.quiet: false

/# Set this to true to log all events, including system usage information and all requests.
/# logging.verbose: false
[root@logstash ~]# 
`

**Question**:
So what's going on here? (also, logstash isn't sending the email when the match is found)

**Comment by DreadPirateRob** [comment]
I had to put a slash "/" in front of all of the pound signs "#", otherwise the formatting was messed up here on github

**Comment by danielmitterdorfer** [comment]
Hi @DreadPirateRob,

this is no issue with Elasticsearch hence I'll close the ticket. We have a [dedicated discussion forum](https://discuss.elastic.co) for such questions. Can you please post your question there (the [Logstash forum](https://discuss.elastic.co/c/logstash) seems to fit best)? 

As a hint: Elasticsearch does not know about the field `@timestamp` and hence it complains. You need to define a mapping for your index, which is (very loosely speaking) similar to a DDL statement in SQL. You also set `manage_template => false` in your Logstash configuration. [According to the docs](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-manage_template) this means that Logstash will not create a mapping automatically and you have to provide your own.

Another hint: You can use [Markdown](https://help.github.com/articles/github-flavored-markdown/) for formatting in Github comments.

**Comment by DreadPirateRob** [comment]
Since the error occurs in the elasticsearch logs, I figured this would be the place to put this issue. Also, I did use markdown. 

I will change the `manage_template => false` configuration in logstash. I'll also post this in the logstash forum as suggested.

**Comment by danielmitterdorfer** [comment]
> Since the error occurs in the elasticsearch logs, I figured this would be the place to put this issue

Sure, no worries. You're right; it could have also been an issue with Elasticsearch and it is sometimes hard to tell what's the root cause.

> Also, I did use markdown. 

I just referred to the Markdown reference as you mentioned that you had trouble with the hash comments in the yml file. You can use triple backticks to start / end a multi-line block comment:

```
# this is a multiline ...
# preformatted block
# that will not be broken
# I used ``` to start the block and will now use ``` to end it again.
```

**Comment by DreadPirateRob** [comment]
for future reference, the question is posted here https://discuss.elastic.co/t/indices-data-read-field-stats-s-nested-illegalargumentexception-field-timestamp-doesnt-exist/52738

Also (for my fellow newbies), the forums only have a 5K character limit, so to post my question with the relevant logs & config files I had to make 5 posts in the thread just to get all the information in.

**Comment by DreadPirateRob** [comment]
Ahh, see I used a single backtick instead of the triple. fail on my part.
