### ISSUE TITLE
How to set "index": "not_analyzed" While push data from Mysql using mysql-replicator

### ISSUE THREAD

**Issue by Git-Rajkumar** [elastic/elasticsearch#18853]
I post my question in elastic search forums https://discuss.elastic.co/t/how-to-set-index-not-analyzed-while-push-data-from-mysql-using-mysql-replicator/52718, This is My Problem, Suggest me  How to do this?.

**Comment by dadoonet** [comment]
discuss is the best place for questions. Let's keep the question there .
