### ISSUE TITLE
Feature Request : Get Nested sub elements in a document in a paginated fashion

### ISSUE THREAD

**Issue by pmishra002** [elastic/elasticsearch#18850]
Is it possible to get the nested sub elements in a document in a paginated fashion. Example we have a document as below and we would know the document id

{
"_index": "index1",
"_type": "type1",
"_id": "81cabf3c-51f5-442a-b78d-4324c4344f51",
"_version": 1,
"found": true,
"_source": {
"chiild1" : "child1 value"
"names": [
{
"name": "John"
},
{
"name": "Walter"
},
{
"name": "Justin"
},
{
"name": "Cramer"
}
]
}
}

Can we run a query like below (It does not work but are there other options ?)

GET index1/type1/81cabf3c-51f5-442a-b78d-4324c4344f51?sourceinclude=names.name&start=0&size=2

1.

{
"_index": "index1",
"_type": "type1",
"_id": "81cabf3c-51f5-442a-b78d-4324c4344f51",
"_version": 1,
"found": true,
"_source": {
"names": [
{
"name": "John"
},
{
"name": "Walter"
}
]
}
}

2.

GET index1/type1/81cabf3c-51f5-442a-b78d-4324c4344f51?sourceinclude=names.name&start=2&size=2

{
"_index": "index1",
"_type": "type1",
"_id": "81cabf3c-51f5-442a-b78d-4324c4344f51",
"_version": 1,
"found": true,
"_source": {
"names": [
{
"name": "Justin"
},
{
"name": "Cramer"
}
]
}
}

**Comment by clintongormley** [comment]
Hi @pmishra002 

You can do this with inner hits:

    PUT t 
    {
      "mappings": {
        "t": {
          "properties": {
            "foo": {
              "type": "nested"
            }
          }
        }
      }
    }
    
    PUT t/t/1
    {
      "foo": [
        {
          "name": "one",
          "order": 1
        },
        {
          "name": "two",
          "order": 2
        },
        {
          "name": "three",
          "order": 3
        },
        {
          "name": "four",
          "order": 4
        },
        {
          "name": "five",
          "order": 5
        },
        {
          "name": "six",
          "order": 6
        },
        {
          "name": "seven",
          "order": 7
        },
        {
          "name": "eight",
          "order": 8
        },
        {
          "name": "nine",
          "order": 9
        }
      ]
    }
    
    GET t/_search?_source=false
    {
      "query": {
        "nested": {
          "path": "foo",
          "query": {
            "match_all": {}
          },
          "inner_hits": {
            "sort": ["foo.order"],
            "from": 3
          }
        }
      }
    }
