### ISSUE TITLE
Highlight "*" doesn't work with match _all field.

### ISSUE THREAD

**Issue by renanleandrof** [elastic/elasticsearch#18869]
**Elasticsearch version**: 2.3.3
**JVM version**: Java HotSpot(TM) 64-Bit Server VM (25.20-b23 mixed mode windows-amd64 compressed oops)
**OS version**: Windows 7

I'm sending a request like this:

```json
{
    "from": 0, 
    "query": {
        "match": {
            "_all": "presidencia"
        }
    }
    ,
    "aggs": {
        //... some aggregations 
    }
    ,
    "highlight": {
        require_field_match : false
        ,"fields": {
            "*": {}
        }
    }
}
```

But my response doesn't come with highlight field. Response:

```json
{
    "took": 68,
    "timed_out": false,
    "_shards": {"total": 15, "successful": 15, "failed": 0},
    "hits": {
        "total": 692785,
        "max_score": 0.48536316,
        "hits": [
            //Some hits WITHOUT the HIGHLIGHT results...
        ]
    },
    "aggregations": {
        //some aggs ...
    }
}
```

**Comment by nik9000** [comment]
See the note about _all in https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html . This is a known limitation of _all and highlighting. The usual way to work around this is to set `require_field_match` to false and then highlight against `*`. That has its problems as well, but it does work around it.

**Comment by renanleandrof** [comment]
Sorry, you replied before I could update the question, I am doing the
required_field_match false thing and still nothing comes.
Em 14 de jun de 2016 17:25, "Nik Everett" <notifications@github.com>
escreveu:

**Comment by nik9000** [comment]
> I am doing the required_field_match false thing and still nothing comes.

Ah! Sorry about that. Then it could be the analyzers producing tokens for your fields that don't match up with _all. That is one of the problems. I'd try to use the [analyze](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-analyze.html) API to track it down.

It *probably* isn't a bug so much as a known limitation so this conversation ought to move to discuss.elastic.co.
