### ISSUE TITLE
index.routing.allocation.total_primary_shards_per_node

### ISSUE THREAD

**Issue by samcday** [elastic/elasticsearch#18874]
Currently, an index can be configured with [`index.routing.allocation.total_shards_per_node`](https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-total-shards.html). We're making heavy use of this to ensure that the shards for our indices are evenly distributed across our available nodes.

However, this control does not extend far enough, we also need to be able to control the allocation of the primaries vs. replicas. So, here's a feature request for `index.routing.allocation.total_primary_shards_per_node`.

---

Today, if we have 2 nodes, and we create 2 indices with 2 primary shards, each with a replica, we can end up in a situation where one node has all 4 primary shards, and the other node has the replicas. This will happen even if we configure `{"index.routing.allocation.total_shards_per_node": 2}` on each index.

If `index.routing.allocation.total_primary_shards_per_node` were implemented, we would be able to create the indices with settings `{"index.routing.allocation.total_primary_shards_per_node": 1, "index.routing.allocation.total_shards_per_node": 2}`, which would result in each node having exactly 2 primary shards and 2 replicas.

**Comment by clintongormley** [comment]
Why does it matter?  Primary vs replica is just a role - the shards should be doing the same work.

**Comment by clintongormley** [comment]
Ah, now I've seen your comment in #18866 and I understand more.

**Comment by clintongormley** [comment]
Discussed this in Fix it Friday.  We agree that this setting is not the way to go. Instead we should be working on improving #18866
