### ISSUE TITLE
DateIndexNameProcessor date_rounding needs different values for months and minutes

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch#18877]
The [DateIndexName Processor documentation](https://www.elastic.co/guide/en/elasticsearch/reference/master/date-index-name-processor.html) lists `m` as the value for both minute and month `date_rounding` units. The value should be different for each unit. 

[Date Math uses `M` for month](https://www.elastic.co/guide/en/elasticsearch/reference/master/date-math-index-names.html) so I think this is just a documentation change. Happy to submit PR for this

**Comment by martijnvg** [comment]
thx @russcam that is indeed incorrect! I'll fix it.
