### ISSUE TITLE
Completion Suggester with  prefix and regx not working

### ISSUE THREAD

**Issue by ishara** [elastic/elasticsearch#18884]
I have try with Completion Suggest with prefix,regx and text. This is work only with text.  
but I have check with elasticsearch test cases and working fine with prefix and regex (Test class -CompletionSuggestSearchIT).
 
**Elasticsearch version**:2.3.3

**JVM version**:1.8

**OS version**:windows 10

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

DELETE /simple_suggest_index
PUT /simple_suggest_index
PUT /simple_suggest_index/simple_type/_mapping
{
"simple_type": {
"properties": {
  "name" : { "type" : "string" },
"suggest": {
"type": "completion",
"analyzer" : "simple",
"search_analyzer": "simple",
"preserve_separators":false,
"preserve_position_increments":false
}
}
}
}

POST /simple_suggest_index/simple_type/
{"name":"1","suggest":{"input":["Foo Fighters"]}}
POST /simple_suggest_index/simple_type/
{"name":"2","suggest":{"input":["Generator"]}}
POST /simple_suggest_index/simple_type/
{"name":"3","suggest":{"input":["Foo Fighters Generator"]}}
POST /simple_suggest_index/simple_type/
{"name":"4","suggest":{"input":["Mr ishara samantha nanayakkara"]}}

POST /simple_suggest_index/_suggest?pretty
{
  "simple_type": {
    "prefix": "m",
    "completion": {
      "field": "suggest",
      "fuzzy": {
        "fuzziness": 2
      }
    }
  }
}
POST /simple_suggest_index/_search?pretty
{
  "suggest" : {
    "simple_type" : {
      "prefix" : "m",
      "completion" : {
        "field" : "suggest",
        "size" : 10,
        "fuzzy" : {
          "fuzziness" : 2,
          "transpositions" : true,
          "min_length" : 3,
          "prefix_length" : 1,
          "unicode_aware" : false,
          "max_determinized_states" : 10000
        }
      }
    }
  }
}

**Describe the feature**:

{
   "_shards": {
      "total": 5,
      "successful": 0,
      "failed": 5,
      "failures": [
         {
            "shard": 0,
            "index": "simple_suggest_index",
            "status": "INTERNAL_SERVER_ERROR",
            "reason": {
               "type": "exception",
               "reason": "failed to execute suggest",
               "caused_by": {
                  "type": "illegal_argument_exception",
                  "reason": "[suggest] does not support [prefix]"
               }
            }
         }
      ]
   }
}

**Comment by clintongormley** [comment]
Hi @ishara 

The new completion suggester, which supports prefix and regex, is only available in 5.0
