### ISSUE TITLE
http output plugin fails on CONNECT request 

### ISSUE THREAD

**Issue by arkadyi** [elastic/elasticsearch#18897]
**Elasticsearch version**: 2.3.1

**JVM version**: 1.8.0_77

**OS version**: CentOs 7

**Description of the problem including expected versus actual behavior**:

I'm trying to use http output plugin to send data via proxy.
It works till original url is not HTTPS.
Once original url is HTTPS proxy authentication stops to work.
When I looked into tcp dump I found out that logstash does not send headers in HTTP request and hence proxy authentication failed.
It also generates an exception:

NameError: no method 'setHeader' for arguments (org.jruby.RubySymbol,org.jruby.RubySymbol) on Java::OrgApacheHttpClientMethods::HttpPost
  available overloads:
    (java.lang.String,java.lang.String)
    (java.lang.String,java.lang.String)
                   []= at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/java_extensions.rb:18
  request_from_options at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:490
                  each at org/jruby/RubyHash.java:1342
  request_from_options at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:490
               request at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:418
                  post at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:265
                  post at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client/proxies.rb:31
               receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-http-2.1.3/lib/logstash/outputs/http.rb:120
         multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-http-2.1.3/lib/logstash/outputs/http.rb:93
                  each at org/jruby/RubyArray.java:1613
         multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-http-2.1.3/lib/logstash/outputs/http.rb:93
  worker_multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/output_delegator.rb:130
         multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/output_delegator.rb:114
          output_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:301
                  each at org/jruby/RubyHash.java:1342
          output_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:301
           worker_loop at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:232
         start_workers at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:201

My configuration is:
output {
                http {
                        http_method => "post"
                        url => "https://my-domain.com/"
                        cacert => "/etc/ssl/certs/GeoTrust_SSL_CA_G2.cer"
                        codec => "json"
                        headers => {
                                "Proxy-Authorization" => "Basic c2XXXXXXXXXcnQ="
                                "Pragma" => "no-cache"
                        }
                       proxy => "http://10.10.0.254:3128"
                }
}

It works (and sends headers) if I try to send data to http://my-domain.com  instead of httpS://my-domain.com

**Comment by jasontedor** [comment]
There is a [repository](https://github.com/elastic/logstash) that is dedicated to Logstash, I think that you'll have better luck seeking an answer there.
