### ISSUE TITLE
build it with gradle error

### ISSUE THREAD

**Issue by xuzhou2020** [elastic/elasticsearch#18916]
os : windows 7
gradle: 2.14

----------please  add  pom.xml  , thanks
error:
--------------------
* Where:
Build file 'E:\elasticsearch-mapper-attachments-master\build.gradle' line: 20

* What went wrong:
Could not compile build file 'E:\elasticsearch-mapper-attachments-master\build.g
radle'.
> startup failed:
  build file 'E:\elasticsearch-mapper-attachments-master\build.gradle': 20: unab
le to resolve class org.elasticsearch.gradle.ElasticsearchProperties
 @ line 20, column 1.
     import org.elasticsearch.gradle.ElasticsearchProperties
     ^

  1 error

**Comment by dadoonet** [comment]
We have no idea about what you are doing.
We are building the project every day and we don't really hit issues like this.

You could ask for help on discuss.elastic.co but provide more info please.

Closing. Feel free to reopen if you think it's a bug.

**Comment by jasontedor** [comment]
This appears to be from elastic/elasticsearch-mapper-attachments, so if you're trying to build for 2.x, you should open an issue in that repository.

**Comment by dadoonet** [comment]
lol. He did: https://github.com/elastic/elasticsearch-mapper-attachments/issues/217 :)

But from 2.2 IIRC, mapper-attachments is now living here. (with maven)

**Comment by xuzhou2020** [comment]
Hi:
     just add pom.xml,  so I can build it with maven .
     thank you

**Comment by dadoonet** [comment]
No. We won't do that.
You have to use gradle to build the latest version.
If you are looking at the 2.x version, it uses Maven. Just switch to 2.x branch.

**Comment by javanna** [comment]
This seems the same problem as #18935 after all.

**Comment by xuzhou2020** [comment]
now test again:
----------------------
1. Windows 7
2. jdk1.8 64bit
3. gradle 2.13
------------------gradle build 
wait for a long time.... ok

file list  in dir
--E:\elasticsearch-master\plugins\mapper-attachments\build\distributions
mapper-attachments-5.0.0-alpha4-SNAPSHOT.jar
mapper-attachments-5.0.0-alpha4-SNAPSHOT.pom
mapper-attachments-5.0.0-alpha4-SNAPSHOT.zip
mapper-attachments-5.0.0-alpha4-SNAPSHOT-javadoc.jar
mapper-attachments-5.0.0-alpha4-SNAPSHOT-sources.jar


--- elasticsearch  version
{
  "name" : "Lodestone",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.2.1",
    "build_hash" : "d045fc29d1932bce18b2e65ab8b297fbf6cd41a1",
    "build_timestamp" : "2016-03-09T09:38:54Z",
    "build_snapshot" : false,
    "lucene_version" : "5.4.1"
  },
  "tagline" : "You Know, for Search"
}




=========now  install mapper-attachments=========
E:\elasticsearch-rtf-master\bin>plugin install file:///e:/mapper-attachments-5.0
.0-alpha4-SNAPSHOT.zip
-> Installing from file:/e:/mapper-attachments-5.0.0-alpha4-SNAPSHOT.zip...
Trying file:/e:/mapper-attachments-5.0.0-alpha4-SNAPSHOT.zip ...
Downloading ....................................................................
................................................................................
.............................................................DONE
Verifying file:/e:/mapper-attachments-5.0.0-alpha4-SNAPSHOT.zip checksums if ava
ilable ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .
md5 file to verify)
ERROR: Plugin [mapper-attachments] must be at least a jvm or site plugin



so, what's wrong with me ???

please help

**Comment by dadoonet** [comment]
You built a plugin for 5.0 but you are trying to install it on another version.

Not sure what is exactly your need but please ask on discuss.elastic.co.

**Comment by xuzhou2020** [comment]
Hi:

    maybe I didn't say it clear,  
    my elasticsearch verion is  2.2.1 
    so I choose "github"
    and when I build it with  gradle.   
    then    result :   mapper-attachments-5.0.0-alpha4-SNAPSHOT.zip

    so now  I am  puzzled...

----------------------------------------------------------------------
https://github.com/elastic/elasticsearch-mapper-attachments/

     bin/plugin install elasticsearch/elasticsearch-mapper-attachments/3.1.2
You need to install a version matching your Elasticsearch version:

Elasticsearch	Attachments Plugin	Docs
> 2.1	elasticsearch repository	github
es-2.1	Build from source	es-2.1
2.1.2	3.1.2	3.1.2
2.1.1	3.1.1	3.1.1
2.1.0	3.1.0	3.1.0
es-2.0	Build from source	es-2.0
2.0.2	3.0.4	3.0.4
2.0.1	3.0.3	3.0.3
2.0.0	3.0.2	3.0.2
2.0.0-beta2	3.0.1	3.0.1
2.0.0-beta1	3.0.0	3.0.0
es-1.7	2.7.1	2.7.1
es-1.6	2.6.0	2.6.0
es-1.5	2.5.0	2.5.0
es-1.4	2.4.3	2.4.3
es-1.3	2.3.2	2.3.2
es-1.2	2.2.1	2.2.1
es-1.1	2.0.0	2.0.0
es-1.0	2.0.0	2.0.0
es-0.90	1.9.0	1.9.0
To build a SNAPSHOT version, you need to build it with Maven:

gradle clean assemble
plugin --install mapper-attachments \
       --url file:target/releases/elasticsearch-mapper-attachments-X.X.X-SNAPSHOT.zip

**Comment by dadoonet** [comment]
I see. You did not notice the very first lines of the README, right?

So read the doc: https://www.elastic.co/guide/en/elasticsearch/plugins/2.2/mapper-attachments.html

You don't need to build the plugin...

**Comment by rjernst** [comment]
@dadoonet can we delete the master branch in that repo to remove some confusion? The gradle code there is horribly out of date (still points to a 3.0 snapshot of build-tools), and will never be used.

**Comment by dadoonet** [comment]
I asked the same myself for all plugins some months ago.
I think it makes sense. I'd like to remove all files but the README or remove the master branch and default to es-1.7 branch.

**Comment by rjernst** [comment]
> I'd like to remove all files but the README

That sounds the best to me.

**Comment by dadoonet** [comment]
@rjernst FYI I cleaned most of our repos ^^^ :)
