### ISSUE TITLE
Multi_match search query ignoring fields

### ISSUE THREAD

**Issue by cechovsky** [elastic/elasticsearch#18925]
I have simple tests to test elasticsaerch queries, but sometimes queries behave very strange - like multi_match sometimes ignoring fields I'd like to query.

Eg. I have following address data

| Margaretenstraße | 1            | Krailling | Deutschland |
| Margaretenstraße | 2A          | Krailling | Deutschland |
| Margaretenstraße | 3            | Krailling | Deutschland |
| Margaretenstraße | 4            | Krailling | Deutschland |

I created index - only simple without analysing.

I called _search query

```
{
  "explain": true, 
  "query": {
    "multi_match": {
      "type": "most_fields",
      "query": "margaretenstraße krailling 4",
      "tie_breaker": 1,
      "fields": [
        "house_number",
        "street",
        "city"
      ]
    }
  }
}
```

And it returns correct object "margaretenstraße krailling 4". But when I add some boosting to city - city^2 it looks like it ignores house number field and returns "margaretenstraße krailling 4". When I analyzed scoring in explain, there is **no score for matching house_number field at all**.

What can cause this problem? Is it common behavior? I tried it more times and sometimes when I create a new, the same index it works but sometimes not.

**Comment by cechovsky** [comment]
I analyzed scoring explanation and
- the same data
- the same query

and scoring explanation is different
![image](https://cloud.githubusercontent.com/assets/2878125/16123206/781ffb2a-33ea-11e6-9de0-3350f00aa7ba.png)

**Comment by clintongormley** [comment]
This is just a side effect of query rewriting.  You're probably using 5 shards with a small amount of data, so you have one document on each shard.  The term `4` only appears on one shard, and so will only appear in the explain output for that doc.  The other docs won't have it.

Try creating the index with just one shard (or adding lots more data), then it will work correctly:

    PUT t 
    {
      "settings": {
        "number_of_shards": 1
      }
    }
    
    
    POST t/t/_bulk
    {"index": {}}
    {"house_number": "1", "street": "Margaretenstraße", "city": "Krailling"}
    {"index": {}}
    {"house_number": "2A", "street": "Margaretenstraße", "city": "Krailling"}
    {"index": {}}
    {"house_number": "3", "street": "Margaretenstraße", "city": "Krailling"}
    {"index": {}}
    {"house_number": "4", "street": "Margaretenstraße", "city": "Krailling"}
    
    GET t/_search
    {
      "explain": true,
      "query": {
        "multi_match": {
          "type": "most_fields",
          "query": "margaretenstraße krailling 4",
          "tie_breaker": 1,
          "fields": [
            "house_number",
            "street",
            "city^2"
          ]
        }
      }
    }

**Comment by cechovsky** [comment]
Thank you. You're right. 

But I'm still wondering why it has such behavior that when I search for "margaretenstraße krailling 4" and I'm sure that I have this address in my index why it returns "margaretenstraße krailling 1".

**Comment by clintongormley** [comment]
See https://www.elastic.co/guide/en/elasticsearch/guide/2.x/relevance-is-broken.html
