### ISSUE TITLE
Painless: String += fails with map in java 8

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#18929]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/256/consoleText

This looks like a fairly minimal reproduction:
```
    public void testAppendStringIntoMap() {
        assertEquals("nullcat", exec("def a = new HashMap(); a.cat += 'cat'"));
    }
```

I'm not super familiar with this code. Does someone else want it or should I grab it?

**Comment by nik9000** [comment]
I'm going to disable the java-9 indy string concat stuff until this is fixed because it is causing build failures on java-9. Without the indy thing no ArrayIndexOutOfBoundsException....

**Comment by nik9000** [comment]
I pushed 13d16fbf41e0cf90c9051e015681cc2198bb0334 which disables java-9's indy string work and adds a unit test that fails with it enabled (basically just the snippet in the description).

**Comment by uschindler** [comment]
This is a bug in above code, it should not even trigger string concats!

**Comment by uschindler** [comment]
Whats the exception you get on this?

**Comment by uschindler** [comment]
Can somebody please update this outdated java version?

**Comment by uschindler** [comment]
We need to first rint the bytecode. AIIOBE always happens when you fck up the stack frames.

**Comment by nik9000** [comment]
> Can somebody please update this outdated java version?

I'll poke the right folks for that.

**Comment by nik9000** [comment]
> I'll poke the right folks for that.

Done. It still happens for 122 as well.

**Comment by nik9000** [comment]
> Done. It still happens for 122 as well.

Or to be clear - I've poked the right people. They haven't upgraded yet.

**Comment by uschindler** [comment]
This is just a guess: The indy string concats just found a bug in the EChain handling for compound assignments!

What likely happens: basically this code appends a string to null. so the result should be "nullcat". If the EChainCode misses to finally call MethodWriter#writeToStrings() finally then java 8 and java 9 behave differently:

- in java 8 this does not corrupt the stack, because the writeToStrings just calls toString() on the stringbuilder thats on stack. The number of args on stack does not change. The code succeeds and as the assignment goes to a "def", the def contains a StringBuilder afterwards. Which is not so bad, as it does not break the test.

- in Java 9, if you miss to call writeToString(), the invokedynamic is missing, so you have a lot of parts on stack that are never consumed. And ASM then fails to calculate stack frames. I just wonder why the state machine in MethodWriter#endMethod does not hit the bug!

Uwe

**Comment by uschindler** [comment]
I'd suggest to add the state machine also to Java 8 code (e.g., record how often writeNewStrings vs writeToString is called in a state machine). Then it should fail with Java 8, too.

**Comment by uschindler** [comment]
> Done. It still happens for 122 as well.

Yeah, that was just a side note. See above, the problem is a bug in compound statements. We are just lucky that Java 8 does not fail (because stack keeps valid).

**Comment by uschindler** [comment]
I think the problem here is that the code in EChain does not correctly set cat=true, because the first arg is not actually a string. I think we only have tests for "string" + blabla, but never anyothertype + "xxx"

**Comment by rmuir** [comment]
I see this if i print bytecode up to this point. Yes I am hooking this in so it will be easier!
```
 1> hit exception during compile, bytecode so far: 
  1> // class version 52.0 (52)
  1> // access flags 0x31
  1> public final class org/elasticsearch/painless/Executable$Script extends org/elasticsearch/painless/Executable  {
  1>   // compiled from: <debugging>
  1>   // access flags 0x1
  1>   public <init>(Ljava/lang/String;Ljava/lang/String;Ljava/util/BitSet;)V
  1>     ALOAD 0
  1>     ALOAD 1
  1>     ALOAD 2
  1>     ALOAD 3
  1>     INVOKESPECIAL org/elasticsearch/painless/Executable.<init> (Ljava/lang/String;Ljava/lang/String;Ljava/util/BitSet;)V
  1>     RETURN
  1>     MAXSTACK = 0
  1>     MAXLOCALS = 0
  1>   // access flags 0x1
  1>   public execute(Ljava/util/Map;Lorg/apache/lucene/search/Scorer;Lorg/elasticsearch/search/lookup/LeafDocLookup;Ljava/lang/Object;)Ljava/lang/Object;
  1>    L0
  1>     LINENUMBER 9 L0
  1>    L1
  1>     LINENUMBER 9 L1
  1>     NEW java/util/HashMap
  1>     DUP
  1>     INVOKESPECIAL java/util/HashMap.<init> ()V
  1>    L2
  1>     LINENUMBER 9 L2
  1>     ASTORE 5
  1>    L3
  1>     LINENUMBER 24 L3
  1>     ALOAD 5
  1>     DUP_X1
  1>    L4
  1>     LINENUMBER 25 L4
  1>     INVOKEDYNAMIC cat(Ljava/lang/Object;)Ljava/lang/Object; [
  1>       // handle kind 0x6 : INVOKESTATIC
  1>       org/elasticsearch/painless/DefBootstrap.bootstrap(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;I[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;
  1>       // arguments:
  1>       1
  1>     ]
  1>     LDC "cat"
  1>     INVOKEDYNAMIC concat(Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/String; [
  1>       // handle kind 0x6 : INVOKESTATIC
  1>       java/lang/invoke/StringConcatFactory.makeConcat(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
  1>       // arguments: none
  1>     ]
  1>     DUP_X1
  1>    L5
  1>     LINENUMBER 25 L5
  1>     INVOKEDYNAMIC cat(Ljava/lang/Object;Ljava/lang/Object;)V [
  1>       // handle kind 0x6 : INVOKESTATIC
  1>       org/elasticsearch/painless/DefBootstrap.bootstrap(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;I[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;
  1>       // arguments:
  1>       2
  1>     ]
  1>    L6
  1>     LINENUMBER 24 L6
  1>     ARETURN
  1>     MAXSTACK = 0
  1>     MAXLOCALS = 0
```

**Comment by uschindler** [comment]
How does Java 8 look like?

**Comment by rmuir** [comment]
```
// class version 52.0 (52)
// access flags 0x31
public final class org/elasticsearch/painless/Executable$Script extends org/elasticsearch/painless/Executable  {

  // compiled from: <debugging>

  // access flags 0x1
  public <init>(Ljava/lang/String;Ljava/lang/String;Ljava/util/BitSet;)V
    ALOAD 0
    ALOAD 1
    ALOAD 2
    ALOAD 3
    INVOKESPECIAL org/elasticsearch/painless/Executable.<init> (Ljava/lang/String;Ljava/lang/String;Ljava/util/BitSet;)V
    RETURN
    MAXSTACK = 4
    MAXLOCALS = 4

  // access flags 0x1
  public execute(Ljava/util/Map;Lorg/apache/lucene/search/Scorer;Lorg/elasticsearch/search/lookup/LeafDocLookup;Ljava/lang/Object;)Ljava/lang/Object;
   L0
    LINENUMBER 9 L0
    LINENUMBER 9 L0
    NEW java/util/HashMap
    DUP
    INVOKESPECIAL java/util/HashMap.<init> ()V
   L1
    LINENUMBER 9 L1
    ASTORE 5
   L2
    LINENUMBER 24 L2
    NEW java/lang/StringBuilder
    DUP
    INVOKESPECIAL java/lang/StringBuilder.<init> ()V
    ALOAD 5
    DUP_X1
   L3
    LINENUMBER 25 L3
    INVOKEDYNAMIC cat(Ljava/lang/Object;)Ljava/lang/Object; [
      // handle kind 0x6 : INVOKESTATIC
      org/elasticsearch/painless/DefBootstrap.bootstrap(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;I[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;
      // arguments:
      1
    ]
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/Object;)Ljava/lang/StringBuilder;
    LDC "cat"
    INVOKEVIRTUAL java/lang/StringBuilder.append (Ljava/lang/String;)Ljava/lang/StringBuilder;
    INVOKEVIRTUAL java/lang/StringBuilder.toString ()Ljava/lang/String;
    DUP_X1
   L4
    LINENUMBER 25 L4
    INVOKEDYNAMIC cat(Ljava/lang/Object;Ljava/lang/Object;)V [
      // handle kind 0x6 : INVOKESTATIC
      org/elasticsearch/painless/DefBootstrap.bootstrap(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;I[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;
      // arguments:
      2
    ]
   L5
    LINENUMBER 24 L5
    ARETURN
    MAXSTACK = 3
    MAXLOCALS = 6
}
```

**Comment by uschindler** [comment]
Hi,
I think I know the problem:
The Java 8 old code assumes while duplicating stack arguments that there is a stringbuilder on stack. But for Java 9, it is not there. So the "dup_x1" after the "aload 5" duplicates the wrong stack item.

I have to look at the generating code ton find a way how to handle this correctly. In fact we duplicate the wronmg item. For indy string concats a plain "dup" would be correct.

**Comment by rmuir** [comment]
I opened #18932 with the Debugger improvement.

**Comment by uschindler** [comment]
The bug is in EChain#write: 
```java
writer.writeDup(link.size, 1);         // dup the StringBuilder
```

See the comment. The second arguments must be 0 for indy string concats. Not sure how to fix this.

**Comment by rmuir** [comment]
Yes, thats the fix. all tests pass with that on java 9. we just have to conditionally do it.

**Comment by uschindler** [comment]
I have to verify the other parts doing concats, too. The compound code is hairy (and very complicated), and we had stack bugs before, too.

The second problem with indy string concats is: You pop a lot of stuff onto stack, while with Java 8 you pop one item and call append. In Java 9 you have no chance to look back in stack unless you record sizes - but then bytecode does not allow it.

**Comment by uschindler** [comment]
EBinary looks fine, no crazy stack duping. So its only EChain that hits the issue. I think we can easily fix this:
- I let writeNewStrings return an int (the actual size of element it pushed), for java 8 it returns 1, with indy concats just 0. This is the size of the element on stack used for the concats
- we just use return value in the dup instruction

**Comment by uschindler** [comment]
I added a PR (see above).
