### ISSUE TITLE
Same mapping over the index in elasticsearch 2.3.3

### ISSUE THREAD

**Issue by sgc445** [elastic/elasticsearch#18937]
**Elasticsearch version**:2.3.3

**JVM version**:1.7

**OS version**:14.04

I am working on a project which is currently using elasticsearch 1.4, Now we are going to upgrade elasticsearch,We have so many field which have different mapping on different record type .

We have some common field on different record type and have different implementation as per our requirement so they have different mapping as well. Is there any way to have different mapping over the same index?

Is there any meaning to make field mapping nested type which just require type string?

**Just add feature that user can have different mapping over the same index for same field through index setting**:

**Comment by clintongormley** [comment]
Hi @sgc445 

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
