### ISSUE TITLE
Allow to run elasticsearch queries as "raw json" string like in curl requests

### ISSUE THREAD

**Issue by cforce** [elastic/elasticsearch#18952]
Allow to run elasticsearch queries as "raw json" strings .
```
{
    ...,

    "aggs" : {
        "grades_count" : {
            "value_count" : {
                "script" : {
                    "file": "my_script",
                    "params" : {
                        "field" : "grade"
                    }
                }
            }
        }
    }
}
```
 Currently to run them through spring data es, i have to rebuild them with a builder pattern. But i just want to load some external ready to use query in form as json that used on the low level api as you would do with curl. The jest client ( https://github.com/spring-projects/spring-data-elasticsearch/pull/147 ) does not work on local embeeded elasticsearch. Thats the reason the ElasticSearchTemplate does not provide the needed API to run that kind of raw query (like for exmaple the SearchSourceBuilder in Jest) . In https://github.com/elastic/elasticsearch/pull/18735 it was created a new pull request, but does it support this requirement?
The following restrictions have to get solved:

- JestElasticsearchTemplate() does not implement the getClient() method.
```
public class JestElasticsearchTemplate implements ElasticsearchOperations, ApplicationContextAware {...
@Override
	public Client getClient() {
		throw new UnsupportedOperationException();
	}
```

- Spring data "ElasticsearchTemplate" does not implement raw string query feature like the example query (with aggs!!!) from above. 
- The base class "ElasticsearchOperations" does not provide the raw string query feature from JestElasticsearchTemplate()

Her i tried to make use of a snapshot of https://github.com/spring-projects/spring-data-elasticsearch/pull/147

 ```
@Bean
    public ElasticsearchOperations elasticsearchTemplate() {

        ElasticsearchOperations elasticsearchOperations;
        if (connection.isEmbedded()) {
            Client client = NodeBuilder.nodeBuilder().local(true).node().client();
            elasticsearchOperations = new ElasticsearchTemplate(client);
        } else {
            JestClientFactory factory = new JestClientFactory();
            factory.setHttpClientConfig(new HttpClientConfig.Builder(connection.getUrl())
                    .multiThreaded(connection.isMultiThreaded()).build());
            JestClient client = factory.getObject();
            elasticsearchOperations = new JestElasticsearchTemplate(client);
        }
        return elasticsearchOperations;
    }
```

**Comment by dadoonet** [comment]
It will be possible with Elasticsearch 5.0 REST client.
Spring data team will just have to use it.

In the meantime may be JEST could provide such a raw method? May be you should ask there?

**Comment by cforce** [comment]
As i use ElasticsearchOperations as wrapper for index creation and seraching, the problem is i can't access Jest api without brakingv the abstraction layer. I then must work with two "approaches dependent of the use case index/serach  - as i would to go along which spring as far as possible until thiy feature is available.
I have (as you see above) an swicth to configure if i use the embedded es (for dev env) or the external es (for cloud stage). I woould additional need to manage an "loop" connection for jest queries on the embedded  es if that is even possible . I have no spring (auto) configuration support here.

**Comment by cforce** [comment]
What is the release plan for Elasticsearch 5.0 REST client?

**Comment by dadoonet** [comment]
But I don't understand what we can add in elasticsearch to help here?

**Comment by cforce** [comment]
Well you are right.. i have to post that at spring data es project.

**Comment by cforce** [comment]
https://jira.spring.io/browse/DATAES-266
