### ISSUE TITLE
save base64 file ------mapper-attachments

### ISSUE THREAD

**Issue by xuzhou2020** [elastic/elasticsearch#18966]
Hi:
some problems as follows:
--------------------------------------------------

**Elasticsearch version**: 2.2.1

**JVM version**: jdk1.8

**OS version**:  windows 7

**Description of the problem including expected versus actual behavior**:

1.  I  install  plugin:  mapper-attachments

after it,  reboot   Elasticsearch

2.  create a mapping
mapping = XContentFactory.jsonBuilder().startObject()

					// 索引库名（类似数据库中的表）
					.startObject(indexType).startObject("properties")
							// ID
					.startObject("id").field("type", "string").endObject()

					.startObject("logtime").field("type", "string").endObject()

							// 标题  中文分词, field("analyzer", "ik")
					.startObject("title").field("type", "string").field("analyzer", "ik").field("include_in_all", false)
					.endObject()

							// 描述
					.startObject("atta").## field("type", "attachment")/*.field("analyzer", "ik")*/
					.endObject()

					.endObject().endObject().endObject();

3.  then  I test it.   using  firefox  RestClient

http://localhost:9200/op/atta/1

{
"id":"at001",
"logtime":'2016-06-20 10:30:00",
"title":"上传附件测试",
"attach":"6IOM5pmv6Imy5piv57qi6Imy55qELOiuoeeul+acuuaKgOacr+eahOWPkeWxlSzlhZrnmoQxM+Wkp+W3sue7j+WPrOW8gC5ramxpbmvpnIDopoHmi5vogZjmlrDlkZjlt6XkuoblkJc/Cg=="

}

and the result is ,

{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse"}],"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"json_parse_exception","reason":"Unexpected character (''' (code 39)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')\n at [Source: org.elasticsearch.common.io.stream.InputStreamStreamInput@37def43e; line: 3, column: 12]"}},"status":400}

so  what's wrong ???

**Comment by dadoonet** [comment]
Please ask your questions on discuss.elastic.co where we can definitely help you better.

Also the code you provided is incorrect and you probably modify it for this ticket. See `##` for example.
Would be better to GET the actual mapping you have with your RestClient and copy in discuss its JSON form.

**Comment by xuzhou2020** [comment]
1. discuss.elastic.co    register???  git  account cannot log in.


2. here is the java code..
------------------------------------------------



package demo;

import org.elasticsearch.common.xcontent.XContentBuilder;
import org.elasticsearch.common.xcontent.XContentFactory;
import tool.ESTool;

import java.io.IOException;

/**
 * Created by Administrator on 2016/6/8.
 */
public class BaiduClient {

	public static void main(String[] args) throws Exception {

	/*	//数据库名字 db
		String index = "op";

		//表的名字 table
		String type = "atta";

		//生成的create table 语句
		XContentBuilder mapping = createMapping(type);

		ESTool esTool = new ESTool();
		esTool.setIp("127.0.0.1").setIndexName(index).setIndexType(type);

		//建立表(create table )
		esTool.createIndex(index, type, mapping);

		//添加数据
		//        URL resource = Object.class.getResource("/config/data");
		//        System.out.println(resource);
		//        Files.lines(Paths.get(resource.toURI()))
		//                .forEach(txt -> {
		//
		//
		//                    System.out.println(txt);
		//                    esTool.save( BaseUtil.uuid(),txt);
		//                });

		String id = "10001";

		//      String jsonData=  {"id":"1004","logtime":"2014-12-24 09:20:30","title":"浅析理论资源与文学理论体系建构的危机","desc":"经多年积累，文艺学学科建设进入到一个新的发展阶段，其显在的表征在于部分文学理论家在体系建构方面更趋自觉。有学者就认为，在反本质主义的视域中，新世纪有三种理论体系尤..."}
		String jsonData = "上面的json字符串";

		//新增数据
		esTool.save(id, jsonData);

		//修改
		esTool.update(id, jsonData);

		//删除
		esTool.deleteById(id);

		//查询
		String keyword = "文学";
		//第一页
		int page = 1;

		//每页显示15行
		int rows = 15;
		esTool.query(keyword, page, rows);
*/


		//数据库名字 db
		String index = "op";

		//表的名字 table
		String type = "atta";

		//生成的create table 语句
		XContentBuilder mapping = createAttaMapping(type);


		ESTool esTool = new ESTool();
		esTool.setIp("127.0.0.1").setIndexName(index).setIndexType(type);

		//建立表(create table )
		esTool.createIndex(index, type, mapping);

		//添加数据
		//        URL resource = Object.class.getResource("/config/data");
		//        System.out.println(resource);
		//        Files.lines(Paths.get(resource.toURI()))
		//                .forEach(txt -> {
		//
		//
		//                    System.out.println(txt);
		//                    esTool.save( BaseUtil.uuid(),txt);
		//                });
//
		String id = "10001";
//
//		//      String jsonData=  {"id":"1004","logtime":"2014-12-24 09:20:30","title":"浅析理论资源与文学理论体系建构的危机","desc":"经多年积累，文艺学学科建设进入到一个新的发展阶段，其显在的表征在于部分文学理论家在体系建构方面更趋自觉。有学者就认为，在反本质主义的视域中，新世纪有三种理论体系尤..."}

		String jsonData ="{\"id\":\"at001\", \"logtime\":'2016-06-20 10:30:00\", \"title\":\"上传附件测试\", \"attach\":\"6IOM5pmv6Imy5piv57qi6Imy55qELOiuoeeul+acuuaKgOacr+eahOWPkeWxlSzlhZrnmoQxM+Wkp+W3sue7j+WPrOW8gC5ramxpbmvpnIDopoHmi5vogZjmlrDlkZjlt6XkuoblkJc/Cg==\"}";
//		String jsonData = "上面的json字符串";

		jsonData="{\"id\":\"at001\", \"logtime\":'2016-06-20 10:30:00\", \"title\":\"上传附件测试\", \"attach\":\"6IOM5pmv6Imy5piv57qi6Imy55qELOiuoeeul+acuuaKgOacr+eahOWPkeWxlSzlhZrnmoQxM+Wkp+W3sue7j+WPrOW8gC5ramxpbmvpnIDopoHmi5vogZjmlrDlkZjlt6XkuoblkJc/Cg==\"}";
//
//		//新增数据
		esTool.save(id, jsonData);
//
//		//修改
//		esTool.update(id, jsonData);
//
//		//删除
//		esTool.deleteById(id);
//
//		//查询
//		String keyword = "文学";
//		//第一页
//		int page = 1;
//
//		//每页显示15行
//		int rows = 15;
//		esTool.query(keyword, page, rows);



	}

	/**
	 * 创建 建表的语句  create table ()...
	 *
	 * @param indexType 表名
	 * @return
	 */
	public static XContentBuilder createMapping(String indexType) {
		XContentBuilder mapping = null;
		try {
			mapping = XContentFactory.jsonBuilder().startObject()

					// 索引库名（类似数据库中的表）
					.startObject(indexType).startObject("properties")
					// ID
					.startObject("id").field("type", "string").endObject()

					.startObject("logtime").field("type", "string").endObject()

					// 标题  中文分词, field("analyzer", "ik")
					.startObject("title").field("type", "string").field("analyzer", "ik").field("include_in_all", false)
					.endObject()

					// 描述
					.startObject("desc").field("type", "string").field("analyzer", "ik").field("include_in_all", false)
					.endObject()



					.endObject().endObject().endObject();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return mapping;
	}


	/**
	 * 测试附件
	 * @param indexType
	 * @return
	 */
	public static XContentBuilder createAttaMapping(String indexType) {
		XContentBuilder mapping = null;
		try {
			mapping = XContentFactory.jsonBuilder().startObject()

					// 索引库名（类似数据库中的表）
					.startObject(indexType).startObject("properties")
							// ID
					.startObject("id").field("type", "string").endObject()

					.startObject("logtime").field("type", "string").endObject()

							// 标题  中文分词, field("analyzer", "ik")
					.startObject("title").field("type", "string").field("analyzer", "ik").field("include_in_all", false)
					.endObject()

							// 描述
					.startObject("atta").field("type", "attachment")/*.field("analyzer", "ik")*/
					.endObject()

					.endObject().endObject().endObject();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return mapping;
	}

}






package tool;

import org.elasticsearch.action.admin.indices.mapping.put.PutMappingRequest;
import org.elasticsearch.action.admin.indices.mapping.put.PutMappingResponse;
import org.elasticsearch.action.index.IndexRequestBuilder;
import org.elasticsearch.action.search.SearchResponse;
import org.elasticsearch.action.search.SearchType;
import org.elasticsearch.client.Client;
import org.elasticsearch.client.Requests;
import org.elasticsearch.client.transport.TransportClient;
import org.elasticsearch.common.text.Text;
import org.elasticsearch.common.transport.InetSocketTransportAddress;
import org.elasticsearch.common.xcontent.XContentBuilder;
import org.elasticsearch.index.query.MultiMatchQueryBuilder;
import org.elasticsearch.index.query.QueryBuilders;
import org.elasticsearch.search.SearchHit;
import org.elasticsearch.search.SearchHits;
import org.elasticsearch.search.highlight.HighlightField;
import org.elasticsearch.search.sort.SortOrder;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.util.Map;

/**
 * Created by Administrator on 2016/6/8.
 */
public class ESTool {

    //elastic服务器ip
    private String ip="127.0.0.1";

    //数据库db
    private String indexName;

    //表 table
    private String indexType;


    public String getIp() {
        return ip;
    }

    public ESTool setIp(String ip) {
        this.ip = ip;
        return this;
    }

    public String getIndexName() {
        return indexName;
    }

    public ESTool setIndexName(String indexName) {
        this.indexName = indexName;
        return this;
    }

    public String getIndexType() {
        return indexType;
    }

    public ESTool setIndexType(String indexType) {
        this.indexType = indexType;
        return this;
    }


    /**
     * 创建一个 客户端连接
     * @return
     */
    public static Client esClient(){

        Client esClient = null;
        try {



//            esClient = new TransportClient().addTransportAddress(new InetSocketTransportAddress("127.0.0.1", 9300));
//

//            esClient = TransportClient.builder().build()
//                    .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByAddress(new byte[]{(byte)127,(byte)0,(byte)0,(byte)1}), 9300));


            esClient = TransportClient.builder().build()
                    .addTransportAddress(new InetSocketTransportAddress(new InetSocketAddress("127.0.0.1", 9300)));
        } catch (Exception e) {
            e.printStackTrace();
        }

        return esClient;
    }



    // 创建索引 database/table
    // 第一次 加载的时候,创建

    /**
     *
     * @param indexName   db
     * @param indexType   table
     * @throws java.io.IOException
     */
    public static void createIndex(String indexName, String indexType,XContentBuilder mapping) throws IOException {
        Client esClient = ESTool.esClient();

//        System.out.println("mapping:" + mapping.string());

        // 创建一个空索引  database
        try {
            esClient.admin().indices().prepareCreate(indexName).execute().actionGet();
        }catch (Exception e){
            e.printStackTrace();
        }

        //表结构  执行
        try {
            PutMappingRequest putMapping = Requests.putMappingRequest(indexName).type(indexType).source(mapping);
            PutMappingResponse response = esClient.admin().indices().putMapping(putMapping).actionGet();

            if (!response.isAcknowledged()) {
                System.out.println("Could not define mapping for type [" + indexName + "]/[" + indexType + "].");
            } else {
                System.out.println("Mapping definition for [" + indexName + "]/[" + indexType + "] succesfully created.");
            }
        }catch (Exception e){
            e.printStackTrace();
        }

        esClient.close();
    }



    /**
     * 添加一行数据
     * @param id
     * @param jsonData
     */
    public  void save(String id,String jsonData){

        Client client=ESTool.esClient();

        IndexRequestBuilder requestBuilder = client.prepareIndex(indexName, indexType,id).setRefresh(true);

        /*IndexResponse indexResponse = */requestBuilder.setSource(jsonData).execute().actionGet();

        client.close();
    }


    /**
     * 更新一行数据
     * @param id
     * @param jsonData
     */
    public  void update(String id,String jsonData){

        Client client=ESTool.esClient();

        //更新数据
        client.prepareUpdate().setIndex(indexName).setType(indexType).setId(id).setDoc(jsonData).get();

        client.close();
    }



    /**
     * 删除一行数据 byId
     * @param id
     */
    public  void deleteById(String id){

        Client client=ESTool.esClient();

        //delete数据
        client.prepareDelete().setIndex(indexName).setType(indexType).setId(id).get();
        client.close();

    }


    /**
     * 根据关键字查询
     * @param keyword  关键字
     * @param page     第几页, 1,2,3
     * @param rows     每页显示多少行
     */
    public  void query(String keyword,int page, int rows){



        Client esClient = ESTool.esClient();

        MultiMatchQueryBuilder multiMatchQueryBuilder = QueryBuilders.multiMatchQuery(
                keyword,     // Text you are looking for
                //kimchy elasticsearch是要查询的字符串
                "title"/*, "desc"*/           // Fields you query on
                //user 和 message都是field
        );

        SearchResponse searchResponse = esClient
                .prepareSearch(indexName)
                .setTypes(indexType)

                //设置高亮显示字段
                .addHighlightedField("title")

                //高亮显示标识
                .setHighlighterPreTags("<em>")
                .setHighlighterPostTags("</em>")

                .setSearchType(SearchType.DFS_QUERY_THEN_FETCH)
                .setQuery(multiMatchQueryBuilder)

                //排序字段
                .addSort("logtime", SortOrder.DESC)
                .setFrom(page-1)
                .setSize(rows)
                .execute().actionGet();

        SearchHits hits = searchResponse.getHits();

        long total = hits.totalHits();
        System.out.println("total="+total);

        if(total>0){

            SearchHit[] searchHists = hits.getHits();

            for (SearchHit hit : searchHists) {

                Map<String, Object> source = hit.getSource();
                System.out.println(source);

                // 获取对应的高亮域
                Map<String, HighlightField> result = hit.highlightFields();

                // 从设定的高亮域中取得指定域
                HighlightField titleField = result.get("title");

                if(titleField!=null){

                    // 取得定义的高亮标签
                    Text[] fragments = titleField.fragments();

                    // 为title串值增加自定义的高亮标签
                    String title = "";
                    for (Text text : fragments) {
                        title += text;
                    }
                    // 将追加了高亮标签的串值重新填充到对应的对象
                    // product.setTitle(title);
                    // 打印高亮标签追加完成后的实体对象
                    System.out.println(title);
                }


            }

        }



    }


}

**Comment by dadoonet** [comment]
Please join https://discuss.elastic.co/

**Comment by xuzhou2020** [comment]
Hi:
    I ask a question, but  it seemed that nobody pays attention to it .
    https://discuss.elastic.co/

**Comment by dadoonet** [comment]
You need to be patient on discuss. 

Read:

* https://discuss.elastic.co/t/notes-on-using-these-forums/118
* https://www.elastic.co/fr/community/codeofconduct

If you need to have "immediate" answers with a SLA we can connect you to the sales team.

Thanks!
