### ISSUE TITLE
painless doc examples could be tested better

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#18961]
I want to revamp this doc, i really do. But right now the examples in there aren't really being tested. I can put garbage methods in scripts and nothing fails. Perhaps its only compiling them and not actually running them against any documents, I don't know...

**Comment by nik9000** [comment]
It depends....  I can have a look at this on Monday probably.

**Comment by rmuir** [comment]
Thanks... It may be a simple bug in the examples themselves. Generated yaml seemed ok but no expert... I just have the feeling no actual docs are being hit

**Comment by rmuir** [comment]
here is an example of what i'm trying that isn't provoking any fail. Of course this will compile, but if it were actually to run on any document it would crap out:

```
--- a/docs/reference/modules/scripting/painless.asciidoc
+++ b/docs/reference/modules/scripting/painless.asciidoc
@@ -109,7 +109,7 @@ GET hockey/_search
     "total_goals": {
       "script": {
         "lang": "painless",
-        "inline": "int total = 0; for (int i = 0; i < doc['goals'].length; ++i) { total += doc['goals'][i]; } return total;"
+        "inline": "doc['goals'].bogusMethod()"
       }
     }
   }
```

Since we have a lot of dynamic functionality i want it to catch me if i screw up. Part of the problem I think is that our examples are too lenient? I imagine having a lot of these to explain various syntax and stuff like that... Is there another way to encode checks other than `//TESTRESPONSE` ? Or another way to put it, a way to do `//TESTRESPONSE` but without it being user-visible in the docs?

**Comment by clintongormley** [comment]
> Or another way to put it, a way to do //TESTRESPONSE but without it being user-visible in the docs?

Yes, use comment blocks:

    ////////////////////
    None of this is visible:

    [source,js]
    ---------------
    PUT foo/bar/1
    { "foo": 5 }
    ---------------
    // TEST
    ////////////////////

    This example is visible:

    [source,js]
    ---------------
    GET foo/_search
    {
      "script_fields": {
        "my_field": {
          "script": {
            "lang": "painless",
            "inline": "doc['foo'].value+1"
          }
        }
      }
    }
    ---------------
    // CONSOLE
    // TEST[continued]

    ////////////////////
    The response can be hidden as well

    [source,js]
    ---------------
    {
      "took": 2,
      "timed_out": false,
      "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
      },
      "hits": {
        "total": 1,
        "max_score": 1,
        "hits": [
          {
            "_index": "foo",
            "_type": "bar",
            "_id": "1",
            "_score": 1,
            "fields": {
              "my_field": [
                6
              ]
            }
          }
        ]
      }
    }
    ---------------
    // TESTRESPONSE[s/"took".*/"took": "$body.took",/]
    ////////////////////

**Comment by rmuir** [comment]
thanks @clintongormley

**Comment by nik9000** [comment]
I merged https://github.com/elastic/elasticsearch/pull/18979 which might make the comments not a required thing for painless. You bogusMethod example fails now. I'm going to close this because I think it is enough. If not, open it again.

**Comment by rmuir** [comment]
@nik9000 thanks a lot for looking into this!
