### ISSUE TITLE
ElasticSearch always true option.

### ISSUE THREAD

**Issue by Jack-Collins** [elastic/elasticsearch#18970]
Due to a major [shortfall ](http://stackoverflow.com/questions/6114435/in-mustache-templating-is-there-an-elegant-way-of-expressing-a-comma-seperated-l)with the mustache templating language I have found that it very difficult to query based on an array passed as a parameter as there is a known issue with a trailing comma.

To cut a long story short, a more elegant solution that awkwardly manipulating the input data would be possible if an always true option existed within elastic

```
{
"bool" : {
         "must" : [
             {
                 "term" : "myInputtedTerm1" 
             },
             {
                  "term" : "myInputtedTerm2"
             },            
                 alwaysTrue         
        ]
    }
}
```

Digging around I can't see anything like this that exists so I do believe it is worth implementing. Or if somebody has a workaround, please let me know.

Cheers

**Comment by clintongormley** [comment]
@tlrx would your toJSON change help here?

**Comment by tlrx** [comment]
The trailing comma is a well known issue and we'll provide a workaround for that. It should help in this case, yes.

@Jack-Collins How your parameters look like for the sample you gave?

**Comment by Jack-Collins** [comment]
the param is just an array: ["myInputtedTerm1", "myInputtedTerm2"]

**Comment by tlrx** [comment]
@Jack-Collins Thanks.

The pull request #18856 might help you. It allows something like:

```json
{
    "inline": "{\"query\":{\"bool\":{\"must\": {{#toJson}}clauses{{/toJson}} }}}",
    "params": {
        "clauses": [
            { "term": "foo" },
            { "term": "bar" }
        ]
   }
}
```

to be rendered as:

```json
{
    "query" : {
      "bool" : {
        "must" : [
          {
            "term" : "foo"
          },
          {
            "term" : "bar"
          }
        ]
      }
    }
}
```
