### ISSUE TITLE
Tests: OpenCloseIndexIT (suite) breaks with certain seed

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#18976]
From CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=centos/620/console

Also fails on osx locally. Test leaks file handles.

To reproduce: 
```
gradle clean :core:integTest -Dtests.seed=8E8A4389665B4EFB -Dtests.class=org.elasticsearch.indices.state.OpenCloseIndexIT -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=UTC
```

**Comment by s1monw** [comment]
I think this is fixed by https://github.com/elastic/elasticsearch/commit/459665914b3aa3b107a3e3c9069ab812ebbf36b7 but I will verify

**Comment by s1monw** [comment]
yeah doensn't fail anymore it's the `@Inject` annotation on NodeEnviroment that messes things up here
