### ISSUE TITLE
Possible Regression on 5.0A3 for string to text conversion

### ISSUE THREAD

**Issue by isaias** [elastic/elasticsearch#18974]
**Elasticsearch version**: 
5.0 A3

**JVM version**: 
1.8.0_91

**OS version**:
CentOS 7

**Description of the problem including expected versus actual behavior**:
On 5.0 A2 the automatic upgrade https://github.com/elastic/elasticsearch/pull/17861 was working fine for a mapped string using an analyzer (Path Hierarchy Tokenizer), after upgrade to 5.0 A3 it didn't work, so I think we have a regression at that point.

**Steps to reproduce**:
 1. Define an analyser for a path_hierarchy

"analyzer": {
        "paths": {
          "tokenizer": "path_hierarchy"
        }
 2. Set it for an analyzed string on mapping 
 

**Provide logs (if relevant)**:

**Comment by jpountz** [comment]
I tried the following locally on a fresh download of 5.0 alpha3

```
PUT test
{
  "settings": {
    "analysis": {
      "analyzer": {
        "path_analyzer": {
          "type": "custom",
          "tokenizer": "path_tokenizer"
        }
      },
      "tokenizer": {
        "path_tokenizer": {
          "type": "path_hierarchy"
        }
      }
    }
  },
  "mappings": {
    "test": {
      "properties": {
        "foo": {
          "type": "string",
          "analyzer": "path_analyzer"
        }
      }
    }
  }
}

GET test/_mapping
```

which returned

```
{
  "test": {
    "mappings": {
      "test": {
        "properties": {
          "foo": {
            "type": "text",
            "analyzer": "path_analyzer"
          }
        }
      }
    }
  }
}
```

This looks correct to me. Could you provide a recreation for the issue that you are seeing?

**Comment by isaias** [comment]
@jpountz I've tried to reproduce on my environment and it didn't happen anymore. The only difference was that I updated from Alpha 2 to Aplha3 using RPM. I've tried to do it again but the error didn't happen. I'll close. Thanks.

**Comment by isaias** [comment]
@jpountz, I reproduced the error with a fresh Alpha 3, see the "bar" definition.


{
  "settings": {
    "analysis": {
      "analyzer": {
        "path_analyzer": {
          "type": "custom",
          "tokenizer": "path_tokenizer"
        }
      },
      "tokenizer": {
        "path_tokenizer": {
          "type": "path_hierarchy"
        }
      }
    }
  },
  "mappings": {
    "test": {
      "properties": {
        "foo": {
          "type": "string",
          "analyzer": "path_analyzer"
        },
        "bar": {
            "type": "string",
            "index": "not_analyzed",
            "fields": {
              "tree": {
                "type": "string",
                "analyzer": "path_analyzer"
              }
            },
            "include_in_all": false,
            "fielddata": false
          }
      }
    }
  }
}

**Comment by clintongormley** [comment]
Actually, this  is just to do with `include_in_all`:

    PUT t
    {
      "mappings": {
        "test": {
          "properties": {
            "foo": {
              "type": "string",
              "include_in_all": false
            }
          }
        }
      }
    }

**Comment by jpountz** [comment]
OK, so we need to add `include_in_all` to the whitelist of parameters we automatically upgrade.
