### ISSUE TITLE
One similarity per index

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#18971]
Currently you can mix BM25 and the classic similarity in the same index:

```
{
  "book" : {
    "properties" : {
      "title" : { "type" : "text", "similarity" : "BM25" },
      "text" : { "type" : "text", "similarity" : "classic" }
    }
}
```

... this can be buggy since the base similarity cannot be picked properly. The base similarity is used to compute a factor for the coordinates and the query norm (cf Similarity.coord and Similarity.queryNorm).
It is a per query setting that can change the score completely. For `BM25` the coord and the queryNorm are disabled (returns 1.0f) whereas they are important factors in the `classic` similarity. To resolve this we have two settings for the index similarity `index.similarity.default.type` and `index.similarity.base.type`.
In order to make the things easier we could have a single setting:
`index.similarity.type`
... that is dynamically updatable if the similarities are compatible: 
https://github.com/elastic/elasticsearch/issues/6727
This would not make the "are compatible?" easier but this would prevent the user to shoot themselves in the foot.

**Comment by clintongormley** [comment]
I agree that we should combine those two settings into one, but am unsure about the name.  Don't forget that there are other configuration options which can appear under [`index.similarity`](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules-similarity.html#configuration).  Perhaps we should just call it `index.similarity.default.type`.

Btw in master, if I do:

    PUT t/t/1
    {"text": "foo"}
        
    GET t/_mapping/field/text?include_defaults

I get:

              "similarity": "classic",

so something even more is wrong...  Is it the get-field-mapping API or the default similarity?

**Comment by clintongormley** [comment]
Ah I see you're on it already: https://github.com/elastic/elasticsearch/pull/18948

**Comment by clintongormley** [comment]
@jimferenczi re uniting those two settings i'm having second thoughts...  The only reason for having `.base.type` is to support TF/IDF for bwc.  But query norm and coord are going to be removed in Lucene (see https://issues.apache.org/jira/browse/LUCENE-7347)

We shouldn't encourage people to use TF/IDF by default for new indices, just for bwc for queries on old indices.  The  `.base.type` setting can be removed in ES 6.0, so perhaps we should just keep it as it is today, ie two separate settings, but set to bm25 by default.

Note: similarities can be updated on closed indices, so people can move entirely to BM25 even with existing indices.

**Comment by jpountz** [comment]
This is only under discussion for now and it might be a bit controversial, but indeed it would have the benefit of removing the need for a `base` similarity.

**Comment by rmuir** [comment]
+1 to move away from queryNorm and coord, even if they have to hang around lucene for some reason.

Really: this is 1980s type stuff :)

**Comment by jimferenczi** [comment]
Discussed in FixItFriday. One option could be to remove the support for the `classic` similarity in ES. BM25 should be considered as a full replacement for TFIDF similarity. Since the classic similarity is the only user of the queryNorm, coord API we could completely remove the `base` similarity if `classic` is removed.

**Comment by rmuir** [comment]
> Discussed in FixItFriday. One option could be to remove the support for the classic similarity in ES. BM25 should be considered as a full replacement for TFIDF similarity.

I'd be +1 to this. Here is why. users of `classic` will be unhappy with Lucene 6 regardless of what we do: see https://issues.apache.org/jira/browse/LUCENE-6711

This is a great improvement to all similarities, including `classic`. But it means, there is literally zero "value" backwards-compatibility-wise, in providing `classic` to old users. If they have *any sparsity at all*, not just scores, but also relative ranking of documents will change (for the better). 

So why keep `classic` around at all?

**Comment by jimczi** [comment]
Duplicate of #23208
