### ISSUE TITLE
[feature request] provide other shard allocation strategies

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#18989]
[situation description]
I have a big cluster which stores daily rolling index and it keeps many days index in cluster. one day, the write traffic will grow for some reason and that days index will grow much larger than usual. So I have to add more nodes to the cluster to share the write traffic. meantime, I don't want to rebalance the data between existing nodes and newly added nodes. 

so I need below shard allocation strategy

**Describe the feature**:
allocation shards based on index balance not overall shard balance.

**Comment by nik9000** [comment]
I think you can use allocation filtering to get this.

**Comment by makeyang** [comment]
@nik9000  I'm talking about a user friendly way to achieve so. u are talking about there is a way to achieve so. so basiclly we are talking about different thing.

**Comment by clintongormley** [comment]
@makeyang I have no idea what this means:

> allocation shards based on index balance not overall shard balance.

Please can you provide some detail on your issues otherwise I'm just going to close them.

**Comment by makeyang** [comment]
@clintongormley
let me give a details. Let's say I have a cluster with A and B, 2 nodes. And I have a detail rolling index named index_20160101, index_20160102 etc. at the beginning, all the shards are allocated one A and B.  so now day, I added 2 nodes, C and D into cluster with rebalance set to false. (because I added node to cover write spikes) but when I add these 2 nodes, newly created index are all alocated on C and D because they carry little shards. but this is not I added nodes for. I added nodes to balance write traffic between A B C and D.
 so without consider overall shards allocation but only one index allocation, which means to see if shard per index is balanced acoss the nodes, I can achieve so.

**Comment by ywelsch** [comment]
If you want a balance purely based on spreading shards of each index you can set `cluster.routing.allocation.balance.shard` to 0 and `cluster.routing.allocation.balance.index` to some value > 0 (see https://www.elastic.co/guide/en/elasticsearch/reference/current/shards-allocation.html#_shard_balancing_heuristics ).

**Comment by clintongormley** [comment]
And if @ywelsch 's suggestion isn't enough, you can use https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-total-shards.html

**Comment by makeyang** [comment]
@clintongormley @ywelsch 
let me see.
