### ISSUE TITLE
exception in thread "main" java.lang.RuntimeException bootstrap checks failed

### ISSUE THREAD

**Issue by gutasaputra** [elastic/elasticsearch#18982]
hello there,

thanks in advance to create such a wonderfull tools like elasticsearch.
i wanna to implement it in my application to boost-up the search feature that i have.

the problems is, when i ran **bin\elasticsearch.bat** , i always getting this kinda error.

> exception in thread "main" java.lang.RuntimeException bootstrap checks failed

> initial heap size [268435456] not equal to maximum heap size
> [2147483648] this can cause resize pause and prevents mlockall
> from locking the entire heap
> 
> please set discovery.zen.minimum_mater_nodes to a majority
> of the number of master eligible nodes in your cluster

**this is my environment information** 

**Elasticsearch version:**
Version: 5.0.0-alpha1, Build: 7d4ed5b/2016-04-04T10:39:25.841Z, JVM: 1.8.0_91

**JVM version:**
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**OS Version**
Win 10 64 bit.

i read this article : 
https://www.elastic.co/guide/en/elasticsearch/guide/1.x/_important_configuration_changes.html

and then i decide to set : 
**discovery.zen.minimum_master_nodes: 2**

the same error cames up.
what should i do in order to fix that?

i hope you guys can help me to fix this kinda of error.

**Comment by jasontedor** [comment]
The bootstrap checks are [documented](https://www.elastic.co/guide/en/elasticsearch/reference/master/bootstrap-checks.html). You're running into the [heap size check](https://www.elastic.co/guide/en/elasticsearch/reference/master/_heap_size_check.html) and the [minimum master nodes check](https://www.elastic.co/guide/en/elasticsearch/reference/master/_minimum_master_nodes_check.html). It looks like you already figured out to set `discovery.zen.minimum_master_nodes` but I do not see any indication that you also tuned the heap size? You need configure the minimum heap size to be equal to the maximum heap size if Elasticsearch is reachable via an external network interface.

> and then i decide to set : 
**discovery.zen.minimum_master_nodes: 2**

> the same error cames up.

Are you sure that that is what happened? If so, can you please provide a reproduction? I would have expected that the minimum master nodes bootstrap check would be passing and that you would only see an error on the heap size bootstrap check failing.

Please note that Elastic reserves GitHub for verified bug reports and feature requests. If you have general questions, the [Elastic Discourse forum](https://discuss.elastic.co) is a great place to get help.

**Comment by gutasaputra** [comment]
ohya, i forget to change the xms and xmx value.
i updated to this : 

> -Xms2g
> -Xmx2g

thanks alot

![elastic](https://cloud.githubusercontent.com/assets/1556126/16206888/c2d74e08-3754-11e6-95bf-c7b9f7db0946.png)

**Comment by jasontedor** [comment]
> thanks alot

You're welcome.
