### ISSUE TITLE
[feature request]more memory consumption metrix

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#18988]
**Describe the feature**:
provide more memory consumption metrix like 
index requests memory useage
index response memory usage
search requests memory usage
search workflow(lucene doc etc) memory usage
search response memory usage
cluster status memory usage
etc

**Comment by clintongormley** [comment]
@makeyang as usual you have provided a few keywords without explaining what you would like this feature to look like, how you want to use it, etc.  Please provide a reasonable explanation.

**Comment by makeyang** [comment]
@clintongormley  sorry, I thought u guys would thouth the same thing ~~~
better provide below APIs for monitor nodes/cluster momory consuption:
request API: GET _cat/memory
response:
node index_request_memory, index_response_memory, etc, segment_memory, fielddata, filtercache
XXXXX

this is basiclly what I thought how I would use it. 
the basic idea is:
when I give each node some memory for heap space, I can use JVM tools to detected how much heap memory is used, but I don't know the details. 
the details are consisted of what the part I mention plus segment memory, fielddata etc.
we have to know if memory is upder process or not and which part consump majority part of memory. 
with and only with this, we can estimate the capisity of memory very precisily.

**Comment by clintongormley** [comment]
@makeyang we provide memory stats (with a lot of detail) for segments, fielddata and doc values, caches,  indexing buffers, and a host of other values.  Look at `GET _nodes/stats`. Index request/response and search request/response is all mixed in together as they use a pool of BigArrays, and the memory use is usually transient so it doesn't make sense to report on that.

The one number we don't report is cluster state size, but there is an open issue for it: https://github.com/elastic/elasticsearch/issues/3415

What else is missing?

**Comment by makeyang** [comment]
@clintongormley  I don't agree with this one: the memory use is usually transient so it doesn't make sense to report on that. 
consider this situation: if the memory presure is caused by heavy indexing or searching, that makes a lot of sense to report these memory consumption.
remember, we get these values when and only when memory is under presure, then these transient value u mentioned is "persisited".

**Comment by clintongormley** [comment]
For this we have the [`inflight_requests` circuit breaker](https://www.elastic.co/guide/en/elasticsearch/reference/master/circuit-breaker.html#in-flight-circuit-breaker), which will report its current memory usage.

What else is missing?

**Comment by makeyang** [comment]
circuit breaker can't report the memory consumption.

**Comment by clintongormley** [comment]
Yes it can.  That's what the `estimated_size_in_bytes` is:

        "in_flight_requests": {
          "limit_size_in_bytes": 2112618496,
          "limit_size": "1.9gb",
          "estimated_size_in_bytes": 0,
          "estimated_size": "0b",
          "overhead": 1,
          "tripped": 0
        },

**Comment by bleskes** [comment]
@makeyang I'm not sure what you mean exactly with 

> we get these values when and only when memory is under presure, then these transient value u mentioned is "persisited".

But maybe you are looking for something like Marvel - this is a monitoring tool that collects stats data and store it so you can see the historical behavior . See https://www.elastic.co/products/marvel
