### ISSUE TITLE
[README.textfile] From source build 

### ISSUE THREAD

**Issue by sjyun** [elastic/elasticsearch#18991]
**Elasticsearch version**: master branch

**JVM version**: 1.8

**OS version**: windows 8

**Description of the problem including expected versus actual behavior**:
h3. Building from Source
Elasticsearch uses "Gradle":http://gradle.org for its build system. You'll need to have a modern version of Gradle installed - 2.8 should do.
In order to create a distribution, simply run the @gradle build@ command in the cloned directory.

**Steps to reproduce**:
 1. clone elasticsearch
 2. cd source home
 3. gradle build

**Provide logs (if relevant)**:

**Describe the feature**:
how about change discription?
gradle :distribution:rpm:assemble
gradle :distribution:zip:assemble
gradle :distribution:tar:assemble

more simple and fast

**Comment by clintongormley** [comment]
What do you mean?
