### ISSUE TITLE
jsr166e library comes inbuilt in Java 1.8. Changes need to make use of it.

### ISSUE THREAD

**Issue by SKumarMN** [elastic/elasticsearch#19005]
As Java 1.8 comes inbulit with jsr166e library (java.util.concurrent.atomic.LongAdder), woudn't it be nice idea to make use of it than an external jsr166e library(com.twitter.jsr166e.LongAdder).

I know java 1.7 doesn't have it hence jsr166e library is shipped along with ES. Till when ES would be supporting java versions less than 1.8?

**Comment by jasontedor** [comment]
> As Java 1.8 comes inbulit with jsr166e library (java.util.concurrent.atomic.LongAdder), woudn't it be nice idea to make use of it than an external jsr166e library(com.twitter.jsr166e.LongAdder).

We already do in master.

> Till when ES would be supporting java versions less than 1.8?

The master branch already requires Java 8.
