### ISSUE TITLE
Yaml parser does not support full set of boolean options

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#19006]
As it stands today, the boolean parser [only accepts the following](https://github.com/elastic/elasticsearch/blob/v2.3.3/core/src/main/java/org/elasticsearch/common/Booleans.java#L123-L134):

- true: `"true"`, `"on"`, `"yes"`, `1`
- false: `"false"`, `"off"`, `"no"`, `0`

But the [yaml spec says these are all valid](http://yaml.org/type/bool.html):

>  y|Y|yes|Yes|YES|n|N|no|No|NO
|true|True|TRUE|false|False|FALSE
|on|On|ON|off|Off|OFF

I'm not sure how this relates to the effort to [make settings less lenient](https://github.com/elastic/elasticsearch/issues/11503), but it feels problematic right now that not all valid yaml booleans are recognized (e.g. "True").  Maybe I'm just missing something?

Arose from user question: https://discuss.elastic.co/t/value-cannot-be-parsed-to-boolean-is-there-some-to-get-es-to-say-which-property-this-is

**Comment by jasontedor** [comment]
There is no requirement to support language-independent types, there are optional. The only schema that is required is the [failsafe schema](http://www.yaml.org/spec/1.2/spec.html#id2802346). Note that the (optional) [JSON schema](http://www.yaml.org/spec/1.2/spec.html#id2803629) only requires support for `(true|false)`.

**Comment by jasontedor** [comment]
My preference is that we should go the other direction and *only* support `(true|false)` and even get rid of `on`, `yes` and `1`, and `off`, `no` and `0`. I've always found `on` and `no` to be particularly offensive because the risk of an unnoticeable typo being very high.

**Comment by polyfractal** [comment]
I'd definitely be in favor of *just* supporting `true|false` as well.  The current situation is very confusing, since you aren't really sure what parts of the yaml spec are actually supported.
