### ISSUE TITLE
X-Pack Alpha 3 - Role Management - Web UI not correctly auto-completing for field-level security field

### ISSUE THREAD

**Issue by CCoffie** [elastic/elasticsearch#19000]
**Elasticsearch version**: 5.0.0-alpha3

**OS version**: Debian 8.4

**Description of the problem including expected versus actual behavior**:
Field security field in Kibana's new Security tab is autocompleting with document types rather than document fields.

**Steps to reproduce**:
 1. Open Kibana and navigate to the Security tab
 2. Then go to the Role menu and attempt to create a new role
 3. You will first have to fill in the "Add an index" field with your index
 4. Then proceed to click on the "Add a field" field and you'll notice it recommend recommend some things. Those recommendations are suppose to be Document fields but you will be given Document types.

**Comment by clintongormley** [comment]
Hi @CCoffie 

Thanks for reporting.  This fix will be in alpha4
