### ISSUE TITLE
X-Pack Alpha 3 - Security Web UI 

### ISSUE THREAD

**Issue by CCoffie** [elastic/elasticsearch#19015]
**Elasticsearch version**: 5.0.0-alpha3

**OS version**: Debian 8.4

**Description of the problem including expected versus actual behavior**:
I submitted a bug earlier today about the Web UI for Role Management and I have since found more bugs with the same menu. When creating new roles if you type something into the query field and then delete it and save the role. The role get created with an empty query field rather than no query field. This can cause problems when the role is assigned. I also noticed the "field" field has similar problems even if you don't select it.

**Comment by lukasolson** [comment]
This will be fixed in alpha4. Thanks!
