### ISSUE TITLE
need to save same field in different type and field have different data type.

### ISSUE THREAD

**Issue by kingaj** [elastic/elasticsearch#19017]
in elasticsearch 1.7.3 have no issue when i created one index have two type and have same filed in in type with different data type 

but this is not work in 2.3.1 it fire number format exception.

like example 

PUT indexname1/type1/1
{
    "id":1
}

then i created second type in same index

PUT indexname1/type2/1
{
    "id":"v1"
}

then it fire error number format but it work 1.7.3 version

**Comment by kingaj** [comment]
please help

**Comment by cbuescher** [comment]
Please read [this article](https://www.elastic.co/blog/great-mapping-refactoring) about the reasons why this behaviour changed. Also, please use the forums at https://discuss.elastic.co/ for questions like this in the future since elasticsearch reserves Github for bug reports and feature requests.

**Comment by kingaj** [comment]
so many time i try to open https://discuss.elastic.co/  but it cant open
