### ISSUE TITLE
Remove the support for `fielddata_fields`

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#19027]
The parameter `fielddata_fields` is deprecated (https://github.com/elastic/elasticsearch/issues/18943) but we continue to fallback to the fielddata cache when the docvalues are not enabled on the field. 
We should remove the ability to retrieve the fields through the fielddata cache because the output is not equivalent to the docvalue and may greatly differ from the stored field.

**Comment by rashidkpc** [comment]
Note that Kibana makes use of fielddata_fields for retrieving the millisecond value of date fields in documents. Is there an alternative for that purpose?

**Comment by rashidkpc** [comment]
I guess `docvalue_fields`? Is that going to break on old indices that don't have docvalues? Is there a way to have a transparent fallback here?

**Comment by clintongormley** [comment]
> I guess docvalue_fields? Is that going to break on old indices that don't have docvalues? Is there a way to have a transparent fallback here?

We need to fallback to fielddata for 5.x, can be removed in 6.0

**Comment by jimferenczi** [comment]
discussed in FixItFriday, the fallback to fielddata for 5.x is only for keyword/text fields. It won't work if the field is numeric since the fielddata for numerics has been removed entirely. 

> Note that Kibana makes use of fielddata_fields for retrieving the millisecond value of date fields in documents. Is there an alternative for that purpose?

You'll have to ensure that the doc_values are activated on the field otherwise it won't work. This is a side effect of the fielddata removal for numeric fields. Note that this has nothing to do with this issue, this is how the 5.x works and this is not going to change.

**Comment by clintongormley** [comment]
Fielddata for numeric fields were deprecated in 2.0 and removed in 5.0, so doc values would be enabled for any numeric field in an index created in 2.x, unless the user changed the mappings.

So we're good to remove fielddata_fields, and kibana will need to change their use of fielddata_fields to `docvalue_fields`

**Comment by colings86** [comment]
`fielddata_fields` were [deprecated in 5.0](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/breaking_50_search_changes.html) so can be removed in 6.0

**Comment by jimczi** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/25537
