### ISSUE TITLE
Refresh interval -1 still makes docs searchable

### ISSUE THREAD

**Issue by marcinkubica** [elastic/elasticsearch#19021]
Elastics 2.3.3

```refresh_interval: -1 ``` makes docs searchable after some period (possibly cluster default value)

also ```refresh_interval: -1s``` not helping

.

docs: https://www.elastic.co/guide/en/elasticsearch/guide/2.x/near-real-time.html#refresh-api and in few other places in docs

**Comment by clintongormley** [comment]
@marcinkubica segments will be written when the indexing buffer needs to be cleared.  There is a PR which is being discussed about whether we can change this behaviour.

Closing in favour of https://github.com/elastic/elasticsearch/pull/16028
