### ISSUE TITLE
Specific JSON key ordering causes search query failure

### ISSUE THREAD

**Issue by nanotone** [elastic/elasticsearch#19034]
**Elasticsearch version**:

5.0.0~alpha3

**JVM version**:

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**OS version**:

Linux ip-10-10-155-146 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
Create an index with two mappings in a parent/child relationship. e.g.
```bash
$ curl -XPUT 'http://localhost:9200/foo/' -d '{"settings":{"number_of_shards":1},"mappings":{"blog":{"properties":{"name":{"type":"keyword"}}},"tag":{"_parent":{"type":"blog"},"properties":{"name":{"type":"keyword"}}}}}'
{"acknowledged":true}
```

Make this search query, with the `query` key preceding the `has_child` key in the `should` clause.
```bash
$ curl 'http://localhost:9200/foo/_search' -d '{"query":{"bool":{"should":{"query":{"query_string":{"query":"go"}},"has_child":{"query":{"query_string":{"query":"go"}},"child_type":"tag"}}}}}'
{"error":{"root_cause":[{"type":"parsing_exception","reason":"no [query] registered for [query]","line":1,"col":37}],"type":"parsing_exception","reason":"no [query] registered for [query]","line":1,"col":37},"status":400}
```

But switching the key order makes it work. According to http://json.org/ this serialization represents the exact same object as before.
```bash
$ curl 'http://localhost:9200/foo/_search' -d '{"query":{"bool":{"should":{"has_child":{"query":{"query_string":{"query":"go"}},"child_type":"tag"},"query":{"query_string":{"query":"go"}}}}}}'
{"took":102,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}
```

**Provide logs (if relevant)**:
No logs appear to be generated for the error.

**Comment by clintongormley** [comment]
Hi @nanotone 

Thanks for trying out the alpha and for reporting this bug. The bug isn't what you think: the `query` query no longer exists, so it is actually the SECOND query which isn't failing correctly.

**Comment by cbuescher** [comment]
To reformulate the problem slightly, when querying something like:
```
GET /foo/_search
{
  "query": {
    "bool": {
      "must": {       
        "unknown_query" : {
          "match": {
            "fuz": "buzz"
          }
        }
      }
    }
  }
}
```
we correctly get the error stated above: `"type": "parsing_exception",  "reason": "no [query] registered for [unknown_query]"`, but if we add a valid query before the invalid one, like the following, we don't get an error:
```
GET /foo/_search
{
  "query": {
    "bool": {
      "must": {
        "match": {
            "fizz": "bizz"
        },
        "unknown_query" : 
        {
          "match": {
            "fuz": "buzz"
          }
        }
      }
    }
  }
}
```

**Comment by cbuescher** [comment]
@clintongormley shouldn't more than one query clauses be specified as an array, or is `"must" : { "query1" : { ... }, "query2" : { ... } }` supported? Because if it is, I think that's whats not working.

**Comment by clintongormley** [comment]
@cbuescher yes absolutely right, so it's just ignoring whatever is left in that object
