### ISSUE TITLE
_cat/nodes api does not return anything for certain nodes 

### ISSUE THREAD

**Issue by skshandilya** [elastic/elasticsearch#19039]
_cat/nodes?v&h=n,l,rc,m
n                        l     rc m 
es-data-13-internal   0.26   31gb - 
es-master-02-internal 0.07 10.8gb m 
es-data-05-internal   0.15 31.1gb - 
es-client-02-internal 0.00 17.6gb - 
es-data-11-internal   0.63 30.2gb - 
es-client-01-internal             - 
es-master-01-internal 0.00 10.8gb \* 
es-data-02-internal   0.44 29.8gb - 
es-data-06-internal   0.63 30.8gb -
**Elasticsearch version**:
1.7.5
**JVM version**:
1.8.0._51
**OS version**:
centos 6.6

This is happening for any random node in the cluster.

**Comment by javanna** [comment]
How many client nodes do you have in your cluster? Which node do you hit with your REST request?

**Comment by skshandilya** [comment]
we have 2 client nodes which are frontended by a haproxy, so no idea which one it hit
I did the same query on client 1 but then client 2 show no stats

**Comment by skshandilya** [comment]
We have also seen the same behavior on some data nodes too and at the same time we have seen some exceptions in log messages

**Comment by javanna** [comment]
that is what I thought. whenever you hit one of the client nodes, you cannot get data from the other client node in the cluster. This is the same problem as #16815, fixed in elasticsearch 5.0.0-alpha1 .

**Comment by javanna** [comment]
@skshandilya I am not sure the exception you find in the logs is related to calling `_cat/nodes`, that smells like another problem to me. Can you post a full recreation of that problem with data nodes?

**Comment by skshandilya** [comment]
Unfortunately that would be difficult we have seen this on a cluster that is processing data, I will update this issue when I see it again.
When this happens the cluster is green and we see no other issues except that our cron job which monitors es using _cat/nodes sees this and alerts. The only way this got fixed is by rebooting the node.
What about the client info not showing up?

**Comment by javanna** [comment]
> What about the client info not showing up?

As I said before, this is the same problem as #16815, fixed in elasticsearch 5.0.0-alpha1 .

**Comment by colings86** [comment]
No further feedback so closing for now
