### ISSUE TITLE
_optimize API results in increased disk usage

### ISSUE THREAD

**Issue by mkelkarbv** [elastic/elasticsearch#19049]
**Elasticsearch version**: 1.7.3

**JVM version**:  openjdk version "1.8.0_65"
OpenJDK Runtime Environment (build 1.8.0_65-b17)
OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)

**OS version**: Amazon linux 3.14.35-28.38.amzn1.x86_64 

**Description of the problem including expected versus actual behavior**:

Using _optimize API results in increased disk usage, It used to reduce disk usage in ES 1.3.9.

**Steps to reproduce**:

Before optimize -

```
green open &part-cvreview6         6 2  6949511  3745  64.4gb  21.1gb 
green open &part-prrreview3        6 2 10322051  4917 128.5gb  44.9gb 
green open &part-prrcontributor3   6 2 24509019  2664  48.2gb  16.1gb 
green open &part-cvanswer1         6 2  1493576   425   9.2gb     3gb 
green open &part-prrstory0         6 2   357212     1   3.7gb   1.2gb
```

after doing `curl -XPOST 'http://localhost:9200/_optimize?max_num_segments=1'`

```
green open &part-cvreview6         6 2  6949511 0  91.3gb  30.4gb 
green open &part-prrreview3        6 2 10322051 0 158.4gb  52.8gb 
green open &part-prrcontributor3   6 2 24509019 0  51.5gb  17.1gb
green open &part-cvanswer1         6 2  1493576 0   9.5gb   3.1gb 
green open &part-prrstory0         6 2   357212 0   4.1gb   1.3gb
```

Larger indices are worst affected..

**Comment by jpountz** [comment]
This is expected to happen if you have sparse fields in your index. This means that you could probably save a fair amount of disk space - even before optimizing - by modeling your documents a bit differently in order to avoir sparse fields.

**Comment by mkelkarbv** [comment]
@jpountz Can you explain that a bit more? what do you mean by "sparse fields" ?

**Comment by jpountz** [comment]
The current design of Lucene makes it inefficient with fields that only exist in a minority of documents, especially when doc values or norms are enabled on those fields. Typically if only 1% of your documents have a value for field foo, the disk usage for this field will not be the space required for a single value times the number of docs that have a value, but times the total number of documents in the index.

Sometimes this can be addresses by merging two fields together, sometimes by splitting unrelated data into their own indices, etc.

**Comment by mkelkarbv** [comment]
@jpountz thank you for the explanation!

**Comment by mkelkarbv** [comment]
@jpountz one last thing. Has this functionality changed between lucene 4.9.1 to 4.10.4?

**Comment by jpountz** [comment]
It does not seem so.
