### ISSUE TITLE
Simple Query String boolean operators are not simple

### ISSUE THREAD

**Issue by dsem** [elastic/elasticsearch#19053]
**Describe the feature**:

The boolean operators `AND`, `OR`, and `NOT` are not simple, as they can act on the term to the left or the right in an often non-obvious manner, [as stated in the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_boolean_operators).

The `+`, `|`, and `-` operators are much more clear, just as flexible, and all-around simpler.

The `simple_query_string` query language accepts only `+`s, `|`s, and `-`s as boolean operators, and although they look like pluses, pipes, and minuses, [they act like `AND`s, `OR`s, and `NOT`s](https://discuss.elastic.co/t/behavior-of-in-simple-query-strings-vs-query-strings/53823/2)!

This is very unexpected behavior. Pluses, pipes, and minuses should act the same in `query_string` and `simple_query_string` queries.  At the very least, the documentation should clearly state (or better, _emphasize_) that the pluses in query string act as `AND`s, and not pluses.

**Comment by clintongormley** [comment]
What part of the syntax documentation do you find unclear?

https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-simple-query-string-query.html#_simple_query_string_syntax

**Comment by dsem** [comment]
When I read, "`+` signifies AND operation," I am not totally convinced that `+` means AND because

* Maybe "AND operation" is a way to describe how the `+` behaves on the `query_string` language too.
* Why would `+` behave differently in the two types of query languages?
* If this is a simple query language, I would be more inclined to believe it uses the simpler boolean operators of `+`, `|`, and `-` (if these can be called boolean operators)

**Comment by clintongormley** [comment]
@dsem feel free to submit a PR to improve the explanation

**Comment by colings86** [comment]
No further feedback
