### ISSUE TITLE
Failed to start the kibana service in Windows 8 64 bit

### ISSUE THREAD

**Issue by vinothn44** [elastic/elasticsearch#19059]
Elasticsearch 2.3.3

Installed Java : JDK - 8u91

Windows 8 X64

I have set the environment variables as below  to initialize the installation process of elastic search 

JAVA_HOME -> C:\Program Files\Java\jdk1.8.0_91

Then installed the elastic search using command prompt using admin mode with a command service install -> successfully installed

Then tried to start the service using the command -> service start after that getting issue like 

failed to start failed starting 'elasticsearch-service-x64' service 

Could you please let me know the cause  of the issue and troubble shooting steps. 

Thanks in advance

Regards
Vinoth

**Comment by jasontedor** [comment]
We would need more details to be able to help you find the cause. For example, there are service logs that would be helpful to see here. However, Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions. I suggest requesting help there if looking at those logs does not help you track down the cause.

**Comment by vinothn44** [comment]
please find the attached screen shot error thrown in the event viewer.

![kibana](https://cloud.githubusercontent.com/assets/20125262/16334387/3b87bfce-3a1e-11e6-8bec-76c122e3172a.PNG)
