### ISSUE TITLE
How to use elasticsearch 2.3.1 in java.

### ISSUE THREAD

**Issue by zonglinyue** [elastic/elasticsearch#19056]
I  want to update elasticsearch from 1.4.1 to 2.3.1.but when i use it only find Elasticsearch is unshaded from 2.0 onwards .and need to some third party dependencies like Guava and Joda?
I‘m a newbie,please some one tell me how to use elasticsearch 2.3.1 in java 1.7.and  where I can find the right version dependencies jars.

**Comment by dadoonet** [comment]
Please ask questions like this on discuss.elastic.co.

BTW you could read [this](https://www.elastic.co/blog/to-shade-or-not-to-shade) if needed.

**Comment by zonglinyue** [comment]
I've read this page before，and try to update pom.xml then "mvn package",but failture and still don't understand how to do.
Thank you anyway. @dadoonet
