### ISSUE TITLE
Remove uses of `ExceptionHelper.detailedMessage`

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#19069]
This method tries to summarize an exception in a single string. But the entire point of the structured exception work was to get real stack traces. This method just hurts, and does not help. For example, if you have a `NullPointerException`, nothing will help except for the stack trace, but detailedMessage will only emit the exception name.  We should remove all uses of this (there are over 50 right now).

**Comment by jpountz** [comment]
+1 this annoyed me multiple times already

**Comment by rmuir** [comment]
> This method just hurts, and does not help.

Then lets rename it to `ExceptionsHurter`, and deprecate it to at least stop the bleeding. Otherwise the task will get bigger over time.

**Comment by rjernst** [comment]
> deprecate it to at least stop the bleeding

Done in #19160
