### ISSUE TITLE
when i use pattern with analyzer then fire agggrigation query then it split data 

### ISSUE THREAD

**Issue by kingaj** [elastic/elasticsearch#19060]
my index
----------
PUT /whatever
{
  "settings": {
    "analysis": {
        "filter" : {
            "code" : {
               "type" : "pattern_capture",
               "preserve_original" : 1,
               "patterns" :"[\\w\\s\\/]+"
            }
         },
   "analyzer" : {
            "code" : {
               "tokenizer" : "pattern",
               "filter" : [ "code", "lowercase" ]
            }
         }

    }
  },
  "mappings": {
    "type": {
      "properties": {
        "name": {
          "type": "string",
          "analyzer": "code"
        }
      }
    }
  }
}

insert record
---------------
PUT whatever/d/1
{
    
    "name":"Ajay Rathod"
}

i fire query 
--------------
GET whatever/_search
{
 
    "query": {
        "query_string": {

           "query": "name:Ajay"
           
        }
    },
    "aggs":
    {
        "demo1":{
            "terms":{
                "field":"name"
            }
        }
    }
        
}

result
---------

{
   "took": 3,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 0.19178301,
      "hits": [
         {
            "_index": "whatever",
            "_type": "d",
            "_id": "1",
            "_score": 0.19178301,
            "_source": {
               "name": "Ajay Rathod"
            }
         }
      ]
   },
   "aggregations": {
      "demo1": {
         "doc_count_error_upper_bound": 0,
         "sum_other_doc_count": 0,
         "buckets": [
            {
               "key": "ajay",
               "doc_count": 1
            },
            {
               "key": "rathod",
               "doc_count": 1
            }
         ]
      }
   }
}

it split my name with space

**Comment by kingaj** [comment]
please help im stuck with long time

**Comment by dadoonet** [comment]
Please ask questions on discuss.elastic.co instead.
We can help you there.
