### ISSUE TITLE
Java API MultiGet does not provide high level source filtering and field inclusion per the REST API

### ISSUE THREAD

**Issue by arciisine** [elastic/elasticsearch#19064]
**Describe the feature**:
The links below are for ES 1.7, but the request also applies to 2.3.

Per the [Multi Get REST documentation](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/docs-multi-get.html#mget-source-filtering) top level source filtering and field inclusion are supported.  

Parity is missing between the MultiGet Java API and the MultiGet REST API.

**Comment by dadoonet** [comment]
Are you looking for something like the following?

```java
client.prepareGet("index", "type", "id").setFetchSource("include", "exclude").get()
```

I agree that it's not super obvious but I think this is what you are looking for.

**Comment by arciisine** [comment]
I'm looking fore
```java
client.prepareMget("index", null, ids).setFetchSource("include", "exclude").get()
```

Which is not supported by the Java API, but is supported by the Rest API

**Comment by dadoonet** [comment]
This? 

```java
        client.prepareMultiGet().add(new MultiGetRequest.Item("index", "type", "id").fetchSourceContext(new FetchSourceContext("include", "exclude"))).get();
```

**Comment by arciisine** [comment]
Yeah, I found that, and ended up doing this:

```java
        List<String> idsToFind = ...
        String[] includes = ...
        String[] excludes = ...

        if (includes != null || excludes != null) {
            for (String id : idsToFind) {
                MultiGetRequest.Item item = new MultiGetRequest.Item(index, null, id)
                if (includes != null) {
                    item.fetchSourceContext().includes(includes)
                }
                if (excludes != null) {
                    item.fetchSourceContext().excludes(excludes)
                }
                builder.add(item);
            }
        } else {
            builder.add(index, null, idsToFind)
        }
```

This doesn't seem to match the high level source filtering indicated in the REST API, but it does work.

**Comment by arciisine** [comment]
I updated the bug to be specifically about the high level source/field management versus the inability to actually do that work. 

I'm not sure if there is a performance difference between adding it on a per item basis or adding it to the entire request.

**Comment by dadoonet** [comment]
Behind the scene we are doing the exact same thing:

```java
    public MultiGetRequestBuilder add(String index, @Nullable String type, Iterable<String> ids) {
        for (String id : ids) {
            request.add(index, type, id);
        }
        return this;
    }
```

And 

```java
    public MultiGetRequest add(String index, @Nullable String type, String id) {
        items.add(new Item(index, type, id));
        return this;
    }
```

I don't know what will be the plan with the new REST Client but for the TransportClient (or NodeClient) I don't think we need to add this as we can always do it as you wrote, which ends up with the same data structure in memory.

**Comment by arciisine** [comment]
I'm less concerned about the Java API and more concerned about how the high level filtering works via the REST API.  I'm wondering if it can do something more efficient on the Elasticsearch side if I can declare a consistent set of include/exclude versus a per document configuration.

**Comment by s1monw** [comment]
@arciisine I am confused, you want a default exclude/include for all GET requests on the REST API, right? I really wonder if we should do this since where would you stop if you start adding these APIs? I would rather keep these API clean and don't overload anything except of index and type?

**Comment by arciisine** [comment]
@s1monw This is primarily looking for parity with the REST api which does provide the high level include/exclude.  The reasoning behind the request is not one of convenience (though that does hold some merit), but one of potential performance.  I do not know how the REST API interprets the high level include/exclude.  If all it does is convert the high level include/exclude into item specific includes/excludes then there is nothing to gain (apart from ease of use). 

The Java API docs seem to indicate that it subsumes everything from the REST API, and the REST API docs indicate:

> You can also use the url parameters _source,_source_include & _source_exclude to specify defaults, which will be used when there are no per-document instructions.

**Comment by clintongormley** [comment]
It is for convenience only, and won't benefit performance so i think we're good to close this one.
