### ISSUE TITLE
How to enable Slow Logs for Suggest query ?

### ISSUE THREAD

**Issue by ishara** [elastic/elasticsearch#19084]
**Elasticsearch version**:Any

**Describe the feature**: I want to enable Slow Logs logging for _suggest query. I have already enable index.search.slowlog.* logs , I can see only search logs.

Is there any way to log _suggest query ?

**Comment by clintongormley** [comment]
Currently there isn't a way to do this

**Comment by ishara** [comment]
No luck , _suggest query not log.

**Comment by s1monw** [comment]
this is fixed in 5.0 since we are going through the search phase with suggestions too.
