### ISSUE TITLE
How to make cache available for index which is bulk indexing data

### ISSUE THREAD

**Issue by 9zdata** [elastic/elasticsearch#19087]
How to make cache available for index which is bulk indexing data.

I use es in logging scenario, the alerts need to query es every 10 seconds, but no cache hits event if I set 
 curl -XPUT 'localhost:9200/es_index_logrouter60_2016-06-17/_settings' -d'{ "index.cache.query.enable": true}'

Could anyone help me?

**Comment by nik9000** [comment]
This is a question best asked on `discuss.elastic.co`. We try to keep github for bugs and features.
