### ISSUE TITLE
Elastic Search node using the complete swap.

### ISSUE THREAD

**Issue by ravitandur** [elastic/elasticsearch#19081]
**Elasticsearch version**: 1.7

**JVM version**: 1.7.0_45-b18

**OS version**: Linux 2.6.18-406.el5 #1 SMP Wed Jun 3 05:51:45 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

I am running 5 nodes ES cluster. Each node is having 16GB RAM and 8 CPUs.
Xms configured 8GB.
No other processes are running on these nodes.
Number of documents per day 300 million
Total documents in cluster : 3 billion
After few days, when I check the swap usage, it is getting used completely.
I am not able to find out the root cause why swap is getting used?
Can you please let me know what is causing swap usage on my ES nodes?
If you need anyf urther information to debug this issue, please let me know.

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by ravitandur** [comment]
free -m
             total       used       free     shared    buffers     cached
Mem:         15922      15518        404          0         46       6489
-/+ buffers/cache:       8981       6941
Swap:         2047       **2036**         10

**Comment by jasontedor** [comment]
For some background on Elasticsearch, and swapping, please see my [comments](https://github.com/elastic/elasticsearch/issues/17605#issuecomment-207149090) on #17065. If you have follow-up questions, please open a topic on the [Elastic Discourse forum](https://discuss.elastic.co) as Elastic reserves GitHub for bug reports and feature requests.
