### ISSUE TITLE
Bulk update with script / upsert broken in 1.7.5 with different JSON key order

### ISSUE THREAD

**Issue by andrewvc** [elastic/elasticsearch#19103]
If, in the JSON object of a bulk update with scripted upsert the keys "upsert" and "scripted_upsert" do not appear as the first keys the whole thing fails. 

This is ONLY in 1.x. This works in 2.x and 5.x

This works

``````
POST /test/type/_bulk
{"update":{"_id":"5","_retry_on_conflict":1}}
{"upsert":{},"scripted_upsert":true,"script":{"script":"ctx._source['@timestamp'] = event['@timestamp']; ctx._source['@version'] = event['@version']","params":{"event":{"@timestamp":"2016-06-24T22:35:46.992Z","@version":"1","message":"sample message here"}}}}```
``````

This does not

```
POST /test/type/_bulk
{"update":{"_id":"5","_retry_on_conflict":1}}
{"script":{"script":"ctx._source['@timestamp'] = event['@timestamp']; ctx._source['@version'] = event['@version']","params":{"event":{"@timestamp":"2016-06-24T22:35:46.992Z","@version":"1","message":"sample message here"}}},"upsert":{},"scripted_upsert":true}
```

Thanks to @pickypg for pinning down the source of this which seems to be [here in UpdateHelper.java](https://github.com/elastic/elasticsearch/blob/v1.7.5/src/main/java/org/elasticsearch/action/update/UpdateHelper.java#L83)

**Comment by dakrone** [comment]
Closing this as we no longer are working on the 1.x branches and they are far past the EOL cycle.
