### ISSUE TITLE
Release code(v2.3.3) complie Error:Failed to execute goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.3.2:junit4 

### ISSUE THREAD

**Issue by wenpos** [elastic/elasticsearch#19117]
**Elasticsearch version**:release code(v2.3.3)

**JVM version**:1.8.0_60

**OS version**: 32~14.04.1-Ubuntu

**Description of the problem including expected versus actual behavior**:
yes, I download the release code(v2.3.3)  and put it on an CI environment. When execute the command 'mvn test',  most of the test suites failed, most of whose log turn out to be "Throwable #1: java.lang.NoClassDefFoundError: org.elasticsearch.test.ESTestCase". Detail information is as follows:

**Steps to reproduce**:
 1.mvn install
 2.mvn clean test

**Provide logs (if relevant)**:
part of the log:
Suite: org.elasticsearch.test.rest.test.TestSectionParserTests
ERROR   0.00s J0 | TestSectionParserTests.initializationError <<<
   > Throwable #1: java.lang.NoClassDefFoundError: org.elasticsearch.test.ESTestCase
   > 	at java.lang.Class.getDeclaredMethods0(Native Method)
   > 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
   > 	at java.lang.Class.getDeclaredMethods(Class.java:1975)
   > 	at com.carrotsearch.randomizedtesting.ClassModel$3.members(ClassModel.java:215)
   > 	at com.carrotsearch.randomizedtesting.ClassModel$3.members(ClassModel.java:212)
   > 	at com.carrotsearch.randomizedtesting.ClassModel$ModelBuilder.build(ClassModel.java:85)
   > 	at com.carrotsearch.randomizedtesting.ClassModel.methodsModel(ClassModel.java:212)
   > 	at com.carrotsearch.randomizedtesting.ClassModel.<init>(ClassModel.java:207)
   > 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
Completed [554/558 (549!)] on J0 in 0.00s, 1 test, 1 error <<< FAILURES!

part of the log:
[ERROR] Failed to execute goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.3.2:junit4 (tests) on project elasticsearch: There were test failures: 558 suites, 583 tests, 7 suite-level errors, 546 errors [seed: 9A962C70CAEC565A] -> [Help 1]

**Comment by dadoonet** [comment]
When does this fail? When you execute the first command or the second one?

**Comment by dadoonet** [comment]
I tried this on my laptop on 2.3.3 tag:

```sh
mvn clean install
```

And everything is fine.

You probably have an error in your setup.

**Comment by wenpos** [comment]
thank you, what do you mean my setup?

**Comment by dadoonet** [comment]
I meant your "CI environment".

**Comment by wenpos** [comment]
thank you, I'll have a look
