### ISSUE TITLE
Insertion Bulk data not work. 

### ISSUE THREAD

**Issue by gutasaputra** [elastic/elasticsearch#19113]
Hi all, 
so basically im trying new things. this time with elastic search.
i already install elastic and kibana, and sense plugin of course.
i try all basic command like create index, mapping, adding document etc.
everything goes well until i try bulk insertion.

```
POST /ecommerce/product/_bulk
{"index":{"_id":"1002"}}
{"name":"SWA magazine", "price":"90.000", "description":"swa magazine description",
"status":"active", "quantity":3, "categories":[{"name":"magazine"}], 
"tags":["business", "magazine", "sales", "news"]}
{"index":{"_id":"1003"}}
{"name":"SWA magazine", "price":"90.000", "description":"swa magazine description",
"status":"active", "quantity":3, "categories":[{"name":"magazine"}], 
"tags":["business", "magazine", "sales", "news"]}
```

i dont even know what is wrong with my code.
i always got this error :  

![error bulk elastic](https://cloud.githubusercontent.com/assets/1556126/16406725/0b1504ea-3d3a-11e6-91d2-3eabf66b8dc2.png)

pls help me to fix this out.
many thanks in advance.

**Comment by spinscale** [comment]
Please use the [forum](http://discuss.elastic.co/) for this kind of questions.

you need ensure, that there are no new lines in your JSON body of the document you are trying to index. bulk indexing is very picky about this. See the [bulk API docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html)

**Comment by clintongormley** [comment]
You can't have new lines in your bulk body.  In Sense you can just use Auto Indent to format it as follows:

    POST /ecommerce/product/_bulk
    {"index":{"_id":"1002"}}
    {"name":"SWA magazine","price":"90.000","description":"swa magazine description","status":"active","quantity":3,"categories":[{"name":"magazine"}],"tags":["business","magazine","sales","news"]}
    {"index":{"_id":"1003"}}
    {"name":"SWA magazine","price":"90.000","description":"swa magazine description","status":"active","quantity":3,"categories":[{"name":"magazine"}],"tags":["business","magazine","sales","news"]}
