### ISSUE TITLE
mvn test throws errors like this 'NoClassDefFoundError org.elasticsearch.test.ESTestCase'

### ISSUE THREAD

**Issue by wenpos** [elastic/elasticsearch#19115]
Suite: org.elasticsearch.common.lucene.uid.VersionsTests
ERROR   0.00s J0 | VersionsTests.initializationError <<<
   > Throwable #1: java.lang.NoClassDefFoundError: org.elasticsearch.test.ESTestCase
   > 	at java.lang.Class.getDeclaredMethods0(Native Method)
   > 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
   > 	at java.lang.Class.getDeclaredMethods(Class.java:1975)
   > 	at com.carrotsearch.randomizedtesting.ClassModel$3.members(ClassModel.java:215)
   > 	at com.carrotsearch.randomizedtesting.ClassModel$3.members(ClassModel.java:212)
   > 	at com.carrotsearch.randomizedtesting.ClassModel$ModelBuilder.build(ClassModel.java:85)
   > 	at com.carrotsearch.randomizedtesting.ClassModel.methodsModel(ClassModel.java:212)
   > 	at com.carrotsearch.randomizedtesting.ClassModel.<init>(ClassModel.java:207)
   > 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
Completed [10/558 (10!)] on J0 in 0.00s, 1 test, 1 error <<< FAILURES!

**Comment by cbuescher** [comment]
Please ask questions like this in our forum discuss.elastic.co. When opening a question there it would help to know more about what you are trying to achieve, what your setup ist (are you running from command line or from ide etc...
