### ISSUE TITLE
Valid IPs giving "not a valid ip address" error

### ISSUE THREAD

**Issue by esamudio** [elastic/elasticsearch#19124]
**Elasticsearch version**:  2.3.3

**JVM version**: 1.8.0_91

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:

@jpountz I think I might have found a problem as a result of the quick fix from [issue #18740](https://github.com/elastic/elasticsearch/issues/18740). It doesn't give me the "Mixing up field types" error anymore but it tells me that the IPs are not valid:

**Provide logs (if relevant)**:
`source[{"@version":"1","@timestamp":"2016-06-27T21:16:52.085Z","domain_name":"2667500489.MARS.ORDERBOX-DNS.COM.","type":"A","ip_address":"162.251.82.124,162.251.82.125,162.251.82.252,162.251.82.253","domain_name_exact":"2667500489.MARS.ORDERBOX-DNS.COM.","domain_name_length":33,"ip_address_exact":"162.251.82.124,162.251.82.125,162.251.82.252,162.251.82.253","domain_name_segmented":["2667500489mars","order","box","dns"],"last_registered":"2016-05-01T10:00:00.000-0500"}]} MapperParsingException[failed to parse [ip_address]]; nested: IllegalArgumentException[failed to parse ip [162.251.82.124,162.251.82.125,162.251.82.252,162.251.82.253], not a valid ip address]; at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:329) at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:309) at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:436) at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:262) at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:122) at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309) at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:580) at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:559) at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:212) at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:224) at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:326) at org.elasticsearch.action.bulk.TransportShardBulkAction.shardUpdateOperation(TransportShardBulkAction.java:389) at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:191) at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:68) at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639) at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279) at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271) at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75) at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376) at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.IllegalArgumentException: failed to parse ip [162.251.82.124,162.251.82.125,162.251.82.252,162.251.82.253], not a valid ip address at org.elasticsearch.index.mapper.ip.IpFieldMapper.ipToLong(IpFieldMapper.java:84) at org.elasticsearch.index.mapper.ip.IpFieldMapper.innerParseCreateField(IpFieldMapper.java:351) at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:241) at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:321) ... 23 more
`
Here's the mapping:

```
{
    "settings": {
        "number_of_shards": {{ num_shards }},
        "number_of_replicas": 2,
        "index":{
            "analysis":{
               "analyzer":{
                  "keylower":{
                     "tokenizer":"keyword",
                     "filter":"lowercase"
                  }
               }
            }
        }
    },
    "mappings": {
        "_default_": {
            "properties": {
                "ip_address":{
                    "type":"ip"
                }
            }
        },
        "NS": {
            "properties": {
                "domain_name": {
                    "type": "string",
                    "index": "analyzed",
                    "analyzer":"keylower"
                },
                "domain_name_exact": {
                    "type": "string",
                    "index":"not_analyzed"
                },
                "domain_name_length": {
                    "type": "integer"
                },
                "type": {
                    "type": "string",
                    "index": "not_analyzed"
                },
                "is_registered": {
                    "type": "boolean"
                },
                "last_registered": {
                    "type":   "date"
                },
                "last_deregistered": {
                    "type":   "date"
                },
                "registered_history": {
                    "type":   "date"
                },
                "deregistered_history": {
                    "type":   "date"
                },
                "name_servers": {
                    "type": "string",
                    "index": "analyzed"
                },
                "name_servers_exact": {
                    "type": "string",
                    "index":"not_analyzed"
                },
                "past_name_servers": {
                    "type": "string",
                    "index": "analyzed"
                },
                "past_name_servers_exact": {
                    "type": "string",
                    "index":"not_analyzed"
                },
                "domain_name_segmented": {
                    "type": "string",
                    "index": "not_analyzed"
                },
                "domain_name_exact_pronounceability": {
                    "type": "integer"
                },
                "domain_name_segmented_pronounceability": {
                    "type": "integer"
                }
            }
        },
        "A": {
            "properties": {
                "domain_name": {
                    "type": "string",
                    "index": "analyzed",
                    "analyzer":"keylower"
                },
                "domain_name_exact": {
                    "type": "string",
                    "index":"not_analyzed"
                },
                "domain_name_length": {
                    "type": "integer"
                },
                "type": {
                    "type": "string",
                    "index": "not_analyzed"
                },
                "ip_address": {
                    "type": "ip"
                },
                "ip_address_exact": {
                    "type": "string",
                    "index": "not_analyzed"
                }
            }
        }
    }
}
```

I'm not sure if this is unrelated but I've exhausted the docs and discussion at this point. I'm dealing with 20 shards(also 20 nodes), 2 replicas, 16GB of ram(8GB to heap), mlockall set to true, ran "sudo swapoff -a" on all the machines and still have problems with the GB not doing its job and nodes becoming unresponsive. Looking at the logs, I was getting errors like the one above before the GC warnings appeared, can they be related?

**Comment by colings86** [comment]
`162.251.82.124,162.251.82.125,162.251.82.252,162.251.82.253` is not a valid ip address. If you are trying to assign multiple IP addresses to the `ip_address` field, you must provide them as an array of values such as:

```
{
    "ip_address": [ "162.251.82.124" , "162.251.82.125" , "162.251.82.252" , "162.251.82.253" ]
}
```

**Comment by esamudio** [comment]
I should have made this clearer. I have the document in elasticsearch already and that happens when I perform an update call to insert a completely unrelated field.

**Comment by jpountz** [comment]
Can you provide us with a simple recreation of the issue so that we can look into it?

**Comment by esamudio** [comment]
I think I finally understood where the issue originates but I'm not sure of how to easily replicate it. I'm not familiar enough with github issues to know if I can move this one or if I have to duplicate it because it seems to be a logstash problem. The elasticsearch plugin in logstash seems to be the cause of the problem. Whenever I insert or update anything using "action => update" in logstash, the IPs give problems. This is a new document being indexed with logstash using update. Below is an excerpt of the logstash log:

`{:timestamp=>"2016-06-28T02:48:01.215000+0000", :message=>"Failed action. ", :status=>400, :action=>["update", {:_id=>"2667500489.MARS.ORDERBOX-DNS.COM.", :_index=>"full", :_type=>"A", :_routing=>nil, :_retry_on_conflict=>1}, #<LogStash::Event:0x3b5cf2c6 @metadata_accessors=#<LogStash::Util::Accessors:0x4053d7b9 @store={}, @lut={}>, @cancelled=false, @data={"@version"=>"1", "@timestamp"=>"2016-06-28T02:47:08.358Z", "zone"=>"com", "sign"=>"+", "domain_name"=>"2667500489.MARS.ORDERBOX-DNS.COM.", "type"=>"A", "ip_address"=>["162.251.82.124", "162.251.82.125", "162.251.82.252", "162.251.82.253"], "domain_name_exact"=>"2667500489.MARS.ORDERBOX-DNS.COM.", "domain_name_length"=>33, "is_registered"=>true, "last_registered"=>"2016-05-01T10:00:00.000-0500", "registered_history"=>["2016-05-01T10:00:00.000-0500"], "deregistered_history"=>[], "ip_address_exact"=>["162.251.82.124", "162.251.82.125", "162.251.82.252", "162.251.82.253"]}, @metadata={}, ...[omitted for brevity]... :response=>{"update"=>{"_index"=>"full", "_type"=>"A", "_id"=>"2667500489.MARS.ORDERBOX-DNS.COM.", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [ip_address]", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"failed to parse ip [162.251.82.124,162.251.82.125,162.251.82.252,162.251.82.253], not a valid ip address"}}}}, :level=>:warn}`

**Comment by jpountz** [comment]
I don't think Github has any workflow to move issue, so you'd have to open another one on the logstash repo: https://github.com/elastic/logstash. I am closing this one in the meantime.

**Comment by esamudio** [comment]
Thanks! I really appreciate the effort and quick response you guys have whenever an issue is opened
