### ISSUE TITLE
[reference doc update request]concurrent update

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#19120]
let's assume concurrent update operation is A, B
    let's assume each shard has one replica, then P and R stands for primary and R stands for replica
    let's assume update operation without specifying version and therefore use internal versiont type

so it could happen different things:
1. P execute A, B, R execute A, B
2. P execute A, B, R execute B, A
3. P execute A, B, R execute only A, B has failed on R due to version conflict
4. P execute only A and B failed due to version conflit. R execute A

all of the above has the possibility to happen, right?
if so, better update this part into reference doc and let users to get it well.

**Comment by jasontedor** [comment]
This should be a topic on the [Elastic Discourse forum](https://discuss.elastic.co), which I see you already [opened](https://discuss.elastic.co/t/es-concurrent-update-question/54136). We appreciate your active involvement in the community, but it would be helpful if you followed the repository guidelines (in the issue template) and also did not double post.

**Comment by clintongormley** [comment]
You'll find it all clearly documented here: https://www.elastic.co/guide/en/elasticsearch/guide/current/_partial_updates_to_a_document.html

**Comment by makeyang** [comment]
@clintongormley clear enough. thanks.
