### ISSUE TITLE
Roadmap for Elasticsearch 5 release candidate?

### ISSUE THREAD

**Issue by phathvu** [elastic/elasticsearch#19139]
The latest version of ES is [elasticsearch-5-0-0-alpha3](https://github.com/elastic/elasticsearch/releases/tag/v5.0.0-alpha3)

Doese someone know about roadmap for Elasticsearch 5 release candidate?
Thank you.

**Comment by dadoonet** [comment]
Please ask questions on discuss.elastic.co.

You will probably find an already answered question there BTW.

**Comment by satterly** [comment]
See https://discuss.elastic.co/t/elastic-5-0-0-release-date/61382
