### ISSUE TITLE
Deprecate discovery-azure and rename it to discovery-azure-classic

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#19144]
As discussed at https://github.com/elastic/elasticsearch-cloud-azure/issues/91#issuecomment-229113595, we know that the current `discovery-azure` plugin only works with Azure Classic VMs / Services (which is somehow Legacy now).

The proposal here is to rename `discovery-azure` to `discovery-azure-classic` in case some users are using it.
And deprecate it for 5.0. 

Note that the renaming already happened from 2.x to 5.0 because we split `cloud-azure` in 2 plugins:

* `discovery-azure`
* `repository-azure`

We can then work on a new `discovery-azure-arm` plugin if there is a need.

Another option could be to provide classic and ARM in the same `discovery-azure` plugin but this will mean that we will depend on multiple Azure SDK jars. Read https://github.com/Azure/azure-sdk-for-java/wiki/Azure-SDK-for-Java-Features
But I don't think we should do it as it could potentially lead us to some JAR conflicts.

**Comment by Mpdreamz** [comment]
Would definitely prefer a clean split so we can easily phase out `discovery-azure-classic` when at such it time it makes sense to do so.
