### ISSUE TITLE
Add support for Azure Resource Manager (ARM)

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#19146]
As explained in #19144 we could create a new plugin named `discovery-azure-arm` which is based on the [newest versions of the Azure SDK](https://github.com/Azure/azure-sdk-for-java/wiki/Azure-SDK-for-Java-Features).

Classic was based on private key / password which was bad for what we want to achieve with such a plugin.
ARM uses now key / secrets which are really much more flexible and safer.

Basically you can now write code like [this example](https://github.com/Azure/azure-sdk-for-java/wiki/Getting-Started#client-creation):

``` java
ComputeManagementClient client;

// Default environment, no credentials
client = new ComputeManagementClientImpl();

// Custom environment with AzureChinaCloud endpoint
String chinaCloudEndpoint = "https://management.chinacloudapi.cn/";
client = new ComputeManagementClientImpl(chinaCloudEndpoint);

// Default environment with credentials
ApplicationTokenCredentials credentials = new ApplicationTokenCredentials(
        "client-id", "tenant-id", "secret", null);
client = new ComputeManagementClientImpl(credentials);

// Custom environment with credentials
client = new ComputeManagementClientImpl(chinaCloudEndpoint, credentials);

// Fully customized, with HTTP client and Retrofit modifiable
client = new ComputeManagementClientImpl(
        chinaCloudEndpoint,
        credentials,
        new OkHttpClient.Builder(),
        new Retrofit.Builder());
```

**Comment by jpountz** [comment]
Looks like we should do it. @dadoonet is there anything to discuss here (it has the `discuss` label)?

**Comment by aslanbekirov** [comment]
@dadoonet It seems that  you already started working on it. Is there a planned date for release?

**Comment by dadoonet** [comment]
No date sorry. I just can tell that this will happen only with 5.0 series or later. So won't be available for 2.x series.

**Comment by aslanbekirov** [comment]
We would like to contribute, can you publish the branch that you are working on,so we may continue with that?

**Comment by ejsmith** [comment]
Will this support using an Azure Scale Sets to discover member nodes?

**Comment by justinbarias** [comment]
Hello, any update on this piece of work? Or at least a placeholder plugin for the "azure-discovery-arm" plugin?

**Comment by JamieCressey** [comment]
+1 for this plugin

**Comment by synhershko** [comment]
@dadoonet what is the status of this? was this released and can be used with 5.x? Classic plugin has a deprecated warning but no ARM plugin seems to be available at this point?

**Comment by dadoonet** [comment]
@synhershko I made some progress recently on this at #22679.
Not ready yet. My plan is to have something ready for 6.x series.

In the meantime, if you want to use azure discovery you still need to use the classic version of the plugin even though it's deprecated.

**Comment by synhershko** [comment]
Problem is its useless if you use ARM for your deployment. Any chance this
can be backported (and finished soon :) ) ?

**Comment by dadoonet** [comment]
I don't think it will be ever backported when finished.

**Comment by ywelsch** [comment]
We had an internal discussion on this and, while generally useful, think that we currently cannot take this one on, in particular give it the proper testing, support and maintenance that we provide for the other plugins in the ES repo. This might be a better fit as a community plugin for now. As a clear indication that we're not going to work on this in the foreseeable future, I'm closing this issue.
