### ISSUE TITLE
Combine query with completion suggester

### ISSUE THREAD

**Issue by jeremyb** [elastic/elasticsearch#19143]
**Elasticsearch version**: 2.3.3

**JVM version**: 1.8.0_91

**OS version**: Ubuntu 16.04

**Description of the problem including expected versus actual behavior**:

Hi, I'm trying to combine query with completion suggester. I made an example available on found.no:
https://www.found.no/play/gist/667e4d974fe0f0045e5c0b5e44e47b06

Basically I would like to filter completion suggester by some criteria (like organization tenancy, etc.). 
I saw that a context extension is available on completion query.

I would like to know if it's a bug or if completion suggester doesn't take in account query, filter, post_filter, etc.? Should we use context to filter suggestions?

I tried on different versions, especially Elasticsearch 2.3.3.

**Steps to reproduce**:
https://www.found.no/play/gist/667e4d974fe0f0045e5c0b5e44e47b06

**Comment by clintongormley** [comment]
Hi @jeremyb 

The completion suggester uses a completely separate mechanism from search, and so can't be combined with queries.  This is documented.

**Comment by jeremyb** [comment]
Thanks for your reply @clintongormley. I suspected something like this.

IMHO the fact that "completion suggester uses a completely separate mechanism from search" is not very clear in the documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html. And the first example with a mix of query and suggest can be confusing.

**Comment by squinker** [comment]
Yes, I made the same mistake here, it could really use a bit of highlighting.

**Comment by Lane565** [comment]
any alternative solution？
I have recently encountered a similar problem
