### ISSUE TITLE
Scripts should be stored in QueryShardContext

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#19161]
Currently the apis for compiling scripts take the ClusterState to support stored scripts. This is going away in #19136 since most users of the ScriptService should not need to know or care about where the script comes from, it should be an impl detail of the ScriptService. The one place that needs this api is doing a search scroll. There, the QueryShardContext keeps the cluster state at the time the scroll was created. However, a simpler approach is to have the context keep any scripts it uses. This should be fairly simple as it appears from a cursory glance that anywhere in a search request that accesses a script peeks into the ScriptService of the query shard context. Instead, a wrapper method can be used that will cache the script in the context.

**Comment by rjernst** [comment]
Also note that this should solve the same problem with file scripts, which could currently be changed during a scroll. With this they will be cached like any other script in the context.

**Comment by jdconrad** [comment]
@rjernst Is this still relevant?

**Comment by rjernst** [comment]
Yes, I think it is still relevant. I'm marking as adoptme.

**Comment by rjernst** [comment]
In the years since I opened this issue, I haven't heard of anyone actually running into this. To be clear, it is an edge case that could only happen if using a stored script, and changing that script in the middle of a scroll query. Given the seemingly low chance of this happening, I'm closing this as the way to fix it is much more complex than I originally anticipated, and currently not worth the maintenance overhead.

**Comment by stu-elastic** [comment]
@rjernst closing, reopen if still relevant.
