### ISSUE TITLE
Get all parents if ALL/NONE of children match

### ISSUE THREAD

**Issue by jondeandres** [elastic/elasticsearch#19166]
Hi, I'm not sure I can do this with ES:

Having a parent doc_type A and children doc_type B. Is there a way to query "all the A documents where NONE/ALL of their Bs children match some filters"?

Having:

- A1
  - B1.foo = 200
  - B2.foo = 100
- A2
  - B3. foo = 100

I tried with the query below, but with this I get A1 since one of their children doesn't have `foo: 100`.
```json
{
  "query": {
    "has_child": {
      "type": "b",
      "query": {
        "filtered": {
          "filter": {
            "bool": {
              "must_not": { "term": { "foo": 100 }}
            }
          }
        }
      }
    }
  }
}
```

In summary, can we get parents for those which *all*/*none* of their children match the given filters?

**Comment by clintongormley** [comment]
Not in any efficient way.  You have to count all children and compare that to how many children match.  The following will return all parents where all children match but it is a horrible inefficient solution and I would never recommend using it in practice:


    PUT t 
    {
      "mappings": {
        "parent": {},
        "child": {
          "_parent": {
            "type": "parent"
          }
        }
      }
    }
    
    PUT t/parent/1
    {}
    
    PUT t/parent/2
    {}
    
    PUT t/parent/3
    {}
    
    PUT t/child/3?parent=1
    {
      "tag": "foo"
    }
    
    PUT t/child/4?parent=1
    {
      "tag": "bar"
    }
    
    PUT t/child/5?parent=1
    {
      "tag": "bar"
    }
    
    PUT t/child/6?parent=2
    {
      "tag": "foo"
    }
    
    PUT t/child/7?parent=3
    {
      "tag": "bar"
    }
    
    
    
    GET t/parent/_search
    {
      "query": {
        "has_child": {
          "type": "child",
          "score_mode": "sum",
          "query": {
            "function_score": {
              "query": {
                "match_all": {}
              },
              "functions": [
                {
                  "weight": -1
                },
                {
                  "filter": {
                    "match": {
                      "tag": "foo"
                    }
                  },
                  "weight": 1
                }
              ],
              "score_mode": "sum",
              "boost_mode": "replace"
            }
          }
        }
      },
      "min_score": 0
    }

**Comment by jondeandres** [comment]
Thanks @clintongormley for the response! We'll see what we can do.
