### ISSUE TITLE
Resolve scripts on coordinating node

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#19162]
While #19161 will help with search scroll requests having consistent scripts through the life of a scroll, an issue still exists where stored scripts can be updated an a search request could execute different versions depending on the order/quickness that shards get updated cluster state.

One possible solution is to do the script resolution on the coordinating node, so that the same scripts are passed along to each shard. A caveat to this is figuring out how to do this without opening up a path to sidestepping the controls on script execution for inline vs stored vs file scripts (ie, rewriting to an inline script would not work).

**Comment by jdconrad** [comment]
@rjernst Is this still relevant?

**Comment by rjernst** [comment]
I think this is still relevant, especially now that file scripts are gone, and we no longer have per script type permissions. I'm marking as adoptme.

**Comment by stu-elastic** [comment]
We can resolve the script on the coordinator.

If we can assume transport is secure then we don't have to worry about this strategy by passing the "no-inline-scripts" setting.  Otherwise, we'd need to validate that the script used to exist under that stored name.

We should check with the security team to validate.

**Comment by stu-elastic** [comment]
Options:
1) Serialize script on coordinator and pass that along with request.
Pro: Simple
Con: May dramatically increase size of request

2) Hash script and pass hash, reject if stored script on node has different hash.
Con: Will fail requests that succeeded before.  Must resolve script has when parsing query.

3) Version scripts and pass version, keep old scripts around and use old version if possible.  
Pro: Smooth behavior for clients.
Con: Complex.  This would require updating scripts to use a consensus protocol.  We'd have to prepare the new script everywhere, then commit it.

4) Return the script hash used from each shard, use this info on coordinating node to alert for inconsistent results
Pro: Easy to bring back for queries.
Con: Tricky to do on handle bulk.

Do we need stored scripts at all?

**Comment by stu-elastic** [comment]
Next step:
* Send email to es@ re: do we need stored scripts at all?

**Comment by stu-elastic** [comment]
Conclusion from email, we need stored scripts.

**Comment by stu-elastic** [comment]
Summary: Add warning box about inconsistent results if a stored script update co-occurs with a query.

**Comment by stu-elastic** [comment]
Adding a warning to docs for this rare a problem is too noisy.
