### ISSUE TITLE
[feature request]add a key "description" when create a index

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#19173]
**Describe the feature**:
currently when u create a index, u can specify num of shards, num of replicas and mapping. 
I'd like suggest that we can add a key called "description" which is used to add some comments when create index and it is used this way:

curl -XPUT 'http://localhost:9200/twitter/' -d '{
    "description" : "this is book info index etc"
}'

**Comment by bleskes** [comment]
have you considered using the meta field: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-meta-field.html ? It's not exactly what you ask as it is per type and not per index, but it might get you what you need.

**Comment by makeyang** [comment]
it could be used. thanks

**Comment by s1monw** [comment]
there seems to be a solution - if it won't work please reopen thanks @bleskes
