### ISSUE TITLE
Not Able to Upload File in ElasticSearch through REST API using AngularJS

### ISSUE THREAD

**Issue by SushantVarshney** [elastic/elasticsearch#19171]
I want to insert data in ElasticSearch through it's REST API through AngularJS but it's giving error:
` Malformed Data must start with an object ` when sending through POST

And when sending through PUT it's showing error:
`Http  Put doesn't allow Preflight Response`

**My code in controller is:**

```
 var f =document.getElementById('file')
		   angular.forEach(f.files,function(file,index){
		      console.log(file.name +" RECEIVED")

		      var createIndexUrl='http://'+$rootScope.elasticSearch.url+':9200/'+$rootScope.elasticSearch.indexName+'/'+$rootScope.elasticSearch.typeName+'/'+$rootScope.elasticSearch.id+'?pretty'
		      r = new FileReader();
		      r.readAsArrayBuffer(file);
		      r.onloadend = function(e){
		          var data = e.target.result;
		          var jsonData=JSON.stringify(data)
		       console.log(createIndexUrl);
		          
		          
		       
		    	  /* $http.put(createIndexUrl,data,{headers: {'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',"Access-Control-Allow-Methods" : "POST, GET, PUT, DELETE, OPTIONS"}})*/
		          $http.put(createIndexUrl,data,{headers: {'Content-Type': undefined}})
		    	   .success(function(data) {
		    	   
		    	   console.log("SUCCESSFULL "+data)
		       }).error(function(data) {
		        console.log("ERROR "+data);
		       });
		        }
		     });
		 };
```

**On Html Page:**
` <input type="file" id="file" multiple>`

**Comment by clintongormley** [comment]
It sounds like you need to configure `http.cors.allow-methods` and maybe some other CORS parameters:
https://www.elastic.co/guide/en/elasticsearch/reference/2.3/modules-http.html#_settings_2

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
