### ISSUE TITLE
Not able to install plugin. 

### ISSUE THREAD

**Issue by vinay992002** [elastic/elasticsearch#19179]
**Elasticsearch version**:

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by cbuescher** [comment]
Closing since there is no context information about any potential bug here. If you want to ask general questions about using Elasticsearch please use the forum at https://discuss.elastic.co/.
