### ISSUE TITLE
How to free  up space once you encounter: ][INFO ][cluster.routing.allocation.decider] [usdrst05] low disk watermark [15%] exceeded on [9KjGeluVg][usdnrst05] free: 146.4gb[14.5%], replicas will not be assigned to this node

### ISSUE THREAD

**Issue by choll33** [elastic/elasticsearch#19181]
How do you reclaim space once you encounter 

][INFO ][cluster.routing.allocation.decider] [usdrst05] low disk watermark [15%] exceeded on [9KjGelExXuVg][usdrst05] free: 146.4gb[14.5%], replicas will not be assigned to this node

  1008G  811G  147G  85% /elasticsearch/data

On all my other nodes the indices take up the following:

@usnst03:/elasticsearch/data/prod/nodes/0/indices$ du -sh 
99G     report_us3e_v2
@usnrst03:/elasticsearch/data/prod/nodes/0/indices$ du -sh 
322G    report_us3_v2
@usnrst03:/elasticsearch/data/prod/nodes/0/indices$ du -sh 
41G     report_log_us3e_v2
@usnrst03:/elasticsearch/data/prod/nodes/0/indices$

On this node the indicies space is as follows:

@usnst05:/elasticsearch/data/prod/nodes/0/indices# du -sh 
629G    report__us3_v2
root@usnres05:/elasticsearch/data/prod_us_nres/nodes/0/indices# du -sh 
53G     report_us3e_v2
root@usnres05:/elasticsearch/data/prod_us_nres/nodes/0/indices# du -sh 
130G    report_us3e_v2

I was able to stop and start the service to get things back to allocating however how do I free up space ?

**Comment by jasontedor** [comment]
Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions.
