### ISSUE TITLE
 Add ranking evaluation API to Elasticsearch

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#19195]
This relates to #18798.

This effort tries to help downstream users figure out whether the ranking function they are using produces good enough search result rankings.

To validate our API does the right thing we focus on annotation based quality metrics only (Prec@, MRR, ERR, see also https://en.wikipedia.org/wiki/Mean_reciprocal_rank and https://en.wikipedia.org/wiki/Learning_to_rank#Evaluation_measures).

The API takes a set of queries, each with a set of search results, and their relevance wrt. to the query. We focus on binary, maybe graded relevancy for now, it's explicitly not a goal to have very generic ratings per result.

For simplicity reasons those evaluation datasets will be supplied at query time instead of being stored and accessible in a dedicated index. Supporting to resume quality computations is something we decided to care about once users start asking for it.

What we leave to the user:
- Logging queries. We assume that what most users want to do with that API is to figure out how well their mapping from user supplied query and all sorts of additional information works for ranking search results. As a result logging plain elastic search queries isn't very helpful. What might be helpful is logging query parameters, like e.g. in template requests. We keep that in mind as future work.
- Creating annotations. This step is left to the downstream user, who need to figure out how to assign some quality level to search results given a query. It's also left to the downstream user to build a query annotation UI.

As a second step we envision enabling users to automatically learn which weights to assign to query parameters.

As a third step we envision downstream users being able to monitor their ranking quality over time. This involves building a QA specific UI that helps talk to the API outlined above, maybe integrating watcher for constant monitoring.

**Comment by MaineC** [comment]
As a bit of real world validation of the above suggestion here's what Erik Bernhardson from Wikimedia, thanks @nik9000 for the introduction, told us about how Wikimedia's search team is doing ranking QA:

> Real world data sets are a bit hard. We do collect a reasonable (0.5%) amount of click through 
> and dwell time data from which to try and derive SAT (satisfied) clicks. Unfortunately the 
> individual queries are considered [PII](https://en.wikipedia.org/wiki/Personally_identifiable_information) which means the data isn't able to be shared publicly. 
> This data gets fed into our [relevance forge](https://github.com/wikimedia/wikimedia-discovery-relevanceforge) software, currently we use a calculation nominally 
> called the [Paul Score](https://github.com/wikimedia/wikimedia-discovery-relevanceForge/blob/master/engineScore.py#L176-L208
) after [Paul Nelson from Search Technologies](https://www.elastic.co/elasticon/conf/2016/sf/engine-scoring-and-predictive-analytics-to-boost-search-accuracy) that presented the idea at 
> elasticon.

> The basic concept is to take all queries and clicks from a user session and consider any click to 
> be a vote for all queries in that session. A form of DCG is then calculated per-session based on 
> this, and all the session scores are averaged together. This is a very basic method of handling 
> query reformulation, along with not over weighting heavy users. It is somewhat useful, but has a 
> very heavy preference for links that already show up in the top of the search rankings. For us we 
> already see ~85% of clicks are to the top 3 [results](https://phabricator.wikimedia.org/T126522#2027738), so it's really only optimizing for the other 
> 15% of clicks. We haven't started using this with autocomplete but it might be more useful there 
> as there are more reformulations to work with.

> The only thing i could offer up is the results from our labeling platform ([discernatron](https://discernatron.wmflabs.org/), [see also](https://github.com/wikimedia/wikimedia-discovery-discernatron) In 
> Discernatron results sourced from our own engine, google, bing and duck duck go are labeled on 
> a 4 point scale by human graders. This is a brand new platform that has very minimal usage so 
> the data set is currently too small to be much use to anyone. The queries used here have been 
> hand filtered to remove PII (10 to 20% of queries end up getting filtered) so are possible to be 
> released as a public dataset. Sadly it only has ~70 sets of scores against 32 unique queries as of 
> today. We are still iterating on the code behind the labeling platform before really pushing for it's 
> usage. If the data might be interesting a relatively recent TSV export is [available](https://phabricator.wikimedia.org/P3255), but i doubt 
> it's enough for you to do much. Once we get a reasonable amount of data here we will be using it 
> for nDCG calculations in relevance forge, and possibly other algorithms (Yandex's [pFound](http://romip.ru/romip2009/15_yandex.pdf) is 
> an interesting algo i've been looking at recently). In our ideal world we would be getting around 
> 500 new queries graded this way every month, but we are a ways away from that reality.

> I don't know if you are aware, but the presenter from NY Times at elasticon spent about 5 
> minutes of his presentation [complaining that elastic didn't currently have anything like this built in](https://www.elastic.co/elasticon/conf/2016/sf/all-the-data-thats-fit-to-find-search-at-the-new-york-times 
). 
> His name escapes me at the moment, but might be someone worth looking up and pinging as 
> well.




 What metrics are you currently using?

> Currently using Paul score and nDCG as mentioned. Considering pFound, but it's mostly an 
> nDCG reformulation using binary judgements (probably click throughs) that takes into account 
> how likely a user is to continue progressing down the search results. We will possibly find more 
> as we have time to look around and evaluate things. There are plenty of different ways to 
> generate a score, but most are quite similar to what we already calculate. Will have to figure out 
> what it is we want to measure that isn't covered by the above three. We've only done initial steps 
> with our relevance forge project so far, but we finally got some dedicated hardware to clone 
> elasticsearch indicies to and run it on. Will be using it more over the coming months as we 
> evaluate the change from tf/idf to bm25. If we come up with new requirements that lead us to 
> investigating more algo's I'll ping you.

 
Can I make our conversation public on github so it gets tracked with the rank evaluation ticket?

> No restrictions, it can all be replicated to the public issue.

> One thing that would be important, at least for us, is for any kind of API to not just take search 
> terms with a templated query, but entire generated queries. We have a decent bit of pre-
> processing that happens on user queries before they get sent off to elasticsearch. Mostly things 
> like custom boost's, but also special grammar, feature escaping (ex. we don't allow user specified 
> boosts with ^, or grouping with parens), etc. Perhaps not directly useful to you, but our raw 
> generated queries are available by attaching a cirrusDumpQuery query parameter to any [fulltext](https://en.wikipedia.org/wiki/Special:Search?search=morelike:California&fulltext=1&cirrusDumpQuery) 
> [search](https://en.wikipedia.org/wiki/Special:Search?search=elasticsearch&fulltext=1&cirrusDumpQuery).

**Comment by MaineC** [comment]
Keeping here for the record: After giving a talk on how to build personalisation features step by step starting with basic ES features last Thursday at BEDCon which included talks on how to evaluate search results there was quite some interest in this functionality from attendees. Was great being able to point them to the feature branch. Though unlikely it would be great to get some early feedback.

**Comment by softwaredoug** [comment]
I have a question, in part because I'm trying to figure out how a product of mine ([Quepid](http://quepid.com)) would use this API (or be replaced by this API, which is also fine).

My understanding is the following
- This feature logs query keyword strings (whatever is plugged in from a search template)
- This feature logs basically per-doc judgements or quality metrics, probably based on analytics. But also possibly based on manual human judgments.

Is it planned that I could use this feature to do test-driven relevancy? Let's say I want to tweak my query, analysis, (or really anything) and measure the impact. Will that be a supported feature? Can I reevaluate somehow by recomputing an NDCG score for a select subset of queries? Or would this need to be done externally somehow?

**Comment by MaineC** [comment]
Hi Doug,

thanks for getting into this conversation. As this API really is in the early stages we are very much looking for input on how to improve it and make it work better with software like Quepid.

> This feature logs query keyword strings (whatever is plugged in from a search template)

Logging is currently left to the user.

> This feature logs basically per-doc judgements or quality metrics, probably based on analytics. But also possibly based on manual human judgments.

In it's current stage we assume that the user of this API provides human judgments. Reading through the Quepid tour I would imagine that this is equal to the query ratings you collect from your users.

> Per query, I can have a historic sense of NDCG, MRR, and other classic relevance metrics

You'd execute a request against an Elasticsearch index that provides information on the queries to run for testing as well as the quality level of documents returned. As a result you'd get a relevance score. This would give you a sense of NDCG/MRR/etc. wrt. specific queries and documents that have been annotated. The way I would imagine someone to use this API would be to first execute the queries as they are against the index to get a sense of current NDCG/MRR/etc. Then change the queries executed (either by using another template but still the same parameters, or in a very simple setup generating new queries with existing parameters (semi-)automatically and re-executing these. Together with the quality level the API would give you a list of documents returned by your search queries that don't have any ratings yet so you can easily ship them off to manual inspection.

You can take a look at the current API request/response format here: https://github.com/elastic/elasticsearch/blob/feature/rank-eval/modules/rank-eval/src/main/java/org/elasticsearch/index/rankeval/RestRankEvalAction.java#L46

Hope this helps clear some confusion. Please don't hesitate to ask for further details. Also if you have any input on how to improve the API, on which other extensions would be helpful for you let us know. Would be great to receive feedback from you as soon as you start playing with this. If you want to get your hands dirty feel free to check out [our rank-eval module on the feature/rank-eval branch](https://github.com/elastic/elasticsearch/tree/feature/rank-eval/modules/rank-eval/src/main/java/org/elasticsearch/index/rankeval).

Again thanks for your feedback,
Isabel
