### ISSUE TITLE
Ingest: Skip Empty Pipelines

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#19192]
The idea here is to allow indexing to supply a _known_ pipeline that can be empty. If the pipeline is empty, then just skip it. That's it.

---------

For example:

```http
PUT /_ingest/pipeline/upgrade-my-api-2
{
  "description" : "Placeholder to upgrade from API v2 to current",
  "processors" : [ ]
}
```

While API v2 is the current version, the pipeline naturally does nothing, so the ingest pipeline should literally be skipped. But eventually, you can create an API v3, update the pipeline and then new indexing can be adjusted as needed (including index renames).

```http
PUT /my-index-2/type/123?pipeline=upgrade-my-api-2
{
  "field" : "blah"
}
```

After v3 rolls out, the pipeline is replaced with something like (and it could be further modified for v4 to allow v2 to v4, for as long as a version needs to survive):

```http
PUT /_ingest/pipeline/upgrade-my-api-2
{
  "description" : "Upgrade from API v2 to v3",
  "processors" : [
    {
      "rename": {
        "field": "field",
        "target_field": "another_name"
      }
    },
    {
      "set": {
        "field": "_index",
        "value": "my-index-3"
      }
    }
  ]
}
```

This enables secondary systems to be upgraded in a rolling fashion to enable temporary pipeline usage without any overhead burden while it's not needed.

**Comment by talevy** [comment]
@pickypg, I've opened a PR ^^ to implement this edge-case optimization. It is as minimal as it can be. Basically, it avoids the creation of the Map of Maps for the IngestDocument (which is probably the most costly thing). It does not avoid the Ingest Service, so index requests still get routed to ingest nodes and all that comes with that.

**Comment by clintongormley** [comment]
@talevy If the coordinating node has `node.ingest: true`, will ingest happen on that node, or will it be sent to some ingest node in round-robin fashion?  Just wondering if we should support a `pipeline_preference`  option, like we do for search.

**Comment by talevy** [comment]
@clintongormley iirc, ingest will happen on the coordinating node of the index request. This may or may not be the same as the coordinating node of a bulk request. So, I believe it tags along to whatever preference behavior the regular index request adopts
