### ISSUE TITLE
Registering plugin using an embedded client node

### ISSUE THREAD

**Issue by johnament** [elastic/elasticsearch#19197]
Hi, we're using the Java client API as an embedded node.  

```
final Settings settings = Settings.settingsBuilder()
                                          .put("plugin.types", DeleteByQueryPlugin.class.getName())
                                          .loadFromPath(findConfigFile())
                                          .build();
        this.node = nodeBuilder().settings(settings).node();
        this.node.start();
        this.client = node.client();
```

We notice that the plugin is never registered.  Is there a way to register the plugin?

**Comment by johnament** [comment]
I was able to work around by creating a custom node class to override it, but its odd that plugins aren't loaded in embedded without installing the standalone node

```
    private static class FlerpNode extends Node {

        public FlerpNode(Settings preparedSettings) {
            super(InternalSettingsPreparer.prepareEnvironment(preparedSettings, null), Version.CURRENT, asList(DeleteByQueryPlugin.class));
        }
    }
```

**Comment by jasontedor** [comment]
You did not post what version of Elasticsearch you're on, but `plugin.types` is no longer supported and the workaround that you're using is the only way to achieve your goal of using a plugin with an embedded node.

**Comment by johnament** [comment]
Sorry, this is ElasticSearch 2.3.3, latest GA.

Is this approach future proof?  It looks like for instance 5.0 removes the version param

https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/node/Node.java#L183

**Comment by jasontedor** [comment]
Maybe you mean something different by "future proof" than I'm understanding, but I think it's fair to say that nothing in the Java API is future proof, especially across major versions.

**Comment by johnament** [comment]
Ok.  So how do I get this in as a feature request, to register additional plugins via the embedded client?

**Comment by dadoonet** [comment]
You can start a local standard node instance with all plugins you need then use a TransportClient in your application.

**Comment by jasontedor** [comment]
> Ok. So how do I get this in as a feature request, to register additional plugins via the embedded client?

That would duplicate #15107 and #15927, which have been closed. You will see that the discussion there points you to the method that you discovered here.

**Comment by johnament** [comment]
Ok, thanks for linking to this tickets.  I think I understand a bit better.  Would be a good thing to consider switching then.
