### ISSUE TITLE
Is there an api to get stopwords used by an anlyzer

### ISSUE THREAD

**Issue by dzhang22** [elastic/elasticsearch#19203]
Say I'm using http://localhost:9200/_analyze?analyzer=indonesian as an analyzer. Is there an api that I can use to get all the Indonesian stopwords used by this analyzer? If it doesn't exist, can we add one?

**Elasticsearch version**:

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jpountz** [comment]
There is no generic API to get stop words across all ways that analyzers can be constructed, so I doubt we can have such an API. The default list of stop words for indonesian is here if you are interested https://github.com/apache/lucene-solr/blob/master/lucene/analysis/common/src/resources/org/apache/lucene/analysis/id/stopwords.txt
