### ISSUE TITLE
REST client is not released with the right groupId

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#19205]
Apparently we published the REST Client on maven central at https://repo1.maven.org/maven2/org/elasticsearch/rest/5.0.0-alpha4/

Which means that the artifact coordinates are `org.elasticsearch:rest:5.0.0-alpha4`.
But it should be `org.elasticsearch.client:rest:5.0.0-alpha4`.

**Comment by dadoonet** [comment]
Also reported at https://discuss.elastic.co/t/restclient-in-5-0-0-alpha4/54509

**Comment by javanna** [comment]
This is fixed in our gradle configuration, also the artifacts for 5.0.0-alpha4 were added in the proper locations and the groupId was updated in their corresponding poms.
