### ISSUE TITLE
Aggregate data and filtered values in elastic search error?

### ISSUE THREAD

**Issue by stefansaye** [elastic/elasticsearch#19209]
I need to filter a group of values based on date  (added field here) and term then  order by group count(*) asc

for sql is looks like ,
   
    select item,count(*) counts from table where date between '2014-07-01T00:00:00.000Z' and '2014-08-01T00:00:00.000Z' and user = "andy" group by item order by counts asc

So I am using the following thing :

 
    
     {
        "size": 0,
        "aggs": {
          "filtered_aggs": {
                   "filter": {
                        "range": {
                        "date": {
                            "gte": "2016-06-20T00:00:00.000Z",
                            "lte": "2016-06-26T00:00:00.000Z"
                                    }
                                },
                        "terms" : {   
                           "user": "andy"
                                  }

                 },
        "aggs": {
            "list": {
                     "terms": {
                           "field": "item",
                           "size": 0
                               }
                            }
                  }
              }
           }
      }

But seems like it's not correct. how should I correct it? 

Any help will be appreciated!

**Comment by clintongormley** [comment]
Hi @stefansaye 

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
