### ISSUE TITLE
Smoke Tester: Try to compile a plugin as part of tests

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#19213]
In order to test if the repository has been created correctly and dependencies are available, the smoke test should also try to build a plugin. Alternatively there does not need to be any sourcecode or elasticsearch plugin, but just a project that has a fair share of elasticsearch dependencies, so we make sure those are downloaded correctly.

Reasoning is to prevent something like #19205 in the future

**Comment by jasontedor** [comment]
We are going to address this as part of our internal release process. As such, this issue should be closed.
