### ISSUE TITLE
BulkProcessor doesn't commit the transaction log even if flush() is called

### ISSUE THREAD

**Issue by panfngsugar** [elastic/elasticsearch#19228]
**Elasticsearch version**: 2.3.3

**JVM version**: 1.8

**OS version**: Mac 10.10.5

**Description of the problem including expected versus actual behavior**:
Expecting the bulkProcessor to commit the transaction log when calling flush()
but that's not the case

**Steps to reproduce**:
run following test code:
1. create an index request 
2. add it to a bulk processor
3. flush the bulk processor
4. refresh the same index
5. an exception will be thrown saying the index could not be found
``` 
public class testBulkProcessor extends ESIntegTestCase {
    @Test
    public void testBulkProcessor(){
        BulkProcessor bulkProcessor =
                BulkProcessor.builder(client(), new BulkProcessor.Listener() {
                    @Override
                    public void beforeBulk(long executionId, BulkRequest request) {
                    }
                    @Override
                    public void afterBulk(long executionId, BulkRequest request,
                            BulkResponse response) {
                    }
                    @Override
                    public void afterBulk(long executionId, BulkRequest request,
                            Throwable failure) {
                    }
                }).setBulkActions(1000)
                        .setBulkSize(new ByteSizeValue(5, ByteSizeUnit.MB)).setConcurrentRequests(2)
                        .build();
        IndexRequest indexRequest = new IndexRequest("test", "test", "1");
        indexRequest.source(new HashMap());
        bulkProcessor.add(indexRequest);
        bulkProcessor.flush();
        client().admin().indices().prepareRefresh("test").get();
    }
}
```

**Provide logs (if relevant)**:
[test] IndexNotFoundException[no such index]
the exception is thrown at 
```
client().admin().indices().prepareRefresh("test").get();
```

**Comment by ywelsch** [comment]
This is not a bug, just a wrong usage of the API. By setting `setConcurrentRequests(2)` the bulk processor is executing `bulkProcessor.flush()` asynchronously. This means that the index "test" is not created yet while you call refresh on it. Either set `setConcurrentRequests(0)` or wait on the `afterBulk` event using the `BulkProcessor.Listener` before doing a refresh.

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.
