### ISSUE TITLE
Thread Context should collect unique response headers in async actions

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#19222]
The current implementation of the `ThreadContext` (#17804) works by having the context passed from thread-to-thread, and the last thread to write to it wins. In the case of async (e.g., scatter/gather) request/response schemes, this won't work if anything unique happens along the way.

This covers all current needs, but it could prove to be very useful to have it actually collect unique async response headers.

**Comment by ldematte** [comment]
We have mechanisms for handling it, and the issue appears to have been stale for long, closing
