### ISSUE TITLE
Unable to install Elasticsearch

### ISSUE THREAD

**Issue by muraliappiness** [elastic/elasticsearch#19229]
Hi,

I have followed all the instuctions given on this page: https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html

The last step mentioned results in a HttpError404: 
sudo apt-get update && sudo apt-get install elasticsearch

It is not able to find the packages mentioned in this link: https://packages.elastic.co/elasticsearch/2.3.1/debian/dists/stable/main/binary-amd64/Packages

below is the result of me running the installation command

sudo apt-get update && sudo apt-get install elasticsearchHit http://security.ubuntu.com trusty-security InRelease                       
Hit http://security.ubuntu.com trusty-security/main Sources                    
Hit http://security.ubuntu.com trusty-security/restricted Sources              
Hit http://security.ubuntu.com trusty-security/universe Sources                
Hit http://security.ubuntu.com trusty-security/multiverse Sources              
Hit http://security.ubuntu.com trusty-security/main amd64 Packages             
Hit http://security.ubuntu.com trusty-security/restricted amd64 Packages       
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages         
Hit http://security.ubuntu.com trusty-security/multiverse amd64 Packages       
Hit http://security.ubuntu.com trusty-security/main i386 Packages              
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages        
Hit http://security.ubuntu.com trusty-security/universe i386 Packages          
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages        
Hit http://security.ubuntu.com trusty-security/main Translation-en             
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en       
Hit http://security.ubuntu.com trusty-security/restricted Translation-en       
Hit http://security.ubuntu.com trusty-security/universe Translation-en         
Ign http://extras.ubuntu.com trusty InRelease                                  
Ign http://ppa.launchpad.net trusty InRelease                                  
Ign http://in.archive.ubuntu.com trusty InRelease                              
Ign http://ppa.launchpad.net trusty InRelease                                  
Hit http://in.archive.ubuntu.com trusty-updates InRelease                      
Hit http://ppa.launchpad.net trusty InRelease                                  
Hit http://in.archive.ubuntu.com trusty-backports InRelease                    
Get:1 http://extras.ubuntu.com trusty Release.gpg [72 B]                       
Ign http://ppa.launchpad.net trusty InRelease                                  
Hit http://extras.ubuntu.com trusty Release                                    
Hit http://ppa.launchpad.net trusty InRelease                                  
Hit http://extras.ubuntu.com trusty/main Sources                               
Hit http://extras.ubuntu.com trusty/main amd64 Packages                        
Hit http://ppa.launchpad.net trusty InRelease                                  
Hit http://extras.ubuntu.com trusty/main i386 Packages                         
Ign http://packages.elastic.co stable InRelease                                
Hit http://ppa.launchpad.net trusty Release.gpg                                
Hit http://ppa.launchpad.net trusty Release.gpg                                
Hit http://in.archive.ubuntu.com trusty Release.gpg                            
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://in.archive.ubuntu.com trusty-updates/main Sources                   
Get:2 https://packages.elastic.co stable InRelease                             
Ign https://packages.elastic.co stable InRelease                               
Ign https://packages.elastic.co stable InRelease                               
Hit http://in.archive.ubuntu.com trusty-updates/restricted Sources             
Hit http://packages.elastic.co stable Release.gpg                              
Ign https://packages.elastic.co stable Release.gpg                             
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://packages.elastic.co stable Release                                  
Ign https://packages.elastic.co stable Release.gpg                             
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://packages.elastic.co stable/main amd64 Packages                      
Ign https://packages.elastic.co stable Release                                 
Hit http://packages.elastic.co stable/main i386 Packages                       
Ign https://packages.elastic.co stable Release                                 
Hit http://ppa.launchpad.net trusty Release.gpg                                
Ign http://extras.ubuntu.com trusty/main Translation-en_IN                     
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Ign http://extras.ubuntu.com trusty/main Translation-en                        
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://in.archive.ubuntu.com trusty-updates/universe Sources               
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://in.archive.ubuntu.com trusty-updates/multiverse Sources             
Hit http://in.archive.ubuntu.com trusty-updates/main amd64 Packages            
Hit http://in.archive.ubuntu.com trusty-updates/restricted amd64 Packages      
Hit http://in.archive.ubuntu.com trusty-updates/universe amd64 Packages        
Hit http://in.archive.ubuntu.com trusty-updates/multiverse amd64 Packages      
Hit http://ppa.launchpad.net trusty Release                                    
Hit http://in.archive.ubuntu.com trusty-updates/main i386 Packages             
Hit http://ppa.launchpad.net trusty Release                                    
Hit http://ppa.launchpad.net trusty Release                                    
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://in.archive.ubuntu.com trusty-updates/restricted i386 Packages       
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://in.archive.ubuntu.com trusty-updates/universe i386 Packages         
Hit http://in.archive.ubuntu.com trusty-updates/multiverse i386 Packages       
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Ign http://packages.elastic.co stable/main Translation-en_IN                   
Hit http://in.archive.ubuntu.com trusty-updates/main Translation-en            
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://in.archive.ubuntu.com trusty-updates/multiverse Translation-en      
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Ign http://packages.elastic.co stable/main Translation-en                      
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://in.archive.ubuntu.com trusty-updates/restricted Translation-en      
Hit http://in.archive.ubuntu.com trusty-updates/universe Translation-en        
Hit http://in.archive.ubuntu.com trusty-backports/main Sources                 
Hit http://in.archive.ubuntu.com trusty-backports/restricted Sources           
Hit http://in.archive.ubuntu.com trusty-backports/universe Sources             
Hit http://in.archive.ubuntu.com trusty-backports/multiverse Sources           
Ign http://ppa.launchpad.net trusty/main Translation-en_IN                     
Hit http://in.archive.ubuntu.com trusty-backports/main amd64 Packages          
Hit http://in.archive.ubuntu.com trusty-backports/restricted amd64 Packages    
Ign http://ppa.launchpad.net trusty/main Translation-en                       
Hit http://in.archive.ubuntu.com trusty-backports/universe amd64 Packages      
Hit http://in.archive.ubuntu.com trusty-backports/multiverse amd64 Packages    
Hit http://in.archive.ubuntu.com trusty-backports/main i386 Packages           ^[[B
Hit http://in.archive.ubuntu.com trusty-backports/restricted i386 Packages     
Hit http://in.archive.ubuntu.com trusty-backports/universe i386 Packages       
Hit http://in.archive.ubuntu.com trusty-backports/multiverse i386 Packages     
Hit http://in.archive.ubuntu.com trusty-backports/main Translation-en          
Hit http://in.archive.ubuntu.com trusty-backports/multiverse Translation-en    
Hit http://in.archive.ubuntu.com trusty-backports/restricted Translation-en    
Hit http://in.archive.ubuntu.com trusty-backports/universe Translation-en      
Hit http://in.archive.ubuntu.com trusty Release                                
Ign http://dl.google.com stable InRelease                                      
Hit http://dl.google.com stable Release.gpg                                    
Hit http://dl.google.com stable Release                                        
Hit http://in.archive.ubuntu.com trusty/main Sources                           
Hit http://dl.google.com stable/main amd64 Packages                            
Hit http://in.archive.ubuntu.com trusty/restricted Sources                     
Hit http://in.archive.ubuntu.com trusty/universe Sources                       
Hit http://in.archive.ubuntu.com trusty/multiverse Sources                     
Hit http://in.archive.ubuntu.com trusty/main amd64 Packages                    
Hit http://in.archive.ubuntu.com trusty/restricted amd64 Packages              
Hit http://in.archive.ubuntu.com trusty/universe amd64 Packages                
Hit http://in.archive.ubuntu.com trusty/multiverse amd64 Packages              
Hit http://in.archive.ubuntu.com trusty/main i386 Packages                     
Err https://packages.elastic.co stable/main amd64 Packages                     
  HttpError404
Hit http://in.archive.ubuntu.com trusty/restricted i386 Packages               
Err https://packages.elastic.co stable/main i386 Packages                      
  HttpError404
Hit http://in.archive.ubuntu.com trusty/universe i386 Packages                 
Ign http://dl.google.com stable/main Translation-en_IN                         
Hit http://in.archive.ubuntu.com trusty/multiverse i386 Packages               
Ign https://packages.elastic.co stable/main Translation-en_IN                  
Ign http://dl.google.com stable/main Translation-en                
Ign https://packages.elastic.co stable/main Translation-en                     
Err https://packages.elastic.co stable/main amd64 Packages                     
  HttpError404
Err https://packages.elastic.co stable/main i386 Packages                      
  HttpError404
Ign https://packages.elastic.co stable/main Translation-en_IN                  
Hit http://in.archive.ubuntu.com trusty/main Translation-en                    
Ign https://packages.elastic.co stable/main Translation-en                     
Hit http://in.archive.ubuntu.com trusty/multiverse Translation-en              
Hit http://in.archive.ubuntu.com trusty/restricted Translation-en              
Hit http://in.archive.ubuntu.com trusty/universe Translation-en                
Ign http://in.archive.ubuntu.com trusty/main Translation-en_IN                 
Ign http://in.archive.ubuntu.com trusty/multiverse Translation-en_IN
Ign http://in.archive.ubuntu.com trusty/restricted Translation-en_IN
Ign http://in.archive.ubuntu.com trusty/universe Translation-en_IN
Fetched 72 B in 53s (1 B/s)
W: Failed to fetch https://packages.elastic.co/elasticsearch/2.3.1/debian/dists/stable/main/binary-amd64/Packages  HttpError404

W: Failed to fetch https://packages.elastic.co/elasticsearch/2.3.1/debian/dists/stable/main/binary-i386/Packages  HttpError404

W: Failed to fetch https://packages.elastic.co/elasticsearch/2.3/debian/dists/stable/main/binary-amd64/Packages  HttpError404

W: Failed to fetch https://packages.elastic.co/elasticsearch/2.3/debian/dists/stable/main/binary-i386/Packages  HttpError404

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by jasontedor** [comment]
I do not think that you literally followed the instructions on that page. I suspect that you replaced "2.x" by "2.3.1" and that is leading to the HTTP 404 status codes. For clarity, here are the *exact* commands that you need to execute:

```
$ wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
OK
$ echo "deb https://packages.elastic.co/elasticsearch/2.x/debian stable main" | sudo tee -a /etc/apt/sources.list.d/elasticsearch-2.x.list
deb https://packages.elastic.co/elasticsearch/2.x/debian stable main
vagrant@vagrant-ubuntu-trusty-64:~$ sudo apt-get update
Get:1 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
Get:2 http://security.ubuntu.com trusty-security/main Sources [117 kB]         
Ign http://archive.ubuntu.com trusty InRelease          
Get:3 https://packages.elastic.co stable InRelease                    
Ign https://packages.elastic.co stable InRelease                  
Get:4 http://security.ubuntu.com trusty-security/universe Sources [38.0 kB]
Get:5 https://packages.elastic.co stable Release                      
Get:6 http://security.ubuntu.com trusty-security/main amd64 Packages [501 kB]
Get:7 https://packages.elastic.co stable/main amd64 Packages
Get:8 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]            
Get:9 https://packages.elastic.co stable/main Translation-en_US     
Get:10 http://security.ubuntu.com trusty-security/universe amd64 Packages [130 kB]
Get:11 http://security.ubuntu.com trusty-security/main Translation-en [276 kB] 
Get:12 http://security.ubuntu.com trusty-security/universe Translation-en [77.1 kB]
Hit http://archive.ubuntu.com trusty Release.gpg                               
Get:13 http://archive.ubuntu.com trusty-updates/main Sources [277 kB]
Ign https://packages.elastic.co stable/main Translation-en_US    
Ign https://packages.elastic.co stable/main Translation-en
Get:14 http://archive.ubuntu.com trusty-updates/universe Sources [157 kB]
Get:15 http://archive.ubuntu.com trusty-updates/main amd64 Packages [788 kB]
Get:16 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [362 kB]
Get:17 http://archive.ubuntu.com trusty-updates/main Translation-en [396 kB]
Get:18 http://archive.ubuntu.com trusty-updates/universe Translation-en [190 kB]
Hit http://archive.ubuntu.com trusty Release                           
Get:19 http://archive.ubuntu.com trusty/main Sources [1,064 kB]
Get:20 http://archive.ubuntu.com trusty/universe Sources [6,399 kB]
Hit http://archive.ubuntu.com trusty/main amd64 Packages                       
Hit http://archive.ubuntu.com trusty/universe amd64 Packages                   
Hit http://archive.ubuntu.com trusty/main Translation-en                       
Hit http://archive.ubuntu.com trusty/universe Translation-en                   
Ign http://archive.ubuntu.com trusty/main Translation-en_US                    
Ign http://archive.ubuntu.com trusty/universe Translation-en_US                
Fetched 10.9 MB in 8s (1,222 kB/s)                                             
Reading package lists... Done
$ sudo apt-get install elasticsearch
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  elasticsearch
0 upgraded, 1 newly installed, 0 to remove and 189 not upgraded.
Need to get 27.4 MB of archives.
After this operation, 30.8 MB of additional disk space will be used.
Get:1 https://packages.elastic.co/elasticsearch/2.x/debian/ stable/main elasticsearch all 2.3.3 [27.4 MB]
Fetched 27.4 MB in 10s (2,692 kB/s)                                            
Selecting previously unselected package elasticsearch.
(Reading database ... 86712 files and directories currently installed.)
Preparing to unpack .../elasticsearch_2.3.3_all.deb ...
Creating elasticsearch group... OK
Creating elasticsearch user... OK
Unpacking elasticsearch (2.3.3) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up elasticsearch (2.3.3) ...
Processing triggers for ureadahead (0.100.0-16) ...
$
```

If you do need to install Elasticsearch 2.3.1, you can execute:

```
$ sudo apt-get install elasticsearch=2.3.1
```
