### ISSUE TITLE
Open file descriptors go up after increasing index.merge.policy.max_merged_segment

### ISSUE THREAD

**Issue by mkelkarbv** [elastic/elasticsearch#19224]
**Elasticsearch version**: 1.7.3

**JVM version**: openjdk version "1.8.0_65"
OpenJDK Runtime Environment (build 1.8.0_65-b17)
OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)

**OS version**: Amazon linux 3.14.35-28.38.amzn1.x86_64

**Description of the problem including expected versus actual behavior**:
We have multi gigabyte indices in our cluster, and we started noticing degraded performance over time ( our response times degraded by 20ms-40ms each month ). 

In many of these indices, several segments had about 3gb of data, and percentage of deleted documents was about 1%-2%. I thought the default max size limit of 5gb was possibly getting in the way of merging those segments, so I decided to increase it up to 15G, expecting ES to merge more and decrease segments. But when I increased the max size to 15gb, open file descriptor usage climbed up from 3.4k range to 3.8k-4k range, and degraded our response times. No new merges happened as a result of this change.

When the limit was set back to 2G, merges started happening and open file descriptor usage dropped. Further decreasing the limit to 1G had the same effect. 

**Steps to reproduce**:
1. increase  index.merge.policy.max_merged_segment to 15G. 
2. watch how file descriptor usage goes up...

**Provide logs (if relevant)**:   I could not find anything in the logs to explain the behavior.

**Comment by clintongormley** [comment]
> But when I increased the max size to 15gb, open file descriptor usage climbed up from 3.4k range to 3.8k-4k range, and degraded our response times. No new merges happened as a result of this change.

You say that no new merges happened, but how long did you wait? I think the most likely explanation is that it started to merge eg 5 x 3GB shards, which increased the open file handles and put a lot of IO load on the system (thus affecting response times), but perhaps you didn't let it complete?

**Comment by mkelkarbv** [comment]
@clintongormley I waited for an hour for merges to start, but there was no merge activity. the I/O also did not go up.

**Comment by clintongormley** [comment]
@mikemccand could you shed any light on this?

**Comment by mikemccand** [comment]
Increasing `max_merged_segment` will not cause merges to occur ... there must also be a set of 10 (by default) segments around that same size in order for a merge to be picked, and there must be too many segments in the shard so that a merge is needed.  If you enable `TRACE` logging for `org.elasticsearch.index.engine.lucene.iw` it will give (very verbose!) details about how merges are being selected.

However, this change should not have caused an increase nor decrease in file descriptors.

Were there any other changes done?  Open scroll requests?  Ongoing indexing?  New shards?

**Comment by mkelkarbv** [comment]
Indexing was happening all the time on this cluster. New shards were not being created.

**Comment by mkelkarbv** [comment]
is there a feedback on this? is there something we can tune?

**Comment by colings86** [comment]
@mkelkarbv are you still seeing this issue on recent releases on Elasticsearch?

**Comment by colings86** [comment]
No further feedback, closing
