### ISSUE TITLE
Can't map array of [lon, lat] 

### ISSUE THREAD

**Issue by nerotix** [elastic/elasticsearch#19233]
I'm trying to get Kibana to see my location info as a geo_point. I've been running about mapping and how to do it, but I can't seem to figure it out. The data looks like this in mongodb:

`{ "_id" : "3", "loc" : "[-122.0574, 37.41919999999999]", "fs" : "Clean", "name" : "www.googleapis.com", "timestamp" : "2016-07-02T21:02:53.623Z", "destination" : "192.168.79.136", "source" : "216.58.212.138", "vt" : "0" }`

I've tried the following:

```
curl -XPUT 'http://localhost:9200/yapdns/_mapping' -d '
    {
      "mappings": {
        "loc": {
          "properties": {
            "location": {
              "type": "geo_point"
            }
          }
        }
      }
    } '
```

But got this error: 
`{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: mapping type is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: mapping type is missing;"},"status":400}`

Then I tried:

```
curl -XPUT 'http://localhost:9200/yapdns/_mapping/loc' -d '
{
  "properties": {
    "loc": {
      "type": "geo_point"
    }
  }
}
```
and got this error:

`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"mapper [loc] cannot be changed from type [string] to [geo_point]"}],"type":"illegal_argument_exception","reason":"mapper [loc] cannot be changed from type [string] to [geo_point]"},"status":400}`

I'm with struggling with this issue for hours now..

How would I map the values that are stored in the key "loc" as geo_point?

**Comment by dadoonet** [comment]
Please ask this on discuss.elastic.co

Your mapping is incorrect. Field name is loc and not location IMO.
