### ISSUE TITLE
Field stats API gte/lt reversed?

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#19232]
[Here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-field-stats.html) we state;
>min_value - The lowest value in the field.
>max_value - The highest value in the field.

And then in [this example](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-field-stats.html#_field_stats_index_constraints) we have;
```
curl -XPOST "http://localhost:9200/_field_stats?level=indices" -d '{
   "fields" : ["answer_count"] 
   "index_constraints" : { 
      "creation_date" : { 
         "min_value" : { 
            "gte" : "2014-01-01T00:00:00.000Z"
         },
         "max_value" : {
            "lt" : "2015-01-01T00:00:00.000Z"
         }
      }
   }
}
```

But if you test it, it appears that the correct layout is actually in reverse when it comes to using `lt` and `gte`;
```
curl -XPOST "http://localhost:9200/_field_stats?level=indices" -d '{
   "fields" : ["answer_count"] 
   "index_constraints" : { 
      "creation_date" : { 
         "min_value" : { 
            "lt" : "2015-01-01T00:00:00.000Z"
         },
         "max_value" : {
            "gte" : "2014-01-01T00:00:00.000Z"
         }
      }
   }
}
```

Logically it seems that the second way is correct, but I didn't want to just make a PR without checking.

**Comment by jpountz** [comment]
This sounds correct to me too.

**Comment by markwalkom** [comment]
Any other feedback, this should be an easy fix.

**Comment by clintongormley** [comment]
Actually, the existing format is correct.  We're looking for indices where the earliest creation_date is the same or after 2014-01-01  and the latest creation_date is before 2015-01-01.

Here's an example which demonstrates that this is correct:

    
    PUT 2014-01/t/1
    {
      "date": "2014/01/01"
    }
    
    PUT 2014-02/t/1
    {
      "date": "2014/02/01"
    }
    
    PUT 2014-03/t/1
    {
      "date": "2014/03/01"
    }
    
    PUT 2014-04/t/1
    {
      "date": "2014/04/01"
    }
    
    PUT 2014-05/t/1
    {
      "date": "2014/05/01"
    }
    
    PUT 2014-06/t/1
    {
      "date": "2014/06/01"
    }
    
    GET 2014*/_field_stats?level=indices
    {
      "fields": [
        "date"
      ],
      "index_constraints": {
        "date": {
          "min_value": {
            "gte": "2014/03/01",
            "format": "yyyy/MM/dd"
          },
          "max_value": {
            "lt": "2014/06/01",
            "format": "yyyy/MM/dd"
          }
        }
      }
    }

**Comment by markwalkom** [comment]
Yeah, after I re-read it a few times it makes more sense. As does your example.
Thanks :)

**Comment by bleskes** [comment]
I think what people want to know is which indices are relevant to a certain period. Since all index constraints need to be matched, the version posted will return indices that are fully contained within the requested period. However, if indices are partially overlapping that period, they will not be returned. Here is a little tweak that demonstrates this (note the extra doc in the 2014-06 index):


```
PUT 2014-01/t/1
{
  "date": "2014/01/01"
}


PUT 2014-02/t/1
{
  "date": "2014/02/01"
}

PUT 2014-03/t/1
{
  "date": "2014/03/01"
}

PUT 2014-04/t/1
{
  "date": "2014/04/01"
}

PUT 2014-05/t/1
{
  "date": "2014/05/01"
}

PUT 2014-06/t/1
{
  "date": "2014/06/01"
}

PUT 2014-06/t/1
{
  "date": "2014/06/10"
}

PUT 2014-07/t/1
{
  "date": "2014/07/10"
}

## doesn't return 2014-06
GET 2014*/_field_stats?level=indices&filter_path=*.*.fields.date.doc_count
{
  "fields": [
    "date"
  ],
  "index_constraints": {
    "date": {
      "min_value": {
        "gte": "2014/03/01",
        "format": "yyyy/MM/dd"
      },
      "max_value": {
        "lt": "2014/06/03",
        "format": "yyyy/MM/dd"
      }
    }
  }
}

## does return 2014-06
GET 2014*/_field_stats?level=indices&filter_path=*.*.fields.date.doc_count
{
  "fields": [
    "date"
  ],
  "index_constraints": {
    "date": {
      "max_value": {
        "gte": "2014/03/01",
        "format": "yyyy/MM/dd"
      },
      "min_value": {
        "lt": "2014/06/03",
        "format": "yyyy/MM/dd"
      }
    }
  }
}
```

**Comment by clintongormley** [comment]
@bleskes nice one..
