### ISSUE TITLE
Reindex API fails if replicas count is increased during the operation

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#19234]
Reindexing using the Reindex API on 2.3.1, and setting replicas count to > 0 during the reindexing operation failed the operation with the following error:

```
   "failures": [
      {
         "index": "entities-1467533893025",
         "type": "entity",
         "id": "AVDSeSyc-CwqIYtC3lcT",
         "cause": {
            "type": "unavailable_shards_exception",
            "reason": "[entities-1467533893025][0] Not enough active copies to meet write consistency of [QUORUM] (have 1, needed 4). Timeout: [1m], request: [BulkShardRequest to [entities-1467533893025] containing [7] requests]"
         },
         "status": 503
      },
```

Can the reindex API be more tolerant for replication scaling? we used it this way because reindexing to 0 replicas is faster, but wanted to add replicas when nearing completion of the reindexing operation to allow for faster rollout of the new index.

**Comment by bleskes** [comment]
Reindexing behaves in the same way as normal indexing. Looking at the code, we currently don't expose the `consistencyLevel` parameter of the underlying indexing request. IMO we should. @nik9000 any opinion here?

Note that long term we have plans (which will hopefully make it into 5.0 - see discussions on #18985 ) to rename the consistencyLevel parameter to `waitForActiveShards` which reflects how it works. This will be set per request, but also have an index level settings to control the default, which will be updatable dynamically giving you what you want in a better way IMO.

**Comment by synhershko** [comment]
Sounds good. Might be worthy to mention I was jumping from replicas: 0 to 6, but given the batch mode of reindexing - the default IMO should be 100% async replication.

**Comment by bleskes** [comment]
Let’s not conflate async replications with the active shards requirement - it’s a different thing. That said async replication presents a challenge for error and such. It is removed and will therefore unlikely to come back.  If it all, we should invest in running the search of reindex concurrently to the indexing but that is another discussions as well (and it creates coordination complexity which I’m not sure at all is needed here).

**Comment by clintongormley** [comment]
This isn't a problem with reindexing, but with any CRUD request.  If you increase replicas to a point where the quorum is not available, CRUD requests will stall and eventually timeout.  I don't think this is a bug that can be fixed.

Exposing the consistency level (which would have to be done at the start of reindexing) would be a workaround for this situation and we should probably do that.

**Comment by nik9000** [comment]
> Exposing the consistency level (which would have to be done at the start of reindexing) would be a workaround for this situation and we should probably do that.

You can set the consistency level on reindex the same way you set it on any other write action. I just never documented it because I'm a doofus. [Here](https://github.com/elastic/elasticsearch/blob/2.4/modules/reindex/src/test/resources/rest-api-spec/test/reindex/60_consistency.yaml) is the test. It is just a request parameter.

Sorry I didn't notice this five days ago when you opened it....

**Comment by nik9000** [comment]
Ah. I do mention it in the URL Parameters section.
