### ISSUE TITLE
Is it normal that the search is very slow for * prefix search?

### ISSUE THREAD

**Issue by zyanbingchn** [elastic/elasticsearch#19239]
**Elasticsearch version**:  1.7.2

**JVM version**: 1.7

**OS version**: suse 11

**Description of the problem including expected versus actual behavior**:

Our data scale is very large, if I use the condition: *1.1.1.1 to search, it will spend very long time.
who can describe the mechanism of search for * which it is as the prefix of the condition, please?
is it really need so much time for search?

**Steps to reproduce**:
 1.  build a large scale data enviroment
 2.  use the condition: *1.1.1.1 to search

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by markwalkom** [comment]
Using a leading wildcard means that ES needs to check the queried field of *every* matching doc to check if the value exists. It's like a table scan.

This isn't a bug, so if you have further questions around this, please ask on https://discuss.elastic.co :)
