### ISSUE TITLE
Support for "Span Near Multiple" queries

### ISSUE THREAD

**Issue by trejkaz** [elastic/elasticsearch#19240]
The existing "Span Near" query type allows me to specify three terms which are all near each other.

```
{
    "span_near" : {
        "clauses" : [
            { "span_term" : { "field" : "value1" } },
            { "span_term" : { "field" : "value2" } },
            { "span_term" : { "field" : "value3" } }
        ],
        "slop" : 12,
        "in_order" : false,
        "collect_payloads" : false
    }
}
```

I would like a variant of this, but where the distance is measured between some base query and each of a collection of other queries.

For example,

```
{
    "span_near_multiple" : {
        "clause": { "span_term" : { "field" : "a" } },
        "near_clauses" : [
            { "span_term" : { "field" : "b" } },
            { "span_term" : { "field" : "c" } }
        ],
        "slop" : 2,
        "in_order" : false,
        "collect_payloads" : false
    }
}
```

This should match:

* a x b c
* b x x a x x c

The second of these examples is not matched by the existing Span Near query.

This should not match:

* a x x b

This is not the same as converting the query to a boolean query, because the following examples should not match:

* a x x b x x x x x x a x x c
* a x x b c x x a

If there is any way to get this behaviour from the existing queries, that would be good to know as well. But the best I can come up with is an approximation right now, and apparently the approximation is no longer good enough for one particular user.

**Comment by jpountz** [comment]
Would the below query work?

```
{
  "span_near": {
    "clauses": [
      {
        "span_term": {
          "field": "value1"
        }
      },
      {
        "span_or": {
          "clauses": [
            {
              "span_term": {
                "field": "value2"
              }
            },
            {
              "span_term": {
                "field": "value3"
              }
            }
          ]
        }
      }
    ],
    "slop": 2,
    "in_order": false,
    "collect_payloads": false
  }
}
```

**Comment by trejkaz** [comment]
Using a span_or would match:

* a x x b

but should not.

**Comment by jpountz** [comment]
This is the parth that confuses me a bit: how should the `near_clauses` be combined?

**Comment by trejkaz** [comment]
Each clause in `near_clauses` should be within the specified range of the `clause`. Essentially the same as `span_near`, but with multiple terms being tested.

**Comment by clintongormley** [comment]
This should work I think:

    PUT t/t/1
    {
      "text": "one two three four five six seven eight"
    }
    
    GET t/_search
    {
      "query": {
        "span_containing": {
          "little": {
            "span_term": {
              "text": "three"
            }
          },
          "big": {
            "span_near": {
              "clauses": [
                {
                  "span_term": {
                    "text": "one"
                  }
                },
                {
                  "span_term": {
                    "text": "three"
                  }
                },
                {
                  "span_term": {
                    "text": "four"
                  }
                }
              ],
              "slop": 2,
              "in_order": false
            }
          }
        }
      }
    }

**Comment by trejkaz** [comment]
That one doesn't match the already-provided example "a x b c".

Presumably the span_near returns the span from b to c, so a is not inside it.

**Comment by clintongormley** [comment]
I've played around with various options and find myself to be defeated. I've also found [this comment](https://lucidworks.com/blog/2009/07/18/the-spanquery/#comment-2222) from the author of the SpanWithinQuery which suggests that what you want might be possible by modifying the SpanWithinQuery.

We just inherit the span queries from Lucene, so I think you have two options: (a) open an issue on Lucene to convince somebody to build this query, or (b) write a plugin with a custom query based on SpanWithinQuery which does what you need. (If you do the latter, then please consider donating it to Lucene).

**Comment by trejkaz** [comment]
I have made attempts to hack queries in Lucene to get a similar effect (funnily enough I appear on that thread you link as well, from 5 years ago when I was last looking at this stuff!) but found span queries too hard to understand in order to modify them. I think the most I was able to do was make a SpanNotNearQuery out of SpanNotQuery because it only required modifying one line...

I already filed an issue with Lucene themselves for SpanAndQuery/SpanNearAllQuery at the time as well, but years passed with nothing being done, so it seems like nobody else has been keen enough to have it. :/

**Comment by trejkaz** [comment]
Another rewrite that I thought should work at the time went like this:

    spanNearAll(main, [near1, near2], slop)
     -> spanNot(
            main,
            spanOr([
                spanNot(main, near1, slop),
                spanNot(main, near2, slop)
            ])

Which is to say that you find all the spans where each sub-span is *not* near the main span, and then exclude those spans from the results, so what I thought would be left is the spans where all of the clauses are near the main span.

In practice though, it failed the tests, and I never understood why.

Another rewrite that someone else said they were using went like this:

    spanNearAll(main, [near1, near2], slop)
     -> spanNear([
            main,
            spanNear(main, near1, slop),
            spanNear(main, near2, slop)
        ], 0)

This passes nearly all the tests, but there are some edge cases where it's still wrong, things like:

    a x x x b c x x x a

It finds the span from a to b and then the span from c to a, and then decides that yes, the spans are near enough to match, and returns a false hit.

**Comment by clintongormley** [comment]
Discussed in Fix it Friday.  This should be added in Lucene rather than in Elasticsearch, even if it is added to the Lucene sandbox.
