### ISSUE TITLE
why the size of search thread pool in ES2.3.3 is smaller than before(f.e es version 1.3.0 )

### ISSUE THREAD

**Issue by kankedong** [elastic/elasticsearch#19245]
My server cpu cores are 24,today,i find the number of the search thread pool is 37 in my es version2.3.3;i want to know why this number is smaller than old version. what is the new default setting perpous?
thx for any answers~

**Comment by dadoonet** [comment]
Please ask your questions on discuss.elastic.co.

We can better help/answer there.
