### ISSUE TITLE
Missing filter params spec in termvectors API and mtermvectors API

### ISSUE THREAD

**Issue by saxsir** [elastic/elasticsearch#19243]
Term vectors API and Multi term vectors API supported filter params, but it's missing in spec files？

https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/termvectors.json

https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/mtermvectors.json

**Comment by clintongormley** [comment]
The `filter` param is part of the body, which is not spec'ed out in the REST specs at all.  We only specify the URL and query-string params.

See https://www.elastic.co/guide/en/elasticsearch/reference/2.3/docs-termvectors.html#docs-termvectors-terms-filtering
