### ISSUE TITLE
Alias delete and addition silently fails occasionally

### ISSUE THREAD

**Issue by smithsimonj** [elastic/elasticsearch#19247]
**Elasticsearch version**:
2.3.2
**JVM version**:
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
**OS version**:
Centos 7
**Description of the problem including expected versus actual behavior**:
I was migrating data on our 12 node elastic cluster and created a replica index with a new mapping for every index (79 indices in total). Then I ran a post command to `http://localhost:9200/_aliases` on one of the nodes and posted a list of 158 actions consisting of a remove of the alias pointing at the old index and then an add of the same alias name to the new index.

So something like:

```
Remove: A - > A1
Add: A -> A2
```

For every index.

This appeared to work and the result of GET  on `http://localhost:9200/_aliases` showed the correct mapping that I was hoping to achieve.

There was a serious error however with two of the indices the results of a search gave the results of **both** the old and the new index. Also, attempting to index new documents failed with an error saying that you cannot index documents on an alias with two indices.

As mentioned the GET on `http://localhost:9200/_aliases` yielded the correct result, leaving me to feel that the operations on two of the indices were not carried out to completion.

Further because the system appeared to think that the aliases were like those given in the result of GET on `http://localhost:9200/_aliases` I could not delete the alias to the old index.

In the end, I managed to get the alias to work for the two broken indices by reversing the change that I made, then remaking it. I.e. applying:

```
Remove: A -> A2
Add: A - > A1
```

Then again:

```
Remove: A - > A1
Add: A -> A2
```

And this finally fixed it so that the state shown by GET on `http://localhost:9200/_aliases` matched the observed behaviour.

This is very serious error when doing mass migrations as you can have no trust in the results of the alias changes.

We did not find any errors in the elastic logs when this operation occurred. 

**Steps to reproduce**:
1. Change the aliases in a single command for many (O(100)) indices on a large cluster
2. Attempt to insert a document into every alias and look for errors

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by ywelsch** [comment]
@smithsimonj I'll see whether I can reproduce this issue. Can you provide the exact command you ran for updating the aliases on the indices and also show the output of `http://localhost:9200/_aliases` when it was broken?

**Comment by smithsimonj** [comment]
@ywelsch I'm afraid I can't as it comprises a complete list of our clients. I used a script to generate the command and they were all of the form like that given below. The script looks good. The ```_aliases``` result also looked correct but the behaviour of the system didn't match the ```_aliases``` result.

One of my colleagues verified that I wasn't going mad and had indeed run the correct commands at the time. He also verified that the elastic cluster was in a funky state.

I'm sorry this is of no help to you, but I am confident from what we saw that there was a bug at play. Let me know how you get on trying to replicate it.

{
  "actions": [
    {
      "remove": {
        "index": "A-1464640477011",
        "alias": "A"
      }
    },
    {
      "add": {
        "index": "A-1466784086139",
        "alias": "A"
      }
    },
    {
      "remove": {
        "index": "B-1464640477011",
        "alias": "B"
      }
    },
    {
      "add": {
        "index": "B-1466784086139",
        "alias": "B"
      }
    },
  ...
}

**Comment by smithsimonj** [comment]
So I've anonymised the alias PUT body in this file: [elastic_bug_alias_command.txt](https://github.com/elastic/elasticsearch/files/346317/elastic_bug_alias_command.txt)

The elastic was initially set up so that all the old indices were aliased with the first part of the name (i.e. ```aa -> aa-1464640477011```. and the new indices i.e. ```aa-1466784086139``` did not have any aliases.

After this command the _aliases result looked as expected, but the behaviour of aliases ```ah``` and ```bb``` was as though:

- The indices ```ah-1464640477011``` and ```ah-1466784086139``` both had the alias ```ah```
- The indices ```bb-1464640477011``` and ```bb-1466784086139``` both had the alias ```bb```

**Comment by ywelsch** [comment]
@smithsimonj I've simulated your scenario multiple times and cannot find an issue. Implementation-wise, nothing points to a bug here. Updating the aliases results in one a single cluster state update (all or nothing). This means that indices are resolved during indexing/search operations either on the old or the new cluster state. I suspect that something was wrong in the `_aliases` update command (maybe using a wrong alias name?). Removing a non-existing alias is a no-op and will be silently ignored. Can you replicate the issue on a test cluster?

**Comment by smithsimonj** [comment]
Ok @ywelsch I'll try and write a script that replicates it

**Comment by colings86** [comment]
No further feedback. If you write a script that replicates the issue on a recent release please reopen this issue

**Comment by hshelat** [comment]
I have seen the exact same issue. In my case, we used the IndicesClient API of python elasticsearch client to update the aliases.
Elasticsearch version: 2.4.0
elasticsearch-py version: 2.4.0
To update aliases, we used update_aliases(body) where body is 
{"actions": [{"remove" : {"index": "myindex*", "alias": "myindex_current"}}, {"add": {"index": "myindex-2018_2", "alias": "myindex_current"}}]}
