### ISSUE TITLE
GregorianCalendar no longer accessible in ES 2.3?

### ISSUE THREAD

**Issue by twigbranch** [elastic/elasticsearch#19257]
In ES 2.0 I had a script (in a separate file called via script_file) which would utilize GregorianCalendar as follows:
`
endDate = new GregorianCalendar();
 `

After upgrading to 2.3, I get the following error at that line:
> unable to resolve class GregorianCalendar 

If I try to import with the following, I get an error at the import line.
`
import java.util.GregorianCalendar;
`

> unable to resolve class java.util.GregorianCalendar

**Comment by jasontedor** [comment]
Could you be more precise about what you're doing? I'm supposing this is in a script but it sure would be nice if you gave a simple reproduction (commands that set up and reproduce the situation from a clean install yet presumably worked in an earlier version that you didn't specify).

**Comment by twigbranch** [comment]
Updated with a bit more detail.

**Comment by jasontedor** [comment]
It's best to not edit in-place after replies have occurred, it makes the thread confusing. It would still be nice to have a minimal reproduction.

**Comment by twigbranch** [comment]
After looking around I found this:
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-security.html

I added the following in a security policy file and the script works again:
`
grant {
    permission org.elasticsearch.script.ClassPermission "java.util.GregorianCalendar";
    permission org.elasticsearch.script.ClassPermission "groovy.time.TimeCategory";
};
`

It would be nice if these were already whitelisted.

Would be nice also if the upgrade guide listing the breaking api changes included the link above (particularly given that the error information is vague and says nothing about security).

**Comment by clintongormley** [comment]
This is already listed in the breaking changes here: https://www.elastic.co/guide/en/elasticsearch/reference/current/float.html#_scripting_and_security
