### ISSUE TITLE
Updates in bulk api always update shards.

### ISSUE THREAD

**Issue by gkozyryatskyy** [elastic/elasticsearch#19267]
**Elasticsearch version**: 2.3.3

**JVM version**: 1.8.0_45

**OS version**: OS X 10.11.5

**Description of the problem including expected versus actual behavior**:
Bulk api with updates respond _shards.successful > 0 even if new _source not different from the old _source.

**Steps to reproduce**:
```
nano request
{ "update" : { "_index" : "test", "_type" : "test", "_id" : "1" } }
{ "doc" : {"data" : "some_data"}, "doc_as_upsert" : true }

# returning _shards.successful = 1
curl -XPOST 'localhost:9200/_bulk' --data-binary "@requests";

# sending request again. This should return _shards.successful = 0 but instead returns _shards.successful = 1
curl -XPOST 'localhost:9200/_bulk' --data-binary "@requests";
```

Here is example with _update api
```
# returns _shards.successful = 1
curl -XPOST localhost:9200/test/test/1/_update?pretty -d '{ "doc" : {"data" : "some_data"}, "doc_as_upsert" : true }'

# sending request again. Returns _shards.successful = 0
curl -XPOST localhost:9200/test/test/1/_update?pretty -d '{ "doc" : {"data" : "some_data"}, "doc_as_upsert" : true }'
```

**Comment by clintongormley** [comment]
The `update` API should change to return number of successful shards.

**Comment by gkozyryatskyy** [comment]
@clintongormley 
There was a noop (data was the same), that is why shards was not updated and _shards.successful = 0.
But the point is, that `bulk` api with `update` request in it, should detect noop too and return _shards.successful = 0 in the second call too. That is why `bulk` API with `update` in it, should be changed and return _shards.successful = 0 after update with same `_source`. Am I correct?

**Comment by clintongormley** [comment]
@gkozyryatskyy sure - you could argue it either way. I think it is more meaningful to say that the request was processed correctly for this shard, even though it is a noop

**Comment by gkozyryatskyy** [comment]
@clintongormley 
If it will return _shards.successful = 1for the same `_source`(request was processed correctly for this shard, even though it is a noop), it will be impossible to understand whether the data was reindexed (i.e does `_source` in `update` request changes the existed `_source`?). Exactly this functionality I need in `bulk` + `update` request. =)

**Comment by clintongormley** [comment]
@gkozyryatskyy a better way of doing this would be in this PR https://github.com/elastic/elasticsearch/pull/9736 which was closed only because of a lack of response. We'd still accept this feature if somebody wanted to pick up where this PR left off.

**Comment by gkozyryatskyy** [comment]
@clintongormley 
PR #9736 seems really a better way. It will be great if you can reopen/merge this feature.
