### ISSUE TITLE
Is there any more detailed elasticsearch dsl query document

### ISSUE THREAD

**Issue by justdoit0823** [elastic/elasticsearch#19260]
I read elasticsearch official document, but the dsl query chapter content is little.Is there any more detailed document content about how to construct dsl query and really understand dsl structure?

**Comment by dadoonet** [comment]
Please ask questions on discuss.elastic.co.

You can read:

* https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
* https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html

**Comment by justdoit0823** [comment]
But the above document link describe little information and is not systematic.

**Comment by nik9000** [comment]
> is not systematic.

Look in the table of contents to the right - it has entries like "Full text queries" and "Geo queries". It is all there.

**Comment by justdoit0823** [comment]
@nik9000 , I have already read that content which you mentioned. There are some simple query example and no more structural content and rules about the whole dsl query.

**Comment by clintongormley** [comment]
@justdoit0823 the definitive guide takes you through a long and detailed explanation of the query dsl.
