### ISSUE TITLE
Remove fielddata circuit breaker

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#19262]
This was added at a time when fielddata was the norm. As of 5.0, fielddata is only supported on text fields and is disabled by default. So there is no way to go out of memory because of fielddata with default mappings.

**Comment by clintongormley** [comment]
Fielddata may still be enabled on text fields for eg significant terms.  Is there a significant cost to keeping the circuit breaker?

**Comment by dakrone** [comment]
> So there is no way to go out of memory because of fielddata with default mappings.

This is only accurate for 5.0-only data, if someone upgrades a 2.3 cluster they may still be using field data. That said, I have to agree with Clint, someone may still enable fielddata, so I don't think it should be removed?

**Comment by jpountz** [comment]
The cost is not clear, I was just annoyed that the circuit-breaking service leaks into the MappedFieldType API and was thinking that we could remove it now that fielddata is not a first-class feature anymore.

**Comment by jpountz** [comment]
Discussed in FixitFriday: fielddata on analyzed strings are the reason why we added the circuit breaker so we cannot remove it unless we have a replacement.
