### ISSUE TITLE
Allow allocation and replication of closed indices

### ISSUE THREAD

**Issue by otisg** [elastic/elasticsearch#19273]
Being able to close indices is a great way to reduce memory usage in an ES cluster with lots of indices.  Unfortunately, it makes cluster expansion less automatic -- closed indices don't want to relocate when new nodes are added to the cluster.

It would be great it one could instruct ES to allow relocation of closed indices, too.

Similarly, imagine you have an index with 1 replica.  Imagine this index is closed.  Imagine that the node where there the replica was located dies.  Ooops, at this point this index doesn't have a replica.  I don't know if that will turn the index/cluster yellow or ES won't react to that, but it would be great it one could tell ES to create a replica on another node to make up for the lost replica.

**Comment by jasontedor** [comment]
Duplicates #12963
