### ISSUE TITLE
Node failures are not batch processed by the master

### ISSUE THREAD

**Issue by jjfalling** [elastic/elasticsearch#19282]
Currently when nodes fail we go through the failures one by one, each resulting in a cluster state publish. This can cause an issue on large clusters that lose a significant number of nodes. 

@bleskes

**Comment by ywelsch** [comment]
yes, that's certainly an optimization that can be done (we have talked about this before but not gotten around to it yet. It's simpler now to implement with the batching infrastructure in the clusterservice). Would you like to contribute a PR?
