### ISSUE TITLE
JAR HELL - ES plugin-specific libraries conflicts with ES_HOME/lib libraries

### ISSUE THREAD

**Issue by chindhuhari** [elastic/elasticsearch#19293]
**Elasticsearch version**: 2.3.2

**JVM version**: 1.7

**OS version**: Windows 8

**Description of the problem including expected versus actual behavior**: 
My crawl-plugin is dependent on Apache Tika 1.8 jar, when I try to start ES, it throws a Jar-Hell.
I've tried the isolation plugin property as well, seems like it's not supported. Looking for a solution to this problem or a right way to get working.
Please find the trace below :
D:\ES_BINARY\elasticsearch-2.3.2\bin>elasticsearch
[2016-07-07 00:44:16,298][INFO ][node                     ] [Monstro the Mighty] ve
[2016-07-07 00:44:16,299][INFO ][node                     ] [Monstro the Mighty] in
Exception in thread "main" java.lang.IllegalStateException: failed to load bundle [
rch-2.3.2/plugins/crawl-plugin/tika-app-1.8.jar] due to jar hell
Likely root cause: java.lang.IllegalStateException: jar hell!
class: com.sun.jna.AltCallingConvention
**jar1: C:\ES_BINARY\elasticsearch-2.3.2\lib\jna-4.1.0.jar
jar2: C:\ES_BINARY\elasticsearch-2.3.2\plugins\crawl-plugin\tika-app-1.8.jar**
        at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:282)
        at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:186)
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
        at org.elasticsearch.node.Node.<init>(Node.java:158)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by dadoonet** [comment]
Please use discuss.elastic.co for questions.

In mapper-attachments plugin we reduced the dependencies Tika is using for that. Have a look at the pom.xml in 2.3 branch. Might help you.

**Comment by chindhuhari** [comment]
Hi @dadoonet !
Sorry, I'll post it on the discuss page from now on. I thought it might be an issue that has to be fixed.
The problem is, the Tika jar here is being used by my custom crawl plugin. There is a jna jar in the elasticsearch's lib/ which is causing conflicts, which in turn is throwing a jar hell. **What do we do when the libraries we want to use has conflicts with elasticsearch's libraries.** 
I've pasted the trace, please do take a look.
Thanks!

**Comment by dadoonet** [comment]
You basically have to fix JAR conflicts on your side. So remove any jar which might conflict with elasticsearch.
Think about Jar Hell detector as a safe guard. It protects you from running unexpected code.

BTW, having a crawler as an elasticsearch plugin does not sound like a good idea to me.

Disclaimer: I wrote [FSCrawler](https://github.com/dadoonet/fscrawler) which was a river plugin but is now a standalone application.
As you can imagine I have no conflict anymore with elasticsearch librairies as I don't run my code embedded in elasticsearch :p .

**Comment by chindhuhari** [comment]
Hi again ! Thanks for your immediate reply.
The problem is, the Tika jar(used by my plugin) by itself has a conflict with the jna jar used by elasticsearch. As in, tika-app-1.8.jar structure :
                     **tika-app-1.8.jar\com\sun\jna\     <- This package and obviously the classes inside that is matching with the jna jar in ES_HOME/lib/
So, there is no scope of removing the jna out of the tika jar (repackaging the tika jar), as we are not allowed to that here :(**

I totally agree with you and have already seen the FSCrawler plugin :) months ago, just that it's something that might not be allowed at the place I work :|

Thanks much !

**Comment by dadoonet** [comment]
As I said, if you do the [exact same thing we are doing](https://github.com/elastic/elasticsearch/blob/2.3/plugins/mapper-attachments/pom.xml#L38-L402), I believe you won't have a conflict.
