### ISSUE TITLE
How to insert a parent-child Document?

### ISSUE THREAD

**Issue by debug529** [elastic/elasticsearch#19299]
when I use java client to insert a document, there's some errors:
unexpected error during the primary phase for action [indices:data/write/index], request [index {[userindex][useritem][1172], source[{"id":1172,"parent":"1172","text":"useritem1172"}]}]
java.lang.IllegalArgumentException: Can't specify parent if no parent field has been configured

> User user = new User(i, "user" + i, (int) (Math.random() * 100));
 byte[] userJson = JSONObject.toJSONBytes(user);
            IndexResponse response = client.prepareIndex("userindex", "user", user.getId().toString()).setSource(userJson).get();
            System.out.println(i + ", created=" + response.isCreated());

>  Item item = new Item(i, "useritem" + i, user.getId().toString());
            byte[] itemJson = JSONObject.toJSONBytes(item);
            IndexResponse response1 = client.prepareIndex("userindex", "useritem", item.getId().toString()).setParent(user.getId().toString()).setSource(itemJson).get();
            System.out.println(i + ", itemcreated=" + response1.isCreated());

should I make mapping first and how to make?

**Comment by jasontedor** [comment]
Please ask questions on the Elastic [Discourse forums](https://discuss.elastic.co/), we use GitHub for bug reports and feature requests only.
