### ISSUE TITLE
Build Failure: org.elasticsearch.snapshots.FsBlobStoreRepositoryIT.testMultipleSnapshotAndRollback

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#19291]
I was unable to reproduce this, but I'm not running Windows.

Reproduce With:
gradle :core:integTest -Dtests.seed=94DC6FDB9849F3FD -Dtests.class=org.elasticsearch.snapshots.FsBlobStoreRepositoryIT -Dtests.method="testMultipleSnapshotAndRollback" -Dtests.es.logger.level=DEBUG -Dtests.assertion.disabled=org.elasticsearch -Dtests.security.manager=true -Dtests.nightly=false -Dtests.heap.size=762m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:-UseCompressedOops -XX:+AggressiveOpts" -Dtests.locale=cs -Dtests.timezone=America/Fort_Wayne

Build Failure:
http://build-us-00.elastic.co/job/es_core_master_windows-2012-r2/3485/testReport/junit/org.elasticsearch.snapshots/FsBlobStoreRepositoryIT/testMultipleSnapshotAndRollback/

**Comment by abeyad** [comment]
I'll look into it

**Comment by javanna** [comment]
@abeyad news on this? Looks like a security manager problem happened only once and never again.

**Comment by abeyad** [comment]
@javanna I think this can be closed, you're right and I was never able to reproduce it.
