### ISSUE TITLE
Loading modules from class path

### ISSUE THREAD

**Issue by roytmana** [elastic/elasticsearch#19305]
We use embedded elastic heavily (WAR) and with modularization we are facing the issue of not being able to use native elastic modules particularly lang-expression because even if we drop its JARS into our class path the module is not getting registered. I was wondering if elastic team would consider an alternative and explicit way to register modules on class path such as a properties files in META-INF or programmatic registration or even giving elastic url(s)/streams for modules/plugins jars/resources so that elastic could load it with a separate class loader as normal. 
Currently it is very locked down and inflexible that modules (and plugins) can only be loaded from home directory. When we deliver our application to third party for deployment and maintenance it is very odd, error prone and unsafe to deliver bunch of jars and property files to be placed in external directories making sure that during upgrades old stuff get removed and new stuff gets placed in proper directories where the deployers only expect WAR and context files

**Comment by rjernst** [comment]
If the modules directory exists as it should, the modules will be loaded, even when constructing a Node directly. You just need the proper environment.

**Comment by roytmana** [comment]
yes it will load if I have modules directory under elastic home. it will even load if modules jars ar ein class path rather than under modules as long as there is sub-directory under modules for the module with plugin-descriptor.properties and plugin-security.policy (not sure it is supported configuration) but my point is that with embedded deployments of elastic it is expected that all application components are inside WAR file and there is no need to manage a whole bunch of additional JARs and properties making sure they are properly upgraded with each system upgrade. That's why I am asking for more open module deployment and registration mechanism

**Comment by roytmana** [comment]
@rjernst  Another viable option would be supporting not just modules and plugins directories but modules.zip and plugins.zip for packaged modules. With that integrity of modules inside the archive could be ensured and upgrade becomes just a matter of replacing modules.zp. All it takes is an abstraction over file based modules/plugins access so it can work over file system or zip file. I would be happy too develop it if it is acceptable for the elastic team

**Comment by roytmana** [comment]
The environment an dPluginService are actually implemented on top of FileSystem so using Zip file system is possible instead of the default one

just to try I plugged this into Environment class

```
      URI uri = URI.create("jar:"+ homeFile.toUri() + "/modules.zip");
      FileSystem fs = zipFileSystems.get(uri);
      if (fs == null) {
        Map<String, String> env = new HashMap<>();
        env.put("create", "true");
        try {
          fs = FileSystems.newFileSystem(uri, env);
          zipFileSystems.put(uri, fs);
        } catch (IOException e) {
          throw new IllegalArgumentException(e);
        }
      }
      modulesFile = fs.getPath("/");
```

and when my modules.zip only have plugin-descriptor.properties and plugin-security.policy while actual JARS are on class path it worked just fine. Unfortunately if I bundle JARS in modules it fails in checkJarHell because it jumps from Path representation linked to Zip file file system to relative URIs then files could not be found

**Comment by jprante** [comment]
@raytmana excellent suggestion. 

Adding plugins in zip filesystems is also how I implemented pluggable web apps in my Groovy web app platform so I would welcome this as an opportunity to better package and deploy plugins for ES.

**Comment by jasontedor** [comment]
We [do not support](https://www.elastic.co/blog/elasticsearch-the-server) embedded Elasticsearch nodes.
