### ISSUE TITLE
Async REST client implementation

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#19301]
I have been working on adding an async variant of the `performRequest` method to our `RestClient`. We currently have only the sync version, and we use apache http client internally. The http client is created by the `RestClient`, or it can be created externally and provided (see [here](https://github.com/elastic/elasticsearch/blob/master/client/rest/src/main/java/org/elasticsearch/client/RestClient.java#L384)), so that anything can be customized as long as supported by the underlying http client implementation.

For the async method we are thinking about using apache async http client. The apache async client class implements a different interface (`HttpAsyncClient` rather than `HttpClient`), although the way to configure it is similar to its sync sibling that it depends on. We would like to use only one client internally, which would have to be the async one then, in which case the sync `performRequest` method would just forward to the async one and wait for a response from it.

There are a couple of concerns around relying solely on the apache async http client:

- the async client doesn't seem as widely used as the sync one. People are mostly familiar with the sync one. Most of our users (hard to measure, just guts feeling) will use our sync method, but will end up using the async client internally anyways if we go for using async only internally, which is transparent only up to the point where users provide their own instance of the client with their own configuration (ssl, basic auth, custom timeouts...).

- apache async client doesn't support (yet) transparent content decompression, which means people are not going to be able to make advantage of http compressed responses out of the box. The client won't provide the needed "accept" header, so no compressed responses will be returned.

There may be other limitations that I haven't bumped into yet, suggestions are welcome. In general, do we think that the compressed response limitation is a big deal? I would say no but I opened this issue so we can discuss and come to a conclusion or evaluate alternatives.

A couple of alternatives to using only the apache async client internally:
1) Support both clients and use one or the other depending on the method called, or have two different `RestClient` implementations. The latter may sound cleaner, but it ends up complicating things quite a bit, especially moving forward with the high level client (e.g. which client impl is needed/required/supported for each specific api?).
2) Use an async client only internally, but not the apache one. It needs to be able to send get and delete requests with body (or allow to make it possible with few lines of code).

**Comment by danielmitterdorfer** [comment]
My thoughts on this:

> In general, do we think that the compressed response limitation is a big deal? 

Given that other language clients also don't support it out of the box, I'd say no. It may make a difference for requests with larger bodies (like bulk requests) but I have experienced that it's sometimes worse in the higher percentile latencies (99th percentile and up) for search requests.

> async client doesn't seem as widely used as the sync one

That may be true but the question is whether there are more mature alternatives than the Apache async client.

Regarding the suggested alternatives:

> Support both clients and use one or the other depending on the method called, or have two different RestClient implementations

I'd tend not to do that because this could like get a maintenance nightmare or a huge time sink when hunting for bugs. If we use just one implementation internally something either breaks or it doesn't (or always behaves slow or whatever) but at least it does not depend whether users choose the sync or the async version of our API.

**Comment by nik9000** [comment]
I also like the idea of having one implementation internally. Implementing the synchronous version of the API by doing the async call and blocking on the future seems fairly sane. I think it is worth looking at the performance impacts of it though.

Regarding maturity - it might be worth looking at something like okhttp. I get the sense httpclient async doesn't see all that much use. It feels kind of like an afterthought. okhttp doesn't break sync and async into two libraries which gives me the sense that async is more a core design choice. I don't know if it is a good choice, just an option that might be worth looking into.

**Comment by nik9000** [comment]
I just checked - okhttp only depends on okio which depends on nothing. Collectively they pull in animal sniffer and android as optional dependencies. We wouldn't ship either one but we'd still have to poke the third party audit a bit.

**Comment by javanna** [comment]
> I think it is worth looking at the performance impacts of it though.

Yes! #19281 will help.

> Regarding maturity - it might be worth looking at something like okhttp

Last time I checked, I didn't find a way to send get requests with a body with it, and that didn't seem like something that could be patched (https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/http/HttpMethod.java#L36). Maybe that one per se shouldn't be a reason not to consider it though, not sure.

**Comment by nik9000** [comment]
> Maybe that one per se shouldn't be a reason not to consider it though, not sure.

For better or worse we support GET with a body and we need to test it and the http client is the thing that does that.

I opened https://github.com/square/okhttp/issues/2706. Even if they wanted to implement it simple timing may make us using it impossible. But I figured it was worth a shot.

**Comment by javanna** [comment]
We discussed this in FixItFriday. Everybody agrees that we should go with only one http client implementation otherwise things would become hard to maintain. We will go with apache async http client and see how that works out. It is not a huge deal to change the underneath implementation later anyways, besides user configuration that would need to be adapted. Closing.
