### ISSUE TITLE
network.publish_host does not pull the appropriate values from network.bind_host

### ISSUE THREAD

**Issue by trevor-vaughan** [elastic/elasticsearch#19304]
**Elasticsearch version**:

2.3

**JVM version**:

1.8

**OS version**:

CentOS 7 and CentOS 6

**Description of the problem including expected versus actual behavior**:

The documentation indicates that network.publish_host should be pulled from network.bind_host if it is not explicitly set. https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#advanced-network-settings

In my tests, network.publish_host was being set to 127.0.0.1 even when network.bind_host was being explicitly set.

My setup uses the  expanded YAML format and does not collapse the keys. I do not know if this bug is present with collapsed keys.

Example config snippet:

```yaml
'network' => {
  'bind_host' => '10.5.2.3'
}
```

**Steps to reproduce**:
 1. Start a cluster with network.bind_host set to an explicit IP and without network.publish_host set in the expanded YAML format.

**Comment by clintongormley** [comment]
Thanks for reporting @trevor-vaughan - I've updated the docs
