### ISSUE TITLE
Use output of rescoring when top hits aggregation is used

### ISSUE THREAD

**Issue by ebernhardson** [elastic/elasticsearch#19317]
**Describe the feature**:

When using the top_hits aggregation it is sorting by the scores prior to rescore running. I put together an trimmed down example script that demonstrates this. The score from the main query is returned as 2.6434526, but the score as seen in top_hits aggregation is 1.

The larger goal is to perform a search over a geographic area, take the top N (we use 8192) hits per shard, and then show the top M hits per grid point. While the example below uses a match_all for simplicity with a 10km area, the query could just as well be run with a query_string query, additional filters, and over a much larger area. I would like to keep the original limits put in place in the rescore phase and only aggregate over those 8k results per shard.  Utilizing the result of rescoring is incredibly important for choosing the best items per grid point in my use case.

```
#!/bin/sh

curl -s -XDELETE localhost:9200/top_hits_rescore | jq -c .
curl -s -XPUT localhost:9200/top_hits_rescore/ -d '{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 0
    }
  }
}' | jq -c .;

curl -s -XPUT localhost:9200/top_hits_rescore/_mapping/page -d '{
  "properties": {
    "title": { "type": "string" },
    "weight": { "type": "long" },
    "coord": { "type": "geo_point", "lat_lon": true }
  }
}' | jq -c .

curl -s -XPOST localhost:9200/top_hits_rescore/page/ -d '{
  "title": "foo",
  "weight": 42,
  "coord": { "lat": 1.2345, "lon": 5.4321 }
}' | jq -c .

curl -s -XPOST localhost:9200/top_hits_rescore/_flush | jq -c .

curl -s -XGET localhost:9200/top_hits_rescore/page/_search -d '{
  "rescore": [
    {
      "query": {
        "rescore_query": {
          "function_score": {
            "functions": [ {
              "field_value_factor": {
                "modifier": "log2p",
                "field": "weight"
              }
            } ]
          }
        }
      }
    }
  ],
  "query": {
    "bool": {
      "must": [ { "match_all": {} } ],
      "filter": [ {
        "geo_distance": {
          "distance": "10km",
          "coord": { "lat": 1.2345, "lon": 5.4321 }
        }
      } ]
    }
  },
  "aggs": {
    "grid": {
      "geohash_grid": { "field": "coord" },
      "aggs": {
        "top_grid_hits": { "top_hits": {} }
      }
    }
  }
}' | jq .
```

**Comment by clintongormley** [comment]
We should be able to add this, as long as we can reuse the existing rescore infrastructure

**Comment by Morikko** [comment]
It is only working when you use the TopHits aggregations with the default sorting. It won't work with a custom sort, the score value used is the one before the rescore application.

Example:
```json
{
    "aggs": {
        "hit": {
            "top_hits": {
                "sort": [
                    "_score",
                    {
                        "number_of_links": "desc"
                    }
                ]
            }
        }
    },
    "query": {
        "match": {
            "paragraph": {
                "query": "hello"
            }
        }
    },
    "rescore": {
        "window_size": 100,
        "query": {
            "rescore_query": {
                "match": {
                    "paragraph": {
                        "query": "world"
                    }
                }
            },
            "query_weight": 1,
            "rescore_query_weight": 100
        }
    },
    "from": 0,
    "size": 5
}
```
In the main hits there is a max score around hundreds and in the top hits aggregation it is less than ten.

Is it expected or a bug ?

**Comment by jimczi** [comment]
We should throw an error in that case, that's what we do if you define a custom `sort` in the main query, @Morikko , but we forgot to add the check in the `top_hits` aggregation.
Can you open a new issue ?
