### ISSUE TITLE
What is the deal with GeoDistanceIT#testDuelOptimizations?

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#19315]
It calls `assertDuelOptimization` which is fairly confusing but doesn't seem to assert a whole lot. In fact I'm not really sure what it does assert.

When you run the whole suite with `@Seed("A72FE66BDD9F236C")` it GCs fairly hard.

This cam up in:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=ubuntu/726/console

**Comment by jasontedor** [comment]
Is this a duplicate of #19263?

**Comment by nik9000** [comment]
Dupe.

**Comment by nik9000** [comment]
I should have searched.
