### ISSUE TITLE
Show ignored error in verbose simulate processor results

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#19319]
It would be nice to include the error (that was ignored in processors with `ignore_failure` flag on) with the document returned in a /_simulate?verbose response.

So that the processor's result would look like this:

```
[
...
{
"tag" : "processor_tag",
"ignored_error": { "error" : ... },
"doc" : {...}
},
...
]
```

Even though the processor technically succeeded, it is useful to have the ignored failure (if one is present) for debugging purposes

**Comment by martijnvg** [comment]
So when we decorate (`TrackingResultProcessor#TrackingResultProcessor`) the pipeline's processors we would set `ignoreFailure` always to false on the newly returned `CompoundProcessor` and in `TrackingResultProcessor#execute(...)` we would remember the caught exception but not throw it?

**Comment by talevy** [comment]
@martijnvg, exactly. This means that `SimulateProcessorResult` would not be either an error or a document, but instead could contain both an error and a document to be rendered.

So here: https://github.com/talevy/elasticsearch/blob/28fd684eef75592346e72c92177e7dd86af82608/core/src/main/java/org/elasticsearch/action/ingest/TrackingResultProcessor.java#L52-L52

would change to be something like this:

```
processorResultList.add(new SimulateProcessorResult(actualProcessor.getTag(), new IngestDocument(ingestDocument), e));
```

and then the `SimulateProcessorResult#toXContent` would property render the json response as suggested in the issue description.

**Comment by martijnvg** [comment]
+1
