### ISSUE TITLE
Options to perform a request with the new Rest client 

### ISSUE THREAD

**Issue by jettro** [elastic/elasticsearch#19312]
**Describe the feature**:
At the moment the method to perform a request using the new Rest client (5.0 alpha 4) looks like this:

```
Response response = client.performRequest(
            "GET",
            "_cluster/health",
            new Hashtable<>(),
            null);
```

If you do not need to provide parameters, you have to provide an empty Map. And if you do not need a request body you have to pass _null_. For me an additional method like this seems nice to have.

```
Response response = client.performRequest(
            "GET",
            "_cluster/health");
```

**Comment by javanna** [comment]
We discussed this in FixItFriday, we will add this method and also another one that accepts parameters but not the body. PR will come soon.
