### ISSUE TITLE
Rename default cluster name

### ISSUE THREAD

**Issue by uboness** [elastic/elasticsearch#19330]
Today, when not explicitly configured, the cluster name defaults to `elasticsearch`. With the broader role ES serves in the stack (specifically when looking at it in Kibana 5.0+) this can be quite confusing.

We should instead name it `my_elastic`. We believe this name is appropriate as:
- it communicates the cluster role in the context of the elastic stack
- the `my_` prefix is "annoying" enough to encourage the users to renamed it :)

**Comment by s1monw** [comment]
I'd personally name it `unnamed_cluster` or `unnamed_elastic_cluster` I think it should be clear that it must be changed. `my_` isn't clear IMO

**Comment by jasontedor** [comment]
We don't need to pick a Windows 95-esque name to encourage users to change the cluster name. We can just add a bootstrap check that requires a non-default cluster name if the instance is running in production mode.

**Comment by jasontedor** [comment]
I opened #19339.

**Comment by jasontedor** [comment]
After consideration of the complexity of changing the cluster name and how it relates to the on-disk data folder, and considering also #18554, I have closed #19939. I do not think we should choose an intentionally annoying name.

**Comment by uboness** [comment]
@jasontedor I'm fine with a bootstrap check... but that's still missing the point raised in this issue. The current name doesn't play well with our stack and we need to change it. 

`unnamed`, `cluster` or `elastic` all don't play well on their own. `my_elastic` is still my vote (even if for some it brings back memories from the past). With the direction kibana is going, It's the one name that when opening Kibana and reading `/cluster/my_elastic` in the breadcrumbs, actually makes sense and to some extend friendly.

Big -1 on leaving it as is

**Comment by jasontedor** [comment]
@uboness My previous comment was not a comment for leaving it as is, just a comment against choosing an annoying name.

**Comment by jasontedor** [comment]
No additional feedback in one-and-a-half-years. I will close this issue for now, and we can open a new issue if there is a compelling reason to do so.
