### ISSUE TITLE
FieldValueFactorFunctionParser retrieves the SearchContext with SearchContext.current()

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#19341]
This only works when executing search requests, since in that case there is a live search context. However this breaks the percolator which needs to parse queries when indexing documents.

For the record this seems to be fixed on master (5.0) thanks to the query refactoring. However 2.4 is still affected.

**Comment by javanna** [comment]
`RandomScoreFunctionBuilder` has the same problem, still in master: https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/query/functionscore/RandomScoreFunctionBuilder.java#L139

**Comment by clintongormley** [comment]
@javanna @jpountz is this still a problem in 5.0?

**Comment by jpountz** [comment]
It's not indeed! Fixed by #20778.
