### ISSUE TITLE
Remove cloud.enabled setting

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#19349]
This setting `cloud.enabled` has been removed in master (5.0) which is nice.
I think we should also remove it in 2.4 as it is:

* useless
* error prone for our java transport client users. See https://discuss.elastic.co/t/transportclient-and-creating-an-s3-snapshot-repository/55088

If we don't remove this setting in 2.4, we need than to document this setting in every cloud related plugin documentation.

Thoughts?

* Remove?
* Document?
* Both (document in 2.3, 2.2, 2.1, 2.0 branches) and remove in 2.4?

**Comment by clintongormley** [comment]
> Both (document in 2.3, 2.2, 2.1, 2.0 branches) and remove in 2.4?

Document, and ignore the setting in 2.4 with deprecation logging.  We don't want a breaking change if we can avoid it.

**Comment by dadoonet** [comment]
So that looks strange. I tried to look at the code today and reproduce the issue reported and was not able.

Here is what I did:

* Launch a node with default settings and `cloud-aws` plugin.
* Create a TransportClient like this:

```
        TransportClient client = new TransportClient.Builder()
                .addPlugin(CloudAwsPlugin.class)
                .build();
        client.addTransportAddress(new InetSocketTransportAddress(new InetSocketAddress("127.0.0.1", 9300)));

        PutRepositoryResponse putRepositoryResponse = client.admin().cluster().preparePutRepository("test-repo")
                .setType("s3").setSettings(Settings.EMPTY).get();
```

This does not raise the issue reported.
Also in code we default `cloud.enabled` to `true`. So I can't understand how this happened.

I think I should close it for now and may be reopen if the issue is confirmed by the user (on discuss).
