### ISSUE TITLE
template issues

### ISSUE THREAD

**Issue by jacksu** [elastic/elasticsearch#19347]
if one template name is template_one, args "template":"a*";another name is template_two,args "template":"aa*".If i create index name is "aa_20160709",which template will use.

**Comment by jasontedor** [comment]
This is a general question but Elastic reserves GitHub for bug reports and feature requests. You can ask general questions on the [Elastic Discourse forums](https://discuss.elastic.co). Also, note that you could experiment with this very easily and know right away.
