### ISSUE TITLE
Throwing error while importing geopoint field in elasticsearch using cmd

### ISSUE THREAD

**Issue by sauravsharma001** [elastic/elasticsearch#19344]
**Version:** elasticsearch 2.3.3
**Operating System:** Windows 8.1

**Mapping File:**
{
"mappings": {
"ticket": {
"properties": {
"Action": {
"type": "string", "index" : "not_analyzed"
},
"Case Number": {
"type": "string"
},
"Department": {
"type": "string"
},
"Case Record Type": {
"type": "string"
},
"Centerline": {
"type": "geo_point",
"lat_lon": true
},
"Service Request Type": {
"type": "string"
},
"Status": {
"type": "string", "index" : "not_analyzed"
},
"Origin": {
"type": "string", "index" : "not_analyzed"
},
"Subject": {
"type": "string", "index" : "not_analyzed"
},
"Street": {
"type": "string"
},
"Contact Name": {
"type": "string", "index" : "not_analyzed"
},
"Created Date": {
"format": "date_time",
"type": "date"
},
"Closed Date": {
"format": "date_time",
"type": "date"
},
"SLA": {
"type": "string"
}
}
}
}

}
-------------------------------------------------------------------------------------------------------------------------------
**Sample Data:** ticket_1.json
{
"index": {
"_index": "tickets",
"_type": "Police Department",
"_id": 10670953
}
}{
"Case Number": "10670953",
"Department": "Police Department",
"Case Record Type": "Abandoned Vehicle",
"Service Request Type": "Abandoned Vehicle",
"Status": "Closed",
"Origin": "Phone",
"Subject": "Abandoned Vehicle",
"Street": "310 E WILLIAM ST",
"Contact Name": "",
"Centerline": [-75.12612642,
39.99305799],
"Created Date": "2016-04-08T18:32:12.000Z",
"Closed Date": "2016-04-25T16:23:26.000Z",
"SLA": "30 Business Days"
}{
"index": {
"_index": "tickets",
"_type": "License & Inspections",
"_id": 10670956
}
}{
"Case Number": "10670956",
"Department": "License & Inspections",
"Case Record Type": "Building Dangerous",
"Service Request Type": "Building Dangerous Occupied",
"Status": "In-Progress",
"Origin": "Phone",
"Subject": "Building Dangerous",
"Street": "642 S 55TH ST",
"Contact Name": "Steven Jones",
"Centerline": [-75.23307959,
39.94990503],
"Created Date": "2016-04-08T18:33:55.000Z",
"Closed Date": null,
"SLA": "5 Business Days"
}

-----------------------------------------------------------------------------------------------------------------------------
**Command used for uploading data into elasticsearch**

curl -XPUT localhost:9200/tickets/_bulk?pretty --data-binary @ticket_1.json

------------------------------------------------------------------------------------------------------------------------------
**Error Thrown:**
{
"took" : 31,
"errors" : true,
"items" : [ {
"index" : {
"_index" : "tickets",
"_type" : "Police Department",
"_id" : "10670953",
"status" : 400,
"error" : {
"type" : "mapper_parsing_exception",
"reason" : "failed to parse",
"caused_by" : {
"type" : "illegal_state_exception",
"reason" : "Mixing up field types: class org.elasticsearch.index.mapper.core.DoubleFieldMapper$DoubleFieldType != class org.e
lasticsearch.index.mapper.geo.BaseGeoPointFieldMapper$GeoPointFieldType on field Centerline"
}
}
}
}, {
"index" : {
"_index" : "tickets",
"_type" : "License & Inspections",
"_id" : "10670956",
"status" : 400,
"error" : {
"type" : "mapper_parsing_exception",
"reason" : "failed to parse",
"caused_by" : {
"type" : "illegal_state_exception",
"reason" : "Mixing up field types: class org.elasticsearch.index.mapper.core.DoubleFieldMapper$DoubleFieldType != class org.e
lasticsearch.index.mapper.geo.BaseGeoPointFieldMapper$GeoPointFieldType on field Centerline"
}
}
}
} ]
}

**Comment by clintongormley** [comment]
You create a mapping called `ticket`, but then you create docs with types `Police Department` and `License & Inspections`, without the geo point mapping

**Comment by sauravsharma001** [comment]
Thanks @clintongormley. That resolved the error.

**Comment by vishnubraj** [comment]
How did you solve it.. i am also having problem in creating maual ip type. Please look at this ticket https://discuss.elastic.co/t/mixing-up-field-types-error-ip-field-is-not-getting-added/55332/2
