### ISSUE TITLE
Modify foreach processor to accept a single processor instead of collection

### ISSUE THREAD

**Issue by BigFunger** [elastic/elasticsearch#19345]
@BigFunger, @Bargs, and @talevy had a discussion on Zoom earlier today, and this is one of the issues that we discussed.

### Summary
I would like to see the foreach processor reworked so that it only accepts a single processor instead of an array of processors as it does now.

### Background
I have been working on the UI for ingest pipelines, and specifically I have been trying to implement the foreach processor. The UI uses the verbose setting on the simulate API to report back to the user. 

This way, when the user add or edits a processor, I can use the output from the parent processor as the input of the next and provide them with the data necessary to build out their processors. This is a problem in the context of the foreach processor because I can't provide the user with the input and output of each of the processors defined within the foreach processor.

Per our discussion, it also make sense to structure the foreach processor in this way because it follows the patterns that have been established in the other processors. For example, if you want to apply an `uppercase` processor to more than one field in the document, you need to create one `uppercase` processor for each field you want to act on.

### Example
With a pipeline definition of the following:
```json
{
  "pipeline": {
    "description": "",
    "processors": [
      {
        "split": {
          "tag": "processor_1",
          "field": "message",
          "separator": " "
        }
      },
      {
        "foreach": {
          "tag": "processor_2",
          "field": "message",
          "processors": [
            {
              "uppercase": {
                "tag": "processor_3",
                "field": "_value"
              },
              "lowercase": {
                "tag": "processor_4",
                "field": "_value"
              },
              "uppercase": {
                "tag": "processor_5",
                "field": "_value"
              }
            }
          ]
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "message": "these are the words of a sentence"
      }
    }
  ]
}
```

I would expect the following output:
```json
{
  "docs": [
    {
      "processor_results": [
        {
          "tag": "processor_1",
          "doc": {
            "_type": "_type",
            "_id": "_id",
            "_index": "_index",
            "_source": {
              "message": [
                "these",
                "are",
                "the",
                "words",
                "of",
                "a",
                "sentence"
              ]
            },
            "_ingest": {
              "timestamp": "2016-07-06T21:27:14.585+0000"
            }
          }
        },
        {
          "tag": "processor_3",
          "doc": {
            "_type": "_type",
            "_id": "_id",
            "_index": "_index",
            "_source": {
              "message": [
                "THESE",
                "ARE",
                "THE",
                "WORDS",
                "OF",
                "A",
                "SENTENCE"
              ]
            },
            "_ingest": {
              "timestamp": "2016-07-06T21:27:14.585+0000"
            }
          }
        },
        {
          "tag": "processor_4",
          "doc": {
            "_type": "_type",
            "_id": "_id",
            "_index": "_index",
            "_source": {
              "message": [
                "these",
                "are",
                "the",
                "words",
                "of",
                "a",
                "sentence"
              ]
            },
            "_ingest": {
              "timestamp": "2016-07-06T21:27:14.585+0000"
            }
          }
        },
        {
          "tag": "processor_5",
          "doc": {
            "_type": "_type",
            "_id": "_id",
            "_index": "_index",
            "_source": {
              "message": [
                "THESE",
                "ARE",
                "THE",
                "WORDS",
                "OF",
                "A",
                "SENTENCE"
              ]
            },
            "_ingest": {
              "timestamp": "2016-07-06T21:27:14.585+0000"
            }
          }
        },
        {
          "tag": "processor_2",
          "doc": {
            "_type": "_type",
            "_id": "_id",
            "_index": "_index",
            "_source": {
              "message": [
                "THESE",
                "ARE",
                "THE",
                "WORDS",
                "OF",
                "A",
                "SENTENCE"
              ]
            },
            "_ingest": {
              "timestamp": "2016-07-06T21:27:14.585+0000"
            }
          }
        }
      ]
    }
  ]
}
```
Instead, I get this back:

```json
{
  "docs": [
    {
      "processor_results": [
        {
          "tag": "processor_1",
          "doc": {
            "_id": "_id",
            "_type": "_type",
            "_index": "_index",
            "_source": {
              "message": [
                "these",
                "are",
                "the",
                "words",
                "of",
                "a",
                "sentence"
              ]
            },
            "_ingest": {
              "timestamp": "2016-07-08T21:36:14.400+0000"
            }
          }
        },
        {
          "tag": "processor_2",
          "doc": {
            "_id": "_id",
            "_type": "_type",
            "_index": "_index",
            "_source": {
              "message": [
                "these",
                "are",
                "the",
                "words",
                "of",
                "a",
                "sentence"
              ]
            },
            "_ingest": {
              "timestamp": "2016-07-08T21:36:14.400+0000"
            }
          }
        }
      ]
    }
  ]
}
```

**Comment by Bargs** [comment]
👍  In addition to @BigFunger's points about the requirements for the ingest UI, I think this change will make pipelines much easier to reason about, without really losing any power. When I started trying to think about the possible outcomes of deeply nested forEach processors, with an arbitrary number of sub-processors, and an arbitrary number of failure branches, my head started to hurt.

**Comment by martijnvg** [comment]
I'm +1 with only allowing a single processor inside the `foreach` processor. The complexity can really increase quickly, which is unintended and doesn't serve the `foreach` processor's goal (performing on operation on all values in an array).

**Comment by clintongormley** [comment]
👍

**Comment by talevy** [comment]
looks like there is consensus around this. I'll get on this

**Comment by Bargs** [comment]
If foreach only accepts one processor, would it be more user friendly to expose this functionality as a flag that can be applied to any processor, as opposed to being a special processor that wraps other processors? 

For the nested loop use case (foreach inside a foreach) the user could simply specify the level of nesting they require. So to modify the nested numbers in a field value like `[[1, 2], [3, 4]]` they could declare a processor like this:

```
{
  "set": {
    "field": "_value",
    "value": "foo",
    "foreach": 2
  }
}
```

To me this feels a bit more declarative and natural if we only support looping one processor, but maybe it's just me.

**Comment by talevy** [comment]
here is the PR for this issue: #19402 

@Bargs: Although I do agree `foreach` feels like it should be more of a 1st class citizen of the pipeline DSL, I am not sure how generally applicable this is to all types of processors and fields. I think that leaving it as its own Processor should still be fine for now.

**Comment by hogbinj** [comment]
However it makes removing fields in an attachment array difficult there seems to be a limit of only one foreach in a Processors pipeline

[https://discuss.elastic.co/t/tuning-attachment-ingest-with-arrays-get-rid-of-the-raw-data/72220](url)

**Comment by talevy** [comment]
@hogbinj a little confused what to you mean. Here is a sample Simulate API request that runs a pipeline with multiple foreach processors

```
POST _ingest/pipeline/_simulate
{
  "pipeline" : {
    "processors" : [
      {
        "foreach" : {
          "field": "field",
          "processor" : {
            "uppercase" : { "field" : "_ingest._value.data" }
          }
        }
      },
      {
        "foreach" : {
          "field": "field",
          "processor" : {
            "remove" : { "field" : "_ingest._value.data" }
          }
        }
      }
    ]
  },
  "docs" : [
    {
      "_source" : {
        "field": [{"data": "a"}, {"data": "b"}, {"data": "c"}]
      }
    }
  ]
}
```

**Comment by hogbinj** [comment]
You cant do that in elastic cloud. 

Kibana only allows one foreach

![image](https://cloud.githubusercontent.com/assets/6162120/22127788/72b6cdde-de95-11e6-8544-d1100f6ee1dc.png)

**Comment by talevy** [comment]
ah, that is because there is a missing closing brace before that second `foreach`

**Comment by hogbinj** [comment]
OK now the pipeline is correct syntax as Kibana takes it, although sense or DevTools is still throwing an error HOWEVER.....
![image](https://cloud.githubusercontent.com/assets/6162120/22128192/4ea2943a-de97-11e6-84cf-ab08a9767b68.png)

When I ingest data through the pipeline I've lost the whole attachment field. not just the data field

![image](https://cloud.githubusercontent.com/assets/6162120/22128236/9147cf9e-de97-11e6-9450-c83ff31c7b1b.png)

**Comment by hogbinj** [comment]
Arrrgghh! Curly Bracket hell!!  Working now.  Thank you so much.  Needed one more closing bracket

![image](https://cloud.githubusercontent.com/assets/6162120/22128342/f947a63c-de97-11e6-9ea6-49eae1f284d1.png)

**Comment by talevy** [comment]
sweet! happy to hear it all worked out!
