### ISSUE TITLE
String Query for java API dosen't find some documents by name

### ISSUE THREAD

**Issue by EngErik** [elastic/elasticsearch#19350]
Hello! 

First, sorry for my poor english, but let me try to explain my problem. 

I'm working in an application using elasticsearch java api for managed my documents. 
Everything works fine, i'm able to search in DB and save on my index, i can count my documents aggregate by field and a lot of cool things, but i stucked on a weird problem. 

When i trying to search my document by field called name, some documents doesn't not return on search. 

Let me give an example:

My documents is look like this(just for example):

id: 1
name: book
type: pdf

---------

id: 2
name: Test of my search service
type: zip

When i trying to search, if i search by name, send as parameter the value "book", it works fine, but when i trying to search, send my parameter value "service", the result is empty. 

Here my search code:

`SearchRequestBuilder src1 = client.prepareSearch()
					.setQuery(QueryBuilders.queryStringQuery(parameter)
							.field("name"));`

Anyone knows, why this search doesn't find my parameter value "service" on name field of document with id 2?

Thanks!

**Comment by jasontedor** [comment]
This is a general question but Elastic reserves GitHub for bug reports and feature requests. You can ask general questions on the [Elastic Discourse forum](https://discuss.elastic.co).
