### ISSUE TITLE
Export saved searches

### ISSUE THREAD

**Issue by dpappas** [elastic/elasticsearch#19361]
Hello everyone

I use Elasticsearch and Kibana.

Is there a way to export my saved searches' json request with a get request?
I would like to do so automatically. Not using the kibana UI.

Thank you

**Comment by jasontedor** [comment]
This question looks like it would best be addressed through Kibana channels. I recommend posting a question in the Kibana category on the [Elastic Discourse forum](https://discuss.elastic.co).
