### ISSUE TITLE
File Dependencies do not work as expected

### ISSUE THREAD

**Issue by matzischatzi** [elastic/elasticsearch#19369]
**Elasticsearch version**: 5.0.0-alpha5-SNAPSHOT

**JVM version**:  jdk 1.8.0_91

**OS version**: Ubuntu 14.04 LTS

**Description of the problem including expected versus actual behavior**: File Dependencies do not work as expected

**Steps to reproduce**:
 1. If I use the following build script, it works so far:

```
   buildscript {
	   repositories {
		   mavenCentral()
		   maven {
			   name 'sonatype-snapshots'
			   url "https://oss.sonatype.org/content/repositories/snapshots/"
		}
		jcenter()
	}
	dependencies {
		  classpath "org.elasticsearch.gradle:build-tools:5.0.0-alpha5-SNAPSHOT" 
	}
}
apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'eclipse'
apply plugin: 'elasticsearch.esplugin'
```

 2. If instead I manually download the .jar file https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/gradle/build-tools/5.0.0-alpha5-SNAPSHOT/build-tools-5.0.0-20160613.145150-483 and use the file dependencies as follows, it does not work any more (see error log below):

```
   buildscript {
	repositories {
		mavenCentral()
		maven {
			name 'sonatype-snapshots'
			url "https://oss.sonatype.org/content/repositories/snapshots/"
		}
		jcenter()
	}
	dependencies {
		  classpath files("/home/anhxa/tmpdir/build-tools-5.0.0-20160613.145150-483.jar") 
	}
}
```

 3. What am I missing here? What do I have to do in order to make the file dependency described in step 2 work properly? Many thanks for your help!
```
**Error logs**: * What went wrong:
A problem occurred evaluating root project 'example-plugin'.
\> Failed to apply plugin [id 'carrotsearch.randomized-testing']
   \> Could not create task of type 'RandomizedTestingTask'.
```

**Comment by nik9000** [comment]
I'm tentatively marking this as a build bug.

I'm not sure what is wrong - could you run gradle with `--stacktrace` and `--debug --stacktrace` and post both as a gist? It is hard to tell what is up from here.

**Comment by matzischatzi** [comment]
Thank you for your prompt reply! 

As you suggested, I already created a gist including stacktrace.txt and debug_stacktrace.txt:

https://gist.github.com/matzischatzi/866c5fe657c16c73b205780752997118

**Comment by nik9000** [comment]
Ah! I should have realized. It says it can't create `com/carrotsearch/ant/tasks/junit4/SuiteBalancer which makes sense because that isn't part of Elasticseach's built - it is a dependency *of* Elasticsearch's build. And including the project dependency gets you our build's dependencies. But including the file dependency doesn't. So, yeah, file isn't going to work unless you resolve the dependencies yourself. [This](https://github.com/elastic/elasticsearch/blob/master/buildSrc/build.gradle#L86) is the current list of the build dependencies.
