### ISSUE TITLE
Currently available elasticsearch build-tools and elasticsearch binaries do not match the current source code on github

### ISSUE THREAD

**Issue by matzischatzi** [elastic/elasticsearch#19368]
**Elasticsearch version**: 5.0.0-alpha5-SNAPSHOT

**JVM version**: jdk 1.8.0_91

**OS version**: Ubuntu 14.04 LTS

**Description of the problem including expected versus actual behavior**:

The currently available elasticsearch build-tools and elasticsearch binaries do not match the current source code on github

**Steps to reproduce**:
 1. I've downloaded the elasticsearch source code from https://github.com/elastic/elasticsearch

 2. Then I tried to build a simple elasticsearch plugin using the RestHandler interface. According to the source code, I have to implement the following method: 
     void handleRequest(RestRequest request, RestChannel channel) throws Exception;

 3. To build the above elasticsearch plugin, I used the version "5.0.0-alpha5" for the elasticsearch build-tools as well as for elasticsearch itself (see the build.gradle attached below). 
[build_gradle.txt](https://github.com/elastic/elasticsearch/files/357774/build_gradle.txt)

 4.  Regarding the RestHandler interface, there apparently is a difference between the elasticsearch source code on github and in the repository https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/gradle/build-tools/5.0.0-alpha5-SNAPSHOT/
Therefore, I always get the error message displayed in logs.

 5. How do I get elasticsearch build-tools and elasticsearch binaries which match the current source code on github? Many thanks in advance for your help!

**logs**: ...src/main/java/org/elasticsearch/plugin/example/HelloRestHandler.java:8: error: HelloRestHandler is not abstract and does not override abstract method handleRequest(RestRequest,RestChannel,NodeClient) in RestHandler

**Comment by jasontedor** [comment]
The Elasticsearch codebase is an incredibly fast moving target, and even the SNAPSHOT builds off of master can lag behind by several hours and sometimes longer (from the time the commit moves through the CI pipeline to a successful build to the repository publishing job).

> Then I tried to build a simple elasticsearch plugin using the RestHandler interface. According to the source code, I have to implement the following method: 
void handleRequest(RestRequest request, RestChannel channel) throws Exception;

That interface changed on 2016-06-29, I do not think that you're up to date on the latest commits in master.
