### ISSUE TITLE
Change Deprecated REST Handler prefix to be more granular

### ISSUE THREAD

**Issue by djschny** [elastic/elasticsearch#19377]
**Elasticsearch version**: master (v5.0.0)

**JVM version**: n/a

**OS version**: n/a

**Describe the feature**:

Recently a deprecation warning response header was added as part of https://github.com/elastic/elasticsearch/pull/17804 and /elastic/elasticsearch/issues/17687

The [prefix used](https://github.com/elastic/elasticsearch/pull/17804/files#diff-a2f8f23221b079e15cfc451728820f92R40) is `Warning:` however this is not really granular enough to make it useful.

For example to really get the full benefit of this running packetbeat on Elasticsearch nodes indexing the rest requests would be ideal. Then dashboards could be built in Kibana showing the top X URL paths that have deprecations, etc. However since these are grouped under the common/generic `Warning:` header it is less than ideal as one would need to do a query on the word "deprecation" in the text of the header. If something like `X-Elasticsearch-Deprecation` was used it would make it very easy to filter and also future proofs if other non-deprecation warnings are added in the future.

**Comment by clintongormley** [comment]
I think you're misunderstanding the purpose of the deprecation headers.  Deprecation headers are intended to alert the USER that the request that they have just run uses deprecated functionality (ie it provides the context to the user). As such, the official `Warning:` header is perfect for the purpose.

We also have deprecation logs, which provide the SYSADMIN with information that users are using deprecated functionality (but with less context).  If you wanted to make graphs out of deprecations, then consuming the deprecation logs would be the way to go.

However, making graphs out of how many different types of deprecations there are really doesn't help much.  What you want to know is that there is NO use of deprecated functionality, as it will break in the next major version.
