### ISSUE TITLE
[feature request]bound some settings to alias

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#19379]
**Describe the feature**:
let's say I have a index and it has 2 aliases: index_r and index_w, one for read and one for write.
if it can bound some index settings to alise, that would be good.

curl -XPOST 'http://localhost:9200/_aliases' -d '
{
    "actions" : [
        {
            "add" : {
                 "index" : "index",
                 "alias" : "index_r",
                 "settings" : {
                      "index.blocks.read_only" : "true"
                   }            
              },
              "add" : {
                 "index" : "index",
                 "alias" : "index_w",
                 "settings" : {
                      "index.blocks.read" : "true",
                      "index.blocks.metadata" : "true"
                   }            
              }

        }
    ]
}'

with this bound, a better data reindex service can be provieded

**Comment by clintongormley** [comment]
Aliases belong to an index, as do these settings.  They don't exist outside an index, so there is nowhere to put settings like these which only apply to the alias.  You need a proxy or other security solution which implements these controls

**Comment by makeyang** [comment]
@clintongormley  don't hurry to close issue. 
so my question is: will ES introduce the notation of "view"? alias and settings bound together to form a view?

**Comment by clintongormley** [comment]
no
