### ISSUE TITLE
Allow access to Lucene field infos via API

### ISSUE THREAD

**Issue by sfussenegger** [elastic/elasticsearch#1938]
At times it's interesting to get an overview over the created Lucene fields while working with compolex mappings. This info could be added to the index status API.

When opening an index with [Luke](http://code.google.com/p/luke/) it immediately shows a list of fields with corresponding term counts. That would certainly be a good starting point.

**Comment by clintongormley** [comment]
@sfussenegger are there still stats that you're after than aren't already exposed via other APIs?

**Comment by sfussenegger** [comment]
@clintongormley I haven't followed elasticsearch development as closely for the last two years, so I really don't know what is available by now. So as far as I'm concerned you can close this issue.

**Comment by clintongormley** [comment]
thanks @sfussenegger
