### ISSUE TITLE
New type always adds a _parent#null field if no _parent mapping specified

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#19389]
```
PUT test 
{
  "mappings": {
    "type": {
      
    }
  }
}

GET test/_mapping/field/*
```
results in:

```
...
        "_parent#null": {
          "full_name": "_parent#null",
          "mapping": {}
        }
...
```

**Comment by brwe** [comment]
Pushed a test for that too since I had one already.

**Comment by martijnvg** [comment]
I was concerned that the ParentFieldMapper also adds a `_parent#null` doc values field in this case. Luckily this is not the case. The `_parent#null` field only exists in the mapping, but it isn't doing anything.

**Comment by jpountz** [comment]
@martijnvg was the `_parent#null` field only visible with the get field mapping API, or also with the mappings API?

**Comment by clintongormley** [comment]
Only with the get-field-mapping API.  Doesn't that mean that it is a real Lucene field?

**Comment by jpountz** [comment]
No, it only means that this field can be looked up by name in the mappings.

**Comment by martijnvg** [comment]
@jpountz Yes, only the get-field-mapping api. Also I verified that no such field was actually added to the Lucene index.
