### ISSUE TITLE
feature request ES 5: Add parameter "copy_to" to fieldtype "percolator"

### ISSUE THREAD

**Issue by mumpi** [elastic/elasticsearch#19382]
**Describe the feature**:

ES 2 indexes the content of a percolator query object to "_all". That is useful for an application to maintain percolators. 

The ES 5 field type "percolator" is not indexed to "_all" neither does it allow the "copy_to" parameter, nor could I copy another object field to a percolator type field.

"query.extracted_terms" did not show any hits for what I tried. (I use "query_string" queries).

So from my perspective the "copy_to" parameter in a percolator field would be the most versatile solution.

Thank you.

**Comment by clintongormley** [comment]
As far as i can tell, ES2 doesn't index the contents of the query into the `_all` field which makes sense, as the `query` field is disabled --  it isn't even parsed:

    PUT t 
    {
      "mappings": {
        "t": {
          "properties": {
            "foo": {
              "type": "string"
            }
          }
        }
      }
    }
    
    PUT t/.percolator/1
    {
      "query": {
        "match": {
          "foo": "bar"
        }
      },
      "one": "two"
    }
    
    GET t/.percolator/_search
    {
      "aggs": {
        "all_field": {
          "terms": {
            "field": "_all",
            "size": 10
          }
        }
      }
    }


This returns:

    "all_field": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "two",
          "doc_count": 1
        }
      ]
    }

The `copy_to` parameter wouldn't help here either, as you can't copy an object to a `text` field.

In 5.0, the `query.extracted_terms` includes the extractable terms in the format `field\0term`, so eg this works:

    PUT t 
    {
      "mappings": {
        "t": {
          "properties": {
            "foo": {
              "type": "text"
            },
            "query": {
              "type": "percolator"
            }
          }
        }
      }
    }
    
    PUT t/t/1
    {
      "query": {
        "match": {
          "foo": "bar"
        }
      }
    }
    
    GET t/t/_search
    {
      "query": {
        "match": {
          "query.extracted_terms": "foo\u0000bar"
        }
      }
    }

But I realise that this may not be the most useful format for your purposes. Honestly, I think the best solution is for you to extract the terms you want indexed yourself, and to add them as metadata.

**Comment by mumpi** [comment]
There might be another way round: For My EL 2 percolator I set a mapping 
...
       "query": {
            "type": "object",
            "enabled": true
        }
...
This seems responsible for indexing the query. A listing of the actual mapping shows:


`          "query": {
            "properties": {
              "query_string": {
                "properties": {
                  "default_field": {
                    "type": "string"
                  },
                  "default_operator": {
                    "type": "string"
                  },
                  "minimum_should_match": {
                    "type": "string"
                  },
                  "query": {
                    "type": "string"
                  }
                }
              }
            }
          },
`

So - instead of applying "copy_to" to the percolator type field why not start from the object type and "copy_to" the percolator type? (I tried; but ES 5 refused).

**Comment by martijnvg** [comment]
> (I tried; but ES 5 refused).

This is because the percolator from 5.0 now only works if a field of type `percolator` has been configured, whereas before an `object` field was required.

**Comment by clintongormley** [comment]
> This seems responsible for indexing the query. A listing of the actual mapping shows:

Yes, but you also end up creating lots and lots of indexed fields, some of which might end up causing mapping conflicts later on.  This is a no-go.

**Comment by mumpi** [comment]
hmm, i see. But instead of defining the query as "object" and "enable" it I could also specify the required properties / subproperties for - in my sample - the "query_string" query.

And then "copy_to" the "percolator" type

**Comment by clintongormley** [comment]
@mumpi reread my comment https://github.com/elastic/elasticsearch/issues/19382#issuecomment-232014634 where I explain why this is a bad idea (even though it may have worked in your situation).

I don't think there is anything we can do here, so I'm going to close

**Comment by mumpi** [comment]
Thank you for your effort.
