### ISSUE TITLE
Deprecate and eventually remove template query?

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#19390]
The search template api can template the entire search request, so I think that should be preferred over the `template` query. I can't think of a good templating use case right now that only the `template` query can be used, so lets deprecate and remove this query?

**Comment by polyfractal** [comment]
++

It's also confusing because the syntax is only subtly different from the template search request.  I was just helping a user on the forums who was confused why their `"size"` parameter wasn't being applied.  Turns out they were using a template query instead of template search request on accident.

**Comment by s1monw** [comment]
I wonder if that has an impact on https://github.com/elastic/elasticsearch/issues/19195 which might eventually want to run template queries rather than template requests? for the metrics to evaluate queries we want to be in charge of the search request the user should only specify the query?

**Comment by martijnvg** [comment]
@s1monw I would expect that the ranking evaluation API is supposed to work with actual concrete user queries rather than templated queries? I can imagine that if templating is wanted then maybe also the set of search results should be templatable (or just the entire request)? 

If templating is required for other APIs too then we can think of a way to support this in general? For example maybe if the url path ends with `_template` the requests gets redirected to the template api first, templating happens and then the request is redirected to the target API. 

Today the validate query and the explain APIs are the only APIs that allow specifying a query and these APIs would then lose the ability to template if `template` query were to be removed. I think that this fine, because these are debug APIs. In the case a query needs to be explained that sits in file or stored template then one can use the template render api to resolve that, extract the query bit from the rendered request and then execute the explain api.

**Comment by s1monw** [comment]
> @s1monw I would expect that the ranking evaluation API is supposed to work with actual concrete user queries rather than templated queries? I can imagine that if templating is wanted then maybe also the set of search results should be templatable (or just the entire request)?

that is not true - usually these APIs work with the user input and a template - if you bind your evaluation to a specific way how to query the API is useless. You use that for experiments so you just wanna change the template not the input data for the query. its the same reason why logging queries is useless, all you need is the data to build the query ie. the user input from the application layer

**Comment by martijnvg** [comment]
Thanks for explaining. I didn't exactly know how the evaluation API should work. So just to be sure the ranking evaluation request will hold a template that is used by all the specified queries to be evaluated?

**Comment by s1monw** [comment]
I want @MaineC and @cbuescher to comment here too before we make a move

**Comment by clintongormley** [comment]
> You use that for experiments so you just wanna change the template not the input data for the query. 

This would still be feasible with a search template rather than a query template.  We could evaluate the search template first, then make any changes we wanted to make on top of that, no?

**Comment by s1monw** [comment]
> This would still be feasible with a search template rather than a query template. We could evaluate the search template first, then make any changes we wanted to make on top of that, no?

I think this is a huge hassle, we would need to embed it ourself. we can try this but I want this to be  tested before we delete this feature.

**Comment by s1monw** [comment]
@martijnvg just explained me that we use could just use a script to evaluate to a string instead of a template query inside a search template, similar to what suggest collate does. I think that makes sense so I think we can just move forward here. +1

**Comment by MaineC** [comment]
Sounds like a good plan to me (with the caveat that I don't know exactly how suggest collate works).

**Comment by martijnvg** [comment]
@MaineC It is basically a query that runs to verify if a candidate suggestions actually yields documents. The collate query can be specified as mustache script and the candidate suggestion is available here as a variable. Makes sense?
