### ISSUE TITLE
Using script_fields turns off _source retrieval

### ISSUE THREAD

**Issue by Bargs** [elastic/elasticsearch#19403]
**Elasticsearch version**: master (6861d35)
**JVM version**: 1.8.0_60
**OS version**: OSX 10.11.4

**Description of the problem including expected versus actual behavior**:

I recently discovered in Kibana master that creating a script field prevents other fields from loading on the Discover tab  https://github.com/elastic/kibana/issues/7699. The problem is that when `script_fields` is present in the query body, `_source` is no longer returned for each hit. Nothing has changed in the Kibana query as far as I can tell, so I think this is a change in behavior for ES.

**Steps to reproduce**:
 1. Execute a query without `script_fields`, see that `_source` is returned by default.
 2. Execute the same query with `script_fields` (any simple script should do, but it can't just be an empty object), see that `_source` is now missing

**Comment by clintongormley** [comment]
Yes, it has always been this way.  The idea is that if you are specifying custom fields, then you don't want the full `_source`.  Turn return the `_source` with script fields, just set `?_source=true`

**Comment by Bargs** [comment]
Thanks @clintongormley, I see what changed in Kibana now. Sorry for the false alarm.
