### ISSUE TITLE
Can I solve one search request whith multi Groovy scripting file ? 

### ISSUE THREAD

**Issue by zliu789** [elastic/elasticsearch#19409]
Like the database functions .. we can use the function like to_number(to_char(...)) ， so the function is **not fixed**.

now we defined the function :
 "def abs(data) {return Math.abs(data);};";
 "def upper(data){if(data!=null){return data.toUpperCase();}else{return null}};";

and use it in script , **inline** ...like this
"script":"def abs(data) {return Math.abs(data);};def upper(data){if(data!=null){return data.toUpperCase();}else{return null}};upper(abs(doc['fieild'].value))"

so this way can make memory leak? (Es 2.3.4)

if use script file ,how can i do it ..

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
