### ISSUE TITLE
Scripted_upsert in BULK UPDATE operation

### ISSUE THREAD

**Issue by rmanu23** [elastic/elasticsearch#19413]
**Describe the feature**:

Is it possible to have the "scripted_upsert" feature in bulk update operations? 

It would be great to propose that through BULK API...

right now, I must put my document in "param" fields of the script part AND in the upsert field.

unless I'm doing something wrong...

**Comment by clintongormley** [comment]
This works just fine, eg:

    POST /test/type1/_bulk
    {"update":{"_id":1}}
    {"scripted_upsert":true,"script":{"inline":"ctx._source.counter += count","params":{"count":4}},"upsert":{"counter":1}}

**Comment by juriad** [comment]
The attribute `scripted_upsert` is not mentionedd in the documentation. That should be fixed.
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html#bulk-update
