### ISSUE TITLE
Decide how to make transport client to work with netty

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#19412]
with #19411 and #19392 the transport client must add the netty module explicitly otherwise networking won't work. Today folks need to add the plugin explicitly on the builder, this might be cumbersome and we might want to add some magic to load it automatically if it's on the classpath. We should at least document it and throw appropriate exceptions.

**Comment by s1monw** [comment]
one way of doing this would be a stand-alone project called `client/transport-client` that depends on `core` as well as `transport-netty` that adds the plugin by default. I think that would be the best separation here. Another idea is to move the transport client into it's own project entirely that depends on core and netty but is pulled in from `test/framework` to cycle it in tests as we do today. I think we have to keep that feature (testing it with core) otherwise there are too many sources of bugs and I am hesitating in investing too much into it. @rjernst WDYT

**Comment by rjernst** [comment]
Creating `client/transport-client` sounds right to me. Having it just depend on core and transport netty sounds ok as a first cut. We can try moving the actual TransportClient class into there as a followup.

**Comment by s1monw** [comment]
lets do that then

**Comment by dadoonet** [comment]
++ moving the TransportClient to its project is cleaner IMHO.

**Comment by nik9000** [comment]
If you make client/transport-client maybe it should include a few modules
by default: reindex, mustache, percolator, stuff like that. That way users
of those built in features don't need to do special stuff.
