### ISSUE TITLE
Why was setPercolateFiler method removed form percolate request (Java Api)

### ISSUE THREAD

**Issue by Aleksandr-Filichkin** [elastic/elasticsearch#19429]
I'm migrating form ElasticSearch 1.3 to 2.3.2 I see that Java API was changed for Percolate stuff. I used filter for percolated document like this:

request.setPercolateFilter(filter);
New API doesn't have such method. Filter is not supported for percolator. I see only such stuff

request.setPercolateQuery(filterQuery);
Documentation says that we can use filter, but api doesn't have it.

What was the reason to remove filter from percolator?
Does query have the same performance as filter?

**Comment by dadoonet** [comment]
Please ask questions on discuss.elastic.co.

Filters and queries have been merged in 2.0. Read 2.0 breaking changes doc
