### ISSUE TITLE
Broken link at Documentation > Ingest node > Grok processor

### ISSUE THREAD

**Issue by mostolog** [elastic/elasticsearch#19430]
Hi

Website documentation for ingest [node-grok processor](https://www.elastic.co/guide/en/elasticsearch/reference/master/grok-processor.html) and [github page](https://github.com/elastic/elasticsearch/blob/master/docs/reference/ingest/ingest-node.asciidoc#grok-processor) aswell have a broken link at "[**120 reusable patterns**](https://github.com/elastic/elasticsearch/tree/master/modules/ingest-grok/src/main/resources/patterns)"

**Comment by martijnvg** [comment]
Thanks @mostolog, it should be fixed when the docs have been rebuild.

**Comment by mostolog** [comment]
Thanks
