### ISSUE TITLE
Should the Elasticsearch packages configure respawn?

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#19438]
After #19272, Elasticsearch instances will now die after hitting a fatal error (e.g., out of memory error). The breaking changes documentation associated with this change includes the note:

> Operators should consider configuring their Elasticsearch services so that they respawn automatically in the case of such a fatal crash.

The question put forth here is: should the Elasticsearch packages attempt to configure this? The challenge here is that this is not straightforward on System V init-based systems (`/etc/inittab`) but it is straightforward on systemd-based systems.

Marking this as [discuss](https://github.com/elastic/elasticsearch/labels/discuss).

**Comment by jasontedor** [comment]
We discussed this during Fix-it-Friday. We will configure respawn for systemd-based systems. We will investigate providing respawn for the System V init-based systems, but since most Linux systems are migrating to sytsemd, we will accept inconsistency if providing it for System V init-based systems is onerous. We will also need to investigate the possibilities on Windows, can @elastic/microsoft help here?

**Comment by Mpdreamz** [comment]
Windows allows service to be recover from failures quite elaborately:

![image](https://cloud.githubusercontent.com/assets/245275/16869979/ab788e28-4a7f-11e6-830b-e314c35e9d24.png)

Options also available on the command line, I'll cross reference this issue on the windows installer repos so we can ship with this OOB and try to allign with the *nix packages.

**Comment by jasontedor** [comment]
@Mpdreamz Right, the question is whether or not it's possible to build the installer to configure this automatically on installation.

**Comment by Mpdreamz** [comment]
Thats what I meant with shipping with this feature out of the box, yes it should be possible to configure this automatically during installation.

**Comment by jasontedor** [comment]
> Thats what I meant with shipping with this feature out of the box, yes it should be possible to configure this automatically during installation.

+1

**Comment by russcam** [comment]
+1 - can be configured with sc.exe

**Comment by jasontedor** [comment]
Duplicates #25425
