### ISSUE TITLE
Add combo analysis to core analysis plugins

### ISSUE THREAD

**Issue by moskiteau** [elastic/elasticsearch#19449]
The combo analysis plugin is not maintained anymore and it's quite usefull and necessery for multilingual indexes. This plugin should be moved to core and maintened by elastic.

https://github.com/yakaz/elasticsearch-analysis-combo
https://github.com/yakaz/elasticsearch-analysis-combo/pull/21

Thank you

**Comment by clintongormley** [comment]
This was already proposed in https://github.com/elastic/elasticsearch/issues/1169 and we decided not to offer this plugin as it is a much better approach to use multiple fields with different analyzers instead of a single field with a mish-mash of tokens.

**Comment by moskiteau** [comment]
Could you reference some literature?

**Comment by clintongormley** [comment]
I can't, but I can tell you that Lucene's analysis streams are designed to operate on a single field, with a single analyzer. Mixing up analyzers is likely to give you broken offsets and positions which could prevent indexing or result in run time exceptions with eg the FVH.

On top of that, you're messing with term statistics by creating duplicate terms for tokens which analyse identically, so the relevance calculation will be poor. 

Lastly, you don't actually save much space compared to having a field per analyzer.  And even if you do today, things may well change tomorrow as Lucene adds optimisations for its primary use case.
