### ISSUE TITLE
Allow dots in field names for mappings API

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#19443]
The dots in fieldnames work for 5.0 was for dynamic fields and document parsing. But we still need to add support for specifying dots in fieldnames in mappings apis. This is less troublesome to users as dynamic mappings (where sometimes the source field name cannot be controlled), but still a pain to deal with.

**Comment by jpountz** [comment]
Do you mean that a mapping like this:

```
{
  "properties": {
    "a.b": {
      "type": "keyword"
    }
  }
}
```

should be parsed as:

```
{
  "properties": {
    "a": {
      "type": "object",
      "properties": {
        "b": {
          "type": "keyword"
        }
      }
    }
  }
}
```
?

**Comment by rjernst** [comment]
@jpountz Yes, exactly.

**Comment by jpountz** [comment]
Discussed with @rjernst and @colings86, it seems that we could do it reasonably easily by pre-processing the map that stores the mapping it DocumentMapperParser.
