### ISSUE TITLE
the inconsistency of java files and class files in elasticsearch-1.4.4

### ISSUE THREAD

**Issue by Abbyli** [elastic/elasticsearch#19465]
To whom it may concern,
I downloaded java files and class files of elasticsearch-1.4.4, and found several java files missing, such as files in path org\elasticsearch\common\cli, org\elasticsearch\common\lang3, org\elasticsearch\common\compress and org\elasticsearch\common\annotations. 
Why did that happen?

**Elasticsearch version**: 1.4.4

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
