### ISSUE TITLE
Is there a security vulnerability associated with "mustache templating"?

### ISSUE THREAD

**Issue by Jack-Collins** [elastic/elasticsearch#19468]
It seems like this is basically a direct substitution mechanism into a preset template. So in theory if somebody knew what they were doing, couldn't they alter the intended purpose of a template through some carefully thought-out JSON-injection?

Not sure if this belongs here but was something that occurred to me as a potential security bug and wanted to get some feedback on it.

thanks

**Comment by rmuir** [comment]
probably :)

I do not know why this one is assumed to be safe.

**Comment by hub-cap** [comment]
We have a new way to report potential vulnerabilities, and it is explained [here](https://www.elastic.co/community/security). If you feel there is a concrete violation you have found, please report it. Im CC'ing @elastic/security so they are aware of the closing of this issue.
