### ISSUE TITLE
date histogram doc count with interval day is correct, but giving more doc count with hour

### ISSUE THREAD

**Issue by dks007** [elastic/elasticsearch#19463]
Hi ,
  I am writing query to find hourly count with some filter: 
date histogram doc count with interval day is correct, but giving more doc count with hour

For example my query with interval day:

    GET _search
    {
      "size": 0,
      "aggs": {
        "eventtime": {
          "filter": {
            "bool": {
              "must": [
                {
                  "term": {
                    "RW.RT": "152"
                  }
                },
                {
                  "term": {
                    "RW.RE": "received"
                  }
                }
              ]
            }
          },
          "aggregations": {
            "timeslice": {
              "date_histogram": {
                "field": "RW.DT",
                "interval": "day",
                "format": "YYYY-MM-dd HH:MM:ss",
                "min_doc_count": 1
              }
            }
          }
        }
      }
    }

Output is : 

    "hits": {
      "total": 147,
      "max_score": 0,
      "hits": []
    },
    "aggregations": {
      "eventtime": {
         "doc_count": 6,
         "timeslice": {
            "buckets": [
               {
                  "key_as_string": "2016-07-14 00:07:00",
                  "key": 1468454400000,
                  "doc_count": 6
               }
            ]
         }
      }
      }

This is ok..but when i change interval with hour ..
Output is 

    "hits": {
      "total": 147,
      "max_score": 0,
      "hits": []
    },
    "aggregations": {
      "eventtime": {
         "doc_count": 6,
         "timeslice": {
            "buckets": [
               {
                  "key_as_string": "2016-07-14 07:07:00",
                  "key": 1468479600000,
                  "doc_count": 1
               },
               {
                  "key_as_string": "2016-07-14 08:07:00",
                  "key": 1468483200000,
                  "doc_count": 2
               },
               {
                  "key_as_string": "2016-07-14 09:07:00",
                  "key": 1468486800000,
                  "doc_count": 4
               },
               {
                  "key_as_string": "2016-07-14 12:07:00",
                  "key": 1468497600000,
                  "doc_count": 1
               },
               {
                  "key_as_string": "2016-07-14 13:07:00",
                  "key": 1468501200000,
                  "doc_count": 1
               }
            ]
         }
      }
     }

Here in output doc count is  9, this should be 6 
Please help me

**Comment by clintongormley** [comment]
Your date format is using `MM` for minutes, instead of `mm`

**Comment by dks007** [comment]
Thank u for comment clintongormley , but format is not an issue.. i did that...format is just for displaying if u need any specific kind of format...No of doc count is difference in in case of hour but in case of day it is ok...Please see above query.

**Comment by clintongormley** [comment]
That's true. In which case, (and you haven't provided example docs) but it looks like you have multiple values per doc in that field.  If you use the [value count](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-valuecount-aggregation.html) agg this will work as you expect.

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
