### ISSUE TITLE
MacAddressProvider munged mac address is random and unrelated to mac address

### ISSUE THREAD

**Issue by hao5ang** [elastic/elasticsearch#19479]
**Elasticsearch version**: 2.3.4

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

I find [TimeBasedUUIDGenerator.java](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/TimeBasedUUIDGenerator.java) use mac adress to identify current machine([MacAddressProvide.java](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/MacAddressProvider.java)). But it XOR the mac adress with random bytes . As I know this will make the mac address to really random and increase the probability of conflict. 

I'm not sure how to fix it. If we use mac adress directly, we should start only one process in one machine. Maybe add the process id factor will fix it. Add the process id factor can not solve the situation of start services with threads(Such as Tomcat. Tomcat serve multi webapps with same process? I think this will not happen in ES service ).

**Comment by jpountz** [comment]
Why would it increase the probability of conflict?

**Comment by hao5ang** [comment]
Mac address is unique, but the munged address is random. We have possibility of 1/2^48 to conflict if we deploy 2 nodes.

**Comment by jpountz** [comment]
This is true. We need to xor the mac address so that two nodes that are started on the same physical machine do not generate the same identifiers (since they would see the same mac address). 1/2^48 is a very low probability but it is true that as more nodes get added to the cluster, the probability of collisions increases quickly. For instance, in the case of a 1000 nodes cluster, the probability of a collision is ~2*10^-9.

**Comment by jpountz** [comment]
After discussing it a bit with @mikemccand , the current probability is probably low enough to be acceptable, especially given that ids need to be unique per index, so `min(num_nodes, number_of_replicas)` (the number of distinct nodes that hold a shard of the same index) is more relevant that the number of nodes here. Eg. the probability is ~1.6*10^-13 for 10 shards.

**Comment by hao5ang** [comment]
Yes, the probability is really low. I think we can also just use random bytes directly because the munged mac address has no relationship with the mac address.
