### ISSUE TITLE
Add option to specify custom data directory with gradle run command

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#19474]
When developing a feature it is very useful to be able to stop and start Elasticsearch multiple times while maintaining the same data directory. This lets you make changes to the feature whilst still being able to test your changes quickly without having to reload whatever dataset each time.

Currently the `gradle run` command starts up a completely fresh cluster with a blank data directory which I think is absolutely the right default behaviour. However it would be good to have a option such as `--data /absolute/path/to/data/directory` which sets the data directory to your custom path.

Bonus points if you can also specify a custom `elasticsearch.yml` file to use so you can enable options like CORS etc. on the cluster.

**Comment by javanna** [comment]
I guess it wouldn't be possible or maybe it is too much to just let it accept whatever option our startup script accepts? I think @bleskes was looking for something similar just the other day.

**Comment by bleskes** [comment]
I was looking for an option to run ES from the IDE with full config control via the command line (as one starting ES would normally have). Not the same :)

**Comment by rjernst** [comment]
I opened #29102

**Comment by rjernst** [comment]
This can be achieved with `-Dtests.es.path.data=</path/data>`

**Comment by colings86** [comment]
@rjernst this is great, thanks for pushing this change
