### ISSUE TITLE
Deleted index is coming live again 

### ISSUE THREAD

**Issue by aloneldi** [elastic/elasticsearch#19477]
**Elasticsearch version**:
2.2
**JVM version**:
1.8
**OS version**:
debian 8.4
**Description of the problem including expected versus actual behavior**:
Cluster with 3 nodes . Data is being pushed to node 1 in the cluster in bulk => total count 1 million .
After bulk operation complete shutting down node 1 .
Running query to count docs the number is the same as before node 1 shutdown 1 million.
deleting the index .
Counting the number of docs once again => no data
starting node 1 => there are docs but less then 1 million (~800k) .

The expected results is to have none . The join node should get sync with the current master .

**Steps to reproduce**:
 1. 3 nodes cluster pushing data in bulk using the current master node IP 
 2. stop the master node 
 3.delete the index
4. start the previous master node 
5. The index have data again but not as its original count 

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by s1monw** [comment]
fixed by https://github.com/elastic/elasticsearch/issues/18249 - we import data in 2.x as we find it. it's a problem but a known and fixed one. thanks for opening the issue

**Comment by aloneldi** [comment]
in which 2.x is it fixed ? 2.3 ? I'm running 2.2 .

Thanks

Alon

**Comment by bleskes** [comment]
@aloneldi the fix is 5.0 only sadly - the fix is quite tricky and will not be ported to 2.x. 

PS. you can see that reflected by the labels in the #18249 . Also check the corresponding PR, https://github.com/elastic/elasticsearch/pull/18250 for some extra background and discussion (if you want)
