### ISSUE TITLE
Invalid JSON returned when highlight query is not found in escaped content

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#19485]
Found in 1.7, confirmed in 2.3.3

To repro:

```
POST test-index/shakespeare/1
{
  "play_name": "Henry IV",
  "speech_number": 1,
  "text_entry": "{\"content\":\"March all one way and be no more opposed\"}"
}

GET /test-index/_search
{
  
 "size" : 10,
 "query" : {
   "match" : {
     "speech_number" : {
       "query" : "1"
     }
   }
 },
 "highlight" : {
   "tags_schema" : "styled",
   "fields" : {
     "text_entry" : {
       "number_of_fragments" : 0,
       "highlight_query" : {
         "match" : {
           "text_entry" : {
             "query" : "textstring"
           }
         }
       },
       "no_match_size" : 100000000
     }
   }
 }
}
```

If the highlight query includes text present in the document, the results will be properly formatted.  If the text is not present, the highlight return block looks like:

```
        "highlight": {
          "text_entry": [
            "{\"content\":\"March all one way and be no more opposed"
          ]
        }
```

Not sure this is an actual JSON formatting error as the braces are contained within a quote, but in any case the closing brace should not be dropped.

**Comment by seang-es** [comment]
Also happens with XML content:

```
POST test-index/shakespeare/2
{
  "play_name": "Henry V",
  "speech_number": 2,
  "text_entry": "<Script><text>March all one way and be no more opposed</text></Script>"
}

GET /test-index/_search
{
  
 "size" : 10,
 "query" : {
   "match" : {
     "speech_number" : {
       "query" : "2"
     }
   }
 },
 "highlight" : {
   "tags_schema" : "styled",
   "fields" : {
     "text_entry" : {
       "number_of_fragments" : 0,
       "highlight_query" : {
         "match" : {
           "text_entry" : {
             "query" : "finance"
           }
         }
       },
       "no_match_size" : 100000000
     }
   }
 }
}
```

**Comment by clintongormley** [comment]
You can never rely on valid JSON, XML, HTML, etc being returned from a highlighting request. For example:

    PUT t/t/1
    {
      "text": "<p>one <b>two three four five six seven eight nine ten five six seven eight nine ten five six seven eight nine ten five six seven eight nine ten five six seven eight nine ten five six seven eight nine ten five six seven eight nine ten five six seven eight nine ten five six seven eight nine ten five six seven eight nine ten five six seven eight nine ten</b></p>"
    }
    
    GET _search
    {
      "highlight": {
        "fields": {
          "text": {
            "highlight_query": {
              "match": {
                "text": "one two"
              }
            }
          }
        }
      }
    }

returns:


        "highlight": {
          "text": [
            "<p><em>one</em> <b><em>two</em> three four five six seven eight nine ten five six seven eight nine ten five six seven"
          ]
        }

As for why `no_match_size` is dropping the final `}` or `>`, it's because it is using the character offsets returned by the analyzer to determine the end of the text.  

This example:

    PUT t/t/1
    {
      "text": "one two three!!!!!"
    }

    PUT t/t/2
    {
      "text": "three four five!!!!!a"
    }
    
    GET _search
    {
      "highlight": {
        "fields": {
          "text": {
            "highlight_query": {
              "match": {
                "text": "foo"
              }
            },
            "no_match_size": 1000
          }
        }
      }
    }

returns highlights `one two three` and `three four five!!!!!a`

Curiously, searching for `three` DOES include the trailing punctuation:`one two <em>three</em>!!!!!` and `<em>three</em> four five!!!!!a`.

Potentially we could make these two cases use the same logic.

**Comment by markharwood** [comment]
Closing, as per @clintongormley comments. Highlighting has never attempted to preserve any valid markup contained in the text it is highlighting because this is too complex and not compatible with the goals of summarising text.

**Comment by markharwood** [comment]
One suggestion though - for structured text consider storing it not as a blob of marked-up text but instead as regular JSON e.g. an array of "chapter" objects each of which have text fields. Then consider indexing using `nested` documents and the `inner_hits` query to select the best chapters that match your text query.
