### ISSUE TITLE
Rollover API Numbering not honouring preceding zeroes

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#19484]
Elasticsearch Rollover API tested on ES 5.0-alpha4

Tested as shown in documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-rollover-index.html

```
PUT /roll_me_over-0001
{
  "aliases": {
    "roll_me_over": {}
  }
}

POST roll_me_over/_rollover 
{
  "conditions": {
    "max_age":   "1m"
  }
}
```
Docs state that naming will follow the same pattern:

> If the name of the existing index ends with - and a number — e.g. logs-0001 — then the name of the new index will follow the same pattern, just incrementing the number (logs-0002).

But instead:

```
yellow open   roll_me_over-0001             5   1          0            0       650b           650b
yellow open   roll_me_over-2                5   1          0            0       260b           260b
```

**Comment by clintongormley** [comment]
I think we should respect the zero padding as it makes for easier sorting, but then if we rollover to a number higher than allowed with the padding we should do what we do today (ie just increment)

**Comment by s1monw** [comment]
do we have to auto-detect this? can't we ask the user to provide this with the request and have a default there?

**Comment by areek** [comment]
I agree with @s1monw here, we can already supply a name for the new index vi `POST /roll_me_over-0001/_rollover/roll_me_over-0002` where `roll_me_over-0002` is the new index name. IMO, it would be simpler to just increment the old index name not respecting zero padding (current behaviour) and let the user provide the new index name if a simple increment is not enough?
Though, the example in the docs is misleading here, I will adapt it to ensure the above is clear?
@clintongormley WDYT?

**Comment by s1monw** [comment]
another option is to just have a  padding all the time lets say 6 digits and we are done? `String.format` should do this for us?

**Comment by areek** [comment]
hmm, IMO having any padding at all seems arbitrary, is there any specific reason to add any padding?

**Comment by s1monw** [comment]
@areek I think people often sort the index by name for recovery order etc. so that might be the most significant one

**Comment by clintongormley** [comment]
> another option is to just have a padding all the time lets say 6 digits and we are done?

++
