### ISSUE TITLE
Allow Completion/Context Suggester to consume each token as an Input

### ISSUE THREAD

**Issue by gingerwizard** [elastic/elasticsearch#19493]
**2.x/5.x**:

Currently if configuring the completion suggester to utilise a field value for input, the text is tokenised using the configured analyzer.   The output tokens are subsequently concatenated to form a suggestion.  Only one value can therefore be loaded by this process. In order to load multiple input values for a suggestion, users are currently required to list multiple inputs.

This ticket proposes allowing a configuration option to cause each token to be consumed as a separate suggestion - rather than concatenating to form a single output.  Whilst this would need to be used with caution, as it may lead to a "bloated" FST structure, it would mean users could utilises the full capability of the analyzers chain - splitting out multiple possible inputs for matching.

**Comment by s1monw** [comment]
I have trouble to understand what you are exactly proposing but it sounds like an infix suggester. The completions suggester is a prefix suggester and we can't simply add an option to make it something else. It doesn't have any special options for the reason you mentioned since it's risky and won't really work in most of the cases either. How would you provide weights for each of the terms?

**Comment by gingerwizard** [comment]
@s1monw correct in infix observation - but it could potentially be used for more than this.  Currently we do the following to achieve infix matches:

> PUT test/documents/1
> {
>   "name": "Boeing Jets are super cool",
>   "suggest_field": {
>     "input": [
>       {
>         "input": "Boeing Jets are super cool"
>       },
>       {
>         "input": "Jets are super cool"
>       },
>       {
>         "input": "super cool"
>       }
>     ],
>     "output": "Boeing Jets"
>   },
>   "tags": "engines"
> }

As discussed, however, this would lead to potential abuse and is not a good generic addition. Closing.

**Comment by clintongormley** [comment]
For future readers, a better approach would be to use the completion suggester for the full title match case (or a couple of alternatives), and to fall back to ordinary search if no results are returned.
