### ISSUE TITLE
how to setting the default value of precision_threshold 

### ISSUE THREAD

**Issue by tonyC2016** [elastic/elasticsearch#19511]
i use elasticsearch-2.2.1,when i cardinality a field for 1 day,and use different  precision_threshold  values got a different cardinality value,in my case ,i use grafana for dash board,and  its unique count request have no feather for precision_threshold , so  i wanna to konw if  es can setting a default value for precision_threshold ,if it can ,where  is setting ,and if i set the value 400000, will it coz some bad results? most of my sence ,it is need to cardinality  operation for a field
the request json like:

```
{
    "query": {
        "filtered": {
            "filter": {
                "bool": {
                    "must": [
                        {
                            "range": {
                                "inputDate": {
                                    "gte": "1468857600000",
                                    "lte": "1468943999999"
                                }
                            }
                        }
                    ]
                }
            }
        }
    },
	 "aggs": {
        "partyId_count": {
            "cardinality": {
                "field": "getterGiftId",
                "precision_threshold": 40000
            }
        }
    }
}'
```

**Comment by jpountz** [comment]
There is no way to set the default `precision_threshold`.

>  if i set the value 400000, will it coz some bad results

Yes, counts are approximate: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html#_counts_are_approximate

**Comment by tonyC2016** [comment]
@jpountz  yes i had read the doc

**Comment by tonyC2016** [comment]
@jpountz ，yeah, another question,if there is no a default value for precision_threshold.how can es give back a not excalty metric value ,is es designed just for a real time  and threw the right result of data away?

**Comment by jpountz** [comment]
Indeed elasticsearch wants search requests to be realtime. Computing exact counts in the general case would require shards to exchange the set of values they have locally, which could be gigabytes on high-cardinality fields.
