### ISSUE TITLE
Upgrade Jackson in 2.3, 2.x branch to at least 2.7.5

### ISSUE THREAD

**Issue by roytmana** [elastic/elasticsearch#19521]
Any chance Jackson could be upgrade to at least very stable and long time ago released 2.7.5 (if not 2.8)?
Now that you do not shadow it it is conflicting with my other dependencies

**Comment by jasontedor** [comment]
No changes along these lines will be made in the 2.3 branch. There is #18939 open to upgrade master to 2.8.0, it might be backported to 2.4 but it might not and you should not count on it.

**Comment by roytmana** [comment]
ok, thanks @jasontedor
@tlrx Jackson 2.8 has been released :-)
any rough time frame when back-port to 2.4 (if it is going to happen) and 2.4 release may happen?

**Comment by jasontedor** [comment]
> any rough time frame when back-port to 2.4 (if it is going to happen) and 2.4 release may happen?

Again, a backport here is not guaranteed and we will not give a time frame, even rough. You can track the status on #18939.

**Comment by tlrx** [comment]
> @tlrx Jackson 2.8 has been released :-)

I know, thanks :) We still have to fix the way some `XContent` objects are built and it should be OK to upgrade.
