### ISSUE TITLE
Should Netty 4 be the default implementation?

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#19527]
In #19526, a Netty 4-based transport and HTTP implementation was introduced. Currently the Netty 3-based implementation is the default transport. Should the Netty 4-based implementation be the default implementation for future pre-releases of Elasticsearch 5.0.0 to ensure that we get a lot of coverage from the community on the new networking implementation? Resolving this should be a blocker for the next pre-release of Elasticsearch 5.0.0.

**Comment by rmuir** [comment]
I don't think we should use unmaintained software. Can we take the netty3 module and move it to a plugin? Maybe that way, if something goes really bad with netty4, we have an escape hatch for the user.

**Comment by s1monw** [comment]
before we make this move (I agree with rob basically) we should have some benchmark numbers, rough ones are fine so we can at least tell we are not fucking things up completely. To make netty4 default we don't need to move netty3 to a plugin, it's a setting basically we can move from netty3 to netty4 to use it as a default. We can consider keeping it as a module for a release or two to make it easy to switch between them...
