### ISSUE TITLE
Bucket aggregation for names in named queries

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#19539]
If naming query clauses is useful for adding context to individual top hits it is arguably also useful context for reviewing larger collections of results in aggregations.

My assumption is that the names of the clauses that matched each doc accompany it as it is collected so that they can be displayed in top hits. If correct, this means a new bucket agg could route docs into buckets based on these query names. I don't think this would require any special parameters in the DSL so would look something like this:

	GET ofac/_search
	{
	   "query": {
		  "bool": {
			 "should": [
				{
				   "match": {
					  "_all": {
						 "query": "chicken turkey",
						 "_name": "poultry"
					  }
				   }
				},
				{
				   "match": {
					  "_all": {
						 "query": "pork beef",
						 "_name": "meat"
					  }
				   }
				},
				{
				   "match": {
					  "_all": {
						 "query": "spaghetti penne linguine",
						 "_name": "pasta"
					  }
				   }
				}

			 ]
		  }
	   },
	   "size": 0,
	   "aggs": {
		  "clauses": {
			 "named_queries": {
			 },
			 "aggs": {
				 ....
			 }
		  }
	   }
	}

The results would show buckets keyed with the names `poultry` and `meat` etc.
An interesting twist is that a named_queries agg could be nested under another named_queries agg and the results effectively represent a weighted graph showing if poultry or meat was a more common ingredient with pasta dishes.

**Comment by jimferenczi** [comment]
> My assumption is that the names of the clauses that matched each doc accompany it as it is collected so that they can be displayed in top hits. If correct, this means a new bucket agg could route docs into buckets based on these query names. I don't think this would require any special parameters in the DSL so would look something like this:

The named queries are applied during the fetch phase on the top documents only. They are not extracted during the search phase since it's cheaper to replay the named queries on the top documents as long as the number of top hits is small. 

> An interesting twist is that a named_queries agg could be nested under another named_queries agg and the results effectively represent a weighted graph showing if poultry or meat was a more common ingredient with pasta dishes.

Are `filters` aggs not enough for this use case ?
```
{
   "aggs": {
      "clauses": {
         "filters": {
            "filters": {
               "poultry": {
                  "term": {
                     "body": "chicken turkey"
                  }
               },
               "meat": {
                  "term": {
                     "body": "spaghetti penne linguine"
                  }
               }
            }
         },
         "aggs": {
            "cooccurrence": {
               "filters": {
                  "filters": {
                     "pasta": {
                        "term": {
                           "body": "spaghetti penne linguine"
                        }
                     }
                  }
               }
            }
         }
      }
   }
}
```

**Comment by markharwood** [comment]
>The named queries are applied during the fetch phase on the top documents only

Ah - thanks, @jimferenczi that clears up some of the mystery on how the names appear :)

>Are filters aggs not enough for this use case ?

Yes, but I had assumed that the names were context in the search phase so offering them in aggs felt like a cheap by-product of running an existing query - so you could run a search for the top N docs and also get some overview of how your search concepts inter-relate.
I can see now that this isn't query data that is cheaply recycled for use in aggs so will close the issue.
