### ISSUE TITLE
gradle assemble fails

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#19535]
**Environment info**:

```
dm@io:~ $ gradle --version

------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_74 (Oracle Corporation 25.74-b02)
OS:           Mac OS X 10.11.5 x86_64
```

**Steps to reproduce**:

 1. run `gradle assemble` on the latest master

This produces:

```
:modules:lang-mustache:generatePomFileForJarPublication FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':modules:lang-mustache:generatePomFileForJarPublication'.
> Could not apply withXml() to generated POM
   > Cannot invoke method startsWith() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Additionally, I also see:

```
:distribution:deb:generatePomFileForNebulaPublication
Unable to convert null to https form in MavenScmPlugin. Using original value.
[...]
:distribution:integ-test-zip:generatePomFileForNebulaPublication
Unable to convert null to https form in MavenScmPlugin. Using original value.
[...]
:distribution:rpm:generatePomFileForNebulaPublication
Unable to convert null to https form in MavenScmPlugin. Using original value.
[...]
```

before the fatal error occurs, so it seems that some property cannot be resolved? The `lang-mustache` module is maybe just unlucky as it's the first one where a method is invoked on this null object?

**Comment by rjernst** [comment]
@danielmitterdorfer Are you trying to run this on a copy of the repo, without gradle? This works for me locally (with git), and it works in CI (we do a `build`, which includes `assemble` there). The `startsWith` that was added recently looks at the git origin, and creates a url (ie finding the github url for the repo), but if the repo has no git info, I could see this happening.

**Comment by danielmitterdorfer** [comment]
@rjernst Thanks for the pointer. That rang a bell: I have recently set up [git worktree](https://git-scm.com/docs/git-worktree) so I need to checkout the repo only once but have multiple work trees (one for each major version). I'll try tomorrow if that's the root cause (but based on your description I am already pretty sure it is...) and close the ticket then if that's the case.

@javanna has also mentioned that he has experienced this problem or did I misunderstand you?

**Comment by dakrone** [comment]
Should we add a quick check in gradle for the `.git` directory and dump a slightly more useful error message? I could see someone downloading a tarball of the source from github and seeing this without any idea what causes it.

**Comment by javanna** [comment]
I had and still have this out of master. Not sure what is wrong with my local checkout :)

**Comment by nik9000** [comment]
I usually build Elasticsearch without git - though I usually just do `gradle check`. I do this because I usually run the tests on a desktop rather than abuse my silly little Macbook Air. I don't sync the `.git` directory because it is just a bunch of binary stuff and doesn't work well with `unison`.

**Comment by danielmitterdorfer** [comment]
I did a fresh clone of the ES repo without using the git worktree feature and it works now fine. @javanna can you also freshly clone the repo and retry? If that works for you too, can you please close the ticket then?

**Comment by javanna** [comment]
With a fresh checkout of es core it works. Would it be possible to know why I need a fresh checkout? I don't think I was doing anything weird. Maybe some assumptions made in our build should be adjusted? I think we should keep the ticket open till we figured that out.

**Comment by danielmitterdorfer** [comment]
@javanna For my local checkout I am almost certain it relates to git worktree. If you use that feature, `.git` is not a directory as usual but a file that contains (on my machine):

```
gitdir: /Users/dm/Projects/elasticsearch/src/.repo/elasticsearch/.git/worktrees/elasticsearch
```

i.e. a poor man's symlink. :)

Did you keep your old checkout? Maybe your .git/config reveals something interesting.

**Comment by javanna** [comment]
ok it turns out I have this problem because my remote is not named `origin`. I can imagine others rename it too. Not sure what we need that url for, but can we change the build to not make these assumptions about git?

**Comment by nik9000** [comment]
Looks like this comes from https://github.com/nebula-plugins/gradle-info-plugin/blob/master/src/main/groovy/nebula/plugin/info/scm/GitScmProvider.groovy#L55-L64

**Comment by rjernst** [comment]
> can we change the build to not make these assumptions about git?

No,  this only happens when you do an assemble,  because it needs to build poms,  and the poms for maven central require having the URL for the repo.

**Comment by javanna** [comment]
perfect, then it will just mean a jar/pom/zip/whatever will never come out of my machine.

**Comment by javanna** [comment]
Trying to go back to nice mode :) I don't know what the background is and we may depend on some plugins that don't do the right thing. But why is "no" the only possible answer? Maybe we can evaluate alternatives? Or explain why I'm asking for the moon? 

I don't think making these assumptions is correct. Requiring git is one thing, then assuming `origin` as the right remote is another one. Maybe we can have different paths for when we need this info (CI/making a release) and when we don't. Maybe if I have to build a jar/zip locally I don't need that stuff? Again, just thinking out loud. Let me know if I can help.

**Comment by rjernst** [comment]
When I said "no", I meant that we must have the git info to build the pom. As far as "allowing other names for origin", I don't think we should write a bunch of code just to handle this edge case that is not necessary in 99.99% of cases, especially when our own release process does not need it. As far as being lenient, we could put a bogus url in there if we cannot get the git info, but fail if we are releasing (currently, that is `-Dbuild.snapshot=false`). I'm personally against this b/c I don't think we should have leniency here, but I know we already do in the case of the git info for jar metadata, so if someone wants to add that, I would not stand in the way as long as it is a hard fail for a release.

**Comment by javanna** [comment]
not too sure that renaming remotes is an edge case, that was my main point. happy to be proved wrong if I am the only one doing it. I can always rename back the remote to what it needs to be when I need to generate the jar, or leave origin around by making a copy rather than renaming it. Do others have thoughts?

**Comment by bleskes** [comment]
For what it’s worth, I would like to be able to build local zip/tars to sometime test a build and I have the elasticsearch github remote renamed from origin. If I understand correctly the requirement to have a url comes from maven. Is it maybe possible to:

1) Allow supplying a url as a parameter to the build?
2) Allow only creating a tar/zip/rpm (which don’t go to maven)? Luca, I think this is enough for you? 
3) Hard code the urls? this is the build for a elasticsearch/plugins which have a canonical urls, just like they have canonical artifact id?

**Comment by rjernst** [comment]
> 1) Allow supplying a url as a parameter to the build?

I don't think we need this flexibility.

> 2) Allow only creating a tar/zip/rpm (which don’t go to maven)? Luca, I think this is enough for you?

I've already suggested a way to have this leniency above.

> 3) Hard code the urls? this is the build for a elasticsearch/plugins which have a canonical urls, just like they have canonical artifact id?

This is part of the gradle plugin we publish from buildSrc, which allows not only our plugins to be built, but those of community plugins as well.

**Comment by bleskes** [comment]
> > 2) Allow only creating a tar/zip/rpm (which don’t go to maven)? Luca, I think this is enough for you?

> I've already suggested a way to have this leniency above.

I didn't mean building things with a fake url, but rather only building the zip file. Can you elaborate about what you mean requiring a url in the pom files? Looking at a 5.0.0-Alpha4 distro, I don't see a pom.xml file anywhere (not as a file and not in the es-5.0.0.jar). I do see a MANIFEST.MF baked into the jar, which does specify a url as `Module-Origin`. However, if I look at a 2.2.0 distro which I happen to have lying around, it doesn't have a MANIFEST.MF file, but does have a pom.xml which in turn doesn't specify any url.

**Comment by rjernst** [comment]
I'm not talking about the jar, I am talking about what goes into the distributions directory. Running gradle assemble means "assemble everything", and everything includes pom files, because that is part of what we distribute (publishing to maven).  And don't look at 2.x, we did things wrong in maven forever, and only found out about it recently with the unified release work (we were grandfathered into sidestepping the pom checks maven central has).

**Comment by bleskes** [comment]
> gradle assemble means "assemble everything"

I understand. My question was whether we can have an "assemble zip/tar files" command, which only does that and is part of the assemble everything path.

> don't look at 2.x, we did things wrong in maven forever

I'm trying to understand what we should do/are doing. I take it to mean it is not required to have a pom.xml file as part of the jar and that pom files need urls (although it seems maven doesn't enforce it as 2.x is published there). Is that what you mean?

**Comment by jasontedor** [comment]
You can build a package via `gradle :distribution:(deb|rpm|tar|zip):assemble` and it works whether or not you're in a real repository or a worktree, and whether or not your remote is named elastic/origin/upstream.

I think the belief that the remote should be named `origin` is too far, this is clearly impacting a lot of people. If you follow the GitHub guidelines for [contributing](https://guides.github.com/activities/contributing-to-open-source/#contributing) you'll [eventually](https://help.github.com/articles/syncing-a-fork/) land on a [page](https://help.github.com/articles/configuring-a-remote-for-a-fork/) where the result is that the upstream remote is named `upstream`.

**Comment by nik9000** [comment]
That page is how I've always set up my github clones - exception I rename `origin` to `nik9000` because I want to make sure there is never anything that accidentally does something to the "default" name....

**Comment by rjernst** [comment]
> I think the belief that the remote should be named origin is too far

I did not write the code,  it is from a 3rd party gradle plug in as Nike pointed out.  If you want to open a PR there to fix,  please do. But not that I don't know how it would know which of many remotes is the one to grab the URL from..

**Comment by jasontedor** [comment]
> I did not write the code, it is from a 3rd party gradle plug in as Nike pointed out.

To be clear, my comments were aimed exactly at Nebula's convention here; sorry for the confusion.
