### ISSUE TITLE
On full cluster restart, shards are not recovering and remaining in Unassigned state

### ISSUE THREAD

**Issue by venkatreddyamalla** [elastic/elasticsearch#19538]
**Elasticsearch version**: 2.x

**JVM version**: 1.7 and 1.8

**OS version**: Ubuntu 14.05

**Description of the problem including expected versus actual behavior**:
**TL;DR** If I have more replicas than my data-nodes while restarting the cluster then shards are not recovering. 

I have cluster of 8 nodes ( 3 master + 5 data) and configured replica as 4 for each and every index in order to keep all shards in each and every node(can sustain max of 4 data nodes failure).  Now in process of full cluster restart, I've shutdown all data + master nodes. I started restarting cluster by making master nodes up first then data nodes 1 by one. As I had replica 4, my cluster should have recovered all indices from data node-1 when I restarted it.  But it didn't happened, cluster state was _red_, and all shards were in unassigned state(I didn't find any thing in logs like why shards recovering is not happening). Instead when I changed _replication_ to <=1, all shards are started recovering and finally my cluster state went to _yellow_ .  Can you please let me know if I'm missing any configuration here.

**Steps to reproduce**:
 1. Start a cluster of 1 master + 1 data node
 2. Create index with 1 shard with replica 1( Now cluster state will become to **Yellow**)
 3. Stop elasticsearch in data node - cluster state **Red**
 4. Start elasticsearch in data node - cluster state **Yellow** (_Recovered successfully_)
 5. Now increase replica to 2 - cluster state **Yellow**
 6. Stop elasticsearch in data node - cluster state **Red**
 7. Start elasticsearch in data node - cluster state **Red** . Now index is not getting recovered and all shards remaining in state *unassigned*  As replica(2) is more than available data-nodes(1).
 8.  Now decrease the replica to 1 or 0 (<= available data nodes in cluster(in this case 1)), and index is recovered immediately.

**Comment by clintongormley** [comment]
Hi @venkatreddyamalla 

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by venkatreddyamalla** [comment]
Hi @clintongormley 
Thanks for your suggestion. I suspected it is a bug in elasticsearch and posted here but I'm wondering like how it was not qualified as bug. Could you please shed some light on this weird behaviour if you are already aware of this?

**Comment by bleskes** [comment]
This is a known  and documented behavior (which doesn't means it's good). It was fixed with https://github.com/elastic/elasticsearch/issues/14739 and was explained in several issues around it, see for example https://github.com/elastic/elasticsearch/issues/18393#issuecomment-219671552

**Comment by venkatreddyamalla** [comment]
Thanks a lot @bleskes for pointers. It is really helpful than simple template message.
