### ISSUE TITLE
Ability to index to an alias pointing to multiple indices

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#19548]
Ability to index to an alias which points to multiple indices.  It would be good to be able to define (either with a flag, or perhaps with a 'priority' field) to which index documents should be written.  This would allow an application to point to an alias for both search and index queries and have the target index to which documents will actually be indexed configurable in the cluster.

**Comment by clintongormley** [comment]
This has been discussed previously (although I can't find the issue).  Use one alias (which points to one index) for CRUD, and another alias (which can point to one or more indices) for searching.  No need for more complex alias configuration.
