### ISSUE TITLE
Delete child documents when parent is deleted.

### ISSUE THREAD

**Issue by Avatah** [elastic/elasticsearch#1954]
Discussed here:
https://groups.google.com/forum/?fromgroups#!topic/elasticsearch/nfpTXJFePhA
Child documents should be deleted when parent documents is deleted. Especially if it's deleted by ttl.

**Comment by clintongormley** [comment]
Revisiting this issue: I can't seen us implementing this as some kind of built in trigger, especially as we are talking about making the _ttl functionality simpler and less automatic.  

Deleting children of a parent is easy enough to do client side with the delete-by-query plugin, as is deleting expired docs.  I'm going to close this

**Comment by Alireza-DarkMan** [comment]
Hi
I wonder if delete-by-query is deprecated why should we use it?

**Comment by clintongormley** [comment]
The delete-by-query plugin is not deprecated.

**Comment by Alireza-DarkMan** [comment]
Sorry that was a miss understanding.
Thank you :)

**Comment by hgfischer** [comment]
Does this problem still exists? If not, in which version it was fixed?

**Comment by stavarengo** [comment]
+1
