### ISSUE TITLE
improve painless instanceof tests

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#19542]
We need to improve ComparisonTests to also test the case where variable is `def` and `null`, and make sure it does the right thing: there may be bugs.

For example: `x instanceof Number`.

**Comment by Plokji** [comment]
Hi I'm new to contributing to OSS. I would like to have a try and resolve this issue.
Thanks.

**Comment by nik9000** [comment]
Sure! Enjoy.

**Comment by jdconrad** [comment]
AFAIK this works.  Closing.
