### ISSUE TITLE
Create a percentile_ranks_bucket pipeline aggregation

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#19546]
We have a [`percentiles_bucket`](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-aggregations-pipeline-percentiles-bucket-aggregation.html) pipeline aggregation but we currently don't have the reverse operation `percentile_ranks_bucket` which would be the pipeline aggregation equivalent to the `percentile_ranks` aggregation.

**Comment by Makthum** [comment]
Hi,

I am aware this functionality is not implemented yet, but is there a way i can accomplish percentile_rank over a bucket aggregation ?

**Comment by colings86** [comment]
Not currently, you would need to do this calculation in your client application for now.

**Comment by delirius325** [comment]
This would be a neat feature to add, +1

**Comment by markharwood** [comment]
cc @elastic/es-search-aggs

**Comment by vishleshpatel** [comment]
@colings86, I would like to pick this issue but I am new to Elasticsearch. I would need some pointers and ramp up time to finish this task. If that is okay, I would go ahead and take a stab at this. Thanks!

**Comment by polyfractal** [comment]
Heya @vishleshpatel :)  All yours if you want to work on it!  You'll need to implement a few different classes, but most are just boilerplate with some tweaked names/parameters.  I'd use the existing percentiles bucket agg as a template:

- `PercentileRanksBucketPipelineAggregationBuilder`, similar to [`PercentilesBucketPipelineAggregationBuilder`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/pipeline/PercentilesBucketPipelineAggregationBuilder.java). Builder object for java users, and contains to/from xcontent parsing for the REST json
- `PercentileRanksBucketPipelineAggregator`, similar to [`PercentilesBucketPipelineAggregator`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/pipeline/PercentilesBucketPipelineAggregator.java).  This contains the code that does the actual aggregating, e.g. taking in the bucket values and emitting the percentile ranks values
- `InternalPercentileRanksBucket`, similar to [`InternalPercentilesBucket`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/pipeline/InternalPercentilesBucket.java).  This is the "internal" result, e.g. the result generated by the aggregator.
- `PercentileRankBucket`, similar to [`PercentilesBucket`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/pipeline/PercentilesBucket.java). Interface defining the response, can probably just extend `PercentileRanks`.  Note that the prior "Internal" response implements this interface.  The Internal object is the non-public API used by Elasticsearch, while the PercentileRankBucket interface is the API consumed by java clients
- Register the new aggregation in the [`SearchModule`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/SearchModule.java#L501-L506)

There are probably other things I'm forgetting that you'll find along the way, but that should get you started.  Happy to help, the best way is to probably a WIP PR that we can iterate on if you run into issues that you have questions about.

**Comment by vishleshpatel** [comment]
@polyfractal awesome!! thanks for the pointers! I would get going with this and ask you questions as I get puzzles on d way.

**Comment by selfishone** [comment]
@colings86 @vishleshpatel is this task still being worked on?  If not I would like to try it out

**Comment by jmbessa** [comment]
@polyfractal Hi! I would like to know if this issue is still open. If yes, can I work on it? This would be my first issue

**Comment by didendron** [comment]
Can I work on it? If yes, I will try to create this aggregation with the tests.

**Comment by wchaparro** [comment]
Closing as not planned, focus on ES|QL development
