### ISSUE TITLE
Elasticsearch refresh -1 to disable documents from being searchable doesnt work and updates documents after 5 mins

### ISSUE THREAD

**Issue by sufficetoentice** [elastic/elasticsearch#19569]
**Elasticsearch version**: 2.2

**JVM version**: 1.8.60 

**OS version**: Linux

 I wish to imitate DB transactions in elasticsearch because I want a stream of documents to be available at the same time for searching. In order to do that, thought of disabling refresh until I index all the documents and then do a forcemerge/enable refresh explicitly to make them searchable at the same time. However I noticed , even after disabling refresh, the documents get updated after 5 minutes automitically. 

The way I understand is refresh is equivalent to Lucene flush which would write to segments and make them searchable after 1 second. I also tried a huge interval of transaction logs flush. The settings are as under 
translog": { 
"flush_threshold_size": "1024mb", 
"sync_interval": "60m", 
"flush_threshold_period": "60m", 
"fs": { 
"type": "simple" 
}

Please let me know if this is achievable in Elasticsearch.

**Comment by nik9000** [comment]
It really isn't. See https://github.com/elastic/elasticsearch/pull/16028 for most of the conversation. The short version is that even if it tried fairly hard not to make documents visible unless the user told it to Elasticsearch would still make them visible when migrating a shard copy to another node.
