### ISSUE TITLE
Provide ability to apply query side synonym changes in real-time

### ISSUE THREAD

**Issue by my3sons** [elastic/elasticsearch#1956]
For search analyzers that contain a synonym type filter, it would be great to be able to make changes to the synonym file and have those changes recognized immediately by the associated analyzers without having to close/open the index. Ideally, the synonym cache would be refreshed automatically with changes to the corresponding synonym file. Another option would be to provide API call that could be made to refresh cache on demand. For most ecommerce sites, synonyms provide great value, and therefore are used quite frequently, and it is critical that these changes be implemented without any search outage.

**Comment by clintongormley** [comment]
We currently have no way to distinguish analyzers that would be used at search time only from those that are used at index time.  Changing the synonyms list for index-time analyzers would be a bad idea: you'd end up with incorrect data in your index.

Leaving this open for future discussion

**Comment by brusic** [comment]
My plugin is caught up in the issue Clinton referenced. My production code maintains a static collection of the analyzers, but I found that approach a bit kludgy. I switched to using the IndicesService, but that is where the issue comes into play. 

https://github.com/brusic/refresh-token-filters

**Comment by markharwood** [comment]
We discussed this some more and as Clinton said in his comment above there may be undesirable consequences for indexing if we make it simple for users to switch the definitions on the fly. Of course if you know what you are doing and it is a search-time-only analyzer it is possible to provide a custom plugin as  @lindstromhenrik noted which can safely reload synonym sets, perhaps from a centralised resource.

Given we don't want to make it easy for novice users to do the wrong thing and users who know what they are doing have a work-around the original proposal isn't something we are choosing to add to core.
Sorry, and thanks for raising the discussion.
