### ISSUE TITLE
ElasticSugar deleteOnExit doesn't work

### ISSUE THREAD

**Issue by ssemichev** [elastic/elasticsearch#19586]
The temporary directories do not deleted

> sbt my-service/it:test

> scala> System.getProperty("java.io.tmpdir")
res2: String = /var/folders/y5/lw613j_56sq4n_bkz4l9kr0r0000gn/T/

I can manually delete testNodeHomePath in afterAll method, but it seems it should work with existing  deleteOnExitHook. Do you know why the hook doesn't work?

````
val indexName = getClass.getSimpleName.toLowerCase

  behavior of "index matchers"

  it should "support index document count" in {
    indexName should haveCount(4)
    indexName should not(haveCount(11))
  }
}
```


**Elasticsearch version**:
2.3

**JVM version**:
1.8

**OS version**:
OSX 10.9.5

**Description of the problem including expected versus actual behavior**:

**Comment by nik9000** [comment]
I think maybe this is an issue with https://github.com/sksamuel/elastic4s instead of Elasticsearch? Reopen if you disagree.
