### ISSUE TITLE
[Ingest] GET should match _template behavior

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#19585]
While testing some ingest functionality, I ran into this:

```http
GET /_ingest/pipeline/xyz
```

will always return

```json
{
  "pipelines": []
}
```

even though `xyz` doesn't exist.

**Comment by javanna** [comment]
This is a feature, not a bug :)

I think it is this way because you can get back multiple pipelines with a single request. then what do we do if one is there but another doesn't exist? we return what we have and the status code is always 200. I don't love this behaviour either, but I think the solution to this would be then to only be able to retrieve one pipeline per request.

**Comment by pickypg** [comment]
Taking `_template` as the example, the normal approach seems to be:

```http
GET /_template
```

This will return _all_ templates.

```http
GET /_template/xyz
```

This will return just the one you asked for. So maybe we just need two separate `GET` endpoints?

**Comment by pickypg** [comment]
For what it's worth, `GET _template/xyz` returns `{}` if the template doesn't exist, so that would loosely match what is currently happening.

**Comment by pickypg** [comment]
Also, another subtle difference is that `_template` returns an object whose keys are the template names. While this returns an array of pipelines that contain a field named "id" with the appropriate value.

I honestly prefer the array approach because it avoids any potentially invalid JSON field names, but it is a difference.

**Comment by pickypg** [comment]
Alright, I spoke with @talevy offline about this as well. Although it looks a little different (object keys versus an array), we behave in the same way as

```http
GET /_template/{id1},{id2}
GET /_ingest/pipeline/{id1},{id2}

GET /_template/prefix*
GET /_ingest/pipeline/prefix*

GET /_template/{unknown_id}
GET /_ingest/pipeline/{unknown_id}
```

(While the failures return an otherwise empty response, they do use HTTP 404)

However, we are lacking:

- [ ] Fetch all

```http
GET /_template
GET /_ingest/pipeline
```

Note: You can get it by just specifying `*`:

```http
GET /_ingest/pipeline/*
```

**Comment by martijnvg** [comment]
The get pipeline api combines both a get and list in a single api. I'm not sure whether the get template api should change to be more like the get pipeline api or the other way around. Like you I personally like the array response format. 

If we choose to streamline the get template and get pipeline API, we should also consider other APIs that read from the cluster state, like get template and get script APIs.

Regarding missing pipelines, the get pipeline api only returns a 404 if no pipeline could be found. If some of the requested pipelines couldn't be found it isn't immediate visible in the response so maybe we could improve this by including an empty config:

```json
{
  "id":"missing_id",
  "config": null
}
```

**Comment by javanna** [comment]
I am starting to think that we should do what mget does for all these apis. If we want to return multiple items we cannot have one meaningful status code, so that should always be 200, then each requested item should have its own status in the response. I find this 404 behaviour confusing with the ingest api, that it returns 404 only when nothing is found.

**Comment by pickypg** [comment]
> I find this 404 behaviour confusing with the ingest api, that it returns 404 only when nothing is found.

The downside is that there's no quick "is it there" check without parsing the body since there's _only_ a bulk variant of this get API. `_mget` has the excuse that it's the bulk variant of get, which would return 404s, but `_mget` naturally loses it for the reason you described.

**Comment by pickypg** [comment]
> I'm not sure whether the get template api should change to be more like the get pipeline api or the other way around.

I think this should definitely change to be like Get Index Templates and allow it to return everything without specifying `*` because that's definitely not an obvious feature.

**Comment by martijnvg** [comment]
> I think this should definitely change to be like Get Index Templates and allow it to return everything without specifying * because that's definitely not an obvious feature.

+1 that makes sense. I was referring to the response format.

**Comment by clintongormley** [comment]
Hmmm returning pipelines in an array is different from what we do everywhere else in Elasticsearch.  Why are we returning this:

```
{
  "pipelines": [
    {
      "id": "my-pipeline-id",
      "config": {
        "description": "describe pipeline",
        "processors": [
          {
            "set": {
              "field": "foo",
              "value": "bar"
            }
          }
        ]
      }
    },
    {
      "id": "my-pipeline-id-2",
      "config": {
        "description": "describe pipeline",
        "processors": [
          {
            "set": {
              "field": "foo",
              "value": "bar"
            }
          }
        ]
      }
    }
  ]
}
```

instead of this:

```
{
  "pipelines": {
    "my-pipeline-id": {
      "description": "describe pipeline",
      "processors": [
        {
          "set": {
            "field": "foo",
            "value": "bar"
          }
        }
      ]
    },
    "my-pipeline-id-2": {
      "description": "describe pipeline",
      "processors": [
        {
          "set": {
            "field": "foo",
            "value": "bar"
          }
        }
      ]
    }
  }
}
```

**Comment by pickypg** [comment]
At that point do we even need to wrap it with the `pipelines` object, which just served to be an array?

```json
{
  "my-pipeline-id": {
    "description": "describe pipeline",
    "processors": [
      {
        "set": {
          "field": "foo",
          "value": "bar"
        }
      }
    ]
  },
  "my-pipeline-id-2": {
    "description": "describe pipeline",
    "processors": [
      {
        "set": {
          "field": "foo",
          "value": "bar"
        }
      }
    ]
  }
}
```

**Comment by clintongormley** [comment]
> At that point do we even need to wrap it with the pipelines object, which just served to be an array?

True - I was taking this from mappings/settings/etc, but templates don't have a top-level `templates` key and i think pipelines are most similar to those.

**Comment by martijnvg** [comment]
Ok - then lets change to get pipeline API to return pipelines in the style templates API does.

(all thought personally I prefer array based notation as the ordering is more consistent and it is the right element to return multiple objects - but consistency is important too!)
