### ISSUE TITLE
How to add header to bulkRequest using BulkProcessor?

### ISSUE THREAD

**Issue by jasper-zhang** [elastic/elasticsearch#19593]
If using BulkRequestBuilder, I can use method `putHeader` to add header, but if I use BulkProcessor, I must `putHeader` to each IndexRequestBuilder. 

Meybe a method of BulkProcessor is necessary, so I could  put header to the BulkRequest.

**Comment by dadoonet** [comment]
Please ask your questions on discuss.elastic.co.
You don't have to explicitly add a header. You just have to add IndexRequest or DeleteRequest as explained in the doc: https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-docs-bulk-processor.html

**Comment by dadoonet** [comment]
I'm sorry. I probably misread your demand. Reopening.

Thanks @javanna for the heads up.

**Comment by javanna** [comment]
putHeader is not exposed anymore in requests and request builders. You rather have to do the following which also works with `BulkProcessor` :

```
client.filterWithHeader(Collections.singletonMap("Authorization", token)).prepareSearch().get();
```
