### ISSUE TITLE
Expand threadpool types that can be listed by /_cat/thread_pool

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch#19590]
**Describe the feature**:

Currently `/_cat/thread_pool` seems to be limited to displaying details of a few specific thread pools.  While the default thread pools displayed are great, it would be nice if it could display details on all current thread pools in a cluster, like all listed in the `thread_pool` section of `/_nodes/stats` with the `h` or `v` parameter.  Currently, many of these thread pools cannot be display by this endpoint.

**Comment by martijnvg** [comment]
@joshuar Which thread pools would you like to be added? Currently [these TP](https://github.com/elastic/elasticsearch/blob/0a293fad29311da1a7472e2faf6790fc34f26ae2/core/src/main/java/org/elasticsearch/rest/action/cat/RestThreadPoolAction.java#L58) are supported via the `h` header.

**Comment by spinscale** [comment]
for starters,  `FETCH_SHARD_STARTED, FORCE_MERGE, FETCH_SHARD_STORE` threadpools are missing, but I'd be awesome if the custom threadpools could be included as well, like in the node stats, so you can just refer to them by their regular name

**Comment by martijnvg** [comment]
+1 to add `FETCH_SHARD_STARTED`, `FORCE_MERGE` and `FETCH_SHARD_STORE`  TPs. 

The reason it is fixed now, is because of how currently for each TP is assigned to an abbreviated name that used in column header. This makes it tricky when it comes to custom TP, since we don't know the name upfront. Perhaps for custom TPs we could just use the full name?

**Comment by spinscale** [comment]
+1, thats what I meant with `just refer to them by the regular name`.. sorry for being unclear

**Comment by joshuar** [comment]
Possibly PERCOLATE on top of @spinscale's list.

I'd say thread pools used by our plugins would be good candidates to be able to view more easily if possible to add here?

**Comment by martijnvg** [comment]
> Possibly PERCOLATE on top of @spinscale's list.

The percolate TP has been removed since 5.0-alpha1. The percolator uses the search TP since it became a query.

> I'd say thread pools used by our plugins would be good candidates to be able to view more easily if possible to add here?

Agreed. Hopefully this can be done by using their full name.

**Comment by nik9000** [comment]
> Hopefully this can be done by using their full name.

+1. I think we should allow listing all the thread pools.
