### ISSUE TITLE
access doc_count in scripted_metric section.

### ISSUE THREAD

**Issue by Shashi-GS** [elastic/elasticsearch#19597]
Could you please help me on accessing the doc_count or the value_count aggregation result in the scripted metric section?

**Comment by colings86** [comment]
In future please ask question on the user forum https://discuss.elastic.co. This issues list is reserved for bug reports and feature requests, there is much more help on using Elasticsearch available on the forums.

Could you please give an example of the request you have tried so far to get this working to give some context around your question?

**Comment by Shashi-GS** [comment]
sure. Thank you for the response.   Please find the issue link for your reference.
https://discuss.elastic.co/t/access-doc-count-in-scripted-metric-section/56371
