### ISSUE TITLE
Mark Foreach Processor as experimental

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#19602]
From an offline discussion with @martijnvg and @BigFunger...

The foreach processor breaks many of the conventions of the other processors in Ingest.
It allows for a nested processor to execute in a separate context, and this separate context has been proven to be leaky.

Issues like #19601 and #19592 poke holes in the current interface we have designed. For these reasons, I think that the processor should be marked *experimental* for the upcoming 5.0 release. I do still think the processor adds a ton of value. We do not have many other tools for working with arrays in our documents, and this is a great tool for that.

**Comment by talevy** [comment]
@clintongormley your thoughts on this issue would be great!

**Comment by jpountz** [comment]
+1 to add the `experimental` annotation in case of any doubts about the stability of the API

**Comment by javanna** [comment]
but isn't ingest as a feature already experimental per se? do we want to make foreach super experimental? :)

**Comment by clintongormley** [comment]
i'm good with calling out foreach as experimental.  wondering if we should change the foreach model to avoid the issues (which i don't fully understand).  perhaps tomorrow we can chat on zoom?

**Comment by martijnvg** [comment]
I'll mark the foreach processor as experimental.
