### ISSUE TITLE
All of the indices are lost all of a sudden

### ISSUE THREAD

**Issue by abhishekkunnath** [elastic/elasticsearch#19600]
I had elasticsearch service under amazon AWS which had data processed from Amazon AWS S3 and Lambda. And Kibana was used to visualize the incoming streaming data. All of a sudden the indices disappeared and whole data was lost. 

i had about 700 above JSON documents under one index and there were a few more sample indices.

but now when i list all the indices, it returns

```
health status index        pri rep docs.count docs.deleted store.size pri.store.size 
yellow open   esroumaanapp   5   1          6            0     52.5kb         52.5kb 
yellow open   .kibana-4      1   1          1            0      2.4kb          2.4kb 
```

The data is now streaming again, but all the previous data is lost.
Is there a way to recover them?

elasticsearch status

```
{
  "status" : 200,
  "name" : "Golden Girl",
  "cluster_name" : "178367654016:manudomain",
  "version" : {
    "number" : "1.5.2",
    "build_hash" : "20085dbc168df96c59c4be65f2999990762dfc6f",
    "build_timestamp" : "2016-04-20T15:51:59Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by dadoonet** [comment]
Please ask for questions on discuss.elastic.co. And describe all the steps and configuration you have (like number of nodes., settings, hardware...)

We can help you there.
