### ISSUE TITLE
Phrase Suggester collate query

### ISSUE THREAD

**Issue by shyam-aryan** [elastic/elasticsearch#19615]
I'm not able to set the collate query in Phrase Suggester api.

I created a template query initially like this
`POST /_search/template/sc
{
    "template": {
        "query": {
              "query_string" : {
                "query" : "{{suggestion}}",
                "fields" : [ "SearchAllText" ],
                "default_operator" : "and",
                "analyze_wildcard" : true
              }
              }
    }
}`

and then tried to use that in PhraseSuggestionBuilder with collateQuery, but it doesn't seem to interpret correctly.

`QueryBuilder qb = templateQuery("sc", ScriptService.ScriptType.INDEXED, null);        PhraseSuggestionBuilder psb = SuggestBuilders.phraseSuggestion(name)
                .text(original)
                .field(SUGGEST_FIELD)
                .size(1)
                .addCandidateGenerator(generator
                        .suggestMode("popular")
                        .minWordLength(1)
                        .prefixLength(0))
                        .collateQuery(qb.toString());`

Above query gets translated to this:
`phraseSuggest": {
    "text": "xyz",
    "phrase": {
        "field": "SuggestCompletion",
        "size": 1.0,
        "direct_generator": [
            {
                "field": "SuggestCompletion",
                "suggest_mode": "popular",
                "prefix_length": 0.0,
                "min_word_length": 1.0
            }
        ],
        "collate": {
            "query": "{\n  \"template\" : {\n    \"id\" : \"sc\",\n    \"params\" : null\n  }\n}"
        }
    }
}
`
Can you please help me with this?

**Comment by clintongormley** [comment]
Hi @shyam-aryan 

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only. If it turns out that this is a bug, then feel free to reopen with the details.

thanks
