### ISSUE TITLE
add  /elasticsearch-2.3.3/lib/jts-1.13.jar to build path

### ISSUE THREAD

**Issue by ucasyp** [elastic/elasticsearch#19617]
**Elasticsearch version**:

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by dadoonet** [comment]
JTS is marked as optional.

Which means that you simply have to add it to your `pom.xml` if you wish.

See https://github.com/elastic/elasticsearch/blob/2.4/core/pom.xml#L90-L94
