### ISSUE TITLE
Throttling importing dangling shards

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#19624]
If you have 1000s of shards and blow away your cluster state by mistake and try to bring an empty master online then the cluster will try to import all the dangling shards. The trouble is that each node tries to import all of its shards as soon as it comes online. It is quite possible that the master node doesn't have the heap to process the whole request, especially if dozens of nodes try to do this all at the same time.

Given that this is a recovery operation and not a super common one I don't think we should engineer fancy stuff like brackpressure. Instead I think we should throttle the number of dangling shards we try to import at once, maybe adding a randomized wait before the first import when an empty master comes online to stagger nodes.

**Comment by bleskes** [comment]
it's very hard to coordinate things between distributed nodes. I suggest something simple like a node level settings that makes the node only send 5 dangling indices at a time (by default). Once those are allocated the next batch can be sent.

**Comment by jpountz** [comment]
Discussed in FixitFriday: @bleskes's suggestion above should help while being simple, so we are removing the `discuss` label and making it an `adoptme`.

**Comment by bleskes** [comment]
I haven't heard of this being an issue in practice in the last years (it is a valid one though). Since we have no concrete plans of implementing it and are actually doubting whether to keep the dangling indices feature, I'm going to close the issue as won't fix for now. If the need arises we can reopen.
