### ISSUE TITLE
Number format in "origin" attribute of Gauss decay functional score query

### ISSUE THREAD

**Issue by MalhotraKaran** [elastic/elasticsearch#19620]
**Elasticsearch version**: 2.3.1

**JVM version**: 8

**OS version**: ubuntu 14.04

**Description of the problem including expected versus actual behavior**: Number_format error when using multiple numbers in "origin" attribute in Gauss scoring function. 

**Query**:
"gauss": { 
    "experience": { 
          "origin": "11, 12",
          "scale": "2",
          "offset": "0",
          "decay": 0.33
    }
}

**Output** :- {"error":{"root_cause":[{"type":"number_format_exception","reason":"For input string: "11,12""}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"profiles","node":"AHWbyD5qR3yYDAzNIOZ8rA","reason":{"type":"number_format_exception","reason":"For input string: "11,12""}}]},"status":400}

**Comment by clintongormley** [comment]
You can't use multiple origins in decay functions.  The `"lon,lat"` format is reserved for geo-point fields
