### ISSUE TITLE
Make snapshots save in new directory

### ISSUE THREAD

**Issue by shaharmor** [elastic/elasticsearch#19635]
**Describe the feature**:
When taking a snapshot, the files are saved to the `location` defined in the repository settings.
If another snapshot is being taken right after the first one, it will be saved to the same directory as the first one, mixing the files together (Possibly overriding some of them?).

It would be nice if each snapshot would be saved to a new directory. It can be possible to either set the name in the snapshot command or maybe use a timestamp of some sort.

So when running:
```bash
# create repository
curl -XPUT 'http://localhost:9200/_snapshot/my_backup' -d '{
    "type": "fs",
    "settings": {
        "location": "/mount/backups/my_backup",
        "compress": true
    }
}'

# create snapshot
curl -XPUT 'http://localhost:9200/_snapshot/my_backup/my_snapshot' -d '{
  "indices": "index_1,index_2",
  "ignore_unavailable": "true",
  "include_global_state": false
}'
```

It will be saved to `/mount/backups/my_backup/my_snapshot/` instead of `/mount/backups/my_backup/` directly.

**Comment by rjernst** [comment]
Please ask questions on https://discuss.elastic.co. We reserve github for confirmed bug reports and feature requests.

Also, please read [how snapshots work](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html)  carefully. In particular:

> The index snapshot process is incremental. In the process of making the index snapshot Elasticsearch analyses the list of the index files that are already stored in the repository and copies only files that were created or changed since the last snapshot. That allows multiple snapshots to be preserved in the repository in a compact form.
