### ISSUE TITLE
update_by_query Retry on conflicts

### ISSUE THREAD

**Issue by anaghasjoshi** [elastic/elasticsearch#19632]
**Elasticsearch version**: 2.3.0

**JVM version**: 1.8

**OS version**: ubuntu 14.04

**Description of the problem including expected versus actual behavior**:
I am using update_by_query API I do not get anything in failures [] when version conflicts happen. Is there a way I can retry on version conflicts on update_by_query?

**Steps to reproduce**:
1. Run update_by_query on certain documents
2. Meanwhile modify some of the documents
3. Version conflicts arise

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by nik9000** [comment]
> Is there a way I can retry on version conflicts on update_by_query?

It doesn't support that right now. You can either ignore version conflicts or abort the entire request.

**Comment by nik9000** [comment]
> I am using update_by_query API I do not get anything in failures [] when version conflicts happen.

We have tests for this behavior. Can you provide a bash script or something like that that reproduces the problem?

**Comment by anaghasjoshi** [comment]
There are no scripts. Our system gets a lot of data from various other systems, where they all tend to modify the same set of documents (sometimes when one has taken a snapshot for update and the other has requested to index). Is there no way we can identify the version conflicted documents?

**Comment by nik9000** [comment]
> Is there no way we can identify the version conflicted documents?

If you don't pass `conflicts=proceed` in the request it should fail the request when it hits the first conflict and you can retry yourself. There is no built in retry on conflict, specifically because we'd have to be fairly fancy to make sure that the query that you send still matches.

If you aren't passing `conflicts=proceed` and you are still aren't seeing the failures on conflicts then you've found a bug. We have plenty of tests in this area so I expect the bug is something I haven't thought of. So I'd like you to provide a thinned down example that I can run in a shell or that reproduces it.

**Comment by serzh** [comment]
Hi, guys. Are there any progress on adding `retry_on_conflicts` feature for `update_by_query' API? 
I'm really interested in this feature.

**Comment by marshall007** [comment]
> You can either ignore version conflicts or abort the entire request.

@nik9000 how do you ignore version conflicts? Were you just referring to `conflicts=proceed`? Is there a workaround for when your update script is just appending to an array or incrementing a value?

**Comment by nik9000** [comment]
Yes, conflicts=proceed is all I meant. There isn't anything for the race
case. For the append to array case you could redo the update by query
ignoring docs that already have the field. It would certainly be nicer if
we had a recheck feature for conflicts like those but it'd be fiddly to put
together.

**Comment by colings86** [comment]
@nik9000 Is this still an issue? Could this be closed?
