### ISSUE TITLE
Remove found and created from index, delete, update, and bulk

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#19630]
People can just use `operation` instead.

**Comment by nik9000** [comment]
At the time of filing this issue we don't have a branch that yet targets 6.0 so this can't be worked on.

**Comment by nik9000** [comment]
Relates to #19566.

**Comment by clintongormley** [comment]
@nik9000 we should add deprecation docs to 5.0 though

**Comment by nik9000** [comment]
> @nik9000 we should add deprecation docs to 5.0 though

#19633

**Comment by olcbean** [comment]
hey @nik9000 
Now that #19633 is merged, I would like to have a go at implementing the remaining enhancement. I figured I will ask before doing the work, as the issue does not have an `adoptme` tag.
Thanks!

**Comment by nik9000** [comment]
@olcbean it is all yours! Thanks for asking! I'd totally forgotten about it.
