### ISSUE TITLE
search template mustache loop quoting

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch#19643]
**Elasticsearch version**: 2.3.4

**JVM version**: java version "1.8.0_65", Java(TM) SE Runtime Environment (build 1.8.0_65-b17), Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

**OS version**: OS X 10.11.5 (15F34)

**Description of the problem including expected versus actual behavior**: mustache loop inserting extra quotes and commas.

**Steps to reproduce**:
 1. Use example from https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html#_validating_templates

    ```
    GET /_render/template
    {
      "inline": {
        "query": {
          "terms": {
            "status": [
              "{{#status}}",
              "{{.}}",
              "{{/status}}"
            ]
          }
        }
      },
      "params": {
        "status": [ "pending", "published" ]
      }
    }
    ```
 2. Expected (from the documentation)

    ```
    {
      "template_output": {
        "query": {
          "terms": {
            "status": [ 
              "pending",
              "published"
            ]
          }
        }
      }
    }
    ```
 3. Actual Result

    ```
    {
      "template_output": {
        "query": {
          "terms": {
            "status": [
              "",
              "pending",
              "",
              "published",
              ""
            ]
          }
        }
      }
    }
    ```

**Comment by tlrx** [comment]
This is unfortunately a known issue of Mustache. We added a helper function to better render arrays of values in #18856 using the notation `{{#join}}my_iterable{{/join}}`. It will be released in the next 2.4 / 5.0 versions.

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/commit/8afb8da9cf74ae1d465700909a47655a2ea2481f and https://github.com/elastic/elasticsearch/commit/69c25bf8d98f281da37eac570d078dfd879966bd

**Comment by jpcarey** [comment]
@clintongormley @tlrx is there a workaround for the currently impacted versions?  I think we should update or remove that particular example for those versions, as one would be more prone to hitting this issue by having a bad example in our docs.  I spent about an hour pulling apart a configured watch before I realized what the actual issue was.  This might be worth a separate bug, but hitting a _search template with the described issue from above provides a fairly useless response error:

```
{
   "error": {
      "root_cause": [
         {
            "type": "query_parsing_exception",
            "reason": "[_na] query malformed, no field after start_object",
            "index": "logstash-uptime-test",
            "line": 1,
            "col": 2
         }
      ],
      "type": "search_phase_execution_exception",
      "reason": "all shards failed",
      "phase": "query",
      "grouped": true,
      "failed_shards": [
         {
            "shard": 0,
            "index": "logstash-uptime-test",
            "node": "4sTl4inGTWC0sHRirlCrZg",
            "reason": {
               "type": "query_parsing_exception",
               "reason": "[_na] query malformed, no field after start_object",
               "index": "logstash-uptime-test",
               "line": 1,
               "col": 2
            }
         }
      ]
   },
   "status": 400
}
```

**Comment by clintongormley** [comment]
@jpcarey i updated the 2.x docs to reflect the real rendering (as mentioned by you above).  The exception that you're getting means you're doing something different from the example, eg this works:

    PUT t/t/1
    {
      "status": "pending"
    }
    
    GET /_search/template
    {
      "inline": {
        "query": {
          "terms": {
            "status": [
              "{{#status}}",
              "{{.}}",
              "{{/status}}"
            ]
          }
        }
      },
      "params": {
        "status": [ "pending", "published" ]
      }
    }
    
Try using `/_render/template` with the code giving you this error and you will be able to see where it is going wrong.
