### ISSUE TITLE
Postgresql storedprocedure to elasticsearch

### ISSUE THREAD

**Issue by kavurupavan** [elastic/elasticsearch#19644]
Hi,

I have to index Postgresql Stored Procedure which is having million of records. Can someone let me know the process how to do indexing the Stored Procedure into elasticsearch.  Without using parameter i want to download whole data in elasticsearch. Please help me. Thanks in advance.

bin=/home/elasticsearch-jdbc-2.3.1.0/bin
lib=/home/elasticsearch-jdbc-2.3.1.0/lib
 echo ' {
        "jdbc" : {
        "driver": "org.postgresql.Driver",
        "url": "jdbc:postgresql://localhost:5432/testdb",
        "user": "b2g_mns",
        "password": "b2gmns",
       "sql" : [
            {
                "callable" : true,
                "statement" : "{call  cloud10k.sp_fs_comp_search(?::varchar, ?::varchar, ?::varchar, ?::bigint)}",
		"parameter" : [
                                "CITI", "ALL", "ALL", 0
                                 ]
                           }
                        ],
                "index" : "my_jdbc_river03",
                "type" : "my_jdbc_river03"
       }
 }' | java \
      -cp "/home/elasticsearch-jdbc-2.3.1.0/lib/*" \
      -Dlog4j.configurationFile=/home/elasticsearch-jdbc-2.3.1.0/bin/log4j2.xml \
       org.xbib.tools.Runner \
       org.xbib.tools.JDBCImporter

Thanks,
Pavan Kumar.

**Comment by dadoonet** [comment]
Please ask questions on discuss.elastic.co

**Comment by kavurupavan** [comment]
Hi sir,
I asked i didn't receive any response.
