### ISSUE TITLE
when index with 0 replica, if lost some primary shards, the lost shards will keep unassigned status

### ISSUE THREAD

**Issue by jasstionzyf** [elastic/elasticsearch#19642]
**Elasticsearch version**:
2.2.0

**JVM version**:
jdk-8u71-linux-x64

**OS version**:
CentOS release 6.7 (Final)

**Description of the problem including expected versus actual behavior**:
   it is a little strange that as long as the cluster has more then 0 replications, the lost unassigned shards will be reassigned, but with 0 replications, they will keep unassigned status.
  is this a normal feature that only support manual reassign the lost primary shards when no replications ?

**Comment by dadoonet** [comment]
Please ask questions on discuss.elastic.co

Yes. This is expected.
