### ISSUE TITLE
Adjacent wildcards in string query causes incorrect result

### ISSUE THREAD

**Issue by 518jelly** [elastic/elasticsearch#19641]
Elasticsearch version: 2.1.1

JVM version: java version "1.7.0_79" (Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode))

OS version: CentOS release 6.7 (Final)

Description of the problem including expected versus actual behavior:
Expected correct results for query "U??ZB4", but the result always hits 0.

Steps to reproduce:
 1.
execute search:
{"query":{"bool":{"filter":{"bool":{"should":{"wildcard":{"plateno":"U?SZB4"}}}}}}}
gets correct results:
"hits": { "total": 1,"plateno": "UBSZB4"}
 2.
execute search:
{"query":{"bool":{"filter":{"bool":{"should":{"wildcard":{"plateno":"U??ZB4"}}}}}}}
gets incorrect results:
"hits": { "total": 0}

**Comment by dadoonet** [comment]
I can't reproduce it with this script:

```sh
curl -XDELETE "localhost:9200/test?pretty"
curl -XPUT "localhost:9200/test/doc/1?pretty&refresh" -d '{
	"foo": "barbaz"
}'
curl -XGET "localhost:9200/test/_search?pretty" -d '{
	"query": {
		"wildcard": {
			"foo":"bar?az"
		}
	}
}'
curl -XGET "localhost:9200/test/_search?pretty" -d '{
	"query": {
		"wildcard": {
			"foo":"bar??z"
		}
	}
}'
```

My guess is that because wildcard queries are not analyzed it does not give the expected result. Depends on your mapping as well.

You can follow up on discuss.elastic.co where we can help with this question.
Not an issue. (tested in 5.0)
