### ISSUE TITLE
ES 2.3.4: same query being run several times

### ISSUE THREAD

**Issue by doron-logzio** [elastic/elasticsearch#19657]
**Elasticsearch version**: 2.3.4

**JVM version**: 1.7.0_101

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:

Our setup is as follows:
An index over 11 nodes each of them holding 2 shards one primary and one replica (not of the same shard).
When running a slow query of search_type  QUERY_THEN_FETCH and looking at the elasticsearch slow query logs we see that on each of the nodes we are getting 3 calls of the exact same query with timestamps miliseconds apart.
We were wondering whether this is a "feature" of the slow query logging or whether there are really 3 distinct calls of the same query performed on the index and if the latter, what would be an explanation for this.

The query we are running is:
{"index":["index-*****************_"],"search_type":"count","ignore_unavailable":true}
{"size":0,"aggs":{"2":{"date_histogram":{"field":"@timestamp","interval":"30m","time_zone":"+03:00","min_doc_count":1,"extended_bounds":{"min":1469318400000,"max":1469393384478}},"aggs":{"3":{"terms":{"field":"level","size":5,"order":{"_count":"desc"}}}}}},"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"_"}},"filter":{"bool":{"must":[{"query":{"match":{"type":{"query":"mainlog","type":"phrase"}}}},{"range":{"@timestamp":{"gte":1469318400000,"lte":1469393384478}}}],"must_not":[]}}}},"highlight":{"pre_tags":["@kibana-highlighted-field@"],"post_tags":["@/kibana-highlighted-field@"],"fields":{"*":{}},"fragment_size":2147483647}}

And the slow query log (after some processing on our end) is:
[2016-07-28 07:53:00,561][INFO ][index.search.slowlog.query] [index-*****************_]took[5.2s], took_millis[5209], types[], stats[], search_type[QUERY_THEN_FETCH], total_shards[11], source[{"size":0,"aggs":{"2":{"date_histogram":{"field":"@timestamp","interval":"30m","time_zone":"+03:00","min_doc_count":1,"extended_bounds":{"min":1469318400000,"max":1469393384478}},"aggs":{"3":{"terms":{"field":"level","size":5,"order":{"_count":"desc"}}}}}},"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"_"}},"filter":{"bool":{"must":[{"query":{"match":{"type":{"query":"mainlog","type":"phrase"}}}},{"range":{"@timestamp":{"gte":1469318400000,"lte":1469393384478}}}],"must_not":[]}}}},"highlight":{"pre_tags":["@kibana-highlighted-field@"],"post_tags":["@/kibana-highlighted-field@"],"fields":{"*":{}},"fragment_size":2147483647}}], extra_source[],

(the other two instances are exactly the same with a slight variance on the time taken)

**Comment by clintongormley** [comment]
The slow log records queries at the shard level. You have more than one shard from the same index on the same node.

**Comment by doron-logzio** [comment]
Thanks. This does clarify things a bit, but:
As stated there are only two shards per node (one of them even a replica) and still I get 3(!!!) slowquery logs.

Would there be any other possible reason?

**Comment by clintongormley** [comment]
I've tested this out locally and I get one slow log message per shard, only.  (It doesn't matter if it is primary or replica - a search can hit either one).

If you are seeing something different then please could you put together a small recreation that demonstrates the issue?

**Comment by doron-logzio** [comment]
thanks for this!
Will try to put a "small recreation"

**Comment by colings86** [comment]
no further feedback
