### ISSUE TITLE
[1.7.3] Two identical ES clusters with identical data return different results

### ISSUE THREAD

**Issue by Fizzadar** [elastic/elasticsearch#19656]
Hi Elastic! Yesterday we were migrating from an old cluster to a new one and experienced a really bizzare issue with a simple terms aggregation. We've got identical versions/ES-binaries (build hash is the same) and data in both clusters - yet one returns correct terms data for one query and the other does not.

The query in question:

```json
{
  "aggregations": {
    "colours": {
      "aggregations": {
        "offset__terms": {
          "terms": {
            "field": "offset",
            "shard_size": 0,
            "size": 10
          }
        }
      },
      "nested": {
        "path": "colours"
      }
    }
  },
  "size": 0,
  "timeout": "60s"
}
```

Run against docs:

```json
{
    "colours": [
        {
            "offset": 1,
            "basic_name": "black"
        }
    ]
}
```

One cluster returns:

```json
"aggregations": {
    "colours": {
        "doc_count": 1,
        "offset__terms": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
            ]
        }
    }
}
```

And the other:

```json
"aggregations": {
    "colours": {
        "doc_count": 1,
        "offset__terms": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 0,
            "buckets": [
                {
                    "key": 1,
                    "doc_count": 1
                }
            ]
        }
    }
}
```

We fixed the issue by changing the nested field name from `offset` to `colours.offset` - however I'm still baffled as to why the two clusters would return different results. Additionally when using other fields nested under colours both the short and full path syntax work - this _only_ affects the `offset` key!

-

ES version info (both clusters identical):

```json
{
  "status" : 200,
  "name" : "cluster-X-01",
  "cluster_name" : "cluster-X",
  "version" : {
    "number" : "1.7.3",
    "build_hash" : "05d4530971ef0ea46d0f4fa6ee64dbc8df659682",
    "build_timestamp" : "2015-10-15T09:14:17Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by clintongormley** [comment]
This is due to a mapping bug which is fixed in 2.x.  You have more than one field called `offset` and it just chooses the first one it finds.  Hence, specifying the full path fixes the issue
