### ISSUE TITLE
ES 2.3.4 accepts two fields with the same name and different types

### ISSUE THREAD

**Issue by segalziv** [elastic/elasticsearch#19654]
**Elasticsearch version**:
2.3.4

**Description of the problem including expected versus actual behavior**:
We are indexing logs to version 2.3.4. We got some index mapper parsing exceptions and checking the mapping I found out that the mapping contains two fields, under two different types, with the same name but their types are different.

Is it the desired behaviour? 

I had the understanding that under an index it could never happen. I would expect elasticsearch to accept the first type and reject the second one.

Here is the relevant part of the resulting mapping:
Please see 'body' field below

```
{
    "test-index": {
        "mappings": {
            "type-b": {
                "properties": {
                    "body": {
                        "type": "string"
                    }
                }
            },
            "type-a": {
                "properties": {
                    "extraData": {
                        "properties": {
                            "body": {
                                "properties": {
                                    "inner-field": {
                                        "type": "long"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Steps to reproduce**:
 1.  POST into type-a {"extraData": { "body": { "inner-field":5 } } }
 2. POST into type-b {"body": "text"}
 3. Check the mapping

**Provide logs (if relevant)**:
These are the mapper parsing errors, on some cases:
> {"type":"mapper_parsing_exception","reason":"failed to parse [body]","caused_by":{"type":"illegal_argument_exception","reason":"unknown property [linkId]"}}

**Comment by rjernst** [comment]
Those fields in your mappings do not have the same _path_. Your body fields have full paths of `extraData.body` and `body`, so they are considered different fields (the full path is used when indexing into lucene).

The exception you see is unrelated to the steps to reproduce you have here. You have an invalid settings in your mapping for the body field (which is not shown here).

**Comment by segalziv** [comment]
Ops, missed that. Thanks @rjernst
