### ISSUE TITLE
Shield authentication failed to ES 2.3.4

### ISSUE THREAD

**Issue by GaneshbabuRamamoorthy** [elastic/elasticsearch#19651]
Hi Team,

I installed ES 2.3.4 & latest shield and I can able to create esadmin user.

But we didn't have license for shield latest version I am getting below exception in ES logs,

License will expire on [Saturday, July 30, 2016]. If you have a new license, please update it.
Otherwise, please reach out to your support contact

Commercial plugins operate with reduced functionality on license expiration:
- shield
- Cluster health, cluster stats and indices stats operations are blocked
- All data operations (read and write) continue to work

Also I tried verifying the shield esadmin user by executing the following curl command,
curl --user esadmin:Gemmot08 -XGET '10.247.0.5:9200?pretty=true'

I am getting below error,

{
  "error" : {
    "root_cause" : [ {
      "type" : "security_exception",
      "reason" : "unable to authenticate user [esadmin] for REST request [/?pretty=true]",
      "header" : {
        "WWW-Authenticate" : "Basic realm=\"shield\""
      }
    } ],
    "type" : "security_exception",
    "reason" : "unable to authenticate user [esadmin] for REST request [/?pretty=true]",
    "header" : {
      "WWW-Authenticate" : "Basic realm=\"shield\""
    }
  },
  "status" : 401
}

Due to that, I couldn't login into the ES HQ & marvel plugins for monitoring purpose.

Is the shield not working because of license update?

Please kindly let us know so that I can work the team to get the latest shield license.

Thanks,
Ganeshbabu R

**Comment by clintongormley** [comment]
Hi @GaneshbabuRamamoorthy 

You need to contact support:

> Otherwise, please reach out to your support contact
