### ISSUE TITLE
Add a CLI tool to rename indices on disk

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#19660]
In #19123, we introduced a CLI tool to allow expert users to manually recover from corrupted translogs by writing a fresh one.

It would be nice to expand this tool to allow us to manually import a dangling index that has a naming conflict with a current index in the cluster.  Right now, we automatically import dangling indices as long as the name of the index doesn't clash with any of the index names in the system, and if there is a clash, we don't import the dangling index but we do leave the data on the node.  Instead, we can look to expand the tool to allow manual intervention to import the dangling index with a different name.

**Comment by rjernst** [comment]
This proposed tool is much different than the translog tool. For the translog, it is deleting a local file. But to manually recover dangling indices would require modifying cluster state right? Or am I misunderstanding what this tool would do?

**Comment by abeyad** [comment]
That's correct, it would have to recover data from potentially many nodes (wherever shards are stored for that dangling index) and modify the cluster state. It was a thought we had to provide some kind of tool like this in the distributed meeting, but its by no means a fleshed out idea. I should probably put a discuss label on it instead.

**Comment by bleskes** [comment]
Some clarification, based on a discussion in fix it friday:
1) The idea was indeed born as a potential solution to the situation where all masters were lost and new indices were auto-created by ongoing indexing *before* existing indices were reimported. At that point we can't import those indices anymore and such a tool would allow it.
2) Currently there isn't any "cluster state on disk" but rather a collection of files on different levels - cluster settings and such on the top level and per index metadata in each index folder (though that will change it  the future). The tool should just go into a specific index and change the metadata file in it.
3) We should verify the node is not running at the time.
4) We should have a test that verifies what happens where someone renames an index on disk (within its UUID named folder) and creates a conflict between data folders/cluster state where an index with the same uuid has different names.
5) We had the concern of having to maintain multiple complex bash script. If not already the case we should make the bash (and bat) be as simple as possible wrappers around java where do and test all commands/actions/param testing. This will make it more accessible for people who do not live in bash/bat

Another question that came up is whether we see another use case for index on disk renaming other than dangling indices. If you know one, please speak up.

**Comment by bleskes** [comment]
While being a valid idea, it hasn't seen any interest in the last (almost) 2 years and we have no concrete plans to implement. I'm going to close it for now. We can re-open if the need occurs.
