### ISSUE TITLE
Reindex multiple indices with a wildcard

### ISSUE THREAD

**Issue by loekvangool** [elastic/elasticsearch#19662]
**Describe the feature**:
Would be great if the Reindex API would support wildcards.

```
GET _cat/indices/logstash-*
logstash-2016-01-01
logstash-2016-01-02

POST /_reindex
{
  "source": {
    "index": "logstash-*"
  },
  "dest": {
    "index": "logstash-new-*"
  }
}

GET _cat/indices/logstash-*
logstash-2016-01-01
logstash-2016-01-02
logstash-new-2016-01-01
logstash-new-2016-01-02
```

**Comment by babadofar** [comment]
Did you see this issue https://github.com/elastic/elasticsearch/pull/18654
Reindex from multiple wildcard index into a new named index already works without script.
Apparently you can use painless scripting to name the new index using parts of the old name.

**Comment by clintongormley** [comment]
Yep, we're not going to add direct support for mapping multiple source indices to multiple target indices, as it is very use case dependent.  The scripting approach provides all the flexibility you need.  Also, it is often better to run these jobs separately to limit the impact of failure.
