### ISSUE TITLE
Rename `_operation` to `result` and rework a few of the responses

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#19664]
I propose we rename `_operation` and make its return values a little more intuitive:

Right now when you index you when you index like so:
```
curl -s -XPOST localhost:9200/test/test/1?pretty -d'{"test": "test"}' | grep operation
```
You get `"_operation": "create"`. Let's change that to `"result": "created"`. If you do the same thing again right now you'll get `"_operation": "index"`. Let's change that to `"result": "updated"`.

Right now when you delete like so:
```
curl -s -XDELETE localhost:9200/test/test/1?pretty | grep operation
```
You get `"_operation": "delete"`. Let's change it to `"result": "deleted"`. If you try again you get `"_operation": "noop"`. Lets change it to `"result": "not_found"`.

Right now when you update like so:
```
curl -s -XPOST localhost:9200/test/test/1/_update?pretty -d '{
    "doc" : {
        "test" : "test"
    },
    "doc_as_upsert" : true
}' | grep operation
```
You get `"_operation": "create"`. Let's change it to `"result": "created"`. If you try again you get `"_operation": "noop"`. Lets change it to `"result": "noop"`. It should also return `"result": "updated"` if it updates the document.

Note that we still return good results for conflicts using the HTTP status. This is how it works now:
```
curl -s -XPOST localhost:9200/test/test/_bulk?pretty -d'
{"create": {"_id": "1"}}
{"test": "test"}
'
```
returns
```
{
  "took" : 1,
  "errors" : true,
  "items" : [
    {
      "create" : {
        "_index" : "test",
        "_type" : "test",
        "_id" : "1",
        "status" : 409,
        "error" : {
          "type" : "version_conflict_engine_exception",
          "reason" : "[test][1]: version conflict, document already exists (current version [1])",
          "index_uuid" : "5EIrYSj0QKimIvsWcmqlZQ",
          "shard" : "3",
          "index" : "test"
        }
      }
    }
  ]
}
```
Which is great.

Updates also properly return 404s when you ask them to update a thing that doesn't exist:
```
curl -s -XPOST localhost:9200/test/test/2/_update?pretty -d '{
    "doc" : {
        "test" : "test"
    }
}'
```
returns:
```
"error" : {
  "root_cause" : [
    ...
  ],
  "type" : "document_missing_exception",
  "reason" : "[test][2]: document missing",
  "index_uuid" : "5EIrYSj0QKimIvsWcmqlZQ",
  "shard" : "2",
  "index" : "test"
},
"status" : 404
```
It looks similar in the bulk response, including returning the status. Wonderful.

This came from a voice chat with @bleskes and @colings86.

One interesting question that came up is "why don't we just use HTTP status instead of `_operation`/`result`?" The answer is that `noop` and `updated` both map to `200 OK`.

Edited: `updated` used to be called `modified`.

**Comment by nik9000** [comment]
> One interesting question that came up is "why don't we just use HTTP status instead of _operation/result?" The answer is that noop and index both map to 200 OK.

Now that I think about it, with this change the `result` could *derive* the HTTP status as well. It is just that `noop` and `index` would both map to `200 OK`.

**Comment by nik9000** [comment]
@clintongormley, could you have a look at this?

**Comment by nik9000** [comment]
Adding `discuss` label so I can get consensus from folks.

**Comment by bleskes** [comment]
we discussed this on fix it friday and we like it. The only request was to change the `result: modified` to `result: updated`. I tried to channel @nik9000 and explain he found it confusing w.r.t the `_update` API but people felt that's actually good and liked it better.

**Comment by nik9000** [comment]
> I tried to channel @nik9000 and explain he found it confusing w.r.t the _update API but people felt that's actually good and liked it better.

Thanks for trying to channel me while I was sleeping. I'm ok with `updated` even if it is less good. I'll go and change the issue description.
