### ISSUE TITLE
Cardinality aggregation not working with term aggregation using include/exclude filters

### ISSUE THREAD

**Issue by dobariya** [elastic/elasticsearch#19683]
**Elastic version-2.3.3**:

**JVM-1.8**:

**OS-Windows Server 2008 R2**:

**We want distinct count on each term aggregation performed so we used below query to perform the same using cardinality aggregation with term aggregation.But we found that cardinality is not working when used "include filters" with term aggregation.Total distinct names in ES we have 20 and after include filters is applied we have distinct 4 names but cardinality is not able to get and always return 20.Please look into this or else correct me if i have missed anything to get the desired output.**:

Query

```
{
  "size": 0,
  "aggs": {
    "filter": {
      "filter": {},
      "aggs": {
        "Names": {
          "terms": {
            "field": "names",
            "size": 100,
            "order": [
              {
                "_count": "desc"
              }
            ],
            "include":"da.*"            
          }
        },
        "count": {
          "cardinality": {
            "field": "names"
          }
        }        
      }
    }
  }
}
```

Returned result

```
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 74204,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "filter": {
      "doc_count": 74204,
      "Names": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": [
          {
            "key": "daren_farmer",
            "doc_count": 9437
          },
          {
            "key": "dan_hyvl",
            "doc_count": 4003
          },
          {
            "key": "danny_mccarty",
            "doc_count": 2092
          },
          {
            "key": "dana_davis",
            "doc_count": 2073
          }
        ]
      },
      "count": {
        "value": 20
      }
    }
  }
}
```

**Comment by jpountz** [comment]
This is because aggregation work on documents, not values. So all documents that have at least one value that matches the include condition will go through the cardinality aggregation.

So for instance if a document has two values `danemark` and `germany`, the terms aggregation will not return counts for `germany` since it does not match the regex, but the cardinality agg will still see it.

**Comment by jpountz** [comment]
A workaround could be to index every value as a nested document, but this has some performance implications.
