### ISSUE TITLE
Percolator doesn't accept dot notation for sub-field as filter

### ISSUE THREAD

**Issue by jalberto** [elastic/elasticsearch#19680]
**Elasticsearch version**: 2.3.3
**JVM version**: 1.8
**OS version**: ubuntu 16.04

**Description of the problem including expected versus actual behavior**:
I cannot register a percolator using dot notation for sub-fields in a filter. I get this error:

    Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Field name [state.raw] cannot contain '.'"}],"type":"mapper_parsing_exception","reason":"Field name [state.raw] cannot contain '.'"},"status":400}

Expected behaviour is to be able to register the percolator

**Steps to reproduce**:
 1. Create a mapping with a not-analysed raw sub-field eg:

```
    "state": {
        "type": "string",
        "fields": {
          "state": {
            "type": "string"
          },
          "raw": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      },
```

 2. Register a percolator:

```
    {
   "query":{
      "query_string":{
         "query":"\"foo\"",
         "default_operator":"AND"
      }
   },
   "filter":{
      "bool":{
         "must":[
            {
               "range":{
                  "date":{
                     "lt":"2016-04-30",
                     "gte":"1950-01-01"
                  }
               }
            },
            {
               "term":{
                  "state.raw":"foo"
               }
            }
         ],
         "should":{ }
          }
       }
    }
```
 
 3. Get 400 Error

**Comment by kingigi** [comment]
I replaced  "state.raw"  with  "[state][raw]" and it seems to work.
Does that work for you?

**Comment by clintongormley** [comment]
Hi @jalberto 

You shouldn't be using `filter` in the percolator.  It's actually called `post_filter` these days.  This is a filter that is applied after aggregations are calculated and before search hits are returned.

This ends up being indexed in the percolator as a field called `state.raw`, which is illegal.

Your entire query should be under the `query` key, so you could do, for instance (using the query dsl syntax in 2.x):

    {
      "query": {
        "bool": {
          "must": [
            {
              "query_string": {
                "query": "\"foo\"",
                "default_operator": "AND"
              }
            }
          ],
          "filter": [
            {
              "range": {
                "date": {
                  "lt": "2016-04-30",
                  "gte": "1950-01-01"
                }
              }
            },
            {
              "term": {
                "state.raw": "foo"
              }
            }
          ]
        }
      }
    }
