### ISSUE TITLE
EquivalenceIT fails reproducibly with a seed

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#19697]
```
  2> REPRODUCE WITH: gradle :core:integTest -Dtests.seed=A4648847991E5C27 -Dtests.class=org.elasticsearch.search.aggregations.EquivalenceIT -Dtests.method="testRandomRanges" -Dtests.security.manager=true -Dtests.jvms=12 -Dtests.locale=nn-NO -Dtests.timezone=Europe/Helsinki
FAILURE 5.55s J10 | EquivalenceIT.testRandomRanges <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 4 expected:<889> but was:<890>
   >    at __randomizedtesting.SeedInfo.seed([A4648847991E5C27:D00DCF66E03EFC10]:0)
   >    at org.elasticsearch.search.aggregations.EquivalenceIT.testRandomRanges(EquivalenceIT.java:186)
   >    at java.lang.Thread.run(Thread.java:745)
```

**Comment by chengpohi** [comment]
@nik9000 I have done some investigations about this test failed, this is caused when use seed: **A4648847991E5C27**, it will generate one number: **83.99999909626781**, but for **idx type** without set values mapping, it choose the **float type** mapping for it, this will caused rounding. so it fail.

**Comment by chengpohi** [comment]
I have created a pull request for fixing this: https://github.com/elastic/elasticsearch/pull/19701 

but I am not sure how can I attach this pull request into this issue, Is there some way to do it? Thanks, :)
