### ISSUE TITLE
when search, routing settings invalid

### ISSUE THREAD

**Issue by sshling** [elastic/elasticsearch#19714]
**Elasticsearch version**: 2.1.2

**JVM version**:1.8

**OS version**:cent os 7.0

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
- create index mapping
```
POST routingtest
{
  "mappings": {
    "t": {
      "_routing": {
        "required": true
      },
      "properties": {
        "title": {
          "type": "string"
        }
      }
    }
  }
}
```
- insert test data
```
POST routingtest/t/1?routing=45
{
  "title": "routing=45"
}
POST routingtest/t/2?routing=47
{
  "title": "routing=47"
}
```

- query  :
```
routingtest/t/_search?routing=45
{
  "_shards": {
    "total": 1,
    "failed": 0,
    "successful": 1
  },
  "hits": {
    "hits": [
      {
        "_routing": "45",
        "_index": "routingtest",
        "_type": "t",
        "_source": {
          "title": "routing=45"
        },
        "_id": "1",
        "_score": 1
      },
      {
        "_routing": "47",
        "_index": "routingtest",
        "_type": "t",
        "_source": {
          "title": "routing=47"
        },
        "_id": "2",
        "_score": 1
      }
    ],
    "total": 2,
    "max_score": 1
  },
  "took": 1,
  "timed_out": false
}
```
result unexpected, two doc all output,but I think only _routing=45 output ,why so ？

ths

**Comment by cbuescher** [comment]
Hi,
this is because the hash of the routing value can map to the same shard. 
In the future, please raise questions like this in the user forum first. Elastic reserves GitHub for bug reports and feature requests but provides a Discourse forum and IRC channels for general questions at https://discuss.elastic.co/
