### ISSUE TITLE
Disable norms for all fields

### ISSUE THREAD

**Issue by ebuildy** [elastic/elasticsearch#19716]
**Describe the feature**:

Nowsaday many people use elasticsearch with the ELK stack for logging management, and so, they want  to optimize elasticsearch for this. Disabling norms seems a good optimization but this is not possible at index level (only by field), so, is it possible to implement "norm" setting at index setting level?

**Comment by jpountz** [comment]
You could do this easily with an index template?

**Comment by ebuildy** [comment]
Looks like nop, from https://discuss.elastic.co/t/how-to-disable-norms-for-all-field/27232 .

**Comment by jasontedor** [comment]
I'm not convinced that that Discourse post is correct.

**Comment by jasontedor** [comment]
This is just a sketch, but I think that you can do something like this:

```json
curl -XPUT localhost:9200/i?pretty=1 -d '
{
  "mappings": {
    "_default_": {
      "_all": { "enabled" : true, "omit_norms" : true },
      "dynamic_templates": [ {
        "omit_norms": {
          "match_mapping_type": "*",
          "mapping": {
            "omit_norms": true
          }
        }
      } ]
    }
  }
}'
```

**Comment by clintongormley** [comment]
`omit_norms` is deprecated.  instead you should use this:

    PUT /_template/template?pretty=1
    {
      "template" : "*",
      "mappings": {
        "_default_": {
          "_all": { "enabled" : true, "omit_norms" : true },
          "dynamic_templates": [ {
            "omit_norms": {
              "match_mapping_type": "*",
              "mapping": {
                "norms": {
                  "enabled": false
                }
              }
            }
          } ]
        }
      }
    }

**Comment by michaelbannister** [comment]
The `_default_` mapping is no longer an option. Is there an alternative method of disabling `norms` globally?

**Comment by hajdukd** [comment]
Im also interested in this.

**Comment by jpountz** [comment]
If you want to change Elasticsearch's default dynamic mappings to disable norms by default, you can do the following at index creation time:

```
PUT my_index
{
  "mappings": {
    "dynamic_templates": [
      {
        "strings": {
          "match_mapping_type": "string",
          "mapping": {
            "type": "text",
            "norms": false,
            "fields": {
              "raw": {
                "type":  "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      }
    ]
  }
}      }
          }
        }
      }
    ]
  }
}
```

**Comment by hajdukd** [comment]
@jpountz I've ported the solution proposed by @clintongormley to 7.0.0+ ES and more or less its:
```
    "mappings": {
      "dynamic_templates": [
        ....,
        {
          "omit_norms": {
            "match_mapping_type": "*",
            "mapping": {
              "norms": false
            }
          }
        }
      ]
    }
```
But it has to be the last mapping to not take precedence over other ones, which also have to be marked with "norms: false".

**Comment by kladiv** [comment]
Hi @hajdukd ,
in ES 7.15 i see the following deprecation message concerning the `omit_norms` block (i guess):
```
{"type": "deprecation.elasticsearch", "timestamp": "2021-11-30T22:26:10,996Z", "level": "DEPRECATION", "component": "o.e.d.i.m.FieldMapper", "cluster.name": "esprod", "node.name": "esprod-master-0", "message": "Parameter [norms] is used in a dynamic template mapping and has no effect on type [null]. Usage will result in an error in future major versions and should be removed.", "key": "norms", "cluster.uuid": "jPSAvlWrRVqU0ojIpbUQLQ", "node.id": "66MnBDwzTzKJONQF9MtN7w"  }
```

So, is it going to stop working in the next releases?
Thank you

**Comment by ebuildy** [comment]
All solutions are quite complex to use.

This functionnality is possible to configure a default "similarity" (see https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html#default-base ), so a default "omit_norm" at index level make sense.
