### ISSUE TITLE
Master: Netty4 rest tests take much longer under linux

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#19711]
**Elasticsearch version**: master

**JVM version**: 1.8.0_91
**OS version**:  Fedora 23, Ubuntu

**Description of the problem including expected versus actual behavior**:
Running the netty 4 tests under fast linux boxes turns out to be much slower than under osx using a far slower notebook. Asked several other developers to verify on their linux workstations, where the same happened.

I only have remote SSH access to a fast linux box and havent gotten a profiler running via SSH correctly yet, so my current findings are rather external. Will try to setup ASAP.

Two current findings, which I cannot yet make any sense of

* I/O seems huge when the test runs. Running `dstat  -r -d -c --disk-util` while the test runs, shows a nearly 100% utilization of the disk, even though there are only 51MB of logs written after a full test run. The test ran on an SSD.
* Running sysdig for 90 seconds (created 500MB logs) while the test was running, shows that it spends most time in `epoll` and `futex` system calls (far more time than the 90 seconds, so must be run in parallel), could not spot any huge file I/O however.

**Steps to reproduce**:
 1. `cd modules/transport-netty4`
 2. `gradle integTest -Dtests.class='*.Netty4ClientYamlTestSuiteIT'`

Also, reducing the number of nodes from two to one makes the tests go faster (in both cases), but they are still of by a factor of two between that fast linux workstation and my notebook.

**Comment by rmuir** [comment]
This is not related to the network. Instead each node constantly fsyncs over and over, various stacks looking like this:

```
TRACE 307088:
  sun.nio.ch.FileDispatcherImpl.force0(FileDispatcherImpl.java:Unknown line)
  sun.nio.ch.FileDispatcherImpl.force(FileDispatcherImpl.java:76)
  sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:386)
  org.apache.lucene.util.IOUtils.fsync(IOUtils.java:420)
  org.elasticsearch.gateway.MetaDataStateFormat.write(MetaDataStateFormat.java:139)
  org.elasticsearch.index.shard.IndexShard.persistMetadata(IndexShard.java:1527)
  org.elasticsearch.index.shard.IndexShard.<init>(IndexShard.java:268)
  org.elasticsearch.index.IndexService.createShard(IndexService.java:343)
...
TRACE 307239:
  sun.nio.ch.FileDispatcherImpl.force0(FileDispatcherImpl.java:Unknown line)
  sun.nio.ch.FileDispatcherImpl.force(FileDispatcherImpl.java:76)
  sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:386)
  org.elasticsearch.index.translog.TranslogWriter.create(TranslogWriter.java:98)
  org.elasticsearch.index.translog.Translog.createWriter(Translog.java:381)
  org.elasticsearch.index.translog.Translog.<init>(Translog.java:204)
```

So cpu samples are looking like this:
```
CPU SAMPLES BEGIN (total = 1555901) Mon Aug  1 12:28:09 2016
rank   self  accum   count trace method
   1 98.05% 98.05% 1525506 306145 sun.nio.ch.EPollArrayWrapper.epollWait
   2  0.12% 98.17%    1872 307128 sun.nio.ch.FileDispatcherImpl.force0
   3  0.12% 98.28%    1791 307088 sun.nio.ch.FileDispatcherImpl.force0
   4  0.11% 98.39%    1713 307129 sun.nio.ch.FileDispatcherImpl.force0
   5  0.11% 98.50%    1644 307089 sun.nio.ch.FileDispatcherImpl.force0
   6  0.08% 98.58%    1267 307239 sun.nio.ch.FileDispatcherImpl.force0
   7  0.08% 98.66%    1185 307232 sun.nio.ch.FileDispatcherImpl.force0
   8  0.07% 98.73%    1162 307271 sun.nio.ch.FileDispatcherImpl.force0
   9  0.07% 98.80%    1106 307270 sun.nio.ch.FileDispatcherImpl.force0
  10  0.05% 98.85%     725 307450 sun.nio.ch.FileDispatcherImpl.force0
  11  0.05% 98.89%     719 307453 sun.nio.ch.FileDispatcherImpl.force0
  12  0.05% 98.94%     713 307436 sun.nio.ch.FileDispatcherImpl.force0
  13  0.04% 98.98%     650 307455 sun.nio.ch.FileDispatcherImpl.force0
  14  0.04% 99.02%     616 307446 sun.nio.ch.FileDispatcherImpl.force0
  15  0.04% 99.06%     609 307456 sun.nio.ch.FileDispatcherImpl.force0
  16  0.03% 99.09%     504 307254 sun.nio.ch.FileDispatcherImpl.force0
  17  0.02% 99.12%     380 306430 sun.nio.ch.FileDispatcherImpl.force0
  18  0.02% 99.13%     271 307454 sun.nio.ch.FileDispatcherImpl.force0
  19  0.01% 99.15%     201 306431 sun.nio.ch.FileDispatcherImpl.force0
CPU SAMPLES END
```

**Comment by rmuir** [comment]
The reason that it is faster on OS X, is because OS X fsync is worthless on java:

https://bugs.openjdk.java.net/browse/JDK-8080589

**Comment by jasontedor** [comment]
I independently discovered the same cause as @rmuir, this has nothing to do with Netty 4, it's all from excessive fsyncs. The question then becomes why are the fsyncs so excessive? The same slowdown can be observed on the Netty 3 tests if the Netty 3 tests are put on equal ground with the Netty 4 tests by modifying them to also use two nodes:

```diff
diff --git a/modules/transport-netty3/build.gradle b/modules/transport-netty3/build.gradle
index 7b8b94a..e13170e 100644
--- a/modules/transport-netty3/build.gradle
+++ b/modules/transport-netty3/build.gradle
@@ -36,6 +36,15 @@ dependencies {
     compile 'io.netty:netty:3.10.6.Final'
 }
 
+integTest {
+    includePackaged = true
+    cluster {
+        setting 'http.type', 'netty3'
+        setting 'transport.type', 'netty3'
+        numNodes = 2
+    }
+}
+
 thirdPartyAudit.excludes = [
         // uses internal java api: sun.security.x509 (X509CertInfo, X509CertImpl, X500Name)
         'org.jboss.netty.handler.ssl.util.OpenJdkSelfSignedCertGenerator',
```

On an OS X laptop, for Netty 3:

```
$ Darwin jason-mbp.tedor.me 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
$  gradle :modules:transport-netty3:integTest -Dtests.class='*.Netty3ClientYamlTestSuiteIT' 
.
.
.
BUILD SUCCESSFUL                                                                                                                                                        

Total time: 1 mins 26.048 secs 
```

On a Fedora workstation (i7-5930K, *very* fast Samsung 950 Pro SSD), for Netty 3:

```
$ uname -a
Linux totoro.tedor.me 4.5.7-202.fc23.x86_64 #1 SMP Tue Jun 28 18:22:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ gradle :modules:transport-netty3:integTest -Dtests.class='*.Netty3ClientYamlTestSuiteIT' 
.
.
.
BUILD SUCCESSFUL

Total time: 4 mins 12.431 secs
```

On an OS X laptop, for Netty 4:

```
$ Darwin jason-mbp.tedor.me 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
$ gradle :modules:transport-netty4:integTest -Dtests.class='*.Netty4ClientYamlTestSuiteIT' 
.
.
.
BUILD SUCCESSFUL                                                                                                                                                        

Total time: 1 mins 2 secs
```

On a Fedora workstation (i7-5930K, *very* fast Samsung 950 Pro SSD), for Netty 4:

```
$ uname -a
Linux totoro.tedor.me 4.5.7-202.fc23.x86_64 #1 SMP Tue Jun 28 18:22:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ gradle :modules:transport-netty4:integTest -Dtests.class='*.Netty4ClientYamlTestSuiteIT' 
.
.
.
BUILD SUCCESSFUL

Total time: 4 mins 7.784 secs
```

**Comment by rmuir** [comment]
You can also see it easily with a mac:

```
  JDK Version           : Oracle Corporation 1.8.0_66 [Java HotSpot(TM) 64-Bit Server VM 25.66-b17]
...
BUILD SUCCESSFUL

Total time: 2 mins 19.326 secs
```

```
  JDK Version (compile) : Oracle Corporation 9-ea [Java HotSpot(TM) 64-Bit Server VM 9-ea+129]
...
BUILD SUCCESSFUL

Total time: 5 mins 39.762 secs
```

**Comment by bleskes** [comment]
This is a good (and surprising) find. For my understanding - what makes the netty rest test different (if they are actually different) from the normal tests and rest test? 

Re the fsyncs - at least the stack traces Robert found show the persisting of the initial metadata associated with a shard - one is the state file, which is only written when a shard is first created and when, if it all, it is promoted to a primary. The second stack trace is fsyncing the initial translog files created with a fresh translog.

Next to that there are Index level state files that in theory (long term) we can stop fsyncing once we move to persistent cluster state publishing queue. 

Is there anything else in the stack traces you guys saw? As @jasontedor already pointed out in another channel, reducing the shard count in the test is an immediate win.

**Comment by rmuir** [comment]
I run the test like this to produce [java.hprof.txt](https://github.com/elastic/elasticsearch/files/394687/java.hprof.txt) for each JVM

```
gradle integTest -Dtests.class='*.Netty4ClientYamlTestSuiteIT' -Dtests.jvm.argline='-agentlib:hprof=cpu=samples,depth=20,interval=1'
... wait
... ^C after say 400 tests, before it finishes so it dumps, else we kill -9 and you get nothing
$ find . -name java.hprof.txt
./build/testrun/integTest/J0/java.hprof.txt
./build/cluster/integTest node1/cwd/java.hprof.txt
./build/cluster/integTest node0/cwd/java.hprof.txt
```

You can see all the stacks from this file. Some improvements are possible, e.g. renameTempFilesSafe can probably be sped up with https://issues.apache.org/jira/browse/LUCENE-7373, as we don't need to sync metadata after each file one-by-one, just a single time at the end. But by frequency that is one of the least common.

**Comment by rmuir** [comment]
> As @jasontedor already pointed out in another channel, reducing the shard count in the test is an immediate win.

Separately I agree with this. A FileSystemProvider approach like what unit tests use (https://github.com/apache/lucene-solr/blob/master/lucene/test-framework/src/java/org/apache/lucene/mockfile/DisableFsyncFS.java) is not so good here, because we have to box/unbox Path objects, very invasive and not so realistic. 

I think it would be better to have just a few simple integration testing instead for the network stuff, and stronger unit tests... it just needs to meet the contract of Transport or whatever apis it implements.

**Comment by rmuir** [comment]
Here is my solution, its fire and forget and these tests become 45 seconds.

```
/* gcc -fPIC -shared -o disable_fsync.so disable_fsync.c */
int fsync(int fd) {
  return 0;
}

int fdatasync(int fd) {
  return 0;
}
```

in `.profile` i add this:

`alias gradle='LD_PRELOAD=/home/rmuir/disable_fsync.so gradle'`

**Comment by bleskes** [comment]
Thanks @rmuir . Indeed most of those stacks are part of shard creations. There are some index metadata persisting that I already mentioned and some recovery related renaming of temporary files that I think was what you were referring. I don't see any quick/easy wins here  (putting aside your wonderful solution :))

**Comment by s1monw** [comment]
there is another option. I think we can maybe reduce the number of shards to 1 or 2 in these tests. I think that would still give use the integration coverage that we want.

**Comment by javanna** [comment]
@s1monw see #19742 ;)

**Comment by s1monw** [comment]
good @javanna
