### ISSUE TITLE
`_source` field is absent when using `explain` API

### ISSUE THREAD

**Issue by llRandom** [elastic/elasticsearch#19722]
**Elasticsearch version**: 2.3.3

**JVM version**: 1.8.0_91

**OS version**: Windows Service 2012 R2

**Description of the problem including expected versus actual behavior**:
If I set `explain` argument to `true`, response body doesn't return `_source` field for hits. I've also tried to specify `_source` argument to `true` in request (tried both body and querystring) but it didn't help.

**Steps to reproduce**:
 1. Set body parameter `explain` to `true`
 2. Set body parameter `source` to `true`
 3. Execute search request

**Comment by clintongormley** [comment]
This works just fine:

    PUT t/t/1
    {
      "foo": "bar"
    }
    
    GET t/_search
    {
      "explain": true, 
      "query": {
        "match": {
          "foo": "bar"
        }
      }
    }

returns:

    {
      "took": 2,
      "timed_out": false,
      "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
      },
      "hits": {
        "total": 1,
        "max_score": 0.30685282,
        "hits": [
          {
            "_shard": 3,
            "_node": "CjaO7NUOSJGrxp32Z5-KZQ",
            "_index": "t",
            "_type": "t",
            "_id": "1",
            "_score": 0.30685282,
            ########### HERE'S THE SOURCE FIELD ###########
            "_source": {
              "foo": "bar"
            },
            "_explanation": {
              "value": 0.30685282,
              "description": "weight(foo:bar in 0) [PerFieldSimilarity], result of:",
              "details": [
                {
                  "value": 0.30685282,
                  "description": "fieldWeight in 0, product of:",
                  "details": [
                    {
                      "value": 1,
                      "description": "tf(freq=1.0), with freq of:",
                      "details": [
                        {
                          "value": 1,
                          "description": "termFreq=1.0",
                          "details": []
                        }
                      ]
                    },
                    {
                      "value": 0.30685282,
                      "description": "idf(docFreq=1, maxDocs=1)",
                      "details": []
                    },
                    {
                      "value": 1,
                      "description": "fieldNorm(doc=0)",
                      "details": []
                    }
                  ]
                }
              ]
            }
          }
        ]
      }
    }


You haven't provided a recreation so i can't tell what you're doing wrong
