### ISSUE TITLE
Not able to Assemble using Gradle

### ISSUE THREAD

**Issue by blueelvis** [elastic/elasticsearch#19726]
**Elasticsearch version**: Latest Source

**JVM version**: 1.8.0_101

**OS version**: Windows 10

**Description of the problem including expected versus actual behavior**:
I forked the ElasticSearch repository and then cloned it. I downloaded Gradle 2.13 (Considering that Gradle 2.14 is not working as of yet) and when I ran `gradle assemble` , I am getting errors.

**Steps to reproduce**:
 1. Clone repository
 2. Open the repository directory while making sure Gradle is accessible.
 3. Try `gradle assemble`

**Provide logs (if relevant)**:

> * Where:
> Build file 'D:\dev\elasticsearch\build.gradle' line: 21
> 
> * What went wrong:
> Could not compile build file 'D:\dev\elasticsearch\build.gradle'.
> > startup failed:
>   build file 'D:\dev\elasticsearch\build.gradle': 21: unable to resolve class org.eclipse.jgit.lib.Repository
>  @ line 21, column 1.
>      import org.eclipse.jgit.lib.Repository
>      ^
> 
>   build file 'D:\dev\elasticsearch\build.gradle': 22: unable to resolve class > org.eclipse.jgit.lib.RepositoryBuilder
>  @ line 22, column 1.
>      import org.eclipse.jgit.lib.RepositoryBuilder
>      ^
> 
>   build file 'D:\dev\elasticsearch\build.gradle': 20: unable to resolve class > com.bmuschko.gradle.nexus.NexusPlugin
>  @ line 20, column 1.
>      import com.bmuschko.gradle.nexus.NexusPlugin
>      ^
> 
>   3 errors
> 

More Verbose Log - http://pastebin.com/LT0GeM46

**Comment by jasontedor** [comment]
Sorry, I think that you have something specific in your environment because this does not reproduce. If you're still looking for help, can I suggest that you open a topic on the [Elastic Discourse forum](https://discuss.elastic.co), we reserve GitHub for verified bug reports and feature requests.
