### ISSUE TITLE
Rename TransportXXXAction classes to XXXTransportAction

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#19737]
Just a proposal here. Feel free to close if non sense.

We have today the following classes for actions:
- `XXXAction`
- `XXXRequest`
- `XXXRequestBuilder`
- `XXXResponse`
- `TransportXXXAction`

When you try to reduce the number of packages, let say for a plugin for example, you might want to put all your actions within the same package. For example, see the [reindex plugin](https://github.com/elastic/elasticsearch/tree/master/modules/reindex/src/main/java/org/elasticsearch/index/reindex):

It has (skipping non related classes):

```
├── DeleteByQueryAction.java
├── DeleteByQueryRequest.java
├── DeleteByQueryRequestBuilder.java
├── ReindexAction.java
├── ReindexRequest.java
├── ReindexRequestBuilder.java
├── RestDeleteByQueryAction.java
├── RestReindexAction.java
├── RestRethrottleAction.java
├── RestUpdateByQueryAction.java
├── RethrottleAction.java
├── RethrottleRequest.java
├── RethrottleRequestBuilder.java
├── TransportDeleteByQueryAction.java
├── TransportReindexAction.java
├── TransportRethrottleAction.java
├── TransportUpdateByQueryAction.java
├── UpdateByQueryAction.java
├── UpdateByQueryRequest.java
├── UpdateByQueryRequestBuilder.java
```

As a developer, I have to scroll up and down every time when I want to open the TransportAction associated with a given Action.

The proposal is to rename `TransportXXXAction` to `XXXTransportAction` so all those related classes will be grouped all together.

Thoughts?

Depending on the result of this discussion, we can also imagine a follow up for `RestXXXAction` which could become `XXXRestAction`.
The previous example would become:

```
├── DeleteByQueryAction.java
├── DeleteByQueryRequest.java
├── DeleteByQueryRequestBuilder.java
├── DeleteByQueryRestAction.java
├── DeleteByQueryTransportAction.java
├── ReindexAction.java
├── ReindexRequest.java
├── ReindexRequestBuilder.java
├── ReindexRestAction.java
├── ReindexTransportAction.java
├── RethrottleAction.java
├── RethrottleRequest.java
├── RethrottleRequestBuilder.java
├── RethrottleRestAction.java
├── RethrottleTransportAction.java
├── UpdateByQueryAction.java
├── UpdateByQueryRequest.java
├── UpdateByQueryRequestBuilder.java
├── UpdateByQueryRestAction.java
├── UpdateByQueryTransportAction.java
```

**Comment by nik9000** [comment]
+1 on doing both. It'd make reading reindex easier and it only has four
actions.

**Comment by abeyad** [comment]
+1

**Comment by nik9000** [comment]
> it transports the reindex action

I think of it as *implementing* the reindex action rather than *transporting* it.

**Comment by dadoonet** [comment]
> I think of it as implementing the reindex action rather than transporting it.

That was my initial thought as well. If it is, we should may be rename with something more obvious like `ReindexActionImplementation` (just a proposal here)?

**Comment by jasontedor** [comment]
> I think of it as implementing the reindex action rather than transporting it.

But that's what I mean? It coordinates and executes the entire action. Look at something like `TransportBroadcastByNodeAction`. At the start of the request, it transports a node-level request to each node responsible for executing node-level operations. Each node receives these requests, executes the operations, and transports the result back to the coordinating node. The coordinating node then collects these results, and notifies the action listener.

**Comment by nik9000** [comment]
> It coordinates and executes the entire action.

I've always thought of the coordination and execution portions as "more than" transporting the action though.

**Comment by javanna** [comment]
I've always referred to these classes in my head as the "transport actions" as opposed to the "rest actions". The latter is the code executed on the rest layer which then delegates to the former, which is the corresponding action that executes on the transport layer. That's why I don't read "transport" as a verb and I would be in favour of the proposed rename.

And the fact that it would help keeping classes for the same api closer rather than far apart is a plus too.

**Comment by dadoonet** [comment]
Do we have any veto on this?
It's "just" about renaming. Should I try to get that before 5.0.0 Beta or GA? Or do we prefer doing this for 6.0?

@clintongormley @s1monw what do you think?

**Comment by dadoonet** [comment]
Should I close it or work on a PR against 6.0 branch?

**Comment by javanna** [comment]
Given that we didn't reach consensus on this, I don't think we should do it. Closing.
