### ISSUE TITLE
[elasticsearch][urgency: low][Error with offline installs when .zip files are stored in elasticsearch plugins directory]

### ISSUE THREAD

**Issue by clintonjimmie** [elastic/elasticsearch#19730]
**Versions:**
**ES:** Elasticsearch 2.3.4
**Plugins:** License 2.3.4, Watcher 2.3.4, Shield 2.3.4, AWS Cloud Plugin 2.3.4

Description of the problem including expected versus actual behavior:

Installing elasticsearch plugins with offline packages gets the error, "ERROR: Could not load plugin descriptor for existing plugin [shield-2.3.4.zip.sha1]. Was the plugin built before 2.0?" if the .zip file is stored in the elasticsearch/plugins directory (eg /home/jimmie/elasticsearch2.3.4/plugins/). This happens with the plugins noted above that we host, but did not happen with a plugin we did not build and provide (I tried with kopf).

Is this expected behavior? Is this something we should throw in the install documents with something like, "Do not store the plugin .zip files in the ES/plugins directory. Why not try /home/user instead?"

Context: Customer is building an elasticseach cluster that will not have internet access. As such, all installs will be done with offline packages.

Steps to reproduce:

1.     Download .zip and .SHA1 files to a machine with access to the internet
2.     Transfer files to elasticsearch node(s) and store files in the elasticsearch/plugins directory
3.     ???^H^H^H^H^H
4.     Install the plugins using bin/plugin install file:///path/to/file/elasticsearch/plugins/plugin.name

Please let me know if you need more information.

Thank you!

**Comment by dadoonet** [comment]
Wrong repo. Closing.
