### ISSUE TITLE
Extend Validate API to also validate the entire request, not just the query component

### ISSUE THREAD

**Issue by geekpete** [elastic/elasticsearch#19733]
Extend the Validate API to perform complete request validation rather than just the query component.

eg:

- overall syntax check
- minimal discovery to see if requested fields specified in _source section exist or not
- other stuff?

**Comment by clintongormley** [comment]
what's the use case here?  why not just run the query?  checking if requested fields exist won't work because they're not required to exist.

For me, the most useful part of the validate query request is the `explanation` that can be requested.

**Comment by geekpete** [comment]
The customer was looking to do a single validate to see if anything was wrong with the entire request.

I guess the current way is validate to test the query component, then try the whole request and catch errors if particular fields don't exist that you're trying to retrieve.

One call that does lots instead of two calls to check the different parts of the request.

**Comment by clintongormley** [comment]
I'd just use the search API directly.  Validate doesn't seem to be of much use here.
