### ISSUE TITLE
Better abstraction for rank evaluation labels

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#19744]
Currently in the [Rating enum](https://github.com/elastic/elasticsearch/blob/feature/rank-eval/modules/rank-eval/src/main/java/org/elasticsearch/index/rankeval/PrecisionAtN.java#L132) we only allow for binary ratings. This is not appropriate for metrics that need graded relevance values. Need to find a better abstraction here.

(also need to find better github labels to file issues like this under)

**Comment by cbuescher** [comment]
@MaineC should we close this? We use int-value ratings now and added threshhold options for metrics that need binary labels.

**Comment by MaineC** [comment]
Closing as #20303 pretty much solves this issue.
