### ISSUE TITLE
[DOCS] Document _cat/tasks API

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#19756]
Now that we have `_cat/tasks`, we should add it to the list of documented `_cat` APIs as well as describe what the various fields mean.

**Comment by debadair** [comment]
Documented, but not included in the list of cat APIs in the Reference section. 
https://github.com/elastic/elasticsearch/blob/5772c1c7dd343b77af082d37db992b0aad68ae3e/docs/reference/cluster/tasks.asciidoc
