### ISSUE TITLE
Java API: unexpected hit count using scroll search

### ISSUE THREAD

**Issue by csquire** [elastic/elasticsearch#19757]
The Java API documentation for [using scroll](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-search-scrolling.html) states that the size-parameter is per shard.  In testing, that is not the behavior I see.

When I run the following code, each scroll response only contains `<size>` results instead of `<size * num shards>` results.  This is occurring in ES 2.3.1.  I tested using wildcard index name that matches 155 indexes (and millions of documents), each with 8 primary shards.

Switching the search type to the deprecated 'scan' type changes the behavior to more closely match the documentation.

Is this expected scroll functionality and the documentation is incorrect?  The main [documentation page on scroll](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-request-scroll.html) makes no reference to size.

Results using scroll:

> Initial Hit Count: 100
> Scroll Hit Count: 100
> Scroll Hit Count: 100
> Scroll Hit Count: 100
> Scroll Hit Count: 100
> etc...

Results using scan:

> Initial Hit Count: 0
> Scroll Hit Count: 123217
> Scroll Hit Count: 16200
> Scroll Hit Count: 16071
> Scroll Hit Count: 16000
> etc...

```
        Settings settings = Settings.settingsBuilder().put(
                "cluster.name", CLUSTER_NAME
        ).build();

        TransportClient tc = TransportClient.builder().settings(settings).build();
        tc.addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName(NODE_IP), 9300));

        SearchRequestBuilder builder = tc.prepareSearch(INDEX)
                .addSort(SortParseElement.DOC_FIELD_NAME, SortOrder.ASC)
                .setScroll(TimeValue.timeValueSeconds(5))
                .setQuery(new MatchAllQueryBuilder())
                .setSize(100);

        SearchResponse response = builder.execute().actionGet();
        System.out.println("Initial Hit Count: " + response.getHits().getHits().length);

        while(true)
        {
            response = tc.prepareSearchScroll(response.getScrollId()).setScroll(TimeValue.timeValueSeconds(5)).execute().actionGet();
            System.out.println("Scroll Hit Count: " + response.getHits().getHits().length);
            if (response.getHits().getHits().length == 0) {
                break;
            }
        }
```

**Comment by s1monw** [comment]
I don't think that documentation hit is accurate. @clintongormley WDYT

**Comment by clintongormley** [comment]
Correct, size is per shard for scanning, not ordinary scrolling.  Note this goes away if you sort by `_doc` instead.

**Comment by ppf2** [comment]
Suggested changes:

*  Remove "per hit" from example code comment and note (https://www.elastic.co/guide/en/elasticsearch/client/java-api/master/java-search-scrolling.html)
*  Add a short paragraph on what it means to specify "size" in a scroll query (https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-scroll.html).
* Update the paragraph starting with "Although we specified a size of 1,000, we get back many more documents." accordingly (https://www.elastic.co/guide/en/elasticsearch/guide/master/scroll.html#scroll)
