### ISSUE TITLE
Remove version type `FORCE` 

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#19769]
The version type `FORCE` was added as an expert option to allow people to roll back changes in the external version use case where they have made mistakes in their synchronization logic.

It's a very dangerous operation as it forgoes all concurrency guarantees and may leave replicas and primaries out of sync. In hind sight I think we should not have added it and the problem goes far enough to warrant it's removal.

Note that long term, we can support this kind of thing when we move the replication logic to rely on sequence numbers for concurrency.

See for example: https://github.com/elastic/elasticsearch/issues/19692

**Comment by s1monw** [comment]
+100
