### ISSUE TITLE
filtered script not registered

### ISSUE THREAD

**Issue by PKFresher** [elastic/elasticsearch#19771]
Elasticsearch version:
1.7
JVM version:
7
OS version:
win7

 1.my query 

```
{
   "query": {
      "filtered": {
         "query": {
            "query_string": {
               "default_field": "question",
               "query": " i love my pet"
            },
            "filter": {
               "script": {
                  "script": "doc['company_id'].value > 100"
               }
            }
         }
      }
   }
}
```

` Error:nested: QueryParsingException[[helloworld_dvvbylgzwt] No query registered for [script]]; }]`

I learn from this page  

 https://www.elastic.co/guide/en/elasticsearch/reference/1.6/query-dsl-script-filter.html

 
what's wrong with my query?

**Comment by dadoonet** [comment]
filter is in query here instead of filtered.

Please ask questions like this on discuss.elastic.co
