### ISSUE TITLE
An example of sorting by a nested field in the guide is incorrect

### ISSUE THREAD

**Issue by swarmer** [elastic/elasticsearch#19779]
I'm not an expert in elasticsearch so I might be wrong, but I believe that [the example in the guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-sorting.html) is missing `"nested_path": ` in the sort block.

[The example](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-request-sort.html#nested-sorting) in the reference seems to correctly include this attribute and states that it is mandatory when sorting by nested fields.

**Elasticsearch version**: 2.3

**Comment by clintongormley** [comment]
This issue was moved to elastic/elasticsearch-definitive-guide#582
