### ISSUE TITLE
Documentation typo in Inner hits

### ISSUE THREAD

**Issue by andremilk** [elastic/elasticsearch#19775]
I believe that there is a typo at this link https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html

> If _inner_hits is defined on a query that supports it then each search hit will contain an inner_hits json object with the following structure:

That _inner_hits is typo, is it not?

**Comment by clintongormley** [comment]
yes, thanks for reporting.  i've fixed this
