### ISSUE TITLE
Indexing keywords should not utf8-encode twice

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#19782]
If you have a keyword field, the value bytes will likely come as utf8 bytes over the network, then be converted to a String when we call `text()` on the json parser from KeywordFieldMapper and finally converted back to utf8 bytes by Lucene's terms dict.

UTF8 conversions are not cheap so it would be nice to avoid this double conversion if possible.

Lucene already supports indexing keywords from utf-8 bytes, but it does not look Jackson supports avoiding the UTF8 conversion. Do I miss it or is it a feature request we should make? Even if it might not come naturally for json given that it is character-based, it should eg. for Smile since it stores strings internally as utf8 bytes.

Note: I only mentioned keyword fields here since text fields need to be converted to utf16 strings anyway since this is the representation we need for char filters, tokenizers and token filters to work.

**Comment by s1monw** [comment]
++ lets see how invasive it is to fix it

**Comment by tlrx** [comment]
> Do I miss it or is it a feature request we should make?

Can't we use `parser.utf8Bytes()` instead of `text()`?

**Comment by jpountz** [comment]
@tlrx I had seen it but it seems to be implemented by `JSonXContentParser`, which returns `new BytesRef(CharBuffer.wrap(parser.getTextCharacters(), parser.getTextOffset(), parser.getTextLength()));` (which does a utf8 conversion) and none of the subclasses override it.

**Comment by s1monw** [comment]
@jpountz I think so, it's reading each byte direclty into a char array so I think the raw info is lost.

**Comment by clintongormley** [comment]
@jpountz this is closed by #19867, no?

**Comment by jpountz** [comment]
No. #19867 was another change that allowed to reduce utf8 conversions, but this issue is still valid.

**Comment by javanna** [comment]
This bug was opened 8 years ago, it has not been addressed so far, and it is not on our radar either. Closing.
