### ISSUE TITLE
The edit field format absent

### ISSUE THREAD

**Issue by sherry-ger** [elastic/elasticsearch#19795]
**Elasticsearch version**:
ES 2.3

**Description of the problem including expected versus actual behavior**:
Please see https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html

The edit field format is absent.

**Comment by colings86** [comment]
@sherry-ger could you describe a bit more about what the issue is here, I'm not following where the bug is?

**Comment by sherry-ger** [comment]
User error - A browser refresh and everything looks fine now.
