### ISSUE TITLE
Remove lat_lon?

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#19792]
The PR that deprecated `lat_lon` in 2.x said:

```
With GeoPoinV2 lat_lon and precision_step parameters will be removed in 5.0. This PR adds deprecation logging for 2.x.
```

Should this be included in 5.0?

**Comment by eskibars** [comment]
cc @nknize

**Comment by nknize** [comment]
Thx @nik9000! Yes, it should be included for 5.0. I'll open a PR to axe it here shortly.

**Comment by clintongormley** [comment]
@nknize i also note that `lat_lon` isn't deprecated in the docs, see https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html#geo-point-params and https://www.elastic.co/guide/en/elasticsearch/reference/current/lat-lon.html

Please could you add the `deprecated[]` annotation to the docs.

**Comment by Mpdreamz** [comment]
Did this already get removed in `5.0.0-beta1` ?

Getting the following message for this mapping:

```json
"location": {
     "type": "geo_point",
     "lat_lon": true
}
```

```json
"Failed to parse mapping [project]: Mapping definition for [location] has unsupported parameters:  [lat_lon : true]",
```

Comparing: 
https://www.elastic.co/guide/en/elasticsearch/reference/2.4/geo-point.html#geo-point-params
https://www.elastic.co/guide/en/elasticsearch/reference/5.x/geo-point.html#geo-point-params

Seems to indicate it has but the mapping breaking changes section does not list it.

**Comment by clintongormley** [comment]
@nknize looks like #20315 needs some breaking changes docs

**Comment by debadair** [comment]
No longer mentioned in the docs & mentioned in 5.0 breaking changes. https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_mapping_changes.html#_literal_geo_point_literal_fields
