### ISSUE TITLE
Should we remove/modify some of the experiment tags in the documentation

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#19798]
Below is a list of the experimental tags that are in the documentation at the time of writing (I've used blame view for the links only so I can skip to the experimental tag in the file). I have added the link to the PR that added the tag and the version it was added in (where I can find it) to each in the list as well as what I think we should do with the tag (remove or keep):

| Feature | Documentation Link | Pull Request | Version Added | Action |
| --- | --- | --- | --- | --- |
|Adjacency Matrix Agg | [docs/reference/aggregations/bucket/adjacency-matrix-aggregation.asciidoc:9](https://github.com/elastic/elasticsearch/blame/master/docs/reference/aggregations/bucket/adjacency-matrix-aggregation.asciidoc#L9)| || Beta 
| Significant Text Agg|[docs/reference/aggregations/bucket/significanttext-aggregation.asciidoc:4](https://github.com/elastic/elasticsearch/blame/master/docs/reference/aggregations/bucket/significanttext-aggregation.asciidoc#L4)| || Keep tag
| Analysis-ICU Rules Customisation | [docs/plugins/analysis-icu.asciidoc:120](https://github.com/elastic/elasticsearch/blame/master/docs/plugins/analysis-icu.asciidoc#L120) | https://github.com/elastic/elasticsearch/pull/13651 | 5.0.0-alpha2 | Keep Tag   - Add note about experimental in Lucene|
| Matrix Aggregation | [docs/reference/aggregations/matrix.asciidoc:4](https://github.com/elastic/elasticsearch/blame/master/docs/reference/aggregations/matrix.asciidoc#L4) | https://github.com/elastic/elasticsearch/pull/18300 | v5.0.0-alpha4 | Keep Tag |
| Scripted Metric Aggregation | [docs/reference/aggregations/metrics/scripted-metric-aggregation.asciidoc:4](https://github.com/elastic/elasticsearch/blame/master/docs/reference/aggregations/metrics/scripted-metric-aggregation.asciidoc#L4) | https://github.com/elastic/elasticsearch/issues/7075 | v1.4.0-beta1 | Keep Tag |
| Moving Average Pipeline Agg `predict` param | [docs/reference/aggregations/pipeline/movavg-aggregation.asciidoc:4](https://github.com/elastic/elasticsearch/blame/master/docs/reference/aggregations/pipeline/movavg-aggregation.asciidoc#L4) | https://github.com/elastic/elasticsearch/issues/10024 | v2.0.0-beta1 | Keep tag |
| Normalizers|[docs/reference/analysis/normalizers.asciidoc:4](https://github.com/elastic/elasticsearch/blame/master/docs/reference/analysis/normalizers.asciidoc#L4)| | |Beta| 
| Flatten Graph Token Filter|[docs/reference/analysis/tokenfilters/flatten-graph-tokenfilter.asciidoc:4](https://github.com/elastic/elasticsearch/blame/master/docs/reference/analysis/tokenfilters/flatten-graph-tokenfilter.asciidoc#L4)| | |Keep tag| 
| Synonym Graph Token Filter |[docs/reference/analysis/tokenfilters/synonym-graph-tokenfilter.asciidoc:4](https://github.com/elastic/elasticsearch/blame/master/docs/reference/analysis/tokenfilters/synonym-graph-tokenfilter.asciidoc#L4)| ||Keep tag | 
| Word Delim Graph Token Filter|[docs/reference/analysis/tokenfilters/word-delimiter-graph-tokenfilter.asciidoc:4](https://github.com/elastic/elasticsearch/blame/master/docs/reference/analysis/tokenfilters/word-delimiter-graph-tokenfilter.asciidoc#L4)| | |Keep tag| 
| Simple Pattern Tokenizer|[docs/reference/analysis/tokenizers/simplepattern-tokenizer.asciidoc:4](https://github.com/elastic/elasticsearch/blame/master/docs/reference/analysis/tokenizers/simplepattern-tokenizer.asciidoc#L4)| | |Keep tag - Lucene| 
| Simple Pattern Split Tokenizer|[docs/reference/analysis/tokenizers/simplepatternsplit-tokenizer.asciidoc:4](https://github.com/elastic/elasticsearch/blame/master/docs/reference/analysis/tokenizers/simplepatternsplit-tokenizer.asciidoc#L4)| | |Keep tag - Lucene| 
| Tasks API|[docs/reference/cluster/tasks.asciidoc:4](https://github.com/elastic/elasticsearch/blame/master/docs/reference/cluster/tasks.asciidoc#L4)| | |Beta | 
| Index Sorting|[docs/reference/index-modules/index-sorting.asciidoc:4](https://github.com/elastic/elasticsearch/blame/master/docs/reference/index-modules/index-sorting.asciidoc#L4)| | |Beta | 
| `index.store.type`|[docs/reference/index-modules/store.asciidoc:35](https://github.com/elastic/elasticsearch/blame/master/docs/reference/index-modules/store.asciidoc#L35)| | |Keep tag | 
| `fixed_auto_queue_size`|[docs/reference/modules/threadpool.asciidoc:97](https://github.com/elastic/elasticsearch/blame/master/docs/reference/modules/threadpool.asciidoc#L97)| | | Keep tag|

**Comment by jpountz** [comment]
Interestingly if I had built the same table, I would probably have the opposite action in most cases. :) 

For instance I think the derivative pipeline aggs or the profile flag map to common use-cases (even though in the case of the profile agg we would probably still need a note that the response format may change). I'd probably also wait for pipeline aggs to be exposed in Kibana since that would be a very good test of the usability of pipeline aggs, but this is something I hope we'll be able to do soon.

On the other hand, I don't like exposing options about internals like the terms agg execution hint or percentiles implementation. In the case of percentiles, I am wondering whether we could replace the option with something that characterizes the data or the expected accuracy without being implementation specific and would allow us to pick an impl internally.

**Comment by colings86** [comment]
Discussed in Fix It Friday and have updated the table to reflect what we talked about

**Comment by javanna** [comment]
@colings86 what is left to do here? anything to discuss further?

**Comment by colings86** [comment]
Nothing to discuss further but the items above that have "remove tag" in the action need to have the experimental tag removed

**Comment by clintongormley** [comment]
@colings86 we should consider which features should use the beta tag instead (ie we will support this feature and plan to keep it, but the API may change significantly)

**Comment by clintongormley** [comment]
Updated the table in the description to account for removed tags in #25727

**Comment by colings86** [comment]
Closing this as its no longer relevant
