### ISSUE TITLE
stats api needs work

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#19809]
See the discussion on https://github.com/elastic/elasticsearch/pull/19717

The stats api has some problems, which makes it hard to safely add new statistics or even keep the current ones working:
- ByteSizeValue is currently used, but its not obvious how to handle "unsupported" or "unbounded" cases, while at the same time using this API. doing "interpretation" to 0 is confusing. Using ByteSizeValue itself, well, its totally unclear about what values it supports. Does it really support negatives? Does it really support -1? In one method you can see logic for e.g. `-1`, in other methods you can see they will be clearly broken if the value is negative. I assume there are missing unit tests as well as missing checks and missing docs and bugs.
- Stats have missing unit tests. It would be flaky to test the results from the jvm, but simple unit tests can be written for e.g. serialization/deserialization logic. This is easy to do and plain old POJO testing, it can ensure all possible range of values (including exceptional cases) will work correctly.
- The wrapper POJOs are missing docs. This makes it hard to work the code, since its not easy to correlate them to the MBean where they come from, and the methods on them to which mbean methods returned that piece of data. Adding `@see` can help, as well as trying to improve the consistency of naming...
- Too much leniency: lots of `catch (Exception)` and allowing things to be null that are unnecessary. For example `ManagementFactory` methods document whether or not something is guaranteed to be there in the jvm, we shouldn't allow these to be null or catch Exceptions. If its not guaranteed, sure, but those are special cases. This leniency hides the fact, for example, that classloader statistics are currently just "dropped" across the wire.

I closed that PR because i don't think we should be piling on more statistics until we fix this stuff...

**Comment by javanna** [comment]
With #20255 and #20327 we added serialization tests. The only missing tests are for `NodeIndicesStats` and all `CommonStats` and subobjects. They need to be reworked I think so that they can be made `Writeable`, immutable and easily testable. They are quite hard to unit test at the moment. I left a TODO [here](https://github.com/elastic/elasticsearch/pull/20327/files#diff-06b2ca5560d0b41e4bbd2b212760ef59R367)

**Comment by minhlongdo** [comment]
Hi, is this being worked on internally?

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
