### ISSUE TITLE
query DSL parse error

### ISSUE THREAD

**Issue by mccheung** [elastic/elasticsearch#19818]
**Elasticsearch version**:  2.3.3  2.3.5

**JVM version**: java version "1.8.0_74"

**OS version**: OSX 10.11.6

**Description of the problem including expected versus actual behavior**:

I used filtered to filter data,  the query json:

	{
    "query" : {
        "filtered" : {
            "query" : {
                "multi_match" : {
                    "operator" : "and",
                    "fields" : [
                        "name",
                        "name_pinyin",
                        "code",
                        "brand_attrs",
                        "properties",
                        "classification"
                    ],
                    "query" : "登山"
                },
                "filter" : {
                    "and" : [
                        {
                            "match" : {
                                "product_tags" : "优惠不愚人"
                            }
                        }
                    ]
                }

            }
        }
    }
	}

If I use this json to query,  it can get right result.

If I change `multi_match` and `filter` index to below: 

	{
    "query" : {
        "filtered" : {
            "query" : {
                "filter" : {
                    "and" : [
                        {
                            "match" : {
                                "product_tags" : "优惠不愚人"
                            }
                        }
                    ]
                },
                "multi_match" : {
                    "operator" : "and",
                    "fields" : [
                        "name",
                        "name_pinyin",
                        "code",
                        "brand_attrs",
                        "properties",
                        "classification"
                    ],
                    "query" : "登山"
                }
            }
        }
    }
	}

It's get below error info:

	{
  		"error" : {
    	"root_cause" : [ {
      	"type" : "query_parsing_exception",
      	"reason" : "No query registered for [filter]",
      	"index" : "XXXXXXX",
      	"line" : 1,
      	"col" : 78
    	} ],
    	"type" : "search_phase_execution_exception",
    	"reason" : "all shards failed",
    	"phase" : "query_fetch",
    	"grouped" : true,
    	"failed_shards" : [ {
      		"shard" : 0,
      		"index" : "XXXXXXXXX",
      		"node" : "hCaDhXEVTYO5Ixd6lrhM7A",
      		"reason" : {
        		"type" : "query_parsing_exception",
        		"reason" : "No query registered for [filter]",
        		"index" : "XXXXXXXXX",
        		"line" : 1,
        		"col" : 78
      		}
    	} ]
  	},
  	"status" : 400
	}

**Comment by dadoonet** [comment]
Please ask questions on discuss.elastic.co.


Filter should be at the same level of query. Not inside.
