### ISSUE TITLE
The `keyword` name is confusing to me.

### ISSUE THREAD

**Issue by jordansissel** [elastic/elasticsearch#19812]
Context: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/462/

The new `keyword` type introduced by https://github.com/elastic/elasticsearch/issues/12394 feels very confusing to me.

I often index data that has multiple words in it, such as sports player names, location names, server names, etc, and had historically made this data in Elasticsearch mapped as a "string which is not_analyzed". This model made sense to me, as it expressed pretty much exactly what I wanted -- a string where the entire contents of the string is the "term" (in ES/Lucene terminology).

The name chosen to call the `keyword` feature feels wrong, to me. "United States" is two words. "San Jose Sharks" is three words. "www.google.com" is a network address with 3 parts. For all of these examples, I have wanted to do terms aggregations or similar operations which require the whole text to be considered a single term. Under this new `keyword` label, these things which have multiple parts are all now called a singular `word` and that very much confuses me.

As a note, I understand the `keyword` type uses only the `keyword` tokenizer, and that we may say that because of this, `keyword` is the correct name for the type. My counter to this is that the `keyword` tokenizer is incorrectly named for the same reason.

Can we change the `keyword` to something that may better reflect what it is?

**Comment by s1monw** [comment]
I think we had this conversations so often already. I agree with you but it was the best name after all discussion and all suggestions. Now is the time to fix it though but I feel like we have already had the discussions. @clintongormley do you recall where those happened

**Comment by suyograo** [comment]
LS would like to be consistent with ES's default of multi-fields (as defined in https://github.com/elastic/elasticsearch/issues/12394), but I am concerned about the upgrade path for all the Logstash-indexed docs out there with `field.raw`. Is the answer to that -- reindexing?

Did we consider using `.raw` for multi-field?

**Comment by rjernst** [comment]
The name originally came up in #11901, and was further discussed in #18195.

**Comment by rjernst** [comment]
And also in #17188

**Comment by jordansissel** [comment]
Closing this in favor of https://github.com/elastic/elasticsearch/issues/18195
