### ISSUE TITLE
Should we remove the experimental tag from Shadow Replicas

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#19822]
This came up in fixItFriday when discussing https://github.com/elastic/elasticsearch/issues/19798 and it was felt that in the case of shadow replicas it warrants it's own issue to discuss whether we still consider this experimental.

/cc @dakrone

**Comment by dakrone** [comment]
I think in order to remove the experimental tag from this, we should add a table with filesystems and whether they do or do not work with shadow replicas. IE, NFS doesn't work, but AzureFS does, etc

**Comment by javanna** [comment]
Support shadow replicas was removed, hence nothing to do here.
