### ISSUE TITLE
Highlighter for multivalue fields

### ISSUE THREAD

**Issue by Hocdoc** [elastic/elasticsearch#19826]
**Describe the feature**:
When running the Elasticsearch highlighter on multivalue fields there is no easy way to get the source of the highlighted fragment.

Workaround: I remove the `em`-Tags, decode it again from Html to plain text and search it in all values of the multivalue field, but this is rather complicated.

It would be a nice feature if the highlighter could return somehow the source of the highlighted fragment f.ex. returning the array index.

**Comment by clintongormley** [comment]
@Hocdoc there's no way to get that information.  a multi-valued field is the same as any other analyzed field, there are just extra fake gaps inserted between values

**Comment by Hocdoc** [comment]
Thanks for your answer!

Although I'm not totally convinced: The highlighter needs the actual content of the field (stored or `_source`), so it should be possible to determine which array index of the source the highlighter is using.
I can do this manually in my code base with my workaround described above, so this should also work in the Highlighter source.
