### ISSUE TITLE
Create a better way of choosing the algorithm for the Percentiles/Percentiles_rank aggregation

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#19820]
At the moment the algorithm for percentiles/percentiles_rank is chosen based on the user explicitly specifying the algorithms name. This is not ideal as it requires the user to understand the algorithms and their use-cases and when to use each one. 

A better solution would be to let the user choose which tradeoffs they wish to make, for example; precision, whether they need support for negative values, whether they care more about accuracy at the extremes or across the whole range, etc.

The above are not concrete suggestion of options we should expose but an example of the kinds of questions a user is more able to decide with the knowledge about their domain but without requiring them to know the actual algorithm. 

This also give us the example to add new algorithms or tweak an algorithm to improve it for the set of tradeoffs the user has selected.

**Comment by markgsimon** [comment]
Is this still an on ongoing issue?

**Comment by colings86** [comment]
@elastic/es-search-aggs

**Comment by wchaparro** [comment]
related to https://github.com/elastic/elasticsearch/issues/95903

**Comment by wchaparro** [comment]
closing as not planned.
