### ISSUE TITLE
HistogramIT.testEmptyWithExtendedBounds fails with -Dtests.seed=3CE91761FF561FDF

### ISSUE THREAD

**Issue by brwe** [elastic/elasticsearch#19833]
See here: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/1366/consoleText

@colings86 I assigned this to you because I you know the test best. Feel free to reassign this to someone else if you don't feel like working on that.

**Comment by colings86** [comment]
@brwe thanks for raising this. I've opened https://github.com/elastic/elasticsearch/pull/19855 to fix it

**Comment by cbuescher** [comment]
LGTM
