### ISSUE TITLE
Docs: function_score description of offset/scale is incorrect

### ISSUE THREAD

**Issue by gibrown** [elastic/elasticsearch#19832]
At https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-function-score-query.html#function-decay

The description of

> scale: Required for all types. Defines the distance from origin at which the computed score will equal decay parameter. 

> offset: If an offset is defined, the decay function will only compute the decay function for documents with a distance greater that the defined offset

Seems to indicate that an offset of 5 days and a scale of five days means that the decay will be 0.5 at 5 days.

But the graph at https://www.elastic.co/guide/en/elasticsearch/reference/current/images/decay_2d.png

And I think the equation say that the decay will be 0.5 at 10 days.

Should say something like:

> scale: Required for all types. Defines the distance from origin + offset at which the computed score will equal decay parameter.

**Comment by dakrone** [comment]
I agree this is a little confusing, we can probably reword it, what do you think @brwe ?

**Comment by brwe** [comment]
> scale: Required for all types. Defines the distance from origin + offset at which the computed score will equal decay parameter.

That is right and I find it a much better explanation. @gibrown want to make the change?
