### ISSUE TITLE
Array index out of bounds in PutMappingRequest#buildFromSimplifiedDef

### ISSUE THREAD

**Issue by arcneon** [elastic/elasticsearch#19836]
**Elasticsearch version**: 2.3.4

**JVM version**: Not relevant

**OS version**: Not relevant

**Description of the problem including expected versus actual behavior**:

Array index out of bounds when trying to create a mapping from a java map. Looking at source of master, the probable cause is the loop variable being incremented inside the loop.

https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/admin/indices/mapping/put/PutMappingRequest.java#L189

**Comment by arcneon** [comment]
Ignore, user error

**Comment by jasontedor** [comment]
I think that you're not using the API correctly, the code is correct here. The items need to be input in pairs ("field", "type=string,store=true"), and that's the reason for the increment (to extract the field name, and then move the loop index to the definition.

**Comment by cbuescher** [comment]
Looking at the way that method is used internally I don't see a problem with the loop. The varargs `Object... source` is supposed be pairs of fieldnames and property lists (e.g. `"field1", "type=string,store=true"`), so although incrementing the counter inside the loop looks strange at first I think its okay. What are you trying to do using this method?

**Comment by cbuescher** [comment]
^ ups, race condition, writing this at the same time as Jason apparently ;-)

**Comment by jasontedor** [comment]
We could add a code comment here, and maybe some input validation. :smile:

**Comment by arcneon** [comment]
Indeed; I was inadvertently passing a map builder instead of a map and it was going through the varargs method instead of the map specific one.
