### ISSUE TITLE
30GB for JVM and full gc unable to free allocated memory

### ISSUE THREAD

**Issue by kubbo** [elastic/elasticsearch#19838]
**Elasticsearch version**:
2.3.4

**JVM version**:
1.8

# some gc log 
[monitor.jvm              ] [Powerpax] [gc][young][132059][21130] duration [756ms], collections [1]/[1.4s], total [756ms]/[10.3m], memory [26.7gb]->[24.1gb]/[29.6gb
], all_pools {[young] [2.7gb]->[3.2mb]/[2.7gb]}{[survivor] [20.6mb]->[240.8mb]/[357.7mb]}{[old] [23.9gb]->[23.9gb]/[26.5gb]}

# doubt
I use bulk to index. 30 billion doc very day. But some node alway out of cluster because long time full gc after some days.
 I dump bin log and find taskManager object cost most of memory(18GB), I doubt why taskManager cost cost many memory ? It cache large number of task(request) ? some body can explain the situation? thanks 

![2016-08-06_023347](https://cloud.githubusercontent.com/assets/8613477/17446938/585d0ce0-5b7e-11e6-8833-b2b16622c631.png)

**Comment by jasontedor** [comment]
Do you have any plugins installed?

**Comment by kubbo** [comment]
Yes, I installed some pluins:
- hq
- ik
- kopf
- license
- marvel-agent,search-guard-2
- search-guard-ssl

**Comment by jasontedor** [comment]
searchguard-ssl is the culprit here: floragunncom/search-guard-ssl#31

Duplicates #19764
