### ISSUE TITLE
Allow for easier implementation of fine-grained security

### ISSUE THREAD

**Issue by digitalsanctum** [elastic/elasticsearch#1984]
I posted the following on the mailing list: https://groups.google.com/forum/?fromgroups#!topic/elasticsearch/lAmxGvP3pos

I'd like to suggest an implementation which allows override "fields" or "partial_fields" in order to accomplish filtering of certain fields (which are used for fine-grained security).

For example:

1. if a user passes in a query which has no "fields" or "partial_fields" defined, use a predefined "partial_fields" to prevent sensitive fields from appearing in search results.
2. if a user passes a query which has "fields" or "partial_fields", then merge or override fields available in search results.

In other posts I have seen the suggestion to use indexed fields to accomplish fine-grained security. This works well except for the above scenario for trying to filter security-centric fields from search results.

I look forward to hearing about an existing feature or new feature to accomplish the above.

**Comment by clintongormley** [comment]
Closing in favour of #10174
