### ISSUE TITLE
Multiword Synonyms and Phrase Queries , Is there a mistake in the Elastic documentation?

### ISSUE THREAD

**Issue by pengqiuyuan** [elastic/elasticsearch#19854]
Can you help me with this problem, thank you!

problem1 : https://github.com/elastic/elasticsearch-definitive-guide/issues/581

problem2 : https://github.com/elastic/elasticsearch-definitive-guide/issues/580

**Elasticsearch version**: 2.2.1

**JVM version**: openjdk version "1.8.0_91"

**OS version**: Red Hat Enterprise Linux Server release 7.1 (Maipo)

and

**Elasticsearch version**: 1.7.1

**JVM version**: openjdk version "1.8.0_91"

**OS version**: CentOS release 6.7 (Final)

**Comment by javanna** [comment]
Can you please ask your question in our [discuss forum](https://discuss.elastic.co/)? We reserve github issues for bugs and feature requests. Thanks!

**Comment by pengqiuyuan** [comment]
OK <http://cn.bing.com/dict/search?q=OK&FORM=BDVSP6&mkt=zh-cn>,the problem
<http://cn.bing.com/dict/search?q=problem&FORM=BDVSP6&mkt=zh-cn> was
<http://cn.bing.com/dict/search?q=was&FORM=BDVSP6&mkt=zh-cn> moved
<http://cn.bing.com/dict/search?q=moved&FORM=BDVSP6&mkt=zh-cn> to
<http://cn.bing.com/dict/search?q=to&FORM=BDVSP6&mkt=zh-cn> discuss
<http://cn.bing.com/dict/search?q=discuss&FORM=BDVSP6&mkt=zh-cn> discuss
forum
<https://discuss.elastic.co/t/multiword-synonyms-and-phrase-queries-is-there-a-mistake-in-the-elastic-documentation/57463/1>
. Thanks!

2016-08-08 16:38 GMT+08:00 Luca Cavanna <notifications@github.com>:
