### ISSUE TITLE
The max_clause_count setting is not documented

### ISSUE THREAD

**Issue by dawi** [elastic/elasticsearch#19858]
The max_clause_count option is not documented in the reference documentation.

It seems that it was documented once (https://github.com/elastic/elasticsearch/issues/482#issuecomment-563798):

> in the elasticsearch configuration file (the yml file for example), set the mentioned setting. See more here: http://www.elasticsearch.com/docs/elasticsearch/setup/configuration/#Settings.

**Comment by biinari** [comment]
The only place I can find it mentioned is in the [5.0 breaking settings changes](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_settings_changes.html#_search_settings)

Some mention would be useful along with a little background on reasons for keeping it low and how high it might be reasonable to set it in particular circumstances. It looks like the default value is 1024.

I have found some answers in discussion fora that recommend against increasing this limit, in favour of changing the query usage to avoid high numbers of clauses:

* https://discuss.elastic.co/t/how-to-set-index-query-bool-max-clause-count/32264/3 (and further responses from Elastic Cloud Engineers in same discussion)
* http://stackoverflow.com/a/9808839/839209

**Comment by kunisen** [comment]
any updates here?
