### ISSUE TITLE
ES_JAVA_OPTS set in /etc/default/elasticsearch are not taken into account with the default .deb installation

### ISSUE THREAD

**Issue by lucianprecup** [elastic/elasticsearch#19850]
**Elasticsearch version**:
5.0.0-alpha4

**Plugins installed**:
["ingest-attachment"]

**JVM version**: 
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

**OS version**:
DISTRIB_ID=Debian
DISTRIB_RELEASE=8

**Description of the problem including expected versus actual behavior**:
ES_JAVA_OPTS set in /etc/default/elasticsearch are not taken into account with the default .deb installation.

Setting ES_HEAP_SIZE is *well* taken into account and says : 
```
Aug 06 23:21:05 paris systemd[1]: Started Elasticsearch.
Aug 06 23:21:05 paris elasticsearch[23728]: Error: encountered environment variables that are no longer supported
Aug 06 23:21:05 paris elasticsearch[23728]: Use jvm.options or ES_JAVA_OPTS to configure the JVM
Aug 06 23:21:05 paris elasticsearch[23728]: ES_HEAP_SIZE=12g: set -Xms12g and -Xmx12g in jvm.options or add "-Xms12g -Xmx12g" to ES_JAVA_OPTS
Aug 06 23:21:05 paris systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
```

But if you uncomment and set ES_JAVA_OPTS to, let's say `-Xms12g -Xmx12g`, these settings are simply ignored.

`-Xms` and `-Xmx` settings in /etc/elasticsearch/jvm.options are also well taken into account.

**Steps to reproduce**:
 1. `dpkg -i elasticsearch-5.0.0-alpha4.deb` 
 2. `vi /etc/default/elasticsearch` and set ES_HEAP_SIZE to 12g
 3. `service elasticsearch restart` --> `Use jvm.options or ES_JAVA_OPTS to configure the JVM` `ES_HEAP_SIZE=12g: set -Xms12g and -Xmx12g in jvm.options or add "-Xms12g -Xmx12g" to ES_JAVA_OPTS`
 4. add "-Xms12g -Xmx12g" to ES_JAVA_OPTS
 5. `service elasticsearch restart` --> settings are not taken into account
 6. set -Xms12g and -Xmx12g in /etc/elasticsearch/jvm.options --> all works great

**Provide logs (if relevant)**:
```
? elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled)
   Active: failed (Result: exit-code) since Sat 2016-08-06 23:21:05 CEST; 4s ago
     Docs: http://www.elastic.co
  Process: 23728 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid -Edefault.path.logs=${LOG_DIR} -Edefault.path.data=${DATA_DIR} -Edefault.path.conf=${CONF_DIR} (code=exited, status=1/FAILURE)
  Process: 23726 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec (code=exited, status=0/SUCCESS)
 Main PID: 23728 (code=exited, status=1/FAILURE)

Aug 06 23:21:05 paris systemd[1]: Started Elasticsearch.
Aug 06 23:21:05 paris elasticsearch[23728]: Error: encountered environment variables that are no longer supported
Aug 06 23:21:05 paris elasticsearch[23728]: Use jvm.options or ES_JAVA_OPTS to configure the JVM
Aug 06 23:21:05 paris elasticsearch[23728]: ES_HEAP_SIZE=12g: set -Xms12g and -Xmx12g in jvm.options or add "-Xms12g -Xmx12g" to ES_JAVA_OPTS
Aug 06 23:21:05 paris systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Aug 06 23:21:05 paris systemd[1]: Unit elasticsearch.service entered failed state.
```

**Comment by jasontedor** [comment]
This does not reproduce for me. I just tested on a Debian 8 system, adding the line

```
ES_JAVA_OPTS="-Xms1g -Xmx1g"
```

to `/etc/default/elasticsearch` on an otherwise clean install. I started Elasticsearch via the service and sure enough Elasticsearch started with the right flags:

```
$ jps -l -m -v 1200
1200 org.elasticsearch.bootstrap.Elasticsearch -p /var/run/elasticsearch/elasticsearch.pid -Edefault.path.logs=/var/log/elasticsearch -Edefault.path.data=/var/lib/elasticsearch -Edefault.path.conf=/etc/elasticsearch -Xms256m -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Dio.netty.noUnsafe=true -XX:+HeapDumpOnOutOfMemoryError -Xms1g -Xmx1g -Des.path.home=/usr/share/elasticsearch
```

and from the logs:

```
[2016-08-07 12:43:15,911][INFO ][env                      ] [Oykgh-4] heap size [1015.6mb], compressed ordinary object pointers [true]
```
