### ISSUE TITLE
`index.version.created` values causing Issues with `elasticsearch-image` plugin

### ISSUE THREAD

**Issue by daviddyball** [elastic/elasticsearch#19869]
**Elasticsearch version**: `2.3.3`

**Plugins installed**: [`elasticsearch-image-2.3.3`, `mobz/elasticsearch-head`,`cloud-aws`]

**JVM version**: The version shipped in the official docker container (I think it's `OpenJDK-1.8`)

**OS version**: Debian `8.5`

**Description of the problem including expected versus actual behavior**:

Setting any value between `1000000` and `1999999` for `index.version.created` value works fine with `elasticsearch-image` v`2.3.3`, but if I set it to the correct version signature for Elasticsearch 2.3.3 (`2030399`) all the available `image` type mappings disappear and trying to create a mapping that uses type `image` returns an error.:

I've also raised a ticket against `https://github.com/kiwionly/elasticsearch-image` [here](https://github.com/kiwionly/elasticsearch-image/issues/17)

**Steps to reproduce**:
 1. Build the `elasticsearch-image` plugin from https://github.com/kiwionly/elasticsearch-image
  
  ```
  gradle plugin
  ```
 2. Load a docker instance of `2.3.3`
  
  ```
  docker run -ti --rm -p 9200 --name elasticsearch elasticsearch:2.3.3
  ```
 3. Load the `elasticsearch-image` plugin
  
  ```
  docker cp elasticsearch-image.2.3.3.zip elasticsearch:/tmp/elasticsearch-image.2.3.3.zip
  docker exec -ti /usr/share/elasticsearch/bin/plugin install file:///tmp/elasticsearch-image.2.3.3.zip
  ```
 4. Create a new index with `2030399` as the `index.version.created`
  ```
  curl -XPUT 'localhost:9200/my_index' -d '{
    "settings": {
      "number_of_shards": 1,
      "number_of_replicas": 0,
      "index.version.created": 2030399
    }
  }'
  ```
 5. Try to put a new mapping that uses the `image` field to receive the error (see bellow)

  ```
  curl -XPUT 'localhost:9200/my_index/my_doc/_mapping' -d '
  {
      "my_doc": {
          "properties": {
              "my_image": {
                  "type": "image",
                  "feature": {
                      "JCD": {
                          "hash": ["BIT_SAMPLING", "LSH"]
                      }
                  }
              }
          }
      }
  }'
  ```

**Provide logs (if relevant)**:
```
MapperParsingException[Failed to parse mapping [product]: 
    Mapping definition for [raw_image] has unsupported parameters:
        [feature : {JCD={hash=[BIT_SAMPLING]}]];
```

**Comment by jasontedor** [comment]
> The version shipped in the official docker container (I think it's `OpenJDK-1.8`)

At this time, there is no official Docker image prepared by Elastic. There are images that claim to be "official" but they are not vetted by Elastic and we do not support them. Whether or not you already know this, I say it because there is a lot of confusion on this issue.

**Comment by jasontedor** [comment]
Why are you setting `index.version.created`?

**Comment by daviddyball** [comment]
@jasontedor Thanks for the clarification. I guess it falls under the community maintained Docker library builds of Elasticsearch from here https://github.com/docker-library/elasticsearch

The documentation for `elasticsearch-image` dictated that `index.version.created` needs to be set, which is indeed true as leaving it unset gives the same results as setting it to `2030399`.

`kiwionly` (the plugin maintainer) says the code that actually does the checking is in ES itself and not in the plugin source. I've grep'd the source for `elasticsearch-image` and I couldn't see any references to requiring <`2000000` values for `index.version.created`, so I figured I'd ask here.

**Comment by clintongormley** [comment]
it sounds like the author of the plugin is relying on 1.x features that have since been removed.  Sounds like you need to take it up with him
