### ISSUE TITLE
Proximity and phrases search fast-vector-highlighter vs. highlighter + exposing highlighter

### ISSUE THREAD

**Issue by robert-abbott** [elastic/elasticsearch#1986]
This issue is being opened per discussion on https://groups.google.com/forum/?fromgroups&hl=en#!starred/elasticsearch/d35-QiElg90

"Hi,
here https://gist.github.com/1222046 is a bug reconstruction for
highlighting issues with fast-vector-highlighter in cases of proximity
search and exact phrases searching (when exact phrases contain stop
words).
Reconstruction shows two cases where default/plain highlighter works
correctly/better then the fast-vector-highlighter (maybe there are
some cases/queries where situation is reversed), so my question is: if
these bugs in fast-vector-highlighter code require some time to be
fixed maybe it would be useful to expose highlighter (as a quick fix),
so in the case where field is stored (with "term_vector" :
"with_positions_offsets") users can chose between using
fast-vector-highlighter and default/plain highlighter. Because, even
if fast-vector-highlighter is much faster and should be used for
highlighting matches in fields with term vectors stored, in some cases
(like proximity and stop-word phrases) it does not work correctly, so
being able to use plain highlighter would help.

Thanks,

Tomislav"

**Comment by vineet85** [comment]
@clintongormley - Does the FVH currently support proximity queries?

**Comment by vineet85** [comment]
The FVH still highlights if we use the ES Query_String_Query

POST localhost:9200/testIndex/_search
{
   "query": {
   "query_string": {
      "default_field": "fulltext.exact",
      "query": "\"significant parsing\"~4"
   }
   }, 
   "highlight": {
      "fields": {
         "fulltext.exact": {
            "type": "fvh",
            "number_of_fragments": 0
         }
      },
      "require_field_match": true
   }
}

However it is not support when using the Span Query:-
POST localhost:9200/testIndex/_search
{
    "query": {
		"filtered": {
			"query": {
				"span_near": {
					"clauses": [{
						"span_term": {
							"fulltext.exact":  "significant"
						
						}
					}, {
						"span_term": {
							"fulltext.exact": 
								 "complexity"
							
						}
					}],
					"slop": 4,
					"in_order": false
				}
			},
			"filter": {
				"term": {
					"documentid": "1de7343c6bdd400b936f76782db93065"
				}
			}
		}
	},
	"highlight": {
		"fields": {
			"fulltext.exact": {
				"matched_fields": ["fulltext.exact"],
				"type": "plain",
				"number_of_fragments": 0
			}
		},
		"require_field_match": true
	}
}

**Comment by clintongormley** [comment]
As of 5.0, the `plain` highlighter works for all cases below, the `fvh` highlighter fails for out of order proximity queries and for all span queries.

Updated recreation:

```
PUT /twitter/

PUT /twitter/tweet/_mapping
{
  "properties": {
    "message": {
      "type": "text",
      "term_vector": "with_positions_offsets"
    }
  }
}

PUT /twitter/tweet/1
{
  "user": "kimchy",
  "post_date": "2009-11-15T14:12:12",
  "message": "trying out Elastic and Search"
}

PUT /twitter/tweet/2
{
  "user": "kimchy",
  "post_date": "2009-11-15T14:12:12",
  "message": "trying out Search and Elastic"
}

GET /twitter/tweet/_search
{
  "query": {
    "query_string": {
      "default_field": "message",
      "query": "\"Elastic Search\"~4"
    }
  },
  "highlight": {
    "fields": {
      "message": {
        "type": "fvh"
      }
    }
  }
}

POST /twitter/tweet/_search
{
  "query": {
    "span_near": {
      "clauses": [
        {
          "span_term": {
            "message": "search"
          }
        },
        {
          "span_term": {
            "message": "elastic"
          }
        }
      ],
      "slop": 4,
      "in_order": false
    }
  },
  "highlight": {
    "fields": {
      "message": {
        "type": "fvh"
      }
    }
  }
}
```

**Comment by clintongormley** [comment]
Closing in favour of #21621
