### ISSUE TITLE
InternalEngine should not catch AlreadyClosedException

### ISSUE THREAD

**Issue by rmuir** [elastic/elasticsearch#19861]
There is a lot of exception catching/masking of ACE by InternalEngine, this is **really bad** and will lead to even crashes of the JVM.

Here is an example of what I mean: https://github.com/elastic/elasticsearch/blob/f6aeb35ce8244f4e60cb827cccb42a359f3a2862/core/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L564-L566

```
} catch (AlreadyClosedException e) {
            ensureOpen();                                 // possibly masks ACE by another exception!
            maybeFailEngine("refresh", e);                // definitely swallows ACE!
}
```

Please, do not catch this exception! It should only happen in truly exceptional circumstances, such as a bug in the code, and so on. Perhaps it should be treated similar to Error by elasticsearch.

**Comment by mikemccand** [comment]
+1

**Comment by clintongormley** [comment]
@mikemccand could you tackle this please?

**Comment by rmuir** [comment]
I think the simplest improvement would be to grep for `AlreadyClosedException` and remove all catch blocks of it everywhere. It may not fix all of the problems, but it will only help.

I am concerned about the current situation but even more concerned about 5.0 which will use mmap more heavily (which is the right thing to do).

@uschindler and I worked all week on improving the safety here in lucene, too to avoid crashes (https://issues.apache.org/jira/browse/LUCENE-7409) which should also make things better.

**Comment by uschindler** [comment]
Keep in mind that AlreadyClosedException extends RuntimeException, so there might be cases where it is swallowed anyways.

In my personal opinion, we should change AlreadyClosedException to extend IOException in Lucene. Thats a separate issue, but making it extend RuntimeException/IllegalStateException seems bad.

**Comment by mikemccand** [comment]
> In my personal opinion, we should change AlreadyClosedException to extend IOException in Lucene. 

Maybe open a Lucene issue to discuss this?  I'm not sure I agree :)

I think it'd then be all too easy for apps to ignore `AlreadyClosedException` by accident (since nearly every Lucene API throws `IOException`) when in fact it's a serious bug in the application if this exception strikes.

**Comment by rmuir** [comment]
Not only do i consider this a release blocker, but i think it needs to be a lucene-upgrade-blocker.

We need to stop suppressing the ACE ASAP, and get it into jenkins and work our way towards a failing test, and a fix, all before upgrading lucene.

As long as we are suppressing ACE, https://issues.apache.org/jira/browse/LUCENE-7409 will only make the situation worse (makes the bug more rare). 

I prefer SIGSEGV. Elasticsearch cannot stop it :)

**Comment by mikemccand** [comment]
Just to give some context on this issue and why I think it's so urgent:

  * There is a bug lurking somewhere in ES, where it tries to use an already closed Lucene `IndexReader`.  We need to find it and fix it asap.

  * Lucene tries hard to detect when users do this, and throw an `AlreadyClosedException`, but this is only best effort, and it's really tricky (see https://issues.apache.org/jira/browse/LUCENE-7409, and even with that improvement I can easily provoke SIGSEGV when running the test case on my dev boxes).  When Lucene's best effort check doesn't work, the JVM will likely halt with SIGSEGV when using `MMapDirectory` (the default in ES).

  * Today, ES can swallow this ACE, thus causing our tests to not "notice" there is even a problem, making it less evident.  This PR is addressing this.

We really need to take `AlreadyClosedException` seriously...
