### ISSUE TITLE
ClusterSettings causes many unwanted class initializers to run

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#19878]
All built-in cluster settings are registered in `ClusterSettings`. Since the settings that are registered there usually live in a service class, the moment that `ClusterSettings` is initialized, the class initializers for all these classes run. We have had problems in the past with class initializers running at unexpected times, and we have had situations like the `NettyUtils` class initializer that we had to take extra care to ensure that initialization was not performed until after the security manager was installed lest we end up unknowingly opening the door to unsafe / native code (after the Netty modularization, this is no longer an issue, but it's used to explain the sorts of issues that can arise).

I do not think that we should do this. I think that the settings objects should be moved to dedicated settings classes (e.g., [BootstrapSettings](https://github.com/elastic/elasticsearch/blob/f547886a9b3cd50911ae518da3c327d7a32ad0b0/core/src/main/java/org/elasticsearch/bootstrap/BootstrapSettings.java)) so we can avoid having to reason about these complicated class initialization issues.

I'm marking this as a [Meta](https://github.com/elastic/elasticsearch/labels/Meta) issue, it's too big to pull off in one PR and instead should be done in lots of little PRs.

**Comment by rjernst** [comment]
+1 in general. But I also don't think we need a ton of these (1 or a few high level should be enough). We don't need an alternate class for every service class we have, there are already too many classes!

**Comment by jasontedor** [comment]
I agree that we do not need a ton of these, and that was absolutely not the implication I intended. I'm thinking a few for large high-level concepts (networking, search, scripting, etc.).

**Comment by jasontedor** [comment]
Another problem with all these service class initializers running is that it's easy to run into a cycle in the directed initialization graph which can lead to a runtime deadlock (i.e., `X` depends on `Y` depends on `X`; the class initializer for `X` will take out a class lock on `X`, trigger the class initializer for `Y` which will wait for class initialization for `X` to complete which can not happen).

**Comment by rjernst** [comment]
While I still think this would be a nice to have, it has been 1.5 years and this has not been a priority. I'm going to close this, and we can continue to think about this as refactorings are made.
