### ISSUE TITLE
Elasticsearch: Scripting in minimum should match

### ISSUE THREAD

**Issue by kmalhotra** [elastic/elasticsearch#19885]
**Elasticsearch version**: 2.3.1

**JVM version**: 1.8

**Description of the problem including expected versus actual behavior**:

I have a case wherein I am trying to match 2 set of documents for relevancy. I have to achieve bi-directional searching between the document.

For example, lets consider LinkedIn job relevancy. I want to search for Candidate->Job and Job->Candidate. Both the document set's exists in Elasticsearch i.e, candidate and job.

I want to apply a "Minimum_should_match" for skills query.i.e., atleast 2 of the 3 jobs skills should match for a Candidate. I managed to achieve this using "should" and "minimum_should_match" for Job->Candidate but failed to replicate the same for Candidate->Job.

Is this possible with scripting for minimum_should_match? Didn't find any examples for this.

Kindly help..!

Note:- Scoring is not an option. As we already have a separate scoring algo in place.

**Comment by jpountz** [comment]
Sorry but I don't understand the question, what does the arrow mean in `Candidate->Job` for instance?

**Comment by kmalhotra** [comment]
My Bad.  Let me try with some code now.

For Job -> candidate case:-
I have candidates objects in my Elasticsearch index and job object is an input, to find relevancy i am using something like

{
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "skills": "android"
          }
        },
        {
          "match": {
            "skills": "elasticsearch"
          }
        }
      ],
      "minimum_should_match": "50%"
    }
  }
}

This works perfectly.


For Candidate -> Job

I have job objects in elasticsearch index and a candidate object is an input. I want to find the best matching job for the candidate based on skills in the jobs and apply a minimum_should_match of 50% for skills in jobs. I cannot do something like:- 

{
  "query": {
    "bool": {
      "should": [
        {
          "match": {
            "candidateSkills": "android"
          }
        },
        {
          "match": {
            "candidateSkills": "elasticsearch"
          }
        }
      ],
      "minimum_should_match": "50%"
    }
  }
}

Because this will find jobs in which at-least 50% of candidate skills match.

**Comment by jpountz** [comment]
Am I right to understand that you want to ensure that at least 50% of the skills listed in the job offer should be skills that the candidate has?

If yes, then this sounds like a problem that you can either solve using the percolator, or by searching with a plain disjunction on the skills that the candidate has in addition with a script filter that would ensure the constraint is verified (the bool query will only help with speeding things up since the script will only run on jobs that have at least one of the candidate's skills).

**Comment by clintongormley** [comment]
I'm still struggling to understand.  Your candidate has 2 skills.  You want to find jobs where the candidates skills satisfy at least 50% of the required skills for the job?

**Comment by kmalhotra** [comment]
@jpountz  Yes, 50% of skills in job should match candidate skills.

Percolation might not fit my case considering our queries are dynamic based on user's input. I will still give it a try. 
Can you give an example of a script filter, wherein I can evaluate how many skills matched to verify the constraint?


@clintongormley Yes, suppose a job has 4 skills and a candidate has 8 skills, now this candidate should be declared a match only if candidate has at-least 2 of the skills mentioned in the job. As stated above, this behavior is achieved successfully in case I have "candidates" in my index and searching using job skills but I am unable to replicate the other way round, i.e, when "jobs" is in index and candidate profile is used for query composition.

**Comment by clintongormley** [comment]
>  Yes, suppose a job has 4 skills and a candidate has 8 skills, now this candidate should be declared a match only if candidate has at-least 2 of the skills mentioned in the job.

I think you mean that the candidate should have at least 4 (50%) of the skills mentioned in the job (8)?

This you can do by adding a field to the job document specifying how many skills are required, eg:


    PUT jobs/job/1
    {
      "skills": [
        "one",
        "two",
        "three",
        "four"
      ],
      "number_of_skills": 4
    }
    
    PUT jobs/job/2
    {
      "skills": [
        "two",
        "three",
        "four",
        "five",
        "six"
      ],
      "number_of_skills": 5
    }
    
Then run a query with two functions cores: the inner one scores `1` for every skill that is matched, the outer one divides the score by the number of skills in the job, then the `min_score` parameter only returns jobs where the candidate's skills match at least 50% of the skills in the job.

    GET _search
    {
      "query": {
        "function_score": {
          "boost_mode": "replace",
          "score_mode": "first",
          "min_score": 0.5,
          "script_score": {
            "script": {
              "lang": "groovy",
              "inline": "(float) _score / doc['number_of_skills'].value"
            }
          },
          "query": {
            "function_score": {
              "boost_mode": "replace",
              "score_mode": "sum",
              "query": {
                "constant_score": {
                  "filter": {
                    "terms": {
                      "skills": [
                        "three",
                        "four"
                      ]
                    }
                  }
                }
              },
              "functions": [
                {
                  "filter": {
                    "term": {
                      "skills": "three"
                    }
                  },
                  "weight": 1
                },
                {
                  "filter": {
                    "term": {
                      "skills": "four"
                    }
                  },
                  "weight": 1
                }
              ]
            }
          }
        }
      }
    }

**Comment by dennis87** [comment]
is it possible to accomplish it without using script_score? ( groovy disabled )

**Comment by gsitu322** [comment]
@kmalhotra Hey sorry to bring up back up, but wondering if that solution worked for you? I was looking for something similar and wanted to see if there was a way to handle this dynamically as well.
