### ISSUE TITLE
Compare aggregation result in Elastic Search to find repetitive users

### ISSUE THREAD

**Issue by sa35t** [elastic/elasticsearch#19883]
Currently I can find unique users with in data range, but how do I compare it with my whole corpus to find how many of them are new and how many of them repetitive. Current query to find unique user with in time range

`{
"from": 0,
"size": 0,
"query": {
"filtered": {
"query": {
"query_string": {
"analyze_wildcard": true,
"query": "*"
}
},
"filter": {
"bool": {
"must": [
{
"range": {
"date_time": {
"lte": 1468348199000,
"format": "epoch_millis",
"gte": 1468261800000
}
}
}
],
"must_not": []
}
}
}
},
"aggs": {
"cardinality_device_id": {
"terms": {
"field": "device_id"
}
}
},
"fields": [
"*",
"_source"
]
}`

Any help will be appreciated. Thanks

**Comment by johtani** [comment]
Can you please ask your question in our [discuss forum](https://discuss.elastic.co/c/elasticsearch)? We reserve github issues for bugs and feature requests. Thanks!

**Comment by sa35t** [comment]
I have already asked there but nobody has replied. That's why I have asked here.
