### ISSUE TITLE
Build Failure: org.elasticsearch.index.mapper.geo.GeoPointFieldMapperTests.testGeoHashSearchWithPrefix

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#19895]
I was able to reproduce this test failure locally.

Reproduce with: 
1.
```gradle :core:test -Dtests.seed=78FD9CE1DD644100 -Dtests.class=org.elasticsearch.index.mapper.geo.GeoPointFieldMapperTests -Dtests.method="testGeoHashSearchWithPrefix" -Dtests.security.manager=true -Dtests.locale=ko -Dtests.timezone=US/Arizona```
2.
```gradle :core:test -Dtests.seed=21804C3974E780C3 -Dtests.class=org.elasticsearch.index.mapper.geo.GeoPointFieldMapperTests -Dtests.method="testGeoHashSearchWithPrefix" -Dtests.security.manager=true -Dtests.locale=pt-BR -Dtests.timezone=Pacific/Bougainville```
3.
```gradle :core:test -Dtests.seed=6BEFE3BE00E008B -Dtests.class=org.elasticsearch.index.mapper.geo.GeoPointFieldMapperTests -Dtests.method="testGeoHashSearchWithPrefix" -Dtests.security.manager=true -Dtests.locale=es-HN -Dtests.timezone=Pacific/Ponape```

Build Failure:
1.
(https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+dockeralpine-periodic/243/console)
2.
(https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/1227/console)
3.
(https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/1228/console)

**Comment by rjernst** [comment]
@jpountz I think these geo related failures have to do with #19867, but I was unable to figure out why. Can you take a look?

**Comment by jpountz** [comment]
I'll look tomorrow morning!
