### ISSUE TITLE
Build Failure: org.elasticsearch.index.engine.InternalEngineTests.testUpgradeOldIndex

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#19894]
I was able to reproduce this test failure locally.

Reproduce with: 
```gradle :core:test -Dtests.seed=5F4B00F95E2F7681 -Dtests.class=org.elasticsearch.index.engine.InternalEngineTests -Dtests.method="testUpgradeOldIndex" -Dtests.security.manager=true -Dtests.locale=sr-Latn-BA -Dtests.timezone=America/Eirunepe```

Build Failure:
(https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/1224/console)

**Comment by rjernst** [comment]
We shouldn't have generated bwc indexes for alpha5, we don't have bwc indexes for alpha releases. I removed them in 6efbe54.
