### ISSUE TITLE
Build Failure: org.elasticsearch.bwcompat.RepositoryUpgradabilityIT

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#19897]
I was able to reproduce this test failure locally.

Reproduce with:
1.
```gradle :core:integTest -Dtests.seed=F0557CC38215D15D -Dtests.class=org.elasticsearch.bwcompat.RepositoryUpgradabilityIT -Dtests.method="testRepositoryWorksWithCrossVersions" -Dtests.security.manager=true -Dtests.locale=hu -Dtests.timezone=Africa/Libreville```
2.
```gradle :core:integTest -Dtests.seed=8DAEAD3037BDBDDA -Dtests.class=org.elasticsearch.bwcompat.RepositoryUpgradabilityIT -Dtests.method="testRepositoryWorksWithCrossVersions" -Dtests.security.manager=true -Dtests.locale=lg-UG -Dtests.timezone=Europe/Helsinki```

Build Failure:
1.
(https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/1225/console)
2.
(https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/909/console)

**Comment by rjernst** [comment]
We shouldn't have generated bwc indexes for alpha5, we don't have bwc indexes for alpha releases. I removed them in 6efbe54.
