### ISSUE TITLE
Build Failure: org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#19898]
I was able to reproduce the test failure locally.

Reproduce with:
1.
```gradle :core:integTest -Dtests.seed=F0557CC38215D15D -Dtests.class=org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT -Dtests.method="testOldClusterStates" -Dtests.security.manager=true -Dtests.locale=ar-OM -Dtests.timezone=America/Thunder_Bay```
2.
``gradle :core:integTest -Dtests.seed=F0557CC38215D15D -Dtests.class=org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT -Dtests.method="testOldIndexes" -Dtests.security.manager=true -Dtests.locale=ar-OM -Dtests.timezone=America/Thunder_Bay```
3.
```gradle :core:integTest -Dtests.seed=8DAEAD3037BDBDDA -Dtests.class=org.elasticsearch.bwcompat.OldIndexBackwardsCompatibilityIT -Dtests.method="testOldIndexes" -Dtests.security.manager=true -Dtests.locale=en-LC -Dtests.timezone=Asia/Bangkok```

Build Failure:
1, 2
(https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/1225/console)
3
(https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/909/console)

**Comment by rjernst** [comment]
We shouldn't have generated bwc indexes for alpha5, we don't have bwc indexes for alpha releases. I removed them in 6efbe54.
