### ISSUE TITLE
Undocumented side effects from fixing PreBuiltTransportClientsTests PR #19803

### ISSUE THREAD

**Issue by ruckc** [elastic/elasticsearch#19903]
**Elasticsearch version**: 5.0.0-alpha5

**Plugins installed**: []

**JVM version**: Oracle Java 1.8.0_102

**OS version**: Windows 10 x86_64

**Description of the problem including expected versus actual behavior**:

When switching from 5.0.0-alpha4 to 5.0.0-alpha5, existing elasticsearch.yml stopped working, with what appears as an impossible error to bypass.  I expect the node to startup, but the PR #19803 seems to completely change the logic for starting a new Node object.

With my working in 5.0.0-alpha4 configuration, with 5.0.0-alpha5, I get this exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: Unknown [transport] type [] possible values: [local]
	at org.elasticsearch.common.util.ExtensionPoint$SelectedType.bindType(ExtensionPoint.java:151)
	at org.elasticsearch.common.network.NetworkModule.configure(NetworkModule.java:154)
```

I have to add `transport.type: local` because the default isn't detecting `local`.  Then, once i've added `transport.type`, I get this exception:

```
Exception in thread "main" java.lang.IllegalArgumentException: Unknown [http_transport] type [] possible values: []
	at org.elasticsearch.common.util.ExtensionPoint$SelectedType.bindType(ExtensionPoint.java:151)
	at org.elasticsearch.common.network.NetworkModule.configure(NetworkModule.java:159)
```

To get past this error, i can change `http.enabled` to `false`, which I don't want to do, but it seems that previous "working" is no longer the case.

As for expected result, I'd ideally expect previous defaults to work.  If that isn't possible, it would be beneficial to provide better error messages as I have no clue why `http_transport` is being output if `http.enabled: true`.  Also breaking changes for 5.0 should be updated for embedded users.

**Steps to reproduce**:
I setup a sample maven project to recreate this issue and included the relevant sections below.
https://github.com/ruckc/elasticsearch-embedded-issue

elasticsearch.yml:
```
network.host: 127.0.0.1
http.port: 9200
http.enabled: true
gateway.expected_nodes: 1
cluster.routing.allocation.disk.watermark.low: 512mb
cluster.routing.allocation.disk.watermark.high: 256mb
path.data: target/test/testdata2
path.home: target/test
```

sample main method:
```
    public static void main(String... args) throws IOException {
        try (InputStream is = Main.class.getResourceAsStream("/elasticsearch.yml")) {
            Settings settings = Settings.builder().loadFromStream("elasticsearch.yml", is).build();

            Node node = new Node(settings);
            node.start();
        }
    }
```

**Comment by ruckc** [comment]
Its is almost like almost all of the transports other than `local` were removed from elasticsearch-5.0.0-alpha5.jar.  I just tried adding the transport-netty4-client-5.0.0-alpha5.jar to see if Netty4Plugin autowired and it didn't, and I can't find any description of how to make `http.type` pickup a plugin.

**Comment by jasontedor** [comment]
You need to install a transport, which you haven't as they are modularized outside of core now.

```diff
diff --git a/pom.xml b/pom.xml
index 980e5e0..c1dad7a 100644
--- a/pom.xml
+++ b/pom.xml
@@ -30,6 +30,12 @@
             <groupId>org.elasticsearch</groupId>
             <artifactId>elasticsearch</artifactId>
             <version>5.0.0-alpha5</version>
+            <type>jar</type>	  
+        </dependency>
+        <dependency>
+            <groupId>org.elasticsearch.plugin</groupId>
+            <artifactId>transport-netty4-client</artifactId>
+            <version>5.0.0-alpha5</version>
             <type>jar</type>
         </dependency>
         <dependency>
@@ -44,4 +50,4 @@
         <maven.compiler.target>1.8</maven.compiler.target>
         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
     </properties>
-</project>
\ No newline at end of file
+</project>
diff --git a/src/main/java/com/example/elasticsearch/embedded/Main.java b/src/main/java/com/example/elasticsearch/embedded/Main.java
index 05bce20..9119bc2 100644
--- a/src/main/java/com/example/elasticsearch/embedded/Main.java
+++ b/src/main/java/com/example/elasticsearch/embedded/Main.java
@@ -17,8 +17,11 @@ package com.example.elasticsearch.embedded;
 
 import java.io.IOException;
 import java.io.InputStream;
+import java.util.Collections;
 import org.elasticsearch.common.settings.Settings;
+import org.elasticsearch.node.internal.InternalSettingsPreparer;
 import org.elasticsearch.node.Node;
+import org.elasticsearch.transport.Netty4Plugin;
 
 /**
  *
@@ -30,8 +33,14 @@ public class Main {
         try (InputStream is = Main.class.getResourceAsStream("/elasticsearch.yml")) {
             Settings settings = Settings.builder().loadFromStream("elasticsearch.yml", is).build();
 
-            Node node = new Node(settings);
+            Node node = new PluginNode(settings);
             node.start();
         }
     }
+
+    static class PluginNode extends Node {
+	public PluginNode(Settings settings) {
+	    super(InternalSettingsPreparer.prepareEnvironment(settings, null), Collections.singletonList(Netty4Plugin.class));
+	}
+    }
 }
```

**Comment by ruckc** [comment]
@jasontedor Is this documented at this level in breaking changes?

**Comment by jasontedor** [comment]
To be clear, with the above change, everything starts fine for me:

```bash
23:16:20 ⌁49% [jason:~/src/ruckc/elasticsearch-embedded-issue] master(+18/-3)* 130 ± mvn exec:java -Dexec.mainClass=com.example.elasticsearch.embedded.Main
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building elasticsearch-embedded-issue 1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ elasticsearch-embedded-issue ---
2016-08-09 23:16:22 INFO  node:215 - [] initializing ...
2016-08-09 23:16:23 INFO  env:370 - [G8Y1LLz] using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [341.7gb], net total_space [464.7gb], spins? [unknown], types [hfs]
2016-08-09 23:16:23 INFO  env:379 - [G8Y1LLz] heap size [3.5gb], compressed ordinary object pointers [true]
2016-08-09 23:16:23 INFO  node:236 - [G8Y1LLz] node name [G8Y1LLz] derived from node ID; set [node.name] to override
2016-08-09 23:16:23 INFO  node:242 - [G8Y1LLz] version[5.0.0-alpha5], pid[77912], build[d327dd4/2016-08-04T08:59:39.568Z], OS[Mac OS X/10.11.6/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_92/25.92-b14]
2016-08-09 23:16:23 INFO  plugins:217 - [G8Y1LLz] no modules loaded
2016-08-09 23:16:23 INFO  plugins:220 - [G8Y1LLz] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2016-08-09 23:16:24 INFO  node:381 - [G8Y1LLz] initialized
2016-08-09 23:16:24 INFO  node:431 - [G8Y1LLz] starting ...
2016-08-09 23:16:24 INFO  transport:179 - [G8Y1LLz] publish_address {local[1]}, bound_addresses {local[1]}
2016-08-09 23:16:27 INFO  service:659 - [G8Y1LLz] new_master {G8Y1LLz}{G8Y1LLzMSoiiS7nlZNDBtw}{7mzGZmplR7mCw0QbaCYNQw}{local}{local[1]}, reason: zen-disco-elected-as-master ([0] nodes joined)
2016-08-09 23:16:27 INFO  gateway:298 - [G8Y1LLz] recovered [0] indices into cluster_state
2016-08-09 23:16:27 INFO  http:79 - [G8Y1LLz] publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}
2016-08-09 23:16:27 INFO  node:536 - [G8Y1LLz] started
^C23:16:37 ⌁49% [jason:~/src/ruckc/elasticsearch-embedded-issue] master(+18/-3)* 130 ±

**Comment by debarshiraha** [comment]
Looks like this impacts running Elasticsearch.java from Eclipse? What will be the steps now?

**Comment by ruckc** [comment]
@debarshiraha this impacts any embedded usage of ElasticSearch, if transports other than local are desired.  It isn't documented in breaking changes yet.

**Comment by debarshiraha** [comment]
Does org.elasticsearch.bootstrap.Elasticsearch.java need a fix or do we need to apply some setting while running it from Eclipse?

**Comment by ruckc** [comment]
You have to include a transport client now, previously elasticsearch's jar contained it, now its separate jar.  Also, you need a custom Node implementation as shown in the above diff.

**Comment by debarshiraha** [comment]
Thanks, trying similar code on master branch, looks like it can't find a master:

"timed out while waiting for initial discovery state - timeout: 30s"

**Comment by shivangshah** [comment]
+1 for adding this to breaking changes documentation. Spent couple of hours trying to figure this out.

**Comment by sidhhu** [comment]
I get the same exception when I try to download the jar and start it with the binary.

**Comment by 1ambda** [comment]
I am also trying to solve this issue, but faced a problem unexpected applying proposed code by @debarshiraha

```
incompatible types: java.util.List<java.lang.Class<org.elasticsearch.transport.Netty4Plugin>> cannot be converted to java.util.Collection<java.lang.Class<? extends org.elasticsearch.plugins.Plugin>>
```

Because `org.elasticsearch.transport.NettyPlugin` extends `org.elasticsearch.plugins.Plugin`, there is no reason to get this error :(

I think it's a kind of dependency problem. `pom.xml` looks like

```xml
    <profile>

      <properties>
        <elasticsearch.version>5.0.0</elasticsearch.version>
        ...
      </properties>
      <dependencies>

        <dependency>
          <groupId>org.elasticsearch.client</groupId>
          <artifactId>transport</artifactId>
          <version>${elasticsearch.version}</version>
        </dependency>

        <dependency>
          <groupId>org.elasticsearch</groupId>
          <artifactId>elasticsearch</artifactId>
          <version>${elasticsearch.version}</version>
        </dependency>

        <dependency>
          <groupId>org.elasticsearch.plugin</groupId>
          <artifactId>transport-netty4-client</artifactId>
          <version>${elasticsearch.version}</version>
        </dependency>
```

Could anyone have the same problem?

**Comment by 1ambda** [comment]
I am not sure why the above error was occurred but we can work around by specify type explicitly like `Collections.<Class<? extends Plugin>>singletonList(Netty4Plugin.class)`

**Comment by oscarcastaneda** [comment]
I'm facing the same exact issue reported by @ruckc with 5.0.1. Followed the same steps, including importing transport client separately. Elastic comes up but only if "path.home" is set along with "transport.type" set to "local" and "http.enabled" set to "false". Not sure why this issue was closed but it remains an issue on 5.0.1.

**Comment by rjernst** [comment]
You should use the PreBuiltTransportClient, which was added in alpha5:
https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html

**Comment by oscarcastaneda** [comment]
Thanks @rjernst 

I am indeed using PreBuiltTransportClient. And I am also importing transport client, which is now in a separate jar as pointed out by @ruckc .

This is Elastic 5.0.1 which I am trying to run on an Apache Spark Cluster. (Which explains the Scala below.)

Here's what I have:

```
import org.elasticsearch.transport.client._
import org.elasticsearch.node.Node._
import org.elasticsearch.common.settings.Settings
import org.apache.logging.log4j._

class ElasticsearchServer5 {
  private val clusterName = "Elastic5test"  
  private val settings = Settings.builder()
    .put("path.home", "/var/opt/elasticsearch")
    .put("transport.type", "local")
    .put("http.enabled","false")
.build

  val client = new org.elasticsearch.transport.client.PreBuiltTransportClient(settings)
  private lazy val node = new org.elasticsearch.node.Node(settings)

  def start(): Unit = {
    node.start()
  }
}

val server = new ElasticsearchServer5
server.start()
```

The server only comes up if I import org.elasticsearch.transport.client._ and include three configuration options:

1. Specify path.home
2. Set "transport.type" to "local"
3. Set "http.enabled" to "false"

These three options were recommended by @ruckc And indeed they help to at least bring up the server. But since I have "http.enabled" set to "false" I can not interact with Elastic through http.

It is weird that only with these configuration options Elastic 5.0.1 comes up. I have tested this with Elasticsearch 1.7.2 on an Apache Spark cluster (1.6.2) and it does come up and I can run it and interact with it smoothly. 

Additional information:

Elasticsearch version: 5.0.1
Plugins installed: None.
JVM version: 1.8.0_66-internal (Oracle Corporation)
OS version: Linux 3.16.0-44-generic

**Comment by rjernst** [comment]
@oscarcastaneda This is a closed issue, and we reserve github for feature requests and confirmed bug reports. The original issue here did not look like it was using PreBuiltTransportClient (based on the code snippets), hence my comment.  In the future please try asking questions like this at https://discuss.elastic.co.

I would guess your issue has to do with constructing a Node, not the transport client. We do not support embedding elasticsearch in this way. Please see https://www.elastic.co/blog/elasticsearch-the-server. Also, for suggestions on how to run integration tests with 5.x, see http://david.pilato.fr/blog/2016/10/18/elasticsearch-real-integration-tests-updated-for-ga/.
