### ISSUE TITLE
Optionally fail on metadata extraction error

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#19928]
As discussed at https://github.com/elastic/elasticsearch/pull/19927#discussion_r74283442

We should add a similar option [as we had for the legacy mapper-attachments plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/current/mapper-attachments-error-handling.html).

Let's add back a `ignore_errors` (default to `false`) which can be added within ingest attachment settings.
Ignore errors may only be applied to metadata parsing errors. Like when we try to convert a String to a Number.

The goal is to still have text extracted whatever is happening on a metadata level.

May be if `ignore_errors` equals `true` we should copy all the original content as is (I mean as Strings) in a `errors` field like:

``` json
{
  "attachment": "foo bar",
  "errors": {
    "content_length": "i am not a number"
  }
}
```

Thoughts?

**Comment by javanna** [comment]
ingest already allows to catch errors with an `on_failure` section that is supported at the processor level and at the pipeline level. Would this new option do something that cannot be done with an `on_failure` section ?

**Comment by dadoonet** [comment]
It would still generate the field with extracted text. Only some metadata would not be generated.

**Comment by dadoonet** [comment]
As said by @javanna as we already have a way to catch global errors on a processor or pipeline level, let's close this feature request.
