### ISSUE TITLE
Build Failure: ScheduleWithFixedDelayTests#testBlockingCallOnSchedulerThreadFails

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#19922]
**Elasticsearch version**: 2.4

Only seems to happen on the 2.4 branch. Last seen here:

http://build-us-00.elastic.co/job/es_core_24_windows-2012-r2/1352/

I was able to reproduce this this on my local machine running Ubuntu with the Reproduce-Line from that build:

mvn test -Pdev -pl org.elasticsearch:elasticsearch -Dtests.seed=D84D08A9A1B7D44A -Dtests.class=org.elasticsearch.threadpool.ScheduleWithFixedDelayTests -Dtests.method="testBlockingCallOnSchedulerThreadFails" -Des.logger.level=DEBUG -Dtests.assertion.disabled=org.elasticsearch -Dtests.nightly=false -Dtests.client.ratio=0.0 -Dtests.heap.size=512m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:+UseCompressedOops -Djava.net.preferIPv4Stack=true" -Dtests.locale=pt -Dtests.timezone=America/Sitka

Similar, but here the test seems to be stalling for a long time is this build failure:

http://build-us-00.elastic.co/job/es_core_24_windows-2012-r2/1341/

When I run this locally, I also get the the stalled tests:

mvn test -Pdev -pl org.elasticsearch:elasticsearch -Dtests.seed=745D325D13102F3A -Dtests.class=org.elasticsearch.threadpool.ScheduleWithFixedDelayTests -Dtests.method="testBlockingCallOnSchedulerThreadFails" -Des.logger.level=DEBUG -Dtests.assertion.disabled=org.elasticsearch -Dtests.nightly=false -Dtests.client.ratio=0.0 -Dtests.heap.size=512m -Dtests.jvm.argline="-server -XX:+UseConcMarkSweepGC -XX:-UseCompressedOops -XX:+AggressiveOpts -Djava.net.preferIPv4Stack=true" -Dtests.locale=ar -Dtests.timezone=US/Hawaii

**Comment by jasontedor** [comment]
@jaymode Can you take a look?

**Comment by jaymode** [comment]
I pushed eb37e3f87fc26bd6599ee2d51dd21ad04c535bbe. The issue was that assertion get disabled randomly in CI on 2.4, which causes this test to fail (see dev-tools/build_randomization.rb).
