### ISSUE TITLE
elasticsearch-plugin - ERROR: E is not a recognized option

### ISSUE THREAD

**Issue by djschny** [elastic/elasticsearch#19931]
**Elasticsearch version**: v5.0.0-alpha5

**Plugins installed**: non

**JVM version**: 1.8.0_92

**OS version**: Mac 10.11.5

**Description of the problem including expected versus actual behavior**:
Execute `bin/elasticsearch-plugin` with no arguments and the usage is printed, but there is also what appears to be an erroneous `ERROR: E is not a recognized option` is being displayed:

```
djschny:meetup djschny$ elasticsearch-5.0.0-alpha5/bin/elasticsearch-plugin
A tool for managing installed elasticsearch plugins

Commands
--------
list - Lists installed elasticsearch plugins
install - Install a plugin
remove - Removes a plugin from elasticsearch

Non-option arguments:
command              

Option         Description        
------         -----------        
-h, --help     show help          
-s, --silent   show minimal output
-v, --verbose  show verbose output
ERROR: E is not a recognized option
```

**Comment by jasontedor** [comment]
Duplicates #18689

**Comment by rajamarni** [comment]
Following is worked for me
C:\Program Files\Elastic\Elasticsearch\6.7.0>.\bin\elasticsearch-plugin install file:///C:\Program Files\Elastic\Elasticsearch\6.7.0\graph-2.4.6.zip
