### ISSUE TITLE
Provide an api to retrieve mappings statistics

### ISSUE THREAD

**Issue by tpraizler** [elastic/elasticsearch#19948]
**Describe the feature**:

It would be great if there was a way to get statistics on index mappings (size? memory? etc)

My use case is that I am doing lots of cleanups in my mappings which are a mess, and it would have been great to see the cleanup impact on the mappings, and the index in general.

**Comment by clintongormley** [comment]
Mappings are part of the cluster state.  I think the easiest way to measure the cleanups is just to retrieve all mappings before and after the cleanups and measure the difference.

I don't think we need a dedicated API for mapping size, but I'm closing this in favour of https://github.com/elastic/elasticsearch/issues/3415 (adding the cluster state size to stats)

**Comment by tpraizler** [comment]
Thanks @clintongormley.
I was actually encouraged to open this feature request [here](https://discuss.elastic.co/t/how-to-query-current-mapping-size/57703).

By "retrieve all mappings" you mean use the _mapping endpoint? or _stats endpoint on the index?

**Comment by clintongormley** [comment]
@tpraizler you can do it with the `_mapping` endpoint

**Comment by tpraizler** [comment]
Thanks! which fields should I look for in the huge response of this endpoint?
Anything in particular? @clintongormley 

And Thanks!

**Comment by clintongormley** [comment]
@tpraizler you wanted a way of measuring how much reduction you had made in the mappings. Just compare the size of the responses
