### ISSUE TITLE
ES 5.0-alpha5 on windows fails to install windows service

### ISSUE THREAD

**Issue by alextxm** [elastic/elasticsearch#19941]
**Elasticsearch version**: 5.0-alpha5

**Plugins installed**: []

**JVM version**: 1.8.0_92

**OS version**: Windows Server 2008 R2

**Description of the problem including expected versus actual behavior**:
Execution of the "service install" command fails due to folder name containing spaces (see screenshot)
![cattura](https://cloud.githubusercontent.com/assets/6169392/17583831/4fd0040e-5fb3-11e6-9a6c-4d5bbfadd794.PNG). The same command / configuration works fine with ES 2.3.x

**Steps to reproduce**:
 1. Install ES 5.0-alpha5 into a folder like C:\Program Files\elasticsearch
 2. As an admin, go to to bin/ and try to execute "service install myesservicename"

**Comment by jasontedor** [comment]
I can reproduce this issue, thank you for reporting @alextxm. I have marked you as eligible for the [Pioneer Program](https://www.elastic.co/blog/elastic-pioneer-program).

**Comment by jasontedor** [comment]
I opened #19951.
