### ISSUE TITLE
I have shield and license installed on all my Nodes, 1 client,3 Master and 6 data Nodes but as soon as i start the cluster shield automatically goes down,exposing my cluster publicly.

### ISSUE THREAD

**Issue by Nabeelgujjar** [elastic/elasticsearch#19940]
**Elasticsearch version**:

**Plugins installed**: []

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by tlrx** [comment]
Hi,

We reserve GitHub for verified bug reports and feature requests, can I suggest that you open a topic on the [Elastic Discourse forum](https://discuss.elastic.co/) so that we can help you there?
