### ISSUE TITLE
Highlighting does not seem to work in 2.3.4

### ISSUE THREAD

**Issue by EugenyPavlenko** [elastic/elasticsearch#19942]
Hello!

My ES version:

```
curl 'localhost:9200'
{
  "name" : "Rune",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.4",
    "build_hash" : "e455fd0c13dceca8dbbdbb1665d068ae55dabe3f",
    "build_timestamp" : "2016-06-30T11:24:31Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}

```

Search query posted via **PHP** ES library (your):

```
Array
(
    [index] => myindex_en03
    [type] => products
    [body] => Array
        (
            [query] => Array
                (
                    [query_string] => Array
                        (
                            [query] => 1333
                        )

                )

            [highlight] => Array
                (
                    [pre_tags] => <em>
                    [post_tags] => </em>
                    [fields] => Array
                        (
                            [title] => stdClass Object
                                (
                                )

                            [shortDescr] => stdClass Object
                                (
                                )

                        )

                )

        )

)

```

That is index settings:

```php
$params = [
				'index' => $this->curIndexName,
            	'body' => [
					'mappings' => [
						'objects' => [
							'properties' => [
								//"title" => [
								//	"type" => "string",
								//	"store" => true 
								//],
								'applications3-0' => [
									'type' => 'string',
									'index' => 'not_analyzed'
								],
								'applications3-123' => [				
									'type' => 'string',
									'index' => 'not_analyzed'
								],
								'applications3-1' => [
									'type' => 'string',
									'index' => 'not_analyzed'
								],
								'applications3-2' => [
									'type' => 'string',
									'index' => 'not_analyzed'
								],
								'applications3-3' => [
									'type' => 'string',
									'index' => 'not_analyzed'
								],
								'applications3-4' => [
									'type' => 'string',
									'index' => 'not_analyzed'
								],
								'applications3-5' => [
									'type' => 'string',
									'index' => 'not_analyzed'
								],
								'functions' => [
									'type' => 'string',
									'index' => 'not_analyzed'
								],
								'benefits' => [
									'type' => 'string',
									'index' => 'not_analyzed'
								]
							]
						]
					]
				]
			];
```

As a result:
1) I do not have any ES errors
2) I do have normal response, having correct hits returned, based on "query_string"
3) **BUT I do not have "highlight" key (clause) returned whatsoever!**

According to documentation:

> In order to perform highlighting, the actual content of the field is required. If the field in question is stored (has store set to true in the mapping) it will be used, otherwise, the actual _source will be loaded and the relevant field will be extracted from it.

So, I am not obliged to have "store: true" on each field?

But, also, I tried to set store: true in mappings (you see this code is commented out in my code snippet above), but the result was the same like now.

I got tired to fight with hightlight (to get it returned), can somebody tell me what I am doing wrong? The must be some easy mistake...

**Comment by nik9000** [comment]
> So, I am not obliged to have "store: true" on each field?

No. You have to have either `store:true` or store the `_source`. Usually storing the `_source` is the best option and it is on by default.

Your best bet is to work forwards from examples from the docs using curl or sense. Start with the working examples in the docs and make them look like your PHP query. At some point it'll stop working and you should be able to figure out what happened. Either it is a bug or you are doing something that isn't supported.

For things like this it is more appropriate to ask on discuss.elastic.co

**Comment by EugenyPavlenko** [comment]
Hello @nik9000 !

Sorry for writing here again. I followed your proposal to go "from easy to hard" and suddenly I failed on a very basic things like:
```bash
#!/bin/bash

indexName="idx"
dataType="data"

curl -XGET 'http://localhost:9200/'$indexName'/'$dataType'/_search?pretty=true' -d '{
    "query" : {
        "term": {"_all" : "bbb"}
    },
    "highlight" : {
        "fields" : {
            "title": {},
            "content": {}
        }
    }
}'

echo "Search completed!"
```

Hits are returned but no "highlight" field.

![2016-08-17_16-24-40](https://cloud.githubusercontent.com/assets/1785921/17765734/61981bd6-6530-11e6-885b-dba2f741cbf3.png)


I created more detailed thread here:
https://discuss.elastic.co/t/cant-get-highlight-working-in-2-3-4/58257

but did not get any response yet... Maybe, if you have 1-2 free min. to look into this.. I think there should some simple mistake or this simply a bug.

**Comment by EugenyPavlenko** [comment]
if somebody has the same issue, the solution is:

> "require_field_match": false
