### ISSUE TITLE
index not automatically created, receive exception - no such index

### ISSUE THREAD

**Issue by mikewanguk** [elastic/elasticsearch#19943]
**Elasticsearch version**: 2.3.4

**Plugins installed**: []

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:
in elasticsearch 2.3.4, calling nest elasticClient.Index() or Bulk() with a new index when index doesn't exist throws exception - no such index, whereas in early version of elasticsearch e.g. 2.3.1, elasticsearch will automatically create index if it doesn't exist

**Steps to reproduce**:
1. call nest elasticClient.Index() or Bulk() for a new index
2. receive server error - no such index
3. Index() or Bulk() will automatically create index if it doesn't exists, with early version elasticSearch e.g. 2.3.1

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by nik9000** [comment]
I *think* this is either something to do with your configuration (you can
turn off auto creation) or to do with you client. Elasticsearch has
thousands of tests that rely on this behavior.

**Comment by clintongormley** [comment]
Agreed.  I'm going to close this ticket for now.  If you find something significant and can provide a full recreation please reopen
