### ISSUE TITLE
ES_RESTART_ON_UPGRADE not respected during yum upgrade.

### ISSUE THREAD

**Issue by Gacko** [elastic/elasticsearch#19950]
**Elasticsearch version**: 2.3.3+, probably any version using ES_RESTART_ON_UPGRADE

**Plugins installed**: [None]

**JVM version**: 1.8.0_72

**OS version**: Oracle Linux 7.2

**Description of the problem including expected versus actual behavior**:

The environment file /etc/sysconfig/elasticsearch describes a parameter called "ES_RESTART_ON_UPGRADE". This file is sourced during the pre-install script of your RPM package. But: The script checks for a parameter called "RESTART_ON_UPGRADE" - the "ES_"-prefix is missing and the service won't be restarted during the upgrade process.

We tried copying the whole parameter in /etc/sysconfig/elasticsearch, renamed it to "RESTART_ON_UPGRADE" and did a re-install via yum. This time our Elasticsearch node was restarted as expected.

**Steps to reproduce**:
 1. Install Elasticsearch from repository using yum.
 2. Set ES_RESTART_ON_UPGRADE in /etc/sysconfig/elasticsearch to true.
 3. Do a upgrade using using yum.
 4. See that Elasticsearch has not been restarted.

**Comment by clintongormley** [comment]
thanks for reporting @Gacko - I've opened a PR #19976

**Comment by Gacko** [comment]
I wasn't sure if this has to be fixed in the sysconfig or in the install script. I would have opened a PR otherwise. Thank you!
