### ISSUE TITLE
Put script API should be able to accept scripts not wrapped into a JSON object

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#19963]
In 5.0 in order to store a script, the script needs to be wrapped into a single field json object:

```
curl -XPOST 'localhost:9200/_scripts/groovy/calculate-score' -d '{"script": "log(_score * 2) + my_modifier" }'
```

It's not bit deal for one-liners as in this example, but it makes debugging large scripts more complicated then it needs to be. It would be great if put script command accepted unwrapped scripts like this:

```
curl -XPOST 'localhost:9200/_scripts/groovy/calculate-score' -d 'log(_score * 2) + my_modifier'
```

**Comment by imotov** [comment]
After speaking to @javanna it looks like it might be a good idea to integrate this with #19388, otherwise we will have to add even more magic into detection of the content type.

**Comment by clintongormley** [comment]
Yeah, I'd rather stick with just the one way of doing it.  The few end points which support text bodies are problematic.

**Comment by javanna** [comment]
Given the direction is to remove the existing endpoint that support plain/text rather than adding new ones, see #22751, I would close this. Do you mind @imotov ? :)

**Comment by imotov** [comment]
Makes sense!
