### ISSUE TITLE
(5.0.0-alpha5) Elasticsearch plugin is red; plugin:elasticsearch@5.0.0-alpha5 Service Unavailable

### ISSUE THREAD

**Issue by naisanza** [elastic/elasticsearch#19968]
I'm not sure if it's an elasticsearch issue or a kibana issue (https://github.com/elastic/kibana/issues/7985), but this didn't happen with the alpha4 build

**JVM version**: java version "1.8.0_101"

**Kibana version**: Kibana 5.0.0-alpha5

**Elasticsearch version**: Elasticsearch 5.0.0-alpha5

**Server OS version**: Proxmox Ubuntu 15.10 LXC

**Browser version**: Chrome/Firefox

**Browser OS version**:

**Original install method (e.g. download page, yum, from source, etc.)**: 
 - https://download.elastic.co/kibana/kibana/kibana-5.0.0-alpha5-linux-x86_64.tar.gz
 - https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/5.0.0-alpha5/elasticsearch-5.0.0-alpha5.tar.gz
 - http://javadl.oracle.com/webapps/download/AutoDL?BundleId=211989

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Create Ubuntu 15.10 container; apt update; apt upgrade
 2. Download java, kibana, elasticsearch
 3. No changes to kibana.yml
 4. Make changes to elasticsearch.yml (see below)
 5. Start Elasticserach `su elastic -c "ES_JAVA_OPTS='-Xms2048m -Xmx2048m' elasticsearch"`
 6. Start Kibana
 7. Receive error (see screenshot)

```
root@Kibana-500-alpha5:~# grep -v "#" /opt/elasticsearch-5.0.0-alpha5/config/elasticsearch.yml                                                                                            cluster.name: cluster-mk1-beta
discovery.zen.minimum_master_nodes: 1
node.master: false
node.data: false
```

This error does not occur if elasticsearch.yml is set to:

```
network.host: _site_ 
```

and kibana.yml is set to:

```
elasticsearch.url: "http://10.1.10.213:9200"
```

**Errors in browser console (if relevant)**:

![screenshot from 2016-08-11 20-53-07](https://cloud.githubusercontent.com/assets/1614425/17609737/bbebba00-6005-11e6-929f-de0f5be2d482.png)

**Provide logs and/or server output (if relevant)**:

**Comment by jasontedor** [comment]
The problem is that you have `node.data` and `node.master` set to false; in this Kibana, Kibana can not find the master node, and even when it does find the master node, after it creates the .kibana index, the master will not have a data node on which to allocate a primary shard for that index.

**Comment by naisanza** [comment]
@jasontedor did I read something wrong from the documentation?

https://www.elastic.co/guide/en/kibana/current/production.html

**Comment by jasontedor** [comment]
The instructions for setting `node.data` and `node.master` to false are only for if you are running a dedicated client node on the same host as your Kibana instance but you still must have somewhere a cluster that has a master and data nodes. Your setup describes starting exactly one Elasticsearch node, and in this case you must allow this node to play the role of a master node and a data node.

**Comment by naisanza** [comment]
@jasontedor that's my fault that I didn't mention. I have an elasticsearch cluster running in production mode sitting in the same subnet

**Comment by jasontedor** [comment]
Okay! Now we can make sense of this situation. Sadly, I think that you've been led astray by documentation that needs improvement.

If you have a remote cluster, your client node needs to be configured to talk to that cluster. This means that at a minimum, you have configure the discovery layer so that the client node can reach the cluster, and the client node needs to be bound to a network device that can reach the cluster (e.g., if the cluster is on a remote machine, you can't bind the client node to its loopback device). If you're using simple unicast zen discovery (the default), you can just specify a hosts list (it's enough to specify the master-eligible nodes, and I consider this a best practice). In my case, I will start a single node cluster on my workstation:

```
$ ES_JAVA_OPTS="-Xms4g -Xmx4g" ~/elasticsearch/elasticsearch-5.0.0-alpha5/bin/elasticsearch -E network.host=_eno1_ -E discovery.zen.minimum_master_nodes=1
```

I'm binding to one of this machine's ethernet devices named `eno1` which has IP address 192.168.1.179.

On my laptop, I will start a client node (as you're trying to do) pointing to this node:

```
$ ES_JAVA_OPTS="-Xms4g -Xmx4g" ~/elasticsearch/elasticsearch-5.0.0-alpha5/bin/elasticsearch -E node.data=false -E node.master=false -E discovery.zen.ping.unicast.hosts=192.168.1.179 -E network.host=_en0_ -E discovery.zen.minimum_master_nodes=1
```

I'm binding to this machine's wireless device named `en0` which has IP address 192.168.1.92.

Now on my laptop I edit the `kibana.yml` to point to this client node:

```
elasticsearch.url: "http://192.168.1.92:9200"
```

and start Kibana and have success:

```
14:17:49 [jason:~] $ ~/kibana/kibana-5.0.0-alpha5-darwin-x86_64/bin/kibana
  log   [14:17:56.329] [info][status][plugin:kibana@5.0.0-alpha5] Status changed from uninitialized to green - Ready
  log   [14:17:56.363] [info][status][plugin:elasticsearch@5.0.0-alpha5] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [14:17:56.389] [info][status][plugin:console@5.0.0-alpha5] Status changed from uninitialized to green - Ready
  log   [14:17:56.400] [info][status][plugin:kbn_doc_views@5.0.0-alpha5] Status changed from uninitialized to green - Ready
  log   [14:17:56.402] [info][status][plugin:kbn_vislib_vis_types@5.0.0-alpha5] Status changed from uninitialized to green - Ready
  log   [14:17:56.406] [info][status][plugin:markdown_vis@5.0.0-alpha5] Status changed from uninitialized to green - Ready
  log   [14:17:56.418] [info][status][plugin:metric_vis@5.0.0-alpha5] Status changed from uninitialized to green - Ready
  log   [14:17:56.421] [info][status][plugin:spy_modes@5.0.0-alpha5] Status changed from uninitialized to green - Ready
  log   [14:17:56.423] [info][status][plugin:status_page@5.0.0-alpha5] Status changed from uninitialized to green - Ready
  log   [14:17:56.426] [info][status][plugin:table_vis@5.0.0-alpha5] Status changed from uninitialized to green - Ready
  log   [14:17:56.438] [info][listening] Server running at http://0.0.0.0:5601
  log   [14:17:56.439] [info][status][ui settings] Status changed from uninitialized to yellow - Elasticsearch plugin is yellow
  log   [14:18:01.432] [info][status][plugin:elasticsearch@5.0.0-alpha5] Status changed from yellow to yellow - No existing Kibana index found
  log   [14:18:02.047] [info][status][plugin:elasticsearch@5.0.0-alpha5] Status changed from yellow to green - Kibana index ready
  log   [14:18:02.047] [info][status][ui settings] Status changed from yellow to green - Ready
```

and on my workstation:

```
[2016-08-12 14:16:31,783][INFO ][cluster.service          ] [lbWdifM] added {{rLXgiug}{rLXgiugpT2Cq9NRPHT-hfA}{pDuDqfgDRoSH8eoG_aSu8A}{192.168.1.92}{192.168.1.92:9300},}, reason: zen-disco-node-join[{rLXgiug}{rLXgiugpT2Cq9NRPHT-hfA}{pDuDqfgDRoSH8eoG_aSu8A}{192.168.1.92}{192.168.1.92:9300}]
[2016-08-12 14:18:01,614][INFO ][cluster.metadata         ] [lbWdifM] [.kibana] creating index, cause [api], templates [], shards [1]/[1], mappings [server, config]
[2016-08-12 14:18:04,558][INFO ][cluster.metadata         ] [lbWdifM] [.kibana/w8Uhj1BWTeKNkI2wtX5YBw] create_mapping [index-pattern]
```

showing that the `.kibana` index was created through the client via Kibana.

I hope this helps. I think that the documentation led you astray because it makes no mention of configuring the client node for discovery of the cluster, and implies that you can bind the client node to localhost which is not going to work by default if the cluster is a remote cluster.

**Comment by jasontedor** [comment]
I will reopen the Kibana issue that opened and leave a note that the documentation needs improvement. Thanks for downloading 5.0.0-alpha5 and trying it out, and I'm sorry that you experienced this hiccup.

**Comment by ManojkNagulapalli** [comment]
Hi I have installed Kibana on Windows7. After pointing to the kibana server its showing elasticsearch plugin is red and  also plugin:elasticsearch@5.0.2	 Not Found. Any help is appreciated..
![image](https://cloud.githubusercontent.com/assets/12676553/21013866/90c79e4e-bd29-11e6-8ace-14570e52eeb6.png)

**Comment by jasontedor** [comment]
@ManojkNagulapalli Elastic reserves GitHub for verified bug reports and feature requests and provides a [forum](https://discuss.elastic.co) for general help.

**Comment by gr8Adakron** [comment]
After installing elastic search and kibana. And after starting both the service elasticsearch and kibana. when I am trying to get to the localhost:5601 that is kibana. I was getting this page.
![elastic](https://cloud.githubusercontent.com/assets/16715364/22182367/e8def1ea-e0c9-11e6-90b9-6b19c24e2182.png)
**Help! Urgent**

**Comment by raulk89** [comment]
I have the exact same problems as you, gr8Adakron.

Any help is appreciated..

**Comment by raulk89** [comment]
Ok, I solved the problem, you have to mod the kibana.yml file (/etc/kibana/kibana.yml), and add elastic user/pass. 
Default is elastic/changme

_# If your Elasticsearch is protected with basic authentication, these settings provide
# the username and password that the Kibana server uses to perform maintenance on the Kibana
# index at startup. Your Kibana users still need to authenticate with Elasticsearch, which
# is proxied through the Kibana server.
elasticsearch.username: "elastic"
elasticsearch.password: "changeme"_

**Comment by ror6ax** [comment]
I have this issue while running Kibana on Mesos. We're using Mesos-DNS and I pass elasticsearch URL which is provided by it. Can you please advice what might be done to fix it?

ui settings	 Elasticsearch plugin is red
plugin:kibana@5.2.0	 Ready
plugin:elasticsearch@5.2.0	 Not Found

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by marcelokanzaki** [comment]
Thanks @raulk89. That helped.
