### ISSUE TITLE
Switch InternalShardLock from using LockObtainFailedException to a different exception

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#19978]
According to the [documentation](https://github.com/apache/lucene-solr/blob/cea8a488f0d48041abb4be0dbe29ab81f04522bf/lucene/core/src/java/org/apache/lucene/store/LockObtainFailedException.java#L22-L25) for `LockObtainFailedException`:

`This exception is thrown when the <code>write.lock</code> could not be acquired.`

We should not use this exception for the in-memory semaphore that's part of [NodeEnvironment](https://github.com/elastic/elasticsearch/blob/15c96df5b5d5b22b13a27adb4650917fc6ad1d80/core/src/main/java/org/elasticsearch/env/NodeEnvironment.java#L706-L716), we should use a different exception class.

**Comment by rmuir** [comment]
+1 hijacking this exception is crying wolf, it freaks me out if i see it, especially if it does not contain the expected contents. Lets please not use it for any other purpose.
