### ISSUE TITLE
Reindex cancel and status don't work via transport client

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#19979]
We recently moved the registration of named writeables to pull approach. The task status named writeables were left out of this refactoring and should be migrated as well. As a result, transport client doesn't see the `BulkByScrollTask.Status` as its registration happens in `NetworkModule` after the transport client pulled all the named writeables during its initialization.

I guess we want to create a TaskPlugin interface like we have done with SearchPlugin, ActionPlugin etc.

**Comment by javanna** [comment]
This can be tested by removing the @ClusterScope annotation from ReindexTestCase, which currently disables transport client in all of the reindex integration tests. One of the problems that we would have caught using transport client is #19977, another is this issue.

**Comment by nik9000** [comment]
> @ClusterScope

So I added that annotation because it was on the test case from that I cribbed the module test from. I can't remember which one it was, but I expect we use this annotation all over the place for dubious reasons. Maybe we should remove go through the uses and prune them?

**Comment by nik9000** [comment]
> TaskPlugin

I'd put the method in ActionPlugin because tasks are always paired with some action. There is also a `registerTaskStatus` which maybe can move in there too....

**Comment by javanna** [comment]
> I can't remember which one it was, but I expect we use this annotation all over the place for dubious reasons. Maybe we should remove go through the uses and prune them?

I had a quick look, and I don't see that manu usages, most seem legit, but sure we should probably go over the tests that use it and re-evaluate.

**Comment by nik9000** [comment]
I can fix this on Monday if no one else claims it first.

**Comment by nik9000** [comment]
Claimed. I'll work on it this morning.
