### ISSUE TITLE
Missing path.repo changes in 2.3 (from 1.6)

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#19971]
Here - https://www.elastic.co/guide/en/elasticsearch/reference/2.3/breaking-changes-1.6.html#_snapshot_and_restore - we seem to be missing the `path.repo` changes.

They are listed here though - https://www.elastic.co/guide/en/elasticsearch/reference/1.7/breaking-changes-1.6.html#_snapshot_and_restore

**Comment by clintongormley** [comment]
Actually, I'm not sure why we still have migration notes for 1.x in the 2.x docs, so I've deleted them.

Each major version now has only migration notes for that major version
