### ISSUE TITLE
Don't return OK to service if bootstrap checks fail

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#19970]
In the ES 5 alphas we have some awesome bootstrap checks. However when you start ES as a service, eg `service elasticsearch start` and haven't completed those, it gives;
```
 * Starting Elasticsearch Server                                                                                                                                                                                                       [ OK ]
```
And in the logs it complains because not all of the checks passed.

We shouldn't really be returning an `OK` from the service if it doesn't start at all.

**Comment by jasontedor** [comment]
Duplicates #19297, it's the same issue; daemonization succeeds and *later* the Elasticsearch processes halts.
