### ISSUE TITLE
Java Client considered harmful without checked exceptions.  

### ISSUE THREAD

**Issue by burtonator** [elastic/elasticsearch#19980]
The Elasticsearch java client, at the heart of the Exception tree, uses RuntimeExceptions.

> public class ElasticsearchException extends RuntimeException

This puts me in a position where I have no idea which methods can fail due to a transient elasticsearch protocol exception, no way to gracefully handle these and resume my behavior, and no idea which exceptions to catch.

I now have to dive into the code to figure out which exceptions can be thrown which can happen at any time.

Further, the documentation doesn't clearly lay out WHY this decision was made.

Nearly every Java API in the world uses checked Exceptions at this point.  

If Elastic things unchecked exceptions are the way to go then this should at LEAST clearly be laid out in the documentation.  Right now it isn't explained clearly and this is problematic.

**Comment by jpountz** [comment]
> Nearly every Java API in the world uses checked Exceptions at this point. 

This is just not true. Many APIs throw unchecked exceptions, and there is disagreement about whether checked exceptions are a useful feature or a mistake: https://www.google.com/search?q=checked+exceptions+mistake.

However, you are right that the Java API needs more love and that the exceptions it might throw should be better documented.

**Comment by burtonator** [comment]
@jpountz I said "nearly ever" Java API. I think it would be fair to say that 90-95% of APIs use checked exceptions.  

One idea I thought of could be to have 2 clients... a CheckedClient and an UncheckedClient.  The only problem here is that its hard to enforce/document WHICH of the checked APIs is being throw.  You might not always want to throw ElasticsearchException.

**Comment by javanna** [comment]
may I suggest to try out the new java REST client that was released first with 5.0.0-alpha4 ? That is the client that we would like our users to use on the long run and that we would like to replace the java api with at some point.

**Comment by javanna** [comment]
I don't think we are going to make major changes to the java API at this point. We want to focus on the high level REST client, see #19055 for what's coming there, which is going to replace the transport client and make the current java API internal API only.
