### ISSUE TITLE
Numeric field distance aggregation

### ISSUE THREAD

**Issue by webattitude** [elastic/elasticsearch#19983]
**Elasticsearch version**: 2.3.4

**Plugins installed**: [license, marvel-agent]

**JVM version**: 1.8.0_91

**OS version**: Debian 8.5 (jessie)

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
N/A

**Provide logs (if relevant)**:
N/A

**Describe the feature**:
I need an aggregation type on distance between a numeric field among sample documents.
This is usefull to extract sessions from logs.
Typically, I have events logs, with timestamps. I want to group documents which timestamps are within range (say 30minutes) compared to each other, ie docs rolling out over a period of 2 hours may be grouped because each doc is less than 30minutes near its neighbor.

**Comment by webattitude** [comment]
I guess it achievable with a plugin, but I think it would be great feature

**Comment by jpountz** [comment]
How different would it be from a date histogram?

**Comment by webattitude** [comment]
date histogram is fixed interval, ie from 14:30 to 15:00.
Distance between each document could lead to something like this : documents from 14:30 to 17:00 could be grouped because each document is less than 30m near to the next one.

**Comment by jpountz** [comment]
So that would be like a date histogram, except that you would collapse non-empty adjacent buckets?

**Comment by webattitude** [comment]
yes, provided documents'timetamps are close enough

**Comment by clintongormley** [comment]
Is this not k-means clustering? https://github.com/elastic/elasticsearch/issues/5512

**Comment by jpountz** [comment]
That sounds similar indeed, except maybe that I would expect a k-means impl to allow me to configure the number of clusters, while here it seems the configuration parameter would rather be a minimum distance between clusters (the number of clusters being unbounded)?

@webattitude Can you please give more information about the use-case. I can hardly imagine such an aggregation help identify sessions since there could be multiple concurrent sessions, so I believe you would plan to put this maybe under a terms aggregation on a `session_id` field?

**Comment by webattitude** [comment]
yes the number of clusters is unbounded
You're right, there could be multiple concurrent sessions, but I'll find some way to identify them.
We are tracking events from angular front end. I'd like to group events according to this rule (less than 30min close docs are in same cluster), then count sessions, along with events within session to infer level of activity for exemple.

**Comment by jpountz** [comment]
> there could be multiple concurrent sessions, but I'll find some way to identify them

I would like to understand more about this. Finding sessions seems to be a common use-case but it is also a hard problem so I would like to make sure that we build something that actually works for this use-case and is efficient.

**Comment by webattitude** [comment]
We use access token, I guess we will create a session id from that token, which will be sent along with tracking data. Then we will extract 30minutes sessions from these _long time_ sessions.
makes sens ? we dont really need to identify concurrent sessions actually

Oh ok, I just got it : we have a user id among tracking data
(I was thinking about _concurrent sessions_ from different browsers)

**Comment by jpountz** [comment]
So if you had such an aggregation, you would run it under a terms aggregation on the `user_id` field I suppose? And what information would you like to get about the sessions? Only `doc_count`? Maybe duration? More?

**Comment by webattitude** [comment]
duration absolutely, maybe average, total duration, average delay between sessions (globally or by user), and median or percentiles (although I feel like this is achievable with another aggregation... I'm newbie with ES).
Also we will probably need to output a date histogram from this, to see hourly repartition.

**Comment by webattitude** [comment]
how do you feel about that ?

**Comment by jpountz** [comment]
I know @colings86 has been working on doinc k-mean clustering on geo points (#5512) and would like to see how it goes before moving forward on this issue. Even though the clustering rules will be different, it raises similar issues such as whether we should support sub aggregations (which is technically possible, but would require that we add the ability to merge buckets together, which is something we do not do today) and what intermediate representation shards should return.

**Comment by webattitude** [comment]
Hi, any news ?

**Comment by webattitude** [comment]
@jpountz any advancement about this ?

**Comment by colings86** [comment]
@jpountz is this issue still relevant? Could it maybe be closed in favour of https://github.com/elastic/elasticsearch/issues/5512 which is also about adding clustering?

**Comment by colings86** [comment]
@elastic/es-search-aggs

**Comment by jpountz** [comment]
We decided to not pursue this. We can't support this use-case at scale and it felt to us that entity-centric indices would be a more efficient way to aggregate data based on sessions.
