### ISSUE TITLE
how to update some field and increment some filed on single request ?

### ISSUE THREAD

**Issue by imiskolee** [elastic/elasticsearch#19999]
i has a doc. its like 
```json
{
 "last_update" : 100000,
  "update_counter" : 0
}
```

when i change the last_update,i want to incr the update_counter field.

we know, incr a filed we can use script,but can't provide both script and doc?

how to do ?

**Comment by cbuescher** [comment]
Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse](https://discuss.elastic.co/) forum and [IRC channels](https://www.elastic.co/community) for general questions.
