### ISSUE TITLE
Intermittent ReceiveTimeoutTransportException on Java transport Client

### ISSUE THREAD

**Issue by parasboth** [elastic/elasticsearch#19998]
We have a ES production cluster setup of 5 nodes (all nodes are master eligible nodes with ample amount of disk space & RAM) with the default elastic search settings. But we are observing an intermittent issue where we are getting a failure from ES with the following exception:

failed to get local cluster state for {node address}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: 
[cluster:monitor/state] request_id [1] timed out after [5002ms]
    at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679) [elasticsearch-2.3.3.jar!/:2.3.3]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]

The cluster sniffing feature has been enabled in the transport client.

**Comment by ywelsch** [comment]
That exception happens in the sniffing code if a node fails to respond within the configured timeout (default is 5 seconds). You can increase the timeout (`client.transport.ping_timeout`) to see if that helps. If this was a one-time thing I would not worry about it though as it could just mean anything from a short network hiccup to a long GC on the node. Are you using just one or all 5 nodes as seed list for the sniffing?

**Comment by xuyuanjin** [comment]
I encountered the same issue and disabling sniffer fixed the problem. ES cluster: 2.3.5

**Comment by jasontedor** [comment]
No feedback, closing.
