### ISSUE TITLE
Highlighting with wildcard for fields

### ISSUE THREAD

**Issue by kelto** [elastic/elasticsearch#20007]
**Elasticsearch version**: 2.3.5

**Plugins installed**: [marvel, license-2.3.3]

**JVM version**: 1.8.0_60

**OS version**:  RHEL 4.4.7-4

**Description of the problem including expected versus actual behavior**:
Highlighting on wildcard fields does not return the highlighted words when using inner_hits.
Note: It seems specifying query_string's "fields" will cause highlighting to show up.

The request looks like this:
```
{
    "from": 0,
    "size": 20,
    "_source": [
        "id",
        "name"
    ],
    "query": {
        "bool": {
            "should": [
                {
                    "query_string": {
                        "query": "simple query string",
                        "use_dis_max": true
                    }
                },
                {
                    "has_child": {
                        "type": "child",
                        "score_type": "sum",
                        "query": {
                            "query_string": {
                                "query": "simple query string",
                                "use_dis_max": true
                            }
                        },
                        "boost": 1,
                        "inner_hits": {
                            "name": "child",
                            "_source": false,
                            "highlight": {
                                "pre_tags": [
                                    "<mark>"
                                ],
                                "post_tags": [
                                    "</mark>"
                                ],
                                "fields": {
                                    "*": {}
                                },
                                "require_field_match": true
                            }
                        }
                    }
                },
                {
                	// same has_child query on other children ...
                }
            ]
        }
    }
}
```
and in the response, some child show a match, but there is no highlight provided:
```
{
    "took": 8224,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "failed": 0
    },
    "hits": {
        "total": 164890,
        "max_score": 3.8307233,
        "hits": [
            {
                "_index": "index",
                "_type": "parent",
                "_id": "id",
                "_score": 3.8307233,
                "_source": {
                    "id": "id"
                },
                "inner_hits": {
                    "first_child": {
                        "hits": {
                            "total": 0,
                            "max_score": null,
                            "hits": []
                        }
                    },
                    "second_child": {
                        "hits": {
                            "total": 1,
                            "max_score": 16.715395,
                            "hits": [
                                {
                                    "_index": "index",
                                    "_type": "second_child",
                                    "_id": "id_child",
                                    "_score": 16.715395,
                                    "_routing": "id",
                                    "_parent": "id",
                                    "highlight": {
                                        "second_child.field1": [
                                            "<mark>simple query string</mark> ..."
                                        ],
                                        "second_child.field2": [
                                            "<mark>simple query string</mark> ..."
                                        ]
                                    }
                                }
                            ]
                        }
                    },
                    "third_child": {
                        "hits": {
                            "total": 1,
                            "max_score": 15.483837,
                           // hit found but no highlight
                            "hits": [
                                {
                                    "_index": "index",
                                    "_type": "third_child",
                                    "_id": "third_id",
                                    "_score": 15.483837,
                                    "_routing": "id",
                                    "_parent": "id"
                                }
                            ]
                        }
                    }
                }
            }
        ]
    }
}
```

The _all fields is enabled, and using _all instead of * does not fix the problem.

**Comment by clintongormley** [comment]
You have `require_field_match` set to `true`, but you're querying on the `_all` field, which isn't stored and isn't in the `_source`.   This works:

    PUT t 
    {
      "mappings": {
        "parent": {},
        "child": {
          "_parent": {
            "type": "parent"
          }
        }
      }
    }
    
    PUT t/parent/1
    {
      "name": "simple query string"
    }
    
    PUT t/child/2?parent=1
    {
      "name": "simple query string"
    }
    
    
    GET /t/parent/_search
    {
      "_source": [
        "id",
        "name"
      ],
      "query": {
        "bool": {
          "should": [
            {
              "query_string": {
                "query": "simple query string",
                "use_dis_max": true
              }
            },
            {
              "has_child": {
                "type": "child",
                "score_mode": "sum",
                "query": {
                  "query_string": {
                    "query": "simple query string",
                    "use_dis_max": true
                  }
                },
                "inner_hits": {
                  "name": "child",
                  "_source": false,
                  "highlight": {
                    "fields": {
                      "*": {}
                    },
                    "require_field_match": false
                  }
                }
              }
            }
          ]
        }
      }
    }

**Comment by kelto** [comment]
Setting require_field_match to false make it works for some search, but for a few one (i have reproduced it with two query_string for the moment) some children do not send back the highlights, and for some no children send the highlights.
The query_string used:
"tomato": all children send the corresponding highlights
"maize": no highlight at all (but show that there is a hit)
"four": partial highlights (but show that there is a hit)

**Comment by clintongormley** [comment]
Please can you provide a curl recreation demonstrating the problem

**Comment by kelto** [comment]
I'm trying to find some simple data to reproduce the problem, but have trouble to do so.
Unfortunately I can't provide the real data here.
