### ISSUE TITLE
Search reduce failures map to 503 status code

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#20004]
[`SearchPhaseExecutionException#status()`](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/search/SearchPhaseExecutionException.java#L87-L90) returns a `503 Unavailable` status code if there are no shard failures added to the exception:

```
        if (shardFailures.length == 0) {
            // if no successful shards, it means no active shards, so just return SERVICE_UNAVAILABLE
            return RestStatus.SERVICE_UNAVAILABLE;
        }
```

If an Exception is thrown in the reduce phase (e.g. from the reduce of an aggregation) this means that it will be given a 503 status code since if there were no failures returned from the shards. 

It looks like this is primarily caused by the fact that [`ReduceSearchPhaseException`](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/search/ReduceSearchPhaseException.java) extends `SearchPhaseExecutionException` so maybe either we should override the `status()` method in `ReduceSearchPhaseException` or we should not have `ReduceSearchPhaseException` extend `SearchPhaseExecutionException`?

**Comment by nik9000** [comment]
I feel like we should have an explicit `IndexUnavailable` exception to throw when we want to throw a `503`. So I think `SearchPhaseExecutionException` shouldn't return `503`.

**Comment by clintongormley** [comment]
For context: the clients use a `503` status code to signal that they should resniff (if sniffing is enabled) and retry the request.  This makes sense when the node they were talking to is disconnected from the cluster, but not if indices are recovering.

**Comment by polyfractal** [comment]
Chatted about this in Search meeting.

We decided that `ReduceSearchPhaseException` should probably just return a generic 500 exception (either by extending something else or just overriding `status()`).  The case that triggers this (#20003) will be fixed independently, since that's really a parsing issue, but the underlying exception doesn't really make sense to be a 503 instead of 500.

**Comment by antrix190** [comment]
Hey @polyfractal if nobody is working on this i want to have a crack on this one.

**Comment by deeps-usha** [comment]
Hi @polyfractal , I have done the changes to this issue. But I am not able to push my branch and create a pull request. Can you please let me know how to create a PR for this?

**Comment by polyfractal** [comment]
Hi @deeps-usha, you'll need to [fork the repository](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo) to your github account, make the changes and push to your version of the repo, then [send a PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests) with that.  The github documentation should be able to guide you through the process :)

**Comment by deeps-usha** [comment]
Hi @polyfractal, I have raised a pull request https://github.com/elastic/elasticsearch/pull/63219. Please review.

**Comment by jmbessa** [comment]
Hi! I would like to know if this issue still open. If yes, can I work on it? This would be my first issue

**Comment by imotov** [comment]
@jmbessa we have quite a few students from PUC-Rio contacting us recently about contributing. I assume that you all got an assignment in your CS class. Would it be possible to get in touch with your professor for this class to discuss this effort in order to make it useful for both students and developers?

**Comment by jmbessa** [comment]
@imotov could you give me your e-mail, please? I will send to him and he will contact you

**Comment by imotov** [comment]
My email is my first name at elastic.co.

**Comment by jmbessa** [comment]
@polyfractal could you review the PR #74395, please?

**Comment by imotov** [comment]
@jmbessa Zach cannot review your PR. I am trying to work with your professor to find a working solution for this situation. We don't really have enough bandwidth in our team at the moment to do reviews for all students in your class. I am really sorry about it.
