### ISSUE TITLE
Allow update mapping for `default` field on context suggester

### ISSUE THREAD

**Issue by zanona** [elastic/elasticsearch#20006]
## Feature Request:

The `default` property on Context Suggester is really useful, specially when you want to fall back to select all categories should `null` be specified on the request query.

However, as you can imagine, if we map a `default` field with the available categories at the time:

```json
{
  "properties": {
    "skill": {
      "type": "completion",
      "context": {
        "industry": { "type": "category", "default": ["Technology",  "Finance"] }
      }
    }
  }
}
```

This would work pretty well, however if the platform decides to cater for more industries in the future, than the `default` becomes obsolete and impossible to replace at the moment throwing an exception.

I would like to suggest allowing update the mapping for the `default` field under a contextual suggester so a `null` option can still accommodate  a _catch_all_ solution.

What do you reckon?

**Comment by clintongormley** [comment]
Hi @zanona 

The completion suggester has been completely rewritten in 5.0 and now allows searching all categories.
