### ISSUE TITLE
node stats gc old min max collection time

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch#20015]
For the _node/stats jvm.gc.old, it would be great to have a `min` and `max` collection_time value to be able to see the longest gc old run time.

**Comment by jpountz** [comment]
I am afraid we cannot do much here since this information is not exposed by the JVM: https://docs.oracle.com/javase/8/docs/api/java/lang/management/GarbageCollectorMXBean.html

**Comment by clintongormley** [comment]
The max value would be for the lifetime of the node, so I'm not sure that it would add much value.  More useful is to expose this information (or current trends) in a monitoring tool.
