### ISSUE TITLE
Incosistent API definition and test for ingest.get_pipeline

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch#20010]
**Elasticsearch version**: master (21af485a88bc4f667fc043cabd61dd54a823ae92)

`ingest.get_pipeline` has `id` parameter marked as required (https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/ingest.get_pipeline.json#L12) yet the tests (https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/test/ingest/10_basic.yaml#L49) call `get_pipeline` without the `id` parameter.

Integrated test suite should be validating parameters marked as required.

**Comment by martijnvg** [comment]
The `id` parameter should not be marked as required, since it is fine to just call GET `/_ingest/pipeline` to get all pipelines.

**Comment by HonzaKral** [comment]
Could we also change the test runner to verify the `required` parameters and fail if one is missing to prevent this from repeating? I'd be happy to create another ticket for it.

**Comment by clintongormley** [comment]
Perhaps we shouldn't be relying on the `required` flag at all?  Whether it is required or not can be deduced from the provided URL patterns.

**Comment by HonzaKral** [comment]
We still need it for the `body` param, which should be tested.

Either way works, either we make it implicit (I like the `required` flag for it's expressiveness) or we start testing it to make it reliable.
