### ISSUE TITLE
Phrase Suggester returns different results with aliases

### ISSUE THREAD

**Issue by shyam-aryan** [elastic/elasticsearch#20019]
**Elasticsearch version**: 2.3.2

**JVM version**: 1.8.0_65

**OS version**: Oracle Linux Server release 6.5

We use a field SearchAllText in Phrase Suggester which is populated across multiple indices. We have 2 aliases:
1) `search_all` which covers 34 indices.
2) `index_load` which covers 30 indices. 

index_load excludes 4 indices that search_all includes but rest all are same. When we run the Phrase Suggester against both we are seeing different results. Here index_load generates more suggestions than search_all alias. I would expect at least same suggestions on search_all alias as well. Any idea why the behavior is different? My expected result is `walgreen`

```
GET index_load/_search?search_type=count
{
  "suggest" : {
    "text" : "wagreen",
    "phrase_suggest" : {
      "phrase" : {
        "field" : "SearchAllText.suggest",
        "size" : 10,
        "direct_generator" : [ {
          "field" : "SearchAllText.suggest",
          "suggest_mode" : "popular",
          "min_word_length" : 0,
          "prefix_length" : 0,
          "size" : 10
        } ],
         "collate": {
            "query": {
              "query_string" : {
                "query" : "{{suggestion}}",
                "fields" : [ "SearchAllText" ],
                "default_operator" : "and",
                "analyze_wildcard" : true
              }
              },
           "prune": false 
         }
      }
    }
  }
}
```

Returns

```
{
   "took": 82,
   "timed_out": false,
   "_shards": {
      "total": 60,
      "successful": 60,
      "failed": 0
   },
   "hits": {
      "total": 82791251,
      "max_score": 0,
      "hits": []
   },
   "suggest": {
      "phrase_suggest": [
         {
            "text": "wagreen",
            "offset": 0,
            "length": 7,
            "options": [
               {
                  "text": "warren",
                  "score": 0.008121356
               },
               {
                  "text": "walgreens",
                  "score": 0.0037804323
               },
               {
                  "text": "walgreen",
                  "score": 0.0032029075
               },
               {
                  "text": "wareena",
                  "score": 0.0025363953
               },
               {
                  "text": "waren",
                  "score": 0.0025306016
               }
            ]
         }
      ]
   }
}
```

and the same phrase query run against search_all alias returns this:

```
{
   "took": 89,
   "timed_out": false,
   "_shards": {
      "total": 64,
      "successful": 64,
      "failed": 0
   },
   "hits": {
      "total": 83151341,
      "max_score": 0,
      "hits": []
   },
   "suggest": {
      "phrase_suggest": [
         {
            "text": "wagreen",
            "offset": 0,
            "length": 7,
            "options": [
               {
                  "text": "warren",
                  "score": 0.008121356
               }
            ]
         }
      ]
   }
}
```

**Comment by clintongormley** [comment]
What version are you using?

Also, if you run the suggestion on just the 4 indices that are different, what happens?

**Comment by shyam-aryan** [comment]
Hi @clintongormley - Please see the versions above. I get no suggestions when run against the 4 indices that are different.

	{
	   "took": 43,
	   "timed_out": false,
	   "_shards": {
		  "total": 4,
		  "successful": 4,
		  "failed": 0
	   },
	   "hits": {
		  "total": 360125,
		  "max_score": 0,
		  "hits": []
	   },
	   "suggest": {
		  "phrase_suggest": [
			 {
				"text": "wagreen",
				"offset": 0,
				"length": 7,
				"options": []
			 }
		  ]
	   }
	}

**Comment by clintongormley** [comment]
@areek any idea of what may be happening here?

**Comment by shyam-aryan** [comment]
Hi @areek - Did you get a chance to look into this ?

**Comment by areek** [comment]
Hey @shyam-aryan, I will look into this soon (by today), sorry for the delay here :)

**Comment by shyam-aryan** [comment]
Hi @areek any update on this please?

**Comment by shyam-aryan** [comment]
Hi @areek any update on this please?

**Comment by shyam-aryan** [comment]
Hi @areek - any update please?

**Comment by shyam-aryan** [comment]
Hi @areek @clintongormley We upgraded to ES v2.3.2 but still able to reproduce this issue. Can you please take a look?

**Comment by andyb-elastic** [comment]
Hi, I apologize that we haven't been responsive here. I'm not able to reproduce this issue. @jimczi is there anything obviously wrong here?

**Comment by tomcallahan** [comment]
Hi,

Unfortunately we do not support this version of Elasticsearch anymore.  I'm sorry that we did not respond in a timely manner on this one.  Please let me know if this issue persists on a supported version of Elasticsearch.
