### ISSUE TITLE
Order by sub-aggregations on max/min/avg distance

### ISSUE THREAD

**Issue by zaobao** [elastic/elasticsearch#20021]
**Elasticsearch version**:2.3.4

**JVM version**:1.8.2

**OS version**:CentOS 7

**Describe the feature**:
I need to get all ids (about 10000 ids) which is sorted by some fields. Getting ids from hits is too slow because the fetch phase takes too much time. 

If I use the terms aggregation with average sub aggregation on those fields to sort, the performance is considerably improved. 

The order of the buckets supports sub aggregations on numeric fields. 

e.g.
```
{
    "aggs" : {
        "product" : {
            "terms" : {
                "field" : "productID",
                "order" : { "avg_sales_count" : "desc" }
            },
            "aggs" : {
                "avg_sales_count" : { "avg" : { "field" : "sales_count" } }
            }
        }
    }
}
```
Now I need the same support for geo-point fields to sort buckets from near to far.

The min/max/avg distance for each bucket can be returned by a scripted_metric sub aggregation, but its results can't be used to sort buckets.

**Comment by colings86** [comment]
Would using a script on the avg/min/max aggregation to calculate the avg/min/max distance from a fix point for each bucket. Because you would be using a numeric metric aggregation you would then be able to use this in the terms order feature.

```
"average_distance": {
  "avg": {
    "script": {
      "inline": "doc['point'].arcDistanceInKm(ref_lat, ref_lon)",
      "params": {
        "ref_lat": 51.512923,
        "ref_lon": -0.132785
      }
    }
  }
}
```

**Comment by zaobao** [comment]
I've solved this issue by writing a plugin.
https://github.com/zaobao/elasticsearch-aggregation-geometrics
