### ISSUE TITLE
Missing explanation about indices.store module in the documentation

### ISSUE THREAD

**Issue by philipskokoh** [elastic/elasticsearch#20022]
**Describe the feature**:

I found that there is a module for `indices.store.throttle` mentioned here:
https://www.elastic.co/guide/en/elasticsearch/guide/master/indexing-performance.html#segments-and-merging

However, I cannot find explanation about `indices.store.throttle` in the documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-indices.html

Are there other `indices.store` setting that we can tune?

**Comment by clintongormley** [comment]
these settings have been removed: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/breaking_20_setting_changes.html#_merge_and_merge_throttling_settings

**Comment by philipskokoh** [comment]
Then the definitive guide should be updated. People may think that the parameters still exist.
