### ISSUE TITLE
Decay function docs incorrect / confusing (log vs ln)

### ISSUE THREAD

**Issue by xyu** [elastic/elasticsearch#20027]
The [function score docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html#_supported_decay_functions) for how sigma and lambda are derived for the `gauss` and `exp` decay functions say they use as part of their equation `log(decay)`.

This is confusing because these functions are really taking the natural logarithm (`ln`) of decay not base 10 log. I understand that Java uses the `log()` [method](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#log-double-) to take the natural logarithm and that the `log10()` [method](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#log10-double-) is instead used for base 10 log. However the equations in this doc are written with LaTeX so I think they should therefore conform to commonly accepted math symbols (`ln`) rather then Java method names in this case.

**Comment by jasontedor** [comment]
The commonly accepted math symbol for natural logarithms [is](https://en.wikipedia.org/wiki/Natural_logarithm#Notational_conventions) `log`.

**Comment by xyu** [comment]
I understand that `log` is sometimes used but why not update the docs to use `ln` instead to avoid the possible ambiguity? As the wikipedia page you linked to says:

> The notations "ln x" and "loge x" both refer unambiguously to the natural logarithm of x. "log x" without an explicit base may also refer to the natural logarithm. This usage is common in mathematics and some scientific contexts as well as in many programming languages.[5] In some other contexts, however, "log x" can be used to denote the common (base 10) logarithm.
