### ISSUE TITLE
What language tag should we use for painless in the docs?

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#20025]
It [looks](https://github.com/elastic/elasticsearch/blame/master/docs/java-api/query-dsl/script-query.asciidoc#L15-L20) like right now we're using `[source,js]`. Should we teach the syntax highlighter we have for the docs to highlight painless and use `[source,painless]`? Maybe that is as simple as having the syntax highlighter use `js` or `groovy` for the highlighting when it sees `painless`?

**Comment by dakrone** [comment]
I use groovy syntax highlighting in my editor for painless scripts and it seems to work well, for the time being we can probably use `[source,groovy]` for the painless scripts?

**Comment by jasontedor** [comment]
I think we should stick with @nik9000's suggestion just so we do not have to cleanup in the future if we do come to teaching the syntax highlighter about Painless.

**Comment by nik9000** [comment]
> if we do come to teaching the syntax highlighter about Painless.

It also lets you grep for `[source,groovy]` and find all the groovy snippets.

**Comment by clintongormley** [comment]
btw the syntax highlighter we use at the moment is https://github.com/google/code-prettify

**Comment by nik9000** [comment]
> btw the syntax highlighter we use at the moment is https://github.com/google/code-prettify

In case anyone is also having trouble getting code highlighting to work: privacy badger kills the fetch from cdn.rawgit.com so you don't get it.

**Comment by nik9000** [comment]
I played with it a bit this morning and it does a half decent job of highlighting the snippets if you do `[source,painless]`. I suppose we could actually build a highlighter extension for it if we get upset with something that it does, but just labeling the snippets as `[source,painless]` seems to work well enough for now.

**Comment by nik9000** [comment]
Ok - look like I can just rename them. I'll open up a PR when I get around to it. If someone else wants it just grab assign it to yourself.
