### ISSUE TITLE
Safeguard for regex used in pattern tokenizer

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#20038]
Related to https://github.com/elastic/elasticsearch/issues/19901.  Given that there is a potential for a regex to go into endless recursions/backtracking, and bring down a shard, longer term it may be worthwhile to look into an alternate regex implementation for the pattern tokenizer or even moving it out to a plugin as an "advanced" feature.

**Comment by ppf2** [comment]
Not sure if this is the only case where a document can end up potentially bringing down the shard.  But this is a good opportunity to look at this in a broader view to see if having document isolation or similar (as a generic implementation) will be beneficial here. cc: @abeyad

**Comment by abeyad** [comment]
I don't believe a few bad documents or bad processing of documents should ever bring an entire shard down, so i'm +1 on finding a robust solution for this.  It won't be a trivial problem to solve, though we do handle similar issues in ES through various mechanisms (e.g. circuit breaker for too heavy aggregations, etc)

**Comment by romseygeek** [comment]
We have some safeguards for regexes coming in 6.3 (eg #28542), so I think this can be closed.
