### ISSUE TITLE
New feature. Search and run saved queries

### ISSUE THREAD

**Issue by Bilijoy** [elastic/elasticsearch#20049]
Hello,

I am storing some queries in Kibana, for example _idUser:244_ is saved as "Query1".
I need to execute "Query1" later, vía api, to get the results.

For example, I need something like this to get the results:

GET /_search/saved_queries/<queryNameToRun>

And something like this to get the stored queries:

GET /_search/saved_queries/list_all

Thanks!

**Comment by jpountz** [comment]
I think it would make more sense to implement such a feature on top of elasticsearch than in elasticsearch.

**Comment by clintongormley** [comment]
We already have search templates, which will do exactly what you need
