### ISSUE TITLE
Missing max_file_descriptors from process stats

### ISSUE THREAD

**Issue by Doweig** [elastic/elasticsearch#20048]
**Elasticsearch version**: 2.3.3

**Plugins installed**: []

**JVM version**: openjdk version "1.8.0_91"

**OS version**: Debian 8 (Docker) running on 4.5.0-coreos-r1

**Description of the problem including expected versus actual behavior**:

I'm trying to get the`max_file_descriptors` value but it's missing from the `process` stats object

**Steps to reproduce**:
 1. `curl localhost:9200/_node/_process?pretty`
 2. find the `process` object from the JSON response
 3. `max_file_descriptors` is missing

**Provide logs (if relevant)**:

```javascript
"nodes" : {
    "WFzPuO3IS_qcGOSpf-rWeg" : {
      "name" : "Stonecutter",
      "transport_address" : "10.12.1.85:9300",
      "host" : "10.12.1.85",
      "ip" : "10.12.1.85",
      "version" : "2.3.3",
      "build" : "218bdf1",
      "http_address" : "es-gl-shequ-stats-2.localhost/10.12.1.85:9200",
      "attributes" : {
        "master" : "true"
      },
      "process" : {
        "refresh_interval_in_millis" : 1000,
        "id" : 1,
        "mlockall" : false
      }
    },
    ...
}
```

**Describe the feature**:

`curl localhost:9200/_node/_process?pretty` is supposed to give informations on `max_file_descriptors` as [described on the official documentation](https://www.elastic.co/guide/en/elasticsearch/guide/current/_file_descriptors_and_mmap.html)

I have 3 nodes on 3 identical server, all have the same issue.

Thanks guys for your help :)

**Comment by clintongormley** [comment]
thanks @Doweig - it's moved to node-stats:

    GET _node/stats/process

i've updated the guide

**Comment by Doweig** [comment]
Yup, thanks ;)
