### ISSUE TITLE
can't give weight to function_score

### ISSUE THREAD

**Issue by laesunk** [elastic/elasticsearch#20047]
Hello. i wrote a query for scoring integer field. 
but i faced with a problem while giving a weight to my script query(decay_function)
I read some docs(below). i found boost_factor( under ES 1.3. i'm using 1.3 version)
(https://www.elastic.co/guide/en/elasticsearch/reference/1.3/query-dsl-function-score-query.html)

but it is not multiplying a weight but changing script score to just a weight that i given (description : "static boost factor")
I'm wondering it is working well or not? qeury is below

 {
          "exp": {
            "read_cnt": {
              "origin": "2478",
              "scale": "500",
              "offset": "0",
              "decay": 0.9
            }
          },
          "boost_factor": 0.6
}

**Comment by clintongormley** [comment]
@laesunk you need to upgrade.

Also,  please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
