### ISSUE TITLE
ClusterBlockException is not serializable!

### ISSUE THREAD

**Issue by spjoe** [elastic/elasticsearch#20054]
Make the following field transient, or make ClusterBlock serializable.

https://github.com/elastic/elasticsearch/blob/0f00c14afc8428a2a72c0b766d2171029dc8f6e1/core/src/main/java/org/elasticsearch/cluster/block/ClusterBlockException.java#L37

Every `Throwable `is marked with `Serializeable`, so every derived class must be serializable.

**Comment by jasontedor** [comment]
We do not use Java serialization for exceptions.

**Comment by spjoe** [comment]
Okay but we do, you cannot mark a class `Serializeable `but make it unserializable this breaks a lot of stuff. Please just make the field transient.
