### ISSUE TITLE
Standardize import sort order

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#20062]
Currently we have no standard specified for what the import statement order should be in java source files. Most developers here use intellij, but intellij and eclipse have different defaults. The matter is further complicated by a couple issues:
- Lucene uses the eclipse order (java imports first), so those who work on lucene as well are used to that (and at least I have intellij defaults set to match the eclipse defaults for this reason).
- Gradle+intellij do not provide the ability to customize this, so the intellij project generated for gradle always uses the intellij defaults (whatever that is set to in the users global defaults).
- It might be possible to generate eclipse and gradle projects with the same settings, but that would require maintaining manually edited intellij xml setting files, like lucene does

I don't have much of an opinion on this, but do think it would be nice if (my) PRs did not often have import statement reordering. But I also don't think just saying "we must use intellij defaults" is adequate enough of a policy. IMO the only way saying we use a specific order can work is if we do the work to make the generated intellij project consistent with the eclipse project (in project settings for both).

**Comment by nik9000** [comment]
I looked into seeing if I could customize Eclipse to do the same thing as the IntelliJ default a while back but it can't be configured in exactly the same way because of some ordering differences on inner classes - I forget exactly what it was.

If we really care about making the import order consistent we should make checkstyle fail the build if it is out of order. It has support for that if we feel it is important to turn on.

**Comment by rjernst** [comment]
We should not enforce this unless we can make both eclipse and intellij act the same. And like I said, just making eclipse use the "default default"  of intellij does not work. We would have to make sure both generated projects specify it explicitly.

**Comment by colings86** [comment]
I added the `build` label to this as it seemed the most appropriate label since we don't have (and I don't think we need) a `dev env` label. If you know of a more appropriate label for the functional area please add it instead

**Comment by nik9000** [comment]
A bunch of us talked about this and we don't really think this is worth it right now given that we can't convince Eclipse and IntelliJ to do the same thing. We've talked about using [google's formatter](https://github.com/google/google-java-format) for this sort of thing one day and we might get this if and when we do that.
