### ISSUE TITLE
Elasticsearch not running after update due to 'update_all_types' 

### ISSUE THREAD

**Issue by hsb1007** [elastic/elasticsearch#20069]
Hi all.

I am on Ubuntu with Elasticsearch not being able to start due to 'update_all_types' issue at the moment.

WIth Elasticsearch not running at all, how do we clear all index data? 

I am using Symfony elasticabundle to 'populate' the index.

With elastcisearch not running, it's hard to find its version as well but I assume it's above 2.0 because we have update_all_types mapping issue if I understand correctly.

Any advice would be so much appreciated!

**Comment by jpountz** [comment]
This indicates you are using types and some of them managed to go out of sync in spite of existing checks. Is it an index that was upgraded from 1.x?

> WIth Elasticsearch not running at all, how do we clear all index data? 

Removing the `data` directory should work. But beware it will remove all indexed data.

**Comment by clintongormley** [comment]
Given that @jpountz has answered the question and there is no more info available, I'm going to close this issue.  @hsb1007 if you think you have encountered a bug, please open an issue providing the relevant info

**Comment by hsb1007** [comment]
Yup Thank you so much for getting me on to the right direction. I have ended up downgrade elasticsearch!
