### ISSUE TITLE
Add alias action that deletes an index

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#20064]
If we add an alias action that deletes an index then we can swap an existing index with an alias in one request which applies the cluster state change atomically. This is quite useful because while the best practice is to address Elasticsearch indexes through aliases not everyone does that all the time. This will give folks who aren't using an alias an easy way to do it. Something like:

```
curl -XPOST 'http://localhost:9200/_aliases?pretty' -d '{
    "actions" : [
        { "delete_index" : { "index" : "important_stuff" } },
        { "add" : { "index" : "important_stuff_1471541773", "alias" : "important_stuff" } }
    ]
}'
```

It is super nice to do this in one action because:
1. The cluster state update is atomic so if there is any failure adding the alias then the index isn't deleted.
2. There is no time where a search for the index name comes back with no results. There would be, unfortunately, some time where the results can be a bit confused because index names aren't resolved to a permanent ID on the coordinating node. A procedure like this will minimize that time though.

**Comment by nik9000** [comment]
@clintongormley, we discussed this earlier today. It is an important precondition to doing #20024 and good even if we decide not to do #20024.

**Comment by clintongormley** [comment]
Great Nik.  The only thing is that I'd change `delete-index` to `delete_index` to be consistent with other parameters.

**Comment by nik9000** [comment]
Yeah, I'll do that. I noticed yesterday that this is one place where we
still support camelCase in and funny-dash-case and our normal snake_case.
Shall I drop support for the other two while I'm there? Camel case is
officially deprecated so that seems safe.

**Comment by clintongormley** [comment]
> Shall I drop support for the other two while I'm there? 

+1
