### ISSUE TITLE
Add explain support to percolate

### ISSUE THREAD

**Issue by Fiedzia** [elastic/elasticsearch#20076]
**Describe the feature**:

I can get explanation for search results, but not for results of percolation. That would be useful for me because I am trying to provide explanation to my users why they are getting the document I am returning.

Note that I care about explaining why given percolated query was matching the document,
not about why given set of percolation queries was tested (query part of percolate request).

**Comment by clintongormley** [comment]
@martijnvg would this be possible?

**Comment by martijnvg** [comment]
As part of the big percolator refactoring in 5.0, the `percolator` query can now provide an explanation about why the matching percolator query matched.

@Fiedzia If your try the latest 5.0 alpha release you can via the search api execute a `percolator` query and if your enable explain then ES can provide an explanation why the percolator query matched.

**Comment by clintongormley** [comment]
Awesome, thanks @martijnvg
