### ISSUE TITLE
ES 2.3.4 CPU high usage after 2-3 hours running arround 80-90% (Core i5 6400), exhaust after end of elasticsearch.bat (Java Platform SE Binary) application. What Happen with me?

### ISSUE THREAD

**Issue by tranbaohuu** [elastic/elasticsearch#20084]
**Elasticsearch version**:

**Plugins installed**: []

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jasontedor** [comment]
Elastic reserves GitHub for verified bug reports and feature requests. While this is very light on details, the looks like a general question that is best addressed in the [Elastic Discourse forums](https://discuss.elastic.co) or on IRC in #elasticsearch.
