### ISSUE TITLE
[docs] node query cache units are unclear

### ISSUE THREAD

**Issue by leeavital** [elastic/elasticsearch#20086]
The docs at https://github.com/elastic/elasticsearch/blob/2.3/docs/reference/modules/indices/query_cache.asciidoc say that I can specify the cache size as a percent, but it does not specify what the percent is of!

**Comment by clintongormley** [comment]
Thanks @leeavital - fixed by bc9e50e7e2ce6cf369cf441df58a55702833a67a

it's a percentage of heap

**Comment by leeavital** [comment]
Cheers, thanks @clintongormley
