### ISSUE TITLE
Automatically create aliases based on field

### ISSUE THREAD

**Issue by hijakk** [elastic/elasticsearch#20087]
**Describe the feature**:
I have a data stream that receives a finite, but arbitrary user defined set of tags. Aliases are an extremely valuable feature, and I've got a cron job that reads every index, reads every filtered alias currently assigned to it, and then compares that against the unique set of tags in that index. Any missing aliases are created.
Thus, if a record like 
`{"tag":["a1", "q2", "r8"]}`
is inserted into index monthly_2016_08, and the a1 and r8 filtered aliases already exist,
`{"term":{"tag":"a1"}}`
and
`{"term":{"tag":"r8"}}`
but the q2 alias does not, it will be created - 
`{"term":{"tag":"q2"}}`

In a sufficiently large cluster, this isn't the most lightweight operation to run on a regular basis, but we have to to keep our cross temporal index access to, say, /a1/_search working.

It seems like a potential optimization point with the index template aliases to allow dynamic creation of aliases based on the content of a specified field. Something like:
`{"aliases" : {"{value}" : {"field":"tag"} }}`
Whenever a unique token is inserted into the particular field, a filtered alias would automatically be created against that field. 
Essentially:
`{"term":{"tag":"{value}"}}`

There would also be minimal cycle time with an automated process - as it is, if a tag unique to the index is added, it could take up to the interval of the cron job to be activated - while for every other run in the day, no unique tags are added to the index. 

Is this a feasible feature?

**Comment by clintongormley** [comment]
Hi @hijakk 

I'm afraid this isn't something we would implement in Elasticsearch.  If we're going to add new features, we prefer to add primitives that users can combine to achieve their higher level goals.  This is a high level feature, which means that 10 users will want to do things in 11 different ways. The primitives already exist in Elasticsearch to implement this feature.
