### ISSUE TITLE
Upgrade to Lucene 6.2.0

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#20092]
I'm testing the Lucene 6.2.0 RC 1 by upgrading ES ... I have a few failing tests still, but I think it's close.

**Comment by rmuir** [comment]
I think we need to fix the AlreadyClosedException issues before doing this.

**Comment by s1monw** [comment]
@rmuir see https://github.com/elastic/elasticsearch/pull/20095/
