### ISSUE TITLE
Remove spaces from commented out config settings

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#20090]
From [time to time](https://discuss.elastic.co/t/path-repo-makes-es-fail-to-start/58482/3) a user runs into an issue with ES not starting and it's sometimes because they uncomment a config option in `elasticsearch.yml` but only remove the `#`.

eg; 
`# cluster.name: my-application`
becomes;
` cluster.name: my-application`
Note the white space in front (it's hard to see here).

Could we make this simpler for users by just removing that white space between the `#` and the setting? ie;
`#cluster.name: my-application`

**Comment by dadoonet** [comment]
I agree that a lot of people are falling into this trap. (Me included when I started my first Elasticsearch:) )

+1

**Comment by abeyad** [comment]
I agree, and it would also bring `elasticsearch.yml` in line with `logging.yml` and 'jvm.options`, which already practice this (no space between # and the setting). 

I've opened a PR for this: https://github.com/elastic/elasticsearch/pull/20094
