### ISSUE TITLE
Grant permission failed?

### ISSUE THREAD

**Issue by chenjinyuan87** [elastic/elasticsearch#20098]
I'm developing my own plugin based on 5.0.0 alpha5.
In this plugin, i need to create some files in the "config" folder.
Thus, i wrote a plugin-security.policy like this:
```
grant {
  permission java.io.FilePermission "<<ALL FILES>>", "read,write";
};
```
When installing the plugin, I received the following warn:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission <<ALL FILES>> read,write
```

It seems my policy is right. 
But when testing my plugin, i failed to create my configure file:
`java.lang.SecurityException: access denied ("java.io.FilePermission" "/home/es/elasticsearch-5.0.0-alpha5/config/ansj_dic/user" "write")`

What's the problem?

**Comment by dadoonet** [comment]
You'd better ask on discuss.elastic.co.

You should read https://www.elastic.co/guide/en/elasticsearch/plugins/master/plugin-authors.html

Where security is explained.
