### ISSUE TITLE
Mapping can't specify custom analyzer and default search_analyzer

### ISSUE THREAD

**Issue by joemoore13** [elastic/elasticsearch#20107]
**Elasticsearch version**:2.2.0

**Plugins installed**: [kopf]

**JVM version**:1.8

**OS version**:Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:
Specifying "search_analyzer : default" is ignored, but b/c of the ordering resolution here: https://www.elastic.co/guide/en/elasticsearch/guide/current/_controlling_analysis.html
the default analyzer is only used after the analyzer. i.e. search_analyzer> analyzer > default, but since the setting search_analyzer : default is ignored, it is impossible to achieve the equivalent of what we could in 1.x with index_analyzer: "custom", search_analyzer: "default".  You can workaround by creating a copy of default analyzer with a different name, but this change is non-obvious and difficult to notice if you arent looking for it, since it just silently ignores the settings for search_analyzer and uses ones with different results.
**Steps to reproduce**:
 1.
```
PUT test/_mapping/my_type
{
  "properties": {
    "field" : {
      "type": "string",
      "search_analyzer": "default",
      "analyzer" : "custom_analyzer"
    }
  }
}
```
 2.
```
GET test/_mapping/my_type
returns:
"user" : {
    "mappings" : {
      "user" : {
        "_all" : {
          "enabled" : false
        },
{
  ...
  "properties": {
    "field" : {
      "type": "string",
      "analyzer" : "custom_analyzer"
    }
  }
}
```
whereas you get back both analyzers if you do not set to default

**Comment by jpountz** [comment]
This was fixed by #16255 so upgrading to a more recent release (>= 2.3.0) should fix the issue. I just tried your recreation and I could indeed reproduce on 2.2.0 but not on 2.3.0.
