### ISSUE TITLE
ES 2.3.5 Node gets unstable (memory issue) if role is master

### ISSUE THREAD

**Issue by theely** [elastic/elasticsearch#20114]
**Elasticsearch version**: 2.3.5

**Plugins installed**: [license,marvel-agent]

**JVM version**:
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-8u102-b14.1-1~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)

**OS version**: Official Docker ES Image 2.3.5

**Description of the problem including expected versus actual behavior**:

I am running two nodes (elastic1, elastic2) on top of Mesos and Docker. Both nodes are running the official elasticsearch docker image version 2.3.5. Both nodes have the same Docker (1.11.2) and Mesos (0.28.1) version.
The main difference among the node is the hardware:
elastic1: 2 magnetic disks (RIDE 0), 64GB RAM,  AMD Opteron 6338P
elastic2: 2 SSD disks (RIDE 0), 128GB RAM,  Intel Xeon E5-1650V2

Since elastic 1 uses magnetic disks it has an additional es setting:
index.merge.scheduler.max_thread_count: 1

The issue is a bit complex to describe but basically when the node elastic2 acts as master it enters in a loop where it will use up all assigned memory (5GB) and than garbage collect all of it (takes about 10sec) to start over again. However if the node elastic2 is acting as slave everything runs smoothly. Attached you will find an image showing some metrics of the before and after master role assignment. The red line on the image indicates the exact time when roles are switch between the nodes.

![node-usage](https://cloud.githubusercontent.com/assets/2025999/17882022/2b33bc0c-690a-11e6-8420-2590bdf94cd2.png)

Also I will attach the log file showing the before and after entries. You can see the many GC runs and the time it takes. After the restart and the role switch no more entries were logged and the cluster was stable.

**Provide logs (if relevant)**:
[2016-08-22 12:43:21,536][WARN ][monitor.jvm              ] [elastic2] [gc][old][57319][19431] duration [10.5s], collections [1]/[10.6s], total [10.5s]/[2.6d], memory [4.7gb]->[4.7gb]/[4.9gb], all_pools {[young] [605.3mb]->[592.1mb]/[665.6mb]}{[survivor] [0b]->[0b]/[83.1mb]}{[old] [4.1gb]->[4.1gb]/[4.1gb]}
[2016-08-22 12:43:35,087][WARN ][monitor.jvm              ] [elastic2] [gc][old][57320][19432] duration [13.3s], collections [1]/[13.5s], total [13.3s]/[2.6d], memory [4.7gb]->[4.7gb]/[4.9gb], all_pools {[young] [592.1mb]->[603.2mb]/[665.6mb]}{[survivor] [0b]->[0b]/[83.1mb]}{[old] [4.1gb]->[4.1gb]/[4.1gb]}
[2016-08-22 12:43:46,271][WARN ][monitor.jvm              ] [elastic2] [gc][old][57321][19433] duration [11s], collections [1]/[11.1s], total [11s]/[2.6d], memory [4.7gb]->[4.8gb]/[4.9gb], all_pools {[young] [603.2mb]->[629.5mb]/[665.6mb]}{[survivor] [0b]->[0b]/[83.1mb]}{[old] [4.1gb]->[4.1gb]/[4.1gb]}
[2016-08-22 12:43:59,236][WARN ][monitor.jvm              ] [elastic2] [gc][old][57322][19434] duration [12.8s], collections [1]/[12.9s], total [12.8s]/[2.6d], memory [4.8gb]->[4.7gb]/[4.9gb], all_pools {[young] [629.5mb]->[593.4mb]/[665.6mb]}{[survivor] [0b]->[0b]/[83.1mb]}{[old] [4.1gb]->[4.1gb]/[4.1gb]}
[2016-08-22 12:44:10,448][WARN ][monitor.jvm              ] [elastic2] [gc][old][57323][19435] duration [11s], collections [1]/[10.6s], total [11s]/[2.6d], memory [4.7gb]->[4.7gb]/[4.9gb], all_pools {[young] [593.4mb]->[653.2mb]/[665.6mb]}{[survivor] [0b]->[0b]/[83.1mb]}{[old] [4.1gb]->[4.1gb]/[4.1gb]}
[2016-08-22 12:44:23,487][WARN ][monitor.jvm              ] [elastic2] [gc][old][57324][19436] duration [12.9s], collections [1]/[13.5s], total [12.9s]/[2.6d], memory [4.7gb]->[4.8gb]/[4.9gb], all_pools {[young] [653.2mb]->[636.9mb]/[665.6mb]}{[survivor] [0b]->[0b]/[83.1mb]}{[old] [4.1gb]->[4.1gb]/[4.1gb]}
[2016-08-22 12:44:34,708][WARN ][monitor.jvm              ] [elastic2] [gc][old][57325][19437] duration [11s], collections [1]/[10.6s], total [11s]/[2.6d], memory [4.8gb]->[4.7gb]/[4.9gb], all_pools {[young] [636.9mb]->[596.3mb]/[665.6mb]}{[survivor] [0b]->[0b]/[83.1mb]}{[old] [4.1gb]->[4.1gb]/[4.1gb]}
[2016-08-22 12:44:49,023][WARN ][monitor.jvm              ] [elastic2] [gc][old][57326][19438] duration [14.1s], collections [1]/[14.8s], total [14.1s]/[2.6d], memory [4.7gb]->[4.7gb]/[4.9gb], all_pools {[young] [596.3mb]->[588mb]/[665.6mb]}{[survivor] [0b]->[0b]/[83.1mb]}{[old] [4.1gb]->[4.1gb]/[4.1gb]}
Received killTask
Shutting down

================ MASTER SWITCH ================

[2016-08-22 12:44:58,478][INFO ][node                     ] [elastic2] version[2.3.5], pid[1], build[90f439f/2016-07-27T10:36:52Z]
[2016-08-22 12:44:58,478][INFO ][node                     ] [elastic2] initializing ...
[2016-08-22 12:44:58,825][INFO ][plugins                  ] [elastic2] modules [reindex, lang-expression, lang-groovy], plugins [license, marvel-agent], sites []
[2016-08-22 12:44:58,842][INFO ][env                      ] [elastic2] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda3)]], net usable_space [149.3gb], net total_space [434.5gb], spins? [possibly], types [ext4]
[2016-08-22 12:44:58,842][INFO ][env                      ] [elastic2] heap size [4.9gb], compressed ordinary object pointers [true]
[2016-08-22 12:44:59,955][INFO ][node                     ] [elastic2] initialized
[2016-08-22 12:44:59,955][INFO ][node                     ] [elastic2] starting ...
[2016-08-22 12:45:00,043][INFO ][transport                ] [elastic2] publish_address {xx.xx.xx.xx:9300}, bound_addresses {[::]:9300}
[2016-08-22 12:45:00,046][INFO ][discovery                ] [elastic2] newsriver/-JAQ76_VT3iWrWvYlre-rA
[2016-08-22 12:45:03,103][INFO ][cluster.service          ] [elastic2] detected_master {elastic1}{8iaBxIvQQn2JM7tNFMjaYg}{xx.xx.xx.xx}{xx.xx.xx.xx:9300}{master=true}, added {{elastic1}{8iaBxIvQQn2JM7tNFMjaYg}{xx.xx.xx.xx}{xx.xx.xx.xx:9300}{master=true},}, reason: zen-disco-receive(from master [{elastic1}{8iaBxIvQQn2JM7tNFMjaYg}{xx.xx.xx.xx}{xx.xx.xx.xx:9300}{master=true}])
[2016-08-22 12:45:03,182][INFO ][http                     ] [elastic2] publish_address {xx.xx.xx.xx:9200}, bound_addresses {[::]:9200}
[2016-08-22 12:45:03,182][INFO ][node                     ] [elastic2] started

**Comment by clintongormley** [comment]
Hi @theely 

The long GC messages make me think that you are swapping heap to disk.  Please see the documentation, and ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by theely** [comment]
Hi @clintongormley 
Thanks for the quick reply, I don't believe it is a swapping problem ES is running with the `bootstrap.mlockall: true` option as indicated by the documentation: https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html
Also if the issue would be some miss configuration why would it happen only if the node is running as master? And way does it affect only one node, they both share the same config?

I am writing here and not in the forum because to me this looks like some kind of memory leak, or some bug that under certain circumstances is eating up a lot of memory very quickly.
Anyway I am going to open a forum discussion as well and reporting back here if needed.

Thanks

**Comment by clintongormley** [comment]
hi @theely - sorry you're right, i read too quickly. Have you tried dumping the heap on the master and seeing what is using all of the memory?

**Comment by clintongormley** [comment]
Even just a nodes stats request when memory is full may be revealing

**Comment by jasontedor** [comment]
> Official Docker ES Image 2.3.5

Perhaps you already know this, but I say this for general benefit because there is a lot of confusion on this issue: at this time there is not an official Elasticsearch image. That is, there is no Docker image that claims to be "official" that is affiliated with Elastic.

Regarding your issue, do you have a lot of churn in your cluster state? Can you get a heap dump immediately before a full GC (you can't use a standard tool for this, they usually trigger a full GC and then take the heap dump; instead run `jinfo  -flag  +HeapDumpBeforeFullGC  <PID>` and don't forget to disable it with `jinfo  -flag  +HeapDumpBeforeFullGC  <PID>`after the heap dump that is produced immediately proceeding the next full GC).

**Comment by theely** [comment]
Hi there,
I am having some troubles in providing you with the memory dump. Firstly I have problems in replicating the issue on the node, expect for the disk space nothing has changed since I reported the issue. However the node elastic2 is now running as master for several days and the described memory issue has still not manifested himself.
The second problem is that jinfo or jmap binaries are not installed on the Docker image I am using since it is based on openJDK 8 **JRE**. I tried to manually copy the missing binaries from the JDK of the same openJDK version but that wont work (it can not locate the java runtime). Alternatively I could modify the Docker image to install the JDK instead of the JRE but I am afraid this will jeopardize the issue reproducibility. Alternatively I could try to enable JMX and remotely dumping the heap.

Any thoughts on how I could proceed?

**Comment by theely** [comment]
@clintongormley Looks like we were able to replicate the issue and we may also have isolated the problem. The node enters in a faulty behaviour under heavy usage of the following update script:
```
public long updateLastVisit(String hostname, BaseSource source) {

        String lastVisit = dateFormatter.format(new Date());
        //This script iterates trough all sources of a website and 
        //updates the lastVisit field of the specific source.
        Script updateSource = new Script("ctx._source['lastUpdate']='" + lastVisit + "' \n " +
                "ctx._source.sources = ctx._source.sources.each({ " +
                "item -> if (item['url'] == '" + source.getUrl() + "') { " +
                "item['lastVisit'] = '" + lastVisit +
                "'}" +
                "})");

        Client client;
        client = ElasticsearchPoolUtil.getInstance().getClient();
        try {

            UpdateRequest updateRequest = new UpdateRequest();
            updateRequest.index("newsriver-website")
                    .type("website")
                    .id(hostname)
                    .script(updateSource)
                    .retryOnConflict(3);


            return client.update(updateRequest).get().getVersion();

        } catch (ExecutionException e) {
            logger.error("Unable to update website source", e);
        } catch (InterruptedException e) {
            logger.error("Unable to update website source", e);
        }
        return -1;
    }
```
Is it possible that this script is causing the issue? It is executed concurrently several times per second.

In the mean time we are extending the Docker image to use the Java 8 JDK (see previous comment) hoping to retrieve a heap dump soon.

**Comment by jasontedor** [comment]
@theely It looks like you might not be returning the `client` to the pool or am I misunderstanding your script?

**Comment by tlrx** [comment]
You could also use script parameters so that the script will be compiled once and then cached and reused. 

In the current state it is compiled every time source & lastVisit changed (every time this code runs). The compilation produces many objects that need to be garbage collected and the fact that the script changed at almost every execution put a lot of pressure on the script cache.

**Comment by theely** [comment]
@jasontedor No the class name ElasticsearchPoolUtil  is misleading, in fact getClient() is sharing a singleton instance of a ES's Client object. If I am not mistaken this is the suggested approach, since the ES Client is thread safe.

We are testing a slight variation of the script that is updating the nested objects using a for loop instead of the .each() method.

```
 Script updateSource = new Script("ctx._source['lastUpdate']='" + lastVisit + "' \n " +
                "for (item in ctx._source.sources) {" +
                    "if (item['url'] == '" + source.getUrl() + "') { " +
                       "item['lastVisit'] = '" + lastVisit +
                   "'}" +
                "}");
```

![screen shot 2016-09-02 at 15 25 10](https://cloud.githubusercontent.com/assets/2025999/18205323/b1bc95ea-7121-11e6-97c4-41e0950038d1.png)

The new script started at 14h20 and beside a load increase on the machines (witch was expected, previously we disabled the old script) the nodes are quite stable.

Is it possible that the issue was related to the usage of the .each() method? Is there any issue using lambdas?

@tlrx I see I was not aware of it, I thought Groovy was fully interpreted. I will try it right away and post performance results.

I am actually not even sure we are supposed to make such an heavy use of nested object update method (via script)? The documentation concerning nested objects (https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-objects.html) is not covering the update topic.

**Comment by jasontedor** [comment]
> No the class name ElasticsearchPoolUtil is misleading, in fact getClient() is sharing a singleton instance of a ES's Client object. If I am not mistaken this is the suggested approach, since the ES Client is thread safe.

You should definitely rename that class as it's terribly misleading. :cry: The clients that we provide are thread-safe so your usage is fine then.

I think then that your issue is the issue that @tlrx pointed out.

> I see I was not aware of it, I thought Groovy was fully interpreted.

No, it gets compiled to bytecode at runtime.

**Comment by theely** [comment]
@jasontedor, @clintongormley Indeed looks like the issue was caused by the problem @tlrx pointed out.
My explanation is that by doing high usage of the Update API and using a script with "embedded" parameters ES **was quickly filling the heap with thousands of compiled groovy scripts instances**. After deploying the new script version that makes proper use of the parameters (shame on me 😅) the heap is stable and no longer growing (see picture).
![screen shot 2016-09-02 at 16 28 43](https://cloud.githubusercontent.com/assets/2025999/18207286/d2faea5a-712a-11e6-9d6e-be617cf8b9de.png)

I suppose the script cash has no size limit. I am wondering if it should be limited? For instance a portion of the heap. What was killing the node was the GC that needed more than 10s to clean up the heap. Alternatively we  could limit the number of cached scripts instances, does it make sense to cache thousands of scripts? I guess that if so many scripts need to be cached it is most probably a symptom of an error (like my case).

**Comment by tlrx** [comment]
> I suppose the script cash has no size limit. I am wondering if it should be limited?

As far as I remember the script cache is limited to 100 scripts. Once reached, every new script evicts the oldest one. This is what I meant by "putting pressure on the cache". The number of class/objects created by Groovy is difficult to contain (note: it creates classes for closure/lambdas too) but in newer version of Elasticsearch (see #19694) we added script compilation throttling to avoid too many scripts to be compiled per minute.

**Comment by clintongormley** [comment]
thanks for letting us know @theely 

btw, we've added a circuit breaker in 5.0 which would have caught this issue: https://github.com/elastic/elasticsearch/pull/19694

**Comment by theely** [comment]
@clintongormley and @tlrx I am not sure circuit breaker will solve the issue. I am afraid it will only mitigate it and make it harder to debug. In this case the issue has been easily discovered since many scripts were compiled per second. But in a different scenario let say a new script per minute gets compiled or even less the circuit breaker will not prevent the script cache and the heap to grow. Eventually at some point the GC will still need to free the memory from the compiled groovy scripts.

**My fear is that compiled groovy script are too heavy and complex objects structures to be saved in memory without special precautions.** 

This because even with a cache limit of only 100 scripts in my case this has not prevented the heap to be fully filled. Because the GC decided to keep the unreferenced objects in memory till the heap size reached its maximum allowed size. Then however the GC needed an enormous amount of time to free the memory from such heavy objects. And it would have been even worst if I would have assigned more memory to the nodes.

I would propose the following amendment:
 

1. Add some logging when the script cache limit is reached. This should alert the developer that something wrong is going on.
2. Handle compiled groovy script with extra care, for example caching them as SoftReferences and tuning the GC with -XX:SoftRefLRUPolicyMSPerMB=2500 or by explicitly calling the GC after avery script evacuation.

Do feel this is something that would make sense to elaborate further? I could try to come up with some suggestions and open a pull requests.

**Comment by tlrx** [comment]
I agree, the circuit breaker won't resolve the issue but in the case of Groovy it will prevent to create too many objects in a short time frame and then remove pressure on both cache and heap.

> My fear is that compiled groovy script are too heavy and complex objects structures to be saved in memory without special precautions.

I agree too, Groovy scripts can lead to many object/class creation. In your case you may be interested in moving to Native scripts or Painless.

> Add some logging when the script cache limit is reached. This should alert the developer that something wrong is going on.

I don't see a full cache as an issue. What concerns me is the fact to compile a lot of short living scripts that cause cache misses and cache eviction. Those are reported through the statistics API but maybe we could monitor and warn on too many cache eviction or misses?

> Handle compiled groovy script with extra care, for example caching them as SoftReferences and tuning the GC with -XX:SoftRefLRUPolicyMSPerMB=2500 or by explicitly calling the GC after avery script evacuation.

I don't think this is something we'd like to investigate as a default setting. This has a big impact on how object are managed in the JVM and can have consequence in other place we use (or will use) SoftReference. Same thing for explicit GC calls, this may just hang the JVM.

> Do feel this is something that would make sense to elaborate further? I could try to come up with some suggestions and open a pull requests.

Your suggestion for better warning message sounds appealing to me :) Point 2) seems too tricky and too dangerous to correctly implement so I'd say that it don't worth the trouble... But that's just my point of view so maybe you can wait for other opinion.

**Comment by CharlesLdy** [comment]
@theely @tlrx @clintongormley 
I got the same problem with elasticsearch 2.3.5, my jdk version is 1.7. The different is that my groovy script executed with logstash's output.  I got the exception out of memory permgen space twice. And the permgen space and heap space always growing.
At first, my script is just something like if...else. After I read the issue, I create a method to get the script compiled once and then cached and reused. but it did't work. can you help me ? thanks a lot!
my script:
`def orderConfirm(String orderId, double orderGmv, String orderConfirmTime, int buyCount) {
    if (ctx._source.orderConfirmNum) {
        ctx._source.orderConfirmNum += 1
    } else {
        ctx._source.orderConfirmNum = 1
    }

    if (ctx._source.orderConfirmTimes) {
        ctx._source.orderConfirmTimes += orderConfirmTime
    } else {
        if (ctx._source.orderConfirmTime) {
            ctx._source.orderConfirmTimes = [ctx._source.orderConfirmTime, orderConfirmTime]
        } else {
            ctx._source.orderConfirmTimes = [orderConfirmTime]
        }
    }

    if (ctx._source.orderIds) {
        ctx._source.orderIds += orderId
    } else {
        if (ctx._source.orderId) {
            ctx._source.orderIds = [ctx._source.orderId, orderId]
        } else {
            ctx._source.orderIds = [orderId]
        }
    }

    if (ctx._source.orderGmvs) {
        ctx._source.orderGmvs += orderGmv
    } else {
        if (ctx._source.orderGmv) {
            ctx._source.orderGmvs = [ctx._source.orderGmv, orderGmv]
        } else {
            ctx._source.orderGmvs = [orderGmv]
        }
    }

    if (ctx._source.buyCounts) {
        ctx._source.buyCounts += buyCount
    } else {
        if (ctx._source.buyCount) {
            ctx._source.buyCounts = [ctx._source.buyCount, buyCount]
        } else {
            ctx._source.buyCounts = [buyCount]
        }
    }

    if (!ctx._source.orderConfirm) {
        ctx._source.orderConfirm = 1
    }

    ctx._source.orderId = orderId
    ctx._source.orderGmv = orderGmv
    ctx._source.orderConfirmTime = orderConfirmTime
    ctx._source.buyCount = buyCount
}

orderConfirm('%{orderId}', %{orderGmv}, '%{orderConfirmTime}', %{buyCount})`

something like %{orderId} is just cite the variable from logstash's filter.
