### ISSUE TITLE
adding `date_detection: false` to an existing _type returns `"acknowledged": true`, but does not get added.

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch#20111]
**Elasticsearch version**: 2.3.5
**JVM version**:
```
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```
**Description of the problem including expected versus actual behavior**:
adding `date_detection: false` to an existing _type returns `"acknowledged": true`, but does not actually get added.

**Steps to reproduce**:
```
POST test2
PUT test2/_mapping/test
{
  "properties": {
    "date": {
      "type": "string"
    }
  }
}
POST test2/test
{ "date": "2014-01-01" }

PUT test2/_mapping/test
{
  "date_detection": false
}
GET test2/_mapping
```

**Comment by jpountz** [comment]
This reproduces on master too, and interestingly it seems that this never worked. I opened a pull request to make it work (#20119), but I'm tempted to make it a 5.0-only change to be safe since this never worked before.

**Comment by jpcarey** [comment]
@jpountz I have no pressing need since I only stumbled across this, so 5.0-only is fine by me.
