### ISSUE TITLE
Explain deprecation of geohash-prefix and friends

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#20126]
We've deprecated geohash-prefix and friend but we haven't explained why in the docs.

**Comment by nik9000** [comment]
This includes the following files:
* geohash-prefix.asciidoc
* geohash-precision.asciidoc
* lat-long.asciidoc
* geohash-cell-query.asciidoc

**Comment by imotov** [comment]
@nik9000 I cannot quite figure out what's missing here? Can we close this?
