### ISSUE TITLE
Provide a UI option through Marvel or HQ to manage rolling upgrades and restarts.

### ISSUE THREAD

**Issue by bunjamins** [elastic/elasticsearch#20133]
**Describe the feature**: Provide a UI option through Marvel or HQ to manage rolling upgrades, this could be a simple checkbox or option to set a cluster transient setting of /_cluster/settings "cluster.routing.allocation.enable": "none" but also to create this as maintenance mode which would keep the cluster in yellow state. this could streamline restarts and upgrades of the cluster significantly

**Comment by clintongormley** [comment]
Hi @bunjamins 

Features like this are on our roadmap, but this is not the right repository to discuss them.  Discussions about Marvel should happen in the forums instead https://discuss.elastic.co

thanks
