### ISSUE TITLE
min_doc_count not working for unique counts

### ISSUE THREAD

**Issue by dugpa** [elastic/elasticsearch#20137]
Using ElasticSearch v5 alpha 5 when doing normal counts, min_doc_count works fine. If doing a unique count, the min_doc_count continues to filter on total docs and not total unique docs.

**Comment by clintongormley** [comment]
Hi @dugpa 

Could you provide a small recreation that demonstrates the problem please?

**Comment by colings86** [comment]
No further feedback, closing
