### ISSUE TITLE
Render endpoint will not display invalid json

### ISSUE THREAD

**Issue by gary-harpaz** [elastic/elasticsearch#20138]
**Elasticsearch version**: 2.3.5

**Description of the problem including expected versus actual behavior**:
We are using search templates heavily. Previously I was able to debug json parse errors of my templates using the render endpoint. This is especially important when using conditional clauses which are not valid json, and therefore can not be validated before rendering.  
In this version the json parse exception is simply returned by the render endpoint.

**Steps to reproduce**:
1. Create the following search template. Note the intentional missing comma after {{size}}:

curl -X POST -H Content-Type: application/json  http://localhost:9200/_search/template/test-template -d {"template":"{\"size\":\"{{size}}\"\"query\":{\"match_all\":{}}}"}
1. Render the template using:
   curl -XGET "http://localhost:9200/_render/template" -d '
   { \
   "id" : "test-template", 
   "params": { 
     "size" : "10" 
   } 
   }'

The response is:
{
   "error": {
      "root_cause": [
         {
            "type": "json_parse_exception",
            "reason": "Unexpected character ('\"' (code 34)): was expecting comma to separate OBJECT entries\n at [Source: [B@ac52d7b; line: 1, column: 14]"
         }
      ],
      "type": "json_parse_exception",
      "reason": "Unexpected character ('\"' (code 34)): was expecting comma to separate OBJECT entries\n at [Source: [B@ac52d7b; line: 1, column: 14]"
   },
   "status": 500
}

I expect the result to contain the rendered template so that I can debug the syntax error as was available previous versions.

**Comment by clintongormley** [comment]
Replication in console:

    POST /_search/template/test-template
    {"template":"{\"size\":\"{{size}}\"\"query\":{\"match_all\":{}}}"}
    
    GET /_render/template
    { "id" : "test-template", "params": { "size" : "10" } }

@colings86 could you take a look please?

**Comment by clintongormley** [comment]
Note: this is fixed in 5.0

**Comment by colings86** [comment]
Closing since this is fixed in 5.0
