### ISSUE TITLE
match_phrase_prefix query does not work as expected

### ISSUE THREAD

**Issue by matzischatzi** [elastic/elasticsearch#20143]
**Elasticsearch version**: 2.3.5

**Plugins installed**: []

**JVM version**: 1.8.0_101

**OS version**: Windows 10 64bit

**Description of the problem including expected versus actual behavior**: When using the following request: 
{
"query": {
        "match_phrase_prefix": {
            "_all":"here"
        }
    }
}

the document count varies as follows for the input:
'h' : 2055 
'he' : 264
'her': 110
'here': 413
It appears as if elasticsearch does not perform prefix matching for this word but rather exact matching. Has this issue already been reported?

Many thanks!

**Comment by jpountz** [comment]
This is a known issue of `match_phrase_prefix` that made us consider removing it: #17655.
