### ISSUE TITLE
Naming inconsistency: field/stored_field

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#20155]
The `_search` API has replaced `fields` with `stored_fields` in the request, but the response still uses `fields`. The GET API still uses `fields` for both the request and the response.

Relates #18943

**Comment by jimferenczi** [comment]
> but the response still uses fields

The fields in the response are the concatenation of `stored_fields`, `docvalue_fields` and `script_fields` so I think that the naming is correct.

> The GET API still uses fields for both the request and the response.

We should change the request but not the response. It's also a concatenation of the other types of fields that can be requested.

I've also noticed that the documentation is not correct:
```
For backwards compatibility, if the fields parameter specifies fields which are not stored (`store` mapping set to
`false`), it will load the `_source` and extract it from it. This functionality has been replaced by the
<<search-request-source-filtering,source filtering>> parameter.
```
We don't "load the `_source` and extract it from it." anymore. I'll update the docs.

**Comment by jpountz** [comment]
Changing the `GET` API to take `stored_fields` rather than `fields` sounds good to me!

**Comment by clintongormley** [comment]
Historically, `fields` was a way of getting back just the fields you were interested in.  I'm thinking that we should do the same as we've done for search: remove `fields` and support `_source`, `stored_fields`, etc...

**Comment by jimferenczi** [comment]
> I'm thinking that we should do the same as we've done for search: remove fields and support _source, stored_fields, etc...

_source and source filtering are already supported. Though `docvalue_fields` is missing and I can rename `fields` to `stored_fields`.
