### ISSUE TITLE
Some boolean filters result in errors like "[and] query does not support [field1]"

### ISSUE THREAD

**Issue by apidruchny** [elastic/elasticsearch#20161]
Elasticsearch version: 2.3.5
Getting unexpected errors from some queries with filters. These queries worked with Elasticsearch version 1.7.5, but fail on version 2.3.5. Below are steps to reproduce.
 1. Create an index
```
PUT testindex
{
    "mappings" : {
        "type1" : {
            "properties" : {
                "field1" : { "type" : "string", "index" : "not_analyzed" }
            }
        }
    }
}
```
 2. Issue the following query:
```
POST
{
    "query" : {
        "match_all" : {}
    },
    "post_filter" : {
        "not" : {
            "and" : [
                {
                    "query" : {
                        "term" : {
                            "field1" : "1234"
                        }
                    }
                }
            ]
        }
    }
}
```
And the result is:
```
{
  "error" : {
    "root_cause" : [ {
      "type" : "query_parsing_exception",
      "reason" : "[and] query does not support [field1]",
      "index" : "testindex",
      "line" : 11,
      "col" : 29
    } ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query_fetch",
    "grouped" : true,
    "failed_shards" : [ {
      "shard" : 0,
      "index" : "testindex",
      "node" : "0JJWSN2WRwaX1dvaW3yPfA",
      "reason" : {
        "type" : "query_parsing_exception",
        "reason" : "[and] query does not support [field1]",
        "index" : "testindex",
        "line" : 11,
        "col" : 29
      }
    } ]
  },
  "status" : 400
}
```
Expected result, as it also works in Elasticsearch version 1.7.5:
```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```

**Comment by clintongormley** [comment]
Hi @apidruchny 

I can reproduce this failure - something funny in the parsing of the `not` query.  That said, `and`, `or`, and `not` are deprecated and have been removed in 5.0.  You should rewrite this query to use `bool` instead:

    POST _search
    {
      "query": {
        "match_all": {}
      },
      "post_filter": {
        "bool": {
          "must_not": [
            {
              "term": {
                "field1": "1234"
              }
            }
          ]
        }
      }
    }


By the way, use `post_filter` ONLY if you want to include documents in your aggregation that you then want to exclude from the returned `hits`.  Using it as a generic filtering mechanism is very inefficient

**Comment by apidruchny** [comment]
Yes, I know that boolean filters are deprecated, and post_filter is inefficient. This is just a distilled example. In reality our query is a much more complicated filtered query (no post_filter) and we are trying to migrate from version 1.7.5 to 2.3.5. Could this issue please be re-opened? Even being deprecated, the "not" filter should still work, to allow legacy applications to migrate to the current version of Elasticsearch. And this is exactly what we are trying to do.

**Comment by clintongormley** [comment]
Sure I can reopen it, but we're unlikely to fix deprecated functionality unless somebody sends a PR.  Why migrate to `not` when you're just going to have to repeat the migration for the next version anyway?

**Comment by apidruchny** [comment]
Thanks. We are not migrating to ```not```, we are migrating to Elasticsearch 2.3.5 and the ```not``` filter is already used in a legacy application. Sure, it will be necessary to replace the ```not``` filter eventually, but we would prefer to not have to do it now when we are still on version 1.7.5.

**Comment by apidruchny** [comment]
There is a very easy workaround (adding "filter" element under "not"). I am going to close this issue. Thanks for looking at this issue. Following works:
```
POST _search
{
    "query" : {
        "match_all" : {}
    },
    "post_filter" : {
        "not" : {
            "filter" : {
                "and" : [
                    {
                        "query" : {
                            "term" : {
                                "field1" : "1234"
                            }
                        }
                    }
                ]
            }
        }
    }
}
```
