### ISSUE TITLE
Create an example to show how the rank-eval endpoint is supposed to work

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#20164]
In [an earlier comment](https://github.com/elastic/elasticsearch/issues/19195#issuecomment-229752392) to #19195 using a tiny set of annotated Wikipedia queries seemed like a good real world use case to figure out whether the current setup of the rank-eval API has any flaws.

@cbuescher spent some time downsampling the wikipedia index to something manageable for this use case (essentially including those pages in the index that actually match the queries in the annotation sample above for a reasonably simple query structure).

As #19747 turned out to introduce quite a bit of complexity we thought that this might be a good chance to see what using the API might look like for a Java dev. Christoph came up with a really rough prototype [see here](https://github.com/cbuescher/elasticsearch/commit/ed944e89bc82ee7bd3197fb659e753b21a5b8c06) Turning that into a slightly cleaner standalone Java project turned out to be non trivial due to #18131.

Given that we'll stop supporting transport client anyway sooner or later, I'm wondering what the best path forward looks like for turning this into some demoable code.

One option I can think of:Directly use the page title as doc id to avoid the extra roundtrip at the top of this class. Use the REST API eg. via Python and forget about Java altogether.

@nik9000 @rjernst do you have any advice?

**Comment by MaineC** [comment]
On Thu, Aug 25, 2016 at 5:45 PM, Ryan Ernst <notifications@github.com>
wrote:

> When you are referring to the "java api", do you mean the transport client?
>
Jepp, that's what the example code linked from above is currently using.


> Are you saying the rank-eval work is in a plugin, and has classes that
> should be exposed in the transport client? If so, support for that was
> added in #19431 <https://github.com/elastic/elasticsearch/pull/19431>.
>

Great - thanks for pointing that out.

Isabel

**Comment by MaineC** [comment]
Still lost here. Let me reproduce the steps I took and the outcome I'd expect, maybe that helps.

I'm trying to create a demo Maven project, to build and run the [demo code](https://github.com/cbuescher/elasticsearch/commit/ed944e89bc82ee7bd3197fb659e753b21a5b8c06). To try that out locally I would like to make the [rank-eval jar](https://github.com/elastic/elasticsearch/tree/feature/rank-eval/modules/rank-eval) available in my local maven repository.

According to our [maven/gradle cheatsheet](https://github.com/elastic/elasticsearch/blob/master/GRADLE.CHEATSHEET) getting this done should be as simple as executing `gradle install`. Doing so in the module `rank-eval` (and for that matter also in `reindex`) leads me to the following output on the command line:


    :modules:reindex:signArchives SKIPPED
    :modules:reindex:install SKIPPED


    Skipping task ':modules:reindex:install' as task onlyIf is false.
    :modules:reindex:install SKIPPED


I added `  hasClientJar = true` to the `esplugin` section of build.gradle but get the same behaviour as above.

@rjernst @martijnvg any ideas where I took the wrong turn? (Telling me to just do away with the Java code and build the example in Python would be ok as well, I just want to make sure I don't go down this path just because I missed a small detail.)

**Comment by rjernst** [comment]
@MaineC using `gradle install` is the "old" way. With unified release, we now use the maven-publish gradle plugin, which provides `gradle publishToMavenLocal`. However, this does not quite work yet as how we generate the client jar's is a bit of a hack at the moment. I will work on fixing this, but using `hasClientJar = true` is the way to go, it just does not yet work with installing into maven .m2.

**Comment by MaineC** [comment]
@rjernst Thanks for the clarification (and the patience with explaining). Let me know when things are working, I'll go and backtrack to the docs that let me to believe that I should be using `gradle install` and update those then.

**Comment by cbuescher** [comment]
I think this can be close, if we create an example project we can now use the high level client.
