### ISSUE TITLE
_cat/nodes documentation is out of date

### ISSUE THREAD

**Issue by mrec** [elastic/elasticsearch#20162]
**Elasticsearch version**: 2.3.2

**Plugins installed**: `[
    analysis-korean           
    analysis-kuromoji         
    analysis-smartcn          
    analysis-stconvert        
    delete-by-query           
    enhanced-highlighter      
    enhanced-plain-highlighter
    entsearch                 
    head                      
    license                   
    marvel-agent              
    reindex                   
    repository-hdfs   
]`

**JVM version**: Java HotSpot(TM) 64-Bit Server VM 1.8.0_65

**OS version**: Oracle Linux 2.6.32-431.5.1.el6.x86_64

**Description of the problem including expected versus actual behavior**:
The (2.3) documented default columns for `_cat/nodes` bear no relation to reality. I found a few mentions of this page being very very out of date ([example](https://github.com/elastic/elasticsearch/pull/16656#issuecomment-183821524)), but no ticket for it.

**Steps to reproduce**:
 1. Browse to /_cat/nodes?v
 2. Browse to https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-nodes.html
 3. Compare and contrast

**Comment by clintongormley** [comment]
hi @mrec 

Thanks for opening.  Would you like to send a PR to update the docs?

**Comment by mrec** [comment]
Possibly, but it's not going to happen anytime very soon.
