### ISSUE TITLE
Should remove Nullable annotation for indexSettings in Mapper.BuilderContext

### ISSUE THREAD

**Issue by johtani** [elastic/elasticsearch#20174]
Now, 
Mapper.BuilderContext has indexSettings and it has [Nullable annotation](https://github.com/elastic/elasticsearch/blob/8c40b2b54eac3e3ab3c41ece5c758be75173191b/core/src/main/java/org/elasticsearch/index/mapper/Mapper.java#L51).
However, we should remove this annotation because Mapper is related indexSettings especially indexCreatedVersion I think, for example, #19860 requires the version for validating field name.
And having indexSettings is useful for implementing backward compatibility.

**Comment by jpountz** [comment]
+1 index settings should always be available there
