### ISSUE TITLE
It occurred error when I install bigdesk plugin

### ISSUE THREAD

**Issue by zte-wangning** [elastic/elasticsearch#20176]
**Elasticsearch version**: 
2.3.0

**Plugins installed**: 
elasticsearch-head-master

**JVM version**:
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**OS version**:
Linux node215 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
I want to get ElasticSearch CLuster realtime performance information  var bigdesk,but it occurred an error when I install the plugin. as follows:
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Steps to reproduce**:
 1. I download the plugin from github https://github.com/lukas-vlcek/bigdesk
 2. I installed the plugin to the one-node cluster used the command : 
      ./bin/plugin install file:/home/elasticsearch-ansible/bigdesk-master.zip 
 3. then the error occurred:
        -> Installing from file:/home/elasticsearch-ansible/bigdesk-master.zip...
    Trying file:/home/elasticsearch-ansible/bigdesk-master.zip ...
    Downloading ....DONE
    Verifying file:/home/elasticsearch-ansible/bigdesk-master.zip checksums if available ...
    NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
    ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by lukas-vlcek** [comment]
https://github.com/lukas-vlcek/bigdesk/issues/84#issuecomment-203772915

**Comment by clintongormley** [comment]
This is a community plugin not supported by Elasticsearch.  Closing
