### ISSUE TITLE
I continuously getting the same error on my cluster

### ISSUE THREAD

**Issue by samusenkoiv** [elastic/elasticsearch#20175]
I use elasticsearch 2.3
>  [2016-08-26 11:37:57,539][WARN ][index.translog           ] [Living Hulk] [request-new-db-2016.03][1] failed to delete unreferenced translog files
>  java.nio.file.FileSystemException: /usr/share/elasticsearch/data/rallyware-elasticsearch/nodes/0/indices/request-new-db-2016.03/1/translog: Operation not permitted
>       	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
>       	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
>       	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
>       	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
>       	at java.nio.file.Files.newDirectoryStream(Files.java:457)
>       	at org.elasticsearch.index.translog.Translog$OnCloseRunnable.handle(Translog.java:726)
>       	at org.elasticsearch.index.translog.Translog$OnCloseRunnable.handle(Translog.java:714)
>       	at org.elasticsearch.index.translog.ChannelReference.closeInternal(ChannelReference.java:67)
>       	at org.elasticsearch.common.util.concurrent.AbstractRefCounted.decRef(AbstractRefCounted.java:64)
>       	at org.elasticsearch.index.translog.TranslogReader.close(TranslogReader.java:143)
>       	at org.apache.lucene.util.IOUtils.closeWhileHandlingException(IOUtils.java:129)
>       	at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:354)
>       	at org.elasticsearch.index.translog.Translog.<init>(Translog.java:179)
>       	at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:208)
>       	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:151)
>       	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
>       	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1509)
>       	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1493)
>       	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:966)
>       	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:938)
>       	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:241)
>       	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
>       	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
>       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>       	at java.lang.Thread.run(Thread.java:745)
>  [2016-08-26 11:37:57,541][WARN ][index.translog           ] [Living Hulk] [request-new-db-2016.03][1] failed to delete temp file /usr/share/elasticsearch/data/rallyware-elasticsearch/nodes/0/indices/request-new-db-2016.03/1/translog/translog-7744687990160654189.tlog
>  java.nio.file.NoSuchFileException: /usr/share/elasticsearch/data/rallyware-elasticsearch/nodes/0/indices/request-new-db-2016.03/1/translog/translog-7744687990160654189.tlog
>       	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
>       	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
>       	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
>       	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
>       	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
>       	at java.nio.file.Files.delete(Files.java:1126)
>       	at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:358)
>       	at org.elasticsearch.index.translog.Translog.<init>(Translog.java:179)
>       	at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:208)
>       	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:151)
>       	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
>       	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1509)
>       	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1493)
>       	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:966)
>       	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:938)
>       	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:241)
>       	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
>       	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
>       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>       	at java.lang.Thread.run(Thread.java:745)
>  [2016-08-26 11:37:57,544][WARN ][indices.cluster          ] [Living Hulk] [[request-new-db-2016.03][1]] marking and sending shard failed due to [failed recovery]
>  [request-new-db-2016.03][[request-new-db-2016.03][1]] IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: FileSystemException[/usr/share/elasticsearch/data/rallyware-elasticsearch/nodes/0/indices/request-new-db-2016.03/1/translog/translog.ckp: Cannot allocate memory];
>       	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:250)
>       	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
>       	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
>       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>       	at java.lang.Thread.run(Thread.java:745)
>  Caused by: [request-new-db-2016.03][[request-new-db-2016.03][1]] EngineCreationFailureException[failed to create engine]; nested: FileSystemException[/usr/share/elasticsearch/data/rallyware-elasticsearch/nodes/0/indices/request-new-db-2016.03/1/translog/translog.ckp: Cannot allocate memory];
>       	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:155)
>       	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
>       	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1509)
>       	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1493)
>       	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:966)
>       	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:938)
>       	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:241)
>       	... 5 more
>  Caused by: java.nio.file.FileSystemException: /usr/share/elasticsearch/data/rallyware-elasticsearch/nodes/0/indices/request-new-db-2016.03/1/translog/translog.ckp: Cannot allocate memory
>       	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
>       	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
>       	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
>       	at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:230)
>       	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:581)
>       	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
>       	at java.nio.file.Files.copy(Files.java:1274)
>       	at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:344)
>       	at org.elasticsearch.index.translog.Translog.<init>(Translog.java:179)
>       	at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:208)
>       	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:151)
>       	... 11 more
>  [2016-08-26 11:37:57,546][WARN ][cluster.action.shard     ] [Living Hulk] [request-new-db-2016.03][1] received shard failed for target shard [[request-new-db-2016.03][1], node[VuX_pbrQRIe22Ugg4i1nNg], [P], v[1219], s[INITIALIZING], a[id=WiXkt1_lTzu1xUhxgPVvPg], unassigned_info[[reason=ALLOCATION_FAILED], at[2016-08-26T11:37:56.491Z], details[failed recovery, failure IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: FileSystemException[/usr/share/elasticsearch/data/rallyware-elasticsearch/nodes/0/indices/request-new-db-2016.03/1/translog/translog.ckp: Cannot allocate memory]; ]]], indexUUID [4URCbbqhT6iqZcxZFMIrzg], message [failed recovery], failure [IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: FileSystemException[/usr/share/elasticsearch/data/rallyware-elasticsearch/nodes/0/indices/request-new-db-2016.03/1/translog/translog.ckp: Cannot allocate memory]; ]
>  [request-new-db-2016.03][[request-new-db-2016.03][1]] IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to create engine]; nested: FileSystemException[/usr/share/elasticsearch/data/rallyware-elasticsearch/nodes/0/indices/request-new-db-2016.03/1/translog/translog.ckp: Cannot allocate memory];
>       	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:250)
>       	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)
>       	at org.elasticsearch.index.shard.StoreRecoveryService$1.run(StoreRecoveryService.java:129)
>       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>       	at java.lang.Thread.run(Thread.java:745)
>  Caused by: [request-new-db-2016.03][[request-new-db-2016.03][1]] EngineCreationFailureException[failed to create engine]; nested: FileSystemException[/usr/share/elasticsearch/data/rallyware-elasticsearch/nodes/0/indices/request-new-db-2016.03/1/translog/translog.ckp: Cannot allocate memory];
>       	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:155)
>       	at org.elasticsearch.index.engine.InternalEngineFactory.newReadWriteEngine(InternalEngineFactory.java:25)
>       	at org.elasticsearch.index.shard.IndexShard.newEngine(IndexShard.java:1509)
>       	at org.elasticsearch.index.shard.IndexShard.createNewEngine(IndexShard.java:1493)
>       	at org.elasticsearch.index.shard.IndexShard.internalPerformTranslogRecovery(IndexShard.java:966)
>       	at org.elasticsearch.index.shard.IndexShard.performTranslogRecovery(IndexShard.java:938)
>       	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:241)
>       	... 5 more
>  Caused by: java.nio.file.FileSystemException: /usr/share/elasticsearch/data/rallyware-elasticsearch/nodes/0/indices/request-new-db-2016.03/1/translog/translog.ckp: Cannot allocate memory
>       	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
>       	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
>       	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
>       	at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:230)
>       	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:581)
>       	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
>       	at java.nio.file.Files.copy(Files.java:1274)
>       	at org.elasticsearch.index.translog.Translog.recoverFromFiles(Translog.java:344)
>       	at org.elasticsearch.index.translog.Translog.<init>(Translog.java:179)
>       	at org.elasticsearch.index.engine.InternalEngine.openTranslog(InternalEngine.java:208)
>       	at org.elasticsearch.index.engine.InternalEngine.<init>(InternalEngine.java:151)
>       	... 11 more

Here's my `free -m`

> total used free shared buffers cached
> Mem: 3913 2876 1037 1 85 547
> -/+ buffers/cache: 2243 1670
> Swap: 0 0 0

And here's my `dh -f`

> Filesystem Size Used Avail Use% Mounted on
> none 40G 25G 14G 65% /
> tmpfs 2.0G 0 2.0G 0% /dev
> tmpfs 2.0G 0 2.0G 0% /sys/fs/cgroup
> none 233G 183G 50G 79% /usr/share/elasticsearch/data
> 192.168.10.1:/Users/ihorsamusenko/projects/elasticsearch/config/elasticsearch.yml 233G 183G 50G 79% /usr/share/elasticsearch/config/elasticsearch.yml
> /dev/disk/by-uuid/6051a71b-6e80-4e4d-a1f2-1ec74b9de3de 40G 25G 14G 65% /etc/hosts
> shm 64M 0 64M 0% /dev/sh

I'm getting these errors again and again. What could be the reason of that?
Thank you

**Comment by ywelsch** [comment]
you have already opened an issue on our Discourse forums, where I am helping you trying to figure this out. GitHub is reserved for bug reports and feature requests only.

**Comment by samusenkoiv** [comment]
@ywelsch github allows to publish bigger posts, so I posted here more detailed trace
