### ISSUE TITLE
Extract hour of day from timestamps

### ISSUE THREAD

**Issue by webattitude** [elastic/elasticsearch#20193]
**Elasticsearch version**:
2.3.4

**Plugins installed**: []

**JVM version**:
1.8.0_91

**OS version**:
Debian 8.5 (jessie)

**Description of the problem including expected versus actual behavior**:
Can one extract hour of day from docs timestamp ?
I'd like to make for example a bar chart with events repartition by hour of day.

**Comment by jasontedor** [comment]
Elastic reserves GitHub for verified bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) for general questions.
