### ISSUE TITLE
[5.0alpha5] rpm install ignores vm.max_map_count setting on RHEL 7.2

### ISSUE THREAD

**Issue by karlgrose** [elastic/elasticsearch#20195]
**Elasticsearch version**: 5.0alpha5

**Plugins installed**: default

**JVM version**: 1.8.0_101

**OS version**: RHEL 7.2

**Description of the problem including expected versus actual behavior**: Using the rpm install via yum, the file /usr/lib/sysctl.d/elasticsearch.conf is installed, but its settings for vm.max_map_count are ignored by the OS

**Steps to reproduce**:
 0. sudo sysctl vm.max_map_count (shows pre-installation setting)
 1. yum install elasticsearch
 2. sudo sysctl --system
 3. sudo sysctl vm.max_map_count (shows value unchanged from before)

**Workaround**:
add a symlink as follows:
cd /usr/lib/sysctl.d
sudo ln -s elasticsearch.conf 90-elastic.conf

Now when "sudo sysctl --system" is run the config file is parsed and a new value is obtained for vm.max_map_count suggesting that the config file might better be named in the format nn-elasticsearch.conf to be processed by the OS.

**Comment by clintongormley** [comment]
It seems that there is a different service with a higher priority which is overwriting the settings in `elasticsearch.conf`.  Perhaps we should just update the file name?

**Comment by karlgrose** [comment]
Yes, this was a priority conflict created by my having added elasticsearch.conf in /etc/sysctl.d to set a kernel swappiness setting while not realizing that a lower-priority file was in /usr/lib/sysctl.d already. Setting those packaging-based files to less common names (such as the one suggested) would prevent this sort of user error.

**Comment by clintongormley** [comment]
Discussed in FixItFriday - essentially we're competing with other services, so we could change our file to `90-` then another service could change theirs to `99-` etc.  There is no consistent way of enforcing this.  And perhaps Elasticsearch settings are overwriting things that are important for other services.

So we don't think we should do anything here.  The good news is that, if another service changes an important setting to a value that is incompatible with running Elasticsearch, we will refuse to start.  This makes it easy for the user to spot that there is a problem and to rectify it using (eg) the symbolic link workaround that you presented.
