### ISSUE TITLE
Rename template name/pattern match field

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#20202]
[Here](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-templates.html) we have;

```
PUT /_template/template_1
{
  "template": "te*",
  "settings": {
    "number_of_shards": 1
  }
```

As you can see we reference the term **template** 3 times in 3 lines, which is pretty loaded - even if the second (`template_1`) is an example name of a template.

I was speaking to a new user the other day and they mentioned that the second reference to **template** isn't immediately obvious that it applies to the index name/pattern that this template should match.

I thought I'd raise this issue to see if perhaps we can rename it to `match_pattern`, or `index_pattern` or something else that is a little more descriptive.

**Comment by johtani** [comment]
Duplicated of #18922 .
