### ISSUE TITLE
Missing footnote descriptions in mappings

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#20201]
At the bottom of [this page](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/mapping.html) there are 13 listed footnotes, but only the first 5 have descriptions associated with them.

It looks like the extra numbers are autogenerated as we reference them in the code blocks and we're just missing the other 8.

**Comment by nik9000** [comment]
This looks more like a layout issue. They look to be grouped intentionally and the comments make sense. I wonder if it'd look nicer if `<2>` and `<8>` just used the same number?

**Comment by clintongormley** [comment]
This is just how asciidoc -> docbook works.  Nothing we can do here
