### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.common.collect.ImmutableSet.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;[Ljava/lang/Object;)Lcom/google/common/collect/ImmutableSet;

### ISSUE THREAD

**Issue by ruanzy** [elastic/elasticsearch#20204]
java.lang.NoSuchMethodError: com.google.common.collect.ImmutableSet.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;[Ljava/lang/Object;)Lcom/google/common/collect/ImmutableSet;

**Comment by jpountz** [comment]
@ruanzy We cannot help if you do not provide more information. Can you provide us with the elasticsearch version, list of installed plugins (+version) and the sequence of operations that needs to be performed to trigger this exception?

**Comment by ruanzy** [comment]
elasticsearch 2.3.5   jdk  1.7

**Comment by ruanzy** [comment]
`			client = TransportClient.builder().build()
					.addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName(host), 9300));`

**Comment by jpountz** [comment]
Could it be that you upgraded some dependencies without recompiling your application?

**Comment by ruanzy** [comment]
I have referenced all the jar packages in the elasticsearch/lib directory.

**Comment by jpountz** [comment]
Did you reference exactly the same jars at compile time and runtime? The error you get means that a method could not be invoked at runtime since it could not be found. But then compilation should have failed too, hence my question. Could you recompile your application against the exact same jars that you put on the classpath at run time and check whether you still have the issue.

Another possibility is that you have two different jars that have the `com.google.common.collect.ImmutableSet` class and for some reason a different one was picked at compile time and run time.

**Comment by ruanzy** [comment]
`client = TransportClient.builder().build() .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName(host), 9300));`

at run time

**Comment by jpountz** [comment]
Did you recompile?

**Comment by ruanzy** [comment]
sure

**Comment by ywelsch** [comment]
@ruanzy you seem to have an old Guava version on your classpath (or google-collect, the predecessor to guava). Can you provide us with a full list of JARs on your classpath?

see also:
http://stackoverflow.com/questions/25808115/google-contacts-java-lang-nosuchmethoderror-com-google-common-collect-immutab

**Comment by ruanzy** [comment]
D:\elasticsearch\lib\apache-log4j-extras-1.2.17.jar
D:\elasticsearch\lib\commons-cli-1.3.1.jar
D:\elasticsearch\lib\compiler-0.8.13.jar
D:\elasticsearch\lib\compress-lzf-1.0.2.jar
D:\elasticsearch\lib\elasticsearch-2.3.5.jar
D:\elasticsearch\lib\guava-18.0.jar
D:\elasticsearch\lib\HdrHistogram-2.1.6.jar
D:\elasticsearch\lib\hppc-0.7.1.jar
D:\elasticsearch\lib\jackson-core-2.6.6.jar
D:\elasticsearch\lib\jackson-dataformat-cbor-2.6.6.jar
D:\elasticsearch\lib\jackson-dataformat-smile-2.6.6.jar
D:\elasticsearch\lib\jackson-dataformat-yaml-2.6.6.jar
D:\elasticsearch\lib\jna-4.1.0.jar
D:\elasticsearch\lib\joda-convert-1.2.jar
D:\elasticsearch\lib\joda-time-2.9.4.jar
D:\elasticsearch\lib\jsr166e-1.1.0.jar
D:\elasticsearch\lib\jts-1.13.jar
D:\elasticsearch\lib\log4j-1.2.17.jar
D:\elasticsearch\lib\lucene-analyzers-common-5.5.0.jar
D:\elasticsearch\lib\lucene-backward-codecs-5.5.0.jar
D:\elasticsearch\lib\lucene-core-5.5.0.jar
D:\elasticsearch\lib\lucene-grouping-5.5.0.jar
D:\elasticsearch\lib\lucene-highlighter-5.5.0.jar
D:\elasticsearch\lib\lucene-join-5.5.0.jar
D:\elasticsearch\lib\lucene-memory-5.5.0.jar
D:\elasticsearch\lib\lucene-misc-5.5.0.jar
D:\elasticsearch\lib\lucene-queries-5.5.0.jar
D:\elasticsearch\lib\lucene-queryparser-5.5.0.jar
D:\elasticsearch\lib\lucene-sandbox-5.5.0.jar
D:\elasticsearch\lib\lucene-spatial3d-5.5.0.jar
D:\elasticsearch\lib\lucene-spatial-5.5.0.jar
D:\elasticsearch\lib\lucene-suggest-5.5.0.jar
D:\elasticsearch\lib\netty-3.10.5.Final.jar
D:\elasticsearch\lib\securesm-1.0.jar
D:\elasticsearch\lib\snakeyaml-1.15.jar
D:\elasticsearch\lib\spatial4j-0.5.jar
D:\elasticsearch\lib\t-digest-3.0.jar

**Comment by ywelsch** [comment]
Are you absolutely sure this is the full list?

please add the following lines

```
System.out.println(System.getProperty("java.class.path"));
System.out.println(com.google.common.collect.ImmutableSet.class.getResource("ImmutableSet.class"));
```

to your program before the call to `client = TransportClient.builder().build() .addTransportAddress(new ...` and provide us the output.

**Comment by jpountz** [comment]
Closing because of lack of feedback.
