### ISSUE TITLE
Remove the `analyze_wildcard` option

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#20209]
If we get #20208 in then the only remaining benefit of the `analyze_wildcard` option is that it tokenizes prefix queries so that eg. `foo-bar*` is parsed to `foo AND bar*` with a query parser that parses on dashes. However I am not sure this was really an intented feature, rather a consequence of the fact that if the analyzer would generate multiple tokens, then we had to find some way to use them that makes sense. However now that analyzers have a way to apply character-level normalization only, we could remove `analyze_wildcard` and just normalize the prefix without tokenizing?

**Comment by nik9000** [comment]
If the document was `foo-barf` then it'd be tokenized as `foo`, `barf` which `foo AND bar*` actually finds but `foo-bar*` doesn't. OTOH as soon as you start throwing in stemming it'll fall over in weird ways so it is too scary to actually rely on.

Personally I'd be ok removing it just because analyzing prefixes is so funky.

**Comment by clintongormley** [comment]
here's the reason this option was added https://github.com/elastic/elasticsearch/issues/787

downside is it only works some of the time

**Comment by Grinnz** [comment]
We use this because we need to normalize wildcard searches. Unfortunately it seems that it doesn't work on terms that aren't prefixes, e.g. *foo, so we have to manually normalize those search terms.

**Comment by jpountz** [comment]
I just ran the following locally and it worked for me, the wildcard search was normalized:

```
PUT index/doc/1
{
  "body": "foobar"
}

GET index/_search
{
  "query": {
    "query_string": {
      "query": "body:F*R"
    }
  }
}
```
Maybe you are testing on a pre-5.2 cluster that does not automatically normalize wildcard queries? Otherwise I'd be interested to look at a recreation of this issue.

**Comment by Grinnz** [comment]
This is on 5.4. Try with this analyzer and a query starting with a wildcard:

```
{"type":"pattern","lowercase":true,"pattern":"\\s"}
```

**Comment by jpountz** [comment]
Thanks, it is a bug indeed. I opened #24967.

**Comment by Grinnz** [comment]
For the record, I've since switched us to a custom analyzer with the 'whitespace' tokenizer and 'lowercase' token filter, and everything works as expected without setting analyze_wildcard.

**Comment by andyb-elastic** [comment]
@elastic/es-search-aggs

**Comment by javanna** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
