### ISSUE TITLE
Disable stdout (duplicate logs)

### ISSUE THREAD

**Issue by jlecour** [elastic/elasticsearch#20212]
**Elasticsearch version**: 2.3.5

**JVM version**: OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-1~deb8u1)

**OS version**: Debian 8.5

**Description of the problem including expected versus actual behavior**: log messages are written to `${path.logs}/${cluster.name}.log` **and** `stdout`. When using SystemD, logs end up in two files (ES log and syslog)

I don't see a good reason to keep both locations for logs (see "the bad" section here : http://www.kibinlabs.com/systemd-logging-tricks/)

**Comment by jlecour** [comment]
Hey, my report wasn't supposed to be harsh or rude, but only a matter to discuss for a possible improvement.
I really like Elasticsearch and appreciate all the work you all put in it. Thank you very much.

**Comment by clintongormley** [comment]
No worries @jlecour - wasn't taken like that at all :)

**Comment by tlrx** [comment]
We added a `--quiet` option to elasticsearch in #20422 to disable stdout log messages. It has been added in the elasticsearch's systemd service file for 5.0 and 6.0. 

I'm closing this issue since it will be fixed in the next major version. Feel free to reopen if needed.

**Comment by simonclausen** [comment]
I think it would be reasonable to have this fixed in the 2.x branch as well, as it is not a major change and as mentioned "bad".

If 2.x goes the same way as 1.x, it will live some time before going out of support and will probably see a number of minor version releases.
