### ISSUE TITLE
When the update aliases action is applied to indexes with many aliases that alias resolution step is a bottleneck

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#20210]
The [`_aliases`](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html) action can take a long time to resolve the names of aliases to remove removing aliases from indices with many aliases.

I'm reporting this second hand so I'm not 100% sure what the reproduction steps are. Like, how many aliases it takes before resolution is slow and how slow is it?

**Comment by ywelsch** [comment]
Relates to #16853

**Comment by hub-cap** [comment]
Closing this for lack of detail. There is definitely a limitation to the number of aliases for a normal deployment.
