### ISSUE TITLE
how can i install marvel in windows？

### ISSUE THREAD

**Issue by MyNameIsFei** [elastic/elasticsearch#20228]
`E:\kibana-4.5.4-windows\bin>kibana plugin -i marvel -u file:///E:/kibana-4.5.4-windows/temp/marvel-2.3.4.tar.gz
Installing marvel
Attempting to transfer from file:///E:/kibana-4.5.4-windows/temp/marvel-2.3.4.tar.gz
Error: ENOTFOUND
Plugin installation was unsuccessful due to error "No valid url specified."`

**Comment by ywelsch** [comment]
GitHub is reserved for bug reports and feature requests. The best place
to ask a general question is at the Elastic Discourse forums at
https://discuss.elastic.co
