### ISSUE TITLE
[2.4 code issue]MergePolicyConfig.java: defind static string while still use hard code string

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#20224]
public static final String INDEX_MERGE_POLICY_MAX_MERGED_SEGMENT = "index.merge.policy.max_merged_segment";
ByteSizeValue maxMergedSegment = indexSettings.getAsBytesSize("index.merge.policy.max_merged_segment", DEFAULT_MAX_MERGED_SEGMENT);

and there are many same issues in this class.

**Comment by jasontedor** [comment]
This has already been addressed in master, and will not be backported to 2.4 (there is no bug here).
