### ISSUE TITLE
[feature request]add a safeguard for segment memory

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#20226]
I have a big cluster which has many nodes and each nodes hold many data. some of those data are open(currently been used) and some are closed(currently not been used).
then some of users want to open some closed index, and I open them. suddently, the cluster crashed due to some of nodes long gc and then more nodes long gc
so why not add a safeguard for segment memory, in this case, when segment memory breaks the safegurad, the exception should be thrown and save the cluster.

**Comment by clintongormley** [comment]
Discussed in FixItFriday.  We have done a lot of work to try to reduce the amount of memory used by segments.  Interfering with this process would be complex and likely introduce bugs.  Instead, we'd rather solve this issue with the `max_shards_per_node` setting described in https://github.com/elastic/elasticsearch/issues/20760#issuecomment-252206854
