### ISSUE TITLE
Elasticsearch unstable after upgrade from 1.7.2 to 2.3.5 - multiple issues

### ISSUE THREAD

**Issue by AGirin** [elastic/elasticsearch#20232]
**Elasticsearch version**: 2.3.5

**Plugins installed**: [head, kopf, cloud_aws, marvel, license]

**JVM version**: 1.8.0_51

**OS version**: CentOS 6.6

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Cluster has 21 nodes. Previous version (1.7.2) worked with no issues for more than a year. 

What we see is huge spike in write IOPS per node (500 writes/s before 2500 writes/s now). Around noon we have a script that reads a lot of data from this cluster and our read IOPS go high as well. We are running on AWS and the volume has only 3,000 max. With all those IOPS we hit the limit of 3,000 and at this point Elastisearch goes down. 

![image](https://cloud.githubusercontent.com/assets/5177657/18093612/16ea9248-6e96-11e6-9fcc-9acda254116b.png)

When we look at all ES nodes and get the status of Elasticsearch service we get this: `elasticsearch dead but subsys locked`. When we try to start ES backup we get this:
```

Starting elasticsearch: Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000429990000, 15408234496, 0) failed; error='Cannot allocate memory' (errno=12)

 There is insufficient memory for the Java Runtime Environment to continue.
 Native memory allocation (mmap) failed to map 15408234496 bytes for committing reserved memory.
 An error report file with more information is saved as:
 /tmp/hs_err_pid8710.log
[FAILED]
```

So apparently init script does not correctly report Elasticsearch status - ES is still running but it is in a bad state. So we have to kill ES manually with kill -9 (which is not fun at all on 21 servers) and only then we can start ES back online.

So with that multiple questions:

1. Why does new ES has so much more write IOPS? How do we prevent this? 

One possibility is that auto-throttling is in place? We used to have this setting in our previous cluster:

indices.store.throttle.max_bytes_per_sec = "100mb"

So 2.3.5 apparently has auto-throttling enabled by default. Since it is impossible to delete our previous setting - does new ES just ignores it? Or how do we delete it? How can we disable auto-throttling if it causes the issue?

2. What is wrong with init script? We use official rpm and it seems there is a bug with init script - it does not correctly detect hung process. How can we fix that? 

Thanks a lot!

**Comment by jasontedor** [comment]
These looks like general questions rather than a bug report and Elastic reserves GitHub for verified bug reports and feature request. The best place to ask general questions is the [Elastic Discourse forums](https://discuss.elastic.co).

> Why does new ES has so much more write IOPS? How do we prevent this?

This is probably due to fsyncing per request. If you're not using bulk requests, use bulk requests. If are you using bulk requests, you could look at increasing the size of the payload per request. Lastly, you can disable fsync per request by setting `index.translog.durability` to `async` but note that this comes with a loss of safety.

> What is wrong with init script? We use official rpm and it seems there is a bug with init script - it does not correctly detect hung process. How can we fix that?

Duplicates #19297

**Comment by AGirin** [comment]
So... How do we fix init script? I looked at all the messages in #19297 and followed ALL references to other  numerous issues and have yet to see the fix. Is this still an open issue? Hard to believe it is not fixed - the problem was reported in 2015.

**Comment by jasontedor** [comment]
> Is this still an open issue?

Yes.

> Hard to believe it is not fixed - the problem was reported in 2015.

That's not how things work.
