### ISSUE TITLE
Upgrading to ES2.3.4 caused date field mapping to change

### ISSUE THREAD

**Issue by jsmilkstein** [elastic/elasticsearch#20238]
**Elasticsearch version**: 1.5.2 -> 2.3.4

**Plugins installed**: None

**JVM version**: 

**OS version**: CentOS 7 (various)

**Description of the problem including expected versus actual behavior**:
We had a date field which mappings enforced through applying a template like:
"normalDate": {
                  "type": "date",
                  "format": "dateOptionalTime",
                  "store": true
               },
And stored dates were YYYY-MM-DD hh:mm:ss as expected.  Upon upgrading to ES2.3.4, all mappings for existing indices were changed to:
"normalDate" : {
            "type" : "date",
            "store" : true,
            "format" : "epoch_millis||dateOptionalTime"
          }
And now dates are represented with epoch_millis.  All new indices created after upgrade have the proper template applied and dates are as-expected.
I believe this mapping can be corrected, or dates normalized on return, but it doesn't seem like the mapping should change just through upgrade for an existing index.

**Steps to reproduce**:
 1.  Create document with a date field, send in using a dateTime format in ES1.5
 2. Upgrade to ES2.3.4
 3. Check mappings for the field, and the representation of the data in ES after upgrade.

**Comment by dakrone** [comment]
@jsmilkstein I believe this is because the mappings have been updated to include that format, which was implicit before (it's now explicit), see: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/breaking_20_mapping_changes.html#_default_date_format

1.5 supported sending epoch_millis before, it was just never returned in the mapping.

**Comment by jsmilkstein** [comment]
Then you would suggest being explicit with our date format in the template file now?  It’s just strange because it was never that way before, and isn’t with new indices, but all existing indices got that format appended.

**Comment by dakrone** [comment]
> Then you would suggest being explicit with our date format in the template file now?

If you are able, being explicit will always be easier to reason about than dynamic mapping

> It’s just strange because it was never that way before, and isn’t with new indices, but all existing indices got that format appended.

This is so they did not suddenly break a client that might be sending timestamps like `{ "normalDate": 182991892 }`, the mappings are just explicit about supporting this now (they always did in 1.5)
