### ISSUE TITLE
Add support for templating to rank-eval

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#20231]
Problem: In it's current state the rank-eval request API forces the user to repeat complete queries for each test request. In most use cases the structure of the query to test will be stable with only parameters changing across requests, so this looks like lots of boilerplate json for something that could be expressed in a more concise way.

**Comment by MaineC** [comment]
Proposal: Use templating/ ScriptServices to enable users to submit only one test request template and let them only specify template parameters on a per test request basis.


Input from @martijnvg: "So in general, if templating is required, an api can just call the ScriptService and create a Script with ‘mustache’ as language. This way there is no hard compile time dependency to mustache. But when ES is running with all its modules, the template provided as Script gets rendered. An example of this can be found in the phrase suggester which has a collate parameter. Collate is kind of a query that gets run in order to verify a suggestion.

In phrase suggester the collate function is provided as Script and contains the query and provide access to phrase suggestion variables, only know at runtime.

https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/suggest/phrase/PhraseSuggestionBuilder.java#L394

If using the scriptservice directly for templating doesn’t make sense or can’t somehow not work in rank eval api, please let me know. So somewhere in the rerank api you should use script service to evaluate a Script that has been provided by the user. (the user thinks it is a template, but we don’t make a difference between scripting and templating in ES)."

**Comment by MaineC** [comment]
Example of an API request:

    GET /index/type/_rank_eval/template
    {
        "spec_id": "human_readable_id",
        "template": "string that constitutes a search request template",
        "requests": [{
            "id": "human_readable_id",
            "params": { ... params to the request to check ... },
            "ratings": { ... mapping from doc id to rating value ... }
         }],
        "metric": {
            "... metric_name... ": {
                "... metric_parameter_key ...": ...metric_parameter_value...
            }
        }
      }

@clintongormley feedback on the proposed API welcome

**Comment by clintongormley** [comment]
I'm on the fence about this one.  Should it be a single template specified at the top level, or should you be able to specify a different template per request.  Certainly the former would be a common use case, but the latter is more flexible (if more verbose).  But perhaps a UI would solve the verbosity.

**Comment by MaineC** [comment]
I'm not quite sure what the benefit of specifying a template per request would be. Do you have an example use case for clarification?

**Comment by clintongormley** [comment]
I was thinking about comparing different templates, but eg with the same parameters.  Thinking about it again I think what you're doing here makes more sense.

**Comment by MaineC** [comment]
> I was thinking about comparing different templates, but eg with the same parameters.

That makes a lot of sense to me. IIRC in some earlier iteration of the API we even had support for specifying multiple templates at once.

I'm wondering if it would be fine for users to be required to send one rank-eval request per template they want to test. Given the above API proposal those requests would only differ in the template section, so all the rest could be automatically generated/ copy-paste-ed/...

**Comment by MaineC** [comment]
Fixed with #20374
