### ISSUE TITLE
Add support for "missing" parameter to the terms aggregation "order"

### ISSUE THREAD

**Issue by golubev** [elastic/elasticsearch#20237]
It would be nice to be able to use `missing` parameter when ordering a terms aggregation - just [like the  `missing` parameter in the `sort`](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-request-sort.html#_missing_values).

My use case: I want to order my buckets by the `min_price` for each bucket
```json
{
    "query": {
        "bool": {
            "filter": [
                "<some filters>"
            ]
        }
    },
    "size": 0,
    "aggregations": {
        "announcements": {
            "terms": {
                "field": "ann_id",
                "order": [
                    {
                        "min_price": {
                            "order": "asc",
                            "missing": "_last"
                        }
                    }
                ],
                "size": 30
            },
            "aggregations": {
                "min_price": {"min": {"field": "price"}},
                "<some other aggregations>"
            }
        }
    }
}
````
But when I am trying to do that, I get:
```
Unexpected token START_OBJECT for [order] in [announcements].
```
Some announcements (buckets aggregated by `ann_id`) can have no prices in the bucket's documents, so `min_price` aggregation when calculated will be equal to `null`.

Furthermore, when I choose in the example above to order buckets this way:
```json
    "order": [
        {"min_price": "asc"}
    ],
```
buckets having `null` `min_price` are last.
But when I change it to be:
```json
    "order": [
        {"min_price": "desc"}
    ],
```
buckets having `null` `min_price` are first. And that is really strange to me.

It would be also interesting that when I am using `max_price` (`max` subaggregation) the behavior with nulls changes vice versa.

**Comment by jpountz** [comment]
Discussed in FixitFriday. Sorting terms aggregations by sub aggregations is known to have pitfalls (#17588) so we are reluctant to make it more powerful. There might be workarounds in some cases eg. by configuring a missing value on the `min` aggregation.

**Comment by golubev** [comment]
Thanks, @jpountz! Succeeded by configuring `missing` value for the `min` aggregation and changing application logic a bit:
- to order by `min` aggregation only in `asc` direction;
- when it's required to order in the `desc` direction - order by `max` subaggregation.
