### ISSUE TITLE
handling of json payloads with duplicate field names

### ISSUE THREAD

**Issue by djschny** [elastic/elasticsearch#20241]
**Elasticsearch version**: 5.0.0-alpha5

**Plugins installed**: []

**JVM version**: 

**OS version**:

**Description of the problem including expected versus actual behavior**:

Considering the following request/response:

```
curl -XPUT "http://localhost:9200/test" -d'
{
  "settings": {
    "number_of_shards": 4,
    "number_of_shards": 1
  }
}'
```

```
curl "http://localhost:9200/test?pretty"
{
  "test" : {
    "aliases" : { },
    "mappings" : { },
    "settings" : {
      "index" : {
        "creation_date" : "1472515277804",
        "number_of_shards" : "1",
        "number_of_replicas" : "1",
        "uuid" : "mXl843bTQzyYl1ImeTqKaQ",
        "version" : {
          "created" : "5000005"
        }
      }
    }
  }
}
```

Elasticsearch accepts the request and Elasticsearch accepts the request with a "last one wins" rule.

If this command is placed in Kibana Console, then it shows as an error. For example:
<img width="341" alt="screen shot 2016-08-30 at 11 35 13 am" src="https://cloud.githubusercontent.com/assets/129643/18109074/4244db3c-6ec4-11e6-97a1-2aef153ac97a.png">

The JSON RFC says "The names within an object SHOULD be unique". Should Elasticsearch reject a request like this? Or should Sense be adjusted to not show this as an error?

**Comment by dakrone** [comment]
I *think* I recall us discussing it and enabling the detection on Jackson was a non-trivial amount of overhead for JSON parsing, but maybe someone else knows the history more.

Related: https://github.com/elastic/elasticsearch/issues/19614

**Comment by javanna** [comment]
I think that it's very helpful if the kibana console shows this as an error, regardless of what elasticsearch does with this request. We said we would try to see whether we can start rejecting such requests but we first have to measure how big of an impact it is, and/or maybe explore doing it only for some apis where performance matters less. Closing in favour of #19614 .
