### ISSUE TITLE
5.0.0-alpha5 - Strange _cat/indices output

### ISSUE THREAD

**Issue by ceeeekay** [elastic/elasticsearch#20247]
**Elasticsearch version**: 5.0.0-alpha5
**Plugins installed**: none
**JVM version**: openjdk-8-jre-headless:amd64
**OS version**: Ubuntu 14.04.4

When checking _cat/indices, some indices were listed without doc and store.size stats. At first glance these appear the same as closed indices, but health and stats columns show green/open.

```
health status index                          uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   kelp-client-metrics-2016.08.29 ye3zduCbQFacKFZ7ylKr6w   2   0      34556            0      8.3mb          8.3mb
green  open   kelp-client-metrics-2016.08.13 DvjNn6cBQqSzA2a8VB_qQA   2   0
```

Closing and opening the affected indices resolves the issue, as does restarting the data node.
Debug logs on the master show nothing. Unfortunately the data node was restarted before I had a chance to enable debug logging for it. Info level logs on the data node showed nothing.

Index info from the API appears to be normal for the affected indices - Cerebro was able to show the doc count and index size while it was missing from _cat output.

**Steps to reproduce**:
 Unsure how it got like this - unable to reproduce, sorry.

**Comment by colings86** [comment]
Are you still seeing this issue on you Elasticsearch cluster? If so, are you now able to reproduce the bug?

**Comment by ceeeekay** [comment]
Hi there,

No sign of this reoccurring since opening this issue. Currently running 5.2.0.

**Comment by jasontedor** [comment]
Thanks for reporting back. Please feel free to reopen if this reproduces and you can provide more information.
