### ISSUE TITLE
standard analyzer bug when processing "number,number" ? [2.3.2]

### ISSUE THREAD

**Issue by childe** [elastic/elasticsearch#20246]
**Elasticsearch version**: 2.3.2

**Plugins installed**: []

**JVM version**: sun 1.8.0_77

**OS version**: CentOS release 6.4 (Final)

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

1. create index

    ```
    POST testindex
    {
       "settings": {
          "index": {
             "number_of_shards": "1",
             "number_of_replicas": "0"
          }
       },
       "mappings": {
          "logs": {
             "dynamic": "false",
             "_all": {
                "enabled": false
             },
             "properties": {
                "snlist": {
                   "type": "string",
                   "analyzer": "standard"
                }
             }
          }
       }
    }
    ```

2. test analyzer with _analyze api

    ```
    GET_analyze?analyzer=standard&text=106614,106607'

    {
       "tokens": [
          {
             "token": "106614",
             "start_offset": 0,
             "end_offset": 6,
             "type": "<NUM>",
             "position": 0
          },
          {
             "token": "106607",
             "start_offset": 7,
             "end_offset": 13,
             "type": "<NUM>",
             "position": 1
          }
       ]
    }
    ```

3. post one document to testindex
    ```
    POST testindex/logs
    {
       "snlist": "106614,106607"
    }
    ```

4. terms aggregation

    ```
    POST testindex/logs/_search
    {
       "size": 0,
       "aggs": {
          "snlist": {
             "terms": {
                "field": "snlist"
             }
          }
       }
    }

   {
   "took": 8,
   "timed_out": false,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 0,
      "hits": []
   },
   "aggregations": {
      "snlist": {
         "doc_count_error_upper_bound": 0,
         "sum_other_doc_count": 0,
         "buckets": [
            {
               "key": "106614,106607",
               "doc_count": 1
            }
         ]
      }
   }
   } 
    ```

**Comment by jpountz** [comment]
This is actually a "feature" of the _analyze API which splits the input text on commas, so it sees your input text as a two-values array: ["106614", "106607"]. The `standard` analyzer analyzes `106614,106607` down to a single token, is the aggs suggest.

**Comment by childe** [comment]
@jpountz I do not think _analyze API always splits input on commas. You can use any analyzer in _analyze API and they will give different results. Both my test and the example in document (https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-analyze.html
) proves this.

I am curious why the standard analyzer behaves differently between the 2 API. 
And I think _analyze API should give same results(tokens) with that in aggs API. Am i right?

**Comment by jpountz** [comment]
It does split on commas, try to run this for instance:

```
GET _analyze?analyzer=keyword&text=ab cd,ef gh
```

It returns two tokens in spite of the fact that the keyword analyzer was used.

**Comment by clintongormley** [comment]
Hmmm I don't like this feature much, although it is consistent with other multi-valued query string params.  I'm tempted to remove the comma splitting.  Multiple values for `text` can always be provided in the request body.

**Comment by childe** [comment]
@jpountz @clintongormley  Thanks so much! 
I finally understand what you mean :)  My poor English!

**Comment by jpountz** [comment]
No worries. However I'm tempted to keep this one open. Like @clintongormley suggested, maybe we should stop splitting on commas.

**Comment by johtani** [comment]
@clintongormley @jpountz how about deprecating request parameters?

**Comment by clintongormley** [comment]
@johtani good idea - will make things simpler.  Also deprecate plain text bodies at the same time - should be JSON only

**Comment by johtani** [comment]
@clintongormley deprecating in v5.0 and remove in v5.1 is OK? or deprecating v2.4.1?

**Comment by clintongormley** [comment]
@johtani deprecate in 5.0 (including deprecation logging), and remove in 6.0

**Comment by johtani** [comment]
Deprecating in 5.x done by #20686
