### ISSUE TITLE
Artifact IDs under org.elasticsearch.client too generic.

### ISSUE THREAD

**Issue by ctrimble** [elastic/elasticsearch#20248]
The Maven Artifact IDs under [org.elasticsearch.client](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.elasticsearch.client%22) are very generic and could cause naming conflicts.  Most other elasticsearch artifacts are prefixed with `elasticsearch-`.  These artifacts should follow the same practice.

Version: 5.0.0-alpha5

This issue is related to this [discussion](https://discuss.elastic.co/t/new-client-artifacts-naming-and-packaging-problematic/59228).

**Comment by javanna** [comment]
@rjernst thoughts?

**Comment by dadoonet** [comment]
I think we should do it for any library which could be used outside Elasticsearch nodes.

So +1 here.

**Comment by rjernst** [comment]
I don't know about prefixing with `elasticsearch-`, but I do think they could be a little more verbose. Perhaps `rest-client`, `rest-client-sniffer`, and `transport-client` would be a bit better? +1 to making whatever change is agreed on for the next prerelease.

**Comment by ctrimble** [comment]
@rjernst I know it may seem like adding `elasticsearch-` is redundant, since the name is in the artifact's `groupId`.  Unfortunately, `groupId` does not appear in the final artifact's name, so it is good practice to make the `artifactId` unique enough that you are not going to get conflicts when it is consumed.  Your suggestions will result in jar names like `rest-client.jar`, `rest-client-sniffer.jar`, and `transport-client.jar`.  Those could easily cause issues when building an application that connects to multiple rest APIs.

**Comment by rjernst** [comment]
I don't have any strong opinion one way or another. If we are more explicit in the artifact ids, then I don't see why we need more than one groupid (`org.elasticsearch`).

**Comment by ctrimble** [comment]
Although I did not want to open up a discussion on `groupIds`, I totally agree with @rjernst 's point.  `groupIds` function more as a namespace mechanism for Maven Central and having more than one in a project adds no real value.

**Comment by clintongormley** [comment]
I've put an `adoptme` label on this because it sounds like there is consensus (although I'd like to hear from @dadoonet and @javanna as well).

it's probably too late in the cycle to make this change now, but if we decide to do it, we could target 6.0

**Comment by dadoonet** [comment]
@clintongormley Not obvious but I already added my vote (thumb up). I'm totally +1 for that.
