### ISSUE TITLE
ByteSizeValue supports values that can't be serialized

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#20262]
I noticed that `ByteSizeValue` allows any input value, including negative values.
 When it comes to serializing it though, we use `writeVLong` which starts with an assertion `assert i >= 0;`. I suspect this is the reason why in some cases we do not use `ByteSizeValue` instance but plain long values instead, in places like `OsStats` (because we default to `-1` which cannot be serialized) and we end up creating a new `ByteSizeValue` instance on demand for each get call.

Should we change the way we serialize it or shall we introduce some validation at construction time in `ByteSizeValue`?

**Comment by nik9000** [comment]
I think either? If we write with vlong we really should validate the values are >= 0. We default to `-1` in `OsStats`, not 0. Maybe we should just default to a null `TimeValue`?

**Comment by nik9000** [comment]
I do think it is a bit weird to allow negative bytes, though not super weird. Think of the answer to "how many bytes would be left free after I assigned this shard to my node with a full disk?" It'd be a negative number in bytes....

**Comment by javanna** [comment]
> We default to -1 in OsStats, not 0.

in #20255 we will also have potentially `0` as a default for cumulative memory values. I think that -1 should rather be null, and we should use `writeOptionalWriteable` for that. Not sure where negative values may actually make sense, but accepting something that we won't serialize seems really wrong, so I am leaning towards changing serialization here first of all (at least 0 does make sense for a byte size value).

**Comment by nik9000** [comment]
vlong can write 0 though, so that is ok?

**Comment by javanna** [comment]
> vlong can write 0 though, so that is ok?

yes, forget about that bit... >= 0 is not the same as > 0 :) sorry for the noise there.

**Comment by tlrx** [comment]
Duplicate of #19809

ByteSizeValue as well as TimeValue need more love as well as the whole Stats stuff. I plan to work on this as soon as possible and @abeyad proposed his help too

**Comment by javanna** [comment]
thanks for pointing that out. although #19809 seems broader than this one it definitely covers this issue, closing in favour of #19809 .  Let's just not forget that once we fix all this we can probably stop creating ByteSizeValue instances on demand to work around the fact that -1 cannot be serialized.
