### ISSUE TITLE
mapper.allow_dots_in_name is node level configuration

### ISSUE THREAD

**Issue by djschny** [elastic/elasticsearch#20272]
**Elasticsearch version**: 2.4

**Plugins installed**: []

**JVM version**: 1.8.0_92-b14

**OS version**: Mac 10.11.5

**Description of the problem including expected versus actual behavior**:
The setting of `mapper.allow_dots_in_name` is a node level configuration setting as opposed to a cluster/dynamic setting. However I'm failing to think of a reason why it would be an advantage to have the value set inconsistent across nodes. This is a request to have it made a cluster level and dynamic setting.

**Comment by jpountz** [comment]
The motivation against making it a cluster setting is that it exposes you to a lot of unknowns and thus setting this option should not be just "allowing dots in fields names seems legit, let's do that". Dots in field names in 5.0 work well, I am not saying there are no bugs, but at least we know how we can make it work. On the other hand on 2.4, dots in field names are really a hack and this escape hatch is only a last resort option for users who cannot make their way from 1.7 because of the dots-in-fieldnames restriction that 2.0 introduced.

**Comment by djschny** [comment]
> The motivation against making it a cluster setting is that it exposes you to a lot of unknowns and thus setting this option should not be just "allowing dots in fields names seems legit, let's do that".

I do not understand how it being a System property that needs to be make any of the unknowns different or worse. I person has to make a conscious decision to change this setting. They have to look it up and find out what the setting is and where to do that.

However it is trappy with the current way because a user could get into a situation where the setting was not set on a subset of nodes and then is experiencing sporadic errors/behavior. Historically there has been a push to try to protect against inconsistent cluster configuration at the node level, so not sure why we are going against that here.

**Comment by s1monw** [comment]
> I do not understand how it being a System property that needs to be make any of the unknowns different or worse. I person has to make a conscious decision to change this setting. They have to look it up and find out what the setting is and where to do that.

it's the fact that its different from anything else that this is a workaround and can cause serious issues with your mapping. The fact that we won't do any harm if the setting is not provided is why I think this is not a problem. it's an upgrade path for affected users. users that didn't have that problem should really not have an easy time to enable it.

**Comment by colings86** [comment]
Closing as it was intentional the setting was made this way
