### ISSUE TITLE
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (default) on project parent: Resources archive cannot be found. Could not find artifact org.elasticsearch:rest-api-spec:jar:2.3.5-SNAPSHOT in oss-snapshots (https://oss.sonatype.org/content/repositories/snapshots/)    

### ISSUE THREAD

**Issue by srikanthsk** [elastic/elasticsearch#20275]
**Elasticsearch version**:

**Plugins installed**: []

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by srikanthsk** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/rest-api-spec/

ES-V-2.3.5 is not available in the repository

how do i fix this..help me out
any other way to build elastisearch source code?

**Comment by dadoonet** [comment]
2.3.5 has been released: https://www.elastic.co/downloads/past-releases/elasticsearch-2-3-5

That's why you can't find it as a snapshot.

Please ask your questions on discuss.elastic.co instead.
