### ISSUE TITLE
change exist field from analyed to not_analyzed

### ISSUE THREAD

**Issue by JoyceYy** [elastic/elasticsearch#20273]
**Elasticsearch version**:1.73

I want to change exist field from analyed to not_analyzed,is it possible?I try to modified it,but got exception as follow:

`{"error":"MergeMappingException[Merge failed with failures {[mapper [referer] has different index values, mapper [referer] has different tokenize values, mapper [referer] has different index_analyzer]}]","status":400}
`

**Comment by jpountz** [comment]
This cannot be done on an existing index, you would need to reindex.
