### ISSUE TITLE
TRA waits when an index doesn't exist but fails immediately when shard is not found

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#20279]
TransportReplicationAction currently has an inconsistency in how it deals with requests that refer to things that don't exist (which is different than not available).

1) When an index is not found in the cluster state, we go into a retry loop where we wait for the index to appear.
2) When a request comes in for a shard that doesn't exists (i.e., the shard id is higher than the number of shards ) we fail immediately - as it will never appear.

This is surprising and we should fix it.

In my opinion we should:
1) Require ReplicationRequests to have a complete ShardId when they get to the reroute phase in TRA.
2) Fail immediately when that shard id can not be resolved.
3) Change TransportIndexAction and similar write actions to resolve the incoming requests and set their proper shard id (with index uuid). If they need to create the index, they can go ahead, but then it's up to them to also wait until the current (data) node, knows about the index that was just created. We can have a shared utility method for this on `AutoCreateIndex`.

**Comment by bleskes** [comment]
one more note - when converting an index name to an `Index` instances, we always have to wait in the case the index is not there. The reason is that, sadly,  a create index operation can finish successfully without all nodes knowing about it. Since we can then accept a follow up indexing request on arbitrary nodes, which should also give a chance for lagging cluster state to arrive. Practically this means that TransportIndexAction and friends need to wait also when they don't create a missing index . I expect this to be a common pattern when we move all index resolving to the rest layer (once the transport client has been removed, so there is time...)

**Comment by ywelsch** [comment]
> Require ReplicationRequests to have a complete ShardId when they get to the reroute phase in TRA.

Addressed by #40424

> Fail immediately when that shard id can not be resolved.

There's no resolving anymore of the shard id in TRA

> Change TransportIndexAction and similar write actions to resolve the incoming requests and set their proper shard id (with index uuid). If they need to create the index, they can go ahead, but then it's up to them to also wait until the current (data) node, knows about the index that was just created. We can have a shared utility method for this on AutoCreateIndex

This is taken care of by TransportBulkAction now.

Remaining points addressed by #49647
