### ISSUE TITLE
Allow plugins to register sub-Commands of elasticsearch-plugin

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#20286]
Right now Elasticsearch plugins that want ship scripts have to deal with locating the configuration of Elasticsearch so they can run properly. On the other hand in 5.0 Elasticsearch will ship the `elasticsearch-plugin` command that already does this. If we could allow plugins to register `subcommands` of `elasticsearch-plugin` then they wouldn't need to duplicate all that effort.

We certainly could improve support for plugins shipping their own shell and batch scripts but I'm not really a fan of writing more and more and more batch scripts, most of which just figure out where the Elasticsearch code is and then start java.

**Comment by nik9000** [comment]
The neat thing about doing this is that it'd let us nuke the funny bin handling that we do in the plugin installer.

**Comment by imotov** [comment]
I think this is a very elegant solution for the problem. The users script in x-pack is 90% copy of the code of previous version of the elasticsearch's plugin script.

**Comment by dakrone** [comment]
This sounds interesting but how would this work for non-plugin scripts? If we are going to make them sub-commands of a script, why not make them part of the `elasticsearch` script rather than the `elasticsearch-plugin` script?

**Comment by dakrone** [comment]
And actually, why not make `plugin` a subcommand of the `elasticsearch` script altogether so there is only a single script that has to be managed/maintained?

**Comment by nik9000** [comment]
> And actually, why not make plugin a subcommand of the elasticsearch script altogether so there is only a single script that has to be managed/maintained?

I have no problem with that. I just proposed adding them to `elasticsearch-plugin` because it is a script we already have and the commands come from plugins. It is a fairly week argument, I know.

**Comment by dakrone** [comment]
> the commands come from plugins

Not all the commands come from plugins, now that we have the translog truncate tool

**Comment by dakrone** [comment]
Another thing that I am unsure about is security permissions, do the `bin/elasticsearch` and `bin/elasticsearch-plugin` classes have different security allowances?

**Comment by nik9000** [comment]
The required permissions would be all about what commands you execute. To install or remove plugins you need to run as root (in deb and rpm installations) because we couldn't come up with a way to make those directories non-writeable to the Elasticsearch user. To run elasticsearch you'd need to be the elasticsearch user (in deb and rpm installations). I guess translog tool needs to be the ES user too? Otherwise I think you can be anyone that can read elasticsearch.

**Comment by nik9000** [comment]
> I have no problem with that. I just proposed adding them to elasticsearch-plugin because it is a script we already have and the commands come from plugins. It is a fairly week argument, I know.

Another argument for doing it this way is to limit the scope of this particular change. I've marked this as both breaking and blocking 5.0.0 so I want to be somewhat careful about committing to a big rework even if it is a better idea.

**Comment by nik9000** [comment]
Ok - this's been open for a bit and only positive comments - maybe @clintongormley can have a look? I've marked it as blocking for 5.0.0 because it'd be nice to have the cleanup in case we write any more scripts in the 5.x branch, but maybe it should be in 6.x instead? I'm not really sure.

**Comment by jasontedor** [comment]
I don't think we should do this, at least not for 5.x, it's too big of a change and there are ramifications to think through carefully:
 - what if two plugins try to register the same command
 - we will probably end up with a support burden for third-party plugins subcommands
 - the plugin commands do not run with the Java security manager but it should if we are going to start talking about third-party plugins registering subcommands

I think for the purpose of the problem that we are trying to solve here we should just make something like an `elasticsearch-env.sh` script that other plugins scripts can source to properly setup the environment.

**Comment by nik9000** [comment]
`elasticsearch-env` solves the problem as well but I didn't like that solution as much because it means yet more infrastructure that diverges on Windows and Linux.

Your points about not doing it right now are valid. I'm happy to switch it to 6.0. If we go with `elasticsearch-env` we can ship that with an earlier version of Elasticsearch without a problem.

Security in particular is a bit of a mixed bag with plugin scripts. Plenty of them must be run as root so they can make changes to the filesystem in directories that Elasticsearch doesn't have write permissions on. Others can run as anyone that can read the Elasticsearch jar files. How all of that plays with the java security manager is a mystery to me.

**Comment by dakrone** [comment]
I agree with not doing this for 5.0, I think this is far too large a change to introduce this late. I also think the `elasticsearch-env` solution works totally well too

**Comment by rjernst** [comment]
I don't think we should do this, even for 6.0. It would require an entirely new api for a plugin to define these commands, but we should not be promoting scripts for anything! Scripts are something that should be one off. They only operate on a single node, and plugins should strive to add apis for their maintenance. A shared shell script to include would be an acceptable compromise IMO.

**Comment by clintongormley** [comment]
I agree with @rjernst and @jasontedor's comments.  It seems unnatural to try to force all scripts into the `elasticsearch-plugin` command.  The `elasticsearch-env` include is by far my preference.

**Comment by clintongormley** [comment]
Fix it Friday agrees with the `elasticsearch-env` approach.  I think this can be closed.
