### ISSUE TITLE
Doc[‘field_name’] returns unexpected big number

### ISSUE THREAD

**Issue by mehmetonler** [elastic/elasticsearch#20282]
Hey, 
I am using ES 1.7.  I run the following query and I expect to get 15 which is current popularity for it. but it returns 4607464916994563600.

```
    POST /myIndex/en/_search
    {
      "size": 1,
      "script_fields": {
        "toTestField": {
          "script": "doc['popularity'].value"
        }
      }
    }
```

Result:

```
    {
      "took": 87,
      "timed_out": false,
      "_shards": {
        "total": 2,
        "successful": 2,
        "failed": 0
      },
      "hits": {
        "total": 3059534,
        "max_score": 1,
        "hits": [
          {
            "_index": "myIndex",
            "_type": "en",
            "_id": "12345",
            "_score": 1,
            "fields": {
              "toTestField": [
                4607464916994563600
              ]
            }
          }
        ]
      }
    }
```

This occurs on one of my the production machine. The others work just fine. Because of this bug, search results get really weird. Any ideas, why this is happening?

**Comment by jpountz** [comment]
This is a known 1.7 issue: the popularity field was dynamically mapped as a double on one shard and as a long on another shard. Then shards moved around and long bits got interpreted as doubles or vice-versa. This is fixed as of 2.0. If you cannot upgrade, the only workaround is to configure mappings explicitly.

**Comment by mehmetonler** [comment]
how can I configure mappings explicitly, for existing data

**Comment by jpountz** [comment]
It cannot be fixed after mappings have been created, the workaround I indicated only works for newly created indices. In short, you should avoid relying on dynamic mappings ot 1.7.
