### ISSUE TITLE
Remove `token_filter` in _analyze API

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#20283]
When you define an analyzer, we only support `filter` instead of `token_filter`. See https://www.elastic.co/guide/en/elasticsearch/reference/master/analysis-custom-analyzer.html

But the `_analyze` API still supports both forms. I suggest that we remove support for `token_filter` in `_analyze` API.

See also #17843.

**Comment by dadoonet** [comment]
@johtani WDYT?

**Comment by johtani** [comment]
+1

**Comment by s1monw** [comment]
++
