### ISSUE TITLE
Global aggregation and Nested & Children

### ISSUE THREAD

**Issue by tchiotludo** [elastic/elasticsearch#20281]
I'm working on a faceted search.
I want to return with aggregation the number of facets for all filters.
If the user choose 1 filter, I want to display all others possible value.

The possible way is see on the doc is : 

- [Scoping Aggregations](https://www.elastic.co/guide/en/elasticsearch/guide/current/_scoping_aggregations.html)
- [Filter Bucket](https://www.elastic.co/guide/en/elasticsearch/guide/current/_filter_bucket.html)

It seems easier for me to use the global aggregation to achieve my goal.
The document contains children property `article` and article contains nested document `kind`

Here is the query : 
```json

{
  "query":{
    "bool":{
      "must":[
        {
          "terms":{
            "organization_address.city.raw":[
              "Lille"
            ]
          }
        },
        {
          "has_child":{
            "type":"article",
            "query":{
              "constant_score":{
                "filter":{
                  "terms":{
                    "article.article_kind.kind_id":[
                      2
                    ]
                  }
                }
              }
            }
          }
        }
      ]
    }
  },
  "aggregations":{
    "article":{
      "children":{
        "type":"article"
      },
      "aggregations":{
        "kind":{
          "global":{},
          "aggregations":{
            "kind":{
              "nested":{
                "path":"article_kind"
              },
              "aggregations":{
                "kind_id":{
                  "terms":{
                    "field":"article_kind.kind_id"
                  },
                  "aggregations":{
                    "kind_name":{
                      "terms":{
                        "field":"article_kind.kind_name.fr.raw"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "city":{
      "global":{},
      "aggregations":{
        "city":{
          "terms":{
            "field":"organization_address.city.raw"
          }
        }
      }
    }
  }
}
```

and elasticsearch return :
 
`Aggregation [article] cannot have a global sub-aggregation [kind]. Global aggregations can only be defined as top level aggregations`

Expected as the document [say](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-global-aggregation.html) : 

Global aggregators can only be placed as top level aggregators (it makes no sense to embed a global aggregator within another bucket aggregator)

But does the nested & children document is not a relevant use case ?

I can use Filtering bucket in my case, but it need to be combined with Post Filter (that does not filter aggregation) and have 2 distinct aggregation, 1 for the all the document and 1 with all the Filtering bucket from query applied to current field aggregation.

Tell me if I'm wrong and there is a better way to handle this use case.

**Comment by clintongormley** [comment]
Hi @tchiotludo 

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by tchiotludo** [comment]
Hi @clintongormley, 

It's a feature request :smile: 
It's just that I'm not sure at 100 % that the global aggregation is not supported with children & nested, so I write the issue like a question.

**Comment by HarveyWilliams** [comment]
I agree that this doesn't seem to be a current feature and it would be nice if it was added. Otherwise we can still use Post Filter to get around this.
