### ISSUE TITLE
Two fields, type Long, behaving differently on query aggregation

### ISSUE THREAD

**Issue by jgminer** [elastic/elasticsearch#20289]
**Elasticsearch version**: 2.3.5

**Plugins installed**: [head, kopf, cloud_aws, marvel, license]

**JVM version**: 1.8.0_51

**OS version**: CentOS 6.6

**Description of the problem including expected versus actual behavior**:

When querying two different fields, both with identical type "Long" (based off of the _mapping API endpoint), one returns all zeros, the other returns the proper decimal.

The only difference with the content of these fields is field1 has decimal n where 0<=n<=1 whereas field2 only has 0<=n<1.

I'm wondering if Elasticsearch is rounding treating these aggregations differently for some reason given their content and the fact that field1 has entries where it is 1 exactly and not a decimal. This doesn't seem right as they are both mapped to the same analyzed type - Long.

**Steps to reproduce**:
Raw Kibana Query, same for each field except for field queried:
```
{
  "size": 0,
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "query": "someQuery",
          "analyze_wildcard": true
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gte": 1472753632067,
                  "lte": 1472753932067,
                  "format": "epoch_millis"
                }
              }
            }
          ],
          "must_not": []
        }
      }
    }
  },
  "highlight": {
    "pre_tags": [
      "@kibana-highlighted-field@"
    ],
    "post_tags": [
      "@/kibana-highlighted-field@"
    ],
    "fields": {
      "*": {}
    },
    "require_field_match": false,
    "fragment_size": 2147483647
  },
  "aggs": {
    "2": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "1m",
        "time_zone": "America/Somewhere",
        "min_doc_count": 1,
        "extended_bounds": {
          "min": 1472753632066,
          "max": 1472753932066
        }
      },
      "aggs": {
        "1": {
          "avg": {
            "field": "field1"
          }
        }
      }
    }
  }
}

```
Field 1 Results:
```
{
  "took": 3,
  "timed_out": false,
  "_shards": {
    "total": 9,
    "successful": 9,
    "failed": 0
  },
  "hits": {
    "total": 8337,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "2": {
      "buckets": [
        {
          "1": {
            "value": 0.03139013452914798
          },
          "key_as_string": "2016-09-01T13:13:00.000-05:00",
          "key": 1472753580000,
          "doc_count": 223
        },

        ...etc
      ]
    }
  }
}
```
Field2 Results:
```
{
  "took": 12,
  "timed_out": false,
  "_shards": {
    "total": 9,
    "successful": 9,
    "failed": 0
  },
  "hits": {
    "total": 8318,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "2": {
      "buckets": [
        {
          "1": {
            "value": 0
          },
          "key_as_string": "2016-09-01T13:22:00.000-05:00",
          "key": 1472754120000,
          "doc_count": 1559
        },
        ...etc
      ]
    }
  }
}
```

So the second result is an average of zero, despite Field2 for that query containing 0, 0.1, 0.4, etc.

Any help sincerely appreciated.

**Comment by dakrone** [comment]
Can you provide the documents this aggregation is running over so we can try to reproduce?

> field1 has decimal n where 0<=n<=1 whereas field2 only has 0<=n<1

This doesn't really make sense to me, you said that the field is of type `long`, but you are only sending values between 0 and 1? This seems like something that should be a `double` or `float`?

**Comment by jgminer** [comment]
I cannot provide the documents exactly as written, however I will try to explain better what I think happened.

When these documents were first created, these fields each would have had the value '0', leading to Elasticsearch assigning the analyzed fields as `long`. However, later on the documents started seeing values that were decimals for the same index, but they were stuck with the old analyzed type. So I think it makes sense why both fields are of type `long`.

What doesn't make sense is why the aggregation would return so differently on essentially the same values. I'm thinking our best bet may be to have Logstash (the source) assign a template for this index that assigns a new field as non-analyzed - we've done this in the past, but I'm trying to understand the typed-ness of Elasticsearch and avoid a hacky solution.

**Comment by clintongormley** [comment]
This is easily explained with the following example:

    PUT t/t/1
    {
      "one": 0,
      "two": 0
    }
    
    PUT t/t/2
    {
      "one": 1,
      "two": 0.9
    }
    
    PUT t/t/3
    {
      "one": 0.5,
      "two": 0.5
    }
    
    GET t/_search
    {
      "docvalue_fields": [
        "one",
        "two"
      ],
      "aggs": {
        "one": {
          "avg": {
            "field": "one"
          }
        },
        "two": {
          "avg": {
            "field": "two"
          }
        }
      }
    }

which returns:

    {
      "took": 2,
      "timed_out": false,
      "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
      },
      "hits": {
        "total": 3,
        "max_score": 1,
        "hits": [
          {
            "_index": "t",
            "_type": "t",
            "_id": "2",
            "_score": 1,
            "_source": {
              "one": 1,
              "two": 0.9
            },
            "fields": {
              "two": [
                0
              ],
              "one": [
                1
              ]
            }
          },
          {
            "_index": "t",
            "_type": "t",
            "_id": "1",
            "_score": 1,
            "_source": {
              "one": 1,
              "two": 0.9
            },
            "fields": {
              "two": [
                0
              ],
              "one": [
                1
              ]
            }
          },
          {
            "_index": "t",
            "_type": "t",
            "_id": "3",
            "_score": 1,
            "_source": {
              "one": 0.5,
              "two": 0.5
            },
            "fields": {
              "two": [
                0
              ],
              "one": [
                0
              ]
            }
          }
        ]
      },
      "aggregations": {
        "one": {
          "value": 0.6666666666666666
        },
        "two": {
          "value": 0
        }
      }
    }
    
`one` and `two` are both longs, so any decimal part is discarded. `one` contains values 0 <= n <= 1, which results in lots of zeroes and the occasional 1.  `two` contains values 0 <= n < 1, which results in all zeroes.

**Comment by jgminer** [comment]
@clintongormley Thanks for the clear, concise explanation and example. That makes sense given the type `long`.
