### ISSUE TITLE
Scan scrolling should return results in the initial response

### ISSUE THREAD

**Issue by erickt** [elastic/elasticsearch#2028]
Scrolling with the search_type scan have a different initial response compared with scrolling without scan. Scans do not return documents in the initial response, but regular scrolling does. This can be a bit confusing for end users. According to @kimchy, this difference is no longer required by the implementation, but is maintained for backwards compatibility. It would be nice if at some point in the future we could do away with this difference.

**Comment by kul** [comment]
:+1:  #9380

**Comment by jasontedor** [comment]
The scan search type will be deprecated by #12994 in favor of a scroll search ordered by `_doc` (optimized in #12983). This deprecation obviates the need to address this issue.
