### ISSUE TITLE
bootstrap mlockall | memory_lock bug?

### ISSUE THREAD

**Issue by dropje86** [elastic/elasticsearch#20295]
**Elasticsearch version**: v2.4.0

**Plugins installed**: [marvel]

**JVM version**: 1.8.0_72

**OS version**: Ubuntu Trusty

**Description of the problem including expected versus actual behavior**:
When I start an Elasticsearch node with the bootstrap.mlockall: true option it starts swapping like crazy within 30 seconds and eventually dies. When I use bootstrap.memory_lock: true Elastic keeps running as expected. It seems there is something fishy going on with the deprecation setting not working although I can't pinpoint why that is.

**Steps to reproduce**:
 1. Using ES 2.4.0 set bootstrap.mlockall: true
 2. Set ES_HEAP_SIZE to a big chunk of the total available memory
 2. Generate some load and wait 

**Provide logs (if relevant)**: Nothing is logged and it's not the OOM killer that was responsible for the process disappearing. Elastic just dies without notice.

**Comment by jasontedor** [comment]
Duplicates #17605

**Comment by dropje86** [comment]
@jasontedor thanks for the quick reply. Evidence of swapping was coming from `top`. However, I spoke too soon. This, after some time, also occurred with memory_lock set. Sorry for the inconvenience, I'll close this one.

**Comment by jasontedor** [comment]
Okay, please see #17605 regarding why Elasticsearch can still swap even with memlock in use.
