### ISSUE TITLE
Documentation for field_masking_span query 

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch#20293]
It looks like [`field_masking_span` query](https://github.com/elastic/elasticsearch/issues/471) has been supported for a long time but [remains undocumented](https://www.elastic.co/guide/en/elasticsearch/reference/master/span-queries.html). 

It should be included in the documentation for the latest 1.x, 2.x and 5.x releases.

**Comment by russcam** [comment]
See https://github.com/elastic/elasticsearch-net/pull/2231

**Comment by clintongormley** [comment]
I'm actually wondering if we should remove the `field_masking_span` query, which seems like it is a  poor man's `nested`, but relying on term positions in different fields (see https://lucene.apache.org/core/2_9_4/api/core/org/apache/lucene/search/spans/FieldMaskingSpanQuery.html)

**Comment by yevhen** [comment]
@clintongormley could you please elaborate more on this? We are using 2 separate fields to analyze the same content with morphology and exact. The posistions are completely equal in both fields so we can safely use FieldMaskngQuery, and we don't need scoring at this point. How would `nested` help us in this case? Thanks!

**Comment by clintongormley** [comment]
@yevhen ok i may have misunderstood the use cases.  my understanding was that it was a workaround for multiple corresponding values in each field, eg:

    {
      "users": [ 
       { "first_name": "john", "last_name": "smith" },
       { "first_name": "jack", "last_name": "white" },
      ]
    }

which ends up being indexed as:

    users.first_name: john, jack
    users.last_name: smith, white

Nested solves this use case in a much better way.  

If `field_masking_span` query has other use cases, then I'm happy to leave it there.

Given that you're using it, any chance you could send a PR adding the docs? (as I clearly don't understand the use case properly)

**Comment by yevhen** [comment]
@clintongormley sure, no problem. Where to add docs?

**Comment by yevhen** [comment]
@clintongormley ping :)

**Comment by russcam** [comment]
@yevhen The documentation is built with the asciidoc build process in the [docs repo](https://github.com/elastic/docs). The source for the `master` branch of the elasticsearch docs is in 
https://github.com/elastic/elasticsearch/tree/master/docs/reference, with the span queries living in https://github.com/elastic/elasticsearch/tree/master/docs/reference/query-dsl.

Once an asciidoc file is added for `field_masking_span` in the query-dsl directory, a link to it should be added to the [`span-queries.asciidoc`](https://github.com/elastic/elasticsearch/blob/master/docs/reference/query-dsl/span-queries.asciidoc) file.

**Comment by yevhen** [comment]
@russcam done

**Comment by clintongormley** [comment]
@yevhen i don't see a pull request for this in our repo?  Did you create one?

**Comment by yevhen** [comment]
@russcam but isn't the current PR is not the right one? :)

I did the commit https://github.com/YouScan/elasticsearch/commit/d51ade78d800b7abda5e7d79967fdb32d273927d which you can see referenced by the current PR (#20293)

**Comment by yevhen** [comment]
Should I make a separate PR?

**Comment by russcam** [comment]
@yevhen You've referenced this issue but would you be able to open a [PR with your change](https://github.com/elastic/elasticsearch/pulls), referencing this issue?

**Comment by yevhen** [comment]
this https://github.com/elastic/elasticsearch/pull/20395
