### ISSUE TITLE
ES keeps bouncing shards around and it doesn't seem to end for a long time

### ISSUE THREAD

**Issue by mkelkarbv** [elastic/elasticsearch#20308]
**Elasticsearch version**: 1.7.3

**Plugins installed**: cloud-aws

**JVM version**: openjdk version "1.8.0_65"
OpenJDK Runtime Environment (build 1.8.0_65-b17)
OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)

**OS version**: Amazon linux 3.14.35-28.38.amzn1.x86_64

**Description of the problem including expected versus actual behavior**:

Elasticsearch keeps moving shards around infinitely...

**Steps to reproduce**:
1. set cluster settings for include/exclude nodes using shard allocation filtering. 
2. watch the logs for this exception 
   "Suspect illegal state: trying to move shard from primary mode to replica mode"

After this, shards keep bouncing around infinitely....Usually it finishes moving shards in 3 hours. We waited for almost 10 hours for the same amount of data and it did not finish.

I have tried to get rid of all replicas by updating index settings, but it did not help...

**Provide logs (if relevant)**:

The only relevant message that I see is 

"Suspect illegal state: trying to move shard from primary mode to replica mode"

**Comment by bleskes** [comment]
The "Suspect illegal state: trying to move shard from primary mode to replica mode" message typically suggest split brain. Did you set `minimum_master_nodes`? Can you check the current master for all nodes during such an event by calling `GET _cat/master`?

**Comment by mkelkarbv** [comment]
@bleskes we set minimum_master_nodes = 2 ( we have 3 master eligible nodes). 
I cross-checked nodes to see if they were pointing to current master, and they were. The cluster is not around anymore. If I can get some guidance on what additional info to collect, I can collect it and report back the next time this happens.

**Comment by bleskes** [comment]
@mkelkarbv I would set the logs to `DEBUG` and if possible the `cluster.service` log to `TRACE`. That will help for sure.

**Comment by bleskes** [comment]
There has been no feedback for a while. I'm closing this for now.
