### ISSUE TITLE
JDBC Input plugin slowly eating PGA memory on Clobs

### ISSUE THREAD

**Issue by romychs** [elastic/elasticsearch#20325]
**Elasticsearch version**: 2.3.5

**Plugins installed**: [none]

**JVM version**: Oracle 8u102

**OS version**: RHEL 6

**Description of the problem including expected versus actual behavior**: I am use jdbc input plugin to transfer log messages from oracle table to ES. Input configured like:
jdbc {
    type => "cdr-prod"
    jdbc_driver_library => "/app/logstash/lib/ojdbc7.jar"
    jdbc_driver_class => "Java::oracle.jdbc.driver.OracleDriver"
    jdbc_connection_string => "jdbc:oracle:thin:<some>"
    jdbc_user => "log_user"
    jdbc_password => "log_passwd"
    jdbc_fetch_size => 200
    schedule => "* * * * *"
    statement => "SELECT logid, SUBSTR((in_xml).getClobVal(),1,8192) in_xml, SUBSTR((out_xml).getClobVal(),1,8192) out_xml FROM log_messages WHERE  logid > :sql_last_value ORDER BY logid
    sql_log_level => "debug"
    use_column_value => true
    tracking_column => "logid"
    last_run_metadata_path => "/app/logstash/db/log_messages.since"
    jdbc_validate_connection => true
    jdbc_validation_timeout => 90
    jdbc_pool_timeout => 15
    connection_retry_attempts => 5
    connection_retry_attempts_wait_time => 10
 }
logid is primary key, in_xml and out_xml is XMLType columns. We are seeing a constant memory leak. I Think it is because plugin does not release CLOBs, and continuously reuse connection from connection pool. Connection pool does not have any parameter for connection recycle (after some time of usage, or after some count os statement execution). 

**Steps to reproduce**:
 1. Log in a Oracle DB table with message in  XMLType column (some kilobytes).
 2. Running Logstash v 2.3.4 with jdbc  input plugin 
 
**Provide logs (if relevant)**:
Scream from DBA, about enormous memory consumption by log_user session.

**Comment by s1monw** [comment]
> Plugins installed: [none] 

hmm not an elasticsearch pluign, you might wanna go to logstash instead https://github.com/elastic/logstash

**Comment by romychs** [comment]
Excusez-moi, you're right :)
