### ISSUE TITLE
I want to implement a elasticsearch Data Migrator!

### ISSUE THREAD

**Issue by baiyunping333** [elastic/elasticsearch#20322]
I want to implement a elasticsearch Data Migrator. the [elasticsearch-dump](https://github.com/taskrabbit/elasticsearch-dump) is very slow. What is the best way that is doing this!

**Comment by jimferenczi** [comment]
Hi @baiyunping333 ,

Please ask questions like these in the forum instead: https://discuss.elastic.co

The github issues list is reserved for bug reports and feature requests only.
thanks
