### ISSUE TITLE
Elasticsearch logger names

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#20326]
When using Log4j and other Java-based loggers, the name of a logger tied to a class is the fully-qualified name of the class. For Elasticsearch, this would be `org.elasticsearch...` (e.g. the logger tied to `Bootstrap` would be `org.elasticsearch.bootstrap.Bootstrap`). However, Elasticsearch has long had a feature that drops the `org.elasticsearch` (so the logger for `Bootstrap` becomes `bootstrap.Bootstrap`).

I suppose this is just to remove some verbosity, but it is inconsistent with logger names in other projects, and even inconsistent with other logger names that appear in our plugins (for example, in the AWS SDK based plugins we do not drop `com.amazonaws`). We do modify `org.jboss.netty` to `netty3` and `io.netty` to just `netty`, but we do not do this for any other loggers that get exposed.

It causes another problem though: there is no way to set the logger level for only the Elasticsearch packages. That is, if you want to set the logger level to trace for Elasticsearch, then this means setting the root logger level which means picking up everything else (e.g., Netty) even if you don't want that.

The question here is, should we remove this feature and just always require the `org.elasticsearch` prefix? Note that this should not impact the ability to drop the `org.elasticsearch` prefix when the package name is logged as part of the log format, we can control that separately.

**Comment by dadoonet** [comment]
I'm +1 to require `org.elasticsearch` and basically use everything standard.
It was super nice but I think we should drop this "feature".

Big +1 on my end.

**Comment by bleskes** [comment]
@jasontedor can you please clarify this:

> Note that this should not impact the ability to drop the org.elasticsearch prefix when the package name is logged as part of the log format, we can control that separately.

PS. I will be sad if we can't come up with a consistent way, without options, to not have those long package names in our default logs. These were there for the embedded use case / embedded transport clients. With those going away it would be great if we can somehow keep the conciseness of the current default server logs.

**Comment by jasontedor** [comment]
@bleskes The Log4j pattern layout lets us control the precision of the logger name that is emitted. For example, we can specify `%c{-2}` and this will drop the first two levels in the hierarchy so `org.elasticsearch.bootstrap` becomes `bootstrap`. The downside to this approach is that `io.netty.buffer.ByteBufUtil` drops the `io.netty` and is just `buffer.ByteBufUtil` losing that it comes from Netty. Another option is `%c{1.}` so `org.elasticsearch.bootstrap` becomes `o.e.bootstrap` and `io.netty.buffer.ByteBufUtil` becomes `i.n.b.ByteBufUtil`.

**Comment by jasontedor** [comment]
Note that there's another discrepancy which is that we drop the class name from all loggers (so `org.elasticsearch.bootstrap.Bootstrap` becomes `bootstrap` because of the front and back truncation of the log name). This is again inconsistent with how log names from other components are treated (e.g., it's `io.netty.buffer.ByteBufUtil` including the class name).

**Comment by jasontedor** [comment]
Personally, I'm fine with how it is now. I put this up for discussion as @dadoonet asked in another channel and I do think it's worth ensuring we have consensus on this as we are wrapping up the Log4j 2 conversion.

**Comment by nik9000** [comment]
I'm ever so slightly in the camp of doing it the standard way instead of
our funny, but maybe slightly easier way. But not so much in favor of it
that I think it is worth spending a lot of time on.

**Comment by jasontedor** [comment]
> I'm ever so slightly in the camp of doing it the standard way instead of our funny, easier way.

To be clear, our easier way has problems. The one that I noted above about not being able to control the logging level for Elasticsearch only, we've effectively equated Elasticsearch with the root logger. The other is that it's impossible to control the log level for a single class, it's package-level only. This can be problematic for large packages, especially as we me to compress packages. 

> But not so much in favor of it that I think it is worth spending a lot of time on.

Either way, this would not be a time-consuming change at all.

**Comment by jasontedor** [comment]
The more I think about this, the more I'm becoming convinced that the two detriments I've pointed out outweigh the benefits of not having to type `org.elasticsearch` and that we should make this change. Others?

**Comment by jasontedor** [comment]
We discussed this during Fix-it-Friday and have agreed that we should let the logger names be the full name of the class (e.g., `org.elasticsearch.cluster.service.ClusterService`).
