### ISSUE TITLE
Add minhash token filter

### ISSUE THREAD

**Issue by softwaredoug** [elastic/elasticsearch#20345]
It would be nice to be able to use the minhash token filter, using [minHash token filter](https://issues.apache.org/jira/browse/LUCENE-6968) added to Lucene.

The minhash algorithm implements locality-sensitive hashing. Basically, every token is hashed into a hash table. The hash table is then sampled to generate a smaller set of representative tokens.

This has several applications
- Dimensionality reduction that preserves information that can be used in similarity calculations. For example, efficient deduplication over large sets of text, more like this, etc.

**Comment by softwaredoug** [comment]
weird this wasn't linked, associated [PR](https://github.com/elastic/elasticsearch/pull/20346)

**Comment by jasontedor** [comment]
Duplicates #20149
