### ISSUE TITLE
Geodistance aggregation across multiple contigious geolines

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#20355]
I have a map of a journey that I have taken, I have points on this journey that I can join to show the path I have taken. I'd now like to be able to measure the lengths of the lines between each point and provide a sum of those and say "this trip was N metres long" within Elasticsearch.

I am not sure if this would be a pipeline agg or a base level one (ie at geobounds level) but it seems like a pretty neat function we could add.

**Comment by clintongormley** [comment]
This doesn't fit in with the execution model of aggs or search.  There's no sense of order in which a journey could be expressed. it'd be much easier to just get back the docs with the lat/lon points then calculate the distance client side.
