### ISSUE TITLE
Maximum verbosity GC logging in a parseable format

### ISSUE THREAD

**Issue by beiske** [elastic/elasticsearch#20366]
I would like it to be possible to specify in the log config that Elasticsearch should output gc details on every observation to a custom log file. I would also want this output to include all details monitored and be in a format suitable for parsing with Logstash or similar tools.

Some of the details I'm interested in are:
- Fill ratio for each pool, before and after gc
- GC counts per type (major and minor) since last observation
- Percentage of the time since last observation that the Garbage Collector was active.

**Comment by jasontedor** [comment]
So we have these metrics available today, but we log these to the main Elasticsearch log file.
 - the ability to log every event can be controlled by tuning the thresholds to zero
 - the ability to specify a custom log file should be manageable through the Log4j configuration (but I'll ensure this is the case)
 - the format is not easily parseable
 - the log lines for GC overhead are separate from the log lines for collection samples

I'll look into improving these items.

**Comment by jasontedor** [comment]
To summarize past discussion via another channel on this topic: it's possible the needs here can be met by just enabling GC logging although this requires investigation; either way, there are improvements that can be made to the logging that is done within Elasticsearch which is what the previous [comment](https://github.com/elastic/elasticsearch/issues/20366#issuecomment-245265245) outlines.

**Comment by jasontedor** [comment]
I no longer think that we should do this. Instead, we now produce GC logs by default. These can be consumed as needed.
