### ISSUE TITLE
Fuzziness in multi_match query ranks typos over exact matches

### ISSUE THREAD

**Issue by bogdanzafirov** [elastic/elasticsearch#20369]
**Elasticsearch version**: 2.3.0

**Plugins installed**: [head, decompound, naturalsort]

**JVM version**: 1.8.0_03

**OS version**: Linux Mint 18

**Description of the problem including expected versus actual behavior**: When performing a multi_match query with fuzziness enabled results with typos have higher score than exact matches. The expected behavior should give exact matches higher score than fuzzy matches.  

**Steps to reproduce**:
 1. Create the search index with the provided index settings ([index.txt](https://github.com/elastic/elasticsearch/files/459299/index.txt))
 2. Insert the documents with the following values for the field "username": user100, user1000, user1001, user1002, user1003, user1004 
 3. Execute the multi_match query ([query.txt](https://github.com/elastic/elasticsearch/files/459300/query.txt))
 4. The first few results are "user1000", "user1001", "user1002" etc. instead "user100"
 
**Provide logs (if relevant)**: /

This issue is a duplicate of https://github.com/elastic/elasticsearch/issues/3125. But somehow this issue isn't fixed yet, although the Lucene bugfix https://issues.apache.org/jira/browse/LUCENE-329 is marked as solved.

**Comment by clintongormley** [comment]
> This issue is a duplicate of #3125. 

Actually this is quite different.  Issue 3125 is about having many occurrences of the correct term and few occurrences of an incorrectly spelled term, and having the incorrectly spelled term rank over the correct term.

The problem with your  example is this: combining fuzziness with an edge-ngram field is a bad idea.  Here's why:

    PUT t
    {
      "settings": {
        "number_of_shards": 1,
        "analysis": {
          "filter": {
            "edge_ngram": {
              "type": "edgeNGram",
              "min_gram": 1,
              "max_gram": 15
            }
          },
          "analyzer": {
            "my_analyzer": {
              "type": "custom",
              "tokenizer": "standard",
              "filter": [
                "lowercase",
                "edge_ngram"
              ]
            },
            "my_search_analyzer": {
              "type": "custom",
              "tokenizer": "standard",
              "filter": [
                "lowercase"
              ]
            }
          }
        }
      },
      "mappings": {
        "user": {
          "properties": {
            "username": {
              "type": "string",
              "analyzer": "my_analyzer",
              "search_analyzer": "my_search_analyzer"
            }
          }
        }
      }
    }
    
    POST t/user
    {"username":"user100"}
    POST t/user
    {"username":"user1001"}
    
    POST t/_validate/query?explain&rewrite
    {
      "query": {
        "match": {
          "username": {
            "query": "user100",
            "fuzziness": "1"
          }
        }
      }
    }

This query is rewritten (based on the terms in the index) as:

    (username:user10)^0.8333333 username:user100 (username:user1001)^0.85714287

The doc with `user100` matches the first two clauses, while `user1001` matches all three, and so scores higher.

if you tried the same experiment with `user1000`, `, user1001`, `user1002` and searched for `user1000` then you would get the right result.
