### ISSUE TITLE
Extend rank evaluation response to include information useful for ranking debugging

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#20363]
This relates to #19195

We already track which documents were seen in the actual response to our test queries to help with further debugging, guide further annotation efforts etc.

Open question: Would it be helpful to also track which of the annotated documents made it into the respective responses? If so, which information should we include - document id, title, some user definable field, something else?

**Comment by cbuescher** [comment]
First of all I'd find it usefull to get a breakdown of the total 'quality_level' according to the contricution of each individual search request. Something like this:
```
{
	"rank_eval": {
		"spec_id": "my-rank-eval",
		"quality_level": 0.75,
		"partial_results": [{
			"id": "amsterdam_query",
			"unknown_docs": [],
			"quality_level": 0.5
		}, {
			"id": "berlin_query",
			"unknown_docs": [],
			"quality_level": 1.0
		}]
	}
}
```
This introduces an additional array on the top level (`partial_results`, name open to suggestions) which contains the partial metric result and any additional "explain" like information. The later might differ for each metric.

**Comment by MaineC** [comment]
This got a ++ from @polyfractal - "to "breakdown" contribution mentioned in #20363.  I can guarantee users will ask to see that info :)"

**Comment by clintongormley** [comment]
Another thought, would be good to include timings per search request.  eg one set of search terms could take 20ms and another could take 1000ms

**Comment by MaineC** [comment]
Overall I think this could be helpful information. 

Not sure though if this might lead to people trying to use the API just for doing performance comparisons which I think would be better served by a separate API.

**Comment by MaineC** [comment]
@cbuescher added information on which hits were returned per query including rating information (if any). For now I'd like to close this issue as done and re-open should we find out we actually need more debugging information.
