### ISSUE TITLE
`multi_value_mode` on Terms Aggregation

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#20370]
Today, all terms in a multi-valued field are aggregated.  Sometimes users want to prioritize the terms in some fashion, so that only one (or several) of the terms are aggregated while the rest are ignored.  This is more complicated than just inclusion/exclusion filtering, since it needs to be evaluated on a per-document basis in context of the other tags.

This can be useful if the document should only "belong" to a single bucket based on some kind of tagging scheme, rather than being added to multiple buckets.

It is currently possible today by using a script in the terms aggregation.  I've worked up an example here: https://gist.github.com/polyfractal/a9c3b1c87bdd7cb8151e5b17a24d70d2

But it might be nice to support this natively in the Terms agg.  @colings86 and I were spitballing a `multi_value_mode` which could be set to a number of options: `first`,`last`,`all`, `script`, potentially others.

The idea is that you could provide a list of priorities, in an ordered array:

``` json
{
  "my_terms_agg": {
    "field": "tags",
    "multi_value_mode": "first",
    "priorities": ["foo", "bar", "baz", "fizz", "buzz"]
  }
}
```

And this document:

``` json
{
  "tags": ["xyz", "bar", "buzz"]
}
```

would only be aggregated into the "bar" bucket, since "bar" has a higher priority than "buzz", which has a higher priority than "xyz" (because it's not in the list at all).
- `all` default terms agg behavior today
- `first` / `max`: priorities are first -> last in the sorted array
- `last` / `min`: priorities are last -> first in the sorted array
- `script`: runs a script, which returns the terms to be aggregated.  But this is provided by scripting today, so probably not needed

If we only allow selecting either all the values, or just one value, it should be pretty simple implementation wise.  We can iterate through the matches as today, but instead of calling `collectDoc()` on each iteration we simply record the highest (or lowest) priority seen so far and cache the bytes.  At the end, we call `collectDoc()` once with those bytes.
### More complicated alternative

We could get fancier, although I don't think this is a good idea.  For example, we could allow the user to provide a map of priorities and allow returning above threshold, ties, etc:

``` json
{
  "my_terms_agg": {
    "field": "tags",
    "multi_value_mode": "<=2",
    "priorities": {
      "foo": 1, 
      "bar": 2, 
      "baz": 2, 
      "fizz": 3, 
      "buzz": 4
    }
  }
}
```

Which aggregates "foo" + "bar" + "baz" because their priorities are <= 2.

Honestly this is getting rather complicated, and could be done by scripting, so I don't think it'd be good to implement.  But I wanted to at least throw out the possibility :)

/cc @colings86 and @tylerfontaine

**Comment by colings86** [comment]
actually to clarify, my position on the feature was slightly different to this. My suggestion was that the multi_value_mode option would support `[ 'all', 'min', 'max', 'sum', 'avg', 'script' ] and the value(s) used for the aggregation would be the result of the chosen option applied to the values for the field in each document. For example:
* All - would work as it does now, each value in the document would be passed to the aggregator to collect
* Min - would only pass the minimum value in the document to the aggregator to collect
* Max - would only pass the maximum value in the document to the aggregator to collect
* Sum - would pass the sum of all the values in the document to the aggregator to collect
* Avg - would pass the mean average of all the values in the document to the aggregator to collect
* Script - Would pass all the values to a script whose output is an array of the values to pass to the aggregator

The example above form @polyfractal would then be an example of using a script to determine the value to use based on a prioritised array of values passed in as params to the script.

**Comment by polyfractal** [comment]
Ah, oops, thanks for the clarification :)

Downside to min/max/sum/avg is that it assumes numeric input, so it wouldn't work/be useful for string fields?

**Comment by colings86** [comment]
We discussed this in FixItFriday and agreed that the numeric use case is appealing for this (i.e. https://github.com/elastic/elasticsearch/issues/20370#issuecomment-245300544). The feeling was that the string fields case couldn't be solved much easier than having the simple script the @polyfractal has given in the gist above so using the terms aggregation for this specific priorities case would be the way to go.

**Comment by polyfractal** [comment]
Just to play devil's advocate, I'm not sure numerics alone justify the extra complexity added to the code by introducing this feature.  A script to average/min/max the numerics in a multivalued field is not terribly different from that needed to handle strings, and it's probably a bit simpler.

I guess I'd vote that if the string version is fine as a script, the numerics are probably fine as well and we can keep the implementation cleaner. :)

**Comment by colings86** [comment]
That's a good point. Maybe we should discuss this more

**Comment by jpountz** [comment]
Discussed in FixitFriday: we'd be happy to support simple multi-value modes like min/max that can be integrated both easily and efficiently (at the ordinals level). More complex use-cases need to use a scripted terms aggregation.

**Comment by polyfractal** [comment]
Eh, I vote close then.  Min/max is a trivial script, and I don't think it justifies making the terms agg even more complex for something simple like that.  IMO :)

**Comment by clintongormley** [comment]
We actually discussed making multi-value mode available consistently across all appropriate aggs.  Our implementation would be more efficient than a script and would probably be widely used.

**Comment by colings86** [comment]
@polyfractal @jpountz @clintongormley do you think this is still relevant? Is this something we should still do?

/cc @elastic/es-search-aggs

**Comment by clintongormley** [comment]
Given that zero users have commented in all this time, I don't think there is much demand for this.  It can be done today via a Painless script, which is much more efficient than previous scripting was.  let's close
