### ISSUE TITLE
Add node name to decider trace logging

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#20379]
The allocation decider logging at TRACE level can sometimes be helpful to determine why a shard is not getting allocated on specific nodes.  Currently, we [only log the node id](https://github.com/elastic/elasticsearch/blob/165565a8174975d26b5da83f864db48d469f5925/core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/AllocationDeciders.java#L77) for these messages.  It will be helpful to also include the node name (esp. when dealing with a lot of nodes in the cluster).

**Comment by makeyang** [comment]
I checked the code and found out that it's mainly logged only with node name, like below code:
logger.warn("Unable to retrieve node FS stats for {}", nodeStats.getNode().getName());
logger.trace("sending diff cluster state version [{}] with size {} to [{}]", clusterState.version(), clusterStateDiffBytes.length, discovery.localNode().getName());

so how about we only log node name here ?
if u guys agree with this, I'd like to fix it this way

**Comment by clintongormley** [comment]
@bleskes @dakrone thoughts?

**Comment by dakrone** [comment]
I don't think it'd be bad to add the name, should be a very small change to do

**Comment by bleskes** [comment]
It's trace logging, which typically means the more information you have, the better. I would say just log the whole DiscoveryNode object

**Comment by s1monw** [comment]
fixed by #20437
