### ISSUE TITLE
Allow specifying `type` in search templates

### ISSUE THREAD

**Issue by marshall007** [elastic/elasticsearch#20376]
Currently, specifying the `type` parameter in a search template results in:

```
SearchParseException[failed to parse search source. unknown search element [type]]
```

Our search templates look something like this:

```js
{
  "type": "bins", // doesn't work
  "query": {
    "bool": {
      "should": [
        // ...
        {
          "has_child": {
            "type": "products",
            "query": {
              "bool": {
                "should": [
                  // ...
                ],
                "filter": {
                  // ...
                }
              }
            },
            "score_mode": "max",
            "inner_hits": {
              "size": 200
            }
          }
        }
      ]
    }
  }
}
```

It's unclear to me whether this is a bug or intended behavior. In particular, for queries that include a `has_child/parent` clause, it doesn't really make sense that we would be able to define the child type but not the parent type in the search template. In our case, it would only ever make sense to execute this query in the context of the parent type (`bins`), so it seems like we should be able to be explicit about that in the template.

**Comment by jimferenczi** [comment]
Please ask questions like this in the forum https://discuss.elastic.co/c/elasticsearch first.
What you're asking is already possible. You can add the type in the path or your request:
```
GET _all/bins/_search/template
```
... or you can add a clause in your boolean query:
````
 "query": {
      "bool": {
         "should": [],
         "filter": [],
         "must": {
            "term": {
               "_type": "t"
            }
         }
      }
   }
```

**Comment by marshall007** [comment]
@jimferenczi sorry, I was already aware of the other mechanisms for filtering by `type` in your query. I was specifically noting in this issue that lack of support for the `type` field in search templates seems like an inconsistency.
