### ISSUE TITLE
Feature Request: Decent Logstash and Kibana service wrapper for Windows

### ISSUE THREAD

**Issue by sderungs** [elastic/elasticsearch#20371]
We have a entirely Windows-based environment with no options to setup dedicated Linux VMs for Elastic Stack. Elasticsearch comes with a well functioning service wrapper.
Unfortunately, Logstash and Kibana don't...
To be able to install Logstash and Kibana as a service on Windows one has to use some other service wrapper - like for example the Non-Sucking-Service-Manager (https://nssm.cc/), which in contrary of its name, really sucks! Reason: terminating the service won't always also terminate all Logstash/Kibana related processes. Meaning if you restart a service, instead of killing all processes from the old one and instantiating new ones, you have duplicated processes running.
This is not how I imagine running Logstash and Kibana for a big project setup...
Both should come with as-easy-installable services as Elasticsearch.

**Comment by dadoonet** [comment]
I think you are talking about:

* https://github.com/elastic/kibana/issues/6218
* https://github.com/elastic/logstash/issues/4005

Closing as elasticsearch has that already.
