### ISSUE TITLE
Use buffering in XContentBuilder.field(String,Text)

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#20381]
As a possible improvement, the method `XContentBuilder.java` method could use buffering instead of working on byte arrays if it is supported by Jackson.

This issue is created after a `TODO` in [XContentBuilder.java](https://github.com/elastic/elasticsearch/blob/bd93c7054c4c9ef3309e55c2e6eabbff983e469c/core/src/main/java/org/elasticsearch/common/xcontent/XContentBuilder.java#L346-L348) so that we don't forget it.

**Comment by nik9000** [comment]
@tlrx is this still worth investigating? It seems like we're plenty busy already but if you think it'll provide a lot of benefit we should do it. I'll close it for now but if you think it is worth doing please reopen it.
