### ISSUE TITLE
Highlighting no longer works for Lucene-style wilcard queries within a function-score.

### ISSUE THREAD

**Issue by benzitohhh** [elastic/elasticsearch#20392]
**Elasticsearch version**: 2.4.0

**Plugins installed**: None

**JVM version**: 8

**OS version**: MacOSX, Linux

Highlighting no longer works for Lucene-style wilcard queries within a function-score.

This was working ok in v2.3.4, but is not working since v2.4.0

I think this may be related to this change: https://github.com/elastic/elasticsearch/pull/18183

For example, previously the below was returning highlights ok. Now it still returns results, but without any highlights:
```
{
    "highlight": {
        "fields": {
          "name": {}
        }
    },
  
    "query": {
        "function_score": {
            "script_score": {
                "script": "(1 + 5 * log(1 + doc['size_active'].value) )"
            },

            "query": {
                "query_string": {
                    "fields": [
                        "name"
                    ],
                    "query": "microsoft*"
                }
            }

        }
    }
}
```

The same query without the wildcard returns highlights for all hits:
```
{
    "highlight": {
        "fields": {
          "name": {}
        }
    },
  
    "query": {
        "function_score": {
            "script_score": {
                "script": "(1 + 5 * log(1 + doc['size_active'].value) )"
            },

            "query": {
                "query_string": {
                    "fields": [
                        "name"
                    ],
                    "query": "microsoft"
                }
            }

        }
    }
}
```

**Comment by clintongormley** [comment]
@jimferenczi would you mind taking a look?

**Comment by jimferenczi** [comment]
@clintongormley, I opened https://github.com/elastic/elasticsearch/pull/20400

**Comment by vinothkgithub** [comment]
Wildcards support with FunctionScoreQuery is issue is fixed ? If yes in which version of ES it is supported? Is there a  patch available to fix this issue in ES 2.4.0 version?

**Comment by clintongormley** [comment]
@vinothkgithub see https://github.com/elastic/elasticsearch/pull/20400 - it's fixed in 2.4.1

**Comment by vinothkgithub** [comment]
Tried the below query in 2.4.1 and 2.4.4 but it is not highlighting wildcard search in FunctionScoreQuery Any suggestions ?
Request Query:

{
  "query" : {
    "function_score" : {
      "query" : {
        "function_score" : {
          "query" : {
            "query_string" : {
                "fields":["content","title"],
              "query" : "rec*",
              "default_operator" : "and",
              "auto_generate_phrase_queries" : false
            }
          },
          "functions" : [ {
            "filter" : {
              "match" : {
                "content" : {
                  "query" : "rec*",
                  "type" : "phrase"
                }
              }
            },
            "weight" : 20.0
          }, {
            "filter" : {
              "match" : {
                "title" : {
                  "query" : "rec*",
                  "type" : "phrase"
                }
              }
            },
            "weight" : 20.0
          } ]
        }
      },
      "functions" : [ ]
    }
  },
  "explain" : true,
  "fields" : ["title","content"],
  "highlight" : {
    "fields" : {
      "content":{},
      "title":{}
    }
  }
}





Response:
{
  "took": 19,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 3,
    "max_score": 20,
    "hits": [
      {
        "_shard": 0,
        "_node": "gfwiOjHuR-uvQE8cyhRhQA",
        "_index": "book",
        "_type": "samplebook",
        "_id": "AVo83CXrro3C9qemkLzo",
        "_score": 20,
        "fields": {
          "title": [
            "book2"
          ],
          "content": [
            "sample books rec"
          ]
        },
        "_explanation": {
          "value": 20,
          "description": "sum of:",
          "details": [
            {
              "value": 20,
              "description": "function score, product of:",
              "details": [
                {
                  "value": 1,
                  "description": "max of:",
                  "details": [
                    {
                      "value": 1,
                      "description": "content:rec*, product of:",
                      "details": [
                        {
                          "value": 1,
                          "description": "boost",
                          "details": []
                        },
                        {
                          "value": 1,
                          "description": "queryNorm",
                          "details": []
                        }
                      ]
                    }
                  ]
                },
                {
                  "value": 20,
                  "description": "min of:",
                  "details": [
                    {
                      "value": 20,
                      "description": "function score, score mode [multiply]",
                      "details": [
                        {
                          "value": 20,
                          "description": "function score, product of:",
                          "details": [
                            {
                              "value": 1,
                              "description": "match filter: content:rec",
                              "details": []
                            },
                            {
                              "value": 20,
                              "description": "product of:",
                              "details": [
                                {
                                  "value": 1,
                                  "description": "constant score 1.0 - no function provided",
                                  "details": []
                                },
                                {
                                  "value": 20,
                                  "description": "weight",
                                  "details": []
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "value": 3.4028235e+38,
                      "description": "maxBoost",
                      "details": []
                    }
                  ]
                }
              ]
            },
            {
              "value": 0,
              "description": "match on required clause, product of:",
              "details": [
                {
                  "value": 0,
                  "description": "# clause",
                  "details": []
                },
                {
                  "value": 1,
                  "description": "_type:samplebook, product of:",
                  "details": [
                    {
                      "value": 1,
                      "description": "boost",
                      "details": []
                    },
                    {
                      "value": 1,
                      "description": "queryNorm",
                      "details": []
                    }
                  ]
                }
              ]
            }
          ]
        }
      },
      {
        "_shard": 3,
        "_node": "gfwiOjHuR-uvQE8cyhRhQA",
        "_index": "book",
        "_type": "samplebook",
        "_id": "AVo83AThro3C9qemkLzn",
        "_score": 1,
       "fields": {
          "title": [
            "book"
          ],
          "content": [
            "sample books recom"
          ]
        },
        "_explanation": {
          "value": 1,
          "description": "sum of:",
          "details": [
            {
              "value": 1,
              "description": "max of:",
              "details": [
                {
                  "value": 1,
                  "description": "content:rec*, product of:",
                  "details": [
                    {
                      "value": 1,
                      "description": "boost",
                      "details": []
                    },
                    {
                      "value": 1,
                      "description": "queryNorm",
                      "details": []
                    }
                  ]
                }
              ]
            },
            {
              "value": 0,
              "description": "match on required clause, product of:",
              "details": [
                {
                  "value": 0,
                  "description": "# clause",
                  "details": []
                },
                {
                  "value": 1,
                  "description": "_type:samplebook, product of:",
                  "details": [
                    {
                      "value": 1,
                      "description": "boost",
                      "details": []
                    },
                    {
                      "value": 1,
                      "description": "queryNorm",
                      "details": []
                    }
                  ]
                }
              ]
            }
          ]
        }
      },
      {
        "_shard": 4,
        "_node": "gfwiOjHuR-uvQE8cyhRhQA",
        "_index": "book",
        "_type": "samplebook",
        "_id": "AVo82-Ufro3C9qemkLzm",
        "_score": 1,
        "fields": {
          "title": [
            "book"
          ],
          "content": [
            "sample books recommended"
          ]
        },
        "_explanation": {
          "value": 1,
          "description": "sum of:",
          "details": [
            {
              "value": 1,
              "description": "max of:",
              "details": [
                {
                  "value": 1,
                  "description": "content:rec*, product of:",
                  "details": [
                    {
                      "value": 1,
                      "description": "boost",
                      "details": []
                    },
                    {
                      "value": 1,
                      "description": "queryNorm",
                      "details": []
                    }
                  ]
                }
              ]
            },
            {
              "value": 0,
              "description": "match on required clause, product of:",
              "details": [
                {
                  "value": 0,
                  "description": "# clause",
                  "details": []
                },
                {
                  "value": 1,
                  "description": "_type:samplebook, product of:",
                  "details": [
                    {
                      "value": 1,
                      "description": "boost",
                      "details": []
                    },
                    {
                      "value": 1,
                      "description": "queryNorm",
                      "details": []
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    ]
  }
}

**Comment by jimczi** [comment]
> Tried the below query in 2.4.1 and 2.4.4 but it is not highlighting wildcard search in FunctionScoreQuery Any suggestions ?

You have a nested `function_score` inside a `function_score`:
````
"query" : {
   "function_score" : {
       "query" : {
           "function_score" : {
````

Any reason why ? I don't see a use case for this but you're right it's not working. The highlighter extracts the query inside the `function_score` but not recursively. 
You can just remove the parent function score in your recreation and the terms are correctly highlighted.

**Comment by vinothkgithub** [comment]
Thanks , Tired with one function_score as suggested still it is not highlighting any  configuration required?

{
      "query" : {
        "function_score" : {
          "query" : {
            "query_string" : {
                "fields":["content","title"],
              "query" : "rec*",
              "default_operator" : "and",
              "auto_generate_phrase_queries" : false
            }
          },
          "functions" : [ {
            "filter" : {
              "match" : {
                "content" : {
                  "query" : "rec*",
                  "type" : "phrase"
                }
              }
            },
            "weight" : 20.0
          }, {
            "filter" : {
              "match" : {
                "title" : {
                  "query" : "rec*",
                  "type" : "phrase"
                }
              }
            },
            "weight" : 20.0
          } ]
        }
      },
  "explain" : true,
  "fields" : ["title","content"],
  "highlight" : {
    "fields" : {
      "content":{},
      "title":{}
    }
  }
}


Response:

{
  "took": 17,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 3,
    "max_score": 1,
    "hits": [
      {
        "_shard": 0,
        "_node": "1NPwf1MBTcC4hZTIpiTO8Q",
        "_index": "book",
        "_type": "samplebook",
        "_id": "AVo9aOYUmOpf6AthWiL6",
        "_score": 1,
        "fields": {
          "title": [
            "samplebook"
          ],
          "content": [
            "this sample book is recommended"
          ]
        },
        "_explanation": {
          "value": 1,
          "description": "sum of:",
          "details": [
            {
              "value": 1,
              "description": "max of:",
              "details": [
                {
                  "value": 1,
                  "description": "content:rec*, product of:",
                  "details": [
                    {
                      "value": 1,
                      "description": "boost",
                      "details": []
                    },
                    {
                      "value": 1,
                      "description": "queryNorm",
                      "details": []
                    }
                  ]
                }
              ]
            },
            {
              "value": 0,
              "description": "match on required clause, product of:",
              "details": [
                {
                  "value": 0,
                  "description": "# clause",
                  "details": []
                },
                {
                  "value": 1,
                  "description": "_type:samplebook, product of:",
                  "details": [
                    {
                      "value": 1,
                      "description": "boost",
                      "details": []
                    },
                    {
                      "value": 1,
                      "description": "queryNorm",
                      "details": []
                    }
                  ]
                }
              ]
            }
          ]
        }
      },
      {
        "_shard": 1,
        "_node": "1NPwf1MBTcC4hZTIpiTO8Q",
        "_index": "book",
        "_type": "samplebook",
        "_id": "AVo9aTMomOpf6AthWiL7",
        "_score": 1,
        "fields": {
          "title": [
            "samplebook1"
          ],
          "content": [
            "this sample book is recom"
          ]
        },
        "_explanation": {
          "value": 1,
          "description": "sum of:",
          "details": [
            {
              "value": 1,
              "description": "max of:",
              "details": [
                {
                  "value": 1,
                  "description": "content:rec*, product of:",
                  "details": [
                    {
                      "value": 1,
                      "description": "boost",
                      "details": []
                    },
                    {
                      "value": 1,
                      "description": "queryNorm",
                      "details": []
                    }
                  ]
                }
              ]
            },
            {
              "value": 0,
              "description": "match on required clause, product of:",
              "details": [
                {
                  "value": 0,
                  "description": "# clause",
                  "details": []
                },
                {
                  "value": 1,
                  "description": "_type:samplebook, product of:",
                  "details": [
                    {
                      "value": 1,
                      "description": "boost",
                      "details": []
                    },
                    {
                      "value": 1,
                      "description": "queryNorm",
                      "details": []
                    }
                  ]
                }
              ]
            }
          ]
        }
      },
      {
        "_shard": 4,
        "_node": "1NPwf1MBTcC4hZTIpiTO8Q",
        "_index": "book",
        "_type": "samplebook",
        "_id": "AVo9aXRBmOpf6AthWiL8",
        "_score": 1,
        "fields": {
          "title": [
            "samplebook2"
          ],
          "content": [
            "this sample book is recorded"
          ]
        },
        "_explanation": {
          "value": 1,
          "description": "sum of:",
          "details": [
            {
              "value": 1,
              "description": "max of:",
              "details": [
                {
                  "value": 1,
                  "description": "content:rec*, product of:",
                  "details": [
                    {
                      "value": 1,
                      "description": "boost",
                      "details": []
                    },
                    {
                      "value": 1,
                      "description": "queryNorm",
                      "details": []
                    }
                  ]
                }
              ]
            },
            {
              "value": 0,
              "description": "match on required clause, product of:",
              "details": [
                {
                  "value": 0,
                  "description": "# clause",
                  "details": []
                },
                {
                  "value": 1,
                  "description": "_type:samplebook, product of:",
                  "details": [
                    {
                      "value": 1,
                      "description": "boost",
                      "details": []
                    },
                    {
                      "value": 1,
                      "description": "queryNorm",
                      "details": []
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    ]
  }
}

**Comment by jimczi** [comment]
@vinothkgithub your example works with 2.4.4
The fix in 2.4.1 was incomplete and required another fix ;)
Please upgrade to 2.4.4

**Comment by vinothkgithub** [comment]
Thanks, it works Good :-)

**Comment by rkalhans** [comment]
Hello,

I tested this in ES 2.4.4 and I can still see this issue. 
Here is my query
```
POST workitemsearchshared_0_1/workItemContract/_search
{
   "highlight": {
      "pre_tags": [
         "<highlighthit>"
      ],
      "post_tags": [
         "</highlighthit>"
      ],
      "fields": {
         "fields.str|title|system$": {}
      },
      "require_field_match": true
   },
   "fields": [
      "fields.str|title|system$"
   ],
   "query": {
      "function_score": {
         "query": {
            "query_string": {
               "query": "park*",
               "fields": [
                  "fields.str|title|system$"
               ]
            }
         },
         "functions": [
            {
               "filter": {
                  "term": {
                     "fields.str|title|system$": "parkour"
                  }
               },
               "weight": 8
            }
         ]
      }
  }
}
```
**Highlighting working here**

![highitingworking](https://cloud.githubusercontent.com/assets/5341933/23609530/7e2dda2c-0294-11e7-9762-731b1523dc25.PNG)

**Highlighting not working here**

![notworking](https://cloud.githubusercontent.com/assets/5341933/23609531/80776a78-0294-11e7-9809-7a82a41c2b62.PNG)

**Server build etc.**
![server](https://cloud.githubusercontent.com/assets/5341933/23609642/f6273f64-0294-11e7-9428-77054e1a15d1.PNG)
