### ISSUE TITLE
Enable Netty 4 advanced leak detection in tests and fail the build if there is a leak

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#20398]
Netty has pooled and unpooled byte buf alloactors. The pooled allocator uses reference counting to track when a byte buf can be returned to the pool, and leak detection to ensure that byte bufs are properly accessed/released. Netty has different levels of detection from disabled to paranoid (check every access). We should enable leak detection in tests and fail the build if a leak is detected.

Relates #19526, relates #19562

**Comment by original-brownbear** [comment]
Gave this a go in https://github.com/elastic/elasticsearch/pull/31861 :)
