### ISSUE TITLE
position_increment_gap should be allowed for analyzed fields where positions are not stored

### ISSUE THREAD

**Issue by nomoa** [elastic/elasticsearch#20413]
In #19510 position_increment_gap is no longer allowed on fields where position are not stored.
It's a breaking change that prevents some indices running on 2.3.4 to be upgraded to 2.4.

Initially I thought that it could break some use cases with the shingle token filter but it does not appear to be the case.

The problem here (I think) is that a breaking change has been introduced into the 2.4 branch.

**Comment by clintongormley** [comment]
@nomoa thanks - yeah it wasn't the intention to introduce a breaking change in a minor upgrade.

@rjernst we should add a bwc layer so that we can upgrade these indices.  will need to apply to 5.0 as well i think (correct @jpountz ?)

**Comment by jpountz** [comment]
Correct.

**Comment by s1monw** [comment]
@jpountz @clintongormley what's the status on this?

**Comment by s1monw** [comment]
@dakrone ^^

**Comment by dakrone** [comment]
@s1monw I have not started on this, I'll start working on it today.

**Comment by dakrone** [comment]
Resolved by https://github.com/elastic/elasticsearch/pull/20806 and https://github.com/elastic/elasticsearch/pull/20810

**Comment by nomoa** [comment]
Thanks!
