### ISSUE TITLE
Add Named Queries to explanation

### ISSUE THREAD

**Issue by david206** [elastic/elasticsearch#20414]
**Describe the feature**:
When adding `_name` to query, the name will be visible on the explanation (on the same level as the hit it matched on), in addition to the `matched_queries` field. This will make explanation of complicated queries more readable.

**Comment by jpountz** [comment]
Integrating these features would not be easy unfortunately. Moreover, query rewriting currently has the ability to merge some queries together or to remove them if they prove useless so that would make it impossible to put the name of the queries in the explanation.

Closing it as a won't fix.
