### ISSUE TITLE
2.4 and support for Netty 4

### ISSUE THREAD

**Issue by cuthbe** [elastic/elasticsearch#20410]
We are trying to upgrade our ES to 2.4 but when we do we are getting jar conflicts with the very old Netty version running on 2.4, I think it is picking up 3.6? Any chance this is going to be updated?

**Comment by s1monw** [comment]
this is coming in 5.0 and will not be backported. see https://github.com/elastic/elasticsearch/issues/3226

**Comment by cuthbe** [comment]
Wow thanks for the quick response. Okay so hang ten for 5.0 then.

**Comment by s1monw** [comment]
@cuthbe it's not too far out but I can't give you an exact date. Given the fact that we already branched 5.0 out is a good sign :)

**Comment by cuthbe** [comment]
Thanks for the update. Looking forward to the update.
