### ISSUE TITLE
RankEval: Fetch specifications/ annotations from an index

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#20439]
Some feedback from @polyfractal 

Re: size of request json.  I also think it'd be useful  (phase two feature, no need for it now!) for this API to support fetching the specification(s) from an index.  I don't think it's outside the responsibility of the API.  A secondary tool/UI could do it, but the point is to reduce complexity of the request, persisting the specification, and reducing network overhead.  

E.g. imagine there is a UI sitting on top of the API.  That UI needs to persist the ranking specification somewhere, likely in ES.  So either the UI needs to fetch the entire specification then send it right back to the server, or the API can just do it internally.  I see it similar to why the Terms Filter supports a "lookup" mode.

It'd also simplify the scenario where rankings are created by some user automation, not human-tagging.  Allowing the specs to be storeable means the creation process can be decoupled from the ranking process.

But I 100% agree this is not an important feature to prioritize now, just something to consider later :)

**Comment by cbuescher** [comment]
Closing in favour of a summary in https://github.com/elastic/elasticsearch/issues/40865
