### ISSUE TITLE
Backwards50ClientYamlTestSuiteIT test {p0=cluster.stats/10_basic/cluster stats test} fails occasionally

### ISSUE THREAD

**Issue by johtani** [elastic/elasticsearch#20436]
`Backwards50ClientYamlTestSuiteIT` `test {p0=cluster.stats/10_basic/cluster stats test}` fails occasionally with the following assertion error:
```
FAILURE 0.02s | Backwards50ClientYamlTestSuiteIT.test {p0=cluster.stats/10_basic/cluster stats test} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [cluster.stats/10_basic:25]: field [nodes.os.mem.free_percent] doesn't have a true value
   > Expected: not "0"
   >      but: was "0"
   > 	at __randomizedtesting.SeedInfo.seed([E2ADCCE8E05826B1:6AF9F3324EA44B49]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:329)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:309)
   > 	at java.lang.Thread.run(Thread.java:745)
   > Caused by: java.lang.AssertionError: field [nodes.os.mem.free_percent] doesn't have a true value
   > Expected: not "0"
   >      but: was "0"
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.rest.yaml.section.IsTrueAssertion.doAssert(IsTrueAssertion.java:53)
   > 	at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:325)
   > 	... 37 more
```

Latest build where this occurred: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/2231/consoleFull

Reproduce with:
`gradle :qa:backwards-5.0:integTest -Dtests.seed=E2ADCCE8E05826B1 -Dtests.class=org.elasticsearch.backwards.Backwards50ClientYamlTestSuiteIT -Dtests.method="test {p0=cluster.stats/10_basic/cluster stats test}" -Dtests.security.manager=true -Dtests.locale=fr-CA -Dtests.timezone=Asia/Ulan_Bator`

And same error occurred 5.0 branch. https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.0+multijob-unix-compatibility/os=ubuntu/4/consoleFull

**Comment by spinscale** [comment]
that wont be reproducible with the seed, as it's solely dependent if the system running the tests on, does not have any memory available (just ran into this locally)... Checking for the value being not null should be sufficient

**Comment by spinscale** [comment]
fixed in https://github.com/elastic/elasticsearch/pull/20434
