### ISSUE TITLE
Add Mean Average Precision to list of supported rank eval metrics

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#20440]
Suggestion from @polyfractal - Mean Average Precision might be a nice metric to ship in addition to the others

**Comment by MaineC** [comment]
@polyfractal After re-reading the Wikipedia article here https://en.wikipedia.org/wiki/Information_retrieval#Mean_average_precision I believe this is what we already have if you configure rank_eval to return the precision metric:

What we do internally is to compute precision_at_n for each query, then return the average over  precision values for all queries in the response.

Maybe I'm missing something here?

**Comment by polyfractal** [comment]
Ah, ok, I think I may just have misunderstood how the precision metric was being calculated.  Average of precision_at_n does indeed sound like MAP :)

**Comment by MaineC** [comment]
Ok, closing this one then.
