### ISSUE TITLE
Filters not working when applied to an analyzed field

### ISSUE THREAD

**Issue by Nokel81** [elastic/elasticsearch#20449]
**Elasticsearch version**:
2.5.3
**Plugins installed**: []

**JVM version**:
JVM: 1.8.0_91
**OS version**:
macOSX El Capitan 10.11.2
**Description of the problem including expected versus actual behavior**:
With an elasticsearch database with a model with specific analytics for each field the custom filter described in the elasticsearch.yml file does not seam to be applied to the field when querying. 
**Steps to reproduce**:
 1. In yml file:
```
index:
    analysis:
        analyzer:
            nofuzzy:
                type: keyword
                tokenizer: keyword
                filter: trim
```
 2. Model that is posted to `[PUT] localhost:9200/test/`
```
{
    "mappings": {
        "temp": {
            "properties": {
                "text": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "analyzer": "nofuzzy"
                },
                "desc": {
                    "type": "string",
                    "index": "not_analyzed"
                }
            }
        }
    }
}
```
 3. Add various data
 4. Perform a search on the field `name` with mismatched capitalizations (including adding or removing capitals, and using just capitals or lowercase letters.
 5. Receive nothing back

**Comment by dakrone** [comment]
> Perform a search on the field name with mismatched capitalizations (including adding or removing capitals, and using just capitals or lowercase letters.

The `keyword` tokenizer does not change the case of the originally indexed terms; in order to match them, you will need to match the case in your query. If you want to have case-insensitive matching you need to use the `lowercase` token filter.

**Comment by Nokel81** [comment]
Sorry, I copied the wrong filter, I was using the "lowercase" filter, I will change my original post

**Comment by dakrone** [comment]
> Sorry, I copied the wrong filter, I was using the "lowercase" filter, I will change my original post

Can you include a document and what query you are using so we can try to reproduce this?

**Comment by Nokel81** [comment]
Document:
```
{
    "text": "Hello from the other side",
    "name": "JOHN CENA, master of the universe",
    "dexc": "It came from behind"
}
```
Query:
```
{
    "query": {
        "regexp: {
            "name": ".*cena.*"
        }
    }
}
```

This does not find the document

**Comment by dakrone** [comment]
You have typos in your configuration, causing it to not have the effect you intend, here's a correct configuration:

```yaml
index:
  analysis:
    analyzer:
      nofuzzy:
        type: custom
        tokenizer: keyword
        filter: [lowercase]
```

I would recommend against putting this into `config/elasticsearch.yml` though, as it is disallowed in elasticsearch 5.x. So I'd recommend you put it into either an index template or in the index settings itself.
