### ISSUE TITLE
RankEval: Will we run into folks running rank eval on a fully labelled corpus?

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#20441]
Question from @polyfractal  I wonder if we'll run into folks who have an entirely labelled dataset (I'm thinking ML folks, not IR), who may be interested in metrics like f-score, AUC of ROC curve, etc?  Just a thought for far-future discussions, no need to spend many cycles thinking about now.  Sorta ties into what was mentioned about using scroll for bigger datasets, etc

**Comment by MaineC** [comment]
While I myself like AUC of ROC curve and friends very much I wonder how for any practical purpose people would come up with a fully labelled corpus and store that inside of ES.

**Comment by cbuescher** [comment]
Closing in favour of  #29653 meta issue.
