### ISSUE TITLE
Feature request: Be able to specify logger.yml path

### ISSUE THREAD

**Issue by chendo** [elastic/elasticsearch#2044]
I'd like to be able to specify the `logger.yml` path when booting up elasticsearch, similar to the `-Des.config=<path>` option.

Use case: booting up a ES for testing purposes, want to be able to specify a custom logger.yml without having to edit the system-wide one.

**Comment by javanna** [comment]
We've had a long discussion about this in our FixItFriday session. Our feeling is that we're trying to remove complication from the code base. Having one way to do things just makes it simpler to understand and debug. So for now, we're going to close this issue. We may revisit this in the future if there is popular demand and the change makes life easier for the majority of users.
