### ISSUE TITLE
Native script example looks up field values using source

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#20454]
The example code snippet provided [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html#native-java-scripts) uses source() for field lookups.  For most cases, using doc().get is much more efficient.  

Suggestions:
1.  Update the documentation to provide a doc() lookup example
2.  Also add a link to our native script examples [here](https://github.com/imotov/elasticsearch-native-script-example)

**Comment by rjernst** [comment]
> For most cases, using doc().get is much more efficient.

It is *always* more efficient. It is just in some cases, doc values are not available (eg in an update or ingest script).

**Comment by rjernst** [comment]
Native scripts have been removed in master and the replaced docs no longer do source lookups.
