### ISSUE TITLE
Provide an easier way to list templates

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#20467]
Currently to get a list of the templates you have to call `_templates`, which then returns (usually) a large JSON result you need to parse.
This isn't the easiest way to find out what exists when you want to do a quick check or help someone troubleshoot.

Would be possible to add a `_cat/template`  output that listed something like name, index pattern (ie the `template value`) and the order so that users can quickly see what is in the cluster.
Otherwise a `_template?summary` option that shows the same?

**Comment by tlrx** [comment]
It sounds like a good idea, maybe `_cat/templates` (plural) to be consistent with other cat actions. I think it could also display the recent `version` @pickypg added some time ago.

**Comment by makeyang** [comment]
+1 and can anybody give it a adoptme tag?

**Comment by nik9000** [comment]
Makes sense to me. Anyone object to me giving it the low-hanging-fruit and adoptme tags like @makeyang mentioned?
