### ISSUE TITLE
multi_match with type phrase_prefix query doesn't return all the results on the field _all

### ISSUE THREAD

**Issue by francescoinfante** [elastic/elasticsearch#20470]
**Elasticsearch version**: 2.4.0

**Plugins installed**: []

**JVM version**: 1.8.0_91

**OS version**: OS X 10.11.6

**Description of the problem including expected versus actual behavior**:
When I try the following query:

```
{
  multi_match: {
    fields: ["_all"],
    query: "hel",
    type: "phrase_prefix"
}
```
It doesn't return documents that contains `hel` as prefix but only documents that contains `hel` as a token.

**Steps to reproduce**:
 1. 
```
POST cleanindex/type
{
  field: "hello world"
}
```
 2.
```
GET cleanindex/type/_search
{
  query: {
    multi_match: {
      fields: ["_all"],
      query: "hel",
      type: "phrase_prefix"
    }
  }
}
```
-> It doesn't return any document, while (I think) it should.
 3.
```
GET cleanindex/type/_search
{
  query: {
    multi_match: {
      fields: ["_all"],
      query: "hello",
      type: "phrase_prefix"
    }
  }
}
```
-> It returns the document.

**Comment by jimferenczi** [comment]
Thank you for the detailed report @francescoinfante 

I opened https://github.com/elastic/elasticsearch/pull/20471
