### ISSUE TITLE
Completion suggester docs claim `_source` filters the source but this isn't implemented

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#20482]
I found this while going through snippets that aren't marked `// CONSOLE`. In this case the [this](https://github.com/elastic/elasticsearch/blame/master/docs/reference/search/suggesters/completion-suggest.asciidoc#L201-L222) snippet looks to suggest something that isn't implemented.

**Comment by nik9000** [comment]
I know @jimferenczi's been working on source filtering lately but the completion suggester is @areek's baby. It looks like this is simply a case of the parsing not being implemented which isn't super difficult to fix so I expect anyone can take it.

**Comment by nik9000** [comment]
I can also take this if everyone else is busy!

**Comment by jimferenczi** [comment]
I don't think it is worth implementing this since the _suggest endpoint will be deprecated in 5.0 (https://github.com/elastic/elasticsearch/pull/20435) and that it works with the _search API ?

**Comment by nik9000** [comment]
Perfect! So long as we use the _search API in the docs we're all good then.

**Comment by russcam** [comment]
@nik9000 Completion Suggester documentation still says `_suggest` supports `_source` filtering.

Since `_suggest` endpoint still exists in 5.0, I think source filtering should be included as per the current documentation, to be consistent with suggestions when using the `_search` endpoint.

**Comment by nik9000** [comment]
Yeah, if we're going to remove it in 6.0 we don't need docks there but we should fix the docs in the 5.0 and 5.x branch. @russcam, are you willing to open a PR to do it?

**Comment by nik9000** [comment]
> Yeah, if we're going to remove it in 6.0 we don't need docks there but we should fix the docs in the 5.0 and 5.x branch. @russcam, are you willing to open a PR to do it?

Ignore that. I've found a moment so I'll just do it now.

**Comment by nik9000** [comment]
@russcam I opened #21268.
