### ISSUE TITLE
windows 10 run error

### ISSUE THREAD

**Issue by cuibty** [elastic/elasticsearch#20480]
run elasticsearch.bat
Invalid initial heap size: -Xms${packaging.elasticsearch.heap.min}
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

Windows 10（1067）Pro x64 
ElasticSearch 1.7.5

**Comment by dadoonet** [comment]
I downloaded 1.7.5 from https://www.elastic.co/downloads/past-releases/elasticsearch-1-7-5 
I can't find this `-Xms${packaging.elasticsearch.heap.min}`. From which site did you download elasticsearch?

**Comment by jasontedor** [comment]
This does not reproduce for me on a fresh install of Elasticsearch 1.7.5 on Windows 10. I downloaded the [zip packaging](https://www.elastic.co/downloads/past-releases/elasticsearch-1-7-5). The line that you point out does not appear in the batch files. I do not think there is a bug here, I think that you have a bad package or an environmental problem. Feel free to open a topic on the [Elastic Discourse forum](https://discuss.elastic.co) if you need additional help troubleshooting. Please note that you'll have to give more detail instructions on reproducing.
