### ISSUE TITLE
Reindex from remote response parsing is too strict?

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#20504]
I just noticed a potential problem with reindex from remote, which could also apply to other cases where we use `ObjectParser`. Whenever a field that is not declared is received, the parser will barf as the field is not supported by the parser. This is very good when we parse requests so that we make sure that something that gets sent by users which is not supported is not ignored. Rather throw an error so users can fix their request. When parsing from a remote node though this strictness can cause problems because we want to be compatible with multiple es versions.

If we in the future add one single field to the response of any of the api that reindex from remote relies on (info, search, bulk...) parsing breaks and reindex from remote doesn't work anymore. I experienced this in #20503. I think that reindex from remote should parse the fields that it knows about and ignore the rest, to make sure that we are compatible? Maybe using `ObjectParser` is not the best in this specific case?

**Comment by nik9000** [comment]
> Maybe using ObjectParser is not the best in this specific case?

I think it might be better to just teach it how to ignore extra fields we don't care about in this fairly rare case.

**Comment by javanna** [comment]
> I think it might be better to just teach it how to ignore extra fields we don't care about in this fairly rare case.

Sure I just wouldn't want ObjectParser to become lenient in any other case though... if it can be lenient we may end up using it that way in other places for no reason?

**Comment by nik9000** [comment]
I think we could make the leniency optional and use code review to prevent us from being silly about it.

**Comment by javanna** [comment]
We discussed this during FixItFriday. Reindex from remote should keep on using `ObjectParser`, but we should write a subclass for it (PartialObjectParser) that allows to parse partial messages. We parse what we know about and ignore the rest. Obviously this new subclass should only be used in special cases like reindex from remote, not for parsing requests where we still want to be strict and barf whenever we get something that is not supported.
