### ISSUE TITLE
Query with suggester doesn't output suggestions[v5.0.0a5]

### ISSUE THREAD

**Issue by itay-grudev** [elastic/elasticsearch#20500]
The query below only outputs hits and not suggestions. If I drop the query part, I get suggestions, but of course no hits.

```bash
curl -XPOST http://localhost:9200/_search -d '
{
  "query": {
    "multi_match": {
      "query": "workd",
      "fields": ["title^5", "plain_body"]
    },
    "filters": {
      "terms": {
        "status": [ 3 ]
      }
    }
  },
  "suggest": {
    "text": "workd",
    "title": {
      "term": {
        "field": "title"
      }
    },
    "body": {
      "term": {
        "field": "plain_body"
      }
    }
  }
}'
```

**Comment by s1monw** [comment]
that doesn't sound good @areek can you please take a look?

**Comment by itay-grudev** [comment]
I am not 100% certain (as I might have made a mistake) but I think that `highlight` is ignored as well when added to the requests.

**Comment by itay-grudev** [comment]
I just moved the query part to the end of the request and the suggestions started working. It seems like someone `brake`-ed out earlier after handling the `query` case.

**Comment by areek** [comment]
@itay-grudev can you post the response you are getting from the `_search` endpoint when you define query and suggest?

**Comment by itay-grudev** [comment]
Which case (suggest/query order)?

**Comment by jimferenczi** [comment]
This is a bug indeed but I don't think it's related to the suggest part. Your query is not valid but it is not caught by the query parser. `filters` is not recognized as a query and it seems that it breaks the parsing of the whole query. I'll investigate but you should check your queries first in order to remove the part that are not valid.

**Comment by itay-grudev** [comment]
@jimferenczi  I don't think it is the suggesters. I think it is the query parser as well, as the problem doesn't occur when I change the order of the `query` and `suggest` statements.

**Comment by clintongormley** [comment]
@jimferenczi `query` should only accept a single key, not multiple

**Comment by itay-grudev** [comment]
I would like to note that if I place the `filters` block in the root object I get the:
```txt
{"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a START_OBJECT in [filters].","line":1,"col":219}],"type":"parsing_exception","reason":"Unknown key for a START_OBJECT in [filters].","line":1,"col":219},"status":400}
```
This also happens if I use `filter` (singular).

P.S. Dumps coming in a minute.

**Comment by jimferenczi** [comment]
@clintongormley yep but for some reason this is not caught by the parser and we end up with a weird query that is a mix of the two keys (at least in my reproduction scenario). The weird thing is that the validation API rejects the query but the _search endpoint doesn't. I'll investigate ...

**Comment by itay-grudev** [comment]
@jimferenczi What is the correct syntax for the query? Where should the `suggest`, `filters` and `highlight` parts be?

**Comment by areek** [comment]
@itay-grudev can you try:
```
{
	"query": {
		"bool": {
			"must": [{
				"multi_match": {
					"query": "workd",
					"fields": ["title^5", "plain_body"]
				}
			}],
			"filter": [{
				"terms": {
					"status": [3]
				}
			}]
		}
	},
	"suggest": {
		"text": "workd",
		"title": {
			"term": {
				"field": "title"
			}
		},
		"body": {
			"term": {
				"field": "plain_body"
			}
		}
	}
}
```

**Comment by itay-grudev** [comment]
This works, yes. Thanks.

**Comment by itay-grudev** [comment]
My problem is resolved. When you handle your query parser problem you should close the issue.
