### ISSUE TITLE
plugins.path or home.path need to be configurable or some other way of activating plugins after install

### ISSUE THREAD

**Issue by beiske** [elastic/elasticsearch#20518]
When running Elasticsearch on Cloud we configure the plugins directory external to the installation. This enables us to activate plugins by copying them to an external directory when the container starts. This is required because all plugins are installed when building the docker image. Installing plugins at boot time is not an option as the download process is too error prone and slow for that.

Part of https://github.com/elastic/elasticsearch/pull/18594 made the plugins path hard coded to be relative to the home path and the home path setting cannot be configured as the the boot script resolves it relative to location of the install.

**Comment by jasontedor** [comment]
We discussed this during Fix-it-Friday and agreed that the built-in installation procedure should be followed here to install plugins into the plugins directory.
