### ISSUE TITLE
Strange results when querying nested objects on multiple paths

### ISSUE THREAD

**Issue by SergeyBondarenko** [elastic/elasticsearch#20519]
**Elasticsearch version**: 2.3.3
**Plugins installed**: no plugin
**JVM version**: 1.8.0_91
**OS version**: Linux version 3.19.0-56-generic (Ubuntu 4.8.2-19ubuntu1)

**Description of the problem including expected versus actual behavior**:

I get strange results when I query nested objects on multiple paths. I want to search for all `female` with `dementia`. And there are matched patients among the results. But I also get other diagnoses I'm not looking for, the diagnoses related to these patients.
 
For example, I also get the following diagnoses despite the fact that I looked only for `dementia`.

 - Mental disorder, not otherwise specified 
 - Essential (primary) hypertension

Why is that? 
I want to get **only** `female` with `dementia` and don't want other diagnoses.

`Client_Demographic_Details` contains one document per patient. `Diagnosis` contains multiple documents per patient. The ultimate goal is to index my whole data from PostgreSQL DB (72 tables, over 1600 columns in total) into Elasticsearch. 

**Steps to reproduce**:

 1. **Mapping.**
    {
      "denorm1" : {
        "aliases" : { },
        "mappings" : {
          "Patient" : {
            "properties" : {
              "Client_Demographic_Details" : {
                "type" : "nested",
                "properties" : {
                  "Patient_ID" : {
                    "type" : "long"
                  },
                  "Gender_Description" : {
                    "type" : "string"
                  }
                }
              },
              "Diagnosis" : {
                "type" : "nested",
                "properties" : {
                  "Patient_ID" : {
                    "type" : "long"
                  },
                  "Diagnosis" : {
                    "type" : "string"
                  }
                }
              }
            }
          }
        },
        "settings" : {
          "index" : {
            "creation_date" : "1473974457603",
            "number_of_shards" : "5",
            "number_of_replicas" : "1",
            "uuid" : "Jo9cI4kRQjeWcZ7WMB6ZAw",
            "version" : {
              "created" : "2030399"
            }
          }
        },
        "warmers" : { }
      }
    }
 
 2. **Query.**
    {'query': {
           'bool': {
               'must': [
                   {'nested': {
                       'path': 'Diagnosis',
                       'query': {
                           'bool': {
                               'must': [{'match_phrase': {'Diagnosis.Diagnosis': {'query': "dementia"}}}]
                           }  
                       }
                   }},
                   {'nested': {
                       'path': 'Client_Demographic_Details',
                       'query': {
                           'bool': {
                               'must': [{'match_phrase': {'Client_Demographic_Details.Gender_Description': {'query': "female"}}}]
                           }  
                       }
                   }}
               ]
           }
        }}

 3. **Result.**
   {
      "hits": {
        "hits": [
          {
            "_score": 3.4594634, 
            "_type": "Patient", 
            "_id": "72", 
            "_source": {
              "Client_Demographic_Details": [
                {
                  "Gender_Description": "Female", 
                  "Patient_ID": 72, 
                }
              ], 
              "Diagnosis": [
                {
                  "Diagnosis": "F00.0 -  Dementia in Alzheimer's disease with early onset", 
                  "Patient_ID": 72, 
                }, 
                {
                  "Patient_ID": 72, 
                  "Diagnosis": "F99.X -  Mental disorder, not otherwise specified", 
                }, 
                {
                  "Patient_ID": 72, 
                  "Diagnosis": "I10.X -  Essential (primary) hypertension", 
                }
              ]
            }, 
            "_index": "denorm1"
          }
        ], 
        "total": 6, 
        "max_score": 3.4594634
      }, 
      "_shards": {
        "successful": 5, 
        "failed": 0, 
        "total": 5
      }, 
      "took": 8, 
      "timed_out": false
    }

**Comment by clintongormley** [comment]
All of the clauses you want to match in the same nested document must be in the same nested query (eg nested -> bool -> female+dementia)

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
