### ISSUE TITLE
Documentation: Comment Elasticsearch Indexing Templates

### ISSUE THREAD

**Issue by breml** [elastic/elasticsearch#20513]
**Describe the feature**:

As of https://github.com/elastic/elasticsearch/commit/6f7253c5242e7fb94d959ce291c88f93887e3bde Elasticsearch does have support for C-style comments in indexing templates and mappings. Unfortunately this is nowhere documented in the API reference. Therefore I would like to file a PR, which would add this information to the documentation. Before I change the documentation, I would like to ask, which would be the best place to add this information.

My suggestion would be to add a `NOTE` in https://github.com/elastic/elasticsearch/blob/master/docs/reference/indices/templates.asciidoc.

What do you think?

**Comment by clintongormley** [comment]
Sounds good to me
