### ISSUE TITLE
Definition of metadata operations in Tribe node and Index Settings

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#20525]
[Tribe node documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-tribe.html) is missing some detail about what `tribe.blocks.metadata` encompasses.  Currently stating that "all metadata operations" can be blocked, but doesn't explain what that means.

Similarly, there is a [`index.blocks.metadata` setting](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#dynamic-index-settings), so it seems that metadata blocks are possible at the cluster level and the index level.

A [code search for ClusterBlockLevel.METADATA_READ](https://github.com/elastic/elasticsearch/search?utf8=%E2%9C%93&q=ClusterBlockLevel.METADATA_READ) reveals the following general operations, so it seems that more than just index level metadata is restricted.

Cluster State
Snapshot / Restore
Task Management
Index Aliases
Index Settings
Index Mapping
(etc, etc)

I wonder if it would be beneficial to have a documentation page explaining "Cluster Level Blocks and Index Level Blocks", including read, write, and metadata, and then the tribe docs (and the index module docs) can just link there.

**Comment by javanna** [comment]
Tribe node has been deprecated and removed, closing.
