### ISSUE TITLE
Strange nested type appearance in JavaScript

### ISSUE THREAD

**Issue by darky** [elastic/elasticsearch#20523]
**Elasticsearch version**: 2.3.5

**Plugins installed**: ["lang-javascript"]

**Description of the problem including expected versus actual behavior**:

Script on JavaScript, that works with nested type not properly processing it as array.
For example in this script array not have method `filter`, but have `forEach`, that strange:
```javascript
{
    script: {
        lang: "javascript",
        script: `
            _source.pushes.filter(function(obj) {
                return obj.week === ${weekTimestamp}
            }).length < 5
        `
    }
}
```

For solving problem need manually forcing it to array:
```javascript
{
    script: {
        lang: "javascript",
        script: `
            Array.prototype.slice.call(_source.pushes).filter(function(obj) {
                return obj.week === ${weekTimestamp}
            }).length < 5
        `
    }
}
```

**Comment by clintongormley** [comment]
Hi @darky 

The javascript plugin is deprecated in 5.0 - we won't be releasing any updates to it.
