### ISSUE TITLE
Issues with APT repository?

### ISSUE THREAD

**Issue by sspilleman** [elastic/elasticsearch#20537]
Are there issues with the APT repository?

See 

> apt-get update

 output below:
```
Ign:9 https://packages.elastic.co/elasticsearch/6.x/debian stable InRelease
Ign:10 https://packages.elastic.co/elasticsearch/6.x/debian stable Release
Ign:11 https://packages.elastic.co/elasticsearch/6.x/debian stable/main amd64 Packages
Ign:12 https://packages.elastic.co/elasticsearch/6.x/debian stable/main i386 Packages
Ign:13 https://packages.elastic.co/elasticsearch/6.x/debian stable/main all Packages
Ign:14 https://packages.elastic.co/elasticsearch/6.x/debian stable/main Translation-en_US
Ign:15 https://packages.elastic.co/elasticsearch/6.x/debian stable/main Translation-en
Ign:11 https://packages.elastic.co/elasticsearch/6.x/debian stable/main amd64 Packages
Ign:12 https://packages.elastic.co/elasticsearch/6.x/debian stable/main i386 Packages
Ign:13 https://packages.elastic.co/elasticsearch/6.x/debian stable/main all Packages
Ign:14 https://packages.elastic.co/elasticsearch/6.x/debian stable/main Translation-en_US
Ign:15 https://packages.elastic.co/elasticsearch/6.x/debian stable/main Translation-en
Ign:11 https://packages.elastic.co/elasticsearch/6.x/debian stable/main amd64 Packages
Ign:12 https://packages.elastic.co/elasticsearch/6.x/debian stable/main i386 Packages
Ign:13 https://packages.elastic.co/elasticsearch/6.x/debian stable/main all Packages
Ign:14 https://packages.elastic.co/elasticsearch/6.x/debian stable/main Translation-en_US
Ign:15 https://packages.elastic.co/elasticsearch/6.x/debian stable/main Translation-en
Ign:11 https://packages.elastic.co/elasticsearch/6.x/debian stable/main amd64 Packages
Ign:12 https://packages.elastic.co/elasticsearch/6.x/debian stable/main i386 Packages
Ign:13 https://packages.elastic.co/elasticsearch/6.x/debian stable/main all Packages
Ign:14 https://packages.elastic.co/elasticsearch/6.x/debian stable/main Translation-en_US
Ign:15 https://packages.elastic.co/elasticsearch/6.x/debian stable/main Translation-en
Ign:11 https://packages.elastic.co/elasticsearch/6.x/debian stable/main amd64 Packages
Ign:12 https://packages.elastic.co/elasticsearch/6.x/debian stable/main i386 Packages
Ign:13 https://packages.elastic.co/elasticsearch/6.x/debian stable/main all Packages
Ign:14 https://packages.elastic.co/elasticsearch/6.x/debian stable/main Translation-en_US
Ign:15 https://packages.elastic.co/elasticsearch/6.x/debian stable/main Translation-en
Err:11 https://packages.elastic.co/elasticsearch/6.x/debian stable/main amd64 Packages
  404  Not Found
Ign:12 https://packages.elastic.co/elasticsearch/6.x/debian stable/main i386 Packages
Ign:13 https://packages.elastic.co/elasticsearch/6.x/debian stable/main all Packages
Ign:14 https://packages.elastic.co/elasticsearch/6.x/debian stable/main Translation-en_US
Ign:15 https://packages.elastic.co/elasticsearch/6.x/debian stable/main Translation-en
Reading package lists... Done
W: The repository 'https://packages.elastic.co/elasticsearch/6.x/debian stable Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://packages.elastic.co/elasticsearch/6.x/debian/dists/stable/main/binary-amd64/Packages  404  Not Found
```

**Comment by markwalkom** [comment]
We haven't built packages for 6.X yet sorry.

**Comment by sspilleman** [comment]
I think I looked yesterday and they were there I believe? Did some initial discovery on starting on trying to migrate to ES 5.x yesterday, today I wanted to take the plunge and it's not working anymore....

**Comment by markwalkom** [comment]
Are you after 5.0 or 6.0 though?

**Comment by sspilleman** [comment]
I get the issue now. The [download page](https://www.elastic.co/downloads/elasticsearch) gets you to a page if you click on the "Elasticsearch can also be installed from our RPM or Debian repositories." link. On [that](https://www.elastic.co/guide/en/elasticsearch/reference/master/deb.html) page it is described on how to add the repo.... and the code shows 6.x(!)..... typo on the webpage I think

Now I switched to deb https://packages.elastic.co/elasticsearch/5.x/debian stable main
And its working......

**Comment by markwalkom** [comment]
We just changed master to 6.X which is why.

You should really be using current, but definitely not master :)

**Comment by jsieler** [comment]
Please note that there is also version 5.x with "5.1.0" inside...

**Comment by brenc** [comment]
I got this today too. Using the docs [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html) I added `deb https://artifacts.elastic.co/packages/5.5/apt stable main`. I changed it to `deb https://artifacts.elastic.co/packages/5.x/apt stable main` which seems to work.

**Comment by jasontedor** [comment]
@brenc Thanks for pointing that out, it means the 5.5 docs are broken. We will look into this and get a fix published quickly.

**Comment by jasontedor** [comment]
Thanks again @brenc. I pushed c680c61432614644e62be1712ebfcde1ddc96029 and it will republish soon (usually within thirty minutes).

**Comment by Dalma-TB** [comment]
same issue again with the 5.x definition as above. Also tried 5.6, 5.5, none of them has the Release file.

**Comment by cgough** [comment]
I cannot install any versions of elasticsearch from either 5.x or 6.x, following the instructions provided at:

https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html

```
[admin002.prod:/etc/apt/sources.list.d] root% cat apt-elastic-logstash.list
deb https://artifacts.elastic.co/packages/6.x/apt xenial stable main
```
Running `apt-get` update returns the following error:
```
Reading package lists... Done
W: The repository 'https://artifacts.elastic.co/packages/6.x/apt xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://artifacts.elastic.co/packages/6.x/apt/dists/xenial/stable/binary-amd64/Packages  404  Not Found
```

If I alter this to use the 5.x package, I get the following error:
```
[admin002.prod:/etc/apt/sources.list.d] root% cat apt-elastic-logstash.list
deb https://artifacts.elastic.co/packages/5.x/apt xenial stable main
....
W: The repository 'https://artifacts.elastic.co/packages/5.x/apt xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://artifacts.elastic.co/packages/5.x/apt/dists/xenial/stable/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
So I cannot get any of these repos to work. I am forced to download and install the package manually.

**Comment by markwalkom** [comment]
@cgough you have the wrong repos, per the docs;

```
deb https://artifacts.elastic.co/packages/6.x/apt stable main
```

**Comment by pkaramol** [comment]
I am having the same issues today, `apt update` output below:

```
$ sudo apt update --allow-unauthenticated
Ign:1 https://artifacts.elastic.co/packages/6.x/apt stable InRelease
Err:2 https://artifacts.elastic.co/packages/6.x/apt stable Release
  Received HTTP code 403 from proxy after CONNECT
Hit:3 http://gr.archive.ubuntu.com/ubuntu xenial InRelease
Hit:4 http://gr.archive.ubuntu.com/ubuntu xenial-updates InRelease      
Hit:5 http://security.ubuntu.com/ubuntu xenial-security InRelease       
Hit:6 http://gr.archive.ubuntu.com/ubuntu xenial-backports InRelease    
Reading package lists... Done
E: The repository 'https://artifacts.elastic.co/packages/6.x/apt stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by nicpottier** [comment]
Did you install the apt-https transport?

`sudo apt-get install apt-transport-https`

**Comment by seidler2547** [comment]
You don't only need `apt-transport-https` but also `ca-certificates` installed.

**Comment by iondrugalea** [comment]
I still have this issue, any solutions?
this is my content of /etc/apt/source.list.d/elasticsearch
`deb   https://artifacts.elastic.co/packages/6.x/apt stable main`


apt-get update -o Debug::pkgProblemResolver=true -o Debug::pkgDPkgPM=true
`Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Ign:4 https://artifacts.elastic.co/packages/6.x/apt stable InRelease
Hit:5 http://deb.debian.org/debian stretch Release
Ign:6 https://artifacts.elastic.co/packages/6.x/apt stable Release
Ign:7 https://artifacts.elastic.co/packages/6.x/apt stable/main all Packages
Ign:8 https://artifacts.elastic.co/packages/6.x/apt stable/main amd64 Packages
Ign:9 https://artifacts.elastic.co/packages/6.x/apt stable/main Translation-en
Ign:10 https://artifacts.elastic.co/packages/6.x/apt stable/main Translation-en_US
Ign:7 https://artifacts.elastic.co/packages/6.x/apt stable/main all Packages
Ign:8 https://artifacts.elastic.co/packages/6.x/apt stable/main amd64 Packages
Ign:9 https://artifacts.elastic.co/packages/6.x/apt stable/main Translation-en
Ign:10 https://artifacts.elastic.co/packages/6.x/apt stable/main Translation-en_US
Ign:7 https://artifacts.elastic.co/packages/6.x/apt stable/main all Packages
Ign:8 https://artifacts.elastic.co/packages/6.x/apt stable/main amd64 Packages
Ign:9 https://artifacts.elastic.co/packages/6.x/apt stable/main Translation-en
Ign:10 https://artifacts.elastic.co/packages/6.x/apt stable/main Translation-en_US
Ign:7 https://artifacts.elastic.co/packages/6.x/apt stable/main all Packages
Ign:8 https://artifacts.elastic.co/packages/6.x/apt stable/main amd64 Packages
Ign:9 https://artifacts.elastic.co/packages/6.x/apt stable/main Translation-en
Ign:10 https://artifacts.elastic.co/packages/6.x/apt stable/main Translation-en_US
Hit:11 http://packages.treasuredata.com/3/debian/stretch stretch InRelease
Ign:7 https://artifacts.elastic.co/packages/6.x/apt stable/main all Packages
Ign:8 https://artifacts.elastic.co/packages/6.x/apt stable/main amd64 Packages
Ign:9 https://artifacts.elastic.co/packages/6.x/apt stable/main Translation-en
Ign:10 https://artifacts.elastic.co/packages/6.x/apt stable/main Translation-en_US
Ign:7 https://artifacts.elastic.co/packages/6.x/apt stable/main all Packages
Err:8 https://artifacts.elastic.co/packages/6.x/apt stable/main amd64 Packages

Ign:9 https://artifacts.elastic.co/packages/6.x/apt stable/main Translation-en
Ign:10 https://artifacts.elastic.co/packages/6.x/apt stable/main Translation-en_US
Hit:12 http://repo.percona.com/percona/apt stretch InRelease
Hit:13 http://repo.zabbix.com/zabbix/3.4/debian stretch InRelease
Hit:14 http://repo.percona.com/prel/apt stretch InRelease
Hit:16 http://repo.zabbix.com/zabbix/4.0/debian stretch InRelease
Reading package lists... Done
W: The repository 'https://artifacts.elastic.co/packages/6.x/apt stable Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://artifacts.elastic.co/packages/6.x/apt/dists/stable/main/binary-amd64/Packages
E: Some index files failed to download. They have been ignored, or old ones used instead.`

**Comment by adrian-petcu-rm** [comment]
The issue started to happen since yesterday.
Output of lsb_release -a:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

Output of apt update:
Hit:1 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu bionic-updates InRelease                    
Hit:3 http://eu-central-1.ec2.archive.ubuntu.com/ubuntu bionic-backports InRelease                  
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                                   
Ign:5 https://artifacts.elastic.co/packages/5.x/apt stable InRelease                                
Ign:6 http://apt.datadoghq.com stable InRelease                                                     
Err:7 https://artifacts.elastic.co/packages/5.x/apt stable Release          
  404  Not Found [IP: 34.120.127.130 443]
Hit:8 http://apt.datadoghq.com stable Release                       
Hit:9 https://nginx.org/packages/ubuntu bionic InRelease            
Reading package lists... Done                                       
E: The repository 'https://artifacts.elastic.co/packages/5.x/apt stable Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

Content of /etc/apt/sources.list.d/beats.list:
deb      "https://artifacts.elastic.co/packages/5.x/apt"  stable main

**Comment by tedder** [comment]
@adrian-petcu-rm @paul-sud @iondrugalea  good news, it isn't you. There's a problem on elastic's side. It happens intermittently.

https://discuss.elastic.co/t/artifacts-elastic-co-intermittently-fails-404-no-longer-has-a-release-file/266151

**Comment by iondrugalea** [comment]
hey @adrian-petcu-rm  thanks.
I've solved the issue already
Thanks!
