### ISSUE TITLE
Cant't add to Idea

### ISSUE THREAD

**Issue by helloworldtang** [elastic/elasticsearch#20536]
E:\elasticsearch>gradle -v

------------------------------------------------------------
**Gradle 2.13**-rc-1
------------------------------------------------------------

Build time:   2016-04-06 11:02:11 UTC
Build number: none
Revision:     5d64a8733cfd1545eb11d817a25526cfd1e3bb09

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Windows 7 6.1 amd64

E:\elasticsearch>gradle idea

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\elasticsearch\buildSrc\build.gradle' line: 33

* What went wrong:
A problem occurred evaluating root project 'buildSrc'.
> Gradle **2.13** is required to build elasticsearch

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 2.123 secs

E:\elasticsearch>

**Comment by dadoonet** [comment]
Rc1 is not the final release.
Works well on my side with 2.13

If you need more help please open a discussion on discuss.elastic.co
