### ISSUE TITLE
elasticsearch Create a snapshot repository error.

### ISSUE THREAD

**Issue by Canon88** [elastic/elasticsearch#20541]
When I use ` curl -XPUT 'http://192.168.184.33:9200/_snapshot/elkbak' -d '{"type": "fs","settings": {"location": "/data/elk_bak","compress": true}}'`.
Shows the following error:
`
{"error":{"root_cause":[{"type":"repository_verification_exception","reason":"[elkbak] [AvxdLuwDTGCif9MujDW8mw, 'RemoteTransportException[[logserver-es-02][192.168.184.34:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[elkbak] store location [/data/elk_bak] is not accessible on the node [{logserver-es-02}{AvxdLuwDTGCif9MujDW8mw}{192.168.184.34}{192.168.184.34:9300}{master=true}]]; nested: NotSerializableExceptionWrapper[access_denied_exception: /data/elk_bak/tests-UI5DJFuzRLWs2XuQ2SIcgA/data-AvxdLuwDTGCif9MujDW8mw.dat];']]"}],"type":"repository_verification_exception","reason":"[elkbak] [AvxdLuwDTGCif9MujDW8mw, 'RemoteTransportException[[logserver-es-02][192.168.184.34:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[elkbak] store location [/data/elk_bak] is not accessible on the node [{logserver-es-02}{AvxdLuwDTGCif9MujDW8mw}{192.168.184.34}{192.168.184.34:9300}{master=true}]]; nested: NotSerializableExceptionWrapper[access_denied_exception: /data/elk_bak/tests-UI5DJFuzRLWs2XuQ2SIcgA/data-AvxdLuwDTGCif9MujDW8mw.dat];']]"},"status":500}
`

What is the problem, anybody help me. Thank you!

**Comment by abeyad** [comment]
If you can kindly post any questions on the [discussion](https://discuss.elastic.co) forum.  We reserve Github for issues and feature requests. 

It looks like you don't have `/data/elk_bak` mounted on the `logserver-es-02` node (or otherwise, there some permissions issues with the directory).  You can ask on the discussion forum if you're still stuck.

**Comment by Canon88** [comment]
Thank you for your reply.
This is my configuration, I think I have configured.
**logserver-es-01**
```
cluster.name: my_logsearch
node.name: logserver-es-01
node.master: true
node.data: true
index.number_of_shards: 5
index.number_of_replicas: 1
path.logs: "/data/logs/elasticsearch"
path.data: "/data/elasticsearch"
network.host: 192.168.184.33
http.port: 9200
bootstrap.mlockall: true
transport.tcp.compress: true

discovery.zen.fd.connect_on_network_disconnect : true
discovery.zen.initial_ping_timeout : 10s
discovery.zen.fd.ping_interval : 2s
discovery.zen.fd.ping_retries  : 10

network.tcp.keep_alive : true
indices.recovery.max_size_per_sec: 0
indices.recovery.concurrent_streams: 5
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.timeout: 3s
discovery.zen.ping.unicast.hosts: ["logserver-es-01","logserver-es-02"]
path.repo: ["/data/elk_bak"]
```
**logserver-es-02**
```
node.name: logserver-es-02
....
path.repo: ["/data/elk_bak"]
```

**Comment by abeyad** [comment]
That's your Elasticsearch configuration, which looks fine.  The error message indicates that you do not have anything mounted on `/data/elk_bak` for the node to access.  It is a configuration issue on your machine.  If you do an `ls` on `/data/elk_bak`, do you get anything?

As mentioned, if you are still stuck after trying to get your mounts and permissions correct, please post your question on the discussion forum.  Thank you.
