### ISSUE TITLE
Histogram Aggregation: With minimum doc count and extended bounds (Not filtering results)

### ISSUE THREAD

**Issue by marklombardi** [elastic/elasticsearch#20543]
**Elasticsearch version**: 2.3.3

**Plugins installed**: [Sense, Kibana]

**JVM version**: build 25.101-b13

**OS version**: Windows 10

**Description of the problem including expected versus actual behavior**:
Running a Histogram Aggregation with minimum doc count and extended bounds and range filter does not filter the results as described in the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html#search-aggregations-bucket-histogram-aggregation-extended-bounds).

"_Note that (as the name suggest) extended_bounds is not filtering buckets. Meaning, if the extended_bounds.min is higher than the values extracted from the documents, the documents will still dictate what the first bucket will be (and the same goes for the extended_bounds.max and the last bucket). **For filtering buckets, one should nest the histogram aggregation under a range filter aggregation with the appropriate from/to settings_**."

**Steps to reproduce**:
 1. Refer to the following [discussion](https://discuss.elastic.co/t/histogram-aggregation-with-minimum-doc-count-and-extended-bounds/58495): 

**Provide logs (if relevant)**: N/A

**Comment by clintongormley** [comment]
@marklombardi please provide an actual recreation of the problem, and explain what the problem is.  I can't follow what you're saying in the discuss issue, and screenshots do not help at all.

From the little I can understand, it sounds like you are not writing the correct aggs, rather than there being a bug. So I suggest you continue this conversation in discuss, but provide the info I mention above.

**Comment by marklombardi** [comment]
@clintongormley, sorry I thought the first screenshot was pretty self evident. The date range filters are specified as 2016-08-01 to 2017-08-02, however the buckets returned in the aggregation range from 2015-08-02 thru 2016-08-02 (extended-bounds +/- 1 yr). 

The bug is the date range filter in the query or sub-aggregation does not filter the results (with extended bounds set to +/- 1 yr) as specified in the documentation. Only 2 days worth of data should be returned instead of 365.

**Comment by clintongormley** [comment]
@marklombardi as I asked above, please provide a curl recreation of the problem, including the docs you are indexing.  eg if you have multiple values in your date field and one falls within the range and the other outside the range then you'll get exactly what you're describing.

but continue this conversation in the forum, not here.  this doesn't sound like a bug to me.  if it does turn out to be a bug then we can open a new ticket with the recreation

**Comment by DeeeFOX** [comment]
@clintongormley fix in any version?
