### ISSUE TITLE
Delete by Query 

### ISSUE THREAD

**Issue by shahidash** [elastic/elasticsearch#20551]
Hi Folks

Using elasticsearch-2.2.0. I am using the following query

curl -XDELETE http://127.0.0.1:9200/index -d '{"query": {"bool": {"filter": [{"range": {"timestamp": {"gte": "2016-01-01", "lte": "now"}}}], "must": [{"term": {"org_id": 7}}, {"term": {"source": "abc"}}, {"term": {"e_id": "7_1"}}]}}, "size": 100, "from": 0, "_source": []}'

When i do GET method it only gets one record/document. While performing the DELETE method . it delete all documents as well as index(with mapping). Have installed deletebyquery plugin

**Comment by jpountz** [comment]
This is because elasticsearch interpretes the above request as an index deletion. To delete documents, you need to call the `_query` endpoint.

```
curl -XDELETE http://127.0.0.1:9200/index/_query -d '{"query": {"bool": {"filter": [{"range": {"timestamp": {"gte": "2016-01-01", "lte": "now"}}}], "must": [{"term": {"org_id": 7}}, {"term": {"source": "abc"}}, {"term": {"e_id": "7_1"}}]}}, "size": 100, "from": 0, "_source": []}'
```
