### ISSUE TITLE
Incorrect highlight when using span_or query in span_near query

### ISSUE THREAD

**Issue by alwag85** [elastic/elasticsearch#20555]
**Elasticsearch version**: 1.7.1-2.2.1

**Plugins installed**: []

**JVM version**: 1.8

**OS version**: Windows Server 2008 R2

**Description of the problem including expected versus actual behavior**: I have incorrect highlight when I use span_or query in span_near query. 
For example: 
I have the text: "Obama States President".
If I use simple query string: "`President NEAR/5 (\"United States\" | Obama)`" then I have correct result:  "`<em>Obama</em> States <em>President</em>`".
If I use equivalent query: 
```
{
	"span_near":{
		"clauses":[
			{
				"span_term":{
					"Text":"President"
				}
			},
			{
				"span_or":{
					"clauses":[
					{
						"span_near":{
							"clauses":[
								{
								"span_term":{
									"Text":"United"
								}
								},
								{
								"span_term":{
									"Text":"States"
								}
								}
							],
							"slop":0,
							"in_order":true
						}
					},
					{
						"span_term":{
							"Text":"Obama"
						}
					}
					]
				}
			}
		],
	"slop":5,
	"in_order":false
	}
}
```
then I have wrong result: "`<em>Obama</em> <em>States</em> <em>President</em>`".

**Steps to reproduce**:
Steps to reproduce you can see here: [https://discuss.elastic.co/t/incorrect-highlight-when-using-span-or-query-in-span-near-query/50340](https://discuss.elastic.co/t/incorrect-highlight-when-using-span-or-query-in-span-near-query/50340)

**Comment by jimferenczi** [comment]
This is a limitation of the highlighter when it deals with SpanOr query or repeated terms in a span query. The problem here is that the highlighter does not try to extract the part of the span query that matches the text but rather checks which terms inside the span query could appear in the span. This leads to false positive like in the provided example. I think it's possible to fix but it would be in Lucene land.

**Comment by clintongormley** [comment]
thanks @jimferenczi. @alwag85 I'd consider opening an issue in Lucene, to see if anybody is interested in fixing it.
