### ISSUE TITLE
Upgrade geoip2 to 2.8.0

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#20563]
As seen in https://github.com/elastic/elasticsearch/issues/20559#issuecomment-248049166, version 2.8.0 has been released recently: http://maxmind.github.io/GeoIP2-java/

Change log says:

## 2.8.0 (2016-09-15)

* All changes included in 2.8.0-rc1.
* Updated documentation to clarify what the accuracy radius refers to.

## 2.8.0-rc1 (2016-06-20)

* IMPORTANT: Java 7 is now required. If you need Java 6 support, please continue using 2.7.0 or earlier.
* This library no longer uses Google HTTP Client. It now directly uses Apache HttpClient.
* WebServiceClient now implements Closeable. A pool of connections will be kept alive to be used across requests. To ensure all connections are closed when the object goes out of scope, call close() or use the try-with-resource statement as appropriate.
* Setting of a proxy for the WebServiceClient is now supported by the proxy(Proxy) builder method.
* Updated documentation to reflect that the accuracy radius is now included in City.
* Updated dependencies.

**Comment by s1monw** [comment]
nothing to discuss - lets upgrade
