### ISSUE TITLE
Avoid unnecessary creation of prefix loggers in LoggerInfoStream

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#20570]
Today when a caller requests a prefix logger, we create a new one for every invocation. This should not be a problem if the caller holds on to the logger as is usually the case. Not every caller does this (e.g., `LoggerInfoStream`) and this can be problematic in the case of heavy indexing with multiple threads as these creations end up contending over a synchronized block.

**Comment by nik9000** [comment]
Can we make all the callers hold onto their prefix logger?
