### ISSUE TITLE
Improving docs on Phrase Suggester

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#20572]
There appears to be a few unclear items in the [phrase suggester documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-phrase.html):
1.   Direct Generator - By default, does an instance of DG run without configuration?  If so, what are the default parameters.  In particular, what is the default "field" parameter.
2.  How does the "field" parameter of the Direct Generator relate to the "field" parameter of the _phrase_ configuration.
3.  What happens to _collate_ when multiple shards contain the same suggestion?
4.  Does phrase suggester require shingles or ngrams?  If so:
   1. Which is required and for what reasons?
   2. Why does it continue to work without these mappings?

**Comment by nik9000** [comment]
I did *some* of this work in [master](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-suggesters-phrase.html) already. It contains a working example with shingles.

**Comment by nik9000** [comment]
I suppose I can take this if no one else wants it.

**Comment by PhaedrusTheGreek** [comment]
I know @areek has done a bit of work

**Comment by andyb-elastic** [comment]
@elastic/es-search-aggs

**Comment by jrodewig** [comment]
[docs issue triage]
