### ISSUE TITLE
Query_String query inclusive date range is not "inclusive"

### ISSUE THREAD

**Issue by WojciechLuczkow** [elastic/elasticsearch#20579]
**Elasticsearch version**: 2.4.0

**Plugins installed**: []

**JVM version**: Java HotSpot 64-bit Server VM (build 25.65-b01, mixed mode)

**OS version**:  Windows 7 SP 1

**Description of the problem including expected versus actual behavior**:

When searching date field using query_string query and providing timestamp like:

[2016-09-13 TO 2016-09-20] the entry with timestamp field being 2016-09-20T08 is not matched - same with curly brackets i.e. {2016-09-13 TO 2016-09-20} 
[2016-09-13 TO 2016-09-20T09]  works (but [2016-09-13 TO 2016-09-20T08] not)

I have just migrated from 1.7.5 to 2.4.0 and in 1.7.5 above query was returning correct, in my understanding, results.

**Steps to reproduce**:
 1. Perform search using query_string query for inclusive date range [yyyy-mm-dd TO yyyy-mm-dd] and provide date with day but without hour

**Comment by jpountz** [comment]
I can reproduce on master with the following recreation

```
PUT test/test/1
{
  "date": "2016-09-07T14:55:30Z"
}

PUT test/test/2
{
  "date": "2016-09-09T11:07:59Z"
}

GET test/_search
{
  "query": {
    "query_string": {
      "default_field": "date",
      "query": "[2016-09-07 TO 2016-09-09]"
    }
  }
}
```

Only document 1 matches the query, not 2.

**Comment by jpountz** [comment]
However things still work if the rounding is explicit:

```
GET test/_search
{
  "query": {
    "query_string": {
      "default_field": "date",
      "query": "[2016-09-07 TO 2016-09-09||/d]"
    }
  }
}
```
