### ISSUE TITLE
minimum_should_match ignored for match boolean queries because Lucene setDisableCoord(true)

### ISSUE THREAD

**Issue by vaughnd** [elastic/elasticsearch#20581]
**Elasticsearch version**: 2.4

**Description of the problem including expected versus actual behavior**:

We have a sourceUrl compound field with a custom analyzer for the sourceUrl.pathName component. The idea is that we can run a query to get all urls in a path, e.g. example.com/path/here brings back everything under example.com/path/here.*. The following code worked fine in ES 1.7, but in ES 2.4 it doesn't. Lucene 5.5.2 always sets disable_coords:true when using a match query of type boolean, which makes ES stop applying the minimum_should_match parameter. The behaviour has changed in the Lucene 6.x branch, so I'm not sure if this is a bug in Lucene 5.5.2 that will get patched or if ES is doing something wrong. Apologies if I should be reporting this to the Lucene project instead. Any guidance will be appreciated.

**Index settings and mappings**:

```
{
  "settings": {
    "index": {
      "analysis": {
        "char_filter": {
          "drop_trailing_slash": {
            "pattern": "/$",
            "type": "pattern_replace",
            "replacement": ""
          },
          "path": {
            "type": "pattern_replace",
            "pattern": "^(.*://)?([^/]*)((/[^?]*?)?(/([^/]*.html?)?)?)(\?.*)?$",
            "replacement": "$3"
          },
          "drop_leading_slash": {
            "type": "pattern_replace",
            "pattern": "^/",
            "replacement": ""
          },
        },
        "analyzer": {
          "pathName": {
            "filter": "lowercase",
            "char_filter": [
              "path",
              "drop_leading_slash",
              "drop_trailing_slash"
            ],
            "type": "custom",
            "tokenizer": "pathName"
          },
        },
        "tokenizer": {
          "pathName": {
            "type": "path_hierarchy",
            "reverse": "false",
            "delimiter": "/"
          },
        }
      },        
    }
  },
  "mappings": {
  "page": {
    "properties": {
      "sourceUrl": {
      "index": "no",
      "type": "string",
      "fields": {
        "pathName": {
          "analyzer": "pathName",
          "type": "string"
        },
        "raw": {
          "index": "not_analyzed",
          "type": "string"
        }
      }
    }
  }
}
```

**Query that fails by bringing back too many results**:

```
{"query": {
    "bool" : {
      "filter" : {
        "match" : {
          "sourceUrl.pathName" : {
            "query" : "http://www.animalfactguide.com/category/animal-news/page/6/",
            "type" : "boolean",
            "minimum_should_match" : "100%"
          }
        }
      }
    }
  }
}
```

**Query I'm forced to use to dodge the broken code path and get properly filtered results**:

```
{
  "query": {
    "bool" : {
      "filter" : {
        "match" : {
          "sourceUrl.pathName" : {
            "query" : "http://www.animalfactguide.com/category/animal-news/page/",
            "type" : "boolean",
            "minimum_should_match" : "100%",
"cutoff_frequency": 0.99
          }
        }
      }
    }
  }
}
```

The code path that seems broken to me:

Lucene always setDisableCoords(true) here:
https://github.com/apache/lucene-solr/blob/releases/lucene-solr/5.5.2/lucene/core/src/java/org/apache/lucene/util/QueryBuilder.java#L284

Which stops ES 2.4 from applying minimum_should_match:
https://github.com/elastic/elasticsearch/blob/v2.4.0/core/src/main/java/org/elasticsearch/index/query/MatchQueryParser.java#L174

There's no other way to get past this other than setting a cutoff_frequency which sets a commonTermsCutoff = 0.5 and follows the createCommonTermsQuery code path here:
https://github.com/elastic/elasticsearch/blob/v2.4.0/core/src/main/java/org/elasticsearch/index/search/MatchQuery.java#L176

**Comment by clintongormley** [comment]
@jimferenczi could you take a look at this please?

**Comment by jimferenczi** [comment]
@vaughnd you need to define a query analyzer for your `sourceUrl.pathName`. The `path_hierarchy` tokenizer should be used at indexing time but at query time you need to define another analyzer that would use your char filters and a *keyword* tokenizer:

````
"analyzer": {
          "pathName_query": {
            "filter": "lowercase",
            "char_filter": [
              "path",
              "drop_leading_slash",
              "drop_trailing_slash"
            ],
            "type": "custom",
            "tokenizer": "keyword"
          },
        },
````

The `keyword` tokenizer is mandatory since you want to match only one term, for instance the query: "http://www.animalfactguide.com/category/animal-news/page/" will match the term "www.animalfactguide.com/category/animal-news/page/6" and that's all you want.
 That's how the path_hierarchy tokenizer is meant to be used; extra work at indexing time in order to speed up queries.

**Comment by vaughnd** [comment]
Ahh, thanks Jim!
