### ISSUE TITLE
Update heap size documentation

### ISSUE THREAD

**Issue by andrewkroh** [elastic/elasticsearch#20587]
The [heap size documentation](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/heap-size.html) for 5.x should be updated to reflect that the min and max defaults are now the same at 2GB. (Changed here: https://github.com/elastic/elasticsearch/commit/743b2ed1b2c7166d30dd3dd1721120bd9738a172)

Also I think the jvm.options example [lines](https://github.com/elastic/elasticsearch/blame/5.0/docs/reference/setup/sysconfig/heap_size.asciidoc#L51-L52) each need a leading `-` (dash).

**Comment by clintongormley** [comment]
thanks @andrewkroh - fixed
