### ISSUE TITLE
rpm package pre install script creates user elasticsearch with non existent home directory

### ISSUE THREAD

**Issue by JalehD** [elastic/elasticsearch#20599]
**Elasticsearch version**: 2.4 & 2.3

The script creates user `elasticsearch` with no home (`useradd -M ...`). That's fine, but it also miss `-d` option, so default `/home/elasticsearch` is used in `/etc/passwd`. It breaks f.e. cron tasks for this user: 

`#tail /var/log/cron ` 
`Sep 19 19:00:01 ip-10-253-16-101 CROND[2806]: (CRON) ERROR chdir failed (/home/elasticsearch): No such file or directory `

 Suggested Solution by the user: extend the `useradd` command by `-d /usr/share/elasticsearch`

**Comment by jasontedor** [comment]
Duplicates #14453
