### ISSUE TITLE
Highlighter - long /double field search highlights doesnt work

### ISSUE THREAD

**Issue by culiangfanzi** [elastic/elasticsearch#20606]
part of index mapping:
 "request_time" : {
            "type" : "float",
            "index" : "analyzed",
            "doc_values" : true
          },
          "response_time" : {
            "type" : "float",
            "index" : "analyzed",
            "doc_values" : true
          }
the response_time filed worked, but highlighter did not work, can anyone solve this problem ??

**Comment by clintongormley** [comment]
Highlighters are for text, not numeric fields.  If you need to highlight numbers then you need to index them as strings

**Comment by culiangfanzi** [comment]
excuse me.
could you kindly tell me why not for numeric fields?

**Comment by clintongormley** [comment]
highlighting requires term positions and offsets, which are only used for text.  numbers have a completely different index format which is optimised for numeric search
