### ISSUE TITLE
parent/child relation not working correctly

### ISSUE THREAD

**Issue by fesnault** [elastic/elasticsearch#20619]
**Elasticsearch version**: 2.1.2

**Plugins installed**: [kopf]

**JVM version**: Oracle JDK 1.7

**OS version**: Ubuntu 14 & OS X 10.11.6

**Description of the problem including expected versus actual behavior**:

In an index with documents linked by a parent/child relationship, I have a strange behaviour while trying to get/filter documents on their parents or on their children.

My use case is I have some documents containing fields (subject, content, creator, creation_date, status (draft, reviewed,...) indexed in elasticsearch. For some fields of the documents (for example its status), I also have indexed the history of changes (for example the change from draft to review, the time spent in the oldest status, the person who changed the status, when,...). 

Documents and History items are indexed in two different types (doc_mapping and doc_mapping_history) of the same index.

I'm trying to get the number of status change in one document (simplified version of my real request). So I try to do like this :

```
GET myindex/doc_mapping/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "document_key": "MYDOC803"
          }
        },
        {
          "range": {
            "created": {
              "gte": "01/06/2016",
              "lte": "30/06/2016",
              "format": "dd/MM/yyyy"
            }
          }
        }
      ]
    }
  }
}
```

This gives me my expected documents, no problem. But if I add this, i have no result **or only some results** (yes it's strange, some work, some do not) :

```
GET myindex/doc_mapping/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "document_key": "MYDOC803"
          }
        },
        {
          "range": {
            "created": {
              "gte": "01/06/2016",
              "lte": "30/06/2016",
              "format": "dd/MM/yyyy"
            }
          }
        },
        {
          "has_child": {
            "type": "doc_mapping_history",
            "query": {
              "match_all": {}
            }
          }
        }
      ]
    }
  }
}
```

The strange thing is that the child documents **are** present in the index. I can see them if i execute this : 

```
GET myindex/doc_mapping_history/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "document": "MYDOC803"
          }
        },
        {
          "term": {
            "field": "status"
          }
        }
      ]
    }
  }
}
```

I have the expected results. But if I had this, then no result comes back :

```
GET myindex/doc_mapping_history/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "document": "MYDOC803"
          }
        },
        {
          "term": {
            "field": "status"
          }
        },
        {
          "has_parent": {
            "type": "doc_mapping",
            "query": {
              "match_all": {}
            }
          }
        }
      ]
    }
  }
}
```

Is there a bug in ES 2.1.2 about child/parent management, which could lead to some documents being correctly processed/indexed/retrieved, or am I missing something ?

I must add that I tried this on two environment : my dev environment and the production-ready environement. Problem is exactly the same, the same documents fail, the same documents work.
I don't see any error in the logs during indexing or during querying, either in ES logs or in my app logs. Note that I now try my queries directly in kopf plugin, and the result is the same, so my app is not responsible. 

So the problem either comes from my mapping, my indexing, my querying, or from ES itself.
Do anyone have an idea?

**Comment by martijnvg** [comment]
@fesnault I'm unsure what is going wrong here. Is it possible to provide a more isolated reproduction of the issue? (with the mappings, index requests for both parent and childs and the searches). It is important to know if for example the parent ids are set correctly on the index requests.

**Comment by fesnault** [comment]
Hi @martijnvg and thanks for replying.

It's actually difficult to create a reproductible environment.
I tried creating the same situation, with similar mappings and documents, but the query works correctly in the testing index.
I also tried to create another index and inject the same mappings as in the real one. I then injected three document, one parent and two children, taken directly from production.
But here too, my query works.

As an example, here is a child document from production (filtered out) :
```
{
  "_index": "filtered",
  "_type": "doc_mapping_history",
  "_id": "194855",
  "_score": 6.254041,
  "_routing": "PID-803",
  "_parent": "PID-803",
  "_source": {
    "issuetype": "Epic",
    "issue": "PID-803",
    "created": "2016-06-22T07:53:45.709Z",
    "duration": 39709,
    "field": "status",
    "group_id": 120998,
    "change_id": 194855,
    "issue_created": "2016-06-22T07:53:06.000Z",
    "old_value": "[10007] Draft",
    "user": "fesnault",
    "new_value": "[10503] Assessing Scope"
  }
}
```

And here is the parent document :
```
{
  "_index": "filtered",
  "_type": "doc_mapping",
  "_id": "PID-803",
  "_version": 2,
  "_routing": "fesnault",
  "_parent": "fesnault",
  "found": true,
  "_source": {
    "summary": "Filtered",
    "issuetype": "Epic",
    "issue_id": 22245,
    "project_key": "PID",
    "created": "2016-06-22T07:53:06.000Z",
    "description": "Filtered",
    "key": "PID-803",
    "status": "Assessing Scope"
    }
}
```

Note that the parent document also has a parent himself.

About the way they are indexed. This is done by a software. I added some logs which showed me that the children documents were indexed with a parent, so the parent parameter is not forgotten. Here is the line of code doing this :
```
indexResponse = client.prepareIndex(indexName, getTypeName(mappingTitle), (changeValues.get("change_id")).toString()).setSource(changeValues).setParent(parentId).execute().actionGet();
```

Is there anyway I could do to get more information? Some special logging or query ? Btw no error shows up in the logs, just no result.

**Comment by clintongormley** [comment]
You have grandparents?  In which case, i think you indexed the grandchildren with `?parent={parentid}` but without `&routing={grandparentid}`.  The parent goes to the same shard as the grandparent, so the grandchildren need to know what shard that is, and can't deduce it just from the parent's ID

**Comment by fesnault** [comment]
Hi @clintongormley ,
Great, I modified my indexing code to add the grandparent id to the grandchildren indexing, and it works perfectly fine, my query with has_parent restriction returns the expected results.

Thanks a lot !

I learned something about indexing documents with parents and grandparents.
