### ISSUE TITLE
Investigate reusability of testing code for equals() / hashCode()

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#20629]
For the query refactoring we started testing equals()/hashCode() contracts for the query builders in a central abstract [base test](https://github.com/elastic/elasticsearch/blob/master/test/framework/src/main/java/org/elasticsearch/test/AbstractQueryTestCase.java#L725), assuming the test can use some helper methods to e.g. make deep copies of objects via serialization. We have similar tests e.g. in `BaseAggregationTestCase` and for several other parts of the search request (e.g. the SuggestBuilderTests via the abstract WritableTestCase, AbstractShapeBuilderTestCase). We also started doing those kind of tests in a helper class now in the rank_eval module, which triggered the [discussion](https://github.com/elastic/elasticsearch/pull/20497#discussion_r79830341) if we should make an effort to centralize this.

While putting this kind of basic equals/hashCode tests into abstract superclasses works for test of similar classes (e.g. all queries), it is a bit tricky to generalize this easily and makes the test inheritance structure hard and tests sometimes difficult to read. On the other hand, having this kind of tests clearly documented in some central test utility class would make reusing it more straight forward and avoid the duplication we have today. I'm leaning towards not inheriting this kind of testing code but rather have some utility function somewhere that e.g. takes the original object, some function that returns a deep copy and a function that returns a mutation (an instance different in only one aspect) as arguments and does all the assertions necessary. This way it can be used by different tests without the burden of having to inherit various levels of abstract base test classes.

**Comment by nik9000** [comment]
On problem with just using equals is that it can be difficult to find the
difference. I'm not really sure what to do about that though, but I figure
this is a place to bring it up.

**Comment by javanna** [comment]
++ on this I wondered the same as well looking at the repetition. Most of it can be eliminated I think.

> On problem with just using equals is that it can be difficult to find the
difference. I'm not really sure what to do about that though, but I figure
this is a place to bring it up.

Very true, the tests that we have now around equals and hashcode are not perfect. Testing that something is not equal to something else requires writing code to change some original instance of the object. In many cases we don't do it and we only verify that unomodified objects remain equal (and hashcode is the same) even after serialization, that is the part that can be generified.

**Comment by cbuescher** [comment]
@nik9000 @javanna I opened a PR for this, there are a lot of tests that can use this. It works also for cases where we don't check that a modified object is not equal to its original, in that case this part of the test is skipped. However, I left TODOs where we should add this to the existing test (basically all QueryBuilders, Aggregations etc...)
