### ISSUE TITLE
ReIndexRethrottle requests_per_second cannot be 0

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch#20625]
**Elasticsearch version**: 2.4.0

Related to:

https://github.com/elastic/elasticsearch/pull/18791
https://github.com/elastic/elasticsearch/pull/19101

Reindex rethrottle has been backported to Elasticsearch 2.4.0. [Per the rest api spec description](https://github.com/elastic/elasticsearch/blob/v2.4.0/rest-api-spec/src/main/resources/rest-api-spec/api/reindex_rethrottle.json), `requests_per_second` can be `0` or `"unlimited"` to represent no throttle, or any float greater than 0.

However, Elasticsearch 2.4.0 does not accept `0` as a value for `requests_per_second`. Response returned is

```
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=UTF-8
Content-Length: 386

{
  "error" : {
    "root_cause" : [ {
      "type" : "illegal_argument_exception",
      "reason" : "[requests_per_second] must be a float greater than 0. Use \"unlimited\" to disable throttling."
    } ],
    "type" : "illegal_argument_exception",
    "reason" : "[requests_per_second] must be a float greater than 0. Use \"unlimited\" to disable throttling."
  },
  "status" : 400
}
```

I wasn't sure what the consensus for a change would be here; 
- change the implementation to allow `0`, or align with 5.0 and remove `"unlimited"` and accept `-1` for no throttle
- change documentation to indicate float greater than 0 or `"unlimited"`

**Comment by nik9000** [comment]
Is https://github.com/elastic/elasticsearch/pull/19101 good enough?

**Comment by nik9000** [comment]
> remove "unlimited" and accept -1 for no throttle

That is what 5.0 does, I blieve.

**Comment by russcam** [comment]
#19101 backported to 2.x would be good; it would align with 5.0

**Comment by russcam** [comment]
Thinking about it further, could we support both `"unlimited"` and `-1`? Continuing to support `"unlimited"` as input would be for backwards compatibility; The .NET client exposes `requests_per_second` as a property, `RequestsPerSecond` of type `float` and _"shepherds"_ `float.PositiveInfinity` into sending `"unlimited"` in the request and likewise, converting `"unlimited"` in the response back into `float.PositiveInfinity`.

I could see a situation where, if `"unlimited"` were altogether removed in favour of `-1`, then a 2.x version of the .NET client that I'm looking to release shortly would start to break for reindex rethrottle if a user upgraded from Elasticsearch 2.4.0 to the next 2.x version.

/cc @elastic/microsoft

**Comment by nik9000** [comment]
I'm not sure that supporting `-1` in 2.x is really all that useful because I don't expect us to have a 2.5.0 at all. Without something like that I'm not sure how many users we can really expect to have a version of Elasticsearch that supports `-1`.

**Comment by russcam** [comment]
In that case, I can see a couple of ways forward

1. remove `0` as an option for no throttle in the documentation
2. allow `0` as an option for no throttle in the implementation

Happy to submit a PR for either 😄

**Comment by nik9000** [comment]
Zap it from the docs! If you are willing to open a pr I'll certainly review
it.

On Sep 22, 2016 12:31 AM, "Russ Cam" <notifications@github.com> wrote:

In that case, I can see a couple of ways forward

   1. remove 0 as an option for no throttle in the documentation
   2. allow 0 as an option for no throttle in the implementation

Happy to submit a PR for either 😄

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/elastic/elasticsearch/issues/20625#issuecomment-248808470>,
or mute the thread

**Comment by russcam** [comment]
Thanks @nik9000, done! #20628

**Comment by colings86** [comment]
@russcam can this be closed now or is there more work to be done here?

**Comment by russcam** [comment]
@colings86 It just needs to be merged. Happy to pull the merge trigger if it looks good to you?

**Comment by Sue-Gallagher** [comment]
Fixed per Deb Adair 3/20/2018
