### ISSUE TITLE
Implement an "automatic" way to parallelize reindex and friends using sliced scroll

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#20624]
Since reindex and friends work well with sliced scroll we can implement a way to parallelize reindex using sliced scroll that looks like this:

```
  curl -XPOST 'localhost:9200/_reindex?workers=5&filter_path=took' -d'{
    "source": {
      "index": "source4"
    },
    "dest": {
      "index": "dest"
    },
    "script": {
      "inline": "ctx._id = params.i + '"'.'"' + ctx._id",
      "params": {
        "i": '$i'
      }
    }
  }'
```

The new bit of the above is `workers=5`.

I prototyped this locally this afternoon and saw this kind of performance when reindexing a million small documents on a fairly beefy desktop:

```
workers:took
01:{"took":19204}
02:{"took":13485}
03:{"took":10487}
04:{"took":10042}
05:{"took":7211}
06:{"took":10428}
07:{"took":20285}
08:{"took":19518}
09:{"took":18893}
10:{"took":15245}
11:{"took":16474}
12:{"took":16016}
13:{"took":15267}
14:{"took":16331}
15:{"took":14146}
16:{"took":14173}
17:{"took":13339}
18:{"took":14083}
19:{"took":12795}
20:{"took":11463}
```

Using 5 workers nets me a 62% improvement which feels pretty substantial. I'm sure my quick and dirty bash scripts don't constitute proper performance testing. And prototypes. And these were trivial documents with a trivial analysis pipeline and no doc values fields or anything. But, even still, this seems worth doing. I imagine you'd get much more performance improvement for more complex indexing.

The "fun" parts of making this work is handling stuff like status reporting and rethrottling and cancellation. Cancelation should come "for free" from the task system. The rest will take a bit of work to get right.

**Comment by jpountz** [comment]
> 05:{"took":7211}

Do you think it is noise or due to the fact the source index has 5 shards?

**Comment by nik9000** [comment]
I think it is because the source has five shards, yeah. I think the bottleneck for *this* reindex job is reading rather than writing. If it were otherwise then we'd see something more linear. I suspect that reading being the bottleneck is only true if the analysis is simple and we don't use doc values and things. My documents for this test were just `{"test": "test"}`.

**Comment by jimferenczi** [comment]
The results of your test are strange. On my laptop I am seeing linear performance depending on the number of threads. One thing that disturbs me when looking at your result is that the big speedup is only seen when the number of workers match the number of shards. I think this is misleading, using the same number of shards to set the number of workers should be the fastest but the difference with workers=4 or workers=6 (where num shards equals 5) should not be that big. 
I tried your test with only the read part (no reindexing) and I have 6s with workers=1, 4s with workers=2, 3s with workers=3, 2.5s with workers=4, 2s with workers=5 and 2s with workers=6.
If I test with more fields than just  ```{"test": "test"}``` I can see a 3x to 4x improvement with workers>3.

**Comment by nik9000** [comment]
@jimferenczi: Its been a while since I ran that test. I'll crack it open again soon.

I think we should bounce the conversation over to https://github.com/elastic/elasticsearch/pull/20767 because that is the implementation I'm looking at.

**Comment by geekpete** [comment]
Can this also be used in delete-by-query since it's now limited by a serial scroll as well and might have performance boosted in the very same way by parallelising the scroll by slicing.

**Comment by nik9000** [comment]
Yes. It'll be for reindex, update by query, and delete by query.
