### ISSUE TITLE
ES_HEAP_SIZE takes no effect!!!!

### ISSUE THREAD

**Issue by leaxoy** [elastic/elasticsearch#20636]
I had set `ES_HEAP_SIZE` in `/usr/share/elasticsearch/bin/elasticsearch.in.sh`, `/etc/sysconfig/elasticserch` to 8g. And set `LimitMEMLOCK=infinity` in `/usr/lib/systemd/system/elasticsearch.service`. And `MAX_LOCKED_MEMORY=unlimited` in `/etc/sysconfig/elasticsearch`.
At first, it's seems no problem.  But about a day later, when i use top, i find elasticsearch use 12g memory. Then it will killed by system due to out_of_memory error. Is there any one can help me. 
It's urgent.

**Comment by leaxoy** [comment]
Yeah. 
Elasticserch version: 2.3.5
System: CentOS 7
Plugin: marvel, license, analysis-ik, analysis-pinyin.

**Comment by leaxoy** [comment]
When is use `ps aux|grep elastic`.
It shows belows:
`/bin/java -Xms8g -Xmx8g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Djna.nosys=true -Des.path.home=/usr/share/elasticsearch -cp /usr/share/elasticsearch/lib/elasticsearch-2.3.5.jar:/usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch start -Des.pidfile=/var/run/elasticsearchelasticsearch.pid -Des.default.path.home=/usr/share/elasticsearch -Des.default.path.logs=/var/log/elasticsearch -Des.default.path.data=/var/lib/elasticsearch -Des.default.path.conf=/etc/elasticsearch`

**Comment by s1monw** [comment]
`/bin/java -Xms8g -Xmx8g` your process is configured to use 8GB heap space. it might take way more memory via memory mapping files etc. so that's expected. Yet, this is all left to the OS to use the Virtual Memory so not much we can do.
