### ISSUE TITLE
Add support for role assumption in s3 repository

### ISSUE THREAD

**Issue by malpani** [elastic/elasticsearch#20635]
S3 repository currently relies on either the IAM instance profile credentials or explicitly passed in access/secret credentials at time of repository creation. 

I was thinking of working on a feature that allows the S3 repository module to take in an optional parameter `role_name` which is an IAM role name. If role_name is passed in, the plugin will use STS assume role to assume the passed role-name and use those credentials to write to S3.

The benefit is ability within an access controlled cluster to grant access to specific user roles to backup data into their own S3 buckets which could be on an AWS account completely different from the account that is running this cluster on EC2

**Comment by dadoonet** [comment]
It makes sense to me. Do you want to come with a PR on master branch ?

**Comment by malpani** [comment]
Yes, I will work on a PR for this.

**Comment by tlrx** [comment]
Closing in favor of #16428
