### ISSUE TITLE
Systemd issue with boot order.

### ISSUE THREAD

**Issue by Kraeutergarten** [elastic/elasticsearch#20647]
Since the current Type of the service is "simple" systemd proceed immediately with the "depending" units. 

See: https://www.freedesktop.org/software/systemd/man/systemd.service.html -> Options -> Type

Since elasticsearch needs some time to start, there are some problems with other software, which needs elasticsearch being up.

I hope you understand the problem and I'm sorry for my bad english.

**Comment by nik9000** [comment]
That makes sense! You'd like the service not to be "up" until it is
actually ready to take requests.

**Comment by Nosxxx** [comment]
> You'd like the service not to be "up" until it is actually ready to take requests.
That's exactly what I mean. Thank you.

**Comment by tlrx** [comment]
I understand the issue but I don't see what makes sense to you @nik9000 : are you in favour of moving away from the `simple` type?

**Comment by nik9000** [comment]
I know you *can* move away from it to get features like this but I don't know more than that.

**Comment by usercz** [comment]
You need to use `Type=forking`, and make elasticsearch do a fork() after it's ready, to signal that it's ready. This has been the way of unix demons for decades.

So something like
```
//Some initialization code
create socket

daemon() // Basically a fork, it's a libc call

the rest of the stuff
```

So systemd, after the fork happened, knows that the socket is ready and subsequent units can be started and they will find the socket.

Even if the socket isn't ready to reply to data, it's fine that they can connect, send the request and get stuck for a bit, waiting the answer.

**Comment by usercz** [comment]
This isn't for systemd only, it's the normal way daemons are supposed to work on unix.

**Comment by marknelsonengineer** [comment]
Wow, I can't believe this issue hasn't generated more comments...  My 2 cents worth...
1.  This is a big deal.  Elasticsearch is a production quality daemon and, while systemd integration is mundane, it's the future.  Leveraging systemd is a good investment.
2.  I'd recommend we get Elasticsearch to use either dbus or sd_notify...  This way, we can use systemd's watchdog monitoring *and* we can configure Kibana (which also needs a systemd script) to literally start after Elastisearch is ready for business (assuming they are running on the same box).

If I can get some insight from one of the more experienced maintainers, I'd be happy to volunteer to look into adding this capability.

**Comment by williamrandolph** [comment]
We, and by "we" I mean @jasontedor, changed the systemd service type to notify in PR #44673. I will try to verify that this change fixes the issue reported here.

**Comment by jasontedor** [comment]
@williamrandolph Thanks for bringing this issue to my attention, I wasn’t aware of it. Yes, the work in #44673 should close this issue out indeed.

@marknelsonengineer Sorry that this issue and your comment was neglected for so long. We integrated Elasticsearch with `systemd` via `sd_notify` indeed in #44673. That functionality will be available in the 7.4.0 release.

**Comment by williamrandolph** [comment]
I'm closing this issue due to the successful merge of #44673.

**Comment by ltworf** [comment]
> Thanks for making this only included in the packages and not archives.

Does this mean that if I download an elasticsearch .tar.gz this change will not be included in it?

**Comment by jasontedor** [comment]
Yes, we support systemd integration when installed via our packages, and didn’t add a module to the archives that we expect would be unused.

**Comment by ltworf** [comment]
Well I'd use it. Should I create a bugreport about it?
