### ISSUE TITLE
Log how many result found for a slow query

### ISSUE THREAD

**Issue by qiao-meng-zefr** [elastic/elasticsearch#20648]
Redirected from [here](https://discuss.elastic.co/t/can-elasticsearch-log-how-many-result-found-for-a-slow-query/61408)

**Describe the feature**:
Can we add this to the slow log:
- how many results/hits found for the query.

I understand it's probably going to be a per shard number, but will be still very useful for performance tuning and so on.

Appreciate it!

**Comment by hardik-iiita** [comment]
This makes sense. I will look into it.

**Comment by hardik-iiita** [comment]
this is good idea and help developer to debug their slow-query further

**Comment by shibing624** [comment]
thx

**Comment by qiao-meng-zefr** [comment]
I know it's been a while, but still think this is a great debugging tool for elasticsearch user. Is there any plan to add this feature or at least re-evaluate it?

Thanks elastic team!

**Comment by jasontedor** [comment]
I opened #29034.
