### ISSUE TITLE
Duplicate items in the dynamic_templates should give an error on mapping

### ISSUE THREAD

**Issue by LeonardGC** [elastic/elasticsearch#20641]
**Elasticsearch version**: 5.0.0 beta1

**Plugins installed**: []

**JVM version**:Version 8 Update 101

**Steps to reproduce**:
 1. Definition of a mapping where I define 2 "testString" blocks.
```
{
  "settings": {
    "analysis": {
      "analyzer": {
        "default": {
          "type": "custom",
          "tokenizer": "standard",
          "filter": [
            "standard",
            "lowercase",
            "asciifolding"
          ]
        },
        "lowercasedRaw": {
          "type": "custom",
          "tokenizer": "keyword",
          "filter": [
            "lowercase"
          ]
        }
      }
    }
  },
  "mappings": {
    "_default_": {
      "dynamic_templates": [
        /* all "test" fields have an analyzed subfield added */
        {
          "testString": {
            "match_mapping_type": "string",
            "match" : "test",
            "mapping": {
              "type": "string",
              "analyzer": "lowercasedRaw",
              "index": "analyzed",
              "fields": {
                "analyzed": {
                  "type": "string",
                  "index": "analyzed",
                  "analyzer": "default"
                }
              }
            }
          }
        },
        /* string fields are by default analyzed with the lowercasedRaw analyzer */
        /* NOTICE the duplicate "testString" name */
        {
          "testString": {
            "match_mapping_type": "string",
            "mapping": {
              "analyzer": "lowercasedRaw",
              "index": "analyzed",
              "type": "string"
            }
          }
        }
      ]
    }
  }
}
```

 2. First case
Add the following records (in bulk):
```
{"index":{"_type" : "log", "_id" : "1" } }
{"test":"testing"}
{"index":{"_type" : "log", "_id" : "2" } }
{"group":"U2"}
```

Get the mapping now (I removed the "_default_" part, because that stays the same):
```
{
  "testing": {
    "mappings": {
      "log": {
        "dynamic_templates": [
          {
            "testString": {
              "match": "test",
              "match_mapping_type": "string",
              "mapping": {
                "analyzer": "lowercasedRaw",
                "fields": {
                  "analyzed": {
                    "analyzer": "default",
                    "index": "analyzed",
                    "type": "string"
                  }
                },
                "index": "analyzed",
                "type": "string"
              }
            }
          },
          {
            "testString": {
              "match_mapping_type": "string",
              "mapping": {
                "analyzer": "lowercasedRaw",
                "index": "analyzed",
                "type": "string"
              }
            }
          }
        ],
        "properties": {
          "group": {
            "type": "text",
            "analyzer": "lowercasedRaw"
          },
          "test": {
            "type": "text",
            "fields": {
              "analyzed": {
                "type": "text"
              }
            },
            "analyzer": "lowercasedRaw"
          }
        }
      }
    }
  }
}
```
 3. Second case
Add the following records (in bulk): (these are the same records as above, but only the order is changed:
```
{"index":{"_type" : "log", "_id" : "2" } }
{"group":"U2"}
{"index":{"_type" : "log", "_id" : "1" } }
{"test":"testing"}
```

Get the mapping now (I removed the "_default_" part, because that stays the same):
```
{
  "testing": {
    "mappings": {
      "log": {
        "dynamic_templates": [
          {
            "testString": {
              "match": "test",
              "match_mapping_type": "string",
              "mapping": {
                "analyzer": "lowercasedRaw",
                "fields": {
                  "analyzed": {
                    "analyzer": "default",
                    "index": "analyzed",
                    "type": "string"
                  }
                },
                "index": "analyzed",
                "type": "string"
              }
            }
          }
        ],
        "properties": {
          "group": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "test": {
            "type": "text",
            "fields": {
              "analyzed": {
                "type": "text"
              }
            },
            "analyzer": "lowercasedRaw"
          }
        }
      }
    }
  }
}
```

If you compare these 2 mappings you'll see the differences.

4. Notice that if you correct the original mapping and give the 2 items a different name, the mapping stays consistent, regardless the order of the records.

**Comment by clintongormley** [comment]
Hi @LeonardGC 

I've tried your recreation several times, and I always get the same mappings:

    DELETE t
    
    PUT t
    {
      "settings": {
        "analysis": {
          "analyzer": {
            "default": {
              "type": "custom",
              "tokenizer": "standard",
              "filter": [
                "standard",
                "lowercase",
                "asciifolding"
              ]
            },
            "lowercasedRaw": {
              "type": "custom",
              "tokenizer": "keyword",
              "filter": [
                "lowercase"
              ]
            }
          }
        }
      },
      "mappings": {
        "_default_": {
          "dynamic_templates": [
            {
              "testString": {
                "match_mapping_type": "string",
                "match": "test",
                "mapping": {
                  "type": "string",
                  "analyzer": "lowercasedRaw",
                  "index": "analyzed",
                  "fields": {
                    "analyzed": {
                      "type": "string",
                      "index": "analyzed",
                      "analyzer": "default"
                    }
                  }
                }
              }
            },
            {
              "testString": {
                "match_mapping_type": "string",
                "mapping": {
                  "analyzer": "lowercasedRaw",
                  "index": "analyzed",
                  "type": "string"
                }
              }
            }
          ]
        }
      }
    }

This request:
    
    POST t/_bulk
    {"index":{"_type" : "log", "_id" : "1" } }
    {"test":"testing"}
    {"index":{"_type" : "log", "_id" : "2" } }
    {"group":"U2"}
    
    GET _mapping?filter_path=**.properties

returns 

    {
      "t": {
        "mappings": {
          "log": {
            "properties": {
              "group": {
                "type": "text",
                "analyzer": "lowercasedRaw"
              },
              "test": {
                "type": "text",
                "fields": {
                  "analyzed": {
                    "type": "text"
                  }
                },
                "analyzer": "lowercasedRaw"
              }
            }
          }
        }
      }
    }

and so does     

    POST t/_bulk
    {"index":{"_type" : "log", "_id" : "2" } }
    {"group":"U2"}
    {"index":{"_type" : "log", "_id" : "1" } }
    {"test":"testing"}


(Obviously I'm deleting the index in between the two tests)    

You want to try it out again and check?

**Comment by LeonardGC** [comment]
Hi @clintongormley 

You are right, I can't duplicate it with my example, BUT, I can replicate it with some small change.
Just rename the "testString" to "strings":

```
{
  "settings": {
    "analysis": {
      "analyzer": {
        "default": {
          "type": "custom",
          "tokenizer": "standard",
          "filter": [
            "standard",
            "lowercase",
            "asciifolding"
          ]
        },
        "lowercasedRaw": {
          "type": "custom",
          "tokenizer": "keyword",
          "filter": [
            "lowercase"
          ]
        }
      }
    }
  },
  "mappings": {
    "_default_": {
      "dynamic_templates": [
        /* all "test" fields have an analyzed subfield added */
        {
          "strings": {
            "match_mapping_type": "string",
            "match" : "test",
            "mapping": {
              "type": "string",
              "analyzer": "lowercasedRaw",
              "index": "analyzed",
              "fields": {
                "analyzed": {
                  "type": "string",
                  "index": "analyzed",
                  "analyzer": "default"
                }
              }
            }
          }
        },
        /* string fields are by default analyzed with the lowercasedRaw analyzer */
        /* NOTICE the duplicate "strings" name */
        {
          "strings": {
            "match_mapping_type": "string",
            "mapping": {
              "analyzer": "lowercasedRaw",
              "index": "analyzed",
              "type": "string"
            }
          }
        }
      ]
    }
  }
}
```

Is this a reserved name?

**Comment by clintongormley** [comment]
I get exactly the same thing as before.  At first I thought it might be the comments but I tried with the comments and it all still works.

**Comment by clintongormley** [comment]
Can you paste EXACTLY the steps you are taking to demonstrate the problem?

**Comment by clintongormley** [comment]
thanks for pursuing it @LeonardGC
