### ISSUE TITLE
Max Score Calculation Issue With Painless Scripting

### ISSUE THREAD

**Issue by bharvidixit** [elastic/elasticsearch#20651]
**Elasticsearch version**: elasticsearch-5.0.0-alpha5

**Plugins installed**: []

**JVM version**: 1.8.0_72

**OS version**:  Ubuntu 15

**Description of the problem including expected versus actual behavior**:
On a given sample of data sets and using function score query in combination of script_score, the max_score is returned ad 1.
![image](https://cloud.githubusercontent.com/assets/10341430/18810897/9168e1d6-82bf-11e6-919a-929e6347f142.png)

**Steps to reproduce**:
[mapping_and_docs.zip](https://github.com/elastic/elasticsearch/files/491312/mapping_and_docs.zip)

1. Find attached zip file which contains, library.json (mapping) and books.json ( documents for indexing) 
2. Create index: curl -XPUT 'localhost:9200/library'
3. Put mapping: curl -XPUT 'localhost:9200/library/book/_mapping' -d @library.json
4. Index docs: curl -XPOST 'localhost:9200/_bulk' --data-binary @books.json
5. Use following query for search: 
GET library/book/_search
{
  "query": {
    "match_all": {}
  },
  "rescore": {
    "query": {
      "rescore_query": {
        "function_score": {
          "query": {
            "match_all": {}
          },
          "script_score": {
            "script": {
              "inline": "doc['year'].value",
              "lang": "painless"
            }
          }
        }
      }
    }
  },"_source": ["title", "available"]
}

**Comment by bharvidixit** [comment]
I just tried it with 5.0.0-beta1 also and getting the same result as explained earlier.

**Comment by jpountz** [comment]
Not sure why it would be specific to painless, maybe it is a general issue with rescorers?
