### ISSUE TITLE
Remove Marvel character reference from install guide

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#20653]
5.0, 5.x, and master

https://www.elastic.co/guide/en/elasticsearch/reference/master/_installation.html

>Without going too much into detail, we can see that our node named "I8hydUG" (which will be a different Marvel character in your case) has started and elected itself as a master in a single cluster.

We no longer use Marvel characters as default node names.

**Comment by bohyun-e** [comment]
Good catch, @ppf2 
cc: @debadair @pickypg

**Comment by jasontedor** [comment]
Closed by #20654
