### ISSUE TITLE
Make possible to use of priority in election

### ISSUE THREAD

**Issue by pznamensky** [elastic/elasticsearch#20655]
It seems, that it's not possible to create node that could elect but not to become master.
This option could be useful in some cases.
For example, we have 2 master nodes with data and we want to avoid split brain and the existence of two masters. We can create another instance without data and `node.master = true`. But this third node can become master. So this node must be able to handle a lot of request and must have low latency connection with other nodes.
But in fact we want to have node with minimum hardware requirement.
Is it possible to add option like "weigth" or "priority" which will be considered in master election?
Another way is to add flag which will disallow to elect current node as master.
Current option `node.master` controls both actions: to elect and to be elected.

**Comment by jasontedor** [comment]
Duplicates #14340

**Comment by bleskes** [comment]
On a side note - it is very likely that a master only node with no data will not need much hardware. What requests did you in mind with "handle a lot of request a"? If you don't point external traffic at it the potentially frequent requests the master node will  need to process is mapping changes. If you don't have an extreme number of those minimal hardware should be fine. I suggest you try it out.
