### ISSUE TITLE
Documentation suggests using no longer available option -D

### ISSUE THREAD

**Issue by algestam** [elastic/elasticsearch#20652]
**Elasticsearch version**: 5.0.0-beta1

**Plugins installed**: [none]

**JVM version**: 1.8.0_91

**OS version**: Ubuntu 16.04.1 LTS

**Description of the problem including expected versus actual behavior**:

The documentation on _Disabling swapping_ (setup/sysconfig/swap) has a suggestion on changing tempdir by using the no longer available option `-D`. The actual command in the documentation looks like this:

    ./bin/elasticsearch -Djava.io.tmpdir=/path/to/temp/dir

Since the `-D` option isn't available, the output when running the command is:

    elasticsearch@host:/elasticsearch$ ./bin/elasticsearch -Djava.io.tmpdir=/path/to/temp/dir
    starts elasticsearch

    Option                Description                                              
    ------                -----------                                              
    -E <KeyValuePair>     Configure a setting                                      
    -V, --version         Prints elasticsearch version information and exits       
    -d, --daemonize       Starts Elasticsearch in the background                   
    -h, --help            show help                                                
    -p, --pidfile <Path>  Creates a pid file in the specified path on start        
    -q, --quiet           Turns off standard ouput/error streams logging in console
    -s, --silent          show minimal output                                      
    -v, --verbose         show verbose output                                      
    ERROR: D is not a recognized option

Updating the docs to no longer advise on using the `-D` option when starting elasticsearch would in my opinion solve this problem. Other ways of specifying Java options are mentioned in the documentation.

**Steps to reproduce**:
 1. Start elasticsearch with the command `elasticsearch -Djava.io.tmpdir=/path/to/temp/dir`
 2. Elasticsearch responds with an error message regarding the `-D` option

**Comment by jasontedor** [comment]
Thanks @algestam; I pushed a7c777f58af1afbd7f9b887cdc039efefb25a177 and marked you as eligible for the [Pioneer Program](https://www.elastic.co/blog/elastic-pioneer-program).

**Comment by algestam** [comment]
Great, thank you so much!
