### ISSUE TITLE
Should shadow indices reuse allocation ids when promoting a replica to primary

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#20650]
Shadow replica to primary promotion is special in that that it requires the `ShadowIndexShard` of the replica to be replaced with a new `IndexShard` instance. At the moment this is achieved be giving the shard a new allocation id, triggering a cleanup in `IndicesClusterStateService`. This is the easiest solution from the `IndicesClusterStateService` perspective but it have the down side that it cause the in sync replica list to be out of date / empty and may cause problems if the cluster is shut down before the new primary is started. We should decide whether we want to align this with how normal shard work (reuse of allocation ids) or come up with another solutions.

This was all discovered while working on #20637 and adding extra validation logic [here](https://github.com/elastic/elasticsearch/pull/20637/commits/3b23135cefd6a49c8942d93c929a021255d0aef4#diff-814ec451d0e00936e3a5f9cb6811e5bdR143)

**Comment by dakrone** [comment]
> We should decide whether we want to align this with how normal shard work (reuse of allocation ids)

Should we re-use the allocation id since we only have a single copy of the data, so any copies of the data are up-to-date?

**Comment by bleskes** [comment]
> Should we re-use the allocation id since we only have a single copy of the data, so any copies of the data are up-to-date?

It is a bit further off then how do things now but  that is indeed another valid option, conceptually. Recently the exact semantics of aID was raised for discussion:

1) Are they associated with the life cycle of a shard assignment to a node - i.e., if the master assigns a shard to a node, then fails it due to a disconnect and the re-assigns it there the new allocation should have a new ID.
2) Are they associated with the storage on a node? in which case, it should stay the same every time we reuse a storage as is. Note that currently a replica recovery destroys the storage folder and rebuilds it, which is why we have to assign a new id. This will change with seq# based recovery.

**Comment by bleskes** [comment]
Another things that play here is that currently the promotion of a replica to primary also removes the old aid from the in-sync replicas list, causing it to only contain other replicas. If those replicas fail during the initialization of the newly promoted replica, we trigger the assertion we have [here](https://github.com/elastic/elasticsearch/blob/1e6a882ab9174e6c00954264f859086a16d1f8b3/core/src/main/java/org/elasticsearch/cluster/routing/allocation/IndexMetaDataUpdater.java#L199) , causing the follwing failure:

```
  > Throwable #1: java.lang.AssertionError: in-sync set became empty but active primary wasn't failed: [WU7AocjrSB-sG0IOflGj8w]
   > 	at __randomizedtesting.SeedInfo.seed([B37B65076A2E7CB1:CBFC6CD43515AAF8]:0)
   > 	at org.elasticsearch.cluster.routing.allocation.IndexMetaDataUpdater.updateInSyncAllocations(IndexMetaDataUpdater.java:199)
   > 	at org.elasticsearch.cluster.routing.allocation.IndexMetaDataUpdater.applyChanges(IndexMetaDataUpdater.java:122)
```

See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+dockeralpine-periodic/58
