### ISSUE TITLE
Add a GeoHeatmapAggregator for geo_shape fields and queries

### ISSUE THREAD

**Issue by sstults** [elastic/elasticsearch#20665]
**Describe the feature**:

There currently is not a way for ES to provide any kind of analysis over `geo_shape` fields. Lucene supports the creation of a heatmap at arbitrary granularity through its `HeatmapFacetCounter`. It was first used in Solr's facet mechanism, but it's usable by any Lucene application. This feature issue adds a metric aggregator `GeoHeatmapAggregator` to accomplish that.

For example, an aggregation of:

``` javascript
{
    "aggs" : {
        "overlay": { 
            "heatmap" : {
                "field" : "shapes",
                "grid_level" : 4,
                "max_cells" : 100000,
                "geom" : {
                    "geo_shape" : {
                        "shapes" : {
                            "shape" : {
                                "type" : "envelope",
                                "coordinates" : [
                                    [-180,90],
                                    [180,-90]
                                ]
                            },
                            "relation" : "intersects"
                        }
                    }
                }
            }
        }
    }
}
```

Might produce output similar to:

``` javascript
{
    ...

    "aggregations": {
        "overlay": {
            "grid_level":4,
            "rows":7,
            "columns":6,
            "min_x":45.0,
            "min_y":11.25,
            "max_x":180.0,
            "max_y":90.0,
            "counts": [
                [0,0,2,1,0,0],
                [0,0,1,1,0,0],
                [0,1,1,1,0,0],
                [0,0,1,1,0,0],
                [0,0,1,1,0,0],
                [],
                []
            ]
        }
    }
}
```

**Comment by dsmiley** [comment]
Just a little correction: "It's meant for use in Solr's facet mechanism" -- no... it's for any Lucene app that might want to calculate heatmaps from the RPT index.  Solr was the first Lucene app to use it.  If you think there are any Solr-isms or stuff in that functionality you feel doesn't belong, please file a Lucene issue.

**Comment by sstults** [comment]
Thanks @dsmiley, the description has been updated.

**Comment by sstults** [comment]
I added support for grid level calculation based off of `dist_err` and `dist_err_pct`, so I also updated the description of this ticket.

**Comment by polyfractal** [comment]
Closing in favor of https://github.com/elastic/elasticsearch/issues/21293.  

The request in #21293 seems very similar (aggregating over `geo_shapes` to provide a heat map of sorts), but should be more general since it's a bucketing aggregation instead of just a metric.
