### ISSUE TITLE
1263) Error injecting constructor, java.lang.IllegalArgumentException: failed to parse [1.6m], fractional time values are not supported

### ISSUE THREAD

**Issue by ikapriz** [elastic/elasticsearch#20662]
**Elasticsearch version**: 5.0.0-beta1

**Plugins installed**: [none]

**JVM version**: jdk1.8.0_65

**OS version**: Linux 2.6.32-042stab108.8 #1 SMP Wed Jul 22 17:23:23 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: On startup of elasticsearch master only node: starts, generates 1263 identical errors in the log (provided below) and crashes. Expected the clean start.
**Steps to reproduce**:
 1.  Download and install rpm version elasticsearch-5.0.0-beta1.rpm
 2.  Make sure 'service elasticsearch start' command starts the elasticsearch fine. I had to modify JAVA location in /etc/sysconfig/elasticsearch for it to start correctly.
 3.  Replace /etc/elasticsearch/elasticsearch.yml with attached elasticsearch.yml file. In that file none of the hosts that are specified in unicast list exists 
 4.  Run 'service elasticsearch stop'
 5. Run 'service elasticsearch start'
 6. Wait for a few seconds. Servers prints 1263 errors into the /var/log/elasticsearch.log and crashes

**Provide logs (if relevant)**:
Provided configuration file and log file
[elasticsearch.log.gz](https://github.com/elastic/elasticsearch/files/494356/elasticsearch.log.gz)
[elasticsearch.yml.gz](https://github.com/elastic/elasticsearch/files/494355/elasticsearch.yml.gz)

**Comment by tlrx** [comment]
Thanks for reporting.

I suspect the `discovery.zen.ping_timeout: 5s` is used to calculate the `join_timeout` setting which is `ping_timeout x 20` by default. Then the resulting `100s`  value is rendered as a fractional time value string by the setting framework before being parsed again... and failed.
