### ISSUE TITLE
debian repo https://artifacts.elastic.co/packages/5.x-prerelease/apt not signed

### ISSUE THREAD

**Issue by tomas-mazak** [elastic/elasticsearch#20664]
**Elasticsearch version**: 5.x-prerelease

**OS version**: Debian Jessie

**Description of the problem including expected versus actual behavior**:
It looks like the new debian repo https://artifacts.elastic.co/packages/5.x-prerelease/apt is not signed (Release.gpg does not exist).

**Steps to reproduce**:
 1. add "deb https://artifacts.elastic.co/packages/5.x-prerelease/apt stable main" to sources.list
 2. apt-get update

**Provide logs (if relevant)**:
~# apt-get update
...
W: The repository 'https://artifacts.elastic.co/packages/5.x-prerelease/apt stable Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

~# curl https://artifacts.elastic.co/packages/5.x-prerelease/apt/dists/stable/Release.gpg
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>packages/5.x-prerelease/apt/dists/stable/Release.gpg</Key><RequestId>B9AE59CE38CDA017</RequestId><HostId>Q/MRmACsweTorlZX4IZC23rgAE2rORU51xaNPNM4mMzolK9nRI/lu+Uc+xL9s8f6wg2Km9wpBgo=</HostId></Error>

**Comment by tomas-mazak** [comment]
Hello, is anybody going to look at this issue? It block switching from 5.0.0-alpha to beta for debian users...

**Comment by rjernst** [comment]
This will be fixed in the next prerelease. Thanks!

**Comment by tomas-mazak** [comment]
@rjernst Why is that? And if the new repo cannot be fixed, why don't you add the beta package to the old one (http://packages.elastic.co/elasticsearch/5.x/debian)?

**Comment by rjernst** [comment]
@tomas-mazak For 5.0, as we are unifying versions across our stack, we have built a unified release process, and artifact locations are changing. When the next prerelease occurs, it will rewrite the repository metadata, and fix the signature filename.

**Comment by thg303** [comment]
is it going to be fixed or what?

**Comment by rjernst** [comment]
@thg303 This issue was fixed almost a year ago. If you are experiencing issues, please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports.
