### ISSUE TITLE
highlight_query does not honor all terms of must clause

### ISSUE THREAD

**Issue by dsem** [elastic/elasticsearch#20676]
**Elasticsearch version**: 2.4.0

**Plugins installed**: None

**JVM version**: 8

**OS version**: Alpine

**Description of the problem including expected versus actual behavior**:
I am using `highlight_query` to highlight results independent of the way they were queried.  When I specify a `bool` clause with two `must` terms, the highlighting occurs when either of the `must` terms match.  I would expect this to behave more like a regular `bool` query, where all `must` terms must match in order for a document to be returned.

**Steps to reproduce**:
 1. Create a simple index with one document and two fields:
 ```json
{
    "field_1": "value_1",
    "field_2": "value_2"
}
 ```

 2. Query the document with two `must` clauses under `highlight_query`:
 ```json
{
    "highlight": {
        "fields": {
            "*": {
                "highlight_query": {
                    "bool": {
                        "must": [
                            {
                                "match": {
                                    "field_1": {
                                        "query": "value_1"
                                    }
                                }
                            },
                            {
                                "match": {
                                    "field_2": {
                                        "query": "no match"
                                    }
                                }
                            }
                        ]
                    }
                }
            }
        }
    }
}
 ```

 3. The document is improperly matched:
 ```json
    "hits": {
        "hits": [
            {
                "_id": "AVdurOuxCEUee5q0MANw",
                "_index": "cluster",
                "_score": 1.0,
                "_source": {
                    "field_1": "value_1",
                    "field_2": "value_2"
                },
                "_type": "doc",
                "highlight": {
                    "field_1": [
                        "<em>value_1</em>"
                    ]
                }
            }
        ],
 ```

I would expect there to be no `highlight` section in the query response because the document does not match the `must` clause specified under `highlight_query`.

**Comment by clintongormley** [comment]
@dsem the highlight query is not used for filtering, that's the job of the main query (which in this case is match_all).  Highlighting just extracts a bag of words from the terms and highlights those.  If you had the same query with bool-must as your main query, then the document wouldn't have been included in the hits at all.  This is just the way that highlighting works.

**Comment by dsem** [comment]
Thanks for your reply.

I understand that highlight_query isn't used for filtering.  My use case has a query returning all documents in a thread (e.g., a list of emails in an email thread), while highlighting certain terms found in the documents.  Therefore the filtering and highlighting queries are completely different.

Is there a way to make this issue an enhancement request?

**Comment by clintongormley** [comment]
> Is there a way to make this issue an enhancement request?

I don't think we can make this work unless Lucene completely changes how their highlighters work.

**Comment by ps23** [comment]
I have the same issue. The documentation says:
"It is also possible to highlight against a query other than the search query by setting highlight_query. This is especially useful if you use a rescore query because those are not taken into account by highlighting by default. Elasticsearch does not validate that highlight_query contains the search query in any way so it is possible to define it so legitimate query results aren’t highlighted at all. Generally it is better to include the search query in the highlight_query. Here is an example of including both the search query and the rescore query in highlight_query."

It also gives the following example:

```
"highlight" : {
        "order" : "score",
        "fields" : {
            "content" : {
                "fragment_size" : 150,
                "number_of_fragments" : 3,
                "highlight_query": {
                    "bool": {
                        "must": {
                            "match": {
                                "content": {
                                    "query": "foo bar"
                                }
                            }
                        },
                        "should": {
                            "match_phrase": {
                                "content": {
                                    "query": "foo bar",
                                    "slop": 1,
                                    "boost": 10.0
                                }
                            }
                        },
                        "minimum_should_match": 0
                    }
                }
            }
        }
    }
```

What is the purpose of having a separate query in the first place then when all that the highlighter does is to extract all terms as a list of terms to match?

The currently behaviour treats all terms as OR and highlights anything that it finds no matter if it was defined through bool must, should, query_string AND, |(value1 + value2).

**Comment by aslamy** [comment]
I have the same issue. It does not matter if you use highlight_query or not. The result is always the same.
