### ISSUE TITLE
Elasticsearch turns off randomly without any error

### ISSUE THREAD

**Issue by keshav-marketingmindz** [elastic/elasticsearch#20678]
**Elasticsearch version**:
2.4.0
**Plugins installed**: []
elasticsearch
**JVM version**:
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
**OS version**:
ubuntu 14.04
**Description of the problem including expected versus actual behavior**:
The elasticsearch service should run constantly but its getting down without any reason
**Steps to reproduce**:
 1. Install elasticsearch on a ubuntu 14.04
 2. Create index documents on a every 10 min cron
 3. Elasticsearch gets down automatically

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by dakrone** [comment]
Hi,
We reserve Github issues for feature requests and bug reports. If you are having problems please us https://discuss.elastic.co instead!
