### ISSUE TITLE
"mapper_parsing_exception", "reason"=>"Cannot generate dynamic mappings of type [_id] for [_id]"

### ISSUE THREAD

**Issue by ljchu** [elastic/elasticsearch#20679]
**Elasticsearch version**: 2.4.0
**Logstash version**:2.4.0
**JVM version**:1.7
**Description of the problem including expected versus actual behavior**:

I want to write log into es use logstash,and use my custom field as es index's _id,but throw the exception below:

"mapper_parsing_exception", "reason"=>"Cannot generate dynamic mappings of type [_id] for [_id]"}

**Steps to reproduce**:
 1.start es and create es index,like logstash-log
 2.config logstash like below:

```
input {
        file {
        path => [logpath]
        start_position => beginning
        codec => "json"
   }
 }
filter {
  grok {
    match => { "message" => "%{DATA:timestamp}\^%{DATA:_id}\^%{DATA:args}"}
  }
output {
    elasticsearch {
        hosts => ["localhost:9200"]
        index => "logstash-log"
    }
}
```
 3. start logstash and write log into the log file like:

`2016-09-28 16:32:00^55300003^something`

so,what should I do to fix this?
TKS.

**Comment by ljchu** [comment]
I got it, config the logstash output like:
```
output {
        elasticsearch {
        hosts => ["localhost:9200"]
        index => "logstash-log"
        document_id => "%{document_id}"
        }
}

```
and use "document_id" format my id.

**Comment by jpountz** [comment]
Thanks for bringing closure!
