### ISSUE TITLE
Include 1.x -> 5.x instructions in upgrade guide

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#20675]
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/setup-upgrade.html only shows 2.x -> 5.x upgrade information.  

It is important to include 1.x -> 5.x information in the upgrade guide given that you must reindex the data between these versions.

This information is covered in the [upgrade api](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/indices-upgrade.html) documentation which is nice, but really should also be in the setup-upgrade section for this is the entry point for Elasticsearch upgrades.  We don't have to provide info as detailed as the upgrade api page on 1.x -> 5.x, but there should at least be some high level information on 1.x -> 5.x since it is not as straightforward as a 2.x -> 5.x upgrade given the requirement to reindex the data (and some users are accustomed to not calling the upgrade api directly and letting merge upgrade the segments over time, so they can completely miss the information that is only in the upgrade api doc and just assume that they can just go to 2.x first and then to 5.x without reindexing, etc..)

Also, the [upgrade api](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/indices-upgrade.html) information is a bit obsolete as well

>The only way to prepare an index created in 1.x for use in 5.x is to reindex your data in a cluster running Elasticsearch 2.3.x, which you can do with the new reindex API.

This is no longer true with [reindex from remote](https://github.com/elastic/elasticsearch/pull/18585) which allows you to reindex from 1.x to 5.0.

**Comment by niemyjski** [comment]
I agree, I'm currently in the process of upgrading https://github.com/exceptionless/foundatio.repositories from 1.x to 5.x and we are going to use external reindexing to accomplish this.
