### ISSUE TITLE
Bulk insert write slower and slower!

### ISSUE THREAD

**Issue by wenma** [elastic/elasticsearch#20677]
es : v2.3.1
test bulk insert :  10w docs/bulk  *  100 times
```
Bulk insert use 4.1s
Bulk insert use 4.7s
Bulk insert use 7.5s
Bulk insert use 10s
Bulk insert use 12.3s
Bulk insert use 15s
Bulk insert use 16.8s
Bulk insert use 21.6s
Bulk insert use 24.4s
Bulk insert use 26.7s
Bulk insert use 32.4s
Bulk insert use 31.4s
Bulk insert use 32.8s
Bulk insert use 38.7s
Bulk insert use 41.7s
Bulk insert use 46s
Bulk insert use 47.9s
Bulk insert use 48.7s
```
Has anyone ever met this problem？

**Comment by s1monw** [comment]
can you share more information like what kind of documents you are using, how do you index your document (code / or curl statements)?

**Comment by jpountz** [comment]
Closing because of lack of feedback. Please reopen if you have more information to provide.
