### ISSUE TITLE
ES2.4 load mapping failed

### ISSUE THREAD

**Issue by hrdxwandg** [elastic/elasticsearch#20683]
i use es 2.4, my mapping json txt file is as below:
{
    "mappings": {
        "poem": {
            "_all": {
                "enabled": "false"
            },
            "properties": {
                "pid": {
                    "store": "true",
                    "index": "not_analyzed",
                    "type": "integer"
                },
                "authorid": {
                    "store": "true",
                    "index": "not_analyzed",
                    "type": "integer"
                },
                "authorname": {
                    "store": "true",
                    "index": "not_analyzed",
                    "type": "string"
                },
                "category": {
                    "store": "true",
                    "index": "not_analyzed",
                    "type": "string"
                },
                "dynasty": {
                    "store": "true",
                    "index": "not_analyzed",
                    "type": "string"
                },
                "tag": {
                    "store": "true",
                    "index": "not_analyzed",
                    "type": "string"
                },
                "content": {
                    "store": "true",
                    "index": "analyzed",
                    "type": "string",
                    "analyzer": "ik"
                },
                "title": {
                    "store": "true",
                    "index": "not_analyzed",
                    "type": "string"
                }
            }
        }
    }
}

my function code is as below:
public void createIndex(String indexName, String type) {
		if (!isIndexExists(indexName)) {
			client.admin().indices().prepareCreate(indexName).execute().actionGet();
			String jsonMap = IOUtils.ReadFile(MAP_CONF + indexName);
			jsonMap = jsonMap.trim();
			client.admin().indices().preparePutMapping(indexName).setType(type).setSource(jsonMap).execute()
					.actionGet();
		}
	}
the code throw an exception as follow:
MapperParsingException[Root mapping definition has unsupported parameters:  [mappings : {poem={_all={enabled=false}, properties={pid={store=true, index=not_analyzed, type=integer}, authorid={store=true, index=not_analyzed, type=integer}, authorname={store=true, index=not_analyzed, type=string}, category={store=true, index=not_analyzed, type=string}, dynasty={store=true, index=not_analyzed, type=string}, tag={store=true, index=not_analyzed, type=string}, content={store=true, index=analyzed, type=string, analyzer=ik}, title={store=true, index=not_analyzed, type=string}}}}]]
	at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:171)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:159)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:99)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:549)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:468)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

is anyone can help me? how to solve the problem? I google and find many article,but still unresovled. 
thanks a lot!

**Comment by tlrx** [comment]
When using the Java API, mappings are expected to be passed in the map directly. In your case I suspect that you have a root object "mappings" that is not expected. Try to pass this "mappings" map directly.

Also, we reserve Github issues for feature requests and bug reports, please use https://discuss.elastic.co instead.

**Comment by hrdxwandg** [comment]
thank you. i change my json as follow but still not ok:
{
    "poem": {
        "_all": {
            "enabled": "false"
        },
        "properties": {
            "pid": {
                "store": "true",
                "index": "not_analyzed",
                "type": "integer"
            },
            "authorid": {
                "store": "true",
                "index": "not_analyzed",
                "type": "integer"
            },
            "authorname": {
                "store": "true",
                "index": "not_analyzed",
                "type": "string"
            },
            "category": {
                "store": "true",
                "index": "not_analyzed",
                "type": "string"
            },
            "dynasty": {
                "store": "true",
                "index": "not_analyzed",
                "type": "string"
            },
            "tag": {
                "store": "true",
                "index": "not_analyzed",
                "type": "string"
            },
            "content": {
                "store": "true",
                "index": "analyzed",
                "type": "string",
                "analyzer": "ik"
            },
            "title": {
                "store": "true",
                "index": "not_analyzed",
                "type": "string"
            }
        }
    }
}
