### ISSUE TITLE
Automatic generated index has faulty mappings

### ISSUE THREAD

**Issue by pojaszek** [elastic/elasticsearch#20684]
*Software*
Elasticsearch version: 2.3.5
Lucene version: 5.5.0

*Issue*

When I put my first document to index lambdalog-2016.09.28 it creates new index without mappings from template.

Index template:
```
{
  "lambdalog_template": {
    "order": 1,
    "template": "lambdalog*",
    "settings": {
      "index": {
        "mapper": {
          "dynamic": "false"
        }
      }
    },
    "mappings": {
      "log": {
        "dynamic": false,
        "properties": {
          "@correlationId": {
            "index": "not_analyzed",
            "type": "string"
          },
          "@version": {
            "type": "integer"
          },
          "@owner": {
            "index": "not_analyzed",
            "type": "string"
          }
        }
      }
    },
    "aliases": {
      "lambdalog": {
        
      }
    }
  }
}
```

I make a request like:
```curl -v -XPOST 'http://localhost:9200/lambdalog-2016.09.28/log/' -d '{ "foo": "bar" }'``` 

After this request index is created and its mapping `lambdalog-2016.09.28/_mapping/` looks like:
```
{
  "lambdalog-2016.09.28": {
    "mappings": {
      "log": {
        "properties": {
          "foo": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

Above mappings should look like after creating index ```curl -v -XPUT 'http://localhost:9200/lambdalog-2016.09.28```:
```
{
  "lambdalog-2016.09.28": {
    "mappings": {
      "log": {
        "dynamic": "false",
        "properties": {
          "@correlationId": {
            "type": "string",
            "index": "not_analyzed"
          },
          "@owner": {
            "type": "string",
            "index": "not_analyzed"
          },
          "@version": {
            "type": "integer"
          }
        }
      }
    }
  }
}
```

It works fine when I changed document type from 'log' to '_default_' in template:
```
 "mappings": {
      "log": {
```
with:
```
 "mappings": {
      "_default_": {
```
But in this case I lost possibility of having different mappings for different document types.

**Comment by clintongormley** [comment]
@pojaszek I followed your instructions (see below) and they worked perfectly.  I think you either made a mistake somewhere along the way, or you have some other template which is clashing.

    PUT _template/lambdalog_template
    {
      "order": 1,
      "template": "lambdalog*",
      "settings": {
        "index": {
          "mapper": {
            "dynamic": "false"
          }
        }
      },
      "mappings": {
        "log": {
          "dynamic": false,
          "properties": {
            "@correlationId": {
              "index": "not_analyzed",
              "type": "string"
            },
            "@version": {
              "type": "integer"
            },
            "@owner": {
              "index": "not_analyzed",
              "type": "string"
            }
          }
        }
      },
      "aliases": {
        "lambdalog": {}
      }
    }
    
    POST /lambdalog-2016.09.28/log/
    { "foo": "bar" }
    
    GET lambdalog-2016.09.28/_mapping

Returns:

```
{
  "lambdalog-2016.09.28": {
    "mappings": {
      "log": {
        "dynamic": "false",
        "properties": {
          "@correlationId": {
            "type": "string",
            "index": "not_analyzed"
          },
          "@owner": {
            "type": "string",
            "index": "not_analyzed"
          },
          "@version": {
            "type": "integer"
          }
        }
      }
    }
  }
}
```
