### ISSUE TITLE
Rankings based on term proximity rather than term frequency

### ISSUE THREAD

**Issue by calufa** [elastic/elasticsearch#20697]
Currently "span_near" queries return desired results if all the "span_terms" exists on the results documents. I wonder if its possible to have an "or" inside the clauses, so if one of the terms doesn't exist it still return documents based on term proximity.

The use case is the following. I want to boost documents where terms occur close together (proximity). The closer the terms are from each other the higher the ranking, instead of ranking higher the documents that contains all the terms.

Consider these 2 documents:
1) the great fox
2) the black night has come and the great and mighty fox went for dinner

If you query for "the great black fox", ES returns the following:
1) the black night has come and the great and mighty fox went for dinner
2) the great fox

I would like 'the great fox' to be ranked higher even thought is missing 'black'.

**Comment by jpountz** [comment]
There is no way you can do this now, and that would be a fairly costly query to implement. I believe you could achieve something close with the following query, just adapt the slop of the phrase queries to your needs.

```
{
  "query": {
    "bool": {
      "should": [
         {
           "match_phrase": {
             "body": "the great",
             "slop": 10
           }
         },
         {
           "match_phrase": {
             "body": "great black",
             "slop": 10
           }
         },
         {
           "match_phrase": {
             "body": "black fox",
             "slop": 10
           }
         },
       ],
       "filter": [
         {
           "bool": {
             "should": [
               {
                 "match": {
                   "body": "the"
                 }
               },
               {
                 "match": {
                   "body": "great"
                 }
               },
               {
                 "match": {
                   "body": "black"
                 }
               },
               {
                 "match": {
                   "body": "fox"
                 }
               }
             ]
           }
         }
       ]
    }
  }
}
```

I am closing it now since I don't think there is enough need for it, but we could reconsider if we see this coming more in the future.
