### ISSUE TITLE
Make Elasticsearch docs open in Console editor popup closeable

### ISSUE THREAD

**Issue by lukas-vlcek** [elastic/elasticsearch#20693]
**Elasticsearch version**: Documentation for 5.x

**Description of the problem including expected versus actual behavior**:

Make the popup window closeable (add Close input '[X]' or 'ESC' key listener).

![view_in_console](https://cloud.githubusercontent.com/assets/205174/18948722/88ce028c-8638-11e6-8764-9b7b07393a90.jpg)

**Comment by lukas-vlcek** [comment]
Oh, obviously, the popup is shown when the Settings icon is clicked, not the "VIEW IN CONSOLE" link.

**Comment by jasontedor** [comment]
This would get the correct level of attention on the [Kibana repository](https://github.com/elastic/kibana).

**Comment by jasontedor** [comment]
This is for our docs, I see. Can you change the title to make that clearer?

**Comment by lukas-vlcek** [comment]
Thanks @jasontedor

**Comment by clintongormley** [comment]
This issue was moved to elastic/docs#120
