### ISSUE TITLE
ES-Hadoop (Spark) does not support Shield run_as functionality

### ISSUE THREAD

**Issue by isp300** [elastic/elasticsearch#20699]
**Elasticsearch version**:
2.4.0
**Plugins installed**: [shield]

**Describe the feature**:
I need to use Shield run_as functionality with ES-Hadoop (Hadoop/Spark). According to documentation in order to do this you have to provide custom HTTP header es-shield-runas-user. This perfectly works with "generic" Java client using org.elasticsearch.common.settings.Settings.Builder.put("request.headers.es-shield-runas-user", "run_as_user_name")
ES-Hadoop has separate implementation that does not provide this functionality (since there is no ability to provide required custom header).

In order to fix this i'd like to suggest the next changes in org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport:

```
....
private static final String HEADER_SETTINGS_PREFIX="es.client.header";
....
public CommonsHttpTransport(Settings settings, String host) {
....
HttpClientParams params = new HttpClientParams();
        params.setParameter(HttpMethodParams.RETRY_HANDLER, new DefaultHttpMethodRetryHandler(
                settings.getHttpRetries(), false) {

            @Override
            public boolean retryMethod(HttpMethod method, IOException exception, int executionCount) {
                if (super.retryMethod(method, exception, executionCount)) {
                    stats.netRetries++;
                    return true;
                }
                return false;
            }
        });
//changes Start
 Properties properties = settings.asProperties();
        List<Header> headers = new ArrayList<>();
        for (Map.Entry<Object, Object> entry : properties.entrySet()) {
            String key = entry.getKey().toString();
            if(key.startsWith(HEADER_SETTINGS_PREFIX)){
                headers.add(new Header(key.substring(HEADER_SETTINGS_PREFIX.length() + 1), entry.getValue().toString()));
            }
        }
        if(!headers.isEmpty()){
            params.setParameter("http.default-headers", headers);
        }
//changes end
....
}
```

In order to use this functionality in Spark client side you have to add something like this:
SparkConf sparkConf = <get SparkConf>
 sparkConf.set("spark.es.client.header.es-shield-runas-user", <run_as user name>);

In addition you can provide set of properties spark.es.client.header.[ES-Hadoop custom header name] which will be converted to custom header(s). This could be useful if you are planning to use additional HTTP processors like balancer, proxy, etc. In this case some custom header(s) could be processed by these parties.

Suggested solution is relied on apache httpclient 3.1 which is using in current ES-Hadoop implementation. 
It would be great, if you guys, upgrade it with the latest apache httpclient that allows request/response hooks HttpRequestInterceptor/HttpResponseInterceptor (aside of other improvements). In this case suggested solution could be easier/functional.

**Comment by jasontedor** [comment]
Please open this on the elasticsearch-hadoop repository.
