### ISSUE TITLE
Field stats API skips geo_point fields

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch#20707]
**Elasticsearch version**: master

**Plugins installed**: none

**JVM version**: 1.8.0_102

**OS version**: macOS Sierra

**Description of the problem including expected versus actual behavior**: fields of type `geo_point` are not described in the `_field_stats` output

**Steps to reproduce**:
sense requests: https://gist.github.com/spalger/72050d99ee9dc5a4ee8d1186e9cc05c9
which results in a matching filter, but no `pin.location` field listed in the field_stats output

**Comment by clintongormley** [comment]
@jpountz could you take a look at this?

**Comment by jpountz** [comment]
The current behaviour of this API is to ignore all fields for which we do not know how to compute stats. Geo points are fixable, but should we add other fields like geo shapes as well as meta fields such as `_index`? Those are currently ignored as well.

**Comment by spalger** [comment]
My naive opinion is that all values that work as "field" identifies in queries or aggregations should be included in the stats.

**Comment by javanna** [comment]
This seems to have been fixed by #21947. After that though the field stats API has been removed.
