### ISSUE TITLE
Parse exception for reroute command.

### ISSUE THREAD

**Issue by murali-chevuri** [elastic/elasticsearch#20700]
Hi,

I am using elasticsearch 5.0.0-alpha5 and Xpack 5.0.0-alpha5. I trying to fix unassigned shards with below reroute command. I am getting below parsing exception. Please help.

COMMAND

curl -u elastic:changeme -XPOST http://xxxx:9200/_cluster/reroute -d '{    "commands": [       {         "allocate": {           "index": "collectd--2016.09.06",           "shard": 1,           "node": "xxxx",           "allow_primary": true         }       }     ]}'

ERROR

{"error":{"root_cause":[{"type":"parsing_exception","reason":"no [allocation_command] registered for [allocate]","line":1,"col":48}],"type":"parsing_exception","reason":"[cluster_reroute] failed to parse field [commands]","line":1,"col":48,"caused_by":{"type":"parsing_exception","reason":"no [allocation_command] registered for [allocate]","line":1,"col":48}},"status":400}

**Comment by jasontedor** [comment]
It's `allocate_replica`, `allow_primary` is removed.
