### ISSUE TITLE
Pls help me cannot index 2 location properties in 2 type

### ISSUE THREAD

**Issue by huynhquocbao92** [elastic/elasticsearch#20715]
`"created_at" => "2016-09-15 14:12:57"
"updated_at" => "2016-09-15 14:12:57"
"is_deleted" => 0
"stamp_rally_spot_location" => [
  "location" => [
    "lat" => 35.4285439
    "lon" => 140.2880265
  ]
]`
Because i cannot index 2 location properties in 2 type, so i added location data same above. How to I can filter location when query?
`'filter' => [
    'and' => [
        [
            'geo_distance' => [
                'field' => 'stamp_rally_spot_location',
                'distance' => $distance,
                'distance_type' => 'arc',
                'location'=>[
                    'lat' => floatval($latitude),
                    'lon' => floatval($longitude)
                ]
            ]
        ]
    ]
],`
Please help me. Thank you.

**Comment by andyb-elastic** [comment]
Hi @huynhquocbao92, we use github for bug reports and feature requests. Questions like this are best asked in [the forum](https://discuss.elastic.co/c/elasticsearch)
