### ISSUE TITLE
MLT min_doc_freq, max_doc_freq calculated per shard, not globally

### ISSUE THREAD

**Issue by wewebber** [elastic/elasticsearch#20729]
**Elasticsearch version**: 2.3.3

**Description of the problem including expected versus actual behavior**:

The min_doc_freq, max_doc_freq fields of the MLT query appears to be calculated on a per-shard basis, not globally.  If this is expected behavior it should be noted in the reference documentation.

**Steps to reproduce**:

```
PUT /mytest/
{
   "settings": {
      "index": {
         "number_of_shards": 2
      }
   }
}

PUT /mytest/mydoc/1
{
    "text" : "how green was my valley"
}

PUT /mytest/mydoc/2
{
    "text" : "how green was my valley"
}

PUT /mytest/mydoc/3
{
    "text" : "how green was my valley"
}

PUT /mytest/mydoc/4
{
    "text" : "something different"
}

PUT /mytest/mydoc/5
{
    "text" : "also not the same"
}

PUT /mytest/mydoc/6
{
    "text" : "one other unique thing"
}

GET /mytest/mydoc/_validate/query?rewrite=true
{
   "query": { 
      "mlt": {
         "fields": [
            "text"
         ],
         "like": "how green was my valley",
         "min_term_freq" : 1,
         "min_doc_freq" : 3
      } 
   }
}
```

Output is:

```
{
   "valid": true,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "explanations": [
      {
         "index": "mytest",
         "valid": true,
         "explanation": "+() #ConstantScore(_type:mydoc)"
      }
   ]
}
```

However, same sequence, but with:

```
    "number_of_shards" : 1
```

Gives output:

```
{
   "valid": true,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "explanations": [
      {
         "index": "mytest",
         "valid": true,
         "explanation": "+((text:how text:my text:valley text:was text:green)~1) #ConstantScore(_type:mydoc)"
      }
   ]
}
```

An analogous demonstration for max_doc_freq applies (add four "how green was my valley" documents; set query parameters to "min_doc_freq" : 1, "max_doc_freq" : 3; observe difference between 1 shard and 2 shards).

**Comment by wewebber** [comment]
It occurred to me that the above behavior might have been caused by the use of the _validate API, but if you just do the straight MLT query, you get similar results.  With two shards and "min_doc_freq=1", you get 3 hits; with "min_doc_freq=2" you get 2 hits (i.e. from one shard, nothing from the other); with "min_doc_freq=1" you get no hits.

**Comment by jpountz** [comment]
I don't think this can be fixed in a scalable way, so +1 to add a note about this limitation in the docs.

**Comment by talevy** [comment]
Docs have a lot of work around these features. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).
