### ISSUE TITLE
Strict URL Parsing Rejects Compound `preference` Parameter

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#20769]
**Elasticsearch version**: master

**Plugins installed**: []

**JVM version**: 1.8

**OS version**: any

**Description of the problem including expected versus actual behavior**:
The [`preference` parameter](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-request-preference.html) allows you to limit which shards you execute a search against with the `_shards:x,y,z` property. You can combine this `_shards` configuration with other preferences by separating the items with a semicolon.

So if I want to look for all documents that are hosted on a single shard, and prefer that the operation be executed on the primary shard (not a replica) I would type the following:
```
curl -XPOST ‘localhost:9200/test/test/_search?preference=_shards:0;_primary’
```

This now gets flagged by the new strict URL parsing (https://github.com/elastic/elasticsearch/pull/20722), as it highlights that `_primary` is not recognized:
```
>> {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/test/test/_search] contains unrecognized parameter: [_primary]"}],"type":"illegal_argument_exception","reason":"request [/test/test/_search] contains unrecognized parameter: [_primary]"},"status":400}
```
However, searching with only one preference seems to still work:
```
curl -XPOST ‘localhost:9200/test/test/_search?preference=_shards:0’
>> {"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"test","_type":"test","_id":"3","_score":1.0,"_source":{"c":3}}]}}

curl -XPOST ‘localhost:9200/test/test/_search?preference=_primary’
>> {"took":1,"timed_out":false,"_shards":{"total":2,"successful":2,"failed":0},"hits":{"total":3,"max_score":1.0,"hits":[{"_index":"test","_type":"test","_id":"3","_score":1.0,"_source":{"c":3}},{"_index":"test","_type":"test","_id":"1","_score":1.0,"_source":{"a":1}},{"_index":"test","_type":"test","_id":"2","_score":1.0,"_source":{"b":2}}]}}
```

Not sure why we use a semicolon for this second level separator since semicolons are reserved characters for URLs. If the character is encoded (as “%3B”) the request completes as expected:
```
curl -XGET 'localhost:9200/test/test/_search?preference=_shards:0%3B_primary'
>> {"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"test","_type":"test","_id":"3","_score":1.0,"_source":{"c":3}}]}}
```

**Steps to reproduce**:
The test data I used isn’t really important, just enough to scatter some documents across two shards, but here are the settings and reproduction steps:

```
curl -XPUT localhost:9200/test/ -d '{
  "settings":{
    "number_of_shards":2
  }
}'

curl -XPUT localhost:9200/test/test/1 -d ‘{“a”:1}’
curl -XPUT localhost:9200/test/test/2 -d ‘{“b”:2}’
curl -XPUT localhost:9200/test/test/3 -d ‘{“c”:

#Works
curl -XPOST ‘localhost:9200/test/test/_search?preference=_shards:0’ 
curl -XPOST ‘localhost:9200/test/test/_search?preference=_primary’

#Used to work, now breaks
curl -XPOST ‘localhost:9200/test/test/_search?preference=_shards:0;_primary’

#Works again
curl -XGET 'localhost:9200/test/test/_search?preference=_shards:0%3B_primary'
```

**Describe the feature**:
Should we modify this parameter to use a different separator? I'm wary of continuing use of the semicolon as a list-of-lists separator in a URL. If we're doing strict parsing maybe this should be changed to a different symbol that isn't reserved...

**Comment by nik9000** [comment]
> This now gets flagged by the new strict URL parsing (#20722), as it highlights that _primary is not recognized:

I wonder if it used to just ignore `_primary` without the escaping?

**Comment by jbaiera** [comment]
@nik9000 You might be on to something. Booted up the 5.0.0-beta1 release and tried encoded and unencoded. I'm running this locally with one node, so the replica shards on this index are unassigned.

I expected this to fail because the replica is unassigned.
```
curl -XGET 'localhost:9200/test/test/_search?preference=_shards:0;_replica'
>> {"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"test","_type":"test","_id":"3","_score":1.0,"_source":{"c":3}}]}}
```
... But it doesn't. Now, If we escape the semicolon...
```
curl -XGET 'localhost:9200/test/test/_search?preference=_shards:0%3B_replica'
>> {"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[],"caused_by":{"type":"no_shard_available_action_exception","reason":null,"index_uuid":"d6I_drjZRZydiv4gXBmE5Q","shard":"0","index":"test"}},"status":503}
```

Can you say "Smoking Gun"?

**Comment by jasontedor** [comment]
I think we just need a new separator here since the unescaped form just never worked.
