### ISSUE TITLE
Ensure Painless scripts are pure functions

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#20762]
Today we have `now()` support in painless which is causing all kinds of trouble when it comes to caching. Users that really need a notion of `now()` can pass a parameter to the script that holds the current timestamp and it will be consistent on all shards. Support for out datemath `now` is not needed here since it's really not a commonly used method. We should remove the support for 5.0 GA 

Relates to #20645

**Comment by s1monw** [comment]
@jdconrad can you take a look

**Comment by jdconrad** [comment]
Never mind, I realize that the permanent solution is for a user to pass in a param :)

**Comment by jdconrad** [comment]
Now has been removed from 6.0, 5.1, and 5.0.  Closing this issue.
