### ISSUE TITLE
Service Set up when installing from Tar

### ISSUE THREAD

**Issue by PatBee** [elastic/elasticsearch#20772]
**Elasticsearch version**: 2.4.1

**Plugins installed**: []

**JVM version**: 1.8

**OS version**: Amazon Linux

**Description of the problem including expected versus actual behavior**:
When installing from tar file there appear to be no scripts start up and shutdown from init.d to run elastic search as a service.  Googling for an answer takes me to pages that imply these exist when installing from package managers.  

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by nik9000** [comment]
Right. The expectation is that if you want init scripts that work for your OS you'll use the package manager. If you are installing on an OS that doesn't support that packages we build then our init scripts aren't likely to work for you anyway.
