### ISSUE TITLE
Fast Vector Highlighter fails to highlight when using synonym analyzer in 5.0.0-beta1

### ISSUE THREAD

**Issue by pangyikhei** [elastic/elasticsearch#20781]
**Elasticsearch version**: 5.0.0-beta1

**Plugins installed**: [analysis-icu, ingest-attachment]

**JVM version**: Oracle JDK 1.8.0_101

**OS version**: Windows 10/Windows Server 2012

**Description of the problem including expected versus actual behavior**:
Actual behavior: Fast Vector highlighter fails to highlight search results when using a synonym analyzer on the query in 5.0.0-beta1. Forcing the use of the plain highlighter highlights the synonym match.
Expected behavior: Fast Vector highlighter should highlight the words as in 2.4.0.

**Steps to reproduce**:
 1. Add mapping to index with english wordnet synonyms https://gist.github.com/pangyikhei/27e4e0390533a0b6c2bc185ceb860276

 2. Add document 
~~~~
PUT my_index/my_type/1
{
  "my_string":"the quick brown fox jumped over the lazy dog"
}
~~~~

3..  Search for a word (whether a synonym or not) using the synonym analyzer

~~~~
GET my_index/my_type/_search
{
  "query": {
    "match": {
      "my_string": {
        "query": "fast",
        "analyzer":"synonym"
      }
    }
  },
  "highlight": {
    "fields": {
      "my_string": {}
    }
  }
}
~~~~

**Comment by clintongormley** [comment]
@pangyikhei can you reproduce this issue without using wordnet?  If so could you provide a simple recreation just using inline synonyms?

**Comment by pangyikhei** [comment]
I tried with inline solr, inline wordnet, and solr file synonyms and could reproduce the problem with all of them.

Creating index with mappings and settings for inline solr synonyms: https://gist.github.com/pangyikhei/00e480ac28dfe6c197427568982d406f

Reproduced with previous search without explicitly specifying the highlighter type (should implicitly use the fvh since it is mapped with "term_vector": "with_positions_offsets") and also with explicitly specifying the highlighter type:

    GET my_index/my_type/_search
    {
      "query": {
        "match": {
          "my_string": {
            "query": "agile",
            "analyzer": "synonym"
          }
        }
      },
      "highlight": {
        "fields": {
          "my_string": {
            "type": "fvh"
          }
        }
      }
    }

If I explicitly specify "type": "plain", the synonym gets highlighted.

Even searching for "quick" doesn't highlight "quick" in the my_string field when using "type": "fvh".

The search result:

    {
      "took": 1,
      "timed_out": false,
      "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
      },
      "hits": {
        "total": 1,
        "max_score": 0.27233246,
        "hits": [
          {
            "_index": "my_index",
            "_type": "my_type",
            "_id": "1",
            "_score": 0.27233246,
            "_source": {
              "my_string": "the quick brown fox jumped over the lazy dog"
            }
          }
        ]
      }
    }

**Comment by clintongormley** [comment]
Bug confirmed.  This used to work in 2.x.  I wonder if terms are not being extracted properly from a synonyms query?

Copy-pasteable recreation:

<details>

    PUT my_index
    {
      "settings": {
        "analysis": {
          "filter": {
            "synonym": {
              "format": "solr",
              "type": "synonym",
              "synonyms": [
                "quick, fast, agile, speedy"
              ]
            }
          },
          "analyzer": {
            "synonym": {
              "filter": [
                "synonym"
              ],
              "tokenizer": "standard",
              "ignore_case": "true"
            }
          }
        }
      },
      "mappings": {
        "my_type": {
          "dynamic_templates": [
            {
              "strings": {
                "mapping": {
                  "term_vector": "with_positions_offsets",
                  "type": "text",
                  "store": true,
                  "fields": {
                    "raw": {
                      "ignore_above": 4000,
                      "index": true,
                      "type": "keyword"
                    }
                  }
                },
                "match_mapping_type": "string"
              }
            }
          ]
        }
      }
    }
    
    PUT my_index/my_type/1
    {
      "my_string": "the quick brown fox jumped over the lazy dog"
    }
    
    GET my_index/my_type/_search
    {
      "query": {
        "match": {
          "my_string": {
            "query": "agile",
            "analyzer": "synonym"
          }
        }
      },
      "highlight": {
        "fields": {
          "my_string": {
            "type": "fvh"
          }
        }
      }
    }

</details>

@jimferenczi could you take a look at this please?
