### ISSUE TITLE
Reindex failures clarification

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#20787]
I'm writing some client side code (using nest) to use server side reindexing. I noticed that there is a failures array (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html). I was trying to figure out if the `id` property was a scroll id or the document id. 

The type in nest is `BulkIndexByScrollFailure` and both the elastic docs don't have any real clarification on what's included. I took a look at the source via github (BulkIndexByScrollResponse) and was trying to track down where this happens (kind of hard without a real ide) and wasn't having very much luck.

cc @Mpdreamz

**Comment by nik9000** [comment]
If there is an id field then it is the document's id that failed.

**Comment by niemyjski** [comment]
Thanks, I wasn't sure the type names kinda made me think it was a scrollid and it could of been either. Once I get done with this, I'll try and write something up for the docs.
