### ISSUE TITLE
Term aggregation on array not_analyzed field include regex filter issue

### ISSUE THREAD

**Issue by amitanjani** [elastic/elasticsearch#20795]
I was using elasticsearch 1.7.3 and my term aggregate query

`"aggregations" : {"tagsList" : {  "terms" : {
     "field" : "tagsList.tagsList_sort",
     "size" : 100,
     "order" : {
           "_term" : "asc"
       },
      "include" : "((?i).*accoun.*)"  }}`

Recently I upgraded my es version to 2.3.x and above query is not working. Please suggest similar query for esv2.3.x

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
