### ISSUE TITLE
5.0.0-beta1 unable to successfully call elasticsearch.bat

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#20809]
I'm in the process of tracking this issue down with appveyor.. But when I run elasticsearch.bat from powershell (`Start-Process "$(Get-Location)\elasticsearch-node1\bin\elasticsearch.bat" -RedirectStandardError "$(Get-Location)\elasticsearch-node1\error.txt" -RedirectStandardOutput "$(Get-Location)\elasticsearch-node1\log.txt"`

I get the following text in `error.txt`: `\Java\jdk1.8.0\bin\java.exe was unexpected at this time.`

I thought it could be a pathing issue due to the error, but it's escaped. Looking through the batch file it looks like it's calling `"%JAVA%" %ES_JAVA_OPTS% %ES_PARAMS% -cp "%ES_CLASSPATH%" "org.elasticsearch.bootstrap.Elasticsearch" !newparams!`

```
C:\Users\appveyor>echo %java%
%java%

C:\Users\appveyor>echo "%java_home%"
"C:\Progra~1\Java\jdk1.8.0"
```

**Comment by niemyjski** [comment]
If anyone runs into this issue, it's caused by the java_home environment variable was not set not in the 8.3 DOS format, like `C:\Progra~1\Java\jdk1.8.0`

**Comment by smarts** [comment]
Is there any way to fix this from the Elasticsearch side?

**Comment by jasontedor** [comment]
I opened #21921.
