### ISSUE TITLE
Ingest API Default Pipeline

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#20804]
Would it make sense for Ingest API calls to have a default pipeline behavior in the case where [dynamic routing](https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/491) is happening and the pipeline might not exist?

```
PUT my-index/my-type/my-id?pipeline=maybe_exists&default_pipeline=definitely_exists
{
  "foo": "bar"
}
```

**Comment by clintongormley** [comment]
I don't like this at all.  It is messy and inconsistent.  Later on, when you retrieve the document, you have no idea which pipeline was applied.  I looked at your link to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/491 but that problem can be solved with logstash config.
