### ISSUE TITLE
Rest Client Dependencies

### ISSUE THREAD

**Issue by isaias** [elastic/elasticsearch#20815]
**Elasticsearch version**: Elastic Rest Client 5.0.0-beta1

**Plugins installed**: []

**JVM version**: java version "1.8.0_101"

**OS version**: CentOs

**Description of the problem including expected versus actual behavior**:

Using Rest Client version 5.0.0-alpha5 the dependencies for httpcore-nio and httpasyncclient are included automatically but for 5.0.0-beta1 they aren't.  

**Steps to reproduce**:
 1. Just declare "org.elasticsearch.client" % "rest" % "5.0.0-beta1" and see that dependencies are't downloaded and declare 5.0.0-alpha5 and see that dependencies will be downloaded.

What is the expected behavior?

**Comment by nik9000** [comment]
Does should be included.

**Comment by clintongormley** [comment]
@javanna @rjernst ?

**Comment by rjernst** [comment]
I just tested in both maven and gradle, and the dependencies look like they are correctly being resolved. Can you elaborate more with your configuration and what you actually see as output that indicates to you they are not included transitively?

**Comment by isaias** [comment]
@rjernst Maybe can be a problem using SBT + Scala. After your comment I've created a simple maven project and dependencies are correctly downloaded. I'll verify why 5.0.0-alpha5 download all dependencies using SBT and beta1 doesn't .

I'm closing it.
