### ISSUE TITLE
jarHell error

### ISSUE THREAD

**Issue by chilly** [elastic/elasticsearch#20812]
master  commit 2e1539b879ad8e9cbcb0a3fd963403816e4eb177

> gradle build -x test -x integTest

:benchmarks:jarHell
checking for jar hell...
Exception in thread "main" java.lang.IllegalStateException: jar hell!
class: org.joda.time.base.BaseDateTime
jar1: /Users/chilly/workspace/elasticsearch/core/build/distributions/elasticsearch-6.0.0-alpha1-SNAPSHOT.jar
jar2: /Users/chilly/.gradle/caches/modules-2/files-2.1/joda-time/joda-time/2.9.4/1c295b462f16702ebe720bbb08f62e1ba80da41b/joda-time-2.9.4.jar
	at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:277)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:187)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:88)
	at org.elasticsearch.bootstrap.JarHell.main(JarHell.java:70)
:benchmarks:jarHell FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':benchmarks:jarHell'.
> Process '/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin/java -cp /Users/chilly/workspace/elasticsearch/benchmarks/build/classes/main:/Users/chilly/workspace/elasticsearch/benchmarks/build/resources/main:/Users/chilly/workspace/elasticsearch/core/build/distributions/elasticsearch-6.0.0-alpha1-SNAPSHOT.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.openjdk.jmh/jmh-core/1.15/c4a847a017c200eb06dde350f146d5be9cd6a54d/jmh-core-1.15.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.openjdk.jmh/jmh-generator-annprocess/1.15/ed3beec312be8e3db2bdca478a20949ce0a51293/jmh-generator-annprocess-1.15.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/net.sf.jopt-simple/jopt-simple/4.6/306816fb57cf94f108a43c95731b08934dcae15c/jopt-simple-4.6.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-math3/3.2/ec2544ab27e110d2d431bdad7d538ed509b21e62/commons-math3-3.2.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-core/6.2.0/849ee62525a294416802be2cacc66c80352f6f13/lucene-core-6.2.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-analyzers-common/6.2.0/d254d52dd394b5079129f3d5f3bf4f2d44a5936e/lucene-analyzers-common-6.2.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-backward-codecs/6.2.0/b625bb21456b3c0d1e5e431bced125cb060c1abd/lucene-backward-codecs-6.2.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-grouping/6.2.0/9527fedfd5acc624b2bb3f862bd99fb8f470b053/lucene-grouping-6.2.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-highlighter/6.2.0/7ca342372a3f45e32bbd21cecaa757e38eccb8a5/lucene-highlighter-6.2.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-join/6.2.0/da0b8de98511abd4fe9c7d48a353d17854c5ed46/lucene-join-6.2.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-memory/6.2.0/bc9e075b1ee051c8e5246c237c38d8e71dab8a66/lucene-memory-6.2.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-misc/6.2.0/94ddde6312566a4da4a50a88e453b6c82c759b41/lucene-misc-6.2.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-queries/6.2.0/dce47238f78e3e97d91dc6fefa9f46f07866bc2b/lucene-queries-6.2.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-queryparser/6.2.0/17ef728ac15e668bfa1105321611548424637645/lucene-queryparser-6.2.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-sandbox/6.2.0/520183f7b9aba77a26e224760c420a3844b0631a/lucene-sandbox-6.2.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-spatial/6.2.0/8dba929b66927b936fbc76103b109ad6c824daee/lucene-spatial-6.2.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-spatial-extras/6.2.0/3b5a6ef5cd90c0218a72e9e2f7e60104be2447da/lucene-spatial-extras-6.2.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-spatial3d/6.2.0/fcdb0567725722c5145149d1502848b6a96ec18d/lucene-spatial3d-6.2.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-suggest/6.2.0/3d9d526c51f483d27f425c75d7e56bc0849242d6/lucene-suggest-6.2.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.elasticsearch/securesm/1.1/1e423447d020041534be94c0f31a49fbdc1f2950/securesm-1.1.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/com.carrotsearch/hppc/0.7.1/8b5057f74ea378c0150a1860874a3ebdcb713767/hppc-0.7.1.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/joda-time/joda-time/2.9.4/1c295b462f16702ebe720bbb08f62e1ba80da41b/joda-time-2.9.4.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.joda/joda-convert/1.2/35ec554f0cd00c956cc69051514d9488b1374dec/joda-convert-1.2.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/1.15/3b132bea69e8ee099f416044970997bde80f4ea6/snakeyaml-1.15.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.8.1/fd13b1c033741d48291315c6370f7d475a42dccf/jackson-core-2.8.1.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.dataformat/jackson-dataformat-smile/2.8.1/5b73867bc12224946fc67fc8d49d9f5e698d7f/jackson-dataformat-smile-2.8.1.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml/2.8.1/eb63166c723b0b4b9fb5298fca232a2f6612ec34/jackson-dataformat-yaml-2.8.1.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.dataformat/jackson-dataformat-cbor/2.8.1/3a6fb7e75c9972559a78cf5cfc5a48a41a13ea40/jackson-dataformat-cbor-2.8.1.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/com.tdunning/t-digest/3.0/84ccf145ac2215e6bfa63baa3101c0af41017cfc/t-digest-3.0.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.hdrhistogram/HdrHistogram/2.1.6/7495feb7f71ee124bd2a7e7d83590e296d71d80e/HdrHistogram-2.1.6.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.locationtech.spatial4j/spatial4j/0.6/21b15310bddcfd8c72611c180f20cf23279809a3/spatial4j-0.6.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/com.vividsolutions/jts/1.13/3ccfb9b60f04d71add996a666ceb8902904fd805/jts-1.13.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.7/8de00e382a817981b737be84cb8def687d392963/log4j-api-2.7.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.7/a3f2b4e64c61a7fc1ed8f1e5ba371933404ed98a/log4j-core-2.7.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-1.2-api/2.7/39f4e6c2d68d4ef8fd4b0883d165682dedd5be52/log4j-1.2-api-2.7.jar:/Users/chilly/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna/4.2.2/5012450aee579c3118ff09461d5ce210e0cdc2a9/jna-4.2.2.jar org.elasticsearch.bootstrap.JarHell' finished with non-zero exit value 1

mac os java version "1.8.0_74"

**Comment by s1monw** [comment]
nothing to do here. there is no issue our master builds just fine

**Comment by chilly** [comment]
how to solve this problem ?

**Comment by clintongormley** [comment]
@chilly clean up your classpath so that it doesn't have duplicate libraries

**Comment by chilly** [comment]
solved.
gradle clean build -x test -x integTest
