### ISSUE TITLE
Phrase suggester under _search does not execute match_all query by default

### ISSUE THREAD

**Issue by bharvidixit** [elastic/elasticsearch#20813]
**Elasticsearch version**: 5.0.0-beta1

**Plugins installed**: []

**JVM version**: 1.8.0_72

**OS version**: Ubuntu 15

**Description of the problem including expected versus actual behavior**:
While using phrase suggester with query, the total hots are always 0. Means match_all query is not getting executed by default. This was running fine with Elasticsearch 2.4.0 

**Steps to reproduce**:
_1. Create an index and index one document with following commands_
curl -XPUT "http://localhost:9200/test_index"

curl -XPUT "http://localhost:9200/test_index/test_type/1" -d'
{"text":"united states"}'

_2. Execute following search query:_
curl -XGET "http://localhost:9200/test_index/_search?pretty" -d'
{
   "suggest": {
      "text": "Unitd States",
      "our_suggestion": {
         "phrase": {
            "field": "text"
         }
      }
   }
}'

_This will yield following response_
![image](https://cloud.githubusercontent.com/assets/10341430/19212737/501d170e-8d75-11e6-9976-13aa613888c9.png)

_If you include match_all query explicitly, it runs fine:_
curl -XGET "http://localhost:9200/test_index/_search?pretty" -d'
{
   "query": {
      "match_all": {}
   },
   "suggest": {
      "text": "Unitd States",
      "our_suggestion": {
         "phrase": {
            "field": "text"
         }
      }
   }
}'

![image](https://cloud.githubusercontent.com/assets/10341430/19212745/904ab52a-8d75-11e6-9f47-4d2783a197bc.png)

**Comment by clintongormley** [comment]
This is still present in rc1 - @areek could you take a look please?

thanks for reporting @bharvidixit

**Comment by clintongormley** [comment]
Actually, I'm thinking that this is a feature instead of a bug.  The `_suggest` end point is deprecated in favour of the `_search` end point.  So if all you want to do is use suggesters, why run a search by default as well?

I think all that needs changing here is the documentation.

**Comment by bharvidixit** [comment]
In this case, i think the hits array needs to be removed from the response. Showing 0 hits looks confusing.

**Comment by clintongormley** [comment]
@bharvidixit makes sense

**Comment by talevy** [comment]
We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal for updating the documentation (including +1s).
