### ISSUE TITLE
Inconsistent _parent field query

### ISSUE THREAD

**Issue by jprante** [elastic/elasticsearch#2082]
There is a small inconsistency in the _parent field query. 

With term query, only **parent_id** is required, but with e.g. wildcard query, the format **parent_type#parent_id** is required, as described in http://www.elasticsearch.org/guide/reference/api/delete.html

Demonstration: a curl-based parent/child example script can be found here: https://gist.github.com/3047912

Alternative - term query

	curl -XGET 'http://localhost:9200/test/library/_search?pretty' -d '{
	      "query": {
	            "term" : {
	                  "_parent" : "1"
	             }
	      }
	}'

Alternative - wildcard query
	
	curl -XGET 'http://localhost:9200/test/library/_search?pretty' -d '{
	      "query": {
	            "wildcard" : {
	                  "_parent" : "title#1"
	             }
	      }
	}'

Both yield same result.

Suggestion: there should be no special format or query types allowed for _parent queries to avoid confusion. Possibly every _parent query should just be forced to become a term query. The docs at http://www.elasticsearch.org/guide/reference/mapping/parent-field.html need a query example. http://www.elasticsearch.org/guide/reference/api/delete.html should be cleaned up.

**Comment by martijnvg** [comment]
Better late than never... I don't exactly recall how the support for `_parent` field query was in 2012, but at the moment both formats (with and without parent type) are supported for both the term and wildcard queries.

The reason why there is a special type syntax is that in the case that there are multiple parent types, one can pick the parent type to filter by.

**Comment by martijnvg** [comment]
this is no longer inconsistent
