### ISSUE TITLE
Bounding the processors count to 32 still valid?

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#20828]
Following https://github.com/elastic/elasticsearch/issues/3478 we limited the maximum number of processors on which the thread pools are created to 32. Since that version of ES this was observed on, many more versions (with many improvements) were released.

Is this limitation still valid?
I would think yes, but this raises two more issues that might need some thought:
- is there a **minimum** memory size (RAM or HEAP?) above which we can safely increase this count to the real number of cores using the **processors** setting?
- does this issue apply for smaller than 32 values? For example, a machine with 2GB RAM and 16 cores would have similar issues?

**Comment by jasontedor** [comment]
The processors limitation isn't directly about physical memory. In general it's about limiting the number of threads; with the various thread pools that are sized as a function of the number of logical processors, Elasticsearch creates a tremendous number of threads. 
 - this can lead to `OutOfMemoryException` if `ulimit -u` is too low (note that the message in this case is `unable to create native threads`, I've always considered `OutOfMemoryException` to a be poor choice for this underlying cause)
 - each thread does have a fixed memory cost (1 MB per thread for its stack with the JVM defaults on a 64-bit JVM) although this is off heap; on a machine with 32 logical processors Elasticsearch creates hundreds of threads
 - these threads have to be scheduled on actual cores; if there are way more runnable threads than there are actual cores, the OS will just spend all its time context switching across the threads and this is bad for performance

I do wonder what the underlying reason for this question is though?

**Comment by astefan** [comment]
Thanks @jasontedor. I was a bit mislead (and didn't look at the error itself properly in https://github.com/elastic/elasticsearch/issues/3478) by the description of the previous issue where the author mentioned RAM size.

> if there are way more runnable threads than there are actual cores, the OS will just spend all its time context switching across the threads

The size of the thread pools is sized according to the number of processors and on a machine with X cores (X<=32) we create the thread pools according to our defaults for each type of pool. So, the number of runnable threads compared to the number of cores should have the same ratio for 32 cores or 48 cores.

We also support the multi nodes per physical machine scenario where a 48 cores machine divided by 3 ES nodes (with proper `processors` setting) would create more threads in total than a single ES node on the same machine since a `processors: 16` wouldn't break the 32 limit.

> if `ulimit -u` is too low

And this can be adjusted accordingly I suppose.

**Comment by astefan** [comment]
No hidden reason :-), just want to understand the limits and the recommendations we can make.

**Comment by jpountz** [comment]
I tend to agree with @astefan that there is something we should do there. Either we should remove this artificial limit so that the default configuration can make use of all resources of a machine, or we should keep it and add a note to our setup instructions to configure the number of processors in the `elasticsearch.yml` on machines that have more than 32 processors.

My preference would be to remove this limit and make Elasticsearch more reasonable about the number of threads. For instance there is no reason to have different threadpools for `bulk` and `index`, or for `search` and `get`: these are exactly the same operations.

**Comment by jpountz** [comment]
Also for the record, the situation might already be a bit better today than when the limit was introduced, for instance we divided the size of the `search` threadpool by 2 and removed the `percolate` thread pool (since percolation is now a `search` operation).

**Comment by mikemccand** [comment]
> My preference would be to remove this limit and make Elasticsearch more reasonable about the number of threads.

+1

On my 72 core box I have to override that default 32 max core count.
