### ISSUE TITLE
about space

### ISSUE THREAD

**Issue by feiniu5566** [elastic/elasticsearch#20826]
hello  
I'm feiniu5566  and i use es for a lang time.
Today  i want to update es from 1.0 to 2.4
and have some questions.
One : about space
Exception:
Exception in thread "main" SettingsException[Failed to load settings from [elasticsearch.yml]]; nested: ElasticsearchParseException[malformed, expected settings to start with 'object', instead was [VALUE_STRING]];

Here is solutions:
http://www.cnblogs.com/jiu0821/p/5624908.html

So  can you pay atteation to this problem    
Thanks
A boy from China  .
ps: My English is so pool ,haha.

**Comment by jasontedor** [comment]
YAML parsing is very strict, that's what you're running to here. A space is needed to separate the key from the value.

From the [spec](http://www.yaml.org/spec/1.2/spec.html#id2759963):

>  Mappings use a colon and space (“: ”) to mark each key: value pair.
