### ISSUE TITLE
Allow plugins to register custom statistic types?

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#20824]
Today if plugins have stats that need to be exposed then these plugins typically introduce their own API(s) in order to share their stats. This works, but isn't ideal as it does introduce more APIs that need to be monitored / checked. Also if information needs to be displayed in one of the cat apis too, then this requires adding an additional endpoint for the cat api. 

I think it would be worth to explore if we can make statistics pluggable. We could start with custom node level info / stats. So if a plugin registers custom node level stats then it would be displayed in both the node stats and nodes cat APIs. This would make it easier for plugins to expose statistics and reduces the amount of endpoints that need to be monitored by third party systems.

**Comment by rjernst** [comment]
I liked this idea and discussed a similar idea with @clintongormley a couple weeks ago. I think the api should include plugging in node infos as well. My idea was to have methods on the base service interface like `getInfos()` and `getStats()`, and then have Node construction pull them all together.

**Comment by martijnvg** [comment]
While this is still idea is still valid, nothing has happened with it for almost 1.5 year. Closing this for now and hopefully in the future stats api get refactored in such a way that this idea is possible.
