### ISSUE TITLE
Elasticsearch-PHP requires cURL, or a custom HTTP handler

### ISSUE THREAD

**Issue by onerciller** [elastic/elasticsearch#20823]
Hi, I have been using lumen 5.2 resftul api. Normally, I don't getting error such when it is running on host but,  I am getting error this way "**Elasticsearch-PHP requires cURL, or a custom HTTP handler**" 
What could be reason for this.

**Comment by clintongormley** [comment]
Hi @onerciller 

Please open this issue on the elasticsearch-php repo instead
