### ISSUE TITLE
Add circuit breaker for completion suggestor FST

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#20837]
We currently allow users to monitor the size of their FSTs using the nodes stats API. However, it would be good if we could add the memory used by the completion suggester's FST into the circuit breaker (probably the fielddata circuit breaker) to prevent an OOME in the event there is not enough memory for the FST.

**Comment by jpountz** [comment]
For the record, I think @areek has plans to move FSTs to disk, which would remove the need for such a circuit breaker. It doesn't mean we should not do it, but if it is significant work we might want to just wait for FSTs to become disk-based.

**Comment by dakrone** [comment]
> For the record, I think @areek has plans to move FSTs to disk, which would remove the need for such a circuit breaker.

That would be great!

**Comment by danielmitterdorfer** [comment]
Completion suggesters are still held in memory but this memory usage is already tracked via the accounting circuit breaker in https://github.com/elastic/elasticsearch/blob/f033c3fb8955d3ac01e5551556b67a5b7a172d95/server/src/main/java/org/elasticsearch/index/engine/RamAccountingRefreshListener.java#L72 (Lucene reports that memory usage via `SegmentReader#ramBytesUsed()`)
