### ISSUE TITLE
elasticsearch remove index settings

### ISSUE THREAD

**Issue by mixiaojiong** [elastic/elasticsearch#20831]
**Elasticsearch version**:2.3.5

**Plugins installed**: []

**JVM version**:1.7

**OS version**:centos 6.7

This is my index config.
{
  "index": {
    "creation_date": "1473673683011",
    "routing": {
      "allocation": {
        "enable": "all",
        "exclude": {
          "_name": "",
          "_ip": ""
        },
        "include": {
          "_name": "*",
          "_ip": "10.110.18.21,10.110.16.43,10.110.16.44,10.110.16.50"
        },
        "disable_allocation": "default"
      }
    },
    "uuid": "mx23AlX4QJ2JSk0EdFeX2g",
    "number_of_replicas": "0",
    "number_of_shards": "5",
    "version": {
      "created": "2040099"
    }
  }
}

I want to remove 
"routing": {
      "allocation": {
        "enable": "all",
        "exclude": {
          "_name": "",
          "_ip": ""
        },
        "include": {
          "_name": "*",
          "_ip": "10.110.18.21,10.110.16.43,10.110.16.44,10.110.16.50"
        },
        "disable_allocation": "default"
      }
    },

How to operate?

**Comment by jasontedor** [comment]
Please ask questions on the [Elastic Discourse forum](https://discuss.elastic.co); GitHub is reserved for feature requests and bug reports.
