### ISSUE TITLE
Multiple template matching no longer works in Elasticsearch 2.4.1

### ISSUE THREAD

**Issue by seallison** [elastic/elasticsearch#20849]
**Elasticsearch version**: 2.4.1

**Plugins installed**: []

**JVM version**: 1.8.0_91

**OS version**: OS X 10.11.6 and Amazon Linux 2016.03

**Description of the problem including expected versus actual behavior**: In 1.7.5, [multiple template matching](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/indices-templates.html#multiple-templates) worked as documented. In 2.4.1, [multiple template matching](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html#multiple-templates) does not work if the template refers to an analyzer defined in a previous template.

**Steps to reproduce**:
 1. Create a template that defines a custom analyzer. This template matches all indices ("template": "*") and is ordered first ("order": 0).
 2. Create a template that defines a mapping and uses the custom analyzer from the first template.
 3. The second template cannot be created with Elasticsearch 2.4.1, but this has worked in all prior 1.x releases of Elasticsearch.

A gist of the recreate steps is here: https://gist.github.com/seallison/a4b916a1606c8f8ecc1450a021996509

**Comment by jasontedor** [comment]
Duplicates #20479
