### ISSUE TITLE
add `ignore_missing` to `split` pipeline processor 

### ISSUE THREAD

**Issue by djschny** [elastic/elasticsearch#20840]
**Elasticsearch version**: v5.0.0-rc1

**Description of the problem including expected versus actual behavior**:

The `split` processor throws an error if the json element is not present in the document. Request to have it implement `ignore_missing` to resolve like what was done for other processors.

See https://github.com/elastic/elasticsearch/issues/19995 for reference.

**Comment by djschny** [comment]
@talevy and @eskibars when you get a chance would you mind looking at this please?

**Comment by talevy** [comment]
@djschny apologies for the delay (I know I lied to you about how soon this would be done 😸)

let me know what you think!

**Comment by djschny** [comment]
Looks good from what I can tell. Thank you!
