### ISSUE TITLE
Expose splitOnWhitespace in `Query String Query`

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#20841]
Since Lucene 6.2.0 it is possible to disable the parse on whitespace behavior of the query parser, 

> instead, preferably the queryparser would parse around only real 'operators'. 

We should expose this option in the `query_string_query`:

```
{
    "query_string" : {
        "fields" : ["title", "text"],
        "query" : "foo bar",
        "split_on_whitespace": false
    }
}
```

this would solve many cases where splitting on whitespace is problematic (ngram, shingles, multi word synonyms). 
The `match query` is usually a good alternative for these cases except for users that relies on some features of the `query_string_query` not present in the `match query` (boolean operators, explicit prefix word or phrase, ...).

Note that this is already possible to disable the splitting on whitespace in the `simple query string query`. The `flags` option can be used to disable the whitespace in the grammar though it is not documented.

**Comment by jpountz** [comment]
+1 to expose it. It would be nice that both queries expose this feature the same way eventually, even though it doesn't look easy to me.

> The flags option can be used to disable the whitespace in the grammar though it is not documented.

Even though the documentation is (too) minimal, it looks documented to me:
https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-simple-query-string-query.html#_flags

**Comment by jimferenczi** [comment]
> +1 to expose it. It would be nice that both queries expose this feature the same way eventually, even though it doesn't look easy to me.

Or maybe we can change the default and make the splitOnWhitespace optional ;). This would fix the ambiguity between `match_query` and query parser based query. IMO the user should not have to read ten pages about query parsing to understand that this option should be used or not. If we can make it harmless for cases where it would not be required we can make it the default in 6.0 ?

**Comment by jimferenczi** [comment]
Discuss in FixItFriday, we had an agreement that splitOnWhitespace=false should be the default but it would change the expectations for a lot of users so the proposed plan is to expose the feature in 5.x (with default to true) and change the default to false in 6.0. This would give the ability for the users to test it before upgrading to 6. Saved queries (percolator, ...) could also be problematic so maybe we should add an upgrade path for these.

**Comment by clintongormley** [comment]
See https://github.com/elastic/elasticsearch/pull/20925#issuecomment-254223125

**Comment by hteleb** [comment]
I have a problem on this, I am using Amazon ElasticSearchService, eventhough i set "split_on_whitespace":false" but still split phrase into tokens as per query validation as follows:

{  
               "query_string":{  
                  "query": "imperial college london",
                  "fields": ["audoc.affilnav"],
                  "split_on_whitespace":false,
               }
            }

"explanation": "+docproperties.doc_type:apr +audoc.authlast:jackson +audoc.affilnav:imperial college london"


any idea?

**Comment by hteleb** [comment]
"split_on_whitespace" does not work when include wildcard

 {  
               "query_string":{  
                  "query": "imperial colle?e london",
                  "fields": ["audoc.affilnav"],
                  "split_on_whitespace":false
               }
            }

"explanation": "+(audoc.affilnav:imperial audoc.affilnav:colle?e audoc.affilnav:london)"

**Comment by jimczi** [comment]
@hteleb see https://github.com/elastic/elasticsearch/issues/8026#issuecomment-334493730
We have the discuss forum for question like this.
