### ISSUE TITLE
Add a commons VFS repository to the shared file system repository capabilities

### ISSUE THREAD

**Issue by garpinc** [elastic/elasticsearch#20868]
**Elasticsearch version**: 2.4.1

**Plugins installed**: []

**JVM version**:1.8

**OS version**:Windows 10

**Describe the feature**:  1) I'd like the location path.repo and in the snapshot (https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html) settings to be able to refer to a VFS location. This way you are not constrained to a mounted drive and rather you can access the files via any plugin that commons VFS (https://commons.apache.org/proper/commons-vfs/) supports.

**Comment by tlrx** [comment]
This issue is two years old and didn't get much attraction, so I'm going to close the issue. If anyone is interested in revived it please feel free to comment or +1.
