### ISSUE TITLE
Ability to access ctx variable within Lambda function

### ISSUE THREAD

**Issue by gingerwizard** [elastic/elasticsearch#20869]
Watcher painless scripts typically need to access ctx variables.  Currently this is not possible within a Lambda function. This requires the user to assign ctx values to temporary vars, thus bloating the script.

**Comment by clintongormley** [comment]
@gingerwizard for clarity, could you provide a sample of what you have to do today and what you'd like to be able to do?

**Comment by gingerwizard** [comment]
Sure @clintongormley simple example. 

Consider this simple script:

`def hosts = ctx.payload.aggregations.per_host.buckets; if (hosts.size() == 0) return false; return hosts.stream().anyMatch(p -> p.per_minute.buckets[p.per_minute.buckets.length - 1].iowait_deriv.value > ctx.metadata.threshold);`

The ctx.medatadata.threshold var is not accessible within the anyMatch Lambda function.  Thus you have to push it into a temporary variable.

`def threshold=ctx.metadata.threshold; def hosts = ctx.payload.aggregations.per_host.buckets; if (hosts.size() == 0) return false; return hosts.stream().anyMatch(p -> p.per_minute.buckets[p.per_minute.buckets.length - 1].iowait_deriv.value > threshold);`

Minor issue but its not uncommon to use the contents of ctx extensively so it does result in the scripts being unnecessarily verbose.

**Comment by jdconrad** [comment]
This is fixed.  Closing.
