### ISSUE TITLE
Sort value of certain dates is incorrect

### ISSUE THREAD

**Issue by chaudum** [elastic/elasticsearch#20865]
**Elasticsearch version**: 2.4.1

**Plugins installed**: []

**JVM version**:
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

**OS version**:
OSX 10.11.6
Darwin local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

When executing a query using sorting by field values against an index that has a date field returns incorrect sort values (milliseconds-since-the-epoch) for certain dates.

**Steps to reproduce**:

 1. Create index with date field
```
http PUT :9200/ts_index  mappings:='{"default": {"properties": {"ts": {"type": "date"}}}}'
```

 2. Add document with ts = date `1970-01-01T00:00:01Z` (= `1000L`)

```
http PUT :9200/ts_index/default/1 ts=1000
```

 3. Search index and sort by ts field

```
http GET :9200/ts_index/default/_search  query:='{"match_all": {}}' sort:='[{"ts": {}}]' fields:='["ts"]'
```

```json
{
    "_shards": {
        "failed": 0,
        "successful": 5,
        "total": 5
    },
    "hits": {
        "hits": [
            {
                "_id": "1",
                "_index": "ts_index",
                "_score": null,
                "_type": "default",
                "fields": {
                    "ts": [
                        "1000"
                    ]
                },
                "sort": [
                    -30610224000000 /* <- wrong */
                ]
            }
        ],
        "max_score": null,
        "total": 1
    },
    "timed_out": false,
    "took": 49
}
```

https://gist.github.com/chaudum/7a0a70456e7ea90822fe8e2c1396d4e1

I've tested with date values from 0-999 (which return correct sort value) and quickly tested a few values between 1000 and 9999 (which do not seem to work) and above 10000 which works again.
Also tested with arbitrarily high values (e.g. `99999999999L`) which also do not work.

**Describe the feature**:

**Comment by cbuescher** [comment]
I problem here is that when indexing "1000" with the default date mapping (which parses dates as  `"strict_date_optional_time||epoch_millis"`), it treats this as the year 1000 AD. If you index a document with `{ "ts" : "1000-01-01T00:00:00Z" }` you also get the same negative sort value as in your example. If you specify `"format" : "epoch_millis"` in your mappings for the date field everything works as expected for me.

**Comment by chaudum** [comment]
thanks for clarification @cbuescher !
