### ISSUE TITLE
docs: snapshot restore versions

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch#20866]
The docs page for all version of snapshot / restore should explain the limitations in how they can be restored in the future.

> You can restore indices that were created in the previous major version only.  Indices that were created before the previous major version (even if they were snapshotted in the previous major version) cannot be restored.

> Create an index in 2.x, snapshot it, restore in 5.x [supported]
> Create an index in 1.x, snapshot it, restore in 2.x [supported]
> Create an index in 1.x, snapshot it in 2.x, restore in 5.x [ NOT supported]
> Create an index in 1.x, reindex it in 2.x, snapshot it in 2.x, restore in 5.x [supported]

**Comment by nik9000** [comment]
I'm happy to write something up. Usually we write these changes against master and backport to a few places. In that case it'd be normal to backport to the 5.x and 5.0 and 2.4 branches. Are you suggesting going all the way back to 1.7 just so we get good coverage?

**Comment by jpcarey** [comment]
@nik9000 yes, 1.7 should get a notice as well, since questions will arise from any of our three major versions.
