### ISSUE TITLE
Refactor code for module core

### ISSUE THREAD

**Issue by kunal642** [elastic/elasticsearch#20878]
Removed unnecessary code from core module
Refactored code for core module

**Comment by clintongormley** [comment]
I think this was opened in error.  Closing

**Comment by kunal642** [comment]
@clintongormley: I havent pushed to the branch yet. I am working on this issue.
Please reopen the issue

**Comment by clintongormley** [comment]
@kunal642 open a PR when it is ready, no need for an issue here

**Comment by kunal642** [comment]
@clintongormley: Sure, Thanks
