### ISSUE TITLE
how to change mapping or field type

### ISSUE THREAD

**Issue by sylarhero** [elastic/elasticsearch#20879]
In the process of using elasticsearch, I need to set the not_analyzed for some fields, but the amount of data is very large,how to do this?

**Comment by sylarhero** [comment]
or can i copy the fields data to a new index?

**Comment by cbuescher** [comment]
Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co/) and [IRC channels](https://www.elastic.co/community) for general questions like this.
