### ISSUE TITLE
Cannot install elasticsearch service on Windows 2012 R2 server

### ISSUE THREAD

**Issue by mike-mosher** [elastic/elasticsearch#20899]
**Elasticsearch version**:  5.0.0-rc1

**Plugins installed**: none

**JVM version**: jdk1.8.0_101

**OS version**: Windows 2012 R2 64-bit

**Description of the problem including expected versus actual behavior**:
Cannot install the service.  
- I have the following environment variables set:
  - JAVA_HOME:  C:\Program Files\Java\jdk1.8.0_101
  - ES_HEAP_SIZE: 8g
- I have verified that jvm.options have the following lines commented out:
```
## -Xms8g
## -Xmx8g
```

I run the following: `.\elasticsearch-service.bat install elasticsearch-5.0.0-rc1`

I get the following output:

```
Error: encountered environment variables that are no longer supported
Use jvm.options or ES_JAVA_OPTS to configure the JVM
ES_HEAP_SIZE=8g: set -Xms8g and -Xmx8g in jvm.options or add "-Xms8g -Xmx8g" to ES_JAVA_OPTS
```

I delete ES_HEAP_SIZE and add ES_JAVA_OPTS: "-Xms8g and -Xmx8g" (without quotes)

I run the command again and get the following:
```
Installing service      :  "elasticsearch-5.0.0-rc1"
Using JAVA_HOME (64-bit):  "C:\Program Files\Java\jdk1.8.0_101"
thread stack size not set; configure via C:\elasticsearch-5.0.0-rc1\config\jvm.options or ES_JAVA_OPTS
```

I delete ES_JAVA_OPTS and edit jvm.options:
```
-Xms8g
-Xmx8g
```

Run again and get the following:
```
Installing service      :  "elasticsearch-5.0.0-rc1"
Using JAVA_HOME (64-bit):  "C:\Program Files\Java\jdk1.8.0_101"
thread stack size not set; configure via C:\elasticsearch-5.0.0-rc1\config\jvm.options or ES_JAVA_OPTS
```

I leave jvm.options alone and create ES_JAVA_OPTS again. Now it see duplicate settings:
```
Installing service      :  "elasticsearch-5.0.0-rc1"
Using JAVA_HOME (64-bit):  "C:\Program Files\Java\jdk1.8.0_101"
duplicate min heap size settings found
```

**Comment by jasontedor** [comment]
You missed the message: 

`thread stack size not set; configure via C:\elasticsearch-5.0.0-rc1\config\jvm.options or ES_JAVA_OPTS`

This is covered in the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/windows.html#windows-service):

```
The service installer requires that the thread stack size setting be configured in jvm.options *before* you install the service. On 32-bit Windows, you should add `-Xss320k` to the jvm.options file, and on 64-bit Windows you should add `-Xss1m` to the jvm.options file.
```

Ideally you'll just set the heap and the stack size in the jvm.options file, leave `ES_JAVA_OPTS` out of it (it's there, it's an option, it's useful for development but the preferred approach is to just set your configs in the jvm.options file).

**Comment by jasontedor** [comment]
Many thanks for downloading and trying out 5.0.0-rc1; I've added you to the [Pioneer Program](http://www.elastic.co/blog/elastic-pioneer-program). Please do let us know if you encounter any issues. :smile:

**Comment by mike-mosher** [comment]
I appreciate the help.  I'm not a Java person, so I assumed it was barking about the heap size.  I didn't realize there was a difference between this and the thread stack size.  

Thanks for your help.

**Comment by jasontedor** [comment]
> Thanks for your help.

You are very welcome.

**Comment by joniba** [comment]
@jasontedor the referenced [docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/windows.html#windows-service) do not contain the quoted paragraph about thread stack size. I think it's somewhat discouraging that non-java people running on windows need to sift through github issues just to try to start elastic for the very first time.

I'm sure it's all very clear to those that are fluent with the settings. But I don't even see this jvm.options file. I've read through the documentation about installing on windows and certainly it does not work as per the documentation (on windows 10 at least).

**Comment by jasontedor** [comment]
@joniba That's because we ship with thread stack size settings in the default jvm.options file now, you'll see this in the latest versions of the packages. Because of this, the note in question has been moved to a different [page](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/setup.html) of the docs as it now pertains to *all* installations.

**Comment by jasontedor** [comment]
The point is, we recognize the pain that was here and are trying to make it easier.

Relates #21920

**Comment by joniba** [comment]
Sorry if I'm being a pain but the page you linked also does not mention setting -Xss1m in the jvm.options. I don't understand why there isn't a simple note somewhere, at least for windows users (or which ones need to set this? I didn't get it) to set this variable.

**Comment by jasontedor** [comment]
> Sorry if I'm being a pain but the page you linked also does not mention setting -Xss1m in the jvm.options.

As I mentioned, you do not need to set it anymore with the default jvm.options file that ships with Elasticsearch starting in version 5.1.1 (the latest is 5.1.2). The note on the page that I linked to says:

>Elasticsearch ships with default configuration for running Elasticsearch on 64-bit server JVMs. If you are using a 32-bit client JVM, you must remove `-server` from jvm.options and if you are using any 32-bit JVM you should reconfigure the thread stack size from `-Xss1m` to `-Xss320k`.

This is because the default jvm.options that we ship with works on all platforms *except* those that have a 32-bit client JVM (exceedingly rare these days). The stack size in the jvm.options also works on all platforms although it is best to change it on 32-bit JVMs.

**Comment by joniba** [comment]
Hmm I'm on 5.0.0 and getting the thread stack size error. I only downloaded it yesterday. Weird. Downloading 5.1.2 now.

**Comment by jasontedor** [comment]
> Hmm I'm on 5.0.0 and getting the thread stack size error. I only downloaded it yesterday. Weird. 

That's because the change to ship with a default was only introduced in 5.1.1.

> Downloading 5.1.2 now.

You will not have this specific problem with that package.

**Comment by joniba** [comment]
Yes 5.1.2 worked more or less out of the box, thanks.

**Comment by jasontedor** [comment]
> Yes 5.1.2 worked more or less out of the box, thanks.

Awesome, thank you for reporting back, it's appreciated.

**Comment by aateeque** [comment]
5.1.2 worked pretty much out of the box; but trying to install 5.2.1 on the same box I am seeing the same error:
```
duplicate min heap size settings found
```

Where all does the install script look for the min heap size settings? 

In my jvm.options I have:
   - `-Xms2g` & `-Xmx4g` commented out 
   - `-server` set
   - `Xss1m` set
  
Have env var: `ES_HEAP_SIZE=-Xms4g -Xmx4g`

Any pointers on what's happening here? Thanks!

**Comment by jasontedor** [comment]
I think that you have `-Xms` or `-XX:MinHeapSize` set in (either in `jvm.options` or `ES_JAVA_OPTS`) and you have also set `JVM_MS`. Just unset `JVM_MS`.

Also, `ES_HEAP_SIZE` is not supported in 5.x, you need to remove that.

**Comment by aateeque** [comment]
I am running ES 1.x on the same box; will removing `ES_HEAP_SIZE` cause problems for v1 instance?

**Comment by jasontedor** [comment]
If you're using `ES_HEAP_SIZE` for your v1 instance then yes, removing it will cause problems because it will not be set anymore when you start your v1 instance.

**Comment by aateeque** [comment]
I have another server, which has both 1.x & 5.2.1 running quite happily with `ES_HEAP_SIZE=4g`. I have copied over the same java.options file, but can't install the service on second server.

After copying the jvm.options over I am now getting this on server 2:
```
Error: encountered environment variables that are no longer supported
Use jvm.options or ES_JAVA_OPTS to configure the JVM
ES_HEAP_SIZE=4g: set -Xms4g and -Xmx4g in jvm.options or add "-Xms4g -Xmx4g" to ES_JAVA_OPTS
```

**Comment by jasontedor** [comment]
> I have another server, which has both 1.x & 5.2.1 running quite happily with `ES_HEAP_SIZE=4g`.

If this is the case, then you started 5.2.1 without `ES_HEAP_SIZE` set. That environment variable is unsupported for 5.x, and we do not silently ignore it so that you do not mistakenly think it's doing something useful.

The error message that you're seeing now is expected when `ES_HEAP_SIZE` is set and a 5.x instance is started.

> Why is this so hard :(

I'm sorry that you're struggling with this. The changes across two major releases were done to make the system easier to work worth but of course there's always transition pain. If you continue to struggle with this, please ask for help on the [forum](https://discuss.elastic.co); we will be happy to help.

**Comment by aateeque** [comment]
I've removed that env var, and now trying `elasticsearch-service.bat install`, I get:
```
Installing service      :  "elasticsearch-service-x64"
Using JAVA_HOME (64-bit):  "D:\Java\jdk1.8.0_40x64\jre"
Failed installing 'elasticsearch-service-x64' service
```

**Comment by jasontedor** [comment]
You have to look at the service logs. May I suggest again that you create a topic on the [forum](https://discuss.elastic.co)? Feel free to link to it from here.

**Comment by aateeque** [comment]
Thanks, I have created it [here](https://discuss.elastic.co/t/running-1-x-5-x-sxs/76289)
