### ISSUE TITLE
Add documentation for task status for index/bulk/update

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#20891]
You can use the tasks API to monitor the status of index, bulk, and update actions. The status should be marked "experimental" because we aren't at all sure that the format is right or finished, but we should document it.

**Comment by bleskes** [comment]
@nik9000 can you elaborate more on what you had in mind? Those requests are hopefully short lived. What can of information do think we should expose?

**Comment by henningandersen** [comment]
@nik9000 is this still relevant? Given the short life of such tasks, I guess the relevance is mainly debugging when something fails and therefore leaving it undocumented may be better than tying us into the format/response (though experimental)? Another minor issue with short lived tasks is that the tasks api may show multiple tasks running "at the same time" while they never did in reality (could be one client doing one task at a time, but hitting different nodes)?
