### ISSUE TITLE
New Feature Req - Throttling write speed in ES-Hadoop Connector

### ISSUE THREAD

**Issue by kamaldsingh** [elastic/elasticsearch#20897]
Hello,

I was trying out ES - hadoop connector and I see that in case of too many parallel writes, like from a spark job, writes keep on getting dropped. 
org.elasticsearch.hadoop.EsHadoopException: Could not write all entries (maybe ES was overloaded?). Bailing out...

The workaround is to decrease number of partitions and tune the batch size and timeouts accordingly.

As mentioned in https://discuss.elastic.co/t/pushback-to-hadoop-from-es-on-bulk-load/1535/5 there's no bi-directional communication between Hadoop and the connector - the connector cannot say, there's too much data, slow down.

Does anyone think it might be a good idea to use sth. like Blocking Queues here and add acks while writing (kafka) so as to let the consumer (thread on ES) read at slower pace.

Else we would have to tune the batch size, write speed, http timeouts ourself.

Any other suggestions are more than welcome.

I'm open to building/contributing to this its a good idea.

https://discuss.elastic.co/t/throttling-write-speed-in-es-hadoop-connector/62528/1

**Comment by jasontedor** [comment]
For now, this is best discussed on the [Discourse post](https://discuss.elastic.co/t/throttling-write-speed-in-es-hadoop-connector/62528/1) that you opened. In the future, please do not cross post (it fractures conversations).
