### ISSUE TITLE
GC runs indefinitely on Elasticsearch node

### ISSUE THREAD

**Issue by amitanjani** [elastic/elasticsearch#20908]
I am using elasticsearch version1.7.3. 
I am running 3 node es cluster on 16gb ram and 4 core machine. 8gb ram is allocated to es process. 
I am using mongoriver to sync data from mongo db. Some bulk update happened to mongo db. I got exception in elasticsearch 
[ERROR][org.elasticsearch.river.mongodb.MongoDBRiverBulkProcessor] Bulk processor failed. failure in bulk execution
and org.elasticsearch.transport.NodeDisconnectedException: 
and after node rejoin to cluster GC started. GC was consuming 90% of CPU. It was running indefinitely. sawtooth pattern was observed in grabage collection memory graph.

What should we do to avoid this scenerio?
I am unable to debug root cause of this issue.
What should we do to fix this issue? I restarted node in which GC was running after that GC started on other node.

**Comment by jasontedor** [comment]
Elastic reserves GitHub for verified bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) for general questions.
