### ISSUE TITLE
Add arbitrary metadata to indices to allow better filtering / selection of indices

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#20903]
**Describe the feature**:

For purposes of managing data, an index can have attributes which are related to, but not represented in the documents contained in the index, for example:
- authorisation (e.g. this data should be visible only to users in these roles)
- application (e.g. in a logging usecase which (one or more) application's data logging)
- retention policy

This can now only be represented in the index name, which can become very unwieldy, and sometimes is not even possible (e.g. if an index should be visible to multiple roles).

It would be great if an index could contain arbitrary metadata which can in turn be used e.g. for selecting indexes for snapshot, allocation or even query.

**Comment by ynux** [comment]
+1
This would greatly help us in managing complex Shield / Security roles

**Comment by clintongormley** [comment]
> application (e.g. in a logging usecase which (one or more) application's data logging)

@robin13 what do you mean here? ^^

Indices already have metadata attributes.  It sounds like the part that is missing is the ability to use those in x-pack, etc, no?

**Comment by robin13** [comment]
@clintongormley 

> Indices already have metadata attributes. 

Can I define arbitrary metadata related to an index?

Some examples to illustrate

Creating an index:

```
PUT /foo
{
  "metadata": {
    "retention": "long",
    "client": 98765
  }
}

PUT /bar
{
  "metadata":{
    "retention":"short",
    "client":12345
  }
}
```

Would allow queries
```
GET /_search?metadata=client:12345
```
i.e. the metadata argument could limit the indices to be searched

Or even more powerful for curator
```
 - filtertype: metadata
   field: retention
   value: short
```

i.e. it would allow curator to filter the indices against which the actions are to be applied by attributes which are not simply size or age.

**Comment by ynux** [comment]
That would help us a lot. Presently, the retention policy is part of the index name. The same applies to Shield roles: In our setup, events are indexed into separate indexes, and roles are allowed to see indexes with certain name patterns. Also, the name patterns are used in Kibana. This leads to long names ("group1-group2-group3-retentionpattern-kibanapattern-logstash-YYYY.MM.DD", and to intense worries of changing any of this.

**Comment by clintongormley** [comment]
> Indices already have metadata attributes. 

Sorry, I was thinking nodes, not indices.

**Comment by hub-cap** [comment]
This feature request is an interesting idea but since its opening we have not seen enough feedback that it is a feature we should pursue. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).
