### ISSUE TITLE
What are these indexes which in kibana ui

### ISSUE THREAD

**Issue by wanglifengwf** [elastic/elasticsearch#20901]
What are these indexes which in kibana ui?

![image](https://cloud.githubusercontent.com/assets/9550346/19336037/a873789e-913a-11e6-9095-31343eb09fb4.png)

**Comment by bleskes** [comment]
It looks like you have your cluster accessible via the internet and someone is probing and by doing it creates indices. You should lock down your cluster.

I'm closing this now as we use github to track issues. Questions and discussions are held on http://discuss.elastic.co . If you want to discuss this further I'd recommend doing it there.
