### ISSUE TITLE
Template validation is wrongfully identical to index validation

### ISSUE THREAD

**Issue by acarstoiu** [elastic/elasticsearch#20919]
**Elasticsearch version**: 2.4.1

After upgrading to the said version from 2.3 we were greeted with a nasty surprise. Templates are now validated upfront, as if they were _complete_ objects, which they are certainly **not**. This design error implemented in #8802 is also cooked for 5.0.

When a new index is created, all templates are scanned for a match between their pattern and the index name. All applicable templates are then merged in the order indicated by the `order` property and it's the resulting settings and mappings that are applied to the new index.

Then why validate templates for completeness?! It's plain silly, and _not even documented_. 

**Example:**
All analyzers are defined in a common template that has pattern `*` and order `0`. These analyzers can used throughout all indices and it's up to the higher order templates to make actual use of them.
This arrangement is now impossible, as you're using the same validator for templates as for an index mapping (which rightfully checks that all referred anlyzers are present).

The mapping validation code should be more insightful and refrain from such checks when working on templates.

**Comment by jasontedor** [comment]
Duplicates #20479, duplicates #20849
