### ISSUE TITLE
Replace URL unfriendly character in index date math 

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#20918]
We have the notion of [date math in index names](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/date-math-index-names.html) we expose this date math as part of the URL. This means, we have an index name like `<logstash-{now/d-2d}>`. There are chars the require encoding like `< > { }` and there is the slash that requires encoding as well (but only this single one slash in the middle, not the others and this is where the fun for clients begin). However you cannot just pick the whole URL and encode, but only the index name if you want to do it right.

My idea to solve this (and thus only need to url encode the path once without any special handling) is to also support another char in addition to the slash for date math, that has no special meaning for paths (or not use the URL path to address this, but this sounds more tricky).

Maybe there are completely different ideas that I am not aware of, that would make handling date based indices in the path easier. Everything is welcome, that prevents this kind of encoding complexity IMO. I'd like to discuss and brainstorm some ideas.

**Comment by rjernst** [comment]
> There are chars the require encoding like `< > { }`

In [RFC2396](https://tools.ietf.org/html/rfc2396), these characters are considered safe to use:

```"-" | "_" | "." | "!" | "~" | "*" | "'" | "(" | ")"```

And these are considered "unwise":

```
"{" | "}" | "|" | "\" | "^" | "[" | "]" | "`"
```

But I dont' think the unwise characters are really dangerous, at least in modern systems (in fact, we just started using `|` in the shard preference param). You could use square brackets for the outter container, and maybe tilde for the datemath separator?

**Comment by rjernst** [comment]
You could also use parens instead of square brackets, but that depends if it considered "ok" to use these in index names themselves (which I don't think it should be, let's keep them to simple alphanum!).

**Comment by clintongormley** [comment]
@rjernst then there is curl, which (and i had no idea) has argument globbing enabled by default, which interprets `{}[]` as special characters

**Comment by clintongormley** [comment]
I'm more and more tempted to add an index selector widget to request bodies, eg:

    GET _search
    {
       "indices": {
            "max_age": "10d",
            "max_docs": 10000,
            "name":  "logs-*",
            etc
      }
    }

**Comment by rjernst** [comment]
Curl is really for playing around. We thought about the same thing with pipe for shard preference (which also must be escaped from the command line). But I don't think we should complicate that more for a testing only edge case.

**Comment by spinscale** [comment]
we discussed this today and came to the conclusion that the clients need to be able to handle this and do all the URL encoding by himself. This is way easier than introducing a second character instead of the slash to Elasticsearch.

Elasticsearch 5.x will have a `{{#url}}` mustache functions that will help with URL encoding.
