### ISSUE TITLE
Parsing of "ZZZ" component in date formats fails

### ISSUE THREAD

**Issue by yrodiere** [elastic/elasticsearch#20911]
**Elasticsearch version**: 2.4.1 
Used to work in 2.3.1.

**Plugins installed**: none

**JVM version**: java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**OS version**: Fedora 24

**Description of the problem including expected versus actual behavior**:

Parsing of "ZZZ" component in date formats seems to fail for some formats. I don't know what exactly triggers the issue, but having a literal just before the "ZZZ" component seems to be enough.

I managed to reproduce the bug in Joda-time 2.9.4 directly. There seems to be a [fix in master](https://github.com/yrodiere/joda-time/commit/eaaff1d0687fc86a745ca8f3ea0b069b3cf54233), but it has not been released yet.

The next release of Elasticsearch on the 2.4 branch should upgrade the Joda dependency to fix this bug.

**Steps to reproduce**:
1. Launch an Elasticsearch node on localhost:9200
2. Execute the following bash script:

```
curl -XPUT 'localhost:9200/testindex/?pretty'
curl -XPUT 'localhost:9200/testindex/testtype/_mapping?pretty' -d'{"properties":{"zonedDate":{"type":"date","store":true,"format":"yyyy-MM-dd'['ZZZ']'"}}}'
curl -XPUT 'localhost:9200/testindex/testtype/1?pretty' -d'{"zonedDate":"2016-10-13[CET]"}'
```

**Provide logs (if relevant)**:
Elasticsearch response for the last command:

```
{
  "error" : {
    "root_cause" : [ {
      "type" : "mapper_parsing_exception",
      "reason" : "failed to parse [zonedDate]"
    } ],
    "type" : "mapper_parsing_exception",
    "reason" : "failed to parse [zonedDate]",
    "caused_by" : {
      "type" : "illegal_argument_exception",
      "reason" : "Invalid format: \"2016-10-13[CET]\" is malformed at \"CET]\""
    }
  },
  "status" : 400
}
```

**Comment by yrodiere** [comment]
Hello,

It seems Joda Time 2.9.5 is out. I just did a quick test, and overriding the version of the library to 2.9.5 seems to fix the issue on Elasticsearch 2.4.1: running the set of commands I gave above will not fail anymore.
It would probably also fix 5.0.0 (which is also affected by this bug, by the way).

Any change to see this in the next hotfix releases for 2.x and 5.x?

**Comment by gsmet** [comment]
@tlrx do you know if there will be another maintenance release for 2.4.x? It would be nice to get it fixed for 2.4.x too.

Thanks!

**Comment by tlrx** [comment]
@gsmet I'm backporting it to 2.4.x right now so if there's another maintenance release it will be part of it.

**Comment by gsmet** [comment]
@tlrx thanks! FYI, we can't support ZonedDateTime in our Hibernate Search-Elasticsearch integration at the moment because of this bug and we do not support 5 yet - it's in project. It would be nice to get a 2.4.x release without this issue!
