### ISSUE TITLE
v5.0.0rc1 - reduce_params is not being recognised as a valid key in scripted_metric aggregation

### ISSUE THREAD

**Issue by nishant-tomer** [elastic/elasticsearch#20917]
**Elasticsearch version**: v5.0.0rc1
**Plugins installed**: [mapper-murmur3]
**OpenJDK version** : 1.8.0_91
**JVM_version** : OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
**OS version**: Ubuntu 16.04 LTS / Ubuntu 14.04 LTS

**Description of the problem including expected versus actual behavior**:
`reduce_params` is not being recognised as a valid key in scripted_metric aggregation but [docs for v5.0.0rc1 mention](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-aggregations-metrics-scripted-metric-aggregation.html#_other_parameters) that it should be recognised.

**Steps to reproduce**:
i have some docs in an index with following mapping 
```
   "sales": {  "type": "double" }
``` 
i am using following query to test `scripted_metric` aggregation which involves only `sales` field
```
{
   "size": 0,
   "aggregations": {
      "sum_test": {
         "scripted_metric": {
            "params": {
               "_agg": {}
            },
            "reduce_params":{},
            "init_script": "params._agg['transactions'] = []",
            "map_script": "if (!doc['sales'].empty) { params._agg.transactions.add(doc['sales'].value) } else { params._agg.transactions.add(0.0) }",
            "combine_script": "double sales = 0; for (t in params._agg.transactions) { sales += t } return sales",
            "reduce_script": "double sales = 0;  for (t in params._aggs) { sales += t } return sales"
         }
      }
   }
}
```
This query is throwing a `400` error with type `parsing_exception`.

**Provide logs (if relevant)**:
ES response for test query above
```
{
   "error": {
      "root_cause": [
         {
            "type": "parsing_exception",
            "reason": "Unknown key for a START_OBJECT in [sum_test]: [reduce_params].",
            "line": 9,
            "col": 29
         }
      ],
      "type": "parsing_exception",
      "reason": "Unknown key for a START_OBJECT in [sum_test]: [reduce_params].",
      "line": 9,
      "col": 29
   },
   "status": 400
}
```

ES Response after removing `reduce_params` key from `scripted_metric` object in the test query above
```
{
   "took": 34,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 6145,
      "max_score": 0,
      "hits": []
   },
   "aggregations": {
      "sum_test": {
         "value": 1802900.2899999975
      }
   }
}
```

**Comment by clintongormley** [comment]
I think this is just a matter of documentation.  The `reduce_params` param was removed in 2c3165d080c066cc11c2d1478df6aefff2700e90 - presumably you just pass the params inside the `reduce_script` construct:

    "reduce_script": {
      "inline": ".....",
      "params": {...}
    }

@colings86 can you confirm?

**Comment by colings86** [comment]
Yep, this is a documentation issue, the params for the `reduce_script` should indeed be passed in the way @clintongormley describes
