### ISSUE TITLE
Deprecate EOL'ed Ubuntu 15.04 from Vagrantfile

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#20920]
Ubuntu 15.04 (as well as 15.10) has reached end of life as per https://wiki.ubuntu.com/Releases

Therefore I think there's no point including it in packaging tests and we should remove the corresponding entries from the Vagrantfile: https://github.com/elastic/elasticsearch/blob/master/Vagrantfile#L33-L38

**Comment by nik9000** [comment]
Fine by me!

**Comment by clintongormley** [comment]
Closed by #20921

**Comment by dliappis** [comment]
Also backported to:

- 5.0: https://github.com/elastic/elasticsearch/commit/666023751ae7d425b475989df1f2c24c6f24441f
- 5.x: https://github.com/elastic/elasticsearch/commit/1050e6f87cb258dd7782ea6032cd00a6c21c9ee9
