### ISSUE TITLE
Elasticsearch 5.0 rc1 Monitoring reporting incorrect node names. All nodes with different ip named as master node.

### ISSUE THREAD

**Issue by ajaybhatnagar** [elastic/elasticsearch#20923]
Setup : 

Elasticsearch build 5.0 rc1 on Ubuntu 16.04 with separate monitoring cluster, JDK 1.8.0-102. Screen shot attached.

![es5rc1_monitor](https://cloud.githubusercontent.com/assets/8180763/19362234/ecaceaae-9153-11e6-98c9-c7781cdf5ca0.jpg)

When deploying separate cluster for monitoring, monitoring cluster nodes reports incorrect host name for different nodes. Ip addresses are different but host names are all same as master node of the cluster. 
Name	Status	CPU Usage	JVM Memory	Load Average	Disk Free Space	Shards
 es-tst-m01		0%	7%	0	9.6 GB	0
10.236.133.172:9300		0% max	11% max	0.07 max	9.6 GB max	
		0% min	4% min	0.01 min	9.6 GB min	
 es-tst-m01		0%	7%	0	19.3 GB	0
10.236.133.188:9300		0.33% max	11% max	0 max	19.3 GB max	
		0.33% min	4% min	0 min	19.3 GB min	
 es-tst-m01		0%	9%	0	97.2 GB	0
10.236.133.174:9300		0% max	11% max	0.27 max	97.2 GB max	
		0% min	6% min	0 min	97.2 GB min	
 es-tst-m01		0%	6%	0	97.2 GB	0
10.236.133.178:9300		0% max	13% max	0.05 max	97.2 GB max	
		0% min	6% min	0 min	97.2 GB min	
 es-tst-m01		0%	7%	0	9.6 GB	0
10.236.133.171:9300		0% max	11% max	0.06 max	9.6 GB max	
		0% min	4% min	0.01 min	9.6 GB min

**Comment by bohyun-e** [comment]
Hi @ajaybhatnagar - could you ask this in https://discuss.elastic.co/c/x-pack as Monitoring is a part of X-Pack?

Closing the issue.
