### ISSUE TITLE
[Feature Request] add wait_for_completion to index open command

### ISSUE THREAD

**Issue by shaharmor** [elastic/elasticsearch#20937]
**Describe the feature**:
When opening an index using the `_open` command, its sometimes needed to wait for the index to be fully opened and usable before running additional commands on the index.

For example, when trying to compress an index using the `codec: "best_compressions"` index config, you need to first close the index, change the setting, open the index, and then `forcemerge` it for the compression to take effect.

If you run both the `open` command and the `forcemerge` command one after the other in the same script, the `forcemerge` will exit instantly (probably because the index is not yet "loaded" or something).

It would be great to add the `wait_for_completion` query parameter like in other commands so that it will be possible to synchronously wait for the opening to complete.

**Comment by clintongormley** [comment]
@abeyad does `_open` support the `wait_for_active_shards` param?

**Comment by ywelsch** [comment]
@clintongormley no, it currently does not but could be added. Should we mark this as adoptme?

**Comment by shaharmor** [comment]
Hey, is there any estimate of when/if this will get implemented? And if so, will it reach ES v2.x as well?

**Comment by jasontedor** [comment]
> Hey, is there any estimate of when/if this will get implemented?

No.

> And if so, will it reach ES v2.x as well?

It will not reach 2.x as 2.x will only see bug fixes now.

**Comment by shaharmor** [comment]
Is still the case in 6.0?

**Comment by jasontedor** [comment]
I doubt that it will make an appearance in 6.0.0, maybe some time in the 6.x lifetime though. It's not a high-priority feature.
