### ISSUE TITLE
[feature request]high level search profile API

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#20933]
**Describe the feature**:
1. define critical steps for search: let's say query re-write, dfs, search invert index, score, rank, fetch doc
2. record the slowest one of each critical steps info, let's say: [index1][shard1], dfs, timecost: 2ms
3. each search reutrn each slowest of each critical steps

**Comment by polyfractal** [comment]
Have you seen the existing [Profile API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-profile.html)?  It returns per-shard breakdown of many of the things you listed: scoring, rewriting, etc.

It doesn't instrument everything in ES yet (DFS for example, or the fetch phase), but the goal is to add more to the feature over time.  For example, in 5.0 it gained the ability to [profile aggregations](https://github.com/elastic/elasticsearch/pull/18414)
