### ISSUE TITLE
Force merge does not compress index if already at 1 segment

### ISSUE THREAD

**Issue by shaharmor** [elastic/elasticsearch#20936]
**Elasticsearch version**: v2.4.1

**Plugins installed**: [license, marvel-agent]

**JVM version**: javac 1.8.0_101

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:
Trying to further compress an index, I have changed the `codec` index setting to `best_compression` per the guide (By closing the index, changing the setting, and reopening the index), and then called `forcemerge` on the index with `max_num_segments=1`.

The problem is that if the Index was already `forcemerge`ed before using `max_num_segments=1`, the `forcemerge` request will exit immediately without compressing the index.

**Steps to reproduce**:
1. create index with some data
2. run `forcemerge` using `max_num_segments=1`
3. close the index
4. change the index setting `codec` to `best_compression`
5. open the index
6. run `forcemerge` using `max_num_segments=1`

Expected: Index should be further compressed
Actual: Nothing happens

**Comment by s1monw** [comment]
this is not supported at this point

**Comment by shaharmor** [comment]
Any estimate on if/when it will be?

**Comment by s1monw** [comment]
I don't think we have it on the roadmap I will mark it as adopt me... as a workaround you could try to use the [upgrade API ](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-upgrade.html) but it will only work if the segment is not from the current version

**Comment by shaharmor** [comment]
@s1monw got it, thnx.
The index is from the same version 😄 

Will reindexing work? Also, maybe this should be documented somewhere, about the correct flow to compress

**Comment by s1monw** [comment]
well reindex might work if you have set the codec to `best_compression`. Yet, updateing a single document per shard should also do the job and after that you can run the force_merge

**Comment by aditya-agrawal** [comment]
Hi, I would like to take this up. Any pointers would be appreciated.

**Comment by aditya-agrawal** [comment]
@s1monw is there anyway to determine change in codec?

**Comment by aditya-agrawal** [comment]
@s1monw should we add one option to force a force_merge in cases when no deleted documents are there in the segment?

**Comment by aditya-agrawal** [comment]
@s1monw Can we add an option to force a force_merge as suggested in https://github.com/elastic/elasticsearch/issues/5243?

**Comment by dforste** [comment]
I would like to see this implemented as it seems to be a long standing issue that might be an easy fix. I would think there would be a couple ways of going about in fixing it: 
1. Adding a query parameter to force a merge. 
2. Adjust merging behavior to take into account the change in codec. 

It may be the case the implementing number 2 would fix the issue without the need for a force parameter. It would additionally allow elastic to do the work over time as it has free cycles which seems preferable.

**Comment by lukecolpo** [comment]
Hi - i'm new to contributing to open source software and was wondering if i could give this issue a try.

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
