### ISSUE TITLE
HTTP module does not regard Connection: Close in v5.0.0

### ISSUE THREAD

**Issue by algestam** [elastic/elasticsearch#20938]
**Elasticsearch version**: 5.0.0-rc1

**Plugins installed**: []

**JVM version**: Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

**OS version**: Ubuntu 16.04 x64

**Description of the problem including expected versus actual behavior**:

When setting up a simple monitoring solution for a test instance of elasticsearch 5.0.0 with Nagios, I observed that the Nagios check program `check_http` fails with a socket timeout error:

    user@host:/usr/lib/nagios/plugins# ./check_http -H elasticsearch -p 9200
    CRITICAL - Socket timeout after 10 seconds

This was a bit strange since it works ok when running on older versions of elasticsearch (tested with 2.3.3).

Investigated a bit further to check what the `check_http` actually does and tried to replicate the behaviour with netcat revealed a difference between the older elasticsearch installation and the 5.0.0 installation where elasticsearch previously closes a HTTP connection if the request header contains `Connection: Close` where 5.0.0 does not.

The workaround for getting the Nagios check program to work is to use the `-N` flag that doesn't wait for the document body but simply stops reading after the headers.

**Steps to reproduce**:
 1. Make an API request to elasticsearch with netcat:

        user@host:/# ncat elasticsearchhost 9200
        GET / HTTP/1.1
        User-Agent: check_http/v2.1.2 (monitoring-plugins 2.1.2)
        Connection: Close
        Host: elasticsearchhost
 2. Press enter to view the response

        HTTP/1.1 200 OK
        content-type: application/json; charset=UTF-8
        content-length: 351
        
        {
          "name" : "j0-yZSR",
          "cluster_name" : "logs",
          "cluster_uuid" : "kozqvcWRSxuyRUABAKcINQ",
          "version" : {
            "number" : "5.0.0-rc1",
            "build_hash" : "13e62e1",
            "build_date" : "2016-10-07T16:52:58.798Z",
            "build_snapshot" : false,
            "lucene_version" : "6.2.0"
          },
          "tagline" : "You Know, for Search"
        }

 3. Press enter twice after receiving the response. The server should close the connection but it doesn't. When trying the same procedure on 2.3.3 it closes the connection correctly.

Also, if changing the header when testing on 2.3.3 to not contain the `Connection: Close` directive, 2.3.3 correctly changes the behavior to keep-alive and will not close the connection.

**Comment by nik9000** [comment]
I wonder if this is a change that came with netty 4....

**Comment by jasontedor** [comment]
Thanks for the report. This morning I verified its validity and have a fix. I will open a pull request on Monday.

I've marked you as eligible for the [Pioneer Program](https://www.elastic.co/blog/elastic-pioneer-program).

**Comment by algestam** [comment]
Great, thanks so much!

**Comment by jasontedor** [comment]
I opened #20956.
