### ISSUE TITLE
[feature request]request in query cache dump&replay

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#20932]
**Describe the feature**:
1. when I add node to certain cluster and after data rebalance, there is nothing cached in new nodes, so better can replay the request so it can warm the new nodes
2. when I upgrade the cluster, better can dump the request in query cache and after upgrade, replay those request to warm up the cluster

**Comment by clintongormley** [comment]
Unfortunately this wouldn't be possible.  The results in the request cache are tied to index readers and are applicable only to the current node.
