### ISSUE TITLE
Should I reimport data after updating synonyms file

### ISSUE THREAD

**Issue by Vincent717** [elastic/elasticsearch#20939]
Hi All,

I was wondering, If I update the synonyms files, do I need to reload the data into ES?
Because I have tried to only restart ES after updating synonyms files, but it does not work.
If it is so, do you have any more efficient solution, since reloading data is quite frustrated..

**Comment by dadoonet** [comment]
Hi @Vincent717 

Please ask your questions on discuss.elastic.co instead.
This place is only for confirmed bugs or feature requests.

Thanks!

**Comment by dadoonet** [comment]
Hi @Vincent717 

Please ask your questions on discuss.elastic.co instead.
This place is only for confirmed bugs or feature requests.

Thanks!
