### ISSUE TITLE
lang is still required in Ingest Script Processor

### ISSUE THREAD

**Issue by eskibars** [elastic/elasticsearch#20943]
**Elasticsearch version**: 5.0.0-rc1

**Description of the problem including expected versus actual behavior**:
Currently we [default scripts to lang=painless and treat the parameter as optional in many places](https://github.com/elastic/elasticsearch/issues/20122#issuecomment-244337340).  We [say it's not required](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/script-processor.html) in the Ingest Script Processor, but we still throw `"reason": "[lang] required property is missing"` if you don't include the parameter.  I think this one just got missed when we did the defaults switch.

**Steps to reproduce**:

    POST _ingest/pipeline/_simulate
    {
      "pipeline" :
      {
        "description": "_description",
        "processors": [
          {
            "script": {
              "inline":"ctx.hi = 'hello';"
            }
          }
        ]
      },
      "docs": [
        {
          "_index": "shanetest",
          "_type": "shanetest",
          "_id": "1",
          "_source": {
            "field_a": 3
          }
        }
      ]
    }

**Comment by clintongormley** [comment]
@talevy could you take a look please?

**Comment by talevy** [comment]
yeah, will get on it today

**Comment by talevy** [comment]
@eskibars https://github.com/elastic/elasticsearch/pull/20981 should fix this. let me know what you think!

thanks for the report
