### ISSUE TITLE
Some searches may slow down as a node warms up

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#20957]
**Elasticsearch version**: 5.0.0-rc1

**Plugins installed**: [none]

**JVM version**: 1.8.0_102

**OS version**: Mac OS X (reproducible on Linux as well)

**Description of the problem including expected versus actual behavior**:

On indices with a large number of small records a match_all search can become significantly slower after the first few executions. 

**Steps to reproduce**:
1. download elasticsearch 5.0.0-rc1 and start a single node with default settings
2. using [`esrally`](https://github.com/elastic/rally) execute `nyc_taxis` banchmark to create this index
3. restart the node
4. execute the following command several times taking note of `took` time reported for each execution

```
curl "localhost:9200/nyc_taxis/_search"
```

On my machine, I typically see the following execution times: the first query typically takes around 90ms, the second query can take anywhere between 30ms and 80ms, then starting with 3rd query execution time would oscillate between 270ms and 380ms. In other words, the 3rd search can be more than 10x slower than the second.

**Analysis**:

By manually instrumenting elasticsearch and lucene libraries I was able to narrow the source of slow down to [this loop](https://github.com/apache/lucene-solr/blob/branch_6_2/lucene/core/src/java/org/apache/lucene/search/MatchAllDocsQuery.java#L53-L58) in the `score` method of `BulkScorer` in `MatchAllDocsQuery`. In my tests after 2 search executions, this loop would become significantly slower while execution time for all other areas would remain the same. I have verified that scorers, collectors didn't change between executions and all executions looped over the same set of segments with the same number of documents. The only difference between the second and the third execution that I was able to find is that the loop significantly slows down right after JVM inlines the score method. By experimenting with different requests I was able to delay method inlining, and I was consistently observing slow down immediately after seeing the following message in JVM's inlining output

```
  @ 15   org.apache.lucene.search.FakeScorer::<init> (16 bytes)   inline (hot)
    @ 2   org.apache.lucene.search.Scorer::<init> (10 bytes)   inline (hot)
      @ 1   java.lang.Object::<init> (1 bytes)   inline (hot)
  @ 32   org.apache.lucene.search.TopScoreDocCollector$ScorerLeafCollector::setScorer (6 bytes)   inline (hot)
   \-> TypeProfile (5/5 counts) = org/apache/lucene/search/TopScoreDocCollector$SimpleTopScoreDocCollector$1
  @ 72   org.apache.lucene.search.TopScoreDocCollector$SimpleTopScoreDocCollector$1::collect (127 bytes)   inline (hot)
    @ 4   org.apache.lucene.search.FakeScorer::score (5 bytes)   inline (hot)
     \-> TypeProfile (13395/13395 counts) = org/apache/lucene/search/FakeScorer
    @ 117   org.apache.lucene.util.PriorityQueue::updateTop (12 bytes)   executed < MinInliningThreshold times
  @ 4   org.apache.lucene.search.FakeScorer::score (5 bytes)   inline (hot)
   \-> TypeProfile (19539/19539 counts) = org/apache/lucene/search/FakeScorer
```

So, there is definitely a strong correlation between slow down and this method being inlined. 

**Other thoughts**:
Since it seems to be a JVM issue I am not sure if we can/should do anything about it. The test case here is somewhat artificial as well. On the other side, artificial or not it's an order of magnitude performance degradation and I wonder if it occurs in other places as well, but it is not as noticeable because a cold node is generally slower! So, I would like to discuss this issue before spending more time on it.

**Comment by dadoonet** [comment]
Looks like the JVM optimizer does not optimize as we would expect?

Wondering what would happen if you try to turn it off with XX:MaxInlineSize=0?

See http://niklasschlimm.blogspot.fr/2012/01/java-7-how-to-write-really-fast-java.html?m=1

**Comment by imotov** [comment]
@dadoonet I tried it, for some reason JVM ignores this setting and inlines it anyway. When I turn off inlining completely everything becomes slow (I am getting consistent response time of about 500ms).

**Comment by dadoonet** [comment]
> I tried it, for some reason JVM ignores this setting and inlines it anyway.

Hmmm. That's strange because it is still documented for Java8 http://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html. So this should work. May be `0` is not supported anymore so that we should try `1` instead?

I also wonder if this happened with previous versions of Lucene? May be it's a reproductible behavior which can be reproduced with pure Lucene code which in that cas we should open the issue there?
Or do you believe that elasticsearch code makes that behavior happening?

**Comment by clintongormley** [comment]
@danielmitterdorfer @jpountz any ideas?

**Comment by danielmitterdorfer** [comment]
@clintongormley I'll need a bit more time for a definitive answer but @imotov could try to avoid inlining of the method in question with `-XX:CompileCommand="dontinline org.apache.lucene.search.FakeScorer::score"`. `-XX:MaxInlineSize=0` is somewhat brutal. :)

**Comment by imotov** [comment]
@danielmitterdorfer I am getting about 700ms response time for all requests. By the way, I don't think `FakeScorer::score` is the method in question. Last week, I tried removing FakeScorer completely by commenting out scoring and it didn't have any effect on the result. I am pretty sure the issue is with  `org.apache.lucene.search.TopScoreDocCollector$SimpleTopScoreDocCollector$1::collect`.

**Comment by danielmitterdorfer** [comment]
@imotov Oh, then I just misread your initial comment, sorry. The correct command should be -XX:CompileCommand="dontinline org.apache.lucene.search.TopScoreDocCollector$SimpleTopScoreDocCollector$1::collect" in this case.

**Comment by imotov** [comment]
Yep, tried that as well - same result.

**Comment by danielmitterdorfer** [comment]
In the meantime I ran `esrally --preserve-install=true --pipeline=from-distribution --distribution-version=5.0.0-rc1 --track=nyc_taxis` and got the following 99th percentile service time for the query in question (`match_all`):

![service_times](https://cloud.githubusercontent.com/assets/1699576/19476494/d230b31a-9539-11e6-8880-00f2b50ad4a8.png)

This looks as I'd expect it. Maybe this is something related to your hardware? (CPU cache size?)

**Comment by danielmitterdorfer** [comment]
So, after a couple of experiments I got the following results (see [script source](https://gist.github.com/danielmitterdorfer/4ce26e92e0650f0472e0ab782ae4a98f)):

Force that `org.apache.lucene.search.TopScoreDocCollector$SimpleTopScoreDocCollector$1::collect` is not inlined:

| idx | response_time_ms | took_ms | 
|-----|------------------|---------| 
| 0   | 469.48           | 466.00  | 
| 1   | 507.87           | 504.00  | 
| 2   | 477.45           | 468.00  | 
| 3   | 474.57           | 470.00  | 
| 4   | 473.75           | 469.00  | 
| 5   | 475.56           | 471.00  | 
| 6   | 473.45           | 469.00  | 
| 7   | 474.74           | 470.00  | 
| 8   | 475.93           | 471.00  | 
| 9   | 475.59           | 470.00  | 
| 10  | 474.34           | 469.00  | 

where `response_time_ms` is the end-to-end response time in ms and `took_ms` the content of the `took` field in the JSON response.

With default behavior (i.e. no compiler control command):

| idx | response_time_ms | took_ms | 
|-----|------------------|---------| 
| 0   | 80.07            | 37.00   | 
| 1   | 174.90           | 162.00  | 
| 2   | 269.38           | 257.00  | 
| 3   | 291.43           | 284.00  | 
| 4   | 315.52           | 302.00  | 
| 5   | 270.99           | 257.00  | 
| 6   | 267.95           | 257.00  | 
| 7   | 265.99           | 254.00  | 
| 8   | 267.39           | 255.00  | 
| 9   | 326.63           | 276.00  | 
| 10  | 266.90           | 255.00  | 

We can clearly see:

* the performance impact of inlining
* a real increase in the response time in the second case whereas response time is roughly constant in the first case

**Comment by imotov** [comment]
We have discussed this and it doesn't seem that we should (or can) do something about it and will just leave this to JVM to eventually fix. Closing.
