### ISSUE TITLE
ArrayIndexOutOfBoundsException while searching index, the number of return documents shoud be very large 

### ISSUE THREAD

**Issue by rubbyjing20** [elastic/elasticsearch#20959]
I am using latest version of elasticsearch to search a large number of index. The number of returned document should be around 4000000. I don't want to use scroll cause I would like to record the time to return the result without counting the network time in multiple scrolls. However, when size in search increase to 712227,  I got the ArrayIndexOutOfBoundsException error.  I increase the heap size to 64G and increase the max open file to 65535. Neither of them works. 

The stack trace are as below:
java.lang.ArrayIndexOutOfBoundsException: -131072
.       at org.elasticsearch.common.util.BigByteArray.set(BigByteArray.java:97)
.       at org.elasticsearch.common.io.stream.BytesStreamOutput.writeBytes(BytesStreamOutput.java:93)
.       at org.elasticsearch.common.io.stream.StreamOutput.write(StreamOutput.java:299)
.       at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:2014)
.       at com.fasterxml.jackson.core.json.UTF8JsonGenerator.flush(UTF8JsonGenerator.java:1027)
.       at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.flush(JsonXContentGenerator.java:436)
.       at org.elasticsearch.common.xcontent.json.JsonXContentGenerator.writeRawField(JsonXContentGenerator.java:369)
.       at org.elasticsearch.common.xcontent.XContentBuilder.rawField(XContentBuilder.java:914)
.       at org.elasticsearch.common.xcontent.XContentHelper.writeRawField(XContentHelper.java:378)
.       at org.elasticsearch.search.internal.InternalSearchHit.toXContent(InternalSearchHit.java:476)
.       at org.elasticsearch.search.internal.InternalSearchHits.toXContent(InternalSearchHits.java:184)
.       at org.elasticsearch.search.internal.InternalSearchResponse.toXContent(InternalSearchResponse.java:111)
.       at org.elasticsearch.action.search.SearchResponse.toXContent(SearchResponse.java:195)
.       at org.elasticsearch.rest.action.support.RestStatusToXContentListener.buildResponse(RestStatusToXContentListener.java:43)
.       at org.elasticsearch.rest.action.support.RestStatusToXContentListener.buildResponse(RestStatusToXContentListener.java:38)
.       at org.elasticsearch.rest.action.support.RestStatusToXContentListener.buildResponse(RestStatusToXContentListener.java:30)
.       at org.elasticsearch.rest.action.support.RestResponseListener.processResponse(RestResponseListener.java:43)
.       at org.elasticsearch.rest.action.support.RestActionListener.onResponse(RestActionListener.java:49)
.       at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:89)
.       at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:85)
.       at org.elasticsearch.action.search.SearchScrollQueryThenFetchAsyncAction.innerFinishHim(SearchScrollQueryThenFetchAsyncAction.java:223)
.       at org.elasticsearch.action.search.SearchScrollQueryThenFetchAsyncAction.finishHim(SearchScrollQueryThenFetchAsyncAction.java:211)
.       at org.elasticsearch.action.search.SearchScrollQueryThenFetchAsyncAction.access$100(SearchScrollQueryThenFetchAsyncAction.java:44)
.       at org.elasticsearch.action.search.SearchScrollQueryThenFetchAsyncAction$2.onResponse(SearchScrollQueryThenFetchAsyncAction.java:191)
.       at org.elasticsearch.action.search.SearchScrollQueryThenFetchAsyncAction$2.onResponse(SearchScrollQueryThenFetchAsyncAction.java:185)
.       at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:41)
.       at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:836)
.       at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:820)
.       at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:810)
.       at org.elasticsearch.transport.DelegatingTransportChannel.sendResponse(DelegatingTransportChannel.java:58)
.       at org.elasticsearch.transport.RequestHandlerRegistry$TransportChannelWrapper.sendResponse(RequestHandlerRegistry.java:140)
.       at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:409)
.       at org.elasticsearch.search.action.SearchServiceTransportAction$FetchByIdTransportHandler.messageReceived(SearchServiceTransportAction.java:405)
.       at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
.       at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77)
.       at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
.       at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
.       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
.       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
.       at java.lang.Thread.run(Thread.java:745)

**Comment by dadoonet** [comment]
So you changed the default settings in `elasticsearch.yml` file?

> I don't want to use scroll cause I would like to record the time to return the result without counting the network time in multiple scrolls. 

That's not how it works and I don't see why you would record such a time which is not accurate with what you would do in production.
Use scroll. That's definitely the way to go instead of trying to fill your memory.

And please ask this on discuss.elastic.co if you want to discuss about this. This space is only for bug reports.

**Comment by rubbyjing20** [comment]
Hi, thanks for your reply. I added ES_HEAP_SIZE=64G in elasticsearch file and I would like to record the time because I just want to compare the time with Solr and other search server.

**Comment by s1monw** [comment]
> I would like to record the time because I just want to compare the time with Solr and other search server.

_search servers_ are build to return the top N where N is small (10 or 100) if you wanna retrieve all results we have a dedicated API called scroll. there is not a single reason to compare fetching gazillion of docs in a single run the API is not made for this.

**Comment by dadoonet** [comment]
FI the discussion now moved to https://discuss.elastic.co/t/arrayindexoutofboundsexception-while-searching-index-the-number-of-return-documents-shoud-be-very-large/63160
