### ISSUE TITLE
Painless - Request for native String split function

### ISSUE THREAD

**Issue by gingerwizard** [elastic/elasticsearch#20952]
**Describe the feature**:
String.split is not exposed for performance.  Can achieve using regex but this requires the user to enable regexes for what is a rather common use case.

Can we have a native split that only supports a char sequence and not a regex?

**Comment by clintongormley** [comment]
@jdconrad what do you think?

**Comment by jdconrad** [comment]
I think it's fine to add a native method for this.

**Comment by eliranmoyal** [comment]
Hey , any news on that?
and for now how can i achieve something similar to "doc['myField'].value.split(' ')[1]" using the regex class?
Thanks!

**Comment by jdconrad** [comment]
@eliranmoyal Apologies, I haven't had time to work on this, yet.  @rjernst What do you think the best way to add a String split method would be for this?

**Comment by rjernst** [comment]
I'm apprehensive about this because I think it will cause confusion if we simply add a `split` method available for String with different semantics than javadocs state.

**Comment by nik9000** [comment]
> I'm apprehensive about this because I think it will cause confusion if we simply add a split method available for String with different semantics than javadocs state.

Indeed. If we make one I think it'd be a poor choice to call it `split` because of the one in java. Too confusing.

**Comment by jdconrad** [comment]
@rjernst @nik9000 Good point there here.  Would either of you be in support of having some kind of utils method still?  It might be nice to be able to split on a char if regexes are disabled.

**Comment by nik9000** [comment]
I'd be fine with something like "foo bar".splitOn(" ")

**Comment by gingerwizard** [comment]
What about a tokenize method?

**Comment by jdconrad** [comment]
Already whitelisted -- 

```class StringTokenizer -> java.util.StringTokenizer extends Enumeration,Object {
  StringTokenizer <init>(String)
  StringTokenizer <init>(String,String)
  StringTokenizer <init>(String,String,boolean)
  int countTokens()
  boolean hasMoreTokens()
  String nextToken()
  String nextToken(String)
}```

**Comment by eliranmoyal** [comment]
The tokenizer don't work like split (on multiple char split), the string argument it accepts is a multi delimiters tokens.
meaning `"he*y*+bye".split("*+")` will result in `["he*y","bye"]`
while `StringTokenizer("he*y*+bye","*+")` after iterating will result in `["he","y","bye"]`

**Comment by jshah111** [comment]
Is this now available as of 5.x?

https://www.elastic.co/guide/en/elasticsearch/reference/current/split-processor.html

**Comment by caioflores** [comment]
Any update on it? I was trying to use the method today and found this issue.

**Comment by jdconrad** [comment]
We are currently working on creating a whitelist per script context and will re-address this issue when that work is completed.  For now the easiest way to do this is to use regexes.

**Comment by karmi** [comment]
Voting for having some kind of `split` implementation, for something like `...hostname.split('.')[0]`, to get a subdomain from full URL eg. in aggregations, or transforming payloads in Watcher.

**Comment by tony0918** [comment]
Is that possible to apply a regex pattern to a field value to get substring extracted?

**Comment by jdconrad** [comment]
We should be able to improve this situation now that contexts are done.

**Comment by jdconrad** [comment]
Discussed with @rjernst.  We will add an augmented method for String with the signature like String[] splitOnToken(String).  This will be usable without requiring regexes to be enabled.

**Comment by ypid-geberit** [comment]
I stumbled across this and am proposing a `splitOnToken` version which is based on the String split implementation of openjdk. Hope this helps. I tested it on Elasticsearch 6.2.4.

```Java
List splitOnToken(String input, char ch, int limit) {
  /* Painless does not have String split so we reimplement it here.
   * Ref: https://github.com/elastic/elasticsearch/issues/20952
   * Based on: https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/java/lang/String.java
   * It returns a ArrayList instead of a String[] because list.toArray does not seem to be whitelisted in Painless.
   * Example: splitOnToken("gnu.example.org", (char)'.')[0]
   */
  int off = 0;
  int next = 0;
  boolean limited = limit > 0;
  ArrayList list = new ArrayList();

  while ((next = input.indexOf(ch, off)) != -1) {
    if (!limited || list.size() < limit - 1) {
      list.add(input.substring(off, next));
      off = next + 1;
    } else {    // last one
      //assert (list.size() == limit - 1);
      list.add(input.substring(off, input.length()));
      off = input.length();
      break;
    }
  }

  if (off == 0) {
    list.add(input);
    return list;
  }

  if (!limited || list.size() < limit) {
    list.add(input.substring(off, input.length()));
  }

  int resultSize = list.size();
  if (limit == 0) {
    while (resultSize > 0 && list.get(resultSize-1).length() == 0) {
      resultSize--;
    }
  }
  return list.subList(0, resultSize);
}

List splitOnToken(String input, char ch) {
  return splitOnToken(input, ch, 0);
}
```
