### ISSUE TITLE
Primary shard is not active or isn't assigned is a known node

### ISSUE THREAD

**Issue by barik94** [elastic/elasticsearch#20967]
I use elasticsearch `ver. 1.4.4` with FOS Elastica Bundle. 
On reindex data see `Primary shard is not active or isn't assigned is a known node` error.
Find only this advice 
http://stackoverflow.com/questions/27547091/primary-shard-is-not-active-or-isnt-assigned-is-a-known-node 
but my disk is full on 76% not 85%.
So what a problem?
Help me, please

**Comment by bleskes** [comment]
We use github to report bugs, issues and features. We're happy to help you figure what's going on, but please ask it on discuss.elastic.co . Thanks you!

**Comment by barik94** [comment]
@bleskes https://discuss.elastic.co/t/primary-shard-is-not-active-or-isnt-assigned-is-a-known-node/63182
