### ISSUE TITLE
Elasticsearch publishes wrong ip when run with docker 1.12 in swarm mode.

### ISSUE THREAD

**Issue by guenhter** [elastic/elasticsearch#20961]
**Elasticsearch version**:
5.0.0-RC1

**Plugins installed**: []
None

**JVM version**:
Shipped Version with Elasticsearch-Docker
https://github.com/elastic/elasticsearch-docker

**OS version**:
Debian 8 in Guest (using Elasticsearch via Docker)
Linux machine1 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Tried to create an elasticsearch cluster with docker 1.12.2 in swarm mode. ES now publish_address point to a wrong destination. It should connect to the actual correct VIP but it points to the \32 address which is equal for all scaled services.

**Steps to reproduce**:
1. Run these commands:

```
docker network create   --driver overlay   --subnet 10.0.9.0/24   --opt encrypted   services

docker service create --name es      --replicas 1 --network services -p 9200 -p 9300 -e "discovery.zen.minimum_master_nodes=2" -e "ES_JAVA_OPTS=-Xms256m -Xmx256m"                                                 docker.elastic.co/elasticsearch/elasticsearch
```
1. Than check the ip addresses of the container with 
   `docker exec CONTAINER-ID ip address`

```
...
32: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1424 qdisc noqueue state UP
    link/ether 02:42:0a:00:09:07 brd ff:ff:ff:ff:ff:ff
    inet 10.0.9.7/24 scope global eth2
       valid_lft forever preferred_lft forever
    inet 10.0.9.6/32 scope global eth2
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:fe00:907/64 scope link
       valid_lft forever preferred_lft forever
```
1. `docker logs CONTAINER-ID` shows, that the container connect to 10.0.9.6/32
   `[2016-10-14T17:06:55,515][INFO ][o.e.t.TransportService   ] [5xx0tvy] publish_address {10.0.9.6:9300}, bound_addresses {[::]:9300}`

This is a problem, because that address is shared among all tasks (all scaled containers) and only the first ES-instance will register successfully, all others get a
`[2016-10-14T17:43:07,760][INFO ][o.e.d.z.ZenDiscovery     ] [XlcRAHZ] failed to send join request to master [{5xx0tvy}{5xx0tvyJR0GX2WMCBaw8ig}{6WExWxXlRYC4XwlFSuyOcw}{10.0.9.6}{10.0.9.6:9300}], reason [RemoteTransportException[[5xx0tvy][10.0.9.7:9300][internal:discovery/zen/join]]; nested: IllegalArgumentException[can't add node {XlcRAHZ}{XlcRAHZ0S6aEDrmhK7UC_g}{SRbRCA4ESp6OLDNJWU-NXA}{10.0.9.8}{10.0.9.8:9300}, found existing node {1N8RQt-}{1N8RQt-3QwS4ANWneRGGgQ}{wYsLm1gyS4mtFiwYKx0KPA}{10.0.9.8}{10.0.9.8:9300} with same address]; ]`
message

**Comment by clintongormley** [comment]
Thanks for trying out the RC.  What logic could we apply to choose the other IP automatically (and in a generic, non-docker-specific way)?

**Comment by guenhter** [comment]
I'm in discussion with the docker guys what the correct way is. I let you know ASAP.

**Comment by guenhter** [comment]
@clintongormley 

```
link/ether 02:42:0a:00:00:05 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.5/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.0.0.4/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:fe00:5/64 scope link
       valid_lft forever preferred_lft forever
```

I notices the following in the ES log:
```
....
publish_address {10.0.0.4:9302}, bound_addresses {[::]:9302}
[2016-10-18T19:08:11,178][INFO ][o.e.b.BootstrapCheck     ] [ZPJ6URQ] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2016-10-18T19:08:14,286][INFO ][o.e.c.s.ClusterService   ] [ZPJ6URQ] new_master {ZPJ6URQ}{ZPJ6URQUT4KIdtOIAbNmxQ}{_rOzPemYR2uA3izwXQQt4w}{10.0.0.4}{10.0.0.4:9302}, added {{bRwjGA2}{bRwjGA2BS2SoPvLLWmZyhA}{LETUSTEIQM2gXX646OzrYA}{10.0.0.2}{10.0.0.2:9301},}, reason: zen-disco-elected-as-master ([1] nodes joined)[{bRwjGA2}{bRwjGA2BS2SoPvLLWmZyhA}{LETUSTEIQM2gXX646OzrYA}{10.0.0.2}{10.0.0.2:9301}]
...
[2016-10-18T21:19:51,840][WARN ][o.e.x.s.t.n.SecurityNetty4Transport] [ZPJ6URQ] exception caught on transport layer [[id: 0xa4d1e4b0, L:/10.0.0.5:60162 - R:/10.0.0.2:9301]], clos
...
```

It seems, that `10.0.0.4` (subnet 32) is used for publishing but for the actual transport, the `10.0.0.5` (subnet 24) is used. IMO the latter one is the better choice. Can't ES be just published, where it communicates?

**Comment by guenhter** [comment]
I close this for now and re-open it in case something should be done. Best approach would be, if docker can handle this and ES has nothing to do.
