### ISSUE TITLE
Index expression matching improvements

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#20962]
As part of #20898 we discussed some improvements to index expression matching that we should work on for 6.0:
- given that there won't be indices starting with `-` around anymore (those indices have been created with 2.x and will need reindexing on 6.x), we can re-evaluate how negations work. Order shouldn't matter anymore, e.g. `-test1,test*` and `test*,-test1` should resolve to the same set of indices, while in 5.x the former resolves to a concrete index called `-test1`, and the latter is an actual negation.
- remove support for `+` (deprecate in 5.x), it is implicit when not specified

**Comment by bleskes** [comment]
>  Order shouldn't matter anymore, e.g. -test1,test* and test*,-test

Can you elaborate more about this? it doesn't feel intuitive to me. I would expect that you can't start with negation (you must have something first to remove it) and that things are evaluated in order - add some, remove some, remove some more, add things again etc.

**Comment by javanna** [comment]
I see. Marking as discuss then, I couldn't come up with cases where the order would make a difference, I thought it would make things more complicated, but it may be me. I see it as remove this index from the indices matched by the rest of the expression.

Whatever we decide to do here, we have to remember to change the "wildcarSeen" behaviour, as with #20898 we explicitly support indices that have names starting with `-`. We don't have to support those in 6.x, hence we could either make the order not matter or reject index patterns with negations that don't start with a wildcard expression.

**Comment by dakrone** [comment]
> remove support for `+` (deprecate in 5.x), it is implicit when not specified

+1

As far as the ordering goes, I agree with @bleskes, it's strange to have negations before adding anything, so I would be in favor of disallowing starting the expressions with `-` (requiring something like `*,-foo`)

**Comment by javanna** [comment]
Opened #24515 . There was no consensus on the ordering matter so I left that out.
