### ISSUE TITLE
Ability to tag different segments of custom scoring queries and later retrieve with explanation.

### ISSUE THREAD

**Issue by kmalhotra** [elastic/elasticsearch#20985]
**Tag query functional scoring segments to be used with _explanation**: It would be great if ES can provide an ability to tag certain aspects of functional score score and later retrieve and use with _explain api.

Let me provide some insights into my use case, let me know if a workaround exists the same.

I have a complex functional scoring query,used to find relevancy between two entities based on custom scoring logic. Things work well with "_search" api, since I only need the total score at that point of time, but for some other background process I need specific details wrt how each component of the functional score query contribute to the total score. I am using "_explain" for this, but there are 2 problems that I face:-
1. The response of _explain is tricky to decode, i.e identify contribution of each field to the total score (with java api).
2. I also have a complex logic which defines different weight for each keyword matching against a single field in the entity, this means that even if I am able to solve issue 1, there is no way for me to differentiate between these scores.

**My Suggestion**:- It would be great if I can just tag different segments of query at query preparation time(for _explain api and not _search api ) and individual factors in response.

Thoughts/Suggestion/ Work around?

**Comment by clintongormley** [comment]
Hi @kmalhotra 

First, I wouldn't use the explain API for production searches - it adds a LOT of overhead.  Second, I'm not sure we can comfortably store all of this info for every search hit and return it.  Perhaps you should use script score to calculate this info just on the results you return instead?

**Comment by kmalhotra** [comment]
Hi @clintongormley 

I am not using "_explain" for production searches. It is only used as a background task only to analyse scores, hence I can afford a performance hit.  

Also, I have updated my suggestion in the initial comment.

**How would I use this? 
1. For real time production searches, I will prepare the query(with tags but of no use) and will execute on "_search" api.
2. For background process, I will prepare the query same way(with tags) and will execute on "_explain" api and fetch individual scores based on tags. 

Thoughts?

**Comment by andyb-elastic** [comment]
From the discussion here it sounds like this isn't something we currently want to implement. We're always open to reconsidering in the future based on feedback, which is always welcome.

@elastic/es-search-aggs
