### ISSUE TITLE
support date math in field stats API

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#20984]
**Describe the feature**:
Add date math support to the field stats API. The ability to do something like this could be useful:

```
GET metricbeat-*/_field_stats?level=indices
{
  "fields": ["@timestamp"],
  "index_constraints": {
    "@timestamp": {
      "max_value": {
        "lt":"now-30d"
      }
    }
  }
}
```

It could help with managing time series indices. Other uses?

**Comment by clintongormley** [comment]
Duplicate of https://github.com/elastic/elasticsearch/issues/21182
