### ISSUE TITLE
LoggerMessageFormat class has ambigous method arguments

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#20987]
The `LoggerMessageFormat` class has two `format` calls, one that accepts a prefix and the other one that doesnt.

In the rare special case of handing over only a single string as part of the message to be formatted, the method with the prefix gets called, even though the developer most likely intended to call the other class.

A code example

```
public class LoggerMessageFormatTests extends ESTestCase {

    public void testThatLoggingWorksWithoutPrefix() throws Exception {
        assertThat(LoggerMessageFormat.format("this", " is {}", "sparta"), is("this is sparta"));
        assertThat(LoggerMessageFormat.format("", "this is {}", "sparta"), is("this is sparta"));
        // this one fails as the returned string is "this is {}sparta"
        assertThat(LoggerMessageFormat.format("this is {}", "sparta"), is("this is sparta"));
    }
}
```

This might bite, when the developer throws a non ES exception and wants to create a useful string first using the `LoggerMessageFormat`.

**Comment by jasontedor** [comment]
I'd prefer to just get rid of `LoggerMessageFormat` (I've mentioned this previously).

**Comment by pgomulka** [comment]
still an issue and we might want to work on it

**Comment by glgomess** [comment]
Hi there! Can i work on this? (newcomer here)

**Comment by glgomess** [comment]
Hi! I've submmitted ther PR, but it failed with the CLA. I've tried many times to sign it, and it seems to work, but the cla-bot continues to block the PR.
Here's a print of the signed document:

![Captura de Tela (132)](https://user-images.githubusercontent.com/32991894/124037214-91a98700-d9d5-11eb-9c6f-b3586e482a26.png)

Anyone knows what it could be?

**Comment by ldematte** [comment]
If/when we are going to work on logging, we are going to remove LoggerMessageFormat entirely. Closing.
