### ISSUE TITLE
Document Whitelisted Painless Functions

### ISSUE THREAD

**Issue by gingerwizard** [elastic/elasticsearch#20989]
Elasticsearch 5.0 rc1

Can we document the functions listed [here](https://github.com/elastic/elasticsearch/tree/master/modules/lang-painless/src/main/resources/org/elasticsearch/painless)

Maybe just generate an Java docs that link through to the appropriate Java function to simplify maintenance?  At worse can we reference this in the main page?

**Comment by nik9000** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/painless-api-reference.html
