### ISSUE TITLE
Migrate select examples of native scripts into native script engine

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#20983]
In #19966 we outline our goal to deprecate and then remove native script engine. The first step towards this goal is to create a set of examples that demonstrates how to write effective script engines for different tasks similar to what we did in the [native script example project](https://github.com/imotov/elasticsearch-native-script-example).

**Comment by rjernst** [comment]
@imotov Since we have expert script engine usage documented now and native scripts removed from master, can this be closed? Or were there more examples you want to copy over?

**Comment by imotov** [comment]
I agree, I think we can close this one.
