### ISSUE TITLE
[Bug] Scroll API not allowing "." convention for embedded document objects

### ISSUE THREAD

**Issue by timford2015** [elastic/elasticsearch#21003]
On ElasticSearch 2.4, it would seem that the Scroll API is unable to deal with nested "." field structures, the exact same query is usable with the "_search" API.

Document Structure:

{ "event":{
     "collected":"<date data>",
     "field1": "<value>",
     "field2": "<value>",
     "field3": "<value>",
     "field4": "<value>",
     "field5": "<value>"
  },
  "context":{
    "field1":"<data>",
    "field2":"<data>",
    "field3":"<data>",
    "field4":"<data>",
    "field5":"<data>"
}}

Submitted Query:
{"query":{"filtered":{"query":{"query_string":{"query":"*","analyze_wildcard":true}},"filter":{"bool":{"must":[{"range":{"event.collected":{"gte":1471568336217,"lte":1476752336217,"format":"epoch_millis"}}}],"must_not":[]}}}}}

Resulting Output:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Field name [event.collected] cannot contain '.'"}],"type":"mapper_parsing_exception","reason":"Field name [event.collected] cannot contain '.'"},"status":400}

**Comment by clintongormley** [comment]
@timford2015 your query is broken.  you have range inside terms, and missing a `}`.

Was this a bad copy paste?  Try putting the real query.

**Comment by timford2015** [comment]
sorry a bad cut and paste -- fixed

**Comment by clintongormley** [comment]
@timford2015 what do you mean by the scroll API?  You don't pass queries to the scroll API.  You pass a scroll ID.

And the exception you're getting sounds like you're trying to create a document, not using the scroll API.  

This sounds like user error to me rather than a bug.  I suggest you ask for advice in the forum instead: http://discuss.elastic.co

**Comment by timford2015** [comment]
I know that you pass a scroll ID -- however to get the scroll ID you must initiate a query with the scroll=<timeframe> appended to the restful call -- I am even trying the documentation on  this page: https://www.elastic.co/guide/en/elasticsearch/guide/current/scroll.html

There seems to be an issue with the documentation in that if you follow it step by step -- you still need to add document type to the restful url.  As well as I don't get a scroll_id to then make the next query for retrieving documents.  I can go to the forum -- that might help -- but there still seems to be a bug on at least the initial query of not accepting "." in the field name for a query when initiating at the start of the scroll API calls
