### ISSUE TITLE
Elasticsearch cluster not recovers from disconnection

### ISSUE THREAD

**Issue by guenhter** [elastic/elasticsearch#21010]
**Elasticsearch version**:
5.0.0-RC1
use elasticsearch-docker

**Plugins installed**: []
Not by myself. Only already installed plugins from elasticsearch-docker

**JVM version**:
JVM from elasticsearch-docker

**OS version**:
Debian 8.6
Linux apollo 4.7.0-0.bpo.1-amd64 #1 SMP Debian 4.7.5-1~bpo8+2 (2016-10-01) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Cluster running on two nodes. Only one of them is configured as master, but both are data nodes.
It is running within docker swarm (and also use the overlay network of docker).
The plain cluster (which is idle because nothing is currently writing to it) nodes sometimes loses their connection to each other but it seems that they don't recover from tag (at least not always)

Its not (at least not only) a networking issue, because when I remove and re-add the data node, everything is fine again.

```
curl -u elastic http://138.201.138.161:9201/_cat/health
Enter host password for user 'elastic':
1476855078 07:31:18 docker-cluster yellow 1 1 7 7 0 0 6 0 - 53.8%
```

**Steps to reproduce**:
 1. Setup docker 1.12.2 in swarm mode (with at least two nodes)
 2. Run two nodes (one master one only data)
 3. Just leave them over night
 4. In the morning, the cluster state is yellow because the connection is lost

```
docker network create --driver overlay elastic
docker service create \
              --name es_1 \
              --network elastic \
              -p 9201:9200 -p 9301:9301 \
              -e "discovery.zen.ping.unicast.hosts=es_1:9301" \
              -e ES_JAVA_OPTS="-Xms256m -Xmx256m" \
              -e "discovery.zen.minimum_master_nodes=1" \
              -e "transport.tcp.port=9301" \
              --mount type=bind,source=/etc/localtime,destination=/etc/localtime,readonly \
              --mount type=bind,source=/etc/timezone,destination=/etc/timezone,readonly \
              --mount type=volume,source=elasticsearch,destination=/usr/share/elasticsearch/data \
              docker.elastic.co/elasticsearch/elasticsearch
docker service create \
              --name es_2 \
              --network elastic \
              -p 9202:9200 -p 9302:9302 \
              -e "discovery.zen.ping.unicast.hosts=es_1:9301" \
              -e ES_JAVA_OPTS="-Xms256m -Xmx256m" \
              -e "discovery.zen.minimum_master_nodes=1" \
              -e "transport.tcp.port=9302" \
              --mount type=bind,source=/etc/localtime,destination=/etc/localtime,readonly \
              --mount type=bind,source=/etc/timezone,destination=/etc/timezone,readonly \
              --mount type=volume,source=elasticsearch,destination=/usr/share/elasticsearch/data \
              docker.elastic.co/elasticsearch/elasticsearch
```

** Logs
[es_log_data_node.txt](https://github.com/elastic/elasticsearch/files/538038/es_log_data_node.txt)
[es_log_master_node.txt](https://github.com/elastic/elasticsearch/files/538037/es_log_master_node.txt)

**Comment by ywelsch** [comment]
this is expected as you had a split brain because of misconfiguring `discovery.zen.minimum_master_nodes=1`. Both nodes seem to be master-eligible, see the warning in the logs:

```
[2016-10-18T19:08:14,359][WARN ][o.e.d.z.ElectMasterService] [ZPJ6URQ] value for setting "discovery.zen.minimum_master_nodes" is too low. This can result in data loss! Please set it to at least a quorum of master-eligible nodes (current value: [1], total number of master-eligible nodes used for publishing in this round: [2])
```
