### ISSUE TITLE
Add support for shortcut operators for lists in painless

### ISSUE THREAD

**Issue by ctindel** [elastic/elasticsearch#21027]
Following up on this bug report:

https://github.com/elastic/elasticsearch/issues/21026

Just creating a feature request to allow shortcut operators for lists in painless.

**Comment by jdconrad** [comment]
Note as an example this would be like the following:

``` def x = new ArrayList(); def y = 1; x += y;```

The list as a result would be [1].

**Comment by jdconrad** [comment]
We have decided to not change this.  Closing.
