### ISSUE TITLE
Got different results between Multi-Type and Type Query

### ISSUE THREAD

**Issue by dragonkid** [elastic/elasticsearch#21035]
**Elasticsearch version**: 2.1.1

**Plugins installed**: [head, kopf]

**JVM version**:

java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

**OS version**:

ubuntu 14.04

**Description of the problem including expected versus actual behavior**:

when I search data like this:

```
http://localhost:9200/*-*/574661f050b7fe40c61e6236,57451c9f50b7fe40c61e6230,574548e750b7fe40c61e6234/_search

{
  "query": {
    "match_all": {}
  }
}
```

I got the results in other types.

Only when I search like this:

```
http://localhost:9200/*-*/_search

{
  "query": {
    "bool": {
      "should": [
        {
          "type": {
            "value": "574661f050b7fe40c61e6236"
          }
        },
        {
          "type": {
            "value": "574548e750b7fe40c61e6234"
          }
        },
        {
          "type": {
            "value": "57451c9f50b7fe40c61e6230"
          }
        }
      ]
    }
  }
}
```

I got the results which I supposed to.

I want to know how can I fix this, thx:)

**Comment by jpountz** [comment]
Would you be able to provide a simple script that reproduces the issue?

**Comment by dragonkid** [comment]
Sorry, I can't. Because this issue can not be reproduced everytime. But I have met this three times.

**Comment by clintongormley** [comment]
Without further info we're unable to do any more here.  Closing
