### ISSUE TITLE
`ip_range` aggregation does not automatically generate a `key` for each bucket

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#21045]
While writing tests for the `ip_range` aggregation, I noticed that it does not automatically generate a key for each range, while the `range` aggregation on a numeric field does. Should we make this consistent?

**Comment by colings86** [comment]
@elastic/es-search-aggs

**Comment by nikhilbarar** [comment]
Is this issue accepted?

**Comment by talevy** [comment]
@nikhilbarar the exact details may not have been hashed out, but since this issue was recently tagged with `adoptme` then yes, it has been accepted as something to look into fixing
