### ISSUE TITLE
Problem with coerce?

### ISSUE THREAD

**Issue by ctindel** [elastic/elasticsearch#21053]
Testing with 5.0.0-RC1 on elastic cloud.  It's possible I'm not doing this right but I think I followed the docs.  I'm trying to make es cast some strings to integers and floats, but they seem to stay in as strings.

```
curl -XPUT foo -d '{
  "mappings" : {
    "data" : {
      "properties" : {
        "myFloat" : { "type": "float", "coerce": true},
        "myInt" : { "type": "integer", "coerce": true}
      }
    }
  }
}'

curl -XPOST foo/foo/1 -d '{
  "myFloat" : "1.5",
  "myInt" : "1"
}'

GET foo/foo/1
```

Returns:

```
{
  "_index": "foo",
  "_type": "foo",
  "_id": "1",
  "_version": 1,
  "found": true,
  "_source": {
    "myFloat": "1.5",
    "myInt": "1"
  }
}
```

**Comment by rjernst** [comment]
`_source` is always what you pass in, ie the raw json. `coerce` means "when parsing, force it into the type of the field. So in this case, it means it will do an Integer.parseInt and Float.parseFloat.

**Comment by bluelink8888** [comment]
so when will see result json type is Integer or Float?
you mean api will do pasre work?

**Comment by jpountz** [comment]
@bluelink8888 The coerce option tells Elasticsearch to not reject the document if the provided value is a string that can be parsed to the expected type (eg. float or integer). However the source is not updated like Ryan said. If you want these values to be converted to numbers, this should be done in your ingestion pipeline (eg. logstash) if you have one, or on client side.

**Comment by jpountz** [comment]
Note that in 5.0 it will be possible to do it automatically with a `convert` processor: https://www.elastic.co/guide/en/elasticsearch/reference/master/convert-processor.html

**Comment by bluelink8888** [comment]
@jpountz thanks for answer. i have same problem before.
when i use postman to get data. the result json show datatype is String.
but when i use java api to search data. the result in java will convert to what i setting before.
i don't know it will convert datatype before.
