### ISSUE TITLE
Elasticsearch runs out of heap space after running ~1 week

### ISSUE THREAD

**Issue by jbstrm** [elastic/elasticsearch#21059]
We're running Elasticsearch 2.3.2 (and Kibana 4.5.0) on an Azure Virtual Machine with Windows Server 2012 R2 and 14 MB RAM (2 core cpu). Java version 8.0.910.14. head plugin is also installed.

We have a problem with used heap size, while fluctuating a bit, slowly increases until it reaches 99% and staying there constantly. It warns about GC (old) taking about 12 seconds to finish. Then it crashes with a java.lang.OutOfMemoryError: Java heap space. This takes about a week to ten days.

bootstrap.mlockall is set to true in elasticsearch.yml config.

Elasticsearch service manager Java Options:
-XX:+UseParNewGC
-Xms4096m
-Xmx4096m
-Djava.awt.headless=true
-XX:+UseCMSInitiatingOccupancyOnly
-XX:+HeapDumpOnOutOfMemoryError
-XX:+DisableExplicitGC
-Dfile.encoding=UTF-8
-Djna.nosys=true
-Delasticsearch

Initial memory pool: 4096 MB
Maximum memory pool_ 4096 MB
Thread stack size: 256 KB

Any ideas?

**Comment by jasontedor** [comment]
Elastic reserves GitHub for bug reports and feature request but provides a [Discourse forum](https://discuss.elastic.co) for general questions.
