### ISSUE TITLE
Inner hits should fail when the same name is used multiple times in the same query

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#21055]
This typically happens if the query contains eg. two inner hits definitions on the same nested path and does not define explicit names for inner hits.

**Comment by martijnvg** [comment]
Additionally we can maybe also make `name` option required.

**Comment by jpountz** [comment]
I think users like the fact that we use a name that is a good description of the join by default. Also most queries should be reasonable and only do one join. So I'd be leaning towards keeping `name` optional.

**Comment by andyb-elastic** [comment]
It looks like duplicate names are still allowed in master, both with `name` explicitly provided or not. This sounds like something we likely still want to do

@elastic/es-search-aggs

**Comment by jimczi** [comment]
This was implemented in https://github.com/elastic/elasticsearch/pull/37645, hence closing
