### ISSUE TITLE
DocsClientYamlTestSuiteIT sometimes fails

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#21062]
`DocsClientYamlTestSuiteIT` sometimes fails because the order of the indices returned by the `_cat/indices` of the documentation snippet is wrong.

<details>
REPRODUCE WITH: gradle :docs:integTest -Dtests.seed=286B3ECD348881B0 -Dtests.class=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT -Dtests.method="test {yaml=reference/cat/indices/line_8}" -Dtests.security.manager=true -Dtests.locale=und -Dtests.timezone=Iran

> [2016-10-21T15:24:37,056][INFO ][o.e.s.DocsClientYamlTestSuiteIT] Stash dump on failure [{
>   1>   "stash" : {
>   1>     "body" : "health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size\ngreen  open   twitter2 _xA1Q6kuSSa6D6JvWLaaLg   5   0          0            0       260b           260b\nyellow open   twitter  -iylnuImQpahvry2rLVLBw   1   1       1200            0       130b           130b\n"
>   1>   }
>   1> }]
>   1> [2016-10-21T15:24:37,057][ERROR][o.e.s.DocsClientYamlTestSuiteIT] This failing test was generated by documentation starting at reference/cat/indices.asciidoc:line_8. It may include many snippets. See docs/README.asciidoc for an explanation of test generation.
>   2> REPRODUCE WITH: gradle :docs:integTest -Dtests.seed=286B3ECD348881B0 -Dtests.class=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT -Dtests.method="test {yaml=reference/cat/indices/line_8}" -Dtests.security.manager=true -Dtests.locale=und -Dtests.timezone=Iran
> FAILURE 0.71s | DocsClientYamlTestSuiteIT.test {yaml=reference/cat/indices/line_8} <<< FAILURES!
> Throwable #1: java.lang.AssertionError: Failure at [reference/cat/indices:2456]: field [$body] was expected to match the provided regex but didn't
> Expected: health \s+status \s+index    \s+uuid                   \s+pri \s+rep \s+docs.count \s+docs.deleted \s+store.size \s+pri.store.size\s\* yellow \s+open   \s+twitter  \s+.+   \s+1   \s+1       \s+1200            \s+0     \s+\d+(.\d+)?[tgmk]?b         \s+\d+(.\d+)?[tgmk]?b\s\* green  \s+open   \s+twitter2 \s+.+   \s+5   \s+0          \s+0            \s+0       \s+\d+(.\d+)?[tgmk]?b           \s+\d+(.\d+)?[tgmk]?b\s*
>      but: was "health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size\ngreen  open   twitter2 _xA1Q6kuSSa6D6JvWLaaLg   5   0          0            0       260b           260b\nyellow open   twitter  -iylnuImQpahvry2rLVLBw   1   1       1200            0       130b           130b\n"
>    at __randomizedtesting.SeedInfo.seed([286B3ECD348881B0:A03F01179A74EC48]:0)
>    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:329)
>    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:309)
>    at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.AssertionError: field [$body] was expected to match the provided regex but didn't
> Expected: health \s+status \s+index    \s+uuid                   \s+pri \s+rep \s+docs.count \s+docs.deleted \s+store.size \s+pri.store.size\s\* yellow \s+open   \s+twitter  \s+.+   \s+1   \s+1       \s+1200            \s+0     \s+\d+(.\d+)?[tgmk]?b         \s+\d+(.\d+)?[tgmk]?b\s\* green  \s+open   \s+twitter2 \s+.+   \s+5   \s+0          \s+0            \s+0       \s+\d+(.\d+)?[tgmk]?b           \s+\d+(.\d+)?[tgmk]?b\s*
>      but: was "health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size\ngreen  open   twitter2 _xA1Q6kuSSa6D6JvWLaaLg   5   0          0            0       260b           260b\nyellow open   twitter  -iylnuImQpahvry2rLVLBw   1   1       1200            0       130b           130b\n"
>    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
>    at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:64)
>    at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:76)
>    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:325)
>    ... 37 more
> IGNOR/A 0.01s | DocsClientYamlTestSuiteIT.test {yaml=reference/setup/cluster_restart/line_21}
> Assumption #1: [reference/setup/cluster_restart/line_21] skipped, reason: features [always_skip] not supported
> IGNOR/A 0.01s | DocsClientYamlTestSuiteIT.test {yaml=reference/indices/create-index/line_153}
> Assumption #1: [reference/indices/create-index/line_153] skipped, reason: features [always_skip] not supported
>   2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-unix-compatibility/os/opensuse/docs/build/testrun/integTest/J0/temp/org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT_286B3ECD348881B0-001
>   2> NOTE: test params are: codec=Asserting(Lucene62), sim=RandomSimilarity(queryNorm=true,coord=crazy): {}, locale=und, timezone=Iran
>   2> NOTE: Linux 3.16.7-29-default amd64/Oracle Corporation 1.8.0_101 (64-bit)/cpus=4,threads=1,free=425831832,total=523239424
>   2> NOTE: All tests run in this JVM: [DocsClientYamlTestSuiteIT]
> Completed [1/1] in 115.11s, 665 tests, 1 failure, 15 skipped <<< FAILURES!
> 
> [ant:junit4] JVM J0: stderr was not empty, see: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-unix-compatibility/os/opensuse/docs/build/testrun/integTest/temp/junit4-J0-20161021_115306_814.syserr
> Tests with failures:
> - org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/cat/indices/line_8}

`twitter2` appears before `twitter` which is wrong.
</details>

**Comment by a2lin** [comment]
@tlrx Has this been happening on all platforms? I think this test was run on opensuse?

Sorting (&s=index) should have made this output deterministic.

I tried on master several times and was unable to reproduce (test passed). I then changed the sort order (with the corresponding flip in output) and it still worked. I then reversed the order of the v and s parameters (in order to ensure that all parameters were consumed) and that also passed.

I'm a bit stuck. Do you have any tips on how to debug this more?

**Comment by nik9000** [comment]
I'll have a look in a bit - I thought I was going to grab it on Friday but I didn't because I got distracted. I think it is a somewhat rare issue caused by timing. Or something. Not sure. The output when this failed is:

```
health status index uuid pri rep docs.count docs.deleted store.size pri.store.size
green open twitter2 _xA1Q6kuSSa6D6JvWLaaLg 5 0 0 0 260b 260b
yellow open twitter -iylnuImQpahvry2rLVLBw 1 1 1200 0 130b 130b
```

Which is legit output, just that the `store.size` really is strange. See that `twitter` is `130b` but has more documents? It might be that we just can't rely on the size of the index to be consistent so I have to be underhanded about testing the snippet.

I'll take a closer look in a few hours when I'm able.

**Comment by jpountz** [comment]
This happened again: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu/249/testReport/junit/org.elasticsearch.smoketest/DocsClientYamlTestSuiteIT/test__yaml_reference_cat_indices_line_8_/

**Comment by nik9000** [comment]
@jpountz opened a PR to switch the sort from the size to the number of documents. My early flush wasn't good enough.

**Comment by abeyad** [comment]
@nik9000 The test failed again, this time a _cat/recovery test:   - org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/cat/recovery/line_16}

See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.3+multijob-intake/192/console

**Comment by nik9000** [comment]
If you assign it to me I can have a look on Monday. Every "method" that
fails on this is its own unique issue, just like with the yaml rest tests.

**Comment by nik9000** [comment]
That last failure was just a timing burble. I've pushed b2b1f2f37f24363b18d1e5559f538d94b0892847 so we'll be ok with such burbles in the future.
