### ISSUE TITLE
Doc:  Optional reindexing for 2.x -> 5.x to take advantage of new features

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#21076]
**Elasticsearch version**: 5.0

On the current upgrade page, we indicate that between 1.x -> 5.x, reindex to upgrade is required.  And for 2.x -> 5.x, a full cluster restart upgrade.  

But there are scenarios (optional) where reindexing is necessary even for 2.x -> 5.x upgrades.  For example, for existing indices where the user may want to take advantage of the new points type in 5.x.  These will require reindexing to take advantage of (simply upgrading from 2.x -> 5.0 is not sufficient).

Looking at the current documentation, the [upgrade](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/setup-upgrade.html) section simply mentions a full cluster restart upgrade for 2.x -> 5.x.  There's no reference to the (previously known as) upgrade api, or the need to reindexing to take advantage of new features.  If you go directly to the [upgrade api](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/indices-upgrade.html) page, it says it's been deprecated/removed and replaced by the new [reindex to upgrade](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/reindex-upgrade.html) page, which is solely focused on the 1.x -> 5.x upgrade. 

It will be nice to add the following
- From the upgrade guide, a note on when 2.x -> 5.x users may still want to reindex.  Maybe specify the supported upgrade type as Full cluster restart (optional: Reindex existing indices after upgrade) and link to below.
- On the Reindex to upgrade page, create a new section for 2.x -> 5.x, and indicate why users may still want to reindex existing indices (which they can certainly do after performing the full cluster restart upgrade) to take advantage of new features, eg.
  - New points type
  - New geospatial data structures
  - Any other ones?

**Comment by debadair** [comment]
Closing as obsolete.
