### ISSUE TITLE
5.0.0-rc Unable to enable _size

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#21071]
I'm upgrading from 1.x and ran into an error with enabling `_size` (5.0-rc on Windows 10). As per the docs here:
https://www.elastic.co/guide/en/elasticsearch/plugins/5.0/mapper-size-usage.html

```
PUT my_index
{
  "mappings": {
    "my_type": {
      "_size": {
        "enabled": true
      }
    }
  }
}
```
Fails with 

```json
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [my_type]: Root mapping definition has unsupported parameters:  [_size : {enabled=true}]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "Root mapping definition has unsupported parameters:  [_size : {enabled=true}]"
    }
  },
  "status": 400
}
```

**Comment by niemyjski** [comment]
I've tried with the mapping and ingest plugins installed. I get the same behavior as a vanilla install.

**Comment by rjernst** [comment]
_size was moved to a plugin. You need to install mapper-size

**Comment by nik9000** [comment]
I *think* 

> I've tried with the mapping and ingest plugins installed.

means they've installed the plugin. I'm not sure though.

We have integration tests for this plugin and they are still passing. The documentation @niemyjski  linked also contains snippets that are tested as well.

**Comment by niemyjski** [comment]
I've installed two different plugins from that docs page and both caused it to fail.

**Comment by niemyjski** [comment]
hmm, I wonder if this is related to: https://github.com/elastic/elasticsearch/issues/21072

Because I installed the plugin and asked for elevated permissions, it said it installed. I rebooted the node and tried and it failed. I just reinstalled it (didn't ask for permissions), then rebooted the node and this worked.

**Comment by niemyjski** [comment]
Could the plugin have failed to install (after I gave it permissions) and it said it succeeded?

**Comment by nik9000** [comment]
> Could the plugin have failed to install (after I gave it permissions) and it said it succeeded?

Bugs are bugs and windows doesn't get nearly as much testing as linux but we do test this stuff.

For what it is worth I tested locally (on macOS) and it worked:
```
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.0-rc1.tar.gz
tar xf elasticsearch-5.0.0-rc1.tar.gz 
cd elasticsearch-5.0.0-rc1
./bin/elasticsearch 
```
and then
```
curl -XPUT 'localhost:9200/my_index?pretty' -d'
{
  "mappings": {
    "my_type": {
      "_size": {
        "enabled": true
      }
    }
  }
}'
```
which worked fine. Can you see if the plugin is installed with `curl localhost:9200/_cat/plugins`?

It'd take me a few hours to set up a local windows machine for testing.

**Comment by niemyjski** [comment]
I can but I don't know if I can get it in the same state. It's installed now. I guess I can uninstall and reboot and try again

**Comment by dadoonet** [comment]
From 2.x _size is now a plugin.

Read https://www.elastic.co/guide/en/elasticsearch/plugins/current/mapper-size.html <https://www.elastic.co/guide/en/elasticsearch/plugins/current/mapper-size.html>

**Comment by niemyjski** [comment]
Yeah, I wasn't able to reproduce, there was some kind of installer issue that I can no longer reproduce.
