### ISSUE TITLE
Painless internal: rename `isDefOptimized` to `canBeDefOptimized`

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#21074]
`isDefOptimized` implies that returning `true` means that the node has already been optimized. But returning `true` actually means that it **can** be optimized.

**Comment by Jordanwmk** [comment]
Hi, I'm new to OSS but I would like to have a go at resolving this issue. Whereabouts is this variable stored? Has the new variable name been finalized to 'canBeDefOptimized'?

**Comment by nik9000** [comment]
Honestly I filed this a while back when I was first learning lang-painless's internals so I'm not sure that it is valid. I marked it as `discuss` because I really wasn't sure if it was right. @jdconrad, can you talk about this some?

This is the code I'm talking about: https://github.com/elastic/elasticsearch/blob/master/modules/lang-painless/src/main/java/org/elasticsearch/painless/node/AStoreable.java#L78-L82

**Comment by jdconrad** [comment]
@nik9000 is right, canBeDefOptimized makes more sense.

**Comment by jdconrad** [comment]
This isn't going to change.  Closing.
