### ISSUE TITLE
[feature request]make cache expand expand-copy-close way?

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#21086]
**Describe the feature**:
currently we I expand(enlarge the memory) filter cache, the action is to close th old one and build a new one, which will cause previously cache completely removed.
can it be made to expand-copy-close way?

**Comment by jpountz** [comment]
Actually we removed the ability to resize the filter cache has been removed for quite some time now. Like you noticed it had the bad side effect of clearing the cache. It was also quite a tricky operation in terms of concurrency: the implementation was not 100% correct, which could lead to memory leaks in some rare cases. So we decided to not offer the ability to resize the filter cache live when we switched to a new cache. This new requires nodes to be restarted.

**Comment by makeyang** [comment]
@jpountz  any plan to make new cache dynamicly resize?

**Comment by jpountz** [comment]
No. Resizing the filter cache correctly would be hard to get right and on the other hand, resizing the cache should be a rare operation so when we discussed it we concluded it was fair to require a node restart to change the cache size.
