### ISSUE TITLE
[DOCS] Document index.gc_deletes Setting

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#21095]
Currently the only place that you can learn about `index.gc_deletes` is the old [Versioning Support blog post](https://www.elastic.co/blog/elasticsearch-versioning-support) (at the bottom).

**Comment by agirbal** [comment]
+1
Would like to hear about caveats too - does it persist upon shard relocation, node restart, etc.
Typical question: I've got a queue with updates that may not be ordered, i.e. an update to a doc might come after a delete which has a higher version number. Can I rely on this automatic feature of ES to prevent the doc from being reinserted? Or is this feature purely for internal ES hygiene?

**Comment by bleskes** [comment]
> Can I rely on this automatic feature of ES to prevent the doc from being reinserted?

Yes you can, but you need to guarantee that gc.deletes is comfortably higher than the time between processing the delete command and the index one, including things like GC and such.

**Comment by rjernst** [comment]
@bleskes Is this still something that should be documented? If so, can you do so, or assign to someone who knows enough about this setting (the javadocs in code don't tell me enough to know how to explain it).

**Comment by bleskes** [comment]
Good question. I'll bring it up for discussion. Thanks for the ping.

**Comment by DaveCTurner** [comment]
Relates #28781.

**Comment by DaveCTurner** [comment]
Closed by #28781.
