### ISSUE TITLE
Get index returns index.provided_name but is unknown on creation

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch#21096]
**Elasticsearch version**: 5.0.0-rc1

`index.provided.name` is added automatically to a newly created index:

`PUT /foo`

`GET /foo`
```json
{
  "foo" : {
    "aliases" : { },
    "mappings" : { },
    "settings" : {
      "index" : {
        "creation_date" : "1477329094025",
        "number_of_shards" : "5",
        "number_of_replicas" : "1",
        "uuid" : "2ysmQ0_9QrumHvHgQyri8A",
        "version" : {
          "created" : "5000099"
        },
        "provided_name" : "foo"
      }
    }
  }
}

```

However, if this setting is passed when creating an index, ES fails with:

```json
{
	"error": {
		"root_cause": [{
			"type": "illegal_argument_exception",
			"reason": "unknown setting [index.provided_name] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
		}],
		"type": "illegal_argument_exception",
		"reason": "unknown setting [index.provided_name] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
	},
	"status": 400
}
```

Seems to me that if this setting has been removed, then it shouldn't be added/returned.  Or, it is a valid setting and there is a flaw in the settings validation.  I ran into this while testing our client-side reindex helper, which uses existing index settings to create a new index.

**Comment by s1monw** [comment]
this works as expected. You can't set `index.version.created` either and you will get the same exception. `index.provided_name` is a private setting that is set internally if you create an index with a date math pattern for instance. You can't just copy settings over with 5.0 they are validated and there are several that you can set from the outside.
