### ISSUE TITLE
Build a histogram based on the doc_count field of a Terms Aggregation

### ISSUE THREAD

**Issue by MarcAragones** [elastic/elasticsearch#21106]
## Describe the feature

Build a histogram based on the `doc_count` field of a Terms Aggregation.
## Example

Imagine we have the names of some cities and their streets:

``` json
{ "city":"New York",      "street":"Atlantic Avenue" }
{ "city":"New York",      "street":"Hudson Street" }
{ "city":"New York",      "street":"Fawn Court" }
{ "city":"Boston",        "street":"Atlantic Avenue" }
{ "city":"Boston",        "street":"Hudson Street" }
{ "city":"Boston",        "street":"7th Avenue" }
{ "city":"Washington DC", "street":"Atlantic Avenue" }
{ "city":"Washington DC", "street":"Dogwood Drive" }
{ "city":"Washington DC", "street":"7th Avenue" }
```

If we count each time that a street appears (this would be the **Terms Aggregation**), we will get the following:

```
| Street name     | Number of times |
|-----------------|-----------------|
| Atlantic Avenue |               3 |
| Hudson Street   |               2 |
| 7th Avenue      |               2 |
| Hudson Street   |               1 |
| Dogwood Drive   |               1 |
```

Now, the feature would have to build a histogram that says how many street names are unique, how many are seen in two cities, and so on...

To do so, we should get the result of a **Terms Aggregation** and send it to a **Histogram Aggregation**.

Here is the result for the example above:

```
| Street name count | Number of times |
|-------------------|-----------------|
|                 1 |               2 |
|                 2 |               2 |
|                 3 |               1 |
```
### What could be done

The first table is build with the results of the following aggregation:

``` bash
curl -XGET 'http://localhost:9200/index1/type1/_search?pretty' -d '
{
  "size": 0,
  "aggs": {
    "group_by_street": {
      "terms": {
        "field": "street"
      }
    }
  }
}'
```

Then, if we add the histogram, it could be something like this:

``` bash
curl -XGET 'http://localhost:9200/index1/type1/_search?pretty' -d '
{
  "size": 0,
  "aggs": {
    "histogram_streets": {
      "histogram": {
        "field": "group_by_street>_count",
        "interval": 1
      },
      "aggs": {
        "group_by_street": {
          "terms": {
            "field": "street"
          }
        }
      }
    }
  }
}'
```

**Comment by clintongormley** [comment]
> If we count each time that a street appears (this would be the Terms Aggregation), we will get the following:

You wouldn't actually.  Each street would be unique, because you're not taking city into account in your aggs.

Honestly, I'm not seeing the common use case for the example you provide.  I'll leave this open for now to see if others disagree.

**Comment by zengfulongit** [comment]
I have a similar question : build a histogram based on the doc_count field of a Terms Aggregation.
Imagine we have a user access log
```
{"user":"Andy"}
{"user":"Biff"}
{"user":"Chip"}
{"user":"Andy"}
{"user":"Biff"}
{"user":"Kipper"}
{"user":"Chip"}
{"user":"Kipper"}
{"user":"Kipper"}
{"user":"Chip"}
{"user":"Chip"}
{"user":"Floppy"}
```

we count each time that user access
```
| User name     | Number of times |
|---------------|-----------------|
| Andy          |               2 |
| Biff          |               2 |
| Chip          |               3 |
| Kipper        |               3 |
| Floppy        |               1 |
```

Now, the feature would have to build a histogram that says unique user access times distribution...
```
| User name count | Number of times |
|-----------------|-----------------|
| 1               |               1 |
| 2               |               2 |
| 3               |               2 |
```

**Comment by polyfractal** [comment]
Hey all.  This feature request is an interesting idea but since its opening we have not seen enough feedback that it is a feature we should pursue. We prefer to close this issue as a clear indication that we are not going to work on this at this time. 

We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).

If we do pursue this in the future, it would make sense to implement it as a pipeline aggregation rather than a regular aggregation.
