### ISSUE TITLE
3ES node cluster restart ERROR failed to build store metadata . checking segment info integrity (with commit no)

### ISSUE THREAD

**Issue by aderm** [elastic/elasticsearch#21110]
Elasticsearch version: 1.4.4

JVM version: 1.7.0_06

OS version: SUSE11 sp3

We received the following error message in the logs
[WARN ][index.store              ] [node_65174] failed to open / find files while reading metadata snapshot
[WARN ][index.store              ] [node_65174] [dpspingan_2016][3]failed to build store metadata. checking segment info integrity (with commit [no])
....
FileNotFoundException: No such file[_3jc_es090_0.pos]

**Comment by jasontedor** [comment]
Elasticsearch 1.4.4 is end-of-life and no longer supported.
