### ISSUE TITLE
Painless doesn't support `d` for double constants

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#21116]
Painless looks to support `f` for floating point constants but doesn't support `d`. Should it? It isn't really required because all decimal constants are by default doubles but I find myself writing it from time to time because I want to be explicit.

**Comment by jdconrad** [comment]
I just never added it because it was redundant as you said.  It works for ints right now, but we can add it for decimal value too.

**Comment by nik9000** [comment]
> I just never added it because it was redundant as you said. It works for ints right now, but we can add it for decimal value too.

If you are ok with it I can open a PR for it when I get time. It isn't difficult, I think. I like the compatibility with java that it adds, though it might only be me that benefits from it.

**Comment by jdconrad** [comment]
Sure, I agree that this one should be pretty simple.
