### ISSUE TITLE
Plain highlighter should not analyze documents when the extracted query terms are empty

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#21112]
For instance for this query:

```
GET _search
{
   "size": 100,
   "highlight": {
      "fields": {
         "*": {}
      },
      "fragment_size": 0
   },
   "query": {
        "match_all": {}
   }
}
```

... we should be able to bypass the highlighter since there is no term to match. Currently all the fields are retrieved and analyzed to find an hypothetical match.

**Comment by jimczi** [comment]
cc @elastic/es-search-aggs

**Comment by mayya-sharipova** [comment]
Closing this issue, as we would like users to use `unified` highlighter, and in time deprecate `plain` highlighter.
