### ISSUE TITLE
Index data is wiped after upgrading from 5.0.0-alpha to 5.0.0-rc1

### ISSUE THREAD

**Issue by liweinan0423** [elastic/elasticsearch#21111]
I have a data folder which contains 29GB data, after upgrading from 5.0.0-alpha to 5.0.0-rc1, the data folder became 14M. The index names are still in, but all data in the indices are gone.

**Comment by clintongormley** [comment]
Hi @liweinan0423 

Sorry you lost your data, but there are notices on the blog posts and release notes saying that upgrading the alphas to any other version is not supported, eg https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-5.0.0-alpha1.html
