### ISSUE TITLE
Bulk mappings import

### ISSUE THREAD

**Issue by nickstenning** [elastic/elasticsearch#2112]
At the moment, I can `GET /index/_mapping` and get a list of all type mappings for a given index.

It would be nice if I could `PUT /index/_mapping` with the same format to bulk update mappings.

I'm aware I can also specify a "mappings" key at index creation time, but hosted services such as [Bonsai](//bonsai.io) don't allow me to create and delete indices, so having this "symmetric" API call would be very handy.

**Comment by clintongormley** [comment]
Given that this issue has had no further comments in the last 4 years, I'm going to close it
