### ISSUE TITLE
[feature request]smart search shard selector according to data allocation

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#21128]
**Describe the feature**:
let's say I have 3 data nodes and one index with 3 primary shard and 2 replica. so each data node holds complete dataset. if it possible to and a switcher and make each search request to route to one node according to this data allocation and save network tranport time

**Comment by cbuescher** [comment]
I might miss something, but isn't this what `"preference" : "_local"` does (https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-preference.html)?

**Comment by makeyang** [comment]
o, yes. thank very much.
