### ISSUE TITLE
Some endpoints return Content-Length: 0 for HEAD requests

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#21125]
After #21123 when Elasticsearch receive a HEAD request it returns the Content-Length of the that it would return for a GET request with an empty response body. Except in the document exists, index exists, and type exists requests which return 0. We should fix them to also return the Content-Length that would be in the response.

**Comment by jasontedor** [comment]
I'm adding the v5.1.0 label too, I think we should target a fix there.

**Comment by jasontedor** [comment]
These are all addresses now. Closing.
