### ISSUE TITLE
Search context is not cleaned when scroll search is cancelled

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#21126]
Cancelling search with scroll can leave some search contexts behind. See test failure in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu/160/console

**Comment by nik9000** [comment]
😢

**Comment by imotov** [comment]
I think I found the reason for the failure in these tests, but we need changes from #20767 to properly fix it.

**Comment by nik9000** [comment]
I'll get to it! I've got something **so** close to ready for review that I'd like to finish off first then I'll address your comments in #20767.
