### ISSUE TITLE
[doc request]list all default values for meta-field

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#21127]
**Describe the feature**:
otherwise, it cause misunderstanding

**Comment by javanna** [comment]
Hi @makeyang can you elaborate please? What issues have you experienced?

**Comment by makeyang** [comment]
@javanna  
take this page as example: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/mapping-all-field.html
in this page, I don't know if _all is enable or disable by default. I don't know it's what its defalut index options are.
the other pages describe meta field has the same issue.
so better to list them at the front or end of the page

**Comment by Sue-Gallagher** [comment]
Fixed per Deb Adair 3/20/2018
