### ISSUE TITLE
Upgrading from 5.0.0-rc1 to stable might be broken on Debian

### ISSUE THREAD

**Issue by jlecour** [elastic/elasticsearch#21139]
Hi,

I'm not 100% sure about that but there might be an issue for Debian users who have already installed a beta/rc version.

On a Debian 8.6, I've been using the "prerelease" source list, and I've installed Elasticsearch, Logstash and Kibana (`5.0.0-rc1`).

An hour ago, after the 5.0.0 GA announcement, I've changed my source list to the "normal" repository URL, did an `apt update` and `apt upgrade`.

Only Logstash was available for upgrade.

In the packages list for the "elastic" source list, the packages were all present, but a version number issue was preventing APT to consider them as newer versions.

I did `apt remove elasticsearch kibana && apt install elasticsearch kibana` then I got the correct (latest) versions.

**Comment by rjernst** [comment]
This is indeed a bug, and I'm sorry it has taken so long to get a fix. The problem was with the underlying library used for building the deb package. I've opened #29000 to fix this, which will apply for 7.0 prerelease versions when they are released.
