### ISSUE TITLE
execution mode in range filter in ES 2.4

### ISSUE THREAD

**Issue by amitranjan-fk** [elastic/elasticsearch#21148]
**Elasticsearch version**: 2.4.1

**Plugins installed**: hq

**JVM version**: 1.8.0_05

**OS version**: Debian  7.11

**Description of the problem including expected versus actual behavior**:
Template execution fails with error "[range] query does not support [execution]" if `execution` mode is specified in the `range` filter inside `bool`  query.

What is the default mode of execution in ES 2.x for range queries ?

**Comment by jpountz** [comment]
The `range` option has been removed, range queries now always use the index for their execution. The previous `fielddata` option had the drowback that it could end up doing a linear scan if other parts of the query were not selective enough.

Also consider upgrading to 5.0, which has faster range support: https://www.elastic.co/blog/searching-numb3rs-in-5.0
