### ISSUE TITLE
Add version 5.0.0 to Maven repository

### ISSUE THREAD

**Issue by aadu** [elastic/elasticsearch#21140]
**Describe the feature**:
Add elasticsearch 5.0.0 to [maven repository](https://mvnrepository.com/artifact/org.elasticsearch/elasticsearch). I have a 5.0.0-rc1 compatible build of a discovery plugin that fails on the GA v5.0.0 install because plugins require exact version compatibility.

**Comment by jasontedor** [comment]
You can obtain Elasticsearch via the coordinates:

```
<dependency>
    <groupId>org.elasticsearch</groupId>
    <artifactId>elasticsearch</artifactId>
    <version>5.0.0</version>
</dependency>
```

I do not know what Mvn Repository is, it looks like it just indexes Maven coordinates from elsewhere and we are not going to go out of our way to be affiliated with a site like that (especially when we already have officially-hosted repositories).
