### ISSUE TITLE
Rollover API: indicate failure in dry run if an index already exists

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#21149]
**Elasticsearch version**: 5.0.0

**Description of the problem including expected versus actual behavior**:
When executing `_rollover?dry_run`, check for the existence of `new_index` and indicate if a rollover is expected to succeed or fail according to known conditions at execution time.

**Steps to reproduce**:
1. Setup an index for rollover
2. Create an empty index having a name matching the next `new_index` after rollover
3. Execute `_rollover?dry_run`.
4. Execute `_rollover`.

```
GET packetbeat/_aliases
{
  "packetbeat-000004": {
    "aliases": {
      "packetbeat": {}
    }
  }
}
```

```
PUT packetbeat-000005
{
  "acknowledged": true,
  "shards_acknowledged": true
}
```

Normally this is a 7 day rollover. Set it to 0 day (or remove the condition entirely) to just execute it:

```
POST packetbeat/_rollover?dry_run
{
  "conditions": {
    "max_age": "0d"
  }
}

{
  "old_index": "packetbeat-000004",
  "new_index": "packetbeat-000005",
  "rolled_over": false,
  "dry_run": true,
  "acknowledged": false,
  "shards_acknowledged": false,
  "conditions": {
    "[max_age: 0s]": true
  }
}
```

I would have expected the dry run to indicate failure.

The actual rollover fails as expected:

```
POST packetbeat/_rollover
{
  "conditions": {
    "max_age": "0d"
  }
}

{
  "error": {
    "root_cause": [
      {
        "type": "index_already_exists_exception",
        "reason": "index [packetbeat-000005/0FDcEuIQTh6lVvD-l7lkxg] already exists",
        "index_uuid": "0FDcEuIQTh6lVvD-l7lkxg",
        "index": "packetbeat-000005"
      }
    ],
    "type": "index_already_exists_exception",
    "reason": "index [packetbeat-000005/0FDcEuIQTh6lVvD-l7lkxg] already exists",
    "index_uuid": "0FDcEuIQTh6lVvD-l7lkxg",
    "index": "packetbeat-000005"
  },
  "status": 400
}
```

**Comment by s1monw** [comment]
I agree we should try to throw the same exception with `dry_run=true`
