### ISSUE TITLE
Update mapper-attachment in ES2.4  use tika 1.13

### ISSUE THREAD

**Issue by SKumarMN** [elastic/elasticsearch#21166]
*_Elasticsearch version_2.4*:

**Plugins installed**: [mapper_attachments]

**JVM version**: 1.8

**OS version**: Win 7

Mapper-attachments plugin is currently using tika 1.11 and there are various fixes that are made in tika 1.13. In ES 5.0 ingest-attachment, I see tika 1.13 is being used. 

Update mapper-attachment in ES2.4  use tika 1.13 which reduces quite some parsing errors found in tika 1.11

**Comment by nik9000** [comment]
I'm not sure we want to bump the version of a dependency in a patch release. I mean, maybe it is safe but in general it seems scary. And I don't think we'll release another major release of 2.x.

**Comment by dadoonet** [comment]
I'm just wondering if we consider this as a bug or not. If not, I agree we won't fix it

**Comment by clintongormley** [comment]
Agree with @nik9000 - too risky, and 5.0.0 is out already.  Closing as won't fix

**Comment by clintongormley** [comment]
Agree with @nik9000 - too risky, and 5.0.0 is out already.  Closing as won't fix
