### ISSUE TITLE
Add Explicit Multi & PhraseQuery support to REST & Java API

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#2118]
currently I don't see explicit support for MultiPhraseQuery in ElasticSearch. It would be interesting to be able to combine PhraseQuery with fuzzy terms especially with Lucene 4.0 coming up.

**Comment by jpountz** [comment]
@s1monw Do you mean we should have a dedicated "phrase" query in addition to the match phrase query?

**Comment by clintongormley** [comment]
@s1monw do you still want this?

**Comment by clintongormley** [comment]
Chatted to @s1monw who said no, so closing
