### ISSUE TITLE
Should stored scripts and ingest node configurations be included into a snapshot?

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#21184]
In 5.0 stored scripts were moved from a special index to the cluster state and therefore they can no longer be stored as part of a snapshot. In the snapshot/restore API we have an option to "include global cluster state" into snapshot or restore operations, which currently translates into storing or restoring index templates and persistent settings as a part of a snapshot/restore operation. It seems logical to expand the definition of the "global cluster state" to also include stored scripts and ingest node pipelines.

**Comment by e-mars** [comment]
+ adding myself

**Comment by talevy** [comment]
+1
