### ISSUE TITLE
using date math for index names requires url encoded /

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#21181]
**Elasticsearch version**: 5.0

**Description of the problem including expected versus actual behavior**:
The docs for using date math for index names, such as [rollover API](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/indices-rollover-index.html#_using_date_math_with_the_rolllover_api) mention using an unencoded `/` like this:

```
<logs-{now/d}-1>
```

This does not work and requires a url encoded `/` (`%2F`):

```
<logs-{now%2Fd}-1>
```

Like the docs:

```
PUT <logs-{now/d}-1>
No handler found for uri [/%3Clogs-%7Bnow/d%7D-1%3E] and method [PUT]
```

url encoded:

```
PUT <logs-{now%2Fd}-1>
{
  "acknowledged": true,
  "shards_acknowledged": true
}
```

```
GET <logs-{now%2Fd}-1>
{
  "logs-2016.10.28-1": {
    "aliases": {},
    "mappings": {},
    "settings": {
      "index": {
        "creation_date": "1477686788578",
        "number_of_shards": "1",
        "number_of_replicas": "1",
        "uuid": "Ci2YP1ixRUumJonM_-UCWw",
        "version": {
          "created": "5000099"
        },
        "provided_name": "<logs-{now/d}-1>"
      }
    }
  }
}
```

Should the docs be updated or should the requirement for url encoded `/` be removed?

**Comment by s1monw** [comment]
looks pretty ugly but I guess it's the way to go, I wonder what @clintongormley thinks

**Comment by javanna** [comment]
This was previously discussed a few times. For instance in #14216 and #16256. Docs need to be updated. We can't remove this requirement, slashes that are not path separators must be escaped.
