### ISSUE TITLE
DateMath with `M` (months) seems to be buggy 

### ISSUE THREAD

**Issue by Hexer338** [elastic/elasticsearch#21199]
**Elasticsearch version**: 5.0.0-rc1

**Plugins installed**: [murmur3]

**JVM version**: openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-8u102-b14.1-1~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.102-b14, mixed mode)

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:
DateMath using `now` and `M`(months) is not returning expected results .

**Steps to reproduce**:
**Example 1:**
 1.  Create an index with current date
    ```
    PUT index/type/1
    {
        "time": "2016-10-31T11:31:31"
    }
    ```

 2. The following queries return different results:
    ```
    # First Query:
    GET index/_search
    {
        "query": {
            "bool": {
                "must": [
                   {
                       "range": {
                          "time": {
                             "lte": "now+M-M"
                          }
                       }
                   }
                ]
            }
        }
    }

    # Second Query:
    GET index/_search
    {
        "query": {
            "bool": {
                "must": [
                   {
                       "range": {
                          "time": {
                             "lte": "now"
                          }
                       }
                   }
                ]
            }
        }
    }
    ```

 3. The first query returns empty hits while the second query returns the document. This issue seems to be happening only with `M` (months) in the dateMath.

**Example2:**
 1. These two queries also return different results for above dataset.
    ```
    # First Query:
    {
       "query": {
          "bool": {
             "must": [
                {
                   "range": {
                      "time": {
                         "gte": "now+330m/M-330m",
                         "lt": "now+330m/M+M-330m"
                      }
                   }
                }
             ]
          }
       }
    }

    # Second Query:
    {
       "query": {
          "bool": {
             "must": [
                {
                   "range": {
                      "time": {
                         "gte": "now+330m/M-330m",
                         "lt": "now+330m/M-330m+M"
                      }
                   }
                }
             ]
          }
       }
    }
    ```

 2. The first query returns result and second query returns empty hits. Note that in second query only `+M-330m` is replaced with `-330m+M`.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jasontedor** [comment]
This is due to the fact that month isn't a fixed unit of measure (months have 28, 29, 30, or 31 days (and let's ignore the fact that day isn't a fixed unit of measure either)), combined with how JodaTime handles this oddity and how the date math parser does not simplify expressions (i.e., it does not reduce `now+M-M` to `now` before evaluating it). From the [JodaTime docs](http://www.joda.org/joda-time/apidocs/) for `DateTime#plusMonths`:

> The calculation will do its best to only change the month field retaining the same day of month. However, in certain circumstances, it may be necessary to alter smaller fields. For example, 2007-03-31 plus one month cannot result in 2007-04-31, so the day of month is adjusted to 2007-04-30.

In particular, adding a month to 2016-10-31 will take you to 2016-11-30 (ignoring time, but note that  there is a DST transition there depending on the timezone), and then subtracting a month will take you back to 2016-10-30. This explains the issue that you're seeing.
