### ISSUE TITLE
Add a way for a plugin to share data with its running instances on different nodes

### ISSUE THREAD

**Issue by Branor** [elastic/elasticsearch#21193]
I maintain the Couchbase transport plugin, which relied on the server attributes collection in the `NodeInfo` class as a way for every plugin instance to discover which other nodes are running the plugin and which address each one is bound to. This collection, as well as the get/put methods in `NodeService` were removed in the following commit: https://github.com/elastic/elasticsearch/commit/dbbfadeefaffa71c46a7640437524779be611bcb#diff-58b020797e31e6c490011454f2fa6106

Admittedly, it wasn't a very good way to implement that functionality to begin with. Is there an alternative way for a plugin to share custom metadata that's specific to each running plugin instance? 
NodeInfo has a list of plugins and modules, but I can't find a way to set and retrieve custom data/attributes on a per-node basis. It can't be in some configuration/global store because at runtime the plugin needs responses only from the nodes that are actually part of the cluster at that time.

**Comment by rjernst** [comment]
I think the way to do this would be for the plugin to add custom cluster state. How often is this info from each node updated?

**Comment by rjernst** [comment]
Another possibility is #20824

**Comment by dadoonet** [comment]
May be you can also in such a case create an index named `.couchbase` and simply store whatever you want in it?
Then a plugin could write in it the very first time the plugin is started in the cluster.
Other plugin instances (running on other nodes) could read whatever document you have in it.

I have been using such a strategy when I was creating now removed river plugins.

Would that work for you?

**Comment by clintongormley** [comment]
No further feedback. Closing
