### ISSUE TITLE
Duplicate `timeout` parameter in ES 5.0 REST API spec of `update_by_query.json`

### ISSUE THREAD

**Issue by olivere** [elastic/elasticsearch#21195]
There are two different definitions of the `timeout` parameter in [`update_by_query.json`](https://github.com/elastic/elasticsearch/blob/5.0/rest-api-spec/src/main/resources/rest-api-spec/api/update_by_query.json):

```json
...
"timeout": {
  "type" : "time",
  "description" : "Explicit operation timeout"
},
...
"timeout": {
  "type" : "time",
  "default": "1m",
  "description" : "Time each individual bulk request should wait for shards that are unavailable."
},
...
```

**Comment by nik9000** [comment]
We've already fixed it but the fix didn't make it into 5.0: #20934. I've poked the fix's author to ask him to backport to the 5.0 branch so it makes it whenever we cut a 5.0.1.
