### ISSUE TITLE
Storing search templates in cluster state - broken docs or code?

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#21202]
Trying the advice from [our latest docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-template.html#pre-registered-templates) where we can store search templates using this command: 

    POST /_search/template/<templatename>

this produces this error on the latest master 

	{
	   "error": {
		  "root_cause": [
			 {
				"type": "invalid_index_name_exception",
				"reason": "Invalid index name [_search], must not start with '_', '-', or '+'",
				"index_uuid": "_na_",
				"index": "_search"
			 }
		  ],
		  "type": "invalid_index_name_exception",
		  "reason": "Invalid index name [_search], must not start with '_', '-', or '+'",
		  "index_uuid": "_na_",
		  "index": "_search"
	   },
	   "status": 400
	}

Either we have a bug or the docs haven't been updated with changes to the code. This command works OK in 5.0

**Comment by dakrone** [comment]
Hmm... It looks like it *is* registered, see:

https://github.com/elastic/elasticsearch/blob/1f5adaa82472d21ba2811a9d62e46eaf168016fc/modules/lang-mustache/src/main/java/org/elasticsearch/script/mustache/RestPutSearchTemplateAction.java#L35

Seems like an actual bug, but I tried to reproduce this on the `master` branch with:

```json
POST /_search/template/flabergaz
{
  "template": {
    "query": {
      "match": {
        "title": "{{query_string}}"
      }
    }
  }
}
```

And it works fine, what request are you trying?

**Comment by markharwood** [comment]
>And it works fine, what request are you trying?

Running master as of this morning but running inside eclipse so that may be relevant:  with xpack, security and monitoring disabled.

	POST /_search/template/mytemplate 
	{
		"template":{
		  "query": {
			 "bool": {
				"must": [
				   {
					  "term": {
						 "myField": "{{post}}"
					  }
				   }
				]
			 }
		  }
		}
	}

**Comment by dakrone** [comment]
@markharwood that example works just fine for me on master (using `gradle run` to run ES). I think this might be a problem with running ES inside of Eclipse, I believe @colings86 was having problems similar to this when running in Eclipse also.

**Comment by markharwood** [comment]
OK - I'll close. I think this is the first time I've come across an issue with the eclipse behaviour so will bear in mind in future.
Sorry for the noise and thanks for testing!
