### ISSUE TITLE
5.0 doc page mentions Groovy as the default scripting language

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#21208]
The [Painless doc](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/modules-scripting-painless.html) for 5.0 states:
>Painless is a simple, secure scripting language available in Elasticsearch by default. It is designed specifically for use with Elasticsearch and can safely be used with inline and stored scripting, which is enabled by default.

[Groovy Scripting Language](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/modules-scripting-groovy.html): 

>Groovy is the default scripting language available in Elasticsearch. Although limited by the Java Security Manager, it is not a sandboxed language and only file scripts may be used by default.

**Comment by nik9000** [comment]
Indeed, groovy is no longer the default. Would you like to open a PR to fix it or should I?
