### ISSUE TITLE
_missing_ is missing?

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#21226]
`_missing_` doesn't appear to have made it into 5.0 (it's in the [2.4 docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html)), but it's not in the [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_search_changes.html).

Was this removed?

**Comment by biyuhao** [comment]
AFAIK it's deprecated in 5.0, but I don't know why it's not in the breaking changes.
See #15153

**Comment by clintongormley** [comment]
this was deprecated in 2.2: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-missing-query.html

I've added it to the breaking changes for 5.0
