### ISSUE TITLE
Packaging for systemd unit file and ES_USER

### ISSUE THREAD

**Issue by martinb3** [elastic/elasticsearch#21231]
Howdy! I'm not sure if this really a bug or a feature, but it's a packaging request. In short, we respect a lot of environment variables in the systemd packaging for the v5.0.0 release:

```
[Service]
Environment=ES_HOME=/usr/share/elasticsearch
Environment=CONF_DIR=/etc/elasticsearch
Environment=DATA_DIR=/var/lib/elasticsearch
Environment=LOG_DIR=/var/log/elasticsearch
Environment=PID_DIR=/var/run/elasticsearch
EnvironmentFile=-/etc/sysconfig/elasticsearch
```

But then we ignore ES_USER and ES_GROUP:
```
User=elasticsearch
Group=elasticsearch
```

Maybe the intention is to deprecate `ES_USER` and `ES_GROUP` from being the correct way to run Elasticsearch, but we should probably respect those env vars in systemd or stop respecting them in sys-v init systems.

I'm maintaining the Chef cookbook for Elasticsearch, and I'm trying to avoid hacking up the systemd unit file just to allow users to override the user and group like they can already with the init script.

Thanks in advance!

**Comment by tlrx** [comment]
Yes, as of today it's not possible to use environment variable to define systemd `User` and `Group`. 

But I think that `ES_USER` and `ES_GROUP` are still valuable, I'm not sure we should stop respecting them in sysv-init scripts because it would force people to edit them directly in init.d scripts which is not the usual way to go. I think we are aligned with usual practices here, both for sysv-init scripts and systemd scripts. We could potentially detect a misconfiguration in systemd configuration, like `ES_USER=foo` in environment file and `User=bar` in systemd file in a kind-of `ExecPreStart` script.

**Comment by martinb3** [comment]
👍 maybe a warning in the existing ExecPreStart script is the right step. FWIW, I was working on a system where I was using a custom /etc/default/elasticsearch, so I never noticed the new package does install this warning in the envfile:

```
             -# SysV init.d
             -#
             -# When executing the init script, this user will be used to run the elasticsearch service.
             -# The default value is 'elasticsearch' and is declared in the init.d file.
             -# Note that this setting is only used by the init script. If changed, make sure that
             -# the configured user can read and write into the data, work, plugins and log directories.
             -# For systemd service, the user is usually configured in file /usr/lib/systemd/system/elasticsearch.service
             -#ES_USER=elasticsearch
             -#ES_GROUP=elasticsearch
```

Maybe that's adequate; I just didn't notice it since I already had one.

**Comment by jasontedor** [comment]
We are going to remove support for customizing the user/group. The packaging distributions will ship with elasticsearch/elasticsearch as the user/group. We are going to rely on the configuration management solutions or point users to customizing the archive distribution if they want to run with non-default user/group.
