### ISSUE TITLE
Painless should have a "practical examples" page

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#21238]
Painless should have a "practical examples" page (or pages) in the docs where we do things like give an example of using painless with script fields or updating documents with painless. We already have a section in the main painless page called "updating fields with painless" but I think we should grow a bunch more of these sections and they'll get long.

**Comment by nik9000** [comment]
In particular, using null safe dereferences (#21239) with script_fields is a bit fiddly because if the field totally doesn't exist then we throw an error rather than return null. That is the right thing for us to do, but it is a thing we should point out in a section about using painless for script_fields.

**Comment by markharwood** [comment]
As for practical examples, I just revisited my old Groovy-based demo for entity-centric indexing and converted it to use Painless. Example data and script tested with 5.2.2 is [here](http://bit.ly/entcent_painless):

**Comment by yehosef** [comment]
This would really be helpful for date functions - I'm trying to create an iso8601 date from a timestamp and it's a little confusing.

**Comment by debadair** [comment]
[docs issue triage]

More Painless examples have been added in various ways since this issue was opened. Closing in favor of opening targeted issues for additional types of examples.
