### ISSUE TITLE
Conditional pipeline processors

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#21248]
I wish there was a way to do some very basic conditional pipeline actions without going straight to scripts. For example, run this pipeline only if this field exists. I don't want to have to specify a failure action when a field doesn't exist....

```cs
            var response = await Configuration.Client.PutPipelineAsync(Pipeline, d => d
                .Processors(p => p
                    .Lowercase<Employee>(l => l.Field(f => f.Name))
                    .Trim<Employee>(t => t.Field(f => f.Name))
                ).OnFailure(of => of.Set<Employee>(s => s.Field(f => f.Name).Value(String.Empty))));
```

**Comment by clintongormley** [comment]
@niemyjski have you seen the `ignore_missing` parameter? https://www.elastic.co/guide/en/elasticsearch/reference/current/lowercase-processor.html

**Comment by niemyjski** [comment]
I didn't see that, and will take a look into it, but it still would be super nice to be able to some basic stuff like maybe check if a value was specified and if it doesn't specify defaults or run different processors on the field.

**Comment by nicholasyin** [comment]
Why wasn't this property added to every type of processor?
