### ISSUE TITLE
Feature Request: composable pipelines

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#21247]
I think it would be super useful to be able to specify multiple pipelines that should run. It would also simplify your code and testing if we did this as we could compose multiple pipelines that should run. For example I could have the following pipelines get run: `ensure-id-pipeline,format-name-pipeline` and then I just keep on reusing them, then when something doesn't work I can go look at that specific pipeline. Thoughts?

**Comment by clintongormley** [comment]
One possibility we've considered is making pipelines composable, so you can create a pipeline which calls other pipelines.  Which would be your preference?  Specifying them inline as per your example or composability?

**Comment by niemyjski** [comment]
I think both should be supported. I see a use case for both methods.

**Comment by wasserman** [comment]
I vote for inline.  This should be simpler to implement and easier for users to manage.  It is a better alternative to building many similar pipelines via copy/paste.  Hopefully this feature would also be more efficient than running smaller pipelines serially.   Composable pipelines are more likely to allow for complicated designs that are difficult to troubleshoot and could result in pipeline cycles through nesting or recursion.

**Comment by talevy** [comment]
Closing since the complexity of this outweighs the benefits and the existing solution of copying functionality
