### ISSUE TITLE
Rank evaluation: We should allow for more than one template to be specified

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#21257]
Problem: We introduced the ability to shorten the rank eval request by using a template in #20231. When playing with the API it turned out that there might be use cases where - e.g. due to various heuristics - folks might want to translate the original user query into more than just one type of Elasticsearch query.

Proposed solution: Give each template an id that can later be referenced in the actual requests like so:

    GET /index/type/_rank_eval/template
    {
        "templates": [
            "template": {
                "inline": "string that constitutes a search request template",
                "id": "human_readable_name"
            }],
        "requests": [{
            "id": "human_readable_id",
            "params": { ... params to the request to check ... },
            "template_id": "human_readable_name",
            "ratings": { ... mapping from doc id to rating value ... }
         }],
        "metric": {
            "... metric_name... ": {
                "... metric_parameter_key ...": ...metric_parameter_value...
            }
        }
      }

**Comment by MaineC** [comment]
@cbuescher I think at some point we briefly talked about this, but never actually tracked it in an issue.

**Comment by jpountz** [comment]
> there might be use cases where - e.g. due to various heuristics - folks might want to translate the original user query into more than just one type of Elasticsearch query.

Can you give examples?

**Comment by MaineC** [comment]
Trying to make up an hypothetical example here:

Looking at https://www.otto.de/ you can enter both, some free text query as well as article numbers (e.g. found in printed catalogs). Having seen nothing but the user interface I have no idea how this is actually implemented, but I could imagine systems like these to have some logic in the application that tries to identify user queries/ search intents that look like article numbers and use a different template for retrieving results for that from the index compared to the template used for all other queries.

The only way to come up with an estimate answer to the question "Given a random user comes to our 
site, how well does our search perform?" is to sample a mix of both, queries for article numbers and free text queries. Being able to represent those as two templates in the rank eval request should make it easier to play around with how these queries are being translated to actual Elasticsearch queries.

Makes any sense at all?

**Comment by jpountz** [comment]
Thanks.

**Comment by MaineC** [comment]
Resolved with #22139
