### ISSUE TITLE
Missing test-jar dependency on Maven Central

### ISSUE THREAD

**Issue by jloisel** [elastic/elasticsearch#21263]
**Elasticsearch version**: 5.0.0

**Plugins installed**: []

**JVM version**: 1.8

**OS version**: any

**Description of the problem including expected versus actual behavior**:

As stated in the documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/using-elasticsearch-test-classes.html

Elasticsearch 5.0.0 lacks the "test-jar" artifact, it's not available on Maven Central.

**Comment by nik9000** [comment]
It has moved: http://search.maven.org/#artifactdetails%7Corg.elasticsearch.test%7Cframework%7C5.0.0%7Cjar

I'll push an update to the docs.

**Comment by s1monw** [comment]
try:
```XML
<dependency>
    <groupId>org.elasticsearch.test</groupId>
    <artifactId>framework</artifactId>
    <version>5.0.0</version>
</dependency>
```

**Comment by nik9000** [comment]
I pushed some updates to the docs: b2bbc485b176c1cc1c3afbc89b4fe69a9db83d98

I made a pom locally with the right versions and it fetched the dependencies properly.

**Comment by jloisel** [comment]
Great! Thanks guys :+1:

**Comment by s1monw** [comment]
@jloisel thank you!
