### ISSUE TITLE
full_id parameter unrecognized at /_cat/nodes in 5.0

### ISSUE THREAD

**Issue by nlowe** [elastic/elasticsearch#21266]
**Elasticsearch version**: `Version: 5.0.0, Build: 253032b/2016-10-26T05:11:34.737Z, JVM: 1.8.0_111`

**Plugins installed**: []

**JVM version**:

```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

**OS version**:

* Ubuntu 16.04.1
* `Linux elastic 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
In previous versions of elasticsearch, the `_cat/nodes` api accepted the parameter `full_id` to show the full node ID instead of an abbreviated version. It appears that this parameter is no longer accepted in `5.0`, and now returns a `400` response with an error:

```json
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "request [/_cat/nodes] contains unrecognized parameter: [full_id]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "request [/_cat/nodes] contains unrecognized parameter: [full_id]"
  },
  "status": 400
}
```

I'm not very familiar with the codebase, but according to [these lines](https://github.com/elastic/elasticsearch/blob/5.0/core/src/main/java/org/elasticsearch/rest/action/cat/RestNodesAction.java#L217-L236), this parameter should still exist, correct?

This causes [elasticbeat](https://github.com/radoondas/elasticbeat/blob/master/beater/nodes.go#L18) to be unable to collect stats on individual nodes and significantly impairs its effectiveness.

**Steps to reproduce**:
 1. Install and start an Elasticsearch `5.0` node
 2. `GET _cat/nodes?full_id=true`

**Provide logs (if relevant)**:
> No log lines emitted in elasticsearch logs.

**Comment by nik9000** [comment]
I believe you are right. I'll grab this in a few minutes if no one gets to it first.

**Comment by s1monw** [comment]
I can do it too @nik9000 if you want.. it's consumed too late though.

**Comment by nik9000** [comment]
Yeah, @jasontedor has a little spot where you can put things that might be consumed later to sneak by the check. I don't remember the name but I remember it being fairly obvious when you poke around.

If you want it you can have it.
