### ISSUE TITLE
Parent-child mapping on existing index

### ISSUE THREAD

**Issue by farhan687** [elastic/elasticsearch#21265]
**Elasticsearch version**: 2.4

How can I add parent-child mapping on existing index?

I read [over here](https://www.elastic.co/guide/en/elasticsearch/guide/current/parent-child-mapping.html) that I can add parent-child mapping with `update-mapping` api also.

Is there any example to achieve this?

thank you.

**Comment by cbuescher** [comment]
Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co/) and [IRC channels](https://www.elastic.co/community) for general questions.
