### ISSUE TITLE
Version conflict exception message enhancement

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#21278]
I am opening this issue to request the enhancement of the message when a document is not found. In that situation one gets:

https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/VersionType.java#L106

```
 "current version [" + currentVersion + "] is different than the one provided [" + expectedVersion + "]"
```

Being Current Version `-1`.

Maybe we can change the message when we have a document not found. Such as "Document not found". Which will be more intuitive than current version -1?

**Comment by nik9000** [comment]
This came up in a reindex context and it was fairly confusing. Maybe this is a thing reindex should have special cases for on top of any special cases we add for versioning in general. But this particular case seems like a thing versioning in general should handle.

**Comment by clintongormley** [comment]
Could we add to the message instead of changing it?  I know the Perl client parses these version numbers for metadata on a conflict exception.  There might be others depending on the same behaviour.

**Comment by nik9000** [comment]
> Could we add to the message instead of changing it?

Sure.

**Comment by bleskes** [comment]
This error message seems to come from the external versioning logic but external versioning doesn't see -1  ( == NOT_FOUND) as a conflict): 

```
   public boolean isVersionConflictForWrites(long currentVersion, long expectedVersion, boolean deleted) {
            if (currentVersion == Versions.NOT_FOUND) {
                return false;
            }
```

What am I missing?

**Comment by gmoskovicz** [comment]
@bleskes i see this in ES 2.3 and 2.4, perhaps it changes for 5.x hence why it doesn't make sense this issue now?

**Comment by clintongormley** [comment]
@bleskes why do you say this is for external versioning? You can see this error when running this on a non-existent doc:

    PUT t/t/2?version=3
    {}

**Comment by bleskes** [comment]
@clintongormley yes, that one generate a message which is definitely not nice - but it's different than the message above - this is the one I get (note the lack of higher or equal)

```
version conflict, current version [-1] is different than the one provided [3]
```

**Comment by gmoskovicz** [comment]
@bleskes i took that message from Master. I updated the description of this issue for clarification.

**Comment by clintongormley** [comment]
ah right, thanks for clarifying @bleskes

**Comment by gmoskovicz** [comment]
I have updated the description to make sure that it matches what we are referring to.

**Comment by vladimirdolzhenko** [comment]
@clintongormley @bleskes  Reverted back backport from 6.x branch - the change is only in 7.0
