### ISSUE TITLE
Have an option like refresh=wait_for but that only waits for the primary to refresh, not the replicas

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#21276]
Maybe we should have an option like `refresh=wait_for` but that only waits for the primary to refresh, not the replicas. This would allow folks using `preference=_primary` to wait less long. It isn't clear how much less long, though, because the primary and the replica have similar refresh intervals. For a long window (like 30 seconds) it could be significant though.

**Comment by bleskes** [comment]
I think reading from the primary is a leftover habit from the days of async replication. @synhershko  it seems you requested this  - can you elaborate on your use case?

**Comment by synhershko** [comment]
Do you have measurements on time for replication to happen?

We could really use that for highly real-time use-cases. There are scenarios where we explicitly query the primary only to see the most recent data possible, so new data is visible faster. We would love to wait for refresh and see even more recent data if it doesn't add significant latency.

If querying the primary only also waits for replication to happen and then refresh on replicas, that could easily add hundreds of ms and more, and in our cases (which I'll be happy to share in detail privately...) this means this feature is less real-time that we'd like.

I hope this makes sense, and I'd love to elaborate in private if needed.

**Comment by synhershko** [comment]
FWIW from the API standpoint when search preference asks for replica only, it doesn't make sense to wait for replication anyway, no?

**Comment by bleskes** [comment]
> We could really use that for highly real-time use-cases. There are scenarios where we explicitly query the primary only to see the most recent data possible

not sure how much this buys you as the primary and replica have their own 1s refresh intervals - no guarantee which will come in first for every given indexing operations. I'm curious to hear your use case but in ES in general we give no special treatment to the primaries for reads and aim for the simplicity of having the data read from all copies equally - just in the same fashion that indexing is done by all copies equally.

Do note that we wait for the refresh on the primary and replicas concurrently - we don't wait for the primary refresh to finish before starting to replicate.

**Comment by s1monw** [comment]
I agree with @bleskes here I don't think there is much gain here if any. @synhershko do you have any numbers on the ask you are making? I mean do you have a system that see sizable gains from that?

**Comment by s1monw** [comment]
also @synhershko can you clarify what you mean by the `highly real-time use-cases` what do you want to minimize, like the time to wait until a doc can be read? Maybe changing the refresh interval would be the right thing instead?

**Comment by ywelsch** [comment]
This feature would also have to account for primary relocation. Even if you use `_primary` you're not guaranteed to hit the same node in subsequent requests. I'm not sure it's worth the complexity.

**Comment by synhershko** [comment]
> not sure how much this buys you as the primary and replica have their own 1s refresh intervals - no guarantee which will come in first for every given indexing operations.

Most likely the primary, assuming replication takes time on a busy cluster.

> I'm curious to hear your use case

Gladly. I'll be seeing you soon :)

> I mean do you have a system that see sizable gains from that?

@s1monw I do. I will give Boaz the full details when I see him end of this month. It's too delicate and too complex for explaining on this thread. Basically think highly real-time system that needs maximum precision. Changing the refresh interval feels like an overkill - the wait_for_refresh sounds pretty much optimal to our use case because it will still refresh occasionally but will guarantee highly consistent reads, while we can live with some delays in reads.

> This feature would also have to account for primary relocation.

I'd argue this is less common. Specifically, for our cluster, we lock allocation anyway for performance reasons.

**Comment by bleskes** [comment]
> Most likely the primary, assuming replication takes time on a busy cluster.

Not sure this is the case, but as you say - we'll talk more.

**Comment by javanna** [comment]
@bleskes do you have anything to add to this issue?

**Comment by bleskes** [comment]
I think we can close this. Thanks for the ping Luca.
