### ISSUE TITLE
Elasticsearch response time - strange values

### ISSUE THREAD

**Issue by cechovsky** [elastic/elasticsearch#21279]
I'm querying simple Elasticsearch index with house numbers data.

```
".house-numbers": {
    "mappings": {
      "house-number": {
        "properties": {
          "id": {
            "type": "keyword"
          },
          "value": {
            "type": "text",
            "index_options": "docs"
          }
        }
      }
    }
  }
```
Then I'm querying data like POST http request

Request url

http://localhost:9200/.house-numbers/housenumber/_search
Headers:

Content-Type: text/plain
Content-Length: 55
Accept: */*
Accept-Encoding: gzip, deflate, br
Request body:

```
{
  "size": 30,
  "query": {
    "match": {
      "value": {
        "query": "2 3"
      }
    }
  }
}
```
The request returns data in 10ms - 30ms and everything works fine. The elasticsearch response parameter 'took' is small in all cases 3-5ms.

When I change size in the request body to "size": 35 the response time has suddenly 500ms. The 'took' parameter from Elasticsearch is the same. There are no special characters and the size of the response is very similar.

I tried many clients NEST, Postman, Fiddler to do these requests, every client has the same behaviour.

Setting of my elasticsearch contains only

http.compression : true
http.compression_level : 9
Setting of my jvm

```
"jvm": {
  "timestamp": 1478108615141,
  "uptime_in_millis": 17150141,
  "mem": {
    "heap_used_in_bytes": 1384307624,
    "heap_used_percent": 66,
    "heap_committed_in_bytes": 2077753344,
    "heap_max_in_bytes": 2077753344,
    "non_heap_used_in_bytes": 96403904,
    "non_heap_committed_in_bytes": 101502976,
    "pools": {
      "young": {
        "used_in_bytes": 324358632,
        "max_in_bytes": 558432256,
        "peak_used_in_bytes": 558432256,
        "peak_max_in_bytes": 558432256
      },
      "survivor": {
        "used_in_bytes": 69730304,
        "max_in_bytes": 69730304,
        "peak_used_in_bytes": 69730304,
        "peak_max_in_bytes": 69730304
      },
      "old": {
        "used_in_bytes": 990220848,
        "max_in_bytes": 1449590784,
        "peak_used_in_bytes": 1190046816,
        "peak_max_in_bytes": 1449590784
      }...
```
I tried different versions of elasticsearch I tried different settings - turn off http.compression, change compression_level I tried another hosts for elasticsearch

Am I doing something wrong or is it some type of bug in elasticsearch.

**Comment by clintongormley** [comment]
The `took` time counts everything up to result serialisation, so this sounds like an issue on the network side.  I wonder if your HTTP clients are using chunking.  Could you try using curl and explicitly disabling chunking as follows:

    curl -H "Expect:" ...

If that doesn't work, could you provide us with the two responses.  Another thought, do you have a virus scanner enabled?

**Comment by cechovsky** [comment]
I did some exploration and you're right, it was networking issue. I had fiddler running and it inspects some requests long time.

Now it is working good but .NET client NEST is doing similar problems. But it is issue for another repository.

**Comment by clintongormley** [comment]
thanks for letting us know @cechovsky
