### ISSUE TITLE
Support Backblaze B2 for Snapshot/Restore

### ISSUE THREAD

**Issue by OverlordQ** [elastic/elasticsearch#21283]
**Describe the feature**:

B2 is a competitor to S3, Google, Azure, RS, etc cloud storage offerings.  It would be great to offer this in addition to backing up to s3 buckets

**Comment by clintongormley** [comment]
Hi @OverlordQ 

This is the first time I've heard of B2.  It is unlikely that we will add support for it unless we get a lot more requests.  I'll leave this issue open for people to record their support.

**Comment by benaudiolock** [comment]
We would certainly make use of it as well.

**Comment by laurikari** [comment]
We would definitely use this.

**Comment by chmarr** [comment]
+1 !
It's, like, 3-4 times cheaper than S3.

**Comment by tlrx** [comment]
We talked about this with @ywelsch today and we both think that Backblaze B2 support for snapshot/restore could be implemented as community plugin. So we prefer to close this issue as a clear indication that we are not going to work on it at this time. If anyone would like to implement this, we will be glad to provide help or assistance if needed.

**Comment by vinnytroia** [comment]
+1

**Comment by nilayp** [comment]
Nilay from Backblaze here. We are getting a lot of requests for a plugin to elastic search that supports B2 object storage. As we have a [B2 Java SDK](https://github.com/Backblaze/B2_Command_Line_Tool), we believe the work won't be terribly hard. 

Is there somewhere I can go to read more about implementing a community plugin?

Is there someone on this issue that would be interested in working on such a project, under our sponsorship? If so, drop a line to our[ Contact Sales page](https://www.backblaze.com/b2/contact-sales.html) and mention my name.

-- Nilay

**Comment by tlrx** [comment]
> Is there somewhere I can go to read more about implementing a community plugin?

There's no step by step documentation that shows how to implement a repository plugin, but looking at the code of the existing ones can help:

- https://github.com/elastic/elasticsearch/tree/master/plugins/repository-gcs
- https://github.com/elastic/elasticsearch/tree/master/plugins/repository-s3

The plugin's entry point is a class that extends `Plugin` and implements `RepositoryPlugin`.

**Comment by painslie** [comment]
Backblaze is 1/4 the cost of AWS, has a reliable reputation; this could be a popular plugin; we'd use it.

**Comment by jsirianni** [comment]
👍  would love this

**Comment by jerrac** [comment]
Has anyone implemented snapshots via B2's S3 compatible API? As in use the official S3 plugin, just point it at B2 instead of Amazon.

**Comment by gitamj** [comment]
B2 has S3 compatible API. It works fine for us. We are using a snapshot like this:

`{
  "type": "s3",
  "settings": {
    "bucket": "elastic-backup",
    "region": "",
    "endpoint": "s3.us-west-001.backblazeb2.com"
  }
}`
