### ISSUE TITLE
Fail to parse query with query string search with unbalanced brackets

### ISSUE THREAD

**Issue by diugalde** [elastic/elasticsearch#21288]
I'm using ES v2.4 and If I make a request like the following, where there are unbalanced brackets ( `(`, `)`, `{`, `}`, `[`, `]`) in the query, I receive an exception.

```
GET index1/job/_search
{
  "query": {
    "query_string": {
      "fields": ["jobNumber"],
      "query": "827950 { foo"
    }
  }
}
```

For example, with the python client, the exception is the following:

`elasticsearch.exceptions.RequestError: TransportError(400, u'search_phase_execution_exception', u'Failed to parse query [827950 { foo]')`

**Comment by dakrone** [comment]
The `query_string` query is very strict, it throws exceptions about query parsing if there are any problems with the query (as in your case with the `{`). If you need a less strict query the `simple_query_string` query is a better option.

For future reference, we reserve Github issues for feature requests and bug reports. If you are having problems please use https://discuss.elastic.co instead!

**Comment by jiyuan312986471** [comment]
Hi everyone,

I've got the same error.

`elasticsearch.exceptions.RequestError: TransportError(400, 'search_phase_execution_exception', 'Failed to parse query [NOTRE DAME D OR]')`

Here's my `query_string`:
```
{
    'query_string': {
        'fields': ['commune', 'libelle_acheminement'],
        'query': 'NOTRE DAME D OR'
    }
}
```

I'm using Elasticsearch 5.4.0 btw.
