### ISSUE TITLE
Increase maximum number of fields per index

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#21282]
When using Logstash Twitter Input with `full_tweet` option (https://www.elastic.co/guide/en/logstash/current/plugins-inputs-twitter.html#plugins-inputs-twitter-full_tweet), this one comes with thousand of fields.

For example, I have some demos running with this config and migration tool is telling me that I have 1138 for one of my indices and 1447 in the other one.

Wondering if we can increased the default value to something like 2000?

If we can't we need to ask logstash team probably to remove this `full_tweet` option or to document how to remove some twitter fields with a `mutate`filter.

Thoughts?

**Comment by jasontedor** [comment]
This is a soft limit (`index.mapping.total_fields.limit`), why should we increase the default?

**Comment by dadoonet** [comment]
Ha sorry @jasontedor. I missed that in our docs. Actually I misread https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_mapping_changes.html#_field_mapping_limits 

Closing.
