### ISSUE TITLE
refresh vs flush

### ISSUE THREAD

**Issue by kaybinwong** [elastic/elasticsearch#21297]
**Elasticsearch version**: 5.0.0
> The refresh API allows to explicitly refresh one or more index, making all operations performed since the last refresh available for search. The (near) real-time capabilities depend on the index engine used. For example, the internal one requires refresh to be called, but by default a refresh is scheduled periodically.

i see the different between  [refresh vs flush](http://stackoverflow.com/questions/19963406/refresh-vs-flush) at stackoverflow, but i still can not understand.

does the refresh op fsynced or still in memery?
when refresh, does it clear the related translog?

**Comment by bleskes** [comment]
We reserve github for issues and feature requests, so I'm going to close this. Quickly answering your questions:

> does the refresh op fsynced or still in memory?

Operations are fsynced to the transaction log as soon as they are indexed. Refresh doesn't have to fsync them

> when refresh, does it clear the related translog?

No it doesn't. Only flush clears the translog.

If you have any more questions about this please feel free to ask on discuss.elastic.co and we'll be happy to help.

**Comment by kaybinwong** [comment]
got it, thx a lot
