### ISSUE TITLE
Strict shard request cache in 5.0 should automatically not cache non-deterministic queries  rather than throw an error

### ISSUE THREAD

**Issue by geekpete** [elastic/elasticsearch#21295]
**Elasticsearch version**: 
5.0

**Plugins installed**: 
Waiting on more info can backfill once collected.

**JVM version**: 
1.8.x (waiting on confirmation)

**OS version**:
Waiting on more info

**Description of the problem including expected versus actual behavior**:

Running a bool query with a range using "now" in the query throws an error due to the shard request cache refusing to cache it:

eg the range portion of a sample query:

```
        {
          "range": {
            "sentAt": {
              "from": "now-2M",
              "to": "now-1M",
              "include_lower": true,
              "include_upper": true,
              "boost": 1
            }
          }
        }
```
A full example query is here:
https://gist.github.com/geekpete/9b9d61dea18a86b47ce6d85d3ed6b839

**Steps to reproduce**:
 1. Use elasticsearch 5.0
 2. Run a range query (in this case was a bool query that used range
 3. Receive a RemoteTransportException with "features that prevent cachability are disabled on this context":

**Provide logs (if relevant)**:
```
RemoteTransportException[[ZRykcOY][XXXX:xxxx][indices:data/read/search[phase/fetch/id]]]; nested: FetchPhaseExecutionException[Fetch Failed [Failed to highlight field [message]]]; nested: ElasticsearchParseException[could not read the current timestamp]; nested: IllegalArgumentException[features that prevent cachability are disabled on this context]; 
```

The new version of Elasticsearch has the Shard Request Cache on by default and it's suggest that to avoid this error when using "now" in queries that the cache be disabled per-request, index-wide or cluster-wide:
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/shard-request-cache.html

An alternative to this behaviour might be to automatically not cache the requests that cannot be cached without throwing an error. Perhaps provide detail in the logs at debug level (or whatever level is suitable) whenever this occurs per request "features detected that prevent cachability" so that users can still debug when this is occurring such as when performance isn't good and the user expects that the requests are being cached.

**Comment by jpountz** [comment]
This failure is not intentional. Rather, it indicates that there is a bug since something is consuming the current timestamp after Elasticsearch made a decision about the cachability of the request. The goal is indeed to simply not cache requests that make use of the current timestamp.

**Comment by s1monw** [comment]
we added this safety to make sure we don't consume non-deterministic sources after we cache the query. now this is using stuff in the fetch phase which is ok but we still trip the safety. I will work on a fix

**Comment by s1monw** [comment]
I tried to reproduce this with highlighting but I can't. Is it possible to get some stacktrace?

**Comment by s1monw** [comment]
```DIFF
diff --git a/core/src/test/java/org/elasticsearch/search/fetch/subphase/highlight/HighlighterSearchIT.java b/core/src/test/java/org/elasticsearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
index ac6bc9a..ed63ea1 100644
--- a/core/src/test/java/org/elasticsearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
+++ b/core/src/test/java/org/elasticsearch/search/fetch/subphase/highlight/HighlighterSearchIT.java
@@ -2974,12 +2974,12 @@ public class HighlighterSearchIT extends ESIntegTestCase {
                     .preTags("<x>")
                     .postTags("</x>")
                 ).setQuery(QueryBuilders.boolQuery().must(
-                    QueryBuilders.rangeQuery("d").gte("now-7d/d").lte("now").includeLower(true).includeUpper(true).boost(1.0f))
+                    QueryBuilders.rangeQuery("d").gte("now-12h").lte("now").includeLower(true).includeUpper(true).boost(1.0f))
                     .should(QueryBuilders.termQuery("field", "hello")))
                 .get();
 
             assertSearchResponse(r1);
-            assertThat(r1.getHits().getTotalHits(), equalTo(3L));
+            assertThat(r1.getHits().getTotalHits(), equalTo(1L));
             assertHighlight(r1, 0, "field", 0, 1,
                 equalTo("<x>hello</x> world"));
         }
```

with this patch I can reproduce it.. working on a fix
