### ISSUE TITLE
Invalid location constraint when no region is provided in elastic 5 s3 backup plugin

### ISSUE THREAD

**Issue by girishramnani** [elastic/elasticsearch#21290]
i am trying to register a s3 repository using the following command.

```
curl -XPUT http://localhost:9200/_snapshot/testingbucketstore -d '{"type":"s3","settings":{"bucket":"somenewuniquebucketigirish","access_key":"***","secret_key":"***"}}'
```
I havent specified an region in the json and according to the documentation it `Defaults to US Standard `. But i get this error :
```

{"error":{"root_cause":[{"type":"amazon_s3_exception","reason":"amazon_s3_exception: The specified location-constraint is not valid (Service: Amazon S3; Status Code: 400; Error Code: InvalidLocationConstraint; Request ID: 845256AFBF889D0E)"}],"type":"repository_exception","reason":"[testingbucketstore] failed to create repository","caused_by":{"type":"amazon_s3_exception","reason":"amazon_s3_exception: The specified location-constraint is not valid (Service: Amazon S3; Status Code: 400; Error Code: InvalidLocationConstraint; Request ID: 845256AFBF889D0E)"}},"status":500}

```

elastic version - 5.0.0

**Comment by abeyad** [comment]
You've opened two issues related to not being able to register an s3 repository - which one represents the issue you are seeing when trying to register it?  I tried an S3 repository without specifying the region and it worked fine.

Also, we reserve Github for issues and feature requests, we will be happy to help you on the [discussion forums](https://discuss.elastic.co).
