### ISSUE TITLE
Number of Read operation increase significantly while merge segment

### ISSUE THREAD

**Issue by stephanustedy** [elastic/elasticsearch#21296]
**Elasticsearch version**: 2.4.0

**Plugins installed**: [kopf]

**JVM version**: 7

**OS version**: Ubuntu 14

**Description of the problem including expected versus actual behavior**:
Number of Read operation increase significantly.
I think it doing merge, 
when it happen, will cause a latency spike because of IO wait.

**Steps to reproduce**:
- I still dont know how to reproduce, but it happen sometimes, around 30 min once.

**Describe the feature**:
Add feature to limit number of read operation while merging segment.

**Comment by clintongormley** [comment]
Elasticsearch uses Lucene's merge auto-throttling to try to balance hardware resources between merge and search.  We need more info about what you're seeing.  Could you send the output of `GET _node/stats` during one of these latency spikes?

**Comment by stephanustedy** [comment]
@clintongormley 
attached some stats while merging, it causing spike.


[merge.txt](https://github.com/elastic/elasticsearch/files/577494/merge.txt)
![image](https://cloud.githubusercontent.com/assets/11306368/20089672/20c9ddd0-a5bb-11e6-8d9c-f90ae5028930.png)

**Comment by clintongormley** [comment]
I see that there is an ongoing merge of about 5GB, but your system has served 5.7 days worth of searches and has only spent 58 minutes merging.  Something that I find odd is that 50% of your docs are deleted? That seems like a high percentage.  Are you using TTL?  

To me your system looks healthy, are you seeing any practical problem or just a spike in IO?  Do you have any custom settings in your config file, cluster, or indices?

**Comment by stephanustedy** [comment]
yes, in my case update and delete is high. Im not using TTL.
does huge deletion affect this ?

actually, my system have iops limit, 1000.
when it merging, IO read will spike untill more than 1000, 
and causing lots of IO wait.

is 1000 iops for elastic is normal ?

yes, there is some. there is the settings
[settings.txt](https://github.com/elastic/elasticsearch/files/577814/settings.txt)

**Comment by clintongormley** [comment]
> does huge deletion affect this ?

It just means that more merging needs to happen.

**Comment by stephanustedy** [comment]
> #cache configuration
> indices.fielddata.cache.size: 20%
> indices.queries.cache.size: 50%
> indices.requests.cache.size: 30%

for this settings, my fielddata size is small, less than 1 mb.
most of my field is using doc_values.

what number do you suggest for cache size ? 
let say I only set for query cache and request cache.

and also, I check on node stats
> "total_auto_throttle": "5mb"

there is this number,
auto throttled to 5mb.
is it because heavy load on my server, and it throttled it ?

**Comment by clintongormley** [comment]
> what number do you suggest for cache size ? 

Just delete the settings and use the defaults.

> is it because heavy load on my server, and it throttled it ?

It means it was throttled for a total of 5mb, so very little.

**Comment by stephanustedy** [comment]
ok.

If I add more shards and nodes (or multiple disk), 
number of IO usage should be decrease ?

**Comment by clintongormley** [comment]
If these IO spikes are coming from merges, then it means your disks are slow and you will hit this in the future, no matter how many nodes you have.  You could use striping across multiple disks to increase throughput but the best thing would be to just increase your available IOPS (or even better, switch to SSDs).

This ticket is firmly in the realm of advice now, rather than bugs, so I suggest asking any more in the forum: https://discuss.elastic.co
