### ISSUE TITLE
Add note next to index settings that can be set at the node level

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#21316]
In the breaking changes 5.0 guide (https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_settings_changes.html), we mentioned index.codec being one of the settings that can be set on the node level.

>From Elasticsearch 5.0 on only selected settings like for instance index.codec can be set on the node level. All other settings must be set on each individual index.

The way the text is worded above suggests that there may be other ones. It will be helpful to add a short note to each [index module setting](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules.html) that can be set as a node level setting. Even if index.codec is the only one, it will be helpful to indicate that it can be set at the node level on the index modules page.

**Comment by rashig** [comment]
@ppf2 @clintongormley 
I would like to pick this task as a first contribution, please let me know the details and process.

**Comment by jrodewig** [comment]
[docs issue triage]

Closing this issue as 5.0 has fallen outside of our support lifecycle now.
