### ISSUE TITLE
_source doesn't work on parent inner_hits

### ISSUE THREAD

**Issue by ericofusco** [elastic/elasticsearch#21312]
**Elasticsearch version**: 5.0.0

**Plugins installed**: []

**JVM version**: Oracle JRE Server 8u112

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:

When _source is defined on inner_hits, it doesn't work the same way it works on outer hits. It gives the same error for any type I use. I guess it should work the same way is described on https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html.

For example "inner_hits":{ "_source": "name" } it doesn't work.

Query example:

```
GET local/document/_search
{  
      "_source": "name",
      "query":{  
         "bool":{  
            "must":[  
               {  
                  "bool":{  
                     "should":[  
                        {  
                           "has_parent":{  
                              "type":"document_category",
                              "inner_hits":{  
                                "_source": "name"                                                   
                              },
                              "query":{  
                                 "multi_match":{  
                                    "fields":[  
                                       "name",
                                       "description"
                                    ],
                                    "query":"test",
                                    "operator":"and"
                                 }
                              }
                           }
                        }
                     ]
                  }
               }
            ]
         }
      }
   }
}
```

Error: [inner_hits] _source doesn't support values of type: VALUE_STRING

**Steps to reproduce**:
 1. Create child and parent documents
 2. Use _source within inner_hits in has_parent

**Comment by clintongormley** [comment]
Inner hits expects the object form of `_source`, not the short form accepted by the top-level `_source`  pararameter

**Comment by ericofusco** [comment]
@clintongormley,

Thanks for the reply. Could you please give me a quick example for the "_source" ?

**Comment by clintongormley** [comment]
Sorry @ericofusco, I was just agreeing with you and adding some detail for @martijnvg 

This form of `_source` works in inner hits:

    "_source": { "includes": [...], "excludes": [...] }

**Comment by ericofusco** [comment]
@clintongormley ,

Alright. I guess I should keep this issue open until this is updated to accept the short form.

Using the object form as shown in your example works as expected.

Thanks again.

**Comment by sean-cherbone** [comment]
Additionally,
`
"_source": ["field1","field2"]
`
fails with error
> [inner_hits] _source doesn't support values of type: START_ARRAY

but works as:
`
"_source": { "includes":["field1","field2"] }
`
I will assume this is the same issue.

If this is the intended behavior from here on out, it just needs to be stated as such in the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html). The [inner hits options](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html#_options) documentation for 5.0 currently provides a link to the [top level source filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html) API; indicating that @ericofusco's code and mine should work.

**Comment by vincentfretin** [comment]
With elasticsearch 5.1.1,  "_source": { "includes":["uid"] } indeed doesn't give an error but the returned _source is actually an empty {} instead of {"uid": "8599f82f97684c72a9620f5552358b5d"} I'm waiting in my case.

**Comment by Tobion** [comment]
I can confirm @vincentfretin. Source filtering on inner hits is bugged:

- Using the short source filtering syntax creates an error
- Using `"_source": { "includes":["uid"] }` returns an empty _source even when the field exists
- Using "_source": { "includes":["uid"], "exludes":["foo"] }` returns the full _source and ignores the excluded field.

Tested with version 5.0.2 and 5.1.2

**Comment by JohPa8696** [comment]
Hi! I am new to the project. Can I try to tackle this issue? Any advice or suggestion would be much appreciated.

**Comment by polyfractal** [comment]
As reported by @Chakrygin in #23829 (see ticket for reproduction), this appears to be broken in field collapsing as well.  And also applies to disabling source entirely, not just various forms of filtering.

**Comment by clintongormley** [comment]
@talevy could you take a look at this please?

**Comment by abhishek5678** [comment]
Hi Everyone,
This example is working fine.but when i am checking with my data then it is not working.i am sending my data if anybody will be solve that then please reply me.


POST /icd10/item/1
{
    "name": "Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism (D50-D89)",
    "children": [{
        "name": "Iron deficiency anemia secondary to blood loss (chronic)",
        "code": "D50.0"
	}, {
		"name": "Sideropenic dysphagia",
            "code": "D50.1"
	}, {
		"name": "Other iron deficiency anemias",
            "code": "D50.2"
	}]
}

Also sending my mapping file and query also
mapping file:
PUT /icd10
{
    "mappings": { 
"item": {
      "properties": {
                "name":{
                    "type": "string"
                },
            "children": {
              "type": "nested",           
              "include_in_parent": true,  
              "properties": {
                "name": {
                  "type": "string"
                },
                "code": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }




QUERY:
GET /icd10/item/_search
{
  "_source": {
    "includes": [ "*" ],
    "excludes": [ "children" ]
  },
  "query": {
    "nested": {
      "path": "children",
      "inner_hits": {        
        "_source": {
          "excludes":["name"]
        }
      },
      "query": {
        "bool": {
          "must": [
            {
              "term": {
                "children.name": "Sideropenic dysphagia"
              }
            }
          ]
        }
      }
    }
  }
}

**Comment by talevy** [comment]
Finally got around to fixing this... and realized someone beat me to it 3 days ago 💥!

Looks like this commit fixed it: https://github.com/elastic/elasticsearch/commit/70e14d5e3fb78a74a89e812fc019882e781c61e4
So now the behavior is consistent in how the top-level and the inner-hits `_source` fields are parsed.

Tested against `5.x` with the shorthand string, array, and `includes`/`excludes`.

test CONSOLE script:
```
PUT company
{
  "mappings": {
    "branch": {},
    "employee": {
      "_parent": {
        "type": "branch" 
      }
    }
  }
}

POST /company/_bulk
{ "index": { "_type": "branch", "_id": "london" }}
{ "name": "London Westminster", "city": "London", "country": "UK" }
{ "index": { "_type": "employee", "_id": "london", "_parent": "london" }}
{ "name":  "Alice Smith", "dob":   "1970-10-24", "hobby": "hiking"}

GET company/_search
{
  "_source": "name",
  "query": {
    "has_parent": {
      "parent_type": "branch",
      "inner_hits": { "_source" : "city"},
      "query": {
        "match": {
          "country": "UK"
        }
      }
    }
  }
}
```
