### ISSUE TITLE
[5.0.0] Unable to run painless script againg float/long field: Invalid int constant

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#21313]
I'm unable to increment a float / long field due to a conversion error. Here is the mapping:

```
PUT /test-organizations
{
  "mappings": {
    "project": {
      "dynamic": false,
      "properties": {
        "id": {
          "type": "keyword"
        },
        "next_summary_end_of_day_ticks": {
          "type": "float"
        }
      }
    }
  }
}
```

```
PUT /test-organizations/project/1ecd0826e447ad1e78877ab2?op_type=create
{
  "id": "1ecd0826e447ad1e78877ab2",
  "next_summary_end_of_day_ticks": 636138180000000000
}
```

```
POST test-organizations/project/1ecd0826e447ad1e78877ab2/_update
{
  "script": "ctx._source.next_summary_end_of_day_ticks += 864000000000;"
}
```

Fails with
```json
{
  "error": {
    "root_cause": [
      {
        "type": "remote_transport_exception",
        "reason": "[qCyn3Kx][local[1]][indices:data/write/update[s]]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "failed to execute script",
    "caused_by": {
      "type": "script_exception",
      "reason": "compile error",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "Invalid int constant [864000000000]."
      },
      "script_stack": [
        "... mary_end_of_day_ticks += 864000000000;",
        "                             ^---- HERE"
      ],
      "script": "ctx._source.next_summary_end_of_day_ticks += 864000000000;",
      "lang": "painless"
    }
  },
  "status": 400
}
```

**Comment by jdconrad** [comment]
This is not a bug.  Use 864000000000L to specify this as a long constant or F to specify as a float constant.  864000000000 cannot be an int as it well exceeds the maximum value for the int spec in Java, so the error here is correct.

**Comment by niemyjski** [comment]
Yeah I get that. But this worked with groovy and is a PAIN. Why can't this be inferred from the mappings?

**Comment by niemyjski** [comment]
You could visit the painless parse result and update it according to the mappings would probably solve a few issues and give you better type checking

**Comment by jdconrad** [comment]
This cannot be done in the current architecture.  Scripts can be used across different indexes with different mappings, so if one mapping is float and one mapping is int there is no way to tell at compile-time which mapping to apply without tying a script to an index.  This cannot be done because our customers expect to be able to use the same script across multiple indexes.  This is unlikely to change in the near future if at all.  Even if we did infer from the mappings, this still would not work because it would require us to infer the RHS from the LHS.  Strict typing here prevents errors and improves performance.

**Comment by niemyjski** [comment]
Fair enough, thanks for the explanation.

**Comment by jdconrad** [comment]
You're welcome.  I'm sorry for the troubles you've been having switching over.  I realize transitions like this are not easy.
