### ISSUE TITLE
5.0 Breaking change with DateHistogram agg timezone feature: The datetime zone id '00:00' is not recognised

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#21320]
I did a very quick search through the breaking change log but didn't see this mentioned. We had an existing query that we generated in 1.x and it's working on 5.x except for when the offset is >= 00:00.

We **have generic code that just takes an offset and parses it into the format `XX:XX`** with an optional `-`. We then pass this as the timezone offset..

```
"date_histogram": {
        "field": "date",
        "interval": "14h",
        "min_doc_count": 0,
        "time_zone": "00:00"
      }
```

This however blows up in 5.x

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "The datetime zone id '00:00' is not recognised"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "The datetime zone id '00:00' is not recognised"
  },
  "status": 400
}
```

Reading over the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html), it doesn't say that this is not an allowed value (`00:00`).

> Time zones may either be specified as an ISO 8601 UTC offset (e.g. +01:00 or -08:00) or as a timezone id, an identifier used in the TZ database like America/Los_Angeles.

**Comment by s1monw** [comment]
@cbuescher can you take a look at this

**Comment by niemyjski** [comment]
I think I found the issue... So previously we were generating a `-` for any negative range and just `XX:XX` for any possitive range. It seems that I can't even run `10:00` as it errors out (a positive time range). However, `+00:00` or `-00:00` or `+10:00` works

**Comment by niemyjski** [comment]
I took this from wikipedia on `ISO 8601`
> An offset of zero, in addition to having the special representation "Z", can also be stated numerically as "+00:00", "+0000", or "+00". However, it is not permitted to state it numerically with a negative sign, as "−00:00", "−0000", or "−00". The section dictating sign usage (section 3.4.2 in the 2004 edition of the standard) states that a plus sign must be used for a positive or zero value, and a minus sign for a negative value. Contrary to this rule, RFC 3339, which is otherwise a profile of ISO 8601, permits the use of "-00", with the same denotation as "+00" but a differing connotation.

It appears that you have to specify a `-` or a `+`. But, this wasn't required in 1.x so something changed and thus broke. I think bare minimum this needs to be documented in the breaking changes and or supported. Thoughts?

**Comment by niemyjski** [comment]
With this said, is there an offset format that you recommend:

1. `+00:00`
2. `+0000`
3. `+00`

**Comment by rjernst** [comment]
The +/- change happened in 2.0: #8889

I believe you should use `[+-]dd:dd`

**Comment by brandonkearby** [comment]
I might be blind, but I didn't see any parsing for timezone in DateHistogramParser

**Comment by niemyjski** [comment]
@rjernst thanks very much for that. I don't remember seeing that in the 2.x breaking change logs but I did track it down to this: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_aggregation_changes.html#_timezone_for_date_field_2 

From the sounds of that patch it only supports `[+-]dd:dd`. Wonder if tests against all the ISO 8601 offset combinations should be added? Feel free to close this or take any action. It might be good to support the different ISO standards since it says it supports ISO 8601 (just my feedback).

**Comment by niemyjski** [comment]
On a side note: Upgrading from 1.x to 5.x I wish there was a dynamic list that showed you breaking changes between majors. I have a feeling lots of people are skipping 2.x and going straight to 5 and hitting everything that was broken along the way (I tried to read over all the breaking changes  in all versions since 1.x but there are so many and It's hard to see what affects you). :(

**Comment by cbuescher** [comment]
I opened a PR that adds test for these alternative ways of writing zero offset time zones. It seems like Joda (which is doing the time zone offset conversion) is already doing this correctly.

**Comment by s1monw** [comment]
@niemyjski did you check the [migration plugin ](https://github.com/elastic/elasticsearch-migration) by any chance?

**Comment by niemyjski** [comment]
@s1monw I did but in the 2x time frame. I don't remember seeing this in the plugin (not sure how it would have picked this up).
