### ISSUE TITLE
URI Search fails with parse_exception when query string contains slash

### ISSUE THREAD

**Issue by stefansaye** [elastic/elasticsearch#21323]
I get an error message when including a slash in query string.

The query is looks as below ,

    "query_string": {
             "query": "user0\/0\/0\/2",
               "default_field": "message"
       }

I know / is reserved characters, so I have  escape them with a leading backslash \,
but still got parse error,
Here's the response from ES:

        "shard" : 0,
          "index" : "logstash-log-2016.11.04",
          "node" : "J-EyJuTKRhaWsg",
          "reason" : {
           "type" : "query_parsing_exception",
           "reason" : "Failed to parse query [user0/0/0/2]",
           "index" : "logstash-log-2016.11.04",
           "line" : 20,
           "col" : 21,
           "caused_by" : {
             "type" : "parse_exception",
             "reason" : "parse_exception: Cannot parse 'user0/0/0/2': Lexical error at line 1, column 19.  Encountered: <EOF> after : \"/2\"",
             "caused_by" : {
               "type" : "token_mgr_error",
               "reason" : "token_mgr_error: Lexical error at line 1, column 19.  Encountered: <EOF> after : \"/2\""
             }
           }
         }
       } ]
     },
     "status" : 400
    }

This occurs with ES  "number" : "2.3.5",

**Comment by clintongormley** [comment]
@stefansaye that single `\` is for JSON escaping.  To have it make its way through to the query string, you need to double escape it:  `user0\\/0\\/0\\/2`
