### ISSUE TITLE
5.0 how to change default analyzer

### ISSUE THREAD

**Issue by 23233** [elastic/elasticsearch#21325]
## yep~  now don't in elasticsearch.yml change default analyzer??

**i want a method change default analyzer and search analyzer**

thanks~~~

**Comment by johtani** [comment]
Hello,
Please ask questions like these on the discussion forum: https://discuss.elastic.co/
We reserve Github for issues and feature requests.
Regarding your question, [you should set it to index settings or via index template](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_settings_changes.html#_index_level_settings)
