### ISSUE TITLE
GeoSearch with France matches docs in England

### ISSUE THREAD

**Issue by JnBrymn-EB** [elastic/elasticsearch#21324]
ES version 2.3.4 - build_hash: e455fd0c13dceca8dbbdbb1665d068ae55dabe3f

When querying for documents in France using a geo_shape query, documents in England are matched.

This gist shows how to repro the problem and includes the geo boundary of France.
https://gist.github.com/JnBrymn-EB/9aa32a4606ea2d2228f788d6fba245b1

Here is a screenshot of the portion of geo boundary that we're concerned about
![image](https://cloud.githubusercontent.com/assets/11304245/19993785/55466f2c-a216-11e6-8487-239fd45de25d.png)

**Comment by JnBrymn-EB** [comment]
ping @nknize

**Comment by clintongormley** [comment]
Hi @JnBrymn-EB 

First, please could you provide a simple recreation that we can just copy and paste into Console/Sense?  Second, have you tried to recreate this in 2.4.0?

**Comment by colings86** [comment]
No further feedback. @JnBrymn-EB if you have a reaction script or more information please comment and reopen this issue

**Comment by JnBrymn-EB** [comment]
Thanks. Sorry I didn't find the time to better repro this. It'll come up again if it's real.
