### ISSUE TITLE
Remove the upgrade API

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#21337]
The upgrade API is no longer useful for adapting an old index for the next major version+1. Instead, the reindex API should be used instead.  

We should remove the upgrade API.

**Comment by dadoonet** [comment]
I think we should do it when disabling source field will be removed: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html#_disabling_the_literal__source_literal_field

For now I don't believe we can remove this feature. No?

**Comment by rjernst** [comment]
@dadoonet We tried removing the ability to disable _source, but there was backlash. Why do you consider it to be related and blocking the removal of the upgrade api?

**Comment by dadoonet** [comment]
Reindex API reads _source right?

**Comment by clintongormley** [comment]
Yes it does, so reindex won't work if you disable source.  That's par for the course.  The upgrade API still won't help you to move to major version + 2.
