### ISSUE TITLE
Add documentation on how to use the transport client in 5.0.0+

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#21331]
From multiple topics on the Discourse forum we see users running into issues when using the 5.0 transport client. One issue is that they don't know what Maven coordinates to use to get running. Another issue is that the log4j dependency needs to be exact at the moment, it should be 2.6.2 and not 2.7  [1]. We should document this as part of the [transport client documentation](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html).

[1] https://discuss.elastic.co/t/issue-with-elastic-search-5-0-0-java-lang-classnotfoundexception-org-apache-logging-log4j-core-async-daemonthreadfactory/64345/7

**Comment by clintongormley** [comment]
@dadoonet please could you take care of this one

**Comment by jasontedor** [comment]
@dadoonet I think it would also be helpful to include in these docs how to replace Log4j 2 with another logging provider via the SLF4J bridge when using the transport client.

**Comment by dadoonet** [comment]
Closed by #21477
