### ISSUE TITLE
Duplicate IN_PROGRESS snapshots returned by GET /_snapshot/repo/_all in Elasticsearch 5.0

### ISSUE THREAD

**Issue by brino** [elastic/elasticsearch#21335]
**Elasticsearch version**: 
5.0.0

**Plugins installed**: 
none

**JVM version**: 
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)

**OS version**:
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-327.el7.x86_64
      Architecture: x86-64

**Description of the problem including expected versus actual behavior**:
When I create a snapshot in any repository, then get all snapshots in the repository. I see two snapshots IN_PROGRESS! Then when the process finishes, I only see one SUCCESSFUL snapshot. The snapshots seem to work correctly, it's just that it shows duplicates while IN_PROGRESS. You can even see below, they have the same uuid: RHlVXKe-TKqB47nAoeh3Sw. Seems like this is probably not intended behavior!

**Steps to reproduce**:
 
1. (CREATE) $ curl -XPUT localhost:9200/_snapshot/brokerhistory/test -d'{"indices":"brokerhistory_2016-11-04"}'
```json 
{"accepted":true}
```
 
2. (IN_PROGRESS) $ curl -XGET localhost:9200/_snapshot/brokerhistory/_all?pretty
```json
{
  "snapshots" : [
    {
      "snapshot" : "test",
      "uuid" : "RHlVXKe-TKqB47nAoeh3Sw",
      "version_id" : 5000099,
      "version" : "5.0.0",
      "indices" : [
        "brokerhistory_2016-11-04"
      ],
      "state" : "IN_PROGRESS",
      "start_time" : "2016-11-04T13:24:42.755Z",
      "start_time_in_millis" : 1478265882755,
      "failures" : [ ],
      "shards" : {
        "total" : 0,
        "failed" : 0,
        "successful" : 0
      }
    },
    {
      "snapshot" : "test",
      "uuid" : "RHlVXKe-TKqB47nAoeh3Sw",
      "version_id" : 5000099,
      "version" : "5.0.0",
      "indices" : [
        "brokerhistory_2016-11-04"
      ],
      "state" : "IN_PROGRESS",
      "start_time" : "2016-11-04T13:24:42.755Z",
      "start_time_in_millis" : 1478265882755,
      "failures" : [ ],
      "shards" : {
        "total" : 0,
        "failed" : 0,
        "successful" : 0
      }
    }
  ]
}
```

3. (SUCCESS) $ curl -XGET localhost:9200/_snapshot/brokerhistory/_all?pretty
```json
{
  "snapshots" : [
    {
      "snapshot" : "test",
      "uuid" : "RHlVXKe-TKqB47nAoeh3Sw",
      "version_id" : 5000099,
      "version" : "5.0.0",
      "indices" : [
        "brokerhistory_2016-11-04"
      ],
      "state" : "SUCCESS",
      "start_time" : "2016-11-04T13:24:42.755Z",
      "start_time_in_millis" : 1478265882755,
      "end_time" : "2016-11-04T13:25:31.027Z",
      "end_time_in_millis" : 1478265931027,
      "duration_in_millis" : 48272,
      "failures" : [ ],
      "shards" : {
        "total" : 1,
        "failed" : 0,
        "successful" : 1
      }
    }
  ]
}
```

**Comment by abeyad** [comment]
Thank you for reporting @brino, this is indeed a bug and we will work on a fix.

**Comment by brino** [comment]
Cool! Glad to help.

**Comment by abeyad** [comment]
@brino note that snapshot/restore is working fine, it is just the json response returned when calling `_all`.  Specifying `_current` works as expected.

**Comment by brino** [comment]
Yes, the snapshot definitely seems to be working properly, just that response has a duplicate IN_PROGRESS.
