### ISSUE TITLE
Field and max_docs_per_value arguments in sampler agg on ES5

### ISSUE THREAD

**Issue by pkphlam** [elastic/elasticsearch#21347]
**Elasticsearch version**: 5.0

I'm having trouble with the `field` and `max_docs_per_value` arguments that control diversity in the sampler aggregation for ES 5.0. With code that previously worked in ES 2.x which simply defines a field to control diversity on, I now get the following error when trying to define the arguments in ES 5.0:

`RequestError: TransportError(400, 'parsing_exception', 'Unsupported property "field" for aggregation "sampler')`

The documentation seems to be the same between the versions. I'm using the elasticsearch and elasticsearch_dsl python packages to do this, although this seems like an ES error?

**Comment by clintongormley** [comment]
@markharwood could you take a look at this? I'm seeing the same as the reporter:

```
POST t/t/_bulk
{"index":{}}
{"text":"one"}
{"index":{}}
{"text":"two"}
{"index":{}}
{"text":"two"}
{"index":{}}
{"text":"three"}
{"index":{}}
{"text":"three"}
{"index":{}}
{"text":"three"}

GET t/_search
{
  "size": 0,
  "aggs": {
    "NAME": {
      "sampler": {
        "field": "author",
        "max_docs_per_value": 3
      }
    }
  }
}
```

Also, the docs seem to have two aggs called sampler:

* https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-aggregations-bucket-diversified-sampler-aggregation.html
* https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-aggregations-bucket-sampler-aggregation.html

**Comment by markharwood** [comment]
As far as I recall @colings86  during refactoring needed to break `sampler` agg into 2 different aggs: `sampler` and `diversified_sampler`.
It wasn't done to make the DSL simpler from an end-user's perspective but was purely for internal technical implementation reasons. The result is that the docs both end up needing to describe the same details (shard_size etc) and `sampler` agg retains a description of how to do diversification using the alternative agg now required to do this.

**Comment by clintongormley** [comment]
@markharwood ok, except the diversified sampler still refers to `sampler`

**Comment by colings86** [comment]
@clintongormley Yep, the first of your links should be titled `diversified_sampler` and the code samples should reference that as the name too.
