### ISSUE TITLE
Java client exception thrown only when all shards fail.

### ISSUE THREAD

**Issue by TheGreatYamcha** [elastic/elasticsearch#21345]
**Elasticsearch version**:1.4.4

**Plugins installed**: [head]

**JVM version**:1.8

**OS version**:rhel 6

**Description of the problem including expected versus actual behavior**: the java client throws a EsRejectedExecutionException only when all shards fail. When some shards fail, no exception is thrown.

**Steps to reproduce**:
 1.Run parallel arbitrary queries with the java client until the server cannot handle anymore.
 2.Only some of the queries will fail, throwing EsRejectedExecutionException. If only some shards fail, the exception isn't thrown.

**Comment by clintongormley** [comment]
Sorry @TheGreatYamcha but 1.4.4 is way too old.  Please upgrade and open a new issue if you can replicate this on 5.0

**Comment by TheGreatYamcha** [comment]
I can test it on a newer version, but as you know (https://github.com/elastic/elasticsearch/issues/18978), elasticsearch returns 200 when some shards fail and `SearchResponse.status()` also returns `RestStatus.OK` even when a shard fails. This is apparently the intended behavior.
I want to make sure that not throwing an exception when a shard fails is not the intended behavior and is indeed a bug.

**Comment by clintongormley** [comment]
Not throwing an exception in search when some (not all) shards fail is considered a feature, not a bug as we return you what information we can (perhaps while shards are recovering).  You can check the `_shards` response for more info about how many shards succeeded or failed.

**Comment by TheGreatYamcha** [comment]
@clintongormley then why did you tell me to try this on a newer version of Elasticsearch?

**Comment by clintongormley** [comment]
Because I misread your original issue
