### ISSUE TITLE
Expand /_cat/snapshots API to accept _all and treat /_cat/snapshots as a synonym for /_cat/snapshots/_all

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#21346]
The `/_cat/snapshots` API previously had a required path parameter `repository`. This meant that if you wanted help for this API, you previously had to say `/_cat/snapshots/<repository>?help`. The `<repository>` could be anything. When strict URL parsing was added, this would lead to the `repository` parameter going unconsumed. To circumvent this, a handler was added for `/_cat/repository` so that you can say `/_cat/repository?help` and not have to deal with strict URL parsing. This handler is a weird endpoint now though, it makes this API different from other cat APIs. This endpoint should do something. This issue proposes making the `/_cat/snapshots/repository` endpoint accept `_all` as a parameter (with the obvious behavior to give the output for all repositories) and make `/_cat/snapshots` a synonym for `/_cat/snapshots/_all`.

Relates #20722

**Comment by liketic** [comment]
Hi @javanna , is this still worth to fix? Thanks in advance.

**Comment by javanna** [comment]
yes @liketic feel free to take it ;)

**Comment by dakrone** [comment]
I checked and this is no longer an issue. I'm closing this as fixed.
