### ISSUE TITLE
remove 'Local Transport' section from modules/transport documentation in 5.0/5.x

### ISSUE THREAD

**Issue by agebhar1** [elastic/elasticsearch#21359]
The section was already remove in 194a6b1 'Remove LocalTransport in favor of MockTcpTransport' but was not yet cherry-picked to 5.0/5.x branches. The [online documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-transport.html#_local_transport) still contains it.

**Comment by jasontedor** [comment]
This was only deprecated in 5.x, but removed in master.

**Comment by agebhar1** [comment]
But `NodeBuilder` doesn't exists anymore in 5.0, it was removed in 6f166dd0fff5421bb81cd102fc84360fb43e6b9a.

**Comment by clintongormley** [comment]
@dadoonet could you update the docs with the correct use of Node instead of NodeBuilder please?

**Comment by jasontedor** [comment]
> but `NodeBuilder` doesn't exists anymore in 5.0, it was removed in 6f166dd0fff5421bb81cd102fc84360fb43e6b9a.

Sure, but note that is a separate issue than what you opened here. We will get the docs fixed though, thank you for pointing it out.

**Comment by agebhar1** [comment]
Sorry for confusion. Found the commit which removed the invalid `NodeBuilder` part from documentation. The issue title could have been chosen better.

**Comment by PolinaMash** [comment]
Could you please clarify in documentation how to start and use local node now, if it still remains. Or what should we use if this approach was changed completely. We used local nodes for testing purposes.
It was described previously here https://www.elastic.co/guide/en/elasticsearch/client/java-api/2.0/node-client.html
Also there left Local Transport section unchanged though NodeBuilder doesn't exists anymore: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-transport.html#_local_transport

**Comment by s1monw** [comment]
@PolinaMash i remove that section in #21529 if you want to run tests please use our [test-framework](https://www.elastic.co/guide/en/elasticsearch/reference/current/testing-framework.html) you can just run an integration test by subclassing `ESIntegTestCase` as described [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/integration-tests.html). if you use maven just include it like [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/using-elasticsearch-test-classes.html)

**Comment by agebhar1** [comment]
@PolinaMash have a look at [this](/agebhar1/facelasticq/blob/master/src/main/java/com/github/agebhar1/facelasticq/service/elasticsearch/EmbeddedNode.java) - it spins up a (isolated) node within the same JVM, see also test cases.

**Comment by PolinaMash** [comment]
@s1monw thanks for update. About testing framework it doesn't suit here because we test application microservice that is written over elasticsearch Java api. Local node was ideal solution for our case, when we can start elasticsearch 'locally" and clear everything when tests end.
@agebhar1 thanks, that solution made my tests work! Also i found this issue https://github.com/elastic/elasticsearch/issues/19903 it's exactly what I faced before has written here. I think it make sense to include this also to documentation, because "local node" feature is rather useful in some cases and now it looks like it was completely kicked off.

**Comment by agebhar1** [comment]
Hi @PolinaMash thanks for reply, that it helped - sounds good. #19903 - yep me too. I struggled some hours with reading commit history. But at the end it works. I would appreciate to add it to documentation.
