### ISSUE TITLE
`term_vector` should not prevent a `string` field from being upgraded to `text`

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#21356]
Elasticsearch 5.0

The following:

```
PUT index
{
  "mappings": {
    "type": {
      "properties": {
        "foo": {
          "type": "string",
          "index": "analyzed",
          "term_vector": "with_positions"
        }
      }
    }
  }
}
```

throws this exception:

    The [string] type is removed in 5.0 and automatic upgrade failed because parameters [term_vector] are not supported for automatic upgrades. You should now use either a [text] or [keyword] field instead for field [phrase]

**Comment by javanna** [comment]
I wonder if it's not too late to fix this, cc @elastic/es-search-aggs

**Comment by jpountz** [comment]
We didn't get many complaints about it. Closing.
