### ISSUE TITLE
Plugin ingest-geoip only works some of the time

### ISSUE THREAD

**Issue by blacktop** [elastic/elasticsearch#21366]
**Elasticsearch version**: 5.0.0

**Plugins installed**: [ingest-geoip, ingest-user-agent]

**JVM version**: 8
**OS version**: alpine 3.4

**Description of the problem including expected versus actual behavior**:
I am using ingest-geoip to ingest nginx logs and it only seems to work some of the time.

I am doing a somewhat large bulk ingest so maybe I am sometimes overwhelming the ingest node if my machine is busy doing other things?

**Steps to reproduce**:

https://github.com/blacktop/docker-es-demo-data

```bash
$ docker run -d --name elastic -p 9200:9200 blacktop/elasticsearch:geoip
$ docker run -d --name kibana --link elastic:elasticsearch -p 5601:5601 blacktop/kibana
$ docker run --rm --link elastic:elasticsearch blacktop/es-data
```
=OR=
```bash
$ docker run -d --name elastic -p 9200:9200 blacktop/elasticsearch:x-pack
$ docker run -d --name kibana --link elastic:elasticsearch -p 5601:5601 blacktop/kibana:x-pack
$ docker run --rm --link elastic:elasticsearch -e ES_USERNAME=elastic -e ES_PASSWORD=changeme blacktop/es-data
```

![screen shot 2016-11-06 at 5 22 28 pm](https://cloud.githubusercontent.com/assets/6118188/20043182/9e29758c-a445-11e6-8921-512ad838a585.png)

**Comment by clintongormley** [comment]
Sorry @blacktop but nobody is going to jump through hoops to run your demo on docker :)  There's just too much else to do.  Can you provide more information about why you think it is not working, what's in the logs, what is returned in your bulk indexing requests, any ingest errors included in your indexed docs, etc.

**Comment by blacktop** [comment]
@clintongormley I apologize, I thought having it in docker would make it even easier to run and recreate.  It sounds like you guys are very overworked.

I will instrument my code with more logging and see it I can see the issue.

https://github.com/blacktop/docker-es-demo-data/blob/master/5.0/main.go

Thank you.

**Comment by clintongormley** [comment]
thanks @blacktop - appreciated :)
