### ISSUE TITLE
Debian sources.list W: Failed to fetch https://artifacts.elastic.co/packages/5.x/apt/dists/stable/main/binary-amd64/Packages  Failed to connect to artifacts.elastic.co port 443: Connection refused

### ISSUE THREAD

**Issue by lyf-t** [elastic/elasticsearch#21367]
i was using Debian install elasticsearch reference from [elastic.co  deb.html](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/deb.html)
1. `wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -`
2. `sudo apt-get install apt-transport-https`
3. `echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list`
4. `sudo apt-get update && sudo apt-get install elasticsearch`

then get:
`Failed to connect to artifacts.elastic.co port 443: Connection refused
E: Failed to fetch https://artifacts.elastic.co/packages/5.x/apt/pool/main/f/filebeat/filebeat_5.0.0_amd64.deb  Failed to connect to artifacts.elastic.co port 443: Connection refused`
 

my `source.list`
 `deb http://mirrors.163.com/debian/ jessie main non-free contrib
deb http://mirrors.163.com/debian/ jessie-updates main non-free contrib
deb http://mirrors.163.com/debian/ jessie-backports main non-free contrib
deb-src http://mirrors.163.com/debian/ jessie main non-free contrib
deb-src http://mirrors.163.com/debian/ jessie-updates main non-free contrib
deb-src http://mirrors.163.com/debian/ jessie-backports main non-free contrib
deb http://mirrors.163.com/debian-security/ jessie/updates main non-free contrib
deb-src http://mirrors.163.com/debian-security/ jessie/updates main non-free contrib`

`/etc/apt/sources.list.d/elastic-5.x.list`
     `deb https://artifacts.elastic.co/packages/5.x/apt stable main`

java -version 1.7.0_111
Debian version 8.5

**Comment by cjeanneret** [comment]
Weird, had the exact same error on Saturday, but yesterday it was OK… Might be some issue when new packages are pushed?

**Comment by clintongormley** [comment]
@lyf-t could you try again please?  If still failing, could you upload the output of this command please?

    curl -v -L -H https://artifacts.elastic.co/packages/5.x/apt/pool/main/f/filebeat/filebeat_5.0.0_amd64.deb

**Comment by lyf-t** [comment]
oh, success installed
i was completed install elasticsearch, below is my steps references from [Elasticsearch install](http://www.ttlsa.com/linux/elasticsearch-install-on-ubuntu/)

1. wget -O - http://packages.elasticsearch.org/GPG-KEY-elasticsearch | apt-key add -
2. echo "deb http://packages.elasticsearch.org/elasticsearch/1.1/debian stable main" >>  /etc/apt/sources.list
3. apt-get install elasticsearch
4. update-rc.d elasticsearch defaults 95 1
5. /etc/init.d/elasticsearch start

and then i was typed 
   ` netstat -tnulp`
found the 9200 port and 9300 port

**Comment by clintongormley** [comment]
thanks @lyf-t

**Comment by dliappis** [comment]
@lyf-t Glad that you do this working.

Just for posterity and troubleshooting, could you please share the output of the curl command [mentioned above](https://github.com/elastic/elasticsearch/issues/21367#issuecomment-258831428)? One point of interest is whether you are using IPv6 and the curl output should show that.

Thank you!

**Comment by lukawendy** [comment]
Hi I met this issue, how to solve it? @lyf-t @clintongormley @dliappis 

Err https://artifacts.elastic.co stable/main amd64 Packages
  HttpError404
Ign https://artifacts.elastic.co stable/main Translation-en
Ign https://artifacts.elastic.co stable/main Translation-en
Fetched 3481 B in 2s (1234 B/s)
W: Failed to fetch https://artifacts.elastic.co/elasticsearch/packages/5.x/apt/dists/stable/main/binary-amd64/Packages  HttpError404

**Comment by lukawendy** [comment]
sorry, the fetch path is not correct. Sorry to bother.
