### ISSUE TITLE
failed to start

### ISSUE THREAD

**Issue by sminds** [elastic/elasticsearch#21363]
Cento 6.7, elasticsearch 5.0

`sudo service elasticsearch start`

```
Starting elasticsearch: /usr/share/elasticsearch/bin/elasticsearch: line 198: 13950 Killed                  exec "$JAVA" $ES_JAVA_OPTS -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" org.elasticsearch.bootstrap.Elasticsearch "$@" 0>&-
                                                           [FAILED]
```

**Comment by jasontedor** [comment]
Elastic reserves GitHub for verified bug reports and feature requests but provides the [Elastic Discourse forum](https://discuss.elastic.co) for general questions.

There are numerous reasons that Elasticsearch can fail to start, and you've given no information to help distinguish the reason that it is failing to start for you. If you do post a topic on the forum, you're more likely to get high-quality assistance if you provide as much germane information as you have.
