### ISSUE TITLE
Fail build when our version of a transitive dependency differs from the version one of our dependencies depends on

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#21373]
Fail build when our version of a transitive dependency differs from the version one of our dependencies depends on. This'll make more sense with an example.

```
plugin:analysis-icu:6.0.0
  +----- lucene-analyzers-icu:6.3.0-snapshot-a66a445
                 +----- icu4j:56.1
  +----- icu4j:54.1     <----- This should cause a build failure
```

Sometimes we do want to override the version of some dependency so we'd need some way to shut the check off for certain dependencies.

Relates to #21352

**Comment by clintongormley** [comment]
@nik9000 we may not want to update ICU at the same time as Lucene does, but instead only make the change on a major version, so we should have a way to silence this build failure as well.

**Comment by dadoonet** [comment]
Discussed in FixIt friday. Closing it in favor of https://github.com/elastic/elasticsearch/issues/15238#issuecomment-261509240 which contains the details of what is expected.
