### ISSUE TITLE
We should be able to specify how to handle arrays of Objects in a Dynamic Template

### ISSUE THREAD

**Issue by rodney757** [elastic/elasticsearch#21386]
**Describe the feature**:

When creating a dynamic template, we should be able to specify how to map arrays of Objects. Since Object arrays are a bit different in elasticsearch, it would be helpful to specify a template that will use the Nested datatype for any array of Objects

**Comment by jpountz** [comment]
I understand your reasoning, but nested objects are heavy, so I am reluctant to make it easy to create them automatically. I'll mark it as `discuss` to give others a chance to chime in, but I would lean towards not implementing this feature.

**Comment by jpountz** [comment]
Discussed in FixitFriday: Nested objects are an expensive feature so we do not want to make it easier to create nested objects implicitly.

**Comment by rosendi** [comment]
@jpountz Any changes in your decision? For example I have an `event` model with custom user attributes with nested arrays. Events come with different structures all the time so I can't use mappings to tell ES which attributes are nested explicitly. For my case ES should treat arrays of objects always as `nested`. So what is a good way to handle for such cases? Am I missing something?
