### ISSUE TITLE
Slow reindex with sort _doc desc

### ISSUE THREAD

**Issue by richardpeng** [elastic/elasticsearch#21395]
I'm using the _reindex API in version 2.4.1 and would like to sort by `_doc` descending to presumably import the latest documents into a new index. However, this is extremely slow compared to the default `_doc` ascending sort. Would it be possible to make the descending sort as fast as the default sort?

**Comment by jpountz** [comment]
Could you explain your use-case more in details? In particular I suspect there is a wrong assumption with:

> import the latest documents into a new index

The `_doc` id is most of times correlated with the import order, but it can also become completely unrelated since merges are allowed to completely reorder documents, so you might have some old documents getting a higher doc id than some recent documents.

`sort: _doc` really means "I do not care about the order, so give me the documents in whatever order suits you best".

**Comment by javanna** [comment]
maybe we should prohibit setting the direction (desc or asc) when using sort by _doc given that doesn't do what users may expect? or maybe change the syntax to make it clear that it really means no sorting?

**Comment by jpountz** [comment]
Maybe. I had a similar intention when suggesting that we rename `_doc` to `_any` (#13789). Then we could also sort in ascending doc id order if someone specifies `_any DESC`.

**Comment by nik9000** [comment]
I figure we're kind of stuck with `_doc` for now. I mean we _could_ change it in 6.0 but I don't really think it is worth it now that it has been out for so long and we feel like we've explained it. Maybe the right thing to do here is to remove setting the direction for `_doc` like @javanna says and mention why in the docs.

**Comment by jpountz** [comment]
Yeah I agree the cost is not worth the gain here, now that we have been communicating about using `sort: _doc` for fast scrolls. +1 to @javanna 's suggestion too.

**Comment by richardpeng** [comment]
I understand that `_doc` is meant for fast scrolls and that it shouldn't be used as a proxy for import order. However, even though it's very slow and doesn't return documents exactly in import order, it's still faster than reindexing hundreds of millions of documents. Ideally, I'd like a way to sort by import order.

**Comment by nik9000** [comment]
> Ideally, I'd like a way to sort by import order.

The usual way to do this it to maintain a last modified date on the document. Elasticsearch has an [ingest processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/date-processor.html) that can be used to stick the date on documents that you index but I don't believe it works for updates.

**Comment by richardpeng** [comment]
Sounds good. I'll maintain a date field on my documents. Thanks for the pointer on the ingest processor. I'll check that out.

**Comment by colings86** [comment]
Closing as there doesn't seem like anything for us to do here.
