### ISSUE TITLE
[bug report]lots of memory consumption in clientHandlers

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#21394]
**Elasticsearch version**:
2.1 
**Plugins installed**: []
delete-by-query
elasticsearch-analysis-ik
repository-hdfs
**JVM version**:
jdk1.8.0_60
**OS version**:
CentOS Linux release 7.1.1503
**Description of the problem including expected versus actual behavior**:
our cluster is with 6.7T*2 and 17 data nodes with 30G heap and 17 gateway nodes with 8G heap and 3 master with 6G heap
we use fielddata which consump about 6G memory per data node.
and with about 400 search/seconds, the nodes with great memory presure and some of them even out of the cluster.
the I stop read/write and delete all the data.
but there are some data nodes still with over 90 heap usage and wouldn't drop even with heap dump which will force full-gc.
and then I take a look at the heap dump and found out that clientHandlers holds many many objects.
below is the pic of heap dump:
https://github.com/makeyang/grocery/blob/master/heapdump.png

please let me know if u need anything

**Comment by makeyang** [comment]
this one is more clear:
https://github.com/makeyang/grocery/blob/master/headdump2.png

**Comment by makeyang** [comment]
this one:
https://github.com/makeyang/grocery/blob/master/heapdump3.png

**Comment by makeyang** [comment]
so basically should we just add timout config for ShardActiveResponseHandler?

**Comment by clintongormley** [comment]
@imotov is this something you've fixed in 2.x?

**Comment by imotov** [comment]
@clintongormley you are probably referring to #19794, which was indeed fixed in the plugin that was causing the leak. This one seems to be a completely different unrelated issue, but I think I have a good idea how to fix it as well. Will open PR in a bit.
