### ISSUE TITLE
Rank eval: Add option to switch between verbose/non-verbose result format

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#21407]
Problem: Currently for each rank evaluation request we return the verbose response format including all hits and ratings as specified per #20497 we added some detailed information on which hits were returned per rated search request. While this is useful for debugging purposes, when tinkering with queries it might make sense to also support a minimal response format like so:

    {
        "rank_eval": {
            "quality_level": 1.0,
            "metric_details": {
                    "relevant_docs_retrieved": 2,
                    "unknown_docs_retrieved": 5,
                    "retrieved_docs": 2
                    }
                }
            }
        }
    }

**Comment by jpountz** [comment]
I'm not sure this is worth working on, I would be fine with this API having a verbose output all the time, even if that means returning more information than what a UI would need.

**Comment by MaineC** [comment]
One clarification: I'm not worried at all about providing more information than what a UI would need.

The problem I am trying to solve with that is to make it easier for people tinkering with the API without some UI to be able to quickly see changes in quality_level, number of relevant/ unknown documents retrieved without having to mentally parse/ fold away all the other detail information.

I'm fine though with punting/ closing this.

**Comment by cbuescher** [comment]
I think closing this is okay, the verbose version should be fine for all we are trying to do now.
