### ISSUE TITLE
migration/migrate_5_0/java.asciidoc 5.0/5.x - wrong transport package version

### ISSUE THREAD

**Issue by agebhar1** [elastic/elasticsearch#21404]
In [docs/reference/migration/migrate_5_0/java.asciidoc](https://github.com/elastic/elasticsearch/blob/5.0/docs/reference/migration/migrate_5_0/java.asciidoc) the plugin is not up-to-date. The Maven dependency is:

```
<dependency>
    <groupId>org.elasticsearch.client</groupId>
    <artifactId>transport</artifactId>
    <version>5.0.0-alpha5</version>
</dependency>
```

**Comment by jasontedor** [comment]
Thanks for reporting. I pushed 927d532e9825a93792400ce5ca7dad198eba0fde for 5.0 and e8a6758f45093c502661cebc9b0bfca11bffdfa0 for 5.x.

**Comment by agebhar1** [comment]
you're welcome
