### ISSUE TITLE
docs/groovy-api/index.asciidoc 5.0/5.x - wrong Groovy API package version

### ISSUE THREAD

**Issue by agebhar1** [elastic/elasticsearch#21406]
Sorry found another one. In [docs/groovy-api/index.asciidoc](https://github.com/elastic/elasticsearch/blob/5.0/docs/groovy-api/index.asciidoc) the plugin is not up-to-date. The Maven dependency is:
```
<dependency>
    <groupId>org.elasticsearch</groupId>
    <artifactId>elasticsearch-groovy</artifactId>
    <version>5.0.0-alpha5</version>
</dependency>
```

**Comment by jasontedor** [comment]
Thanks again. I pushed the following commits: 

- Master: cc2743743c90a117a64bb0c10d1e16e6e1a7e864
- 5.x: 7a9c6243d2070aa8589abb208dce96413bfb60e1
- 5.0: 922b96f16b30ee26d9217eeeec0ef825eb47d2fc

**Comment by agebhar1** [comment]
;)
