### ISSUE TITLE
A node information display has gone

### ISSUE THREAD

**Issue by nevermore424** [elastic/elasticsearch#21422]
my cluster has four nodes , I have installed marvel plugin.at first,i can see all  the node information,but when i restart my cluster.one of a node information display has gone...

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/ (and provide a lot more info than you've provided above).

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by nevermore424** [comment]
ok
