### ISSUE TITLE
Upgrade ICU Plugin to latest available in Lucene

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#21425]
The ICU plugin currently uses ICU 54.1, while Lucene is on v56.1 and plans to upgrade to v58.1 (https://issues.apache.org/jira/browse/LUCENE-7540)

We should upgrade to the latest available in Lucene for 6.0.

Relates to https://github.com/elastic/elasticsearch/issues/21352

**Comment by jimczi** [comment]
Note that the ICU plugin now uses v56.1:
https://github.com/elastic/elasticsearch/pull/24821

This is the version tested by Lucene but not the latest available:
https://issues.apache.org/jira/browse/LUCENE-7540

**Comment by jimczi** [comment]
Lucene master uses the latest version now (59.1) so we'll have to upgrade the ES plugin too when we upgrade to a new snapshot.
