### ISSUE TITLE
sending elasticsearch logs to logstash fails due to security manager

### ISSUE THREAD

**Issue by gehel** [elastic/elasticsearch#21428]
**Elasticsearch version**: 2.4.1

**Plugins installed**: [experimental-highlighter,extra,analysis-icu]

**JVM version**: OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-0ubuntu0.14.04.3)

**OS version**: Ubuntu Trusty (14.04)

**Description of the problem including expected versus actual behavior**:

We are trying to send the logs of our elasticsearch search cluster to logstash with [logstash-gelf](https://github.com/mp911de/logstash-gelf) (yes, they are 2 different elasticsearch clusters). This fails due to security manager restrictions. I can't find the correct way to configure the security manager to allow logstash-gelf to send UDP packets. I tried following the [documentation I found](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-security.html) on security manager, but with no success.

The policy that I'm trying to use:

    grant codeBase "file:/usr/share/elasticsearch/lib/logstash-gelf.jar" {
      permission java.net.SocketPermission "localhost:0", "listen,resolve";
    };

**Steps to reproduce**:
 1. add the logstash-gelf jar to elasticsearch libs
 2. configure a gelf appender in logging configuration
 3. add a policy rule in /usr/share/elasticsearch/.java.policy (also tried to configure it by adding  `-Djava.security.policy=file:///...` to `ES_JAVA_OPTS`
 4. restart elasticsarch

expected: logs are sent to logstash

actual: no logs are sent to logstash and exception is seen on console (see below)

note: this used to work fine with elasticsearch 1.7.5

**Provide logs (if relevant)**:

```
log4j:ERROR Could not send GELF message: access denied ("java.net.SocketPermission" "localhost:0" "listen,resolve")
java.security.AccessControlException: access denied ("java.net.SocketPermission" "localhost:0" "listen,resolve")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:685)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkListen(SecurityManager.java:1134)
	at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:689)
	at sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:91)
	at biz.paluch.logging.gelf.intern.sender.GelfUDPSender.initiateChannel(GelfUDPSender.java:35)
	at biz.paluch.logging.gelf.intern.sender.GelfUDPSender.<init>(GelfUDPSender.java:28)
	at biz.paluch.logging.gelf.intern.sender.DefaultGelfSenderProvider.create(DefaultGelfSenderProvider.java:40)
	at biz.paluch.logging.gelf.intern.GelfSenderFactory.createSender(GelfSenderFactory.java:63)
	at biz.paluch.logging.gelf.intern.GelfSenderFactory.createSender(GelfSenderFactory.java:45)
	at biz.paluch.logging.gelf.log4j.GelfLogAppender.append(GelfLogAppender.java:95)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.elasticsearch.common.logging.log4j.Log4jESLogger.internalInfo(Log4jESLogger.java:120)
	at org.elasticsearch.common.logging.support.AbstractESLogger.info(AbstractESLogger.java:81)
	at org.elasticsearch.node.Node.<init>(Node.java:149)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

**Comment by jasontedor** [comment]
@gehel I'm very sorry, but I'm going to have to ask you for a more thorough reproduction here because this does not reproduce for me, and it surprises me that you're having trouble here. The reason that this is surprising to me is because the logging appenders would be configured because the security manager is installed.

My reproduction:

 - start a logging instance of Elasticsearch with the default config, a different cluster name, and specify http.port and transport.tcp.port: `--cluster.name=gelf --http.port=9201 --transport.tcp.port=9301`
 - start Logstash with `gelf` input and `elasticsearch` output: `-e 'input { gelf {} } output { elasticsearch { hosts => [ "127.0.0.1:9201" ] } }'`
 - start tcpdump against loopback interface and filter udp and port 12201
 - edit logging.yml with the following diff
```
3c3
< rootLogger: ${es.logger.level}, console, file, gelf
---
> rootLogger: ${es.logger.level}, console, file
38,49d37
<   gelf:
<     type: biz.paluch.logging.gelf.log4j.GelfLogAppender
<     Threshold: INFO
<     Host: udp:localhost
<     Port: 12201
<     Version: 1.1
<     Facility: elasticsearch
<     ExtractStackTrace: true
<     FilterStackTrace: true
<     MdcProfiling: false
<     TimestampPattern: yyyy-MM-dd HH:mm:ss,SSSS
<     MaximumMessageSize: 8192
```
 - start Elasticsearch pointing to this config

I can see packets in the tcpdump, and most importantly, I can see events hitting the logging instance of Elasticsearch:

```
[2016-11-09 12:14:18,155][INFO ][cluster.metadata         ] [Korvac] [logstash-2016.11.09] create_mapping [logs]
```

```
$ curl -XGET "localhost:9201/_search?size=1&pretty=1"
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "logstash-2016.11.09",
      "_type" : "logs",
      "_id" : "AVhKFUY6iHKVEXE6By2d",
      "_score" : 1.0,
      "_source" : {
        "host" : "jason-mbp.local",
        "level" : 6,
        "facility" : "elasticsearch",
        "@version" : "1",
        "@timestamp" : "2016-11-09T17:14:08.731Z",
        "source_host" : "127.0.0.1",
        "message" : "[Freakmaster] version[2.4.1], pid[26800], build[c67dc32/2016-09-27T18:57:55Z]",
        "LoggerName" : "node",
        "Server" : "jason-mbp.local",
        "SourceSimpleClassName" : "Node",
        "SourceClassName" : "org.elasticsearch.node.Node",
        "Time" : "2016-11-09 12:14:08,0731",
        "Severity" : "INFO",
        "SourceLineNumber" : 149,
        "Thread" : "main",
        "SourceMethodName" : "<init>"
      }
    } ]
  }
}
```

**Comment by gehel** [comment]
@jasontedor thanks for the quick answer! Strange that this works for you. If I understand correctly, you did not install any gelf specific security policy and it works?

I'm not sure what you mean by:
> The reason that this is surprising to me is because the logging appenders would be configured because the security manager is installed.

I'll see if I can find anything else problematic in our configuration, but I am not really sure where to look...

**Comment by jasontedor** [comment]
> If I understand correctly, you did not install any gelf specific security policy and it works?

This is correct, I did not, and I did not expect to have to.

>I'm not sure what you mean by:

>>The reason that this is surprising to me is because the logging appenders would be configured because the security manager is installed.

When the JVM starts, there is no security manager in place, we configure it after some initialization has occurred. It is only after the security manager is in place that permissions become relevant. In particular, logging is something that we configure before the security manager is in place, the appender will have been created and the socket opened already.

**Comment by gehel** [comment]
A quick look at the sources of logstash-gelf indicate that the DatagramChannel is created and connected at initialisation, not on the first message, so if elasticsearch does indeed configure security manager only after logging, what I'm seeing does not make sense. I assume this is true for elasticsearch 2.4.1?

I'll try to do a test on a fresh elasticsearch install and I'll see if can reproduce it there as well.

**Comment by jasontedor** [comment]
> if elasticsearch does indeed configure security manager only after logging

This is definitely the case.

> I assume this is true for elasticsearch 2.4.1?

Yes, and that's what I tested against (thank you for providing the version information in the initial report).

```
$ curl -XGET localhost:9200/
{
  "name" : "Sybil Dvorak",
  "cluster_name" : "elasticsearch_jason",
  "cluster_uuid" : "LsjwB5UySQmUjrHEqVUO-A",
  "version" : {
    "number" : "2.4.1",
    "build_hash" : "c67dc32e24162035d18d6fe1e952c4cbcbe79d16",
    "build_timestamp" : "2016-09-27T18:57:55Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}
```

> I'll try to do a test on a fresh elasticsearch install and I'll see if can reproduce it there as well.

Thanks.

**Comment by gehel** [comment]
It turns out that we are using a fairly old version of logstash-gelf (1.5.3) and not the latest and greatest 1.11.0. I can reproduce the problem in a fresh install and logstash-gelf 1.5.3, but not with 1.11.0

That does not entirely explain why the security manager gets in the way, but I suspect a later initialisation of the DatagramChannel in 1.5.3, but I have not checked.

Time to upgrade! Thanks @jasontedor for the help! I'm closing this as resolved.

**Comment by jasontedor** [comment]
You're welcome @gehel. Thanks for providing an easy means of reproducing, that gave me an opportunity to dig into your actual situation.

We [filter](https://github.com/elastic/elasticsearch/blob/a025c9c2eb1564033eb148a8d157ae70849b108c/core/src/main/java/org/elasticsearch/bootstrap/ESPolicy.java#L117) out the permission `permission java.net.SocketPermission "localhost:0", "listen"`. That's why you could not successfully grant it.

I'm sorry for the trouble, but I'm glad that you're able to proceed now.

**Comment by jasontedor** [comment]
The logstash-gelf appender change that obviated this issue is mp911de/logstash-gelf@89d384055cc958627a7e72d92b10119409cc8fe9. Prior to that, the UDP sender would be initialized on the first log message, which would be after we had installed the security manager.

**Comment by gehel** [comment]
@jasontedor Thanks for digging into this! That was my intuition, but I did not actually take the time to find the commit and validate the theory. Great!
