### ISSUE TITLE
How to run elasticsearch using elasticsearch-docker.yml version 2 yml

### ISSUE THREAD

**Issue by DhairyashilBhosale** [elastic/elasticsearch#21433]
Hi I am beginner in elasticsearch, I am trying to run elasticsearch on ubuntu14.04 .

1) elasticsearch-docker.yml

  `

      version "2"
      services:  
        els:
          image: elasticsearch:latest
        ports:
          - "9200:9200"
          - "9300:9300"
        volumes:
          - "./config/elasticsearch.yml:/etc/elasticsearch/config/elasticsearch.yml"          
        #command: bash -c "service elasticsearch start" # Command is now working in version 2
        tty: true`

As per above yml file without '_command_' this is working, means without command it is pulling elastic search image if it is not there. `$ docker-compose up` working fine.
 
`$ docker pa -a `
`
    CONTAINER ID     COMMAND               CREATED   STATUS      PORTS 
     b5cb2s34d              elasticsearch:latest   10 sec          up              0.0.0.0:9200-->9200/tcp,            
        0.0.0.0:9300-->9300/tcp                    
`
It showing all port forwarding is working fine. 
I didn't modified or made changes in **/config/elasticsearch.yml**

but while testing it not working:
_http://localhost:9200_ or using _curl_

Its not working because elasticsearch service is not running inside docker container but whenever I  coment out `command` tag in docker-compose.yml file i.e. `command: bash -c "service elasticsearch start"` then its set all port forwarding and up the container but service inside container i.e 'elasticsearch service' is not running. 
So how to Explicitly pass command  i.e. `command: bash -c "service elasticsearch start"` in docker-compose.yml

**so how to run only Elasticsearch by using docker-compose.yml using version 2****?**

Docker-compose version : 1.9
Docker version: 1.12

**Comment by jasontedor** [comment]
@DhairyashilBhosale We provide [images](https://www.elastic.co/blog/releasing-beta-version-of-elastic-docker-images) which includes a [sample docker-compose](https://gist.githubusercontent.com/dliappis/52de1f4bb10fd23f5b91ea5fcb5d2560/raw/260723cf8d496ed15a5dd4801a6e9cb616c9f3c3/docker-compose.yml) file. You can read more on the aforementioned link, or on our [dedicated repository](https://github.com/elastic/elasticsearch-docker).
