### ISSUE TITLE
java.lang.NoClassDefFoundError: org/elasticsearch/xpack/XPackPlugin

### ISSUE THREAD

**Issue by shivangshah** [elastic/elasticsearch#21435]
I followed the guide mentioned here https://www.elastic.co/guide/en/x-pack/current/api-java.html and all in all everything worked within the IDE. 

Our application is spring boot based, so we end up creating fat jars for deployment using prebuild maven plugins. The problem is, when we run the jar file we get the following error

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.elasticsearch.client.Client]: Factory method 'esClient' threw exception; nested exception is java.lang.NoClassDefFoundError: org/elasticsearch/xpack/XPackPlugin
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 41 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/elasticsearch/xpack/XPackPlugin
	at org.elasticsearch.xpack.client.PreBuiltXPackTransportClient.<init>(PreBuiltXPackTransportClient.java:50)
	at org.elasticsearch.xpack.client.PreBuiltXPackTransportClient.<init>(PreBuiltXPackTransportClient.java:46)
```
Here's the dependencies we added:
```
 <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>x-pack-transport</artifactId>
            <version>5.0.0</version>
        </dependency>
```

and here's the code we use to initialize the client (based on the discussion https://github.com/elastic/elasticsearch/issues/19903)
```
Node node = new PluginNode(settings);
        node.start();
        return node.client();
    }

    static class PluginNode extends Node {
        public PluginNode(Settings settings) {
            super(InternalSettingsPreparer.prepareEnvironment(settings, null), Collections.singletonList(Netty4Plugin.class));
        }
    }
```
also, once in a while we get this in our CI builds as well
```
[35,35] cannot find symbol
[ERROR] symbol:   class Netty4Plugin
[ERROR] location: package org.elasticsearch.transport
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
```
which doesn't make sense because x-pack-transport by default includes the `transport` dependency as well 
```
[INFO] +- org.elasticsearch.client:x-pack-transport:jar:5.0.0:compile
[INFO] |  |  +- org.elasticsearch.client:rest:jar:5.0.0:compile
[INFO] |  |  \- org.elasticsearch.client:sniffer:jar:5.0.0:compile
[INFO] |  \- org.elasticsearch.client:transport:jar:5.0.0:compile
```

I see others are getting some compile time issues as well (on that thread). Is it possible that at runtime xpack transport client doesn't load the right classes?

**Comment by shivangshah** [comment]
Here is another follow up. 

We removed the `transport` dependency as `x-pack-transport` brings in `transport` dependency by itself and we started getting this compilation error.
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/scmbuild/.jenkins/workspace/ci-company-pr/src/main/java/com/company/config/SearchConfig.java:[35,35] cannot find symbol
  symbol:   class Netty4Plugin
  location: package org.elasticsearch.transport
[INFO] 1 error
```

There seems to be some mismatch of runtime (and apparently compile time as well) dependencies. Again, this does not happen on IDE.

**Comment by rjernst** [comment]
@shivangshah The transport client does not deal with any classloading. All of its dependencies should be on the classpath with the client jar itself. It sounds to me like whatever you are using to pull the client jar is not also pulling transitive dependencies (at least that is what the second error you show makes me think). Missing XPackPlugin at runtime seems would seem you are missing jars in the classpath (or rather the classloader you setup with spring).

This repo is reserved for bug fixes and feature requests for Elasticsearch core.  The best place to ask questions like these is in the forums: https:/discuss.elastic.co/c/x-pack

**Comment by shivangshah** [comment]
@rjernst thanks for the reply, I will look into this. I looked at both the jar files (local vs CI) and seems like the one from the CI (the one that giving the above error) is actually missing `x-pack-api-5.0.0.jar` for some reason. So you are probably right, it's not pulling transitive dependencies. Thanks for the insight !

**Comment by igaidai4uk** [comment]
@shivangshah have you figured the issue? I am having the same.
Thanks.

**Comment by shivangshah** [comment]
@igaidai4uk is your application spring boot based? Are the dependencies being pulled through a proxy (such as nexus?). If so, this is actually a nexus issue. Turned out that the repository proxy setting in nexus for `artifacts.elastic.co` doesn't work correctly for some reason (we actually need to reach out to elastic support for this, but haven't done that yet) and because of that the `x-pack-transport` transitive dependencies are not downloaded. Now because these classes are loaded at runtime, you will not see compilation issues during maven builds/package. You will only see it when you run the application. 

I figured this out by `jar xvf` my actual working spring boot jar with a non working spring boot jar and looked at the lib folder manually, comparing all the jar files. Turns out `x-pack-transport`'s all transitive dependencies were missing. 

I hope this helps.

**Comment by deepak-bala** [comment]
For those looking at this thread now, the reason this happens is because of this.

```
[WARNING] The POM for org.elasticsearch.plugin:x-pack-api:jar:5.1.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
```

Both the `x-pack-transport-5.1.2.pom` and `x-pack-api-5.1.2.pom` files from the ES repo have duplicate `licenses` and `developers` XML tags. Remove these tags locally and the transitive dependencies will be downloaded. You'll need to get maven to re-import the jars once you edit these pom files.

The following exceptions can occur if these dependencies are not present

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.elasticsearch.client.Client]: Factory method 'esClient' threw exception; nested exception is java.lang.NoClassDefFoundError: org/elasticsearch/xpack/XPackPlugin
```

```
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.unboundid.util.Debug

```

Related threads in discuss.elastic.co

https://discuss.elastic.co/t/error-xpack-class-not-found-exception-in-java/65168/5
https://discuss.elastic.co/t/how-to-set-up-elastic-maven-reposiroty/68986
