### ISSUE TITLE
Accent search bringing different results on ES 5.0 (compared to ES 2.4)

### ISSUE THREAD

**Issue by evertramos** [elastic/elasticsearch#21437]
**Elasticsearch version**: 5.0

**Plugins installed**: [ingest-attachment]

**JVM version**: OpenJDK version "1.8.0_102"

**OS version**: boot2docker and Ubuntu 14.0 (docker version of elasticsearch 5.0 container)

**Description of the problem including expected versus actual behavior**: 

On the last version of ES (2.4) when using a *brazilian analizer* it would bring all results for an specific query which has accent, example: 

If I search "prodigo" it would bring the result for two words "prodigo" and "pr**ó**digo" (with accent).

On ES 5.0 it does not bring the same result, if you type "prodigo" only query for "prodigo".

Here is my configurations:

```
// On ES 2.4
"properties": {
    "field1": {
        "type": "string",
        "analyzer": "brazilian"
    }
}
```
````
// On ES 5.0
"properties": {
    "field1": {
        "type": "text",
        "analyzer": "brazilian"
    }
}
````

I have tried to use *ascifolding* as of below, without success:
````
"analyzer": {
    "brazilian": {
        "tokenizer": "standard",
        "filter": {
            "standard",
            "lowercase",
            "asciifolding"
        }
    }
}
````

When quering the _analyzer *brazilian* on both my servers, production (ES 2.4) and development (ES 5.0), it brings the same result, as below:

````
// Query on /index/_analyze
{
	"analyzer": "brazilian",
	"text": "prodigo",
	"explain": true
}

// Results:
{
  "detail": {
    "custom_analyzer": false,
    "analyzer": {
      "name": "brazilian",
      "tokens": [
        {
          "token": "prodig",
          "start_offset": 0,
          "end_offset": 7,
          "type": "<ALPHANUM>",
          "position": 0,
          "bytes": "[70 72 6f 64 69 67]",
          "keyword": false,
          "positionLength": 1
        }
      ]
    }
  }
}
````

Not sure if this is a bug or even enough information, so please let me know if I could improve this issue, or if it is one.

Thanks!

**Comment by dadoonet** [comment]
I think you have a problem somewhere as I can not reproduce your problem:

```
DELETE test
PUT test
{
  "settings": {
    "analysis": {
      "analyzer": {
        "brazilian": {
          "tokenizer": "standard",
          "filter": [
            "standard",
            "lowercase",
            "asciifolding"
          ]
        }
      }
    }
  },
  "mappings": {
    "type": {
      "properties": {
        "foo": {
          "type": "text",
          "analyzer": "brazilian"
        }
      }
    }
  }
}
PUT test/type/1
{
  "foo": "prodigo"
}
PUT test/type/2
{
  "foo": "pródigo"
}
GET test/type/_search
{
  "query": {
    "match": {
      "foo": "prodigo"
    }
  }
}
```

I suggest you ask on discuss.elastic.co as a next step as we prefer to keep discussion there and only open issues when confirmed on discuss first.

**Comment by clintongormley** [comment]
This is a new index?  It may be related to the change from TF/IDF to BM25 as the default similarity

**Comment by evertramos** [comment]
@dadoonet thanks for your reply. I just download a new version of elasticsearch image from http://hub.docker.com and your example did not work... so, we are probably working on different versions of ES5.

I am using this version of ES 5:
````
{
  "name" : "zy-7EZA",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "TQDmG1KYRUqIFSvydSIrCg",
  "version" : {
    "number" : "5.0.0",
    "build_hash" : "253032b",
    "build_date" : "2016-10-26T05:11:34.737Z",
    "build_snapshot" : false,
    "lucene_version" : "6.2.0"
  },
  "tagline" : "You Know, for Search"
}
````

@clintongormley thanks for you reply. It is a new index, I do not know TF/IDF or BM25, is there a way I can change it and try that out on my side?

I have opened a [discuss](https://discuss.elastic.co/t/accent-issue-on-search-es-5-0/65500).

**Comment by dadoonet** [comment]
I'm used 

```
[PQ1p7Sk] version[5.0.0], pid[30895], build[253032b/2016-10-26T04:37:51.531Z], OS[Mac OS X/10.11.6/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_60/25.60-b23]
```

Which is the same build. Strange you are seeing a different behavior.

**Comment by clintongormley** [comment]
I have confirmed that @dadoonet's example works on 5.0.0, and I've confirmed that the `brazilian` analyzer removes the accent correctly, as it did in 2.4.0.

I've also confirmed that an index created in 2.4.0 continues to work correctly after upgrading to 5.0.0:

```
PUT t
{
  "mappings": {
    "t": {
      "properties": {
        "foo": {
          "type": "string",
          "analyzer": "brazilian"
        }
      }
    }
  }
}

PUT t/t/1
{
  "foo": "prodigo"
}

PUT t/t/2
{
  "foo": "pródigo"
}

GET t/_search
{
  "query": {
    "match": {
      "foo": "prodigo"
    }
  }
}

GET t/_search
{
  "query": {
    "match": {
      "foo": "pródigo"
    }
  }
}

```

Rerun the searches after upgrading to 5.0.0 - continues to work.

**Comment by evertramos** [comment]
I found what is the problem and not sure if it is an issue... if you use the field name on the search it will bring the result accordingly, but in my case, the content was attached from a pdf file and some how is not bringing the same result:

````
//query: GET /test/_search?q=foo:prodigo
{
  "took": 12,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": 0.2876821,
    "hits": [
      {
        "_index": "test",
        "_type": "type",
        "_id": "2",
        "_score": 0.2876821,
        "_source": {
          "foo": "prodigo"
        }
      },
      {
        "_index": "test",
        "_type": "type",
        "_id": "1",
        "_score": 0.2876821,
        "_source": {
          "foo": "pródigo"
        }
      }
    ]
  }
}
````

````
//query: GET /test/_search?q=prodigo
{
  "took": 11,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": 0.2876821,
    "hits": [
      {
        "_index": "test",
        "_type": "type",
        "_id": "_search",
        "_score": 0.2876821,
        "_source": {
          "query": {
            "match": {
              "foo": "prodigo"
            }
          }
        }
      },
      {
        "_index": "test",
        "_type": "type",
        "_id": "2",
        "_score": 0.2876821,
        "_source": {
          "foo": "prodigo"
        }
      }
    ]
  }
}
````

Please confirm that you can reproduce that. 

Also, in my case here is the situation of my indexed file:

````
{
        "_index": "wikisearch",
        "_type": "docs",
        "_id": "AVhNuYD3iuM0uPNBmtcQ",
        "_score": 0.3656123,
        "_source": {
          "editor": "FEB",
          "attachment": {
            "date": "2004-09-16T15:25:26Z",
            "content_type": "application/pdf",
            "language": "pt",
            "content": "pródigo",
            "content_length": 935904
          },
          "content": "JVBERi0xLjYNJeLjz....."
}
````

Even trying to search with **attachment.content:prodigo** it´s not bringing the expected result (pródigo).

Let me know if it is an issue or if we keep that under discussion.

**Comment by clintongormley** [comment]
The `_all` field uses the `standard` analyzer, not the `brazilian` analyzer.

**Comment by evertramos** [comment]
@clintongormley even using the *attachement.content* it´s not bringing it up... here is the processor I am using it:

````
{
    "description": "Extract attachment information",
    "processors": {
        {
            "attachment": {
                "field": "content",
                "indexed_chars": -1
            }                        
        },
    }
}
````

Do I need to tell this processor to use *Brazilian* filter? If so, how do I do it?

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
