### ISSUE TITLE
_reindex and random_score query don't play nice

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#21432]
Some [folks](https://discuss.elastic.co/t/-reindex-and-a-random-score-query/50198/4) are trying to use size and `random_score` to take a random subset of a source index into a target index but they aren't getting random sorting. I expect this is because `_reindex` defaults to sorting by `_doc` and we need to fix the sorting for it to work. It might be a bug but I'm expecting there is a "right" way to make reindex do the random sorting and we need to document it.

**Comment by clintongormley** [comment]
@nik9000 isn't it just about specifying `sort: _score` if you want to enable that?

**Comment by avencar** [comment]
@clintongormley I've tried that and still no luck.

**Comment by nik9000** [comment]
> @nik9000 isn't it just about specifying sort: _score if you want to enable that?

I suspect so. I'll try and get it working locally soon and make an example in the reindex docs. If not, well, I'll fix it.

**Comment by nik9000** [comment]
This works for me:
```
curl -XDELETE localhost:9200/test
for i in $(seq 1 1000); do
  curl -XPOST localhost:9200/test/test -d'{"test": "test"}'; echo
done
curl localhost:9200/_refresh?pretty
  
for i in $(seq 1 50); do
  curl -XPOST localhost:9200/_reindex?filter_path=created,updated -d'{
    "size": 10,
    "source": {
      "index": "test",
      "query": {
        "function_score" : {
          "query" : { "match_all": {} },
          "random_score" : {}
        }
      },
      "sort": "_score"
    },
    "dest": {
      "index": "random-1"
    }
  }'
  curl localhost:9200/_refresh

  curl 'localhost:9200/random-1/_search?size=0&filter_path=hits.total'; echo
done
```

**Comment by nik9000** [comment]
The second loop selects more and more random documents.

I'll push an update to the docs and close this.

**Comment by avencar** [comment]
I ran your script and it still didn't work for me. I should mention we're running an older version of elasticsearch (2.3.4). I end up with 20 documents in the random-1 index. It seems like it possibly worked correctly the first few iterations of reindex (10 new, 4 new, 6 new) but the next 47 iterations produced documents already in previous set of 20. Not as random as I would expect.

**Comment by nik9000** [comment]
Master: eeb6602c985aacb09fb679db6b0557ba9b901c5f
5.x: adc794781a68a36d057ffacd1c2a9a196824bc73
5.0: d24bd5de1e03f6232cbced36c5551cfc8376e760

**Comment by nik9000** [comment]
> I ran your script and it still didn't work for me. I should mention we're running an older version of elasticsearch (2.3.4).

I just tried it on 2.3.4 and it looks like it doesn't work there. I don't think it is particularly likely we'll fix it in 2.x though.
