### ISSUE TITLE
ES & Kibana 5.0 - Visualizations, Discovery, Dashboards do not work on restoring snapshot made on ES 2.4.0

### ISSUE THREAD

**Issue by singh-akash** [elastic/elasticsearch#21450]
I restored a snapshot which was created on Elasticsearch 2.4.0 & Kibana 4.5.4. When I restore this snapshot on Elasticsearch 5.0, Elasticsearch data is restored correctly, but Kibana visualizations are not displayed. I get the following error on browser console:

commons.bundle.js?v=14438:38 Error: IndexPattern's configured pattern does not match any indices
at handleMissingIndexPattern (kibana.bundle.js?v=14438:26)
at processQueue (commons.bundle.js?v=14438:38)
at commons.bundle.js?v=14438:38
at Scope.$eval (commons.bundle.js?v=14438:39)
at Scope.$digest (commons.bundle.js?v=14438:39)
at Scope.$apply (commons.bundle.js?v=14438:39)
at done (commons.bundle.js?v=14438:37)
at completeRequest (commons.bundle.js?v=14438:37)
at XMLHttpRequest.xhr.onload (commons.bundle.js?v=14438:37)

It does work when I delete .kibana index and restart kibana, but all my visualizations are lost. Can you help me out with this? Thanks.

**Comment by dakrone** [comment]
Hi,
We reserve Github issues for feature requests and bug reports. If you are having problems please use https://discuss.elastic.co instead!

In your case, this is a Kibana issue, so please start a discussion here: https://discuss.elastic.co/c/kibana

**Comment by singh-akash** [comment]
I have posted on the forum and didn't get a response. I will await a response on forum then. Sorry for the trouble.

The link to the post is: https://discuss.elastic.co/t/discover-and-visualization-page-not-working-on-snapshot-restore/65278

**Comment by singh-akash** [comment]
Should I start a discussion on Kibana link https://discuss.elastic.co/c/kibana as well? Given that I have already made a post earlier?

**Comment by dakrone** [comment]
Since you already have a post, I wouldn't start another one until the first one gets older

**Comment by singh-akash** [comment]
Ok I will await feedback on the post then. Thanks for your help.

Regards,
Akash Singh
