### ISSUE TITLE
bin is not a recognized command.

### ISSUE THREAD

**Issue by azizsagi** [elastic/elasticsearch#21459]
Hi,
      I have successfully installed elasticsearch in windows server 2012. But now I can't install x-pack. I have found the following command 

bin/elasticsearch-plugin install x-pack

here on https://www.elastic.co/start

and my elasticsearch version is 5.0. 

**Error is
bin is not recognized as an internal or extgernal command.**

c:\elasticsearch\elasticsearch-5.0.0 is the path

Please assist me.

**Elasticsearch version**:

**Plugins installed**: []

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by dadoonet** [comment]
Please ask your questions on discuss.elastic.co. We can help there.

try:

```
cd bin
elasticsearch
```
