### ISSUE TITLE
Illegal User Settings while updating clusters

### ISSUE THREAD

**Issue by sudhir7474** [elastic/elasticsearch#21455]
Hi I am getting an illegal User Settings error while updating user settings.

I am using Elasticsearch 2.4.1 when i have updated user settings and click on Update getting an error saying Illegal User Settings. I am trying to update SMTP settings

Below is the configuration I am trying to update
watcher.actions.email.service.account:
  gmail_account:
    profile: gmail
    smtp:
      auth: true
      starttls.enable: true
      host: smtp.gmail.com
      port: 587
      user: _username_
      password: _password_

Error message is as below:

{
    "msg": "Illegal user settings", 
    "ok": false, 
    "detail": {
        "errors": [
            "'watcher.actions.email.service.account.gmail_account.smtp.host': is not allowed", 
            "'watcher.actions.email.service.account.gmail_account.profile': is not allowed", 
            "'watcher.actions.email.service.account.gmail_account.smtp.port': is not allowed", 
            "'watcher.actions.email.service.account.gmail_account.smtp.user': is not allowed", 
            "'watcher.actions.email.service.account.gmail_account.smtp.password': is not allowed", 
            "'watcher.actions.email.service.account.gmail_account.smtp.auth': is not allowed", 
            "'watcher.actions.email.service.account.gmail_account.smtp.starttls.enable': is not allowed"
        ]
    }, 
    "error": "BadRequest"
}

**Comment by dadoonet** [comment]
They have been renamed. Look at xpack doc.
If you need help please ask on discuss.elastic.co

**Comment by clintongormley** [comment]
Also, take a look at the migration assistant, which would have alerted you to these changes: https://github.com/elastic/elasticsearch-migration/
