### ISSUE TITLE
Tests: UpdateSettingsIT.testUpdateAutoThrottleSettings failed

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#21461]
**Elasticsearch version**: master branch

The following test failed, non reproducable, on CI. Link is [here](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/262/console).

What stands out, is the following error message:

```
[UpdateSettingsIT#testUpdateAutoThrottleSettings]: cleaned up after test
FAILURE 0.17s J2 | UpdateSettingsIT.testUpdateAutoThrottleSettings <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: an empty collection
   >      but: <[Attempted to append to non-started appender testUpdateAutoThrottleSettings]>
   > 	at __randomizedtesting.SeedInfo.seed([A2A85E1799BF25C7:F06B7EEB53063DD5]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:279)
   > 	at org.elasticsearch.test.ESTestCase.ensureCleanedUp(ESTestCase.java:244)
   > 	at java.lang.Thread.run(Thread.java:745)
```

The test itself starts its own MockAppender at the beginning:

```
    public void testUpdateAutoThrottleSettings() throws IllegalAccessException {
        MockAppender mockAppender = new MockAppender("testUpdateAutoThrottleSettings");
        mockAppender.start();
        Logger rootLogger = LogManager.getRootLogger();
        Level savedLevel = rootLogger.getLevel();
        Loggers.addAppender(rootLogger, mockAppender);
        Loggers.setLevel(rootLogger, Level.TRACE);
       
       ....
```

So, even though the mock appender is started, it seems as if somehow a component did not get notified about this. I dont know enough about log4j2, if there might be an issue - or I am maybe locking at the wrong things.

**Comment by spinscale** [comment]
@jasontedor any idea on this one?

**Comment by jasontedor** [comment]
I'll take a look, thanks @spinscale.

**Comment by imotov** [comment]
It looks like there are similar failures in another test in this suite:
```
1> [2016-11-11T12:18:48,093][INFO ][o.e.i.s.UpdateSettingsIT ] [UpdateSettingsIT#testUpdateMergeMaxThreadCount]: cleaned up after test
FAILURE 0.22s J0 | UpdateSettingsIT.testUpdateMergeMaxThreadCount <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: an empty collection
   >      but: <[Attempted to append to non-started appender testUpdateMergeMaxThreadCount]>
   > 	at __randomizedtesting.SeedInfo.seed([12EFA62A6A1DA08C:7C24A0F5DF787B40]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:279)
   > 	at org.elasticsearch.test.ESTestCase.ensureCleanedUp(ESTestCase.java:244)
   > 	at java.lang.Thread.run(Thread.java:745)
```
See an example [here](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=sles/233/consoleFull)

**Comment by jasontedor** [comment]
I took a look at this this afternoon. I do not immediately see what is going on, and the failures do not reproduce. My only theory is that the appender is not always successfully getting removed, and since we call stop on it, an append in a later test is tripping the assertion.

For now I have pushed commits so that there is an actual stack trace to look at when the offending append is made:
 - master: 9352d166024435a1f0465e73c227083e18efbd85
 - 5.x: da5af7d1f52261af0ded4d901648b7faa7022053
 - 5.0: 5ff7438c1611513c1599fd5bd9b01e2cb5e66709

**Comment by jasontedor** [comment]
Okay, the stack trace gave a clue as to what is going on here. There is a race condition. We submit a cluster state update, and the test proceeds after the master processes this cluster state update. At the end of the test, we remove the mock appender, and stop it. If the master has processed the cluster state update, but still has a log message to write, we can blow up. Namely:
 - master attempts to log `logger.debug("processing [{}]: took [{}] done applying updated cluster_state (version: {}, uuid: {})", tasksSummary,
                executionTime, newClusterState.version(), newClusterState.stateUUID());`
 - Log4j grabs a reference to the current appenders, which includes the mock appender
 - the finally statement in the test removes the mock appender, and stops it
 - Log4j iterates over the appenders, using the reference it previously grabbed, this will still include the mock appender, which is now stopped
 - :boom:

I will think about a fix.
