### ISSUE TITLE
Multi-cluster search, GET, and field_stats

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#21473]
# Background
The tribe node today joins a list of clusters and merges their cluster state into a single overall view.  Because it knows about the location of every shard in its clusters, it can scatter requests out to all involved shards then gathers and reduces the shard level results.

This approach has some downsides: joining many clusters can result in a very large merged cluster state, indices with the same name in different clusters can't be searched, and any master-level actions (eg creating an index) just hangs because there is no master.

While, no doubt, there are some users who use the tribe node to write to indices in different clusters, by far the majority use for tribe is to perform searches and aggregations across multiple clusters.

# Proposal

Allow a cluster to to perform searches on external clusters, and to merge their results with results from the local cluster.

The main cluster would be provided with a list of cluster names and the publish addresses of some nodes in the cluster (could use these as a static round-robin list or as seed nodes for sniffing).  This list would be dynamically updatable, so clusters could be added or removed at will.

By default, the search API would work as it does today ,eg the following command would search all local indices only:

    GET */_search 

However, indices can be preceded by a cluster name and a colon to perform searches on remote clusters eg the following would search all indices beginning with `logs` in the local, `europe`, and `asia` clusters:

    GET logs*,europe:logs*,asia:logs*/_search

The local cluster would forward search requests to the remote clusters and treat the results in the same way as it would the results from a single shard, which can be merged with the results from local shards and the other remote clusters into a single global result set.

Hits could be returned as:

    "index": "europe:logs-2016.11.10"

Pipeline aggregations would have to be removed from the aggs sent to remote clusters, and only applied on the coordinating node after results have been merged.

We would also need an API which can list known clusters and their indices (eg for Kibana) and the GET and field-stats APIs should be made multi-cluster aware as well.

This would be a read-only integration.  Any writes (including creating an index) would happen in the local cluster only.

**Comment by javanna** [comment]
> We would also need an API which can list known clusters and their indices (eg for Kibana) and the GET and field-stats APIs should be made multi-cluster aware as well.

Would that mean that the local cluster just needs to proxy those requests to the remote one(s)?

**Comment by clintongormley** [comment]
@javanna yes
