### ISSUE TITLE
'Run_as' x-pack feature cannot handle multithreading / parallel connections for non-builtin users

### ISSUE THREAD

**Issue by nktl** [elastic/elasticsearch#21472]
When using run_as feature (**es-security-runas-user** header), authentication randomly fails with 40X when requests are running in parallel.

To replicate:

1. No 'run_as' used, just regular basic auth using 'native' impersonator user (10 concurrent threads):
`ab -c 10 -n 2000 -A impersonator:somepass http://localhost:9200/`

All good:

```
Complete requests:      2000
Failed requests:        0   
Write errors:           0   
```

2. 'Run_as' used, trying to impersonate 'builtin' elastic user (10 threads too):
`ab -c 10 -n 2000 -H 'es-security-runas-user: elastic' -A impersonator:somepass http://localhost:9200/`

Still good:

```
Complete requests:      2000
Failed requests:        0   
Write errors:           0   
```

3. 'Run_as' used, trying to impersonate 'non-builtin' user (10 threads too):

`ab -c 10 -n 2000 -H 'es-security-runas-user: somenativeuser' -A impersonator:somepass http://localhost:9200/`

```
Complete requests:      2000
Failed requests:        137 
Write errors:           0   
Non-2xx responses:      137 
```

Some of the responses fail with 401 in such case. This happens for **both users from native and ldap realms.**

**HOWEVER:**

4.  'Run_as' used, trying to impersonate 'non-builtin' user (**single thread only**):

`ab -c 1 -n 2000 -H 'es-security-runas-user: somenativeuser' -A impersonator:somepass 

```
Complete requests:      2000
Failed requests:        0
Write errors:           0
```

So single thread test runs OK.

It looks like something bad happens when **run_as** feature has to do parallel lookups on the (not builtin) user  - the process does not scale to multiple threads very well.

**Comment by clintongormley** [comment]
Hi @nktl 

What version of Elasticsearch are you using?

**Comment by nktl** [comment]
Forgot to mention  - this is on ES 5.0

**Comment by clintongormley** [comment]
thanks @nktl - looking into it

**Comment by colings86** [comment]
Since this is an issue relating to x-pack I have raised an issue in our internal bug tracker for X-Pack. I will close this issue here as the issue does not directly relate to Elasticsearch. Thank you for reporting the issue.
