### ISSUE TITLE
Accent search over ingest attachment processor not working properly with brazilian filter [ES 5.0]

### ISSUE THREAD

**Issue by evertramos** [elastic/elasticsearch#21486]
**Elasticsearch version**: 5.0

**Plugins installed**: [ingest-attachment]

**JVM version**: OpenJDK version "1.8.0_102"

**OS version**: boot2docker and Ubuntu 14.0 (docker version of elasticsearch 5.0 container)

**Description of the problem including expected versus actual behavior**: 

After ingesting a PDF file with ingest-attachment plugin, using *brazilian* filter, the query (_search) does not bring the results as it should be, when using words with *accents* (as of the brazilian portuguese word "prodigo" which should bring all records as "pródigo", as well).

If we use regular indexing, by regular I mean without processors, it does work perfectly as of [mentioned in this issue.](https://github.com/elastic/elasticsearch/issues/21437)

But, the real issue is when you ingest a file through ingest-attachment, the filter used on the index field property does not respond properly.

As we can see and prove on the test below:

````
// PUT /i (Create Index)
{
    "mappings" : {
        "docs" : {
            "properties" : {
                "name" : { 
                	"type" : "text",
                	"analyzer" : "brazilian"
            	},
                "content" : { 
                	"type" : "text",
                	"analyzer" : "brazilian"
            	}
            }
        }
    }
}

// PUT /_ingest/pipeline/attachment (Create Pipeline)
{
  "description" : "Extract attachment information",
  "processors" : [
    {
      "attachment" : {
        "field" : "content",
        "indexed_chars" : -1
      }
    }
  ]
}

// POST /i/docs/1 (Index file 1)
{
	"name": "file1"
}

// POST /i/docs/2 (Index file 2)
{
	"name": "file2"
}

// PUT /i/docs/1?pipeline=attachment (Ingest file1 base62 encoded with word "pródigo")
{
  "content": "ZmlsaG8gcHLDs2RpZ28="
}

// PUT /i/docs/2?pipeline=attachment (Ingest file2 base62 encoded with word  "prodigo")
{
  "content": "ZmlsaG8gcHJvZGlnbw=="
}
````

After the environment set we can query and see the results:
````
// GET i/_search?q=attachment.content:prodigo (Results to:)
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 0.25811607,
    "hits": [
      {
        "_index": "i",
        "_type": "docs",
        "_id": "2",
        "_score": 0.25811607,
        "_source": {
          "attachment": {
            "content_type": "text/plain; charset=ISO-8859-1",
            "language": "sk",
            "content": "filho prodigo",
            "content_length": 14
          },
          "content": "ZmlsaG8gcHJvZGlnbw=="
        }
      }
    ]
  }
}

// GET /i/_search?q=attachment.content:pródigo (Results to:)
{
  "took": 12,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 0.25811607,
    "hits": [
      {
        "_index": "i",
        "_type": "docs",
        "_id": "1",
        "_score": 0.25811607,
        "_source": {
          "attachment": {
            "content_type": "text/plain; charset=UTF-8",
            "language": "sk",
            "content": "filho pródigo",
            "content_length": 14
          },
          "content": "ZmlsaG8gcHLDs2RpZ28="
        }
      }
    ]
  }
}
````

Where we can see that when searching the same term with or without accent the query it is not bringing the expected result which should be both files for any of the queries above mentioned.

P.S.: Please note that I mentioned PDF but used a small base64 enconded string in order to reduce size of text, but the results are the same.

**Comment by dadoonet** [comment]
You did not apply the analyzer to attachment.content field but to content field.
That's the reason it does work as you would expect.

**Comment by evertramos** [comment]
ok!

For future reference... we my mapping should be:

````
{
    "mappings" : {
        "docs" : {
            "properties" : {
            	"attachment.content" : {
            		"type": "text",
            		"analyzer" : "brazilian"
        	}
            }
        }
    }
}
````

Thanks!

**Comment by suzify** [comment]
@evertramos @dadoonet 

The mapping that you concluded with is exactly what I need! However, I don't know how to write it in such a way that would have the equivalent meaning and intention in C#/NEST. Does anyone have any insight on this? For more detail, I've included my ES discussion post: https://discuss.elastic.co/t/how-to-assign-index-search-analyzers-when-ingesting-attachments-es-5-0/70613

//////////
My autocomplete implementation of autocomplete worked in v2.3. But ever since the upgrade, I can't figure out how to apply index and search time analyzers to the attachment's content field for all ingested attachments like PDFs and so forth. Does anyone have an example or a pointer to getting me started? Thank you so much in advance!

I have followed the example listed under "The Future" in https://www.elastic.co/blog/the-future-of-attachments-for-elasticsearch-and-dotnet, and that's what I have so far. See below:

My NEST code:

1) Creating the index:
    var response = CreateIndex(_currentIndex, i => i
        .InitializeUsing(indexState)
        .Mappings(m => m
            .Map<Topic>(t => t
                .AutoMap()
                .AllField(all => all
                    .Enabled(false)
                )
                .Properties(p => p
                    .Object<Attachment>(a => a
                        .Name(n => n.Attachment)
                        .AutoMap()
                    )
                )
            )
        )
    );

2) Creating the pipeline for the attachment:
    IPutPipelineResponse response = PutPipeline("attachments", p => p
        .Description("Document attachment pipeline")
        .Processors(pr => pr
            .Attachment<Topic>(a => a
                .Field(f => f.Content)
                .TargetField(f => f.Attachment)
            )
            .Remove<Topic>(r => r
                .Field(f => f.Content)
            )
        )
    );

My mapping:
    {
      "es5" : {
        "aliases" : { },
        "mappings" : {
          "topic" : {
            "_all" : {
              "enabled" : false
            },
            "properties" : {
              "content" : {
                "type" : "text",
                "store" : true,
                "analyzer" : "autocomplete",
                "search_analyzer" : "search"
              },
              "delete" : {
                "type" : "boolean"
              },
              "file" : {
                "properties" : {
                  "author" : {
                    "type" : "text",
                    "fields" : {
                      "keyword" : {
                        "type" : "keyword",
                        "ignore_above" : 256
                      }
                    }
                  },
                  "content" : { **********I want to analyzers for this**********
                    "type" : "text",
                    "fields" : {
                      "keyword" : {
                        "type" : "keyword",
                        "ignore_above" : 256
                      }
                    }
                  },
                  "content_length" : {
                    "type" : "long"
                  },
                  "content_type" : {
                    "type" : "text",
                    "fields" : {
                      "keyword" : {
                        "type" : "keyword",
                        "ignore_above" : 256
                      }
                    }
                  },
                  "date" : {
                    "type" : "date"
                  },
                  "detect_language" : {
                    "type" : "boolean"
                  },
                  "indexed_chars" : {
                    "type" : "long"
                  },
                  "keywords" : {
                    "type" : "text",
                    "fields" : {
                      "keyword" : {
                        "type" : "keyword",
                        "ignore_above" : 256
                      }
                    }
                  },
                  "language" : {
                    "type" : "text",
                    "fields" : {
                      "keyword" : {
                        "type" : "keyword",
                        "ignore_above" : 256
                      }
                    }
                  },
                  "name" : {
                    "type" : "text",
                    "fields" : {
                      "keyword" : {
                        "type" : "keyword",
                        "ignore_above" : 256
                      }
                    }
                  },
                  "title" : {
                    "type" : "text",
                    "fields" : {
                      "keyword" : {
                        "type" : "keyword",
                        "ignore_above" : 256
                      }
                    }
                  }
                }
              },
              "hash_id" : {
                "type" : "text"
              },
              "path" : {
                "type" : "text"
              },
              "title" : {
                "type" : "text"
              }
            }
          }
        },
        "settings" : { ... }
      }
    }
//////////

Thank you in advance!

**Comment by clintongormley** [comment]
@suzify Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
