### ISSUE TITLE
Allow scientific notation in date queries (epoch millis format)

### ISSUE THREAD

**Issue by mpe85** [elastic/elasticsearch#21489]
When runnig a query against a date field, it is not possible to use a long value with scientific notation.

Sample Query:
{"range":{"updatedAt":{"gte":1.478789928E12}}}

Mapping:
"updatedAt": {
   "format": "strict_date_optional_time||epoch_millis",
   "store": true,
   "type": "date"
}

Parser Error:
{"type":"parse_exception","reason":"failed to parse date field [1.478789928E12] with format [strict_date_optional_time||epoch_millis]"}

Tested with Elasticsearch version 2.3.5 and 2.4.1

Using this format should be possible here, since JSON officially supports the scientific "E" notation in number values (see http://www.json.org)

**Comment by gsmet** [comment]
Found http://stackoverflow.com/questions/39540118/date-format-in-scientific-notation-es-v1-5-v2-3-incompatibility which is related to this.

**Comment by makeyang** [comment]
@jpountz  @gsmet I tried issue on 1.5.3 and it truns out that 1.5.3 still can't parse this query. below is the exception:
curl -XGET 'http://192.168.200.191:9815/test/_search' -d ' {"query" : {"term" : { "timestamp" : "1.473977633e+12"} } } '
{"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[0u8_F5w_S_OT8pbdpnk4iQ][test][0]: SearchParseException[[test][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [\n{\n\"query\" : {\n   \"term\" : { \"timestamp\" : \"1.473977633e+12\"}\n}\n}\n]]]; nested: ElasticsearchParseException[failed to parse date field [1.473977633e+12], tried both date format [dateOptionalTime||date_time], and timestamp number]; nested: IllegalArgumentException[Invalid format: \"1.473977633e+12\" is malformed at \".473977633e+12\"]; }]","status":400}

**Comment by makeyang** [comment]
@jpountz I tried on master code and failed below:
org.elasticsearch.common.joda.DateMathParser.parseDateTime(DateMathParser.java:209)
I'd like to fix it and can u give some guide about this?

**Comment by liketic** [comment]
Hi @jpountz @jasontedor Is this worth to contribute? Thanks in advance. 😄

**Comment by jpountz** [comment]
I was going to answer "yes" but the current code in master makes me think that it might be fixed already as `EpochTimeParser` seems to handle the case that the time is provided using scientific notation. Unless the issue occurs higher up in the stack.

**Comment by liketic** [comment]
@jpountz Thanks.

**Comment by cbuescher** [comment]
I just checked this with 6.x versions of elasticsearch and scientific notation seems to be supported now.
