### ISSUE TITLE
Implement IndicesRequest in RestoreSnapshotRequest

### ISSUE THREAD

**Issue by breml** [elastic/elasticsearch#21491]
**Describe the feature**:

The restore snapshot API does allow to select indices that should be restored the same way the create snapshot does. Unfortunately the `org.elasticsearch.action.admin.cluster.snapshots.restore.RestoreSnapshotRequest` does not implement the `org.elasticsearch.action.IndicesRequest.Replaceable` interface like `org.elasticsearch.action.admin.cluster.snapshots.create.CreateSnapshotRequest` does, although all needed methods are already present.

This prevents me currently from handling `RestoreSnapshotRequests` as `IndicesRequest`.

**Comment by javanna** [comment]
Closing this for the reason stated [here](https://github.com/elastic/elasticsearch/pull/21492#issuecomment-264141777).
