### ISSUE TITLE
Documentation for -b flag in PluginCli.java is missing

### ISSUE THREAD

**Issue by dwerder** [elastic/elasticsearch#21490]
Documentation is missing explaination for flag -b in elaticsearch-plugin in PluginCli.java

**Comment by clintongormley** [comment]
@dwerder would you like to send a PR?

**Comment by dwerder** [comment]
Sorry, but I am not a java coder and I also don't know if more flags/options are missing. Just wanted to give a hint.

**Comment by rjernst** [comment]
Documentation does exist, which should be printed when using the plugin command with `--help` (or not arguments at all):
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java#L175

**Comment by clintongormley** [comment]
I've opened a PR to document batch mode here: https://github.com/elastic/elasticsearch/pull/21700
