### ISSUE TITLE
MockDiskUsagesIT testRerouteOccursOnDiskPassingHighWatermark hangs on java9

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#21502]
This test hangs on master, 5.x and 5.0 builds on java 9 every few hours. 

One of the latest failures here - https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+java9-periodic/614/consoleFull

An example of it failing alone - https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.0+java9-periodic/577/console

**Comment by jasontedor** [comment]
For now the CI has been rolled back to a JDK 9 build for which this does not fail.
