### ISSUE TITLE
Failing assertion in ParentFieldSubFetchPhase

### ISSUE THREAD

**Issue by kbarrett** [elastic/elasticsearch#21503]
**Elasticsearch version**: 5.0.0

**Plugins installed**: []

**JVM version**:Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_65/25.65-b01

**OS version**:Linux/4.2.6-201.fc22.x86_64/amd64

**Description of the problem including expected versus actual behavior**: When running elasticsearch with assertions enabled, fetching inner_hits for a nested document inside a child document causes an assertion to fail.

**Steps to reproduce**:
1. Start Elasticsearch 5.0 with assertions enabled
2. Run [these sense commands](https://github.com/elastic/elasticsearch/files/586347/crash-repro-steps.txt)
3. The last one will fail

**Provide logs (if relevant)**:

**Comment by martijnvg** [comment]
Thanks @kbarrett! I've updated a pr with a fix #21522.
