### ISSUE TITLE
Map reduce and Orchestration feature/plugin for elasticsearch, is it a good idea?

### ISSUE THREAD

**Issue by raghu83sn** [elastic/elasticsearch#21513]
**Describe the feature**:
I started using scripted aggregations sometime back, i wanted to understand is it a good idea to 
a) Create a feature or plugin for elasticsearch to execute Map Reduce kind of jobs. using groovy or other scripts in scripted aggregation feature. There are lot of groovy, javascript, nodejs..... libraries for statistical operations, machine learning etc....
b) With Ability to create a sink to write the results in to another index or any other sink.
c) Also have a feature/plugin like Apache Oozie for orchestration of job flows(Nothing flow of set of sequential or parallel elasticsearch queries to be executed ).
d) Not sure, probably we can have dedicated coordinating nodes configurable, to run only MapReduce queries, by enabling some configuration in elasticsearch.yml. 
e) Store data of one query execution in memory to be utilised by next job in the job run flow(we can add a level of persistence between job runs) or to be written back to a sink(can be another ES index itself). 

is it a good idea or not, if not why ?

Thanks and Regards,
Raghu

**Comment by dadoonet** [comment]
Please ask questions on discuss.elastic.co.
This place is only for confirmed issues.

Thanks!
