### ISSUE TITLE
can not access kibana from host machine,just can access  localhost

### ISSUE THREAD

**Issue by becky-guo** [elastic/elasticsearch#21516]
now,I can access like this : curl http://localhost:5601 ,but I can't access  like  http://192.168.1.200:5601.

the firewall  is stoped.  is there something config I can set it ?

**Comment by jasontedor** [comment]
This repository is for Elasticsearch. You can get dedicated help for Kibana on the [Elastic Discourse forum](https://discuss.elastic.co) or on the [Kibana repository](https://github.com/elastic/kibana). You might want to check the docs on [configuring](https://www.elastic.co/guide/en/kibana/current/settings.html) Kibana too.
