### ISSUE TITLE
Shard allocation same host based on hostname only

### ISSUE THREAD

**Issue by juntezhang** [elastic/elasticsearch#21528]
**Shard allocation same host based on hostname only**:

I want to make sure the primary shards are at least in 1 rack. 
I want to make sure the same primary and replica shards are not in the same zone.
Also see this thread here: https://discuss.elastic.co/t/shard-awareness-multiple-awareness-attributes/65506/4

There is a cluster level shard allocation setting 
> cluster.routing.allocation.same_shard.host 

It allows to perform a check to prevent allocation of multiple instances of the same shard on a single host, based on host name and host address.

It would be really useful if the check can also be performed when the host (node) name is the same while the addresses are different. For example:
> cluster.routing.allocation.same_shard.hostname

**Comment by ywelsch** [comment]
The logic currently allows either IP or hostname to match (there is no need for both to match - see also discussion in #11490)
