### ISSUE TITLE
Painless lambdas can only be arguments

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#21521]
It looks like in Painless lambdas (like `a -> a.toString()`) can only be function arguments. They can't be assigned to variables or returned from functions and stuff. This isn't a huge limitation but it does prevent things like writing a function that returns a behavior based on an argument. I don't think this is a super high priority but it is a limitation I didn't expect coming from java.

**Comment by jdconrad** [comment]
This is working as expected.  Handling lambdas as first-class citizens with a def type proved to be too complex for the benefit.  Lambdas really are just sugar, so I would hope that a user will be able to come up with a work around if they need something this complex in a script.

**Comment by s1monw** [comment]
I agree with @jdconrad  that there is quite some complexity here. I also think we don't have enough data-points in terms of user feedback if this is really needed and if there are situations were we can't work around. I will close this for now and suggest revisit this in a year from now with more infos / experience. if you feel very strongly about this please feel free to reopen and we discuss further
