### ISSUE TITLE
Automatic ID generation fails with bulk request of op_type "create"

### ISSUE THREAD

**Issue by exchsac** [elastic/elasticsearch#21535]
```
$ cat test
{"create": {"_index": "test", "_type": "doc"}}
{"title": "Lorem ipsum dolor"}

curl -X POST 'localhost:9200/_bulk' --data-binary "@test"

{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;"},"status":400}
```
"index" works fine
Version: 5.0.0, Build: 253032b

**Comment by dakrone** [comment]
@exchsac the `create` op explicitly requires an id to be set, because it then uses that to throw an exception if the document already exists. If you want to have automatic ID generation you need to use the "index" operation.

**Comment by exchsac** [comment]
This was not the case with 2.3.4 therefore it breaks things.

**Comment by bleskes** [comment]
@exchsac yes - sorry for that. 5.0 brings great speed ups when using auto generated ids. To achieve that we had to make sure those are never used with versioned operations - i.e., operations that compare the already indexed version of the document with the newly supplied one. Under the hood create is such a versioned operations stating that the previous version should be deleted/non existed. This is why it doesn't work anymore.

PS if you haven't already you might want to go through the [breaking changes list](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-5.0.html) the APIs you use. We keep it up to date to prevent such surprises.

**Comment by s1monw** [comment]
> This was not the case with 2.3.4 therefore it breaks things.

correct, we broken this on purpose in a major version jump. If you have alternative ideas when to break I would be happy to hear them

**Comment by exchsac** [comment]
Thanks for the responses. I didn't, nor do I see the issue in breaking changes, thats why I thought it's worth mentioning.

**Comment by s1monw** [comment]
it's [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_index_apis.html#_optype_create_without_an_id)

**Comment by exchsac** [comment]
@s1monw Ok I stand corrected :-)
