### ISSUE TITLE
scripted metric aggregation docs implicitly assume Groovy as default lang

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#21536]
Currently, the [5.0 docs for scripted metric aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-aggregations-metrics-scripted-metric-aggregation.html) assume that the default scripting language is Groovy. However, we changed the default scripting language to Painless in 5.0 and this [confuses users](https://discuss.elastic.co/t/scripted-metric--agg-variable-not-defined/65802) as they get non-obvious error messages when they follow the example in the docs:

```json
...
       "reason" : {
          "type" : "script_exception",
          "reason" : "compile error",
          "caused_by" : {
            "type" : "illegal_argument_exception",
            "reason" : "Variable [_agg] is not defined."
          },
          "script_stack" : [
            "_agg[transactions] = []",
            "^---- HERE"
          ],
          "script" : "_agg[transactions] = []",
          "lang" : "painless"
        }
...
```

We could now either:

(a) Fix the docs so we explicitly define the scripting language (as I've done on Discuss)
(b) or fix the docs so it works with Painless

I'd opt for option (b) but maybe we also need code changes then. /cc @jdconrad

**Comment by nik9000** [comment]
I'm happy to have a look at these in a bit. I converted a couple of aggregations docs to `// CONSOLE` so we test these as part of the build a while back but never got to these. I'll try and convert this page next.

**Comment by nik9000** [comment]
I pushed:
master: 7dcff27aea501754bcea971d5ef2fb2219032664
5.x: 1d89775591c1100676dd7f676a92c1fe610e5015
5.0: c3dd4a760846f3a0290435401f25b42291773ac5
