### ISSUE TITLE
Cat tests expect indices to be returned in a particular order

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#21547]
This [build](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/656/console) failed because the `_cat` API returned index `twitter2` before `twitter`, while the regular expression expected them to occur in the opposite order. I think we should either fix the test to not care about the order or the cat API to return indices in a specific order (eg. sorted alphabetically?).

**Comment by jasontedor** [comment]
The request does request a sort by index name:

`GET /_cat/indices/twi*?v&s=index`

**Comment by jpountz** [comment]
Thanks. So the issue is about sorting.

**Comment by jpountz** [comment]
OK actually I had not correctly understood the failure at all, the failing line is not the first cat request which sorts by index name, it is another one that sorts by store size. This is the same bug as #21062.
