### ISSUE TITLE
ES 5 randomly switching from field.keyword to just field

### ISSUE THREAD

**Issue by DigiAngel** [elastic/elasticsearch#21553]
**Elasticsearch version**: 5.0.0

**Plugins installed**: [none]

**JVM version**: java version "1.8.0_111"

**OS version**:  Ubuntu Server 16.04

**Description of the problem including expected versus actual behavior**:
ES 5.0.0 appears to randomly  switch from field.keyword to just field

**Steps to reproduce**:
 1.  Installed, setup, ran with data going to the "service" field.
 2.  After close to two days, data starts to go to the "service.keyword" field (by design)
 3.  After creating a new index automatically (found this out via logs), data went back to the "service" field.

**Provide logs (if relevant)**:
Some reference links:
[https://discuss.elastic.co/t/beta-fielddata/64332/5](url)
[https://discuss.elastic.co/t/data-stopped-going-to-keyword-field/65871](url)

Devs, please let me know if you'd like me to put the screenshots and data from the second Discuss link which has all the information...thought I would save time/space.  Also, this is a dev environment that I can totally restart from scratch (again) for figuring out this issue.  Thank you.

**Comment by jpountz** [comment]
This seems to be due to the fact you have dynamic templates configured. Elasticsearch will map strings as a text+keyword field by default. However, if you have dynamic templates, they will have precedence over Elasticsearch's defaults and will be used instead.

**Comment by DigiAngel** [comment]
Thank you.  I guess my experience has been that this is "sort of" happening.  For about 7 days everything went to service.keyword, why suddenly back to service?

**Comment by DigiAngel** [comment]
Also, should I open another bug as even though my mapping template instructs to not analyze strings, they are still being analyzed?  Thank you.

**Comment by DigiAngel** [comment]
So after redoing this...yea this indeed is a case of "if only the user would get out of the way and let ES do it's thing".  I was trying to fix strings being analyzed, and ES 5 has already done that.  Removing the dynamic template portion and just using a template that changed a couple fields to IP addresses is what was needed.  Thank you.

**Comment by jpountz** [comment]
Thank you for bringing closure.
