### ISSUE TITLE
Elasticsearch 5.0 /_cat/fielddata API returns blank output

### ISSUE THREAD

**Issue by HariSekhon** [elastic/elasticsearch#21564]
**Elasticsearch version**: 5.0

**Plugins installed**: none

**JVM version**: Docker

**OS version**: Docker

**Description of the problem including expected versus actual behavior**:

Elasticsearch 5.0 official docker container returns blank output when querying the _cat/fielddata API.

I've used this _cat API endpoint for a number of years and checking back at the documentation for 5.0 at https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-fielddata.html but I see no mention of it being deprecated or why it should return blank results, I'd expect to get the details of the Docker node output as I have various automated tests that are using this information that used to work against previous Docker image versions. Switching to using /_nodes does show the node details so the Elasticsearch node has the information, it's just not presenting it via the _cat API.

**Steps to reproduce**:
 1. docker run -ti -p 9200:9200 elasticsearch:5.0
 2. curl http://host:9200/_cat/fielddata
 3. results in no output where before it was populated with a table of node details
 4. curl http://host:9200/_nodes which shows the info is available inside Elasticsearch, it's just not presented via the _cat API any more, which seems like a bug

**Comment by dakrone** [comment]
@HariSekhon when you perform a `curl 'localhost:9200/_nodes/stats/fielddata'`, is your cluster currently using fielddata at all? If no fielddata is in use, the table will be empty causing the output to be empty (as you are seeing)

**Comment by HariSekhon** [comment]
I think what's caught me off guard is breakage in CI tests looking at fielddata stats where there are none, the behaviour seems to have changed between 2.4 and 5.0 where before it used to return zero bytes and now it returns nothing:

2.4.1 /_cat/fielddata?v:
```
id                     host       ip         node  total 
KYiKey7WQoOR5ONtACAKVA 172.17.0.2 172.17.0.2 Slick    0b
```
5.0.0 /_cat/fielddata?v:
```
id host ip node field size
```

Comparing the outputs for fielddata stats between 2.4 and 5.0 they appear the same with no fielddata, I guess I was mainly caught off guard by the behaviour change, which is not convenient at all really.

2.4.1 /_nodes/stats/fielddata:
```
{
    "cluster_name": "elasticsearch",
    "nodes": {
        "a1CKJQRxStmPZ7oD8RTw8Q": {
            "host": "172.17.0.2",
            "ip": [
                "172.17.0.2:9300",
                "NONE"
            ],
            "name": "Prototype",
            "timestamp": 1479235173230,
            "transport_address": "172.17.0.2:9300"
        }
    }
}
```
5.0.0 /_nodes/stats/fielddata:
```
{
    "_nodes": {
        "failed": 0,
        "successful": 1,
        "total": 1
    },
    "cluster_name": "elasticsearch",
    "nodes": {
        "EtJysrEATTqYOS1HoGCtVw": {
            "host": "172.17.0.2",
            "ip": "172.17.0.2:9300",
            "name": "EtJysrE",
            "roles": [
                "master",
                "data",
                "ingest"
            ],
            "timestamp": 1479235583082,
            "transport_address": "172.17.0.2:9300"
        }
    }
}
```

2.4.1 /_stats/fielddata:
```
{
    "_all": {
        "primaries": {
            "fielddata": {
                "evictions": 0,
                "memory_size_in_bytes": 0
            }
        },
        "total": {
            "fielddata": {
                "evictions": 0,
                "memory_size_in_bytes": 0
            }
        }
    },
    "_shards": {
        "failed": 0,
        "successful": 1,
        "total": 1
    },
    "indices": {
        "hari": {
            "primaries": {
                "fielddata": {
                    "evictions": 0,
                    "memory_size_in_bytes": 0
                }
            },
            "total": {
                "fielddata": {
                    "evictions": 0,
                    "memory_size_in_bytes": 0
                }
            }
        }
    }
}
```

5.0.0 /_stats/fielddata::
```
{
    "_all": {
        "primaries": {
            "fielddata": {
                "evictions": 0,
                "memory_size_in_bytes": 0
            }
        },
        "total": {
            "fielddata": {
                "evictions": 0,
                "memory_size_in_bytes": 0
            }
        }
    },
    "_shards": {
        "failed": 0,
        "successful": 1,
        "total": 1
    },
    "indices": {
        "hari": {
            "primaries": {
                "fielddata": {
                    "evictions": 0,
                    "memory_size_in_bytes": 0
                }
            },
            "total": {
                "fielddata": {
                    "evictions": 0,
                    "memory_size_in_bytes": 0
                }
            }
        }
    }
}
```

**Comment by HariSekhon** [comment]
I've changed my code to infer that it must be 0 bytes if there is no output but that is actually not very safe if searching for a specific node which isn't found in the output then instead of raising an exception it has to infer 0 bytes, but it also could have been an incorrectly specified node that was searched on which will now infer 0 bytes instead of the correct response which is there is no such node.

I feel the old explicit behaviour was better and safer from this perspective, I'd request that the behaviour be reverted to it's original method of explicit outputs.

**Comment by dakrone** [comment]
@HariSekhon I believe this was changed as part of https://github.com/elastic/elasticsearch/issues/10249, which changes the output entirely and https://github.com/elastic/elasticsearch/pull/18068 which dropped the `total` field (what would usually be 0 here), while I agree it makes sense to not have the `total` field in a row-centric output, I'm not sure whether we should explicitly return 0 if there is no fielddata usage.

@clintongormley what do you think?

**Comment by jasontedor** [comment]
We discussed this during Fix-it-Friday and agreed to leave it as is. As @dakrone mentioned, this is a consequence of the change to row-centric output and `total` does not make sense there.

> I've changed my code to infer that it must be 0 bytes if there is no output but that is actually not very safe if searching for a specific node which isn't found in the output then instead of raising an exception it has to infer 0 bytes, but it also could have been an incorrectly specified node that was searched on which will now infer 0 bytes instead of the correct response which is there is no such node.

If you want to be safe, you can double-check against `/_cat/nodes`.
