### ISSUE TITLE
circuit_breaking_exception

### ISSUE THREAD

**Issue by prigornitskiy** [elastic/elasticsearch#21560]
[parent] Data too large, data for [<http_request>] would be larger than limit of [283829862/270.6mb]"

**Elasticsearch version**:
{
  "name": "u6fJI8i",
  "cluster_name": "elasticsearch",
  "cluster_uuid": "EWXMG9E6TkST75QAyjQnCQ",
  "version": {
    "number": "5.0.0",
    "build_hash": "253032b",
    "build_date": "2016-10-26T05:11:34.737Z",
    "build_snapshot": false,
    "lucene_version": "6.2.0"
  },
  "tagline": "You Know, for Search"
}

OS:
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.2 (jessie)
Release:	8.2
Codename:	jessie

thereafter not performed any request. It helps only restart.

**Comment by jasontedor** [comment]
Can you provide a reproduction, or a description of the circumstances that led to this including what request you are sending?

**Comment by jasontedor** [comment]
No feedback, closing.
