### ISSUE TITLE
confusing documentation ES 5.0 script plugin 

### ISSUE THREAD

**Issue by rboorugu** [elastic/elasticsearch#21567]
your documentation is contradictory 
page below describes how to use Native (Java) Scripts in 5.0 which uses ScriptModule 
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-native.html

here in this page https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_plugins.html
it indicates below

ScriptPlugin
Plugins that register custom scripts should implement ScriptPlugin and remove their onModule(ScriptModule) implementation.

**Comment by dakrone** [comment]
@clintongormley it looks like this is fixed in 5.x and master with your commit https://github.com/elastic/elasticsearch/commit/34d90b04, should that one be backported to 5.0 also?

**Comment by rboorugu** [comment]
got it bit it should be as below right - changed "id" to "inline"?

curl -XPOST localhost:9200/_search -d '{
  "query": {
    "function_score": {
      "query": {
        "match": {
          "body": "foo"
        }
      },
      "functions": [
        {
          "script_score": {
            "script": {
                "inline": "my_script",
                "lang" : "native"
            }
          }
        }
      ]
    }
  }
}'

**Comment by clintongormley** [comment]
@rjernst you'll know better than me which is correct and which incorrect

**Comment by rjernst** [comment]
@rboorugu Your snippet looks correct to me.

FYI, I actually (mostly) fixed the docs referenced here in #21414 (however, I missed a single line referring to ScriptModule). But I also should have backported those doc fixes to 5.0 branch (will do that now).

**Comment by rjernst** [comment]
Ok I backported that doc part of my change: 151d6b7

**Comment by rjernst** [comment]
I also fixed the remaining reference to ScriptModule:
master: 914664d
5.x: c912163
