### ISSUE TITLE
_cat/allocation truncating node name

### ISSUE THREAD

**Issue by HariSekhon** [elastic/elasticsearch#21565]
**Elasticsearch version**: 5.0.0

**Plugins installed**: none

**JVM version**: Docker

**OS version**: Docker

**Description of the problem including expected versus actual behavior**:

Querying the /_cat/allocation API in Elasticsearch 5.0.0 shows the node name is being truncated at 7 characters, which breaks code that is looking to match the node name exactly as returned by other parts of the API (eg. /_nodes) and also increases the chances of naming collisions. I've tested this is also true on 2.4.1.

**Steps to reproduce**:
 1. docker run -ti -p 9200:9200 elasticsearch:5.0
 2. curl http://host:9200/_cat/allocation?v
 3. curl http://host:9200/_nodes

Notice that the node name is step 2 is truncated compared to the complete node name shown in step 3.

Why not just output the whole node name, seems simpler?

**Comment by jasontedor** [comment]
The full node name is in fact printed:

```
$ ~/elasticsearch/elasticsearch-5.0.0/bin/elasticsearch -E node.name=this-node-name-is-really-long -d
$ curl -XGET "localhost:9200/_cat/allocation?h=node&v"
node
this-node-name-is-really-long
```

What you're observing is the fact that the default node name is derived from the node ID, it's the first seven characters as you observe. However, the node is an auto-generated base-64 UUID. Collisions can happen with the truncated hash, but they are not likely (you need ~2.4 million nodes to have a 50% chance of a collision (it's the birthday paradox with 64^7 birthdays)). If this concerns you, you can set a node name explicitly.

**Comment by jasontedor** [comment]
For reference, here's the [code](https://github.com/elastic/elasticsearch/blob/253032b4a7818992af360097e3ddc1475fa7b044/core/src/main/java/org/elasticsearch/rest/action/cat/RestAllocationAction.java#L144) the prints the full node name.

**Comment by HariSekhon** [comment]
Ah now I realize it's the name generation mechanism that changed in 5.0 which has broken my CI tests for the version upgrade. I understand you've probably made this change to increase randomness for auto-generated node name, I'm not worried about collisions it'd only be an issue if it was actually truncating real names which are more likely to have a shared prefix in some companies with server naming conventions, was more just about the consistency between the two, I had worked around this but given this info I've improved the fix, thanks very much for the explanation.
