### ISSUE TITLE
Scripted metric aggregation needs _aggs in params

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#21584]
If you define `params` in `scripted_metric` aggs you need to define `_aggs` as an empty map or the "normal" way of using scripts doesn't work.

See the third sippet on [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-scripted-metric-aggregation.html) page for what that looks like.

**Comment by nik9000** [comment]
@jdconrad, this is what I was showing you a few minutes ago.

**Comment by colings86** [comment]
@elastic/es-search-aggs

**Comment by polyfractal** [comment]
@rationull @rjernst I think this was fixed/obsoleted by #29328, could you confirm?

**Comment by rationull** [comment]
@polyfractal yep, that's correct. No more interaction with `params` is required and the agg state map is initialized internally now.

**Comment by polyfractal** [comment]
Great, thanks @rationull!  Closing! :)
