### ISSUE TITLE
JSAPI scroll documentation is inconsistent

### ISSUE THREAD

**Issue by pushplay** [elastic/elasticsearch#21586]
In the documenation for client.scroll at https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-scroll the parameter `scroll` is listed as accepting either a Date or number.  The example on the same page uses a string`scroll: '30s'`.  Either the parameter should be documented as also accepting a string or the example needs to be updated.

If the parameter can be a string like `'30s'` is that also true of other parameters in other functions that accept `Date, Number`?

**Comment by jasontedor** [comment]
There's a dedicated [repository](https://github.com/elastic/elasticsearch-js) for elasticsearch-js. Could you please open an issue there?

**Comment by pushplay** [comment]
Ah I didn't know about that one.  Cheers.
