### ISSUE TITLE
My field is doc_value , but got error : Fielddata is disabled on text fields by default. Set fielddata=true 

### ISSUE THREAD

**Issue by small-tomorrow** [elastic/elasticsearch#21587]
**Elasticsearch version**: 5.0.0

**Plugins installed**: [] x-pack

**JVM version**: jdk8

**OS version**: centos 6.4

I got ' Fielddata is disabled on text fields by default. Set fielddata=true' in my request , but it confused me ,since I put not_analyzed to my field , so it is not a text field , which will support doc_values according to https://www.elastic.co/guide/en/elasticsearch/reference/5.0/fielddata.html#_fielddata_is_disabled_on_literal_text_literal_fields_by_default.
**here is part of my template :** 
"timestamp": {
"format": "epoch_millis",
"type": "date",
"doc_values": true
},
"device_id": {
"index": "not_analyzed",
"type": "string",
"doc_values": true
},
"name_type": {
"type": "integer",
"doc_values": true
}

**when I try to request with a aggregtion like :** 
"aggs": {
"cardinality_count": {
"cardinality": {
"field": "device_id"
}
}
}
**but I got failures as :**
"reason": {
"type": "illegal_argument_exception",
"reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [device_id] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory."
} 
@
Any help will be great appreciated !

**Comment by small-tomorrow** [comment]
@clintongormley  HI ,clinton , sorry to disturb , but I just can not fix it

**Comment by small-tomorrow** [comment]
plz , any advice ?

**Comment by small-tomorrow** [comment]
@ncdc @dysinger @AndrewO @ph @matschaffer   any ideas ?

**Comment by small-tomorrow** [comment]
anyway, when I set my mapping before post data to it , the queries work ! but I have so much data generated with ES2.1.0 , so how can I make it ?

**Comment by jpountz** [comment]
Can you share the mapping you have on 2.1? (Not the template, I need the exact mapping as returned by `GET _mapping`)

**Comment by small-tomorrow** [comment]
{
    "template" : "mobile_*",
    "settings" : {
        "number_of_shards" : 20
    },
    "mappings" : {
        "measurementStat": {
            "properties": {
                "timestamp": {"type": "date","format": "epoch_millis", "doc_values": true},
                "app_id": {"type": "integer", "doc_values": true},
                "app_version": {"type": "string", "index": "not_analyzed", "doc_values": true},
                "os_info": {"type": "string", "index": "not_analyzed", "doc_values": true},
                "model": {"type": "string", "index": "not_analyzed", "doc_values": true},
                "brand": {"type": "string", "index": "not_analyzed", "doc_values": true},
                "device_id": {"type": "string", "index": "not_analyzed", "doc_values": true},
                "scope_type": {"type": "integer", "doc_values": true},
                "name_type": {"type": "integer", "doc_values": true},
                "scope": {"type": "string", "index": "not_analyzed", "doc_values": true},
                "name": {"type": "string","index": "not_analyzed", "doc_values": true},
                "short_scope": {"type": "string", "index": "not_analyzed", "doc_values": true},
                "short_name": {"type": "string","index": "not_analyzed", "doc_values": true},
                "scope_and_name": {"type": "string","index": "not_analyzed", "doc_values": true},
                "sub_short_scope": {"type": "string","index": "not_analyzed", "doc_values": true},
                "max": {"type": "float", "doc_values": true},
                "min": {"type": "float", "doc_values": true},
                "avg": {"type": "float", "doc_values": true},
                "total": {"type": "float", "doc_values": true},
                "count": {"type": "integer", "doc_values": true},
                "apn_id": {"type": "integer", "doc_values": true},
                "ip": {"type": "string", "index": "not_analyzed", "doc_values": true},
                "country_id": {"type": "string", "index": "not_analyzed", "doc_values": true},
                "provider_id": {"type": "integer", "doc_values": true},
                "region_id": {"type": "integer", "doc_values": true},
                "city_id": {"type": "integer", "doc_values": true}
            }
        }
    }
}
@jpountz

**Comment by small-tomorrow** [comment]
could it be the reason that I start my ES 5.0.0 with the data.path of the ES 2.1.0 , cause there are much data of old version ?

**Comment by jpountz** [comment]
@small-tomorrow I asked for the mappings but it looks like you shared the index template again. Can you share the actual mappings of your indices instead? (`curl -XGET 'localhost:9200/_mapping`)

**Comment by small-tomorrow** [comment]
"mobile_1235591_20161017": {
      "mappings": {
         "measurementStat": {
            "properties": {
               "apn_id": {
                  "type": "integer"
               },
               "app_id": {
                  "type": "integer"
               },
               "app_version": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "avg": {
                  "type": "float"
               },
               "brand": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "city_id": {
                  "type": "integer"
               },
               "count": {
                  "type": "integer"
               },
               "country_id": {
                  "type": "string",
                  "index": "not_analyzed"
               },
               "device_id": {
                  "type": "string",
                  "index": "not_analyzed"
               }
         }
     }
}
@jpountz  actually ,the mapping is generated by template , and I found it the same above

**Comment by jpountz** [comment]
I tried to reproduce the problem by creating an index with a not_analyzed string field in 2.x and then moving the data to a 5.0.1 cluster, but this worked. Can you check that `mobile_1235591_20161017` is the only index that you search and that there is no other index that is included that might have doc values disabled for the `device_id` field?

**Comment by clintongormley** [comment]
@small-tomorrow please don't spam people with comments like https://github.com/elastic/elasticsearch/issues/21587#issuecomment-260842271, https://github.com/elastic/elasticsearch/issues/21587#issuecomment-260842647, https://github.com/elastic/elasticsearch/issues/21587#issuecomment-260845050, https://github.com/elastic/elasticsearch/issues/21587#issuecomment-260848143

Please post the full output of this request:

    GET */_mapping/field/device_id?include_defaults

**Comment by small-tomorrow** [comment]
Sorry for disturbing ! It will never  happen again !  I have checked for another time , and every device_id have doc_values abled , and the Mapping is : 
```
"measurementStat": {
            "device_id": {
               "full_name": "device_id",
               "mapping": {
                  "device_id": {
                     "type": "keyword",
                     "boost": 1,
                     "index": true,
                     "store": false,
                     "doc_values": true,
                     "term_vector": "no",
                     "norms": false,
                     "index_options": "docs",
                     "eager_global_ordinals": false,
                     "similarity": "BM25",
                     "null_value": null,
                     "include_in_all": true,
                     "ignore_above": 2147483647
                  }
               }
            }
         }
```

**Comment by jpountz** [comment]
It looks like the issue is that your index template is not applied to new indices created after you upgrade while still pointing to the same data path since `device_id` is mapped with the default dynamic mappings (`device_id` as `text` and `device_id.keyword` as `keyword`). Can you check that the index template exists and that it has the expected content?

**Comment by clintongormley** [comment]
You are aware that the template doesn't affect existing indices?  It only applies to new indices.

**Comment by clintongormley** [comment]
> I have checked for another time , and every device_id have doc_values abled , and the Mapping(started with the old version data) is :

When you use the old data dir, you definitely don't have doc values enabled.  See:

                     "type": "text",
                     "boost": 1,
                     "index": true,
                     "store": false,
                     "doc_values": false,  <--- NOT ENABLED

**Comment by small-tomorrow** [comment]
You are right ,they  weren't !  It seemed that I should start es with old data dir , and change the field type to keyword  in order to make it searchable again . Thanks , And It works !  OOM keep troubling me , and the uploading bulk request is Okay with ES 2.1.0 ,anyway it's an another problem . Thank you so much !

**Comment by small-tomorrow** [comment]
thanks again , clinton  and jpountz
