### ISSUE TITLE
Index Partitioning with Custom Routing

### ISSUE THREAD

**Issue by scottsom** [elastic/elasticsearch#21585]
I'm interested in adding an optimization that would make it possible for a custom routing value go to a subset of shards in an index rather than just a specific shard. This would work by picking the subset of shards using the routing value then pick the shard within that set using the document ID.

The primary use case for this is multi-tenant indices with custom routing that suffer from one or both of the following:

- The big users cannot fit into a single shard or there are so many of them that it is highly likely that they will land on the same shards
- Users occasionally have a surge in write traffic that a single shard cannot process fast enough

Ultimately, you end up with the dreaded hot shard, severely impacting the write throughput and search latency of all requests that visit that node.

I am familiar with the parts of the Elasticsearch documentation that discuss [faking an index per user with aliases](https://www.elastic.co/guide/en/elasticsearch/guide/current/faking-it.html) and [giving the big users their own index](https://www.elastic.co/guide/en/elasticsearch/guide/current/one-big-user.html). This approach works well initially but what the documentation does not discuss is what happens when you hit 100,000 users, 500,000 users, then 1,000,000 users? Since the [cluster state is finite](https://www.elastic.co/guide/en/elasticsearch/guide/current/finite-scale.html) then having millions of aliases is not good position to be in, especially with it constantly growing for every new user.

Suppose we had a 100 shard index and we knew our biggest users were each ~3% of the total size. Without being able to use custom routing (users are too big) or aliases per user (too many users) then you would have to settle for one giant index, leading to a sub-optimal configuration since you are not leveraging the spatial locality that the custom routing can give you. As a result, every search request hits all 100 shards in the index.

If you could partition this index, let's say 10 ways to be safe, then any given user can only be found on 10 shards. It would not be far fetched to see up to a 10x increase in search throughput on the same amount of hardware when custom routing is provided with this change since you have significantly reduced the work that needs to be done per request.

It is certainly possible to achieve this through a client managed hashing scheme such that you have 10 indices of 10 shards each then you just do your own hashing to determine which index you route the request to. However, this would require you to have a special client wrapper for accessing Elasticsearch and if you ever wanted to change your partitioning scheme then you would need to do a coordinated deployment. If this partitioning was managed by Elasticsearch then it would just be a reindex followed by an alias flip.

I believe this is a generic enough problem that it makes sense to implement this in Elasticsearch, making it easier for other developers in the community to benefit from without having to write their own hashing code and worrying about the complexities that go along with it.

Before I got to far along on writing the code I wanted to see if there would be any strong objections to such a feature. For example, one shortcoming is that it would not be possible to guarantee that a grandparent would be in the same shard as its grandchildren (which I believe is a reasonable limitation).

For reference, I did manage to dig up a similar feature request from a couple of years ago: https://github.com/elastic/elasticsearch/issues/8472 (hopefully it's ok that I opened a new issue for this)

**Comment by makeyang** [comment]
how about make hash method configable?

**Comment by jpountz** [comment]
> how about make hash method configable?

I like the current proposal better than making the hash method configurable, since there are fewer moving parts, so it is much easier to support in terms of backward compatibility for instance.

@scottsom One thing I am wondering is whether in practice you would use the same number of shards for all users or not. I did not spend much time thinking about it, but I have the feeling that this feature only makes sense if all users have the same number of shards. Otherwise it means that the client has the logic to be able to know how to handle each user, meaning it could probably deal with multiple indices instead.

**Comment by scottsom** [comment]
Yes, the client would be unaware of the partitioning (aside from providing a routing value) and all users would use the same number of shards.

You would pick your partitions based on the size of the largest users. You would need to consider how many shards your biggest users would ideally span across and if you have a lot of them, how likely is it that they will fall into the same partition.

If you imagine an index with 64 shards then valid ways to partition this are [1, 2, 4, 8, 16, 32, 64] ways. If you partition it 64 ways then this is equivalent to how custom routing works today (each user lives in a single shard). If you partition it 1 way then this is equivalent to having no partitioning (each user lives on all shards). The values in-between is what this proposal aims to allow.

You can conclude that as the number of partitions decreases, the likelihood of imbalanced shards decreases at the cost of having to broadcast each search to more shards per request. When it doubt it would be best to start with a small number of partitions (or no partitioning) then ease into more partitions (through reindexing) to find the sweet spot based on your data distribution, how stable it is, and observed access patterns.

To draw an analogy, this is similar to what you would find in some database offerings. For example, Oracle's "Composite Hash-Hash Partitioning".

**Comment by makeyang** [comment]
today someone ask for "Composite Hash-Hash Partitioning", tomorrow others will ask for other hash partitioning. so why just provide configable and customerized hash function?

**Comment by jpountz** [comment]
We just discussed this issue in FixitFriday. We do NOT want to make the hash function configurable in a way that would allow arbitary functions. However we are considering the idea of being able to specify a number of shards that documents may go to at index creation time, which could not be modified afterwards and would default to `1`. For instance one thing we would need to validate is whether we can make it play nicely with index shrinking. We would like to have a prototype implementing this idea in order to get a better idea of whether integrating this feature would be reasonable.

**Comment by scottsom** [comment]
I'm glad there is interest in adopting this feature - I will proceed with an implementation and send a pull request.

From my brief foray into the code base, it did not appear that index shrinking should be impacted since routing is determined based on the original number of shards _then_ the shrinking factor is applied [0]. It is definitely a use case that will need to be verified though.

[0] https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/cluster/routing/OperationRouting.java#L223-L225

**Comment by scottsom** [comment]
There are two different approaches that I have been considering. For both options, I would expect the data distribution to be roughly the same (will need to verify), so I think it is just a matter of preference.

**1. Specify number of partitions**

This adds an index setting, `number_of_partitions`, which allows you to specify the number of ways to partition the index. It would be required that `number_of_shards % number_of_partitions == 0`, otherwise the partitions could not be of equal size.

With this, the calculation of which shards to search is fairly straight forward. For example, with a 4 shard index partitioned 2 ways then the calculation is just:

`hash(routing_value) % number_of_partitions` with a value of 0 going to shards [0, 1] and a value of 1 going to shards [2, 3].

**2. Specify a partition size**

This adds an index setting, `partition_size`, which allows you to specify the number of shards any given routing value can go to. The only requirement for this value is that it is `1 <= partition_size <= number_of_shards`.

The calculation for this one is a bit more complex. We could for example, [shuffle](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle) the shards and route the request to the first `partition_size` values. The seed value to our random number generator would be the hash of the routing value.


From the user's perspective, option 2 is a bit more flexible because you could for example, allow any given routing value to go to 75% of the shards (e.g. an index of 4 shards with a partition size of 3). A side effect of this approach however, is that index shrinking would result in different routing values going to a different number of shards. For example, if we shrunk our 4 shard index to 2 shards then some routing values will go to 2 shards while others would go to 1.

Your wording here:

> we are considering the idea of being able to specify a number of shards that documents may go to at index creation time

Seems to indicate that you have a preference to option 2?

**Comment by jpountz** [comment]
> From my brief foray into the code base, it did not appear that index shrinking should be impacted since routing is determined based on the original number of shards then the shrinking factor is applied [0]. It is definitely a use case that will need to be verified though.

Sounds correct.

I was just thinking about another potential issue: parent/child relations. This feature would mean that an index that has a partition size that is greater than 1 should not be able to create a parent/child mapping or the join would not work anymore?

> The only requirement for this value is that it is 1 <= partition_size <= number_of_shards.

Maybe we should even require that the partition size is <= number_of_shards/2. If routed documents can still go to a majority of shards, I'm not sure routing is still valuable?

> Seems to indicate that you have a preference to option 2?

Yes indeed. For what it is worth, an implementation I was thinking about was to compute the target shard as something like `(hash(_routing) + hash(_id) % partition_size) % num_shards`.

**Comment by scottsom** [comment]
> I was just thinking about another potential issue: parent/child relations. This feature would mean that an index that has a partition size that is greater than 1 should not be able to create a parent/child mapping or the join would not work anymore?

Right, parent/child relationship could be sent to the same shard with some special handling but it would be too hackish (e.g. use the parent _id instead of the child _id for hashing, thus requiring the _parent and _routing values for child gets). For grandparent/grandchild data models, I don't see a way to get them all on the same shard.

Hopefully it would be an acceptable limitation for a partitioned index to just reject parent/child mappings?

> Maybe we should even require that the partition size is <= number_of_shards/2. If routed documents can still go to a majority of shards, I'm not sure routing is still valuable?

Yes, routing to a majority is a bit weird but even if you partitioned it such that every request hit 9 out of 10 shards, I would expect that it would still be possible to measure a _slight_ performance gain, despite it being a bit nonsensical. Perhaps the option could be left open for the users to decide what works best for them?

> Yes indeed. For what it is worth, an implementation I was thinking about was to compute the target shard as something like `(hash(_routing) + hash(_id) % partition_size) % num_shards`.

That sounds like a good way to choose the shards. This will result in each partition being a sequence of shards rather than a random permutation, which is easier to reason about.

**Comment by scottsom** [comment]
To back this up with some numbers, I've written an implementation and then loaded the [Apache Software Foundation Public Mail Archives](https://aws.amazon.com/datasets/apache-software-foundation-public-mail-archives/) into a cluster with a single node (i2.xlarge). The routing value is the mailing list.

There is about 1.7M emails in total and here is the distribution of the top 10 mailing lists.

Mailing List|% of documents
-|-
tomcat.apache.org-users|4.11%
struts.apache.org-user|3.00%
tomcat.apache.org-dev|2.46%
httpd.apache.org-dev|2.27%
www .apache.org-apache-bugdb | 2.15%
commons.apache.org-dev|1.65%
spamassassin.apache.org-users|1.61%
cocoon.apache.org-dev|1.60%
cocoon.apache.org-users|1.58%
axis.apache.org-java-dev|1.57%

I created 8 different indices, each with 8 shards and different partition sizes. The _partition_size_1_ index is how custom routing works today and the _no_partition_ is how the default routing works today.

Here is the distribution of the emails between the shards:

Index|Shard 0|Shard 1|Shard 2|Shard 3|Shard 4|Shard 5|Shard 6|Shard 7|Quality†|Max - Min
-|-|-|-|-|-|-|-|-|-|-|
partition_size_1|167624|162620|148384|237575|194000|297919|306198|150497|1.08470836316453|157814
partition_size_2|159448|164696|155727|192763|215957|246446|300951|228829|1.05140859885752|145224
partition_size_3|208371|159902|159713|182503|193171|243665|265820|251672|1.0347405326755|106107
partition_size_4|230471|196955|157411|179132|185405|218903|259334|237206|1.02348236763392|101923
partition_size_5|222910|216243|187282|173571|181887|208067|236832|238025|1.01246333206541|64454
partition_size_6|225629|212691|205436|195833|177401|201223|224552|222052|1.00559815982774|48228
partition_size_7|214221|216155|204849|210426|195329|194444|215920|213473|1.00160620679272|21711
no_partition|207835|208012|208214|207844|208655|208345|208583|207329|0.999999698460185|1326

† The quality formula is for measuring the uniformity of a hash function and comes from [this page](https://www.strchr.com/hash_functions) which got it from the [Red Dragon Book](https://en.wikipedia.org/wiki/Compilers:_Principles,_Techniques,_and_Tools). A quality of 1 is a perfect score.

As expected, we see the distribution becoming more uniform as our partition sizes increase until we reach a near perfect distribution with no partitioning, which is simply hashing on the automatically generated ID.

Finally, I ran some search load tests on each index using varying levels of concurrency. This test is running a match query on _all using a random dictionary word and filtering (and routing when applicable) on a random mailing list. Each worker thread would only complete after it had ran 1000 sequential queries. For tests with multiple workers, they all ran concurrently. The measured time is when all workers finished their 1000 queries.

Index|Time (s) – 1 Worker|Time (s) – 2 Workers|Time (s) – 4 Workers|Time (s) – 8 Workers|Time (s) – 16 Workers
-|-|-|-|-|-|
partition_size_1|2.00|2.52|3.78|7.17|13.99
partition_size_2|2.09|3.04|4.85|9.41|17.99
partition_size_3|2.34|3.64|5.96|11.19|21.94
partition_size_4|2.86|4.31|7.15|13.70|26.31
partition_size_5|3.32|4.85|8.34|15.78|30.43
partition_size_6|3.56|5.31|9.26|17.46|33.38
partition_size_7|3.72|5.76|10.24|19.31|37.30
no_partition|4.02|6.25|11.18|21.40|40.93

We see that with respect to search performance, despite the shards being rather imbalanced, routing each request to a single shard is still the most efficient access pattern. This makes sense because the dataset we are working with is relatively small and each mailing list can sit in a single shard with plenty of room to spare.

We also see that routing to a majority of the shards can still yield a significant performance boost compared to no partitioning.

This is not an ideal dataset to demonstrate the usefulness of this optimization (need something much bigger) but hopefully it gives you an idea of the potential.

**Comment by scottsom** [comment]
Another way this could be implemented is to leave the `_routing` field alone and introduce a new field, let's call it `_partitions`. This would allow us to support parent/child models, partitioning on N dimensions, and can be extended to support more than just hash partitioning (i.e. we could do range partitioning on dates, numbers, and/or coordinates).

Suppose we could create an index like this:
```javascript
{
  "settings": {
    "index": {
      "number_of_shards": 24,
      "partitions": [
        {
          "type": "hash",
          "shards": 6
        },
        {
          "type": "date",
          "shards": 2,
          "interval": "2h"
        }
      ]
    }
  }
}
```

The shard count for each partition must be less than the total number of shards in the index _and_ less than the number of shards in the previous partition. In other words, each additional partition further refines the set of shards that need to be searched.

As an example, let's imagine we had a cluster that was consuming time series data from various systems. We observe that most searches are being done within the context of a `source_system` and usually on `event_time` over an hourly period. We want to optimize the cluster for this access pattern, so our first partition is done on `source_system`, which is hashed and picks 6 out of 24 shards. Next we partition on `event_time` such that the same 2 hour interval is distributed between 2 out of the 6 shards that were just picked. Finally, we hash on `_id` (or custom `_routing`) to pick the final shard out of the 2 remaining.

Now we can support the following searches:
* Neither `source_system` or `event_time` is provided - search all 24 shards
* Only `source_system` is provided - search 6 shards
* Both `source_system` and `event_time` is provided - search 2 shards (or more if the date range falls outside our interval)
* Only `event_time` is provided - search all 24 shards

Indexing our document would have a payload like this:

```javascript
{
  "_partitions": ["foo_system", "2016-11-21T12:34.56Z"],
  "_source": {
    "source_system": "foo_system",
    "event_time": "2016-11-21T12:34.56Z"
  }
}
```

For what it's worth, I wouldn't aim to implement different types of partitioning (dates) in an initial implementation. Just wanted to illustrate the extensibility of this approach.

**Comment by compasses** [comment]
@scottsom The routing cannot make sure each shard have  single one routing key's data. Do you consider this kind of case? Like i want each shard have only one routing key located in.

**Comment by scottsom** [comment]
@compasses It is not the intention of this change to support a 1:1 mapping between shards and routing values. If that is your goal then you would be better off not using _routing and create an index per routing value, which only works as long as the cardinality of the routing value is low. Otherwise you will end up with an unmanageable amount of shards.

For reference, this is the commit I ran the benchmark above on and can be used as a prototype:
https://github.com/scottsom/elasticsearch/commit/f48f28303dd02f0fc54376e5563693bb4354f016

It allows you to create an index like this:

```bash
curl -XPUT 'localhost:9200/foo' -d '
{               
    "settings" : {
        "index" : {
            "number_of_shards" : 12,
            "number_of_replicas" : 0,
            "partition_size": 3
        }
    }
}'
```

It requires each mapping to have _routing required and does not allow _parent fields.

If this is a reasonable approach and the limitations are acceptable then I can add more tests and send a pull request.

**Comment by compasses** [comment]
@scottsom get it. thanks

**Comment by scottsom** [comment]
@jpountz What are the next steps here?

**Comment by jpountz** [comment]
@scottsom Last time we discussed about this feature, we said we could think about integrating it if it does not add too much complexity to how routing works in the code base. Would you like to give it a try?

**Comment by scottsom** [comment]
Here is a commit to my fork with the implementation that I used for the benchmarks above:
https://github.com/scottsom/elasticsearch/commit/f48f28303dd02f0fc54376e5563693bb4354f016

If we want to proceed with this then I will look into adding more tests around it and send a pull request.

**Comment by jpountz** [comment]
+1 to open a PR

**Comment by makeyang** [comment]
it's still a static way to solve hot share/hot data issue. 
but the real case is that: before data is pushed into cluster, there is no way to know which part will be the hot part. so my question is: is there any plan to make ES can solve these kind of problem dynamic? 
nowsdays, with reindex feature and timestamp feature powered, maybe it's time to talk about dynamic sharding?
