### ISSUE TITLE
Performance Regression on Bulk Insert from 1.7.5 to 5.0.0

### ISSUE THREAD

**Issue by sallgeud** [elastic/elasticsearch#21583]
**Elasticsearch version**: 5.0.0

**Plugins installed**: []

**JVM version**: 1.8.0

**OS version**: Windows Server 2012 R2

**Description of the problem including expected versus actual behavior**: While upgrading our code from 1.7.5 to 5.0.0, we performed our standard set of indexing tests. Most regular, single item indexing tasks appears to be as quick as before (though we can't be entirely sure, because it's so fast). However, bulk indexing of 50 at a time, in a highly multi-threaded environment was approximately 55% slower in 5.0 than it is in 1.7.

We are unable to determine if this might be related to the underlying C# driver. However, ANTS suggests we're not using more CPU clocks other than waiting. We are using the LowLevel client (Formerly known as Raw), and submitting raw JSON. As such, the only changes between the two tests were the driver and the version of elasticsearch

**Steps to reproduce**:
 1. Write code with NEST 1.7 and Elastic 1.7 to multi-thread a bulk insert across several multi-dimensional types in the same index
 2. Test
 3. Modify the written code to work with NEST 5.0 and Elastic 5.0 and repeat 

**Provide logs (if relevant)**: The logs only include basic information about new type mappings being created. No errors or other information.

**Comment by sallgeud** [comment]
Indexing 670k records across 100 types: ~10-100k records in each type

**5.0**: 4:40
**1.7**: 3.06

**Comment by jpountz** [comment]
Since you only have 50 items by bulk entry, I suspect this is caused by the fact that since 2.0, we fsync data on every bulk request. You could either set `index.translog.durability` to `async` to get the 1.7 behaviour back, or use larger bulk requests that will better amortize the cost of fsync across documents (recommended).

**Comment by sallgeud** [comment]
Testing with durability set to async got us down to 4:02. Testing with a higher bulk size next.

**Comment by jasontedor** [comment]
> Testing with durability set to async got us down to 4:02.

It might be clear to you, but I think it's worth being explicit for the benefit of everyone: this comes with a loss of durability. You can lose acknowledged requests.

**Comment by sallgeud** [comment]
I was off... we're indexing by bulk of 100. Increasing that to 200 and 500 showed a < 2 second change @200 and > 10 second increase @500.

We're ok with durability being somewhat non-existent as it's non-critical data. I just added a modification immediately before and immediately following bulk indexing to remove durability. 

The best I was able to do was get the time down to 3:40 by reducing the number of shards to 3 (from 5). Our tests use a single server with no replicas, and settings to match.

**Comment by s1monw** [comment]
@sallgeud are you using autogenerated IDs or you won IDs? Also are you specifying you mappings ahead of time or do you use dynamic mappings? With dynamic mappings you might see some slowdowns since we wait of the master to publish the mapping to all nodes in that case since 2.x

**Comment by clintongormley** [comment]
Also, do your tests reindex the same document ID repeatedly?  If so, see https://github.com/elastic/elasticsearch/issues/21460#issuecomment-259686101

**Comment by sallgeud** [comment]
We are using our own id. It's a simple integer. We have to use dynamic mappings, as our data itself is very dynamic. While we could pre map on this bulk, it wouldn't help much for every day functionality, as our structure, from the elastic perspective, changes regularly. It's user configured dynamic mappings, basically. 

There's no reindexing of the same id in our tests. Think of it as a bulk importer from another nosql db.

**Comment by s1monw** [comment]
> While we could pre map on this bulk, it wouldn't help much for every day functionality, as our structure, from the elastic perspective, changes regularly. It's user configured dynamic mappings, basically. 

this causes the slowdown you are seeing. the mapping update now waits for the master to _ack_ it. I wonder if your test data causes lots of mapping updates and if that is realistic. Your mappings should converge over time so the slowdown should disappear over time ie. if you benchmark runs longer the impact should vanish?

**Comment by sallgeud** [comment]
One would certainly think so. I'll test pre-mapping. However, a quick investigation showed that > 95% of our first-records within a type had all of the fields.

**Comment by yossicahen** [comment]
I don't know if I need to open a new issue, but I have also an identical bug on upgrading from 2.4 to 5.2. I have a significant performance regression on Bulk Indexing. I tried to change the number of documents on each batch from 1000 to 5000 or 10,000, but no changes. Rollback to 2.4.2 solves the problem. Is there a major change in ES5 bulking? Indexing?

**Comment by colings86** [comment]
No further feedback on this specific issue.

@yossicahen its probably worth opening a separate issue for what you are seeing. Please include as much information as you can and if possible include a recreation script for what you are seeing
