### ISSUE TITLE
Java REST Client 5.0.1 Maven

### ISSUE THREAD

**Issue by toliwa** [elastic/elasticsearch#21581]
**Elasticsearch version**: 5.0.1

**Plugins installed**: []

**JVM version**: 8

**OS version**: Linux

**Description of the problem including expected versus actual behavior**:

In the documentation on [https://www.elastic.co/guide/en/elasticsearch/client/java-rest/5.x/_maven_repository.html](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/5.x/_maven_repository.html) the REST client is said to be available on [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.elasticsearch.client%22). However, only version 5.0.0 is there, while the transport and sniffer are there in version 5.0.1. Looks like the REST client has been forgotten during the latest update.

Additionally, the same [documentation](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/5.x/_maven_repository.html) proposes the following dependency:

```
<dependency>
    <groupId>org.elasticsearch.client</groupId>
    <artifactId>rest</artifactId>
    <version>5.1.0</version>
</dependency>
```

The version should be ``5.0.1``. Is this maybe an auto-increment in the wrong place?

**Steps to reproduce**:
 1. Go to [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.elasticsearch.client%22)
 2. No 5.0.1 REST client there

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by nik9000** [comment]
The client [looks](http://repo1.maven.org/maven2/org/elasticsearch/client/rest/5.0.1/) to be in maven central.

This looks like an issues with search.maven.org. They have a [page](http://search.maven.org/#artifactdetails%7Corg.elasticsearch.client%7Crest%7C5.0.1%7Cjar) for it but it doesn't come back in the search you linked.

**Comment by toliwa** [comment]
Thanks, I was able to get the 5.0.1 REST JARs through maven from the page that you linked.

**Comment by nik9000** [comment]
I'll leave this open for a bit and check back. If the jar doesn't show up in search I'll figure out who to ask about it.

**Comment by nik9000** [comment]
Looks like search.maven.org is updated now.
