### ISSUE TITLE
Restarting node causes cluster red with dangling index

### ISSUE THREAD

**Issue by SmartSara** [elastic/elasticsearch#21589]
**ENV:** 
Ubuntu 14.04.1 LTS
Elasticsearch cluster: version 2.3.0 with 6 nodes

**Reproduce steps:**

- Create an index 
`curl -XPUT 'http://localhost:9200/sara_wednesday_test/' -d '{
    "settings" : {
        "index" : {
            "number_of_shards" : 6, 
            "number_of_replicas" : 1
        }
    }
}'`

- See shards allocations, esnode02 holds primary shard 2 and replica shard 1
curl localhost:9200/_cat/shards?pretty | grep sara_wednesday_test`
sara_wednesday_test 1 p STARTED   0    130b 10.29.97.183 esnode03
sara_wednesday_test 1 r STARTED   0    130b 10.29.97.182 esnode02
sara_wednesday_test 2 p STARTED   0    130b 10.29.97.182 esnode02
sara_wednesday_test 2 r STARTED   0    130b 10.29.97.181 esnode01
sara_wednesday_test 3 r STARTED   0    130b 10.29.97.186 esnode06
sara_wednesday_test 3 p STARTED   0    130b 10.29.97.181 esnode01
sara_wednesday_test 5 r STARTED   0    130b 10.29.97.185 esnode05
sara_wednesday_test 5 p STARTED   0    130b 10.29.97.184 esnode04
sara_wednesday_test 4 p STARTED   0    130b 10.29.97.185 esnode05
sara_wednesday_test 4 r STARTED   0    130b 10.29.97.184 esnode04
sara_wednesday_test 0 p STARTED   0    130b 10.29.97.186 esnode06
sara_wednesday_test 0 r STARTED   0    130b 10.29.97.183 esnode03

- Shutdown node esnode02 in the cluster

- Delete the index
`curl localhost:9200/sara_wednesday_test -XDELETE`
{"acknowledged":true}

- Restart node esnode02 in the cluster, seeing logs:

> [2016-11-16 00:10:59,661][INFO ][gateway                  ] [esnode02] [sara_wednesday_test] dangling index, exists on local file system, but not in cluster metadata, auto import to cluster state

- Cluster health shows red. See shard allocation, only shard 1 and shard 2 STARTED, other shards have been lost.
`curl localhost:9200/_cat/shards?pretty | grep sara_wednesday_test`
sara_wednesday_test 1 r STARTED      0    159b 10.29.97.186 esnode06
sara_wednesday_test 1 p STARTED      0    159b 10.29.97.182 esnode02
sara_wednesday_test 3 p UNASSIGNED
sara_wednesday_test 3 r UNASSIGNED
sara_wednesday_test 2 r STARTED      0    159b 10.29.97.183 esnode03
sara_wednesday_test 2 p STARTED      0    159b 10.29.97.182 esnode02
sara_wednesday_test 5 p UNASSIGNED
sara_wednesday_test 5 r UNASSIGNED
sara_wednesday_test 4 p UNASSIGNED
sara_wednesday_test 4 r UNASSIGNED
sara_wednesday_test 0 p UNASSIGNED
sara_wednesday_test 0 r UNASSIGNED

Obviously, deleted index data still remains on the esnode02 filesystem, and when the node restarts, it is reimported into cluster by default. However, esnode02 does not hold the complete data of the index, thus causing index red and cluster red.

The problem here is that, as I am an ops guy, hosting Elasticsearch cluster for my consumers, I can only see there is something wrong with the index, indicating there must be unassigned shards (data loss).
I think probably the right behavior is either Elasticsearch deletes the dangling index if the data is not complete, or Elasticsearch finds a way to recover the deleted data if reimport is the default behavior.

Hope to hear from you soon. Thanks.

**Comment by ywelsch** [comment]
This is fixed with index tombstones in v5.0.0 (see #18250).

Quoting @bleskes from #19477:

> the fix is 5.0 only sadly - the fix is quite tricky and will not be ported to 2.x.
