### ISSUE TITLE
Deleting non-dynamic settings by cluster settings API

### ISSUE THREAD

**Issue by d0znpp** [elastic/elasticsearch#21593]
**Elasticsearch version**:

**Plugins installed**: []

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
```
    private boolean updateSettings(Settings toApply, Settings.Builder target, Settings.Builder updates, String type, boolean onlyDynamic) {
        boolean changed = false;
        final Set<String> toRemove = new HashSet<>();
        Settings.Builder settingsBuilder = Settings.builder();
        for (Map.Entry<String, String> entry : toApply.getAsMap().entrySet()) {
!            if (entry.getValue() == null) {
                toRemove.add(entry.getKey());
!            } else if ((onlyDynamic == false && get(entry.getKey()) != null) || hasDynamicSetting(entry.getKey())) {
                validate(entry.getKey(), toApply);
                settingsBuilder.put(entry.getKey(), entry.getValue());
                updates.put(entry.getKey(), entry.getValue());
                changed = true;
            } else {
                throw new IllegalArgumentException(type + " setting [" + entry.getKey() + "], not dynamically updateable");
            }
```
It's possible to delete non-dynamic settings by using cluster/_settings API.
https://github.com/elastic/elasticsearch/blob/5a03eb91e664e64041315c597f320b60b556d9a7/core/src/main/java/org/elasticsearch/common/settings/AbstractScopedSettings.java#L449
Please add the same check hasDynamicSetting(entry.getKey() to first condition.

Example:
```
PUT ...
{
    "transient" : {
        "non-dynamic-setting-name-here": null
     }
}
```

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by s1monw** [comment]
would you mind opening a PR for this?

**Comment by d0znpp** [comment]
Sure! https://github.com/elastic/elasticsearch/pull/21594

**Comment by s1monw** [comment]
@d0znpp I think you opened the PR against the wrong branch?
