### ISSUE TITLE
Slowlog cannot handle very long queries and truncates the log entry

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#21602]
5.0.

Can't share the actual query here, but feel free to reach out to me directly.

Single query is sent via curl @test.json (which is a 956Kb file, with 32K+ lines, with a very large terms filter).  The resulting log entry in the slowlog shows the following, with none of the usual took time, shard hit information, but an entry that starts with just the bottom part of the query where the large terms filter is.

```
[2016-11-16T11:32:46,279][DEBUG][index.search.slowlog.query] [H9GIwD1]                   42324,
                      61981,
                      395144,
                      420125,
                      376625,
                      27874,
                      102929,
```

Actual query has:

```
                {
                  "terms": {
                    "some_field": [
                      <a large number of longs here>
                   ]
```

Just to clarify this ticket is more about slowlog handling of large queries (we are already aware that having that many terms in a terms filter is not the ideal approach here).

**Comment by jasontedor** [comment]
This is controlled by the log4j 2 configuration. If you open the default log4j2.properties that ships with Elasticsearch you'll see:

```
appender.index_search_slowlog_rolling.layout.pattern = [%d{ISO8601}][%-5p][%-25c] %marker%.10000m%n
```

Replace `%.10000m` with `%m`. The former truncates the query from the beginning to the last 10000 characters.

**Comment by ppf2** [comment]
Nice, thx for the tip @jasontedor !

**Comment by ppf2** [comment]
@jasontedor could there still be an issue here (or an enhancement request)?  Part of the issue here is that by default it uses log4j2's truncation functionality.  It seems like it will be more user friendly to provide some other way to truncate the message that does not also remove the timing, # of shards, information so that the truncated slowlog is more useful?

```
[2016-11-16T17:01:46,253][DEBUG][index.search.slowlog.query] [H9GIwD1] ax_boost" : 3.4028235E38,
      "boost" : 1.0
    }
  },
  "stored_fields" : [ ],
  "ext" : { }
}], 
```

**Comment by jasontedor** [comment]
@ppf2 The reason this pattern is used is to not blow disk space. We could truncate from the beginning; would that help?

**Comment by dakrone** [comment]
> Part of the issue here is that by default it uses log4j2's truncation functionality.

> The reason this pattern is used is to not blow disk space.

Yes, this was added because a user had their hundred-megabyte mapping being written out (repeatedly!) to the log file as a single line. We should definitely not remove the truncation by default, but maybe truncating from the beginning as Jason mentioned would help.

**Comment by ppf2** [comment]
Yep, I think truncating by default from the beginning will help, at least it will show the took times (will be helpful for perf testing situations where I already know what the queries look like and all you really care about are the took times for aggregating metrics), thx!

**Comment by jasontedor** [comment]
I opened #21609.
