### ISSUE TITLE
search templates don't work anymore in ES v5

### ISSUE THREAD

**Issue by maczes** [elastic/elasticsearch#21603]
Hello,

it looks like search templates don't work anymore in ES v5. The search template query returns: "reason": "no [query] registered for [query]"

**Elasticsearch version**: v5.0.0 and v5.0.1

**Plugins installed**: []
No custom plugins installed except that delivered by default with ES v5.x

**JVM version**: 
OpenJDK Runtime Environment (build 1.8.0_72-internal-b05)
OpenJDK 64-Bit Server VM (build 25.72-b05, mixed mode)

**OS version**:
Debian GNU/Linux 8

**Description of the problem including expected versus actual behavior**:
The  search template query returns: "reason": "no [query] registered for [query]" instead of actual result.
Same behavior in Sense and using Java API client

**Steps to reproduce**:
What I'm doing is:
1. add stored template into cluster scope:
POST /_search/template/cm_getlites
{
  "template": {
    "query": {
      "bool": {
        "must": [{
            "match": {
              "moId": "{{moId}}"
            }
          }, {
            "match": { "metaClass": "{{metaClass}}" }
          }] 
}}}}

2. run query
GET /_search
{
  "query": {
    "template": {
      "id": "cm_getlites",
      "params": {
        "moId": "some_name",
        "metaClass": "some_class"
}}}}

Checked also with index (cm) scope -> GET /cm/_search .This same result.

I was following this guide to setup and search with stored template: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-template-query.html#_stored_templates

Thanks.

**Comment by maczes** [comment]
It seems to it work but in other request form that described in the official guide.

# OK
GET /cm/_search/template
{
  "id": "cm_getlites",
  "params": {
    "moId": "some_name",
    "metaClass": "some_class"
}}

But I can't get this same behavior in java API. It looks like Java API always send this:
{
"query": {
"template": {
"id": "cm_getlites",
"params": {
"moId": "some_name",
"metaClass": "some_class"
}}}}

**Comment by javanna** [comment]
Can you share you java code please?

**Comment by maczes** [comment]
Hi,

Thanks for looking at this.
I create template from json file (cm_getlites.json) with this code:

client.admin().cluster().preparePutStoredScript()
                .setId(templateName)
                .setScriptLang("mustache")
                .setSource(new BytesArray(SearchUtils.readFile(templatePath, Charsets.UTF_8)))
                .get();

cm_getlites.json file content
{
  "template": {
    "query": {
      "bool": {
        "must": [
          {
            "match": {
              "moId": "{{moId}}"
            }
          },
          {
            "match": {
              "metaClass": "{{metaClass}}"
            }
          }
        ]
      }
    }
  }
}

And here is the test working on template:
@Test
    public void testTemplateWorksFine() throws Exception
    {
        Map<String, Object> params = new HashMap<>();
        params.put( "moId", SampleDataInserter.MO_ID_1 );
        params.put( "metaClass", SampleDataInserter.META_CLASS_1 );

        SearchRequestBuilder searchRequestBuilder = client().prepareSearch( "cm" )
                .setQuery( new TemplateQueryBuilder(
                        CM_GETLITES_TEMPLATE_NAME,
                        ScriptService.ScriptType.STORED,
                        params) );

        SearchResponse searchResponse = searchRequestBuilder.execute().actionGet();

        assertNotNull( searchResponse );
        assertThat( searchResponse.getHits().getTotalHits(), is( 1l ) );
    }

Let me know if anything else is needed.

**Comment by clintongormley** [comment]
There are two forms of search templates.  One which allows templating the whole search query, and a `template` query (deprecate) which allows you to embed a query inside the query DSL.

The first example you provide is using the `template` query, which results in the following request being executed  (note the double `query`):

```
GET /_search
{
  "query": {
    "query": {
      "bool": {
        "must": [
          {
            "match": {
              "moId": "some_name"
            }
          },
          {
            "match": {
              "metaClass": "some_class"
            }
          }
        ]
      }
    }
  }
}

```

There used to be a `query` clause which allowed you to use a query inside a filter.  This clause was deprecated in 2.0 and removed in 5.0.  If you remove the `query` element from the template, then you can use your template with the `template` query:

```
PUT t/t/1
{
  "moId": "some_name",
  "metaClass": "some_class"
}

POST /_search/template/cm_getlites
{
  "template": {
    "bool": {
      "must": [
        {
          "match": {
            "moId": "{{moId}}"
          }
        },
        {
          "match": {
            "metaClass": "{{metaClass}}"
          }
        }
      ]
    }
  }
}

GET /_search
{
  "query": {
    "template": {
      "id": "cm_getlites",
      "params": {
        "moId": "some_name",
        "metaClass": "some_class"
      }
    }
  }
}

```

(Note: this form is deprecated and will be removed in 6.0)

The second form allows you to template the whole search request, which you'd do as follows:

```
POST /_search/template/cm_getlites
{
  "template": {
    "query": {
      "bool": {
        "must": [
          {
            "match": {
              "moId": "{{moId}}"
            }
          },
          {
            "match": {
              "metaClass": "{{metaClass}}"
            }
          }
        ]
      }
    }
  }
}

GET /_search/template
{
  "id": "cm_getlites",
  "params": {
    "moId": "some_name",
    "metaClass": "some_class"
  }
}
```
