### ISSUE TITLE
SearchHit getScore() is NaN

### ISSUE THREAD

**Issue by zhangjw-ECHO** [elastic/elasticsearch#21610]
**Elasticsearch version**:
5.0
**Plugins installed**: []

**JVM version**:
jdk8 up 65
**OS version**:
window server 2012
**Description of the problem including expected versus actual behavior**:
SearchHit getScore() is NaN
**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by cbuescher** [comment]
How are you using the java api?

**Comment by jpountz** [comment]
No feedback, closing. I suspect what happened is that the hits were sorted by something else than the score and `track_scores` was not configured. https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_track_scores
