### ISSUE TITLE
modules (e.g. lang-painless, lang-groovy etc) not published on maven central for 5.0.x

### ISSUE THREAD

**Issue by TrustNoOne** [elastic/elasticsearch#21615]
I had to take the `lang-painless.jar` from the distribution and publish it on my private repository to be able to execute (in tests) an embedded node with scripting enabled.

Is there a reason why the modules have not been published? I couldn't find anything in the issues. They were there before, at least for groovy:

```
org.elasticsearch.module	reindex	2.4.1  all (8)	27-Sep-2016	pom  jar  zip  javadoc.jar  sources.jar  
org.elasticsearch.module	lang-groovy	2.4.1  all (11)	27-Sep-2016	pom  jar  zip  javadoc.jar  sources.jar  
org.elasticsearch.module	lang-expression	2.4.1  all (11)	27-Sep-2016	pom  jar  zip  javadoc.jar  sources.jar  
org.elasticsearch.module	modules	2.4.1  all (11)	27-Sep-2016	pom  

```

**Comment by s1monw** [comment]
are you embedding a node or why do you need these jars?

**Comment by s1monw** [comment]
this might be relevant in this case https://www.elastic.co/blog/elasticsearch-the-server

**Comment by TrustNoOne** [comment]
Yes, I am embedding a node, I've been doing this for years for integration testing in my builds, of course not in production.

Since embedding it's not supported then you won't be publishing the artifacts? It's not a big deal, I have everything working, it's just that I can't find them on maven central.

**Comment by s1monw** [comment]
> Since embedding it's not supported then you won't be publishing the artifacts? It's not a big deal, I have everything working, it's just that I can't find them on maven central.

pretty much

did you look into using our testing framework instead by any chance?

**Comment by TrustNoOne** [comment]
It doesn't look like it does what I want, I am already unit testing my code but I also have a suite of integration tests that starts an instance of my application and uses actual external databases. The only one I'm embedding is elasticsearch, well, because I can :) 

Furthermore I am using scala/elastic4s/specs2 so I don't think I can use the test framework classes. I guess I'll keep publishing module jars from the distribution on my private artifactory and migrate to a proper external instance in the future to avoid headaches since it's not supported anymore.

I'll also have a look at the test framework code as soon as I can to see if I can use something. 

Funny thing is everything works properly, it's just that I don't have the painless plugin on central. I get that what I'm doing could break anytime because you don't support it, thanks for the insight anyway :)

**Comment by clintongormley** [comment]
thanks for understanding :)

**Comment by synhershko** [comment]
@s1monw can you please elaborate on how the test framework will help here? if I need lang-expression or analysis-kuromoji for my unit/integration tests with Elasticsearch, how does it help if they are not available on maven and I can't pull them to my setup?

**Comment by s1monw** [comment]
the test framework can expose you n external cluster coming from a zip file that has all plugins you need. if not you have to install them.

**Comment by trejkaz** [comment]
The good news is that someone else has started publishing some of them on Maven, including this one:

https://mvnrepository.com/artifact/org.codelibs.elasticsearch.module/lang-painless

We're using an embedded node in unit tests for our plugins, because spinning up an external cluster is way too slow, especially (but not solely) because Elasticsearch's plugin install script doesn't cache plugin artifacts.
