### ISSUE TITLE
Small documentation inconsistency 

### ISSUE THREAD

**Issue by waqark3389** [elastic/elasticsearch#21629]
I am on version 2.4, This page: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/modules-discovery-zen.html

States that ping_timeout is 3s in one paragraph, then further down it states 30s in the table. Which is it? And can we put the correct one up 

:)

**Comment by jasontedor** [comment]
@waqark3389 These are referring to different settings. One is `discovery.zen.ping_timeout` which is used for master election. The second is `discovery.zen.fd.ping_timeout` (note the `fd`) which is used for fault-detection pings.
