### ISSUE TITLE
phrase suggester doc errors

### ISSUE THREAD

**Issue by LucaWintergerst** [elastic/elasticsearch#21624]
There are two mistakes I just found in the phrase suggester documentation for 5.0
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-suggesters-phrase.html

> In this case we received the expected correction xorr the god jewel first while the second correction is less conservative where only one of the errors is corrected.

This sentence is no longer relevant. It refers to an example in the 2.4 documentation

> popular: Only suggest terms that occur in more docs on the shard then the original term.

_Then_ should be _than_

**Comment by ywelsch** [comment]
@LucaWintergerst Can you open a PR with the change? It's super easy:

1) Go here:
https://github.com/elastic/elasticsearch/blob/master/docs/reference/search/suggesters/phrase-suggest.asciidoc

2) Click on the crayon icon in the top right of the screen (Edit this file)
3) In the "commit changes" box add a commit message and select "Create a new branch for this commit and start a pull request"
4) Wait for someone to review the change

Thanks!

**Comment by LucaWintergerst** [comment]
created PR https://github.com/elastic/elasticsearch/pull/21651 and merged after LGTM of Christoph. He will also take care of the cherry picking on 5.x and 5.0

Thanks for reminding me that I can just do this myself @ywelsch :)

**Comment by ywelsch** [comment]
Thanks @LucaWintergerst
