### ISSUE TITLE
transport client fails in uber jar - no shortHash

### ISSUE THREAD

**Issue by brackxm** [elastic/elasticsearch#21627]
**Elasticsearch version**: 5.0.1

**Plugins installed**: [ReindexPlugin, PercolatorPlugin, MustachePlugin, Netty3Plugin, Netty4Plugin, XPackPlugin]

**JVM version**: 1.8.0_112

**OS version**: osx 10.12.1

**Description of the problem including expected versus actual behavior**:

Getting the cluster node info fails when using the transport client from an uber jar.
Similar to #19930, but using the transport client.
NodeInfo.readFrom() triggers the initialisation of Build.CURRENT which fails with "Error finding the build shortHash" 

**Steps to reproduce**:
 1. build uber jar with the transport client
 2. get cluster node info

**Provide logs (if relevant)**:

**Describe the feature**:

Maybe get the build info from an elasticsearch specific file in the classpath, so it is more uber jar friendly.

**Comment by liorze** [comment]
You should create the jar using the `maven-shade-plugin`, by adding it to your pom file:

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>2.4.1</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals><goal>shade</goal></goals>
            <configuration>
                <transformers>
                    <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                    <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                        <mainClass>com.company.Application</mainClass>
                        <manifestEntries>
                            <Change></Change>
                            <Build-Date></Build-Date>
                        </manifestEntries>
                    </transformer>
                </transformers>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by jasontedor** [comment]
Sorry, but I don't think we are going to modify our build process to support tearing our jar apart.

**Comment by liorze** [comment]
@jasontedor, are you suggesting that you don't support running the transport client in a jar?

**Comment by jasontedor** [comment]
> are you suggesting that you don't support running the transport client in a jar?

I'm saying that if you tear our jar apart, you need to put it back together with all the pieces that we expect to be there (for example, having the manifest entires that we are looking for like you suggested [previously](https://github.com/elastic/elasticsearch/issues/21627#issuecomment-261804213).

**Comment by liorze** [comment]
You should at least update the docs to avoid this confusion in the future.
https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/_embedding_jar_with_dependencies.html

**Comment by jasontedor** [comment]
Okay, we will do that. Thanks for the heads up.

**Comment by csouthwell** [comment]
If your using Lein (w/clojure) how can you resolve the META-INF like using shade in maven?

**Comment by tvernum** [comment]
@csouthwell I think you're going to need to ask some Leiningen experts, the ES team doesn't have expertise in how to do things that we don't support, in a build tool that we don't support. Sorry.

My advice would be to hit stackoverflow (or a lein specific forum) and ask how to add specific entries to the manifest when running `lein uberjar`

**Comment by martijnvg** [comment]
Closing issue. The paragraph about shading has been removed: ab2d74c0014b658f2b63e78055616a38e6cc8dd2
