### ISSUE TITLE
unexpect result  when time field mapping contains store: true

### ISSUE THREAD

**Issue by sshling** [elastic/elasticsearch#21639]
**Elasticsearch version**: 2.1.2  or newest

```
PUT store
{
   "mappings": {
      "performance": {
         "_source": {
            "enabled": false
         },
         "properties": {
            "host": {
               "store": true,
               "type": "long"
            },
            "time": {
               "format": "epoch_millis",
                "store": true,
               "type": "date"
            }
         }
      }
   }
}
POST store/performance
{
    "host":1234,
    "time":1479264717
}

GET  store/_search
{
  "fields": [
    "*",
    "_source"
  ],
  "fielddata_fields": [
    "time"
  ]
}
```
query result:

```
"time": [
    "1479144300000",
    1479144300000
  ]
```

But expect result:

```
"time": [
    1479144300000
  ]
```

Yes, setting the store the timestamp field does not make any sense ,but most ES users do not use the
ES very well ,so there is an inappropriate way to use it .However,I think that ES should consider this situation,to tolerate or compatible with this imappropriate use:
1. This setting can be ignored when setting the index type mappings.
2. Or to return to the search results,ignore the duplication of the results, take the value of the field from on place.

I'm from China, my English is not very good ,can understand what I mean?

**Comment by clintongormley** [comment]
hi @sshling 

> This setting can be ignored when setting the index type mappings.
> Or to return to the search results,ignore the duplication of the results, take the value of the field from on place.

We can do neither of these I'm afraid.  Stored fields return the original value, while doc values/fielddata return the appropriate format for the doc values type.  Here's a similar example in 5.0:

```
PUT store
{
  "mappings": {
    "performance": {
      "_source": {
        "enabled": false
      },
      "properties": {
        "host": {
          "store": true,
          "type": "long"
        },
        "time": {
          "store": true,
          "type": "date"
        }
      }
    }
  }
}

POST store/performance
{
  "host": 1234,
  "time": "2016-01-01"
}

GET store/_search
{
  "stored_fields": [
    "_source",
    "*"
  ],
  "docvalue_fields": [
    "time"
  ]
}
```

This returns:

```
      {
        "_index": "store",
        "_type": "performance",
        "_id": "AVh85FFkwXj0XIjNXeNO",
        "_score": 1,
        "fields": {
          "host": [
            1234
          ],
          "time": [
            "2016-01-01T00:00:00.000Z",
            1451606400000
          ]
        }
      }
```

The first value in the array is from the stored fields, the second from doc values.  We can't deduplicate here or only return one value, because you asked for both.

**Comment by sshling** [comment]
@clintongormley  
The important thing is,I think setting the store the timestamp field does not make any sense , What do you think?

**Comment by clintongormley** [comment]
@sshling I disagree - you may well want to store the original value.
