### ISSUE TITLE
Nested filter does not work for fields within a subobject

### ISSUE THREAD

**Issue by jpblair** [elastic/elasticsearch#21632]
**Elasticsearch version**: 1.7.5

**Plugins installed**: marvel, cloud-aws, bigdesk

**JVM version**: 1.8.0_40

**OS version**: CentOS 6.6

**Description of the problem including expected versus actual behavior**:  Using the `nested` filter does not appear to work when the filter uses fields that are within a subobject of the nested object (ie, not top-level).

**Steps to reproduce**:
 1. Create a new index (POST to `[cluster]/nested-filter-test`).
 2. POST the following payload to `/[cluster/nested-filter-test/test-type` to create a type `test-type` with a nested field in its mapping:
```
{
	"properties": {
		"nestedField": {
			"type":"nested",
			"properties": {
				"topLevel": {
					"type": "string",
					"index": "not_analyzed"
				},
				"subobject": {
					"properties": {
						"subfield": {
							"type": "string",
							"index": "not_analyzed"
						}
					}
				}
			}
		}
	}
}
```
 3. POST to `[cluster]/nested-filter-test/test-type` with the following payload to index a document:
```
{
	"nestedField": [
		{
			"topLevel": "value1",
			"subobject": {
				"subfield": "value2"
			}
		},
		{
			"topLevel": "value3",
			"subobject": {
				"subfield": "value4"
			}
		}
	]
}
```
4. Query for the document using the nested filter - put the following payload in Sense for `GET _search`, using the URL `[cluster]/nested-filter-test/test-type`:
```
{
    "filter": {
		"nested" : {
			"filter" : {
				"term" : {
					"subobject.subfield" : "value2"
				}
			},
			"path" : "nestedField"
		}
	}
}
```
5. The indexed document should be returned since the value of `subobject.subfield` is "value2" for the first object in `nestedField`, but it is not.  However, if you change the term filter to the following (ie, query on a top-level field of the nested object), the document is returned:
```
"term" : {
	"topLevel" : "value1"
}
```

I first posted this on the Elastic forums [here](https://discuss.elastic.co/t/querying-on-a-subobject-field-within-a-nested-object/65533), but did not get a response.  Thanks for your help.

**Comment by jpountz** [comment]
Sorry for not being more reactive on discuss. I just left a reply there.
