### ISSUE TITLE
Allow Ingest Pipeline to be Skipped if `node.ingest: false`

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#21634]
The idea is to add a flag, which defaults to `false`, that allows pipelines to be skipped if no ingest nodes exist.

```http
POST /_bulk?pipeline=xyz&can_skip_pipeline
```

The purpose is to allow tools like Monitoring, and anything else that creates consistent, versioned indices, to supply pipelines so that old data can be transitioned into a new version (as much as possible) as it flows into updated systems (e.g., API v1 may need to be upgraded to API v2, if/where possible).

However, if a user removes ingest nodes, then they effectively block all requests until they disable the ingest feature for their tool (or it constantly auto-detects, which is possible, but wasteful given the unlikely nature of it changing). Given that pipelines are about enrichment, it seems reasonable to have an opt-in way to say "it's okay if none of it happens".

**Comment by javanna** [comment]
We discussed this as part of FixItFriday. We agreed that the proposed change is not the right approach. Enrichment via ingest pipeline shouldn't be considered less important than other things. If you provide a pipeline id, we should make sure that it gets executed. It feels weird to pass another parameter to say "ignore it if you can't do it". We feel like this logic should be moved to the application/client.
