### ISSUE TITLE
Upgrade 1.xx to 5.xx

### ISSUE THREAD

**Issue by lee149205** [elastic/elasticsearch#21643]
I'm using es 1.4 . I want to upgrade to 5.xx .So, i will do :

+ Create snapshot from es 1.4 (passed)
+ Restore to es 2.4 (passed)
+ Reindex in es 2.4 (failed)
+ Created snapshot from new index in es 2.4 (not yet)
+ Restore to es 5 (not yet)

Show error when reindex : "unknown property [search]"
<img width="591" alt="screen shot 2016-11-18 at 2 27 15 pm" src="https://cloud.githubusercontent.com/assets/11714006/20422182/55f1948e-ad9b-11e6-9124-0bdfc7298d1b.png">

Mapping of index
<img width="188" alt="screen shot 2016-11-18 at 2 30 09 pm" src="https://cloud.githubusercontent.com/assets/11714006/20422244/b4701fb2-ad9b-11e6-83c0-44bc2dec1d66.png">

Data in index
<img width="352" alt="screen shot 2016-11-18 at 2 35 58 pm" src="https://cloud.githubusercontent.com/assets/11714006/20422370/8caedba2-ad9c-11e6-875b-ea069cc10f7e.png">

How to fix this error? Plz, help me. Thanks

**Comment by jpountz** [comment]
Please ask at https://discuss.elastic.co/ and give information using text rather than images. Your mappings and a sample document would probably be useful too.
