### ISSUE TITLE
[code issue in master][discuss]there are so many hard code setting strings all around

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#21642]
Setting.intSetting("index.routing.allocation.total_shards_per_node", -1, -1,
Property.Dynamic, Property.IndexScope);
Setting.intSetting("cluster.routing.allocation.total_shards_per_node", -1,  -1,
Property.Dynamic, Property.NodeScope);

is it better to define it somewhere once and refer it anywhere?

**Comment by jpountz** [comment]
I'll let others chime in as well, but to me this is not an issue as long as we fail on unknown settings.

**Comment by jasontedor** [comment]
I prefer it as is. First, it's just clearer this way. Second, I often search the codebase for where settings are defined so I can chase down how they are used in the code. If these were defined in terms of some other string constant, that searching would no longer work and that would be a serious pain.

**Comment by jpountz** [comment]
Closing then.
