### ISSUE TITLE
tojson in search template can only be used as inline.

### ISSUE THREAD

**Issue by borissmidt** [elastic/elasticsearch#21648]
**Elasticsearch version**: 2.4

**Plugins installed**: only the default

**JVM version**: 1.8

**OS version**: ubuntu 14

**Description of the problem including expected versus actual behavior**:
I want to be able to inline an array into a search template, I saw in the documentation that i need to use the `#tojson` command. 

This function does not work when i use it in a saved template. But it seems to work when i use it inline. 

```
POST /_search/template/example
{
   "template": {
        "query":{"bool":{"must": "{{#toJson}}clauses{{/toJson}}" }}
       }
}
GET /_render/template
{
    "id": "example",
    "params": {
        "clauses": [
            "kuipstoel","brunello","cognac"
        ]
   }
}
```
Results in the following error
```
{
   "error": {
      "root_cause": [
         {
            "type": "json_parse_exception",
            "reason": "Unexpected character ('k' (code 107)): was expecting comma to separate Object entries\n at [Source: [B@6097a0fb; line: 1, column: 30]"
         }
      ],
      "type": "json_parse_exception",
      "reason": "Unexpected character ('k' (code 107)): was expecting comma to separate Object entries\n at [Source: [B@6097a0fb; line: 1, column: 30]"
   },
   "status": 500
}
```

However when i use it as directly in the render with an inline field it will  work as expected.
```
GET /_render/template
{
    "inline": "{\"query\":{\"bool\":{\"must\": {{#toJson}}clauses{{/toJson}} }}}",
    "params": {
        "clauses": [
            "kuipstoel","brunello","cognac"
        ]
   }
}

i get:
{
  "template_output": {
    "query": {
      "bool": {
        "must": [
          "kuipstoel",
          "brunello",
          "cognac"
        ]
      }
    }
  }
}

```

So is this a real bug or am i just using wrong functions?

**Comment by tlrx** [comment]
When using search templates functions like `toJson` you need to carefully consider the parameters you pass to the script. 

In your example, `{{#toJson}}clauses{{/toJson}}` refers to an array containing 3 strings "kuipstoel", "brunello", "cognac" so it must be used as an array in your query.

In 5.0, you can search directly using a search template like this:
```
POST /_search/template 
{
    "inline": "{\"query\":{\"bool\":{\"must\": [{\"terms\": {\"clauses\": {{#toJson}}clauses{{/toJson}} }}] }}}", 
    "params": {
        "clauses": [
            "kuipstoel","brunello","cognac"
        ]
   }
}
```

The search template will be compiled and cached before being executed as the following query:
```
{"query":{"bool":{"must": [{"terms": {"clauses": ["kuipstoel","brunello","cognac"] }}] }}}
```


In 5.0, you can store it like this (here under the name `test`):
```
POST /_search/template/test 
{
    "template": "{\"query\":{\"bool\":{\"must\": [{\"terms\": {\"clauses\": {{#toJson}}clauses{{/toJson}} }}] }}}"
}
```

And then use it to search documents:

```
GET /_search/template 
{"id":"test", "params":{"clauses":["a","b","c"]}}
```

To complete your example, you could also store a template like this:

```
POST /_search/template/test
{                                                                    
    "template": "{\"query\":{\"bool\":{\"must\": {{#toJson}}clauses{{/toJson}} }}}"   
}
```

but if you look carefully at the structure of the query you can see that it expects an array of queries (that's the format expected by the `must` clause of a `bool` query). 

So you have to pass the right parameters:

```
GET /_search/template 
{
  "id":"test", 
  "params": { 
    "clauses":  [
      {
        "terms": {
          "clauses": ["a","b","c"]
        }
      }
    ]
  }
}

```

**Comment by borissmidt** [comment]
So if i see this correctly then the tojson has a different syntax from the other templates. 
i.e. 
in this example the querry is a normal querry
```
GET /_search/template
{
    "inline" : {
      "query": { "match" : { "{{my_field}}" : "{{my_value}}" } },
      "size" : "{{my_size}}"
    },
    "params" : {
        "my_field" : "foo",
        "my_value" : "bar",
        "my_size" : 5
    }
}
```

While with `#tojson` you have to make the full  querry a string. 

I actually just need to inline arrays but the tojson seems to be the only function that allows me to do that without generating an empty string field "". 

PS the example i used was just the one from the website. I have a different more complex query which is called from a java client.

**Comment by tlrx** [comment]
> So if i see this correctly then the tojson has a different syntax from the other templates.
> While with #tojson you have to make the full querry a string. 

By the nature of the function, ie generating JSON, and because you are using a REST JSON API to store this template, yes it has to be used in a inline query in order to build the query itself. 

You can also create a file `config/scripts/test.mustache` containing

```
{
	"query": {
		"bool": {
			"must": {{#toJson}}clauses{{/toJson}}
		}
	}
}

```

This way you don't have to make the full query a string.

**Comment by borissmidt** [comment]
Ok thanks for the help. 

Maybe this could be added to the wiki?
Because its not stated clearly that you have to stringify your string when using the `#json` and not with the other mustache functions.

**Comment by tlrx** [comment]
I think it is already documented at https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-template.html

But if you think the documentation could be improved on this point, please feel free to contribute :) There is an "edit" button on the page.

**Comment by ebuildy** [comment]
So in conclusion, it's not possible to store a template (via ``POST /_search/template/{NAME}`` method) containing ``{{#toJson}}``?

**Comment by borissmidt** [comment]
@ebuildy it is possible, First you create your template request and then you post it as a stringified post:
```
POST _search/template/marketplace_singleproductpages
{
  "template":"{\n  \"_source\": [\n    \"url\"  ],\n  \"size\": 100,\n  \"query\": {}}"
}
```

**Comment by timtutt** [comment]
@borissmidt -  Does that mean there is currently no way to do this with the Elasticsearch apis. In the javascript API for instance the put template allows you to specify an id as a template, but not the full URL to post. I have a number of templates that I automatically load using some scripts, but using toJson in this manner does not seem possible.

**Comment by borissmidt** [comment]
@timtutt, it is possible to do if you post the templates as a string. The last part of the url is the id.
to save the template:
Post /_seach/template [id]
To use the template:
Get /_search/ template
{
id:[id],
params:{a:hello}
}

You should take s a look at the documentation since it explains it better.

**Comment by RomainXie** [comment]
@borissmidt 
Try to save a template with {{#tojoin}} will get a error back.
My template is 

```
POST _scripts/test-json
{
  "script": {
    "lang": "mustache",
    "source": {"query": {"filter": {"bool": {"must": [{"terms": {"beat.hostname": {{#tojson}}hostname{{/tojson}} } }] } } } }
  }
}
```

The error message:

```
      "caused_by": {
        "type": "i_o_exception",
        "reason": "Unexpected character ('{' (code 123)): was expecting double-quote to start field name\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@5f8a9c1a; line: 10, column: 36]"
      }
```

After change the template like below, the syntax is correct. But I can not get the result.

```
POST _scripts/test-json
{
  "script": {
    "lang": "mustache",
    "source": {"query": {"filter": {"bool": {"must": [{"terms": {"beat.hostname": ["hostname"] } }] } } } }
  }
}
```

A test call:

```
GET /_search/template
{
  "id": "test-json",
  "params": {
    "hostname": ["begon", "testhost"]
  }
}
```

Is something I missed?
My version is 5.6.3

Thanks

**Comment by dnhatn** [comment]
@RomainXie please ask questions at https://discuss.elastic.co/. Thank you.
