### ISSUE TITLE
[code issue in master]many duplicate code in ShardsLimitAllocationDecider.java

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#21641]
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ShardsLimitAllocationDecider.java
method canAllocate() and canRemain() have so many duplicate code. better refacory it.

**Comment by jpountz** [comment]
I usually don't feel too bad about code duplication since I like code duplication better than having a utility method with weird semantics, but in that particular case, it looks like we could do something, eg. for computing the node shard count and the index shard count. Would you like to work on a pull request?

**Comment by jasontedor** [comment]
This is fine, the only difference between these two methods is strict inequality checks (`canRemain`, a shard can not stay if we are above the limits) and non-strict inequality check (`canAllocate`, a shard not be allocated if we are at or above the limits). If we are going to refactor here, I'd prefer to see more than just aggregating the counts but rather everything can be combined with the exception of different predicates for the index and node counts. Please let us know @makeyang if you'll work on a pull request for this.

**Comment by makeyang** [comment]
@jasontedor I'll work on a pull request for this.

**Comment by makeyang** [comment]
@jasontedor  sorry to bother, can you help to review code here and give comments:
https://github.com/makeyang/elasticsearch/commit/0d09ac1a26b79915564278c7995e071b06fed280#diff-a74ad8dfacd4f985eb3977517615ce25
because I'm very unconfident about this change. 
really sorry to bother.

**Comment by clintongormley** [comment]
@makeyang best way to get reviews (even for a work in progress) is to open a pull request.

**Comment by makeyang** [comment]
@clintongormley  ok. got it.

**Comment by ywelsch** [comment]
Closed by #21845
