### ISSUE TITLE
CI: ClusterServiceTests.testTimedOutUpdateTaskCleanedUp failes occasionally

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#21649]
I couldn't reproduce this locally, but saw three failures in the last few days so far. One looks like this:

```2> REPRODUCE WITH: gradle :core:test -Dtests.seed=7BA543F2F08452FC -Dtests.class=org.elasticsearch.cluster.service.ClusterServiceTests -Dtests.method="testTimedOutUpdateTaskCleanedUp" -Dtests.security.manager=true -Dtests.locale=es-AR -Dtests.timezone=Pacific/Gambier
FAILURE 0.02s J0 | ClusterServiceTests.testTimedOutUpdateTaskCleanedUp <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected empty map but was {org.elasticsearch.cluster.service.ClusterServiceTests$2@6aa29132=[[block-task]]}
   > 	at __randomizedtesting.SeedInfo.seed([7BA543F2F08452FC:C465A3553AECEACA]:0)
   > 	at org.elasticsearch.cluster.service.ClusterServiceTests.testTimedOutUpdateTaskCleanedUp(ClusterServiceTests.java:191)
   > 	at java.lang.Thread.run(Thread.java:745)
```
but continues with a larger tail about which looks like the cluster state to me

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=amazon/269/console

And there are other two failures in the same test have a more complicated stack trace:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+rank-eval+multijob-intake/9/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-unix-compatibility/os=centos/242/console

**Comment by ywelsch** [comment]
Fixed by b1fd257
