### ISSUE TITLE
Config update mapping (dynamic) ?

### ISSUE THREAD

**Issue by lee149205** [elastic/elasticsearch#21644]
I use es 1.4 . I see "update_mapping (dynamic)"

<img width="445" alt="1" src="https://cloud.githubusercontent.com/assets/11714006/20422664/4cb316e2-ad9e-11e6-9b47-aa731f5da8ef.png">

When upgrade to es 2.4, I don't see "dynamic"
<img width="464" alt="2" src="https://cloud.githubusercontent.com/assets/11714006/20422671/54247ab0-ad9e-11e6-8563-8841018f0679.png">

How to turn on dynamic for all index ?

**Comment by jpountz** [comment]
As of 2.0, dynamic mapping updates are no different from mapping updates through the API, which is why the log message does not specify whether it is dynamic or not.
