### ISSUE TITLE
Get term vectors in search result 

### ISSUE THREAD

**Issue by BitcoinKing** [elastic/elasticsearch#21668]
I am trying to get termvectors in search result:
https://www.elastic.co/guide/en/elasticsearch/reference/1.7/docs-termvectors.html

Now i use `s = s.highlight('title')` (http://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html)
to get part of highlighted text. The problem here is that i need manually process string to get actual search query words found.

I need to know for every result text what words it consist from search query. How?
(asked also https://discuss.elastic.co/t/get-termvectors-in-search-result/62508 but no response)

**Comment by jpountz** [comment]
Sorry for the lack of response on the discuss thread, I just left a suggestion there.
