### ISSUE TITLE
Documentation for BulkProcessor shows a bulk size of 1GB

### ISSUE THREAD

**Issue by ismael-hasan** [elastic/elasticsearch#21661]
The documentation for the [Java API, for bulk processing](https://www.elastic.co/guide/en/elasticsearch/client/java-api/5.0/java-docs-bulk-processor.html), shows in the example the following values:

```
.setBulkActions(10000)
.setBulkSize(new ByteSizeValue(1, ByteSizeUnit.GB))  
```

For bulk processes it is recommended to start small (10-15MB) and then start increasing until the sweet spot is found. Showing 1GB in the example code snippet can lead users to just copy-paste the code thinking that those are the correct/default values. 
The default values in the Java client API are conservative, 5MB and 1000 actions.

**Comment by dadoonet** [comment]
Closed by #21664
