### ISSUE TITLE
Custom jvm.options for multinode configuration

### ISSUE THREAD

**Issue by perarnetol** [elastic/elasticsearch#21672]
**Elasticsearch version**: 5.0.1
**Plugins installed**: 0
**JVM version**: 1.8.0_111
**OS version**: Centos 7

**Description of the problem including expected versus actual behavior**:
When running multiple instances of elasticsearch on the same server, it ignores the jvm.options file in conf dir.

**Steps to reproduce**:
 1. Install elasticsearch
 2. Create two conf folders /etc/elasticsearch/node1 and /etc/elasticsearch/node2
 3. Edit config files in both folders
Try to run nodes, and settings in the individual jvm.options files, like heap size, is ignored.

A workaround is to set ES_JAVA_OPTS with individual settings in the /etc/sysconfig/elasticsearch-nodeX file, this works.

**Comment by jasontedor** [comment]
You can use `ES_JVM_OPTIONS` to specify a custom path for the JVM options file.
