### ISSUE TITLE
No deduplication in completion suggester ES 5.0

### ISSUE THREAD

**Issue by devlo** [elastic/elasticsearch#21676]
Hi,
I've used output deduplication feauture in completion suggester in ElasticSearch 2.x but after upgrade to 5.0 completion suggester is unusable because of lack of deduplication. 
This regression kills completion suggester and upgrade to 5.0+ for anyone that uses completion suggester output like this in ES 2.x (from what i searched in issues I was not the only one using it like that). 

Is there a plan to implement that? Or how can I get the same behavior now?

**Comment by clintongormley** [comment]
Hi @devlo 

Deduplication was something that users complained about.  The new completion suggester is document oriented so there will be one document for every result, and there are no plans to change this.  The best plan is to maintain an index for the completion suggester which has one document per suggestion.
