### ISSUE TITLE
Expand /_cat/nodes to return information about hard drive (ES v5)

### ISSUE THREAD

**Issue by adamlepkowski** [elastic/elasticsearch#21679]
Hi, the purpose of a /_cat/nodes API is to provide information about node cluster topology. Currently response contains extensive information about heap, memory, cpu and load but there is only one information about hard drive - disk.avail. Shouldn't we have there more information about hard drive like disk.used disk.avail disk.total disk.percent?

**Comment by agebhar1** [comment]
Hi, got started to implement this low hanging fruit ...
