### ISSUE TITLE
did I get to the upper limit of /bulk upload API ?

### ISSUE THREAD

**Issue by small-tomorrow** [elastic/elasticsearch#21678]
After upgrade from V 2.1.0 to V 5.0.0,  I seemed to be  so easy to got a OOM ERROR using /bulk api to upload data .few minutes after my service started, I would receive this :' [gc][91065] overhead, spent [16.5s] collecting in the last [16.5s]
java.lang.OutOfMemoryError: Java heap space ' .  **What is the  upper limit of ／bulk API ?** 
I have just gave **32G to ES**, and my total memory size is 90G, more , part of my elasticsearch.yml is : 

script.engine.groovy.inline.aggs: on

indices.fielddata.cache.size: 40%
indices.breaker.fielddata.limit: 60%
indices.breaker.request.limit: 40%
indices.breaker.total.limit: 70%
thread_pool.bulk.queue_size: 5000

**However, I hava 1 billion of items(documents) to upload every day , any advice ?**
@clintongormley  @matschaffer

**Comment by dadoonet** [comment]
Please ask your questions on discuss.elastic.co. 
And read https://discuss.elastic.co/t/about-the-elasticsearch-category/21/1

Don't directly ping people like this and let folks decide to which question they want to answer.

**Comment by small-tomorrow** [comment]
okay, sorry for disturbe
