### ISSUE TITLE
index creation limitation

### ISSUE THREAD

**Issue by culiangfanzi** [elastic/elasticsearch#21684]
here is the prolem, when we used ES 2.X, we created indexes too much, about hundreds of indexes per day so the ES stucked when creating indexes (the index creation process was very slow). 
Is there any limitation about indexes count ?  Is the es service available (can accept queries ) when creating indexes?
thanks a lot for hearing from you ...

**Comment by dadoonet** [comment]
Please ask your questions on discuss.elastic.co. We can better help there.
This space is only for confirmed issues.
Thanks.

**Comment by clintongormley** [comment]
@culiangfanzi currently there is no limitation on the number of indices you can create.  There are two possibilities we are looking at:

* The max number of shards per node: https://github.com/elastic/elasticsearch/issues/20705
* Limiting index creation rate: https://github.com/elastic/elasticsearch/issues/20760

See https://github.com/elastic/elasticsearch/issues/11511 for more safeguards
