### ISSUE TITLE
Sort by nested string field yields unexpected results

### ISSUE THREAD

**Issue by orweinberger** [elastic/elasticsearch#21685]
**Elasticsearch version**:2.4.1

**JVM version**: 1.8.0

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:

When sorting on nested string fields, we get a `null` sorting value and results are unsorted.

**Steps to reproduce**:
 1. Set the mapping for the index with a nested string field:

```
"normalized": {
  "type": "nested",
  "properties": {
    "timestamp": {
    "index": "not_analyzed",
    "type": "string"
    }
  }
}
```
 2. Insert a few documents and run the following query:

```
"sort": {
    "normalized.timestamp": {
      "order": "desc"
    }
}
````
 3. Notice the `sort` key in the results returning as `null`

**Notes**:

It's important to note that although the field name is `timestamp` it contains a string, however to my understanding, range queries and sorting should still work, my timestamp format is: `2016-11-20T12:57:27.493000Z`

When I run the same query in v1.7.4 results are returned correctly, also, looking at the documentation it looks like I might need to change the sort to:

```
  "sort": [
    {
      "normalized.timestamp": {
        "order": "desc",
        "nested_filter": {
          "range": {
            "normalized.timestamp": {
              "gte": "2016-11-20T00:00:00",
              "lte": "2016-11-20T23:59:59"
            }
          }
        }
      }
    }
  ]
```

However, running this in v2.4.1 also yields a `null` for the sort key and results are returned unsorted.
I went through the breaking changes between 1.x and 2.x and couldn't find any mention to something that may interfere with the above search. Another thing I tried and **did** work was using `inner_hits` but this looks like a bit of a workaround and I would much prefer just using sort in the top level DSL.

**Comment by jpountz** [comment]
Can you try:

```
  "sort": [
    {
      "normalized.timestamp": {
        "nested_path": "normalized",
        "order": "desc"
        }
      }
    }
  ]
```

**Comment by orweinberger** [comment]
This works, not sure how I missed this in the docs. Thanks!
