### ISSUE TITLE
_index can't replace indicesQuery for Multi - index have parent query

### ISSUE THREAD

**Issue by libenyang** [elastic/elasticsearch#21699]
**Elasticsearch version**:
5.0.0
**Plugins installed**: []

**JVM version**:

**OS version**:
cent OS
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:
elasticsearch 5.0.x will  replace indicesQuery  with _index，but in this case _index is not useful：
I have muti gis index and muti type A-a B-b C-c,and I want search in all type and Index with have parent query.
so I should use boolQuery for each type have parent query. and I must use indicesQuery for each subquery,If not there is error because search in index which have no that type.
but use _index is still have this error,so _index can't replace indicesQuery for Multi - index have parent query

**Comment by clintongormley** [comment]
I have no idea what you're talking about.  Could you provide a recreation of the problem in curl please?

**Comment by libenyang** [comment]
Sorry, I did not describe the problem clearly
for example：
Sorry, I did not describe the problem clearly
for example
There are two indexes and types of parent documents
indicesQuery is ok，Using _index will have an error type that does not exist in the index 
{
  "bool" : {
    "should" : [
      {
        "indices" : {
          "indices" : [
            "sp_gs"
          ],
          "query" : {
            "bool" : {
              "must" : [
                {
                  "has_parent" : {
                    "query" : {
                      "bool" : {
                        "should" : [
                          {
                            "term" : {
                              "da" : {
                                "value" : "商品",
                                "boost" : 1.0
                              }
                            }
                          },
                          {
                            "match_phrase" : {
                              "s_0_da" : {
                                "query" : "商品",
                                "analyzer" : "ik_max_word",
                                "slop" : 0,
                                "boost" : 1.0
                              }
                            }
                          }
                        ],
                        "disable_coord" : false,
                        "adjust_pure_negative" : true,
                        "boost" : 1.0
                      }
                    },
                    "parent_type" : "gs",
                    "score" : true,
                    "ignore_unmapped" : false,
                    "boost" : 1.0
                  }
                }
              ],
              "filter" : [
                {
                  "term" : {
                    "district" : {
                      "value" : "浙江省温州市",
                      "boost" : 1.0
                    }
                  }
                }
              ],
              "disable_coord" : false,
              "adjust_pure_negative" : true,
              "boost" : 1.0
            }
          },
          "no_match_query" : {
            "match_none" : {
              "boost" : 1.0
            }
          },
          "boost" : 1.0
        }
      },
      {
        "indices" : {
          "indices" : [
            "sp_go"
          ],
          "query" : {
            "bool" : {
              "must" : [
                {
                  "has_parent" : {
                    "query" : {
                      "bool" : {
                        "should" : [
                          {
                            "term" : {
                              "da" : {
                                "value" : "商品",
                                "boost" : 1.0
                              }
                            }
                          },
                          {
                            "match_phrase" : {
                              "s_0_da" : {
                                "query" : "商品",
                                "analyzer" : "ik_max_word",
                                "slop" : 0,
                                "boost" : 1.0
                              }
                            }
                          }
                        ],
                        "disable_coord" : false,
                        "adjust_pure_negative" : true,
                        "boost" : 1.0
                      }
                    },
                    "parent_type" : "go",
                    "score" : true,
                    "ignore_unmapped" : false,
                    "boost" : 1.0
                  }
                }
              ],
              "filter" : [
                {
                  "term" : {
                    "district" : {
                      "value" : "浙江省温州市",
                      "boost" : 1.0
                    }
                  }
                }
              ],
              "disable_coord" : false,
              "adjust_pure_negative" : true,
              "boost" : 1.0
            }
          },
          "no_match_query" : {
            "match_none" : {
              "boost" : 1.0
            }
          },
          "boost" : 1.0
        }
      }
}

**Comment by clintongormley** [comment]
That's what the `ignore_unmapped` option is for:

```
PUT one
{
  "mappings": {
    "one_parent": {},
    "one_child": {
      "_parent": {
        "type": "one_parent"
      }
    }
  }
}

PUT two
{
  "mappings": {
    "two_parent": {},
    "two_child": {
      "_parent": {
        "type": "two_parent"
      }
    }
  }
}

PUT one/one_parent/1
{}

PUT one/one_child/2?parent=1
{}

PUT two/two_parent/1
{}

PUT two/two_child/2?parent=1
{}

GET one,two/_search
{
  "query": {
    "bool": {
      "should": [
        {
          "has_child": {
            "ignore_unmapped": true,
            "type": "one_child",
            "query": {
              "match_all": {}
            }
          }
        },
        {
          "has_child": {
            "ignore_unmapped": true,
            "type": "two_child",
            "query": {
              "match_all": {}
            }
          }
        }
      ]
    }
  }
}

```

**Comment by libenyang** [comment]
thanks for your answer
