### ISSUE TITLE
rest.exception.stacktrace.skip no longer works

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#21708]
```
$ POST /hockey/player/1/_explain?rest.exception.stacktrace.skip=false
request [/hockey/player/1/_explain] contains unrecognized parameter: [rest.exception.stacktrace.skip]
```

This parameter is super useful for debugging.

**Comment by nik9000** [comment]
@jasontedor pointed out to me that `rest.exception.cause.skip` is also missing as well. I don't really use that one but it is indeed missing.

**Comment by s1monw** [comment]
@nik9000 can you get a PR up for this?

**Comment by nik9000** [comment]
> @nik9000 can you get a PR up for this?

Yeah, I'm happy to do it in a bit. I'll self assign. If someone else wants it just grab it.

**Comment by nik9000** [comment]
Working on this now - it turns out those parameters were always intended to be internal. They just happened to actually work. The right parameter is `error_trace`. I'm going to document it and close the issue.

**Comment by nik9000** [comment]
I pushed some docs and tests:
Master: 17916237005f0eedc4de8587b3927731be215d6f
5.x: 1e25314c07a61bc0fa8c2ec3525380202705b894
5.0: 345949c02bbbcaf03a528bef56894172383a0156
