### ISSUE TITLE
`query_string` query mismatch when using multiple analyzers with and without stop words removal

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#21712]
When using the `query_string` with default_operator set to AND on two fields, one with stop words removal and the other without, the stop words become mandatory for the fields that don't remove them. 
Consider for instance this mapping:

````
PUT t
{
   "mappings": {
      "t": {
         "properties": {
            "text": {
               "type": "text",
               "analyzer": "text_analyzer"
            },
            "text_stop": {
               "type": "text",
               "analyzer": "text_stop_analyzer"
            }
         }
      }
   },
   "settings": {
      "index": {
         "analysis": {
            "analyzer": {
               "text_stop_analyzer": {
                  "filter": [
                     "lowercase",
                     "stop"
                  ],
                  "type": "custom",
                  "tokenizer": "standard"
               },
               "text_analyzer": {
                  "filter": [
                     "lowercase"
                  ],
                  "type": "custom",
                  "tokenizer": "standard"
               }
            }
         }
      }
   }
}
````

The following query:
````
GET t/_validate/query?explain
{
   "query": {
      "query_string": {
         "query": "the doors",
         "fields": [
            "text",
            "text_stop"
         ],
         "default_operator": "AND"
      }
   }
}
````
... produces:

````
{
   "valid": true,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "explanations": [
      {
         "index": "t",
         "valid": true,
         "explanation": "+(text:the) +(text:doors | text_stop:doors)"
      }
   ]
}
````

... so "the" must be present in the field "text". This is problematic since it means that document like the following won't match:
````
PUT t/t/1
{
    "text": "the doors"
}
````

As a workaround we could make "the" optional since it has been removed from some fields ?:

````
 "explanation": "(text:the) +(text:doors | text_stop:doors)"
````

**Comment by jimczi** [comment]
Discussed in FixItFriday, `cross_fields` based on whitespace split is not going to work in a lot of use cases so the ultimate solution would be to treat `cross_fields` like the `multi_match` does. It means that `cross_fields` should only be executed on fields that share the same analyzer. Now that `split_on_whitespace` is integrated in the `query_string` it should be feasible to reconcile `multi_match` and `query_string`. With this approach the example shown above would create a query like the following:
```
  "explanation": "+(+text:the +doors) | +(+text_stop:doors)"
```
which does not perform `cross_fields` since the two fields do not share the same analyzer.

**Comment by guilhermemaranhao** [comment]
Hello @jimczi , 

I'm facing a simpler issue related to query_string and stopwords and I'm suppose it has to do with 5.x version. In 2.4 version, I used query_string with default_operator: 'AND' and the analyzer: 'brazilian_stop_word' both set on it. And it worked perfectly: When one searched for some term containing a "stopword", the query_string ignored it and everything went fine.
Now, in 5.x, the same search seems not ignoring the "stopword" and so nothing is returned. As the searched field was indexed with the stopword analyzer, the stopword isn't indexed.
Does anybody know if there was a change in 5.x query_string related to stopword analysis? I didn't find anything in the breaking changes.

Thanks

**Comment by jimczi** [comment]
@guilhermemaranhao can you provide a simple recreation that exhibits the problem. I tried the following and it works fine:

`````
PUT t 
{
   "mappings": {
      "page": {
         "properties": {
            "text": {
               "type": "text",
               "search_analyzer": "brazilian",
               "analyzer": "brazilian"
            }
         }
      }
   },
   "settings": {
      "analysis": {
         "filter": {
            "brazilian_stop": {
               "type": "stop",
               "stopwords": "_brazilian_"
            }
         },
         "analyzer": {
            "brazilian": {
               "tokenizer": "standard",
               "filter": [
                  "lowercase",
                  "brazilian_stop"
               ]
            }
         }
      }
   }
}

GET t/_validate/query?explain
{
    "query": {
        "query_string": {
           "query": "tudo está bem",
           "default_field": "text",
           "default_operator": "AND",
           "analyzer": "brazilian"
        }
    }
}

GET t/_validate/query?explain
{
    "query": {
        "query_string": {
           "query": "tudo está bem",
           "default_field": "text",
           "default_operator": "AND"
        }
    }
}

{
   "valid": true,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "explanations": [
      {
         "index": "t",
         "valid": true,
         "explanation": "+text:está +text:bem"
      }
   ]
}
`````

**Comment by guilhermemaranhao** [comment]
Thank you so much @jimczi ! 

I've just realized that I'm using some fields in the query_string that aren't analyzed with the brazilian_stop_word_analyzer. In the previous 2.4 version, all the fields were analyzed by this brazilian analyzer, that's why it worked.

Kind regards,

Guilherme

**Comment by colings86** [comment]
@jimczi is this still an issue?

**Comment by jimczi** [comment]
Considering that we don't split on whitespace anymore in 6.0, this issue should not be a problem anymore unless explicit `AND`s are used. I think this is acceptable so I'll close this issue.
