### ISSUE TITLE
Documentation for index settings with a filter is incorrect.

### ISSUE THREAD

**Issue by trevan** [elastic/elasticsearch#21713]
The documentation at https://www.elastic.co/guide/en/elasticsearch/reference/5.0/indices-get-settings.html for "Filtering settings by name" is incorrect.

Instead of:
curl -XGET 'http://localhost:9200/2013-*/_settings/name=index.number_*'

It should be:
curl -XGET 'http://localhost:9200/2013-*/_settings/index.number_*'

**Comment by clintongormley** [comment]
thanks @trevan - fixed
