### ISSUE TITLE
Change in search slowlog format in 5.0+

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#21711]
Before 5.0 queries in the search slow log were reformatted by default into a single line and this behavior was controlled by undocumented `index.search.slowlog.reformat` setting that was set to `true` by default. By setting `index.search.slowlog.reformat` to `false` it was possible to turn this feature off and log search queries as they were sent by client and essentially switch slowlog to multiline format. 

Starting with 5.0 the `index.search.slowlog.reformat`setting is ignored on search slowlog and we always pretty print queries, which made slowlog multi-line with no option to get back to the previous behavior. 

The behavior of index slow log didn't change and I don't see anything related in breaking changes, which makes me think that this change might have been unintentional. 

I think we should document and restore the `index.search.slowlog.reformat` behavior or, alternatively, remove this setting since it's no longer used. I would personally prefer the former solution since dealing with multi-line logs can be quite painful. Thoughts?

**Comment by clintongormley** [comment]
+1 to restoring the option and making single-line by default

**Comment by makeyang** [comment]
+1 for single-line by fefault
