### ISSUE TITLE
Can't exclude analyzed field of a property from _all

### ISSUE THREAD

**Issue by Mates1500** [elastic/elasticsearch#21710]
**Elasticsearch version**: 2.4.1

**Plugins installed**: []

**JVM version**: 1.8.0_111

**OS version**: Ubuntu 14.04 LTS

**Description of the problem including expected versus actual behavior**:
Whenever I try to
```json
PUT /index/Content/_mapping

        "Content":{
          "properties":{
        "rawData":{
            "type":"string",
            "fields":{
                "czech":{
                  "type":"string",
                  "analyzer":"czech_html_strip",
                  "include_in_all": false
                }}
            },
        "title":{
            "type":"string",
            "fields":{
                "czech":{
                  "type":"string",
                  "analyzer":"czech_html_strip",
                  "include_in_all": false
                }}
            },
        "description":{
            "type":"string",
            "fields":{
                "czech":{
                  "type":"string",
                  "analyzer":"czech_html_strip",
                  "include_in_all": false
                }}
          }
          }}
```
I get back ```{"acknowledged": true}```, which means that everything should be fine?
However, when I GET the _mapping back, the `include_in_all` parameter is not present in the mapping at all. Is this the expected behavior? Setting this parameter to any of the `properties` themselves works just fine.

**Expected Behavior**: These three analyzed fields are completely ignored while searching through the `_all` field
**Actual Behavior**: The query is still taking the aforementioned fields into account

**Comment by clintongormley** [comment]
The bug is that we don't throw an exception when specifying `include_in_all` on sub-fields:

```
PUT t
{
  "mappings": {
    "t": {
      "properties": {
        "foo": {
          "type": "string",
          "fields": {
            "bar": {
              "type": "string",
              "include_in_all": false
            }
          }
        }
      }
    }
  }
}
```

@Mates1500 The value of each main field (not sub field) is copied to the `_all` field as a string, and the `_all` field applies its own analyzer.  Those fields are being included in all because don't specify `include_in_all` on the main fields.

**Comment by Mates1500** [comment]
> The value of each main field (not sub field) is copied to the _all field as a string, and the _all field applies its own analyzer. Those fields are being included in all because don't specify include_in_all on the main fields.

So is it possible to somehow **include the main field** in _all, **but not the sub field**? It does not necessarily have to be set in the mapping, I've been searching through the documentation for a long time but couldn't find anything useful for my specific case: 
I'm searching through a lot of types, each with about a dozen properties, so specifying every single property would really be a pain. The sub fields are there for the client front-end for language analysis, but they're pointless in the admin front-end where I'm just trying to search through everything _precisely_, without the analyzers transforming the entire thing around.

**Comment by clintongormley** [comment]
> So is it possible to somehow include the main field in _all, but not the sub field? 

It's the main field's string value which is included in all, not the tokens.  (The string value is the same for sub-fields, so there is no point in including it twice).  The _all field takes these string values and analyses them using the `standard` analyzer by default - this can be changed.  Or alternatively you can use `copy_to` to copy the fields you're interested in to a custom field with its own analyzer.

**Comment by Mates1500** [comment]
@clintongormley Yeah, you're right, I just found out that my web app has been using the client (nonadmin) service the whole time due to a routing bug in the framework, therefore I was still seeing the language analyzed subfields.
Though, in the end it's still good that this bug has been discovered. :+1:

**Comment by makeyang** [comment]
@clintongormley  I'd like pull request to fix it. but I got stucked in another pull. can you help to review & merge my pull so I can pull this one?
