### ISSUE TITLE
Feature: Built in prunning of indices by date

### ISSUE THREAD

**Issue by rsgross** [elastic/elasticsearch#21722]
If elasticsearch is being used for log aggregation then the elasticsearch cluster size can grow rapidly effecting performance and taking up valuable resources. Furthermore, if an organization is not concerned with archiving data past a certain date then they have to manually delete indices within that cluster every so often or create a process for pruning data which can be messy (e.g. a cron job).

I propose a feature solves this common problem within elasticsearch. There should be a rest endpoint that turns on a reoccurring process within elasticsearch that does just that. It should take an amount and unit to prune older indices by and should be asynchronously checked every so often on the backend.

**Comment by jasontedor** [comment]
Have you looked at using [Elasticsearch Curator](https://github.com/elastic/curator) for this?

**Comment by clintongormley** [comment]
hi @rsgross 

While this would indeed be useful, it is at odds with the type of features that we add to Elasticsearch core.  The core is intended to be like a kernel.  Features are added as primitives which can be used by applications built on top of core.

For instance the rollover and shrink APIs are primitives which allow index management tools to be added by an application, which also knows about scheduling and how to notify users when things go wrong.

As @jasontedor has said you should take a look at Curator.  We won't add this feature to core.  If we do add something like this, it'll be in X-Pack which builds on top of core.
