### ISSUE TITLE
json_parse_exception Numeric value out of range of long

### ISSUE THREAD

**Issue by max0x7ba** [elastic/elasticsearch#21728]
**Elasticsearch version**:
elasticsearch-5.0.0
metricbeat-5.0.1

**Plugins installed**:
None

**JVM version**:
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**OS version**:
Red Hat Enterprise Linux Server release 6.8 (Santiago) x86_64

**Description of the problem including expected versus actual behavior**:
Metricbeat sends `system.filesystem.files` field with value of 18446744073709551615, which is (2^64 - 1).

**Steps to reproduce**:
 1. Enable metricset `filesystem` in `metricbeat.modules` -> `module: system`,
 2. Start `metricbeat`.
 3. Observe the warning in the log.

**Provide logs (if relevant)**:
`2016-11-22T05:35:17-05:00 WARN Can not index event (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse [system.filesystem.files]","caused_by":{"type":"json_parse_exception","reason":"Numeric value (18446744073709551615) out of range of long (-9223372036854775808 - 9223372036854775807)\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@39fece1e; line: 1, column: 234]"}}`

**Comment by clintongormley** [comment]
Hi @max0x7ba 

This looks like an issue that should be opened on the metrics beat repo.  Elasticsearch doesn't have support for unsigned longs.
