### ISSUE TITLE
Dots in field names doesn't work with nested fields

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#21726]
On 5.0.1:

```
PUT t 
{
  "mappings": {
    "t": {
      "properties": {
        "foo": {
          "type": "nested"
        }
      }
    }
  }
}

PUT t/t/1
{
  "foo.bar": 5
}

PUT t/t/2
{
  "foo": {"bar": 5}
}

```

Returns Doc 1
```
GET t/_search
{
  "query": {
    "match": {
      "foo.bar": 5
    }
  }
}
```

Returns Doc 2
```
GET t/_search
{
  "query": {
    "nested": {
      "path": "foo",
      "query": {
        "match": {
          "foo.bar": 5
        }
      }
    }
  }
}

```

**Comment by jpountz** [comment]
I don't like the ambiguity that exists with dots in field names and nested mappings. For instance the below document:

```
{
  "foo.bar": 3,
  "foo.baz": 42
}
```

could be both equivalent to

```
{
  "foo": {
    "bar": 3,
    "baz": 42
  }
}
```

and

```
{
  "foo": [
    { "bar": 3 },
    { "baz": 42 }
  ]
}
```

which are indexed differently if `foo` is a nested object.

So should we reject dots in field names when the dot is a delimitation for a nested object?

**Comment by clintongormley** [comment]
> So should we reject dots in field names when the dot is a delimitation for a nested object?

I think we should.  How do we do this in a way that doesn't break behaviour in a minor version?

**Comment by jpountz** [comment]
> How do we do this in a way that doesn't break behaviour in a minor version?

The bug fix consists of raising an error, so I don't think there is any way to fix the bug and not break in a minor release at the same time. I see this bug as an index corruption since fields do not go to the intended document so I would vote to raise an error in all cases rather than trying to keep the bug for old indices.

**Comment by Thermi** [comment]
It might be, that we're hitting this issue in ElasticSearch 2.4.2, as well. In our case, we use fields whose names have dots in them. We're running queries on them with range filters inside a boolean filter and the query returns documents that have values outside the defined range. Does this bug pertain the issue I'm seeing as well?

**Comment by clintongormley** [comment]
@Thermi hard to say - i'd open a new issue providing a full curl recreation of what you're seeing and we can go from there

**Comment by Thermi** [comment]
Please disregard the sentence about dots in field names. That's not the case. I'll open a new issue on this repo for the problem I'm seeing.
