### ISSUE TITLE
Use field name 'ownerid' with mapping

### ISSUE THREAD

**Issue by hubsn** [elastic/elasticsearch#21724]
**Elasticsearch version**:
2.4.1

**Plugins installed**: no

**JVM version**:
1.8

**OS version**:
CentOS Linux release 7.2.1511 (Core)

**Description of the problem including expected versus actual behavior**:
I want to map with name 'ownerid' of the field, but It doesn't process. Following error returned.
```
http://127.0.0.1:9200/example_index/_mapping/example_type
{
  "properties": {
    "ownerid": {
      "type": "long"
    }
  }
}
```
```json
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "mapper [ownerid] cannot be changed from type [int] to [long]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "mapper [ownerid] cannot be changed from type [int] to [long]"
  },
  "status": 400
}
```

I guess... The 'ownerid` is reserved thing..., isn't it?

**Comment by dadoonet** [comment]
Please ask for help on discuss.elastic.co.

Not an issue here. The `ownerid` field has been defined previously so you can't change it. You need to delete your index and create it again.

**Comment by hubsn** [comment]
@dadoonet 
I never defined 'ownerid' to field. Just first trying of mapping. It's weird. So I had issued.
Could you check this in 2.4.1 version? It will reproduce.
Thanks.

**Comment by dadoonet** [comment]
I just ran a test on 2.4.1:

```
DELETE test
PUT test
PUT test/_mapping/type
{
  "properties": {
    "ownerid": {
      "type": "long"
    }
  }
}
```

It gives:

```json
{
  "acknowledged": true
}
```

But let's continue the discussion at https://discuss.elastic.co/t/are-there-reserved-fields-in-a-document/66935

**Comment by hubsn** [comment]
@dadoonet 
Really thanks. I commented that [discuss](https://discuss.elastic.co/t/are-there-reserved-fields-in-a-document/66935).
