### ISSUE TITLE
Query with a search value and a sort on field name type, results in error.

### ISSUE THREAD

**Issue by jjettenn** [elastic/elasticsearch#21725]
**Elasticsearch version**: 1.7.3

**Plugins installed**: []

**JVM version**: Java(TM) SE Runtime Environment (build 1.8.0_112-b16)

**OS version**: 10.10.5 (14F2009) OS X Yosemite

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
1. Use MOLGENIS 2.0-RC
2. Upload: [emx_all_datatypes.xlsx](https://github.com/elastic/elasticsearch/files/605879/emx_all_datatypes.xlsx)
3. Go to data explorer -> select Attribute.
4. Search: xbool
5. Sort on Data type 

**Provide logs (if relevant)**:
Error! Failed to execute phase [query], all shards failed; shardFailures {[Q32gpkcGTrK7fIF2swhC2g][molgenis][0]: SearchParseException[[molgenis][0]: query[_all:typetest],from[0],size[20]: Parse Failure [Failed to parse source [{"from":0,"size":20,"query":{"match":{"_all":{"query":"TypeTest","type":"phrase","slop":10}}},"sort":[{"type.raw":{"order":"asc","mode":"min"}}]}]]]; nested: QueryParsingException[[molgenis] [nested] failed to find nested object under path [type]]; }

**Describe the feature**:
It seems that a field name type is causing this problem. Changing the name of the attribute into dataType (not type) is fixing the problem.

**Comment by dadoonet** [comment]
I don't think you opened this issue in the right repo. You should report that problem in https://github.com/molgenis/molgenis repo instead, no?

Closing as I think it's not something we can solve on our end.
