### ISSUE TITLE
FileBasedDiscovery causes connections on every ping round

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#21739]
Currently `UnicastHostsProvider#buildDynamicNodes` is called multiple times during the pinging rounds. Once on start, one more after 1.5 seconds (by default) and last time at the end (3s by default).  My guess is that this done in an attempt to get the latest information possible when connect to EC2 / GCE/ Azure's API. This does have a nasty side effect on the FileBasedUnicastHostsProvider, which currently reads it's file on ever call. The file reading is not a problem on it's own as it is just as fast as an EC2 call. The problem part is that each read generates nodes with new node ids, meaning that UnicastZenPing will setup new connections with each of these rounds. 

I see two relatively easy ways of solving it:
1) Call `buildDynamicNodes` once at the beginning of each round (might be the simplest).
2) Add an "onStartPing" method to `UnicastHostsProvider` which is guaranteed to be called at the beginning of each pinging round. `FileBasedDiscovery` can read the file contents in that method.

**Comment by rjernst** [comment]
+1 to option number 1

**Comment by bleskes** [comment]
I marked this as an adopt me. It's a fairly easy entry into the discovery universe. If anyone want's to pick it up, ping me and I'll help get going.

**Comment by makeyang** [comment]
@bleskes I want's to pick this up.

**Comment by bleskes** [comment]
@makeyang good to hear. @chengpohi already made an attempt. Not sure if he (judging by avatar) plans to continue with it....
