### ISSUE TITLE
More informative stack trace for Painless

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#21733]
**Describe the feature**:

Currently when a painless script cannot be compiled, the error looks something like this:

```
[2016-11-22T14:16:11,800][WARN ][o.e.s.ScriptService      ] [rcl-nas] failed to load/compile script [sensors-count-transform]
org.elasticsearch.script.ScriptException: compile error
...
Caused by: java.lang.IllegalArgumentException: invalid sequence of tokens near [':'].
        at org.elasticsearch.painless.Executable$Script.compile(sensors-count-transform.painless:104) ~[?:?]
...
```

In this case the number 104 is not very helpful in determining the actual location of the error - it would be much more helpful if the error could output the actual line and character number where the syntax error occurred.

**Comment by nik9000** [comment]
This looks useful and involves knocking ANTLR parsers around which is one of my favorite things to do! I used to do it for fun! No joke!

**Comment by nik9000** [comment]
Or maybe it is "just" making sure the script stack we generate is properly rendered in this context. I dunno! I find out in a bit.

**Comment by jdconrad** [comment]
Since this is an actual ANTLR syntax error, I think the place to work on this would be ParserErrorStratery under painless.input.  There is a ton of work than can be done here to specialize on our errors and make them better based on the context.

**Comment by nik9000** [comment]
Most of the right data is already there. Here is a snippet of what we return if you try to search with a broken script:
```
          "caused_by" : {
            "type" : "script_exception",
            "reason" : "compile error",
            "caused_by" : {
              "type" : "illegal_argument_exception",
              "reason" : "invalid sequence of tokens near ['String'].",
              "caused_by" : {
                "type" : "no_viable_alt_exception",
                "reason" : null
              }
            },
            "script_stack" : [
              "boolean String errr; doc['num1']. ...",
              "        ^---- HERE"
            ],
            "script" : "boolean String errr; doc['num1'].value > 1;",
            "lang" : "painless"
          }
```

The two important bits are "`invalid sequence of tokens near ['String'].`" and 
```
            "script_stack" : [
              "boolean String errr; doc['num1']. ...",
              "        ^---- HERE"
            ],
```

It'd be nice if we returns less stuff though. I'm not 100% sure how much stuff it is safe to remove though.

**Comment by nik9000** [comment]
I've been digging into `script_stack` a bit this morning. I think I'll open a few PRs around it and the error reporting in general related to this issue. I don't know that they'll close the issue, just make things better. I'm not sure what we should do to close the issue, actually. But here are some things I'm going to work on:

1. Add tests for the script_stack and its rendering in REST responses.
2. Remove some code duplication around generating it.
3. Have a look at what gets included. Right now it stops the first time it sees your script which feels like it is missing some useful information when there are function calls and lambdas.
4. Some error messages to in addition to `compile error` and `runtime error` so that the `root_cause` field is more useable.

**Comment by rjernst** [comment]
@robin13 Did you see that error in your logs, because this script is a file script? I think we could improve the log message for compile errors from file scripts so it is more like what we see from inline scripts in requests.

**Comment by robin13** [comment]
@rjernst Yes - it was in the elasticsearch logs after updating a file script.

**Comment by nik9000** [comment]
> @rjernst Yes - it was in the elasticsearch logs after updating a file script.

Ah! I hasn't thought about file scripts. Making the log on file script compilation nice is a much simpler thing.

**Comment by nik9000** [comment]
I mean, I should have known from the log line in the issue description....

**Comment by nik9000** [comment]
On later reflection, I think #21767 is enough to close this so I'm gonna close it. @robin13, please reopen if you disagree. Here is an example of script compilation failure on startup now:
```
[2016-11-28T11:45:10,803][WARN ][o.e.s.ScriptService      ] [0XjgN0T] failed to load/compile script [foo]: {
  "type" : "script_exception",
  "reason" : "compile error",
  "caused_by" : {
    "type" : "illegal_argument_exception",
    "reason" : "unexpected token ['adsf'] was expecting one of [{<EOF>, ';'}]."
  },
  "script_stack" : [
    "asdf adsf adsf \n",
    "     ^---- HERE"
  ],
  "script" : "asdf adsf adsf \n",
  "lang" : "painless"
}
```

Elasticsearch still starts but you get the warning. It isn't perfect, but I think it is much better than it was before.

**Comment by robin13** [comment]
Thank you @nik9000 - that looks much better! :)
