### ISSUE TITLE
path.data is not pruned after node rejoins

### ISSUE THREAD

**Issue by tomsommer** [elastic/elasticsearch#21746]
**Elasticsearch version**: 5.0.1

I have multiple nodes who rejoined my cluster and so initiated a rebalance. This is all fine, but the nodes are now exceeding their watermark threshold because the master/node does not recognize the stale data from when the node left the cluster.

Shouldn't stale data be pruned from the nodes when they rejoin? Or do I need to wipe `path.data` manually from each node?

**Comment by clintongormley** [comment]
@tomsommer stale data is only cleaned up after shards have been allocated correctly, otherwise we run the risk of losing data if something else goes wrong later on.

**Comment by clintongormley** [comment]
I'd imagine though that, given time, it'd manage to restore one index, then wipe the old shards, leaving more space for the next index etc.  Can you provide more info about what you're seeing, and any custom settings that you have?

**Comment by tomsommer** [comment]
After the restart I saw almost twice the disk usage on each node, compared to after the rebalance was complete. This leads me to think a complete rebalance and prune was done (total data shift on all nodes). This is a bit alarming, as this means a potential cluster restart could lead to a x2 disk-requirement depending on how the nodes recover? But perhaps this is unavoidable and I hit an edge case.

A wipe of old/stale data on the nodes does seem to have happened though and node diskusage is back to normal after the rebalance.

**Comment by clintongormley** [comment]
@tomsommer i think you were unlucky, you shouldn't normally see all data shift around.  Also, if your disks are near full, then shards shouldn't be moved TO that node, so I think we're OK here.
