### ISSUE TITLE
Pre-registered indexed search template not working 

### ISSUE THREAD

**Issue by svola** [elastic/elasticsearch#21747]
I have worked with Search-Templates before. In older versions of ES it worked.
But now in ES 5.0.1 it is not working anymore.
I'm following the docs here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html#pre-registered-templates

	POST /_search/template/template1
	{
	  "template": {
	    "size": 10,
	    "query": {
	      "multi_match": {
		"query": "{{query_string}}",
		"fields": [
		  "description",
		  "title"
		]
	      }
	    }
	  }
	}

	GET /_search/template
	{
	    "id": "template1", 
	    "params": {
		"query_string": "search for these words"
	    }
	}

Storing the template returns a success message.

Searching returns:

	{
	  "error": {
	    "root_cause": [
	      {
		"type": "illegal_state_exception",
		"reason": "There are no external requests known to support wildcards that don't support replacing their indices"
	      }
	    ],
	    "type": "illegal_state_exception",
	    "reason": "There are no external requests known to support wildcards that don't support replacing their indices"
	  },
	  "status": 500
	}

The .scripts index is empty aswell.

Is the documentation wrong or is it a bug?

**Comment by clintongormley** [comment]
@svola you didn't mention that you have x-pack installed.  this is a bug with the interaction between search templates and x-pack security.  If you specify an index it'll work (eg `GET my_index/_search/template`)

We'll work on a fix for the search template API

**Comment by svola** [comment]
@clintongormley Sorry I wasn't aware of x-pack. By specifying the search index it works. Thanks!

**Comment by svola** [comment]
Ok now I tried to run "render_template" and it leads to the same issue.
Adding an index before _render didn't help...

	GET _search/template/list_main_entity_0.0.1

	{
	  "lang": "mustache",
	  "_id": "list_main_entity_0.0.1",
	  "found": true,
	  "template": "{\"size\":10,\"query\":{\"multi_match\":{\"query\":\"{{query_string}}\",\"fields\":[\"description\",\"title\"]}}}"
	}



	GET /_render/template/list_main_entity_0.0.1
	{
	  "params": {
	    "query_string" : "test"
	  }
	}



	{
	  "error": {
	    "root_cause": [
	      {
		"type": "illegal_state_exception",
		"reason": "There are no external requests known to support wildcards that don't support replacing their indices"
	      }
	    ],
	    "type": "illegal_state_exception",
	    "reason": "There are no external requests known to support wildcards that don't support replacing their indices"
	  },
	  "status": 500
	}

**Comment by javanna** [comment]
yes @svola we are aware of that too. Render doesn't accept indices. You can work around it till a fix is out using the `/_search/template` endpoint with `simulate` set to `true` which does the same as what the render template endpoint does, but also allows setting the indices.

**Comment by svola** [comment]
@javanna Where exactly should that simulate-parameter go?

**Comment by javanna** [comment]
@svola nowhere, I am sorry, I got confused. The issue with the render endpoint cannot be worked around at the moment. We just have to release a fix.

**Comment by javanna** [comment]
Heads up, we have fixed this bug, this issue will be resolved with the 5.1 release. The render endpoint is problematic and there is no easy fix. As for the search template endpoint, the issue can worked around in 2.4.2 and 5.0.x by either using explicit indices or the deprecated template query as part of the search endpoint (rather than the search template endpoint).
