### ISSUE TITLE
Documentation about search template is inexact

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#21755]
In this doc: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html

We wrote that such a query:

```json
GET /_render/template
{
  "inline": {
    "query": {
      "terms": {
        "status": [
          "{{#status}}",
          "{{.}}",
          "{{/status}}"
        ]
      }
    }
  },
  "params": {
    "status": [ "pending", "published" ]
  }
}
```

Generates:

```json
{
  "template_output": {
    "query": {
      "terms": {
        "status": [ 
          "pending",
          "published"
        ]
      }
    }
  }
}
```

It's actually not exact. I just tried it out with 5.0.1 and got:

```json
{
  "template_output": {
    "query": {
      "terms": {
        "status": [
          "",
          "pending",
          "",
          "published",
          ""
        ]
      }
    }
  }
}
```

@MaineC WDYT? Is it a bug or a documentation issue?

**Comment by tlrx** [comment]
It is due to the way Mustache works. I remember I found an issue about this on the Mustache repo but I can't find it again.

**Comment by clintongormley** [comment]
This is from old documentation.  In fact in 2.3, we document this output:  https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-template.html

In 5.0, we changed the example to use `toJson`: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-template.html#_converting_parameters_to_json
