### ISSUE TITLE
Validate pom files

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#21758]
We currently build pom files for elasticsearch artifacts when running `gradle assemble`. We should validate these pom files, eg to ensure they don't contain broken xml, duplicate sections, valid tag names, etc.

**Comment by dadoonet** [comment]
Related to #21338 I guess?

**Comment by rjernst** [comment]
Yes, I think it is related. It could be that #21338 satisfies the goal here.

**Comment by rjernst** [comment]
Closing in favor of #21338
