### ISSUE TITLE
Add request or index details in Task Management API

### ISSUE THREAD

**Issue by cwurm** [elastic/elasticsearch#21768]
**Describe the feature**:
It would be nice to see the original request or details about affected indexes In the output of `_tasks`.

E.g. `GET /_tasks?detailed=true&actions=*reindex&pretty` provides no information about what it's working on, making it hard to know which task corresponds to which reindexing job currently running.

**Comment by clintongormley** [comment]
@imotov is this similar to what you're doing in https://github.com/elastic/elasticsearch/pull/21740 ?

**Comment by imotov** [comment]
@clintongormley yes, it's pretty much the same only for a different set of requests.

**Comment by imotov** [comment]
@cwurm adding a task description is relatively simple process for a single request, however we have close to 100 different requests and it's not really possible (or useful) to add task descriptions to all of them at the same time. I have opened PR for reindex, update-by-query and delete-by-query commands. If you can think of other tasks for which you would like to prioritize adding proper descriptions, please list them on this issue.

**Comment by cwurm** [comment]
@imotov The one other I can think of is snapshot/restore. However I didn't check if that one already has an informative description.

**Comment by imotov** [comment]
@cwurm They don't. I just opened #21901 to fix that. I am also planning to add a description to bulk request next. I think that should cover most of the users' needs.

**Comment by bleskes** [comment]
Closing as the issue description is too broad to be actionable (doesn't mean it isn't valid). Some of it has been picked up already.
