### ISSUE TITLE
Wildcard query fails when one document has missing field

### ISSUE THREAD

**Issue by xgp** [elastic/elasticsearch#21761]
**Elasticsearch version**: 5.0.1

**Plugins installed**: [x-pack]

**JVM version**: 1.8.0_102

**OS version**: Linux version 3.16.0-55-generic (buildd@lgw01-42) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) \#74~14.04.1-Ubuntu SMP Tue Nov 17 10:15:59 UTC 2015

**Description of the problem including expected versus actual behavior**: When searching documents with a wildcard query, the query will fail if one document is inserted with an empty value for the field that is being searched. The expected behavior is that the same results will be returned, without the documents with the missing field.

**Steps to reproduce**:
 1. Index some documents:
```
$ curl --user elastic:changeme -XPUT "http://localhost:9200/test/event/1" -d'
{
  "@timestamp": "2016-11-23T16:12:33.000+0000",
  "name": "XYZ.abc.FAILURE",
  "message": "test"
}'

$ curl --user elastic:changeme -XPUT "http://localhost:9200/test/event/2" -d'
{
  "@timestamp": "2016-11-23T15:12:33.000+0000",
  "name": "ABC.xyz.SUCCESS",
  "message": "test"
}'

$ curl --user elastic:changeme -XPUT "http://localhost:9200/test/event/3" -d'
{
  "@timestamp": "2016-11-23T15:12:33.000+0000",
  "name": "ABC.xyz.FAILURE",
  "message": "test"
}'
```
 2. Do a wildcard search on term 'name':
```
$ curl --user elastic:changeme -XGET "http://localhost:9200/test/event/_search" -d'
{
    "query": {
        "wildcard" : { "name.keyword" : "ABC*" }
    }
}
```
Which yields the results:
```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": 1,
    "hits": [
      {
        "_index": "test",
        "_type": "event",
        "_id": "2",
        "_score": 1,
        "_source": {
          "@timestamp": "2016-11-23T15:12:33.000+0000",
          "name": "ABC.xyz.FAILURE",
          "message": "test"
        }
      },
      {
        "_index": "test",
        "_type": "event",
        "_id": "1",
        "_score": 1,
        "_source": {
          "@timestamp": "2016-11-23T15:12:33.000+0000",
          "name": "ABC.xyz.SUCCESS",
          "message": "test"
        }
      }
    ]
  }
}
```
 3. Add one more document with missing field 'name':
```
$ curl --user elastic:changeme -XPUT "http://localhost:9201/test/event/4" -d'
{
  "@timestamp": "2016-11-23T15:12:33.000+0000",
  "message": "test"
}'
```
4. Repeat the search in \#2 above. All the documents are returned.

**Comment by xgp** [comment]
Also note that when I do the query in kibana discover (i.e. "name.keyword:ABC*"), it **highlights** the correct fields, but still returns all documents

**Comment by clintongormley** [comment]
@xgp When I try your recreation, step 4 returns just the same two documents as in step 2.  You want to try it again and see if you've changed something in the recreation?

If you're still seeing this behaviour, run the following and paste the result:

```
GET /test/_validate/query?explain
{
  "query": {
    "wildcard": {
      "name.keyword": "ABC*"
    }
  }
}
```

**Comment by xgp** [comment]
It seemed to do it intermittently for a while, and then settle on returning the correct two results. Does ES cache GET searches?

**Comment by clintongormley** [comment]
> Does ES cache GET searches?

it caches agg results, but not hits.

**Comment by colings86** [comment]
No further feedback so closing this issue, if you can still reproduce the issue please reopen and post a recreation script.
