### ISSUE TITLE
regexp query fails when field has a "/" in the data. (string/text)

### ISSUE THREAD

**Issue by kvesterling** [elastic/elasticsearch#21763]
**Elasticsearch version**:  5.0.0

**Plugins installed**: X-Pack

**JVM version**: 1.8.0_112

**OS version**: CentOS Linux release 7.2.1511

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Create a field in a document.
 2. Populate that field with data that contains a "/" (slash) like say "Ethernet9/5"
 3. Query using a regexp with something like "Ethernet9.*5" or "Ethernet9\/5"
 4. Raise eyebrows at lack of results.

**Comment by dadoonet** [comment]
If you are using the default analyzer, that's expected.

**Comment by clintongormley** [comment]
@kvesterling see https://www.elastic.co/guide/en/elasticsearch/guide/2.x/_wildcard_and_regexp_queries.html

**Comment by kvesterling** [comment]
Yes, I have seen that one...  Strange thing is, the bug is even prevalent when performing searches in Kibana...  Which is very odd, I've attempted escaping the "/" with \, \\, even attempted to match the slash with .*

**Comment by kvesterling** [comment]
Observe:

<img width="379" alt="screen shot 2016-11-25 at 9 13 11 am" src="https://cloud.githubusercontent.com/assets/13852287/20627691/a566dbd8-b2ef-11e6-8ef9-d93a4f9d18b9.png">
<img width="423" alt="screen shot 2016-11-25 at 9 14 49 am" src="https://cloud.githubusercontent.com/assets/13852287/20627694/abf80288-b2ef-11e6-8683-a41a4cd3ddbb.png">

**Comment by clintongormley** [comment]
@kvesterling If your `Name` field is analyzed with the `standard` analyzer, then it contains the three terms `ethernet`, `10`, `24`. Your regex can only match within a single term.

If you have a `Name.keyword` field, then it contains one term `Ethernet 10/24` and you can run a case-sensitive regex on the whole term:

```
PUT t/t/1
{
  "Name": "Ethernet 10/24" 
}

GET t/_search
{
  "query": {
    "query_string": {
      "query": "Name.keyword:/Ethernet 10\\/24/"
    }
  }
}
```

**Comment by kvesterling** [comment]
How do I go about getting a Name.keyword field?  I've read the information about setting up an analyzer, but I'm missing something, and I cannot figure out what it is.  It seems to create it for other fields, like hostname...

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
