### ISSUE TITLE
Search templates for rank_eval endpoint currently only work when sent through REST end point

### ISSUE THREAD

**Issue by MaineC** [elastic/elasticsearch#21777]
In it's current implementation, templates used in a rank eval request are executed when parsing the REST request like so:

https://github.com/elastic/elasticsearch/blob/feature/rank-eval/modules/rank-eval/src/main/java/org/elasticsearch/index/rankeval/RankEvalSpec.java#L156

However we also allow templates to be set through a Java API call to "setTemplate" on that same spec. This doesn't go through template execution so fails further down the line.

To make this work, I believe we'd have to move template execution further down, probably to TransportRankEvalAction.

With the new Java REST client being refined and improved, I'm wondering if that change is actually worth it: I think, as soon as Java calls also go through REST the above refactoring would be obsolete.

Opening this issue to track further discussion.

**Comment by MaineC** [comment]
@cbuescher @javanna any input from your side welcome.

**Comment by javanna** [comment]
Not sure we can yet define apis based on the fact that we will remove transport client at some point, hopefully in 6.0. Maybe it is worth adapting to make this api work with java api too?

**Comment by MaineC** [comment]
@javanna Makes sense to me.

**Comment by MaineC** [comment]
Closed by #21855
