### ISSUE TITLE
Jre x86 on Win x64

### ISSUE THREAD

**Issue by i2um1** [elastic/elasticsearch#21783]
Good evening, ❄️ ElasticSearch dev team ❄️ !

I have a problem:
Why I can't run elasticsearch.bat on Windows 10 x64 with jre1.8.0_111 x86? After some research I found out that bin folder doens't have server folder and elasticsearch.in.bat requires it. Could you handle this situation?

Thanks in advance

**Comment by clintongormley** [comment]
Hi @ 

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by dadoonet** [comment]
Can we reopen Clint? I think we have a documentation issue here, no?
Not really obvious in support matrix for instance.

https://discuss.elastic.co/t/es-5-0-1-doesnt-work-with-jre-x86-on-win-x64/67128/7

**Comment by clintongormley** [comment]
Thanks @dadoonet  - i agree

**Comment by jasontedor** [comment]
This is not correct, you can start it after you remove or comment out the line `-server` in the `jvm.options` file. Here's a log line showing a running Elasticsearch instance on the x86 client VM:

```
[2016-12-01T09:57:44,609][INFO ][o.e.n.Node               ] [PsFqIqd] version[5.0.0], pid[3832], build[253032b/2016-10-26T04:37:51.531Z], OS[Windows 10/10.0/x86], JVM[Oracle Corporation/Java HotSpot(TM) Client VM/1.8.0_102/25.102-b14] 
```

**Comment by jasontedor** [comment]
I opened #21920.
