### ISSUE TITLE
Unreachable objects which are in old generation.

### ISSUE THREAD

**Issue by hsshee** [elastic/elasticsearch#21780]
**Elasticsearch version**: 2.3.4

**Plugins installed**: [kopf, hq]

**JVM version**: 1.8

**OS version**: Cent OS 6.8

**Description of the problem including expected versus actual behavior**:

Whenever "minor gc" occurs, the use of the old generation area increases.
For reference, attatch my jvm options.
```shell
-Xms8g -Xmx8g -XX:+UseParNewGC -XX:+UseConcMarkSweepGC \
-XX:NewRatio=2 -XX:MaxTenuringThreshold=10 -XX:CMSInitiatingOccupancyFraction=75 \
-XX:+UseCMSInitiatingOccupancyOnly -XX:+PrintGCDetails -XX:+PrintGCTimeStamps \
-XX:+PrintGCDateStamps -XX:+PrintClassHistogram -XX:+PrintTenuringDistribution \
-XX:+PrintGCApplicationStoppedTime -XX:+DisableExplicitGC
```

Because of the short-term use, I expected no object to move to the old generation area but it worked contrary to expectation.
Which objects are alive in the old generation area?
In order to check the above situation, I analyzed heapdump but almost all objects in the old generation area were unreachable objects.

Is this your intended situation?
Are there objects that is stored in old generation for the performance of elasticsearch?

I look forward to your help.

Thanks in advance!

**Comment by clintongormley** [comment]
It's quite normal for live objects to be moved from young to old generation during a young gen GC.  Later an old gen GC will clean up the unreachable objects.

What problem are you seeing?

**Comment by hsshee** [comment]
Thanks for your reply.

I expected no object to move to the old generation area. 
So I would like to know what / why unreachable objects is living in old generation.
This information will be very helpful to me.

**Comment by jasontedor** [comment]
These are general JVM questions not specific to Elasticsearch.

**Comment by hsshee** [comment]
Because I thought it was the object related to elasticsearch, I contacted you here.Thank you for your answer.

**Comment by jasontedor** [comment]
We reserve GitHub for bug reports and feature requests, and provide a [forum](https://discuss.elastic.co) for general questions about Elasticsearch. Your questions are more general about garbage collection in the JVM, for which there are more suitable resources.

**Comment by hsshee** [comment]
Thank you for your detailed explanation.
