### ISSUE TITLE
Unable to start Elasticsearch

### ISSUE THREAD

**Issue by voyalab** [elastic/elasticsearch#21796]
**Elasticsearch version**: 5.0

**JVM version**: openjdk version "1.8.0_111"

**OS version**: Amazon Linux AMI release 2014.03

I am using AWS m3.large instance. I have two elasticsearch nodes. For my data node(node-2) , When I started elasticsearch service with **sudo service elasticsearch start**
```

[2016-11-25T09:31:56,884][INFO ][o.e.b.BootstrapCheck     ] [node-2] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2016-11-25T09:31:56,886][ERROR][o.e.b.Bootstrap          ] [node-2] node validation exception
bootstrap checks failed
max number of threads [1024] for user [elasticsearch] is too low, increase to at least [2048]
```

Then I edited file /usr/lib/systemd/system/elasticsearch.service and added line **LimitNPROC=2048.**

When I restarted service. I checked status: `sudo service elasticsearch status
`
It returned ,
`
elasticsearch dead but subsys locked`
In Log

```
[2016-11-25T09:50:32,138][INFO ][o.e.b.BootstrapCheck     ] [node-2] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2016-11-25T09:50:32,140][ERROR][o.e.b.Bootstrap          ] [node-2] node validation exception
bootstrap checks failed
max number of threads [1024] for user [elasticsearch] is too low, increase to at least [2048]
```

Am I missing something ?

**Comment by clintongormley** [comment]
As far as I know, [Amazon Linux AMI](https://www.reddit.com/r/aws/comments/52kzhp/have_the_amazon_linux_amis_switched_to_systemd/)  isn't using systemd, so you should be setting the nproc limit with `ulimit` or by configuring `limits.conf`

**Comment by voyalab** [comment]
**ulimit -u command returns:**
```
[root@ip-address-subsys]# ulimit -u
2048
```
**/etc/security/limits.conf**
```
<domain>      <type>  <item>         <value>
#

#*               soft    core            0
#*               hard    rss             10000
#@student        hard    nproc           20
#@faculty        soft    nproc           20
#@faculty        hard    nproc           50
#ftp             hard    nproc           0
#@student        -       maxlogins       4
elasticsearch    hard    nproc           2048
```

**Comment by voyalab** [comment]
I updated my Amazon Linux instance from **2014.03 to 2016.09**. It worked for me.
