### ISSUE TITLE
X-pack 5.0.1 ,for default username and password

### ISSUE THREAD

**Issue by a5601564** [elastic/elasticsearch#21792]
**Elasticsearch version 5.0.1:

**Plugins installed  X-pack 5.0.1:  

**JVM version  1.8.0.65:

**OS version  centos 7.2:

**Description of the problem including expected versus actual behavior 

x-pack安装之后有一个超级用户elastic ，其默认的密码是changeme

it doesn't work；
:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by a5601564** [comment]
and when i run Elasticsearch on X-pack 5.0.1 
some
exceptions has accured 
[lmwGdLM] exception when exporting documents
org.elasticsearch.xpack.monitoring.exporter.ExportException: exporters are either not ready or faulty

**Comment by a5601564** [comment]
大家行行好，帮帮我

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
