### ISSUE TITLE
update_by_query within bulk API

### ISSUE THREAD

**Issue by ericofusco** [elastic/elasticsearch#21806]
I'm wondering if it's possible to add update_by_query within the bulk API just like we have for index, update, delete. Right now I have a Queue to send updates to ElasticSearch via bulk API and sometimes I need to send update_by_query requests too. Unfortunately it's not possible with update_by_query and one bulk request needs to be sent first, a single request with update_by_query then another bulk request.

If I have several update_by_query requests inside the Queue it's necessary to send several single requests for them and bulk requests in between.

**Comment by dadoonet** [comment]
No update by query is doing bulk operations behind the scene and there is no really gain IMO trying to do multiple update by query within a "bulk" request.

On the other end, we already support multisearch, multiget so may be we can support a multiupdate query (which is not bulk but serves the same use case you explained).

Marking this as discuss so the team can talk about it.

**Comment by clintongormley** [comment]
I don't see the point in adding a multi-update-by-query.  First, update by query is already a complicated API and I wouldn't want to complicate it further.  Second, you can just send multiple update-by-query requests in parallel, unless you want them to be applied sequentially, and a multi-update-by-query operation wouldn't guarantee that either.

**Comment by dadoonet** [comment]
> Second, you can just send multiple update-by-query requests in parallel

Isn't the same thing we can say for multiget and multisearch?

**Comment by gongzhxu** [comment]
I have the same requirements. If update_ by_query is not in the bulk of create, update and delete. There is a problem of data consistency

**Comment by spencerdcarlson** [comment]
> Second, you can just send multiple update-by-query requests in parallel

My thought is that the main benefit adding `_update_by_query` to the `_bulk` api would be to avoid the overhead of creating a network connection, serialization , etc. I don't think sending n request in parallel is as efficient as sending 1 request with n messages in the body.
