### ISSUE TITLE
Joyent SmartOS LX branded zone, java8, elastic search 5.0.1 does not launch.

### ISSUE THREAD

**Issue by TyrfingMjolnir** [elastic/elasticsearch#21800]
**Elasticsearch version**: 5.0.1

**Plugins installed**: []
None yet, this is initial install

**JVM version**:
```
$ dpkg -l | grep java
ii  java-common                    0.52                         all          Base of all Java packages
ii  oracle-java8-installer         8u111+8u111arm-1~webupd8~0   all          Oracle Java(TM) Development Kit (JDK) 8
ii  oracle-java8-set-default       8u111+8u111arm-1~webupd8~0   all          Set Oracle JDK 8 as default Java
```
**OS version**:
Joyent SmartOS LX zone
```
uname -a
Linux 722adaae-b1ec-cfcf-c349-dd1bcc6ac5c0 3.16.0 BrandZ virtual linux x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:
Elastic search does not launch: http://termbin.com/jk85

**Steps to reproduce**:
 1. Install Joyent SmartOS
 2. Create LX branded zone of 201610
```
$ cat lxDeb_elk01.json
{
  "alias": "lxDeb_elk01",
  "brand": "lx",
  "kernel_version": "3.16.0",
  "max_physical_memory": 1024,
  "quota": 20,
  "image_uuid": "d9798e62-8cba-11e6-8f4f-e79bce537258",
  "resolvers": [ "10.0.0.2", "4.2.2.6", "8.8.4.4"],
  "nics": [
    {
      "nic_tag": "admin",
      "ip":      "10.0.0.10",
      "netmask": "255.255.255.0",
      "gateway": "10.0.0.1",
      "primary": true
    }
  ]
}
```
 3. Do apt-get install java8 from oracle repo
 4. Do apt-get install elasticsearch from elastic search debian repo
 5. Launch as pr: systemctl start elasticsearch.service

**Provide logs (if relevant)**: http://termbin.com/jk85

**Describe the feature**:
launch elastic search: systemctl start elasticsearch.service

**Comment by jasontedor** [comment]
This:

```
siginfo: si_signo: 7 (SIGBUS), si_code: 3 (BUS_OBJERR), si_errno: 12, si_addr: 0x00000000be783000
```

is usually indicative of a hardware issue. Yet, I notice:

```
  "max_physical_memory": 1024,
```

This is likely a problem, maybe the problem and just manifesting is a disastrous form. Try editing the [heap size](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/heap-size.html) via `jvm.options` and replace `-Xms2048m` and `-Xmx2048m` with `-Xms512m` and `-Xmx512m`, respectively. Alternatively, if you want to run with the default heap size of 2g, you'll want to increase the amount of RAM available to `4096`.

**Comment by jasontedor** [comment]
No feedback, closing.
