### ISSUE TITLE
/_bulk write with `consistency` param throws an error

### ISSUE THREAD

**Issue by quex46** [elastic/elasticsearch#21804]
es v5.0.1 (using official docker image)

request:
```
POST http://127.0.0.1:9200/_bulk?consistency=one

{ "index" : { "_index" : "test1", "_type" : "type1" } }
{ "field1" : "value1" }
```
throws 400 bad request:
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "request [/_bulk] contains unrecognized parameter: [consistency]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "request [/_bulk] contains unrecognized parameter: [consistency]"
  },
  "status": 400
}
```

according to the v5.0 docs [here](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/docs-bulk.html#bulk-versioning) it has not been renamed.

**Comment by jasontedor** [comment]
The parameter is [`wait_for_active_shards`](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/docs-bulk.html#bulk-wait-for-active-shards) now.

**Comment by jasontedor** [comment]
I think it's worth noting here that this really shows the value of changes like #20722 and #21417. Old versions of Elasticsearch would silently accept unrecognized parameters, leading the user to think that they did something (when they were not, and can even be dangerously against the user's intentions).
