### ISSUE TITLE
Able to create separate folders in Kibana for visualizations/Dashboards

### ISSUE THREAD

**Issue by udaykirankona** [elastic/elasticsearch#21816]
Hi Guys,

Is there anyway to create separate folders for Visualizations and Dashboards in Kibana. If this feature is not available adding this near future will be very helpful.

Thanks,
Uday.K

**Comment by johtani** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
