### ISSUE TITLE
Document the impact of snapshot repository upgrade

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#21838]
Version: 5.0

Per our discussion with @abeyad , a 5.x cluster can read a repository created by 2.x, but once the repository is read and updated by the 5.x cluster, it will now use a new format, so if the 2.x cluster continues to write to the repository afterwards, the 5.x cluster will not be able to see those new snapshots.  

It will be helpful to document this in the snapshot/restore section of our guide (and perhaps also in breaking changes).

**Comment by maemichi-monosense** [comment]
@ppf2 Thank you for noting this problem. I've just been troubled with the same issue.
I tried to share a S3 repository among v2.3.2 & v5.1.1 hosts, then I got confused that those snapshots taken by v2.x are invisible from v5.x hosts once I took a snapshot by a v5.x host. 
(I use AWS ElasticSearch service)

I agree to add a note about this issue.

**Comment by ywelsch** [comment]
Fixed by b57cb83567e2fe69937a575a583a4833f75cf13a
