### ISSUE TITLE
NullPointerException ES 1.7

### ISSUE THREAD

**Issue by kalyc** [elastic/elasticsearch#21839]
**Elasticsearch version**: 1.7

Hi, 

I keep getting this error randomly whenever I execute a request to my local ES to perform a custom aggregation - 
`{
"error" : "NullPointerException[null]",
"status" : 500
}`
The request is successful at times and at times it returns the above error message. 
I have not been able to view the stack trace for the same. Could someone please provide an insight on how should I go debugging this? Or any ideas from where could this error be occurring would be helpful. I feel that this has got to do with some ES settings.

Thanks!

**Comment by clintongormley** [comment]
@kalyc you haven't provided any information to help us answer your question, and 1.7 is really old.  I suggest either upgrading or asking for help in the forums.

**Comment by kalyc** [comment]
@clintongormley - could you please suggest some forums where I can post this question? I have added it to discuss.elastic.co
