### ISSUE TITLE
Discovery-ec2 plugin compatible with ES 5.1 is missing!

### ISSUE THREAD

**Issue by walruz** [elastic/elasticsearch#21863]
**Elasticsearch version**: 5.1.0

**Plugins installed**: [discovery-ec2]

**JVM version**: 1.8.0_111

**OS version**: Amazon Linux

**Description of the problem including expected versus actual behavior**: After upgrading to ES 5.1.0, when downloading the discovery-ec2 plugin for the current version is missing

**Steps to reproduce**:
 1. Upgrade to ES 5.1.0
 2. Run /usr/share/elasticsearch/bin/elasticsearch-plugin install discovery-ec2
 3. Notice that the application fails to find the file
 4. Try to manually download the plugin from https://artifacts.elastic.co/downloads/elasticsearch-plugins/discovery-ec2/discovery-ec2-5.1.0.zip
 5. Notice again that the file doesn't exist

**Comment by jasontedor** [comment]
At this time, there is not an official release of Elasticsearch 5.1.0. The latest version in the Elasticsearch 5.x series is 5.0.2.

**Comment by walruz** [comment]
Sorry to bother you, @jasontedor, but apparently it was pushed to the Yum repositories, at least when our server did a `yum upgrade` today, you can see that ES 5.1.0 is the current version provided by the Yum repo at https://artifacts.elastic.co/packages/5.x/yum

**Comment by jasontedor** [comment]
@walruz I have verified there is an issue, thanks for reporting. We will fix this immediately.

**Comment by clintongormley** [comment]
@walruz something went wrong in our release process and uploaded 5.1.0 rpm and deb instead of 5.0.2.  Please delete the version you've downloaded as it is not final :(  We'll upload the 5.0.2 packages shortly.  Sorry for the mistake and thanks for reporting
