### ISSUE TITLE
Switch custom component serialization in ClusterState from PROTO to NamedWriteable

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#21868]
We currently have two different ways to serialize/deserialize objects with variable types. The older method, which is used in cluster state serialization is using [registered `PROTO` objects](https://github.com/elastic/elasticsearch/blob/a9a2753f0b07ee644e1babfd9de4f00df17e7b2a/core/src/main/java/org/elasticsearch/cluster/ClusterState.java#L105) to select the proper de-serialization reader. In all other places we switched to using `NamedWriteable`s for the same purpose. 

I would like to convert custom objects in `ClusterState`, `MetaData` and `IndexMetaData` to `NamedWritable`s and see if I can completely remove `PROTO`-based serialization to make cluster state serialization/deserialization more in line with the rest of the system. It's a significant change internally and will affect plugins that are registering custom metadata objects, but it looks like wire-protocol would remain the same and therefore it should be possible to make this change compatible with rolling restart.

**Comment by nik9000** [comment]
I didn't take this on when I was converting stuff to NamedWriteable a while back just because I had enough stuff to do converting what I did convert. I think this makes sense if you can keep the wire protocol the same.

**Comment by s1monw** [comment]
lets do this it's a good cleanup
