### ISSUE TITLE
allow overriding index-templates-sourced-stuff when "manually" creating an index

### ISSUE THREAD

**Issue by celesteking** [elastic/elasticsearch#21870]
You've got a template that covers hell lot of index names. Then suddenly you want to create an index (with slightly different settings) that falls under those names. You specify your settings in body request, but they're disregarded because template took priority. This should be corrected or explicitly stated in docs with big red text.

**Comment by jpountz** [comment]
> You specify your settings in body request, but they're disregarded because template took priority.

Information that is specified at index creation time is supposed to always have precedence over information that is inherited from templates. Can you give a concrete example of what you did? This might be a bug.

**Comment by colings86** [comment]
No further feedback
