### ISSUE TITLE
Renaming an index / hotswapping / aliasing

### ISSUE THREAD

**Issue by celesteking** [elastic/elasticsearch#21871]
There should be a way to safely rename / revoke / reindex / manipulate an index. 

Currently, I have to do the following:

1. Create NEW index
1. Copy  (aka reindex) data from OLD to NEW
1. Delete OLD index
1. Make an alias/link from OLD index name to NEW index
1. Do my stuff
1. Delete OLD index alias
1. Create OLD index
1. Copy (aka reindex) data from NEW to OLD index.
1. Delete OLD index.

3-4 transition is a race cond. If app is heavily writing to index, you're out of luck. Your index will be constantly created, you won't be able to even make an alias.
6-7 is a potential race condition.

To work around the problem, we need aliases to work with existing indexes. 
Also, an index rename functionality should be implemented, so that entire 4-7 would not be needed.

**Comment by celesteking** [comment]
+ Proper field mapping update should be implemented.

One of the advantages of noSQL is schema-less. I don't see how this is schemaless looking at 1-9 and all the manipulations I have to do if 1 tiny field wasn't "analyzerized" properly when it entered the database.

In SQL, I'd do "ALTER TABLE MODIFY COLUMN" and I'm done. This thing should really be better in this regard, or at least close.

**Comment by jasontedor** [comment]
Duplicates #20064, duplicates #17426
