### ISSUE TITLE
REST client to support node selectors like other language clients

### ISSUE THREAD

**Issue by mikeh-elastic** [elastic/elasticsearch#21888]
**Describe the feature**:
Add option to use custom node selection logic for sending requests only to certain nodes like in the javascript, perl, etc clients.  For example, allow sniffing of the cluster but send requests only to client nodes within the cluster.

**Comment by javanna** [comment]
Thanks for opening this @mikeh-elastic . It is not the first time that I hear this ask for the Java REST client, and I think it makes sense to add as the other language clients support this too.

As for the transport client part, I don't think we are going to add features to it, as we want to focus more and more on the Java REST client.

**Comment by gmoskovicz** [comment]
Adding some more context from the recent linked issue:

Right now if you want to allow an application to use Client Nodes only, you need to define the nodes in the connection settings for the Client. If you add sniffing, you will be able to sniff any node and you could use the sniffHosts option to sniff just client nodes from an external source.

If you want to have a dynamic pool of nodes (client only nodes) that when you add a new client node to a cluster, that node is added to the connection pool, but when you add master or data nodes, those aren't used, one of the ways that people would do that is by using an external Load Balancer.

I think that it will be great for the Java REST client to be able to have a way to sniff client-only nodes.

The current Transport Client doesn't do that, and actually just retrieves a list of data nodes. The reason the transport client excludes non-data nodes is to avoid sending search traffic to master only nodes (from the docs).
