### ISSUE TITLE
Different performance in SATA and SSD with simple client and default config

### ISSUE THREAD

**Issue by wu-sheng** [elastic/elasticsearch#21880]
**Elasticsearch version**: 5.0.2

**Plugins installed**: [
[2016-11-30T15:42:29,353][INFO ][o.e.p.PluginsService     ] [wOXQQyL] loaded module [aggs-matrix-stats]
[2016-11-30T15:42:29,353][INFO ][o.e.p.PluginsService     ] [wOXQQyL] loaded module [ingest-common]
[2016-11-30T15:42:29,354][INFO ][o.e.p.PluginsService     ] [wOXQQyL] loaded module [lang-expression]
[2016-11-30T15:42:29,354][INFO ][o.e.p.PluginsService     ] [wOXQQyL] loaded module [lang-groovy]
[2016-11-30T15:42:29,354][INFO ][o.e.p.PluginsService     ] [wOXQQyL] loaded module [lang-mustache]
[2016-11-30T15:42:29,354][INFO ][o.e.p.PluginsService     ] [wOXQQyL] loaded module [lang-painless]
[2016-11-30T15:42:29,354][INFO ][o.e.p.PluginsService     ] [wOXQQyL] loaded module [percolator]
[2016-11-30T15:42:29,354][INFO ][o.e.p.PluginsService     ] [wOXQQyL] loaded module [reindex]
[2016-11-30T15:42:29,354][INFO ][o.e.p.PluginsService     ] [wOXQQyL] loaded module [transport-netty3]
[2016-11-30T15:42:29,354][INFO ][o.e.p.PluginsService     ] [wOXQQyL] loaded module [transport-netty4]
]

**JVM version**:
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

**OS version**:
CentOS and MacOS

**Description of the problem including expected versus actual behavior**:
I use a very simple code to batch insert index.
```java
public static void main(String[] args) {
        try {
            TransportClient client = new PreBuiltTransportClient(Settings.EMPTY).addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("test_es"), 9300));
            IndexOperator operator = new IndexOperator(client);

            for (int i = 0; i < 1_000_000_000; i++) {
                IndexMetaCollection collection = new IndexMetaCollection();
                for (int j = 0; j < 100; j++) {
                    RequestSpan requestSpan =
                            RequestSpan.newBuilder().setSpanType(1).setAddress(NetUtils.getLocalAddress().toString()).setApplicationId("1").setCallType("1").setLevelId(0)
                                    .setProcessNo(19287).setStartDate(System.currentTimeMillis()).setTraceId(
                                    TraceId.newBuilder().addSegments(201611).addSegments(j).addSegments(8504828).addSegments(2277).addSegments(53).addSegments(3).build())
                                    .setUserId("1").setViewPointId("http://localhost:8080/wwww/test/helloWorld").setRouteKey(i).build();
                    IndexMetaInfo info = new IndexMetaInfo(new RequestSpanData(requestSpan), new DataFileNameDesc(), i, j);
                    collection.add(info);
                }

                operator.batchUpdate(collection);

                if (i % 100 == 0) {
                    System.out.println(" num=" + i + " ");
                }
            }
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }
    }

    public int batchUpdate(IndexMetaCollection metaInfos) {
        BulkRequestBuilder requestBuilder = client.prepareBulk();
        for (IndexMetaInfo indexMetaInfo : metaInfos) {
            try {
                requestBuilder.add(client.prepareIndex(INDEX_NAME, INDEX_TYPE).setSource(buildSource(indexMetaInfo)));
            } catch (Exception e) {
                logger.error("Failed to update index.", e);
                HealthCollector.getCurrentHeathReading("IndexOperator").updateData(HeathReading.ERROR, "Failed to " + "update index.");
            }
        }

        BulkResponse bulkRequest = requestBuilder.get();
        if (bulkRequest.hasFailures()) {
            HealthCollector.getCurrentHeathReading("IndexOperator")
                    .updateData(HeathReading.ERROR, "Failed to " + "update index. Error message : " + bulkRequest.buildFailureMessage());
        }

        return metaInfos.size();
    }
```

In Mac, SSD, it has high performance.
In a test PC(CentOS, SATA), it has much lower performance.  Only have 1/100 performance. It's strange.

**Steps to reproduce**:
 1. run the code just enough.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by wu-sheng** [comment]
Further, what is good config in a single node elasticsearch, with heavy-write jobs.

**Comment by ywelsch** [comment]
Use concurrent bulk requests with client-side threads or separate asynchronous requests. ES does an fsync at the end of processing a bulk request and only returns after the fsync completes. Also note that GitHub is reserved for bug reports and feature requests. The best place to ask a general question is at the Elastic Discourse forums at https://discuss.elastic.co.

**Comment by wu-sheng** [comment]
I will ask other questions on Elastic Discourse forums. 
Just for this question, can you tell me which is the better way to do batch insert, and have high performance?
