### ISSUE TITLE
Visualisation unable to print certain document content

### ISSUE THREAD

**Issue by error756** [elastic/elasticsearch#21883]
**Elasticsearch version**: 2.4.0

**Plugins installed**: [Kibana 4.5.4, Sense, Marvel, License]

**JVM version**: openjdk-7-jdk:amd64  -  7u111-2.6.7-0ubuntu0.14.04.3

**OS version**: Ubuntu 14.04.5

**Description of the problem including expected versus actual behavior**:
(Can also be reproduced in a clean docker Elasticsearch 5.0.0 build 14438)
Certain crafted strings cannot be properly indexed. While they do show up within the "discover" section, they are missing in the visualisation.

**Steps to reproduce**:
 1. PUT a logstash similar template through SENSE/Dev-Tools
     http://pastebin.com/qJrgTVxU
 2. Insert content into index. Run the following example Perl script:
     http://pastebin.com/j52DR4JL
 3. Create a new data table visualisation on field "error_message.raw".
     You should only see one of the errors while the Discover section shows both documents.
     It seems to break somewhere around "Thread ID [ ***(***) ]"

**Provide logs (if relevant)**: -

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by error756** [comment]
Hi Clinton

I think the issue was exactly in the right location as it is not a question
of how to use visualisations.
If the difference of a string causes the filterless visualisation to show
one while not the other, this does look very much like a bug in the product.
Could you please re-open the issue?

Thanks and kind regards,
Marcel

**Comment by clintongormley** [comment]
> If the difference of a string causes the filterless visualisation to show one while not the other, this does look very much like a bug in the product.

Or a misunderstanding about how the product works.  For instance, your `error_message.raw` field is mapped to `"ignore_above": 256`.  Have you checked the length of the missing error message?

This is not a bug.

**Comment by error756** [comment]
Interesting... I tried increasing the template length before which didn't
change anything. Tried now again with the same result until I deleted the
index with the sample documents. Now that the index is re-created, the
ignore_length seems to work. Seems like the template is only applied when
the index is created then... Good catch... Thanks, Marcel
