### ISSUE TITLE
Add support for us-east-2 AWS region

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#21881]
AWS supports `us-east-2` region. We need to add it to our s3 and ec2 plugins.

* EC2 region: http://docs.aws.amazon.com/general/latest/gr/rande.html#ec2_region
* S3 region: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

Note that in the meantime people can define `cloud.aws.ec2.endpoint` and `cloud.aws.s3.endpoint` to `ec2.us-east-2.amazonaws.com` and `s3.us-east-2.amazonaws.com`.

**Comment by sanvir10** [comment]
Sorry, this is working now,  was a mistake in the config with the group-security name, but this is working whit this config file.

bootstrap.mlockall: true
cloud.aws.access_key: XXX
cloud.aws.secret_key: YYY
cluster.name: myCluster
node.name: elastic1 #and elastic2, two nodes in the cluster
discovery.type: "ec2"
discovery.zen.ping.multicast.enabled: false
discovery.ec2.groups: "couch-elastic"  //
discovery.ec2.host_type: "private_ip"
discovery.ec2.ping_timeout: "30s"
discovery.ec2.tag.cluster: "cluster-elastic"
cloud.aws.ec2.endpoint: "ec2.us-east-2.amazonaws.com"
discovery.ec2.availability_zones: "us-east-2a"
cloud.aws.region: "us-east"

Thanks so much

**Comment by dadoonet** [comment]
Closed by #21961
