### ISSUE TITLE
Improve the System Configuration docs in regards to SystemD and best practices

### ISSUE THREAD

**Issue by abraxxa** [elastic/elasticsearch#21891]
**Elasticsearch version**: 5.0.2

**Plugins installed**: x-pack

**JVM version**: OpenJDK 1.8.0_111/25.111-b14

**OS version**: Debian 8 64bit

**Description of the problem including expected versus actual behavior**:
When upgrading a cluster it's very time consuming to edit the deb package provided config files for every node as apt upgrade asks when it detects a diff.
This isn't an issue when the files in /etc/elasticsearch are untouched and the configuration is instead done via a systemd override file as described in [Systemd configuration](https://www.elastic.co/guide/en/elasticsearch/reference/current/setting-system-settings.html#systemd).
My issue was that the information is split up between this doc and e.g. [Set JVM heap size via jvm.options](https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html).
Each section shows how to set the values in the package provided files and something how do to it differently for SysV and/or SystemD, sometimes even differentation between RPM and DEB based distros making it hard to find the right one.
This is related to #16781.

**Describe the feature**:
Please restructure the docs to show the best-practice way of doing it first and not to edit package provided files.
Having a clear distinction between SysV and SystemD would also help.
If you don't want to change the basic structure from config options to SysV/SystemD please at least add a section for those two to every page in the [Important System Configuration](https://www.elastic.co/guide/en/elasticsearch/reference/current/system-config.html).

Providing a sample systemd override file which sets the important config options would be a great help too, mine currently looks like that:

/etc/systemd/system/elasticsearch.service.d/elasticsearch.conf:
```
[Service]
LimitMEMLOCK=infinity
Environment=DATA_DIR=/data/elasticsearch
Environment="ES_JAVA_OPTS=-Xms16g -Xmx16g"
```

Thanks!

**Comment by jasontedor** [comment]
> When upgrading a cluster it's very time consuming to edit the deb package provided config files for every node as apt upgrade asks when it detects a diff.

We do not recommend editing these, and you should be using deployment scripts and configuration management tools.

The docs say:

> To override these, add a file called `/etc/systemd/system/elasticsearch.service.d/elasticsearch.conf` and specify any changes in that file

> `Environment=DATA_DIR=/data/elasticsearch`

I encourage you to to put this in `elasticsearch.yml`.

> `Environment="ES_JAVA_OPTS=-Xms16g -Xmx16g"`

I encourage you to put this in `jvm.options`.

**Comment by abraxxa** [comment]
Why do you encourage to put this in the package provided files which lead to apt/dpkg asking for each file if it should overwrite it with the file from the new package?

**Comment by jasontedor** [comment]
Because it's the preferred location for these configuration values and you can tell dpkg/apt-get to not override them (`dpkg --force-confold -i <path>` or `apt-get -o Dpkg::Options::="--force-confold" upgrade elasticsearch`).

**Comment by abraxxa** [comment]
Sad that you don't want to improve the docs when a customer tells you that they are suboptimal.
The stackoverflow and servervault questions tell the same story.

**Comment by jasontedor** [comment]
I've explained that we encourage configuration for Elasticsearch and JVM options in the respective configuration files rather than the systemd service file and how to deal with the issues that you're seeing on upgrade; this appears to be incongruous with your preferences. I'm more than happy to continue to iterate on this conversation, but I'll need a concrete response to my previous rebuttal or a concrete suggestion on what you think could be done to make the docs more optimal.

**Comment by damm** [comment]
The unfortunate part is the Chef Cookbook that you ship hardcodes this and does not hint at such configuration.  I will update the referenced issue to mention that.
