### ISSUE TITLE
Have the JSON processor add fields to the root of the document

### ISSUE THREAD

**Issue by msimos** [elastic/elasticsearch#21898]
**Elasticsearch version**:

5.0.0

**Plugins installed**: []

None

**JVM version**:

All

**OS version**:

Any

**Describe the feature**:

The JSON processor has an optional field called "target_field". If you don't specify target_field then target_field becomes what you specified as "field". There isn't anyway to add the fields to the root of a document. Logstash & Filebeat can do this so this would be the obvious solution and maybe preferable. But it would be useful to have this functionality in the Ingest node as well.

**Comment by clintongormley** [comment]
@talevy what do you think?

**Comment by talevy** [comment]
maybe add a backwards compatible `add_to_root` flag.

If this is set to true, then do as suggested. This will ignore any `target_field` that is provided/defaulted.
