### ISSUE TITLE
Add ingest support for Java API upsert request

### ISSUE THREAD

**Issue by mrvincenzo** [elastic/elasticsearch#21903]
Today `IndexRequest` and the `UpdateByQueryRequest` have`setPipeline` method that can be used to set the pipeline. 
On the opposite, `UpdateRequest` doesn't have the `setPipeline` method and lacks the ingest support which makes it impossible to use for upserts.

It would be nice if `UpdateRequest`had ingest support.

**Comment by dadoonet** [comment]
I'm +1 for this. Wondering if it can also make sense for the update part.

Let say I want to update the PDF document I previously indexed and that I want to provide only the BASE64 content.
Using a pipeline would be useful I believe.

**Comment by dadoonet** [comment]
Actually we already support it. I missed that.

In Java, when you want to do upsert, you pass an IndexRequest to `setUpsert` method.
This IndexRequest can have a pipeline defined.

Does this work for you?

**Comment by mrvincenzo** [comment]
I am not using the `IndexRequest` but the index source document. I guess I can switch to using `IndexRequest`.
