### ISSUE TITLE
5.0.1: Sorting on keyword fields doesn't work

### ISSUE THREAD

**Issue by tangopium** [elastic/elasticsearch#21900]
**Elasticsearch version**: 5.0.1
**Plugins installed**: none
**JVM version**: 1.8.0
**OS version**: Ubuntu 16.04

A have a text field in my mapping, on which I want to sort the results on in alphabetical order. In ES 2.x I had defined it like described [here](https://www.elastic.co/guide/en/elasticsearch/guide/current/multi-fields.html). In ES 5.x this doesn't work anymore. So I tried to define a separate field (not multi-field) called `name_raw` of type _keyword_ and during search `sort: name_raw`. But the returned result is exactly the same as without the `sort: name_raw` (not sorted on the `name_raw` field in any way)

**Comment by MaineC** [comment]
I just tried reproducing your issue, in my case alphabetical ordering works. Probably I'm missing some specifics of your setup. Would you mind posting a brief curl reproduction to illustrate the issue?


    PUT test/foo/1
    {"user":"john"}
    PUT test/foo/2
    {"user":"johndo"}

    GET test/foo/_mapping

    {
       "test": {
          "mappings": {
             "foo": {
                "properties": {
                   "user": {
                      "type": "text",
                      "fields": {
                         "keyword": {
                            "type": "keyword",
                            "ignore_above": 256
                         }
                      }
                   }
                }
             }
          }
       }
    }

    GET _search
    {
        "query": {"match_all": {}},
        "sort": [
           {
              "user.keyword": {
                 "order": "asc"
              }
           }
        ]
    }

**Comment by clintongormley** [comment]
No further feedback. Closing

**Comment by jughead** [comment]
Got the same issue on Elasticsearch 6.0.0
```
PUT test
{
  "mappings": {
    "foo": {
      "properties": {
        "user": {
          "type": "text"
        }
      }
    }
  }
}

PUT test/foo/1
{"user":"john"}
PUT test/foo/2
{"user":"johndo"}

PUT test/_mapping/foo
{
  "properties": {
    "user": {
      "type": "text",
      "fields": {
        "raw": {
          "type": "keyword"
        }
      }
    }
  }
}

GET test/_search
{
    "query": {"match_all": {}},
    "sort": [
       {
          "user.raw": "asc"
       }
    ]
}
```
=>
```
{
  "took": 9,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": null,
    "hits": [
      {
        "_index": "test",
        "_type": "foo",
        "_id": "2",
        "_score": null,
        "_source": {
          "user": "johndo"
        },
        "sort": [
          null
        ]
      },
      {
        "_index": "test",
        "_type": "foo",
        "_id": "1",
        "_score": null,
        "_source": {
          "user": "john"
        },
        "sort": [
          null
        ]
      }
    ]
  }
}
```

**Comment by clintongormley** [comment]
@jughead you can't add the `.raw` field after the documents are indexed and expect them to already have values.  only documents indexed after you added that field will have values

**Comment by jughead** [comment]
@clintongormley ok. So only reindex helps?

**Comment by clintongormley** [comment]
correct

**Comment by jughead** [comment]
@clintongormley thank you
