### ISSUE TITLE
Cannot start Elasticsearch as a Windows service

### ISSUE THREAD

**Issue by ericferon** [elastic/elasticsearch#21917]
**Elasticsearch version**: 5.0.2

**Plugins installed**: []

**JVM version**: 1.8.0_112

**OS version**: Windows

**Description of the problem including expected versus actual behavior**:
The service has been installed on Windows successfully. But when starting it, there is a message from Windows that it cannot be started

**Steps to reproduce**:
 1. Install Elasticsearch 5.0.2 with JAVA_HOME="C:\Program Files (x86)\Java\jre8"
 2. Run elasticsearch-service.bat install
 3. In Windows services, start the Elasticsearch service

**Provide logs (if relevant)**:
[2016-12-01 17:41:27] [info]  [ 9068] Commons Daemon procrun (1.0.15.0 32-bit) started
[2016-12-01 17:41:28] [info]  [ 9068] Running 'elasticsearch-service-x86' Service...
[2016-12-01 17:41:28] [info]  [13124] Starting service...
[2016-12-01 17:41:28] [error] [13124] Missing service ImageFile
[2016-12-01 17:41:28] [error] [13124] The system cannot find the file specified.
[2016-12-01 17:41:28] [error] [13124] ServiceStart returned 1
[2016-12-01 17:41:28] [error] [13124] The system cannot find the file specified.
[2016-12-01 17:41:28] [info]  [ 9068] Run service finished.
[2016-12-01 17:41:28] [info]  [ 9068] Commons Daemon procrun finished

**Comment by tlrx** [comment]
Can you please specify the OS version?

**Comment by ericferon** [comment]
I’m testing Elasticsearch on my Windows10 PC.
Best regards,
Eric Feron

**Comment by AMarthaller** [comment]
Did you set the thread stack size? I ran into something similar a couple weeks ago and found a couple relevant threads on needing to set -Xss1m in the java options (on Windows).

https://github.com/elastic/elasticsearch/issues/20899
https://github.com/elastic/elasticsearch/issues/18317

**Comment by jasontedor** [comment]
@AMarthaller We fail the service installation (with a message) if the thread stack size is not set.

**Comment by ericferon** [comment]
Yes, I set the –Xss1m in jvm.options.
Best regards,

**Comment by trevorndodds** [comment]
Try adding JAVA_HOME="C:\Program Files (x86)\Java\jre8" as a SYSTEM variable.

**Comment by ericferon** [comment]
It was already added.
Best regards,

**Comment by asolopovas** [comment]
+1 Same other here on Windows 10
The Elasticsearch 5.0.2 (elasticsearch-service-x64) service terminated with the following service-specific error: 
Incorrect function.

**Comment by cherguii** [comment]
thank you

**Comment by cherguii** [comment]
It was already added for me to
Big thanks

**Comment by joseph-kaainoa** [comment]
I had the exact same thing happen, I had to look at the elasticsearch-stderr log which had a problem loading the node.name in my case, I didn't have a space before the value, so it didn't like that.  After I added the space, everything worked as expected.

**Comment by soumendrak** [comment]
For me, it got fixed after adding JAVA_HOME as a system variable.

**Comment by jasontedor** [comment]
I think this is fixed in recent versions of Elasticsearch. Please upgrade and if the issue persists, we can reopen this issue.

**Comment by antonkrugerTA** [comment]
Ensure you have the latest java RTL installed

**Comment by AlpNek** [comment]
@jasontedor 

> I think this is fixed in recent versions of Elasticsearch.

Which version of Elasticsearch was it fixed in? Thanks!

**Comment by akifshaikh73** [comment]
6.4.1 works well. Check your log files - under the logs directory. In my case even though I had the JAVA_HOME defined , it said it wasn't able to find JRE. Turned out it was in the User variables , moved it to System Environment variables and it works fine.

**Comment by taku333** [comment]
Thanks!!
It was the same in Elasticsearch 7.0 (alpha 1)

I moved after describing JAVA_HOME in the system environment variable
Also, in the log, "Failed creating Java% JAVA_HOME% \ jre \ bin \ server \ jvm.dll" was written

**Comment by glucaci** [comment]
I have the same problem with version 6.6.1-oss installed from .zip on Windows Server 2016 Datacenter 10.0.14393 / 56GB RAM

`JAVA_HOME` is set as System Variable
```
elasticsearch-service.bat install

Installing service      :  "elasticsearch-service-x64"
Using JAVA_HOME (64-bit):  "C:\Program Files\Java\jdk-11.0.2"
-XX:+UseConcMarkSweepGC;-XX:CMSInitiatingOccupancyFraction=75;-XX:+UseCMSInitiatingOccupancyOnly;-XX:+AlwaysPreTouch;-server;-Xss1m;-Djava.awt.headless=true;-Dfile.encoding=UTF-8;-Djna.nosys=true;-Djdk.io.permissionsUseCanonicalPath=true;-Dio.netty.noUnsafe=true;-Dio.netty.noKeySetOptimization=true;-Dio.netty.recycler.maxCapacityPerThread=0;-Dlog4j.shutdownHookEnabled=false;-Dlog4j2.disable.jmx=true;-Dlog4j.skipJansi=true;-XX:+HeapDumpOnOutOfMemoryError;-Xmx14336m;-Xms14336m
The service 'elasticsearch-service-x64' has been installed.
```
Logs after `elasticsearch-service.bat start`
```
[2019-02-22 21:10:10] [info]  [21880] Commons Daemon procrun (1.1.0.0 64-bit) started
[2019-02-22 21:10:10] [info]  [21880] Running 'elasticsearch-service-x64' Service...
[2019-02-22 21:10:10] [info]  [19200] Starting service...
[2019-02-22 21:10:10] [error] [13880] CreateJavaVM Failed
[2019-02-22 21:10:10] [error] [13880] The system cannot find the file specified.
[2019-02-22 21:10:10] [error] [19200] Failed to start Java
[2019-02-22 21:10:10] [error] [19200] ServiceStart returned 4
[2019-02-22 21:10:10] [info]  [21880] Run service finished.
[2019-02-22 21:10:10] [info]  [21880] Commons Daemon procrun finished
```
Stderr and stdout has no aditional information.


Java options from `elasticsearch-service.bat manager`
```
-XX:+UseConcMarkSweepGC
-XX:CMSInitiatingOccupancyFraction=75
-XX:+UseCMSInitiatingOccupancyOnly
-XX:+AlwaysPreTouch
-server
-Xss1m
-Djava.awt.headless=true
-Dfile.encoding=UTF-8
-Djna.nosys=true
-Djdk.io.permissionsUseCanonicalPath=true
-Dio.netty.noUnsafe=true
-Dio.netty.noKeySetOptimization=true
-Dio.netty.recycler.maxCapacityPerThread=0
-Dlog4j.shutdownHookEnabled=false
-Dlog4j2.disable.jmx=true
-Dlog4j.skipJansi=true
-XX:+HeapDumpOnOutOfMemoryError
-Xmx14336m
-Xms14336m
-Delasticsearch
-Des.path.home=c:\elasticsearch-6.6.1
-Des.path.conf=E:\ElasticConfig
-Des.distribution.flavor=oss
-Des.distribution.type=zip
```

If i start `bin\elasticsearch.bat` from comand line is working. 
Before I installed the full version (6.6.1) also from .zip and had no problem.

**Comment by ninja-saigon** [comment]
> 6.4.1 works well. Check your log files - under the logs directory. In my case even though I had the JAVA_HOME defined , it said it wasn't able to find JRE. Turned out it was in the User variables , moved it to System Environment variables and it works fine.

JAVA_HOME should be a system variable. Thanks

**Comment by HarelM** [comment]
I just encountered it on windows server 2012 when trying to start the service, should I open another issue?

**Comment by suhrab** [comment]
It happened to me on Windows Server 2019. I extracted zip to the Path, which contained **spaces**. 
Extracted to path with no spaces and it works

**Comment by yosiasz** [comment]
in my case it was a wrong config setting in the yml file
path.repo:
