### ISSUE TITLE
doc value may null_pointer_exception in script when scrolling

### ISSUE THREAD

**Issue by chenryn** [elastic/elasticsearch#21913]
**Elasticsearch version**: 2.3.2, 2.4.2

**Plugins installed**: []

**JVM version**:1.8

**OS version**:centos6.5

**Description of the problem including expected versus actual behavior**:
Try to use script filter when scrolling, the doc['fieldname'].value in some shards may return null_pointer_exception after several scroll running.
This problem may happen only if the hits is a bit large and is not always exception at same time.
btw, I'm sure all logs has such field and the search body can successfully run at common search API.

**Steps to reproduce**:
 1. indexing millions of apache access log line into the ES.
 2.run such shell `sh test.sh > test.log`:
```bash
#!/bin/bash
first_id=`curl -s -XGET 'http://192.168.1.81:9200/logstash-201611*/_search?pretty&scroll=1m' -d '{
  "size" : 10000,
  "query" : {
    "bool" : {
      "must" : {
        "term" : { "logtype" : "apache" }
      },
      "filter" : {
        "script" : {
          "script" : {
            "inline" : "doc[\"apache.method\"].value.length() > 2",
            "lang": "groovy"
          }
        }
      }
    }
  }
}' | jq '._scroll_id'`
for i in `seq 1 100`;do
curl -XGET 'http://192.168.1.81:9200/_search/scroll?pretty' -d '{
  "scroll" : "1m",
  "scroll_id" : '$first_id'
}'
done
```
 3. run `grep '"fail" : ' test.log`, you may see something like:
```
    "failed" : 0
    "failed" : 0
    "failed" : 0
    "failed" : 17,
    "failures" : [ {
        "reason" : "failed to run inline script [doc[\"apache.method\"].value.length() > 2] using lang [groovy]",
    "failed" : 17,
    "failures" : [ {
    "failed" : 17,
    "failures" : [ {
    "failed" : 17,
    "failures" : [ {
```

**Provide logs (if relevant)**:
The full failure output:
```
  "_shards" : {
    "total" : 90,
    "successful" : 73,
    "failed" : 17,
    "failures" : [ {
      "shard" : -1,
      "index" : null,
      "reason" : {
        "type" : "script_exception",
        "reason" : "failed to run inline script [doc[\"apache.method\"].value.length() > 2] using lang [groovy]",
        "caused_by" : {
          "type" : "null_pointer_exception",
          "reason" : "Cannot invoke method length() on null object"
        }
      }
    } ]
  },
```

**Describe the feature**:

**Comment by clintongormley** [comment]
@chenryn could you upload the stack trace as well please?

Also, any chance you could try this out in 5.0 (and with painless) to see if you can still reproduce it?

**Comment by jpountz** [comment]
> I'm sure all logs has such field

Is that also true for documents that do not match `"logtype" : "apache"`, or documents that are deleted but have not been expunged by a merge yet? There is no guarantee that the filter executes after the query (or vice versa), so the script could be evaluated against any document of the index, including deleted ones as I suggested in my previous sentence.

I am also curious whether this starts failing after all documents have been returned or any time. I see follow up requests after the one that complains that `apache.method` is missing have 17 failures too, what is the error for those?

**Comment by chenryn** [comment]
@clintongormley No 5.0 on production env now, I will try to reproduce this on my laptop later.(Midnight in China now)
@jpountz This is a pure appending ELK use case, we would delete any logs. And sorry, I don't understand what mean is "Is that also true for documents that do not match `logtype:apache`"?
The first time failed, only one failure message as I paste above, then the following times, 17 failure messages were:
```
  "failures" : [ {
      "shard" : -1,
      "index" : null,
      "reason" : {
        "type" : "search_context_missing_exception",
        "reason" : "No search context found for id [11404942]"
      }
    }, {
      "shard" : -1,
      "index" : null,
      "reason" : {
        "type" : "search_context_missing_exception",
        "reason" : "No search context found for id [11404944]"
      }
    }, {
      "shard" : -1,
      "index" : null,
      "reason" : {
        "type" : "search_context_missing_exception",
        "reason" : "No search context found for id [11404943]"
      }
    }, {
```
I think that because those search contexts were destoried by the first exception.

**Comment by jpountz** [comment]
> This is a pure appending ELK use case

OK. Good to know.

> Is that also true for documents that do not match logtype:apache"

I was wondering whether you had any document at all in your `logstash-201611*` indices that do not have a value for `apache.method`, including those that do not match the query that you put in the `must` clause: `"term" : { "logtype" : "apache" }`. What is the result of the below aggregation?

```
curl -s -XGET 'http://192.168.1.81:9200/logstash-201611*/_search' -d '{
  "size": 0,
  "aggs": {
    "missing_method": {
      "missing": {
        "field": "apache.method"
      }
    }
  }
}
```

**Comment by chenryn** [comment]
@jpountz yes, there are other "logtype"s. But how could an outside event break the must query?

**Comment by chenryn** [comment]
@clintongormley I try this on 5.0.0 with both groovy and painless, no error happen.

**Comment by jdconrad** [comment]
@jpountz Is this still worth discussing or can this be closed?

**Comment by rjernst** [comment]
There have been improvements in the handling of missing values in scripts and the associated documentation. Scripts never return null anymore, and instead should be checked for "no values" using `size() == 0` on the returned list of values from `doc`. Thus I think this issue can be closed.
