### ISSUE TITLE
`GET _mapping/X` causes illegal_state_exception and status 500

### ISSUE THREAD

**Issue by cwurm** [elastic/elasticsearch#21916]
**Elasticsearch version**: 5.0.1 (Elastic Cloud)
**Plugins installed**: [x-pack, ingest-*, analysis-*, etc.]
**JVM version**: (Elastic Cloud)
**OS version**: (Elastic Cloud)

**Description of the problem including expected versus actual behavior**:
Sending a query of the form `GET _mapping/X` returns an error, but probably not the one it should:

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_state_exception",
        "reason": "Failed to close the XContentBuilder"
      }
    ],
    "type": "illegal_state_exception",
    "reason": "Failed to close the XContentBuilder",
    "caused_by": {
      "type": "i_o_exception",
      "reason": "Unclosed object or array found"
    }
  },
  "status": 500
}
```

**Comment by rjernst** [comment]
I can reproduce this and am investigating.
