### ISSUE TITLE
The need to allow min_doc_count >shard_min_doc_count in significant_terms aggregation

### ISSUE THREAD

**Issue by voidlps** [elastic/elasticsearch#21927]
**Describe the feature**: 
In significant terms aggergation: allow min_doc_count > shard_min_doc_count is required when need to set shard_min_doc_count=0 to get correct bg_count in some cases

**Use-case description:**
In  index per time frame scenario, running significant_terms on different time-range requires to set shard_size=0,shard_min_doc_count=0 to get correct score.  In this case, setting min_doc_count to a larger number is still meaningful

 
there is the use-case we get very unexpected behaviour using default values:
1. environment: logstash created one index per day 
2. do a significant terms to logstash-* multiple indexes, with foreground [now-1h to now] / background [now-1d to now] using background-filter to check if there are something special in the log in last hour
  
we found the in many cases, we have some terms looks like very common, and bg_doc_count number seems incorrecnt, looks like it counts contains only documents of current day.  Esp at the hour just after midnight or the next.
  
A very special case to reproduce is, we have indexes logstash-20161201 & logstash-20161202, now=20161202 03:00 the foreground=[20161202 02:00-20161202 03:00], background=[20161201 03:00-201602 03:00], 
we may see the the many common term like "json" is reported as significant term, with bg_doc_count value having only doc with "json" in index logstash-20161202, but not  logstash-20161201

By reading document carefully and some source code, we understand where the issue comes from:
*the bg_count of "json" from shards of  logstash-20161201 will not be counted*  

because default value of shard_min_doc_count=1 will let the term "json" has no chance to be selected to let reducer count it 
since the foreground has no intersection to index logstash-20161201, so all terms of those shards will with doc_count=0

only when set min_doc_count=0,shard_size=0,shard_min_doc_count=0, we get the behaviour we expected originally.

However we still would like to set min_doc_count to some number instead extracting a long list to filter later in application, but min_doc_count > shard_min_doc_count is not allowed.  Any value set to min_doc_count cannot correct the behaviour.

**Comment by clintongormley** [comment]
@markharwood any thoughts?

**Comment by markharwood** [comment]
Generally, doing significant_terms analysis on time-based indices to find things significant about recent entries won't work.
The "foreground" query to match recent-stuff typically has no meaning on older indices. They will match nothing and without a foreground set will contribute nothing in the way of foreground or background statistics. Playing with size settings won't alter the fact that an empty query result = an empty response from that shard.

While time-based indices are the right approach for ageing content efficiently they are not the right physical arrangement for this type of analysis. You'll need to adopt another approach.
