### ISSUE TITLE
[code issue][discuss]TransportClient default with both ScheduledPing and NodesSampler

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#21929]
defalut build TransportClient with client.transport.ping_timeout and NettyTransport.PING_SCHEDULE. should default stop ScheduledPing ?

**Comment by colings86** [comment]
It is not clear what the bug is for this issue, could you please add more details about the bug you have seen and also include a script to recreate the bug the you are seeing?

**Comment by makeyang** [comment]
I mean since there is already sample, we don't have to schedule ping.

**Comment by jasontedor** [comment]
The application level pings (controlled by `transport.ping_schedule`) are not enabled by default, I don't think there is anything to do here.
