### ISSUE TITLE
Delete document API causes index-creation

### ISSUE THREAD

**Issue by mrosterm** [elastic/elasticsearch#21926]
I've recently stumbled upon that ES might create an index if there is a delete request for a document in it and the index does not exist. To me this seems veeeery weird. Anyone that can explain why and whether I can disable this?

```[2016-11-23 12:07:48,532][INFO ][cluster.metadata         ] [xxx-node] [xxx-2016.03] creating index, cause [auto(delete api)], templates [template.xxx], shards [2]/[1], mappings [_default_]```

**Comment by s1monw** [comment]
> To me this seems veeeery weird.

I share this, it's totally weird. I am +100 to remove this feature, I am not even sure why we didn't do this long ago. @clintongormley 

btw. you can disable this by setting `action.auto_create_index` to `false`

**Comment by mrosterm** [comment]
I use the auto-create-index feature when doing indexing operations, so entirely disabling it is not something I can do unfortunately. Happy to hear that I'm not the only one thinking it is a bit strange 😄

**Comment by ywelsch** [comment]
@s1monw the reason is given here:

https://github.com/elastic/elasticsearch/pull/15451#issuecomment-165772026

**Comment by mrosterm** [comment]
I guess the best way to fix it in my case, would be to fix my code to not issue a delete request for a document that does not exist. I just stumbled upon this behaviour and wanted to share it. Closing.

**Comment by s1monw** [comment]
I think we should have a dedicated setting for this which defaults to false.

**Comment by jasontedor** [comment]
Duplicates #15425
