### ISSUE TITLE
Document stance on file system

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#21925]
This question comes up quite often. Would be nice to document which file system we recommend/support, eg. for unix, we recommend ext4 or xfs.

**Comment by debadair** [comment]
[docs issue triage]

**Comment by rjernst** [comment]
The question hasn't come up really over the last 5 years. We essentially support (implicitly) the default filesystems of the OSes we support. Trying to claim direct support for particular filesystems would add another dimension to our testing which is not worth the cost. Instead, we will continue to support filesystems in the same way we support each OS: we test with defaults and will investigate issues up to the point we believe it is a system level problem.
