### ISSUE TITLE
Scripting: Strict parsing behaviour changed between 5.0 and 5.1 branches

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#21935]
The following test succeeds in 5.0, but fails in the 5.1 branches of Elasticsearch

```java
    public void testParsing() throws Exception {
        XContentBuilder builder = jsonBuilder().startObject().field("id", "my-script").endObject();
        XContentParser parser = JsonXContent.jsonXContent.createParser(builder.bytes());
        Script.parse(parser, ParseFieldMatcher.STRICT);
    }
```

It seems as if parsing `id` has been replaced with `stored`. I dont think that in minor releases this behaviour should change, as it might break plugins when parsing scripts.

**Comment by javanna** [comment]
@spinscale  strict parsing is really only used in testing at the moment. We don't expose to users a way to parse in strict mode. We are planning to change that, see #19552. I am not sure, but maybe this is just a deprecation problem? We are indeed deprecating stuff in 5.1 that wasn't deprecated in 5.0. Did you trace this back to the change that was made?

**Comment by s1monw** [comment]
💯  @javanna

**Comment by spinscale** [comment]
Found the commit https://github.com/elastic/elasticsearch/commit/530c49a4a07acbfbe55af71d25b7d871692b38d3

**Comment by nik9000** [comment]
We do want to deprecate things in minor releases. That is kind of the point of deprecation, at least for us it is. I'm gonna close because I think we're doing the right thing here.
