### ISSUE TITLE
How to avoid NOOP while partically updating elastic search document.

### ISSUE THREAD

**Issue by renukaradhya** [elastic/elasticsearch#21931]
**Elasticsearch version**: 5.0.0

**Plugins installed**: Head

**JVM version**:1.8

**OS version**:Linux

**Description of the problem including expected versus actual behavior**:

 I have a requirement to update a flag based on some criteria. But the flag updates are not working consistently, it updates some times and will not some times.  Getting lot of NOOP update status while updating. Number of messages I am processing/pushing is huge ~ 1-2 lakhs per minute. Every document insertion will result in update of older version of the document.

Below is my code for updation.

QueryBuilder queryBuilder = QueryBuilders.boolQuery().must(QueryBuilders.termQuery("clientId", clientId))
        .must(QueryBuilders.termQuery("applicable", "true"));
    SearchResponse searchResponse = client.prepareSearch(indexName).setTypes("messages").setQuery(queryBuilder)
        .addStoredField("id").setSize(100).execute().actionGet();
    for (SearchHit hit : searchResponse.getHits()) {
      String id = hit.getId();
      if (id != null) {
        UpdateRequest updateRequest = new UpdateRequest();
        updateRequest.index(indexName);
        updateRequest.type("messages");
        updateRequest.id(id);
        updateRequest.doc(XContentFactory.jsonBuilder().startObject().field("applicable", "false").endObject());
        try {
          UpdateResponse response = client.update(updateRequest).actionGet();
        } catch (Exception e) {
          e.printStackTrace();
        }
      }
    }
Here i want to update applicable flag to false for old messages for a client and insert a new message with applicable=true, So at query time the application will use this applicable flag. I am calling this above code before every insert of new message for a clientId.

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
