### ISSUE TITLE
Asking for advice on the ES based application design

### ISSUE THREAD

**Issue by xujintao521** [elastic/elasticsearch#21930]
**Elasticsearch version**:5.01

**Plugins installed**: []

**JVM version**:1.8

**OS version**:centos 7.1

**Description of the problem including expected versus actual behavior**:
Question1: Given several group of products, each group has 10 similar products. We want to choose the one which has the max score from each group. 
How can we design the process by using Elastic Search? Please give us any advice. Thank you in advance..
Question2: It seems that the Script class can't support integer. String type can do.

 
**Steps to reproduce**:
 1. for Question2: 
doc['key'].values.contains(int_type) 
Where doc['key']. is an array, and when we pass int_type as the parameter, it doesn't work.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jasontedor** [comment]
Elastic reserves GitHub for verified bug reports and feature requests, and provides a [forum](https://discuss.elastic.co) for general questions.
