### ISSUE TITLE
Provide more information on _failed_to_convert_ exceptions

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#21946]
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/IndexingSlowLog.java#L187

```
[2016-12-01 13:44:14,966][WARN ][index.indexing.slowlog.index] [node_name] [index][2] took[1.3m], took_millis[83880], type[match], id[AVi8VwvBCah0Po5KgBmM], routing[], source[source[_failed_to_convert_]
```

When we get the _failed_to_convert_ message in the slowlog entry for indexing, it doesn't provide any information on what part of the document it has trouble json-ing.  It will be helpful to provide some pointers so the end user can go check their source/ingest pipeline, etc..

**Comment by kunal642** [comment]
would the line and cloumn of the failure be enough??

**Comment by liketic** [comment]
Hi @ppf2 Can I work on this? I think at least, we can put the exception message to source. Any thoughts about this? Thanks. 😃

**Comment by cbuescher** [comment]
@ppf2 Here's an example of the way the error is logged currently for invalid json. For invalid json, e.g. the invalid token in the tests, currently we print:

```
[foo/123] took[10nanos], took_millis[0], type[test], id[id], routing[], source[_failed_to_convert_]
```

whereas with this change we would get the exception message as well:

```
[foo/123] took[10nanos], took_millis[0], type[test], id[id], routing[], source[_failed_to_convert_[Unrecognized token 'invalid': was expecting ('true', 'false' or 'null')
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@171f40bc; line: 1, column: 15]]], reformat[true], x_content_type[JSON]
```

Do you think that is helpful enough to close your issue?

**Comment by ppf2** [comment]
Thanks, I think `Unrecognized token 'invalid': was expecting ('true', 'false' or 'null')` will be useful.  `Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@171f40bc; line: 1, column: 15]]` For this part, it will be more useful if we can print out the actual content (or just small snippet of the content starting at where it is failing the parsing) instead of the column number.  But certainly, just having the exception returned is a good start.  Thx!

**Comment by cbuescher** [comment]
> it will be more useful if we can print out the actual content (or just small snippet of the content starting at where it is failing the parsing)

This is not going to be easy, since printing the "_source" in json form is the operation we are failing on here in the first place. So I think we'll have to go with the exception message here.

**Comment by ppf2** [comment]
Sounds good, thx!
