### ISSUE TITLE
use pattern implemented for sorting within nested objects to enable decay functions to be applied to properties within nested objects

### ISSUE THREAD

**Issue by rhbecker** [elastic/elasticsearch#21948]
**Describe the feature**:

In order to enable [decay functions](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/query-dsl-function-score-query.html#function-decay) to be applied to properties within nested objects, follow the pattern implemented for [sorting within nested objects](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/search-request-sort.html#nested-sorting) - i.e. allow functions like `gauss` to accept `nested_path` and `nested_filter` parameters.

If I have a property whose value is an array of nested objects like ...
```
"locations": [
  {
    "name": "home",
    "coordinates": [-87, 41]
  },
  {
    "name": "work",
    "coordinates": [-74, 20]
  }
]
```

I could then do a search like ...
```
GET /my_index/_search
{
  "query": {
    "function_score":{
      "functions": [
        {
          "gauss": {
            "locations.coordinates": {
              "origin": { "lat": 42, "lon": -88 },
              "scale": "100km"
            }
          },
          "nested_path": "exposedItems"
        }
      ]
    }
  }
}
```

`multi_value_mode` (documented [here](multi_value_mode)) would then need to understand how to evaluate the appropriate property of each nested object in deciding which to use to calculate the score - e.g. in the example above, `"multi_value_mode": "min"` would compare the `coordinates` value from both locations against `origin` and score the match based on the closer one.

Apologies if this is already somehow supported. I've been scouring documentation, issues in this repo, and discuss.elastic.co threads without finding much guidance on how `function_score` and nested objects are supposed to play together.

**Comment by clintongormley** [comment]
Hi @rhbecker 

We shouldn't add syntax specifically for nested fields.  Instead, here's an issue discussing how we could combine the scores from any query (including nested queries) https://github.com/elastic/elasticsearch/issues/17116
