### ISSUE TITLE
Unable to get field stats for unindexed fields

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch#21952]
**Elasticsearch version**: master
**Plugins installed**: x-plugins
**JVM version**: 1.8
**OS version**: macOS

**Description of the problem including expected versus actual behavior**:
I am unable to get stats about a field (like "aggregatable" and "searchable") if it's mapping has `"index": false`.

**Steps to reproduce**:
 1. sense script: https://gist.github.com/spalger/e2bada332f4f8a6cdbb6811998fbebcd
 2. observe that the field stats response does not have a section for the "num" field

From discuss user: https://discuss.elastic.co/t/why-is-kibana-unable-to-aggregate-non-indexed-fields-that-have-doc-values-true/67879

**Comment by jpountz** [comment]
@jimczi Can you have a look?

**Comment by jimczi** [comment]
I have a PR open for this here: https://github.com/elastic/elasticsearch/pull/21821
It was approved by Nik but I was planning on rewriting the serialization for the master branch after this comment:
https://github.com/elastic/elasticsearch/pull/21821/files#r89792384
Though it's more difficult than I though so I will merge this PR tomorrow and cleanup the serialization for the master branch later.
Thanks for opening this issue.

**Comment by FluxLemur** [comment]
Just to make sure, #21821 is expected to be in the v5.2.0 release of Kibana and Elasticsearch? And if so, what is expected date for the release (roughly)?

**Comment by jimczi** [comment]
> Just to make sure, #21821 is expected to be in the v5.2.0 release of Kibana and Elasticsearch? 

Correct

> And if so, what is expected date for the release (roughly)?

I would say beginning of next year but it's not decided yet ;)

**Comment by jpountz** [comment]
@jimczi Can it be closed now, or are there things left to do?

**Comment by jimczi** [comment]
That's strange, I though that https://github.com/elastic/elasticsearch/pull/21821 would close this issue but it didn't. I am closing it now ;)

**Comment by spalger** [comment]
@jimczi I'm not 100% sure, but I think it's because in the markdown for the description you linked to the issue, rather than using `#21952`.
