### ISSUE TITLE
`java.lang.ArrayIndexOutOfBoundsException` when requesting mapping fields

### ISSUE THREAD

**Issue by kadishmal** [elastic/elasticsearch#21967]
**Elasticsearch version**: 2.3.4

**Plugins installed**: [kopf,bigdesk,head]

**JVM version**: 1.8

**OS version**: CentOS 6

**Description of the problem including expected versus actual behavior**:

We manage time based indices, one per day. Each type represents a project. We have several thousand projects, each has a different mapping depending on their logs.

When setting up a Kibana index, particularly its index pattern, the request fails with 500 status code proxied from ES. The request that Kibana sends to ES is:

    GET /logs-*/_mapping/field/*?_=1480925187142&ignore_unavailable=false&allow_no_indices=false&include_defaults=true

The logs in ES master node:

```
[2016-12-05 18:06:51,375][WARN ][rest.suppressed          ] path: /logs-*/_mapping/field/*, params: {ignore_unavailable=false, allow_no_indices=false, index=logs-*, include_defaults=true, fields=*, _=1480928770404}
java.lang.ArrayIndexOutOfBoundsException
```

No stack trace or anything else considering that debug logging is enabled.

When I narrow the mapping request from `logs-*` to `logs-2016-12-*`, ES returns 3.2MB mappings data properly. I measured the total size of the mappings that covers `logs-*`. It's 826MB. So, I suspect ES cannot handle large amount of entries in the mapping which I think should be fixed.

**Comment by clintongormley** [comment]
Please could you paste the stack trace from the Elasticsearch logs

**Comment by kadishmal** [comment]
@clintongormley that's the point that ES is already configured in `debug` mode, and no other logs are available.

**Comment by clintongormley** [comment]
ah right - that's all that is logged.   Try repeating the request but add the query string param `?error_trace=true`

**Comment by colings86** [comment]
No further feedback. @kadishmal if you are still seeing this issue could you try what @clintongormley mentioned above, paste the result in a comment and reopen.
