### ISSUE TITLE
How to delete a illegal index name?

### ISSUE THREAD

**Issue by aniude** [elastic/elasticsearch#21965]
cause of my mistaken. now in indics' index name is %{[@metadata][index]}.

curl 'localhost:9200/_cat/indices?v'

health status index                 uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   %{[@metadata][index]} Pk6f0C5nTtKh37yQO1y5TQ   5   1     249088            0    163.1mb        163.1mb

when exec 'curl -XDELETE 'localhost:9200/%\{\[@metadata\]\[index\]\}?pretty'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "invalid escape sequence `%{[' at index 0 of: %{[@metadata][index]}"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "invalid escape sequence `%{[' at index 0 of: %{[@metadata][index]}"
  },
  "status" : 400
}
is that any method to delete it? or delete the filename directly by physical is ok?

**Comment by crossdsection** [comment]
What was the method?
