### ISSUE TITLE
ip type returns garbage when queried as field

### ISSUE THREAD

**Issue by burnstreet** [elastic/elasticsearch#21977]
**Elasticsearch version**: 5.0.0

**Plugins installed**: []

**JVM version**: openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

**OS version**: Ubuntu 16.04  4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
when querying for a field that is mapped as IP type, the result value is unicode garbage. 

**Steps to reproduce**:
 1. upload mapping 
POST /_template/test 
{
    "mappings": {
        "logevent": {
            "properties": {
                "@fields": {
                    "properties": {
                        "IP": {
                            "type": "ip"
                        }
                    }
                },
                "@logtype": {
                    "index": "not_analyzed",
                    "type": "keyword"
                },
                "@timestamp": {
                    "format": "strict_date_optional_time||epoch_millis",
                    "index": "not_analyzed",
                    "type": "date"
                }
            }

        }
    },
    "template": "test-bug"
}
 2. upload doc / create index
POST /test-bug/logevent/
{
   "@timestamp": "2016-12-05T06:59:41.393Z",
   "@fields": {
       "IP": "70.92.108.189"
   }
}
 3. query for field
POST /test-bug/logevent/_search
{
  "docvalue_fields" : [
    "@timestamp",
	"@fields.IP"
  ]
}

**Result:**
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "test-bug",
        "_type": "logevent",
        "_id": "AVjPswaq8VThoQGWfX4A",
        "_score": 1,
        "_source": {
          "@timestamp": "2016-12-05T06:59:41.393Z",
          "@fields": {
            "IP": "70.92.108.189"
          }
        },
        "fields": {
          "@fields.IP": [
            **"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000��l½"**
          ],
          "@timestamp": [
            1480921181393
          ]
        }
      }
    ]
  }
}

**Provide logs (if relevant)**:

**Comment by jpountz** [comment]
This is a bug indeed, I think we should return a formatted ip address as well as a formatted date.
