### ISSUE TITLE
Rename `delimiter_payload_filter` to `delimiter_payload`.

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#21978]
This pre-built token filter is inconsistent with other pre-built token filters since it includes `filter` in its name while the other ones don't.

**Comment by sangeethakp** [comment]
Hai! Can I kindly take up this issue and submit a PR?

**Comment by clintongormley** [comment]
Thanks for showing interest in contributing to Elasticsearch.

Here's a guide to how to go about it: https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md

**Comment by i-am-Nathan** [comment]
Hello! Its been over a month can i still take up this issue and submit a PR?

**Comment by gabrielhao** [comment]
Should this issue be closed after the PR ?
