### ISSUE TITLE
Using stored script faces “Too many dynamic script compilations within one minute” error.

### ISSUE THREAD

**Issue by xxx111x1** [elastic/elasticsearch#21970]
**Elasticsearch version**: 5.0
**Plugins installed**: [X-pack]
**JVM version**: 1.8.0_111
**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:
Hi Team,
We are facing "on_failure_message=[script] Too many dynamic script compilations within one minute, max: [32/min]; please use on-disk, indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_per_minute" error. and we are using stored script. as you can see below. 

We also change the "script.max_compilations_per_minute" to have a try, but it seems not work. Our index rate is around 15k/s, and the failed is around 20%.

**Configuration**: 
```
{
  "logstashLogs": {
    "description": "Get device id and user id",
    "processors": [
      {
        "script": {
          "lang": "painless",
          "id": "index-device-and-app"
        }
      },
      {
        "script": {
          "lang": "painless",
          "id": "extract-app-stat"
        }
      }
    ],
    "on_failure": [
      {
        "set": {
          "field": "_index",
          "value": "failed-{{ _index }}"
        }
      },
      {
        "set": {
          "field": "_error",
          "value": "{{ _ingest }}"
        }
      }
    ]
  }
}
```
**Scripts**:
index-device-and-app.painless:
```
if (ctx._index.startsWith('logstash-raw-')) {
    if (ctx.tag == 'gBbJrY' || ctx.tag == 'tThBgH') {
        def re = /^\d+\/\d+\/\d+\/(?<source>[^\/]+)\/(?<uid>\d+)\/(?<did>\d+)_\d+\.\S+$/;
        def m = re.matcher(ctx.parameters[0]);
        if (m.matches()) {
            ctx._index = ctx._index.replace('logstash-raw-', 'logstash-' + m.namedGroup('source') + '-');
            ctx.deviceId = m.namedGroup('did');
            ctx.userId = m.namedGroup('uid');
        }
    }
}
```

extract-app-stat.painless:
```
if (ctx._index.startsWith('logstash-app-')) {
    def re = /^\[(?<logtime>.*?)\] \[INFO\] \[STAT\] (?<measure>.*)$/;
    def m = re.matcher(ctx.parameters[1]);
    if (m.matches()) {
        def measureValues = /,/.split(m.namedGroup('measure'));
        def name = measureValues[0].replace(' ', '');
        def value = null;

        if (measureValues.length > 1) {
            value = measureValues[1].trim();
        }

        if (value == 'on' || value == 'off' || value == 'auto') {
            name = name + value;
            value = null;
        }

        if (value == null) {
            ctx[name + '_count'] = 1;
        } else {
            if (value.startsWith('time = ')) {
                value = Float.parseFloat(value.substring(7));
            }
            ctx[name] = value;
            ctx[name + '_count'] = 1;
        }
        ctx.stat = true;
    }
    re = /^\[(?<logtime>.*?)\].*$/;
    m = re.matcher(ctx.parameters[1]);
    if (m.matches()) {
        def f = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
        def p = new SimpleDateFormat('yy-MM-dd hh:mm:ss');
        f.setTimeZone(TimeZone.getTimeZone('Asia/Shanghai'));
        p.setTimeZone(TimeZone.getTimeZone('Asia/Shanghai'));
        ctx.logtime = f.format(p.parse(m.namedGroup('logtime')));
    }
}
```

**Provide logs (if relevant)**:

**Comment by nik9000** [comment]
@dakrone, I think this is some fun combination of your script limiter and ingest templates. Can you have a look?

**Comment by dakrone** [comment]
Sure I'll take a look at this.

> We also change the "script.max_compilations_per_minute" to have a try, but it seems not work.

@xxx111x1 can you explain a little bit more about this? This should be a dynamic setting. What do you mean by "seems not [to] work"?

**Comment by xxx111x1** [comment]
@dakrone 
Thanks for your reply, "seems not [to] work" means, the setting is work, but enlarging the max_compilations_per_minute value cannot resolve my problem.

**Comment by dakrone** [comment]
@xxx111x1 I've been trying to reproduce this, but without any luck, here's what I've done:

On 5.0.0, I started ES with `script.painless.regex.enabled: true`, then performed:

```json
POST /_scripts/painless/index-device-and-app?pretty
{
  "script": "if (ctx._index.startsWith('logstash-raw-')) {if (ctx.tag == 'gBbJrY' || ctx.tag == 'tThBgH') {def re = /^\\d+\\/\\d+\\/\\d+\\/(?<source>[^\\/]+)\\/(?<uid>\\d+)\\/(?<did>\\d+)_\\d+\\.\\S+$/; def m = re.matcher(ctx.parameters[0]); if (m.matches()) {ctx._index = ctx._index.replace('logstash-raw-', 'logstash-' + m.namedGroup('source') + '-'); ctx.deviceId = m.namedGroup('did'); ctx.userId = m.namedGroup('uid');}}} "
}

POST /_scripts/painless/extract-app-stat?pretty
{
  "script": "if (ctx._index.startsWith('logstash-app-')) {def re = /^\\[(?<logtime>.*?)\\] \\[INFO\\] \\[STAT\\] (?<measure>.*)$/; def m = re.matcher(ctx.parameters[1]); if (m.matches()) {def measureValues = /,/.split(m.namedGroup('measure')); def name = measureValues[0].replace(' ', ''); def value = null; if (measureValues.length > 1) {value = measureValues[1].trim();} if (value == 'on' || value == 'off' || value == 'auto') {name = name + value; value = null;} if (value == null) {ctx[name + '_count'] = 1;} else {if (value.startsWith('time = ')) {value = Float.parseFloat(value.substring(7));} ctx[name] = value; ctx[name + '_count'] = 1;} ctx.stat = true;} re = /^\\[(?<logtime>.*?)\\].*$/; m = re.matcher(ctx.parameters[1]); if (m.matches()) {def f = new SimpleDateFormat(\"yyyy-MM-dd'T'HH:mm:ss.SSSZ\"); def p = new SimpleDateFormat('yy-MM-dd hh:mm:ss'); f.setTimeZone(TimeZone.getTimeZone('Asia/Shanghai')); p.setTimeZone(TimeZone.getTimeZone('Asia/Shanghai')); ctx.logtime = f.format(p.parse(m.namedGroup('logtime')));}} "
}
```

To store the scripts in ES (which compiles them, so this would be 2 script compilations counted towards the bucket).

Then I added the pipeline as you had it defined:

```json
PUT /_ingest/pipeline/logstashLogs
{
  "description": "Get device id and user id",
  "processors": [
    {
      "script": {
        "lang": "painless",
        "id": "index-device-and-app"
      }
    },
    {
      "script": {
        "lang": "painless",
        "id": "extract-app-stat"
      }
    }
  ],
  "on_failure": [
    {
      "set": {
        "field": "_index",
        "value": "failed-{{ _index }}"
      }
    },
    {
      "set": {
        "field": "_error",
        "value": "{{ _ingest }}"
      }
    }
  ]
}
```

I then ran the following in a tight loop over and over to try and trip the circuit breaker:

```json
POST /logstash-app-1/doc?pipeline=logstashLogs&pretty
{"body": "foo"}
```

However, I was never able to get the circuit breaker to trip.

Can you confirm this is how you're using the system? Is there perhaps something that continually re-adds the script that could be causing more compilation? Am I missing any steps for how you are running this?

**Comment by xxx111x1** [comment]
@dakrone, it is wired that there is no error now. The only thing we did is changing the logstash configuration.

We wrote two configs for two topics, and we found it was wroten twince into Elastic Search. So we merge the two configs to one.

**Before the change, two configuration files.**
input {
  kafka {
    bootstrap_servers => "10.2.1.23:9092"
    topics => ["flume_1"]
    consumer_threads => 4
    session_timeout_ms => "30000"
    max_poll_records => "64"
    codec => "json"
  }
}
filter {
  date {
    match => ["timestamp", "UNIX_MS"]
    timezone => "Asia/Shanghai"
  }
}
output {
  elasticsearch {
    hosts => ["10.2.1.33:9200","10.2.1.28:9200","10.2.1.32:9200","10.2.1.35:9200                                                       "]
    index => "logstash-raw-%{+YYYY-MM-dd}"
    user => "logstash"
    password => "1111111"
    pipeline => "logstashLogs"
    flush_size => 4096
  }
}

input {
  kafka {
    bootstrap_servers => "10.2.1.23:9092"
    topics => ["ipc002_1"]
    consumer_threads => 4
    session_timeout_ms => "30000"
    max_poll_records => "64"
    codec => "json"
  }
}
filter {
  date {
    match => ["timestamp", "UNIX_MS"]
    timezone => "Asia/Shanghai"
  }
}
output {
  elasticsearch {
    hosts => ["10.2.1.33:9200","10.2.1.28:9200","10.2.1.32:9200","10.2.1.35:9200                                                       "]
    index => "logstash-raw-%{+YYYY-MM-dd}"
    user => "logstash"
    password => "1111111"
    pipeline => "logstashLogs"
    flush_size => 4096
  }
}




**Now, one files**
input {
  kafka {
    bootstrap_servers => "10.2.1.23:9092"
    topics => ["flume_1", "ipc002_1"]
    consumer_threads => 4
    session_timeout_ms => "30000"
    max_poll_records => "64"
    codec => "json"
  }
}
filter {
  date {
    match => ["timestamp", "UNIX_MS"]
    timezone => "Asia/Shanghai"
  }
}
output {
  elasticsearch {
    hosts => ["10.2.1.33:9200","10.2.1.28:9200","10.2.1.32:9200","10.2.1.35:9200                                                       "]
    index => "logstash-raw-%{+YYYY-MM-dd}"
    user => "logstash"
    password => "1111111"
    pipeline => "logstashLogs"
    flush_size => 4096
  }
}

I don't think this is relative with this issue, but now, there is no more errors.

**Comment by dakrone** [comment]
Can you include the entire exception and stacktrace from the logs when this occurs next? I'd like to see where it came from.

Are you doing any other scripting in this cluster other than this pipeline during indexing?

**Comment by xxx111x1** [comment]
Sure, however do you know which log file I should looking for? Since we cannot find this error message neither in "logstash-plain-{date}.log" nor  "elasticsearch-{date}.log" files where the date is the day errors happended.

As for the second question, no other scripts .

**Comment by dakrone** [comment]
> Sure, however do you know which log file I should looking for?

It should be in the regular `elasticsearch.log` file

**Comment by colings86** [comment]
No further feedback. @xxx111x1 if you have the exception then please paste it in a comment and reopen
