### ISSUE TITLE
Add types options to DeleteByQueryRequest - java api

### ISSUE THREAD

**Issue by eliranmoyal** [elastic/elasticsearch#21984]
**Elasticsearch version**: 5.0.1

**Describe the feature**:
Hey  I'm using the java api in order to do delete requests
I need to delete specific types from my index
 DeleteByQueryRequest class contains just indices function and not types function.
on elastic1.x and the deleteByQuery plugin there was a java api option for deleting  specific types
Can you add it to the class api?
Thanks!

**Comment by bawse** [comment]
Is this issue still open?

**Comment by javanna** [comment]
@bawse thanks for pointing this out, it should have been closed when #23265 was merged.
