### ISSUE TITLE
Incorrect Metrics Reported in version 5.0.1

### ISSUE THREAD

**Issue by animageofmine** [elastic/elasticsearch#21988]
**Elasticsearch version**: 5.0.1

**Plugins installed**: N/A

**JVM version**: 
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

**OS version**:
Linux elasticsearchClient1 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
The issue is report here: https://discuss.elastic.co/t/incorrect-metrics-reported-in-version-5-0-1/67909

Basically, few of the metrics reported by Elasticsearch for version 5.0.1 seem incorrect. I verified by comparing the metrics from version 2.4.2 

Version 2.4.2 clearly shows free memory around 11G, but version 5.0.1 reports 25G which is more than the memory of the host, scary!:open_mouth:

We are planning to deploy things to production, so your quick response will be very much appreciated. 

**Steps to reproduce**:
 1. Start a dockerized (debian) container for elasticsearch 5.0.1
 2. curl -XGET 'http://localhost:9200/_nodes/stats' | jq . | more
 3. Look for metric os.mem.free_in_bytes. It should show memory more than that is reported by OS
 4. Stop the docker container "docker stop <containerIdOrName> 
 5. Start dockerized (debian) container for elasticsearch 2.4.2 
 6. Perform steps 2-3 and compare the same metric. 2.4.2 reports accurate numbers / metrics, while 5.0.1 does not. 

**Provide logs (if relevant)**:
```
             total       used       free     shared    buffers     cached
Mem:           14G       4.0G        10G       508K       1.3M       3.1G
-/+ buffers/cache:       990M        13G
Swap:         3.9G         0B       3.9G

```
VERSION 5.0.1 (INCORRECT)
```
curl -XGET 'http://localhost:9200/_nodes/stats' | jq . | more
"os": {
        "timestamp": 1480968507747,
        "cpu": {
          "percent": 0,
          "load_average": {
            "1m": 0.07,
            "5m": 0.07,
            "15m": 0.06
          }
        },
        "mem": {
          "total_in_bytes": 31170383872,
          "free_in_bytes": 24336519168,
          "used_in_bytes": 6833864704,
          "free_percent": 78,
          "used_percent": 22
        },
        "swap": {
          "total_in_bytes": 4194299904,
          "free_in_bytes": 4194299904,
          "used_in_bytes": 0
        }
      },
```
```
top - 20:13:30 up 5 days, 23:12,  0 users,  load average: 0.02, 0.06, 0.07
Tasks:   5 total,   1 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.8 us,  0.2 sy,  0.0 ni, 99.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  14972960 total,  6439536 used,  8533424 free,     1332 buffers
KiB Swap:  4095996 total,        0 used,  4095996 free.  3229128 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20   0   21888   1864   1440 S   0.0  0.0   0:00.07 start.sh
   60 elastic+  20   0 5812272 2.359g  16132 S   0.0 16.5   0:20.18 java
  143 root      20   0    5952    612    524 S   0.0  0.0   0:00.00 tail
  161 root      20   0   21952   2160   1652 S   0.0  0.0   0:00.07 bash
  172 root      20   0   23492   1352   1076 R   0.0  0.0   0:00.00 top

```
VERSION 2.4.2 (CORRECT)
```
curl -XGET 'http://localhost:9200/_nodes/stats' | jq . | more
"os": {
        "timestamp": 1480966154732,
        "cpu_percent": 1,
        "load_average": 0.44,
        "mem": {
          "total_in_bytes": 15332311040,
          "free_in_bytes": 11011239936,
          "used_in_bytes": 4321071104,
          "free_percent": 72,
          "used_percent": 28
        },
        "swap": {
          "total_in_bytes": 4194299904,
          "free_in_bytes": 4194299904,
          "used_in_bytes": 0
        }
      },
```
```
top - 20:17:03 up 5 days, 23:15,  0 users,  load average: 0.03, 0.06, 0.06
Tasks:   3 total,   1 running,   2 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.8 us,  0.2 sy,  0.0 ni, 99.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  14972960 total,  4220556 used, 10752404 free,     1332 buffers
KiB Swap:  4095996 total,        0 used,  4095996 free.  3229396 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 elastic+  20   0 4655716 239172  15852 S   0.0  1.6   0:08.50 java
   94 root      20   0   21944   2112   1632 S   0.0  0.0   0:00.07 bash
  103 root      20   0   23492   1352   1076 R   0.0  0.0   0:00.00 top
```

**Comment by animageofmine** [comment]
Is there anyone looking at this  bug? Or are we on our own with the new versions?

**Comment by javanna** [comment]
I had a look and I don't see any particular regression in our OS stats. On my machine, I get the same values when I compare 2.4 output with 5.0 output. I think this may have to do specifically with docker, though we have to verify what changed around this with 5.0. @jasontedor do you happen to have any idea?

**Comment by jasontedor** [comment]
Sorry, but this appears to be a Docker issue. I can reproduce it, but only inside a Docker container. Yet, it has nothing to do with Elasticsearch as the following Java code shows:

```java
import java.lang.management.ManagementFactory;
import java.lang.management.OperatingSystemMXBean;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

public final class Memory {
    public static void main(String[] args) throws NoSuchMethodException, IllegalAccessException, InvocationTargetException, ClassNotFoundException {
	final OperatingSystemMXBean osMxBean = ManagementFactory.getOperatingSystemMXBean();
	final Method method = Class.forName("com.sun.management.OperatingSystemMXBean").getMethod("getFreePhysicalMemorySize");
	final long value = (long) method.invoke(osMxBean);
	System.out.println(value);
    }
}
```

This produces the same output as Elasticsearch does running inside the container. This isn't surprising, since this is exactly the same code that we use inside of Elasticsearch to report the free memory statistics. Why is it working in the 2.4.2 image and not the 5.0.1 image? I don't know what libraries these two images are built on, but I'm sure there are some discrepancies and they likely account for the difference but it's clearly not an Elasticsearch issue.

**Comment by animageofmine** [comment]
@jasontedor Thanks for looking into it. 

Do you mean that you were able to repro the issue when you dockerized ES 5.0.1, but if you execute the same thing on host (no container), you can't repro?

Following is the dockerfile content that matters for 5.0.1

```
FROM openjdk:8-jre 

ARG DEBIAN_FRONTEND=noninteractive
RUN set -x \
 && apt-get update -qq \
 && apt-get install -qqy --no-install-recommends ca-certificates curl \
 && apt-get install -qqy jq \
 && rm -rf /var/lib/apt/lists/* \
 && curl -L -o /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
 && curl -L -o /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
 && export GNUPGHOME="$(mktemp -d)" \
 && gpg --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
 && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
 && rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc \
 && chmod +x /usr/local/bin/gosu \
 && gosu nobody true \
 && apt-get clean \
 && set +x

ENV ES_VERSION 5.0.1
ENV ES_PACKAGE elasticsearch-${ES_VERSION}.deb
ENV ES_GID 991
ENV ES_UID 991

RUN apt-get update -qq \
 && apt-get install -qqy openjdk-8-jdk \
 && apt-get clean \
 && groupadd -r elasticsearch -g ${ES_GID} \
 && curl https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add - \
 && useradd -r -s /usr/sbin/nologin -M -c "Elasticsearch service user" -u ${ES_UID} -g elasticsearch elasticsearch \
 && curl -O https://artifacts.elastic.co/downloads/elasticsearch/${ES_PACKAGE} \
 && dpkg -i ${ES_PACKAGE} \
 && rm -f ${ES_PACKAGE}



```

**Comment by jasontedor** [comment]
@animageofmine That's correct, it reproduces on Dockerized 5.0.1 (and this means that I see Elasticsearch and the simple Java program I gave above reporting free memory that are in discordance with `free` inside in the Docker container), but it does not reproduce on the host.

**Comment by animageofmine** [comment]
Thanks for confirming. Let me see, if I can find something useful here. Strange to find this issue only in dockerized container. 

When you ran directly on your host, is the host debian based? I am just wondering if java 1.8 has issues on debian.

**Comment by jasontedor** [comment]
> Thanks for confirming. Let me see, if I can find something useful here. Strange to find this issue only in dockerized container.

I agree, it's quite puzzling. I have more info for the puzzle too. I put together a trivial C program that is equivalent to the code the JVM executes when it is getting free memory from the system.

```c
#include <stdio.h>
#include <unistd.h>

int main(int argc, char **argv) {
  long pageSize = sysconf(_SC_PAGESIZE);
  long availablePhysicalPages = sysconf(_SC_AVPHYS_PAGES);
  printf("%ld\n", availablePhysicalPages * pageSize);
}
```

This program produces the *correct* value inside the host (correct as measured by matching `free` and `/proc/meminfo` (if you `strace` the JVM when it's getting the free memory from the system, and `strace` the above code, you'll see that they both just parse read `/proc/meminfo`).

> When you ran directly on your host, is the host debian based?

I reproduced it on both an Alpine Linux based host (Moby, on Docker for Mac on my laptop), and on a Fedora host (my bare-metal Linux workstation).

**Comment by spinscale** [comment]
I can only score with half baked docker knowledge, but I just remembered from some playing around time ago that the `/proc` fs is shared and thus contains the host statistics, but is not cgroup aware.

Can you start the docker instance with the `-m` parameter?
