### ISSUE TITLE
[TEST] Incorrect indentation in the `skip` part of YAML files leads to incorrect definitions

### ISSUE THREAD

**Issue by karmi** [elastic/elasticsearch#21980]
Frequently, in the `skip` definition of tests, we use incorrect indentation, like in [`cat.nodes/10_basic.yaml`](https://github.com/elastic/elasticsearch/blob/d77d4fa/rest-api-spec/src/main/resources/rest-api-spec/test/cat.nodes/10_basic.yaml#L63-L65):

```yaml
- skip:
  version: " - 5.0.0"
  reason:  The full_id setting was rejected in 5.0.0 see #21266
```

The `version` and `reason` keys are on the same level as `skip`, leading to an incorrect definition of the skip section (example based on Ruby):

```json
[{"skip":null,"version":" - 5.0.0","reason":"The full_id setting was rejected in 5.0.0 see"}]
```

The expected definition is:

```json
[{"skip":{"version":" - 5.0.0","reason":"The full_id setting was rejected in 5.0.0 see"}}]
```

This happens frequently also for the `do` clauses (see eg. 8c721b10af2b3f300d45dc9f615e71b5c08c958d), leading to incorrect test definitions. It seems that the Java YAML parser is more lenient/intelligent than parsers for other languages, because these tests seem to run under Java, but fail under Ruby, Python, etc.

I suggest we add code to the YAML test runner which verifies that every clause ("action") such as `do`, `skip`, `match` has only a _single key_ and throws an error otherwise. The Python runner already [does this verification](https://github.com/elastic/elasticsearch-py/blob/master/test_elasticsearch/test_server/test_common.py#L98), and when it has been added to the Ruby runner, it has identified the example listed in this issue.

----

/cc @elastic/es-clients

**Comment by karmi** [comment]
Thanks, @javanna!!

**Comment by javanna** [comment]
sorry it took me a while to get to this @karmi , it was just our own parsing code that was lenient, and following the fix I had to fix a bunch of tests too :)

**Comment by HonzaKral** [comment]
Thanks @javanna, this is great news!
