### ISSUE TITLE
Filter clause (incorrectly) adds additional search results

### ISSUE THREAD

**Issue by phile314** [elastic/elasticsearch#21996]
**Elasticsearch version**:
2.4.0

**Plugins installed**: []

**JVM version**:
openjdk version "1.8.0_122"
OpenJDK Runtime Environment (build 1.8.0_122-00)
OpenJDK 64-Bit Server VM (build 25.122-b00, mixed mode)

**OS version**:
Debian 8

**Description of the problem including expected versus actual behavior**:
Adding a filter clause to  a query with a single should clause causes additional results to be returned. I expect a filter to only remove results. Adding a filter should never increase the number of results in my opinion. The documentation is not a hundred percent clear on the filter behavior, but it certainly doesn't mention/justify the behavior I observed.

**Steps to reproduce**:
 1. Create index
<pre>
PUT test_es_bug
{
       "vacancy": {
          "properties": {
              "id": {
	            "type": "long"
	          },
	          "jobTitle": {
	            "term_vector": "yes",
	            "type": "string"
	          }
          }
       }
}
</pre>
2. Create an index entry
<pre>
PUT test_es_bug/vacancy/1
{
    "jobTitle": "Java Developer"
}
</pre>
 3. Executing the following query will yield zero results:
<pre>
GET test_es_bug/_search
{ "query":
   {
  "bool" : {
    "should" : {
          "match" : {
            "jobTitle" : {
              "query" : "bla",
              "type" : "boolean"
            }
         }
      }
    }
  }
}
</pre>
 4. If a filter clause is added, more than zero results are returned:
<pre>
GET test_es_bug/_search
{ "query":
   {
  "bool" : {
    "filter" : {
      "bool" : {
        "mustNot" : {
          "terms" : {
            "jobTitle" : [ "bla" ]
          }
        }
      }
    },
    "should" : {
          "match" : {
            "jobTitle" : {
              "query" : "bla",
              "type" : "boolean"
            }
         }
      }
    }
  }
}
</pre>
Result:
<pre>
{
   "took": 1,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 0,
      "hits": [
         {
            "_index": "test_es_bug",
            "_type": "vacancy",
            "_id": "1",
            "_score": 0,
            "_source": {
               "jobTitle": "Java Developer"
            }
         }
      ]
   }
}
</pre>
**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jpountz** [comment]
Thanks for the detailed example.

This is the [expected behaviour](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html#query-dsl-bool-query): if the query does not have `must` or `filter` clauses, then at least one `should` clause must match, but if there is one or more `must` or `filter`, then the `should` clauses become optional and only give better scores to the documents that they match.

You can require that one should clause must match by setting `minimum_should_match=1` on the `bool` query. Another option could be to make this a `must` clause if you do not plan on adding more `should` clauses.

**Comment by phile314** [comment]
Thanks for the amazingly fast response:-)

Your answer makes sense. There might still be some way to improve the documentation. I have read the  [Bool Query Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html#query-dsl-bool-query) before opening the bug (maybe should have mentioned that), but I found it didn't specify exactly how the ``filter``+``should`` combination should behave.


> if there is one or more must or filter, then the should clauses become optional and only give better scores to the documents that they match.

For combinations of ``must`` and ``should`` clauses, this is what I would naively expect, but you might consider adding a note explaining that it also applies to the ``filter``+``should`` combination.

**Comment by jpountz** [comment]
Maybe you could open a pull request to improve the documentation? Reference docs are under `docs/reference` in this repo.

**Comment by phile314** [comment]
I really would like to, but the CLA makes this difficult/too complicated for me.
