### ISSUE TITLE
S3 snapshot repo documentation wrong for "read_only"

### ISSUE THREAD

**Issue by msimos** [elastic/elasticsearch#22007]
**Elasticsearch version**:

Elasticsearch 5.0.0

**Plugins installed**: []
[msimos@msi-gs60 elasticsearch-5.0.0]$ bin/elasticsearch-plugin list --verbose
Plugins directory: /home/msimos/Downloads/elasticsearch-5.0.0/plugins
repository-s3
- Plugin information:
Name: repository-s3
Description: The S3 repository plugin adds S3 repositories
Version: 5.0.0
 * Classname: org.elasticsearch.plugin.repository.s3.S3RepositoryPlugin
x-pack
- Plugin information:
Name: x-pack
Description: Elasticsearch Expanded Pack Plugin
Version: 5.0.0
 * Classname: org.elasticsearch.xpack.XPackPlugin

**JVM version**:

OpenJDK 1.8.0-111

**OS version**:

Fedora Linux

**Description of the problem including expected versus actual behavior**:

Documentation here states:

https://www.elastic.co/guide/en/elasticsearch/plugins/5.0/repository-s3-repository.html

read_only
Makes repository read-only. Defaults to false.

But this doesn't appear to work.

**Steps to reproduce**:

[msimos@msi-gs60 es]$ curl -u elastic:changeme http://localhost:9200/_snapshot/s3_repo1?pretty
{
  "s3_repo1" : {
    "type" : "s3",
    "settings" : {
      "bucket" : "xxxxx.elasticsearch.org",
      "base_path" : "/mikesimos",
      "endpoint" : "s3.amazonaws.com",
      "protocol" : "http",
      "read_only" : "true"
    }
  }
}

[msimos@msi-gs60 es]$ curl -XPUT -u elastic:changeme http://localhost:9200/_snapshot/s3_repo1/backup3?pretty
{
  "accepted" : true
}

This should fail. However this works using "readonly": true works:

[msimos@msi-gs60 es]$ curl -u elastic:changeme http://localhost:9200/_snapshot/s3_repo1?pretty       
{
  "s3_repo1" : {
    "type" : "s3",
    "settings" : {
      "bucket" : "xxxxx.elasticsearch.org",
      "base_path" : "/mikesimos",
      "endpoint" : "s3.amazonaws.com",
      "protocol" : "http",
      "readonly" : "true"
    }
  }
}
[msimos@msi-gs60 es]$ curl -XPUT -u elastic:changeme http://localhost:9200/_snapshot/s3_repo1/backup3?pretty
{
  "error" : {
    "root_cause" : [
      {
        "type" : "repository_exception",
        "reason" : "[s3_repo1] cannot create snapshot in a readonly repository"
      }
    ],
    "type" : "repository_exception",
    "reason" : "[s3_repo1] cannot create snapshot in a readonly repository"
  },
  "status" : 500
}

**Comment by msimos** [comment]
While I haven't tested it the Azure snapshot repo also has the same read_only flag. Don't know if this is correct or not. I don't have an Azure account to test.

**Comment by dadoonet** [comment]
Agreed that it's also applicable to azure.
If I recall correctly it's coming by inheritance from core.
