### ISSUE TITLE
Primary promotion violates NodeVersionAllocationDecider

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#22002]
When a primary fails, a replica shard is promoted to primary to take it's place. If the replica that is promoted resides on a node with a higher ES version than what's on nodes with other replicas, the newly promoted primary might use a new postings format or codec that is not available on the replication target nodes.
Preventing a primary to be on a node with a higher version than nodes with replicas is currently done using an allocation decider (`NodeVersionAllocationDecider`). Allocation deciders are only checked though when a primary or a replica is allocated / moved, not when a replica is promoted to primary.

**Comment by ywelsch** [comment]
There is another offender I think: Upon primary relocation (which can be done from an old to a new node), there is a short period in time during relocation handoff where the relocation target (on a newer node) replicates back to the relocation source (on an older node). /cc: @bleskes

**Comment by bleskes** [comment]
>  the newly promoted primary might use a new postings format or codec that is not available on the replication target nodes.

Note that is currently OK as it is only relevant when doing a recovery. However we want to make this rule stricter so it will apply at all times (and use it for other stuff).

>  Upon primary relocation (which can be done from an old to a new node), there is a short period in time during relocation handoff where the relocation target (on a newer node) replicates back to the relocation source (on an older node).

That's a good one. I think the period is longer though - one the primary has relocated from old to new we can end up in a situation that other replicas are on old for a long time. That part is solvable by preventing relocation of primaries from old to new if there is another replica on an old node (which will mean move the replicas first).   However the scenario you describe still holds - and it gets messy. Something to think about - I don't see an immediate solution .

**Comment by ywelsch** [comment]
Replication from a newer node to an older node is ok, and difficult to avoid (e.g. primary relocation during rolling restart). The recovery is avoided as when then old primary fails, all initializing shards are failed as well.
