### ISSUE TITLE
5.0.2 - Terms Aggregate Field [is_first_occurrence] of type [boolean] does not support custom time zones

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#22009]
Obviously the following needs work (porting from 1.x)... But this error is just unreal.  I'm trying to provide a default value for a terms field: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html and https://www.elastic.co/guide/en/elasticsearch/reference/current/boolean.html

```
PUT test 
{
  "mappings": {
    "test": {
      "properties": {
        "is_first_occurrence": {
          "type": "boolean"
        }
      }
    }
  }
}

POST /test/test/_search
{
  "size": 0,
  "aggs": {
    "terms_is_first_occurrence": {
      "terms": {
        "field": "is_first_occurrence",
        "missing": "false"
      }
    }
  }
}
```

Returns the following error a very large percentage of the time, otherwise it succeeds
```json
 {
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Field [is_first_occurrence] of type [boolean] does not support custom time zones"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "test",
        "node": "qCyn3KxuRCS2cUBxDMbz2g",
        "reason": {
          "type": "illegal_argument_exception",
          "reason": "Field [is_first_occurrence] of type [boolean] does not support custom time zones"
        }
      }
    ],
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "Field [is_first_occurrence] of type [boolean] does not support custom time zones"
    }
  },
  "status": 400
}
```

**Comment by niemyjski** [comment]
Seems specifying any value for `missing` doesn't work. I also tried `"include": 1` and that blew up with 

```json
{
  "error": {
    "root_cause": [
      {
        "type": "parsing_exception",
        "reason": "Unexpected token VALUE_NUMBER [include] in [terms_is_first_occurrence].",
        "line": 7,
        "col": 20
      }
    ],
    "type": "parsing_exception",
    "reason": "Unexpected token VALUE_NUMBER [include] in [terms_is_first_occurrence].",
    "line": 7,
    "col": 20
  },
  "status": 400
}`
```

**Comment by jpountz** [comment]
Thanks for the bug report. I can reproduce the issue that you describe.

**Comment by telser** [comment]
Also hit this bug, we see it for text fields and boolean fields. Really confusing issue.

**Comment by drewboardman** [comment]
Hit this bug as well. We discovered it does not throw an error with `keywordField` types.

    "aggregations" : {
    "statuses" : {
      "terms" : {
        "field" : "myIntField",
        "missing" : "other"
      }
    }

`
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Field [myIntField] of type [integer] does not support custom time zones"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "production_index",
        "node": "myNode",
        "reason": {
          "type": "illegal_argument_exception",
          "reason": "Field [myIntField] of type [integer] does not support custom time zones"
        }
      }
    ],
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "Field [myIntField] of type [integer] does not support custom time zones"
    }
  },
  "status": 400
}`
