### ISSUE TITLE
Remove reference to indices.recovery.concurrent_streams in breaking changes

### ISSUE THREAD

**Issue by n0othing** [elastic/elasticsearch#22001]
Our 5.0 [breaking changes ](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_settings_changes.html#_recovery_settings) emphasize `indices.recovery.concurrent_streams` as a replacement for `index.shard.recovery.concurrent_streams` : 
```
index.shard.recovery.concurrent_streams is superseded by indices.recovery.concurrent_streams
```

However, `indices.recovery.concurrent_streams` has been removed in 5.0 and is an invalid setting.

```
[2016-12-06T10:00:22,766][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [indices.recovery.concurrent_streams] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
```

**Comment by clintongormley** [comment]
@s1monw @bleskes has this setting been removed, or just not exposed?

**Comment by bleskes** [comment]
@clintongormley it's completely removed in #15372  and replaced with `cluster.routing.allocation.node_concurrent_recoveries`

**Comment by s1monw** [comment]
@n0othing would you mind opening a PR to fix that docs issue?

**Comment by n0othing** [comment]
https://github.com/elastic/elasticsearch/pull/22208
