### ISSUE TITLE
Type field missing in get mapping result

### ISSUE THREAD

**Issue by ppadovani** [elastic/elasticsearch#22011]
**Elasticsearch **: 5.0.2
**Plugins installed**: []
**JVM version**: 8
**OS version**: OS X 10.11.6
**Description of the problem including expected versus actual behavior**:

Performing a get mapping on the REST interface no longer returns information about nested objects. Given a mapping with nested objects, the 'type' is missing:

"type": "nested",
"properties": {
...
}

There is now no way to know if an object is nested or not. Additionally, there is no way to 'copy' a mapping from one cluster to another by just retrieving the mapping. The original JSON used to create the mapping must always be used. Additionally, verification of a mapping on a cluster to the original JSON can no longer be performed.

**Comment by clintongormley** [comment]
This is incorrect:

```
PUT t 
{
  "mappings": {
    "t": {
      "properties": {
        "nested": {
          "type": "nested"
        },
        "object": {
          "type": "object"
        }
      }
    }
  }
}

GET t/_mapping
```

returns:

```
{
  "t": {
    "mappings": {
      "t": {
        "properties": {
          "nested": {
            "type": "nested"
          },
          "object": {
            "type": "object"
          }
        }
      }
    }
  }
}
```

If you can come up with a reproduction that shows otherwise, then please open a new issue with the details

**Comment by ppadovani** [comment]
I'm a fool... 

I screwed up my test mapping when I created my index.

forgive me... ;-)
