### ISSUE TITLE
`require_field_match` should include `_all` field query 

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#22017]
Currently if `require_field_match` is true the highlighter extracts the parts of the query that target the field being highlighted. It becomes a little bit fuzzy when the `_all` field is involved since this field can match the content of any field but is not taken in account when `require_field_match` is true. The new `all_fields` mode solves this issue because the generated query now contains a reference to the requested fields (the query targets all fields instead of one big field that copied the other fields at indexing time). This also means that the highlighter behaves differently if `_all` is enabled or disabled. We could fix this discrepancy by changing the meaning of `require_field_match=true` to include queries that target the `_all` field. For accuracy we could extract `_all` field query only if the field being highlighted is included in `_all` (which can be disabled/enabled in the mapping).

Relates to https://github.com/elastic/kibana/pull/9091

**Comment by javanna** [comment]
I wonder how complex this would be and if it's worth it given that on the long run we want to get rid of the _all field. The new `all_fields` mode already works it seems, should we just document that this is the recommended solution over highlighting against the `_all` field?

**Comment by jimczi** [comment]
> I wonder how complex this would be and if it's worth it given that on the long run we want to get rid of the _all field

I think it's fairly easy to do for the `plain` and the `unified` highlighter. Since we won't get rid of the _all field in 5.x I think it can still be useful. 

> The new all_fields mode already works it seems, should we just document that this is the recommended solution over highlighting against the _all field?

Absolutely, the `all_fields` mode is a perfect fit since it will create dedicated queries for each field. When using `_all` we only have one query and the analyzer that creates the query might be different than the one set on the explicit field. Still I wonder if we should try to fix the discrepancy since we don't know when we will remove the _all field completely ?

**Comment by javanna** [comment]
I don't know, my personal opinion is that highlighting the `_all` field with `require_field_match` set to `true` means not understanding what highlighting is and does. Certainly this comes from having changed the default `require_field_match` value to `true`, which happened some versions ago. The `_all` field is a separate field, we never hid that. But I totally see that users have different expectations on this matter.

**Comment by jimczi** [comment]
Just to be clear this issue is not about highlighting the `_all` field. It's about highlighting a field with a query that contains reference to `_all`.

For instance the following query (using `query_string`):
````
text:foo category:other bar
````

would only highlight "foo" if `require_field_match` is set to true for the "text" field. The word "bar" would not be highlighted since it "targets" the `_all` field. Since the _all field contains a copy of the text field we might want to include this word to the highlighting of `text` even when `require_field_match` is true ?

**Comment by javanna** [comment]
Ok, thanks for clarifying that. This sounds better than I initially thought, it's not about highlighting `_all` but rather searching on `_all` and highlighting other fields, that will never have a match as the field with a match was `_all`. This is the perfect usecase for `require_field_match` set to `false`, but when set to `false` `foo` would also be highlighted in the `category` field and `other` in the `text` field. We would like to relax `require_field_match` only for the `bar` term, which is searched against the `_all` field and highlighted against other fields, but `require_field_match` can only be set globally.

**Comment by Bargs** [comment]
Nailed it @javanna. If a Kibana user has an index pattern that matches some indices with `_all` enabled and some with it disabled, they might get results where highlighting appears to be broken:

![screen shot 2016-11-16 at 3 01 17 pm](https://cloud.githubusercontent.com/assets/6239176/20363590/cad55bbc-ac0d-11e6-8e78-616fb96ef815.png)

The first red rectangle comes from an index with `_all` disabled (hence using the new all query), the second red rectangle from an index with `_all` enabled.

Even if all the indices have `_all` enabled, the highlighting would be much improved if we could relax `require_field_match` just on the `_all` field. It's a long time request from Kibana users.

**Comment by clintongormley** [comment]
How about we solve it like this:  use a `highlight_query` that uses `all_fields` mode and `require_field_match: true` - that way we get consistent and correct highlighting, no?

Given that (a) we've never had good highlighting on the _all field and (b) we're moving towards removing it, I'd much rather not spend any time on adding workarounds.

**Comment by jimczi** [comment]
>  that way we get consistent and correct highlighting, no?

yes and yes. The `all_fields` is perfect for the highlighter, query terms are correctly analyzed for each highlighted field.

**Comment by clintongormley** [comment]
OK - so no changes required on our side.  Kibana can use this solution instead: https://github.com/elastic/elasticsearch/issues/22017#issuecomment-266987021
