### ISSUE TITLE
Remove Shadow Replicas

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#22024]
The [shadow replicas](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/indices-shadow-replicas.html) feature (added in #8976) has not seen the amount of usage we originally hoped for. On the flip side it is very tricky to maintain, effectively adding a second replication logic. Example issues include #22021 , #17695, #16358 , #13583 , #16357 - see [here](https://github.com/elastic/elasticsearch/issues?utf8=%E2%9C%93&q=%20label%3A%22%3AShadow%20Replicas%22%20) for more. It is also requires new features (like sequence numbers) to be implemented for both normal replicas and shadow replicas, increasing the amount of future work.

Given the lack of uptake we are considering to remove them (and will mark them as deprecated in a separate PR).  

This is issue is opened as a placeholder for discussion and to give people the option to object and state their use case.

**Comment by makeyang** [comment]
segment-based or segments-based replication is really helpful for certain scenario.let's say to provide something like read-write isloate which is common in database.
but this feature shouldn't bound to shared filesystem.

**Comment by bleskes** [comment]
@makeyang yes. Segment based replication represent different trade offs and is interesting in some aspects. As you say - it is not bound to a shared file system. We talking (for a long time) about the cons and pros of it and how to potentially implement it without relying on a shared file system to do the heavy lifting of transferring files between nodes (note that we currently rely on the translog to be copied as well, something segment based replication doesn't imply). If and when we implement it, it should work on normal file systems. Since that's the hardest part to address, I don't feel there is value in keeping shadow replicas to expedite segment based replication (if this is what you meant).

**Comment by makeyang** [comment]
@bleskes  got it. thanks. if translog based or segment based asynchronous replication is implemente, it is really no reaso to keep shadow replicas.

**Comment by chenryn** [comment]
Is this meaning asynchronous replica will be published when shadow replica is totally removed?

**Comment by jasontedor** [comment]
> Is this meaning asynchronous replica will be published when shadow replica is totally removed?

It does not mean that.

**Comment by apatrida** [comment]
what about read heavy scenarios where you want to scale uniformly per node without the delay of replication (segment or per transaction) or without the cost of applying them (per transaction) and maybe over a WAN (segment would work for that, since likely it is async)?

**Comment by apatrida** [comment]
Other question related to the future of replacing this, because not sure where thinking is represented (other github issue) for future replication models.

WAN replication => the clusters are not one cluster, but two distinct and may have different shard balances.  Poor man's version of this now is `near-cluster=>S3 backup/snapshot=>S3 restore snapshot=>remote-cluster`

**Comment by bleskes** [comment]
> what about read heavy scenarios where you want to scale uniformly per node without the delay of replication (segment or per transaction) or without the cost of applying them (per transaction)

I'm not sure what you mean? a ready heavy environment means writing is not a big deal, and most of the work of the shards is to serve reads. Shadow replicas, which still need to push the segments (with the few new documents) and do stuff like merging, won't help much there?

> maybe over a WAN
> Poor man's version of this now is near-cluster=>S3 backup/snapshot=>S3 restore snapshot=>remote-cluster

I need, snapshot and restore is the current solution. Shadow replicas are not a long term solution as the current implementation assumes a shared file system. We are working on stuff like changes API which will allow you to stream (with delay) operations to another cluster.

**Comment by jrj0823** [comment]
Have you considered running ES directly on a shared filesystem?
I notice that after shadow replica is removed, there is no feature to write data directly to shared filesystem.
I think read ability can be scaled more quickly and at low cost with a shared filesystem. 
If shared filesystem supports tiered storage like EC, we do not need to handle the migration of hot and cold data.

**Comment by DaveCTurner** [comment]
> Have you considered running ES directly on a shared filesystem?

Yes, see [this blog post](https://www.elastic.co/blog/stateless-your-new-state-of-find-with-elasticsearch) for news about developments in that direction.
