### ISSUE TITLE
RPM: systemd service file has hardcoded User and Group values

### ISSUE THREAD

**Issue by nerijusk** [elastic/elasticsearch#22044]
Systemd service file has hardcoded User and Group values. While the elasticsearch.rpm pre/post install scripts do a good job in setting the ownership of directories to a user/group specified in /etc/sysconfig/elasticsearch, they fail to correctly configure systemd service. The values for User and Group are left with the default 'elasticsearch'. This essentially renders user/group settings in aforementioned sysconfig file useless. In a controlled environments where all users are defined not locally on servers, but in central directory, the user/group name could be different due to naming standards, etc.
Please fix the pre/post installation script to set the correct User/Group values in the same way it chowns the log/data/config directories.

Seen this on the 5.0.1 version.

Thanks!

**Comment by jasontedor** [comment]
We are going to remove support for customizing the user/group. The packaging distributions will ship with elasticsearch/elasticsearch as the user/group. Users that wish to customize the packaging can use the Ansible role, or customize the archive distributions.
