### ISSUE TITLE
DateFormat Issue

### ISSUE THREAD

**Issue by mattswoops** [elastic/elasticsearch#22042]
**Elasticsearch version**:
5.0

**Description of the problem including expected versus actual behavior**:
I am setting up a date in the mapping for my index. I receive the date like this:

2016-12-07T23:39:49+01:00:Wednesday, 07 December 2016

If I use this string to represent the date:
yyyy-MM-dd'T'HH:mm:ssZZ:EEEE, dd MMMM yyyy
 I get a failure:
"Invalid format: \"2016-12-07T23:27:22+01:00:Wednesday, 07 December 2016\" is malformed at \"Wednesday, 07 December 2016\""

However if I use this format:
yyyy-MM-dd'T'HH:mm:ssZZ EEEE, dd MMMM yyyy
and I manually edit my file to be:
2016-12-07T23:39:49+01:00 Wednesday, 07 December 2016

It accepts the date fine. I have also tried 
yyyy-MM-dd'T'HH:mm:ssZZ:EEEE
2016-12-07T23:39:49+01:00:Wednesday  
FAILS

2016-12-07T23:39:49+01:00:
yyyy-MM-dd'T'HH:mm:ssZZ:
FAILS

yyyy-MM-dd'T'HH:mm:ssZZ':'EEEE, dd MMMM yyyy
2016-12-07T23:39:49+01:00:Wednesday, 07 December 2016
FAILS

**Comment by clintongormley** [comment]
That's because Joda time is interpreting the colon before Wednesday as part of the time zone (which can take seconds).  nothing for us to do here i'm afraid
