### ISSUE TITLE
Sorting by GeoDistance for GeoShape type

### ISSUE THREAD

**Issue by kaxil** [elastic/elasticsearch#22040]
I need to sort documents based on the distance from a polygon (geoshape type) to a point.

Currently I read in the documentation that:
> Geo_distance sorting assumes geo_point type

Is it somehow possible to use `_geo_distance` with `geo_shape` type ?

Thanks

**Comment by cbuescher** [comment]
Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions.

**Comment by lukas-gitl** [comment]
And this wasn't a feature request? Same question... I'll post back here if I find something for the next person :)
