### ISSUE TITLE
5.0.2 missing from repos

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#22063]
**Elasticsearch version**: 5.0.2

**Plugins installed**: []

**JVM version**: 1.8

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:
Tried to install 5.0.2 after the release of 5.1.1 and it seems to be removed from the repos.

**Steps to reproduce**:
 1. Try to install 5.0.2 from repos

**Provide logs (if relevant)**:
```
root@packer-virtualbox-iso-1461948451:~# apt-get install elasticsearch=5.0.2
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '5.0.2' for 'elasticsearch' was not found
```

The repos are correct;
```
root@packer-virtualbox-iso-1461948451:~# cat /etc/apt/sources.list.d/elasticsearch.list
deb https://artifacts.elastic.co/packages/5.x/apt stable main
```

**Comment by markwalkom** [comment]
Originally raised here - https://discuss.elastic.co/t/older-versions-not-available-in-apt-repository/68489

**Comment by jasontedor** [comment]
This duplicates a known issue.

**Comment by DavidWittman** [comment]
@jasontedor link to known issue?

**Comment by DavidWittman** [comment]
Found it: https://github.com/elastic/elasticsearch/issues/21943

**Comment by jasontedor** [comment]
Duplicates #21943
