### ISSUE TITLE
RestoreBackwardsCompatIT.testRestoreUnsupportedSnapshots failures

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#22068]
See for instance https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/940/console. The failure reproduces all the time and seems to be due to the removal of the 2.0 version constants (https://github.com/elastic/elasticsearch/pull/22004/files). I muted the test.

What should be do about that? On the one hand, I see it is nice to have a nice error message with old versions, but on the other hand we cannot keep around the code that allows to read all snapshots forever?

**Comment by ywelsch** [comment]
Relates to #22069

**Comment by clintongormley** [comment]
@ywelsch was this issue closed by https://github.com/elastic/elasticsearch/pull/22069 ?

**Comment by ywelsch** [comment]
jup
