### ISSUE TITLE
geoip ingest processor reduces indexing throughput significantly

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#22074]
Users report that they experience a significant slowdown during indexing when the geoip ingest processor is enabled (see https://discuss.elastic.co/t/ingest-geoip-plugin-performance/68381). Our own benchmarking has confirmed this behavior (we've seen slowdowns of roughly 40%).

Currently, we query the Maxmind database for every IP we encounter. When the geoip ingest processor is fed from a Web server log we can benefit significantly from caching as the same IP is logged multiple times within a short time frame.

**Comment by jpountz** [comment]
I'm curious how Logstash works around this?

**Comment by danielmitterdorfer** [comment]
They use a [LRU cache](https://www.elastic.co/guide/en/logstash/current/plugins-filters-geoip.html#plugins-filters-geoip-lru_cache_size).

**Comment by jasontedor** [comment]
Note that the ingest-user-agent plugin similarly uses the cache from core Elasticsearch.

**Comment by danielmitterdorfer** [comment]
@jasontedor Yes, I noticed this and I am about to use this cache implementation too. Thanks for the pointer anyway.
