### ISSUE TITLE
Hashicorp Vault backend for Shield

### ISSUE THREAD

**Issue by thenom** [elastic/elasticsearch#22071]
Feature request:

We handle a lot of client data and have got quite far with regards to storing no credentials anywhere on our AWS architecture for our current solution we are working on.  The problem with ES that we are currently hitting is, if we had a 30 day index that we clean up using the _delete_by_query then we cannot use watcher or any external call for this because we would have to store auth details for the call (forced to use http input in the watch as we cannot use _api calls in the simple search input).

The side affect of implementing Vault as a shield realm is we could use the OTP feature and auditing of Vault to regulate user access to the ES cluster or even Vault user\pass on Kibana.  Also we could utilize the aws-ec2 auth backend feature in Vault and give EC2 instances\lambda's ect access to ES based on the IAM policy applied to an instance.

**Comment by colings86** [comment]
Since this is an issue relating to x-pack an issue has been raised in our internal bug tracker for X-Pack. I will close this issue here as the issue does not directly relate to Elasticsearch. Thank you for reporting this feature request
