### ISSUE TITLE
improve QueryBuilders introspection

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#22089]
**Describe the feature**:

When creating an query it is desirable to also know its content (for example to avoid repetition or to enhance it). While some `QueryBuilder`s expose their properties, some do not making things pretty difficult.
Here's a couple of examples that I constantly bump into:

* `SearchSourceBuilder` & `AggregatorFactories$Build`
One can add aggregations but cannot read them. There's a public method to know their number but the getters are package private.

* `NestedQueryBuilder`
The nested field `path` is not accessible so one cannot know what's the nested path. The 'parent' information is availble in `HasParent/HasChildQueryBuilder`s.

Maybe on a separate topic, it would be great to have some type of visitor api to be able to easily walk a query and collect the needed information.
Take for example inner hits - there seems to be a method for gather them (`InnerHitBuilder#extractInnerHits`) but:
a. it only returns copies of the info so it's not possible to update/modify them
b. there's no `InnerHit.EMPTY`-type of object which means most nested/parent/child queries don't have any inner hit specified and as such not much is collected.

**Comment by jpountz** [comment]
> When creating an query it is desirable to also know its content (for example to avoid repetition or to enhance it)

I don't think it should be a design goal of query builders. See that related review comment where it is suggested that we remove the ability to retrieve terms from a `TermsQueryBuilder`: https://github.com/elastic/elasticsearch/pull/21776#discussion_r90214171. For the use-case of enhancing queries, I think a better approach would be to use a completely different abstraction that can then be converted into a `QueryBuilder`.

**Comment by costin** [comment]
> I don't think it should be a design goal of query builders. 

Whatever decision is made here, there needs to be consistency. All builders already allow partial content to their content so either all of it is accessible or none at all (including `TermsQueryBuilder`).

**Comment by jpountz** [comment]
Agreed.

**Comment by cbuescher** [comment]
cc @elastic/es-search-aggs

**Comment by polyfractal** [comment]
Chatted about this on Fixit Thursday.  Some of this has changed since the ticket was opened (e.g. `SearchSourceBuilder` now exposes aggregations as a public method).  Would be nice if the builders were consistent, but since the TransportClient going away soon and the HLRC taking over, this is probably a moot point?

@costin think it's ok to close?

**Comment by costin** [comment]
Ok by me. Thanks.
