### ISSUE TITLE
elasticsearch-plugin exit code is always 0

### ISSUE THREAD

**Issue by tberne** [elastic/elasticsearch#22085]
**Elasticsearch version**: 5.1.1

**Plugins installed**: []

**JVM version**: 1.8.0_111

**OS version**: Windows 10 x64

**Description of the problem including expected versus actual behavior**: elasticsearch-plugin.bat install someplugin does not return error to console. %ERROR_LEVEL% is always 0. By looking linux script, I assume it has the same behavior.

**Steps to reproduce**:
 1. ./elasticsearch-plugin.bat install xxx
 2. echo %ERROR_LEVEL%
 3. It returns 0. Should be something else.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
I have not verified this issue.

> By looking linux script, I assume it has the same behavior.

It does not.

```
$ ~/elasticsearch/elasticsearch-5.0.2/bin/elasticsearch-plugin install xxx > /dev/null
$ echo $?
64
```

**Comment by tberne** [comment]
It seems it has something to do with a command prompt wrapper I use.

**Comment by jasontedor** [comment]
This issue does not reproduce for me.

**Comment by jasontedor** [comment]
> It seems it has something to do with a command prompt wrapper I use.

Okay, thanks for reporting back.
