### ISSUE TITLE
Terms partitioning lacks testing

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#22102]
I pushed a fix for some `TermsTest` failures here: 20ff703e07c692c5e68e6b30a6e6413a34dd10a7
but it seems that there where no real rest tests using this feature no do we have any unittests for `IncludeExclude.java` the most of the untested code has been added in https://github.com/elastic/elasticsearch/pull/21626 

I assigned this to @markharwood since you pushed #21626 as well as @jpountz since the partition stuff was added later in #22051

**Comment by markharwood** [comment]
Thanks for raising this @s1monw and apologies for the noise. Will get on this tomorrow.

**Comment by dakrone** [comment]
Related: https://github.com/elastic/elasticsearch/issues/22091
