### ISSUE TITLE
Elasticsearch 5.1.1 not starting & no failure are printed in STDOUT

### ISSUE THREAD

**Issue by guptayuvraj** [elastic/elasticsearch#22101]
**Problem Description**
I faced an issue when upgrading my elasticsearch 2.3.3 to elasticsearch 5.1.1 by upgrading from apt repository. When elasticsearch 5.1.1 was upgraded and I tried to start it, Elasticsearch did not start but in the STDOUT it never gave a failure. Instead, in STDOUT it gave an OK message wwhich signifies that elasticsearch has started succesfully.

**Problem Issue Identification**
After debugging it, I found the issue causing it by traversing through the /var/log/elasticsearch/elasticsearch.log file. The issue was caused by using elasticsearch-head plugin which was installed in ES-2.3.3 but as it is not supported in ES-5.1.1, elasticsearch failed to start.

**Actual Behaviour**
As an end-user I think we should not get an OK message if elasticsearch fails to start and it should be mentioned in the Installation of Elasticsearch documentation (https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html).

**Note: This issue will occur for every plugins which were earlier supported prior to ES-5.0.x version.**

Steps To Reproduce:
1. Install any ES version prior to ES-5.x.x
2. Install Elasticsearch-head in previous ES version (Validate its installation as it will be listed under $ES_HOME/plugins directory)
3. Upgrade ES to ES-5.1.1
4. Add ES as a service
5. Run ES as a service. You will get following STDOUT console on command line:-

root@ubuntu:/home/yuvraj# sudo service elasticsearch start
 Starting Elasticsearch Server                                                                         [2016-12-11T12:07:50,609][WARN ][o.e.c.l.LogConfigurator  ] ignoring unsupported logging configuration file [/etc/elasticsearch/logging.yml], logging is configured via [/etc/elasticsearch/log4j2.properties]
                                                                                                  [ OK ]

Please find required details as mentioned below - 

**Elasticsearch version**: Elasticsearch-5.1.1

**Plugins installed**: elasticsearch-head

**JVM version**: Oracle java version "1.8.0_91"

**OS version**: Ubuntu 14.04

**Provide logs (if relevant)**: [elasticsearch-error-captured.txt](https://github.com/elastic/elasticsearch/files/644320/elasticsearch-error-captured.txt)

**Comment by jasontedor** [comment]
Duplicates #19297

**Comment by guptayuvraj** [comment]
@jasontedor This is a different issue as observed than the one you have mentioned to as duplicated.
In the duplicated issue, the issue exists when there is incorrect YAML syntax used.
However, in the issue mentioned above, we get no failure message if plugins are already present which are not supported by ES 5.x.x.

So if I am upgrading from ES 2.x.x to ES 5.x.x wherein in my ES 2.x.x version I am using plugins, then when running ES 5.x.x it will not start ES and no failure will be printed in the STDOUT console.

**Comment by jasontedor** [comment]
@guptayuvraj It's the same issue; the Elasticsearch JVM successfully starts and then later fails during bootstrap, but reports success to the service. This is because the service is merely looking of the JVM having successfully forked. The details of why it fails are not germane.

**Comment by ItsMrAkhil** [comment]
@guptayuvraj @jacobevans I'm facing the same issue. is there any solution for this?

**Comment by guptayuvraj** [comment]
Hi @ItsMrAkhil 

My problem occurred as I had upgraded from Elasticsearch V2-x-x to Elasticsearch V5-x-x. I  solved the issue after uninstalling all the plugins which were installed in ESV2-x-x.

**Comment by ItsMrAkhil** [comment]
@guptayuvraj How can I do the same. Will you please let me know? How to remove Elasticsearch completely.

**Comment by guptayuvraj** [comment]
@ItsMrAkhil You do not need to remove Elasticsearch completely, you can just remove the plugins installed with ES2-x-x and run Elasticsearch5-x-x, it will work perfectly.

**Comment by ItsMrAkhil** [comment]
No, I didn't install any plugins I did a fresh install of Elasticsearch@latest-verion. Buth though I'm getting the same info -> Starting -> Then stopping within a second. @guptayuvraj
