### ISSUE TITLE
why elasticsearch Default Garbage collection  is CMS not G1

### ISSUE THREAD

**Issue by yangsishu** [elastic/elasticsearch#22100]
**Elasticsearch version**:

**Plugins installed**: []

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by yangsishu** [comment]
What caused the problem if use G1

**Comment by abeyad** [comment]
Kindly use the [discussion forums ](https://discuss.elastic.co/)to ask general questions.  We reserve Github for bug reports and feature requests.  To answer your question, checkout this [blog post](https://www.elastic.co/blog/a-heap-of-trouble).
