### ISSUE TITLE
Google storage plugin not found

### ISSUE THREAD

**Issue by cortopy** [elastic/elasticsearch#22129]
**Elasticsearch version**: 2.4.1

**Description of the problem including expected versus actual behavior**:

If I run `/elasticsearch/bin/plugin install repository-gcs` no plugin is found.

The terminal outputs a not found error:

```
# /elasticsearch/bin/plugin install repository-gcs --verbose
-> Installing repository-gcs...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/repository-gcs/2.4.1/repository-gcs-2.4.1.zip ...
Failed: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/repository-gcs/2.4.1/repository-gcs-2.4.1.zip]; nested: FileNotFoundException[https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/repository-gcs/2.4.1/repository-gcs-2.4.1.zip]; 
```

I've tried to see if there's a full link in the docs, but no link is mentioned in the docs for 2.4.1. If I try with the [offline link for elasticsearch 5](https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-gcs/repository-gcs-6.0.0-alpha1.zip) no file is found either

**Steps to reproduce**:
 1. /elasticsearch/bin/plugin install repository-gcs

**Comment by jasontedor** [comment]
There is not a repository-gcs plugin for Elasticsearch 2.4.1, only starting in Elasticsearch 5.0.0 was there a plugin that provided repository support with Google Cloud Storage on the backend.

**Comment by jasontedor** [comment]
Relates #13578
