### ISSUE TITLE
action.destructive_requires_name: true is ignored

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#22121]
**Elasticsearch version**:
2.2 through current

**Steps to reproduce**:
 1.  Set `action.destructive_requires_name: true`
 2.  Do:  

```
POST /asdf/asdf/1
{
    "asdf"  : 3
}

DELETE as*
```

Error indicates acknowledgement of the feature

```
{
   "error": {
      "root_cause": [
         {
            "type": "illegal_argument_exception",
            "reason": "Wildcard expressions or all indices are not allowed"
         }
      ],
      "type": "illegal_argument_exception",
      "reason": "Wildcard expressions or all indices are not allowed"
   },
   "status": 400
}
```

But `_cat/indices` shows indices deleted.

**Comment by ywelsch** [comment]
I tried this with ES 2.3.3 and could not reproduce it.

- How did you set `action.destructive_requires_name: true`?
- Is this a single-node cluster? Any special plugins installed?
- Can you repeat the experiment with a clean ES install?

**Comment by gmoskovicz** [comment]
@PhaedrusTheGreek why we closed this issue? What was happening? 

Was this a multi-node user case and the setting (requires name) was not set in certain nodes?

**Comment by pindarvanarman** [comment]
We are experiencing exact same problem with 5.1.1.  I can provide screenshots.

**Comment by javanna** [comment]
@pindarvanarman this was fixed in 5.1.2, please upgrade, ideally to the latest version.

**Comment by rodrigongarcia** [comment]
Hi, in Docker version 5.5.0 has te same issue.

**Comment by javanna** [comment]
@rodrigongarcia this specific issue was solved, if you see the same with a more recent version, can you please open another issue and explain how we can reproduce it?

**Comment by rodrigongarcia** [comment]
Hi, in Docker version 5.5.0 has te same issue.
