### ISSUE TITLE
Cannot find broken indexes using log descriptions alone

### ISSUE THREAD

**Issue by jbflowers** [elastic/elasticsearch#22122]
**Elasticsearch version**: 5.0.0

**Plugins installed**: [none]

**JVM version**: 1.8.0_60

**OS version**: Centos 6.7

**Description of the problem including expected versus actual behavior**: 
Warning and exception log file outputs index and shard ids by name like:

[2016-12-12T11:29:46,815][WARN ][o.e.c.a.s.ShardStateAction] [TOR-DT-JFLOWERS] [logstash-2016.11.20][2] received shard failed for shard id [[logstash-2016.11.20][2]], allocation id [8JfIWSYMSqWtDeJES4UcQA], primary term [0], message [master {TOR-DT-JFLOWERS}{XC-eD65FSRaIJb8Ebkz8tg}{vuaf9o0BSvGBgd7YIleV5w}{192.168.61.73}{192.168.61.73:9300} has not removed previously failed shard. resending shard failure]

Using this message there's no easy way for me to find the affected index (logstash-2016.11.20) in my ES data, as all my indexes look like hashes:

drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 11:00 ZQpjvW4YQBu80ns-O07PgQ
drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 11:01 ZR4HLIddQae3zEPS-P9DbQ
drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 11:00 zR-xA6RfTx6zObRROk451A
drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 11:00 ZRY-BHsrR7aQ828zPdFQ2g
drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 11:01 zUqHQljrTOCNIJhPmR12Ug
drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 11:01 ZvAHVTiZRmumHZ48HJYf3A
drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 11:01 ZWaI8U-yRJiYlWArt1zCqQ
drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 11:00 zwoZKoBuS0aJ0RJG1rEm-w
drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 11:00 zw_qiGvgTCyS8qjpZvsMoA
drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 10:59 zWUAP4F-StaEEroUcnunDQ
drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 11:01 Zx04zv_0SI2DVdw0RKoYlQ
drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 11:01 ZX08JkPaTXqtJx_ZqddRDQ
drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 11:01 zXLWEvCFSMKEy-UZroboUg
drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 10:59 zXNbgyc8RbCy5bM3ZKBDKQ
drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 10:59 zyxyWKXSShiraF9KGm3cnw
drwxrwxrwx 1 vagrant vagrant 4096 Dec 12 11:02 ZzvbY_9JQ-KrV6rzD9ES_A

I tried doing some searches in my ES data folder for the hashes in the message as well ("8JfIWSYMSqWtDeJES4UcQA", "C-eD65FSRaIJb8Ebkz8tg", and "vuaf9o0BSvGBgd7YIleV5w") and couldn't find anything.

My ES instance isn't starting up, so I can't do anything like a "_cat/indices" or anything like that for more info.

**Steps to reproduce**:
 1. Make an error/exception/warning for a specific index
 2. Try to find that index by the log's description only

**Comment by dakrone** [comment]
@jbflowers can you help us understand why this message would require finding the path of disk? I guess I'm unsure what you intend to do with the data after it's found.

**Comment by jbflowers** [comment]
I'm trying to  get my ES running again?
I plan to delete the index or run Lucene's "CheckIndex -fix" on it. The point here is to fix or delete the problem index. 
Is there some other solution I'm missing here? Are you saying I should just wipe my whole cluster???

**Comment by dakrone** [comment]
> I plan to delete the index or run Lucene's "CheckIndex -fix" on it. The point here is to fix or delete the problem index.
> Is there some other solution I'm missing here?

You should try and understand why the shard was failed before deleting it, if you delete the index from disk ES is still going to complain when you start it back up since the data is still present in the persisted cluster state information. Perhaps you have more log messages about why the shard was marked as failed prior to the message being sent?

> Are you saying I should just wipe my whole cluster???

I never said or implied that.

**Comment by jbflowers** [comment]
Haha, I edited the comment _waaaaay_ before you replied. Realized I was angry and melodramatic at first :) 
Not entirely sure how you even saw it, although I bet you got angry too and copy-pasted from an email. Anyhow, sorry about that.

And yeah, there's some potentially important information before that error. Thanks for the suggestion! I'll post those later but for now I want to see the rest of my cluster come to life. Is there any way to manually close or move indices while ES is off?

**Comment by jbflowers** [comment]
This was an issue on my part, although it would have been nice to get an idea of the index in the logs! Feel free to close
