### ISSUE TITLE
using msearch with bulk API

### ISSUE THREAD

**Issue by rboorugu** [elastic/elasticsearch#22127]
i generate some  tags out of the document after its indexed for which i have been making use of msearch with percolator queries - below is sample payload

 {"body":["
{"index":"search-stack"},
{"from":0,"size":1000,"query":{"percolate":{"field":"query","document_type":"all","index":"search-stack","type":"all","id":10}},"_source":false},
{"index":"search-stack"},
{"from":0
,"size":1000,"query":{"percolate":{"field":"query","document_type":"all","index":"search-stack","type":"all","id":1}},"_source":false}"]}

i get a response back something like below

{
	"responses": [{
		"took": 35,
		"timed_out": false,
		"_shards": {
			"total": 12,
			"successful": 12,
			"failed": 0
		},
		"hits": {
			"total": 1,
			"max_score": 3.2442338,
			"hits": [{
				"_index": "search-stack",
				"_type": "all",
				"_id": "tags_motionToAlterOrAmend",
				"_score": 3.2442338
			}]
		},
		"status": 200
	}, {
		"took": 105,
		"timed_out": false,
		"_shards": {
			"total": 12,
			"successful": 12,
			"failed": 0
		},
		"hits": {
			"total": 1,
			"max_score": 2.9642727,
			"hits": [{
				"_index": "search-stack",
				"_type": "all",
				"_id": "tags_unreasonableSearchAndSeizure",
				"_score": 2.9642727
			}]
		},
		"status": 200
	}]
}

only way for me to request to result is by index for example
request 1 in payload "id":10 will have to be mapped to response hit 1 and accordingly as response doesn't include id of the document - is there any other way to map it?

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
