### ISSUE TITLE
Docs advise using deprecated ENV var ES_HEAP_SIZE / broken upgrade process

### ISSUE THREAD

**Issue by chrono** [elastic/elasticsearch#22128]
After upgrading from 2.x we ran into issues with the heap size. It reverted to some default of around ~2G.

It seems that support for this variable was removed in 5.x

Documentation: https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html This is (despite saying "current" in the url) the documentation of 2.x.

> Generally, setting the ES_HEAP_SIZE environment variable is preferred over setting explicit -Xmx and -Xms values.

There is no mention of it being deprecated.

During the upgrade process, elasticsearch printed **no warning whatsoever**. A quick investigation shows that such warning / error-ing is intended but fails to trigger:

Intends to warn: bdfa063946d4c5f3ab30918b9c628442c21be27c
Defeats the warning: 3879aa2a98a823a4fba90ea587169adeee1d0ac3 (`ES_HEAP_SIZE` no longer passed to the script that would do the warning)

**Elasticsearch version**:
Version: 5.0.1, Build: 080bb47/2016-11-11T22:08:49.812Z, JVM: 1.8.0_111

**OS version**:
Ubuntu 14.04.5 LTS

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Configure a 2.x as documented (`ES_HEAP_SIZE` is preferred)
 2. Upgrade to 5.x
 3. Fail to notice this https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_packaging.html#_jvm_options
 4. Elasticsearch starts with heap size of ~2G instead of configured heap size or any warning/error

**Comment by MaineC** [comment]
As you seem to have pinned down the exact location in the code base that is causing the issue - would you mind taking this a step further and submitting a pull request with a fix?

**Comment by clintongormley** [comment]
But what is the fix here? It's not clear to me what we could change here to make it better.

> It seems that support for this variable was removed in 5.x
>
> Documentation: https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html This is (despite saying "current" in the url) the documentation of 2.x.
>
>> Generally, setting the ES_HEAP_SIZE environment variable is preferred over setting explicit -Xmx and -Xms values.
> There is no mention of it being deprecated.

There's a disconnect between the Definitive Guide and the ES Reference, where it is indeed documented under breaking changes: https://www.elastic.co/guide/en/elasticsearch/reference/5.1/breaking_50_packaging.html#_jvm_options

We need to do something with the Def Guide to make it obvious that it refers to legacy ES still.

Other than docs, any ideas how we could improve this experience?

**Comment by MaineC** [comment]
I may have read @chrono incorrectly, but the way I understood the bug report what he would like to see is some some kind of warning message in the logs when upgrading from 2.x to 5.x and leaving no longer supported configuration messages in place, no?

**Comment by jasontedor** [comment]
We do error if `ES_HEAP_SIZE` (and other variables) is set. The trouble comes from the fact that we do not export those variables from the startup script. So, if you have set `ES_HEAP_SIZE`, and run the startup script, we do not export so you never see the error that `ES_HEAP_SIZE` is no longer supported and Elasticsearch starts with the default. We could conditionally (only if they are set) export these in 5.x only.

**Comment by chrono** [comment]
Yeah, my idea for a fix would be to pass the ENV vars to the startup script (for at least the majority of the 5.x lifecycle) so that the startup script can break if they're set.

At 6.x I'd think it would be safe to remove the export.

**Comment by jasontedor** [comment]
Closed by #22183
