### ISSUE TITLE
Is there a simple way to do autocomplete?

### ISSUE THREAD

**Issue by amihaiemil** [elastic/elasticsearch#22137]
I would like to implement suggestion/autocomplete for the user input.

E.g. if the user starts typing, let's say ``auth``, I would like to display options such as ``authorization``, ``authentication`` etc.
Of course, the option should yield results, so they should come from the index. 

I tried going with the straightforward [Suggesters](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-suggesters.html) option, but apparently that is not what I want, since it corrects the user input, not complete it (e.g. if the user types "Asmterdan", it suggests the correct version "Amsterdam", but if the user types "Ams", it says nothing.

Then, I found [Completion Suggester](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-suggesters-completion.html) which seems to do the trick - **but it's too complicated** and it seems funny to me that word correction is implemented out of the box, while a simple autocompletion requires mappings or other settings on the index.

I also found [this](https://www.elastic.co/guide/en/elasticsearch/guide/current/_index_time_search_as_you_type.html) article, but again, it seems to complicated. I assume there has too be an easier way to do it.

So what I want is a simple method for autocomplete. I would expect it to be something like this:

``GET localhost:9200/index/_autocomplete?q=textContent:ams``, where ``index`` is the name of the index and ``textContent`` is the field in which I'm searching.

Note that I'm using elasticsearch 2.3 (currently that's the latest provided by AWS)

**Comment by amihaiemil** [comment]
@jpountz Maybe you or one of your colleagues can give me a hint here? :D 

Many thanks,
Mihai

**Comment by jimczi** [comment]
@amihaiemil we reserve github for bugs and feature requests. You can ask general questions like this on the forum:
https://discuss.elastic.co/c/elasticsearch

As a side note I am not sure that:

> too complicated

is a good reason not to try. Autocompletion is not "simple" especially because it needs to be fast. Though the completion suggester documentation shows you exactly what you need to do to make it works so please just try it out ;).

**Comment by amihaiemil** [comment]
@jimczi sure, thanks for the response.

I meant ``too complicated`` because you have to prepare mappings/settings for autocomplete but on the other hand, word correction, which seems more complicated, can be done with a simple call.

So I just assumed I got it wrong, that in fact there might be such a simple way for autocomplete as well.

**Comment by amihaiemil** [comment]
@jimczi I asked the question on the forum. Maybe you can have a look when you catch some time :D
https://discuss.elastic.co/t/simple-way-to-implement-autocomplete-functionality/68979/3

Thanks,
Mihai
