### ISSUE TITLE
Windows-friendly start/stop processes

### ISSUE THREAD

**Issue by tberne** [elastic/elasticsearch#22142]
Feature request.
**Describe the feature**: Elasticsearh could provide a more Windows-friendly way of starting and stopping.
Let me explain.
The JVM parameters must be passed by setting `ES_JAVA_OPTS` environment variable with a variable per line. In *nix systems, it is trivial to be done. But in Windows, it may be done in a hacky way. For example:

    setlocal enableDelayedExpansion
    set NL=^
    
    
    :: All line breaks above are required
    set ES_JAVA_OPTS=-Xms512M!NL!-Xmx512M

Another drawback on Windows is that it can't send signals properly. Thus, by starting Elasticsearch using `elasticsearch.bat -p es.pid` and then using that pid to stop Elasticsearch doesn't work very well. When using `TaskKill` to stop Elasticsearch, it doesn't perform a clean stop process. 
I've [tried to create a simple Node.js script to manage Elasticsearch](https://github.com/nodejs/help/issues/405) (start / stop) but it doesn't work well because of Windows limitations.

I'm suggesting to change the way ES_JAVA_OPTS is defined (it could be all variables in a single line, for example) and to add another way to stop Elasticsearch. All to focus on Windows users experience.

**Comment by tberne** [comment]
Just to show an example, [here's a simplified version of how I managed to start and stop Elasticsearch on Windows](https://gist.github.com/tberne/29185659f1716cd6fa33f7e18bbeed76).

**Comment by jasontedor** [comment]
You didn't say the version, so I will only describe current state (since that's all we are likely to consider improvements to).

>I'm suggesting to change the way ES_JAVA_OPTS is defined (it could be all variables in a single line, for example)

The preferred way to set JVM options is via `jvm.options`. Why aren't you using this?

> and to add another way to stop Elasticsearch

We have a [Windows service](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/windows.html#windows-service) that allows you to start and stop Elasticsearch. Why is this not sufficient?

**Comment by tberne** [comment]
I forgot to mention. Elasticsearch version 5.1.1.
I didn't describe the complete scenario. This is for a standalone version of product we develop here in the company I work. We have a build process that embbeds the Elasticsearch in this standalone distribution.
It is easier for us to leave config files untouched and perform all required configurations via scripting.
As it is a single-zip distribution, without the need of an install process, we wouldn't like to use Elastic as service either.

**Comment by jasontedor** [comment]
We are not going to support this, sorry. We support running Elasticsearch as a stand-alone server from the distributions that we provide.

**Comment by tberne** [comment]
Please, reconsider this. It really affects not only me, but anyone who tries to manage Elasticsearch via scripting in Windows.
