### ISSUE TITLE
change the index allocation makes the loads of cluster very high

### ISSUE THREAD

**Issue by pfctgeorge** [elastic/elasticsearch#22159]
Hi

We have an elasticsearch cluster. The nodes with tag "hot" stores the data of recent 3 days, and nodes with tag "cold" stores the older data of recent 30 days.
At every night, we change the index settings of "index.routing.allocation.require.tag" to move the data in hot tag which before 3 days into "cold" nodes. But recently, we notice that this process makes our loads of "cold" nodes very high and the nodes almost down. 
Can anybody kindly told us how can we optimize this phase?

Thanks.

settings: 
```
{
  "index": {
     "routing": {
        "allocation": {
           "require": {
              "tag": "cold"
           },
        }
    }
  }
}
```

Elasticsearch Version: 2.4.0
JVM version: 1.8.0_51

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
