### ISSUE TITLE
GeoPoint returns incorrect geohash for lat 90, lon 180

### ISSUE THREAD

**Issue by Hithran** [elastic/elasticsearch#22163]
**Elasticsearch version**: 5.1.1

**JVM version**: 1.8.0_111

**Description of the problem including expected versus actual behavior**:

The .geohash method on org.elasticsearch.common.geo.GeoPoint returns geohash "000000000000" for coordinates lat 90, lon 180, Which should be "zzzzzzzzzzzz".
GeoPoint.fromGeohash("000000000000") returns lat -90, lon -180

**Comment by clintongormley** [comment]
@nknize thoughts?
