### ISSUE TITLE
Painless - Provide a Limited Set of Date Functions

### ISSUE THREAD

**Issue by gingerwizard** [elastic/elasticsearch#22162]
Discussed this with @jdconrad 

Date formatting and manipulation in Painless currently relies on using native Java methods which are probably not performant.  Example - suppose i want to show dates by day (mon-sun).  This is a reasonably common usecase.  I resort to:

new SimpleDateFormat('E').format(new Date(doc['created_on'].value))

Proposal is for a simple set of date parsing functions - to and from string.

**Comment by gingerwizard** [comment]
The expressions functions are probably a good starting point - https://www.elastic.co/guide/en/elasticsearch/reference/5.0/modules-scripting-expression.html#_date_field_api

The only one i would add is the ability to possibly return strings e.g. Mon, thus avoiding common logic in user scripts.

**Comment by gmoskovicz** [comment]
Also, it would be great to provide some examples on how to works with dates. Dates are useful and many people would need to know how to deal with this.

**Comment by jdconrad** [comment]
I think we should definitely provide an easier API to deal with here for some basic things like the example pointed out.  I think @nik9000 may have some more thoughts on this as well.

**Comment by nik9000** [comment]
Yeah! This is on my list to look at more closely soonish. I have one higher priority thing in front of it but after that this is next on my list.

**Comment by nik9000** [comment]
> Yeah! This is on my list to look at more closely soonish. I have one higher priority thing in front of it but after that this is next on my list.

OK! I think I'm getting close to ready to be able to work on this. Are we ok with making sure we exposing the same API we expose to expressions to painless?

**Comment by jdconrad** [comment]
@nik9000 Not sure on the API exactly.  Expressions is limited because it can only handle double values, so that may not be the correct set of additional methods to provide.

**Comment by eskibars** [comment]
I don't think we're in any obligation to reproduce the Expressions API, since the transition targets we've been focusing on are easing users migration from Groovy->Painless, not Expressions->Painless.  I've always found the Expressions date functions to be verbose and don't seem like the best fir for the string case, as @jdconrad points out.  I think we should focus on a few goals like being able to format a date (e.g. epoch seconds, HH:mm) as a start, calculating time elapsed (date1 - date2) as a second effort, and maybe more advanced date math (date1 +/- n seconds) sometime in the future if there's reason to believe there's demand.  I've heard the date formatting come up a few times already.

**Comment by nik9000** [comment]
Ok. I'm finally starting to have a look. The first thing I notice is that something like this should work already:
```
PUT /hockey/player/1?refresh
{"first":"johnny","last":"gaudreau","goals":[9,27,1],"assists":[17,46,0],"gp":[26,82,1], "date": "2012/01/01 00:00:00"}

GET /hockey/_mapping

POST /hockey/player/_search
{
  "script_fields": {
    "centuryOfEra": {
      "script": "doc.date.date.centuryOfEra"
    }
  }
}
```
[Here](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/painless-api-reference.html#painless-api-reference-org-joda-time-ReadableDateTime) is a list of methods you can call on that `date`. Note that there is no `dates`. If you have a multi-valued field you are currently out of luck.
