### ISSUE TITLE
Adjacency matrix aggregation

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#22169]
Sometimes we want to use aggregations to understand the details of how certain entities are connected:

* When did these IP addresses talk to each other?
* How much money was sent per day between a selection of bank accounts?

Right now we can structure this with an agg tree as follows:

* query terms [A,B,C] with `min_should_match:2`
* terms agg 1 with `include: [A,B,C]`
   * terms agg 2 with `include [A,B,C]`
       * detail aggs  eg `date_histogram` or `sum`...

This will generate leaf aggregations for all of the possible connections but _will generate too many of them._ If the number of terms is N the number of leaf buckets created in a worst-case scenario is N² when it need only be (N²-N)/2. We don't want duplicate results for both A->B and B->A buckets. Similarly, we don't want A->A buckets. This trimming can be achieved if `terms agg 2` only collects terms that are less than the parent bucket's term in `terms agg 1`. (We could use "greater than" as the filter but the choice is immaterial).

We could implement this by either:
1) Adding extra parameters to existing `terms` aggs or
2) Creating a new dedicated `adjacency` aggregation 

Option 1 feels clumsy and introduces a need for changes in the agg framework to allow a child to see the keys used by the parent bucket.
The advantage of option 2 is that clients would only need to specify the list of terms once as a parameter and it could provide a more compact results format.

Would appreciate your thoughts @colings86 and @jpountz

**Comment by markharwood** [comment]
For examples of what visualizations this agg underpins see http://www.caleydo.org/tools/upset/

**Comment by jpountz** [comment]
Agreed with doing another agg rather than adding options to terms.

Do you always need this on the same field, or sometimes on two fields as well (if one field is a source and the other field a destination)?

**Comment by markharwood** [comment]
Multi-field is possibly a requirement and I haven't thought too deeply about that other than we might want the option to liberate terms from the fields when grouping e.g. I know `from` `to` and `cc` in email docs all contain email addresses and I just want to see when various email addresses have interacted over time.

**Comment by jpountz** [comment]
I don't have any objections, se let's give it a try? One requirement I have is to make sure it has a minimal set of options, eg. no configurable sorting, only fields (not scripts), no `min_doc_count`, etc.

**Comment by markharwood** [comment]
>One requirement I have is to make sure it has a minimal set of options

++  ...although there is one extra option I'd like to see: _support for grouping_. Users sometimes need to organise requested terms into groups and examine the intersections between groups of terms. Grouping is a feature of Graph UI and users to want to examine intersections at this level of detail. Currently the UI uses `filters` aggs instead of `terms` aggs to achieve this but grouped or ungrouped, the principle is the same - we don't want N² entity intersection results when we could have (N²-N)/2.

**Comment by markharwood** [comment]
Here's a rough cut at the syntax.
I'm calling the agg `adjacency` and the unit of grouping an _entity_ . In an adjacency agg we just list a set of `entities` whose interactions we want to examine.
Each _entity_ consists of:
* A user-supplied unique key (mandatory, used in the response)
* An optional definition of what index terms (`fields` and `values`) are grouped into this entity.

If any of the entity definitions lack a `values` clause the entity key is assumed to be the indexed term (I expect most of the time the values clause will be missing).
If any of the entity definitions lack a `fields` clause they inherit the `default_fields` setting at the root of the agg.

Let's start with the simple case of entities sharing a single common field:

	{
		"aggs": {
			"intersections":{
				"adjacency":{
					"default_fields" : ["actors"],
					"entities" : {
                                               "Tom Hanks":{},
                                               "Meg Ryan":{}...
					}				
				},
				"aggs":{
					"when_appeared_together" {
						"date_histogram":{...}
					}
				}
			}
		}	
	}

This would give:

	{
		"intersections": {
			"Meg Ryan": {
				"doc_count":5,
				"intersects": {
					"Tom Hanks": {
						"doc_count":2,
						"aggs":{
							"when_appeared_together"...
						}
					}
				},
			"Tom Hanks":{
				"doc_count":30,
				"intersects":{}
			}
			
		}
	}

Note we get doc_counts for each of the actors on their own and the smallest-possible set of results to describe all of the intersections. This is a trivial example but when supplying more actors we might find that the "Tom Hanks" at the root of the response would contain `intersects` detail for the actors with a key greater-than "Tom Hanks" e.g. "Tom Hardy".  


If we have entities that come from different fields we'd need to explicitly define the `fields` parameter for each entity. In this example we consider IP addresses accessing a particular user-account

	{
		"aggs": {
			"intersections":{
				"adjacency":{
					"entities" :  
						"183.23.10.45": { 
							"fields":["ip"]
						},
						"@elasticmark":{ 
							"fields":["account_id"]
						}
					},
					"aggs":{
						"last_log_in":{
							"max":{...}
						}
					}			
				}
			}
		}	
	}
	//results
	{
		"intersections": {
			"@elasticmark": {
				"doc_count":5,
				"intersects": {
					"183.23.10.45": {
						"doc_count":2,
						"aggs":{
							"last_log_in" ...
						}
					}
				},
			"183.23.10.45":{
				"doc_count":30,
				"intersects":{}
			}
			
		}
	}


In the next scenario we have only one type of entity (bank account ID) but we find examples of this entity in both `payer` and `payee` fields. We use a common `default_fields` setting which is inherited by each entity definition so we don't care which field the key is found in:

	{
		"aggs": {
			"intersections":{
				"adjacency":{
					"default_fields" : ["payer", "payee"],
					"entities" : {
						"Mr Big":{},
						"Mule 3":{}, 
						"Dealer 2":{}
					}
				},
				"aggs":{
					"money_exchanged":{
						"sum": {...}
					}
				}
			}
		}	
	}
	//results
	{
		"intersections": {
			"Mr Big": {
				"doc_count":5,
				"intersects": {
					"Mule 3": {
						"doc_count":2,
						"aggs":{
							"money_exchanged"...
						}
					}
				},
			"Mule 3":{
				"doc_count":30,
				"intersects":{}
			}
			
		}
	}

This is a similar example except we have an IP address entity found on `srcIP` and `destIP` fields. We are just interested in the volumes of data transferred between servers:

	{
		"aggs": {
			"intersections":{
				"adjacency":{
					"default_fields" : ["destIP", "srcIP"],
					"entities" : {
								"183.23.10.45":{},
								"192.168.2.1":{},....
								}
				},
				"aggs":{
					"bytes_exchanged":{
						"sum":{...}
					}
				}
			}
		}	
	}
	//results
	{
		"intersections": {
			"183.23.10.45": {
				"doc_count":5,
				"intersects": {
					"192.168.2.1": {
						"doc_count":2,
						"aggs":{
							"bytes_exchanged"...
						}
					}
				},
			"192.168.2.1":{
				"doc_count":30,
				"intersects":{}
			}
			
		}
	}

In this example we have only two entities (`webservers` and `appservers`) but each of these are a grouping of child entities.

	{
		"aggs": {
			"intersections":{
				"adjacency":{
					"default_fields" : ["destIP", "srcIP"],
					"entities" : {
								"webservers": {
										"entities": {
											"192.168.2.1":{},
											"192.168.2.2":{}
										}
								},
								"appservers": {
										"entities": {
											"192.168.4.1":{},
											"192.168.4.2":{}
										}
								}							
							}						
					]
				},
				"aggs":{
					"bytes_exchanged" :{
						"sum":{...}
					}
				}
			}
		}	
	}
	//results
	{
		"intersections": {
			"webservers": {
				"doc_count":5,
				"intersects": {
					"appservers": {
						"doc_count":2,
						"aggs":{
							"bytes_exchanged"...
						}
					}
				},
			"appservers":{
				"doc_count":30,
				"intersects":{}
			}
			
		}
	}


In this example we use the same groups (webservers and appservers) but make the relationship directional by considering only one of the roles the entity has (source or destination). This is done by using the different field names

	// User-defined groups - directional
	{
		"aggs": {
			"intersections":{
				"adjacency":{
					"entities" : {
								"webservers_src": {
										"default_fields" : ["srcIP"],
										"entities": {"192.168.2.1":{},...}
								},
								"appservers_target": {
										"default_fields" : ["destIP"]
										"entities": {"192.168.4.2":{}...}
								}							
							}						
					]
				},
				"aggs":{
					"data_served":{
						"sum":{
							"field": "response_size"
						}
					}
				}
			}
		}	
	}
	//results
	{
		"intersections": {
			"webservers_src": {
				"doc_count":5,
				"intersects": {
					"appservers_target": {
						"doc_count":2,
						"aggs":{
							"data_served"...
						}
					}
				},
			"appservers_target":{
				"doc_count":30,
				"intersects":{}
			}
			
		}
	}

**Comment by markharwood** [comment]
There may be some different execution models here.
If there's a small number of entities but each are composed of many grouped terms (e.g. my `webservers` and `appservers` example) then we could use a `Filters` agg approach and build a Bits structure for each entity. This would be largely localised serial access (for each term, read a list of doc IDs) versus the `terms` agg approach of looking up doc values where not every lookup necessarily yields a match. Doing intersects will obviously be easier using Bits.

The disadvantage of the Bits approach is it would require more memory if the number of entities is large.

**Comment by markharwood** [comment]
If we think Bits filters are the way to go we could actually implement this just by adding a `return_intersections` boolean param to the existing `filters` agg. It could then return additional buckets for key pairs using a separator e.g. `key1|key2`

**Comment by markharwood** [comment]
I put together a PR based on the Filters/Bits approach : https://github.com/elastic/elasticsearch/pull/22239

**Comment by markharwood** [comment]
Pushed to master https://github.com/elastic/elasticsearch/commit/f01784205f4512a989ed85382d02cd645bf2f667
and 5.x https://github.com/elastic/elasticsearch/commit/190bd7dbf3df35667bd401c6e5573876f39745e1
