### ISSUE TITLE
Improve ingest-user-agent

### ISSUE THREAD

**Issue by ThaDafinser** [elastic/elasticsearch#22176]
Since the `ingest-user-agent` plugin is based on https://github.com/ua-parser/uap-core the results are quiet good, but could be better.

I created a comparison of all available user-agent-parsers (and an abstraction for them) in PHP here: http://thadafinser.github.io/UserAgentParserComparison/v5/index.html

At least some of those providers could be "easily" ported over to java, since the datasource is seperated:
- https://github.com/piwik/device-detector/tree/master/regexes
- https://github.com/browscap/browscap

Any interest in this?

**Comment by clintongormley** [comment]
@talevy what do you think? It'd be worth aligning whatever we do in ES and Logstash

**Comment by talevy** [comment]
@clintongormley I'll discuss this with the Logstash team. Test coverage here is rather minimal. Although it would be awesome to have a parser that matches more strings, it would be unfortunate if whichever source we move to results in poorer results for existing matches.

**Comment by ThaDafinser** [comment]
@talevy if the current results need to stay, it would require a kind of "chain provider" like it was written here: https://github.com/ThaDafinser/UserAgentParser#chain-provider

**Comment by talevy** [comment]
thanks, good to know.

regarding the two libraries your recommended, I believe `piwik/device-detector` is out of the question due to the LGPL license.

Most of the others (including Browsecap) look useable.

@ThaDafinser, Given your testing experience, if you had to choose one to port, which would you choose to chain first?

**Comment by ThaDafinser** [comment]
My favorites
- WhichBrowser
- PiwikDeviceDetector

Why? They both have a pretty solid data background 
- WhichBrowser with https://html5test.com/
- PiwikDeviceDetector with http://piwik.org

They both try to only give results, if they can really detect the browser. Others often return wrong positives with "cath em all" rules, so you get missleading informations.

Read more here: https://github.com/ThaDafinser/UserAgentParserComparison/issues/14

**Comment by talevy** [comment]
cool, thanks @ThaDafinser, since piwik is out of the question due to licensing (if I am not mistaken), then maybe it would be worthwhile to explore WhichBrowser

**Comment by talevy** [comment]
Closing and will discuss the possibility of using WhichBrowser with the Logstash team
