### ISSUE TITLE
[DOCS] Document more return values of Nodes Stats, Cluster State and Cluster Stats

### ISSUE THREAD

**Issue by loekvangool** [elastic/elasticsearch#22199]
We document some Stat APIs return values in full, and some not. Some of the undocumented values are pretty specific to Elasticsearch, and therefore could benefit users a lot if they were explained.

The following groups of [Nodes Stats](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-nodes-stats.html) are not documented:
- http
- breaker
- jvm
- thread_pool
- transport
- discovery

The [Cluster State API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-state.html) documentation does not list details of any of its groups:
- version
- master_node
- nodes
- routing_table
- metadata
- blocks

The [Cluster Stats API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-stats.html) documentation also does not document its return values.

**Comment by clintongormley** [comment]
@loekvangool how about sending a PR?

**Comment by jrodewig** [comment]
Docs issue triage.

Leaving this open. Created a meta issue to help track progress: #47524

**Comment by jrodewig** [comment]
I'm hesitant to full document the response parameters for the cluster state API as they're subject to change. This is noted in the [current documentation][0]:

> The response is an internal representation of the cluster state and its format may change from version to version. If possible, you should obtain any information from the cluster state using the other, more stable, cluster APIs.

However, we have now documented most of the returned responses for the node stats API and the cluster stats API. When #53475 is merged, that work should be complete.

[0]: https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-state.html
