### ISSUE TITLE
Deprecate and remove `minimum_number_should_match`

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#22198]
The `minimum_should_match` parameter already handles all formats (numbers, percentages, multi-options) and there is no need for the `minimum_number_should_match` parameter.

Let's deprecate immediately and remove in 6.0

**Comment by dhirajnair** [comment]
This would be my first issue in this community.
Appreciate if you have any comments \ advice.

I have attached the screenshot of fix. 

![screen shot 2016-12-19 at 12 40 07 pm](https://cloud.githubusercontent.com/assets/4291826/21328407/9fcf41a4-c5e8-11e6-9018-b0147aff3f04.png)

Thanks
Dhiraj

**Comment by clintongormley** [comment]
Hi @dhirajnair - the way to elicit feedback is by opening a PR.  Your screenshot looks like a partial fix, there will be more to do, including adding tests.

**Comment by dhirajnair** [comment]
Thanks for the prompt response. I will look into this and submit a PR when ready

**Comment by cbuescher** [comment]
Looks like I discovered this issue too late, while answering a forum question I also found this unnecessary parameter yesterday and removed it with https://github.com/elastic/elasticsearch/pull/22403. @dhirajnair Sorry, I hope you didn't put much work into this just yet, my bad. I will close this, the parameter and the methods in the java api have been deprecated in 5.x and removed in 6.0.
