### ISSUE TITLE
Rename processor not accepting dots in field names

### ISSUE THREAD

**Issue by Dom-nik** [elastic/elasticsearch#22193]
**Elasticsearch version**: 5.0.1

**Plugins installed**: None

**JVM version**: 1.8.0_111-b15

**OS version**: CentOS 7.2.1511

**Description of the problem including expected versus actual behavior**:
The rename processor doesn't allow me to name a field using a dot, which is necessary to nest a field using the dot_expander processor. What I try to do seems to be exactly the same as the last example in dot_expander documentation: https://www.elastic.co/guide/en/elasticsearch/reference/5.1/dot-expand-processor.html

The query in the update by query part is just an example, but it works.
What I actually try to achieve is to update a nested field using update by query API, but this seems impossible out of the box and requires this workaround. Any suggestions welcome.

**Steps to reproduce**:
```
PUT _ingest/pipeline/nest_field
{
  "description" : "Nests usergroup_group_name into usergroup.group_name",
  "processors" : [ {
      "rename" : {
        "field" : "usergroup_group_name",
        "target_field" : "usergroup.group_name"
        }
      },
      {
      "dot_expander": {
        "field": "usergroup.group_name"
        }
      }
  ]
}
```
```
POST index1/_update_by_query?pipeline=nest_field
{
  "query":
    {
      "query_string": {
        "fields": ["user.Username"], 
        "query": "b*"
        }
    }
}
```

**Error:**
```JSON
...
"cause": {
        "type": "exception",
        "reason": "java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: [group_name] is not an integer, cannot be used as an index as part of path [usergroup.group_name]",
        "caused_by": {
          "type": "illegal_argument_exception",
          "reason": "java.lang.IllegalArgumentException: [group_name] is not an integer, cannot be used as an index as part of path [usergroup.group_name]",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "[group_name] is not an integer, cannot be used as an index as part of path [usergroup.group_name]",
            "caused_by": {
              "type": "number_format_exception",
              "reason": "For input string: \"group_name\""
            }
          }
        },
        "header": {
          "processor_type": "rename"
        }
      },
      "status": 500
...
```

**Comment by clintongormley** [comment]
Hi @Dom-nik 

First, you don't need the `dot_expander`.  The `rename` does the job just fine:

```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "rename": {
          "field": "usergroup_group_name",
          "target_field": "usergroup.group_name"
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "usergroup_group_name": "foo"
      }
    }
  ]
}
```

Second, the exception says `"[group_name] is not an integer, cannot be used as an index as part of path [usergroup.group_name]"` so for some reason, it is expecting `group_name` to be an integer. perhaps you have this field mapped incorrectly?

You haven't provided enough info for us to be able to recreate this issue, but (as I demonstrate above) what you're trying to do works just fine, so I'm going to close this issue.  If you have further questions I'd suggest asking them in the forums: https://discuss.elastic.co
