### ISSUE TITLE
Unable to get parent type from mapping

### ISSUE THREAD

**Issue by tarasrng** [elastic/elasticsearch#22209]
**Elasticsearch version**: 5.x

**Plugins installed**: []

**JVM version**: 1.8.0_101

**OS version**: Windows 10

**Description of the problem including expected versus actual behavior**:
In 2.x retrieving of the parent type from mapping was easy:
`GET authors/book/_mapping/field/_parent`
Starting from 5.x the same query returns nothing - I guess because of that: 

> https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_mapping_changes.html#_literal__parent_literal_field_no_longer_indexed

It's strange, because the mapping for the type:
`GET authors/book/_mapping/`
 contains "_parent" field.

**Steps to reproduce**:
 1. Index simple parent-child mapping: 
`PUT /authors
{
  "mappings": {
    "author" :{},
    "book": {
      "_parent": {
        "type": "author" 
      }
    }
  }
}`
 2. Get the type of the parent from mapping: 
`GET authors/book/_mapping/field/_parent`
Response in 2.x:
`{
   "authors": {
      "mappings": {
         "book": {
            "_parent": {
               "full_name": "_parent",
               "mapping": {
                  "_parent": {
                     "type": "author"
                  }
               }
            }
         }
      }
   }
}`
Response in 5.x:
`{}`
 3. Get all mappings for the type:
`GET authors/book/_mapping`
Response (contains parent!): 
`{
   "authors": {
      "mappings": {
         "book": {
            "_parent": {
               "type": "author"
            },
            "_routing": {
               "required": true
            }
         }
      }
   }
}`
Isn't that strange that mapping for the type contains field "parent", but I can't get the mapping for this field directly? If this is not an issue, then how is it possible to get parent type in 5.x?

**Comment by clintongormley** [comment]
That's weird - if I create a field which is not indexed and not aggregatable, it still shows up in the field mappings API:

```
PUT t 
{
  "mappings": {
    "t": {
      "properties": {
        "one": {
          "type": "keyword",
          "index": false,
          "doc_values": false
        }
      }
    }
  }
}

GET t/_mapping/field/one
```

So I'm not sure why the `_parent` isn't being returned.  @martijnvg do you have any ideas?

**Comment by makeyang** [comment]
@martijnvg  are you working on this? if not, I'd like give it a try.

**Comment by martijnvg** [comment]
@makeyang No, I haven't had the time to look into it...

The reason the `_parent` field isn't returned is because the field name is actually `_parent#[parent-type]`. The `_parent` key is the mapping is really a just a key, not the actual field name that we use the index and mapping. So I expect `GET authors/book/_mapping/field/_parent#author` or `GET authors/book/_mapping/field/_parent*` to return the fields.

**Comment by martijnvg** [comment]
The following does return the parent fields from the field mapping api:

```
PUT /authors
{
  "mappings": {
    "author": {},
    "book": {
      "_parent": {
        "type": "author"
      }
    }
  }
}

GET authors/book/_mapping/field/_parent%23author

GET authors/book/_mapping/field/_parent*
```

Although when specifying the mapping the `_parent` name is used, there is no such field internally it is translated into `_parent#[parent-type]`. In an index there can be many _parent fields, one per parent type. Although this may look confusing, from a field level it is consistent. I think this will be clearer once the `_parent` field is replaced with the `join` field as described in #20257.

**Comment by javanna** [comment]
Given the explanation from @martijnvg above and the fact that parent child works now without requiring multiple types under the same index, I am closing this issue.
