### ISSUE TITLE
Rest client doc references non-existing 5.1.0 version for dependency

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#22211]
The dependency example in the [rest client documentation for 5.1 (current)](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_maven_repository.html) is incorrect given that 5.1.0 does not exist.  Should be 5.1.1.

![image](https://cloud.githubusercontent.com/assets/7216393/21247406/080641b2-c2e4-11e6-8159-b93d32889b98.png)

The example is getting pulled from a {version} tag, seems like we will have to rebuild the rest client doc for 5.1.1 to correct it?

**Comment by jasontedor** [comment]
Closed by ace4a5fc68f5c8e3c30b484e50ccdf0b307bd091
