### ISSUE TITLE
TransportClient in scala

### ISSUE THREAD

**Issue by ddpaimon** [elastic/elasticsearch#22214]
**Elasticsearch version**: 5.1.1

**Plugins installed**: []

**JVM version**: 1.8

**OS version**: Ubuntu 16.04

**Description of the problem including expected versus actual behavior**:
How to create transport client in scala for Elasticsearch 5.1.1.

**Comment by dadoonet** [comment]
Better chance if you ask on discuss.elastic.co or on Scala user group.

Not an issue here. Closing.
