### ISSUE TITLE
Support for kv in Ingest Node

### ISSUE THREAD

**Issue by fhopf** [elastic/elasticsearch#22222]
**Describe the feature**:

It would be very nice to have ingest node support similar to the kv filter in Logstash https://www.elastic.co/guide/en/logstash/current/plugins-filters-kv.html

It is mentioned in the original ingest node issue #14049 but implementation never seems to have happened. Are there any plans for support in the future?

**Comment by clintongormley** [comment]
@talevy any reason the kv processor was left out?

**Comment by talevy** [comment]
@clintongormley no super strong reason, due to where we were at the time it was punted to v2 status.

I can work on this and get it in for 5.2

**Comment by spinscale** [comment]
@fhopf a very poor man's kv filter in between could be done using the script processor, like done [here](https://gist.github.com/spinscale/7bba10f5fcd935653617bf653577ea20), however this requires `script.painless.regex.enabled=true` and will be much cleaner/less error prone in a real processor, that does not make use of regexes, so handle with care.  Looking forward to the real thing :-)
