### ISSUE TITLE
LogLog-β algorithm for cardinality estimation

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#22230]
**Describe the feature**:
A [new paper](https://arxiv.org/abs/1612.02284) released this month introduces a new cardinality estimation algorithm called LogLog-Beta/β:

> "The new algorithm uses only one formula and needs no additional bias
> corrections for the entire range of cardinalities, therefore, it is more
> efficient and simpler to implement. Our simulations show that the accuracy
> provided by the new algorithm is as good as or better than the accuracy
> provided by either of HyperLogLog or HyperLogLog++."

Some comments about its accuracy (graphs included) can be found in [this PR](https://github.com/antirez/redis/pull/3677).

**Comment by colings86** [comment]
Closing this issuee for now, as mentioned in https://github.com/elastic/elasticsearch/pull/22323#issuecomment-314782891 the improvements in accuracy did not appear to be significant when we tested this so we are not going to pursue this for now
