### ISSUE TITLE
multi_match phrase_prefix on _all?

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [elastic/elasticsearch#22248]
Hello,

I'm using ES 2.3.1.

```
DELETE /test_index?ignore_unavailable=true

POST /test_index/content/1
{
  "name": "lorem"
}

POST /test_index/content/_search
{
  "query": {
    "multi_match": {
      "query": "lore",
      "fields": [
        "_all"
      ],
      "type": "phrase_prefix"
    }
  }
}
```

... yields 0 results. Changing to match "lorem" or switching to searching the "name" field (instead of _all) works.

Can anyone reproduce, or provide an explanation or solution?

**Comment by jimczi** [comment]
This is a bug on 2.3, you should upgrade to the latest 2.4 (2.4.3) which has the fix:
https://github.com/elastic/elasticsearch/pull/20471
