### ISSUE TITLE
Find no. of Buckets entering an Aggregation Pipeline

### ISSUE THREAD

**Issue by singhvijayy** [elastic/elasticsearch#22247]
Let me explain with the help of an example -

Lets say we have a `laces` index:
```
    "shoeid": {
            "type": "string",
            "index": "not_analyzed"
    },

    "shoetimestamp": {
            "type": "date",
            "format": "epoch_millis",
    },

    "laceindex": {
            "type": "string",
            "index": "not_analyzed"
    },

    "lacetimestamp": {
            "type": "date",
            "format": "epoch_millis",
    },

    "info": {
            "type": "string",
            "analyzer": "whitespace"
    }
```

All `laceindex` and `lacetimestamp` are unique, but `shoeid` and `shoetimestamp` are shared. If I want to get all laces with same `shoeid` and then do a calculation with `shoetimestamp` and `no. of buckets coming out of the terms aggr on shoeid` i.e.` laces with same shoeid`, I cannot do that! 

Because when I run an aggregation, I do not have no. of buckets entering the pipeline!

Following aggregation query doesn't solve the purpose -

    "aggs": {
            "one": {
                    "terms": {
                            "field": "shoeid",
                            "size": 10000
                    },

                    "aggs": {
                            
                            // IDEALLY I WOULD LIKE TO DO -
                            // no. of buckets entering this pipeline * shoetimestamp
                            // (shoetimestamp will be same for all buckets here)

                            "count": {
                                    "value_count": {
                                            "field": "shoetimestamp"
                                    }

                                    // I have lost shoetimestamp here :(
                            }
                    }
            }
    }

**Comment by clintongormley** [comment]
Sorry @singhvijayy but I don't follow your question at all.  That said, 
please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
