### ISSUE TITLE
Wildcard in query_string query returns json_parse_exception

### ISSUE THREAD

**Issue by ruflin** [elastic/elasticsearch#22255]
* Elasticsearch versions: 
  * 5.1.1 (official docker image)
  * master

Based on https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax it should be possible to use * in the field names if it is properly escaped. The following works as expected:

```
GET /metricbeat-*/_search
{
  "query": {
    "query_string": {
      "fields": ["system.*.cores"],
      "query": "4"
    }
  }
}
```

The correct results are returned. Rewriting this with only a query as below fails:

```
GET /metricbeat-*/_search
{
  "query": {
    "query_string": {
      "query": "system.\*.cores:4"
    }
  }
}
```

This returns the following error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "json_parse_exception",
        "reason": "Unrecognized character escape '*' (code 42)\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@39e64a6c; line: 4, column: 26]"
      }
    ],
    "type": "json_parse_exception",
    "reason": "Unrecognized character escape '*' (code 42)\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@39e64a6c; line: 4, column: 26]"
  },
  "status": 500
}
```

To tests is it is best to run metricbeat with its default configuration and load data into elasticsearch.

**Comment by jimczi** [comment]
Since it's JSON you'll need to use double backslash. The first one is for JSON and the second one is for the query_string query. 

So this:
````
GET /metricbeat-*/_search
{
  "query": {
    "query_string": {
      "query": "system.\\*.cores:4"
    }
  }
}
````
... works.

**Comment by jpountz** [comment]
I opened a PR to make it explicit in the docs https://github.com/elastic/elasticsearch/pull/22257

**Comment by ruflin** [comment]
@jimczi I can confirm it works with `\\`
@jpountz Thanks for the docs fix.
