### ISSUE TITLE
Highlight query on multi-value field does not work on array of strings

### ISSUE THREAD

**Issue by aeryaguzov** [elastic/elasticsearch#22259]
**Elasticsearch version**: 2.4.2

**Steps to reproduce**:
 
```
curl -XDELETE "http://localhost:9200/wtf"

curl -XPUT "http://localhost:9200/wtf?pretty=true"

curl -XPUT "http://localhost:9200/wtf/doc/_mapping?pretty=true" -d '
{
  "doc": {
    "properties": {
      "tags": {
        "type": "string",
        "index":"analyzed"
      }
    }
  }
}
'

curl -XPUT "http://localhost:9200/wtf/doc/1?pretty=true&refresh=true" -d '
{
  "tags": [                                                             
    "foo bar",                         
    "foo bar baz"
  ]                      
}
'

curl -XGET "http://localhost:9200/wtf/doc/_search?pretty=true" -d '
{
  "query": {"match": {"tags": {"query": "foo baz", "operator": "and"}}},
  "highlight": {"fields": {"tags": {}}}
}                
'                      

```
Expected:

```
{
  "took" : 7,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.22917584,
    "hits" : [ {
      "_index" : "wtf",
      "_type" : "doc",
      "_id" : "1",
      "_score" : 0.22917584,
      "_source" : {
        "tags" : [ "foo bar", "foo bar baz" ]
      },
      "highlight" : {
        "tags" : [ "foo bar", "<em>foo</em> bar <em>baz</em>" ]
      }
    } ]
  }
}
```

Actual:

```
{
  "took" : 7,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.22917584,
    "hits" : [ {
      "_index" : "wtf",
      "_type" : "doc",
      "_id" : "1",
      "_score" : 0.22917584,
      "_source" : {
        "tags" : [ "foo bar", "foo bar baz" ]
      },
      "highlight" : {
        "tags" : [ "<em>foo</em> bar", "<em>foo</em> bar <em>baz</em>" ]
      }
    } ]
  }
}
```

In docs we have array type definition (https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html) in which we have a note about array of objects(array values are flattened). As I understand, array of strings (not objects) works in the same way. It is ok for search (when matching is done), but, as you see, it is not ok with highlights (we highlight invalid item(first "foo" must not be highlighted)).

If it is a bug, we need to fix it for highlight, if it is a "feature", we should warn people that highlights won't work as expected. What do you think ?

**Comment by clintongormley** [comment]
@aeryaguzov As you correctly point out, arrays of strings are flattened, so your field looks like:

    foo, bar,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,foo, bar, baz

Your query looks for any occurrence of foo and baz and it finds foo twice.

If you want your arrays to be treated as separate values then you need to put them inside a `nested` field.

**Comment by clintongormley** [comment]
... or use positional queries like `match_phrase` with `slop`
