### ISSUE TITLE
Elastic search is not starting. No errors. Only warning: cannot be run as root.

### ISSUE THREAD

**Issue by tkgauri** [elastic/elasticsearch#22251]
**Elasticsearch version**: 5.1.1

**Plugins installed**: []

**JVM version**: java version "1.8.0_101"

**OS version**: CentOS release 6.8 (Final)

**Description of the problem including expected versus actual behavior**:
Elastic search is not starting. It gives me warning "org.elasticsearch.bootstrap.StartupException: java.lang.RuntimeException: can not run elasticsearch as root". But when I run without root, it gives me long list of errors; some of them are "java.io.FileNotFoundException: permission denied."
**Steps to reproduce**:
 1. sudo ./elasticsearch

I have lowered the memory limits from config/jvm.options to 512mb. But doesn't work.
-Xms100m
-Xmx200m

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by dadoonet** [comment]
We can help on discuss.elastic.co.
Please ask your questions there.

Here it's not an issue. Please also read https://www.elastic.co/guide/en/elasticsearch/reference/current/setup.html
