### ISSUE TITLE
Add Ability to Create Index Based on Alias Name For Index Templates

### ISSUE THREAD

**Issue by eladmena** [elastic/elasticsearch#22260]
Index templates allow specifying that alias(es) will be created once a index is dynamically created.
When adding a new document the index matching the name will be created.

As I'd prefer consumer to use the alias rather than the index, it means that the when using templates the initial document PUT should be with the index name and only then use the alias name, which beats the purpose of index templates as I need different behaviour for the first put.

for example for this template
{
  "template": "**XXX_***",
  "mappings": {
    "type01": {
      "properties": {
        "field01": {"type": "text"}
      }
    }
  },
  "aliases": {
	"{index}_alias" : {}
  }
}

put for XXX_A_alias will create:

- index named XXX_A_alias

- alias named XXX_A_alias_alias
while the intention was to create index named XXX_A and alias named XXX_A_alias

It would be best to add **preferAliasAsSourceName** property to infer index name from the alias, in case the matched name also matches the alias.
ie: 
{
  "template": "**XXX_***",
  "mappings": {
    "type01": {
      "properties": {
        "field01": {"type": "text"}
      }
    }
  },
  **"preferAliasAsSourceName": true,**
  "aliases": {
	"{index}_alias" : {}
  }
}

XXX_A_alias matches the alias name, and {index} = XXX_A as such the index name will be XXX_A

**Comment by clintongormley** [comment]
@eladmena aliases don't exist until they are added to an index.  If you want your users to consume the alias instead of the index, then you need to create the index first and add an alias.  Later you can change the alias behind the scenes.  This is exactly what we are proposing in https://www.elastic.co/blog/managing-time-based-indices-efficiently

**Comment by eladmena** [comment]
@clintongormley I wasn't suggesting to first create the alias then the index.
Just to add the ability to infer the index name from the alias and not the other way around.

Otherwise the templates feature is useless when aliases are involved as if I want consumers to create documents using the alias the first document should be added with the index, and if I already have different behaviour for the first document put, I can create the index myself.
