### ISSUE TITLE
Is logstash is the best tool to send logs to Elasticsearch

### ISSUE THREAD

**Issue by rajasekaran07** [elastic/elasticsearch#22261]
Hi Team,

It is a kind question. I am just curious to know why logstash is the best tool to send logs to elasticsearch. We are running our all applications in AWS so, we are planning to use AWS Cloudwarch logs to collect and send application logs to elasticsearch. please give some suggestion for best practices.

Regards,
Raja

**Comment by jasontedor** [comment]
Elastic reserves GitHub for bug reports and feature requests but provides a [forum](https://discuss.elastic.co) for general questions.
