### ISSUE TITLE
5.1.1 DateHistogram Agg with timezone returns wrong tick count

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch#22269]
Please correct me if I'm wrong but If I have a date and it's always stored as UTC and I specify a timezone of +1h the tick count should be equal to `2016-12-17T01:00:00.000`. I'm seeing it be `2016-12-16T23:00:00.000`. When I do `-01:00` it returns the inverse (Should this be switched around or am I just thinking about this wrong.. dates are tuff..)

Code to reproduce:
```json
PUT /employees
{
  "mappings": {
    "employee": {
      "properties": {
        "id": {
          "type": "keyword"
        },
        "nextReview": {
          "type": "date"
        }
      }
    }
  }
}

POST /employees/employee/58583211e3641c29a4a8a563
{
  "id": "58583211e3641c29a4a8a563",
  "nextReview": "2016-12-17T19:16:33.578+00:00"
}


POST /employees/employee/_search
{
  "size": 0,
  "aggs": {
    "date_nextReview": {
      "date_histogram": {
        "field": "nextReview",
        "interval": "1d",
        "format": "date_optional_time",
        "time_zone": "+01:00"
      }
    }
  }
}
```

Returns
```json
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "date_nextReview": {
      "buckets": [
        {
          "key_as_string": "2016-12-17T00:00:00.000+01:00",
          "key": 1481929200000,
          "doc_count": 1
        }
      ]
    }
  }
}
```
On http://www.epochconverter.com/ `1481929200000` returns:

```
Assuming that this timestamp is in milliseconds:
GMT: Fri, 16 Dec 2016 23:00:00 GMT
Your time zone: 12/16/2016, 5:00:00 PM GMT-6:00
```

**Comment by niemyjski** [comment]
I found this behavior in my unit tests as I'm asserting it's going to be +1 hour a head. ![screen shot 2016-12-19 at 12 34 12 pm](https://cloud.githubusercontent.com/assets/1020579/21326379/01fb7166-c5f0-11e6-84c8-dd39c735394c.png)

**Comment by clintongormley** [comment]
It's correct.  Think about it like this:

* When it is midnight at UTC+1, then it is 11pm at UTC
* The `key_as_string` is returned in UTC+1 (and represents midnight in UTC+1) 
* The `key` is in millis-since-the-epoch which is in UTC (and so represents 11pm UTC)

**Comment by clintongormley** [comment]
And yes, time zones are hard :)

**Comment by niemyjski** [comment]
Gotcha that makes more sense :).
