### ISSUE TITLE
Warn when implicit long to double promotions may be surprising

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#22265]
When discussing #22232 it was noted that the implicit long to double promotions may not only be an issue with the terms aggregation, but also for instance if running an `histogram` aggregation on a `long` field with a fractional interval: only buckets that contain integer values will not be empty. This might surprising from UIs like Kibana where users do not necessarily know about the mappings beyond the fact that a given field is a number. We could look into returning warnings in http headers in such cases.

**Comment by s1monw** [comment]
+1 to return warning headers here. We discussed it in fixit friday

**Comment by markharwood** [comment]
cc @elastic/es-search-aggs

**Comment by wchaparro** [comment]
Closing as not planned.
