### ISSUE TITLE
[feature request]provide options to disable trans log

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#22276]
**Describe the feature**:
1. in some case, users can afford lose some data to trade write performance, so better to provide this options like hbase did.

**Comment by clintongormley** [comment]
We already have async translog flushing, which allows the user to control how much data they are willing to lose.  The translog is central to our shard resiliency and we're not going to add a code path which allows it to be disabled.

**Comment by jasontedor** [comment]
To add, the translog will take on a bigger role with features like sequence IDs.
