### ISSUE TITLE
Why completion suggester show keywords list uncompleted

### ISSUE THREAD

**Issue by CCMBChina** [elastic/elasticsearch#22275]
**Elasticsearch version**:
2.2
**Plugins installed**: []
head
**JVM version**:
1.7
**OS version**:
linux 2.6
**Description of the problem including expected versus actual behavior**:

related question：https://discuss.elastic.co/t/completion-suggester-strange-behavior-after-index-optimization/54240/1

when using completion suggester in production,i find a problem that when i input a character ‘o’, by which completion suggester should show 10 keywords that starts with prefix 'o',but unexpectedly, only 5 words in the list.i do not know why.
in production,i use this tempalte,and i use 10 indices to suggest,like curl -XPOST localhost:9200/suggest-a,suggest-b,suggest-c,suggest-d,suggest-e,suggest-f,suggest-g,suggest-h,suggest-i,suggest-j/_suggest,every indice exists 10000 datas,and the size is 20:
curl -XPUT localhost:9200/_template/template_suggest -d '{
    "template" : "suggest-*",
    "settings": {
       "number_of_shards" : 3
    },
    "mappings" : {
      "suggest" : {
        "properties" : {
          "word" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "suggest" : { 
            "type" : "completion",
            "analyzer" : "standard",
            "search_analyzer" : "standard",
            "preserve_separators" : false,
            "max_input_length" : 100,
            "payloads" : true
          }
        }
      }
    }
}'
is it cache or 3 shards that lead to this problem?
It is strange that when i reindex this suggest index ,it may show 6 keywords or 7 keywords,but still uncompleted.
i use java api ,and what is the meaning of shardSize in CompletionSuggestionBuilder

**Comment by clintongormley** [comment]
Hi @CCMBChina 

First, I'm unable to replicate your problem without actual data - need a full recreation in curl.  Second, the completion suggested in 2.x has been completely rewritten in 5.0 and won't be receiving any bug fixes, so I would suggest trying it out in 5.0 before reopening this ticket.
