### ISSUE TITLE
Plugin install fails if another plugin in incompatible version is still installed

### ISSUE THREAD

**Issue by jakommo** [elastic/elasticsearch#22286]
**Elasticsearch version**: 2.4.1 upgrade to 2.4.3

**Plugins installed**: [license, marvel-agent, cloud-aws]

**JVM version**: Java 8 u111

**OS version**: Ubuntu 14.04 

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Install ES 2.4.1, install at least two plugins
 2. Upgrade ES to e.g. 2.4.3
 3. Remove the first plugin and install it again (while the other plugin(s) are still on the old version)

```
root@plugin-20161220-214522trusty-64-jre-1:/usr/share/elasticsearch#/usr/share/elasticsearch# bin/plugin remove cloud-aws
-> Removing cloud-aws...
Removed cloud-aws
root@plugin-20161220-214522trusty-64-jre-1:/usr/share/elasticsearch# bin/plugin install cloud-aws
-> Installing cloud-aws...
Trying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/cloud-aws/2.4.3/cloud-aws-2.4.3.zip ...
Downloading ................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://download.elastic.co/elasticsearch/release/org/elasticsearch/plugin/cloud-aws/2.4.3/cloud-aws-2.4.3.zip checksums if available ...
Downloading .DONE
ERROR: Plugin [marvel-agent] is incompatible with Elasticsearch [2.4.3]. Was designed for version [2.4.1]
root@plugin-20161220-214522trusty-64-jre-1:/usr/share/elasticsearch# bin/plugin list
Installed plugins in /usr/share/elasticsearch/plugins:
    - marvel-agent
    - license
root@plugin-20161220-214522trusty-64-jre-1:/usr/share/elasticsearch#
```

**Describe the feature**:
The installation of `cloud-aws` fails because `marvel-agent` is still installed in an old version.
We should not fail to install a plugin, if another one is not up to date.

**Comment by jasontedor** [comment]
Duplicates #22084

**Comment by jakommo** [comment]
@jasontedor not sure this is a dup. https://github.com/elastic/elasticsearch/issues/22084 is about failing when the old version of the _same_ plugin is still installed, while this is about failing the plugin install if _any other_ plugin is still installed in an old version.

**Comment by jasontedor** [comment]
It's a duplicate. It's happening for the same reason. We do a verify post-install and the verify fails because of the outdated plugin. Also, we've discussed this before and decided to leave as-is (I can't find the previous discussion).

**Comment by rjernst** [comment]
One instance of a discussion around it, albeit brief, was in #15197.

**Comment by jakommo** [comment]
thanks for the clarification @jasontedor @rjernst
