### ISSUE TITLE
Update the foreach processor documentation to include an example using the ingest attachment processor

### ISSUE THREAD

**Issue by gameldar** [elastic/elasticsearch#22294]
As part of trying to solve an issue with using the ingest attachment processor to handle an array of attachments I found the solution to doing so based upon a discourse thread, and digging through the source of the ingest attachment processor.

However this solution isn't in the documentation, so it needs adding.

This was initiated from the following discourse thread:
https://discuss.elastic.co/t/can-the-ingest-attachment-processor-plugin-extract-array-data/67199

**Comment by dadoonet** [comment]
This has been fixed by #22310. Closing.
