### ISSUE TITLE
Update by query API

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#2230]
The update by query API allows all documents that with the query to be updated with a script.  This feature is experimental.
The update by query works a bit different than the delete by query. The update by query api translates the documents that match into bulk index / delete requests. After the bulk limit has been reached, the bulk requests created thus far will be executed. After the bulk requests have been executed the next batch of requests will be prepared and executed. This behavior continues until all documents that matched the query have been processed. The bulk size can be configured with the *action.updatebyquery.bulk_size* option in the elasticsearch configuration. For example:
`action.updatebyquery.bulk_size=2500`

# Example usage
Index an example document:
curl -XPUT 'localhost:9200/twitter/tweet/1' -d '
```
{
   "text" : {
      "message" : "you know for search"
    }
}
```

Execute the following update by query command:
curl -XPOST 'localhost:9200/twitter/_update_by_query' -d '
```
{
    "query" : {
        "term" : {
            "message" : "you"
        }
    },
    "script" : "ctx._source.field1 += 1"
}
```
This will yield the following response:
```
{
  "ok" : true,
  "took" : 9,
  "total" : 1,
  "updated" : 1,
  "indices" : [ {
    "twitter" : { }
  } ]
}
```
By default no bulk item responses are included in the response. If there are bulk item responses included in the response, the bulk response items are grouped by index and shard. This can be controlled by the `response` option.

# Options:

Additional general options in request body:
* `lang`:  The script language.
* `params`: The script parameters.

## Query string options:
* `replication`:  The replication type for the delete/index operation (sync or async).
* `consistency`: The write consistency of the index/delete operation.
* `response`:  What bulk response items to include into the update by query response. This can be set to the following: `none`, `failed` and `all`. Defaults to none. Warning: `all` can result in out of memory errors when the query results in many hits.
* `routing` : Sets the routing that will be used to route the document to the relevant shard.
* `timeout` : Timeout waiting for a shard to become available.

This is issue originates from #1607

**Comment by leibale** [comment]
+1

**Comment by mrdanadams** [comment]
+1

**Comment by niemyjski** [comment]
+1

**Comment by ejsmith** [comment]
+1

**Comment by pemontto** [comment]
:+1:

**Comment by raf64flo** [comment]
That feature would be gorgeous! +1

**Comment by crusy** [comment]
+1

**Comment by lukens** [comment]
+1

**Comment by tostasqb** [comment]
+1

**Comment by dapi** [comment]
+1

**Comment by niemyjski** [comment]
+1

On 3/3/15, Danil Pismenny <notifications@github.com> wrote:
> +1
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/elasticsearch/elasticsearch/issues/2230#issuecomment-76946870


-- 
Thanks
-Blake Niemyjski

**Comment by engineee** [comment]
+1

**Comment by fjarrett** [comment]
+1

**Comment by wumingwuan** [comment]
+1

**Comment by bogdanovich** [comment]
+1

**Comment by mahadoang** [comment]
PUT authors/book/1
{
  "name": "Revelation Space1",
  "genre": "scifi1",
  "publisher": "penguin1",
  "author":[
    {"author_id":1001,"author_name":"mahadoang"},
    {"author_id":1002,"author_name":"bugping"}
  ]
}

PUT authors/book/2
{
  "name": "Revelation Space2",
  "genre": "scifi2",
  "publisher": "penguin2",
  "author":[
    {"author_id":1001,"author_name":"mahadoang"},
    {"author_id":1003,"author_name":"bugping3"}
  ]
}

PUT authors/book/3
{
  "name": "Revelation Space3",
  "genre": "scifi3",
  "publisher": "penguin3",
  "author":[
    {"author_id":1001,"author_name":"mahadoang"}
  ]
}

GET authors/book/_search
{
  "query": {
    "query_string": {
      "default_field": "author.author_id",
      "query": 1001
    }
  }
}


i want update  author.author_name form "mahadoang" to "somechai" where author.author_id = 1001

///////////////////// update ////////////////
POST authors/_update_by_query
{
  "query": {
    "query_string": {
      "default_field": "author.author_id",
      "query": 1001
    }
  },
  "script" : "ctx._source.author.author_name = author_name",
   "params" : {
      "author_name" : "somechai"
   }
}

not update  help me.
Thank you.

**Comment by ofavre** [comment]
I guess you did not enable dynamic scripting.
But you truly should ask this on yakaz/elasticsearch-action-updatebyquery directly.
You'll see how to enable it in the readme.

**Comment by mahadoang** [comment]
Thank you very much.
Update success.

**Comment by aelingold** [comment]
+1

**Comment by pjcardy** [comment]
+1

**Comment by sigpwned** [comment]
+1

**Comment by stropo** [comment]
:+1:

**Comment by bvnagaraju** [comment]
can some one tell me if this update only through scripting ?

**Comment by bvnagaraju** [comment]
Is there  a way we know when this will be ready

**Comment by xelllee** [comment]
+1

**Comment by IUnknownPtr** [comment]
+1

**Comment by abhas9** [comment]
+1

**Comment by rtrujill007** [comment]
+1

**Comment by chibenwa** [comment]
+1

**Comment by knoxxs** [comment]
+1

**Comment by ogorun** [comment]
+1

**Comment by clintongormley** [comment]
Update by query should be implemented as part of the reindex API #492

**Comment by davidchipping** [comment]
+1

**Comment by xpepermint** [comment]
+1

**Comment by sDaniel** [comment]
Please stop to +vote spamming and let github know we need a voting feature.
https://github.com/isaacs/github/issues/9

**Comment by KurtPreston** [comment]
+1

**Comment by kpashka** [comment]
+1

**Comment by nik9000** [comment]
_update_by_query has landed in master: https://github.com/elastic/elasticsearch/commit/c7c8bb357a1ef459a7c59db4da9cbda1c0d439db

I'm not going close this until it's backported to 2.3 though.

**Comment by lukens** [comment]
great work @nik9000!

**Comment by eskibars** [comment]
Closing, as the _update_by_query @nik9000 mentioned has been backported to 2.3.  For those finding this later, see documentation at https://www.elastic.co/guide/en/elasticsearch/reference/2.x/docs-update-by-query.html

**Comment by DaveVdE** [comment]
Has the `response` query parameter been integrated with this feature too? I can't seem to get it to work.

**Comment by nik9000** [comment]
No. This wasn't a port of the original, it was its own thing. The bulk
responses are only available for failures that abort the action. We talked
a lot about including more responses but decided that it wasn't worth it
given that they could consume too much memory.
