### ISSUE TITLE
Add support of window functions from SQL

### ISSUE THREAD

**Issue by Koc** [elastic/elasticsearch#22307]
Please add support of window functions for sorting like

product_id | company_id | is_special_odder
-------------|-----------|----
1 | 1 | 0
2 | 1 | 1
3 | 2 | 0
4 | 2 | 1
5 | 2 | 1
6 | 3 | 0
7 | 3 | 0

```sql
SELECT  product_id, company_id
FROM    product
ORDER BY ROW_NUMBER() OVER (PARTITION BY company_id ORDER BY is_special_offer DESC)
```

Result 

product_id | company_id | is_special_odder
-------------|-----------|----
2 | 1 | 1
4 | 2 | 1
6 | 3 | 0
1 | 1 | 0
5 | 2 | 1
7 | 3 | 0
3 | 2 | 0

http://stackoverflow.com/questions/7207867/alternate-results-with-order-by-clause

**Comment by s1monw** [comment]
I have to admit I am not fully sure how this exactly works what you are asking for but would something like [inner hits](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html) help here?

**Comment by Koc** [comment]
Inner hits looks similar but not sure if it return same as window function.

```sql
SELECT  product_id, company_id
FROM    product
ORDER BY ROW_NUMBER() OVER (PARTITION BY company_id ORDER BY is_special_offer DESC)
```

works using next algorythm:

1. pre-order all result by is_special_offer DESC
2. associate each row from preordered result with row number. For each company_id creates own counter which starts from 0
3. order by this computed counters

It works ok with big results (no any limits for rows count per company) and allows paginate result.

**Comment by Koc** [comment]
I don't need top N results per company. **All** results is needed (don't know how many products can be created per company)

**Comment by rjernst** [comment]
I believe windowing is relatively expensive to compute, and would be difficult to do given Lucene's current scoring architecture. It would mean reading values from multiple docs in order to score a single doc.

**Comment by s1monw** [comment]
> I believe windowing is relatively expensive to compute, and would be difficult to do given Lucene's current scoring architecture. It would mean reading values from multiple docs in order to score a single doc.

I agree this seems to violate very basic assumptions we make.

> I don't need top N results per company. All results is needed (don't know how many products can be created per company)

I understand but ES / Lucene is designed for top N and if you wanna do very different things it's likely that we won't be able to help you.

**Comment by clintongormley** [comment]
I think the conclusion here is clear. Closing

**Comment by bragboy** [comment]
A workaround (although not optimal) - https://blog.francium.tech/sql-window-function-partition-by-in-elasticsearch-c2e3941495b6
