### ISSUE TITLE
Missing Keyed Response for Percentiles Bucket

### ISSUE THREAD

**Issue by gingerwizard** [elastic/elasticsearch#22302]
**Elasticsearch version**:
5.1

I would expect the Percentiles Bucket pipeline aggregation to support a keyed response, similar to the main percentiles agg. Attempting to do this throws the error below, indicating its not currently supported.

```
{
  "error": {
    "root_cause": [
      {
        "type": "parsing_exception",
        "reason": "Unexpected token VALUE_BOOLEAN [keyed] in [lower_bound]",
        "line": 32,
        "col": 17
      }
    ],
    "type": "parsing_exception",
    "reason": "Unexpected token VALUE_BOOLEAN [keyed] in [lower_bound]",
    "line": 32,
    "col": 17
  },
  "status": 400
}
```
This introduces a few challenges - primarily the fields produced contains dots with are not accessible in templates.

**Comment by polyfractal** [comment]
@elastic/es-search-aggs

**Comment by gauravmishra123** [comment]
Hi I am a newbie , Can I take this issue if not taken ? 
Any pointers would be appreciated.

**Comment by mayya-sharipova** [comment]
@gauravmishra123 This issue is not taken, so please work on this if you like.
You can start with working `PercentilesBucketPipelineAggregationBuilder.java` file to make a parser accept `keyed` field. See how the parser in `PercentilesAggregationBuilder` accepts `keyed` field

**Comment by gauravmishra123** [comment]
Thanks a ton @mayya-sharipova  for the help.
I have started working on this.

**Comment by gauravmishra123** [comment]
Hi

I will be committing the fix this week only

**Comment by jucaleb4** [comment]
@gauravmishra123 good job! Thanks for letting me know

**Comment by not-napoleon** [comment]
Hi @gauravmishra123 , I was thinking about picking up this issue since it seems you haven't had a chance to get to it.  If you're still working it, please let me know.  Thanks!

**Comment by not-napoleon** [comment]
@gauravmishra123 sounds good.  If you get stuck or have a question, feel free to leave a note here and I'll do my best to help.

**Comment by joaofcmb** [comment]
Hi @gauravmishra123 , I would like to pick up this issue. Are you still working on it?

**Comment by gauravmishra123** [comment]
No @joaofcmb  , I had started to work on this but has got some situtation at my home ,so couldn't get time .You can proceed on this.
