### ISSUE TITLE
Es can not load the plugin at run time

### ISSUE THREAD

**Issue by sakuradavid** [elastic/elasticsearch#22319]
ES 2.3.0 server .
I would like to load the plugin at run time, but failed, I can not get from guice node instance, guice no spring similar application context, ask, can achieve a similar solr load plugins at run time ?

**Comment by jasontedor** [comment]
No, this is not possible. Plugins must be initialized during startup.

**Comment by jasontedor** [comment]
In the future, please ask questions on the [forum](https://discuss.elastic.co); Elastic reserves GitHub for verified bug reports and feature requests.

**Comment by sakuradavid** [comment]
Got it.Thianks

**Comment by sakuradavid** [comment]
Got it.Thanks.
