### ISSUE TITLE
Clarify use of date math in index names with custom date formats

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#22322]
**Elasticsearch version**: 5.1

You can run this curl command to see that date math calculation with custom formats including more than year, month and day is crippled/bogus.

```
curl -g -v 'localhost:9200/<logstash-{now%2fd{YYYY.MM.dd.hh.mm.ss}}>'

{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"logstash-2016.12.22.12.00.00","index_uuid":"_na_","index":"logstash-2016.12.22.12.00.00"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"logstash-2016.12.22.12.00.00","index_uuid":"_na_","index":"logstash-2016.12.22.12.00.00"},"status":404}
```

The index name `logstash-2016.12.22.12.00.00` does not seem to take minutes and seconds into account and the hour seems to be wrong as well.

The docs dont mention anything, that these formats are not supported - and I am not too sure they should (especially seconds), but this is unexpected behaviour so we should either fix it or document it.

**Comment by clintongormley** [comment]
I think we should just document it

**Comment by mayur-persistent** [comment]
@spinscale @clintongormley I want to take up this issue as a first contribution. Let me know what I need to do?

**Comment by clintongormley** [comment]
@mayur-persistent Thanks for showing interest in contributing to Elasticsearch.

Here's a guide to how to go about it: https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md

**Comment by mayur-persistent** [comment]
@clintongormley I have identified the file where I need to make those changes. https://github.com/elastic/elasticsearch/edit/5.1/docs/reference/api-conventions.asciidoc

Would you prefer that we show the message just below the table describing the valid  regular expression as a important note?

**Comment by clintongormley** [comment]
@mayur-persistent sounds fine - open a PR and we can iterate there

**Comment by jpountz** [comment]
cc @elastic/es-search-aggs

**Comment by mayya-sharipova** [comment]
issue is still relevant

**Comment by matriv** [comment]
In my opinion this is the expected behavior. 
- The hour turns to `12` because `hh` is used instead of `HH`. If it's changed to `HH` the hour becomes `00`.
- Since `now%2fd` => `now/d` is used this means that the hours/minutes/seconds are all set to 0, so the  `logstash-2016.12.22.12.00.00` result as an index name is correct. (again if `HH` is used then it becomes: `logstash-2016.12.22.00.00.00`)

Imho, this behavior doesn't need any further explanation.

**Comment by matriv** [comment]
Backported to `7.x` with 3b42dde64fa7165163d98ebbf54a9978d0175c23
to `7.2` with a5a533ea6a501a7fed54ce0ddf51d014d2aeb049
to `7.1` with a09faf8047c4a8a50041a7664b6433ae6d61ed52
to `6.8` with 225670bcd334b7861263e4932ff8da59b65e17d8
