### ISSUE TITLE
Error: Could not find or load main class Active

### ISSUE THREAD

**Issue by unkn19wn** [elastic/elasticsearch#22320]
Hellow After My System crashed my elasticsearch cant start and gives me some error like this :
Error: Could not find or load main class Active
im On Windows 10 and using jdk 1.8.25

**Elasticsearch version**:5.1.1

**Plugins installed**: []

**JVM version**:

**OS version**: Windows 10

**Description of the problem including expected versus actual behavior**:
Error: Could not find or load main class Active
**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by dadoonet** [comment]
Please ask on discuss.elastic.co and provide there your logs.
