### ISSUE TITLE
Painless scripting language add value to the field not working 

### ISSUE THREAD

**Issue by DBARUNNER** [elastic/elasticsearch#22324]
I am using Elasticsearch 5.0.1 want to add value to paritial of document, I use scripting update 

{
    "script" : {
        "inline": "ctx._source.tags.add(params.tag)",
         "inline": "ctx._source.type.add(params.typee)",
        "lang": "painless",
        "params" : {
            "tag" : "blue",
             "type" : "location"
        }
    }
}

but it just add type value not tags value, my mean is that it just add value to one field not both

**Comment by jpountz** [comment]
I think this issue has nothing to do with painless but with the fact that you specify the `inline` property twice, which makes the json document illegal and Elasticsearch only sees the last one. Try: `"inline": "ctx._source.tags.add(params.tag); ctx._source.type.add(params.typee)"`.
