### ISSUE TITLE
Highlight issue using Simple Query Search with "term_vector":"with_positions_offsets" option along with language analyzer

### ISSUE THREAD

**Issue by evertramos** [elastic/elasticsearch#22346]
**Elasticsearch version**: 5.1

**Plugins installed**: [ingest-attachment]

**JVM version**: OpenJDK version "1.8.0_102"

**OS version**: boot2docker and Ubuntu 14.0 (docker version of elasticsearch 5.0 container)

**Description of the problem including expected versus actual behavior**: When indexing a content (pdf file content) we expected to have, under the _simple_query_search_, using double quote ("searched phrase"), the results highlighted as it does with regular search. But if we use as is recommended in ES docs of [Highlighting attachments](https://www.elastic.co/guide/en/elasticsearch/plugins/5.1/mapper-attachments-highlighting.html) the option **"term_vector":"with_positions_offsets"** along with an analyzer, I tested **english** and **brazilian**, the highlight does not show up under the query search, using the simple query search with double quotes, if you have any **stopword** in your search string.

Resume...

if you have any stop word in your search, the highlight simply does not show up in your results! if you use **"term_vector":"with_positions_offsets"** along with an analyzer (**english** and **brazilian** tested).

**Steps to reproduce**:

 1. Create an Index:
```
PUT 127.0.0.1:9200/my_index
{
  "settings" : {
        "index" : {
            "number_of_shards" : 1
        }
    },
    "mappings" : {
        "my_type" : {
          "_source" : {
            "enabled" : true
        },
            "properties" : {
                "name" : { 
                  "type" : "string",
                  "store" : true
              },
                "attachment.content" : { 
                  "type" : "text",
                  "analyzer" : "english",
                  "term_vector" : "with_positions_offsets",
                  "store" : true
              }
            }
        }
    }
}
```

 2. Create a pipeline:
```
PUT 127.0.0.1:9200/_ingest/pipeline/attachment
{
  "description" : "Extract attachment information",
  "processors" : [
    {
      "attachment" : {
        "field" : "content",
        "indexed_chars" : -1
      }
    }
  ]
}
```

 3. Index something:
```
PUT 127.0.0.1:9200/my_index/my_type/1?pipeline=attachment
{
  "name" : "The english team"
  "content" : "V2UgYXJlIHRoZSBlbmdsaXNoIHRlYW0="
}
```

4. Do the search with **simple_query_string** as of the [official docs sample](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/query-dsl-simple-query-string-query.html#_simple_query_string_syntax), using quotes:
```
GET 127.0.0.1:9200/my_index/_search?pretty=true
{
    "stored_fields" : ["name"],
    "size" : 15,
	"query" : {
        "simple_query_string" : {
            "query" : "\"we are the english team\"",
            "fields" : ["attachment.content"],
            "default_operator" : "and"
        }
	},
	
	"highlight" : {
	    "number_of_fragments" : 3,
	    "fragment_size" : 50,
	    "fields" : {
			"attachment.content" : {
			    "highlight_query" : {
			        "simple_query_string" : {
			            "query" : "\"we are the english team\"",
			            "fields" : ["attachment.content"],
			            "default_operator" : "and"
			        }
			    }
			}
		}
	}
}
```

So,

i. if you take of the stop words from the search as of searching only for "english team" it will bring the highlight;

ii. if you remove the analyzer from your mapping, it will bring the highlight, but I believe analyzer are very important, at least for our project today, which is in Portuguese;

iii. last thing if you remove the term vector option **"term_vector":"with_positions_offsets"** it also works... but it becomes very, very slow, so, not possible to use this way.

Please if this is not an issue, forgive taking your time, but it took over weeks trying to solve this and tested everything I could to solve it, even using "query_string" to substitute simple query, which did not work, and simple query options are so great that I believe could not be substituted.

Thanks!

**Comment by dadoonet** [comment]
I'd create a recreation script without ingest as I think it does not play any role here. Can you do that?

Then can you test what is the output of the _analyze API when using your analyzer? That might give some clues. BTW what is exactly your index settings when you switch to Portuguese?

**Comment by evertramos** [comment]
Hello @dadoonet,

I did the test and without the ingest the results are the same. Here is the scripts:
```
PUT 127.0.0.1:9200/my_index
{
  "settings" : {
        "index" : {
            "number_of_shards" : 1
        }
    },
    "mappings" : {
        "my_type" : {
          "_source" : {
            "enabled" : true
        },
            "properties" : {
                "name" : { 
                  "type" : "string",
                  "store" : true
              },
                "content" : { 
                  "type" : "text",
                  "analyzer" : "english",
                  "term_vector" : "with_positions_offsets",
                  "store" : true
              }
            }
        }
    }
}
```

```
PUT 127.0.0.1:9200/my_index/my_type/1
{
  "name" : "English the name",
  "content" : "we are the english team"
}
```

```
GET 127.0.0.1:9200/my_index/_search?pretty=true
{
    "size" : 15,
    "stored_fields" : ["name"],

	"query" : {
        "simple_query_string" : {
            "query" : "\"we are the english team\"",
            "fields" : ["content"],
            "default_operator" : "and"
        }
	},
	
	"highlight" : {
	    "number_of_fragments" : 3,
	    "fragment_size" : 50,
	    "fields" : {
			"content" : {
			    "highlight_query" : {
			        "simple_query_string" : {
			            "query" : "\"we are the english team\"",
			            "fields" : ["content"],
			            "default_operator" : "and"
			        }
			    }
			}
		}
	}
}
```

Here is the analyzers:

1. English
```
GET 127.0.0.1:9200/_analyze
{
  "analyzer" : "english",
  "text" : "\"we are the english team\""
}'
```
Results:
```
{
  "tokens": [
    {
      "token": "we",
      "start_offset": 1,
      "end_offset": 3,
      "type": "<ALPHANUM>",
      "position": 0
    },
    {
      "token": "english",
      "start_offset": 12,
      "end_offset": 19,
      "type": "<ALPHANUM>",
      "position": 3
    },
    {
      "token": "team",
      "start_offset": 20,
      "end_offset": 24,
      "type": "<ALPHANUM>",
      "position": 4
    }
  ]
}
```

2. Brazilian Portuguese:
```
GET 127.0.0.1:9200/_analyze
{
  "analyzer" : "brazilian",
  "text" : "\"Paulo de Tarso\""
}
```
Results: 
```
{
  "tokens": [
    {
      "token": "paul",
      "start_offset": 1,
      "end_offset": 6,
      "type": "<ALPHANUM>",
      "position": 0
    },
    {
      "token": "tars",
      "start_offset": 10,
      "end_offset": 15,
      "type": "<ALPHANUM>",
      "position": 2
    }
  ]
}
```
P.S.: Somehow it takes the last letter off from the analyze, but it comes out right in the query results as of: **Paulo** and **Tarso**.

And here is my full mapping:
```
{
  "settings" : {
        "index" : {
            "number_of_shards" : 1
        }
    },
    "mappings" : {
        "Livros" : {
          "_source" : {
            "enabled" : true
        },
            "properties" : {
                "name" : { 
                  "type" : "string",
                  "analyzer" : "brazilian",
                  "store" : true
              },
                "author" : { 
                  "type" : "string",
                  "analyzer" : "brazilian",
                  "store" : true
              },
                "editor" : { 
                  "type" : "string",
                  "analyzer" : "brazilian",
                  "store" : true
              },
                "url" : { 
                  "type" : "string", 
                  "store" : true
              },
                "attachment.content" : { 
                  "type" : "text",
                  "analyzer" : "brazilian",
                  "term_vector" : "with_positions_offsets",
                  "store" : true
              }
            }
        }
    }
}
```

That simple!

Any further information that would help?

Thanks for your prompt reply.

**Comment by jimczi** [comment]
@evertramos thanks for the report. This is known bug in Lucene:
https://issues.apache.org/jira/browse/LUCENE-7551
The only workaround for the time being is to remove the stop word filter from the analyzers that are used for highlighting. 
We have a plan for a new highlighter called `unified` in 5.x, this highlighter does not have this issue and works with `fast_vectors` so I am going to close this issue and you should probably switch to this new highlighter when it's available (probably in 5.2).

**Comment by evertramos** [comment]
Thanks @jimczi

I will try to set it up as you said. Hope to get this UH soon, once project should be live in a few days now.

Cheers! Happy New Year!

**Comment by evertramos** [comment]
Well, maybe not the best solutions, but I got around with the below settings, only for the record:

1. Mapping the highlight with multi-field:
```
{
  "settings" : {
        "index" : {
            "number_of_shards" : 1
        }
    },
    "mappings" : {
        "Livros" : {
          "_source" : {
            "enabled" : true
        },
            "properties" : {
                "name" : { 
                  "type" : "string",
                  "analyzer" : "brazilian",
                  "store" : true
              },
                "attachment.content" : { 
                  "type" : "text",
                  "analyzer" : "brazilian",
                  "term_vector" : "with_positions_offsets",
                  "store" : true,
                  "fields" : {
					"general" : {
						"type" : "text",
						"analyzer" : "standard",
						"term_vector" : "with_positions_offsets",
						"store" : true
					}
                  }
              }
            }
        }
    }
}
```

2. In search query I use:
```
{
    "stored_fields" : ["name", "author", "editor", "content", "url"],
    "size" : 15,
  "query" : {
        "simple_query_string" : {
            "query" : "\"paulo de tarso\" +prodigo -dileto",
            "fields" : ["attachment.content"],
            "default_operator" : "and"
        }
  },
  
  "highlight" : {
      "number_of_fragments" : 3,
      "fragment_size" : 50,
      "fields" : {
      "attachment.content" : {
          "highlight_query" : {
			"multi_match": {
				"query": "\"paulo de tarso\" +prodigo -dileto",
				"fields": [ 
					"attachment.content",
					"attachment.content.general"
				],
				"type": "most_fields" 
			}
          }
      }
    }
  }
}
```

So I could merge the highlight as probably how the UnifiedHighlight will do it, but a lot better. I understand that my index will be probably doble sized because of the multi-field, as I expect, but right now it solved the situation.

Thanks to all you folks for the great job and the attention.

**Comment by evertramos** [comment]
Hello @jimczi,

Sorry for bothering... any chances to have ````unified```` really integrated with ES? 

As it seems it´s still in experimental mode as of: 

https://www.elastic.co/guide/en/elasticsearch/reference/5.4/search-request-highlighting.html#_unified_highlighter

Thanks

**Comment by jimczi** [comment]
@evertramos when we add a new functionality we often mark it as `experimental`. This is just a warning that says that this is new and that we reserve the right to change it completely in a future release if necessary. This does not prevent you from using it, quite the contrary ;).

**Comment by evertramos** [comment]
All right @jimczi!

Thanks again for your attention.

Cheers
