### ISSUE TITLE
Improved docs related to query order

### ISSUE THREAD

**Issue by ctindel** [elastic/elasticsearch#22353]
A prospective customer was asking about order of operations with a bool query, specifically if the filter section executed before the must/must_not sections.  We weren't able to find an answer to this in our product manual, the closest we could find was this one:

https://www.elastic.co/guide/en/elasticsearch/guide/current/_finding_exact_values.html#_internal_filter_operation

"Although not quite true in reality (execution is a bit more complicated based on how the query planner re-arranges things, and some heuristics based on query cost), you can conceptually think of non-scoring queries as executing before the scoring queries. The job of non-scoring queries is to reduce the number of documents that the more costly scoring queries need to evaluate, resulting in a faster search request."

Maybe we can add some details to the bool query page?

**Comment by clintongormley** [comment]
Things have changed since that para was written in the definitive guide.  It used to matter.  These days the point is: you shouldn't have to think about it, Lucene should figure out the optimum execution for itself.  Also, there's no real way to document this as the execution is dependent on many factors.

**Comment by ctindel** [comment]
It doesn't matter whether someone uses a filter or a must clause in a book query?

**Comment by clintongormley** [comment]
Not for execution order, only because those clauses are executed in "filter context" as described here: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html

I'll add a link from the bool query page to this page

**Comment by ctindel** [comment]
Sounds good!
