### ISSUE TITLE
 context suggestion with Boolean contexts:illegal_argument_exception

### ISSUE THREAD

**Issue by essuraj** [elastic/elasticsearch#22358]
Elasticsearch version: 5.1
Plugins installed: none

illegal_argument_exception
[category] context doesn't support values of type: VALUE_BOOLEAN

```
{
    "suggest" : {
        "prefix" : "add-a-title",
        "completion" : {
            "field" : "TagSuggest",
            "size": 10,
            "contexts": {
                "IsDeleted": { "context" : true }
            }
        }
    }
}
```

elasticsearch 5+ doesn't allow context suggestion s with Boolean contexts.. what can be done about this?

**Comment by clintongormley** [comment]
@essuraj  you need to use the new syntax in 5.0: https://www.elastic.co/guide/en/elasticsearch/reference/5.1/suggester-context.html#suggester-context

**Comment by essuraj** [comment]
@clintongormley I have used the new syntax.. but previously i can add a boolean field too. After the update i am unable to use boolean fields

**Comment by clintongormley** [comment]
Ah gotcha, the snippet you provided is a query, not a mapping.
