### ISSUE TITLE
[feature request]and one more dynamic index setting parameter: traslog path

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#22359]
which can be used to customrized translog path.

**Comment by jpountz** [comment]
What is the motivation for this feature request?

**Comment by makeyang** [comment]
@jpountz while translog could be write on each write operation, in order to improve overall write performance, some users may choose write translog in SSD while write index file on spin disk.

**Comment by jpountz** [comment]
Then we'll probably reject this feature request. We used to have the ability to store shards on multiple data paths but moved away from it. See #9498 for background. Additionally I am not convinced that moving the tranlog to a faster disk while leaving the index on a slow disk would improve write performance.
