### ISSUE TITLE
Unexpected behavior for aggregation of date type represented as epoch_second

### ISSUE THREAD

**Issue by xpr0ger** [elastic/elasticsearch#22352]
```JSON
{
   "name": "C8NYKUu",
   "cluster_name": "elasticsearch",
   "cluster_uuid": "Kg5evNHqTT6EhULQeXf9WA",
   "version": {
      "number": "5.0.0",
      "build_hash": "253032b",
      "build_date": "2016-10-26T05:11:34.737Z",
      "build_snapshot": false,
      "lucene_version": "6.2.0"
   },
   "tagline": "You Know, for Search"
}
```

**Mapping**:
```JSON
{
    "properties": {
        "dt": {
            "type": "date",
            "format": "epoch_second"
        }
    }
}
```

**Some data for test purpose**:
```JSON
POST /test/dt_test
{
    "dt": 1482819449
}
```

**Search query**:
```JSON
{
  "size": 0,
  "query": {
    "match_all": {}
  },
  "aggs": {
    "ids": {
      "terms": {
        "field": "dt"
      },
      "aggs": {
        "dt_max": {
          "max": {
            "field": "dt"
          }
        },
        "bs": {
          "bucket_selector": {
            "buckets_path": {
              "dt_max": "dt_max"
            },
            "script": {
              "lang": "painless",
              "inline": "return Instant.ofEpochMilli(params.dt_max).isAfter(Instant.ofEpochSecond(0))"
            }
          }
        }
      }
    }
  }
}
```

There are two problems in the last query:
* Instead of seconds inside dt_max I've got milliseconds. Is this ok?
* But the most important what I've found out is what the dt_max is the double for inline script.

I've expected what for each of steps in the query I'll get the seconds or I'm wrong? Might it be related to https://github.com/elastic/elasticsearch/issues/17920.

**Comment by jpountz** [comment]
> Instead of seconds inside dt_max I've got milliseconds. Is this ok?

There is a related discussion here https://github.com/elastic/elasticsearch/pull/22201#issuecomment-268634732. Today we use the internal representation for keys, which feels wrong to me. I'd like to fix it but this will be a breaking change.

> But the most important what I've found out is what the dt_max is the double for inline script.

This one is expected, #9545 has more background on this.

Closing as a dup of #9545
