### ISSUE TITLE
Mapper Attachment Plugin - error loading .xlsx attachments

### ISSUE THREAD

**Issue by bdevaca** [elastic/elasticsearch#22369]
I'm receiving this error when attempting to load an excel spreadsheet into Elasticsearch as file content.

I turned on ignore errors to false and I see this error now when loading .xlsx files.

{"error":
{"root_cause":[
{"type":"mapper_parsing_exception","reason":"Failed to extract [-1] characters of text for [null] :
Could not initialize class org.apache.poi.POIXMLProperties"}],
"type":"mapper_parsing_exception","reason":"Failed to extract [-1] characters of text for [null] :
Could not initialize class org.apache.poi.POIXMLProperties","caused_by":{"type":"no_class_def_found_error","reason":"Could not initialize class org.apache.poi.POIXMLProperties"}},
"status":400}

These are the jars that my application is using:
ooxml-schemas-1.0.jar
poi-3.8.jar
poi-ooxml-3.8.jar
poi-ooxml-schemas-3.8.jar

**Comment by dadoonet** [comment]
Linking to full report at https://discuss.elastic.co/t/mapper-attachment-plugin/70160

**Comment by bdevaca** [comment]
Ok, I've gotten a little further. Our application is already using tika for some other process. I update the tika-parsers and tika-core jars from version 1.3 to 1.4 and the original exception went away. Now I'm getting the exception defined in this issue: https://github.com/elastic/elasticsearch/issues/16864

Is this still an issue with Elasticsearch 2.2.0 and the plugin? Do we need to upgrade to 5.X?

**Comment by dadoonet** [comment]
Thank you for the follow up!

It has been fixed in 2.3.0 as per https://github.com/elastic/elasticsearch/pull/17059.

I'm closing this issue then.

**Comment by bdevaca** [comment]
Thank you!
