### ISSUE TITLE
Add ability to set response headers in REST Handlers (ActionPlugin)

### ISSUE THREAD

**Issue by sscarduzio** [elastic/elasticsearch#22367]
Hi, I'm writing a plugin and I've been trying to set a cookie.
It's not easy because albeit I have a RestRequest parameter in `BaseRestHandler.process`, I never have a response object! 

All I see is just this `channel` (an abstraction over the socket) that is passed around and eventually some internal rest handler will write a serialized response in it. 
And then it's too late for me to add any response headers.

## Proposed solution
How about we let users add response headers from the RestRequest instance?
The response headers will be later copied over into the response right before being serialized to the channel.

I.e.

1. Add a method `RestRequest.setResponseHeader(String name, String value)` which will put an entry into a private`RestRequest.responseHeaderMap` field.

2. Add a getter method `RestRequest.responseHeaders()` returning the above map.

2. Modify the `HttpServer.sendResponse` method for copying all the response headers found in `delegate.request().responseHeaders()` into the headers of the response using  the existing`RestResponse.setHeader` method.

I could put this in a pull request if I get any feedback that the reasoning is sound for you guys at Elastic.

**Comment by rjernst** [comment]
We already have a way to add response headers. See [`ThreadContext`](https://github.com/elastic/elasticsearch/blob/66fbb0dbc21f56e074981d1cfaaa9e7cf4676336/core/src/main/java/org/elasticsearch/common/util/concurrent/ThreadContext.java).

However, it looks like we statically set the `ThreadContext` on the one current use (the deprecation logger). The impl of `RestChannel` has the `ThreadContext`, and gets the response headers from there. We could potentially add a method for adding response headers to `RestChannel`, make it an abstract class, and move the `ThreadContext` up to that. @s1monw @javanna wdyt?

**Comment by sscarduzio** [comment]
@rjernst I agree that DeprecationLogger.java is a curious place to initialise the context that will be used all across the framework.

I reiterate on the need to enable plugin developers to either get an instance of ThreadContext or have some methods to get/set response headers from (for example) RestChannel.

As for now, implementing `BaseRestHandler` in my plugin I cannot access ThreadContext instance.

**PS**: Well I might, but by reflection on `channel.delegate.threadContext` in the `RestFilter.process(RestRequest request, RestChannel channel, NodeClient client, RestFilterChain filterChain)` method. But it's not what I should find myself doing :/

**Comment by s1monw** [comment]
I don't understand the problem here to be honest. There is no such method `BaseRestHandler#process` neither in 2.x nor in 5.x nor in master. In all versions you have a handle method where you handle the request and send back a response. `RestResponse#addHeader(String name, String value)` has everything you need no?

Can you maybe share some code where you would like to set the header?

**Comment by sscarduzio** [comment]
Hi @s1monw thanks for answering! You're right, the process method was in it was `RestFilter` which I anonymously instantiated from my impl of `BaseRestHandler`.

Nevertheless, I still would like to know if there is a way to inject a header in the RestResponse without creating a new `RestResponse` object. I.e. from `RestFilter#process`?

Here's the code example required: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/src/main/java/org/elasticsearch/plugin/readonlyrest/wiring/ReadonlyRestRestAction.java#L44

Once again, I don't intend to create the response object myself, I just want to inject an extra header on whatever response will come back from ES.

**Comment by s1monw** [comment]
@sscarduzio note we removed `RestController#registerFilter` for several reasons in the upcoming 5.2 since it can be very trappy and potentially bypass security. You should instead implement `ActionPlugin` in 5.2 and implement `UnaryOperator<RestHandler> getRestHandlerWrapper(ThreadContext threadContext)` then you can use the thread context to add a response header and you will be fine. would that help in your case?

**Comment by rjernst** [comment]
I missed the part about `process`. Simon is right in everything he has said. Note that implementing `getRestHandlerWrapper` means your plugin cannot work alongside `x-pack` (only one plugin may implement this). @sscarduzio you are trying to add a response header with every rest request, not some custom rest handler you are adding?

**Comment by sscarduzio** [comment]
@rjernst, my code needs to set a response header (Set-Cookie) *IF* a certain header is present in the request. I'm super open on how this is going to happen.
No problem for x-pack compatibility.

BTW: 5.2.x is not out, so it's unpractical to test the proposed solution with`getRestHandlerWrapper`. Also this implicitly means that in order to support 5.1.x I need reflection. Right?

**Comment by rjernst** [comment]
> 5.2.x is not out, so it's unpractical to test the proposed solution with `getRestHandlerWrapper`

We publish snapshots to maven central, so you can test with that.

> Also this implicitly means that in order to support 5.1.x I need reflection. Right?

No, as it is not currently possible to have a single artifact that works for multiple versions of elasticsearch. Each plugin must be built specifically for a version of elasticsearch.

**Comment by s1monw** [comment]
for 5.1.x I'd just do 
```JAVA
public ReadonlyRestRestAction(Settings settings, RestController controller, ThreadPool pool) {
  ThreadContext context = pool.getThreadContext();
  // now you can use the context to set your headers
}

```

makes sense?

**Comment by sscarduzio** [comment]
Thank you @s1monw this is exactly what I was looking for, I just didn't think about using DI for making the thread pool just appear from thin air 👍 

@rjernst: yeah I'm making different builds for different version, I was referring to the fact that the code backing the 5.1 build needed to be different, as the `getRestHandlerWrapper` is not yet available.

**Comment by sscarduzio** [comment]
Hey, is there a solution to similarly set response headers in 2.x ?

**Comment by s1monw** [comment]
I am closing this for now since there is a solution
