### ISSUE TITLE
 Painless script error ： doc['last_name'].value will return number value if the value of field 'last_name' contains number chars

### ISSUE THREAD

**Issue by iFrankWu** [elastic/elasticsearch#22366]
**Elasticsearch version**:5.1.1

**Plugins installed**: [head,kibana]

**JVM version**:1.8.0_112

**OS version**:CentOS Linux release 7.2.1511 (Core)

**Description of the problem including expected versus actual behavior**:
When I use painless to 
**Steps to reproduce**:
 1.
PUT /my_index/my_type/1?pretty
{
  "title": "Mr",
  "first_name": "Barry",
  "last_name": "White df 43"
}
 2.
GET /my_index/_search?pretty
{
  "query": {
    "match_all": {}
  },
  "script_fields": {
    "consume-time": {
      "script": {
        "lang": "painless",
        "inline": "doc['last_name'].value"
      }
    }
  }
}
 
it return number 43 , it seems its a bug?

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jimczi** [comment]
Please use the forum for questions like this:
https://discuss.elastic.co/c/elasticsearch

This is the first value present in the fielddata for this field. To return the string entirely you'll have to change the type of the `last_name` field to `keyword`:
https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-fields.html

**Comment by iFrankWu** [comment]
Thanks， its works after change the type to 'keywords'.
