### ISSUE TITLE
Elastic Search "should" clause is not working as expected when "should", "must" and "must_not" clause are present.

### ISSUE THREAD

**Issue by bandikishores** [elastic/elasticsearch#22374]
**Elasticsearch version**: 5.1.1

**Plugins installed**: []

**JVM version**: 1.8.0_91

**OS version**: Ubuntu 16.04 LTS

**Description of the problem including expected versus actual behavior**:

When searching in Elastic Search using POST request.
_Expected:_
When "should", "must" and "must_not" clause are all present, then all 3 needs to be considered for selection.
_Actual:_
The "should" clause is being ignored when "should", "must" and "must_not" clause are all present. Search basically ignores "should" and considers just "must","must_not".

**Steps to reproduce**:

 1. Upload the data provided [here](https://raw.githubusercontent.com/elastic/elasticsearch/master/docs/src/test/resources/accounts.json) into elastic search.
2. Fire below request:
```
curl -XPOST 'localhost:9200/bank/account/_search?pretty' -d'
    {
      "query": {
        "bool": {
          "should": [
            { "match": { "address": "lane" } },
            { "match_phrase": { "address": "mill avenue" } }
          ],
          "must": [
            { "match": { "age": "38" } }
          ],
          "must_not": [
            { "match": { "state": "ID" } }
          ]
        }
      },
      "from": 0,
      "size": 1,
      "_source": ["account_number", "balance", "firstname", "lastname", "age", "email", "address", "state"],
      "sort": [
        { "account_number": "asc" },
        { "balance": "desc"}
      ]
    }'
```

3. Response:
```
{
  "took" : 6,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 36,
    "max_score" : null,
    "hits" : [
      {
        "_index" : "bank",
        "_type" : "account",
        "_id" : "21",
        "_score" : null,
        "_source" : {
          "account_number" : 21,
          "firstname" : "Estella",
          "address" : "859 Portal Street",
          "balance" : 7004,
          "state" : "WV",
          "age" : 38,
          "email" : "estellapaul@zillatide.com",
          "lastname" : "Paul"
        },
        "sort" : [
          21,
          7004
        ]
      }
    ]
  }
}

```

Result:
The record with address **"859 Portal Street"** was received and **it doesn't contain "lane" or "mill avenue"**.

**Comment by nexeh** [comment]
Why was this issue closed?

**Comment by bandikishores** [comment]
@nexeh When must/must_not are present, then minimum_should_match should be set. I added this attribute and it worked as expected.
Hence closed the issue.
