### ISSUE TITLE
Multilevel Nested Query - RequestError Exception 400 - Failed to create query

### ISSUE THREAD

**Issue by Rahul-Babu-R** [elastic/elasticsearch#22385]
Hello all,

I am using Elasticsearch 5.1.1. While doing a nested query, it is returning 400 Error

My Doc will look like this 

> {

        "_index" : "test",
        "_type" : "test_five",
        "_source" : {
          "doc" : {
            "keyword_elas" : "elasticsearch",
            }
          },
          "doc_as_upsert" : true }

This is my Query Code 

> {

    "query": {
        "nested": {
            "path":"_source",
            "query": {
                "nested": {
                    "path": "_source.doc",
                    "query": {
                        "match": {
                            "_source.doc.keyword_elas": "elasticsearch"
                        }
                    }
                }
            }
        }
    }}

For the above Query i got an exception 
> elasticsearch.exceptions.RequestError: TransportError(400, u'search_phase_execution_exception', u'failed to create query: {\n  "nested" : {\n    "query" : {\n      "nested" : {\n 

Is this an exception due to some Query Mistake ?

**Comment by cbuescher** [comment]
Closing since this doesn't look like a bug but very much like a usage problem. Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions.
