### ISSUE TITLE
5.x Aggregation Performance worse than 1.7.x ?

### ISSUE THREAD

**Issue by sinsonglew** [elastic/elasticsearch#22382]
**Describe the feature**: We migrated from 1.7.1 to 5.1.1, and upgrade the corresponding query. we found out that **FiltersAggregation** works much slower, nearly taking 10x time than 1.7.x version. 

Does anybody has similar experience, any optimization advices wil help. Thanks advance!

**Comment by jpountz** [comment]
1.7 used to load filters into a bit set while 5.x consumes filters on the fly. So I would expect 5.x to perform better in the case that the filter is not cached, especially if the query is selective, and 1.x to perform better if the filter was cached. What does your filters aggregation look like?

**Comment by sinsonglew** [comment]
@jpountz , we have such a need: get latest post of multi users by one request. the built query as follows:

`{
  "size": 0,
  "timeout": "3000ms",
  "aggregations": {
    "collector": {
      "filters": {
        "filters": {
          "204443405": {
            "bool": {
              "filter": [
                {
                  "bool": {
                    "must": [
                      {
                        "term": {
                          "userId": {
                            "value": 204443405,
                            "boost": 1
                          }
                        }
                      },
                      {
                        "terms": {
                          "typeId": [
                            1,
                            2
                          ],
                          "boost": 1
                        }
                      },
                      {
                        "term": {
                          "effect": {
                            "value": true,
                            "boost": 1
                          }
                        }
                      }
                    ],
                    "must_not": [
                      {
                        "terms": {
                          "workId": [
                            101219700,
                            576315300,
                            578923100
                          ],
                          "boost": 1
                        }
                      }
                    ],
                    "disable_coord": false,
                    "adjust_pure_negative": true,
                    "boost": 1
                  }
                }
              ],
              "disable_coord": false,
              "adjust_pure_negative": true,
              "boost": 1
            }
          },
          "204659905": {
            "bool": {
              "filter": [
                {
                  "bool": {
                    "must": [
                      {
                        "term": {
                          "userId": {
                            "value": 204659905,
                            "boost": 1
                          }
                        }
                      },
                      {
                        "terms": {
                          "typeId": [
                            1,
                            2
                          ],
                          "boost": 1
                        }
                      },
                      {
                        "term": {
                          "effect": {
                            "value": true,
                            "boost": 1
                          }
                        }
                      }
                    ],
                    "must_not": [
                      {
                        "terms": {
                          "workId": [
                            101219700,
                            576315300,
                            578923100
                          ],
                          "boost": 1
                        }
                      }
                    ],
                    "disable_coord": false,
                    "adjust_pure_negative": true,
                    "boost": 1
                  }
                }
              ],
              "disable_coord": false,
              "adjust_pure_negative": true,
              "boost": 1
            }
          },
          "214507405": {
            "bool": {
              "filter": [
                {
                  "bool": {
                    "must": [
                      {
                        "term": {
                          "userId": {
                            "value": 214507405,
                            "boost": 1
                          }
                        }
                      },
                      {
                        "terms": {
                          "typeId": [
                            1,
                            2
                          ],
                          "boost": 1
                        }
                      },
                      {
                        "term": {
                          "effect": {
                            "value": true,
                            "boost": 1
                          }
                        }
                      }
                    ],
                    "must_not": [
                      {
                        "terms": {
                          "workId": [
                            101219700,
                            576315300,
                            578923100
                          ],
                          "boost": 1
                        }
                      }
                    ],
                    "disable_coord": false,
                    "adjust_pure_negative": true,
                    "boost": 1
                  }
                }
              ],
              "disable_coord": false,
              "adjust_pure_negative": true,
              "boost": 1
            }
          },
          "215114505": {
            "bool": {
              "filter": [
                {
                  "bool": {
                    "must": [
                      {
                        "term": {
                          "userId": {
                            "value": 215114505,
                            "boost": 1
                          }
                        }
                      },
                      {
                        "terms": {
                          "typeId": [
                            1,
                            2
                          ],
                          "boost": 1
                        }
                      },
                      {
                        "term": {
                          "effect": {
                            "value": true,
                            "boost": 1
                          }
                        }
                      }
                    ],
                    "must_not": [
                      {
                        "terms": {
                          "workId": [
                            101219700,
                            576315300,
                            578923100
                          ],
                          "boost": 1
                        }
                      }
                    ],
                    "disable_coord": false,
                    "adjust_pure_negative": true,
                    "boost": 1
                  }
                }
              ],
              "disable_coord": false,
              "adjust_pure_negative": true,
              "boost": 1
            }
          }
        },
        "other_bucket": false,
        "other_bucket_key": "_other_"
      },
      "aggregations": {
        "top": {
          "top_hits": {
            "from": 0,
            "size": 4,
            "version": false,
            "explain": false,
            "_source": {
              "includes": [
                "workId",
                "userName"
              ],
              "excludes": []
            },
            "sort": [
              {
                "lastUpdateTime": {
                  "order": "desc"
                }
              }
            ]
          }
        }
      }
    }
  },
  "ext": {}
}`

**Comment by jpountz** [comment]
You can probably get faster results by moving the common bits to the query part:

```javascript
{
  "size": 0,
  "timeout": "3000ms",
  "query": {
    "bool": {
      "filter": [
        {
          "terms": {
            "typeId": [1, 2]
          }
        },
        {
          "term": {
            "effect": true
          }
        }
      ],
      "must_not": [
        {
          "terms": {
            "workId": [101219700, 576315300, 578923100]
          }
        }
      ]
    }
  },
  "aggregations": {
    "collector": {
      "filters": {
        "filters": {
          "204443405": {
            "term": {
              "userId": 204443405
            }
          },
          "204659905": {
            "term": {
              "userId": 204659905
            }
          },
          "214507405": {
            "term": {
              "userId": 214507405
            }
          },
          "215114505": {
            "term": {
              "userId": 215114505
            }
          }
        }
      },
      "aggregations": {
        "top": {
          "top_hits": {
            "from": 0,
            "size": 4,
            "version": false,
            "explain": false,
            "_source": {
              "includes": [
                "workId",
                "userName"
              ],
              "excludes": []
            },
            "sort": [
              {
                "lastUpdateTime": {
                  "order": "desc"
                }
              }
            ]
          }
        }
      }
    }
  },
  "ext": {}
}
```

I did not test it so there might be typos but hopefully this gives you the idea.

**Comment by sinsonglew** [comment]
@Adrien，Your advice help a lot，thanks！

发自我的 Windows Phone
________________________________

**Comment by sinsonglew** [comment]
Hi, @jpountz , hoping get advices for another question.  Efficiency issue between _**terms**_ query and **_range_** query , to enumerable integers , for example with number size less than 50, we can filter by terms and ranges. but which is better and preferred. Thanks !

**Comment by jpountz** [comment]
Use a range.
