### ISSUE TITLE
Rollover API: Add condition to rollover on field value

### ISSUE THREAD

**Issue by jakommo** [elastic/elasticsearch#22392]
**Describe the feature**:
Currently the rollover API support two conditions. `max_docs` and `max_age` (which will be calculated based on the index creation time).

I'd like to propose an additional condition, that takes the value of a field into account.
E.g. `max_value` on the `@timestamp` field.
This could be useful when reindexing from daily indices into rollover indices, but you want the rollover indices at max weekly (to comply with retention policies). 
Currently the `max_age` cant be used for this, as it's based on the index creation time and not the timestamp of the documents in the index.

**Comment by s1monw** [comment]
I need to understand more why this is useful. The purpose of the rollover API was mainly to gain a way to build a _well sized_ index. ie. find a sweet spot in terms of documents and then just keep on indexing, we roll over for you. If you want to restrict documents that go into an index with reindexing then you can just filter the reindexing instead, that way you would get indices with only these documents. Rollover is only best effort here I think. if the problem is that the index might have been created a week ago for some reason and now things are off due to that then I guess we need to fix the `max_age` somehow?

**Comment by jakommo** [comment]
Thansk for your feedback @s1monw 

> I need to understand more why this is useful

I think it's mainly useful on reindexing, when you want to use something like `max_age` but can't use it as it only works for ongoing indexing. (due to the condition check on index created).

> The purpose of the rollover API was mainly to gain a way to build a well sized index. ie. find a sweet spot in terms of documents and then just keep on indexing, we roll over for you.

I understand, however there is already the `max_age` condition, which would roll-over based on the age of the index rather than the # of docs. I guess this was implemented to have some kind of retention period control, if the  # of docs is not met for some reason. 

Maybe my proposal, should be to make the `max_age` working when reindexing. I.e. don't take the creation time into account but the timestamp of the docs (might not work for all use cases, so maybe make it configurable if its index creation or age of a date field? )

>  If you want to restrict documents that go into an index with reindexing then you can just filter the reindexing instead, that way you would get indices with only these documents

Yes, but I was thinking of using the rollover for this, rather than having a script sorting it out. 
The `max_age` kind of does this already, it just checks for the index creation time, rather than a value from the documents.
Now I don't know how the rollover works in the background and if it would make sense to shift this from reindex with a script to rollover, but I thought, as there is already a `max_age`, we could adjust it to also work in such a case.

What do you think? 

> if the problem is that the index might have been created a week ago for some reason and now things are off due to that then I guess we need to fix the max_age somehow?

I didn't think about this, but it sounds like a pro towards making it configurable and to take the value of the "oldest" date field into account.

**Comment by s1monw** [comment]
>Now I don't know how the rollover works in the background and if it would make sense to shift this from reindex with a script to rollover, but I thought, as there is already a max_age, we could adjust it to also work in such a case.

just FYI `_rollover` must be invoked periodically from the outside to do anything. I think it would be confusing if we make it _field aware_

**Comment by jakommo** [comment]
Thanks for clarifying @s1monw, I totally missed the periodic `_rollover` call, my understanding was that this is done in the background automatically. 
With that in mind, my proposal does not make sense. Closing.

**Comment by s1monw** [comment]
> Thanks for clarifying @s1monw, I totally missed the periodic _rollover call, my understanding was that this is done in the background automatically.
With that in mind, my proposal does not make sense. Closing.

the reason why it's not in the background is that it's very hard to test and also hard to communicate to the user if something fails. It would also give users the impression we would be strict about the limits which we are not.
