### ISSUE TITLE
Let's talk about HTTP testing with assertions enabled

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#22390]
For better or worse Elasticsearch uses assertions to detect bugs. The vast, vast majority if users run with them disabled because that is the default and they have a performance overhead. Sometimes it is a non-trivial performance overhead. Anyway, we recently turned assertions on during out HTTP tests (#22334) and they caught a few bugs, some of them we're quite glad it caught. We think there is value in running the assertions during testing. We wrote them to catch bugs, after all. But we also think there is value in the HTTP testing being as true to production settings as possible and running with assertions enabled obviously doesn't do that.

So this issue is to discuss striking a balance.

**Comment by jasontedor** [comment]
To recap a discussion we had via another channel on this:
 - we are going to keep assertions enabled by default in standalone tests (just like our other tests)
 - we are going to add a dedicated CI job that runs with assertions disabled in all tests
 - we are going to improve the error reporting for standalone tests (dump all nodes logs if any test fails)
