### ISSUE TITLE
Document `detailed` parameter for task manager

### ISSUE THREAD

**Issue by eskibars** [elastic/elasticsearch#22407]
**Elasticsearch version**: 5.1.1

**Describe the feature**: Several people have asked how to use the [detailed task descriptions](https://github.com/elastic/elasticsearch/pull/21740) + [search cancellation](https://github.com/elastic/elasticsearch/pull/20405). I realized they're probably asking because we haven't updated our [task management docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/tasks.html) to list the `detailed` parameter

**Comment by nik9000** [comment]
I'll put this on my list of things to do but it might be a day or two. If someone else gets to it before I do please unassign me.
