### ISSUE TITLE
Accept proper/valid JSON body in _bulk request

### ISSUE THREAD

**Issue by mpenet** [elastic/elasticsearch#22402]
Right now `_bulk` accepts a body that is not a real valid JSON document but a `\n` delimited sequence of JSON fragments. 
It would be more friendly, if, when passing an `application/json` content-type, the server would accept a proper JSON Array as body value.

It might incur a minimal overhead compared to the simple `\n` format but this should be negligible assuming JSON parsing is done with a library that supports streaming (I think it already does).

Related to this on https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html it says: 
```
The REST API endpoint is /_bulk, and it expects the following JSON structure:
[...]
```
It might be desirable to change the wording since it's not in fact a JSON structure but a "blob" composed of JSON fragments.

**Comment by clintongormley** [comment]
A JSON array would add significant overhead to the parsing.  The meta lines are short and are all that are needed to redirect the bulk request from the coordinating node to the node that holds the relevant shard.  The doc lines are long and complicated, so skipping forward to the next `\n` saves a lot of parsing, and allows the shard-specific mini-bulk to read the doc line directly from the network buffer when forwarding, without having to create a new JSON structure.

> It might be desirable to change the wording since it's not in fact a JSON structure but a "blob" composed of JSON fragments.

Would you like to send a PR with the appropriate wording?
