### ISSUE TITLE
MockTcpTransportTests.testTracerLog often fails

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#22418]
Example of failure:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/1246/console

**Comment by javanna** [comment]
@s1monw can you have a look? I saw that you worked on this test and added some test logging quite recently.

**Comment by s1monw** [comment]
oh yeah, I found the issue but never fixed it. I will push a fix soon
