### ISSUE TITLE
[STORE] path dedicated to index.

### ISSUE THREAD

**Issue by rkalhans** [elastic/elasticsearch#22415]
**This is a feature request**
**Elasticsearch version :**   2.4
 We would like to have  ability to configure path for an index.  This would solve the following problem.

1. We are currently using shared indices for our customers. We would like to have ability to have premium customers isolated from free customers. Since we are using a custom plugin for a custom search, the search performance depends on the disk IO performance. We don't want high disk queues for premium customers.  Also since we are on cloud storage which is subject to throttling, we would want to isolate the premium customer from getting throttled. 

2. We can move to HDD for non premium customers vs SSD for premium ones. also hot and cold indices can be handled in this manner.

3. Selective disk encryption for sensitive data: We have sensitive data which we would like to be encrypted. Since encryption is prone to slowness, it would make sense to have encrypt only selective disks and not all of them.

**Comment by s1monw** [comment]
you can set `path.data` per index. This will override the default setting for every index and will use this path on every node. That way you can point all date for a single index to this directory. Will this be sufficient? Just set it when you create the index.

**Comment by rkalhans** [comment]
@s1monw sorry, I could not follow you. I tried the following
```
PUT  findex
{
    "path":
    {
        "data":["F:\\data"]
    },
        "mappings": {}
}

```
This created the new index in the original location. also I cannot find documentation of using path.data per index

**Comment by s1monw** [comment]
Sorry I was giving you the wrong settings. You have to set `path.shared_data` to a path on the filesystem under which the per index directories are created ie. `/opt/customer_indices`  then you can create an index with `index.data_path: /opt/customer_indices/customer_1` and it will create the index directory in `/opt/customer_indices/customer_1`. This is part of the shadow replica [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/indices-shadow-replicas.html) but you don't need shadow replicas for this at all. the `path.shared_data` is required to enable the security manager to grant permissions for write access to this directory.

**Comment by rkalhans** [comment]
cool. this works. Thanks a lot.

**Comment by s1monw** [comment]
YW
