### ISSUE TITLE
Cluster allocation explain backwards tests fail

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#22414]
See failure example: 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/557/console

Relates to #22182

**Comment by javanna** [comment]
@abeyad can you have a look please? It may be that these tests need a missing skip section, but can you double check that this is expected please?

**Comment by javanna** [comment]
I have later realized that this may be fixed already, I am not 100% sure though, feel free to close without any further action :)

**Comment by abeyad** [comment]
@javanna thanks for looking! this was fixed by d1bf4ea4ee551d698f83cf01023ce75b27652ac1.  I'll update the version number in the description as you suggested.
