### ISSUE TITLE
ClusterAllocationExplainIT.testUnassignedPrimaryWithExistingIndex fails

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#22417]
See example of failure: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/562/console

Relates to #22182

**Comment by javanna** [comment]
@abeyad can you take a look please?

**Comment by abeyad** [comment]
@javanna this is a test bug, I pushed a fix: 6f242920d3590ab36e08918c6a5a69ad6a689d9c
