### ISSUE TITLE
changing password fails

### ISSUE THREAD

**Issue by tronicum** [elastic/elasticsearch#22419]
**Elasticsearch version**:
Version: 5.1.1, Build: 5395e21/2016-12-06T12:36:15.409Z, JVM: 1.8.0_111

**Plugins installed**: []
x-pack

**JVM version**:
openjdk-8-jre-headless 8u111-b14-2~bpo8+1
**OS version**:
docker image (elastic)

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. install xpack
 2. run http://localhost:9200/_xpack/license?acknowledge=true'
     (result: {"acknowledged":true,"license_status":"valid"}root@container:~#)
 3. try to change password

**Provide logs (if relevant)**:

(i used https://www.elastic.co/guide/en/x-pack/current/security-getting-started.html as guide)

curl -XPUT -u elastic:changeme 'localhost:9200/_xpack/security/user/elastic/_password' -d '{
  "password" : "verysecurepassword"
}'

{"error":{"root_cause":[{"type":"security_exception","reason":"current license is non-compliant for [security]","license.expired.feature":"security"}],"type":"security_exception","reason":"current license is non-compliant for [security]","license.expired.feature":"security"},"status":403}root@46348dda2b19

**Comment by tronicum** [comment]
pulled elasticsearch:latest, still broken.

**Comment by jaymode** [comment]
It appears that you have installed a basic license, which does not allow security to be used. This is why you get a license exception. If you have further questions please use https://discuss.elastic.co

**Comment by tronicum** [comment]
can i change the password without xpack installed?

**Comment by tronicum** [comment]
i would like to use basic authentification between kibana and elasticsearch with x-pack enabled. 
is that impossible?

**Comment by jaymode** [comment]
We reserve github for bug reports, please open a discussion at the link I provided earlier for your questions.
