### ISSUE TITLE
Indicate if global state is present is snapshot

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#22423]
When a snapshot is made with `include_global_state`, the [_status endpoint](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_snapshot_status) should indicate if state data is present, maybe with some info about what it has.

**Comment by bawse** [comment]
Could you give some more information on this? I'm a new contributor.

**Comment by PhaedrusTheGreek** [comment]
A snapshot usually contains a backup of some indices, but when you take the snapshot with the `include_global_state` parameter, then other non-index data is included in the backup, such as templates, persistent settings, and other global state.      Then when you go to [restore](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_restore) the backup, you can specify `include_global_state` again in the API call, and that state will be restored along with the indices.  It would just simply be useful to be able to see a yes/no flag in the _status endpoint indicating the snapshot includes global state.

**Comment by wedneyyuri** [comment]
Hi @PhaedrusTheGreek, do you know any detailed docs about the `global_state` data and how it can be useful?

**Comment by liketic** [comment]
I can take this.
