### ISSUE TITLE
mustache template support unquoted variable replace

### ISSUE THREAD

**Issue by oxnz** [elastic/elasticsearch#22427]
**Add unquoted variable replace capabilities**:
currently, the template variable expand got auto-quoted, so there's no way to pass-in numbers or other advanced structure like dictionary except the usage of stored file or inline string
It would be nice to have a feature can easily expand variables in an unquoted manner like this:

```http
GET /_render/template
{
  "inline": {
    "function_score": {
      "inline": "return params.ts;",
      "params": "unquoted({{#toJson}}script_params{{/toJson}})"
    }
  },
  "params": {
    "script_params": {
      "timestamp": 1400000000,
      "title_weight": 0.85
    }
  }
}
```

returns

```json
{"template_output":{"function_score":{"inline":"return params.ts;","params":{"title_weight":0.85,"timestamp":1400000000}}}}
```

instead of

```json
{"template_output":{"function_score":{"inline":"return params.ts;","params":"{"title_weight":0.85,"timestamp":1400000000}"}}}
```

**Comment by clintongormley** [comment]
The only way to do it is to pass the template as a string, otherwise the JSON request can't be parsed.  We're stuck with what we have I'm afraid
