### ISSUE TITLE
5.1 javaAPI - DeleteByQueryRequestBuilder change

### ISSUE THREAD

**Issue by lyumkh** [elastic/elasticsearch#22424]
**Elasticsearch version**: 5.1.1

**Plugins installed**: []

**JVM version**: 

**OS version**: centos 7

**Description of the problem including expected versus actual behavior**:
ES 5.1 version does not support delete-by-query plugin.
so i need to change the javaAPI code.

The following code is from the previous 2.3 version.
`new DeleteByQueryRequestBuilder(ElasticConnector.getInstance().getJavaClient(), DeleteByQueryAction.INSTANCE)
 .setIndices(GLOBAL_ID)
.setTypes(MessageService.DEVICE)
.setQuery(QueryBuilders.boolQuery().should(QueryBuilders.termQuery("user_id", user_id))
							   .should(QueryBuilders.termQuery("device_id", device_id)                    .mustNot(QueryBuilders.boolQuery().must(QueryBuilders.termQuery("user_id", user_id))					                    		                          .must(QueryBuilders.termQuery("device_id", device_id))
 )).execute().actionGet();`

This code has a problem with "DeleteByQueryRequestBuilder cannot be resolved to a type"
How do I change the code?

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jasontedor** [comment]
Please ask general questions on the [forum](https://discuss.elastic.co). Elastic reserves GitHub for verified bug reports and feature requests.
