### ISSUE TITLE
Kibana dashboard filters "No results found"

### ISSUE THREAD

**Issue by Passpes** [elastic/elasticsearch#22428]
**4.1.1****Centos 7.3**:

Centralized logging for IPA
https://www.freeipa.org/page/Centralized_Logging

Docker container for REK stack
pschiffe/rsyslog-elasticsearch-kibana

Log forwarding confgiuration on IPA server
https://github.com/pschiffe/ipa-log-config/blob/master/ipa_log_config.py

So basically I have a configuration containing 2 servers IPA and REK and I can see all the data on Kibana so Rsyslog is sending properly data to REK's Rsyslog which transfert it to Elasticsearch for the parsing.

The problem is that  pschiffe/rsyslog-elasticsearch-kibana comes with some dashboards to simplify the visualization of all these data https://www.youtube.com/watch?v=7YjA6z5nE0I which is not working.

what's the problem ? and how can I fix it ?

**Comment by dadoonet** [comment]
Please ask questions like this on discuss.elastic.co.
We can help there.
