### ISSUE TITLE
Add Ability to Infer Index Name from Alias When Using Index Templates

### ISSUE THREAD

**Issue by eladmena** [elastic/elasticsearch#22446]
When using index templates the first creation of a document will use the index name and create alias(es) based on the template definition.
I'd like to add the ability to infer the index name from one of the aliases.

This is needed when using context based indices (for example index per project id) and wanting to use aliases for all requests.
Otherwise the first create of a document should be with the index name and later calls with the alias name, and if already using different behaviour for first create request and subsequent ones one can create the index on its own so index templates will not help for this case.
Having this feature allows a uniform way for accessing documents.

Note by default this feature is off for any given template, unless explicitly specifying **infer_index_name_from_alias** = true in the template definition.

## Usage example:
```
PUT /_template/template_1
{
  "template": "project-*",
  "settings": {
    "number_of_shards": 1,
	"number_of_replicas" : 0
  },
  "mappings": {
    "type01": {
      "dynamic": "strict",
      "properties": {
        "field01": {"type": "text"}
      }
    }
  },
  "aliases": {
	"{index}-read" : {},
	"{index}-write" : {}
  },
  "infer_index_name_from_alias" : true
}
```
using the **infer_index_name_from_alias** = true, it specifies that when this template matches try to infer the index name from the alias.

thus when calling:
```
POST /project-01-write/type01/
{
    "field01" : "aaaaa"
}
```

Index **proect-01** will be created and aliases **project01-read** & **project01-write**
If **infer_index_name_from_alias** is false or not set index name will be **project01-write** and aliases will be **project01-write-read** & **project01-write-write**.

This is already implemented, tested & documented in https://github.com/eladmena/elasticsearch

**Comment by oana-stroie-hs** [comment]
Hi, @eladmena, will this issue be fixed?

**Comment by eladmena** [comment]
This issue is fixed, but pending merge of pull request 22447
https://github.com/elastic/elasticsearch/pull/22447

**Comment by eladmena** [comment]
Ping on that issue.
It is already implemented, the change is simple, tested (with integration test) and documented.

Currently the code marks it to work only for Elasticsearch 7

**Comment by clintongormley** [comment]
Hi @eladmena 

Sorry we haven't discussed this issue yet.

I'm afraid i don't like this idea.  It is hard to reason about for users, and likely to have a lot of edge cases. For instance, doing a wildcard search might cause matching templates to spring into existence.

 Instead, I think that a better solution would be a request time option that says "fail this indexing request if the index doesn't exist".  Then the client could take the action of creating the index (which would include the correct alias from the template), and then continue onwards using the alias.

This is safe, simple, and easy to reason about.

**Comment by eladmena** [comment]
Hey @clintongormley,
Thank for your response.

I think this feature is very useful and without it the index templates feature is incomplete, especially when a lot of best practices are to work with aliases, having this feature gives the user the ability to use the index using aliases from call no. 1, having a single behaviour when using the index, no matter if it exists or not.

Having a failure beats the purpose of index templates, now the user will have to create the index on his own and keep track what indices are created and what not (in our application we managed the indices ourselves without using index templates as this feature was missing)

Can you please elaborate on your concerns? If you'll look on the fix implementation (most of the logic is in _TransportCreateIndexAction.inferIndexNameFromAlias()_) you'll see it only affects index creation, changing the index name only if it can be inferred from the alias of the template, without changing the original request. It also works with date maths and tested using IT to verify it works as needed when turned on and doesn't affect other requests if turned on or not set.

**Comment by bleskes** [comment]
> Can you please elaborate on your concerns

We try to fully understand the reasoning for adding features. The interaction between indices, aliases and templates is already complex enough.

Can you please elaborate on your use case? What is the role of the aliases?  i.e., what's the reason to distinguish between read and write?

**Comment by eladmena** [comment]
the -read/-write suffix is just an example for aliases names.

The idea of this feature (more an enhancement for the index-templates feature) is as follows:
In case an index-template has aliases in its configuration and the application works with aliases to access indices, then the index template feature doesn't give a complete solution.

for example if my template matches "a*" and has an alias called **{index}**_-alias_. (which means that when creating an index called **abc** it'll also create an alias called **abc**_-alias_.
If I'll index (add document) to a non existing index using the (application logic) alias name abc-alias, the index template will treat **abc-alias** as the index name and will create an alias called **abc-alias**_-alias_, not as intended. If ES would have treated the request as create index called **abc** by inferring the index name from the alias name we could have had a uniform behaviour from request no. 1.

To workaround this limitation one needs to first create the index using the index name and then access the index using the alias name, however, if this is the case then index template doesn't help (in this case) as one needs a different behaviours in case it is the first call or whether it's subsequent ones, and if that's the case, the first call can be create the index with the mapping you need, and the rest will access the index using the alias.

How it affected our app:
we were population ES using Logstash which got the index name from the app, we wanted to both have a uniform index name per context and also use aliases, it wasn't possible with ES only, our solution was the above workaround, we had to keep a cache of what indices are in ES and if they do not exist create them, and having Logstash always use the alias name.

**Comment by clintongormley** [comment]
I can see how this works for your particular naming scheme, but this is fragile.  Eg, what if I want my alias to be `foo`,  instead of `foo-write`?  Then I have an alias setting of `{{index}}` which matches any index.  Or what if I want my alias to be `{{apache}}` but my index name to be `apache-2017.11.12`?

This change adds one narrow bit of functionality which relies on convention to work, and introduces situations where it won't work correctly and will confuse users.  I'm against making this change.

**Comment by eladmena** [comment]
The current implementation of index templates allows to create alias(es) based on the index name, the above enhancement allows to reverse the order that the index name will be inferred from the alias. keeping the same behaviour of index templates.

In case you want to change the issue to be **force** derive index name from alias it may be more complicated

1. Having an index template can have multiple aliases
so one will need to set the "master" alias which will the name will be derived from ==> derive the index name ==> derive the other aliases (either from the index/"master" alias name)
1. The order of the aliases is not consistent, meaning for the invoking the same request I can get a different order of aliases, so when implementing one needs to make sure the "master" alias is called first.

In any case I prefer the pull request will be merged and open another issue for the alias --> index name, as those are complementary as it's either index name --> alias name or alias name --> index name

**Comment by clintongormley** [comment]
This is my point. It is narrow, complicated, and confusing, and just leads to more changes.  I don't want to merge this PR at all, for these reasons.   Sorry, but this feels like a change we will regret.  I'm -1 on doing this.

**Comment by test987654123** [comment]
I am sorry. My wish help.
This is a index template setting configuartion.
 {
        "order": 5,
        "version": 60001,
        "index_patterns": [
            "debug*"
        ],
        "settings": {
            "index": {
                "number_of_shards": "1",
                "number_of_replicas": "0",
                "refresh_interval": "1s"
            }
        },
        "mappings": {
            "doc": {
                "properties": {
                    "logLevel": {
                        "type": "keyword"
                    },
                    "hostname": {
                        "type": "keyword"
                    },
                    "application": {
                        "type": "keyword"
                    }
                }
            }
        },
        "aliases": {
            "{application}-alias-for-{env}": {
            "format": {
                "env": {
                    "lang":   "expression",
                    "script": "doc['logLevel'].value"
                },
                "application": {
                    "lang":   "expression",
                    "script": "doc['application'].value"
                }
            }
        }
        }
    }

-------------------------------------------------------------
when create index, auto create alias ,but result not is I wish
