### ISSUE TITLE
Highlighting html markup includes closing html tags if no blank space between text and html tag

### ISSUE THREAD

**Issue by Khamersk** [elastic/elasticsearch#22448]
**Elasticsearch version**: 2.3.2

**Plugins installed**: None

**JVM version**: 1.7.0_67

**OS version**: Windows 7

**Description of the problem including expected versus actual behavior**:
I have a field that is indexed called "htmlMarkup".  I want to be able to search and highlight on this field without getting hits on html.  I added the "html_strip" char filter on my index and that effectively removes the hits on html markup.  However when it comes to highlighting the results I get a result similar to this:
```
"htmlMarkup": "<span><span>test123</span></span>"
```

I search on the term: 
`"test123"`

my highlight result:

` "<highlight>test123</span></span></highlight>`

I would expect when highlighting on the search term "test123" that I would get a result like this:
`<highlight>test123</highlight>`

When I add a blank space after "test123" ie: 

`<span><span>test123 </span></span>`

the result i get is correct: 
`
<highlight>test123 </highlight>`

If I do not use the  "html_strip" char filter than the highlight works correctly and as expected however, then I am able to search on "span" and get hits on the html markup itself.

**Steps to reproduce**:
 1. Query on term that is within html markup on an field with "html_strip" char filter, the field must contain no space after term before closing html markup tags end
 2. Notice that the highlight includes the closing html tags
 3.

**Comment by clintongormley** [comment]
I would either index text instead of HTML, or use a pattern-replace character filter to remove HTML tags before tokenizing the text.
