### ISSUE TITLE
Provide URL encoding support in Painless

### ISSUE THREAD

**Issue by sherry-ger** [elastic/elasticsearch#22459]
**Describe the feature**:

Provide URL encoding support in Painless.  This is especially useful in a Watch for an URL in an email action or a Slack action.  Although a workaround using String replaceAll is doable, it is not very convenient.

**Comment by clintongormley** [comment]
@sherry-ger Our templates provide a helper for URI encoding already - can't that be used instead of Painless?

**Comment by sherry-ger** [comment]
@clintongormley  I am not sure I follow.  The use case is limited to Watcher.  The request is to encode a Kibana URL in a Watcher email action, in the transform section in specific, so it can be included in the email body.

**Comment by clintongormley** [comment]
A watcher email body is rendered from a Mustache template. Templates already have support for doing URL encoding. See https://github.com/elastic/elasticsearch/pull/20838
