### ISSUE TITLE
memory locking requested for elasticsearch process but memory is not locked

### ISSUE THREAD

**Issue by wh211212** [elastic/elasticsearch#22485]
**Elasticsearch version**:elasticsearch-5.1.1

**Plugins installed**: [NULL]

**JVM version**:jdk1.8.0_111

**OS version**:CentOS release 6.8 (Final)

**Description of the problem including expected versus actual behavior**:
I'm set  bootstrap.memory_lock: true, then restart elasticsearch,failed
**Steps to reproduce**:
 1. configure elasticsearch.yml
 2.restart elasticsearch
 3.checkrun

**Provide logs (if relevant)**:

**Describe the feature**:
bootstrap checks failed
memory locking requested for elasticsearch process but memory is not locked
max number of threads [1024] for user [elasticsearch] is too low, increase to at least [2048]

**Comment by dadoonet** [comment]
Probably because of this: https://www.elastic.co/guide/en/elasticsearch/reference/current/_maximum_number_of_threads_check.html

Please ask on discuss.elastic.co instead.

**Comment by wh211212** [comment]
I'm already solve max number of threads [1024],but the memory locking problem also exist... then I'm set bootstrap.memory_lock: false ,elasticsearch restart succeed. but I also want configure memory locaking...

**Comment by dadoonet** [comment]
discuss.elastic.co is the best place to ask for help.

This space is for confirmed issues only.
