### ISSUE TITLE
Mapping explain endpoint

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#22483]
It'd be great if we had functionality that let a user push a doc through a `_mapping` endpoint of some sort (`?explain` perhaps?) and then got a reply that contained what ES would then do with that doc after it applies the mapping, but without indexing the doc.

For bonus points it'd be great if it also checked templates, and then explained which templates matched accordingly.

I think this would be helpful for users with multiple templates, perhaps with varying order, and understanding which apply to a doc. But also for any user wanting to see how their mapping would apply, without indexing the doc.

**Comment by clintongormley** [comment]
The simplest way of running this test is to index a doc.  Why would we need an explain function on top of this?

**Comment by markwalkom** [comment]
Perhaps a better term would be simulate, like the ingest node can do. That is more my line of thinking.

Because just like with pipeline, sometimes you want to see the outcome of a document being mapped without it actually being mapped+indexed+stored and then having to retrieve it.

**Comment by clintongormley** [comment]
I'm still not getting what it is you want this API to return.  What is it that you're wanting to test? Ingest pipelines can be complicated, so it makes sense to have detailed debugging, but here?  If it's analysis you're after, we have the analyze endpoint. If it is just to see what fields are created, I'm not seeing the benefit of adding a new API when you can just create a test index then drop it again.

**Comment by markwalkom** [comment]
Mappings can also be complicated, if you add in synonyms, custom analysis etc. 
As a user I want it to return the doc after the mapping has been applied. But without indexing it, retrieving it and then deleting the index because I need to change it.

Exactly like the ingest pipeline does :)

**Comment by clintongormley** [comment]
> As a user I want it to return the doc after the mapping has been applied

The doc doesn't change.  The source is exactly the same.  So what is it you want returned?

**Comment by clintongormley** [comment]
> Mappings can also be complicated, if you add in synonyms, custom analysis etc.
As a user I want it to return the doc after the mapping has been applied. But without indexing it, retrieving it and then deleting the index because I may then need to change it.

This sounds like something best accomplished with a UI that uses the `analyze` API.
