### ISSUE TITLE
Additional Graph Token Stream Support in Match Query

### ISSUE THREAD

**Issue by mattweber** [elastic/elasticsearch#22490]
#21517 introduced simple support for graph token streams in the match family of queries.  It looks like this should be taken further and support common terms and phrase prefix.  Right now, if using either of these modes, a `GraphQuery` is potentially returned but will never have the [common terms](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/search/MatchQuery.java#L358) or [phrase prefix](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/search/MatchQuery.java#L329) wrapping as if this was returned as a normal boolean or phrase query.

Assuming there are no objections to this, I can work on a PR.
/cc @mikemccand @jpountz

**Comment by mikemccand** [comment]
+1, thanks @mattweber
