### ISSUE TITLE
TransportClient fails with IllegalStateException when lucene-test-framework MVN dependency added

### ISSUE THREAD

**Issue by andrewwwooster** [elastic/elasticsearch#22494]
**Elasticsearch version**: 5.1.1

**Plugins installed**: []

**JVM version**: 1.8.0_111

**OS version**: Windows 7

**Description of the problem including expected versus actual behavior**:
My program uses a TransportClient and works fine, but when I add a lucene-test-framework dependency it fails with the following error:
```
java.lang.IllegalStateException: running tests but failed to invoke RandomizedContext#getRandom
	at magellan.es5.SimpleTest.testTransportClient(SimpleTest.java:17)
Caused by: java.lang.reflect.InvocationTargetException
	at magellan.es5.SimpleTest.testTransportClient(SimpleTest.java:17)
Caused by: java.lang.IllegalStateException: No context information for thread: Thread[id=1, name=main, state=RUNNABLE, group=main]. Is this thread running under a class com.carrotsearch.randomizedtesting.RandomizedRunner runner context? Add @RunWith(class com.carrotsearch.randomizedtesting.RandomizedRunner.class) to your test class. Make sure your code accesses random contexts within @BeforeClass and @AfterClass boundary (for example, static test class initializers are not permitted to access random contexts).
	at magellan.es5.SimpleTest.testTransportClient(SimpleTest.java:17)
```

It seems like requiring randomizedtesting just to run a TransportClient is a little onerous.

**Steps to reproduce**:
 1.  See attachment.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by andrewwwooster** [comment]
[es5 TransportClinet IllegalStateException.zip](https://github.com/elastic/elasticsearch/files/692741/es5.TransportClinet.IllegalStateException.zip)

**Comment by s1monw** [comment]
wait, you are adding lucene test framework which has a dep on randomized runner, otherwise we'd not try to load the class. Yet, what are you using of the test framework in your application? If you don't use RR you can exclude it's dep? I am not saying the error is right but It might just be wrong usage of the TransportClient in your tests?

**Comment by andrewwwooster** [comment]
To explain:
Some of my tests use the TransportClient, but are not based on the randomizedtesting.
Some separate analyzer tests use the Lucene test framework's assertTokenStreamContents(), due to these I included a dependency on  lucene-test-framework.  The moment I included this dependency the TransportClient broke.

My sense was that the randomizedtesting approach was recommended, but not required.  This dependency seems to make it required.

**Comment by s1monw** [comment]
I am not sure if you can have the best of all worlds. this setup looks very special since you are depending on RandomizedRunner but you don't initialize it properly. I think you should initialize it then stuff will work.

**Comment by s1monw** [comment]
@andrewwwooster just to clarify you are talking about the test setup not production, right?

**Comment by amirhmd** [comment]
Hey guys, sorry, is there any body who could help me getting started with contributing to this project? i am very looking forward to contributing in this project but I am new and i am not very high in experience.

**Comment by s1monw** [comment]
no feedback - closing
