### ISSUE TITLE
ES5.11 Failed to start with Windows Server 2012

### ISSUE THREAD

**Issue by javasec** [elastic/elasticsearch#22506]
es5.11 %JAVA% it doesn't work in Windows Server 2012 ,but win7 looks like there is no such problem.
SET JAVA="%JAVA_HOME%"\bin\java.exe
change %JAVA% to "%JAVA_HOME%\bin\java.exe" it work well.

**Comment by jasontedor** [comment]
Closed by #22132

**Comment by jasontedor** [comment]
This will be fixed in an eventual 5.1.2 patch release.
