### ISSUE TITLE
Document `must_not` context and scoring

### ISSUE THREAD

**Issue by swekaj** [elastic/elasticsearch#22518]
**Describe the feature**:
On the documentation page for the (bool)[https://www.elastic.co/guide/en/elasticsearch/reference/5.1/query-dsl-bool-query.html] query there is no mention that the `must_not` clause executes in a filter context and returns a constant score of `0`.  In fact, the only place I can find mention of this is a brief mention on the (query-filter context)[https://www.elastic.co/guide/en/elasticsearch/reference/5.1/query-filter-context.html] page.

That `must_not` uses a filter context can be a fairly important consideration when deciding how to structure a query, as such it should be, at a minimum, mentioned, and ideally explained in detailed.  Even something as simple as

> Clauses are executed in filter context meaning that scoring is ignored and clauses are considered for caching.  Because scoring is ignored, a score of `0` for all documents is returned.

**edit**: correction on what score is returned, I thought it was `1` initially as that's the score returned when just a `must_not` clause is specified.  Further testing leads me to believe that's because of an implicit `must` clause with a `match_all` query since if a `filter` clause or `must` clause with `constant_score` with `boost: 0` the score is reduced to `0`.

**Comment by clintongormley** [comment]
Thanks for opening this issue. Would you be interested in submitting a docs PR for this?

**Comment by swekaj** [comment]
Not at all, done.

**Comment by mayya-sharipova** [comment]
closing this issue, as this has already been implemented.
