### ISSUE TITLE
Consider introducing a global "size" parameter for delete-by-query

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#22522]
Today, the delete-by-query plugin version 2.4 uses a default `size` value configured directly in the source code that can be adjusted only with every request. The same applies for 5.x version of the API and `scroll_size`.

To eliminate the need of specifying custom values every time with each request, consider adding a globally default configurable parameter in `elasticsearch.yml` or a dynamically configurable one via cluster settings.

**Comment by clintongormley** [comment]
@astefan We don't have a globally configurable default for (eg) search `size`, inner hits, aggs etc.  Why would we add it for this?

**Comment by astefan** [comment]
@clintongormley  with such a global parameter configurable in `elasticsearch.yml` for example, any client code or application doesn't have to change and potentially be redeployed when this default customized value changes. One change will go on the "server" side and will be applied to any clients accessing the API or the plugin.

**Comment by clintongormley** [comment]
@astefan the same could be said for client applications - they can use a global config which each call references.  I hardly think that users are going to want to update these global defaults on a frequent basis.  I could see a purpose for a globally enforced maximum but not a global default.  We offer a good out of the box default, anything else should be configured in the client.
