### ISSUE TITLE
Pipeline aggregation: full histogram of an aggregation 

### ISSUE THREAD

**Issue by rcrezende** [elastic/elasticsearch#22537]
The thread on https://github.com/elastic/elasticsearch/issues/21962 went so fast that I couldn't discuss.

I understand the point and I can see the scalability issue if what is communicated with the coordinating node is the pair (thing_id, NumberActions).

a) But instead, if the reduce phase is each shard returning (NumberActions, count) or even better (with constant memory O(Percentile_Buckets * N_Shards)) the coordinating reduces on (Shard_Id, Sum(Actions), [(Percentile_Bucket, NumberActions)]),  then implementation is efficient.

b) If the current design forces the coordinating node always reduce on the parent bucket, then how about bootstrap: sample with replacement things_id, perform the percentiles_bucket, then repeat the process few iterations for better precision. 

I'd be happy with having support only for percentiles_bucket so assumptions can be made and the two approaches above are acceptable, although I prefer (a).

**Comment by markharwood** [comment]
>if the reduce phase is each shard returning (NumberActions, count)
> then implementation is efficient.

But inaccurate. It would fail to provide a globally accurate count for each thing as it loses the key to sum thing1's counts from multiple shards. Given the typical randomised routing of documents to shards each thing's reported global number of actions would be, roughly speaking, 1/numShards of its true value.

The problem keeps coming back to the age-old issue of attempting behavioural analysis of high-cardinality entities on an event-centric store where each entity's related events are scattered around a network. There's too much cost and resources involved in joining the related data together at query time so maintaining an entity-centric index where related data is indexed locally is the only sensible approach. 

>The thread on #21962 went so fast that I couldn't discuss.

This issue has been open a year without any discussion and I would suggest the same solution [proposed on the previous related issue](https://github.com/elastic/elasticsearch/issues/21962#issuecomment-265217574) so will close this.
