### ISSUE TITLE
Verify a registered repository in 6.0 does not contain incompatible data only

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#22535]
When a user upgrades to a 6.0 cluster, they must have done so from a 5.x cluster.  However, it is possible that the user upgraded from 2.x -> 5.x and then from 5.x -> 6.x without having registered their snapshot repository on the 5.x version.  This will mean that once the user is on a 6.x cluster, they will no longer be able to read their repository data from 2.x (as we only allow backward compatibility with the last major version).  We removed the ability to read all of the 2.x snapshot data from 6.x in #22004.

However, we could improve this situation by preventing a user from even registering a repository on 6.x if that repository contains no valid 5.x repository data (i.e. the `index-N` file) and in addition we detect the presence of 2.x data in the repository (through the presence of the old `index` file).  The presence of `index` and the absence of any `index-N` is an indication that the repository was never used in a 5.x cluster and was only used in a 2.x cluster.  Instead of creating a scenario where the repository data files could be deleted or silently dropping snapshots, we could fail to register the repository in such a situation so the user is alerted that their repository seems to only contain pre 5.x files.

**Comment by ywelsch** [comment]
Discussed with @tlrx: we prefer to close this issue as a clear indication that we are not going to work on it at this time. If anyone would like to implement this, we will be glad to provide help or assistance if needed.
