### ISSUE TITLE
link to configuration documentation in default elasticsearch.yml is broken

### ISSUE THREAD

**Issue by tadzys** [elastic/elasticsearch#22545]
**Elasticsearch version**: 5.1.1

**Plugins installed**: []

**JVM version**:1.8.0_112

**OS version**:Windows 8

**Description of the problem including expected versus actual behavior**:

Default config file has the following comments:

# Please see the documentation for further information on configuration options:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html>

the link is broken.

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jasontedor** [comment]
Thanks for reporting. This is unfortunate, and is why we try to avoid putting links in places like this, log messages, etc. The link you're looking for is now https://www.elastic.co/guide/en/elasticsearch/reference/5.1/settings.html.

**Comment by clintongormley** [comment]
Fixed in 2ec5deef089723885dc76462c68b953f3af364ca
