### ISSUE TITLE
Reenable LiveVersionMapTests.testRamBytesUsed on JDK9

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#22548]
I've disabled `LiveVersionMapTests.testRamBytesUsed` for JDK9 on branches master, 5.x and 5.2 for now. Needs to be re-enabled once we have a Lucene release where RamUsageTester works under JDK 9.

**Comment by jasontedor** [comment]
I looked into reenabling this test on JDK 9. Now the test can execute successfully, but it fails on the last assertion. @jpountz has graciously agreed to investigate.
