### ISSUE TITLE
Unable to start elasticsearch-5.1.1 

### ISSUE THREAD

**Issue by Gaurav2Github** [elastic/elasticsearch#22542]
**Elasticsearch version**: 5.1.1

**Plugins installed**: [x-pack]

**JVM version**:

openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode)

**OS version**:
RHEL 7.2

**Description of the problem including expected versus actual behavior**:
Followed steps [Install Elasticsearch with .zip or .tar.gz]( https://www.elastic.co/guide/en/elasticsearch/reference/5.1/zip-targz.html#zip-targz)
**Steps to reproduce**:
 1. Install OpenJDK [java-1.8.0-openjdk]
 2. Unarchived elasticsearch binary to install location
 3. Change install location ownership to unique user and group [elkusr:elkgrp]
 4. Update /etc/security/limits.conf
     - 'elkusr    -        nofile      65536'
     - 'elkusr    soft   memlock unlimited'
     - 'elkusr    hard memlock unlimited'
     - 'elkusr    soft  nproc       2048'
     - 'elkusr    hard nproc      2048'
 5. Update /etc/sysctl.conf  and reload systemctl
     - 'vm.max_map_count = 262144'
     - 'vm.swappiness = 0'
 6. Installed x-pack plugin from binary
    - elasticsearch/bin/elasticsearch-plugin install file:///tmp/x-pack-5.1.1.zip
 7. Update elasticsearch.yml configuration
    - cluster.name: "elk_cluster"
    - node.name: "test_vm_1"
    - path.data: "/var/data/elasticsearch" 
    - path.logs: "/var/log/elasticsearch"
    - bootstrap.memory_lock: true 
    - network.host: "10.100.0.5"
    - discovery.zen.ping.unicast.hosts: ["test_vm_1", "test_vm_2"]
    - discovery.zen.minimum_master_nodes: 2
 8. no change done to jvm.options or log4j.properties config.
 9. Create service for elasticsearch
    -  [/etc/systemd/system/elasticsearch.service](https://gist.github.com/Gaurav2Github/4e9b27719f5d560129f40da656b5f456)
 10. Start elasticsearch service
**Provide logs (if relevant)**:
elasticsearch created no logs for this.
```
service elasticsearch status
Redirecting to /bin/systemctl status  elasticsearch.service
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/etc/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2017-01-11 13:51:09 NZDT; 1s ago
     Docs: http://www.elastic.co
  Process: 26496 ExecStart=/opt/elasticsearch/bin/elasticsearch -Des.pidfile=${PID_DIR}/elasticsearch.pid -Des.default.path.home=${ES_HOME} -Des.default.path.logs=${LOG_DIR} -Des.default.path.data=${DATA_DIR} -Des.default.path.conf=${CONF_DIR} (code=exited, status=64)
 Main PID: 26496 (code=exited, status=64)
```

I even tried to execute elasticsearch directly, I got this warning and stopped:
```
/opt/elasticsearch/bin/elasticsearch
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N

```
Any advise?

**Comment by jasontedor** [comment]
> OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N

This is a non-issue. It's a from OpenJDK vendors applying a patch to enable `-XX:+AssumeMP` by default. You can disable it and remove this warning message by adding `-XX:-AssumeMP` to jvm.options.

> `Main PID: 26496 (code=exited, status=64)`

This indicates a command-line usage error.

Looking at your command-line:

>`/opt/elasticsearch/bin/elasticsearch -Des.pidfile=${PID_DIR}/elasticsearch.pid -Des.default.path.home=${ES_HOME} -Des.default.path.logs=${LOG_DIR} -Des.default.path.data=${DATA_DIR} -Des.default.path.conf=${CONF_DIR}`

This is not the correct syntax. You need to use `-E` for these options, and drop the `es.` prefixes.

Also, why use an archive distribution to install, why not use the RPM which will setup the service for you?

If you need additional help, please open an issue on the [forum](https://discuss.elastic.co). Elastic reserves GitHub for verified bug reports and feature requests.

**Comment by Gaurav2Github** [comment]
Thanks for the advise. 
I have corrected it now.
Free memory was low. Increasing it fixed the issue.
Using RPM is anytime better option to use.
