### ISSUE TITLE
source filtering (_source) field matching too loose

### ISSUE THREAD

**Issue by jacob87o2** [elastic/elasticsearch#22557]
**Elasticsearch version**:  `5.1`

**Plugins installed**: none

**JVM version**: 
```
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```
**OS version**: `Ubuntu 14.04.1 LTS`

**Description of the problem including expected versus actual behavior**:

I don't know if this is a bug or a feature, but in my opinion it shouldn't work like that.

When filtering source (`_source`), there are returned fields that contain only part of the string.

Let's say we have source object looking like this: 
```
{
    "photos": ["a.jpg", "b.jpg"],
    "photosCount": 2
}
```
When filtering like this: `"_source": ["photosCount"]`, `photos` field is also returned.
(same for `"_source": "photosCount"` and `"_source": {"include": ["photosCount"]}`)
Now I have to explicitly exclude `photos`, for not having it in response.

**Steps to reproduce**:

 1.
```
curl -XPOST 'localhost:9200/some_thing/some_type' -d '
{
    "photos": ["a.jpg", "b.jpg"],
    "photosCount": 2
}
```
 2.
```
curl -XPOST 'localhost:9200/some_thing/some_type/_search?pretty' -d '
{
  "_source": "photosCount",
  "query": {}
}
```

**Comment by clintongormley** [comment]
May be related to https://github.com/elastic/elasticsearch/pull/20736

**Comment by clintongormley** [comment]
@mikemccand Could you take a look at this please? I think the automaton change in #20736 has a bug

**Comment by nik9000** [comment]
I just confirmed in master with this:
```
POST /some_thing/some_type
{
    "photos": ["a.jpg", "b.jpg"],
    "photosCount": 2
}

POST /some_thing/some_type/_search?pretty
{
  "_source": "photosCount"
}
```

**Comment by mikemccand** [comment]
I'll have a look @clintongormley
