### ISSUE TITLE
Cannot see DevTools (console) on using a created user

### ISSUE THREAD

**Issue by iyerabhi07** [elastic/elasticsearch#22555]
Hi I am using ELK 5.1.1 and I installed x-pack plugin at ElasticSearch and Kibana. 
I created a new user from the management console, assigned it a role to be able to just read an index that I created.
But on logging in to Kibana with that user, I am not able to see the DevTools (console) to run any queries.
Kibana and ElasticSearch are connected, I have updated Kibana credentials at the yml file.

**Comment by jasontedor** [comment]
Please open this issue in the Kibana repository.
