### ISSUE TITLE
Forbids scroll query that sets size to 0

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#22552]
A scroll query like the following:
````
POST _search?scroll=1m
{
  "size": 0
}
````
... returns no hit but subsequent queries with the returned scroll id will replay the entire query even though there is no hits to return.
It would be better to throw an exception on the initial query in order to forbids scroll query with `size:0`. 

Relates #22500

**Comment by nik9000** [comment]
Makes sense to me. We allow `-1` because that means "all". And we allow `0` for regular search because that means "none" but "none" doesn't make sense with scroll.

**Comment by jpountz** [comment]
+1

**Comment by liketic** [comment]
Hi @jpountz Is this still worth to contribute? Thanks.
