### ISSUE TITLE
ES high load after 2017-01-01 00:00:00(UTC)

### ISSUE THREAD

**Issue by chixuan777** [elastic/elasticsearch#22582]
Hi, 
We have 5 nodes in the es cluster.(es2.1.1 on centos7 3.10.0-327.3.1.el7.x86_64)
After 2017-01-01 00:00:00(UTC), one of the nodes got a very high cpu load.
Nothing helped after we restart the es-jvm.
We checked that the cpu interruption is very high during that time.
When we restart the os, the cpu load and the interruption are very low.

We thought that it was caused by the "leap second" problem. But the os version is very new...

So any one faced the same problem?

**Comment by jasontedor** [comment]
If it's only one node, it's probably not a leap second issue. In the future, you could take a stack dump or use hot threads to see what the node was doing. For general discussion, please open a topic on the [forum](https://discuss.elastic.co). Elastic reserves GitHub for verified bug reports and feature requests.
