### ISSUE TITLE
Problem with client-side plugin development (TransportInterceptor usage with TransportClient, Transport intercepror does not support DI)

### ISSUE THREAD

**Issue by pkalinkina** [elastic/elasticsearch#22585]
We have a plugin, that on client-side(TransportClient) adds headers to each request.
It was developed for Elasticsearch version 2.3.5 with overriding TransportService.sendRequest()
(extending class held objects, managed by guice) and adding new TransportService to the
plugin with onModule(TransportModule module).

Now we are trying to update to 5.1.1 version and TransportService.sendRequest() is final.
Our plugin now extends NetworkPlugin and we tried to implement TransportInterceptor interface 
to intercept all requests, but to add custom headers  we need Guice-managed class and access 
to Threadpoll to get Threadcontext. 

Can you advice on how to handle this situation?

**Comment by s1monw** [comment]
I think for this you should use `FilterClient` and override `doExecute` like this:

```Java
void doExecute(action, request, listener) {
        final ThreadContext threadContext = threadPool().getThreadContext();
        final ThreadContext.StoredContext storedContext = threadContext.newStoredContext();
        try (ThreadContext.StoredContext ctx = threadContext.stashContext()) {
            threadContext.putHeader("foo", "bar"); // add your header...
            super.doExecute(action, request, listener);
        }
}
```

**Comment by pkalinkina** [comment]
But if I want to define all functionality in plugin an use client like this:
`TransportClient client = new PreBuiltTransportClient(settings, AuthenticationPlugin.class)`

**Comment by s1monw** [comment]
> But if I want to define all functionality in plugin an use client like this:
TransportClient client = new PreBuiltTransportClient(settings, AuthenticationPlugin.class)

you can also get the ThreadPool in the plugin from `createComponents` and then use is with a transport interceptor.

**Comment by pkalinkina** [comment]
But `createComponents ` is not used inside of `TransportClient `

**Comment by s1monw** [comment]
oh true, then you have to go through FilterClient. that is the intended way to solve this. that's what it was added for

**Comment by Gordiychuk** [comment]
@s1monw offered solution looks like work around, the main problem that  `TransportInterceptor` not support DI, it's lead to many problem when whole dependency located inside DI but one of class required it an can't access without static hacks. I have example of this hack:
https://github.com/floragunncom/search-guard/blob/5.1.1/src/main/java/com/floragunn/searchguard/SearchGuardPlugin.java#L252
https://github.com/floragunncom/search-guard/blob/5.1.1/src/main/java/com/floragunn/searchguard/transport/SearchGuardInterceptor.java#L74

Maybe we can provide ability loockup interceprots from DI?

**Comment by s1monw** [comment]
Google Guice is about to removed and TransportClient will be removed in upcomeing versions. We won't add stuff like TransportInterceptors to guice. There is a clear way forward by using FilterClient for this.

**Comment by Gordiychuk** [comment]
What will be use instead of guice for provide DI? What will be official way to create client that provide access to elaticsearch? Right now FilterClient looks like delegator. As a result our clients should create manually some wrapper class instead of specify list plugins.

**Comment by s1monw** [comment]
you can just subclass FilterClient and automatically install your plugin there. then you have a dedicated client. We won't use DI in the future it's a disaster from SW engineering perspective and makes encapsulation impossible. We will work towards providing relevant abstractions and extensions points. Most of the plugins don't use DI anymore.

**Comment by Gordiychuk** [comment]
It's future plans or we already rewrites this code? I thinks it will required a lot of rewrite code inside elasticsearch and for all clients. If it's takes much time, maybe fix this problem for current version instead of add WA for plugin owners? I can provide PR.

**Comment by s1monw** [comment]
@Gordiychuk what problem are you talking about? I don't see why you can't use a FilterClient?

**Comment by Gordiychuk** [comment]
Because API looks not consistent, users should specify list of plugins, but instead of that user will specify list of plugin plus our implementation of FilterClient. 

It will not work, when i have an application that is configured outside by user and if user decides to omit security for ealsticsearch. Now all we have to do is omit our plugin from the list of plugins. But if we use FilterClient that acts as our plugin(intercepts requests) and has Client that has all others plugins, this looks strange.

Offered solution with override `doExecute` does not cover case when it's necessary too intercept each request because delegated client does not execute overriden method(doExecute), it out case it means that all regular request will works correctly because execute flow looks like `User->AuthPlugin(extends FilterClient)->doAction->doExecute(plus our logic)->TransportClient->TransportService->Netty` in doExecute we inject all required headers, but internal request like health check etc will fail because internal request go through TransportService or TransportClient directly.

**Comment by s1monw** [comment]
if you want to inject a set of headers with every request you can do this via settings. like this:

```Java

Settings settings = Settings.builder().put("request.headers.your.custom.auth.header", authHeader).build();
```

your plugin can do that as well there is no need to intercept requests.

**Comment by pkalinkina** [comment]
But if I want to change this header later I still will have to use `ThreadContext` and `FilterClient`?

**Comment by s1monw** [comment]
> But if I want to change this header later I still will have to use ThreadContext and FilterClient?

correct. what is your usecase for this?

**Comment by pkalinkina** [comment]
Usecase for updating authorization header: I'm implementing OAuth2 and if an access token is no longer valid we have to refresh it.

**Comment by pkalinkina** [comment]
Usecase for updating authorization header: 
We are implementing OAuth2 with client credentials authorization flow.
We specify client credentials in Settings for `TransportClient `and  our plugin aquares token from Identity Provider, stores it and inserts token in header of each outcoming request. If token is no longer valid, it is updated via Identity Provider.
To do so, we have to be able to intercept and change headers of all the outcoming request from Client inside the installed plugin.  And for that we need to have some dependecies from DI (`ThreadContext` and our custom dependenies) in `TransportInterceptor `class (in 5.1.1 version of elasticsearch we don't have this ability)

**Comment by s1monw** [comment]
one think I think that makes sense is to make a change like this:
```diff

diff --git a/core/src/main/java/org/elasticsearch/plugins/NetworkPlugin.java b/core/src/main/java/org/elasticsearch/plugins/NetworkPlugin.java
index 991a21f..eb89daa 100644
--- a/core/src/main/java/org/elasticsearch/plugins/NetworkPlugin.java
+++ b/core/src/main/java/org/elasticsearch/plugins/NetworkPlugin.java
@@ -27,6 +27,7 @@ import org.elasticsearch.common.io.stream.NamedWriteableRegistry;
 import org.elasticsearch.common.network.NetworkService;
 import org.elasticsearch.common.settings.Settings;
 import org.elasticsearch.common.util.BigArrays;
+import org.elasticsearch.common.util.concurrent.ThreadContext;
 import org.elasticsearch.common.xcontent.NamedXContentRegistry;
 import org.elasticsearch.http.HttpServerTransport;
 import org.elasticsearch.indices.breaker.CircuitBreakerService;
@@ -43,7 +44,7 @@ public interface NetworkPlugin {
      * Returns a list of {@link TransportInterceptor} instances that are used to intercept incoming and outgoing
      * transport (inter-node) requests. This must not return <code>null</code>
      */
-    default List<TransportInterceptor> getTransportInterceptors(NamedWriteableRegistry namedWriteableRegistry) {
+    default List<TransportInterceptor> getTransportInterceptors(NamedWriteableRegistry namedWriteableRegistry, ThreadContext context) {
         return Collections.emptyList();
     }
```

that way you have the thread context in the interceptor and can set headers as you like?

**Comment by Gordiychuk** [comment]
Yes, this solution will works for us. Thanks.
