### ISSUE TITLE
Sort order sometimes is case sensitive, sometimes not

### ISSUE THREAD

**Issue by sergpsu** [elastic/elasticsearch#22583]
Following construction supports case insensitive DESC/desc order
```"sort":{"field":"DESC"}```

but

```"sort":{"field":{"order":"DESC"}}```

gives an error

```Sort order [DESC] not supported.```

I'm using v5.0.0

**Comment by jimczi** [comment]
Thanks for the report @sergpsu 
This is fixed in v5.1 which now accepts upper/lower case order.
