### ISSUE TITLE
[Regression] Template validation doesn't take into account template hierarchy ("order")

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#22580]
Consider the following scenario:

`default.json` defines some mappings for common fields and/or dynamic mapping shared by all indices in a cluster. Specifies order 1 and `template:*`.
`default_en.json` defines language specific mappings for fields, e.g. `{ "content": {"analyzer":"myenglish"}}`. Specifies order 2 and `template:*_en`.
`articles_en.json` defines articles mappings for the English language, and is using the `myenglish` analyzer defined on a previous template. Specifies order 3 and `template:english_en`.

Before v5 it worked because all templates were added, and only parsed, validated and applied on the event of index creation, using the order of precedence and applied along with the rest of the matching templates.

On v5 you will get the following error when putting articles_en.json : `MapperParsingException[analyzer [myenglish] not found for field [myfield]]` because it's been evaluated in isolation without taking other templates and index names into account.

This is a regression from pre-v5 versions, and in addition is not documented anywhere.

Presumably relates to #8802 (apriori correctness validation vs actually testing using temp index creation). It would be nice to keep template validation (which is great feature!) but also take into account related templates (based on index creation). I'm aware it isn't trivial to do, but important for real-world usages of templates.

**Comment by clintongormley** [comment]
Closing in favour of #21105

**Comment by synhershko** [comment]
Always one step ahead :)

Can I suggest this pitfall is documented somewhere? was kinda of a head scratching moment when upgrading a client system to 5
