### ISSUE TITLE
Remove signer setting in aws plugins

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#22599]
We have a `signer` setting in our aws plugins, which overrides the signing type used to sign aws requests. However, this is _completely_ untested, and is only needed for third party aws replacement apis like ceph. I think we should remove this setting, since it is untested and unsupported, and let the community fork the plugins to customize them for ceph, if there is demand.

**Comment by dadoonet** [comment]
Agreed.

**Comment by clintongormley** [comment]
This is a breaking change so let's do it for 6.0 only (and deprecation logging for 5.x)
