### ISSUE TITLE
Move DeleteByQuery helper classes from reindex module to core

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#22616]
today if a plugin needs DBQ functionality they include / depend on the reindex jar. This is really bad since it's not intended to be a dependency of another plugin. Yet, DBQ is useful in some situations and it can easily be used without all the request / response classes. We should have a static helper class that does all the heavy lifting for us in core and them do the exposure in the reindex module.

@nik9000 can you take a stab at this?

**Comment by nik9000** [comment]
I can have a look at this, sure.
