### ISSUE TITLE
Make headers case-insensitive

### ISSUE THREAD

**Issue by mayyamus** [elastic/elasticsearch#22623]
**Elasticsearch version**:all

**Plugins installed**: []

**JVM version**:all

**OS version**:all

**Description of the problem including expected versus actual behavior**:
perhaps setHeaders method can't override default header  in RestClient, because httpHeader names are case-insensitive.suggest converting  all default header and request header names to lowercase/uppercase.

![diff](https://cloud.githubusercontent.com/assets/24735504/21955372/f06fdf9e-daa4-11e6-8caf-0dcb51641d0c.png)

**Comment by adityasrini** [comment]
I’d like to take this up if no one is already working on this or has been assigned to this.

**Comment by javanna** [comment]
go ahead @adityasrini thanks!

**Comment by javanna** [comment]
given that we have decided (see #30616) to remove support for default headers, as they are already supported by the apache http client which we use to perform requests, I am going to close this.
