### ISSUE TITLE
function_score with replace boost_mode not replacing query scores of zero

### ISSUE THREAD

**Issue by davidbkemp** [elastic/elasticsearch#22629]
**Elasticsearch version**: 5.1.2

**Plugins installed**: []

**JVM version**: 1.8.0_92

**OS version**: OS X Yosemite 10.10.5

**Description of the problem including expected versus actual behavior**:

When performing a `function_score` query with `boost_mode` set to `replace`, the query is supposed to ignore the scores of the query component of the `function_score` query and only use the scores given by the functions.  Instead, for some queries, Elasticsearch is (incorrectly) giving scores of zero.

**Steps to reproduce**:
 1. Execute the following curl commands:

```
curl -XPOST "http://localhost:9200/test/test" -d'
{
  "description": "banana",
  "date": "2016-01-01"
}'

curl -XGET "http://localhost:9200/test/test/_search" -d'
{
  "query": {
    "function_score": {
      "boost_mode": "replace",
      "score_mode": "max",
      "query": {
        "bool": {
          "filter": [
            {
              "range": {
                "date": {
                  "gte": "2016-01-01"
                }
              }
            }
          ]
        }
      },
      "functions": [
        {
          "weight": 3,
          "filter": {
            "match": {
              "description": "banana"
            }
          }
        }
      ]
    }
  }
}'
```

 2. Note how the score is 0 when it should be 3.

```
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 0,
    "hits": [
      {
        "_index": "test",
        "_type": "test",
        "_id": "AVmhFx-cux_TRkqjzbdy",
        "_score": 0,
        "_source": {
          "description": "banana",
          "date": "2016-01-01"
        }
      }
    ]
  }
}
```

**Provide logs (if relevant)**:
N/A

**Comment by jimczi** [comment]
Thanks for the bug report @davidbkemp 
The bug is fixed for the next minor release 5.2:
https://github.com/elastic/elasticsearch/issues/22138
