### ISSUE TITLE
Sudden loss of all indices data

### ISSUE THREAD

**Issue by cortopy** [elastic/elasticsearch#22635]
**Elasticsearch version**: 5.0.1

**Plugins installed**: []

**JVM version**: OpenJDK 1.8.0

**OS version**: Alpine Linux 3.4 / Kubernetes 1.4

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. As per the logs below, an index was created at midnight (by Logstash). This is the normal behaviour to be expected
 2. However, about four hours later, the same index had to be recreated up to 10 times
 3. Following that event, all indices were wiped out. Now, only data from that time remains in the cluster. All data from persistent storage was deleted too.

**Provide logs (if relevant)**:

There are ten logs after 04:00 of type:

```
 Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started[myindex][0])
```

followed by one entry each of `update mapping`

**Comment by clintongormley** [comment]
Sorry to tell you @cortopy but it looks like your ES cluster is exposed to the internet and you have been hacked. See https://www.elastic.co/blog/protecting-against-attacks-that-hold-your-data-for-ransom
