### ISSUE TITLE
Expose BooleanSimilarity

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#22630]
This similarity scores only based on query boosts and the number of matching clauses. https://github.com/apache/lucene-solr/blob/master/lucene/core/src/java/org/apache/lucene/search/similarities/BooleanSimilarity.java

**Comment by aravindputrevu** [comment]
Can i work on that ? @clintongormley  @jpountz

**Comment by jpountz** [comment]
@aravindputrevu Sure, feel free to work an a PR and ping me if you need help. You can look at how other similarities are plugged in to get started.

**Comment by aravindputrevu** [comment]
@jpountz  How to build the source ? i installed the latest Gradle plugin and using Intellij !
BTW there are many modules which module should i build ?

Thanks in advance.

**Comment by aravindputrevu** [comment]
Can someone help me in doing the setup ?

**Comment by jpountz** [comment]
@aravindputrevu I dn't know about intellij, but running `gradle idea` should create configuration files that Intellij can understand. Regarding the modules directory, I think there might be a misunderstanding as building them is not optional. This folder should really be regarded as another source folder.

**Comment by jpountz** [comment]
I just noticed there was already an issue open for integrating this similarity: closing in favour of #6731.
