### ISSUE TITLE
"Visualize: Fielddata is disabled on text fields by default."

### ISSUE THREAD

**Issue by rootAmeen** [elastic/elasticsearch#22633]
Hi guys,
I recently started a new setup of ELK stack based on version 5.1. Everything went smoothly except for the visualization section on Kibana. Whenever I try to create something (like a visual of beat.name), I get the error message: 
> Visualize: Fielddata is disabled on text fields by default. Set fielddata=true on [beat.name] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.

I'm currently using filebeat to ship all my log messages, and I've checked the official documentation and came across this link: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/fielddata.html

I tried to apply it on my setup but I just can't figure out what exactly to put in the curl statement to reflect this change on logs.  What should I relpace "/my_index/_mapping/my_type" with? 

I appreciate your help.

Thanks.

**Comment by dadoonet** [comment]
Please ask questions on discuss.elastic.co where we can help.

**Comment by rootAmeen** [comment]
Hi @dadoonet. I already posted twice there but got 0 responses, that's why I thought about posting here :)

**Comment by clintongormley** [comment]
@rootAmeen Did you try searching?  If so you would have found this: https://github.com/elastic/elasticsearch/issues/15267#issuecomment-183746431
