### ISSUE TITLE
我想改同义词从数据库中获取 如何改

### ISSUE THREAD

**Issue by hehongju** [elastic/elasticsearch#22632]
**Elasticsearch version**:

**Plugins installed**: []

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by dadoonet** [comment]
Please ask your question on discuss instead.

https://discuss.elastic.co/c/in-your-native-tongue/46-category
