### ISSUE TITLE
MappedFieldType.rangeQuery should rewrite to an `exists` query when both bounds are open

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#22640]
Queries that have both bounds open can be generated even if the user passed explicit bounds due to query rewriting. Unfortunately, queries that have both bounds open are still costly to execute, so we should look into using `exists` queries instead (or even `match_all` queries if all docs have a value for the field).

**Comment by AnnaGMiguel** [comment]
Hello @jpountz, I'm looking for my first contribution to elasticsearch.
I'm familiarizing myself with the code base.

**Comment by jpountz** [comment]
@AnnaGMiguel Sorry for the late reply, I just saw your message. If you are looking for help to get started, you can look at the RangeQueryBuilder class.
