### ISSUE TITLE
Mapping support for treating JSON keys as data values

### ISSUE THREAD

**Issue by benjismith** [elastic/elasticsearch#22644]
**Describe the feature**: I'd like to design an Elasticsearch schema to handle cases where JSON keys are used as data values, rather than the current mechanism, which only supports treating JSON keys as a part of the schema.

For example, I'd like to load the [Hedonometer Dataset](http://hedonometer.org/words.html) (a list of ten thousand words and their crowdsourced "happiness" scores) into a "dictionary" object in my application. The JSON for the dictionary object would look like this:

```
{
  "name" : "hedonometer",
  "source" : "http://hedonometer.org/words.html",
  "words" : {
    "laughter" : { "score" : 8.5, "stdev" : 0.93 },
    "happiness" : { "score" : 8.44, "stdev" : 0.97 },
    "love" : { "score" : 8.42, "stdev" : 1.10 },
    ... 9,997 more lines ...
  }
}
```

This kind of data structure works best for my application, because it gives me O(1) hash-table lookup of entries by their dictionary word. However, I'd also like to store those dictionaries in Elasticsearch, with the list of words as a `nested object` field, but this presents me with a bit of a dilemma...

Elasticsearch will interpret this document as though there were ten-thousand different fields in its schema. That's not what I want.

I want the JSON object keys to be implicitly treated as a field named `word` in a nested schema of dictionary words.

Right now, the only way to do this is to change my JSON documents so they look like this instead:

```
{
  "name" : "hedonometer",
  "source" : "http://hedonometer.org/words.html",
  "words" : [
    { "word" : "laughter", "score" : 8.5, "stdev" : 0.93 },
    { "word" : "happiness", "score" : 8.44, "stdev" : 0.97 },
    { "word" : "love", "score" : 8.42, "stdev" : 1.10 },
    ... 9,997 more lines ...
  ]
}
```

But I now I can't do O(1) lookups of dictionary words in my application, and I'd rather not have to transform my JSON back and forth whenever I store it in Elasticsearch and retrieve it for my application.

So I'm proposing a new `key_transform` schema-design mechanism, whereby a JSON object's keys can be treated as values (with an implicit field name) in the body of an embedded tuple. 

For example, the schema for my "dictionary" object would be written like this:

```
{
  "properties": {
    "name": { "type": "string" },
    "source": { "type": "string" },
    "words": {
      "type" : "nested",
      "key_transform" : "word",
      "properties" : {
        "word" : { "type": "string" },
        "score" : { "type": "float" },
        "stdev" : { "type": "float" }
      }
    }
}
```

The `key_transform` property would only apply to nested mappings, with its value providing the field name of the string field which would receive the object key as its value.

I'd also like to propose the logical counterpart, a `val_transform` mechanism, so that a simple key/val object could be indexed according to a simple two-field nested mapping. For example, if I only need to index a single numeric value per dictionary word, my JSON might look like this:

```
{
  "name" : "hedonometer",
  "source" : "http://hedonometer.org/words.html",
  "words" : {
    "laughter" : 8.5,
    "happiness" : 8.44,
    "love" : 8.42,
    ... 9,997 more lines ...
  }
}
```

...which would transform both the JSON keys and values, to conform with a mapping like this:

```
{
  "properties": {
    "name": { "type": "string" },
    "source": { "type": "string" },
    "words": {
      "type" : "nested",
      "key_transform" : "word",
      "val_transform" : "score",
      "properties" : {
        "word" : { "type": "string" },
        "score" : { "type": "float" }
      }
    }
}
```

It would be illegal to use a `val_transform` property without also using `key_transform`.

It would also be illegal to use `key_transform` to map into non-string fields.

It would be an indexing error to submit a JSON document into a `val_transform` mapping, if the document's JSON values are incompatible with the data types of the `val_transform` field.

**Comment by jpountz** [comment]
That would be a huge change of how document parsing works, so I don't think we will be keen to implement this as the message we are trying to spread is rather that documents should be designed based on the queries that will be run.

By the way, are you sure you will want to index those words as nested docs? I can't tell since I'm not sure how you will leverage this dataset, but I'm wondering there might be more interesting things to do by indexing words as documents, ie. one document per word that would look like this:

```
{
  "name" : "hedonometer",
  "source" : "http://hedonometer.org/words.html",
  "word" : "laughter",
  "score" : 8.5,
  "stdev" : 0.93
}
```

**Comment by clintongormley** [comment]
> That would be a huge change of how document parsing works, so I don't think we will be keen to implement this as the message we are trying to spread is rather that documents should be designed based on the queries that will be run.

+1

The document in Elasticsearch should reflect how fields are indexed.  What you are describing is firmly in the realm of an ORM (ie application side).
