### ISSUE TITLE
Highlight feature does not work

### ISSUE THREAD

**Issue by vsizov** [elastic/elasticsearch#22642]
I'm just following https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html and it does not work. I suppose I'm doing something wrong, but anyway, something has to be done about this as I just follow samples from docs.

**Elasticsearch version**:
5.1.2 and 5.0.2

**Plugins installed**: []

**JVM version**:
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
**OS version**:
Mac OS Sierra, direct installation and as an official docker image (so linux alpine)

**Description of the problem including expected versus actual behavior**:

Highlight feature does not work. I tried examples from Elasticsearch reference and my own samples

**Steps to reproduce**:
 1.

```
PUT twitter/tweet/1
{
    "user" : "kimchy",
    "post_date" : "2009-11-15T14:12:12",
    "message" : "trying out Elasticsearch"
}
```
 2.

```
GET /_search
{
    "query" : {
        "match": { "user": "kimchy" }
    },
    "highlight" : {
        "fields" : {
            "content" : {}
        }
    }
}
```

 3. Look at the output:

```
{
  "took" : 105,
  "timed_out" : false,
  "_shards" : {
    "total" : 10,
    "successful" : 10,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.30685282,
    "hits" : [ {
      "_index" : "twitter",
      "_type" : "tweet",
      "_id" : "1",
      "_score" : 0.30685282,
      "_source" : {
        "user" : "kimchy",
        "post_date" : "2009-11-15T14:12:12",
        "message" : "trying out Elasticsearch"
      }
    } ]
  }
}

```

**Provide logs (if relevant)**:

No logs

**Comment by jimczi** [comment]
Your query targets the `user` field and you try to highlight the `content` field. Check the `require_field_match` section which explains in details why and how a field gets highlighted:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html#field-match

The forum is usually a good place for question like this, we reserve Github for bugs and feature report:
https://discuss.elastic.co/c/elasticsearch

**Comment by vsizov** [comment]
As I already said I found this sample in the official documentation. Maybe it should be addressed then?

**Comment by clintongormley** [comment]
thanks @vsizov - fixed
