### ISSUE TITLE
Problem with manually specifying request headers for AbstractClient.prepareSearch()

### ISSUE THREAD

**Issue by pkalinkina** [elastic/elasticsearch#22658]
Hello,

Can you please give advice on the following situation: 
we have a plugin that on the server side filters request via custom headers. These headers are changeable (headers for OAuth2 authentication with token expiration).  And with a previous version of elasticsearch (2.3.5) we could have a client perform a searchRequest with manually added headers that are not stored after the request is processed. 
Example: `client.prepareSearch().putHeader("Authorization", "AccessToken")).get();`

This option is removed in current version (5.1.1)

We can state headers in `Settings `for `Client`, but in this case we can't change header later.

How can we add headers to request that are built with methods `client.prepar...()`

**Comment by javanna** [comment]
Headers can still be set per request as follows, but we changed how that can be done:

```
client.filterWithHeader(Collections.singletonMap("header", "value")).prepareSearch().get();
```
