### ISSUE TITLE
POM for org.elasticsearch.client:x-pack-transport:jar:5.1.2 is invalid

### ISSUE THREAD

**Issue by brackxm** [elastic/elasticsearch#22651]
The POM for org.elasticsearch.client:x-pack-transport:jar:5.1.2 is invalid, preventing maven from using its transitive dependencies.

Maven issues this warning:
> [WARNING] The POM for org.elasticsearch.client:x-pack-transport:jar:5.1.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

There is a related comment in #21435 about duplicate xml tags.

**Comment by clintongormley** [comment]
Related https://github.com/elastic/elasticsearch/issues/21758

**Comment by rjernst** [comment]
Fixed with #22664
