### ISSUE TITLE
Add option to disable source logging for search slow log 

### ISSUE THREAD

**Issue by animageofmine** [elastic/elasticsearch#22683]
**Describe the feature**:
Details in this thread: https://discuss.elastic.co/t/turn-off-source-for-slow-logs/71182

As far as I know, there is an option to disable source logging for indexing logs, however there is no way to disable source logging for search logs. We are right now logging indexing and search slow logs to fetch latency for both search and indexing queries. 

Example
The following exists

```
index.indexing.slowlog.source: 0 OR
index.indexing.slowlog.source: false

```
but the following configuration does not exist

```
index.search.slowlog.source: 0 OR
index.search.slowlog.source: false
```

Is it straight forward to add this feature? I was looking at the code and though it seemed like a simple change, I wasn't sure because the code (IndexSettings) is referenced a lot of times. I am willing to work on the change though if someone can give me a quick starter.

**Comment by animageofmine** [comment]
I was able to dig a little more into code and test it on my local box. The change seems to be working, hence I sent out a PR. Can someone please take a look?

**Comment by animageofmine** [comment]
@abeyad Would you mind taking a look or redirecting this to the right person? Thank you for your help!

**Comment by javanna** [comment]
From the discussion in #22685 . We want to allow disabling source logging (but not truncating it) in the search slowlog. Yet the change depends on #9669 .

**Comment by javanna** [comment]
@elastic/es-search-aggs

**Comment by shubhamjn** [comment]
Anyone planing to pick up this issue.
I have a use case where the slow logs are getting exception 

[es-d03-rm] [!!!org.elasticsearch.index.SearchSlowLog$SlowLogSearchContextPrinter@33d78e80=>org.elasticsearch.ElasticsearchException:com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name (context: Object)!!!]

This might be because the search request is pretty huge and is getting truncated, thereafter throwing an exception while parsing. 
This issue fix can help me working around this problem. I am willing to contribute as well.

**Comment by satyammittal** [comment]
Any update on this task? I guess a similar parameter like elastic provide for indexing source would be good.

**Comment by pgomulka** [comment]
we discussed this on a core-infra sync on 14th April
We concluded that we will not work on this.
The search request body is the crucial information that is needed to help identify the problem. 

Hiding the sensitive information from search slow logs will not help to address the main problem - which is the fact that the sensitive data is present in the cluster anyway. See the reasoning in https://github.com/elastic/elasticsearch/issues/47853#issuecomment-818754933

For the reasons above, I will close the issue. If you want to add more details, feel free to reopen and comment
