### ISSUE TITLE
X-Pack Monitoring - Index info is cached and is not updated.

### ISSUE THREAD

**Issue by aadicodes** [elastic/elasticsearch#22684]
**Elasticsearch version**: Version: 5.1.2, Build: c8c4c16/2017-01-11T20:18:39.146Z, JVM: 1.8.0_102

**Plugins installed**: []
Plugins directory: /usr/share/elasticsearch/plugins
discovery-ec2
- Plugin information:
Name: discovery-ec2
Description: The EC2 discovery plugin allows to use AWS API for the unicast discovery mechanism.
Version: 5.1.2
 * Classname: org.elasticsearch.plugin.discovery.ec2.Ec2DiscoveryPlugin
repository-s3
- Plugin information:
Name: repository-s3
Description: The S3 repository plugin adds S3 repositories
Version: 5.1.2
 * Classname: org.elasticsearch.plugin.repository.s3.S3RepositoryPlugin
x-pack
- Plugin information:
Name: x-pack
Description: Elasticsearch Expanded Pack Plugin
Version: 5.1.2
 * Classname: org.elasticsearch.xpack.XPackPlugin

**JVM version**: oracle JDK , JVM 1.8.0_102

**OS version**: Amazon Linux AMI release 2016.09

**Description of the problem including expected versus actual behavior**:
I have setup a 3 node ES 5.1.2 cluster and installed below plugins. As well , I installed Kibana 5.1.2 along with x-pack plugin.
I am currently using a 30 day free license. I used a python based load test generator available at below location to test this cluster.
https://github.com/logzio/elasticsearch-stress-test
This plugin creates bunch of indices and documents based on input params and finally after the test it removes all the indices and docs
it created. 

Problem : Besides successful cleanup at the end of each load test, when I view Monitoring section on Kibana, under Indices section I see list of indices
and their metrics shown in the table. But all the indices that were created during load test were deleted and does not exist in Elasticsearch anymore. 

I think its a defect and please fix the same.

Please let me know if you need additional details.

**Comment by clintongormley** [comment]
I believe that the indices will disappear as time moves on - it shows data for them because you're looking at a window of time during which the indices still existed.  

@pickypg could you confirm?

**Comment by pickypg** [comment]
The indices will disappear once the time window rolls past their existence. For example, if you have "Last 15 minutes", then it will disappear after the 15 minutes have passed from it being deleted. Similarly, if you have the Last hour selected, then it would stick around for an hour.

The status of the index should change to N/A to acknowledge that it's no longer available.
