### ISSUE TITLE
Turn off Security Manager if not possible to wrap code in doPrivileged()` block.

### ISSUE THREAD

**Issue by pkalinkina** [elastic/elasticsearch#22692]
Hello, 

In the current version of elasticsearch, the ability to turn off `Security Manager` via is removed and all permissions have to be directly stated in plugin-security.policy file.
But for our plugin we use a third party library that runs background threads (caffeine cache), and we get a security exception.

Do we still have the ability to turn off `Security Manager` somehow? Because we don't have an ability to wrap code that causing exception in` AccessController.doPrivileged()` block.

**Comment by jasontedor** [comment]
> Do we still have the ability to turn off `Security Manager` somehow?

No.

> Because we don't have an ability to wrap code that causing exception in` AccessController.doPrivileged()` block.

You can grant the permission globally. That is at your own risk though.

Please ask additional questions on the [forum](https://discuss.elastic.co); Elastic reserves GitHub for verified bug reports and feature requests.

**Comment by jasontedor** [comment]
If you do open a topic on the forum, please link to it here (and provide a full stack trace of the situation).
