### ISSUE TITLE
how to get the 'valid doc total' by _stats?

### ISSUE THREAD

**Issue by lanegg** [elastic/elasticsearch#22708]
GET /_stats
result:
"primaries": {
        "docs": {
          "count": 32,
          "deleted": 70
        },

deleted > count

Q1: How is the deleted calculated?
Q2: How is the 'valid doc total' calculated?

**Comment by jasontedor** [comment]
As explained in the issue template, GitHub is reserved for bug reports and feature requests. The best place to ask a general question is at the Elastic Discourse forums at https://discuss.elastic.co.
