### ISSUE TITLE
Introduce a better deprecation policy

### ISSUE THREAD

**Issue by trejkaz** [elastic/elasticsearch#22707]
From Elasticsearch 2 to Elasticsearch 5 (which really is only one major version up), many methods and classes were removed without warning.

As someone who is currently updating existing Elasticsearch 2 code to Elasticsearch 5, I am finding the current lack of a policy to be extremely difficult to work with.

The [documentation we did get](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_java_api_changes.html) has several places where it says something was removed without describing the replacement. In some cases, it has documented a class (InnerHitsBuilder) being enhanced, when as far as I can tell, it has been removed, and there is absolutely no mention of its removal, and certainly no mention of its replacement.

How I think it should be:
* For minor releases, nothing gets removed, only deprecated.
* For major releases, only already-deprecated things get removed.
* For anything which is deprecated, the `@deprecated` tag in the Javadoc properly documents the replacement.

It is of course acceptable to do this the Lucene way - on releasing 6.0, release a 5.99 with all the additional `@deprecated` markers for things which 6.0 has removed.

**Comment by dadoonet** [comment]
@trejkaz The fact is that there has never been a clear separation between elasticsearch the server and the client. All are coming from the same JAR.
So basically a contract has never been defined with java users about what is part of the client or what is not or what is shared by both of them.

I'm sure that all the efforts the team is doing ATM to write a [High Level REST client](https://github.com/elastic/elasticsearch/tree/master/client/rest-high-level) will allow hopefully such `@Deprecated` annotation usage and have smoother transitions. But this is still a WIP.

Although it's not part of the source code, we tried to document as much as we can the changes including in the Java API like here for example: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_java_api_changes.html but we might have missed some few things.

**Comment by trejkaz** [comment]
A REST client would resolve the other main beef I have with the API, which is that all I really wanted to do is update Lucene to v6... but then the dependency clashed, so I had to upgrade Elasticsearch... and now I'm in a mess.

**Comment by trejkaz** [comment]
Actually, I should probably say, we have some amount of plugin code as well, and I have been seeing similar things going on over there. Randomly a class or a field will disappear... and I'll read the breaking changes and there won't be any mention of it. I think that 90% of the changes I've had to do, I found the thing to do by digging up the commit from the git history of elasticsearch to find other usages of it and then following their example. But some of these things that elasticsearch itself wasn't even using have been a real challenge.

Lucene has a pattern of marking experimental and internal APIs with Javadoc tags, which usually alerts to the APIs you should probably stay away from. (That said, in the Lucene 6 release, even they completely removed methods in non-internal APIs, so...)

**Comment by dadoonet** [comment]
The main difference IMO is that Elasticsearch is not a library but a server. You are considering it here as a framework or a library.
Not the case.

Plugins needs to have a better contract probably as for now you can use whatever class you want from elasticsearch (the server). Like String utils class...
That's why you have this feeling I think.

**Comment by javanna** [comment]
> Plugins needs to have a better contract probably as for now you can use whatever class you want from elasticsearch (the server).

We have been working on clarifying the plugins api, as opposed to allowing plugins to extend pretty much anything. That has already improved a lot and allows us to break much less stuff for plugins. We also introduced the `breaking-java` label to highlight breaking changes for plugins.

As for the java api problems, we do have a low level REST client that doesn't depend on elasticsearch, but you need to write requests and read responses yourself, which is a bit too low level. We are working on a high level REST client that supports the same requests and responses that the java API supports, but that unfortunately means that it will still depend on the whole elasticsearch at least in the beginning, although it will send REST requests. See https://www.elastic.co/blog/state-of-the-official-elasticsearch-java-clients to know more.

**Comment by jasontedor** [comment]
In order of stability:
 - the REST API
 - the transport client API
 - the plugins API

The REST API is sacred, we are careful about deprecating, providing warning headers and logging, and removing only when appropriate.

The transport client API is fairly stable these days, but we do reserve the right to break it in minor releases (this happens rarely). This API will eventually be deprecated and completely removed. Related to this, APIs that support the transport client API are more likely to be stable than not, but change can happen here too and we try to document them.

We are working towards a stable plugins API, but we have a long way to go there. When this API is stable, we will provide a reasonable deprecation policy.

Beyond this, we reserve the right to break any accessible method on any public class at any time. Elasticsearch is not a general library, the above APIs are intended to the ones for public consumption, everything else is internal implementation details.

Someday we will be able to provide clear delineation between the above APIs and the APIs that we intend to be internal only. Until then, the above guidance is what we have to offer.
