### ISSUE TITLE
max_determinized_states in query_string is no longer supported

### ISSUE THREAD

**Issue by nomoa** [elastic/elasticsearch#22722]
We're upgrading client to elastic 5.1.2 and we noticed that the `max_determinized_states` is no longer accepted by the `query_string` query.

The following query is accepted by elastic 2.x:
```
curl localhost:9200/twitter/_search -d '{"query":{"query_string":{"query":"test", "max_determinized_states":10}}}'
```

But will fail on elastic 5.1.2 with:
```
"type":"parsing_exception","reason":"[query_string] query does not support [max_determinized_states]"
```

I don't think it's intentional because this option is still referenced in the documentation (and actually very useful).

**Comment by nik9000** [comment]
I can have a look in a bit.

**Comment by nomoa** [comment]
Thanks!

**Comment by nik9000** [comment]
Done @nomoa. If you want to work around it you can use `max_determined_states`. In 5.3 that'll emit a warning header telling you to use `max_determinized_states` instead. In 6.0 only `max_determinized_states` will be supported.

**Comment by nomoa** [comment]
Thank you Nik, this is perfect.
