### ISSUE TITLE
ElasticsearchUncaughtExceptionHandler] [] fatal error in thread [main], exiting java.lang.NoClassDefFoundError: org/elasticsearch/index/analysis/AnalysisModule$AnalysisBinderProcessor

### ISSUE THREAD

**Issue by guybarnea** [elastic/elasticsearch#22738]
thanks.
our plugin workes fine in version 2.3.5.
we have to make changes in plugin's jar file , in order to succeeded install it in v5.1.1.
when we try to run the elasticsearch , we get this error.
do you have any idea?

**Comment by jasontedor** [comment]
I'm not sure what you mean when you say you made changes to the plugin's JAR; I'm reading it as you extracted the contents of the JAR, modified the plugin-descriptor.properties file to change the version and put the JAR back together again. That is emphatically not going to work, the plugin API between 2.x and 5.x is different, classes that existed in 2.x are not necessarily still going to be present in 5.x (and this class is indeed not). You will need to modify the source code to compile with 5.x, and then assemble an entirely new JAR.

If you have additional questions, please open a topic on the [forum](https://discuss.elastic.co); Elastic reserves GitHub for verified bug reports and feature requests.
