### ISSUE TITLE
Return Span Position information from span queries

### ISSUE THREAD

**Issue by hanan-levy-sp** [elastic/elasticsearch#22732]
**Describe the feature**:
I'd like to be able to access the Position Information of matched terms in spans queries. 
 There's a way through accessing the "getSpans" method in Lucene( and Lucene .Net.),  however, the data is not exposed through ElasticSearch, and is not retrieved in the Hits or Explains sections of Span Query responses.

Having the position information will allow accessing the actual matched terms through the Term Vector. 
It will therefore allow to query the actual matches and match sequences, even for span queries that does not explicitly state the terms involved, such as Span Multi-term Queries (Regex, Wildcard and prefix Span Queries), and the Near-Span Queries that involve them. 
e.g. 
Matching credit card number continuous sequences, and the verifying the actual results.

**Comment by clintongormley** [comment]
Hi @hanan-levy-sp 

Could you expand more about your use case and practically how you would use this feature?

**Comment by hanan-levy-sp** [comment]
Sure. 

Assume you're indexing large amounts of data, in very big documents - so you won't be able to store the actual data, and would also like to exclude it from the _source field. 

Let say you wish to find a sequence of 4 terms, that match particular regular expression. 
for instance - a master card number sequence. 
You could create 4 span multi queries - with an underlying regex query - and join them all in a SpanNear, ordered query with a slope of 0. 

That would give you the doc_id of all document that contain such a sequence. 
However, if you wanted to know the actual sequence that matched the SpanNearQuery. For example, if you want to verify that the matched terms actually constitute a valid credit card number (let's say you're monitoring sensitive information for security, classification and remediation purposes) you would have to run a verification algorithm, on the actual terms. You'd have to join the 4 consecutive terms, into a card number and verify it by the Luhn verification algorithm. 

You can't use highlighting - since you cannot store the actual data, and won't store it since its too big-  and you've excluded it from the _source. 

One way of getting the data is based on Spans, and term vectors. 
The spans information form the SpanNear query, will contain the position information for each matching sequence (and for each term within that sequence) - in every document that matched it. 

using this position information you can than access the term vector of that specific field, in that specific document, and retrieve the actual terms. 

There are probably tons of other situation in which you'd want to access the actual term, in a specific position. 

And since there's already access to that information - it's a shame not to make available for use.
The Lucene's Span Queries all expose the getSpans method as a public method, and you can easily access it using Lucene. 
I don't think you can do that in Elasticsearch. (Do correct me if I'm wrong - It would be super helpful! )

A good response in my view would be a  JSON array, containing all spans objects for each hit document, where each span object contains the Start and End position of each document.

**Comment by hanan-levy-sp** [comment]
In the last line: 
" the Start and End position of each" matched  **span **   within the document - of course.

**Comment by hanan-levy-sp** [comment]
Any Thoughts?

**Comment by jimczi** [comment]
>That would give you the doc_id of all document that contain such a sequence.
However, if you wanted to know the actual sequence that matched the SpanNearQuery. For example, if you want to verify that the matched terms actually constitute a valid credit card number (let's say you're monitoring sensitive information for security, classification and remediation purposes) you would have to run a verification algorithm, on the actual terms. You'd have to join the 4 consecutive terms, into a card number and verify it by the Luhn verification algorithm.

@hanan-levy-sp the response contains only the top document that match the query. So what you describes here would be achievable in a custom query rather than just returning the positions in the response. You could for instance write a plugin that defines a new `credit card query` extending `Query` and implemented with the two-phase execution of the `Scorer` API. The first phase would just select the docs that match the `SpanNear` query and the second phase could just runs a verification on all spans inside the current document. This way you could return only the hits that fully match the query (hits that contain a verified credit card number) and you don't have to do anything on the client side.

**Comment by hanan-levy-sp** [comment]
Hi Jim, 
I'm not sure i'm following. 
will not exposing the Spans information of a Lucene Span query return the position info of each term in every document that matched the query? 

If so, you could just parse it as part of the response and return a list of positions for each matched document. subject to restriction of how many results you need to return ("size").

The credit card example is just one example. I need to positions so i can re-discover the actual terms.

I'll appreciate your response.
thank you
Hanan.

**Comment by jimczi** [comment]
> I'm not sure i'm following.
will not exposing the Spans information of a Lucene Span query return the position info of each term in every document that matched the query?

No, not every document just the top documents. If you want to filter documents based on the matched positions then you should not work at the response level but rather at the index level. This is why I advised you to create a custom span query that fits your need. This query would run on every document but would return only the matching document (those that contain valid credit card number for instance). This way you don't have to do the filtering on the top documents, they would be already filtered. 

> If so, you could just parse it as part of the response and return a list of positions for each matched document. subject to restriction of how many results you need to return ("size").

I understand what you're asking but I don't think it's a good design (at least for your use case). Though you could write a custom plugin that would return the positions for each top hit. You can check for instance `org.elasticsearch.search.fetch.subphase.MatchedQueriesFetchSubPhase` that runs named queries on the top hits and adds the name of the matching queries to the response for each hit. But again if your intent is to filter documents based on the output of span queries then a custom query would be a better fit.

**Comment by hanan-levy-sp** [comment]
Hi Jim,
Thanks for the elaborate response. 
Can you please refer me to such a custom query plugin? 

thanks very much 
Hanan.

**Comment by jimczi** [comment]
> Can you please refer me to such a custom query plugin?

Well it's a custom query plugin so it doesn't exist yet, **you** must write it ;) 
You can check this page for examples of ES plugins:
https://www.elastic.co/guide/en/elasticsearch/plugins/5.2/api.html

**Comment by hanan-levy-sp** [comment]
Yea. I know. :) 
I was wondering if you knew of any example of a custom query plugin, that i might have a look at for the integration with elastic. 
The logic I'll obviously write myself. 

Thanks.

**Comment by hanan-levy-sp** [comment]
I've found what i needed. 
Thanks for all you help. 

Hanan.

**Comment by shijiebei2009** [comment]
@hanan-levy-sp 
I want to know how do you solve this problem? I want to get position information by span query too.
