### ISSUE TITLE
Set LimitMEMLOCK in systemd service file

### ISSUE THREAD

**Issue by cwurm** [elastic/elasticsearch#22734]
https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html#mlockall documents how to lock the memory on different systems. For systemd, it's setting `LimitMEMLOCK=infinity` in an override file for the systemd service file (`/etc/systemd/system/elasticsearch.service.d/elasticsearch.conf` as documented on https://www.elastic.co/guide/en/elasticsearch/reference/current/setting-system-settings.html#systemd).

However, couldn't we just set this in the default service file already (`/usr/lib/systemd/system/elasticsearch.service`)?

Would save one step when setting things up and make it less likely people forget to configure this.

**Comment by jasontedor** [comment]
I don't think that we should do that.

First, memory locking should be the least preferred option to preventing the JVM heap from landing on disk. It's an option for users for which completely disabling swap or setting minimizing swappiness are not options.

Second, additional configuration is required anyway for enabling memory locking: setting `bootstrap.memory_lock`. If a user enables this but has not configured max locked memory correctly, memory locking will fail. In production mode, [startup will fail](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/_memory_lock_check.html) informing the user that additional configuration is needed. In particular, if the OS is enforcing restrictive per-user limits (e.g., the default on stock Fedora 25 is 64k), adding `LimitMEMLOCK=infinity` to the unit file is not enough.
