### ISSUE TITLE
[feature request]shard group

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#22737]
**Describe the feature**:
1. with this issue: https://github.com/elastic/elasticsearch/issues/21585#event-927040461 
can patially fix this situation:
Users occasionally have a surge in write traffic that a single shard cannot process fast enough

but think one extremely situation that we may meet:
one shard is almost unavaiable due to  write traffic even with above instrument. the most quick fix way is to add one more backup shard to take ove all the write traffic and give that share a time to take a breath and then recovery. afterwords, all the read traffic have to visit 2 shards.
we may call this shard group

**Comment by clintongormley** [comment]
@makeyang you can do that today by increasing the number of replicas (a dynamic setting).  Of course, creating the second shard puts load onto servers while it copies all the data across, but there's no getting away from that
