### ISSUE TITLE
[Documentation] Clarify that jvm.options should be preserved during an update 2.4->5.x

### ISSUE THREAD

**Issue by vsizov** [elastic/elasticsearch#22744]
https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html#rolling-upgrades

The doc says `Either copy the files in the config directory from your old installation to your new installation, or use the -E path.conf= option on the command line to point to an external config directory.`  The problem is that ES 5.x contains a `jvm.options` file that should be preserved otherwise Elastic will not start. I think the documentation should be clear on this. Sorry if I missed something, and thank you for your time.

**Comment by jasontedor** [comment]
Thanks for reporting @vsizov.
