### ISSUE TITLE
type[tw] missing [type=type_missing_exception]

### ISSUE THREAD

**Issue by alkesh26** [elastic/elasticsearch#22740]
**Elasticsearch version**: 5.1.0

**Description of the problem including expected versus actual behavior**:
I have disabled dynamic mapping and facing this exception while creating an index like

`abc-latest-tw/tw/<id>` and getting the error

`elastic: Error 404 (Not Found): type[tw] missing [type=type_missing_exception]`

**Steps to reproduce**:
 1. Installed elasticsearch 5.1.0.
 2. Called the following API.
```
PUT _template/template_all
{
  "template": "*",
  "order":0,
  "settings": {
    "index.mapper.dynamic": false 
  }
}
```
 3. Create an index with following POST request

`http://localhost:9200/abc-latest-tw/tw/1` with POST body like

```
{
  "firstKey" : 1,
  "secondKey" : "abcd"
}
```

**Provide logs (if relevant)**:
Getting the following error
`elastic: Error 404 (Not Found): type[tw] missing [type=type_missing_exception]`

I want to disable dynamic mapping for all existing and new indices.

**Comment by jasontedor** [comment]
You've disabled automatic type creation (that's what [`index.mapper.dynamic` does](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/dynamic-mapping.html)), so you have to explicitly create the type first either when you [create the index](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/indices-create-index.html) or via the [put mapping API](https://www.elastic.co/guide/en/elasticsearch/reference/5.1/indices-put-mapping.html).

**Comment by alkesh26** [comment]
Hey @jasontedor thanks for the answer. 

What if I want to store the data without any mapping? Just dumping the data.

**Comment by jasontedor** [comment]
You have to have a mapping. If you have additional questions, please open a topic on the [forum](https://discuss.elastic.co).
