### ISSUE TITLE
Cannot update index template using REST on s390x Docker Container

### ISSUE THREAD

**Issue by benjsmi** [elastic/elasticsearch#22755]
**Elasticsearch version**: 5.1.1

**Plugins installed**: none

**JVM version**: 
```
openjdk version "1.8.0_102"
OpenJDK Runtime Environment (build 1.8.0_102-8u102-b14.1-1~bpo8+1-b14)
OpenJDK 64-Bit Zero VM (build 25.102-b14, interpreted mode)
```

**OS version**:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

**uname**
```
$ uname -a
Linux ******** 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:42:36 UTC 2016 s390x s390x s390x GNU/Linux
````

**Description of the problem including expected versus actual behavior**:
I stood up elasticsearch v5.1.1 in a Docker container running on System Z with the JNA libraries built for JNA support for ES.  I then pointed a logstash v5.1.1 container at this elasticsearch with the elasticsearch output plugin enabled.  When first starting the elasticsearch container, I see:
```
[2017-01-23T22:05:45,735][DEBUG][o.e.b.JNANatives         ] unable to install syscall filter
java.lang.UnsupportedOperationException: seccomp unavailable: 's390x' architecture unsupported
    at org.elasticsearch.bootstrap.Seccomp.linuxImpl(Seccomp.java:267) ~[elasticsearch-5.1.1.jar:5.1.1]
    at org.elasticsearch.bootstrap.Seccomp.init(Seccomp.java:630) ~[elasticsearch-5.1.1.jar:5.1.1]
    at org.elasticsearch.bootstrap.JNANatives.trySeccomp(JNANatives.java:215) [elasticsearch-5.1.1.jar:5.1.1]
```

Which I'm not 100% sure I need to worry about nor is the source of the problem.  To the best of my knowledge, the above block means that elasticsearch tried to access a Java Native feature to increase the security of my deployment by _disallowing_ certain features at the kernel level for my protection but could not because that feature is not available in my kernel.  I include here as FYI just in case it has an effect on the problem I see later on.

Elasticsearch starts fine and I wait for it to finish coming up, then I kick on my logstash container.  Logstash connects and attempts to store the first index template.  That's when I see this:
```
[2017-01-23T22:06:55,319][DEBUG][r.suppressed             ] path: /_template/logstash, params: {name=logstash}
org.elasticsearch.ElasticsearchParseException: Failed to derive xcontent
    at org.elasticsearch.common.xcontent.XContentFactory.xContent(XContentFactory.java:239) ~[elasticsearch-5.1.1.jar:5.1.1]
    at org.elasticsearch.action.admin.indices.template.put.PutIndexTemplateRequest.source(PutIndexTemplateRequest.java:362) ~[elasticsearch-5.1.1.jar:5.1.1]
    at org.elasticsearch.rest.action.admin.indices.RestPutIndexTemplateAction.prepareRequest(RestPutIndexTemplateAction.java:50) ~[elasticsearch-5.1.1.jar:5.1.1]
    at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:66) ~[elasticsearch-5.1.1.jar:5.1.1]
    at org.elasticsearch.rest.RestController.executeHandler(RestController.java:243) ~[elasticsearch-5.1.1.jar:5.1.1]
    at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:200) [elasticsearch-5.1.1.jar:5.1.1]
    at org.elasticsearch.http.HttpServer.dispatchRequest(HttpServer.java:113) [elasticsearch-5.1.1.jar:5.1.1]
    at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:507) [transport-netty4-5.1.1.jar:5.1.1]
```

Based on the [code](https://github.com/elastic/elasticsearch/blob/5.1/core/src/main/java/org/elasticsearch/common/xcontent/XContentFactory.java#L182), my read is that the XContentFactory instantiates the xContent class, where the [content type is guessed](https://github.com/elastic/elasticsearch/blob/5.1/core/src/main/java/org/elasticsearch/common/xcontent/XContentFactory.java#L248) based on the contents of the message.  What's odd is that I _know_ that logstash is sending a JSON object in the body of the message, and the code says if the message starts with `{`, it shouldn't return null, but rather should return the `JSON` type.

I highly doubt that it's an incorrect request, given that logstash is the one generating it and that I can point this same container/image at an elasticsearch that is running on x86 and it functions correctly.

I have committed my work for the steps to reproduce in a Github repository under my namespace: https://github.com/benjsmi/elasticsearch-s390x

Within this repo, you'll find all the files necessary to build elasticsearch 5.1.1 on s390x.  

Also, within this repo, you'll see the files necessary to build JNA for s390x:
https://github.com/benjsmi/elasticsearch-s390x/blob/master/jna/Dockerfile-jna-z

The above Dockerfile can be used to build a docker builder on s390x, which will pull down the JNA code, ant, and run the targets to create a JAR that has s390x support with the relevant libdispatch.so.

**Steps to reproduce**:
 1. Build the Docker Image at https://github.com/benjsmi/elasticsearch-s390x on an s390x machine with the command:

```
docker build -t elasticsearch:s390x -f ./Dockerfile-z .
```

 2. Run the container on this Z system with command:

```
docker run -it -p 9200:9200 elasticsearch:s390x
```

3. Run an instance of logstash, configure to point at the above s390x machine on port 9200.  It doesn't matter how this logstash is configured elsewise, so long as its output is set to point at the above s390x machine.

**Provide logs (if relevant)**:

The logs for the logstash container:
http://pastebin.com/ds0Kvsdg

The logs for the elasticsearch container:
http://pastebin.com/fBh7L4Tz

**Comment by jasontedor** [comment]
I'm sorry, we do not support s390x. If you can reproduce the issue on an OS that we do support, we will take a look.

**Comment by jasontedor** [comment]
By the way, the syscall filter indeed has nothing to do with the problem, that's expected on your OS.

**Comment by benjsmi** [comment]
s390x is not an operating system, it's an architecture.  I am using Ubuntu on this s390x machine.  Are you saying that this _architecture_ is not supported?

**Comment by jasontedor** [comment]
As I said:

> I'm sorry, we do not support s390x.

**Comment by jasontedor** [comment]
> s390x is not an operating system, it's an architecture.

Oh, I see why you responded this way. It's because I said:

> If you can reproduce the issue on an OS that we do support, we will take a look.

Sorry, I meant to say system there, that was just a typo.

**Comment by clintongormley** [comment]
Whether the system is supported or not, you are right in saying that elasticsearch is not identifying the content type as JSON. I'd inspect what is actually being sent - the answer is probably pretty obvious
