### ISSUE TITLE
Index-Level Default Operator Configuration

### ISSUE THREAD

**Issue by FishkinsDC** [elastic/elasticsearch#22750]
**Describe the feature**:
I'd like all the query strings against my index to use AND as the default operator. It's possible to configure a default operator for a specific query, but not for all queries against an index. I'd like to be able to set a default operator for a whole index, analogous to ```<solrQueryParser defaultOperator="AND"/>``` in Solr.

**Comment by clintongormley** [comment]
Hi @FishkinsDC 

No this isn't something we support and it's not something we plan on supporting either.
