### ISSUE TITLE
Combining template queries with aggregations do not work as expected

### ISSUE THREAD

**Issue by jomarl** [elastic/elasticsearch#22766]
**Elasticsearch version**:
5.1.2

**Plugins installed**: [Phonetic Analysis, X-Pack] 

**JVM version**:
1.8.0_101-b13

**OS version**:
Linux Mint 17

**Description of the problem including expected versus actual behavior**:

Aggregations added to a SearchRequest are ignored when used in combination with SearchTemplateRequestBuilder. The same go for any size/from parameters.

We use a lot of templates in combination with some common aggregations that are added to many of our searches, and in the process of migrating to ES 5.1.2 from ES 1.6 we are unable to use this combination. Is this not longer possible in ES 5.1.2 or are we doing this the wrong way? We do not want to duplicate the aggregations to every search template we use - or is that the only way?

**Steps to reproduce**:

```
SearchRequestBuilder builder = esClient.prepareSearch("xx")) .setTypes("xx").builder.setSize(200);

builder.addAggregation(
      AggregationBuilders.terms("country")
                    .field("country.raw")
                    .order(Terms.Order.term(true))
                    .size(100)
                    .valueType(ValueType.STRING)
);

SearchTemplateRequestBuilder templateBuilder = new SearchTemplateRequestBuilder(esClient)
                        .setRequest(builder.request())
                        .setScript(templateName)
                        .setScriptType(ScriptType.FILE)
                        .setScriptParams(templateParams);

response = templateBuilder.get();

assertNotNull(templateBuilder.get().getAggregations()); //fails 
assertEquals(response.getHits().getHits().length, 200); //fails - give 10/default
```

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by tlrx** [comment]
@jomarl Thanks for reporting. I looked at what you describe and I'm surprised it even worked in previous versions of elasticsearch. 

Search templates are designed to be self sufficient, ie you only provide some parameters and the whole query can be built out of them; but they are not designed to be kind of completed or altered using the Java API. In 5.x, many things were improved in search template to ensure that (before 5.x, search templates, script and template query code were really intricate and mixed, they are now better separated).

You could maybe use a combination of search template + template queries to replicate what you did in 1.6. I spent some time trying to find a good solution but I failed. Maybe you'll be luckier than me :) Maybe you could also use a search template that defines the common aggregations, and build the query string on application side and pass it as a parameter. In any case, template queries are deprecated in 5.x and will be removed in next versions so the solution must not be based on it.

**Comment by tlrx** [comment]
No feedback, closing.

**Comment by jomarl** [comment]
Hi, and a delayed thanks for the help.

We moved away from using mustache templates to building our search queries using the java api.

**Comment by AkopovaAnna** [comment]
Hi @jomarl ;
I have also used mustache, and encountered with problems and exceptions, such as org.elasticsearch.script.mustache.SearchTemplateRequest cannot be cast to org.elasticsearch.script.mustache.SearchTemplateRequest". This is actual also in the simple examples used in elasticsearch template query search example.
As a result the search template query could not be build and execute. Could you help and suggest what kind of solutions you use?
