### ISSUE TITLE
Improve "Fielddata is disabled on text fields by default" message

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#22768]
Whenever you try to aggregate on a text field, you get back the following message:

```
Fielddata is disabled on text fields by default. Set fielddata=true on [field] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.
```

That makes sense, but given that we now by default have the raw version of the field, shall we print out some suggestion like "use [field.keyword] instead"? Otherwise people may go and enable loading of fielddata instead.

**Comment by clintongormley** [comment]
There's no guarantee that there is a `.keyword` field - I'd only show this message if we're sure there is one.  Also, recent versions of Kibana only show fields that are aggregatable, so this message is seen much less frequently.

**Comment by javanna** [comment]
I see, maybe just give the two options then? It would be nice to mention keyword fields at least, just not to make people enable fielddata by mistake.

**Comment by javanna** [comment]
Discussed in FixItFriday, we decided to rephrase the error message and mention the two options: either enable fielddata or aggregate on a field of type keyword.

**Comment by IanvsPoplicola** [comment]
Hi @javanna is core/src/main/java/org/elasticsearch/index/mapper/TextFieldMapper.java the only file that needs to be changed for this issue?

**Comment by jpountz** [comment]
@IanvsPoplicola Yes indeed.

**Comment by colings86** [comment]
I've opened https://github.com/elastic/elasticsearch/pull/23841 to improve the error message for this per https://github.com/elastic/elasticsearch/issues/22768#issuecomment-275670687. However, since the error can be seen when sorting as well as aggregating (and maybe in other cases too) I did not mention aggregating in the message

**Comment by IanvsPoplicola** [comment]
Hi @colings86 , I've recently done a bit of work on this; I'd really appreciate some feedback if you could have a look at my changes!
Basically what it does is now every time TextFieldType's fielddataBuilder() method gets called while fielddata is disabled, it will check to see if there is any sub-field of keyword-type under the textfield, and will only replace the error message if such sub-field exists.

**Comment by colings86** [comment]
@IanvsPoplicola I'm not sure we need the logic to be complex here. I think always adding the message is ok. That way it makes it clear to the user whenever they see this that for text fields there are two way to aggregate or sort the data, either enable field data at the cost of using memory or use/add a keyword field. If we only show the message when the keyword sub field exists the users will not for example that they can re-index with a keyword field to solve this issue.

**Comment by IanvsPoplicola** [comment]
Fair enough, thank you very much for the feedback!

**Comment by mahesh1104** [comment]
Fielddata is disabled on text fields by default. Set fielddata=true on [endpoints_data.uri] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.
i am getting this error in grafana, how to achive this one
