### ISSUE TITLE
Remove auto creation of bucket for s3 repository

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#22761]
Creating a bucket is a management operation which a user should have already done, and only needs to do once. We should remove auto bucket creation and error if the configured bucket does not exist.

**Comment by dadoonet** [comment]
I agree.

**Comment by dadoonet** [comment]
Discussed on FixIt friday session. We agreed that we should remove auto creation of S3 bucket and fails if it not exists.
