### ISSUE TITLE
Extra host discovery functionality for SSL hostname matching.

### ISSUE THREAD

**Issue by bernielomax** [elastic/elasticsearch#22779]
Hi,

This is a feature request for the discovery-ec2 plugin. Recently I have been trying out Shield in an AWS environment. Since this is an elastic environment I was hoping to use our own wildcard SSL certificates as nodes were likely to come and go. During implementation I discovered that the only available settings for `network.host` are for AWS public/private hostnames/IPS which will never match against our certificates.  What would potentially solve this issue is by adding additional network host settings:

_ec2:privatePtr_
_ec2:publicPtr_

That way you could use reverse DNS to determine the full company hostname rather than the Amazon internal/public name. Our automations could then generate these Route53 entries during the launch of the instance.

Or you could possibly just use tagging to achieve a similar result.

**Comment by dadoonet** [comment]
I think that this #22743 should help you.

**Comment by bernielomax** [comment]
@dadoonet thanks for the reply. The linked issue should do the trick. Do you know when it will likely be released? I see it was merged into master only a few hours ago.

**Comment by dadoonet** [comment]
I'm waiting for a review for branch 5.x.
I'm unsure yet which version will contain this. My bet is that you will have to wait for 5.3.0 but again I'm unsure ATM.

Closing your issue then as it will address your needs.

**Comment by bernielomax** [comment]
Great. Thanks @dadoonet ! :+1:

**Comment by dadoonet** [comment]
@bernielomax FYI Merged in 5.x branch with https://github.com/elastic/elasticsearch/pull/22819

**Comment by bernielomax** [comment]
Thanks @dadoonet I cant wait for it to be released. Im currently in a catch 22 between this issue and  https://github.com/logstash-plugins/logstash-output-http/issues/21 as logstash does not seem to be adhere to ssl_certificate_verification = false.
