### ISSUE TITLE
script for search rank (script_score)

### ISSUE THREAD

**Issue by fix2015** [elastic/elasticsearch#22774]
hey guys, i have pb, i have field 
rank = {
0: 'js',
1: php
...
}
i need order so i decide use script_score and write this code
script_score{
 script = ` (1 + (doc['rank'].size() > 0 ? doc['rank'].values.find{it =="js"} ?  1 : 0 : 0))`;
}
but its not help can you help me how find value in arrys in elasticsearch???

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
