### ISSUE TITLE
Keyword in ES 5.1.1 consume twice as much space comparing to String in ES 2.4.1

### ISSUE THREAD

**Issue by tomasfalt** [elastic/elasticsearch#22785]
**Elasticsearch version**:
5.1.1 and 2.4.1
**Plugins installed**: 
X-pack for 5.1.1, DeleteByQuery for 2.4.1
**JVM version**:
1.8.0_111
**OS version**:
Windows Server 2012 R2

**Description of the problem including expected versus actual behavior**:
Keyword in ES 5 seems to consume twice as much space comparing to String in ES 2
**Steps to reproduce**:
 1. Create an simple index with following mapping for 2.4.1:
```json
{
  "mappings": {
    "stringtest": {
      "properties": {
        "stringField": {
          "index": "not_analyzed",
          "type": "string"
        }
      }
    }
  }
}
```
and for 5.1.1
```json
   {
  "mappings": {
    "stringtest": {
      "properties": {
        "stringField": {
          "type": "keyword"
        }
      }
    }
  }
}
```
 2. Add one million documents with the same text (in my case I added ThisIsAString{i} where {i} is a number that increments for each document) to each index.
 3. The size of the 5.1.1 index is twice the size of the 2.4.1 index (at least in my environment)

**Comment by clintongormley** [comment]
i tested this with one shard for each index and force-merging after indexing, and both indices were 43M.

Not sure what's different about your environment but something is wrong with your test
