### ISSUE TITLE
[code issue][discuss]create a Annotation to mark method/fields for test purpose

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#22780]
* ONLY EXPOSED FOR TESTS!
// NOTE: this class is not part of guice and was added so the provider lookup's key can be accessible for tests
// public for tests
// for tests
// only settable for tests

somthings like these scatter all around code. so better create a Annotation to tell.

**Comment by jasontedor** [comment]
Thanks for the suggestion. However, I question the value of these comments to begin with (since you can tell my usages if a method is used in testing), and either way I do not think we need annotation for this purpose.
