### ISSUE TITLE
Slow query when using groovy.time.TimeCategory in groovy script

### ISSUE THREAD

**Issue by msimos** [elastic/elasticsearch#22791]
**Elasticsearch version**:

2.4.4

**JVM version**:

1.8

**OS version**:

Linux

**Description of the problem including expected versus actual behavior**:

In Elasticsearch 2.4.4 it seems that use(groovy.time.TimeCategory) { is causing slow query performance. If I remove this statement and the operation of specialPriceEndDate + 1.days - 1.seconds, the query returns in 100 ms otherwise it takes 2 minutes. The same Groovy script in Elasticsearch 1.7.x takes 2s consistently. 

**Steps to reproduce**:

```
GET t/_search
{
   "query": {
      "script": {
         "script": {
            "file": "vehicle_price_filter",
            "lang": "groovy",
            "params": {
               "_op": "lte",
               "_param1": 16000,
               "_param2": null
            }
         }
      }
   }
}
```
```
{
   "took": 148227,
   "timed_out": false,
   "_shards": {
      "total": 2,
      "successful": 2,
      "failed": 0
   }
```

**Comment by rjernst** [comment]
Groovy has been removed for 6.0. Closing.
