### ISSUE TITLE
inconsistency between source filtering names in query parameter vs request body

### ISSUE THREAD

**Issue by djschny** [elastic/elasticsearch#22792]
**Elasticsearch version**: 5.1.1

**Plugins installed**: []

**JVM version**: 1.8.0_92-b14

**OS version**: Mac 10.12.2

**Description of the problem including expected versus actual behavior**:
In regards to source filtering and using include/exclude it appears @pickypg and I observed two discrepancies:

* `_source_include` in singular or plural form when used as a query parameter works fine, however when the singular form is used in the request body, an error is thrown and a plural version is required to be used.
* the error that does come back is a deprecated field response as opposed to executing the request and the deprecation coming back as a header

As a side note Console in Kibana is auto suggesting the singular version as well and will enter an issue there for that as well.

**Steps to reproduce**:

```
# Request - successful as query parameter with either singular or plural version
GET nutrition/_search?_source_includes=calories
```

```
# Request - throws error as request body
GET nutrition/_search
{
  "_source": {
    "include": "calories"
  }
}

# Response
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Deprecated field [include] used, expected [includes] instead"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Deprecated field [include] used, expected [includes] instead"
  },
  "status": 400
}
```

**Comment by pav-1** [comment]
Hello,  I'm looking for my first contribution to elasticsearch. I'll take it up.

I'm familiarizing myself with the code base. 
So, hope it doesn't stop anyone else from coming up with a fix before I do!

**Comment by chaynika** [comment]
If this bug hasn't been fixed yet, I would like to work on it, starting today. Thank you!

**Comment by pav-1** [comment]
Sure. Not an issue.

FYI for headstart, this is not present in master , but only in the version
it's raised and master branch uses slightly different APIs to parse the
tokens. So, that change is not directly portable.

**Comment by hesamemadi** [comment]
Hey @chaynika , If this bug hasn't been fixed yet, I would like to work on it, starting today. Thank you!

**Comment by pav-1** [comment]
@djschny 
This is not an issue anymore in 5.2.2 or master as `ParseFieldMatcher` is deprecated/removed and strict mode is not used when parsing _includes_.

Is this required in 5.1.x?

**Comment by pratikadola** [comment]
Has the issue been fixed?

**Comment by nik9000** [comment]
> Has the issue been fixed?

It is still an issue. We'd want to deprecate the singular form in one PR which we'd merge to master and 6.x and then remove the singular form in a followup. These kinds of changes can be a bit tricky around the multi-version REST tests but the changes themselves are fairly simple.
