### ISSUE TITLE
Added filtering/querying on top_hits aggregation results

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#22817]
In some cases it is useful to further filter top_hits results based on their content.  For example:

Here's an example of the scenario. 

Term aggregation By 'x' returns 3 documents. 
1.	D1 { x: '5', fx: 'A', date: '2017-01-01T00:00:00' } 
2.	D2 { x: '5', fx: 'B', date: '2017-01-05T00:00:00' } 
3.	D3 { x: '5', fx: 'C', date: '2017-01-11T00:00:00' } 
What we've now aggregating by 'x' is 
•	Count: 
o	3 
•	First: 
o	D1 { x: '5', fx: 'A', date: '2017-01-01T00:00:00' } 
•	Last: 
o	D3 { x: '5', fx:'C', date: '2017-01-013T00:00:00' } 
What we want to do 
•	Filter by whatever field in D1 or D3 i.e. D1.fx is equals to 'A'. If yes, return bucket, If not, don't return

It appears this is not currently possible, but it would be helpful.

**Comment by jpountz** [comment]
We just discussed it in Fixit Friday and confirm this is not possible.

We wonder that there might be ways to find the relevant information in a different way but the abstract example makes it difficult to reason about potential alternatives. Could you provide a concrete example?

**Comment by colings86** [comment]
No further feedback.
