### ISSUE TITLE
[Docs] "Query and filter context" doc is confusing.

### ISSUE THREAD

**Issue by vsizov** [elastic/elasticsearch#22813]
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html

I find this doc confusing for new users.
`This query will match documents where all of the following conditions are met`and goes list of 4 conditions. And then we see the text: `two match clauses are used in query context, which means that they are used to score how well each document matches.`. The last one I take as "The more match conditions have been met the higher _score will be". 

We need to highlight that if document has 2 occurrences of "Search" it will have higher "_score" than document with 1 occurrence. It can be obvious for you, but it's now that obvious for new users.
Sorry if I missed something, my English is crappy so I could be wrong.

**Comment by clintongormley** [comment]
Hi @vsizov 

Thanks for the issue, but I disagree with the conclusion:

> We need to highlight that if document has 2 occurrences of "Search" it will have higher "_score" than document with 1 occurrence. 

The purpose of this page is to explain the difference between query and filter context only, not how scoring algorithms work, which is explained elsewhere.  This page is already long enough; adding more detail here will just make it harder to parse.
