### ISSUE TITLE
line number in painless compile error is incorrect

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#22827]
Given some script with a compile problem:

```
void doSomething() {
 someVariable.push("asdf")
}
```

Only the following is included compile error - which doesn't have a correct line number:

```
Caused by: java.lang.IllegalArgumentException: Variable [someVariable] is not defined.
	at org.elasticsearch.painless.Executable$Script.compile(compile_me.painless:24) ~[?:?]
```

**Comment by jdconrad** [comment]
We actually made the decision to make it character rather than line since that information is more helpful for most scripts since they are typically single lines.  I thought this was documented, but it's not, so I'll add it to the list of things that need documentation.

**Comment by PhaedrusTheGreek** [comment]
Character number is fantastic.
