### ISSUE TITLE
IcuFoldingTokenFilter still accepts camelCase parameter

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#22823]
https://github.com/elastic/elasticsearch/blob/master/plugins/analysis-icu/src/main/java/org/elasticsearch/index/analysis/IcuFoldingTokenFilterFactory.java#L48

https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu-folding.html

**Comment by Mpdreamz** [comment]
Same is true for the expert settings under https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu-collation.html

Should we document these as snake case and deprecate the camelCase variants?

**Comment by IanvsPoplicola** [comment]
Hi @Mpdreamz I'm a newbie here and I'm thinking of making this my first contribution to elasticsearch! Where do you recommend me to start looking for a solution for this issue? Any advice is welcome!

**Comment by williamw1994** [comment]
Hi @Mpdreamz Is this issue still there? Would you mind if I taking this issue?

**Comment by gmaddex** [comment]
Hi, I'm trying to get started with some low hanging fruit and I'd like to take this issue on if you don't mind.

**Comment by Mpdreamz** [comment]
@gmaddex I don't think anyone is working on it, go for it!

**Comment by liketic** [comment]
@Mpdreamz What's I need to do if I want to fix this? Thanks very much!

**Comment by romseygeek** [comment]
cc @elastic/es-search-aggs
