### ISSUE TITLE
ICU Collation Token Filter missing documentation on rules

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#22824]
The code mentions it either takes a `rules` or `language`/`country`/`variant` combination

https://github.com/elastic/elasticsearch/blob/master/plugins/analysis-icu/src/main/java/org/elasticsearch/index/analysis/IcuCollationTokenFilterFactory.java#L54

But the documentation does not mention these rules, are they deprecated?

**Comment by clintongormley** [comment]
no they aren't deprecated, just not documented

**Comment by jrodewig** [comment]
[docs issue triage]

The ICU collation token filter is now deprecated. :)

Closing as a stale issue.
