### ISSUE TITLE
Add default logging for allocate_*_primary reroute commands

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#22821]
5.1.1

For commands that can lead to data loss (ok-ed by the end user) like allocate_*_primary, it will be helpful to log some messages at the INFO level so that there is a record of when such command was executed for historical troubleshooting purposes.  Currently, it only logs exceptions if the command actually fails, but not when it is successful.

**Comment by bleskes** [comment]
I would suggest WARN for the for allocate primary one..

**Comment by fernandozhu** [comment]
Hello there, I'm happy to work on this issue.

**Comment by fernandozhu** [comment]
Hello there, I'm happy to adopt this issue.

**Comment by andy-elastic** [comment]
I'll take this one
