### ISSUE TITLE
Paging w/ multi_match on edge ngram produces duplicate docs

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch#22836]
As I fully described here:
https://discuss.elastic.co/t/paging-w-multi-match-on-edge-ngram-produces-duplicate-docs/71778

**Comment by clintongormley** [comment]
Hi @tdoman 

This doesn't sound like a bug to me.  I think what you're seeing is "bouncing results" - documents in different shards are stored in different segments, which means that the scores are slightly different. If you use ?preference=$session_id or something similar to ensure that the same user always hits the same shard copy, this behaviour should disappear.

**Comment by tdoman** [comment]
Indeed, I had thought the same thing as I had employed the "preference" setting for bouncing results before.  However, I was able to reproduce this problem on a single node system which is why I entered the issue.  Sorry, I forgot to add that detail.

**Comment by clintongormley** [comment]
Could you add a full recreation please?  What you're describing doesn't make sense given how doc collection works, so I'd like to see exactly what you're doing

**Comment by colings86** [comment]
No further feedback, closing
