### ISSUE TITLE
Grok Processor should complain about patterns it doesn't understand

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#22831]
The following command (note the `UNKNOWN` pattern name):

```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "grok": {
          "field": "myfield",
          "patterns": [
            """{%UKNOWN:field}"""
          ]
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "myfield": "50-59"
      }
    }
  ]
}
```

results in the following error:

```
 "reason": "java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Provided Grok expressions do not match field value: [50-59]",
        "caused_by": {
          "type": "illegal_argument_exception",
          "reason": "java.lang.IllegalArgumentException: Provided Grok expressions do not match field value: [50-59]",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "Provided Grok expressions do not match field value: [50-59]"
          }
```

Note that the actual failure is nowhere to be found.  It also seems it gets all the way to evaluating the field values. IMO it should fail early and hard.

PS. This is on 5.1

**Comment by talevy** [comment]
as of now, I believe if it doesn't match the correct format, it assumes it is just plain-old regex. what if  you wanted to match `{%UKNOWN:field}`, literally?

**Comment by bleskes** [comment]
@talevy sorry, I'm not following what you say. Also for my surprise ` %{\d+:field}` didn't seem to work, with no failure messages either.

**Comment by clintongormley** [comment]
I think @talevy is saying that the correct format for grok patterns is `%{\w+:\w+}`, so `{%UNKNOWN:field}` doesn't match that pattern and is just treated as an ordinary regex.  Similarly `%{\d+:field}` doesn't match the pattern either.

**Comment by talevy** [comment]
@clintongormley, thanks for the clarification. That is exactly what I meant

**Comment by bleskes** [comment]
thx for clarifying @clintongormley . Sadly that was a typo on my end when I made the issue. `%{UKNOWN:field}` gives exactly the same behavior. 

re `%{\d+:field}` -  I expected `%{.*}` to always be matched and it's content analyzed. In that sense I expected grok patterns to be a templating strings for regular expressions. Reading the logstash docs, I see it is not and people can used named matches (or custom patterns) for things not in our list. That said, I think my issue about named patterns still holds.

**Comment by talevy** [comment]
@bleskes makes sense, I'll make it do a better job during parsing
