### ISSUE TITLE
Investigate removing retries from s3 blob store

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#22845]
The s3 client has a maxRetries setting, which is uses internally for retrying throttled requests. The setting is also read by the s3 blob store, and a while{try/catch} is used along with retries (but without backoff). It appears this outer retry mechanism may have existed for throttling before the sdk client did that, or also for eventual consistency. For the latter, this should no longer be a problem, as currently s3 provides read-after-write consistency for new PUTs (and afaik we should not be overwriting blobs). This issue is to discuss removing the retries from the blob store (but not the client).

**Comment by abeyad** [comment]
+1

> (and afaik we should not be overwriting blobs)

Correct

**Comment by dadoonet** [comment]
I agree. I'd just like to double-check with @tlrx as he introduced this feature with https://github.com/elastic/elasticsearch-cloud-aws/commit/cbe82d269f3af1cacb9360784e0772586dae7b5e

**Comment by tlrx** [comment]
+1 too, I think we can remove the discuss label.
