### ISSUE TITLE
GREP_OPTIONS='--color=always' breaks bin/elasticsearch

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#22841]
**Elasticsearch version**: 5.1.1

**Plugins installed**: []

**JVM version**: 1.8.0_45

**OS version**: Mac OS Sierra

**Description of the problem including expected versus actual behavior**:

Some users place grep coloring options in their bash profiles to color matches in 
grep responses. Elasticsearch relies on grep to help construct command-line arguments
for the java command that is executed by bin/elasticsearch. This results in special bash
color code characters which result in parsing errors.

error:

```
Error: Could not find or load main class -Xms2g
```

this `-Xms2g` is here only because it is the first argument that matched `-`, where grep has colored
the `-` in such a way that it does not get parsed successfully by the java command as an argument, and thinks it is a class name.

**Steps to reproduce**:
 1. run elasticsearch like so:

```
$ GREP_OPTIONS='--color=always' bin/elasticsearch
```

**Proposed fix**:

```diff
+++ distribution/src/main/resources/bin/elasticsearch
@@ -56,7 +56,7 @@ fi
 
 parse_jvm_options() {
   if [ -f "$1" ]; then
-    echo "$(grep "^-" "$1" | tr '\n' ' ')"
+    echo "$(grep --color=never "^-" "$1" | tr '\n' ' ')"
   fi
 }
```

not sure if this solution is platform-agnostic, maybe different OSes have different greps

**Comment by rjernst** [comment]
Isn't GREP_OPTIONS deprecated?

**Comment by talevy** [comment]
@rjernst that is what I found in the interwebs as well, but still operational in many systems today.

**Comment by talevy** [comment]
I understand if this is a noop since it is a very particular scenario for someone's custom bash hacks. It was an interesting enough debugging session I just experienced, that I thought it would help to at least document this potential situation somewhere

**Comment by jasontedor** [comment]
Duplicates #18644

**Comment by talevy** [comment]
ah, thanks @jasontedor. didn't find that one before posting this. looks like that is settled.
