### ISSUE TITLE
Unhelpful grok error when grok pattern contains spaces around colons

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#22844]
**Elasticsearch version**: 5.1.1

**Description of the problem including expected versus actual behavior**: A grok pattern with spaces around the colon delimiters causes an error, but the error doesn't explain what caused the problem.

To clarify, I added the spaces around the colons to make the pattern easier for me to read. I'm not arguing this should be allowed, just suggesting that the error should make it easier for me to identify and fix the problem. 😄 

**Steps to reproduce**:
 
Run these queries in Kibana Console:

```
PUT _ingest/pipeline/grok_spaces
{
  "description": "Demo the unhelpful error when you specify a grok pattern with spaces",
  "processors": [
     {
      "grok": {
        "field": "method",
        "patterns": ["%{WORD: method}"]
      }
    }
  ]
}


POST _ingest/pipeline/grok_spaces/_simulate
{
  "docs" : [
    {
      "_source": {
        "method": "GET"
      }
    }
  ]
}
```

You'll get this error:

```
{
  "docs": [
    {
      "error": {
        "root_cause": [
          {
            "type": "exception",
            "reason": "java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Provided Grok expressions do not match field value: [GET]",
            "header": {
              "processor_type": "grok"
            }
          }
        ],
        "type": "exception",
        "reason": "java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Provided Grok expressions do not match field value: [GET]",
        "caused_by": {
          "type": "illegal_argument_exception",
          "reason": "java.lang.IllegalArgumentException: Provided Grok expressions do not match field value: [GET]",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "Provided Grok expressions do not match field value: [GET]"
          }
        },
        "header": {
          "processor_type": "grok"
        }
      }
    }
  ]
}
```

**Comment by original-brownbear** [comment]
I guess the way to fix this one would be to stop using the catchall regex to extract everything from the grok syntax:

```java
private static final String GROK_PATTERN =
            "%\\{" +
            "(?<name>" +
            "(?<pattern>[A-z0-9]+)" +
            "(?::(?<subname>[[:alnum:]@\\[\\]_:.-]+))?" +
            ")" +
            "(?:=(?<definition>" +
            "(?:" +
            "(?:[^{}]+|\\.+)+" +
            ")+" +
            ")" +
            ")?" + "\\}";
```

and instead parse the given grok code manually. Then we could give cleaner feedback here (and it would improve our ability to support a wider range of field names and such). The downside is that it moves us further away from LS which uses the same regex to read the grok code ...
Unassigned myself again, not sure if it's worth taking that kind of action here for now.

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
