### ISSUE TITLE
remove DocumentMapper#parse that is only used by tests

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#22840]
While working on #22691, I noticed that there is a version of DocumentMapper#parse that is only ever used by tests, but is present in our main source code.

```
public ParsedDocument parse(String index, String type, String id, BytesReference source)
```

It seems like this method should be removed so we have a single parse method or moved to test code.

**Comment by AdityaJNair** [comment]
Hi just made a pull request regarding this issue. Can you please have a review over this?
Thanks
