### ISSUE TITLE
MLT Query Unlike clause issue

### ISSUE THREAD

**Issue by SKumarMN** [elastic/elasticsearch#22852]
**Elasticsearch version**: 5.0.2

**Plugins installed**: [ None]

**JVM version**: 1.8

**OS version**: Windows 7

**Description of the problem including expected versus actual behavior**:
The text/ document in "unlike" query is not influencing the MLT query

Data : 

{ "index":  { "_index": "library", "_type": "book","_id":1 }}
{"title":"Magic Of Thinking Big", "description":"Millions of people throughout the world have improved their lives using The Magic of Thinking Big. Dr. David J. Schwartz, long regarded as one of the foremost experts on motivation, will help you sell better, manage better, earn more money, and—most important of all—find greater happiness and peace of mind." }
{ "index":  { "_index": "library", "_type": "book","_id":2 }}
{"title":"The Power of Positive Thinking", "description":"The book describes the power positive thinking has and how a firm belief in something, does actually help in achieving it" }
{ "index":  { "_index": "library", "_type": "book","_id":3 }}
{"title":"Think and Grow Rich", "description":"Think And Grow Rich has earned itself the reputation of being considered a textbook for actionable techniques that can help one get better at doing anything, not just by rich and wealthy, but also by people doing wonderful work in their respective fields. " }
{ "index":  { "_index": "library", "_type": "book","_id":4 }}
{"title":"The Magic of thinking Big", "description":"First published in 1959, David J Schwartz's classic teachings are as powerful today as they were then. Practical, empowering and hugely engaging, this book will not only inspire you, it will give you the tools to change your life for the better - starting from now." }
{ "index":  { "_index": "library", "_type": "book","_id":5 }}
{"title":"How to Stop Worrying and Start Living", "description":"The book is written to help readers by changing their habit of worrying. The author Dale Carnegie has shared his personal experiences, wherein he was mostly unsatisfied and worried about lot of life situations." }
{ "index":  { "_index": "library", "_type": "book","_id":6 }}
{"title":"Practicing The Power Of Now", "description":"To make the journey into The Power of Now we will need to leave our analytical mind and its false created self, the ego, behind." }

Query:
{ 
    "query": {
        "more_like_this" : {
            "like" :[
            {
                "_index" : "library",
                "_type" : "book",
                "_id" : "3"
            }],
            "unlike":"leave our analytical mind",
            "min_term_freq" : 2,
            "min_doc_freq":2
        	
        }
    }
}

Response: 

{
  "took": 25,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 3,
    "max_score": 0.13702196,
    "hits": [
      {
        "_index": "library",
        "_type": "book",
        "_id": "2",
        "_score": 0.13702196,
        "_source": {
          "title": "The Power of Positive Thinking",
          "description": "The book describes the power positive thinking has and how a firm belief in something, does actually help in achieving it"
        }
      },
      {
        "_index": "library",
        "_type": "book",
        "_id": "6",
        "_score": 0.13702196,
        "_source": {
          "title": "Practicing The Power Of Now",
          "description": "To make the journey into The Power of Now we will **need to leave our analytical** mind and its false created self, the ego, behind."
        }
      },
      {
        "_index": "library",
        "_type": "book",
        "_id": "4",
        "_score": 0.09183437,
        "_source": {
          "title": "The Magic of thinking Big",
          "description": "First published in 1959, David J Schwartz's classic teachings are as powerful today as they were then. Practical, empowering and hugely engaging, this book will not only inspire you, it will give you the tools to change your life for the better - starting from now."
        }
      }
    ]
  }
}

Even though "leave our analytical mind" text is used in "unlike" clause, the returned results still contain documents with those terms

**Comment by clintongormley** [comment]
The `unlike` parameter is used to ensure that any of the words listed are not used as `like` terms.  It doesn't exclude documents that contain those terms.

Also, in this example you are running MLT with far too few docs.  If you examine the query that is actually being run, you will see that it is only searching for `and` and `by`:

```
PUT library
{
  "settings": {
    "number_of_shards": 1
  }
}

POST _bulk
{ "index": { "_index": "library", "_type": "book","_id":1 }}
{"title":"Magic Of Thinking Big", "description":"Millions of people throughout the world have improved their lives using The Magic of Thinking Big. Dr. David J. Schwartz, long regarded as one of the foremost experts on motivation, will help you sell better, manage better, earn more money, and—most important of all—find greater happiness and peace of mind." }
{ "index": { "_index": "library", "_type": "book","_id":2 }}
{"title":"The Power of Positive Thinking", "description":"The book describes the power positive thinking has and how a firm belief in something, does actually help in achieving it" }
{ "index": { "_index": "library", "_type": "book","_id":3 }}
{"title":"Think and Grow Rich", "description":"Think And Grow Rich has earned itself the reputation of being considered a textbook for actionable techniques that can help one get better at doing anything, not just by rich and wealthy, but also by people doing wonderful work in their respective fields. " }
{ "index": { "_index": "library", "_type": "book","_id":4 }}
{"title":"The Magic of thinking Big", "description":"First published in 1959, David J Schwartz's classic teachings are as powerful today as they were then. Practical, empowering and hugely engaging, this book will not only inspire you, it will give you the tools to change your life for the better - starting from now." }
{ "index": { "_index": "library", "_type": "book","_id":5 }}
{"title":"How to Stop Worrying and Start Living", "description":"The book is written to help readers by changing their habit of worrying. The author Dale Carnegie has shared his personal experiences, wherein he was mostly unsatisfied and worried about lot of life situations." }
{ "index": { "_index": "library", "_type": "book","_id":6 }}
{"title":"Practicing The Power Of Now", "description":"To make the journey into The Power of Now we will need to leave our analytical mind and its false created self, the ego, behind." }

GET library/_validate/query?explain&rewrite
{
  "query": {
    "more_like_this": {
      "fields": ["title","description"], 
      "like": [
        {
          "_index": "library",
          "_type": "book",
          "_id": "3"
        }
      ],
      "unlike": "leave our analytical mind",
      "min_term_freq": 2,
      "min_doc_freq": 2
    }
  }
}
```

returns explanation:

    "(description:and description:by) -ConstantScore(_uid:book#3)"

**Comment by apeteri** [comment]
@clintongormley, it looks like the example appearing in the documentation is slightly misleading in this case. The [parameters section](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html#_document_input_parameters) states the following:

> The `unlike` parameter is used in conjunction with `like` in order not to select terms found in a chosen set of documents. In other words, we could ask for documents `like: "Apple"`, but `unlike: "cake crumble tree"`. The syntax is the same as `like`. 

From your description and looking at the implementation, `unlike` is only capable of excluding terms added to `like` from documents or string literals, but not from the result set (this is what you wrote above) or the top "`max_query_terms`" number of SHOULD clauses that ultimately drive the MLT search (this is what I imagined reading the documentation).
