### ISSUE TITLE
FieldStatsResponse.getIndicesMergedFieldStatus returns unchecked FieldStats

### ISSUE THREAD

**Issue by trejkaz** [elastic/elasticsearch#22854]
**Elasticsearch version**:

2.4.1, 5.1.2

**Plugins installed**: []

n/a

**JVM version**:

n/a

**OS version**:

n/a

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Have some code referencing FieldStatsResponse. e.g.:

            FieldStatsResponse response = getClient().prepareFieldStats()
                                                     .setIndices(getIndexId(IndexIdCategory.ITEM))
                                                     .setLevel("indices")
                                                     .setFields(STORE_SPECIFIC_ID)
                                                     .get();

            Map<String, Map<String, FieldStats>> stats = response.getIndicesMergedFieldStats();

An unchecked warning shows up on the FieldStats because we have not specified its type parameter.

Now try to fix it:

            Map<String, Map<String, FieldStats<Long>>> stats = response.getIndicesMergedFieldStats();

Now you'll get a compilation error. It turns out that getIndicesMergedFieldStats() also references it without the parameter:

        public Map<String, Map<String, FieldStats>> getIndicesMergedFieldStats() {
            return this.indicesMergedFieldStats;
        }

I'd like it to return the type parametrised.

The workaround is probably to cast to Map<?> and then back to the more correct type, and slap an unchecked warning suppression on the line with the cast.

**Comment by jimczi** [comment]
Thanks for the report @trejkaz 
You are right, we should always return `FieldStats<?>`. 

> I'd like it to return the type parametrised.

This is not possible, the returned object is a view per index of all field stats. The cast to `Long` is not permitted at this point so instead you could maybe just check the object returned by these functions?:
`````
FieldStats#getMinValue
FieldStats#getMaxValue
`````

**Comment by trejkaz** [comment]
Ah... in the case of our example, we know it's a Long, because we'd only asked for one field which we know the type of. But `FieldStats<?>` would probably be fine too, at least we could remove the warning without funny tricks.

**Comment by martijnvg** [comment]
Closing this issue, because the field stats api has been deprecated and removed from master and 6.x branch in favour of the field caps api.
