### ISSUE TITLE
Should task descriptions be generated only when read?

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#22866]
Right now most `Task`s generate their descriptions when the tasks are created. A few tasks generate the descriptions on the fly because the descriptions are large, but sometimes we don't catch all the large ones (see #22832). Maybe it'd be cleaner if *all* tasks always generated their descriptions on the fly. This would probably save a few allocations, especially given that most of the time the descriptions are not read.

**Comment by nik9000** [comment]
@imotov, what do you think?

**Comment by imotov** [comment]
@nik9000 This is a tough one. I was going back on forth on it for quite a while. Generating descriptions on the fly will force all tasks to keep pointers to their requests for the entire life of a task. I am not sure we want that for some very large requests (bulk api request on coordinating node for example) either.

**Comment by nik9000** [comment]
Yeah, we don't want to keep a reference to the request for the lifetimes if we can help it. But I think we should avoid allocating strings for the description unless we can help it too.... Hard indeed.

**Comment by nik9000** [comment]
We talked a bit over on https://github.com/elastic/elasticsearch/pull/22832 and decided to make `Task#getDescription` abstract to force all implementers to think about it what the description should be and how long it will get and whether or not to make it on the fly.

**Comment by sabi0** [comment]
@nik9000 In #22832 it was mentioned that `ReplicationRequest#getDescription` should be made abstract, not `Task#getDescription`. Which one is it then?

P.S. Even though `SearchRequest` generates task description lazily, the task keeps the reference for a (potentially) large `source` (and the original request). Shouldn't that be changed in a way similar to #22832 ?
(as far as I can tell this is the only "lazy" description; there are no other overrides of `Task#getDescription`)

**Comment by nik9000** [comment]
> @nik9000 In #22832 it was mentioned that ReplicationRequest#getDescription should be made abstract, not Task#getDescription. Which one is it then?

`Task#getDescription`, I think. @imotov, what do you think?

You are right about search holding on to a reference. Personally I'm ok with holding on to a reference here but I'm willing to be convinced it isn't a good idea.

**Comment by imotov** [comment]
@nik9000 if we want to make it lazily evaluated, that's the way to do it. Unfortunately, it will mean that we will have to override createTask for every single request and override getDescription in there. That's a lot of changes, but they should be pretty simple, it will also simplify the structure, a bit since we can remove `Request#getDescription` completely then.

**Comment by sabi0** [comment]
Sorry, I am not sure I followed you correctly - what is the intended benefit of this refactoring?
Saving some memory on never used Strings? But wouldn't keeping a reference to the whole request undermine this intention? (I am not familiar with `Request` / `Task` lifecycles)
Or did you mean to save some CPU cycles on Strings concatenation?

**Comment by bleskes** [comment]
I'm closing this for now as it has been stale for a while. If the need arises to do this, we can' revisit.
