### ISSUE TITLE
Centralise URL whitelisting

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#22860]
Today we have URL whitelists for reindex and for URL repositories, we don't have them for S3, Azure, HDFS etc.

Instead, we should provide a centralised URL whitelist which can be used by all of these services.

**Comment by maddin2016** [comment]
Something like `node/cluster.whitelist` which is initialized at startup?

**Comment by clintongormley** [comment]
It'd be settings in the conf.yaml (like the whitelists today)

**Comment by maddin2016** [comment]
So there should be 3 tasks

1. Create this Setting

1. Change existing services to use this  setting

1. Make it available for Plugins (S3, Azure, ...)

What about the naming of this setting `node[or]cluster.whitelist`?

**Comment by nik9000** [comment]
I'm not sure about the name. One other task is to pull the whitelist
checking code to a common spot. I think we want the checking in reindex
applied to all the places where you can configure a URL over the API.

**Comment by dadoonet** [comment]
I'm unsure about whitelisting in a global place for all the plugins TBH.

Let say I need to access:

* `http://foo.com` URL repo
* `/path/to` Shared FS
* `foo.bar` S3 bucket
* `foo.bar/container` Azure container
* `/hdfsservice/foo/bar` HDFS repo

What would the whitelist look like? Something like:

```yml
cluster.whitelist: [ "http://foo.com", "/path/to", "foo.bar", "foo.bar/container", "/hdfsservice/foo/bar" ]
```

I'm afraid we can mix settings which does not express the same kind of "url". 
Like what will happen to Shared FS repo if someone tries to create a repository under a `/hdfsservice/foo/bar` dir name?

Can we think of something like:

```yml
cluster.whitelist: 
  url: [ "http://foo.com" ]
  fs: [ "/path/to" ]
  s3: [ "foo.bar" ]
  azure: [ "foo.bar/container" ]
  hdfs: [ "hdfs://hdfsservice/" ]
```

Where each plugin (or core repo) declares or not the settings if it needs to support it?

**Comment by nik9000** [comment]
I was thinking just URL whitelisting. I think we have enough URLs around to make that a thing.

Are the other settings all things we configure over the API? I guess they are.

**Comment by maddin2016** [comment]
I found that idea from @dadoonet nice to prefix each setting. This makes it a lot easier to separate and filter them. Is it ok to put this all into one PR?

**Comment by ywelsch** [comment]
We discussed this on Fixit Friday and had a concern: Having a centralised whitelist would provide less control over what each plugin can do. For example, you might want to allow reindexing from a remote address (i.e. only receive data from that remote address), but might not like to send your data there as part of a snapshot.
