### ISSUE TITLE
Make it possible to configure the number of mantissa bits on half floats, floats, doubles

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#22886]
Say you want to store latencies in a field. Typical values are small but there are also some outliers. You have 3 choices:
 - `half_float`, but the fact that it has a very limited range of values (max value is 65504) means that outliers might be converted to `POSITIVE_INFINITY`,
 - `scaled_float`, but the outliers will unfortunately raise the number of bits for everyone in doc values due to how doc values work
 - `float` will work fine, but ideally we'd like something more space-efficient

The way `float` and `half_float` work is better suited than `scaled_float` for latencies since millisecond accuracy is important for small latencies, but second precision is probably more than enough for latencies of several minutes.

I think we could make Elasticsearch better at storing latency-style data by making it possible to configure the number of mantissa bits. For instance floats use 24 bits for their mantissa, which translates to roughly 7 significant figures. But if we assume that 3 decimal digits are enough, which I suppose would be true for lots of users, then 10 mantissa bits would be enough, so we could store those floats on 18 bits instead of 32.

Maybe we could figure out a way to expose such floats. I guess one way would be to add new types and another way would be to add options to the existing `half_float`, `float` and `double` types. One good news is that we could make it work it in such a way that it only requires changes at index time by rounding float values to the closest float that has at least X trailing zeros. Then Lucene would compress it using existing GCD compression (that it uses for dates today).

**Comment by maddin2016** [comment]
Hi @jpountz, do you mean something like this. For example we pass a param precision of 3, 4, 5, ...
```
3 digits -> 123.4567 -> 123
4 digits -> 123.4567 -> 123.5
5 digits -> 123.4567 -> 123.457
```

**Comment by jpountz** [comment]
@maddin2016 I think you meant 6 digits on the last line, but that is the idea indeed.

**Comment by maddin2016** [comment]
Yeap, 6 digits :+1: . I would prefer to create an optional setting for types `float, double, half_float`, lets say `precision`.

**Comment by maddin2016** [comment]
Hi @jpountz, one question i have. We can't make a `float` smaller as `4 byte` or a double smaller as `8 byte`, right? If i understand you correctly we just round up/down and lucene take care of storing it as small as possible.
For example `1.4` is storing internaly as `1.399999976158142`. 
So we rounded to `1.390000000000000`?? Or do we search search for the nearest float with trailing zeros which is `1.44 -> 1.440000057220459`

**Comment by jpountz** [comment]
What you say is correct except that it would work on the binary representation of those numbers rather than their decimal representation.

You are right that floats cannot represent `1.4` accurately, and its actual value is `1.399999976158142`, which is stored internally as: `00111111101100110011001100110011`. The idea of this change would be to clear X trailing zeros. For instance if X is 16 (50% saving since floats use 32 bits), this gives us `00111111101100110000000000000000` (`1.3984375`), which is something that Lucene will efficiently compress.

**Comment by maddin2016** [comment]
Nice 👍. One thing i would discuss is the precision. If we say we store 3 digits, but have a value of `123.45` it is not better to define the scale and not the precision.

**Comment by maddin2016** [comment]
I have tested a litte bit. So lets say someone will store a latency of `12.456789` wich is `12 minutes`, `45 seconds` and `6789 milliseconds` and he say a precision of seconds is enough for me. So we can do the following
```java
        int bits = Float.floatToIntBits(12.456789f);
        int sign = bits >>> 31;
        int exp = (bits >>> 23 & ((1 << 8) - 1)) - ((1 << 7) - 1);
        int mantissa = bits & ((1 << 23) - 1);
        System.out.println(mantissa / Math.pow(2, 23) + 1);
        System.out.println(Integer.toBinaryString(mantissa));
        mantissa = mantissa & 0x7FF000;
        System.out.println(mantissa / Math.pow(2, 23) + 1);
        System.out.println(Integer.toBinaryString(mantissa));
        System.out.println(Float.intBitsToFloat((sign << 31) | (exp + ((1 << 7) - 1)) << 23 | mantissa));
```
which prints
```
1.557098627090454
10001110100111100000010
1.556640625
10001110100000000000000
12.453125
```

So you can see i have stolen 12 bits from mantissa bits. But this method is relative inflexible because i hardcode these 12 bits. So how we would set X stolen bits to come close to our second precision without become to inaccurate.

**Comment by jpountz** [comment]
> So lets say someone will store a latency of 12.456789 wich is 12 minutes, 45 seconds and 6789 milliseconds

Hmm this sounds wrong to me since there are 60 seconds per minute, not 100.

> So how we would set X stolen bits to come close to our second precision without become to inaccurate.

We would need to be able to compute X based on the acceptable precision, I think that should be doable? There will certainly be corner-cases however, like we should probably not touch NaN and infinities and be careful with subnormal floats.

**Comment by maddin2016** [comment]
🙈 on digit to much. Sorry, should be `12.45678`

**Comment by maddin2016** [comment]
@jpountz, if you can look at [this](https://gist.github.com/maddin2016/cf13521cef07f08661164442d59638e9) gist. (It's just an idea, so it's really hacky!!)

The idea behind this is the following

1. Extract our precision digits and convert them into a new float. In this example `45.55689` to `45.55` if we have a precision of 4.

1. Extract the mantissa bits from the new float and mask them with our original mantissa bits. And then set the bits that are equal until the first difference. After that set all bits to `0`. 
For example
`45.55896` -> **01101100011**110001100000
`45.55`              -> **01101100011**001100110011
becomes  `01101100011000000000000`

1. Then convert our `BitSet` to an integer an build the result which is `45.546875` `01101100011000000000000`

There are maybe better ways to do this, but i want to know if you think if this is the right way.

**Comment by jpountz** [comment]
I suspect this would not work all the time since some floats that you truncate based in base 10 might result in a float that has a different exponent, so the logic that finds the first different bit would be broken. Here is something that should be a good starting point if you are interested:

```java
int mantissaBits = 24; // 23 stored + 1 implicit
float f = 45.55689f;
int significantDigits = 4;
// significantBits = log2(10^significantDigits)
int significantBits = (int) Math.ceil(Math.log(Math.pow(10, significantDigits)) / Math.log(2));
int fBits = Float.floatToIntBits(f);
// TODO: this is only truncating, it should round to nearest even instead
// TODO: handle NaN, infinities and subnormal floats
int mask = ~0 << (mantissaBits - significantBits);
int roundedBits = fBits & mask;
float rounded = Float.intBitsToFloat(roundedBits);
System.out.println(f + " got rounded to " + rounded);
```

**Comment by maddin2016** [comment]
Hi @jpountz, i currently struggling with this. You are right that we have to round that new float because if we truncate it gives us a completely different value `45.554688`. Here we get one digit more!! Problem is that i have no idea how we can round to the nearest even without touching our digits that we have to cut off (in this case 10) and getting a float that has the same length. I have read [this](http://pages.cs.wisc.edu/~markhill/cs354/Fall2008/notes/flpt.apprec.html) but it doesn't brings me further 😩

**Comment by jpountz** [comment]
Yes, floating-point bits manipulations can be a bit tricky... On my end I am fine with not having rounding working perfectly from the first iteration, there are other challenges that need to be addressed in the integration as well. For instance the way we convert floats to sortable ints with `NumericUtils.floatToSortableInt` means that we will need to be careful with negative values, or their sortable int representation will end up with lots of 1s while we are looking for 0s. If you really want to tackle this issue I have no objections, but it might be better to try and tackle an easier one first.

**Comment by maddin2016** [comment]
Hi @jpountz, i also think this one is not the easiest and requires more knowledge on this topic. Anyway thanks for the explanations and i'm curious how the solution will look.

**Comment by javanna** [comment]
@elastic/es-search-aggs

**Comment by javanna** [comment]
No progress was made on this issue for a very long time. Closing this as it is currently not on our radar.
