### ISSUE TITLE
lt and gt with floats does not work.

### ISSUE THREAD

**Issue by hecrogu** [elastic/elasticsearch#22880]
**Elasticsearch version**: 5.1.2

**Plugins installed**: []

**JVM version**: 1.8.0_111"

**OS version**: Debian GNU/Linux 8 

**Description of the problem including expected versus actual behavior**:
Range query does not work properly. I have an index with a float field, I called it 'analysis_time'.
I create a query to search between 2 values, using gte and lt. Here is my query:

```
{
  "query": {
    "range": {
      "analysis_time": {
        "lt": <float-value>,
        "gte": <float-value>
      }
    }
  }
}

```
I established a range between 2 float number, for example 
        "lt": 1485851711.686809,
        "gte": 1485850431.424259

I have 2 documents with 2 float_values in that range: 1485850431.424259 and 1485851710.686809, so when I execute the query both should be returned, but only 1 its return to me (1485850431.42425).

If i change the lt for lte, does not work too.

**Steps to reproduce**:
 1. Create a index and store documents with this float values: 
```
 curl -X PUT <elastic-host><index_name>/1/_create -d'{"analysis_time":1485851710.686809}
 curl -X PUT <elastic-host><index_name>/1/_create -d'{"analysis_time":1485850431.424259}
```
 2. Execute the query:
curl -X POST <elastic-host><index_name>/_search -d'{
  "query": {
    "range": {
      "analysis_time": {
        "lt": 1485851711.686809,
        "gte": 1485850431.424259
      }
    }
  }
}'
 3. Check that only 1 hit is returned.

4. Execute the query:
curl -X POST <elastic-host><index_name>/_search -d'{
{
  "query": {
    "range": {
      "analysis_time": {
        "lte": 1485851709.686809
      }
    }
  }
}
4. Check that 2 hits are returned and only 1 should be returned (1485850431.424259)

**Comment by jimczi** [comment]
We reserve github for bugs and feature request. You should ask your question in the forum directly:
https://discuss.elastic.co/c/elasticsearch

Regarding your issue 'lt' stands for "lesser than" so if you have `lt: 1485851711.686809` documents with that value are not returned. If you change `lt` to `lte` then the two documents should show up. Though you're not creating the documents correctly. Doing:
````
curl -X PUT <elastic-host><index_name>/1/_create -d'{"analysis_time":1485851710.686809}
````
means that you put a document in the index `index_name` with type set to `1`. The `_id` of the document is the last part of the path so in your recreation it will be `_create`. This `_id` is a unique identifier in this index so when you try to put a second document with the same `_id` it will remove the first version and replace it with the new document.

**Comment by hecrogu** [comment]
My bad writing the steps to reproduce, but i create rigth both documents, I edit the post. This is a bug @jimczi, try to reproduce.

**Comment by jimczi** [comment]
@hecrogu it's just that you should index your values with `double`s not `float`s, your numbers are not accurately encoded when translated to a float value.
For instance the value `1485851710.686809` is mapped to the float value: `1485851648` which explain why your query does not return the expected hits.
