### ISSUE TITLE
Range query with floats fields does not work

### ISSUE THREAD

**Issue by hecrogu** [elastic/elasticsearch#22882]
**Elasticsearch version**: 5.1.2

**Plugins installed**: []

**JVM version**: 1.8.0_111"

**OS version**: Debian GNU/Linux 8 

**Description of the problem including expected versus actual behavior**:
Range query does not work properly. I have an index with a float field, I called it 'analysis_time'.
I create a query to search between 2 values, using gte and lt. Here is my query:

```
{
  "query": {
    "range": {
      "analysis_time": {
        "lt": <float-value>,
        "gte": <float-value>
      }
    }
  }
}

```
I established a range between 2 float number, for example 
        "lt": 1485851711.686809,
        "gte": 1485850431.424259

I have 2 documents with 2 float_values in that range: 1485850431.424259 and 1485851710.686809, so when I execute the query both should be returned, but only 1 its return to me (1485850431.42425).

If i change the lt for lte, does not work too.

**Steps to reproduce**:
 1. Create a index and store documents with this float values: 
```
 curl -X PUT <elastic-host><index_name>/1/_create -d'{"analysis_time":1485851710.686809}
 curl -X PUT <elastic-host><index_name>/2/_create -d'{"analysis_time":1485850431.424259}
```
 2. Execute the query:
curl -X POST <elastic-host><index_name>/_search -d'{
  "query": {
    "range": {
      "analysis_time": {
        "lt": 1485851711.686809,
        "gte": 1485850431.424259
      }
    }
  }
}'
 3. Check that only 1 hit is returned.

4. Execute the query:
curl -X POST <elastic-host><index_name>/_search -d'{
{
  "query": {
    "range": {
      "analysis_time": {
        "lte": 1485851709.686809
      }
    }
  }
}
4. Check that 2 hits are returned and only 1 should be returned (1485850431.424259)

**Comment by clintongormley** [comment]
Floating point numbers create dynamic fields of type `float`.  Your numbers are too big to fit into a float while retaining their precision, so they are rounded.  If you change your field type to `double`, then it works.

**Comment by AmrSoliman** [comment]
the same issue repeated with me, query is like 
`{
  "query": {
    "range": {
      "rating": {
        "lt": 5,
        "gte": 4.5
      }
    }
  }
}`
but the results were documents with rating 5 onlyin same time there were documents with 4.7, 4.8 and 4.9.
i got those results after changing gte to 4 instead of 4.5
@clintongormley

**Comment by distroid** [comment]
I have a same problem. I'm trying to filter from 6.5 to 6.5
```
"range": {
  "518": {
    "lt": 6.5,
    "gte": 6.5
  }
}
```
and i got in results records with 6, 6.6, 6.8 and etc. How fix it? @clintongormley

**Comment by nerdvegas** [comment]
Why is this closed? I'm having the same issue.

**Comment by forexknight** [comment]
I'm having the same issue as @distroid .

**Comment by Zerozzzz** [comment]
My problem resolved by changed field type to double
