### ISSUE TITLE
Elastic search query doesnt support enum?

### ISSUE THREAD

**Issue by moghimire** [elastic/elasticsearch#22885]
I've enum QFields like this:

```
public enum QFields {
	
	TITLE("title"),
	DESCRIPTION("description");
	

	private String fieldName;

	private QFields(String fieldName) {
		this.fieldName = fieldName;
	}
}
```

And when i query like this
```QueryBuilders.boolQuery().must(QueryBuilders.multiMatchQuery("hello there", QFields.TITLE.toString(), QFields.DESCRIPTION.toString()));```

Instead of lowercase title, description it does query on Uppercase.

I'm using Elasticsearch 5.1.2

Thanks

**Comment by javanna** [comment]
This is not an Elasticsearch problem the default implementation of `toString` for enums is to return what `name()` returns, which is uppercase. I would add a `fieldName` getter to your enum or change its `toString` to return `fieldName` rather than `name()`
