### ISSUE TITLE
Build tries to run Java 8+ 'jjs' command before checking the Java version

### ISSUE THREAD

**Issue by sabi0** [elastic/elasticsearch#22898]
Gradle itself was run on Java 8, but JAVA_HOME was pointing to Java 7.
The build failed with "Cannot run program "C:\applications\jdk1.7.0\bin\jjs" (in directory "C:\development\Projects\elasticsearch\benchmarks"): CreateProcess error=2, The system cannot find the file specified"

There is a check for minimal Java version with proper error message - see lines 130 and further in `BuildPlugin.groovy`. But the Java version retrieval `javaVersionDetails = findJavaVersionDetails(project, javaHome)` (BuildPlugin.groovy:101) uses `jjs` command which is only available in Java 8+.

**Comment by sabi0** [comment]
I also think `findJavaHome()` in `BuildPlugin.groovy` should make use of `org.gradle.java.home` property. Rather than rely solely on JAVA_HOME environment variable.

This would allow more flexibility in specifying which JDK to use for building.
(via `gradle.properties` or with `-Dorg.gradle.java.home=/JDK_PATH` on the command line)

**Comment by rjernst** [comment]
> Gradle itself was run on Java 8

Gradle uses JAVA_HOME, so it would have been running in java 7. If you have org.gradle.java.home set, then it will briefly start on that java from JAVA_HOME, and fork to the java that was specified.  This is how we test with java 9 (gradle running on java 8, JAVA_HOME set to java 9, which is what the compile/tests use, and why findJavaHome uses only JAVA_HOME, by design).

There isn't much we can do with java 7 and before, as far as detecting them. Or rather, I don't think we should have any special logic to support giving a nice error message there, since, for example, java 7 has been EOL for almost 2 years.

**Comment by sabi0** [comment]
Fair enough.
But there _is_ logic to check the minimal Java version. But if the version is < than minimal that code will never be executed. Because the plugin will fail earlier while trying to _retrieve Java version_ (using `jjs` command).

In my case I was running Gradle from IDEA. And there is a separate 'Gradle JDK' setting there. So Gradle was running with Java 8 while JAVA_HOME was still pointing to Java 7.
So effectively 'elasticsearch.build' plugin is incompatible with IntelliJ IDEA when JAVA_HOME points to Java 7.
(even thought running Gradle from command line will work fine due to `org.gradle.java.home`)

**Comment by rjernst** [comment]
> So effectively 'elasticsearch.build' plugin is incompatible with IntelliJ IDEA when JAVA_HOME points to Java 7.

This cannot work. JAVA_HOME must point to java 8 or later, because, regardless of which version of java gradle uses via org.gradle.java.home (which still must be java 8, if set), the java pointed to by JAVA_HOME is used to compile and test ES.

**Comment by sabi0** [comment]
You obviously know it better.
My point was that minimal Java version checking code does not make much sense since it needs that very same minimal version to just determine the version number for comparison.

**Comment by rjernst** [comment]
@sabi0 Let me see if I can do a preliminary check using gradle's builtin java version detection.

**Comment by rjernst** [comment]
@sabi0 Using gradle's java version isn't possible, but I at least improved the error you see: #22911

**Comment by sabi0** [comment]
By the way `jrunscript -f es-gradle-tmp.js` works the same as `jjs es-gradle-tmp.js` and is available even on Java 6.

**Comment by sabi0** [comment]
Moreover, you could do even this:
`jrunscript -e 'print(java.lang.System.getProperty("java.specification.version"));'`
and don't bother with creating / deleting temporary files.

**Comment by sabi0** [comment]
Here
```groovy
    private static String runJavascript(Project project, String javaHome, String script) {
        ByteArrayOutputStream output = new ByteArrayOutputStream()
        project.exec {
            executable = new File(javaHome, 'bin/jrunscript')
            args = [ '-e', script ]
            standardOutput = output
            errorOutput = new ByteArrayOutputStream()
        }
        return output.toString('UTF-8').trim()
    }
```

But you'd then have to 'double-escape' the double quotes in the scripts:
`String versionScript = 'print(java.lang.System.getProperty(\\"java.version\\"));'`

**Comment by sabi0** [comment]
By the way, the 'Java 1.8 or above is required ...' error message could mention JAVA_HOME.

Otherwise it might be not so clear where the the wrong version comes from.
E.g. when running Gradle from IDEA (with Java 8) it only shows the exception message, not the 'Elasticsearch Build Hamster' output before it.

**Comment by rjernst** [comment]
@sabi0 Thank you! I had never heard of `jrunscript`. I like that much better.

**Comment by sabi0** [comment]
FYI: When I was trying `jrunscript` approach on Windows (with Gradle 2.13) I discovered that quotes in the arguments weren't escaped. So build would try to run the following command:
`bin/jrunscript -e "print(java.lang.System.getProperty("java.version"));"`
And it would fail with exit code 10.

To fix this I had to double-escape the quotes myself (as one escaping level is removed by Groovy):
```groovy
String versionScript = 'print(java.lang.System.getProperty(\\"java.version\\"));'
return runJavascript(project, javaHome, versionScript)
```
Then the command was executed successfully:
`bin/jrunscript -e "print(java.lang.System.getProperty(\"java.version\"));"`
