### ISSUE TITLE
Support for remote path in reindex api

### ISSUE THREAD

**Issue by huawangpp** [elastic/elasticsearch#22913]
**Elasticsearch version**: 5.x

**Plugins installed**: []

**JVM version**: 

**OS version**:

**Describe the feature**:
In the 5.x reindex api, support for remote is added, e.g, 
POST _reindex
{
  "source": {
    "remote": {
      "host": "http://otherhost:9200",
      "username": "user",
      "password": "pass"
    },
...

However the host property is strictly enforced to three parts, scheme, host and port. We host elasticsearch behind a proxy and need the ability to specify a path too. I found code in https://github.com/elastic/elasticsearch/blob/v5.2.0/modules/reindex/src/main/java/org/elasticsearch/index/reindex/RestReindexAction.java, that enforces this rule.

...
 private static final Pattern HOST_PATTERN = Pattern.compile("(?<scheme>[^:]+)://(?<host>[^:]+):(?<port>\\d+)");
...

Can we add the support for path?

**Comment by nik9000** [comment]
> Can we add the support for path?

Is everything in elasticsearch prefixed with some path? Like `curl -XGET proxy/elasticsearch` gets root url and `curl -XPOST proxy/elasticsearch/test/_search` is how you'd do a search? If so, path prefix wouldn't be too hard to add.

**Comment by clintongormley** [comment]
a path prefix is supported by most of the REST clients too (including the Java REST client)

**Comment by huawangpp** [comment]
@nik9000, the url is like http://host:port/path for us. There is no additional elasticsearch needed in the url, e.g,  curl -XPOST proxy/test/_search

**Comment by Alsyia** [comment]
We are accessing ES endpoints through a reverse proxy, and this would be really useful.

**Comment by ajhewett** [comment]
Just got bitten by this.  We also have ES endpoints behind reverse proxies and are not able to use them as a source for remote reindex.
Our url is like http://host:port/elasticsearch

**Comment by quirogadf** [comment]
Also a problem for us since we keep elastic behind a load balancer.

**Comment by suraj-soni** [comment]
Any updates on this ? I just got bitten by this one as well
