### ISSUE TITLE
Remove `ScriptDocValues#getValues`

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#22919]
I expect `ScriptDocValues#getValues` was added for backwards compatibility a long time ago but at this point I don't think we need it. At this point everything every script that does `doc.foo.values.something` can do `doc.foo.something` instead.

Should we drop `ScriptDocValues#getValues` in 6.0?

**Comment by clintongormley** [comment]
+1 (with appropriate deprecation logging)

**Comment by nik9000** [comment]
Talked among a small group - we're fine with removing. I'll put together a change to deprecate in 5.x and remove in 6.0.

**Comment by jdconrad** [comment]
@nik9000 Was this ever completed?

**Comment by nik9000** [comment]
No, but it feels like a legit thing we should do. Like, we should deprecate it in 6.x and remove in master.

**Comment by j-haj** [comment]
I am interested in taking a look at this. @nik9000 can you give some direction? It seems like the plan was to deprecate and remove some time in 6.x. However, we are already at 6.4 and it doesn't seem like the deprecation warnings were ever added. At this point, are we only interested in adding deprecation info?

**Comment by nik9000** [comment]
Right @j-haj! We've traditionally done this sort of thing in a two phase process:
1. Merge a PR that adds a deprecation warning to `getValues` to both 6.x and master.
2. Merge a PR that drops the `getValues` entirely just to master.

We do this because it keeps 6.x as "mostly backports of stuff in master" and it allows us to always develop against master. So if you'd like to take this then step 1 is deprecating `getValues`.

One important thing: on `DeprecationLogger` there is a `deprecated` and a  `deprecatedAndMaybeLog` method. Use `deprecatedAndMaybeLog` because it'll be *much* faster. It is quite common for search scripts to run millions of times per request and the savings really adds up.

**Comment by j-haj** [comment]
Perfect - I will get working on this and comment if I have any questions.

**Comment by j-haj** [comment]
@nik9000 I have added a call to `deprecatedAndMaybeLog` to `ScriptDocValues#getValues`. The message I am logging says "Deprecated getValues used" - I was not sure what else should be said. Summarizing the comment at the top of this thread seemed excessive. Is there anything else that should be communicated to the user?

Also, `ScriptDocValues#getValue` should be left as is, right?

**Comment by nik9000** [comment]
> Also, `ScriptDocValues#getValue` should be left as is, right?

That depends on who you ask! Some of us aren't big fans of it to be honest. `ScriptDocValues` is a list and not treating it like one is kind of a problem. But one thing at a time.

> I am logging says "Deprecated getValues used" - I was not sure what else should be said. Summarizing the comment at the top of this thread seemed excessive. Is there anything else that should be communicated to the user?

I think it'd be good to say something about how `getValues` isn't needed and you should just leave it out but I don't really know how to say it properly. `getValues doesn't do anything` doesn't quite convey that you can just drop it out of the calls.

**Comment by j-haj** [comment]
Perfect - I can work with that and will have a PR out later this morning.

**Comment by nik9000** [comment]
I closed this without thinking earlier today. The issue isn't resolved by #34279. I'm not as good at reading as I thought!

**Comment by rjernst** [comment]
This was removed in #36183
