### ISSUE TITLE
Not enable to use Java API for create a Graph 

### ISSUE THREAD

**Issue by ahr12** [elastic/elasticsearch#22927]
ElasticSearch - 5.1.2
Kibana - 5.1.2
Java 1.8 oracle
OS- Ubuntu 14.04
Hello,
I am new in ElasticSearch. I am trying to create the graph of my data file and I already make a graph using the Kibana but edges do not connect properly.Can you tell me the query for making a graph in ElasticSearch and it will be good if I get some examples?

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
