### ISSUE TITLE
Improve ElasticsearchException metadata rendering and parsing

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#22928]
When rendered as `ToXContent`, ElasticsearchException can print out additional metadata using the `metadataToXContent(XContentBuilder builder, Params params)` method. For example, this is used by parsing exceptions to report the line & column of violations or by circuit breaker exceptions to report an exceeded limit. Other exceptions like `SearchPhaseExecutionException` also prints out complex objects like shard failures. But ElasticsearchException also provides support for metadata through the `addMetadata()` method. 

So we could change the internal Map<String, List<String>> to also supports numbers and booleans and then change subclasses that add simple metadata using metadataToXContent() to using addMetadata() directly. Then we could also add support for parsing other types than String/List of string in the `fromXContent() `method.

**Comment by Jingw98** [comment]
I will try to improving it

**Comment by liketic** [comment]
@tlrx Is this need to fix? I think I can take this. Thanks.

**Comment by tlrx** [comment]
@liketic Yes, it's still something that can be improved.

**Comment by liketic** [comment]
@tlrx Thanks for your reply. So the target is removing `metadataToXContent()` and only support `addMetadata()`?

**Comment by DaveCTurner** [comment]
@liketic yes, that sounds like a sensible goal to work towards. See also #27672 for a wider issue.

**Comment by nik9000** [comment]
> So we could change the internal Map<String, List> to also supports numbers and booleans and then change subclasses that add simple metadata using metadataToXContent() to using addMetadata() directly. Then we could also add support for parsing other types than String/List of string in the fromXContent()method.

I read this and thought we should go the other way. I feel like we could make `metadataToXContent` and the parser consistent more easily then a `Map`. I feel like we'd have tighter control over what belongs in the fields then too.

**Comment by nik9000** [comment]
I see now. The `Map` way lets us add the metadata without adding extra exceptions. Adding custom exceptions is fairly heavy in Elasticsearch because they have to be thrown across the wire. It really isn't worth adding them just for some fields. Probably.

**Comment by dakrone** [comment]
I'm going to close this one, as we've removed the high level rest client in favor of the Java client.
