### ISSUE TITLE
[deb] Unable to install previous package version when using artifacts.elastic.co

### ISSUE THREAD

**Issue by XANi** [elastic/elasticsearch#22929]
Current repo ( ```https://artifacts.elastic.co/packages/5.x/apt stable main```) contains only latest version of package which means anyone that is on older version (either on purpose, or waiting for maintenance window to upgrade) won't be able to install new node or reinstall existing one. IMO `5.x` repo should contain all released 5.x version, just like the download page

**Comment by jasontedor** [comment]
Duplicates #21943
