### ISSUE TITLE
Javadoc: invalid code sample in XContentParser 

### ISSUE THREAD

**Issue by fabiankessler** [elastic/elasticsearch#22932]
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/xcontent/XContentParser.java

Says: 

     XContentType xContentType = XContentType.JSON;
     XContentParser parser = xContentType.xContent().createParser("{\"key\" : \"value\"}");

But this does not compile. 
This works:

    XContentType.JSON.xContent().createParser(NamedXContentRegistry.EMPTY, "myjson".getBytes());

Up until 5.1.2 this syntax worked but that's gone:

    XContentFactory.xContent(XContentType.JSON).createParser("myjson".getBytes());

This SO question is relevant http://stackoverflow.com/questions/30531768/from-json-string-to-xcontentbuilder/32886833 maybe the ES team could agree on how to do it?

**Comment by nik9000** [comment]
You shouldn't need `getBytes`.... I'll fix the javadoc and comment on the SO question.
