### ISSUE TITLE
Elasticsearch cluster status RED and not responding 

### ISSUE THREAD

**Issue by pkbelidha** [elastic/elasticsearch#22941]
and here is the status I can see 
{
  "cluster_name" : "elasticsearch-major-qa",
  "status" : "red",
  "timed_out" : false,
  "number_of_nodes" : 9,
  "number_of_data_nodes" : 5,
  "active_primary_shards" : 14718,
  "active_shards" : 29436,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 8220,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 78.17080943275973
}

**Comment by pkbelidha** [comment]
Hi friends, 

My Elastic search cluster is not responding and status is RED from last few days. It is not able to allocate the shards which are unassigned. This issue started when I first restart the primary instance and I am also not able to delete the shards which are unassigned. Can you please help

**Comment by jasontedor** [comment]
Please open a topic on the [forum](https://discuss.elastic.co); Elastic reserves GitHub for verified bug reports and feature requests and provides the forum for general help.
