### ISSUE TITLE
Layered aliases

### ISSUE THREAD

**Issue by bra-fsn** [elastic/elasticsearch#22944]
To help reindexing data in elasticsearch without a downtime it would be good to have layered aliases.
This alias could have an index in the upper layer, which means if there is data in the upper layer, it always wins over the lower layer.

If index A is the lower layer and index B is the upper:
- issuing a get to the alias would first check the doc in B -returning it if it's present- and if nothing was found, fall back to A
- doing an index request to the alias would also first check the document's presence in B, then A and act accordingly (getting the modification always into B, leaving A untouched, assuming the reindex process won't overwrite the newly modified doc)
- updating documents would behave the same: first check B, if nothing found, check A, if there is a doc, make the modifications and index it into B
- deletes should be propagated to the lower layer too, so reindex won't reintroduce already deleted documents.

With this feature it would be possible to reindex indexes without any downtime by presenting an upper layer into an alias and start to reindex old data from A to B (leaving out already modified docs in B).

**Comment by clintongormley** [comment]
Hi @bra-fsn 

Thanks for the suggestion but we've had similar proposals in the past and decided against all of them.  The model you propose is very use-case specific and is prone to race conditions and lots of hidden bugs.  We are not going to complicate aliases like this.

Instead, you should keep using your original index during reindexing and make multiple passes to ensure that all changes are copied over, then make an atomic switch from old to new index.  In the future we will add a changes api (#1242) which makes this process easier.

**Comment by bra-fsn** [comment]
Hi,

I'm sad to hear that. This way, it's impossible to really reindex without downtime, even with the changes api.
But of course I agree that this is a hard task.

Thanks for the reply.
