### ISSUE TITLE
Support Line-delimited JSON Content Type

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch#22943]
Looks like I procrastinated weighing in on #22691 for too long.

The elasticsearch-js client has been sending the `Content-Type` header forever, but users started to complain about sending invalid JSON with the JSON content type (see https://github.com/elastic/elasticsearch-js/issues/296) a couple years ago. Because of this we started using the `application/x-ldjson` content type for line delimited JSON, which Wikipedia recommended at the time. Do you think Elasticsearch could support that value for header? Apparently sending line-delimited JSON with the json header isn't going to work for some people/proxies.

**Comment by jaymode** [comment]
To be clear, `elasticsearch-js` would send `application/x-ldjson` allowed for requests like bulk, mget, msearch. For regular requests with content like search, it sends `application/json`. Is that correct?

**Comment by pickypg** [comment]
(just so you don't get heads-down, `_mget` is actually valid JSON)

**Comment by jaymode** [comment]
@spalger I opened #22947. I did want to note that the latest spec uses `application/x-ndjson` instead of `application/ld-json`, which was the proposed value in draft 1 of the spec. The comments in the code in the PR have links to this.

**Comment by clintongormley** [comment]
@elastic/es-clients - heads up about using `application/x-ndjson` for bulk and msearch APIs

**Comment by karmi** [comment]
@clintongormley I can't change headers on the fly for a specific API when the client has been already initialized. Can we also support `application/json` there?

**Comment by clintongormley** [comment]
@karmi it is still supported.  but eg @HonzaKral wanted a correct content-type header for bulk, so now he can

**Comment by karmi** [comment]
@clintongormley Great, thank you!
