### ISSUE TITLE
[Bug] Large text fields cannot be indexed

### ISSUE THREAD

**Issue by XiaonuoGantan** [elastic/elasticsearch#22985]
In ElasticSearch 5.x, the fielddata of text fields are disabled by default. And there are two solutions:

1. Use the keyword-sub-type as in {"article": {"type":"text", {"fields": {"keyword":{"type": "keyword"}}}}} and then use "title.keyword" in sort, aggregations and queries

2. Enable fielddata

Solution 1 imposes a maximum size limit of 32766 terms on the field "article" and solution 2 incurs a large memory footprint. Suppose the field "article" is big (imagine 500000+ words), what's the best way to implement this field with low memory footprint, all words can be searched, and no maximum size limit?

**Comment by jpountz** [comment]
Both options do not have the same effect either, in the first case terms aggregations would return whole strings as terms while in the second case it would return single tokens.

**Comment by XiaonuoGantan** [comment]
Yes. I misunderstood what the keyword sub type should do. No problem here
