### ISSUE TITLE
Should Deprecation HTTP headers normalize comma in messages

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#22986]
Not entirely sure what the HTTP spec status of response headers is but with request headers

```
Key: Value1, Value2
```

is equivalent to:

```
Key: Value1
Key: Value2
```

Quite a few deprecation messages contain a comma which causes an ambiguity when I get to actually parse these (from .NET BCL in this case.

e.g:

```
HTTP/1.1 200 OK
Warning: Deprecated field [fielddata_fields] used, expected [docvalue_fields] instead
Warning: [groovy] scripts are deprecated, use [painless] scripts instead
content-type: application/json; charset=UTF-8
content-length: 3676
```

Yields:

![image](https://cloud.githubusercontent.com/assets/245275/22629641/178e5de8-ebea-11e6-8420-c6c2914536cb.png)

Which is impossible to stitch back together as two messages.

**Comment by nik9000** [comment]
Bleh. Looks like we shouldn't use comma, yeah. [This](http://stackoverflow.com/questions/3096888/standard-for-adding-multiple-values-of-a-single-http-header-to-a-request-or-resp) SO question has some fun discussion about it. It looks like a lot of standard headers contain `,` and can't be merged, but well behaved headers don't contain `,`. It links to [this](https://github.com/bnoordhuis/mozilla-central/blob/master/netwerk/protocol/http/nsHttpHeaderArray.h#L185) (MPLed) code that shows how a browser does it....

**Comment by jasontedor** [comment]
It is indeed the case that the warning header can be multi-valued which means that we do need to address the comma-separated issue here. On closer inspection of the HTTP spec, we are not following the warning header specification. We should be prepending each warning with a code (we can just use 199 miscellaneous) and an agent (we can just use the Elasticsearch version), and then we should be quoting each warning string to address the comma issue.
