### ISSUE TITLE
Cancellation of Search with the Task Management API

### ISSUE THREAD

**Issue by jfwm2** [elastic/elasticsearch#22990]
**Describe the feature**: Currently Search does not currently support cancellation. Apparently the only tasks supporting cancellation at the moment are Reindex and Delete-By-Query. We would need to have cancellable search and we may contribute to integrate the task management API to the Search tasks in order to cancel searchs.

**Comment by jimczi** [comment]
@jfwm2 this feature is now available in 5.x (starting in 5.1):
https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search.html#global-search-cancellation

**Comment by jfwm2** [comment]
Thanks @jimczi !
