### ISSUE TITLE
Get document can return incorrect fields with _source_include option.

### ISSUE THREAD

**Issue by mitchknife** [elastic/elasticsearch#23002]
**Elasticsearch version**: 5.2.0 (latest docker image)

**Plugins installed**: []

**JVM version**: 8u111

**OS version**: Docker 1.12.5 (running on Mac OS 10.11.5)

**Description of the problem including expected versus actual behavior**:
The `_source_include` query string option can sometimes return fields not asked for. In the following case `_source_include=my_field_2` returns both `my_field` and `my_field_2` in the`_source` response, where I would expect only `my_field_2`. As far as I can tell, `my_field` must be an array for this behavior.

**Steps to reproduce**:
 ```
PUT my_index

POST my_index/foo/1
{
  "my_field": ["abcd"],
  "my_field_2": "1234"
}

GET my_index/foo/1?_source_include=my_field_2
```
**Expected response**
```
{
  "_index": "my_index",
  "_type": "foo",
  "_id": "1",
  "_version": 1,
  "found": true,
  "_source": {
    "my_field_2": "1234"
  }
}
```
**Actual response**
```
{
  "_index": "my_index",
  "_type": "foo",
  "_id": "1",
  "_version": 1,
  "found": true,
  "_source": {
    "my_field": [
      "abcd"
    ],
    "my_field_2": "1234"
  }
}
```

**Comment by clintongormley** [comment]
Fixed by https://github.com/elastic/elasticsearch/pull/22593 (which was incorrectly labelled as v5.2.0)
