### ISSUE TITLE
Windows service script doesn't respect %CONF_DIR% when setting the jvm.options path

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch#23004]
We allow for specifying a config directory that resides outside of `%ES_HOME%` by specifying [%CONF_DIR%](https://github.com/elastic/elasticsearch/blob/master/distribution/src/main/resources/bin/elasticsearch-service.bat#L227).

However setting the [jvm.options path is hard-coded](https://github.com/elastic/elasticsearch/blob/master/distribution/src/main/resources/bin/elasticsearch-service.bat#L146)  to `%ES_HOME%/config` and doesn't use `%CONF_DIR%` which results in either an error or causes the wrong jvm.options file to be used when it's set.

**Comment by clintongormley** [comment]
@gmarz the location of the `jvm.options` file should be configurable with the `ES_JVM_OPTIONS` environment variable: https://www.elastic.co/guide/en/elasticsearch/reference/5.2/breaking_50_packaging.html#_jvm_options

**Comment by gmarz** [comment]
@clintongormley but it defaults to `ES_HOME\config\jvm.options` which is problematic if `CONF_DIR` is set but not `ES_JVM_OPTIONS`.

I think it should default to `CONF_DIR\jvm.options` instead, and `CONF_DIR` default to `ES_HOME\config`, which it already does.

**Comment by gmarz** [comment]
Had a related conversation with @jasontedor on slack and we discussed removing the ability to specify a config path altogether.

**Comment by wonkyto** [comment]
We run multiple elasticsearch datanodes on the same system - as we change the CONF_DIR to point to the correct location for the configuration of each elasticsearch instance, it becomes an issue to have a single jvm.options file. Previously this was set via the ES_HEAP_SIZE variable in /etc/sysconfig/elasticsearch-data-node-0X however this variable is no longer supported. 

Our current situation is that all instances running use the same jvm options, so it's not a deal-breaker, however now I'm coming to puppetise the deployment, it will be a problem based on our previous puppet design using version 2.X.

**Comment by roweryan** [comment]
@gmarz Please don't remove the ability to specify a config path.

**Comment by jasontedor** [comment]
> Please don't remove the ability to specify a config path.

@roweryan Would you mind explaining your use case so we have a better understanding why you're requesting this?

**Comment by roweryan** [comment]
@jasontedor Sure. I need to keep my log files and config separate from my binaries. If the config lives inside the binary directory this makes my life more difficult :)

**Comment by jasontedor** [comment]
> I need to keep my log files and config separate from my binaries.

This only pushed the question back one layer. 😄

Why do you need this?

**Comment by roweryan** [comment]
The unpacked tar.gz file needs to match what is in the tar.gz file I can get from your download page. If there are changed files or extra files in there then our check fails.
