### ISSUE TITLE
NoNodeAvailableException (None of the configured nodes are available) error when trying to push data to Elastic from a Spark job

### ISSUE THREAD

**Issue by hexastax** [elastic/elasticsearch#23010]
**Elasticsearch version**:
2.3.1

**Plugins installed**: [Kibana 4.5.4]

**JVM version**:
Java (TM) SE Runtime Environment (build 1.8.0_112-b15)

**OS version**:
Red Hat Enterprise Linux Server release 6.7 (Santiago)

**Description of the problem including expected versus actual behavior**:
Attempting to connect to Elastic programmatically within a Spark job, by getting a TransportClient, then performing a health check before ingesting any documents:

`ClusterHealthResponse chr = client.admin().cluster().prepareHealth().setWaitForGreenStatus().setTimeout(TimeValue.timeValueSeconds(10)).get();`

This code works perfectly fine when the call is issued inside a standalone Java application. However, when this code runs inside a Spark job, we get the error NoNodesAvailable.

Full stack trace is available in the discussion forum [here](https://discuss.elastic.co/t/nonodeavailableexception-none-of-the-configured-nodes-are-available-error-when-trying-to-push-data-to-elastic-from-a-spark-job/73904). 

**Steps to reproduce**:
 1. Implement a Spark job with a driver that connects to Elastic and checks the health and publishes documents, as mentioned above.

**Provide logs (if relevant)**:
[2017-02-06 22:53:19,688][TRACE][transport.tracer         ] [test-node-1] [208][indices:data/read/search[phase/query+fetch]] received response from [{test-node-1}{GGiOFd08SRqte42P93v0vQ}{XX.XXX.XXX.XX}{XX.XXX.XXX.XX:9300}]

(Around this time we got on Spark side:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{XX.XXX.XXX.XX}{XX.XXX.XXX.XX:9300}]])

[2017-02-06 22:53:19,775][TRACE][transport.netty          ] [test-node-1] channel opened: [id: 0x9aa97215, /XX.XXX.XXX.XX:39476 => /XX.XXX.XXX.XX:9300]
[2017-02-06 22:53:19,904][TRACE][transport.netty          ] [test-node-1] channel closed: [id: 0x9aa97215, /XX.XXX.XXX.XX:39476 => /XX.XXX.XXX.XX:9300]
 
[2017-02-06 22:53:22,202][TRACE][transport.tracer         ] [test-node-1] [209][cluster:monitor/nodes/info[n]] received response from [{di-test-node-1}{GGiOFd08SRqte42P93v0vQ}{XX.XXX.XXX.XX}{XX.XXX.XXX.XX:9300}]

Not much in the log. We set   **transport: TRACE**  in logging.yml but didn't seem to get much tracing from such classes as TransportClientNodesService.  We were hoping to trace how the nodes get validated and added. Not seeing that info in the logs.

**Things we have tried**:

1. Checked the cluster status, all good, green. Side note: this is a single node cluster.
2. Tried making the TransportClient be a singleton. No help.
3. Tried setting and increasing **client.transport.ping_timeout** and **client.transport.nodes_sampler_interval** to 60seconds. No help.
4. The timeout on the cluster health check increased to 60 seconds. No help.
5. Tried setting the network.host as the host's IP address  or  [\_eth0\_, \_local\_].  No help.

Any info or recommendations would be appreciated as we haven't yet seen any feedback to the forum post. Thanks.

**Comment by clintongormley** [comment]
Hi @hexastax 

We reserve the issues list for bug reports and feature requests.  The forum is the right place to ask this question, so I'm going to close the issue.  I will however ping @jbaiera and ask him to look at the forum post: https://discuss.elastic.co/t/nonodeavailableexception-none-of-the-configured-nodes-are-available-error-when-trying-to-push-data-to-elastic-from-a-spark-job/73904

**Comment by hexastax** [comment]
Thanks, Clinton!

- Dmitry
