### ISSUE TITLE
Function score filter performs greatly worse than bool query filter

### ISSUE THREAD

**Issue by gm42** [elastic/elasticsearch#23013]
**Elasticsearch version**: 2.4.4

**Plugins installed**: []

**JVM version**: OpenJDK 1.7.0_121

**OS version**: Linux 4.4.41 x86_64

**Description of the problem including expected versus actual behavior**:
Using a function score filter leads to degraded performance and likely not optimized filtering within ES/Lucene.

Moving the filter to a composite bool query shows desired behavior.

# Using function score filter
```
    "query": {
        "bool": {
            "filter": {
                "bool": {
                    "filter": [
                        {
                            "has_parent": {
                                "parent_type": "myparent",
                                "query": {
                                    "bool": {
                                        "filter": {
                                            "terms": {
                                                "first_id": [
                                                    9
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        {
                            "terms": {
                                "second_id": [
                                    9
                                ]
                            }
                        },
                        {
                            "range": {
                                "days": {
                                    "from": 30,
                                    "to": 60
                                }
                            }
                        }
                    ]
                }
            },
            "must": {
                "function_score": {
                    "boost_mode": "replace",
                    "min_score": 10,
                    "score_mode": "first",
                    "script_score": {
                        "script": {
                            "inline": "100",
                            "lang": "expression"
                        }
                    }
                }
            }
        }
    },
    "size": 0
}
```

# Using bool query filter

![loadtest5x](https://cloud.githubusercontent.com/assets/16498973/22689035/51e7b00c-ed2f-11e6-833b-d294cc5a8e63.png)

```
 "query": {
        "function_score": {
            "boost_mode": "replace",
            "functions": [
                {
					"filter": {
						"bool": {
							"filter": [
								{
									"has_parent": {
										"parent_type": "myparent",
										"query": {
											"bool": {
												"filter": {
													"terms": {
														"first_id": [
															9
														]
													}
												}
											}
										}
									}
								},
								{
									"terms": {
										"second_id": [
											9
										]
									}
								},
								{
									"range": {
										"days": {
											"from": 30,
											"to": 60
										}
									}
								}
							]
						},
                    "script_score": {
                        "script": {
                            "inline": "100",
                            "lang": "expression"
                        }
                    }
                }
            ],
            "min_score": 10,
            "score_mode": "first"
        }
    },
    "size": 0
}
```

![loadtest5x_v10](https://cloud.githubusercontent.com/assets/16498973/22689039/5b98bbbe-ed2f-11e6-98ae-edefbc771ecf.png)

# Conclusion

I would kindly ask to explain if this is expected behavior or not (and eventually some details about why), and then either consider this a bug report or a documentation update suggestion (I can contribute the PR for that, if I get some better understanding of the problem).

**Comment by clintongormley** [comment]
First, your second query is malformed - I'm getting a JSON error and it is just too messy to try to clean up myself - I don't understand exactly what you're trying to do there.  Please try to paste valid code when opening an issue.

Second, your two queries do different things.  Filters inside function queries are used to apply a function to matching docs only, but they don't filter the docs returned (which the bool filter does).

**Comment by gm42** [comment]
@clintongormley my point was more that they are called in the same way, `filter`, yet they are acting differently.

**Comment by clintongormley** [comment]
Sure, but that's what the docs are for ;)

**Comment by gm42** [comment]
@clintongormley but wouldn't be worth adding a note, which could as well be your quote:

> Filters inside function queries are used to apply a function to matching docs only, but they don't filter the docs returned (which the bool filter does).
> 

I cannot estimate how much of a "noob" doubt this would be, but by reading https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-bool-query.html and https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-function-score-query.html I could not infer what you just said.

**Comment by clintongormley** [comment]
It may well be that the docs could be improved - I can see that the way they're written today assumes some knowledge, eg:

> The function_score allows you to modify the score of documents that are retrieved by a query. This can be useful if, for example, a score function is computationally expensive and it is sufficient to compute the score on a filtered set of documents.

This explains the purpose: you get back the results returned by a query, but you can alter the score of a subset of those docs by using a filter to match the subset.  But it doesn't make clear that the assumption you had was incorrect.

Fancy sending a PR to make this clearer?

**Comment by gm42** [comment]
Sure, will provide. I ended up using `function_score` + `min_score` because of a missing feature (function score in post-filter IIRC), so it took some effort to figure out what was causing the performance issue.

**Comment by gm42** [comment]
I did not have time to arrange the PR, but I would like to propose changes in two paragraphs instead one.

Let me re-formulate the question from OP: what is the (internal) technical reason for MinScore/ConstantScoreFilter to have such performance correlation with amount of concurrent queries? Feel free to cite Lucene internals if needed.

If I know the answer to this, I might be able to provide a better documentation improvement (without the low-level details); I can infer it's due to "returning all the docs" part, but still quite surprising.

**Comment by clintongormley** [comment]
Filters in the function_score query are used to apply a function to a limited subset of all the results of the query.  (eg if the hotel room has a balcony, then increase the score by 1). So these filters don't affect what hits are returned - that is determined by the query.  

For min_score to work, ALL documents returned by the query need to be scored, and then filtered out one by one.  This is much less efficient than including a filter in the query which says: only return hotel rooms which have a balcony.

**Comment by gm42** [comment]
Ah! That makes sense, thank you so much @clintongormley!

As I understand it's like document scores are being "buffered" at some step and only afterwards filtered (this at least would explain the observation).

**Comment by vino-jay** [comment]
It's bad to use the ScriptPlugin.About 1 million datas but cost 10 seconds。
How to improve the performance？
GET test_index/_search
{
  "from": 0,
  "size": 20,
  "query": {
    "function_score": {
      "query": {
        "bool": {
          "filter" : [
          {
            "range" : {
              "les_start_time" : {
                "from" : "2019-06-13 21:00:00",
                "to" : "2019-07-26 10:00:00",
                "include_lower" : true,
                "include_upper" : false,
                "boost" : 1.0
              }
            }
          }
        ]
        }
      },
      "functions": [
        {
          "script_score": {
            "script": {
              "source": "qi_sv_abnormal_score",
              "lang": "abnormal_scoring_script",
              "params": {"esScoreFields":"teacher_voice_pct,student_voice_pct"}
            }
          }
        }
      ],
      "score_mode": "multiply",
      "boost_mode": "replace"
    }
  }
}
