### ISSUE TITLE
Support Elasticsearch date-mapping pattern names in DateProcessor

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#23032]
as mentioned here: #22982, it would be nice to use ES's built-in formats listed out here: https://www.elastic.co/guide/en/elasticsearch/reference/5.x/mapping-date-format.html#built-in-date-formats.

Like

```
"date": {
  "field": ...,
  "target_field": ...,
  "formats": [ "basic_date_time_no_millis" ]
}
```

**Comment by spinscale** [comment]
This is related to #27330 - I will look up, if the date formats can be easily converted to java time. If that's the case, it makes sense to add this to the data processor, otherwise we would add something that might be deprecated soon.

**Comment by talevy** [comment]
@spinscale cool. another thing to note about why this wasn't tackled yet is that we want to keep Ingest independent of ES as much as possible (via https://github.com/elastic/elasticsearch/issues/29233)

**Comment by rjernst** [comment]
@talevy We discussed this in FixItThursday, and think we should just fix this (in conjunction with the java 8 time api work), as the separation of ingest from ES has a lot of other blockers, and should not prohibit fixing this issue.

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
