### ISSUE TITLE
Forcing development mode

### ISSUE THREAD

**Issue by hanny24** [elastic/elasticsearch#23052]
We use ElasticSearch in docker for running our tests. It would be really beneficial for us to somehow force development mode (as we need to connect to transport port). This requires that all developer's machines are properly set, especially the `vm.max_map_count=262144`.

**Comment by jasontedor** [comment]
Sorry, this is not going to happen. There's a lot of previous thinking on this. A starting point is our [blog post](https://www.elastic.co/blog/bootstrap_checks_annoying_instead_of_devastating) on this subject.

**Comment by hanny24** [comment]
Yes I've read it. I even agree that current behaviour is reasonable default. Yet I feel that there should be a very **explicit** configuration option that turns ES into development mode.

**Comment by s1monw** [comment]
> Yes I've read it. I even agree that current behaviour is reasonable default. Yet I feel that there should be a very explicit configuration option that turns ES into development mode.

I know it's a controversial issue. From our perspective it's too dangerous to allow this kind of flag. You are binding to non-local host you are doing serious stuff. Even if you are running in a environment it must be setup correctly. We agreed as a team to not add such a flag. Also, there is no possible solution to make everybody happy. This has been agreed as a reasonable compromise that gives us the best of both worlds. Thanks for the empathy, I appreciate it.
