### ISSUE TITLE
Support `key_as_string` inside aggregation path

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#23056]
Multi-bucket aggregations that support formatting, like `DateHistogram` provide their content in a formatted manner (typically through `key_as_string`). While inside aggregation path one can refer to the key, currently there's no support for getting the formatted key despite being available.

**Comment by jpountz** [comment]
For the record, I'd like to remove `key_as_string` and fix `key` to always return formatted keys. (#18518)

**Comment by costin** [comment]
Sounds good to me.

**Comment by clintongormley** [comment]
Closing in favour of #18518
