### ISSUE TITLE
http 200 response code for partial result

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch#23059]
**Elasticsearch version**: 2.4.0
A _search partial response comes back with http code `200: OK`.  I would have expected this to be a `206: Partial Content`. 

I did not find this behavior documented, and only a short paragraph that states we can return a partial response: https://www.elastic.co/guide/en/elasticsearch/reference/5.1/docs-replication.html#_failure_handling_2

```
{
  "took": 9918,
  "timed_out": false,
  "_shards": {
    "total": 64,
    "successful": 27,
    "failed": 37,
    "failures": [
      {
        "shard": 1,
        "index": "data-20170101",
        "node": "dqqZ8_s7Q7CKzABoyJjLAg",
        "reason": {
          "type": "es_rejected_execution_exception",
          "reason": "rejected execution of org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler@47e9a0ad on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@5f83d265[Running, pool size = 48, active threads = 48, queued tasks = 1000, completed tasks = 10576391]]"
        }
      },
      ...
    ]
  },
  "hits": {
    ...
  }
}
```

**Comment by jpcarey** [comment]
should also apply to `timed_out: true` requests, where the hits/aggs will be based upon the data collected up to the timeout threshold.

**Comment by nik9000** [comment]
Bulk, msearch, and mget also work this way.

**Comment by gauravmishra123** [comment]
Hi Can I take  this issue??

**Comment by ashishguptak** [comment]
hello, let me know if anyone is working on this. 
I would be willing to take it up.

**Comment by gauravmishra123** [comment]
Hi ashish
Thanks for your concern but I am already working on this issue.

**Comment by bleskes** [comment]
@gauravmishra123 thanks for working on this. Note though that we can't use 206 Partial Response as the spec says we then we must include:

> Either a Content-Range header field (section 14.16) indicating the range included with this response, or a multipart/byteranges Content-Type including Content-Range fields for each part.

Neither of these make sense in the context of ES. I therefore think that the current behavior should be documented and that's it. Pinging @elastic/es-docs for advice on where to put this as I can't find a natural place.

**Comment by gauravmishra123** [comment]
Thanks bleskes for your help.Please let me know if anything else needs to be done.

**Comment by jrodewig** [comment]
@gauravmishra123 Let me know if you're still working on this.

If not, I can take it up. Thank you!
