### ISSUE TITLE
5.2 is not backward compatible for update (Script object creation)

### ISSUE THREAD

**Issue by kamesh84** [elastic/elasticsearch#23066]
**Elasticsearch version**: 5.0.1 o 5.2 migration

**Plugins installed**: [NA]

**JVM version**: Java 8

**OS version**: windows

**Description of the problem including expected versus actual behavior**:
Script constructor method signature changed 
**Steps to reproduce**:
 5.0.1 had method signature is  Script( String lang, ScriptType type,String idOrCode, Map<String, Object> params) 
 5.2 version is changed to Script(ScriptType type, String lang, String idOrCode, Map<String, Object> params) {

**Describe the feature**:
Method signature change is affected backward compatibility.

**Comment by s1monw** [comment]
@kamesh84 thanks for opening this. BWC on a java API level is difficult topic and if the changes are minor like this one or required we prefer a compile error over a compiler warning. Not everybody agrees with this but I personally like it much better if your compiler fails than a ignored deprecation warning. This is different for things like the JDK where you really don't know which one you are running on but with ES upgrades are explicit and fixes are straight forward.
