### ISSUE TITLE
Elasticsearch when  a index have many types how to delete one of types?

### ISSUE THREAD

**Issue by zqc0512** [elastic/elasticsearch#23065]
Elasticsearch when  a index have many types how to delete one of types?
thanks.

**Comment by zqc0512** [comment]
thanks.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by zqc0512** [comment]
in my network i can't open discuss.elastic.co  plase open it again  @dadoonet @deontologician 
thanks.

**Comment by dadoonet** [comment]
Tell your admin that this forum is important for you.

You can't really delete a type. The mapping will still be there.
You may want to reindex instead.

**Comment by dadoonet** [comment]
Apparently you found a way: https://discuss.elastic.co/t/elasticsearch-5-2-when-a-index-have-many-types-how-to-delete-one-of-types/74468/2
