### ISSUE TITLE
`copy_to` cannot be used on `object` mappings

### ISSUE THREAD

**Issue by InfinitiesLoop** [elastic/elasticsearch#23064]
Elasticsearch version: 2.4

I am not sure if this is a feature request or a bug, but the docs are definitely not clear on the expected behavior. I assumed this would work from what I read.

I am trying to use `copy_to` in a mapping to move fields from one part of the document to another, with respect to searching in ES. I do not want to actually modify the source document, I just want users to be able to find the documents using a different field path.

The reason for this is that I have varying types of a documents that are mostly independent from one another, but have a few fields in common. I am dynamically generating mappings for these documents from a protocol buffer schema. The type of the message is the first part of the object, with its fields define within. Each of these messages can have a hierarchy of fields of their own.

As an oversimplified example, two messages might look like:

```json
{
  "type_a": {
    "foo": { "bar": 1 },
    "fieldA": "abc"
  }
}

{
  "type_b": {
    "foo": { "bar": 2 },
    "fieldB": "abc"
  }
}
```

Both types have a "foo.bar" field, but they differ otherwise. In reality, `foo` contains numerous fields and even more nesting.

The problem is with this hierarchy, each `foo.bar` field is different: `type_a.foo.bar` and `type_b.foo.bar`. This makes searching for them and aggregating on them _together_ really difficult, or impossible (in kibana, anyway).

I cannot simply drop the outer 'type' portion of the hierarchy, because it's entirely possible that `type_a` and `type_b` have field names in common but of different types -- they live in the same index, so they have to have different mappings defined, which means they have to have a different field path.

So instead, I'm trying to use `copy_to` to effectively give the fields I need a new location with regard to search and aggregations. 

It actually works beautifully on simple field types. But it fails on `object` mappings. I could workaround this by defining a `copy_to` mapping on every single field within the object instead, but as I said, there can be a lot of them and have their own levels of nesting, and they'd all just be there so they could have a copy_to and index:no parameter. That is going to complicate how I generate these mappings quite a bit. 

Here's an example mapping that reproduces it:

```
curl -v -XPUT http://localhost:9200/copy_test -d '
{
  "mappings": {
    "mytype": {
      "properties": {
        "foo": {
          "properties": {
            "bar": {
              "type": "string"
            }
          }
        },
        "move_field": {
          "type": "object",
          "copy_to": "foo",
          "index": "no"
        }
      }
    }
  }
}'
```
This results in an error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Mapping definition for [move_field] has unsupported parameters:  [copy_to : foo] [index : no]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [mytype]: Mapping definition for [move_field] has unsupported parameters:  [copy_to : foo] [index : no]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "Mapping definition for [move_field] has unsupported parameters:  [copy_to : foo] [index : no]"
    }
  },
  "status": 400
}
```

I have tried a few variations, such as specifying `properties` instead of `type: object` and what-not. But nothing works.

**Comment by clintongormley** [comment]
I'm afraid that specifying `copy_to` and `index: no` on each concrete field is indeed the solution.  `copy_to` needs to be specified on a concrete field.

**Comment by InfinitiesLoop** [comment]
Ok then, it is what it is. Is this not even a consideration for enhancement? :)

**Comment by clintongormley** [comment]
Sorry but no - the mapping code is fiendishly complex and implementing this would add a significant amount of complexity, plus if we add that, then somebody will want the ability to change the copy_to of a sub-object, etc.  Slippery slope.  We prefer to keep these things explicit.
