### ISSUE TITLE
TransportClientNodesService swallows exceptions, reports them at DEBUG log level, and maps all to NoNodesAvailableException

### ISSUE THREAD

**Issue by hexastax** [elastic/elasticsearch#23076]
**Elasticsearch version**:
2.3.1

**Plugins installed**: [Kibana]

**JVM version**:
1.8.0_112-b15

**OS version**:
Red Hat 6.7

**Description of the problem including expected versus actual behavior**:
Described in detail in my form post: https://discuss.elastic.co/t/nonodeavailableexception-none-of-the-configured-nodes-are-available-error-when-trying-to-push-data-to-elastic-from-a-spark-job/73904

TransportClientNodesService swallows exceptions, reports them at DEBUG log level, and maps all to a generic NoNodesAvailableException, which makes it very hard to uncover the actual underlying problem.

Actual code in the service:

    protected List<DiscoveryNode> validateNewNodes(Set<DiscoveryNode> nodes) {
        for (Iterator<DiscoveryNode> it = nodes.iterator(); it.hasNext(); ) {
            DiscoveryNode node = it.next();
            if (!transportService.nodeConnected(node)) {
                try {
                    logger.trace("connecting to node [{}]", node);
                    transportService.connectToNode(node);
                } catch (Throwable e) {
                    it.remove();
                    logger.debug("failed to connect to discovered node [" + node + "]", e);
                }
            }
        }

        return Collections.unmodifiableList(new ArrayList<>(nodes));
    }

The desired behavior would be to:
a. Log the original exception at the ERROR level into the log.
b. Wrap the original exception into the NoNodeAvailableException or, better, rethrow the original exception, or something that does not lose the cause exception.

**Steps to reproduce**:
 1. Build a Spark uber-jar with Maven Shade plugin, without using the org.apache.maven.plugins.shade.resource.ServicesResourceTransformer transformer.
 2. Deploy the Spark job and kick it off.
 3. Observe that the code trying to connect to Elastic from the Spark job gets a generic NoNodeAvailableException, with no apparent way to tell what's wrong (the cluster is all GREEN).

**Comment by javanna** [comment]
The problem here is that you may have some nodes failing but not all of them, in which case no exception needs to be thrown. I tend to agree with you that maybe logging at error level is more appropriate and I will mark the corresponding PR for discussion.

**Comment by martijnvg** [comment]
Closing this issue since the rest client has a better way to allow applications to deal with error logging via a failure listener.
