### ISSUE TITLE
Textual intervals in histogram aggregations producing number_format_exception

### ISSUE THREAD

**Issue by jacobam88** [elastic/elasticsearch#23073]
**Elasticsearch version**: 2.4.4

Textual intervals in histogram aggregations producing number_format_exception.
![image](https://cloud.githubusercontent.com/assets/25662402/22782683/f7eaaac0-eed0-11e6-8474-f42770026605.png)

Mapping of "last_time" is

`"last_time": {
                        "type": "date",
                        "ignore_malformed": true,
                        "format": "date_optional_time"
                    }`

Range queries working fine:

![image](https://cloud.githubusercontent.com/assets/25662402/22782887/dbdf83e0-eed1-11e6-9569-b3b5ada5ce50.png) 

Didn't find anything in docs stating that allowed interval values depends on date formats. Something i'm missing?

**Comment by jimczi** [comment]
Use `date_histogram` instead of `histogram` and it works fine. The latter requires valid number. 
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#search-aggregations-bucket-datehistogram-aggregation
