### ISSUE TITLE
Update lucene dependency version to 6.4.1

### ISSUE THREAD

**Issue by PnPie** [elastic/elasticsearch#23075]
**Elasticsearch version**: master

**Plugins installed**: []

**JVM version**: Oracle Corporation 1.8.0_121 [OpenJDK 64-Bit Server VM 25.121-b13]

**OS version**: Ubuntu Linux 4.4.0-62-generic (amd64)

**Description of the problem including expected versus actual behavior**:
In `core/src/main/java/org.elasticsearch/Version.java`:
```
    public static final Version V_5_2_1_UNRELEASED = new Version(V_5_2_1_ID_UNRELEASED, org.apache.lucene.util.Version.LUCENE_6_4_1);
    public static final int V_5_3_0_ID_UNRELEASED = 5030099;
    public static final Version V_5_3_0_UNRELEASED = new Version(V_5_3_0_ID_UNRELEASED, org.apache.lucene.util.Version.LUCENE_6_4_1);
    public static final int V_6_0_0_alpha1_ID_UNRELEASED = 6000001;
    public static final Version V_6_0_0_alpha1_UNRELEASED =
        new Version(V_6_0_0_alpha1_ID_UNRELEASED, org.apache.lucene.util.Version.LUCENE_6_4_1);
    public static final Version CURRENT = V_6_0_0_alpha1_UNRELEASED;
```
**org.apache.lucene.util.Version.LUCENE_6_4_1** was cited, but the current `org.apache.lucene` version is 6.4.0 according to dependencies.

There are also the same version issues in `core/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java` for `TermContext#wasBuiltFor()` function which is not existed in lucene 6.4.0.

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jasontedor** [comment]
No, that's not correct. Here's [version.properties](https://github.com/elastic/elasticsearch/blob/b85fa54ee74f88b9dc1ce20ce82702ff97c14d2d/buildSrc/version.properties#L3) right now:

```
lucene            = 6.4.1
```

Here's [Version.java](https://github.com/elastic/elasticsearch/blob/b85fa54ee74f88b9dc1ce20ce82702ff97c14d2d/core/src/main/java/org/elasticsearch/Version.java#L116-L117) on the same commit:

```
    public static final Version V_6_0_0_alpha1_UNRELEASED =
        new Version(V_6_0_0_alpha1_ID_UNRELEASED, org.apache.lucene.util.Version.LUCENE_6_4_1);
```

**Comment by jasontedor** [comment]
> There are also the same version issues in `core/src/main/java/org/apache/lucene/queries/BlendedTermQuery.java` for `TermContext#wasBuiltFor()` function which is not existed in lucene 6.4.0.

If you're seeing issues like this, I think that your workspace just has not refreshed the latest dependencies from the version.properties change. You might want to force a refresh.
