### ISSUE TITLE
copy_to doesn't store data as nested object although target field is defined as nested object

### ISSUE THREAD

**Issue by demoaccount2015** [elastic/elasticsearch#23077]
copy_to is not storing data as nested object although jobActivity is defined as nested type. If we directly aggregate on jobActivity.jobTitle field. it returns the data but nested aggregation query doesn't return any result.

I am using below query to query nested object

```
POST /{index_name}/{type}/_search
{
  "size": 0,
  "query": {
    "match_all": {
      
    }
  },
  "aggregations": {
    "jobActivity": {
      "nested": {
        "path": "jobActivity"
      },
      "aggregations": {
        "jobTitle": {
          "terms": {
            "field": "jobActivity.jobTitle.jobTitle_sort",
            "size": 0,
            "order": {
              "_term": "asc"
            }
          }
        }
      }
    }
  }
}
```
Please find below index mapper for the field:

```


{
  "appliedJob": {
    "type": "nested",
    "include_in_parent": true,
    "properties": {
      "jobTitle": {
        "type": "string",
        "fields": {
          "jobTitle_sort": {
            "type": "string",
            "index": "not_analyzed"
          }
        },
        "copy_to": [
          "jobActivity.jobTitle"
        ]
      }
    }
  },
  "jobActivity": {
    "type": "nested",
    "properties": {
      "jobTitle": {
        "type": "string",
        "fields": {
          "jobTitle_sort": {
            "type": "string",
            "index": "not_analyzed"
          }
        }
      }
    }
  }
}


```

**Comment by jpountz** [comment]
What version are you using?

**Comment by clintongormley** [comment]
This is correct.  Nested docs are for arrays of associated objects, so you can't copy from one nested doc (or a top level field) into another nested doc.  What if the destination field had an array of 3 nested docs? Which one would you add the field to?

**Comment by demoaccount2015** [comment]
@jpountz I am using elasticsearch version 2.3.5

**Comment by demoaccount2015** [comment]
@clintongormley Why is it not allowed to copy an object field to nested object?

**Comment by clintongormley** [comment]
Because there can be multiple nested objects - each one is indexed as a separate document.  Which one do you copy the object field to?

If you want to copy it to all of them, then use an ingest processor instead.
