### ISSUE TITLE
Remove undocumented action.bulk.action.allow_id_generation/action.allow_id_generation setting?

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#23088]
We currently have a setting in our indexing for whether auto id generation is allowed, however, this setting is not documented and I'm not sure whether it's something we want to support.

If we don't, it should be removed and the code cleaned up.
If we do, then we should document it so it's an official setting.

I've never heard of anyone using it in my experience before, so I'm +1 to remove the settings.

**Comment by clintongormley** [comment]
These settings are not exposed - you get an exception if you try to set them, so I think they can be safely removed

**Comment by nik9000** [comment]
> you get an exception if you try to set them

This sounds like strict parsing was, a half implemented setting. I vote remove.
