### ISSUE TITLE
'convert' Processor does not support all numeric datatypes that elasticsearch is designed to allow.

### ISSUE THREAD

**Issue by DawtCom** [elastic/elasticsearch#23085]
**Elasticsearch version**:  
    "number": "5.1.1",
    "build_hash": "5395e21",
    "build_date": "2016-12-06T12:36:15.409Z",
    "build_snapshot": false,
    "lucene_version": "6.3.0"

**Plugins installed**: []

**JVM version**:
java version "1.8.0_101"

**OS version**:
Windows 10

**Description of the problem including expected versus actual behavior**:
During some application testing using ingest pipeline processors, we noticed when trying to convert a string that represented a dollar amount to a double, it was not allowed.  We noticed then that convert restricts to only : integer, float, string, boolean, and auto.   I would hope that we might be able to update this to support the other datatypes that are acceptable.

IE. long, double, short, byte at a minimum.   

**Steps to reproduce**:
 1. Create a simulate pipeline:
```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "description": "This would be used to map numeric strings to there equivalent int",
    "processors": [
      {
        "convert": {
          "field": "num_emp",
          "type": "integer"
        }
      },
      {
        "convert": {
          "field": "salary_midpoint",
          "type": "double"
        }
      }
    ]
  },
  "docs": [
    {
      "_index": "test",
      "_source": {
        "num_emp": "2",
        "salary_midpoint": "195000.0"
      }
    }
  ]
}
```

**Provide logs (if relevant)**:
```
{
  "error": {
    "root_cause": [
      {
        "type": "parse_exception",
        "reason": "[type] type [double] not supported, cannot convert field.",
        "header": {
          "processor_type": "convert",
          "property_name": "type"
        }
      }
    ],
    "type": "parse_exception",
    "reason": "[type] type [double] not supported, cannot convert field.",
    "header": {
      "processor_type": "convert",
      "property_name": "type"
    }
  },
  "status": 400
}
```

**Comment by clintongormley** [comment]
@talevy should not just make int and float convert to long and double by default?

**Comment by talevy** [comment]
@clintongormley yeah, that isn't a bad idea. Especially since that is more ES-default oriented. The way it is now does seem silly, but aligns with Logstash more.

**Comment by DawtCom** [comment]
Could logstash also be aligned?

On Feb 9, 2017 1:22 PM, "Tal Levy" <notifications@github.com> wrote:

@clintongormley <https://github.com/clintongormley> yeah, that isn't a bad
idea. Especially since that is more ES-default oriented. The way it is now
does seem silly, but aligns with Logstash more.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/elastic/elasticsearch/issues/23085#issuecomment-278744454>,
or mute the thread
