### ISSUE TITLE
How to use the slicing

### ISSUE THREAD

**Issue by liuyaopeng** [elastic/elasticsearch#23096]
I used slicing in the project,but i found this api has a bug。
If the number of slices is greater than the number of shares。
Each piece of data hits add up the wrong number.

**Comment by bleskes** [comment]
Thx @liuyaopeng but I find it hard to understand what went wrong. Can you maybe give concrete examples of API calls and responses?

**Comment by clintongormley** [comment]
Hi @liuyaopeng 

I've just tested this with 5 shards and 7 slices and it worked perfectly.  If you're still having problems, I'd start with opening an issue in the forums https://discuss.elastic.co with a complete recreation.  If you do find a bug, then please open an issue with the recreation.

thanks

**Comment by liuyaopeng** [comment]
i try again ，it sometimes will wrong

**Comment by liuyaopeng** [comment]
hi @clintongormley 
thank you for your reply.I did some experiments. 
Here is my code:

`public static void main(String[] args) throws UnknownHostException {
        int totalResults = 0;

        int s = 7;
        List<String> keys = new ArrayList<>();
        for (int i = 0; i < s; i++) {

            int j = 0;

            SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
//            searchSourceBuilder.query(QueryBuilders.termQuery("patient_info.GENDER", "男"));
            searchSourceBuilder.size(Integer.MAX_VALUE);
            searchSourceBuilder.query(QueryBuilders.matchAllQuery());
            searchSourceBuilder.slice(new SliceBuilder(i, s));
            Settings settings = Settings.builder().put("client.transport.sniff", true).put("cluster.name", "elasticsearch-gennlife-ark-2.0").build();
            TransportClient client = null;
            client = (new PreBuiltTransportClient(settings, new Class[0])).addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("10.0.0.66"), 9301));

            SearchRequestBuilder builder = client.prepareSearch(new String[]{"yantai_hospital_clinical_patients"}).setTypes(new String[]{"patients"}).setSearchType(SearchType.DFS_QUERY_THEN_FETCH).setSource(searchSourceBuilder);


            SearchResponse responsesearch = (SearchResponse) builder.setScroll("5m").setSize(500).execute().actionGet();

            totalResults += responsesearch.getHits().getHits().length;
            int expectedSliceResults = (int) responsesearch.getHits().getTotalHits();
            int numSliceResults = responsesearch.getHits().getHits().length;
            String scrollId = responsesearch.getScrollId();

            for (SearchHit hit : responsesearch.getHits().getHits()) {
                keys.add(hit.getId());
            }

            while (responsesearch.getHits().getHits().length > 0) {
                responsesearch = client.prepareSearchScroll("test")
                        .setScrollId(scrollId)
                        .setScroll(new Scroll(TimeValue.timeValueSeconds(10)))
                        .get();
                scrollId = responsesearch.getScrollId();
                totalResults += responsesearch.getHits().getHits().length;
                numSliceResults += responsesearch.getHits().getHits().length;
                for (SearchHit hit : responsesearch.getHits().getHits()) {
                    keys.add(hit.getId());
                }
            }


            client.close();

            System.out.println("sclice:" + i + "," + numSliceResults);
        }
        System.out.println("total:" + totalResults);
    }`
i have 5 shards, total 11501 docs.
The following is the case of 7slice output

> sclice:0,1168
sclice:1,1155
sclice:2,2282
sclice:3,2333
sclice:4,2284
sclice:5,1167
sclice:6,1120
total:11509
Our elasticsearch server version is 5.1.1，my elasticsearch client is 5.2.0. i has try it on http,This is also the case.

thanks

**Comment by jimczi** [comment]
@liuyaopeng I tried to reproduce your issue but couldn't. I checked with 5.1.1, 5.2, 5.3, 5.x and master, they all returned the expected number of hits using your code (and random data). 
> I have 5 shards, total 11501 docs.

Are you sure ? ;)
Are you adding/deleting/updating documents during your test ? Can you try to do:

````
GET yantai_hospital_clinical_patients/patients/_search
{
}
````
.. and check the `hits.total` returned in the response. Is it 11501 ?

**Comment by liuyaopeng** [comment]
@jimczi 

> "took": 10,
"timed_out": false,
"_shards": {
"total": 5,
"successful": 5,
"failed": 0
},
"hits": {
"total": 11501,

Here was the  response header.
Where i test, nobody doing adding/deleting/updating for the  documents.

I found that each with a slice query out the number of data is not unique, is a random change. For example, slice0, there may be 1168 or 1160. Or other numbers. So it will cause the total number of inconsistencies.
Do you know what the situation is? Do you  have any ideas to fix it?

**Comment by jimczi** [comment]
> I found that each with a slice query out the number of data is not unique, is a random change. For example, slice0, there may be 1168 or 1160. Or other numbers. So it will cause the total number of inconsistencies.

This should not happen unless you have replicas out of sync. The slice query choose a set of replica to run the query and stick to it for the whole scroll. Each slice is independent and can choose a different replica to perform the request so I suspect that you have replicas with different number of documents. Can you check that ?

**Comment by liuyaopeng** [comment]
@jimczi 
I checked the replica of the problem,
but i could not found any problem about that.

> yantai_hospital_clinical_patients 1 r STARTED 2275 11.9mb 10.0.0.66 node-66
yantai_hospital_clinical_patients 1 p STARTED 2275 11.9mb 10.0.0.67 node-67
yantai_hospital_clinical_patients 2 p STARTED 2282 13.6mb 10.0.0.66 node-66
yantai_hospital_clinical_patients 2 r STARTED 2282 13.6mb 10.0.0.67 node-67
yantai_hospital_clinical_patients 4 p STARTED 2284 12.5mb 10.0.0.66 node-66
yantai_hospital_clinical_patients 4 r STARTED 2284 12.5mb 10.0.0.67 node-67
yantai_hospital_clinical_patients 3 r STARTED 2333   13mb 10.0.0.66 node-66
yantai_hospital_clinical_patients 3 p STARTED 2333   13mb 10.0.0.67 node-67
yantai_hospital_clinical_patients 0 p STARTED 2327 12.9mb 10.0.0.66 node-66
yantai_hospital_clinical_patients 0 r STARTED 2327 12.9mb 10.0.0.67 node-67

**Comment by clintongormley** [comment]
@liuyaopeng can you provide your index to us so that we can try to replicate on our side?

**Comment by liuyaopeng** [comment]
@clintongormley 
How do i give you my index？
Do i send data to clint@traveljury.com?

**Comment by wuxmer** [comment]
@liuyaopeng The same bug occurs in my project, have u fix it now ?

**Comment by jimczi** [comment]
@wuxmer which version are you using ? This bug is fixed since 5.3.1 so if you have an issue with slicing in a version that has the fix you should open another issue.
