### ISSUE TITLE
Document `eager_global_ordinals`

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#23101]
`eager_global_ordinals` is missing from https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-params.html and from the corresponding  [field datatypes](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-types.html)

**Comment by nezda** [comment]
also https://github.com/elastic/elasticsearch/issues/8053#issuecomment-287817376
