### ISSUE TITLE
min_score with percolator

### ISSUE THREAD

**Issue by Raghavsalotra** [elastic/elasticsearch#23103]
**Elasticsearch version**: 5.1

**Plugins installed**: [head]

**JVM version**: 1.8

**OS version**: ubuntu 14.01

**Describe the feature**:

Is there a way to use min_score with Elasticsearch5.1 percolator. I thought of doing it by putting field
with type percolator with field holding query json as a nested field.
eg:

MAPPING
```
{"properties":{
"parent_field"{"type": "percolator"}
}}
```

Document:
```
{"parent_field": {"query": {<query json>},
                            "min_score": 10}}
```

this way elastic is not allowing me to even index that document.

Thanks.

**Comment by clintongormley** [comment]
No you can't use `min_score` there.  You could use  `min_score` in the search request that you use to execute the percolation query.
