### ISSUE TITLE
Corrupted index after the amazon network issue

### ISSUE THREAD

**Issue by BalamuruganMariyappan** [elastic/elasticsearch#23100]
**Elasticsearch version**:1.4.2-1

**Plugins installed**: []

**JVM version**:1.7.0_91"

**OS version**:Amazon Linux AMI-2015.09

**Description of the problem including expected versus actual behavior**:
 We have  3 node ES cluster and that has been hosted on AWS . We can see below error message, after the amazon network connectivity issue( see https://status.aws.amazon.com/) which is happen on today. Could you please advise how I can bring up the cluster again to good state, without any data?

**Provide logs (if relevant)**:

[index.store ] [ [.marvel-2015.03.19][0] Failed to open / find files while reading metadata snapshot
[2017-02-10 01:54:54,379][WARN ][index.engine.internal ] [.marvel-2015.03.16][0] failed engine [corrupted preexisting index]
org.apache.lucene.index.CorruptIndexException: [.marvel-2015.03.16][0] Preexisting corrupted index [corrupted_Jja1GRiPTFyzm4G_tuEvsg] caused by: CorruptIndexException[codec footer mismatch: actua
l footer=1431655765 vs expected footer=-1071082520 (resource: NIOFSIndexInput(path="/es-data/evs01/nodes/0/indices/.marvel-2015.03.16/0/index/_83k_es090_0.doc"))]
**Describe the feature**:

**Comment by bleskes** [comment]
> Could you please advise how I can bring up the cluster again to good state, without any data?

Delete the indices that are corrupted.

> Elasticsearch version:1.4.2-1

This ^^ is the biggest issue to be honest. So many things have been fixed in this area, including checks during data transfers to make sure corrupted data isn't copied around. I strongly suggest you upgrade ASAP.

If you have any more questions, please ask at discuss.elastic.co. We try keep github for issues and freature requests.

**Comment by BalamuruganMariyappan** [comment]
@Boaz Leskes , thank  you so much for your advise.
