### ISSUE TITLE
Problem with ElasticSearch's partial highlighting of a term which contain more than 2 similar characters.

### ISSUE THREAD

**Issue by ilia-valchenko** [elastic/elasticsearch#23105]
**Elasticsearch version**: ElasticSearch-2.3.5

**Plugins installed**: [kopf]

**JVM version**: java version "1.8.0_121"

**OS version**: Windows 10

![analyzer-4-1](https://cloud.githubusercontent.com/assets/20212906/22825666/b5736734-ef9f-11e6-8c0f-3d9e2f3854a2.png)
![analyzer-4-1-bug](https://cloud.githubusercontent.com/assets/20212906/22825667/b576278a-ef9f-11e6-903e-3f69647b18e0.png)
![duplicate](https://cloud.githubusercontent.com/assets/20212906/22825668/b576ea62-ef9f-11e6-8c86-434c30cb4a61.png)

**Description of the problem including expected versus actual behavior**:
The problem is that elasticsearch highlighter can't highlight the word which contain more then one similar characters. You can see it in attached images. I tried to use another version of nGram such as 4.1, but it doesn't help me. 

This is the settings of my index: 

```
"index": {
    "creation_date": "1486725803911",
    "analysis": {
      "analyzer": {
        "customIndexNgramAnalyzer": {
          "filter": [
            "lowercase"
          ],
          "type": "custom",
          "tokenizer": "customNGramTokenizer"
        },
        "customSearchNgramAnalyzer": {
          "filter": [
            "lowercase"
          ],
          "type": "custom",
          "tokenizer": "keyword"
        }
      },
      "tokenizer": {
        "customNGramTokenizer": {
          "token_chars": [
            "letter",
            "digit"
          ],
          "min_gram": "1",
          "type": "ngram",
          "max_gram": "15"
        }
      }
    },
    "number_of_shards": "5",
    "number_of_replicas": "1",
    "uuid": "qYKuwo7bR-ug_U1cNL5iNA",
    "version": {
      "created": "2030599"
    }
  }
```

Mapping settings:

```
"task": {
    "properties": {
      "PublishDate": {
        "format": "strict_date_optional_time||epoch_millis",
        "type": "date"
      },
      "Description": {
        "type": "string"
      },
      "IsCompleted": {
        "null_value": false,
        "store": true,
        "type": "boolean"
      },
      "Title": {
        "search_analyzer": "customSearchNgramAnalyzer",
        "analyzer": "customIndexNgramAnalyzer",
        "type": "string"
      },
      "Id": {
        "type": "float"
      }
    }
  }
```

This is my query:

```
{
  "query": {
    "match": {
      "Title": "h"
    }
  },
  "highlight": {
    "fields": {
      "Title": {}
    }
  }
}
```

This is a part of response: 

```
{
        "_index": "taskmanager",
        "_type": "task",
        "_id": "8",
        "_score": 0.26481834,
        "_source": {
          "Id": 8,
          "Title": "Highlight",
          "Description": "Add highlight to my project.",
          "PublishDate": "2017-02-09T12:19:54",
          "IsCompleted": false
        },
        "highlight": {
          "Title": [
            "<em>Highligh</em>t"
          ]
        }
      }

```

As you can see I got wrong highlighting value. The excepted result is `<em>H</em>ighlig<em>h</em>`t

There are terms which were created by my analyzer: 

```
{
        "_index": "taskmanager",
        "_type": "task",
        "_id": "12",
        "_score": 1,
        "fields": {
          "terms": [
            "g",
            "gh",
            "h",
            "hi",
            "hig",
            "high",
            "i",
            "ig",
            "igh"
          ]
        }
      }



```

**Steps to reproduce**:
 1. Start elasticsearch-2.3.5
 2. Install and run kopf plugin
 3. Create an index by using json which is given above
 4. Add some "task" entity to your index. 

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by clintongormley** [comment]
This is a limitation of the plain highlighter.  It works with the FVH and the postings highlighter, and it works without `term_vector` or `index_options` with the new unified highlighter that is coming in 5.3.0.
