### ISSUE TITLE
Empty string with completion type results in IllegalArgumentException

### ISSUE THREAD

**Issue by bjfish** [elastic/elasticsearch#23121]
**Elasticsearch version**:
5.2.0

**Description of the problem including expected versus actual behavior**:

Result is IllegalArgumentException. Expected empty strings to be ignored.

Is this an issue? If not, is there a recommended resolution?

**Steps to reproduce**:
In Sense:
```
PUT twitter
{
  "mappings": {
    "tweet": {
      "properties": {
        "message": {
          "type": "completion"
        }
      }
    }
  }
}

PUT twitter/tweet/3
{
    "message" : ""
}
```
Edit: Updated description to simpler example.

**Comment by clintongormley** [comment]
I agree - empty string should be ignored.

Simpler recreation:

```
PUT twitter
{
  "mappings": {
    "tweet": {
      "properties": {
        "message": {
          "type": "completion"
        }
      }
    }
  }
}

PUT twitter/tweet/3
{
    "message" : ""
}
```

**Comment by florianflock** [comment]
Have the same issue. Does anyone have a solution for that?

**Comment by andyb-elastic** [comment]
@elastic/es-search-aggs 

Jim has a PR open for this #28289
