### ISSUE TITLE
normalizers to support pattern_replace char filter

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#23142]
```json
PUT test-index
{
  "settings": {
    "analysis": {
      "char_filter": {
        "whitespace_remove": {
          "type": "pattern_replace",
          "pattern": "\\s+",
          "replacement": " "
        }
      },
      "normalizer": {
        "my_normalizer": {
          "type": "custom",
          "char_filter": ["whitespace_remove"],
          "filter": ["lowercase", "asciifolding"]
        }
      }
    }
  },
  "mappings": {
    "type": {
      "properties": {
        "foo": {
          "type": "keyword",
          "normalizer": "my_normalizer"
        }
      }
    }
  }
}
```

Returns with :

```json
{
   "error": {
      "root_cause": [
         {
            "type": "illegal_argument_exception",
            "reason": "Custom normalizer [my_normalizer] may not use char filter [whitespace_remove]"
         }
      ],
      "type": "illegal_argument_exception",
      "reason": "Custom normalizer [my_normalizer] may not use char filter [whitespace_remove]"
   },
   "status": 400
}
```

Note the use case - normalizing whitespace of keyword fields, to overcome differences in user queries (for exact boosting) or aggregations on user based content

**Comment by jpountz** [comment]
We accept the same set of analysis components for normalizers and analyzing prefix/wildcard queries, and I think `pattern_replace` filters should be applied. I opened https://issues.apache.org/jira/browse/LUCENE-7692 to discuss it.

**Comment by pmusa** [comment]
I am getting the same error trying to use synonyms. Is it also going to be supported by the change @jpountz?

**Comment by jpountz** [comment]
The particular issue that @synhershko reported will be fixed when we upgrade to Lucene 6.5 (which is expected to be the case for Elasticsearch 5.4). However synonyms are more complicated since the set of synonym rules is currently opaque to the consumers of the synonym filter, so they have no way to know whether the synonym filter introduces new tokens or whether it only replaces some tokens.

**Comment by pmusa** [comment]
What I wanted was a dictionary. Like synonyms with just the keyword tokenizer, but that is not guaranteed for all users :/ Guess fielddata it is :)

**Comment by jpountz** [comment]
Can't you do something with ingest?

**Comment by pmusa** [comment]
I need a dictionary lookup: "elastic search" => "elasticsearch", "es" => "elasticsearch", which is not natively implemented (and I don't think it will). I could do it with scripts defining the dictionary (it is small) in the pipeline itself. (I will try both and check the performance impact). Thanks

**Comment by maciejjarzynski** [comment]
Is there any update on that issue?

**Comment by Lackoftactics** [comment]
Any progress on 6.2? Need this feature

**Comment by jpountz** [comment]
Added to 5.4.0 via #23385.
