### ISSUE TITLE
Expose more summary metrics in bulk API response

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#23143]
_Note: I created this ticket due to a discussion with @bleskes in elastic/rally#207_

Today a typical bulk response looks like:

```json
{
   "took": 30,
   "errors": false,
   "items": [
      {
         "index": {
            "_index": "test",
            "_type": "type1",
            "_id": "1",
            "_version": 1,
            "result": "created",
            "_shards": {
               "total": 2,
               "successful": 1,
               "failed": 0
            },
            "created": true,
            "status": 201,
            "_seq_no" : 0
         }
      }
   ]
}
```

This is fine as long as no errors occur. However, in case of errors, clients need to traverse the complete response structure to get information like:

* How many operations succeeded / failed?
* Did we have shard failures? How many shards failed?

Here is an example of what Rally extracts from a bulk response with 4.000 successful indexing operations, 500 operations where one out of two shards failed and 500 operations with both shards failed:

```json
{
  "bulk-size": 5000,
  "errors": true,
  "success-count": 4000,
  "error-count": 1000,
  "ops": {
    "index": {
      "item-count": 5000,
      "created": 4000,
      "noop": 1000
    }
  },
  "shards_histogram": [
    {
      "item-count": 4000,
      "shards": {
        "total": 2,
        "successful": 2,
        "failed": 0
      }
    },
    {
      "item-count": 500,
      "shards": {
        "total": 2,
        "successful": 1,
        "failed": 1
      }
    },
    {
      "item-count": 500,
      "shards": {
        "total": 2,
        "successful": 0,
        "failed": 2
      }
    }
  ],
   "took": 30,
   "errors": true,
   "items": [ { "...": "..." } ]
}
```

_Note: Don't treat this as definitive response structure. This just serves as an illustration of what I'm after._

What I want to put up for discussion is:

1. Is such a feature useful for clients in general?
2. If yes, then which data should we provide at the top-level?

**Comment by clintongormley** [comment]
As a client author, this data wouldn't be useful to me.  What I need to know is which items failed so that I can pass each item to the user's code for handling one by one.  This is already possible with the API today.

**Comment by bleskes** [comment]
@clintongormley the discussion we had was around giving an easy indication that one need to go and iterated over the items looking for information. For errors, we already have an `errors: true`. Rally needed a slightly more subtle flag indicating that one of the replicas have failed. My idea was to merge all the _shards headers from the shard level bulk into a single shard header at the top of the bulk response. Rally can then look at those numbers and if total != successful it can report something didn't go as planned (if relevant).

**Comment by clintongormley** [comment]
@bleskes but would this be generally useful outside Rally?  I'm not seeing the utility.

**Comment by bleskes** [comment]
The only valid use I see (next to Rally) is for people that really want to make sure their data is on at least X amount of copies. In those cases you need to inspect all the `_shards` headers and this can be a nice optimization. Of course it's a judgment call as to whether this all is worth the extra code. I'm fine with going either way.

**Comment by danielmitterdorfer** [comment]
We discussed it in Fix It Friday and the consensus was that we want to keep the response as minimal as possible. Hence closing.
