### ISSUE TITLE
wildcards not supported when date math is used in index names

### ISSUE THREAD

**Issue by sarwarbhuiyan** [elastic/elasticsearch#23145]
**Elasticsearch version**: 5.2

**Plugins installed**: []

**JVM version**: 1.8

**OS version**: Redhat

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Create indices such as metricbeat-1234-2017.02.13 and index some data
 2. Try to query index using date math and wild card <metricbeat-*-{now/d}>
 3.  Query returns 0 results

**Comment by cbuescher** [comment]
cc @elastic/es-search-aggs

**Comment by talevy** [comment]
We feel that adding complexity to the index name resolution is not the direction we want to take. One option is to leverage aliases to group the different `metricbeat` use-cases in such a way that this level of querying is possible.

I will go ahead and close this for now, but if workarounds for this become too unwieldy, feel free to raise a comment we can happily re-discuss!
