### ISSUE TITLE
ClassCastException with ES 5.2 and reindex requests

### ISSUE THREAD

**Issue by salyh** [elastic/elasticsearch#23144]
Elasticsearch Version: 5.2.0

I write a plugin where i need to check if a request is a `ReindexRequest` and if so i like to cast the `ActionRequest` type to `ReindexRequest` type and do something with it.

Within an `ActionFilter` implementation in the `apply()` method i check if `request instanceof ReindexRequest` but it appears that this _instanceof_ comparison fails because `request` and `ReindexRequest` seems to be the same class but loaded by different classloaders. Looks like one side of the comparison is loaded by the plugin classloader and the other by the "main" elasticsearch classloader or the reindex module classloader.

In the my plugin dependencies i added a dep to org.elasticsearch.plugin:reindex-client:5.2.0

**Comment by rjernst** [comment]
You won't be able to modify the ReindexRequest, for the reason you mention (plugins are in isolated classloaders).  If you are trying to modify the index request, you should just modify it client side.

If that does not work for you, we can further help you come up with a solution at https://discuss.elastic.co.  We reserve github for verified bug reports and feature requests.
