### ISSUE TITLE
[illegal_argument_exception] explicit index in bulk is not allowed 

### ISSUE THREAD

**Issue by orthecreedence** [elastic/elasticsearch#23150]
I've upgraded to elasticsearch 5.1.1 (I'm on the AWS-hosted elasticsearch service, so the version and config are out of my control) and trying to use the bulk API to move a large number of records from our database to elasticsearch.

I'm getting the error: 

```
{ [Error: [illegal_argument_exception] explicit index in bulk is not allowed]
  status: 400,
  displayName: 'BadRequest',
  message: '[illegal_argument_exception] explicit index in bulk is not allowed',
  path: '/_bulk',
  query: {},
  body: '{"index":{"_index":"cards.2017-02-08","_type":"card","_id":23891342}}\n{"id":23891342,"entity_id":28400,"type":"news"}\n',
  statusCode: 400,
  response: '{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"explicit index in bulk is not allowed"}],"type":"illegal_argument_exception","reason":"explicit index in bulk is not allowed"},"status":400}',
  toString: [Function],
  toJSON: [Function] }
```

Any idea what this means or how to work around it?

Thank you.

**Comment by tlrx** [comment]
This error happens when the setting `rest.action.multi.allow_explicit_index` is set to false. You can find more information in https://www.elastic.co/guide/en/elasticsearch/reference/5.2/url-access-control.html

**Comment by tlrx** [comment]
I closed the issue because it isn't a bug, and we reserve Github issues for bugs.

There are good chances that in your case, the cluster has the setting I mentioned set to `false` and the bulk request body contains document that refers to indices that are different form the one specified in the URL.

**Comment by orthecreedence** [comment]
Thanks for the link! I'll do some more reading.
