### ISSUE TITLE
Combined space and time support for points

### ISSUE THREAD

**Issue by Michael-Jing** [elastic/elasticsearch#23158]
**Describe the feature**:
this [blog](https://www.elastic.co/blog/lucene-points-6.0) describes the potential advantage of doing multidimensional range query, say, geo_spatial plus time, I would like that come into reality.

Basically, I need to do queries like find me certain kind of things happened in an area during a specified time range, so a type with three fields, ie, latitude, longitude and timestamp is what I need.

**Comment by jpountz** [comment]
Agreed that encoding time as a 3rd dimension might allow for interesting speedups when filtering on both location and time, however it raises some challenges in terms of integration.

In the mean time, a workaround is to index location and time as two different fields of type `date` and `geo_point`, and use the `bool` query to filter on location and time at the same time.

**Comment by kraanerk** [comment]
3D point (x, y, z) support would be really nice to have.

**Comment by bhavesh123** [comment]
Waiting for this feature to release.. It will be really exciting..

**Comment by Ristellise** [comment]
Any update to this? This seems like a really interesting support, I also don't think it's too hard to implement it fully either. Any status update would be appreciated 😄

**Comment by sqlboy** [comment]
+1

**Comment by craigtaverner** [comment]
This issue describes correlating time indexing with spatial indexing, and so should be considered separately from spatial 3D (or 2.5D) indexing, which is something that has been of interest for some time, but not relevant to this issue. I've changed the title to better represent the spatial-temporal feature.

Having said that, combining time into the same index as space is a non-trivial exercise. It is also worth noting that many spatial indexes are optimised around the fact that you 'zoom in' on all dimensions simultaneously. If you query a narrow latitude range, you also query a similarly narrow longitude range. This is not true if you build in a temporal dimension. As such it is more common to use separate space and time indexes, and query first the most restrictive, and filter on the other. For this reason we think that people interested in both time and space queries, should keep an eye on TSDB features in Elasticsearch. We'll close this issue in favour of the work in TSDB, for example https://github.com/elastic/elasticsearch/issues/85274
