### ISSUE TITLE
Red Hat versions below 7 do not support SECCOMP

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#23159]
**Elasticsearch version**:
ES 5.2.0
**OS version**:
Red Hat 6

Red Hat versions prior to 7 do not support SECCOMP which will lead to bootstrap failure without configuring `bootstrap.system_call_filter: false`. Let's call out the lack of SECCOMP in RHEL 6 in the docs until Elasticsearch no longer supports it. 

https://github.com/elastic/elasticsearch/issues/22899

**Comment by rjernst** [comment]
This hasn't really come up again in 2 years. Closing.
