### ISSUE TITLE
cluster.routing.allocation.node_concurrent_recoveries not documented under cluster settings

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#23152]
Breaking changes doc calls out [cluster.routing.allocation.concurrent_recoveries](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_settings_changes.html#_allocation_settings
) and [indices.recovery.concurrent_streams](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_settings_changes.html#_recovery_settings) being replaced by `cluster.routing.allocation.node_concurrent_recoveries`.

But `cluster.routing.allocation.node_concurrent_recoveries` is [not documented](https://www.elastic.co/guide/en/elasticsearch/reference/master/shards-allocation.html
).    The closest settings you can find are `cluster.routing.allocation.node_concurrent_incoming_recoveries` and `cluster.routing.allocation.node_concurrent_outgoing_recoveries`.  Are we now recommending setting separate incoming and outgoing recoveries?  Or is this a miss in the documentation?

**Comment by bleskes** [comment]
Thx @ppf2 . I opened #23160 adding this to the docs. It's a valid settings.
