### ISSUE TITLE
ctx._now time seems to be incorrect

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#23169]
To repro:

Create a document, then update it as follows:

```
POST my-index/my-type/1/_update
{
   "script" : {
       "inline": "ctx._source.timestamp_now = ctx._now; ctx._source.epochms = new Date().getTime();",
       "lang": "painless"
   },
   "upsert" : {
       "foo":"bar"
   }
}
```

In the results we're seeing, epochms is correct, but timestamp_now seems to be a random time.  The ctx._now time is consistently increasing, but on various different nodes it has returned times ranging from 2003 to 2019.

**Comment by rjernst** [comment]
@seang-es Can you please include the exact mappings, as well as the output when retrieving the updated document?

**Comment by jpcarey** [comment]
Elasticsearch 5.2.0 + x-pack, macOS Sierra 10.12.3 (16D32), Oracle java version "1.8.0_65"
```
POST t/t/1
{
  "foo": "bar"
}
POST t/t/1/_update
{
  "script": {
    "inline": "ctx._source.timestamp_now = ctx._now; ctx._source.epochms = new Date().getTime();",
    "lang": "painless"
  },
  "upsert": {
    "foo": "bar2"
  }
}
```
`GET t/t/1` Response:
```
{
  "_index": "t",
  "_type": "t",
  "_id": "1",
  "_version": 4,
  "found": true,
  "_source": {
    "foo": "bar",
    "timestamp_now": 1206909990,
    "epochms": 1487111464024
  }
}
```
`GET t/_mapping` Response:
```
{
  "t": {
    "mappings": {
      "t": {
        "properties": {
          "epochms": {
            "type": "long"
          },
          "foo": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "timestamp_now": {
            "type": "long"
          }
        }
      }
    }
  }
}
```

**Comment by s1monw** [comment]
I think this is a bug. _now is set to nanotime in millis.

**Comment by rjernst** [comment]
I found the bug. We currently use `System.nanoTime()` and convert that to milliseconds, but that is *not* milliseconds since epoch. This was changed about 1.5 years ago to avoid System.currentTimeMillis() from going backwards (see #11626).  We either need to go back to System.currentTimeMillis(), or look at how to protecting from negative time diffs differently.

**Comment by rjernst** [comment]
Oops sorry Simon, I guess that's what you were trying to say. :)
