### ISSUE TITLE
Ingest timestamp is not parseable as a valid ES date

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#23168]
To repro:

Create an index with a field 'timestamp' set to date type.
Create the following ingest pipeline:

```
PUT _ingest/pipeline/timestamp 
{ 
"description" : "Adds a timestamp field at the current time", 
"processors" : [ { 
"set" : { 
"field": "timestamp", 
"value": "{{_ingest.timestamp}}" 
} 
} ] 
} 
```

Attempt to ingest a document using this pipeline.

Result:

```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse [timestamp]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse [timestamp]",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "Invalid format: \"Tue Feb 14 12:49:00 EST 2017\""
    }
  },
  "status": 400
}
```

This is specifically the method described in the documentation as a possible replacement for _timestamp.  We can work around it with a date processor in the ingest pipeline, but that's a really clunky solution for users trying to get the _timestamp feature back.

**Comment by A-Triaca** [comment]
This appears to have been marked as deprecated?
https://github.com/elastic/elasticsearch/blob/945b3cd4ca5cba36e3dddcc5d8b1d795f4c788cc/qa/smoke-test-ingest-with-all-dependencies/src/test/resources/rest-api-spec/test/ingest/60_pipeline_timestamp_date_mapping.yaml#L62
What is the expected way of creating an ingest pipeline that inserts a datetime?
