### ISSUE TITLE
Elasticsearch incorrectly handles expect header

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#23172]
If you send a 100-continue header to Elasticsearch with a content-length header that exceeds the configured max content length, Elasticsearch responds with a 417 status (Expectation Failed). Since we intend to support the 100-continue header (we basically have to since curl automatically sends it as soon as the content-length is at least 1024 bytes), this is a violation of the HTTP specification; instead, we should be responding with 413 status (Request Entity Too Large). The 417 status is intended to only be used if the server does not support an expectation that the client specified in the expect header. That brings us to our second source of trouble. The specification defines expectation extensions and this is where 417 status replies are okay. If the client sends an expect header containing anything other than 100-continue, we should be replying with 417 status but instead we reply with 200 status.

The relevant section from the specification:

>The server MUST respond with a 417 (Expectation Failed) status if any of the expectations cannot be met or, if there are other problems with the request, some other 4xx status.

Of the two aforementioned problems, it's the first that is awful for end users. This is because if try to send a request to Elasticsearch that exceeds the content-length, Elasticsearch does not help them by telling them the request is too large. Instead, it provides the completely misleading 417 status. At this point, users are rightfully lost. With Elasticsearch configured to have a max content length of 100MiB:

```
17:43:18 [jason:~] $ dd if=/dev/zero of=zero count=128 bs=1024k
128+0 records in
128+0 records out
134217728 bytes transferred in 0.099644 secs (1346970013 bytes/sec)
17:43:19 [jason:~] $ curl -v localhost:9200/ --data-binary @zero
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9200 (#0)
> POST / HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.51.0
> Accept: */*
> Content-Length: 134217728
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
< HTTP/1.1 417 Expectation Failed
< content-length: 0
* HTTP error before end of send, stop sending
< 
* Curl_http_done: called premature == 0
* Closing connection 0
17:43:23 [jason:~] $ curl -v -H "Expect: chocolate=yummy" localhost:9200/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9200 (#0)
> GET / HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.51.0
> Accept: */*
> Expect: chocolate=yummy
> 
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 322
< 
{
  "name" : "49wXA7G",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "J33uKzjOSi2PYl3dlE1R_A",
  "version" : {
    "number" : "6.0.0-alpha1",
    "build_hash" : "5343b87",
    "build_date" : "2017-02-13T22:41:34.078Z",
    "build_snapshot" : true,
    "lucene_version" : "6.5.0"
  },
  "tagline" : "You Know, for Search"
}
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

The cause of this issue is due to a specification violation in the Netty 4 HTTP codec. I have opened netty/netty#6374 and with this patch, Elasticsearch will do the right thing:

```
17:43:25 [jason:~] $ dd if=/dev/zero of=zero count=128 bs=1024k
128+0 records in
128+0 records out
134217728 bytes transferred in 0.091381 secs (1468769446 bytes/sec)
17:43:56 [jason:~] $ curl -v localhost:9200/ --data-binary @zero
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9200 (#0)
> POST / HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.51.0
> Accept: */*
> Content-Length: 134217728
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
< HTTP/1.1 413 Request Entity Too Large
< content-length: 0
* HTTP error before end of send, stop sending
< 
* Curl_http_done: called premature == 0
* Closing connection 0
17:43:58 [jason:~] $ curl -v -H "Expect: chocolate=yummy" localhost:9200/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9200 (#0)
> GET / HTTP/1.1
> Host: localhost:9200
> User-Agent: curl/7.51.0
> Accept: */*
> Expect: chocolate=yummy
> 
< HTTP/1.1 417 Expectation Failed
< content-length: 0
< 
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

**Comment by jasontedor** [comment]
This is blocked on a release of Netty that incorporates netty/netty#6374.

**Comment by jasontedor** [comment]
The PR netty/netty#6374 has been integrated, we only awaiting a release now.

**Comment by sfratini** [comment]
@jasontedor  I understand this is an awful old bug and closed, however I am having this issue trying to query ElasticSearch from the PowerBI desktop Web DataSource even on 6.0.1 version. 

Is this suppose to still happen? I have been reading that PowerBI does actually add the Expect-100 header so this is expected. 

What is the workaround/solution here then? Changing the content-length setting in ElasticSearch?

https://stackoverflow.com/questions/566437/http-post-returns-error-417-expectation-failed
