### ISSUE TITLE
Wrong distance calculation

### ISSUE THREAD

**Issue by enp** [elastic/elasticsearch#23178]
**Elasticsearch version**: 5.1.1

**Plugins installed**: [ingest-geoip,ingest-user-agent]

**JVM version**:openjdk 1.8.0_71

**OS version**:Linux kernel 4.4.39

**Description of the problem including expected versus actual behavior**: distance calculation in custom score function and in decay functions works wrong, but works good while sorting by distance. 

More details in https://discuss.elastic.co/t/scoring-by-distance/75141. Is this enough or I need to attach json files with test data and test requests?

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
