### ISSUE TITLE
Error while setting up a parallel cluster to upgrade from 1.7.5 to 5.2.1

### ISSUE THREAD

**Issue by ImdotnetJunkie** [elastic/elasticsearch#23197]
**Elasticsearch version**: 5.2.1

**Plugins installed**: [NONE]

**JVM version**: 1.8.0_40

**OS version**: Windows2008R2

**Description of the problem including expected versus actual behavior**:
We had earlier version(1.75) of ES running and now we are trying to upgrade to 5,2 as per the upgrade guidelines. I'm trying to set up a parallel cluster and getting below Error while starting ES:

Error: encountered environment variables that are no longer supported
use jvm.options or ES_JAVA_OPTS to configure the JVM
ES_HEAP_SIZE=4g: set -Xms4g and -Xmx4g in jvm.options or add @-Xms4g -Xmx4g@ to ES_JAVA_OPTS

Although, jvm.options file already contains these setting by default.

**Steps to reproduce**:
 1. Must have old version (1.7.5) of ES and set env varibale "ES_HEAP_SIZE=4g"
 2. Set up new ES (5.2.1)
 3. Go to bin directory
 4. Start Command Prompt from here
 5. Start ElasticSearch.bat 

**Provide logs (if relevant)**:

**Comment by rjernst** [comment]
You need to remove ES_HEAP_SIZE from your environment.

**Comment by ImdotnetJunkie** [comment]
Wouldn't this impact our existing cluster ?

**Comment by rjernst** [comment]
@ImdotnetJunkie You need to remove it when you upgrade.  The new jvm options handling errors when the old mechanisms to set these parameters are found, so that someone does not accidentally believe they are being set, when in fact they need to adjust how they set them for the new system. Hence the error message which explains exactly how to set the same with the new way.

**Comment by ImdotnetJunkie** [comment]
As, i mentioned that im gonna run parallel cluster for some time while we move over to 5.x completely. So, if i remove this env variable and start my ES Service (1.7.5), would it run without any issues ?

**Comment by jasontedor** [comment]
If you need the heap setting for 1.7.5, then you have to set them somehow. You could for example start 1.7.5 with the `ES_HEAP_SIZE` heap setting, and start 5.x without it.

**Comment by ImdotnetJunkie** [comment]
@jasontedor : To start 5.x cluster, i need to comment out (as below) in every batch file e.g. (elasticsearch.bat, elasticsearch-service.bat etc)

rem if not "%ES_HEAP_SIZE%" == "" set bad_env_var=1

Is that correct ?

**Comment by jasontedor** [comment]
I would advise against modifying the startup scripts, that's entering territory that we do not support. My advise would be to unset `ES_HEAP_SIZE` when starting Elasticsearch 5.x, and setting it again before starting Elasticsearch 1.x.
