### ISSUE TITLE
Remove usage of `TermsQuery`

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#23201]
`TermsQuery` is now deprecated in Lucene and has been replaced by `TermInSetQuery`, which is slightly different as it operates on a single field. We should migrate our usage of `TermsQuery` to `TermInSetQuery`.

**Comment by maddin2016** [comment]
Hi @jpountz, i assume this "only" requires to replace usages of `TermsQuery` with `TermInSetQuery` because it uses the same constructor?

**Comment by jpountz** [comment]
I assume this is what will need to be done in most cases. But the new constructors require that all terms come from the same field and there might be cases when more involved changes need to be done.

**Comment by maddin2016** [comment]
I think it is [this](https://issues.apache.org/jira/secure/attachment/12847631/LUCENE-7637.patch) patch which implements this, right? Is this actually available from sources? If i'm right this line `assert field.equals(iterator.field());` checks the equality of the field. Can you give please an example when terms comes from different fields.

**Comment by jpountz** [comment]
`TermsQuery` had two constructors that took an array or a list of `Term` objects.  They do not exist anymore with `TermsInSetQuery` so call sites that use these constructors may need to construct a BooleanQuery over multiple `TermInSetQuery` instead (one per field).
