### ISSUE TITLE
Feature: Zstandard compression support and possibility to choose a compression algo

### ISSUE THREAD

**Issue by Cornoualis** [elastic/elasticsearch#23204]
Hi !

It would be awesome to add support to [Zstandard](http://facebook.github.io/zstd), an awesome (de)compression algorithm by Facebook.

The [benchmarks ](http://facebook.github.io/zstd/#benchmarks)show impressive speed/compression rate, compared to zlib.

It would be very nice to have the possibility to have an "algorithm" setting in the snapshot API...

**Example:**
```
PUT /_snapshot/my_backup
{
    "type": "fs",
    "type": "fs",
    "settings": {
      "location": "/mount/backups/my_backup",
      "compress": true,
      "algorithm": "zstd"
  }
}
```

There are bindings provided for many languages and of course, for [java/jvm](https://github.com/luben/zstd-jni).

The idea would be to let the user choose an algorithm, which implies that the user has the zstd binaries installed (like elastic requires the jre/jdk to be installed).

**Comment by jpountz** [comment]
On the one hand I like the idea because I think Zstandard is a great compression algorithm. On the other hand, we have been striving to not use libraries that use JNI bindings or Java's `sun.misc.Unsafe` in order to keep troubleshooting easy. Overall this has more cons than pros to me. If compressing snapshots is what you are after, maybe another way to make it work would be to enable compression on the volume that store the snapshots at the filesystem level.

**Comment by Cornoualis** [comment]
Salut and thank you for your answer!
I understand what you mean. I'll give a try on OpenZFS+LZ4 compression...

**Comment by denji** [comment]
The beauty of zstd is achieved using dictionaries. @Cornoualis OpenZFS not fully stable cross platform.

**Comment by mitar** [comment]
MongoDB added Zstandard support and [I did some benchmarks](https://mitar.tnode.com/post/store-ids-in-mongodb-as-binary-or-as-string/) and results are very positive for Zstandard. Maybe this should be revisited?

**Comment by mitar** [comment]
There seems to be also now [a pure Java implementation](https://github.com/airlift/aircompressor/tree/master/src/main/java/io/airlift/compress/zstd) available.

**Comment by jpountz** [comment]
Linking to [LUCENE-8739](https://issues.apache.org/jira/browse/LUCENE-8739) which has related discussions.

**Comment by mitar** [comment]
Related PR: https://github.com/apache/lucene/pull/439

**Comment by kakao-sol-kim** [comment]
@Cornoualis Can I use a dictionary for zstd ?
if I can use zstd dictionary, it makes better efficiency for small docs in es.
