### ISSUE TITLE
Docs out of sync regarding default values for geo_shape mapping

### ISSUE THREAD

**Issue by adambro** [elastic/elasticsearch#23206]
**Elasticsearch version**: number": "5.1.1", "build_hash": "5395e21" from official Docker image

**Description of the problem including expected versus actual behavior**:

When I query the default mapping values using mapping API with `?include_defaults=true` I'm getting the following for `geo_shape` field:

```js
{
              "type": "geo_shape",
              "tree": "geohash",
              "tree_levels": 0,
              "precision": "-1.0m",
              "strategy": "recursive",
              "distance_error_pct": 0.025,
              "orientation": "RIGHT",
              "points_only": false,
              "coerce": false
 }
```

Above values do not match the default values mentioned in documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/5.1/geo-shape.html#geo-shape-mapping-options

Here's the query result when I've added `precision: 1m` property to geo_shape mapping:
```js
{
              "type": "geo_shape",
              "tree": "geohash",
              "tree_levels": 0,
              "precision": "1.0m",
              "strategy": "recursive",
              "distance_error_pct": 0.0,
              "orientation": "RIGHT",
              "points_only": false,
              "coerce": false
}
```

Still `tree_levels` is 0 (which is confusing). On the other hand `distance_error_pct` changes to 0 as documented.

Not sure if it's only docs out o date, because:
* `tree_levels: 0` seems to be a bug
* `precision: "-1.0m"` by default does not make sense

**Comment by clintongormley** [comment]
@nknize could you have a look please?

**Comment by adambro** [comment]
Hi @clintongormley and @nknize any news on geo search docs being out of date?

**Comment by imotov** [comment]
The problem here is not that the docs are out of sync, but that we are showing placeholder values instead of default values in the mapping with `?include_defaults=true`. Placeholder values are not the actual values that are used, but instead they indicate that the value wasn't specified and we should use defaults instead. The result might be confusing. For example the placeholder value of `-1` for precision indicates that the default value of `50m` should be used.

**Comment by adambro** [comment]
@imotov thanks for handling this!
