### ISSUE TITLE
Minor fix of _cat documentation

### ISSUE THREAD

**Issue by biyuhao** [elastic/elasticsearch#23211]
**Elasticsearch version**:5.2

**Plugins installed**: []

**JVM version**:1.8.0

**OS version**:macOS

**Description of the problem including expected versus actual behavior**:
There is a missing `\n` after `/_cat/thread_pool/{thread_pools}` in `_cat` documentation

**Steps to reproduce**:
 1.curl -XGET 127.0.0.1:9200/_cat

**Provide logs (if relevant)**:
part of output:
...
/_cat/thread_pool
**/_cat/thread_pool/{thread_pools}/_cat/plugins**
/_cat/fielddata
...

expected output:
...
/_cat/thread_pool
**/_cat/thread_pool/{thread_pools}**
**/_cat/plugins**
/_cat/fielddata
...

**Comment by clintongormley** [comment]
Thanks for reporting @biyuhao .  Would you like to send a PR?

**Comment by biyuhao** [comment]
Working on it, just a minute.
