### ISSUE TITLE
Multi-match type exceptions in Query String Query

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#23210]
When querying across multiple fields of different types in Query String Query, if there is a mismatch between the data type of the query string and the data type of the queried field, then an exception occurs.  When a similar search is run via `multi_match`, no issue is observed.  Tested under ES 5.2.0

```
PUT /tester22/
{
   "mappings": {
      "test": {
         "properties": {
            "Product": {
               "properties": {
                  "Id": {
                     "type": "string"
                  },
                  "IsBlue": {
                     "type": "boolean"
                  },
                  "Inventory": {
                     "type": "long"
                  }
               }
            }
         }
      }
   }
}

POST /tester22/test
{
    "Product":{
        "Id": "asdf",
        "IsBlue" : false,
        "Inventory" : 234
    }
}
```

Results in `number_format_exception`:
```
GET /tester22/_search
{
   "query": {
       "query_string": {
          "query": "Product.\\*:asdf"
       }
   }
}
```

Works seamlessly:
```
GET /tester22/_search
{
 "query": {
        "multi_match": {
            "query":       "asdf",
            "type":        "cross_fields", 
            "operator":    "and",
            "fields":      [ "Product.*" ]
        }
    }
}

```

**Comment by jimczi** [comment]
Good catch, it seems that nested fields expanded by a wildcard does not respect the `lenient` parameter of the query.
By default `lenient` is false for the `match` and `query_string` query so in theory all your example should throw an exception.
I can replicate the problem on 2.x.

**Comment by alexshadow007** [comment]
@jimczi Lenient parameter is ignored in `multi_match` query only for `cross_fields` type ([code](https://github.com/elastic/elasticsearch/blob/4bce7271659889d839388d7df5c61a6d2a5c3c7a/core/src/main/java/org/elasticsearch/index/search/MultiMatchQuery.java#L245)).
Is this desirable behavior? There is [test case](https://github.com/elastic/elasticsearch/blob/cdd7c1e6c26474721a1513c83ab3ca6473e9f9ef/core/src/test/java/org/elasticsearch/index/search/MultiMatchQueryTests.java#L133) for this behavior.

**Comment by jimczi** [comment]
@alexshadow007 thanks for looking, `lenient` should not be ignored for `cross_fields`, this is a bug. 
This issue is marked with `adoptme` so feel free to open a PR for it.
