### ISSUE TITLE
Add target_field parameter to gsub Processor

### ISSUE THREAD

**Issue by loekvangool** [elastic/elasticsearch#23228]
A [gsub](https://www.elastic.co/guide/en/elasticsearch/reference/master/gsub-processor.html) Processor can replace a value in situ, but currently can't write this to another field. If it could, Ingest Node could be used for use cases where values need to be mapped, while keeping the architecture simple (Filebeat -> Elasticsearch).

**Comment by talevy** [comment]
Closed by #24133
