### ISSUE TITLE
install elasticsearch error 

### ISSUE THREAD

**Issue by kevensuu** [elastic/elasticsearch#23224]
install es error:
<pre>
[elsearch@iZwz99k8xfd8rnadsjeyxfZ elasticsearch-5.2.1]$ ./bin/elasticsearch
Error: could not find or load main class org.elasticsearch.bootstrap.Elasticsearch
</pre>

<pre>
[elsearch@iZwz99k8xfd8rnadsjeyxfZ elasticsearch-5.2.1]$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
</pre>

what could I do?

**Comment by tvernum** [comment]
These sorts of issues can be handled more effectively at https://discuss.elastic.co/c/elasticsearch

Please ask your question there - you will need to provide more information about how you installed elasticsearch (zip/rpm/deb/etc) and what OS you are running.
