### ISSUE TITLE
actions name 

### ISSUE THREAD

**Issue by danielmotaleite** [elastic/elasticsearch#23220]
Hi, i notice a minor name problem in elasticsearch actions:

indices:admin/mapping/put
indices:admin/mappings/fields/get
indices:admin/mappings/get

Notice that the first is singular and the other plural. the singular is here:

https://github.com/elastic/elasticsearch/blob/44ac5d057a8ceb6940c26275d9963bccb9f5065a/core/src/main/java/org/elasticsearch/action/admin/indices/mapping/put/PutMappingAction.java#L28

Maybe this should be all mappings, to follow the same logic and avoid future miss types and bugs.

Of course, this is a minor issue and if you disagree, feel free to close this.

**Comment by clintongormley** [comment]
Hi @danielmotaleite 

Thanks for reporting.  I think this is correct - you can only PUT one mapping, but you can retrieve multiple mappings.  That said, the GET mapping API uses the singular.  Do we throw a reasonable exception if the wrong action is specified?

**Comment by javanna** [comment]
The action names are used internally on the transport layer. Users don't see nor specify these. I don't think this could lead to bugs or typos, as we have constants for these too.

**Comment by clintongormley** [comment]
thanks @javanna - closing
