### ISSUE TITLE
RestClient should use system properties for SSL

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#23231]
The RestClient uses the Apache HttpAsyncClient internally, which does not obey the JVM system defaults for SSL but rather configures its own defaults as [documented](https://hc.apache.org/httpcomponents-asyncclient-dev/httpasyncclient/apidocs/org/apache/http/impl/nio/client/HttpAsyncClientBuilder.html) in the builder's javadocs. This has an effect on reindex as it uses the RestClient internally and cannot be easily configured to trust different certificates by using the JVM's default system properties.

I think the RestClient should default to use system properties and in turn this would also enable reindex to be configured using the JVM defaults.

**Comment by Jingw98** [comment]
I will try to fix this if it's OK :)

**Comment by jkelastic** [comment]
@ppf2  thanks :D
