### ISSUE TITLE
Provide the ability to supply detect_language as a setting via the ingest-attachment pipeline API

### ISSUE THREAD

**Issue by vikasmestry** [elastic/elasticsearch#23246]
**Describe the feature**: Provide the ability to supply detect_language as a setting via the ingest-attachment pipeline API

Currently the ingest-attachment processor pipeline supports the following options

field, target_field, indexed_chars, properties, ignore_missing.

Please include the following parameter in the options:

detect_language

**Comment by dadoonet** [comment]
No it can only be supported as an ingest attachment pipeline setting.

Can you update the title and description please?

**Comment by talevy** [comment]
Closing in favor of https://github.com/elastic/elasticsearch/issues/29094

**Comment by dadoonet** [comment]
#29094 is not exactly the same thing. I mean that Tika has this feature that can be exposed here directly.

For example here is how Im' doing that in FSCrawler: https://github.com/dadoonet/fscrawler/blob/master/tika/src/main/java/fr/pilato/elasticsearch/crawler/fs/tika/TikaDocParser.java#L136-L148

We can do both IMO.

**Comment by talevy** [comment]
sorry, I was not clear. @martijnvg and myself discussed this offline and came to the conclusion that this should just be handled in a separate processor.

If you feel strongly that this should work within Tika, then that is fair. Please re-open if you feel that way

**Comment by talevy** [comment]
right, I am not committed to any specific library yet. I don't know if spinscale/elasticsearch-ingest-langdetect is using the best or worst library out there. Whichever is used, a new processor sounds like a good idea for this
