### ISSUE TITLE
Removal of the allocate_replica allocation command

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#23244]
There are several possible allocation commands that can be issued as part of a `/_cluster/reroute` request.  One of these commands is to allocate a replica shard with the command `allocate_replica`.    This issue is to propose and discuss removal of the `allocate_replica` command.  If a replica cannot be allocated in the cluster, it means either shard allocation rules have been setup to prevent its allocation, or there aren't enough nodes to hold the primary and all replica shard copies.  In the case of the former, the solution is to fix the allocation settings to allow the replica to be allocated.  In the case of the latter, startup more nodes.  

Its not clear what utility the `allocate_replica` command provides and in the worst case, it masks a more serious issue with cluster settings that is preventing the master node from allocating the replica shard.

Relates #18819

**Comment by ywelsch** [comment]
I can think about two purposes at the moment:
- allocate a replica shard when automatic shard allocation is disabled (`cluster.routing.allocation.enable`, ...).
- force-fully allocate a replica shard when shard allocation is throttled.

These are also the only two cases where this command will succeed, all other scenarios will be rejected.

**Comment by abeyad** [comment]
> allocate a replica shard when automatic shard allocation is disabled (cluster.routing.allocation.enable, ...).

Shouldn't the user just re-enable shard allocation as opposed to executing this command?

> force-fully allocate a replica shard when shard allocation is throttled.

Shouldn't the number of concurrent recoveries be increased in such a situation?

I feel changing the actual relevant settings is the better way to go about making sure replicas are allocated, rather than offering this one off command.  WDYT?

**Comment by ywelsch** [comment]
With #18819 being closed, we can close this one as well.
