### ISSUE TITLE
Java Search API - 'setExplain' to false on SearchRequestBuilder has no effect

### ISSUE THREAD

**Issue by paul-maker** [elastic/elasticsearch#23249]
**Elasticsearch version**: 5.0

**JVM version**: 1.8

**OS version**: Windows

**Description of the problem including expected versus actual behavior**: setExplain on the class SearchRequestBuilder seems to have no effect when set to false. Inspecting the JSON returned from a subsequent search shows that the explanation is still included for each hit.

**Comment by cbuescher** [comment]
How do you use SearchRequestBuilder? Can you share a code examples and also describe what it is exactly that you are seeing that you think is wrong on the search hits? I just checked some parts of the code and everything seems to be in order there, so I'm wondering what you are seeing.

**Comment by paul-maker** [comment]
SearchResponse response = transportClient.prepareSearch("idx_jlr_elastic_kb")
		        .setTypes("childfile")
		        .setSearchType(SearchType.DFS_QUERY_THEN_FETCH)
		        .setExplain(false)
		        .setQuery(queryBuilder)
		        .setFrom(0).setSize(60).setExplain(true)
		        .execute()
		        .actionGet();
		
		return response.toString();

Inspecting the toString shows that the explanation is included

**Comment by dadoonet** [comment]
But you wrote `.setExplain(true)`

**Comment by paul-maker** [comment]
ops, that is an epic fail, i will close this
