### ISSUE TITLE
Elasticsearch data type ip does not recognize valid IPv6 formats

### ISSUE THREAD

**Issue by vbohata** [elastic/elasticsearch#23263]
Elasticsearch ip data type does not support following IPv6 addresses:

:: - this is short format of 0000:0000:0000:0000:0000:0000:0000:0000, frequently precent in our logs

percent sign at the end of the address like fe80::71a3:2b00:ddd3:753f%16. Number of string after the percent sign is often part of the ip address identifying the inteface. This part should be automatically ignored by elasticsearch while storing this ip address

Problematic Elasticsearch version: 5.2

**Comment by jasontedor** [comment]
Duplicates #22400

**Comment by vbohata** [comment]
This is not duplicate item. In this issue, there are 2 problems (:: and percentage format). In percentage format I think ES should ignore that part (not accept it as mentioned in #22400)

**Comment by clintongormley** [comment]
@vbohata `::` works just fine:

```
PUT t
{
  "mappings": {
    "t": {
      "properties": {
        "ip": {
          "type": "ip"
        }
      }
    }
  }
}

PUT t/t/1?refresh
{
  "ip": "::"
}

GET t/t/_search
{
  "query": {
    "match": {
      "ip": "::"
    }
  }
}
```

**Comment by vbohata** [comment]
Sorry, :: really works without problem. Few days ago I had error in logstash from elasticsearch about parsing ::, but it looks it was actually caused by another field and ip field was just a victim.
