### ISSUE TITLE
Limit the timeout of scroll requests

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#23268]
Individual scrolls requests should be consumed quickly in order not to hold references on to old segments for too long. Right now we accept arbitrary timeouts but we should be more defensive and put a limit. 5 minutes should be plenty for everyone?

**Comment by nik9000** [comment]
Reindex's throttling relies on setting the timeout higher enough to wait
out the throttle period. Five minutes is probably fine but if we are going
to do this we'll have to touch reindex too to make the error message it
sends more sensible or to change how it implements throttling.

**Comment by maddin2016** [comment]
Hi @jpountz, what about this
```java
public Scroll(StreamInput in) throws IOException {
        this.keepAlive = new TimeValue(in);
        if(keepAlive.seconds() > 300)
            throw new IllegalArgumentException("Keep alive time should be less than 5 minutes");
    }

    /**
     * Constructs a new scroll of the provided keep alive.
     */
    public Scroll(TimeValue keepAlive) {
        if(keepAlive.seconds() > 300)
            throw new IllegalArgumentException("Keep alive time should be less than 5 minutes");
        this.keepAlive = Objects.requireNonNull(keepAlive, "keepAlive must not be null");
    }
```

**Comment by i-am-Nathan** [comment]
Hi can I give this one a shot if it is still there?

**Comment by discoverytrips** [comment]
If the amount of data is too big, try to use Spark + ES.
but if it uses Spark, input-output ratio, may not be too high.

**Comment by pratiksanglikar** [comment]
Is anyone working on this issue?
If not, can I pick up this issue as my first contribution?

**Comment by abeyad** [comment]
@pratiksanglikar I don't believe anyone is currently working on it, you are welcome to pick this up.  Thank you!

**Comment by pratiksanglikar** [comment]
@abeyad Thank you!
I'll pick up this issue.
