### ISSUE TITLE
Add the examples to changes required in /etc/security/limits.conf for production use

### ISSUE THREAD

**Issue by sarwarbhuiyan** [elastic/elasticsearch#23274]
**Describe the feature**:
Enhance the /etc/security/limits.conf example in https://github.com/elastic/elasticsearch/edit/5.2/docs/reference/setup/sysconfig/configuring.asciidoc and add in the configurations for "nproc", "memlock", "as" and any others which should be set that Bootstrap warns about.

**Comment by clintongormley** [comment]
@sarwarbhuiyan fancy sending a PR?
