### ISSUE TITLE
IpRangeAggregatorTests#testRanges fails

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#23272]
The test `IpRangeAggregatorTests#testRanges` fails with seed 4AC319F8A6B0329B.

**Comment by jasontedor** [comment]
Would you take a look @jimczi?

**Comment by jimczi** [comment]
Thanks @jasontedor and sorry for the noise

**Comment by jasontedor** [comment]
Thanks @jimczi.
