### ISSUE TITLE
Optimize heavy filtered aliases

### ISSUE THREAD

**Issue by yannisf** [elastic/elasticsearch#23281]
I created a filtered alias that had as filter a terms query with thousands of rows. The json itself was about 40MB. The performance when searching through this alias is detrimental.

My observations are that:
- The filter is cached and a bitset is created for this filter
- Search performance takes a lot of time because elasticsearch takes a lot of time to process the filter and not to query the index itself (that is, once the filter is cached)
- If the filtered alias is somehow hardwired with the respective cached bitset performance would be very good.

I have also opened a question in the discussion forum: https://discuss.elastic.co/t/searching-through-an-alias-with-filter-is-very-slow-in-elasticsearch/74503

**Comment by clintongormley** [comment]
@yannisf what version of Elasticsearch are you using?

There is a PR which improved the performance of these queries that went into 5.1.1 https://github.com/elastic/elasticsearch/pull/21776

Also, if you could presort your terms, you'd get an extra boost.

**Comment by yannisf** [comment]
I am using 2.4, but tested this provisionally with 5.2 and the issue is still there. 
My terms are uuid4. Presorting them using what sort order is the best?

**Comment by jpountz** [comment]
Is there a way that you could add additional metadata to your documents and run `term` queries instead of running very large `terms` filters on uuids?

**Comment by yannisf** [comment]
We could, but the level of indirection the aliases provide, simplified a lot our design. You see, these metadata are quite dynamic, so the solution to just recreate the aliases (once per day) is much simpler than having to update 2Bi of documents.

Of course now that we run on this roadblock we are all open to suggestions. @jpountz I really appreciate that you are trying to help.

**Comment by yannisf** [comment]
Hi @clintongormley , @jpountz,

I would very much appreciate some feedback on the issue, even if it is something "There is nothing you can do other than redesigning your index".  From my side, I would like to see as a feature: When searching against a filtered alias.  use the cached bitset (if there is one cached already), instead of having to reevaluate the alias filters all the time.

Hopefully, the feature request make sense. Thank you for your support.

**Comment by jpountz** [comment]
The answer is likely that the index should be redesigned indeed. Large terms filters are quite an anti pattern to efficiently leverage Elasticsearch. In case you can get hot threads while you are running some queries in a loop, I could get a look at the hot threads to check what the bottleneck is. I want to keep expectations low, but it might something we can improve. If you can check against 5.x rather than 2.x, that would be more helpful.

**Comment by javanna** [comment]
No further feedback. Closing.
