### ISSUE TITLE
Explore possibility of smaller size for terms aggs in incremental reduce

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#23285]
This is a spinn-off from #23253 where we introduced the initial infrastructure  to reduce search requests incrementally rather than once all responses are received. For terms aggs we need to maintain all buckets until we received all responses to maintain the same results. It might be a good tradeoff to loose some additional precision if # of shards is large in order to free memory sooner.

**Comment by colings86** [comment]
One tricky aspect to this is that because the order of shards responding is not guaranteed consecutive calls of the same terms agg request could return different error values.

**Comment by colings86** [comment]
We discussed this and decided that we don't want to do it given that we would have to give up the determinism of the error which would make it very difficult to test and to reproduce users problems.
