### ISSUE TITLE
Reg aggregation using java client

### ISSUE THREAD

**Issue by vivred** [elastic/elasticsearch#23301]
Hi,

Earlier in elasticsearch 2.4 version, we used to fetch aggregation json string from DB (agg string used to get added dynamically) and used to set aggregations using setAggregations(bytes[] string) method in java transport client. But now when we updated to 5.0 we found that setAggregations is no longer supported.

Could anyone please help me how to build aggregation from json String. As those aggregation are to be picked up from DB, it is not possible to manually create one using aggregationbuilder.

Regards,
Vivek

**Comment by jasontedor** [comment]
Please ask questions on the [forum](https://discuss.elastic.co). Elastic reserves GitHub for verified bug reports and feature requests.

**Comment by vivred** [comment]
I did ask this in forums, but didnt get any reply. There is also an another post on the same issue 1 month back but no reply was given by anyone. Didnt find any solution in documets also.so thought this is right place since developers would know the best.

**Comment by vivred** [comment]
https://discuss.elastic.co/t/reg-aggregations-using-java-client/75861

**Comment by vivred** [comment]
https://discuss.elastic.co/t/setaggregation-in-java-client-builder-not-available-in-5-x/68317

previous topic which no one replied

**Comment by jasontedor** [comment]
You opened the topic nineteen hours ago. There is no SLA on the forum.

**Comment by vivred** [comment]
https://discuss.elastic.co/t/setaggregation-in-java-client-builder-not-available-in-5-x/68317

this was created on dec 16. no reply at all
