### ISSUE TITLE
Reg setAggregations using java client

### ISSUE THREAD

**Issue by vivred** [elastic/elasticsearch#23302]
Hi,

Earlier in elasticsearch 2.4 version, we used to fetch aggregation json string from DB (agg string used to get added dynamically) and used to set aggregations using setAggregations(bytes[] string) method in java transport client. But now when we updated to 5.0 we found that setAggregations is no longer supported.

Could anyone please help me how to build aggregation from json String. As those aggregation are to be picked up from DB, it is not possible to manually create one using aggregationbuilder.

Reg this issue we earlier posted it in elasticsearch forums but didnt get any reply, been more than a month.
https://discuss.elastic.co/t/setaggregation-in-java-client-builder-not-available-in-5-x/68317
https://discuss.elastic.co/t/reg-aggregations-using-java-client/75861

If any developers could help us through this issue that would be great.

Regards,
Vivek

**Comment by jasontedor** [comment]
Duplicates #23301
