### ISSUE TITLE
Tests: Netty4PipeliningEnabledIT#testThatNettyHttpServerSupportsPipelining fails reproducibly

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#23322]
On current master (771fd1f4eaa700ddecf634dee04be80f0a40471f): https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/1844/console

'''
gradle :modules:transport-netty4:integTestRunner -Dtests.seed=BF593F0EC855DB4E -Dtests.class=org.elasticsearch.http.netty4.Netty4PipeliningEnabledIT -Dtests.method="testThatNettyHttpServerSupportsPipelining" -Dtests.security.manager=true -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" -Dtests.locale=ko -Dtests.timezone=Asia/Beirut
'''

**Comment by cbuescher** [comment]
Probably related: https://github.com/elastic/elasticsearch/pull/23317

**Comment by bleskes** [comment]
> Probably related: #23317

Yep. It does.
