### ISSUE TITLE
Change field data apis to use BaseCompositeReader instead of DirectoryReader

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#23338]
Because we use `DirectoryReader` we can let the lucene test framework randomily wrap the readers in our aggregation unit tests:
https://github.com/elastic/elasticsearch/pull/23305/commits/5bbfb6c5bb57c28215d29a8b5874a4517704a530#diff-ab07a3e29560885c391583295d69c3d1R101

If we would change all field data and field data cache signatures to use `BaseCompositeReader` instead of `DirectoryReader` we would be able to randomily wrap readers in these tests.

**Comment by jpountz** [comment]
I think it was done this way because directory readers guarantee that they remain open for a long time, while index reader wrappers may be short-lived, which can cause performance bugs.

**Comment by javanna** [comment]
@martijnvg is this still valid?

**Comment by martijnvg** [comment]
The problem only occurs if Lucene test framework wraps the reader with specific readers (e.g. `ParallelCompositeReader`) The reason I like to use `LuceneTestCase#wrapReader(...)` is because it randomly wraps the reader in an `AssertingDirectoryReader`, which can detect misuse of the Lucene internal apis. I think as a compromise we can instead add our own `wrapReader(...)` method that only randomly wraps the reader in an `AssertingDirectoryReader`.
