### ISSUE TITLE
Incorrect parsing of a JSON doc containing a zero-length fieldName

### ISSUE THREAD

**Issue by matAtWork** [elastic/elasticsearch#23348]
The error generated by [DocumentParser.java#L182]( https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java#L182) (`object field starting or ending with a [.] makes object resolution ambiguous: [" + fullFieldPath + "]"`) incorrectly rejects the field path "", which is not ambiguous.

This kind of document (edge-case, I know) was accepted in ES v1.x. Ideally (for me) the document would be accepted, but in any case the error description is incorrect - if "" is a special case that is considered illegal by ES (but not JSON), it should be documented as such and reported accordingly.

**Elasticsearch version**:
5.2.1

**Plugins installed**: []
x-pack

**JVM version**:
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

```
**OS version**:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. `curl -XPUT localhost:9200/test/test/1 -d '{ "": "abc" }'`

**Provide logs (if relevant)**:
Response:
```
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse"}],"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"object field starting or ending with a [.] makes object resolution ambiguous: []"}},"status":400}
```
Expected response:
```
{"_index":"test","_type":"test","_id":"1","_version":2,"result":"updated","_shards":{"total":2,"successful":1,"failed":0},"created":false}
```

**Comment by dakrone** [comment]
@matAtWork I definitely agree the message could be clearer. This was something I introduced to fix a different mapping problem in https://github.com/elastic/elasticsearch/pull/22891

I'll take a look and see if I can make the error more descriptive of the actual problem.

**Comment by matAtWork** [comment]
Thanks for the quick response. Incidentally, I got around my issue by creating a mapping with "enabled: false" for the objects containing these keys (they're a state machine - I don't want to search them), which introduces the anomaly that this can indexed in some mappings (enabled: false), but not in others

**Comment by clenk** [comment]
I also ran into this issue, but I needed to index the field and search on it so I could not use @matAtWork's workaround. A more accurate error message would have saved me time and confusion.

**Comment by grantholly** [comment]
**elasticsearch version:**
`5.4.1`

**java version:**
`
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
`
**os version:**
`
CentOS Release 7.3.1611
`

**logstash version:**
`2.4.1`

If you are using Logstash to write to Elasticsearch, you might get a message like this in the logstash log file:
`"response":{"index":{"_index":"logstash-2017.06.11","_type":"REDACTED","_id":"AVyYXGBT5FKNI6XHxtkZ","status":400,"error":{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"object field starting or ending with a [.] makes object resolution ambiguous: []"}}}},"level":"warn"}`

Here's a look at the document that Logstash is trying to get Elasticsearch to index:
`    
{"doc": {
  "hdr": {
    "timing": {
      "service_name": {
        "": 0
      }
    }
  }
} }  
`
