### ISSUE TITLE
Invalid result returned with queryString on string array field.

### ISSUE THREAD

**Issue by demoaccount2015** [elastic/elasticsearch#23341]
I have field tags:["software engineer", "IT implementation"].

I have prepared term aggregation on tags field. which return me bucket: [{software engineer: 1} , {IT professional: 1} ]

now in term aggregation filter, I am using queryString to filter "software profess" tags. Term aggregation filter doesn't filter data.

I have used position_increment_gap:100 for tagsList field in indexing. Still, I am getting invalid result.

**Comment by dakrone** [comment]
Hi,
We reserve Github issues for feature requests and bug reports. If you are having problems please use https://discuss.elastic.co instead!
