### ISSUE TITLE
String query "*"  returns all documents when allow_leading_wildcard and analyze_wildcard are set to false

### ISSUE THREAD

**Issue by trik-1** [elastic/elasticsearch#23356]
Elasticsearch version: `5.2.0`
```
  "version" : {
    "number" : "5.2.0",
    "build_hash" : "24e05b9",
    "build_date" : "2017-01-24T19:52:35.800Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.0"
  }
```

JVM version: 1.8

OS version: Alpine Linux

When running the below query all documents are matched using the `*` query:

```
{
  "size" : 5,
  "query" : {
    "query_string" : {
      "query" : "*",
      "allow_leading_wildcard": false,
      "analyze_wildcard": false
    }
  }
}
```

Should the `allow_leading_wildcard` and `analyze_wildcard` settings cause this to fail ?

For example conversely 

```
{
  "size" : 5,
  "query" : {
    "query_string" : {
      "query" : "content:*",
      "allow_leading_wildcard": false,
      "analyze_wildcard": false
    }
  }
}
```

results in a parse exception with the reason "parse_exception: '*' or '?' not allowed as first character in WildcardQuery"

**Comment by dakrone** [comment]
> Should the allow_leading_wildcard and analyze_wildcard settings cause this to fail ?

The `*` in this query is being parsed as a variant of the special `*:*` query, which is a match all query. You can see from explain output or validating the query with a rewrite what it's being rewritten to. In the converse example, since it has an actual field, it throws an exception since it doesn't allow leading wildcards.

**Comment by clintongormley** [comment]
I wonder if we shouldn't rewrite `field:*` to an exists query instead?

**Comment by jimczi** [comment]
> I wonder if we shouldn't rewrite field:* to an exists query instead?

That's what the code is trying to do but it's working only when `default_field` or `fields` contain the field `content`.

This query for instance:
`````
GET _validate/query?explain&rewrite
{
   "query": {
      "query_string": {
         "query": "foo:*",
         "default_field": "foo",
         "allow_leading_wildcard": false,
         "analyze_wildcard": false
      }
   }
}
`````
returns:

`````
{
   "valid": true,
   "_shards": {
      "total": 1,
      "successful": 1,
      "failed": 0
   },
   "explanations": [
      {
         "index": "t",
         "valid": true,
         "explanation": "ConstantScore(_field_names:foo)"
      }
   ]
}
`````

So basically this is a bug, we should not create query like `field:*` but rather rely on the exists query. If we do that then `allow_leading_wildcard` can be ignored for this kind of query.

**Comment by dakrone** [comment]
@jimczi I think this is resolved by your PR, is that correct?

**Comment by jimczi** [comment]
Right, this issue was not close automatically because I used "relates" instead of "closes" in the commit message.
Thanks @dakrone
