### ISSUE TITLE
parsing_exception: no [query] registered for [filtered]

### ISSUE THREAD

**Issue by avishake** [elastic/elasticsearch#23353]
Hi,
I am trying to find all the results which is not contain a field 'open_location'. I am using the below code. But it gives me the error for print result. The error is,
  parsing_exception: no [query] registered for [filtered]

Please help me...

 `$index_name=$db_name.'_temp_traking';
		$para= [
			'index' => $index_name,
			'type' => $index_name,
			'body' => [
				'query' => [
					'filtered' => [
						'filter' => [
							'bool' => [
								'must_not' => [
									'missing' => [
										'field' => 'open_location'
									]
								]
							]
						]
					]
				]
			]
		];
		$response = $client->search($para);`

**Comment by jpountz** [comment]
You are using old syntax that was deprecated in 2.0 and removed in 5.0. You should run the following:

```
$index_name=$db_name.'_temp_traking';
$para= [ 'index' => $index_name, 'type' => $index_name, 'body' => [ 'query' => [ 'bool' => [ 'filter' => [ 'exists' => [ 'field' => 'open_location' ] ] ] ] ] ];
$response = $client->search($para);
```

**Comment by avishake** [comment]
I want to find those which documents haven't 'open_location' field. The above code is checking that if 'open_location' exists then search. I need the opposite.

**Comment by jpountz** [comment]
For the record, this is NOT what your original query was trying to do. Anyway, here is a new query that should do the job:

```
$index_name=$db_name.'_temp_traking';
$para= [ 'index' => $index_name, 'type' => $index_name, 'body' => [ 'query' => [ 'bool' => [ 'must_not' => [ 'exists' => [ 'field' => 'open_location' ] ] ] ] ] ];
$response = $client->search($para);
```
