### ISSUE TITLE
how can we get Distinct data in ElasticSearch using query?

### ISSUE THREAD

**Issue by karan69** [elastic/elasticsearch#23367]
**Elasticsearch version**:2.1.0

**Plugins installed**: []no

**JVM version**:1.8

**OS version**:8.1

**Description of the problem including expected versus actual behavior**:I want to get DISTINCT data from elasticsearch ,i m using aggregation but it giives me only Distinct Counts .

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
