### ISSUE TITLE
Expose duplicate removal in the completion suggester

### ISSUE THREAD

**Issue by mikemccand** [elastic/elasticsearch#23364]
Lucene 6.5.0 adds an option to the NRT document suggester to efficiently remove duplicates, and it's included in the last snapshot upgrade (https://github.com/elastic/elasticsearch/pull/23362).

This should fix https://github.com/elastic/elasticsearch/issues/22912, but I won't have time to work on it.

**Comment by trompx** [comment]
Hello @mikemccand,

Will this option be available for the context suggester too?

I index document question with a category property so I use the context suggester to suggest question when new documents are created and filtered by category so the completion suggester would not be enough for my usecase.
