### ISSUE TITLE
index.mapper.dynamic ignored entirely and mapping types ignored when using templates

### ISSUE THREAD

**Issue by Cidan** [elastic/elasticsearch#23374]
**Elasticsearch version**: 5.2.1

**Plugins installed**: [discovery-gce]

**JVM version**: Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

**OS version**: Ubuntu 14.04.5 LTS

**Description of the problem including expected versus actual behavior**:

When creating an index with `index.mapper.dynamic`, the setting is set, but completely ignored -- dynamic mapping remains enabled.

Further, when using a template, types are ignored altogether even though the mapping is applied to the index.

**Steps to reproduce**:
 1. Create a fresh cluster.
 2. Create an index with the following mapping:
`
{
  "settings": {
    "index": {
      "number_of_shards": 30,
      "number_of_replicas" : 2,
      "mapper": {
        "dynamic": false
      },
      "mapping": {
        "ignore_malformed": true
      }
    }
  },
  "mappings" : {
    "test-type" : {
      "properties" : {
        "a_bool" : {
          "type" : "boolean",
          "null_value" : true
        },
        "a_keyword" : {
          "type" : "keyword",
          "null_value" : "undefined"
        },
        "a_long" : {
          "type" : "long",
          "null_value" : 0
        },
        "a_float" : {
          "type" : "float",
          "null_value" : 0.0
        },
        "text" : {
          "type" : "text"
        }
      }
    }
  }
}
`

 3. Post the following document to `test-index/test-type`

`
{
  "not_in_mapping": "this should not index"
}
`

 4. Check `test-index/test-type/_mapping?pretty` and you will now see this field that was not in the mapping.

 5. Use the file in step 2 as a template by adding `"template": "*"` to the top level and posting the template

 6. Create a new index without settings and let the template apply it self.

 7. Post any document that has a mismatched mapping and observe that all mappings are completely ignored -- the document will index successfully.

**Comment by PnPie** [comment]
It seems that `index.mapper.dynamic` setting is only taken into account along with the creation of index and cannot be effectively modified.

I created an index with `"index.mapper.dynamic":false`, then modified it to `true`, I can see in the settings of index with `"mapper": {"dynamic": "true"}` but I still can't put any data because of `type_missing_exception`.

In reverse, I created an index by default with dynamic mapper and I can always put data into it even if I changed `index.mapper.dynamic` to `false`.

**Comment by Cidan** [comment]
In my example above, `index.mapper.dynamic` is always ignored and uses the default value of `true`, even when creating an index with `false`. What version are you using?

**Comment by PnPie** [comment]
I used 5.0.2
```
"version" : {
    "number" : "5.0.2",
    "build_hash" : "f6b4951",
    "build_date" : "2016-11-24T10:07:18.101Z",
    "build_snapshot" : false,
    "lucene_version" : "6.2.1"
  }
```

**Comment by Cidan** [comment]
Interesting. This seems to be a regression from > 5.0.2.

**Comment by ywelsch** [comment]
@Cidan The setting `index.mapper.dynamic` disables auto-creation of new types. It does not prevent the mapping of an already-defined type from being updated, see https://www.elastic.co/guide/en/elasticsearch/reference/5.2/dynamic-mapping.html#_disabling_automatic_type_creation
What you want to configure is the `dynamic` property on the type (see https://www.elastic.co/guide/en/elasticsearch/reference/5.2/dynamic.html). You can even apply this property to all types in the mapping by specifying it on the default mapping, for example:
```
"mappings" : {
    "_default_" : {
      "dynamic": "strict"
    },
   ...
```

**Comment by Cidan** [comment]
Thank you, I'll try this out.
