### ISSUE TITLE
Document comments in Painless

### ISSUE THREAD

**Issue by ycombinator** [elastic/elasticsearch#23372]
Painless apparently supports `// ...` and `/* ... */` style comments. This is useful when writing out long, complex scripts.

It would be great to have this feature documented in https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-painless.html and/or https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-painless-syntax.html.

Thanks!

**Comment by nik9000** [comment]
@jdconrad is this a thing you are covering in your docs work? Should I assign this to you so you can close that when it is in?

**Comment by jdconrad** [comment]
@nik9000 I assigned to myself as this will be included in my updated documentation.

**Comment by nik9000** [comment]
> @nik9000 I assigned to myself as this will be included in my updated documentation.

Thanks!

**Comment by drawsmcgraw** [comment]
Hi @jdconrad! I've submitted https://github.com/elastic/elasticsearch/pull/24550 to help take this off your list. Hopefully I inferred the documentation style correctly. I'm happy to make any requested changes.

**Comment by jdconrad** [comment]
This is in the existing documentation now.  https://www.elastic.co/guide/en/elasticsearch/painless/current/painless-specification.html
