### ISSUE TITLE
index.cache.field.type

### ISSUE THREAD

**Issue by blair319** [elastic/elasticsearch#23370]
**Elasticsearch version**: 5.2.0

**Plugins installed**: []

**JVM version**:1.8.0_121

**OS version**:redhat

**Description of the problem including expected versus actual behavior**:
when I 

curl -XPUT http://XXXXX:9200/logstash-XXX-2017.02.25/_settings -d '{"index.cache.field.type":"soft"}'

then
{
    "error": {
        "root_cause": [{
            "type": "illegal_argument_exception",
            "reason": "unknown setting [index.cache.field.type] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
        }],
        "type": "illegal_argument_exception",
        "reason": "unknown setting [index.cache.field.type] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
    },
    "status": 400
}

the "index.cache.field.type":"soft" remove?

**Comment by jasontedor** [comment]
The setting `index.cache.field.type` has not been a valid setting since 0.20.6! You must be looking at a very old reference to see any mention of this setting. If you have additional questions, please ask them on the [forum](https://discuss.elastic.co).
