### ISSUE TITLE
histogram on an array

### ISSUE THREAD

**Issue by sundarv85** [elastic/elasticsearch#23384]
**Describe the feature**:

This is a feature request.

When we have an array of long/int, then a percentile or avg on such an array works correctly by considering the count of the array elements. But when histogram is requested, the current implementation of histogram works based on doc count. 

```
DELETE histperc
PUT histperc
PUT histperc/_mapping/t
{
  "properties": {
    "name": {
      "type": "string"
    },
    "avg": {
      "type": "long"
    },
    "entries": {
      "type": "long"
    },
    "count": {
      "type": "long"
    }
  }
}

POST /histperc/t/_bulk
{ "index": { "_id": "e1" }}
{ "name": "GET /login", "avg": 2, "entries": [2, 2, 3, 3, 3], "count": 5}
{ "index": { "_id": "e2" }}
{ "name": "GET /login", "avg": 1, "entries": [1, 2, 1], "count": 3}
{ "index": { "_id": "e3" }}
{ "name": "GET /login", "avg": 7, "entries": [7], "count": 1}
{ "index": { "_id": "e4" }}
{ "name": "GET /login", "avg": 3, "entries": [3], "count": 1}

# works correctly
GET /histperc/t/_search
{
  "aggs": {
    "perc": {
      "percentiles": {
        "field": "entries"
      }
    }
  }
}

# works correctly
GET /histperc/t/_search?size=0
{
  "aggs": {
    "average": {
      "avg": {
        "field": "entries"
      }
    }
  }
}

# works based on doc count. Interested in getting it to work with the values of the array instead
GET /histperc/t/_search
{
  "aggs": {
    "hist": {
      "histogram": {
        "field": "entries",
        "interval": 1
      }
    }
  }
}
```

The reason to request such a support is, in time-based data, most of the times the only change is in the value in this array and the rest of the elements are the same. Hence, the cost of duplicating the documents is higher for this one feature of histogram, esp because avg and percentile already work correctly on this array.

**Comment by markharwood** [comment]
The logic for leaf and bucket aggregations is by necessity, different.

"Bucket" aggregations like `histogram` work by assigning docs to buckets and maintaining a doc count for each bucket.

Given these two docs:

    {  "myvalue": 1 }
    {  "myvalue": [1, 2, 2, 4] }

.. the histogram agg correctly reports the following doc counts:

     [
        { "key": 1,  "doc_count": 2  },
        { "key": 2, "doc_count": 1 },
        { "key": 3, "doc_count": 0 },
        { "key": 4, "doc_count": 1}
     ]

"Leaf" aggregations like `avg` compute results from _value_ instances - a doc may contain none, one or many values and these are added up and divided by the total number of value instances.

I'm unclear as to what results you are expecting or what new query syntax would be required to produce them so can you share some examples? Thanks

cc @elastic/es-search-aggs

**Comment by colings86** [comment]
No further feedback. Please comment if you have more details on the questions asked and we can look at re-opening this issue

**Comment by sundarv85** [comment]
@markharwood Sorry about the delay in getting back.

@markharwood From your example, 

> 
> ```
> {  "myvalue": 1 }
> {  "myvalue": [1, 2, 2, 4] }
> ```
> .. the histogram agg correctly reports the following doc counts:
> 
> ```
>  [
>     { "key": 1,  "doc_count": 2  },
>     { "key": 2, "doc_count": 1 },
>     { "key": 3, "doc_count": 0 },
>     { "key": 4, "doc_count": 1}
>  ]
> ```
> 

Here, we would prefer to get the count for `key:2` as `2` instead of `1`. As you see,` [1,2,2,4] ` even though it is only one document, `1, 2, 4` each get one doc count. However, the duplicate `2` is not given another additional count, rather only one.

**Comment by sundarv85** [comment]
@colings86 could this issue be looked at again? 

Imagine a time series where we store one document per minute, multiple occurrences within that minute could easily be captured in an array. Since this histogram is not working on arrays, we have to split the document into separate entires just because of this issue.

**Comment by colings86** [comment]
@sundarv85 We discussed this internally and I've opened https://github.com/elastic/elasticsearch/issues/30268 which suggests adding a value_count to the buckets which would return the number of values that fell into that bucket. I'm going to keep this issue closed in favour of that one which generalises to all bucket aggregations
