### ISSUE TITLE
Partial update does not work with nested objects

### ISSUE THREAD

**Issue by dilipsridhar** [elastic/elasticsearch#23398]
**Elasticsearch version**: 5.2.0

**Plugins installed**: []

**JVM version**: 1.8.0_01

**OS version**: Ubuntu 16.04.01 LTS

**Description of the problem including expected versus actual behavior**:
In a nested document adding a child at the nested level replaces the existing children with this new child. Does not insert.

Create a blog object as follows:
PUT /test/blog_index/1
{
	"settings": {
		"index": {
		"number_of_shards": 1,
		"number_of_replicas": 1
		}
	},
	"mappings": {
		"blog": {
			"properties": {
				"title": { "type": "string" },
				"content": { "type": "string" },
				"categories": { 
					"type": "nested", 
					"properties": {
						"category": { "type": "string" }
					}
				},
				"comments": {
					"type": "nested", 
					"properties": {
						"comment": { "type": "string" },
						"votes": { "type": "short" }
					}
				}
			}
		}
	}
}

Insert Data:
PUT /test/blog/BL0000072
{
  "blog": {
    "title": "Self driving car making significant progress",
		"content": "Self driving car making significant progress...",
		"categories": [
		    {
		      "category": "TECH"
		    }
		],
		"comments": [
		  {
		    "comment": "This is cool",
		    "votes": 2
		  },
		  {
		    "comment": "is this true?",
		    "votes": 1
		  }
		  ]
  }
}

Updating the field 'votes' in the document replaces all the other comments:

POST /test/blog/BL0000072/_update
{
  "script": {
    "lang": "painless",
    "inline": "ctx._source.blog.comments = params.currentComment; ctx._source.blog.comments = params.comments",
    "params": {
      "currentComment": [
        {
          "searchText": "This is cool",
          "votes": 0
        }
      ],
      "comments": [
        {
          "comment": "This is uber cool",
          "votes": 1
        }
      ]
    }
  },
    "upsert" : {
        "counter" : 1
    }
}

**Steps to reproduce**:
 1. Create the index
 2. Insert data
 3. Update a comment: On update the 2 comments are replaced with a single comment.

**Provide logs (if relevant)**:

**Comment by cbuescher** [comment]
I think there is something wrong with your script. You are assigning `ctx._source.blog.comments` twice, I don't think thats intended. Also, if you want to just update one comment, use something like `ctx._source.blog.comments[i]`. In general, if you are unsure about any of this in the future, consider opening an issue in our [Discourse forum](https://discuss.elastic.co) first because Elastic reserves GitHub for bug reports and feature requests.

**Comment by dilipsridhar** [comment]
`ctx._source.blog.comment` should appear only once in POST. That is correct. Will check what you say. Will post in the forums before creating an Issue henceforth. Thanks.

**Comment by Ammie1** [comment]
Solved the nested update on below YouTube video
https://www.youtube.com/watch?v=A3aldCB6i0A
