### ISSUE TITLE
Bootstrap check utility for pre-5.x upgrade

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#23394]
Bootstrap checks add many helpful safety checks to ES at boot time.  One problem they present is that we don't have a clear specification in advance of upgrading to 5.x which bootstrap checks are going to happen and what will cause a cluster to fail to start.  Things that were allowed in 2.x are no longer permitted, and the process of working through each bootstrap issue and restarting to find the next issue.  It would help users plan for upgrades if we had a utility that would run the same set of bootstrap checks that 5.x uses on startup in order to verify whether a node is compliant.

**Comment by jpountz** [comment]
It is not clear to me what such a utility would bring compared to starting up a 5.x node with the target configuration?

**Comment by jasontedor** [comment]
> One problem they present is that we don't have a clear specification in advance of upgrading to 5.x which bootstrap checks are going to happen and what will cause a cluster to fail to start.

Every bootstrap check is [documented](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/bootstrap-checks.html).

> Things that were allowed in 2.x are no longer permitted, and the process of working through each bootstrap issue and restarting to find the next issue.

We print every failing bootstrap check on startup, it is not necessary to go through them one-by-one.

> It would help users plan for upgrades if we had a utility that would run the same set of bootstrap checks that 5.x uses on startup in order to verify whether a node is compliant.

This can be done by starting the node (for example, in a QA environment) in the expected configuration.

**Comment by seang-es** [comment]
The ask is to be able to run the same checks while they still have 2.x running in order to verify the configuration before upgrading.  The workaround would be to start a new 5.x node on the boxes that's not connected to the existing cluster.  This may be worth including in our documentation.
