### ISSUE TITLE
Allow setting of index.uuid upon Index Creation

### ISSUE THREAD

**Issue by bevans88** [elastic/elasticsearch#23413]
I'm looking into exposing the index.uuid setting so that it can be configured upon creating an index to allow it to be deterministic rather than a base64 encoded UUID.

I understand that this would mean that the user would need to to guarantee index uuid uniqueness across clusters, but I'd assume that if someone is setting it then they would be aware of this contract. 

The current use case for this involves per-index encryption, so the ability to have deterministic paths to the index is crucial.

Thoughts?

I've just found https://github.com/elastic/elasticsearch/pull/16217 which seems to have been the start of the change to moving towards using the uuid. 

Cheers!

**Comment by ywelsch** [comment]
You can solve this using [allocation filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-allocation-filtering.html):
- Have some nodes encrypt their drives and mark those nodes with an attribute "encrypted"
- Use allocation filtering to specify which indices should be on the encrypted nodes.

Alternatively, you can use `index.data_path` (but set `path.shared_data` beforehand as well), see https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-shadow-replicas.html
Note that this might not be supported in future versions of ES anymore.

**Comment by bevans88** [comment]
The allocation filtering would rely on all indexes that are allocated to a node being encrypted with the same key; what I need is the ability to encrypt individual indexes with their own key. 

While I could in essence have a node per index/set of indices and only store those on the node so that multi-tenant encryption works it would seem rather heavy.

**Comment by bleskes** [comment]
> I need is the ability to encrypt individual indexes with their own key

That's a valid use case for`index.data_path`. While we are likely to remove the shadow replicas feature, custom data paths are likely to stay for exactly this reason.

**Comment by jasontedor** [comment]
> but set `path.shared_data` beforehand as well

I think despite the planned removal of shadow replicas, we need to continue to enable this particular feature, probably changing the name of this setting if it needs to remain too.

**Comment by jasontedor** [comment]
When an index is deleted, an index tombstone with the index UUID is stored in the cluster state. This would not play well with the ability to arbitrarily set the index UUID.

**Comment by bevans88** [comment]
Thanks for the replies, I can work with the index.data_path and path.shared_data, was just concerned that they were going to be removed hence wanting to know if setting the UUID was possible.
