### ISSUE TITLE
Dynamic template

### ISSUE THREAD

**Issue by shubhamitc** [elastic/elasticsearch#23429]
**Elasticsearch version**:  2.3.5

**Plugins installed**: []

**JVM version**: Java(TM) SE Runtime Environment (build 1.8.0_101-b13)

**OS version**: CentOS release 6.8 (Final)

**Description of the problem including expected versus actual behavior**: 
**Expected** 
  Dynamic template should be persisted in disk  and should be available after ES node restart. 
**Actual**
  After restart of ES nodes template is not working and all the dates are back to string. 

**Steps to reproduce**:
 1. Put a dynamic template
 2. Restart all the data and management nodes
 3. Check the template using http://localhost:9200/_template

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by clintongormley** [comment]
This bug still exists in 5.2

**Comment by clintongormley** [comment]
Sorry - mistake in my testing - templates persist just fine in 2.3.5 and above.

@shubhamitc could you provide a complete recreation, including what you're putting to the `_template` API?

**Comment by shubhamitc** [comment]
This is our template , 

PUT http://elk-api-node.blueapple.mobi:9200/_template/logstash
 
{
    "order": 0,
    "template": "logstash-*",
    "settings": {
      "index": {
        "number_of_replicas": "1",
        "number_of_shards": "5",
        "refresh_interval": "5s"
      }
    },
    "mappings": {
      "_default_": {
        "dynamic_templates": [
          {
            "message_field": {
              "mapping": {
                "index": "analyzed",
                "omit_norms": true,
                "fielddata": {
                  "format": "disabled"
                },
                "type": "string"
              },
              "match": "message",
              "match_mapping_type": "string"
            }
          },
          {
            "custom_time_fields": {
              "mapping": {
                "ignore_malformed": true,
                "format": "yyyy-MM-dd HH:mm:ss.SSS",
                "doc_values": true,
                "type": "date"
              },
              "match": "*Time",
              "match_mapping_type": "string"
            }
          },
          {
            "custom_date_fields": {
              "mapping": {
                "ignore_malformed": true,
                "format": "yyyy-MM-dd HH:mm:ss.SSS",
                "doc_values": true,
                "type": "date"
              },
              "match": "*Date",
              "match_mapping_type": "string"
            }
          },
          {
            "custom_txnid_long_fields": {
              "mapping": {
                "index": "analyzed",
                "omit_norms": true,
                "fielddata": {
                  "format": "disabled"
                },
                "type": "string",
                "fields": {
                  "raw": {
                    "index": "not_analyzed",
                    "ignore_above": 256,
                    "doc_values": true,
                    "type": "string"
                  }
                }
              },
              "match": "*lastBillingResponseTransactionId",
              "match_mapping_type": "long"
            }
          },
          {
            "custom_response_delay_long_fields": {
              "mapping": {
                "doc_values": true,
                "type": "long"
              },
              "match": "responseDelayMillis",
              "match_mapping_type": "string"
            }
          },
          {
            "custom_response_delay_long_fields": {
              "mapping": {
                "doc_values": true,
                "type": "float"
              },
              "match": "responseDelaySecs",
              "match_mapping_type": "string"
            }
          },
          {
            "string_fields": {
              "mapping": {
                "index": "analyzed",
                "omit_norms": true,
                "fielddata": {
                  "format": "disabled"
                },
                "type": "string",
                "fields": {
                  "raw": {
                    "index": "not_analyzed",
                    "ignore_above": 256,
                    "doc_values": true,
                    "type": "string"
                  }
                }
              },
              "match": "*",
              "match_mapping_type": "string"
            }
          },
          {
            "float_fields": {
              "mapping": {
                "doc_values": true,
                "type": "float"
              },
              "match": "*",
              "match_mapping_type": "float"
            }
          },
          {
            "double_fields": {
              "mapping": {
                "doc_values": true,
                "type": "double"
              },
              "match": "*",
              "match_mapping_type": "double"
            }
          },
          {
            "byte_fields": {
              "mapping": {
                "doc_values": true,
                "type": "byte"
              },
              "match": "*",
              "match_mapping_type": "byte"
            }
          },
          {
            "short_fields": {
              "mapping": {
                "doc_values": true,
                "type": "short"
              },
              "match": "*",
              "match_mapping_type": "short"
            }
          },
          {
            "integer_fields": {
              "mapping": {
                "doc_values": true,
                "type": "integer"
              },
              "match": "*",
              "match_mapping_type": "integer"
            }
          },
          {
            "long_fields": {
              "mapping": {
                "doc_values": true,
                "type": "long"
              },
              "match": "*",
              "match_mapping_type": "long"
            }
          },
          {
            "date_fields": {
              "mapping": {
                "doc_values": true,
                "type": "date"
              },
              "match": "*",
              "match_mapping_type": "date"
            }
          },
          {
            "geo_point_fields": {
              "mapping": {
                "doc_values": true,
                "type": "geo_point"
              },
              "match": "*",
              "match_mapping_type": "geo_point"
            }
          }
        ],
        "properties": {
          "@timestamp": {
            "doc_values": true,
            "type": "date"
          },
          "geoip": {
            "dynamic": true,
            "properties": {
              "location": {
                "doc_values": true,
                "type": "geo_point"
              },
              "longitude": {
                "doc_values": true,
                "type": "float"
              },
              "latitude": {
                "doc_values": true,
                "type": "float"
              },
              "ip": {
                "doc_values": true,
                "type": "ip"
              }
            },
            "type": "object"
          },
          "@version": {
            "index": "not_analyzed",
            "doc_values": true,
            "type": "string"
          }
        },
        "_all": {
          "enabled": true,
          "omit_norms": true
        }
      }
    },
    "aliases": {}
  }

**Comment by jasontedor** [comment]
This still does not reproduce. How many master-eligible nodes and data-only nodes do you have, and what is the value of `discovery.zen.minimum_master_nodes` on all nodes?

**Comment by shubhamitc** [comment]
discovery.zen.minimum_master_nodes=2 
Total master = 3 
Number of data nodes = 8 

Upon restarting the management node we are loosing the dynamic template.

**Comment by jasontedor** [comment]
> Number of data nodes = 8

And to be clear, these nodes are not master eligible (`node.master` is set to `false`)?

**Comment by shubhamitc** [comment]
Yes for all data nodes. With zen discovery set for 120 seconds.

**Comment by jasontedor** [comment]
Does this reproduce reliably? That is, every time you put the template and do a full-cluster restart, the template is no longer visible via the get template API? Can you provide output that supports this (put, restart, get)?

**Comment by jasontedor** [comment]
> With zen discovery set for 120 seconds.

Also, can you clarify which setting you're referring to here?

**Comment by shubhamitc** [comment]
This is conf for data node. ..... 


discovery.zen.minimum_master_nodes: 2
discovery.zen.ping.timeout: 120s
discovery.zen.ping.multicast.enabled: true
discovery.zen.ping.unicast.hosts: ["10.138.0.5","10.138.0.7","10.138.0.2","10.138.0.3","10.138.0.4"]
node.master: false
node.data: true
cluster.routing.allocation.disk.threshold_enabled: True
cluster.routing.allocation.disk.watermark.low: 30gb
cluster.routing.allocation.disk.watermark.high: 20gb

**Comment by javanna** [comment]
Closing due to lack of feedback. Feel free to reopen whenever you can provide the requested info that would help diagnosing the issue.
