### ISSUE TITLE
Cluster.routing.allocation.awareness cause shards unassigned

### ISSUE THREAD

**Issue by jayqie** [elastic/elasticsearch#23422]
**Elasticsearch version**: 5.2.0

**Plugins installed**: [elasticsearch-analysis-ik-5.2.0, elasticsearch-analysis-mmseg-5.2.0, elasticsearch-analysis-pinyin-5.2.0]

**JVM version**: 1.8.0_111

**OS version**: CentOS Linux release 7.3.1611 (Core) 

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

I split one elasticsearch cluster into two groups for different scenario usage. One is for high-frequency calls, and the other is normal. The two groups are isolated to prevent the normal group from being affected. I split the cluster using following steps:

1. Create a elasticsearch cluster with four datanodes, two are high-frequency calls, and two are normal.
data-1: node.attr.cluster: highfreq
data-2: node.attr.cluster: normalfreq
data-3: node.attr.cluster: highfreq
data-4: node.attr.cluster: normalfreq

2. Create a new index, routing to two groups
PUT /ztest
{
"settings": {
"number_of_shards": 3,
"number_of_replicas": 1,
"index.routing.allocation.include.cluster": "highfreq,normalfreq"
}
}

3.Make sure that each group has a complete copy of shards.
PUT /_cluster/settings
{
"persistent" : {
"cluster.routing.allocation.awareness.attributes" : "cluster"
}
}

4.Specify the group when querying
GET /ztest/_search?preference=cluster:highfreq
GET /ztest/_search?preference=cluster:normal

It seems to work properly: 

![normal](https://cloud.githubusercontent.com/assets/2605076/23444513/956f6890-fe70-11e6-8ad0-f1da87c07593.png)

5. But sometimes I want to allocate the index only in normal group(this often occurs in some scenarios):
PUT /ztest
{
"settings": {
"number_of_shards": 3,
"number_of_replicas": 1,
"index.routing.allocation.include.cluster": "normalfreq"
}
}

Then only primary shards can be allocated, and the replication shards are unassigned, although there is still a spare resource of one data-node: 
![error](https://cloud.githubusercontent.com/assets/2605076/23444521/a13e2238-fe70-11e6-87d0-bfc03414411a.png)

**Comment by ywelsch** [comment]
Awareness is a cluster-wide property and cannot be disabled on a per-index level. This means that once you enable awareness all indices are affected by it.

**Comment by jayqie** [comment]
Yes, I want to affected the whole cluster. 
When set awareness, the indices include.cluster = "highfreq,normalfreq" can work properly, but the indices include.cluster = "normalfreq" will always have a replication unassigned.

**Comment by ywelsch** [comment]
The unassigned shards are expected here because you're giving two conflicting commands:
- by specifying `"cluster.routing.allocation.awareness.attributes" : "cluster"`, you're essentially saying: please distribute shards according to the cluster attribute. Awareness will make sure that there won't be 2 shard copies on `normalfreq` and none on `highfreq` nodes (and vice versa).
- by specifying `include.cluster = "normalfreq"`, you're saying: put all shards on `normalfreq` nodes.

Also note that the setting `include.cluster = "highfreq,normalfreq"` is effectively a NOOP here.

**Comment by dnhatn** [comment]
@ywelsch Should we close this issue? Looks like that this is not an issue.

**Comment by ywelsch** [comment]
right, closing
