### ISSUE TITLE
RangeQuery where to is near Long.MAX_VALUE causes invalid rewrite

### ISSUE THREAD

**Issue by johnvint** [elastic/elasticsearch#23436]
**Elasticsearch version**: 5.2.0
**JVM version**: Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
**OS version**: OSX 10.11.6

**Description of the problem including expected versus actual behavior**:
This was found when upgrading from ES version 1.7 to 5.2. ES 1.7 had expected results.

When executing a range query on a date where `"include_upper":  true`, a date value at or near `Long.MAX_VALUE` causes the `RangeQueryBuilder` rewrite to overflow the `to` field resulting in an invalid `range` query, ie:
```
{
  "query": {
    "range": {
      "test_date": {
        "from": null,
        "to": 9223372036854775807,
        "include_lower": true,
        "include_upper": true
      }
    }
  }
}
```
Regardless of data the result set here is `0` hits. The expectation would be for the above query to be equivalent to:
```
{
  "query": {
    "range": {
      "test_date": {
        "from": null,
        "to": null,
        "include_lower": true,
        "include_upper": true
      }
    }
  }
}
```

**Steps to reproduce**:
```
curl -XPUT http://localhost:9200/test -d '{
  "mappings": {
    "test": {
      "properties": {
        "test_date": {
          "type": "date"
        }
      }
    }
  }
}'

curl -XPOST http://localhost:9200/test/test -d '{
  "test_date": 1488387860020
}'

curl -XPOST http://localhost:9200/test/test -d '{
  "test_date": 1588387860020
}'

## Query should return 1 hit (the first document indexed)
## PASSES
curl -XPOST http://localhost:9200/test/_search -d '{
  "query": {
    "range": {
      "test_date": {
        "from": null,
        "to": 1500000000000,
        "include_lower": true,
        "include_upper": true
      }
    }
  }
}' | jq 

## Query should return 2 hits being effectively a boundless range
## PASSES
curl -XPOST http://localhost:9200/test/_search -d '{
  "query": {
    "range": {
      "test_date": {
        "from": null,
        "to": null,
        "include_lower": true,
        "include_upper": true
      }
    }
  }
}' | jq

## Query should return 2 hits being effectively a boundless range. 
## FAILS - returns no hits
curl -XPOST http://localhost:9200/test/_search -d '{
  "query": {
    "range": {
      "test_date": {
        "from": null,
        "to": 9223372036854775807,
        "include_lower": true,
        "include_upper": true
      }
    }
  }
}' | jq 

## I noted that this only occurs when the include_upper is true.
## PASSES
curl -XPOST http://localhost:9200/test/_search -d '{
  "query": {
    "range": {
      "test_date": {
        "from": null,
        "to": 9223372036854775807,
        "include_lower": true,
        "include_upper": false
      }
    }
  }
}' | jq 
```
**Analysis**:

I noted that this only occurs when `"include_upper": true`. This is because the date parsing will attempt to round the value up and by doing so will cause the `to` field to overflow such that `to < from`.

This can be easily reproducible with the following: (which is effectively what the `RangeQueryBuilder` rewrite will do)
```
FormatDateTimeFormatter DEFAULT_DATE_TIME_FORMATTER = Joda.forPattern("strict_date_optional_time||epoch_millis", Locale.ROOT);
DateMathParser parser = new DateMathParser(DEFAULT_DATE_TIME_FORMATTER);
assert parser.parse("9223372036854775807", System::currentTimeMillis, true, DateTimeZone.UTC) > 0;
```

**Conclusion**:
Going forward we will make sure the `to` and `from` are both null in the event the query should be boundless.  I understand this is probably the better way to go anyway, the outcome was still surprising.

**Comment by njlawton** [comment]
Hi I am new to the project. Could I try and tackle this?

**Comment by dakrone** [comment]
@njlawton sure! feel free to grab any issue tagged with "adoptme"

**Comment by hesamemadi** [comment]
Hi @njlawton  Are you still going to work on this issue?

**Comment by njlawton** [comment]
Sorry I am no longer working on this issue. Feel free to pick it up.

**Comment by hesamemadi** [comment]
Sorry go for it... I am going to pick another one

**Comment by cbuescher** [comment]
@johnvint thanks a lot again for erposting this bug. Since this seems to be cause by a Joda rounding issue (details in https://github.com/elastic/elasticsearch/pull/23741), it is unlikely that this is going to be fixed upstream soon and its an rare edge case, I'm going to close this issue. Still good to keep this as a known issue though. Feel free to reopen if you think otherwise.
