### ISSUE TITLE
Don't profile ConstantScore queries

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#23430]
A ConstantScore query will return the iterator of its inner query.  However, when profiling, the constant score query is wrapped separately from its inner query, which distorts the times emitted by the profiler.

This could be fixed by not wrapping the iterator if it is already a profiling implementation.

**Comment by firstprayer** [comment]
Interested in picking up this task.

@clintongormley Do you have any code pointer on where should I start? As a newbie I'm not very familiar with the whole architecture of ES


 ![newbie](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0THiET0wh-D4plYx6OvBwew2GYdBQpgDwPQfoiLkOcmRJ11MDhI0LF3tRxg)

**Comment by hchokshi** [comment]
Hi @clintongormley I'm also interested in having a crack at this task as my first contribution if this is still active, and @firstprayer isn't still doing it. However, I cannot find any iterators in the `ConstantScoreQuery` class or the `QueryProfiler` class.

Can you give pointers as to where to start looking, and what is meant by the iterator you mention? I only find a handful of results for "iterator" or "iterate" in the core project, under package `org.elasticsearch.search.profile`

**Comment by liketic** [comment]
Hi @clintongormley Is this still worth to work?

**Comment by clintongormley** [comment]
@liketic it is (i'm the wrong person to ask about how to do it though :) )

**Comment by theostoican** [comment]
Hi, was this issue, by any chance, solved here: https://github.com/kblincoe/elasticsearch/commit/6e0c6c5dd7b622517bcb76919c62e7cf9a503fb5 ? I do not see a PR with this, though.

**Comment by ashishguptak** [comment]
Is this issue being worked-upon? If not, I would be interested in taking it up.

**Comment by mayya-sharipova** [comment]
@ashishguptak I don't think anyone is working on this, please go ahead

**Comment by ashishguptak** [comment]
I see an exhaustive discussion thread on this - https://github.com/kblincoe/elasticsearch/pull/77.
Would like to know the current status. Also, I don't see unit tests around ContextIndexSearcher.class - Do you recommend adding them as a part of this activity?

**Comment by mayya-sharipova** [comment]
@ashishguptak Looks like a PR https://github.com/kblincoe/elasticsearch/pull/77 is stalled.  And yes, tests are necessary as a part of PR.

 @hchokshi  are you still working on this issue?
