### ISSUE TITLE
[Elasticsearch] Current Getting Started Page is returning 404

### ISSUE THREAD

**Issue by hoigau** [elastic/elasticsearch#23445]
**Elasticsearch version**: Current

**Plugins installed**: N/A

**JVM version**: N/A

**OS version**: N/A

**Description of the problem including expected versus actual behavior**:

Access to the Getting Started page from the [Elasticsearch Reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html) returned a 404 error (see attached screendump):

https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started.html

<img width="1321" alt="screen shot 2017-03-02 at 3 45 33 pm" src="https://cloud.githubusercontent.com/assets/23717402/23497691/58ede186-ff5f-11e6-8336-24321551ffaf.png">

**Comment by dadoonet** [comment]
Thanks for reporting. I've seen that as well. 
I'm closing this as it has been reported on another private repo.

**Comment by dadoonet** [comment]
Forgot to say that a refresh often helps.
