### ISSUE TITLE
Update to Azure Storage 5.0.0

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#23448]
We are using `azure-storage:4.0.0` but [latest available version](https://github.com/azure/azure-storage-java) is now 

```
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-storage</artifactId>
    <version>5.0.0</version>
</dependency>
```

Changelog (I highlighted the most important ones IMO):

2017.01.18 Version 5.0.0

 * **Prefix support for listing files and directories.**
 * Added support for setting public access when creating a blob container
 * The public access setting on a blob container is now a container property returned from downloadProperties.
 * Add Message now modifies the PopReceipt, Id, NextVisibleTime, InsertionTime, and ExpirationTime properties of its CloudQueueMessage parameter.
 * Populate content MD5 for range gets on Blobs and Files.
 * Added support in Page Blob for incremental copy.
 * **Added large BlockBlob upload support. Blocks can now support sizes up to 100 MB.**
 * Added a new, memory-optimized upload strategy for the upload* APIs. This algorithm only applies for blocks greater than 4MB and when storeBlobContentMD5 and Client-Side Encryption are disabled.
 * getQualifiedUri() has been deprecated for Blobs. Please use getSnapshotQualifiedUri() instead. This new function will return the blob including the snapshot (if present) and no SAS token.
 * getQualifiedStorageUri() has been deprecated for Blobs. Please use getSnapshotQualifiedStorageUri() instead. This new function will return the blob including the snapshot (if present) and no SAS token.
 * Fixed a bug where copying from a blob that included a SAS token and a snapshot ommitted the SAS token.

**Comment by peterleonardlie** [comment]
I would like to take try to fix this issue :)

**Comment by dadoonet** [comment]
All yours! ;)

**Comment by peterleonardlie** [comment]
hi @dadoonet I'm kinda new to this,
i know we have to change the dependencies in elasticsearch/plugins/repository-azure/build.gradle 
what is the branch i have to use? master? or there is other branch?

**Comment by dadoonet** [comment]
Master. We do the backport if needed.
