### ISSUE TITLE
Replace `#!/bin/bash` with `#!/usr/bin/env bash`

### ISSUE THREAD

**Issue by jan0sch** [elastic/elasticsearch#23443]
**Elasticsearch version**: 5.2.2

**OS version**: Any OS that has bash not in `/bin` like FreeBSD for example.

**Description of the problem including expected versus actual behavior**:
Starting elasticsearch results in an error about bash not being found:

```
./bin/elasticsearch: bad interpreter: /bin/bash: no such file or directory
```

**Steps to reproduce**:
 1. Download and extract elasticsearch
 2. Change into elasticsearch directory
 3. run `/bin/elasticsearch`

A solution would be to replace the shebang `#!/bin/bash` with `#!/usr/bin/env bash`. This affects several scripts.

**Comment by jan0sch** [comment]
Thanks for the detailed answer. I actually never ran into a system where `env` was not in `/usr/bin` ;-)

Because of the limitations of `env` under linux I guess that path and argument issues cannot be circumvented which is sad. However it would be great to mention the fact that `bash` is assumed to be available under `/bin` in the readme or docs. Maybe together with the reasons stated here why it cannot be changed.

This would leave the option of symlinking or patching the start scripts manually after installation to the affected users.

**Comment by jasontedor** [comment]
> However it would be great to mention the fact that `bash` is assumed to be available under `/bin` in the readme or docs.

This is a good suggestion. I opened #23464.

**Comment by jan0sch** [comment]
Looks good. Shall I close this issue and my pull request?

**Comment by jasontedor** [comment]
> Looks good. Shall I close this issue and my pull request?

Yes, I think so. Thank you for your understanding. :smile:
