### ISSUE TITLE
must_not clause returns score of 1

### ISSUE THREAD

**Issue by juzpermsky** [elastic/elasticsearch#23449]
**Elasticsearch version**:
5.2.0
**JVM version**:
1.8.0_101
**OS version**:
Ubuntu 16.04.1 LTS
**Description of the problem including expected versus actual behavior**:
[Here](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/query-dsl-bool-query.html) we see:
![image](https://cloud.githubusercontent.com/assets/9256158/23504447/510f94f8-ff61-11e6-8ff3-ecdb6ed054ca.png)
But, in fact, we get score of 1.
**Steps to reproduce**:
 1. `PUT test/test/test
{
  "test":"test"
}`
 2. `GET test/_search
{
  "explain": true, 
  "query": {
    "bool": {
      "must_not": [
        {
          "exists": {
            "field": "not_test"
          }
        }
      ]
    } 
  }
}`
 3. Response: `{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_shard": "[test][2]",
        "_node": "qQxx48b4QB27w0TOTlxhAw",
        "_index": "test",
        "_type": "test",
        "_id": "test",
        "_score": 1,
        "_source": {
          "test": "test"
        },
        "_explanation": {
          "value": 1,
          "description": "sum of:",
          "details": [
            {
              "value": 1,
              "description": "*:*, product of:",
              "details": [
                {
                  "value": 1,
                  "description": "boost",
                  "details": []
                },
                {
                  "value": 1,
                  "description": "queryNorm",
                  "details": []
                }
              ]
            }
          ]
        }
      }
    ]
  }
}`

**Comment by JohPa8696** [comment]
I am new to this project and would like to work on this issue. Any advice and suggestion would be greatly appreciated.

**Comment by JohPa8696** [comment]
I am no longer working on this issue

**Comment by javanna** [comment]
I am not sure whether this is a bug or a documentation issue. @jpountz what do you think?

**Comment by clintongormley** [comment]
That's because there is an implicit `match_all` when only a `must_not` clause is used.

**Comment by clintongormley** [comment]
I'm not sure this is worth documenting - who is going to rely on this behaviour?

**Comment by nik9000** [comment]
I think the docs just say the score is `0` when it should be `1`. Probably my mistake. I reworked some of those docs a week or two ago.

**Comment by jpountz** [comment]
We return a score of 0 when there are only `filter` clauses, I think it would be consistent to do the same when there are only `must_not` clauses? I think it would be just a matter of making the `match_all` query a `FILTER` clause rather than `MUST` in `Queries.fixNegativeQueryIfNeeded`.

**Comment by clintongormley** [comment]
should probably just remove this sentence:

> Because scoring is ignored, a score of 0 for all documents is returned.

No score is returned because the docs are not returned

**Comment by cbuescher** [comment]
Removing the `discuss` label since we already have an open PR adressing this.

**Comment by andyb-elastic** [comment]
@elastic/es-search-aggs 

@jpountz do we still want to merge #26015
