### ISSUE TITLE
Increase chunk_size max to 256 Mb instead of 64 Mb

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#23446]
While working on an azure issue, I found [this documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/understanding-block-blobs--append-blobs--and-page-blobs) which says that we can now increase the max block blob to 256mb instead of the default 64mb which has been introduced in #22577

> # About Block Blobs
> Block blobs let you upload large blobs efficiently. Block blobs are comprised of blocks, each of which is identified by a block ID. You create or modify a block blob by writing a set of blocks and committing them by their block IDs. Each block can be a different size, up to a maximum of 100 MB (4 MB for requests using REST versions before 2016-05-31), and a block blob can include up to 50,000 blocks. The maximum size of a block blob is therefore slightly more than 4.75 TB (100 MB X 50,000 blocks). For REST versions before 2016-05-31, the maximum size of a block blob is a little more than 195 GB (4 MB X 50,000 blocks). If you are writing a block blob that is no more than 256 MB (64 MB for requests using REST versions before 2016-05-31) in size, you can upload it in its entirety with a single write operation; see [Put Blob](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/put-blob).

**Comment by dadoonet** [comment]
See also #23448

**Comment by nmjacob** [comment]
I am new to GitHub public projects, so if possible I would like to make this my first fix on the project. That way I can dip my toe in the water.

**Comment by peterleonardlie** [comment]
Hi, I've changed the maximum chink size from 64MB to 256MB

**Comment by dadoonet** [comment]
Thanks @peterleonardlie for your PR but @nmjacob said first that he would like to contribute to the project.

So if you don't mind, I'd like that he starts the effort with our help.
Do you mind closing your PR and take another one like https://github.com/elastic/elasticsearch/issues/23448 to contribute?

Thanks!

**Comment by peterleonardlie** [comment]
sure no problem! im sorry for starting it then, because i see nothing happened after a day :)

**Comment by nmjacob** [comment]
Forgive me for my ignorance, but I just submitted a pr to fix this. Do I need to link it to the issue in any way? Sorry about the delay getting the fix done.

**Comment by dadoonet** [comment]
@nmjacob You just have to create the PR and add `Closes #23446.` in your commit message so the PR will contain also this text and will be linked to this issue.

**Comment by batradhruv** [comment]
Can I pick this up?

**Comment by ywelsch** [comment]
@batradhruv this was already picked up, see #32101 and #12448
