### ISSUE TITLE
Serach record from multiple table using ElasticSearch in .net

### ISSUE THREAD

**Issue by Rahul96553** [elastic/elasticsearch#23455]
Search Record From Multiple Table ElasticSearch Query using .net?

**Comment by jasontedor** [comment]
@Rahul96553 Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
