### ISSUE TITLE
While using multiple Inner hits, null array is shown

### ISSUE THREAD

**Issue by imapurv** [elastic/elasticsearch#23450]
I have upload the query and result. Please Tell is it a bug or I am making some mistake.

[Untitled Document.txt](https://github.com/elastic/elasticsearch/files/813767/Untitled.Document.txt)

**Comment by cbuescher** [comment]
Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions. Please open an issue there first if unsure about how to use a feature. To help reproduce your issue, it would also be helpful to provide a full reproduction including mappings and the sample data you use.
