### ISSUE TITLE
Unable to start the 3Node Elasticsearch Cluster named: Development 

### ISSUE THREAD

**Issue by chennaraov** [elastic/elasticsearch#23461]
![image](https://cloud.githubusercontent.com/assets/19313298/23517541/ae7053c6-ff3e-11e6-9990-242f272cc9fc.png)

**Elasticsearch version**:

**Plugins installed**: []

**JVM version**:

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

And don't paste images even on discuss. I saw you did.
