### ISSUE TITLE
ES fails to start when empty state file exists

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#23466]
- Tested on ES 5.1.1
- Also related - https://github.com/elastic/elasticsearch/issues/13012

In more than one example, including the referenced Github issue, it seems that a disk failure (under RAID0 in both examples, not sure if the RAID is relevant or not) causes corruption (evidently on _other_ disks in `path.data`) where an empty state file is written.  

In the case where that empty state file exists, ES fails to start.  To reproduce the startup failure:

```
mkdir -p elasticsearch-5.1.1/data/nodes/0/indices/xlhpEFBXTY6V2c6EP0jDFF/_state
touch elasticsearch-5.1.1/data/nodes/0/indices/xlhpEFBXTY6V2c6EP0jDFF/_state/state-888.st

./elasticsearch-5.1.1/bin/elasticsearch

...
[2017-03-02T14:56:34,734][ERROR][o.e.g.GatewayMetaState   ] [5RtLzjO] failed to read local state, exiting...
org.elasticsearch.ElasticsearchException: java.io.IOException: failed to read [id:888, legacy:false, file:/Users/jay/Workspace/elasticsearch-5.1.1/data/nodes/0/indices/xlhpEFBXTY6V2c6EP0jDFF/_state/state-888.st]
...
Caused by: java.io.IOException: failed to read [id:888, legacy:false, file:/Users/jay/Workspace/elasticsearch-5.1.1/data/nodes/0/indices/xlhpEFBXTY6V2c6EP0jDFF/_state/state-888.st]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:326) ~[elasticsearch-5.1.1.jar:5.1.1]
        ... 46 more
Caused by: java.lang.IllegalStateException: class org.apache.lucene.store.BufferedChecksumIndexInput cannot seek backwards (pos=-16 getFilePointer()=0)
...
[2017-03-02T14:56:34,743][ERROR][o.e.g.GatewayMetaState   ] [5RtLzjO] failed to read local state, exiting...
```

**Comment by jasontedor** [comment]
The state file is corrupt. We definitely should not ignore it. It needs to be destroyed on this node and recovered from elsewhere.

**Comment by jasontedor** [comment]
I'm closing this issue, if someone disagrees that we should be lenient here, please feel free to reopen the issue.

**Comment by saiprasannasastry** [comment]
@jasontedor what is the solution for this? i have seen this issue as well and don't have a way to figure out which state file is corrupt.
any pointers ?
@PhaedrusTheGreek were you able to resolve it?

**Comment by jasontedor** [comment]
@saiprasannasastry If you open a topic on the [forums](https://discuss.elastic.co) with details of the problem you're facing someone will take a look. That's our preferred method of handling user questions.

**Comment by saiprasannasastry** [comment]
@jasontedor sure will do that, but this was closed without a proper comment, hence added it

**Comment by jasontedor** [comment]
The point of this issue was: ES fails to start when its local state file is corrupt. We closed this as: we are not going to change the behavior here, a corrupt state file is a serious issue. That was stated [here](https://github.com/elastic/elasticsearch/issues/23466#issuecomment-283776256) and given as the close reason in the [following](https://github.com/elastic/elasticsearch/issues/23466#issuecomment-298167822) comment.
