### ISSUE TITLE
Request to add ability to _simulate an existing document(s)

### ISSUE THREAD

**Issue by djschny** [elastic/elasticsearch#23467]
**Describe the feature**:

With `_ingest` pipelines there is the ability to `_simulate` a pipeline where docs are sent up inline in the request. It would be convenient to also supply document id(s) of existing documents inside Elasticsearch to use for the simulation. We do this today for explain relevancy for example.

I find a lot of folks that are learning pipelines and trying to build them reach for this feature.

**Comment by dakrone** [comment]
Instead of adding a new endpoint, this could possibly reuse the existing `/_validate` endpoint, perhaps as `/_validate/ingest/{pipeline-id}` with a document.

**Comment by talevy** [comment]
Although this would be convenient for some, the intention of the simulate pipeline is to reduce the complexity only to the pipeline in question. Closing
