### ISSUE TITLE
No inner hits returned when nested query inside dismax query (v5)

### ISSUE THREAD

**Issue by wboult** [elastic/elasticsearch#23482]
**Elasticsearch version**:
5.2.1
**Plugins installed**: []
**JVM version**:
1.8
**OS version**:
NAME="Amazon Linux AMI"
VERSION="2016.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2016.09"
PRETTY_NAME="Amazon Linux AMI 2016.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2016.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2016.09

**Description of the problem including expected versus actual behavior**:
I've just moved to elastic v5 (5.2.1) from 2.3.5 and am finding that I cannot get nested inner hits back when the nested query is placed inside a dismax query.

**Steps to reproduce**:
 1. Create new index with nested type

```
curl -XPUT localhost:9200/nested-dismax '{
  "mappings": {
    "tpe": {
      "properties": {
        "bob": {
          "type": "nested",
          "properties": {
            "name": {
              "type": "text"
            }
          }
        }
      }
    }
  }
}'
```

 2. Index a document:

```
curl -XPUT localhost:9200/nested-dismax/tpe/1 '{
  "bob" : {
    "name" : "Bob"
  }
}'
```

 3. Try a nested query without a dismax and it works:

```
curl -XGET localhost:9200/nested-dismax/_search '{
  "query": {
    "nested": {
      "path": "bob",
      "query": {
        "match": {
          "bob.name": "Bob"
        }
      },
      "inner_hits":{}
    }
  }
}'
```

4. Try it with a dismax around it and no inner hits are returned:

```
curl -XGET localhost:9200/nested-dismax/_search '{
  "query": {
    "dis_max": {
      "queries": [
        {
          "nested": {
            "path": "bob",
            "query": {
              "match": {
                "bob.name": "Bob"
              }
            },
            "inner_hits": {}
          }
        }
      ]
    }
  }
}'
```

PS - apologies if the curls don't run straight away, I was using sense and my server got shut down before I could test the curl version!

**Comment by martijnvg** [comment]
@wboult Thanks for reporting this. Inner hits are indeed not working when nesting it under `dis_max` query.

**Comment by zahir-koradia** [comment]
I see the fix has been added to v6. Is it expected to be back ported to v5?
