### ISSUE TITLE
Allow multiple similar scores being returned

### ISSUE THREAD

**Issue by firstprayer** [elastic/elasticsearch#23488]
Looking through the docs it seems there isn't a way to returning multiple similarity scores for retrieved documents so making the feature requests here (if this is supported please close this issue).

Basically what I want is, when doing the search, returning top-relevant documents based on BM25 score (the default strategy), but in the meantime, also compute other similarity scores for those documents (such as TF-IDF similarity, DFI similarity), and returned them as part of the results for each document.

Reason why we need this being - we'd like to use BM25 for an initial retrieve, then do fine-tuning on the retrieved set on our side. We'd like to use learning-to-rank algorithm and we want to use BM25 score, TF-IDF score, DFI score, etc, as part of the features. 

While it's possible to do the calculation in our end - say, for TF-IDF we can just fetch the termVector for each document, and then do the computation manually - I feel it's much ideal if we can get this done with ElasticSearch, since it has all the data it need to do the computation.

I'm thinking about having something like
```
{
  fieldName: {
     type: "text",
     similarity: "BM25",
     extra_similarity: ["classic", "dfi"],
  }
}
```

Then in the returned results:

```
{_score: bm25Score, _extra_scores: {classic: ..., dfi: ...}}
```

**Comment by firstprayer** [comment]
@ncdc @AndrewO @ph @matschaffer @deontologician can anyone with more permission take a look at this? It seems I can't even apply tag on this issue. Please let me know what you guys think of the value of this work - we find it useful, but maybe it can be implemented in a different and better way.

**Comment by robertfeldt** [comment]
Has there been any further progress or discussion on this? I would also like to extract multiple similarity values for later tuning.

**Comment by clintongormley** [comment]
We wouldn't be able to do this without significant changes in Lucene.  I suggest asking there first.
