### ISSUE TITLE
Cannot delete watchers when using basic license

### ISSUE THREAD

**Issue by lemonlinger** [elastic/elasticsearch#23490]
I know that the watcher function cannot be used under the basic license. 
Now I want to delete a watcher created when using trial license. However, I failed to do this.
Get the followed response from my elasticsearch host:
`{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "current license is non-compliant for [watcher]",
        "license.expired.feature": "watcher"
      }
    ],
    "type": "security_exception",
    "reason": "current license is non-compliant for [watcher]",
    "license.expired.feature": "watcher"
  },
  "status": 403
}`

So, is there a way to delete watchers when using basic license?
Thanks for any comments.

**Comment by tvernum** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking these sorts of questions and prefers to use GitHub only for verified bug reports and feature requests.

I'd suggest that you check the list of enhancements/bug fixes in the [X-Pack release notes](https://www.elastic.co/guide/en/x-pack/current/xpack-release-notes.html) and if that doesn't resolve your issue, ask again on [discuss](https://discuss.elastic.co/c/x-pack).

I'm going to close this issue. If the discussion on the forum determines that there is an unresolved bug, then we can open a new issue.
