### ISSUE TITLE
No source field in org.elasticsearch.search.suggest.completion.CompletionSuggestion.Entry.Option

### ISSUE THREAD

**Issue by gkozyryatskyy** [elastic/elasticsearch#23496]
**Elasticsearch version**: 5.2.1
**Elasticsearch transport client version**: 5.2.1

**Description of the problem including expected versus actual behavior**:
Completion suggestion responses have a `_source` field (suggest.{name}.options._source)
Example:

```
{
   "took":4,
   "timed_out":false,
   "_shards":{
      "total":5,
      "successful":5,
      "failed":0
   },
   "hits":{
      "total":0,
      "max_score":0.0,
      "hits":[ ]
   },
   "suggest":{
      "keyword":[
         {
            "text":"angelina",
            "offset":0,
            "length":8,
            "options":[
               {
                  "text":"Angelina Confronts Anthony",
                  "_index":"autocomplete",
                  "_type":"keyword",
                  "_id":"Angelina Confronts Anthony",
                  "_score":1.0,
                  "_source":{
                     "text":"Angelina Confronts Anthony",
                     "categories":[
                        "TROPE",
                        "ALL"
                     ]
                  },
                  "contexts":{
                     "categories":[
                        "ALL"
                     ]
                  }
               },
               {
                  "text":"Angelina Jolie",
                  "_index":"autocomplete",
                  "_type":"keyword",
                  "_id":"Angelina Jolie",
                  "_score":1.0,
                  "_source":{
                     "text":"Angelina Jolie",
                     "categories":[
                        "TROPE",
                        "ADULT",
                        "ALL"
                     ]
                  },
                  "contexts":{
                     "categories":[
                        "ALL"
                     ]
                  }
               }
            ]
         }
      ]
   }
}
```

But `org.elasticsearch.search.suggest.completion.CompletionSuggestion.Entry.Option` have no `source()` method or `source` field. How can I get source from completion suggester results using elasticsearch java transport client?

**Comment by cbuescher** [comment]
Elastic reserves GitHub for bug reports and feature requests. Please use the [Discourse forum](https://discuss.elastic.co) or [IRC channels](https://www.elastic.co/community) for general questions like this in the future. Regarding your question: try `option.getHit().getSource()` (or any other of the getSource*() methods)

**Comment by gkozyryatskyy** [comment]
@cbuescher Just thought there is no way to retrieve the source (then it would be a bug) and was confused with json\object structure. Thank you for your help.

**Comment by rsmilyanov** [comment]
@gkozyryatskyy did you find a way to read the source map? I am facing the same problem and I cannot find a way to read the source map from the response and ```Option``` does not have ```getHit()``` as it was mentioned above already.

**Comment by gkozyryatskyy** [comment]
@rsmilyanov 
What version of the client are you using?
https://github.com/elastic/elasticsearch/blob/ee802ad63c0f21d697a5095dd05dc6f94626ee4d/core/src/main/java/org/elasticsearch/search/suggest/completion/CompletionSuggestion.java
has `public SearchHit getHit()` method

**Comment by rsmilyanov** [comment]
@gkozyryatskyy 
I am using version 5.0.0 and I found my problem. It was a dummy mistake with the variable type from my side :( I got the source from the response finally. Thanks for your quick response.

**Comment by harshitdx29** [comment]
@rsmilyanov How did you get it? Facing the same issue. Option doesn't have a gitHit() or getSource() method.

**Comment by rsmilyanov** [comment]
@harshitdx29 
```
Suggest suggestResponse = searchReponse.getSuggest();

CompletionSuggestion suggestion = (CompletionSuggestion) suggestResponse.getSuggestion(suggestName);

List<CompletionSuggestion.Entry> entries = suggestion.getEntries();

for (CompletionSuggestion.Entry entry : entries)
{
       for (CompletionSuggestion.Entry.Option option : entry.getOptions())
       {
             option.getHit().getSourceAsMap()
       }
}
```

**Comment by harshitdx29** [comment]
Thanks @rsmilyanov
