### ISSUE TITLE
Highlighting is not working with function score query and querystring with wild-card

### ISSUE THREAD

**Issue by rkalhans** [elastic/elasticsearch#23492]
**Elasticsearch version**:**2.4.4**

**Plugins installed**: []

**JVM version**:**java-8**

**OS version**:**Windows**

**Description of the problem including expected versus actual behavior**:

**Highlighting working without function score query**
![highitingworking](https://cloud.githubusercontent.com/assets/5341933/23610593/0eb3474a-0299-11e7-8ef6-0851b0af1848.PNG)

**Highlight broken with function score query**
![notworking](https://cloud.githubusercontent.com/assets/5341933/23610594/0eb40f22-0299-11e7-894c-09d3648041c4.PNG)

**Server versions, build etc.**
![server](https://cloud.githubusercontent.com/assets/5341933/23610592/0eb2c02c-0299-11e7-8460-9127fd75bf93.PNG)

Here is the query used in plain text.
```
POST workitemsearchshared_0_1/workItemContract/_search
{
   "highlight": {
      "pre_tags": [
         "<highlighthit>"
      ],
      "post_tags": [
         "</highlighthit>"
      ],
      "fields": {
         "fields.str|title|system$": {}
      },
      "require_field_match": true
   },
   "fields": [
      "fields.str|title|system$"
   ],
   "query": {
      "function_score": {
         "query": {
            "query_string": {
               "query": "park*",
               "fields": [
                  "fields.str|title|system$"
               ]
            }
         },
         "functions": [
            {
               "filter": {
                  "term": {
                     "fields.str|title|system$": "parkour"
                  }
               },
               "weight": 8
            }
         ]
      }
  }
}

```
This may be due to a partial fix of [BUG#20392](https://github.com/elastic/elasticsearch/issues/20392)

**Comment by zdenal** [comment]
Hi @rkalhans have you find any solution for this issue? I am also trying make highlighting works with `function_score` .... w/o success :(

Thanks,
Zdenal

**Comment by nik9000** [comment]
I believe this is one of the cases where in the past I used `highlight_query` without the `function_score` to get the job done. It is worth investigating that, I think.

**Comment by zdenal** [comment]
@nik9000 this helped me a lot!!! Thank you!!!!

Zdenal

**Comment by jimczi** [comment]
Highlighting prefix (multi-term) queries inside `function_score` does not work with the `postings` highlighter.
The `plain` and `fvh` highlighters are not affected and works as expected with the example above.
The `postings` highlighter has been deprecated in 5.x and is removed from 6 so I'll close this issue.
The workaround is to use an `highlight_query` as Nik suggested or to upgrade to 5 and use the `unified` highlighter that is able to highlight all text queries exposed in es.

**Comment by prashanttct07** [comment]
Has anyone solved the same? As we were trying the same query on 2.0, 2.4, 2.6 with plain and fvh but that is not working too.

**Comment by Surt** [comment]
Can't do it either. Any tip to make highlight work with function score?
