### ISSUE TITLE
Elasticsearch 5.2.2 on low cpu memory optimization

### ISSUE THREAD

**Issue by akefallonitis** [elastic/elasticsearch#23494]
I installed elasticsearch 5.2.2 on arm raspberry pi3 and i have 100% all cpus. Except max memory , shards and rellocation is there any other settings to apply for low resources machines? Eg threads and max cpu cores or something else as optimization? Thanks in advanced for help

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
