### ISSUE TITLE
Old GC pool is increasing continously with number of requests

### ISSUE THREAD

**Issue by vanga** [elastic/elasticsearch#23499]
**Elasticsearch version**:
5.2.2
**Plugins installed**: [mapper-murmur3, ec2-discovery, s3-repository, x-pack]

**JVM version**:
openjdk version "1.8.0_121"

**OS version**:
Ubuntu 16.04
**Description of the problem including expected versus actual behavior**:
Heap usage is continuously increasing as I run queries with scripts, which is causing frequent old GCs. Old GC is clearing most of the heap, but it's happening almost all the time (because of the no of scripts that are being run)
**Steps to reproduce**:
Refer ES query https://gist.github.com/vanga/2cd8e1fd7c3b2bffa89fda8ce3a8a481#file-query1
I have already asked this in forum
https://discuss.elastic.co/t/heap-usage-of-client-node-is-continuously-increasing-as-i-run-queries/77032

I have also tested the above query in 3 different scenarios
1) Run once every second 
2) Run every second by setting `inline: ""`
3) Run every second by removing the reduce script altogether

Memory increase:
1) causes an increase of 400-500 MB per 10 minutes
2) causes an increase of 100 MB per 10 minutes
3) negligible in a time window of 10 mins, but it's increasing slowly

This increase seems like not much, but with significant traffic/data size on production this is causing frequent GCs (almost all the time, every minute or so)
This isn't happening if I run queries without scripts, no matter with what concurrency. 

is this a bug or is there anything that can be done to improve this situation.
I am not sure if this will be helpful, but here is the jmap histo output
```
----------------------------------------------
   1:       6331050      998816688  [C
   2:        922539      190724632  [B
   3:       5909870      189115840  java.util.HashMap$Node
   4:       6293885      151053240  java.lang.String
   5:       2055583      132862912  [Ljava.util.HashMap$Node;
   6:       2317385      111234480  java.util.HashMap
   7:       2482432       59578368  java.util.ArrayList
``` 
**Provide logs (if relevant)**:

**Comment by bleskes** [comment]
> (because of the no of scripts that are being run)
> This isn't happening if I run queries without scripts, no matter with what concurrency.

That query is quite complicated so I think it would helpful to try to reproduce with a smaller one. Can you double check it's not the terms agg (the size 10000 is obviously dangerous):

```
      "terms": {
        "field": "locations",
        "size": 10000,
        "order": {
          "_term": "asc"
        }
      },
```

What happens if you run your script (`latestByTimeStamp__f7BedzrFUQ__test_meta__WMk4jA0bd24 `) as a single top level agg?

**Comment by vanga** [comment]
@bleskes that query results in about 110 terms. And, based on testing, removing the reduced script made a significant difference. 
Do you still think it's because of the aggregation?


> What happens if you run your script (latestByTimeStamp__f7BedzrFUQ__test_meta__WMk4jA0bd24) as a single top level agg?
I will check this

**Comment by vanga** [comment]
I have tested the query with various sizes
100, 200, 500, 1000, 10000.

Except with 100, all other cases have caused the memory(old gc pool) to increase.

**Comment by jdoss** [comment]
We are seeing the same problem with 5.2.2 with our aggregations. Tons of Old GCs when we have many aggregations running at the same time from our users. Everything was fine in 2.4 before we upgraded.

**Comment by bleskes** [comment]
@jdoss it would be great if you can give specific examples of the aggregations you use, trying to pin pointing the ones that started using more information.

**Comment by vanga** [comment]
An update: Memory increase issue is gone after we brought down the number of indices
`70 indices with 5 shards, 1 replica` => `< 10 indices, 5 shards, 1 replica`
