### ISSUE TITLE
ES 2.4.0 shard initialization taking more time 

### ISSUE THREAD

**Issue by searchandanalytics** [elastic/elasticsearch#23501]
Hello Experts,

**Elasticsearch version**: 2.4.0

**Plugins installed**: [ KOPF, AWS-cloud . s3cmd]
**JVM version**: 1.8

**OS version**: Ubuntu

**Description of the problem including expected versus actual behavior**:
 New stage environment with 5 node (1 Master, 2 Master-data, 2 Data) have 3 indexes with total size around 600 MB. All node restarted after modification in yml file (added path.repo). Now the problem is after 12 hr cluster health is RED and shard still in initialization state.

Cluster - 1 Master, 2 Master-data, 2 data
All master-data and data node and 64GB RAM and 1.29 TB space . Master node have 32 GB and 660 GB space.
Heap - not more than half of total available memory.

Yml config - all default except below

cluster.name: myname
node.name: prodnode1
node.master: true
node.data: true
path.data: /data/elasticsearch
path.logs: /var/log/elasticsearch
path.repo: /data/datas3/elastic-search-backup
bootstrap.memory_lock: true
network.host: hostIP
discovery.zen.ping.unicast.hosts: ["master-only", "master-data", "master-data"]
discovery.zen.minimum_master_nodes: 2

Any help appreciated. Thanks in advance.

**Comment by bleskes** [comment]
@searchandanalytics we try to reserve github to issues and feature request. Can you please ask your question at our forums on discuss.elastic.co? if it turns out to be an issue we can come back here. I also suggest you give some more info like logs and the output of the `_recovery` API.

**Comment by searchandanalytics** [comment]
Okay. bleskes. 
Just to update here.  _recovery returns blank response and nothing in logs but _tasks returns response as below.. 
CXveFzvHS-GMv-h-uf4RVA:2083" : {
          "node" : "CXveFzvHS-GMv-h-uf4RVA",
          "id" : 2083,
          "type" : "netty",
          "action" : "internal:discovery/zen/publish",
          "start_time_in_millis" : 1488870873680,
          "running_time_in_nanos" : 40744147056568
        }
