### ISSUE TITLE
Searching for children without parents

### ISSUE THREAD

**Issue by acarstoiu** [elastic/elasticsearch#23504]
**Elasticsearch version**: 2.4.3

Given a pair of parent and child entities, already populated within an index, I would like to obtain all child entities whose parent is missing (for whatever reasons, e.g. due to bugs). If I execute
```
GET idx/child/_search
{
  query: {
    bool: {
      must_not: {
        has_parent: {
          parent_type: "parent",
          query: {
          }
        }
      }
    }
  }
}
```
I get all existing children. Hmm.. what if I submit this query:
```
GET idx/child/_search
{
  query: {
    bool: {
      must: {
        has_parent: {
          parent_type: "parent",
          query: {
          }
        }
      }
    }
  }
}
```
I get **_again_ all existing children**. Regardless of how you interpret an empty `query` block within `has_parent` this is plain non-sense. Every child has a single parent that cannot _both_ satisfy and not satisfy a predicate at the same time.

**Comment by hlu725** [comment]
Hi,guys. i'd like to fix this bug.
could u give me your test data which can show the bug
thank u

**Comment by acarstoiu** [comment]
There's no need for specific data. Any parent-child mapping with one child document in the index would do.

**Comment by talevy** [comment]
This feature request is an interesting idea but since its opening we have not seen enough feedback that it is a feature we should pursue. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).

**Comment by acarstoiu** [comment]
Sorry to say it, but you missed the fact that this is first and foremost a **bug report**, not a feature request. Two logically opposed queries that return the same thing is a fault - just choose one side and then we can talk about _improvements_.

**Comment by talevy** [comment]
@acarstoiu apologies, I should have taken a closer look here (my fault). Thank you for replying and 
continuing the discussion; This, obviously, still sounds relevant to you, so I will go ahead and re-open the issue

**Comment by colings86** [comment]
This bug has been fixed by the fact that in later versions  of Ealsticsearch the empty query `"query":{}` is no longer valid and the fact that a `has_parent` query must now have a query
