### ISSUE TITLE
Add `ignoreMissing` parameter to queries that fetch execute get requests?

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#23502]
There are a number of queries (`geo_shape`, `percolator` etc.) that potentially use the get api to fetch data in order to run the query. If the document that they need to fetch is missing the entire search fails with an error. I think this is good default behaviour. However there are cases where one might want to ignore this and just ignore the query in question. 

I think we should add `ignoreMissing` boolean parameter to these queries and if `ignoreMissing` has been set to true the query gets ignored. The parameter should default to false. Similar to how `ignoreUnmapped` parameter works on other queries.

**Comment by BlureX** [comment]
Hi there, I'm new to this project but I was wondering if I could work on this issue?

**Comment by clintongormley** [comment]
Discussed in FixItFriday.  Today, a query with a missing geoshape etc returns enough info in the exception to allow the application to do the right thing. We're reluctant to add this when we haven't heard requests for it before, although the feature has been there for a long time. Every added feature means more opportunities for bugs and unintended consequences.  

I'll leave this open to see if it gathers any more support.

**Comment by matteus6007** [comment]
My team currently uses the `geo_shape` query to match a UK postcode to a `geo_point`, but if the user enters a valid format for a postcode, but it is not found it currently returns a `400` with the wrapper exception inside it, I would prefer if either a) it would act as if there are no matches and return no results or maybe better b) you could add a bool query to check if the shape exists

**Comment by jpountz** [comment]
Discussed in FixitFriday. Queries that fetch remote documents introduce quite a number of corner-cases, so we are not keen to making it more complex unless we see significant traction.
