### ISSUE TITLE
Update using index aliases

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch#23507]
I have a scenario where I create monthly indexes, the latest 12 month are referred by an alias (current_month).

We have a scenario where we may need to update certain documents.

We will know the _id value before-hand, and know the update field, but will not know in which monthly index the document is available.

Is there a way to update the document just by referring the alias (current_month).

Or do I need to do the following:

1)      First search and figure out which index has the document

2)      Then apply the update to that index

We are currently working around this by using the second method, but it would be useful if the update could be sent to the alias.  I know the ID would not necessarily be unique across all indices, but it is likely that it would be and in the event it is not, we could trap that out as an error.

**Comment by jasontedor** [comment]
> We are currently working around this by using the second method, but it would be useful if the update could be sent to the alias.

I do not think that we should allow this. An alias can point to multiple indices; what if the document ID matches a document in multiple indices behind the alias? It's too confusing to only allow it in situations where this is not the case so I'm against this feature.

**Comment by jasontedor** [comment]
> It's too confusing to only allow it in situations where this is not the case so I'm against this feature.

Additionally, this is subject to time-of-check-time-of-use problems.

**Comment by javanna** [comment]
I am closing this, we are not going to implement this for the reasons that Jason stated above.
