### ISSUE TITLE
Support for accessing Azure repositories through a proxy

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#23506]
Consider adding support for accessing an Azure snapshot repository through a proxy. At the moment, the only closely related option is to use `https.proxyPort/Host` java options, which are ignored for this type of Azure access.

**Comment by dadoonet** [comment]
We need first to implement #23448 so we will be able to do something like:

```java
OperationContext.setDefaultProxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("10.1.1.1", 8888)));
```

Which [has been added](https://github.com/Azure/azure-storage-java/commit/85ffeb46856f591a65e681a9065cc7a1a356f83c) since v4.2.0.
