### ISSUE TITLE
How can I modify the 'index.max_result_window' again?

### ISSUE THREAD

**Issue by tonyjames3212** [elastic/elasticsearch#23516]
**Elasticsearch version**:5.2.0

**JVM version**:8u121

**OS version**:CentOS6.5

**Description of the problem including expected versus actual behavior**:
I have changed the 'index.max_result_window' to 1,000,000 by this:
```
PUT _all/_settings?preserve_existing=true'
{
  "index.max_result_window" : "10000000"
}
```
The response:
```
{
  "acknowledged": true
}
```
Actually, I donot need deep-scroll. So I try to modify the "index.max_result_window" to 10,000,000 and It returns:
```
{
  "acknowledged": true
}
```
But it is still 1,000,000:
`GET _all/_settings`
```
{
...
    "max_result_window": "1000000",
...
    "max_result_window": "1000000",
...
}
```
And it didnt work for search by using `"from": 10000000, "size": 1`.I found that I could not even change its value any more.How can I do this?

**Comment by tonyjames3212** [comment]
Anyone have any ideas?

**Comment by cbuescher** [comment]
Works for me if you don't use `preserve_existing=true` when you try to reset the value. Also, please note that Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions like this.

**Comment by shmera55** [comment]
PUT _all/_settings?preserve_existing=true'
{
  "index.max_result_window" : "10000000"
}

Above Line how to write in C# 

Please Help Me & Thanks !!!

**Comment by cbuescher** [comment]
@shmera55 Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests.
