### ISSUE TITLE
Protection or diagnostics for stuck thread pool

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#23524]
We ran into a situation where the generic thread pool appears to have been filled with tasks that were stuck (perhaps indefinitely).

We were able to submit new tasks (forever, the queue is unbounded) but they weren't ever going to run, and there was no easy way of diagnosing that problem (in code, or via logs)

At the very least something in the logs for "thread pool is overloaded and not progressing" would help support detect the problem when it occurs, but it would be great if we could do something more than that.

CC @jaymode

**Comment by jasontedor** [comment]
What version is this? How many cores did the machine have? What is the stack trace of the stuck tasks? Why is the output of `/_nodes/stats/thread_pool` not enough?

**Comment by tvernum** [comment]
It's 5.2.2

Once we worked out that it was a threadpool issue we were able to diagnose and repair.  
The place where we were spinning our wheels was working out that the problematic behaviour we was seeing was caused by thread tasks not executing.

**Comment by jasontedor** [comment]
I think we can close this, I think that diagnostics from `/_nodes/stats/thread_pool` are sufficient and I'm hesitant to add log messages that no one reads.
