### ISSUE TITLE
[doc] Font too tiny for long reading

### ISSUE THREAD

**Issue by lukas-vlcek** [elastic/elasticsearch#23535]
Hi,

I don't know if this is just on my side but the online documentation seems to be using quite tiny font face now. IMHO this is step back, especially for people with impaired vision.

Attaching screenshots to compare L&F _yesterday_ vs _today_.

Yesterday:

<img width="1148" alt="screen shot 2017-03-10 at 11 13 17" src="https://cloud.githubusercontent.com/assets/205174/23791344/da444b2a-0582-11e7-9e9c-19306cb2c414.png">

Today:

<img width="1149" alt="screen shot 2017-03-10 at 11 13 41" src="https://cloud.githubusercontent.com/assets/205174/23791354/e5d659d8-0582-11e7-892b-97197289fcbb.png">

Yesterday:

<img width="1146" alt="screen shot 2017-03-10 at 11 13 59" src="https://cloud.githubusercontent.com/assets/205174/23791379/fbd27884-0582-11e7-8c6e-a513a89dd0e1.png">

Today:

<img width="1145" alt="screen shot 2017-03-10 at 11 14 13" src="https://cloud.githubusercontent.com/assets/205174/23791386/01fa0880-0583-11e7-9b6d-444660e52613.png">

**Comment by dadoonet** [comment]
I don't see any difference on my side. Did you change your browser zoom settings to 90% by any chance ?

**Comment by lukas-vlcek** [comment]
@dadoonet You still see what I call "yesterday" view?
I did not change anything. I had couple of older browser tabs opened with "yesterday" view. After I hit reload the new version come up.

**Comment by lukas-vlcek** [comment]
@dadoonet Above screenshots were taken from Chrome. I tried to open online doc in Safari now (which I normally don't use for ES online doc viewing) and I am getting similar tiny font face. So this is probably not result of misconfiguration of particular browser instance.

**Comment by lukas-vlcek** [comment]
It is strange, it seems as if `font-weight: 400;` is not applied and `font-weight: 300;` is used instead. I do not know... may be the data for font weight 400 were not loaded?

**Comment by dadoonet** [comment]
Here is what I'm seeing today on Chrome

![image](https://cloud.githubusercontent.com/assets/274222/23802279/a777f978-0567-11e7-82c3-625d3880e2a4.png)

But as we are using a CDN AFAIK, may be there is some propagation issues?

FWIW I'm going to ping the content team to look at it.

**Comment by lukas-vlcek** [comment]
It seems something has changed. I no longer see the super tiny font, it is much more readable now. Very close to what it was before. Except the code syntax highlighting is gone ATM, but that is probably another issue. I am closing the ticket.

Example 1):
![screen shot 2017-05-31 at 13 10 52](https://cloud.githubusercontent.com/assets/205174/26629484/ebd4824a-4602-11e7-8ff6-67b6d6fb6486.png)

Example 2):
![screen shot 2017-05-31 at 13 09 22](https://cloud.githubusercontent.com/assets/205174/26629486/ef35b47c-4602-11e7-96ba-48a258e2ecbf.png)
