### ISSUE TITLE
Add APIs to support custom GeoPoint encodings and aggregation  

### ISSUE THREAD

**Issue by FrankXia** [elastic/elasticsearch#23530]
**Describe the feature**:

Please add an extensible mechanism/API to GeoPoint field mapper so that developers can add their own encodings with the latitude/longitude data and related API to aggregation framework so that those custom encodings could be used for multi-bucket aggregation. 

1. The first part of the request is to make it possible for developers to add custom latitude/longitude based encodings without duplicating the GeoPoint data. 

2. The second part of the request is to make those custom encodings usable in the Elasticsearch aggregation framework without duplicating codes of GeoHash_Grid based aggregation with minor changes.

**Comment by jpountz** [comment]
What would be the benefits of using a different encoding?

**Comment by FrankXia** [comment]
To visualize geospatial data in a spatial reference system other than WGS84 with a regular grid such as square and hexagon.

**Comment by polyfractal** [comment]
@nknize thoughts on this one?

**Comment by rjernst** [comment]
We discussed this in FixItThursday, and we think this is an extremely advanced use case which does not warrant an extension point. It would require re-opening up the system to custom codecs, which we previously had and removed. If there are changes that would allow improvements to the use case described here, they should be proposed and made in Lucene.
