### ISSUE TITLE
Polygon aggregation

### ISSUE THREAD

**Issue by FrankXia** [elastic/elasticsearch#23531]
**Describe the feature**:

We are requesting a new type of aggregation that would aggregate GeoPoint/GeoShape docs from an index into a multi-bucket return based on a set of polygons from another index.

**Comment by jpountz** [comment]
I think it would work today already if you run a `filters` aggregation against `geo_shape` filters? cc @nknize

**Comment by FrankXia** [comment]
Yes, I am aware of the solution using geo_shapes as filters. However, the use cases we have are much more complicated and the number of polygons/geo_shapes could be easily over 10s of thousands and even millions.

**Comment by colings86** [comment]
As @jpountz mentions this can be done with a filters aggregation. I don't think there is much that we could do that would improve the performance over what the filters aggregation would provide
