### ISSUE TITLE
why did same text get different _score?

### ISSUE THREAD

**Issue by zpzkit** [elastic/elasticsearch#23534]
### _**

**Elasticsearch version*2.3.3*:

**Plugins installed**: [head,ik]

**JVM version*openjdk version "1.8.0_111"*:

**OS version*CentOS release 6.8 (Final)*:

+++++++++++++++++++++++++++++++++++++++++
my mapping：
"mappings": {
  "weixinMedia": {
  "_all": {
  "analyzer": "ik_max_word"
},
  "properties": {
  "mediaScore": {
  "type": "float"
},
  "weixinId": {
  "type": "string"
},
  "pi": {
  "type": "long"
},
  "mediaNameLen": {
  "type": "integer"
},
  "pmid": {
  "index": "not_analyzed",
  "type": "string"
},
  "mediaName": {
  "analyzer": "ik_max_word",
  "term_vector": "with_positions_offsets",
  "boost": 2,
  "type": "string"
}
}
},
+++++++++++++++++++++++++++++++++++++++++
my request:
{
  "track_scores" : "true",
  "sort" : {
        "_script" : {
            "type" : "number",
            "script" : "_score+(doc.pi.value/100.0)",
            "order" : "desc"
        }
    },
      "query" : {
        "match_phrase" : { "mediaName" : "微美食" }
    }
}
+++++++++++++++++++++++++++++++++++++++++
expect result:
 {
      "_index" : "media_b",
      "_type" : "weixinMedia",
      "_id" : "MzA5NTgyOTUyNA==",
      "_score" : 17.916512,
      "_source" : {
        "mediaName" : "微美食",
        "pmid" : "MzA5NTgyOTUyNA==",
        "mediaNameLen" : 3,
        "mediaScore" : 2.2,
        "pi" : 600
      },
      "sort" : [ 23.91651153564453 ]
    }, {
      "_index" : "media_b",
      "_type" : "weixinMedia",
      "_id" : "MjM5NzMxOTM4MQ==",
      "_score" : 17.916512,
      "_source" : {
        "mediaName" : "微美食",
        "pmid" : "MjM5NzMxOTM4MQ==",
        "mediaNameLen" : 3,
        "mediaScore" : 2.062,
        "pi" : 506
      },
      "sort" : [ 22.97651153564453 ]
    }, {
      "_index" : "media_b",
      "_type" : "weixinMedia",
      "_id" : "MjM5OTg0OTcwMg==",
      "_score" : 17.916512,
      "_source" : {
        "mediaName" : "微美食西安",
        "pmid" : "MjM5OTg0OTcwMg==",
        "mediaNameLen" : 5,
        "mediaScore" : 2.308,
        "pi" : 629
      },
      "sort" : [ 24.20651153564453 ]
    },
+++++++++++++++++++++++++++++++++++++++++

actual result with explain:
{
      "_shard" : 4,
      "_node" : "uSTOGHNUSjGNFweC7RynRQ",
      "_index" : "media_b",
      "_type" : "weixinMedia",
      "_id" : "MjM5OTg0OTcwMg==",
      "_score" : 17.916512,
      "_source" : {
        "mediaName" : "微美食西安",
        "pmid" : "MjM5OTg0OTcwMg==",
        "mediaNameLen" : 5,
        "mediaScore" : 2.308,
        "pi" : 629
      },
      "sort" : [ 24.20651153564453 ],
      "_explanation" : {
        "value" : 17.916512,
        "description" : "sum of:",
        "details" : [ {
          "value" : 17.916512,
          "description" : "weight(mediaName:\"微 美食 食\" in 161368) [PerFieldSimilarity], result of:",
          "details" : [ {
            "value" : 17.916512,
            "description" : "fieldWeight in 161368, product of:",
            "details" : [ {
              "value" : 1.0,
              "description" : "tf(freq=1.0), with freq of:",
              "details" : [ {
                "value" : 1.0,
                "description" : "phraseFreq=1.0",
                "details" : [ ]
              } ]
            }, {
              "value" : 17.916512,
              "description" : "idf(), sum of:",
              "details" : [ {
                "value" : 4.92588,
                "description" : "idf(docFreq=9932, maxDocs=503580)",
                "details" : [ ]
              }, {
                "value" : 7.0545344,
                "description" : "idf(docFreq=1181, maxDocs=503580)",
                "details" : [ ]
              }, {
                "value" : 5.9360976,
                "description" : "idf(docFreq=3616, maxDocs=503580)",
                "details" : [ ]
              } ]
            }, {
              "value" : 1.0,
              "description" : "fieldNorm(doc=161368)",
              "details" : [ ]
            } ]
                      } ]
        }, {
          "value" : 0.0,
          "description" : "match on required clause, product of:",
          "details" : [ {
            "value" : 0.0,
            "description" : "# clause",
            "details" : [ ]
          }, {
            "value" : 0.055814438,
            "description" : "_type:weixinMedia, product of:",
            "details" : [ {
              "value" : 1.0,
              "description" : "boost",
              "details" : [ ]
            }, {
              "value" : 0.055814438,
              "description" : "queryNorm",
              "details" : [ ]
            } ]
          } ]
        } ]
      }
    }, {
      "_shard" : 3,
      "_node" : "uSTOGHNUSjGNFweC7RynRQ",
      "_index" : "media_b",
      "_type" : "weixinMedia",
      "_id" : "MzA5NTgyOTUyNA==",
      "_score" : 17.796759,
      "_source" : {
        "mediaName" : "微美食",
        "pmid" : "MzA5NTgyOTUyNA==",
        "mediaNameLen" : 3,
        "mediaScore" : 2.2,
        "pi" : 600
      },
            "sort" : [ 23.7967586517334 ],
      "_explanation" : {
        "value" : 17.796759,
        "description" : "sum of:",
        "details" : [ {
          "value" : 17.796759,
          "description" : "weight(mediaName:\"微 美食 食\" in 120379) [PerFieldSimilarity], result of:",
          "details" : [ {
            "value" : 17.796759,
            "description" : "score(doc=120379,freq=1.0), product of:",
            "details" : [ {
              "value" : 0.99999994,
              "description" : "queryWeight, product of:",
              "details" : [ {
                "value" : 17.79676,
                "description" : "idf(), sum of:",
                "details" : [ {
                  "value" : 4.93295,
                  "description" : "idf(docFreq=10996, maxDocs=561478)",
                  "details" : [ ]
                }, {
                  "value" : 6.9785085,
                  "description" : "idf(docFreq=1421, maxDocs=561478)",
                  "details" : [ ]
                }, {
                  "value" : 5.885302,
                  "description" : "idf(docFreq=4242, maxDocs=561478)",
                  "details" : [ ]
                } ]
              }, {
                "value" : 0.05619,
                "description" : "queryNorm",
                "details" : [ ]
              } ]
            }, {
              "value" : 17.79676,
              "description" : "fieldWeight in 120379, product of:",
              "details" : [ {
                "value" : 1.0,
                "description" : "tf(freq=1.0), with freq of:",
                "details" : [ {
                  "value" : 1.0,
                  "description" : "phraseFreq=1.0",
                  "details" : [ ]
                } ]
              }, {
                "value" : 17.79676,
                "description" : "idf(), sum of:",
                "details" : [ {
                  "value" : 4.93295,
                  "description" : "idf(docFreq=10996, maxDocs=561478)",
                  "details" : [ ]
                }, {
                  "value" : 6.9785085,
                  "description" : "idf(docFreq=1421, maxDocs=561478)",
                  "details" : [ ]
                }, {
                  "value" : 5.885302,
                  "description" : "idf(docFreq=4242, maxDocs=561478)",
                                    "details" : [ ]
                } ]
              }, {
                "value" : 1.0,
                "description" : "fieldNorm(doc=120379)",
                "details" : [ ]
              } ]
            } ]
          } ]
        }, {
          "value" : 0.0,
          "description" : "match on required clause, product of:",
          "details" : [ {
            "value" : 0.0,
            "description" : "# clause",
            "details" : [ ]
          }, {
            "value" : 0.05619,
            "description" : "_type:weixinMedia, product of:",
            "details" : [ {
              "value" : 1.0,
              "description" : "boost",
              "details" : [ ]
            }, {
              "value" : 0.05619,
              "description" : "queryNorm",
              "details" : [ ]
            } ]
          } ]
        } ]
      }
    }, {
      "_shard" : 4,
      "_node" : "uSTOGHNUSjGNFweC7RynRQ",
      "_index" : "media_b",
      "_type" : "weixinMedia",
      "_id" : "MjM5NzMxOTM4MQ==",
      "_score" : 17.916512,
      "_source" : {
        "mediaName" : "微美食",
        "pmid" : "MjM5NzMxOTM4MQ==",
        "mediaNameLen" : 3,
        "mediaScore" : 2.062,
        "pi" : 506
      },
      "sort" : [ 22.97651153564453 ],
      "_explanation" : {
        "value" : 17.916512,
        "description" : "sum of:",
        "details" : [ {
          "value" : 17.916512,
          "description" : "weight(mediaName:\"微 美食 食\" in 364138) [PerFieldSimilarity], result of:",
                    "details" : [ {
            "value" : 17.916512,
            "description" : "fieldWeight in 364138, product of:",
            "details" : [ {
              "value" : 1.0,
              "description" : "tf(freq=1.0), with freq of:",
              "details" : [ {
                "value" : 1.0,
                "description" : "phraseFreq=1.0",
                "details" : [ ]
              } ]
            }, {
              "value" : 17.916512,
              "description" : "idf(), sum of:",
              "details" : [ {
                "value" : 4.92588,
                "description" : "idf(docFreq=9932, maxDocs=503580)",
                "details" : [ ]
              }, {
                "value" : 7.0545344,
                "description" : "idf(docFreq=1181, maxDocs=503580)",
                "details" : [ ]
              }, {
                "value" : 5.9360976,
                "description" : "idf(docFreq=3616, maxDocs=503580)",
                "details" : [ ]
              } ]
            }, {
              "value" : 1.0,
              "description" : "fieldNorm(doc=364138)",
              "details" : [ ]
            } ]
          } ]
        }, {
          "value" : 0.0,
          "description" : "match on required clause, product of:",
          "details" : [ {
            "value" : 0.0,
            "description" : "# clause",
            "details" : [ ]
          }, {
            "value" : 0.055814438,
            "description" : "_type:weixinMedia, product of:",
            "details" : [ {
              "value" : 1.0,
              "description" : "boost",
              "details" : [ ]
            }, {
              "value" : 0.055814438,
              "description" : "queryNorm",
              "details" : [ ]
            } ]
          } ]
        } ]
      }
    },
+++++++++++++++++++++++++++++++++++++++++
I don't know why the same word with different _score and the first one is not precise matching.Did I have some error or the plugin of ik is not precision?

thanks!

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by zpzkit** [comment]
ok! Thank you for reminding me！
