### ISSUE TITLE
Additional Bootstrap Check for node.max_local_storage_nodes

### ISSUE THREAD

**Issue by tylerfontaine** [elastic/elasticsearch#23541]
**Describe the feature**:

Currently, we don't require a setting for node.max_local_storage_nodes, which defaults to 50, which would allow 50 instances to create sub-directories in a single data path.

In production, an errant script, or simply performing actions out of order could cause a second node to be started, which 1) has the same node name 2) creates this second directory under path.data

If this happens more than once, you're in a situation where you have to be very careful about how you shut them down, and mitigation is a little painful, since you have to stop it, start it with a new name (since there is no option to exclude by ID, nor could you exclude by IP, since both nodes on that host will share the ID), exclude it from allocation to empty it, etc.

Further, it could potentially go unnoticed for long enough that it leads to disks filling up, or other performance issues.

I would propose that we add a bootstrap check, when bound to something other than localhost, that requires this setting be set explicitly, to avoid this situation from happening accidentally.

**Comment by dadoonet** [comment]
The default value is 1 AFAIK.

**Comment by jasontedor** [comment]
> Currently, we don't require a setting for node.max_local_storage_nodes, which defaults to 50, which would allow 50 instances to create sub-directories in a single data path.

This part is not accurate, we changed `node.max_local_storage_nodes` in #19964 for 5.0.0 so that it defaults to one.

**Comment by tylerfontaine** [comment]
++ thanks Sorry for noise :)
