### ISSUE TITLE
Missing mapping for nested dynamic field results in error "failed to find nested object under path"

### ISSUE THREAD

**Issue by shunitben** [elastic/elasticsearch#23551]
**Elasticsearch version**: 2.3.4

**Plugins installed**: none

**JVM version**: java version "1.8.0_65"

**OS version**: Mac OSX el capitan

**Description of the problem including expected versus actual behavior**:

We have items in our system, and each item can have translations. A translation may contain these fields: name, teaser, tags. We have a dynamic list of languages, so we map the translations fields dynamicly.

The elastic index mapping defines dynamic templates, which have definitions for regular string fields, and for nested "tags" fields:

      "dynamic_templates": [
        {
          "tags": {
            "mapping": {
              "type": "nested",
              "properties": {
                "name": {
                  "type": "string"
                },
                "weight": {
                  "type": "integer"
                }
              }
            },
            "path_match": "translations.*.tags"
          }
        },
  	  	... [strings dynamic mapping]
      ]
	  
	  
When documents are added to the index, this results in such mappings:
	  
      "properties": {
	    ...
        "translations": {
          "properties": {
            "fr": {
              "properties": {
                "name": {
                  "type": "string",
                  "fields": {
                    "raw_lowercase": {
                      "type": "string",
                      "analyzer": "raw_lowercase"
                    }
                  },
                  "analyzer": "standard-stopwords"
                },
                "tags" : {
                  "type": "nested",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "weight": {
                      "type": "integer"
                    }
                  }
                }
              }
            },
			...[other langs]
          }
        }
      }
	  
Our issue is when querying in languages where a document that contains these fields hasn't yet been added for a specific language.
For example, if I've only added one document with a russian translation, and this russian translation only has a name (no teaser or tags fields), then the resulting mapping for russian will look like this:

            "ru": {
              "properties": {
                "name": {
                  ...
                }
              }
            }

If I then run a query that uses translations.ru.tags, I get the following error:

	failed to find nested object under path [translations.ru.tags]  

However, a query using translations.ru.teaser is perfectly fine - it does not complain, but of course, it won't return any results.

We would expect nested fields to be ignored in the same way as regular string fields, or to have some flag that would allow this behavior. Is there such a thing? We couldn't find it.

**Comment by jpountz** [comment]
Here is a recreation of the problem:

```
DELETE index 

PUT index
{
  "mappings": {
    "_doc": {
      "dynamic_templates": [
        {
          "tags": {
            "mapping": {
              "type": "nested",
              "properties": {
                "name": {
                  "type": "keyword"
                },
                "weight": {
                  "type": "integer"
                }
              }
            },
            "path_match": "translations.*.tags"
          }
        }
      ]
    }
  }
}

PUT index/_doc/1
{
  "translations": {
    "fr": {
      "name": "foo",
      "tags": [
        {
          "name": "baz",
          "weight": 4
        },
        {
          "name": "quux",
          "weight": 2
        }
      ]
    }
  }
}

PUT index/_doc/2
{
  "translations": {
    "ru": {
      "name": "bar"
    }
  }
}

GET index/_search
{
  "query": {
    "nested": {
      "path": "translations.ru.tags",
      "query": {
        "match": {
          "translations.ru.tags.name": "quux"
        }
      }
    }
  }
}
```

This can be worked around by slightly changing the dynamic mapping rules:

```
DELETE index 

PUT index
{
  "mappings": {
    "_doc": {
      "dynamic_templates": [
        {
          "tags": {
            "mapping": {
              "type": "nested",
              "properties": {
                "name": {
                  "type": "keyword"
                },
                "weight": {
                  "type": "integer"
                }
              }
            },
            "path_match": "translations.*.tags"
          }
        }
      ]
    }
  }
}

PUT index
{
  "mappings": {
    "_doc": {
      "dynamic_templates": [
        {
          "lang": {
            "mapping": {
              "properties": {
                "tags": {
                  "type": "nested",
                  "properties": {
                    "name": {
                      "type": "keyword"
                    },
                    "weight": {
                      "type": "integer"
                    }
                  }
                }
              }
            },
            "path_match": "translations.*"
          }
        }
      ]
    }
  }
}

PUT index/_doc/1
{
  "translations": {
    "fr": {
      "name": "foo",
      "tags": [
        {
          "name": "baz",
          "weight": 4
        },
        {
          "name": "quux",
          "weight": 2
        }
      ]
    }
  }
}

PUT index/_doc/2
{
  "translations": {
    "ru": {
      "name": "bar"
    }
  }
}

GET index/_search
{
  "query": {
    "nested": {
      "path": "translations.ru.tags",
      "query": {
        "match": {
          "translations.ru.tags.name": "quux"
        }
      }
    }
  }
}
```
