### ISSUE TITLE
Reindex: push execution of sliced requests to data nodes if possible

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#23560]
Reindex supports [`slice`](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex-automatic-slice) to parallelize it's process. If you pick the appropriate number of slices then it'd be possible to move execution of the entire slice from the coordinating node to the data node. This should save some network traffic.

**Comment by bleskes** [comment]
@nik9000 is this still on your radar? is it worth the complexity?

**Comment by nik9000** [comment]
> @nik9000 is this still on your radar?

No.

> is it worth the complexity?

I don't know. It'd save a little bit of network traffic. Reindex is built to allow this so it shouldn't be *too* hard.

**Comment by bleskes** [comment]
I'm closing this for now. The reindexing infra needs to go through a re-write to use seq# and the persistent tasks. We should look if that's is interesting to pursue (I have my doubts, would love to see some concrete hard evidence) one we know how the new code looks like and what the implications are.
