### ISSUE TITLE
IndicesQueryCache consume a lot of memory

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#23564]
Elasticsearch version:
2.1
Plugins installed: []
delete-by-query
elasticsearch-analysis-ik
repository-hdfs
JVM version:
jdk1.8.0_60
OS version:
CentOS Linux release 7.1.1503

Description of the problem including expected versus actual behavior:
the server is out of memory and heap dump is below:
https://github.com/makeyang/grocery/blob/master/indicesquerycache.png

below is config:
indices.memory.index_buffer_size: 40%
index.translog.sync_interval: 30s
index.translog.durability: async
indices.fielddata.cache.size: 20%
index.queries.cache.everything: true
index.requests.cache.enable: true
indices.requests.cache.size: 10%
index.store.type: mmapfs
indices.cache.filter.size: 10%
threadpool.search.size: 512

so my question is:
is this the leak caused by https://issues.apache.org/jira/browse/LUCENE-7657 or is it becase 
https://github.com/elastic/elasticsearch/issues/18161, which is search thread too many?

**Comment by jasontedor** [comment]
You have set the search thread pool to have size 512 so I think that this duplicates #18161.

Either way, we provide the [forums](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. If you have follow-up questions, would you please ask them there?
