### ISSUE TITLE
ElasticSearch on Docker Swarm Bound or publish to a non-loopback or non-local address strap check fail.

### ISSUE THREAD

**Issue by rommik** [elastic/elasticsearch#23569]
I'm trying to setup ElasticSearch and Kibana on Docker Swarm. Nothing fancy, just two services linked by a common overlay network. However, ElasticSearch fails to run and I get the following error in the logs:

{"log":"[2017-03-13T20:21:24,770][WARN ][i.n.u.i.MacAddressUtil   ] Failed to find a usable hardware address from the network interfaces; using random bytes:
 e7:ea:87:86:44:61:22:b0\n","stream":"stdout","time":"2017-03-13T20:21:24.771125868Z"}
{"log":"[2017-03-13T20:21:24,888][INFO ][o.e.t.TransportService   ] [hiKddpp] publish_address {10.0.50.2:9300}, bound_addresses {[::]:9300}\n","stream":"stdo
ut","time":"2017-03-13T20:21:24.889167419Z"}
{"log":"[2017-03-13T20:21:24,901][INFO ][o.e.b.BootstrapChecks    ] [hiKddpp] bound or publishing to a non-loopback or non-link-local address, enforcing boot
strap checks\n","stream":"stdout","time":"2017-03-13T20:21:24.901545734Z"}

What is the reason for the strap check to fail?

example of my swarm stack file:

version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    volumes:
      - elasticData:/usr/share/elasticsearch/data
    networks:
      monitoring:
    deploy:
      placement:
         constraints:
           - node.hostname == swarm-node-monitor
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.1
    environment:
     - ELASTICSEARCH.URL=http://elasticsearch:9200
    networks:
      monitoring:
      proxy:
    deploy:
      placement:
         constraints:
           - node.hostname == swarm-node-monitor
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=kibana.my-domain.com
        - com.df.servicePath=/
        - com.df.port=5601
        - com.df.httpsOnly=true
volumes:
   elasticData:
     driver: local

networks:
  proxy:
    external: true
  monitoring:
    driver: overlay
    external: false

**Comment by jasontedor** [comment]
> What is the reason for the strap check to fail?

If there are failing bootstrap checks, they will be after the log line that you showed. You should read these looks and address the issues that they present.

Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
