### ISSUE TITLE
Return whether a new index was created when indexing a document

### ISSUE THREAD

**Issue by mjustin** [elastic/elasticsearch#23570]
**Describe the feature**:
Return whether a new index was created when indexing a document (as well as the index name, per  #23044).

I'm working in an application that is dynamically creating new indexes (based on an index template and a predictable and consistent index naming scheme).  There are certain things it would like to do when new indexes are created; however, Elasticsearch doesn't indicate whether an indexing action has resulted in the creation of a new index.  Therefore the client would have to check if the index exists prior to each indexing operation, or possibly have a scheduled task check for any new indexes that didn't previously exist.

A more natural seeming solution would be if the app could check the response to see whether an index were created as part of the indexing action.  This also seems like something that would be generally useful to be able to know when indexing a document.

**Comment by olcbean** [comment]
If OK I would like to give it a try.

**Comment by bleskes** [comment]
> There are certain things it would like to do when new indexes are created; 

@mjustin can you clarify what those things are? I want to double check that they are based implemented by listening to indexing operations.

**Comment by jasontedor** [comment]
@olcbean Before spending too much time on this, we have not come to a decision whether or not this feature should be implemented. I think we need to understand the use-case better, as evidenced by the questions that @bleskes has asked already.

**Comment by jasontedor** [comment]
No additional feedback, closing.
