### ISSUE TITLE
How to search two fields has the same value

### ISSUE THREAD

**Issue by kevin-tang-rs** [elastic/elasticsearch#23578]
There are two fields, id_cur and id_steady, i hope to query the content which id_cur == id_steady, how to implement, thank you

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
