### ISSUE TITLE
How to send data to external data storage e.g. elastic search?

### ISSUE THREAD

**Issue by JenifferWuUCLA** [elastic/elasticsearch#23576]
How to send web form's data to external data storage e.g. elastic search? Would you pls help to give me some code demos to follow?

Thanks!

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
