### ISSUE TITLE
geo_shape "contains" relation is backwards - should be "within"

### ISSUE THREAD

**Issue by IamJeffG** [elastic/elasticsearch#2358]
I don't want to bikeshed, but I believe the "contains" relation in geo_shape queries and filters does the opposite of what "contains" means in GIS circles.  Rather, the relation actually performs a "within".

The confusion comes from the fact that the DSL is not explicit about how the query/filter should be read.  Compare:
* "Give me all results where the indexed document's shape contains this filter shape."
* "Give me all results where this filter shape contains the indexed document's shape."

The Elasticsearch DSL does have some precedent for the ordering, specifically that they should be read as in the first ordering (indexed documents are the subject, query terms are the sentence's object).  For example, the "has_child" filter's behavior "Gives all results where the indexed (parent) document has_(a)_child matching the query."

Observe that the commonly accepted spatial relation semantics (e.g. http://en.wikipedia.org/wiki/DE-9IM) assert that "A contains B" is equivalent to "B within A".

For the Elasticsearch DSL to be both self-consistent and correct, the [currently implemented behavior](http://www.elasticsearch.org/guide/reference/query-dsl/geo-shape-filter.html)
> Finds those indexed shapes which are fully contained within the filter shape. Any shapes will additional area outside of the filter shape are excluded.

should instead be named "within".  In fact, you used the word "within" to define the "contains" relationship.  The relationship you describe is indeed "within".

By contrast, a true "contains" relationship would have been defined like so:
> contains – Finds those indexed shapes that contain the filter shape.  The filter shape will not contain any points outside the shapes returned.

It would be great to rename this predicate now while 0.20 is brand new and you've still listed it as "experimental", before the wrong semantics catch on and confusion begins.

**Comment by clintongormley** [comment]
@nknize could you add some docs for `relation` and `strategy` to the geoshape query please?

**Comment by zia-m** [comment]
### ### ### ### ### ### _**edADSadsADSasdASD**_
