### ISSUE TITLE
query dsl whith regexp bug?

### ISSUE THREAD

**Issue by authasme** [elastic/elasticsearch#23587]
**Elasticsearch version**:2.1

**Plugins installed**: []

**JVM version**:1.7

**OS version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:
I used "query dsl" whith regexp, it returned nothing when fields contains "\s，\n .etc" , how can I do?

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
