### ISSUE TITLE
How does the best_compression work after I setting it?

### ISSUE THREAD

**Issue by darouwan** [elastic/elasticsearch#23586]
I am working on index compression currently. Now I have existed index about 500MB to be compressed, but I meet the following questions:
1. When does the best_compression work after I setting it? Immidieately or after a while? 
2. Does it work on existed index or the upcoming index data? Or both? 
3. Have the index data been compressed by LZ4 if I don't set the index.codec ?

Thanks.

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
