### ISSUE TITLE
Feature request: more geo aggregation stats and/or metrics

### ISSUE THREAD

**Issue by cmk1523** [elastic/elasticsearch#23584]
I'd love to see statistics (i.e. standard deviation) of a set of geo points.  The geo_centroid aggregation is a first step, however there's more stats that can be calculated.

I'd also like to see statistics about a geo_bounds result (i.e. size of the bounds/window in meters). If anyone knows how to script that, please let me know!

**Comment by nknize** [comment]
related to #14727, #11460

**Comment by eskibars** [comment]
Hey @cmk1523 -- I'm curious if you have specific statistics you'd like to see and any background on them?

**Comment by cmk1523** [comment]
Geovariance and ranges would be nice. Geovarinace could possibly help in determining if something is moving or not. Perhaps this stuff: https://www.mathworks.com/help/stats/geostat.html

**Comment by eskibars** [comment]
Thanks.  Do you have some specific use cases in mind that you could share?

**Comment by polyfractal** [comment]
I'm going to close this in favor of https://github.com/elastic/elasticsearch/issues/14727.  That issue is sort of the superset of "advanced stats on geo", which would encompass functionality like this.
