### ISSUE TITLE
Should IP range aggregation have an option to automatically group into "classful addressing" buckets?

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#23589]
Sometimes it is useful to think in terms of [classful addressing](https://en.wikipedia.org/wiki/Classful_network#Classful_addressing_definition), grouping IPs into their traditional groups based on prefix. Should the IP range aggregation support an option to do this? Or maybe we should document a painless script to do this?

Example:

IP | Bucket
--:|:---
5.0.1.7 | 5.0.0.0/8 
5.123.5.1 | 5.0.0.0/8
195.12.1.234 | 195.12.1/24

**Comment by jasontedor** [comment]
Classful addressing is mostly dead, replaced by CIDR instead. The significance of the defined classes is largely irrelevant these days. I do not think we should add something to core for this since it can be done in scripting if needed.

**Comment by javanna** [comment]
@nik9000 given what Jason said I would be leaning towards closing this as won't fix. Hope you don't mind.
