### ISSUE TITLE
Reindex: illegal_argument_exception "mapper [xxx] of different type".  int/str coercion not performed and ignore_malformed not respected

### ISSUE THREAD

**Issue by dseeley** [elastic/elasticsearch#23608]
**Elasticsearch version**: 5.2.2

**Plugins installed**: []

**JVM version**: 1.8.0_121

**OS version**: Centos 7.3.1611

**Description of the problem including expected versus actual behavior**:

When batch/scroll size is greater than 1, reindexing does not perform type coercion from int to str.  It also does not respect the ignore_malformed directive on the destination index mapping. 
1. If a type is mapped as a string type, and a document is sent that has an integer as that type, reindexing fails (where the original indexing process had coerced it into a string).  
1. If a type is mapped as an integer type, and a document is sent that has an string as that type, reindexing fails (where the original indexing process had not indexed the field due to ignore_malformed)

Presumably this happens when a batch contains conflicting types.  Setting the batch/scroll size to 1 fixes this, but is not viable for reindexing large indexes.

**Steps to reproduce**:

The order that the reindex picks the documents from the source doesn't appear to be deterministic, but one of the issues above is seen by the following:

```
curl -XDELETE 'localhost:9200/reindextestsrc'
curl -XDELETE 'localhost:9200/reindextestdest'

curl -XPUT 'localhost:9200/reindextestsrc?pretty' -d'{
  "settings": {
    "index.mapping.ignore_malformed": true,
    "index.mapping.coerce": true
  },
  "mappings": {
    "_default_": { "numeric_detection": true }
  }
}'

curl -XPUT 'localhost:9200/reindextestdest?pretty' -d'{
  "settings": {
    "index.mapping.ignore_malformed": true,
    "index.mapping.coerce": true
  },
  "mappings": {
    "_default_": { "numeric_detection": true }
  }
}'

curl -XPUT 'localhost:9200/reindextestsrc/person/1' -d '{
    "name": "Fred",
    "age": "unknown"
}'

curl -XPUT 'localhost:9200/reindextestsrc/person/2' -d '{
    "name": "John",
    "age": 25
}'

curl -XPUT 'localhost:9200/reindextestsrc/person/3' -d '{
    "name": "Jim",
    "age": "unknown"
}'
```

Then attempt a reindex:
```
curl -XPOST 'localhost:9200/_reindex?pretty' -H 'Content-Type: application/json' -d'
{
  "conflicts": "proceed",
  "source": {
    "index": "reindextestsrc",
    "size": 1000,
    "sort": "_uid"
  },
  "dest": {
    "index": "reindextestdest"
  }
}
'
```

***Response:***
```
{
  "took" : 32,
  "timed_out" : false,
  "total" : 3,
  "updated" : 0,
  "created" : 2,
  "deleted" : 0,
  "batches" : 1,
  "version_conflicts" : 0,
  "noops" : 0,
  "retries" : {
    "bulk" : 0,
    "search" : 0
  },
  "throttled_millis" : 0,
  "requests_per_second" : -1.0,
  "throttled_until_millis" : 0,
  "failures" : [
    {
      "index" : "reindextestdest",
      "type" : "person",
      "id" : "3",
      "cause" : {
        "type" : "illegal_argument_exception",
        "reason" : "mapper [age] of different type, current_type [long], merged_type [text]"
      },
      "status" : 400
    }
  ]
}
```

By setting _size_ to 1, the reindex succeeds, but this is not viable on sizeable indexes.

**Comment by nik9000** [comment]
I've seen this when you create a new index using reindex without setting up the types first. Elasticsearch is using its standard type inference mechanisms and reindex exposes the problems with it more quickly then normal operations. My guess is you have `age` fields in your source that look like `11` and that look like `"11"`. If the `11` hits first then Elasticsearch will infer the type of the field is `long`. If the `"11"` hits first then Elasticsearch will infer that they type is `text`. If they hit at the same time then you'll get the error you got. Is this what happened to you?

There is a section at the top of the reindex documentation marked `IMPORTANT` that advises you to set up the target index first yourself. Do you have any ideas on other places to put this documentation so it is more visible?

**Comment by dseeley** [comment]
This is just a simple illustrative example.  The actual index I am having problems with uses dynamic templates, and the resultant mapping is thousands of lines long.  It is not practical to set it up manually beforehand.  On reindex, the target index assumes the correct template (same as the source), which uses dynamic field mappings, and correctly interprets the first 1.6 million documents, but then comes across a new document type with conflicting field types and fails as per the example.

I believe it is failing because a scan/scroll batch contains multiple documents with 'age' fields that are interpreted as different types.  I would expect that once the first document from the batch has been indexed, the index has this type set for the field; any subsequent indexing of that field with a differing type should be either ignored or coerced.  When the batch size is set to 1, the problem goes away, but this is not a practical solution (far too slow).

**Comment by clintongormley** [comment]
> The actual index I am having problems with uses dynamic templates, and the resultant mapping is thousands of lines long. It is not practical to set it up manually beforehand.

You can set it up manually very easily, by retrieving the mapping from the old index and passing it as a parameter to the create-index command.

Your fields are mapped as they are because of chance ordering of documents.  If they'd arrived in a different order, you'd have seen rejections on the original index.  That's just the way dynamic mappings work - there's nothing more we can do here.

**Comment by dseeley-sky** [comment]
I didn't use the original mapping as you suggest because it was being reindexed from es1.5 to es5, and I figured the differences would matter.  In the end, I used stream2es, which didn't suffer from this problem.

**Comment by dseeley** [comment]
I didn't use the original mapping as you suggest because it was being reindexed from es1.53 to es5, and I assumed the differences would matter - perhaps this was not true.  In the end, I used stream2es, which didn't suffer from this problem.
