### ISSUE TITLE
Error on 'keyword field' documentation: support to search_analyzer parameter 

### ISSUE THREAD

**Issue by guilhermemaranhao** [elastic/elasticsearch#23609]
Hi everyone,

It's said in https://www.elastic.co/guide/en/elasticsearch/reference/5.2/keyword.html that the `search_analyzer` parameter is accepted to the keyword datatype.

I've specified a `search_analyzer` parameter to a keyword field on my index and got the exception (something I expected it would happen)....

`Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Mapping definition for [my_keyword_field] has unsupported parameters:  [search_analyzer : my_analyzer]"}]`

Regards,

Guilherme

**Comment by rjernst** [comment]
`search_analyzer` is not actually supported on `keyword` fields. For that we have `normalizer`, and there has been discussion in #23336 about adding support for a search time normalizer. @jpountz should we update the docs for now to remove `search_analyzer` since it currently does not work?

**Comment by guilhermemaranhao** [comment]
Thank you!
