### ISSUE TITLE
ElasticSearch Unit test ESIntegTestCase does not load

### ISSUE THREAD

**Issue by git-cambridge** [elastic/elasticsearch#23611]
I am using ES5.2.2, with Lucene 6.4.1. I have followed the steps in 
https://www.elastic.co/guide/en/elasticsearch/reference/current/integration-tests.html
to create nodes for ElasticSearch unit tests. However, on running them, I get

java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.test.ESTestCase

Is this is a bug? I have posted on the elastic discussion website, and have had no response.

**Comment by jasontedor** [comment]
I know that you started on the [forum](https://discuss.elastic.co) but that's where this discussion needs to stay as Elastic reserves GitHub only for verified bug reports and feature requests. As such, I hope you don't mind that I close this. Please feel free to link to the topic from here.
