### ISSUE TITLE
Bit Array [Feature Request]

### ISSUE THREAD

**Issue by seperman** [elastic/elasticsearch#23616]
**Describe the feature**:

Please consider adding bit arrays to Elasticsearch. 
Why? Because one can use the Bloom filter in Elasticsearch which is very useful in searching.

Currently the only way to achieve this is by having arrays of integers that contain the indexes of bits that ON as you can see in this stackoverflow question: http://stackoverflow.com/q/39110962/1497443
But the current solution is not very efficient.

**Comment by nik9000** [comment]
That sounds like a good use for a plugin - a mapper plugin could interpret binary/some nice json encoding and build the appropriate index for the bloom filter. At least that is my instinct.

**Comment by sriram2520** [comment]
@nik9000 can you please point me towards a good documentation on writing custom mapper plugin for the above purpose. I have been searching for a good blog  and explanation with an example on this topic, but couldn't find one

**Comment by nik9000** [comment]
The plugin API isn't really stable so the best way to learn about it at this point is to read other users of it. It'll get better, one day. But for now, that is the way it is. We maintain two mapper plugins in Elasticsearch's source tree so they should always be up to date and useful examples:
* https://github.com/elastic/elasticsearch/tree/5.2/plugins/mapper-murmur3
* https://github.com/elastic/elasticsearch/tree/5.2/plugins/mapper-murmur3

**Comment by rjernst** [comment]
I'm going to close this as a bit array is not something we are likely to add as an official mapping type. As Nik pointed out, this is something that should be done in a plugin. Additionally, bloom filters were removed from Elasticsearch many versions ago, so any plugin implementation would need to bring in its own bloom filter library.
