### ISSUE TITLE
AdapterActionFuture does not restore the thread's interrupt flag when catching InterruptedException

### ISSUE THREAD

**Issue by hlivni** [elastic/elasticsearch#23617]
**Elasticsearch version**: 5.3

**Plugins installed**: []

**JVM version**: any

**OS version**: any

**Description of the problem including expected versus actual behavior**:
The `actionGet` methods catch an `InterruptedException` but fail to restore the thread's interrupt flag (by calling `Thread.currentThread().interrupt()`) before throwing an `IllegalStateException`

**Steps to reproduce**:
 N/A

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
> Elasticsearch version: latest

Please state the exact version. In a year "latest" will not mean anything.

**Comment by hlivni** [comment]
Exact version added. Thanks for the feedback

**Comment by jasontedor** [comment]
You added 5.3 but this version of Elasticsearch 5.3 is not released.

**Comment by jasontedor** [comment]
I agree with you that we should restore the interrupt flag here. I opened #23618.
