### ISSUE TITLE
Result sorting issues

### ISSUE THREAD

**Issue by aircat2018** [elastic/elasticsearch#23626]
My database is used to store user data
Each user has about tens of thousands of data.
When the search based on keywords, it will result in multiple pages are the same user’s results.
How to achieve when search by the keywords, each user first results on the top of the result, to prevent multiple pages are the same user.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
