### ISSUE TITLE
Autostart of ELASTIC search is failing.

### ISSUE THREAD

**Issue by manojraib** [elastic/elasticsearch#23625]
Hi ,

We have installed the elastic in elasticsearch user ,

We are trying to start using the systemctl and we are getting the below error .COuld you please help me to resolve the same.

Mar 16 23:36:25 xxxxxhostname elasticsearch[94819]: [2017-03-16T23:36:25,585][INFO ][o.e.t.TransportService   ] [*****c1-m2] publish_address {10.12
Mar 16 23:36:25 xxxxxhostname elasticsearch[94819]: [2017-03-16T23:36:25,589][INFO ][o.e.b.BootstrapCheck     ] [*****c1-m2] bound or publishing to
Mar 16 23:36:25 xxxxxhostname elasticsearch[94819]: ERROR: bootstrap checks failed
Mar 16 23:36:25 xxxxxhostname elasticsearch[94819]: max file descriptors [4096] for elasticsearch process is too low, increase to at least [65536]
Mar 16 23:36:25 xxxxxhostname elasticsearch[94819]: memory locking requested for elasticsearch process but memory is not locked
Mar 16 23:36:25 xxxxxhostname elasticsearch[94819]: [2017-03-16T23:36:25,602][INFO ][o.e.n.Node               ] [*****c1-m2] stopping ...
Mar 16 23:36:25 xxxxxhostname elasticsearch[94819]: [2017-03-16T23:36:25,623][INFO ][o.e.n.Node               ] [*****c1-m2] stopped
Mar 16 23:36:25 xxxxxhostname elasticsearch[94819]: [2017-03-16T23:36:25,623][INFO ][o.e.n.Node               ] [*****c1-m2] closing ...
Mar 16 23:36:25 xxxxxhostname elasticsearch[94819]: [2017-03-16T23:36:25,638][INFO ][o.e.n.Node               ] [*****c1-m2] closed
Mar 16 23:36:25 xxxxxhostname systemd[1]: elasticsearch.service: main process exited, code=exited, status=78/n/a
Mar 16 23:36:25 xxxxxhostname systemd[1]: Unit elasticsearch.service entered failed state.
Mar 16 23:36:25 xxxxxhostname systemd[1]: elasticsearch.service failed.
Mar 16 23:36:25 xxxxxhostname systemd[1]: elasticsearch.service holdoff time over, scheduling restart.
Mar 16 23:36:25 xxxxxhostname systemd[1]: Started ElasticSearch Service.
Mar 16 23:36:25 xxxxxhostname systemd[1]: Starting ElasticSearch Service...
Mar 16 23:36:27 xxxxxhostname elasticsearch[94869]: [2017-03-16T23:36:27,072][WARN ][o.e.b.JNANatives         ] Unable to lock JVM Memory: error=12,
Mar 16 23:36:27 xxxxxhostname elasticsearch[94869]: [2017-03-16T23:36:27,074][WARN ][o.e.b.JNANatives         ] This can result in part of the JVM b
Mar 16 23:36:27 xxxxxhostname elasticsearch[94869]: [2017-03-16T23:36:27,074][WARN ][o.e.b.JNANatives         ] Increase RLIMIT_MEMLOCK, soft limit:
Mar 16 23:36:27 xxxxxhostname elasticsearch[94869]: [2017-03-16T23:36:27,075][WARN ][o.e.b.JNANatives         ] These can be adjusted by modifying /
Mar 16 23:36:27 xxxxxhostname elasticsearch[94869]: # allow user 'elasticsearch' mlockall
Mar 16 23:36:27 xxxxxhostname elasticsearch[94869]: elasticsearch soft memlock unlimited
Mar 16 23:36:27 xxxxxhostname elasticsearch[94869]: elasticsearch hard memlock unlimited
Mar 16 23:36:27 xxxxxhostname elasticsearch[94869]: [2017-03-16T23:36:27,075][WARN ][o.e.b.JNANatives         ] If you are logged in interactively,
Mar 16 23:36:27 xxxxxhostname elasticsearch[94869]: [2017-03-16T23:36:27,172][INFO ][o.e.n.Node               ] [*****c1-m2] initializing ...
Mar 16 23:36:27 xxxxxhostname elasticsearch[94869]: [2017-03-16T23:36:27,238][INFO ][o.e.e.NodeEnvironment    ] [*****c1-m2] using [1] data paths,
Mar 16 23:36:27 xxxxxhostname elasticsearch[94869]: [2017-03-16T23:36:27,238][INFO ][o.e.e.NodeEnvironment    ] [*****c1-m2] heap size [1.9gb], com
Mar 16 23:36:27 xxxxxhostname elasticsearch[94869]: [2017-03-16T23:36:27,239][INFO ][o.e.n.Node               ] [*****c1-m2] node name [*****c1-m2
Mar 16 23:36:27 xxxxxhostname elasticsearch[94869]: [2017-03-16T23:36:27,241][INFO ][o.e.n.Node               ] [*****c1-m2] version[5.1.2], pid[94

Regards
Manoj.Rai.B

**Comment by manojraib** [comment]
this is systemmd file

 cat /etc/systemd/system/elasticsearch.service
[Unit]
Description=ElasticSearch Service
After=network.target

[Service]
ExecStart=/home/elasticsearch/elasticsearch-5.1.2/bin/elasticsearch
#PIDFile=/elastic/data/software/elasticsearch-5.2.0/bin/es.pid
User=elasticsearch
Type=simple
Restart=always

[Install]
WantedBy=default.target

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
And check bootstrap checks doc
