### ISSUE TITLE
delete by query optimizations

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#23630]
While I was reading #23629, I started to think if we can have some optimizations for the Delete By Query feature:

If someone runs a `match_all` DBQ, we can:

* Save the current index settings / mappings
* Drop the index
* Recreate the index with previous index settings / mappings

More generic way: I wonder if we can actually try to automagically optimize the way delete by query is working.

Like detect that we are going to suppress 90% or more data, then:

* create a new index with old settings/mappings
* use reindex with a negation of the query used in delete by query
* switch the existing alias
* drop the old index

Of course it's not that straightforward but I'm wondering if this is something we can think of.

I believe that we should have as a constraint an alias to be able to use those optimizations. Otherwise we fallback to the current implementation.

Thoughts?

**Comment by jasontedor** [comment]
We can not do these, it changes the index UUID, it's not the same behavior.
