### ISSUE TITLE
Need to know what this means?

### ISSUE THREAD

**Issue by jquinnet** [elastic/elasticsearch#23639]
i need to know if this number is the total % of initializing shards that are trying to realocate and if it's going to go to 0 when completed or if it's going to go to 100 once done? 

  **"active_shards_percent_as_number" : 98.95833333333334**

  "cluster_name" : "blah-2",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 8,
  "number_of_data_nodes" : 5,
  "active_primary_shards" : 96,
  "active_shards" : 190,
  "relocating_shards" : 0,
  "initializing_shards" : 2,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  **"active_shards_percent_as_number" : 98.95833333333334**

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
