### ISSUE TITLE
when can Field Collapsing available?

### ISSUE THREAD

**Issue by jayqie** [elastic/elasticsearch#23642]
Elasticsearch version: 5.2.2
JVM version: 1.8.0_91
OS version: CentOS release 6.7

I find Field Collapsing function in master document, but not in the 5.2.2 documents. When will the next version be published and then I can use this function?

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by dadoonet** [comment]
It's in 5.3 which should be released soon hopefully.
