### ISSUE TITLE
Describe how to apply best_compression

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#23646]
[Here](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/index-modules.html#index-codec) we don't mention how to change the index codec, just that it can be done.
I wasn't sure if this would be better done in the docs or in the def guide, but I wanted to start a conversation around it.

Inspired by [this thread](https://discuss.elastic.co/t/how-does-the-best-compression-work-after-i-setting-it/78643).

**Comment by darouwan** [comment]
@markwalkom  Thanks a lot!
