### ISSUE TITLE
Reenable `include_in_all` in 5.x

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#23654]
https://github.com/elastic/elasticsearch/pull/21971 removed the `include_in_all` mapping parameter, but it should have gone into master only, with deprecation logging added to 5.x.

Unfortunately, `include_in_all` was removed from 5.2.0 as well.  This is a regression that should be reverted and have deprecation logging in its place.

**Comment by mfeltscher** [comment]
Thanks!

**Comment by nik9000** [comment]
Closing manually as the fix went to branches other than `master` and github only auto-closes when the fix is merged to `master`.
