### ISSUE TITLE
Provide better logging on snapshot restore when allocation filtering criteria is not met

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#23655]
2.x, 5.x

Currently, by default, if a snapshot is taken against an index with allocation filtering settings, and the target cluster do not have nodes started with the corresponding node attributes for allocation, it is not clear to the administrator why the restore appears to be stuck. 

- The recovery api will show outstanding recovery at all
- The cluster state api will show the restored shards stuck in INIT state
- There are no threads indicating any outstanding restore action
- Even when logging is turned up to debug mode, there is no logging telling the user why the restore is not happening

On 5.x, it's better because we have a [cluster allocate explain api](https://www.elastic.co/guide/en/elasticsearch/reference/master/cluster-allocation-explain.html) that can be used to get an explanation.  However, the above of the restored shards stuck in INIT recovery state can be misleading to users and they may not immediately realize that they have to go run the cluster allocation explain api.

It will be a better experience if the snapshot restore process can determine that there are shard allocation filtering settings as part of the restored snapshot and that the target cluster does not have matching attributes - and will write a warning message to the log files indicating that.

Something like the following written to the logs will be nice:

```
Cannot find any nodes matching index setting [index.routing.allocation.<setting>] filters [tag:"<something>"]```

**Comment by jaymode** [comment]
It would be good to also add that you can change the settings when re-trying the restore to allow it to succeed or by tagging nodes, etc.

**Comment by tlrx** [comment]
> On 5.x, it's better because we have a cluster allocate explain api that can be used to get an explanation. However, the above of the restored shards stuck in INIT recovery state can be misleading to users and they may not immediately realize that they have to go run the cluster allocation explain api.

This has been improved in #27493: in the situation you described, the shards won't be allocated and will be UNASSIGNED. The next logical step is to use the Cluster Allocation Explain API and it will return something like:
```
"deciders" : [
        {
          "decider" : "restore_in_progress",
          "decision" : "NO",
          "explanation" : "shard has failed to be restored from the snapshot [repository:snap-0/Vf5oSPe5SEm_OXeap3h93A] because of [restore_source[repository/snap-0]] - manually close or delete the index [books] in order to retry to restore the snapshot again or use the reroute API to force the allocation of an empty primary shard"
        },
        {
          "decider" : "filter",
          "decision" : "NO",
          "explanation" : "node does not match index setting [index.routing.allocation.include] filters [size:\"foo\"]"
        }
      ]
```

which I think is enough, what do you think?

**Comment by ywelsch** [comment]
I think that the fix mentioned by @tlrx should improve the situation here, so I'm closing this issue.
