### ISSUE TITLE
Aggregation Support for Range Fields

### ISSUE THREAD

**Issue by nknize** [elastic/elasticsearch#23660]
The original Range Field PR (https://github.com/elastic/elasticsearch/pull/21002) included a `CustomRangeDocValuesField` for enabling doc values on Lucene Range Field types. One reason it was removed is because Aggregations have no way of leveraging range fields; so I am opening this issue to solicit ideas on adding range field support to aggregations. For relevant bucket aggregations (e.g., histogram, range, date_histogram, date_range, ip_range)  it seems the simple way is to count the document if the indexed range `INTERSECTS` with the bucket range? There are also a lot of interesting things (e.g., distribution stats) we could do for supporting range fields in existing metric aggregations (`stats`, `extended_stats`, etc). I don't want to overthink this but it seems like there are several different directions we could go here; and we had some questions around this topic at elasticon AMA, so I'd like to start gathering some thoughts.

**Comment by jpountz** [comment]
Relates to #23182.

**Comment by nknize** [comment]
Oh hay!! I might have seen that one if I didn't have 265K unread emails! Thanks @jpountz! Closing this issue as a duplicate.
