### ISSUE TITLE
Unexpected Key values in Histogram Aggregation

### ISSUE THREAD

**Issue by daver208** [elastic/elasticsearch#23664]
**Elasticsearch version**: 5.2 and 5.22

**Plugins installed**: xpack 5.2 5.22

**JVM version**:Oracle 1.8.0_121(OSX)  openjdk:8-jre (docker image from https://hub.docker.com/_/elasticsearch/)

**OS version**: Mac OSX Yosemite (10.10.5) (Elasticsearch 5.2.0) AND Ubuntu 16.04 (Elasticsearch 5.2.2) 

**Description of the problem including expected versus actual behavior**:
When using a decimal interval as an argument to the Histogram Aggregation, some keys come back with insignificant digits in the returned result.  I can truncate / use toFixed() to 'fix' the key, but the behavior is undocumented. Run the following curl commands to replicate.

```
curl -s -XPUT localhost:9200/decimal_test -d'
{
    "settings" : {
        "index" : {
            "number_of_shards" : 1, 
            "number_of_replicas" : 0 
        }
    }
}'

curl -s -XPUT localhost:9200/decimal_test/doc/1 -d'
{
    "testVal" : 1.0
}'
curl -s -XPUT localhost:9200/decimal_test/doc/2 -d'
{
    "testVal" : -1.0
}'

curl -s localhost:9200/decimal_test/doc/_search?pretty -d'
{
    "size": 0,
    "aggs" : {
        "test_agg" : {
            "histogram" : {
                "field" : "testVal",
                "interval" : 0.1,
                "min_doc_count" : 0
            }
        }
    }
}'

curl -XDELETE localhost:9200/decimal_test
```
The above will generate the following output
```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "test_agg" : {
      "buckets" : [
        {
          "key" : -1.0,
          "doc_count" : 1
        },
        {
          "key" : -0.9,
          "doc_count" : 0
        },
        {
          "key" : -0.8,
          "doc_count" : 0
        },
        {
          "key" : -0.7000000000000001,
          "doc_count" : 0
        },
        {
          "key" : -0.6000000000000001,
          "doc_count" : 0
        },
        {
          "key" : -0.5,
          "doc_count" : 0
        },
        {
          "key" : -0.4,
          "doc_count" : 0
        },
        {
          "key" : -0.30000000000000004,
          "doc_count" : 0
        },
        {
          "key" : -0.2,
          "doc_count" : 0
        },
        {
          "key" : -0.1,
          "doc_count" : 0
        },
        {
          "key" : 0.0,
          "doc_count" : 0
        },
        {
          "key" : 0.1,
          "doc_count" : 0
        },
        {
          "key" : 0.2,
          "doc_count" : 0
        },
        {
          "key" : 0.30000000000000004,
          "doc_count" : 0
        },
        {
          "key" : 0.4,
          "doc_count" : 0
        },
        {
          "key" : 0.5,
          "doc_count" : 0
        },
        {
          "key" : 0.6000000000000001,
          "doc_count" : 0
        },
        {
          "key" : 0.7000000000000001,
          "doc_count" : 0
        },
        {
          "key" : 0.8,
          "doc_count" : 0
        },
        {
          "key" : 0.9,
          "doc_count" : 0
        },
        {
          "key" : 1.0,
          "doc_count" : 1
        }
      ]
    }
  }
}
```

**Comment by fernandozhu** [comment]
I'm happy to work on this issue

**Comment by childe** [comment]
```
% node
> 0.2+0.1
0.30000000000000004
```

```
% python
Python 2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 0.2+0.1
0.30000000000000004
```

**Comment by dadoonet** [comment]
OMG!

**Comment by fernandozhu** [comment]
Probably makes sense to round those floating values

**Comment by colings86** [comment]
Note that you can specify a `format` parameter in your `histogram` request to normalise the display of the key values to your requirements. E.g. here you could use `####0.0` to specify that you want only 1 decimal figure to be displayed in the output for the keys.

**Comment by colings86** [comment]
Discussed in FixItFriday and we don't think this is a bug. The buckets are correct as they do contain values greater than or equal to the key value and less than the key of the next bucket. The fact that the floating point representation gives cannot represent all decimal figures exactly is a side effect of the way it is implemented (as in because it uses floating point arithmetic. As mentioned above if you want to display a particular format for the key with a certain number of decimal figures you can specify the `format` parameter on the request

**Comment by daver208** [comment]
@colings86 I'm happy if that is the resolution of the issue, but it would be nice if it were documented.  I say that, knowing I wouldn't look at the documentation first myself.  But It would still be nice...

**Comment by colings86** [comment]
@daver208 Good point, I've reopened this and labelled it as a docs issue so the documentation can be updated
