### ISSUE TITLE
cat aliases {name} documented as list instead of string

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#23661]
[cat RestAliasAction](https://github.com/elastic/elasticsearch/blob/6265ef1c1ba1d308bcc28d00dccccac555e33b89/core/src/main/java/org/elasticsearch/rest/action/cat/RestAliasAction.java#L43) exposes an endpoint taking `{alias}` which feeds this **single** `alias` into the [GetAliasRequest constructor](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/admin/indices/alias/get/GetAliasesRequest.java#L42) exactly [as documented](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-alias.html)

However [cat.aliases](https://github.com/elastic/elasticsearch/blob/6265ef1c1ba1d308bcc28d00dccccac555e33b89/rest-api-spec/src/main/resources/rest-api-spec/api/cat.aliases.json#L9-L12) documents it as a `list` instead of a `string`

**Comment by colings86** [comment]
This bug can be reproduced with the following script:
```
PUT test
{
  "aliases": {
    "alias-1": {},
    "alias-2": {}
  }
}

PUT test2
{
  "aliases": {
    "alias-1": {},
    "alias-2": {},
    "alias-3": {}
  }
}

PUT test3
{
  "aliases": {
    "alias-3": {},
    "alias-4": {}
  }
}

# Correctly returns test and test2 indices
GET _cat/aliases/alias-1?v

# Should return test and test2 indices but returns nothing but the headers
GET _cat/aliases/alias-1,alias-2?v
```

**Comment by glefloch** [comment]
Hi, I would like to contribute to the project. Can I take this issue?

**Comment by colings86** [comment]
@glefloch yes, we would very much appreciate you tackling this issue so feel free to submit a Pull Request with a fix if you wish. You may want to read https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md to get started on contributing.
