### ISSUE TITLE
Check for homogeneous java versions

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#23668]
There have been occasional issues with specific versions of Java, and one of the most difficult error profiles to debug is when the bug is an incompatibility between two different java versions used within a single cluster.  I believe it is our recommendation to always have the same version of Java across a cluster, so would it be possible (and reasonable) to have some log warnings if the node does not have the same version (and vendor) java as the elected master node?

**Comment by jasontedor** [comment]
It is a best practice (for simplicity of operational management) but there really aren't any problems these days from different supported Java versions being used as we do not use Java serialization anywhere anymore.

> There have been occasional issues with specific versions of Java, and one of the most difficult error profiles to debug is when the bug is an incompatibility between two different java versions used within a single cluster.

Is there a specific issue on a recent version that you have in mind? I'm not aware of a problem here.

**Comment by robin13** [comment]
Thank you for the clarification - did not realise that there was no Java serialisation any more, so I guess it is not necessary after all...
Perhaps more pertinent then would be to check if the Java version being used [is supported](https://www.elastic.co/support/matrix#show_jvm) (tested) and create a boot-time warning if not.

**Comment by jasontedor** [comment]
We have a bootstrap check for known bad versions of Java, and known bad versions of Java given certain settings (e.g., using G1GC on versions less than 8u40). I think this is sufficient. I think one change that we should make here is to fail the node when starting on an early access build of Java 9.

**Comment by jasontedor** [comment]
I integrated #23743.
