### ISSUE TITLE
Document preserve_existing parameter

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#23673]
In https://github.com/elastic/elasticsearch/pull/17223 we added a new parameter to preserve existing settings when doing setting update. If set to `true` existing settings on an index remain unchanged, the default is `false`.

It would be great to document this setting 😃 .

**Comment by s1monw** [comment]
++

**Comment by glefloch** [comment]
Hi, I created a PR that document the new setting. Can you tell me if there is other places where it should be documented?

**Comment by javanna** [comment]
Closed by #23971
