### ISSUE TITLE
Explain mapping explosion

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#23687]
[Here](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/mapping.html#mapping-limit-settings) we talk about mapping explosions, but don't really go into what that is and why it's bad.

There's a few old blog posts about what this is means, but It'd be great if we elaborated in the docs. Not sure if the main docs or def guide is the place though.

**Comment by TanyaPedersen** [comment]
Hi, 

I'm a student in my third year of a Bachelor of Information Technology degree.  I'm new to github and a first time contributer to open source.  

I'd like to attempt to fix this issue, are there any further thoughts on whether main docs or def guide is the appropriate place for the changes?

- Tanya

**Comment by clintongormley** [comment]
Hi @TanyaPedersen 

Thanks for the offer.  I'd add it to the reference docs section, probably just above this: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#mapping-limit-settings

**Comment by lukas-vlcek** [comment]
@clintongormley Are there any mapping limit settings available for ES 2.x or they apply for ES 5.x and above only?

**Comment by markwalkom** [comment]
Can we backport this to 5.X as well, still seems relevant.

**Comment by javanna** [comment]
@markwalkom already backported to 5.6 with https://github.com/elastic/elasticsearch/commit/325d31fe0a247826f50d246979f350b5a52d2943 .
