### ISSUE TITLE
Normalizer Settings Validation

### ISSUE THREAD

**Issue by DustinChaloupka** [elastic/elasticsearch#23683]
**Elasticsearch version**: 5.2.2

**Plugins installed**: Just the defaults

**JVM version**: openjdk `1.8.0_111-8u111-b14-3~14.04.1-b14`

**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:
Was trying to migrate an analyzed `string` field (from ES 2.4) to a better field setup. I hadn't found anything super clear on how to go about doing this, so one of the things I had tried was adding a normalizer. However, I mistakenly used a `tokenizer` parameter as apart of the normalizer, which it does not support. This addition was after closing the index. But, since it's not possible to "remove" a parameter from a normalizer (at least that I could find), the `tokenizer` parameter is now permanently part of the normalizer. Now, I have no way of opening the index since ES gives back a `500` when trying to open a badly configured index.

I would expect that if there is index validation on opening an index, that any settings that get added to an index would get validated as well so that this state cannot happen. Instead I was given a `200` back when misconfiguring the closed index.

Not specifically part of the "bug" part of this, but now I'm wondering if it's possible to even open this index at all now?

**Steps to reproduce**:
 1. Close an index
 2. Add a `"tokenizer": "my_tokenizer"` field to a normalizer in the closed index
 3. Try to open the index

**Provide logs (if relevant)**:
```
➜  ~ curl -XPOST 'http://localhost:9200/my_index/_close'
{"acknowledged":true}
➜  ~ curl -XPUT 'http://localhost:9200/my_index/_settings' -d '{"analysis": {"normalizer": {"my_normalizer": {"type": "custom","tokenizer": "my_tokenizer"}}}}'
{"acknowledged":true}
➜  ~ curl -XPOST 'http://localhost:9200/my_index/_open'
{"error":{"root_cause":[{"type":"exception","reason":"Failed to verify index [my_index/w_VhFiSWRhiIz-z9AGOoPQ]"}],"type":"exception","reason":"Failed to verify index [my_index/w_VhFiSWRhiIz-z9AGOoPQ]","caused_by":{"type":"illegal_argument_exception","reason":"Custom normalizer [my_normalizer] cannot configure a tokenizer"}},"status":500}
```

Note: The tokenizer that was trying to be used was already created in the index.

**Comment by colings86** [comment]
@jpountz are you able to take a look at this?
