### ISSUE TITLE
Add target field to lowercase processor (and others)

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#23682]
From this discussion: https://discuss.elastic.co/t/workaround-alternative-for-normalizer-in-es-5-1/79470/3?u=dadoonet

Could be nice to be able to lowercase a field but target it to another field like "field.raw" for example.

If accepted, I think we should do it for most processors.

**Comment by clintongormley** [comment]
+1 - do it for (almost?) all processors
