### ISSUE TITLE
more_like_this query doesn't work with child documents

### ISSUE THREAD

**Issue by tyth** [elastic/elasticsearch#23699]
**Elasticsearch version**: 5.2.2

**Plugins installed**: []

**JVM version**: openjdk version "1.8.0_65"

**OS version**: CentOS release 6.8 

**Description of the problem including expected versus actual behavior**:
`more_like_this` query does not work correctly with child documents, when using document reference in `like` parameter. Queries always return 0 hits. It works fine for same query and documents, if I index them without child-parent relationship.

Adding `_routing` does not change anything. I tried (as an experiment) providing the reference with `_parent` parameter, as documentation tells that like parameter _"is similar to the one used by the Multi GET API"_, but it leads to "failed to parse More Like This item. unknown field [_parent]".

Works when providing text in like parameter directly.
It worked fine with same query in version 2.x.

**Steps to reproduce**:
 1. Create mappings A and B, where B has A as a parent
 2. Index some documents
 3. Query B with `more_like_this`

A query for reproduction can be basic:
```
{
  "query":{
    "more_like_this":{
      "fields":[
        "text"
      ],
      "like":[
        {
          "_index":"index_name",
          "_type":"B",
          "_id":"child_id"
        }
      ],
      "min_term_freq":1,
      "min_doc_freq":1
    }
  }
}
```

**Comment by colings86** [comment]
This reproduces on master with the following script:
```
PUT my_index
{
  "mappings": {
    "my_parent": {},
    "my_child": {
      "_parent": {
        "type": "my_parent" 
      }
    }
  }
}

PUT my_index/my_parent/1 
{
  "text": "This is a parent document"
}

PUT my_index/my_child/2?parent=1 
{
  "text": "This is a child document"
}

PUT my_index/my_child/3?parent=1&refresh=true 
{
  "text": "This is another child document"
}


PUT my_index/my_parent/4
{
  "text": "This is a parent document"
}

PUT my_index/my_child/5?parent=4
{
  "text": "This is a child document"
}

PUT my_index/my_child/6?parent=4&refresh=true 
{
  "text": "This is another child document"
}

# Works and returns hits
GET my_index/_search
{
  "query":{
    "more_like_this":{
      "fields":[
        "text"
      ],
      "like":[
        {
          "_index":"my_index",
          "_type":"my_parent",
          "_id":"1"
        }
      ],
      "min_term_freq":1,
      "min_doc_freq":1
    }
  }
}

# Returns 0 hits
GET my_index/_search
{
  "query":{
    "more_like_this":{
      "fields":[
        "text"
      ],
      "like":[
        {
          "_index":"my_index",
          "_type":"my_child",
          "_id":"2"
        }
      ],
      "min_term_freq":1,
      "min_doc_freq":1
    }
  }
}
```
Even if you specify the `_routing` using the parent's id it still returns 0 hits:

```
# Returns 0 hits
GET my_index/_search
{
  "query":{
    "more_like_this":{
      "fields":[
        "text"
      ],
      "like":[
        {
          "_index":"my_index",
          "_type":"my_child",
          "_id":"2",
          "_routing": "1"
        }
      ],
      "min_term_freq":1,
      "min_doc_freq":1
    }
  }
}
```
