### ISSUE TITLE
A way to inject dependencies in a Plugin class?

### ISSUE THREAD

**Issue by sscarduzio** [elastic/elasticsearch#23694]
I keep in hitting [this](https://github.com/elastic/elasticsearch/blob/ee802ad63c0f21d697a5095dd05dc6f94626ee4d/core/src/main/java/org/elasticsearch/plugins/PluginsService.java#L412) every time.

I tried using @Inject with fields, but they are null.

```java
  @Inject
  private NodeClient client;
```

Is there a way to inject dependencies in an Elasticsearch plugin class? Or any way around this?

**Comment by colings86** [comment]
Hi @sscarduzio  

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

In terms of your question, as the exception message says you can only have a zero-arg constructor or a constructor with only a `Settings` parameter so you cannot inject dependencies in the constructor. In your case if you want access to a `Client` object you can do this by implementing `Plugin.createComponents(Client client, ClusterService clusterService, ThreadPool threadPool, ResourceWatcherService resourceWatcherService, ScriptService scriptService, NamedXContentRegistry xContentRegistry)` and using the `Client` passed into this method
