### ISSUE TITLE
Hits limit for multi search

### ISSUE THREAD

**Issue by thammadi** [elastic/elasticsearch#23707]
Hi, 

Sorry I have to post it as an issue, but I wanted to know what is the max limit of hits returned from a multi search query (combined and individual)?

Thanks,

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by thammadi** [comment]
@jasontedor, thanks for letting know. I won't mind you closing this issue. Will post on the forums instead.

Thanks again.
