### ISSUE TITLE
Geo operations in ES 5.1.2 are slower than older ES

### ISSUE THREAD

**Issue by imidya** [elastic/elasticsearch#23709]
**Elasticsearch version**: 5.1.2

**Plugins installed**: None

**JVM version**: Oracle JDK 1.8.0_121, JVM build 25.121-b13 64-Bit

**OS version**: Ubuntu 14.04.1 LTS

**Description of the problem including expected versus actual behavior**:

I want to implement a function which is giving a geo point (latitude and longitude) and returning matched administrative districts which the geo point is inside the district.

In ES 1.4, I implement this function through percolator. I store percolators with GeoShape datatype for each district. Get the execution time of percolate query is 10ms. When I upgrade ES to 5.1.2,  the execution with same datatype takes more than 400ms. I'm trying to solve this problem and find a document in ES official website, it says that only Terms Query percolater will be keep in memory and other percolators will be placed in disk or memory decided by ES. Therefore, I convert GeoShape to GeoHash and use Terms Query[1] instead of percolate query, this action reduces the execution time from 400ms to 50ms. But the execution time is still five times than ES 1.4.

Another solution I tried is indexing GeoShape into an index and quering with GeoShape Query. And I found the execution time of geo point is matched by large GeoShape document is much longer than small GeoShape document. The execution time are 7ms and 70ms. But in ES 1.4, the execution time is always 20ms whether geo point macthed by samll document or large doucment. 

The problems are:

1. Percolator in ES 5.1.2 is much slower than ES 1.4 when we percolate a geo point with many GeoShape queries.
2. There are clear difference of execution time between geo point matched by small document and large document.

| ES version    | Implementation                                                        | Time  |
| ------------- |:---------------------------------------------------------------------:| -----:|
|ES 1.4         |GeoShape Query through percolator                                      |20ms   |
|ES 5.1.2       |GeoShape Query through percolator                                      |400ms  |
|ES 5.1.2       |Terms Query with GeoHash through percolator                            |50ms   |
|ES 5.1.2       |Index GeoShape and GeoShape Query (Geo point matched by small document)|<10ms   |
|ES 5.1.2       |Index GeoShape and GeoShape Query (Geo point matched by large document)|70ms   |

[1] Percolator in Terms Query with GeoHash

```
{
	"query": {
		"bool": {
			"filter": {
				"terms": {
					"hash": [
						"wsjkqzbzc",
						"wsjkqzbzd",
						"wsjkqzbze",
						"wsjkqzbzf",
						"wsjkqzbzg",
                                                 …
					]
				}
			}
		}
	}
}
```

**Steps to reproduce**:

You can download percolators and geojson data [HERE](https://github.com/imidya/kr_geojson)

- ES 1.4 (Percolator)

 1. Setup ES 1.4
 2. Put a mapping and create a percolator index
 
```
PUT kr-adminarea
{
	"mappings": {
		"geojson": {
			"properties": {
				"location": {
					"type": "geo_shape"
				}
			}
		},
		".percolator": {
			"properties": {
				"query": {
					"type": "object",
					"enabled": false
				}
			}
		}
	}
}
```
 
 3. Index percolators into index.

```
POST kr-adminarea/.percolator/kr11
{
	"query": {
		"bool": {
			"filter": {
				"geo_shape": {
					"location": {
						"shape": {
							"coordinates": [
								[
									[
										121.631747299,
										24.36943161500005
									]
									.....
								]
							]
						}
					}
				}
			}
		}
	}
} 
```
 
 4. Performance test.

```
GET kr-adminarea/geojson/_percolate
{
  "doc": {
    "location": {
      "type": "point",
      "coordinates": [126.671228, 34.553791]
    }
  }
}
```

```
GET kr-adminarea/geojson/_percolate
{
  "doc": {
    "location": {
      "type": "point",
      "coordinates": [127.062141, 37.590843]
    }
  }
}
```

 

- ES 5.1.2 (Percolate Query)

1. Setup ES 5.1.2
2. Put a mapping and create a percolator index
 
```
PUT kr-adminarea
{
  "mappings": {
    "geojson": {
      "properties": {
        "location": {
          "type": "geo_shape"
        }
      }
    },
    "queries": {
      "properties": {
        "query": {
          "type": "percolator"
        }
      }
    }
  }
} 
```

3. Index percolators which in "percolaters" folder into index.

```
POST kr-adminarea/queries/kr1
{
	"query": {
		"bool": {
			"filter": {
				"geo_shape": {
					"location": {
						"shape": {
							"coordinates": [
								[
									[
										121.631747299,
										24.36943161500005
									]
									.....
								]
							]
						}
					}
				}
			}
		}
	}
} 
```

4. Performance test.

```
GET kr-adminarea/_search
{
	"query": {
		"percolate": {
			"field": "query",
			"document_type": "geojson",
			"document": {
				"location": {
					"coordinates": [127.062141, 37.590843],
                                        "type": "point"
				}
			}
		}
	}
}
```
 
 
- ES 5.1.2 (GeoShape Index)

1. Setup ES 5.1.2
2. Put a mapping and create an index
 
```
PUT kr-adminarea
{
  "mappings": {
    "geojson": {
      "properties": {
        "location": {
          "type": "geo_shape",
          "tree": "quadtree",
          "precision": "50m"
        }
      }
    }
} 
```

3. Index GeoShape data in "geo_shape" folder.

```
POST kr-adminarea/geojson/kr1
{
	"location": {
		"shape": {
			"coordinates": [
				[
					[
						121.631747299,
						24.36943161500005
					]
					.....
				]
			]
		}
	}
} 
```

4. Performance test. (Matched by small document, geo point: 127.062141, 37.590843)

```
GET kr-adminarea/geojson/_search
{
   "_source": false,
   "query": {
      "bool": {
         "filter": {
            "geo_shape": {
               "location": {
                  "shape": {
                     "coordinates": [127.062141, 37.590843],
                     "type": "point",
                     "relation": "interacts"
                  }
               }
            }
         }
      }
   }
}
```

5. Performance test. (Matched by large document, geo point: 126.671228, 34.553791)

```
GET kr-adminarea/geojson/_search
{
   "_source": false,
   "query": {
      "bool": {
         "filter": {
            "geo_shape": {
               "location": {
                  "shape": {
                     "coordinates": [126.671228, 34.553791],
                     "type": "point",
                     "relation": "interacts"
                  }
               }
            }
         }
      }
   }
}
```

**Comment by clintongormley** [comment]
@nknize @martijnvg my guess here is that percolating geoshapes is slower than before because we no longer cache percolator queries.  thoughts?

**Comment by nknize** [comment]
@martijnvg I haven't really dug into this yet. I know there has been some work on percolator since this was opened. Any quick thoughts before we dive in?

**Comment by martijnvg** [comment]
The reason that `geo_shape` queries are slower compared to other queries is that the shape parsing is slow (the jts parsing). I expect that the query parsing for this query is going to improve when #32039 (bkd shape improvements) and #25445 (pre-selecting geo_shape candidate matches) have been implemented. So I'm closing this issue in favor of these issues. 

If possible the `geo_polygon` query should be used, because the query parsing of that query is much  lighter than what `geo_shape` query is doing.
