### ISSUE TITLE
Script filtering on nested field

### ISSUE THREAD

**Issue by sergpsu** [elastic/elasticsearch#23712]
I'm trying to use following script filter:
```
"query":{
"bool":{
"must":{
"script":{
"script":{
"doc.containsKey('MEMBERS')"
}
}
}
}
}
```
and this does not give any result. If I replace MEMBERS with LAST_MESSAGE_DATE the query works as expected. I have thousands of documents with MEMBERS so the query really does not work as expected.
Elasticsearch version 5.1.2

Mapping
```
"mappings" : {
      "CONV" : {
        "properties" : {
          "LAST_MESSAGE_DATE" : {
            "type" : "long"
          },
          "MEMBERS" : {
            "type" : "nested",
            "properties" : {
              "ID" : {
                "type" : "long"
              },
              "LEFT" : {
                "type" : "long"
              },
              "NICK" : {
                "type" : "keyword"
              },
              "READ" : {
                "type" : "long"
              }
            }
          },
          "MESSAGES" : {
            "type" : "nested",
            "properties" : {
              "DATE" : {
                "type" : "long"
              },
              "FROM_ID" : {
                "type" : "long"
              },
              "NICK" : {
                "type" : "keyword"
              },
              "TEXT" : {
                "type" : "text"
              }
            }
          }
        }
      }
    }
  }
```

**Comment by rjernst** [comment]
I see that you previously created a [discuss thread](https://discuss.elastic.co/t/script-filtering-by-nested-object-size-problem/79622/2), but waited only a few hours before creating this github issue. Elastic uses github for feature requests and confirmed bug reports. Please use the forum, and [be patient.](https://www.elastic.co/community/codeofconduct)

Note that while I don't think this is a bug, I do think the situation can be improved to be more transparent, so I have opened 
https://github.com/elastic/elasticsearch/issues/23719.
