### ISSUE TITLE
support  java.util.Date fields in the DateIndexNameProcessor

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch#23718]
**Elasticsearch version**: 5.2.2

**Plugins installed**: x-pack

**Description**: If you create a new field using the `script` processor, ex. `ctx.new_date = new Date();`, and then try to use the `date_index_name` processor, it throws
`{"type":"exception","reason":"java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: field [new_date] of type [java.util.Date] cannot be cast to [java.lang.String]","header":{"processor_type":"date_index_name"}}`

If you skip the `date_index_name` step, it properly writes out a formatted string in the es document as `"new_date": "2017-03-23T16:03:13.626Z"`. 

This works if you use SimpleDateFormat to create an appropriately formatted string from the date, but this is not nearly as obvious or simple as just using `ctx.new_date = new Date();`
``` json
PUT _ingest/pipeline/monthlyindex
{
  "description": "monthly date-time index naming",
  "processors": [
    {
      "script": {
        "lang": "painless",
        "inline": """
DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
dateFormat.setTimeZone(TimeZone.getTimeZone("UTC")); 
Date date = new Date();
ctx.new_date = dateFormat.format(date);
"""
      }
    },
    {
      "date_index_name": {
        "field": "new_date",
        "index_name_prefix": "myindex-",
        "date_rounding": "M"
      }
    }
  ]
}

PUT /myindex/type/1?pipeline=monthlyindex
{
  "foo": "bar"
}
```

**Comment by talevy** [comment]
Hey @jpcarey, are you sure you ran that pipeline as you are showing it? or maybe an older version of it? The one you provided looks good?

```
POST _ingest/pipeline/_simulate
{
  "pipeline" :
  {
  "description": "monthly date-time index naming",
  "processors": [
    {
      "script": {
        "lang": "painless",
        "inline": "DateFormat dateFormat = new SimpleDateFormat(\"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'\");dateFormat.setTimeZone(TimeZone.getTimeZone(\"UTC\"));Date date = new Date(); ctx.new_date = dateFormat.format(date);",
        "params": {
          "param_c": 10
        }
      }
    },
    {
      "date_index_name": {
        "field": "new_date",
        "index_name_prefix": "myindex-",
        "date_rounding": "M"
      }
    }
  ]
},
  "docs": [
    {
      "_index": "index",
      "_type": "type",
      "_id": "id",
      "_source": {
        "foo": "bar"
      }
    }
  ]
}
```

returns

```
{
  "docs": [
    {
      "doc": {
        "_index": "<myindex-{2017-03-23||/M{yyyy-MM-dd|UTC}}>",
        "_type": "type",
        "_id": "id",
        "_source": {
          "new_date": "2017-03-23T20:01:38.227Z",
          "foo": "bar"
        },
        "_ingest": {
          "timestamp": "2017-03-23T20:01:38.227+0000"
        }
      }
    }
  ]
}
```

Looks good

**Comment by jpcarey** [comment]
Sorry, the full example was for what was required to make it work. Just need to substitute the painless script to `ctx.new_date = new Date();` to get the error that I provided:

``` json
PUT _ingest/pipeline/monthlyindex
{
  "description": "monthly date-time index naming",
  "processors": [
    {
      "script": {
        "lang": "painless",
        "inline": "ctx.new_date = new Date();",
        "params": {
          "param_c": 10
        }
      }
    },
    {
      "date_index_name": {
        "field": "new_date",
        "index_name_prefix": "myindex-",
        "date_rounding": "M"
      }
    }
  ]
}

PUT /myindex/type/1?pipeline=monthlyindex
{
  "foo": "bar"
}
```

**Comment by talevy** [comment]
OK, cool.

This is a valid issue. Currently, the processor assumes a formatted date string in the field and does not support reading in a date. Although, understanding a Date object makes sense.

mind if I re-label this as a feature request for supporting Date valued fields in the DateIndexNameProcessor?
