### ISSUE TITLE
Drop document in ingest pipeline

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#23726]
It'd be really useful to be able to drop a document in an ingest pipeline, ie to not index it at all.

Perhaps, by setting `_index` to `""`?

**Comment by dadoonet** [comment]
Is it in the case of an exception in the pipeline? I mean that we don't have conditionals so why would you not index a document that you sent to indexation process?

**Comment by clintongormley** [comment]
Conditionals are next ;) (although there are scripts anyway)

But eg a document is going to an index that I no longer want to use - I want to be able to drop the document instead

**Comment by dadoonet** [comment]
I wonder if we should have a `drop` processor to implement that. As we have the same feature in Logstash... https://www.elastic.co/guide/en/logstash/current/plugins-filters-drop.html

**Comment by talevy** [comment]
@clintongormley I know Beats requested this feature a while back... I was not aware that an empty string `_index` results in a successful non-index?

One way to achieve this is to run a `fail` processor. The difference here is that we would not return back a `2XX` for this request, and the client would think there was a problem, instead of "dropping was successful".

**Comment by clintongormley** [comment]
>  I was not aware that an empty string _index results in a successful non-index?

No, it was a suggestion.  I see the same string length exception that you do.

I like your suggested response for the `drop` processor.

The one problem is that I don't see how to trigger the `drop` processor without conditionals.  I want to say: "if the index is Foo, then drop this document".  There's no easy way to do this.  The only conditionals I have are in a script, but then I can't use that to call the `drop` processor unless I throw some dummy exception to trigger an `on_failure` handler.

**Comment by dadoonet** [comment]
For now (before we have conditionals - was not aware that was a plan BTW), `on_failure` seems to be the way to go.
I wonder if we can in a script throw a NoOpException which does not print any warn in logs but just triggers the `on_failure` pipeline.

**Comment by dadoonet** [comment]
That said we can also support both. If `index` is empty or null, skip the operation.

**Comment by PhaedrusTheGreek** [comment]
+1 for a clean way to drop messages

**Comment by talevy** [comment]
Closing due to the lack of infrastructure for properly handling this.

Feel free to re-open if this comes up again

**Comment by dadoonet** [comment]
Hurray! We are going to support it finally! See #32278
