### ISSUE TITLE
Test Failure: org.elasticsearch.search.aggregations.metrics.avg.InternalAvgTests

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#23723]
Looks like a rounding error in test case.

Reproduce With:

gradle :core:test -Dtests.seed=AD4714EA5A654B38 -Dtests.class=org.elasticsearch.search.aggregations.metrics.avg.InternalAvgTests -Dtests.method="testReduceRandom" -Dtests.security.manager=true -Dtests.locale=el-GR -Dtests.timezone=US/Pacific
FAILURE 0.01s J0 | InternalAvgTests.testReduceRandom

Build Failure:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/982/console

**Comment by cbuescher** [comment]
This is a double rounding issue, we sum over ~200 larger double values here and it seems the rounding error you get when summing them depends on the order you iterate over them. I tried summing the input values for this particular test seed in different random orders and get suprisingly different results after the 7th decimal point:
```
9869965.179804232
9869965.179804225
9869965.179804234
9869965.179804236
9869965.179804238
9869965.179804238
9869965.179804232
9869965.17980423
9869965.179804228
9869965.179804228
```

I will decrease the expected precision for this test.
