### ISSUE TITLE
Nest driver can't create include: "" element in the aggregations

### ISSUE THREAD

**Issue by wolczas** [elastic/elasticsearch#23721]
**Elasticsearch version**: 5.2.2

**OS version**: Win 10

**Description of the problem including expected versus actual behavior**:
```include``` section in the aggregation is unable to create a simple string inside of ```terms```.

I want to create
```
"catpaths": {
          "terms": {
            "field": "categories.categoryPath",
           "include": "(/[^/]+){2}"
          },
 ```
Using Nest statements ```include``` value gets wrapped in ```[]``` and ```pattern``` elements:

* ```TermsAggregationDescriptor<T> Include(string includePattern, string regexFlags = null);```
Nest:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.Include(@"(/[^/]+){2}*","")
DSL:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; **"include":{"pattern":"(/[^/]+){2}"}}**

* ```TermsAggregationDescriptor<T> Include(IEnumerable<string> values)```
Nest:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;var sequence = Enumerable.Repeat("(/[^/]+){2}", 1);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;.Include(sequence)
DSL:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**"include": ["(/[^/]+){2}"]**

I need a Nest TermsAggregationDescriptor ```include``` statement that will generate string DSL:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**"include": "(/[^/]+){2}"**

Extra ```pattern``` element prevents parser to continue with evaluating nested aggs.
Array of ```include []``` uses literal strings and does not evaluate elements regex expression.

**Comment by jasontedor** [comment]
I think that you should open this on the [elastic/elasticsearch-net](https://github.com/elastic/elasticsearch-net/) repository.

**Comment by wolczas** [comment]
Thank You! done:
https://github.com/elastic/elasticsearch-net/issues/2682

**Comment by jasontedor** [comment]
You're welcome. It's appreciated that you linked to the subsequent issue from here, to help future passersby that land here.
