### ISSUE TITLE
Test Failure: org.elasticsearch.test.test.InternalTestClusterTests

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#23728]
Unable to reproduce locally.

Reproduce With:

gradle :test:framework:test -Dtests.seed=77755856DF44A43D -Dtests.class=org.elasticsearch.test.test.InternalTestClusterTests -Dtests.security.manager=true -Dtests.locale=en-US -Dtests.timezone=Etc/UTC

Build Failure:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/745/console

**Comment by imotov** [comment]
Failed again https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/746/console 

@bleskes, could you take a look?

**Comment by spinscale** [comment]
another failure here, unable to reproduce with a few iterations as well, message is

```
ElasticsearchException[failed to update minimum master node to [3] (current masters [3])]; nested: IllegalArgumentException[illegal value can't update [discovery.zen.minimum_master_nodes] from [2] to [3]]; nested: IllegalArgumentException[cannot set discovery.zen.minimum_master_nodes to more than the current master nodes count [2]];
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/2319/testReport/junit/org.elasticsearch.test.test/InternalTestClusterTests/testDifferentRolesMaintainPathOnRestart/

@bleskes, could you take a look?
