### ISSUE TITLE
smartcn_tokenizer is slower between 1.3.4 and 2.4.3

### ISSUE THREAD

**Issue by stevekaeser** [elastic/elasticsearch#23722]
**Elasticsearch version**: 2.4.3

**Plugins installed**: [smartcn_tokenizer]

**JVM version**: 1.8

**OS version**: Debian Jessie

**Description of the problem including expected versus actual behavior**: When running the smartcn_tokenizer, it takes almost 4x as long on 2.4.3 than it does on 1.3.4

**Steps to reproduce**:
 1. create an index on with the following mapping:
`PUT test-index
{
	"settings": {
		"analysis": {
			"analyzer": {
				"zh_analyzer": {
					"filter": [
						"icu_normalizer",
						"icu_folding"
					],
					"type": "custom",
					"tokenizer": "smartcn_tokenizer"
				}
			}
		}
	},
	"mappings": {
		"post": {
			"properties": {
				"content": {
					"properties": {
						"zh": {
							"type": "string",
							"similarity": "BM25",
							"fields": {
								"word_count": {
									"type": "token_count",
									"analyzer": "zh_analyzer"
								}
							},
							"analyzer": "zh_analyzer"
						}
					}
				}
			}
		}
	}
}`
 2. Make the call to _analyze that is attached in analyze.txt. ( the content was too big to include in the body )
[analyze.txt](https://github.com/elastic/elasticsearch/files/865667/analyze.txt)

 3. The timing that I get on my cluster is ~6 seconds on 1.3.4 and ~22 seconds on 2.4.3.

**Provide logs (if relevant)**: N/A

**Comment by romseygeek** [comment]
Just tried this out on 6.2.2 and it still seems to take a long time.

@elastic/es-search-aggs

**Comment by cbuescher** [comment]
Given the lack of a measurable reproduction and the age of this issue I'm going to close this.
