### ISSUE TITLE
Bad error message when misspelling docs in _mget

### ISSUE THREAD

**Issue by stevenmwade** [elastic/elasticsearch#23720]
**Elasticsearch version**: 5.x

**JVM version**: 8

**OS version**: OSX 10.11.6

**Description of the problem including expected versus actual behavior**: When searching _mget and passing `{"doc": []}` (misspelling `docs`), should throw a better error message when seeing the array.

**Steps to reproduce**:
`doc` instead of `docs`:
```
GET _mget
{
  "doc" : [
    {
      "_index" : "orders-current",
      "_type" : "order",
      "_id" : 6
    },
    {
      "_index" : "products",
      "_type" : "product",
      "_id" : 4321
    }
  ]
}
```

Error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "action_request_validation_exception",
        "reason": "Validation Failed: 1: no documents to get;"
      }
    ],
    "type": "action_request_validation_exception",
    "reason": "Validation Failed: 1: no documents to get;"
  },
  "status": 400
}
```

@dakrone

**Comment by olcbean** [comment]
Do you mean that instead `no documents to get;` the msg should changed to `Unknown key for a START_OBJECT in [doc].` (similar to the one displayed for search)?

**Comment by rjernst** [comment]
Looks like the keys should be validated [here](https://github.com/elastic/elasticsearch/blob/ee802ad63c0f21d697a5095dd05dc6f94626ee4d/core/src/main/java/org/elasticsearch/action/get/MultiGetRequest.java#L324).  And the value type should also be validated as well. Right now it only looks for array. Anything else is silently ignored.
