### ISSUE TITLE
Painless and Groovy yield slightly different values calculating buckets

### ISSUE THREAD

**Issue by paulohss** [elastic/elasticsearch#23732]
****Elasticsearch version**: 5.2.2**

****OS version**: Windows 10**

****Painless and Groovy yields slightly different values calculating buckets**:**

****Steps to reproduce**:**
 1. If guys find it useful, I can upload the indexes I'm using. The steps below are based upon it.

 2. Run the following command, using Painless as default:

```
GET /unittesttg1_tg1_fq1/_search
{
  "size": 0,
  "aggs": {
    "groupby": {
      "range": {
        "script": {
          "inline": "((doc['LAST_MODIFIED_DATE'].value - doc['SUBMIT_DATE'].value) / 3600000)"
        },
        "ranges": [
          {
            "from": 0.0,
            "to": 10.0,
            "key": "A 0 - 10"
          },
          {
            "from": 10.0,
            "to": 20.0,
            "key": "B 10 - 20"
          }
        ]
      }
    }
  }
}
```
Result:
Bucket 1 (A 0 - 10): **4576**
Bucket 2 (B 10 - 20): **191**

 3. Now, run the same command, this time forcing the language as groovy ("lang":   "groovy",).
Result:
Bucket 1 (A 0 - 10): **4557**
Bucket 2 (B 10 - 20): **191**

4. The first bucket comes wrong when using painless.
    (I compared this results with the original data source) 

5. Meaning that, in order to get accurate results I need to stick with:
```
GET /unittesttg1_tg1_fq1/_search
{
  "size": 0,
  "aggs": {
    "groupby": {
      "range": {
        "script": {
          **"lang":   "groovy",**
          "inline": "((doc['LAST_MODIFIED_DATE'].value - doc['SUBMIT_DATE'].value) / 3600000)"
        },
        "ranges": [
          {
            "from": 0.0,
            "to": 10.0,
            "key": "A 0 - 10"
          },
          {
            "from": 10.0,
            "to": 20.0,
            "key": "B 10 - 20"
          }
        ]
      }
    }
  }
}
```

**Comment by javanna** [comment]
hi @paulohss ,
can you please post the document that your example is based on?

**Comment by paulohss** [comment]
Hi @javanna , thanks for your quick reply.

You can find the indexes here:
https://www.dropbox.com/scl/fi/1hgs6vrr0t2cllv0zsrz4/data.zip?dl=0&oref=e&r=AAVbKET_SxeS5Hp7gwBrdKRe4h5yqTUsijrwhQCeio5vr9tz4I3-UOMzQSDhwC0CX0N2Q3Tcwz192yG5CwUC3sqHysKDZGBethD6SovefzCpwpvPY58XU7DUphw2YQ4jg2vE5Wk8jVZJ-_JtMe2pEcKV_XwP_mgngz-KhT48Dsa8xw&sm=1

**Comment by javanna** [comment]
@nik9000 @jdconrad can either of you have a look please?

**Comment by nik9000** [comment]
> @nik9000 @jdconrad can either of you have a look please?

I can add it to my list.

**Comment by jdconrad** [comment]
@paulohss If you modify the Painless script to
```
((doc['LAST_MODIFIED_DATE'].value - doc['SUBMIT_DATE'].value) / 3600000.0)
```
does this change the results to the same as Groovy?

**Comment by paulohss** [comment]
Wow.
It actually does!

Should I always run the calculations like that?

Thanks

**Comment by jdconrad** [comment]
@paulohss -- What happened here is the way promotion works in Groovy is slightly different from Painless (I'm actually working on documentation for this right now).  Groovy promotes division in this case to a double value automatically, whereas Painless left it as int because all 3 values are ints.  Adding the .0 creates a double forcing Painless to promote all the values to doubles for the division.

**Comment by nik9000** [comment]
@jdconrad, should we close this or wait to close it until your docs are merged?

**Comment by jdconrad** [comment]
I'll go ahead and close as there's nothing actionable here.

**Comment by paulohss** [comment]
Thanks guys.

**Comment by jdconrad** [comment]
@paulohss You're welcome!  If you have any other issues, please feel free to re-open.

**Comment by paulohss** [comment]
Hi @jdconrad 

I use ES 5.1.2 and I'm trying to compute day of week and time of day from a date field and consider timezone at the same time.

my first script is `def d = doc['my_field'].date; d.addHours(10); d.getDayOfWeek();`

The error message is can't find addHours() method

```
"caused_by": {
    "type": "illegal_argument_exception",
    "reason": "Unable to find dynamic method [addHours] with [1] arguments for class [org.joda.time.MutableDateTime]."
},
"script_stack": [
    "d.addHours(10); ",
    " ^---- HERE"
],
```
If I change script to `MutableDateTime d = doc['my_field'].date; d.addHours(10); d.getDayOfWeek();` The error message becomes

```
"caused_by": {
  "type": "illegal_argument_exception",
  "reason": "unexpected token ['d'] was expecting one of [{<EOF>, ';'}]."
},
"script_stack": [
  "MutableDateTime d = doc['relation_denstu. ...",
  "                ^---- HERE"
],
```
Without addHours to adjust timezone, everything is fine. But if I try to adjust timezone dynamically, everything failed. Any help?

**Comment by rjernst** [comment]
@paulohss Please don't ask questions on a closed issue. Elastic maintains a [forum](https://discuss.elastic.co) for questions; github is reserved for verified bug reports and feature requests.
