### ISSUE TITLE
Incomplete reference documentation for 'Highlighting'

### ISSUE THREAD

**Issue by sudo-suhas** [elastic/elasticsearch#23736]
**Elasticsearch version**: 5.2

**Description of the problem**:
In the [Highlighting reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html), there is no mention of `fragmenter` but the [builder](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/HighlightBuilder.java) has an option for the same.

Could the documentation be updated for the same? I do not understand the option well enough to submit a pull request for the same.

**Comment by javanna** [comment]
You are right @sudo-suhas , just note that `fragmenter` is supported only by the plain highlighter. Our docs don't currently cover every single option of each single highlighter implementation, rather the most common options that are supported by all the different implementations. We'd accept a PR for this too.
