### ISSUE TITLE
Incomplete documentation for 'keyed' parameter in Percentiles Aggs

### ISSUE THREAD

**Issue by sudo-suhas** [elastic/elasticsearch#23731]
**Elasticsearch version**: 5.2

**Description of the problem**:
The parameter `keyed`, for associating a unique string key with each bucket and return the ranges as a hash rather than an array, is supported on Percentiles Aggregation and Percentile Ranks Aggregation as can be seen [here](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/metrics/percentiles/PercentilesAggregationBuilder.java#L167-L173) and [here](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/metrics/percentiles/PercentileRanksAggregationBuilder.java#L154-L160).

However, the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-rank-aggregation.html) make no mention of it.

**Comment by sudo-suhas** [comment]
The same is true for Date Histogram Aggregation as well. 
[Date Histogram Docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-bucket-datehistogram-aggregation.html), [Code](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java#L266-L272).
Is the parameter applicable for all aggregations?

**Comment by javanna** [comment]
hi @sudo-suhas the `keyed` argument is supported by range, geo_distance_range, ip_range, histogram, date_histogram, percentiles and percentile_ranks aggregations.  I agree that we should mention that where missing in the docs. Are you up for sending a pull request on that?

**Comment by sudo-suhas** [comment]
@javanna I'll be more than happy to submit a pull request :smile: . It should be enough to keep it similar to the documentation which can be found [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-range-aggregation.html) right? Is there anything else I need to keep in mind other than the instructions specified [here](https://github.com/elastic/elasticsearch/blob/master/docs/README.asciidoc)?

Although this is a slightly different issue, in the [Highlighting reference](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html), there is no mention of `fragmenter` but the [builder](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/fetch/subphase/highlight/HighlightBuilder.java) has an option for the same.

**Comment by javanna** [comment]
sounds good @sudo-suhas will be waiting for your PR then. As for the other issue, please open another issue or just send a PR that addresses that problem.

**Comment by sudo-suhas** [comment]
@javanna I have created an issue(#23736) for the highlighting issue.

**Comment by sudo-suhas** [comment]
@javanna I have found another inconsistency in the documentation for Geo Distance Aggregation. Should I open an issue for it? I am worried that I might be spamming issues.
