### ISSUE TITLE
Elasticsearch query directly through Java API without creating relevant API objects

### ISSUE THREAD

**Issue by aravindtga** [elastic/elasticsearch#23749]
**Elasticsearch version**: 5.1.1
**JVM version**: 1.8
**OS version**: Windows 10

I am using the following elasticsearch query to fetch the details,

`{
	"query": {
		"bool": {
			"must": {
        		"match_all": {}
    		},
			"filter": {
				"bool": {
					"should": [
					{"match": {
						"val": "GET"
					}}]
				}
			}
		}
	}
}`

It is working fine and given the result as required. 

I want to execute the same query through java and get the same results and tried the following,
`getClient().prepareSearch(esIndex)
				.setQuery(QueryBuilders.queryStringQuery(QUERY)).execute().actionGet();`
				
It is not returning the data and throw some query format wrong exception as well.

Is there any Java API available using which the same query can be executed?

**NOTE**: There is a possibility available to create the boolquery and aggregation builders in java api and execute the same. I am just curious to find a way to execute this query directly through elasticsearch java api

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
