### ISSUE TITLE
Geo-Shape datatype and ignore_malformed

### ISSUE THREAD

**Issue by murdav** [elastic/elasticsearch#23747]
Dear All,

This issue it to ask you the possibility to have ignore_malformed parameter available also for geo-shape datatype.
A futher example is the availability of the [param for geo-point datatype](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/geo-point.html#geo-point-params).

Example:

```
PUT test
{
    "settings" : {
        "number_of_shards" : 1
    },
    "mappings" : {
        "type1" : {
            "properties" : {
                "name" : { "type" : "text" },
                "bbox": {
                  "type": "geo_shape",
                  "precision": "10km",
                  "tree": "quadtree",
                  "ignore_malformed": "true"
                  }
            }
        }
    }
}
```

For example I would need to add the BBOX field, but it's possible that the values are not in the known range, hence I got:

`'reason': 'Bad X value 180.00001 is not in boundary Rect(minX=-180.0,maxX=180.0,minY=-90.0,maxY=90.0)'},
`

It will be great to skip only the above-mentioned field and not the entire record. I could also think adding a [null value ](https://www.elastic.co/guide/en/elasticsearch/reference/current/null-value.html) and search for records that have null_value/blank/None/Empty field.

Initial discussion:
https://discuss.elastic.co/t/geo-shape-and-unsupported-validation-method-ignore-malformed/79887

Thanks you once again,

D

**Comment by hudsonb** [comment]
+1, I was hoping to be able to do this very thing (add ignore_malformed: true to geo_shape fields) as I am getting invalid polygons on occasion from a 3rd party web service and it's causing the entire document to fail to index rather than skipping the one bad field.

**Comment by hartfordfive** [comment]
👍 Similar to this issue which is related to objects: https://github.com/elastic/elasticsearch/issues/12366.
