### ISSUE TITLE
Fuzzy query parsing logic allows illegal syntax

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#23759]
A user [ran into an issue](https://discuss.elastic.co/t/apply-fuzziness-on-multiple-terms-in-a-not-analyzed-field/79798/4) when they passed an array for the "value" property in a fuzzy query:

	{
	  "query": {
		"fuzzy": {
		  "name": {
			"value": [
			  "donald",
			  "trump",
			  "president"
			],
			"boost": 1,
			"fuzziness": 1,
			"prefix_length": 0,
			"max_expansions": 50
		  }
		}
	  }
	}

Rather than failing with a parse error (e.g. "expected string not an array") it runs a query which fails to match anything.

**Comment by olcbean** [comment]
In this case the `FuzzyQueryBuilder` would actually result in `"value": "]"` :  hence the unexpected result.

If OK I would like to try to fix the issue.

**Comment by cbuescher** [comment]
@olcbean I already fixed it and was about to push the PR, sorry I should have assigned this to me.
