### ISSUE TITLE
Confusing documentation for Date Histogram Aggregation

### ISSUE THREAD

**Issue by sudo-suhas** [elastic/elasticsearch#23756]
**Elasticsearch version**: 5.2

**Description of the problem**:
On the reference documentation page for [Date Histogram Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#_scripts), it says the following
> Like with the normal [histogram](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html), both document level scripts and value level scripts are supported

However on the [histogram page](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html), there is no mention of scripts what so ever. Both [`HistogramAggregationBuilder`](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/HistogramAggregationBuilder.java) and [`DateHistogramAggregationBuilder`](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java) extend [`ValuesSourceAggregationBuilder`](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/support/ValuesSourceAggregationBuilder.java#L187-L204) which has getters and setters for `script`.

Shouldn't the reference documentation for Histogram Aggregation have a section for scripts? Also not entirely sure what this means - _both document level scripts and value level scripts are supported_

**Comment by markharwood** [comment]
>not entirely sure what this means - both document level scripts and value level scripts are supported

Agreed - looks like some more clarity here and on related `histogram` agg is needed. I suspect the "document-level" and "term-level" scripts relate to the gathering of raw values from documents and the presentation of terms in results (the script section talks about controlling ordering and filtering of results but no example i provided).

**Comment by sudo-suhas** [comment]
@markharwood Actually, the appropriate documentation for this is present in [Range Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-range-aggregation.html#_script_12)

**Comment by colings86** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/23772 which encompasses the inconsistencies in the docs more comprehensively
