### ISSUE TITLE
Create index : unable to use custom analyzer in default mapping at index creation time

### ISSUE THREAD

**Issue by MarneusCalgarXP** [elastic/elasticsearch#23755]
**Elasticsearch version**: 5.2.2

**Plugins installed**: [analysis-phonetic]

**JVM version**: Oracle java 1.8.0_77 (build 1.8.0_77-b03)

**OS version**: Windows 7

**Description of the problem including expected versus actual behavior**:

When using create index API, I can define custom analyzers in "analysis" section.
I can also define the default mapping in the "mapping" section.
But when I want to use one of my custom analyzers in the mapping section, ElasticSearch fails.

**Steps to reproduce**:
`
DELETE test_custom_analyzer
`
`
PUT test_custom_analyzer
{
  "analysis": {
    "analyzer": {
      "my_analyzer": {
        "tokenizer": "whitespace",
        "filter": [
          "elision",
          "lowercase",
          "asciifolding"
        ]
      }
    }
  },
  "mappings": {
    "_default_": {
      "properties": {
        "field1": {
          "type": "text",
          "analyzer": "my_analyzer"
        }
      }
    }
  }
}
`

**Provide logs (if relevant)**:

elasticsearch response:
`{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "analyzer [my_analyzer] not found for field [field1]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [_default_]: analyzer [my_analyzer] not found for field [field1]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "analyzer [my_analyzer] not found for field [field1]"
    }
  },
  "status": 400
}`

**Comment by MarneusCalgarXP** [comment]
Note : after a few tests, it seems that elastic ignores the "analysis" section when you provide a "mapping" section. If you provide a "mapping" section, you have to embed the "analysis" section into a "settings"/"index" section.

The following reports no error:
`PUT test_custom_analyzer
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "my_analyzer": {
            "tokenizer": "whitespace",
            "filter": [
              "elision",
              "lowercase",
              "asciifolding"
            ]
          }
        }
      }
    }
  },
  "mappings": {
    "_default_": {
      "properties": {
        "field1": {
          "type": "text",
          "analyzer": "my_analyzer"
        }
      }
    }
  }
}`

**Comment by markharwood** [comment]
Yep, it looks like illegal syntax is ignored in this API e.g.

	PUT test
	{
		"FOO_SHOULD_BE_ILLEGAL_HERE": {
			"BAR_IS_THE_SAME": 42
		},
		"mappings": {
			"test": {
				"properties": {
					"field1": {
						"type": "text"
					}
				}
			}
		}
	} 

	{
	  "acknowledged": true,
	  "shards_acknowledged": true
	}

Your illegal "analysis" section like my illegal "foo" section above is overlooked and could give the false impression that it was accepted.

**Comment by clintongormley** [comment]
We should complain about unknown keys at the same level as `mappings`/`settings`

**Comment by olcbean** [comment]
It looks like the top level keys for create index (`mappings` `settings`and `aliases`) are not verified. 
I would like to have a go at it :)
