### ISSUE TITLE
Link to javadocs

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#23761]
_From @eskibars on March 23, 2017 18:13_

We recently started publishing javadocs at https://artifacts.elastic.co/javadoc/org/elasticsearch/<project>/<version>/index.html

It'd be great to link the associated java projects/clients to these docs, e.g.:
- [ ] https://www.elastic.co/guide/en/elasticsearch/client/java-api/[VERSION]/transport-client.html to https://artifacts.elastic.co/javadoc/org/elasticsearch/elasticsearch/[VERSION]/index.html?org/elasticsearch/client/transport/TransportClient.html)
- [ ] Somewhere under https://www.elastic.co/guide/en/elasticsearch/client/java-rest/[VERSION]/_getting_started.html to https://artifacts.elastic.co/javadoc/org/elasticsearch/client/rest/[VERSION]/index.html

_Copied from original issue: elastic/docs#154_

**Comment by MentalMittal** [comment]
Hi. This is my first-time contributing and would like to take up this issue. But the only problem is that I don't have any idea how to do this. Can someone help me in this?

**Comment by nik9000** [comment]
Have a look in the `docs` directory in the Elasticsearch source code. The thing to make sure of is that the version numbers in the links line up. You can use `:elasticsearch-javadoc:` to reference the Elasticsearch javadocs root url.

**Comment by MentalMittal** [comment]
i thank you for giving me a response. I am very sorry but I don't see any links like   https://www.elastic.co/guide/en/elasticsearch/client/java-api/[VERSION]/transport-client.html which got to be changed. Can you tell me how to do that ?

**Comment by nik9000** [comment]
> I am very sorry but I don't see any links like https://www.elastic.co/guide/en/elasticsearch/client/java-api/[VERSION]/transport-client.html which got to be changed. Can you tell me how to do that ?

That is generated from one of the files in [here](https://github.com/elastic/elasticsearch/tree/master/docs/java-api).

**Comment by MentalMittal** [comment]
I have been looking at these files for 10 hours but I don’t get where is the link and what to write instead. I have read the asciidoc documentations and it says that the link will be after `link:` but there isn’t any `link:` in the files. Can you give me one example of what to change and to what? and the rest I can find and change.
