### ISSUE TITLE
Conflicting line width in the stylecheckTest and CONTRIBUTING.md

### ISSUE THREAD

**Issue by olcbean** [elastic/elasticsearch#23768]
In the [CONTRIBUTING.md](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md) it is stated that the line width should be set to 140

> Please follow these formatting guidelines:
>
> - Java indent is 4 spaces
> - Line width is **140** characters
> ...

However running `gradle check` will complain for any line longer than 100 chars : 

`<error line="125" severity="error" message="Line is longer than 100 characters (found 119)." source="com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck"/>`

For consistency should [CONTRIBUTING.md](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md) be changed or the checkstyleTest?

**Comment by olcbean** [comment]
I just saw that according to https://github.com/elastic/elasticsearch/commit/e8b2f9afd4d38b1e279e15d57c78ac033f9569f9 the line width has been changed to 100, so I will just go ahead and update the CONTRIBUTING.md

**Comment by jasontedor** [comment]
No need for a PR, I will handle this.

**Comment by olcbean** [comment]
Oh.. I did not see that... 

Here is https://github.com/elastic/elasticsearch/pull/23769 anyway :)

**Comment by jasontedor** [comment]
Sorry, and I only now saw this and already pushed df67f83834a1d35fdb09bab948e9c5b69ea12b81. Thanks for the PR either way.
