### ISSUE TITLE
Customize Similarity/score for range query

### ISSUE THREAD

**Issue by nbqyqx** [elastic/elasticsearch#23765]
**Elasticsearch version**:
2.3.3
**Plugins installed**: []
es-customized-similarity
**JVM version**:
open idk 1.8
**OS version**:
mac
**Description of the problem including expected versus actual behavior**:
Customize Similarity/score for range query
I have add customized es plugin for term query. But it does not work well for the rang query. My question is how can I disable the queryNorm or customize the queryNorm for range query.

**Steps to reproduce**:
 1.install 2.3.3 es
 2.install term query similarity plugin
 3.range search

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by jpountz** [comment]
I don't think there is a good way to combine range queries and term queries and get "good" scores. You mention query norm, but term freq and doc freq are problematic too since those metrics either do not make sense for ranges or would be too costly to compute. It is fairly unusual to want range queries to take part of the scores, I'm wondering that you might just want to use them for filtering?

**Comment by nbqyqx** [comment]
The scenario(4 queries in should bool query) wants the range queries be part of the score. If we can disable the query norm for the range query, then the score=boost*isMatch. The customized term query score=boost*isMatch also, hence if we match all 4 conditions, the score=100.

{
  "from":0, "size":10,
  
  "query": {
     "bool" : {
       			"disable_coord":"true",
                "should": [
                  {"term" : { "building_house_type_building_city_id" : "112", "boost":0 }},
                  {"term" : { "building_house_type_building_region_id" : "1195", "boost":40 }},
                  {"term" : { "building_house_type_house_room_type_s": "3", "boost":20}},
                  { "range" : {
                      "building_house_type_covered_area": {
                                "gte":130,
                                  "lte":150,
                                  "boost":20
                    
                        }
                    }
                  },
                  { "range" : {
                      "building_house_type_price": {
                                "gte":105675200,
                                  "lte":255675200,
                                  "boost":20
                    
                        }
                    }
                  }
                ]
                 
     }
  }
	
}

**Comment by jpountz** [comment]
OK I get what you are trying to do now. I think disabling `queryNorm` won't be enough, you need to disable the contribution from the term and doc freqs as well for it to work, which should be possible with the `boolean` similarity that we are adding: #23637.

**Comment by jpountz** [comment]
You can already achieve a similar result today by wrapping the `term` queries under a `constant_score` query and setting the boost on the `constant_score` query.

**Comment by nbqyqx** [comment]
the query norm still has the side effect. I want the score 100 not  if all match the query

"_explanation": {
"value": 1.3867505,
"description": "sum of:",
"details": [
  {
"value": 1.3867505,
"description": "sum of:",
"details": [
  {
"value": 0.5547002,
"description": "ConstantScore(building_house_type_building_region_id: 	+), product of:",
"details": [
  {
"value": 40,
"description": "boost",
"details": [],
},
  {
"value": 0.013867505,
"description": "queryNorm",
"details": [],
}
],
},
  {
"value": 0.8320503,
"description": "ConstantScore(building_house_type_covered_area:[130.0 TO 140.0]), product of:",
"details": [
  {
"value": 60,
"description": "boost",
"details": [],
},
  {
"value": 0.013867505,
"description": "queryNorm",
"details": [],
}
],
}
],
},


======
{
  "query": {
  	"bool" : {
  		"should": [   
        	{	
            	"constant_score": {
    				"filter":{ 
    					"term" : {
    						"building_house_type_building_region_id": "1195"
    					}
    				},
        			"boost": 40
            	}
            },
          	{	
            	"constant_score": {
    				"query":{ 
    					"range" : {
                      		"building_house_type_covered_area": {
                                "gte":130,
                                  "lte":140
                    
                        	}
                        }
                    },
        			"boost": 60
                }
            }
         ]
    }
   
  }
	
}

**Comment by nbqyqx** [comment]
I tried the boolean similarity found it can not be applied to range query either:
========
{
  "query": {
     "bool" : {
       			"disable_coord":"true",
                "should": [
                  {"term" : { "building_house_type_building_city_id" : "112", "boost":0 }},
                  {"term" : { "building_house_type_building_region_id" : "1195", "boost":40 }},
                  {"term" : { "building_house_type_house_room_type_s": "3", "boost":20}},
                  {
                    	
                    
                                "term" : {
                      				"building_house_type_covered_area": 
                                		"138",
                                		"boost":20
                        			
                    			}
                            
                        
                  },
                  { "range" : {
                      "building_house_type_price": {
                                "gte":105675200,
                                  "lte":255675200,
                                  "boost":20
                    
                        }
                    }
                  }
                ]
                 
     }
  }
	
}
=====

"_explanation": {
"value": 80.99627,
"description": "sum of:",
"details": [
  {
"value": 80.99627,
"description": "sum of:",
"details": [
  {
"value": 0,
"description": "ConstantScore(building_house_type_building_city_id:`p), product of:",
"details": [
  {
"value": 0,
"description": "boost",
"details": [],
},
  {
"value": 0.04981355,
"description": "queryNorm",
"details": [],
}
],
},
  {
"value": 40,
"description": "weight(building_house_type_building_region_id: 	+ in 1970) [PerFieldSimilarity], result of:",
"details": [
  {
"value": 40,
"description": "singlematch",
"details": [
  {
"value": 1,
"description": "fieldNorm(doc=1970)",
"details": [],
},
  {
"value": 40,
"description": "queryWeight",
"details": [],
}
],
}
],
},
  {
"value": 20,
"description": "weight(building_house_type_house_room_type_s:` in 1970) [PerFieldSimilarity], result of:",
"details": [
  {
"value": 20,
"description": "singlematch",
"details": [
  {
"value": 1,
"description": "fieldNorm(doc=1970)",
"details": [],
},
  {
"value": 20,
"description": "queryWeight",
"details": [],
}
],
}
],
},
  {
"value": 20,
"description": "weight(building_house_type_covered_area:`( in 1970) [PerFieldSimilarity], result of:",
"details": [
  {
"value": 20,
"description": "score(, doc=1970), computed from:",
"details": [
  {
"value": 20,
"description": "query boost",
"details": [],
}
],
}
],
},
  {
"value": 0.996271,
"description": "building_house_type_price:[1.056752E8 TO 2.556752E8], product of:",
"details": [
  {
"value": 20,
"description": "boost",
"details": [],
},
  {
"value": 0.04981355,
"description": "queryNorm",
"details": [],
}
],
}
],
},

**Comment by jpountz** [comment]
Query norm is only a feature of the `classic` similarity, so I suspect you are somehow opting in for it at index creation time by doing something like this:

```
PUT /my_index
{
  "settings": {
    "index": {
      "similarity": {
        "default": {
          "type": "classic"
        }
      }
    }
  }
}
```

If that is the case, just remove these index settings, which will cause Elasticsearch to use BM25 as the base similarity, which does not perform query normalization.

**Comment by nbqyqx** [comment]
I have no classic  similarity setting, instead using custom boolean similarity
=====
"settings": {
    "index": {
      "refresh_interval": "5s",
      "max_result_window" : 500000
    },
    "similarity" : {
      "custom_similarity" : {
        "type" : "essimilarity"
      },
      "boolean_similarity" : {
        "type" : "boolean"
      }
    }

**Comment by jpountz** [comment]
Oh sorry I'm seeing you are using Elasticsearch 2.3. I thought you were on 5.x since you were able to test the boolean similarity. Then you need to explicitly opt in for BM25. In order to do that, you should close your index, update the default similarity and open the index again. The update call should look something like that:

```
PUT /my_index/_settings
{
  "settings": {
    "index": {
      "similarity": {
        "default": {
          "type": "BM25"
        }
      }
    }
  }
}
```

**Comment by nbqyqx** [comment]
It does work when I removed the field similarity setting and set the default similarity to BM25. :)
Thanks~

**Comment by nbqyqx** [comment]
set the default similarity to my customized boolean similarity also get the expected result.
My question is why set the default similarity from classic to BM25 or mine will change the range query score?
