### ISSUE TITLE
Some characters return blank tokens with standard tokenizer and icu_folding filter.

### ISSUE THREAD

**Issue by A-Hall** [elastic/elasticsearch#23764]
**Elasticsearch version**: 5.2.2

**Plugins installed**: ICU Analysis plugin

**JVM version**:  1.8.0_121

**OS version**: CentOS 7

**Description of the problem including expected versus actual behavior**:  Some special characters are returning empty tokens instead of no tokens when using the standard analyzer with the icu_folding filter.  The customer did a good job explaining the issue:

> We've encountered a couple of situations where the analyzer returns empty characters for tokens. For example, if you use the standard tokenizer or the uax_url_email tokenizer, and the icu_folding filter, you can get an empty token with the input 'ˆ' which is not a carat, but U+02C6, which is a circumflex modifier character. Granted, this is not really good input, and we found it when someone pasted binary data in a document that was indexed, but is it reasonable to expect the analyzer to only return non-empty tokens? 
> 
> (In this case, it is the icu_folding filter that causes the problem. The modifier character is a unicode ALetter, so the tokenizer just returns it as-is, even though it does not have a subsequent character to modify. The filter, which removes diacritical marks and folds letters to lowercase, filters out the diacritical, hence the empty token. If you were to follow U+02C6 with an alphabet letter, the tokenizer would return both codepoints as a single token, and the filter would strip out the U+02C6, leaving just the lowercase version of the alphabet letter.)

**Steps to reproduce**:

 1.
```
PUT icu_sample
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "folded": {
            "tokenizer": "standard",
            "filter": [
              "icu_folding"
            ]
          }
        }
      }
    }
  }
}
```

 2.
```
POST icu_sample/_analyze
{
  "analyzer": "folded",
  "text": "ˆ"
}
```

 3. Returns:
```
{
  "tokens": [
    {
      "token": "",
      "start_offset": 0,
      "end_offset": 1,
      "type": "<ALPHANUM>",
      "position": 0
    }
  ]
}
```

**Comment by A-Hall** [comment]
Additionally:
> It looks like U+02B0 through U+0971 from http://www.fileformat.info/info/unicode/category/Lm/list.htm reproduce it.

**Comment by jimczi** [comment]
That's the expected behavior. If you input an accent modifier in a standard tokenizer it will be kept as a token. The `icu_folding` will then removes that character leaving a blank token in the stream.
Everything works, you'll just build an inverted list for this empty token.
It is not expected to use a standard tokenizer on a binary input and even doing so does not yield any exception/bug so I'll close this as resolved.
