### ISSUE TITLE
Incomplete docs for script/missing/format in Aggregations reference

### ISSUE THREAD

**Issue by sudo-suhas** [elastic/elasticsearch#23772]
**Elasticsearch version**: 5.2

**Description of the problem**:
There are around 25 aggregation builders which extend [`ValuesSourceAggregationBuilder`](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/support/ValuesSourceAggregationBuilder.java)
This class adds the following options to an aggregation

- field
- script
- missing
- format
- time_zone
- value_type <- Internal field

I am not able to see the rationale for extending this class in some cases such as Children aggregation which
only has a single option `type` for mapping between child and parent.

In any case, I am opening this issue to report the places where documentation for inherited fields of `ValuesSourceAggregationBuilder` is missing by cross referencing test cases which link back to this class. 
It is possible that the test cases did not cover all possible options. Inputs from elasticsearch core team would be very helpful.

- [Histogram Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html#_response_format):
  + script
  + format
- [Date Histogram Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-bucket-datehistogram-aggregation.html):
  + script - Incomplete, Tracked in issue #23756
- [Range Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-range-aggregation.html):
  + format
  + missing
- [Date Range Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-daterange-aggregation.html):
  + script
  + missing
- [Geo Distance Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geodistance-aggregation.html):
  + missing
- [IP Range Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-iprange-aggregation.html):
  + missing
- [Diversified Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-bucket-diversified-sampler-aggregation.html):
  + missing
- [Significant Terms Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-bucket-significantterms-aggregation.html)
  + script
  + format
  + missing
- [Terms Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-bucket-terms-aggregation.html)
  + format
- [Avg Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-metrics-avg-aggregation.html)
  + format
- [Geo Bounds Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-metrics-geobounds-aggregation.html)
  + missing
- [Geo Centroid Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-metrics-geocentroid-aggregation.html)
  + script
  + missing
- [Max Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-metrics-max-aggregation.html)
  + format
- [Min Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-metrics-min-aggregation.html)
  + format
- [Percentiles Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-metrics-percentile-aggregation.html)
  + format
- [Extended Stats Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-metrics-extendedstats-aggregation.html)
  + format
- [Stats Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-metrics-stats-aggregation.html)
  + format
- [Sum Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-metrics-sum-aggregation.html)
  + format
- [Value Count Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/search-aggregations-metrics-valuecount-aggregation.html)
  + missing

**Comment by polyfractal** [comment]
@elastic/es-search-aggs

**Comment by debadair** [comment]
[docs issue triage]

**Comment by lockewritesdocs** [comment]
This issue hasn’t been updated in 3+ years so I’m closing it. We can revisit if needed.

**Comment by javanna** [comment]
Does the issue in the docs still exist? Have we determined that it's something we don't want to fix? I am hesitant on closing issues based on lack of activity alone.

**Comment by lockewritesdocs** [comment]
@javanna, we're going through the backlog to close out old issues so that we can focus on upcoming work. If someone from your team can own this issue, please assign it to them and we can help get this work merged.
