### ISSUE TITLE
Painless and Working with Dates

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#23775]
Some functionality in Elasticsearch requires one to parse dates to a custom format so we can return this in the output. Some examples of this would be:

- Scripted fields with a custom date format
- Scripted aggregation (though date histogram is better/easier)
- Watcher outputs (expose the date in a custom format)

It would be great to add some examples in the documentation around how to manipulate dates. Most of the examples show that the `SimpleDateFormat` is very useful in Java to do this, however this is not available in Painless (right?).

Relates: https://github.com/elastic/elasticsearch/issues/22720

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/23777
