### ISSUE TITLE
Document action field values in Tasks API docs?

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch#23773]
Should the different values of the `action` field in the task listing be documented in the Tasks API docs?  For example, what the `"cluster:monitor/tasks/lists[n]"` means.  Is there a definitive list of these values or the naming convention we can reference?

**Comment by bleskes** [comment]
I understand the sentiment and this would be great to have. That said, those are the internal messages nodes sent to each other (each network request is logged as a task). There are so many of them that this will be a monumental task to go and document them all. On top of it it, they change from time to time and I don't think we're ready to commit to keeping documentation up to date. As said, I would love to have it but I don't think it's realistic for this to happen any time soon. I'm going to close as won't fix.
