### ISSUE TITLE
Lookup mechanism has bad performance for large terms list

### ISSUE THREAD

**Issue by toniov** [elastic/elasticsearch#23782]
According to the docs, Terms Query [lookup mechanism](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html#query-dsl-terms-lookup) is supposed to be used to filter a lot of terms.

I tested it with Elasticsearch version `2.3.4` with a 2 million documents index, and filtering with around 20 thousand terms make the query quite slow (more than 500ms).

There is a related issue here: https://github.com/elastic/elasticsearch/issues/18829

If it's not prepared to filter thousands of terms properly, taking into account that in Twitter there are many users with thousands of followers, I think a Twitter example should not be used in the official docs. Maybe a warning about performance should be written there.

Is there any way to speed up this kind of queries? Any plan for improvements?

**Comment by jpountz** [comment]
I think we should set expectations in the docs indeed. Large terms filters are problematic in general, even if the lookup mechanism is not used.

**Comment by mayya-sharipova** [comment]
Closing this issue, as this has been addressed in https://github.com/elastic/elasticsearch/pull/27968
in the `terms-query.asciidoc`

**Comment by fzyzcjy** [comment]
> a Twitter example should not be used in the official docs

@toniov Hi I wonder which example do you mean? Is it [this example](https://github.com/elastic/examples/tree/master/Common%20Data%20Formats/twitter), or there was some more advanced ones? Thanks!

**Comment by toniov** [comment]
@fzyzcjy It was just a short example in the lookup mechanism [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-terms-query.html#_terms_lookup_twitter_example).

**Comment by fzyzcjy** [comment]
@toniov Thanks!

**Comment by rex-remind101** [comment]
Hello,

According to this post, 20k terms is slow. Yet, according to https://github.com/elastic/elasticsearch/pull/27968/files#diff-4e93d5bf58e29274e79023abea854a60R133 65k terms is defensive, i.e. possibly not slow. This seems like a contradiction, or did something change between the writing of this post and a later version of Elasticsearch.

Thanks!

**Comment by rex-remind101** [comment]
@toniov thoughts ^ ?

**Comment by toniov** [comment]
@rex-remind101
It's been a long time since then, so not sure of the current status for this kind of query. In the testing I did, around 20,000 terms made the query very slow, but under other circumstances it might not. Like running a Elasticsearch cluster under a different set up.

Getting a number that would much every case is not possible in my opinion. Not sure from where that 65k default max that the Elasticsearch team chose came from to be honest, but might not be a reference depending on your case.

My advice is that you make a load test for your case and see the results. And also, I would try to avoid in general using term queries with many terms and would look for alternatives.

Good luck!

**Comment by toniov** [comment]
@rex-remind101
It's been a long time since then, so not sure of the current status for this kind of query. In the testing I did, around 20,000 terms made the query very slow, but under other circumstances it might not. Like running a Elasticsearch cluster under a different set up.

Getting a number that would fit every case is not possible in my opinion. Not sure from where that 65k default max that the Elasticsearch team chose came from to be honest, but might not be a reference depending on your case.

My advice is that you make a load test for your case and see the results. And also, I would try to avoid in general using term queries with many terms and would look for alternatives.

Good luck!
