### ISSUE TITLE
Log4j's ParameterizedMessage has a static ThreadLocal<StringBuilder>

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#23798]
I was just looking at a heap dump from a user where some threads we holding strong references to very large string builders. The problem seems to come from Log4j's ParameterizedMessage which uses a static `ThreadLocal<StringBuilder>` in order to reuse memory when building messages. Unfortunately, the string builders never decrease in size, so this thing can only grow over time given that we use fixed thread pools.

**Comment by rjernst** [comment]
I wonder if we should add `ThreadLocal` to the forbidden list in third-party-audit? This won't stop us from using libraries with it, but it would make us aware, and we could then document in the excludes list why it is ok for each dependency.

**Comment by jpountz** [comment]
+1 to auditing dependencies for threadlocals
I also opened an issue against log4j, suggesting that this threadlocal be removed: https://issues.apache.org/jira/browse/LOG4J2-1858.

**Comment by kumar1005** [comment]
i would love to solve this issue.

**Comment by jpountz** [comment]
@kumar1005 This is an upstream issue, so it would have to be addressed in Log4j2 directly.

**Comment by jpountz** [comment]
This has been fixed upstream and should be fixed in log4j 2.9.

**Comment by jpountz** [comment]
According to them, 2.9 is not going to happen anytime soon. Forking the fixed class does not seem easy either as it relies on several pkg-private classes, so I'm leaning towards waiting for 2.9 to be released since I don't have the cycles to do any better.
