### ISSUE TITLE
how to access the _index object through painless inline

### ISSUE THREAD

**Issue by chembohuang** [elastic/elasticsearch#23808]
i need the POSITIONS info,  it's ok to get it by the groovy language:
```json
"script": {
        "inline": "def s = 0;termInfo=_index['goods_name_separate'].get('book',_POSITIONS| _CACHE);for(pos in termInfo){s++; break;}; return s;",
        "lang": "groovy"
      }
```
but how to get the _index object through painless and java? 
i got compile error when turned lang to painess.

**Comment by tvernum** [comment]
Please ask this question on our [discuss forum](https://discuss.elastic.co/) where we can provide better support.
Elastic uses GitHub issues for confirmed bugs and feature requests which have been discussed on the forums.

Thank you.
