### ISSUE TITLE
Request to add "ip range" field datatype

### ISSUE THREAD

**Issue by presto9292** [elastic/elasticsearch#23811]
Now that ES 5.2.0 introduced support for Numeric and Date Range field types, is it possible to add support for IP range field types , i.e. ipv4_range and ipv6_range

**Comment by martijnvg** [comment]
Ip ranges have recently been added to Lucene: LUCENE-7738
It should be available with Elasticsearch 6.0 (The lucene change hasn't been backed ported to the Lucene version that Elasticsearch 5.x uses)

**Comment by presto9292** [comment]
Any chance of having this in the upcoming 6.0 release ?

**Comment by dadoonet** [comment]
IP Range is in 6.0: https://www.elastic.co/guide/en/elasticsearch/reference/master/range.html

Wondering why this issue is still opened. @clintongormley Should we close it?

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/24433
