### ISSUE TITLE
Can rollover api add condition for absolute time?

### ISSUE THREAD

**Issue by myrfy001** [elastic/elasticsearch#23813]
**Describe the feature**:
Now, the rollover api can roll to a new index after 1d, so, there is a problem(suppose all the time below is in UTC).

Suppose a new index name is `<logs-{now/d}-1>`and is create on `2017-01-01 23:59:59`, and then I want to roll it when each day begins, so I set up a crontab task to execute rollover api on `00:00:00` every day. Because the 24 hours has not been reached, so the api will do nothing.

Thus, I have a index called `logs-20170101-000001` but it actually saves the data for `2017-01-02`

And, the next time the crontab executs the rollover api will be on 2017-01-03 00:00:00, so I have a new index named `logs-20170103-000002` and skiped `logs-20170102-000002`

So, can there be a new condition that can be used for a absolute time?

**Comment by clintongormley** [comment]
The idea of the rollover API is to free you from time based indices.  But you do have options:  either you can pass in your own index name when you call rollover, or you could use a pattern like `<logs-{now-1h/d}-1>`

**Comment by myrfy001** [comment]
I think this will not solve the problem.
Suppose you use a roll over condition `1d`, and created the first index at `2017-01-01 12:00:00`, Although you can pass in your own index name when you call rollover, or you could use a pattern like `<logs-{now-1h/d}-1>`, but any call to the roll over api won't take action before 24 hours.

That is, every index with a date as prat of it's name will have mixed data of two days.

You can't ask a user to create the first Index at a certain time to make the following index have the right segmentation.  eg, If anyone want to have a index roll over at `00:00:00 UTC`, you shouldn't tell him that he must take a cup of coffee, stay late into night, and create the first index at `00:00:00 UTC`.
