### ISSUE TITLE
Simple Query String Query: Allow ? and * parameters to be used as wildcard within a string

### ISSUE THREAD

**Issue by weberhofer** [elastic/elasticsearch#23821]
It would be great if we could use "?" and "*" within a word to find e.g. all occurrences of "hello" and "hallo" searching for "h?llo". Or another example to search for "Kir*tan" to find "Kirgistan" and "Kirgisistan".

**Comment by cbuescher** [comment]
Hi, this is already possible with the 'query_string' query. Is there a particular reason why you think this should be included in 'simple_query_string' as well?

**Comment by weberhofer** [comment]
The query_string seems to be easier to use for average customers. It also allows me to limit the query on specific fields.

**Comment by cbuescher** [comment]
After discussion we decided that this is not something we're not keen on supporting. The functionality exists already with other queries, we want to increase the amount of options of the `simple_query_string`. Also the fact that wildcard queries can use a lot of memory and perform badly makes them less ideal for a "simple" query type.

**Comment by clintongormley** [comment]
to add to this, the simple query string tries to keep the number of special characters low, and ?  is a character often found in text

**Comment by weberhofer** [comment]
Thank you for taking it into consideration.
