### ISSUE TITLE
doc_values mapping cannot be updated (the documentation indicates they can be disabled)

### ISSUE THREAD

**Issue by ismael-hasan** [elastic/elasticsearch#23820]
**Elasticsearch version**: 5.X

The documentation states that doc_values can be disabled in already created fields; this is not possible, doc_values cannot be enabled/disabled after an index is created. 
cc/ @jimczi could you please confirm? 

[Updating field mappings](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/indices-put-mapping.html#updating-field-mappings):

> Updating field mappings
In general, the mapping for existing fields cannot be updated. There are some exceptions to this rule. For instance:
    new properties can be added to Object datatype fields.
    new multi-fields can be added to existing fields.
    doc_values can be disabled, but not enabled.
    the ignore_above parameter can be updated.

**Comment by rjernst** [comment]
This behavior was changed in 5.0 (#16147) but the docs weren't updated. @ismael-hasan Would you be interested in opening a PR to change the docs?
