### ISSUE TITLE
Feature Request/Help : Terms Filter Execution/Caching Optimization

### ISSUE THREAD

**Issue by anjishnu** [elastic/elasticsearch#23835]
In elastic search 1.4 there were different ways of optimizing cacheing for terms filters
https://www.elastic.co/guide/en/elasticsearch/reference/1.4/query-dsl-terms-filter.html

Is there any way to access these settings in ES 5.1? If so how? If not, how are terms filters cached now and how does one go about optimizing cacheing in this case?

**Comment by anjishnu** [comment]
If there's no way to configure the cache optimization - could we please have those knobs back?

**Comment by jpountz** [comment]
Why do you need them back, is the current behaviour bad for your case? I'd rather improve the default behaviour to work better for you than add those knobs back. They made many queries slow by over-caching so I'd really like not to add them back.

**Comment by jpountz** [comment]
Closing. If you know of cases that the current strategy makes wrong decisions, please open a new issue.
