### ISSUE TITLE
Bool minimum_should_match with "should" clause clarity

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#23831]
The [bool query docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/query-dsl-bool-query.html) aren't clear - it does say " In a boolean query with no must or filter clauses, one or more should clauses must match a document. ", but what it doesn't say is that when there IS a must or filter clause, then 0 should clauses must match.   

Recommended adding something (to the _should_ clause section) like:

> When a must or filter clause is present, minimum_should_match defaults to 0.

**Comment by archie-sh** [comment]
The behaviour is not the same if you nest the should inside a filter for example 

`{
  "size": 10,
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "filter": {
              "exists": {
                "field": "id"
              }
            },
            "should": [
              {
                "term": {
                  "facilities": {
                    "value": "KITCHEN"
                  }
                }
              },
              {
                "term": {
                  "facilities": {
                    "value": "INTERNET"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}`

then minimum_should_match is 1. If I write the following query 

`{
  "size": 10,
  "query": {
    "bool": {
      "filter" : {
        "exists": {
          "field": "id"
        }
      },
      "should": [
        {
          "term": {
            "facilities": {
              "value": "KITCHEN"
            }
          }
        },
        {
          "term": {
            "facilities": {
              "value": "INTERNET"
            }
          }
        }
      ]
    }
  }
}`

then mimum_should_match is 0. I think more of a documentation problem this is a bug.

**Comment by nik9000** [comment]
> I think more of a documentation problem this is a bug.

It looks like this is intentional. Or, at least, [documented](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html):
![screen shot 2017-04-26 at 1 34 26 pm](https://cloud.githubusercontent.com/assets/215970/25447985/1cf942aa-2a85-11e7-950f-0b71162d6e47.png)

I agree this is weird though.
