### ISSUE TITLE
null_value is not supported for text fields

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#23839]
```
DELETE test
PUT test
{
  "mappings": {
    "my_type": {
      "properties": {
        "status_code": {
          "type":       "text",
          "null_value": "NULL" 
        }
      }
    }
  }
}
```

This is now failing in 5.x.

Either it's a bug and we should still support it or we should document it as a breaking change for people who are moving their `string` mapping to `text`.

Thoughts?

**Comment by jpountz** [comment]
I can think of use-cases for `null_value` on structured fields like numbers and keywords, but not for `text. It also introduces corner-cases, eg. should the `null_value` be analyzed or not? I'm leaning towards not supporting `null_value` on `text`.

**Comment by dadoonet** [comment]
I'm fine with that. I'm moving this issue from "bug" to "doc" as I think it should be clear in breaking changes.

**Comment by clintongormley** [comment]
it's not a breaking change - the `string` field has been removed and replaced with the `text`field, which doesn't support `null_value` (along with other things like `doc_values`)

**Comment by dadoonet** [comment]
I think it was not super clear to some users as reported in:

* https://discuss.elastic.co/t/equivalent-setting-for-following-mapping-in-elasticsearch-5-x/80104
* https://discuss.elastic.co/t/why-null-value-parameter-has-been-removed-for-text-field-type/79882

That's the reason I thought writing something about it in our doc because when I searched for `null_value` in our documentation, I went to this page: https://www.elastic.co/guide/en/elasticsearch/reference/5.3/null-value.html
Which lead me to thought that it is a common option supported for any type:

> The `null_value` parameter allows you to replace explicit `null` values with the specified value so that it can be indexed and searched.

**Comment by clintongormley** [comment]
OK - then we could add a list of fields which support `null_value` to that page

**Comment by glefloch** [comment]
Hi, I just pushed a PR to fix this issue. Can you tell me how I could test the documentation, and generate HTML? Do I need to clone the `docs` project? 
Also, are you ok with the list of field types? If there is any missing types or type that doesn't support `null_value` don't hesitate to tell me.

**Comment by clintongormley** [comment]
`null_value` is already listed under the fields that support it.  creating two way links will just lead to linkrot.  closing

**Comment by hajimurtaza** [comment]
So then how do I handle null or empty strings in text fields?

**Comment by everistusturing** [comment]
I really need to know how to handle null or empty strings
