### ISSUE TITLE
Install Elasticsearch Service in Windows

### ISSUE THREAD

**Issue by KiarashS** [elastic/elasticsearch#23849]
Elasticsearch service can not install in windows, When I run blow command:
`.\elasticsearch-service.bat install`
This output displayed in the command prompt:
```
C:\Users\Kiarash\Desktop\elasticsearch\bin>.\elasticsearch-service.bat install
Installing service      :  "elasticsearch-service-x64"
Using JAVA_HOME (64-bit):  "C:\Program Files\Java\jdk1.8.0_121"
'findstr /b \- "C:\Users\Kiarash\Desktop\elasticsearch\config\jvm.options" | findstr /b /v "\-server \-client"' is not recognized as an internal or external command,
operable program or batch file.
The syntax of the command is incorrect.
```

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. When you open a topic there, please provide the Windows version. As such, I hope you don't mind that I close this. We can reopen this if there is a verified bug here.
