### ISSUE TITLE
Remove support for custom user/groups in packaging

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#23848]
Our packaging tries to provide a way for users to customize the user/group for Elasticsearch.

It works okay for Sys V init (although installation does spew some errors that it turns out can be ignored).

It does not work at all for systemd, it requires some customization after installation.

We do not test either configuration.

I think permitting custom user/groups here is unnecessary complexity to our packaging, and we should remove this.

I think that for users that want custom user/groups, they should use an archive distribution, or use a configuration management solution like Ansible/Chef (e.g., our Ansible role permits customizing the user/group for both [Sys V init](https://github.com/elastic/ansible-elasticsearch/blob/771dac0829381033c7faaf4bf149c5bc1bc19891/templates/init/debian/elasticsearch.j2#L37-L39) and [systemd](https://github.com/elastic/ansible-elasticsearch/blob/771dac0829381033c7faaf4bf149c5bc1bc19891/templates/systemd/elasticsearch.j2#L17-L18)).

I note that Logstash does not provide the ability to customize the user/group through the packaging.

Relates #21231, relates #22044

**Comment by nik9000** [comment]
I didn't realize we had this ability. +1 to remove. I figure if you want
this you probably use the tar package already because you didn't know it
was possible with deb or rpm.

**Comment by jasontedor** [comment]
We discussed this in Fix-it-Friday and we are going to proceed with removing this functionality.

**Comment by martinb3** [comment]
> We are going to rely on the configuration management solutions

Hi @jasontedor -- as a maintainer of the Chef cookbook for elasticsearch, we generally look upstream for advice on how best to customize and deploy elasticsearch. In fact, maintaining forks of init scripts / unit files and merging in changes from upstream is something I'd really _love_ to avoid doing. It's been very prone to error in the past.

I urge you to reconsider pushing this responsibility down to the maintainers to manage separate scripts and merge in changes.

**Comment by jasontedor** [comment]
@martinb3 Thank you for your input here, I appreciate it. I share the same concern as you regarding forking scripts and configuration files, please see comments I left in elastic/ansible-elasticsearch#285.

> I urge you to reconsider pushing this responsibility down to the maintainers to manage separate init-system scripts and continuously merge in changes.

You do not have to take on this responsibility if you do not want to, and based on your comments in #21231 it seems that you're okay with removing support for customizing the user/group? The mention of configuration management solutions to address this problem was only a recommendation for what users that want to customize the user/group should could do, not a burden being pushed on to you and other maintainers, I'm sorry that you took it that way.

**Comment by martinb3** [comment]
Thank you for your response, @jasontedor -- I truly appreciate it!

Indeed, right now, we're simply not providing the functionality in systemd init scripts in the Chef cookbook. I'm okay with just leaving it as-is, but I was also thinking it would be a short term problem and eventually get resolved upstream.

We can always tell users to simply [provide their own unit file for systemd instead](https://github.com/elastic/cookbook-elasticsearch/blob/master/libraries/resource_service.rb#L26-L27). I imagine this will upset some folks enough to come read this issue and potentially open more issues here upstream, but I understand not wanting to maintain this stuff here either (after all, I'm basically in the same boat/saying the same thing 👍 ).

It might be useful to have a list of what Elasticsearch does and doesn't allow overrides for using the environment, so we can solve some of this through documentation, and then both projects (elasticsearch and the chef cookbook, and even the Ansible playbook too) can link to this as an authoritative design doc. Maybe this already exists?

As long as we allow/enable people to inject their own init scripts, I don't feel like we're locking anyone out from making changes. Thanks again!

**Comment by jasontedor** [comment]
> Maybe this already exists?

I agree, we should clearly document this change and at least provide some guidance on what users that want to customize the user/group can do to meet that need.

> As long as we allow/enable people to inject their own init scripts, I don't feel like we're locking anyone out from making changes.

I agree.

> Thanks again!

Thank *you*.

**Comment by jasontedor** [comment]
Thank you @dakrone!
