### ISSUE TITLE
BulkIndexByScrollResponse on Java API is not exposing total.

### ISSUE THREAD

**Issue by NicolasYDDER** [elastic/elasticsearch#23845]
**Elasticsearch version**: 5.2.2

**Plugins installed**: []

**JVM version**: openjdk version "1.8.0_66"

**OS version**: Windows 7

**Description of the problem including expected versus actual behavior**:
According the Java API documentation provided by the Elastic website https://www.elastic.co/guide/en/elasticsearch/client/java-api/5.2/java-docs-delete-by-query.html BulkIndexByScrollResponse is the new black to get the delete_by_query response.

If I check the delete_by_query doc the response return below:

```javascript
{
  "took" : 147,
  "timed_out": false,
  "deleted": 119,
  "batches": 1,
  "version_conflicts": 0,
  "noops": 0,
  "retries": {
    "bulk": 0,
    "search": 0
  },
  "throttled_millis": 0,
  "requests_per_second": -1.0,
  "throttled_until_millis": 0,
  "total": 119,
  "failures" : [ ]
}
```

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html

Problem :
BulkIndexByScrollResponse is not exposing all response field returned by the delete_by_query response. The getTotal() is missing.

https://github.com/elastic/elasticsearch/blob/5.2/modules/reindex/src/main/java/org/elasticsearch/index/reindex/BulkIndexByScrollResponse.java

**Comment by colings86** [comment]
@nik9000 Do you think this is something we should add?

**Comment by javanna** [comment]
Some of these fields are exposed through `response.getStatus()`, e.g. `response.getStatus().getTotal()`. As far as I can see all of the information printed out at REST is also available in the java api. Maybe this is just a matter of improving javadocs.

**Comment by NicolasYDDER** [comment]
`getStatus()`is a protected method in case of BulkIndexByScrollResponse, so `getStatus().getTotal()` is not accessible from application-side.

**Comment by javanna** [comment]
@NicolasYDDER do you mean `BulkByScrollResponse`? I can't quite find the class that you mentioned, can you clarify this please?

**Comment by jasontedor** [comment]
I tripped on the same thing as you @javanna, and @nik9000 helped me track it down.

The name of the class changed between 5.2 and 5.3 In 5.2, it's `BulkIndexByScollResponse` and `BulkIndexByScrollResponse#getStatus` is indeed protected there. However, in 5.3 the name of the class is `BulkByScrollResponse` and `BulkByScrollResponse#getStatus` is public. So, I think there's nothing to do here since upgrading should get the desired functionality.

**Comment by javanna** [comment]
thanks @jasontedor makes sense now!

**Comment by ESamir** [comment]
Our documentation is still using BulkIndexByScrollResponse  , we need to update it and use BulkByScrollResponse

**Comment by nik9000** [comment]
> Our documentation is still using BulkIndexByScrollResponse , we need to update it and use BulkByScrollResponse
> https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-docs-delete-by-query.html

I pushed 
https://github.com/elastic/elasticsearch/commit/c5910c0e352ebc6f89cb941268b9ab55cbef515a to fix it.
