### ISSUE TITLE
Add exclude_keys option to KV processor

### ISSUE THREAD

**Issue by andrewkroh** [elastic/elasticsearch#23856]
It would be nice to have an `exclude_keys` configuration option for the key-value processor in Ingest Node. `exclude_keys` would specify a list of keys that are not included in the final document even if they are present in the raw data parsed by the processor. There is already an [`include_keys`](https://github.com/elastic/elasticsearch/blob/v5.3.0/modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/KeyValueProcessor.java#L108) filter.

The [kv filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-kv.html#plugins-filters-kv-exclude_keys) in Logstash has this option.

I want to use this to prevent certain keys from being overwritten by dynamic data coming from the KV processor.

**Comment by javanna** [comment]
@talevy what do you think?

**Comment by talevy** [comment]
this makes sense, I'll get to it soon!
