### ISSUE TITLE
Elasticsearch persistent cluster settings not apply?

### ISSUE THREAD

**Issue by viewsite** [elastic/elasticsearch#23860]
Hi, i  have a question on  Cluster Update Settings

 i create a 2-node cluster and write some data to it.  The shards of index is distributed across two nodes.
then i put the setting below to the  cluster to exclude one node. 

    curl -XPUT http://1.1.1.1:18437/_cluster/settings?pretty -d '
    {
      "persistent" : {
        "cluster.routing.allocation.exclude._ip": "1.1.1.1"
      }
    }'

and i got acknowledge response. but  it doesn't takes effect. the shard of the node 1.1.1.1 is still working and not being  reallocated.

but it  works well  like settings below

    curl -XPUT http://1.1.1.1:18437/_cluster/settings?pretty -d '
    {
      "transient" : {
        "cluster.routing.allocation.exclude._ip": "1.1.1.1"
      }
    }'

i am afraid of losing my settings in case that the cluster restart so i want to put my settings in persistent module. why doesn't  persistent cluster setting working  like  transient settings?

my elasticsearch version is 5.0.0

and above is all my settings

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Let's keep the discussion on https://discuss.elastic.co/t/elasticsearch-persistent-cluster-settings-not-apply/80683

Thanks!

**Comment by jasontedor** [comment]
While this looks like a question, it appears to be a potential bug report. I think it's worth investigating whether or not this reproduces. If it does not reproduce then I agree that it should be closed and then we can direct to the forum.

**Comment by jasontedor** [comment]
This does not reproduce. I started two nodes, one on my laptop and one on my workstation. I created an index with two shards, no replicas. These shards allocated one on each node:

```
$ curl -XGET 192.168.1.232:9200/_cat/shards
i 1 p STARTED 0 130b 192.168.1.208 lAlVgsS
i 0 p STARTED 0 130b 192.168.1.232 Of7qASD
```

I put this setting:

```
$ curl -XPUT 192.168.1.232:9200/_cluster/settings?pretty=true -d '
{
  "persistent": {
    "cluster.routing.allocation.exclude._ip": "192.168.1.208"
  }
}'
{
  "acknowledged" : true,
  "persistent" : {
    "cluster" : {
      "routing" : {
        "allocation" : {
          "exclude" : {
            "_ip" : "192.168.1.208"
          }
        }
      }
    }
  },
  "transient" : { }
}
```

The shard relocated:

```
$ curl -XGET 192.168.1.232:9200/_cat/shards            
i 1 p STARTED 0 130b 192.168.1.232 Of7qASD
i 0 p STARTED 0 130b 192.168.1.232 Of7qASD
```
