### ISSUE TITLE
can't use elasticsearch with circleci because of bootstrap checks

### ISSUE THREAD

**Issue by alrooney** [elastic/elasticsearch#23866]
Currently you have a policy of enforcing bootstrap checks if not binding to localhost.  This prevents me from testing on circleci because the docker test setup there does not bind to localhost and starting the elasticsearch container fails due to 
```
[2017-04-02T03:30:05,591][INFO ][o.e.b.BootstrapChecks    ] [Vwkcgeo] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
ERROR: bootstrap checks failed
max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2017-04-02T03:30:05,597][INFO ][o.e.n.Node               ] [Vwkcgeo] stopping ...
[2017-04-02T03:30:05,659][INFO ][o.e.n.Node               ] [Vwkcgeo] stopped
[2017-04-02T03:30:05,660][INFO ][o.e.n.Node               ] [Vwkcgeo] closing ...
[2017-04-02T03:30:05,667][INFO ][o.e.n.Node               ] [Vwkcgeo] closed
Exited with code 78
```
It would be nice if we could explicitly disable bootstrap checks.

**Comment by jasontedor** [comment]
Relief is coming for the this scenario. See #23598.

**Comment by alrooney** [comment]
Great.  Thanks.  Also figured out the transport trick.  I was able to use circleci by setting the transport.host to localhost as follows in the circleci config.yml:

```
...
      - image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
        environment:
          xpack.security.enabled: false
          transport.host: localhost
```

**Comment by jasontedor** [comment]
That's right. If you do not need transport, that's the preferred and simplest option. :smile:

**Comment by jasontedor** [comment]
This is integrated now. We have added a new discovery type suitable for binding transport to an external interface for the purpose of testing the transport client against Elasticsearch in situations where might not have permissions to modify the configuration of the host to pass the bootstrap checks (for example, CI providers). To summarize the situation:
 - we have added a new discovery type called `single-node`
 - when a node uses the discovery type `single-node` it can not form a cluster with another node
 - when a node uses the discovery type `single-node` the bootstrap checks are disabled
 - for users that are running a node using discovery type `single-node` in production, they should enable the system property `es.enable.bootstrap.checks` to force the bootstrap checks to run; they are at their own risk if they do not do this

This is documented in the bootstrap checks docs.

**Comment by chrishough** [comment]
I have been trying your example with no luck, thoughts on https://stackoverflow.com/questions/46597848/circleci-2-ruby-rails-elastic-search

**Comment by tvernum** [comment]
> I have been trying your example with no luck

Please don't append new problems onto closed github issues - the difficulty you are facing has nothing to do with this particular issue. I realise that probably isn't clear to you - you're just facing an problem with circle-ci and this is a circle-ci ticket, but that's exactly why you shouldn't just add these comments onto someone else's issue until you actually know that it's the same problem.

In the future, please ask these sorts of questions on our [discussion forum](http://discuss.elastic.co) where someone can help diagnose it for you.
In this case, I will save you the trouble and answer on stackoverflow.

**Comment by chrishough** [comment]
Will do, I appreciate your guidance as I have been battling this for awhile now and figured that SO post would be great for the community.
