### ISSUE TITLE
CI: FilterAggregatorTests.testRandom fails reliably

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#23879]
This one fails reliably for me on osx

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu/784/consoleFull

```
gradle :core:test -Dtests.seed=3A3804F49E3CD039 -Dtests.class=org.elasticsearch.search.aggregations.bucket.FilterAggregatorTests -Dtests.method="testRandom" -Dtests.security.manager=true -Dtests.locale=ar-KW -Dtests.timezone=Europe/Rome
```

**Comment by jpountz** [comment]
@colings86 Can you take a look?

**Comment by jimczi** [comment]
Fixed by https://github.com/elastic/elasticsearch/commit/c14be2074472478c0abafca51631e22960281b44

**Comment by colings86** [comment]
@jimczi thanks :)
