### ISSUE TITLE
could not add subquery to bool must query

### ISSUE THREAD

**Issue by itrnka** [elastic/elasticsearch#23875]
**Elasticsearch version**: 5.1.1

**Plugins installed**: []

**JVM version**:

**OS version**: linux

**Description of the problem including expected versus actual behavior**:
in older version was supported query in query in unlimited tree level, eg.:

```
query: {
    bool: {
        'must' => [
             'query': {
                   'should': ...
             }
        ]
    }
}

```
it can not be simulated yet...

**Comment by ywelsch** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this. We can reopen this if there is a verified bug here.
