### ISSUE TITLE
feature request: add abort timeout for index operations

### ISSUE THREAD

**Issue by joelstewart** [elastic/elasticsearch#23876]
The API support for timeout only sets how long to wait for the primary shard to become available to begin an indexing operation:

https://www.elastic.co/guide/en/elasticsearch/reference/2.4/docs-index_.html#timeout

But it does not have any effect on indexing that once started may take a long time to complete.

Would like to be able to pass in an abort timeout value that aborts indexing of a document after indexing begins when it exceeds an amount of time.

**Comment by ywelsch** [comment]
Why does it take so long for indexing to complete? Indexing a document should usually be fast. Also, once a document has been indexed into the primary but not replicated yet to all replicas, we cannot just abort the request, as this will make the replicas go out of sync.

**Comment by joelstewart** [comment]
Our reason for the long index times is related to geo indexing.   https://github.com/elastic/elasticsearch/issues/22087  

Some geoshapes just lock it up into hours of a CPU trying to get that geo shape indexed.   This causes a lot of problems, such if a client calls refresh on that index, it fills the refresh queue up.

**Comment by joelstewart** [comment]
Remind me how replicas work?  

If I remember, the translog is what is copied, and then indexing takes place on the replica as well.  I do see how timeouts then introduce a problem of what to do if it timesout on the primary - there is no guarantee it would timeout on the replica(s) as well.   

I'll offer a couple ideas, recognizing each may have ramifications or difficulties: 

1) perhaps there can be a mode to enable aborts.  maybe timeouts in this case are set in elasticsearch,yml or in index settings.  If the mode is on, translog replication takes place after initial indexing?  

2) if indexing fails on primary, send interrupt to secondaries for that doc id.  On replicas, if the task has already completed, do a delete.

3) segment based replication mode:  https://writequit.org/org/es/design/shadow-replicas.html

**Comment by jasontedor** [comment]
I agree with @ywelsch.

Additionally, aborting a thread would require cooperation from the indexing thread all through the engine and inside Lucene, I do not think we want to add checks throughout as it will just increase the cost of indexing with a lot of added complexity.

**Comment by jasontedor** [comment]
> Some geoshapes just lock it up into hours of a CPU trying to get that geo shape indexed. This causes a lot of problems, such if a client calls refresh on that index, it fills the refresh queue up.

I think that instead of adding support for timeouts through Elasticsearch and Lucene, we should instead work on improving the performance here which is what #22087 can hopefully serve as a catalyst for.

**Comment by joelstewart** [comment]
@jasontedor  I understand there are complexities, which is why it would be a non-default operating mode that would enable it (and it could be experimental without guarantees / support).

My only option now is to implement logic that will reject documents with linestrings that have some characteristics.  Trouble is, we don't really know when something is good or bad without having a deeper understanding of the linestring indexing algorithm.

**Comment by jasontedor** [comment]
> understand there are complexities, which is why it would be a non-default operating mode that would enable it (and it could be experimental without guarantees / support).

No, complexity means on the implementation side to what is already very hairy code. Hiding it behind being off by default doesn't change the fact that I'm very cautious about making any of the code involved here even more complex. Adding it behind an experimental flag will not help, it's still code in the main path of execution that has to change.

**Comment by jasontedor** [comment]
> If the mode is on, translog replication takes place after initial indexing?

There is no translog replication, documents are added to the translog when indexing is completed whether it's on the primary, or on the replicas after the primary has completed and the replica has indexed the same document.

> if indexing fails on primary, send interrupt to secondaries for that doc id.

Indexing requests will never be sent to the replica is the primary fails to index the document. We will be replicating failures, but only for the purpose of ensuring that the replicas have an operation history that is identical to that of the primary.

> segment based replication mode:  https://writequit.org/org/es/design/shadow-replicas.html 

Segment-based replication and shadow replicas are slightly different things. Lucene has native segment-based replication. Elasticsearch does not expose it, and exposing it is a massive effort that I personally think is unlikely to be undertaken. Shadow replicas are deprecated and are going to be removed.

**Comment by jasontedor** [comment]
I'm going to close this issue, I will reopen if it if there's a convincing argument presented that we should add timeouts here. Instead, I think we should figure out how to make indexing as fast as possible, including the case of geo points.

**Comment by clintongormley** [comment]
@joelstewart @nknize is working on BKD based geoshapes in Lucene, which will be much more efficient than the current implementation.  This tackles the problem at its root rather than papering over it with a timeout.  Yes, it's not immediate, but it will be worth the wait.
