### ISSUE TITLE
Streaming aggregation results on a per shard or segment basis

### ISSUE THREAD

**Issue by hijakk** [elastic/elasticsearch#23890]
I am a data scientist working with relatively large volumes of data. One of the consistent complaints I've heard from my colleagues about Elasticsearch is the aggregations interface and the inability to scan/scroll for large volumes of results from, say, a terms aggregation.

If it's possible, I think a low level interface that would allow users to get complete results back from individual shards or segments, providing the users the ability to script their own offline "reduce" function would be extremely valuable. 

The primary issue I've seen is, say I've got a year's worth of the twitter 1% stream - maybe a billion tweets. I want to get a list of everybody that's spoken more than one language where one of the languages is English. 

As it is, this aggregation is too large to run in an exhaustive fashion. If I was able to get back that for segment XYZ, users Bob, Fred and Jerry spoke languages English, French and Tamil at rates A, B and C, I can write that to disk for later analysis offline - I don't truly need ES to crunch all the results down for me, but it can get me summaries of chunks of information much more quickly than moving through the data one record at a time.

Currently, when we have a question like this and the data is in Elasticsearch, we have to set up a scan/scroll and manually aggregate in Python or similar. This takes a long time. Is access to the component results of an aggregation, on a very low level before the final "reduce" operation something that would be possible?

**Comment by cbuescher** [comment]
@hijakk you can already restrict the search operation (and thereby also aggregations) to run only on selected shards using the `preference` [url parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-preference.html), e.g by setting `?preference=_shards:1`. I doubt that ES is likely to expose access to any low-level operation on a segment basis though.

**Comment by jpountz** [comment]
Hey @hijakk, the way that our current aggregation framework is designed makes it basically impossible to return results in a streaming fashion. That said, we are exploring alternative ways to compute aggregations which might allow to return results in a streaming fashion. However, this is something that we are only starting exploring now, no single line of code has been written and it's not even clear what the API should look like so it is going to take time before we expose something like this.

**Comment by jpountz** [comment]
Closing for now, we'll open a new issue if/when we have something along the lines of what I described in my previous message.
