### ISSUE TITLE
Provide a re-locatable rpm distribution

### ISSUE THREAD

**Issue by mkelkarbv** [elastic/elasticsearch#23908]
**Elasticsearch version**: 5.2.2

**Plugins installed**: []

**JVM version**: 1.8.0-65

**OS version**: amazon linux

**Description of the problem including expected versus actual behavior**:

elasticsearch 5.2 ( or even 5.3) rpms are not relocatable. I think they should be re-locatable.

**Steps to reproduce**:
 1. download elasticsearch 5.2.2 rpm
 2. install via rpm --relocate
 
`rpm --relocate /usr/share=/mnt/data --install elasticsearch-5.2.2.rpm`

which gives 
`warning: elasticsearch-5.2.2.rpm: Header V4 RSA/SHA512 Signature, key ID d88e42b4: NOKEY
	path /usr/share in package elasticsearch-0:5.2.2-1.noarch is not relocatable`

**Provide logs (if relevant)**:

**Describe the feature**: 

I would like to see re-locatable rpm distributions which can work out of the box. The rpm --prefix sort of works, but then elasticsearch doesn't start because the init.d script has a hardcoded path for ES_HOME (/usr/share/elasticsearch). I can install via zip file, but then I loose all the init.d script niceties...

**Comment by jasontedor** [comment]
Sorry, I think we are very unlikely to provide this functionality, we are trying to keep the packaging simple and I do not see the need to add support for what is already a very rarely used feature with little benefit to doing so.

In fact, the [Fedora packaging guidelines](https://fedoraproject.org/wiki/Packaging:Guidelines#Relocatable_packages) say this:

>The use of RPM's facility for generating relocatable packages is strongly discouraged.

**Comment by jasontedor** [comment]
Oops, closed by hitting the wrong button; leaving this open for discussion.

**Comment by tvernum** [comment]
> I can install via zip file, but then I loose all the init.d script niceties...

@mkelkarbv, Is it just the init.d niceties that are steering away from the zip file?  
Because that's a problem that we can look at solving in other ways.

**Comment by mkelkarbv** [comment]
@jasontedor @tvernum  thank you for your responses!

@jasontedor  good to know! I think there is room for providing some functionality that rpms provide to other distros like zip file/yum.

@tvernum  Here is what I thought was nice about rpm distribution
1. necessary system settings ( max open files, vm.max_map_count ) are taken care of
2. init.d script for service management

In fact, if these things can be made available in a zip distribution, I would love to have that. I hate rpms, but I would like to avoid writing hard to maintain ops code (especially if its already available in distribution X and not in distribution Y).

**Comment by mkelkarbv** [comment]
@jasontedor @tvernum  what do you guys think about adding stuff I mentioned in zip distribution? For now, I have created my own init.d script and code around managing system/environment settings, but I think that could be supplied OOTB with a small setup script..

**Comment by jasontedor** [comment]
I think that we are unlikely to do that for the archive distributions. I think the need for scripts to set up the system, environment, and service scripts is served well by the packaging distributions and the use of these in the archive distributions would be minimal. Doing this would be adding a lot of maintenance overhead for a need that I think is already met.

**Comment by mkelkarbv** [comment]
@jasontedor by "packaging distributions", which specific ones you are referring to? I can't use rpm as is, so my only option is to use ZIP which lacks stuff that I mentioned earlier...

**Comment by jasontedor** [comment]
> by "packaging distributions", which specific ones you are referring to?

By the packaging distributions I mean the RPM and the deb distributions.

> I can't use rpm as is

Because it's not relocatable?

> so my only option is to use ZIP which lacks stuff that I mentioned earlier

Which we are unlikely to add because I think that most people that want these things just use the RPM or the deb.

**Comment by jasontedor** [comment]
We discussed in Fix-it-Friday and have decided that we are not going to do this for reasons provided previously.
