### ISSUE TITLE
Incorrect documentation ES 5.3.3 - Indexing Performance Tuning

### ISSUE THREAD

**Issue by ajaybhatnagar** [elastic/elasticsearch#23927]
Parameters index.refresh_interval, indices.memory.index_buffer_size are mentioned in the document for indexing performance tuning but they are not allowed in the configuration.
Ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/indexing-buffer.html

**Comment by jimczi** [comment]
I don't get what's wrong here. These settings are configurable per node for the index_buffer_size and per index for the refresh interval.
