### ISSUE TITLE
Add `search.remote.{name}.http_addresses` setting

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#23924]
Users should be able to specify a preferred list of `http_addresses` when configuring a remote cluster for cross-cluster search.

Question: should this be `_addresses` or `_urls`?  The nodes may be behind HTTPS instead of HTTP, so should they be specifying `https://10.0.0.1:9200`?  or should we add `search.remote.{name}.https: true|false`?

**Comment by clintongormley** [comment]
@s1monw what do you think?

**Comment by s1monw** [comment]
why would we need this if we can get this through the API added in #23925

**Comment by s1monw** [comment]
I think we should keep it simple for now and just use what the node info gives us. @clintongormley can you close this if you are ok with it.
