### ISSUE TITLE
Elasticsearch giving failed to connect to discovered node

### ISSUE THREAD

**Issue by chaitu0292** [elastic/elasticsearch#23932]
**My java application log was filled up with below error.Any idea why this exception.ES version:2.4.2**

DEBUG transport:319 - [Rl'nnd] failed to connect to discovered node [{node-bla.bla.bla}{AjQO6FQ8S_u5F43exnmZPA}{bla.bla.bla:9300}{data=false, master=false}] ConnectTransportException[[node-bla.bla.bla][bla.bla.bla:9300] connect_timeout[30s]]; nested: ConnectTimeoutException[connection timed out: /bla.bla.bla:9300]; at org.elasticsearch.transport.netty.NettyTransport.connectToChannels(NettyTransport.java:987) at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:920) at org.elasticsearch.transport.netty.NettyTransport.connectToNode(NettyTransport.java:893) at org.elasticsearch.transport.TransportService.connectToNode(TransportService.java:260) at org.elasticsearch.client.transport.TransportClientNodesService$NodeSampler.validateNewNodes(TransportClientNodesService.java:316) at org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler.doSample(TransportClientNodesService.java:388) at org.elasticsearch.client.transport.TransportClientNodesService$NodeSampler.sample(TransportClientNodesService.java:300) at org.elasticsearch.client.transport.TransportClientNodesService$ScheduledNodeSampler.run(TransportClientNodesService.java:333) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745)

**After 45 minutes the above exception stopped and than the below exception started coming.Is there any connection retry time out in ES?**

netty:1095 - [Plug] disconnecting from [{node-bla.bla.bla}{68xnC79rTDKlc55G-bMcfQ}{10.0.2.77}{bla.bla.bla:9300}{data=false, master=false}], channel closed event

**Comment by javanna** [comment]
hi @chaitu0292 

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
