### ISSUE TITLE
The createClone task fails on Windows

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#23938]
```
:distribution:bwc-zip:createClone (Thread[main,5,main]) started.
:distribution:bwc-zip:createClone
Putting task artifact state for task ':distribution:bwc-zip:createClone' into context took 0.0 secs.
Executing task ':distribution:bwc-zip:createClone' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Starting process 'command 'git''. Working directory: C:\jenkins\workspace\es_core_master_windows-2012-r2\distribution\bwc-zip Command: git clone C:\jenkins\workspace\es_core_master_windows-2012-r2 C:\jenkins\workspace\es_core_master_windows-2012-r2\distribution\bwc-zip\build\bwc\checkout-5.x
:distribution:bwc-zip:createClone FAILED
:distribution:bwc-zip:createClone (Thread[main,5,main]) completed. Took 0.004 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':distribution:bwc-zip:createClone'.
> A problem occurred starting process 'command 'git''

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED
```

I'm unsure what the cause of the problem is as it isn't printed in the console.

I was thinking that it perhaps can't find the `git` command, but that doesn't make sense otherwise the jenkins slave was unable to check out the repository in the first place.

Build urls:
* http://build-us-00.elastic.co/job/es_core_master_windows-2012-r2/5217/
* http://build-us-00.elastic.co/job/es_core_master_windows-2012-r2/5218/
* http://build-us-00.elastic.co/job/es_core_master_windows-2012-r2/5219/

**Comment by jasontedor** [comment]
I logged into the slave, and the offending command runs fine from the command prompt. I pushed 2620200ff7d945c5bc17d2b854b4a6a92fd2120e to see if we can get some additional debug output here.

**Comment by jasontedor** [comment]
Okay, there was no extra logging. I logged into the slave again, and instead of running the offending git command, I instead went with running `gradle :distribution:bwc-zip:createClone`. This gave the incredibly helpful output:

```
fatal: cannot create directory at 'plugins/discovery-gce/src/test/resources/org/
elasticsearch/discovery/gce/compute/v1/projects/multiplezonesandtwonodesindiffer
entzones/zones/europe-west1-b': Filename too long
warning: Clone succeeded, but checkout failed.
```

I fixed this by issuing:

```
git config --system core.longpaths true
```

I'll get this updated on all of the slaves.

**Comment by jasontedor** [comment]
We ultimately tracked this one down. It was a combination of a two things; the long paths issue, and a bad PATH variable.
