### ISSUE TITLE
GlobalIT#testWithStatsSubAggregator build failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#23935]
```
1> [2017-04-05T18:15:31,905][INFO ][o.e.s.a.b.GlobalIT       ] [testWithStatsSubAggregator]: before test
ERROR   10.1s J0 | GlobalIT.testWithStatsSubAggregator <<< FAILURES!
   > Throwable #1: java.lang.RuntimeException: 1 arrays have not been released
   > 	at __randomizedtesting.SeedInfo.seed([2BCD6888C069F459:768606DEFD6D5EBC]:0)
   > 	at org.elasticsearch.common.util.MockBigArrays.ensureAllArraysAreReleased(MockBigArrays.java:65)
   > 	at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:389)
   > 	at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:282)
   > 	at java.lang.Thread.run(Thread.java:745)
```

```
REPRODUCE WITH: gradle :core:integTest -Dtests.seed=2BCD6888C069F459 -Dtests.class=org.elasticsearch.search.aggregations.bucket.GlobalIT -Dtests.method="testWithStatsSubAggregator" -Dtests.security.manager=true -Dtests.locale=de-DE -Dtests.timezone=America/Bahia_Banderas
```

Build failure does not reproduce.

Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=fedora/797

**Comment by colings86** [comment]
I have tried reproducing this without success with the above reproduce command (no failure in 604 runs) and also just running the `gradle :core:integTest` repeatedly (no failure in 76 runs). 

What is weird here is that usually on these failures there is a stack trace that shows where the unreleased resource has been referenced but this doesn't seem to be here for this failure.

I'm not really sure what we can do right now for this other than wait for it to reproduce and see if there is a pattern. @jpountz can you think of any extra logging we could add that might help here?

**Comment by colings86** [comment]
@martijnvg this doesn't seem to have failed again from what I can see and was not reproducible, should we close this for now?

**Comment by colings86** [comment]
Closing this for now. Please reopen if the issue reproduces
