### ISSUE TITLE
InternalEngineTests is inconsistent with SeqNoFieldMapper

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#23937]
InternalEngineTests does `final NumericDocValues values = leaf.getNumericDocValues(SeqNoFieldMapper.NAME);` while `SeqNoFieldMapper` creates this field using a `SortedNumericDocValuesField`. We should either change `SeqNoFieldMapper` to create `NumericDocValuesField` instances or `InternalEngine` to call `leaf.getSortedNumericDocValues`.

**Comment by bleskes** [comment]
@jpountz Indeed an issue. I think this is addressed in https://github.com/elastic/elasticsearch/pull/23543/files#diff-2688948cc880616bb08050ed25eec96dR266 .

**Comment by jpountz** [comment]
Awesome, indeed!

**Comment by bleskes** [comment]
cool. Closing then. Thanks for signaling it.
