### ISSUE TITLE
Filter in bool-query unexpectedly sets the minimum_should_match to 0

### ISSUE THREAD

**Issue by roelandvanbatenburg** [elastic/elasticsearch#23940]
**Elasticsearch version**: 5.2.2

**JVM version**: Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b13

**OS version**: Linux/4.9.13-moby/amd64

**Description of the problem including expected versus actual behavior**:
There is unexpected behaviour when combining should clauses with filter clauses in a bool query.
The following queries return different results as the second case is entirely in filter mode and thus defaults minimum_should_match to 1 and the first case is in query mode and uses minimum_should_match=0. This is partially documented in https://www.elastic.co/guide/en/elasticsearch/guide/current/bool-query.html#_controlling_precision
"By default, none of the should clauses are required to match, with one exception: if there are no must clauses, then at least one should clause must match.". However, this does not mention the filter clause and this seems to behave the same as the must-clause, which is quite unexpected.
I would expect that filter clause does not set the minimum_should_match to 0, similar to must_not clause.

**Steps to reproduce**:
 1. insert the brown fox data from https://www.elastic.co/guide/en/elasticsearch/guide/current/match-query.html
 2.
GET /my_index/my_type/_search
```
{
  "query": {
    "bool": {
      "must": {
        "bool": {
          "filter": {
            "match": {
              "title": "brown"
            }
          },
          "should": [{
            "match": {
              "title": "jumps"
            }
          }]
        }
      }
    }
  }
}



-> hits.total: 4 (also matches results without jumps in the title)
```
 3.
GET /my_index/my_type/_search
```
{
  "query": {
    "bool": {
      "filter": {
        "bool": {
          "filter": {
            "match": {
              "title": "brown"
            }
          },
          "should": [{
            "match": {
              "title": "jumps"
            }
          }]
        }
      }
    }
  }
}

-> hits.total: 2
```

**Comment by javanna** [comment]
This works as expected, `filter` clauses are exactly like `must` clauses, except that they don't affect scoring (and they may be more performant thanks to caching). If you want to make your should clause mandatory, it should become a must clause (in case you want it to affect scoring).

Would you like to open a PR to improve our definitive guide and clarify what you found? The page you mentioned is this one: https://github.com/elastic/elasticsearch-definitive-guide/blob/28f3b93ed394b77a5ca9f8d4dc75441d9eb85ff2/100_Full_Text_Search/15_Combining_queries.asciidoc#controlling-precision .
