### ISSUE TITLE
Cannot implement org.elasticsearch.client.HttpAsyncResponseConsumerFactory interface

### ISSUE THREAD

**Issue by mkhan24** [elastic/elasticsearch#23958]
The HttpAsyncReponseConsumerFactory 's access modifier as it sits in version 5.3.0 of Java REST Client libraries is package protected, i.e, no access modifier has been specified therefore users will not be able to implement it outside the org.elasticsearch.client package.

However, the javadoc for the org.elasticsearch.client.HttpAsyncResponseConsumerFactory says :

/**
* Factory used to create instances of {@link HttpAsyncResponseConsumer}. Each request retry needs its own instance of the
* consumer object. Users can implement this interface and pass their own instance to the specialized
* performRequest methods that accept an {@link HttpAsyncResponseConsumerFactory} instance as argument.
*/

I believe implementing the aforementioned interface is the only way to specify a buffer limit of higher than 100 MB?

**Elasticsearch version**: 5.3.0

**JVM version**: 1.8

**Comment by javanna** [comment]
hi @mkhan24 you are right, the buffer limit was supposed to be configurable but it is configurable only from within the `org.elasticsearch.client` package at the moment. I will fix that. In the meantime, the workaround is to implement the `HttpAsyncResponseConsumerFactory` interface and borrow the few lines of code needed from `HeapBufferedResponseConsumerFactory`.

**Comment by mkhan24** [comment]
Hi @javanna , thanks for the changes. Is there a tentative timeline on the official release of 5.3.1 (I presume it's going to be part of that?)

**Comment by javanna** [comment]
hi @mkhan24 I am in the process of backporting the change to 5.x and 5.3. 5.3.1 should be out soon, but I cannot guarantee yet that this change will make it in. Stay tuned.
