### ISSUE TITLE
Path hierarchy aggregation

### ISSUE THREAD

**Issue by vbura** [elastic/elasticsearch#23951]
@clintongormley As i saw in his example https://github.com/elastic/elasticsearch/issues/8896, but running on elasticsearch 5.3 i get this error

i saw that @alexshadow007 has the same issue
_Hello, any solutions to get this functionality in 5.x?_

{
   "error": {
      "root_cause": [
         {
            "type": "unknown_named_object_exception",
            "reason": "Unknown BaseAggregationBuilder [path_hierarchy]",
            "line": 4,
            "col": 25
         }
      ],
      "type": "unknown_named_object_exception",
      "reason": "Unknown BaseAggregationBuilder [path_hierarchy]",
      "line": 4,
      "col": 25
   },
   "status": 400

Do i need to make smthg?  
How i can do this in es 5.3 ?
Thx in advanced 

**Elasticsearch version**: 5.3

**Plugins installed**: [-]

**JVM version**: 1.8

**OS version**: ubuntu 16.4

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
Same as: https://github.com/elastic/elasticsearch/issues/8896

**Comment by javanna** [comment]
Hi @vbura  

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

Thanks


As far as I can see from the linked issue, that aggregation was never implemented, hence it does not work.
