### ISSUE TITLE
Set INDEX_MAPPING_TOTAL_FIELDS_LIMIT_SETTING of 0 as unlimited

### ISSUE THREAD

**Issue by billnbell** [elastic/elasticsearch#23956]
Can we set 0 as unlimited? It does not appear that this is the case?

> private void checkTotalFieldsLimit(long totalMappers) {
>         long allowedTotalFields = indexSettings.getValue(INDEX_MAPPING_TOTAL_FIELDS_LIMIT_SETTING);
>         if (allowedTotalFields < totalMappers) {
>             throw new IllegalArgumentException("Limit of total fields [" + allowedTotalFields + "] in index [" + index().getName() + "] has been exceeded");
>         }
>     }
>

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
