### ISSUE TITLE
Wrong behaviour deleting alias.

### ISSUE THREAD

**Issue by myrfy001** [elastic/elasticsearch#23960]
**Elasticsearch version**:
5.2.2
**Plugins installed**: []
head
**JVM version**:
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
**OS version**:
Linux 3.10.0-229.el7.x86_64
**Description of the problem including expected versus actual behavior**:

With two index named `foo_foo` and `bar_bar` with the same alias `foo` like below:

|  index  | alias |
| ------- | -------|
| foo_foo  |  foo |
| bar_bar | foo |
 
If use the following to remove the alias, only the alias of 'foo_foo' is removed, that's fine.
```
POST /_aliases 
{
  "actions": [
    {
      "remove": {
        "index": "foo_*",
        "alias": "foo"
      }
    }
  ]
}
```
BUT, if use the following to remove, both the alias of `foo_foo` and `bar_bar` will be removed, while I think only the `foo_foo` 's alias should be removed

```
POST /_aliases 
{
  "actions": [
    {
      "remove": {
        "index": "foo*",
        "alias": "foo"
      }
    }
  ]
}
```

**Steps to reproduce**:
 1. Create Two Index using the following:
```
PUT /foo_foo
PUT /bar_bar
```
 2. Add Alias for them using:
```
POST /_aliases
{
    "actions" : [
        { "add" : { "index" : "foo_foo", "alias" : "foo" } },
        { "add" : { "index" : "bar_bar", "alias" : "foo" } }
    ]
}
```
 3. delete alias using:
```
POST /_aliases 
{
  "actions": [
    {
      "remove": {
        "index": "foo_*",
        "alias": "foo"
      }
    }
  ]
}
```

**Comment by olcbean** [comment]
This looks like  a low hanging fruit. If so, I would like to have a look at it.

**Comment by jimczi** [comment]
@olcbean I just marked the issue as adopt me ;)

**Comment by hanumanthan** [comment]
@jimczi I am a first timer and would like to work on this issue. Could you please share the file where I can start to look at ?

**Comment by kunal642** [comment]
@myrfy001 i cannot replicate the issue. I have followed the step and i am able to query bar_bar with the alias foo.

**Comment by jimczi** [comment]
@kunal642 the last step of the reproduction has a typo. I can reproduce the problem with the following request:

`````
POST /_aliases 
{
  "actions": [
    {
      "remove": {
        "index": "foo*",
        "alias": "foo"
      }
    }
  ]
}
`````
