### ISSUE TITLE
query_string and simple_query_string cannot apply minimum should match consistently

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#23966]
We apply the requested `minimum_should_match` on parsed queries produced by `query_string` and `simple_query_string`. Since these queries can target multiple fields we used to rely on the `disableCoord` property of the `Boolean` query. Now that coords are gone in Lucene 7 we are not able to distinguish queries with multiple positions like:

`````
"query": {
	"simple_query_string": {
		"fields": ["field1", "field2"],
		"query": "foo bar",
		"minimum_should_match": 1
	}
}
`````

.... with single position queries on multiple fields:
`````
"query": {
	"simple_query_string": {
		"fields": ["field1", "field2", "field3],
		"query": "foo",
		"minimum_should_match": 2
	}
}
`````
In 5.x we were able to detect that the later query produces a single position and that `minimum_should_match`should not be applied.

In 6.0 this query would be rewritten in:
`foo must appear in 2 out of the 3 provided fields`

This is problematic but I can't think of a good fix for this. 
Furthermore applying `minimum_should_match` on `query_string` and `simple_query_string` is difficult to understand for users (it depends on settings like `split_on_whitespace`, tokenization, ...) so I wonder if we should just remove the support for this option in these query parsers.
The `match` and `multi_match_query` are not impacted since we apply `minimum_should_match` per `analyzer` group.

**Comment by s1monw** [comment]
do we have access to the place where we create the boolean queries so we can maybe wrap them or somehow mark them as eligible for minimum must match? Anyhow I removed the discuss label since we need to fix it either way ....

**Comment by jimczi** [comment]
I think we can just replace the boolean queries with DisjunctionMaxQuery. We already have an option for that in `query_string` called `use_dis_max`. When set to false (the default) we create boolean queries to merge queries targeting different fields and that makes `minimum_should_match` harder to apply. Instead we could still use a DisjunctionMaxQuery but with the tiebreaker set to 1.
The scoring should be equivalent to the boolean query and this would differentiate cross field queries from position queries and solve this particular problem. 
We could also consider adding `use_dismax` in `simple_query_string` but this is not related to this issue.
