### ISSUE TITLE
ZenDiscoveryIT.testNodeFailuresAreProcessedOnce failure

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#23964]
It does not reproduce for me and the test is a bit complex so I'm not sure which stack traces from the log are relevant. I did not disable the test as it looks like a rare failure.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/803/consoleFull

```
REPRODUCE WITH: gradle :core:integTest -Dtests.seed=88FAC903D8799C71 -Dtests.class=org.elasticsearch.discovery.zen.ZenDiscoveryIT -Dtests.method="testNodeFailuresAreProcessedOnce" -Dtests.security.manager=true -Dtests.locale=nl-BE -Dtests.timezone=Chile/Continental
```

**Comment by jpountz** [comment]
@bleskes I assigned it to you thinking you would know who the right person is.

**Comment by ywelsch** [comment]
I pushed 8522b43ce7

**Comment by jpountz** [comment]
Thanks @ywelsch !

**Comment by bleskes** [comment]
thanks*2 @ywelsch
