### ISSUE TITLE
termvector endpoint does not require id

### ISSUE THREAD

**Issue by PortaltechGithub** [elastic/elasticsearch#23978]
As you can read in the ES docs, it's also possible to use artificial documents to look up term stats. In my case i want to determine the "quality" of a word a user searched for. If i search for 
**Example:**
I searched for: `Produktivitätsmanagement` decompounds in `produktivität` and `management` and `produkt`. From the termvectors component i got `doc_freq` and so on. The doc_freq for `produkt` is very high, so i can skip this term in my query.

**ES Docs:**
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-termvectors.html#docs-termvectors-artificial-doc

I'am using this method: `\Elasticsearch\Client::termvectors()` 

```
$parameter = [
    'index' => $index,
    'type' => ['document'],
    'body' => [
        'doc' => [
            'title_stemmed' => $term,
            'text_stemmed' => $term,
            'title_decompounded' => $term,
            'text_decompounded' => $term,        
        ],
        'term_statistics' => true,
        'field_statistics' => false,
        'filter' => [
            'min_doc_freq' => 1,
            'min_word_length' => 4,
        ],
        'per_field_analyzer' => [
            'title_stemmed' => 'default_analyzer',
            'text_stemmed' => 'default_analyzer',
            'title_decompounded' => 'default_analyzer',
            'text_decompounded' => 'default_analyzer',
        ]
    ]
];

$response = $client->termvectors($parameter);
```
I think the code must be changed to require only type and index parameter, but not the ID parameter, in `\Elasticsearch\Endpoints\TermVectors` i changed the `getUri()` method:

```
/**
 * @throws \Elasticsearch\Common\Exceptions\RuntimeException
 * @return string
 */
public function getURI()
{
    $id = '';
    if (isset($this->index) !== true) {
        throw new Exceptions\RuntimeException(
            'index is required for TermVectors'
        );
    }
    if (isset($this->type) !== true) {
        throw new Exceptions\RuntimeException(
            'type is required for TermVectors'
        );
    }
    if (isset($this->id) && strlen($this->id) > 0) {
        $id    = '/' . $this->id;
    }

    $index = '/' . $this->index;
    $type  = '/' . $this->type;
    $uri   = $index . $type . $id . '/_termvectors';

    return $uri;
}
```

**Comment by spinscale** [comment]
this looks like a [elasticsearch-php client](https://github.com/elastic/elasticsearch-php) issue. This repository is only for Elasticsearch Core issues. Can you open it there? I am sure that @polyfractal will take a look then.

Thanks so much!

**Comment by PortaltechGithub** [comment]
Sry, next time i double check the repo!!!
