### ISSUE TITLE
Explicitly disallow default credential file loading in repository-gcs

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#23992]
Google cloud storage has 2 ways to authenticate: by detection of the cloud environment, or by a plaintext file containing credential information.  Support for credential file is being added to the elasticsearch keystore, but the way in which the cloud environment is loaded is problematic for completely disallowing the plaintext credential file.  The google code to load the default credentials first looks for an environment variable which points to the file, and then looks in "known locations", before trying to do detection of the cloud environment.

We should do just as we did with s3 and not allow using a plaintext file. One idea is to look for the environment variable and known locations, and error up front. The tricky part about this is it would require adding security permissions just to check if the env var or files exist. Another idea is to leave it as it is currently, which would both fail, due to lack of security permissions to read the env var or the file locations (in the user home directory).  At minimum, we should document that this is not supported.

**Comment by dadoonet** [comment]
> One idea is to look for the environment variable and known locations, and error up front. 

Is it possible to catch the SMException and throw in that case a better exception?

**Comment by rjernst** [comment]
That may be possible. I will experiment.

**Comment by albertzaharovits** [comment]
Would granting `permission java.io.FilePermission "<<ALL FILES>>", "read"` inside the security policy file but then scoping/limiting **each** `doPrivileged` invocation inside the plugin with the appropriate [least permissions](https://docs.oracle.com/javase/8/docs/api/java/security/AccessController.html#doPrivileged-java.security.PrivilegedAction-java.security.AccessControlContext-java.security.Permission...-) be a reasonable solution? In this case, the file system permissions would be effectively granted only to the code groping for the credentials file.

In general, what do you think about forbidding (un-scopped `doPriviledged`) and having a least privilege method for each call site?

cc @tlrx

**Comment by rjernst** [comment]
@albertzaharovits I don't think we should add any permissions for this. Catching the security exception and "peeking" at it is one solution we might be able to use in order to give a better error message here, as suggested by @dadoonet. We should at minimum document the limitation (my last solution in the original description).

**Comment by albertzaharovits** [comment]
@rjernst understood, thanks for rephrasing it, looks more actionable now!
I was trying to provide a hussle free alternative for the folks running ES on google compute by leveraging the `doPrivileged` in Java 8.

**Comment by albertzaharovits** [comment]
This has been resurrected in today's FixItFriday. Indeed, documenting the limitation, as proposed by @rjernst is the way forward. Adding security privileges only for the sake of a friendlier run time error is not convincing anyone.

I will follow-up with the docs PR.
