### ISSUE TITLE
Transport response handler not found of id

### ISSUE THREAD

**Issue by owenludong** [elastic/elasticsearch#23996]
**Elasticsearch version**: 2.4.0

**Plugins installed**: [head  hq elasticfence]

**JVM version**: 1.7.0_79

**OS version**: centos 7

use elasticsearch 2.4.0 java sdk to put data, but some warn loggers in client and server, what happend?

log:

client: 2017-04-09 10:37:16,476 [elasticsearch[Butterball][transport_client_worker][T#4]{New I/O worker #13}] WARN  [org.elasticsearch.transport] - [Butterball] Transport response handler not found of id [21535]

server: [2017-04-09 10:45:35,838][WARN ][transport                ] [es-order-3] Transport response handler not found of id [856999]

**Comment by bleskes** [comment]
This typically happens when a response times out after a request time. If you have any more question, please use our forums on discuss.elastic.co as we keep github for feature requests and issues. If this turns out to be a problem, please feel free to reopen the issue.
