### ISSUE TITLE
NestedChildrenQuery references an IndexReader

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#24009]
This can cause memory leaks if that query gets cached. Unfortunately we only have access to the right APIs to fix it once we upgrade to Lucene 6.5.1.

**Comment by martijnvg** [comment]
Maybe we should use `ParentChildrenBlockJoinQuery` (was added in lucene 6.5) and remove `NestedChildrenQuery`?

**Comment by jpountz** [comment]
+1!
