### ISSUE TITLE
AsyncBulkByScrollActionTests. testScrollDelay sporadically fails

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#24005]
This test failed a couple of times in the last few weeks in our CI.

From https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+nfs/161/ :

```
> Expected: (<10L> or <9L>)
   >      but: was <8L>
   > 	at __randomizedtesting.SeedInfo.seed([7F0426D0E5786EF3:620E78685D1BC832]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.action.bulk.byscroll.AsyncBulkByScrollActionTests.testScrollDelay(AsyncBulkByScrollActionTests.java:461)
   > 	at java.lang.Thread.run(Thread.java:745)
```

I haven't been able to reproduce this.

**Comment by javanna** [comment]
One more recent failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+nfs/160 . 

```
FAILURE 3.54s J0 | AsyncBulkByScrollActionTests.testScrollDelay <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: (<100L> or <99L>)
   >      but: was <98L>
   > 	at __randomizedtesting.SeedInfo.seed([6458D45590BD85E0:79528AED28DE2321]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.action.bulk.byscroll.AsyncBulkByScrollActionTests.testScrollDelay(AsyncBulkByScrollActionTests.java:455)
   > 	at java.lang.Thread.run(Thread.java:745)
```

Both failures come from the same `elastic+elasticsearch+master+nfs` job, which seems suspicious.

**Comment by nik9000** [comment]
These are caused by using the system time in the test. There was a burble around the time of these test failures. @dakrone warned me against using it when I wrote the test but I didn't listen. I was wrong.

I'll open a PR that removes the system time.
