### ISSUE TITLE
Dynamic template with match_mapping_type ignored when there's a match "*" after it

### ISSUE THREAD

**Issue by andrewclegg** [elastic/elasticsearch#2401]
I have the following dynamic mappings set up in default-mapping.json:

```javascript
{
    "_default_": {
        "_source": {
            "enabled": false
        },
        "_all": {
            "enabled": false
        },
        "dynamic_templates": [
            {
                "strings": {
                    "match": "*",
                    "match_mapping_type": "string",
                    "mapping": {
                        "type": "multi_field",
                        "fields": {
                            "{name}": {
                                "type": "string",
                                "index": "not_analyzed",
                                "omit_norms": true,
                                "omit_term_freq_and_positions": true
                            },
                            "lower": {
                                "type": "string",
                                "index": "analyzed",
                                "analyzer": "lowercase",
                                "omit_norms": true,
                                "omit_term_freq_and_positions": true
                            }
                        }
                    }
                }
            },
            {
                "everything": {
                    "match": "*",
                    "mapping": {
                        "omit_norms": true,
                        "omit_term_freq_and_positions": true
                    }
                }
            }
        ]
    }
}
```

If I understand this page correctly (at the very bottom):

http://www.elasticsearch.org/guide/reference/mapping/root-object-type.html

the first mapping that matches will be applied -- i.e. "everything" should only be applied to fields that don't match "strings".

However, this isn't what I see (in 0.19.8 anyway) -- no matter which order I put the mappings in, all fields have "everything" applied, including string fields.

(By the way, "lowercase" is a simple custom analayzer with a keyword tokenizer and lowercase token filter.)

**Comment by ppf2** [comment]
Recently came across this.  The following is the use case:

https://gist.github.com/ppf2/6da223f9517ddc0e9465

In this case, what appears to work (Test #2 in the gist) is if I add `"match_mapping_type": "*"` in addition to `"match": "*"` in the dynamic template mapping for the default/everything fields.

**Comment by yanjunh** [comment]
This is a sweet workaround.  It appears working for me. thanks

**Comment by clintongormley** [comment]
Given @ppf2 's workaround in https://github.com/elastic/elasticsearch/issues/2401#issuecomment-85208238 it seems that we just need to default `match_mapping_type` to `*`?

**Comment by erikringsmuth** [comment]
+1

The workaround of adding `"match_mapping_type": "*"` to all fields works in the meantime.

```js
PUT /_template/log_template
{
  "template": "log*",
  "mappings": {
    "_default_": {
      "dynamic_templates": [
        {
          "timestamp": {
            "match": "@timestamp",
            "match_mapping_type": "*",
            "mapping": {
              "type": "date",
              "index": "not_analyzed",
              "doc_values": true
            }
          }
        },
        {
          "string_multifield": {
            "match": "*",
            "match_mapping_type": "string",
            "mapping": {
              "type": "string",
              "fields": {
                "raw": {
                  "type": "string",
                  "index": "not_analyzed",
                  "doc_values": true
                }
              }
            }
          }
        },
        {
          "catch_all": {
            "match": "*",
            "match_mapping_type": "*",
            "mapping": {
              "index": "not_analyzed",
              "doc_values": true
            }
          }
        }
      ]
    }
  }
}
```

**Comment by clintongormley** [comment]
@kimchy can you expand on what you mean here:

> The reason for this behavior is actually down to JSON and binary values. Because binary values in json are strings, trying to auto detect a date for example by trying to convert it to string ends up screwing up the internal parser binary value (I need to check if thats the case still). So we first need to try and match on name without actually knowing the type, and then match on the type...

This patch:

             if (unmatch != null && patternMatch(unmatch, name)) {
                 return false;
             }
    -        if (matchMappingType != null) {
    -            if (dynamicType == null) {
    -                return false;
    -            }
    -            if (!patternMatch(matchMappingType, dynamicType)) {
    -                return false;
    -            }
    +        if (dynamicType == null) {
    +            return false;
    +        }
    +        if (matchMappingType != null && !patternMatch(matchMappingType, dynamicType)) {
    +            return false;
             }
             return true;
         }

seems to work fine with binary strings, eg:

    DELETE test

    PUT test
    {
      "mappings": {
        "_default_": {
          "_source": {
            "enabled": false
          },
          "dynamic_templates": [
            {
              "dates": {
                "match": "*",
                "match_mapping_type": "date",
                "mapping": {
                  "type": "date",
                  "format": "YYYY-mm-dd"
                }
              }
            },
            {
              "everything": {
                "match": "*",
                "mapping": {
                  "type": "binary",
                  "store": true
                }
              }
            }
          ]
        }
      }
    }

    PUT test/test/1
    {
      "binary": "QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoB",
      "date": "2014-01-01"
    }

    GET /test/test/_mapping

returns:


            "_source": {
               "enabled": false
            },
            "properties": {
               "binary": {
                  "type": "binary",
                  "store": true
               },
               "date": {
                  "type": "date",
                  "format": "YYYY-mm-dd"
               }
            }

and

    GET test/test/_search?fields=*

returns:

            "fields": {
               "binary": [
                  "QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVoB"
               ]
            }

And to update the original example, this seems to work correctly:

    DELETE test

    PUT test
    {
      "mappings": {
        "_default_": {
          "dynamic_templates": [
            {
              "strings": {
                "match": "*",
                "match_mapping_type": "string",
                "mapping": {
                  "type": "string",
                  "fields": {
                    "raw": {
                      "type": "string",
                      "index": "not_analyzed"
                    }
                  }
                }
              }
            },
            {
              "everything": {
                "match": "*",
                "mapping": {
                  "type": "{dynamic_type}",
                  "doc_values": true
                }
              }
            }
          ]
        }
      }
    }

    PUT test/test/1
    {
      "string": "bar",
      "bool": true,
      "date": "2014-01-01",
      "int": 5
    }

    GET test/test/_mapping

returns:


            "properties": {
               "bool": {
                  "type": "boolean",
                  "doc_values": true
               },
               "date": {
                  "type": "date",
                  "doc_values": true,
                  "format": "dateOptionalTime"
               },
               "int": {
                  "type": "long",
                  "doc_values": true
               },
               "string": {
                  "type": "string",
                  "fields": {
                     "raw": {
                        "type": "string",
                        "index": "not_analyzed"
                     }
                  }
               }

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/18638
