### ISSUE TITLE
Could field value access be simplified?

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch#24036]
Accessing fields that are outside of source is pretty complex right now. There are options like `docvalue_fields`, `fieldata_fields`,  and `stored_fields` but using these options requires knowing and understand the mappings, along with several elasticsearch settings.

It's probably best that user's know how their data is indexed and that they request exactly what they want, but for applications it means we have to start pulling/comprehending mappings and settings to know what we should be requesting.

Any ideas that might simplify this?

**Comment by jpountz** [comment]
To me this is the reason why we have `_source`. I think of `docvalue_fields` (formerly `fielddata_fields`) and `stored_fields` as expert options for the case that the overhead of `_source` is not worth the simplicity it brings. Unfortunately, that indeed requires a closer relationship between the client application and mappings.

**Comment by jpountz** [comment]
It's been almost one year without update so I'll close this issue since we couldn't come up with suggestions how to make things simpler. Let's reopen if we get ideas that could help.

**Comment by javanna** [comment]
This sounds a lot like #49028 where we are reconsidering this same problem.
