### ISSUE TITLE
POST-ing to /_all/_open and /_all/_close break wildcard expansion

### ISSUE THREAD

**Issue by oxymor0n** [elastic/elasticsearch#24031]
Calling `POST /_all/_open` when there is no closed index or calling `POST /_all/_close` when there's no open index breaks the wildcard expansion of `_all` and `*`, causing ES to return a 404 message saying it couldn't find an index whose name is the unexpanded value.

On the other hand, calling `POST /your_index/_open` and `POST /your_index/_close` (i.e. using the exact name of the index) when `your_index` is acknowledged regardless of the state that `your_index` is in.

Steps to replicate:

1. Run ES (tested with the official Docker image)

```
docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" docker.elastic.co/elasticsearch/elasticsearch:5.3.0
```

2. Try to call `POST /_all/_open`

```
curl -XPOST -u elastic:changeme localhost:9200/_all/_close?pretty
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index",
        "index_uuid" : "_na_",
        "index" : "[_all]"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index",
    "index_uuid" : "_na_",
    "index" : "[_all]"
  },
  "status" : 404
}
```

**Comment by javanna** [comment]
Hi @oxymor0n what would you like Elasticsearch to do in those case instead? You are opening/closing an index, which is an operation that cannot be performed if no closed/open index matches the provided expression. You would prefer those apis to be a no-op in those cases, rather than returning an exception?

**Comment by oxymor0n** [comment]
Hello @javanna, thank you for responding.

IMHO the behavior in the case of closing/opening `_all`or `*`-patterns should be consistent with the current behavior of opening/closing an individual index (which returns `{acknowledged: true}` regardless of whether that index is already opened/closed). 

Alternatively, the error message should be changed and documented. As it is at the moment, it's not immediately clear to the user that the error is due to having no index in a valid state. In my case, I thought it meant that I've somehow broken/disabled the wildcard expansion of index names.

Furthermore, maybe the error vs no-op behavior should be controlled by the `ignore_unavailable` parameter, which in the document can disable the error "if the request explicitly refers to a missing index.". Right now, this parameter has no effect on the output of opening/closing wildcards.

- W

**Comment by olcbean** [comment]
```
PUT test
POST _all/_open
```
and 
```
PUT test
POST */_open
```
will both result in `"reason": "no such index"`

```
PUT test
POST test/_open
```
will result in `"acknowledged": true`

Looking in master it seems that `_all` will not be resolved. It is treated as a concrete index name instead of a meta one. 

@javanna Could you specify what the correct behavior should be?

----
I would like to have a go at this once the correct behavior is defined.

**Comment by oxymor0n** [comment]
I've just became aware of the `allow_no_indices` and `expand_wildcards` options (they weren't mentioned in the Open/Close Index API documentation) - sorry if my unfamiliarity with these API conventions caused some confusion 😓 

Setting `allow_no_indices=true` result in a different error if there is no closed index:

```
POST localhost:9200/_all/_open?allow_no_indices=true
{
    "error": {
        "reason": "Index name is required",
        "root_cause": [
            {
                "reason": "Index name is required",
                "type": "illegal_argument_exception"
            }
        ],
        "type": "illegal_argument_exception"
    },
    "status": 400
}
```

Only a combination of `allow_no_indices=true&expand_wildcards=all` results in a successful no-op. 

I understand that this is the default behavior, but imho it is quite obscure. As it is, both `ignore_unavailable` and `allow_no_indices` are not really doing what their documentation says they should do, and it's a bit confusing for new users.

**Comment by javanna** [comment]
I agree the behaviour is a bit confusing. The indices options are well applicable to read requests, to decide which indices to expand to and whether a request should throw an error or an empty response when no indices match the provided expression. 

That said, in case of open and close index, these api really need at least one index to perform the action against. That is why when you set `allow_no_indices=true` you get another error further down the road, indicating that allowing no indices is not supported. Given that these are not read apis, I am not sure we should make them work as a no-op when the request resolves to no indices. That would make the response unclear as there currently is no way to distinguish between a request that did something and a request that did nothing. Marking for discussion.

**Comment by javanna** [comment]
We discussed this as part of FixItFriday, and we would like to align open/close index api to the (desired) behaviour of the delete index api as explained in https://github.com/elastic/elasticsearch/issues/24104#issuecomment-294175335. Specifically, we would like to make open/close a no-op in case there are no matching indices in case `allow_no_indices` is set to `true`. That said, the default behaviour should stay strict as-is.

**Comment by javanna** [comment]
Once more, @olcbean feel free to send a PR and ping me for review.
