### ISSUE TITLE
Query String Query escaping spaces do not work

### ISSUE THREAD

**Issue by jasw** [elastic/elasticsearch#24035]
**Elasticsearch 2.3.5**:

**Plugins installed**: [head, search guard]

**1.8.0_74-b02**:

**32~14.04.1-Ubuntu**:

**Query String Query escaping spaces do not work**:

**Steps to reproduce**:
According to this document: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-query-string-query.html
 
> Watch this space
 A space may also be a reserved character. For instance, if you have a synonym list which converts "wi fi" to "wifi", a > query_string search for "wi fi" would fail. The query string parser would interpret your query as a search for "wi OR fi", while the token stored in your index is actually "wifi". Escaping the space will protect it from being touched by the query string parser: "wi\ fi".

```
{
  "query" : {
    "query_string" : {
      "query" : "*a\\ b\\ c\\ clean*",
      "fields" : [ "Reporting_Name", "Source_Document_Ref", "client.Client_Number" ]
    }
  }
}
```

All 3 fields above are type  raw 'not_analyzed'
Expected results: Matching on documents with any fields listed in the query that have text like "A B C Cleaning". 
Actual Result: No match.
Note: changing analyzer or flip 'escape' flag does not help either.

**Comment by olcbean** [comment]
As the fields are not analyzed, then the pattern `"*a\\ b\\ c\\ clean*"` will not match `"A B C Cleaning"`. Can you try applying `"tokenizer": "lowercase"` or changing your pattern to `"query" : "*A\\ B\\ C\\ Clean*"`?

**Comment by spinscale** [comment]
also, this does not look like a bug report. Please discuss issues like these in the dedicated [Elasticsearch discussion forum](https://discuss.elastic.co/c/elasticsearch), as github issues is intended for bug reports only. Thanks a lot!

**Comment by jasw** [comment]
@olcbean Thanks for the reply. That was a bad example but case does not matter.  "*A\\ B\\ C\\ Clean*" do not match either.  
@spinscale I get your point but I do think its a bug. The documentation specifically covered this test case but did not give the expected result. It is at least a bug in the documentation.  So please leave it open. Thanks Jason

**Comment by jasw** [comment]
@spinscale Also FYI,  I posted this question a week ago on the discussion forum https://discuss.elastic.co/t/query-string-query-escaping-spaces-in-v2-3/81254 with no reply.   But I do also believe it is worth a bug report as explained above. Thanks

**Comment by jasw** [comment]
@spinscale @kimchy Can you please reopen this ticket? Thanks

**Comment by timhng** [comment]
@spinscale , I agree with @jasw. This does appear to be a bug or documentation problem. I'm desperate to see this issue resolved. I'm trying to solve the same problem! Can this please be re-opened. Thanks.

**Comment by jasw** [comment]
@timhng @spinscale  New ticket raised here #24082 with more details and process to reproduce. You should be able to tell it is indeed a bug. Thanks

**Comment by danielmitterdorfer** [comment]
_Note: I'm cross-posting my comment from #24082 also here so this ticket is self-contained_

I just ran the reproduction scenario on a fresh install of Elasticsearch 2.4.4 and Elasticsearch 5.0.0. Both versions behave identical, so I cannot confirm your claim that Elasticsearch 5.0.0 behaves differently. Also, the query does not do what you think it does. Hence, I'll close it as it is not a bug.

However, I think I have a solution for your problem and will soon follow up on the related Discuss thread that you have created recently: https://discuss.elastic.co/t/query-string-query-escaping-spaces-in-v2-3/81254
