### ISSUE TITLE
Build Field Stats-based Resolution into Search API

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#24057]
I recently found myself using a tool that could not easily send `_field_stats` requests to prefetch the "right" indices for a given index pattern and a set of values. I worked around it by going the classic route of feeding it the raw index pattern and being done with it.

However, it got me thinking: could we build the index resolution aspect that tools like Kibana get from using `_field_stats` directly into the search to make it a single request. Generally speaking, I don't care what indices it uses; I just care that it talks to _only_ the right ones unless I need to make multiple requests in sequence.

```http
GET /my-index-*/_search
{
   "index_constraints" : {
      "@timestamp" : { 
         "max_value" : { 
            "gte" : "2014-01-01T00:00:00.000Z"
         },
         "min_value" : { 
            "lt" : "2015-01-01T00:00:00.000Z"
         }
      }
   },
   "query": { },
   "aggs": { }
}
```

It would probably make sense to _optionally_ return the indices that match the request as part of the response payload so that I could just chain requests together and use the first one to simply feed the remaining requests. Interestingly, this would also very likely eliminate the need for the date index resolver math, which is far more limiting than this type of approach (your date pattern must end up matching your index name).

I think that this could be particularly useful with cross-cluster search to avoid an enormous explosion that index patterns generally provide, but also to just simplify the common pattern.

**Comment by jpountz** [comment]
Actually we are following a different route. We recently made efforts that make requesting indices that do not contain any matching documents not an issue anymore by incrementally reduce responses that come from shards (#23946). So our new recommendation would be to just request all indices that match the index pattern and let Elasticsearch deal with it.

**Comment by pickypg** [comment]
@jpountz Will this effectively lead to the original usage of field stats? Naturally it's still a useful API for what it does, but is that the intent?
