### ISSUE TITLE
Source filtering in new field collapsing feature (Elasticsearch 5.3)

### ISSUE THREAD

**Issue by byronvoorbach** [elastic/elasticsearch#24063]
Hi.

While trying out the new 'field collapsing' feature in ES 5.3, I noticed that source filtering is handled differently than when source filtering is applied inside the top query element. I created a gist to show off an example:

https://gist.github.com/byronvoorbach/bc3d73c77aaa7ddaa96ee47a9ba886fc

In short: 'collapse' feature needs an explicit include/exclude during source filtering where as this not needed when using source filtering on top level documents

**Comment by s1monw** [comment]
@byronvoorbach good catch, do you wanna try to work on a PR for this, we are happy to help if you are up for it?

**Comment by byronvoorbach** [comment]
Hey @s1monw!

I'm leaving for Sweden the next couple of days, so won't have time for it till after the Easter weekend. Would be happy to work on a PR when I come back if that's not too late for you guys!

**Comment by s1monw** [comment]
@byronvoorbach just check in when you come back and see if it's been worked on... we will see how quickly we can get to it. You are welcome to help. Enjoy the trip ;)

**Comment by byronvoorbach** [comment]
@simonw Will do, wouldn't mind helping out! And thanks!

**Comment by byronvoorbach** [comment]
@simonw you got me excited to look into the codebase, and I found the issue. Just a single line change is needed to get it to work. 

Should I open up a PR or is it faster to note down the change here?

**Comment by s1monw** [comment]
no go ahead and open a PR please @byronvoorbach

**Comment by byronvoorbach** [comment]
@s1monw Done! https://github.com/elastic/elasticsearch/pull/24068

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/24068
