### ISSUE TITLE
Clarify how rounding 'extended_bounds' should work in 'date_histogram'

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#24064]
Working on #23789 we came upon some issue around `extended_bounds` in `date_histogram` when some rounding is used. The behaviour seems to be a bit unclear, so thats what this issue is about.

Currently, when using `interval` rounding of e.g. a day and providing extended bounds that are not rounded values, we round them down, e.g.:

```
GET index/test/_search
{
  "size": 0,
  "aggs": {
    "my_agg": {
      "date_histogram": {
        "extended_bounds": {
          "min": "2017-04-10T06:00:00Z",
          "max": "2017-04-13T08:00:00Z"
        },
        "field": "date",
        "interval": "1d",
        "min_doc_count": 0
      }
    }
  }
}
```
```
"aggregations": {
    "my_agg": {
      "buckets": [
        {
          "key_as_string": "2017-04-10T00:00:00.000Z",
          "key": 1491782400000,
          "doc_count": 0
        },
        {
          "key_as_string": "2017-04-11T00:00:00.000Z",
          "key": 1491868800000,
          "doc_count": 0
        },
        {
          "key_as_string": "2017-04-12T00:00:00.000Z",
          "key": 1491955200000,
          "doc_count": 1
        },
        {
          "key_as_string": "2017-04-13T00:00:00.000Z",
          "key": 1492041600000,
          "doc_count": 0
        }
      ]
    }
  }
```

To me that seems like a good behaviour because it leaves one edge buckets that overlaps the specified extended bound date. I furthermore think that any additional `offset` should shift the the buckets after rounding by a fixed amount (see https://github.com/elastic/elasticsearch/issues/23776 for a current bug with this)

**Comment by pmourlanne** [comment]
The behaviour of rounding down you describe is the one used in Elasticsearch 1.7
If I understand correctly, rounding up would give results like this :

```
"aggregations": {
    "my_agg": {
      "buckets": [
        {
          "key_as_string": "2017-04-11T00:00:00.000Z",
          "key": 1491868800000,
          "doc_count": 0
        },
        {
          "key_as_string": "2017-04-12T00:00:00.000Z",
          "key": 1491955200000,
          "doc_count": 1
        },
        {
          "key_as_string": "2017-04-13T00:00:00.000Z",
          "key": 1492041600000,
          "doc_count": 0
        },
        {
          "key_as_string": "2017-04-14T00:00:00.000Z",
          "key": 1491782400000,
          "doc_count": 0
        }
      ]
    }
  }
```

This means that any data that was between `2017-04-10T06:00:00Z` (the start of the extended bounds) and `2017-04-10T23:59:59Z` would not be included in the results. And we get an additional bucket starting on `2017-04-14T00:00:00.000Z` which we do not care about (it starts after the end of the extended bounds).

The behaviour you described, rounding down, is the only sensible one I can think of.

(I hope giving my opinion here was appropriate, if not I'm sorry :/)

**Comment by clintongormley** [comment]
Discussed in FixItFriday. Rounding down seems to make sense
