### ISSUE TITLE
snashot getting stuck on a shard V2.3.1

### ISSUE THREAD

**Issue by surekhabalaji** [elastic/elasticsearch#24066]
**Elasticsearch version**: 2.3.1

**Plugins installed**: []
lucene version 5.5.0

**JVM version**: open jdk 1.8.0

**OS version**: CentOS

**Description of the problem including expected versus actual behavior**:

I have setup a cluster with two ElasticSearch servers and have the NFS repo setup on the first server(master) and have the NFS mount setup on these two servers. I created the snapshot repo and was able to take snapshots of individual small indices. When I try to take the snapshot on the entire indices set, the snapshot process gets stuck on a couple of shards in a particular index. I had to stop the Elastic Search servers and restart them to clear the stuck snapshot. 
After restarting, when I tried taking the snapshot, it again got stuck in the same shards. It has been stuck for past 15 hours.

Please see below to see the stuck shards '3' & '4'

 "2": {
                     "stage": "DONE",
                     "stats": {
                        "number_of_files": 207,
                        "processed_files": 207,
                        "total_size_in_bytes": 50471623283,
                        "processed_size_in_bytes": 50471623283,
                        "start_time_in_millis": 1491948418067,
                        "time_in_millis": 2135013
                     }
                  },
                  "3": {
                     "stage": "STARTED",
                     "stats": {
                        "number_of_files": 204,
                        "processed_files": 190,
                        "total_size_in_bytes": 43726103499,
                        "processed_size_in_bytes": 32915497923,
                        "start_time_in_millis": 1491948498451,
                        "time_in_millis": 0
                     },
                     "node": "ohMx7BUXRfyym0YaTlpreQ"
                  },
                  "4": {
                     "stage": "STARTED",
                     "stats": {
                        "number_of_files": 211,
                        "processed_files": 187,
                        "total_size_in_bytes": 51847398788,
                        "processed_size_in_bytes": 40983724276,
                        "start_time_in_millis": 1491948421440,
                        "time_in_millis": 0
                     },
                     "node": "inro3uspRw68FigfTxxu3Q"

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by abeyad** [comment]
Do you have any information in the log files that you can share that would be pertinent?

Also, could you kindly create a post on the [discussion](https://discuss.elastic.co/) forum and I'll be happy to help you there.  We reserve Github for known bugs or feature requests, so until we discuss and eliminate the possibility of the issue being in NFS etc, lets move it to the discussion forums please.  Thank you!

**Comment by surekhabalaji** [comment]
@abeyad , I created a post on the discussion forum for this
https://discuss.elastic.co/t/snashot-getting-stuck-on-a-shard-v2-3-1/82191

**Comment by abeyad** [comment]
@surekhabalaji great, thanks, I'll respond there.  In the meantime, I'll close this issue and if we determine there is a bug in Elasticsearch, we can re-open.
