### ISSUE TITLE
could not find commonTermsQuery api definition for elasticsearch 5.1.1

### ISSUE THREAD

**Issue by ApprenticeMythology** [elastic/elasticsearch#24080]
i just begin to use elasticsearch 5.1.1, but i could not find commonTermsQuery api definition, detail below: 
//set cluster name
			Settings settings = Settings.builder().put("cluster.name", "es5-cluster").build();
			TransportClient client = new PreBuiltTransportClient(settings)
					.addTransportAddress(
							new InetSocketTransportAddress(InetAddress.getByName("127.0.0.1"), 9300));// 127.0.0.1

//this line could not find definition, which dependcy should i add for elasticsearch 5.1.1
please help, thanks~~~
QueryBuilder qb = commonTermsQuery("name","kimchy"); 

i added dependcy  in  pom.xml

		<dependency>
    		<groupId>org.elasticsearch</groupId>
    		<artifactId>elasticsearch</artifactId>
    		<version>5.1.1</version>
		</dependency>	
		
		
		<dependency>
    		<groupId>org.elasticsearch.client</groupId>
    		<artifactId>transport</artifactId>
    		<version>5.1.1</version>
		</dependency>

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
