### ISSUE TITLE
Decouple MultiValueMode

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#24087]
`MultiValueMode` does two things at once: it selects the min/max/median/sum value when documents have multiple values, but also returns a missing value when documents do not have a value. Decoupling would make things cleaner, easier to test and would eg. allow to remove the hack from the matrix stats aggs that need to treat `NEGATIVE_INFINITY` as a missing value since we do not expose ways to select the minimum value without also replacing missing values at the moment.

**Comment by DimitrisParaskevaidis** [comment]
I was thinking about decoupling all anonymous classes, to separate files. I would make sure that tests should succeed after all small steps.

**Comment by mayya-sharipova** [comment]
@DimitrisParaskevaidis  Would you still like to work on this issue?  We don't need to assign you, if you would like to work on it, please let us know here!

**Comment by DimitrisParaskevaidis** [comment]
I would still like to work on this issue . I need more information on how
to decouple MultiValueMode.

Στις Παρ, 23 Μαρ 2018, 6:00 μ.μ. ο χρήστης Mayya Sharipova <
notifications@github.com> έγραψε:

**Comment by wchaparro** [comment]
Closing as not planned for aggregations framework.
