### ISSUE TITLE
Remove UnsortedNumericDoubleValues

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#24086]
This class is a work-around for the fact that multi-valued numerics expect values to be delivered in order. However this attempt to not deliver values in sorted order has the downside of adding a new abstraction that also needs to support computing the min or max values per document. We should remove it and sort values on the fly.

**Comment by liketic** [comment]
@jpountz Can I take this? Seems like this interface is used in a lot of code. Could you provide some help? Thanks in advance.

**Comment by jpountz** [comment]
@liketic Sure. Basically you'd need to remove that interface and convert existing implementations to `SortingNumericDoubleValues`.

**Comment by liketic** [comment]
Thanks! 😄
