### ISSUE TITLE
Create mapping 

### ISSUE THREAD

**Issue by ToujouAya** [elastic/elasticsearch#24107]
**Elasticsearch version**: 5.3.0

**Plugins installed**: []

**JVM version**:  1.8.0_121

**OS version**: windows 10 

**Description of the problem including expected versus actual behavior**:
There is my mapping code created in PHP
`'mappings' => [
                'items' => [
                    'attributes' => [
                        'type' => 'string'
                    ]

                ]
            ]`

attributes property is an object like this 
`
{
title : '',
'description'
}
`

I want to sort in the **title**  . But it show the error that I need to enable fielddata of titile. 
I have changed the config mapping many time but it's not working.

![image](https://cloud.githubusercontent.com/assets/21350606/25040501/f6c298a2-2133-11e7-9fbe-7b1d5e9fba0b.png)
I used basemkhirat/elasticsearch package to connect to elasticsearch serve.
Does anyone have any idea to solve this case?
Please help me. Sorry for my English
Thank you .

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
