### ISSUE TITLE
colon seprate problem?

### ISSUE THREAD

**Issue by heiterzhang** [elastic/elasticsearch#24101]
lasticsearch version: "2.3.1"

Plugins installed: [null]

JVM version:"1.8.0_65"

OS version: "CentOS Linux release 6.2 (Final)"

Description of the problem including expected versus actual behavior:

Steps to reproduce:
1.import this message "tody we go to gdeliveryd: debug:DS::MidasFailInfo:ret=0" in ES
2.search
3.when i search use MidasFailInfo:ret ,it returns normally;
bu when i use part of this words , such as use MidasFailInfo ,it returns empty

i want it returns normally when i search "MidasFailInfo" ,thx

Provide logs (if relevant):

Describe the feature:

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
