### ISSUE TITLE
Add independent boosting of More Like This Query's like vs unlike parameters

### ISSUE THREAD

**Issue by davidklebanoff** [elastic/elasticsearch#24119]
The More Like This Query has parameters for querying documents both **like** and **unlike** given text or documents. It would be nice if these parameters (like and unlike) could be boosted individually so that a balance of false-negatives vs false-positives can be configured through fine tuning of the two parameters.

**Comment by 0xCAB** [comment]
Looking at `MoreLikeThisQueryBuilder` and related classes, it seems the terms extracted from the `unlike` part are skipped from the final MLT query. The boost (if set) is applied to the remaining terms coming from the `like` part.
Could you elaborate on your idea? Do you suggest leaving "skipTerms" in the query and applying a different boost to them?
Maybe another approach would be to add terms from `unlike` via `Occur.MUST_NOT` to the BooleanQuery.

**Comment by davidklebanoff** [comment]
My initial intent was to allow a configurable balancing act between documents matching a combination of `like` and `unlike` ids specified in the query. However, if terms in the documents specified in the `unlike` section are skipped altogether like you describe, this raises an even bigger divergence from my desired/expected behavior.

I would expect 'unlike' documents to simply have an opposite effect to the `like` documents, perhaps with a negative or fractional boost to lower their ranking, not filtering them out all together.

Let's use Netflix movies as a crude example. Suppose we have three movies with a given set of genre fields and a simple like/dislike feature:

A - Like - Action, Comedy
B - Like - Action, Drama
C - Dislike - Action, Comedy

Using these in a `MoreLikeThisQuery`, I would put documents `[A,B]` as input into the `like` parameter and `[C]` as input into the unlike `parameter`. As a result, I would expect Action movies (2 likes vs 1 dislike) and Drama movies (1 like) to be returned... and who know about Comedy movies (1 like vs 1 dislike).

Although, it sounds like given your explanation of how it currently works, we would not see any Action movies, because that term would be skipped. I think that should change. Additionally, If boosting per `like` vs `unlike` was available in the given scenario, one could change the balance of impact a like or dislike has on the final results. For example, if it was configured that a `like` was given twice the boost of a `dislike`, Comedy movies would be returned in the example above.

I hope my above examples clarify my desired/expected behavior.

**Comment by clintongormley** [comment]
As @0xCAB said, the `unlike` terms are stripped from the `like` terms before querying.  For the example you use, you could combine the MLT query with either the function score query or use negative boosting in the boosting query.
