### ISSUE TITLE
Update the More Like This Query documentation for the unlike parameter

### ISSUE THREAD

**Issue by davidklebanoff** [elastic/elasticsearch#24117]
Update the documentation on the ["More Like This Query" page](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html#_document_input_parameters) to make it clear that the "unlike" parameter can use the Multi GET API, just like the "like" parameter. 

Also, in the 1st example on the page the "like" parameter is being used like I imagine "like_text" is supposed to be used. Perhaps the documentation for the More Like This Query is in need of some larger updates overall.

Original issue:
~~Currently the More Like This Query can operate on two types of input: text via the **like** and **unlike** parameters, or full documents through the **ids** parameter.~~

~~The **ids** parameter allows you to input a number of document ids into the query which will return documents similar to the ones provided. There is however, in contrast to the text input options, no way to provide document IDs for documents unlike the desired results.~~

~~I propose we break out the ids parameter into two parameters, much like the text parameters:~~
- ~~likeIds~~
- ~~unlikeIds~~

**Comment by davidklebanoff** [comment]
Nevermind. It's not immediately obvious from the documentation, but I believe this can be achieved with the current API design. Perhaps clearer documentation on [this page](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-mlt-query.html#_document_input_parameters) could make it more apparent that unlike parameter can also use the Multi GET API.

**Comment by javanna** [comment]
hi @davidklebanoff would you be willing to send a PR to clarify our docs?

**Comment by davidklebanoff** [comment]
@javanna Sorry, I do not have the time.

**Comment by cbuescher** [comment]
@davidklebanoff revisiting this issue, I just read the documentation again and in its current form (> 6.0) the page you mentioned says "The syntax is the same as `like`", which in turn mentions the syntax similarity to the Multi Get API. I'm not sure how this should be improved, so I'm closing this issue for now, but please reopen if you have any more concrete suggestions of how the docs should be improved in your opinion.
