### ISSUE TITLE
Don't fetch source by default for nested inner hits?

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#24110]
Elasticsearch has to do an expensive trick to the _source for nested inner hits during the fetch phase. The _source isn't stored with the nested document, but with the root document, so when fetching the _source for inner hits, it gets parsed and the relevant nested part gets extracted and included in the response for that inner nested hit. This can add a significant tax on the search request, especially when fetch more then 10 top level document, or multiple nested inner hit definitions on the search request or returning more than 3 nested docs per inner hit.

I like to change to default behaviour here, so that by default we don't include the _source for nested documents. If the source is needed then it can be turned on and the cost for this becomes than more clear. Also someone relying on this should consider enabling stored fields for specific nested fields that care about. Fetching stored fields for nested inner hits is quick as the stored fields are associated with the nested documents, so there is no need for an expensive trick here.

**Comment by martijnvg** [comment]
Discussed this at fix-it-friday and source computation can be much cheaper if take this into account when implementing #23917, so for now we shouldn't change the default here. If #23917 doesn't give the desired performance improvements we can reconsider.

Also we should better document the cost of fetching source for nested inner hits and the fact that one can just use stored fields for nested documents to significantly improve performance.

**Comment by abhishek5678** [comment]
Hi Guys,
In this data when i am trying with one level nested data then it's working fine but when i am adding one more nested data then it's not working if anybody will be knows about that then please reply me.I am sending my document data and mapping file also.

POST /test_word14/doc/1
{
"name": "Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism (D50-D89)",
"depth": 1,
"children": [{
"name": "Nutritional anemias (D50-D53)",
"depth": 2,
"children": [{
"code": "D50",
"name": "Iron deficiency anemia",
"depth": 3,
"children": [{
"code": "D50.0",
"name": "Iron deficiency anemia secondary to blood loss (chronic)",
"depth": 4
}, {
"code": "D50.1",
"name": "Sideropenic dysphagia",
"depth": 4
}, {
"code": "D50.8",
"name": "Other iron deficiency anemias",
"depth": 4
}, {
"code": "D50.9",
"name": "Iron deficiency anemia, unspecified",
"depth": 4
}]
}]
}]
}

(mapping file)
PUT /test_word16
{
"mappings": {
"doc": {
"properties": {
"name": { "type": "string" },
"depth": {"type":"long"},
"children": {
"type": "nested",
"properties": {
"name": { "type": "string" },
"depth": { "type": "long" },
"children": {
"type": "nested",
"properties": {
"code": { "type": "string" },
"name": { "type": "string" },
"depth": { "type": "long" },
"children": {
"type": "nested",
"properties": {
"code": { "type": "string" },
"name": { "type": "string" },
"depth": { "type": "long" },
}
}
}
}
}
}
}
}
}
}

please tell me what is the query i am applying here.i applied the query like this:
GET /icd10_codes/doc/_search
{
"_source": false,
"query": {
"nested": {
"path": "children",
"query": {
"nested": {
"path": "children.children",
"query": {
"nested": {
"path": "children.children.children",
"query": {
"bool": {
"must": [
{
"match": {
"children.children.name": "Iron"
}
}
]
}
},
"inner_hits": {
"_source": {
"excludes":["name"]
}
}
}
}
}
}
}
}

**Comment by clintongormley** [comment]
@abhishek5678 please stop asking the same question on different threads. Ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks

**Comment by abhishek5678** [comment]
@clintongormley ok I put my problem in https://discuss.elastic.co/
But can you help me to solve this problem
