### ISSUE TITLE
Kibana does not support using tribe nodes as the primary elasticsearch connection.

### ISSUE THREAD

**Issue by ertaoxu** [elastic/elasticsearch#24127]
my tribe node config:

node.name: elk-tribe-1
node.master: false
node.data: false
path.data: /data/es_data/
path.logs: /data/es_log/
network.host: 10.200.0.51
tribe:
  es1:
    cluster.name: xg-ops-elk-javaes-cluster
    discovery:
      zen:
        ping:
          unicast:
            hosts:
              - xg-ops-elk-javaes-1:9300
              - xg-ops-elk-javaes-2:9300
              - xg-ops-elk-javaes-3:9300
  es2:
    cluster.name: xg-ops-elk-pyes-cluster
    discovery:
      zen:
        ping:
          unicast:
            hosts:
              - xg-ops-elk-pyes-1:9300
              - xg-ops-elk-pyes-2:9300
              - xg-ops-elk-pyes-3:9300
  on_conflict: prefer_es1

THE issues:

  log   [04:04:32.347] [info][status][plugin:kibana@5.2.1] Status changed from uninitialized to green - Ready
  log   [04:04:32.414] [info][status][plugin:elasticsearch@5.2.1] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [04:04:32.642] [info][status][plugin:timelion@5.2.1] Status changed from uninitialized to green - Ready
  log   [04:04:32.647] [info][listening] Server running at http://0.0.0.0:5601
  log   [04:04:32.648] [info][status][ui settings] Status changed from uninitialized to yellow - Elasticsearch plugin is yellow
  log   [04:04:32.712] [error][status][plugin:elasticsearch@5.2.1] Status changed from yellow to red - Kibana does not support using tribe nodes as the primary elasticsearch connection.
  log   [04:04:32.713] [error][status][ui settings] Status changed from yellow to red - Elasticsearch plugin is red

**Comment by dadoonet** [comment]
Let's keep the discussion there: https://discuss.elastic.co/t/kibana-does-not-support-using-tribe-nodes-as-the-primary-elasticsearch-connection/82524/1

**Comment by ertaoxu** [comment]
Thanks
