### ISSUE TITLE
Context suggester's context doesn't work on keyword type

### ISSUE THREAD

**Issue by masaruh** [elastic/elasticsearch#24129]
**Elasticsearch version**:
5.3.0

**Description of the problem including expected versus actual behavior**:
When contest field specified by `path`  is `text` type, it works as expected. However, if it's set to `keyword` type, context is set to empty/null.

**Steps to reproduce**:
https://gist.github.com/masaruh/f217c26cf9b52ca71381b088f0e78630

It looks it's because when [CategoryContextMappng reads field value](https://github.com/elastic/elasticsearch/blob/v5.3.0/core/src/main/java/org/elasticsearch/search/suggest/completion/context/CategoryContextMapping.java#L136), `KeywordFieldType` returns `null` (since it doesn't have string value).
Not sure if it's expected behavior or not. But if it's expected, it's better to be documented.

**Comment by vsiv** [comment]
I can reproduce this as well on 5.3. I too am curious whether this is expected behavior.  Thanks.

**Comment by vsiv** [comment]
There is also a bug in the documentation. The first mapping should not have path configured since its consuming direct category values at index time. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/suggester-context.html

**Comment by jasontedor** [comment]
@colings86 Can you take a look?

**Comment by colings86** [comment]
I've reproduced this on the current master branch and to me it looks like a bug. @areek are you able to take this?
