### ISSUE TITLE
elasticsearch 5.3.0 scroll slice api has unexpected results

### ISSUE THREAD

**Issue by pinguo-gongjunheng** [elastic/elasticsearch#24131]
**Elasticsearch version**: 5.3.0

**Plugins installed**: [x-pack, es-discovery]

**JVM version**: oracle jdk8

**OS version**: ubuntu 16.04

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
* count on entire index
```
GET some_index_with_12_shards/event/_count
```
result:
```
{
  "count": 26269522,
  "_shards": {
    "total": 12,
    "successful": 12,
    "failed": 0
  }
}
```
* count on on shard 0
```
GET some_index_with_12_shards/event/_count?preference=_shards:0|_local
```
result:
```
{
  "count": 2188043,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  }
}
```
* create slice scroll with shard 0:
```
GET some_index_with_12_shards/event/_search?scroll=10m&sort=_doc&preference=_shards:0|_local
{
  "slice": {
    "id": 0,
    "max": 21
  }
}
```
result:
![image](https://cloud.githubusercontent.com/assets/19701039/25087695/5cbc2c10-23a3-11e7-9fdd-4d20b81493d7.png)

screen shot show the slice result is for entire index not just shard 0. 

* create scroll without shard 0 preference
```
GET some_index_with_12_shards/event/_search?scroll=10m&sort=_doc
{
  "slice": {
    "id": 0,
    "max": 21
  }
}
```
result
![image](https://cloud.githubusercontent.com/assets/19701039/25087770/f10100c6-23a3-11e7-880c-d92f8b39b291.png)

* try to consume the scroll with preference shard 0, it possible no data, cause we are using elasticsearch generate _uid and in a time sequence index.

* and we are using elasticsearch-hadoop to access those indices, the elasticsearch-hadoop use shard based slice create spark partition, it will cause empty partitions and multi time re-create scrolls on entire scroll.

follow attachment is temporary patch let elasticsearch-hadoop 5.3.0 work with elasticsearch cluster 5.3.0.
simply avoid shard related partition replace it with slice on entire index.

[fix_scroll_slice_issues.patch.zip](https://github.com/elastic/elasticsearch/files/925421/fix_scroll_slice_issues.patch.zip)

**Comment by jasontedor** [comment]
@jimczi Can you take a look?

**Comment by pinguo-gongjunheng** [comment]
if need any other information please contact me feel free.

**Comment by jimczi** [comment]
@pinguo-gongjunheng I am not able to reproduce. When I set the preference on a specific shard, the search returns results from this shard only even when I use the slicing. I tried the following reproduction:

``````
# Create the index with 12 shards
PUT some_index_with_12_shards
{
	"settings": {
		"number_of_shards": 12
	}
}

# Add some documents with auto generated ids 
POST some_index_with_12_shards/event
{
	"field": "hello"
}

GET some_index_with_12_shards/event/_search?scroll=10m&sort=_doc&preference=_shards:0|_local

=> result:
{
  "_scroll_id": "DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAAAAkWQklmZTBQaFhSY2E2Y0Z0N1VZYU1Jdw==",
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 1,
...
}

# search with slice:
GET some_index_with_12_shards/event/_search?scroll=10m&sort=_doc&preference=_shards:0|_local
{
	"slice": {
		"id": 0,
		"max": 2
	}
}

=> result:
{
  "_scroll_id": "DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAAAAoWQklmZTBQaFhSY2E2Y0Z0N1VZYU1Jdw==",
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 1,
...
}

# removing the preference returns results from entire index:
GET some_index_with_12_shards/event/_search?scroll=10m&sort=_doc
{
	"slice": {
		"id": 0,
		"max": 2
	}
}

=> result:
{
  "_scroll_id": "DnF1ZXJ5VGhlbkZldGNoDAAAAAAAAAAGFnRZSy1jdDVqUU4tUFQ1eU0wTUJFd1EAAAAAAAAAARZ0WUstY3Q1alFOLVBUNXlNME1CRXdRAAAAAAAAAAIWdFlLLWN0NWpRTi1QVDV5TTBNQkV3UQAAAAAAAAAFFnRZSy1jdDVqUU4tUFQ1eU0wTUJFd1EAAAAAAAAACxZCSWZlMFBoWFJjYTZjRnQ3VVlhTUl3AAAAAAAAAAwWQklmZTBQaFhSY2E2Y0Z0N1VZYU1JdwAAAAAAAAAEFnRZSy1jdDVqUU4tUFQ1eU0wTUJFd1EAAAAAAAAAAxZ0WUstY3Q1alFOLVBUNXlNME1CRXdRAAAAAAAAAA0WQklmZTBQaFhSY2E2Y0Z0N1VZYU1JdwAAAAAAAAAOFkJJZmUwUGhYUmNhNmNGdDdVWWFNSXcAAAAAAAAADxZCSWZlMFBoWFJjYTZjRnQ3VVlhTUl3AAAAAAAAABAWQklmZTBQaFhSY2E2Y0Z0N1VZYU1Jdw==",
  "took": 94,
  "timed_out": false,
  "_shards": {
    "total": 12,
    "successful": 12,
    "failed": 0
  },
  "hits": {
    "total": 13,
...
}
``````

I tried with ES 5.3.0 and it works as expected. Did I miss something in your example that triggers the problem ?

**Comment by pinguo-gongjunheng** [comment]
badly our cluster has re-create by ops, in new cluster we can not reproduce this issues either. just close it and re-open if we enable reproduce
