### ISSUE TITLE
Still use default jvm.options even start with -Edefault.path.conf

### ISSUE THREAD

**Issue by hellokangning** [elastic/elasticsearch#24159]
**Elasticsearch version**:
5.3

**Plugins installed**: 
[x-pack]

**JVM version**:
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-3~14.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

**OS version**:
Ubuntu 14.04, and install Elasticsearch with Debian Package.

**Description of the problem including expected versus actual behavior**:

`/etc/elasticsearch/jvm.options` as following:
```
-Xms1g
-Xmx1g
```

`/disk2/elasticserach/config/jvm.options` as following:
```
-Xms2g
-Xmx2g
```

`/etc/default/elasticsearch` as following:
```
ES_JAVA_OPTS="-Xms3g -Xmx3g"
```

Then assign new config directory in `/etc/default/elasticsearch`
```
CONF_DIR=/disk2/elasticsearch/config
```

Finnaly I start Elasticsearch by `service elasticsearch start` and execute `ps aux | grep elastic`:

![](https://cloud.githubusercontent.com/assets/5053603/25134475/3da032ec-2482-11e7-9a3b-bf8186d1c17c.png)

The default `jvm.options` and `ES_JAVA_OPTS` works, But new assigned config file does NOT.

**Comment by jasontedor** [comment]
Setting `path.conf` controls the path of the Elasticsearch configuration file, it is never parsed until the JVM has already started where it's too late to find `jvm.options` (and I'm opposed to complicating the startup scripts to parse this before starting the JVM). If you want to specify a different path for jvm.options, you have to set the environment variable `ES_JVM_OPTIONS` to the full path of the desired configuration.
