### ISSUE TITLE
elasticsearch highlight lose Chinese right bracket

### ISSUE THREAD

**Issue by liuguangmin** [elastic/elasticsearch#24151]
I user ES highlightCompont ,encounter a problem
my hightlight's config below:(the highlighter type:plain)
"number_of_fragments": 1,
"fragment_size": 150,
"no_match_size": 150,
"require_field_match": False，
“field”:"title"

my request is http://127.0.0.1:9900/search/iyiou?query=信良记&debug=1&fields=title

And the response:
{
"status": "WARN",
"resultdata": [
{
"itemid": 41859,
"title": "首发丨餐饮供应链品牌<font color=red>信</font><font color=red>良</font><font color=red>记</font>获5000万元Pre-A轮融资"
},
{
"itemid": 43075,
"title": "新辣道小龙虾消失，改善深加工供应链"
},
{
"itemid": 42875,
"title": "李丰x李剑：揭秘小龙虾千亿级消费市场的秘密"
},
{
"itemid": 42409,
"title": "餐饮行业开始打开B端市场，供应链或许成为其最大需求"
},
{
"itemid": 42330,
"title": "一周回顾丨餐饮行业大事件（03.26-04.01"
}
],
"errors": {
"message": "scene_type is null",
"code": -2
},
"resultcount": 5,
"request_id": "1492497551180107"
}

you will find the below record
{
"itemid": 42330,
"title": "一周回顾丨餐饮行业大事件（03.26-04.01"
}

loss Chinese right bracket --->")"

the source doc title is "一周回顾丨餐饮行业大事件（03.26-04.01）"

beacuse this doc is not contains the search word ,so no highlight ,what wrong?
if I change other highlight type for example fvh ,can solve the problem ?

I have change other request :+1:
http://127.0.0.1:9900/search/iyiou?query=餐饮&debug=1&fields=title

the response

{
"status": "WARN",
"resultdata": [
{
"itemid": 43275,
"title": "一周回顾丨<font color=red>餐饮</font>行业大事件（04.10-04.16）"
},
{
"itemid": 43221,
"title": "从麦当劳到绿山，美国<font color=red>餐饮</font>业发生了什么？"
},
{
"itemid": 43081,
"title": "“三高”压顶，<font color=red>餐饮</font>业第二春在何方？"
},
{
"itemid": 43115,
"title": "雄安大迁徙！<font color=red>餐饮</font>人要不要去雄安开<font color=red>餐</font>厅？"
},
{
"itemid": 43073,
"title": "同城众投签约天财商龙，布局全国<font color=red>餐饮</font>股权众筹加速"
},
{
"itemid": 43082,
"title": "中百集团万明治：超市<font color=red>餐饮</font>化很大程度上是个伪命题"
},
{
"itemid": 43046,
"title": "无人机送外卖？2017年<font color=red>餐饮</font>业你该了解的七大趋势"
},
{
"itemid": 42965,
"title": "两年开出125家店的Kao铺创始人吕强：<font color=red>餐饮</font>品牌应该是流量入口的平台"
},
{
"itemid": 42773,
"title": "一周回顾丨<font color=red>餐饮</font>行业大事件（04.02-04.09）"
},
{
"itemid": 42747,
"title": "吴国平：用快时尚做<font color=red>餐饮</font>，外婆家要“慢慢玩”"
},
{
"itemid": 42503,
"title": "中了<font color=red>餐饮</font>业“第四高”，月流水50万仍在赔钱！"
},
{
"itemid": 42409,
"title": "<font color=red>餐饮</font>行业开始打开B端市场，供应链或许成为其最大需求"
},
{
"itemid": 42452,
"title": "三天卖掉同等<font color=red>餐</font>厅一年的量，超市<font color=red>餐饮</font>以低价入侵传统<font color=red>餐饮</font>"
},
{
"itemid": 42330,
"title": "一周回顾丨<font color=red>餐饮</font>行业大事件（03.26-04.01）"
},
{
"itemid": 42029,
"title": "<font color=red>餐饮</font>店面转让费：轮回的陷阱，轮回地坑"
},
{
"itemid": 42011,
"title": "<font color=red>餐饮</font>行业面临新变革，SaaS公司能否成功破竹？"
},
{
"itemid": 41849,
"title": "供应商抢滩<font color=red>餐饮</font>市场玩起全产业链，<font color=red>餐饮</font>老板真完了吗？"
},
{
"itemid": 41859,
"title": "首发丨<font color=red>餐饮</font>供应链品牌信良记获5000万元Pre-A轮融资"
},
{
"itemid": 41650,
"title": "一周回顾丨<font color=red>餐饮</font>行业大事件（03.19-03.25）"
},
{
"itemid": 41675,
"title": "没有支付牌照，智慧<font color=red>餐饮</font>“见光死”？"
}
],
"errors": {
"message": "scene_type is null",
"code": -2
},
"resultcount": 2616,
"request_id": "1492505478181592"
}

I find chinese right bracket appear,

how i solve the problem ,this is maybe a budge

**Comment by jimczi** [comment]
Thanks @liuguangmin 
For no-highlight snippets  the `plain` highlighter discards any character after the last detected word that fits into the `match_no_size` window. This is why `) ` is missing in the highlight response.
The `fvh` has a different behavior and keeps all characters as long as they are in the `match_no_size` range. 
In 5.3.0 we've added a new highlighter called `unified` that should in the near future replace the other alternatives. For the `no_match_size` option it behaves like the `fvh` and does not remove any character. I'd suggest to switch to this new highlighter or upgrade to a version where this highlighter is available.

**Comment by liuguangmin** [comment]
THx I have solve the problem

**Comment by eyesraining** [comment]
THx I have solve the problem
