### ISSUE TITLE
Keyword type: aggregation case insensitive

### ISSUE THREAD

**Issue by giocaputo** [elastic/elasticsearch#24152]
I have a problem with keyword type:
can i aggregate a a file with a keyword type wihout losing the case and sorting case insensitive?

Using the normalizer and lowercase filter lose the the case.
using the text type  must enable fielddata that can consume a lot of heap space, especially when loading high cardinality 

**Elasticsearch version**: 5..2

**Comment by jimczi** [comment]
Please ask questions on the forum; Elastic reserves GitHub for verified bug reports and feature requests.
For your issue since aggregations and sorting use the `doc_values` to extract the value for each document you'll have to use a copy field with a different config for the field sort.

**Comment by giocaputo** [comment]
can be tagged as feature requests?

**Comment by giocaputo** [comment]
@jimczi why is closed yet? can be a  feature requests?
