### ISSUE TITLE
Parse and validate mappings in index templates when they are put

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#2415]
Currently, putting a template will succeed if the JSON is valid even if the mapping couldn't be parsed. An error will be thrown when the index will be created and try to use the mapping, but that may be too late.

An example for such an error is described in https://github.com/elasticsearch/elasticsearch/issues/2414

The probable solution is to validate the mapping defined in the template when putting it.

**Comment by clintongormley** [comment]
@johtani An idea from #14160: When checking the provided index template for validity, store the template as the JSON generated from the real mappings, instead of storing the original string.

**Comment by johtani** [comment]
@clint I see. Just now I don't change storing logic. I will try it.

**Comment by johtani** [comment]
@clint I tried to change storing logic in #8802, then I would like to separate with #8802. 
I need more time for implementing to store the JSON generated from the real mappings. Now, I think the JSON generated from the mappings has properties witbout default values., however, it is some problem for storing template.
