### ISSUE TITLE
Separator not added when adding raw values within array context in XContentBuilder

### ISSUE THREAD

**Issue by zarucki** [elastic/elasticsearch#24166]
Not confident enough to fix it myself and submit as pull request.

Failing test case to add to XContentBuilderTests:
```
{
  XContentBuilder xContentBuilder = XContentFactory.contentBuilder(XContentType.JSON);
  xContentBuilder.startArray();
  xContentBuilder.rawValue(new BytesArray("\"value1\""), XContentType.JSON);
  xContentBuilder.rawValue(new BytesArray("\"value2\""), XContentType.JSON);
  xContentBuilder.endArray();
  assertThat(xContentBuilder.bytes().utf8ToString(), equalTo("[\"value1\",\"value2\"]"));
}
```

When run on master I get:

> Expected: "[\"value1\",\"value2\"]"  but: was "[\"value1\"\"value2\"]"

**Comment by tlrx** [comment]
XContentBuilder.rawValue() is a method used to directly write a BytesReference in the XContentBuilder's output stream. It is used in very specific cases within Elasticsearch when we don't want to copy over or rebuild an object and most of the time it should not be used at all outside these specific cases.

I guess in your case you could use the writeRawField() method which takes care of update the writing context but you'll have to modify the raw content you want to write.

The normal use for the case you described is to use any of the XContentBuilder.array() method.

**Comment by zarucki** [comment]
Ok sorry, fair enough. I got confused by javadocs in com.fasterxml.jackson.core.JsonGenerator where it says:
```
    /**
     * Method that will force generator to copy
     * input text verbatim without any modifications, but assuming
     * it must constitute a single legal JSON value (number, string,
     * boolean, null, Array or List). Assuming this, proper separators
     * are added if and as needed (comma or colon), and generator
     * state updated to reflect this.
     */
    public abstract void writeRawValue(String text) throws IOException;

```
