### ISSUE TITLE
CI Failure: org.elasticsearch.discovery.zen.ElectMasterServiceTests.testHasEnoughNodes

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#24165]
Reproduce locally.

CI Failure: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=amazon/856/console

Reproduce With:
gradle :core:test -Dtests.seed=C6257E620EBB86EE -Dtests.class=org.elasticsearch.discovery.zen.ElectMasterServiceTests -Dtests.method="testHasEnoughNodes" -Dtests.security.manager=true -Dtests.locale=it -Dtests.timezone=Europe/Brussels

**Comment by danielmitterdorfer** [comment]
Also on 5.x: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.4+multijob-unix-compatibility/os=fedora/17/console

**Comment by danielmitterdorfer** [comment]
This is fixed by https://github.com/elastic/elasticsearch/commit/92af92ab97de454cf5141506fea07bd8f2c4edee (5.x) and https://github.com/elastic/elasticsearch/commit/8758c541b35bda1a6494ba703b450517027d5e9f (master).
