### ISSUE TITLE
Shard allocation by disk

### ISSUE THREAD

**Issue by eirc** [elastic/elasticsearch#24181]
**Describe the feature**: Ability to separately configure shard allocation by disk on same node.

What I'd like to achieve is to route some shards to spinning disks and some to SSDs. Currently this can be achieved by routing shards on the node level and having full nodes with only one type of disk or the other.

Is this restriction necessary? Could the API and backend provide the functionality of specifically routing some shards to one disk on the node and some to another on the same node?

**Comment by jasontedor** [comment]
You can do this per index by setting `path.shared_data` and then using the index setting `index.data_path`. Per shard does not make much sense (yes, with custom routing it could but we are still not going to go down that path of more complexity).

**Comment by eirc** [comment]
Wow thanks hadn't realized that! Sorry for the useless issue then :)

**Comment by jasontedor** [comment]
You're welcome. I think it's not useless, it will help future passerbys from search engines looking for the same as this is not well-known functionality. We do need to rename the setting `path.shared_data`, it is poor with its legacy being in shadow replicas which are deprecated in the 5.x series and have been removed for 6.0.0.

**Comment by eirc** [comment]
Yea I was just reading the deprecated shadow replicas documentation. As I understand it these settings were added to enable that feature but after it's removal the settings will stay and will be be able to be used for other usages such as mine?

**Comment by jasontedor** [comment]
> As I understand it these settings were added to enable that feature but after it's removal the settings will stay and will be be able to be used for other usages such as mine?

That's our intention, yes.
