### ISSUE TITLE
jvm.dll not found - when running elasticsearch on Windows

### ISSUE THREAD

**Issue by hemant-elastic** [elastic/elasticsearch#24196]
**Elasticsearch version**: 5.3.0

**Plugins installed**: []

**JVM version**: 1.8.131 (JRE)

**OS version**: Windows 7

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. NO JAVA_HOME set. 
 2.Public JRE is in the PATH
 3. Run elasticsearch.bat

**Provide logs (if relevant)**:
C:\ESearch\CoreDeveloper>elasticsearch\bin\elasticsearch
Error: missing `server' JVM at `C:\Program Files (x86)\Java\jre1.8.0_60\bin\server\jvm.dll'.
Please install or use the JRE or JDK that contains these missing components.

**Comment by jasontedor** [comment]
It looks like you only have the client JVM installed, you need the server VM (or remove the `-server` flag from the JVM options).

Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to any follow-up questions that you have. As such, I hope you don't mind that I close this.

**Comment by hemant-elastic** [comment]
Not at all. Sorry about the wrong place of putting it.

**Comment by jasontedor** [comment]
You're welcome.
