### ISSUE TITLE
sort on value in nested_path and nested filter fails to sort on bool filter with must  

### ISSUE THREAD

**Issue by ajays1991** [elastic/elasticsearch#24194]
Hi,

I would like to learn more  about the following nested_filter support for sort for sort using  nested_path to give higher value for sort with documents having nested document that  should match to bool filter.

**Query with bool filter**
```
{
	"sort": [{
		"m_Companies.value": {
			"order": "asc",
			"nested_path": "m_Companies",
			"nested_filter": {
					"bool": {
						"must": [{
								"term": {
									"topics.id": {
										"value": "13"
									}
								}
							},
							{
								"term": {
									"topics.id": {
										"value": "14"
									}
								}
							}
						]
					}
			}
		}
	}]
}

```

**Expected Response**
```

{
	"hists": [{
			"topics": [{
					"type": "Tools",
					"name": "Data Science",
					"id": 13
				},
				{
					"type": "Challenges",
					"name": "Disaster Resilience",
					"id": 14
				}
			]
		},
		{
			"topics": [

				{
					"type": "Challenges",
					"name": "Prosperity",
					"id": 13
				}
			]

		}
	]
}
```
My observations is that i tired following query i get the exception `parsing_exceptions` with this message `no [query] registered for [query]
`
This points me that nested_filter is query so a bool filter should work, as the term query works well as in the the next query assuming i am not getting exception on bool inside nested_filter. So i really mean to understand this or help me with this.

```
{
	"sort": [{
		"m_Companies.value": {
			"order": "asc",
			"nested_path": "m_Companies",
			"nested_filter": {
				"query": {
					"bool": {
						"must": [{
								"term": {
									"topics.id": {
										"value": "13"
									}
								}
							},
							{
								"term": {
									"topics.id": {
										"value": "14"
									}
								}
							}
						]
					}
				}
			}
		}
	}]
}

```
**Exception**

```
{
	"type": "parsing_exception",
	"reason": "no [query] registered for [query]",
	"line": 27,
	"col": 20
}

```

[Here](http://stackoverflow.com/questions/43477813/nested-sort-by-multiple-values-on-elasticsearch?noredirect=1#comment74012497_43477813) is  the stack post for this.

Thanks in Advance

**Comment by markharwood** [comment]
"How do I ?" type questions are best handled on the [discuss forum](https://discuss.elastic.co/c/elasticsearch). In your case it looks like the nested filter does not echo the path defined in the nested path as in the [example docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/search-request-sort.html#nested-sorting). Either way, create a new topic on the discuss forum to explore this question further before creating an issue here.
We use the github issues for tracking confirmed bugs or handling enhancement requests.
