### ISSUE TITLE
[how to] setup high availability env with elasticsearch cluster

### ISSUE THREAD

**Issue by Newbie111985** [elastic/elasticsearch#24201]
**Elasticsearch version**: 5.1.2

**Plugins installed**: [None]

**JVM version**: jdk 1.8

**OS version**: OEL 6 64-bit

**Description of the problem including expected versus actual behavior**:
This is not a bug report. I want to setup an elasticsearch cluster consisting of 3 nodes. Each node is master eligible and can contain the data. I also need to achieve high availability with this elastic search cluster. Hence would like to know which load balancer should be used and what are the configurations required?

Thanks in advance.

**Comment by olcbean** [comment]
This space is reserved for issues and feature requests.

For general support and help resolving issues, please post on the [discussion forum](https://discuss.elastic.co/c/elasticsearch).

**Comment by Newbie111985** [comment]
Thanks for the inputs. I am closing this issue.

**Comment by jasontedor** [comment]
@olcbean We sincerely appreciate your contributions here but comments like the one that you make above are probably best left for maintainers.

**Comment by olcbean** [comment]
@jasontedor 
My bad, did not mean to overstep.
