### ISSUE TITLE
TESTING.asciidoc say gradle assemble doesn't run tests - which isn't true

### ISSUE THREAD

**Issue by larsf** [elastic/elasticsearch#24218]
**Elasticsearch version**: 5.3

**Plugins installed**: []

**JVM version**: 1.8

**OS version**: centos 7.2

**Description of the problem including expected versus actual behavior**:
The TESTING.asciidoc says gradle assemble does not run any tests, but the output from gradle clearly shows that it does:
....
08:43:53 :core:namingConventions
08:44:04 :core:thirdPartyAudit
08:44:04 :core:precommit
08:44:04 :test:framework:copyCheckstyleConf
08:44:07 :test:framework:checkstyleMain
....
08:44:14 :test:framework:namingConventions
08:44:30 :test:framework:thirdPartyAudit
08:44:30 :test:framework:precommit
08:44:31 :test:framework:test
08:44:31 ==> Test Info: seed=2A6D5190ACA8FF1E; jvms=4; suites=23
08:44:33 Suite: org.elasticsearch.transport.MockTcpTransportTests
08:44:33 ERROR   0.00s J2 | MockTcpTransportTests (suite) <<< FAILURES!
08:44:33    > Throwable #1: java.lang.RuntimeException: can not run elasticsearch as root
**Steps to reproduce**:
 1. gradle assemble
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:
Please include a paragraph as to what you need to do to prevent gradle assemble from running tests. Adding -x :test:framework:test or -x buildSrc:test did not alter behaviour of gradle assemble

**Comment by jasontedor** [comment]
@larsf I think that something is not right here, this does not reproduce for me, and you can see that none of the test tasks are output via a dry run:

```
12:19:55 [jason@totoro:~/src/elastic/elasticsearch-5.x] 5.3 ± gradle --dry-run assemble | grep framework
:test:framework:generatePomFileForNebulaPublication SKIPPED
:test:framework:compileJava SKIPPED
:test:framework:processResources SKIPPED
:test:framework:classes SKIPPED
:test:framework:jar SKIPPED
:test:framework:javadoc SKIPPED
:test:framework:javadocJar SKIPPED
:test:framework:sourcesJar SKIPPED
:test:framework:assemble SKIPPED
```

Are you sure that you're executing the assemble task or are not in some other way triggering tests?

**Comment by larsf** [comment]
Sorry - amazing what our brains get stuck on. There was "gradle build" in the script I was using 10 lines higher than the gradle assemble I put in to build it - closing the issue

**Comment by jasontedor** [comment]
> Sorry - amazing what our brains get stuck on.

Wetware indeed! No worries at all.
