### ISSUE TITLE
rollover `max_docs` uses doc count from both primary and replica/s

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch#24217]
**Elasticsearch version**: 5.3.0

The rollover `max_docs` value uses the doc count from both primary and replica/s.  It should be based upon the primary only, since the replica count can be changed.

(start two nodes, to allow the default 1 replica to allocate)
```
PUT /logs-000001 
{
  "aliases": {
    "logs_write": {}
  }
}
PUT logs_write/test/1
{
  "blah": "foo"
}
POST /logs_write/_rollover?dry_run
{
  "conditions": {
    "max_docs":  2
  }
}
# response
{
  "old_index": "logs-000001",
  "new_index": "logs-000002",
  "rolled_over": false,
  "dry_run": true,
  "acknowledged": false,
  "shards_acknowledged": false,
  "conditions": {
    "[max_docs: 2]": true
  }
}
```
change the replica count to 0:
```
PUT /logs-000001/_settings
{
  "index": {
    "number_of_replicas": 0
  }
}
# response
{
  "old_index": "logs-000001",
  "new_index": "logs-000002",
  "rolled_over": false,
  "dry_run": true,
  "acknowledged": false,
  "shards_acknowledged": false,
  "conditions": {
    "[max_docs: 2]": false
  }
}
```

**Comment by eticzon** [comment]
Hi @jpcarey, @clintongormley! I'd like to adopt this issue, if that's OK.

**Comment by clintongormley** [comment]
@eticzon great

Thanks for showing interest in contributing to Elasticsearch.

Here's a guide to how to go about it: https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md

**Comment by julemik** [comment]
Apprciate it eticzon. I too am experiencing the issue. Doubled my max_docs for temporary solution.

**Comment by fred84** [comment]
@eticzon would you mind if I will handle this issue? 

@jpcarey @clintongormley I we managed to fix it (https://github.com/fred84/elasticsearch/commit/0dc2ec3ec86728bebaa136f2e951cdf93ed0a00d) with rollover integration test successfully passing, but currently struggling with passing full "gradle check"
