### ISSUE TITLE
[feature request]hash index in lucene layer

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#24211]
it's really a lucene issue. 
**Describe the feature**:
let's say I build a image search engine with ES and all I care about is point-query latency based on image feature.
I dont' want term index and I want term dictionary to be constructed as a hashmap which can be load into memory.

**Comment by markharwood** [comment]
>it's really a lucene issue.

Here's where to raise Lucene issues: https://issues.apache.org/jira/browse/LUCENE
