### ISSUE TITLE
[docs request]Bool Query should document ADJUST_PURE_NEGATIVE_DEFAULT 

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#24229]
doc usage of parameter: ADJUST_PURE_NEGATIVE_DEFAULT

**Comment by markharwood** [comment]
Personally this parameter and its default setting feels like a "just do the right thing" choice.
It does what you normally need to do to make Lucene Boolean queries work with only negative clauses.

I'm struggling to conceive of a scenario where the user would want to override this default. Can you supply an example as it would be a useful explanation to go along with the documentation? If we haven't got a use case I'm not sure it makes sense to document it.

**Comment by clintongormley** [comment]
> I'm struggling to conceive of a scenario where the user would want to override this default. 

Agreed

**Comment by makeyang** [comment]
it's just the first time when I saw this new boolean query and it turned out to be different with the previous. so I checked this parameter and learn what it means.
so I guss someone else would wonder to know about it and thus better to document it.
