### ISSUE TITLE
Static code analysis shows a whole bunch of performance/memory optimization possibilities, would this be appreciated.

### ISSUE THREAD

**Issue by KoenDG** [elastic/elasticsearch#24226]
I asked on the IRC what the best way to approach this is, and "just post an issue and ask" was it. So here goes. I was told there will be no biting :P

I forked the project, had Intellij do its static code analysis on it and it had a whole bunch of results under the performance/memory issue categories. These are small and relatively bigger things, depending on the situation.

These are things like: using the `keySet()` of a Map to loop over it, which is very inefficient since every single `.get()` you do will force the JVM to create a new Iterator internally to loop over the map again and go get the value. Looping via the `entrySet()` avoids this.

Things like not using an EnumMap when the key of a Map is an Enum. EnumMap is specifically made for this scenario and uses a primitive array internally, making it a lot smaller in memory and faster in all cases, compared to all other Map implementations.

And a lot more, too much to list here. And that's just the performance/memory stuff.

Now, ElasticSearch is a gigantic project and the resources on who can help where are understandably constrained. So I'm offering to contribute in this manner. It's my way of browsing the code and learning how it works, while at the same time I can contribute some things.

Would this be appreciated/wanted/accepted? Perhaps it could be something in that "projects" tab where the smaller things are stated to go. General cleanup and code optimizations.

Just to give an idea, analyzing just the `core` folder of the source code took Intellij about 4 and a half hours to complete on a 3.4GHz desktop CPU, 4 cores 8 threads. On a limited scanning profile. About half the options were turned off.

Thanks for your time reading this, I hope I can help out in this way.

**Comment by jprante** [comment]
A first step could be to share your findings, by posting it somewhere. 

Because I'm also interested in any hints from "code quality measures", I could also try to run Sonarqube / Findbugs over the code base.

**Comment by KoenDG** [comment]
I'll have the test suite run again overnight and then post it again after I get back from work. I'm from Belgium so I'm in a GMT+1 timezone.

I don't have a personal blog, never felt the need. Also, posting it here first felt like the right way of going about it.

Now, we're talking thousands of notifications and it is advised to look at them individually because the analyzer looks for general patterns that are considered bad **most of the time**.

For instance, have a look at this: [https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/admin/indices/get/GetIndexRequest.java#L113](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/action/admin/indices/get/GetIndexRequest.java#L113)

Intellij reports this as using `==` to compare 2 arrays, instead of `Arrays.equals()`. Sounds like a good thing to point out, right?

But if you look at the code around this point, you'll find that it was set up like this on purpose. As long as nobody pushes a new array of Feature enums to this point in the code, the if statement will always be true. Since the object was set to be the same on lines 99 and 100, `==` is guaranteed to return `true`. Sure, you could do `Arrays.equals`, but that would be slower. Even when the array is no longer the same, `Arrays.equals` is not needed to prove this, simply assessing that the array isn't the same as the static one defined at class level is enough. Even in the case where someone manages to push an array with the exact same content, as the original, having `==` compare it would probably still be faster than `Arrays.equals`.

How much faster? Nanoseconds? Either way, no need to go and make it slower by adding the "correct" way, at this point.

Suggestions by static analysis tools should not be blindly accepted.

I've already pushed a small piece of what was found: [https://github.com/elastic/elasticsearch/compare/master...KoenDG:staticanalysis](https://github.com/elastic/elasticsearch/compare/master...KoenDG:staticanalysis)

But any PR I push on this subject will be smaller and focussed on 1 or 2 categories. Has to stay simple to review. Better lots of small PRs than 1 big that nobody can read.


Last point: I'd also like to point out Google's "Error Prone" compiler: [https://github.com/google/error-prone](https://github.com/google/error-prone)

The installation page shows there is a gradle plugin: [http://errorprone.info/docs/installation](http://errorprone.info/docs/installation)

**Comment by KoenDG** [comment]
This is the result for the `core` folder: http://i.imgur.com/GvDaLQa.png

**Comment by jasontedor** [comment]
My recommendation would be to target the top N most impactful changes (I don't know what N is), rather than submitting micro-optimizations that might not matter, might harm readability, and take time to process.

**Comment by KoenDG** [comment]
@jasontedor I have struggled with this in the past and most of the time found that going for "top-X most important" can create a lot of unpleasant discussion as to what is actually most important. As such, I avoid it entirely. If something is an optimization that has no possible negative side effects, I will present it. I can make the PR's somewhat bigger, say 3-4 subjects per PR. And if a maintainer would like something looked at before anything else, I'd certainly be up for that.

Readability is, of course, paramount. I experience this myself in my own work. If a person has limited time to work on something, all the time spent reading and trying to understand is time taken away from writing. All cases where readability is impaired should be fixed/not merged. It is, for me, the most important aspect of coding.

As such, I feel that what we intend the code to do, should be readable in the code, rather than assuming the compiler will optimize our constructs for us.

In my personal projects, I make very liberal use of the `final` keyword. This is not, as is the trend to accuse, for performance reasons. The compiler is perfectly capable of detecting that a variable will receive no further assignment in the code. No, this is to make it clear when I come back half a year later that a variable will not be assigned to again after it was declared. Or that a class cannot be subclassed.

As for micro-optimizations: many small make one great. It's true that the PRs I made so far are tiny, but this is on purpose. Readability is key, as I already stated. By making it so small, the point is immediately obvious(that's the intention anyway) and the code very readable. One could then say "Only this? It's so little and so minute in effect, will it actually matter"? And they'd be right if I were to stop there. But I'm not planning to.

If I'm going to go over the analyses that Intellij, findbugs and google's error-prone have to offer, I might as well go over them all.

That being said, if anyone actually has a list of things they want to be looked at first in terms of memory/performance optimizations, I'm all ears.

**Comment by jasontedor** [comment]
> I have struggled with this in the past and most of the time found that going for "top-X most important" can create a lot of unpleasant discussion as to what is actually most important.

I think it's fine, just use your best judgment. We can error correct if needed.

> I can make the PR's somewhat bigger, say 3-4 subjects per PR.

I would prefer that we not do this, I think there were three different changes in #24321 and it would be best to limit it to one.

I think we are on the same page regarding readability.

**Comment by jasontedor** [comment]
I'm going to close this issue as there's no-defined end goal for a clean up like this so there's nothing to track per se (although it's good to keep linking PRs here).

**Comment by jasontedor** [comment]
> micro-optimizations that might not matter, might harm readability, and take time to process

Having seen several of these now I think that are better ways to be spending our review/testing time than on these PRs, I do not think these are worth the cost.

**Comment by KoenDG** [comment]
The project has more to do than this, perfectly understandable.

**Comment by s1monw** [comment]
@KoenDG thanks for the empathy!

**Comment by KoenDG** [comment]
@s1monw No worries, this has always been a "I have time to spare, lets run a code analysis" thing for me. There shouldn't ever be a point where I'm actually taking time away from the developers from working on new features and such.

**Comment by jasontedor** [comment]
Thank you for understanding @KoenDG.
