### ISSUE TITLE
"POST’ing Search Template as REST API causes Elastic to fail on start"

### ISSUE THREAD

**Issue by majunzhe** [elastic/elasticsearch#24227]
> I POST an search template using REST API, and it works as excepted.
> But when I restart the es after  registering the template, it throws an exception.
Origin question [Link](https://discuss.elastic.co/t/posting-search-template-as-rest-api-causes-elastic-to-fail-on-start/82552)  https://discuss.elastic.co/t/posting-search-template-as-rest-api-causes-elastic-to-fail-on-start/82552

I am also getting the same exception.

**Comment by jasontedor** [comment]
I think there's indeed a real issue here starting in 5.3.0, maybe related to #22206?
