### ISSUE TITLE
[feature request]provide a unique key search in query DSL

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#24235]
**Describe the feature**:
1. based on below talk:https://lists.gt.net/lucene/java-user/349926
if es can provide this DSL

**Comment by jpountz** [comment]
The GET and index APIs already work this way.

**Comment by makeyang** [comment]
the primary key is not the doc id. actually it's much a unique key to be straightforward

**Comment by jpountz** [comment]
This behaviour cannot be implemented at the query level. Because of updates, the same value could still occur multiple times in an index, it is just that at most one of them would not be deleted. However queries do not care about deleted documents, they return all matches regardless of whether they are deleted or not and then deleted docs are applied on top. So there isn't really a way to do this.

The discussion mentions collectors, which is the right way to do this, but this would only work if you run a PK query on its own, it could not be combined with any other query. So I don't think this optimization would be used a lot in practice, which makes it quite useless?

**Comment by makeyang** [comment]
below is the code in method: loadDocIdAndVersion of VersionsAndSeqNoResolver class:
for (int i = leaves.size() - 1; i >= 0; i--) {
            LeafReaderContext context = leaves.get(i);
            LeafReader leaf = context.reader();
            PerThreadIDVersionAndSeqNoLookup lookup = getLookupState(leaf);
            DocIdAndVersion result = lookup.lookupVersion(term.bytes(), leaf.getLiveDocs(), context);
            if (result != null) {
                return result;
            }
        }
it seems it used the way I thought since the doc with id 1 will be update too.
what's the difference?

**Comment by jpountz** [comment]
The difference is that `lookup.lookupVersion` checks the live docs while queries are not allowed to. I'm wondering what kind of query you are running to expect speedups from the kind of optimization. I'm afraid the gains that such an optimization would have would be drowned into the overhead that query execution brings in general like the retrieval of statistics, interaction with the cache or creation of index inputs.

**Comment by makeyang** [comment]
https://lists.gt.net/lucene/java-user/350168
actually there are some scenario that really focus on primary key search and therefore can afford to sacrifice other scenario such as agg/index etc.
so I wonder if u guys can support this hash index in lucene.

**Comment by jpountz** [comment]
Can you explain more in details why you cannot use your PK as a document id?

**Comment by makeyang** [comment]
let me give a example: my data is user info which is put ES for search. and the same data is in database.
this user info has user id which is generate in database and this user info also has ssn, which is unique for sure.
we need both these fields search for certain secnario.
so yeah, I can have pk, but at most I can only have one pk and left the other one to do unique key search.

**Comment by jpountz** [comment]
OK I see. Would it be an option to use the `ssn` as an id and store the database id as a regular field then (assuming your performance requirements are on `ssn` lookups).

More generally I think we would need more evidence that there are needs for unique keys before we start implementing this feature as it is not a simple change.
