### ISSUE TITLE
Clear scroll API should support single scroll ID

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#24233]
The [clear scroll API](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/search-request-scroll.html#_clear_scroll_api)  currently expects an array of scroll IDs when passed in the body.

The following fails with "Unknown parameter [scroll_id] in request body or parameter is of the wrong type[VALUE_STRING]":

```
DELETE _search/scroll
{
  "scroll_id": "DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAB1FnB1WUlJMEkxUnJlUlc5UmxvWjVaRXcAAAAAAAAAdhZwdVlJSTBJMVJyZVJXOVJsb1o1WkV3AAAAAAAAAHcWcHVZSUkwSTFScmVSVzlSbG9aNVpFdwAAAAAAAAB4FnB1WUlJMEkxUnJlUlc5UmxvWjVaRXcAAAAAAAAAeRZwdVlJSTBJMVJyZVJXOVJsb1o1WkV3"
}
```

We should also accept a single string value.

**Comment by glefloch** [comment]
Hi, can I work on this issue?
