### ISSUE TITLE
Score in Different Shards are not Compatible 

### ISSUE THREAD

**Issue by nbqyqx** [elastic/elasticsearch#24232]
**Elasticsearch version**:
2.3.3 BM25 Similarity
**Plugins installed**: []

**JVM version**:
open jdk 1.8
**OS version**:
mac os
**Description of the problem including expected versus actual behavior**:
Score in different shards are not Compatible. For the same query ```"match" : {  "building_house_type_name" : "test" }``` we may need get the same IDF for the different shards. So that the doc score in different shards are compatible.
The cause of irrelevant IDFs is the docFreqs are different.

**Steps to reproduce**:
 1.Query==> "match" : {  "building_house_type_name" : "test" }
 2.
 3.

**Provide logs (if relevant)**:
```json
  {
"_shard": 0,
...
"_explanation": {
"value": 0.41010404,
...
"description": "weight(building_house_type_name:test in 12130) [PerFieldSimilarity], result of:",
...
"value": 4.553907,
"description": "idf(docFreq=175, maxDocs=16672)",

```
```json
{
"_shard": 2,
...
"_explanation": {
...
"description": "weight(building_house_type_name:test in 1) [PerFieldSimilarity], result of:",
...
"value": 4.454347,
"description": "idf(docFreq=199, maxDocs=17156)",

  {...}

```

**Describe the feature**:
If it is possible to collect all metadata of document in the master node and compute the score then sort the doc? So that the docs in different shards are compatible.

Neal

**Comment by markharwood** [comment]
>If it is possible to collect all metadata of document in the master node and compute the score then sort the doc?

[Yes](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-type.html#dfs-query-then-fetch) :)
