### ISSUE TITLE
Should we remove histogram extended bounds

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#24244]
Extended bounds are tricky and can perform in unexpected ways when combined with other features (such as offset, see [1]). The original use-case for adding this was for taking the verbatim output of aggregations and feeding it into a charting library, but these days charting libraries need the data transformed anyway giving an opportunity to deal with extending the bounds and also have lots of options for extending the axes further than the data. Further the empty buckets returned by extended_bounds do not have friendly values for most of the metric aggregations (e.g. max/min/avg return null in their JSON output for empty buckets) requiring transformation of the returned buckets anyway.

Because of this should we consider removing the extended bounds option in the histogram aggregation to simplify the code and stop the tricky, non-intuitive behaviour with other features like the referenced issue above?

[1] https://github.com/elastic/elasticsearch/issues/24064

**Comment by clintongormley** [comment]
Ping @spalger

**Comment by uboness** [comment]
I'm really on the fence here... this was quite a highly requested feature when we had facets and it was one of the reasons we added it to aggs. I don't think much has changed since then wrt how users use the data (either directly or to plot it using a charting lib). Also, from a pure feature/functional perspective I think it's a valid ask to compute a history for a given timeframe. In most cases, you do need the extended bounds and by removing it we'll basically force everyone to do more munging on the data and keep state between requests and responses.

**Comment by spalger** [comment]
Kibana absolutely could take more control of this client side, but I'm pretty sure that moving away from extended_bounds client side won't be a trivial change.

 - Kibana no longer exposes an option to run date_histograms with extended bounds
 - date_histograms on older visualizations will continue to request it (bwc)
 - extended bounds options is available for numeric histograms
 - Timelion requests it in all of it's date histogram requests

**Comment by clintongormley** [comment]
I would guess that most graph libraries don't need extended bounds as they're only interested in the points with data, but one reason for using extended bounds is that the labels for each bucket would be produced by ES, rather than having to be generated by the graph library.

**Comment by uboness** [comment]
> I would guess that most graph libraries don't need extended bounds as they're only interested in the points with data, but one reason for using extended bounds is that the labels for each bucket would be produced by ES, rather than having to be generated by the graph library.

yes.. the labels is another thing... but for me it's less about the need of the graph libs, but more about the needs of the user. Specially what time based data (date histo), most of the time you want to at least start with relative time to "now"... if the data that is returned is older and you only get that, that is always confusing. For this reason, with date histo I think most of the time you'd want to use the extended bounds

**Comment by matAtWork** [comment]
Unless there is a very good reason for removing 'extended_bounds', don't do it. There are a huge number of assumptions above about what people are doing with data (charting? is that it?), and to remove an inexpensive feature then forcing all consumers to re-implement it is simply an unnecessary burden on users. 

The only possible reason you would consider removing a well-tried and tested feature (in any software) would be if it had an unreasonably high performance penalty, was already severely broken, or severely constrained the performance of a highly desirable new feature.

**Comment by colings86** [comment]
Closing this for now as we have no concrete plans to remove extended_bounds and it seems that lots of people use this feature. This can be reopened or a new issue can be created if we want to discuss this again
