### ISSUE TITLE
Add ingest parallel processor

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#24248]
Today all processors within a pipeline are executed in a sequential order which means that you need to wait for the result of processor 1 before running processor 2.

Which is very good when a processor depends from the previous one.
But in some cases, you would just like it to be as fast as possible and as you don't have dependencies between some processors, you would like to execute it in parallel.

I can imagine something along those lines:

The sequential way:

```
PUT _ingest/pipeline/test
{
  "processors": [
    { "grok": { } },
    { "geoip": { } },
    { "useragent": { } },
    { "date": { } },
    { "remove": { } }
  ]
}
```

With a parallel processor:

```
PUT _ingest/pipeline/test
{
  "processors": [
    { "grok": { } },
    { "parallel": [
        { "geoip": { } },
        { "useragent": { } },
        { "date": { } }
    ] },
    { "remove": { } }
  ]
}
```

Which means in that case that `grok` is executed first, then `geoip`, `useragent` and `date` processors would be executed in parallel. Then `remove` processor will have to wait for the result.

**Comment by rjernst** [comment]
I don't think we should complicate ingest with multiple threads. Right now ingest operates in either the index or bulk threadpool. I would not want to consume additional threads there which should be dedicated to processing parallel index/bulk/ingest requests.

**Comment by martijnvg** [comment]
I agree with Ryan that we should not do this. This would make the ingest infrastructure too complex.

On top of this parallelism with ingest and indexing in general is achieved by concurrent index/bulk requests.

**Comment by clintongormley** [comment]
> On top of this parallelism with ingest and indexing in general is achieved by concurrent index/bulk requests.
+1
