### ISSUE TITLE
_uid field doesn't support regexes

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#24247]
I'm opening this discuss issue in response to a forum [post](https://discuss.elastic.co/t/regex-over--uid-field/83222).

It looks like you used to be able to run a regex query on `_uid` but you can't anymore. Do we want to allow it again?

**Comment by bleskes** [comment]
> So I don't think we should allow this again.

+1 . If people really need this they can also have an id field or use scripted queries (in combination with something else to reduce scope)

**Comment by nik9000** [comment]
Makes sense to me.
