### ISSUE TITLE
query with must_not:exists:field returns incorect result when value is greater then ignore_above

### ISSUE THREAD

**Issue by igbelousov** [elastic/elasticsearch#24256]
**Elasticsearch version**: 5.3.0

**Plugins installed**: [xpack]

**JVM version**: 8

**OS version**: centos 6

**Description of the problem including expected versus actual behavior**:
Filtering documents with missing particular field is not working,
 when value of that field is crossing boundary of ignore_above

**Steps to reproduce**:
1. create index with 3 keyword fields having ignore_above=10

```javascript
DELETE ids28
PUT ids28
{
  "mappings": {
    "library": {
      "_all": {
        "enabled": false
      },
      "properties": {
        "book": {
          "properties": {
            "author": {
              "type": "keyword",
               "ignore_above": 10              
            },
            "title": {
              "type": "keyword",
               "ignore_above": 10
            }
          }
        }
      }
    }
  }
}
```

2. insert document that have big and small title 

```javascript
POST ids28/library
{
  "book.author":  "Mark Twain",
  "book.title": "The Adventures of Tom Sawyer"
}

POST ids28/library
{
  "book.author":  "Walter Scott",
  "book.title": "Ivanhoe"
}

```

3. query every document that does not have book.title, but author is "Mark Twain"

```javascript
GET ids28/library/_search
{
  "query": {
    "constant_score": {
      "filter": {
        "bool": {
          "must_not": {
            "exists": {
              "field": "book.title"
            }
          },
          "must": 
            {
              "term": {
                "book.author": "Mark Twain"
              }
            }        
        }
      }
    }
  }
}
```

expect: no documents should be returned
actual:  a long titled document got returned 

```javascript
{
  "took": 3,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "ids28",
        "_type": "library",
        "_id": "AVuRyyvgpdc_6vQX8rs0",
        "_score": 1,
        "_source": {
          "book.author": "Mark Twain",
          "book.title": "The Adventures of Tom Sawyer"
        }
      }
    ]
  }
}
```

**Comment by markharwood** [comment]
This behaviour is inconsistent with the analyzer-based forms of content filtering. 

* As is stated [in the docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/query-dsl-exists-query.html) - an analyzer that strips a field of all tokens will still match an `exists` clause.

* However the `ignore_above` form of length-filtering will _not_ match an oversized field - it considers an over-sized field the same as a null value ([offending line?](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/mapper/KeywordFieldMapper.java#L306))

**Comment by clintongormley** [comment]
`ignore_above` prevents any analysis of a long text field.  Perhaps using the [limit token count token filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-limit-token-count-tokenfilter.html) would be a better fit for text fields

**Comment by nik9000** [comment]
Discussed this morning with a group. We feel like the best thing to do is explicitly document the limitations of the exists query rather than change any behavior around `ignore_above` or `ignore_malformed`. The behavior we have makes a certain kind of sense and changing it wouldn't necessarily be better. Thus we take the path the breaks clients the least and just make the current behavior more clear.
