### ISSUE TITLE
Bool Query doc should state disable_coord has no effect when using default similarity

### ISSUE THREAD

**Issue by davidbkemp** [elastic/elasticsearch#24267]
**Elasticsearch version**: 5.3.0

**Plugins installed**: []

**JVM version**: N/A

**OS version**: N/A

**Describe the feature**:
The Bool Query documentation https://www.elastic.co/guide/en/elasticsearch/reference/5.3/query-dsl-bool-query.html
currently states "The bool query also supports disable_coord parameter"
It fails to mention that the disable_coord parameter has no effect unless the default "similarity" for the index has been modified to one for which the coord factor is applied: https://www.elastic.co/guide/en/elasticsearch/reference/5.3/index-modules-similarity.html#default-base

See also https://discuss.elastic.co/t/are-the-querynorm-and-coord-factors-no-longer-applied-to-bool-query-scoring/82962

**Comment by jpountz** [comment]
+1 I think it should actually state that the `disable_coord` parameter _only_ has an effect with the `classic` similarity.

**Comment by nik9000** [comment]
I merged #24348 to address this.
