### ISSUE TITLE
Unloadable indices feature

### ISSUE THREAD

**Issue by m31collision** [elastic/elasticsearch#24269]
Hello guys!

I want to propose you implementation for unloadable indices feature. This issue implements what has been requested and discussed in #10869, #23546.

I opened separate pull request (m31collision/elasticsearch#1) in forked repo, please, have a look. Of cource, it is not ready for pulling here and it is implemented for 2.3 version only because we use mainly this version on our prods. It is not used on prod yet, only tests.

It has durty code without tests, but I need to know - is it acceptable for you for further development? It seems to me this implementation has no shortcomings mentioned in those issues.

Thanks.

**Comment by clintongormley** [comment]
@m31collision i suggest opening a PR here and marking as WIP, otherwise nobody will see it

**Comment by m31collision** [comment]
@clintongormley created  #24357, lets try

**Comment by m31collision** [comment]
Of course PR has been closed because it is made for 2.3. I cant do patch for master because it changed a lot relative to 2.3 version. Any ideas?

**Comment by clintongormley** [comment]
@m31collision we're not going to merge anything but important bug fixes into 2.x, so the only way forward is to target master.

**Comment by clintongormley** [comment]
Also, you may want to outline your approach in this issue before submitting a huge PR

**Comment by m31collision** [comment]
> we're not going to merge anything but important bug fixes into 2.x,

yes, I know, but what did you mean by this:

> i suggest opening a PR here and marking as WIP

I said that currently I dont have patch for master. But I expected that you (developers) will do some analyze of my patch and give notes because I dont know this project well.

Well, it remains to me to do this patch for master.

**Comment by cbuescher** [comment]
I'm closing this for now since it looks like this is going to be opened as a PR again. Feel free to reopen or add an outline of your suggested approach here.
