### ISSUE TITLE
Add Fix for java.lang.NoClassDefFoundError: com/graphbuilder/curve/Point fatal error in 5.3

### ISSUE THREAD

**Issue by RkirkCBD** [elastic/elasticsearch#24273]
**Elasticsearch version**:5.3

**Plugins installed**: [ingest-attachment]

**JVM version**:8.0.121

**OS version**:

**Description of the problem including expected versus actual behavior**: java.lang.NoClassDefFoundError: com/graphbuilder/curve/Point fatal error is occurring in 5.3 release.  There was a patch, see #23214,  but it wasn't pushed to 5.3

**Comment by dadoonet** [comment]
Closed by dc4888e21c06eeccc2e6a27de4c6c82bd6a73958

Thanks for reporting and I'm very sorry it happened.
