### ISSUE TITLE
[feature request]make request cache more memory efficiency

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#24278]
**Describe the feature**:
nowadays when eable request cache, each node hold the request results by its own. 
so can we make it more memory efficiency by below ways:
1. if enable request cache, can we route request to node by request hash so that same request will route to same node, therefore, they can use/hit the same cache
2. we don't route request but at the time we fetch/put cache, we make a distributed cache based on curreny facilities.

**Comment by jpountz** [comment]
I agree setting the `preference` with each search request can help make better use of the request cache. There are also similar benefits with the query cache, as well as more consistent scoring if you make sure that a given user always goes to the same shard copies. I'm not totally sold on using the hash of the request as a default preference as I can imagine it would not be desirable all the time, however I'm +1 on better documenting `preference` and how it can help with the request cache.
