### ISSUE TITLE
InternalTestCluster can set SCRIPT_CACHE_SIZE_SETTING to 0 which breaks at least one test

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#24272]
`BulkWithUpdatesIT`, and maybe others, attempt to do a *bunch* of scripting operations. Enough that, if the cache is turned off, the script compilation limit will kick in and kill the test. You can reproduce this with `@Seed("1700EBAFCDE6C8B9")` on `BulkWithUpdatesIT`.

I don't know the right solution here. We could change it so the cache is never turned off 100%, but, unless we prevent that in configuration, someone is going to set up elasticsearch that way one day. And we should randomly test that.... So I think either we make 0 an invalid setting or we should update all the tests that fail when this is 0 to force it to something non-0.... Of course these are fairly difficult to debug.....

Here is a failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.3+multijob-unix-compatibility/137/os=centos/consoleFull

**Comment by danielmitterdorfer** [comment]
This was also discussed in #24308 and with 6d68e8a10c2d66467af88c4a130d3020a23d5673 the script compilation limit is bumped significantly to avoid such spurious failures so I think we can close this one due to 6d68e8a10c2d66467af88c4a130d3020a23d5673.
