### ISSUE TITLE
Elasticsearch Multivalue Fields The statistics contain the number of values

### ISSUE THREAD

**Issue by liuguangmin** [elastic/elasticsearch#24297]
hi team 
 I want to konw How to count the number of value in a multi-valued field in elasticsearch ?
for example field  A is multi-valued 
doc1 : A:[1,2,3],
doc2: A:[2,3]
doc3: A:[4,5]
doc4: A:[1,3],
doc5:A:[1]
 and so : doc1_countA = 3,
              doc2_countA = 2
              doc3_count = 2
              doc4_count = 2
              doc_count = 1
so how to count in elasticsearch ? have any plugs or Other methods?

I used Elasticsearch 5.3.0

**Comment by cbuescher** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general "How to" questions like this and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
