### ISSUE TITLE
[feature request] Is it necessary to add a quick recovery configuration item like "indices.recovery.fast"

### ISSUE THREAD

**Issue by johnyannj** [elastic/elasticsearch#24302]
when shard become very large,   restart one cluster will waste too much time, 

I know the primary shard become started is very fast.

but the cluster become green from yellow is very slow, become  replica shard need recovery：

Especially the first phase of recovery.

Sometimes we need fast recovery services, not too concerned about data consistency。

I recommend adding a configuration item: “indices.recovery.fast”， which can be dynamically modified。

Then we can skip first phase of recovery~~

org.elasticsearch.indices.recovery.RecoverySourceHandler
```
public void phase1(final SnapshotIndexCommit snapshot) throws ElasticsearchException{
......
//add one fast recovery  branch
 if (recoverySettings.fast() && !request.markAsRelocated()) {
                
......
                
            } else if (recoverWithSyncId) {
             
......
            } else {
......
}
```

**Comment by ywelsch** [comment]
Just skipping phase 1 would leave replicas in an inconsistent state. There are better solutions though:
[Synced flush](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-synced-flush.html) should give you instant recoveries if there is no write activity on the indices. For indices that continuously receive writes, Elasticsearch 6 will have fast replica recoveries that also guarantee data consistency (see https://github.com/elastic/elasticsearch/issues/10708).

**Comment by johnyannj** [comment]
hi, synced flush dont resolve problem.

first:  

when shard is too large, the document num is  often inconsistent. 
although the syncid is same but document num is different.  source node recovery will return error, and target node will remove local data and recovery whole shard from primary shard:

RecoverySourceHandler.java

 ```
          String recoverySourceSyncId = recoverySourceMetadata.getSyncId();
            String recoveryTargetSyncId = request.metadataSnapshot().getSyncId();
            final boolean recoverWithSyncId = recoverySourceSyncId != null &&
                    recoverySourceSyncId.equals(recoveryTargetSyncId);
            if (recoverWithSyncId) {
                final long numDocsTarget = request.metadataSnapshot().getNumDocs();
                final long numDocsSource = recoverySourceMetadata.getNumDocs();
                if (numDocsTarget != numDocsSource) {
                    throw new IllegalStateException("try to recover " + request.shardId() + " from primary shard with sync id but number " +
                            "of docs differ: " + numDocsSource + " (" + request.sourceNode().getName() + ", primary) vs " + numDocsTarget
                            + "(" + request.targetNode().getName() + ")");
                }
                // we shortcut recovery here because we have nothing to copy. but we must still start the engine on the target.
                // so we don't return here
                logger.trace("skipping [phase1]- identical sync id [{}] found on both source and target", recoverySourceSyncId);
} else {

Second:

When cluster fail for machine、network、power etc,  there is no chance for you to execute Synced Flush.








```

**Comment by ywelsch** [comment]
> when shard is too large, the document num is often inconsistent.

No, this has nothing to do with shard size. It should only happen in the scenario described [here (Section "Replicas can fall out of sync when a primary shard fails")](https://www.elastic.co/guide/en/elasticsearch/resiliency/master/index.html).
This will be properly fixed by the work mentioned above (#10708) in Elasticsearch 6 and should lead to very quick recovery times.

**Comment by johnyannj** [comment]
@ywelsch 

but when we synced flush and restart , we found many errors:

Caused by: java.lang.IllegalStateException: try to recover [xxxx][1196] from primary shard with sync id but number of docs differ: 66923216 (xxxxxx_9400, primary) vs 66923302(xxxxxx_9200)
    at org.elasticsearch.indices.recovery.RecoverySourceHandler.phase1(RecoverySourceHandler.java:176)
    ... 11 more

which lead to many replica shards be removed and re create again....

why?

**Comment by ywelsch** [comment]
> why?

Can you be more specific what you don't understand? I provided you the link to the explanation. Let me copy-paste the text here:

> When a primary shard fails, a replica shard will be promoted to be the primary shard. If there is more than one replica shard, it is possible for the remaining replicas to be out of sync with the new primary shard. This is caused by operations that were in-flight when the primary shard failed and may not have been processed on all replica shards. Currently, the discrepancies are not repaired on primary promotion but instead would be repaired if replica shards are relocated (e.g., from hot to cold nodes); this does mean that the length of time which replicas can be out of sync with the primary shard is unbounded. Sequence numbers #10708 will provide a mechanism for syncing the remaining replicas with the newly-promoted primary shard.

Part of the recovery is to repair discrepancies between primary and replicas. We won't allow a way to opt out of this behavior. ES 6 will provide fast recoveries when there are discrepancies between shard copies and also do the repair on primary promotion.

**Comment by johnyannj** [comment]
thank you for your patience.

from your help:

I now know the reason of the discrepancies between replica and primary shards。  we have 2 replica shards now.   sometimes disk error, we will stop and replace the node.  one replica shard will become primary shard. then discrepancies appear.

I also know part of the recovery is to repair discrepancies. and ES 6 will provide fast recoveries  base on Sequence numbers

is right?

**Comment by ywelsch** [comment]
correct 👍

**Comment by johnyannj** [comment]
Thank you again~

The last question：

I know the importance of repair discrepancies for recovery。but...
Since the cluster has discrepancies before restart，  Why do we have to fix it when we restart the whole cluster?   

can we  quick recoveries when restart the whole cluster.  after restart，we can modify it back?

I think taking many  hours to restart the whole cluster is a disaster for users。

and 

It will take a long time before ES6 releases

**Comment by jasontedor** [comment]
> Why do we have to fix it when we restart the whole cluster?

> can we quick recoveries when restart the whole cluster. after restart，we can modify it back?

A point of a replica is resiliency, if you lose the primary the replica is there as a valid copy of the acknowledged writes. If a discrepancy arises, it should be repaired as soon as possible to minimize the amount of time that a replica is not a valid copy thus increasing the overall resiliency of the system.

> I think taking many hours to restart the whole cluster is a disaster for users。

Every engineering decision involves tradeoffs. We think decreasing resiliency and increasing the risk of data loss is a worse disaster. As @ywelsch mentioned, we have fast replica recoveries in master today to ship with 6.0.0.

> It will take a long time before ES6 releases

Good things come to those who wait.

**Comment by johnyannj** [comment]
hi @jasontedor, Thank you~

Where can I get the roadmap for ES 6.0? 

ES 6.0 can be released this year?

**Comment by jasontedor** [comment]
> Where can I get the roadmap for ES 6.0?

We do not provide a roadmap yet you can track the PRs here on GitHub with the label [v6.0.0](https://github.com/elastic/elasticsearch/pulls?utf8=✓&q=label%3Av6.0.0%20). There is some taste of what's coming in the talk [What's evolving in Elasticsearch](https://www.elastic.co/elasticon/conf/2017/sf/what-is-evolving-in-elasticsearch).

> ES 6.0 can be released this year?

We do not provide release dates/estimates.
