### ISSUE TITLE
Continuous spaces become one blank space

### ISSUE THREAD

**Issue by lovewanli** [elastic/elasticsearch#24301]
When I put this in elasticsearch 5.3.1 and I get those,all Continuous spaces become one blank space,why this happen ?As a database this sure not happen.

please help me fix this.

{ 
  "filePath": "/cpic/dep       loy/Aladdin/main       /log/AllRece_20170413.log",
  "logText": "2017-04-20 08:00:45,468                                   kkk oooh          dddd               dddd                                     dd "
}

{
  "filePath": "/cpic/dep loy/Aladdin/main /log/AllRece_20170413.log",
  "logText": "2017-04-20 08:00:45,468 kkk oooh dddd dddd dd "
}

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
