### ISSUE TITLE
[TEST] Docs tests for reference/docs/delete/line_10 fails on 5.x

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#24303]
Build URL:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+java9-periodic/2260/console

Looks like some fields in the response are not present in 5.x (does not reproduce on master, have not tried earlier branches):
```
FAILURE 1.86s | DocsClientYamlTestSuiteIT.test {yaml=reference/docs/delete/line_10} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [reference/docs/delete:45]: $body didn't match the expected value:
   >                          $body:
   >                              _id: same [1]
   >                           _index: same [twitter]
   >                    _primary_term: expected [1] but not found
   >                          _seq_no: expected [5] but not found
   >                          _shards:
   >                             failed: same [0]
   >                         successful: same [1]
   >                              total: same [2]
   >                            _type: same [tweet]
   >                         _version: same [2]
   >                            found: same [true]
   >                           result: same [deleted]
   >    at __randomizedtesting.SeedInfo.seed([E5030163EFE87AD3:6D573EB94114172B]:0)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:345)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:325)
```

Reproduce command (reproduces consistently):
```
gradle :docs:integTestRunner -Dtests.seed=E5030163EFE87AD3 -Dtests.class=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT -Dtests.method="test {yaml=reference/docs/delete/line_10}" -Dtests.security.manager=true -Dtests.locale=lo-LA -Dtests.timezone=Canada/Newfoundland
```

**Comment by colings86** [comment]
@bleskes @jasontedor could one of you take a look

**Comment by colings86** [comment]
Oops, hadn't seen that @nik9000 is already looking at this

**Comment by colings86** [comment]
Test is now muted by https://github.com/elastic/elasticsearch/commit/f2e31cdeefc4e03f5202951643b1c6e746817d10

**Comment by jasontedor** [comment]
I think that the wrong branch was muted here (master) whereas this is failing on 5.x because `_primary_terms` and `_seq_no` are not part of the doc write response there. I pushed 2e9d91ecc4b0ef5a88ef257ca32070d32d47e305 to fix the broken test in 5.x, and I pushed f2e31cdeefc4e03f5202951643b1c6e746817d10 to revert the skip on master.

**Comment by jasontedor** [comment]
Closed by 2e9d91ecc4b0ef5a88ef257ca32070d32d47e305

**Comment by colings86** [comment]
@jasontedor thanks for catching that and fixing it

**Comment by nik9000** [comment]
Thanks! I thought I'd pushed a fix for this before bed but it looks like I didn't. I'm sorry!
