### ISSUE TITLE
how to _count mand by transportclient?

### ISSUE THREAD

**Issue by kervin521** [elastic/elasticsearch#24329]
eg.

request url : http://localhost:9200/testlog/_count
request body : 
{
	"query":{
    	"bool":{
        	"should":[{
            	"match":{
        			"operator":"abcd"
        		}},
                {"match":{
        			"content":"测试"
        		}}
                
        	]
        }
    	
    }
}

how to use java api by transportclient?

SearchResponse response = client.prepareSearch(indexs.split(","))
		        .setTypes(types.split(","))
		        .setSearchType(SearchType.DFS_QUERY_THEN_FETCH)
		        .setQuery(QueryBuilders.boolQuery())                 // Query
		        .setExplain(true)
		        .get();
Has it have Similar query methods like Java API?

**Comment by colings86** [comment]
Hi @kervin521,

Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
