### ISSUE TITLE
command:_shutdown is faill,why?

### ISSUE THREAD

**Issue by kervin521** [elastic/elasticsearch#24326]
request url : http://127.0.0.1:9200
result : 

{
  "name" : "l5m25Ck",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "PARuYsoBTjumNOwMJZNouA",
  "version" : {
    "number" : "5.3.1",
    "build_hash" : "5f9cf58",
    "build_date" : "2017-04-17T15:52:53.846Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.2"
  },
  "tagline" : "You Know, for Search"
}

**but exec _shutdown command do failed**

request url : http://127.0.0.1:9200/_shutdown
result : 

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"No endpoint or operation is available at [_shutdown]"}],"type":"illegal_argument_exception","reason":"No endpoint or operation is available at [_shutdown]"},"status":400}

**Comment by jasontedor** [comment]
The [shutdown API was removed](https://www.elastic.co/guide/en/elasticsearch/reference/5.3/cluster-nodes-shutdown.html).

In the future please note that Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to any questions that you have.
