### ISSUE TITLE
Percentiles Bucket Aggregation relies on ordered `percents` array

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#24331]
An interesting edge case that I found when working on #24330: It seems that `percentiles_bucket` relies on the `percents` parameter beeing specifies in increasing order or magnitude. If the list of percentiles to calculate is provided in a different order, e.g.
```
"percentiles_monthly_sales": {
            "percentiles_bucket": {
                "buckets_path": "sales_per_month>sales", 
                "percents": [ 50.0, 25.0, 75.0 ] 
            }
        }
```
the following error is thrown:
```
"type": "illegal_argument_exception",
    "reason": "Percent requested [50.0] was not one of the computed percentiles.  Available keys are: [50.0, 25.0, 75.0]"
```

The reason seems to be that in `InternalPercentileBucket#percentile(double percent)` (https://github.com/elastic/elasticsearch/blob/f217eb8ad8d3ecc82e2f926222b1f036b0d555b7/core/src/main/java/org/elasticsearch/search/aggregations/pipeline/bucketmetrics/percentile/InternalPercentilesBucket.java#L75) the internal array is assumed to be sorted, but we don't enforce this, e.g. in the PercentilesBucketPipelineAggregator or even before when parsing the request.

I think we could either throw an error early if we think the `percents` need to be provided in order, re-sort the array if the user provided it unsorted or change the implementation of `InternalPercentileBucket` so it doesn't rely on an ordered array.

**Comment by cbuescher** [comment]
@colings86 do you have any preferences whether we should throw an error here or should try to make InternalPercentileBucket work without relying on an ordered array?

**Comment by colings86** [comment]
I think we should not rely on the order of the array the user provides

**Comment by tlrx** [comment]
Good catch @cbuescher
