### ISSUE TITLE
Rename reindex and friend's `size` parameter to `max_docs`

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#24344]
Reindex's size parameter is ***very*** easy to confuse with batch size. We should rename it. Standard deprecate in some 5.x release and rename in 6.0 logic should apply here, I think.

**Comment by nik9000** [comment]
I've marked this adoptme because I'm not sure when I'll get to it. I'll keep it on my list but if someone else wants to start playing with reindex I'd be happy to provide moral support and reviews.

**Comment by glefloch** [comment]
Hi @nik9000, can I start working on it?

**Comment by nik9000** [comment]
@glefloch, sure! This is probably a two PR thing - one to add the new name and deprecate the old name that'll be applied to master and 5.x and a followup to remove the old name that is only applied to master.

Adding the new name is a thing you'd do in RestReindexAction and AbstractBulkByQueryRestHandler. At least, I'd start with those classes and dig from there.

**Comment by glefloch** [comment]
@nik9000, by deprecating the old name, you mean handling both settings and maybe add some logs if the old setting is still in use?

**Comment by nik9000** [comment]
> @nik9000, by deprecating the old name, you mean handling both settings and maybe add some logs if the old setting is still in use?

Right. We have lots of examples of code that does this. The change to RestReindexAction might be as simple as adding the new name to the ParseField definition and testing it. The change to AbstractBulkByQueryRestHandler is probably a bit more complex.

**Comment by glefloch** [comment]
@nik9000, After looking at the code, the first first modification is really easy. For `AbstractBulkByQueryRestHandler` class, the size is set from search request is that normal? 
Is there any modification to do in this class?

**Comment by nik9000** [comment]
The second modification is indeed a lot trickier because of reindex's reuse of the search APIs for parsing. I'd like to figure out a nicer way to reuse that one day, but it is low on my list. I'm not totally sure the right way to handle it. It might require that cleanup I've been putting off.

**Comment by dakrone** [comment]
@nik9000 it's been almost a year, is this something we're still considering?

**Comment by nik9000** [comment]
Maybe! It is certainly confusingly named as it stands. I think the twisty mess that is the request objects is probably more important to clean up, now that we want to use the request objects for the high level rest client.

**Comment by henningandersen** [comment]
@nik9000 would it make sense to align this more with `update_by_query` and `delete_by_query` by adding a `scroll_size` parameter for the batch size instead? If we are then to remove source/query.size, we should do so for all 3.
Or is there a history to why we did not do this originally?

**Comment by nik9000** [comment]
Yes, reindex's friends are `update_by_query` and `delete_by_query`. Whatever we do to one we should almost certainly do to all three.

We got where we are today because reindex and friends reuse most of the request parsing infrastructure for `_search`. At the time I didn't want to do major surgery to that request parsing infrastructure because I was new and scared.
