### ISSUE TITLE
[Feature Request] Search Before feature

### ISSUE THREAD

**Issue by joan38** [elastic/elasticsearch#24364]
Hi guys,
We quiet liked the [**Search After**](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-search-after.html) feature and we were wondering if it would be a big effort to do the **Search Before** feature?

Cheers

**Comment by clintongormley** [comment]
The way to do this is to use search after, but to sort in reverse order.

**Comment by joan38** [comment]
@clintongormley That's the way I'm trying to implement but it's super difficulte as I want to generalise that for many requests. And in this implementation I get the opaque SearchRequestBuilder.
Also the result is sorted in reverse order so I need to somehow reverse again the result once it comes back for ES and again it's almost impossible to encapsulate that in a module that manage Pagination

**Comment by apachunuri** [comment]
I have a sort by 3 different fields (as in the example below)
"sort":[
{"field1":"asc"},
{"field2":"desc"},
{"field3": "asc"}
]
Now what does it mean to sort this in the reverse order?
Clearly flipping the order for each field doesn't actually make it the right reverse order.
"sort":[
{"field1":"desc"},
{"field2":"asc"},
{"field3": "desc"}
]
is there a composite sort which basically takes the sort operations as one unit, so we can effectively do a forward or reverse sort. I am using the java high level rest client api (code below). Not sure how to associate sort builder as a single unit of all sorts included, so it’s possible to reverse?

    SortBuilder sortBuilder = new FieldSortBuilder("field1");
    sortBuilder.order(org.elasticsearch.search.sort.SortOrder.ASC);

    SortBuilder sortBuilder1 = new FieldSortBuilder("field2");
    sortBuilder1.order(org.elasticsearch.search.sort.SortOrder.ASC);

    SortBuilder sortBuilder2 = new FieldSortBuilder("field3");
    sortBuilder2.order(org.elasticsearch.search.sort.SortOrder.ASC);

    searchSourceBuilder.sort(sortBuilder);
    searchSourceBuilder.sort(sortBuilder1);
    searchSourceBuilder.sort(sortBuilder2);

**Comment by neerajrocks2k12** [comment]
@apachunuri Did you find answer to your query? I have similar usecase and seems no relevant post exists on this in elastic forum
