### ISSUE TITLE
[feature request]resource control 

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#24360]
**Describe the feature**:
1. bsaed on index to set req/time or size/time for READ/WRITE 

can take this as reference:
https://issues.apache.org/jira/browse/HBASE-11598

**Comment by danielmitterdorfer** [comment]
Hi @makeyang! Thank you for the feature request. Elasticsearch already has a couple of mechanisms to apply back-pressure. For example, we limit the [amount bytes in-flight](https://www.elastic.co/guide/en/elasticsearch/reference/current/circuit-breaker.html#in-flight-circuit-breaker), we have multiple other limits (maximum request size, maximum number of script compilations / minute, etc). We also apply backpressure by rejecting new tasks if the respective task queues are full. You can also configure queue lengths so I am not sure what the benefit of this ticket would be. Hence I am closing but feel free to reopen with further explanation if I misunderstood.
