### ISSUE TITLE
Curator: Add filter to remove indices by age when X % of the disk is full

### ISSUE THREAD

**Issue by jesseolsen** [elastic/elasticsearch#24370]
**Describe the feature**:

Curator: Add filter to remove indices by age when X % of the disk is full

Currently Curator5 supports removing indices when an individual index exceeds a given value in GB.
I would like to be able to have the curator remove indices, based on age, until the % disk used goes back down < X%.

**Comment by danielmitterdorfer** [comment]
Hi @jesseolsen! Thanks for the feature request but unfortunately this is the wrong repo. :) Can you please open the issue in the [Curator repo](https://github.com/elastic/curator) instead? Thank you!
