### ISSUE TITLE
action.destructive_requires_name: true shows error on DELETE *, but deletes anyways

### ISSUE THREAD

**Issue by pindarvanarman** [elastic/elasticsearch#24377]
**Elasticsearch version**:
5.1.1

**Plugins installed**: []
XPACK

**JVM version**:
1.8.0

**OS version**:
CENTOS 7

**Description of the problem including expected versus actual behavior**:

Configuration files show: 
    action.destructive_requires_name: true

However if DELETE * is used, all indices are deleted.  This happens despite an error saying the operation is illegal.

**Steps to reproduce**:

    Set action.destructive_requires_name: true 
    
Do:
    POST /asdf/asdf/1
    {
        "asdf"  : 3
    }

Using GET -cat/indices/as* will show you the indices.

Then if you us DELETE as* you will get the following error

    Error indicates acknowledgement of the feature
    {
       "error": {
          "root_cause": [
             {
                "type": "illegal_argument_exception",
                "reason": "Wildcard expressions or all indices are not allowed"
             }
          ],
          "type": "illegal_argument_exception",
          "reason": "Wildcard expressions or all indices are not allowed"
       },
       "status": 400
    }
    
That is expected behavior.  The problem is that if you check indices again with:

GET -cat/indices/as* 

You will notice the indices has been deleted.

Have seen other people reports this problem but still looking for how it was resolved.

Thanks,

**Comment by jaymode** [comment]
Please upgrade to 5.1.2 where this is fixed. I actually would recommend upgrading to 5.3.2 as there have been many other bug fixes as well since 5.1.1.
