### ISSUE TITLE
Run As Security Violation Issue

### ISSUE THREAD

**Issue by smudgekick** [elastic/elasticsearch#24378]
**Elasticsearch version**:  5.3.1

**Plugins installed**: [x-pack]

**JVM version**: 1.8

**OS version**: Mac OS 10.12.4 

**Description of the problem including expected versus actual behavior**: When making a request using the header: "es-security-runas-user" against a user who's role includes a template query using {{_user.username}}...  we would expect the value of the {{_user.username}} to reflect the run as user but it is reflecting the active user.

**Steps to reproduce**:

1. Create a role that uses a {{_user.username}} placeholder in a template as a document level security query.  

Example:
```
{
	"template": {
		"inline": {
			"match": {
				"acl": "{{_user.username}}"
			}
		}
	}
}
```
2.  Create 2 users both assigned to the role create above.  
3.  Add some documents with a field called "acl" as an array of usernames.
4.  Setup your data so that the active user should have some documents returned and the run as user should have different documents returned.
5.  Connect as one of the users, but query with the “run as” header set as the other user.
6.  This should show the documents for the run as user and not the active user.

However, that is not happening.

When we query using the superuser we get the full dataset as expected:
```
curl -u elastic -XGET 'http://localhost:9200/customer1/general/_search?pretty'
Enter host password for user 'elastic':
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "customer1",
        "_type" : "general",
        "_id" : "2",
        "_score" : 1.0,
        "_source" : {
          "foo" : "baz",
          "acl" : [
            "u1234",
            "billybadboy"
          ]
        }
      },
      {
        "_index" : "customer1",
        "_type" : "general",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "foo" : "bar",
          "acl" : [
            "u1234",
            "u4321"
          ]
        }
      }
    ]
  }
}
```

When we query using the user: u4321 we get 1 document as expected:
```
curl -u u4321 -XGET 'http://localhost:9200/customer1/general/_search?pretty' 
Enter host password for user 'u4321':
{
  "took" : 3,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "customer1",
        "_type" : "general",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "foo" : "bar",
          "acl" : [
            "u1234",
            "u4321"
          ]
        }
      }
    ]
  }
}
```
When we query using the user: billybadboy and "run-as" u4321 we get 1 document but u4321 is not on the acl.  The document that is returned is for billybadboy because he is in the acl:
```
curl -H "es-security-runas-user: u4321" -u billybadboy -GET 'http://localhost:9200/customer1/general/_search?pretty'
Enter host password for user 'billybadboy':
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "customer1",
        "_type" : "general",
        "_id" : "2",
        "_score" : 1.0,
        "_source" : {
          "foo" : "baz",
          "acl" : [
            "u1234",
            "billybadboy"
          ]
        }
      }
    ]
  }
}
```

We suspect this is happening because {{_user.username}} is not reflecting the impersonated user.

**Comment by abeyad** [comment]
@jaymode is this intended or a bug?

**Comment by smudgekick** [comment]
We think this is a bug


Bryan Reynolds
bryan@bbkareynolds.com<mailto:bryan@bbkareynolds.com>
+1 732 718 2272

Sent from my iPhone

On Apr 27, 2017, at 4:36 PM, Ali Beyad <notifications@github.com<mailto:notifications@github.com>> wrote:


@jaymode<https://github.com/jaymode> is this intended or a bug?

**Comment by rjernst** [comment]
Please open a thread in the [x-pack discuss forums](https://discuss.elastic.co/c/x-pack). This repository is for elasticsearch issues, not x-pack.
