### ISSUE TITLE
not able to fetch 2 level nested data in elasticsearch

### ISSUE THREAD

**Issue by abhishek5678** [elastic/elasticsearch#24385]
@martijnvg
I am also running the same nested example but it's not working.In this data when i am trying with one level nested data then it's working fine but when i am adding one more nested data then it's not working if anybody will be knows about that then please reply me.I am sending my document data and mapping file also.

PUT /icd10_codes
{
  "mappings": {
    "doc": { 
      "properties": {
        "name":            { "type": "string" },
        "depth":           {"type":"long"},
        "children": { 
          "type":             "nested",
          "properties": {
            "name":       { "type": "string" },
            "depth":          { "type": "long"   },
            "children":   { 
              "type":         "nested",
              "properties": {
                "code":     { "type": "string" },
                "name":    { "type": "string" },
                "depth":     { "type": "long" }
          }
        }
      }
    }
  }
}
}
}

POST /icd10_codes/doc/1
{
    "name": "Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism (D50-D89)",
    "depth": 1,
    "children": [{
		"name": "Nutritional anemias (D50-D53)",
		"depth": 2,
			"children": [{
				"code": "D50.0",
				"name": "Iron deficiency anemia secondary to blood loss (chronic)",
				"depth": 4
			}, {
				"code": "D50.1",
				"name": "Sideropenic dysphagia",
				"depth": 4
			}, {
				"code": "D50.8",
				"name": "Other iron deficiency anemias",
				"depth": 4
			}, {
				"code": "D50.9",
				"name": "Iron deficiency anemia, unspecified",
				"depth": 4
			}]
	}]
}

please tell me what is the query i am applying here.i applied the query like this:
GET /icd10_codes/doc/_search?_source=false
{
  "query": {
    "nested": {
      "path": "children",
      "query": {
        "bool": {
          "must": [
            {
              "match": {
                "children.name": "Nutritional anemias (D50-D53)"
              }
            },
            {
              "nested": {
                "path": "children.children",
                "query": {
                  "match": {
                    "children.children.name": "Sideropenic dysphagia"
                  }
                }
              }
            }
          ]
        }
      }
    }
  },
  "inner_hits": {
    "kids": {
      "path": {
        "children": {
          "query": {
            "match": {
              "children.name": "Nutritional anemias (D50-D53)"
            }
          },
          "inner_hits": {
            "grand_kids": {
              "path": {
                "children.children": {
                  "query": {
                    "match": {
                      "children.children.name": "Sideropenic dysphagia"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

**Comment by martijnvg** [comment]
@abhishek5678 Like others have told you, this is not the place to ask questions, only for bug reports and feature requests. Please ask these questions in the forum.

**Comment by abhishek5678** [comment]
@martijnvg 
I have posted in elasticforum.but no one can reply me.if you able to resolve that issue whatever i am sending then please reply me
