### ISSUE TITLE
Replica Consistency can prevent an index from allocating on startup or close/open

### ISSUE THREAD

**Issue by n0othing** [elastic/elasticsearch#24392]
**Elasticsearch version**: Tested on 2.4.4

**Description of the problem including expected versus actual behavior**: If an index's replica count is greater than `1` and there aren't enough available nodes to achieve quorum, then that index won't allocate on cluster restart or if you _close/_open the index. This prevents you from being able to _read_ from that index.

**Steps to reproduce**:
 1. Start with 3 nodes

```
GET _cat/nodes?v

host      ip        heap.percent ram.percent load node.role master name         
127.0.0.1 127.0.0.1            8          88 2.25 d         *      Larry Bodine 
127.0.0.1 127.0.0.1            3          88 2.25 d         m      Paibo        
127.0.0.1 127.0.0.1            8          88 2.25 d         m      Maggott      
```

 2. Create our 1P/2R index

```
PUT index
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 2
  }
}

GET _cat/indices?v

health status index pri rep docs.count docs.deleted store.size pri.store.size 
green  open   index   1   2          0            0       390b           130b 
```

 3. Shut down 2 nodes --> the index become yellow and is still allocated.

```
GET _cat/indices?v

health status index pri rep docs.count docs.deleted store.size pri.store.size 
yellow open   index   1   2          0            0       130b           130b 
```

4. Close and reopen the index (or simply restart the active node)

```
POST index/_close

POST index/_open

GET _cat/indices?v

health status index pri rep docs.count docs.deleted store.size pri.store.size 
red    open   index   1   2                                                   
```
5. If we create a brand new index, it will successfully allocate (not that we can really do anything with it because it doesn't meet quorum :) ).

```
PUT index2
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 2
  }
}

GET _cat/indices?v

health status index  pri rep docs.count docs.deleted store.size pri.store.size 
yellow open   index2   1   2          0            0       130b           130b 
red    open   index    1   2                          
```

6. If we attempt an empty `reroute` w/ `DEBUG` logging enabled, we see this in the logs

```
POST /_cluster/reroute

[2017-04-28 09:52:09,782][DEBUG][cluster.service          ] [Larry Bodine] processing [cluster_reroute (api)]: execute
[2017-04-28 09:52:09,783][DEBUG][gateway                  ] [Larry Bodine] [index][0] found 1 allocations of [index][0], node[null], [P], v[0], s[UNASSIGNED], unassigned_info[[reason=INDEX_REOPENED], at[2017-04-28T13:47:22.456Z]], highest version: [7]
[2017-04-28 09:52:09,783][DEBUG][gateway                  ] [Larry Bodine] [index][0]: not allocating, number_of_allocated_shards_found [1]
[2017-04-28 09:52:09,784][DEBUG][cluster.service          ] [Larry Bodine] cluster state updated, version [39], source [cluster_reroute (api)]
[2017-04-28 09:52:09,784][DEBUG][cluster.service          ] [Larry Bodine] publishing cluster state version [39]
[2017-04-28 09:52:09,784][DEBUG][cluster.service          ] [Larry Bodine] set local cluster state to version 39
[2017-04-28 09:52:09,785][DEBUG][cluster.service          ] [Larry Bodine] processing [cluster_reroute (api)]: took 2ms done applying updated cluster_state (version: 39, uuid: YtD5XV_QRN2OVMcXwfF2pQ)
```

I tested the same scenario on `5.3.1` and the index successfully allocated on restart/open, so this seems to only occur in 2.x.

**Comment by ywelsch** [comment]
yes, this is set in place on 2.x as a safety mechanism to prevent stale shards from being allocated as primary. The behavior can be overridden with the index setting `index.recovery.initial_shards` (see https://www.elastic.co/guide/en/elasticsearch/reference/2.4/index-modules.html#index.recovery.initial_shards), but this is not advised as you're trading availability for safety. 
In ES 5 we have completely reworked this part: we now uses unique shard copy ids that allow us to safely select the right shard copy as primary (for an explanation how that works in ES 5, see https://www.elastic.co/blog/tracking-in-sync-shard-copies).
In your example, note that you also did not properly set `minimum_master_nodes`, so you could also experience split brain with the configuration you gave.
