### ISSUE TITLE
allow xpack license to be installed from disk

### ISSUE THREAD

**Issue by rgardam** [elastic/elasticsearch#24393]
Having to install the xpack license via the rest api of elasticsearch makes it a nightmare for configuration management. 

I would love it if you could just have the xpack json file on disk under /etc/elasticsearch/license.json 
and elasticsearch was smart enough to import it from there. 

I have a real hacky way to import it via a script which checks if elasticsearch is up or not. 

Any plans for this?

**Comment by jasontedor** [comment]
This repository is reserved for open source Elasticsearch, not X-Pack issues. You can open a topic on the [forum](https://discuss.elastic.co) if you think this merits discussion. However, I think we are unlikely to consider this, adding a license requires a cluster state update through a master node. Dropping these on disk raises tricky issues: what if it's missing the current master node? What if there are inconsistent license files on disk on two master-eligible nodes? What if the file is replaced while the cluster is online? We have a simple solution to these and others problems today: apply the license through the API and let the current master broadcast the license to the nodes in the cluster.
