### ISSUE TITLE
Simplify File Store intialization

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#24390]
While analyzing #24361 we noted that we can simplify the initialization code for `ESFileStore` and also surrounding code in `Environment`.

1. **Removal of the `spins` flag**

We do not use the `spins` flag (which indicates whether a drive is spinning or an SSD) except in the node stats API. Lucene uses it in its `ConcurrentMergeScheduler` though to choose some default values. But as we only use our own custom subclass `ElasticsearchConcurrentMergeScheduler` which overrides these default choices of Lucene anyway, we can get rid of this flag completely.

2. **Choose file store based on OS**

This will still not solve issues like #24361 because the underlying problem is that [we iterate over all file stores when initializing `Environment`](https://github.com/elastic/elasticsearch/blob/382a617/core/src/main/java/org/elasticsearch/env/Environment.java#L107-L114).

The reason why we do this is to work around [JDK-8034057](https://bugs.openjdk.java.net/browse/JDK-8034057). However, this bug only affects Windows and we can choose the file store based on OS already (see [ESFileStore](https://github.com/elastic/elasticsearch/blob/382a617/core/src/main/java/org/elasticsearch/env/ESFileStore.java#L100)). By leveraging this mechanisms, we can get rid of iteration thus accessing only file stores that we actually need.

**Comment by jasontedor** [comment]
I'm adding the breaking label as this will remove the spins output from the node stats API; I think this is a minor break and worth making because of the advantages we get:
 - no more iterating over the file stores that we do not need
 - simplification of the code
