### ISSUE TITLE
FieldCaps api documentation still uses is_ prefix

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#24413]
https://www.elastic.co/guide/en/elasticsearch/reference/master/search-field-caps.html
https://www.elastic.co/guide/en/elasticsearch/reference/5.x/search-field-caps.html

mentions `is_searchable` and `is_aggregatable` but the `is_` prefix has been removed in `master` and latest 5.4 snapshot builds

**Comment by jimczi** [comment]
Thanks @Mpdreamz
