### ISSUE TITLE
Not supporting "Asia Pacific (Seoul) : ap-northeast-2" region

### ISSUE THREAD

**Issue by mintbass** [elastic/elasticsearch#24427]
Not supporting "Asia Pacific (Seoul) : ap-northeast-2" region yet.

**Comment by jasontedor** [comment]
Adding regions like has been deprecated and will be removed in 6.0.0 so I do not think that are going to add anymore, you can configure it manually (set `discovery.ec2.endpoint` to `ec2.ap-northeast-2.amazonaws.com`.
