### ISSUE TITLE
BM25 docFreq, docCount and avgFieldLength seems to be wrong 

### ISSUE THREAD

**Issue by Viatorus** [elastic/elasticsearch#24429]
**Elasticsearch version**: 5.3.2

**JVM version**: openjdk version "1.8.0_121"

**OS version**: linux gentoo x64

**Description of the problem including expected versus actual behavior**:

DocFreq, DocCount and avgFieldLength are wrong calculated for BM25 or are wrong described in [1](https://www.elastic.co/guide/en/elasticsearch/guide/current/scoring-theory.html), [2](https://www.elastic.co/guide/en/elasticsearch/guide/current/relevance-intro.html#explain), and [3](https://www.elastic.co/guide/en/elasticsearch/guide/current/practical-scoring-function.html).

I checked the same setup with Lucene as standalone and the score result was like expected in step 3 (see below).

**Steps to reproduce**:
 1. 
```
DELETE twitter

PUT twitter/tweet/1
{
    "title" : "b c d d d"
}

PUT twitter/tweet/2
{
    "title" : "b c d d"
}

PUT twitter/tweet/3
{
    "title" : "b c d"
}

PUT twitter/tweet/4
{
    "title" : "b c"
}

POST /twitter/tweet/_search
{
    "explain": true, 
    "query": {
        "term" : {
            "title" : "d"
        }
    }
}
```

 2. Check the explained output:

```
// IDF:
"value": 0.6931472,
"description": "idf, computed as log(1 + (docCount - docFreq + 0.5) / (docFreq + 0.5)) from:",
"details": [
	{
			"value": 1,
			"description": "docFreq",
			"details": []
	},
	{
			"value": 2,
			"description": "docCount",
			"details": []
	}
]

// BM25:
{
		"value": 3,
		"description": "avgFieldLength",
		"details": []
},
                
```

 3. Calculate idf and avgFieldLength your self.

DocCount = 4, DocFreq = 3
IDF = ln(1 + (4 - 3 + 0.5) / (3+0.5) = 0.356..

avgFieldLength = (5 + 4 + 3 + 2) / 4 = 14 / 4 = 3.5

**Comment by jimczi** [comment]
Don't forget that ES creates an index with 5 shards by default and that `docFreq` and `docCount` are computed per shard. You can create an index with 1 shard or use the `dfs` mode to compute distributed stats:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-type.html#dfs-query-then-fetch
