### ISSUE TITLE
Run some bats tests while in "production" mode

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#24431]
I had a peek around the bats tests and didn't see any that ran in "production mode" with `es.enforce.bootstrap.checks` set to true. This seems like a thing we should do. Doing this is going to require adding bash code that sets up the system so they bootstrap checks will pass. We should be able to use the snippets from https://www.elastic.co/guide/en/elasticsearch/reference/current/setting-system-settings.html#limits.conf to do it. Once we've done that we should be able to use the `include-tagged::{file-with-snippet.bash}[tag]` syntax to rebuild the docs so we're fairly sure that the snippets get test coverage.

**Comment by mark-vieira** [comment]
There are no more BATS tests so this issue can be closed.
