### ISSUE TITLE
not able to find auto-completion/suggestion and spell check in elasticsearch

### ISSUE THREAD

**Issue by abhishek5678** [elastic/elasticsearch#24430]
Hi Everyone,
I am putting my mapping file,documentation and whatever the query I have performed.Inside this i want to perform auto-completion/suggestion and spell check.if anyone knows about that then help me.
Mapping File:
PUT /test_word16
{
  "mappings": {
    "doc": { 
      "properties": {
        "name":            { "type": "string" },
        "depth":           {"type":"long"},
        "children": { 
          "type":             "nested",
          "properties": {
            "name":       { "type": "string" },
            "depth":          { "type": "long"   },
        "children": { 
          "type":             "nested",
          "properties": {
            "code":           { "type": "string" },
            "name":       { "type": "string" },
            "depth":          { "type": "long"   },
            "children":   { 
              "type":         "nested",
              "properties": {
                "code":     { "type": "string" },
                "name":    { "type": "string" },
                "depth":     { "type": "long" }
          }
        }
      }
    }
  }
}
}
}
}
}

Documentation:
POST /test_word16/doc/1
{
    "name": "Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism (D50-D89)",
    "depth": 1,
	"children": [{
		"name": "Nutritional anemias (D50-D53)",
		"depth": 2,
		"children": [{
			"code": "D50",
			"name": "Iron deficiency anemia",
			"depth": 3,
			"children": [{
				"code": "D50.0",
				"name": "Iron deficiency anemia secondary to blood loss (chronic)",
				"depth": 4
			}, {
				"code": "D50.1",
				"name": "Sideropenic dysphagia",
				"depth": 4
			}, {
				"code": "D50.8",
				"name": "Other iron deficiency anemias",
				"depth": 4
			}, {
				"code": "D50.9",
				"name": "Iron deficiency anemia, unspecified",
				"depth": 4
			}]
		}]
	}]
}

QUERY:
GET /test_word16/doc/_search
{
  "_source": false,
  "query": {
    "nested": {
      "path": "children.children.children",
      "query": {
        "bool": {
          "must": [
            {
              "match": {
                "children.children.children.name": "Iron"
              }
            }
          ]
        }
      },
       "inner_hits": {        
        "_source": {
          "excludes":["name"]
        }
      }
    }
  }
}
Query is working fine but i am not able to perform auto-completion/suggestion and spell check

**Comment by jimczi** [comment]
@abhishek5678 we reserve github for verified bugs and feature requests. Please open a new topic in the discuss forum:
https://discuss.elastic.co/c/elasticsearch
I'll be happy to answer any questions you have directly in the forum.

**Comment by abhishek5678** [comment]
yes I put my question in https://discuss.elastic.co/c/elasticsearch
