### ISSUE TITLE
Unknown key for a VALUE_STRING in [scripted_metric_aggregation]: [lang]

### ISSUE THREAD

**Issue by serj-p** [elastic/elasticsearch#24449]
The undocumented parameter "lang" for scripted metric aggregation is gone in 5x. I use python in this aggregation and I see no documentation explaining how to tell ES to use python(or groovy) for this kind of request.

**Comment by spinscale** [comment]
Please take some time to write up a proper title, provide a full example, including the request and the response, the Elasticsearch version as well as the JVM version (issues have a template for this reason, in order to try not to go too much back and forth).

Thanks a lot!

**Comment by colings86** [comment]
Since 2.0 the way scripts are specified in the same way across all APIs in Elasticsearch. Details ont he syntax can be found in the scripting modules documentation: https://www.elastic.co/guide/en/elasticsearch/reference/5.3/modules-scripting-using.html

This is also linked from the main documentation page for aggregations: https://www.elastic.co/guide/en/elasticsearch/reference/5.3/search-aggregations.html#_values_source

**Comment by serj-p** [comment]
I run this using openjdk version "1.8.0_121"

STR:
es 2.4:
`curl -XPOST localhost:9200/test/test/1 -d {"test": 1}`
`curl -XPOST localhost:9200/test/_search -d '{
  "aggs": {
    "test_agg": {
      "scripted_metric": {
        "lang": "python",
"map_script": "lambda: 1"
      }
    }
  }
}"`
output: 
`{"took":2,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"test","_type":"test","_id":"1","_score":1.0,"_source":{"test":1}}]},"aggregations":{"test_agg":{"value":[{},{},{},{},{}]}}}`

es 5.3:
`curl -XPOST localhost:9200/test/test/1 -d {"test": 1}`
`curl -XPOST localhost:9200/test/_search -d '{
  "aggs": {
    "test_agg": {
      "scripted_metric": {
        "lang": "python",
"map_script": "lambda: 1"
      }
    }
  }
}"`
output:
`{"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a VALUE_STRING in [test_agg]: [lang].","line":1,"col":48}],"type":"parsing_exception","reason":"Unknown key for a VALUE_STRING in [test_agg]: [lang].","line":1,"col":48},"status":400}`

**Comment by serj-p** [comment]
Do you need any more feedback to take a look at this?

**Comment by clintongormley** [comment]
@serj-p use:

```
    "scripted_metric": {
      "map_script": {
         "lang": "python",
         "inline": "....."
      }
   }
```
