### ISSUE TITLE
how to set the analyzer for a  field when i usespark-elasticsearch saveToEsWithMeta save to es

### ISSUE THREAD

**Issue by tonyC2016** [elastic/elasticsearch#24458]
my question is how to set the analyzer for a  field which's name is changed , 
my code like as below:

  val test ="性别"
    val lbs: Map[String, String] = Map("create_time" -> "1491990010000",
      "name" -> "年龄",
      "values" -> "70后,80后,90后",
      "label" -> "{values}",
      "measure" ->"0.0",
      "tags" ->"用户画像,灰度发布",
       test->"性别,男")
    sc.makeRDD(Seq((1, lbs))).saveToEsWithMeta("label_sys_label/label")

3q for help!!

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by tonyC2016** [comment]
3q
