### ISSUE TITLE
Elk Stack 5.2 & 5.3 Issue with Metricbeat Dashboards on Kibana:::Visualize: Fielddata is disabled on text fields by default 

### ISSUE THREAD

**Issue by rkommine** [elastic/elasticsearch#24456]
**Elasticsearch version**: 5.2.0 & 5.3.0

**Plugins installed**: [logstash beats plugin]

**JVM version**: java version "1.8.0_121"

**OS version**: CentOS Linux release 7.3.1611 (Core)

**Description of the problem including expected versus actual behavior**:

![image](https://cloud.githubusercontent.com/assets/15034740/25652881/f549891c-3007-11e7-8734-8fd28ce4d167.png)

When I Install the elkstack & metricbeats, I have imported metricbeat dashboards using the below command:

/usr/share/metricbeat/scripts/import_dashboards -file /root/beats-dashboards-5.2.0.zip

After this when I open the dashboard & open any of the visualization that contains a textfield, like process name, disk name the error mentioned in above screenshot is coming.

**Steps to reproduce**:
 1. Install elk-stack 5.2.0 or 5.3.0
 2. Import metric beat dashboards using below command
/usr/share/metricbeat/scripts/import_dashboards -file /root/beats-dashboards-5.2.0.zip
 3. Configure metricbeat on any linux server.
4. Open the metricbeat Metricbeat system overview Dashboard in Kibana

**Discussion Forum Post**:

I have raised the issue in below discussion forum. But after almost a month of search in forums & google I am not able to find the solution.

https://discuss.elastic.co/t/elk-stack-5-3-issue-with-metricbeat-dashboards-on-kibana-visualize-fielddata-is-disabled-on-text-fields-by-default/82035

**Provide logs (if relevant)**:
Attached the GET /metricbeat-* output & elasticsearch output
[Downloads.zip](https://github.com/elastic/elasticsearch/files/972810/Downloads.zip)

**Comment by jasontedor** [comment]
I've moved your topic to the Metricbeat category on the forum. This repository is for verified bugs and feature requests for Elasticsearch, we use the forum for general help. I'll ask you to continue there now that I've moved your topic, and since this is the Elasticsearch repository.
