### ISSUE TITLE
Snapshot on HDFS via Kerberised WebHDFS / HttpFS endpoints

### ISSUE THREAD

**Issue by AndreAga** [elastic/elasticsearch#24455]
Hi all,
I suggest to implement in the next release of HDFS repository plugin the way to store snapshot in a remote kerberised Hadoop cluster via WebHDFS / HttpFS endpoints (with or without SSL). From the Java points of view, I think it changes only the URL (specified by the user), but the code would be essentially the same (with Hadoop FileSystem API). Please also consider that many organizations, for internal and (sometimes) unknown policies, allow only that endpoints instead of the RPC HDFS (hdfs://namenode...). Obviously, Kerberos is a must have (via local keytab).

What do you think about this new kind of configuration?

Now:
```
{
  "type": "hdfs",
  "settings": {
    "uri": "hdfs://namenode:8020/",
    "path": "elasticsearch/respositories/my_hdfs_repository",
    "conf.dfs.client.read.shortcircuit": "true",
    "conf.<key>": "",
    ...
  }
}
```
Then:
```
{
  "type": "webhdfs", (or httpfs, or hdfs)
  "settings": {
    "uri": "webhdfs://<HOST>:<HTTP_PORT>/", (or "https://<HOST>:<HTTP_PORT>/webhdfs/v1/" or "hdfs://<HOST>:<HTTP_PORT>")
    "path": "elasticsearch/respositories/my_hdfs_repository",
    "kerberos.enabled": true,
    "kerberos.principal": "USER@PRINCIPAL",
    "kerberos.keytab.path": ".../user.keytab",
    "kerberos.config.path": ".../krb5.conf",
    "hadoop.client.site.path": ".../core-site.xml",
    "hadoop.client.hdfs.path": ".../hdfs-client.xml",
    "hadoop.client.ssl.path": ".../ssl-client.xml",
    ...
  }
}
```
I think hadoop client files are better than the actually conf.<key> options.

What do you think about it? 

Thank you.
Kind regards.

**Comment by spinscale** [comment]
@jbaiera maybe you can comment on this one, you have been playing around with Kerberos/Hadoop recently...

**Comment by jbaiera** [comment]
I think this is a reasonable idea and is worth exploring further, but would like to point out that getting Hadoop to play nice with the Java security model, while doable, is also an exercise in frustration.

**Comment by jbaiera** [comment]
In terms of suggested design, I don't think we should change the type name of the repository. The only thing that should really change is the uri scheme (hdfs, webhdfs, etc.).

> I think hadoop client files are better than the actually conf. options.

While I'm inclined to agree (mirroring those configurations on the REST request is not the most straightforward thing, especially if they're already in file format), do consider that to access and read configuration files on disk we are required to declare file access rules in the plugin security policy. Trying to account for where a user chooses to place those configs in the security policy is potentially just as obtuse as mirroring the configurations onto the request. Perhaps it would be better if we could load these from a designated location like the conf directory.

**Comment by AndreAga** [comment]
> Perhaps it would be better if we could load these from a designated location like the conf directory.

Yeah, maybe it's better if a user put all the required files in the config directory, I didn't think about that.

**Comment by original-brownbear** [comment]
@ywelsch @jbaiera maybe we should close this one? It hasn't come up again in 2.5 years now and it doesn't look like anyone is going to work on it in the foreseeable future? :)

**Comment by jbaiera** [comment]
I think it's fair to close this out. I think it's a reasonable feature to add, but there hasn't been much demand for it outside of this discussion. Happy to reopen it if we see an increase in demand.

**Comment by xyu** [comment]
@jbaiera we (Automattic / WordPress.com) recently ran into this limitation when we wanted to snapshot our ES cluster onto our HDFS cluster. We front our HttpFS/WebHDFS endpoints for our Hadoop cluster with Nginx for SSL and basic auth termination in order to expose a more controlled and cleaner API for "external" use cases like this. It would have been nice to be able to use WebHDFS / HttpFS instead of direct PRC calls to avoid having to punch holes in our firewalls on every Hadoop node to every ES node.

I'm not sure if you've gotten any more requests for WebHDFS support over the years or if this kind of use case warrants reopening this ticket.
