### ISSUE TITLE
Upgrade from 2.2 to 5.2 old data using the new version of the index, the new field analysis error, can not be stored

### ISSUE THREAD

**Issue by lilizhaolilizhao** [elastic/elasticsearch#24459]
"illegal_argument_exception","reason":"Can't parse [index] value [not_analyzed] for field [xxxxx], expected [true] or [false]"}}

**Comment by lilizhaolilizhao** [comment]
"dynamic_templates": [
        {
          "template1": {
            "mapping": {
              "ignore_above": 1024,
              "index": "not_analyzed",
              "type": "{dynamic_type}",
              "doc_values": true
            },
            "match": "*"
          }
        }
"Index": "not_analyzed", modified to "index": "false" or "index": "false", is still wrong

**Comment by nik9000** [comment]
I can't tell what the problem is. Do the old indexes not work? That would
be a bug. If creating new indexes doesn't work with an old index template
that isn't a bug, just a gotcha about upgrading. You should upgrade the
dynamic templates. The release notes should tell you exactly how to do
that.

**Comment by spinscale** [comment]
can you please take the time and write a proper report (we have the template for exactly that reason). This means including exact versions of elasticsearch, the JVMs being used, deployment (i.e. docker, rpm, deb), operating system, the index mapping, the steps you took to upgrade - and of course, what exactly is not working.

**Comment by lilizhaolilizhao** [comment]
Thank you all, I found the solution to the problem.
The problem is that after the upgrade, the old index data mapping is still the previous version.
Resolvent：
Reindex the old Index, to generate a new version mapping, so that you can write data containing the new field
