### ISSUE TITLE
DedicatedClusterSnapshotRestoreIT#testMasterShutdownDuringSnapshot fails in CI

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#24452]
* Failure link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu/917/consoleFull
* reproduction line: `gradle :core:integTest -Dtests.seed=E02060E9AA99A891 -Dtests.class=org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT -Dtests.method="testMasterShutdownDuringSnapshot" -Dtests.security.manager=true -Dtests.locale=es-BO -Dtests.timezone=Africa/Cairo`
* Failure rate: Does not reproduce locally; occured 8 times in the previous year on CI
* Failure description: Snapshot is not complete within a one minute timeout

[build output for the failing test](https://github.com/elastic/elasticsearch/files/972534/build_log.txt)

**Comment by spinscale** [comment]
another one here https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/949/consoleFull

**Comment by imotov** [comment]
Another one here https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/2757/console
