### ISSUE TITLE
cant install as service

### ISSUE THREAD

**Issue by djholly123** [elastic/elasticsearch#24467]
Hi

following this I cant install it as a service but can run ES ok manually. I appreciate the os is old but upgrade is not currently possible

I am following instruction from : https://www.elastic.co/guide/en/elasticsearch/reference/master/rpm.html

**Elasticsearch version**: 5.3.2
**Plugins installed**: none
**JVM version**: 1.8.0_77
**OS version**: CentOS 5.11 Final

**Steps to reproduce**:
in unzipped installe folder /opt/elasticsearch-5.3.2/bin
 1. sudo chkconfig --add elasticsearch
 2. sudo /sbin/chkconfig --add elasticsearch

CANT install service 

any help appreciated

**Comment by jasontedor** [comment]
If you want to install as a service, use the RPM package.

Beyond this, Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by djholly123** [comment]
ok thanks for response
