### ISSUE TITLE
InternalTestClusterTests#testDataFolderAssignmentAndCleaning fails with MasterNotDiscoveredException

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#24464]
* Failure link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/118/consoleFull
* Reproduction line: `gradle :test:framework:test -Dtests.seed=DE0AE1177A089E30 -Dtests.class=org.elasticsearch.test.test.InternalTestClusterTests -Dtests.method="testDataFolderAssignmentAndCleaning" -Dtests.security.manager=true -Dtests.locale=ar-SY -Dtests.timezone=Pacific/Port_Moresby`
* Failure summary. The test fails with "MasterNotDiscoveredException[NodeNotConnectedException[[testm0][127.0.0.1:9562] Node not connected]]; nested: NodeNotConnectedException[[testm0][127.0.0.1:9562] Node not connected]"
* Failure rate: 5 times in CI within the last year

[relevant part from the build log of build 118](https://github.com/elastic/elasticsearch/files/973638/build_log.txt)

**Comment by jimczi** [comment]
Another failure in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/281

**Comment by jaymode** [comment]
Another failure https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/378

**Comment by bleskes** [comment]
This is more than a year old now - I don't think there's much value in chasing it.
