### ISSUE TITLE
Incorrect disk ("fs") stats with multiple nodes in a single box

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#24472]
**Elasticsearch version**: 5.3.0

**Plugins installed**: [none]

**JVM version**: Java 1.8

**OS version**: Windows (but is happening as well in Linux)

**Description of the problem including expected versus actual behavior**: 

Have two nodes in `Disk D`, one pointing to a data folder in `Disk G (node1)` and the other to `Disk F (node2)` both with 2GB each:
Disks:

<img width="868" alt="screen shot 2017-05-03 at 15 38 09" src="https://cloud.githubusercontent.com/assets/1675411/25676090/27dfa3de-3017-11e7-8b9c-462618e6a29f.png">

Nodes stats clearly shows that we have 2 nodes, each with 2GB:

```
{
  "nodes" : {
    "VEpm8eR8SjmV0AEXOy3DUA" : {
      "fs" : {
        "timestamp" : 1493837976833,
        "total" : {
          "total_in_bytes" : 2144333824,
          "free_in_bytes" : 2102579200,
          "available_in_bytes" : 2102579200
        },
        "data" : [
          {
            "path" : "G:\\data\\nodes\\0",
            "mount" : "Node1 (G:)",
            "type" : "NTFS",
            "total_in_bytes" : 2144333824,
            "free_in_bytes" : 2102579200,
            "available_in_bytes" : 2102579200
          }
        ]
      }
    },
    "ItZtzg8ER-WBvMUo2eEYvA" : {
      "fs" : {
        "timestamp" : 1493837976836,
        "total" : {
          "total_in_bytes" : 2144333824,
          "free_in_bytes" : 2102579200,
          "available_in_bytes" : 2102579200
        },
        "data" : [
          {
            "path" : "F:\\data\\nodes\\0",
            "mount" : "Node2 (F:)",
            "type" : "NTFS",
            "total_in_bytes" : 2144333824,
            "free_in_bytes" : 2102579200,
            "available_in_bytes" : 2102579200
          }
        ]
      }
    }
  }
}
```

But the cluster stats are showing only half of that:

```
{
  "nodes" : {
    "fs" : {
      "total_in_bytes" : 2144333824,
      "free_in_bytes" : 2104438784,
      "available_in_bytes" : 2104438784
    }
  }
}
```

Behavior: ` total` shows 2GB
Expected: `total` should show 4GB

**Steps to reproduce**:
 1. Start two nodes one pointing to a mount, the other to another mount
 2. Run `http://localhost:9200/_cluster/stats?pretty&filter_path=nodes.fs`
 3. Verify that total in bytes is 2GB, while it should be 4GB.

This is affecting also Monitoring, as it shows wrong information:

<img width="1002" alt="screen shot 2017-05-03 at 15 58 02" src="https://cloud.githubusercontent.com/assets/1675411/25676696/5dfd7ef8-3019-11e7-941d-b42ccd629529.png">

**Comment by jasontedor** [comment]
We deduplicate FS stats based on IP addresses. Since these machines share the same IP address, the FS totals from the second node are not added. That leads us astray here, since they do not share the same data path. We could look into deduplicating based on IP address and path. However, there are other issues here, for example if two nodes share the same host and same data path but are bound to different interfaces, then we will not de-duplicate (because of the different IP address) but we should because they share the same data path on the same machine. Effectively, IP address is not enough to de-duplicate, we need a unique machine ID and then we should only de-duplicate based on the unique machine ID and path.

**Comment by gmoskovicz** [comment]
@jasontedor so this confirms that the deduplicate logic is broken for this case right? I think that IP address as you said is not enough, so we should check multiple things but not only the IP address.

**Comment by jasontedor** [comment]
> so this confirms that the deduplicate logic is broken for this case right?

I'm really sorry, I'm trying to understand what you're asking that is not already answered in my previous comment? Can you help me understand the question?

**Comment by gmoskovicz** [comment]
@jasontedor all clear, i read your first statement as the logic is the one that we found to be accurate for most cases, but i think that what you meant is that we need to find a better logic for this, which we don't know what is the best.

**Comment by jasontedor** [comment]
Right, this issue exposes a flaw in the logic: it accounts for multiple hosts on a node sharing the same data path, but not for multiple hosts on a node not sharing the same data path, and it does not account for multiple hosts on a node not sharing the same interface.

I do think that my proposal to de-duplicating based on unique machine ID and path is the best path (pun!) forward.

**Comment by coolacid** [comment]
I'll caution against using "same path" as the de-duplicating point. Say, for example,
Instance1: /data/instance1
Instance2: /data/instance2

If the mount point is /data/ then both instances use the same physical disk space - this should be de-duped. 

However, if the mount point is /data/instance1 and /data/instance2 then there is two different mount points and should not be de-duped. 

Note: /_nodes/stats/fs Does provide the mount point (in my production environment on CentOS) at [Node]->fs->data->mount and might be useful to identify de-duplication details.

**Comment by jasontedor** [comment]
Right, and then there are complexities that arise with mount points that share the same storage space (e.g., space sharing in APFS or subvolumes in btrfs). These are not easy problems, and I do not think that we can solve them all, but instead can only do a best effort.

**Comment by gmoskovicz** [comment]
Agree around best effort if we try to do this automatically. However, we could also add a setting that you can manually add to flag this situation in nodes. That will resolve the long tail of smaller issues that we cannot resolve.

**Comment by jasontedor** [comment]
I don't think we will add settings for this, that's just complexity around complexity.

**Comment by nerophon** [comment]
Another user has been tripped up by this. Any thoughts on moving it forward? Marking as adopt me for instance? @jasontedor @gmoskovicz

**Comment by kjelle** [comment]
We see the same, running multiple 6.3.2 docker containers on same host which uses different mount points.  `/_cluster/stats` report about half the fs.total_in_bytes.

**Comment by coolacid** [comment]
Can we get an update on this issue? We're now moving to docker based builds with 3+ instances per server causing this to be even more pronounced.

**Comment by pizzasuprema** [comment]
I am also experiencing this issue using multiple docker containers and multiple disks per host.
https://discuss.elastic.co/t/cluster-not-reporting-actual-available-space/226785

**Comment by cdgh2021** [comment]
we are experiencing this issue too.
any progress on this issue?

**Comment by ylasri** [comment]
Having the same issue with v8.4.1 on docker
https://discuss.elastic.co/t/cluster-stats-disk-available
