### ISSUE TITLE
Support storage account details in Azure repository configuration

### ISSUE THREAD

**Issue by nordbergm** [elastic/elasticsearch#24471]
The `repository-azure` plugin currently stores its account credentials in `elasticsearch.yml`. Similar to what's already supported in the `repository-s3` plugin, we (the ☁️ team) would like to have the option to supply the storage account and storage key as part of the repository configuration. 

This would mean that all the details could be supplied when you create the repository, without having to modify `elasticsearch.yml`.

### Additional Configuration
Add two more configuration options to the repository. When they are present, `account` is not required.

* `storage_account`: This would contain the actual storage account name, and not the configuration reference that can be supplied through `account`.
* `storage_key`: This would contain the secret key required to access the storage account

Create the repository with the storage account and key inline, removing the need to retrieve the details from `elasticsearch.yml`:

### API Example
```json
PUT _snapshot/my_backup2
{
    "type": "azure",
    "settings": {
        "storage_account": "your_azure_storage_account1",
        "storage_key": "your_azure_storage_key1",
        "container": "backup-container",
        "base_path": "backups",
        "chunk_size": "32m",
        "compress": true
    }
}
```

**Comment by abeyad** [comment]
I might be missing something, but if we put things like `storage_key` in the repository settings, then its part of the cluster state and retrievable by the APIs, so it would present a security risk?

**Comment by rjernst** [comment]
@abeyad is right. Storing in repository settings is no more secure than in elasticsearch.yaml. This is why that feature has been removed in 6.0 from s3 repository. The elasticsearch keystore is the place to securely store these settings.

**Comment by dadoonet** [comment]
Agreed. I think it's safe to close this issue as it's described here and may be reopen or open a new one if we need to solve the root cause in a way or another.
