### ISSUE TITLE
cannot excute binart file

### ISSUE THREAD

**Issue by Purelightme** [elastic/elasticsearch#24482]
$ ./elasticsearch
./elasticsearch: line 183: /Users/purelightme/jdk1.8.0_131/bin/java: cannot execute binary file
./elasticsearch: line 183: /Users/purelightme/jdk1.8.0_131/bin/java: Undefined error: 0

I downloaded elasticsearch's .tar.gz file,then i installed java8 from 'brew'.I run 'elasticsearch',coming with above problem.

What can i do?

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
