### ISSUE TITLE
No support for renaming fields in the response.

### ISSUE THREAD

**Issue by jaisharma639** [elastic/elasticsearch#24484]
Say my response looks something like this:
`{
        "_index": "xyz.com",
        "_type": "my_type",
        "_id": "my_id",
        "_score": 1,
        "_source": {
          "UIStage": "Identified",
          "Owner_adjusted": "Jai Sharma"
         }
}`
I'm streaming the response to the user and would like to show something like this to the user:
`{
        "_index": "xyz.com",
        "_type": "my_type",
        "_id": "my_id",
        "_score": 1,
        "_source": {
          "Stage": "Identified",
          "Owner": "Jai Sharma"
         }
}`
Because the names Stage and Owner make more sense to the customer than the convention used internally by company. I looked up for support to achieve this and found out that **partial_fields** would have helped me but unfortunately its deprecated and no more supported in 2.x
Why can't we have something similar to **AS** in SQL here as well?

**Comment by clintongormley** [comment]
Discussed in FixItFriday. Implementing this on the client side when you know what fields you want to rename is easy.  Doing so in a generic way in Elasticsearch has many more corner cases.  `partial_fields` never allowed the renaming of fields, only filtering.  In Elasticsearch, we prefer not to implement things that can be done more simply on the client side, as the added complexity and edge cases is not worth the gain

**Comment by jaisharma639** [comment]
1. I thought this query:
`{
    "query" : {
        "match_all" : {}
    },
    "partial_fields" : {
        "partial1" : {
            "include" : "obj1.obj2.*"
        }
    }
}`
would return the response field as **partial1** instead of obj1.obj2.*. Anyways its deprecated now , so no point discussing it.

2. Well its not that easy to do it on the client side as it involves iterating through the huge response i'm returning. I use the helpers.scan method to return a generator from elasticsearch and have to loop through entire response just to rename each field in each record of response. These kind of features have always been there in any data store but lack in elasticsearch.

**Comment by jaisharma639** [comment]
Does my comment above make sense? Would you suggest a better way of handling this on client side @clintongormley ?
