### ISSUE TITLE
GET /_snapshot/[repo]/_all slow/inefficient

### ISSUE THREAD

**Issue by joachimdraeger** [elastic/elasticsearch#24509]
**Elasticsearch version**: 5.2.0 - master
**Plugins installed**: repository-s3
**JVM version**: 1.8.0_92
**OS version** : Darwin [..] 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64
**Description of the problem including expected versus actual behavior**:

Listing a read-only 2.4.1 S3 snapshot repository with about 100 snapshots takes 10s on ES 5.1.2 and 5m41s on ES 5.2.0 and 5.3.1.

I noticed that the AWS S3 client is making a lot of requests:
```
cat es-5.1.2.log | grep "Sending request: GET /elasticsearch/green" | wc 
185
cat es-5.3.1.log | grep "Sending request: GET /elasticsearch/green" | wc 
9485
cat es-5.3.1.log | grep "Sending request: GET /elasticsearch/green/snap-month_201703_20170331_100020.dat" | wc
94
```
Listing a 5.3.1 S3 snapshot repository with about 100 snapshots takes 17s and with a fix of the problem 3s.
On 6.0.0-alpha1-SNAPSHOT (master) with about 100 snapshots takes 13s and with a fix of the problem 3s.

**Steps to reproduce**:

Tested on 5.3.1 and master
 1.  create 100 snapshots
 2. GET /_snapshot/[repo]/_all, measure time

**Analysis**:

The problem has been introduced with [commit 714e74888acbe6e8443413a295c0c78cd3bd1c4e](https://github.com/elastic/elasticsearch/commit/714e74888acbe6e8443413a295c0c78cd3bd1c4e):
In order to handle incompatible snapshots gracefully `getRepositoryData()`  is called for each `snapshotId`, which is especially problematic for a list operation. `getRepositoryData()` will load the `snapshotIndexBlob` and the `incompatibleSnapshotsBlob` each time. (17s instead of 3s) 

For a legacy and read-only repository, getRepositoryData() will load each snapshot on every call in order to upgrade the data, which leads to exponential cost. (5m41s instead of 10s)

[(problematic call to getRepository)](https://github.com/elastic/elasticsearch/commit/714e74888acbe6e8443413a295c0c78cd3bd1c4e#diff-d5e40e0acdb86da4b9d02a16848fa927R582)

**Comment by danielmitterdorfer** [comment]
@abeyad Can you please have a look?

**Comment by jasontedor** [comment]
Closed by #24403, this will be released with v5.4.1.

**Comment by jod-signal** [comment]
I don't believe #24403 fixes the issue @jasontedor. I reproduced the issue on master rev 6b67e0bf2fb3e27279dff90ba76fa7c93bb4c828 today.
I have a fix on https://github.com/joachimdraeger/elasticsearch/tree/repository-data-fix. I'm happy to open a pull request, but I'm still struggling running `gradle check` on integration tests.

**Comment by jasontedor** [comment]
@jod-signal Please open a PR, @abeyad will work through it with you.
