### ISSUE TITLE
 Node operation rerouting ?

### ISSUE THREAD

**Issue by EliZheng** [elastic/elasticsearch#24500]
Hi, I am reading your introduction about elasticsearch under the code and I got confused about the following content: 
  . All APIs perform automatic node operation rerouting  
What does this mean? It will be very helpful  if you explain it a bit more.

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
