### ISSUE TITLE
ElasticSearch Snapshot API is unresponsive for big indexes

### ISSUE THREAD

**Issue by basilboli** [elastic/elasticsearch#24507]
We have  ElasticSearch 5.2.2 with azure storage plugin configured, total data size is 10 TB  (5TB of data with one 1 replica for every shard). The cluster seems to be in good health and the load is ok. 

**Problem :**
After running snapshot of all the indexes snapshot API becomes unresponsive e.g. doing :

GET _snapshot/REPOSITORY/_all 
PUT _snapshot/REPOSITORY/NEW_SNAPSHOT

both fail on timeout (note : we fail automatically the job after 30s timeout).

**Expected behaviour**: 
We expect snapshot API to be responsive.

**Comment by clintongormley** [comment]
Set the `wait_for_completion` parameter to `false` to have the snapshot job run in the background.

**Comment by basilboli** [comment]
That's the case already : we use ?wait_for_completion=false when creating snapshot. 
The point that it's still unresponsive even for _snapshot/REPOSITORY/_all which should be fast, shouldn't it ? 

Could it be related to the : 
1. Shards no 
2. We do not use dedicated node for snapshotting 
3. Master node is also data node

Thanks.

**Comment by clintongormley** [comment]
Ah, that bit was missing from the original description.  Reopening

**Comment by ywelsch** [comment]
Could also be related to #24403. @abeyad can you have a look?

**Comment by abeyad** [comment]
This will be fixed by https://github.com/elastic/elasticsearch/pull/24403 and https://github.com/elastic/elasticsearch/pull/24510.  Its the same as #24509 so I'm closing this one.
