### ISSUE TITLE
Improve customizing Aggregator memory weight

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#24511]
Right now all Aggregators report that they consume the same amount of memory: 5k. There are absolutely aggregations that can make a better estimate but it is probably important for aggregations that take *more* than 5k report that. If they don't then a sufficiently evil aggregation can knock out the cluster.

Note that this weight only has to include the non-BigArrays portion of the aggregation. The BigArrays portion is of the aggregation is tracked using the BigArrays breaker and doesn't need any estimation because it is based on the actual memory usage at the time.

**Comment by markharwood** [comment]
We added something for this in the aggregator base class: https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/AggregatorBase.java#L122

**Comment by dakrone** [comment]
I think there's some improving we can do here, if we need to decrement the breaker we can still trip the breaker, that method should check for negative numbers and use `addWithoutBreaking` instead, that way it's safer to use as part of the `.close()` method on the aggregations. I'm going to re-open this and change the title.
