### ISSUE TITLE
Bad JSON from ES?

### ISSUE THREAD

**Issue by chrisdrobison** [elastic/elasticsearch#24526]
**Elasticsearch version**: 5.2.2

**Plugins installed**: [analysis-phonetic, x-pack]

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): CentOS 6

**Description of the problem including expected versus actual behavior**:

In our production instance, we seem to be randomly getting back bad JSON data. In .NET, the library is failing with the following errors:

Unterminated string. Expected delimiter: ". Path 'hits.hits[83]._source.file_number', line 1, position 53362.
Unterminated string. Expected delimiter: ". Path 'hits.hits[131]._id', line 1, position 84022.
Unable to read data from the transport connection: The connection was closed.

It always appears to be to always be at 'hits.hits[...'. I've seen different ending, but always starting there.

**Steps to reproduce**:

 1. Perform a basic search that does an exact match on a keyword and limit the result set to 200 items.

Not sure how to help debug this one.

**Comment by jasontedor** [comment]
> Not sure how to help debug this one.

A full reproduction would really help! Put this document, execute this search, explode.

**Comment by chrisdrobison** [comment]
Found the problem. Not related to ES.

**Comment by ng-martin** [comment]
Hi @chrisdrobison 
May i know what your problem was? and how you solved it.
Thanks

**Comment by chrisdrobison** [comment]
We had nginx in front and apparently some bad disk permissions were preventing the entire response from coming back since it couldn't cache the whole response to disk.
