### ISSUE TITLE
'+' in index expressions does not behave as documented

### ISSUE THREAD

**Issue by olcbean** [elastic/elasticsearch#24537]
The documentation ( https://www.elastic.co/guide/en/elasticsearch/reference/master/multi-index.html ) states :

> Most APIs that refer to an index parameter support execution across multiple indices ...  and the ability to "add" (+) and "remove" (-), for example: +test*,-test3.

This reads to me that when multiple indices are used, the `+` can be specified explicitly. Or if it is not provided, the "add" is implicit. In other words `index1,+index2` is equivalent to `index1,index2`

However when I tried it out the results were unexpected.
```
DELETE _all
PUT test
PUT test2
DELETE test,+test*
```
The request is successful, and I expect that both `test` and `test2` are deleted ( the same as if `DELETE test,test*` has been used ). However when I run `GET _cat/indices`, the results is : `yellow open test2 22vx3qayTxyaQCJZAPBq_w 5 1 0 0 985b 985b`.

It appears that `+test*` is ignored.

( Found this while trying to understand #24515 )

**Comment by javanna** [comment]
hi @olcbean thanks for opening this issue. Sounds like a bug to me, I would not have expected this result.

**Comment by javanna** [comment]
heya @olcbean I double checked, and the root cause of this is #5341 . If you encode `+` as `%2B` in the curl call, you'll get the expected result.

**Comment by olcbean** [comment]
Hm... of course it works as expected! `+` is a reserved char in the URL and the `DELETE test,+test*` is exactly trying to match the ` test*` as according to the URL spec. Referring to the docs and using Console misled me as I expected that Console will convert the `+` to `%2B` which is not the case ( I guess as Console has no way of determining if `+` is meant as a SP or as `+` )

To encode the `+` is not a workaround. This is the only way to explicitly "add" an index to the index expressions.

But #5341 is still open... Am I missing something? Maybe the only thing that can be done to "fix" it, is to add a note to the docs that the `+` must be encoded.

**Comment by javanna** [comment]
hey @olcbean that issue is still valid as `+` seems to be a perfectly valid char as part of the url path. We should not require users to encode it.
