### ISSUE TITLE
What are the characteristics of each upgrade or repair bug，Can it clearly provide?

### ISSUE THREAD

**Issue by kervin521** [elastic/elasticsearch#24539]
**Describe the feature**:

**Elasticsearch version**:

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by tvernum** [comment]
This issue appears to have created in error.

**Comment by tvernum** [comment]
Actually on second reading I see that you have attempted to ask a question in the title.

@kervin521, Please ask this question on our [discuss forum](https://discuss.elastic.co/) where we can provide better support. You will need to provide more detail about your question though - it's not clear exactly what you're trying to ask.

Elastic uses GitHub issues for confirmed bugs and feature requests which have been discussed on the forums.
