### ISSUE TITLE
Simplify scripting enabled settings

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#24532]
We currently have 3 concepts in scripts: language, type (inline, file, stored), and context. We also have "fine grained control" over the various combinations of these that can be allowed. These settings are automatically added in the script service, and the logic is complex with fallbacks.

As we are working towards a simpler scripting api, with contexts actually implying the variables available to a script, we should simplify these settings. I propose to have each of these concepts allow for disabling, but not the endless combinations; that level of control is simply not necessary.

My proposed settings are:
```
script.types_allowed: ['inline']
script.contexts_allowed: ['search_template', 'whatever']
```

The plan would be to add these alternative settings in 5.5, at the same time as disabling the old fine grained settings.

**Comment by jasontedor** [comment]
Note there's an issue to remove file-based scripting (#21798) which would help simplify things too.

**Comment by clintongormley** [comment]
I'm not sure we even need languages here - the languages that we expose are safe, so the question is whether you want any scripting enabled or disabled (for all or a list of particular contexts) and if so, would you accept inline or stored, or both.

**Comment by rjernst** [comment]
@clintongormley Ok, I modified the description to (1) not have languages and (2) removed "disabled" so these lists are now inclusive instead of exclusive. For the latter, it means disabling just one context is more work, but it is much clearer that you want exactly these contexts, and new ones added will not be automatically added to your explicit list.

**Comment by jdconrad** [comment]
This has been completed.

**Comment by spalger** [comment]
@rjernst @jdconrad Kibana currently determines which languages were enabled for inline scripting with `http://localhost:9200/_cluster/settings?include_defaults=true&filter_path=**.script.engine.*.inline`, is there some other API we can use now?

**Comment by spalger** [comment]
Sorry, I see discussion has already started in https://github.com/elastic/kibana/issues/11959
