### ISSUE TITLE
Add "parents" bucket aggregation

### ISSUE THREAD

**Issue by fbaligand** [elastic/elasticsearch#24536]
Presently, there is the [children](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-children-aggregation.html) which enables aggregating from buckets on parent document types to buckets on child documents.

This would be great to add the reverse aggregation : "parents" which enables aggregating from buckets on child document types to buckets on parent documents.

**Comment by clintongormley** [comment]
Closing as duplicate of https://github.com/elastic/elasticsearch/issues/5306
