### ISSUE TITLE
How can i use the Wild card characters in scripted fields in elastic search ?

### ISSUE THREAD

**Issue by R2D2-fwks** [elastic/elasticsearch#24545]
Hi Everyone,

I want something similar like this 
`doc["my_field"].value=="*-Volume" ? 1:0`
How can i achieve this from Kibana or from elastic search

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
