### ISSUE TITLE
Automatically slice reindex and friends

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#24547]
Background:

Right now reindex and friends have a [slices](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex-automatic-slice) parameter that you can set to automatically parallelize the process. Setting the right value for the `slices` parameter is a little involved but we have documented [guidelines](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex-picking-slices).

Question:

Is it worth implementing something like `?slices=auto`? We can do a fairly good job picking the number of slices with something simple like:

```
if (sourceIndex.numberOfShards > 50) {
  slices = 1; // too big, user should optimize it by hand.
} else {
  slices = sourceIndex.numberOfShards;
}
```

The point here is that `?slices=auto` can be a sane default. Maybe, even, it could *be* the default in 6.0.

**Comment by jpountz** [comment]
+1 to a sane default value

Maybe we could default to something like `min(numShards, 10)`, I don't like suddenly deoptimizing when crossing a boundary?

Also I don't think we need a parameter value for it, it could just be the default and users would override it with an explicit value if it does not satisfy their needs?

**Comment by nik9000** [comment]
> Also I don't think we need a parameter value for it, it could just be the default and users would override it with an explicit value if it does not satisfy their needs?

That is fine with me.


> Maybe we could default to something like min(numShards, 10), I don't like suddenly deoptimizing when crossing a boundary?

Me neither. The trouble is that it is a bit complex to come up with a good choice if the number of shards is large. I can certainly run some benchmarks to do that though. That might be a good exercise in general though.

**Comment by jimczi** [comment]
> Me neither. The trouble is that it is a bit complex to come up with a good choice if the number of shards is large. I can certainly run some benchmarks to do that though. That might be a good exercise in general though.

The reasoning behind `min(numShards, N)` is to always pick a number that is less or equals to the number of shards. This way the `slicing` does not add any overhead since each shard is assigned to a single slice.

**Comment by nik9000** [comment]
> This way the slicing does not add any overhead since each shard is assigned to a single slice.

This is something I hadn't realized. I went and reread that code. I'd thought that had special cases for when `shards == slices` and `shards == <some integer> * slices`. But it looks like the special case is `shards <= slices` and the `shards == <some integer> * slices` is handled by the general case.

Basically I thought we made more of an effort to keep the slices sized consistently at the cost of efficiency. Instead we go with the most efficient query at the cost of potentially vastly different slice sizes. I'm sure @jpountz and @jimczi know all this but I figured it might be nice to call it out for anyone who ends up on this issue.

In that case `min(numShards, N)` is a very safe bet.

**Comment by andy-elastic** [comment]
@nik9000 I'd like to give this one a shot if it's not too far over my head. I think I follow the discussion here and the docs on slices. Few questions:

1. I'm reading "and friends" here as "APIs that support slices", is that right?
2. Is the [benchmarks project](https://github.com/elastic/elasticsearch/blob/master/benchmarks/README.md) the right place to get started with benchmarking/profiling how well the strategy we choose works
3. If (and I may be misunderstanding here) it's preferable to have #slices be a whole factor of #shards, would it make sense to do something like:

```
choose our constant ceiling, say C = 10
if shards < C
  slices = shards
else
  slices = the largest factor of shards that's under C
endif
```

**Comment by nik9000** [comment]
> I'm reading "and friends" here as "APIs that support slices", is that right?

update-by-query and delete-by-query. Basically the APIs that are implemented in the reindex module. They all share a ton of code.

> Is the benchmarks project the right place to get started with benchmarking/profiling how well the strategy we choose works

I think it is worth talking to @danielmitterdorfer about using https://github.com/elastic/rally for this. It is designed for generating benchmarks. It makes http://banchmarks.elastic.co. Having a reindex benchmark might be a thing. If we had one we could point to this as a big win on the graph. Hopefully.

> If (and I may be misunderstanding here) it's preferable to have #slices be a whole factor of #shards, would it make sense to do something like:

That is what I thought at first but isn't true. Sliced scroll runs in two ways:
1. If the number of slices <= shards then assign each shard to a slice and query those shards.
2. Otherwise, assign each shard to a slice and add a filter.

So we want to shoot for slices == shards exactly. Going above makes the query less efficient and isn't obviously better. Maybe in some cases it is but I don't know that it is worth doing by default. But slices <= shards has very low cost which is why we were ok with doing it by default.

That ceiling constant is more about safety than performance. If you set the number of slices too high then reindex can take a ton of memory.

**Comment by danielmitterdorfer** [comment]
>> Is the benchmarks project the right place to get started with benchmarking/profiling how well the strategy we choose works

The benchmarks project is about microbenchmarks (benchmarking components of Elasticsearch in isolation), [Rally](https://github.com/elastic/rally) is about macrobenchmarks (end-to-end benchmark of the whole system)

> I think it is worth talking to @danielmitterdorfer about using https://github.com/elastic/rally for this. 

The Reindex API is not supported out of the box by Rally but it is very easy to add this capability (see the ["runner" concept in the Rally docs](http://esrally.readthedocs.io/en/latest/adding_tracks.html#custom-runners)) and I can definitely help out with that.

> Having a reindex benchmark might be a thing. If we had one we could point to this as a big win on the graph. Hopefully.

As a first step, we could definitely add reindex to one of the standard [Rally tracks](https://github.com/elastic/rally-tracks) (think: benchmark scenarios). I suggest we add this to the "geonames" track as a starter. 

At the moment we're a bit tight on runtime budget in the nightly benchmarks (total duration is currently ~ 15 hours per day) but I am sure we can do something to make it happen midterm.

**Comment by nik9000** [comment]
> At the moment we're a bit tight on runtime budget in the nightly benchmarks (total duration is currently ~ 15 hours per day) but I am sure we can do something to make it happen midterm.

We're getting close to those being "daily" instead of nightly....

**Comment by andy-elastic** [comment]
>That ceiling constant is more about safety than performance. If you set the number of slices too high then reindex can take a ton of memory

Gotcha, and it seems like a benefit from the user's side is that it gives them a good way to use slices without having to make guesses about how many to configure, and `min(numShards, N)` won't give any surprises.

>As a first step, we could definitely add reindex to one of the standard Rally tracks (think: benchmark scenarios). I suggest we add this to the "geonames" track as a starter.

Sounds good, I'll plan on using geonames. Rally looks like a really cool benchmarking project. I'm sure I'll have more questions for you when I get that far.

**Comment by nik9000** [comment]
> Gotcha, and it seems like a benefit from the user's side is that it gives them a good way to use slices without having to make guesses about how many to configure, and min(numShards, N) won't give any surprises.

Right. I see this as "we are comfortable enough with slices that we may as well always use them when they're obviously faster". The user can get the old behavior back with `slices=1`.

I think a few PRs worth of changes might come from this issue:
1. Update the guidelines I linked in the description to align with the discussion above.
2. Implement `slices=auto`.
3. Set it as the default.

I think we're on board with doing all three though I think making `auto` the default should wait a bit because setting `slices` to anything but `1` doesn't work with reindex-from-remote. We should probably *get* it to work with reindex-from-remote. I didn't implement slices against remote nodes because it didn't seem worth it at the time. Now that slice support has been out for longer there will be more opportunities to reindex remotely.

**Comment by andy-elastic** [comment]
I mostly get how the code matches up with the discussion here but wanted to clarify one thing (I think @jimczi is the original author of this part)

So the node that gets the original reindex request (I think this is called the coordinating node, not sure if that's the right terminology) builds a subrequest for each slice that has a `SliceBuilder`. It looks like the way `SliceBuilder` tells the search subrequest how to slice happens in [`#toFilter`](https://github.com/elastic/elasticsearch/blob/f576c987ce2615f77a8de75741b0f5448229805f/core/src/main/java/org/elasticsearch/search/slice/SliceBuilder.java#L192), which I'm guessing happens right before the actual subrequest is sent.

I walked through an example of `toFilter` with possible input values that looked like this

```
numSlices = 4
numShards = 2

sliceId		shardId		targetShard	numSlicesInShard	shardSlice	query
0		0		0		2			0		TermsSlice(0, 2)
1		0		1		2			0		MatchNothing
2		0		0		2			1		TermsSlice(1, 2)
3		0		1		2			1		MatchNothing

0		1		0		2			0		MatchNothing
1		1		1		2			0		TermsSlice(0, 2)
2		1		0		2			1		MatchNothing
3		1		1		2			1		TermsSlice(1, 2)
```

The relationship between `sliceId` and `targetShard` seems pretty clear from the way it's described [in the javadoc](https://github.com/elastic/elasticsearch/blob/f576c987ce2615f77a8de75741b0f5448229805f/core/src/main/java/org/elasticsearch/search/slice/SliceBuilder.java#L44-L54), but I'm not sure how the returned filter tells the search which shard to operate on. The TermsSliceQuery instances returned seem like they only deal with slices, and I think I get how they divide up a shard into multiple slices. But I'm missing how that encodes "which shard does this slice belong to"

**Comment by jimczi** [comment]
@andy-elastic slicing can be done per shard, I want to split a single shard in several `scroll` requests, or globally. The former is easier to use since you just set the number of slices that you want and each sliced requests can decide which and how each shard should be scrolled.
For instance with `numSlices:4' and `numShards:2` you would have 4 scroll requests, one for each slice id. Each request would be sent to all shards and rewritten locally depending on the `sliceId` they have. More precisely the 4 requests would be divided in:
- Slice 0 returns results for shard 0 and match documents that match `Math.floorMod(_id, maxSlice) == 0`
- Slice 1 returns results for shard 1  and match documents that match `Math.floorMod(_id, maxSlice) == 1`
- Slice 2 returns results for shard 0 and match documents that match `Math.floorMod(_id, maxSlice) == 0`
- Slice 3 return results for shard 1 and match documents that match `Math.floorMod(_id, maxSlice) == 1`

If you do the inverse, 2 slices for 4 shards, slice 0 would return result for shard 0 and 2 and slice 1 for shard 1 and 3. The nice part is that the shard selection is done internally by the request so you don't have to target a specific shard manually. Does this makes sense ?

**Comment by nik9000** [comment]
I had a look and didn't see a way that we direct things to the appropriate shard either. I imagine you can check this for sure by breakpointing on `toFilter`, but I *think* we send the request to all the shards any rely on `MatchNothing`.

**Comment by andy-elastic** [comment]
Thanks guys, that makes sense. So it sounds like the request flow is

1. Client sends reindex request to coordinating node
2. Coordinating node sends one request per slice to other nodes (let's call them workers)
3. Workers produce a query for that slice which only matches shards and documents as described above, and then make a request to the nodes that actually have those shards on them to reindex those documents

or maybe (2) and (3) happen on the same node?

I'll start updating the docs and then add the `slices=auto` option. From the existing code it seems like it would make more sense to do the "auto" => number of slices conversion while constructing the internal `ReindexRequest`.

**Comment by andy-elastic** [comment]
@nik9000 here's an update on where I am with this: I got a version working last week, but it created some behavior that was a little confusing. If slices = auto, it has no way to know whether there's more than one shard (therefore one slice) until it handles the transport request. So if slices=1, it would only create the single child task and an unsliced search. But if slices=auto, then it would create a parent task with one child task and one slice. I wanted to avoid this because it's inconsistent.

I refactored the tasks so that they may act as either a child or parent, depending on how they're configured when the transport request is handled. My refactor works with some of the tests but seems to have a problem with rethrottling. I'm digging into that now.

**Comment by nik9000** [comment]
That makes sense to me. I wouldn't mind too much if `slices=auto` always created a parent task and that one created as many children as needed (maybe just 1). If the refactor is too crazy I think that'd be a fine way to do it.

**Comment by jimczi** [comment]
Resolved by https://github.com/elastic/elasticsearch/pull/26030

**Comment by yazaddaruvala** [comment]
@jimczi do you mind adding some of this information to the docs?

[Sliced Scroll Docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-request-scroll.html#sliced-scroll) is decent, but is missing a lot of information around how to pick a good number for slice, and how the number of slices interacts with number of shards from a performance perspective.

For example, the biggest thing I was confused about was:

- "Does a shard get pinned to the same slice?" i.e. `numShards=4` `numberSlices=4` will there be a total of 4 scroll contexts across all the shards, or a total of 16 scroll contexts across all the shards.

- This issue did a really good job clarifying that it would be only 4 scroll contexts across all the shards.

Another example I am still confused about: When there are `numShards=3` `numberSlices=2`; Then `{ Slice_0: [Shard_0, Shard_2], Slice_1: [Shard_1]`

- Does `Slice_0` open the scroll context on both shards in parallel, or will it go sequentially and only create the scroll context on `Shard_2` after it has killed the scroll context on `Shard_0`?

- Do the shards get assigned to slices lazily or eagerly, i.e. is there [work stealing](https://en.wikipedia.org/wiki/Work_stealing)? Is `Slice_0` immutably assigned `[Shard 0, Shard 2]` or can `Slice_1` take over `Shard_2` if it finished all its work early?

**Comment by EmersonDing** [comment]
@nik9000 Hi. Any progress made on auto slicing with `reindex-from-remote`?

**Comment by nik9000** [comment]
@EmersonDing I never implemented slicing reindex-from-remote. In the years since I last touched this issue I took a year long hiatus from contributing to Elasticsearch full time to work on our docs infrastructure. And now that I'm back to contributing to Elasticsearch consistently I'm spending most of my time on aggs and reindex is owned by other folks who are looking at more sweeping improvements.

**Comment by EmersonDing** [comment]
@nik9000 I see. Can you refer me to anyone who's working on reindex atm, or any ticket more related to reindex with remove or slice? I'm interested in the progress about this feature.
