### ISSUE TITLE
(stack-docker) Problem pulling kibana 5.4.0 unhealthy.

### ISSUE THREAD

**Issue by cvaldess** [elastic/elasticsearch#24540]
docker pull docker.elastic.co/kibana/kibana:5.4.0
5.4.0: Pulling from kibana/kibana
59e69571f6c7: Already exists 
1d183283a292: Pull complete 
cb96f1762d96: Downloading [=============================>             ] 39.47 MB/52.9 MB
443c0035bf3c: Download complete 
44521dcfe57b: Download complete 
b5ed3e53dd29: Download complete 
7e6ba66696b9: Download complete 
64f9b10fdaa1: Download complete
Digest: sha256:f586dec0b7f59922d4be9efdb994308db2c37463562156e7332d22a3849e634e
Status: Downloaded newer image for docker.elastic.co/kibana/kibana:5.4.0

stack-docker: docker-compose up
Creating network "stackdocker_stack" with the default driver
Creating stackdocker_elasticsearch_1
Creating stackdocker_kibana_1
Creating stackdocker_logstash_1
Creating stackdocker_metricbeat_1
Creating stackdocker_filebeat_1
Creating stackdocker_packetbeat_1
Creating stackdocker_heartbeat_1

ERROR: for create_logstash_index_pattern  Container "1131347c736f" is unhealthy.

ERROR: for import_dashboards  Container "1131347c736f" is unhealthy.

ERROR: for set_default_index_pattern  Container "1131347c736f" is unhealthy.
ERROR: Encountered errors while bringing up the project.

docker ps
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                     PORTS                                NAMES
5d2c410fa7e9        docker.elastic.co/beats/packetbeat:5.4.0              "packetbeat -v -e ..."   5 minutes ago       Up 5 minutes                                                    stackdocker_packetbeat_1
0dfdc12c629d        docker.elastic.co/beats/heartbeat:5.4.0               "heartbeat -e"           5 minutes ago       Up 5 minutes                                                    stackdocker_heartbeat_1
1356aa94ab10        docker.elastic.co/beats/filebeat:5.4.0                "filebeat -e"            5 minutes ago       Up 5 minutes                                                    stackdocker_filebeat_1
a007ce564b3c        docker.elastic.co/logstash/logstash:5.4.0             "/usr/local/bin/do..."   5 minutes ago       Up 5 minutes               5044/tcp, 9600/tcp                   stackdocker_logstash_1
e30484a3e87a        docker.elastic.co/beats/metricbeat:5.4.0              "metricbeat -e"          5 minutes ago       Up 5 minutes                                                    stackdocker_metricbeat_1
1131347c736f        docker.elastic.co/kibana/kibana:5.4.0                 "/bin/sh -c /usr/l..."   5 minutes ago       Up 5 minutes (unhealthy)   127.0.0.1:5601->5601/tcp             stackdocker_kibana_1
446954d8f919        docker.elastic.co/elasticsearch/elasticsearch:5.4.0   "/bin/bash bin/es-..."   6 minutes ago       Up 6 minutes (healthy)     127.0.0.1:9200->9200/tcp, 9300/tcp   stackdocker_elasticsearch_1

**Comment by jasontedor** [comment]
This should be in [elastic/kibana-docker](https://github.com/elastic/kibana-docker).
