### ISSUE TITLE
High CPU Usage in one node of cluster of 4 nodes

### ISSUE THREAD

**Issue by gotha229a0** [elastic/elasticsearch#24544]
**Elasticsearch version**: 1.7.5

**Plugins installed**: [HEAD / KOPF ]

**JVM version** (`java -version`): Oracle Java version 1.8

**OS version** : Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:

We have a Cluster of Elasticsearch , 4 data nodes, 1 master node and 1 client node.

The 4 data nodes have 8vCPU and 31GB of RAM each.

We have different indexes but one of them is the biggest one with 1TB of data with replication factor 1.

The problem is that 3 nodes are working as expected, increasing the heap, load and cpu but also decreasing, but one of the nodes are stuck at 100% ( 780% ) CPU usage and never decrease the CPU usage ( we have it up from 2 days right now ) 

We are basically doing search queries ( should with bool filters ) and using multi get API.

Could be that some index/shard got corrupted on this node and this is the reason why the node is ever at 100% CPU?

Sorry for the english and Thanks!

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

BTW this version is too old and not maintained anymore.

**Comment by jasontedor** [comment]
Also, 1.7.5 is an end-of-life (unsupported) version of Elasticsearch now.
