### ISSUE TITLE
curl: (7) Failed connect to 193.81.62.189:9200; Connection refused

### ISSUE THREAD

**Issue by shyamalaponnada** [elastic/elasticsearch#24551]
Hi,
I installed ES 5.0. on my server(centos 7). I want to work on server not localhost. So I changed my elasticsearch.yml file with my ip number:193.81.62.189:

network.host: 193.81.62.189

After restart ES and I tried to connection.

However It didn't work true.

[root@elasticsearch ~]# curl http://193.81.62.189:9200
my error:
curl: (7) Failed connect to 193.81.62.189:9200; Connection refused

What is the problem????

**Comment by jasontedor** [comment]
You should look at the logs and see why startup is failed or hanging. Maybe it's a bootstrap check, maybe you're trying to run as root based on your console output, there's a lot of reasons that Elasticsearch could fail to start here and none of them are bugs. Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
