### ISSUE TITLE
CI Failure: org.elasticsearch.search.aggregations.bucket.nested.ReverseNestedAggregatorTests (testMaxFromParentDocs)

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#24554]
Reproduce With:

gradle :core:test -Dtests.seed=8C113E877BEA9385 -Dtests.class=org.elasticsearch.search.aggregations.bucket.nested.ReverseNestedAggregatorTests -Dtests.method="testMaxFromParentDocs" -Dtests.security.manager=true -Dtests.jvm.argline="-XX:+AggressiveOpts" -Dtests.locale=zh-HK -Dtests.timezone=Atlantic/Stanley

Build Failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.4+aggressive-opts/51/console

**Comment by chengpohi** [comment]
Hello @jdconrad, I have tried to fix this issue, Could you help review this?

**Comment by jdconrad** [comment]
@chengpohi @colings86 has a significantly better knowledge of aggregations than I do.  I'm hopeful he'll be able to take a look.

**Comment by martijnvg** [comment]
Fixed via: 0a88cea2a156b7b794d7f383a8e4a9096dd0efee (5.x) and 13ce32572301b5bd54158cd66075acb2ef13261d (5.4)
