### ISSUE TITLE
Elasticsearch plugin is red(5.4.0)

### ISSUE THREAD

**Issue by macadminrohit** [elastic/elasticsearch#24566]
ui settings:Elasticsearch plugin is red(5.4.0)
plugin:elasticsearch@5.4.0 :  Request Timeout after 3000ms

Not sure how to resolve this. Logstash, Elastic Search and Kibana are installed on the same server

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
