### ISSUE TITLE
geohash_grid how to get more detailed information

### ISSUE THREAD

**Issue by ypli0629** [elastic/elasticsearch#24576]
How to get more detailed information, for example, in this geohash which points are included,not just doc_count

**Comment by ypli0629** [comment]
I use tophits aggs to get more detailed information, but it will affect the efficiency of the query

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

thanks
