### ISSUE TITLE
Deprecate the Tribe node

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#24581]
While we only plan to remove the Tribe node in 7.0, the future for federated search definitely lies with Cross Cluster Search.

I've added a deprecation notice to the Tribe docs https://github.com/elastic/elasticsearch/commit/2486086980663bce5ff25f5ed7eb25d6a2cfc7c7 but we should also add deprecation logging.

**Comment by glefloch** [comment]
I've start working on it from 5.x branch. I run tests and I will do the pull request.
