### ISSUE TITLE
quadtree_grid aggregation

### ISSUE THREAD

**Issue by yavuzmester** [elastic/elasticsearch#24587]
We are drawing heatmaps with quadtrees. For each 256px tile, we dive 8 levels in the quadtree and find the pixel value that way. 

In elasticsearch we can have a location field with the following mapping:

location: {
  type: geo_shape,
  tree: quadtree,
  tree_levels: 25,
  points_only: true
}

But there is only geohash_grid aggregation. What about quadtree_grid aggregation where in the response keys are paths like [0,2,1,3,0,1].

**Comment by clintongormley** [comment]
@nknize any thoughts?

**Comment by jpountz** [comment]
FixitFriday: removing the discuss label and assigning to Nick. This soulds like a useful feature but we need to validate whether we can execute such an aggregation efficiently.

**Comment by nyurik** [comment]
I just submitted a pull request #30231 with [plus code](https://plus.codes/) support - I think that PR can be used as a step towards multi-hashing support.

**Comment by talevy** [comment]
Hi @yavuzmester,

We have created a new `geotile_grid` aggregation that buckets using the quadkey tiling strategy: https://www.elastic.co/guide/en/elasticsearch/reference/7.0/search-aggregations-bucket-geotilegrid-aggregation.html.

Does this enable your use-case? You still only are returned a representation of the bucket, and need to use client-side logic to translate each bucket into a visual tile on a map.

**Comment by nyurik** [comment]
@yavuzmester you might also be interested in #39810

**Comment by polyfractal** [comment]
I'm going to close this, since I think the `geotile_grid` satisfies the requirement for now, with followup from #39810 as mentioned.
