### ISSUE TITLE
InetSocketTransportAddress class no more found in 5.3.2 transport version

### ISSUE THREAD

**Issue by komibajaj** [elastic/elasticsearch#24597]
**Elasticsearch version**: 
<groupId>org.elasticsearch.client</groupId>
            <artifactId>transport</artifactId>
            <version>5.3.2</version>

**Plugins installed**: []

**JVM version** (`java -version`): "1.8.0_112"

**OS version** (`uname -a` if on a Unix-like system): Darwin

**Description of the problem including expected versus actual behavior**:
Expected : org.elasticsearch.common.transport.InetSocketTransportAddress class, as my class was using it with current version till 05/09/2017
Actual: org.elasticsearch.common.transport.InetSocketTransportAddress class not found post 10 a.m. PST of 05/09/2017.

**Steps to reproduce**:

 1. Use the 5.3.2 dependency for transport.
 2. Create a new InetSocketTransportAddress(InetAddress.getByName(clusterHost), 9300)
 3. Compile time error.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
The API changed, use TransportAddress.

**Comment by komibajaj** [comment]
Thanks @jasontedor for clarifying that is what I did, but I thought it might be just by mistake as I also started seeing this issue https://github.com/elastic/elasticsearch/issues/24601 since same time and hence thought to report.
