### ISSUE TITLE
Remove Stored Template API in favor of Stored Scripting API

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#24596]
The existing stored template API is simply a shortcut for the stored scripting API that inserts mustache as the scripting language.  We should remove the stored template API and use the scripting API instead.  With the plans for upcoming contexts this makes even more sense as any language that is capable of returning a String and taking a Map of parameters should be able to execute as a template.

**Comment by jdconrad** [comment]
@martijnvg @nik9000 @rjernst Do you guys have any opinions on this issue?

**Comment by martijnvg** [comment]
@jdconrad I'm :+1: on this change.
