### ISSUE TITLE
[CI] org.elasticsearch.recovery.RelocationIT.testIndexAndRelocateConcurrently fails due to global checkpoint mismatch

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#24599]
Using

```
gradle :core:integTest -Dtests.seed=43166F36FCC6395D -Dtests.class=org.elasticsearch.recovery.RelocationIT -Dtests.method="testIndexAndRelocateConcurrently" -Dtests.security.manager=true -Dtests.locale=hu-HU -Dtests.timezone=Antarctica/Davis
```

I get the following reproducible failure:

```
FAILURE 23.7s | RelocationIT.testIndexAndRelocateConcurrently <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: [test][4], node[SSgDlhBBQiWaq17k34x9VA], [R], s[STARTED], a[id=5Z9JOyGLT6WZfoF7z3ItzA] global checkpoint mismatch
   > Expected: <27L>
   >      but: was <20L>
   > 	at __randomizedtesting.SeedInfo.seed([43166F36FCC6395D:9C276EBBE0C326FE]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.recovery.RelocationIT.lambda$beforeIndexDeletion$1(RelocationIT.java:127)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:716)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:690)
   > 	at org.elasticsearch.recovery.RelocationIT.beforeIndexDeletion(RelocationIT.java:109)
   > 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:581)
   > 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2059)
   > 	at java.lang.Thread.run(Thread.java:745)
```

Originally seen at https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/1385/console , but as that's a PR-build, the log for it might be gone soon. I've uploaded a log from my local running in case the Jenkins log goes away - [err.txt](https://github.com/elastic/elasticsearch/files/991077/err.txt)

**Comment by imotov** [comment]
Lee already opened https://github.com/elastic/elasticsearch/issues/24599
 Thanks Lee!

**Comment by jasontedor** [comment]
Closed by 0b089ac0845db09d8ad51c766d0831257fd97571

**Comment by ywelsch** [comment]
More failures: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/2519/consoleFull

**Comment by abeyad** [comment]
Another failure: 	https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/2586/console

**Comment by jasontedor** [comment]
I pushed additional logging in 0499849b1be18137f6b1cc4923eaef63458eb9c4 to get some insight into this developing situation.

**Comment by rjernst** [comment]
Another failure:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+aggressive-opts/148/console

**Comment by jasontedor** [comment]
Sadly that one did not yet pick up the commit that includes the extra logging, hopefully the next one.

**Comment by jasontedor** [comment]
I muted this test in 9a118691bf990d70b25772de56fbf0025037d334.

**Comment by jasontedor** [comment]
Here are the logs from a build failure with the additional logging enabled: [logs.zip](https://github.com/elastic/elasticsearch/files/1030288/logs.zip)

**Comment by jasontedor** [comment]
We need to transfer a primary context during relocation hand-off. For now we have reenabled this test with a hack in place to work around the issue. The hack will be removed after we have implemented this. See #10708 for additional details.
