### ISSUE TITLE
Cross Cluster Search settings not dynamically updateable

### ISSUE THREAD

**Issue by rfraposa** [elastic/elasticsearch#24590]
**Elasticsearch version**: 5.4.0

**Plugins installed**: []

**JVM version** (`java -version`):  Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

**OS version** (`uname -a` if on a Unix-like system): Mac OS X

**Description of the problem including expected versus actual behavior:** 
Not sure if this was done intentionally, but settings like `connections_per_cluster` and `initial_connect_timeout` can not be configured using the Cluster Update Settings API. All three of these PUT commands generate an `illegal_argument_exception` on ES 5.4.0:

```
PUT _cluster/settings
{
  "transient": {
    "search.remote" : {
      "initial_connect_timeout" : "10s",
      "east_cluster" : {
        "seeds" : ["127.0.0.1:9300"]
      }
    }
  }
}

PUT _cluster/settings
{
  "persistent": {
    "search.remote" : {
      "connections_per_cluster" : 3,
      "east_cluster" : {
        "seeds" : ["127.0.0.1:9300"]
      },
      "west_cluster" : {
        "seeds" : ["127.0.0.1:9300"]
      }
    }
  }
}

PUT _cluster/settings
{
  "persistent": {
    "search.remote" : {
      "node.attr" : "my_gateway",
      "east_cluster" : {
        "seeds" : ["127.0.0.1:9300"]
      }
    }
  }
}
```

The error looks like:

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "persistent setting [search.remote.connections_per_cluster], not dynamically updateable"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "persistent setting [search.remote.connections_per_cluster], not dynamically updateable"
  },
  "status": 400
}
```

**Comment by clintongormley** [comment]
`initial_connect_timeout` is how long to wait at startup, so that only makes sense in the config file.

`node.attr` and `connections_per_cluster` is the same for all clusters, not sure it needs to by dynamically updatable?

**Comment by rfraposa** [comment]
That makes sense for `initial_connect_timeout` and `connections_per_cluster`. Thanks.

I might not understand how `node.attr` is used. I was thinking it is used to limit which nodes a cross-cluster client can connect to, so you provide a custom tag for those nodes on the remote cluster, then set `search.remote.node.attr` to your custom tag value. Wouldn't that setting be unique per remote cluster?

**Comment by clintongormley** [comment]
> Wouldn't that setting be unique per remote cluster?

It could be, but we kept it simple for now.  I can't think of a scenario where using the same attr on all clusters would be problematic?

**Comment by s1monw** [comment]
you'd just use something like `node.attr.cluster_proxy = true` or something like this and use it on all clusters?

**Comment by rfraposa** [comment]
Ok - good to know. Thanks!

**Comment by javanna** [comment]
I am fine with having the same setting for all clusters, but given that we allow to register remote clusters dynamically, I think having these static settings limit the dynamic nature of cross cluster search. For instance, I want to register remote clusters in an existing cluster, and I want to mark remote nodes as gateway: I need to restart all nodes in the existing cluster to be able to configure the node attribute?

**Comment by s1monw** [comment]
>  I need to restart all nodes in the existing cluster to be able to configure the node attribute?

yes, what would be the attribute the nodes already have here? I think its unlikely that they are already tagged.

**Comment by javanna** [comment]
I think it's fine that one has to restart the remote nodes to tag them if they are not tagged, but a bit annoying to have to restart the "local" nodes to make use of the remote tagging.
