### ISSUE TITLE
got mapper_parsing_exception error when a json contain @fields 

### ISSUE THREAD

**Issue by jeremywu0127** [elastic/elasticsearch#24614]
I use `fluentd` to collect my log and use `fluent-elasticsearch-plugin` to forward the log to `elasticsearch`, the log contains the key `@fields` like
```
{"heading":"xxx yyyy","@fields":{"name":"test-fluentd","agent":"amazon linux"}}
```
it got errors like:
```
{"index"=>{"_index"=>"myindex", "_type"=>"fluentd", "_id"=>"AVv2FavAYwkgUC9vlGH_", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [@fields]", "caused_by"=>{"type"=>"illegal_state_exception", "reason"=>"Can't get text on a START_OBJECT at 1:85"}}}}
```
why does this error happen, cause the `@fields` is the reserved keyword ?

**Comment by tlrx** [comment]
Can you please provide the version of elasticsearch and the mappings?

**Comment by jeremywu0127** [comment]
I use the dockerized [`es+kibana`](https://hub.docker.com/r/nshou/elasticsearch-kibana/), the version is `5.3.2`, the mappings looks like 
```
#curl 127.0.0.1:9200/myindex/_mapping/fluentd
{
    "myindex": {
        "mappings": {
            "fluentd": {
                "properties": {
                    "@field": {
                        "properties": {
                            "name": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            },
                            "agent": {
                                "type": "text",
                                "fields": {
                                    "keyword": {
                                        "type": "keyword",
                                        "ignore_above": 256
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by tlrx** [comment]
It looks like it's a misconfiguration in the mappings; elasticsearch expects a text but it gets an object instead. You should check again the documents sent by the `fluent-elasticsearch-plugin`. Also, the mappings you provided refers to `@field`, not `@fields`.

**Comment by jeremywu0127** [comment]
@tlrx I change the `@fields` to `@field`, then it works  fine, nothing else I changed, so I wonder if the `@fields` is reserved keyword in `es`? if not, maybe it is in `fluent-elasticsearch-plugin`

**Comment by tlrx** [comment]
`@fields` is not a reserved keyword, I really think that the document were not correctly formatted according to the mappings. Also next time that would be great to use the Discuss forum (https://discuss.elastic.co/) because we reserve Github for known issues. Thanks!
