### ISSUE TITLE
SearchContextMissingException[No search context found for id [36304]] the es version is 2.1.1

### ISSUE THREAD

**Issue by butter-fly** [elastic/elasticsearch#24610]
**Describe the feature**:

**Elasticsearch version**:

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by cbuescher** [comment]
Please provide a better description about the problem, including a description of what you are doing and a way to reproduce the issue.
