### ISSUE TITLE
Should we remove the keyed option in Aggregations

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#24611]
This issue was created for discussion from #15484 which was resolved (the documentation was added) and so closed but still has an outstanding point for discussion on whether we should keep the `keyed` option in Aggregations going forward.

I'll try to summarise the main points raised on the previous issue below:

Arguments for removal of `keyed`:
* It's not consistently implemented, many of the aggregations don't have a `keyed` option (https://github.com/elastic/elasticsearch/issues/15484#issuecomment-165400312)
* `keyed: true` responses don't (and can't) maintain order (https://github.com/elastic/elasticsearch/issues/15484#issuecomment-165741960)
* `keyed:true` responses produce key names that potentially look like paths eg 99.9 and can't be indexed into elasticsearch and won't work with path syntax (https://github.com/elastic/elasticsearch/issues/15484#issuecomment-165741960)
* Converting an array into a map is a one liner on the application side (https://github.com/elastic/elasticsearch/issues/15484#issuecomment-165741960)

Arguments for keeping `keyed`:
* Sometimes you do know what you're looking for and you use the aggs to get a few specific aggs. In those cases you want to have random access to them instead of writing boilerplate code that iterates over an array to find those aggs (https://github.com/elastic/elasticsearch/issues/15484#issuecomment-165445628)

There was also one other point made that doesn't fit into one side or another but that advocates for making all the agg responses look the same:
* There should be a consistent response structure across all aggs. This enables more generic tools to build UIs on top of the aggs and treat all the aggs the same when parsing the response. IMO, Having an array of buckets as a default structure is a good choice for that. (https://github.com/elastic/elasticsearch/issues/15484#issuecomment-165445628)

**Comment by jpountz** [comment]
Strong +1 to remove that parameter. If consumers of this API want random-access, they can build it in the client.

**Comment by colings86** [comment]
Discussed in FixItFriday and we agreed that we would like to remove this keyed option since it increases the surface area of the API and since the client will need to access all buckets anyway it is very easy to convert the response to a lookup map. 

We should however ensure that the key is always present in the bucket when it is presented as an array.

We also said that given that this might be a big breaking change for users we might want to deprecate this in 6.0 and remove it in 7.0. We would also like to know from the client authors, especially @Mpdreamz whether this change will affect them. Its also something that @epixa will probably be interested in following from the Kibana side.

**Comment by Mpdreamz** [comment]
@colings86 we do not rely on it. We in fact do not even support setting `keyed` on the request side. I'm assuming on purpose but its been a while :smile:

**Comment by HonzaKral** [comment]
This is a nice feature for `range` aggregation where you can label the different ranges ("right here", "walking distance", "driving distance", "far far away" / "cheap", "moderate", "pricey" / ...) without having to define this mapping (name <-> numerical range) in multiple places.

I don't see this useful for most aggregations but for `range` it was super useful to me in many cases.

**Comment by karmi** [comment]
Adding to what @HonzaKral said, which is really where the `keyed` response "shines", I think another, although less important aggregation is the [date histogram](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#_keyed_response_3), which allows for easy extraction of a date, or the [percentile aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-aggregation.html#_keyed_response), where the `keyed` parameter is even `true` by default...

**Comment by colings86** [comment]
Just to clarify, removing the `keyed` option will not affect the feature where you can set the keys for the range aggregation. It will just mean the buckets are always returned as an array of buckets (with your desired keys inside said buckets)

**Comment by HonzaKral** [comment]
Then the question remains what to do with `filters` aggregation using named filters where there is no defined order (objects in json have no order). Without a good solution there, hopefully as friendly as the current situation where you can pass a hash and get hash back or pas a list and get a list back, we will always have inconsistent responses in aggregations removing the primary motivation for this change.

**Comment by jpountz** [comment]
Maybe filters should always return an array like other bucket aggregations? We could try to maintain the same order as in the request. Also: removing the discuss label since everybody seems to agree we should remove the `keyed` option.

**Comment by colings86** [comment]
@elastic/es-search-aggs

**Comment by epixa** [comment]
@elastic/kibana-visualizations

**Comment by ppisljar** [comment]
i vote for removal as well, we will need to update some code on our side but in general i think it will just make it more consistent and easier to maintain.
