### ISSUE TITLE
Consult inner_hit score from function_score

### ISSUE THREAD

**Issue by VitorCaleffi** [elastic/elasticsearch#24623]
is it possible to consult another inner_hit's max_score from a function_score inside another inner_hit? If not, would be a good feature.

**Comment by markharwood** [comment]
Are you talking about use on `nested` docs or `parent_child`?
Either way there are two challenging aspects to this requirement:

1) Efficiently gathering and providing the related doc's values as added context to the scoring scripts
2) Complicating the function_score language to allow you to address the values in this multi-doc context.

On the face of it these seem to be huge technical hurdles and I'm not familiar with many use cases that would justify this. If we are to consider implementing such a solution I think you'd have to provide more details of 

* why this is an important feature and what business problems it helps you solve and
* proposals for the new JSON syntax you would hope to use as a client

**Comment by VitorCaleffi** [comment]
I'm currently using `parent_child`.

Its an idea to sort/order complex query.
Id use it as script:"_globalScore > 0 ? _globalScore + sortImprotance : 0"

**Comment by clintongormley** [comment]
> why this is an important feature and what business problems it helps you solve

**Comment by martijnvg** [comment]
@VitorCaleffi You like to access the max score of a nested inner hit (in case of parent-child-grandchild scenario) or an adjacent inner hit?

**Comment by VitorCaleffi** [comment]
@clintongormley I believe that this way we could make a better sorting on nested queries.

@martijnvg  Nested inner hit.

**Comment by clintongormley** [comment]
@VitorCaleffi I need some concrete example.  This is likely to be a complicated change, so I need to know that what you are trying to do makes sense, and there isn't another way to achieve the same thing.

**Comment by VitorCaleffi** [comment]
@clintongormley I have this situation: 
`
{
"hits":{
...,
_score: 1.23,
"inner_hits":{
"hit1":{
_score: 1.00,
...
}
"hit2":{
_score: 0.23,
...
}
}
}
}
`
I want, by example, from "hit2" know if the global score is bigget than 1, if so, increment X.
Example: Order by post views: (_globalScore < doc['viewsCount'].value) ? doc['viewsCount'].value : _globalScore

**Comment by clintongormley** [comment]
And by global score, you mean the score for the query for that doc?  Or what?

And why do you want to do this?

What you have shown is not a good way to include a signal like viewsCount.  You should never rely on an absolute score to have any meaning.  It depends entirely on which terms have been queried. Instead you want to apply a logarithmic function to viewsCount and add the result to the `_score`.

**Comment by colings86** [comment]
Closing due to no further feedback.
