### ISSUE TITLE
Maven POMs use wildcard exclusions, preventing the use of maven-enforcer-plugin in consuming projects

### ISSUE THREAD

**Issue by yrodiere** [elastic/elasticsearch#24626]
**Elasticsearch version**: 5.4.0

**Plugins installed**: N/A

**JVM version** (`java -version`): N/A

**OS version** (`uname -a` if on a Unix-like system): N/A

**Description of the problem including expected versus actual behavior**:

The POM for `org.elasticsearch.client:rest`, for instance, seems to now [use wildcard exclusions](https://repo1.maven.org/maven2/org/elasticsearch/client/rest/5.4.0/rest-5.4.0.pom) while [it previously didn't](https://repo1.maven.org/maven2/org/elasticsearch/client/rest/5.3.2/rest-5.3.2.pom).

Unfortunately, this feature (wildcard exclusions) is not very mature, and this causes problems to consuming projects.

In particular, the [maven-enforcer-plugin](http://maven.apache.org/enforcer/maven-enforcer-plugin/) is currently unable to cope with such exclusions ([MENFORCER-195](https://issues.apache.org/jira/browse/MENFORCER-195)) due to a missing feature in Maven itself ([MSHARED-339](https://issues.apache.org/jira/browse/MSHARED-339)).
The only workaround is to manage exclusions manually in consuming projects.

This may also affect other POMs, most notably the sniffer.

I know the problem is not caused by Elasticsearch itself, but considering [MSHARED-339](https://issues.apache.org/jira/browse/MSHARED-339) has been open for 3 years, I think we can safely assume it won't be solved anytime soon. Since the maven-enforcer-plugin is [not an exotic one](https://github.com/search?l=Maven+POM&q=maven-enforcer-plugin&type=Code&utf8=%E2%9C%93), maybe you could consider restoring the previous behavior of explicitly listing exclusions in your POM?

**Steps to reproduce**:

 1. Create a new Maven project
 2. Add a dependency to `org.elasticsearch.client:rest:5.4.0`
 3. Set up the maven-enforcer-plugin (version 1.4.1, the latest so far)
 4. Run `mvn clean compile`
 5. Watch the world come apart

**Comment by jasontedor** [comment]
I think this duplicates #24490?

**Comment by yrodiere** [comment]
Ah, sorry, I didn't see that one. Yes, the cause of #24490 seem to be the same. If the solution to #24490 is to get back to explicit exclusions, then it should solve this issue too :)

**Comment by jasontedor** [comment]
No worries, I'm going to close this issue as a duplicate.
