### ISSUE TITLE
[TEST] Vagrant packaging test fails

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/elasticsearch#24645]
**Link to failures**

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/1597/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/1598/console

**Reproduce**

Run on a machine with Vagrant installed: `gradle gradle :qa:vagrant:vagrantCentos6#packagingTest`

This reproduces consistently for me.

Running with `--stacktrace` I got: https://files.slack.com/files-pri/T0CUZ52US-F5CLSTVPU/stacktrace.java

**Comment by tlrx** [comment]
A new "examples" directory has been added in the `plugins` directory and it now appears in the list of plugins tested by the packaging tests. We should test this new plugin too and adapt the function that compares the list of plugins.

**Comment by ywelsch** [comment]
We've gotten many more build failures in the mean-time. I've disabled the packaging test on CentOS 6 using bd364c56a8, please revert that commit after fixing.

**Comment by nik9000** [comment]
I'll go deal with it.

**Comment by nik9000** [comment]
@rjernst just pinged me and took it before I got into it.

**Comment by rjernst** [comment]
I pushed https://github.com/elastic/elasticsearch/commit/f1fd5350c9920fdd07c4985a797a4b4906b3aa73
