### ISSUE TITLE
Clarify memory locking instructions

### ISSUE THREAD

**Issue by ctindel** [elastic/elasticsearch#24651]
This page lists a lot of options but doesn't actually prescribe what exactly to do:

https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html

I clarified with support that the official statement is this:

"The official recommendation is to turn off swap, but this isn't always possible depending on what your linux sysadmins allow.  Failing that, we require you to set bootstrap.memory_lock: true, and you can optionally also configure swappiness to reduce swapping."

Can we update/re-order this page to be more prescriptive with that order, while also showing how to do each of those as we do now?

**Comment by jasontedor** [comment]
I agree that disabling swapping should be listed first, I disagree with "requiring" memory lock, and I'm reluctant to order memory locking in front of minimizing swapping, the resolution to that one is "it depends", there's nuance here.

**Comment by ctindel** [comment]
@jasontedor I'm open to whatever nuance needs to be conveyed as long as it's an ordered priority of things they should do as opposed an unordered list of things they could do.

**Comment by jasontedor** [comment]
Closed by 4e21a33689cc494b3040607788cc041f30b2b7de
