### ISSUE TITLE
ES 5.4 - Bug in field collapsing combined with inner_hits and size > results of query

### ISSUE THREAD

**Issue by byronvoorbach** [elastic/elasticsearch#24672]
Hey all,

I noticed a strange exception when implementing the new collapse feature in Elasticsearch 5.4.
As soon as you choose a "from" in the query, higher than a number of hits that would be returned as a result of the query, the query doesn't get executed and the following exception occurs:

`"reason": "Validation Failed: 1: no requests added;"`

I created this [gist](https://gist.github.com/byronvoorbach/cd9cdf2bbcbede1684201468906ef117#file-collapse-inner_hits-bug-txt) to highlight the problem.

**Comment by jimczi** [comment]
Nice catch @byronvoorbach .
The exception is thrown when the search hits in the response are empty, also it seems that the bug has been introduced in 5.4 (since the gist works as expected in 5.3). I'll work on a fix.

**Comment by byronvoorbach** [comment]
Nice @jimczi !
