### ISSUE TITLE
No repositories for newer versions

### ISSUE THREAD

**Issue by qubusp** [elastic/elasticsearch#24673]
**Describe the feature**:

I want to have a simple good old style repository for the latest elastic and kibana for both apt and yum package managers. I have a server I am ready to offer to the project. It's a pain for idempotent automation solutions to constantly download packages. Just make it work.

**Comment by jasontedor** [comment]
This is not an effective feature request. It's not clear what you're asking for that we do not already provide. We provide apt and yum repositories for Elasticsearch and Kibana:
 - [apt for Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/deb.html)
 - [yum for Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/rpm.html)
 - [apt for Kibana](https://www.elastic.co/guide/en/kibana/5.4/deb.html)
 - [yum for Kibana](https://www.elastic.co/guide/en/kibana/5.4/rpm.html)
