### ISSUE TITLE
InstallPluginCommandTests.testPluginsDirMissing fails on 5.x branch

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#24693]
We had several unnoticed build failure on 5.x:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-intake/1173/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-intake/1195/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-intake/1201/console

The test failures are always the same:
````
Tests with failures:
  - org.elasticsearch.plugins.InstallPluginCommandTests.testPluginsDirMissing {p0=sun.nio.fs.LinuxFileSystem@6b67034 p1=org.elasticsearch.plugins.InstallPluginCommandTests$$Lambda$116/827084938@16267862}
  - org.elasticsearch.plugins.InstallPluginCommandTests.testPluginsDirMissing {p0=com.google.common.jimfs.JimfsFileSystem@453da22c p1=org.elasticsearch.plugins.InstallPluginCommandTests$1Parameter$$Lambda$115/1579526446@71248c21}
  - org.elasticsearch.plugins.InstallPluginCommandTests.testPluginsDirMissing {p0=com.google.common.jimfs.JimfsFileSystem@442675e1 p1=org.elasticsearch.plugins.InstallPluginCommandTests$1Parameter$$Lambda$115/1579526446@6166e06f}
  - org.elasticsearch.plugins.InstallPluginCommandTests.testPluginsDirMissing {p0=com.google.common.jimfs.JimfsFileSystem@49e202ad p1=org.elasticsearch.plugins.InstallPluginCommandTests$1Parameter$$Lambda$115/1579526446@1c72da34}
````

... and the build also fail to send the email notice.

**Comment by rjernst** [comment]
This was due to a broken backport of removing plugin dir leniency, but now I'm not sure why I was backporting that in the first place, so I have reverted the backport.

See https://github.com/elastic/elasticsearch/pull/24173
