### ISSUE TITLE
Arrays of geo_points mess up geohash_grid with geo_centroid

### ISSUE THREAD

**Issue by trevan** [elastic/elasticsearch#24694]
I noticed that the Kibana tilemap visualization using the geo_centroid feature would cause "incorrect" points to be displayed.  I think I tracked it down to a minimal test case:

Create and populate the test index
```
curl -H"Content-Type:application/json" -XPUT localhost:9200/geo_test -d '{"mappings": {"geo": {"properties": {"geohash-geo": {"type": "geo_point"}}}}}'
curl -H"Content-Type:application/json" -XPOST localhost:9200/geo_test/geo -d '{"geohash-geo" : [ "drt2v2d0pdue", "gc7x3w1cwgjy" ], "data": ["data"]}'
```

Request a geohash_grid aggregation with a geo_centroid sub metric:
```
curl -H"Content-Type:application/json" -XPOST 'localhost:9200/geo_test/_search?pretty' -d '{"size":0,"query":{"query_string":{"query":"*","analyze_wildcard":true}},"_source":{"excludes":[]},"aggs":{"2":{"geohash_grid":{"field":"geohash-geo","precision":2},"aggs":{"3":{"geo_centroid":{"field":"geohash-geo"}}}}}}'
```

The result is:
```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "2" : {
      "buckets" : [
        {
          "key" : "gc",
          "doc_count" : 1,
          "3" : {
            "location" : {
              "lat" : 47.83049770630896,
              "lon" : -38.696453254669905
            },
            "count" : 2
          }
        },
        {
          "key" : "dr",
          "doc_count" : 1,
          "3" : {
            "location" : {
              "lat" : 47.83049770630896,
              "lon" : -38.696453254669905
            },
            "count" : 2
          }
        }
      ]
    }
  }
}
```

It returned with two cells but both have the same geo_centroid location that is midway between the two cells.  I would have expected the location to be contained within the cells.

This was seen both in ES 2.3 and a 6.0 build from the end of April.

Edited to shrink and improve the test case.

**Comment by danielmitterdorfer** [comment]
@nknize Can you please have a look at this one?

**Comment by jpountz** [comment]
This is the expected behaviour as aggregations have a document-level granularity. Once a document enters a bucket, all its values can still be seen. A workaround could be to use `nested` documents so that each nested document only has one `geo_point` value and then put the geohash grid aggregation under a nested aggregation at search time.

I'm labelling this `discuss` as another option would be for us to make the geohash grid aggregation compute the centroid as well: this way it could only take into account points that fell into the bucket. But the trade-off is not obvious to me as I have not seen many use-cases for multivalued geo-points and computing centroids would make the geo hash grid more memory-intensive.

**Comment by trevan** [comment]
@jpountz, our use case is that we track communication between two different physical locations. So the document has a start and end location and we want to show where communication is happening.  We can show just the start or just the end (as we have separate fields to store those geo points) but if we want to see both start and end, we get these wrong locations.

**Comment by trevan** [comment]
@jpountz, since Kibana doesn't support nested documents, we can't use the nested document work around.

**Comment by trevan** [comment]
One possible work around would be to have the geohash_grid clamp the location to within the grid's bounding box.  That should look a little better.  Kibana could possibly do that on the client side.

**Comment by jpountz** [comment]
Closing: We don't want to make the geo centroid or geo hash grid aggregations more complex than they are today.
