### ISSUE TITLE
Use date math to compute a snapshot name

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#24705]
This came today at a OPS training.

Would be nice to support date math when creating a snapshot as [we do for indices](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/date-math-index-names.html):

```
# PUT /_snapshot/my_backup/<snapshot_-{now/d}>
PUT /_snapshot/my_backup/%3Csnapshot_-%7Bnow%2Fd%7D%3E
```

Thoughts?

**Comment by jasontedor** [comment]
This seems like an unnecessary complication to me, snapshots are taken *now*, doing date math to store a snapshot taken *now* with a date in the snapshot name different than now sounds like a recipe for confusion.

**Comment by dadoonet** [comment]
If you want to take a snapshot every day, you can simply call `PUT /_snapshot/my_backup/%3Csnapshot_-%7Bnow%2Fd%7D%3E` instead of calling every day:

* `PUT /_snapshot/my_backup/2017-05-15`
* `PUT /_snapshot/my_backup/2017-05-16`
* `PUT /_snapshot/my_backup/2017-05-17`

**Comment by jasontedor** [comment]
You can do this client side already with a simple shell script (or Curator) so I still think we don't need complexity here.

**Comment by jasontedor** [comment]
We discussed this in Fix-it-Friday. The functionality asked for here can indeed simply be achieved client side with *any* programming language being used to generate the requests, there's no need for this complexity in Elasticsearch.
