### ISSUE TITLE
`simple_query_string` unsupported field `auto_generate_phrase_queries`

### ISSUE THREAD

**Issue by yandooo** [elastic/elasticsearch#24710]
I google around and didn't find answer.

Any reasons why this property is unsupported in simple query string query?

The next step for me could be to check actual lucene code if simple query string supports that parameter...

thanks

**Comment by danielmitterdorfer** [comment]
Hi @yandooo, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!

**Comment by yandooo** [comment]
https://discuss.elastic.co/t/simple-query-string-unsupported-field-auto-generate-phrase-queries/85923
