### ISSUE TITLE
Grok processor: API to return the list of default patterns

### ISSUE THREAD

**Issue by suyograo** [elastic/elasticsearch#24725]
Is it possible to add an API that lists the [default patterns](https://github.com/elastic/elasticsearch/tree/master/modules/ingest-common/src/main/resources/patterns) loaded into the Grok processor? I would love to use this in the Grok debugger UI for an auto-complete feature. Maybe other users have a need to *list* patterns as well? :)

We don't have processor-specific APIs in ingest, but I was thinking something along the lines of: 

Request
```
GET _ingest/processor/grok/_patterns
```

Response

```
{
   "patterns": [
      "USERNAME":  "[a-zA-Z0-9._-]+",
      "POSINT": "\b(?:[1-9][0-9]*)\b",
      ...
   ]
}

```

@talevy @clintongormley thoughts?

**Comment by talevy** [comment]
@dadoonet I think it is fine that we are asked that... we'll probably respond that it is not planned :)

I don't have any reservations against this, glad to add it. may pave the way for the grok-discover api

**Comment by clintongormley** [comment]
It'd be nice if would make it somewhat more generic, eg:

    GET _ingest/processor/{name}

which returns processor config or something, where applicable.

**Comment by suyograo** [comment]
+1 to make it generic.
