### ISSUE TITLE
Thread falls into infinite loop when processing Indices query

### ISSUE THREAD

**Issue by kbialek** [elastic/elasticsearch#24735]
**Elasticsearch version**: 5.3.1, 5.3.2, 5.4.0

**Plugins installed**: None

**JVM version**: 1.8.0_121

**OS version**: Linux alan 4.8.0-41-generic #44-Ubuntu SMP Fri Mar 3 15:27:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Problem and actual behavior: Thread falls into infinte loop in org.elasticsearch.index.query.IndicesQueryBuilder#doRewrite when range query 'from' > max value of the field. 
Expected behavior: Query returns a result

**Steps to reproduce**:

 1. Create an index with mapping having a dateTime field
`PUT some_index_name
{
  "mappings": {
    "some_type": {
      "properties": {
        "someDateTimeField": {
          "type": "date" 
        }
      }
    }
  }
}`
 2. Index at least one document
`PUT some_index_name/some_type/1
{ "someDateTimeField": "2015-01-01T12:10:30Z" } `
 3. Send range query with value 'from' > max value of the field
`{
  "from": 0,
  "size": 20,
  "query": {
    "indices": {
      "indices": [
        "some_index_name"
      ],
      "query": {
        "range": {
          "someDateTimeField": {
            "from": "2017-04-21T22:00:00.000Z",
            "to": "2017-04-22T22:00:00.000Z",
            "include_lower": true,
            "include_upper": true
          }
        }
      }
    }
  }
}`

**Comment by clintongormley** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/24736
