### ISSUE TITLE
Has-parent and has-child scoring missing from <= 2.3 docs

### ISSUE THREAD

**Issue by jjfalling** [elastic/elasticsearch#24730]
https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-has-child-query.html#_sorting and https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-has-parent-query.html#_sorting_2 need to be be in 2.3 and earlier docs. 

Also, "score" : true does not work on 2.x, it needs to be "score_mode": "score" 
https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-has-parent-query.html#_sorting_2

**Comment by bleskes** [comment]
@martijnvg can you take a look please?

**Comment by martijnvg** [comment]
Updates the docs:
2.4: 3f56ed52b0e1738d6ec4b289b049a443bb740626
2.3: e48eaf50b04b78e16c0c048952f52fa5fbb9e2eb
2.2: c152738102dcddeca66458056641b6a6364fe43e
2.1: b710e20cac2cc85a32882c616a43726a837f854f
2.0: 72dfa64e0cf57b51612bcb57f1b58a843a883624
