### ISSUE TITLE
Test failure - invalid query syntax in new yml test

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#24734]
Bad match query syntax:  https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/1270/console

Reproduces 

	REPRODUCE WITH: gradle :modules:analysis-common:integTestRunner -Dtests.seed=1045551E25D9DAC7 -Dtests.class=org.elasticsearch.analysis.common.CommonAnalysisClientYamlTestSuiteIT -Dtests.method="test {yaml=search.query/10_match/match query with stacked stems}" -Dtests.security.manager=true -Dtests.locale=sq-AL -Dtests.timezone=Asia/Ujung_Pandang
		   "type" : "parsing_exception",
		   "reason" : "[match] query doesn't support multiple fields, found [text] and [operator]",
		   "stack_trace" : "ParsingException[[match] query doesn't support multiple fields, found [text] and [operator]]

Looks like bad query syntax as part of [this commit](https://github.com/elastic/elasticsearch/pull/24716/files#diff-89789304f1d1d6bb4441ea0642e8e48f):

**Comment by nik9000** [comment]
Ill have a look in a few hours. If this is breaking frequently please skip
the test.

I thought I ran all the tests before merging....

**Comment by nik9000** [comment]
Or not. I found some time this morning. These tests were only half written as is my usual test process. I half write them, let them fail, and fix them. But they didn't run so they didn't fail. I found the cause and I'll open a followup later today.
