### ISSUE TITLE
The "lowercase" tokenizer doesn't apply lowercasing to multi-term queries

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#24752]
While working on #24751 I wrote a test for the behavior that the `lowercase` tokenizer has with regards to multi-term queries. It [looks](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/indices/analysis/PreBuiltTokenizers.java#L92-L95) like it is supposed to lowercase them. But it doesn't seem to work because nothing I can see checks whether or not the tokenizer is a `MultiTermAwareComponent`.

I think this is a bug. @jpountz, what do you think?

**Comment by jpountz** [comment]
Agreed!

**Comment by romseygeek** [comment]
This is the same bug as #28894, which in turn is caused by https://issues.apache.org/jira/browse/LUCENE-8186
