### ISSUE TITLE
Elasticsearch 6.0.0-alpha1 - Lucene Snapshots not found

### ISSUE THREAD

**Issue by sksamuel** [elastic/elasticsearch#24760]
**Elasticsearch version**: 6.0.0-alpha1
**JVM version** (`java -version`): 1.8

**Description of the problem including expected versus actual behavior**:

Trying to build with 6.0.0-alpha1 cannot find lucene snapshots. I cannot see where the snapshot repos have been added to the poms for https://repo1.maven.org/maven2/org/elasticsearch/elasticsearch/6.0.0-alpha1/elasticsearch-6.0.0-alpha1.pom or https://repo1.maven.org/maven2/org/elasticsearch/client/transport/6.0.0-alpha1/transport-6.0.0-alpha1.pom.

I've tried a few variants of elasticsearch artifact repos based on other tickets in here, such as https://artifacts.elastic.co/lucenesnapshots/89f6d17, https://artifacts.elastic.co/lucene/89f6d17 and https://artifacts.elastic.co/maven to no avail.

**Comment by jasontedor** [comment]
It should be:

```
maven {
   url 'https://download.elasticsearch.org/lucenesnapshots/89f6d17'
}
```
