### ISSUE TITLE
Ensure Version#CURRENT is not `_UNRELEASED` if we are on a release branch

### ISSUE THREAD

**Issue by s1monw** [elastic/elasticsearch#24768]
we should make sure that the `Version#CURRENT` is not suffixed with `_UNRELEASED`  if we are on a release branch. I assume we should do this in gradle @rjernst @nik9000 ?

**Comment by nik9000** [comment]
#24798 does this sort of automatically.

**Comment by s1monw** [comment]
++ @nik9000 I will assign this to you then and remove the adoptme label
