### ISSUE TITLE
ScriptServiceTests.testFineGrainedSettings fails with deprecation warnings

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#24769]
build URL: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/988/consoleFull

reproduce command (can reproduce locally):
```
gradle :core:test -Dtests.seed=C218DC1C838AA1B4 -Dtests.class=org.elasticsearch.script.ScriptServiceTests -Dtests.method="testFineGrainedSettings" -Dtests.security.manager=true -Dtests.locale=pl -Dtests.timezone=BST
```

Failure stack trace:
```
FAILURE 0.27s | ScriptServiceTests.testFineGrainedSettings <<< FAILURES!
   > Throwable #1: java.lang.AssertionError
   >    at __randomizedtesting.SeedInfo.seed([C218DC1C838AA1B4:784B090C4509442]:0)
   >    at org.elasticsearch.test.ESTestCase.assertWarnings(ESTestCase.java:337)
   >    at org.elasticsearch.test.ESTestCase.assertSettingDeprecationsAndWarnings(ESTestCase.java:320)
   >    at org.elasticsearch.script.ScriptServiceTests.testFineGrainedSettings(ScriptServiceTests.java:325)
   >    at java.lang.Thread.run(Thread.java:745)
```

It looks like the test is choosing to set the `script.inline` setting which has been deprecated. Before the above error the build logs the following a number of times:
```
[2017-05-18T14:07:59,316][WARN ][o.e.d.c.s.Setting        ] [script.inline] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version.
```

**Comment by colings86** [comment]
@rjernst I assigned this to you as it looks like you've been deprecating script stuff recently, please reassign if you are not the right person for this.

**Comment by jdconrad** [comment]
This is about to go away on master as I'll be removing the settings likely today.  May still happen in 5.x, so I'll try to take a look there.

**Comment by rjernst** [comment]
This hasn't reoccurred in over a week on 5.x, and the test is gone in master. So I am closing for now.
