### ISSUE TITLE
setting default similarity of index to default makes index unusable

### ISSUE THREAD

**Issue by grmblfrz** [elastic/elasticsearch#24770]
**Elasticsearch version**: 5.4.0

**Plugins installed**: [```analysis-icu, bundle, scoring-scripts (locally developed)```]

**JVM version** (`java -version`):
```
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-1~bpo8+1-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```
**OS version** (`uname -a` if on a Unix-like system):
```Linux 3.10.0 (in docker container)```

**Description of the problem including expected versus actual behavior**:
I accidently set the default similarity of an index to 'default'. Now its impossible to open the index or change the faulty setting. It should be possible to recover from this mistake.
**Steps to reproduce**:
```
#!/bin/bash

curl -XDELETE http://localhost:9200/similaritybug
curl -XPUT http://localhost:9200/similaritybug    
curl -XPOST http://localhost:9200/similaritybug/_close
curl -XPUT http://localhost:9200/similaritybug/_settings -d '{ 
  "settings": { 
    "index": { 
      "similarity": { 
        "default": { 
          "type": "default" 
        } 
      } 
    } 
  } 
}'
curl -XPOST http://localhost:9200/similaritybug/_open
 
curl -XPOST http://localhost:9200/similaritybug/_close

curl -XPUT http://localhost:9200/similaritybug/_settings -d '{ 
  "settings": { 
    "index": { 
      "similarity": { 
        "default": { 
          "type": "BM25" 
        } 
      } 
    } 
  } 
}'

curl -XPOST http://localhost:9200/similaritybug/_open
```

**Comment by jimczi** [comment]
@grmblfrz this is a bug indeed.
The settings update should have failed the first time. This is fixed in 5.4.1 (the next bugfix release of 5.4):
https://github.com/elastic/elasticsearch/pull/24487
