### ISSUE TITLE
Terms aggregation of Keyword type and sort alphabetically (case insensitive)

### ISSUE THREAD

**Issue by giocaputo** [elastic/elasticsearch#24773]
Can i aggregate (terms aggregation ) a field with a keyword type  and sorting by text case insensitive?

Elasticsearch version: 5.2

**Comment by cbuescher** [comment]
I'm afraid Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions. Can I ask you to ask your question there again? Somebody will be able to help.

**Comment by giocaputo** [comment]
@cbuescher  This should be a feature request
