### ISSUE TITLE
Dynamic field sort and search_after

### ISSUE THREAD

**Issue by flyweight** [elastic/elasticsearch#24774]
**Describe the feature**:

In hits when using dynamic fields and sorting by one of them, the sort property contains "Infinity" or "-Infinity" which doesn't work properly with `search_after` for pagination.

**Elasticsearch version**: 5.2.2

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
Linux 3.13.0-34-generic #60-Ubuntu SMP Wed Aug 13 15:45:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Sorting against a field that is a dynamic mapping and not populated for all results returns a sort per hit that could contain "Infinity" or "-Infinity".  This is problematic when attempting to get the next page.

This is my post in the forums and an image that shows the problem:

https://discuss.elastic.co/t/sort-by-dynamic-fields-and-use-search-after/86275
http://imgur.com/a/MLi3P

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create an index with a dynamic field mapping
 2. Add some documents that contain a dynamic field and some that do not
 3. Issue a match all query and sort by the dynamic field that was created in step 2 and the UID.
 4. In the last hits, you will see that the `sort` property contains "Infinity" in the first position
 5. Use that `sort` value as the `search_after` value to fetch the next page of results

**Provide logs (if relevant)**:

**Comment by jimczi** [comment]
We use `Infinity` (or `-Infinity`)  for `float` and `double` where the value is missing in the document. `Infinity` is the biggest possible value so we use it to sort the document without value for the field last. You can change this behavior using the `missing` attribute in the sort definition:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_missing_values
It works as expected with `search_after` as shown in the following recreation (tested with 5.x):

````
PUT t
{
	"mappings": {
		"t": {
			"properties": {
				"number": {
					"type": "double"
				}
			}
		}
	}
}

// Add two documents with no value for the field
PUT t/t/1
{
}

PUT t/t/2
{
}

GET t/t/_search
{
	"sort": [
		"number",
		"_uid"
	],
	"search_after": ["Infinity", "t#1"]
}

// the query returns the document with id 2
response:
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": null,
    "hits": [
      {
        "_index": "t",
        "_type": "t",
        "_id": "2",
        "_score": null,
        "_source": {},
        "sort": [
          "Infinity",
          "t#2"
        ]
      }
    ]
  }
}
````

In the example you've linked you're asking for `50` results but the query has only `33` hits (total) so the first page contains all the documents that match the query.
