### ISSUE TITLE
Feature request: when create Index, transport the translog to the not primary shard in async mode

### ISSUE THREAD

**Issue by chixuan777** [elastic/elasticsearch#24783]
we allow the not primary shard lose some data.(low consistency requirment)
Can we config something to let the bulk request just return success after the primary shard write successful, and there will be another thread to transport the data to the replications in async mode?

**Comment by jasontedor** [comment]
No, async replication would violate too many assumptions underlying our system (for example, it would completely break synced flush), and we are simply not going to permit something so unsafe into our system.
