### ISSUE TITLE
Refreshes caused by realtime gets are not counted in the refresh stats

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#24806]
I was investigating something else and it *looks* like refreshes caused by realtime gets do not get factored into the refresh cycle. I was just looking around the code and that is how it looked. This reproduces the problem, I think:

```
DELETE /test

PUT /test
{
  "settings": {
    "refresh_interval": -1
  }
}

PUT /test/doc/1
{
  "test": "TEST"
}

GET /test/doc/1

GET /test/_stats/refresh
```

The refresh stats should show a refresh. Actually, it might be useful to track just how many of these we're getting in their own stat either on their own or in addition to refresh stats because many of them is indicative of a problem.

**Comment by bleskes** [comment]
> The refresh stats should show a refresh.

+1

>  Actually, it might be useful to track just how many of these we're getting in their own stat either on their own or in addition to refresh stats because many of them is indicative of a problem.

I wonder if we need this? What we really care about is how many refreshes happen per sec. Doesn't matter what caused them (and it's very easy to see what the refresh interval settings is).

**Comment by jasontedor** [comment]
I agree, there is a bug here. The problem is the stats tracking is done for refresh calls that go through index shard, but not for refresh calls decided inside the engine.

> Actually, it might be useful to track just how many of these we're getting in their own stat either on their own or in addition to refresh stats because many of them is indicative of a problem.

I do not think that we need this. A refresh is a refresh.

**Comment by nik9000** [comment]
> I do not think that we need this. A refresh is a refresh.

I'm not sure we need this either. If we had this then we could point to it and say "there, that is why you have so many refreshes" without having to dig deeply. It'd be an easy thing to tell people to check.
