### ISSUE TITLE
_rollover api does not support date math

### ISSUE THREAD

**Issue by danwhitacre** [elastic/elasticsearch#24803]
**Elasticsearch version**: 5.1.1

**Plugins installed**: n/a

**JVM version** (`java -version`): 1.8.0

**OS version** (`uname -a` if on a Unix-like system): n/a

**Description of the problem including expected versus actual behavior**:
#### Expected
According to the docs here (https://www.elastic.co/guide/en/elasticsearch/reference/5.1/indices-rollover-index.html#_using_date_math_with_the_rolllover_api), the `_rollover` api supports date math, in addition to incrementing the trailing number of the index. 

#### Actual
I have an index `test-2017.05.18-1` with an alias `test-w`. When calling the rollover api with `max_age: 0d`, my new index associated with the test-w alias is `test-2017.05.18-000002`. It seems to indicate that date math should be applied as well, to create an index `test-2017.05.19-000002`, but that doesn't seem to be the case. Today's date is `5-19-2017`.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

Following the steps in the doc linked above will easily reproduce. Adapting to what I did here for ease:
```
PUT /%3Ctest-%7Bnow%2Fd%7D-1%3E 
{
  "aliases": {
    "test-w": {}
  }
}

# Created index test-2017.05.18-1 with alias test-w

# Wait for a day to pass

POST /test-w/_rollover 
{
  "conditions": {
    "max_age": "0d"
  }
}

# Created index test-2017.05.18-000002 with alias test-w
# Expected test-2017.05.19-000002
```

**Provide logs (if relevant)**:
n/a

**Comment by danwhitacre** [comment]
This might just be a doc issue, if incrementing the date is not supported through the rollover api.

**Comment by ywelsch** [comment]
I cannot reproduce this using ES v5.1.1. My steps:

```
# SET my system clock back 1 day (i.e. to `2017.05.21`) and start Elasticsearch

PUT /%3Ctest-%7Bnow%2Fd%7D-1%3E 
{
  "aliases": {
    "test-w": {}
  }
}

# readjust system clock back to `2017.05.22`

POST /test-w/_rollover 
{
  "conditions": {
    "max_age": "0d"
  }
}
```

which gives me:

```
{
  "old_index": "test-2017.05.21-1",
  "new_index": "test-2017.05.22-000002",
  "rolled_over": true,
  "dry_run": false,
  "acknowledged": true,
  "shards_acknowledged": true,
  "conditions": {
    "[max_age: 0s]": true
  }
}
```

Can you provide the output of `GET /test-2017.05.21-1/_settings` and `GET /test-2017.05.18-000002/_settings`?

**Comment by danwhitacre** [comment]
@ywelsch So I tore down that cluster over the weekend so I don't have access to those indices anymore. Oddly enough though, when I tried to reproduce it right now, it rolled over the date just fine. Not sure what I did differently last week.

**Comment by danwhitacre** [comment]
Closing since I can't reproduce now.

**Comment by ywelsch** [comment]
I wonder if it had to do with timezones. By default we assume UTC to calculate date math expressions.

**Comment by danwhitacre** [comment]
Hmm I don't think it was that. I think I didn't do exactly what the doc asked. It seems I actually created the index with the explicit date rather than using date math to create the index. Then it doesn't rollover the date. Is that expected?

Like so:
```
PUT /blah-2017.05.22-1
{
  "aliases": {
    "blah-w": {}
  }
}

# set system clock forward one day

POST /blah-w/_rollover
{
  "conditions": {
    "max_age": "0d"
  }
}
```
yields
```
{
  "old_index":"blah-2017.05.22-1",
  "new_index":"blah-2017.05.22-000002",
  "rolled_over":true,
  "dry_run":false,
  "acknowledged":true,
  "shards_acknowledged":true,
  "conditions":{
    "[max_age: 0s]":true
  }
}
```

**Comment by ywelsch** [comment]
> It seems I actually created the index with the explicit date rather than using date math to create the index. Then it doesn't rollover the date. Is that expected?

Yes, that does not work - that's why I asked for the index settings. When you create an index with a date math expression in it, we store the original name in a special setting `index.provided_name`. This allows us to use the correct date math expression when doing the rollover. If you manually create an index that misses this information, we cannot guess what the date math expression for the rollover index should be.

**Comment by danwhitacre** [comment]
I see. Thanks. Last time I try to take a shortcut. :)
