### ISSUE TITLE
Dashboard Reporting Generation URL

### ISSUE THREAD

**Issue by EngineersRock** [elastic/elasticsearch#24811]
Elasticsearch version:
5.2.2
Plugins installed: [x-pack, cabana 5.2.2, timelion]

JVM version (java -version):
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

OS version (uname -a if on a Unix-like system):
macOS Sierra 10.12.3

Darwin ws-reporting.apple.com 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

Description of the problem including expected versus actual behavior:
When I try to use the generation URL under the dashboard reporting tab, it takes me to a page with this error on it.

{"statusCode":405,"error":"Method Not Allowed","message":"GET is not allowed"}

I was expecting to see the Dashboard. Here is the URL that is being generated.
http://ws-reporting.apple.com:5601/api/reporting/generate/dashboard/7705e250-0b6b-11e7-b5a1-dd27cf84fda9?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(filters:!(),options:(darkTheme:!f),panels:!((col:9,id:e8f620a0-0b6b-11e7-8a14-33e882567dc6,panelIndex:2,row:1,size_x:2,size_y:2,type:visualization),(col:11,id:db7eb590-0b6b-11e7-b5a1-dd27cf84fda9,panelIndex:3,row:1,size_x:2,size_y:2,type:visualization),(col:9,id:%275fe47270-0b6c-11e7-92ba-2d557a110365%27,panelIndex:4,row:3,size_x:4,size_y:5,type:visualization),(col:1,id:%2725080be0-0b6b-11e7-950a-691f7619af52%27,panelIndex:6,row:1,size_x:8,size_y:7,type:visualization),(col:1,id:%273b8c1480-18b6-11e7-9fea-497b41cb2ac0%27,panelIndex:7,row:22,size_x:6,size_y:6,type:visualization),(col:7,id:%2726cf7050-2162-11e7-b14e-23b21dc79986%27,panelIndex:9,row:8,size_x:6,size_y:6,type:visualization),(col:1,id:%2796ea0ed0-2163-11e7-b14e-23b21dc79986%27,panelIndex:10,row:18,size_x:6,size_y:4,type:visualization),(col:1,id:aebafd50-21ca-11e7-974d-7b3235687fbd,panelIndex:11,row:8,size_x:6,size_y:6,type:visualization),(col:7,id:%27052ca1b0-39be-11e7-aa12-291d1256d4a9%27,panelIndex:13,row:18,size_x:6,size_y:4,type:visualization),(col:1,id:%27897b51d0-3b37-11e7-a973-d1ba62d85507%27,panelIndex:17,row:14,size_x:6,size_y:4,type:visualization),(col:7,id:%2707ef2550-3b38-11e7-a973-d1ba62d85507%27,panelIndex:18,row:14,size_x:6,size_y:4,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:%27*%27)),title:%27Charon+Dashboard%27,uiState:(P-10:(vis:(legendOpen:!f)),P-11:(vis:(params:(sort:(columnIndex:3,direction:asc)))),P-13:(vis:(legendOpen:!f)),P-17:(vis:(legendOpen:!f)),P-18:(vis:(legendOpen:!f)),P-4:(spy:(mode:(fill:!f,name:!n)),vis:(legendOpen:!f)),P-6:(vis:(params:(sort:(columnIndex:2,direction:desc)))),P-7:(vis:(params:(sort:(columnIndex:4,direction:desc)))),P-9:(vis:(params:(sort:(columnIndex:1,direction:asc))))))

Steps to reproduce:
1) Create and save dashboard
2) Open reporting tab and copy the Generation URL
3) Try to open the copied URL

I am seeing this issue for all of our dashboards and indexes.

Please include a minimal but complete recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc. The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

**Comment by jasontedor** [comment]
This should be on the [Kibana repository](https://github.com/elastic/kibana).
