### ISSUE TITLE
Document backwards-incompatible change for GeoDistance queries (5.3 breaking change/incompatibility)

### ISSUE THREAD

**Issue by astral303** [elastic/elasticsearch#24816]
When running a 5.2.2 client against a 5.3 or 5.4 server, when GeoDistance queries with default settings are sent, the server responds with an error:

Caused by: java.io.IOException: Unknown GeoDistance ordinal [3]

This regression was introduced in 5.3 and on in this commit:

https://github.com/elastic/elasticsearch/commit/3a2c628fabe2b30545cd16afc9227542b24bfcfe

That commit changed the ordinals of the Enums in a backwards-incompatible way.

This should be documented in the breaking changes for 5.3. This also breaks the promise of 5.x clients being able to talk to 5.x servers compatibly (note that the 5.2.2 client is not using any new features here).

**Comment by jpountz** [comment]
Hmm I think we should actually fix those, the break was not intended.

**Comment by s1monw** [comment]
++ @jpountz

**Comment by nknize** [comment]
closed with ffec0c6
