### ISSUE TITLE
how to combine nested query with bool queries?

### ISSUE THREAD

**Issue by maralbe** [elastic/elasticsearch#24819]
**Describe the feature**:
i have a mapping like this : 
`

     'candidate_cvs' => [
            'properties' => [
        'folder_applications' => [
            'type' => 'nested',
            "properties" => [
                "created_at" => [
                    "type" => "date"
                ],
                "employer_folder_id" => [
                    "type" => "long"
                ],
                "folder" => [
                    "type" => "nested",
                    "properties" => [
                        "employer_id" => [
                           "type" => "long"
                           ],
                           "id" => [
                                "type" => "long"
                            ]
                        ]
                    ],
                    "hire_stage_id" => [
                       "type" => "long"
                    ],
                    "is_applied" => [
                        "type" => "long"
                    ],
                    "status_id" => [
                        "type" => "long"
                    ]
               ]
            ],
        ]
    ]

so i want to search inside my type, using nested query and bool query.. this is the query that i wrote: `

    "query" => [
                "bool" => [
                    "must" => [
                        
                        "query" => [
                            "nested" => [
                                "path" => "folder_applications",
                                "query" => [
                                    "nested" => [
                                        "path" => "folder_applications.folder",
                                        "query" => [
                                            "match" => ["folder_applications.folder.id" => 7937]
                                        ]
                                    ],

                                    [
                                        "match" => ["folder_applications.status_id" => 141]
                                    ]
                                ]
                            ]
                        ]

                    ],
                    "must_not" => $this->mustNot,
                    "filter" => $this->filter
                ]
            ],
`

but its get me error.. i dont know how to combine my queries..
no [query] registered for [query]

**Comment by ywelsch** [comment]
Please ask questions like these on our [forum](https://discuss.elastic.co). There's an active community there that should be able to help get an answer to your question. GitHub should only be used for verified bug reports and feature requests.
