### ISSUE TITLE
Link fields broken

### ISSUE THREAD

**Issue by EngineersRock** [elastic/elasticsearch#24812]
Elasticsearch version:
5.2.2
Plugins installed: [x-pack, cabana 5.2.2, timelion]

JVM version (java -version):
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

OS version (uname -a if on a Unix-like system):
macOS Sierra 10.12.3

Darwin ws-reporting.apple.com 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

Description of the problem including expected versus actual behavior:
Every document in my index has a link field that points to another website with the source data. Not all of these links are unique and none of them are working. I have checked the documents in the index and I have verified the link field has the correct link. Unfortunately, instead of providing the link from the document all links are pointing to http://ws-reporting.apple.com:5601/app/Link which shows a page with the following error.

{"statusCode":404,"error":"Not Found","message":"Unknown app Link"}

Steps to reproduce:
1) create an index with a link field with a format similar to this. https://some-domain.com/#/stats/TypeOfStats/2/4149
2) create a data table with a link column. 
3) click on the link

**Comment by jasontedor** [comment]
This should be on the Kibana repository.
