### ISSUE TITLE
Dashboard links don't work in iMessage

### ISSUE THREAD

**Issue by EngineersRock** [elastic/elasticsearch#24813]
Elasticsearch version:
5.2.2
Plugins installed: [x-pack, cabana 5.2.2, timelion]

JVM version (java -version):
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

OS version (uname -a if on a Unix-like system):
macOS Sierra 10.12.3

Darwin ws-reporting.apple.com 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

Description of the problem including expected versus actual behavior:
Links to dashboards are very messy and don't work at all in iMessage.
Here is what the link to our dashboard looks like.
http://ws-reporting.apple.com:5601/app/kibana#/dashboard/7705e250-0b6b-11e7-b5a1-dd27cf84fda9?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(filters:!(),options:(darkTheme:!f),panels:!((col:9,id:e8f620a0-0b6b-11e7-8a14-33e882567dc6,panelIndex:2,row:1,size_x:2,size_y:2,type:visualization),(col:11,id:db7eb590-0b6b-11e7-b5a1-dd27cf84fda9,panelIndex:3,row:1,size_x:2,size_y:2,type:visualization),(col:9,id:'5fe47270-0b6c-11e7-92ba-2d557a110365',panelIndex:4,row:3,size_x:4,size_y:5,type:visualization),(col:1,id:'25080be0-0b6b-11e7-950a-691f7619af52',panelIndex:6,row:1,size_x:8,size_y:7,type:visualization),(col:1,id:'3b8c1480-18b6-11e7-9fea-497b41cb2ac0',panelIndex:7,row:22,size_x:6,size_y:6,type:visualization),(col:7,id:'26cf7050-2162-11e7-b14e-23b21dc79986',panelIndex:9,row:8,size_x:6,size_y:6,type:visualization),(col:1,id:'96ea0ed0-2163-11e7-b14e-23b21dc79986',panelIndex:10,row:18,size_x:6,size_y:4,type:visualization),(col:1,id:aebafd50-21ca-11e7-974d-7b3235687fbd,panelIndex:11,row:8,size_x:6,size_y:6,type:visualization),(col:7,id:'052ca1b0-39be-11e7-aa12-291d1256d4a9',panelIndex:13,row:18,size_x:6,size_y:4,type:visualization),(col:1,id:'897b51d0-3b37-11e7-a973-d1ba62d85507',panelIndex:17,row:14,size_x:6,size_y:4,type:visualization),(col:7,id:'07ef2550-3b38-11e7-a973-d1ba62d85507',panelIndex:18,row:14,size_x:6,size_y:4,type:visualization)),query:(query_string:(analyze_wildcard:!t,query:'*')),title:'Charon%20Dashboard',uiState:(P-10:(vis:(legendOpen:!f)),P-11:(vis:(params:(sort:(columnIndex:3,direction:asc)))),P-13:(vis:(legendOpen:!f)),P-17:(vis:(legendOpen:!f)),P-18:(vis:(legendOpen:!f)),P-4:(spy:(mode:(fill:!f,name:!n)),vis:(legendOpen:!f)),P-6:(vis:(params:(sort:(columnIndex:2,direction:desc)))),P-7:(vis:(params:(sort:(columnIndex:4,direction:desc)))),P-9:(vis:(params:(sort:(columnIndex:1,direction:asc))))))

Attached is a screenshot of what this looks like when sent via text 

Is it possible to minimize or clean up these URLs? It makes sharing Dashboards and information annoyingly difficult as a large amount of our teams communication happens via iMessage.
![screen shot 2017-05-19 at 3 35 06 pm](https://cloud.githubusercontent.com/assets/4793099/26269361/c3d4c74a-3ca8-11e7-9798-6ea5948254ee.png)

Steps to reproduce:
Copy and paste dashboard link into iMessage and then send it.

**Comment by jasontedor** [comment]
This should be on the Kibana repository.
