### ISSUE TITLE
Feature Request: Allow GeoJson format for geo_point

### ISSUE THREAD

**Issue by lukas-gitl** [elastic/elasticsearch#24814]
We are using PostGIS `ST_AsGeoJSON` to convert our data from PostgreSQL and then inserting it into ES. It's really inconvenient that the GeoJson format is not supported by ES, since us prevents us to do the conversion generically.

Related issue: https://github.com/elastic/elasticsearch/issues/11420

**Comment by clintongormley** [comment]
Hi @lukas-gitl 

We're not going to be able to move geopoints to accept geojson.  However, we hope to add a new `geo` field type in 6.x which will unify points and shapes, and should hopefully support a number of different formats, including geojson.
