### ISSUE TITLE
gradle upload error

### ISSUE THREAD

**Issue by walleiptXX** [elastic/elasticsearch#24826]
**Describe the feature**:
FAILURE: Build failed with an exception.

* What went wrong:
Task 'upload' not found in root project 'elasticsearch'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Elasticsearch version**:V_6_0_0_alpha1

**Plugins installed**: []

**JVM version** (`java -version`):jdk 1.8

**OS version** (`uname -a` if on a Unix-like system):window 7

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 

 1.gradle upload

**Comment by ywelsch** [comment]
What should the expected outcome be? I don't understand what you're trying to do.

`gradle someRandomTaskNameThatDoesNotExist` will give the same error.

**Comment by walleiptXX** [comment]
I want package elasticsearch to nexus

**Comment by rjernst** [comment]
@walleiptXX we use an external project to do publication of our artifacts to nexus. In the future, please ask questions like this [on our forum](https://discuss.elastic.co/).

**Comment by walleiptXX** [comment]
Ok ,3Q,external project ?

**Comment by jasontedor** [comment]
To clarify, it's an external project to this repository but internal to us.

**Comment by walleiptXX** [comment]
Is there any other way？

**Comment by rjernst** [comment]
@walleiptXX If you want help with whatever you are trying to accomplish, please open a thread on [the forum](https://discuss.elastic.co/).
