### ISSUE TITLE
Clarify transport communication requirements for cross cluster search

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#24836]
It will be nice to clarify in the cross cluster search documentation (https://www.elastic.co/guide/en/elasticsearch/reference/5.4/modules-cross-cluster-search.html#modules-cross-cluster-search) that even though the user will only have to specify a subset of the remote cluster nodes for seeding, CCS client node(s) will still require bidirectional communication over the transport port with all the nodes in the remote cluster (not just the seeding nodes).

**Comment by s1monw** [comment]
> CCS client node(s) will still require bidirectional communication over the transport port with all the nodes in the remote cluster (not just the seeding nodes).

this is not true. The CSS client node does only require unidirectional (CSS client connects to remote cluster only) communication to the nodes that are eligible. By default all nodes are eligible unless you use a tag to filter them.

**Comment by javanna** [comment]
@ppf2 I am looking at clarifying this but I find it already quite clear in our docs: 

> Each remote cluster is referenced by a name and a list of seed nodes.
Those seed nodes are used to discover nodes in the remote cluster which are eligible as _gateway nodes_.

This means that we don't only connect to the seed nodes, which is also suggested by the "seed" naming. As Simon said the connections will be uni-directional only from the nodes belonging to the cluster where the remote clusters are registered.

What would you suggest to clarify this further?

**Comment by ppf2** [comment]
Thanks @s1monw! I can confirm (sorry, had some issues with my firewall rules earlier when testing :)) the uni-directional communication (ccs -> gateway node). 

@javanna I will suggest adding a note/paragraph that includes:

* Clarifying the unidirectional communication between CCS and its identified gateway nodes, i.e. call out that it does not only connect to the seed nodes.
* Clarifying that all nodes in the remote clusters by default are eligible to be gateway nodes so it will try to connect to them (and from here, refer users to the settings portion for the filtering attributes they can add)

This will be helpful for we are likely going to get questions from admins on what ports to open when setting up CCS.  Thx!

**Comment by s1monw** [comment]
++ @javanna can you take care of this?
