### ISSUE TITLE
recovery index from files

### ISSUE THREAD

**Issue by culiangfanzi** [elastic/elasticsearch#24838]
How can I recovery index from files?
es version: 2.4.x
I have a crashed es node,  and the original host cannot start anymore, what should i do to restore the kibana index from these files?

/tmp/kibana_es/0/index/
├── segments_rn
├── write.lock
├── _wz_4.liv
├── _wz.fdt
├── _wz.fdx
├── _wz.fnm
├── _wz_Lucene50_0.doc
├── _wz_Lucene50_0.pos
├── _wz_Lucene50_0.tim
├── _wz_Lucene50_0.tip
├── _wz_Lucene54_0.dvd
├── _wz_Lucene54_0.dvm
├── _wz.nvd
├── _wz.nvm
├── _wz.si
├── _x0.cfe
├── _x0.cfs
├── _x0.si
├── _xq.cfe
├── _xq.cfs
├── _xq.si
├── _xx.cfe
├── _xx.cfs
├── _xx.si
├── _y8.cfe
├── _y8.cfs
└── _y8.si

**Comment by javanna** [comment]
hi @culiangfanzi, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!
