### ISSUE TITLE
Index not found with 'bad-request' as missing index

### ISSUE THREAD

**Issue by cp2587** [elastic/elasticsearch#24840]
__Elasticsearch version__: 
5.2.0

__JVM version (`java -version`)__: 
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-1~bpo8+1-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

__OS version (`uname -a` if on a Unix-like system)__: 
debian 4.8.6-x86_64-linode78

__Description of the problem including expected versus actual behavior__:
When executing a count query over more than 156 indexes, i get the following error

```json
{"status": 404, "error": {"index_uuid": "_na_", "index": "bad-request", "resource.type": "index_or_alias", "root_cause": [{"index_uuid": "_na_", "index": "bad-request", "resource.type": "index_or_alias", "resource.id": "bad-request", "reason": "no such index", "type": "index_not_found_exception"}], "reason": "no such index", "type": "index_not_found_exception", "resource.id": "bad-request"}}
```

I actually have no index missing in the 157 i ask for (also the error does not return a missing index name as it should be). 

__Steps to reproduce__:
run a count query over more than 156 indexes

__Provide logs (if relevant)__:
no logs on the client node

**Comment by jasontedor** [comment]
Duplicates #23034, closed by #23153, first fixed in 5.3.0.
