### ISSUE TITLE
Issue with Installation of ES

### ISSUE THREAD

**Issue by shyamalaponnada** [elastic/elasticsearch#24848]
i have installed 5-alpha version earlier and i uninstalled that version by installing 2.4.5.here the issue unable to run the ES and when i am trying to open the elasticsearch.yml file, i am getting .yml file of 5 alpha vesrion not the latest installed version.

Could you please suggest what would be reason and how can i fix

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
