### ISSUE TITLE
Multiple levels of field collapse

### ISSUE THREAD

**Issue by eskibars** [elastic/elasticsearch#24855]
**Describe the feature**:
Currently, we support 1 level of field collapse + inner hits (https://www.elastic.co/guide/en/elasticsearch/reference/5.4/search-request-collapse.html#_expand_collapse_results).  However, some users need to collapse multiple levels (while still providing features provided by field collapse, e.g. pagination), e.g. to simply provide the top item for 2 tiers of collapsing.  For those users, they  have a few options:

1. Ignore the pagination requirement and do terms+terms+top_hits (which will be fine for some users)
2. In a single query, ask for a very large `inner_hits` `size` and then reduce the set client-side
3. Perform multiple queries: 1 for the first collapse level and then iterate through these for secondary queries

When 1 is not an option for business purposes, this leaves you with options 2 and 3.  2 is a fairly abusive/expensive way to solve it when you're looking for just the top result under each of the top-level collapse.  3 adds a lot of client code as well as round trips (which increase overall query latency).

Unfortunately, opening up multiple levels also opens the query up for abuse in different ways (asking for high depth)

I wanted to open up for discussion the possibility of having multiple levels of field collapse, even if there were additional restrictions (e.g. only 2 levels, only can return a much smaller result set from the second level, etc)

**Comment by emmerich** [comment]
Just a quick note that I myself came across this requirement, and decided to approach it with the terms+terms+top_hits approach. With 7000 documents returned by the query before aggregations, I found that the performance tripled when I added the final top_hits aggregation. (terms+top_hits was fine, terms+terms was fine, terms+terms+top_hits was awful).

I raised this as a forum post here: https://discuss.elastic.co/t/top-hits-performance-inside-2-levels-of-terms-aggregations/92266

But it's perhaps useful to see it here too.

**Comment by tarunramsinghani** [comment]
+1

We are also using term->terms->TopHits to solve a problem, where multiple level of collapse with pagination will be very useful. But the question is would it be better to have Parent->Child Structure to solve this problem performance wise instead of having N-level nesting for collapse ?

**Comment by andyb-elastic** [comment]
@elastic/es-search-aggs

**Comment by stojan-jovic** [comment]
Wondering why did we give up from approach introduced in #31557? Are there plans to support something like that in the near future?
