### ISSUE TITLE
es client crashes 

### ISSUE THREAD

**Issue by ninadvps** [elastic/elasticsearch#24862]
In reference to... https://github.com/elastic/elasticsearch/issues/24721#issuecomment-302838609

I put a comment on the closed issue, so making sure its on the radar...

Below is how you would regenerate the error....
https://drive.google.com/file/d/0B-AtWs3naQrSejYwRThURC1ETWM/view?usp=sharing
here the link to the code.... just follow the below steps to generate the crash, or you can examine the heap dump in it...

cd esTool

sbt;

in the sbt console: testOnly TestEsClient, rerun this command 8 to 12 times.
The crash doesnt happen if u simply run it from a main method only from sbt.

Inside the esTool folder I have esdump.hprof and also esdump_Leak_Suspects.zip which has an index.html which points you to io.netty.buffer.PoolArena$HeapArena ....
Ive played with many of the netty setting etc, with no luck also increasing the heap memory of sbt only delays the problem.

**Comment by jasontedor** [comment]
Please, this is not how we do things. Your comment was seen, but that doesn't imply that you'll get an immediate reply.

**Comment by ninadvps** [comment]
Apologies! I just didn't know how things are interpreted on a closed thread, so raised an issue. On the other hand its interesting that you closed the issue, I'm sure you have a reason for that. Also I don't expect a response right away, but what I do expect that the issue isn't closed without any resolution/a comment, I would expect that is how things are done? Also especially on a closed issue, if the issue was noted, it would be worthwhile to mention simply that someone is looking into it... Please correct me if Im wrong.

**Comment by jasontedor** [comment]
> I just didn't know how things are interpreted on a closed thread, so raised an issue.

**Comment by jasontedor** [comment]
> I just didn't know how things are interpreted on a closed thread, so raised an issue.

I was engaging with you on that thread.

> On the other hand its interesting that you closed the issue, I'm sure you have a reason for that.

As I explained, until we have evidence that the transport client is the problem and not your application code, we will not treat it as a bug.

> I do expect that the issue isn't closed without any resolution/a comment, I would expect that is how things are done?

There's an [explanation](https://github.com/elastic/elasticsearch/issues/24721#issuecomment-302691889) there already, I really do not get this comment at all.

> Also especially on a closed issue, if the issue was noted, it would be worthwhile to mention simply that someone is looking into it...

Again, I was already engaging with you on that thread.

So expectations are clear, I will not engage here any further in a meta-conversation. I *will* look at your issue, I already said there:

> Okay, let's see where this goes. I will be happy to help you if this is an issue on our side.
