### ISSUE TITLE
Clarify whether the Reindex API handles deletions during the reindex process

### ISSUE THREAD

**Issue by takahashi64** [elastic/elasticsearch#24866]
Elastic Search version: 2.4.3

I would like to use the [Reindex API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) to migrate documents from an in-use index in production to a newly created index that has an updated index mapping/definition. 

I stumbled on this [guide](https://summera.github.io/infrastructure/2016/07/04/reindexing-elasticsearch.html) which outlines various approaches to the problem of updating mappings/definition of an index. It points out (what I think to be a valid) an issue with deletions that occur during the document-migration process:

> Deletes
> 
> Deletes are a bit trickier. We can’t handle them like we did writes because there is a race condition. Consider the following problem scenario:
> 
> Given:
> 
> Record A exists in the old index
> We have started the reindex process, capturing A in the scrolled search snapshot
> Record A is not yet in the new index
> When: A DELETE operation on Record A occurs
> 
> Then:
> 
> Record A is deleted from old index, but not from our new index because it doesn’t exist yet
> Record A is later indexed into the new index when it is returned from our scrolled search snapshot
> So there is a race condition between deleting and indexing the record. If we reindex Record A before the DELETE operation comes in, we are fine. If we try to DELETE a non-existent Record A in our new index and then insert the same record from our scrolled search, we have a record in our new index that should not exist.😫
> 
> Options
> 
> Eliminate the possibility of deleting records during reindexing
> Push delete operations to a queue during reindexing to be processed when done

Does the Reindex API cater for deletions that occur during the reindexing process or should I follow the proposed options in the guide, or is there another solution?

**Comment by abeyad** [comment]
> Does the Reindex API cater for deletions that occur during the reindexing process

No, it does not.  You will have to follow one of the two proposed options.  

Also, in the future, kindly propose all questions on the [discussion forum](https://discuss.elastic.co/) we provide.  We reserve GitHub for known bugs and feature requests.  Thank you.
