### ISSUE TITLE
[TEST] SharedClusterSnapshotRestoreIT#testDataFileCorruptionDuringRestore fails sporadically

### ISSUE THREAD

**Issue by abeyad** [elastic/elasticsearch#24860]
The fails sporadically, the latest failure being: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.x+multijob-unix-compatibility/os=debian/795/console

This does not reproduce except sporadically on CI (once every month or so).  I've increased the logging levels to TRACE for the test:
master: 68f03b88c495fd1e408c1aff559e8551004d64b4
5.x: 9f0368e0de4ad30ee1dc3492afa9a38e8a3b3a65
5.4: 6ea51f4184dcdf9632fe3e0a53944ffeac2016b7

The issue is that the restore operation times out: https://github.com/elastic/elasticsearch/blob/master/core/src/test/java/org/elasticsearch/snapshots/SharedClusterSnapshotRestoreIT.java#L852

This happens because the restore operation is never removed from the cluster state, which the `RestoreService` takes care of in https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/snapshots/RestoreService.java#L679

In order for the `RestoreService` to clear up the restore operation from the cluster state, it needs to be triggered by updating the restore shards to the FAILED state, which happens in `RestoreInProgressUpdater`, but it does not update the `failedShards` set for some reason.

I've increased the logging in the `o.e.cluster.routing` package and the `o.e.snapshots` package for this test to hopefully get more info the next time it fails.

**Comment by tlrx** [comment]
This issue fails every month or so in the last two years but didn't fail since Sept 17th 2017. Restore has been improved in #27493 so I'm curious to see if this failure will appear again on 5.6.6/6.0.2.

Please reopen if needed.
