### ISSUE TITLE
unknown property "HADOOP_HOME" in "plugins\repository-hdfs\build.gradle" (Windows OS specific)

### ISSUE THREAD

**Issue by SELVAKUMAR-S** [elastic/elasticsearch#24878]
**Plugins installed**: [default]

**JVM version** : `1.8.0_102`

**OS version** : Windows 7

**Description of the problem including expected versus actual behavior**: 

Issue is Windows specific. Gradle tasks throws out error "unknown Property "HADOOP_HOME" if HADOOP_HOME is set in the system.

Issue is due to referencing unknown property HADOOP_HOME in the exception statement

**Steps to reproduce**:

 1. Set HADOOP_HOME
 2. Make sure that any of the files winUtils.exe, hdfs.dll or hadoop.dll is not present in HADOOP_HOME\bin
 3. Run any of the gradle tasks
 4. Observe that you get error "unknown property HADOOP_HOME in plugins\repository-hdfs\build.gradle #line_number:40

**Provide logs (if relevant)**:

 FAILURE: Build failed with an exception.
* Where:
Build file 'C:\..\..\..\elasticsearch\plugins\repository-hdfs\build.gradle' line: 140

* What went wrong:
A problem occurred evaluating project ':plugins:repository-hdfs'.
> Could not get unknown property 'HADOOP_HOME' for project ':plugins:repository-hdfs' of type org.gradle.api.Project.

**Comment by SELVAKUMAR-S** [comment]
if this seems to be a valid one to fix, i would like to take this as my first task to contribute with.

**Comment by rjernst** [comment]
What gradle command did you run? The repository-hdfs integ test cannot run on windows unless you setup HADOOP_HOME. But the test should simply skip if it is not set.

**Comment by SELVAKUMAR-S** [comment]
yes @rjernst , i set up HADOOP_HOME and ran in to this issue, i tried will gradle assemble, gradle tasks etc..
So as you said, this issue will pop up only if HADOOP_HOME is set

**Comment by rjernst** [comment]
What does the `bin` dir of your HADOOP_HOME contain?

**Comment by SELVAKUMAR-S** [comment]
actually as i mentioned in the description, this issue occurs only if one of the three files "winUtils.exe, hdfs.dll or hadoop.dll" is not present in the bin directory of HADOOP_HOME. So instead of throwing out exception in this case, the mentioned error appears. Initially i didn't have these files in HADOOP_HOME/bin since HADOOP doesn't ship those files so i found this issue and managed to download these files and put in to HADOOP_HOME/bin to resolve it

**Comment by rjernst** [comment]
The error message is there for a reason. We need those files to exist in order to run the mini hdfs cluster the integ tests depend on.

If you want to improve this, you could improve the log message in this case to list the files expected (see plugins/repository-hdfs/build.gradle). But I don't see this as a bug, so I am closing.

**Comment by SELVAKUMAR-S** [comment]
Hi @rjernst  bear me if i am spamming you, but if the HADOOP_HOME/bin doesnot contain the native libraries, the intention is to throw exception with message <throw new IllegalStateException("HADOOP_HOME: " + path.toString() + " is invalid, does not contain hadoop native libraries in $HADOOP_HOME\bin");> but the actual behavior is the build script fails throwing the error <b>Could not get unknown property 'HADOOP_HOME' for project ':plugins:repository-hdfs' of type org.gradle.api.Project.</b> which is because usage of <$HADOOP_HOME> in the exception statement, so we may need to correct this as <      String hadoopHome = path.toString();
      throw new IllegalStateException("HADOOP_HOME: " + hadoopHome + " is invalid, does not contain hadoop native libraries in $hadoopHome\\bin");> , Please correct me if i am wrong

**Comment by SELVAKUMAR-S** [comment]
To put this as simple as possible
- Expected behavior : Exception with message <b>HADOOP_HOME: C:\hadoop-2.8.0 is invalid, does not contain hadoop native libraries in C:\hadoop-2.8.0\bin</b>
- Actual behavior : build.gradle fails with the error <b> Could not get unknown property 'HADOOP_HOME' for project ':plugins:repository-hdfs' of type org.gradle.api.Project</b>
 
The exception message statement is referencing the undefined property "HADOOP_HOME" which causes the issue

**Comment by rjernst** [comment]
@SELVAKUMAR-S Thank you for the clarification. I understand the problem now. I opened #24885 to address this.
