### ISSUE TITLE
Rest test failure for significant text agg

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#24881]
This looks related to the new significant terms aggregation. The exception is:
```
"type" : "unknown_named_object_exception",
  1>         "reason" : "Unknown BaseAggregationBuilder [significant_text]",
  1>         "line" : 1,
  1>         "col" : 84,
  1>         "stack_trace" : "UnknownNamedObjectException[Unknown BaseAggregationBuilder [significant_text]]
```

CI Build:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+aggressive-opts/151/consoleFull

**Comment by markharwood** [comment]
Was missing this version check: https://github.com/elastic/elasticsearch/commit/a64937db7aba2d4c6568052b07c532141a09db8d
