### ISSUE TITLE
I cant get results more than 10K in elasticsearch

### ISSUE THREAD

**Issue by johnbasinger84** [elastic/elasticsearch#24880]
I have a query to get cities from country by country code.

While iam trying to get _**9000 to 10000**_ sets it returns the result.

But when I try to get _**10000 to 11000**_ or _**10000 to 10001**_ it wont return anything. Stops at the point.

Please help me

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

BTW this is expected.
