### ISSUE TITLE
Regular Expression Query Crashes Cluster Data Nodes

### ISSUE THREAD

**Issue by patrickstjohn** [elastic/elasticsearch#24890]
**Elasticsearch version**: Tested on 5.2.1 and 5.4.0

**Plugins installed**: [SearchGuard5 (5.2.1-12 and 5.4.0-12) and X-Pack (5.2.1 and 5.4.0)]

**JVM version**: Java(TM) SE Runtime Environment (build 1.8.0_121-b13)

**OS version**: Linux 3.10.0-514.16.1.el7.x86_64 #1 SMP Fri Mar 10 13:12:32 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: Querying with the following regex immediately crashes ever data node in the cluster. 

**Steps to reproduce**: Put the following query in Kibana "query: /([A-Z0-9]{18100})/ "

**Comment by jasontedor** [comment]
Duplicates #24553
