### ISSUE TITLE
Scripted Metric Aggregation has been marked "experimental" for a very long time

### ISSUE THREAD

**Issue by simonw** [elastic/elasticsearch#24895]
Added in 1.4.0.Beta1: https://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-aggregations-metrics-scripted-metric-aggregation.html

Still marked as "experimental" in 2.4: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-aggregations-metrics-scripted-metric-aggregation.html

And "experimental" in 5.4: https://www.elastic.co/guide/en/elasticsearch/reference/5.4/search-aggregations-metrics-scripted-metric-aggregation.html

And still "experimental" in the docs for 6.0.0.alpha https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-metrics-scripted-metric-aggregation.html

Is it definitely still experimental? I'd like to know before I consider using it.

**Comment by javanna** [comment]
hi @simonw good question. It's something that we have discussed as part of #19798. We plan on removing the experimental tag from the scripted metric aggregation, we just didn't get to it yet.
