### ISSUE TITLE
field collapsing very slow

### ISSUE THREAD

**Issue by zplzpl** [elastic/elasticsearch#24899]
Only one field is used to collapsing . the field type is keyword.

hits.total = 1130 

The same request does not contain the collapsing that are only used for 13 milliseconds, using a collapsing using 130 milliseconds. (This time is CURL starttransfer time)

10x time.

Using the restful api.

**Comment by clintongormley** [comment]
@zplzpl did you read the information that we asked for when you opened this issue? See https://github.com/elastic/elasticsearch/issues/new

**Comment by jimczi** [comment]
Duplicate of #24900
