### ISSUE TITLE
Update by query should support short script form and `doc`

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#24898]
The  `script` parameter in update-by-query requires a full script object, instead of allowing the simple script form:

    "script": "ctx._source.foo=5"

We should be using the same script parser we use every else, which would take care of this automatically.

Also, any reason why we don't support partial doc updates with the `doc` parameter`?

**Comment by rjernst** [comment]
What do you mean by partial updates? `doc` is doc values, ie already indexed values.

**Comment by clintongormley** [comment]
No, I mean the `doc` parameter which exists in the update query, as in:

```
POST index/type/id/_update
{
  "doc": {
    "status": "published"
  }
}
```

This request would merge the `doc` object with the `_source`. It's currently not supported by update-by-query

**Comment by rjernst** [comment]
Ok, thanks for the clarification. So this would happen outside of the script itself.

**Comment by pozhidaevak** [comment]
Hi,
I want to make this issue my first contribution to the project. Has anyone started work on this issue? Is it ok if I start working on it? It will probably take some time for me to understand the issue and familiarise myself with the code.

**Comment by pozhidaevak** [comment]
Thanks, @nik9000. 
It seems that `_update_by_query` uses static function `RestUpdateByQueryAction::parseScript(Map<String, Object>)` to parse script tag. This function is used only in this place. 
I haven't found parsing of `script` field in `RestUpdateAction` class. 
I'll try to find the solution that reuses the same code as in other parts of the project.
For now, I think the best way is to initialize `XContentParser` and use `Script.parse()` function.

**Comment by dakrone** [comment]
This should be closed by #26841

**Comment by olee** [comment]
And what about the `doc` parameter that `_update` accepts but not `_update_by_query`?

**Comment by 3lnc** [comment]
@nik9000 any updates on support for `doc`?

**Comment by nik9000** [comment]
> And what about the doc parameter that _update accepts but not _update_by_query?

We've [talked](https://github.com/elastic/elasticsearch/issues/20135) about this in the past and not been too keen on it.

**Comment by est** [comment]
support only `script` will yield stupid "too many scripts OMG cant compile" errors.

**Comment by souenzzo** [comment]
Still waiting support for doc.

If you are here, you probably want to use this script:

```javascript
{
  source: "for (k in params.keySet()) {ctx._source[k] = params[k]}",
  params: {a: 1, b: 2 ...}
}
```

**Comment by Trass3r** [comment]
Thanks @souenzzo!
It's important to note though that unlike _update this doesn't merge partial objects, it just overwrites.
```json
  "script": {
    "source": "for (k in params.keySet()) {ctx._source[k] = params[k]}",
    "params": {
      "obj": {
        "field2": "val"
      }
    }
  }
```

https://www.reddit.com/r/elasticsearch/comments/upig3f/how_to_merge_objects_in_painless/
