### ISSUE TITLE
elasticsearchjs size too big! how to import only the necessary components?

### ISSUE THREAD

**Issue by rolele** [elastic/elasticsearch#24901]
I build my app using webpack and my app basically double in size as soon as I did:
```
import elasticsearch from 'elasticsearch';

export default class EsClient {
  constructor(_) {
    this.client = new elasticsearch.Client({
      host: 'localhost:9201',
      log: 'trace',
    });
    this.search = ({ params, request } = {}) => new Promise((resolve, reject) => {
      this.client.search(request).then((body) => {
        resolve(body);
      }, (error) => {
        reject(error);
      });
    });
  }
}

```

Going from 79K Gzip:
![1](https://cloud.githubusercontent.com/assets/22406571/26493685/3d45630e-425e-11e7-9894-c36037147a6a.jpg)

To 158K Gzip:
![2](https://cloud.githubusercontent.com/assets/22406571/26493692/494d6e62-425e-11e7-8850-dae01d8ffb1c.jpg)

Is there a way to take advange of the es6 import and only import part of the elasticsearch library?

**Comment by clintongormley** [comment]
You're looking for https://github.com/elastic/elasticsearch-js/issues

**Comment by rolele** [comment]
Arf sorry about that
