### ISSUE TITLE
Copied-to fields fail to highlight

### ISSUE THREAD

**Issue by zelfor5436** [elastic/elasticsearch#24912]
**Elasticsearch version**: 5.2.0

**Plugins installed**: Ingest-Attachment

**JVM version** (`java -version`): OpenJDK 1.8.0_111

**OS version** (`uname -a` if on a Unix-like system): Linux Mint 18.1 x64

**Description of the problem including expected versus actual behavior**:

Highlighting fails to work on fields containing content that has been populated via a "copy_to" directive on another field.

**Steps to reproduce**:

The following code produces two hits, however only one of them has meta->highlight. The expected behavior would be both hits having a highlight on the document.content field.

```python3
#python 3.5.2
from elasticsearch import Elasticsearch as ES
from elasticsearch_dsl import Search, Q

from pprint import pprint as pp

es = ES()
index = "testindex"
doc_type = "product"

es.indices.create(index=index, body={
		"mappings":{
			"product":{
				"properties":{
					"attachment":{
						"properties":{
							"content":{"type":"text", "copy_to":"document.content"}
						}
					},
					"document":{
						"properties":{
							"fulltext":{"type":"text", "term_vector":"with_positions"},
							"content":{"type":"text", "term_vector":"with_positions_offsets", "copy_to":"document.fulltext"}
						}
					}
				}
			}
		}
	})

es.index(index=index, doc_type=doc_type, body={
		"attachment":{
			"content":"this is my text"
		}
	})
es.index(index=index, doc_type=doc_type, body={
		"document":{
			"content":"this is my text"
		}
	})

es.indices.flush()

s = Search(using=es, index=index, doc_type=doc_type)
search = "text"

query = Q("match_phrase_prefix",**{"document.content":search})

s = s.query(query)

s = s.highlight("document.content", number_of_fragments=0, highlight_query=query.to_dict())

for h in s:
	pp(dir(h.meta))

es.indices.delete(index)
```

This code produces the following output...

```
['doc_type', 'id', 'index', 'score']
['doc_type', 'highlight', 'id', 'index', 'score']
```

... I'd expect both hits to have a "highlight" field available.

**Comment by dadoonet** [comment]
I think that the problem here is that you don't store the document.content field. Elasticsearch tries then to extract from _source which does not have that field.

**Comment by zelfor5436** [comment]
How embarrassing.

@dadoonet that makes a whole lot of sense! I can confirm that setting store to True for the document.content field results in the expected highlighting behavior.

**Comment by dadoonet** [comment]
No problem. Happy to help.
If you have other problems like this feel free to ask on discuss.elastic.co which is the best place for that.
Thanks for confirming.
