### ISSUE TITLE
Confusing DateHistogram behavior: buckets starts not from min bound date 

### ISSUE THREAD

**Issue by Guchman** [elastic/elasticsearch#24920]
**Elasticsearch version**: 5.2.2-5.4
I've use pure elasticsearch offical image with testcontainers. But same behavior on producution system. 
**Plugins installed**: []

**JVM version** : 1.8.0_112

**OS version**  : OSx, Linux 

**Description of the problem including expected versus actual behavior**:
When Im trying to aggregate 7d buckets with summing - first bucket take wrong date (closes thursday as I suppose).  
Example. For dates  "2017-12-01" -  "2017-12-07" in filter and extended_bounds expected first bucket is 2017-12-01. But actual is 2017-11-30 (thursday again).

**Steps to reproduce**:
My query is 

    {
      "size": 0,
      "query": {
        "bool": {
          "must": [
            {
              "range": {
                "doc.dateExecute": {
                  "from": "2017-12-01",
                  "to": "2017-12-07",
                  "include_lower": true,
                  "include_upper": true,
                  "boost": 1.0
                }
              }
            }
          ],
          "disable_coord": false,
          "adjust_pure_negative": true,
          "boost": 1.0,
          "_name": "onDates"
        }
      },
      "aggregations": {
        "time": {
          "date_histogram": {
            "field": "doc.dateExecute",

            "interval": "7d",
            "offset": 0,
            "order": {
              "_key": "asc"
            },
            "keyed": false,
            "min_doc_count": 0,
            "extended_bounds": {
              "min": "2017-12-01",
              "max": "2017-12-07"
            }
          }
        }
      }
    }

 And the response is 
 
    {
      "took": 10,
      "timed_out": false,
      "_shards": {
        "total": 230,
        "successful": 230,
        "failed": 0
      },
      "hits": {
        "total": 0,
        "max_score": 0,
        "hits": []
      },
      "aggregations": {
        "time": {
          "buckets": [
            {
              "key_as_string": "2017-11-30T00:00:00.000Z",
              "key": 1512000000000,
              "doc_count": 0
            },
            {
              "key_as_string": "2017-12-07T00:00:00.000Z",
              "key": 1512604800000,
              "doc_count": 0
            }
          ]
        }
      }
    }
Just to be clear: other date periods works as expected. 1day, YEAR, Month, week, etc. But with n-days I have that behavior.

**Comment by jimczi** [comment]
@Guchman I see that you linked your issue in the discuss forum. We usually do the other way around, post in discuss first and if it's confirmed as a bug we open an issue here.
I answered in the forum ;) :
https://discuss.elastic.co/t/confusing-datehistogram-behavior-buckets-starts-not-from-min-bound-date/87343/2
