### ISSUE TITLE
Explain where to get path for translog recovery action

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#24929]
[Here](https://github.com/elastic/elasticsearch/blob/5.4/docs/reference/index-modules/translog.asciidoc#what-to-do-if-the-translog-becomes-corrupted) we guide users on how to fix a corrupted translog.

What's not clear is where we get the `/var/lib/elasticsearchdata/nodes/0/indices/P45vf_YQRhqjfwLMUvSqDw/0/translog/` path from. Is the `P45vf_YQRhqjfwLMUvSqDw` a shard/index ID. Can we add something here that explains where to get the full path from?

This question popped up in [this discuss thread](https://discuss.elastic.co/t/corrupted-translog/87254/).

**Comment by bleskes** [comment]
@markwalkom I think the exception should give you the path. If you're good with that, I'll change the ticket description and label it accordingly.

**Comment by markwalkom** [comment]
Sounds great!
