### ISSUE TITLE
[CI] SmokeTestMultiNodeClientYamlTestSuiteIT {create/60_refresh/refresh=wait_for} fails

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#24935]
The following test failed on CI (see [this build](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/2970/console)): 

org.elasticsearch.smoketest.SmokeTestMultiNodeClientYamlTestSuiteIT test {yaml=create/60_refresh/refresh=wait_for waits until changes are visible in search}

It doesn't reproduce locally and I don't know what happened. The trace shows that the wait_for option timed out but I have no clue why:

  ```
1> [2017-05-28T00:04:33,592][INFO ][o.e.s.SmokeTestMultiNodeClientYamlTestSuiteIT] [test {yaml=cat.aliases/10_basic/Column headers}]: after test
  1> [2017-05-28T00:04:33,598][INFO ][o.e.s.SmokeTestMultiNodeClientYamlTestSuiteIT] [test {yaml=create/60_refresh/refresh=wait_for waits until changes are visible in search}]: before test
  1> [2017-05-28T00:05:03,705][INFO ][o.e.s.SmokeTestMultiNodeClientYamlTestSuiteIT] [test {yaml=create/60_refresh/refresh=wait_for waits until changes are visible in search}]: after test
  1> [2017-05-28T00:05:03,709][INFO ][o.e.s.SmokeTestMultiNodeClientYamlTestSuiteIT] Stash dump on failure [{
  1>   "stash" : {
  1>     "body" : null
  1>   }
  1> }]
ERROR   30.1s | SmokeTestMultiNodeClientYamlTestSuiteIT.test {yaml=create/60_refresh/refresh=wait_for waits until changes are visible in search} <<< FAILURES!
   > Throwable #1: java.lang.RuntimeException: Failure at [create/60_refresh:67]: listener timeout after waiting for [30000] ms
   > 	at __randomizedtesting.SeedInfo.seed([C14AB41884F38AA8:491E8BC22A0FE750]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:346)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:328)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.io.IOException: listener timeout after waiting for [30000] ms
   > 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:660)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:219)
   > 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:191)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestClient.callApi(ClientYamlTestClient.java:169)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.callApiInternal(ClientYamlTestExecutionContext.java:157)
   > 	at org.elasticsearch.test.rest.yaml.ClientYamlTestExecutionContext.callApi(ClientYamlTestExecutionContext.java:89)
   > 	at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:221)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:344)
   > 	... 37 more
```

**Comment by tlrx** [comment]
@nik9000 I assigned it to you since you might have idea concerning the failing wait_for - feel free to reassign if needed.

**Comment by nik9000** [comment]
I'll add it to my queue but not super high because I don't think this is common.

**Comment by jasontedor** [comment]
See this thread
https://groups.google.com/a/elastic.co/d/msg/dev/YvuJFqjJO78/KQgunG_UBgAJ

I ssh to the machine and the issue presents itself again.

I have opened https://github.com/elastic/elasticsearch/pull/24926/ in
response to this.

**Comment by tlrx** [comment]
Should be fixed by #24926

**Comment by nik9000** [comment]
Taking it off my list!

**Comment by talevy** [comment]
have another occurrence:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/1238/console

**Comment by jasontedor** [comment]
If the same test fails twice it does not mean that it has the same cause as the first failure. I think that it's best to not reopen an old issue for a test failure unless the cause is definitively the same as the initial failure that was being tracked. I'm inclined to think that the failure is something different here since this has not failed at all from May 29 until July 11. This leads me to believe that something new tickled this test and caused this failure. I logged into the slave to capture the build logs but sadly they are already destroyed. I'm going to close this issue. If this occurs again, please capture the cause and open a new issue (unless it's genuinely the same cause).
