### ISSUE TITLE
nowInMillis removed from QueryParseContext ?

### ISSUE THREAD

**Issue by DivyaMalini** [elastic/elasticsearch#24955]
In our prev versions we had taken dependency on "nowInMillis()" method for some telemetry purpose . Now in the latest code i see it removed ? I was trying to use System.currentTimeMillis() but worried that the correlation might be broken between nodes.

What is the reason to remove it and how could i accomplish the same now?

**Comment by jasontedor** [comment]
I see https://discuss.elastic.co/t/searchcontext-and-queryparsecontext-not-having-nowinmillis-anymore/87454. Elastic prefers to use GitHub only for verified bug reports and feature requests and provides the [forum](https://discuss.elastic.co) for general questions.
