### ISSUE TITLE
Set operations for lists in painless

### ISSUE THREAD

**Issue by gingerwizard** [elastic/elasticsearch#24980]
This is a low priority feature that i feel would make common painless tasks more succinct.

This requirement typically arises in watches where there is a need to compare sets of values produced by terms aggregations. Consider alerts such as:

1. Alert me when a user logs onto a new server
2. Alert me when a process starts on a server for the first time

Both of these require comparison of two term aggregations. More specifically, consider the steps required for (2).

1. An aggregation to identify all of the servers and their respective processes that have been started in the last N minutes.  
2. A second query which utilises the results of step 2.  This query would utilise a terms filter using the values of set A identified above, restricting to the period less than now-N minutes i.e. processes started prior to the last N minutes.  (1) and (2) use a chain query.
3. A painless condition to determine whether the watch fires by checking if set A and set B are of equal size. If not, we return true indicating a new process has occurred.
4. In our transform step we identify the specific difference between set A and set B using a painless script i.e. what is in A, not present in B. 

The type of set operation in (4) is quite common. This leads to the painless:

```
def history=ctx.payload.history_started_processes.aggregations.process_hosts.buckets.stream().map(p -> p.key).collect(Collectors.toList()); 

return ctx.payload.started_processes.aggregations.process_hosts.buckets.stream().map(e -> e.key).filter(p -> !history.contains(p)).map(p -> ['process_name':/_/.split(p)[0],'host_name':/_/.split(p)[1],'@timestamp':ctx.trigger.triggered_time]).collect(Collectors.toList());
```
 Whilst quite succinct i'm not sure this is very accessible to new users.

Proposal is for some simple set operations to be made available for lists. If these could be exposed as operators e.g.

1. union - s | t  - new set with elements from both s and t
2. intersection - s & t - new set with elements common to s and t
3. difference - s & t - new set with elements in s but not in t

The above is what python uses and is subject to discussion. Not particularly opinionated on this topic.

The above thus becomes

```
return ctx.payload.started_processes.aggregations.process_hosts |
ctx.payload.history_started_processes.aggregations.process_hosts.buckets;
```

cc @eskibars @clintongormley  @jdconrad @spinscale

**Comment by gingerwizard** [comment]
I should emphasise i'm not fussed on the specifics of the syntax - people maybe be understandably reluctant to overload operators. For example,

collection.union(other_collection)

would also be perfect.  The emphasis is keeping the painless succinct whilst also readable.

**Comment by rjernst** [comment]
We should not have set operations on lists, that is trappy.  I also don't see how having such operations on lists would make this any more succinct. You would still have the crazy filter statements. If you want to union the two lists uniquely, build sets using `new HashSet(mylist)`.

**Comment by rjernst** [comment]
I am closing this as I think it is clear we will not be modifying painless as it already contains the necessary pieces.

**Comment by kgeographer** [comment]
Hi
Re: `new HashSet(mylist)`, how can that be executed in Painless for use in a update_by_query()?
thanks
