### ISSUE TITLE
[DOCS] explicitly state whether or not each mapping param can be updated on an existing field

### ISSUE THREAD

**Issue by rhbecker** [elastic/elasticsearch#24991]
**Elasticsearch version**:

v5.4 docs (also checked against master branch)

**Description of the problem including expected versus actual behavior**:

The put mapping doc states:

> Each mapping parameter specifies whether or not its setting can be updated on an existing field.

I interpret this to mean I should expect to find an indication on every one of the 24 mapping parameter doc pages. In reality, only 13 of 24 include a statement (so far as I can find):

1. 10 (coerce, dynamic, enabled, fielddata, format, ignore_above, ignore_malformed, include_in_all, position_increment_gap, search_analyzer) include the statement:

    > Its value can be updated on existing fields using the PUT mapping API.

2. 2 (fields, properties) include a statement like:

    > New [...] can be added to existing fields using the PUT mapping API.

3. 1 (norms) includes the statement:

    > Norms can be disabled on existing fields using the PUT mapping API.

The other 11 (analyzer, boost, copy_to, doc_values, index, index_options, normalizer, null_value, similarity, store, term_vector) don't include the strings "PUT mapping" or "exist", at least in this context.

I do not know whether to consider the absence of a statement to be an indication that these settings cannot be updated on an existing field. IMO, I shouldn't be left with assumptions - the docs should simply state "whether or not its setting can be updated", as promised by the quote from the put mapping doc.

It might also be nice to have a list in 1 place, but I'll be happy enough if the above is addressed.

**Steps to reproduce**:

 1. Open `master/docs/reference/indices/put-mapping.asciidoc`

 2. View lines 139-140, wherein it is stated:

    > Each <<mapping-params,mapping parameter>> specifies whether or not its setting can be updated on an existing field.

 3. Open each of the individual mapping parameter docs found in `master/docs/reference/mapping/params` and search for "put mapping" or "exist".

**Comment by markharwood** [comment]
A quick test with 6.6 and Kibana Console shows it's split fairly evenly between Yes and no:

YES ignore_above
YES boost
YES coerce
YES copy_to
YES dynamic
YES fielddata
YES eager_global_ordinals
YES ignore_above
YES ignore_malformed
YES index_options
YES fields
YES null_value
YES position_increment_gap
N/A properties (new fields can be added, existing fields params as per this list)
YES search_analyzer



NO normalizer
NO doc_values
NO analyzer
NO enabled
NO format
NO index_phrases
NO index_prefixes
NO index
NO norms
NO similarity
NO store
NO term_vector

Not sure if it's best to put this info:

a) in the pages for each param
b) in the page with the table that lists all the params or
c) all of the above

**Comment by debadair** [comment]
[docs issue triage]

We should be clearer about the implications of updating the parameters. (And remove the statement that each parameter indicating whether or not it can be updated if we aren't going to be explicit in all cases.)

**Comment by lockewritesdocs** [comment]
This issue hasn’t been updated in 3+ years so I’m closing it. We can revisit if needed.
