### ISSUE TITLE
Java API exposes Lucene class missing from core elasticsearch artifact

### ISSUE THREAD

**Issue by ejain** [elastic/elasticsearch#24992]
`org.elasticsearch.index.query.QueryBuilders::nestedQuery` takes a parameter of type `org.apache.lucene.search.join.ScoreMode`. This class is not included in the core elasticsearch artifact (5.4.0), so an explicit dependency on lucene-join (6.5.1) has to be added to clients.

**Comment by nik9000** [comment]
This isn't new..... We'd like to drop the dependencies on the client and we
are working on it slowly. The java high level rest client is the first
step. It still has many dependencies we don't want in a client but it gives
us a path to removing them.

**Comment by nik9000** [comment]
The missing from the core artifact bit is new, I think.

**Comment by liketic** [comment]
@nik9000 I think this can be close because I can find the dependency:
https://github.com/elastic/elasticsearch/blob/3664ede9b5452180606cda01f532028091657e6f/core/build.gradle#L47

**Comment by nik9000** [comment]
I'm glad it is fixed now!
