### ISSUE TITLE
Can the Cross Cluster Search of elasticsearch be combined with kibana ?

### ISSUE THREAD

**Issue by ertaoxu** [elastic/elasticsearch#25008]
**Describe the feature**:

**Elasticsearch version**:
5.4.0

**Plugins installed**: []

**JVM version** (`java -version`):
java version "1.8.0_73"
**OS version** (`uname -a` if on a Unix-like system):
CentOS Linux release 7.1.1503 (Core)
**Description of the problem including expected versus actual behavior**:

The tribe nodes is now being used by me with kibana.
I found the elasticsearch new feature  Cross Cluster Search, how can i use it though my kibana?

**Comment by jasontedor** [comment]
See elastic/kibana#11011.
