### ISSUE TITLE
ES architecture 

### ISSUE THREAD

**Issue by lokeshmadan** [elastic/elasticsearch#25012]
We are exploring ES in our stack. I was looking around for some good architecture diagrams which shows internals of ES like how Netty is used by ES, which protocols needs to be configured and enabled for making cluster work(multicast, unicast), which protocols gets utilized at different layers(application(i guess ES uses Native Elasticsearch binary protocol), network ,etc). I know details of how ES works like sharing indexing, pipelines etc in details, all i am missing more of network level architecture details.

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by lokeshmadan** [comment]
@jasontedor : I actually opened the thread on forum [Here](https://discuss.elastic.co/t/es-network-architecture/87646) is the link for that and was adviced to open the feature request for this.

**Comment by markwalkom** [comment]
Is this not something that we can add to the def guide to help better explain the interaction?

**Comment by jasontedor** [comment]
I don't think the internals of how Netty is used by Elasticsearch would be a good addition at all, extremely limited value, if any, to users. I think the remainder is covered in the docs.

**Comment by lokeshmadan** [comment]
@jasontedor : Why do you think this would be "extremely limited value" ? Can you please point me to the link where architecture is covered ? Because i didn't seem to find any :) .

**Comment by nik9000** [comment]
> multicast

not any more

> unicast

https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#unicast.hosts

> which protocols gets utilized at different layers

Maybe useful to make sure we mention somewhere that the inter-node protocol is ES's home grown thing over TCP but I expect it is somewhere already.

A diagram of how ES interfaces with netty isn't super useful unless you are hacking on Elasticsearch, though, actually https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/plugins/NetworkPlugin.java does a fair job of describing the interface at a high level.

**Comment by jasontedor** [comment]
>>I don't think the internals of how Netty is used by Elasticsearch would be a good addition at all, extremely limited value, if any, to users.

> Why do you think this would be "extremely limited value" ? 

The internal implementation detail of ES using Netty for networking, and how it uses Netty for networking, is not of broad interest to the user base. It doesn't help users use the software, and is something that I think would not be of even tangential interest to the vast majority of users. For the users that are interested, the code is open source and they can devour it to their own desires. Therefore, I do not think we should spend any time writing up such details.

**Comment by ats1999** [comment]
I think it would be helpful for new contributors to understand the code.
