### ISSUE TITLE
Simple 2 node cluster

### ISSUE THREAD

**Issue by lokeshmadan** [elastic/elasticsearch#25013]
I tried to form a simple 2 node cluster, with below configuration but doesn't seems to be working. Am i doing anything wrong ? Idea here is 1 node is already running and i want to bootstrap another node and join the cluster.  There's no firewall running on these nodes.

I am running ES5.4 on linux 4.1.12-32.2.3.el7uek.x86_64 Red Hat Enterprise Linux Server release 7.1 (Maipo)

Node A(Bootstrapped first)
network.host: abc.com
http.cors.enabled: true
http.cors.allow-origin: "*"
node.name: abc

NodeB(Bootstrapped later)
network.host: xyz.com
http.cors.enabled: true
http.cors.allow-origin: "*"
discovery.zen.ping.unicast.hosts: ["abc.com"]
node.name: xyz

I am getting below error when trying to bring up NodeB

[2017-06-01T14:07:29,121][INFO ][o.e.d.z.ZenDiscovery ] [xyz] failed to send join request to master [{abc}{JYyN-G5AQ5OoJ504NLX_3Q}{kPgJP_KBRnW0XudYULu6wA}{abc.com}{10.240.3.106:9300}], reason [RemoteTransportException[[abc][10.240.3.106:9300][internal:discovery/zen/join]]; nested: ConnectTransportException[[xyz][10.196.14.151:9300] connect_timeout[30s]]; nested: IOException[connection timed out: xyz.com/10.196.14.151:9300]; ]

I have checked, both the machines can ping each other. Output of netstat -nlp|grep tcp shows 9200 and 9300 ports are listening

tcp6 0 0 10.240.3.106:9200 :::* LISTEN 12568/java 
tcp6 0 0 10.240.3.106:9300 :::* LISTEN 12568/java 
tcp6 0 0 :::22 :::* LISTEN - 
tcp6 0 0 :::12406 :::* LISTEN -

Am i missing something ?

**Comment by dakrone** [comment]
Hi,
We reserve Github issues for feature requests and bug reports. If you are having problems please use https://discuss.elastic.co instead!
