### ISSUE TITLE
[CI] RemoteClusterConnectionTests.testNodeDisconnected failure

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#25026]
This doesn't reproduce locally for me so it might be a rare, one off kind of thing:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/720/console

Actual failure:

```
FAILURE 10.1s J0 | RemoteClusterConnectionTests.testNodeDisconnected <<< FAILURES!
   > Throwable #1: java.lang.AssertionError
   > 	at __randomizedtesting.SeedInfo.seed([56C8A52C3F9393DA:9F9CB13D84E57258]:0)
   > 	at org.elasticsearch.transport.RemoteClusterConnectionTests.testNodeDisconnected(RemoteClusterConnectionTests.java:235)
   > 	at java.lang.Thread.run(Thread.java:745)
```

[Here](https://gist.github.com/nik9000/a91ef00af0ba0fd212ef07bb12b175ef) is the logging from the suite.

**Comment by bleskes** [comment]
This is almost a year old failure. I'm going to close it as I don't think it makes sense to chase it anymore.
