### ISSUE TITLE
Feature Request: Stored Filters

### ISSUE THREAD

**Issue by ljcollins25** [elastic/elasticsearch#25065]
Feature Request:

I'd like the ability to create stored filters (i.e. bitsets which are stored in the index and can be queried when searching to filter documents). I am working on a source control indexing tool and I would like to have filters corresponding to every commit which make it easy to search all documents at particular points in history. Note: this isn't just the changed documents in that commit but the full set of documents in the source tree at that commit. I'm not sure how useful this is to others, but I thought I'd see if there was any interest. Of course, any feedback for different ways of achieving this are also welcome.

Implementation Details:
I'm currently working on a prototype which does this by broadcasting a special stored filter document to be indexed on all nodes. When the stored filter document to a particular shard it does a query and captures the matching documents in each segment into a field. There needs to be some coordination with respect to segments which are currently being merged, so it waits for outstanding merges to complete. Further, as segments are merged they pull in the stored filter terms into their postings.

Scenario:
```
PUT inspect 
{
    "settings": {
        "number_of_shards": 1
    }, 
  "mappings": {
    "stored_filter": { 
      "_all":       { "enabled": false  }, 
      "properties": { 
        "query":    { "type": "query" }
      }
    },
    "user": { 
      "_all":       { "enabled": false  }, 
      "properties": { 
        "name":    { "type": "keyword" }
      }
    }
  }
}

PUT /inspect/user/user1?pretty
{ 
    "name" : "Test User"
}

POST _refresh

PUT /inspect/stored_filter/myfilter2?pretty
{ 
    "name" : "My Filter",
    "query": {
     "constant_score": {
        "filter": {
        "term": {
           "name": "Test User"
        }
        }
     }
   }
}

PUT /inspect/user/user2?pretty
{ 
    "name" : "Test User"
}

GET /inspect/_search
{
   "query" : {
        "stored_filter" : { "id": "myfilter2" }
    }
}
```

In this case the filter would return the user1 document but not user2.

**Comment by clintongormley** [comment]
Hi @ljcollins25 

We discussed this in our FixItFriday session - I'm afraid it is a non-starter.  Bitset filters depend on Lucene's doc IDs per segment.  As soon as segments merge then the doc ID changes, so storing filters in an index just won't work.  

All I can suggest is that you store one or more commit IDs per document and use a term filter on that ID when searching.
