### ISSUE TITLE
Track refresh metrics through Lucene's refresh listeners

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#25075]
When working on #25052 we came to the realization that it is probably better to track refreshes through Lucene's refresh listeners. We're already using Lucene's refresh listeners to power our own refresh listeners so I imagine to code change to do this would be small but I think it is worth spending the extra time to think through all the side effects.

**Comment by nik9000** [comment]
@bleskes and @jasontedor, I believe this summarizes our conversation, please comment if I'm wrong.

**Comment by bleskes** [comment]
closed by  #25083
