### ISSUE TITLE
minimun_should_match does not work at ES 5.* version

### ISSUE THREAD

**Issue by lixiuna0908** [elastic/elasticsearch#25092]
I deploy ES 5.* version, and use ngram as char split like url https://www.elastic.co/guide/en/elasticsearch/guide/current/ngrams-compound-words.html, But minimum_should_match does not work when excute phrase as follows:
GET /my_index/my_type/_search
{
    "query": {
        "match": {
            "text": {
                "query":                "Gesundheit",
                "minimum_should_match": "80%"
            }
        }
    }
}
result still matches “Militär-ges-chichte” and “Rindfleischetikettierungsüberwachungsaufgabenübertragungs-ges-etz,” both of which also contain the trigram ges. Any ideas to process this condition? thanks

**Comment by clintongormley** [comment]
Please ask questions like these in the forum instead: https://discuss.elastic.co/

The github issues list is reserved for bug reports and feature requests only.

You also need to provide a full recreation, including your index settings and mappings, indexing the docs, the results you expect and the results you actually see

**Comment by lixiuna0908** [comment]
Thank you. I have ask this question in https://discuss.elastic.co/t/minimun-should-match-does-not-work-at-es-5-version/88642
