### ISSUE TITLE
Elasticsearch fails with impossible NullPointerExceptions

### ISSUE THREAD

**Issue by Gnitry** [elastic/elasticsearch#25091]
**Elasticsearch version**: 5.4.1

**Plugins installed**: []

**JVM version**: OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)

**OS version**: Linux fs-deb 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
I have this scheme:
5 x Filebeats (Windows 10) -> Logstash (5.4.1) -> Elasticsearch (5.4.1) -> Kibana (5.4.1)
Logstach, Elasticsearch and Kibana are on the same linux machine (16Gb RAM)
The only changes I did in elastic settings are:
```
-Xms8g
-Xmx8g
```
(I made this change not in the beginning but later after some problem googling)
and 
`network.host: 0.0.0.0`

Very often I get elasticsearch crashes with these logs:

https://pastebin.com/raw/kDHE23XS
https://pastebin.com/raw/cJ0Z0qqt
https://pastebin.com/raw/PTGM9L20

Sometimes elasticsearch service just stops with ABORT like described [here](https://discuss.elastic.co/t/es-node-killed-with-6-abrt-how-to-find-out-why-and-by-whom/24108/2) 

Logstash configuration:
https://pastebin.com/raw/7rdsXdcj

jvm.options:
https://pastebin.com/hYDg1gyZ

elasticsearch.yml:
https://pastebin.com/qYMGcSpw

I tried to use systat to find something interesting with cpu or memory, but I didn't see any weird behaviour.

**Comment by jpountz** [comment]
Something is broken: one of the reported NPEs is impossible, and another one points to a line that only has a closing bracket of a method definition. We observed something similar with our internal testing that we have not been able to fully identify yet, but is likely JVM-related. In the mean time, can you check whether these issues reproduce if you use another JVM (eg. the one provided by Oracle).

**Comment by jpountz** [comment]
I renamed the issue so that it better describes the most prominent issue.

**Comment by nik9000** [comment]
I think it is worth doing some hardware tests. I got some of these "funny" NPEs on Debian a couple of months ago and it turned out that I had bad RAM. I ran Memtest86 and that didn't catch it but my motherboard would restart a few times before posting. I contacted my motherboard manufacturer and they told me that was almost always bad RAM. I removed the sticks one by one and found a bad stick, RMAed it, and the problem went away.

Weird stuff. I had expected Memtest86 to see the problem, but no such luck.

**Comment by Gnitry** [comment]
Yeas, you are right. I checked PC by Memtest86 and found problems with memory.
![img_0153 1](https://user-images.githubusercontent.com/3641011/26937440-5349f78e-4cac-11e7-801d-0565d22f0a75.JPG)

Now I need to change memory chip card and try Elastic again.

Thank you all !

**Comment by nik9000** [comment]
Awesome! Well, not awesome for you, I guess. Sorry about your memory! I'm glad it was "just" memory though.
