### ISSUE TITLE
[CI] InternalEngineTests.testConcurrentWritesAndCommits

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#25110]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/274/consoleFull

The test timed out and the reproduce line does not reproduce on my Linux box, I don't have a Windows box to check.

```
REPRODUCE WITH: gradle :core:test -Dtests.seed=6CF2AF390AD96E74 -Dtests.class=org.elasticsearch.index.engine.InternalEngineTests -Dtests.method="testConcurrentWritesAndCommits" -Dtests.security.manager=true -Dtests.locale=zh-TW -Dtests.timezone=Asia/Kuala_Lumpur
```

At first I thought that maybe that test was to heavy but actually the numbers of threads and docs look reasonable to me. Maybe we should just avoid MockDirectoryWrapper in this particular test?

**Comment by cbuescher** [comment]
This might be another instance of this failure:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/335/consoleFull
