### ISSUE TITLE
corrupted snapshot system

### ISSUE THREAD

**Issue by ThomasADavis** [elastic/elasticsearch#25117]
**Describe the feature**:

**Elasticsearch version**: 
5.4.1

**Plugins installed**: []
x-pack

**JVM version** (`java -version`):
java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b12)
OpenJDK 64-Bit Server VM (build 25.131-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Linux d8-r12-c0-n1 4.11.3-1.el7.elrepo.x86_64 #1 SMP Fri May 26 09:19:46 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Snapshots are messed up.

            "repository": "cori-modbus-2017.06.03",
            "shards_stats": {
                "done": 894,
                "failed": 13931,
                "finalizing": 0,
                "initializing": 3866,
                "started": 0,
                "total": 18691
            },
            "snapshot": "status",
            "state": "STARTED",
            "stats": {
                "number_of_files": 25673,
                "processed_files": 25662,
                "processed_size_in_bytes": 1085177064157,
                "start_time_in_millis": 1496711662070,
                "time_in_millis": 99865,
                "total_size_in_bytes": 1085322482511
            },
            "uuid": "mxC9N2ToQi-__DJen98w5g"
        }

I cannot remove this snapshot.

index: cori-modbus-full-2017.06.05
LOCATION: /glusterfs/ec0/es5/cori-modbus-full-2017.06.05
{"acknowledged":true}
{"error":{"root_cause":[{"type":"concurrent_snapshot_execution_exception","reason":"[cori-modbus-full-2017.06.05:cori-modbus-full-2017.06.05]a snapshot is already running"}],"type":"concurrent_snapshot_execution_exception","reason":"[cori-modbus-full-2017.06.05:cori-modbus-full-2017.06.05]a snapshot is already running"},"status":503}

Also snapshot status shows lots of snapshots, but no repository associated with them.
tdavis@d8-r13-c1-n1 elastic]$ sh -x es5.sh snapshot_stop cori-modbus-2017.06.03
+ MASTER=es5-master-1:9200
+ TIMEOUT=2
+ snapshot_stop cori-modbus-2017.06.03
+ curl -s -X DELETE http://es5-master-1:9200/_snapshot/cori-modbus-2017.06.03/cori-modbus-2017.06.03
{"error":{"root_cause":[{"type":"concurrent_snapshot_execution_exception","reason":"[cori-modbus-2017.06.03:cori-modbus-2017.06.03/NCyCZ5SwQPi9TJMJwgvmbA] another snapshot is currently running cannot delete"}],"type":"concurrent_snapshot_execution_exception","reason":"[cori-modbus-2017.06.03:cori-modbus-2017.06.03/NCyCZ5SwQPi9TJMJwgvmbA] another snapshot is currently running cannot delete"},"status":503}+ echo

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. no idea what messed this up.
 2. 
 3.

**Provide logs (if relevant)**:

[snapshots.txt](https://github.com/elastic/elasticsearch/files/1059120/snapshots.txt)
[snap-repo.txt](https://github.com/elastic/elasticsearch/files/1059121/snap-repo.txt)

**Comment by abeyad** [comment]
It looks like you've been creating a repository instead of a snapshot.  The `snap-repo.txt` file has tons of repositories that you have created.  Without a way to reproduce this, I don't know how you got yourself in this situation, other than you were creating a repository where you meant to create a snapshot.

Your best bet is to stop your master node, restart it, then delete all the repositories you've created and start afresh.  

Lastly, if you can kindly post such questions to our discussion forum (https://discuss.elastic.co/), which we provide as a means to get help with issues running Elasticsearch.  We reserve github for known bug reports and feature requests.
