### ISSUE TITLE
empty cluster with all live nodes but stuck in red state

### ISSUE THREAD

**Issue by sinsonglew** [elastic/elasticsearch#25126]
**Describe the feature**:

**Elasticsearch version**: 5.1.1

**Plugins installed**: []

**JVM version** (`java -version`): jdk8

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1. start nodes one by one
 2. change one node X's configuration and restart node X
 3. cat nodes show all nodes, cat health in red

**Provide logs (if relevant)**:

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by sinsonglew** [comment]
this's not a bug, just the settings **_gateway.recover_after_nodes_** I got wrong, detail explanations [https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html](url)
