### ISSUE TITLE
PostingsHighlighting is broken with boosting to multi-fields in ES 5.x

### ISSUE THREAD

**Issue by DivyaMalini** [elastic/elasticsearch#25131]
**Elasticsearch version**: 5.4.0

**Scenario**: 
We have a multi-field indexed with offsets, for instance 'A' the field 'A.B' the sub-field . We query on both the fields to boost the results if matches are found in both.  Now in ES 5.4.0 , i observe when i try to boost on the subfield (A.B) and try to fetch the highlight for the same, highlight hits are missing. _This scenario was totally working fine in ES2.X(we used 2.4.1)._

**Repro steps**:
Index mapping - 
PUT my_index
{
  "mappings": {
    "my_type": {
      "properties": {
        "city": {         
          "fields": {
              "raw": {
                  "type": "string",
                  "index_options": "offsets"
              }
          },
           "type": "string",
          "index_options": "offsets"
        }
      }
    }
  }
}

**Sample indexed data**:
PUT my_index/my_type/1
{
    "city": "New York"
}

**Sample Query**: 
**_(Failure case)_**
POST my_index/my_type/_search
{
   "from": 0,
   "size": 100,
   "highlight": {
      "fields": {
         "city.raw": {
            "type": "postings"
         }
      },
      "require_field_match": true
   },
   "query": {
      "query_string": {
         "query": "y*k",
         "fields": [
            "city.raw^2",
            "city^2"
         ]
      }
   }
}

**_(Passing case)_**
POST my_index/my_type/_search
{
   "from": 0,
   "size": 100,
   "highlight": {
      "fields": {
         "city.raw": {
            "type": "postings"
         }
      },
      "require_field_match": true
   },
   "query": {
      "query_string": {
         "query": "y*k",
         "fields": [
            "city.raw",
            "city^2"
         ]
      }
   }
}

**Comment by jimczi** [comment]
This bug has been fixed in 5.4.1 but only for the `unified` highlighter:
https://issues.apache.org/jira/browse/LUCENE-7769

The `postings` highlighter is deprecated in Lucene (and removed in the next version) in favor of the `unified`. The `unified` highlighter is a fork of the `postings` with a similar behavior when index_options is set to `offset`. You should use this new highlighter and upgrade to 5.4.1.
