### ISSUE TITLE
Incorrect default for similarity in reference docs of text/keyword datatypes

### ISSUE THREAD

**Issue by robinst** [elastic/elasticsearch#25141]
The [similarity section](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/similarity.html) in the reference says that BM25 is default:

> The similarity setting provides a simple way of choosing a similarity algorithm other than the default BM25, such as TF/IDF.

But the [`similarity` parameter in the `text` section](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/text.html#text-params) says the opposite:

> Which scoring algorithm or similarity should be used. Defaults to classic, which uses TF/IDF.

The [`keyword` section](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/keyword.html#keyword-params) has the same problem.

I can create a pull request, but I'm not sure which branch to target. It's probably easier for yous to fix it and merge it to all the necessary branches.

**Comment by jimczi** [comment]
Thansk @robinst 
I pushed https://github.com/elastic/elasticsearch/commit/ad905924ae6dc42e2e7ff8dead9003c5a0c64be7
