### ISSUE TITLE
Support http streaming in Java Rest Client

### ISSUE THREAD

**Issue by arosenheinrich** [elastic/elasticsearch#25146]
We have  use cases where we use elasticsearch as only datastore throwing all kinds of data in it (simplifying our tech stack), including large files that are only stored and fetched later on. Using "standard" http requests we encountered problems as you can run in several limitations, like body size, buffer limits, timeouts and so on. Therefore we had to implement an own client that supported http streaming requests so we could upload and download large data.

It would be really helpful to have an option for using http streaming in the Java Rest Client and therefore in the Java High Level Rest Client.

**Comment by javanna** [comment]
Hi @arosenheinrich what is your own client based on? We depend on apache http async client and we can expose pretty much anything that such library supports. Can you expand a bit on what you did and what would help in your case?

**Comment by arosenheinrich** [comment]
Of course, sorry for the late answer. 

The problem is that we can have quite large (several 100MB) data for a single field in a document. So passing or receiving this data with apache http async client will be a problem because of memory consumption for buffering the object. Apart you could(?) run in limitation like timeouts or body size. Therefore we are using good ol' sync client instead of async and we provide input or output streams as parameter or response so that memory consumption is way lower. Apart, at least in our case this is helpful, we can use libraries that will process such a result stream but couldn't handle a data object of that size. 

So basicly what would help us would be an option to perform a sync request instead of async and at least get an output stream as result instead of the whole object. Providing data via input stream would be even better ;)

Does that make sense to you and would this be useful in a more general context?

**Comment by nik9000** [comment]
> The problem is that we can have quite large (several 100MB) data for a single field in a document.

This is going to cause Elasticsearch heartburn in general, I think.

**Comment by s1monw** [comment]
> The problem is that we can have quite large (several 100MB) data for a single field in a document. So passing or receiving this data with apache http async client will be a problem because of memory consumption for buffering the object. 

elasticsearch is pretty much suffering from the same issue. We have to buffer the documents in memory on all nodes that are involved in the indexing process. There is no streaming of documents in elasticseach itself. From that perspective it might be considered a feature if you don't have a streaming option. I personally think it's good if an API reflects what the software / backend is made for rather than giving the user the impression it has been made for streaming large amounts of data.

> Apart you could(?) run in limitation like timeouts or body size. 

also this is a feature here? I mean the body size limitation is already big, I think it's 1GB at this point but I might be mistaken. Timeouts can be configured on the client side and if transferring large documents is running into and issue I guess this is exactly why this option is configurable.

**Comment by arosenheinrich** [comment]
Hi Simon, thanks for the clarifications. I agree, moving the problem from client side to the server ain't really solving the problem. 
I don't like the idea of solving this by configuration, as you pointed out there are good reasons why they are set the way they are and changing them for rarely used special cases might mask other problems with the majority of use cases. 

 Maybe it would be interesting to think about supporting streaming in elasticsearch for datatypes like binary where no indexing is done and data can be large, but that is certainly beyond the scope of my request. I will therefore close it here, thanks for your explanations!
