### ISSUE TITLE
Error with range query inside "not or"

### ISSUE THREAD

**Issue by kevinder** [elastic/elasticsearch#25140]
**Elasticsearch version**: 2.4.5

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_111

**OS version** (`uname -a` if on a Unix-like system): 

**Description of the problem including expected versus actual behavior**:

Using a range query inside an `or` inside a `not` causes an error on 2.4.5, but not on 1.7.1.

**Steps to reproduce**:

This query works fine:

```
{
  "filter": {
    "or": [
      { "range": { "value": { "gte": 1, "lt": 3 } } },
      { "range": { "value": { "gte": 5, "lt": 7 } } }
    ]
  }
}
```

but wrapping the `or` in a `not` will cause an error:

```
{
  "filter": {
    "not": {
      "or": [
        { "range": { "value": { "gte": 1, "lt": 3 } } },
        { "range": { "value": { "gte": 5, "lt": 7 } } }
      ]
    }
  }
}
```

where the error is a `query_parsing_exception` with message `[or] query does not support [gte]`.

That doesn't seem accurate because it works fine without the `not`.

We are trying to upgrade to 2.x and getting this error there. Our existing version is 1.7.1 where there is no error.   (The error occurs on both 2.4.5 and 2.0.0.) Converting our code to use `should`/`must` syntax is a huge amount of work for various reasons, so we'd prefer any other workarounds or suggestions. Thanks!

**Provide logs (if relevant)**:

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

Note that `or` has been deprecated as per: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-or-query.html
It has been removed in 5.x series.

Use `should` then. But please feel free to ask for more information on discuss.
