### ISSUE TITLE
Error when import visualization into Elasticsearch 6.0.0-alpha2

### ISSUE THREAD

**Issue by sadok-f** [elastic/elasticsearch#25155]
**Elasticsearch version**: Elasticsearch 6.0.0-alpha2

**Plugins installed**: []

**JVM version**: openjdk version "1.8.0_131"

**OS version**: Linux 0a1950b835b7 3.13.0-117-generic #164-Ubuntu SMP Fri Apr 7 11:05:26 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
I'm using a python script to import visualization, search and dashboard into kibana, it works perfect with latest stable version: 5.4.1
but with this version 6.0.0-alpha2, it throw this error:
```
Posting: e641f850-3f0c-11e7-a6f3-0911a5674aba (visualization)
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
```
**Steps to reproduce**:

 1. clone this script: https://gist.github.com/sadok-f/7085c0be7194136bd5c7fabb2f705b56
 2. run it `python load_kibana_objects.py export.json http://192.168.33.11:9200`

Thank you !

**Comment by jasontedor** [comment]
This is not a bug on our side. You need to set the header `Content-Type` to `application/json`. We reserved GitHub for verified bug reports and feature requests. If you need additional help, please ask on the [forum](https://discuss.elastic.co).

**Comment by jasontedor** [comment]
Also, you can see the same behavior in 5.4.1 if you set `http.content_type.required` to `true`. This is the default in 6.0.0 and is unchangeable.

**Comment by sadok-f** [comment]
Thank you for your quick response,

**Comment by jasontedor** [comment]
You're welcome.
