### ISSUE TITLE
Scroll request never ends on mixed version cluster (5.1.2/5.3.2)

### ISSUE THREAD

**Issue by nomoa** [elastic/elasticsearch#25158]
While doing a rolling restart on a cluster to upgrade from 5.1.2 to 5.3.2 we noticed that a script used to rebuild some indices stopped to function properly. The scroll request used constantly returned the same set of results.

Looking into details it appeared to only happen for small indices where the initial scroll request returned all the hits. But also only on indices with a shard that was hosted by nodes with different versions.

Using `preference=_only_nodes:old_version_node` I was able to reproduce the problem consistently on the production cluster.
I have not verified that I could reproduce the problem on a test environment but I think we can reproduce it with:

- Install elastic 5.1.2 a cluster with 2 nodes (node1, node2).
- Create a small index with 5 docs (one shard and one replica so that the index is hosted on both nodes)
- upgrade node1 to elastic to 5.3.2
- Create a scroll context by sending the REST request to node1 but forcing the transport request to be sent to node2: `curl -s -XGET 'node1:9200/test/_search?preference=_only_nodes:node2&size=20&scroll=15m' | jq ._scroll_id`
- The resulting scroll_id is broken calling /_search/scroll multiple times on it will return the same set of results (the node used to send the REST request does not matter)
- Sending the initial rest request to node2 with `preference=_only_nodes:node2` does not trigger the issue
- Sending the initial rest request to node2 with `preference=_only_nodes:node1` does not trigger the issue

So it looks like that if scroll context is created on a node at v5.1.2 but the transport request is sent from a node at v5.3.2 the scroll context is broken.

The problem only appeared on small indices but I did not carefully checked larger indices.

**Comment by jaymode** [comment]
> Create a small index with 5 docs (one shard and one replica so that the index is hosted on both nodes)

The single shard scroll issue between versions >= 5.3 and those < 5.3 has been fixed by https://github.com/elastic/elasticsearch/pull/24512, which was released in 5.4.1. See https://www.elastic.co/guide/en/elasticsearch/reference/5.4/release-notes-5.4.1.html#bug-5.4.1
