### ISSUE TITLE
Problem opening Gradle project with Eclipse

### ISSUE THREAD

**Issue by WojciechLuczkow** [elastic/elasticsearch#25153]
**Elasticsearch version**:
5.4.1
**Plugins installed**: []

**JVM version** (`java -version`):
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
WIndows 10 Pro 10.0 compilation 10586

**Description of the problem including expected versus actual behavior**:
Could no setup project using Gradle and Eclipse
Process fails when trying to download junit 4.12

I can fix it locally by modifying \buildSrc\build.gradle

and changing 
repositories {
  jcenter()
}

to 
repositories {
  mavenCentral()
  jcenter()
}

**Steps to reproduce**:
Try to Import Project using eclipse

**Provide logs (if relevant)**:
C:\elasticsearch>gradle
Download https://jcenter.bintray.com/junit/junit/4.12/junit-4.12.jar

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':buildSrc:runtimeClasspath'.
> Could not download junit.jar (junit:junit:4.12)
   > Could not get resource 'https://jcenter.bintray.com/junit/junit/4.12/junit-4.12.jar'.
      > Response 304: Not Modified has no content!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by cbuescher** [comment]
@WojciechLuczkow I'm sorry to hear you are having trouble with the project setup. However, Elastic reserves GitHub for bug reports and feature requests but provides a Discourse forum and IRC channels for general questions like this. I hope you mind closing this issue and ask you to raise this question in the forums.

**Comment by martijnvg** [comment]
@WojciechLuczkow Please follow the Eclipse instructions mentioned here: https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-to-the-elasticsearch-codebase 

If it still doesn't work please ask on the forum like @cbuescher replied.

**Comment by WojciechLuczkow** [comment]
@cbuescher 
I don't have a problem - I solved it quickly...
I provided you with solution you may find useful adapting

Have you read description or just posted ready to send message?

**Comment by cbuescher** [comment]
@WojciechLuczkow sorry, I didn't get that you were providing the answer to your question yourself. Maybe one more reason to share your findings in the forum.

**Comment by varundbest** [comment]
@WojciechLuczkow Mind Sharing your findings?

**Comment by WojciechLuczkow** [comment]
@varundbest 

It is all above :) In build.gradle section repositories add mvnCentral next to jcenter() so it will be 
repositories {
mavenCentral()
jcenter()
}
