### ISSUE TITLE
De-Humanize _CAT API store sizes

### ISSUE THREAD

**Issue by dngferreira** [elastic/elasticsearch#25151]
Using the _cat API indices and shards p.ex give the store sizes in a human readable format, Mb, Gb, etc.
Can we get a parameter to disable this "humanizing" of the results so we can get results that are more precise for a machine to analize?

**Comment by dadoonet** [comment]
I believe you are looking for this: https://www.elastic.co/guide/en/elasticsearch/reference/current/cat.html#numeric-formats

I'm closing but feel free to reopen or better ask on discuss.elastic.co if you think it does not work for you.

**Comment by dngferreira** [comment]
That's what I was looking for.

Thanks
