### ISSUE TITLE
[docs] Full cluster restart docs link to rolling restart at 3., which can be confusing. 

### ISSUE THREAD

**Issue by jakommo** [elastic/elasticsearch#25175]
On [the full cluster restart guide](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/restart-upgrade.html) in  `3. Shutdown and upgrade all nodes`, we link to the [upgrade node section of the rolling restart guide](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/rolling-upgrades.html#upgrade-node).
This can be confusing for new users as it's not clear if one just need to follow this step in the rolling guide and then switch back to the full cluster restart guide. 
I think we should just copy this section from the rolling guide to the full cluster restart guide, instead of linking.

**Comment by javanna** [comment]
I find the current docs clear and I think it's a pity to copy the single node upgrade to the full cluster restart page. Is this a problem that you encountered with some user? What do you find confusing? Maybe the duplication of the "Upgrade any plugins" section in both pages?

**Comment by javanna** [comment]
Closing due to lack of feedback. I think duplicating is not a good solution. It will cause more confusion, and probably the two pages will go out-of-sync. Feel free to reopen with more feedback and/or alternative proposals.

**Comment by jakommo** [comment]
Sorry for the lack of feedback @javanna . I was on vacation and your post slipped through.
I had at least two users being confused by this, but I can also understand the issues that come with duplication. 
I'll try to get more details on what's the confusing part, should I see another user struggling with this.
