### ISSUE TITLE
`:qa:verify-version-constants` fail on 5.x/5.5

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#25170]
The test fails while trying to spin up 2.0.0 nodes

```
|  [log]
|    Warning: Ignoring JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
|    Please pass JVM parameters via JAVA_OPTS instead
|    ERROR: Parameter [-E]does not start with --
|-----------------------------------------
```

see: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.5+bwc-tests/11/console

**Comment by jasontedor** [comment]
Closed via f38097578c9c0c135cc5c5f37a31928cdd6527df and 58bc8977c7db989cfd47d202cfbcd7e30cfb5f9c
