### ISSUE TITLE
MapperParsingException[object mapping for [matched_details.C03BT006] tried to parse field [null] as object, but found a concrete value]

### ISSUE THREAD

**Issue by wlxy** [elastic/elasticsearch#25191]
**I defined the mapping like this**:
`"properties": {
            "id": {
                "type": "string",
        "index": "not_analyzed"
            },
            "level": {
                "type": "string"
            },
            "matched_sources": {
                "type": "string"
            },
            "black_data": {
                "type": "string"
        },
        "black_class": {
        "type": "string"
        },
        "black_type": {
        "type": "string"
        },
        "matched_details": {
        "type": "nested"
        }
        }`

**but when I loaded data to es,some cases would get this error**:
`tried to parse field [null] as object, but found a concrete value]`

**however,most of the cases are successful, and all the cases have  the same format.
when I get the case that got error to `http://json.cn/` to parse, it's really a json,I don't know 
what's wrong about the es.**

**Comment by bleskes** [comment]
@wlxy can I ask you to ask these kind of questions on our [forum](discuss.elastic.co). If this turns out to be a bug on the ES side, we can open an issue here, with a full reproduction,  version etc. Cheers.

**Comment by wlxy** [comment]
That's would be great, thanks a lot.

**Comment by wlxy** [comment]
@bleskes  That's would be great, thanks a lot.

**Comment by wlxy** [comment]
@bleskes  I'm sorry, but when I try to click the forum, I can not open the web.

**Comment by bleskes** [comment]
@wlxy sorry, I didn't add the http prefix: http://discuss.elastic.co  (I fixed the comment as well)

**Comment by wlxy** [comment]
@bleskes Could I ask you some question about the datatype of ES. Here it is : I have a piece of data with the format of json, like this:
![image](https://user-images.githubusercontent.com/22311242/27114753-5af977f2-50f8-11e7-9c60-d32429c61510.png)

so, what kind of datatype do you think I should define for the field of "matched_details".
I'd appreciate it if you can help me with this.

**Comment by bleskes** [comment]
@wlxy please ask these kind of things on our [forum](http://discuss.elastic.co)

**Comment by wlxy** [comment]
@bleskes Sorry,I just can not open this web  "http://discuss.elastic.co ",thanks anyway.
