### ISSUE TITLE
geoshape use multipolygon data, than I use 'intersects' to search ,the point not in the 'multipolygon',but show

### ISSUE THREAD

**Issue by xionghc628** [elastic/elasticsearch#25202]
this is data：

"serviceRange": {
    "coordinates": [
        [
            [
                [
                    "116.43601566553116",
                    "39.95765390946156"
                ],
                [
                    "116.44979149103165",
                    "39.95781838646284"
                ],
                [
                    "116.45150810480118",
                    "39.95127189636893"
                ],
                [
                    "116.43545776605606",
                    "39.952061456041555"
                ],
                [
                    "116.43601566553116",
                   "39.95765390946156"
                ]
            ]
        ],
        [
            [
                [
                    "106.53720527887344",
                    "29.564131351789236"
                ],
                [
                    "106.55759006738663",
                    "29.564131351789236"
                ],
                [
                    "106.55467182397842",
                    "29.55674014982797"
                ],
                [
                    "106.54020935297012",
                    "29.55659082704403"
                ],
                [
                    "106.53510242700577",
                    "29.559651900004216"
                ],
                [
                    "106.53720527887344",
                    "29.564131351789236"
                ]
            ]
        ]
    ],
    "type": "multipolygon"
}

the version is 1.4

now，I intersects “39.969901,116.433181” to search,than find this data.

I think that I can't search this data!so,what's wrong?thanks!

**Comment by clintongormley** [comment]
@xionghc628 Please provide a recreation of the problem, plus all of the other information that was requested in the new-issue template

**Comment by xionghc628** [comment]
@clintongormley can you help me? I already write this case,thanks!

**Comment by clintongormley** [comment]
> the version is 1.4

You need to upgrade.  This version is no longer supported
