### ISSUE TITLE
Cluster Stats API Returning Incorrect Values

### ISSUE THREAD

**Issue by 326TimesBetter** [elastic/elasticsearch#25207]
I have also raised this issue on the elastic forums here where it has received a little bit of discussion: https://discuss.elastic.co/t/es-cluster-stats-api-returning-false-values/84949

**Elasticsearch version**: 5.3.0

**Plugins installed**: [
mapper-size,
x-pack,
install-repository-hdfs-plugin,
install-repository-s3-plugin,
install-repository-gcs-plugin
]

**JVM version** (`java -version`):
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux kibana-uscen-a-c016-n001 4.4.0-45-generic #66~14.04.1-Ubuntu SMP Wed Oct 19 15:05:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
On some of our nodes, when we hit the cluster stats api in order to check the fs stats and see how much disk we are using, we receive a response of 8192pb/8192pb.
Ex. `curl "$(hostname -i):9200/_cluster/stats?human&pretty"` (jump down to fs, third from bottom)
```
{
  "_nodes" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "cluster_name" : "c016-logging",
  "timestamp" : 1497382449906,
  "status" : "green",
  "indices" : {
    "count" : 75,
    "shards" : {
      "total" : 390,
      "primaries" : 195,
      "replication" : 1.0,
      "index" : {
        "shards" : {
          "min" : 2,
          "max" : 10,
          "avg" : 5.2
        },
        "primaries" : {
          "min" : 1,
          "max" : 5,
          "avg" : 2.6
        },
        "replication" : {
          "min" : 1.0,
          "max" : 1.0,
          "avg" : 1.0
        }
      }
    },
    "docs" : {
      "count" : 69448767,
      "deleted" : 35952
    },
    "store" : {
      "size" : "265.8gb",
      "size_in_bytes" : 285424410206,
      "throttle_time" : "0s",
      "throttle_time_in_millis" : 0
    },
    "fielddata" : {
      "memory_size" : "69.7kb",
      "memory_size_in_bytes" : 71400,
      "evictions" : 0
    },
    "query_cache" : {
      "memory_size" : "73.4mb",
      "memory_size_in_bytes" : 77011824,
      "total_count" : 180142263,
      "hit_count" : 173476473,
      "miss_count" : 6665790,
      "cache_size" : 61613,
      "cache_count" : 92730,
      "evictions" : 31117
    },
    "completion" : {
      "size" : "0b",
      "size_in_bytes" : 0
    },
    "segments" : {
      "count" : 6744,
      "memory" : "579.4mb",
      "memory_in_bytes" : 607625919,
      "terms_memory" : "428.9mb",
      "terms_memory_in_bytes" : 449782182,
      "stored_fields_memory" : "88.5mb",
      "stored_fields_memory_in_bytes" : 92872968,
      "term_vectors_memory" : "0b",
      "term_vectors_memory_in_bytes" : 0,
      "norms_memory" : "17.7mb",
      "norms_memory_in_bytes" : 18603328,
      "points_memory" : "4.9mb",
      "points_memory_in_bytes" : 5192169,
      "doc_values_memory" : "39.2mb",
      "doc_values_memory_in_bytes" : 41175272,
      "index_writer_memory" : "43.6mb",
      "index_writer_memory_in_bytes" : 45782632,
      "version_map_memory" : "215.7kb",
      "version_map_memory_in_bytes" : 220924,
      "fixed_bit_set" : "0b",
      "fixed_bit_set_memory_in_bytes" : 0,
      "max_unsafe_auto_id_timestamp" : 1497312009291,
      "file_sizes" : { }
    }
  },
  "nodes" : {
    "count" : {
      "total" : 5,
      "data" : 3,
      "coordinating_only" : 1,
      "master" : 3,
      "ingest" : 4
    },
    "versions" : [
      "5.3.0"
    ],
    "os" : {
      "available_processors" : 10,
      "allocated_processors" : 10,
      "names" : [
        {
          "name" : "Linux",
          "count" : 5
        }
      ],
      "mem" : {
        "total" : "36.5gb",
        "total_in_bytes" : 39216926720,
        "free" : "2.9gb",
        "free_in_bytes" : 3192020992,
        "used" : "33.5gb",
        "used_in_bytes" : 36024905728,
        "free_percent" : 8,
        "used_percent" : 92
      }
    },
    "process" : {
      "cpu" : {
        "percent" : 77
      },
      "open_file_descriptors" : {
        "min" : 315,
        "max" : 1414,
        "avg" : 677
      }
    },
    "jvm" : {
      "max_uptime" : "34d",
      "max_uptime_in_millis" : 2945872000,
      "versions" : [
        {
          "version" : "1.8.0_25",
          "vm_name" : "Java HotSpot(TM) 64-Bit Server VM",
          "vm_version" : "25.25-b02",
          "vm_vendor" : "Oracle Corporation",
          "count" : 5
        }
      ],
      "mem" : {
        "heap_used" : "5.9gb",
        "heap_used_in_bytes" : 6391948904,
        "heap_max" : "14.9gb",
        "heap_max_in_bytes" : 16018964480
      },
      "threads" : 356
    },
    "fs" : {
      "total" : "8192pb",
      "total_in_bytes" : 9223372036854775807,
      "free" : "8192pb",
      "free_in_bytes" : 9223372036854775807,
      "available" : "8192pb",
      "available_in_bytes" : 9223372036854775807,
      "spins" : "true"
    },
    "plugins" : [
      {
        "name" : "x-pack",
        "version" : "5.3.0",
        "description" : "Elasticsearch Expanded Pack Plugin",
        "classname" : "org.elasticsearch.xpack.XPackPlugin"
      },
      {
        "name" : "mapper-size",
        "version" : "5.3.0",
        "description" : "The Mapper Size plugin allows document to record their uncompressed size at index time.",
        "classname" : "org.elasticsearch.plugin.mapper.MapperSizePlugin"
      }
    ],
    "network_types" : {
      "transport_types" : {
        "netty4" : 4,
        "security4" : 1
      },
      "http_types" : {
        "netty4" : 4,
        "security4" : 1
      }
    }
  }
}
```
In reality, each data node has a 200gb disk for a total of 600gb, and I would expect it to reflect that.

**Steps to reproduce**:

We dont know what the precise conditions are that created this issue but we have one cluster currently demonstrating it, and that cluster consists of:

3 Dual Master/Data Nodes
1 Client Node (also running kibana on the same machine)
1 Tribe Node

When hitting the stats api, from the Master/Data nodes, we receive the expected result:
```
    "fs" : {
      "total" : "600gb",
      "total_in_bytes" : 644268523520,
      "free" : "328gb",
      "free_in_bytes" : 352259792896,
      "available" : "297.5gb",
      "available_in_bytes" : 319443623936,
      "spins" : "true"
    }
```
But when hitting the stats api from the client node, we receive the incorrect result:
```
    "fs" : {
      "total" : "8192pb",
      "total_in_bytes" : 9223372036854775807,
      "free" : "8192pb",
      "free_in_bytes" : 9223372036854775807,
      "available" : "8192pb",
      "available_in_bytes" : 9223372036854775807,
      "spins" : "true"
    }
```
While I don't know what conditions to recreate it, we do have a live cluster in this state which I would be happy to run any diagnostics against.

**Comment by ywelsch** [comment]
This could have to do with https://github.com/elastic/elasticsearch/pull/23093.
@dakrone can you have a look please?

**Comment by 326TimesBetter** [comment]
Any update on this issue?? We used to have crons that depended on this api to calculate disk space in the cluster.

**Comment by dakrone** [comment]
I'm not sure there's anything we can do for this, we adjust the filesystem values only if they are negative, see:

https://github.com/elastic/elasticsearch/blob/9c795bd838864647553b317b9da2b5a40f1a7242/core/src/main/java/org/elasticsearch/monitor/fs/FsProbe.java#L157-L159

and 

https://github.com/elastic/elasticsearch/blob/9c795bd838864647553b317b9da2b5a40f1a7242/core/src/main/java/org/elasticsearch/monitor/fs/FsProbe.java#L144-L147

So in these cases, either the FS is reporting a negative number (doesn't sound like it in this case), or adding all of the sub nodes' information overflows the largest value a `long` can hold:

https://github.com/elastic/elasticsearch/blob/9c795bd838864647553b317b9da2b5a40f1a7242/core/src/main/java/org/elasticsearch/monitor/fs/FsInfo.java#L137-L139

In which case, this is a protection against returning a negative value and not something we can handle until https://bugs.openjdk.java.net/browse/JDK-8162520 is fixed

**Comment by dakrone** [comment]
Going to close this for now since there is no fix version on the JDK bug, once the bug is fixed we can revisit this.
