### ISSUE TITLE
[DOCS] Clarify search.remote.connect for all dedicated nodes

### ISSUE THREAD

**Issue by lcawl** [elastic/elasticsearch#25210]
The Node documentation in the Elasticsearch Reference (https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html) contains the following information:

"...To create a dedicated ingest node, set:
...search.remote.connect: false

...To create a dedicated coordinating node, set:
...search.remote.connect: false
..."

@pickypg asked: Should this be disabled for other "dedicated" node types too (particularly the dedicated master node)?

**Comment by javanna** [comment]
@eskibars can you comment on this please? Does it make sense to make the proposed change to the docs?

**Comment by eskibars** [comment]
The change makes sense.  It was partially done in https://github.com/elastic/x-pack-elasticsearch/pull/1688 .  I just realized that didn't include changes for dedicated data nodes & dedicated master nodes, which it should

**Comment by javanna** [comment]
@eskibars thanks for the quick feedback. Do you have time to take this and send a PR?

**Comment by javanna** [comment]
this can be closed!
