### ISSUE TITLE
search_after is not support geo_distance

### ISSUE THREAD

**Issue by ztianyi312** [elastic/elasticsearch#25225]
**Describe the feature**:
We want to use search_after when sorting by geo_distance

**Comment by vseryakov** [comment]
Gives an error: Comparator type [CUSTOM] for field [latlon] is not supported in 5.5 and 5.6, 

the query is:

{ query: { bool: { must: { query_string: { query: '(status:Ready)' } }, filter: { geo_distance: { distance: 5000, latlon: [ 150.98081635595673, -34.194085878589426 ] } } } }, sort: [ { _geo_distance: { latlon: [ 150.98081635595673, -34.194085878589426 ], order: 'asc', unit: 'm', distance_type: 'arc' } } ], size: 3, search_after: [0] }

the latlon field is type of geo_point

**Comment by jimczi** [comment]
`search_after` fails when you set `unit` to `m` due to an internal optimization. Sorry I missed this case and thanks @vseryakov for spotting !
I opened https://github.com/elastic/elasticsearch/pull/26891
