### ISSUE TITLE
Windows Service installer ignores custom service names

### ISSUE THREAD

**Issue by afscrome** [elastic/elasticsearch#25231]
**Elasticsearch version**: 5.4.0

**Plugins installed**:  Default

**JVM version** (`java -version`): 1.8.0_131

**OS version** (`uname -a` if on a Unix-like system): Win Server 2012 R2

**Description of the problem including expected versus actual behavior**:

Before installing elastic search as a service, set the `SERVICE_ID` environment variable to a custom value.  Based on the documentation at https://www.elastic.co/guide/en/elasticsearch/reference/current/windows.html#windows-service-settings, I expect the service to be installed with the name defined in the 

**Steps to reproduce**:

Run the following powershell to install the elastic search service
```ps
$env:SERVICE_ID = 'SomeService'
.\elasticsearch-service.bat install
```

To fix this:
* If it is not intended to allow the service name to be customised, the docs need to be updated
* If it is intended to allow custom service names, update `elasticsearch-service.bat` to not overwrite any existing `SERVICE_ID` value https://github.com/afscrome/elasticsearch/commit/744bd290822a5dd9404fa1e9cbc1c9ffed0cc4c8 .

**Comment by cbuescher** [comment]
@afscrome I'm not an expert in the windows start script but your analysis makes sense to me. Would you be interested in submitting your patch as a pull request?

**Comment by afscrome** [comment]
PR submitted - #25255
