### ISSUE TITLE
indices.refresh API spec is out of date

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch#25234]
Based on my read of https://www.elastic.co/guide/en/elasticsearch/reference/5.x/indices-refresh.html it would seem that at least some of the parameters listed in https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/indices.refresh.json are no longer supported.

**Comment by bleskes** [comment]
@spalger indeed `operation_threading` and `force` are not relevant. Do you want to take this?

**Comment by spalger** [comment]
Happy to @bleskes

**Comment by amiram** [comment]
@spalger Any estimation on this?

**Comment by spalger** [comment]
5.x: c878ea951e
5.5: f1228db722
5.4: eed30a8e9b
5.3: 22d9043a36
5.2: ebe8bccb1c
5.1: b6fe1ea228
5.0: 84a4e535cc

**Comment by codebrain** [comment]
The Microsoft team generates the low level .NET client from the REST API specifications, so removing these properties propagates to the client as a binary compatibility breaking change within a major version (a semver API breaking change).

We can put in some patching code on this end to ensure that these properties are maintained and marked as [Deprecated] and we'll remove them in 6.x

/cc @elastic/microsoft
