### ISSUE TITLE
[docs] Document keystore eligible settings on S3 repository plugin and AWS discovery plugin

### ISSUE THREAD

**Issue by bczifra** [elastic/elasticsearch#25242]
The [AWS discovery](https://www.elastic.co/guide/en/elasticsearch/plugins/current/discovery-ec2-usage.html) and [S3 repository](https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3-repository.html) pages make no reference to the fact that the AWS credentials can be retrieved from the keystore, despite the fact that the [secure settings documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/secure-settings.html) indicates:`See documentation for each setting to see if it is supported as part of the keystore.` 

I can't seem to find any setting at all that includes any keystore-related information as part of its document.  Right now I think this is pretty confusing for our users.  Additionally, @rjernst [indicated](https://discuss.elastic.co/t/getting-aws-credentials-from-keystore-for-discovery-ec2-plugin/87958/7) that 

> setting discovery.ec2.access_key in elasticsearch.yml should not work. This setting should only be allowed in the keystore

so, if I understand that correctly, we shouldn't be [showing](https://www.elastic.co/guide/en/elasticsearch/plugins/current/discovery-ec2-usage.html) that this can be set in the elasticsearch.yml file.  

Also, based on [this](https://discuss.elastic.co/t/getting-aws-credentials-from-keystore-for-discovery-ec2-plugin/87958/5) post I think the `cloud.aws.*` settings need to be updated everywhere to instead be `discovery.ec2.*`, and `cloud.aws.region` should be `discovery.ec2.endpoint`.

**Comment by dadoonet** [comment]
@rjernst knows it. :) I'm marking that as a blocker for 6.0 final.
Feel free to remove.

**Comment by bczifra** [comment]
@dadoonet awesome.  i didn't quite understand `feel free to remove`. remove what?

**Comment by dadoonet** [comment]
I meant. Feel free to remove the blocker label.
Sorry :)

**Comment by rjernst** [comment]
This was addressed with #26033 and #26065
