### ISSUE TITLE
Deprecate fielddata on `_id`/`_uid`

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#25240]
Some features like `random_score` use fielddata on `_id` and our documentation sometimes recommends to sort on `_id` in order to have a stable sort across pages (eg. https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-search-after.html). However fielddata on such unique fields has a huge cost if you have significant amounts of data, we should move away from it.

We probably have two options here, which are to either add doc values to `_id` (#11887) but this proved controversial due to the overhead it adds to the index, or switch to `_doc` but this has the drawback of not being comparable across shards or after merges.

**Comment by jpountz** [comment]
We discussed in FixitFriday and agreed to cut over `random_score` to use sequence numbers for random score generation. The only drawback compared to today is that documents would get a different score after they are updated, even if the same seed is used.

Consistent sorting on different point-in-time snapshots was more controversial. Here are some opinions:
 - there is nothing we can do in that case, we should set expectations and just remove the recommendation to use the `_uid` as a tie breaker
 - we should recommend using `_seq_no` as a tie-breaker for that purpose rather than `_uid`. It would not be stable in case of updates but is the best we can provide which works in practice.
 - we should automatically append `_seq_no` to every `sort` internally. Same reasoning as the previous idea but without exposing `_seq_no` which is quite an expert/internal feature.

**Comment by rjernst** [comment]
>  The only drawback compared to today is that documents would get a different score after they are updated

I don't see how this is any different than the way it used to be, using the docid.  This is very trappy, to have a random score with the capability of setting a seed, but the seed does not actually guarantee anything.

Why not expose the ability to set what field is used, and make it required if using a seed.  Then the default can be a truly random score (using docid), but if a seed+field is set, that is used.

**Comment by jpountz** [comment]
I like that idea.
