### ISSUE TITLE
Wildcard when checking if index exists always returns 200

### ISSUE THREAD

**Issue by jbudz** [elastic/elasticsearch#25258]
**Elasticsearch version**: master, 5.4.

**Plugins installed**: none

**JVM version** (`java -version`): 1.8.0_121

**Steps to reproduce**:
Following https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-exists.html
5.4:
```
curl -XHEAD localhost:9200/index-that-does-not-exist-*
< HTTP/1.1 200 OK
```

2.4: 
```
curl -XHEAD localhost:9200/index-that-does-not-exist-*
< HTTP/1.1 404 Not Found
```

**Comment by jasontedor** [comment]
Duplicates #25056, you have to add `allow_no_indices=false` now. This should probably be documented.

**Comment by jasontedor** [comment]
I opened #25262.
