### ISSUE TITLE
 Elasticsearch reindex is not working 

### ISSUE THREAD

**Issue by hello4usharath** [elastic/elasticsearch#25260]
We have being trying to perform re indexing of existing to new index with change in mapping. But indexing is not happening properly.

health status index uuid pri rep docs.count docs.deleted store.size pri.store.size
green open ******* iso4UtTXSwuDTNrIMZXjpw 5 1 408486 84 10.4gb 5.2gb
green open ******* wSxaFkrXQJujiGOWhtyEDQ 5 1 408486 201678 29.6gb 15.8gb   - new index from above

docs.count is getting matched but not with docs.deleted and is not getting exited from sense plugin

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
