### ISSUE TITLE
Sum bucket aggregation cannot sum more than one level deep

### ISSUE THREAD

**Issue by andrewvc** [elastic/elasticsearch#25273]
Executing a sum_bucket aggregation with a bucket path multiple levels deep, like `bucket_1>bucket_2>metric` will fail with:

```
{
  "error": {
    "root_cause": [],
    "type": "search_phase_execution_exception",
    "reason": "",
    "phase": "fetch",
    "grouped": true,
    "failed_shards": [],
    "caused_by": {
      "type": "aggregation_execution_exception",
      "reason": "buckets_path must reference either a number value or a single value numeric metric aggregation, got: java.lang.Object[]"
    }
  },
  "status": 503
}
```

It would be preferable that this work. You can work around this by having one `sum_bucket` per aggregation depth level, but it would be nice to either have this return a more relevant error or just work.

**Comment by andrewvc** [comment]
After discussing this with @polyfractal it seems that this is most likely only the case with nested terms aggregations.

**Comment by colings86** [comment]
No, this will be true for any nested aggregations (e.g. terms>histogram) and was made like this by design. I agree that we should improve the error message here but I am hesitant to support summing over multiple levels as its possible to do (like you say) with multiple `sum_bucket` aggregations and we don't currently have support int eh `bucket_path` syntax for traversing multi bucket aggregations

**Comment by andrewvc** [comment]
@colings86 I think that makes sense. I do think it'd be better to return a `422` response code than a `503`, along with a more helpful error.

**Comment by andrewvc** [comment]
I'll just say that I was confused by this for a while till I did some experiments and determined the workaround.

**Comment by polyfractal** [comment]
@elastic/es-search-aggs 

Note: keeping this open because we should fix the error message to be more helpful (display the name of the path component that was not compatible), not the underlying issue of pathing through a multi-bucket.

**Comment by ssmulders** [comment]
After a lot of digging I came here as well, to find it's not a bug but a feature. The error message threw me off as well.

**Comment by jaymc-arg** [comment]
@ssmulders so how did you solve it? i don't get what feature you are talking about.
