### ISSUE TITLE
Cross Search Cluster search doesnt return events with wildchar

### ISSUE THREAD

**Issue by jayannah** [elastic/elasticsearch#25276]
Wildchar should be support in index name while querying the data from remote cluster with Elastic Search Cluster Feature.

`GET /remote_cluster:filebeat-2017.06.*/log/_search` ==> Doesn't return any event
`GET /remote_cluster:filebeat-2017.06.16/log/_search` ==>  Returns events as this has complete index name
`GET /filebeat-2017.06.*/log/_search`  ==> also returns events even though used wildchar in the index name

**Elasticsearch version**: 5.4.0

**Plugins installed**: []
x-pack

**JVM version** (`java -version`):
"1.8.0_73"

**OS version** (`uname -a` if on a Unix-like system):
3.13.0-119-generic #166-Ubuntu SMP Wed May 3 12:18:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
In the Cross Cluster Search while querying with clustername the index name can't have wildchar.  This should be allowed in the same way when we query the local cluster index name without specifying the cluster name in the index name.

GET /filebeat-2017.06.*/log/_search  ==> Works & reurns events even though used wildchar in the index name

GET /remote_cluster:filebeat-2017.06.16/log/_search ==>  Returns events as this has complete index name

GET /remote_cluster:filebeat-2017.06.*/log/_search ==>  DOESN'T return events as the index name has wildchar

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Configure ES with remote cluster as per Cross Cluster Search config
 2. Query the index name with and without wildchar in the  index name from the remote cluster

**Comment by javanna** [comment]
We are aware of this, x-pack doesn't support yet wildcards in 5.4 in combination with cross cluster search. We fixed this for the upcoming 5.5 release.
