### ISSUE TITLE
Cross cluster search example won't work as documented

### ISSUE THREAD

**Issue by LeeDr** [elastic/elasticsearch#25282]
**Elasticsearch version**: 5.4.0 docs

**Description of the problem including expected versus actual behavior**:

In 2 examples in the "Using cross cluster search" section of https://www.elastic.co/guide/en/elasticsearch/reference/5.x/modules-cross-cluster-search.html
it shows this post;
```
POST /cluster_one:twitter/tweet/_search
{
    "match_all": {}
}
```
but that won't work.  It needs to be;
```
POST /cluster_one:twitter/tweet/_search
{
  "query": {
    "match_all": {}
  }
}
```

If you do it as documented you get a "parsing_exception"

**Comment by jasontedor** [comment]
Closed by fde6f72cb57960a73f7466071517a724b6de9402
