### ISSUE TITLE
[CI] ShardStateIT.testPrimaryFailureIncreasesTerm failure

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#25287]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/1134/consoleFull

Tests with failures:
  - org.elasticsearch.cluster.routing.allocation.ShardStateIT.testPrimaryFailureIncreasesTerm

```
  1> [2017-06-19T17:14:49,980][INFO ][o.e.c.r.a.ShardStateIT   ] [testPrimaryFailureIncreasesTerm]: after test
FAILURE 1.60s J0 | ShardStateIT.testPrimaryFailureIncreasesTerm <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <2L>
   >      but: was <1L>
   > 	at __randomizedtesting.SeedInfo.seed([DD5109A109812A3D:2313D14489D49168]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.cluster.routing.allocation.ShardStateIT.assertPrimaryTerms(ShardStateIT.java:88)
```
I wasn't able to reproduce this locally. 

REPRODUCE WITH: gradle :core:integTest -Dtests.seed=DD5109A109812A3D -Dtests.class=org.elasticsearch.cluster.routing.allocation.ShardStateIT -Dtests.method="testPrimaryFailureIncreasesTerm" -Dtests.security.manager=true -Dtests.locale=uk -Dtests.timezone=Pacific/Kosrae

**Comment by cbuescher** [comment]
@bleskes this looks slightly similar to something you were looking into with https://github.com/elastic/elasticsearch/pull/17440. Can you have a quick look if this is related?

**Comment by martijnvg** [comment]
Another almost similar failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/1185/consoleText

```
FAILURE 0.95s J1 | ShardStateIT.testPrimaryFailureIncreasesTerm <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <2L>
   >      but: was <1L>
   > 	at __randomizedtesting.SeedInfo.seed([55793983F1F2F659:AB3BE16671A74D0C]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.cluster.routing.allocation.ShardStateIT.assertPrimaryTerms(ShardStateIT.java:87)
   > 	at org.elasticsearch.cluster.routing.allocation.ShardStateIT.testPrimaryFailureIncreasesTerm(ShardStateIT.java:74)
   > 	at java.lang.Thread.run(Thread.java:748)
```
