### ISSUE TITLE
_cluster/reroute?retry_failed only allocates number of shards permitted by node_concurrent_*_recoveries

### ISSUE THREAD

**Issue by jjfalling** [elastic/elasticsearch#25291]
**Elasticsearch version**: 5.4.1

**Plugins installed**: None

**JVM version**: Oracle 1.8

**OS version**: OSX

**Description of the problem including expected versus actual behavior**:
When allocating shards marked as unallocated due to index.allocation.max_retries, the cluster only allocates the number of shards in node_concurrent_*_recoveries and not all unallocated shards.

For example, on a cluster with 20 unallocated shards with the default concurrent recovery settings, _cluster/reroute?retry_failed will only allocate two shards and the reroute command will need to be re-ran 10 times until all the shards are allocated.

**Comment by bleskes** [comment]
another question is whether we want to move retry_failed to point at specific shards. Conceptually, this flag is there to say "I checked the problem, fixed it, and you should try to allocate again". A list of shards may be a better way of communicating this than a blank "disable max retries check")

**Comment by clintongormley** [comment]
Discussed in FixItFriday - we're going to change `?retry_failed` to reset the number of tries to zero so that all unallocated shards will be retried.

**Comment by matarrese** [comment]
Hi, I was looking at this piece of code on this file `MaxRetryAllocationDecider`
`    @Override
    public Decision canAllocate(ShardRouting shardRouting, RoutingAllocation allocation) {
        final UnassignedInfo unassignedInfo = shardRouting.unassignedInfo();
        final Decision decision;
        if (unassignedInfo != null && unassignedInfo.getNumFailedAllocations() > 0) {`

Should be added something here that reset the number of Failed Allocation?

**Comment by ywelsch** [comment]
@matarrese I think that that is not a good place to do the reset. AllocationDecider instances should not modify state. This rather belongs to the RerouteCommand, i.e. `AllocationService.reroute()` should take care of this.

**Comment by matarrese** [comment]
Hi @ywelsch thank you for your feedback. May I ask more details about where I should implement the logic of resetting the max retry variable? I am studying the source code of the `AllocationService.reroute()` but I can see any decisional logic about the number of attempts and max retry counting.
