### ISSUE TITLE
Feature Request: Add proxy configuration for xpack watcher email action with report attachment

### ISSUE THREAD

**Issue by brommer** [elastic/elasticsearch#25293]
In the following example you describe how to automatically generate reports using a watcher: https://www.elastic.co/guide/en/x-pack/current/automating-report-generation.html

For the HTTP input you provide a proxy host and port parameter: https://www.elastic.co/guide/en/x-pack/current/input-http.html 

However, if I want to create a report as shown in the example, I could not resolve my hostname, since no proxy has been specified. I could not find any documentation on a proxy setting for the attachment/reporting section. So I guess, this is not available yet and thus would be a feature request. 

I know, that the proxy can be set globally using (https://www.elastic.co/guide/en/x-pack/current/notification-settings.html) xpack.http.proxy.(host|port) but that is not really what is wanted, since it is a global setting for the whole ES cluster.

**Comment by spinscale** [comment]
Hey,

Indeed the report attachment does not have an option to add a proxy, but I will add this, as it is pretty easy to add.

Thanks a lot! Your feedback is greatly appreciated!

One minor note: Please dont post this into the Elasticsearch github issue list, as this is reserved for the open source part. If you just post it into the [x-pack discussion forum](https://discuss.elastic.co/c/x-pack) the next time, I will for sure also pick it up there :-)

**Comment by indeework** [comment]
Great, thanks! 

Ok, will do it next time! Thanks for the hint!
