### ISSUE TITLE
Support for configurable list of ports for EC2 Discovery

### ISSUE THREAD

**Issue by CpuID** [elastic/elasticsearch#25303]
**Describe the feature**:

Currently the EC2 Discovery plugin will attempt a single port, as per [this logic](https://github.com/elastic/elasticsearch/blob/master/plugins/discovery-ec2/src/main/java/org/elasticsearch/discovery/ec2/AwsEc2UnicastHostsProvider.java#L179).

It would be nice if you could configure a list of ports (CSV is fine), or a port range (x-y) to interrogate per host. This covers off scenarios when you may need to connect to a single EC2 instance for multiple ES processes in a single cluster.

My current workaround is to use bash + awscli + the file discovery plugin, which has support for host:port combinations, but would be nice to have a native solution to this, thanks :)

*Note: this could also apply to the GCE + Azure discovery plugins as well. I haven't verified if either of these have multiple port support, but I assume they will have equivalent to the EC2 discovery plugin currently.*

**Comment by dadoonet** [comment]
Might be similar to #18790.

**Comment by dadoonet** [comment]
> Note: this could also apply to the GCE + Azure discovery plugins as well. I haven't verified if either of these have multiple port support, but I assume they will have equivalent to the EC2 discovery plugin currently.

GCE supports this already. See https://www.elastic.co/guide/en/elasticsearch/plugins/current/discovery-gce-usage-port.html

**Comment by CpuID** [comment]
Note the difference here between *configurable port* and *multiple ports*... I believe the GCE plugin allows you to change the port, but won't interrogate multiple per host?

**Comment by dadoonet** [comment]
@CpuID That's true. Here we also assign only one port. Instead of trying to get the first available port.

```java
TransportAddress[] addresses = transportService.addressesFromString(address, 1);
```

For my understanding, why do you need to run more than one Elasticsearch instance on your EC2 machine?

**Comment by CpuID** [comment]
My initial motive is to share a single EC2 instance as a master + a data node, but run it in separate JVMs (to minimise risk of STW GC's on data nodes impacting master operations for the overall cluster). But I am sure there are other motives for running separate JVMs, such as running cross-site-search/tribe JVMs separate to data nodes, etc.

**Comment by dadoonet** [comment]
Fair enough. Thanks for the explanation.

**Comment by dadoonet** [comment]
@clintongormley Can I label this one as `adoptme`? I think it makes sense. May be that instead of scanning one single port (9300), we can ask either for a `discovery.ec2.ports` setting (default to `1`), or ask for an explicit port or range of ports like `9300-9302` (default to `9300`) ?

**Comment by jasontedor** [comment]
We discussed this during Fix-it-Friday. Two thoughts:
 
In general, we think it's better to run a single node per host. Especially in cloud environments where you can easily size hosts appropriately. The use-case here for running a dedicated master node of the same host as a data node is not one that we encourage; the arguments that you given regarding doing this to avoid a STW pause on the data node from impacting the master node do not really hold up well. If the data node is stealing resources (CPU, etc.) from the master node that master node is still going to be prone to impact from being on the same host as the data node. This is, of course, assuming that some form of process isolation is not being used, for example, cgroups; but then in that case it would be better to just run separate hosts.

Without a valid use-case, I'm not inclined to make any changes here. If there were a valid use-case, I do not think we would make this change by allowing a port range, but rather specifying specific ports.
