### ISSUE TITLE
Tribe Node does not respect action.search.shard_count.limit

### ISSUE THREAD

**Issue by timhperrin** [elastic/elasticsearch#25317]
**Describe the feature**:

**Elasticsearch version**:

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by timhperrin** [comment]
ES 5.3.2
No Plugins
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
Linux 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

When using Kibana on a Tribe Node to query more than 1000 shards the value in action.search.shard_count.limit is not respected and it uses the default even though the value in action.search.shard_count.limit is set on both clusters the node is a tribe member of to a value higher than 1000.  Is this a bug or is there a work around?

Thank you,
THP

**Comment by ywelsch** [comment]
The tribe node will not take the shard_count limit of the clusters it is connected to into account, but will look at how the setting is locally configured. Can you try setting `action.search.shard_count.limit` directly in your `elasticsearch.yml` on the tribe node?

**Comment by timhperrin** [comment]
That did it.

Thank you
