### ISSUE TITLE
Java API contains unsupported geohash_cell query builder

### ISSUE THREAD

**Issue by igorbunova** [elastic/elasticsearch#25319]
**Steps to reproduce**:
Try using  QueryBuilders.geoHashCellQuery method in the code, for example
```
Client client = ...;
double lat =...;
double lon = ...;
QueryBuilder locationFilter = QueryBuilders.geoHashCellQuery(name, new GeoPoint(lat, lon));
QueryBuider q =  QueryBuilders.boolQuery()
            .must(QueryBuilders.matchQuery("field", "text"))
            .filter(locationFilter);

client.prepareSearch("index").setQuery(q).get();
```

**Elasticsearch version**: 5.4.1

**Description of the problem including expected versus actual behavior**:
The breaking changes description is missed in the documentation.
Java API method should be removed or marked as Deprecated and linked with the alternative API methods or workarounds.
I don't see any other alternatives to this query except the additional fields to store the latitude and the longitude, however, https://www.elastic.co/guide/en/elasticsearch/reference/5.0/geo-point.html#_using_geo_points_in_scripts
says that lat and lon values of the geopoint field are available while scripting, perhaps it is possible to make them available while querying.

**Logs**
QueryShardException[failed to parse [geohash_cell] query. geo_point field no longer supports geohash_cell queries

**Comment by javanna** [comment]
Hi @igorbunova thanks for opening this issue and sorry it took us so long to get back to you.

I did some digging and the relevant PR is #20315 . Seems like in 5.x the geohash_cell query can only be executed against previously existing indices, but not against old indices. That is why it is still available in the java api, also why we removed it in 6.x.

I am afraid that we did miss to list this change among the breaking changes, and we should have deprecated these queries too before removing them which I am not sure we did.

@nknize can you comment further on what the alternatives are please?

**Comment by imotov** [comment]
geoHashCellQuery was removed in 6.0. So we, probably, can close this.
