### ISSUE TITLE
ElasticSearch rising connections...

### ISSUE THREAD

**Issue by csouthwell** [elastic/elasticsearch#25314]
We are rolling out a new ES cluster 10 nodes (16 processors 130GB RAM). This is a large spatial database performing mostly geo queries. 

We are consistently seeing the ES cluster connection count rise exponentially when we get around 2300 req/sec. The cluster then quickly becomes unstable. 

We have tried adding coordinator nodes and dedicated master nodes but the cluster just keeps getting unstable... We are seeing a lot of "Failed to execute fetch phase"

We increased the data node count to 20, and increased the shards from 5 to 30 and still are hitting the same limit.

**Comment by cbuescher** [comment]
Hi @csouthwell, Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions. May I direct you there for this kind of question?
