### ISSUE TITLE
 _all still there (not removed on index level)

### ISSUE THREAD

**Issue by saschaarthur** [elastic/elasticsearch#25326]
Hello,

Im trieing to optimize for space and disabled _all.

mapping looks like this:

```

curl http://10.0.0.3:9200/productsv6/domain6/_mappings
{
    "productsv6": {
        "mappings": {
            "domain6": {
                "_all": {
                    "enabled": false
                },


```
if i now use
`
curl http://10.0.0.3:9200/productsv6/domain6/_search?q=_all:samsung`

at least theres no results returned. so far so good

But if i use
`
curl http://10.0.0.3:9200/productsv6/_search?q=_all:samsung`

it returns me all results related to samsung

any idears? 

Yes i even put _all enabled:false on index level / during index creation.

Seems bugged for me?

Running on latest docker container 5.4

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
