### ISSUE TITLE
Most relevant highlighted fragment in the beginning

### ISSUE THREAD

**Issue by aslamy** [elastic/elasticsearch#25329]
When using highlighting how to sort the most relevant fragments in the beginning?

For example:
`{
    "query" : {
        "match": { "text": "some query text" }
    },
    "highlight" : {
        "fields" : {
            "text" : {"fragment_size" : 150, "number_of_fragments" : 5}
        }
    }
}

"highlight": {
    "text": ["match1, match2, match3, match4, match5"]
}`

In the example above, match5 may be most relevant. How do I sort so that it comes first?

**Comment by ywelsch** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

(Hint: try `"order" : "score"`, see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html)
