### ISSUE TITLE
Counterintuitive date rounding behavior in date filters

### ISSUE THREAD

**Issue by evanv** [elastic/elasticsearch#25339]
**Elasticsearch version**: 5.4.1

**Plugins installed**: [mapper-murmur3,  repository-s3]

**JVM version** (`java -version`): Java 1.8.0_60-b27

**OS version** (`uname -a` if on a Unix-like system): Centos 7

**Description of the problem including expected versus actual behavior**: 

Date range rounding behavior is counterintuitive, imo, and inconsistent with what I think users would expect, based on experiences with other database/IR systems. Consider the following query:

```
GET /_search
{
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "@timestamp": {
              "gte": "now-1d/d",
              "lte": "now/d"
            }
          }
        }
      ]
    }
  },
  "aggs": {
    "MaxDT": {
      "max": {
        "field": "@timestamp"
      }
    },
    "MinDT": {
      "min": {
        "field": "@timestamp"
      }
    }    
  }
}
```

This yields

```
  "aggregations": {
    "MinDT": {
      "value": 1497916800044,
      "value_as_string": "2017-06-20T00:00:00.044Z"
    },
    "MaxDT": {
      "value": 1498067981073,
      "value_as_string": "2017-06-21T17:59:41.073Z"  <--- note this
    }
  }
```

Consider instead the following query:

```
GET /_search
{
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "@timestamp": {
              "gte": "now-1d/d",
              "lt": "now/d"
            }
          }
        }
      ]
    }
  },
  "aggs": {
    "MaxDT": {
      "max": {
        "field": "@timestamp"
      }
    },
    "MinDT": {
      "min": {
        "field": "@timestamp"
      }
    }    
  }
}
```
This yields

```
  "aggregations": {
    "MinDT": {
      "value": 1497916800044,
      "value_as_string": "2017-06-20T00:00:00.044Z"
    },
    "MaxDT": {
      "value": 1498003199988,
      "value_as_string": "2017-06-20T23:59:59.988Z" <--- note this
    }
  }
```

The later query is correct for "Show me what happened yesterday."  The former produces an unexpected date range in that the values of `@timestamp` themselves appear to be rounded down and compared against `now/d`, which is not what I would expect based in the wording in the [existing](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-daterange-aggregation.html#CO79-2) [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#date-math).

I am still looking for the date rounding handling in the source code, but my gut feeling is that `@timestamp` is being rounded down and compared against `now/d`. This may or may not be what you intended and there may or may not be good reasons to do it this way, if you are. But it is not the behavior I would expect based on the docs and based on experience with other databases. If this behavior is intentional, would it be possible to document this behavior as a gotcha?

**Comment by cbuescher** [comment]
Hi @evanv, this is indeed the expected behaviour, although I undestand the confusion (its a question that came up a few times). I just looked at the documentation of the [range query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html#ranges-on-dates) and I think this covers it nicely. The [date range aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-daterange-aggregation.html#CO79-2) might need some reference to that as well, however thats not what you are using in your example. We accept pull requests for documentation, so if you want to take a stab at clarifying this its much appreciated.

**Comment by javanna** [comment]
Seems like there isn't much to do here. I am closing. Do send a PR if you have ideas on how to improve our docs.
