### ISSUE TITLE
 OOXMLParserTest.testXLSBVarious:<td>13.1211231321</td> not found

### ISSUE THREAD

**Issue by Londran** [elastic/elasticsearch#25333]
`Failed tests:
  OOXMLParserTest.testXLSBVarious:1509->TikaTest.assertContains:102 <td>13.1211231321</td> not found in:
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="meta:last-author" content="Allison, Timothy B." />
<meta name="Last-Author" content="Allison, Timothy B." />
<meta name="meta:save-date" content="2017-03-10T14:58:49Z" />
<meta name="Application-Name" content="Microsoft Excel" />
<meta name="Author" content="Allison, Timothy B." />
<meta name="dcterms:created" content="2017-03-09T12:24:26Z" />
<meta name="Application-Version" content="16.0300" />
<meta name="date" content="2017-03-10T14:58:49Z" />
<meta name="creator" content="Allison, Timothy B." />
<meta name="publisher" content="" />
<meta name="Creation-Date" content="2017-03-09T12:24:26Z" />
<meta name="extended-properties:AppVersion" content="16.0300" />
<meta name="protected" content="false" />
<meta name="meta:author" content="Allison, Timothy B." />
<meta name="extended-properties:Application" content="Microsoft Excel" />
<meta name="Last-Save-Date" content="2017-03-10T14:58:49Z" />
<meta name="meta:creation-date" content="2017-03-09T12:24:26Z" />
<meta name="dcterms:modified" content="2017-03-10T14:58:49Z" />
<meta name="dc:creator" content="Allison, Timothy B." />
<meta name="Last-Modified" content="2017-03-10T14:58:49Z" />
<meta name="extended-properties:Company" content="" />
<meta name="X-Parsed-By" content="org.apache.tika.parser.DefaultParser" />
<meta name="X-Parsed-By" content="org.apache.tika.parser.microsoft.ooxml.OOXMLParser" />
<meta name="modified" content="2017-03-10T14:58:49Z" />
<meta name="dc:publisher" content="" />
<meta name="Content-Type" content="application/vnd.ms-excel.sheet.binary.macroenabled.12" />
<title></title>
</head>
<body><div><h1>mySheet1</h1>
<table><tbody><tr>      <td>String</td> <td>This is a string</td></tr>
<tr>    <td>integer</td>        <td>13</td></tr>
<tr>    <td>float</td>  <td>13,1211231321</td></tr>
<tr>    <td>currency</td>       <td>$   0,003,,03.00</td></tr>
<tr>    <td>percent</td>        <td>20%</td></tr>
<tr>    <td>float 2</td>        <td>13,12</td></tr>
<tr>    <td>long int</td>       <td>123456789012345</td></tr>
<tr>    <td>longer int</td>     <td>1,23456789012345E+15</td>   <td><br />
Allison, Timothy B.: Allison, Timothy B.:
test comment2
</td></tr>
<tr>    <td>fraction</td>       <td>1/4</td></tr>
<tr>    <td>date</td>   <td>3/9/17</td></tr>
<tr>    <td>comment</td>        <td>contents<br />
Allison, Timothy B.: Allison, Timothy B.:
test comment
</td></tr>
<tr>    <td>hyperlink</td>      <td>tika_link</td></tr>
<tr>    <td>formula</td>        <td>4</td>      <td>2</td></tr>
<tr>    <td>formulaErr</td>     <td>ERROR</td></tr>
<tr>    <td>formulaFloat</td>   <td>0,5</td>    <td>March</td>  <td>April</td></tr>
<tr>    <td>customFormat1</td>  <td>   46/1963</td>     <td>merchant1</td>      <td>1</td>      <td>3</td></tr>
<tr>    <td>customFormat2</td>  <td>  3/128</td>        <td>merchant2</td>      <td>2</td>      <td>4</td></tr>
<tr>    <td>text test</td></tr>
<tr>    <td><br />
Allison, Timothy B.: Allison, Timothy B.:
comment1
</td></tr>
<tr>    <td><br />
Allison, Timothy B.: Allison, Timothy B.:
comment2
</td></tr>
<tr>    <td><br />
Allison, Timothy B.: Allison, Timothy B.:
comment3
</td></tr>
<tr>    <td>the</td>    <td><br />
Allison, Timothy B.: Allison, Timothy B.:
comment4 (end of row)
</td></tr>
<tr>    <td>the</td>    <td><br />
Allison, Timothy B.: Allison, Timothy B.:
comment5 between cells
</td>   <td>quick</td></tr>
<tr>    <td>comment6<br />
Allison, Timothy B.: Allison, Timothy B.:
comment6 actually in cell
</td></tr>
<tr>    <td><br />
Allison, Timothy B.: Allison, Timothy B.:
comment7 end of file
</td></tr>
<tr>    <td><br />
Allison, Timothy B.: Allison, Timothy B.:
comment8 end of file</td></tr>
</tbody></table>
<p>OddLeftHeader OddCenterHeader OddRightHeader</p>
<p>EvenLeftHeader EvenCenterHeader EvenRightHeader
</p>
<p>FirstPageLeftHeader FirstPageCenterHeader FirstPageRightHeader</p>
<p>OddLeftFooter OddCenterFooter OddRightFooter</p>
<p>EvenLeftFooter EvenCenterFooter EvenRightFooter</p>
<p>FirstPageLeftFooter FirstPageCenterFooter FirstPageRightFooter</p>
<p>test textbox
</p>
<a href="http://lucene.apache.org/">http://lucene.apache.org/</a><p>test WordArt</p>
<a href="http://tika.apache.org/">http://tika.apache.org/</a></div>
<div class="package-entry" /><div class="package-entry" /><div class="package-entry" /></body></html>
Tests in error:
  SentimentParserTest.endToEndTest:43->getTika:78 » TikaConfig https://raw.githu...
  SentimentParserTest.testCategorical:61->getTika:78 » TikaConfig https://raw.gi...

Tests run: 884, Failures: 1, Errors: 2, Skipped: 24
`

Guess this error is due to using . instead of ,. Any possibility to change that?

**Comment by jasontedor** [comment]
I think that you have the wrong repository, this needs to go upstream to Tika.
