### ISSUE TITLE
[CI] DiscoveryDisruptionIT testClusterFormingWithASlowNode fails

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#25338]
The test `DiscoveryDisruptionIT testClusterFormingWithASlowNode` failed on CI:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/1142/console

and it doesn't reproduce locally with:
```
gradle :core:integTest -Dtests.seed=1AF2EE4687C8E45A -Dtests.class=org.elasticsearch.discovery.DiscoveryDisruptionIT -Dtests.method="testClusterFormingWithASlowNode" -Dtests.security.manager=true -Dtests.locale=sr-BA -Dtests.timezone=America/Argentina/San_Juan
```

The build log is 
[consoleText.txt](https://github.com/elastic/elasticsearch/files/1092008/consoleText.txt)

**Comment by bleskes** [comment]
the build didn't include #25320 . I think it's useless to chase these without that fix.

**Comment by tlrx** [comment]
Ok, I didn't know about #25320. Thanks for the precision.
