### ISSUE TITLE
Ingest 50% Slower After Upgrade to 5.3.2 

### ISSUE THREAD

**Issue by timhperrin** [elastic/elasticsearch#25341]
**Describe the feature**:

**Elasticsearch version**:

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by talevy** [comment]
Hi @timhperrin, It is unclear what the exact issue is from the title alone.
would you mind updated the description to provide more details?

**Comment by timhperrin** [comment]
ES 5.3.2
No plugins
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
Linux 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

After upgrading Elasticsearch and Logstash to 5.3.2 we are experiencing an ingest rate about 50% slower than before.  The architecture is the same: kafka --> logstash --> Elasticsearch.  We are not getting any errors in Kafka, ES or LS.  We do see an increase in index_merge_throttle_stop_time and index_merge_throttle_time in ES.

**Comment by timhperrin** [comment]
This Visualization may explain things.
![escapture](https://user-images.githubusercontent.com/29580559/27403832-1fc5ccf8-5689-11e7-8347-f328e32996e6.PNG)

**Comment by nik9000** [comment]
We really can't help without knowing the mappings, index settings, or, well, anything. Increased merge throttling is certainly an issue, but from this side of the internet I can't see why it is happening.

Your best bet is to do a small scale reproduction against the old and new version and reopen if you can isolate the issue.

**Comment by timhperrin** [comment]
We have a dev cluster on the same versions.  Our dev cluster does not have the problem.  In prod we see high merge throttle times that we don't see in dev. These 2 vizs show what I mean.
![prod](https://user-images.githubusercontent.com/29580559/27452690-86e1abfe-5761-11e7-848e-a260807e61c2.PNG)
![dev](https://user-images.githubusercontent.com/29580559/27452691-88adfe9c-5761-11e7-9bc8-4e9fbd63d7d3.PNG)
