### ISSUE TITLE
Cannot get cross-cluster search to work... 

### ISSUE THREAD

**Issue by afederici75** [elastic/elasticsearch#25342]
Hi,
  I just downloaded and installed ES 5.4.2 on my Windows 10 machine to try the cross-cluster search feature. Unfortunately I cannot seem to get it working. Whenever I try to send a query to the "remote" cluster (post /cluster_one:index1/Person/_search) I get back this:

{
  "error": {
    "root_cause": [],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": []
  },
  "status": 503
}

My second ES never receives the query and nothing gets logged. I instead see logs from the first ES and it seems it is not recognizing that it needs to query the other ES instance.

My setup: I have 2 instances of ES running on the same machine. The first (which I refer to as 'local') uses ports http:9400 and tcp:9500. The second ('cluster_one') is setup to use http:9600 and tcp:9700. Both instances work great and they respond using 127.0.0.1, localhost or the name of the machine itself.

I setup the "link" to the second instance from the first, using almost the same JSON in the documentation. The latest version of my JSON is this:

PUT _cluster/settings
{
  "persistent": {
    "search": {
      "remote": {
        "cluster_one": {
          "seeds": [
            "127.0.0.1:9700"
          ]
        }
      }
    }
  }
}

get _cluster/settings returns this:
{
  "persistent": {
    "search": {
      "remote": {
        "cluster_one": {
          "seeds": [
            "127.0.0.1:9700"
          ]
        }
      }
    }
  },
  "transient": {}
}

I then tried to search by using this JSON:

post /cluster_one:index1/Person/_search
{
  "query": {
    "match_all": {}
  }
}

but ES returns the error I pasted at the beginning.
The query works just fine on the second ES instance (e.g. post /index1/Person/_search) directly.

Interesting things I noticed:
-If I add a setting to link ES-1 to itself (like in the docs) and I try to query it, everything works. What doesn't work is accessing a different cluster.
-I tried to change the settings setting 'seeds' to 'null' but that doesn't work. I finally managed to remove the setting using this (notice '[null]', instead of 'null'):

PUT _cluster/settings
{
  "persistent": {
    "search": {
      "remote": {
        "cluster_one": {
          "seeds": [null]
        }
      }
    }
  }
}

I am fairly stuck right now and don't know how to proceed.
I hope I provided enough information.

Thanks,
  Alessandro

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by afederici75** [comment]
Thank you and I don't mind :) but you might want to look into the last part of the text above where I did report a bug...

Basically this part:

-I tried to change the settings setting 'seeds' to 'null' but that doesn't work. I finally managed to remove the setting using this (notice '[null]', instead of 'null'):

PUT _cluster/settings
{
"persistent": {
"search": {
"remote": {
"cluster_one": {
"seeds": [null]
}
}
}
}
}
