### ISSUE TITLE
PreBuiltTransportClient does not appear in javadocs

### ISSUE THREAD

**Issue by ljnelson** [elastic/elasticsearch#25362]
**Elasticsearch version**: 5.4.2

**Plugins installed**: [N/A]

**JVM version** (`java -version`): N/A

**OS version** (`uname -a` if on a Unix-like system): N/A

**Description of the problem including expected versus actual behavior**: `PreBuiltTransportClient` referenced in documentation does not [appear in javadocs](http://javadoc.io/doc/org.elasticsearch/elasticsearch/5.4.2)

**Steps to reproduce**: See http://javadoc.io/doc/org.elasticsearch/elasticsearch/5.4.2

**Comment by jasontedor** [comment]
It's published. You have to go to: https://artifacts.elastic.co/javadoc/org/elasticsearch/client/transport/5.4.2/index.html
