### ISSUE TITLE
Remove Outliers in Query

### ISSUE THREAD

**Issue by k2xl** [elastic/elasticsearch#25368]
I have data like the following:

![image](https://user-images.githubusercontent.com/965260/27451879-97ecf906-575e-11e7-938f-82a9c147602a.png)

Is it possible to filter those outliers? I'd like to smooth the graph but occasionally we get bad data. 

I looked into the percentile aggregations, but they don't seem to filter out the data.

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by k2xl** [comment]
Np, sorry!
