### ISSUE TITLE
Elasticsearch http output: invalid json

### ISSUE THREAD

**Issue by dhellemans** [elastic/elasticsearch#25400]
**Elasticsearch version**: elasticsearch-5.4.2-1.noarch

**Plugins installed**: []

**JVM version** (`java -version`): java-1.8.0-ibm-1.8.0.4.5-1jpp.1.el7_3.x86_64

**OS version** (`uname -a` if on a Unix-like system): Linux el4645.bc 3.10.0-514.21.1.el7.x86_64 #1 SMP Sat Apr 22 02:41:35 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: Elasticsearch returns the following: 

2017/06/26 16:21:22.103591  length=87 from=0 to=86
HTTP/1.1 200 OK\r
content-type: application/json; charset=UTF-8\r
content-length: 327\r
\r

which results in a ParseError e.g. when Fluentd tries to flush its buffers. The correct output should include {} (empty json)

**Steps to reproduce**:

 1. echo -e "HEAD / HTTP/1.1\n" |nc localhost 9200

**Provide logs (if relevant)**:
Fluentd error:

2017-06-26 16:21:22 +0200 [warn]: fluent/output.rb:371:rescue in try_flush: temporarily failed to flush the buffer. next_retry=2017-06-26 16:59:18 +0200 error_class="MultiJson::ParseError" error="Yajl::ParseError" plugin_id="object:db2c98"

**Comment by jasontedor** [comment]
This is not correct, this is a `HEAD` request so there should not be a body. The problem is with the consumer here.
