### ISSUE TITLE
org.elasticsearch.index.shard.IndexShardTests#testRelocatedShardCanNotBeRevivedConcurrently fails in CI

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#25419]
* Test failure link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=amazon/1169/consoleFull
* Failure output:

```
FAILURE 0.07s J1 | IndexShardTests.testRelocatedShardCanNotBeRevivedConcurrently <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: an instance of org.elasticsearch.index.shard.IllegalIndexShardStateException
   >      but: null
   > 	at __randomizedtesting.SeedInfo.seed([1F751A5A090E28D6:9DE5F0E3BB7ADB56]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.index.shard.IndexShardTests.testRelocatedShardCanNotBeRevivedConcurrently(IndexShardTests.java:1218)
   > 	at java.lang.Thread.run(Thread.java:745)

```
* Reproduction line: `gradle :core:test -Dtests.seed=1F751A5A090E28D6 -Dtests.class=org.elasticsearch.index.shard.IndexShardTests -Dtests.method="testRelocatedShardCanNotBeRevivedConcurrently" -Dtests.security.manager=true -Dtests.locale=sr-RS -Dtests.timezone=Australia/Lindeman`
* Frequency: Failed 5 times in CI yesterday; does not reproduce locally.

Likely to relate to #25122.

**Comment by jasontedor** [comment]
Duplicates #25415
