### ISSUE TITLE
Document which analysis components are allowed in normalizers.

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#25427]
We should document which analysis components are allowed in normalizers. Maybe a good start would be to give a subset of the ones that can be used and are usually the most useful ones such as the `lowercase` and the `ascii_folding` filters.

**Comment by mayya-sharipova** [comment]
cc @elastic/es-search-aggs

**Comment by mayya-sharipova** [comment]
Duplicate of https://github.com/elastic/elasticsearch/issues/28605, which is already implemented an merged.
