### ISSUE TITLE
VersionConflictEngineException issue

### ISSUE THREAD

**Issue by hahalixiaojing** [elastic/elasticsearch#25438]
**Describe the feature**:

**Elasticsearch version**:
2.1

**Plugins installed**: []

**JVM version** (`java -version`):
kotlin , java version 1.8

**OS version** (`uname -a` if on a Unix-like system):
wndows 7

**Description of the problem including expected versus actual behavior**:
VersionConflictEngineException
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

when I write this 

       val prepare = this.client.prepareUpdate()
        prepare.setIndex(INDEX)
        prepare.setType("fresh_shop")
        prepare.setId(model.id.toString())
        prepare.setVersion(version)
        prepare.setDocAsUpsert(true)
        prepare.setDoc(source)
        prepare.execute()
        prepare.get()

frequently throw VersionConflictEngineException 

but when I write this

this.client.prepareUpdate().setIndex(INDEX).setType("fresh_shop").setId(model.id.toString()).setVersion(version).setDocAsUpsert(true).setDoc(source).execute().get()

there is not  throw VersionConflictEngineException any

why? 

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by tvernum** [comment]
Please ask this question on our [discuss forum](https://discuss.elastic.co/) where we can provide better support.

Elastic uses GitHub issues for confirmed bugs and feature requests which have been discussed on the forums. As this appears to be a question rather than a confirmed bug, I'm going to close this issue.

Thank you.
