### ISSUE TITLE
Setting queue.page_capacity and queue.max_bytes to the same value breaks logstash

### ISSUE THREAD

**Issue by tmartensson** [elastic/elasticsearch#25440]
**Elasticsearch version**:
5.4.1

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "1.8.0_131"

**OS version** (`uname -a` if on a Unix-like system):
Linux log-server01 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
When using '**_queue.type: persisted_**' and set '**_queue.page_capacity_**' and '**_queue.max_bytes_**' to the same value things look ok in the logfiles but logstash is acting very weird. 

Expected behaviour:
Logs sent in from Filebeat to Logstash should arrive in the configured output.

Actual behaviour:
One log entry appears in the configured output, repeated 4 times.
Filebeat is reporting:
> ERR Failed to publish events caused by: read tcp 10.11.12.13:47304->10.13.12.11:5043: i/o timeout

Also, logstash takes a long time to stop/start when this setting is used.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Set queue.type to persisted
 2. Set queue.page_capacity to 1g
 3. Set queue.max_bytes to 1g
 4. No logs or a few of them appears in the configured output.

**Provide logs (if relevant)**:

**Comment by colings86** [comment]
This seems to be a Logstash issue rather than an Elasticsearch issue. Logstash bugs should be reported in the [Logstash repository](https://github.com/elastic/logstash). Although its probably worth asking this first on the [Discuss Forum](https://discuss.elastic.co/c/logstash) since this could be an environmental issue rather than a bug.
