### ISSUE TITLE
Add remove field to all processors

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#25441]
In a similar way as we have in Logstash, I think we should be able to always provide a `remove` attribute in processors so people can simply remove a field without having to write "complex" pipelines to remove something that has been parsed.

For example instead of writing:

```json
{
  "processors": [
    {
      "grok": {
        "field": "message",
        "patterns": ["%{IP:client} %{WORD:method} %{URIPATHPARAM:request} %{NUMBER:bytes} %{NUMBER:duration}"]
      }
    },{
      "remove": {
        "field": "message"
      }
    }
  ]
}
```

We can write:

```json
{
  "processors": [
    {
      "grok": {
        "field": "message",
        "patterns": ["%{IP:client} %{WORD:method} %{URIPATHPARAM:request} %{NUMBER:bytes} %{NUMBER:duration}"],
        "remove": ["message"]
      }
    }
  ]
}
```

Same applies to ingest-attachment where normally you don't want to keep the original BASE64 content in your docs.

```json
{
  "processors" : [
    {
      "attachment" : {
        "field" : "data"
      }
    },{
      "remove" : {
        "field" : "data"
      }
    }
  ]
}
```

to 

```json
{
  "processors" : [
    {
      "attachment" : {
        "field" : "data",
        "remove" : [ "data" ]
      }
    }
  ]
}
```

**Comment by rjernst** [comment]
Is it really that complex? I think it would be better to keep the processors simple, eventually just having everything done through scripting (see #25165).

**Comment by dadoonet** [comment]
It's not complex. It makes ingest consistent with what Logstash does OOTB.

For example https://www.elastic.co/guide/en/logstash/current/plugins-filters-date.html#plugins-filters-date-remove_field

**Comment by colings86** [comment]
Discussed in FixItFriday and we said that we don't think adding a remove processor is that complex especially as you can give it a list of all the fields you want to remove so you can add one to the end of your pipeline and remove all unneeded fields in one go. Adding the option to all processors means they become more complex themselves since they are no long simply doing one thing.
