### ISSUE TITLE
SimpleNioTransportTests#testConnectException failed in CI

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#25454]
The SimpleNioTransportTests testConnectException failed in CI on the master branch when running on windows: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/379/console

```
FAILURE 1.20s J0 | SimpleNioTransportTests.testConnectException <<< FAILURES!
   > Throwable #1: org.junit.ComparisonFailure: expected:<Connection refused[]> but was:<Connection refused[: no further information]>
   > 	at __randomizedtesting.SeedInfo.seed([4E704AA42FDB9523:AAFDB5A670C0473D]:0)
   > 	at org.elasticsearch.transport.nio.SimpleNioTransportTests.testConnectException(SimpleNioTransportTests.java:107)
   > 	at java.lang.Thread.run(Thread.java:745)
```

Reproduce line:

```
gradle :test:framework:test -Dtests.seed=4E704AA42FDB9523 -Dtests.class=org.elasticsearch.transport.nio.SimpleNioTransportTests -Dtests.method="testConnectException" -Dtests.security.manager=true -Dtests.locale=ar-SD -Dtests.timezone=Europe/Zaporozhye
```

**Comment by tbrooks8** [comment]
It appears that this asserting on this IOException message may not be dependable. It is not important that we do this, as we also assert on our application exception message. I have removed this problematic assertion.

https://github.com/elastic/elasticsearch/commit/cad57959e11ae37936fa7dcf7cc4aaa4ba9b5bb0
