### ISSUE TITLE
Problems regarding "adding indexed groovy scripts"

### ISSUE THREAD

**Issue by mihai1voicescu** [elastic/elasticsearch#25473]
Hello,

I will mark the problems I think exist with 1, 2 and 3.

On version 2.4 running the example specified in the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/modules-scripting.html), for adding a script to the cluster:
```
POST _scripts/groovy/indexedCalculateScore
{
  "script": "log(_score * 2) + my_modifier"
}
```
results in the following:
```
{
   "error": {
      "root_cause": [
         {
            "type": "strict_dynamic_mapping_exception",
            "reason": "mapping set to strict, dynamic introduction of [script] within [groovy] is not allowed"
         }
      ],
      "type": "strict_dynamic_mapping_exception",
      "reason": "mapping set to strict, dynamic introduction of [script] within [groovy] is not allowed"
   },
   "status": 400
}
```
1. Dynamic mapping should not be necessary here in my opinion.
Also running the following:
```
POST _scripts/groovy/indexedCalculateScore
{
  "lang": "groovy"
}
```
results in
```
{
   "error": {
      "root_cause": [
         {
            "type": "script_parse_exception",
            "reason": "expected one of [inline], [file] or [id] fields, but found none"
         }
      ],
      "type": "script_parse_exception",
      "reason": "expected one of [inline], [file] or [id] fields, but found none"
   },
   "status": 500
}
```
but when I specify a one of those fields, lets say id:
```
POST _scripts/groovy/indexedCalculateScore
{
  "id": "test",
  "lang": "groovy"
}
```
it results in
```
{
   "error": {
      "root_cause": [
         {
            "type": "strict_dynamic_mapping_exception",
            "reason": "mapping set to strict, dynamic introduction of [id] within [groovy] is not allowed"
         }
      ],
      "type": "strict_dynamic_mapping_exception",
      "reason": "mapping set to strict, dynamic introduction of [id] within [groovy] is not allowed"
   },
   "status": 400
}
```
2. I think the error message is wrong.
3. Also there is an error in the 2.4 [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/modules-scripting.html): in some places the index is called `.scripts` and in other `_scripts`.

**Comment by rjernst** [comment]
Indexed scripts were removed in 5.0, and instead are now stored (in the cluster state) scripts. The documentation is correct, it does refers to the api endpoint `_scripts`, and the underlying index that scripts are stored in, `.scripts`.

I believe indexed scripts in 2.x rely on dynamic mappings for the .scripts index. Do you have dynamic mappings disabled?

**Comment by mihai1voicescu** [comment]
By index scripts I meant [stored scripts](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html#modules-scripting-stored-scripts), I am sorry for the confusion.
Also my number 1 point specifies that it should not require dynamic mapping, therefore I have dynamic mappings disabled.
Is the dynamic mappings feature required in 5.x to use scripts?

**Comment by rjernst** [comment]
> Is the dynamic mappings feature required in 5.x to use scripts?

No it is not. 

> By index scripts I meant stored scripts

Stored scripts did not exist in 2.x, they were introduced in 5.0.

I'm going to close this issue as I do not think there is any change likely to happen for 2.4.
