### ISSUE TITLE
Elasticsearch complaining about fielddata on doc_values only index

### ISSUE THREAD

**Issue by MisoMadao** [elastic/elasticsearch#25484]
elasticsearch 2.4.5
no plugins installed
java version "1.8.0_131"
Windows 7

I declared a template for an index and explicitly enabling doc_values and disabling fielddata for not_analyzed strings.

`POST _template/test
{
	"order": 0,
	"template": "test",
	"settings": {
		"number_of_shards": 1,
		"number_of_replicas": 0
	},
	"mappings": {
		"data": {
			properties": {
				"name": {
					"type": "string",
					"fielddata": {
						"format": "disabled"
					},
					"index": "not_analyzed",
					"doc_values": true
				}
			}
		}
	}
}`

after indexing some documents, trying to aggregate on those documents will result in elasticsearch complaining about forbidden fielddata loading:

`"reason": "Field data loading is forbidden on [name]"`

forum post: https://discuss.elastic.co/t/understanding-doc-values/90318

**Comment by jpountz** [comment]
This is because `"fielddata": { "format": "disabled" }` is taking precedence. You should pass `format: doc_values` instead or skip it entirely, which will have the same effect.
