### ISSUE TITLE
Getting started doc HTTP method type for search is GET

### ISSUE THREAD

**Issue by fhalde** [elastic/elasticsearch#25507]
In the getting-started guide, every search request using HTTP is shown as a GET request. It might trip a few newbies into thinking as to how a GET request accepts a body. e.g. Postman doesn't let you pass a body using GET request.

https://github.com/elastic/elasticsearch/blob/master/docs/reference/getting-started.asciidoc

Also, was it a conscious thought to go against HTTP spec to use GET method with parameters (AFAIK HTTP doesn't say anything about using a body for GET requests)

**Comment by jasontedor** [comment]
Yes, it's [deliberate](https://github.com/elastic/elasticsearch/issues/16024#issuecomment-172491501). If you use [Console](https://www.elastic.co/guide/en/kibana/5.4/console-kibana.html) or curl, a body can be sent without issues (and our docs provide copy to Console and copy to curl functionality).
