### ISSUE TITLE
Add Rollover API to support wildcards

### ISSUE THREAD

**Issue by synhershko** [elastic/elasticsearch#25506]
Currently, this doesn't work:

```json
POST rawlogs_*/_rollover
{
    "conditions":{
        "max_docs": 1
    }
}
```

(fails with an error "source alias does not exist")

However, using a cron to execute a rollover operation is a common practice and in a multi-tenant scenario having no wildcard support is very limiting. Adding support for rollover on multiple aliases using wildcards as above would be extremely helpful.

**Comment by PnPie** [comment]
If we do it for multiple aliases (especially with support of wild-cards), the naming of newly created indices might be a problem because currently we need to specify a name for an alias if it doesn't match a certain pattern.

Otherwise we have to generate new names for all the newly created indices ?

**Comment by synhershko** [comment]
The generated name can either be derived from the matching alias name(s) via a convention (like now), or the index name pattern can be specified in the `_rollover` operation command itself (sibling to "conditions").

**Comment by fred84** [comment]
@cbuescher May I try to solve this issue?

@synhershko @PnPie Maybe we should fail if we cannot generate new index name for any matching alias?

**Comment by s1monw** [comment]
I am interested in how this would look like especially on the response side. Would we simply return a list of response and internally just resolve the wildcard on the rest layer and then send N individual requests? I think that could work but I really don't want much of a special handling internally to support this.

**Comment by fred84** [comment]
@s1monw  Yes, I think it will be array of responses, e.g. 
```json 
{
    "acknowledged": true,
    "shards_acknowledged": true,
    "dry_run": false,
    "matched_aliases": {
        "logs": {
            "old_index": "logs-000001",
            "new_index": "logs-000002",
            "rolled_over": true,
            "conditions": {
                "[max_age: 7d]": false,
                "[max_docs: 1000]": true
            }
        },
        "logzz": {
            "old_index": "logzz-000001",
            "new_index": "logzz-000002",
            "rolled_over": false,
            "conditions": {
                "[max_age: 7d]": false,
                "[max_docs: 1000]": false
            }
        }
    }
}
```
I worry about breaking API compatibility with existing users. Maybe we should add flag to request (e.g. "enable_multiple_aliases"). If this flag is not set, then wildcards and aliases lists will be forbidden.

As for implementation, I think we can modify TransportRolloverAction.masterOperation so it iterate over aliases, collect responses and then notify listener.

**Comment by s1monw** [comment]
>  I worry about breaking API compatibility with existing users. Maybe we should add flag to request (e.g. "enable_multiple_aliases"). If this flag is not set, then wildcards and aliases lists will be forbidden.

with rest we can start render both ways the the user if there is only one alias that matched. That way both APIs can be used at the same time. don't worry about the java API

**Comment by fred84** [comment]
@s1monw 
When any of alias rollovers failed, what should we return? I see two options:
- first encountered exception (just call `listener.onFailure` and ignore other responses)
- collect all responses (both succeeded and failed) and return them together (example below).

```json
{
  "dry_run" : false,
  "rolled_over_aliases" : {
    "logz_write" : {
      "old_index" : "logz-000001",
      "new_index" : "logz-000002",
      "rolled_over" : true,
      "acknowledged" : true,
      "shards_acknowledged" : true,
      "conditions" : {
        "[max_docs: 1]" : true
      }
    },
    "logs_write" : {
      "old_index" : "logs-000001",
      "new_index" : "logs-000002",
      "rolled_over" : true,
      "acknowledged" : true,
      "shards_acknowledged" : true,
      "conditions" : {
        "[max_docs: 1]" : true
      }
    }
  },
  "failed_aliases" : {
    "logs_fail" : {
      "type" : "illegal_argument_exception",
      "reason" : "Some exception description"
    }
  }
}
```

**Comment by s1monw** [comment]
closing see #26385 for the rational. thanks everybody involved and especially @fred84 for working with us. I really hope it was a good experience nevertheless
