### ISSUE TITLE
[docs] Document max_snapshot_bytes_per_sec and max_restore_bytes_per_sec as available settings for S3 repositories

### ISSUE THREAD

**Issue by n0othing** [elastic/elasticsearch#25522]
The [S3 Repository](https://www.elastic.co/guide/en/elasticsearch/plugins/5.4/repository-s3-repository.html) section of the docs doesn't list `max_snapshot_bytes_per_sec` or `max_restore_bytes_per_sec` as valid settings. The current [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/modules-snapshots.html#_shared_file_system_repository) might suggest those settings are exclusive to `"type": "fs"` repositories.

**Comment by ywelsch** [comment]
@debadair would you be interested in changing the docs here?

**Comment by jrodewig** [comment]
@ywelsch I'll pick this one up.
