### ISSUE TITLE
Behaviour of auto fuzziness should be configurable

### ISSUE THREAD

**Issue by tobymiller1** [elastic/elasticsearch#25528]
When AUTO is used for fuzziness in a query the distance is set to 0 for terms of length 0-2, 1 for lengths 3-5, and 2 for lengths >5. This behaviour is hard-coded.

We find this too permissive, and would like to be able to configure (at an instance level, not per query) the boundaries of 3 and 6, at which the distance changes.

For now we're using our own build of ES to support this, but would like to send it upstream. Would changing these numbers (3 and 6) to configurable parameters be accepted? Are there any other issues we should be aware of?

The current state of org.elasticsearch.common.unit.Fuzziness.asDistance is as follows:
```
public int asDistance(String text) {
    if (this.equals(AUTO)) { //AUTO
        final int len = termLen(text);
        if (len <= 2) {
            return 0;
        } else if (len > 5) {
            return 2;
        } else {
            return 1;
        }
    }
    return Math.min(2, (int) asFloat());
}
```

**Comment by jpountz** [comment]
I can't find them right now but I remember some other similar feature requests. I think we could come up with some form of syntax in the same spirit of what we have for `minimum_should_match`.

**Comment by tobymiller1** [comment]
I think it's simpler than `minimum_should_match`, because in all cases the behaviour of fuzziness can be reduced to two integers (as fuzziness above 2 isn't supported anyway): the threshold at which it becomes 1, and at which it becomes 2. Percentage fuzziness used to be supported but was removed, presumably because it suggested that there was more flexibility when really it was just being turned into two thresholds.

Are you suggesting that it should be customisable at the query level, rather than in configuration? If so, some thought would probably need to be put into the syntax, as there could be confusion between settings that define the fuzziness and those that define the length thresholds for fuzziness, which are both integers.

**Comment by jpountz** [comment]
Agreed with what you said, and yes I think it should be configurable at the query level if possible?

**Comment by tobymiller1** [comment]
Great. The syntax could be e.g. `4,8` to indicate 0 fuzziness up to length 3, 1 fuzziness for 4-7, and 2 fuzziness from 8 onwards, but that would look quite similar to the single integer (`1` or `2`) that indicate fuzziness of 1 or 2 at the moment. Would that be a problem?

**Comment by jpountz** [comment]
Yes, I think we need something more specific. Maybe extending the existing `auto` to something like `auto:4,8`. Just an idea, it probably has drawbacks too. :)

**Comment by tobymiller1** [comment]
I agree. `auto:4` would mean 0 up to 3, and 1 from 4 onwards, and `auto:4,8,12` would make sense if you wanted to permit higher fuzziness in the future.

**Comment by matarrese** [comment]
Hi guys, I really would be happy to work on this story. 
Reading the documentation : https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#fuzziness
and considering an example, I'm gonna try to work on something that looks like:
```
GET /_search
{
    "query": {
        "fuzzy" : {
            "user" : {
                "value" :         "ki",
                    "boost" :         1.0,
                    "fuzziness" :     "auto:4,8",
                    "prefix_length" : 0,
                    "max_expansions": 100
            }
        }
    }
}
```
Is it accetapable?

**Comment by tobymiller1** [comment]
That looks sensible to me. Thanks!
