### ISSUE TITLE
Unable to change existing field of a template mapping

### ISSUE THREAD

**Issue by nfvs** [elastic/elasticsearch#25539]
When trying to change one field in a template mapping (**not** an index mapping), I'm getting this error:

> mapper [owner] cannot be changed from type [keyword] to [text]

Full response:
```
{
  "error": {
    "root_cause": [
      {
        "type": "remote_transport_exception",
        "reason": "[es-master-node1][127.0.0.1:9300][indices:admin/template/put]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "mapper [owner] cannot be changed from type [keyword] to [text]"
  },
  "status": 400
}
```

I realize we cannot update the mappings of existing indices, but this happens when trying to change the **template** mappings, which AFAIK only get used when creating new indices. This used to work fine on previous versions (pre v5).

This is using version 5.4.1

**Comment by jpountz** [comment]
Can you share a recreation of this issue?

**Comment by nfvs** [comment]
```
{
  "template": "data-*",
  "order": 10,
  "settings": {
    "index.mapping.ignore_malformed": true
  },
  "mappings": {
    "doc1": {
      "properties": {
        "owner": "text"
      }
    }
  }
```

Followed by

```
{
  "template": "data-*",
  "order": 10,
  "settings": {
    "index.mapping.ignore_malformed": true
  },
  "mappings": {
    "doc1": {
      "properties": {
        "owner": "keyword"
      }
    }
  }
```

I should point out that there are indices which were created by that template, and they contain data; however, I was under the impression that the template should only influence **new** indices, not existing ones.

**Comment by PnPie** [comment]
Firstly, the syntax is not really correct, it should be rather like this:
```
PUT /_template/data-template
{
  "template": "data-*",
  "order": 10,
  "settings": {
    "index.mapping.ignore_malformed": true
  },
  "mappings": {
    "doc1": {
      "properties": {
        "owner": {
          "type": "integer"
        }
      }
    }
  }
}
```
And I'm on ES 5.5.1, update of template mappings work well for me.

**Comment by nfvs** [comment]
@PnPie but do you have any indices using that property? It seems to only fail for me if there are indices using that, which seems strange since current indices shouldn't affect template mappings.

**Comment by PnPie** [comment]
@nfvs Yeah I just tried it works well even if I created indices by using that templates. And just as the templates only impact indices at creation time, so the creation of indices should not have an influence on templates I suppose. And your error message looks like you are changing the mapping of index instead of the templates.

**Comment by nfvs** [comment]
> And your error message looks like you are changing the mapping of index instead of the templates.

I know, which is what I find weird. By the reply you can see that it's correct, since it contains `[indices:admin/template/put]`

**Comment by jpountz** [comment]
I tried the following recreation and things work as expected:

```
PUT /_template/data-template
{
  "template": "data-*",
  "order": 10,
  "settings": {
    "index.mapping.ignore_malformed": true
  },
  "mappings": {
    "doc1": {
      "properties": {
        "owner": {
          "type": "text"
        }
      }
    }
  }
}

PUT data-1/doc1/1
{
  "owner": "foo bar"
}

PUT /_template/data-template
{
  "template": "data-*",
  "order": 10,
  "settings": {
    "index.mapping.ignore_malformed": true
  },
  "mappings": {
    "doc1": {
      "properties": {
        "owner": {
          "type": "keyword"
        }
      }
    }
  }
}

PUT data-2/doc1/1
{
  "owner": "foo bar"
}

GET data-1,data-2/_mapping
```

which returns

```
{
  "data-2": {
    "mappings": {
      "doc1": {
        "properties": {
          "owner": {
            "type": "keyword"
          }
        }
      }
    }
  },
  "data-1": {
    "mappings": {
      "doc1": {
        "properties": {
          "owner": {
            "type": "text"
          }
        }
      }
    }
  }
}
```

Can you confirm that this recreation fails in your environment?

**Comment by colings86** [comment]
No further feedback. If you are able to recreate this issue using @jpountz's recreation script above then please comment and we can reopen this issue.
