### ISSUE TITLE
Cleanup PathTrie

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#25563]
From #25459:

We should further refactor `PathTrie` so that the params of `RestRequest` are not modified for each `TrieMatchingMethod`, and switch `PathTrie` over to using an `FST` from Lucene, rather than our own trie implementation.

Additionally, `PathTrie` should use the builder pattern so we create an immutable object rather than modifying the existing one.

**Comment by antbac** [comment]
I represent a group of people who would like to contribute to this issue, but seeing how I can't assign myself I'll just write this comment to notify you.

**Comment by antbac** [comment]
Sorry for the very late reply, but I am affraid our group has dispanded. We were unable to produce any satisfactory results so I won't be pushing a pull request.

**Comment by thecoop** [comment]
I'm going to fold this into #107425 to consider as part of that work
