### ISSUE TITLE
License description file is out of date for httpcore 4.4.5

### ISSUE THREAD

**Issue by silverzk** [elastic/elasticsearch#25567]
**Describe the feature**:

**Elasticsearch version**: 5.4.1

**Plugins installed**: [Null]

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): 2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: The license description file for httpcore package is out of date. Elasticsearch 5.4.1 bundles httpcore 4.4.5. The license of httpcore 4.4.5 should be pure Apache 2.0. The CC-BY-2.5 related codes have been removed by httpcore already since 4.4. Please update the license description file for httpcore 4.4.5 and remove the CC-BY-2.5 related description.
 
All the below files need to be updated:
plugins\repository-s3\licenses\httpcore-LICENSE.txt
plugins\discovery-ec2\licenses\httpcore-LICENSE.txt
plugins\repository-gcs\licenses\httpcore-LICENSE.txt

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by javanna** [comment]
Thanks for raising this, I opened #25573.
