### ISSUE TITLE
MSI installation requires administrator rights

### ISSUE THREAD

**Issue by fbaligand** [elastic/elasticsearch#25589]
**Elasticsearch version**: 
5.5.0

**OS version** :
Windows 7

**Description of the problem including expected versus actual behavior**:
When launching MSI installation, when I click on "INSTALL" button, a windows popup is launched which requires an Administrator authentication.
Despite I don't ask to start elasticsearch as a service.
That's a problem for people who has not Administrator rights on their windows hosts (like me).

=> Could you please not require Administrator rights when "start as a service" is not checked ?

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. launch MSI
 2. define locations where I have write access
 3. disable "start as a windows service"
4. do not check any plugin
5. click on INSTALL button
6. I get administrator authentication windows popup
7. I click "Cancel"
8. elasticsearch installation is cancelled

**Comment by wlisik** [comment]
Thats why Im not using ES - its shit

**Comment by jimczi** [comment]
@fbaligand you should open this issue directly on the windows installer repo:
https://github.com/elastic/windows-installers

**Comment by fbaligand** [comment]
OK @jimczi 

Done : https://github.com/elastic/windows-installers/issues/54
