### ISSUE TITLE
Specify the content type using the [Content-Type] header

### ISSUE THREAD

**Issue by alexcurtin** [elastic/elasticsearch#25584]
**Elasticsearch version**:
5.4.2
**Plugins installed**: 
kubernetes-discovery

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
official elasticsearch docker image (alpine? ubuntu?)
**Description of the problem including expected versus actual behavior**:
Setup an EFK stack in Google Container Engine and am getting lots of logs like this:

[o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.

**Steps to reproduce**:

Spin up an EFK stack with latest googles fluentd and elastic search 5.4.2, let the ES cluster boot and you will see the log [o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.

Is this because of how the latest FluentD is shipping logs off to elastic search?

**Provide logs (if relevant)**:

[o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header.

**Comment by tvernum** [comment]
Please ask this question on our [discuss forum](https://discuss.elastic.co/) where we can provide better support.
Elastic uses GitHub issues for confirmed bugs and feature requests which have been discussed on the forums.

Thank you.
