### ISSUE TITLE
ICUCollationKeywordFieldMapper should use Locale.ROOT as a default locale

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#25587]
It currently depends on the default locale, which makes it trappy: behaviour cannot be reproduced on machines that have a different locale.

**Comment by jpountz** [comment]
@andy-elastic I assigned this one to you as I thought you would be interested. For the record, there is no particular urgency.

**Comment by andy-elastic** [comment]
I did wonder where else this would appear after seeing (or rather, being told by the build) we disallow String.format with the default locale

This is where the default locale gets used, right?https://github.com/elastic/elasticsearch/blob/b24326271e6778d5d595005e7e1e4258e7e7ee24/plugins/analysis-icu/src/main/java/org/elasticsearch/index/mapper/ICUCollationKeywordFieldMapper.java#L389

**Comment by jpountz** [comment]
@andy-elastic Correct.

**Comment by andy-elastic** [comment]
Merged in #26413
