### ISSUE TITLE
Cant start ElasticSearch 5.5.0 with .gitkeep file in plugins directory

### ISSUE THREAD

**Issue by itkg-ppottie** [elastic/elasticsearch#25593]
**Describe the feature**: Elasticsearch cant start with a .gitkeep file in plugins directory

**Elasticsearch version**: 5.5.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_131

**OS version** (`uname -a` if on a Unix-like system): your Docker image version 5.5.0

**Description of the problem including expected versus actual behavior**:
using docke-compose to start Elastic Stack , i use volume to mount plugins directory.
To keep my own directory  on my git project , use .gitkeep file in this directory.

When i start services, Elasticsearch try to acces all items in plugins directory like a plugin , and not ignore hidden files.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. create a .gitkeep file in plugins directory of elasticsearch
 2. run the service

**Provide logs (if relevant)**:
[2017-07-07T09:30:23,932][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: org.elasticsearch.bootstrap.BootstrapException: java.nio.file.FileSystemException: /usr/share/elasticsearch/plugins/.gitkeep/plugin-descriptor.properties: Not a directory

**Comment by dadoonet** [comment]
This is expected as per #23982.
You are supposed to modify the plugins installation dir manually.

I'm closing but feel free to comment here or on discuss.elastic.co.
