### ISSUE TITLE
REST client support for PEM certs

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#25604]
From a quick chat with @jaymode , the current high level rest client implementation only supports referencing Java keystores and it will require additional code/libraries to be implemented in order for users to directly reference PEM certs.  This is an enhancement request to provide an option to reference PEM certs directly when using the client.

**Comment by javanna** [comment]
I updated title and labels, this is about the low-level REST client rather than the high level one.

**Comment by jordansissel** [comment]
@ppf2 To clarify, just certificates, right? Not keys?

**Comment by ppf2** [comment]
For this use case, yes, for specifying ca cert bundle.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
