### ISSUE TITLE
Query string search don't return aggregations

### ISSUE THREAD

**Issue by bleekbless** [elastic/elasticsearch#25605]
**Elasticsearch version**: 5.3.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.7

**OS version** (`uname -a` if on a Unix-like system): -a

**Description of the problem including expected versus actual behavior**:
I try to make a search where the parameter is 0 (zero) to filter the query in a query_string just like: "type:message AND sentimentScore:0" and i need aggregations but none was returned the bucket is empty even with many hits successful.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
