### ISSUE TITLE
Error:Unable to make the module: core_main, related gradle configuration was not found. Please, re-import the Gradle project and try again.

### ISSUE THREAD

**Issue by ljwh** [elastic/elasticsearch#25625]
I got a problem when I tried to build elasticserch through source code.
here is my steps:

with my linux (CentOS 7), 
1. I git pull the elasticsearch source code(v5.5.0).
2. run gradle idea  (IDEA) in project root directory:
```sh
gradle idea
```
3. gradle run in project root directory:
```sh
gradle run
```
4. Start elasticsearch with <strong> org.elasticsearch.bootstrap.Elasticsearch.main()</strong>
but got a problem like: 
<strong>"Error:Unable to make the module: core_main, related gradle configuration was not found. Please, re-import the Gradle project and try again."</strong>

**Comment by cbuescher** [comment]
I just checked this with a clean 5.5. checkout on Ubuntu and this works for me. 
@ljwh I'd like to ask you to open an issue in our [Discourse forum](https://discuss.elastic.co) or ask the question in out [IRC channels](https://www.elastic.co/community) if you continue having problems with building Elasticsearch. Elastic reserves GitHub for bug reports and feature requests.
