### ISSUE TITLE
HasChild/HasParentQuery related codes are moved to its own parent-child module in 5.5.0 but not mentioned in its release note

### ISSUE THREAD

**Issue by dynaxis** [elastic/elasticsearch#25624]
**Elasticsearch version**: 5.5.0

**Description of the problem including expected versus actual behavior**:
Parent-child related queries are all moved into its own module, and some API changes are breaking ones. For instance, `QueryBuilders.hasChildQuery/hasParentQuery` methods are moved into `JoinQueryBuilders`, and breaks existing codes.

But all the changes don't seem to be mentioned in the release note for 5.5.0.

**Comment by cbuescher** [comment]
@jimczi might be something we should add to the release notes for 5.5.1 and 5.6?

**Comment by martijnvg** [comment]
@dynaxis Thanks for noticing this. This should have been documented as breaking Java change and the java examples in the docs should have been updated.
