### ISSUE TITLE
Users unable Authenticate with LDAP account - Frequent LDAP timeout after few days

### ISSUE THREAD

**Issue by jayannah** [elastic/elasticsearch#25633]
We have ES cluster with dedicated Co-ordinator node in AWS region with high performance Ec2 instances r4.16xlarge . 

We have installed x-pack and configured the LDAP details for users to login to ES or Kibana with their LDAP user credentails.   Around 10-15 users login every min approx. 

Everything will be working fine and all users will be able to login to ES and Kibana.. After few days, ES nodes unable to establish connection to LDAP and all users login fails (see logs at bottom).

When I restart all the co-ordinator nodes (we have 3 co-ordinator nodes in the cluster & 9 data nodes, 4 master nodes dedicated) only, then everything will start working fine and all users are able to login//

again after few days, all user login fails... restarting co-ordinator nodes again solves for few days..

Please note: We are using the same 20s LDAP timeout connection in Splunk aswell and more than 1000+ users logs concurrently and we never seen any problem in Splunk connecting to LDAP. 

In Elastic Node, we have increased 30s and still see the timeout problem.

Why the restart fixes the issue for few days? 

**Elasticsearch version**:
5.4.2

**Plugins installed**: []
5.4.2

**JVM version** (`java -version`):
"1.8.0_73"

**OS version** (`uname -a` if on a Unix-like system):
Linux ip-200-xx-xx.xx.xxx.xx3.13.0-117-generic #164-Ubuntu SMP Fri Apr 7 11:05:26 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
The ES node unable to establish connection with LDAP hence users are unable to login with LDAP.

After restarting Co-ordinator nodes, everything will be fine for few days.. and after few days again we see this issue.

Here is the configuration file we have used. 
## cat /etc/elasticsearch/elasticsearch.yml
cluster.name: horiz_prod1_escluster1_e
node.name: 10.200.x.x
node.master: false
node.data: false
node.ingest: false
bootstrap.memory_lock: true
network.host: 127.0.0.1,10.200.x.x
http.port: 8089
bootstrap.seccomp: false
discovery.zen.ping.unicast.hosts: [ esm1,esm2,esm3,esm4 ]
discovery.zen.minimum_master_nodes: 3
discovery.zen.master_election.ignore_non_master_pings: true
discovery.zen.fd.ping_timeout: 120s
action.destructive_requires_name: true
cluster.routing.allocation.same_shard.host: true
indices.fielddata.cache.size: 20%
indices.breaker.fielddata.limit: 30%
indices.breaker.request.limit: 30%
cluster.routing.allocation.cluster_concurrent_rebalance: 4
thread_pool.bulk.queue_size: 5000
discovery.zen.ping_timeout: 6s
discovery.zen.commit_timeout: 60s
xpack.security.authc.realms.native.type: native
xpack.security.authc.realms.native.order: 0
xpack.security.authc.realms.active_directory.type: active_directory
xpack.security.authc.realms.active_directory.order: 1
xpack.security.authc.realms.active_directory.domain_name: xxx.xx.xxxx.com
xpack.security.authc.realms.active_directory.url: ldaps://xxxx.xxxx.xxx.com:636
xpack.security.authc.realms.active_directory.ssl.certificate: "/etc/elasticsearch/x-pack/esc.cert.cert"
xpack.security.authc.realms.active_directory.ssl.key_passphrase: elastic
xpack.security.authc.realms.active_directory.ssl.key: "/etc/elasticsearch/x-pack/esc.cert.key"
xpack.security.authc.realms.active_directory.ssl.verification_mode: none
xpack.security.authc.realms.active_directory.unmapped_groups_as_roles: true
xpack.security.authc.realms.active_directory.timeout.tcp_connect: 30s
xpack.security.authc.realms.active_directory.timeout.tcp_read: 30s
xpack.security.authc.realms.active_directory.timeout.ldap_search: 30s

**Steps to reproduce**:
 Login to Kibana or ES co-ordinator node with LDAP user credentials fails due to the timeout issue. 

**Provide logs (if relevant)**:

Logs seen in the Elastic Co-ordinator nodes 

[2017-07-10T13:19:40,048][WARN ][o.e.x.s.a.AuthenticationService] [10.203.3.174] Authentication to realm active_directory failed - authenticate failed (Caused by LDAPException(resultCode=91 (connect error), errorMessage='An error occurred while attempting to connect to server xxx.xxx.xxxx.com:636:  java.io.IOException: LDAPException(resultCode=91 (connect error), errorMessage='Unable to establish a connection to server xxx.xxx.xxx.com/10.6.39.94:636 within the configured timeout of 30000 milliseconds.')'))

**Comment by spinscale** [comment]
please create a post in the forum or open a customer support issue with issues regarding `x-pack`. This repository is for issues regarding Elasticsearch only (the open source part of it). Thanks a lot!
