### ISSUE TITLE
Search wiht numeric characters

### ISSUE THREAD

**Issue by erenglr** [elastic/elasticsearch#25639]
Hi,

I make search with numeric character but I don't find the appropriate result. How do I make?

e.g :
POST autocomplate/serchtype/_search
{"query": {
"query_string": {
"default_field": "name",
"query": "*4rea*"
}
}
}

Thanks.

**Comment by spinscale** [comment]
please ask this kind of question over in the [Elasticsearch discussion forum](https://discuss.elastic.co/c/elasticsearch) - github issues is reserved for issues/bugs only.
