### ISSUE TITLE
does snapshot support nfs?  always Access Denied.

### ISSUE THREAD

**Issue by KeithTt** [elastic/elasticsearch#25640]
es/logstash/kibana version: 5.4.1

https://www.elastic.co/guide/en/elasticsearch/reference/5.5/modules-snapshots.html#modules-snapshots

I follow the official guide to create a snapshot with NFS shared file system, but always failed.

it tells "Access Denied...", I have chown and chmod the ownship of the shared directory.

I run the command on the Dev Tools of Kibana, here is part of the logs of the snapshot:
```
{
  "index": "zixun-nginx-access-2017.07.11",
  "index_uuid": "zixun-nginx-access-2017.07.11",
  "shard_id": 0,
  "reason": "IndexShardSnapshotFailedException[Failed to snapshot]; nested: ElasticsearchException[failed to create blob container]; nested: AccessDeniedException[/nh/esbk/my_backup/indices/DSfpzIRoRF67Ya7ZypAkkA/0]; ",
  "node_id": "4BhIJY_dRxC6LpJj1mXYQw",
  "status": "INTERNAL_SERVER_ERROR"
},        
```

**Comment by spinscale** [comment]
please ask this kind of question over in the [Elasticsearch discussion forum](https://discuss.elastic.co/c/elasticsearch) - github issues is reserved for issues/bugs only.
