### ISSUE TITLE
Make slop optional in span near query

### ISSUE THREAD

**Issue by juretta** [elastic/elasticsearch#25642]
The documentation for the [span near query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-span-near-query.html) suggests that `slop` is optional. 
But if `slop` is not included, an error is returned:

```
  "error": {
    "root_cause": [
      {
        "type": "parsing_exception",
        "reason": "span_near must include [slop]",
        "line": 18,
        "col": 5
      }
    ],
    "type": "parsing_exception",
    "reason": "span_near must include [slop]",
    "line": 18,
    "col": 5
  },
```

Lucene's `org.apache.lucene.search.spans.SpanNearQuery` defaults `slop` to 0.

It seems that either `slop` should be in fact optional (i.e. it can be omitted) or should be defaulted or the docs should be changed to make it a required value.

**Comment by spinscale** [comment]
indeed, this could be written more explicit. We'd also appreciate a PR on it, if you are willing to help out. The file is at https://github.com/elastic/elasticsearch/blob/master/docs/reference/query-dsl/span-near-query.asciidoc and could be edited directly from github

**Comment by juretta** [comment]
Happy to help out but tbh. I'm not entirely sure whether the current behaviour is correct (it's probably not wrong) or ideal.

Seems `slop` could in fact be optional and default to `0`, i.e. match what the documentation says.

But then it becomes a code change, not an update to the docs.

**Comment by javanna** [comment]
I am not sure either whether this is just a docs issue. We introduced validation for the `slop` field although we could just default it to `0` if not present, like lucene does. @cbuescher what do you think?

**Comment by cbuescher** [comment]
The check for "slop" was already part of the "old" SpanNearQueryParser before the refactoring, so I have a feeling we can safely remove it.
