### ISSUE TITLE
Translog file already exists exception thrown on old indices on second restart

### ISSUE THREAD

**Issue by cnsinger** [elastic/elasticsearch#25662]
Hello, 

I hive this bug on my v2.0.0 elasticsearch. How to fix this? Just upgrade my elasticsearch?

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
