### ISSUE TITLE
import data from postgres 9.6 to elasticsearch 5.5 in windows !

### ISSUE THREAD

**Issue by matt212** [elastic/elasticsearch#25665]
hi,
how to import and ultimately sync data from postgres 9.6 to elasticsearch 5.5 
i know logtash exist but there is not download option or installation for windows !
the elastic jdbc has this issues
https://github.com/jprante/elasticsearch-jdbc/issues/962

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by matt212** [comment]
hi @dadoonet  ,
thanks ! create a post on provided discussion platform !
https://discuss.elastic.co/t/import-data-from-postgres-9-6-to-elasticsearch-5-5-in-windows/92785
