### ISSUE TITLE
Content-Type JSON and NDJSON are interchangeable for _bulk and _msearch

### ISSUE THREAD

**Issue by olcbean** [elastic/elasticsearch#25673]
Currently in the documentation for `_bulk` and `_mseach` is stated : 

> NOTE: the final line of data must end with a newline character \n. Each newline character may be preceded by a carriage return \r. When sending requests to this endpoint the `Content-Type` header should be set to `application/x-ndjson`.

However both endpoints accept `Content-Type: application/json`.

~~Also `delete` api (any any other one) accepts `Content-Type: application/x-ndjson`~~

~~`curl -H "Content-Type: application/x-ndjson" -XDELETE 127.0.0.1:9200/_all`~~

**Comment by jaymode** [comment]
> However both endpoints accept Content-Type: application/json.

This was done to avoid breaking clients that sent bulk/msearch bodies with a content type of JSON instead of the ndjson content type. I can see how this is misleading.

> Also delete api (any any other one) accepts Content-Type: application/x-ndjson

The request you provided does not have a body; if you add a body this will be rejected.

**Comment by javanna** [comment]
Maybe we should update the docs to mention that both content-types are supported, or do we plan to only support ndjson in the future for bulk and msearch?

**Comment by jaymode** [comment]
I think we should only support ndjson for these endpoints in the future

**Comment by javanna** [comment]
Alright, maybe we should issue a deprecation warning in case json is specified then and open an issue to formally deprecate it?

**Comment by olcbean** [comment]
@jaymode deprecating json should be a straightforward task. I would like to have a go at it.

**Comment by jaymode** [comment]
@olcbean I am not sure it is that simple. There are some tricky aspects such as the rest tests that use these endpoints and ensuring we don't fail due to the deprecation warnings. Also, the rest tests and api specs do not indicate if an API supports content streaming and changing this may require coordination with other consumers of these specs, right @javanna ?

**Comment by javanna** [comment]
yea I agree there is some coordination needed with the clients team , and we may have to update the spec for bulk and msearch.

**Comment by olcbean** [comment]
I see, indeed it needs more coordination. Nevertheless, given I have spent some time on this part of the internals - please consider assigning me this set of changes once there is clarity on the new spec. Thanks!

**Comment by javanna** [comment]
Thank you @olcbean we will keep that in mind. Closing this issue in favour of #25718.
