### ISSUE TITLE
index.mapper.dynamic: ignored when applied after index creation

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#25683]
Tested under ES 5.5.

As raised initially here - https://discuss.elastic.co/t/index-mapper-dynamic-doesnt-work/65653

When the `index.mapper.dynamic` is applied after index creation, the setting is ignored:

```
PUT /test_index

PUT /test_index/_settings
{
"index.mapper.dynamic":false
}

POST /test_index/test
{
 "asdf": 1
}
```
 ↓
```
...
"created": true
...
```

Whereas if you apply the setting at index creation, type creation is disabled as expected:

```
PUT /test_index
{
   "settings": {
      "index.mapper.dynamic": false
   }
}

POST /test_index/test
{
 "asdf": 1
}
```
 ↓
```
...
"reason": "trying to auto create mapping, but dynamic mapping is disabled"
...
```

**Comment by Crunkle** [comment]
+1

**Comment by PhaedrusTheGreek** [comment]
As pointed out in #25681, `index.mapper.dynamic` [is going away](https://github.com/elastic/elasticsearch/issues/25719) , so this issue can probably be closed.
