### ISSUE TITLE
index.mapper.dynamic: confusing purpose

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#25681]
The `index.mapper.dynamic` index setting clearly says in the documentation that it prevents automatic type creation, but I think it could be easily misunderstood as preventing dynamic field mapping.    

To clear things up, [the documentation for dynamic mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-mapping.html) could explain the difference between disabling _Dynamic Mapping_ and disabling [Dynamic Field Mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-field-mapping.html#dynamic-field-mapping)

**Comment by javanna** [comment]
heya @PhaedrusTheGreek would you like to send a PR to amend this?

**Comment by PhaedrusTheGreek** [comment]
Will do, but first I wonder if its worth discussing whether or not `index.mapper.dynamic` should either be renamed to something like `index.mapper.dynamic_types`   or alternately if it should encompass the disabling of all dynamic field mappings in the index.

**Comment by javanna** [comment]
ok I will mark this for discussion then.

**Comment by clintongormley** [comment]
We should remove the setting - we're only going to have one type going forwards

**Comment by javanna** [comment]
Given @clintongormley 's comment, I am going to close this issue in favour of #25719.
