### ISSUE TITLE
[CI] testMockFailToSendNoConnectRule failure

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#25686]
console logs: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/1231/console

```
FAILURE 0.11s J2 | SimpleNioTransportTests.testMockFailToSendNoConnectRule <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: exception should be thrown
   > 	at __randomizedtesting.SeedInfo.seed([EA2A25444D87DEAC:BE8C6C44F1EC7A36]:0)
   > 	at org.elasticsearch.transport.AbstractSimpleTransportTestCase.testMockFailToSendNoConnectRule(AbstractSimpleTransportTestCase.java:1466)
```

Maybe a flaky issue, I cannot reproduce?

```
gradle :test:framework:test -Dtests.seed=EA2A25444D87DEAC -Dtests.class=org.elasticsearch.transport.nio.SimpleNioTransportTests -Dtests.method="testMockFailToSendNoConnectRule" -Dtests.security.manager=true -Dtests.locale=ar-LY -Dtests.timezone=Asia/Beirut
```

**Comment by talevy** [comment]
may be related https://github.com/elastic/elasticsearch/commit/507418b66719bca25a66a007380dca53ba8499f7

**Comment by talevy** [comment]
another similar occurance: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/3509/console

**Comment by droberts195** [comment]
Same failure in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/1263/console

**Comment by andy-elastic** [comment]
Seeing this now in SimpleNetty4TransportTests on 5.6, I'll backport this fix there

* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+oracle-periodic/567/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+java9-periodic/603/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+multijob-unix-compatibility/os=debian/155/console
