### ISSUE TITLE
Tokenizers should have whitelists

### ISSUE THREAD

**Issue by rlvoyer** [elastic/elasticsearch#25688]
Tokenizers should have an additional configuration setting called `whitelist` that indicates terms that are exceptions to the tokenizer rules and should always be preserved in their original form. This would enable functionality that is akin to what the [keyword marker token filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-keyword-marker-tokenfilter.html) provides, the difference being that the keyword marker token filter prevents stemming from altering tokens. At first glance, the [keep words token filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-keep-words-tokenfilter.html) looks like it might provide the functionality I'm asking for, but it keeps *only* the provided terms.

**Comment by clintongormley** [comment]
@rlvoyer Our analysis function just exposes what is provided by Lucene.  If you want this implemented (and from your description I don't understand exactly what you're after) then you should open an issue on Lucene
