### ISSUE TITLE
Released versions tests failure in 5.4

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#25682]
there is an expectation that `5.4` tests be aware of the released `5.5`. This check fails:

```
Execution failed for task ':core:verifyVersions'.
> out-of-date released versions
  Actual  :[2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 5.0.0, 5.0.1, 5.0.2, 5.1.1, 5.1.2, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.4.0, 5.4.1, 5.4.2, 5.4.3]
  Expected:[2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 5.0.0, 5.0.1, 5.0.2, 5.1.1, 5.1.2, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.4.0, 5.4.1, 5.4.2, 5.4.3, 5.5.0]
```

console logs:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.4+intake/2/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.4+intake/3/console

guess it checks maven for all released versions... maybe it makes sense to filter until Version.CURRENT?

**Comment by jasontedor** [comment]
Closed by https://github.com/elastic/elasticsearch/commit/6ab4b306a22b72336b149a2714a9d0359d6637f3
