### ISSUE TITLE
Document file scripting removal in breaking changes and remove file script references in documentation

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#25690]
File scripts and related settings (eg. path.scripts) were deprecated in 5.5 and [removed](https://github.com/elastic/elasticsearch/pull/24627) in 6.0+.  

I think we will want to document this at https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_60_scripting_changes.html and/or https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_60_settings_changes.html.  

We will also want to remove references to file scripts from various parts of the scripting documentation

- https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-using.html#modules-scripting-using-caching still mentions file scripts being cached
- https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-security.html#modules-scripting-security-do-no-weaken still mentions ES running filesystem scripts for default languages.

**Comment by rjernst** [comment]
Closed by #26579
