### ISSUE TITLE
Tests for indices.put_template use illegal action

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch#25694]
https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/test/indices.put_template/10_basic.yml#L221-L225 uses a directive `raw` which is not documented in the test specifications (https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/test/README.asciidoc) and it is not marked with a `skip.feature` to ensure forwards compatibility of all the clients.

My suggestion is to remove the test since it is anyway something that seems to belong more in a Java-based test - typically the REST tests serve to check the declared API (not raw requests) and that checks the required parameters in the client side so this test would never be possible.

This affects all versions >= 5.5.0

**Comment by rjernst** [comment]
The entire put_template api is deprecated in 5.6 (#25437) and will be removed for 6.0. Is it alright to just have the test go away in master, or is it necessary for the client tests to work with 5.x (can they just blacklist that test?)?

**Comment by HonzaKral** [comment]
In that case the easiest would be to annotate that test with:
```
     - skip:
          features:    raw
```
so that the clients, that haven't implemented the `raw` feature will automatically skip it.

Thanks!

**Comment by javanna** [comment]
Seems like we have these raw requests in some other tests. They come from https://github.com/elastic/elasticsearch/commit/5463294ec4bf3c6d22532840c3c2fd28a1f035bc . Raw is something that should only be used for docs tests, I wouldn't introduce it in yaml tests. I think these tests shouldn't be yaml tests, we should migrate them to java tests that extend `ESRestTestCase` instead.

**Comment by nik9000** [comment]
I imagine we can only enable `raw` for the docs which would prevent this from happening again.

**Comment by javanna** [comment]
@nik9000 that would be nice, I think we have to get used to a different way of writing these tests. We can use java now, we don't have to use yaml all the time :)

**Comment by karmi** [comment]
> is it necessary for the client tests to work with 5.x

Yes, we need to run the tests on the `5.x` branch as well, so either let's rewrite the test to not use the `raw` action, or annotate it with `skip` correctly, as @HonzaKral suggests.

**Comment by javanna** [comment]
I plan on rewriting these tests in java, I just need to get to this... next week hopefully?
