### ISSUE TITLE
UpgradeClusterClientYamlTestSuiteIT fails due to search template deprecation 

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#25702]
See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/1250

gradle :qa:rolling-upgrade:v5.6.0-SNAPSHOT#oldClusterTestRunner -Dtests.seed=33BA1EC69E0B164A -Dtests.class=org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT -Dtests.method="test {p0=old_cluster/10_basic/Index data, search, and create things in the cluster state that we'll validate are there after the ugprade}" -Dtests.security.manager=true -Dtests.locale=ar-AE -Dtests.timezone=EST -Dtests.rest.suite=old_cluster

```
   > Throwable #1: java.lang.AssertionError: Failure at [old_cluster/10_basic:107]: got unexpected warning header [
   > 	299 Elasticsearch-5.6.0-SNAPSHOT-ec66d65 "The stored search template API is deprecated. Use stored scripts instead." "Thu, 13 Jul 2017 09:02:21 GMT"
   > ]
```

This deprecation was added in #25437.

I *think* the test is actually meant to check that templates indexed in 5.x actually still work in 6.0 but I'm not sure of the details. @martijnvg  can you check?

**Comment by martijnvg** [comment]
Test failure has been fixed.
