### ISSUE TITLE
[5.5] More like this query documentation references deprecated 'string' type

### ISSUE THREAD

**Issue by joshua2ua** [elastic/elasticsearch#25713]
From https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-mlt-query.html
(same in current, 5.x and 5.5)

> The fields on which to perform MLT must be indexed and of type string. Additionally, when using like with documents, either _source must be enabled or the fields must be stored or store term_vector. In order to speed up analysis, it could help to store term vectors at index time.

But the string type was split into text and keyword. Does MLT work on text and keyword or just text?

**Comment by javanna** [comment]
hi @joshua2ua thanks a lot for opening this issue, I am going to push a docs fix for it.
