### ISSUE TITLE
[2.3.2] string_index_out_of_bounds_exception when requesting an empty string in _source

### ISSUE THREAD

**Issue by mrec** [elastic/elasticsearch#25712]
**Elasticsearch version**: 2.3.2

**Plugins installed**: [analysis-icu 2.3.2, analysis-korean 2.3.2, analysis-kuromoji 2.3.2, analysis-smartcn 2.3.2, analysis-stconvert 1.8.3, delete-by-query 2.3.2, enhanced-highlighter 2.3.2-1.6, enhanced-plain-highlighter 2.3.2-1.7, entsearch 2.3.2-1.6, head master, license 2.3.2, marvel-agent 2.3.2, reindex 2.3.2,
repository-hdfs 2.3.1]

**JVM version**: 1.8.0

**OS version**: Oracle Linux Server 6.5

**Description of the problem including expected versus actual behavior**:

When picking properties to return via `_source`, if the first one listed is an empty string, the shard containing a matching doc fails with
~~~
        "reason": {
          "type": "string_index_out_of_bounds_exception",
          "reason": "String index out of range: 0"
        }
~~~
This does not happen for empty strings at other positions in the list, or for `fields`, or for strings consisting entirely of spaces, or for strings which don't name valid properties, so I expect the empty string here to be ignored. 

Obviously this isn't something you'd do deliberately, but it can happen if a caller sends something like `select=A,,B,C` to your service and you a) sort fields for consistency/readability and b) aren't sanitizing your inputs enough (*embarrassed cough*).

**Steps to reproduce**:
~~~
PUT mrec
{
  "mappings": {
    "doc": {
      "properties": {
        "s": {
          "type": "string",
          "analyzer": "standard"
        }
      }
    }
  }
}

PUT mrec/doc/1
{
  "s":"apple"
}

GET mrec/_search
{
  "_source": ["","s"]
}
~~~

The following do **NOT** trigger the error:

~~~
GET mrec/_search
{
  "_source": ["s",""]
}

GET mrec/_search
{
  "_source": [" ","s"]
}

GET mrec/_search
{
  "fields": ["","s"]
}
~~~

**Comment by rjernst** [comment]
This does not reproduce for me on master. It is highly unlikely we will do another 2.4.x release, and even if we did I do not anticipate anyone prioritizing tracking down what change occurred to fix this over 2 major versions of development. Given that, I hope you don't mind that I am closing this issue.
