### ISSUE TITLE
Remove index.mapper.dynamic setting

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#25719]
As mentioned in #25681 , the `index.mapper.dynamic` setting should be removed as we are going to support one type only.

**Comment by PnPie** [comment]
Hello,
If no one is on this, I would like to make a PR :)

**Comment by wlisik** [comment]
No `SCSI` enclosed so entitle XPA.

**Comment by javanna** [comment]
This was addressed with #25734
