### ISSUE TITLE
Rest Tests for Painless do not respect the API spec

### ISSUE THREAD

**Issue by HonzaKral** [elastic/elasticsearch#25737]
In (0) you can see a test that uses `lang` instead of `id` to get around the bug fixed by  #25736

This test, however, should be failing since it doesn't specify both `lang` and `id` which are marked as required in the API spec. This suggests that either the test is not being run as it should or that the test runner doesn't check for all required attributes.

0 - https://github.com/elastic/elasticsearch/blob/5.x/modules/lang-painless/src/test/resources/rest-api-spec/test/painless/16_update2.yaml#L7-L9

**Comment by javanna** [comment]
The test is run, but the java yaml test runner doesn't check whether required parameters are specified or not. That unfortunately allows for writing tests that may not work when run from other runners. Marking adoptme.

**Comment by olcbean** [comment]
Hey @javanna, can I give this one a try if you are not working on it? my thinking is to enforce not only the `params` but also the required `parts`.

**Comment by javanna** [comment]
go for it @olcbean , thanks!

**Comment by olcbean** [comment]
@HonzaKral the test is correct but unfortunately the `rest-api-spec` for [put_script](https://github.com/elastic/elasticsearch/blob/07de031195f3af912e4f22e33d7f8d0a6f43388e/rest-api-spec/src/main/resources/rest-api-spec/api/put_script.json#L12) in `5.6` contains a minor mistake : `id` should have been `"required" : false` (see #26923 for more details; the same applies to [delete_script](https://github.com/elastic/elasticsearch/blob/07de031195f3af912e4f22e33d7f8d0a6f43388e/rest-api-spec/src/main/resources/rest-api-spec/api/delete_script.json#L12) and [get_script](https://github.com/elastic/elasticsearch/blob/07de031195f3af912e4f22e33d7f8d0a6f43388e/rest-api-spec/src/main/resources/rest-api-spec/api/get_script.json#L12)).

#27035 makes sure that if a url parameter is specified as `required` but it is not provided, then the test fails.

@HonzaKral @javanna is there anything else that needs to be done for this issue? 
(The mentioned  issues are fixed for `6.0`+)

**Comment by javanna** [comment]
I think we are good @olcbean , closing! Thanks a lot for your contributions!
