### ISSUE TITLE
Fail to run rest api test.

### ISSUE THREAD

**Issue by lucianspec** [elastic/elasticsearch#25758]
$ gradle :distribution:integ-test-zip:integTest \
>   -Dtests.class="org.elasticsearch.test.rest.*Yaml*IT" \
>   -Dtests.method="test {p0=cat.shards/10_basic/Help}"

> Configure project :benchmarks
The getTestClassesDir() method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the getTestClassesDirs() method instead.
        at build_dz8rqo2bw7pljcnxbnb3z3la1.run(/Users/luxin433/WorkSpace/ResearchLab/Elasticsearch/elasticsearch/benchmarks/build.gradle:31)
=======================================
Elasticsearch Build Hamster says Hello!
=======================================
  Gradle Version        : 4.0.1
  OS Info               : Mac OS X 10.12.1 (x86_64)
  JDK Version           : Oracle Corporation 1.8.0_92 [Java HotSpot(TM) 64-Bit Server VM 25.92-b14]
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home
  Random Testing Seed   : AA259FD4444DA4C1
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0

> Task :distribution:integ-test-zip:integTestCluster#wait

Node 0 configuration:
|-----------------------------------------
|  cwd: /Users/luxin433/WorkSpace/ResearchLab/Elasticsearch/elasticsearch/distribution/integ-test-zip/build/cluster/integTestCluster node0/cwd
|  command: sh /Users/luxin433/WorkSpace/ResearchLab/Elasticsearch/elasticsearch/distribution/integ-test-zip/build/cluster/integTestCluster node0/cwd/run -E node.portsfile=true --path.conf /Users/luxin433/WorkSpace/ResearchLab/Elasticsearch/elasticsearch/distribution/integ-test-zip/build/cluster/integTestCluster node0/elasticsearch-6.0.0-beta1-SNAPSHOT/config -E path.data=/Users/luxin433/WorkSpace/ResearchLab/Elasticsearch/elasticsearch/distribution/integ-test-zip/build/cluster/integTestCluster node0/elasticsearch-6.0.0-beta1-SNAPSHOT/data
|  environment:
|    JAVA_HOME: /Users/luxin433/.jenv/versions/1.8
|    ES_JAVA_OPTS:  -Xms512m -Xmx512m  -ea -esa
|    CONF_DIR: /Users/luxin433/WorkSpace/ResearchLab/Elasticsearch/elasticsearch/distribution/integ-test-zip/build/cluster/integTestCluster node0/elasticsearch-6.0.0-beta1-SNAPSHOT/config
|
|  [run]
    "/Users/luxin433/WorkSpace/ResearchLab/Elasticsearch/elasticsearch/distribution/integ-test-zip/build/cluster/integTestCluster node0/elasticsearch-6.0.0-beta1-SNAPSHOT/bin/elasticsearch" "$@" > run.log 2>&1 ; if [ $? != 0 ]; then touch run.failed; fi
|
|  [elasticsearch.yml]
|    cluster.name: distribution_integ-test-zip_integTestCluster
|    node.name: node-0
|    pidfile: /Users/luxin433/WorkSpace/ResearchLab/Elasticsearch/elasticsearch/distribution/integ-test-zip/build/cluster/integTestCluster node0/es.pid
|    path.repo: /Users/luxin433/WorkSpace/ResearchLab/Elasticsearch/elasticsearch/distribution/integ-test-zip/build/cluster/shared/repo
|    path.shared_data: /Users/luxin433/WorkSpace/ResearchLab/Elasticsearch/elasticsearch/distribution/integ-test-zip/build/cluster/shared/
|    node.attr.testattr: test
|    node.max_local_storage_nodes: 1
|    http.port: 0
|    transport.tcp.port: 0
|    cluster.routing.allocation.disk.watermark.low: 1b
|    cluster.routing.allocation.disk.watermark.high: 1b
|    cluster.routing.allocation.disk.watermark.flood_stage: 1b
|-----------------------------------------
Node 0 output:
|-----------------------------------------
|  failure marker exists: false
|  pid file exists: true
|  http ports file exists: true
|  transport ports file exists: true
|
|  [ant output]
|         [echo] ==> [Tue Jul 18 12:47:59 CST 2017] checking health: http://[::1]:49829/_cluster/health?wait_for_nodes=>=1&wait_for_status=yellow
|          [get] Getting: http://[::1]:49829/_cluster/health?wait_for_nodes=>=1&wait_for_status=yellow
|          [get] To: /Users/luxin433/WorkSpace/ResearchLab/Elasticsearch/elasticsearch/distribution/integ-test-zip/build/cluster/integTestCluster node0/cwd/wait.success
|          [get] Error getting http://[::1]:49829/_cluster/health?wait_for_nodes=>=1&wait_for_status=yellow to /Users/luxin433/WorkSpace/ResearchLab/Elasticsearch/elasticsearch/distribution/integ-test-zip/build/cluster/integTestCluster node0/cwd/wait.success
|
|  [log]
|    [2017-07-18T12:47:53,934][INFO ][o.e.n.Node               ] [node-0] initializing ...
|    [2017-07-18T12:47:54,017][INFO ][o.e.e.NodeEnvironment    ] [node-0] using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [27.4gb], net total_space [232.6gb], types [hfs]
|    [2017-07-18T12:47:54,018][INFO ][o.e.e.NodeEnvironment    ] [node-0] heap size [494.9mb], compressed ordinary object pointers [true]
|    [2017-07-18T12:47:54,019][INFO ][o.e.n.Node               ] [node-0] node name [node-0], node ID [a5w5uJw6SCyLvth8X-ryOA]
|    [2017-07-18T12:47:54,020][INFO ][o.e.n.Node               ] [node-0] version[6.0.0-beta1-SNAPSHOT], pid[28958], build[7739aad/2017-07-18T04:13:23.285Z], OS[Mac OS X/10.12.1/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_92/25.92-b14]
|    [2017-07-18T12:47:54,020][INFO ][o.e.n.Node               ] [node-0] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -XX:+HeapDumpOnOutOfMemoryError, -Xms512m, -Xmx512m, -ea, -esa, -Des.path.home=/Users/luxin433/WorkSpace/ResearchLab/Elasticsearch/elasticsearch/distribution/integ-test-zip/build/cluster/integTestCluster node0/elasticsearch-6.0.0-beta1-SNAPSHOT]
|    [2017-07-18T12:47:54,020][WARN ][o.e.n.Node               ] [node-0] version [6.0.0-beta1-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
|    [2017-07-18T12:47:54,149][INFO ][o.e.p.PluginsService     ] [node-0] loaded module [transport-netty4]
|    [2017-07-18T12:47:54,150][INFO ][o.e.p.PluginsService     ] [node-0] no plugins loaded
|    [2017-07-18T12:47:55,239][INFO ][o.e.d.DiscoveryModule    ] [node-0] using discovery type [zen]
|    [2017-07-18T12:47:55,724][INFO ][o.e.n.Node               ] [node-0] initialized
|    [2017-07-18T12:47:55,724][INFO ][o.e.n.Node               ] [node-0] starting ...
|    [2017-07-18T12:47:55,866][INFO ][o.e.t.TransportService   ] [node-0] publish_address {127.0.0.1:49819}, bound_addresses {[fe80::1]:49817}, {[::1]:49818}, {127.0.0.1:49819}
|    [2017-07-18T12:47:58,920][INFO ][o.e.c.s.MasterService    ] [node-0] zen-disco-elected-as-master ([0] nodes joined), reason: new_master {node-0}{a5w5uJw6SCyLvth8X-ryOA}{k8DN2naiRFmw-CQBzBx4ew}{127.0.0.1}{127.0.0.1:49819}{testattr=test}
|    [2017-07-18T12:47:58,925][INFO ][o.e.c.s.ClusterApplierService] [node-0] new_master {node-0}{a5w5uJw6SCyLvth8X-ryOA}{k8DN2naiRFmw-CQBzBx4ew}{127.0.0.1}{127.0.0.1:49819}{testattr=test}, reason: apply cluster state (from master [master {node-0}{a5w5uJw6SCyLvth8X-ryOA}{k8DN2naiRFmw-CQBzBx4ew}{127.0.0.1}{127.0.0.1:49819}{testattr=test} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)]])
|    [2017-07-18T12:47:58,942][INFO ][o.e.h.n.Netty4HttpServerTransport] [node-0] publish_address {127.0.0.1:49830}, bound_addresses {[fe80::1]:49828}, {[::1]:49829}, {127.0.0.1:49830}
|    [2017-07-18T12:47:58,943][INFO ][o.e.n.Node               ] [node-0] started
|    [2017-07-18T12:47:58,945][INFO ][o.e.g.GatewayService     ] [node-0] recovered [0] indices into cluster_state
|-----------------------------------------

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':distribution:integ-test-zip:integTestCluster#wait'.
> Elasticsearch cluster failed to pass wait condition

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
