### ISSUE TITLE
Make index mandatory in terms lookup

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#25750]
When doing a terms lookup, we allow users to omit the index to get the terms from, in which case the index will be the same as the one that is being searched on.

When parsing the terms lookup info, we don't have the current index information available to set it to the created `TermsLookup` class. We end up sending the `TermsLookup` to the shards with the index field set to null. When rewriting the query, we need to carry some context so that we can fetch terms from the correct index if the index is null.

Assuming that this was done to avoid typing the index name twice, I wonder if we can get rid of this "leniency" and instead require the index name when doing terms lookups. This way users will have to be more explicit by always specifying `index`, `type` and `id` of the documents to fetch terms from.

**Comment by s1monw** [comment]
++ this makes perfect sense

**Comment by s1monw** [comment]
we discussed this in the todays clients meeting and agreed to deprecation in 5.6 and remove in 6.0
