### ISSUE TITLE
elasticsearch exclude._ip did not work

### ISSUE THREAD

**Issue by mars00772** [elastic/elasticsearch#25766]
Kibana Version: 4.5.1
Elasticsearch Version: 2.3.3
OS: CentOS release 6.4 
Plugins installed: [marvel]
java version "1.8.0_74"

I was trying to decommission a node ip[x.x.x.x],node name is [Mountjoy]:
```
curl -XPUT 'localhost:9200/_cluster/settings?pretty' -H 'Content-Type: application/json' -d'
{
  "transient" : {
    "cluster.routing.allocation.exclude._ip" : "x.x.x.x"
  }
}
'
```
after several hours,the Marvel show node's shards didn't decrease and elasticsearch v2.3.3 did not have any explaination apis. then i try other exclude attributes below,still didn't work!
```
"_host" : "x.x.x.x",
"_name" : "Mountjoy",
"_ip" : "x.x.x.x"
```
then i try open `    "cluster.routing.rebalance.enable": "none" ` to `"cluster.routing.rebalance.enable": "all"`,seems didn't work,just rebalancing.

the node setting and the info:
```
curl -XGET 'http://localhost:9200/_cluster/settings?pretty'
{
  "persistent" : { },
  "transient" : {
    "cluster" : {
      "routing" : {
        "rebalance" : {
          "enable" : "primaries"
        },
        "allocation" : {
          "cluster_concurrent_rebalance" : "12",
          "disk" : {
            "include_relocations" : "false"
          },
          "exclude" : {
            "_host" : "x.x.x.x",
            "_name" : "Mountjoy",
            "_ip" : "x.x.x.x"
          },
          "node_initial_primaries_recoveries" : "32",
          "balance" : {
            "index" : "1.00f",
            "threshold" : "1.00f",
            "shard" : "0.00f"
          }
        }
      }
    }

curl -XGET 'http://localhost:9200/_nodes?pretty'|less
nodes" : {
    "VnvVx5eZTVqG3WMoJfgFgA" : {
      "name" : "Mountjoy",
      "transport_address" : "x.x.x.x:9300",
      "host" : "x.x.x.x",
      "ip" : "x.x.x.x",

}

````

**Comment by ywelsch** [comment]
I think that you're hitting a bug fixed by #17698. Please upgrade and check if that helps.

**Comment by mars00772** [comment]
the indices setting **index.routing.allocation.require.{attribute}** didn't work!!
sometimes es didn't move the indices marked cold too the cold nodes! 
Am I hitting the same bug ? @ywelsch

**Comment by mars00772** [comment]
oh yes ,it was the bug prevent the cold indices allocation  to cold node,since I had some unassigned shards, all the cold indices stop reblanced without any log.
