### ISSUE TITLE
Match returns worse matching documents rather than better matching ones

### ISSUE THREAD

**Issue by danielspaniol** [elastic/elasticsearch#25762]
**Elasticsearch version**: 
5.2.1

**JVM version**:
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** :
Windows 7

**Description of the problem including expected versus actual behavior**:
In my use case I have a set of questions indexed in elastic and let the user enter a question and I want to find the best matching questions from elastic. 
There are some questions that distinguish in only one word (for example _"Which options do I have for the deductible height with a __partially__ comprehensive insurance?"_ vs _"Which options do I have for the deductible height with a __fully__ comprehensive insurance"_). <br>

**Expected**
When the user now enters a question that is already in Elastic I expect it to yield this question as best match

**Actual**
Elastic yields another question rather than the exact match. 

**Steps to reproduce**:

Create fresh test index

    curl -XDELETE "http://localhost:9200/foo"
    curl -XPUT "http://localhost:9200/foo"

Define mapping

    curl -XPUT "http://localhost:9200/foo/_mapping/foo" -d'
    {
      "properties": {
        "content": {
          "type": "text", 
          "analyzer": "english"
        }
      }
    }'

Index documents with two being very similar (The document being indexed last always has a lower score than the document being indexed second last)

    curl -XPOST "http://localhost:9200/_bulk?refresh" -d'
    { "index" : { "_index" : "foo", "_type" : "foo", "_id" : "1" } }
    { "content": "What is the difference between a fully comprehensive insurance and a partially comprehensive insurance?" }
    { "index" : { "_index" : "foo", "_type" : "foo", "_id" : "2" } }
    { "content": "Which options do I have for the deductible height with a fully comprehensive insurance" }
    { "index" : { "_index" : "foo", "_type" : "foo", "_id" : "3" } }
    { "content": "Which options do I have for the deductible height with a partially comprehensive insurance" }
    '

query with `match` for the last indexed document.
The same would happen if I only search for important terms `deductible height partially comprehensive insurance`

    curl -XGET "http://localhost:9200/foo/_search" -d'
    {
      "query": {
        "match": {
          "content": {
            "query": "Which options do I have for the deductible height with a partially comprehensive insurance"
          }
        }
      }  
    }'

Result (Note how the almost identical question has a much higher score than the identical one).

    "hits": {
        "total": 3,
        "max_score": 5.055572,
        "hits": [
          {
            "_index": "foo",
            "_type": "foo",
            "_id": "2",
            "_score": 5.055572,
            "_source": {
              "content": "Which options do I have for the deductible height with a fully comprehensive insurance"
            }
          },
          {
            "_index": "foo",
            "_type": "foo",
            "_id": "3",
            "_score": 2.8488503,
            "_source": {
              "content": "Which options do I have for the deductible height with a partially comprehensive insurance"
            }
          },
          {
            "_index": "foo",
            "_type": "foo",
            "_id": "1",
            "_score": 1.1623769,
            "_source": {
              "content": "What is the difference between a fully comprehensive insurance and a partially comprehensive insurance?"
            }
          }
        ]
      }

<hr>
Alternative:

query for a single word appearing in the similar questions

    curl -XGET "http://localhost:9200/foo/_search" -d'
    {
      "query": {
        "match": {
          "content": {
            "query": "options"
          }
        }
      }  
    }'

Still the document being indexed last has a much lower score

**Comment by cbuescher** [comment]
@danielspaniol What you are observing is normally a desired behaviour in text scoring. Its called length normalization, meaning that a term in a shorter field has more weight. You can read more about it in the [guide to elasticsearch](https://www.elastic.co/guide/en/elasticsearch/guide/current/scoring-theory.html). Of this is not the behaviour you want you probably need to experiment using a non-analyzed field or something else.

Please note that Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions like this, so I hope you don't mind me closing this.

**Comment by danielspaniol** [comment]
What I described is not desired behavior.
The document indexed last always has a lower score. If I just change the order of documents in my bulk request I get different results.
Also I do not expect a term that does not appear in my search query to produce a higher score than a term appearing in my search query.

`match` should not return `Which options do I have for the deductible height with a fully comprehensive insurance` as a better match than `Which options do I have for the deductible height with a partially comprehensive insurance`  just because the later was index last

**Comment by cbuescher** [comment]
> What I described is not desired behavior.

I understand this, but it still isn't a bug. Please ask further questions about text relevance in the forum. Just in case, have you read https://www.elastic.co/guide/en/elasticsearch/guide/current/relevance-is-broken.html? It might explain something about these kind of situations already.

**Comment by danielspaniol** [comment]
I've already read this article but didn't think I have that few documents in my productive system. 

But you are completely right. Even there I have very few documents (at least in ElasticSearch dimensions). I guess this completely screws with scores for these specific documents.
