### ISSUE TITLE
TransportClientNodesServiceTests#testListenerFailures() failure

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#25760]
Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/491/consoleFull

Reproduce line: ` gradle :core:test -Dtests.seed=B2B50E8F4C5D9FBC -Dtests.class=org.elasticsearch.client.transport.TransportClientNodesServiceTests -Dtests.method="testListenerFailures" -Dtests.security.manager=true -Dtests.locale=ar-TN -Dtests.timezone=Asia/Jayapura` (does not reproduce)

Failure:

```
FAILURE 4.04s J0 | TransportClientNodesServiceTests.testListenerFailures <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <true>
   >      but: was <false>
   > 	at __randomizedtesting.SeedInfo.seed([B2B50E8F4C5D9FBC:FBC31A17CA98DC8B]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.client.transport.TransportClientNodesServiceTests.testListenerFailures(TransportClientNodesServiceTests.java:273)
```

**Comment by jasontedor** [comment]
This looks like a test race condition; there's a timed wait for one second on a latch. I can easily see this timing out on an overloaded CI slave. In fact, if I lower this timeout to three milliseconds, the test sporadically passes and failures, supporting this theory. I do not understand the purpose of the timed wait here, I think that we should do an untimed wait here and let the test fail after the test timeout if for some reason the waiting thread is not unlatched.

**Comment by javanna** [comment]
Makes sense to me @jasontedor . The timeout was there from the early days (2014!) to prevent the test from running forever, not sure whether we had the suite timeout at the time, or whether this was just paranoia. I am good with getting rid of it, I was looking as well and I don't see any other reason for this test to fail.

**Comment by jasontedor** [comment]
Thanks for the context @javanna.
