### ISSUE TITLE
No booting elasticsearch (v5.5.0) for OSX. Due to hidden file check in plugins directory.

### ISSUE THREAD

**Issue by chanified** [elastic/elasticsearch#25783]
I'm having an issue where my elasticsearch won't start on an OSX machine if there is a hidden system file contained in the  /plugins directory called .DS_store. 
This is a common file to OSX which is automatically placed in most of it's directories for filesystem information but is an annoyance to have to continually delete it to start elasticsearch.

From what I can see in the org.elasticsearch.bootstrap.StartupException, it looks like it's looking for hidden directories and have noticed that on the breaking changes page for v5.5, this is meant to solve another issue. see https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-5.5.html

Is it possible to have .DS_store files ignored or make sure a check for the hidden is a directory is made for the next release? I feel that for some they'll be scratching their head when they can't figure out why elasticsearch isn't booting up on OSX :)

Cheers!

uncaught exception in thread [main] org.elasticsearch.bootstrap.StartupException: org.elasticsearch.bootstrap.BootstrapException: java.nio.file.FileSystemException: /SOME_DIR/elasticsearch-5.5.0/plugins/.DS_Store/plugin-descriptor.properties: Not a directory

**Comment by jasontedor** [comment]
Sorry for the trouble. These appear if you browse a non-empty directory in Finder. If you do not browse the `plugins` folder, they do not appear. We do not intend to revert back to being lenient here.
