### ISSUE TITLE
[DOCS] correct link to `compressed oops` java documentation

### ISSUE THREAD

**Issue by bczifra** [elastic/elasticsearch#25794]
The [heap sizing guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/heap-sizing.html) has a link to the [compressed oops documentation](https://wikis.oracle.com/display/HotSpotInternals/CompressedOops).  That links points to `https://wikis.oracle.com/display/HotSpotInternals/CompressedOops`.  However, that now redirects to `https://community.oracle.com/welcome`.

**Comment by jasontedor** [comment]
This is a definitive guide issue, would you please reopen this on its repository?
