### ISSUE TITLE
RestClient will be leaking internal.* packages in its public API

### ISSUE THREAD

**Issue by hub-cap** [elastic/elasticsearch#25798]
In working with shading the rest clients dependencies away, it was apparent that we need to possibly abstract away all the org.apache.http objects that are passed into the RestClient as well. For instance, the constructor and performRequest pass in Header and HttpEntity. With #25208, those are now in the internal.org.apache.http , so everything that uses the rest client will need to use our provided shaded classes.

Alternatively, we can "un-leak" this and make sure we do not have any internal.org.apache.http in the rest client API, and instead rely on Strings for headers and InputStreams for Entity content for the things we use currently. Im sure there are other things I am missing, so please chime in.

Relates #25208

**Comment by javanna** [comment]
Apart from avoiding having our own abstractions for headers and entity etc., the main point of not hiding the apache http client classes is the config part. If one needs to configure ssl or what have you ( and there's many things you can configure in the http client), they can do it using the standard http client config and we can simply link to their documentation.

> everything that uses the rest client will need to use our provided shaded classes

This means that e.g. users providing their config will be using our own `internal.org.apache.http` objects but apart from the imports everything else will be the same? Am I  missing some other implications of this?

**Comment by hub-cap** [comment]
I can see the need for custom config when creating your own `CloseableHttpAsyncClient`.

> This means that e.g. users providing their config will be using our own internal.org.apache.httpobjects but apart from the imports everything else will be the same? Am I missing some other implications of this?

This is correct, a client would just need to change all their `org.apache.http` to `internal.org.apache.http`. 

Ill gladly close this issue if this was an expected outcome of the rest client shading work. I wasn't sure so I wanted to bring it up.

**Comment by rjernst** [comment]
> Am I missing some other implications of this?

Yes, the implications are we will be forever "stuck" with the apache http client.  Keeping this out of the public api is what will allow us to even consider other http clients in the near or long term future.

Given the time frame, I assume we will have to live with this for at least 6.x (in which case we should rename the shaded prefix as "internal" then becomes very confusing as part of the public api).  But I think it is important to not restrict ourselves to one implementation forever by leaking the implementation details into the api.

**Comment by javanna** [comment]
I really don't see the problem with this. We can always change the underlying http client in a major version if we feel the need to. I don't think adding all these needed abstractions and maintaining them is worth the trouble, that was a conscious decision from the beginning.

**Comment by javanna** [comment]
Also, leaking of http client classes is not new with shading, it was already there. Good point on changing the package name as internal can become confusing.

**Comment by s1monw** [comment]
> I really don't see the problem with this. We can always change the underlying http client in a major version if we feel the need to. I don't think adding all these needed abstractions and maintaining them is worth the trouble, that was a conscious decision from the beginning.

I agree with this. at this point we have so many things to take care of, additional abstractions might be just noise. We can work towards changing it in 7.0 but for 6 we are set.

**Comment by javanna** [comment]
I will close this issue for now, we can re-open it in the future if we see that it's worth hiding these dependencies / replacing the http client impl, for now it's not.
