### ISSUE TITLE
SearchHit returns 'Double' value type instead 'Float'

### ISSUE THREAD

**Issue by RuslanDidyk** [elastic/elasticsearch#25792]
**Describe the feature**: When I have 'float' property in my Elasticsearch and I use Java Elasticsearch client to retrieve data - I always get 'double' values instead.

**Elasticsearch version:** 5.5.0
**JVM version:** 1.8.0_101
**OS version:** Windows 10

**Steps to reproduce:**

1. Create new index with the following mapping:
```
{  
    "mappings":{  
        "person":{  
            "properties":{  
                "salary":{  
                    "type":"float"
                }
            }
        }
    }
}
```
2. Create the following documents:

```
[  
    {  
        "salary":102002.6666666666666665,
    },
    {  
        "salary":65019.5,
    },
    {  
        "salary":80125.25,
    },
    {  
        "salary":96123.3333333333333333,
    }
]
```
3. Run code example:
```
        Settings settings = Settings.builder().put("cluster.name", "elasticsearch").build();
        PreBuiltTransportClient client = new PreBuiltTransportClient(settings);
        client.addTransportAddress(
                new InetSocketTransportAddress(InetAddress.getByName("localhost"), 9300));

        SearchRequestBuilder requestBuilder = client.prepareSearch("person").setTypes("person")
                .setQuery(QueryBuilders.matchAllQuery());
        SearchResponse response = requestBuilder.execute().actionGet();
        SearchHit firstHit = response.getHits().iterator().next();
        Map<String, Object> source = firstHit.getSource();
        for (Map.Entry<String, Object> entry : source.entrySet()) {
            assert entry.getValue() instanceof Float : "Value is not Float type!";
        }
```

**Actual behavior:**
Value is instance of 'double' type

**Expected behavior:**
Value is instance of 'float' type

**Comment by jpountz** [comment]
What is the `salary` type in your mappings?

**Comment by RuslanDidyk** [comment]
Sorry, there was a mistake:( It's okay right now.

`salary` type is - float

**Comment by jpountz** [comment]
This is due to the fact that you are retrieving the value from the `_source`, which is unaware of mappings. You might as well get an Integer or a Long if the number does not have a dot in its string representation.

We could use the field types that come from mappings in order to use the right types, but that would also come with drawbacks. For instance it is common to use floats rather than doubles to map floating-point numbers because they give smaller/faster indices however it might incur an accuracy loss. It might be ok for filtering/aggregating but the general contract of the `_source` is that it retains the original information of the json document.

I believe this is something we should better document in the Java API.

**Comment by wang0109** [comment]
@jpountz Are you saying that if I POST a Json with say `{ "salary": 5 }` or `{"salary" : "34.0"}`, the mapping is ignored and whatever the Json gives will be saved into ES?  (so a `int` and a `String`, instead of `float`)..

**Comment by jpountz** [comment]
@wang0109 The mapping defines how data is indexed and stored in doc-values. However, `_source` storage is unaware of the mappings indeed. When you get the source, Elasticsearch gives you back the same json document that had been posted at index time, it doesn't try to convert fields based on how they are mapped.

This means that for instance if you submit a numeric field (eg. mapped as `long`) as a string (`{"foo": "42"}`) then this field will still be returned as a string when fetching the source.

**Comment by wang0109** [comment]
@jpountz in your example, if I do a range query using a lower bound and upper bound, does "42" get compared alphabetical ly as a string or numerically as a `long`? It seems that some sort of implicit conversion rule happens internally, is that the case?

**Comment by jpountz** [comment]
How terms compare to one another is going to depend solely on mappings, not how they are represented in the `_source`. Specifically numbers will use the numeric order and keywords the alphabetical order. The icu_collation_keyword field even allows to sort based on a collation: https://www.elastic.co/guide/en/elasticsearch/plugins/master/analysis-icu-collation-keyword-field.html
