### ISSUE TITLE
Want to upgrade production elasticsearch from 1.7 to 5.5

### ISSUE THREAD

**Issue by darjisanket** [elastic/elasticsearch#25790]
**Describe the feature**:

**Elasticsearch version**:

**Plugins installed**: []

**JVM version** (`java -version`):
   java version "1.8.0_121"
**OS version** (`uname -a` if on a Unix-like system):
    linux
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
**Provide logs (if relevant)**:
I want to upgrade my production elasticsearch 1.7 version to 5.5 version 
-> I found out the below links https://www.elastic.co/guide/en/elasticsearch/reference/current/reindex-upgrade.html

Here we have 2 options:
I wanted to go with Upgrading with reindex-from-remote but issue what we faced is we have only single VM.
I will not able to install latest elasticsearch-5.5 because we have 1.7 installed.
Logs:
warning: elasticsearch-5.5.0.rpm: Header V4 RSA/SHA512 Signature, key ID d88e42b                                                       4: NOKEY
Preparing...                          ################################# [100%]
        file /etc/elasticsearch/elasticsearch.yml from install of elasticsearch-                                                       0:5.5.0-1.noarch conflicts with file from package elasticsearch-1.7.1-1.noarch
        file /etc/init.d/elasticsearch from install of elasticsearch-0:5.5.0-1.n                                                       oarch conflicts with file from package elasticsearch-1.7.1-1.noarch
        file /etc/sysconfig/elasticsearch from install of elasticsearch-0:5.5.0-                                                       1.noarch conflicts with file from package elasticsearch-1.7.1-1.noarch
        file /usr/share/elasticsearch/bin/elasticsearch from install of elastics                                                       earch-0:5.5.0-1.noarch conflicts with file from package elasticsearch-1.7.1-1.no                                                       arch
        file /var/lib/elasticsearch from install of elasticsearch-0:5.5.0-1.noar                                                       ch conflicts with file from package elasticsearch-1.7.1-1.noarch
        file /var/log/elasticsearch from install of elasticsearch-0:5.5.0-1.noar                                                       ch conflicts with file from package elasticsearch-1.7.1-1.noarch
        file /usr/lib/systemd/system/elasticsearch.service from install of elast                                                       icsearch-0:5.5.0-1.noarch conflicts with file from package elasticsearch-1.7.1-1                                                       .noarch
        file /usr/share/elasticsearch/NOTICE.txt from install of elasticsearch-0                                                       :5.5.0-1.noarch conflicts with file from package elasticsearch-1.7.1-1.noarch
        file /usr/share/elasticsearch/README.textile from install of elasticsear                                                       ch-0:5.5.0-1.noarch conflicts with file from package elasticsearch-1.7.1-1.noarc                                                       h
        file /usr/share/elasticsearch/bin/elasticsearch.in.sh from install of el                                                       asticsearch-0:5.5.0-1.noarch conflicts with file from package elasticsearch-1.7.                                                       1-1.noarch
        file /usr/share/elasticsearch/plugins from install of elasticsearch-0:5.                                                       5.0-1.noarch conflicts with file from package elasticsearch-1.7.1-1.noarch

Can you please suggest me how can I upgrade elasticseach from 1.7 to 5.5 without losing my data in single VM?

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by darjisanket** [comment]
Thanks. you can close this will ask same on forum.
