### ISSUE TITLE
Allow MultiGet to search across several indices or an alias with multiple indices.

### ISSUE THREAD

**Issue by jjbursik** [elastic/elasticsearch#25800]
**Feature Request:** Allow MultiGet to search across several indices or an alias with multiple indices.  

I can search for an ID using alias or over several indices, why is the MultiGet prohibiting this (understandable that this is an expensive query)?

**Comment by javanna** [comment]
hi @jjbursik your question is more suited for our [forums](https://discuss.elastic.co/), we reserve github issues for bugs or feature requests.

In short, get is not a query, it retrieves the document by id, hence it needs to know exactly where the document is, meaning index, type and id. If the alias points to multiple indices, which index can we retrieve the document from?
