### ISSUE TITLE
es2.3.3 OOM

### ISSUE THREAD

**Issue by fxltsbl3855** [elastic/elasticsearch#25801]
**Elasticsearch version**: Version: 2.3.3, Build: 218bdf1/2016-05-17T15:40:04Z

**Plugins installed**: [analysis-ik,head]

**JVM version** (`java -version`): 
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): 
Linux iZuf61tefvghtcladtg2l4Z 2.6.32-573.22.1.el6.x86_64 #1 SMP Wed Mar 23 03:35:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
**OS version** (`cat /etc/issue` ):  
CentOS release 6.5 (Final)
Kernel \r on an \m

**Description of the problem including expected versus actual behavior**:
problem: OOM when es run for two days 
 
**Steps to reproduce**:
After Elasticsearch started for two days,there will be OOM.
My operation include:
 1. insert doc to Elasticsearch
 2. using Update By Query API for updating doc
 3. many type of query

My JVM parameters of Elasticsearch:
-Xms=4g
-Xmx=4g 
-Xmn=1700m

before OOM, i using "jstat" (java command) :
![image](https://user-images.githubusercontent.com/8154045/28396340-49ef6524-6d2d-11e7-9889-732d830eebcf.png)

before OOM, i using "jmap -dump" (java command) dump JVM heap, then using MemoryAnalyzer analyzer result :
![es](https://user-images.githubusercontent.com/8154045/28396524-8cdc56e8-6d2e-11e7-994e-361b31130525.png)

The specific reason is not clear, personal suspicion is the reason：
After continued invoking Update By Query API , the groovy script cause OOM。

Thank for checking and answer.

**Comment by jasontedor** [comment]
We can not help without seeing the script. For example, it could be a simple case of a non-parameterized script so you are repeatedly compiling new scripts, a known source of leaks. Yet, we use GitHub as an issue tracker, not for general help. For that, we use the [forum](https://discuss.elastic.co). We can reopen this issue if there is a verified bug.

Also, the lifecycle of 2.x is winding down, and Groovy scripting is dead (removed in 6.0.0). If there is a bug here, there is no guarantee that we will address it. I tell you this for planning purposes, you should start thinking about migration paths.
