### ISSUE TITLE
Alternative to REST 'filter_path' option in TransportClient

### ISSUE THREAD

**Issue by Josca** [elastic/elasticsearch#25812]
Hi,

 I need to search in huge amount of indexed documents and get relevant documents names into client app. I suppose result will have about milions of documents. I need result to contain docs names only, not all content. I did it using filter_path feature via REST api. Is it possible implement it using Java TransportClient? I found no alternative to REST filter_path option when reading Java TransportClient documenation.

Thanks for any advice.

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
