### ISSUE TITLE
Indexing a value of "1.0" to byte field with coerce=true fails on 5.5.0

### ISSUE THREAD

**Issue by PaulieMac** [elastic/elasticsearch#25819]
**Elasticsearch version**:
"version" : {
    "number" : "5.5.0",
    "build_hash" : "260387d",
    "build_date" : "2017-06-30T23:16:05.735Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.0"
  }

**Plugins installed**: none

**JVM version** (`java -version`):
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

**Description of the problem including expected versus actual behavior**:

Attempting to index a value of "1.0" to byte field mapped with coerce=true fails with the following error: number_format_exception

**Steps to reproduce**:

curl -X PUT localhost:9200/testing -d '{ "mappings" : { "coerceme" : { "properties" : { "test" : { "type" : "byte", "coerce" : true}}}}}'

curl -X PUT localhost:9200/testing/coerceme/1 -d '{ "test" : "1.0" }'

Response:
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse [test]"}],"type":"mapper_parsing_exception","reason":"failed to parse [test]","caused_by":{"type":"number_format_exception","reason":"For input string: \"1.0\""}},"status":400}

**Comment by PaulieMac** [comment]
Note.. This behaves a little differently on older ES versions, but on 5.5 the following will succeed:

curl -X PUT localhost:9200/testing/coerceme/2 -d '{ "test" : 1.1 }'

curl -X PUT localhost:9200/testing/coerceme/3 -d '{ "test" : "1" }'

So it appears it will coerce a decimal, but only coerce a numeric string if it is a whole number with no decimal element.

**Comment by scottsom** [comment]
Oddly enough, I was just about to file this exact same bug report for integers.

Are you sure you saw this work on 5.4.1? I was able to reproduce this on both a 5.3.2 and 2.3.2 cluster.

From debugging it, this is where the exception is thrown:
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/common/xcontent/support/AbstractXContentParser.java#L156

So I am not sure this has ever worked, despite the documentation suggesting it should be able to coerce a value like "5.0" to an integer:
https://www.elastic.co/guide/en/elasticsearch/reference/current/coerce.html

**Comment by PaulieMac** [comment]
Ah, I was looking at this code:
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/mapper/NumberFieldMapper.java#L389-L405

That Byte.Parse() will throw something similar; in the case that value is a string, it seems to disregard coerce altogether?

I can ramp up my 5.4.1 instance again, but when (I thought) I saw it work, dynamic was not set to strict - so that may have had something to do with it?

**Comment by PaulieMac** [comment]
Just tried again on 5.4.1 and it failed regardless of the dynamic setting... Perhaps I made a typo or some other doofus error earlier. Have edited the issue to prevent (further) confusion :)

**Comment by jpountz** [comment]
Agreed it would be nice to fix it. I added labels accordingly.

**Comment by scottsom** [comment]
I can put together a fix for this.
