### ISSUE TITLE
Documentation on discovery.zen.ping.unicast.hosts

### ISSUE THREAD

**Issue by tomsommer** [elastic/elasticsearch#25810]
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-zen.html#unicast

The documentation around `discovery.zen.ping.unicast.hosts` doesn't specify what kind of hosts should be added. Is it all nodes? All master nodes? At least one master? Is there a recommended minimum?

There is no information as to when to update this list either or when the list of hosts are actually used (only at start? at any master election?).

Perhaps a link to https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#unicast.hosts and expand the explanation here?

**Comment by jasontedor** [comment]
> Is there a recommended minimum?

I tend to think we should recommend all master-eligible nodes.

**Comment by bleskes** [comment]
> I tend to think we should recommend all master-eligible nodes.

Agreed.

> There is no information as to when to update this list either or when the list of hosts are actually used (only at start? at any master election?).

Update it at any change to master eligible nodes, just in the case that a node is restart and looses the information it has over the live cluster.

@tomsommer care to make a doc PR?

**Comment by jasontedor** [comment]
I opened #25991 for this.
