### ISSUE TITLE
Using Java TransportClient for access to AWS ElasticSearch instance

### ISSUE THREAD

**Issue by Josca** [elastic/elasticsearch#25813]
Hi,

 Is it possible to use Java TransportClient when using AWS ElasticSearch instance and access token? Where can I find documentation for that, please?

Thanks for any advice.

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
