### ISSUE TITLE
Dynamic mapping false isn't working

### ISSUE THREAD

**Issue by rifferti** [elastic/elasticsearch#25825]
I'm using Elasticsearch version 5.5.0 and I'm experiencing problems regarding dynamic mapping. The configuration "False" isn't working like described here: https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic.html . I set the mapping for my type to false and I am still able to create new fields that aren't covered by my mapping.
I also experienced the same behavior using reindex.

index settings:
`{"settings": {
    "index": {
      "mapper": {
        "dynamic": false}}}}`

mapping: 
`{"foo": {
    "dynamic": "false",
    "properties": {
      "myField": {
        "type": "text"}}}}`

**Comment by colings86** [comment]
When you say you are still able to create new fields do you mean that after indexing a document with a new field you can see the new field in your mappings? The `false` option for the `dynamic` setting will still accept documents that have fields which are not in the mapping (i.e. it will not throw an error) but it will not index those fields so you won't be able to search those fields. When you GET the document you will however still see the new fields in the `_source` field as Elasticsearch does not modify the `_source` field. If you want an error to be thrown when you index a field that is not defined in the mappings you will need to use the `false` option.

Saying that, if you are saying that you are setting `"dynamic": "false"` and when indexing new fields they appear in the mapping, could you provide the steps (requests) you are going through from creating the index, indexing a document with an unknown field and seeing it appear in the mapping so we can try to reproduce your issue?

**Comment by rifferti** [comment]
Ah ok, I understood the false option in a different way. I thought the field would be ignored. Maybe the documentation should be a little bit more clear at this point. 
I understood it the way that when I use `"dynamic": "false"` and create documents with fields not covered by the mapping, those fields will be ignored (so they won't be stored) and wouldn't show up in `_source` when I GET the document.

So this issue can be closed.

**Comment by colings86** [comment]
@rifferti I agree that we could make this clearer in the docs so I'm going to reopen this issue until I've reworded the documentations. Thanks for raising this

**Comment by colings86** [comment]
@rifferti I opened https://github.com/elastic/elasticsearch/pull/25829 to fix the documentation.

**Comment by colings86** [comment]
documentation change merged into 5.5, 5.x and master

**Comment by etiennecallies** [comment]
> If you want an error to be thrown when you index a field that is not defined in the mappings you will need to use the `false` option.

typo: `strict` option
