### ISSUE TITLE
date range query performance

### ISSUE THREAD

**Issue by jgq2008303393** [elastic/elasticsearch#25821]
Hi.

  I am testing es to analysis user data. I load a day's data of 1 million users into es 5.0. The common query pattern is using date histogram aggregation to analysis one user's data. I encounter performance problem when using following query:
```
    POST /test/_cache/clear
    GET /test/_search
    {
      "size": 0,
      "query": {
        "bool": {
          "filter": [
            {
              "terms": {
                "user_id": [
                  "1095620139"
                ]
              }
            },
            {
              "range": {
                "timestamp": {
                  "gte": "2017-07-13T03:00:00Z",
                  "lt": "2017-07-13T04:00:00Z"
                }
              }
            }
          ]
        }
      },
      "aggs": {
        "result": {
          "date_histogram": {
            "field": "timestamp",
            "interval": "1m",
            "format": "yyyy-MM-dd HH:mm"
          },
          "aggs": {
            "max_of_field": {
              "max": {
                "field": "counter"
              }
            }
          }
        }
      }
    }
```
  It costs 200ms! 

  But when I remove time range filter as following, 
```
    POST /test/_cache/clear
    GET /test/_search
    {
      "size": 0,
      "query": {
        "bool": {
          "filter": [
            {
              "terms": {
                "user_id": [
                  "1095620139"
                ]
              }
            }
          ]
        }
      },
      "aggs": {
        "result": {
          "date_histogram": {
            "field": "timestamp",
            "interval": "1m",
            "format": "yyyy-MM-dd HH:mm"
          },
          "aggs": {
            "max_of_field": {
              "max": {
                "field": "counter"
              }
            }
          }
        }
      }
    }

```
  It only costs 20ms while processing a whole day's data! 

  I know the implement of the lucene AND processor which fetch documents that match the user_id and the time range separately, then perform set intersection. I think the performance problem is caused by the amount of documents that match the time range.

I think this is a common use case. How to solve this performance problem? 
Any helps would be appreciated!

**Comment by colings86** [comment]
Hi @user, we reserve Github for bug reports and feature requests only. We use the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) to answer questions such as this.  I see that you have already asked this question on the forums (https://discuss.elastic.co/t/combined-index-like-database-rdbms/93262/7) so lets keep the conversation there.
