### ISSUE TITLE
Inconsistent search results

### ISSUE THREAD

**Issue by adamvaughan** [elastic/elasticsearch#25836]
**Elasticsearch version**: 5.5.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_112

**OS version** (`uname -a` if on a Unix-like system): Darwin 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

We are storing email addresses and have noticed an issue when searching for one email address in particular. Changing the email address by a single digit or number makes it work.

**Steps to reproduce**:

I've created two scripts that demonstrate the issue. One shows the search that fails to return any results and the other shows the exact same process but changes the email address by one digit and returns results.

No results:
https://gist.github.com/adamvaughan/5fd1a8292b4190c189a10f607e593881

Works as expected:
https://gist.github.com/adamvaughan/c8ed335ddfc70139d14a69e5699e7fc4

**Comment by rjernst** [comment]
Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports.

You should not be using `keyword` analyzer for search; it should be the same analyzer at both index and search time. Your ngram configuration is the only thing causing the keyword to match anything at search time, and it is also what is preventing a single term from being produced for the longer email address.

**Comment by adamvaughan** [comment]
Thanks @rjernst! 👍
