### ISSUE TITLE
Index Migration Failure for Mapper Attachment after upgrading elasticsearch to 5.5.0 from 5.3.1 

### ISSUE THREAD

**Issue by frankliu81** [elastic/elasticsearch#25834]
[xOOEXQB-RzGhQp7o7NNH9w.zip](https://github.com/elastic/elasticsearch/files/1166429/xOOEXQB-RzGhQp7o7NNH9w.zip)

[elasticsearch_unable_to_upgrade_index.log.zip](https://github.com/elastic/elasticsearch/files/1166451/elasticsearch_unable_to_upgrade_index.log.zip)

**Elasticsearch version**:
5.5.0 (upgrading

 from 5.3.1 using homebrew on Mac El Capitan)

**Plugins installed**: []
Mapper Attachment plugin

**JVM version** (`java -version`):
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Darwin frank-liu-mbp15.local 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Install ElasticSearch 5.3.1 (I have installed with homebrew).  Install the mapper attachment plugin for document search.  Create the document index using the following snippet on a Document model in Rails and using the elasticsearch_rails gem.

```
class Document < ActiveRecord::Base
  mount_uploader :document_attachment, DocumentAttachmentUploader

  # elasticsearch-rails
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  settings index: { number_of_shards: 3 } do
   mappings do
     indexes :title
     indexes :attachment, type: 'attachment'
   end
  end

  def as_indexed_json(options={})
    self.as_json({
      methods: [:attachment]
    })
  end

  def attachment
    path_to_attachment = document_attachment.file.file
    Base64.encode64(open(path_to_attachment) { |file| file.read })
  end
end

Document.import(force: true)
```

 2. Install elasticsearch 5.5.0 (this was done on my machine via, homebrew upgrade elasticsearch)

 3. Start elasticsearch with 'elasticsearch'.  It is unable to start with:
Caused by: java.lang.IllegalStateException: unable to upgrade the mappings for the index [[documents/xOOEXQB-RzGhQp7o7NNH9w]] 

**Provide logs (if relevant)**:
The log for starting elasticsearch and the offending index folder from 
/usr/local/var/elasticsearch/nodes/0 are attached.

**Comment by imotov** [comment]
@frankliu81 Did you reinstall Mapper Attachment plugin after upgrading? Judging by the log file that you provided it doesn't look like it got picked up by elasticsearch:

```
[2017-07-19T16:34:13,748][INFO ][o.e.p.PluginsService     ] [cv_fM-W] no plugins loaded
```

**Comment by frankliu81** [comment]
@imotov, you are right, I didn't reinstall the mapper attachment plugin after upgrading.  Once I re-installed the plugin, then elasticsearch can start.  However, getting the `unable to upgrade the mapping for the index` was quite misleading, seems to indicate the plugin is fine, but the index was the issue.
