### ISSUE TITLE
_bulk upload causes OOM

### ISSUE THREAD

**Issue by truekonrads** [elastic/elasticsearch#25842]
**Elasticsearch version**:
elasticsearch-5.5.0 on Windows and also Amazon ES service running ES 5.3

**Plugins installed**: 
 - Kibana
- X-Pack on Windows 
- whatevcer Amazon ships with by default

**JVM version** (`java -version`):

java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Windows 7 / Amazon's magic OS

**Description of the problem including expected versus actual behavior**:
I was uploading 1.3G of JSON newline delimited data using logstash. Data is windows event logs parsed into fine fields. ES apparently can't keep up with writes and indexes, it keeps consuming more and more memory and then switches off indexing and eventually crashes dumps core. 

**Steps to reproduce**:
1.  Set up a new ES on a workstation-like computer - mine was a intel core i5-3320M with SSD; jvm had 4Gs of RAM
Generate a large-ish data set (800k documents) with dozen fields per JSON-ND record ( I can't share mine)
2. feed it in using logstash - minimal configuration is enough, just host stanza
3.  about 1/3 to 1/2 in you will see ES complaining about data pressure and eventually dumping core

**Provide logs (if relevant)**:

[logs.zip](https://github.com/elastic/elasticsearch/files/1167215/logs.zip)

**Comment by markharwood** [comment]
Looks like you start up with 253 indexes and only 2 gb of RAM.
There are a further 793 "create index" requests in the log file, each with 5 shards and many "update mapping" requests to add field definitions from dynamic templates.
I'm not surprised you have issues with such a configuration.

>I was uploading 1.3G of JSON

Try use less indexes and shards for what is a modest amount of content and available hardware.

**Comment by truekonrads** [comment]
Thank you Mark. I suppose I am more complaining about an unexpected behaviour in what would seem to be a common situation. 

The many indices are logstash's default action of creating one per day. It is reasonable for other users to run into this.
I don't think that application should run out of memory like that. I was able to repeat this with 4 gigs setup on Amazon's ES service as well with same results. In my view, the expected behavior would be to stop receiving messages until it is ready to consume more.
