### ISSUE TITLE
Installation of DEB inside docker container fails

### ISSUE THREAD

**Issue by monotek** [elastic/elasticsearch#25846]
**Elasticsearch version**: 5.5.0

**OS version** (`uname -a` if on a Unix-like system): Debian 8 (inside Docker)

**Description of the problem including expected versus actual behavior**:

Can't install Elasticsearch 5.5.0 inside Debian 8 Docker container (Version 5.4.3 works)

**Steps to reproduce**: 
* docker run -ti debian:8 bash
* apt-get update
* apt-get install wget
* wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
* echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-5.x.list
* apt-get update
* update-ca-certificates -f
* apt-get --no-install-recommends -y install elasticsearch

**Provide logs (if relevant)**:

[91m+ apt-get --no-install-recommends -y install elasticsearch
[0m
Reading package lists...

Building dependency tree...

Reading state information...

The following NEW packages will be installed:
  elasticsearch

0 upgraded, 1 newly installed, 0 to remove and 101 not upgraded.
Need to get 33.4 MB of archives.
After this operation, 37.3 MB of additional disk space will be used.
Get:1 https://artifacts.elastic.co/packages/5.x/apt/ stable/main elasticsearch all 5.5.0 [33.4 MB]

[91mdebconf: delaying package configuration, since apt-utils is not installed
[0m
Fetched 33.4 MB in 2s (14.9 MB/s)

Selecting previously unselected package elasticsearch.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 24421 files and directories currently installed.)
Preparing to unpack .../elasticsearch_5.5.0_all.deb ...

Creating elasticsearch group...
 OK

Creating elasticsearch user...
 OK

Unpacking elasticsearch (5.5.0) ...

Processing triggers for systemd (215-17+deb8u5) ...

Setting up elasticsearch (5.5.0) ...

Failed to get D-Bus connection: Unknown error -1

dpkg: error processing package elasticsearch (--configure):

 subprocess installed post-installation script returned error exit status 1
Processing triggers for systemd (215-17+deb8u5) ...

Errors were encountered while processing:
 elasticsearch

[91mE: Sub-process /usr/bin/dpkg returned an error code (1)
[0m
Removing intermediate container c5ea51ce8034

**Comment by jasontedor** [comment]
This is not an Elasticsearch issue, but an issue with systemd inside Docker containers. You should use the tar.gz instead.

**Comment by monotek** [comment]
True, but it worked in our automatic builds for ages. 
Just with 5.5.0 it stoped working so it seems something in the package changed too.
