### ISSUE TITLE
add support for euclidean point fields of arbitrary dimension (non-geo)

### ISSUE THREAD

**Issue by ehartford** [elastic/elasticsearch#25848]
**Describe the feature**:

Requesting multidimensional euclidean point support. (non-geo)

Lucene added support for [multidimensional points in 6.0](https://www.elastic.co/blog/lucene-points-6.0) and [range queries](https://lucene.apache.org/core/6_6_0/core/org/apache/lucene/document/DoublePoint.html#newRangeQuery-java.lang.String-double:A-double:A-) using k-d tree. 

I am requesting ES field datatypes to expose this feature.

**Comment by jpountz** [comment]
What is your use-case? What would you store in these points and how would you query them?

**Comment by ehartford** [comment]
use case is point clouds, games, simulations, mathematics experiments, finance, modeling.
This is not Geo.  It is not about lat longs, and not spherical geometry.   It is flat euclidean space.

the point is any dimension, for example a 4D data point would look like [1.5,-8,32.1,99] and query would look something like:

```
PUT /my_points
{
    "mappings": {
        "item": {
            "properties": {
                "coords": {
                    "type": "point"
                }
            }
        }
    }
}

PUT /my_points/item/1
{
    "coords" : [1.5,-8,32.1,99]
}
```

```
GET /_search
{
    "query": {
        "bool" : {
            "must" : {
                "match_all" : {}
            },
            "filter" : {
                "point_range" : {
                    "coords" : {
                        "top_left" : [0, 0, 0, 0],
                        "bottom_right" : [25, 25, 25, 25]
                    }
                }
            }
        }
    }
}
```

```
GET /_search
{
    "query": {
        "bool" : {
            "must" : {
                "match_all" : {}
            },
            "filter" : {
                "point_nearest_neighbors" : {
                    "coords" : {
                        "max_range": 12.4,
                        "max_neighbors" : 100
                    }
                }
            }
        }
    }
}
```

max_range and max_neighbors are both optional but you will need at least one of them or you will match every document.

**Comment by ehartford** [comment]
I should point out that Lucene doesn't support nearest neighbors search.  only range search.

but if it did, it would look like:

```
GET /_search
{
    "query": {
        "bool" : {
            "must" : {
                "match_all" : {}
            },
            "filter" : {
                "point_nearest_neighbors" : {
                    "coords" : {
                        "max_distance": 12.4,
                        "max_neighbors" : 100
                    }
                }
            }
        }
    }
}
```

max_distance and max_neighbors are both optional but you will need at least one of them or you will match every document.

**Comment by mikemccand** [comment]
In fact Lucene does support efficient nearest neighbor search using the KD tree (points) data structure: https://github.com/apache/lucene-solr/blob/master/lucene/sandbox/src/java/org/apache/lucene/document/NearestNeighbor.java

However, the distance metric is indeed hardwired for the lat/lon geo use case (haversin), and is not [easily] pluggable for simple euclidean distance.

That said, in the Lucene index the point values stored are plain N dimensional points; the distance metric is only used at query time.  So you could e.g. fork the `NearestNeighbor` impl and build an ES plugin based on that, and/or propose an improvement to the Lucene class to make the distance metric pluggable in `NearestNeighbor.java`.

**Comment by ehartford** [comment]
I looked into doing this a year ago, but I found another solution for my immediate problem (postgresql's cube plugin)
It would be sweet to have this available in ES though.  I'll look into it again.

**Comment by jtibshirani** [comment]
I'm going to update the label to `:Analytics/Geo`, as I think the geo team has been considering this use case. Also tagging @mayya-sharipova, as she has been working on nearest-neighbor queries for the new `dense_vector` and `sparse_vector` types.

**Comment by wchaparro** [comment]
Closing as not planned

**Comment by ehartford** [comment]
That's rough.  It wouldn't be a large change and it would enable a lot of scenarios, and the hard work is already done in Lucene it just needs to be exposed.  Nobody's curious about this?
