### ISSUE TITLE
Sum Buckets Aggregation does not work with Nested / Reverse Nested Aggregation

### ISSUE THREAD

**Issue by ggarciao** [elastic/elasticsearch#25845]
**Environment**
`FROM docker.elastic.co/elasticsearch/elasticsearch:5.4.1`

**Situation:**
We have an index mapping with a nested document. On this index:
-  We use a `terms aggregation` on the nested document (`nested aggregation` then `terms aggregation`).
- Then we use a reverse nested aggregation to go back to the root document (`nested aggregation` then `terms aggregation `then `reverse nested aggregation`)
- Back on the root document, we use a `max aggregation` (`nested aggregation` then `terms aggregation` then `reverse nested aggregation` then `max aggregation`)
- Then we use the `sum bucket aggregation` to sum all the max found on the previous buckets. (a sibling aggregation of the first `nested aggregation` with `buckets_path nested aggregation > terms aggregation > reverse nested aggregation > max aggregation`)

**Exceptions**
`org.elasticsearch.search.aggregations.bucket.nested.InternalNested cannot be cast to org.elasticsearch.search.aggregations.InternalMultiBucketAggregation`  

If you put the `sum buckets aggregation` as a sibling of the `reverse nested aggregation` you get:
`org.elasticsearch.search.aggregations.bucket.nested.InternalReverseNested cannot be cast to org.elasticsearch.search.aggregations.InternalMultiBucketAggregation`

**Some thoughts**
I'm not an expert of the internal implementation of elasticsearch, but I think that the problem here is that the sum bucket aggregation search for the multi bucket aggregation too soon. 

I think that the sum bucket aggregation should allow passing through any single bucket aggregation and executing the sum on a multi bucket aggregation.

I tried to think about having multi buckets aggregation in the `buckets_path` and I think it is conceptually possible if it is implemented as a reduce phase. (I haven't look at the source code, so, take it as a theoretical suggestion only)

**Comment by markharwood** [comment]
Sounds like a complex query :) 
Can you share the raw query JSON or a simplified form of it?

**Comment by colings86** [comment]
No Further feedback. If you have the raw json query to share please comment with it and we can reopen the issue

**Comment by lazycece** [comment]
> Sounds like a complex query :)
> Can you share the raw query JSON or a simplified form of it?

I also have the problem, the query json as following:
```json
{
  "size": 0, 
	"aggs": {
		"agg_date_histogram_voiceTime": {
			"date_histogram": {
				"field": "voiceTime",
				"format": "yyyy-MM-dd",
				"interval": "1w",
				"offset": 0,
				"order": {
					"_key": "asc"
				},
				"keyed": false,
				"min_doc_count": 0
			},
			"aggregations": {
				"agg_nested_ruleLabel": {
					"nested": {
						"path": "ruleLabel"
					},
					"aggregations": {
						"agg_terms_ruleLabel.ruleType.keyword": {
							"terms": {
								"field": "ruleLabel.ruleType.keyword",
								"size": 10,
								"min_doc_count": 1,
								"shard_min_doc_count": 0,
								"show_term_doc_count_error": false,
								"order": [
									{
										"_count": "desc"
									},
									{
										"_key": "asc"
									}
								]
							},
							"aggregations": {
								"reverse_nested": {
									"reverse_nested": {},
									"aggregations": {
										"agg_count": {
											"value_count": {
												"field": "taskId.keyword"
											}
										},
										"agg_cardinality_tel": {
											"cardinality": {
												"field": "tel.keyword"
											}
										},
										"agg_bucketScript": {
											"bucket_script": {
												"buckets_path": {
													"userCount": "agg_cardinality_tel",
													"docCount": "agg_count"
												},
												"script": {
													"source": "params.docCount / params.userCount",
													"lang": "painless"
												},
												"gap_policy": "skip"
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
```
