### ISSUE TITLE
BulkIndexByScrollResponse appearing in Java Delete API documentation post 5.3

### ISSUE THREAD

**Issue by Drewbie18** [elastic/elasticsearch#25867]
**Elasticsearch version**: 5.5.X, 5.4.X

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:

Going through the Java API documentation it appears that the reference to BulkIndexByScrollResponse 
was replaced in version 5.3 as part of the fix for issue  #23845. Where it was replaced with BulkByScrollResponse. Can be seen here: https://www.elastic.co/guide/en/elasticsearch/client/java-api/5.3/java-docs-delete-by-query.html

However the next versions of the docs don't appear to reflect this change: https://www.elastic.co/guide/en/elasticsearch/client/java-api/5.4/java-docs-delete-by-query.html

It caused me some confusion but I think it should be BulkByScrollResponse for 5.5.X and 5.4.X.

**Comment by talevy** [comment]
thank you for sharing this bug.

Looks like there was a port of the docs fix attempted here: https://github.com/elastic/elasticsearch/commit/d7969a02ce0c483ebdd954a131abea59304f0f00. It seems that commit fixed one example, but left the second example alone unintentionally.

does that sound right @nik9000?

**Comment by nik9000** [comment]
> does that sound right @nik9000?

Yes, I believe it is right.

**Comment by liketic** [comment]
@nik9000 This can be closed because I can't find `BulkIndexByScrollResponse ` in doc.

**Comment by nik9000** [comment]
Thanks for the ping! I'll close.
