### ISSUE TITLE
_cat/indices docs.count is different than <index>/_count

### ISSUE THREAD

**Issue by WisdomPill** [elastic/elasticsearch#25868]
Elasticsearch 5.4.1 on Elastic Cloud

I just discovered that _cat/indices docs.count is different than <index>/_count

I was reindexing some indexes for testing and i discovered that the count of documents that I got with the _cat API is different than the query API.

Here's my _cat/indices result

GET _cat/indices/bk-sensor-*,sensor-*?v&s=index&h=index,docs.count,docs.deleted
index                docs.count docs.deleted
bk-sensor-2017-05        314293            0
bk-sensor-2017-06        645792            0
bk-sensor-2017-07         84515            0
bk-sensor-2017-07-05      21966            0
bk-sensor-2017-07-06      21890            0
bk-sensor-2017-07-07      20611            0
bk-sensor-2017-07-08      20642            0
bk-sensor-2017-07-09      20504            0
bk-sensor-2017-07-10      20533            0
bk-sensor-2017-07-11      20538            0
bk-sensor-2017-07-12      20604            0
bk-sensor-2017-07-13      20513            0
bk-sensor-2017-07-14      20507            0
bk-sensor-2017-07-15      20500            0
bk-sensor-2017-07-16      20511            0
bk-sensor-2017-07-17      20718            0
bk-sensor-2017-07-18      21381            0
bk-sensor-2017-07-19      20516            0
bk-sensor-2017-07-20      20504            0
bk-sensor-2017-07-21      20492            0
bk-sensor-2017-07-22      20532            0
bk-sensor-2017-07-23      20504            0
bk-sensor-2017-07-24      16346            0
sensor-2017-05           314293            0
sensor-2017-06           713339            0
sensor-2017-07            93163            0
sensor-2017-07-05         23466            0
sensor-2017-07-06         23190            0
sensor-2017-07-07         23859            0
sensor-2017-07-08         24619            0
sensor-2017-07-09         23395            0
sensor-2017-07-10         23934            0
sensor-2017-07-11         25338            0
sensor-2017-07-12         24635            0
sensor-2017-07-13         23461            0
sensor-2017-07-14         24180            0
sensor-2017-07-15         25831            0
sensor-2017-07-16         25182            0
sensor-2017-07-17         24616            0
sensor-2017-07-18         23231            0
sensor-2017-07-19         23416            0
sensor-2017-07-20         27493            0
sensor-2017-07-21         27713            0
sensor-2017-07-22         24833            0
sensor-2017-07-23         25039            0
sensor-2017-07-24         21043            0

Actually running the count query against every sensor-* gives me a different count than docs.count qith the _cat API. It gives me exactly the same number of docs that my bk-sensor-* indices have.

I think that this may be due to the operations that I do every night on my indices.
Every night I run a curator script that reindexes the index older than 20 days in a monthly index, I delete it and I merge the segments of all the indices that are from the day before and have more than one segment.

If it helps I could provide the index mapping.

I tried to run refresh on an index with the odd number of document but it didn't solve anything.

How can I get the right number of documents through the _cat API?

**Comment by talevy** [comment]
What is the difference between `bk-sensor-*` and `sensor-*`. why do you think you see consistency in one and not the other?

Also, do you see any errors in your re-index operation that may account for any potential failed index operations?

What number do you see when you run a `_count` query?

**Comment by WisdomPill** [comment]
There's no diffecrence except for the mapping that has been set through a template for sensor-* and not for bk-sensor-*. Also there's no error in the reindex operation.
Here's _count query result and _cat/indices result for index sensor-2017-06

GET _cat/indices/sensor-2017-06?v&s=index&h=index,docs.count,docs.deleted

index          docs.count docs.deleted
sensor-2017-06     713339            0

GET sensor-2017-06/_count

{
  "count": 645792,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  }
}

I'm sure I'm not indexing new data in the index since I choose the index using utc time now.

**Comment by javanna** [comment]
There are differences between cat api and count api. The former looks at lucene stats, while the latter executes a query. Lucene stats take into account deleted document, as well as nested documents, which are both hidden in the search count. Are you by any chance using nested docs?

**Comment by WisdomPill** [comment]
Yes I am

**Comment by javanna** [comment]
I do not know, that doesn't sound right. Though this doesn't seem like a bug. I would move this discussion to our [forums](https://discuss.elastic.co/), as we reserve github issue for verified bug reports and feature requests.
