### ISSUE TITLE
Create Index allows unknown fields

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#25869]
I ran this against a recent snapshot of Elasticsearch 6.0. I was surprised that it silently accepted `setting` instead of `settings`, which was only obvious because my index had the default number of shards:

```http
PUT /test-index
{
  "setting": {
    "number_of_shards": 1
  },
  "mappings": {
    "doc": {
      "properties": {
        "location": {
          "type": "geo_shape"
        },
        "geo": {
          "type": "geo_point"
        }
      }
    }
  }
}
```

**Comment by olcbean** [comment]
@pickypg the issue seems to be a duplicate of #23755. There is also an open PR for it : #23869.

**Comment by pickypg** [comment]
Dupe of #23755 indeed. Thanks @olcbean.
