### ISSUE TITLE
AbstractXContentParser - logger is not static

### ISSUE THREAD

**Issue by prog8** [elastic/elasticsearch#25879]
Elasticsearch 5.5.0
I realized that logger in AbstractXContentParser is not static. This causes a lot of new logger instantiations

```
    private final DeprecationLogger deprecationLogger = new DeprecationLogger(Loggers.getLogger(getClass()));
```

This is unfortunately very expensive when I have a script which looks into _source to extract value from it. It seems this logger is instantiated for each document which has very significant impact on performance. See below. Many threads are hanging on "sun.reflect.Reflection.getCallerClass(Native Method)"

```       java.lang.Thread.State: RUNNABLE
            at sun.reflect.Reflection.getCallerClass(Native Method)
            at java.lang.Class.newInstance(Class.java:397)
            at org.apache.logging.log4j.spi.AbstractLogger.createDefaultMessageFactory(AbstractLogger.java:212)
            at org.apache.logging.log4j.spi.AbstractLogger.<init>(AbstractLogger.java:128)
            at org.apache.logging.log4j.spi.ExtendedLoggerWrapper.<init>(ExtendedLoggerWrapper.java:44)
            at org.elasticsearch.common.logging.PrefixLogger.<init>(PrefixLogger.java:46)
            at org.elasticsearch.common.logging.ESLoggerFactory.getLogger(ESLoggerFactory.java:53)
            at org.elasticsearch.common.logging.ESLoggerFactory.getLogger(ESLoggerFactory.java:49)
            at org.elasticsearch.common.logging.ESLoggerFactory.getLogger(ESLoggerFactory.java:57)
            at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:101)
```

Can this logger be as static one?

**Comment by colings86** [comment]
I think the reason this is not static is that we want to use the class name of the concrete class for the logger name instead of creating a logger for the `AbstractXContentParser` itself. I see that @danielmitterdorfer added this deprecation logging so maybe he has an opinion on whether we need to have the class name of the concrete class here or if creating a logger for `AbstractXContentParser` would be ok so the logger can be static?

**Comment by prog8** [comment]
Alternatively, it is possible to instantiate depreciation logger in the same way it is done in some part of  org.elasticsearch.common.settings. This is done conditionally only if depreciation has been detected.

```
    protected void checkDeprecation(Settings settings) {
        // They're using the setting, so we need to tell them to stop
        if (this.isDeprecated() && this.exists(settings) && settings.addDeprecatedSetting(this)) {
            // It would be convenient to show its replacement key, but replacement is often not so simple
            final DeprecationLogger deprecationLogger = new DeprecationLogger(Loggers.getLogger(getClass()));
            deprecationLogger.deprecated("[{}] setting was deprecated in Elasticsearch and will be removed in a future release! " +
                "See the breaking changes documentation for the next major version.", getKey());
        }
    }
```

Notice that in `AbstractXContentParser` `deprecationLogger` is used only in one place and in most cases the condition will not be matched so instantiating `deprecationLogger` on each `AbstractXContentParser` instantiation seems to be redundant and can hurt performance significantly.

```        if (interpretedAsLenient) {
            deprecationLogger.deprecated("Expected a boolean [true/false] for property [{}] but got [{}]", currentName(), rawValue);
        }
```

**Comment by danielmitterdorfer** [comment]
@colings86 Yes, the original motivation was to have the concrete class name to narrow the focus. But given the performance impact + the fact that there are only four implementations (JSON, CBOR, Smile and Yaml) I think the pragmatic choice is to just use a static instance here?

**Comment by danielmitterdorfer** [comment]
Seems it did not auto-close. Closed by #25881.

**Comment by jasontedor** [comment]
We really need to be more careful when we make something static, especially for a class that is so fundamental. The issue here is that merely constructing a list setting (e.g., the setting object for `path.data`) causes a JSON content parser to be initialized which causes this static initializer to run which touches logging. This will happen *before* logging is even configured and that's a no-no.

**Comment by jasontedor** [comment]
For this I opened #26210.
