### ISSUE TITLE
Remove `--path.conf` from bin/elasticsearch help text

### ISSUE THREAD

**Issue by spalger** [elastic/elasticsearch#25871]
#25815 removed support for `--path.conf` from the command line, but the argument is still listed in the help text and consumed when run.

Extra credit: can we make the error message when using `--path.conf` match the error message of other unrecognized flags?

Current: `Found multiple arguments for option c/path.conf, but you asked for only one`
Ideal:  `path.conf is not a recognized option`

original issue text:

---
**Elasticsearch version**: master
**Plugins installed**: none
**JVM version**: `1.8.0_121-b13`
**OS version**: macOS
**Description of the problem including expected versus actual behavior**:

calling `bin/elasticsearch --path.conf=...` with anything causes an error to be logged:

```sh
elasticsearch-6.0.0-beta1-SNAPSHOT  $ ./bin/elasticsearch --path.conf=...
Option                Description
------                -----------
-E <KeyValuePair>     Configure a setting
-V, --version         Prints elasticsearch version information and exits
-c, --path.conf       Configure config path
-d, --daemonize       Starts Elasticsearch in the background
-h, --help            show help
-p, --pidfile <Path>  Creates a pid file in the specified path on start
-q, --quiet           Turns off standard ouput/error streams logging in console
-s, --silent          show minimal output
-v, --verbose         show verbose output
ERROR: Found multiple arguments for option c/path.conf, but you asked for only one
```

**Comment by dakrone** [comment]
@spalger it is a follow-up that we are removing the `--path.config` option, see: https://github.com/elastic/elasticsearch/pull/25815/#issuecomment-316841627

**Comment by spalger** [comment]
Ah, okay, updated the issue title and description. The labels probably need an update too?

**Comment by jasontedor** [comment]
This is known issue and one we decided was okay to maybe ship a beta with but fix before GA. A related issue is that --help for multi-commands (e.g., `elasticsearch-keystore) doesn't work. Both have the same underlying chase and I will fix soon.

**Comment by jasontedor** [comment]
Closed by #25943

**Comment by Bargs** [comment]
I'm confused, what's the proper way to set a custom configuration path now? Perhaps I'm being dense, but I've followed the trail of PRs and looked at the docs and I can't figure it out.

**Comment by chrisronline** [comment]
I'm fairly sure it's an env variable now `CONF_DIR`. See [spencer's changes for libesvm](https://github.com/elastic/libesvm/commit/576af62c4861eb9ba586f87aa0abc6ea980d25d7)

**Comment by Bargs** [comment]
I tried setting `CONF_DIR` with no success :/

**Comment by chrisronline** [comment]
Hmm. Seems to work fine for me:

```
elasticsearch-6.0.0-beta1-SNAPSHOT chris$ ls -la /Users/chris/test
total 8
drwxr-xr-x   5 chris  staff   170 Jul 31 14:06 .
drwxr-xr-x+ 37 chris  staff  1258 Jul 31 14:05 ..
-rw-r--r--   1 chris  staff     0 Jul 31 14:06 elasticsearch.yml
-rw-r--r--   1 chris  staff  2758 Jul 31 14:10 jvm.options
-rw-r--r--   1 chris  staff     0 Jul 31 14:06 log4j2.properties
elasticsearch-6.0.0-beta1-SNAPSHOT chris$ CONF_DIR=/Users/chris/test ./bin/elasticsearch
```

**Comment by jasontedor** [comment]
@Bargs Can you explain the issue you're having with `CONF_DIR` or give a reproduction? If there is a doc issue here that needs addesssing please let me know.

**Comment by Bargs** [comment]
I must not have had enough coffee this morning, I just re-tried `CONF_DIR` and it's working.

@jasontedor the docs in the "Set up Elasticsearch" section still suggest using `--path.conf` https://www.elastic.co/guide/en/elasticsearch/reference/master/settings.html#_config_file_location

**Comment by jasontedor** [comment]
Thanks, I'll fix the docs right away!

**Comment by jasontedor** [comment]
@Bargs I opened #25990.

**Comment by Bargs** [comment]
Awesome, that looks much better. Thank you!
