### ISSUE TITLE
Getting Null Pointer in elastic search 5.4 when setting up the cluster with more than 2 data nodes

### ISSUE THREAD

**Issue by nitishgoyal13** [elastic/elasticsearch#25883]
{
"timeTakenMillis": 58,
"successfulShards": 4,
"failedReasons": [
  "BroadcastShardOperationFailedException[]; nested: SendRequestTransportException[[es-data-nqa-spr_nqa_elasticsearch-5.4-1-2-1d][xxxx][indices:data/read/pipeline[s]]]; nested: NullPointerException; ",
  "BroadcastShardOperationFailedException[]; nested: SendRequestTransportException[[es-data-nqa-spr_nqa_elasticsearch-5.4-1-2-1d][xxxx][indices:data/read/pipeline[s]]]; nested: NullPointerException; ",
  "BroadcastShardOperationFailedException[]; nested: SendRequestTransportException[[es-data-nqa-spr_nqa_elasticsearch-5.4-1-2-1d][xxxx][indices:data/read/pipeline[s]]]; nested: NullPointerException; ",
  "BroadcastShardOperationFailedException[]; nested: SendRequestTransportException[[es-data-nqa-spr_nqa_elasticsearch-5.4-1-2-1d][xxxx][indices:data/read/pipeline[s]]]; nested: NullPointerException; "
],
"failedShards": 4,
"result": {
"headers": [],
"rows": [],
"totalCount": 0
}
}

**Comment by tlrx** [comment]
Can you please provide the logs for both elasticsearch nodes? We need them to see where the NPE occurs.

**Comment by nitishgoyal13** [comment]
There is nothing in the logs for this NPE. I checked the logs everywhere and there are no logs at all

**Comment by yeikel** [comment]
Can you recreate it?

**Comment by tlrx** [comment]
No feedback provided, I'm closing this issue.
