### ISSUE TITLE
"[script] unknown field [source], parser not found" - Painless - issue during update

### ISSUE THREAD

**Issue by SKumarMN** [elastic/elasticsearch#25898]
**Elasticsearch version**: 5.5 

**Plugins installed**: [ None]

**JVM version** (`JDK1.8.131`):

**OS version** (`uname -a` if on a Unix-like system): Windows

Unable to update the document using source in painless

**Steps to reproduce**:

 1. Create a document 

```
PUT/hockey/player/1
 {"first":"johnny","last":"gaudreau"}
```

 2. Try to update the last name as shown below
   ```

POST /hockey/player/1/_update
   {
  "script": {
    "lang": "painless",
    "source": "ctx._source.last = params.last",
    "params": {
      "last": "hockey"
    }
  }
}
```
 

**Provide logs (if relevant)**:
```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "[script] unknown field [source], parser not found"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "[script] unknown field [source], parser not found"
    },
    "status": 400
}

```

Also if this is a bug then one more doc bug needs to be created for this page  https://www.elastic.co/guide/en/elasticsearch/painless/current/painless-examples.html#_updating_fields_with_painless too

**Comment by s1monw** [comment]
for questions like this please use the forum at discuss.elastic.co - your request is wrong, and the documentation you linked seems to have it right. try:

```

POST /hockey/player/1/_update
{
"script": {
 "lang": "painless",
 "inline": "ctx._source.last = params.last",
 "params": {
   "last": "hockey"
 }
}
}
```

instead

**Comment by SKumarMN** [comment]
@s1monw  Yes it's my bad for missing the detail. Thanks though
