### ISSUE TITLE
Elasticsearch array sequence query

### ISSUE THREAD

**Issue by fanfever** [elastic/elasticsearch#25895]
I'm have a field is a integer array like

[1,2,3]
I want to sequence terms like prefix query e.g.

[1,2] yes
[2,1] no
[1,3] no
[1] yes
plz, how to realize this

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
