### ISSUE TITLE
Improve circuit breaker debugging

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#25891]
Circuit breakers are very powerful, but they are also very dangerous, if we get
the accounting wrong we can end up in a "leak" situation where even if we don't
leak real memory, we reject requests based on incorrect accounting.

We had a bug in the past where if the client disconnected prior to the response
being sent then the bytes allocated in the circuit breaker would not be
released.

We have three circuit breakers, `fielddata`, `request`, and `inflight_requests`
(this does not count the script complication and `total` breakers). The
`fielddata` circuit breaker is "safe" due to its static context, but the other
two can be perilous to debug.

We would like to have a better way to debug breakers, so that we can increase
their usefulness and use them in more places. To that effect, we should add
better debugging features, some of our ideas include:

- Adding a "key" when the breaker is incremented and decremented, this can be
  unique to a particular context so that we can tell what impact a particular
  request had on the breaker (something like a session-id the breaker op is
  associated with). Simon brought up that we might want to do the same thing
  with our `RefCounted` implementation, such that we can see where the
  increments/decrements are coming from
- Perhaps a debugging mode for the breaker where we can track the "keys" added
  and removed from the breaker so that we can assert that we don't double-add or
  remove unadded bytes from the breaker
- Wrap the exceptions with as much information as possible, we currently only
  capture the message, bytes wanted, and byte limit in a
  `CircuitBreakingException`, but we may be able to add more contextual
  information to these exceptions so that it's easier to debug from the
  response.

**Comment by tbrooks8** [comment]
I'm not sure where we are on this. I think based upon the discussion from the PR I produced we are mainly interested in possibly adding additional assertions in testing. In particular I think we would like to assert in our integration tests that circuit breakers are back to 0 at the end of a test. Simon describes this [here](https://github.com/elastic/elasticsearch/pull/26067#issuecomment-323684041).

**Comment by rjernst** [comment]
As described in https://github.com/elastic/elasticsearch/pull/26067#issuecomment-323404144, we already have some level of checking tests are back to 0. It isn't through as wrapper, but it has been good enough for the last several years this issue has sat idle. I'm going to close this as there are no plans to work on this and what we have has worked well enough. We can always open a new issue if a new need for better debugging arises.
