### ISSUE TITLE
Refresh interval call is sync or asnyc in elasticsearch

### ISSUE THREAD

**Issue by krishnaraj221193** [elastic/elasticsearch#25903]
Hello,

I am working on elastic search recently we wanted to know how to refresh inerval works 
lets say refresh interval in 1s
 > Will it send refresh call every 1s
or
> Will it call once previous refresh call is complete

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
