### ISSUE TITLE
Convert processor fails to convert float to integer

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#25917]
```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "convert": {
          "field": "foo",
          "type": "integer"
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "foo": "33.3"
      }
    }
  ]
}
```

Throws `number_format_exception`

Could we provide an option to truncate or round ?

Is any code base or behaviour shared with [coerce](https://github.com/elastic/elasticsearch/pull/25835)?

**Comment by jpountz** [comment]
I'd rather like users to use a script processor and make the conversion explicit:

```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "script": {
          "source": " ctx.foo = (int) Math.floor(Double.parseDouble(ctx.foo))"
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "foo": "33.3"
      }
    }
  ]
}
```

Truncation and rounding are trappy... what if the double value is out of long range for instance? Should we fail or return Long.MAX_VALUE? By requiring users to use a script, then they can do whatever they want using functions whose behaviour is well known and documented.

**Comment by nik9000** [comment]
I talked with a small group about this and we all agreed with @jpountz. I know scripting is a lot more difficult then something declarative, but the advantage of scripting is that it is super explicit. @jpountz's solution uses `floor` but you could use `ceil` or `round`. So, at least for now, I'm going to close this and recommend @jpountz solution.
