### ISSUE TITLE
fieldLength not an integer

### ISSUE THREAD

**Issue by mimitsu** [elastic/elasticsearch#25916]
**Elasticsearch version**: 5.4.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_131

> java version "1.8.0_131"
> Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): macOS Sierra 10.12.5

> Darwin Mimis-MacBook-Pro.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:
`fieldLength` is a count so it should be a (nonneg) integer. One possibility for unexpected behavior is that ES encodes the 32-bit integer as an 8-bit integer, then decodes back to 32-bit when used. Have not tested to confirm.

https://stackoverflow.com/questions/22194920/how-is-field-length-defined-in-solr-lucene

However, `avgFieldLength` *IS* an integer -- always (as far as I can tell).

One consequence of this is that the `tfNorm` (which is where `fieldLength` is being used) is influenced.

If, as in the stupid example below, there is just one document in one shard, one might expect either: (a) the same `_score` for both documents (which is what happens when `fieldLength` = `avgFieldLength`) or (b) the `_score` be greater for documents with shorter `fieldLength` (which would happen if the two documents were in the same shard). Instead the document with longer `fieldLength` wins out because of the strange `fieldLength`.

Is this a bug or feature?

**Steps to reproduce**:

```
DELETE m

PUT m/d/2
{
  "a":"one two"
}
PUT m/d/5
{
  "a":"one two three four five"
}
GET m/_search
{
  "explain": true, 
  "query": {
    "match": {
      "a": "one"
    }
  }
}
```

returns

```
    "hits": [
      {
        "_shard": "[m][1]",
        "_node": "pZzmcT7gRhaS6mZID5S0Lg",
        "_index": "m",
        "_type": "d",
        "_id": "5",
        "_score": 0.2824934,
        "_source": {
          "a": "one two three four five"
        },
        "_explanation": {
...
                    {
                      "value": 5.2244897,
                      "description": "fieldLength",
                      "details": []
                    }
...
      {
        "_shard": "[m][2]",
        "_node": "pZzmcT7gRhaS6mZID5S0Lg",
        "_index": "m",
        "_type": "d",
        "_id": "2",
        "_score": 0.25811607,
        "_source": {
          "a": "one two"
        },
        "_explanation": {
...
                    {
                      "value": 2.56,
                      "description": "fieldLength",
                      "details": []
                    }
```

**Comment by jpountz** [comment]
> One possibility for unexpected behavior is that ES encodes the 32-bit integer as an 8-bit integer, then decodes back to 32-bit when used. Have not tested to confirm.

Indeed this is related.

Lucene has historically been using an implementation of TF-IDF that used `1/sqrt(length)` as a length normalization factor. It actually encoded the norm in the index instead of the length, using only 8 bits in order to save space.  Later we made it possible to have more similarities and most of them used different length normalization factors but we wanted them to be index-time compatible with what was the default at that time, so the lenth that they see is `1/norm^2`, which is almost never an integer. In the case of your `one two` document, the length was 2, so the length norm was `1/sqrt(2)~=0.707`, which in-turn was rounded to 0.625 because of 8-bits quantization. This is why you see a length that is equal to `1/0.625^2=2.56`.

This is something that is changing in Lucene 7 (Elasticsearch 6). Our default similarity has been BM25 since Lucene 6 and we also removed support for index-time boosts so we decided to make `norms` store the length of documents (still quantized on 8 bits) instead of a precomputed length normalization factor (see https://issues.apache.org/jira/browse/LUCENE-7730). So as of Elasticsearch 6, the `fieldLength` field will give you an integer.

`avgFieldLength` is not computed based on `fieldLength` but by dividing the total number of occurrences of terms in the field by the number of documents that have a value for the field, which are both recorded by the inverted index. It could be a floating-point number, I believe the fact it was always an integer in your testing was a coincidence.

There are many bad things that happen with scoring when shards do not have enough data for index stats to be similar on all shards, but I understand it can be surprising.

I'm closing this issue since the problem will be addressed in 6.0. For the record, here is the output of your script on 6.0:

```
{
  "took": 17,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": 0.2876821,
    "hits": [
      {
        "_shard": "[m][1]",
        "_node": "6ZJpASksSfmwFmAprivJgA",
        "_index": "m",
        "_type": "d",
        "_id": "5",
        "_score": 0.2876821,
        "_source": {
          "a": "one two three four five"
        },
        "_explanation": {
          "value": 0.2876821,
          "description": "weight(a:one in 0) [PerFieldSimilarity], result of:",
          "details": [
            {
              "value": 0.2876821,
              "description": "score(doc=0,freq=1.0 = termFreq=1.0\n), product of:",
              "details": [
                {
                  "value": 0.2876821,
                  "description": "idf, computed as log(1 + (docCount - docFreq + 0.5) / (docFreq + 0.5)) from:",
                  "details": [
                    {
                      "value": 1,
                      "description": "docFreq",
                      "details": []
                    },
                    {
                      "value": 1,
                      "description": "docCount",
                      "details": []
                    }
                  ]
                },
                {
                  "value": 1,
                  "description": "tfNorm, computed as (freq * (k1 + 1)) / (freq + k1 * (1 - b + b * fieldLength / avgFieldLength)) from:",
                  "details": [
                    {
                      "value": 1,
                      "description": "termFreq=1.0",
                      "details": []
                    },
                    {
                      "value": 1.2,
                      "description": "parameter k1",
                      "details": []
                    },
                    {
                      "value": 0.75,
                      "description": "parameter b",
                      "details": []
                    },
                    {
                      "value": 5,
                      "description": "avgFieldLength",
                      "details": []
                    },
                    {
                      "value": 5,
                      "description": "fieldLength",
                      "details": []
                    }
                  ]
                }
              ]
            }
          ]
        }
      },
      {
        "_shard": "[m][2]",
        "_node": "6ZJpASksSfmwFmAprivJgA",
        "_index": "m",
        "_type": "d",
        "_id": "2",
        "_score": 0.2876821,
        "_source": {
          "a": "one two"
        },
        "_explanation": {
          "value": 0.2876821,
          "description": "weight(a:one in 0) [PerFieldSimilarity], result of:",
          "details": [
            {
              "value": 0.2876821,
              "description": "score(doc=0,freq=1.0 = termFreq=1.0\n), product of:",
              "details": [
                {
                  "value": 0.2876821,
                  "description": "idf, computed as log(1 + (docCount - docFreq + 0.5) / (docFreq + 0.5)) from:",
                  "details": [
                    {
                      "value": 1,
                      "description": "docFreq",
                      "details": []
                    },
                    {
                      "value": 1,
                      "description": "docCount",
                      "details": []
                    }
                  ]
                },
                {
                  "value": 1,
                  "description": "tfNorm, computed as (freq * (k1 + 1)) / (freq + k1 * (1 - b + b * fieldLength / avgFieldLength)) from:",
                  "details": [
                    {
                      "value": 1,
                      "description": "termFreq=1.0",
                      "details": []
                    },
                    {
                      "value": 1.2,
                      "description": "parameter k1",
                      "details": []
                    },
                    {
                      "value": 0.75,
                      "description": "parameter b",
                      "details": []
                    },
                    {
                      "value": 2,
                      "description": "avgFieldLength",
                      "details": []
                    },
                    {
                      "value": 2,
                      "description": "fieldLength",
                      "details": []
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    ]
  }
}
```
