### ISSUE TITLE
date_histogram and offset / interval

### ISSUE THREAD

**Issue by marsu-p** [elastic/elasticsearch#25912]
**Elasticsearch version**: 
Server: 2.2.0
API: 5.4

**Plugins installed**: []

**JVM version** (`java -version`): 
1.8.0_74

**OS version** (`uname -a` if on a Unix-like system): 
LFS

**Description of the problem including expected versus actual behavior**:

According to:
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-aggregations-bucket-datehistogram-aggregation.html#_offset

Interval and Offset accept TimeValues as defined here:
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/common-options.html#time-units

With ES 5.x, offset and interval can also take an integer, but not with ES 2.2. This leads to errors of the form:
`Unknown key for a VALUE_NUMBER in [requestsPerTime]: [interval]`
`Unknown key for a VALUE_NUMBER in [requestsPerTime]: [offset]`
DateHistogramParser.java sets in every case an interval and offset in millis, even if it is not set.

**Steps to reproduce**:

1. preparing the data:
```
PUT myindex
{
    "mappings":{
        "mymapping":{
            "properties":{
                "@version":{
                    "type":"string",
                    "index":"no"
                },
                "@timestamp":{
                    "type":"date"
                },
                "log_timestamp":{
                    "type":"date"
                }
            }
        }
    }
}
PUT myindex/mymapping/1
{
    "log_timestamp" : "2017-07-26T13:55:00Z"

}
PUT myindex/mymapping/2
{
    "log_timestamp" : "2017-07-26T15:25:00Z"
}
PUT myindex/mymapping/3
{
    "log_timestamp" : "2017-07-26T15:00:00Z"
}
```

2. java code:
```
AggregationBuilder timeRangeAggregation = AggregationBuilders.dateHistogram("entriesPerTime").field("log_timestamp")
        .interval("2h");
```
3. resulting query:
```
  "aggregations": {
    "entriesPerTime": {
      "date_histogram": {
        "field": "log_timestamp",
        "interval": 7200000,
        "offset": 0,
        "order": {
          "_key": "asc"
        },
        "keyed": false
      }
    }
  }
```
`offset` is obsolete and `interval` does not match the specification, thus the query does not work on ES 2.2 server.

**Provide logs (if relevant)**:

**Comment by danielmitterdorfer** [comment]
Hi @marsu-p. I don't understand why you are talking about two different versions of Elasticsearch  (2.2 and 5.4 + in the docs you refer to 5.5). The version numbers of (transport) client and server always need to match and API calls that work with one major version do not necessarily work with another one. 

We also reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!
