### ISSUE TITLE
Implement `getMutateFunction` in all `AbstractWireSerializingTestCase` and `AbstractStreamableTestCase` subclasses

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#25929]
https://github.com/elastic/elasticsearch/pull/25910 changed `AbstractWireSerializingTestCase` and `AbstractStreamableTestCase` to add a `getMutateFunction` method that is used when testing `hashCode` and `equals` to ensure that changing properties on the test instance makes it not equal to the original. At present this method defaults to returning `null` which disables the inequality checks (the equality checks are still run). 

We should make `getMutateFunction` abstract so we force all subclasses to implement this method and so improve test coverage. Before we can do that we need to implement the method for the ~90 classes that already extend `AbstractWireSerializingTestCase` and `AbstractStreamableTestCase`. This issue serves to track the implementation of the method on those classes.

### Subclasses of `AbstractWireSerializingTestCase`:

* [x] FieldCapabilitiesTests (#25999)
* [x] ScriptMetaDataTests (#25999)
* [x] StoredScriptSourceTests (#25999)
* [x] StoredScriptTests (#26094)
* [x] InternalOrderTests (#26094)
* [x] InternalAdjacencyMatrixTests (#26094)
* [x] InternalFiltersTests (#25999)
* [x] InternalFilterTests (#25999)
* [x] InternalGeoHashGridTests (#26056)
* [x] InternalGlobalTests (#25999)
* [x] InternalDateHistogramTests (#26056)
* [x] InternalHistogramTests (#26056)
* [x] InternalMissingTests (#25999)
* [x] InternalNestedTests (#25999)
* [x] InternalReverseNestedTests (#25999)
* [x] InternalBinaryRangeTests (#26094)
* [x] InternalDateRangeTests (#26094)
* [x] InternalGeoDistanceTests (#26094)
* [x] InternalRangeTests (#26094)
* [x] InternalSamplerTests (#25999)
* [x] SignificantLongTermsTests (#26094)
* [x] SignificantStringTermsTests (#26094)
* [x] DoubleTermsTests (#26094)
* [x] LongTermsTests (#26094)
* [x] StringTermsTests (#26094)
* [x] InternalExtendedStatsTests (#26056)
* [x] InternalMaxTests (#26056)
* [x] InternalStatsTests (#26056)
* [x] InternalAvgTests (#26056)
* [x] InternalCardinalityTests (#26056)
* [x] InternalGeoBoundsTests (#26056)
* [x] InternalGeoCentroidTests (#26056)
* [x] InternalMinTests (#26056)
* [x] InternalHDRPercentilesRanksTests (#26056)
* [x] InternalHDRPercentilesTests (#26056)
* [x] InternalTDigestPercentilesRanksTests (#26056)
* [x] InternalTDigestPercentilesTests (#26056)
* [x] InternalScriptedMetricTests (#26056)
* [x] InternalSumTests (#26056)
* [x] InternalTopHitsTests (#26056)
* [x] InternalValueCountTests (#26056)
* [x] InternalSimpleValueTests (#26058)
* [x] InternalBucketMetricValueTests (#26058)
* [x] InternalPercentilesBucketTests (#26058)
* [x] InternalDerivativeTests (#26058)
* [x] CollapseBuilderTests (#25999)
* [x] RepositoriesMetaDataSerializationTests (#25999)
* [x] SnapshotsInProgressSerializationTests (#25999)
* [x] InternalMatrixStatsTests (#25999)
* [x] InternalChildrenTests (#25999)

### Subclasses of `AbstractStreamableTestCase`:

* [x] RefreshStatsTests (#25999)

### Cleanup

* [ ] Make `AbstractWireSerializingTestCase.mutateInstance()` abstract
* [ ] Make `AbstractStreamableTestCase.mutateInstance()` abstract

**Comment by idegtiarenko** [comment]
Should we make `AbstractWireSerializingTestCase.mutateInstance()` abstract now and implement with empty `return null;` in all remaining sub-classes? This way we would not accidentally introduce more test cases that are silently skipping instance mutation.

**Comment by idegtiarenko** [comment]
This is the compile failures I got after trying to compile only the server module after making `mutateInstance()` abstract:

- [ ] RetentionLeaseStatsWireSerializingTests
- [ ] ShardCountStatsTest
- [ ] ExplainResponseTests
- [ ] GetStoredScriptResponseTests
- [ ] IndexFeatureStatsTests
- [ ] ClusterStateResponseTests
- [ ] SnapshotStatusTests
- [ ] SnapshotsStatusResponseTests
- [ ] ResolveIndexResponseTests
- [ ] ResolveIndexRequestTests
- [ ] GetIndexResponseTests
- [ ] CloseIndexResponseTests
- [ ] GetFieldMappingsResponseTests
- [ ] GetIndexTemplatesResponseTests
- [ ] QueryExplanationTests
- [ ] CreateIndexRequestTests
- [ ] ResizeRequestTests
- [ ] GetSettingsResponseTests
- [ ] HealthMetadataSerializationTests
- [ ] HealthStatusTests
- [ ] HealthNodeTaskParamsTests
- [ ] DataStreamAliasTests
- [ ] DesiredNodesMetadataSerializationTests
- [ ] ItemUsageTests
- [ ] DataStreamTests
- [ ] DataStreamTemplateTests
- [ ] ClusterApplierRecordingServiceStatsTests
- [ ] RoundingWireTests
- [ ] UpdatePersistentTaskRequestTests
- [ ] PersistentTasksExecutorResponseTests
- [ ] StartPersistentActionRequestTests
- [ ] CancelPersistentTaskRequestTests
- [ ] PersistentTasksCustomMetadataTests
- [ ] CompletionPersistentTaskRequestTests
- [ ] PersistentTasksNodeServiceStatusTests
- [ ] SystemIndexMigrationTaskParamsTests
- [ ] FetchSourceContextTests
- [ ] PointInTimeBuilderTests
- [ ] SearchHitTests
- [ ] CollectorResultTests
- [ ] QueryProfileShardResultTests
- [ ] AggregationProfileShardResultTests
- [ ] SearchProfileResultsTests
- [ ] SearchProfileShardResultTests
- [ ] ProfileResultTests
- [ ] SearchProfileDfsPhaseResultTests
- [ ] SearchProfileQueryPhaseResultTests
- [ ] InternalIpPrefixTests
- [ ] MultiValuesSourceFieldConfigTests
- [ ] WeightedAvgAggregationBuilderTests
- [ ] AggregatorFactoriesBuilderTests

**Comment by rjernst** [comment]
It seems like some tests were missed in the generation of the original list. If you think you can cleanly cut these all over to to returning null so that the base method can be made abstract, it would seem worthwhile to stop more tests from being added that do not implement mutateInstance().

**Comment by thecoop** [comment]
`mutateInstance` is now an abstract method, so this can be closed
