### ISSUE TITLE
bootstrap.system_call_filter not disabled!

### ISSUE THREAD

**Issue by seokickup** [elastic/elasticsearch#25926]
ES 5.5
OpenJDK 1.8
CentOS v6

I know this has been discussed and closed here but i still have issues with it, i just installed ES 5.5 in my CentOS 6 box. i am facing the well known error: system call filters failed to install; check the logs and fix your configuration or disable system call filters at your own risk

and i have followed your resolution by disabling the (bootstrap.system_call_filter) by setting it to false in /config/elasticsearch.yml but the problem still persist and i get the same error over and over. 

Did i miss anything here? appreciate your help 

Thanks.

**Comment by danielmitterdorfer** [comment]
Hi @seokickup, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead.

As a hint: If the setting does not change, are you sure you are editing the correct config file? Please see the [directory layout](https://www.elastic.co/guide/en/elasticsearch/reference/current/rpm.html#rpm-layout) in the docs. The default location for config files installed via RPM is `/etc/elasticsearch/elasticsearch.yml`, not `/config/elasticsearch.yml`.
