### ISSUE TITLE
Geo_shape indexing issue - java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by aj7** [elastic/elasticsearch#25933]
**Elasticsearch version**: 5.4.1

**Plugins installed**: []

**JVM version** (`java -version`): java version "1.8.0_131"

**OS version** (`uname -a` if on a Unix-like system): MacOS 10.11.6

**Description of the problem including expected versus actual behavior**:
Have been trying to index a lot of geometry, and getting consistently the same problems with those geometry/polygons that seem to contain a lot of vertices. Have tried importing the shapefile, and geojson through ogr2ogr. also tried generating a json file to use with bulk update. The error I am getting is an ArrayOutofBoundsException. 

Also to note, if I upload the JSON file without specifying a mapping i.e. a geo_shape, then the data gets sucked in, but I would expect it's then not indexed.

As I have consistently been able to reproduce this with different upload routes, I am assuming it has to be a bug - is there a way around it? 

Error I am getting is below:
https://gist.github.com/aj7/12fa99044901d7db8b42a5d5d5753bf8

I am happy to attach the json file if someone want's to try and see for themselves?

**Comment by danielmitterdorfer** [comment]
@aj7 It would be very helpful if you can create a minimal reproduction scenario (data + API calls / curl commands).

**Comment by aj7** [comment]
Sure, I have put the info in the [gist](https://gist.github.com/aj7/307b4577dbe52601c5e7b940d81450cd)

Hope this is fine?

**Comment by danielmitterdorfer** [comment]
Based on the data from the gist I could create a minimal reproduction scenario consisting of only one document (attached compressed as [geometry.json.zip](https://github.com/elastic/elasticsearch/files/1180167/geometry.json.zip)).

```
curl -XDELETE "http://localhost:9200/speedlimit"

curl -XPUT "http://localhost:9200/speedlimit" -d '
{
  "mappings": {
    "speedlimit": {
      "properties": {
        "geometry": {
          "type": "geo_shape",
          "tree": "quadtree",
          "precision": "100m"
        }
      }
    }
  }
}'
# ensure that you've unzipped geometry.json.zip from the attachment above
curl -XPOST 'http://localhost:9200/_bulk?pretty' --data-binary @geometry.json
```

Will lead to:

```
{
  "took" : 33813,
  "errors" : true,
  "items" : [
    {
      "index" : {
        "_index" : "speedlimit",
        "_type" : "speedlimit",
        "_id" : "AV2EWf3T4RDVowrFsHtQ",
        "status" : 400,
        "error" : {
          "type" : "mapper_parsing_exception",
          "reason" : "failed to parse [geometry]",
          "caused_by" : {
            "type" : "array_index_out_of_bounds_exception",
            "reason" : "-1"
          }
        }
      }
    }
  ]
}
```

and in the logs:

```
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [geometry]
	at org.elasticsearch.index.mapper.GeoShapeFieldMapper.parse(GeoShapeFieldMapper.java:473) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:450) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:467) ~[elasticsearch-5.4.1.jar:5.4.1]
[...]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at org.elasticsearch.common.geo.builders.PolygonBuilder.assign(PolygonBuilder.java:483) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.common.geo.builders.PolygonBuilder.compose(PolygonBuilder.java:455) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.common.geo.builders.PolygonBuilder.coordinates(PolygonBuilder.java:221) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.common.geo.builders.MultiPolygonBuilder.build(MultiPolygonBuilder.java:129) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.index.mapper.GeoShapeFieldMapper.parse(GeoShapeFieldMapper.java:455) ~[elasticsearch-5.4.1.jar:5.4.1]
	... 36 more

**Comment by apeters** [comment]
I have nothing to add to this ticket other than to +1 @aj7 on this issue.  We too have seen this error with either high vertex count polygons or polygons with very high precision.  Sometime the workaround is to simplify the geometry with something like PostGIS but often that can compromise the data.  
And, for what it's worth, it's not too hard to generate polygons like this (imagine a highly precise polygon representing country borders).

**Comment by rkuchvarskyy** [comment]
We also faced with this issue
Simple example cause Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
{"type":"Polygon","coordinates":[[[-10,10.0000000000002],[-5,-5],[10,5],[-10,10.0000000000002]],[[-10,10],[0,5],[0,0],[-10,10]]]}

**Comment by DaveCTurner** [comment]
This seems to be because of an error in the geometry you're trying to index, although it would certainly be helpful if there was a more descriptive error message given. The attached zip file, for instance, contains self-intersections so I think it's right to reject it.

Here is a shorter reproduction:

```
$ curl -XDELETE "http://localhost:9200/speedlimit"
{"acknowledged":true}
$ curl -XPUT "http://localhost:9200/speedlimit" -H'Content-type: application/json' -d '{"mappings":{"speedlimit":{"properties":{"geometry":{"type":"geo_shape","tree":"quadtree","precision":"100m"}}}}}'
{"acknowledged":true,"shards_acknowledged":true,"index":"speedlimit"}
$ curl -XPOST "http://localhost:9200/speedlimit/speedlimit" -H'Content-type: application/json' -d '{"geometry":{"coordinates":[[[[4,3],[3,2],[3,3],[4,3]],[[4,2],[3,1],[4,1],[4,2]]]],"type":"MultiPolygon"}}'
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse [geometry]"}],"type":"mapper_parsing_exception","reason":"failed to parse [geometry]","caused_by":{"type":"array_index_out_of_bounds_exception","reason":"-1"}},"status":400}
```

In this case the given geometry contains two triangles, the first of which is anticlockwise and the second is clockwise, indicating that one is an enclave (hole) within the other. However the triangles do not touch.

**Comment by DaveCTurner** [comment]
@rkuchvarskyy the example you give also is not a valid geometry because the "hole" is not completely within the outer polygon. It's too small to see the error, but if I exaggerate the problem a bit your shape looks like this:

<img width="278" alt="screen shot 2017-12-05 at 15 41 56" src="https://user-images.githubusercontent.com/5058284/33615906-39893440-d9d3-11e7-86e4-11992042b03c.png">

**Comment by rkuchvarskyy** [comment]
@DaveCTurner I understood this but I expect some validation error but not java.lang.ArrayIndexOutOfBoundsException

**Comment by DaveCTurner** [comment]
As of version 6.2 these shapes will yield a more descriptive `org.locationtech.spatial4j.exception.InvalidShapeException` rather than `java.lang.ArrayIndexOutOfBoundsException`, via #27685.

Note that this issue was nothing to do with the vertex count, nor the precision, and that the fix does not change the set of shapes accepted by Elasticsearch: it merely improves the message it gives when rejecting some invalid ones.
