### ISSUE TITLE
ingest-attachment plugin (upload without base64 encoding)

### ISSUE THREAD

**Issue by faizalpribadi** [elastic/elasticsearch#25939]
**Elasticsearch version `5.5.1`:

**Plugins installed**: `["ingest-attachment"]`

**JVM version** (`java version "1.8.0_141`):

**OS version** (`Darwin Kernel Version 16.7.0`):

Im so tired when i'm using `ingest-attachment` plugin for indexing my document like `[.doc - .pdf - any kind of documents]`,  Documents with large size `> 50mb` it's so hard to encode, 
is there any other way for indexing large documents ? or indexing documents with parallel processing ? can anyone help me to solve my issue ? thanks !!!

**Comment by hub-cap** [comment]
Hi, 

Are you breaking the pdf up into chunks and encoding them in parallel? I just tested with a quick java application and was able to produce a valid base64 encoded file reading in 1000*3 byte chunks (Base64 likes 3 byte increments so it does not need to pad). Im sure you can write some code that will parallelize that operation to speed up the encoding.

Also, questions like this are better served in the [community forums](https://discuss.elastic.co/c/elasticsearch), as we reserve github issue for verified bug reports and feature requests.
