### ISSUE TITLE
Values in filter terms being ignored during aggregation

### ISSUE THREAD

**Issue by giudicelli** [elastic/elasticsearch#25949]
**Elasticsearch version**: 2.4.5

**Plugins installed**: none

**JVM version**:
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

**OS version** :
Linux XXXX 3.14.32-xxxx-grs-ipv6-64 #9 SMP Thu Oct 20 14:53:52 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
When using a reference in "terms" for the "_uid" field in an aggregation, the filter is being ignored.
However, when using the same filter on a normal search, the filter is being honored.

**Steps to reproduce**:
Create an index and a type holding in a field a list of _uid, in my case the field holds over 50k uids.
Run an aggregation filtering on this list of _uid.
The filter is being ignored, and aggregation is ran on every entry...

Example:
`{
   "size":0,
   "filter":{
     "terms":{
        "_uid":{
           "index":"CACHE_INDEX",
           "type":"Cache",
           "id":"CacheId",
           "path":"UIDSList"
        }
     }
   },
   "aggs":{
      "counter":{
         "date_histogram":{
            "field":"DateField",
            "interval":"day",
            "missing":0,
            "time_zone":"+02:00"
         }
      }
   }
}`

The queried type was created with the following meta parameters:
` 
  {
     "_all" : {"enabled" : false},
      "date_detection": false,
      "dynamic": "strict",
      "properties": { ... }
  }
`

**Comment by rjernst** [comment]
Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports.

Your `_uid` there is not a value, it is an object, and I suspect lacked validation in 2.x. Validation is much better in 5.0+ since The Great Query Refactoring.
