### ISSUE TITLE
Mapper parsing exception for date type

### ISSUE THREAD

**Issue by matthkang** [elastic/elasticsearch#25942]
Sending a log with a date value of "yyyy-MM-dd'T'HH:mm:ss.SSSZ" results in an error of MapperParsingException.

Full error message:
`Failed to index [1] messages. Please check the index error log in your web interface for the reason. Error: failure in bulk execution: [0]: index [graylog_0], type [message], id [9751fd11-7320-11e7-aff3-0242994e81cd], message [MapperParsingException[failed to parse [insertedDtm]]; nested: NumberFormatException[For input string: "2017-07-27T23:08:36.692Z"];]`

I have tried creating custom index mappings with the following format:
`curl -XPUT localhost:9200/_template/graylog -d ' { "template" : "graylog_*", "mappings" : { "message" : { "properties" : { "insertedDtm" : { "type" : "string", "format" : "yyyy-MM-dd'T'HH:mm:ss.SSSZ" } } } } }`

and also tried to set the index's date detection to false:
`curl -XPUT "http://localhost:9200/graylog" -d' { "mappings": { "insertedDtm": { "date_detection": false } } }'`

Any help would be greatly appreciated.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

Check also what your final mapping is (not the template)
