### ISSUE TITLE
Document change in wildcard search behavior starting in ES 5

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#25940]
**Elasticsearch version**: 2.4 -> 5.5

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Test case is here:  https://gist.github.com/ppf2/6b8d7e27631905615662b4746cbd68fd.  On 2.4, the wildcard search+analyze_wildcard:true works against both analyzed and not_analyzed field, but on 5.x, it only works against keyword field.  (Certainly, for wildcard searches, it makes more sense to run against a keyword field, but this represents a change in behavior between the major versions).

Quick chat with @jpountz revealed that there was indeed a change in behavior between the versions where we now match the wildcard expression against a single token.  It will be helpful to document this somewhere, maybe here (https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_search_changes.html)?

**Comment by mayya-sharipova** [comment]
PR #42706 has addressed this issue
