### ISSUE TITLE
"Failed to compute BIC gain" error from Machine Learning

### ISSUE THREAD

**Issue by tommymonk** [elastic/elasticsearch#25945]
Elasticsearch version: 5.5.0
Plugins installed: [x-pack]
JVM version: 1.8.0_141
OS version: Ubuntu Server 16.04

We're trialing the machine learning capabilities of Elasticsearch in Kibana.

Our test job json is [here](https://github.com/elastic/elasticsearch/files/1182774/job.txt).

I'm seeing regular log error messages like the one below, should I be concerned ?

[2017-07-28T10:37:33,573][ERROR][o.e.x.m.j.p.l.CppLogMessageHandler] [test_multi_1] [autodetect/1404] [CXMeansOnline1d.cc@403] Failed to compute BIC gain: Error in function boost::math::lgamma<double>
(double): Evaluation of lgamma at 0., n = 108.739, m = -8.7601e+018, v = 3.76441e+022, wl = 0.855782, ml = -8.7601e+018, vl = 1, wr = 0.144218, mr = -8.7601e+018, vr = 1.11544e+006 | repeated [3]

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch. We do not handle closed source here, instead that's for the X-Pack category on the [forum](https://discuss.elastic.co). Would you please open a topic there?
