### ISSUE TITLE
Option for excluding fields in "all_fields" query mode

### ISSUE THREAD

**Issue by mr-mos** [elastic/elasticsearch#25946]
In ES 6.0 the indexed "_all" field will be removed and Elastic is promoting the "all_fields" query (default_field=*) that does the same (at query- and not indexed time).

There should be a feature for restricting fields in the all_fields search. 
A multi_match or other queries would expect, that clients know which fields are available and should be searched by default. In many cases this is a configuration on the index and shouldn't be known by the client.

It would be nice to have a configuration option similar to the " include_in_all: false" used in the deprecated indexd based _all-field.

This topic was discussed with @dakrone in the the issue #25105  and in the thread https://discuss.elastic.co/t/option-for-excluding-fields-in-all-fields-mode-query-for-es-6-0/93218

**Comment by jimczi** [comment]
Discussed in Fix it Friday and we agreed that we should also accept an array for the `index.query.default_field` index setting. It would then be possible to define the default search fields associated with an index. The rules to expand the field names would be the same as if provided as `fields` in a `query_string` query.

**Comment by mr-mos** [comment]
Thanks. Any planning when it will be integrated into ES.   beta-2  ?

**Comment by jimczi** [comment]
Still some blockers on the `simple_query_string` side but I plan to work on this as soon as https://github.com/elastic/elasticsearch/pull/26145 is resolved.
