### ISSUE TITLE
Number _id on ES 6 with single-type indexes

### ISSUE THREAD

**Issue by ddorian** [elastic/elasticsearch#25957]
On the new version, with _id being just a single value, and cases where the _id is an integer, actually store/index/doc_id it as an integer (you can do this with solr). This will make smaller indexes and faster performance. So a mapping-setting or index-setting to only allow integer (or date etc) values. The api can still stay as string, I don't know.

Makes sense ?

**Comment by jpountz** [comment]
We cannot use numbers as ids, since the data-structure they use in Elasticsearch (points) cannot be used is ids in Lucene: ids need to be indexed with the inverted index.

However, we did some changes in #25352 to store numeric ids more efficiently.
