### ISSUE TITLE
On the elasticsearch of the Fuzzy Query problem, please help answer, pointing me forward.

### ISSUE THREAD

**Issue by hubiao1** [elastic/elasticsearch#25973]
Version: 5.5.0
Windows 10
Jdk 1.8

1: What should I need to set up an index before I can query?

2: I would like to match any data that is indexed (with a lot of Chinese)? Can Fuzzy Query do that? How about speed

3: my ultimate goal is to achieve like this% keyword% any match.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by hubiao1** [comment]
Https://discuss.elastic.co/c/elasticsearch China can not visit now.

**Comment by dadoonet** [comment]
Really? I thought this problem has been solved.

@medcl can you confirm the discuss access problem ?

**Comment by hubiao1** [comment]
I have not solved this problem. The The The

**Comment by hubiao1** [comment]
@dadoonet @medcl

**Comment by medcl** [comment]
@hubiao1 you may also visit http://elasticsearch.cn for convenient
