### ISSUE TITLE
[DOCS] Examples contained in README.textile are no longer valid

### ISSUE THREAD

**Issue by olcbean** [elastic/elasticsearch#25978]
In the current [README.textile](https://github.com/elastic/elasticsearch/blob/master/README.textile) there are a few references to multiple types per index. In the example below there are 2 types ( `user` and `tweet` ) on the index `twitter` : 

```
curl -XPUT 'http://localhost:9200/twitter/user/kimchy?pretty' -H 'Content-Type: application/json' -d '{ "name" : "Shay Banon" }'

curl -XPUT 'http://localhost:9200/twitter/tweet/1?pretty' -H 'Content-Type: application/json' -d '
{
    "user": "kimchy",
    "post_date": "2009-11-15T13:12:00",
    "message": "Trying out Elasticsearch, so far so good?"
}'
```
As per #24428 only one type can be created per index, and the above requests result in an error :
```
"type" : "illegal_argument_exception",
"reason" : "Rejecting mapping update to [twitter] as the final mapping would have more than 1 type: [tweet, user]"
``` 
Relates to #25401

**Comment by nik9000** [comment]
Man. I feel bad that the docs testing doesn't catch this as well. I've wanted it to, but it relies on the CONSOLE syntax and the readme.asciidoc can't use that.
