### ISSUE TITLE
Request to `_nodes` does not return `http_address`

### ISSUE THREAD

**Issue by beowulfenator** [elastic/elasticsearch#25980]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 5.5.1, Build: 19c13d0/2017-07-18T20:44:24.823Z

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "1.8.0_131"

**OS version** (`uname -a` if on a Unix-like system):
Linux ubuntu 4.4.0-62-generic

**Description of the problem including expected versus actual behavior**:
I am running a single ES node bound to a specific IP address (`network.host: 10.26.1.102`). As per [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/cluster-nodes-info.html), the `_nodes` request should return, among other things, `http_address`, and yet it doesn't. Other fields are present, but that one is not. Is this a bug, or are the docs outdated?

**Steps to reproduce**:
`curl -XGET 10.26.1.102:9200/_nodes?pretty`

**Provide logs (if relevant)**:
```
"nodes" : {
  "MU4dFMhCRCOd-dmzkRoncA" : {
    "name" : "MU4dFMh",
    "transport_address" : "10.26.1.102:9300",
    "host" : "10.26.1.102",
    "ip" : "10.26.1.102",
    "version" : "5.5.1",
    "build_hash" : "19c13d0",
    "total_indexing_buffer" : 213876736,
    "roles" : [
      "master",
      "data",
      "ingest"
    ],
    ...
```

**Comment by jasontedor** [comment]
It's there, in the `http` object. You can see this by piping the output to `grep` (e.g., `curl -XGET localhost:9200/_nodes?pretty=true | grep -A 8 http`) or via more sophisticated means such as `curl -XGET localhost:9200/_nodes/http?pretty=true` which filters the response down to only the `http` object or `curl -XGET localhost:9200/_nodes | jq '.nodes | .[].http'`.

**Comment by beowulfenator** [comment]
Thanks for your reply. Here's what I get in the `http` object.
```
"http" : {
  "bound_address" : [
    "10.26.1.102:9200"
  ],
  "publish_address" : "10.26.1.102:9200",
  "max_content_length_in_bytes" : 104857600
},
```
I'm upgrading from ES1.7, so I take it that `http.publish_address` now holds the data that used to be in `http_address` in the older version? The docs are definitely outdated then.

**Comment by jasontedor** [comment]
I pushed 91fb08a102a0782d63fadded7dd70a90c7f342ba; the docs will update on the website automatically soon.
