### ISSUE TITLE
Elasticsearch doesn't start inside a UTF-8 cmd.exe on a Windows Server 2016 Core

### ISSUE THREAD

**Issue by ffosselle** [elastic/elasticsearch#25981]
Elasticsearch doesn't start inside a UTF-8 cmd.exe on Windows Server 2016 Core instance.

This can be easily reproduced on a Windows 10 instance by manually changing the codepage to 65001:

1) Open a cmd.exe with default code page set to 850. Elasticsearch starts fine.
2) Change the code page to 65001 (Unicode) via the chcp command.  Start Elasticsearch again. This will throw the exception below:

`2017-07-31 13:51:03,209 main ERROR Unable to inject fields into builder class for plugin type class org.apache.logging.log4j.core.appender.ConsoleAppender, element Console. java.nio.charset.UnsupportedCharsetException: cp65001
        at java.nio.charset.Charset.forName(Charset.java:531)`

The exception is thrown by log4j and already reported as ticket:
https://issues.apache.org/jira/browse/LOG4J2-1888

Till this is fixed, I'm wondering if someone knows a work-around? I tried to set the character set via the log4j2.properties file, but no luck yet.

**Comment by jasontedor** [comment]
Yes, a workaround would be to set the JVM options: -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8.

**Comment by dadoonet** [comment]
@jasontedor Should this be documented in the installation guide?

**Comment by jasontedor** [comment]
@dadoonet For now I don't think so, this is the first report we have seen of this issue; if we see repeated reports, comments or 👍 on this issue then we consider it (I also want to wait and see how the upstream issue is handled).

**Comment by jasontedor** [comment]
Note that the upstream issue is fixed starting in Log4j 2.9.0 which is included in Elasticsearch 5.6.0 and future pre-releases of Elasticsearch 6.0.0 (it missed 6.0.0-beta2). At this time, the need for the above workaround should go away. I will verify this later today.

**Comment by jasontedor** [comment]
I verified that with Log4j 2.9.0, this issue does go away in the following sense: the node will now successfully start with Log4j falling back to UTF-8 as opposed to before where it blew up when it did not know what to do with the charset `cp65001`. However, Log4j dumps a low-level stack trace to the console. This is a low-level dump in the sense that it does not go through the status logger so we have no chance to capture this and keep it off the console.

**Comment by yaoayaoa** [comment]
1.set utf-8:

   1.cmd
   2.chcp 65001
   3.close




2.set default code:

   1.cmd
   2.chcp 936
   3.right-hand button -> option -> discard old copies

**Comment by AdrianMonk1987** [comment]
> Yes, a workaround would be to set the JVM options: `-Dsun.stdout.encoding=UTF-8` and `-Dsun.stderr.encoding=UTF-8`.

Thank you for your answer. It worked. I'm using elasticseach6.0 In OS/Windows10. When I start up elasticseach, the console throw this error. Based your method, I revise ES_HOME/config/jvm.options by adding ' -Dsun.stdout.encoding=UTF-8
-Dsun.stderr.encoding=UTF-8 ' . Start up es again, the console doesn't throw any error any more.
