### ISSUE TITLE
Can replica shard stop writing translog?

### ISSUE THREAD

**Issue by djjsindy** [elastic/elasticsearch#25997]
**Describe the feature:**
   
   Replica shard can recovery from primary shard (segment diff & primary translog),considering write performance requirements，can replica shard stop writing translog？
   when primary shard shutdown abnormally , first flush replica shard and then primary shard switch。

**Comment by bleskes** [comment]
@djjsindy this could be a trade off we can make - with a lot of extra complexity - but it will also prevent things like ops based recovery (to a limited degree) and a Changes API where the historical operations in the translog are needed. I'm curious to learn why you request the feature.

**Comment by djjsindy** [comment]
@bleskes thanks for your reply.

In my scenarios, in the case of limited hardware resources, I need a very strong write performance, translog cost 20%-30% (not fsync) write time in reality test.
I see some source code of recovery process, I consider whether server can remove the replica translog.
could you give some suggestions or advice ? I will be looking forward to your reply.

**Comment by bleskes** [comment]
@djjsindy I see. I wonder why the translog is such a big offender if you don't fsync on every request. Just like lucene, it buffers stuff in memory and writes when the buffer is full. Also you can consider running with no replicas and turn them one when indexing is done. I'm going to close this now. We can continue discussing things on discuss.elastic.co . We can always reopen this if things change.
