### ISSUE TITLE
Can update request support 'external' version type ?

### ISSUE THREAD

**Issue by maoxiajun** [elastic/elasticsearch#25996]
<Feature request>

Index request supports explicit version with VersionType.EXTERNAL, but set an explicit version to an update request will fail with an ValidationException("version type is not supported by the update API").
As my opinion, index action with explicit version also needs to retrieve the old doc and make a version check, so can update request support VersionType.EXTERNAL too ?

**Comment by bleskes** [comment]
The external version type is meant for use case where there is an external source of truth which tracks a per doc version number. ES is then kept up to date by indexing all operations from the source, potentially concurrently. I this case the indexing API would be used and the version semantics are "index this complete doc if the current doc version is older". Notice how these semantics work nicely with concurrent indexing. It also means that the version given is the version of the complete document in the source.

The update API is syntactic sugar for "get this doc and change it in this way if it has not changed". This works nicely with interval version but it conflicts with the notion of an external source associating a version with a complete document.

I'm closing this now. Please feel free to open a discussion on discuss.elastic.co to discuss things further. If it ends up we need to change/fix something we can open up a github issue.

**Comment by maoxiajun** [comment]
ok, I'm thinking about it, thx.
