### ISSUE TITLE
[CI] MasterDisruptionIT test fails regularly, but not fully reproducible

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#26011]
Over night a fair share of `org.elasticsearch.discovery.MasterDisruptionIT` failed, here is the list (happening on master, 6.0 and 6.x)

These tests are not reliably failing locally, but one in three runs did on master with this seed

```
gradle :core:integTest -Dtests.seed=6D689A22A8DD69A4 -Dtests.class=org.elasticsearch.discovery.MasterDisruptionIT -Dtests.method="testMasterNodeGCs" -Dtests.security.manager=true -Dtests.locale=mk-MK -Dtests.timezone=America/Recife
```

More failures:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+aggressive-opts/26/consoleFull
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/3761/consoleFull
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+oracle-periodic/67/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=amazon/1388/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/14/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+aggressive-opts/509/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/3760/console

@bleskes can you take a look maybe?

**Comment by tbrooks8** [comment]
This should be fixed by: 58d2dcc54f63cbe2c04762653d68566e99bec992. But I forgot to respond to the build email. That's my bad. Sorry for the noise.

If you go back prior to that commit, these failures were reproducible.
