### ISSUE TITLE
Caching hits for query with size parameter

### ISSUE THREAD

**Issue by kewats** [elastic/elasticsearch#26010]
I am trying to optimise performance of my queries. My queries have sort and aggregations. Additionally, I specify from and size parameters as I need data to be fetched in batches.

I am using request cache which makes sure aggregations are not executed every time. However, I have not been able to find a way to cache the query data.

Looked at [https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html](url)

> "By default, the requests cache will only cache the results of search requests where size=0, so it will not cache hits, but it will cache hits.total, aggregations, and suggestions."

Is there a way I can cache search results in such cases?

Sample query:

```
GET myIndex/_search?request_cache=true
{
    "size": 20,
    "from": 0,
    "query": { ... },
    "sort": { ... },
    "aggregations": { ... }
}
```

**Comment by jpountz** [comment]
The described behaviour is only the default, if you pass `request_cache=true` to the query string, it will be cached regardless of the value of `size`.
