### ISSUE TITLE
BulkProcessor can't be used with empty settings in the high level client

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#26028]
According to [the documentation](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/5.6/java-rest-high-document-bulk.html#java-rest-high-document-bulk-processor), you "only" need to write the following code to create a Rest Bulk Processor:

```java
        ThreadPool threadPool = new ThreadPool(Settings.EMPTY);
        BulkProcessor.Listener listener = new BulkProcessor.Listener() {
            @Override public void beforeBulk(long executionId, BulkRequest request) { }
            @Override public void afterBulk(long executionId, BulkRequest request, BulkResponse response) { }
            @Override public void afterBulk(long executionId, BulkRequest request, Throwable failure) { }
        };

        bulkProcessorDoc = new BulkProcessor.Builder(client.getHlClient()::bulkAsync, listener, threadPool).build();
```

This is actually failing with empty settings as the `ThreadPool` class [is waiting for a `node.name` setting](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java#L166):

```java
        assert Node.NODE_NAME_SETTING.exists(settings);
```

I think we should either remove the need for the node name when configuring a Client ThreadPool or to document that this is needed for now:

```java
        ThreadPool threadPool = new ThreadPool(Settings.builder().put(Node.NODE_NAME_SETTING.getKey(), "high-level-client").build());
```

I wonder though if the High Level Rest Client itself should not provide OOTB a default ThreadPool with a name like `high-level-client`.

Thoughts?

**Comment by javanna** [comment]
@dadoonet where do you see the mention of `ThreadPool threadPool = new ThreadPool(Settings.EMPTY);`? I see `ThreadPool threadPool = new ThreadPool(settings);` where we may want to clarify what the settings should be. I also agree that having to provide node.name is a bit annoying, but I don't think we want to relax that check in core.

**Comment by dadoonet** [comment]
> where do you see the mention of `ThreadPool threadPool = new ThreadPool(Settings.EMPTY);`?

Nowhere. I just found that as I have no specific settings for my client, I can pass an empty one.

We just need then to document that it can't be EMPTY as it must be something like:

```
Settings.builder().put(Node.NODE_NAME_SETTING.getKey(), "high-level-client").build();
```

**Comment by javanna** [comment]
> We just need then to document that it can't be EMPTY 

yes I think so, that is the easiest at the moment.

**Comment by bleskes** [comment]
That assertion in core is made to make sure we can found out what the source test was when it forgets to close the thread pool (lingering threads) or we have an uncaught exception in a thread. I agreed it's a bit of a drag on using the BulkProcessor. We can maybe add a constructor that takes a name to the ThreadPool?  Similar to TestThreadPool (which will be obsolete). We can then also assert that if you use an explicit name, `node.name` isn't set in the setting.

**Comment by jasontedor** [comment]
I made a [different proposal](https://github.com/elastic/elasticsearch/pull/26283#issuecomment-324313494) on #26283; I think we should work to remove the need for the bulk processor to even need the Elasticsearch server thread pool. It does not need its full power, only the scheduler which can be provided separately.
