### ISSUE TITLE
[CI] InternalMatrixStatsTests.testEqualsAndHashcode fails reproducibly

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#26024]
This one fails reliably for me on master

```
gradle :modules:aggs-matrix-stats:test -Dtests.seed=3DAAF17E8B2D0407 -Dtests.class=org.elasticsearch.search.aggregations.matrix.stats.InternalMatrixStatsTests -Dtests.method="testEqualsAndHashcode" -Dtests.security.manager=true -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" -Dtests.locale=en-IE -Dtests.timezone=Europe/Kiev
```

Corresponding build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/3766/console

@colings86 I assume that https://github.com/elastic/elasticsearch/pull/25999/files has sth to do with it, after a quick history check

**Comment by colings86** [comment]
I've fix this in https://github.com/elastic/elasticsearch/commit/bb3d5b7426a19188635fc54a160c772bcb99618d
