### ISSUE TITLE
[CI] ClusterSearchShardsResponseTests.testSerialization fails reproducibly

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#26021]
This test fails reproducibly on 6.x with the seed

```
gradle :core:test -Dtests.seed=5C8255CFDC8B4C68 -Dtests.class=org.elasticsearch.action.admin.cluster.shards.ClusterSearchShardsResponseTests -Dtests.method="testSerialization" -Dtests.security.manager=true -Dtests.locale=et-EE -Dtests.timezone=US/Pacific
```

CI link https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/62/console

@colings86 can you take a look as the NPE stems from a querybuilder test?

**Comment by colings86** [comment]
@spinscale thanks for raising this, I'll look into it. Just for the record I can also reproduce this on master and I suspect the problem also exists on the 6.0 branch

**Comment by colings86** [comment]
I opened https://github.com/elastic/elasticsearch/issues/26023 to fix this
