### ISSUE TITLE
Bug for escape character

### ISSUE THREAD

**Issue by pradeepkusingh** [elastic/elasticsearch#26032]
1.  I am trying to query using mac address(Java rest API) which has colun between 2 each digit and failing.

2.  Applied multiple solutions discussed in a different form and still seeing issues.

java.lang.IllegalArgumentException: Illegal character in query at index 56: /caap-test-2017.08.01/_search?from=0&size=10&q=response:\*xx\:6A\:B7\:D0\:44\:5F\*

**Comment by rjernst** [comment]
Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports.

That said, using `q` query parameter is a shortcut for the query string query. See the documentation on reserved characters and how to escape:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters
