### ISSUE TITLE
Either Painless documentation is misleading, or support for java 8 time is broke

### ISSUE THREAD

**Issue by StuAtGit** [elastic/elasticsearch#26034]
**Elasticsearch version** (`bin/elasticsearch --version`):
 /usr/share/elasticsearch/bin/elasticsearch --version
Version: 5.0.1, Build: 080bb47/2016-11-11T22:08:49.812Z, JVM: 1.8.0_45

**Plugins installed**: []

**JVM version** (`java -version`):
 java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
2.6.32-431.el6.centos.plus.x86_64 #1 SMP Fri Nov 29 23:11:12 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Expected Behavior:
If the documentation states all Java types are supported in Painless, I would expect to be able to assign a field of type OffsetDateTime to another field of type OffsetDateTime.

Action Behavior:
It throws an exception.

The Painless documentation states that all Java types are supported:
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/modules-scripting-painless-syntax.html
It links to Oracles documentation on variables as an explanation:
https://docs.oracle.com/javase/tutorial/java/nutsandbolts/variables.html
I don't understand what variables have to do with types in this context, though.

Java 8 now comes with OffsetDateTime:
https://docs.oracle.com/javase/8/docs/api/java/time/package-summary.html

However, when I try to update a field that is of type OffsetDateTime:
```
ctx._source.messageDatetime = params.messageDatetime;
```
(note, I have a script, and it's along sequence of assignments, but with the above line it breaks, without it, it works fine).

I get an error, with the apparent root cause being:
Caused by: java.io.IOException: can not write type [class java.time.OffsetDateTime]
	at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:639)
	at org.elasticsearch.common.io.stream.StreamOutput.lambda$static$10(StreamOutput.java:554)

Looking at the code, it looks like either the docs are wrong or I'm misunderstanding the code, because it looks like only *primitive* types, and a hodgepodge of other types are supported:

In writeGenericValue:
```
        final Writer writer = WRITERS.get(type);
        if (writer != null) {
            writer.write(this, value);
        } else {
            throw new IOException("can not write type [" + type + "]");
        }
```

In StreamOutput:
```
    static {
        Map<Class<?>, Writer> writers = new HashMap<>();
        writers.put(String.class, (o, v) -> {
            o.writeByte((byte) 0);
            o.writeString((String) v);
        });
        writers.put(Integer.class, (o, v) -> {
            o.writeByte((byte) 1);
            o.writeInt((Integer) v);
        });
        writers.put(Long.class, (o, v) -> {
            o.writeByte((byte) 2);
            o.writeLong((Long) v);
        });
        writers.put(Float.class, (o, v) -> {
            o.writeByte((byte) 3);
            o.writeFloat((float) v);
        });
        writers.put(Double.class, (o, v) -> {
            o.writeByte((byte) 4);
            o.writeDouble((double) v);
        });
        writers.put(Boolean.class, (o, v) -> {
            o.writeByte((byte) 5);
            o.writeBoolean((boolean) v);
        });
        writers.put(byte[].class, (o, v) -> {
            o.writeByte((byte) 6);
            final byte[] bytes = (byte[]) v;
            o.writeVInt(bytes.length);
            o.writeBytes(bytes);
        });
        writers.put(List.class, (o, v) -> {
            o.writeByte((byte) 7);
            final List list = (List) v;
            o.writeVInt(list.size());
            for (Object item : list) {
                o.writeGenericValue(item);
            }
        });
        writers.put(Object[].class, (o, v) -> {
            o.writeByte((byte) 8);
            final Object[] list = (Object[]) v;
            o.writeVInt(list.length);
            for (Object item : list) {
                o.writeGenericValue(item);
            }
        });
        writers.put(Map.class, (o, v) -> {
            if (v instanceof LinkedHashMap) {
                o.writeByte((byte) 9);
            } else {
                o.writeByte((byte) 10);
            }
            @SuppressWarnings("unchecked")
            final Map<String, Object> map = (Map<String, Object>) v;
            o.writeVInt(map.size());
            for (Map.Entry<String, Object> entry : map.entrySet()) {
                o.writeString(entry.getKey());
                o.writeGenericValue(entry.getValue());
            }
        });
        writers.put(Byte.class, (o, v) -> {
            o.writeByte((byte) 11);
            o.writeByte((Byte) v);
        });
        writers.put(Date.class, (o, v) -> {
            o.writeByte((byte) 12);
            o.writeLong(((Date) v).getTime());
        });
        writers.put(ReadableInstant.class, (o, v) -> {
            o.writeByte((byte) 13);
            final ReadableInstant instant = (ReadableInstant) v;
            o.writeString(instant.getZone().getID());
            o.writeLong(instant.getMillis());
        });
        writers.put(BytesReference.class, (o, v) -> {
            o.writeByte((byte) 14);
            o.writeBytesReference((BytesReference) v);
        });
        writers.put(Text.class, (o, v) -> {
            o.writeByte((byte) 15);
            o.writeText((Text) v);
        });
        writers.put(Short.class, (o, v) -> {
            o.writeByte((byte) 16);
            o.writeShort((Short) v);
        });
        writers.put(int[].class, (o, v) -> {
            o.writeByte((byte) 17);
            o.writeIntArray((int[]) v);
        });
        writers.put(long[].class, (o, v) -> {
            o.writeByte((byte) 18);
            o.writeLongArray((long[]) v);
        });
        writers.put(float[].class, (o, v) -> {
            o.writeByte((byte) 19);
            o.writeFloatArray((float[]) v);
        });
        writers.put(double[].class, (o, v) -> {
            o.writeByte((byte) 20);
            o.writeDoubleArray((double[]) v);
        });
        writers.put(BytesRef.class, (o, v) -> {
            o.writeByte((byte) 21);
            o.writeBytesRef((BytesRef) v);
        });
        writers.put(GeoPoint.class, (o, v) -> {
            o.writeByte((byte) 22);
            o.writeGeoPoint((GeoPoint) v);
        });
        WRITERS = Collections.unmodifiableMap(writers);
    }
```

So either the documentation is wrong, or elasticsearch has a bug.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by jdconrad** [comment]
The documentation here in 5.0 is at best misleading, unfortunately.  Check out (https://www.elastic.co/guide/en/elasticsearch/painless/5.5/types.html) for more information on how types work in Painless.  As this documentation is relatively new, any feedback is appreciated if there are confusing areas, ambiguities, or incorrect statements.

**Comment by rjernst** [comment]
@StuAtGit What is your actual request json (ie including parameters, not just the raw script as you have above)?

**Comment by StuAtGit** [comment]
Is there an easy way to dump this from the Java API?
The most promising method I found was:
```
log.debug(updateRequest.upsertRequest().toString());
```
But it appears to not contain the whole request.

**Comment by StuAtGit** [comment]
Also note that I may actually have a workaround coming. Also, I should probably just upgrade to 5.5 - thanks for the reminder & the link @jdconrad  ;)

The workaround is predicate on two main things 
 -  the realization (a straightforward one, once you dig into what's going on), that the types that can be easily assigned to in Painless are necessarily the types that Elastic search natively supports - ints, booleans, maps, lists, and such.

 -  the overall problem I'm trying to solve is how to perform an upsert that merges list. I've seen this referenced elsewhere and dismissed as "too hard, do it with painless". But, note that it's pretty hard to do with painless in a reasonably generic fashion. I may file a feature request for the option to ".mergeLists(true).allowDuplicates(false)" in upsert requests - as that would reduce my problem to a trivial one.

A brief sketch of my workaround is a bit of java code that traverses the Fields of a given POJO (that represents the objects I'm storing in elasticsearch, passed in a request serialized in JSON). Checks the type of each field and decides if:
  - the field is an instance of String, Long, Integer, Double, Boolean ... and generates a simple script line that assigns to the field, with the given field name
  - the field is an instance of a collection - generates a script line that appends values from that field into the existing field in ES
  - the field is another POJO - recurse through the fields of that POJO, building the equivalent flattened path that will exist in elastic search, i.e. "messageDateTime : { dateTime : { year : 0 ..... 
will have a field like [MyRecordType].messageDateTime.dateTime.year built. For each of those paths, at the leaf, you determine the final type, and apply the two rules above.

Note that this all results from me having a large object, with many fields, and, in it, I have *one* list that I really need to be merged, not overwritten - if they are all merged, fine, but that one really does need to be merged. As you can imagine, spending a few days writing up a bunch of Java code to recursively reflect through an objects fields, determining the fields types (and values!!), and generating the corresponding Painless code to allow me to do an upsert where lists are merged does make me think that maybe it would be better to have some simple merge options on the UpsertRequest?
I do understand the general solution to merging a data type in a distributed system is non-trivial:
https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type
But! It seems a few simple options could cover about 90% of the use cases.

**Comment by StuAtGit** [comment]
Another way to make the problem trivial is to allow scripts to run only on certain fields, and use the upsertDoc for all other fields - this means that I could write a small, simple script for one field, and just submit an upsertDoc for the rest. This might be a better approach to the overall use case that triggered this issue.

**Comment by StuAtGit** [comment]
But I digress ;)

**Comment by rjernst** [comment]
Date fields were recently converted over to using the java 8 time api in ES 7.0. The serialization logic mentioned in this issue now handles ZonedDateTime. This is what is now returned from date fields. Thus I am closing this issue.
