### ISSUE TITLE
Painless calls incorrect method, due to inappropriate unboxing

### ISSUE THREAD

**Issue by StuAtGit** [elastic/elasticsearch#26035]
**Elasticsearch version** (`bin/elasticsearch --version`):
/usr/share/elasticsearch/bin/elasticsearch --version
Version: 5.0.1, Build: 080bb47/2016-11-11T22:08:49.812Z, JVM: 1.8.0_45

**Plugins installed**: []

**JVM version** (`java -version`):
java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
2.6.32-431.el6.centos.plus.x86_64 #1 SMP Fri Nov 29 23:11:12 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

If I have a list of integers, and I try to remove one of the integers via the remove() method, it fails, because it calls the wrong remove method.

In java, a List has a remove method like so:
https://docs.oracle.com/javase/8/docs/api/java/util/List.html#remove-java.lang.Object-

I stored a list of Integers in Elastic search, and tried to call the remove method with the Integer to remove:
```
script = "ctx._source.my_list.remove(params.myInteger)";
params = Collections.singletonMap("myInteger", new Integer(22));
```
This fails in strange and confusing ways (I forgot the exact errors), apparently because painless, quite painfully, decides to unbox your Objects (why???), and then calls the wrong java method:
https://docs.oracle.com/javase/8/docs/api/java/util/List.html#remove-int-

Causing it to blow up.

You can have a really ugly work around like so:

```
script = "ctx._source.my_list.remove( ctx._source.my_list.indexOf(params.myInteger) )";
```

Which works, but is pretty terrible.

Note that this is the very first task I did with painless way back when, and it's been reliably painful for that task, and every task since then... maybe some better docs would help, that detail the behavior of the language a little better - like the java documentation...

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by jdconrad** [comment]
The documentation in Painless for 5.0 was definitely poor.  This is something that is being continually worked on, and some progress has been made starting with 5.5.  For this particular issue see (https://www.elastic.co/guide/en/elasticsearch/painless/5.5/_operators.html#dot-operator).

More specifically:

```
Method calls can be overloaded based on arity in Painless. The same method name can be re-used for different methods as long as the number of arguments differs. This differs from Java method overloading, where only the types must differ. This has an effect on some of the provided reference type methods in the Painless API. Where there are overloaded methods with the same arity for a reference type in Java, Painless chooses a single method to be provided.
```

This was done for both practical and performance implications.  The chosen method for remove in this case was remove(int).  Whether or not this was the correct decision is debatable, but the remove method you are expecting does not exist in Painless.  The API  available in Painless can be viewed here (https://www.elastic.co/guide/en/elasticsearch/painless/5.5/painless-api-reference.html).

**Comment by rjernst** [comment]
Closing as this is working as expected.

**Comment by StuAtGit** [comment]
Thanks for the docs. For anyone else that stumbles into this issue, the quote above was from this link:
https://www.elastic.co/guide/en/elasticsearch/painless/5.5/modules-scripting-painless-dispatch.html
And it's useful.

The one thing I would say would be to add a "Common Issues" or "Caveats" set of examples to the examples section of the documentation. Along with warnings stated clearly, and at the beginning, with their consequences made clear, something like:
"Be aware that, while Java methods may be exposed in the painless language, that are not called in the same way. For more details see (link to the above quote). This means that you can get unexpected results when calling overloaded functions - the function you expect to be called may not be called."
 When you're trying to get something simple working quickly, like updating a list, an example is often helpful. As are warnings stated clearly upfront.
