### ISSUE TITLE
Java TransportClient leaking

### ISSUE THREAD

**Issue by tsayao** [elastic/elasticsearch#26048]
**Elasticsearch version** 5.5.1

**Plugins installed**: []

**JVM version** (`java -version`): java version "1.8.0_131" (client)

**OS version** Windows 10 (client), Elasticsearch Docker 5.5.1 for server

**Description of the problem including expected versus actual behavior**:

TransportCliente allocate big byte arrays that does not get freed on .close(), even if garbage collect is forced.

**Steps to reproduce**:

    InetSocketTransportAddress address =
            new InetSocketTransportAddress(InetAddress.getByName(endPoint), javaPort);

    PreBuiltTransportClient preBuiltTransportClient = new PreBuiltTransportClient(settings);
    
    try (TransportClient client = preBuiltTransportClient.addTransportAddress(address)) {
        
        
    }

It leaks even if there is nothing between the transportclient and the .close().

Reported here with some details:
[https://stackoverflow.com/questions/45486310/elasticsearch-java-transportclient-leaking-byte](url)

I have debugged it and the leak seems to occur in TransportClientNodesService ->SimpleNodeSampler, not sure where as the resource freeing code seems quite complicated when it reaches Netty.

May be a Netty4 issue.

**Comment by tsayao** [comment]
Tested with TransportClient 5.0.2 and the leak does not happen.

**Comment by andy-elastic** [comment]
I was able to reproduce this in 

* 5.5.1
* 5.4.3
* 5.3.3
* 5.2.2
* 5.1.2

in these versions after the client is closed, these byte arrays make up >90% of the heap and survive gc prompts from visualvm

<img width="1331" alt="memory-5 5 1" src="https://user-images.githubusercontent.com/29205940/28951338-2815ec4a-787f-11e7-9646-1c891bc6cd87.png">

[The test program I used and the log from a run on 5.1.2](https://gist.github.com/andy-elastic/7164017fec607e800893a434c683fd49)

Versions 5.0.2 and 5.1.1 don't appear to have this behavior; in these versions byte arrays make up about 50% of heap after the client is closed, but almost all of that is released after gc prompt from visualvm

**Comment by andy-elastic** [comment]
[Log from 5.1.2 with ](https://gist.github.com/andy-elastic/870a7f9b6356a94e86716b3d038ecf18) `-Dio.netty.leakDetection.level=advanced`

**Comment by andy-elastic** [comment]
I'll assign this to @jasontedor as I see him on similar issues

**Comment by jasontedor** [comment]
It's not a leak per se, it's from the pooled allocator which would be shared across transport client instances that you create and not removed when you close a transport client instance. You can either disable the pooled allocator (start the JVM with the system property `io.netty.allocator.type` set to `unpooled`, or if you want to continue using the pooled allocator, you could look into tuning it for your use case.

**Comment by tsayao** [comment]
Thanks jason, that did the trick.

I suggest to mention it on the documentation, as for my case the client is not running on a server, it's running on a desktop application running with JavaFX, so taking 100+ mb of memory is not optimal.

Also, it's only one user per machine, so sharing instances will never happen.

Thanks.

**Comment by jasontedor** [comment]
You're welcome, sorry that you ran into the trouble.

**Comment by gaurav36** [comment]
I am also getting memory leak when i upload large number of files, This time memory leak in java rest client.

for more info:  https://discuss.elastic.co/t/memory-leak-in-elasticsearch-java-rest-client-version-5-5/99551
