### ISSUE TITLE
bulkRequest.get() get stuck

### ISSUE THREAD

**Issue by rohitnigam** [elastic/elasticsearch#26049]
Hi 
I am using java transport client 5.5.0 and I have deployed elastic search version 5.5.0 using kubernetes in google container engine. I am using BulkRequestBuilder api to do number of inserts and also waiting for their responses to come back
BulkRequestBuilder bulkRequest = client.prepareBulk();
BulkResponse bulkResponse = bulkRequest.get();
                if (bulkResponse.hasFailures()) {
...
}
I was getting response back from the elastic search and all of a sudden it has stopped ,it seems to  hang for ever.
bulkRequest.get();
Not sure why all of a sudden it has stopped working? Any help would be really appreciated.

Regards
Rohit

**Comment by andy-elastic** [comment]
Hi @rohitnigam, we use this issue tracker for bug reports and feature requests. Please use the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead for advice or questions. Thank you
