### ISSUE TITLE
Problem with the performance of aggregation 

### ISSUE THREAD

**Issue by treecy** [elastic/elasticsearch#26052]
**Elasticsearch version** (`bin/elasticsearch --version`):  
>5.4.2

**Description of the problem including expected versus actual behavior**:
We are trying to use pipeline aggregations to analyse our logs, like:
```json
"aggregations" : {
    "domain" : {
      "terms" : {
        "field" : "referrer"
      },
      "aggregations" : {
        "session_id" : {
          "terms" : { "field" : "session_id" },
          "aggregations" : {
            "gms" : {
              "max" : { "field" : "gms" }
            }
          }
        },
        "sum_gms": {
          "sum_bucket": {
        	"buckets_path": "session_id>gms"
          }
        }
      }
    }
  }
```
The amount of **session_id** buckets is about 100,000, and that made the server die.
Then we set `size: 1000` for  **session_id**,  and it took about **_1 minute_** .

**Is this time spending normal for this quantity of data?
And I don't care about the buckets of session_id, is there any way to optimize the performance?**

By the way, I know `filter_path` can reduce response , but it is useless for aggregation performance.

**Comment by danielmitterdorfer** [comment]
Hi @treecy, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!

As a hint: I think you need to bring your data into a structure that is more suitable to your use case. You could checkout the talk [Elasticsearch: Entity Centric Indexes ](https://www.youtube.com/watch?v=yBf7oeJKH2Y).
