### ISSUE TITLE
invalid role definition [null]

### ISSUE THREAD

**Issue by suckowbiz** [elastic/elasticsearch#26053]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.5.1

**Plugins installed**: [x-pack]

**JVM version** (`java -version`): Java SE Runtime 1.7.0_151-b15

**OS version** (`uname -a` if on a Unix-like system): Red Hat Enterprise Linux Server release 7.4 (Maipo)

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Add `---` in first line of <path-to-es-config>/x-pack/roles.yml to apply to convention of valid yaml file (see: http://yaml.org/)
 2. Restart elasticsearch

Expected behavior:
Elasticsearch will start without errors.

Actual behavior.
Elasticsarch fails with error. "invalid role"

**Provide logs (if relevant)**:
[2017-08-04T09:20:14,940][ERROR][o.e.x.s.a.s.FileRolesStore] [POC_loghost_node_1] invalid role definition [null] in roles file [/usr/share/elasticsearch/config/x-pack/roles.yml]. skipping role...

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch. For X-Pack, we ask that you use the X-Pack category on the [forum](https://discuss.elastic.co).
