### ISSUE TITLE
action.destructive_requires_name: true is ignored docker.elastic.co 5.5.0

### ISSUE THREAD

**Issue by rodrigongarcia** [elastic/elasticsearch#26064]
Elasticsearch Docker version: 5.5.0
Dockerfile
```
FROM docker.elastic.co/elasticsearch/elasticsearch:5.5.0
RUN rm -f /usr/share/elasticsearch/config/elasticsearch.yml
ADD config/ /usr/share/elasticsearch/config/
#Install plugin
RUN bin/elasticsearch-plugin install discovery-ec2 --batch

```
Steps to reproduce:
    elasticsearch.yml contains the property: action.destructive_requires_name: true
    Do:
`GET /_cat/indices/trackeame-rc-client_*-2017.07.31 `
Result:
```
green open trackeame-rc-client_1-2017.07.31  LGLj26U2ST-Prfk99KE9Xw 5 1 496 27   8.4mb     4mb
green open trackeame-rc-client_-1-2017.07.31 MEZ9hDXnQp2hpS9ZvOHpXg 5 1   8  0 676.8kb   336kb
green open trackeame-rc-client_7-2017.07.31  ySgPfDTRQj6EI61HRCX_nA 5 1   1  0  82.1kb    41kb
green open trackeame-rc-client_9-2017.07.31  sZmH9sRfTdSCLeL6DUh1aw 5 1  25  0   1.4mb 779.3kb
green open trackeame-rc-client_6-2017.07.31  WKdM7cgpRgmH9MFN7KXvOA 5 1  14  0   1.2mb 629.2kb
green open trackeame-rc-client_8-2017.07.31  lA6s-P9dQkisBrXOr69Whg 5 1 283 39   5.9mb   2.9mb
green open trackeame-rc-client_3-2017.07.31  ifjSIjJ8SBqTWMh8te7AMQ 5 1   1  0  90.8kb  45.4kb
green open trackeame-rc-client_2-2017.07.31  LktIFOE_TBerj23ZbeWtzg 5 1   2  0 128.9kb  64.4kb

```
`DELETE trackeame-rc-client_*-2017.07.31`

Error indicates acknowledgement of the feature

```
{
   "error": {
      "root_cause": [
         {
            "type": "illegal_argument_exception",
            "reason": "Wildcard expressions or all indices are not allowed"
         }
      ],
      "type": "illegal_argument_exception",
      "reason": "Wildcard expressions or all indices are not allowed"
   },
   "status": 400
}
```

Next no deletes:
`GET /_cat/indices/trackeame-rc-client_*-2017.07.31 ` shows all indices whitout changes.

**Comment by javanna** [comment]
hi @rodrigongarcia , I do not understand where the problem is. Did I get it right that you get back an error and no indices are deleted?

**Comment by rodrigongarcia** [comment]
Hi @javanna , I was use the property "action.destructive_requires_name: true", but elastic ignore it, i would like use wildcards for delete index.

**Comment by javanna** [comment]
@rodrigongarcia that setting set to true means that you cannot use wildcards. If you don't set it its value is false by default, meaning that you can use wildcards. I do not think that the setting is getting ignored, is it possible that you misunderstood what the setting does?

**Comment by rodrigongarcia** [comment]
@javanna that is true, I've misunderstood the documentation.
