### ISSUE TITLE
SearchContextMissingException[No search context found for id

### ISSUE THREAD

**Issue by nitishgoyal13** [elastic/elasticsearch#26074]
I am trying to migrate elasticsearch index from 1.4 to 5.1 and getting this error

shard [_na], reason [RemoteTransportException[[es-data-nqa-normal-elastic-search-4-1d][inet[/x.x.x.x:9300]][indices:data/read/search[phase/scan/scroll]]]; nested: SearchContextMissingException[No search context found for id [70501051]]; ]
shard [_na], reason [RemoteTransportException[[es-data-nqa-normal-elastic-search-4-1d][inet[/x.x.x.x:9300]][indices:data/read/search[phase/scan/scroll]]]; nested: SearchContextMissingException[No search context found for id [70501053]]; ]
shard [_na], reason [RemoteTransportException[[es-data-nqa-normal-elastic-search-6-1d][inet[/x.x.x.x:9300]][indices:data/read/search[phase/scan/scroll]]]; nested: SearchContextMissingException[No search context found for id [4620964]]; ]
shard [_na], reason [RemoteTransportException[[es-data-nqa-normal-elastic-search-2-1d][inet[/x.x.x.x:9300]][indices:data/read/search[phase/scan/scroll]]]; nested: SearchContextMissingException[No search context found for id [150346352]]; ]

at com.spr.search.repository.elasticsearch.ESScan$ESScanIterator.throwOnShardFailures(ESScan.java:167)
at com.spr.search.repository.elasticsearch.ESScan$ESScanIterator.doNext(ESScan.java:132)
at com.spr.search.repository.elasticsearch.ESScan$ESScanIterator.next(ESScan.java:123)
at com.spr.search.repository.elasticsearch.ESScan$ESScanIterator.next(ESScan.java:73)
at

**Comment by tvernum** [comment]
Please ask this question on our [discuss forum](https://discuss.elastic.co/) where we can provide better support.
Elastic uses GitHub issues for confirmed bugs and feature requests which have been discussed on the forums.

Thank you.
