### ISSUE TITLE
packetbeat.sh won't work if the filename contains spaces

### ISSUE THREAD

**Issue by gavinspearhead** [elastic/elasticsearch#26073]
**Elasticsearch version** (`bin/elasticsearch --version`):
packetbeat version 5.5.1 (amd64), libbeat 5.5.1

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.17.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux urd 4.10.0-30-generic #34-Ubuntu SMP Mon Jul 31 19:38:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

packetbeat.sh won't work if the filename contains spaces. This is due to the $@ in the bash script. Quoting does not help.

**Steps to reproduce**:
sudo packetbeat.sh -e -c /etc/packetbeat/packetbeat.yml -t -I DNS01\ -\ C3-.pcap -d "publish"

2017/08/06 22:07:56.836114 beat.go:285: INFO Home path: [/usr/share/packetbeat] Config path: [/etc/packetbeat] Data path: [/var/lib/packetbeat] Logs path: [/var/log/packetbeat]
2017/08/06 22:07:56.836462 beat.go:186: INFO Setup Beat: packetbeat; Version: 5.5.1
2017/08/06 22:07:56.836821 output.go:258: INFO Loading template enabled. Reading template file: /etc/packetbeat/packetbeat.template.json
2017/08/06 22:07:56.840314 output.go:269: INFO Loading template enabled for Elasticsearch 2.x. Reading template file: /etc/packetbeat/packetbeat.template-es2x.json
2017/08/06 22:07:56.841979 output.go:281: INFO Loading template enabled for Elasticsearch 6.x. Reading template file: /etc/packetbeat/packetbeat.template-es6x.json
2017/08/06 22:07:56.843492 client.go:128: INFO Elasticsearch url: http://localhost:9200
2017/08/06 22:07:56.843762 outputs.go:108: INFO Activated elasticsearch as output plugin.
2017/08/06 22:07:56.844013 publish.go:295: INFO Publisher name: urd
2017/08/06 22:07:56.860287 metrics.go:23: INFO Metrics logging every 30s
2017/08/06 22:07:56.884196 async.go:63: INFO Flush Interval set to: 1s
2017/08/06 22:07:56.884449 async.go:64: INFO Max Bulk Size set to: 50
2017/08/06 22:07:56.884864 procs.go:79: INFO Process matching disabled
2017/08/06 22:07:56.885229 protos.go:89: INFO registered protocol plugin: memcache
2017/08/06 22:07:56.886038 protos.go:89: INFO registered protocol plugin: mongodb
2017/08/06 22:07:56.886211 protos.go:89: INFO registered protocol plugin: pgsql
2017/08/06 22:07:56.886365 protos.go:89: INFO registered protocol plugin: thrift
2017/08/06 22:07:56.888078 protos.go:89: INFO registered protocol plugin: amqp
2017/08/06 22:07:56.888274 protos.go:89: INFO registered protocol plugin: dns
2017/08/06 22:07:56.888432 protos.go:89: INFO registered protocol plugin: mysql
2017/08/06 22:07:56.888595 protos.go:89: INFO registered protocol plugin: nfs
2017/08/06 22:07:56.888749 protos.go:89: INFO registered protocol plugin: redis
2017/08/06 22:07:56.888915 protos.go:89: INFO registered protocol plugin: cassandra
2017/08/06 22:07:56.889083 protos.go:89: INFO registered protocol plugin: http
2017/08/06 22:07:56.891885 beat.go:339: CRIT Exiting: Initializing sniffer failed: Error creating sniffer: DNS01: No such file or directory
Exiting: Initializing sniffer failed: Error creating sniffer: DNS01: No such file or directory

**Provide logs (if relevant)**:

**Comment by dadoonet** [comment]
Wrong repository.
Could you report it at https://github.com/elastic/beats/issues ?

Thanks!
