### ISSUE TITLE
Node blocked due to malformed JSON on _count API

### ISSUE THREAD

**Issue by Matthour** [elastic/elasticsearch#26083]
**Elasticsearch version**:
5.5.1

**Plugins installed**:
ingest-geoip, ingest-user-agent, x-pack

**JVM version**:
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-b16)
OpenJDK 64-Bit Server VM (build 25.141-b16, mixed mode)

**OS version**:
Linux e012087cca9f 4.9.36-moby #1 SMP Wed Jul 12 15:29:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
_count API doesn't return a 400 status "parsing_exception" error when sending data matching `".*"` regex pattern.

**Steps to reproduce**:
```
docker run -p 9200:9200 -e "http.host=0.0.0.0" -e "transport.host=127.0.0.1" -d docker.elastic.co/elasticsearch/elasticsearch:5.5.1

curl -XGET -u elastic:changeme -H 'Content-Type: application/json' http://localhost:9200/*/_count -d '""'

# (don't forget to kill the container to save your CPU :-)
```

FYI:
- _search works with the same data (`""`) returning a 400 status "parsing_exception" error
- _count returns same error on data like `a`, `"`, etc. but the problem occurs with data matching `".*"` regex pattern

**Comment by cbuescher** [comment]
@Matthour this is indeed interesting, I just tried it on 5.2.2 and there `_count` and `_search` still give the same respone (a 400 with "parse_exception") when the request body is `""`.
Starting with 5.3.0, `_search` still returns 400 ("parse_exception") but `_count` doesn't return.
