### ISSUE TITLE
minimum_should_match not working

### ISSUE THREAD

**Issue by cbaird1911** [elastic/elasticsearch#26103]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.5.1

**Plugins installed**: [icu plugin]

**JVM version** (`java -version`): 1.8.0_131

**OS version** (`uname -a` if on a Unix-like system): Linux carl 4.11.12-200.fc25.x86_64 #1 SMP Fri Jul 21 16:41:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
minimum_should_match isn't working at all when I'm trying to pare down unwanted results while using ngrams. I believe it is a bug because I even followed all of the steps here: https://www.elastic.co/guide/en/elasticsearch/guide/master/ngrams-compound-words.html and it still doesn't work. I used the sample data and their sample queries too.

**Steps to reproduce**:

Applying a query like the one in the link above:
```
GET /my_index/my_type/_search
{
    "query": {
        "match": {
            "text": {
                "query":                "Gesundheit",
                "minimum_should_match": "80%"
            }
        }
    }
}
```
returns the same results with minimum_should_match that it does without it.

Am I missing something? Did something change with minimum_should_match in 5.x, or is this a bug?

**Comment by nik9000** [comment]
@polyfractal, since this is from the guide, would you like to have a look and see if it is a change that'll have to make it's way into the guide?

**Comment by jimczi** [comment]
I opened an issue for this some time ago:
https://github.com/elastic/elasticsearch-definitive-guide/issues/619
The behavior has changed in 5.x, the `ngram` token filter assigns the same position to all ngrams which makes the query parser think that the different ngrams are synonyms of each other. The solution is to use an `ngram` tokenizer instead.
