### ISSUE TITLE
Unexpected behavior using Boolean expressions with minimum_should_match in a query_string query

### ISSUE THREAD

**Issue by jonben-fw** [elastic/elasticsearch#26110]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):5.5.1

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_66

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:

I get the impression that Boolean expressions in the query are ignored/not working properly in a query_string query when using minimum_should_match. I would have expected that a query_string query using minimum_should_match would respect the Boolean expression in the query like it does if you use default_operator OR/AND. If I for example have minimum_should_match=100% I would expect the same behavior as if I set default_operator=AND (the minimum_should_match i would like to be able to use would look more like "3<80%", but I get the same behavior there).

Is this a bug, or is minimum_should_match not intended to work with Boolean expressions like this?

**Steps to reproduce**:

 1. Create index/populate index:
```
POST _bulk
{"index":{"_index":"index1","_type":"type1","_id":"1"}}
{"field1":"aaa"}
{"index":{"_index":"index1","_type":"type1","_id":"2"}}
{"field1":"bbb"}
```
 2. Query index using a query_string query with minimum_should_match, I get 0 hits
```
GET index1/_search
{
  "query": {
    "query_string": {
      "query": "(bbb OR aaa)",
      "minimum_should_match": "100%", 
      "fields": ["field1"]
    }
  }
}
```
 3. Query index using a query_string query with default_operator AND, I get 2 hits
```
GET index1/_search
{
  "query": {
    "query_string": {
      "query": "(bbb OR aaa)",
      "default_operator": "AND", 
      "fields": ["field1"]
    }
  }
}
```

**Comment by jimczi** [comment]
@jonben-fw we reserve GitHub for bug reports and feature requests but provides a Discourse forum and IRC channels for general questions like this:
https://discuss.elastic.co/c/elasticsearch
To answer your question, `minimum_should_match` only applies to optional clauses so doing `bbb OR aaa` with `minimum_should_match: 100%` is equivalent to `bbb AND aaa`. The default operator in your example is never applied since you provide the boolean operator directly in your query (`AND`, `OR`).

**Comment by jonben-fw** [comment]
Ok, then I misunderstood how minimum_should_match is supposed to work, thank you for your answer and sorry for reporting this as a bug.
