### ISSUE TITLE
[docs] Clarify remote reindex api documentation to indicate that slicing isn't available

### ISSUE THREAD

**Issue by bczifra** [elastic/elasticsearch#26114]
The Reindex from Remote [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#reindex-from-remote) doesn't make note of the fact that Reindex from Remote doesn't support slicing, despite the fact that Reindexing locally [does support it](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex-automatic-slice).  See https://github.com/elastic/elasticsearch/pull/20767 for more details.

**Comment by insukcho** [comment]
I think this `NOTE` should really also show up in the slicing section, not just the remote section. Very easy to miss. Could you please in slicing section for both side(manual & auto)?

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving this open as the following comment is still relevant:
https://github.com/elastic/elasticsearch/issues/26114#issuecomment-390111396

**Comment by jrodewig** [comment]
@insukcho  Closing this issue as #47483 reformatted this page, making the note more prominent.

Please re-open if you feel further action is needed. Thanks!

**Comment by insukcho** [comment]
Thank you very much @jrodewig !!!

**Comment by iwinux** [comment]
Hi,

Would you mind explaining *why* slicing is not supported for remote reindex?
