### ISSUE TITLE
[CI] InternalAggregationTestCase testEqualsAndHashcode fails

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#26121]
something was mutated in the objects for these tests causing inequality

REPRODUCE WITH: 
```
gradle :core:test \
  -Dtests.seed=67E9336A745B3AFF \
  -Dtests.class=org.elasticsearch.search.aggregations.metrics.geobounds.InternalGeoBoundsTests \
  -Dtests.method="testEqualsAndHashcode" \
  -Dtests.security.manager=true \
  -Dtests.locale=th-TH \
  -Dtests.timezone=Antarctica/Troll
```

```
gradle :core:test \
  -Dtests.seed=C19790BBC0EDF910 \
  -Dtests.class=org.elasticsearch.search.aggregations.metrics.geocentroid.InternalGeoCentroidTests \
  -Dtests.method="testEqualsAndHashcode" \
  -Dtests.security.manager=true \
  -Dtests.locale=nn-NO \
  -Dtests.timezone=America/Recife
```

```
gradle :core:test \
  -Dtests.seed=52073064D46FE724 \
  -Dtests.class=org.elasticsearch.search.aggregations.metrics.scripted.InternalScriptedMetricTests \
  -Dtests.method="testEqualsAndHashcode" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-CH \
  -Dtests.timezone=America/Toronto
```

geobounds:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/1045/console

geocentroid:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=amazon/37/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/213/console

InternalScriptedMetric:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.0+multijob-unix-compatibility/os=ubuntu/53/console

**Comment by colings86** [comment]
The `InternalGeoBoundsTests` issue is fixed in https://github.com/elastic/elasticsearch/commit/566992d2a159ef0b9b1ce7cac0801b0c8e4e929e. I'll work on a fix for the other two tests now
