### ISSUE TITLE
Histogram Aggregation for values of long type

### ISSUE THREAD

**Issue by mhko** [elastic/elasticsearch#26122]
This is very similar to https://github.com/elastic/elasticsearch/issues/9545 but on histogram aggregation.

1. We have a field of 64-bit long type in our index. 

2. Suppose that I add a doc with a value of 9223372036854775807 for the field. 

3. With ES 5.x, a histogram aggregation query returns  
`   "aggregations":{
      "longCount":{
         "buckets":[
            {
               "key":9.223372036854776E18,
               "doc_count":1
            }
         ]
      }
   }
`
Whereas, with ES 1.7, below is returned. 
`
   "aggregations":{
      "longCount":{
         "buckets":[
            {
               "key":9223372036854775800,
               "doc_count":1
            }
         ]
      }
   }
`
This issues look similar to https://github.com/elastic/elasticsearch/issues/9545 where a precision problem was reported. I see in HistogramAggregationBuilder.java that double type is used for internal computations. Are these the same issue? Do you plan to fix (or document) it for histogram aggregation? 

Further, I noticed that the keys in the response are of double type regardless of how the type was configured for the field. The behavior seems to have changed from 1.x as well. Is that documented? 

Thanks-

**Comment by jpountz** [comment]
This is an unintended side-effect of the fact that we now support fractional intervals and values. We just discussed it in FixitFriday and agreed to keep the behaviour as-is but better document that we run the aggregation on the double representation of values, which might incur accuracy loss with long values that are greater than 2^53.

**Comment by bhupenchn** [comment]
From what I understand, the rectification is to update the documentation? 
I would like to take this up, as a starting point to contribute on elasticsearch.

**Comment by jimczi** [comment]
@bhupenchn your understanding is correct, feel free to send a PR and we'll review it.

**Comment by bhupenchn** [comment]
Thanks, will do the necessary.

**Comment by bhupenchn** [comment]
@jimczi can you verify if the changes I made are done in relevant files? If I have missed out some do let me know.

**Comment by markharwood** [comment]
cc @elastic/es-search-aggs
