### ISSUE TITLE
Received message from unsupported version: [2.0.0] minimal compatible version is: [5.0.0]

### ISSUE THREAD

**Issue by quanbiao** [elastic/elasticsearch#26134]
hi, i install es5.5.0 in centos6.6 and java8, it start success,but the log output follow:
java.lang.IllegalStateException: Received message from unsupported version: [2.0.0] minimal compatible version is: [5.0.0]
can you help me?

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

Here you have something else running an old version.
