### ISSUE TITLE
Run error after Elasticsearch 6.0.0-Beta1 MSI install

### ISSUE THREAD

**Issue by net1pei** [elastic/elasticsearch#26135]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.0.0-Beta1

**Plugins installed**: 
No

**JVM version** (`java -version`):
1.8.0_144

**OS version** (`uname -a` if on a Unix-like system):
Win7-SP1, 64 bit

**Description of the problem including expected versus actual behavior**:
1.  Install Elasticsearch 6.0.0-Beta1 MSI, URL:  https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0-beta1.msi

2. After install the msi  in Windows7-64 bit OS succesfully, when run in DOS, then get an error:

C:\Program Files\Elastic\Elasticsearch\bin>.\elasticsearch.exe
ERROR: the system property [es.path.conf] must be set

c:\Program Files\Elastic\Elasticsearch\bin>

3. I check the env variables, 
ES_CONFIG=E:\Elastic\Elasticsearch\config
ES_HOME=C:\Program Files\Elastic\Elasticsearch\

then I try with -E path.conf option, but the error still there: 
C:\Program Files\Elastic\Elasticsearch\bin>.\elasticsearch.exe -E path.conf=%ES_CONFIG%
ERROR: the system property [es.path.conf] must be set

**Comment by Mpdreamz** [comment]
It looks like https://github.com/elastic/elasticsearch/pull/25943 bit us here afterall, only spotted this issue yesterday. cc @elastic/microsoft 

Our integration CI tests had (10) pending commits and did not not run, even if it did it currently tests a fixed list of versions we need to inlclude latest snapshot here as well.

**Comment by net1pei** [comment]
@Mpdreamz Thanks。
I think the env variable name of ES_CONFIG is bettter than CONF_DATA, expect the new msi file.

**Comment by net1pei** [comment]
The CONF_DIR name is generic, it can be used for ElasticSearch, also for AlasticSearch, BlasticFind etc, but the ES_CONFIG is sepcific and frankly about ES.  I'm curious why select CONF_DIR?

**Comment by Mpdreamz** [comment]
Opened https://github.com/elastic/windows-installers/pull/70 to address this. Many thanks for reporting this one @net1pei 👍

**Comment by jasontedor** [comment]
@Mpdreamz Please coordinate with me. It's been on my mind that we should change the name of the environment variable for this but I've not been wanting to for backwards breaking reasons. Yet, I still think we should so let's think about doing it now before it gets baked in all over the place (as it's taken on increased importance from the past). I'm out until Monday of week, can we sync then?

**Comment by Mpdreamz** [comment]
@jasontedor absolutely, https://github.com/elastic/windows-installers/pull/70 brings us inline with main ES repos but changing the env var name and supporting a flag on the command line on Windows is something I would love to discuss. 

I'll be in Australian timezone all of next week, I'll send out some suggested times today.

**Comment by jasontedor** [comment]
Sounds good. I'm leaving the Japan timezone unfortunately for US East Coast timezone so I know it will be hard to sync. I opened an issue for discussing this, maybe going async there would be best given the time zone mismatch we will have. See: #26154

**Comment by Mpdreamz** [comment]
Opened https://github.com/elastic/elasticsearch/issues/26158 to discuss the removal of the command line switches for `path.home` and `path.conf`. Enjoy :japan: :jp: 🙂
