### ISSUE TITLE
Repo url is broken in Debian 8

### ISSUE THREAD

**Issue by jurim76** [elastic/elasticsearch#26140]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.5.1

**Plugins installed**: []

**JVM version** (`java -version`):  openjdk version "1.8.0_141"

**OS version** (`uname -a` if on a Unix-like system): Linux ld4-tda-log-04 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.  Add repo according to manual https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html
 2. Run apt-get update
 3. apt-get failed with error

Err https://artifacts.elastic.co stable/main amd64 Packages
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Fetched 84.3 kB in 4s (18.1 kB/s)
W: Failed to fetch https://artifacts.elastic.co/packages/5.x/apt/dists/stable/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Provide logs (if relevant)**:
curl -v  https://artifacts.elastic.co/packages/5.x/apt/dists/stable/main/binary-amd64/Packages
*   Trying 23.21.118.61...
* TCP_NODELAY set
* Connected to artifacts.elastic.co (23.21.118.61) port 443 (#0)
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* Curl_http_done: called premature == 0
* Closing connection 0
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs

**Comment by jakommo** [comment]
@jurim76 I just tried and the curl works fine for me:

```
% curl -v https://artifacts.elastic.co/packages/5.x/apt/dists/stable/main/binary-amd64/Packages       
*   Trying 184.73.156.41...
* Connected to artifacts.elastic.co (184.73.156.41) port 443 (#0)
* found 174 certificates in /etc/ssl/certs/ca-certificates.crt
* found 704 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: *.elastic.co (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: C=US,ST=California,L=Mountain View,O=Elasticsearch\, Inc.,CN=*.elastic.co
* 	 start date: Mon, 18 Jan 2016 00:00:00 GMT
* 	 expire date: Wed, 27 Mar 2019 12:00:00 GMT
* 	 issuer: C=US,O=DigiCert Inc,CN=DigiCert SHA2 Secure Server CA
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET /packages/5.x/apt/dists/stable/main/binary-amd64/Packages HTTP/1.1
> Host: artifacts.elastic.co
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Type: application/octet-stream
< Date: Thu, 10 Aug 2017 12:53:27 GMT
< ETag: "d567cc2b5b20edb271bcd12236e160b5"
< Last-Modified: Tue, 25 Jul 2017 14:43:27 GMT
< Server: nginx/1.4.6 (Ubuntu)
< x-amz-id-2: oEPmowZqGjmHuR/r6XoyrCpn0p42dkF+ymcqu0i4CM9c25srR9pAqSAzZj3mJp89hi0hUaNCDVo=
< x-amz-request-id: D777E22BA3A8874F
< x-amz-version-id: s5g43aRO07mq6_pnyM2D3cDrhy5NIqLp
< x-ngx-hostname: www03
< Content-Length: 87442
< Connection: keep-alive
< 
Package: elasticsearch
Priority: optional
Section: web
Installed-Size: 36433
Maintainer: Elasticsearch Team <info@elastic.co>
Architecture: all
Source: elasticsearch
Version: 5.5.1
Depends: libc6, adduser, bash
Filename: pool/main/e/elasticsearch/elasticsearch-5.5.1.deb
Size: 33367126
MD5sum: 88d3a4d230b21639d4b73d770534b271
SHA1: d6beceeb93ade6c3bc18b76a7f0e365dd95f6f52
SHA256: 84bf72e6103ec8c06ac1a75696b181c8581b10cad2899e7bae2e66b7a84cb485
SHA512: d35d3c28ce98396adcf5d0d79be8015219678b1fef3d08c9034f892b6d871053ce4fb600d33fd39d11d83baa5e710294cfd6d48bd969edc86d23cb3a3bb349f2
Description: Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
 Elasticsearch subproject :distribution:deb
Homepage: https://www.elastic.co/

Package: elasticsearch
Priority: optional
Section: web
...
```

Maybe there was just a temporary glitch? Can you try again?

**Comment by jurim76** [comment]
Looks like proxy issue. Closed
