### ISSUE TITLE
problem with large-ish ES clusters on 5.4.1 that we are not able to reproduce on 2.x

### ISSUE THREAD

**Issue by buildlackey** [elastic/elasticsearch#26152]
PLUGINS
-------
/apps/elasticsearch $ sudo bin/elasticsearch-plugin list
analysis-icu
analysis-kuromoji
mapper-murmur3
raigad-discovery
repository-s3

JAVA VERSION
-------------
  "1.8.0_131"

OS
--

uname -a
Linux es-mcelogs2-useast1-data-useast1e-i-08eda1e5c789e6467 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

DESCRIPTION
-----------

We are seeing a problem with large-ish ES clusters on 5.4.1 that we are not able to reproduce 
on ES 2.4.1. This is triggered by:

    creating an index template with 120 shards / 2 replicas

    indexing one new document that conforms to the pattern specified in the above template.

After we perform the indexing operation we get stuck 'initializing shards'.. 
typically three shards stuck in this state for a very long time (hours.)

To reproduce the issue I am uploading the script we use to:

    - delete the target index we will create (if it is there)
    - create a template that will match against the to-be-created index 

REPRO STEPS
------------

The steps to trigger the problem are as follows:

1)  save attached script to ~/bugReport.sh

2)  Invoke script to create new template for 'ndbench_index'
    #
    host=foo.com        # or whatever is appropriate
    port=9200           # or whatever is appropriate
    shards=120

    bash ~/bugReport.sh $host   $shards  text  default  $port

3)  Write simple document  to 'ndbench_index'
    #
    curl -X PUT http://$host:$port/ndbench_index/junktype/someId    \
            -H 'Content-Type: application/json' -d '{ "foo": "bar" }'

at this point you should see your cluster state go yellow, and you will see some shards 
stuck in the 'initializing' state.

If you delete the index the cluster state will go back to 'green'

While cluster is yellow, If you use /_cat/shards to find the nodes that host the shards that are initializing, and then go to one of the nodes, 
you should see something like this in the log:

    [2017-08-03T01:41:10,002][WARN ][o.e.c.NodeConnectionsService] [us-east-1c.i-dummy1] failed to connect to node {us-east-1d.i-dummy2}{LXjLhNreS76NnPmgMwfedQ}{yrmdDOgzSzSZ_oQ5B-ETNw}{xxx.xx.81.194}{xxx.xx.81.194:7102}{rack_id=us-east-1d} (tried [1] times)
    org.elasticsearch.transport.ConnectTransportException: [us-east-1d.i-dummy2][xxx.xx.81.194:7102] general node connection failure
            at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:559) ~[elasticsearch-5.4.1.jar:5.4.1]
            at org.elasticsearch.cluster.NodeConnectionsService.validateAndConnectIfNeeded(NodeConnectionsService.java:154) [elasticsearch-5.4.1.jar:5.4.1]
            at org.elasticsearch.cluster.NodeConnectionsService$1.doRun(NodeConnectionsService.java:107) [elasticsearch-5.4.1.jar:5.4.1]
                <snip>
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
            at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
    Caused by: java.lang.IllegalStateException: handshake failed, channel already closed
            at org.elasticsearch.transport.TcpTransport.executeHandshake(TcpTransport.java:1589) ~[elasticsearch-5.4.1.jar:5.4.1]
            at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:541) ~[elasticsearch-5.4.1.jar:5.4.1]
        ... 10 more

Final notes: 

    - we have not been able to reproduce this problem when we shrink the cluster size to something 
      smaller (we tried 45 nodes.. no issue occured -- even with 360 shards)

    - using the script you can vary the number of shards in the index template 
        -we found that with a 120 node cluster when we specified 36 shards, 
          the index was created with no issue. Once we moved past that (e.g., 37 shards)
         the problem started surfacing.

    - we also found no issues when we followed the same procedure on ES 2.4.1

        when using ES 2.x you would follow the same steps, but you invoke the script like this:

            bash ~/bugReport.sh $hostPort $shards  string  default 

[bugReport.sh.txt](https://github.com/elastic/elasticsearch/files/1216718/bugReport.sh.txt)

**Comment by ywelsch** [comment]
We need more information here, in particular the full configuration of the nodes and master logs. Can you try to run the same scenario with logging level of `cluster.service` set to DEBUG? The log output you have shown here is not related to running `/_cat/shards`, the stack trace shows that this is an internal operation that is periodically run (by default every 10 seconds) to check network connections.

**Comment by buildlackey** [comment]
Hi there. We believe we have found the source of the bug.  We had max number of file descriptors set to 300K, and in our performance monitoring dashboards a colleague noticed that we were hitting that threshold very close to the same time we were seeing the problem that I reported in our logs ("handshake failed, channel already closed...etc.").     

Our work-around was to increase the max number of open file descriptors (we picked 700K), and the problem no longer occurs for us. 

You might want to chalk this up to a configuration problem, but it might also be valuable to see if there is some low level exception about 'max number of file descriptors reached' that is being swallowed in the code. You may also wish to update your release notes about this behavior, as 2.x didn't seem to hit this file descriptor limit as quickly as 5.x does. 


Thank you for your help on this.  For now, we are able to proceed with large clusters.

**Comment by buildlackey** [comment]
Hi, @ywelsch !  - unfortunately, the fix we thought would work did not quite do it. Still get stuck in initializing shards.   my colleague and i will work on getting the information you requested (hopefully by tomorrow).  /thnx

**Comment by buildlackey** [comment]
Hi.  This is not yet the info you requested.(working on that) . but other observations that might be helpful.


**Not stuck forever:**

 * the cluster will go green if you wait long enough (an hour or so, sometimes just 10 minutes)
      * but this seems very unreasonable for an index that consists of only one small document.

**Not related to handhake exception:**

 * i cannot correlate this bug with the stack trace that includes IllegalstateException...handshake.
    * that 'handshake' exception occurs on startup of our cluster... but does not occur when we 
      create the index and while the shards begin initializing.

**Usually the same nodes are slow, but terminating them causes a new group to be slow:**

* the nodes that are slow in initializing their shards are almost always the same ones.
      * dmesg log looks clean for these nodes.
      * even though two nodes continually show up as "the slow ones", when we terminate these 
        nodes (the Amazon AMI isntances)  we still have the slow shards issue when new 
        nodes are allocated to take the  place  of the terminated nodes in the auto scaling group.
            * the next round of occurrences of 'shards stuck in initalizing state' (after termination) 
               again seems to involve at least one node over and over: with each run of the test
               this   node (not one of the original set that was stuck) will always be one of the stuck ones.

**Comment by buildlackey** [comment]
Hi. one of my colleagues filed a bug on this same issue, so we would like to close this bug as a duplicate of this one -> https://github.com/elastic/elasticsearch/issues/26293
