### ISSUE TITLE
Rename CONF_DIR to ES_PATH_CONF

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#26154]
The environment variable `CONF_DIR` was previously inconsistently used in our packaging to customize the location of Elasticsearch configuration files. The importance of this environment variable has increased starting in 6.0.0 as it's now used consistently to ensure Elasticsearch and all secondary scripts (e.g., `elasticsearch-keystore`) all use the same configuration. The name `CONF_DIR` is there for legacy reasons yet it's too generic. This issue proposes renaming `CONF_DIR` to `ES_PATH_CONF` for 6.0.0. This would be a breaking change but it's a smaller break now than it would be in the future after this environment variable becomes baked-in through the ecosystem.

**Comment by danielmitterdorfer** [comment]
We've discussed it in Fix-It Friday and the change and the proposed name both make sense.

**Comment by jasontedor** [comment]
> I understand the reasoning for calling it ES_PATH_CONF (to match the former --path.conf and/or path.conf settings)

A primary reason is to match the naming convention for the existing settings: `path.data`, `path.home`, and `path.logs` and to match the name of the system property: `es.path.conf` which was also chosen to match these settings albeit for the `es.` prefix.

> I also think using "path" is confusing, as we used to have the env var for the ES config file, so I would keep "dir" in the name.

I'm not sure what you mean about "path" being confusing, "path" is a perfectly reasonable synonym for "directory", shortened to "dir".

> as we used to have the env var for the ES config file

I'm not sure what you're referring to here?

Given the above, I feel strongly that `ES_PATH_CONF` is the right name.

**Comment by rjernst** [comment]
>> as we used to have the env var for the ES config file

> I'm not sure what you're referring to here?

I was referring to the `CONF_FILE` env var that used to be supported, long long ago: #13772

**Comment by jasontedor** [comment]
> I was referring to the `CONF_FILE` env var that used to be supported, long long ago: #13772

That has not existed since 1.x, I don't think it should factor in here at all.
