### ISSUE TITLE
TermsAggregationBuilder#size throws IllegalArgumentException with 0 as an argument value

### ISSUE THREAD

**Issue by jama707** [elastic/elasticsearch#26150]
**Elasticsearch version** : 5.4

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): All

**Description of the problem including expected versus actual behavior**: ES Guide here: [Returning only aggregation results](https://www.elastic.co/guide/en/elasticsearch/reference/current/returning-only-agg-results.html#returning-only-agg-results) says I can set 0 to size. But when I try to set size to my `TermsAggregationBuilder`, it's throwing `IllegalArgumentException("[size] must be greater than 0. Found [" + size + "] in [" + name + "]")`

**Steps to reproduce**: just call `.aggregate( terms("age").field("age").size(0) )`

Is it inconsistent documentation or method should not have restricted to 0 size?

**Comment by jama707** [comment]
My bad -

**Comment by talevy** [comment]
Hi @jama707, The way the documentation references `size` is definitely ambiguous. The `size` that 
this page is referring to is that of the search's — not the aggregation.

Here is the `size` that the aggregation docs are referring to: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html#_parameters_4 (the size parameter). 

Your reproduction step suggests you've updated the [term's aggregation `size`](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_size).

If you set size on the whole query context, not that specific `age` aggregation, all should work!

**Comment by jama707** [comment]
I got it now. Thanks @talevy!
