### ISSUE TITLE
Bring back command line switches for config and home directory

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#26158]
I would like to open this for discussion but happy to fall in line with previous discussions. I realize I am not fully informed on the history around these changes.

We removed support for specifying `-E path.conf` and `--path.conf` in favor of setting `CONF_DIR` as per https://github.com/elastic/elasticsearch/pull/25943

On windows this leads to users having to specify the following on the command line:

```shell
(SET "CONF_DIR=x") & bin\elasticsearch
```

The parenthesis are necessary to control trailing whitespace and the quotes to deal with spaces in the path. Whats worse is that that SET command is viral for the current session. Windows lacks something analogous to:

```shell
env CONF_DIR=x bin/elasticsearch
```

To control the process's environment variables only. I would love to bring them back as command line switches since its such a common use case to specify these. (Which might be something we are actively discouraging?)

**Comment by s1monw** [comment]
@jasontedor I would be curious about your opinon here. I don't like to have more than one way of specifying personally and our current solution is more generic. I wonder if you have an idea to improve

**Comment by s1monw** [comment]
> I think we should leave this as-is.

agreed
