### ISSUE TITLE
Weird calculation of the percentile ranks

### ISSUE THREAD

**Issue by kirolos-kaldas** [elastic/elasticsearch#26156]
Hi,

I have the following list of data:
[22,22,25,26,2730,31,31,32,32,32,36,36,36,38,25,26,27,38,40]

when I use the following query to get the percentile ranks for the given values
{
"aggregations" : {
"agg" : {
"percentile_ranks" : {
"field" : "score",
"values" : [40, 40.5]
}
}
}
}

I get the following:
{
"took" : 5,
"timed_out" : false,
"_shards" : {
"total" : 5,
"successful" : 5,
"failed" : 0
},
"hits" : {
"total" : 19,
"max_score" : 1.0,
"hits" : [ ]
},
"aggregations" : {
"agg" : {
"values" : {
"40": 91.176,
"40.5": 92.647
}
}
}
}

40 is the highest value , so shouldn't 40.5 be 100?
is this value returned from elasticsearch correct or is this a bug?
If its correct then, how is the percentile rank calculated to give you this value?

**Comment by markharwood** [comment]
The docs for percentiles and percentile ranks note that these are approximate and give [details behind this approach](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-aggregation.html#search-aggregations-metrics-percentile-aggregation-approximation).

You can always add a "max" aggregation to your request which will be accurate.
