### ISSUE TITLE
Recent change to backticks in bin/elasticsearch causes incorrect parameter parsing warning

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#26175]
When invoking `bin/elasticsearch` with both `-E` parameters and the `-d` option, the following warning is given:

```
~/scratch/elasticsearch-7.0.0-alpha1-SNAPSHOT 
» bin/elasticsearch -E node.name=foo -d
bin/elasticsearch: line 30: [: node.name=foo: unary operator expected
```

Elasticsearch *does* start successfully in the background, and the `node.name` is "foo" as intended, however, the line:

```
if [ ! `echo $* | grep -E '(^-d |-d$| -d |--daemonize$|--daemonize )'` ]; then
```

Throws the unary operator expected warning.

**Comment by dakrone** [comment]
@jasontedor pinging you on this since I believe the backtick change was something you recently changed in ad4dbbf1a61680da70f22f7f5d6f0566d273829a, I think that particular line change may need to be reverted?

**Comment by jasontedor** [comment]
This duplicates an existing issue.

**Comment by jasontedor** [comment]
Duplicates #26080

**Comment by dakrone** [comment]
Thanks Jason, I searched but apparently didn't see that one

**Comment by jasontedor** [comment]
No worries, I'll put up a fix no later than early next week.
