### ISSUE TITLE
Does elasticsearch have a plan to develop a graph database engine?

### ISSUE THREAD

**Issue by Aoseala** [elastic/elasticsearch#26181]
The graph database is now very hot, and if the elasticsearch support graph database is similar to neo4j, it will be unbeatable.

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
