### ISSUE TITLE
Time Range timestamp raw

### ISSUE THREAD

**Issue by mza97** [elastic/elasticsearch#26199]
Hi,

Is it possible to do a time range with a timestamp like this (I can't use ``` now ```)?:

```
{ "range": { "@timestamp": { "from": "2017-08-14T11:56:02-5m","to": "2017-08-14T11:56:02"}}}
```

Regards

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
