### ISSUE TITLE
es2.3.4 -> es5.5.0 upgrade, all shards is unassigned

### ISSUE THREAD

**Issue by EnglishVillage** [elastic/elasticsearch#26195]
**Describe the feature**: 
es2.3.4 -> es5.5.0 upgrade,shutdown old cluster and reboot new cluster, new cluster is running, but all shards is unassigned.

**Elasticsearch version** (`bin/elasticsearch --version`):
es2.3.4->es5.5.0
**Plugins installed**: []
es2.3.4:delete-by-query, head, jcseg, kopf, license, marvel-agent, sql
es5.5.0:sql, head, cerebro
**JVM version** (`java -version`):
java version "1.8.0_111"
**OS version** (`uname -a` if on a Unix-like system):
centos7
Linux esnode2 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
[log.txt](https://github.com/elastic/elasticsearch/files/1221897/log.txt)

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
