### ISSUE TITLE
/_msearch with two 'should' queries is valid only for first query 

### ISSUE THREAD

**Issue by azr** [elastic/elasticsearch#26205]
**Elasticsearch version** (`bin/elasticsearch --version`):

quay.io/pires/docker-elasticsearch-kubernetes:5.4.3

[Dockerfile](https://quay.io/repository/pires/docker-elasticsearch-kubernetes/image/65995161c2615e1ac06bf7871a7b50e1992003ebc1110a64835e3c807dba7bdb)

**Plugins installed**: []

**JVM version** (`java -version`): openjdk8-jre

**Description of the problem including expected versus actual behavior**:

When I bulk search using /_msearch and send two requests, the second request just replies with ordered list of items whereas first one is correct.
Also if I switch order of requests.
Only difference in requests is type filter.

**Steps to reproduce**:

1.

Insert games and categories, that have a title field.
They have the same layout, just the type changes.

2.

mapping:

```
{
	"settings": {
		"number_of_shards": %d,
		"number_of_replicas": %d,
		"analysis": {
            "filter": {
                "autocomplete_filter": { 
                    "type":     "edge_ngram",
                    "min_gram": 2,
                    "max_gram": 20
                }
            },
            "analyzer": {
                "autocomplete": {
                    "type":      "custom",
                    "tokenizer": "keyword",
                    "filter": [
                        "lowercase",
						"autocomplete_filter"
                    ]
                }
            }
        }
	},
	"mappings": {
		"game": {
			"properties": {
				"title":		{ 
					"type": "string",
					"analyzer": "keyword",
					"fields": {
						 "autocomplete":  {"type":"text", "analyzer": "autocomplete", "search_analyzer": "keyword"}
					}			
				},
				"slug":			{ "type": "text", "index": false},
				"image":		{ "type": "text", "index": false}
			}
		},
		"category": {
			"properties": {
				"title":		{ 
					"type": "string",
					"analyzer": "keyword",
					"fields": {
						 "autocomplete":  {"type":"text", "analyzer": "autocomplete", "search_analyzer": "keyword"}
					}			
				}
			}
		}
	}
}
```

3. Query:

```
{}
{
	"size" : {{.Size}},
	"_source": {
		"excludes": [ "description" ]
	},
	"explain": "false",
	"query" : {
		"bool" : {
			"must": [
				{  "type" : { "value" : "game" } }
			],
			"should": [
				{  "match" : { "title.autocomplete" : { "query" : "{{.Query}}", "boost" : 6.0 } }  },
				{  "match" : { "title.autocomplete" : { "query" : "{{.Query}}", "fuzziness": "AUTO", "boost" : 5.0 } }  },
				{  "match" : { "title" :              { "query" : "{{.Query}}", "fuzziness": "AUTO", "boost" : 2.0 } }  }
			]
		}
	}
}
{}
{
	"size" : {{.Size}},
	"_source": {
		"excludes": [ "description" ]
	},
	"explain": "false",
	"query" : {
		"bool" : {
			"must": [
				{  "type" : { "value" : "category" } }
			],
			"should": [
				{  "match" : { "title.autocomplete" : { "query" : "{{.Query}}", "boost" : 6.0 } }  },
				{  "match" : { "title.autocomplete" : { "query" : "{{.Query}}", "fuzziness": "AUTO", "boost" : 5.0 } }  },
				{  "match" : { "title" :              { "query" : "{{.Query}}", "fuzziness": "AUTO", "boost" : 2.0 } }  }
			]
		}
	}
}
{}
```

second body is just the same except for type filter.

Ouput:0
First response is correct, second one has items ordered by id, even if I flip order.

**Comment by spinscale** [comment]
please ask question like this on the [Elasticsearch discuss forum](https://discuss.elastic.co/c/elasticsearch), as we try to use github for bugs only.

In order to improve your chances of an reply in the forum, you may want to provide a **full** reproduction, including documents to index and concrete queries instead of templated ones.

**Comment by azr** [comment]
That's a bug to me :)

**Comment by spinscale** [comment]
then the second part of my answer still applies: can you please provide exact reproduction steps here (either curl or the console syntax).. also the exact msearch request send to ES not including the newlines you had above

**Comment by azr** [comment]
okay - sorry - doing things a big fast here, servers are on fire :D.

Will make you a proper case in another issue when I have time, you might not ear from that one again ^^

**Comment by azr** [comment]
Okay got time to dig out, turns out the import script was wrong.
Sorry for doubting !!
