### ISSUE TITLE
Flood stage exceeded is incorrectly logged

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#26201]
Tested on 
 - ES 6.0.0-beta1 
 - Mac OSX Sierra

Node is reporting flood stage exceeded:

```
[2017-08-14T09:29:37,167][WARN ][o.e.c.r.a.DiskThresholdMonitor] [Lq-N3tZ] flood stage disk watermark [95%] exceeded on [Lq-N3tZ8QY6B648xAA8H0g][Lq-N3tZ][/Users/jay/Workspace/elasticsearch-6.0.0-beta1/data/nodes/0] free: 11.1gb[9.9%], all indices on this node will marked read-only
```

But the math doesn't add up (flood stage is 95% and there's 9.9% free disk space

And indexing is still allowed, even on indices created before the flood stage log message appears.

```
{
    "_index": "foo",
    "_type": "bar",
    "_id": "7",
    "_version": 1,
    "result": "created",
    "_shards": {
        "total": 2,
        "successful": 1,
        "failed": 0
    },
    "_seq_no": 0,
    "_primary_term": 1
}
```

**Comment by PhaedrusTheGreek** [comment]
**This issue is only happening on Mac OSX from what I can tell so far**

Tested under Centos7 with no issues.

There seems to be more than one issue related to Flood stage under OSX:

Even after freeing up disk space (and even restarting ES), flood stage is still reported as exceeded:

```
[2017-08-14T08:59:10,470][WARN ][o.e.c.r.a.DiskThresholdMonitor] [Gz6JP_Q] flood stage disk watermark [95%] exceeded on [ODZY6GOjQMOY0ti2urj8qg][ODZY6GO][/opt/data/nodes/1] free: 11.1gb[9.9%], all indices on this node will marked read-only
```

**Comment by PhaedrusTheGreek** [comment]
indices are occasionally marked read-only, so indexing is allowed only temporarily between the creation of a new index and when this task runs.

**Comment by jasontedor** [comment]
Is this a clean install, are you sure that you did not set the flood state setting to a disk space free instead of a disk percentage free? Can you show the output of `GET /_cluster/settings?include_defaults=true&filter_path=**.flood_stage&pretty=true` and `GET /_nodes/settings?filter_path=**.flood_stage&pretty=true`?

**Comment by PhaedrusTheGreek** [comment]
Seems that [this line](https://github.com/elastic/elasticsearch/blob/e165c405ac4e467e8ff6d73b415a9190d8bdd335/core/src/main/java/org/elasticsearch/cluster/routing/allocation/DiskThresholdMonitor.java#L80) is comparing with the high watermark accidentally

**Comment by jasontedor** [comment]
You're right: #26204
