### ISSUE TITLE
Vagrant fixtures should clean themselves up appropriately

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch#26207]
We are seeing problems in environments like build and CI servers where Vagrant machines are not being cleaned up after a build is completed. We use Vagrant for packaging tests, and for integration test fixtures like the `krb5kdc` in the HDFS Repository plugin. In the latter case, Vagrant test fixtures are ignored if the local environment cannot support Vagrant/VirtualBox. 

When the build process is done using a Vagrant box, the box is often halted instead of destroyed. This is preferable in the local development environment since it can decrease the overhead of iterating on tests that use these boxes - they do not need to be re-copied and re-provisioned each execution, instead they are just started back up again. However, in the case of a build environment, projects are often blown away and freshly checked out. The previously halted machines are left abandoned on build machines which can cause the disk space to be exhausted after just over a week of builds.

Suggestion: Our Vagrant based fixture objects should be environment aware enough to know when they should destroy themselves or when it's ok to just halt after a task is completed. At the moment, my thoughts around this are either sensing an extra option passed into the build or picking something up from the environment variables.

**Comment by rjernst** [comment]
I think a sys prop indicating we are running in CI would work. We might find something that already exists, although I can't think of anything offhand.

**Comment by hub-cap** [comment]
Would running a clean after a successful build be enough for this? Maybe our CI nodes can run their normal checks, and if all is good, run a clean? This would make the build not have to change at all.

**Comment by jasontedor** [comment]
We destroy boxes since #28813.
