### ISSUE TITLE
uax_url_email tokenizer TLD issues?

### ISSUE THREAD

**Issue by neu5ron** [elastic/elasticsearch#26219]
Elasticsearch has the built-in tokenizer for URLs and emails, however I have noticed that certain top level domains cause the tokenizer to create tokens that (I would believe) are incorrect. It may be due to the TLD's that the patterns use are incorrect? I will let you be the judge, as I  am not %100 sure.

For example using:
`curl -XPOST "http://127.0.0.1:9200/test-analysis/_analyze" -H 'Content-Type: application/json' -d'
{
  "tokenizer": "uax_url_email",
  "text": "nate.guagenti@test.academy"
}'`
Will produce:
`{
  "tokens": [
    {
      "token": "nate.guagenti@test.ac",
      "start_offset": 0,
      "end_offset": 21,
      "type": "<EMAIL>",
      "position": 0
    },
    {
      "token": "ademy",
      "start_offset": 21,
      "end_offset": 26,
      "type": "<ALPHANUM>",
      "position": 1
    }
  ]
}`

Where as `curl -XPOST "http://127.0.0.1:9200/test-analysis/_analyze" -H 'Content-Type: application/json' -d'
{
  "tokenizer": "uax_url_email",
  "text": "nate.guagenti@test.com"
}'`
Will produce (correctly):
`{
  "tokens": [
    {
      "token": "nate.guagenti@test.com",
      "start_offset": 0,
      "end_offset": 22,
      "type": "<EMAIL>",
      "position": 0
    }
  ]
}`

**Comment by polyfractal** [comment]
Seems this has come up before: https://github.com/elastic/elasticsearch/issues/6467

Which generated a (still open) issue in Lucene: https://issues.apache.org/jira/browse/LUCENE-5753

Looks like Lucene needs to update the TLD registry that they are using?

**Comment by neu5ron** [comment]
Ah OK, no wonder I was not able to find it. As I was searching for is:open and that #6467 is closed.

**Comment by jasontedor** [comment]
I think similar to #6467, we can close this one; this one can be tracked upstream in the linked Lucene issue.
