### ISSUE TITLE
Typo in script settings docs

### ISSUE THREAD

**Issue by duydo** [elastic/elasticsearch#26236]
In the [Scripting and security](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-security.html#allowed-script-types-setting) document, the script setting should be started with `script.`, not with the `scripts.`

**Comment by jasontedor** [comment]
Closed by 6d8ef3153c81c3f8d80206a7d34473f4ab4d32cc

**Comment by jasontedor** [comment]
Thanks for the report @duydo.
