### ISSUE TITLE
Upsert

### ISSUE THREAD

**Issue by forestlcoder** [elastic/elasticsearch#26256]
**Describe the feature**:Use upsert method to merge partial document in an existed index,firstly the newly added result only contain index name、type and _id，run upsert method again the source will be added.

**Elasticsearch version** (`bin/elasticsearch --version`):5.2

**JVM version** (`java -version`):java-1.8.0_141 64bit

**OS version** (`uname -a` if on a Unix-like system): windows 10

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1.declare and initialize an IndexRequest、UpdateRequest instance.
 2.use upsert method to merge partial document.
 3.add UpdateRequest  instances with add method in BulkRequestBuilder
 4.run get method from BulkRequestBuilder instance

**Provide logs (if relevant)**:

**Comment by jpountz** [comment]
Sorry I don't understand what the bug is, can you explain what your expectations are and what you get?

**Comment by forestlcoder** [comment]
Expectations:if the document is not existed ,the source int the hits should not be empty
Actually:if the document is not existed ,the source int the hits is empty actually
the upsert code as follows:
`IndexRequest indexReq = null;
			try {
				indexReq = new IndexRequest("m-new-worder", "order")
						.source(XContentFactory.jsonBuilder()
								.startObject()
//map is lack
								.endObject());
			} catch (IOException e1) {
				e1.printStackTrace();
			}
			
			UpdateRequest updateReq = null;
			for (Map<String, Object> rsData : finalList) {
//				将_id设置为task_order_id
				if (!StringUtils.isEmpty(rsData.get("task_order_id"))) {//排除task_order_id不为空和null的情况
					String s = (String) rsData.get("task_order_id");
					s = deleteQuotes(s);
					try {
						updateReq = new UpdateRequest("m-new-worder", Type, String.valueOf(s))
							.doc(XContentFactory.jsonBuilder()
								.map(rsData))
							.upsert(indexReq);
					} catch (IOException e) {
						e.printStackTrace();
					}
`

**Comment by tlrx** [comment]
If the document does not already exist, the contents of the upsert element will be inserted as a new document. In your case, upsert is set to `indexReq` which is an `IndexRequest` with empty source. That's why you have an empty document after the first execution. If you execute it twice, the doc will be be merged with the existing empty document.

Maybe https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docs-update.html#_literal_doc_as_upsert_literal is what you need.
