### ISSUE TITLE
CIDR to ip_range

### ISSUE THREAD

**Issue by eskibars** [elastic/elasticsearch#26260]
**Describe the feature**:
Currently the `ip_range` type accepts the standard range notation (e.g. `gte`, `lte`).  However, IP ranges are fairly commonly defined by a CIDR.  It adds some complexity to the mapping internally, but in order to avoid having to do the conversion externally when the source data may come directly from e.g. a network switch and also to cut down on the overall size of `_source`, it may be nice to support the implicit conversion.

**Comment by s1monw** [comment]
we discussed it in fixit firday and we are convinced we should do this. Not sure about the priority. I am labeling it adopt me.

**Comment by dakrone** [comment]
Fixed in #27192
