### ISSUE TITLE
when i use fvh to highlight my search result, i find that the highlight is dislocation

### ISSUE THREAD

**Issue by th72228120** [elastic/elasticsearch#26277]
**Describe the feature**: 

**Elasticsearch version** (`bin/elasticsearch --version`): 2.3.3

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_74

**OS version** (`uname -a` if on a Unix-like system): GNU/Linux

**Description of the problem including expected versus actual behavior**:
when i use fvh to highlight my search result, i find that the highlight is dislocation

**Steps to reproduce**:

 1. create index and add mapping
curl web1:6200/test_1/_mapping?pretty
{
  "test_1" : {
    "mappings" : {
      "mtype" : {
        "properties" : {
          "doc" : {
            "type" : "string",
            "term_vector" : "with_positions_offsets",
            "analyzer" : "ik"
          }
        }
      }
    }
  }
}

 2. insert a document
curl -XPUT web1:6200/test_1/mtype/2 -d '{"doc":["泌尿系疾病", "结核", "细菌感染和真菌病", "结核病后遗症", "(1)2型糖尿病 糖尿病肾病IV期 糖尿病足清创术后（左足）（2） 陈旧性肺结核（右肺上叶）", "呼吸道疾病", "陈旧性肺结核", "血管疾病", "腿溃疡", "皮肤和结缔组织疾病", "糖尿病血管病变", "糖尿病神经病变", "糖尿病足", "放线菌目感染", "足溃疡", "糖尿病", "葡萄糖代谢障碍", "呼吸道感染", "营养和代谢性疾病", "分枝杆菌感染", "未特指的糖尿病", "肺结核", "肾疾病", "(1)2型糖尿病 糖尿病肾病IV期 糖尿病足清创术后(左足)(2) 陈旧性肺结核(右肺上叶)", "糖尿病肾病", "糖尿病并发症", "糖尿病肾病IV期", "细菌感染", "代谢疾病", "皮肤疾病", "女性泌尿生殖系统疾病", "呼吸道结核和未特指结核的后遗症", "未特指的糖尿病伴有周围循环 并发症", "革兰氏阳性菌感染", "心血管疾病", "内分泌系统疾病", "2型糖尿病", "肺疾病", "非胰岛素依赖型糖尿病", "男性泌尿生殖系统疾病", "皮肤溃疡", "非胰岛素依赖型糖尿病不伴有并发症"]}'

 3.search with highlight
{
    "query":{
        "multi_match": {
                        "slop": 2,
                        "fields": [
                          "doc"
                        ],
                        "minimum_should_match": 1,
                        "operator": "and",
                        "query": "2型糖尿病",
                        "type": "phrase"
                      }
        },
    "highlight":{
        "fields":{
            "doc":{
                  "fragment_size": 18,
                  "number_of_fragments": 15,
                  "boundary_chars":  ".,!? ，。！？、" 
            }
        }
    }
}

4. the return is like this:
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.26849622,
    "hits" : [{
      "_index" : "test_1",
      "_type" : "mtype",
      "_id" : "2",
      "_score" : 0.17439342,
      "_source" : {
        "doc" : [ "泌尿系疾病", "结核", "细菌感染和真菌病", "结核病后遗症", "(1)2型糖尿病 糖尿病肾病IV期 糖尿病足清创术后（左足）（2） 陈旧性肺结核（右肺上叶）", "呼吸道疾病", "陈旧性肺结核", "血管疾病", "腿溃疡", "皮肤和结缔组织疾病", "糖尿病血管病变", "糖尿病神经病变", "糖尿病足", "放线菌目感染", "足溃疡", "糖尿病", "葡萄糖代谢障碍", "呼吸道感染", "营养和代谢性疾病", "分枝杆菌感染", "未特指的糖尿病", "肺结核", "肾疾病", "(1)2型糖尿病 糖尿病肾病IV期 糖尿病足清创术后(左足)(2) 陈旧性肺结核(右肺上叶)", "糖尿病肾病", "糖尿病并发症", "糖尿病肾病IV期", "细菌感染", "代谢疾病", "皮肤疾病", "女性泌尿生殖系统疾病", "呼吸道结核和未特指结核的后遗症", "未特指的糖尿病伴有周围循环并发症", "革兰氏阳性菌感染", "心血管疾病", "内分泌系统疾病", "2型糖尿病", "肺疾病", "非胰岛素依赖型糖尿病", "男性泌尿生殖系统疾病", "皮肤溃疡", "非胰岛素依赖型糖尿病不伴有并发症" ]
      },
      "highlight" : {
        "doc" : [ "(1)\<em\>2型糖尿病\</em\> 糖尿病肾病IV期", "(1\<em\>)2型糖尿\</em\>病 糖尿病肾病IV期", "内分泌系统疾\<em\>病\</em\>", "\<em\>2型糖\</em\>尿病" ]
      }
    } ]
  }
}

 one of the highlight is "\<em\>2型糖\</em\>尿病". but it should be "\<em\>2型糖尿病\</em\>".
so what should I do to resolve this problem? please give me some suggestions, thanks .
**Provide logs (if relevant)**:

**Comment by tlrx** [comment]
Hi, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elastic forums](https://discuss.elastic.co/) instead. Thank you!

**Comment by th72228120** [comment]
sorry, but i think it is a bug
