### ISSUE TITLE
updateByQuery cluster state red

### ISSUE THREAD

**Issue by prigornitskiy** [elastic/elasticsearch#26276]
Elasticsearch version: 5.3.2

**Steps to reproduce**:
 1. insert 45.000.000 documents
 2. run:
`      let res = await client.updateByQuery({
        index: config.get('index'),
        type: config.get('type'),
        slices: 5,
        waitForCompletion: false,
        conflicts: "proceed",
        requestTimeout: 36000000,
        timeout: -1,
        body: {
          "query": {
            "bool": {
              "must": {
                "match_all": {}
              },
              "filter": {
                "bool": {
                  "must": [
                    {
                      "exists": {
                        "field": "offers"
                      }
                    }
                  ]
                }
              }
            }
          },
          "script": {
            "lang": "painless",
            "inline": 'for (int i = 0; i < ctx._source.offers.length; i++) {ctx._source.offers[i].price_usd = ctx._source.offers[i].price / params.toUSD[ctx._source.offers[i].code]}',
            "params": {
              "toUSD": params
            }
          }
        }
      })`
 3. After a while the cluster status red

**Comment by tlrx** [comment]
Hi @prigornitskiy, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elastic forums](https://discuss.elastic.co/) instead. Thank you!
