### ISSUE TITLE
Data query in different ways, the same record to return the data inconsistent

### ISSUE THREAD

**Issue by lilizhaolilizhao** [elastic/elasticsearch#26271]
## elasticsearch version:5.2.0
In kibana, discover page and visualize page aggregation query, elasticsearch return data inconsistency, there are some differences
![qq 20170818145949](https://user-images.githubusercontent.com/7157975/29448172-eb2cc600-8427-11e7-85ae-61d492b80b79.png)
![qq 20170818150012](https://user-images.githubusercontent.com/7157975/29448171-eb2a3f66-8427-11e7-8c73-a6a999e14cc9.png)

**Comment by tlrx** [comment]
Can you please provide:
- the mapping for the document and packet_size field?
- the document with the given `_id` as returned by a `GET /index/type/id`
- the aggregation executed by Kibana

**Comment by lilizhaolilizhao** [comment]
**This example uses a new ID, the last used ID has been deleted**
## 1 mapping:
{
  "stats-eth-agg-1-2017.08.21": {
    "mappings": {
      "agg": {
        "_all": {
          "enabled": false,
          "norms": false
        },
        "dynamic_templates": [
          {
            "template1": {
              "match": "*",
              "mapping": {
                "doc_values": true,
                "ignore_above": 1024,
                "index": "not_analyzed",
                "type": "{dynamic_type}"
              }
            }
          }
        ],
        "properties": {
          "aggregate_timestamp_double": {
            "type": "long"
          },
          "aggregate_timestamp_double_5m": {
            "type": "long"
          },
          "end_timestamp": {
            "type": "date"
          },
          "id": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "packet_size": {
            "type": "float"
          },
          "port": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "probe_hostname": {
            "type": "keyword",
            "ignore_above": 1024
          },
          "start_timestamp": {
            "type": "date"
          },
          "subnet": {
            "type": "text",
            "analyzer": "whitespace",
            "fielddata": true
          }
        }
      },
      "_default_": {
        "_all": {
          "enabled": false,
          "norms": false
        },
        "dynamic_templates": [
          {
            "template1": {
              "match": "*",
              "mapping": {
                "doc_values": true,
                "ignore_above": 1024,
                "index": "not_analyzed",
                "type": "{dynamic_type}"
              }
            }
          }
        ],
        "properties": {
          "end_timestamp": {
            "type": "date"
          },
          "start_timestamp": {
            "type": "date"
          },
          "subnet": {
            "type": "text",
            "analyzer": "whitespace",
            "fielddata": true
          }
        }
      }
    }
  }
}
## 2 GET /index/type/id
**request**:          
            curl -XGET 'http://10.128.9.207:9200/stats-eth-agg-1-2017.08.21/agg/cb202746-7891-491d-b7b5-f7f10e21eef6'
**reponse**:         
            {
  "_index": "stats-eth-agg-1-2017.08.21",
  "_type": "agg",
  "_id": "cb202746-7891-491d-b7b5-f7f10e21eef6",
  "_version": 1,
  "found": true,
  "_source": {
    "start_timestamp": "2017-08-21T15:50:00.000Z",
    "port": "0",
    "probe_hostname": "ni-server",
    "packet_size": **2327931416**,
    "id": "cb202746-7891-491d-b7b5-f7f10e21eef6",
    "aggregate_timestamp_double": 82800,
    "aggregate_timestamp_double_5m": 85800
  }
}
## 3  the aggregation request
**request**: 
            {
  "size": 0,
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "_id:cb202746-7891-491d-b7b5-f7f10e21eef6",
            "analyze_wildcard": true
          }
        },
        {
          "range": {
            "start_timestamp": {
              "gte": 1503310388784,
              "lte": 1503396788784,
              "format": "epoch_millis"
            }
          }
        }
      ],
      "must_not": []
    }
  },
  "_source": {
    "excludes": []
  },
  "aggs": {
    "2": {
      "sum": {
        "field": "packet_size"
      }
    }
  }
}
**reponse**:
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "2": {
      "value": 2327931392
    }
  },
  "status": 200
}
![qq 20170822182425](https://user-images.githubusercontent.com/7157975/29561224-47da1e2e-8767-11e7-9b5a-02c177b6c2ce.png)
![qq 20170822182449](https://user-images.githubusercontent.com/7157975/29561226-48350384-8767-11e7-9fff-a9a64b506376.png)

**Comment by lilizhaolilizhao** [comment]
@tlrx

**Comment by tlrx** [comment]
Thanks @lilizhaolilizhao.

The value `"packet_size": 2327931416` returned in the `_source` field in the GET request and shown in Kibana is the exact value provided when the document has been indexed. But what is interesting is the value indexed for the field packet_size for this document and you can return this value using [Doc Value Fields](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-request-docvalue-fields.html). 

In your search request, just add: `"docvalue_fields" : ["packet_size"]` and it should return `2.327931392E9`. I think that this is due to `2327931416` being parsed first as `double` and then narrowly converted to a `float` which results in a precision loss.

If you can trade disk space for accuracy and map the `packet_size` field as a `double` you should get back the right result.

**Comment by lilizhaolilizhao** [comment]
Thanks.   You are right. Is converted from double to float type, the damage caused by the accuracy.
![qq 20170823101148](https://user-images.githubusercontent.com/7157975/29595733-f7ed20f2-87eb-11e7-9107-e72459909b27.jpg)
![qq 20170823101152](https://user-images.githubusercontent.com/7157975/29595734-f7f86368-87eb-11e7-8765-7e0ff8d806cd.jpg)

**Comment by lilizhaolilizhao** [comment]
@tlrx 
## 1  I found the **root causes of the problem**
this project settings is a dynamic template, the template does not specify the type of "packet_size", "packet_size" program variables of type double, according to the field "packet_size" type of dynamic template generation in mapping is **FLOAT TYPE**.
## 2 The Elasticsearch version we used was upgraded from **2.2.1 to 5.2.0**. 
The same dynamic template, in the mapping generated on 2.2.1, the field "packet_size" is **DOUBLE TYPE**; in the mapping generated on 5.2.0, the field "packet_size" is **FLOAT TYPE**.

## **The following content is the dynamic template:**
{
  "order": 0,
  "template": "stats-eth-agg-1-*",
  "settings": {
    "index": {
      "number_of_replicas": "0"
    }
  },
  "mappings": {
    "_default_": {
      "dynamic_templates": [
        {
          "template1": {
            "mapping": {
              "ignore_above": 1024,
              "index": "not_analyzed",
              "type": "{dynamic_type}",
              "doc_values": true
            },
            "match": "*"
          }
        }
      ],
      "_all": {
        "norms": {
          "enabled": false
        },
        "enabled": false
      },
      "properties": {
        "subnet": {
          "fielddata": true,
          "analyzer": "whitespace",
          "type": "string"
        },
        "end_timestamp": {
          "type": "date"
        },
        "start_timestamp": {
          "type": "date"
        }
      }
    }
  },
  "aliases": {}
}

**Comment by lilizhaolilizhao** [comment]
@tlrx  
I initially think it is a double type variable, and the mapping field type generated by the dynamic template is incorrect. What do you think?
Thank you very much.

**Comment by tlrx** [comment]
> I initially think it is a double type variable, and the mapping field type generated by the dynamic template is incorrect. What do you think?

I think that:
- the mapping must be explicit for the `packet_size` field and mapped as a `double` (the dynamic template defaults to the dynamic type detection, which depends of the value received for the 1st document)
- the content sent to Elasticsearch must be valid doubles

It should be OK. I don't see this as a bug since the type detected for the field really depends of what is sent for the first document. On a production cluster the mappings of every field should be clearly defined.

**Comment by lilizhaolilizhao** [comment]
@tlrx 
If the dynamic template does not explicit the specified type, a double type variable is identified as the float type in the mapping. Is this a bug? That's what I've found at the project.

**Comment by tlrx** [comment]
> If the dynamic template does not explicit the specified type, a double type variable is identified as the float type in the mapping. Is this a bug? That's what I've found at the project.

When no mapping is defined, float are used by default instead of double because it is more space efficient. That's explicitly defined [here](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/index/mapper/DocumentParser.java#L757-L759) in the code so it's not a bug.


> And the corresponding field type the 1st document are also of the double type. In the last version（2.2.1）, there was no such problem.

Yes, it's been changed in #15319 and documented in the [breaking changes for 5.0](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_mapping_changes.html#_floating_points_use_literal_float_literal_instead_of_literal_double_literal)

**Comment by lilizhaolilizhao** [comment]
@tlrx  ok, thanks.
