### ISSUE TITLE
[DOCS] Bulk API copy as curl link defines json content type but documentation says it must be ndjson

### ISSUE THREAD

**Issue by sophiec20** [elastic/elasticsearch#26280]
Found in https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docs-bulk.html and later versions.

If you click on "Copy as curl" on the `POST _bulk` example, the following is copied to clipboard. This specifies the wrong content type; according to the documentation it should be `Content-Type: application/x-ndjson`.

```
curl -XPOST 'localhost:9200/_bulk?pretty' -H 'Content-Type: application/json' -d'
{ "index" : { "_index" : "test", "_type" : "type1", "_id" : "1" } }
{ "field1" : "value1" }
{ "delete" : { "_index" : "test", "_type" : "type1", "_id" : "2" } }
{ "create" : { "_index" : "test", "_type" : "type1", "_id" : "3" } }
{ "field1" : "value3" }
{ "update" : {"_id" : "1", "_type" : "type1", "_index" : "test"} }
{ "doc" : {"field2" : "value2"} }
'
```

**Comment by nik9000** [comment]
Either content type works now. This will have to be done before #25718 though.

**Comment by bleskes** [comment]
@nik9000 how easy is it to do this given that we use the standard `//CONSOLE` annotation here?

**Comment by nik9000** [comment]
> @nik9000 how easy is it to do this given that we use the standard //CONSOLE annotation here?

We'd need to add a marker to snippet and modify the `docs` repo to pass that marker to generated page. And we'd have to modify the JS to generate the new type. I'd go with it taking a day or two for me to do. It'd be easier for someone more familiar with the docs build but I doubt any of those folks have time.

**Comment by henningandersen** [comment]
@nik9000 maybe you want to pick this up?

**Comment by nik9000** [comment]
@bmcconaghy, how does Kibana know when to shift to ndjson? I figure the docs should use the same logic.

**Comment by bmcconaghy** [comment]
@nik9000 grepping the code it appears that console doesn't know about this either.

**Comment by nik9000** [comment]
@bmcconaghy, so, do you think we should look for `_bulk` or for json that looks like ndjson?

**Comment by bmcconaghy** [comment]
Not sure.  Is _bulk the only endpoint that takes ndjson?  If so, looking for _bulk seems fine.

**Comment by nik9000** [comment]
I believe msearch needs it as well.

**Comment by droberts195** [comment]
Is a change planned that will validate the content type more rigorously? If so then this could affect the [ML post data](https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-post-data.html) endpoint too.

As it stands it’s not a major problem because the processing is the same (for all 3 of these endpoints) regardless of whether the content type is specified to be json or nd-json. But if this is planned to change then it will affect ML post data too.

**Comment by henningandersen** [comment]
@droberts195 there is an open issue on fixing this: #25718 . I believe it is not scheduled to be done, but is still under discussion. If it is done, it seems reasonable to expect that the REST spec will contain information on expected content type.

**Comment by jrodewig** [comment]
[docs issue triage]
