### ISSUE TITLE
<em> tags are dislocated when I use fvh to highlight the search result

### ISSUE THREAD

**Issue by th72228120** [elastic/elasticsearch#26285]
**Elasticsearch version** (`bin/elasticsearch --version`): v2.3.3

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_74

**OS version** (`uname -a` if on a Unix-like system): GNU/Linux

**Description of the problem including expected versus actual behavior**:
\<em\> tags are dislocated when I use fvh to highlight the search result
**Steps to reproduce**:

 1. the mapping is :
curl web1:6200/test_1/mtype/_mapping?pretty
{
  "test_1" : {
    "mappings" : {
      "mtype" : {
        "properties" : {
          "doc" : {
            "type" : "string",
            "term_vector" : "with_positions_offsets",
            "analyzer" : "ik"
          }
        }
      }
    }
  }
}
 2. put a document :
curl -XPUT web1:6200/test_1/mtype/3 -d '{"doc":[ "(1)2型糖尿病 糖尿病肾病IV期 糖尿病足清创术后（左足）（2） 陈旧性 肺结核（右肺上叶）", "(1)2型糖尿病 糖尿病肾病IV期 糖尿病足清创术后(左足)(2) 陈旧性肺结核(右肺上叶)", "2型糖尿病"]}'
 3.query with highlight :
{
  "query": {
    "multi_match": {
      "slop": 2,
      "fields": [
        "doc"
      ],
      "minimum_should_match": 1,
      "operator": "and",
      "query": "2型糖尿病",
      "type": "phrase"
    }
  },
  "highlight": {
    "fields": {
      "doc": {
        "fragment_size": 18,
        "number_of_fragments": 15,
        "boundary_chars": ".,!? ，。！？、"
      }
    }
  }
}

4. the hit is:
{
    "_index":"test_1",
    "_type":"mtype",
    "_id":"3",
    "_score":0.34878683,
    "_source":{
        "doc":[
            "(1)2型糖尿病 糖尿病肾病IV期 糖尿病足清创术后（左足）（2） 陈旧性肺结核（右肺上叶）",
            "(1)2型糖尿病 糖尿病肾病IV期 糖尿病足清创术后(左足)(2) 陈旧性肺结核(右肺上叶)",
            "2型糖尿病"
        ]
    },
    "highlight":{
        "doc":[
            "(1)\<em\>2型糖尿病\</em\> 糖尿病肾病IV期 糖尿病足清创术后（左足）（2）",
            "(1\<em\>)2型糖尿\</em\>病 糖尿病肾病IV期",
            "陈旧性肺结核(右肺上叶\<em\>)\</em\>",
            "\<em\>2型糖\</em\>尿病"
        ]
    }
}

5. notice that the <em> tags are dislocated in the highlight result. "\<em\>2型糖\</em\>尿病" should be "\<em\>2型糖尿病\</em\>"

take a look, thanks.

**Provide logs (if relevant)**:

**Comment by th72228120** [comment]
the same as v5.4.2, \<em\> tags are dislocated in the highlighted search result

**Comment by th72228120** [comment]
when I use english it is repeated, too
1. create a document. 
curl -XPUT web1:6250/test_1/mtype/9 -d '{"doc":[ "hello word =", "this is my hello word", "hello world"]}'
2. search query is:
{
  "query": {
    "multi_match": {
      "slop": 2,
      "fields": [
        "doc"
      ],
      "minimum_should_match": 1,
      "operator": "and",
      "query": "hello world",
      "type": "phrase"
    }
  },
  "highlight": {
    "fields": {
      "doc": {
        "fragment_size": 180,
        "number_of_fragments": 15
      }
    }
  }
}
3. result is
{
        "_index" : "test_1",
        "_type" : "mtype",
        "_id" : "9",
        "_score" : 3.0837474,
        "_source" : {
          "doc" : [
            "hello word =",
            "this is my hello word",
            "hello world"
          ]
        },
        "highlight" : {
          "doc" : [
            "this is my hello wor<em>d</em>",
            "<em>hello wor</em>ld"
          ]
        }
      }

**Comment by jimczi** [comment]
Can you share the definition of the custom `ik` analyzer that you defined for the `test_1` index. I cannot reproduce the bug without this. Also can you try to use the `unified` highlighter instead and see if the bug reproduces ? The `fvh` highlighter is still maintained but we plan to remove it in favor of the `unified` highlighter in a near future. The `unified` highlighter can use term vectors to extract the offsets so the performance should be similar.

**Comment by th72228120** [comment]
I download the ik analyzer from https://github.com/medcl/elasticsearch-analysis-ik/tree/v5.4.2 and my mapping is :
{
  "test_1" : {
    "mappings" : {
      "mtype" : {
        "properties" : {
          "doc" : {
            "type" : "text",
            "term_vector" : "with_positions_offsets",
            "analyzer" : "ik_max_word"
          }
        }
      }
    }
  }
}

right now I try the unified highlighter and it doesn't seems to work yet
my query is:
{
  "query": {
    "multi_match": {
      "slop": 2,
      "fields": [
        "doc"
      ],
      "minimum_should_match": 1,
      "operator": "and",
      "query": "hello world",
      "type": "phrase"
    }
  },
  "highlight": {
    "fields": {
      "doc": {
        "type": "unified",
        "fragment_size": 180,
        "number_of_fragments": 15
      }
    }
  }
}

the result is :
{
        "_index" : "test_1",
        "_type" : "mtype",
        "_id" : "9",
        "_score" : 2.1357477,
        "_source" : {
          "doc" : [
            "hello word = ",
            "this is my hello word",
            "hello world"
          ]
        },
        "highlight" : {
          "doc" : [
            "this is my hello wo\<em\>rd\u0000he\</em\>",
            "hel\<em\>lo wo\</em\>rld"
          ]
        }
      }

**Comment by th72228120** [comment]
I find the problem is due to the ik analyzer.
thanks a lot.
