### ISSUE TITLE
Build Failure - :qa:mixed-cluster:v5.6.0-SNAPSHOT

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#26287]
Multiple Test Failures for :qa:mixed-cluster:v5.6.0-SNAPSHOT

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.0+multijob-darwin-compatibility/78/console

REPRODUCE WITH: gradle :qa:mixed-cluster:v5.6.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=2105558FC1301C46 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=cluster.state/20_filtering/Filtering the cluster state by blocks should return the blocks}" \
  -Dtests.security.manager=true \
  -Dtests.locale=fi-FI \
  -Dtests.timezone=Asia/Muscat

REPRODUCE WITH: gradle :qa:mixed-cluster:v5.6.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=2105558FC1301C46 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=cluster.state/20_filtering/Filtering the cluster state by blocks should return the blocks}" \
  -Dtests.security.manager=true \
  -Dtests.locale=fi-FI \
  -Dtests.timezone=Asia/Muscat

REPRODUCE WITH: gradle :qa:mixed-cluster:v5.6.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=2105558FC1301C46 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=indices.stats/13_fields/Completion fields - star}" \
  -Dtests.security.manager=true \
  -Dtests.locale=fi-FI \
  -Dtests.timezone=Asia/Muscat

REPRODUCE WITH: gradle :qa:mixed-cluster:v5.6.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=2105558FC1301C46 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=nodes.stats/11_indices_metrics/Metric - one}" \
  -Dtests.security.manager=true \
  -Dtests.locale=fi-FI \
  -Dtests.timezone=Asia/Muscat

REPRODUCE WITH: gradle :qa:mixed-cluster:v5.6.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=2105558FC1301C46 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=indices.exists_template/10_basic/Test indices.exists_template with local flag}" \
  -Dtests.security.manager=true \
  -Dtests.locale=fi-FI \
  -Dtests.timezone=Asia/Muscat

REPRODUCE WITH: gradle :qa:mixed-cluster:v5.6.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=2105558FC1301C46 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=cluster.reroute/11_explain/Explain API with empty command list}" \
  -Dtests.security.manager=true \
  -Dtests.locale=fi-FI \
  -Dtests.timezone=Asia/Muscat

REPRODUCE WITH: gradle :qa:mixed-cluster:v5.6.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=2105558FC1301C46 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=index/36_external_gte_version/External GTE version}" \
  -Dtests.security.manager=true \
  -Dtests.locale=fi-FI \
  -Dtests.timezone=Asia/Muscat

REPRODUCE WITH: gradle :qa:mixed-cluster:v5.6.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=2105558FC1301C46 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=indices.stats/11_metric/Metric - _all include_segment_file_sizes}" \
  -Dtests.security.manager=true \
  -Dtests.locale=fi-FI \
  -Dtests.timezone=Asia/Muscat

REPRODUCE WITH: gradle :qa:mixed-cluster:v5.6.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=2105558FC1301C46 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=indices.get_alias/10_basic/Getting alias on an non-existent index should return 404}" \
  -Dtests.security.manager=true \
  -Dtests.locale=fi-FI \
  -Dtests.timezone=Asia/Muscat

REPRODUCE WITH: gradle :qa:mixed-cluster:v5.6.0-SNAPSHOT#mixedClusterTestRunner \
  -Dtests.seed=2105558FC1301C46 \
  -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT \
  -Dtests.method="test {p0=indices.get_alias/10_basic/Getting alias on an non-existent index should return 404}" \
  -Dtests.security.manager=true \
  -Dtests.locale=fi-FI \
  -Dtests.timezone=Asia/Muscat

**Comment by s1monw** [comment]
@dakrone can you look it seems like it's related to our latest changes

```
 2> elokuuta 18, 2017 4:01:39 AP. org.elasticsearch.client.RestClient logResponse
  2> WARNING: request [PUT http://[::1]:62258/testidx/_settings?error_trace=true] returned 1 warnings: [299 Elasticsearch-5.6.0-SNAPSHOT-2102b6b "The [_all] field is deprecated and will be removed in Elasticsearch 6.0" "Fri, 18 Aug 2017 00:01:39 GMT"]
  1> [2017-08-18T04:01:39,104][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test {p0=cluster.state/20_filtering/Filtering the cluster state by blocks should return the blocks}]: after test
  1> [2017-08-18T04:01:39,106][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] Stash dump on failure [{
  1>   "stash" : {
  1>     "body" : {
  1>       "acknowledged" : true
  1>     }
  1>   }
  1> }]
  2> REPRODUCE WITH: gradle :qa:mixed-cluster:v5.6.0-SNAPSHOT#mixedClusterTestRunner -Dtests.seed=2105558FC1301C46 -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT -Dtests.method="test {p0=cluster.state/20_filtering/Filtering the cluster state by blocks should return the blocks}" -Dtests.security.manager=true -Dtests.locale=fi-FI -Dtests.timezone=Asia/Muscat
  2> REPRODUCE WITH: gradle :qa:mixed-cluster:v5.6.0-SNAPSHOT#mixedClusterTestRunner -Dtests.seed=2105558FC1301C46 -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT -Dtests.method="test {p0=cluster.state/20_filtering/Filtering the cluster state by blocks should return the blocks}" -Dtests.security.manager=true -Dtests.locale=fi-FI -Dtests.timezone=Asia/Muscat
ERROR   0.20s | MixedClusterClientYamlTestSuiteIT.test {p0=cluster.state/20_filtering/Filtering the cluster state by blocks should return the blocks} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [cluster.state/20_filtering:25]: got unexpected warning header [
   >    299 Elasticsearch-5.6.0-SNAPSHOT-2102b6b "The [_all] field is deprecated and will be removed in Elasticsearch 6.0" "Fri, 18 Aug 2017 00:01:39 GMT"
   > ]
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:352)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:332)
   >    at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.lang.AssertionError: got unexpected warning header [
   >    299 Elasticsearch-5.6.0-SNAPSHOT-2102b6b "The [_all] field is deprecated and will be removed in Elasticsearch 6.0" "Fri, 18 Aug 2017 00:01:39 GMT"
   > ]
   >    at org.elasticsearch.test.rest.yaml.section.DoSection.checkWarningHeaders(DoSection.java:290)
   >    at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:234)
   >    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:348)
   >    ... 37 moreThrowable #2: org.elasticsearch.client.ResponseException: DELETE http://[::1]:62291*: HTTP/1.1 403 Forbidden
   > {"error":{"root_cause":[{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/5/index read-only (api)];"}],"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/5/index read-only (api)];"},"status":403}
   >    at org.elasticsearch.client.RestClient$1.completed(RestClient.java:354)
   >    at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343)
   >    at org.elasticsearch.client.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
   >    at org.elasticsearch.client.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
   >    at org.elasticsearch.client.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
   >    at org.elasticsearch.client.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
   >    at org.elasticsearch.client.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
   >    at org.elasticsearch.client.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
   >    at org.elasticsearch.client.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
   >    at org.elasticsearch.client.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
   >    at org.elasticsearch.client.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
   >    at org.elasticsearch.client.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
   >    at org.elasticsearch.client.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
   >    at org.elasticsearch.client.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
   >    at org.elasticsearch.client.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
   >    at org.elasticsearch.client.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
   >    at java.lang.Thread.run(Thread.java:748)
  1> [2017-08-18T04:01:39,114][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test {p0=indices.stats/13_fields/Completion fields - star}]: before test
  1> [2017-08-18T04:01:39,828][INFO ][o.e.b.MixedClusterClientYamlTestSuiteIT] [test {p0=indices.stats/13_fields/Completion fields - star}]: after test
```

**Comment by dakrone** [comment]
@s1monw @jdconrad I reverted the changes to the 5.6 branch last night, this looks like CI has not caught up to a good commit yet.

**Comment by s1monw** [comment]
ok lets close it
