### ISSUE TITLE
Build Failure: Cannot Expand ZIP

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#26288]
Cannot expand ZIP '/var/lib/jenkins/workspace/elastic+x-pack-elasticsearch+5.6+periodic/elasticsearch/distribution/bwc/build/bwc/checkout-5.5/distribution/zip/build/distributions/elasticsearch-5.5.2-SNAPSHOT.zip' as it does not exist.

https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+5.6+periodic/541/console

**Comment by jasontedor** [comment]
It's from the release/version bump dance, it's fixed now.
