### ISSUE TITLE
Build Failure :qa:full-cluster-restart:v6.1.0-SNAPSHOT#oldClusterTestCluster#node1.configure

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#26290]
Execution failed for task ':qa:full-cluster-restart:v6.1.0-SNAPSHOT#oldClusterTestCluster#node1.configure'.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/3950/console

**Comment by jasontedor** [comment]
Elasticsearch could not start because logging was being touched before logging was initialized. This is no-no, and we fail startup. This is fixed by a1adf4cd8a3bde5805c9783e5f44a7ebae37c952.
