### ISSUE TITLE
two nodes with the same cluster name having two different cluster uuid

### ISSUE THREAD

**Issue by midokate** [elastic/elasticsearch#26301]
Hello
    i configured two node with the cluster name (production) but when i installed head plugin i didn't see the two nodes i saw the node which its address is used to open head plugin
(for instance <node1 ip add>:9200/_plugin/head will show me the node 1 as master and as the only node in the cluster the same thing goes for the node2 )

    my configuration :  
==> node1:
cluster.name: production
index.numer_of_shards : 5
index .number_of_replicas : 0
node.name: node1
network.host: node1 Ip Add
discovery.zen.ping.unicast.hosts: [node1 Ip Add ,node2 Ip Add]
discovery.zen.ping.multicast.enabled: false
discover.zen.ping.timeout: 20s

==> node2:
cluster.name: production
index.numer_of_shards : 5
index .number_of_replicas : 0
network.host: node2 Ip Add
node.name: node1
discovery.zen.ping.unicast.hosts: [node1 Ip Add ,node2 Ip Add]
discovery.zen.ping.multicast.enabled: false
discover.zen.ping.timeout: 20s

**Comment by jasontedor** [comment]
The UUID is a non-issue, if the nodes could form a cluster the resulting cluster state would have a single, shared UUID (from whichever node became master). So, this points to a configuration/environment issue for you. We handle verified bugs and feature requests here, and general questions on the [forum](https://discuss.elastic.co).

**Comment by akmaharshi** [comment]
I am getting uuid as "_na_". I believe as we have only one master server, we may not have uuid information. Let me know if I am correct.
Please let me know where does the application fetch uuid information from ?
