### ISSUE TITLE
Debug log file size increase exponentialy due to elasticsearch

### ISSUE THREAD

**Issue by shekharS7** [elastic/elasticsearch#26303]
Debug log file size is increase exponentially due to elastic search debug. And its coming in gb. It takes lots of time to download and open and also its is consuming disk space. 

So if we disable log from magento it will not generate debug file. But I need debug file to track other magento modules and fix erros as required. In elastic search debug I am getting these following lines which is increasing the size. I can disable or comment it or remove in the code these .... However I would like to know if I remove/comment these line will it cause any problems or is it required or is there any other alternative way to reduce the file size. 

1)Request Body {"0":"{ .....................................................
2)Response {"0":{ .......................................................................

It is important to know how I can reduce the file size with any other method without affecting to track other magento modules etc.... 

Please let me know what methods I an use to reduce the debug log file size and what are the best practices I can follow.

**Comment by s1monw** [comment]
this is a bugtracker and reserved for feature requests and bug reports. If you have a particular question about elasticsearch please consult the [forum](discuss.elastic.co ) while this rather sounds like a 3rd party configuration issue.
