### ISSUE TITLE
Anyway to change a long datatype to string in _source when index a document?

### ISSUE THREAD

**Issue by xueyihan** [elastic/elasticsearch#26304]
Kibana can't display long type correctly. I need to change a long type data stored in the _source to a string. I use mongodb + mongo-connector + elasticsearch, i have no idea to do this!

**Comment by cbuescher** [comment]
Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions.
I'd suggest starting to look at the Ingest APIs and the [Ingest Node](https://www.elastic.co/guide/en/elasticsearch/reference/master/ingest.html) as a startet. This very likely solves your needs.

**Comment by xueyihan** [comment]
Thanks, that's really helpful! @cbuescher

**Comment by xueyihan** [comment]
no way to bind a pipeline to a index? it' hard to use when you have to add a pipeline id to a request, especially for mongo-connector. @cbuescher
