### ISSUE TITLE
Do we have a plan to implement a replication policy by using lucene's NRT replication?

### ISSUE THREAD

**Issue by yiguolei** [elastic/elasticsearch#26316]
Do we have a plan to implement a replication policy by using lucene's NRT(https://issues.apache.org/jira/browse/LUCENE-5438) replication?  Or anybody that is working on this? I think it will reduce a lot of cpu.

Any other reasons that ES doesn't use this feature?

**Comment by jasontedor** [comment]
At this time, we do not. Please ask additional questions on the [forum](https://discuss.elastic.co); we reserve GitHub for verified bug reports and feature requests.
