### ISSUE TITLE
XMoreLikeThis diverged from Lucene MoreLikeThis

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#26323]
XMoreLikeThis is a copy of MoreLikeThis query for elasticsearch that was added to fix an issue in Lucene but the es class has diverged from Lucene over time. We added new features to it that are not in Lucene:
https://github.com/elastic/elasticsearch/pull/8674
https://github.com/elastic/elasticsearch/pull/7014
... and the same happened on the Lucene side.

It should be possible to backport some of these to Lucene and simply overrides the Lucene class for the ones that are specific to es.

**Comment by andyb-elastic** [comment]
@elastic/es-search-aggs

**Comment by jimczi** [comment]
Duplicate of https://github.com/elastic/elasticsearch/issues/10626
