### ISSUE TITLE
Kibana not displaying syslogs over openvpn

### ISSUE THREAD

**Issue by bm1391** [elastic/elasticsearch#26324]
I have configured a ELK stack and I am having problems getting Kibana to display the logs only* over our VPN. Our logstash server is 10.100.1.10 and the openvpn server is 10.200.1.0/24 network. I am able to send test logs (logger test1, logger test2 etc.) from the remote hosts to our logstash server and I can see the logs I send in /var/log/syslog.Because of this, I can't seem to think it is a firewall issue at all. I am transferring the logs via UDP (. @ipaddress:514). The Logstash and syslog server are on the same host(10.100.1.10). Any hosts on the 10.100.1.0/24 network can send logs and Kibana displays them.

Tests: From remote host (10.200.1.10)

` ping 10.100.1.10(logstash) => success`

` netcat 10.100.1.10 -z -v -u 514 => success`

**Comment by jasontedor** [comment]
This is the open source Elasticsearch repository and it sounds like you're having a Kibana issue. For that, I think you should try a topic in Kibana category on the [forum](https://discuss.elastic.co) as that's where we prefer to handle general help, reserving GitHub for verified bug reports and feature requests.
