### ISSUE TITLE
more_like_this query does not work with nested data types

### ISSUE THREAD

**Issue by fbaligand** [elastic/elasticsearch#26322]
**Elasticsearch version** (`bin/elasticsearch --version`): 
5.4.1

**Description of the problem including expected versus actual behavior**:
If I make a more_like_this query on a field A which is inside a "nested" B field, it returns no results.
If I remove "nested" type on B field, the more_like_this query works as expected : relevant results are returned.

=> Could you fix `more_like_this` query to work fine with fields which are inside a "nested" field ?

**Comment by colings86** [comment]
@martijnvg could you take a look at this?

**Comment by jpountz** [comment]
Duplicate of #21625
