### ISSUE TITLE
API to verify connection between cross cluster search and gateway nodes

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#26327]
Feedback from field admins:

While CCS' architecture is fundamentally different from tribe nodes where it does not keep a bidirectional connection open to every remote node, it can be useful to have an utility api so admins can use it to quickly verify if the CCS cluster can successfully make a connection with at least search.remote.connections_per_cluster number of gateway nodes (and which nodes are successful) for each downstream cluster.  This can be useful for large deployments with many downstream clusters.

**Comment by colings86** [comment]
It looks like this already exists in the [Remote Cluster Info API](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/cluster-remote-info.html). I think this covers the request here?

**Comment by ppf2** [comment]
Interesting, this is often missed because it is not linked from the main cross cluster search documentation and this API is really only used with CCS.  Can we add a reference from https://www.elastic.co/guide/en/elasticsearch/reference/5.5/modules-cross-cluster-search.html so that users are aware? :)  Reopening to convert to a doc issue.  thx!
