### ISSUE TITLE
[BalancedShardsAllocator] balance shards  should consider the storage space of instances?

### ISSUE THREAD

**Issue by keenbo** [elastic/elasticsearch#26336]
As the [BalancedShardsAllocator] balance the shards  Follow 2 important principles.
First,Make sure that all es instances have near slice quantities.
Second,The index‘s shards are allocated in different instances as much as possible.

We have different machines, and the storage capacity of machines is not the same size. If we do not consider the storage space weight of the instance, when the capacity storage is full, the low capacity machine will first arrive at the storage bottleneck, and then it will lead to removal. Because the [DiskThresholdDecider] will make the moving decition!

**Comment by andy-elastic** [comment]
Can you explain a little more about why the existing disk allocation settings don't work for your use case? Thanks

**Comment by javanna** [comment]
Closing for lack of feedback. We will certainly reopen once we get back more info on this.
