### ISSUE TITLE
Nexus can't proxy the address of x-pack-transport

### ISSUE THREAD

**Issue by kervin521** [elastic/elasticsearch#26334]
maven config x-pack-transport-5.x.x.jar ,Agents need to be used because of the Intranet Environment，in the private Nexus Repository,It config the proxy address of Repository:
```
<repository>
 	<id>elastic-releases</id>
 	<url>https://artifacts.elastic.co/maven/</url>
</repository>
```

but the status of proxy is unsuccessful.

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch. For X-Pack issues, please raise a topic in the X-Pack category on the [forum](https://discuss.elastic.co).

**Comment by dadoonet** [comment]
Have a look at https://www.elastic.co/guide/en/x-pack/current/java-clients.html which describes how to add the repo in Nexus.
