### ISSUE TITLE
Problem With Total and Nested Field limits

### ISSUE THREAD

**Issue by abhiCR7** [elastic/elasticsearch#26343]
**Describe the feature**:

**Elasticsearch version**: 2.4.x

**Plugins installed**: none

**JVM version** (`java -version`): 1.8.0_91

I have currently v2.4 Elasticsearch in production and in the process to upgrade it to v5.5.
I’m facing problem with
   `index.mapping.total_fields.limit: 1000`
   `index.mapping.nested_fields.limit: 50`
My current total fields are in the order of 13000 and nested_fields around 100.
Since this is non-dynamic field I’m not able to update it. Is creating a new index the only option?
if no, Is there any way I can upgrade without creating new index so I can change the default values of these settings?

**Comment by rjernst** [comment]
Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports. With that said, both of those settings are dynamic index settings. I'm not sure what led you to believe they are not.
