### ISSUE TITLE
[discuss]should just check major+minor version equality when load plugin?

### ISSUE THREAD

**Issue by makeyang** [elastic/elasticsearch#26348]
currently before load plugin, esVersion.equals(Version.CURRENT) is checked. 
my question is: should ES team consider that the revision release won't broke plugin protocal so that only major + minor verion is checked

**Comment by jasontedor** [comment]
We have discussed this before and we are not going to change this, no leniency here at all. We release our own plugins with each patch release to guarantee that the compiled plugins are compatible with the compiled server code. We think that community plugins should do the same to try to provide the same guarantees, so we enforce that plugins are released targeting a specific version of Elasticsearch.
