### ISSUE TITLE
SearchResponse should implement HasAggregations

### ISSUE THREAD

**Issue by lupo112** [elastic/elasticsearch#26340]
`SearchResponse` (and possibly other classes, which has method `getAggregations`) should implement interface `HasAggregations`. It will simplify fuctional-like programming in Java 8.

**Comment by javanna** [comment]
hi @lupo112 could you please show me an example where this change would help?

**Comment by lupo112** [comment]
```java
searchResponse
	.flatMap(this::extractAggs)
	.cast(SingleBucketAggregation.class)
	.flatMap(this::extractAggs)
	.toMap(Aggregation::getName)
	...
```

In this case, I have to define two methods with different input arguments:
```java
private Observable<Aggregation> extractAggs(SearchResponse bucket) {
	return Observable.fromIterable(bucket.getAggregations())
		.filter(agg -> !IGNORED_AGGS.contains(agg.getName()));
}

private Observable<Aggregation> extractAggs(HasAggregations bucket) {
	return Observable.fromIterable(bucket.getAggregations())
		.filter(agg -> !IGNORED_AGGS.contains(agg.getName()));
}
```

While `SearchResponse` contains method `getAggregations` which is the same as defined in the interface `HasAggregations`.

**Comment by jpountz** [comment]
Thank you for explaining, we get your point now.

We discussed it in FixitFriday and agreed to not do it. This interface was added as a way to mark aggregations that have sub aggregations, so we felt like putting it on SearchResponse would be wrong.
