### ISSUE TITLE
How to set multi value about http.cors.allow-origin in es 5.x

### ISSUE THREAD

**Issue by zqc0512** [elastic/elasticsearch#26351]
in my es env
i need **two client** can use elasticsearch-head can connect to es but not allow 
how i can set about **http.cors.allow-origin** in elasticsearch.yml file
**not set to http.cors.allow-origin: ***

**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by tvernum** [comment]
Please ask this question on our [discuss forum](https://discuss.elastic.co/) where we can provide better support.
Elastic uses GitHub issues exclusively for tracking bugs and feature requests.

Thank you.
