### ISSUE TITLE
failed to build elasticsearch

### ISSUE THREAD

**Issue by jiezhu2007** [elastic/elasticsearch#26374]
**Elasticsearch version** (`bin/elasticsearch --version`):
5.5.1
**Plugins installed**: []
None
**JVM version** (`java -version`):

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
windows 7 64bit

**Description of the problem including expected versus actual behavior**:

build fail

**Steps to reproduce**:

 1.gradle tasks
 2.gradle build
 3.fail to build, and report list below

=======================================
Elasticsearch Build Hamster says Hello!
=======================================
  Gradle Version        : 4.1
  OS Info               : Windows 7 6.1 (amd64)
  JDK Version           : Oracle Corporation 1.8.0_144 [Java HotSpot(TM) 64-Bit
Server VM 25.144-b01]
  JAVA_HOME             : C:\Program Files\Java\jdk1.8.0_144
Gradle now uses separate output directories for each JVM language, but this buil
d assumes a single directory for all classes from a source set. This behaviour h
as been deprecated and is scheduled to be removed in Gradle 5.0

> Configure project :plugins:repository-hdfs
hdfsFixture unsupported, please set HADOOP_HOME and put HADOOP_HOME\bin in PATH
secured hdfsFixture is unsupported, please install Vagrant 1.8.6+ to enable

> Task :core:jar
Building without git revision id.

> Task :benchmarks:javadocJar
Building without git revision id.

> Task :benchmarks:forbiddenApisMain
Forbidden method invocation: java.lang.Class#getDeclaredField(java.lang.String)
[Do not violate java's access system: Use getField() instead]
  in org.elasticsearch.benchmark.routing.allocation.generated.AllocationBenchmar
k_measureAllocation_jmhTest (AllocationBenchmark_measureAllocation_jmhTest.java:
373)
Forbidden method invocation: java.lang.reflect.AccessibleObject#setAccessible(bo
olean) [Do not violate java's access system]
  in org.elasticsearch.benchmark.routing.allocation.generated.AllocationBenchmar
k_measureAllocation_jmhTest (AllocationBenchmark_measureAllocation_jmhTest.java:
374)

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':test:framework:test'.
> No value has been specified for property 'testClassesDir'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 15s
68 actionable tasks: 16 executed, 52 up-to-date

**Comment by jasontedor** [comment]
All of our branches build right now, so this is probably an environment problem. I recommend running `gradle clean`. For additional help, please ask on the [forum](https://discuss.elastic.co) as we reserve GitHub for verified bug reports and feature requests.

**Comment by jiezhu2007** [comment]
I changed the gradle  to version 3.3,the error is gone.
I suspect that there is compatibility issues with version 4.1 of gradle.
