### ISSUE TITLE
Why elasticsearch 5.4 bulk update so slow and increased 100+ segments per second

### ISSUE THREAD

**Issue by huzhaohui** [elastic/elasticsearch#26382]
elaricsearch 5.4.3  bulk update docs, it increased more than 100 segments(it increase several segments while i bulk update docs in elasticsear1.7 ).
bulk update parameters:
elaricsearch version:5.4
index.refresh_interval:30s( effective when bulk index, not effective when bulk update, but why?)
Do not it(segments) depend on index.refresh_interval and buffer size?

> {
> "state": "open",
> "settings": {
> "index": {
> "refresh_interval": "30s",
> "number_of_shards": "3",
> "translog": {
> "flush_threshold_size": "512m",
> "sync_interval": "5s",
> "durability": "async"
> }

**Comment by danielmitterdorfer** [comment]
Hi @huzhaohui, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!

**Comment by huzhaohui** [comment]
thank you.

https://discuss.elastic.co/t/why-elasticsearch-5-4-bulk-update-so-slow-and-increased-100-segments-per-second/98358
