### ISSUE TITLE
[Docs] Doc in Japanese break the documentation tests

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#26381]
Commit 2ce358af29ce839243964b55af246474704d769c added many asciidoc files in a jp/ directory. Those files are not listed in the exclusion list (aka `expectedUnconvertedCandidates`) in the `docs/build.gradle` file and it breaks the build when the `gradle :docs:check` command is executed.

**Comment by tlrx** [comment]
Also on 5.3: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.3+dockeralpine/11/

**Comment by nik9000** [comment]
Yikes! @debadair can we move the translated docs to a subdirectory of docs? That way we can ignore them entirely in the docs build. We *shouldn't* have different examples in the translations.

It'd be nice to know how the translations are made so we can deal with them properly. As it stands I expect folks to start submitting PRs agains the translations and I dunno if we should merge them. Honestly I wonder if the translations should be in the core repository at all....

**Comment by debadair** [comment]
@nik9000 They are in subdirectories of docs--docs/jp and docs/kr. 

Regarding the translations, we went back & forth but ultimately decided to treat the translations like we do the rest of the docs. We will accept PRs against them subject to review & the usual requirements. The translations that I've added to the build this week were done by a vendor and reviewed by our own native speakers. We kept that process in separate, private repos so we could get the translation team ramped up & work out the kinks in the process out of public view. Going forward, the idea is to follow our normal process and have them submit PRs against the product repos.

**Comment by debadair** [comment]
Talked to @nik9000 & he's going to exclude the docs/jp and docs/kr directories from testing in the 5.3 and 5.4 branches. (Currently the only branches with translated content.) Ultimately, the right thing to do is move the English docs into docs/en and only test against that directory, but I'd prefer to put off moving the files & making the necessary doc config changes at least until after we get 5.6 out.

**Comment by nik9000** [comment]
Fixed the build with c2b9cc1ebff93fa4699bdebbb51dab0e2667364a.
