### ISSUE TITLE
Make sure all registered aggregations in core are also registered in the client

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#26384]
Currently we don't have a good way of testing whether all the aggregation parsers registered in core ES are also registered in the HL client (see e.g. #26370 as an example). We should investigate if we can improve testing so aggregations that are added in the future are properly registered and we don't forget about them in the rest-highlevel client.

**Comment by dakrone** [comment]
Closing this as we've removed the high level rest client in favor of the [Java client](https://github.com/elastic/elasticsearch-java/).
