### ISSUE TITLE
 Could not resolve all files for configuration ':benchmarks:classpath'.

### ISSUE THREAD

**Issue by saliormoon** [elastic/elasticsearch#26386]
**Compile Elasticsearch Souce Code With Gradle** 
When I compile the elasticsearch source code with gradle, I get a serious problem, such as the Bug report:

* What went wrong:
A problem occurred configuring project ':benchmarks'.
> Could not resolve all files for configuration ':benchmarks:classpath'.
   > Could not resolve com.github.jengelman.gradle.plugins:shadow:1.2.3.
     Required by:
         project :benchmarks
      > Could not resolve com.github.jengelman.gradle.plugins:shadow:1.2.3.
         > Could not get resource 'https://plugins.gradle.org/m2/com/github/jeng
elman/gradle/plugins/shadow/1.2.3/shadow-1.2.3.pom'.
            > Could not GET 'https://plugins.gradle.org/m2/com/github/jengelman/
gradle/plugins/shadow/1.2.3/shadow-1.2.3.pom'.
               > sun.security.validator.ValidatorException: PKIX path building f
ailed: sun.security.provider.certpath.SunCertPathBuilderException: unable to fin
d valid certification path to requested target

**Elasticsearch version** (`bin/elasticsearch --version`):v5.5.2

**JVM version** (`java -version`): jdk1.8

**OS version** (`uname -a` if on a Unix-like system):Windows

**Description of the problem including expected versus actual behavior**:
Compile Elasticsearch Souce Code With Gradle

Can someone help me?

**Comment by danielmitterdorfer** [comment]
Hi @saliormoon, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!

From the following part of your error message I conclude that your certificate configuration in the JDK is broken and you should look into fixing this:

```
> Could not GET 'https://plugins.gradle.org/m2/com/github/jengelman/
gradle/plugins/shadow/1.2.3/shadow-1.2.3.pom'.
> sun.security.validator.ValidatorException: PKIX path building failed: 
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

Hope that helps!

**Comment by saliormoon** [comment]
broken?@danielmitterdorfer
D:\jdk1.8\bin>java SSLPoke developer.nrel.gov 443
java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketI
mpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.ja
va:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocket
Impl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java
:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:432)
        at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryIm
pl.java:88)
        at SSLPoke.main(SSLPoke.java:25)

**Comment by jasontedor** [comment]
@saliormoon Please ask questions on the [forum](https://discuss.elastic.co).

**Comment by saliormoon** [comment]
ok.

**Comment by saliormoon** [comment]
thanks a lot.@danielmitterdorfer
