### ISSUE TITLE
Ability to aggregate on suggester results

### ISSUE THREAD

**Issue by cwarny** [elastic/elasticsearch#26393]
I'd like my aggregations to operate on the set of documents filtered by my suggester (just like it does when the filtering is done by a query). Instead it ignores the suggester and aggregates across the board.

Example:

```
{
	"suggest": {
		"my-suggest" : {
			"prefix" : "hel",
			"completion" : {
				"field" : "myfield.suggest"
			}
		}
	},
	"aggs": {
		"my-aggs": {
			"terms" : { 
				"field": "myfield.raw"
			}
		}
	}
}
```

I'd like `my-aggs` to only return terms that start with `hel`.

**Comment by cwarny** [comment]
I've thought a little more about this. I am guessing the reply will be that suggesters are meant to maximize speed and that interacting them with aggregations will slow them down. I'm also guessing the alternative approach would be something like this:

```
{
	"query": {
		"match_phrase_prefix": {
			"myfield" : "hel"
		}
    },
	"aggs": {
		"my-aggs": {
			"terms" : { 
				"field": "myfield.raw"
			}
		}
	}
}
```

**Comment by colings86** [comment]
Aggregating on suggestions wouldn't really work since the output of suggesters is a suggestion (basically a term) and not a set of documents, whereas the input of aggregations is a set of documents. For your use case I would suggest using your second approach.
