### ISSUE TITLE
SearchContextMissingException[No search context found for id [xxxxx]

### ISSUE THREAD

**Issue by nitishgoyal13** [elastic/elasticsearch#26403]
I am migrating es cluster from 1.4 to 5.4.

Still getting the same error
[indices:data/read/search[phase/scan/scroll]]]; nested: SearchContextMissingException[No search context found for id [4003744]
Successfully migrated the dev and testing cluster.
Getting the error while migrating prod cluster.

I have increased the scroll time to 30 mins and decreased the bulk size to 100. I have run the migration multiple times. Every time, after running for few hours, it fails with the below error

error:org.elasticsearch.ElasticsearchException: 4 shards failed while scrolling -
shard [_na], reason [RemoteTransportException[[es-data-elastic-paid1-30-1e][inet[/x.x.x.x:9200]][indices:data/read/search[phase/scan/scroll]]]; nested: SearchContextMissingException[No search context found for id [4003744]]; ]
shard [_na], reason [RemoteTransportException[[es-data-elastic-paid1-38-1e][inet[/y.y.y.y:9200]][indices:data/read/search[phase/scan/scroll]]]; nested: SearchContextMissingException[No search context found for id [4126954]]; ]
shard [_na], reason [RemoteTransportException[[es-data-elastic-paid1-26-1e][inet[/u.u.u.u:9200]][indices:data/read/search[phase/scan/scroll]]]; nested: SearchContextMissingException[No search context found for id [3512259]]; ]
shard [_na], reason [RemoteTransportException[[es-data-elastic-paid1-28-1e][inet[/z.z.z.z:9200]][indices:data/read/search[phase/scan/scroll]]]; nested: SearchContextMissingException[No search context found for id [3821269]]; ]
at com.spr.search.repository.elasticsearch.ESScan$ESScanIterator.throwOnShardFailures(ESScan.java:167)
at com.spr.search.repository.elasticsearch.ESScan$ESScanIterator.doNext(ESScan.java:132)
at com.spr.search.repository.elasticsearch.ESScan$ESScanIterator.next(ESScan.java:123)
at com.spr.search.repository.elasticsearch.ESScan$ESScanIterator.next(ESScan.java:73)
at

**Comment by dakrone** [comment]
Hi,
We reserve Github issues for feature requests and bug reports. If you are having problems please use https://discuss.elastic.co instead!

This looks like your `scroll_id` is being used longer than the scroll timeout. Perhaps you are using the initial `scroll_id` instead of using the (potentially newer) `scroll_id` that comes in each response.

**Comment by nitishgoyal13** [comment]
Scan<SearchHit> scroll = new ESScan<>(new Lookup<ESClientDetails>() {
                @Override
                public ESClientDetails lookup() {
                    return finalFromEsClient;
                }
            }, new Adapter<SearchHit, SearchHit>() {
                @Override
                public SearchHit adapt(SearchHit input) {
                    return input;
                }
            }, searchRequestBuilder, bulkIndexSize);

            long docsReindexed = 0;
            long lastBatchTime = System.currentTimeMillis();
            for (final List<SearchHit> searchHits : scroll) {
                     // Do precessing
             }
