### ISSUE TITLE
Return resolved query in results

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#26406]
Perhaps something like:

```
_search
{
 "return_query_in_result": true,
 "query" {
    ...
 }
}
```

With features like date math, the executed query is different than the one originally supplied.  It might be useful for troubleshooting and/or for informational.   For example,  in date range math, today in August,`"lte": "now-1M/M"` resolves to Aug 1, where as `"lt": "now-1M/M"` resolves to July 31, which might throw off a user who hasn't read the docs.

**Comment by jpountz** [comment]
Is the validate API with rewrite=true good enough for your needs?

**Comment by javanna** [comment]
@PhaedrusTheGreek can you answer Adrien's question above please?

**Comment by PhaedrusTheGreek** [comment]
Validate could work, the info is there, but its in epoch format so it's not convenient for casual testing.

```
GET /some_index/_validate/query?rewrite=true
{
 "query": {
    "bool": {
        "must": [
            {
                "range": {
                    "@timestamp": {
                        "gte": "now-1M/M",
                        "lt": "now/M"
                    }
                }
            }
        ]
    }
 }
}

...

{
 "valid": true,
 "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
 },
 "explanations": [
 {
    "index": "some_index",
    "valid": true,
    "explanation": "@timestamp:[1498867200000 TO 1501545599999]"
 }
 ]
}
```

**Comment by jpountz** [comment]
Actually, we parse date math expressions directly into milliseconds so I'm afraid there is no intermediate representation of the date that we could try to expose with some API. So anything more would be significant work and maintenance.

**Comment by javanna** [comment]
Agreed, I would close this issue. Users will have to parse the time from epoch and make sense of the date themselves.
