### ISSUE TITLE
Named queries return documents with no `matched_queries`

### ISSUE THREAD

**Issue by ddorian** [elastic/elasticsearch#26417]
**Elasticsearch version** (`bin/elasticsearch --version`): "5.2.0"

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
Linux guru 4.4.0-87-generic #110~14.04.1-Ubuntu SMP Tue Jul 18 14:51:32 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Named queries don't always match, they return docs without `named_queries` attribute.

**Steps to reproduce**:
Execute python script and watch output. The second search has no `matched_queries`.
```
    from elasticsearch import Elasticsearch
    es = Elasticsearch()
    the_index = {
        'settings': {'number_of_shards': 1, 'number_of_replicas': 0, 'refresh_interval': 0},
        'mappings': {
            'test': {
                'properties': {
                    'field1': {'type': 'keyword'},
                    'field2': {'type': 'keyword'},
                    'field3': {'type': 'keyword'},
                }
            }
        }
    }
    if es.indices.exists('the_test'):
        es.indices.delete('the_test')
        es.indices.create('the_test', body=the_index)
    es.index('the_test', 'test', {'field1': ['bum'], 'field2': 'bum', 'field3': '#bum'}, refresh=True)
    print(es.search('the_test', body={'query':{'bool': {'filter': {'bool':{'must':[{'term': {'field1': {'value': 'bum', '_name': 'bum'}}}]}}}}}, _source=False))
    print(es.search('the_test', body={'query':{'bool': {'filter': {'bool':{'should':[
        {'term': {'field1': {'value': 'bum', '_name': 'bum'}}},
        {'term': {'field2': {'value': 'bum', '_name': 'bum'}}},
        {'term': {'field3': {'value': 'bum', '_name': 'bum'}}},
    ]}}}}}, _source=False))

```

**Comment by tlrx** [comment]
@ddorian You must use a different value for `_name` for each query

**Comment by ddorian** [comment]
Oh, that makes sense(but sucks on the ui). But how to combine multiple `term` queries so I can specify the name only once ?

**Comment by tlrx** [comment]
I think you can set the `_name` at the `bool` level.

**Comment by ddorian** [comment]
Thanks, that works and makes sense. Maybe you should fix the docs with these 2 points ?

**Comment by tlrx** [comment]
The documentation https://www.elastic.co/guide/en/elasticsearch/reference/5.5/search-request-named-queries-and-filters.html shows a sample with different values for `_name` so I think it's ok.

**Comment by ddorian** [comment]
But they are different filters ? Anyway, I didn't understand it. But it make sense to mention that you shouldn't duplicate.

**Comment by tlrx** [comment]
If you think that the documentation can be improved, please open a pull request :+1:
