### ISSUE TITLE
Locale validation breaks with randomized locales

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#26425]
Lucene provides a helper method to get a random locale. This may break with the new LocaleUtils.isValid method, which tries to make sure only locales with iso alpha-3 language and country codes are used, since Lucene does not have such a restriction. This happens, for example, when the locale `en-DG` is used.

Repro line:
```gradle :modules:ingest-common:test -Dtests.seed=EA476B6050B3EB91 -Dtests.class=org.elasticsearch.ingest.common.DateProcessorFactoryTests -Dtests.method="testParseLocale" -Dtests.security.manager=true -Dtests.jvm.argline="--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.nio.file=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED --add-opens=java.base/java.util.regex=ALL-UNNAMED" -Dtests.locale=ksh -Dtests.timezone=Asia/Saigon```

build:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+java9-periodic/407/console

relates #26186

**Comment by rjernst** [comment]
@jpountz Can you take a look? Either we need to be more restrictive in ES tests with our own locale randomization, or lucene needs to be more selective in the locales it chooses from?

**Comment by jpountz** [comment]
Thanks @rjernst I'll look.
