### ISSUE TITLE
Kibana unable to connect to Elasticsearch even when ssl keys/certs passed in as env variables

### ISSUE THREAD

**Issue by ocofaigh** [elastic/elasticsearch#26426]
**Kibana version**: 5.5.2

**Elasticsearch version**: 2.4.1

**Server OS version**: Red Hat Enterprise Linux Server release 7.4 (Maipo)

**Browser version**: n/a

**Browser OS version**: n/a

**Original install method (e.g. download page, yum, from source, etc.)**: docker pull kibana:latest

**Description of the problem including expected versus actual behavior**: Unable to connect to Elasticsearch at https://<ip_address>:8743
I understand that ES is now proxied by an nginx instance running on the master node alongside ES. It runs on port 8743. This nginx instance has keys/certs that are now needed to get kibana to connect successfully. I was able to get them from the the nginx instance in order to pass in as enviornment variables to the docker run command. But this does not seem to be working. Kibana still cannot connect to ES.

**Steps to reproduce**:
 1. `docker pull kibana:latest`
 2. Get the docker container id: 
![image](https://user-images.githubusercontent.com/29608224/29836440-2b506a52-8ced-11e7-8d0d-680a957da3d9.png)
 3. Grab the keys and certs from the docker container, placing them in /tmp: 
`docker cp $id:/etc/cfc/conf /tmp/kibana`
4. Docker run Kibana, passing in the keys/certs as env variables:
`docker run -d --name kibana -p 5601:5601 -e ELASTICSEARCH_URL="https://<ip_address>:8743" -e ELASTICSEARCH_SSL_CERT="/tmp/kibana/conf/es/server.pem" -e ELASTICSEARCH_SSL_KEY="/tmp/kibana/conf/es/server-key.pem" -e ELASTICSEARCH_SSL_VERIFY="false" -e ELASTICSEARCH_SSL_CA="/tmp/kibana/conf/es/ca.pem" kibana:latest`
5. Log into kibana dashbaord - Unable to connect to Elasticsearch at https://<ip_address>:8743

**Errors in browser console (if relevant)**: Unable to connect to Elasticsearch at https://<ip_address>:8743

**Provide logs and/or server output (if relevant)**:
[kibana_latest_logs.txt](https://github.com/elastic/elasticsearch/files/1261638/kibana_latest_logs.txt)
 (I have replaced the IP address of the server with <ip_address>)

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch, this looks like it would better be handled on the Kibana repository [elastic/kibana]((https://github.com/elastic/kibana) or the Kibana Docker repository [elastic/kibana-docker](https://github.com/elastic/kibana-docker).
