### ISSUE TITLE
sum value does not match with the sum of all item in hits

### ISSUE THREAD

**Issue by 5ean** [elastic/elasticsearch#26424]
**Describe the feature**:

**Elasticsearch version 5.5 (`bin/elasticsearch --version`):

**Plugins installed**: [No plug in]

**JVM version** (`java -1.7`):

**OS version** (windows server):

**Description of the problem including expected versus actual behavior**:

The sum value is not correct

Here is the query:
```
GET sample-2017_07/_search 
{
  "size" : 0,
  "query": {
    "match": {
      "RESP_NODE.keyword": "T3481"
    }
  },
  "_source": {
    "excludes": []
  },
      "aggs": {
        "4": {
          "sum": {
            "field": "RWA_AMT"
          }
        }
      }
}
```

And the return is like:
```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 3038,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "4": {
      "value": 950937581.1279907
    }
  }
}
```

the result is 2000+ more than the correct answer 950935544.6046678.

So I added `"from" : 0, "size" : 3038`, in query. extract the all items in hits segment and summed up. The answer matches the correct one which is 950935544.6046678.

Can someone help me on this?

**Comment by 5ean** [comment]
Here is the sample data to reproduce this issue.
[test.txt](https://github.com/elastic/elasticsearch/files/1261804/test.txt)

Here is index:
```
{
  "sample": {
    "aliases": {},
    "mappings": {
      "test": {
        "properties": {
          "COL1": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "COL2": {
            "type": "float"
          }
        }
      }
    },
    "settings": {
      "index": {
        "creation_date": "1504042093988",
        "number_of_shards": "5",
        "number_of_replicas": "1",
        "uuid": "ATMGcoNtREqJy5WUzWIAIA",
        "version": {
          "created": "5050299"
        },
        "provided_name": "sample"
      }
    }
  }
}
```
Here is query
```
GET sample/test/_search
{
  "size" : 0,
  "query": {
    "match": {
      "COL1": "T3481"
    }
  },
  "_source": {
    "excludes": []
  },
      "aggs": {
        "4": {
          "sum": {
            "field": "COL2"
          }
        }
      }
}
```
following is the result:
```
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 3038,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "4": {
      "value": 950937581.1279907
    }
  }
}
```

The correct answer is 950935544.6046678 not 950937581.1279907

**Comment by cbuescher** [comment]
@colings86 do you have any opinion about whether this is due to e.g. internal float conversions, etc.?

**Comment by jpountz** [comment]
This is due to float conversions indeed. For instance the dataset has value `-68683370.7909999937` whose closest float is distant by about 2.8 from its closest double. For the record, please note that `950935544.6046678` is not the correct answer, it is just less incorrect. If you need more accuracy, you can map your field as a `double` rather than `float`. Note however that it will increase storage requirements.
