### ISSUE TITLE
Add an option to disable deleting indices using alias

### ISSUE THREAD

**Issue by kiju98** [elastic/elasticsearch#26435]
I have a customer mistakenly deleted their important indices using alias.
Once an index is deleted, it is impossible to recover it.
I think it would be great if an option to disable deleting indices using alias similar with `action.destructive_requires_name`.
I think very few people may find deleting multiple indices using alias whereas disabling it would improve the safety by preventing mistakes.

**Comment by bleskes** [comment]
We totally agree and delete an index via an alias is no longer possible in 6.0: https://github.com/elastic/elasticsearch/pull/25268
