### ISSUE TITLE
retryable scroll

### ISSUE THREAD

**Issue by brackxm** [elastic/elasticsearch#26433]
To retrieve al lot of data, using the scroll api is recommended.
Currently (5.5)  it is not possible to retry individual pages.
The scroll_id is reused over multiple requests.
If something goes wrong, e.g. a network problem, and the client retries a request it gets the next page. Thus loosing a page.
The client would have to retry by getting all documents again (and possibly having to do some extra bookkeeping to check what documents have already been processed).

A solution would be to use token based paging. With each request a new token/scroll_id can be returned. That way individual request are different and can be retried.

This can be done with the current api, as the documentation already states to use the scroll_id from the latest request.

**Comment by jpountz** [comment]
For the record, it has implications as it means for instance that we will need to encode more information in the scroll ids and won't be able to automatically close scrolls once all matching documents have been retrieved.

**Comment by brackxm** [comment]
The server state could still be removed after the timeout.
If too much resources are needed only a limited number of extra pages/token could be support.
e.g.  1 extra.
Or it could be configurable, like the current timeout.

**Comment by jpountz** [comment]
We discussed it in FixitFriday and agreed to close it in favour of #26472.
