### ISSUE TITLE
Snapshot azure repository support for Azure China 

### ISSUE THREAD

**Issue by ckalyanpur** [elastic/elasticsearch#26432]
**Describe the feature**:

The azure snapshot plugin currently takes a storage account name and key as an input and tries to retrieve the CloudStorageAccount by forming a connection string via the provided input. The domain in the default case is assumed to be '**core.windows.net**' which works for most of Microsoft's data centers. 

In China, the domain is different, hence trying to store/restore a snapshot by using the storage account name and key alone as inputs does not work. The storage account access keys provide an EndpointSuffix attribute which indicates the domain to be used. As a feature, it will be nice to have an additional input attribute for the Endpoint Suffix with the default still being 'core.windows.net' if left unspecified.

We currently are running ES1.6 in china for our prod customers. In order to circumvent this, we had to include the EndpointSuffix portion as part of the account key input value since the connection string is formed through concatenation. It will be nice to have this as an explicit input.

**Elasticsearch version** (`bin/elasticsearch --version`): 1.6.2

**Comment by liketic** [comment]
Hi @dadoonet Are you working on this? I'm happy to take this.  :)

**Comment by dadoonet** [comment]
I'm not. Feel free to take it and send your PR.

Thanks!
