### ISSUE TITLE
Date Histogram got wrong result for "yyyy-ww"

### ISSUE THREAD

**Issue by buptrobin** [elastic/elasticsearch#26439]
ES Version 2.4. 
Some one else report 5.1-5.5 also have the same behavior, but I did not confirm.

For date historgram, elasticsearch returning “2014-01” for date “2014-12-31” with format “yyyy-ww”, actually it should be "2015-01".

The query I use is:
```
{
  "_source": [ "9303" ],
  "size": 3,
  "query": {
    "bool": {
      "must": [
        {
          "range": {
            "9303": {
              "from": 2014-12-31",
              "to": "2014-12-31"
            }
          }
        }
      ]
    }
  },
  "explain": false,
  "aggregations": {
    "9303": {
      "date_histogram": {
        "field": "9303",
        "interval": "week",
        "format": "yyyy-ww",
        "time_zone": "Asia/Shanghai"
      }
    }
  }
}

```

I check the code, it should used "years" instead of "weekyear" for the formatter internal printer.
But not sure this is happen in ES or in the org.joda.time package.

**Comment by jpountz** [comment]
Your format is wrong, it mixes regular years and weekyears. It should look like this:

```
GET index/_search
{
  "aggregations": {
    "9303": {
      "date_histogram": {
        "field": "date",
        "interval": "week",
        "format": "xxxx-ww",
        "time_zone": "Asia/Shanghai"
      }
    }
  }
}
```
