### ISSUE TITLE
Elasticsearch-5.5.2.msi will not install when choosing X-Pack.

### ISSUE THREAD

**Issue by soernt** [elastic/elasticsearch#26442]
[InstallLog.txt](https://github.com/elastic/elasticsearch/files/1263595/InstallLog.txt)
**Elasticsearch version**:
5.5.2

**Server OS version**:
Windows 10, 64Bit, German

**Original install method (e.g. download page, yum, from source, etc.)**:
Downloadpage -> elasticsearch-5.5.2.msi

**Description of the problem including expected versus actual behavior**:
The setup erorrs.

**Steps to reproduce**:
 1. Start the "elasticsearch-5.5.2.msi", choose the "X-Pack" option to install, leave everything else with default values.

**Provide logs and/or server output (if relevant)**:
Install log file attached.
[InstallLog.txt](https://github.com/elastic/elasticsearch/files/1263597/InstallLog.txt)

The ElasticSearch installs successfully when not choosing the "X-Pack" option.

**Comment by cbuescher** [comment]
@Mpdreamz would you be able to take a look at this? I briefly scanned the log and found this:
```
Calling custom action Elastic.Installer.Msi!Elastic.Installer.Msi.Elasticsearch.CustomActions.Install.ElasticsearchPluginsAction.ElasticsearchPlugins
Elastic.InstallerHosts.Elasticsearch.Tasks.InstallPluginsTask: Installing Elasticsearch plugins
[0] installing x-pack installing x-pack
Syntaxfehler.
[0] installing x-pack installing x-pack
System.Exception: Execution failed (C:\Program Files\Elastic\Elasticsearch\bin\elasticsearch-plugin.bat install x-pack ). ExitCode: 255 ErrorCheck: True ErrorOut:Syntaxfehler.

   bei Elastic.Installer.Domain.Configuration.Plugin.PluginStateProviderBase.Install(Int32 pluginTicks, String installDirectory, String configDirectory, String plugin, String additionalArguments)
   bei Elastic.InstallerHosts.Elasticsearch.Tasks.InstallPluginsTask.ExecuteTask()
   bei Elastic.InstallerHosts.SessionExtensions.Handle(Session session, Func`1 action)
CustomAction ElasticsearchPluginsAction returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 14:42:52: InstallFinalize. Return value 3.
MSI (s) (D8:D0) [14:42:52:028]: Note: 1: 2265 2:  3: -2147287035 
```

but I'm not sure if this is helpful or tells you anything.

**Comment by jasontedor** [comment]
Please use the dedicated repository for this: [elastic/windows-installers](https://github.com/elastic/windows-installers)
