### ISSUE TITLE
Assign shards and Data replication 

### ISSUE THREAD

**Issue by aniked** [elastic/elasticsearch#26440]
Hello , 
By mistake, a folder (index) have been deleted from a node : /data3/data/es/esdartyprd/nodes/0/indices/enc_idx/2/index )

I can see that data are missed for primary shard in this node (node1) => 
for this index , here what gives me the command curl -XGET http://localhost:9200/_cat/shards 

enc_idx         2 p STARTED    57824815 28.8gb 10.135.8.201 HDPESPRD1
enc_idx         2 r STARTED    57824815 36.5gb 10.135.8.202 HDPESPRD2
enc_idx         2 r STARTED    57824815 36.5gb 10.135.10.15 HDPESPRA1
enc_idx         2 r STARTED    57824815 36.5gb 10.135.8.203 HDPESPRD3
enc_idx         2 r UNASSIGNED

You can see that data are missed in the node1 which is master ! And still have problem to assign data to node4 

Any possibility to recover or replicate missed data from replicate shards ? Is that done automatically? Any solutions to assign the shard which is not assigned ? In the log I find an error that a file is corrupted from this folder : 

 [enc_idx][2] Corrupted index [corrupted_1ytPPpKkTZCGG_zQcbBG-w] caused by: CorruptIndexException[codec footer mismatch: actual footer=1063427 vs expected footer=-1071082520 (resource: NIOFSIndexInput(path="/data3/data/es/esdartyprd/nodes/0/indices/enc_idx/2/index/_3gv6_es090_0.pos"))]

**Comment by cbuescher** [comment]
Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions.
