### ISSUE TITLE
RestHighLevelClient cannot be sub classed outside of the `org.elasticsearch.client` package.

### ISSUE THREAD

**Issue by tsachev** [elastic/elasticsearch#26455]
**Elasticsearch High Level REST Client version** 5.6.0-SNAPSHOT

**Description of the problem including expected versus actual behavior**:

`RestHighLevelClient` javadoc states that

> Can be sub-classed to expose additional client methods that make use of endpoints added to Elasticsearch through plugins, or to add support for custom response sections, again added to Elasticsearch through plugins.

I would expect to be able to call all the protected methods if I am sub-classing from another package, but actually I currently need access to the `Request` class in order to do so.

I am not willing to write my extension code in `org.elasticsearch.client` package in order to be able to extend it. The public/protected API should be sufficient to do so in my own package.

**Steps to reproduce**:
There are two test cases that shows that `RestHighLevelClient` can be extended (`RestHighLevelClientExtTests` and `CustomRestHighLevelClientTests`), but the subclasses (`RestHighLevelClientExt` and `CustomRestClient`) are defined in the same package as `RestHighLevelClient`, if you move them in another package they no longer compile.

**Comment by cbuescher** [comment]
Thanks, this is a good point. I will label this for discussion but I think it makes sense to allow this.

**Comment by javanna** [comment]
You are right @tsachev this needs to be fixed.
