### ISSUE TITLE
wrong use of `org.apache.http.entity.ContentType.create(String)` in rest client

### ISSUE THREAD

**Issue by tsachev** [elastic/elasticsearch#26452]
The high level rest client is sometimes calling this method with `application/json; charset=utf8`.
This is wrong and works by accident. The righ way is to pass the charset in some of the overloads.

In fact there is a bug HTTPCORE-423(https://issues.apache.org/jira/browse/HTTPCORE-423) that has been
fixed in httpcore `4.4.6` (apache/httpcomponents-core@f8f55e88a35c4afbb088e0d17292762f74f8d251) so the rest client is currently not able to update its dependencies, because an `IllegalArgumentException` will be thrown.

I hit this because I was have the newer version in my classpath (don't get me wrong, I am very happy that you removed shading from the rest client).

I fixed this in my fork (tsachev/elasticsearch@d94ce7f9bc5b048ced8af48a9d716a0362abb322), can you please take a look. I would create a PR, but not sure against which branch will be best (`5.x`, `5.6` or `master`).

**Comment by jasontedor** [comment]
Duplicates #26438 for which I think there is already work in flight.
