### ISSUE TITLE
Docs for Painless do not demonstrate how to safely handle values which *might* be null or empty

### ISSUE THREAD

**Issue by sirosen** [elastic/elasticsearch#26459]
This is a pretty common pattern in more general programming scenarios, but maybe less common in scripted updates. However, it was highly non-obvious in the docs.

If you want to check if a field is present on a doc, or if its present-but-empty, there should be examples to follow.

My particular use-case: for manually scripted updates to all docs in the index, we want to track the updates which were run in an object, and use it to enforce script idempotence as a flag.

Here's (a simplified version of) what _works_:
```groovy
def update_name = '2017-08-31-myupdate';
// let's not nitpick over this, but I'm including it in case ctx._source behaves differently
// I assume it does not matter, but including it for completeness
def entry = ctx._source.entry;
if (entry['_ran_updates'] == null)
    entry._ran_updates = [:];
else if (entry._ran_updates[update_name])
    continue;
// stuff
entry._ran_updates[update_name] = true;
```

The issue is that the use of `entry['_ran_updates'] == null` is not at all obvious.
Things that do not work include:
- `!entry['_ran_updates']` -- `!null` gives a NullPointer exception in painless?
- `entry['_ran_updates'].empty` -- also gives a NullPointer exception if the field isn't there at all

There are a bunch of other variants that don't work, like `!entry._ran_updates`, for the same basic reasons.

I think the painless docs should have an example of conditional logic on the presence/absence of an attribute. A potentially good example would be "insert a value into a map only if it is already defined" or a similar conditional-update.

**Comment by nik9000** [comment]
https://www.elastic.co/guide/en/elasticsearch/painless/5.5/_operators.html#_null_safe and https://www.elastic.co/guide/en/elasticsearch/painless/5.5/_operators.html#_elvis ought to help here. I admit that we could move it.

And yes, we could use a section about how painless doesn't emulate the falsy syntax of groovy or javascript.

**Comment by sirosen** [comment]
FWIW, I did a lot of reading trying to figure out why `!entry._ran_updates` wasn't working, and in all that time I didn't find the `elvis` operator. That might recommend moving it to a more prominent place.

When you suggest these operators, in my case I guess it would turn into
```groovy
entry._ran_updates = entry?._ran_updates ?: [:];
if (entry._ran_updates[update_name])
  continue
```

Am I understanding that correctly? I'm happy to turn my case into a cleaner example of conditionally assigning values to a hashmap and open a documentation PR.

> And yes, we could use a section about how painless doesn't emulate the falsy syntax of groovy or javascript.

Is there a section about differences from Groovy in general for this to go into? I tested my stuff using groovysh and was surprised to see it go amiss when I ran tests against an index.

**Comment by nik9000** [comment]
> When you suggest these operators, in my case I guess it would turn into

Something like that. 

I'd certainly love a PR better documenting this but I just don't know where to put it in the documentation. Maybe someone like @debadair or @jdconrad has a better idea.

**Comment by jdconrad** [comment]
Closing this.  Documentation for the elvis operator exists under https://www.elastic.co/guide/en/elasticsearch/painless/current/_operators.html

**Comment by sirosen** [comment]
The elvis operator doesn't have strong bearing on the fact that `!null` is a very common pattern in Groovy (and Python, and Javascript, and...), but errors in Painless.

The most confusing thing here was not figuring out how to write "or equals", but how Painless and Groovy differ.

**Comment by thespatt** [comment]
@jdconrad your link is no longer valid, is there a chance you could update it?

**Comment by jdconrad** [comment]
@thespatt See (https://www.elastic.co/guide/en/elasticsearch/painless/current/painless-operators-reference.html#elvis-operator)
