### ISSUE TITLE
bootstrap.system_call_filter to false not able to configure cluster

### ISSUE THREAD

**Issue by SudhakarSundar** [elastic/elasticsearch#26461]
Hi,

Iam using the Elasticsearch 5.5.2, and Iam not able to configure cluster. I dont see my nodes talking to each other.  I tried using the following configuration in my elasticsearch.yml.

I tried changing the transport.host: to my server ip, but doing so the bootstrap check fails, 
`unable to install syscall filter: java.lang.UnsupportedOperationException: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and C     ONFIG_SECCOMP_FILTER are needed
        at org.elasticsearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:363) ~[elasticsearch-5.5.2.jar:5.5.     2]`
my question is if SecComp fails then can't I run the elasticsearch in the cluster mode?
Iam using Red Hat Enterprise Linux Server release 6.8 (Santiago)  OS.

my elasticsearch.yml

`#
#action.destructive_requires_name: true
#
network.host: ${HOSTNAME}
network.host: X.X.X.X
transport.host: localhost
transport.tcp.port: 9300

#bootstrap.system_call_filter: false

# Enabling CORS - for production we need to restrict domain wise
http.cors.allow-origin: "/.*/"
http.cors.enabled: true
http.cors.allow-headers: "X-Requested-With,content-type,authorization"
http.cors.allow-credentials: true

# Enabling clustering more
cluster.name: logsearch
node.name: "node_1"
node.master: true
node.data: true
#discovery.zen.ping.multicast.enabled: false
#
discovery.zen.minimum_master_nodes: 1
discovery.zen.ping.unicast.hosts: ["X.X.X.X:9300","X.X.X.X:9300"]
`

**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
> my question is if SecComp fails then can't I run the elasticsearch in the cluster mode?

No, please read the error message that accompanies this failing bootstrap check (not shown in the logs you pasted, but please check your logs for the same):

```
[2017-08-31T17:49:27,630][INFO ][o.e.b.BootstrapChecks    ] [rmPsFBs] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed
[1]: system call filters failed to install; check the logs and fix your configuration or disable system call filters at your own risk
```

You need to disable the node from attempting to install the system call filters; this is you accepting the risk that Elasticsearch will be less secure than if it could sandbox itself via `seccomp`. The [docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/system-call-filter-check.html#system-call-filter-check) cover this.

If you have additional questions, please ask on the [forum](https://discuss.elastic.co). We reserve GitHub for verified bug reports and feature requests.
