### ISSUE TITLE
When is elasticsearch 6.0 release planned?

### ISSUE THREAD

**Issue by selvakumarEsra** [elastic/elasticsearch#26468]
we are developing a new product that uses elasticsearch. Just wanted to know release date for elasticsearch 6.0, so we can plan to onboard or upgrade accordingly. 

Please suggest suitable channel to ask this question, Apologies for raising the query as issue.

**Comment by jpountz** [comment]
We don't disclose release dates in advance. However it is no secret that most development efforts these days are targeted at Elasticsearch 6.0, yet we will produce one or more release candidates before GA (we only produced alphas and betas so far) so I think it is safe to assume that this will be a matter of months - but I can't tell how many.

**Comment by hatdropper1977** [comment]
They just released it.
https://www.elastic.co/blog/elastic-stack-6-0-0-released
