### ISSUE TITLE
Long field value auto minus 10, why???

### ISSUE THREAD

**Issue by shijiebei2009** [elastic/elasticsearch#26465]
now I am update a document by _id, update :
POST action_log_2016/action_log_2016/201601070000000010/_update
{
"doc": {
"IDX": 201601070000000010,
"actiondetail": "for testing"
},
"doc_as_upsert": true
}
and the results is :
"hits": {
"total": 1,
"max_score": 1,
"hits": [
{
"_index": "action_log_2016_v3",
"_type": "action_log_2016",
"_id": "201601070000000010",
"_score": 1,
"_source": {
"IDX": 201601070000000000,
"actiondetail": "for testing"
}
}
]
}

amazing! the IDX auto minus 10

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
