### ISSUE TITLE
Replace `_scroll` with the ability to acquire point-in-time views + search_after

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#26472]
`_scroll` comes with limitations such as the fact that it only allows to go forward, which can be an issue if there are connectivity issues while the client is retrieving one page as this particular page cannot be retried.

We would like to replace `_scroll` with an API that allows to open point-in-time views of the data and then allows to paginate through it using `search_after`. We could even keep the sort by `_doc` optimization if users provide `"track_total_hits": false` in their request.

In FixitFriday it was suggested that we call this API `Jim's API`.

**Comment by mayya-sharipova** [comment]
Will this API also allow to go backward certain doc, for example using `search_before`?  or for retrieving a previous page, we can use `search_after` with a reverse sort order?

**Comment by jpountz** [comment]
I think your idea to go backwards is the right one. Alternatively, clients could remember sort values associated with previously visited pages so that they can go back efficiently. So we don't need to add any new API/option?

**Comment by mayya-sharipova** [comment]
Right, we don't need another API/option for going backwards if docs are returned in the stable sorted order; in this case we can just reverse the the sort order.
When you were saying "clients could remember sort values associated with previously visited pages", what are these "sort values"? Are these docs as in `search_after` parameter?

**Comment by jpountz** [comment]
Sort values are values that each document was sorted against and that [we return in the response](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_sort_values). For instance if you sort by score then price, those could be `[2.2, 100]` and if the client application can store somewhere in the session what sort values have been passed to `search_after` in order to get hits from page X, then it could easily go to page X again by reusing those sort values, it does not need to cache the entire response.

**Comment by ssmelov** [comment]
Do you know if there is any design document for this new API?

**Comment by jimczi** [comment]
This feature has been merged in https://github.com/elastic/elasticsearch/pull/61062, hence closing.
