### ISSUE TITLE
Add 'preserve_original' option in stemmer token filter

### ISSUE THREAD

**Issue by fbaligand** [elastic/elasticsearch#26485]
As on `asciifolding` token filter, it would be great to add `preserve_original` option on stemmer token filter, so that stemmer filter generates stemmed token but also keeps original token at same position.

**Comment by jimczi** [comment]
You can do that already with the `keyword_repeat` filter:
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/analysis-keyword-repeat-tokenfilter.html
It generates an additional token that will not be stemmed (works only with the stemmers).

**Comment by fbaligand** [comment]
Hi @jimczi ,

Thanks a lot for the info !
And sorry for this false issue.

Fabien
