### ISSUE TITLE
maybe a token filter that limit tokens by frequency is useful to minhash

### ISSUE THREAD

**Issue by cclient** [elastic/elasticsearch#26487]
feature:

filter tokens like

select count(*) as num,token from tokens group by token order by  num desc limit 128;

then do minhash

**Comment by jimczi** [comment]
Can you describe the feature a bit more ? What do you mean by frequency ? The frequency of the terms inside the document ? If so I think it would be better to implement it directly inside the minhash filter since it seems to be only useful there ?

**Comment by colings86** [comment]
No further feedback. If you can provide more details on the feature request then please post them here and we can reopen the issue
