### ISSUE TITLE
Opening Winlogbeat dashboard crashes Elasticsearch 6.0.0-beta2 with StackOverflowError

### ISSUE THREAD

**Issue by praseodym** [elastic/elasticsearch#26482]
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 6.0.0-beta2, Build: 23ffa4f/2017-08-29T01:53:03.739Z, JVM: 1.8.0_144

**Plugins installed**: ingest-geoip, ingest-user-agent

**JVM version** (`java -version`): Java(TM) SE Runtime Environment (build 1.8.0_144-b01)

**OS version** (`uname -a` if on a Unix-like system): Linux 4.9.0-3-amd64 Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Elasticsearch crashes unexpectedly.

**Steps to reproduce**:
1. Set up Winlogbeat with Kibana index pattern + dashboard (`winlogbeat.exe -c winlogbeat.yml setup`)
2. Index some event log data with Winlogbeat (`winlogbeat.exe -c winlogbeat.yml`)
3. Do any of the following:
    * Open 'Winlogbeat Dashboard' in Kibana
    * Open the `winlogbeat-*` pattern in Discover in Kibana
    * Execute `curl 'localhost:9200/winlogbeat-*/_search?q='` (`?q=` is required here to replicate the crash)
4. Elasticsearch crashes with a `java.lang.StackOverflowError` 100% of the time

**Provide logs (if relevant)**:
* [elasticsearch-1.log.txt](https://github.com/elastic/elasticsearch/files/1273080/elasticsearch-1.log.txt) (contains multiple stack traces)
* [elasticsearch-2.log.txt](https://github.com/elastic/elasticsearch/files/1273081/elasticsearch-2.log.txt)
* [elasticsearch-3.log.txt](https://github.com/elastic/elasticsearch/files/1273082/elasticsearch-3.log.txt)
* [elasticsearch-4.log.txt](https://github.com/elastic/elasticsearch/files/1273083/elasticsearch-4.log.txt)
* [elasticsearch-5.log.txt](https://github.com/elastic/elasticsearch/files/1273084/elasticsearch-5.log.txt)
* [elasticsearch-6.log.txt](https://github.com/elastic/elasticsearch/files/1273085/elasticsearch-6.log.txt)
* [elasticsearch-7.log.txt](https://github.com/elastic/elasticsearch/files/1273091/elasticsearch-7.log.txt)
* [elasticsearch-8.log.txt](https://github.com/elastic/elasticsearch/files/1273092/elasticsearch-8.log.txt)
* [elasticsearch-9.log.txt](https://github.com/elastic/elasticsearch/files/1273093/elasticsearch-9.log.txt)
* [elasticsearch-10.log.txt](https://github.com/elastic/elasticsearch/files/1273094/elasticsearch-10.log.txt)
* [elasticsearch-11.log.txt](https://github.com/elastic/elasticsearch/files/1273159/elasticsearch-11.log.txt)
* [elasticsearch-12.log.txt](https://github.com/elastic/elasticsearch/files/1273160/elasticsearch-12.log.txt)

Edit 1: DateFieldMapper does not always appear in stack traces
Edit 2: Threw away Elasticsearch data directory twice and reproduced twice (see logs 11 and 12)

**Comment by praseodym** [comment]
Edit: DateFieldMapper does not always appear in stack traces

**Comment by jasontedor** [comment]
Duplicates #26198

**Comment by jasontedor** [comment]
Thanks for the report, and thanks for trying out the beta. I have added you to the [Pioneer Program](https://www.elastic.co/blog/elastic-pioneer-program-6-0).

**Comment by praseodym** [comment]
Cheers, thanks for the quick triage!
