### ISSUE TITLE
phonetic token filter : make 'replace' option work for 'beidermorse' encoder

### ISSUE THREAD

**Issue by fbaligand** [elastic/elasticsearch#26486]
Presently, on phonetic token filter, 'replace' option works for all encoders except `beidermorse` encoder.
It would be great to add support for 'replace' option with `beidermorse` encoder.

That is particularly relevant because `beidermorse` is the only encoder which supports multiple languages, not only english.

**Comment by jimczi** [comment]
The `beidermorse` is a filter provided by Lucene so it would be better for you to open this issue in Lucene directly. 
I agree that for consistency the `replace` option should be applicable to all phonetic filters but can you explain the use case for `replace:false` ? It seems to me that you could just use an additional field that does not perform the phonetic transfo and use that at query time with the phonetic field ?

**Comment by fbaligand** [comment]
Indeed, currently, as 'replace' option does not work with `beidermorse`, I use multi-fields, with one simple analyzer, one stemmer analyzer and one phonetic analyzer. Then I use multi-match with different boosts on each analyzer.

With 'replace: false', I could use only one field, so one analyzer with all features : standard, stemmer and phonetic, and then especially combine stemmer and phonetic features. At the end, I have the term in all its possible combinations : stemmed and phonetic, only stemmed, only phonetic (at the same position).

That said, I will open an issue on Lucene, as you mentioned.

**Comment by fbaligand** [comment]
@jimczi 
For info, I opened a issue on Lucene JIRA :
https://issues.apache.org/jira/browse/LUCENE-7954

**Comment by jimczi** [comment]
Thanks @fbaligand 
I am not a big fan of using a single field to index different forms. The multi-fields approach is more flexible because you can boost each form (stemmed, phonetic, ...) differently. Are you concerned about performance when using the multi fields approach ? Since terms are different, the cost should be the same if you index the phonetic and the original form in two fields.

**Comment by jimczi** [comment]
@fbaligand  you can comment directly on the Lucene jira that you opened so I hope you don't mind if I close this issue.

**Comment by fbaligand** [comment]
No problem @jimczi 
I hope especially that Lucene will implement this feature... but given the only answer to the issue, I'm pessimist :(
