### ISSUE TITLE
Use sequences numbers for Compare and Set operations

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#26493]
Elasticsearch currently supports CAS operations (needed for optimistic concurrency) using a document `_version` field. Sadly this [is not water tight](https://www.elastic.co/guide/en/elasticsearch/resiliency/current/index.html#_the__version_field_may_not_uniquely_identify_document_content_during_a_network_partition_status_ongoing) and can go wrong if a primary fails between the read and the CAS write operation. To remedy this we need to move to using a document's `_seq_no` and `_primary_term` fields as an identifier for CAS operations.

To do so we will add two parameters to write operations - `_expected_seq_no` and `_expected_primary_term`. When set, those parameters will require the document to have exactly the expected values in the respective fields for a successful write. 

Note that this can co-exists with the the current `_version` based method, which we can phase out or make optional later on.

Relates #10708

**Comment by dnhatn** [comment]
Hi @jasontedor, I am thinking to work on this. What do you think? Thank you.

**Comment by jasontedor** [comment]
@dnhatn I think we can get there, but let’s work our ways towards it.

**Comment by DaveCTurner** [comment]
Just registering my interest in this too @dnhatn. Please ping me if you're discussing this.

**Comment by dnhatn** [comment]
@DaveCTurner Sure.

**Comment by dnhatn** [comment]
@jasontedor, I have some questions to discuss with you.

1. Is a combination of `(_version, _primary_term)` strong enough to guarantee the uniqueness? The reason I prefer using `_version` over `_seq_no` because `_seq_no` is increased for every write operation on a shard while `_version` is for a document level.

2. Is it good to break this into several smaller steps:
    - [x] Returns `_primary_term` for INDEX/UPDATE requests (We already returned now)
    - [ ] Returns `_primary_term` for GET requests
    - [ ] Returns `_primary_term` for requests (eg. SearchHit)
    - [ ] Implements concurrency control using `(_primary_term and _version)` for GET/DELETE/UPDATE requests

Thank you, Nhat.

**Comment by jasontedor** [comment]
Let’s return to this one in the future after we have addressed some other issues first.

**Comment by dnhatn** [comment]
@bleskes has completed this in https://github.com/elastic/elasticsearch/pull/36467 and the related PRs.
