### ISSUE TITLE
Issue when reading synonyms which contains åäö from a file

### ISSUE THREAD

**Issue by aslamy** [elastic/elasticsearch#26491]
Hi !
I got some exception when I use swedish ÅÄÖ on my synonym words.

```
    {
      "error" : {
        "root_cause" : [
          {
            "type" : "illegal_argument_exception",
            "reason" : "failed to build synonyms"
          }
        ],
        "type" : "illegal_argument_exception",
        "reason" : "failed to build synonyms",
        "caused_by" : {
          "type" : "malformed_input_exception",
          "reason" : "Input length = 1"
        }
      },
      "status" : 400
    }
```

The problem occur when I use a file to read synonyms.
This works fine.

```
   {
	"settings": {
		"index": {
			"analysis": {
				"filter": {
					"synonym": {
						"type": "synonym",
						"synonyms": ["Äpple, App"]
					}
				}
			}
		}
	}
}
```

But not when reading from a file:

```
    {
        "settings": {
            "index" : {
                "analysis" : {
                    "filter" : {
                        "synonym" : {
                            "type" : "synonym", 
                            "synonyms_path" : "synonym.txt",
                            "tokenizer" : "standard" 
                        }
                    }
                }
            }
        }
    }
```

I already read this:
https://discuss.elastic.co/t/synonym-using-a-file-is-not-working-malformed-input-exception/60487/5

I have already  applied an asciifolding token filter before the synonym filter in the filter chain but still not working.

```
       "analysis": {
          "analyzer": {
            "custom_swedish_analyzer": {
              "type": "custom",
              "filter": [
                "asciifolding",
                "lowercase",
                "synonym",
                "swedish_stemmer_filter",
                "swedish_stopwords_filter"
              ],
              "tokenizer": "standard"
            }
```

**Comment by dadoonet** [comment]
Is your file UTF8 encoded?

**Comment by aslamy** [comment]
What do you mean ? If you mean :
å = Ã ¥
ä = Ã ¤
ö = Ã ¶  in UTF8 .
I have tested this way. Now file will be read but when i use åäö to search det synonyms not match. 
But when I use Ã ¥,Ã ¤,Ã ¶ then I get match.

**Comment by jpountz** [comment]
The synonyms file needs to be UTF-8 encoded. You need to change to encoding of your current file by doing something like this: `iconv -t utf-8 -f iso-8859-1 -o synonym_new.txt synonym.txt` (replace iso-8859-1 with the actual charset of your file, which can be found with `file -i synonym.txt`). Then replace `synonym.txt` with `synonym_new.txt`.

**Comment by aslamy** [comment]
Thank you. That worked.
