### ISSUE TITLE
Typo in date format

### ISSUE THREAD

**Issue by aleph-zero** [elastic/elasticsearch#26500]
**Elasticsearch version** (`bin/elasticsearch --version`):
master
**Plugins installed**: []
N/A
**JVM version** (`java -version`):
N/A
**OS version** (`uname -a` if on a Unix-like system):
N/A
**Description of the problem including expected versus actual behavior**:
I believe that there is a typo in org.elasticsearch.common.joda.Joda. As seen below, ```Time``` should not be capitalized, but rather should be ```basic_t_time```.

https://github.com/elastic/elasticsearch/blob/8f0369296f61d8c6ddcf821899715b4d969d4438/core/src/main/java/org/elasticsearch/common/joda/Joda.java#L82

**Comment by ashworx** [comment]
I want to take it as my first PR.

**Comment by jasontedor** [comment]
@ashworx Thanks for your interest but there is an open PR (#26503) for this one already.

**Comment by sumanthrao** [comment]
I would like to contribute to this project, how do I go ahead?
