### ISSUE TITLE
ES returns stored fields of type date as string

### ISSUE THREAD

**Issue by akefirad** [elastic/elasticsearch#26504]
**Elasticsearch version**:
```json
{
  "version": {
    "number": "5.4.2",
    "build_hash": "929b078",
    "build_date": "2017-06-15T02:29:28.122Z",
    "build_snapshot": false,
    "lucene_version": "6.5.1"
  }
}
```
**Description of the problem including expected versus actual behavior**:
When query asks for `stored_fields`, in the result, fields of type date are returned as string, even though they are defined as long (`epoch_millis`). In ES version 1.X it would be long.

**Steps to reproduce**:
1. Create an index with one date field with the following mapping:
```json
{
  "type": "date",
  "store" : true,
  "format" : "epoch_millis"
}
```
 2. Index a document with some date value.
 3. Make the following search query:
```json
{
  "query":{ "match_all": {} },
  "stored_fields": [ "mydate" ]
}
```
4. The result is as follow:
```json
{
  "took": 7,
  "timed_out": false,
  "_shards": {},
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "foo",
        "_type": "bar",
        "_id": "1162256",
        "_score": 1,
        "fields": {
          "mydate": [
            "1504540873381"
          ]
        }
      }
    ]
  }
}
```

**Comment by markharwood** [comment]
String is perhaps being used here as the lowest-common-denominator format.
Date fields can have a number of acceptable formats listed in their mappings and so determining which to use when rendering stored fields may be a challenge.
I have been able to reproduce this example you provided and I expect we either need to look at adding some type-sensitive rendering (if possible) or documenting the current untyped behaviour better.

**Comment by jpountz** [comment]
+1 to documenting. Stored fields do not guarantee that they preserve formatting at the moment.

**Comment by jpountz** [comment]
Discussed in FixitFriday, we agreed to document the current behaviour, at least for now.
