### ISSUE TITLE
Filter nested document for subaggregations

### ISSUE THREAD

**Issue by willcosgrove** [elastic/elasticsearch#26511]
**Describe the feature**:

I'm trying to build a pretty standard search UI, with a sidebar with various filters, and a count next to each option to show the user how many results lie behind each option.  The only unusual thing about the search is that the filters are all on nested items of the documents returned.

I've got the query working perfectly, returning the correct results, but I'm unable to get the correct counts back in my aggregations.

Let me briefly explain the issue I'm trying to solve:

I have an index that has nested fields.  I want to perform terms and range aggregations on some of those nested fields, while also applying a filter on other nested fields.  The filter aggregation is not doing what I need it to do.  Say I have a document, that represents a Winery, that looks like this:

```js
{
  winery_id: 1,
  wines: [
    { price: 3000, score: 90 },
    { price: 40000, score: 100 }
  ]
}
```

If I apply a filter aggregation like this:

```json
"filter": {
  "nested": {
    "path": "wines",
    "query": {
      "range": {
        "wines.scores": {
          "gte": 100
        }
      }
    }
  }
}
```

And then as a subaggregation I do a range on the `wines.price` field with a single bucket of `<= 3000`.  I want elasticsearch to _not_ count the document I mentioned above as part of this range bucket aggregation, because the Winery has no single wine that has a score `>= 100` and a price `<= 3000`.  But it does count it, because the Winery has a wine with a score `>= 100`, and another wine with a price `<= 3000`.

The filter allows the winery through on the condition that one of the wines has a score  `>= 100`.  But the other wines still remain in the winery for the subaggregations of that filter.

I do not know if this is something that is already supported in elasticsearch, but I have poured over the aggregation docs for hours and have played around in the Kibana console for hours, and have not been able to find an aggregation definition that achieves what I'm looking for.

If its not possible, then my feature request is to have some way of making a filter aggregation "knock out" or remove nested documents from subaggregations.

**Comment by colings86** [comment]
Could you paste the full search request you are sending to Elasticsearch?

**Comment by colings86** [comment]
No futher feedback. If you have the full search request please post it here and we can reopen the issue
