### ISSUE TITLE
Dead Link for Offline Install Of X-Pack 6.0.0

### ISSUE THREAD

**Issue by hatdropper1977** [elastic/elasticsearch#26524]
Expected behavior:  Download offline zip for X-Pack 6.0.0
 Actual behavior:  Dead Link

 The X-Pack 6.0.0 [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/installing-xpack-es.html) reads as follows:

> If you want to install X-Pack on a machine that doesn’t have internet access: Manually download the X-Pack zip file: [https://artifacts.elastic.co/downloads/packs/x-pack/x-pack-6.0.0-rc1.zip](https://artifacts.elastic.co/downloads/packs/x-pack/x-pack-6.0.0-rc1.zip) (sha1) 

Clicking the link for download results in the following error:
```xml
<Error>
 <Code>NoSuchKey</Code> 
 <Message>The specified key does not exist.</Message>
 <Key>downloads/packs/x-pack/x-pack-6.0.0-rc1.zip</Key> 
 <RequestId>4773CA7D079A16F4</RequestId>
 <HostId> kxveIxS/6Xp6w5O0yVC014Mfx5qC3zEkhGpIRtfaKT2rCSZrLCHP4gtTu3Az9HKpuyol9+XVRIg= 
</HostId>
</Error>
```

**Comment by jasontedor** [comment]
This is the open source repository for Elasticsearch, we do not handle issues for closed source X-Pack here. For that, we use the X-Pack category on the [forum](https://discuss.elastic.co).

**Comment by jasontedor** [comment]
I pushed 163b99a0f08548bee5299b107d5dbe575c1e7aee.
