### ISSUE TITLE
Cannot start elasticsearch with systemd

### ISSUE THREAD

**Issue by xeccgtt** [elastic/elasticsearch#26538]
We can start eleacticsearch 5.5.2 out side of systemd and  it runs with out issue.  But when we start eleacticsearch 5.5.2 with systemd it fails with the following error.
    [1] bootstrap checks failed
    [1]: max file descriptors [65535] for elasticsearch process is too low, increase to at least [65536]

we modified the following files to try to resolve the issue,  see below:
    /etc/security/limits.conf
    /etc/security/limits.d/20-nproc.conf
    /usr/lib/systemd/system/elasticsearch
These changes did not help.  We must need a different configuration file changed. any id what that file is.  

version of Linux
    Linux 3.10.0-327.13.1.el7.x86_64 #1 SMP Mon Feb 29 13:22:02 EST 2016 x86_64 x86_64 x86_64 GNU/Linux

elasticsearch.service
    [Unit]
    Description=elasticsearch
    After=network.target
    Wants=network.target

    [Service]
    ExecStart=/opt/pki/elasticsearch/bin/elasticsearch -p /opt/pki/elasticsearch_pid/pid
    Restart=on-failure
    RestartSec=20
    StartLimitInterval=20
    StartLimitBurst=5
    User=pkimd1m
    LimitNOFILE=65535

    [Install]
    WantedBy=multi-user.target

/etc/security/limits.conf
     *               soft    nofile          65536
     *               hard    nofile          65536

/etc/security/limits.d/20-nproc.conf
     *               soft    nofile          65536
     *               hard    nofile          65536

/usr/lib/systemd/system/elasticsearch
     LimitNOFILE=65536
     LimitMEMLOCK=unlimited

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by jasontedor** [comment]
Feel free to link from here and I will try to help you but we do not do general help here.

**Comment by xeccgtt** [comment]
Jason,  I moved my question to the forum

https://discuss.elastic.co/t/systemd-can-not-start-elasticsearch/99765
