### ISSUE TITLE
Classloading issues relating to security policy failures

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#26546]
A [recently added assertion](https://github.com/elastic/elasticsearch/commit/c9964d17bf7db7e07e37acbb651d8b54fe644d44) in Security.java is failing and triggering class-loading issues in a new build project.

Examples: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.0+snapshot-false/1/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+snapshot-false/1/console

The assertion fails here:

 	ERROR   0.00s J0 | TransportSearchActionTests (suite) &lt;&lt;&lt; FAILURES!
	 Throwable #1: java.lang.AssertionError
		at org.elasticsearch.bootstrap.Security.readPolicy(Security.java:215)
		at org.elasticsearch.bootstrap.BootstrapForTesting.&lt;clinit&gt;(BootstrapForTesting.java:134)
		at org.elasticsearch.test.ESTestCase.&lt;clinit&gt;(ESTestCase.java:186)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:348)

and then all subsequent tests failed to load the ESTestCase class:

	ERROR   0.00s J0 | SearchModuleTests.initializationError &lt;&lt;&lt; FAILURES!
	 Throwable #1: java.lang.NoClassDefFoundError: org.elasticsearch.test.ESTestCase
		at java.lang.Class.getDeclaredMethods0(Native Method)
		at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
		at java.lang.Class.getDeclaredMethods(Class.java:1975)
		at com.carrotsearch.randomizedtesting.ClassModel$3.members(ClassModel.java:215)

As @jasontedor noted:
    
> The assertion is tripping in an unexpected place, it's implying that the elasticsearch-rest-client JAR is on the class path for core tests which is on its face baffling. This requires investigation to understand why

**Comment by jasontedor** [comment]
I can explain what is happening here. The elasticsearch-rest-client is indeed on the classpath and it turns out this is expected because core tests depend on test framework which has elasticsearch-rest-client as a dependency:

From `gradle :core:dependencies -Dbuild.snapshot=false`

```
testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- org.apache.lucene:lucene-core:7.0.0-snapshot-d94a5f0
+--- org.apache.lucene:lucene-analyzers-common:7.0.0-snapshot-d94a5f0
+--- org.apache.lucene:lucene-backward-codecs:7.0.0-snapshot-d94a5f0
+--- org.apache.lucene:lucene-grouping:7.0.0-snapshot-d94a5f0
+--- org.apache.lucene:lucene-highlighter:7.0.0-snapshot-d94a5f0
+--- org.apache.lucene:lucene-join:7.0.0-snapshot-d94a5f0
+--- org.apache.lucene:lucene-memory:7.0.0-snapshot-d94a5f0
+--- org.apache.lucene:lucene-misc:7.0.0-snapshot-d94a5f0
+--- org.apache.lucene:lucene-queries:7.0.0-snapshot-d94a5f0
+--- org.apache.lucene:lucene-queryparser:7.0.0-snapshot-d94a5f0
+--- org.apache.lucene:lucene-sandbox:7.0.0-snapshot-d94a5f0
+--- org.apache.lucene:lucene-spatial:7.0.0-snapshot-d94a5f0
+--- org.apache.lucene:lucene-spatial-extras:7.0.0-snapshot-d94a5f0
+--- org.apache.lucene:lucene-spatial3d:7.0.0-snapshot-d94a5f0
+--- org.apache.lucene:lucene-suggest:7.0.0-snapshot-d94a5f0
+--- org.elasticsearch:securesm:1.1
+--- net.sf.jopt-simple:jopt-simple:5.0.2
+--- com.carrotsearch:hppc:0.7.1
+--- joda-time:joda-time:2.9.5
+--- org.yaml:snakeyaml:1.15
+--- com.fasterxml.jackson.core:jackson-core:2.8.6
+--- com.fasterxml.jackson.dataformat:jackson-dataformat-smile:2.8.6
+--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.8.6
+--- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.8.6
+--- com.tdunning:t-digest:3.0
+--- org.hdrhistogram:HdrHistogram:2.1.9
+--- org.locationtech.spatial4j:spatial4j:0.6
+--- com.vividsolutions:jts:1.13
+--- org.apache.logging.log4j:log4j-api:2.9.0
+--- org.apache.logging.log4j:log4j-core:2.9.0
+--- org.apache.logging.log4j:log4j-1.2-api:2.9.0
+--- org.elasticsearch:jna:4.4.0-1
+--- org.elasticsearch.test:framework:6.1.0 -> project :test:framework
|    +--- org.elasticsearch.client:elasticsearch-rest-client:6.1.0 -> project :client:rest
|    |    +--- org.apache.httpcomponents:httpclient:4.5.2
|    |    +--- org.apache.httpcomponents:httpcore:4.4.5
|    |    +--- org.apache.httpcomponents:httpasyncclient:4.1.2
|    |    +--- org.apache.httpcomponents:httpcore-nio:4.4.5
|    |    +--- commons-codec:commons-codec:1.10
|    |    \--- commons-logging:commons-logging:1.1.3
|    +--- com.carrotsearch.randomizedtesting:randomizedtesting-runner:2.5.2
|    +--- junit:junit:4.12
|    +--- org.hamcrest:hamcrest-all:1.3
|    +--- org.apache.lucene:lucene-test-framework:7.0.0-snapshot-d94a5f0
|    +--- org.apache.lucene:lucene-codecs:7.0.0-snapshot-d94a5f0
|    +--- org.apache.httpcomponents:httpclient:4.5.2
|    +--- org.apache.httpcomponents:httpcore:4.4.5
|    +--- commons-logging:commons-logging:1.1.3
|    +--- commons-codec:commons-codec:1.10
|    +--- org.elasticsearch:securemock:1.2
|    \--- org.elasticsearch:mocksocket:1.2
+--- com.google.jimfs:jimfs:1.1
\--- com.google.guava:guava:18.0
```

The next question is: why is the assertion tripping given that the JAR is there, we have `build.snapshot` set to `false`, and the version looks right in the dependency? This is because we use `Build.CURRENT.isSnapshot` to determine if we are a snapshot build or not. However, the logic that determines if we are snapshot are not is based on whether or not we are a JAR, and then whether or not a certain entry is in the JAR manifest. When we are running tests, we are not a JAR, we are simply running the classes on the classpath directly from the compiled results on disk. When we are not a JAR, we assume we must be a snapshot. So: we are looking for -6.1.0-SNAPSHOT but only -6.1.0 is there. Thus, the assertion trips and tests explode.
