### ISSUE TITLE
script.allowed_types throws an IllegalArgumentException

### ISSUE THREAD

**Issue by emmerich** [elastic/elasticsearch#26548]
**Elasticsearch version** (`bin/elasticsearch --version`):
`Version: 5.5.2, Build: b2f0c09/2017-08-14T12:33:14.154Z, JVM: 1.8.0_141`

**Plugins installed**: [`ingest-geoip`]

**JVM version** (`java -version`):
```
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-b16)
OpenJDK 64-Bit Server VM (build 25.141-b16, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
`Linux 0ea6bb92d1e2 4.9.41-moby #1 SMP Wed Sep 6 00:05:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
`script.allowed_types: inline` in `elasticsearch.yml` throws an IllegalArgumentException. It should not.

**Steps to reproduce**:

 1. Add `script.allowed_types: inline` to `elasticsearch.yml`
 2. Start ElasticSearch, note the error.
 3. Remove `script.allowed_types: inline` from `elasticsearch.yml`
 4. Restart ElasticSearch, starts correctly.

**Provide logs (if relevant)**:
Full `elasticsearch.yml`:
```
cluster.name: dev-wars
node.name: dev-master
logger.org.elasticsearch.index.analysis: debug

script.allowed_types: none
script.max_compilations_per_minute: 300

action.destructive_requires_name: true
```

**Note**: I am running ElasticSearch using the Docker image:
`docker.elastic.co/elasticsearch/elasticsearch:5.5.2`

**Comment by rjernst** [comment]
@emmerich Can you please provide the actual stack trace for the IAE?

**Comment by colings86** [comment]
No further feedback. If you have the stack trace please post it here and we can reopen the issue
