### ISSUE TITLE
MapperParsingException[failed to parse]; nested: NumberFormatException[empty String]

### ISSUE THREAD

**Issue by Abhishekshukla02** [elastic/elasticsearch#26559]
when latitude and longitude is empty or null getting the Numberformatexception, I have also checked with ignore_malformed: true this is also no working. latitude: type: double index: not_analyzed longitude: type: double index: not_analyzed

**Comment by cbuescher** [comment]
Hi,

this works as expected in 5.5.3:

```
PUT /test
{
  "mappings": {
    "t": {
      "properties": {
        "a": {
          "type": "double",
          "index": false
        },
        "b": {
          "type": "double",
          "index": false
        },
        "c": {
          "type": "double",
          "index": false
        }
      }
    }
  }
}


PUT /test/t/1
{
  "a" : null,
  "b" : "",
  "c": 1.5
}

GET /test/t/_search
{
  "query": {"ids": {"values": [1]}} ,
  "docvalue_fields": ["a", "b", "c"]
}

-->

{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "test",
        "_type": "t",
        "_id": "1",
        "_score": 1,
        "_source": {
          "a": null,
          "b": "",
          "c": 1.5
        },
        "fields": {
          "c": [
            1.5
          ]
        }
      }
    ]
  }
}
```

Please provide a concrete ES version together with a full recreation of the problem if you continue having this problem. I will close this for now, if you still have trouble you can try the [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community), or reopen if you can provide a way to reproduce your exception.
