### ISSUE TITLE
Not able to search from java

### ISSUE THREAD

**Issue by nishanthsolomon** [elastic/elasticsearch#26558]
I want to create a simple java program for elastic search.
from the documentations and examples i came up with the following 
```
package testListJava;
import static org.elasticsearch.node.NodeBuilder.nodeBuilder;

import org.elasticsearch.action.get.GetResponse;
import org.elasticsearch.client.Client;
import org.elasticsearch.node.Node;


public class test {

    public static void main(String[] args) {
    	Node node = nodeBuilder().clusterName("mycluster1").node();
    	Client client = node.client();
    	
    	GetResponse response = client.prepareGet("abc", "def", "1")
    	        .execute()
    	        .actionGet();

        System.out.println(response.toString());  
        System.out.println("-----------------------------------"); 
    }

}
```
But I am not able to get the response.
I get the following error.

Exception in thread "main" java.lang.NoSuchMethodError: org.elasticsearch.common.settings.Settings.settingsBuilder()Lorg/elasticsearch/common/settings/Settings$Builder;
	at org.elasticsearch.node.NodeBuilder.<init>(NodeBuilder.java:57)
	at org.elasticsearch.node.NodeBuilder.nodeBuilder(NodeBuilder.java:63)
	at testListJava.test.main(test.java:12)

what should I do?

I am using elasticsearch-5.5.2.
openjdk version "1.8.0_111"
Eclipse Platform Version: Luna SR1 (4.4.1)

**Comment by dadoonet** [comment]
> what should I do?

Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by gaurav-m** [comment]
Hi 
@nishanthsolomon did you find a fix to your problem?
I'm facing same problem. Can't find a good solution.
