### ISSUE TITLE
repository-gcs plugin not working : service account not readable

### ISSUE THREAD

**Issue by webattitude** [elastic/elasticsearch#26567]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 5.1.2, Build: c8c4c16/2017-01-11T20:18:39.146Z, JVM: 1.8.0_111

**Plugins installed**: []
analysis-icu
repository-gcs
x-pack

**JVM version** (`java -version`):
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux elasticsearch-4-1-vm 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Impossible to create a snapshot repository

**Steps to reproduce**:
```
PUT /_snapshot/gcs
{
  "type": "gcs",
  "settings": {
    "bucket": "es-backup",
    "service_account": "/usr/share/elasticsearch/config/user_account.json"
  }
}
```

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
```
{
  "error": {
    "root_cause": [
      {
        "type": "repository_exception",
        "reason": "[gcs] failed to create repository"
      }
    ],
    "type": "repository_exception",
    "reason": "[gcs] failed to create repository",
    "caused_by": {
      "type": "access_control_exception",
      "reason": "access denied (\"java.io.FilePermission\" \"/usr/share/elasticsearch/config/service_account.json\" \"read\")"
    }
  },
  "status": 500
}
```

**Comment by jasontedor** [comment]
This is not a bug. When you install from a package distribution, configuration goes in /etc/Elasticsearch by default.
