### ISSUE TITLE
Aggregate on _parent field not working with 5.5.2

### ISSUE THREAD

**Issue by hienchu** [elastic/elasticsearch#26571]
I am running on ES 5.5.2, the example mentioned here [aggregating on the _parent field](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-parent-field.html#CO199-2) is not working. I tried on ES 5.4.0 and it works as expected.

**Comment by hienchu** [comment]
Should have go through existing issues....
I tried aggregate on "_parent#[parent_type]" and it works. So this is very likely to be broken by some changes around this.

**Comment by jimczi** [comment]
Thanks for reporting @hienchu 
The ability to use `_parent` directly in aggregations and scripts has been broken in 5.5. The workaround is to use the full name for the field as you already did (`_parent#[parent_type]`). At this point and considering that the `_parent` field will soon disappear (in favor of the `join` field) I am not sure it is worth fixing. We chatted with @martijnvg and said that we can instead document the new syntax and add the breaking change in the release notes.

**Comment by cbuescher** [comment]
cc @elastic/es-search-aggs

**Comment by jimczi** [comment]
The `_parent` field has been removed in 7.0, hence closing
