### ISSUE TITLE
Range queries on range fields accept `relation: disjoint` but treat it as `relation: intersects`

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#26575]
This can be confusing since `disjoint` means the opposite of `intersects`.

**Comment by liketic** [comment]
Hi @jpountz Seems like this is fixed in #26552  What need to do to fix this? Thanks.

**Comment by jpountz** [comment]
@liketic I don't think it is fixed. Documentation states that the relation can be of of `intersects`, `contains` and `within` (https://www.elastic.co/guide/en/elasticsearch/reference/current/range.html) so we need to fix `RangeQueryBuilder` to reject other values.
