### ISSUE TITLE
transportclient  BulkProcessor lost header !!! threadPool().getThreadContext().getHeader

### ISSUE THREAD

**Issue by hexian55** [elastic/elasticsearch#26596]
**Describe the feature**:

BulkProcessor lost threadPool().getThreadContext().getHeader
**Elasticsearch version** (`bin/elasticsearch --version`):
5.5x
**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):
linux macos
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

when I use transport client, put header to threadpool.threadContext.header，
but sometime ,the header lost.
I'm cp BulkProcessor.java BulkRequestHandler.java  
and add log to print threadpool.threadContext.header,  it's lost by sometime.

client code:
client.threadPool().getThreadContext().putHeader("Authorization", token);

BulkRequestHandler update code:
![image](https://user-images.githubusercontent.com/16074700/30317905-2216a6d0-97de-11e7-85a8-5b3e5ccc8fdd.png)

output:
![image](https://user-images.githubusercontent.com/16074700/30318000-6bf3c67a-97de-11e7-8141-8df50039eae4.png)

**Comment by colings86** [comment]
@javanna are you able to have a look at this?

**Comment by colings86** [comment]
Could you explain a bit more about what you are trying to do? Why are you trying to set Authorization headers in this way? If you are trying to authenticate with the XPack Security plugin then this can be done by following the steps in https://www.elastic.co/guide/en/x-pack/current/java-clients.html. The threadpool is almost certainly not going to be the right place to be setting these headers.

**Comment by hexian55** [comment]
I have found a way to fix it. 
I use myself authority plugin.
Add authentication in transportt client header and http header.
but in BulkProcessor, when add request, eg:  bulkProcessor.add(request),

 private synchronized void internalAdd(DocWriteRequest request, @Nullable Object payload) {
        ensureOpen();
        bulkRequest.add(request, payload);
        executeIfNeeded();
    }
if executeIfNeeded(), then execute Immediately in this thread.
but if flushInterval To meet the conditions, then execute Immediately in other thread .
so, this header is lost in other thread.

**Comment by colings86** [comment]
Glad you have found a fix but do note that this is not a supported way of adding headers so this could well break in subsequent versions

**Comment by hexian55** [comment]
I want to fix this code, can reopen this issues?
but if well break in subsequent versions, Can there be other ways to replace it?
Or now i have other better way to do it？

**Comment by hexian55** [comment]
@Override
        public void execute(BulkRequest bulkRequest, long executionId, Map<String, String> headers) {
            if (client.threadPool().getThreadContext().getHeaders() == null && headers != null) {
                client.threadPool().getThreadContext().putHeader(headers);
            }....
I want to add header para in this method.
it's will fix this bug, Do you have a better suggestion?

**Comment by hexian55** [comment]
@colings86

**Comment by colings86** [comment]
> I have found a way to fix it.

I took this as you had solved your problem and your issue was fixed which is why I closed the issue. However, we do reserve this Github issue list only for bug reports and feature requests. It is clear now that this is not a bug in Elasticsearch but rather a question about a bug in your application code. Questions like this should normally be asked in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). Could you create a topic there to discuss this further? I am not familiar enough with this aspect of the codebase to know what the right solution is here

**Comment by hexian55** [comment]
but I think this is es bug, because this header lost in org.elasticsearch.action.bulk.BulkProcessor.

**Comment by colings86** [comment]
@jaymode @javanna is the ThreadContext supposed to be used in this manner to set and get headers and therefore not being able to get the header from the thread context is a bug?

**Comment by hexian55** [comment]
please see org.elasticsearch.action.bulk.BulkProcessor,
BulkProcessor(Client client, BackoffPolicy backoffPolicy, Listener listener, @Nullable String name, int concurrentRequests, int bulkActions, ByteSizeValue bulkSize, @Nullable TimeValue flushInterval) {
        this.bulkActions = bulkActions;
        this.bulkSize = bulkSize.getBytes();

        this.bulkRequest = new BulkRequest();
        this.bulkRequestHandler = (concurrentRequests == 0) ? BulkRequestHandler.syncHandler(client, backoffPolicy, listener) : BulkRequestHandler.asyncHandler(client, backoffPolicy, listener, concurrentRequests);

        if (flushInterval != null) {
            this.scheduler = (ScheduledThreadPoolExecutor) Executors.newScheduledThreadPool(1, EsExecutors.daemonThreadFactory(client.settings(), (name != null ? "[" + name + "]" : "") + "bulk_processor"));
            this.scheduler.setExecuteExistingDelayedTasksAfterShutdownPolicy(false);
            this.scheduler.setContinueExistingPeriodicTasksAfterShutdownPolicy(false);
            this.scheduledFuture = this.scheduler.scheduleWithFixedDelay(new Flush(), flushInterval.millis(), flushInterval.millis(), TimeUnit.MILLISECONDS);
        } else {
            this.scheduler = null;
            this.scheduledFuture = null;
        }
    }

the code will execute other thread,lead to the client.threadPool().getThreadContext().header lost.

Is not that a bug?

**Comment by jaymode** [comment]
I think that this should be considered a issue. We shouldn't lose headers when switching threads as this is the only way for users to provide headers with requests.

**Comment by hexian55** [comment]
if I fix to

 org.elasticsearch.action.bulk.BulkProcessor

    BulkProcessor(Client client, BackoffPolicy backoffPolicy, Listener listener, @Nullable String name, int concurrentRequests, int bulkActions, ByteSizeValue bulkSize, @Nullable TimeValue flushInterval) {
        this.bulkActions = bulkActions;
        this.bulkSize = bulkSize.getBytes();

        this.bulkRequest = new BulkRequest();
        this.bulkRequestHandler = (concurrentRequests == 0) ? BulkRequestHandler.syncHandler(client, backoffPolicy, listener) : BulkRequestHandler.asyncHandler(client, backoffPolicy, listener, concurrentRequests);

        if (flushInterval != null) {
            this.scheduler = (ScheduledThreadPoolExecutor) Executors.newScheduledThreadPool(1, EsExecutors.daemonThreadFactory(client.settings(), (name != null ? "[" + name + "]" : "") + "bulk_processor"));
            this.scheduler.setExecuteExistingDelayedTasksAfterShutdownPolicy(false);
            this.scheduler.setContinueExistingPeriodicTasksAfterShutdownPolicy(false);
            this.scheduledFuture = this.scheduler.scheduleWithFixedDelay(new Flush(client.threadPool().getThreadContext().getHeaders()), flushInterval.millis(), flushInterval.millis(), TimeUnit.MILLISECONDS);
        } else {
            this.scheduler = null;
            this.scheduledFuture = null;
        }
    }



    class Flush implements Runnable {
        private Map<String, String> headers = null;

        public Flush() {
            super();
        }

        public Flush(Map<String, String> headers) {
            this.headers = headers;
        }

        @Override
        public void run() {
            synchronized (BulkProcessor.this) {
                if (closed) {
                    return;
                }
                if (bulkRequest.numberOfActions() == 0) {
                    return;
                }
                if (headers != null) {
                    execute(headers);
                } else {
                    execute();
                }
            }
        }
    }

and  in  org.elasticsearch.action.bulk.BulkProcessor ,add a abstract method
public abstract void execute(BulkRequest bulkRequest, long executionId, Map<String, String> headers);

 @Override
        public void execute(BulkRequest bulkRequest, long executionId, Map<String, String> headers) {
            if (headers != null) {
                client.threadPool().getThreadContext().putHeader(headers);
            }
......

it's ok?

**Comment by jaymode** [comment]
I would look at org.elasticsearch.common.util.concurrent.ThreadContext#preserveContext. We could just use that to wrap the Flush runnable

**Comment by hexian55** [comment]
hi
@jaymode 
I do not know how to use this approach to fix.
Is there a plan to fix this problem in the next version?

**Comment by hexian55** [comment]
hi jaymode

Can you think this is a bug?
