### ISSUE TITLE
Return parent document field only if none of the nested document is matching the given range

### ISSUE THREAD

**Issue by akashmpatel91** [elastic/elasticsearch#26608]
We have a use case where we have a document and it has a nested document based on the dates (A document will have max 365 nested document since we are keeping data for a year). User is giving toDate and fromDate in the input and we are querying the nested document (date field is present in the nested document). But we have a use case where we need to return a field of outer document if none of the inner document is matching with give date range for that outer document. 

Please take below data example
Document1: 
```
{
  "myId": "1",
  "nestedDocumentData": [
    {
     "myInnerDocumentDate": "2017-06-06"
    },
    {
      "myInnerDocumentDate": "2017-07-07"
    },
    {
      "myInnerDocumentDate": "2017-08-08"
    }
  ]
}
```

Document2: 
```
{
  "myId": "2",
  "nestedDocumentData": [
    {
     "myInnerDocumentDate": "2017-06-06"
    }
  ]
}
```

If user input date range as 7/1(1st July) to 8/1(1st August) then output should be myId : 2 which is second document since document 1 has matching date range with given input (In nested document of Document1, 2 nested document has date 7/7 and 8/8).

If user input date range as 6/1 to 7/15 then output should be empty since 6/6 is present in the second document and 7/7 is present in the first document and both the document has AT-LEAST one nested document which is matching the range. 

Any help would be appreciated.

**Comment by colings86** [comment]
@martijnvg are you able to take a look at this?

**Comment by jpountz** [comment]
This looks like a question, not a bug report. Please share this question at discuss.elastic.co, we strive to use Github only for confirmed bugs and feature requests.
