### ISSUE TITLE
CI Failure: Netty3ClientYamlTestSuiteIT

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#26607]
@rjernst Sorry I didn't know who to give this to.  Feel free to re-assign this, you were the last one to touch the Netty3ClientYamlTestSuiteIT, and the tests seem to have been touched by multiple people last.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+intake/149/console

REPRODUCE WITH: gradle :modules:transport-netty3:integTestRunner \
  -Dtests.seed=BE3EC5524585831D \
  -Dtests.class=org.elasticsearch.http.netty3.Netty3ClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=search.aggregation/80_typed_keys/Test typed keys parameter for avg aggregation}" \
  -Dtests.security.manager=true \
  -Dtests.locale=it-IT \
  -Dtests.timezone=Africa/Kampala

REPRODUCE WITH: gradle :modules:transport-netty3:integTestRunner \
  -Dtests.seed=BE3EC5524585831D \
  -Dtests.class=org.elasticsearch.http.netty3.Netty3ClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=delete/26_external_gte_version/External GTE version}" \
  -Dtests.security.manager=true \
  -Dtests.locale=it-IT \
  -Dtests.timezone=Africa/Kampala

REPRODUCE WITH: gradle :modules:transport-netty3:integTestRunner \
  -Dtests.seed=BE3EC5524585831D \
  -Dtests.class=org.elasticsearch.http.netty3.Netty3ClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=delete/26_external_gte_version/External GTE version}" \
  -Dtests.security.manager=true \
  -Dtests.locale=it-IT \
  -Dtests.timezone=Africa/Kampala

REPRODUCE WITH: gradle :modules:transport-netty3:integTestRunner \
  -Dtests.seed=BE3EC5524585831D \
  -Dtests.class=org.elasticsearch.http.netty3.Netty3ClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=cat.aliases/10_basic/Help}" \
  -Dtests.security.manager=true \
  -Dtests.locale=it-IT \
  -Dtests.timezone=Africa/Kampala

REPRODUCE WITH: gradle :modules:transport-netty3:integTestRunner \
  -Dtests.seed=BE3EC5524585831D \
  -Dtests.class=org.elasticsearch.http.netty3.Netty3ClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=indices.refresh/10_basic/Indices refresh test empty array}" \
  -Dtests.security.manager=true \
  -Dtests.locale=it-IT \
  -Dtests.timezone=Africa/Kampala

REPRODUCE WITH: gradle :modules:transport-netty3:integTestRunner \
  -Dtests.seed=BE3EC5524585831D \
  -Dtests.class=org.elasticsearch.http.netty3.Netty3ClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=indices.refresh/10_basic/Indices refresh test empty array}" \
  -Dtests.security.manager=true \
  -Dtests.locale=it-IT \
  -Dtests.timezone=Africa/Kampala

REPRODUCE WITH: gradle :modules:transport-netty3:integTestRunner \
  -Dtests.seed=BE3EC5524585831D \
  -Dtests.class=org.elasticsearch.http.netty3.Netty3ClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=search/30_limits/Rescore window limits}" \
  -Dtests.security.manager=true \
  -Dtests.locale=it-IT \
  -Dtests.timezone=Africa/Kampala

REPRODUCE WITH: gradle :modules:transport-netty3:integTestRunner \
  -Dtests.seed=BE3EC5524585831D \
  -Dtests.class=org.elasticsearch.http.netty3.Netty3ClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=search/30_limits/Rescore window limits}" \
  -Dtests.security.manager=true \
  -Dtests.locale=it-IT \
  -Dtests.timezone=Africa/Kampala

REPRODUCE WITH: gradle :modules:transport-netty3:integTestRunner \
  -Dtests.seed=BE3EC5524585831D \
  -Dtests.class=org.elasticsearch.http.netty3.Netty3ClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=indices.stats/13_fields/Fields - one}" \
  -Dtests.security.manager=true \
  -Dtests.locale=it-IT \
  -Dtests.timezone=Africa/Kampala

REPRODUCE WITH: gradle :modules:transport-netty3:integTestRunner \
  -Dtests.seed=BE3EC5524585831D \
  -Dtests.class=org.elasticsearch.http.netty3.Netty3ClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=indices.stats/13_fields/Fields - one}" \
  -Dtests.security.manager=true \
  -Dtests.locale=it-IT \
  -Dtests.timezone=Africa/Kampala

**Comment by jasontedor** [comment]
The remote node was killed by the OS OOM killer. From the logs for the node:

```
[2017-09-12T15:31:31,192][INFO ][o.e.n.Node               ] version[5.6.1-SNAPSHOT], pid[30347], build[d39ac99/2017-09-12T14:59:10.746Z], OS[Linux/4.8.6-300.fc25.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_144/25.144-b01]
```

From `dmesg`:

```
[11839232.091416] Out of memory: Kill process 30347 (java) score 490 or sacrifice child
[11839232.108042] Killed process 30347 (java) total-vm:16748548kB, anon-rss:8037136kB, file-rss:0kB, shmem-rss:0kB
[11839232.593517] oom_reaper: reaped process 30347 (java), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

This is a CI infrastructure problem that we are tracking internally.
