### ISSUE TITLE
Allow using _exists_ on fields whose data is not indexed

### ISSUE THREAD

**Issue by trevan** [elastic/elasticsearch#26606]
I have indexes that have thousands of fields (especially when you include the ".raw" or ".keyword" version of the fields).  Most of the fields don't need to be queryable or aggregatable, but searching based on the existence of the fields is extremely useful.  As far as I can tell, none of the possible mapping options allow me to disable the indexing of the field values while still allowing me to query if the field exists.

It would be nice if I could flag these fields in the mapping so that I can use \_exists\_ on them while not needing to index the data.

**Comment by jpountz** [comment]
You could potentially look into doing it yourself by adding a new field to your documents that contains the list of fields that they contain. This way you would have full control over what fields are taken into account.

**Comment by trevan** [comment]
@jpountz, I'm planning on doing that but I thought that ES might be doing some special stuff for the field list that I wouldn't be able to duplicate.  I know that I can't use the exists on it, which is a bummer.  But are there optimizations that ES does as well that I wouldn't be able to duplicate?  Or is it really just a separate field that has special handling for exists?

**Comment by jpountz** [comment]
This is actually the way `exists`is implemented. We collect all field names at parsing time and index them under `_field_names` which is later used by `exists` queries.

**Comment by trevan** [comment]
So no special handling other than the `exists` queries?  Good to know.

Can I update `_field_names` myself?  I would like to be able to use the `exists` queries since it doesn't require my users to have to remember that `exists` works for some fieldnames but not for all.

**Comment by jpountz** [comment]
No, you can't update `field_names`. It is totally internal.

**Comment by trevan** [comment]
Is there a way to tell `exists` to use my new field?

Going back to the original request, can ES be changed so that I can add fields to `field_names` that aren't mapped to be indexed?

**Comment by jpountz** [comment]
> Is there a way to tell exists to use my new field?

No.

**Comment by colings86** [comment]
We discussed this in FixItFriday and decided that this is not something we would want to implement as it would add complexity to the mappers for what seems to be a rare use case. This can be implemented by indexing the field names in your document as a custom `my_field_names` field and then use a Term query to determine the documents where the field exists
