### ISSUE TITLE
custom analyzer error for upgrade from es 2.4 to 5.5

### ISSUE THREAD

**Issue by willard-kali** [elastic/elasticsearch#26629]
**Describe the feature**:
I am working on upgrading ES from 2.4.0 to 5.5.0. The issue come when our custom analyzer for existing data in 2.4.0 can't work with ES 5.5.0

**Elasticsearch version** (`bin/elasticsearch --version`):
5.5.0
**Plugins installed**: []
no
**JVM version** (`java -version`):
1.8.0
**OS version** (`uname -a` if on a Unix-like system):
suse
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1.install an es 2.4.0,create template with custom analyzer and make sure it can work
 2.put multi data to es.
 3.upgrade es from 2.4.0 to es 5.5.0 with no data loss, then start cluster.
4. index which using the custom analyzer doesn't work, but others can still work. 

**Provide logs (if relevant)**:
after starting es 5.5.0 cluster, es indices of custom analyzer data is red.for example:

> red    open   index-2017.09.01 _5kVf0JdQe2f4U9xRHUQ4g  20   0                                                  
> red    open   index-2017.09.02 oJHgF926Q7qO7uEMUWwVqw  20   0                                                  
> red    open   index-2017.09.04 OmUDO5WjTvCtwK4cfWqMiQ  20   0                                                  
> red    open   index-2017.09.10 uLf86VbnREKtcY4rfpQsGg  20   0                                                  
> red    open   index-2017.08.28 kohnPoCuSxSosnyQtk_UvQ  20   0                                                  
> red    open   index-2017.09.05 XwhMN_F-S7mrObhfEOFBlw  20   0                                                  
> red    open   index-2017.08.30 F4TdoX3JRL-PmTUEH_U7aw  20   0      

                            

and es logs report:

> [2017-09-13T21:27:15,158][WARN ][o.e.i.c.IndicesClusterStateService] [nM8euBy] [[index-2017.09.05][10]] marking and sending shard failed due to [failed to update mapping for index]
> org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_default_]: analyzer [url_spliter] not found for field [URL]

PS:url_spliter is the custom analyzer.

> "url_spliter" : {
>     "pattern" : "[.|/]",
>     "type" : "pattern"
> }

I find a similar issue:
[updatesettings](https://stackoverflow.com/questions/19758335/error-when-trying-to-update-the-settings)  and flowed it 
close index -> update mapping -> reopen index.
but it doesn't help.

For the issue above, when upgrading ES from 2.4.0 to 5.5.0, how can  I keep the custom analyzer and make it still work for previous data?

**Comment by jimczi** [comment]
I tried to reproduce but the upgrade worked for me. Can you share your 2.4.0 templates and mappings as well as the logs of the upgraded node ?

**Comment by colings86** [comment]
No further feedback. If you have the templates and mappings please share them here and we can reopen the issue
