### ISSUE TITLE
How to sort by aggregations result

### ISSUE THREAD

**Issue by liuzhen88** [elastic/elasticsearch#26638]
hello everyone

this is my code 
response = xx.search query:{},aggs:{
   group_by_store:{
       terms:{
		field:'store_id',
		order:{
			"how to sort by  in_doo/total ?????????"
		},
		size:10
	},
	aggs:{
		total:{
			sum:{
				field:'value'
			}
		},
		in_door:{
			sum:{
				field:'into_door'
			}
		}
}

I want to sort by (in_door/total)  .   How to do ?

Thank you all for your answers

**Comment by jimczi** [comment]
Please ask questions like this in our forum at https://discuss.elastic.co/ . We reserve github issues for verified bugs and feature requests.
