### ISSUE TITLE
Add conditions to Remove Ingest Processor

### ISSUE THREAD

**Issue by LoadingZhang** [elastic/elasticsearch#26645]
**Describe the feature**: I want to remove some fields when it equal to some conditions, such as:
In my nginx log, the value of request_time may be "-",because nginx will automatically fill with "-" if this value is empty, if there have one value is "-", the mapping of this field only should be keyword not number,and I can't do calculate in Kibana or somewhere else.
I don't want this happen, so I want to delete this field if request_time is "-".
Could you add is feature to Remove Processor or other processor if they need too.
Thanks very much.

**Comment by jimczi** [comment]
Please ask questions like this in the [forum](https://discuss.elastic.co/). We reserve github for verified bugs and feature requests.
Regarding your issue you can use the [`script` processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/script-processor.html)  to remove/rewrite the field or set [`ignore_malformed`](https://www.elastic.co/guide/en/elasticsearch/reference/current/ignore-malformed.html) in your mapping.
