### ISSUE TITLE
_cat/aliases throws when no indices has alias

### ISSUE THREAD

**Issue by kirubasankars** [elastic/elasticsearch#26642]
**Elasticsearch version** (`bin/elasticsearch --version`):
5.5.2

**Description of the problem including expected versus actual behavior**:
   GET  _cat/aliases throws when no indices has alias. suppose to has gentle response

**Steps to reproduce**:
   start a fresh elasticsearch instance and do "GET  _cat/aliases". since it has no indices/aliases

**Comment by jasontedor** [comment]
This does not reproduce. Please provide reliable steps to reproduce, and the error messages that you see in the response and in the logs.

**Comment by jasontedor** [comment]
No further feedback, closing.
