### ISSUE TITLE
Feature Request: Support `RestStatus#isSuccess()` method

### ISSUE THREAD

**Issue by moznion** [elastic/elasticsearch#26656]
Motivation
--

I would like to check whether the request succeeded or failed via for each RestStatus enum instance.

e.g.

```java
final SearchResponse searchResponse = client.search(searchRequest);
final boolean isSucceeded = searchResponse.status().isSuccess(); 
//                                                 ~~~~~~~~~~~~ Here

/*
 * Do something...
 */
```

I have a patch so if this proposal looks good, I can send a pull request.
[https://github.com/elastic/elasticsearch/compare/master...moznion:rest_status_util_is_success](https://github.com/elastic/elasticsearch/compare/master...moznion:rest_status_util_is_success)

Misc
--

Is `isSuccess()` just enough?

For example, Perl5's HTTP::Status provides `is_info()`, `is_success()`, `is_redirect()`, `is_error()`, `is_client_error()` and `is_server_error()`.

[http://search.cpan.org/~oalders/HTTP-Message-6.13/lib/HTTP/Status.pm](http://search.cpan.org/~oalders/HTTP-Message-6.13/lib/HTTP/Status.pm)

**Comment by martijnvg** [comment]
@javanna Do you think such an addition to `RestStatus` in the context of the high level client makes sense?

**Comment by javanna** [comment]
I am not sure that this applies to the high-level client. @moznion are you using the transport client or the high-level REST client? With the latter, if you get an error back an exception is thrown, there is no reason to check whether you got back a success response. If you didn't, you would have gotten an exception instead. The only case where this does not currently apply is the Get API where 404 doesn't cause an exception, but `GetResponse` exposes the `isExists` method to be called to verify whether the document was found or not.

That said I think this proposal applies to the transport client, which is being replaced by the high-level REST client. Such a change, although small, would be made to the Elasticsearch codebase, and I am not sure it is needed.

**Comment by moznion** [comment]
> @moznion are you using the transport client or the high-level REST client?

I’m using high-level REST client.

> With the latter, if you get an error back an exception is thrown, there is no reason to check whether you got back a success response.

Does that mean, we don’t have to check the response status? Should we catch the exception to check whether the request is succeeded or not?

Anyway, is this policy documented?

**Comment by javanna** [comment]
Hi @moznion this behaviour is documented [here](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-low-usage-responses.html). That's in the low-level client docs, but given that the high-level client uses it, same applies to the high-level client too. The type of exception that's returned by the high-level client is an `ElasticsearchException` though (as opposed to a `ResponseException`). This is the same behaviour that the transport client used to have, if you are migrating away from it that means you don't need to perform any additional check on the status of the response.

**Comment by moznion** [comment]
@javanna 
I understood. In this case, this feature request looks like not necessary.
Thank you!
