### ISSUE TITLE
Discovery-file plugin always issues a deprecation warning for discovery.type

### ISSUE THREAD

**Issue by franekrichardson** [elastic/elasticsearch#26661]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.0.0-rc2

**Plugins installed**: [discovery-file, found-elasticsearch, repository-s3, x-pack]

**JVM version** (`java -version`): 1.8.0_144

**OS version** (`uname -a` if on a Unix-like system): Alpine Linux

**Description of the problem including expected versus actual behavior**:
The discovery-file plugin always emits the deprecation warning regarding the `discovery.type` config setting regardless of whether or no it is used.:
```
[2017-09-15T12:19:59,562][WARN ][org.elasticsearch.deprecation.discovery.file.FileBasedDiscoveryPlugin] Using discovery.type setting to set hosts provider is deprecated. Set "discovery.zen.hosts_provider: file" instead
``` 

**Steps to reproduce**:

 1. install `discovery-file` plugin
 2. add `discovery.zen.hosts_provider: file` to ES config
 3. ensure `discovery.type` is missing from ES config
 4. start ES

**Comment by rjernst** [comment]
Thanks for trying out the 6.0 beta! This is a warning that is no longer relevant. I've opened a PR to remove this fallback/warning and marked this issue for the Pioneer Program.
