### ISSUE TITLE
Auto expand config settings from environment variables

### ISSUE THREAD

**Issue by tanner-bruce** [elastic/elasticsearch#26676]
When running in a docker/kubernetes environment it would be very useful to be able to set environment variables such as:
```
ES_CLUSTER_NAME=elasticsearch
ES_DISCOVERY_ZEN_PING_UNICAST_HOSTS=...
ES_NETWORK_HOST=...
etc
```

where those variables would then be transferred automatically to the config. It would have to be semi smart to deal with the fact that underscores are already used in the config, however that's definitely not a blocker. This is pretty common across many systems nowadays and would let me drop my initializer script completely.

Also, I would expect this to be done automatically (not via a hard coded list), so that I could set variables for plugins as well, such as `prometheus.indices` for the prometheus exporter.

For an example, see the Confluent Kafka platform: https://docs.confluent.io/current/cp-docker-images/docs/configuration.html

**Comment by rjernst** [comment]
Elasticsearch already provides the ability to use environment variables in config. You can name them whatever you want, and expand them as the value for settings in elasticsearch.yml. See https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html#_environment_variable_substitution.

**Comment by tanner-bruce** [comment]
@rjernst the whole point of this feature request is that you should not need to set them in the elasticsearch.yml as well as in the environment, elasticsearch should be smart about the existing environment variables. See my link to confluent.

**Comment by jasontedor** [comment]
@tanner-Bruce See elastic/elasticsearch-docker#33. For now we are not planning to make any changes in core Elasticsearch along the lines that you are suggesting.
