### ISSUE TITLE
Slowlog settings not working as per documentation

### ISSUE THREAD

**Issue by jayannah** [elastic/elasticsearch#26671]
Referring the same issue https://github.com/elastic/elasticsearch/issues/20927 which is closed .. 

Hi, still see the 5.6 documentation has the same settings.. and I'm getting the same error in ES 5.6 aswell..

https://www.elastic.co/guide/en/elasticsearch/reference/5.6/index-modules-slowlog.html

```
[2017-09-15T16:18:53,965][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: node settings must not contain any index level settings
```

What is t he right configuration? why such important settings are not documented corrected?

**Comment by dadoonet** [comment]
Documentation says:

> All of the above settings are dynamic and are set per-index.

Which means that you can't set that in `elasticsearch.yml` but using update index settings API.

Better to ask this question on discuss.elastic.co where we can give a better support.
As this space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

I'm closing if you don't mind.

**Comment by jayannah** [comment]
Appreciated if there are any examples in the documentation or provide the links.. Thanks for the response.
