### ISSUE TITLE
Is there any intention to retrofit the Java DSL with the http(s) transport?

### ISSUE THREAD

**Issue by jeacott1** [elastic/elasticsearch#26677]
Is there any intention to retrofit the Java DSL with the http(s) transport so that devs dont have to write miles of horrid json and http(s) client stuff, nor wrap everything in custom dsl?

I had assumed when ES said they were ditching the custom transport in favour of http(s) they weren't also intending to ditch the java client along with it, but that doesn't appear to be the case.

Have I missed something?

thanks

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by jeacott1** [comment]
this doesn't seem like a discussion query, just a straight up does the roadmap include a java dsl?
its also not a general question. its very specific and relates directly to both the elastic roadmap and code in this repo.

**Comment by jasontedor** [comment]
Please take a look at the [high-level REST client]( https://www.elastic.co/blog/the-elasticsearch-java-high-level-rest-client-is-out).

If you have additional questions please use the forum. We only track bugs and feature requests here and answer questions on the forum.
