### ISSUE TITLE
Collate queries in phrase suggester not matching correctly

### ISSUE THREAD

**Issue by bencrouse** [elastic/elasticsearch#26715]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.2.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_112

**OS version** (`uname -a` if on a Unix-like system): Darwin Bens-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**: I'm trying to use the collate option to return info based on "active" documents (defined when I index the document). In the script below, I'd expect that the `collate_match` be `false` given this suggestion could not match because the document with the original word has `"active":"false"`. Instead, it's returning the suggestion.
**Steps to reproduce**:
```
curl -XPUT 'localhost:9200/test4?pretty' -H 'Content-Type: application/json' -d'
{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "analysis": {
        "analyzer": {
          "trigram": {
            "type": "custom",
            "tokenizer": "standard",
            "filter": ["standard", "shingle"]
          }
        },
        "filter": {
          "shingle": {
            "type": "shingle",
            "min_shingle_size": 2,
            "max_shingle_size": 3
          }
        }
      }
    }
  },
  "mappings": {
    "test": {
      "properties": {
        "title": {
          "type": "text",
          "fields": {
            "trigram": {
              "type": "text",
              "analyzer": "trigram"
            }
          }
        },
        "active": {
          "type": "keyword"
        }
      }
    }
  }
}
'
curl -XPOST 'localhost:9200/test4/test?refresh=true&pretty' -H 'Content-Type: application/json' -d'
{"title": "noble warriors", "active": "true"}
'
curl -XPOST 'localhost:9200/test4/test?refresh=true&pretty' -H 'Content-Type: application/json' -d'
{"title": "nobel prize", "active": "false"}
'

curl -XPOST 'localhost:9200/test4/_search?pretty' -H 'Content-Type: application/json' -d'
{
  "suggest": {
    "text" : "noble prize",
    "simple_phrase" : {
      "phrase" : {
        "field" :  "title.trigram",
        "size" :   1,
        "direct_generator" : [ {
          "field" :            "title.trigram",
          "suggest_mode" :     "always",
          "min_word_length" :  1
        } ],
        "collate": {
          "query": { 
            "inline" : {
              "match": {
                "active" : "true" 
              }
            }
          },
          "prune": true 
        }
      }
    }
  }
}
'


```

I get this output from that last query:
```
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "suggest" : {
    "simple_phrase" : [
      {
        "text" : "noble prize",
        "offset" : 0,
        "length" : 11,
        "options" : [
          {
            "text" : "nobel prize",
            "score" : 0.5962314,
            "collate_match" : true
          }
        ]
      }
    ]
  }
}
```

**Comment by jimczi** [comment]
This is not how the `collate` option works. The doc says that `collate` checks each suggestion against the specified query to prune suggestions for which no matching docs exist in the index:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-phrase.html
In your example one document matches the query so `collate_match` is set to true. 
The `phrase_suggester` is not document-based, suggestions are build from the term dictionary and they are not associated with a specific document. 
Regarding your issue, you could use a different field `title_active` and set this field for active documents only.

**Comment by bencrouse** [comment]
Thanks for your reply @jimczi - that solution sounds good to me.

I'm still confused by what the intent of the collate feature is then. I read that yesterday and thought this would be what's intended there because of "Checks each suggestion against the specified query to prune suggestions for which no matching docs exist in the index". I took this to mean that for each suggestion, the query provided would be run and the `collate_match` would be based on whether any documents matched that query. I'm having a tough time imagining what else it would do.

I'd appreciate some clarification just for my own understanding, but your solution is easy and reasonable so thanks a lot for your time.

**Comment by s1monw** [comment]
@bencrouse this feature is really there to ensure that you don't provide a _spellchecked_ suggestion to your users that would then return 0 documents. Lets say you have a search box on a website and somebody types in a query. this query string would be turned into an elasticsearch query and executed. With the collate option we try to mimic this behavior to ensure you only get a suggestion back if it would match at least one document given you collate query. I hope this makes more sense?!

**Comment by bencrouse** [comment]
ok, I get it now, I totally misunderstood. I can use it for exactly what I need! thanks for your time and patience @jimczi and @s1monw

**Comment by bencrouse** [comment]
@bradley-pearson6597 this was long ago and unfortunately I don't remember. But I can tell you my original understanding of the collate feature was flawed, and I'm pretty sure the correct understanding led to a solution.
