### ISSUE TITLE
Some Japanese characters changed or missing in aggregations

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch#26728]
Elasticsearch version: 1.7.5
NEST: 1.9.2

Before the "keyword" type, we created our own analyzer to accomplish the same purpose (we called it "tag_analyzer").  As far as I can tell, we're doing everything we should be doing to support languages such as Japanese and yet our aggregations on that field lose or modify some of the characters.  Below I'll include all the pertinent mappings etc. to reproduce.  With those examples, you'll see the Japanese stored and returned properly in the documents themselves but the aggregations produce the unexpected results.  The examples:

1. ビジネスプラン produces ヒシネスフラン
2. Eラーニング produces eラニング

Here is all the repro data required.
```
PUT /_template/test_japanese
{
	"template": "*",
	"settings": {
		"analysis": {
			"analyzer": {
				"tag_analyzer": {
					"type": "custom",
					"tokenizer": "keyword",
					"filter": ["icu_normalizer", "icu_folding"],
					"char_filter": ["html_strip"]
				}
			}
		}
	}
}

PUT /tests_v1
{
	"mappings": {
		"test": {
			"dynamic": "false",
			"properties": {
				"title": {
					"type": "string"
				},
				"tags": {
					"type": "string",
					"fields": {
						"raw": {
							"type": "string",
							"analyzer": "tag_analyzer"
						}
					}
				}
			}
		}
	}
}

PUT /tests_v1/test/1
{
	"title": "This is tagged w/ some Japanese",
	"tags": ["ビジネスプラン"]
}

PUT /tests_v1/test/2
{
	"title": "Another one tagged w/ some Japanese",
	"tags": ["Eラーニング"]
}

POST /tests_v1/test/_search
{
   "aggs": {
      "Category": {
         "filter": {
            "match_all": {}
         },
         "aggs": {
            "Category": {
               "terms": {
                  "field": "tags.raw",
                  "size": 100
               }
            }
         }
      }
   }
}
```

**Comment by tlrx** [comment]
@tdoman I'm pretty sure this is because your terms aggregation works on the tags.raw field, which uses icu_normalizer and icu_folding token filters that change some Japanese signs.

In recent version of Elasticsearch, the ` tags.raw` field could be mapped to a `type: keyword` and no `normalizer` (normalizer are analyzer but for keyword typed fields) and you should get the behavior you're expecting.

**Comment by tdoman** [comment]
@tlrx Thanks, is there a way to emulate the "keyword" type in 1.7.x?  That's essentially what we were trying to do long before the "keyword" type was introduced.

**Comment by tlrx** [comment]
In 1.7 there's the Keyword Analyzer (https://www.elastic.co/guide/en/elasticsearch/reference/1.7/analysis-keyword-analyzer.html). If you still need to filter some chars you can combine the keyword tokenizer (https://www.elastic.co/guide/en/elasticsearch/reference/1.7/analysis-keyword-tokenizer.html) with char_filter.

**Comment by tdoman** [comment]
@tlrx So the problem w/ the Keyword Analyzer is that I need case insensitivity.  Upon further review, I've discovered that the "icu_normalizer" we're using achieves exactly what we need with regard to case but that the "icu_folding" filter is what impacts the Japanese characters.  I'm running tests now but it looks like simply removing the "icu_folding" filter from the custom `tag_analyzer` will accomplish the desired result and will be required for us as we move forward to any version of ES.

**Comment by tlrx** [comment]
> but that the "icu_folding" filter is what impacts the Japanese characters.

Yes, that's what I suspected, maybe I should have suggested to remove this one first. ICU or Ascii folding converts some chars to their "simplified" version. In Latin languages, "ä" is changed to "a" for example.

Note that starting from 5.6, it's possible to use normalizers with `keyword` analyzers. They can be used to lowercase tokens (see https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-normalizers.html)
