### ISSUE TITLE
more like this query: allow informing source and target fields separately.

### ISSUE THREAD

**Issue by pedrocalais** [elastic/elasticsearch#26743]
In a [more like this](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/query-dsl-mlt-query.html) query we can specific input documents like below:

```
GET /_search
{
    "query": {
        "more_like_this" : {
            "fields" : ["title", "description"],
            "like" : [
            {
                "_index" : "imdb",
                "_type" : "movies",
                "_id" : "1"
            },
            {
                "_index" : "imdb",
                "_type" : "movies",
                "_id" : "2"
            },
            "and potentially some more text here as well"
            ],
            "min_term_freq" : 1,
            "max_query_terms" : 12
        }
    }
}
```

However,  if we want to target this MLT query to an index which is not `imbd`, then we have a problem,
because `fields` is applied for both input documents _and_ documents which will be subject to the query. I guess we need to be able to separately inform and filter the source and target fields of an MLT query when they belong to different indexes.

**Comment by s1monw** [comment]
I don't necessarily understand what you are trying to do. as far as I understand you want to use documents to build MLT but then query a different field names on the target index? Is this conceptually correct or did you just model your data differently but they are semantically the same?

**Comment by james-daily** [comment]
We have the same issue: multiple indices (with different mappings) but comparable fields.  For example, we would like to compare `index1.type1.title` to `index2.type2.description`.

As it is we have to construct an artificial document, which means 1) sending a lot of information over the wire and 2) slower queries because Elasticsearch has to re-analyze the fields every time.

**Comment by chvndb** [comment]
We also have this issue, where documents from one index are related to document from another index in a structured way. When we do our `more_like_this` query, we want to exclude those that we already know that are related. 

In other words, we have a bool query with multiple `more_like_this` queries that `should` match and 1 `more_like_this` queries that `must_not` match. Where the `must_not` is used similar to SQL `where not equals`.

**Comment by talevy** [comment]
Pinging @elastic/es-search-aggs

**Comment by markharwood** [comment]
The available workaround is to GET the doc first, pull into your client and then create an artificial doc to perform MLT on. Obviously this involves more clientside work but the proposed alternative will add complexity to define the field mappings (which source fields go to which target fields and in which indices) and has the issue that different fields may use different analyzers so the tokens found in one index+field may not be interoperable with those from another.

Closing for the above reasons.

**Comment by cduranleau** [comment]
> and has the issue that different fields may use different analyzers so the tokens found in one index+field may not be interoperable with those from another.

Is that a new problem? E.g. index1.type1.description and index2.type1.description might not be interoperable already?

I'm now to the ES ecosystem so that might be a silly question with a simple answer I'm not seeing.

**Comment by markharwood** [comment]
This came up again in https://github.com/elastic/elasticsearch/issues/35509 which we are currently keeping open, pending some feedback.
