### ISSUE TITLE
Simple substring query seems to be impossible with Elasticsearch/Lucene--please add it.

### ISSUE THREAD

**Issue by szalapski** [elastic/elasticsearch#26759]
**Describe the feature**:  

In Elasticsearch, it seems impossible to search for an arbitrary substring, perhaps including spaces. (Searching for part of a word isn't quite enough; I want to search any substring of an entire field.)

Suppose I have only a few thousand documents in my Elasticsearch index, and I try:

  "query": {
         "wildcard" : { "description" : "*plan*" }
  }
That works as expected--I get every item where "plan" is in the description, even ones like "supplantation".

Now, I'd like to do

  "query": {
         "wildcard" : { "description" : "*plan is*" }
  }   
...so that I might match documents with "Kaplan isn't" among many other possibilities.

I was hoping there might be something built-in for this Elasticsearch, given that this simple substring search seems like a very basic capability (Thinking about it, it is implemented as strstr() in C, LIKE '%%' in SQL, Ctrl+F in most text editors, String.IndexOf in C#, etc.), but this seems not to be the case. It seems this isn't possible with wildcard, match prefix, or any other query type I might see. How do I simply search on any substring?

I could use a RegExp query, but even that is limited to a field that uses the keyword analyzer and is 32K or less.  I also have to convert my term to lowercase, even if the data has uppercase.

(I am aware any such query would be slow or perhaps even impossible for large data sets.)

See also https://stackoverflow.com/questions/30379094/elasticsearch-regexp-with-space-not-working

**Comment by jbaiera** [comment]
@jimczi Thoughts on this?

**Comment by s1monw** [comment]
This is a pretty standard usecase for ngrams. Yet, we don't do thinks like `IndexOf` that is linear to the number of terms in the term dictionary. In order to match efficiently you gotta index your stuff in accordingly. Take a look at https://www.elastic.co/guide/en/elasticsearch/reference/5.6/analysis-ngram-tokenizer.html and please ask your questions in our discuss forums http://discuss.elastic.co

**Comment by szalapski** [comment]
ngrams is too complicated and peculiar for this simple case.  Wildcard could be extended to support this.

**Comment by s1monw** [comment]
I am sorry but scanning terms is not going to fly for us. We are committed to make our software scale, full scans don't scale at all and the majority of users have a large amount of data. It might be that elasticsearch is not the right tool for you then. I don't necessarily understand why you can't user ngrams and a simple match query.

**Comment by s1monw** [comment]
also if you store your values as docvalues you can just use a script query and do whatever you want with it if you feel like this is how you wanna use elasticsearch. it won't scale and is very slow

**Comment by szalapski** [comment]
Simple substring search seems like a very basic capability.  Thinking about it, it is implemented as strstr() in C, LIKE '%%' in SQL, Ctrl+F in most text editors, String.IndexOf in C#, etc.
