### ISSUE TITLE
Kibana in Chrome doesn't degrade gracefully when there is an issue with returned data

### ISSUE THREAD

**Issue by digitalrinaldo** [elastic/elasticsearch#26757]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

Version: 5.6.0, Build: 781a835/2017-09-07T03:09:58.087Z, JVM: 1.8.0_144

**Plugins installed**: []

None

**JVM version** (`java -version`):

java version "1.8.0_144"

**OS version** (`uname -a` if on a Unix-like system):

4.4.0-1013-aws #22-Ubuntu SMP

**Description of the problem including expected versus actual behavior**:

Kibana/Chrome has issues when large datasets are returned. 

**Steps to reproduce**:

Perform a query using Kibana in chrome that returns a large amount of data. A 38Mb return is causing the issue today for me. However I have seen this problem over and over. 

Do a date historgram in seconds on 180K records and chrome crashes.  Was this a silly thing for the user to do yes. 

**Provide logs (if relevant)**:

There are no logs, the browser says snap something went wrong every time

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch. For Kibana, you can use the Kibana [repository](https://gitub.com/elastic/kibana).

**Comment by digitalrinaldo** [comment]
Sorry thanks.
