### ISSUE TITLE
failed to put mappings on indices  crash the elasticsearch 

### ISSUE THREAD

**Issue by newbei** [elastic/elasticsearch#26766]
1 we have the some index like ics_pcs_2017.06.06
2 we delete the some old index use jave code:
	getClient.admin().indices().prepareDelete(indexname).execute().actionGet()
	
	I think the index ics_pcs_2017.06.06 will have 60G+ and 100,000,000 documents in it.
	
3 we make a new logstash to receive old logs,and we found in the ES log:
	ES logs info
	
	create index for ics_pcs_2017.06.06(didn't get the detail log)
	
	.....
	[o.e.c.m.MetaDataCreateIndexservice] create index cause [auto(bulk api)], templates[icstemplate],shards [6]/[1], mappings [icslog]
	
	.....
	[o.e.c.m.MetaDataCreateIndexservice] [ics_pcs_2017.06.06/xtNoHLSOS4GBQo01-Nprg] update_mapping [icslog]
	
	...
	[o.e.a.a.1.m.p.TransportPutMappingAction] [ics-master1] failed to put mappings on indices[[[ics_pcs_2017.06.06/xtNoHLSOS4GBQo01-Nprg]]]
	org.elasticsearch.cluster.metada.ProcessClusterEventTimeoutException:failed to process cluster event(put-mapping) within 30s
	
	....
	-----------
	then there is many logs like  failed to put mappings on indices[[[ics_pcs_2017.06.06/xtNoHLSOS4GBQo01-Nprg]]]
	... failed to put mappings on indices[[[ics_pcs_2017.06.06/xtNoHLSOS4GBQo01-Nprg]]]
	...failed to put mappings on indices[[[ics_pcs_2017.06.06/xtNoHLSOS4GBQo01-Nprg]]]
	
	and cause the elasticsearch master down.

Would you please help and explain the reason, thanks a lot.

**Comment by tlrx** [comment]
Hi @newbei, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elastic forums](https://discuss.elastic.co/) instead. Thank you!
