### ISSUE TITLE
Painless filter returns error "Variable [doc] is not defined."

### ISSUE THREAD

**Issue by Bargs** [elastic/elasticsearch#26760]
**Elasticsearch version** (`bin/elasticsearch --version`): master
**JVM version** (`java -version`): 1.8.0_131
**OS version** (`uname -a` if on a Unix-like system): macOS Sierra 10.12.6

**Description of the problem including expected versus actual behavior**:

In Kibana, when a user interacts with the UI to create a filter on a scripted field, we create a script filter that looks like this:

```
{
  "script": {
    "script": {
      "inline": "boolean compare(Supplier s, def v) {return s.get() == v;}compare(() -> { doc['bytes'].value * 2; }, params.value);",
      "lang": "painless",
      "params": {
        "value": 6022
      }
    }
  }
```

In this case, `doc['bytes'].value * 2;` is the user defined script. The rest we add in order to do a comparison against the value the user's script produces.

In master, the above script query is returning the following error:

```
{
  "type": "query_shard_exception",
  "reason": "failed to create query: {\n  \"bool\" : {\n    \"must\" : [\n      {\n        \"match_all\" : {\n          \"boost\" : 1.0\n        }\n      },\n      {\n        \"script\" : {\n          \"script\" : {\n            \"source\" : \"boolean compare(Supplier s, def v) {return s.get() == v;}compare(() -> { doc['bytes'].value * 2; }, params.value);\",\n            \"lang\" : \"painless\",\n            \"params\" : {\n              \"value\" : 6022\n            }\n          },\n          \"boost\" : 1.0\n        }\n      },\n      {\n        \"range\" : {\n          \"@timestamp\" : {\n            \"from\" : null,\n            \"to\" : null,\n            \"include_lower\" : true,\n            \"include_upper\" : true,\n            \"boost\" : 1.0\n          }\n        }\n      }\n    ],\n    \"adjust_pure_negative\" : true,\n    \"boost\" : 1.0\n  }\n}",
  "index_uuid": "nqVm9Xt2QPGXJ7M5myvrPg",
  "index": "logstash-0",
  "caused_by": {
    "type": "script_exception",
    "reason": "compile error",
    "script_stack": [
      "... () == v;}compare(() -> { doc['bytes'].value * 2; } ...",
      "                             ^---- HERE"
    ],
    "script": "boolean compare(Supplier s, def v) {return s.get() == v;}compare(() -> { doc['bytes'].value * 2; }, params.value);",
    "lang": "painless",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "Variable [doc] is not defined."
    }
  }
}
```

I can't reproduce in 6.0 or 5.6 so this seems to be a relatively recent change.

cc @nik9000 since he helped us put together the script originally

**Comment by rjernst** [comment]
I spent some time debugging this with Jack and we have a test case that reproduces the issue. It looks like it will only affect filter scripts on 6.1/7.0. We should have a fix in plenty of time before 6.1 is cut.

**Comment by Bargs** [comment]
Awesome, thank you!

**Comment by rjernst** [comment]
This was "fixed" temporarily in #26824. It will go back to "unfixed" in 7.0.

**Comment by Bargs** [comment]
@rjernst I'm confused, this issue was about `doc`/`params` being used inside lambdas in Painless. As far as I understand, it has nothing to do with the issue with expression scripts. I just retested with a master build and this Painless bug still exists.

**Comment by Bargs** [comment]
@rjernst this bug is also still causing Kibana CI to fail when we try to test against master, so it's high severity for us. Our CI for master is still stuck on an ES build from months ago. I think the fact that this bug fails Kibana CI was hidden by the other (unrelated) issue with expression based scripts.

**Comment by rjernst** [comment]
Sorry @Bargs I got confused with multiple issues.

**Comment by epixa** [comment]
@rjernst Is there anything you need from us to help with this?  @Bargs mentioned that this was high severity for us a couple weeks ago, but now that 6.x is bumped to 6.2 and we're working on getting 6.1 stable enough to release, this has become critical.  We can't run CI on 6.x at all, and both master and 6.1 CI are running against commits that are a couple months old (July).

**Comment by jdconrad** [comment]
I will give this my full attention today.

**Comment by jdconrad** [comment]
@Bargs @epixa This should be fixed.  Apologies for taking so long to get this in.
