### ISSUE TITLE
Illegal combination of [copy_to] and [nested] mappings in elasticsearch-6.0.0-beta2

### ISSUE THREAD

**Issue by osthus-co** [elastic/elasticsearch#26763]
**Elasticsearch version**:  6.0.0-beta2, Build: 23ffa4f/2017-08-29T01:53:03.739Z, JVM: 1.8.0_131

**Plugins installed**: none

**JVM version**: 1.8.0_131-b11

**OS version**: Windows 7 64 bit

**Description of the problem including expected versus actual behavior**:

Version six no longer supports [copy_to] and [nested], see mapping below. This worked in version 5.

**Steps to reproduce**:

{
	"mappings": { 
		"types": {
			"properties": {
				"prop1": {
					"type": "nested",
					"properties": {
						"prop2": {
							"type": "keyword", "copy_to": "prop1.prop2.completion",
							"fields": {
								"completion": { "type": "completion" }
							}
						}
					}
				}
			}
		}
	}
}

**Response**:

{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Illegal combination of [copy_to] and [nested] mappings: [copy_to] may only copy data to the current nested document or any of its parents, however one [copy_to] directive is trying to copy data from nested object [**prop1**] to [**prop1**]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "Illegal combination of [copy_to] and [nested] mappings: [copy_to] may only copy data to the current nested document or any of its parents, however one [copy_to] directive is trying to copy data from nested object [prop1] to [prop1]"
    },
    "status": 400
}

**Comment by tlrx** [comment]
@jpountz Do you have an opinion regarding this issue and you change in #25983?

**Comment by jpountz** [comment]
@osthus-co Thanks for testing out beta2! There is indeed a bug in the validation since we should accept copying between two fields that are under the same nested object. However your mapping has another problem which is that it copies to a multi-field, which is not necessary since multi-fields are already populated with the value of their parent field. I'll fix the issue and improve the error message in case of multi-fields.

**Comment by osthus-co** [comment]
Thank you for the explanation and the fix.
