### ISSUE TITLE
Wrong version of elasticsearch been imported to  project automatically

### ISSUE THREAD

**Issue by holygost** [elastic/elasticsearch#26767]
I use  gradle to build my project and I import the following dependencies:

        compile ("org.elasticsearch:elasticsearch:5.5.0") {  
            exclude group:'org.apache.logging.log4j'  
        }   

        compile ("org.elasticsearch.client:transport:5.5.0"){  
            exclude group:'org.apache.logging.log4j'  
        }  
        compile ("org.elasticsearch.client:x-pack-transport:5.5.0"){  
            exclude group:'org.apache.logging.log4j'  
        }  
after building project completely , I found there has `org.elasticsearch:elasticsearch:5.5.0` and `org.elasticsearch:elasticsearch:1.5.2`。And when I run my project, the  actual running jar is `org.elasticsearch:elasticsearch:1.5.2` 。

My project environment  as follows:
springboot: 1.3.1.RELEASE
gardle : gradle-2.14.1
OS: macOS 10.12.6 (But in windows the issue also exists.)

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
