### ISSUE TITLE
Logger Failure with High Level Rest Client BulkProcessor API

### ISSUE THREAD

**Issue by sahibdes** [elastic/elasticsearch#26762]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):5.6.0

**Plugins installed**: []

**JVM version** (`java -version`):1.8

**OS version** (`uname -a` if on a Unix-like system):Mac OS Sierra

**Description of the problem including expected versus actual behavior**:
While using the BulkProcessor API, on creating the threadpool i get this error:
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.debug(Ljava/lang/String;Ljava/lang/Object;)V
	at org.elasticsearch.threadpool.ThreadPool.<init>(ThreadPool.java:203)
**Steps to reproduce**:
	ThreadPool threadPool = new ThreadPool(Settings.builder().put(Node.NODE_NAME_SETTING.getKey(), "high-level-client").build());

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Use the bulkprocessor api for high level client
 2. Create threadpool object by passing Settings.builder().put(Node.NODE_NAME_SETTING.getKey(), "high-level-client").build() as argument.

**Provide logs (if relevant)**:
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.debug(Ljava/lang/String;Ljava/lang/Object;)V
	at org.elasticsearch.threadpool.ThreadPool.<init>(ThreadPool.java:203)

**Comment by jasontedor** [comment]
Please check the Log4j 2 dependency that you have on the classpath. For 5.6.0 you need Log4j 2.9.0 (api and core). I think you have another version on your classpath and JAR hell is causing this method to not be found. We are working on removing the thread pool dependency from core so that problems like this do not arise so much in the future.

**Comment by jasontedor** [comment]
Relates #26727
