### ISSUE TITLE
_update_by_query's default size accidentally changed to 1000

### ISSUE THREAD

**Issue by rfraposa** [elastic/elasticsearch#26761]
**Describe the feature**:  `scroll_size` seems to be ignored in my request

**Elasticsearch version** (`bin/elasticsearch --version`):  6.0.0-beta2

**Plugins installed**: []

**JVM version** (`java -version`): JDK 8

**OS version** (`uname -a` if on a Unix-like system): Ubuntu

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

No matter what value I set for `scroll_size`, the following request only updates 1,000 documents:
```
POST crimes/_update_by_query?scroll_size=4000
{
  "query" : {
    "match": {
      "area.ward": "6"
    }
  },
  "script" : {
    "source" : "ctx._source.area.ward=10"
  }
}
```
Here is the response I get:
```
{
  "took": 112,
  "timed_out": false,
  "total": 1000,
  "updated": 1000,
  "deleted": 0,
  "batches": 1,
  "version_conflicts": 0,
  "noops": 0,
  "retries": {
    "bulk": 0,
    "search": 0
  },
  "throttled_millis": 0,
  "requests_per_second": -1,
  "throttled_until_millis": 0,
  "failures": []
}
```

Am I doing something wrong?

**Comment by nik9000** [comment]
It looks like you have 1000 documents and a scroll size of 4000. This all looks correct. What is wrong?

**Comment by rfraposa** [comment]
It's the other way around. I have over 4,000 documents that match that query, so I set scroll_size to 4000 so I could update them all in one request. But only 1,000 get updated at a time. I have the run the `_update_by_query` four times to get all documents updated, which is not what I expected.

**Comment by nik9000** [comment]
I've reproduced this locally. The `size` parameter is getting set to the scroll size accidentally.

**Comment by nik9000** [comment]
@rfraposa I've renamed this to the actual issue.

**Comment by nik9000** [comment]
Note: this doesn't effect 5.6. I've not tracked down the patch that changed it but I'll put together a fix.

**Comment by nik9000** [comment]
This is the script I used to reproduce it:
```
for i in $(seq 1 4000); do
    curl -HContent-Type:application/json -XPOST localhost:9200/test/test -d'{"test": "test"}'; echo
done

curl -XPOST localhost:9200/_refresh

curl -HContent-Type:application/json -XPOST 'localhost:9200/test/_update_by_query?refresh&pretty' -d'{
    "query":  {
        "match": {
            "test": "test"
        }
    },
    "script": {
        "inline": "ctx._source.foo=\"bar\""
    }
}'
```

That last one *should* return `4000` documents updated but it returns `1000`.

**Comment by nik9000** [comment]
Better reproduction:
```
for i in $(seq 1 4000); do
    curl -HContent-Type:application/json -XPOST localhost:9200/test/test -d'{"test": "test"}'; echo
done

curl -XPOST localhost:9200/_refresh

curl -HContent-Type:application/json -XPOST 'localhost:9200/test/_update_by_query?refresh&pretty'


#This one it ok!
curl -HContent-Type:application/json -XPOST 'localhost:9200/_reindex?refresh&pretty' -d'{
    "source": {
        "index": "test"
    },
    "dest": {
        "index": "dest"
    }
}'


curl -HContent-Type:application/json -XPOST 'localhost:9200/dest/_delete_by_query?refresh&pretty' -d'{
    "query": {
        "match_all": {}
    }
}'
```

Shows that this effects `_update_by_query` and `_delete_by_query` but not `_reindex`.

**Comment by nik9000** [comment]
I dropped the `blocker` label because we're ok with having this be a "known issue". I have opened up a PR to fix it though.
