### ISSUE TITLE
JsonGenerationException: Can not write a field name, expecting a value

### ISSUE THREAD

**Issue by lailaiququ** [elastic/elasticsearch#26765]
MaxAggregationBuilder maxBuilder = AggregationBuilders.max("maxInfo");
search:"{ }" maxBuilder:"{"error" : JsonGenerationException: Can not write a field name, expecting a value}"

elasticsearch version 5.4.2 
jdk 1.8+

**Comment by da091314** [comment]
you can ingore this error reason，and the response is right

**Comment by lailaiququ** [comment]
Thank You !
