### ISSUE TITLE
all new index can't allocate the shard

### ISSUE THREAD

**Issue by feiyuewuyue** [elastic/elasticsearch#26772]
set "cluster.routing.allocation.exclude._ip" : "ipname" after set the parameter and the shard move all, I stop the node, when I start the same node and set "cluster.routing.allocation.include._ip" : "pre ipname",all new index can't allocate the shard

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by feiyuewuyue** [comment]
my version is 5.2.0,the "cluster.routing.allocation.exclude._ip" : "ipname" take effect,but when I restart the node and set "cluster.routing.allocation.include._ip" : "pre ipname",all index can't relocate,new index shard can't locate
