### ISSUE TITLE
Not able to perform remote reindex with X-Pack Elastic Search

### ISSUE THREAD

**Issue by saurabhdhingra89** [elastic/elasticsearch#26789]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.1

**Plugins installed**: [X-Pack]

**JVM version** (`java -version`): 1.8.0_121

**OS version** (`uname -a` if on a Unix-like system): Windows 7

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Facing issue when doing reindexing remotely with X-Pack enabled
Eg:
```
POST /_reindex   
{
	"source": {
		"remote": {
			"host": "http://<whitelist-ip>"
		},
		"index": "stage_de"
	},
	"dest": {
		"index": "live_de"
	}
}
```

Getting below error in reponse(authentication token is missing however I have verified authentication token is passed in the header)):
```
{
	"error": {
		"root_cause": [
			{
				"type": "status_exception",
				"reason": "body={\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}}],\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}},\"status\":401}"
			}
		],
		"type": "status_exception",
		"reason": "body={\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}}],\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}},\"status\":401}",
		"caused_by": {
			"type": "response_exception",
			"reason": "GET http://10.203.102.174:9200/: HTTP/1.1 401 Unauthorized\n{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}}],\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}},\"status\":401}"
		}
	},
	"status": 401
}
```

While below is working fine(Non remote reindex request)
```
POST /_reindex
{
	"source": {
		"index": "stage_de"
	},
	"dest": {
		"index": "live_de"
	}
}
```

Issue is when trying to reindex remotely, when tried with removing remote host it works fine. Also when X-Pack is disabled reindex works fine remotely

**Comment by tvernum** [comment]
Hi @saurabhdhingra89,

This repository is specifically for bugs and feature tracking for open source elasticsearch.
Since this is an X-Pack issue, we'd ask that you raise it on our [discuss forum](https://discuss.elastic.co/) instead.

Before you do, however you might want to check on the [reindex from remote docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docs-reindex.html#reindex-from-remote). There are specific fields for passing the username and password to the remote cluster.   

Thank you.

**Comment by saurabhdhingra89** [comment]
Thanks @tvernum
