### ISSUE TITLE
allow date math on 'now' with || operator and add recursive '||' processing

### ISSUE THREAD

**Issue by rcrezende** [elastic/elasticsearch#26780]
Because of only this 'else', there are two ways to do date math. If you use 'now' you can't use '||' operator. If you don't use 'now' you have to use '||' operators. See it here:

https://github.com/elastic/elasticsearch/blob/ee802ad63c0f21d697a5095dd05dc6f94626ee4d/core/src/main/java/org/elasticsearch/common/joda/DateMathParser.java#L63

This special case adds unnecessary complexity when generating queries programatically.

Without such else, and maybe adding a code that keeps looking for additional '||', the user code can always just append ('||' + term) without special casing.

if that is implemented, an expression like `"now||-1d/d"` is accepted.
if the recursive "||" makes sense, then the expression `"now||-1d/d||-1d||-1d"` is also valid. Which could be interpreted two ways: or the last overrides all, so `-1d` is the only rounding operation applied. Or the result is `-1d` + rounding, then applied to this result `-2d`.

**Comment by jpountz** [comment]
Can you give a concrete example of some date math expressions that do not work today and that you would like to make work? For instance I believe `now||-1d/d` could be stated as `now-1d/d` and your second example `now||-1d/d||-1d||-1d` looks made up?

**Comment by rcrezende** [comment]
This comes from a feature in a custom ES ui-client when we rewrite the user defined dates with templates.

For instance, a template could be:
```{{timefilter.time.from}}||/d+1d```

Then the template variable ```{{timefilter.time.from}}``` would be resolved to whatever the user selects in the UI. That allows users to define generic expressions for date range filters that would be dynamically resolved at runtime when someone selects the actual date intervals in the UI.

But because there is a special case in the parser, the expression ```{{timefilter.time.from}}||/d+1d``` is not always correct because ```{{timefilter.time.from}}```  can be resolved to the string 'now'.
Implementing such feature, with current ES time expression parsing logic, requires also parsing on the client to merge properly with the template expression.

If '||' could be used with 'now' and multiple '||' allowed, the template expression would be correct regardless of ```{{timefilter.time.from}}```.

Another example:
```
{{timefilter.time.from}} = 'now-3M/d'
template = '{{timefilter.time.from}}||/d+7d'

rewrite => 'now-3M/d||/d+7d' (which is incorrect for ES)
```

Not having such feature doesn't block the date templating, but adds unnecessary complexity when rewriting the template. The above would be rewritten to
 ```
resolve_now_to_the_hardcoded_now_date_at_runtime||-3M/d/d+7d
```

**Comment by jpountz** [comment]
Thanks for the explanation of your needs. I added the `discuss` label. cc @elastic/es-search-aggs

**Comment by jpountz** [comment]
We re-discussed this issue today and agreed to close it for now. While we understand the motivation, we'd like to see more traction to actually implement something like that.
