### ISSUE TITLE
Fuzzy query with fuziness set to AUTO fails on short keywords

### ISSUE THREAD

**Issue by stembi** [elastic/elasticsearch#26783]
**Elasticsearch version** (`bin/elasticsearch --version`):5.1.1

**Plugins installed**: [none]

**JVM version** (`java -version`):java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):Windows 7 Professional 64bit

**Description of the problem including expected versus actual behavior**: Fuzzy query with fuziness set to AUTO does not find exact matches on short fields (1-3 chars)

**Steps to reproduce**:

DELETE /my_index
PUT my_index
{
   "mappings": {
      "my_type": {
         "properties": {
            "title": {
               "type": "text",
               "fields": {
                  "raw": {
                     "type": "keyword"
                  },
                  "text" :{
                      "type": "text"
                  }
               }
            }
         }
      }
   }
}

POST /my_index/my_type/_bulk
{ "index": { "_id": 9 }}
{ "title": "Fahid AL-JASSIM" }

POST /my_index/my_type/_search
{
   "query": {
      "fuzzy": {
         "title.text": {
            "value": "Al",
            "fuzziness": "AUTO"
         }
      }
   }
}

The query is not able to find the entry with id:8. I expect it would be found.

**Provide logs (if relevant)**:

**Comment by stembi** [comment]
It seems the **problem is with case sensitivity**:
ES is passing the indexed documents to the lowercase filter, which stores all the keyword in lowercase.
On the other side, the query itself is doing no analysis of searched text (in our case the "Al"),and because fuzziness is set to 0 (exact match), no match is found. It seems I just misunderstood the ES concept of Fuzzy query - this behaviour is not described anywhere in the documentation. Could anyone confirm this is the **origin** of the problem?

**Comment by s1monw** [comment]
the fuzzy query doesn't apply tokenization / normalization to the terms you pass in. You should use match query instead like this:

```JSON
curl -XGET 'localhost:9200//my_index/my_type/_search?pretty' -H 'Content-Type: application/json' -d'
{
    "query": {
        "match" : {
            "title.text" : {
                "query" : "AI",
                "fuzziness" : "AUTO"
            }
        }
    }
}'
```
