### ISSUE TITLE
Why the response status of the error "Result window is too large" is 500?

### ISSUE THREAD

**Issue by akefirad** [elastic/elasticsearch#26799]
I encountered the following error:
```
{
    "error":{
        "root_cause":[
            {
                "type":"query_phase_execution_exception",
                "reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [100000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."
            }
        ],
        "type":"search_phase_execution_exception",
        "reason":"all shards failed",
        "phase":"query",
        "grouped":true,
        "failed_shards":[...]
    },
    "status":500
}
```
My question is why the status is 500? It's more of client's fault, isn't it? Shouldn't it be 4XX?

**Comment by javanna** [comment]
I would agree on this, thanks for pointing it out. I think the status code is un unwanted side effect of the exception used for this error message, and the exception that it inherits from.

**Comment by liketic** [comment]
@javanna Can we just response a bad request status for `QueryPhaseExecutionException` ? thanks.

**Comment by javanna** [comment]
@liketic yes that would be a better thing to do.

**Comment by javanna** [comment]
Not sure though if 4xx should be associated with `QueryPhaseExecutionException` which can also be a server side problem. The solution may also be to use a different exception for these cases where we validate user input.

**Comment by liketic** [comment]
Some possible options:
1) Bind 4xx status to `QueryPhaseExecutionException ` 
2) Replace `QueryPhaseExecutionException` in those cases with `IllegalArgumentException`
3) Create a new exception extends `QueryPhaseExecutionException`
4) find a another existing exception to replace `QueryPhaseExecutionException` in those places and response 4xx.

Do you prefer which one? Thanks!

**Comment by akefirad** [comment]
I'd not associate 4xx to all `QueryPhaseExecutionException` either. IMHO the best is option 3, but 2 is also works.
