### ISSUE TITLE
RPM install problem

### ISSUE THREAD

**Issue by githubmui** [elastic/elasticsearch#26797]
RPM install of Elasticsearch 5.6.2 on SLES11-SP3 failed with following error:
   elasticsearch-5.6.2.rpm: headerRead failed: Header sanity check: OK

FYI: But RPM install of Logstash 5.6.2 and Kibana 5.6.2 on SLES11-SP3 succeeded.

**Comment by tvernum** [comment]
Hi @githubmui 

I'm afraid we don't support RPM installs on SLES 11, as SLES uses a very old version of RPM.
Unfortunately, you will need to install from zip/tgz.

See the `**` footnote on https://www.elastic.co/support/matrix#matrix_os and https://github.com/elastic/elasticsearch/issues/17470#issuecomment-213418616
