### ISSUE TITLE
Bucket Script not working for division of counts of two queries

### ISSUE THREAD

**Issue by dipak84patel** [elastic/elasticsearch#26816]
I am very new to bucket script and trying to resolve this since few days now. I am trying perform division operation on counts of two queries and having hard time resolving this. What i am trying to do is `count(query1)/count(query2)` and both of these queries are in `message `field. Below is what i have done so far -

```
GET /index/_search
{
  "size": 0,
  "aggs": {
    "parent_agg": {
      "terms": {
        "field": "message"
      },
      "aggs": {
        "four_oh_fours": {
          "filter": {
            "term": {
              "log_message": "404"
            }
          },
          "aggs": {
            "count": {
              "value_count": {
                "field": "message"
              }
            }
          }
        },
        "other": {
          "filter": {
            "term": {
              "log_message": "500"
            }
          },
          "aggs": {
            "count": {
              "value_count": {
                "field": "message"
              }
            }
          }
        },
        "404s_over_others": {
          "bucket_script": {
            "buckets_path": {
              "four_oh_fours": "four_oh_fours.count",
              "other": "other.count"
            },
            "script": "return params.four_oh_fours / (params.other == 0 ? 1: params.other)"
          }
        }
      }
    }
  }
}
```

Also i would like to know once this is in place whether it would be possible to create a visual that shows division count in dashboard. I would appreciate any help.

**Comment by bleskes** [comment]
@dipak84patel thanks for the question. We keep github for bugs and feature requests. For questions and more general discussions we use our forums on http://discuss.elastic.co . Do you mind asking there? I'm going to close this. If it turns out that there is some bug that prevents you from doing what you want we can always reopen.
