### ISSUE TITLE
Saved Search Failing in Dashboard vs Discover

### ISSUE THREAD

**Issue by KnechtionsCoding** [elastic/elasticsearch#26818]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.1 Build 667b497/2017-09-14T19.22.05.189Z

**Plugins installed**: [None]

**JVM version** (`java -version`): 1.8.0_144

**OS version** (`uname -a` if on a Unix-like system): Centos 7.4.1708

**Description of the problem including expected versus actual behavior**: When creating a particular dashboard, which includes a saved search, the following error occurs:

```
Error: Request to Elasticsearch failed: {"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"fetch","grouped":true,"failed_shards":[],"caused_by":{"type":"class_cast_exception","reason":null}},"status":503}
    at http://elk-01-dev-victory.kmi.lan/bundles/kibana.bundle.js?v=15533:29:12495
    at Function.Promise.try (http://elk-server.company.com/bundles/commons.bundle.js?v=15533:82:22232)
    at http://elk-server.company.com/bundles/commons.bundle.js?v=15533:82:21602
    at Array.map (<anonymous>)
    at Function.Promise.map (http://elk-server.company.com/bundles/commons.bundle.js?v=15533:82:21557)
    at callResponseHandlers (http://elk-server.company.com/bundles/kibana.bundle.js?v=15533:29:12111)
    at http://elk-server.company.com/bundles/kibana.bundle.js?v=15533:29:366
    at processQueue (http://elk-server.company.com/bundles/commons.bundle.js?v=15533:38:23621)
    at http://elk-server.company.com/bundles/commons.bundle.js?v=15533:38:23888
    at Scope.$eval (http://elk-server.company.com/bundles/commons.bundle.js?v=15533:39:4619)
```

This despite the search working when viewing it through the discover section.

Elasticsearch is running just fine, no logs related to this have been generated in the /var/log/elasticsearch/elasticsearch.log.

Kibana, and logstash are running just fine as well.
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Honestly, no idea
 2.
 3.

**Provide logs (if relevant)**:

**Comment by bleskes** [comment]
This sounds like an issue that is better opened on the kibana repo: https://github.com/elastic/kibana . Can you please post there?
