### ISSUE TITLE
Fix documents about inline script

### ISSUE THREAD

**Issue by ligyxy** [elastic/elasticsearch#26823]
I am following the document of Update API, Scripted Updates section, https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#_scripted_updates

But when running the first sample query, I get error "[script] unknown field [source], parser not found", and I realize that the script code should be under "inline" field instead of "source".

```
POST test/type1/1/_update
{
    "script" : {
        "inline": "ctx._source.counter += params.count",
        "lang": "painless",
        "params" : {
            "count" : 4
        }
    }
}
```

**Comment by rjernst** [comment]
You are reading docs for the current version (ie 5.6.2). `source` works in that version (and using `inline` is deprecated and removed in 6.0).
