### ISSUE TITLE
Upgrade ANTLR to 4.5.3

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#26834]
Currently painless depends on ANTLR-4.5.1-1 which is not only old but also a patch release to 4.5.1. Upgrading to 4.5.3 provides some bug fixes and a stable enough version that didn't require any patching :)

**Comment by jdconrad** [comment]
I'll try to look at this next week.

**Comment by jonkblack** [comment]
It looks as though 4.7 is also a drop in replacement, tests ran on my machine with no errors.
