### ISSUE TITLE
Example in high level rest client doc is incorrect

### ISSUE THREAD

**Issue by dedemorton** [elastic/elasticsearch#26842]
The following feedback was received through a customer contact form:

2017-09-28 03:26:47
Documentation in: https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-getting-started-initialization.html The code snippet is wrong, it's missing .buid()

**Comment by cbuescher** [comment]
This documentation on master is correct, the API has slightly changed between the alpha and beta releases but the current docs reflect the state of the current RC. On 5.6 the documentation is also correct. The API is different there though, in as far as the RestHighLevelClient constructor takes a low level RestClient as argument, not a RestClientBuilder like on the 6.0 branch.
