### ISSUE TITLE
Delete By Query Request Run on Alias needs Security Rights to Base Index

### ISSUE THREAD

**Issue by c-varberg** [elastic/elasticsearch#26858]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.5.1

**Plugins installed**: ["xpack"]

**JVM version** (`java -version`): 1.8.0_131

**OS version** (`uname -a` if on a Unix-like system): CentOS 7.3.1611

**Description of the problem including expected versus actual behavior**:

In order to run the _delete_by_query on an alias the user needs "delete" privileges to the actual index. I would expect that as long as the user has read/write rights to the alias they would be able to run a _delete_by_query. It is also confusing as the request will return a 200 OK as long as there isn't actually anything to delete. If it finds something to delete then it fails out with a 403 Forbidden. I'm assuming once it finds something to delete it is trying to issue the actual delete on the index instead of the alias.

I am specifically trying to do this with a filtered alias, but I have tested it with a non filtered alias and the same results are seen

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create a new index `PUT testindex`
 2. Add an alias `POST testindex/_alias/testalias`
 3. Create role with read and write rights to alias 
`POST _xpack/security/role/testRole
{
    "indices": [
      {
        "names": [
          "testalias"
        ],
        "privileges": [
          "write",
          "read"
        ]
      }
    ]
}`
4. Create user with the role just created
`POST _xpack/security/user/testUser
{
    "roles": [
      "testRole"
    ],
    "password": "elastic"
}`
5. Run _delete_by_query on alias using new user (200 OK is returned)
`POST testalias/_delete_by_query
{
  "query":{
    "match_all": {}
  }
}`
6. Add document to index
`GET testindex/testtype/1
{
  "name": "test"
}`
7. rerun _delete_by_query on Alias with same user (403 Forbidden Returned)

**Provide logs (if relevant)**:

`{
      "index": "testindex",
      "type": "testtype",
      "id": "1",
      "cause": {
        "type": "security_exception",
        "reason": "action [indices:data/write/bulk[s]] is unauthorized for user [testUser]"
      },
      "status": 403
}`

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch only. We do not handle X-Pack issues here, only in the X-Pack category on the [forum](https://discuss.elastic.co). Would you please open a topic there?

**Comment by c-varberg** [comment]
Thanks for the help jason. I'll move it over to the forum
