### ISSUE TITLE
span_multi broken with numeric range query

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#26859]
In #23119 range queries were optimized when doc values are present (which are enabled by default). However, the new query type (IndexOrDocValuesQuery) returned in this case by NumberFieldMapper.rangeQuery is not handled by SpanMultTermQueryBuilder. It is unclear to me if span_multi can even be supported with a non-term based query, but in that case should probably pass along this information in parsing to force the rangeQuery method to use the non docvalues based query.

**Comment by jimczi** [comment]
The `span_multi` does not support numeric range query but it accepts term range query. 
In es the range query builder cannot differentiate a range query over numerics or terms until the inner build of the Lucene Query. This is why a `span_multi` accepts an inner range query and only fails at build time when it discovers that the range query is not a `TermRangeQuery`:
https://github.com/elastic/elasticsearch/blob/927111c91dac5e3cef868eead3cfe8fd4075bee5/core/src/main/java/org/elasticsearch/index/query/SpanMultiTermQueryBuilder.java#L135
The error message seems ok to me, it alerts the user that the inner query is unsupported. 
How did you encounter this issue @rjernst ? 
With https://github.com/elastic/elasticsearch/pull/23119 only the error message should have changed (from an anonymous class in PointRangeQuery to an IndexOrDocValuesQuery).

**Comment by rjernst** [comment]
Thanks @jimczi. I was confused, nothing to see here. :)
