### ISSUE TITLE
Move everything that depends on JTS to a module

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#26850]
It is easy today to accidentally depend on jts either directly or via spatial4j. Maybe we should move everything that depends on it to a module and remove the dependencies on spatial4j and jts from core?

**Comment by dadoonet** [comment]
![image](https://user-images.githubusercontent.com/274222/31068876-3b495900-a75a-11e7-8815-0a59da24316f.png)

**Comment by s1monw** [comment]
+1

**Comment by jpountz** [comment]
It ended up being more challenging than I thought. I'd suggest to revisit it once shape indexing doesn't require JTS anymore.

**Comment by mark-vieira** [comment]
@jpountz sine this is really a code refactoring, I'm not sure this is strictly a delivery team issue. What area team do you think would be most appropriate to assign this to?

**Comment by rjernst** [comment]
Server no longer depends on JTS or spatial4j. That has been relegated to the legacy-geo module, so I think this issue has been addressed.
