### ISSUE TITLE
SnapshotStatus.toString() always returns a error message

### ISSUE THREAD

**Issue by liketic** [elastic/elasticsearch#26851]
The method `toString` of class `SnapshotStatus` always got a error message:
`{ "error" : "Can not start an object, expecting field name (context: Object)"}`. 

The `toString`:

https://github.com/elastic/elasticsearch/blob/dbea83a1d017bd85ba4e9cdf7e910ce5be7b0610/core/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStatus.java#L162

The `startObject()` of `builder` called twice because it will be called in the start of `toXContent()`.

**Comment by jasontedor** [comment]
For reference we do not require an issue to open a PR. You can open a PR and explain the issue within the PR and that is preferred since it reduces the number of notifications. We really only need issues opened for bugs that aren’t immediately going to see a PR.

**Comment by liketic** [comment]
Got it. Thanks.
