### ISSUE TITLE
Tribe plugin dependency not available on elasticsearch maven

### ISSUE THREAD

**Issue by sksamuel** [elastic/elasticsearch#26867]
The 6.0.0-rc1 build for x-pack-security requires x-pack-api which in turn requires tribe.
```
<dependency org="org.elasticsearch.plugin" name="tribe" rev="6.0.0-rc1" force="true" conf="compile->compile(*),master(compile);runtime->runtime(*)"/>
```
However this is not available.
https://artifacts.elastic.co/maven/org/elasticsearch/plugin/tribe/6.0.0-rc1/tribe-6.0.0-rc1.pom

Other plugins like netty4 are,
https://artifacts.elastic.co/maven/org/elasticsearch/plugin/transport-netty4-client/6.0.0-rc1/transport-netty4-client-6.0.0-rc1.pom

**Comment by danielmitterdorfer** [comment]
Thanks for reporting @sksamuel. 

@hub-cap, @rjernst could you please check why the tribe artifact is missing? I compared the build files of both modules and I guess that the tribe module is missing a config option:

```
esplugin {
    // this is probably missing in for the tribe module?
    hasClientJar = true
}

I guess the x-pack API artifact that is mentioned in the original report needs to reference then the client JAR?

**Comment by jasontedor** [comment]
We know why it's missing. The bigger question is whether or not it's needed and we can remove this as a dependency for the transport clients (I think so?).

**Comment by rjernst** [comment]
I think this is simply a misconfiguration in xpack. It pulls in tribe and netty4 in order to reuse code from them, but it does not actually have an added runtime dependency on them, and certainly this does not transpose to the x-pack transport-client.  I'm going to close this as it is not an elasticsearch oss issue.

**Comment by sksamuel** [comment]
You've closed this without a solution? Or are you saying its user error?

**Comment by rjernst** [comment]
@sksamuel This is a problem with xpack. This repo is for open source elasticsearch. We will fix this internally with xpack, as the xpack transport client should not depend on tribe at all.

**Comment by sksamuel** [comment]
I understand. Thanks.
