### ISSUE TITLE
Unable to download Elasticsearch 6.0.0-rc1 tarball SHA1

### ISSUE THREAD

**Issue by prehor** [elastic/elasticsearch#26862]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.0.0-rc1, Build: b9c0df2/2017-09-25T19:11:45.815Z, JVM: 1.8.0_144

**Plugins installed**: []

**JVM version** (`java -version`): 
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
CentOS Linux release 7.4.1708 (Core) Docker image

**Description of the problem including expected versus actual behavior**:
For Elasticsearch up to 6.0.0-beta2 I can download tarball SHA1 file from:
https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0-beta2.tar.gz.sha1 
and check tarball integrity. This URL scheme does not work for 6.0.0-rc1 and SHA1 file is missing:
https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0-rc1.tar.gz.sha1

Logstash and Kibana are also affected.

**Steps to reproduce**:

1. curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0-rc1.tar.gz.sha1

**Comment by jasontedor** [comment]
Starting with 6.0.0-rc1 we do not produce sha1 anymore, instead [sha512](https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.0.0-rc1.tar.gz.sha512).
