### ISSUE TITLE
Windows Service Does Not Read Config from Custom Path

### ISSUE THREAD

**Issue by isapir** [elastic/elasticsearch#26873]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.2

**Plugins installed**: []

**JVM version** (`java -version`): 1.8u144

**OS version** (`uname -a` if on a Unix-like system): Windows 2008R2

**Description of the problem including expected versus actual behavior**:

Installing the service with a custom config directory does not work.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Set CONF_DIR to a custom directory
 2. call bin/elasticsearch-service.bat install

The problem is that instead of setting `-Des.path.conf="%CONF_DIR%"` the installer sets `-Des.default.path.conf="%CONF_DIR%"`, so the custom config directory is not used, and the custom `elasticsearch.yml` is not read.

**Comment by jasontedor** [comment]
Okay, I can reproduce this and I see the bug. I will come up with a fix. Thanks for the report.

**Comment by jasontedor** [comment]
@isapir I opened #26875; would you be able to verify that this fixes your issue?

**Comment by jasontedor** [comment]
Closed by #26875

**Comment by isapir** [comment]
@jasontedor I can understand your argument about "default" vs. values in `elasticsearch.yml` for `logs` and `data` directories, but how does that apply to the `config` directory?  

The `config` directory can not be overridden in `elasticsearch.yml` because `elasticsearch.yml` is read from the `config` directory.

**Comment by jasontedor** [comment]
@isapir That's not right, in 5.x you can start Elasticsearch with a configuration file that points to another configuration file via `path.conf` (this is no longer the case in 6.x).
