### ISSUE TITLE
date_histogram does not support extended_bounds with dynamic ranges

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#26876]
While trying to use `extended_bounds` with the `date_histogram`, I ran into an issue where I could not supply `now`.

```json
    "detect_no_reports": {
      "date_histogram": {
        "field": "timestamp",
        "interval": "30s",
        "min_doc_count": 0,
        "extends_bounds": {
          "min": "now-60m",
          "max": "now"
        }
      },
      "aggs": {
        "empty_filter": {
          "bucket_selector": {
            "buckets_path": {
              "count": "_count"
            },
            "script": "params.count == 0"
          }
        }
      }
    }
```

The use case here is detecting unexpected gaps in the data. But the problem is that `min` and `max` expect the value to be parsed solely as a `long`.

- `ExtendedBounds.PARSER` is the cause here https://github.com/elastic/elasticsearch/blob/2bdeee88402cf40c66ec889ba5b05a617d556dc0/core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/ExtendedBounds.java#L48
- `DateHistogramAggregationBuilder.PARSER` uses it https://github.com/elastic/elasticsearch/blob/2bdeee88402cf40c66ec889ba5b05a617d556dc0/core/src/main/java/org/elasticsearch/search/aggregations/bucket/histogram/DateHistogramAggregationBuilder.java#L115

Relates to https://github.com/elastic/elasticsearch/issues/24244 (which by asking for this feature, I'm asking to not do).

**Comment by polyfractal** [comment]
Closing, date math is supported in ExtendedBounds now.  

Couldn't quite find the commit when it was added (maybe during the histo/date_histo split? dunno), but there are definitely tests for it now: https://github.com/elastic/elasticsearch/blob/master/server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/ExtendedBoundsTests.java#L113
