### ISSUE TITLE
Mustache: Newlines in scripts are ignored in some cases

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#26882]
**Elasticsearch version** (`bin/elasticsearch --version`): master and below

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

I added the following test in `MustacheTests` to show the issue

```
    public void testNewLinesInIterables() {
        List<Map<String, String>> hits = Arrays.asList(
                Collections.singletonMap("value", "1"),
                Collections.singletonMap("value", "2"),
                Collections.singletonMap("value", "3"));

        Map<String, Object> params = Collections.singletonMap("hits", hits);
        // this adds a new line, when there is an additional character present
        assertScript("{{#hits}}A{{value}}\n{{/hits}}END\n", params, equalTo("A1\nA2\nA3\nEND\n"));
        // this adds new newline, the assertion fails
        assertScript("{{#hits}}{{value}}\n{{/hits}}END\n", params, equalTo("1\n2\n3\nEND\n"));
    }
```

The second example, which does not contain any other characters, except the value and the newline will not print out the newline at all. Adding a second newline makes the assert pass, but for the wrong reasons

```
       // passes
        assertScript("{{#hits}}{{value}}\n\n{{/hits}}END\n", params, equalTo("1\n2\n3\nEND\n"));
```

I have not debugged further.

**Comment by nikoncode** [comment]
I can try to take a look on that.

**Comment by nikoncode** [comment]
This bug is not related to ES codebase, it's inside mustache.java library.

**Comment by jdconrad** [comment]
Clsing this as a workaround has been presented in mustache issue.
