### ISSUE TITLE
Simplify underscore requirements in parameters

### ISSUE THREAD

**Issue by ZLightning** [elastic/elasticsearch#26886]
**Describe the feature**:  When updating a document through the update API, we have to specify parameters like retry_on_conflict without a leading _ in query-string parameters, but on the bulk API, we have to include the parameter as _retry_on_conflict in the action/meta line.  Remembering when to use _ can be confusing to the user.  This is even more true when using a library like elasticsearch.js where you have to specify parameters such as index, type, and id in one case and _index, _type, _id in another.  Elasticsearch should accept parameters in the action/meta line with or without the leading _, and it seems this is already true of some parameters like version/_version and routing/_routing.

**Comment by clintongormley** [comment]
Discussed in FixItFriday.  We agree that we should make this consistent with where these parameters are used in other APIs, eg:

* `_index`, `_type`, and `_id` would keep their underscores, because that is how the fields are named
* params like `version` and `retry_on_conflict` would be without underscores as that is how they are used in other APIs
* `_source` would be with underscore also because that is how it is used in other APIs

This should be deprecated for as long as possible before making the breaking change.

**Comment by PnPie** [comment]
Hello,
We are going to remove all the leading underscore in _Bulk API_ for the parameters like `version`, `routing` etc. ? or we just add support for the two format like `_version/version`. The latter is what we do currently, and not only in _Bulk API_, and also in for example _Multi Get API_, the body of _More Like This Query_ and _Term Vectors_

**Comment by clintongormley** [comment]
> We are going to remove all the leading underscore in Bulk API for the parameters like version, routing etc

Yes.  We make it consistent with how these parameters are used elsewhere (obviously with a deprecation period).

> not only in Bulk API, and also in for example Multi Get API, the body of More Like This Query and Term Vectors

thanks for pointing those out.  we should do the same in these APIs

**Comment by sumanthrao** [comment]
I would like to work on this if no one is working.

**Comment by orinn248** [comment]
I'm looking into this as well

**Comment by mayya-sharipova** [comment]
@sumanthrao @orinn248 I have already finished the implementation on this, will create a PR soon

**Comment by jasontedor** [comment]
Thanks @mayya-sharipova, I’m removing the [adoptme](https://github.com/elastic/elasticsearch/labels/adoptme) label.
