### ISSUE TITLE
default.data.path tried although data.path defined

### ISSUE THREAD

**Issue by andreas-p** [elastic/elasticsearch#26883]
With 5.6.2 on Debian9, I configured data.path to point to a dedicated partition. 
When starting the service, it will fail stating "Unable to access 'default.path.data' (/var/lib/elasticsearch)" which is the distribution's preferred location, but was removed to prevent trouble. 

Seems there are still some remnants after the https://github.com/elastic/elasticsearch/issues/23981 cleanup.

**Comment by jasontedor** [comment]
There should be an underlying cause, for example a filesystem permissions issue. This is expected though. If we can’t access the directory, we can’t verify the problem in #23981 is not present, so we fail. You need to read the cause and fix the problem. This is not a bug.

**Comment by andreas-p** [comment]
IMHO trying to access a directory that is configured away by path.data *is* a bug.
The workaround was to create a read-only the directory /var/lib/elasticsearch again.

**Comment by jasontedor** [comment]
In 5.6 it’s not a bug because we are trying to verify whether or not the consequences of a previous bug are present. The system is operating as intended.
