### ISSUE TITLE
Installation fails in debian

### ISSUE THREAD

**Issue by ntwobike** [elastic/elasticsearch#26889]
I'm getting this when i try to update, any thoughts?

```
root@Debian-90-stretch-64-minimal /etc/apt # uname -a
Linux Debian-90-stretch-64-minimal 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
root@Debian-90-stretch-64-minimal /etc/apt # apt-get update -o Dir::Etc::sourcelist="sources.list.d/elastic-5.x.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
Ign:1 https://artifacts.elastic.co/packages/5.x/apt stable InRelease
Ign:2 https://artifacts.elastic.co/packages/5.x/apt stable Release
Ign:3 https://artifacts.elastic.co/packages/5.x/apt stable/main amd64 Packages
Ign:4 https://artifacts.elastic.co/packages/5.x/apt stable/main all Packages
Ign:5 https://artifacts.elastic.co/packages/5.x/apt stable/main Translation-en
Ign:3 https://artifacts.elastic.co/packages/5.x/apt stable/main amd64 Packages
Ign:4 https://artifacts.elastic.co/packages/5.x/apt stable/main all Packages
Ign:5 https://artifacts.elastic.co/packages/5.x/apt stable/main Translation-en
Ign:3 https://artifacts.elastic.co/packages/5.x/apt stable/main amd64 Packages
Ign:4 https://artifacts.elastic.co/packages/5.x/apt stable/main all Packages
Ign:5 https://artifacts.elastic.co/packages/5.x/apt stable/main Translation-en
Ign:3 https://artifacts.elastic.co/packages/5.x/apt stable/main amd64 Packages
Ign:4 https://artifacts.elastic.co/packages/5.x/apt stable/main all Packages
Ign:5 https://artifacts.elastic.co/packages/5.x/apt stable/main Translation-en
Ign:3 https://artifacts.elastic.co/packages/5.x/apt stable/main amd64 Packages
Ign:4 https://artifacts.elastic.co/packages/5.x/apt stable/main all Packages
Ign:5 https://artifacts.elastic.co/packages/5.x/apt stable/main Translation-en
Err:3 https://artifacts.elastic.co/packages/5.x/apt stable/main amd64 Packages

Ign:4 https://artifacts.elastic.co/packages/5.x/apt stable/main all Packages
Ign:5 https://artifacts.elastic.co/packages/5.x/apt stable/main Translation-en
Reading package lists... Done
W: The repository 'https://artifacts.elastic.co/packages/5.x/apt stable Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://artifacts.elastic.co/packages/5.x/apt/dists/stable/main/binary-amd64/Packages
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by andyb-elastic** [comment]
It looks like this is resolved, please let us know if you're still seeing it.

**Comment by shanehenry** [comment]
I am still seeing this issue when running 'sudo apt-get update && sudo apt-get install elasticsearch'

**Comment by mxc** [comment]
I am getting this to when I run apt-get update.

> Reading package lists... Done                        
> E: The repository 'https://artifacts.elastic.co/packages/5.x/apt stable Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

I can install elastic but "apt get install kibana" results in "E: Unable to locate package kibana"

**Comment by andyb-elastic** [comment]
Hi @mxc @shanehenry @ntwobike thanks for reporting. We're not able to reproduce this on a fresh debian stretch container or vm. Can you please confirm the only apt sources you have configured for Elastic are as described in [the deb documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html) and note whether this issue is still occurring? Thanks

**Comment by mxc** [comment]
It turned out to be the apt-cacherng proxy that we are using rejecting https connection requests. I had to add it to the bypass list in apt-cacherng configuration and all is working now.  Thanks

**Comment by slancio** [comment]
I'm getting the exact same issue on ubuntu, with the line:
`E: Failed to fetch https://artifacts.elastic.co/package/5.x/apt/dists/stable/main/binary-amd64/Packages  404  Not Found` in about the same place.

Currently trying to get filebeat/metricbeat installed.

**Comment by yafp** [comment]
> It turned out to be the apt-cacherng proxy that we are using rejecting https connection requests. I had to add it to the bypass list in apt-cacherng configuration and all is working now. Thanks

I had a similar issue here, editing `acng.conf` and adjusting the `PassThroughPattern` helped. Thanks @mxc
