### ISSUE TITLE
Can not start an object, expecting field name (context: Object) for ClusterHealthRequest

### ISSUE THREAD

**Issue by floragunncom** [elastic/elasticsearch#26894]
**Elasticsearch version** (`bin/elasticsearch --version`):
5.5.1

**Plugins installed**: []

**JVM version** (`java -version`):
1.8.0_102 Oracle Corporation

**OS version** (`uname -a` if on a Unix-like system):
Mac OS X x86_64 10.10.5

**Description of the problem including expected versus actual behavior**:
XContentHelper.toString() outputs `Can not start an object, expecting field name (context: Object)` for a ClusterHealthRequest.

**Steps to reproduce**:

<pre>
ClusterHealthResponse nir = tc.admin().cluster().health(new ClusterHealthRequest()).actionGet();
System.out.println(nir.getNumberOfNodes());
System.out.println("ups!: "+XContentHelper.toString(nir));
</pre>

prints

<pre>
3
ups!: {
  "error" : "Can not start an object, expecting field name (context: Object)"
}
</pre>

Tested with ES 5.5.1 but maybe newer versions are affected as well.

**Comment by jimczi** [comment]
Hi @floragunncom ,
This issue is fixed in 6.1 by https://github.com/elastic/elasticsearch/pull/25866
For 5.5 you'll need to copy the new method in `Strings.toStrings` to use it in your code.
