### ISSUE TITLE
document JVM option MaxFDLimit for macOS max file descriptors

### ISSUE THREAD

**Issue by stuvie** [elastic/elasticsearch#26899]
**Should Document macOS-specific JVM Setting for max file descriptors:**

**Elasticsearch version**: 6.0.0-rc1

**Plugins installed**: [n/a]

**JVM version**: java version "1.8.0_45"

**OS version**: macOS Sierra version 10.12.6

**Description of the problem including expected versus actual behavior**:

As a newcomer to elastic search, I was very frustrated when my server was running out of file descriptors and the suggested fixes I found on stackoverflow were not working. In talking to Jason Tedor at the Elastic ON Tour event in Toronto last week, he told me I had to pass -XX:-MaxFDLimit on MacOS. This should be in the public documention. I’ll submit a pull request.

**Steps to reproduce**:

 1. start up elasticsearch with the default settings
 2. try to import a year's worth of nginx logs via filebeat and logstash. The daily shards will need about 18,000 file descriptors
 3. watch elasticsearch run out of memory
 4. increase kern.maxfiles via /etc/sysctl.conf but see that elasticsearch cannot use the extra file descriptors unless you also pass the JVM option -XX:-MaxFDLimit

**Comment by jasontedor** [comment]
Closed by #26900
