### ISSUE TITLE
org.elasticsearch:elasticsearch is missing in maven dependency page

### ISSUE THREAD

**Issue by saeedansari** [elastic/elasticsearch#26904]
**High Level Rest Client 5.6** documentation is missing a maven dependency in this page
[Maven Repository](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-getting-started-maven.html).
```
<dependency>
    <groupId>org.elasticsearch</groupId>
    <artifactId>elasticsearch</artifactId>
    <version>5.6.2</version>
</dependency>
```

The dependency is mentioned in [dependency page](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-getting-started-dependencies.html) though.

It would be much better to have maven dependencies updated so beginners won't stuck with initialization.

**Comment by dadoonet** [comment]
I don’t understand. If you are using Maven then this dependency is coming as a transitive one.
No need to specify it IMO.

**Comment by javanna** [comment]
@saeedansari can you clarify please? Like David said, the dependency is transitive, you shouldn't need to declare the dependency on elasticsearch explicitly.

**Comment by saeedansari** [comment]
Sorry guys, I should have mentioned Gradle, but mistakenly I went with Maven. I use gradle and when I was only having following dependency:
```
dependencies {
    compile 'org.elasticsearch.client:elasticsearch-rest-client:5.6.2'
}
```
For creating RestHighLevelClient getting following error:
```
Caused by: java.lang.NoClassDefFoundError: org/elasticsearch/common/xcontent/NamedXContentRegistry
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:186) ~[elasticsearch-rest-high-level-client-5.6.2.jar:2.4.6]
	at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:177) ~[elasticsearch-rest-high-level-client-5.6.2.jar:2.4.6]
```

And NamedXContentRegistry is part of elasticsearch core dependency.

Sorry for ambiguity. Should I edit the ticket?

**Comment by javanna** [comment]
@saeedansari with that dependency only you shouldn't even be able to find `RestHighLevelClient` in your classpath. You are depending on the low-level REST client rather than the high-level one. Please have a look at https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-getting-started-maven.html .
