### ISSUE TITLE
How to expose the new Lucene CoveringQuery in the query dsl?

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#26915]
Lucene 7.1 comes with a new query, called the [CoveringQuery](https://issues.apache.org/jira/browse/LUCENE-7621). This is neat query that is like a bool query with should clauses but instead of global minimum should match for all documents it allows a minimum should match per document. I wonder how this new query can best be exposed in the ES query dsl?

It can be exposed in the `bool` query itself (via a `minimum_should_match` field or something like that), but that can be confusing as `CoveringQuery` Lucene query doesn't understand must, filter or must_not clauses and then we run into difficult to explain search results. At this moment I lean towards exposing this a separate query in the query dsl. I'm just not sure what the best name should be for this query, but I think the structure should look something like this:

```
{
   "covering" : {
     "minimum_should_match_field": "my_field",
     "queries": [
        {
          # query1
        },
        {
          # query2
        },
       # etc
     ]
   }
}
```

The field specified in the `minimum_should_match_field` must be a number field with doc values not turned off. There is no need to worry about negative values, because the `CoveringQuery` treats a minimum should match of 0 and lower as 1.

I think that the `match` query should also get a new `type` named `covering` (or another name) and a `minimum_should_match_field` option that then under the hood uses the `CoveringQuery` instead of `BooleanQuery` or `PhraseQuery`.

**Comment by jimczi** [comment]
> It can be exposed in the bool query itself (via a minimum_should_match field or something like that), but that can be confusing as CoveringQuery Lucene query doesn't understand must, filter or must_not clauses and then we run into difficult to explain search results.

Is it possible to extract the should clauses from the original bool query to build the `CoveringQuery` and then add this `CoveringQuery` as a should clause behind the scene ?
I prefer this option because it means that we can extend `minimum_should_match` to support this covering query automatically (without adding a new query).

> The field specified in the minimum_should_match_field must be a number field with doc values not turned off.

It could also be a script since it's a value source ?

**Comment by martijnvg** [comment]
> Is it possible to extract the should clauses from the original bool query to build the CoveringQuery and then add this CoveringQuery as a should clause behind the scene ?
I prefer this option because it means that we can extend minimum_should_match to support this covering query automatically (without adding a new query).

I think that might just work. In the case other clauses are specified too then we need to set `BooleanQuery.Builder#setMinimumNumberShouldMatch(...)` to 1 in order to let it behave as expected? (otherwise the should clauses become completely optional)

> It could also be a script since it's a value source ?

Yes, I think it can be a script too.

**Comment by jimczi** [comment]
> I think that might just work. In the case other clauses are specified too then we need to set BooleanQuery.Builder#setMinimumNumberShouldMatch(...) to 1 in order to let it behave as expected? (otherwise the should clauses become completely optional)

True or we can add the converted `covering` query as a `must` clause.

**Comment by clintongormley** [comment]
Had a brainstorm with @martijnvg, @jpountz, and @colings86.

I'm not crazy about adding this to the `bool` query as:

* this is a specialist use case
* I can't think of example where you would want your queries to cover multiple fields
* the `bool` query is a staple, so adding extra options makes it harder for a new user to get to grips with it

The typical use case is: I am querying a list of values in a single field, and a document should only match if all (or most) of the values that the document contains are mentioned.  

More concrete use cases: 

* The document field contains the list of required permissions, the query contains all the users permissions, the document should only match if all of the required permissions are a subset of the user's permissions.
* The document field contains a list of keywords representing job experience (eg `java`, `ml`, `c++`).  The document should match if 75% of the document's keywords are queried, or if there are too few query terms, then all query terms must be present.

This leads me towards exposing the CoveringQuery in the `terms` query, except that the performance characteristics for this query will be quite different to the current `terms` query.

Also, if you have a `terms` query which support min-should-match-from-a-field/script, then why not also support standard min-should-match?  (Today, you'd have to use a `bool/should` clause for this).

This lead us to think of this as a query to look for super- or sub-sets: how well do the query and document terms intersect?

Suggestion is to expose this as the `terms_set` query:

```
{
  "terms_set": {
    "my_field": {
      "terms": ["foo", "bar", "baz"],
      "minimum_should_match": "50%",
  ||  "minimum_should_match_field": "my_field_value_count",
  ||  "minimum_should_match_script": {
        "source": "....."
      }
    }
  }
}
```

The `script` could inject a parameter with the number of query terms.

> I can't think of example where you would want your queries to cover multiple fields

If users do have valid examples for how they'd like to use this, then we can revisit how to expose a multi-field version of this query, but I think the `terms_set` query will cover >95% of use cases already.

**Comment by derickson** [comment]
@clintongormley  @skearns64  I like the DSL proposal.  It's a somewhat separate topic, but think it will be important to make sure there is a way to use X-pack security templating of an array from user security object metadata to put data into the "terms" field.  I think this currently not possible for other query types.  Might make sense to ask for this to be a test case for the X-Pack team.

We asked for some customer feedback from my geo and they were thumbs up.

I'd love to see 
> min_should_match_percent || min_should_match_count

if you have 3 terms and 2 need to match using a percentage gets weird.

I don't fully grok the script option, I'd need an example to know when and why it would be used

**Comment by derickson** [comment]
having the default value for min_should_match_percent be 100% would make sense to me

**Comment by jpountz** [comment]
I think min_should_match as a percentage might bring some confusion as to whether the number that matters is the number of query terms of the number of terms in the document?

**Comment by clintongormley** [comment]
> I'd love to see
>     min_should_match_percent || min_should_match_count

The standard minimum should match syntax already supports this (at least based on the number of terms in the query): https://www.elastic.co/guide/en/elasticsearch/reference/5.6/query-dsl-minimum-should-match.html

A script could be used to do something similar on the document side.

> I think min_should_match as a percentage might bring some confusion as to whether the number that matters is the number of query terms of the number of terms in the document?

true, although the standard min should match syntax already supports percentages, so it'd be weird to prevent that in this query.  Better to just document it I think.

**Comment by Mpdreamz** [comment]
Huge +1 to your initial suggested exposure @martijnvg 

```json
{
   "covering" : {
     "minimum_should_match_field": "my_field",
     "queries": [
        {
          # query1
        },
        {
          # query2
        },
       # etc
     ]
   }
}
```

Also liking the `covering` addition to the `match` family.

It's super explicit and does not complicate `bool` further. 

Can the `terms_set` suggestion be in addition to the the `covering` query and maybe renamed to `covering_terms` to signal its relation like `match_` family? This way we don't assume usecases and keep our tradition of exposing lucene queries as they are.

**Comment by jpountz** [comment]
Discussed in FixitFriday: if we support the `minimum_should_match` option, then there would be two ways to do the same thing (with `bool` or this new query), plus there is potential confusion around what the percentage applies to, so we'll start by just supporting `minimum_should_match_field` and `minimum_should_match_script` and then adapt the API based on the feedback from users.

**Comment by Mpdreamz** [comment]
Are we going with terms_set or opening it up completely to a list of any query as the covering query?

**Comment by jpountz** [comment]
When discussing it, we couldn't think of use-cases for any other queries than term queries. So we decided to go with term queries only for now, we can potentially change our minds depending on the feedback we'll get from users.
