### ISSUE TITLE
Unable to delete backup repository

### ISSUE THREAD

**Issue by patmanh** [elastic/elasticsearch#26917]
**Elasticsearch version** (`bin/elasticsearch --version`):

`Version: 2.1.1, Build: 40e2c53/2015-12-15T13:05:55Z, JVM: 1.7.0_79`

**Plugins installed**: []

```
    - kopf
    - license
    - cloud-aws
    - marvel-agent
```

**JVM version** (`java -version`):

```
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):

`Linux ip-10-0-0-230 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

We're trying to delete a (very) old s3 backup repository that was set up years ago. There seems to be a 'stuck' restore that is using a snapshot that was in the repo we're trying to delete (the snapshot has since been deleted) . We can see the 'stuck' restore when we hit `http://elasticsearch.hive.co:9200/_cluster/state/customs`

We think the stuck repo is preventing us from deleting the repo. We can create new repos and new snapshots OK. Everything else seems to be functioning just fine.

We want to delete the bucket that is backing the repo from S3 for cost saving purposes - **is it safe for us to manually delete the repo from S3**? Below are various delete/cancel calls that seem to be failing.

**Steps to reproduce**:

```python
es.snapshot.delete(repository='hive-es-backups-repo', snapshot='es-snapshot-2017-07-14-1530')

ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='ec2-54-86-65-23.compute-1.amazonaws.com', port=9200): Read timed out. (read timeout=10))
```

```python
resp = requests.delete('http://elasticsearch.hive.co:9200/_snapshot/hive-es-backups-repo/es-snapshot-2017-07-14-1530/')

print resp.content

'{"error":{"root_cause":[{"type":"snapshot_missing_exception","reason":"[hive-es-backups-repo:es-snapshot-2017-07-14-1530] is missing"}],"type":"snapshot_missing_exception","reason":"[hive-es-backups-repo:es-snapshot-2017-07-14-1530] is missing","caused_by":{"type":"file_not_found_exception","reason":"Blob object [snap-es-snapshot-2017-07-14-1530.dat] not found: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: F80FD0AA460D476B)"}},"status":404}'
```

```python
resp = requests.delete('http://elasticsearch.hive.co:9200/_snapshot/hive-es-backups-repo/')

print resp.content

'{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[MASTER-ip-10-0-0-71][10.0.0.71:9300][cluster:admin/repository/delete]"}],"type":"illegal_state_exception","reason":"trying to modify or unregister repository that is currently used "},"status":500}'
```

We've tried to post to the Elasticsearch support forum as well (https://discuss.elastic.co/t/possible-to-manually-delete-s3-backup-repository/101402), with no luck. Any help is appreciated! Thanks.

**Comment by tlrx** [comment]
Hi @patmanh, we reserve Github for bug reports and feature requests only. So I'm closing this issue in favor of the topic you created on Discuss. Thank you!
