### ISSUE TITLE
Inconsistent API spec for `*_script`

### ISSUE THREAD

**Issue by olcbean** [elastic/elasticsearch#26923]
Looking into #25737 I notice that the `*_script` rest-api-specs [1] definition of path parts as required  is inconsistent with others rest-api-specs.

For example [index](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/index.json) defines two different `paths` : `"paths": ["/{index}/{type}", "/{index}/{type}/{id}"]` and sets `index` and `type` to required, leaving `id` as an optional path part (as it is not in both `paths`).
However `get_script` although defining only a single path : `"paths": [ "/_scripts/{id}" ]`, sets `id` *and* `lang` as required.

My interpretation of the `required : true` is that the path part *must* be in all paths. 

As till now the `required` has not been enforced by the rest test runner, this has gone undetected. However for #25737 I am considering enforcing `required` both for path parts and parameters. This means I will run into more inconsistent definitions of the `required` for path parts.

My question here is: is my understanding of `required` in the rest-api-specs correct? If so, I would proceed and correct all inconsistent definitions of `required` I run into during the implementation of #25737.

[1]*_script rest-api-specs:
[delete_script](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/delete_script.json)
[get_script](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/get_script.json)
[put_script](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/put_script.json)

**Comment by javanna** [comment]
hi @olcbean I think your thoughts are spot on, if we validate use of `required` we also need to fix those tests.  @jdconrad can you shed some light on the scripting APIs and these inconsistencies please?

**Comment by jdconrad** [comment]
Sure.  Sounds like a bug that was introduced due to maintaining backwards compatibility at some point.  Now, that there's only a single path for each delete/get/put script commands it probably makes sense to add required for id.

**Comment by Mpdreamz** [comment]
`context` also needs to be documented instead of `lang` here: https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/put_script.json#L14-L18
