### ISSUE TITLE
`TermsAggregationBuilder` is not right for high level rest client.

### ISSUE THREAD

**Issue by futurechallenger** [elastic/elasticsearch#26939]
in High Level Rest Client doc [here](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/5.6/java-rest-high-search.html#java-rest-high-document-search-request-building-aggs), in section **Requesting Aggregations**. There's a type error! `TermsAggregationBuilder` should be `TermsBuilder`.
```java
SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
TermsBuilder aggregation = AggregationBuilders.terms("by_company")
        .field("company.keyword");
aggregation.subAggregation(AggregationBuilders.avg("average_age")
        .field("age"));
searchSourceBuilder.aggregation(aggregation);
```

**Comment by tlrx** [comment]
`AggregationBuilders.terms()` returns an instance of `TermsAggregationBuilder` as you can [see here](https://github.com/elastic/elasticsearch/blob/5.6/core/src/main/java/org/elasticsearch/search/aggregations/AggregationBuilders.java#L283). I don't think the documentation is wrong, I don't see any interface or class named `TermsBuilder`.

**Comment by dadoonet** [comment]
Agreed with @tlrx. I'm closing. Feel free to add comment if we missed anything here.
