### ISSUE TITLE
suggest_mode = “always” of term suggester doesn't work.

### ISSUE THREAD

**Issue by danny-su** [elastic/elasticsearch#26941]
**Elasticsearch version** (`bin/elasticsearch --version`): 
Version: 5.6.2, Build: 57e20f3/2017-09-23T13:16:45.703Z

**Plugins installed**: []

**JVM version** (`java -version`):
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Darwin danny-mac.local 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Use the official example, index some tweets.
```
curl -XPUT 'http://localhost:9200/twitter/doc/1?pretty' -H 'Content-Type: application/json' -d '
{
    "user": "kimchy",
    "post_date": "2009-11-15T13:12:00",
    "message": "Trying out Elasticsearch, so far so good?"
}'

curl -XPUT 'http://localhost:9200/twitter/doc/2?pretty' -H 'Content-Type: application/json' -d '
{
    "user": "kimchy",
    "post_date": "2009-11-15T14:12:12",
    "message": "Another tweet, will it be indexed?"
}'

curl -XPUT 'http://localhost:9200/twitter/doc/3?pretty' -H 'Content-Type: application/json' -d '
{
    "user": "elastic",
    "post_date": "2010-01-15T01:46:38",
    "message": "Building the site, should be kewl"
}'
```
 2. Post a suggest request with suggest_mode = "always". 
```
POST twitter/_search
{
  "suggest" : {
    "my-suggestion" : {
      "text" : "trying out Elasticsearch",
      "term" : {
        "field" : "message",
        "suggest_mode": "always"
      }
    }
  }
}
```
 3. The following is the response,  but with the suggest_mode="always", the options of my-suggestion must contain the matched words "trying", "out" and "Elasticsearch" respectively.
The  phase suggester has the same issue.
```
{
   "took": 8,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "skipped": 0,
      "failed": 0
   },
   "hits": {
      "total": 0,
      "max_score": 0,
      "hits": []
   },
   "suggest": {
      "my-suggestion": [
         {
            "text": "trying",
            "offset": 0,
            "length": 6,
            "options": []
         },
         {
            "text": "out",
            "offset": 7,
            "length": 3,
            "options": []
         },
         {
            "text": "elasticsearch",
            "offset": 11,
            "length": 13,
            "options": []
         }
      ]
   }
}
```

**Provide logs (if relevant)**:

**Comment by javanna** [comment]
hi @danny-su I suspect that this is not a bug, rather a misunderstanding of how the suggestion API works. May I ask you to ask this question in our [forum](https://discuss.elastic.co/) please instead, maybe asking why it doesn't work as you expect it to work rather than assuming that it doesn't work? We'd like to use github issues only for feature requests or verified bugs. Thanks!

**Comment by kabike** [comment]
I also think this is a bug.
