### ISSUE TITLE
/_snapshot endpoint API documentation

### ISSUE THREAD

**Issue by SimoneCafiero** [elastic/elasticsearch#26945]
Hi guys,
is there a complete documentation of the following API endpoint:

- /_snapshot

I would like to know if it's possible to edit backup metadata names (snap-CUSTOM_NAME or meta-CUSTOM_NAME instead of having a random String where CUSTOM_NAME is) and eventually how to do that through any API parameter. So any documentation of that endpoint would be very helpful.

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
