### ISSUE TITLE
Support Matrix should address Ubuntu "LTS" support

### ISSUE THREAD

**Issue by adoerrES** [elastic/elasticsearch#26955]
Upon confirming that the supported Ubuntu versions in the support matrix also apply to the "LTS" (Long Term Support) versions of Ubuntu, the matrix should explicitly list the LTS support.

Currently just the Ubuntu version number is listed, leaving users to wonder if the LTS versions are supported.

https://www.elastic.co/support/matrix

https://wiki.ubuntu.com/LTS

**Comment by jasontedor** [comment]
I'm confused, the support matrix explicitly lists 14.04 and 16.04, these are synonymous with the most recent LTS releases of Ubuntu. I don't think anything needs to change here?

**Comment by adoerrES** [comment]
Multiple users weren't sure that the version numbers listed were synonymous with the LTS releases for those versions.  

There seems to be an implicit understanding that the Ubuntu releases on the matrix apply to LTS releases, so the request was just to mention LTS explicitly on the matrix for those who weren't sure (unless its problematic to do so).

**Comment by jasontedor** [comment]
> Multiple users weren't sure that the version numbers listed were synonymous with the LTS releases for those versions.

For clarity, there isn't an LTS release for those versions, those versions are LTS releases. This is what I mean by "synonymous".

**Comment by jasontedor** [comment]
I'm closing this since I do not think there a change is needed here (again, 14.04 and 16.04 are LTS releases), and this is not the repository to address these concerns anyway.
