### ISSUE TITLE
Range query's from/to values get recorded as null in slowlog

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#26951]
5.5

I came across this when using the high level rest client where we rewrote a range query's gte/lte to its internal representation of (from/to). 

```
GET /posts/_search
{
  "query" : {
    "bool" : {
      "filter" : [
        {
          "range" : {
            "postDate" : {
              "from" : "2010-01-01",
              "to" : "now/d"
            }
          }
        }
      ]
    }
  }
}
```

It looks like slowlog doesn't know how to handle range query's from/to and recorded its values as nulls.

```
[2017-10-10T10:23:44,752][DEBUG][index.search.slowlog.fetch] [68R5f1x] [posts][3] took[27.2micros], took_millis[0], types[], stats[], search_type[QUERY_THEN_FETCH], total_shards[5], source[{"query":{"bool":{"filter":[{"range":{"postDate":{"from":null,"to":null,"include_lower":true,"include_upper":true,"boost":1.0}}}],"disable_coord":false,"adjust_pure_negative":true,"boost":1.0}}}],
```

**Comment by jimczi** [comment]
The slowlog records the query **after** rewriting, in 5.x queries are rewritten on the coordinating node and on the shards which is why they can differ from the original query when printed in the slowlog. In your example I suspect that the shard rewrote the range query to an open bound query because we detected that the provided range would match all documents in that shard. Open bounds range query are represented with null values so the output is expected.

**Comment by ppf2** [comment]
Thanks @jimczi Thx for the explanation on how we treat the query internally!  I am wondering if there's anything we can do from a user experience point of view.  Slowlogs are often used to identify what queries are being sent from the application.  So showing nulls instead of what the user provided may throw users off when analyzing slowlogs.  It will be helpful to document this behavior in the slowlog documentation.  Or are there too many other scenarios where we would show null after rewriting?

**Comment by jasontedor** [comment]
I think knowing where a query in the slow logs is coming from is best solved orthogonally to how the query is presented in the slow logs. Instead, we have been thinking about adding some metadata or allowing users to add metadata that would help them.

**Comment by jimczi** [comment]
I agree with Jason, it would be simpler to associate metadata with a request that you can search in the slowlog directly.
Relates to https://github.com/elastic/elasticsearch/issues/8547
