### ISSUE TITLE
[Docs] breaking change: Script API no longer accepts script as string

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#26963]
The deprecated 2.x way of indexing scripts with the `lang` as part of the url allowed scripts to still be specified as strings too in 5.x but obviously no longer in 6.x as the deprecated urls are gone as well.

https://www.elastic.co/guide/en/elasticsearch/reference/2.4/modules-scripting.html#_indexed_scripts

**Comment by jdconrad** [comment]
This whole section definitely needs some work.

**Comment by rjernst** [comment]
The current docs are up to date regarding stored scripts. Closing.
