### ISSUE TITLE
[Docs] breaking change: ids query no longer accepts aliases for type

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#26974]
https://www.elastic.co/guide/en/elasticsearch/reference/6.x/breaking_60_search_changes.html 

Should list the fact that ids query `type` parameter no longer `types` and `_type`.

https://github.com/elastic/elasticsearch/blob/5.5/core/src/main/java/org/elasticsearch/index/query/IdsQueryBuilder.java#L54
https://github.com/elastic/elasticsearch/blob/6.0/core/src/main/java/org/elasticsearch/index/query/IdsQueryBuilder.java#L54

**Comment by javanna** [comment]
good catch @Mpdreamz . Relates to #26508.

**Comment by cbuescher** [comment]
Closed by #29017
