### ISSUE TITLE
More than one level of nesting with include_in_parent + include_in_root can lead to duplicate fields

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#26990]
Say your mappings look like this:

```
{
  "properties": {
    "foo": {
      "type": "nested",
      "include_in_root": true,
      "include_in_parent": true
    }
  }
}
```

Then we make sure to only copy to the root if it is different from the parent document. However if you start having more than one level of nesting:

```
{
  "properties": {
    "foo": {
      "type": "nested",
      "include_in_root": true,
      "include_in_parent": true,
      "properties": {
        "bar": {
          "type": "nested",
          "include_in_root": true,
          "include_in_parent": true
        }
      }
    }
  }
}
```

Then `foo.bar` will copy fields to both the root and parent since parent != root. And then foo will copy fields to its parent, which is the root as well. So fields of `foo.bar` will end up twice in the root document.

**Comment by PnPie** [comment]
Hello,
The duplicated fields you mean is which part exactly ? I've had a look at the document fields of indexed data and also the objectMappers in the `DocumentMapper`, it seems I didn't find the duplications ?

**Comment by original-brownbear** [comment]
Gave this a go in https://github.com/elastic/elasticsearch/pull/27072 :)
