### ISSUE TITLE
Make query parsers automatically add missing `nested` queries.

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#26991]
`include_in_parent` is currently not used as much as a feature than as a workaround in order to not always have to provide a nested query when searching for nested data.

We should look into making query parsers automatically add `nested` queries when the queried fields are under a `nested` object which doesn't have `innclude_in_parent` or `include_in_root` set. This will help deprecate `include_in_root` and `include_in_parent`: #12461.

**Comment by martijnvg** [comment]
Related to #11322

**Comment by mayya-sharipova** [comment]
cc @elastic/es-search-aggs

**Comment by martijnvg** [comment]
> We should look into making query parsers automatically add nested queries when the queried fields are under a nested object which doesn't have innclude_in_parent or include_in_root set.

We should do the same with sorting. So that `nested_path` doesn't have to be specified.

**Comment by javanna** [comment]
There are no concrete plans to work on this issue.
