### ISSUE TITLE
Force a new master election for rolling restart

### ISSUE THREAD

**Issue by AlexWerz** [elastic/elasticsearch#26992]
Force a master election to eliminate downtime during rolling restart.

Whenever I need to restart a cluster I follow the rolling restart guide provided here https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html

Bascally:
1. wait for green status
2. Disable shard allocation
3. restart node
4. enable shard allocation
5. wait for green status
6. repeat with next node

I sort my nodes according their role and restart master nodes last. This works fine until I restart the master node. Then the cluster is not reachable anymore for like 30s. All requests to the cluster will fail. This could be prevented if I would have the possibility to change the current master before restarting it.

Thanks,
Alex

**Comment by bleskes** [comment]
During master elections nodes will serve reads requests and indexing requests will wait (but not return) for a new master to be elected. Master election takes between 3 to 5 seconds, but it sounds like you're experiencing something else. I would suggest starting with investigating why that is (if you need help please feel free to post something on our forums at discuss.elastic.co). I'm going to close this issue for now (it has merit but there are much bigger fish to fry at the moment).

**Comment by DaveCTurner** [comment]
@luyuncheng this issue was closed nearly 2 years ago, so this isn't a good place to ask a question like yours. I see you've asked the same question on another closed issue too. I recommend not doing this. If you would like to discuss your question, please open a thread on the [discussion forum](https://discuss.elastic.co/c/elasticsearch) instead.
