### ISSUE TITLE
Discrepancy on node id on _cat apis?

### ISSUE THREAD

**Issue by lmenezes** [elastic/elasticsearch#27008]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.0.0-rc1 and 5.6.2

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_92

**OS version** (`uname -a` if on a Unix-like system): Darwin nb-lmenezes 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**: Node id returned on _cat apis(for example, _cat/nodes) x other non cat apis(for example: _nodes/stats) do not match. I'm not sure if this is somehow intended, or if there is something obvious that I don't know/don't realise, but I would expect that **id** would always be the same.

**Steps to reproduce**:

 1. Start up an ES node(6.0.0-rc1, or 5.6.2, or likely any other version)
 2. ```curl -XGET http://localhost:9202/_nodes/stats/os``` returns 
```json
{
  "_nodes": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "cluster_name": "elasticsearch",
  "nodes": {
    "3ClJWQNoSbKZ3HMcgbJacg": {}
  }
}
```
 3. ```curl -XGET http://localhost:9202/_cat/nodes\?format\=json``` returns
```json
[
  {
    "ip": "127.0.0.1",
    "heap.percent": "11",
    "ram.percent": "100",
    "cpu": "17",
    "load_1m": "2.24",
    "load_5m": null,
    "load_15m": null,
    "node.role": "mdi",
    "master": "*",
    "name": "3ClJWQN" 
  }
]
```

**Comment by jasontedor** [comment]
This is intended by design. The node ID you are looking at in nodes stats API is a persistent node ID. The output you are looking at in cat nodes is the node name which is derived from the node ID as a shortened version of the persistent node ID unless you set the node name explicitly. You can get the full node ID in the cat nodes output by passing a URL parameter (check which with `?help`).

**Comment by lmenezes** [comment]
@jasontedor Sorry, my example was bogus.

Now, output of ```http://localhost:9202/_cat/nodes?format=json&h=id,name```

```
[
  {
    "id": "3ClJ",
    "name": "3ClJWQN"
  }
]
```

**Comment by jasontedor** [comment]
This is still intentional. If you want the full ID on the cat nodes API you have to pass `?full_id=true`.

**Comment by jasontedor** [comment]
So a full example to get the full node ID would be: `GET /_cat/nodes?h=id&full_id=true&v`

**Comment by lmenezes** [comment]
@jasontedor Thanks! Is this documented anywhere and I just missed it?

**Comment by jasontedor** [comment]
@lmenezes I do not think you missed anything, I think that it is not documented sadly. I will fix this.

**Comment by lmenezes** [comment]
👍 and thanks again!

**Comment by jasontedor** [comment]
You're welcome. I opened #27009.
