### ISSUE TITLE
run elasticsearch-7.0.0-alpha1-SNAPSHOT  in intellij idea on windows,get error

### ISSUE THREAD

**Issue by novenzhen** [elastic/elasticsearch#27005]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

I git clone the latest code  from github,then build the source code using gradle,importing the project into intellij idea ,then run the main class elasticsearch,but I get the following error:
ERROR: the system property [es.path.conf] must be set

Does anybody know how to set the parmeters and ienviorment params  to make the main class run?
Very appreciate it.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
