### ISSUE TITLE
Bug in Windows Installer elasticsearch 6 RC-1

### ISSUE THREAD

**Issue by paulkeogh** [elastic/elasticsearch#27011]
**Elasticsearch version** (`bin/elasticsearch --version`): 6 RC-1

**Plugins installed**: None

**JVM version** (`java -version`): 1.8.0_144

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:
The link "Open Elasticsearch in the browser" in the final step of the Windows installer navigates to the network host entered earlier - if you have entered a network host of 0.0.0.0 (to instruct elasticsearch to bind to all network interfaces, this does not work. Manually navigating to 127.0.0.1:9200 does work.

**Steps to reproduce**:

 1. Download and run Windows installer
 2.Enter 0.0.0.0 for the network host when prompted
 3.Click on the "Open Elasticsearch..." link in the final step of the installer

**Comment by dadoonet** [comment]
But when you bind to 0.0.0.0 you need to make sure you pass bootstrap checks.
I believe you don’t here and elasticsearch does not start. Am I right ?

**Comment by paulkeogh** [comment]
It appears to start fine;  From 127.0.0.1:9200 I see;

{
  "name" : "development",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "bNMvBsFuRxum0r3L7KzvMg",
  "version" : {
    "number" : "6.0.0-rc1",
    "build_hash" : "b9c0df2",
    "build_date" : "2017-09-25T19:11:45.815Z",
    "build_snapshot" : false,
    "lucene_version" : "7.0.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}

However, the installer did not create the logs, data or config folders under program files\elastic\elasticsearch so something doesn't look too good....

**Comment by jasontedor** [comment]
There is a repository for the Windows installers: [elastic/windows-installers](https://github.com/elastic/windows-installers). Would you please reopen there?
