### ISSUE TITLE
Rewrite Elasticsearch in Rust

### ISSUE THREAD

**Issue by Serkan-devel** [elastic/elasticsearch#27013]
**Describe the feature**:

A rewritten elastic stack in rust has the capability to run as fast as C++ and written as safe as Java.

**Elasticsearch version** (`bin/elasticsearch --version`): elasticsearch:5.5-alpine (docker)

**Plugins installed**: [redis, async, redis-async]

**JVM version** (rustc 1.19.0 (0ade33941 2017-07-17)):

**OS version** (Linux Kernel 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux):

**Comment by dadoonet** [comment]
😄 

We have no plan like this.
I'm closing if you don't mind

**Comment by swallez** [comment]
Checkout [Tantivy](https://github.com/tantivy-search/tantivy) as a (limited) Lucene replacement if you want something in Rust.

**Comment by lucperkins** [comment]
Possibly the worst "issue" I've ever seen in open source

**Comment by kumargu** [comment]
I know that this issue lacks description; still going to reuse this issue and ask if the plan has changed; given the growing adoption of the language.

**Comment by sandstrom** [comment]
Forward to 2026, and rewriting this in rust with agents isn't actually that crazy of an idea anymore 🦀 

### Examples

- https://github.com/lakehq/sail (rewrite of Spark)
- https://devblogs.microsoft.com/typescript/announcing-typescript-7-0-beta/ (typescript rewritten in go)
- https://github.com/pnpm/pacquet (rewrite of PNPM)

Not saying it's easy or necessarily a good idea, but might be worth discussing at least.
