### ISSUE TITLE
Create mapping suspend 

### ISSUE THREAD

**Issue by winlans** [elastic/elasticsearch#27029]
When I use curl to create mapping for index, curl will hang there, there will not be any corresponding, and will not stop operation.

**Comment by jasontedor** [comment]
There’s not enough information here to debug this. Let’s take this to the [forum](https://discuss.elastic.co). When you open a topic there, can you provide version and `jstack` output from the Elasticsearch process that you sent the request to when the request is hung. You can link to the topic from here. We can reopen this issue if there is a bug here.

**Comment by winlans** [comment]
https://discuss.elastic.co/t/use-curl-to-create-mapping-suspend/104213
