### ISSUE TITLE
MGET API docs wrong for type

### ISSUE THREAD

**Issue by smithsimonj** [elastic/elasticsearch#27024]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 5.5.1

**Plugins installed**: [mapper-murmur3]

**JVM version** (`java -version`): java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): Darwin simon-smith.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64 

**Description of the problem including expected versus actual behavior**:
On the docs for the mget API: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docs-multi-get.html. Current docs are the same.

It states that a query should look like this:

```
GET _mget
{
    "docs" : [
        {
            "_index" : "test",
            "_type" : "type",
            "_id" : "1"
        },
        {
            "_index" : "test",
            "_type" : "type",
            "_id" : "2"
        }
    ]
}
```

Note that the doc_type is specified by `_type`. I found this didn't work but the following does:

```
GET _mget
{
    "docs" : [
        {
            "_index" : "test",
            "doc_type" : "type",
            "_id" : "1"
        },
        {
            "_index" : "test",
            "doc_type" : "type",
            "_id" : "2"
        }
    ]
}
```

Note how the `doc_type` is specified in this second query.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by dadoonet** [comment]
I just tested it and it works well:

```
DELETE test
PUT test/doc/1
{
  "foo": "bar"
}
PUT test/doc/2
{
  "foo": "bar"
}
GET _mget
{
    "docs" : [
        {
            "_index" : "test",
            "_type" : "doc",
            "_id" : "1"
        },
        {
            "_index" : "test",
            "_type" : "doc",
            "_id" : "2"
        }
    ]
}
```

Gives:

```json
{
  "docs": [
    {
      "_index": "test",
      "_type": "doc",
      "_id": "1",
      "_version": 1,
      "found": true,
      "_source": {
        "foo": "bar"
      }
    },
    {
      "_index": "test",
      "_type": "doc",
      "_id": "2",
      "_version": 1,
      "found": true,
      "_source": {
        "foo": "bar"
      }
    }
  ]
}
```

You are probably doing something wrong. 

If you can't find is wrong, please ask on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
