### ISSUE TITLE
Typo in exception error message

### ISSUE THREAD

**Issue by cfx1** [elastic/elasticsearch#27027]
Elasticsearch 5.6.3

OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK Server VM (build 25.144-b01, mixed mode)

Linux localhost.localdomain 2.6.32-696.13.2.el6.i686 SMP Thu Oct 5 20:42:25 UTC 2017 i686 i686 i386 GNU/Linux

IndicesAliasesRequest::ConstructingObjectParser has a typo in the following exception message:
`throw new IllegalArgumentException("Too many operations declared in on opeation entry");`

**Comment by jasontedor** [comment]
Thanks for the report. There’s an open pull request for this: #27025.
