### ISSUE TITLE
how to custom analyzer with transport of Java?

### ISSUE THREAD

**Issue by kervin521** [elastic/elasticsearch#27028]
e.g.

{
    "settings": {
        "analysis": {
            "filter": {
                "default_stopwords": {
                    "type": "stop",
                    "stopwords": ["a","an","and","are","as","at","be","but","by","for","if","in","into","is","it","no","not","of","on","or","such","that","the","their","then","there","these","they","this","to","was","will","with"]
                }
            },
            "char_filter": {
                "symbol_transform": {
                    "mappings": [
                        "&=> and ",
                        "||=> or "
                    ],
                    "type": "mapping"
                }
            },
            "analyzer": {
                "es_analyzer": {
                    "filter": [
                        "lowercase",
                        "default_stopwords"
                    ],
                    "char_filter": [
                        "html_strip",
                        "symbol_transform"
                    ],
                    "type": "custom",
                    "tokenizer": "standard"
                }
            }
        }
    }
}

how to custom analyzer with transport of Java?

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by kervin521** [comment]
I can't access discuss.elastic.co,and it is not custom analyzer test in elasticsearch.

**Comment by medcl** [comment]
@kervin521 the documentation is here: https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-admin-indices.html
if you can't visit discuss.elastic.co, you may visit https://elasticsearch.cn/
