### ISSUE TITLE
[Docs] Docker page should include examples of how to create a cluster with custom ports

### ISSUE THREAD

**Issue by nerophon** [elastic/elasticsearch#27021]
The docker page is here:
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html#docker

It currently describes how to setup Elasticsearch on a single node, but there isn't sufficient detail about how to get nodes to form a cluster. Port mapping, especially, is non-trivial in docker installs using manual orchestration.

Here is an example of launching a couple of docker nodes with custom ports such that they are able to discover one another:

```
docker run -d --name elasticsearch-node-test -p 11101:9200 -p 11106:9300 \
-e "cluster.name=test" \
-e "node.name=test-node-${HOSTNAME}" \
-e "network.publish_host=node1.company.com" \
-e "http.publish_port=11101" \
-e "transport.publish_port=11106" \
-e "discovery.zen.minimum_master_nodes=2" \
-e "discovery.zen.ping.unicast.hosts=node1.company.com:11106,node2.company.com:11106" \
docker.elastic.co/elasticsearch/elasticsearch:5.6.3
```

```
docker run -d --name elasticsearch-node-test -p 11101:9200 -p 11106:9300 \
-e "cluster.name=test" \
-e "node.name=test-node-${HOSTNAME}" \
-e "network.publish_host=node2.company.com.com" \
-e "http.publish_port=11101" \
-e "transport.publish_port=11106" \
-e "discovery.zen.minimum_master_nodes=2" \
-e "discovery.zen.ping.unicast.hosts=node1.company.com:11106,node2.company.com:11106" \
docker.elastic.co/elasticsearch/elasticsearch:5.6.3
```

**Comment by dliappis** [comment]
We discussed this on our team meeting and feel that this (i.e. not using the native solutions of orchestrators like [Kubernetes CNI](https://kubernetes.io/docs/concepts/cluster-administration/networking/) or [overlay network](https://docs.docker.com/network/overlay/) in Docker swarm) would add unnecessary detail in our reference documentation for not such a common use case. Additionally this is not a Docker only topic, such options would apply in other cases where NAT / port forwarding is in use.

We can revisit this if it seems to be important, but for now closing.
