### ISSUE TITLE
Force visualizations to align on a dashboard based on their values in an axis.

### ISSUE THREAD

**Issue by hartmant** [elastic/elasticsearch#27020]
![kibana alignment](https://user-images.githubusercontent.com/3840815/31610567-cd9ffb82-b278-11e7-861c-bcc48f5e69c9.jpg)

**Feature: option to align visualizations on a dashboard**:
Many dashboards feature visualizations with a Date Historgram on the X-axis. As these visualizations are aligned horizontally, the DateTime values themselves do not necessarily align properly. 
See the image attached where - ideally - the 12:40 point on the x-axis would align horizontally for all 3 visualizations. This would definitely improve readability.

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch. For Kibana issues, you want [elastic/kibana](https://github.com/elastic/kibana).
