### ISSUE TITLE
node_stats.fs.io_stats.total.write_kilobytes -> node_stats.fs.io_stats.total.write_bytes

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#27037]
**Describe the feature**:

When trying to make graphs of the stats `node_stats.fs.io_stats.total.write_kilobytes` and using Kibana formatting Bytes can get the nice automatic adjustment to MB / GB etc. but it is all off by a factor of 1024 because the original field is `write_kilobytes` and not `write_bytes`. It would seem more standard to have the data available as a bytes value so that no mutation is necessary for such displays in Kibana etc.

**Comment by javanna** [comment]
I think that both `read_kilobytes` and `write_kilobytes` should be rather printed out as `byteSizeField`s so that they adhere to the `human` flag. That would make them be bytes as default and optionally an additional human-readable field.

**Comment by kujon** [comment]
https://github.com/elastic/elasticsearch/pull/28367 proposed solution here.

**Comment by jasontedor** [comment]
It was a deliberate choice when we introduced these stats that they match exactly what cones out of /proc/diskstats. The proposal here is a deviation from this that I am not keen to make. Also, it’s a breaking change. Note that the monitoring collector can make this change if we so desire but I prefer to leave this as-is.

**Comment by robin13** [comment]
@jasontedor I understand the motivation to maintain consistency with the source, and the concern that any manipulation of the source values may introduce inaccuracies, but in this case I think the benefit of standardisation (and hence usefulness) of these values to other values in the stats output outweighs the concern of error by manipulation (converting kilobytes -> bytes is quite straight forward).
To avoid having a breaking change, the standardised bytes values could be inserted in parallel to kilobytes, with the kilobytes deprecated to be removed in a future version?

**Comment by martijnvg** [comment]
Closing, because it is better to not deviate from what `/proc/diskstats` returns. Dashboards and other tools than need byte level granularity can perform a simple multiplication.
