### ISSUE TITLE
Range datatype documentation should include term query example

### ISSUE THREAD

**Issue by davidbkemp** [elastic/elasticsearch#27030]
I love the fact that there is now a range datatype, but the documentation on how to use it could possibly be improved by explaining that range datatype fields can be matched against using term queries.

The example on
https://www.elastic.co/guide/en/elasticsearch/reference/current/range.html
could be extended with another query like the following:

```
GET /range_index/my_type/_search
{
  "query": {
    "term": {
      "expected_attendees": {
        "value": "12"
      }
    }
  }
}
```

The documentation for Term Query could also be updated to indicate that they can be used to match against range datatype fields.

**Comment by davidbkemp** [comment]
I thought I would have a go at this.  This commit has what I have tried so far: https://github.com/davidbkemp/elasticsearch/commit/b3619c4707ca73ec9d15da18842f48b6fe9dcdab

I think the existing range data type documentation is a little unconventional.  For most of the data types, the documentation seems to only include example mappings and documents.  They typically don't include queries.  I am beginning to feel that it should instead have links to example queries added to the documentation for the `term` and `range` queries.

**Comment by Yang-Rongquan** [comment]
There will be a big performance for range data type when query term and range filer.
And I can't get feedback from elasticsearch support for several days.
