### ISSUE TITLE
[Doc] (v2.4.x) KeepAlive for Generic thread pool set to 30s?

### ISSUE THREAD

**Issue by lukas-vlcek** [elastic/elasticsearch#27033]
The documentation for [cached](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/modules-threadpool.html#_literal_cached_literal) thread pool type reads:

> Unused threads in this thread pool will be terminated after a keep alive expires (defaults to five minutes).

While [there is the default value set to 5m](https://github.com/elastic/elasticsearch/blob/v2.4.6/core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java#L454) explicitly isn't this in fact [already set to 30s](https://github.com/elastic/elasticsearch/blob/v2.4.6/core/src/main/java/org/elasticsearch/threadpool/ThreadPool.java#L210)?

**Comment by danielmitterdorfer** [comment]
You are right. The node info API shows:

```
            "generic": {
               "type": "cached",
               "keep_alive": "30s",
               "queue_size": -1
            },
```

The confusing part is that the default for the `cached` thread pool *type* is 5 minutes but the only thread pool that can use that thread pool type is the `generic` pool which overrides it to 30 seconds. I have removed that confusing part now from the docs.
