### ISSUE TITLE
query search set preference custom value are ignored？

### ISSUE THREAD

**Issue by chendaoqiu** [elastic/elasticsearch#27048]
Elasticsearch version: 5.4.1
Elasticsearch setup: 9 node cluster
JVM version: openjdk version "1.8.0_131"
cluster elasticsearch.yml:
cluster.routing.allocation.awareness.attributes: zone
cluster.routing.allocation.awareness.force.zone.values: zone1,zone2
node.attr.zone: zone1 or zone2

cluster node：
3 master node
4 data node
2 client node

Elastic search preference set to custom value, document still returned from different shards？

**Comment by dadoonet** [comment]
Would be better asking this question on discuss.elastic.co where we can give a better support and provide more details like a full reproduction script to understand exactly what you are doing.

Thanks!
