### ISSUE TITLE
kibana and elasticsearch not support x-pack roles when use tribe node

### ISSUE THREAD

**Issue by YDHui** [elastic/elasticsearch#27047]
Hi,when i use a single es cluster with kibana,it support add roles or modify roles by kibana or  by http api,but when i use tribe node with kibana, it can't support add roles with a error show that 'tribe node can't add roles',but i set a prefer node in tribe node settings.Is there a method to solve this problem?On the other way,is there some plan to support tribe node modify roles in es? THX

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch only. For X-Pack issues, please use the [forum](https://discuss.elastic.co).
