### ISSUE TITLE
Track Lucene segment used memory in circuit breaker accounting

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#27044]
In order to make breakers more accurate, we should track the amount of memory used by Lucene segments in one of the breakers. This allows us to reduce the amount of "unknown" memory that is not tracked by the breakers and thus circuit-breakable.

**Comment by jpountz** [comment]
Does it also mean that we should also bump the threshold of the parent breaker?

**Comment by dakrone** [comment]
@jpountz I don't know yet. This will definitely need testing!
