### ISSUE TITLE
Bug: Elastic 5.6.3, Pattern Matcher not matching

### ISSUE THREAD

**Issue by Eduard3000** [elastic/elasticsearch#27058]
My guess this is a Bug: In Elastic 5.6.3:
java -version
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-1~deb9u1-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)
OS: 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"

Issue:
scripted field Pattern.Matcher noch working:
**Steps to reproduce**:
`
def p = /used_ram=([0-9]+)/;
if(doc['system.syslog.message'].value != null){
def ssm = doc['system.syslog.message'].value;
if (ssm =~ p) {
def m = p.matcher(ssm);
if (m.matches()) {
   return m.group(1);
} else {
   return 666
}
} else {
   return 777
}
} else {
   return 999
}
`
**Provide logs (if relevant)**:
"message": "2017-10-20 08:33:35.266 15660 INFO nova.compute.resource_tracker [req-79177ec1-f0b9-46ac-be47-c429aae839ea - - - - -] Final resource view: name=os-prod-comp2.matrix.test phys_ram=48275MB used_ram=512MB phys_disk=103GB used_disk=0GB total_vcpus=24 used_vcpus=0 pci_stats=[]",

script.painless.regex.enabled: true
system.syslog.message type keyword (<1024bytes)

Any idea why m.matches() not true?

Regex tester shows match.

Thanks for reading.

Regards,
Eduard

**Comment by ywelsch** [comment]
Let's have a look at the Java documentation for matches:

https://docs.oracle.com/javase/7/docs/api/java/util/regex/Matcher.html#matches()

> Attempts to match the **entire region** against the pattern.

Use find() instead of matches() and it should work.

If you have other questions like this please use the discuss forum:
https://discuss.elastic.co/c/elasticsearch
It is used by the community to ask and answers general questions about Elasticsearch.

**Comment by Eduard3000** [comment]
Thanks @ywelsch this worked.

**Comment by Eduard3000** [comment]
@ywelsch Yannick: maybe in https://www.elastic.co/blog/using-painless-kibana-scripted-fields
the example should use find instead of matches.
And I agree with #21238 more practical examples would be helpfull.

Thanks anyway!
Eduard
