### ISSUE TITLE
Docs: UTF-8 character can take up 4 bytes

### ISSUE THREAD

**Issue by ChrisGreenaway** [elastic/elasticsearch#27060]
**Elasticsearch version** (`bin/elasticsearch --version`): master

**Plugins installed**: N/A

**JVM version** (`java -version`): N/A

**OS version** (`uname -a` if on a Unix-like system): N/A

**Description of the problem including expected versus actual behavior**:

ignore-above.asciidoc says "If you use UTF-8 text with many non-ASCII characters, you may want to set the limit to 32766 / 3 = 10922 since UTF-8 characters may occupy at most 3 bytes." however a UTF-8 character can take up 4 bytes.

**Steps to reproduce**:

Look at ignore-above.asciidoc

**Provide logs (if relevant)**:

**Comment by nik9000** [comment]
@clintongormley git blame says you wrote this. @ChrisGreenaway is right, 4 bytes is possible, but not common. It [looks like](https://en.wikipedia.org/wiki/Plane_(Unicode)#Supplementary_Multilingual_Plane) 4 bytes is fairly rare unless you are dealing with fairly special text. Or emoji.

**Comment by DaveCTurner** [comment]
I agree - pretty common to see emoji these days. I opened #27083.

**Comment by DaveCTurner** [comment]
Thanks for the report, @ChrisGreenaway, much appreciated.

**Comment by ChrisGreenaway** [comment]
You are welcome. Thanks for fixing it.
