### ISSUE TITLE
[DOCS] Document data flow for reindexing

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#27063]
I have learned that all of the documents flow over the coordinating node for the `_reindex` API.  This is not necessarily intuitive, and that knowledge may influence the decision of which node to send the query to.  Could this please be documented in the [appropriate page](https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-reindex.html)

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open as this is still relevant.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
