### ISSUE TITLE
Maintain a NuGet package

### ISSUE THREAD

**Issue by HarelM** [elastic/elasticsearch#27067]
### Describe the feature ###
Maintain a [NuGet](https://www.nuget.org/) package.

**Justification**:
I'm using ES as part of my open source project.
The setup of this project requires the presence of ES.
In order for the setup instruction to be simpler I decided to store the binaries of ES as part of my repository (which is a bad practice) - I'm doing this since I write in C# and can't use java package managers such as Maven.
I'm planning on migrating all my 3rd party packages to NuGet but I prefer that the owners of the packages will maintain the NuGet package instead of me...
Any thoughts are welcome.

**Comment by jasontedor** [comment]
We are not going to do this as this is not a common way of distributing Java-based software.

**Comment by HarelM** [comment]
Thanks for the quick response!
I hope you won't mind if I maintain suck a package for my project needs.
Planning on calling it `IsraelHiking.ElasticSearch`.

**Comment by jasontedor** [comment]
One note: it’s “Elasticsearch”, not “ElasticSearch”. 😀

**Comment by russcam** [comment]
@HarelM We are working on extracting the framework that we have as part of the .NET client for running integration tests against Elasticsearch. This framework can download Elasticsearch zip archives and run them. See https://github.com/elastic/elasticsearch-net/issues/2767

**Comment by HarelM** [comment]
This looks promising, but is 5 month old. :-/
Also I have a Windows service that runs on my production environment and a small cmd for dev so I only need the binaries themselves as a NuGet package. Although a code that downloads the relevant zip might be better, not sure though...

**Comment by russcam** [comment]
@HarelM let's have the discussion on the other issue please.

**Comment by HarelM** [comment]
@russcam Sure, no problem, posted there my thoughts and current work.
