### ISSUE TITLE
Cross Cluster Search: expose remote list of indices

### ISSUE THREAD

**Issue by CpuID** [elastic/elasticsearch#27099]
It would be ideal if the `/_cat/indices` and/or the `/.../_aliases` + `/.../_mapping` endpoints supported Cross Cluster Search to expose available indices etc.

### `_aliases` and `_mapping`

These ones should be pretty straightforward.

Current scenario example:

```
$ curl -i "localhost:9200/somecluster%3Alogstash-2017.10.23,somecluster%3Alogstash-2017.10.24/_aliases?ignore_unavailable=true"
{}
```

Ideally you would want something like:

```
$ curl -i "localhost:9200/somecluster%3Alogstash-2017.10.23,somecluster%3Alogstash-2017.10.24/_aliases?ignore_unavailable=true"
{"somecluster:logstash-2017.10.24":{"aliases":{}}}
```

### `_cat/indices`

You may need to add some kind of parameter for `/_cat/indices` as it may be best to feature flag that one (eg. `/_cat/indices?v&ccs` or something), and I assume one issue may be the amount of index metadata being passed over CCS right now (eg. health, document counts, etc).

Maybe just display something signifying it's a remote index, with `N/A` next to most attributes?

**Comment by CpuID** [comment]
Technically the same as `/.../_aliases` would be useful for `/.../_mapping` as well.

**Comment by javanna** [comment]
hi @CpuID the reason why we exposed cross cluster search in the first place is to solve a specific problem: searching against multiple clusters, where the hard part is reducing search results (including aggregations) coming from different clusters and returning the top ones only overall.

What prevents you from sending your aliases, mappings etc. request directly to the cluster where they belong, rather than using a cross cluster search as a proxy?

**Comment by CpuID** [comment]
> What prevents you from sending your aliases, mappings etc. request directly to the cluster where they belong, rather than using a cross cluster search as a proxy?

Hi @javanna 

Being able to target a single ES cluster and knowing that the `clustername:` prefixed behaviour works the same as a non-CCS/direct cluster query is the main motivator. Having to expose your app to both your CCS node as well as various backend cluster nodes partially defeats the purpose (I see your point that you've tackled the "hard" part, aggregating search results in CCS), but being able to remove that direct expose to backend clusters would be more elegant.

Technically we can talk to the backends directly, but it's just an added layer we would need in our app. Having this info exposed via CCS would benefit others I suspect as well. Consider the motivator feature parity with non-CCS API calls :)

Being that the response data from each backend cluster is unique by `clustername:indexname` keys, this feels like a trivial improvement.

**Comment by javanna** [comment]
If the purpose is talking to a single node, you could achieve that with a proxy between your application and your clusters. And merging the responses coming from different clusters is indeed trivial, hence I don't see why we would have to add it as a feature to Elasticsearch.

On the other hand, having to expose your app to multiple clusters is natural if you have multiple clusters, I don't think it defeats the purpose of CCS, which  is implementing search against multiple clusters as that cannot be done outside of Elasticsearch. We drew a line when we implemented CCS and we decided to address a specific and well defined use-case, and what can be done outside of Elasticsearch won't be added to Elasticsearch, as it will add complexity to our codebase for no good reason.

**Comment by CpuID** [comment]
> We drew a line when we implemented CCS and we decided to address a specific and well defined use-case, and what can be done outside of Elasticsearch won't be added to Elasticsearch, as it will add complexity to our codebase for no good reason.

OK no problem thanks.
