### ISSUE TITLE
Documents outside geoshape query are returned

### ISSUE THREAD

**Issue by arko-r** [elastic/elasticsearch#27123]
I have a geoshape query which returns more documents than it should.
Some of the documents are outside of the coordinates specified in the query.

The query specifies a latitude between 54 and 55, but in the results documents with a latitude of 55.01 are also returned (longitude is inside specified coordinate range).
However searching for a longitude between -8 and 9, a longitude of 9.01 is not included in the results (latitude is inside specified coordinate range)

Did I miss something what causes the document with latitude 55.01 to be returned, or is this a bug?

**Elasticsearch version**: 6.0.0-rc1
**JVM version**: 1.8.0_144
**OS version**: Windows 10

**Steps to reproduce**:
_Mapping_
`curl -XPUT "http://localhost:9200/test" -H 'Content-Type: application/json' -d'
{"settings":{"number_of_shards":1,"number_of_replicas":0},"mappings":{"value":{"properties":{"location":{"type":"geo_shape"}}}}}'`
_Data_
`curl -XPOST "http://localhost:9200/_bulk" -H 'Content-Type: application/json' -d'
{"index":{"_index":"test","_type":"value"}}
{"location":{"type":"point","coordinates":[54.999,7.497]}}
{"index":{"_index":"test","_type":"value"}}
{"location":{"type":"point","coordinates":[55,7.497]}}
{"index":{"_index":"test","_type":"value"}}
{"location":{"type":"point","coordinates":[55.01,8.2]}}
{"index":{"_index":"test","_type":"value"}}
{"location":{"type":"point","coordinates":[54.5,9.01]}}
{"index":{"_index":"test","_type":"value"}}
{"location":{"type":"point","coordinates":[54.5,9.01]}}
'`
_Query_
`curl -XGET "http://localhost:9200/test/_search" -H 'Content-Type: application/json' -d'
{"query":{"bool":{"must":{"match_all":{}},"filter":{"geo_shape":{"location":{"shape":{"type":"envelope","coordinates":[[55,-8],[54,9]]},"relation":"within"}}}}}}'`

**Comment by DaveCTurner** [comment]
@arko-r thanks for providing a small reproduction for your issue. The bulk request got a little mangled but I can reproduce it.

This is expected behaviour as noted in https://www.elastic.co/guide/en/elasticsearch/reference/6.0/geo-shape.html#_accuracy and due to the way that Elasticsearch indexes geoshapes:

> Geo_shape does not provide 100% accuracy and depending on how it is configured it may return some false positives or false negatives for certain queries. To mitigate this, it is important to select an appropriate value for the tree_levels parameter and to adjust expectations accordingly.

If you require more accuracy, please configure your mapping appropriately using the `precision` and `distance_error_pct` parameters.
