### ISSUE TITLE
Cap indices.fielddata.cache.size by default?

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#27130]
As we continue to look into safeguards for Elasticsearch, is there still a reason to keep `indices.fielddata.cache.size` unbounded even on 5.x, 6.x.+ now that we have moved to doc values?  Even though it is unlikely for fielddata to be an issue (unless someone is doing an agg on large text fields with fielddata enabled, etc..), is it time to actually set a sensible default instead of leaving it as unbounded?

**Comment by dakrone** [comment]
On the other hand, if we continue not to use fielddata for as much, wouldn't it be better to keep the hard limit (circuit breaker) as an indicator that someone is doing something unadvised, rather than just make the system potentially slower by expiring things in the cache?

**Comment by jpountz** [comment]
> is there still a reason to keep indices.fielddata.cache.size unbounded

Yes. I agree with Lee. Evicting silently is just asking for slow queries.

**Comment by ppf2** [comment]
Thanks for the feedback.  The circuit breaker does also break on ordinals usage correct?

**Comment by jpountz** [comment]
Discussed in FixitFriday: we won't make fielddata bounded. However we could lower the fielddata budget for circuit breaking, eg. 40% instead of 70%.

Separately we should investigate removing fielddata entirely (higher hanging fruit since we need to make sure we cover all use-cases and make the upgrade smooth).

**Comment by andyb-elastic** [comment]
@elastic/es-search-aggs

**Comment by danielmitterdorfer** [comment]
Closed by #27162.
