### ISSUE TITLE
Inconsistent exception types thrown while parsing XContent

### ISSUE THREAD

**Issue by olcbean** [elastic/elasticsearch#27147]
In most cases, if the expected `START_OBJECT` is not detected, an `IllegalArgumentException` is thrown :
https://github.com/elastic/elasticsearch/blob/b88dbe8f49745a26ee92476408e17cc0c2d40693/core/src/main/java/org/elasticsearch/common/xcontent/XContentParserUtils.java#L75-L80

However `ObjectParser` throws `IllegalStateException` : 
https://github.com/elastic/elasticsearch/blob/b88dbe8f49745a26ee92476408e17cc0c2d40693/core/src/main/java/org/elasticsearch/common/xcontent/ObjectParser.java#L149-L151

When parsing `mget` two different exception types may be thrown : 
`ParsingException`
https://github.com/elastic/elasticsearch/blob/b88dbe8f49745a26ee92476408e17cc0c2d40693/core/src/main/java/org/elasticsearch/action/get/MultiGetRequest.java#L323-L330

`IllegalArgumentException` 
https://github.com/elastic/elasticsearch/blob/b88dbe8f49745a26ee92476408e17cc0c2d40693/core/src/main/java/org/elasticsearch/action/get/MultiGetRequest.java#L364-L366

while `RepositoryData` consistently throws `ElasticsearchParseException` : 
https://github.com/elastic/elasticsearch/blob/b88dbe8f49745a26ee92476408e17cc0c2d40693/core/src/main/java/org/elasticsearch/repositories/RepositoryData.java#L487

---
I think that it would be much cleaner if only one exception type is used (at least from now on).

For example what exception type should be thrown when a stricter validation of query field names is introduced (#26013). A different one per request (based on the exception thrown till now in the request)? Or an exception of type X?

Or maybe some of the exception types should be changed? For example can `IllegalStateException` be replaced by `IllegalArgumentException`?

**Comment by javanna** [comment]
I think that `ParsingException` is the way to go , as it also includes the position where the problem was found in the original input. `IllegalArgumentException` sounds ok but it doesn't have the position info which is very useful. `IllegalStateException` seems wrong to me in this context.

**Comment by olcbean** [comment]
Thanks @javanna! So we should stick to the `ParsingException` in general.
Actually one more question : shouldn't the `ParsingException` be actually an `IllegalArgumentException`?

**Comment by javanna** [comment]
Yes let's stick to `ParsingException`

> shouldn't the ParsingException be actually an IllegalArgumentException

it could be, I guess it is convenient to subclass `ElasticsearchException` so that a few common methods around serialization (transport and REST) can be inherited. I do not see an advantage in changing this at this point.

**Comment by liketic** [comment]
Hi @olcbean @javanna I found this issue is marked as adoptme. Can I take this? 👍

**Comment by olcbean** [comment]
Hey @liketic, I have already pushed a PR for `ObjectParser`. Sorry about that.

**Comment by olcbean** [comment]
Closed by #27302
