### ISSUE TITLE
Fielddata Error

### ISSUE THREAD

**Issue by pizu** [elastic/elasticsearch#27142]
Good Morning ALL,

I need to set the Fielddata, but cannot find where I should add this.

Am having the below error when trying to access source.

Oct 27 10:50:38 itnetgraylog elasticsearch: [2017-10-27 10:50:38,700][DEBUG][action.search ] [g0_RYrN] [graylog_0][0], node[g0_RYrNlRruQedtzWQBTwQ], [P], s[STARTED], a[id=rXEbg3YTS4mi0DpNLnBFSw]: Failed to execute [org.elasticsearch.action.search.SearchRequest@36ce65c5]
Oct 27 10:50:38 itnetgraylog elasticsearch: RemoteTransportException[[g0_RYrN][127.0.0.1:9300][indices:data/read/search[phase/query+fetch]]]; nested: IllegalArgumentException[Fielddata is disabled on text fields by default. Set fielddata=true on [source] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.];
Oct 27 10:50:38 itnetgraylog elasticsearch: Caused by: java.lang.IllegalArgumentException: Fielddata is disabled on text fields by default. Set fielddata=true on [source] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.index.mapper.core.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:296)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:111)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.config(ValuesSourceAggregationBuilder.java:355)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.resolveConfig(ValuesSourceAggregationBuilder.java:305)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:299)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:49)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:126)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:211)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.AggregatorFactory.(AggregatorFactory.java:187)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregatorFactory.(FilterAggregatorFactory.java:43)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregationBuilder.doBuild(FilterAggregationBuilder.java:77)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:126)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:211)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.SearchService.parseSource(SearchService.java:695)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.SearchService.createContext(SearchService.java:550)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:509)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:352)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.action.SearchTransportService$SearchQueryFetchTransportHandler.messageReceived(SearchTransportService.java:339)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.action.SearchTransportService$SearchQueryFetchTransportHandler.messageReceived(SearchTransportService.java:336)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.transport.TransportService$5.doRun(TransportService.java:517)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:510)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
Oct 27 10:50:38 itnetgraylog elasticsearch: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Oct 27 10:50:38 itnetgraylog elasticsearch: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Oct 27 10:50:38 itnetgraylog elasticsearch: at java.lang.Thread.run(Thread.java:748)
Oct 27 10:50:38 itnetgraylog elasticsearch: [2017-10-27 10:50:38,700][DEBUG][action.search ] [g0_RYrN] All shards failed for phase: [query_fetch]
Oct 27 10:50:38 itnetgraylog elasticsearch: RemoteTransportException[[g0_RYrN][127.0.0.1:9300][indices:data/read/search[phase/query+fetch]]]; nested: IllegalArgumentException[Fielddata is disabled on text fields by default. Set fielddata=true on [source] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.];
Oct 27 10:50:38 itnetgraylog elasticsearch: Caused by: java.lang.IllegalArgumentException: Fielddata is disabled on text fields by default. Set fielddata=true on [source] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.index.mapper.core.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:296)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:111)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.config(ValuesSourceAggregationBuilder.java:355)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.resolveConfig(ValuesSourceAggregationBuilder.java:305)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:299)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:49)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:126)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:211)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.AggregatorFactory.(AggregatorFactory.java:187)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregatorFactory.(FilterAggregatorFactory.java:43)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.bucket.filter.FilterAggregationBuilder.doBuild(FilterAggregationBuilder.java:77)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:126)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:211)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.SearchService.parseSource(SearchService.java:695)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.SearchService.createContext(SearchService.java:550)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:509)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:352)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.action.SearchTransportService$SearchQueryFetchTransportHandler.messageReceived(SearchTransportService.java:339)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.search.action.SearchTransportService$SearchQueryFetchTransportHandler.messageReceived(SearchTransportService.java:336)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.transport.TransportService$5.doRun(TransportService.java:517)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:510)
Oct 27 10:50:38 itnetgraylog elasticsearch: at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
Oct 27 10:50:38 itnetgraylog elasticsearch: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Oct 27 10:50:38 itnetgraylog elasticsearch: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Oct 27 10:50:38 itnetgraylog elasticsearch: at java.lang.Thread.run(Thread.java:748)

The Above error from logs. When trying to call: http://itnetgraylog:12900/api/sources?range=3600

Linux itnetgraylog 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Graylog Version: v2.3.2+3df951e
Elasticsearch Version: 5.0.0_alpha5-1
MongoDB Version: 3.4.10-1.el7
Operating System: Centos 7
Browser version: Latest Chrome/IE/Firefox

**Comment by cbuescher** [comment]
Hi, sorry to hear you are having trouble, but Elastic reserves GitHub for bug reports and feature requests. We provide a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions like this.
