### ISSUE TITLE
Doc should explain what `data` is in the example of Attachment Processor in a Pipeline.

### ISSUE THREAD

**Issue by nguyenlp** [elastic/elasticsearch#27156]
**Describe the feature**:

In our documentation example for the Attachment Processor in a Pipeline.

https://www.elastic.co/guide/en/elasticsearch/plugins/5.5/using-ingest-attachment.html#using-ingest-attachment

```
PUT _ingest/pipeline/attachment
{
  "description" : "Extract attachment information",
  "processors" : [
    {
      "attachment" : {
        "field" : "data"
      }
    }
  ]
}
PUT my_index/my_type/my_id?pipeline=attachment
{
  "data": "e1xydGYxXGFuc2kNCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0DQpccGFyIH0="
}
GET my_index/my_type/my_id
```

**Elasticsearch version** (`bin/elasticsearch --version`):  Elastic Stack 5.5

**Plugins installed**: []  X-Pack 5.5

**JVM version** (`java -version`):  1.8

**OS version** (`uname -a` if on a Unix-like system):  RHEL 7.x

**Description of the problem including expected versus actual behavior**:

Our documentation puts Base64 encoded 'something' in 'data', as shown above, example.  

However, what is that with reference to the original document in our example?  

How are we getting the Base64 encoded value in 'data' for a file (for example from a PDF file named myfile.pdf)?  

Like where does the value in `data` come from?

```
It would be good for us to explain what that `data` is in the example though.

We should explain what the example is.  Maybe hint how to Base64 encode something?

I've been asked by a few customers `what is that base64 string and how do I build one?`

So adding some sentences and examples context will really help.
```

**Comment by dedemorton** [comment]
@spinscale @ywelsch Wondering if either of you can provide some input on what is missing here? I'd be happy to update the docs, but I'm not familiar with this processor and would need to play around with it a bit (afraid I don't have a lot of time for that at the moment).

**Comment by spinscale** [comment]
So, if the user runs `echo 'e1xydGYxXGFuc2kNCkxvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0DQpccGFyIH0=' | base64 --decode | file -` this file gets qualified as an RTF document (rich text format).

We could extend the docs here, stating more clearly, that the base64 string is an encoded content of an RTF document in this concrete example. If the user is having this kind of pipeline, the user needs to do this actual conversion on the client side before sending the data over to Elasticsearch.

Hope this helps!

**Comment by debadair** [comment]
[doc-issue-triage]
