### ISSUE TITLE
SnapshotShardsService should use TransportMasterNodeAction for shard status updates

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#27151]
While reviewing stuck a stuck snapshot issue related to https://github.com/elastic/elasticsearch/issues/25863#issuecomment-336434632, @ywelsch pointed out that we can improve reliability of shard updates by switching the mechanism to TransportMasterNodeAction (we are currently using a plain TransportRequestHandler that doesn't have a robust retry mechanism of TransportMasterNodeAction). This is a simple change that can significantly improve reliability of snapshot on flakey networks.

**Comment by jyoti0208** [comment]
I would like to work on this.

**Comment by ywelsch** [comment]
@jyoti0208 This is already assigned and there is already an open PR for this - no need to work on this.

**Comment by jyoti0208** [comment]
Is there any other task which I can take as the first-time contributor for this project.

**Comment by ywelsch** [comment]
Sure, any issue marked as `adoptme` is up for grabs. Issues that are additionally marked as `low hanging fruit` should be simpler tasks. 

Please also have a look at our [contributing guide](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md) which will help you get started.
