### ISSUE TITLE
Wrong disk free space reported when there are multiple data paths

### ISSUE THREAD

**Issue by tsullivan** [elastic/elasticsearch#27174]
Moving https://github.com/elastic/kibana/issues/14442 to Elasticsearch repo

Quoting from original author:

> **Kibana version**:
> 5.5.0
> **Elasticsearch version**:
> 5.5.0
> **Server OS version**:
> centos 6.x
> **Browser version**:
> chrom 61.0.3163.91
> **Browser OS version**:
> win 7 64 bit
> **Original install method (e.g. download page, yum, from source, etc.)**:
> download from elastic.co
> **Description of the problem including expected versus actual behavior**:

> I set two path as elasticsearch store data path
> "path" : "/data1/esdata/cc_elastic_node_data1/nodes/0",
> "mount" : "/data1 (/dev/sdb1)",

> "path" : "/data1/esdata/cc_elastic_node_data2/nodes/0",
> "mount" : "/data1 (/dev/sdb1)",

> and my server disk free space (dev/sdb1) is 1.5T
 
> but in kibana monitoring（x-pack）-> nodes -> Disk Free Space it display 3.0 TB, it  calculated same disk twice, is it right?

The value shown in Kibana Monitoring comes from Cluster Stats (`GET _cluster/stats`), which confirms that the calculation for free disk space is doubled when the node is configured to have 2 data paths.

cc @shijiebei2009 @leandrojmp

**Comment by jasontedor** [comment]
This is indeed thrown off by using two paths on the same mount point. It's not clear what the use-case is for this, but we can solve this by de-duplicating based on the underlying store which we already have access to. That said, this is super low-priority so we are going to mark this [`adoptme`](https://github.com/elastic/elasticsearch/labels/adoptme).

**Comment by rjernst** [comment]
Multiple data paths will be deprecated in 7.13 and removed in 8.0 (see https://github.com/elastic/elasticsearch/issues/71205). Given that, I believe this issue is no longer relevant, so I will close it.
