### ISSUE TITLE
Make large indexes easier to manage

### ISSUE THREAD

**Issue by scottsom** [elastic/elasticsearch#27176]
Since large is subjective, you can interpret it as an index measured in terabytes.

## Problem
For non-time series data, it can be difficult to find a value to split your data on when defining your indexes. You need a value that is relatively low cardinality and always has a single value on your documents. If you don't have such a field then you'll probably end up creating a single index to store all of your data. Even when you can split your data into indexes, you may still find yourself with large indexes simply due to scale and/or poor data distributions.

As part of your cluster operations, there will likely come a time where you need to temporarily duplicate an index. For example, recreating the index to change options like the shard count, mappings, or other settings that can only be changed at index creation time. Another example is recovery when you lose some shards and restore from backups to a new index.

In these situations, you'll need enough hardware to sustain two fully replicated versions of your index before you shift your traffic from your old index to your new index then drop the old index. You'll need to potentially double the nodes in your cluster assuming you weren't heavily over-scaled to begin with. If you like to live dangerously then you could probably avoid this by disabling replicas but I'll assume that is not the norm considering the data loss risk.

For small clusters, temporarily going from 2 nodes to 4 nodes won't be a big deal but extrapolating this to a larger scale then it can start to become problematic - temporarily doubling the size of 50 / 100 / 200 node clusters is undesirable.

I think it would be helpful if there was a built-in way to break such indexes down into smaller pieces, so they can be worked with individually and iterated over rather than trying to do everything in one shot.

There are ways to do this from the client side today but I'd see that as a workaround rather than a solution.

## Proposal
One way to tackle this problem is to add support for an index of indexes, or what I'll call a composite index. This would function similar to an alias except it enforces some additional constraints and it would always be writable.

A composite index is created with a list of 2 or more existing indexes and the number of indexes cannot be changed after creation. For example, creating composite index `foo` with 2 underlying real indexes:

```javascript
PUT /_composites/foo
{
  "indexes": [
    "foo_0_v1",
    "foo_1_v1"
  ]
}
```

Indexing a document against `foo` will do the calculation `hash(_id, seed) % num_indexes` to pick between `foo_0_v1` and `foo_1_v1`.
* If `_routing` was provided, that would be used instead of `_id`
* A composite index must use a different `seed` than the current default to ensure a good data distribution across shards

Searching against `foo` will go across all indexes unless a `_routing` value is provided, in which case it will pick the index based on the above calculation.

Once an index is selected then the request will be forwarded to it and it will handle the request as it does today as if you had made the request against it directly.

If we later recreate or restore an underlying index then it can be swapped out. For example, replacing `foo_0_v1` with `foo_0_v2` might look like:

```javascript
PUT /_composites/foo
{
  "indexes": [
    "foo_0_v2",
    "foo_1_v1"
  ]
}
```

Once you have swapped in `foo_0_v2` then `foo_0_v1` can be deleted and work can begin on creating `foo_1_v2`.

With this approach we can do a rolling rebuild of large indexes. For this simple example, since we have two real indexes then we only need enough hardware to handle a copy that is 50% of the original size at any given time.

With 20 underlying indexes, we'd never need a copy larger than 5% of the original size and potentially not even have to temporarily add nodes since you'd probably already have your cluster slightly over-scaled giving you enough buffer for small index rebuilds.

**Comment by jbaiera** [comment]
Perhaps it makes sense to file this as an enhancement to aliases? I believe I've seen discussions in the past around how Elasticsearch might support writing to aliases with multiple indices, and this looks pretty similar in structure.

**Comment by scottsom** [comment]
I agree that it would make sense as an extension to aliases. However, from talking to @s1monw & @jasontedor at Elasticon, it didn't seem like they wanted to see aliases extended with new functionality, so I left them out here.

**Comment by rpedela** [comment]
I like this proposal overall. I have a 1.5 TB index and a tight budget which is very painful to reindex. However I don't see how you would be able to reindex one of the smaller indexes. Would you use the reindex API for each smaller index? What about manual reindexing because the source needs to change? How do you only manual reindex the documents in a smaller index given the distribution is handled by ES?

**Comment by scottsom** [comment]
Yes, both the reindex API and manual reindexing will work on these smaller indexes.

The composite index is essentially a front-end router that will consistently route an `_id` and/or `_routing` value to the same location (in this case, an index).

To re-use the example from above, when you look at a concrete index like `foo_0_v1` on its own, there is nothing special about it, it's just a regular index that is no different than what you are working with today. The fact that it is fronted by the composite index `foo` does not prevent you from using any of the existing APIs like restoring a snapshot, reindexing, shrinking, etc. when working with `foo_0_v1` directly.

If you wanted to reindex from `foo_0_v1` to `foo_0_v2` then you have two options: temporarily stop updates or dual write to your new and old index. These might work as follows:

### Stop Updates
This is the easier option but may not always be possible for when you have tight SLAs on index freshness or can't queue updates.

1. Create index `foo_0_v2`
2. Stop updates to your index
3. Reindex everything from `foo_0_v1` to `foo_0_v2` (using the API or manually)
4. Replace `foo_0_v1` with `foo_0_v2` in your composite index, `foo`
5. Resume updates to your index
6. Delete `foo_0_v1`
7. Repeat 1 - 6 for remaining parts

### Dual Write
This is a bit more complicated but would let you handle new updates while rebuilding your index. It's similar to the steps above but instead of disabling writes, you need to "mirror" changes from `foo_0_v1` to `foo_0_v2`.

1. Create index `foo_0_v2`
2. Establish a mirror from `foo_0_v1` -> `foo_0_v2`
3. Reindex everything from `foo_0_v1` to `foo_0_v2` while preserving the original version (using the API or manually)
4. Replace `foo_0_v1` with `foo_0_v2` in your composite index, `foo`
5. Remove your mirror
6. Delete `foo_0_v1`
7. Repeat 1 - 6 for remaining parts

To elaborate on what I mean by mirroring, some pseudocode for ingestion logic might be:

```
mirrors = { foo_0_v1: foo_0_v2 }
composite_index = foo

...

result = write(composite_index, id, source)

if result.index in mirrors:
  new_index = mirrors[result.index]
  # Does a write with version_type = external
  write(new_index, id, source, result.version)
```

This would work as long as a the write result against a composite index returns the resulting concrete index (just like an alias does).

**Comment by imotov** [comment]
We discussed this in Fix-it-Friday and agreed that we should not implement this feature at this moment. 

We know many cases where elasticsearch users are using several indices as a way to deal with extremely large amount of homogenous data, that would be impractical to store in a single index. While doing this they use a variety of rules for routing documents into different indices and the approach described here is just one example of many different implementation that we saw in the recent years. These users also perform different types of operations to be performed on such composed indices. Because of the diversity of use cases that we have observed, we feel that to make this feature generally applicable we would have to add a lot of complexity to the API and index resolution mechanism. At the same time an implementation covering a concrete use cases like this can be easily made on the client side.

**Comment by rpedela** [comment]
> Because of the diversity of use cases that we have observed, we feel that to make this feature generally applicable we would have to add a lot of complexity to the API and index resolution mechanism. At the same time an implementation covering a concrete use cases like this can be easily made on the client side.

This is not "easily made" on the client. Reindexing was one of those things that every user had to implement themselves and it wasn't easy. It wasn't hard necessarily, but it certainly wasn't easy either. Then the Reindex API was added and made it so much easier for users to reindex small and medium sized indices. Thank you! But there is a still a problem: users with large indexes have to do it themselves or invent ways to organize their indices to utilize ```_reindex``` or ```update_by_query```.

Maybe this specific proposal is a bad one, but the problem still exists. Why are you closing the issue? Why isn't there an open, community discussion about possible solutions? Why is it that many obvious features are shot down in some closed-door meeting? Is "code complexity" really a good reason to say no? What about user experience complexity? Does code complexity always trump user experience complexity?

**Comment by scottsom** [comment]
Just to add my 2 cents if this decision is open to appeal.

My primary intent when creating this issue was to raise awareness of a pain point and hopefully spur discussion on ways it can be solved in Elasticsearch which is why I made the title open ended rather than something specific to my proposal (e.g. "Add support for an index of indexes"). Maybe a solution to this problem needs to iterate on what I have proposed or approach it in a radically different way. Either way, I'm just trying to see this problem addressed in what I believe is the right place. Having clients write their own libraries to do their own hashing and routing computations in their application code feels like poor separation of concerns to me.

Maybe we can't cater to all use cases but isn't that the nature of Elasticsearch - finding the right balance between simplicity and flexibility with a bias towards the former?

Suppose it is the case that an acceptable solution cannot be found due to the diverse and/or complex strategies people have developed. Maybe it is worth discussing whether appropriate hooks can be added to Elasticsearch so plugin authors can add their own index resolution strategies.

**Comment by clintongormley** [comment]
Hi @scottsom 

We did spend a fair bit of time discussing this proposal, it certainly wasn't dismissed out of hand.

We were concerned with the fragility of possible solutions along with the need to introduce a new high-level concept to encapsulate this index-of-indexes.  Also, if we were to do something like this, we fully expect a long list of feature requests asking for different routing strategies etc, as there are many ways to decide how to segment your data.  One generic solution is unlikely to be enough.

This makes us reluctant to make a change like this at the moment, and rather leave it to be done client side.  Perhaps it is something we'll revisit later when there is a clearer generic use case.  But for the now, there are other improvements that we would prefer to focus on.

**Comment by scottsom** [comment]
Thanks, it would be easy to shoot yourself in the foot here so I definitely see the concern.

Any thoughts on adding support for custom index resolution strategies via plugins?
