### ISSUE TITLE
Snapshot process can get stuck in INIT state

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#27180]
If the master disconnects from the cluster after initiating snapshot, but just before the snapshot switches from INIT to STARTED state, the snapshot can get indefinitely stuck in the INIT state. This error is specific to v5.x+ and was triggered by [keeping the master node that stepped down in the node list](https://github.com/elastic/elasticsearch/pull/22049), the cleanup logic in snapshot/restore assumed that if master steps down it is always removed from the the node list. We need to change the cleanup logic to be triggered even if no nodes left the cluster.

**Comment by LarryLo** [comment]
I've met the same issue but have no idea how to stop the snapshot stuck in INIT state.
Any suggestion? Thank you.
