### ISSUE TITLE
StackOverflowError after a Fatal Error on Network Layer

### ISSUE THREAD

**Issue by zzt93** [elastic/elasticsearch#27184]
**Elasticsearch version** (`bin/elasticsearch --version`):  
Version: 5.6.1, Build: 667b497/2017-09-14T19:22:05.189Z, JVM: 1.8.0_45

**Plugins installed**: [xpack, analysis-icu, analysis-smartcn, analysis-ik]

**JVM version** (`java -version`): 1.8.0.45

**OS version** (`uname -a` if on a Unix-like system): 
Linux ubuntu-100 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
The ES log the stackoverflow error then exit.

**Steps to reproduce**:

I am not sure how to reproduce the error, but the error pattern appear twice, I guess they are related.

**Provide logs (if relevant)**:
[Error log](https://gist.github.com/zzt93/7eca0b24ec21d4180e00772d36e4c46a)

**Comment by bleskes** [comment]
Thanks @zzt93 . This was fixed by https://github.com/elastic/elasticsearch/pull/27069 , which will be part of 6.0 (starting with rc2). I'm going to close the issue as it is a dup. 

@jasontedor I didn't look at the details but do you think we want/can backport the fix to 5.6?

**Comment by jasontedor** [comment]
@bleskes This is indeed the same issue that was fixed in 6.0.0 only. We can backport the fix, but it also requires backporting #26484.

**Comment by jasontedor** [comment]
I backported these in 7fa51b3fb640c14ae18363cab6f3c168855e56b7 and https://github.com/elastic/elasticsearch/commit/a26062fa5b19de5aa940f433582ab156dee19db3. This will be fixed in 5.6.4.
