### ISSUE TITLE
index.translog.flush_threshold_size: 50mb not cleaning translogs

### ISSUE THREAD

**Issue by sgutta1** [elastic/elasticsearch#27197]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 2.0.1, Build: 1ebe2f1/2015-11-18T17:42:23Z, JVM: 1.8.0_121

**Plugins installed**: []
SSLPlugin (custom)

**JVM version** (`java -version`):
 1.8.0_121

**OS version** (`uname -a` if on a Unix-like system):
3.10.0-327.36.3.el7.x86_64

**Description of the problem including expected versus actual behavior**:
We have set index.translog.flush_threshold_size: 50mb in yml file, but translog size is going into GBs and total translogs now are close to 20GB.

**Steps to reproduce**:
Set index.translog.flush_threshold_size: 50mb in elasticsearch.yml and restart elasticsearch

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by talevy** [comment]
thank you for reporting, would you mind sharing your [Indices Stats](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/indices-stats.html) to gather more details of the state of your cluster and translog statistics?

**Comment by jasontedor** [comment]
This is from 2.0.1 which indeed had bugs along these lines. These are fixed in later versions of the 2.x series (please upgrade to latest for the fixes). I’m closing this as a known issue for such an old version.

**Comment by sgutta1** [comment]
We are upgrading to 5.5.2 in couple of months. But till that time, is it OK to do a force flush,so that translogs do not grow in size?
