### ISSUE TITLE
Long,double,float numeric types issue with painless scripting

### ISSUE THREAD

**Issue by morphers82** [elastic/elasticsearch#27199]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.0.0-rc2, -rc1
**Plugins installed**: []
kibana

**JVM version** (`java -version`):
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux ubuntu4 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

scripted_upsert on long,double,float datatypes (only ones tested) acts like it is integer and does not allow larger than integer of 2,147,483,647
short data type returns error, but integer and long, double,float do not for test2 field in reproducing steps:
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse [test2]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse [test2]",
    "caused_by": {
      "type": "json_parse_exception",
      "reason": "Numeric value (-2147483648) out of range of Java short\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@5d6c0c32; line: 1, column: 21]"
    }
  },
  "status": 400
}

**Steps to reproduce**:

PUT testing
{
    "settings" : {
        "index" : {
            "number_of_shards" : 5, 
            "number_of_replicas" : 0
        }
    }
}

PUT testing/_mapping/testing
{
  "properties" : {
    "test2" : {
      "type" : "long"
    }
  }
}

POST _scripts/test_script
{
  "script": {
    "lang": "painless",
    "source": "ctx._source.test2=0;ctx._source.test2 += params.test_epoch_second;ctx._source.test2 += params.test_epoch_second;"
  }
}

POST testing/testing/1/_update
{
  "scripted_upsert": true,
	"script":{
    "id":"test_script",
     "params":{
     	"test_epoch_second": 1073741824
     }
	},
  "upsert" : {}
}

**Comment by talevy** [comment]
Hi @morphers82, looks like you are running into an issue that Painless does not know the type of the literal `0` you are setting with `ctx._source.test2=0;`.

try replacing that first assignment with `ctx._source.test2=0L;` to be explicit that the zero is a long.


```
DELETE testing

PUT testing
{
  "settings" : {
    "index" : {
      "number_of_shards" : 1,
      "number_of_replicas" : 0
    }
  },
  "mappings": {
    "testing": {
      "properties": {
        "test2": {"type": "long"}
      }
    }
  }
}

POST _scripts/test_script
{
"script": {
  "lang": "painless",
  "source": "ctx._source.test2=0L;ctx._source.test2 += params.test_epoch_second;"
}
}

POST testing/testing/1/_update
{
"scripted_upsert": true,
"script":{
"id":"test_script",
"params":{
"test_epoch_second": 2147483648
}
},
"upsert" : {}
}
```

```
# GET testing/testing/1
{
  "_index": "testing",
  "_type": "testing",
  "_id": "1",
  "_version": 1,
  "found": true,
  "_source": {
    "test2": 2147483648
  }
}
```

**Comment by rjernst** [comment]
I don't think this is a painless problem; this is just how numeric types work. The default numeric type for an integral number is `int`. It is the same in java. Putting it into a generic map that is used for `ctx._source` can only capture that information. As @talevy pointed out, you can make it explicit by using the `L` suffix (just like in java).
