### ISSUE TITLE
Customized dynamic templates to remove prefix/suffix

### ISSUE THREAD

**Issue by bneelima84** [elastic/elasticsearch#27203]
We have a requirement where defining static mappings is in-convenient, as we allow runtime addition of new properties within a document; So, we would like to use dynamic templates to tell us which fields should be mapped to the exact type that we want; (PS: We don't want to turn on numeric/date detection); 

With dynamic templates, we need to prefix or suffix the fieldNames in-order to get the correct types; However, we wouldn't want the prefix/suffix in actual to go the document that gets indexed eventually; Could we have an option in dynamic templates to remove the prefix/suffix (if need be) ? This option would apply at 
1. While adding new mappings based on dynamic templates
2. To the actual document that gets indexed

I had a quick look at the code and have a set of changes; but wanted to get your opinion if this is a good idea or are there any better ways of handling such things ? 

**Elasticsearch version** (`bin/elasticsearch --version`): 2.4.0

**Plugins installed**: [delete-by-query]

**JVM version** (`java -version`): JDK 1.7

**Comment by jasontedor** [comment]
I think this would introduce needless complexity into dynamic templates when the same could be solved with an ingest processor?

**Comment by jpountz** [comment]
Discussed in FixitFriday. We understand the use-case but it introduces complexity in an area of Elasticsearch that is already quite complex as well as a few corner-cases, like in case a field appears with two different suffixes in a collection. So we'll pass on this one.

**Comment by bneelima84** [comment]
@jasontedor Have a question on using ingest processor for this scenario;
Will the mappings be determined before ingest processing starts or are they determined after ingest processing is complete ?
