### ISSUE TITLE
GetTermVectorsIT.testFilterDocFreq fails on 6.x

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#27215]
With the following error:

```
FAILURE 0.35s J2 | GetTermVectorsIT.testFilterDocFreq <<< FAILURES!
   > Throwable #1: arrays first differed at element [0]; expected:<tag_4[1]> but was:<tag_4[0]>
   > 	at __randomizedtesting.SeedInfo.seed([FF74051DB622A7A9:CE98452659B9F16]:0)
   > 	at org.elasticsearch.action.termvectors.GetTermVectorsIT.checkBestTerms(GetTermVectorsIT.java:1037)
   > 	at org.elasticsearch.action.termvectors.GetTermVectorsIT.testFilterDocFreq(GetTermVectorsIT.java:982)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: org.junit.ComparisonFailure: expected:<tag_4[1]> but was:<tag_4[0]>
   > 	... 42 more
```

I was able to get it to reproduce only once out of many runs with the following:

```
gradle :core:integTest -Dtests.seed=FF74051DB622A7A9 -Dtests.class=org.elasticsearch.action.termvectors.GetTermVectorsIT -Dtests.security.manager=true -Dtests.locale=sv -Dtests.timezone=America/Resolute
```

And the original failure is at https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+oracle-periodic/1167/console

**Comment by dakrone** [comment]
@jpountz I'm unsure of who would be a good person for this, almost all of the git blame is for someone who doesn't work for Elastic any more. In the meantime I am assigning to you, let me know if there's someone who would be better suited!

**Comment by jpountz** [comment]
I reviewed the code and couldn't find the cause of the problem. Also I can't find any failures of this test since November 6th 2017, so I'll close.
