### ISSUE TITLE
no alive nodes found in your cluster all of sudden

### ISSUE THREAD

**Issue by ManishAtSmartshore** [elastic/elasticsearch#27224]
Hi,
I am running into a problem with ES service. Some cron jobs are running on my server and crawling data from other applications. Then the data is indexed in elastic. 
The problem is Elastic service failed any time, and doesn't index data. Saying error
"no alive nodes found in your cluster". 
I had to manually restart the Elasticsearch service, then it back up to work.
(FYI: I am using very basic Elastic configuration)
What can be the cause? Any help Please!

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
