### ISSUE TITLE
ES5.4.3 shrink error 

### ISSUE THREAD

**Issue by hjxhjh** [elastic/elasticsearch#27223]
there is a template 
`{
  "template": "wm_op_log_*",
  "settings": {
    "index": {
      "routing": {`
command line:
`wm_op_log_201701/_shrink/wm_op_log_201701_new?pretty -d'
{
  "settings": {
    "index.number_of_replicas": 0,
    "index.number_of_shards": 10,
    "index.codec": "best_compression"
  },
  "aliases": {
    "wm_op_log_last_year": {},
    "wm_op_log_all": {}
  }
}'`

response:
`{
  "error" : {
    "root_cause" : [
      {
        "type" : "remote_transport_exception",
        "reason" : "[dx-eagle-waimai-oplog13][10.32.171.49:8042][indices:admin/shrink]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "mappings are not allowed when shrinking indices, all mappings are copied from the source index"
  },
  "status" : 400
}`

**Comment by hjxhjh** [comment]
maybe like this https://github.com/elastic/elasticsearch/pull/25380

**Comment by ywelsch** [comment]
Which ES version is this on?

**Comment by hjxhjh** [comment]
version is 5.4.3

**Comment by ywelsch** [comment]
Looks to be #25380 then. Can you try to upgrade to the latest 5.6 version and see if that fixes the issue?
