### ISSUE TITLE
[CI] Failure in packaging `80_upgrade.bats` test

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#27234]
* Build failure link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.0+packaging-tests/269/console

* Error message: 
```
06:14:31 # Checking that the cluster health matches the waited for status...
06:14:31 # unexpected status:  'green' wanted 'yellow'
06:14:31 ok 220 [UPGRADE] check elasticsearch version is version under test
06:14:31 not ok 221 [UPGRADE] verify that the documents are there after restart
06:14:31 # (in test file /project/build/bats/tests/80_upgrade.bats, line 105)
06:14:31 #   `curl -s localhost:9200/library/book/1?pretty | grep Elasticsearch' failed
06:14:31 ok 222 [UPGRADE] stop version under test
```

* Reproduction line: (reproduces locally)
```
REPRODUCE WITH: gradle :qa:vagrant:vagrantFedora26#packagingTest -Dtests.seed=D3D46BD475A0C1D1 
```

**Comment by ywelsch** [comment]
Still broken with same failure one month later: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.0+packaging-tests/374/consoleFull

**Comment by jasontedor** [comment]
@ywelsch What do you mean still broken one month later? The test has been green in the interceding period. In fact, mostly green.

**Comment by jasontedor** [comment]
I think this latest failure had to do with the version bump?

**Comment by jasontedor** [comment]
To be clear, the version having not yet been bumped but should pass after a build with the bump in place completes.

**Comment by jasontedor** [comment]
The latest build is successful. I am treating this as a temporary issue from the version bump and closing this out.
