### ISSUE TITLE
[binary] fields do not have doc_values enabled by default

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#27240]
I'm not sure if this is actually working as intended and a documentation bug, or an actual bug with the documentation being right (either way, existing docs are wrong). The documentation says that `doc_values` are enabled by default for `binary` fields, but that is not the case:

```http
PUT /test
{
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "doc": {
      "properties": {
        "message": {
          "type": "keyword"
        },
        "blob": {
          "type": "binary"
        }
      }
    }
  }
}

PUT /test/doc/1
{
  "message": "in a bottle",
  "blob": "U29tZSBiaW5hcnkgYmxvYg=="
}

GET /test/_search
{
  "query": {
    "bool": {
      "filter": {
        "script": {
          "script": {
            "source": "doc['blob'] != null"
          }
        }
      }
    }
  }
}
```

Unless you manually specify `"doc_values": true` for the `binary` field, the script triggers an exception:

```
org.elasticsearch.index.mapper.MappedFieldType.failIfNoDocValues(MappedFieldType.java:418)
org.elasticsearch.index.mapper.BinaryFieldMapper$BinaryFieldType.fielddataBuilder(BinaryFieldMapper.java:125)
...
```

**Comment by colings86** [comment]
I think this is a documentation bug. IMO the primary use case for binary fields is to store a blob that you don't want to search or aggregate on but you want to be returned in the `_source` of hits. An example of this would be embedding a small profile picture in documents.
