### ISSUE TITLE
_nodes/stats reports wrong values for transport.tx_size_in_bytes

### ISSUE THREAD

**Issue by floragunncom** [elastic/elasticsearch#27258]
**Elasticsearch version** (`bin/elasticsearch --version`):
5.6.2

**Plugins installed**: []

**JVM version** (`java -version`):
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Mac OS 10.11

**Description of the problem including expected versus actual behavior**:
`/_nodes/stats` reports wrong values for `transport.tx_size_in_bytes`

**Steps to reproduce**:
Setup a cluster with two nodes or more and compare `transport.tx_size_in_bytes` reported by `/_nodes/stats` with figures recorded via network tracing tool like wireshark or similar.

After a few debugging sessions it looks like that it boils down to `Netty4MessageChannelHandler.write` which retrieves the readable bytes of the `ByteBuf` as a promise listener.

<pre>
    @Override
    public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception {
        if (msg instanceof ByteBuf && transportServiceAdapter != null) {
            // record the number of bytes send on the channel
            promise.addListener(f -> transportServiceAdapter.addBytesSent(((ByteBuf) msg).readableBytes()));
        }
        ctx.write(msg, promise);
    }
</pre>

For me it looks that the code should be something more like:
<pre>
    @Override
    public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception {
        if (msg instanceof ByteBuf && transportServiceAdapter != null) {
            // record the number of bytes send on the channel
            final int bytesSent = ((ByteBuf) msg).readableBytes());
            promise.addListener(f -> transportServiceAdapter.addBytesSent(bytesSent));
        }
        ctx.write(msg, promise);
    }
</pre>

ES 6.0.0-rc2 works correctly btw.

**Comment by floragunncom** [comment]
@jaymode ping

**Comment by tbrooks8** [comment]
Fixed by #29194. Will be in the v5.6.9 release. Thanks for the issue.
