### ISSUE TITLE
Elasticsearch Java Api can't store painless script

### ISSUE THREAD

**Issue by ericsantosnascimento** [elastic/elasticsearch#27275]
**Bug Report:** ElasticSearch stored script feature using java api returns failing to insert painless script.

**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.1

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_141

**OS version** (`uname -a` if on a Unix-like system): Mac Os Sierra 10.12.6

**Description of the problem including expected versus actual behavior**:

I have some integration tests which demands a embedded elastic search, we added a new change in your application which demands a painless script on the cluster to return the properly search results to the user, right now I'm trying to add a step which try to store the painless script in your embedded cluster so I can adapt your integration tests, However when I try to execute to following line

`this.client.admin().cluster().preparePutStoredScript().setId(fileName.substring(0, fileName.indexOf(".painless"))).setContent(bytesArray).get();`

I get the following error, _java.lang.IllegalArgumentException: unable to put stored script with unsupported lang [painless]_ 

 the current documentation is outdated since the api had changes so I'm not sure if i'm doing this right or not, can you guys provide some input about this error?

**Steps to reproduce**:

 1. spin up a embedded cluster
 2. execute the following line `this.client.admin().cluster().preparePutStoredScript().setId(fileName.substring(0, fileName.indexOf(".painless"))).setContent(bytesArray).get();` with some sort of painless script.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
This strikes me as not a bug, but instead a problem with how you're setting up the embedded node (which we do not recommend for testing, despite how convenient it is). I suspect that you do not have the Painless plugin installed on your embedded node. If you need additional help, please use the forum; we can reopen this if there really is a bug here.

**Comment by ericsantosnascimento** [comment]
Hello @jasontedor thank you for the feedback... well I trust you if is not a bug is not a bug, I'll try to check my embedded cluster plugins...

**Comment by ericsantosnascimento** [comment]
Forum question -> https://discuss.elastic.co/t/embbeed-elastic-search-how-to-install-painless-plugin/106528 I would be very thankful if someone help me.
