### ISSUE TITLE
how to use split on script field on kibana

### ISSUE THREAD

**Issue by xcl3721** [elastic/elasticsearch#27272]
hi.
i wrote the painless script field on the kibana 5.6.1
it's not work /&/.split(param)
code is

int path = doc['x_name.keyword'].value.indexOf('http');
if(path == -1) {
    return '';
}

int paramstart = doc['x_action.keyword'].value.indexOf('?');
if(paramstart == -1){
    return doc['x_action.keyword'];
}

String url = doc['x_action.keyword'].value.substring(0,paramstart);
String param = doc['x_action.keyword'].value.substring(paramstart+1);
if(param != '' && param.indexOf('teset') != -1){
    //param.split('/e/');
           return param;
}
return '';
how to use the split on script field

**Comment by cbuescher** [comment]
Elastic reserves GitHub for bug reports and feature requests but provides a [Discourse forum](https://discuss.elastic.co) and [IRC channels](https://www.elastic.co/community) for general questions.
