### ISSUE TITLE
Have an API command to force re-election of master nodes or specific a node as the primary master

### ISSUE THREAD

**Issue by jkelastic** [elastic/elasticsearch#27285]
**Elasticsearch version** (`bin/elasticsearch --version`): ES 5.6.3

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_144

**OS version** (`uname -a` if on a Unix-like system): Linux  x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Users would like to have an API command to force master re-election or specific a node as the primary master. Currently, restart a master to force election generates a lot of errors in the logs and having a command to do it would be more graceful.

**Comment by jasontedor** [comment]
Duplicates #26992
