### ISSUE TITLE
_nodes/usages: Use REST Spec Names instead

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#27288]
Taking a look at the current master usage of `_nodes/usage`, it contains what are effectively arbitrary names, such as `document_get_action`. It may prove to be more useful _and_ testable if we instead named them based on the the REST Spec name. It would also provide a direct link from the REST spec to the REST endpoint that implements it.

```http
GET /_nodes/usage
{
  "_nodes": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "cluster_name": "my-test",
  "nodes": {
    "dooZWOJ6Q_KdoED5hitzxw": {
      "timestamp": 1509996167568,
      "since": 1509397901314,
      "rest_actions": {
        "nodes_usage_action": 3,
        "document_update_action": 3,
        "put_mapping_action": 2,
        "nodes_info_action": 462278,
        "get_settings_action": 2,
        "get_mapping_action": 231145,
        "document_index_action": 8,
        "create_index_action": 7,
        "get_all_aliases_action": 10280,
        "delete_index_action": 4,
        "document_create_action": 2,
        "get_all_mappings_action": 10280,
        "search_action": 878876,
        "update_settings_action": 5,
        "cluster_health_action": 231144,
        "main_action": 231244,
        "docuemnt_get_action": 131982
      }
    }
  }
}
```

Noting the typo as an example of something that would be avoided (fixed in #27266), but also `main_action`, which translates into the "info" REST endpoint (but in code is the `MainAction`).

As a minor / natural downside, we would be responding with some keys that contain `.` in them, such as `"cluster.put_settings"`, but that _is_ valid.

**Comment by jasontedor** [comment]
We discussed this during Fix-it-Friday. Today we prefer the connection between the names and the implementations in the codebase, there's no enforced connection between the names in the REST spec and the implementations in the codebase. There will hopefully be a day when the spec is generated from the code or vice-versa in which case such a relationship would come for free. As such, we are going to keep this as-is for now.
