### ISSUE TITLE
elasticsearch-plugin.bat error with spaces in java.exe path

### ISSUE THREAD

**Issue by cyril1531** [elastic/elasticsearch#27289]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.3

**Plugins installed**: [] None

**JVM version** (`java -version`): jdk1.8.0_131

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:
"C:\Program" is not a valid command

Fixed by adding double quotes on %JAVA% variable like this:

elastic-search-plugin.bat:

@echo off

SETLOCAL enabledelayedexpansion

IF DEFINED JAVA_HOME (
  set JAVA="%JAVA_HOME%\bin\java.exe"
) ELSE (
  FOR %%I IN (java.exe) DO set JAVA=%%~$PATH:I
)

IF NOT EXIST "%JAVA%" (
  ECHO Could not find any executable java binary. Please install java in your PATH or set JAVA_HOME 1>&2
  EXIT /B 1
)

set SCRIPT_DIR=%~dp0
for %%I in ("%SCRIPT_DIR%..") do set ES_HOME=%%~dpfI

TITLE Elasticsearch Plugin Manager 5.6.3

SET path_props=-Des.path.home="%ES_HOME%"
IF DEFINED CONF_DIR (
  SET path_props=!path_props! -Des.path.conf="%CONF_DIR%"
)

SET args=%*
SET HOSTNAME=%COMPUTERNAME%

"%JAVA%" %ES_JAVA_OPTS% !path_props! -cp "%ES_HOME%/lib/*;" "org.elasticsearch.plugins.PluginCli" !args!

ENDLOCAL

**Comment by DaveCTurner** [comment]
Afraid I don't have an available machine to try and reproduce this on. There are lots of other `.bat` files that look similar, however.

**Comment by DaveCTurner** [comment]
This issue was apparently introduced into 5.4.1 by 8d654eecad17b7ebb9f139201cf7512bc1409e9a, and fixed in 6.* by #25958.

**Comment by rjernst** [comment]
As @DaveCTurner mentioned, this was already fixed in 6.0. I'm going to close this as I don't think back porting the fix to 5.6 is likely.
