### ISSUE TITLE
Update scripting documentation for Java Api

### ISSUE THREAD

**Issue by ericsantosnascimento** [elastic/elasticsearch#27282]
Hello, can someone envolved in the scripting and java api part update the documentation below?

https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/indexed-scripts.html

as you can see above, it's very outdated, right now it's barely impossible to use this documentation since everything have changed, I would love to contribute with such change but actually I can't even make my own piece of code to insert a painless script on my cluster work.

What I'm missing it's basic examples about how to store painless scripts using the java api.

**Comment by javanna** [comment]
@jdconrad can you have a look please?

**Comment by jdconrad** [comment]
@javanna  Will do.

**Comment by jdconrad** [comment]
Going to close this in favor of https://github.com/elastic/elasticsearch/issues/23777
