### ISSUE TITLE
Bug: Sum_bucket result ordering does not work

### ISSUE THREAD

**Issue by ali-bugdayci** [elastic/elasticsearch#27293]
Using docker hub image:

REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
elasticsearch                   5                   7516701e4922        11 weeks ago        315.5 MB

**Elasticsearch version** (`bin/elasticsearch --version`):
```
root@836e3b7e7622:/usr/share/elasticsearch# elasticsearch --version
Version: 5.5.2, Build: b2f0c09/2017-08-14T12:33:14.154Z, JVM: 1.8.0_141
```

**Plugins installed**: []

**JVM version** (`java -version`):
```
root@836e3b7e7622:/usr/share/elasticsearch# java -version
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-1~deb9u1-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)
```

Cant order on sum_bucket results:

The following query works
```

	"aggs": {
		"sources": {
			"terms": {
				"field": "@source",
				"size": 20,

				"min_doc_count": 1
			},
			"aggs": {
				"sources_aggs": {
					"sum_bucket":{
						 "buckets_path": "sources_nested>sources_targets"
					}
				},
				"sources_nested": {
					"terms": {
						"field": "@target",
						"size": 20,
						"order": {
							"sources_targets": "desc"
						},
						"min_doc_count": 1
					},
					"aggs": {
						"sources_targets": {
						
							"avg": {
								"field": "@value"
							}
						}
					}
				}
			}
		}
	}
}
```

Sample data that is written with curl is:

```
      {
          "key" : "4507",
          "doc_count" : 120,
          "sources_nested" : {
            "doc_count_error_upper_bound" : -1,
            "sum_other_doc_count" : 100,
            "buckets" : [
              {
                "key" : "4506",
                "doc_count" : 1,
                "sources_targets" : {
                  "value" : 0.9067630767822266
                }
              }

              ....
              {
                "key" : "3870",
                "doc_count" : 1,
                "sources_targets" : {
                  "value" : 0.29410073161125183
                }
              }
            ]
          },
          "sources_aggs" : {
            "value" : 10.384261131286621
          }
        }
```

But when I add order by the sources_aggs, ES gives error:

```

	"aggs": {
		"sources": {
			"terms": {
				"field": "@source",
				"size": 20,
				"order": {
					"sources_aggs": "desc"
				},
				"min_doc_count": 1
			},
			"aggs": {
				"sources_aggs": {
					"sum_bucket":{
						 "buckets_path": "sources_nested>sources_targets"
					}
				},
				"sources_nested": {
					"terms": {
						"field": "@target",
						"size": 20,
						"order": {
							"sources_targets": "desc"
						},
						"min_doc_count": 1
					},
					"aggs": {
						"sources_targets": {
						
							"avg": {
								"field": "@value"
							}
						}
					}
				}
			}
		}
	}
}
```
The error I get is:

```
        "reason" : "Invalid term-aggregator order path [sources_aggs]. Unknown aggregation [sources_aggs]"
```

sources_aggs.value does not work too.

Should I add reverse_nested similar to this bug?  #16838 

It should not be necessary.

Could this be because the sum_bucket aggregation is calculated at the very end? I do not know the implementation details, just a guess

**Comment by colings86** [comment]
This is not a bug, you can only order the terms aggregation by a numeric metric aggregation. Pipeline aggregations like the `sum_bucket` aggregation cannot be used for terms aggregation order as mentioned in the documentation (https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-order). This is indeed because the pipeline aggregation are calculated only during the reduce phase on the coordinating node and so cannot be used to sort on the shards where each shard needs to return its top-N terms

**Comment by ali-bugdayci** [comment]
Yeah, as I noted since they are calculated at the very end. The thing is it is inside search-aggregations documentation. Hence I could not find it. 

It would be better if it was mentioned or linked to it inside pipeline aggregations documentation too:

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline.html
