### ISSUE TITLE
Whitelist ArrayList.ensureCapacity

### ISSUE THREAD

**Issue by buchanae** [elastic/elasticsearch#27295]
Using version 5.6. I have a nested array, e.g. 
```
data = {
  "logs": [
    {"msg": "hello world"}
  ]
}
```

I'd like to update this data using a painless script, and I'd like to handle the case where the next update wants to set `data.logs[params.index].msg = "log message"`. I'm oversimplifying the example here, but essentially I need to ensure the array is of a certain length before updating.

I'd like to use [ArrayList.ensureCapacity](https://docs.oracle.com/javase/7/docs/api/java/util/ArrayList.html#ensureCapacity%28int%29) to do that, but unfortunately it is not whitelisted.

I ended up using a for-loop as a workaround:
```
    for (; params.index > ctx._source.logs.length - 1; ) {
      Map m = new HashMap();
      ctx._source.logs.add(m);
    }
```

**Comment by DaveCTurner** [comment]
Hi @buchanae! We prefer to use Github issues only for bug reports and feature requests, and to keep support questions in the forums over on https://discuss.elastic.co where we can provide better support. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by jasontedor** [comment]
I think this is a feature request that `ArrayList#ensureCapacity` be whitelisted.

**Comment by DaveCTurner** [comment]
So it is. Sorry @buchanae, my bad.

**Comment by dakrone** [comment]
Is whitelisting `ArrayList#ensureCapacity` putting us at risk of `def a = new ArrayList<String>(); a.ensureCapacity(Integer.MAX_VALUE)`? Is that something we want to try and protect against anyway?

**Comment by jasontedor** [comment]
I don’t follow why ensure capacity is even needed, can you please elaborate on the use-case?

**Comment by buchanae** [comment]
> So it is. Sorry @buchanae, my bad.

It's my fault, I accidentally deleted the **Feature Request** header.

> def a = new ArrayList<String>(); a.ensureCapacity(Integer.MAX_VALUE)

I could write a for-loop to do the same thing, right?

> I don’t follow why ensure capacity is even needed, can you please elaborate on the use-case?

I'd like to use a painless script to set item 4 in an array that is currently of length 1. I'd like to do that with a single call to ensureCapacity instead of a for-loop.

**Comment by dakrone** [comment]
> I'd like to use a painless script to set item 4 in an array that is currently of length 1. I'd like to do that with a single call to ensureCapacity instead of a for-loop.

A call to `ensureCapacity` doesn't actually make there 4 elements, for example, this does not work:

```java
List<String> a = new ArrayList<>();
a.ensureCapacity(4);
a.set(3, "foo");  // will still throw an exception
```

**Comment by jasontedor** [comment]
@buchanae That does not do what you think it does, it changes the capacity but not the size and that's what you need to be able to insert at arbitrary positions like that. I think you will want to reconsider your plan if you need to insert at arbitrary positions like that not knowing up front the size the list should be. As it stands, I still do not see a use-case for this and I'm going to close this issue. I am happy to reopen if there's otherwise a good use-case.
