### ISSUE TITLE
When I deleted index, the disk space not release

### ISSUE THREAD

**Issue by forkforlearn** [elastic/elasticsearch#27307]
**Elasticsearch version5.4 

**Plugins installed**: ['x-pack',]

**JVM version** (`java -1.8`):

**OS version** (centos 6.5):

 1.create index by using "curl -u elastic -XPUT 'http://127.0.0.1:9200/indexnameismine_v1' -d'xxx'"
 2.create mapping by using  "curl  -u elastic  -XPUT 'http://127.0.0.1:9200/indexnameismine_v1/_mapping/mixdoc' -d'xxxxxx'"
 3.create index alias by using "curl -u elastic -XPOST localhost:9200/_aliases -d 'xxxxxxxx'"
 4.import data by using logstash 
 5.delete index by using "curl  -u elastic  -XDELETE 'localhost:9200/indexnameismine?pretty'"
but when i us 'du -h --max-depth=1' to check the data dir,i found the data space is not release,what should i do ,thank u

**Comment by DaveCTurner** [comment]
Hi @forkforlearn! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
