### ISSUE TITLE
uax_url_email tokenizer splits urls in multiple tokens

### ISSUE THREAD

**Issue by mellowonpsx** [elastic/elasticsearch#27309]
**Elasticsearch version**:
`/usr/local/elasticsearch/bin/elasticsearch --version`
Version: 5.5.2, Build: b2f0c09/2017-08-14T12:33:14.154Z, JVM: 1.8.0_144

**JVM version**:
`java -version`
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**OS version**:
`uname -a`
Linux 3.10.0-514.10.2.el7.x86_64 #1 SMP Mon Feb 20 02:37:52 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
the uax_url_email tokenizer splits urls in multiple tokens in presence of digits, ".", "-"
example of url => splits:
"webserver.domain.com" => "webserver.domain.com" [OK]
"webserver1.1domain.com" => "webserver1.1domain.com" [OK]
"webserver1.domain.com" => "webserver1", "domain.com" [WRONG]
"webserver.1domain.com" => "webserver", "1domain.com" [WRONG]
"webserver-root.domain.com" => "webserver", "root.domain.com" [WRONG]
"webserver-2.domain.com" => "webserver", "2", "domain.com" [WRONG]
"webserver-2.2domain.com" => "webserver", "2.2domain.com" [WRONG]

**Steps to reproduce**:
Kibana > Dev Tools > Console

example request:
```
POST _analyze
{"tokenizer": "uax_url_email","text": "webserver.1domain.com"}
```

example response:
```
{
  "tokens": [
    {
      "token": "webserver",
      "start_offset": 0,
      "end_offset": 9,
      "type": "<ALPHANUM>",
      "position": 0
    },
    {
      "token": "1domain.com",
      "start_offset": 10,
      "end_offset": 21,
      "type": "<ALPHANUM>",
      "position": 1
    }
  ]
}
```  

**Steps to reproduce command line**:
curl example request:
```bash
curl -XPOST "http://XXX:9200/_analyze" -H 'Content-Type: application/json' -d' {"tokenizer": "uax_url_email","text": ""webserver2.domain.com"}'
```
curl example response:
```json
{"tokens":[{"token":"webserver2","start_offset":0,"end_offset":10,"type":"<ALPHANUM>","position":0},{"token":"domain.com","start_offset":11,"end_offset":21,"type":"<ALPHANUM>","position":1}]}
```

**Comment by DaveCTurner** [comment]
The `uax_url_email` tokeniser tokenises URLs and email addresses, but in order to recognise a token as a URL it must include the scheme (usually `http://` or `https://`):

    $ curl http://localhost:9200/_analyze -XPOST --data-binary '{"tokenizer": "uax_url_email","text": "https://webserver.1domain.com"}' -H'Content-type: application/json'
    {"tokens":[{"token":"https://webserver.1domain.com","start_offset":0,"end_offset":29,"type":"<URL>","position":0}]}

**Comment by DaveCTurner** [comment]
Additionally, this tokeniser belongs to Lucene. Could you open this issue at https://lucene.apache.org/core/ instead?

**Comment by mellowonpsx** [comment]
FYI https://issues.apache.org/jira/browse/LUCENE-8044
