### ISSUE TITLE
access client ip address in the ingest pipeline

### ISSUE THREAD

**Issue by jpcarey** [elastic/elasticsearch#27312]
**Describe the feature**: It would be useful to have access to the client ip address that is submitting the POST to the ingest pipeline.

cc: @talevy

**Comment by clintongormley** [comment]
What's the use case for this?

**Comment by jpcarey** [comment]
Example: if you ran a website where the client side javascript was lazily uploading some usage / statistics, the client javascript would not have access to the public ip address without calling an external service to return that public ip to inject that into the document that would be uploaded to elasticsearch ingest node (for geoip lookup).

There are many external solutions to this problem, I just figured it would be useful to have access to this information for ingest processing. If proxies were frontending elasticsearch, you'd likely need to allow access to http header (except auth header) to allow selecting the appropriate X-forwarded header.

**Comment by markharwood** [comment]
>if you ran a website where the client side javascript was lazily uploading some usage / statistics

We discussed this on FixItFriday - I'm not sure this architecture is to be encouraged where elasticsearch is exposed directly to browser access. There should be more of a layered architecture with a server-side component that would be capable of adding client IP information to the source of the JSON documents sent to elasticsearch.

**Comment by alexeyst** [comment]
I would love to second the request, it's been used in the browser setup and accessing client IP would be great.

**Comment by khurram-aziz** [comment]
A layered architecture is better; no doubt; but it can be overkill for some entry level scenarios / implementations; for instance here when my API server is misbehaving; I want to log incident/errors into Elasticsearch cluster "directly" (given the API server is already not working as expected)

This is the least that should be done and is quite logical after HTTP module, its CORS settings and elasticsearch.js

**Comment by StingyJack** [comment]
It would be great to be able to automatically attach the client IP address to the document as a field
