### ISSUE TITLE
Normalizer doesn’t like trim filter

### ISSUE THREAD

**Issue by aslamy** [elastic/elasticsearch#27310]
When I use trim filter in normalizer I get this exception:

"type" : "illegal_argument_exception",
"reason" : "Custom normalizer [my_normalizer] may not use filter [trim]"

But it's fine to use the lowercase filter instead.

**Comment by jimczi** [comment]
The `trim` filter is not eligible for normalization. Not all filters can be used in this context but I agree that `trim` should be possible to use in a `normalizer`. I marked this issue as adoptme, would you like to work on a patch for this @aslamy ?

**Comment by ahlusar1989** [comment]
@jimczi I will be happy take this.

**Comment by jimczi** [comment]
Sure, go for it @ahlusar1989 !

**Comment by ahlusar1989** [comment]
Than you! Do you mind assigning this time me @jimczi ?

**Comment by jasontedor** [comment]
Sorry @ahlusar1989, we are unable to assign issues to members of the community that are not in the Elastic organization.

**Comment by ahlusar1989** [comment]
Thanks for clarifying @jasontedor. Thank you affording me the opportunity to work on this.

**Comment by jasontedor** [comment]
You're welcome, and thank you for your interest in contributing.

**Comment by orb** [comment]
This would be extremely useful.

**Comment by pentium10** [comment]
Custom normalizer [my_reverse_normalizer] may not use filter [reverse]
is this the same as this ticket?

**Comment by JoeZ99** [comment]
Length filter is also not allowed to be used as a filter in a normalizer definition. Any ideas of adding it??
