### ISSUE TITLE
unexpected analyzer's result 

### ISSUE THREAD

**Issue by sshling** [elastic/elasticsearch#27326]
**Elasticsearch version** (`bin/elasticsearch --version`):  2.1.2

**Plugins installed**: []

**GET _cat/plugins**
d_172.20.208.84:30000  delete-by-query              2.1.2                j  
d_172.20.208.84:30000  elasticsearch-analysis-ik    1.7.0                j  
d_172.20.208.84:30000  elasticsearch-analysis-mmseg 1.7.0                j  
d_172.20.208.84:30000  reindexing                   2.1.2                j  
d_172.20.208.84:30000  repository-hdfs              2.2.0.BUILD-SNAPSHOT j  

**JVM version** (`java -version`):  JDK 8

**OS version** (`uname -a` if on a Unix-like system):  centos

**Description of the problem including expected versus actual behavior**:

In general, as follows,the correct analyze result is unexpected .
To test , the same plugins installed using a single node, the result(analyze) is correct. 

Now it is on Production Environment, I do not know what the reason is not correct analyze results, the analyzer source code I am not familiar with, I think under certain conditions, will result in the plug-in is also installed by view(_cat/plugins), but the analysis result is not correct.

**Steps to reproduce**:
  
```
GET _analyze
{
  "analyzer" : "mmseg_maxword",
  "text" : "中华人民共和国"
}
```
response：
```
{
  "tokens": [
    {
      "end_offset": 1,
      "start_offset": 0,
      "position": 0,
      "type": "<IDEOGRAPHIC>",
      "token": "中"
    },
    {
      "end_offset": 2,
      "start_offset": 1,
      "position": 1,
      "type": "<IDEOGRAPHIC>",
      "token": "华"
    },
    {
      "end_offset": 3,
      "start_offset": 2,
      "position": 2,
      "type": "<IDEOGRAPHIC>",
      "token": "人"
    },
    {
      "end_offset": 4,
      "start_offset": 3,
      "position": 3,
      "type": "<IDEOGRAPHIC>",
      "token": "民"
    },
    {
      "end_offset": 5,
      "start_offset": 4,
      "position": 4,
      "type": "<IDEOGRAPHIC>",
      "token": "共"
    },
    {
      "end_offset": 6,
      "start_offset": 5,
      "position": 5,
      "type": "<IDEOGRAPHIC>",
      "token": "和"
    },
    {
      "end_offset": 7,
      "start_offset": 6,
      "position": 6,
      "type": "<IDEOGRAPHIC>",
      "token": "国"
    }
  ]
}
```

```
GET _analyze
{
  "analyzer" : "ik_max_word",
  "text" : "中华人民共和国"
}
```
response：
```
{
  "tokens": [
    {
      "end_offset": 1,
      "start_offset": 0,
      "position": 0,
      "type": "<IDEOGRAPHIC>",
      "token": "中"
    },
    {
      "end_offset": 2,
      "start_offset": 1,
      "position": 1,
      "type": "<IDEOGRAPHIC>",
      "token": "华"
    },
    {
      "end_offset": 3,
      "start_offset": 2,
      "position": 2,
      "type": "<IDEOGRAPHIC>",
      "token": "人"
    },
    {
      "end_offset": 4,
      "start_offset": 3,
      "position": 3,
      "type": "<IDEOGRAPHIC>",
      "token": "民"
    },
    {
      "end_offset": 5,
      "start_offset": 4,
      "position": 4,
      "type": "<IDEOGRAPHIC>",
      "token": "共"
    },
    {
      "end_offset": 6,
      "start_offset": 5,
      "position": 5,
      "type": "<IDEOGRAPHIC>",
      "token": "和"
    },
    {
      "end_offset": 7,
      "start_offset": 6,
      "position": 6,
      "type": "<IDEOGRAPHIC>",
      "token": "国"
    }
  ]
}
```

**Comment by johtani** [comment]
Duplicate https://github.com/elastic/elasticsearch/issues/16219
We fixed this 5.0, sorry.
You can get the correct response with index name before '_analyze'

**Comment by sshling** [comment]
Sorry, maybe I did not describe it clearly.
This unexpected result of the analysis, not always happen, such as restarting the cluster may be analysis resolved correctly.

As in the test environment, a node test analysis is correct, this analysis error is difficult to reproduce, so don't know how to solve, suspect some of the source code to determine the problem.

The following request still analysis unexpected:

```
GET pop_ware_new/_mapping
{
	...
    "mappings": {
      "ware": {
	      ...
		  "title": {
		    "analyzer": "mmseg_maxword",
		    "type": "string"
		  }
  ...
}
```

```
GET pop_ware_new/_analyze
{
  "analyzer" : "mmseg_maxword",
  "field" : "title",
  "text" : "中华人民共和国"
}
-----  Response: -----
{
  "tokens": [
    {
      "end_offset": 1,
      "start_offset": 0,
      "position": 0,
      "type": "<IDEOGRAPHIC>",
      "token": "中"
    },
    {
      "end_offset": 2,
      "start_offset": 1,
      "position": 1,
      "type": "<IDEOGRAPHIC>",
      "token": "华"
    },
    {
      "end_offset": 3,
      "start_offset": 2,
      "position": 2,
      "type": "<IDEOGRAPHIC>",
      "token": "人"
    },
    {
      "end_offset": 4,
      "start_offset": 3,
      "position": 3,
      "type": "<IDEOGRAPHIC>",
      "token": "民"
    },
    {
      "end_offset": 5,
      "start_offset": 4,
      "position": 4,
      "type": "<IDEOGRAPHIC>",
      "token": "共"
    },
    {
      "end_offset": 6,
      "start_offset": 5,
      "position": 5,
      "type": "<IDEOGRAPHIC>",
      "token": "和"
    },
    {
      "end_offset": 7,
      "start_offset": 6,
      "position": 6,
      "type": "<IDEOGRAPHIC>",
      "token": "国"
    }
  ]
}
```

**Comment by johtani** [comment]
Did you restart all elasticsearch nodes after installing analyzer plugins?

And next time, please ask this question first on our [discuss forum](https://discuss.elastic.co/c/elasticsearch) where we can provide better support.
Elastic uses GitHub issues for confirmed bugs and feature requests which have been discussed on the forums.
