### ISSUE TITLE
search for Aggregations in ES 5.6.0

### ISSUE THREAD

**Issue by gygesM** [elastic/elasticsearch#27327]
**Describe the feature**: I got a wrong result when i used my query.

**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0

**OS version** (`uname -a` if on a Unix-like system):  2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
![image](https://user-images.githubusercontent.com/11797588/32593915-dd1fd402-c564-11e7-8597-0ee3cb3a5698.png)

i use this method sent a  request to ES.  but i can't get the aggregations from it.please help me!!!!

here is my query,PS${timestamp_from} &   ${timestamp_to} are parameters needed i put in:

`{
      "size" : 0,
      "query":{
        "bool": {
          "must": [
            {
              "range": {
                "timestamp": {
                  "from":  ${timestamp_from},
                  "to":   ${timestamp_to},
                  "include_lower": true,
                  "include_upper": false
            }
          }
          }
          ]
        }},
      "aggs": {
        "max_timestamp": {
          "max": {
            "field": "timestamp"
          }
        }
      }
}`

**Provide logs (if relevant)**:
when i testing it ,i got this error message.
![image](https://user-images.githubusercontent.com/11797588/32594087-84e7dd92-c565-11e7-957d-fa22cb0ead80.png)

**Comment by colings86** [comment]
Hi @gygesM , we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. 

Additionally, both in Github issues and in the forum please don't post pictures of text, they are difficult to read and some people may not be even able to see them.

Thank you!

**Comment by gygesM** [comment]
OK，i understand. thanx,man
