### ISSUE TITLE
Highlighter doesn’t work with custom _all field and no_match_size 

### ISSUE THREAD

**Issue by aslamy** [elastic/elasticsearch#27331]
I have a custom _all fields (content), the values of multiple fields are copied into this field (content) .

mapping:

"content": {
"type": "text",
"store": true,
"term_vector": "with_positions_offsets",
}

In the case where there is a matching fragment to highlight, it returns a snippet of text. But In the case where there is no matching fragment to highlight, I want return a snippet of text from the beginning of the field. But it returns nothing.

Search:
"content": {
"fragment_size" : 150,
"number_of_fragments" : 2,
"no_match_size": 250,
"type": "fvh"
}
This happens when I copy more than one field to content. It works good when only one field is copied to content. I do not use any analyser.

**Comment by spinscale** [comment]
Please ask these kind of question in our [discussion forum](https://discuss.elastic.co/). We try to use github for issues only. Also it would be super helpful for anyone if you provide a full reproducible example over there, see [this post](https://www.elastic.co/help). Thank you!

**Comment by aslamy** [comment]
But this was a bug you closed.

**Comment by spinscale** [comment]
oh, i misread your post, then please provide a full reproducible example and I am happen to reopen
