### ISSUE TITLE
6x Documentation is Missing an important section on Multi Level  Parent Child Mappings

### ISSUE THREAD

**Issue by dougnelas** [elastic/elasticsearch#27336]
The 6.0 and 6.x documentation is missing an important part of the parent-child support regarding the join datatype.

https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html#_multiple_levels_of_parent_join

In 5.6 this is documented that the parent child join type supports multiple levels of parent-child.  This section is missing from the 6.x documentation which at first lead me to believe being able to map grandchild relationships would not be supported.  

https://www.elastic.co/guide/en/elasticsearch/reference/6.0/parent-join.html#_multiple_children_per_parent

Comparing the difference between the sections, it is pretty clear what is missing.

**Comment by jimczi** [comment]
@dougnelas this is intended. We don't want to document this anymore even though this is still supported internally. Running a query with a single level is already costly so more than one level should be avoided. Furthermore we don't have ideas to improve the situation so we want to slowly move away from this functionality and removing the documentation is a step toward this.

**Comment by thomoco** [comment]
Hi @jimczi - the join type looks like very useful functionality in 6.x. For our customers, having multiple levels of parent-child capability is really a critical functionality need. Yes, we all acknowledge that there are performance implication of this, but performance considerations are a cost-benefit decision. It's very important that we allow customers to have this flexibility. Even with multiple tiers of parent-child functionality, Elasticsearch is still far faster than most other products at performing these operations. I'd ask you to please reconsider documenting this - we have active users and customers using a data model requiring multiple levels of parent-child relationships. Thanks - cc: @eskibars for visibility

**Comment by clintongormley** [comment]
@jimczi I had a conversation with @colings86 about this the other day.  I think we need to leave the documentation in there, but add a warning about performance and explain that trying to replicate a relational model with multiple level hierarchies is not the correct way to model your data in ES.

**Comment by jimczi** [comment]
Fair enough. I opened https://github.com/elastic/elasticsearch/pull/27392 to restore the section with a big warning ;)
