### ISSUE TITLE
Sharding and Slicing in Spark read from elasticsearch

### ISSUE THREAD

**Issue by gayatrijay02** [elastic/elasticsearch#27341]
I want to introduce sharding and slicing while reading from  Elasticsearch through SPARK. Please suggest or give me any code snippet. 

Thanks
Gayatri Gupta

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
