### ISSUE TITLE
`must not exist` doesn't work on the second level of nested query

### ISSUE THREAD

**Issue by llRandom** [elastic/elasticsearch#27343]
**Elasticsearch version** (`bin/elasticsearch --version`): 2.4.3

**Plugins installed**: [delete-by-query]

**JVM version** (`java -version`): 1.8.0_151-b12

**OS version** (`uname -a` if on a Unix-like system): Windows 10 x64

**Description of the problem including expected versus actual behavior**:
When I use `exists` query inside `must not` on a second level of `nested` query (nested inside nested) it doesn't match documents that has no sub-nested documents. If I remove `must_not`, it works fine.

**Steps to reproduce**:

 1. create index
```
PUT http://localhost:9200/sample
{
    "mappings": {
        "root": {
            "properties": {
                "id": {
                    "type": "integer"
                },
                "secondLvl": {
                    "type": "nested",
                    "properties": {
                        "thirdLvl": {
                            "type": "nested",
                            "properties": {
                                "name": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```
 2. insert entites
```
POST http://localhost:9200/sample/_bulk
{"index":{"_type":"root","_id":"1"}}
{"id":1,"secondLvl":[{"thirdLvl":[{"name":"test"}]}]}
{"index":{"_type":"root","_id":"2"}}
{"id":2,"secondLvl":[{}]}
```
 3. search
```
POST http://localhost:9200/sample/root/_search
{
    "query": {
        "nested": {
            "query": {
                "nested": {
                    "query": {
                        "bool": {
                            "must_not": [
                                {
                                    "exists": {
                                        "field": "secondLvl.thirdLvl"
                                    }
                                }
                            ]
                        }
                    },
                    "path": "secondLvl.thirdLvl"
                }
            },
            "path": "secondLvl"
        }
    }
}
```
Expected to match the second document. Actual - no results.
If I search without `must_not` query, it works fine, the first document matches. But the opposite query returns nothing instead of the second document.

**Comment by dadoonet** [comment]
I believe this is expected as `secondLvl.thirdLvl` is not a field. But `secondLvl.thirdLvl.name` is.

You should try with:

```name
{
  "exists": {
    "field": "secondLvl.thirdLvl.name"
  }
}
```

I think it's better to discuss that problem on discuss.elastic.co so please reopen there if you need more help.

**Comment by dadoonet** [comment]
Reopening. Might be a real issue. Sorry

**Comment by jimczi** [comment]
The `exists` query handles object field so it's not the issue here. The problem is that a nested query can only match documents that appear at the same level. In your example the second document does not have a value for that level so it cannot match even if it's a `must_not` query because it does not have any fields that appear at that level. I'd not call it a bug but rather a limitation of how nested queries work. @martijnvg  do you agree ?

**Comment by dnhatn** [comment]
A query with `match_all` (as the most inner clause) returns [doc1].

```
POST sample/root/_search
{
  "query": {
    "nested": {
      "query": {
        "nested": {
          "query": {
            "match_all": {}
          },
          "path": "secondLvl.thirdLvl"
        }
      },
      "path": "secondLvl"
    }
  }
}
```

A query with `must` (as the most inner clause) returns [doc1]

```
POST sample/root/_search
{
  "query": {
    "nested": {
      "query": {
        "nested": {
          "query": {
            "bool": {
              "must": [
                {
                  "exists": {
                    "field": "secondLvl.thirdLvl.name"
                  }
                }
              ]
            }
          },
          "path": "secondLvl.thirdLvl"
        }
      },
      "path": "secondLvl"
    }
  }
}
```

It's logical to expect `must_not` as the complement of `must`, thus we should expect a query with `must_not` (as the most inner clause)  return no result (eg. all documents returned in `match_all` but not in `must` ~ no result).

**Comment by llRandom** [comment]
I think I understand an example with `match_all`, 'must` and `must_not` but why it works different if I have 1 level of nested entities instead of 2?

**Comment by martijnvg** [comment]
@jimczi @llRandom Yes, that is a limitation of the nested query. The bool query with must_not doesn't even get evaluated because there are no nested objects on the third level.

I think there are two workarounds for this:
* Add an empty third level in the second document like this:

```
PUT /sample/root/2
{"id":2,"secondLvl":[{"thirdLvl":[{}]}]}
``` 

* Or change the query so that on the second level you add a bool query with two should clauses, one containing your original nested query for the third level and another should clause with a bool query with must not that queries for all second level documents that do not have a third level field:

```
POST http://localhost:9200/sample/root/_search
{
  "query": {
    "nested": {
      "query": {
        "bool": {
          "should": [
            {
              "nested": {
                "query": {
                  "bool": {
                    "must_not": [
                      {
                        "exists": {
                          "field": "secondLvl.thirdLvl"
                        }
                      }
                    ]
                  }
                },
                "path": "secondLvl.thirdLvl"
              }
            },
            {
              "bool": {
                "must_not": [
                  {
                    "nested": {
                      "path": "secondLvl.thirdLvl",
                      "query": {
                        "match_all": {}
                      }
                    }
                  }
                ]
              }
            }
          ]
        }
      },
      "path": "secondLvl"
    }
  }
}
```

**Comment by llRandom** [comment]
Thank you, `must_not match_all` did the trick, sorry for false issue!
