### ISSUE TITLE
number_of_pending_tasks gradually increase,

### ISSUE THREAD

**Issue by qicaihuoyan** [elastic/elasticsearch#27357]
cluster.name: elk-****
node.name: "es-1"
node.master: true
node.data: true
network.host: 0.0.0.0
transport.tcp.port: 9300
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["*********:9300","*********::9300","*********::9300"]
cluster.routing.allocation.node_initial_primaries_recoveries: 50
cluster.routing.allocation.node_concurrent_recoveries: 50
cluster.routing.allocation.cluster_concurrent_rebalance: 0
indices.recovery.max_bytes_per_sec: 500mb
indices.recovery.concurrent_streams: 50
discovery.zen.ping.timeout: 60s
discovery.zen.join_timeout: 60s
discovery.zen.fd.ping_timeout: 60s
discovery.zen.fd.ping_retries: 5
discovery.zen.publish_timeout: 60s
transport.tcp.connect_timeout: 60s
----------------------------------------------------
cluster.name: elk-****
node.name: "es-2"
node.master: false
node.data: true
network.host: 0.0.0.0
transport.tcp.port: 9300
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: "*********:9300","*********::9300","*********::9300"]
cluster.routing.allocation.node_initial_primaries_recoveries: 50
cluster.routing.allocation.node_concurrent_recoveries: 50
cluster.routing.allocation.cluster_concurrent_rebalance: 0
indices.recovery.max_bytes_per_sec: 500mb
indices.recovery.concurrent_streams: 50
discovery.zen.ping.timeout: 60s
discovery.zen.join_timeout: 60s
discovery.zen.fd.ping_timeout: 60s
discovery.zen.fd.ping_retries: 5
discovery.zen.publish_timeout: 60s
transport.tcp.connect_timeout: 60s

---------------------------------------------------
{
  "cluster_name" : "elk-****",
  "status" : "red",
  "timed_out" : false,
  "number_of_nodes" : 3,
  "number_of_data_nodes" : 3,
  "active_primary_shards" : 17349,
  "active_shards" : 22286,
  "relocating_shards" : 0,
  "initializing_shards" : 15,
  "unassigned_shards" : 12463,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 62628,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 8855432,
  "active_shards_percent_as_number" : 64.10654700264642
}
--------------------------------
number_of_pending_tasks gradually increase,There is no downward trend, the log does not have any error message, what is the problem?

**Comment by qicaihuoyan** [comment]
One master,Three node
Elasticsearch version:2.3.1

**Comment by DaveCTurner** [comment]
Hi @qicaihuoyan! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
