### ISSUE TITLE
Add helper methods to LeafSearchScript for easier access of doc field values

### ISSUE THREAD

**Issue by Koc** [elastic/elasticsearch#27356]
Native scripting was much easier than new Script Engines. We could extend `AbstractDoubleSearchScript` and call chain like `((ScriptDocValues.Doubles) doc().get(field)).getValue()` or even just `docFieldDoubles(field).getValue()` for getting field values.

With Script Engines I cann't get doc values. `context.reader().getNumericDocValues(field)` always returns `null`.  I should rewrite my custom scoring with Script Engines for getting ready to furter updates, but I cann't.

Please port `doc()` method to `LeafSearchScript` or describe inside documentation https://www.elastic.co/guide/en/elasticsearch/reference/5.5/modules-scripting-engine.html how to get doc field values.

**Comment by rjernst** [comment]
In 6.0+, `SearchScript` has `getDoc()`.

> context.reader().getNumericDocValues(field) always returns null

Then your field does not have numeric doc values (or it doesn't exist). 

In the future, please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports.

**Comment by Koc** [comment]
To be honest - this is feature request for adding method to class or upgrading documentation :).

> Then your field does not have numeric doc values (or it doesn't exist).

But why `docFieldDoubles(field).getValue()` returns values for same field?
