### ISSUE TITLE
Elasticsearch Cluster health status changed from YELLOW to RED,while creating index with template using bulk api

### ISSUE THREAD

**Issue by sunnywalden** [elastic/elasticsearch#27368]
once I input the data form logstash(version 5.6),elasticsearch reports error like this:
[2017-11-14T00:04:01,227][INFO ][o.e.c.m.MetaDataCreateIndexService] [node-1] [c-channelclick-2017.11.11] creating index, cause [auto(bulk api)], templates [joy], shards [5]/[1], mappings [logs]
[2017-11-14T00:04:01,230][INFO ][o.e.c.r.a.AllocationService] [node-1] Cluster health status changed from [YELLOW] to [RED] (reason: [index [c-channelclick-2017.11.11] created]).

**Elasticsearch version:
5.6 

**Plugins installed**: []
repository-hdfs
**JVM version** (`java -version`):
1.8.0_45
**OS version** (`uname -a` if on a Unix-like system):
CentOS Linux release 7.3.1611
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.create the template 
[elk@elk templates]$ curl -XPUT "http://10.61.8.15:9200/_template/joy?pretty"
{
  "joy" : {
    "order" : 0,
    "template" : "*",
    "settings" : {
      "index" : {
        "number_of_shards" : "5",
        "number_of_replicas" : "1"
      }
    },
    "mappings" : {
      "logs" : {
        "properties" : {
          "sourceId" : {
            "type" : "long"
          },
          "callAdvTime" : {
            "norms" : false,
            "type" : "text",
            "fields" : {
              "keyword" : {
                "ignore_above" : 256,
                "type" : "keyword"
              }
            }
          },
          "orderId" : {
            "type" : "long"
          },
          "channelType" : {
            "norms" : false,
            "type" : "text",
            "fields" : {
              "keyword" : {
                "ignore_above" : 256,
                "type" : "keyword"
              }
            }
          },
          "source" : {
            "norms" : false,
            "type" : "text",
            "fields" : {
              "keyword" : {
                "ignore_above" : 256,
                "type" : "keyword"
              }
            }
          },
          "uuid" : {
            "norms" : false,
            "type" : "text",
            "fields" : {
              "keyword" : {
                "ignore_above" : 256,
                "type" : "keyword"
              }
            }
          },
          "from_ip" : {
            "type" : "ip"
          },
          "delMode" : {
            "norms" : false,
            "type" : "text",
            "fields" : {
              "keyword" : {
                "ignore_above" : 256,
                "type" : "keyword"
              }
            }
          },
          "log_type" : {
            "norms" : false,
            "type" : "text",
            "fields" : {
              "keyword" : {
                "ignore_above" : 256,
                "type" : "keyword"
              }
            }
          },
          "repeatTime" : {
            "type" : "long"
          },
          "@version" : {
            "type" : "keyword"
          },
          "host" : {
            "norms" : false,
            "type" : "text",
            "fields" : {
              "keyword" : {
                "ignore_above" : 256,
                "type" : "keyword"
              }
            }
          },
          "client_ip" : {
            "type" : "ip"
          },
          "logger_name" : {
            "norms" : false,
            "type" : "text",
            "fields" : {
              "keyword" : {
                "ignore_above" : 256,
                "type" : "keyword"
              }
            }
          },
          "scid" : {
            "norms" : false,
            "type" : "text",
            "fields" : {
              "keyword" : {
                "ignore_above" : 256,
                "type" : "keyword"
              }
            }
          },
          "responseMsg" : {
            "norms" : false,
            "type" : "text",
            "fields" : {
              "keyword" : {
                "ignore_above" : 256,
                "type" : "keyword"
              }
            }
          },
          "level" : {
            "norms" : false,
            "type" : "text",
            "fields" : {
              "keyword" : {
                "ignore_above" : 256,
                "type" : "keyword"
              }
            }
          },
          "channelTime" : {
            "norms" : false,
            "type" : "text",
            "fields" : {
              "keyword" : {
                "ignore_above" : 256,
                "type" : "keyword"
              }
            }
          },
          "advId" : {
            "type" : "long"
          },
          "message" : {
            "norms" : false,
            "type" : "text"
          },
          "callAdvUrl" : {
            "norms" : false,
            "type" : "text"
          },
          "tags" : {
            "norms" : false,
            "type" : "text"
          },
          "@timestamp" : {
            "type" : "date"
          },
          "port" : {
            "type" : "long"
          },
          "level_value" : {
            "type" : "long"
          },
          "thread_name" : {
            "norms" : false,
            "type" : "text",
            "fields" : {
              "keyword" : {
                "ignore_above" : 256,
                "type" : "keyword"
              }
            }
          },
          "appid" : {
            "norms" : false,
            "type" : "text",
            "fields" : {
              "keyword" : {
                "ignore_above" : 256,
                "type" : "keyword"
              }
            }
          },
          "proId" : {
            "type" : "long"
          },
          "callChannelUrl" : {
            "norms" : false,
            "type" : "text"
          },
          "delPlat" : {
            "norms" : false,
            "type" : "text",
            "fields" : {
              "keyword" : {
                "ignore_above" : 256,
                "type" : "keyword"
              }
            }
          },
          "status" : {
            "type" : "long"
          }
        }
      }
    },
    "aliases" : { }
  }
}

 2.config logstash read data from tcp 9250 and output them into elasticsearch considering log_type and channelType as conditions.My logstash config file like this: 

input {
  tcp {
    host => "10.61.8.15"
    port => 9250
    mode => "server"
    tags => ["tags"]
    codec => json_lines
  }

}

output {
 stdout{codec =>rubydebug}
  if [channelType] == "A" {
    if [log_type] == "ChannelClick" {
      elasticsearch {
      hosts => ["10.61.8.15:9200"]
      index => "a-channelclick-%{+YYYY.MM.dd}"
      manage_template => false
      template_name => "joy"
      }
    }
    ........

      }

 3.put the data into logstash
 cat test.log
{"sourceId":28,"callAdvTime":"2017-11-10 12:30:34.100","orderId":9,"channelType":"C","source":"mex","landingPageId":null,"uuid":"B7AEBFCC-2ED8-41CD-922B-1168EF9C7B88","from_ip":"127.0.0.1","delMode":"CPA","log_type":"ChannelClick","repeatTime":0,"click_time":null,"@version":1,"host":"10.61.8.3","client_ip":"127.0.0.1","logger_name":"net.jcmob.joyplus.agent.service.impl.ChannelClickServiceImpl","scid":"jcdefault","responseMsg":"yes","level":"INFO","channelTime":"2017-11-09 16:30:33.344","advId":20,"message":"ChannelClick","callAdvUrl":"http://ac.o2.qq.com/php/mbclick.php?sign=report&gid=107424&media=9654&channel=10024426&sch_id=858&create_id=103&loc_id=7352_d900fd66ef4df6f377c5a316fb0e38ce&time=1510216233&ifa=B7AEBFCC-2ED8-41CD-922B-1168EF9C7B88&adsf=jcdefault&cip=127.0.0.1&callback=http%3A%2F%2F127.0.0.1%3A8081%2Fjoyplus%2Fcallback%3Fuuid%3DB7AEBFCC-2ED8-41CD-922B-1168EF9C7B88%26appid%3D1180004118%26joyClick%3D1BVZRP22U8LYL6GOUI6MGP067MX5HSIMUQT32FQUUEYQX4A4CKJJ09865QYEDMLRXV9999LVSFXK4FPRVK3LFO8XSRGXT0FEQA5TRV5S27I1DPBFT3W6Z9C4HLKXA8G8F3SAIZ5CC0WKKR0Q23L1W0QW1R4D6W4WY1MDQR3L012M9QSO97XBMWE317WI78GBB7BTMFUTPJZJ0LKOIWZN6UGLQB4DWX6K3T37KJMCUQJ8PKJMCZVOUE88YFUUO4EW9GLLEM6MZ9GLWA0CAGIK6RTCT1WJC26OVKCVX48WLLZQLDBO7WU3DN2SJXGA2DE294A4OQZ968FLSV61C9EMWXJBPWLDAOK56CNZ6WR6LP7JVJXQH","tags":["tags","tags"],"@timestamp":"2017-11-10T22:30:34.307Z","port":54894,"thread_name":"MvcAsync1","level_value":20000,"appid":"1180004118","proId":20,"callChannelUrl":"sdfsdfsdfds","delPlat":"ios","status":201,"cid":null}
[elk@elk templates]$  nc 10.61.8.15 9250 < test.log
4.then, you'll probabaly get the error the same as me

**Provide logs (if relevant)**:

**Comment by martijnvg** [comment]
@sunnywalden The logs you're referring to are info logs, not error logs. Primary shards are created before replica shards and indexing can handle the fact that replicas become available after the primary shards. There is nothing to worry about here. Please ask questions like this on the [forum](https://discuss.elastic.co/).
