### ISSUE TITLE
backslash regexp searches not working on keyword analyzed data

### ISSUE THREAD

**Issue by oldenbur** [elastic/elasticsearch#27385]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.5.1

**Plugins installed**: []

**JVM version** (`java -version`): java version "1.8.0_144"

**OS version** (`uname -a` if on a Unix-like system): Linux lrdx0000 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: keyword-analyzed strings with backslashes don't appear in the results for regexp searches which seem as though they should match.  See https://discuss.elastic.co/t/windows-path-backslash-rich-regexp-not-working/105275

**Steps to reproduce**:
```
PUT regexp-test
{ 
  "settings" : { 
    "index" : {
      "number_of_shards" : 1, 
      "number_of_replicas" : 0
    }
  },
  "mappings": {
    "doc": {
      "properties": {
        "path": { 
          "type": "keyword"
        }
      }
    }
  }
}

PUT regexp-test/doc/1/_create
{
    "path" : "\\\\*\\c$",
    "post_date" : "2017-10-23T09:00:00"
}
PUT regexp-test/doc/2/_create
{
    "path" : "\\\\*\\d$",
    "post_date" : "2017-10-23T09:05:00"
}

# this does not match anything, although I expect it to since it should match both
# of the above logs
GET regexp-test/_search
{ 
  "query": { "regexp": { "path": "\\\\\\\\.*\\\\" } } 
}
```

**Comment by jimczi** [comment]
The pattern used by the `regexp` query is always anchored:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html#_standard_operators
This means that the pattern must match the entire string. Adding `.*` at the end of the pattern returns the correct document.
