### ISSUE TITLE
Reindex Helper fails on .watches and .triggered_watches without license for service

### ISSUE THREAD

**Issue by andytsnowden** [elastic/elasticsearch#27389]
**Elasticsearch version**: 5.6.3

**Plugins installed**: x-pack

**JVM version**: 1.8.0_151

**OS version** : Ubuntu 17.10, Kernel  4.10.0-38-generic

**Description of the problem including expected versus actual behavior**:

When attempting to use the Reindex Helper in 5.6.3 in preparation for 6.0.0 I am unable to reindex the .watches and .triggered_watches indexes.  My license does not allow access to watches in X-pack so I get a error message stating "current license is non-compliant for [watcher]".  If I attempt to delete the index directly I am told "This endpoint is not supported for DELETE on .watches index."

**Steps to reproduce**:
 1. Open "Reindex Helper" in Kibana
 2. Refresh Indices
 3. Reindex .triggered_watches or .watches

**Provide logs (if relevant)**:

When attempting to reindex:
`{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "Task failed.",
  "type": "security_exception",
  "reason": "current license is non-compliant for [watcher]",
  "license.expired.feature": "watcher",
  "code": "ERR_TASK_FAILED",
  "taskId": "fPwIzkKwRVCtqa1DZkHfVA:233134327"
}`

**Comment by tvernum** [comment]
Hi @andytsnowden 

We try to keep this repository exclusively for open source elasticsearch, and don't track issues relating to our commerical products here.

Would you be able to raise your issue on our [discussion forum](https://discuss.elastic.co/c/x-pack) instead?
When you do, can you provide more details about your troubles deleting `.watches`? That shouldn't happen, so an reproducible example would be really helpful.

Thank you.

**Comment by zyb1994** [comment]
Hi  bro , I also met this problem ,Did you finally solve it?
