### ISSUE TITLE
Reindex Big Index

### ISSUE THREAD

**Issue by EngNahidBehjati** [elastic/elasticsearch#27383]
**Elasticsearch 5.5.1** (`bin/elasticsearch --5.5.1`):

Hi!
I have a problem with reindex.
for almost big index, reindex request has "search context not fount " exception and there is no way I can increase "scroll" parameter to avoid this.

thanks

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
