### ISSUE TITLE
Need to define two children under a same parent and having query on it.

### ISSUE THREAD

**Issue by AliCharper** [elastic/elasticsearch#27394]
Hi,

I really need to write a query for a scenario like this to have all the data in the parent and child with just a single query. It seems writing a query when we have more than one child under a single parent is not that easy or possible.

```
POST /test/grandparent/_search?pretty
{
  "query": 
  {
    "has_child": 
    {
      "type": "parent",
      "query": 
      {
        "has_child": 
        {
          "type": "child",
          "query": 
          {            
            "match_all": {}
          },
           "inner_hits": {}
        }
      },
           "inner_hits": {}
    }
  }
}
```
if I had a secondchild type, I can not add it beside the child in the query. I have written the whole mapping below.

```
PUT /test
{
  "mappings": {
    "grandparent": {},
    "parent": {
      "_parent": {
        "type": "grandparent" 
      }
    },
    "child": {
      "_parent": {
        "type": "parent" 
      }
    }
    ,
    "secondchild": {
      "_parent": {
        "type": "parent" 
      }
  }
  }
}
```

**Comment by martijnvg** [comment]
Please ask questions like this one on the [forum](https://discuss.elastic.co/). You should be able the add a second `has_child` query by using a `bool` query. Github issues are only reserved for bugs and feature requests.
