### ISSUE TITLE
Keeping local modified elasticsearch.yml on dpkg upgrade causes ES start to fail

### ISSUE THREAD

**Issue by slovdahl** [elastic/elasticsearch#27393]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.0.0

**Plugins installed**: []

**JVM version** (`java -version`): OpenJDK 1.8.0_151

**OS version** (`uname -a` if on a Unix-like system): Linux desk 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
During the upgrade from ES 5.6.1 to 6.0 with the `deb` package, dpkg asked if I wanted to keep my local `elasticsearch.yml`, or replace it with the updated default one. I chose to retain my local one (containing only two extra rows in the end of the file, a custom `cluster.name` and `network.host`).

After the upgrade, I tried to manually restart ES. But it refused to start, because it tried to create log files in `/usr/share/elasticsearch/`, and not `/var/log/elasticsearch/` as previously.

Copying the updated `path.logs` setting from the new default `elasticsearch.yml` and starting ES again fixes the problem, but this seems lika a very intrusive change to me, and I think it's going to cause a lot of pain for users upgrading their ES nodes to 6.0.0.

**Steps to reproduce**:

 1. Download and install ES 5.x.
 2. Modify `/etc/elasticsearch/elasticsearch.yml`
 3. Download and upgrade to ES 6.0.0.
 4. Choose to retain the local version of `/etc/elasticsearch/elasticsearch.yml`
 5. Restart ES, it won't start.

**Provide logs (if relevant)**:
[es-upgrade.log](https://github.com/elastic/elasticsearch/files/1474553/es-upgrade.log)
[es-startup.log](https://github.com/elastic/elasticsearch/files/1474551/es-startup.log)

**Comment by jasontedor** [comment]
I am sorry that you experienced trouble but this is covered in the [breaking changes for 6.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_packaging_changes.html#_default_path_settings_are_removed). Additionally, it's a good practice to compare differences in package-shipped configuration files when the installation presents to you that there are differences.
