### ISSUE TITLE
how to use native scrip to filter result

### ISSUE THREAD

**Issue by MengPhantom** [elastic/elasticsearch#27390]
I want filter search result use local python script ,but it not works well.maybe  native script use java is a good choice. but  how can I do this,I only find some alter score script demo. help  me plz!!

**Comment by cbuescher** [comment]
Hi @MengPhantom! Your question is better suited to the user forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by MengPhantom** [comment]
thankyou
