### ISSUE TITLE
missing licence information in Maven artefacts

### ISSUE THREAD

**Issue by mirabilos** [elastic/elasticsearch#27403]
The `elasticsearch-2.4.6-sources.jar` file from Maven refers to “the NOTICE file distributed with this work” but there is none. It’s also missing from the `elasticsearch-2.4.6.jar` file where ASF projects commonly place it, as usually, only the binary is distributed.

The licence body itself is *also* missing from either file.

**Comment by jasontedor** [comment]
Sorry about this. You can obtain the license and the notice from the [repository](https://github.com/elastic/elasticsearch/tree/v2.4.6). For 5.0 and later this is fixed, the license and notice are distributed in the JARs. We are not making any releases from 2.4 so we are not going to fix this there. Given this, I am going to close this issue.
