### ISSUE TITLE
cluster.routing.allocation.disk.watermark.flood_stage not updateable through cluster api

### ISSUE THREAD

**Issue by abraxxa** [elastic/elasticsearch#27406]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.0.0, Build: 8f0685b/2017-11-10T18:41:22.859Z, JVM: 1.8.0_131

**Plugins installed**: [x-pack]

**JVM version** (`java -version`):
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux tsa-tc-es-1 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
According to https://www.elastic.co/guide/en/elasticsearch/reference/6.0/disk-allocator.html you can set cluster.routing.allocation.disk.watermark.flood_stage by using the cluster api. This works for the low and high watermarks but not the flood_stage. Also neither for the persistent nor the transient setting.

**Steps to reproduce**:

```
# curl -Ss -H 'Content-Type: application/json' -XPUT 'http://localhost:9200/_cluster/settings' -d '{"transient": {"cluster.routing.allocation.disk.watermark.flood_stage":"2gb", "cluster.routing.allocation.disk.watermark.low": "10gb", "cluster.routing.allocation.disk.watermark.high": "5gb"}}'
```

**Provide logs (if relevant)**:

```
{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[hostname][1.2.3.4:9300][cluster:admin/settings/update]"}],"type":"illegal_argument_exception","reason":"transient setting [cluster.routing.allocation.disk.watermark.flood_stage], not dynamically updateable"},"status":400}
```

**Comment by s1monw** [comment]
I just downloaded 6.0.0 and ran the command, this is the result:

```JSON
{"acknowledged":true,"persistent":{},"transient":{"cluster":{"routing":{"allocation":{"disk":{"watermark":{"low":"10gb","flood_stage":"2gb","high":"5gb"}}}}}}}
```

is it possible that you have a 5.6 node in your cluster?

**Comment by jasontedor** [comment]
This does not reproduce, I even copy and pasted your `curl` command:

```
$ curl -Ss -H 'Content-Type: application/json' -XPUT 'http://localhost:9200/_cluster/settings' -d '{"transient": {"cluster.routing.allocation.disk.watermark.flood_stage":"2gb", "cluster.routing.allocation.disk.watermark.low": "10gb", "cluster.routing.allocation.disk.watermark.high": "5gb"}}'
{"acknowledged":true,"persistent":{},"transient":{"cluster":{"routing":{"allocation":{"disk":{"watermark":{"low":"10gb","flood_stage":"2gb","high":"5gb"}}}}}}}
```

From the server logs:

```
[2017-11-15T16:11:54,947][INFO ][o.e.c.s.ClusterSettings  ] [xI5KBgc] updating [cluster.routing.allocation.disk.watermark.low] from [85%] to [10gb]
[2017-11-15T16:11:54,947][INFO ][o.e.c.s.ClusterSettings  ] [xI5KBgc] updating [cluster.routing.allocation.disk.watermark.high] from [90%] to [5gb]
[2017-11-15T16:11:54,948][INFO ][o.e.c.s.ClusterSettings  ] [xI5KBgc] updating [cluster.routing.allocation.disk.watermark.flood_stage] from [95%] to [2gb]
```

As such, I would like to see your server logs here (not only the response as you've shared here).

**Comment by abraxxa** [comment]
@s1monw yes I still have 5.6.3 nodes in the cluster as I'm in the process of upgrading using a rolling upgrade. Now that the 6.0.0 node is the master node the command did indeed work and I don't have to set it in elasticsearch.yml.
When should persistent be used and when transient? The docs don't mention that.
Thanks!

**Comment by jasontedor** [comment]
Closing as there is no bug. Persistent is for permanent setting changes, transient is for ones you only want to the next restart.

**Comment by abraxxa** [comment]
Thanks for clarification. Please add the 'until the next restart' to the docs.

**Comment by jasontedor** [comment]
@abraxxa The docs say:

>Settings updated can either be persistent (applied cross restarts) or transient (will not survive a full cluster restart).
