### ISSUE TITLE
X-Pack Audit Trail logs cannot further specified

### ISSUE THREAD

**Issue by fluency03** [elastic/elasticsearch#27410]
**Describe the feature**: 

When we enable X-Pack's Audit Trail as following: 

```
xpack.security.audit:
  enabled: true
  outputs: [index, logfile]
```

What we would like to monitor are mainly two things;
- the login actions
- the actions performed by the *real actual* users, instead of also having `Kibana`, `logstash` and other NPA users.

However, in the audit logs, there are full of these logs from `principle` -  `Kibana` and other NPA users.  Because of there are too many of such logs ( `Kibana` is basically doing this every several seconds for healthcheck), it takes lots of disk space, and more importantly, we cannot have a clear picture about what the real human users have done. 

This lack-of-feature is also described here by Guy Shilo: http://www.idata.co.il/2017/03/securing-elasticsearch-cluster-part-3-auditing/.  He provided a temporary solution which is to configure the `log4j.properties` file of x-pack, by adding regex filtering.  But this is only a temporary solution, and regex expression we have to define really depending on log style of elastic.  This makes our development process not flexible. 

**Elasticsearch version**: 5.6.2
**JVM version**: 1.8.0_141
**OS version**: Red Hat x86_64

**Comment by jasontedor** [comment]
This issue is for open source Elasticsearch only while you're referring to closed source X-Pack. For this, please use the X-Pack category on the [forum](https://discuss.elastic.co).

**Comment by JPLachance** [comment]
Now than X-Pack is open source, can we re-open this issue? In our environment, those audit logs can grow up to 100Go per day and 99.9996% of that is generated by service accounts. Being able to filter out Kibana and Logstash users would help a lot.

If that discussion already occurred somewhere else, feel free to re-direct me 😄
