### ISSUE TITLE
cat API help is broken when url parameters are specified

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#27424]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.0.0

**Description of the problem including expected versus actual behavior**:

When the cat API is used on APIs that support URL parameters like index names, then calling those endpoints with `&h` to get help results in an error

**Steps to reproduce**:

```
# works
GET _cat/shards?help
GET _cat/shards/test
# returns an exception
GET _cat/shards/test?help
```

**Comment by jyoti0208** [comment]
I would like to work on this.

**Comment by olcbean** [comment]
hey @spinscale 
I would like to have a go at this. I figured I will ask before doing the work, as the issue does not have an `adoptme` tag.
Thanks!

**Comment by olcbean** [comment]
@jyoti0208 oh crap! I just now saw your earlier comment ( browser did not refresh properly ). Sorry for jumping up the queue :)

**Comment by spinscale** [comment]
feel free to go ahead! Thanks a lot for working on this!

**Comment by zachdyer** [comment]
I'm getting some broken cat urls when i use 

`http://thecatapi.com/api/images/get?format=xml&results_per_page=20`

**Comment by jasontedor** [comment]
This was explored in #27598 and I do not think that there is much that we [should](https://github.com/elastic/elasticsearch/pull/27598#pullrequestreview-80061309) do here. The behavior would be odd if the index does not exist, or odd if there are unrecognized parameters in the request (do we ignore them? do we throw 404s? do we fail on the unrecognized parameters?). I think we should leave this as-is.

**Comment by olcbean** [comment]
@jasontedor what about adding a short note in the docs that `help` should not be used with any other url params?

**Comment by jasontedor** [comment]
@olcbean That would be good.
