### ISSUE TITLE
URL Ingestor 

### ISSUE THREAD

**Issue by JRRan64** [elastic/elasticsearch#27446]
URL Ingestor to parse a URL into Protocol, Domain, Reverse Domain, Port, Path Parameters  Willing to take my first shot at Open Source Contributing if this does not already exist.   I've done it in SQL already

**Comment by cbuescher** [comment]
@JRRan64 thanks for opening this feature request.This might be something you could do with the existing [Grok Processor](https://www.elastic.co/guide/en/elasticsearch/reference/master/grok-processor.html)? If no, what part is missing?

**Comment by JRRan64** [comment]
Fantastic, can close. Grok Processor's URI pattern is 95% of what we need.  For other Grok newbies like me To see URI in action, And for a Grok resource.. ! grokdebug.herokuapp.com, enter a uri with protocol://domain:port/path?p1=xyz.&p2=1234
