### ISSUE TITLE
Performance when using `time_zone` in date_historgram

### ISSUE THREAD

**Issue by orweinberger** [elastic/elasticsearch#27449]
Running Elasticsearch 5.2.0 on Ubuntu with Kibana, single node, single index of 12m documents (4gb).

I'm experiencing a weird performance issue when using date histograms with the `time_zone` attribute.

The following query takes about 4 seconds to complete:

```
POST index-2017.11.16/_search
{
  "size": 500,
  "sort": [
    {
      "@timestamp": {
        "order": "desc",
        "unmapped_type": "boolean"
      }
    }
  ],
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "analyze_wildcard": true,
            "query": "*"
          }
        },
        {
          "range": {
            "@timestamp": {
              "gte": 1510783200000,
              "lte": 1510869599999,
              "format": "epoch_millis"
            }
          }
        }
      ],
      "must_not": []
    }
  },
  "_source": {
    "excludes": []
  },
  "aggs": {
    "2": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "30m",
        "time_zone": "Asia/Amman",
        "min_doc_count": 1
      }
    }
  },
  "stored_fields": [
    "*"
  ],
  "script_fields": {},
  "docvalue_fields": []
}
```

If I remove the `time_zone` attribute, it takes less than a second. On a different environment which has 8 data nodes and 1.5TB index, the above query takes 7 seconds to complete and about 1 second when removing the `time_zone` attribute.

**Comment by colings86** [comment]
@cbuescher any idea why the timezone might be causing this performance degradation?

**Comment by jpountz** [comment]
Slow downs when specifying a time zone are to be expected, especially in time zones that implement daylight saving time, as it makes the identification of the right bucket for a given date more complex.
