### ISSUE TITLE
In Kibana 5.2.1, the autocomplete does not work for the "exists" keyword.

### ISSUE THREAD

**Issue by jamesDrinkard** [elastic/elasticsearch#27458]
**Elasticsearch version** (`bin/elasticsearch --5.2.1`):

**Plugins installed**: []

**JVM version** (`java -1.8`):

**OS version** (` RHEL 6.9):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1.  Login to Kibana.
 2. Go to DEV Tools.
 3. Start working on a query and try to use the exists keyword.  All the other keywords have autocomplete working, except this one.

**Comment by jasontedor** [comment]
This should be opened against [elastic/kibana](https://github.com/elastic/kibana) as the dev tools are managed from that repository.
