### ISSUE TITLE
Add a soft limit for the number of buckets created by extended_bounds

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#27452]
At the moment there are no safeguards against creating histogram and date_histogram requests that produce a huge number of buckets on the reduce node because the number of empty buckets required by extended bounds is extremely high (see https://github.com/elastic/elasticsearch/issues/27447 for an example).

We should add a soft limit that ensures that the number of buckets required by the combination of the interval and the extended bounds does not cross a threshold and cause GCs/destabilise the cluster. I suggest we set this limit to 1,000.

**Comment by s1monw** [comment]
Sounds good to me
