### ISSUE TITLE
Terms aggregation with nested Boolean field does not work

### ISSUE THREAD

**Issue by revitalbarletz** [elastic/elasticsearch#27463]
with ES version 1.7 I have created the following index with the following mapping:
GET http://localhost:9200/ds1_fqvwhdrtbw/_mapping HTTP/1.1
User-Agent: Fiddler
Host: localhost:9200
Content-Length: 0

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 775

{"ds1_fqvwhdrtbw":
{"mappings":{
"docs":{"_all":{"enabled":false},
"properties":{
"a$author$c":{
"properties":{
"a$subCount$c":{"type":"integer","index":"no","doc_values":true},
"a$subFlagged$c":{"type":"boolean","index":"no"},
"a$subFlaggedCollection$c":{"type":"boolean","index":"no"}}},
"a$key$s":{"type":"string","index_analyzer":"suggestionsix","search_analyzer":"suggestionsq"},
"author":{"properties":{
"subCount":{"type":"integer","copy_to":["a$author$c.a$subCount$c"]},
"subFlagged":{"type":"boolean","copy_to":["a$author$c.a$subFlagged$c"]},
"subFlaggedCollection":{"type":"boolean","copy_to":["a$author$c.a$subFlaggedCollection$c"]}}},
"flagged":{"type":"boolean"},"key":{"type":"string","index":"not_analyzed","fields":{"$smf":{"type":"string","index_options":"offsets"}}}
}}}}}

When running the following query with terms aggregation "
{"query":{"match_all":{}},"from":0,"size":51,"_source":["key","flagged","author"],"aggregations":{"author/subFlagged":{"terms":{"field":"a$author$c.a$subFlagged$c"}}}}

I get 0 buckets even though there is one document with true value.
When I run exactly the same setup only this time with ES 5, I get the below mapping with 1 bucket for the same aggregation query:

HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 728

{"ds1_fvviamjfkp":
{"mappings":{
"docs":{"_all":{"enabled":false},
"properties":{
"a$author$c":{
"properties":{
"a$subCount$c":{"type":"integer","index":false},
"a$subFlagged$c":{"type":"boolean","index":false},
"a$subFlaggedCollection$c":{"type":"boolean","index":false}}},"
a$key$s":{"type":"text","analyzer":"suggestionsix","search_analyzer":"suggestionsq"},
"author":{"properties":{
"subCount":{"type":"integer","copy_to":["a$author$c.a$subCount$c"]},
"subFlagged":{"type":"boolean","copy_to":["a$author$c.a$subFlagged$c"]},
"subFlaggedCollection":{"type":"boolean","copy_to":["a$author$c.a$subFlaggedCollection$c"]}}},
"flagged":{"type":"boolean"},"key":{"type":"keyword","fields":{"$smf":{"type":"text","index_options":"offsets"}}}}}}}}

**Comment by jpountz** [comment]
If I read you correctly, 1.7 had a bug which is now fixed in 5.x, so there is not much to do?

**Comment by colings86** [comment]
I agree that there is nothing to do here since the bug is fixed in 5.x+. Closing this issue
