### ISSUE TITLE
ec2-discovery plugin document is not accurate.

### ISSUE THREAD

**Issue by m15o** [elastic/elasticsearch#27464]
**Elasticsearch version**: 6.0.0

**Plugins installed**: ec2-discovery

**Description of the problem including expected versus actual behavior**:

> [ec2 service endpoint to connect to. This will be automatically figured out by the ec2 client based on the instance location, but can be specified explicitly](https://github.com/elastic/elasticsearch/blob/6.0/docs/plugins/discovery-ec2.asciidoc
)
The document states ec2 service endpoint is automatically figured out by ec2 client, but I need to set the endpoint to make the plugin work. 

This document is correct if the plugin uses AmazonEC2ClientBuilder to build AmazonEC2Client instance. But AmazonEC2Client is created directly, so the endpoint is set to default endpoint, "https://ec2.us-east-1.amazonaws.com."

Related https://github.com/elastic/elasticsearch/issues/25619

**Comment by jpountz** [comment]
cc @dadoonet

**Comment by NeckBeardPrince** [comment]
@m15o @dadoonet 
Actually it's a bit worse than that.
If you set `discovery.ec2.endpoint: us-west-1` it tries to connect to a invalid endpoint.
The default of `us-east-1` does not do this.
I had to hard set the endpoint to `discovery.ec2.endpoint: ec2.us-west-1.amazonaws.com`

```
Connection request: [route: {s}->https://us-west:443][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
```

**Comment by dadoonet** [comment]
@NeckBeardPrince this is expected. The doc says that the end should be one of those: http://docs.aws.amazon.com/general/latest/gr/rande.html#ec2_region

**Comment by sihil** [comment]
Yep, this is a pretty painful experience as it is misleading. Sadly just spent a couple of hours trying to figure out why my eu-west-1 instances were not doing discovery after upgrading and came across this whilst trying to figure out how to specify a region. Definitely keen on #27924 to bring behaviour into line with the documentation.

**Comment by debadair** [comment]
Until  #27924 happens, let's document that it actually defaults to ec2.us-east-1.amazonaws.com.

**Comment by dadoonet** [comment]
@debadair yeah. This is what https://github.com/elastic/elasticsearch/pull/27925 actually brings as well.

**Comment by bnm22** [comment]
+1

**Comment by karl-tpio** [comment]
Just wanted to say that i also just got bit by this one.
https://discuss.elastic.co/t/discovery-ec2-plugin-always-tries-to-ping-localhost/160433/4
