### ISSUE TITLE
Keyset pagination feature request

### ISSUE THREAD

**Issue by hayahyts** [elastic/elasticsearch#27471]
**Describe the feature**:
Guys I've been reading some concept which already exist but seem not to be known by a lot of people. 
This is known by some as **Seed Method** or **Keyset Pagination** on this blog
[Keyset pagination by Markus Winand](http://use-the-index-luke.com/no-offset).

So I thought It'll be a great feature in ElasticSearch
Regards.

**Comment by jpountz** [comment]
Offsets raise issues indeed, but not the one that this blog post mentions since Elasticsearch is pretty different from SQL databases. We already have the `search_after` feature as a way to perform "offset-less pagination".
