### ISSUE TITLE
Elasticsearch disk threshold decider

### ISSUE THREAD

**Issue by hanbj** [elastic/elasticsearch#27479]
The problems that we have encountered in producing clusters:
Due to the large amount of data, there are several nodes in the production disk utilization rate is more than 90%, check the ES log discovery:
High disk watermark [90%] exceeded on [XR6DsFmbQk267g3UFpbQCw][Sage] free: 17.9gb[4.8%], shards will be relocated away from this node, but through the df -h to see, soon disk usage dropped, so guess:
1, the disk usage is more than 90%, es will fragment to other nodes, but the migration, I'm sure that after the migration is completed to delete the local slice data directory, disk space can not be released so fast
2, ES deletes the fragment of the node by script, and copies the copy of another fragment to other nodes
3, may achieve disk warning situation is segment in the merger, es will stop merging, delete the merge process of the intermediate file

Which God knows this detail, thank you.

**Comment by jasontedor** [comment]
I think that you're asking a question here rather that reporting a bug. Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by hanbj** [comment]
Ok, Thanks.
