### ISSUE TITLE
Search with scroll parameter allows to exceed max_result_window

### ISSUE THREAD

**Issue by Alexxfrolov** [elastic/elasticsearch#27475]
**Elasticsearch version** (2.4.0):

**JVM version** (1.8.0_121):

**Description of the problem including expected versus actual behavior**:
parameter `max_result_window `  is ignored when  search query with scroll parameter is performed.
Here is link to the question on stackoverflow:
https://stackoverflow.com/questions/47332789/search-with-scroll-parameter-allows-to-exceed-max-result-window
**Steps to reproduce**:
 1. `curl -XPUT "http://localhost:9200/index_name/_settings" -d '{ "max_result_window" : 10000 }'`
 2. 
```
curl -XGET 'localhost:9200/index_name/_search?scroll=0m&pretty' -d'
{
    "from" : 0, "size" : 100000
}
'
```

**Comment by jimczi** [comment]
Thanks @Alexxfrolov 
This is already fixed by #19367 for v5
