### ISSUE TITLE
Searching with java.util.Date

### ISSUE THREAD

**Issue by ojusti** [elastic/elasticsearch#27477]
1. With the default mapping, Elasticsearch accepts java.util.Date as field values but not as query filters.
While indexing ES systematically transforms java.util.Date to long and back to some joda's date. While searching, ES calls Date.toString and then tries to use the field format and obviously fails.

2. Even if the field's format is modified to java.util.Date.toString's format "EEE MMM dd HH:mm:ss zzz yyyy" (with uppercase Z because of joda), some queries may still fail because toString method cuts away the millisecond part ( try someDate < someDate+1ms)

To reproduce 1/ execute the attached junit test with 6.0.0 or 5.6.4. The issue does not exist on older versions (2.x).
[DateSearchTest.java.txt](https://github.com/elastic/elasticsearch/files/1491454/DateSearchTest.java.txt)

<dependency>
 <groupId>org.elasticsearch</groupId>
 <artifactId>elasticsearch</artifactId>
 <version>6.0.0</version>
</dependency>
<dependency>
 <groupId>org.elasticsearch.plugin</groupId>
 <artifactId>transport-netty4-client</artifactId>
 <version>6.0.0</version>
</dependency>

java version "1.8.0_74"
windows 10

Obtained error:
[stacktrace.txt](https://github.com/elastic/elasticsearch/files/1491458/stacktrace.txt)

**Comment by cbuescher** [comment]
@ojusti thanks for raising this issue, this looks like a dupilcate of https://github.com/elastic/elasticsearch/issues/23014 to me. Can you please check if the linked issue really adresses the problem you face an then close this issue, otherwise please let us know what is missing in #23014

**Comment by ojusti** [comment]
Duplicate of #23014.
