### ISSUE TITLE
bin/elasticsearch-plugin list should display default message if no plugins are installed

### ISSUE THREAD

**Issue by dedemorton** [elastic/elasticsearch#27487]
Elasticsearch should display a message if you run `bin/elasticsearch-plugin list` and no plugins are installed. The message should say something like: "There are no plugins installed".

New users (especially those who are familiar with Logstash) might run the command before installing plugins to see if any plugins are installed by default.

**Comment by dadoonet** [comment]
I think this is on purpose: See #8563
I can't find the PR that changed the behavior though.

**Comment by jasontedor** [comment]
This is indeed intentional and I don’t think we are going to make any changes here.
