### ISSUE TITLE
"Dirty" data of other shards kept on disk after rerouting

### ISSUE THREAD

**Issue by hgfischer** [elastic/elasticsearch#27491]
**Elasticsearch version** (`bin/elasticsearch --version`): `Version: 2.4.3, Build: d38a34e/2016-12-07T16:28:56Z, JVM: 1.8.0_144`

**Plugins installed**: []

**JVM version** (`java -version`):
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
```
Linux els01 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
``` 

**Description of the problem including expected versus actual behavior**:

I removed 2 nodes from the cluster, using cluster shard allocation exclusion lists, to move shards away before turning them off, to do hardware maintenance. After the maintenance both nodes were added at different times with same name and IPs to the cluster, and the cluster shard allocation exclusion lists were cleaned up to allow shards to move in back again.

After some time reallocating data, one of the rebuilt nodes had too much disk used (~85%) while most of the other nodes are bellow (65%). Then after inspecting the data directory I found lots of data from shards that were not allocated on that node.

I could not find the reason of why the node is keeping dirty data there that does not belong to that node.

**Steps to reproduce**:

I am not sure if the following procedure can help reproduce it, but this is more or less what describes the steps that led to the problem:

 1. On a average sized cluster, with 100s of indices with 12 shards, and some billions of documents.
 2. Decommission 2 nodes using cluster shard allocation exclusion list
 3. Add a new node with same hostname and IP address
 4. Allow the node to join and the shard allocation to "finish"
 5. Add the second node
 6. Check disk usage

**Provide logs (if relevant)**:

Don't know what to look for, since the whole "shard reallocation" was trusted enough to not have anyone watching. In the next day I found that the node was with the unusual high disk usage.

**Side quest**:

Apart from reporting the issue, I would like to know what I can do to cleanup the dirty data, without having to rebuild that node. Is there a script that does that? If not, I can write one, but I need to know what and were should I look for, to know what can be deleted.

**Comment by ywelsch** [comment]
Please ask questions like this on our [discuss forums](https://discuss.elastic.co). Shard data is only deleted once that shard is fully allocated. If the health for the shard is green, then all extra copies will be deleted.

**Comment by hgfischer** [comment]
I already used the discuss forum about this same issue, but that place is near dead.
And I am not just asking questions. This was a problem report, that could lead to a bug fix.

BTW cluster was green when this happened.

**Comment by hgfischer** [comment]
Additional info. The cluster was already green. Adding 2 new nodes to the cluster, made it rebalance and it cleaned up dirty data from the node that was using too much disk space.

**Comment by markwalkom** [comment]
> I already used the discuss forum about this same issue, but that place is near dead.

Do you mean https://discuss.elastic.co/t/unbalanced-disk-usage-with-es-2-4-x/108591/? If so then we don't provide SLAs on either Discuss or GitHub issues, and a day hadn't even passed before you raised it here.

While I appreciate this may be urgent for you, we do ask that you have patience as the forums are actually pretty busy, despite no one immediately answering your thread :)

**Comment by hgfischer** [comment]
I wrote that because I have posted many other times there, and rarely have answers.
