### ISSUE TITLE
Unable to start elasticsearch service

### ISSUE THREAD

**Issue by sitilge** [elastic/elasticsearch#27499]
Running `arch 4.13.12`, `elasticsearch Version: 6.0.0, Build: 8f0685b/2017-11-10T18:41:22.859Z, JVM: 1.8.0_144`

I am unable to `# systemctl start elasticsearch`

> elasticsearch.service: PID file /run/elasticsearch/elasticsearch.pid not readable (yet?) after start: No such file or directory

What is the workaround?

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and support and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by jasontedor** [comment]
If you open a topic on the forum, please feel free to link to it from here.
