### ISSUE TITLE
[CI] VersionUtilsTests#testGradleVersionsMatchVersionUtils failure.

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#27497]
```
REPRODUCE WITH: gradle :test:framework:test -Dtests.seed=B5B94250EA246462 -Dtests.class=org.elasticsearch.test.VersionUtilsTests -Dtests.method="testGradleVersionsMatchVersionUtils" -Dtests.security.manager=true -Dtests.locale=sr-CS -Dtests.timezone=Asia/Jakarta
FAILURE 0.11s | VersionUtilsTests.testGradleVersionsMatchVersionUtils <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<[6.0.0, 6.0.1, 6.1.0, 6.2.0]> but was:<[6.0.0, 6.0.1]>
   >    at __randomizedtesting.SeedInfo.seed([B5B94250EA246462:607A5855273429AC]:0)
   >    at org.elasticsearch.test.VersionUtilsTests.testGradleVersionsMatchVersionUtils(VersionUtilsTests.java:280)
   >    at java.lang.Thread.run(Thread.java:748)
```

This reproduces, but I don't know how to fix this. 

The `VersionUtils.allReleasedVersions()` doesn't include 6.0.1 version, but `tests.gradle_index_compat_versions` list of versions does contain it. (based on `indexCompatVersions` variable in gradle). I think what `VersionUtils.allReleasedVersions()` is returning is correct, 6.0.1 has not been released yet, but this is not inline with `indexCompatVersions`.

**Comment by DaveCTurner** [comment]
Deeply related to #27397.

`indexCompatVersions` is what we test for index-compatibility against. Should we test `master` vs `6.0.1-SNAPSHOT`? I think yes, until we're sure we're not going to release `6.0.1` (i.e. on release of `6.2.0`.

**Comment by DaveCTurner** [comment]
Thanks @martijnvg, you beat me to it!
