### ISSUE TITLE
VersionCollection does not support a 7.x branch

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#27509]
At the moment, `VersionCollection` contains a special case for the `6.x` branch only. This means that `gradle check` will start to fail when the `7.x` branch is created because the `rolling-upgrade` and `full-cluster-restart` tests will try and check out a branch called `7.0` instead of `7.x`.

The same sort of thing will go wrong if the `6.x` branch is removed.

It's not clear how to fix this and may not become clear until we get closer to the time.

https://github.com/elastic/elasticsearch/blob/89ba8996c6c735fa6fa0bca1a5cf4268b5daf07e/buildSrc/src/main/groovy/org/elasticsearch/gradle/VersionCollection.groovy#L81

**Comment by hub-cap** [comment]
I suspect we can close this now since the version numbers have been removed from bwc. Thoughts @DaveCTurner @rjernst ?

**Comment by DaveCTurner** [comment]
Yes, I agree.
