### ISSUE TITLE
Improving the layout of multiple callouts

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#27501]
Reported by @alanjames1987 [here](https://twitter.com/AlanJames1987/status/933548484300562432).

On [this page of the docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/analysis-custom-analyzer.html) we have a config;
<img width="581" alt="screen shot 2017-11-23 at 15 22 07" src="https://user-images.githubusercontent.com/3184718/33158929-39717c9e-d062-11e7-9b5b-1d9f93cf3215.png">

And the 6 blue dots are highlighted and explained below;
<img width="819" alt="screen shot 2017-11-23 at 15 21 52" src="https://user-images.githubusercontent.com/3184718/33158940-4d7d18ec-d062-11e7-8019-04dcd7f755ab.png">

What's not really clear to readers is that the 6 dots (known as `callouts`) are all related to that same text definition.

Is this an asciidoc implementation issue, or can we improve this layout?

**Comment by jasontedor** [comment]
@markwalkom I think this should be an issue on [elastic/docs](https://github.com/elastic/docs)?

**Comment by markwalkom** [comment]
All my previous docs issues have been raised here, I'm open to moving it if that's the best place for this more-meta issue though :)

**Comment by jasontedor** [comment]
I think docs issues that are specific to content in this repository are good here, yet this one feels more like a meta-issue (as you say) that could impact any of our docs.

**Comment by markwalkom** [comment]
https://github.com/elastic/docs/issues/265
