### ISSUE TITLE
Total Cluster Document Count VS Total Documents Per Node Count Mismatch

### ISSUE THREAD

**Issue by SKumarMN** [elastic/elasticsearch#27502]
Elasticsearch Version 5.4.1
JDK: 1.8.131

The total number of documents I get when i do _cluster/stats is not matching with the total number of documents of all the nodes put together as shown in _nodes/stats API. Below is the snapshot which shows the difference . I have 3 node cluster. The doc count shown in cluster API matches the primary document count of all the indices obtained by _cat/indices API. I have few indices with replicas too. As Far as I knew doc count includes both the primaries and replicas. 

![doc](https://user-images.githubusercontent.com/2056311/33167461-9ec59994-d063-11e7-9269-8ad2050dd09c.jpg)

**Comment by albertzaharovits** [comment]
> As Far as I knew doc count includes both the primaries and replicas.

Docs count from replicas are not counted.

Docs count is very similar. Most likely an automatic [refresh](https://www.elastic.co/guide/en/elasticsearch/reference/5.4/indices-refresh.html) triggered on some of the shards in between the `_cluster/stats` and `_nodes/stats` operations (which are asynchronous and composite).


Please first visit the [forum](https://discuss.elastic.co/c/elasticsearch) for questions. We try to keep github for issues only. For example you should make sure indexing is disabled (by making the index [read-only](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html)), then issue a `_refresh` and run the stats commands. If then they differ, then it might be an issue worth of github :)

**Comment by SKumarMN** [comment]
@albertzaharovits 
Thanks for your reply. When I took the snap, I had made sure there wasn't any indexing happening and I saw the same stats for hours together. Hence raised it an issue here.  
I did manually invoke _refresh and when i execute the stats command i still same results. 
Cluster doc count matches the  sum of all the primaries obtained via _cat/indices api.  sum of doc count obtained using _node/stats is not matching sum of all the primaries obtained via _cat/indices api or Cluster doc count obtained using _cluster/stats API. 
The issue is clearly reproducible. Can you please recheck this issue at you side too.

Every index is made read only and _refresh is manually called
`catalog: {
settings: {
index: {
mapping: {
total_fields: {
limit: "2000"
}
},
refresh_interval: "10s",
number_of_shards: "5",
**blocks: {
read_only: "true"**
}`

**Comment by albertzaharovits** [comment]
@SKumarMN 
You are right, the two metrics do differ.
`_cluster/stats` and `_cat/indices` return stats from lucene internals.
`_node/stats` and `my_index/_count` return documents from the ES perspective, by doing a search.
The two values can be different if, for example, there are nested documents; Nested documents are counted by lucene but not by ES.
