### ISSUE TITLE
Limit the number of analyzed tokens during highlighting

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#27517]
Limit the number of analyzed tokens during highlighting.
The maximum number is be 10K, and could be modified through an index setting.
If the limit is exceeded, return a flag that highlights are returned with partial results

This limit does **NOT**  apply if documents used postings, indexed with offsets or term vectors.

relates to #27038
depending on the implementation approach, can be a duplicate of #26515

**Comment by mayya-sharipova** [comment]
@jimczi  What if instead of number of analyzed tokens, we will limit the length of the text to be analyzed?
Both `org.apache.lucene.search.highlight.Highlighter` (used in Elastic `PlainHighlighter`), and `org.apache.lucene.search.uhighlight.UnifiedHighlighter` (used in Elastic `CustomUnifiedHighlighter`) already have this limit implemented:

1. `org.apache.lucene.search.highlight.Highlighter` has  `maxDocCharsToAnalyze` (50* 1024 by default)
2.  `org.apache.lucene.search.uhighlight.UnifiedHighlighter` has `maxLength` (10000 by default)

We can also have a default maximum value of  **10000**.  If a user needs to analyze a larger text, he/she can set this value per request. Example:

```json
curl -XGET 'localhost:9200/my_index/_search?pretty' -H 'Content-Type: application/json' -d'
{
  "query": {
    "match": {
      "text": "fox"
    }
  },
  "highlight": {
    "max_length" : 50000,
    "fields": {
      "text": {} 
    }
  }
}
'
```


The advantage of this approach:

1.  Easier implementation as these limits already implemented in the Lucene classes
2.  No much changes in the user API  (only addition of an extra parameter)

**Otherwise**, If we want to go with our initial plan to limit the number of tokens and a flag  in the response to indicate that the highlighting response for this hit is partial, this will require a lot of changes in the response. For example in the current format of the reply as below, it is not clear where the put this partial flag if not the whole text was analyzed.

```json
"hits" : {
    "total" : 1,
    "max_score" : 0.39556286,
    "hits" : [
      {
        "_index" : "my_index2",
        "_type" : "my_type",
        "_id" : "1",
        "_score" : 0.39556286,
        "_source" : {
          "text" : "brown fox",
          "text2" : "Fast brown fox and slow brown fox"
        },
        "highlight" : {
          "text2" : [
            "Fast brown <em>fox</em> and slow brown <em>fox</em>"
          ],
          "text" : [
            "brown <em>fox</em>"
          ]
        }
      }
    ]
  }
```

**Comment by jimczi** [comment]
I am ok with `max_length` being the maximum number of chars to analyze but only if it splits on tokens boundary. That's what the `plain` highlighter does with the `LimitTokenOffsetFilter` but the `unified` simply truncates the input.
Regarding the flag to indicate that the highlight response is partial, I don't think it is needed since the option is explicitly set on the request ? 
The `plain` highlighter is a bit special since it caches all tokens during the analysis which is why it can consumes a lot of memory on big texts. The `unified` behaves differently and does not need to cache anything so highlighting a big field is just slow. I think it's important to have ways to speed up things so I am +1 to add a new option even if we probably have too many options for highlighters already ;).

**Comment by mayya-sharipova** [comment]
Echoing Jim's comment from #26515 here: `maxLength` parameter  (limit on the field size to be analyzed)  is only necessary for the **plain highlighter**; as only this highlighter will keep all tokens for the field in the memory. In contrast, the unified highlighter  keeps in memory only field tokens corresponding to the query.

Points for discussion:
1. Since plain highlighter is not default anymore, do we really need to introduce `maxLength` for it?
2. If we decide to introduce `maxLength` for the plain highlighter, should it be set up:
   * as an indexSetting?
   * or as a part of the search request?

    ```json
   curl my_index/_search 
   {
     "query": {
       "match": {
         "text": "fox"
       }
     },
     "highlight": {
       "max_length" : 50000,
       "fields": {
         "text": {} 
       }
     }
   }
   ```

**Comment by mayya-sharipova** [comment]
As discussed in the Search & Aggs meeting, we will set an index level limit on the number of analyzed tokens during highlighting, and will fail a request if it exceeds this limit
