### ISSUE TITLE
[CI] Vagrant tests fail with logging error

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#27521]
See eg. https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/2175/console.

```
not ok 69 [TAR PLUGINS] install jvm-example with different logging modes and check output
not ok 69 [TAR PLUGINS] install jvm-example with different logging modes and check output
```

This started failing after core-cli was made its own module #27114, so it might be related? cc @hub-cap

**Comment by jasontedor** [comment]
I think there is a bad bug here and this is a blocker for 6.1.0.

**Comment by jpountz** [comment]
OK, I added labels.

**Comment by jasontedor** [comment]
I opened #27523.
