### ISSUE TITLE
[CI] TruncateTranslogIT#testCorruptTranslogTruncation fails

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#27538]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/365/console.

```
 TruncateTranslogIT.testCorruptTranslogTruncation <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: all shards should be failed due to a corrupted translog
   > 	at __randomizedtesting.SeedInfo.seed([BE82146795DBD816:2A70E3779E1B3BE]:0)
   > 	at org.elasticsearch.index.translog.TruncateTranslogIT.testCorruptTranslogTruncation(TruncateTranslogIT.java:171)
   > 	at java.lang.Thread.run(Thread.java:748)
  1> [2017-11-27T13:32:12,883][INFO ][o.e.n.Node               ] [node_s0] stopping ...
  1> [2017-11-27T13:32:12,884][INFO ][o.e.n.Node               ] [node_s0] stopped
  1> [2017-11-27T13:32:12,884][INFO ][o.e.n.Node               ] [node_s0] closing ...
  1> [2017-11-27T13:32:12,887][INFO ][o.e.n.Node               ] [node_s0] closed
```

Unable to reproduce locally:

```
 gradle :core:integTest \
  -Dtests.seed=BE82146795DBD816 \
  -Dtests.class=org.elasticsearch.index.translog.TruncateTranslogIT \
  -Dtests.method="testCorruptTranslogTruncation" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-ME \
  -Dtests.timezone=Africa/Khartoum
```

Log: [consoleText.txt](https://github.com/elastic/elasticsearch/files/1505971/consoleText.txt)

**Comment by dnhatn** [comment]
Another failure https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=oraclelinux/375/console

**Comment by dnhatn** [comment]
Another https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/5327/console

**Comment by dnhatn** [comment]
Another instance https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=amazon/1802/console

Log: [corrupt.txt](https://github.com/elastic/elasticsearch/files/1568173/corrupt.txt)

**Comment by DaveCTurner** [comment]
Another one: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/877/console

**Comment by DaveCTurner** [comment]
I muted this in 96e09187a9 (on 6.x)
