### ISSUE TITLE
Multi Index Phrase Suggestions return only suggestions from single index 

### ISSUE THREAD

**Issue by psytraxx** [elastic/elasticsearch#27539]
**Elasticsearch version**  5.5.3

**Plugins installed**:  none

**JVM version** standard docker image

**OS version** standard docker image

**Description of the problem including expected versus actual behavior**:

Setup multiple indicies using a commonly shared field used for phrase suggestions 

Expected result:

suggestions are returned based on data in each index.

Actual result.

only suggestions from one index are returned

**Steps to reproduce**:

setup a indexed property with a trigram field based on the example on the elastic website
(we use nest)

mapping field

                        .Text(t => t
                            .Name("searchName")
                            .Analyzer(GetLocalizedAnalyzerName("name", languageId))
                            .Fields(f => f.Text(x => x.Name("trigram").Analyzer("trigram"))))

we then use a  search template which contains the following code for the suggestion

 ```
"suggest": {
	  "text": "{{search}}",
	  "brand": {
		"phrase": {
		  "field": "searchName",
		  "size": 1,
		  "gram_size": 1,
		  "direct_generator": [
			{
			  "field": "searchName.trigram",
			  "suggest_mode": "always"
			}
		  ],
		"highlight": {
		  "pre_tag": "<em>",
		  "post_tag": "</em>"
		}{{#portalId}},
		  "collate": {
			"query": {
			  "inline": {
				"bool": {
				  "must": [
					{
					  "term": {
						"suggestionContext": "{{portalId}}_brand"
					  }
					}
				  ]
				}
			  }
			},
			"params": {
			  "portalId": {{portalId}}
			}
		  }{{/portalId}}
		}
	  },
```

we do a templat query in the form of 

 var indexName = clientService.GetSearchIndexNameWildcard(); // returns something like shopsearch_9_*

            var templateName = clientService.GetEnterSearchTemplateName();

            var searchTemplateRequest = CreateSearchTemplateRequest(
                searchParameters,
                indexName: indexName,
                templateName: templateName,
                searchString: searchString);
            
            var elasticClient = clientService.GetElasticClient();

            return elasticClient.SearchTemplateAsync<VoidResponse>(searchTemplateRequest, cancellationToken);

**Comment by jimczi** [comment]
Suggestions are built per shard and the best ones are kept on the coordinating node. 
With a `size` of 1 in the phrase suggester options only the best suggestion among the shards is returned so it is normal that this suggestion comes from a single index (a shard in this index to be more precise). Try with a different size and you should see suggestions coming from other shards/index. 
I hope you don't mind if I close this issue, we have a forum that is better suited for this kind of questions:
https://discuss.elastic.co/c/elasticsearch

**Comment by Zyklop** [comment]
Thank you for your answer. @jimczi 
We tried with your solution and set the size = 10000. If I run the suggest query on one index, I get 10 correct results. For two indices, I get just one result for the other index and loose the 10 that I got on the first index. For queries with more then two indices, no suggestions are returned, no matter what size I use.

**Comment by jimczi** [comment]
That's probably due to the confidence level of your suggest query. By default the phrase suggester will only return suggestions that score higher than the input phrase. The score of the input phase is computed per shard so the filtering depends on the max score given by a shard for the input phrase.  If one shard contains the input phrase with a high frequency then it is expected that all other suggestions are going to be filtered. You can lower the confidence level and set `confidence:0` for instance but this will impact the precision.
