### ISSUE TITLE
HTTP Security Header Not Detected Vulnerability

### ISSUE THREAD

**Issue by rmgarg22** [elastic/elasticsearch#27532]
Our vulnerability scanning tool, the absence of the following HTTP headers X-Frame-Options, X-XSS-Protection, X-Content-Type-Options has been reported. Can this be included in the upcoming versions.
Version we use currently are as below:

Elasticsearch(ELK): 1.2.1
Logstash(ELK): 1.4.1
Kibana(ELK): 3.1.0

**Comment by albertzaharovits** [comment]
Thank you for your interest @rmgarg22 .

Elasticsearch is a REST API server that returns resources as JSON documents, not HTML. The Headers you are mentioning are to be interpreted by a browser which should not interact directly with Elasticsearch. These returned resources are not to be interpreted by a browser, but by a JSON parser which does not care about the HTTP Headers.

You might want to take this to the https://github.com/elastic/kibana repo. Kibana is serving ES results in a form consumable by a browser.
However these Headers should not be present on every resource served by Kibana, if any. You should argue why a certain path is vulnerable if the Header is missing. We have throughly tested Kibana for XSS and CSRF. A generic tool warning is unlikely to arouse interest.

Also, if security is your concern you should consider upgrading the stack. The versions you have mentioned have exceeded *end of life* and any security bugs that we find have not been backported for quite a while now...
