### ISSUE TITLE
AzureMinimumMasterNodesTests @AwaitsFix because of flakiness

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#27554]
[These tests](https://github.com/elastic/elasticsearch/blob/7ac361d86ecae47052b4132e63c5c3e97a09ccc7/plugins/discovery-azure-classic/src/test/java/org/elasticsearch/discovery/azure/classic/AzureMinimumMasterNodesTests.java#L44) don't seem to have run since May 2015 due to the `@AwaitsFix` annotation, but the referenced issue (https://github.com/elastic/elasticsearch-cloud-azure/issues/89) is closed.

Additionally, `discovery-azure-classic` [is deprecated](https://github.com/elastic/elasticsearch-cloud-azure/issues/91#issuecomment-229113595).

I've updated the annotation to point at this issue for now, but feel that the best thing to do is just to get rid of this test.

**Comment by jasontedor** [comment]
This test passed three out of three runs for me. Let's remove the await fix and close this issue and see what happens.

**Comment by jasontedor** [comment]
Closed by d0cd18169e0cd1d9301c5c46a9f874abfc822d31 (and backported to 6.x in 7bc2630f3c60ebba175e916880b11219ce0012e7).

**Comment by tlrx** [comment]
Thanks @jasontedor
