### ISSUE TITLE
`scroll` timeout cannot be changed in _reindex API

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#27555]
The `scroll` timeout is set by default to 5 minutes when using the `_reindex` API. It is possible to change this value when using the java client but not when using the rest API directly. 
5 minutes is quite high but if the indexation is slow we can still reach the timeout and fail the entire reindex due to a context missing in the scroll. Since `_update_by_query` and `_delete_by_query` can change the default value in the rest API, we should also handle this parameter in `_reindex`.

**Comment by PnPie** [comment]
Hello @jimczi 
I made a PR for this :smile:
