### ISSUE TITLE
x-pack/plugin-security.policy: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/ssl/certs/root-ca.crt" "read")

### ISSUE THREAD

**Issue by minfrin** [elastic/elasticsearch#27562]
**Elasticsearch version** (`bin/elasticsearch --version`):

Version: 6.0.0, Build: 8f0685b/2017-11-10T18:41:22.859Z, JVM: 1.8.0_151

**Plugins installed**: []

**JVM version** (`java -version`):

openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Linux elastic01 4.4.0-1041-aws #50-Ubuntu SMP Wed Nov 15 22:18:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

- Install elasticsearch.
- Install elasticsearch x-pack
- Configure a root certificate as follows:

xpack.ssl.certificate_authorities: [ "/etc/ssl/certs/root-ca.crt" ]

- Startup fails as below.

**Provide logs (if relevant)**:

Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/ssl/certs/root-ca.crt" "read")

Turns out /usr/share/elasticsearch/plugins/x-pack/plugin-security.policy contains no sensible defaults for the location of the certificates for the security plugin.

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch only. For X-Pack issues, please use the [forum](https://discuss.elastic.co). Feel free to link from here to a topic that you open in the X-Pack category.
