### ISSUE TITLE
Group data on aggregations

### ISSUE THREAD

**Issue by arkkanoid** [elastic/elasticsearch#27566]
Hi, 
I've some related terms in a field, with the graph tool I can connect it:

<img width="421" alt="captura de pantalla 2017-11-28 a les 18 11 59" src="https://user-images.githubusercontent.com/3811604/33333824-3fde3f18-d468-11e7-8dc9-9ad6107f303c.png">

What I'm looking for is a way to group all this terms as one in an aggregation.
What I get now:

    skills: Descending | Count
    ---------------------------
    agile and lean startups | 14
    lean ux | 14
    agile | 8
    javascript | 8
    html | 6

What I expect:

    skills: Descending | Count
    ---------------------------
    agile and lean startups | 36
    javascript | 8
    html | 6

It's possible to do with the current version of ES?

Thanks

**Comment by DaveCTurner** [comment]
Hi @arkkanoid! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
