### ISSUE TITLE
Remove `index.ttl.disable_purge`

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#27582]
TTL is no longer supported and the `index.ttl.disable_purge` setting can be removed.

**Comment by PnPie** [comment]
I make one PR for this one :)

**Comment by videetssinghai** [comment]
I would like to make a PR for this one if this issue is still open

**Comment by videetssinghai** [comment]
Ok so I found "index.ttl.disable_purge" in 3 files - IndexScopedSettings, IndexSettings and IndexSettingsTest. How do I remove it ? ( straight away remove its functions and tests without affecting the other code ?)

**Comment by videetssinghai** [comment]
@clintongormley

**Comment by javanna** [comment]
hi @videetssinghai there is already a PR waiting for review that fixes this issue, see #27589 .

**Comment by DaveCTurner** [comment]
Sorry, I didn't see this was open. It was deprecated in #29526 and closed in #29527, so this can be closed.
