### ISSUE TITLE
OOM when indexing largish GeoJSON document

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#27594]
**Elasticsearch version**: 5.6.4

**Plugins installed**: []

**JVM version**:

```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**OS version**: `Darwin Davids-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64`

**Description of the problem including expected versus actual behavior**: OOM when indexing an 85MB GeoJSON document

**Steps to reproduce**:

```
PUT /geojson_test
{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "number_of_replicas": 0
    }
  },
  "mappings": {
    "streets": {
      "properties": {
        "type": {
          "type": "text"
        },
        "features": {
          "type": "nested",
          "properties": {
            "type": {
              "type": "text"
            },
            "geometry": {
              "type": "geo_shape",
              "tree": "quadtree",
              "precision": "100cm"
            }
          }
        }
      }
    }
  }
}
```

Then download the file from https://github.com/Chicago/osd-street-center-line/tree/ee45d118cec6760619568a5675278454d6324cf1/data and attempt to put it into this index as a single document. After a while (and a lot of GC activity) ES crashed with an OOM.

**Comment by jasontedor** [comment]
What do you think should happen @DaveCTurner?

**Comment by DaveCTurner** [comment]
Apologies, I missed that bit. I feel we should, at worst, reject the document more gracefully than this.

On `master` the situation is better. The request _is_ rejected as it contains >10000 nested documents, and if I delete all the documents after the first 10k then the request is accepted. Therefore I'm closing this.
