### ISSUE TITLE
Ability to have a memory and cpu water mark for shard movement similar to the disk water mark

### ISSUE THREAD

**Issue by antonpious** [elastic/elasticsearch#27622]
Currently elastic search moves shards to different nodes which has free disk space based on a water mark.
The similar logic is also needed for moving shard based on the memory availability in Java Heap on a node. 
Lets say we have 5 nodes, Node1, Node2, Node3, Node 4 and Node 5
We have 3 Indices Index1, Index2 and Index3 of 3 shards each with 1 replication.
This would lead to 9 Primary Shards and 9 Replica Shards a total of 18 Shards and 18/5 an initial balanced ratio of 4 shards in each of Node1, Node2, Node3, Node 4, and 2 Shards on Node 5. Lets assume that Index3 is not present in Node 5.

The total available memory on each nodes is 10 GB of which 5 GB is allocated to JVM and 5 GB is for Off Heap.
The disk space is 100 GB.

Data is loaded into all the indices and the data grows  so too the memory structures that hold memory.
The Index 3 data ingest is more than the other index 1 and index 2. The data volume in Index 3 keeps growing. There is no disk pressure so the shard movement does not happen. The Memory in Node1, Node2, Node3 and Node 4 constantly grows to reach 4.9 GB of 5 GB. The memory of Node 5 which did not have the index is still at 2.0 GB of 5 GB.

Since the memory in Node1... Node 4 is full due to the various structure of terms, fixed bitsets etc the nodes are not able to ingest more and more data leading to a slow rate of ingest due to memory pressure. If during this time the memory water mark is invoked one of the shards of Index 3 could have been moved to Node 5 leading to a balancing of memory across nodes for the ingest to happen.

The problem becomes more as more and more nodes are added say 7 nodes. In this instance if one or 2 indices take up the memory in Nodes 2, 3,4 all ingest to these nodes are drastically slowed downed though there is memory available on the other nodes and these indices shards can be moved.

The other is both these water mark namely disk and memory should work in combination.

Right now, when the disk is not available on a node, the shard gets moved to the node where there is disk space, but without consideration for both CPU or Memory.

Now when disk is added we should be able to rebalance based on CPU and Memory.
The similar problem of CPU water mark is present when most of the work is done only on few of the nodes while the rest of the nodes are free, this CPU water mark should also be configurable.

**Comment by morphers82** [comment]
I completely agree, memory pressure is why I had to stop auto reallocation and manually move around shards to keep memory pressure equal on nodes.

**Comment by antonpious** [comment]
Attaching a Node which has Mj2K which has used 7.6 GB of 7.9 GB while node G4QZ has 2.8 GB of 7.9 GB
![elastic](https://user-images.githubusercontent.com/15054021/33592120-e83c0150-d94e-11e7-9117-f29d8b79e9a2.PNG)

**Comment by dakrone** [comment]
@antonpious I'd be interested to know what is using the memory on those nodes, is it fielddata? segment memory?

**Comment by antonpious** [comment]
Unfortunately on the load we did not have the monitoring enabled so couldn't get the actual memory used while the load was going on.  We did exactly as morphers82 said, to be safe we had to stop processing move the shard manually around, check the memory has come down on the node and then start the processing. We continued to do this till the load finished.

Once the load finished we backed up the disk and restored on another environment to find where the memory was used. Most of the memory according to X-Pack Monitoring was used by Fixed BitSets ranged from 1 to 1.2 GB and Terms 400 to 450 MB in each node surprisingly Field data was 0 B.

We are simulating these loads should have these as we keep running.

What was baffling was when we restarted one node there was not much memory released but when we restarted the entire cluster the memory came down drastically. So not able to understand what is stored when data is at rest and  only search is happening and when data is being indexed and search is happening. 

If on the other hand if we did not restart, the memory did not come down so would be monitoring this too to check if the memory in heap comes down without restart.

![elasticafterrestart](https://user-images.githubusercontent.com/15054021/33636868-b3f867a4-d9e3-11e7-9c51-cc05a0e47fba.png)

**Comment by s1monw** [comment]
I think I understand your idea and there is nothing wrong with it. We discussed it and we are all struggling a bit how we would implement something like this. Is it something like this. We really need to figure out what is consuming memory ie. in your case using nested documents (that's what I guess from your FixedBitSets). I mean we can go and say we accumulate some defined counts like segment memory and fixedBitSets but even this is tricky it might change pretty quickly due to segment merges etc. I think we need to keep this open and continue brainstorming how we can help along those lines since I think it's a valid ask. 

on the CPU side I think it's tricky since 100% CPU isn't a bad thing necessarily... I guess people pay for this eventually :)

**Comment by DaveCTurner** [comment]
Echoing @simonw, there's a timescale issue here: memory and CPU pressure can be a lot more transient than disk space pressure, and it'd be a bad idea to start reallocating shards because of a transient issue.

On the other hand if there's a _persistent_ imbalance in memory or CPU usage across nodes then it seems like a better idea to shuffle things around to improve the situation. This raises the tricky question of how to tell if an imbalance is persistent or not, but I feel that this question is at the heart of this issue.

> 100% CPU isn't a bad thing necessarily

True, but OTOH being bottlenecked on a few hot nodes while the rest of your cluster sits idle seems suboptimal.

**Comment by antonpious** [comment]
The cluster entered into this state by a mix of search request, id search request and records which were created and updated. I have pointed out the logic changed required on the Id in #28206 

With both these issue as well as the limit on the memory heap of max 31, the current architecture design is safe till one of the node reaches 31 GB of heap space or the max CPU allocation on a node.

So the only logical way out of this situation is to first vertically scale all nodes to max cpu and max 31 GB of  heap memory and then do the horizontal scale of nodes with these vertically scaled limits.

This seems to be a significant design gap for mixed workloads on the same cluster.

**Comment by DaveCTurner** [comment]
We can divide this into two parts:

1. assessing how resource-intensive each shard allocation is, and
2. allocating shards so as not to overwhelm the resources of any individual node.

It might be possible to perform point 1 automatically, although it will take quite some research to come up with reliable ways to measure things like the CPU and memory load of an individual shard. That said, in the situation described here it seems that it'd be possible to manually specify the resource needs of each index's shards, avoiding the need for an automatic process.

The second point is covered by the idea mentioned in https://github.com/elastic/elasticsearch/issues/17213#issuecomment-382310838.

Our preference would be to close this issue and leave #17213 open to track the second point, but if we see compelling evidence that it's important for Elasticsearch to _automatically_ determine the resource needs of each shard then we'll follow that up too.

**Comment by DaveCTurner** [comment]
There were no objections to closing this in favour of #17213 so I'll do so. Please continue to feel free to leave comments indicating support (or otherwise) for this idea and we may revisit it in future.
