### ISSUE TITLE
Ability to have levers to control memory structures when amount of data indexed is more than the memory available

### ISSUE THREAD

**Issue by antonpious** [elastic/elasticsearch#27625]
Lets say we have a Node with 8 GB RAM and 100 GB disk with 1 index with 4 GB allocated to Heap and 4 GB allocated on heap.
We have a constraint on the amount of memory to be allocated to a node. We can only increase the disk but not the amount of memory available. i.e we should be able to index all the data that come in without increase in memory.

As we load data to this index namely 10 GB, 20 GB ... 100 GB we fill the disk and we increase the disk to 200 GB but not the memory, the elastic node memory keeps increasing in any or all of the buckets namely Stored Fields, Doc Values, Norms, Terms, Points, Fixed Bitsets, Term Vectors, Version Maps, Query Cache, Request Cache, Field data etc. Eventually the Heap Size fills up namely 3.9 GB of 4 GB  leading to lessor memory available for new data.

When this happens, the ingestion of new data comes to a crawling pace. Can levers be given to control the quota for each of these namely Stored Fields, Doc Values, Norms etc buckets so beyond a threshold only some policy based data is in memory while others are save to disk.

The same levers need to be given both at the Index level and/or node level.
When these are set at Node Level, the quota apply to all shards in that node
When these are set at Index Level, the quota apply to all shards of that particular index across nodes.

The Memory Quota should be distinguished between New Data and Existing data.
So if an Index has 200 GB of Data which is at Rest the quota should apply to data at rest
If an index is being ingested with new Data then there should be a separate quota on receiving this data and indexing without having to clash with the data that is already at rest, like around 1 GB of data coming in new within a time gap T1

**Comment by dakrone** [comment]
We already have some of these in the form of Circuit Breakers, and we strive to add more when possible. Is there a memory user that you are concerned about in particular?

**Comment by antonpious** [comment]
yes, for Terms and Fixed BitSets. Was able to find the lever for Field Data https://www.elastic.co/guide/en/elasticsearch/reference/6.0/modules-fielddata.html

**Comment by dakrone** [comment]
@antonpious the circuit breaker for terms and bitsets (all the Lucene reader's memory) was added in https://github.com/elastic/elasticsearch/pull/27116 so I believe this can be resolved now.
