### ISSUE TITLE
Child aggregation then by Parent aggregation (using _parent) not working after moving from 2.0.1 to 5.5.2

### ISSUE THREAD

**Issue by barathguna** [elastic/elasticsearch#27620]
Issue: Aggregation on child field and by _parent field is not working after upgrading elastic search from 2.0.1 to 5.5.2.

Test Details:
1. ParentType will have all MAC address and its details.
2. ChildType will have all application installed and its details (e.g. chrome (application name), 13(version), Browser(category))

Query Details:
Aggregate Application by "child1" (application name) then by "child2" (version) then cardinal aggregation by _parent id. This is to achieve, "List all application and its version and number of MAC associated with it"

Issue: "Group By mac parent1" aggregation is 0 in elastic search 5.5.2.

Create Index:
`curl -k -XPUT 'https://localhost:9200/testindex' -H 'Content-Type: application/json' -d'
{
  "settings" : {
        "index" : {
            "number_of_shards" : 3, 
            "number_of_replicas" : 1 
        },
        "analysis":{
            "analyzer":{
                "case_insensitive_analyzer":{
                    "tokenizer":"keyword",
                    "filter":"lowercase"
                }
            }
        }
    },
  "mappings" : {
    "parenttype": {
        "dynamic":"strict",
        "_all":{
            "enabled":false
        },
        "properties":{
            "parent1":{
                "type":"string",
                "analyzer":"case_insensitive_analyzer",
                 "fielddata": "true"
            },
            "parent2":{
                "type":"string",
                "analyzer":"case_insensitive_analyzer",
                 "fielddata": "true"
            },
            "parent3":{
                "type":"string",
                "analyzer":"case_insensitive_analyzer",
                "fielddata": "true"
            }
        }
    },
    "childtype": {
            "dynamic":"strict",
            "_all":{
                "enabled":false
            },
            "_parent":{
                "type":"parenttype"
            },
            "_routing":{"required":true},
            "properties":{
                "child1":{
                    "type":"string",
                    "analyzer":"case_insensitive_analyzer",
                    "fielddata": "true"
                },
                "child2":{
                    "type":"string",
                    "analyzer":"case_insensitive_analyzer",
                    "fielddata": "true"
                },
                "child3":{
                    "type":"string",
                    "analyzer":"case_insensitive_analyzer",
                    "fielddata": "true"
                }
            }
        }
    }
}'`

Insert data:
`curl -k -XPOST 'https://localhost:9200/testindex/parenttype/1' -H 'Content-Type: application/json' -d'
{
  "parent1" : "MAC1",
  "parent2" : "abc12",
  "parent3" : "abc13"
}'
curl -k -XPOST 'https://localhost:9200/testindex/parenttype/2' -H 'Content-Type: application/json' -d'
{
  "parent1" : "MAC2",
  "parent2" : "abc22",
  "parent3" : "abc23"
}'
curl -k -XPOST 'https://localhost:9200/testindex/parenttype/3' -H 'Content-Type: application/json' -d'
{
  "parent1" : "MAC3",
  "parent2" : "abc32",
  "parent3" : "abc33"
}'
curl -k -XPOST 'https://localhost:9200/testindex/childtype/c10?parent=1' -H 'Content-Type: application/json' -d'
{
  "child1" : "chrome",
  "child2" : "6",
  "child3" : "browser"
}'
curl -k -XPOST 'https://localhost:9200/testindex/childtype/c11?parent=1' -H 'Content-Type: application/json' -d'
{
  "child1" : "ff",
  "child2" : "15",
  "child3" : "browser"
}'
curl -k -XPOST 'https://localhost:9200/testindex/childtype/c12?parent=1' -H 'Content-Type: application/json' -d'
{
  "child1" : "jabber",
  "child2" : "5",
  "child3" : "social"
}'
curl -k -XPOST 'https://localhost:9200/testindex/childtype/c20?parent=2' -H 'Content-Type: application/json' -d'
{
  "child1" : "chrome",
  "child2" : "6",
  "child3" : "browser"
}'
curl -k -XPOST 'https://localhost:9200/testindex/childtype/c21?parent=2' -H 'Content-Type: application/json' -d'
{
  "child1" : "safari",
  "child2" : "7",
  "child3" : "browser"
}'
curl -k -XPOST 'https://localhost:9200/testindex/childtype/c22?parent=2' -H 'Content-Type: application/json' -d'
{
  "child1" : "ff",
  "child2" : "16",
  "child3" : "browser"
}'
curl -k -XPOST 'https://localhost:9200/testindex/childtype/c30?parent=3' -H 'Content-Type: application/json' -d'
{
  "child1" : "chrome",
  "child2" : "6",
  "child3" : "browser"
}'`

Aggregation Query: 
`curl -k -XPOST 'https://localhost:9200/testindex/childtype,parenttype/_search?pretty' -H 'Content-Type: application/json' -d'
{
  "from" : 0,
  "size" : 10,
  "query" : { 
    "has_child" : {
      "query" : {
        "match_all" : {}
      },
      "type" : "childtype",
      "score_mode" : "avg",
      "min_children" : 0,
      "max_children" : 2147483647,
      "ignore_unmapped" : false,
      "boost" : 1.0,
      "inner_hits" : {
        "ignore_unmapped" : false,
        "from" : 0,
        "size" : 0,
        "version" : false,
        "explain" : false,
        "track_scores" : false
      }
    }
  },
  "aggregations" : {
    "Children " : {
      "children" : {
        "type" : "childtype"
      },
      "aggregations" : {
        "Group By category child3" : {
          "terms" : {
            "field" : "child3",
            "size" : 10000,
            "min_doc_count" : 1,
            "shard_min_doc_count" : 0,
            "show_term_doc_count_error" : false
          },
          "aggregations" : {
            "Group By version child2" : {
              "terms" : {
                "field" : "child2",
                "size" : 10000,
                "min_doc_count" : 1,
                "shard_min_doc_count" : 0,
                "show_term_doc_count_error" : false
              },
              "aggregations" : {
                "Group By mac parent1" : {
                  "cardinality": {
                    "field": "_parent"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}'`

Result:
`{
  "took" : 26,
  "timed_out" : false,
  "_shards" : {
    "total" : 3,
    "successful" : 3,
    "failed" : 0
  },
  "hits" : {
    "total" : 3,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "testindex",
        "_type" : "parenttype",
        "_id" : "2",
        "_score" : 1.0,
        "_source" : {
          "parent1" : "MAC2",
          "parent2" : "abc22",
          "parent3" : "abc23"
        },
        "inner_hits" : {
          "childtype" : {
            "hits" : {
              "total" : 3,
              "max_score" : 0.0,
              "hits" : [ ]
            }
          }
        }
      },
      {
        "_index" : "testindex",
        "_type" : "parenttype",
        "_id" : "1",
        "_score" : 1.0,
        "_source" : {
          "parent1" : "MAC1",
          "parent2" : "abc12",
          "parent3" : "abc13"
        },
        "inner_hits" : {
          "childtype" : {
            "hits" : {
              "total" : 3,
              "max_score" : 0.0,
              "hits" : [ ]
            }
          }
        }
      },
      {
        "_index" : "testindex",
        "_type" : "parenttype",
        "_id" : "3",
        "_score" : 1.0,
        "_source" : {
          "parent1" : "MAC3",
          "parent2" : "abc32",
          "parent3" : "abc33"
        },
        "inner_hits" : {
          "childtype" : {
            "hits" : {
              "total" : 1,
              "max_score" : 0.0,
              "hits" : [ ]
            }
          }
        }
      }
    ]
  },
  "aggregations" : {
    "Children " : {
      "doc_count" : 7,
      "Group By category child3" : {
        "doc_count_error_upper_bound" : 0,
        "sum_other_doc_count" : 0,
        "buckets" : [
          {
            "key" : "browser",
            "doc_count" : 6,
            "Group By version child2" : {
              "doc_count_error_upper_bound" : 0,
              "sum_other_doc_count" : 0,
              "buckets" : [
                {
                  "key" : "6",
                  "doc_count" : 3,
                  "Group By mac parent1" : {
                    "value" : 0
                  }
                },
                {
                  "key" : "15",
                  "doc_count" : 1,
                  "Group By mac parent1" : {
                    "value" : 0
                  }
                },
                {
                  "key" : "16",
                  "doc_count" : 1,
                  "Group By mac parent1" : {
                    "value" : 0
                  }
                },
                {
                  "key" : "7",
                  "doc_count" : 1,
                  "Group By mac parent1" : {
                    "value" : 0
                  }
                }
              ]
            }
          },
          {
            "key" : "social",
            "doc_count" : 1,
            "Group By version child2" : {
              "doc_count_error_upper_bound" : 0,
              "sum_other_doc_count" : 0,
              "buckets" : [
                {
                  "key" : "5",
                  "doc_count" : 1,
                  "Group By mac parent1" : {
                    "value" : 0
                  }
                }
              ]
            }
          }
        ]
      }
    }
  }
}`

**Comment by jimczi** [comment]
Thanks @barathguna I opened https://github.com/elastic/elasticsearch/pull/27668 to document the new format to access the `_parent` field in aggregations and scripts. It was not intended to break the format but we introduced a bug in this version that forces the usage of an explicit field name when using the `_parent` field outside of the specialized API for parent/child. In your example, the values for the `_parent` field are accessible through `_parent#parenttype`which is the underlying field created to handle the `parenttype => childtype` relation.

**Comment by barathguna** [comment]
Thanks @jimczi 

Here is the working query with "_parent#parenttype":
`curl -k -XPOST 'https://localhost:9200/testindex/childtype,parenttype/_search?pretty' -H 'Content-Type: application/json' -d'
{
  "from" : 0,
  "size" : 10,
  "query" : { 
        "match_all" : {}
  },
  "aggregations" : {
    "Children " : {
      "children" : {
        "type" : "childtype"
      },
      "aggregations" : {
        "Group By app child1" : {
          "terms" : {
            "field" : "child1",
            "size" : 10000,
            "min_doc_count" : 1,
            "shard_min_doc_count" : 0,
            "show_term_doc_count_error" : false
          },
          "aggregations" : {
            "Group By version child2" : {
              "terms" : {
                "field" : "child2",
                "size" : 10000,
                "min_doc_count" : 1,
                "shard_min_doc_count" : 0,
                "show_term_doc_count_error" : false
              },
              "aggregations" : {
                "Group By mac" : {
                  "cardinality": {
                    "field": "_parent#parenttype"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}'`

**Comment by danielmitterdorfer** [comment]
Closed by #27668.
