### ISSUE TITLE
ICU: cjk language analyzer not working as expected 

### ISSUE THREAD

**Issue by louisong** [elastic/elasticsearch#27638]
**Elasticsearch version** : 5.4, 5.6.3

**Description of the problem including expected versus actual behavior**:
Source text : 香港貿發局香港國際春季燈飾展 2016
Query by `match` for the text `香港`

Expected highlighted result: 
`<em>香港</em>貿發局<em>香港</em>國際春季燈飾展 2016`

Actual highlighted result: 
`<em>香港貿發局香港</em>國際春季燈飾展 2016`

**Steps to reproduce**:

1. Create index template using the cjk language analyzer:

> PUT _template/template_test
{
  "template": "test*",
  "mappings": {
    "_default_": {
      "_all": {
        "enabled": false
      },
      "dynamic": false
    }
  },
  "settings": {
    "index": {
      "mapper": {
        "dynamic": "false"
      },
      "number_of_shards": "1",
      "number_of_replicas": "1",
      "analysis": {
        "analyzer": {
          "cjk_main": {
            "tokenizer": "standard",
            "filter": [
              "cjk_width",
              "lowercase",
              "cjk_bigram", 
              "english_stop"
            ]
          }
        },
        "filter": {
          "english_stop": {
            "type": "stop",
            "stopwords": "_english_"
          }
        }
      }
    }
  }
} 

> 

2. Create index with cjk analyzer.

>PUT test_20171201 
{ 
"mappings": { 
"content": { 
"properties": { 
"@timestamp": { 
"type": "date" 
}, 
"@version": { 
"type": "text" 
}, 
"title": { 
"type": "text", 
"analyzer": "cjk_main" 
} 
} 
} 
} 
} 
>

3. Analyze the search string to check tokens with cjk analyzer.

>GET test_20171201/_analyze
{
  "text": ["香港貿發局香港國際春季燈飾展 2016 "],"analyzer": "cjk_main"
}
>

4. Index sample data.

>POST test_20171201/content/1
{
  "title":"香港貿發局香港國際春季燈飾展 2016 "
}
>

5. Highlight search query with the title `香港` which translates to country name `Hong Kong`.

>GET test_20171201/_search
{
  "query": {"match": {
    "title": "香港"
  }}, 
  "highlight": {
    "fields": {
      "title": {
     }
    }
  }
}
>

**Results from ES version 5.4 and 5.6.3**(Bug):

{
  "took": 3,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 0.3802836,
    "hits": [
      {
        "_index": "test_20171201",
        "_type": "content",
        "_id": "1",
        "_score": 0.3802836,
        "_source": {
          "title": "香港貿發局香港國際春季燈飾展 2016 "
        },
        "highlight": {
          "title": [
            `<em>香港貿發局香港</em>國際春季燈飾展 2016 `
          ]
        }
      }
    ]
  }
}

**Results from ES version 6.0** (Expected Results) :
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 0.39556286,
    "hits": [
      {
        "_index": "test_20171201",
        "_type": "content",
        "_id": "1",
        "_score": 0.39556286,
        "_source": {
          "title": "香港貿發局香港國際春季燈飾展 2016 "
        },
        "highlight": {
          "title": [
            `<em>香港</em>貿發局<em>香港</em>國際春季燈飾展 2016`
          ]
        }
      }
    ]
  }
}

**Comment by louisong** [comment]
Expected highlighted result works fine in ES version 6.0 : 
`<em>香港</em>貿發局<em>香港</em>國際春季燈飾展 2016`

**Comment by jimczi** [comment]
In 6.0 the default is to use the `unified` highlighter, unlike the `plain` highlighter it does not try to merge adjacent match in a single fragment which is why it has the expected result in 6.0. This new highlighter has been added in 5.4 so a workaround is to switch to this new highlighter. That's the default in 6 so it's a good idea to use this new highlighter in 5.x in order to prepare for the upgrade to 6. Regarding the bug in the `plain` highlighter I'll check why the two fragments are merged but the long term solution is to switch to the new highlighter.

**Comment by jimczi** [comment]
This is fixed in 6.0 with the `unified` highlighter, hence closing.
