### ISSUE TITLE
Multisearch Query Needed

### ISSUE THREAD

**Issue by gayathrimanohar** [elastic/elasticsearch#27644]
I'm using your elasticsearch code based php mysql. It's working fine. I have to implement the multisearch (mean msearch) concept on project.I have tried more steps for developing the msearch but i could not complete.

Multisearch concept:

single query can search the data on both two index type. One type have no conditions and to listed data.another have to search the data with conditions.finally combine the results and show on page.

1.common index with two types like(my_index / type1,type2)

2. type1 :- To search the title data with no conditions

3. type2 :- To search the title data with  conditions

shows the result with pagination
Note : Already i tried bool query but doesn't work 
 My code is here
public function Msearch($query)
    {
        $client = $this->elasticclient;
        $result = array();

        $i = 0;

        $params = [
		
			 
          'index' => 'cricsearch',
          
              'body'  => [
    ['type' => 'cricnews','scroll' => '30s'],
    ['query' => ['match' => ['title'=> $query]]],

    ['type' => 'cricvideos','scroll' => '30s'],['size'  => 0,'query' => ['match' => ['title'=> $query]]],
	],
	];
          //  print_r($event_id);
		  try {
        $query                 = $client->msearch($params);
		
        $hits                  = sizeof($query['hits']['hits']);
		print_r($hits);
        $hit                   = $query['hits']['hits'];
        $result['searchfound'] = $hits;
        while ($i < $hits) {

            $result['result'][$i] = $query['hits']['hits'][$i]['_source'];

            $i++;
        }
	
  
	
        return  $result;
		  }
		  catch (Exception $e) {
    echo $e->getMessage();
}
    }

**Comment by cbuescher** [comment]
Hi @gayathrimanohar! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
