### ISSUE TITLE
Scroll search. 'slice' query parameter vs query JSON

### ISSUE THREAD

**Issue by ilyaanisimov-reuters** [elastic/elasticsearch#27657]
**Scroll search. 'slice' query parameter**:
Our use case requires generating big terms search queries. 
curl -H "Content-Type: application/json" -d '{"slice":{"id":0,"max":135,"field":"DP"},"size":10,"sort":[{"DP":"desc"},{"T3ID":"asc"}],"_source":false,"query": <here goes 100MB terms query>}'  'elasticsearch.build:9200/idx/_search?scroll=1m

To reduce query size it is zipped. 

**The problem is that we have to zip up almost the same query each time.** The only difference is 'id' parameter ("slice":{"id":0,"max":135,"field":"DP"}).

Proposed solution allows to specify 'slice' parameters in the query parameter string. 'fieldName' is optional. Backward compatibility maintained by prioritizing JSON over query parameters.

curl -H "Content-Type: application/json" -d '{"query": {BIG_QUERY}}'  'elasticsearch.build:9200/idx/_search?scroll=1m&slice=<id>,<max>,<fieldName>

where:
id - is a mandatory string value parsable to int
max - is a mandatory string value parsable to int
fieldName - is a optional string

Example1:
curl -H "Content-Type: application/json" -d '{,"size":10,"sort":[{"DP":"desc"},{"T3ID":"asc"}],"_source":false,"query": <here goes 100MB terms query>}'  'elasticsearch.build:9200/idx/_search?scroll=1m&slice=0,135,DP

Example2 (no field name):
curl -H "Content-Type: application/json" -d '{,"size":10,"sort":[{"DP":"desc"},{"T3ID":"asc"}],"_source":false,"query": <here goes 100MB terms query>}'  'elasticsearch.build:9200/idx/_search?scroll=1m&slice=0,135

**Comment by ilyaanisimov-reuters** [comment]
Here is the PR
https://github.com/elastic/elasticsearch/pull/27676

**Comment by jimczi** [comment]
@ilyaanisimov-reuters can you explain why you need a 100MB query ? I don't think we should add new query parameters in the url because of compression. A query should be small and to be honest a 100MB query should be refused by es right away.

**Comment by ilyaanisimov-reuters** [comment]
@jimczi I understand your point. We are porting old application with it's requirements and sometimes have to generate huge terms queries.It's the only way to fulfill requirements.

**Comment by ilyaanisimov-reuters** [comment]
ES fits most of the requirements we have except some corner cases (what a surprise! we have corner cases). The situation with slices and big queries is just one of them. In other cases we wrote plugins.

**Comment by ilyaanisimov-reuters** [comment]
The general goal of the PR is to remove client side inefficiency of generating a payload for every slice. With the url parameter the payload can be generated once, compressed once, and reused for every sliced scroll request

**Comment by jimczi** [comment]
Sorry for the delay, I hope you don't mind if I close this, generating the payload for a slice should not be the the limiting factor (query should be small). Having `slice` in json is also more readable since it requires multiple parameters to configure.
