### ISSUE TITLE
Float type does not follow IEEE 754 standard

### ISSUE THREAD

**Issue by drw112** [elastic/elasticsearch#27653]
**Elasticsearch version** 6.0.0

**Plugins installed**: [x-pack]

**JVM version** (`java -version`): 1.8.0_60

**OS version** (`uname -a` if on a Unix-like system): Centos 7

**Description of the problem including expected versus actual behavior**:

https://www.elastic.co/guide/en/elasticsearch/reference/6.0/number.html
float | A single-precision 32-bit IEEE 754 floating point.

https://en.wikipedia.org/wiki/IEEE_754 "As with IEEE 754-1985, the biased-exponent field is filled with all 1 bits to indicate either infinity (trailing significand field = 0) or a NaN (trailing significand field ≠ 0)."

Elasticsearch is rejecting our infinity value floats.  The Elasticsearch documentation claims to follow the IEEE 754 float spec but is rejecting infinity and NaN values.

**Steps to reproduce**:

 1. This is the commit that changed this behavior https://github.com/elastic/elasticsearch/commit/d8ff6e9831ede9782d913b67fa04102c2d1182d1
 2. Create an index
 3. Send a finite float to a field on the index
 4. Send an infinity value to the same field on the index

**Provide logs (if relevant)**:
 "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"[float] supports only finite values, but got [Infinity]"}

**Comment by rjernst** [comment]
This is by design. Json has no way to represent inifinity or NaN.
See the original issue: https://github.com/elastic/elasticsearch/issues/25534

**Comment by drw112** [comment]
@rjernst Should the documentation be updated to say it follows [RFC 4627](https://tools.ietf.org/html/rfc4627) or [ECMA-262](https://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf) instead of IEEE 754?  The Elasticsearch docs don't accurately reflect the accepted values for float/half-float/double

> NOTE 4: Finite numbers are stringified as if by calling ToString(number). NaN and Infinity regardless of sign are represented as the String null.

**Comment by rjernst** [comment]
I'll reopen as a docs issue, but I'm not sure in what way we should change the docs. /cc @jpountz

**Comment by jpountz** [comment]
@drw112 would something like that work for you: `A single-precision 32-bit IEEE 754 floating point, restricted to finite values.`?

**Comment by drw112** [comment]
Yes, I think that is clear and concise. Thanks!
