### ISSUE TITLE
Does Term suggester NOT work as expected if the min_word_length is 1?

### ISSUE THREAD

**Issue by vamsyr** [elastic/elasticsearch#27667]
I am using Elasticsearch 5.5.2. I have the below mapping and the documents

Mapping --

PUT /testindex/
{
   "mappings": {
      "testtype": {
         "properties": {
             "city": {
               "type": "text"
         }
      }
    }
 }
}

I have indexed the below documents --

POST testindex/testtype/1
{"city": "a"}

POST testindex/testtype/2
{"city": "ab"}

POST testindex/testtype/3
{"city": "abc"}

When I try the below, I am NOT getting any suggestions

POST /testindex/testtype/_search
    {
     "suggest": {
      "my_suggest": {
       "text": "a",
         "term": {
          "field": "city",
          "min_word_length": 1,
         }
      }
   }
 }

I have tried by adding "prefix_length": 0 also. But still no response for the above query. 

As per my understanding of the documentation of the term suggester, I am expecting 'ab' as the suggested term for the above query. But I am NOT getting any suggestions for the above query. Can someone please validate and clarify? 

In the below query, for the search text 'ab', I am getting 'abc' as the suggested term

POST /testindex/testtype/_search
{
"suggest": {
"my_suggest": {
"text": "ab",
"term": {
"field": "city",
"min_word_length": 1
}
}
}
}

The result I am getting is
"options": [
{
"text": "abc",
"score": 0.5,
"freq": 1
}
]

When I am getting 'abc' as the suggested term for the search text 'ab', why I am NOT getting 'ab' as the suggested term for the search text 'a', though I have set the property 'min_word_length' to 1.

Please validate and clarify. 
Thank you very much.

**Comment by mayya-sharipova** [comment]
To suggest options, the distance between requested term and index terms  is calculated using of the following algorithms:  `internal` (default option), `damerau_levenshtein`, `levenstein`, `jarowinkler` or `ngram`: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-term.html.
If the similarity between the request term and the index terms doesn't pass threshold (0.5), no options are suggested. This happens in your case where similarity between a term `a` with any other term is less than 0.5. You can try to experiment with different `string_distance` algorithm. For example, below returns an option "ab" for me:

```json
{
  "suggest": {
    "my_suggest": {
      "text": "a",
      "term": {
        "field": "city",
        "suggest_mode": "always",
        "min_word_length": 1,
        "string_distance": "levenstein"
      }
    }
  }
}
```

Also, consider using `"suggest_mode": "always"` if you want to include suggestions to terms that already present in the index.

**Comment by vamsyr** [comment]
Thank you very much for your time. I will try as suggested by you.
