### ISSUE TITLE
After upgrading from 5.6.3 to 6.0.0, complains that ingest pipeline does not exists, although it does still exist.

### ISSUE THREAD

**Issue by vchan2002** [elastic/elasticsearch#27661]
**Describe the feature**:

**Elasticsearch version** 6.0.0

**Plugins installed**: ec2-discovery,s3-repository

**JVM version** (`java -version`): 1.8.151

**OS version** (`uname -a` if on a Unix-like system): Amazon Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1.  Initially, I have a ES 5.6.3 cluster, which I have filebeat 6.0.0 pointing system logs to it.  I enabled the system module, which created several ingest pipelines, one of which is called filebeat-6.0.0-system-auth-pipeline.  Filebeat was working fine and elasticsearch ingest pipeline was parsing the system logs correctly.
 2.  I decided to upgrade to 6.0.0 by spinning up a 6.0.0 node, then retiring the old 5.6.3 node, then adding another 6.0.0 node.  I did the Kibana upgrade and it worked fine.
 3.  The 1st 6.0.0 node on elasticsearch complains that the filebeat-6.0.0-system-auth-pipeline is missing... However, what is odd is that hitting _ingest/pipeline/filebeat-6.0.0-system-auth-pipeline API turns up the pipeline with all of the information.. so it's there....
4.  Just to be curious, I restarted the ES node that's throwing the error, but then it stopped throwing the error about ingest pipeline missing.
5.  During all this time, however, the additional parsing that I'm expecting from the ingest node has stopped working.
6.  Just to be curious, I went back to the filebeat node that I have setup, which had been working fine... the filebeat config does not explicitly specify the a pipeline... even though.. when it was in 5.6.3, it was able to work and the ingest nodes were parsing the logs....
7.  So, I was like... why not.... I added, explictly, the pipeline parameter in the output section....
8.  Now Beats throws an error complaining the ingest pipeline does not exists... again.... the pipeline actually does exist.

**Provide logs (if relevant)**:

From elasticsearch

[2017-12-05T00:13:42,662][DEBUG][o.e.a.b.TransportBulkAction] [venuereporting-es5-2-43-7f9c-es-01] failed to execute pipeline [filebeat-6.0.0-system-auth-pipeline] for document [filebeat-6.0.0-2017.12.05/doc/null]
java.lang.IllegalArgumentException: pipeline with id [filebeat-6.0.0-system-auth-pipeline] does not exist
        at org.elasticsearch.ingest.PipelineExecutionService.getPipeline(PipelineExecutionService.java:189) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.ingest.PipelineExecutionService.access$100(PipelineExecutionService.java:41) ~[elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.ingest.PipelineExecutionService$2.doRun(PipelineExecutionService.java:88) [elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) [elasticsearch-6.0.0.jar:6.0.0]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.0.0.jar:6.0.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

Logs from BEATS after I tried to have it explicitly use a pipeline.

2017-12-05T01:07:38Z WARN Can not index event (status=400): {"type":"illegal_argument_exception","reason":"pipeline with id [filebeat-6.0.0-system-auth-pipeline] does not exist"}

Do ingest pipelines carry over from version upgrade of 5 to 6?  Did I miss something that needs to be done to them?

**Comment by vchan2002** [comment]
So... going further troubleshooting... I tried to do a GET of the existing pipeline, delete it, and re-PUT it.... the 1st two steps is fine, but the last step, it complains that 

        "reason": "[processors] required property is missing",

However, the ingest pipeline does have a processors property... So I'm a bit lost as to what's wrong.

`{
  "filebeat-6.0.0-system-auth-pipeline": {
    "description": "Pipeline for parsing system authorisation/secure logs",
    "processors": [
      {
        "grok": {
          "field": "message",
          "ignore_missing": true,
          "pattern_definitions": {
            "GREEDYMULTILINE": "(.|\n)*"
          },
          "patterns": [
            """%{SYSLOGTIMESTAMP:system.auth.timestamp} %{SYSLOGHOST:system.auth.hostname} sshd(?:\[%{POSINT:system.auth.pid}\])?: %{DATA:system.auth.ssh.event} %{DATA:system.auth.ssh.method} for (invalid user )?%{DATA:system.auth.user} from %{IPORHOST:system.auth.ssh.ip} port %{NUMBER:system.auth.ssh.port} ssh2(: %{GREEDYDATA:system.auth.ssh.signature})?""",
            """%{SYSLOGTIMESTAMP:system.auth.timestamp} %{SYSLOGHOST:system.auth.hostname} sshd(?:\[%{POSINT:system.auth.pid}\])?: %{DATA:system.auth.ssh.event} user %{DATA:system.auth.user} from %{IPORHOST:system.auth.ssh.ip}""",
            """%{SYSLOGTIMESTAMP:system.auth.timestamp} %{SYSLOGHOST:system.auth.hostname} sshd(?:\[%{POSINT:system.auth.pid}\])?: Did not receive identification string from %{IPORHOST:system.auth.ssh.dropped_ip}""",
            """%{SYSLOGTIMESTAMP:system.auth.timestamp} %{SYSLOGHOST:system.auth.hostname} sudo(?:\[%{POSINT:system.auth.pid}\])?: \s*%{DATA:system.auth.user} :( %{DATA:system.auth.sudo.error} ;)? TTY=%{DATA:system.auth.sudo.tty} ; PWD=%{DATA:system.auth.sudo.pwd} ; USER=%{DATA:system.auth.sudo.user} ; COMMAND=%{GREEDYDATA:system.auth.sudo.command}""",
            """%{SYSLOGTIMESTAMP:system.auth.timestamp} %{SYSLOGHOST:system.auth.hostname} groupadd(?:\[%{POSINT:system.auth.pid}\])?: new group: name=%{DATA:system.auth.groupadd.name}, GID=%{NUMBER:system.auth.groupadd.gid}""",
            """%{SYSLOGTIMESTAMP:system.auth.timestamp} %{SYSLOGHOST:system.auth.hostname} useradd(?:\[%{POSINT:system.auth.pid}\])?: new user: name=%{DATA:system.auth.useradd.name}, UID=%{NUMBER:system.auth.useradd.uid}, GID=%{NUMBER:system.auth.useradd.gid}, home=%{DATA:system.auth.useradd.home}, shell=%{DATA:system.auth.useradd.shell}$""",
            """%{SYSLOGTIMESTAMP:system.auth.timestamp} %{SYSLOGHOST:system.auth.hostname}? %{DATA:system.auth.program}(?:\[%{POSINT:system.auth.pid}\])?: %{GREEDYMULTILINE:system.auth.message}"""
          ]
        }
      },
      {
        "remove": {
          "field": "message"
        }
      },
      {
        "date": {
          "formats": [
            "MMM  d HH:mm:ss",
            "MMM dd HH:mm:ss"
          ],
          "ignore_failure": true,
          "field": "system.auth.timestamp",
          "target_field": "@timestamp"
        }
      },
      {
        "geoip": {
          "field": "system.auth.ssh.ip",
          "target_field": "system.auth.ssh.geoip",
          "ignore_failure": true
        }
      }
    ],
    "on_failure": [
      {
        "set": {
          "field": "error.message",
          "value": "{{ _ingest.on_failure_message }}"
        }
      }
    ]
  }
}`

**Comment by danielmitterdorfer** [comment]
Hi @vchan2002, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead.

I tried to reproduce your issue as follows:

```
# on 5.6.3:

curl -XPUT 'localhost:9200/_ingest/pipeline/ingestion-status?pretty' -H 'Content-Type: application/json' -d'
{
  "description" : "Sets status",
  "processors" : [
    {
      "set" : {
        "field": "status",
        "value": "ingested"
      }
    }
  ]
}
'
curl -XPOST 'http://localhost:9200/ledger/sale/_bulk?pretty&pipeline=ingestion-status' -H 'Content-Type: application/json' -d'
{"index":{}}
{"date": "2015/01/01 00:00:00", "amount": 200, "type": "sale", "description": "something"}
{"index":{}}
{"date": "2015/01/01 00:00:00", "amount": 10, "type": "expense", "decription": "another thing"}
{"index":{}}
{"date": "2015/01/01 00:00:00", "amount": 150, "type": "sale", "description": "blah"}
'

curl -XGET 'localhost:9200/_search?pretty' -H 'Content-Type: application/json' -d'
{
    "query": {
        "match_all": {}
    }
}
'

# do an upgrade to 6.0.0

# on 6.0.0
curl -XPOST 'http://localhost:9200/ledger/sale/_bulk?pretty&pipeline=ingestion-status' -H 'Content-Type: application/json' -d'
{"index":{}}
{"date": "2017/01/01 00:00:00", "amount": 300, "type": "sale", "description": "something"}
'

curl -XGET 'localhost:9200/_search?pretty' -H 'Content-Type: application/json' -d'
{
    "query": {
        "match_all": {}
    }
}
'
```

All search results contained the field `status` with the value `ingested` indicating that they went through the ingest pipeline just fine (before and after the upgrade).

W.r.t to the trouble that you had with recreating the ingest pipeline on 6.0.0. You've probably tried to create it as follows:

```
curl -XPUT 'localhost:9200/_ingest/pipeline/filebeat-6.0.0-system-auth-pipeline?pretty' -H 'Content-Type: application/json' -d'
{
  "filebeat-6.0.0-system-auth-pipeline": {
    "description": "Pipeline for parsing system authorisation/secure logs",
    "processors": [ ...  ]
  }
}
'
```

However, the correct syntax is:

```
curl -XPUT 'localhost:9200/_ingest/pipeline/filebeat-6.0.0-system-auth-pipeline?pretty' -H 'Content-Type: application/json' -d'
{
    "description": "Pipeline for parsing system authorisation/secure logs",
    "processors": [ ...  ]
}
'
```

Hope that helps you! :)
