### ISSUE TITLE
Elasticsearch6.0

### ISSUE THREAD

**Issue by viewpointJoin** [elastic/elasticsearch#27665]
Elasticsearch6.0 version can't start after setting up cross domain configuration. How do I solve it? My settings are http.cors.enable: true and http.cors.allow-origin: *.

**Comment by tvernum** [comment]
Hi @viewpointJoin 

Please ask this question on our [discuss forum](https://discuss.elastic.co/) where we can provide better support.
Elastic uses GitHub issues for confirmed bugs and feature requests, but it is not a suitable place to try to diagnose and resolve configuration issues.

If you ask your question on the appropriate forum, and provide specific details about what you have tried, and what errors your are encountering, then we'll be happy to help find a solution.
