### ISSUE TITLE
Unexpected token VALUE_STRING

### ISSUE THREAD

**Issue by jilinhao** [elastic/elasticsearch#27686]
GET logstash-i-2017.11.30/_search?pretty
{
"aggs" : {
"destid" : {
"terms" : {
"script" : {
"source": "doc['destid'].value",
"lang": "painless"
}
}
}
}
}

why?
{
"error": {
"root_cause": [
{
"type": "parsing_exception",
"reason": "Unexpected token VALUE_STRING [script] in [destid].",
"line": 5,
"col": 29
}
],
"type": "parsing_exception",
"reason": "Unexpected token VALUE_STRING [script] in [destid].",
"line": 5,
"col": 29
},
"status": 400
}

**Comment by cbuescher** [comment]
Hi, looks like your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
