### ISSUE TITLE
java-rest-high-document bulk api should support a context

### ISSUE THREAD

**Issue by jeacott1** [elastic/elasticsearch#27683]
when I am pulling messages from kafka partitions, and pushing to ES via the bulk api,
I need to know which bulk updates from which partitions actually succeeded in order to mark read checkpoints.
it would be helpful to be able to supply extra context (ie a Map) to the api in order to track such things. 
probably on BulkRequest objects, and individual request objects.

The BulkProcessor should also accept context, and BulkRequest objects directly or provide some other means of tracking bulkRequests for the same usecase.

one solution is to create multiple clients, 1 per partition, but thats not really ideal, and breaks things like setConcurrentRequests and setBulkActions.

Cheers.

**Comment by cbuescher** [comment]
Hi @jeacott1,

the BulkResponse you get back when executing the BulkRequest should hold a response for each item responding of the bulk requests, in the order they have been sent (either the document id/type/index or a failure object). Could you describe in more detail what part is missing from this API to work in your use case?

**Comment by jeacott1** [comment]
sure,
 the current api only accepts and responds with data intended directly for ES consumption. ie I can only send actual to be indexed documents. If I want for example to use the async api, and know which partition Id was associated with a given batch I have 3 basic options.
1. I create a new esClient, or wrapper representing each partition and ensure I use the correct one for the partition each time. seems naive and makes it that much harder to throttle throughput to ES.
2. I add a new partitionid field to my to-be-indexed pojo's representing es documents and not serialise that field to json before submission. somewhat hacky and invasive. 
3. some external means of keeping track of each doc (or the first doc in a bulkRequest) vs partitionid and looking them up.

the trouble with all of these is that I really want to track the batch, not the individual documents since the batch will have an associated kafka offset that needs to be stored, or not depending on success. 

so the ability to pass through arbitrary context stuff would I think be helpful.
none of this works for the BulkProcessor unless it can accept bulkRequests. at least then I can control each submission block is per partition and recognise which one failed when it does. I could also pass through some form of ordering marker so I can properly track responses in order too.

without it I seem to be stuck with hacky workarounds. am I missing something?

**Comment by jasontedor** [comment]
I don't understand, you can capture the context client side as part of your async listener:

```
        final int partitionId;
        final BulkRequest bulkRequest;
        client.bulkAsync(bulkRequest, new ActionListener<BulkResponse>() {
            @Override
            public void onResponse(BulkResponse bulkItemResponses) {
                // capture partitionId and use it in the listener
            }

            @Override
            public void onFailure(Exception e) {
                // capture partitionId and use it in the listener
            }
        });
```

You can capture whatever metadata you need here?

The bulk processor is different since you do not control the batching. Sending bulk requests to the bulk processor mostly defeats the point of the bulk processor (other than controlling the number of outstanding requests), instead use the bulk methods on the clients?

**Comment by jeacott1** [comment]
ok sure, I could use anonymous inner classes, or I could create a new listener/client pair per partition,
 but if I don't want to structure my code that way, or I want to use just a single listener I think this lib should support the case.

**Comment by cbuescher** [comment]
I'm not convinved yet that this is a good enough reason to add more complexity to the bulk api. I'm leaving this issue open for others to comment but currently I think solving this task on the client end is a better solution.

**Comment by jasontedor** [comment]
> ok sure, I could use anonymous inner classes, or I could create a new listener/client pair per partition,
but if I don't want to structure my code that way, or I want to use just a single listener I think this lib should support the case.

Note that you do not have to use anonymous classes. You can have a concrete listener:

```java
class PartitionIdAwareListener extends ActionListener<BulkResponse> {
    private final int partitionId;

    public ParititionIdAwareListener(final int int partitionId) {
      this.partitionId = partitionId;
    }

    .
    .
    .
}
```

Then:

```java
        client.bulkAsync(bulkRequest, new ParititionIdAwareListener(partitionId));
```

We discussed this in Fix-it-Friday and agree that since this can easily be handled client side without adding any complexity to the API we are not going to implement this functionality.

**Comment by jeacott1** [comment]
@jasontedor even with a new listener, it doesn't solve the actual problem.  I still need a new listener per partition instead of a simple single listener though which I can pass a context.

but I guess, cest comme ca.
