### ISSUE TITLE
icu_tokenizer not found

### ISSUE THREAD

**Issue by Ricolo53** [elastic/elasticsearch#27687]
Hello,

I'm on ES 6.0 and I've installed ICU Analysis Plugin like explain [here](https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu.html) to implement better french analyzer like explain on [this website](https://jolicode.com/blog/construire-un-bon-analyzer-francais-pour-elasticsearch#tldr).

But when I try to put analyser on settings, like

```
curl -XPUT 'http://localhost:9200/index' -H 'Content-Type: application/json' -d '
{
  "settings": {
      "index": {
         "analysis": {
            "analyzer": {
               "my_analyzer": {
                  "type": "custom",
                  "tokenizer" : "icu_tokenizer"
               }
            }
         }
      }
   }
}'

```

Error was return :

```
{
	"error": {
		"root_cause": [{
			"type": "illegal_argument_exception",
			"reason": "Custom Analyzer [my_analyzer] failed to find tokenizer under name [icu_tokenizer]"
		}],
		"type": "illegal_argument_exception",
		"reason": "Custom Analyzer [my_analyzer] failed to find tokenizer under name [icu_tokenizer]"
	},
	"status": 400
}
```

Someone have idea about what I'm doing wrong ?

`/usr/share/elasticsearch/bin/elasticsearch-plugin list` return `analysis-icu`

**Comment by Ricolo53** [comment]
Ok, just I don't restart ES after install plugin...... Don't blame me...

**Comment by dadoonet** [comment]
Please next time ask this kind of question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
