### ISSUE TITLE
Remove `delimited_payload_filter` and add to migration assistant

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#27704]
This is a follow up to #26625. What seems left to do is remove the deprecated use of `delimited_payload_filter` in 7.0, but still allow the old form for indices created in 6.x. Also, a check should be added to the migration assistant.

**Comment by romseygeek** [comment]
@elastic/es-search-aggs

**Comment by cbuescher** [comment]
Closed by #27705
