### ISSUE TITLE
Expose failed processor using exception metadata

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#27724]
... instead of headers.

#18342 introduced some extra information on exceptions thrown by a compound processor, using headers, which is one of the many metadata mechanisms we currently have. As part of #27672 we'd like to reduce the variety of metadata mechanisms for the benefit of clients. Could this information be passed through using `addMetadata()` instead?

@talevy do you have any opinions on this?

**Comment by DaveCTurner** [comment]
Also @simonw said this: https://github.com/elastic/elasticsearch/pull/16276#issuecomment-177910583 - do you (Simon) have opinions about preferring metadata over headers?

**Comment by DaveCTurner** [comment]
The code in question is https://github.com/elastic/elasticsearch/blob/24d7fa6d54339b2ab9459558e507ec958f980ca8/core/src/main/java/org/elasticsearch/ingest/CompoundProcessor.java#L158-L163

**Comment by talevy** [comment]
Thanks for bringing this up @DaveCTurner. At the time, headers were the only way to inject custom context without creating a new custom Exception (something that is frowned upon). I was not aware that metadata was added in 5.3 to clean up the semantics of these additional fields (https://github.com/elastic/elasticsearch/pull/22703). It seems like metadata is the more appropriate place for this information given the direction of the code.

I will take a look at this and see if it is as I thought. We can update this code for 7.0.

**Comment by javanna** [comment]
Wasn't also not having to parse response body a reason for using headers over metadata? Do we know if any of our product reads this stuff returned as part of response headers?

**Comment by dakrone** [comment]
Closing this as we are working on something better with the introduction of the failure store for data streams.
