### ISSUE TITLE
Warning on _missing_ query_string usage post-5.0?

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#27736]
Related to https://github.com/elastic/elasticsearch/issues/21226.

I am wondering if there's anything we can do here to help users with migration where they may have Lucene query string using `_missing_`.  Here is the current behavior:

1.  Yep, we documented it here that `_missing_` has been removed: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/breaking_50_search_changes.html#_deprecated_queries_removed

2.  Deprecation logging (eg. in 2.x when preparing for migration to 5.0) fails to detect it.  Note that it does detect missing query (in DSL) form, but if `_missing_` is used with query_string, it does not throw any deprecation logging messages.

3. On 5.x (eg. 5.6), if users continue to use `_missing_` , eg.

```
    "query_string": {
      "query": "_missing_:asdasdasd"
    }
```

Elasticsearch will simply return 0 documents as if all documents contain the asdasdasd field with no indication that it is returning 0 documents because query syntax with _missing_ is used (and have been removed from product).

We are probably not going to go back and change the deprecation logging feature in 2.x, but perhaps there's something we can do in 5.x+ releases to throw a warning to the log file (or even return an error in the response) when someone is using `_missing_` so it is easier for users to tell what is actually happening when 0 documents is returned?

**Comment by jimczi** [comment]
We discussed this during FixItFriday and decided that there's nothing we can do about it. The removal is documented and there is no point adding a deprecation warning that late in 5.x so users should read the breaking change.
