### ISSUE TITLE
Missing table in http exporter reference

### ISSUE THREAD

**Issue by ctindel** [elastic/elasticsearch#27739]
This Page for 6.0:

https://www.elastic.co/guide/en/elasticsearch/reference/current/http-exporter-reference.html

host is a required setting for http exporters, which can take a few different forms as described in the table below.

But there is no "table below".

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch only, we do not handle closed source X-Pack here.

**Comment by ctindel** [comment]
Sorry you're right!
