### ISSUE TITLE
Any way to use MultiLine geometry with Context Suggester

### ISSUE THREAD

**Issue by ahmadazimi** [elastic/elasticsearch#27738]
Hi there,

is there any way to use MultiLine geometry with Context Suggester (geo location content) in v6?

**Comment by dnhatn** [comment]
@ahmadazimi,  Please ask questions on https://discuss.elastic.co where we can give you a better support. We use Github for bug reports and feature requests. Thank you.

**Comment by ahmadazimi** [comment]
@dnhatn Thank you for your hint,
I've already ask it there but nobody is answered it unfortunately.

https://discuss.elastic.co/t/context-suggester-with-multiline-geometry-as-geo-location-context/110924
