### ISSUE TITLE
Option to allow docvalue_fields of date types to return ms

### ISSUE THREAD

**Issue by awick** [elastic/elasticsearch#27740]
Prior to ES 6 docvalue_fields on dates returned ms, now it returns a formatted date.  Would be nice if that formatting could be specified, including allowing epoch_millis.

https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html
Says that "The first format will be used to convert the milliseconds-since-the-epoch value back into a string.", so maybe this is a bug and not a feature request, but it doesn't seem to work.

**Comment by awick** [comment]
Code to reproduce

```
curl -H "Content-type: application/json" -XPUT http://localhost:9200/bug27740 -d '
{
"settings" : { "number_of_shards" : 1 },
  "mappings" : {
    "type1" : {
      "properties" : {
        "field1" : {
          "type" : "date",
          "format" : "epoch_millis"
        }
      }
    }
  }
}'

curl -H "Content-type: application/json" http://localhost:9200/bug27740/type1/1 -d '{"field1": 10}'
curl http://localhost:9200/bug27740/_flush
curl 'http://localhost:9200/bug27740/_search?pretty&docvalue_fields=field1'
```

ES 5 results:
```
        "fields" : {
          "field1" : [
            10
          ]
        }
```

ES 6 results:
```
       "fields" : {
          "field1" : [
            "1970-01-01T00:00:00.010Z"
          ]
        }
```

**Comment by andyb-elastic** [comment]
@elastic/es-search-aggs
