### ISSUE TITLE
Allow `_doc` as a type name

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#27750]
As of 7.0, types support will be gone, the index API will be either `PUT index/_doc/id` or `POST index/_doc` and hits will use `_doc` as a fake type in the response. In order to allow users to have a smoother transition to 7.0, we should allow `_doc` as a type in 6.x.

Relates to #15613

**Comment by morphers82** [comment]
I have been naming my type the same as index, ie: PUT index_name/index_name/id
i don't think it should have to be anything specific or that will make many people's 6.0 indices not work with 7.0 if it has to be _doc.

**Comment by jpountz** [comment]
@morphers82 To clarify, this is not a requirement, this is just a way to potentially make the transition easier for users who decide to opt in for the type name that will be used in 7.0. 6.x indices will work in 7.0 regardless of the type name.

The benefit of switching to `_doc` earlier is that index APIs will work the same way on 6.x and 7.x indices: `PUT index/_doc/id` or `POST index/_doc`.
