### ISSUE TITLE
Get aliases for specific aliases returns all indices

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#27763]
I think the behavior specified in [`IndexAliasesIT#testIndicesGetAliases`](https://github.com/elastic/elasticsearch/blob/5b2ab96364335539affe99151546552423700f6e/core/src/test/java/org/elasticsearch/aliases/IndexAliasesIT.java#L571-L583) is wrong. Namely:
 - create indices foobar, test, test123, foobarbaz, bazbar
 - add an alias alias1 -> foobar
 - add an alias alias2 -> foobar
 - execute get aliases on the transport layer specifying alias1 as the only alias to get
 - the response includes foobar, test, test123, foobarbaz, bazbar albeit with empty alias metadata for all indices except foobar which contains alias1 only
 - previously the response would only contain foobar with alias metadata for alias1

This was a breaking change resulting from #25114, the specific change in behavior arising from a [change to MetaData](https://github.com/elastic/elasticsearch/commit/5b2ab96364335539affe99151546552423700f6e#diff-d6d141c41772a9088a29c2b838e5d8c4).

I am opening this personally considering it a bug but for discussion where we might decide to only document this behavior (not my preference, I think this behavior is weird and not intuitive).

Relates #27743

**Comment by dakrone** [comment]
It's worth noting that this only affects the transport layer. The REST layer doesn't include the extra indices. The transport layer should probably be changed to return only indices that contain the alias when an alias name is specified.

**Comment by jasontedor** [comment]
The transport client is exactly what this issue is being reported for.

**Comment by antitech** [comment]
@jasontedor @dakrone 
Yes Transport client got affected. Now we are explicitly filtering the indices which contains AliasMetaData. Its performance hit too for our application.  

In which release /version we can expect its fix.?

**Comment by dakrone** [comment]
> The transport client is exactly what this issue is being reported for.

Yes I understand, I was only clarifying for the sake of other people
reading.

**Comment by jasontedor** [comment]
> In which release /version we can expect its fix.?

Right now you can not have any expectation, no decision has been reached.

**Comment by s1monw** [comment]
+1

**Comment by jasontedor** [comment]
We discussed this in Fix-it-Friday and agree that this is a bug. Would you take care of this @dakrone.

**Comment by jasontedor** [comment]
@antitech I want to be clear that while we agree this is bug, it is not a high priority bug so there is no expectation about the timeline for a fix.

**Comment by antitech** [comment]
@jasontedor its ok. I'll apply any temporary fix for now . Just a request  can you please attach this bug with aliases tag.

**Comment by cyberstorm256** [comment]
+1

**Comment by martijnvg** [comment]
Reopening this issue, because a qa test failed in another project, in this case the aliases were being expanded (via AliasesRequest#aliases(...)) before arriving in the transport action.

**Comment by jasontedor** [comment]
@martijnvg Is it possible to resolve this issue?
