### ISSUE TITLE
Feature Request: Field collapsing on compound keys

### ISSUE THREAD

**Issue by EricMCornelius** [elastic/elasticsearch#27780]
At the moment, field collapsing is limited to single keyword or numeric fields with doc_values (https://github.com/elastic/elasticsearch/pull/22337#issuecomment-272250521).  This means any field collapsing requires foreknowledge of the unique keys which might be used to collapse data.

It would be extremely useful for adhoc data exploration purposes if this could be extended to allow for compound collapsing keys, and would make a much broader array of "SELECT DISTINCT" like functionality viable.

**Comment by jpountz** [comment]
> This means any field collapsing requires foreknowledge of the unique keys which might be used to collapse data.

This tends to be a common requirement for a search engine: documents must be modeled based on how they will be queried. I'm adding the `discuss` label so that it gets discussed in FixitFriday.

**Comment by jimczi** [comment]
We discussed in FixItFriday and decided that we don't want to support compound keys in field collapsing. You can use the `terms` aggregation with a script to achieve this, field collapsing is a special case to speed up `terms` aggregation when only the top hits need to be collapsed. If you are in a discovery mode then the `terms` aggregation has all the power to achieve what you need.
