### ISSUE TITLE
Completion suggestor not returning all options

### ISSUE THREAD

**Issue by carantunes** [elastic/elasticsearch#27785]
**Elasticsearch version** : 5.5.3

**Plugins installed**: []

**Description of the problem including expected versus actual behavior**:
When preserve_position_increments=true, results don't include suggestions for text not preffixed with the prefix.

Documentation says:

> **preserve_position_increments**
> Enables position increments, defaults to true. If disabled and using stopwords analyzer, you could get a field starting with The Beatles, if you suggest for b. Note: You could also achieve this by indexing two inputs, Beatles and The Beatles, no need to change a simple analyzer, if you are able to enrich your data.

**Steps to reproduce**:
```
PUT test
{
    "mappings": {
        "bands" : {
            "properties" : {
                "names": {
                  "type": "text",
                  "fields": {
                    "suggest": {
                      "type": "completion",
                      "analyzer": "english",
                      "preserve_position_increments": false
                    }
                  }
                }
            }
        }
    }
}

PUT test/bands/1
{"music": "The Beatles"}
              

GET test/_search
{
  "suggest": {
    "topics_suggest": {
      "completion": {
        "field": "names.suggest",
        "fuzzy": true
      },
      "prefix": "b"
    }
  }
}
```
Result from search:

```{
  "took": 5,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  },
  "suggest": {
    "topics_suggest": [
      {
        "text": "b",
        "offset": 0,
        "length": 1,
        "options": []
      }
    ]
  }
}
```

**Comment by jimczi** [comment]
It works fine if you use the correct field name in the document that you insert ;):

````
PUT test/bands/1
{"music": "The Beatles"}
````

Just replace `music` with `names` and it works as expected

**Comment by carantunes** [comment]
duh :/ so sorry!
