### ISSUE TITLE
feature request highlight support non string type

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/elasticsearch#27787]
**Describe the feature**:
A user asked for support for highlighting on non-string field such as IP data type.

**Elasticsearch version** (`bin/elasticsearch --version`):
es 6.x

**Description of the problem including expected versus actual behavior**:

Highlighting is limited to only string type currently.
It would be nice if it can be broadened to additional types such as IP data type.

**Comment by shinbero** [comment]
It'd be better highlighting is applied also when range-searching.

**Comment by markharwood** [comment]
Highlighters have parameters that relate to summarizing lengthy text into snippets which would not apply to structured fields.
Perhaps the [named queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-named-queries-and-filters.html) feature would provide sufficient feedback about what clauses matched?

**Comment by jimczi** [comment]
I agree with @markharwood , the named queries is a good solution for this and can be used without modifications. I am closing this issue because there is a good way to achieve the requested feature without modifying the highlighter.
