### ISSUE TITLE
Inconsistent getters for `shards_acknowledged`

### ISSUE THREAD

**Issue by olcbean** [elastic/elasticsearch#27784]
Several responses include the `shards_acknowledged` flag ( indicating whether the requisite number of shard copies started before the completion of the operation ) and there are two different getters used : `isShardsAcknowledged()` and `isShardsAcked()`

`public boolean isShardsAcknowledged()`
* OpenIndexClusterStateUpdateResponse
* OpenIndexResponse

`public boolean isShardsAcked()`
* CreateIndexClusterStateUpdateResponse
* RolloverResponse
* CreateIndexResponse

Should they be unified?

**Comment by cbuescher** [comment]
I think unifying this would be nice, but we need to keep the "other" version (whichever is kept) around as deprecated before we can remove it in one of the next major versions.

**Comment by olcbean** [comment]
@cbuescher can we remove it in 'this' major version (`7.0`) ? 
Or should I open a tracking issue : to be removed in `8.0` or later?

**Comment by cbuescher** [comment]
@olcbean I'd say its okay to remove in 7.0 since your other PR deprecated the methods in 6.2. Since it isn't a lot of work to just remove them, just open a PR against 7.0 and if it turns out somebody else thinks otherwise we can still open a tracking issue.
