### ISSUE TITLE
painless cannot parse escaped characters correctly

### ISSUE THREAD

**Issue by CJSoldier** [elastic/elasticsearch#27789]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):5.6.3

**Plugins installed**: [smartcn ]

**JVM version** (`java -version`): 
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
CentOS Linux release 7.2.1511 (Core)

**Steps to reproduce**:

 1. insert a new doc.
```
curl -XPUT 'http://192.168.40.106:9200/janusgraph_vertices/vertices/1111' -d '{ "Person_emailList":["aa@qq.com"] }'
```
 2.update multi value field via painless script.
```
curl -XPOST '192.168.40.106:9200/_bulk?pretty' -H 'Content-Type: application/json' -d'
{"update":{"_index":"janusgraph_vertices","_type":"vertices","_id":"1111"}}
{"script":{"source":"if(ctx._source[\"Person_emailList\"] == null){ctx._source[\"Person_emailList\"] = [];}ctx._source[\"Person_emailList\"].add(\"\\\"bb@qq.com\\t\");","lang":"painless"},"upsert":{"Person_emailList":["\"bb@qq.com\t"]}}
'
```

**Provide logs (if relevant)**:
```
{
  "took" : 94,
  "errors" : true,
  "items" : [
    {
      "update" : {
        "_index" : "janusgraph_vertices",
        "_type" : "vertices",
        "_id" : "1111",
        "status" : 400,
        "error" : {
          "type" : "illegal_argument_exception",
          "reason" : "failed to execute script",
          "caused_by" : {
            "type" : "script_exception",
            "reason" : "compile error",
            "script_stack" : [
              "... [\"Person_emailList\"].add(\"\\\"bb@qq.com\\t\");",
              "                             ^---- HERE"
            ],
            "script" : "if(ctx._source[\"Person_emailList\"] == null){ctx._source[\"Person_emailList\"] = [];}ctx._source[\"Person_emailList\"].add(\"\\\"bb@qq.com\\t\");",
            "lang" : "painless",
            "caused_by" : {
              "type" : "illegal_argument_exception",
              "reason" : "unexpected character [\"\\\"bb@qq.com\\t]. The only valid escape sequences in strings starting with [\"] are [\\\\] and [\\\"].",
              "caused_by" : {
                "type" : "lexer_no_viable_alt_exception",
                "reason" : null
              }
            }
          }
        }
      }
    }
  ]
}
```

**Comment by rjernst** [comment]
Painless does not have escape sequences really. As the error message explains, when inside a double quoted string, the only valid escapes are backslash and double quote. But your string has an escaped tab. All you should need to do is remove the double slash before `t`. Also note that you can use single quoted strings in painless to lessen the need for escaping json strings.

```
"source":"if(ctx._source['Person_emailList'] == null){ctx._source['Person_emailList'] = [];}ctx._source['Person_emailList'].add('\"bb@qq.com\t');"
```

In the future, please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports.

**Comment by jonnytest1** [comment]
easy fix : String.valueOf(<charcode>) ...

**Comment by bcouetil** [comment]
I tried `String.valueOf()` around my String with escapes, it does not help my Kibana Painless Lab handle this...
