### ISSUE TITLE
Elasticsearch 6.1.0 POM is referencing missing deps

### ISSUE THREAD

**Issue by r-tock** [elastic/elasticsearch#27806]
Looks like these artifacts are missing on maven central
```
Could not resolve all files for configuration ':compile'.
> Could not find org.elasticsearch:elasticsearch-cli:6.1.0.
  Searched in the following locations:
      file:/Users/robinanil/.m2/repository/org/elasticsearch/elasticsearch-cli/6.1.0/elasticsearch-cli-6.1.0.pom
      file:/Users/robinanil/.m2/repository/org/elasticsearch/elasticsearch-cli/6.1.0/elasticsearch-cli-6.1.0.jar
      https://repo1.maven.org/maven2/org/elasticsearch/elasticsearch-cli/6.1.0/elasticsearch-cli-6.1.0.pom
      https://repo1.maven.org/maven2/org/elasticsearch/elasticsearch-cli/6.1.0/elasticsearch-cli-6.1.0.jar
      file:/Users/robinanil/work/core/lib/elasticsearch-cli-6.1.0.jar
      file:/Users/robinanil/work/core/lib/elasticsearch-cli.jar
      http://dl.bintray.com/content/fullcontact/fullcontact-oss/org/elasticsearch/elasticsearch-cli/6.1.0/elasticsearch-cli-6.1.0.pom
      http://dl.bintray.com/content/fullcontact/fullcontact-oss/org/elasticsearch/elasticsearch-cli/6.1.0/elasticsearch-cli-6.1.0.jar
      http://repo.jenkins-ci.org/releases/org/elasticsearch/elasticsearch-cli/6.1.0/elasticsearch-cli-6.1.0.pom
      http://repo.jenkins-ci.org/releases/org/elasticsearch/elasticsearch-cli/6.1.0/elasticsearch-cli-6.1.0.jar
  Required by:
      project : > org.elasticsearch.client:elasticsearch-rest-high-level-client:6.1.0 > org.elasticsearch:elasticsearch:6.1.0
> Could not find org.elasticsearch.plugin:mapper-extras:6.1.0.
  Searched in the following locations:
      file:/Users/robinanil/.m2/repository/org/elasticsearch/plugin/mapper-extras/6.1.0/mapper-extras-6.1.0.pom
      file:/Users/robinanil/.m2/repository/org/elasticsearch/plugin/mapper-extras/6.1.0/mapper-extras-6.1.0.jar
      https://repo1.maven.org/maven2/org/elasticsearch/plugin/mapper-extras/6.1.0/mapper-extras-6.1.0.pom
      https://repo1.maven.org/maven2/org/elasticsearch/plugin/mapper-extras/6.1.0/mapper-extras-6.1.0.jar
      file:/Users/robinanil/work/core/lib/mapper-extras-6.1.0.jar
      file:/Users/robinanil/work/core/lib/mapper-extras.jar
      http://dl.bintray.com/content/fullcontact/fullcontact-oss/org/elasticsearch/plugin/mapper-extras/6.1.0/mapper-extras-6.1.0.pom
      http://dl.bintray.com/content/fullcontact/fullcontact-oss/org/elasticsearch/plugin/mapper-extras/6.1.0/mapper-extras-6.1.0.jar
      http://repo.jenkins-ci.org/releases/org/elasticsearch/plugin/mapper-extras/6.1.0/mapper-extras-6.1.0.pom
      http://repo.jenkins-ci.org/releases/org/elasticsearch/plugin/mapper-extras/6.1.0/mapper-extras-6.1.0.jar
  Required by:
      project : > org.elasticsearch.client:transport:6.1.0 > org.elasticsearch.plugin:percolator-client:6.1.0
```

**Comment by stephane-bastian** [comment]
confirmed the bug. elasticsearch-cli is not on mavencentral or jcenter

**Comment by Bouizi** [comment]
I'm having the same problem as well:
```
[WARNING] The POM for org.elasticsearch:elasticsearch-cli:jar:6.1.0 is missing, no dependency information available
[WARNING] The POM for org.elasticsearch.plugin:mapper-extras:jar:6.1.0 is missing, no dependency information available
```

**Comment by stephane-bastian** [comment]
I forgot to mention that as a temporary workaround, you can exclude the dependency as follow:

<dependency>
	<groupId>org.elasticsearch.client</groupId>
	<artifactId>elasticsearch-rest-high-level-client</artifactId>
	<version>${elasticsearch.version}</version>
	<exclusions>
		<exclusion>
			<groupId>org.elasticsearch</groupId>
			<artifactId>elasticsearch-cli</artifactId>
		</exclusion>
	</exclusions>
</dependency>

**Comment by r-tock** [comment]
Thanks, but that workaround is not enough for tests as our embedded elastic search dep, needs the following and fails

java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: org/elasticsearch/cli/UserException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)

**Comment by helloworldrta** [comment]
**Same problem:**

Failure to find org.elasticsearch:elasticsearch-cli:jar:6.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository

**Here's my solution:**

wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.0.tar.gz
tar xfz elasticsearch-6.1.0.tar.gz
cp /elasticsearch-6.1.0/lib/elasticsearch-6.1.0.jar /somepath/elasticsearch-6.1.0.jar

vi /path/to/pom.xml

> .......
> .......
>     <properties>
>         <elasticsearch.version>6.1.0</elasticsearch.version>
>         <lucene.version>7.1.0</lucene.version>
>     </properties>
> 
>     <dependencies>
>         <dependency>
>             <groupId>org.elasticsearch</groupId>
>             <artifactId>elasticsearch</artifactId>
>             <version>${elasticsearch.version}</version>
>             <scope>provided</scope>
>         </dependency>
> 
> 		
> 
> 		<dependency>
> 		  <groupId>org.elasticsearch</groupId>
> 		  <artifactId>elasticsearch-cli</artifactId>
> 		  <version>6.1.0</version>
> 		  <scope>system</scope>
> 		  <systemPath>/somepath/elasticsearch-cli-6.1.0.jar</systemPath>
> 		</dependency>
> 
> 		
> 
>         <dependency>
>             <groupId>org.apache.logging.log4j</groupId>
>             <artifactId>log4j-api</artifactId>
>             <version>2.9.1</version>
>             <scope>provided</scope>
>         </dependency>
> .....
> .....

**Comment by jasontedor** [comment]
We are working on this. We expect to have this fixed today. Sorry for the troubles.

**Comment by pangyikhei** [comment]
Also org.elasticsearch:cli:6.1.0 for org.elasticsearch.client:x-pack-transport:6.1.0 > org.elasticsearch.plugin:x-pack-api:6.1.0

**Comment by jasontedor** [comment]
An update on this issue: the missing elasticsearch-cli and mapper-extras are now available in Maven Central. We are working on some additional issues that we have identified during this process including the issue with the x-pack-transport POM referring to `org.elasticsearch:cli` (it should be `org.elasticsearch:elasticsearch-cli`). We will update again when we have this issue resolved.

**Comment by jasontedor** [comment]
We believe that all issues are resolved here. If you encounter additional issues with the Maven artifacts for 6.1.0, please open a new issue. Thanks for the initial report, and sorry again for the troubles.
