### ISSUE TITLE
Unknown settings are ignored inside custom analyzers

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#27814]
By accident I used `filters` to specify token filters inside a custom analyzer instead of `filter`:

```
PUT /test_index
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "my_analyzer": {
            "tokenizer": "whitespace",
            "filters": [
              "lowercase", "stop"
            ]
          }
        }
      }
    }
  }
}

GET /test_index/_analyze
{
  "analyzer": "my_analyzer",
  "text" : "to be or not to be"
}
```

The create index request succeeds and the analyze api happily analyzes the specified text with the `my_analyzer` analyzer, but without applying the token filters. The expected behaviour would be to that the create index api call fails.

Also any field inside the customer analyzer is currently allowed:

```
PUT /test_index
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "my_analyzer": {
            "tokenizer": "whitespace",
            "foo": "bar",
            "filter": [
              "lowercase", "stop"
            ]
          }
        }
      }
    }
  }
}
```

**Comment by liketic** [comment]
Hi @martijnvg , I'm trying to work on this. However, I think maybe this is a common issue, seems like the other `analyzer`s are also didn't validate the unknown settings.  Please correct me if I'm wrong. Thanks in advance.

**Comment by olcbean** [comment]
I read something similar few month back and after some searching I found #16451. Is this is a special case of it?
@martijnvg do you know if any work has been done in this area and this is one of the last pieces to be fixed? Or maybe the whole "package" is this up for grabs ;)

**Comment by mayya-sharipova** [comment]
I closing it in favour of #16451 

@liketic @olcbean  Nobody is working on #16451, please feel free to work on it, by indicating on github that you would like to work on this issue.
