### ISSUE TITLE
Kibana apt installation fails

### ISSUE THREAD

**Issue by moueza** [elastic/elasticsearch#27812]
**Elasticsearch version** (`bin/elasticsearch --version`):
1.7.5-1
**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux accula2 4.13.0-19-generic #22-Ubuntu SMP Mon Dec 4 11:58:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 17.10
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
sudo apt-get update && sudo apt-get install kibana

**Provide logs (if relevant)**:

Atteint:1 http://ppa.launchpad.net/ansible/ansible/ubuntu artful InRelease     
Atteint:2 http://fr.archive.ubuntu.com/ubuntu artful InRelease                 
Ign:3 http://dl.google.com/linux/chrome/deb stable InRelease                   
Atteint:4 http://security.ubuntu.com/ubuntu artful-security InRelease          
Atteint:5 http://fr.archive.ubuntu.com/ubuntu artful-updates InRelease         
Atteint:6 http://dl.google.com/linux/chrome/deb stable Release                 
Atteint:7 http://fr.archive.ubuntu.com/ubuntu artful-backports InRelease       
Ign:9 https://artifacts.elastic.co/packages/6.1/apt stable InRelease           
Err:10 https://artifacts.elastic.co/packages/6.1/apt stable Release
  404  Not Found [IP : 54.235.82.130 443]
Lecture des listes de paquets... Fait
E: The repository 'https://artifacts.elastic.co/packages/6.1/apt stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by colings86** [comment]
This issue list is for Elasticsearch issues and this seems to relate to Kibana. Also note that version 1.7.5 has been "End of Life" for quite a while now and is unsupported. If you are installing the Elastic stack I would suggest you install a recent, supported version. You can find instructions on installing the components of the Elastic stack at https://www.elastic.co/downloads.

Given this is not an issue with Elasticsearch I am going to close this. I would advise you to ask questions like this on the forums `https://discuss.elastic.co`.
