### ISSUE TITLE
Elasticsearch apt installation ambiguous

### ISSUE THREAD

**Issue by moueza** [elastic/elasticsearch#27813]
**Elasticsearch version** (`bin/elasticsearch --version`):
1.7.5-1
**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
**OS version** (`uname -a` if on a Unix-like system):
Linux accula2 4.13.0-19-generic #22-Ubuntu SMP Mon Dec 4 11:58:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 17.10
**Description of the problem including expected versus actual behavior**:
sudo apt-get install elasticsearch OK, but no elasticsearch word completion on console
**Steps to reproduce**:
sudo apt-get install elasticsearch 

**Provide logs (if relevant)**:

**Comment by jkakavas** [comment]
Hi @moueza , we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!
