### ISSUE TITLE
Test: randomValueOtherThan confusing with nulls

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#27821]
`ESTestCase#randomValueOtherThan` ignores nulls. This is it now:

```
    /**
     * helper to get a random value in a certain range that's different from the input
     */
    public static <T> T randomValueOtherThan(T input, Supplier<T> randomSupplier) {
        if (input != null) {
            return randomValueOtherThanMany(input::equals, randomSupplier);
        }

        return(randomSupplier.get());
    }
```

So if you pass in `null` it'll just run the supplier one time. I think this is confusing - if you pass in null it shouldn't return null. I think something like:

```
    /**
     * helper to get a random value in a certain range that's different from the input
     */
    public static <T> T randomValueOtherThan(T input, Supplier<T> randomSupplier) {
        return randomValueOtherThanMany(v -> Object.equals(input, v), randomSupplier);
    }
```

Would be better. Discuss?

**Comment by jasontedor** [comment]
+1, would you be willing to contribute a PR @nik9000? 😇

**Comment by nik9000** [comment]
> +1, would you be willing to contribute a PR @nik9000? 😇

Yes! I'll totally do it, but I wanted to get some buy in before I spent the time running all the tests. I have a sneaking suspicion that we rely on this behavior and I'll be spending an afternoon hunting down weird test failures after I do it.

**Comment by jasontedor** [comment]
I think it's a bug and we can move forward with the fix.

**Comment by jasontedor** [comment]
We discussed this in Fix-it-Friday and agreed to move forward with this change.

**Comment by nik9000** [comment]
I'll have a look next week.
