### ISSUE TITLE
filter on in elasticsearch-1.2.1 trigger the error below. How can i resolve this? i am new to elasticsearch

### ISSUE THREAD

**Issue by heinhtet123** [elastic/elasticsearch#27834]
[DEBUG][action.search.type       ] [Hobgoblin II] [product_catalogue][4], node[DKcHeBciTEmIBk6UsZuSTQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@79f7411] org.elasticsearch.search.SearchParseException: [product_catalogue][4]: query[ConstantScore(*:*)],from[-1],size[-1]: Parse Failure [Failed to parse source [{"query":{"match_all":[]},"filter":{"and":[{"geo_distance":{"distance":"20000miles","location":{"lat":"16.8390025","lon":"96.1522940"},"distance_type":"arc"}}]},"from":0,"size":52}]]

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by jasontedor** [comment]
Elasticsearch 1.2.1 is no longer supported.
