### ISSUE TITLE
Failure inserting document with explicit null in range field

### ISSUE THREAD

**Issue by presto9292** [elastic/elasticsearch#27845]
in 5.6.4 the last PUT statement fails, although it is equivalent to the previous insertions

`DELETE model_range_index`

`PUT model_range_index
{
  "mappings": {
    "my_type": {
      "properties": {
        "my_int": {
          "type": "integer"
        },
        "my_int_range": {
          "type": "integer_range"
        }
      }
    }
  }
}`

`PUT model_range_index/my_type/1
{
  "my_int": 7
}`

`PUT model_range_index/my_type/2
{
  "my_int": 7,
  "my_int_range": []
}`

`PUT model_range_index/my_type/3
{
  "my_int": 7,
  "my_int_range": null
}`

This is the error response:
```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "error parsing field [my_int_range], expected an object but got my_int_range"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse [my_int_range]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "error parsing field [my_int_range], expected an object but got my_int_range"
    }
  },
  "status": 400
}
```

**Comment by presto9292** [comment]
This is the error response

`{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "error parsing field [my_int_range], expected an object but got my_int_range"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse [my_int_range]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "error parsing field [my_int_range], expected an object but got my_int_range"
    }
  },
  "status": 400
}`

**Comment by jpountz** [comment]
Discussed in FixitFriday, agreed this is a bug. We should ignore nulls like we do eg. with numbers or geo points.
