### ISSUE TITLE
Unable to build the package in debian

### ISSUE THREAD

**Issue by raushanjha146** [elastic/elasticsearch#27857]
I downloaded the source from Debian snapshot. and tru to build the package using "dpkg-buildpackage".

I am unable to build the package. 
there was some errors in build process regarding jar files not availabe. 

**Elasticsearch version** (`bin/elasticsearch --version`): 1.7.5

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "1.8.0_151"

**OS version** (`uname -a` if on a Unix-like system): Linux raushan 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1. get the source from debian snapshot
dget http://snapshot.debian.org/archive/debian/20160520T171605Z/pool/main/e/elasticsearch/elasticsearch_1.7.5-1.dsc

 2. run "dpkg-buildpackage"

**Provide logs (if relevant)**:
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /data/elasticsearch-1.7.5/src/main/java/org/elasticsearch/common/xcontent/json/BaseJsonGenerator.java:[57,35] error: cannot find symbol
  symbol:   method writeValue()
  location: class JsonStreamContext
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.983 s
[INFO] Finished at: 2017-12-18T10:16:36+05:30
[INFO] Final Memory: 25M/913M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project elasticsearch: Compilation failure
[ERROR] /data/elasticsearch-1.7.5/src/main/java/org/elasticsearch/common/xcontent/json/BaseJsonGenerator.java:[57,35] error: cannot find symbol
[ERROR] symbol:   method writeValue()
[ERROR] location: class JsonStreamContext
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by dadoonet** [comment]
1.7 is not supported anymore.

**Comment by raushanjha146** [comment]
can you please provide me the latest version link(dsc file) for debian.
So I will build it from source for debian.

**Comment by dadoonet** [comment]
Please ask questions like this on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

But I'm unsure you will get help on a non maintained version though. You should update to at least 2.4, better 5.6, even better 6.1.

Thanks!
