### ISSUE TITLE
[CI] Sporadic failures of testRetentionPolicyChangeDuringRecovery

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#27861]
I see a couple of recent failures of `testRetentionPolicyChangeDuringRecovery`:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/1797/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/5410/console

Also the PR build of #27856:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/6288/console

Attempting to reproduce as advised yields success for me:

```
gradle :core:test -Dtests.seed=C56DDBF5A9AE3C38 -Dtests.class=org.elasticsearch.indices.recovery.RecoveryTests -Dtests.method="testRetentionPolicyChangeDuringRecovery" -Dtests.security.manager=true -Dtests.locale=sr-Latn-ME -Dtests.timezone=PRC
```

Possibly related to work that @dnhatn & @bleskes have been doing in this area? I have no failures of this before 2017-12-16 in my email archive.

**Comment by bleskes** [comment]
@dnhatn can you research please?

**Comment by DaveCTurner** [comment]
FWIW repeated runs on my laptop seem fine, but on my build machine it fails quite readily with that `REPRODUCE` line.

```
$ uname -a
Linux worker-772973 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dnhatn** [comment]
Thanks @DaveCTurner. This is reproducible; I will look into it.

**Comment by DaveCTurner** [comment]
I muted this test in b26cc36928 - please could you unmute it as part of the fix?

**Comment by dnhatn** [comment]
Another instance on 6.x https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=debian/434/console

**Comment by dnhatn** [comment]
I've unmuted the test on 6.x: https://github.com/elastic/elasticsearch/commit/81e420d47f9bbb1f4f5d320ecb7613dae82d9707, master: https://github.com/elastic/elasticsearch/commit/7e3dc122fd88fec2b2aaca53e01956f05e10013c
