### ISSUE TITLE
AbstractQueryBuilder.declareStandardFields should be protected?

### ISSUE THREAD

**Issue by nomoa** [elastic/elasticsearch#27865]
In #25948 some static methods in AbstractQueryBuilder had their visibility reduced to package private.
One of them is declareStandardFields, this method was quite useful and I don't get why it's no longer accessible outside the elastic package?
The printBoostAndQueryName is still accessible from plugins that declare new queries and thus I don't get why this method was hidden.

Would it make sense to change it back to protected or are there other reasons to hide such logic?

Thanks!

**Comment by colings86** [comment]
@nomoa thanks for raising this. I agree that the method could be useful for custom query plugins to access. Maybe @cbuescher know why we made it package private and/or has an opinion on whether we should allow custom queries to access it?

**Comment by cbuescher** [comment]
@nomoa @colings86 I agree that this could be useful, too. I think it was changed to package private in  #25948 because we generally try to tighten visibility but didn't consider use in plugins, or we thought implementations of AbstractQueryBuilder might be able to use the same package as we do.
