### ISSUE TITLE
[Docs] Rolling upgrade use "transient" instead "persistent" for disabling shard allocation 

### ISSUE THREAD

**Issue by johtani** [elastic/elasticsearch#27860]
https://www.elastic.co/guide/en/elasticsearch/reference/6.1/rolling-upgrades.html

In Rolling upgrades document, the sample request of step 1. uses `persistent` for enabling shard allocation, but the sample request for 7. reenabling shard allocation uses `transient`.

If a user restart cluster after upgrading, elasticsearch can not allocate shards any more...
The sample request for 1. has to use `transient`.

This change happened after 6.0, we shared the documentation between rolling upgrade and full cluster restart.

**Comment by jasontedor** [comment]
Duplicates #27677
