### ISSUE TITLE
Bug: When using Highlight and copy_to in combination with no_match_size

### ISSUE THREAD

**Issue by aslamy** [elastic/elasticsearch#27873]
I have:

```
PUT my_index
{
  "mappings": {
    "my_type": {
      "properties": {
        "first_name": {
          "type": "text",
          "copy_to": "full_name" 
        },
        "last_name": {
          "type": "text",
          "copy_to": "full_name" 
        },
         "age": {
          "type": "integer"

        },
        "full_name": {
        "store": true,
          "type": "text"
        }
      }
    }
  }
}
```
```
PUT my_index/my_type/1
{
  "first_name": "John",
  "last_name": "Smith",
  "age": 22
}

```
My search:
```
{  
   "query":{  
      "match":{  
         "age":22
      }
   },
   "highlight":{  
      "require_field_match":false,
      "fields":{  
         "full_name":{  
            "fragment_size":100,
            "number_of_fragments":3,
            "no_match_size":100
         }
      }
   }
}
```
Search result:
```
{  
   "took":2,
   "timed_out":false,
   "_shards":{  
      "total":5,
      "successful":5,
      "skipped":0,
      "failed":0
   },
   "hits":{  
      "total":1,
      "max_score":1,
      "hits":[  
         {  
            "_index":"test",
            "_type":"my_type",
            "_id":"i5wAa2ABlX9GxTORskk2",
            "_score":1,
            "_source":{  
               "first_name":"John",
               "last_name":"Smith",
               "age":22
            },
            "highlight":{  
               "full_name":[  
                  "John"
               ]
            }
         }
      ]
   }
}
```
Problem: 
I use copy_to to copy multi-field to one field. Why do I only get "John"?  I think this is a bug and  I should get "John Smith" or [ "John", "Smith"] .
I have tested this on Elasticsearch 5.5.0 and 6.1.
```[tasklist]
### Tasks
```

**Comment by aslamy** [comment]
More related bug:
If I have this mapping instead (just added "term_vector": "with_positions_offsets"):
```
PUT my_index
{
  "mappings": {
    "my_type": {
      "properties": {
        "first_name": {
          "type": "text",
          "copy_to": "full_name" 
        },
        "last_name": {
          "type": "text",
          "copy_to": "full_name" 
        },
         "age": {
          "type": "integer"

        },
        "full_name": {
        "store": true,
	"term_vector": "with_positions_offsets",
          "type": "text"
        }
      }
    }
  }
}
```
My Search :
```
{  
   "query":{  
      "match":{  
         "age":22
      }
   },
   "highlight":{  
      "require_field_match":false,
      "fields":{  
         "full_name":{  
            "fragment_size":100,
            "number_of_fragments":3,
            "no_match_size":100
         }
      }
   }
}
```
Result:
```
{  
   "took":1,
   "timed_out":false,
   "_shards":{  
      "total":5,
      "successful":5,
      "skipped":0,
      "failed":0
   },
   "hits":{  
      "total":1,
      "max_score":1.0,
      "hits":[  
         {  
            "_index":"test",
            "_type":"my_type",
            "_id":"i5wAa2ABlX9GxTORskk2",
            "_score":1.0,
            "_source":{  
               "first_name":"John",
               "last_name":"Smith",
               "age":22
            }
         }
      ]
   }
}
```
Nothing highlights. But if I decrement no_match_size to 5 then only "Johan" will appears.
New Search:
```
{  
   "query":{  
      "match":{  
         "age":22
      }
   },
   "highlight":{  
      "require_field_match":false,
      "fields":{  
         "full_name":{  
            "fragment_size":100,
            "number_of_fragments":3,
            "no_match_size":5
         }
      }
   }
}
```
Result: 
```
{  
   "took":0,
   "timed_out":false,
   "_shards":{  
      "total":5,
      "successful":5,
      "skipped":0,
      "failed":0
   },
   "hits":{  
      "total":1,
      "max_score":1.0,
      "hits":[  
         {  
            "_index":"test",
            "_type":"my_type",
            "_id":"i5wAa2ABlX9GxTORskk2",
            "_score":1.0,
            "_source":{  
               "first_name":"John",
               "last_name":"Smith",
               "age":22
            },
            "highlight":{  
               "full_name":[  
                  "John"
               ]
            }
         }
      ]
   }
}
```

**Comment by Kalle12345** [comment]
Hi!
Any updates on this issue?  I also have the same problem. When will this bug fix?
Thanks in advance

**Comment by jimczi** [comment]
Sorry for the late reply. `no_match_size` only checks the first value in a multi-valued field, the `copy_to` creates one value per field so it is expected. Though the `fvh` highlighter has a bug when `no_match_size` is greater than the size of the first value in the field, in such case this highlighter will ignore this option. The `unified` highlighter is able to use the `terms_vector` to perform highlighting and is not affected by this bug. The `fvh` highlighter should be deprecated soon so you should switch to this new highlighter (`unified`)  that is already the default in 6x. 
Regarding the issue with `no_match_size` that only selects the first value, I'll leave this issue open and will work on a fix later. For the reason explained above, I don't plan to fix the `fvh` highlighter but only the `unified`.

**Comment by aslamy** [comment]
Hi ! 
I have big amount of text to highlight. I read that fvh highlighter is the fastest highlighter, especially when it comes to a large amount of data. So you mean when it come to performance both fvh and unified highlighter has now same performance ?

**Comment by Kalle12345** [comment]
> Regarding the issue with no_match_size that only selects the first value, I'll leave this issue open and will work on a fix later. For the reason explained above, I don't plan to fix the fvh highlighter but only the unified

@jimczi I discovered it's not only unified highlighter that no_match_size chooses only the first value, even plain highlighter has this issue. Would you work on a fix for both the highlighters?

I will happily wait for a fix for this problem. Thanks in advance

**Comment by jimczi** [comment]
cc @elastic/es-search-aggs

**Comment by mayya-sharipova** [comment]
Closing this in favour of a similar issue: https://github.com/elastic/elasticsearch/issues/7416 to return all array values.
