### ISSUE TITLE
[CI] Sporadic failures in testGetStartingSeqNo

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#27890]
I see a handful of failures of `testGetStartingSeqNo` recently.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1043/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/5422/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+java9-periodic/5119/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/1440/console

I have been unable to reproduce this sort of thing locally after repeated attempts:

    while (gradle :core:test -Dtests.seed=A55AC848F5232BA9   -Dtests.class=org.elasticsearch.indices.recovery.PeerRecoveryTargetServiceTests   -Dtests.method="testGetStartingSeqNo"   -Dtests.security.manager=true   -Dtests.locale=hi-IN   -Dtests.timezone=Asia/Famagusta  > test.log); do date; done

I will suppress this test with an `@AwaitsFix` for now.

**Comment by DaveCTurner** [comment]
The exception (from the first job listed) was as follows.

```
  2> REPRODUCE WITH: gradle :core:test -Dtests.seed=7910CE866B54A317 -Dtests.class=org.elasticsearch.indices.recovery.PeerRecoveryTargetServiceTests -Dtests.method="testGetStartingSeqNo" -Dtests.security.manager=true -Dtests.locale=sq-AL -Dtests.timezone=SystemV/CST6CDT
  1> [2017-12-18T14:05:06,196][INFO ][o.e.i.r.PeerRecoveryTargetServiceTests] [testGetStartingSeqNo]: before test
  1> [2017-12-18T14:05:06,309][WARN ][o.e.i.s.IndexShard       ] [XgzrQnZkUw] [index][0] no index mapper found for field: [_id] returning default postings format
  1> [2017-12-18T14:05:06,345][INFO ][o.e.i.r.PeerRecoveryTargetServiceTests] [testGetStartingSeqNo]: after test
FAILURE 0.16s J2 | PeerRecoveryTargetServiceTests.testGetStartingSeqNo <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <1L>
   >      but: was <5L>
   > 	at __randomizedtesting.SeedInfo.seed([7910CE866B54A317:CC44EB0E093CA20A]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.indices.recovery.PeerRecoveryTargetServiceTests.testGetStartingSeqNo(PeerRecoveryTargetServiceTests.java:95)
  2> NOTE: leaving temporary files on disk at: /var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/core/build/testrun/test/J2/temp/org.elasticsearch.indices.recovery.PeerRecoveryTargetServiceTests_7910CE866B54A317-001
   > 	at java.lang.Thread.run(Thread.java:748)
  2> NOTE: test params are: codec=Asserting(Lucene70): {}, docValues:{}, maxPointsInLeafNode=1089, maxMBSortInHeap=5.673251968705639, sim=RandomSimilarity(queryNorm=true): {}, locale=sq-AL, timezone=SystemV/CST6CDT
```

**Comment by dnhatn** [comment]
Thanks @DaveCTurner. This tests is fixed in https://github.com/elastic/elasticsearch/commit/e9a3932dbce9bbc3d9e216a5c239aadfddef930a
