### ISSUE TITLE
Include index name in Term/Phrase Suggester results

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#27903]
Say you have two different indices with the same configuration, and you want to suggest across them:

```
PUT test1
{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "analysis": {
        "analyzer": {
          "trigram": {
            "type": "custom",
            "tokenizer": "standard",
            "filter": [
              "lowercase"
            ]
          },
          "reverse": {
            "type": "custom",
            "tokenizer": "standard",
            "filter": [
              "standard",
              "reverse"
            ]
          },
          "shingleAnalyzer": {
            "filter": [
              "lowercase"
            ],
            "type": "custom",
            "tokenizer": "standard"
          }
        }
      }
    }
  },
  "mappings": {
    "test": {
      "properties": {
        "phrasesuggest": {
          "type": "text",
          "fields": {
            "trigram": {
              "type": "text",
              "analyzer": "trigram"
            },
            "reverse": {
              "type": "text",
              "analyzer": "reverse"
            }
          }
        }
      }
    }
  }
}

PUT test2
{
  "settings": {
    "index": {
      "number_of_shards": 1,
      "analysis": {
        "analyzer": {
          "trigram": {
            "type": "custom",
            "tokenizer": "standard",
            "filter": [
              "lowercase"
            ]
          },
          "reverse": {
            "type": "custom",
            "tokenizer": "standard",
            "filter": [
              "standard",
              "reverse"
            ]
          },
          "shingleAnalyzer": {
            "filter": [
              "lowercase"
            ],
            "type": "custom",
            "tokenizer": "standard"
          }
        }
      }
    }
  },
  "mappings": {
    "test": {
      "properties": {
        "phrasesuggest": {
          "type": "text",
          "fields": {
            "trigram": {
              "type": "text",
              "analyzer": "trigram"
            },
            "reverse": {
              "type": "text",
              "analyzer": "reverse"
            }
          }
        }
      }
    }
  }
}


POST test1/test?refresh=true
{
  "phrasesuggest": "noble warriors"
}

POST test2/test?refresh=true
{
  "phrasesuggest": "nobel prize"
}

GET test*/_search
{
  "suggest": {
    "text": "noble prize",
    "simple_phrase": {
      "phrase": {
        "field": "phrasesuggest.trigram",
        "size": 1,
        "gram_size": 3,
        "direct_generator": [ {
          "field": "phrasesuggest.trigram",
          "suggest_mode": "always"
        } ],
        "highlight": {
          "pre_tag": "<em>",
          "post_tag": "</em>"
        }
      }
    }
  }
}
```

Then in the results you just get a single result but you don't know which index holds your suggestion:

```
{
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 2,
    "successful": 2,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  },
  "suggest": {
    "simple_phrase": [
      {
        "text": "noble prize",
        "offset": 0,
        "length": 11,
        "options": [
          {
            "text": "nobel prize",
            "highlighted": "<em>nobel</em> prize",
            "score": 0.32654536
          }
        ]
      }
    ]
  }
}
```

For example, if you have a single index per "Project" and you want to suggest a specific field and then you want to know which "Project" holds that suggestion, you need to make a query per index and then check the results.

My proposal here is to **include the _index field as part of the suggest result** so you know which index is returning that suggestion.

**Comment by gmoskovicz** [comment]
CC @jimczi as we discussed this.

**Comment by colings86** [comment]
We discussed this in FixItFriday and wanted to ask the following:

Could you explain why is it necessary to know the index the suggestion came from? When running suggest you are asking Elasticsearch for suggested search terms across a set of shards to give the user a hint on what to search for so I don't see why it matter which index that suggestion is derived from?

We think, instead you should use the _msearch API to issue a suggest request to each index if you want  the results separated per index.

**Comment by gmoskovicz** [comment]
>Could you explain why is it necessary to know the index the suggestion came from? When running suggest you are asking Elasticsearch for suggested search terms across a set of shards to give the user a hint on what to search for so I don't see why it matter which index that suggestion is derived from?

@colings86 imagine you have `N` projects under your account, and you have a search box where you want to type something, and show not only the suggestion but also which project that suggestion is coming from. And of course, say we have a single index per project (for example in a legal use case). I think that this isn't possible without either doing an msearch across each one of the projects, from where you need to know first the index names (all the projects that you have access).

This could be very easy if we have a way to return the suggestion along with the index that it was found.

**Comment by colings86** [comment]
But my question is, why is it useful to show the project the suggestion is coming from? What you have asked of Elasticsearch is "given this context of data (shards/indexes/query), give me some suggestions on what I can search for given what I have already typed". So you are supplying the context of data you want the suggestions in and therefore I think its correct that we should merge equivalent suggestions from different indexes in the same way as we should merge equivalent suggestions from the different shards in the same index. We do this for aggregations which is similar in that you are asking for an aggregated view of the data over multiple shards. 

If you care about separating suggestions by index (or even be some other criteria on the documents e.g. a project field) then personally I think this should be done with multiple suggest calls using the _msearch API and targetting each request in the _msearch with the correct index/query/etc.

**Comment by gmoskovicz** [comment]
> If you care about separating suggestions by index (or even be some other criteria on the documents e.g. a project field) then personally I think this should be done with multiple suggest calls using the _msearch API and targetting each request in the _msearch with the correct index/query/etc.

Sounds good. Thanks!
