### ISSUE TITLE
Add update values to indices stats

### ISSUE THREAD

**Issue by kertal** [elastic/elasticsearch#27913]
Currently there are no statistic available for updates in the [indices stats](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html) request

so currently the following stats for indices are available

```
     "indexing" : {
        "index_total" : 69556331,
        "index_time_in_millis" : 26503314,
        "index_current" : 0,
        "index_failed" : 0,
        "delete_total" : 0,
        "delete_time_in_millis" : 0,
        "delete_current" : 0,
        "noop_update_total" : 0,
        "is_throttled" : false,
        "throttle_time_in_millis" : 0
      },
```
would be nice to have e.g. "**update_total**" && "**update_time_in_millis**".

**Comment by pickypg** [comment]
Just FYI @kertal, incase you are unaware, updates are actually deletes + index operations under the hood.

**Comment by s1monw** [comment]
> Just FYI @kertal, incase you are unaware, updates are actually deletes + index operations under the hood.

that is true but it's not the deletes you see here. I think, @kertal correct me if I am wrong you are interested in how many [_update](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html) calls the shard receives, correct? Or are you interested in how many documents have a version != 1?

**Comment by kertal** [comment]
@pickypg 
yes, i know, each update combines a delete + index operations
@s1monw 
i'd be interested in both numbers (correct me, when i'm doing an upsert, initially, there's no delete op, all following updates will also result in an delete op, right?).

**Comment by s1monw** [comment]
so you are saying you really want to know how often we didn't only append a document but also deleted. ie. called IndexWriter#updateDocument? @kertal can you explain what the usecase is here? the stats might be accurate since we might retry a document in some situations

**Comment by kertal** [comment]
merry xmas, and thanks for the awesome software you're building!
 
in the application i'm building i ran into issues with update performance

https://discuss.elastic.co/t/update-performance-very-low-indexing-rate/103183

sadly i could no longer update this discussion to describe the solution i've found

so in short, i've got a summary record in ES that was updated by every SIP signaling message), which caused poor performance. I've been fixing that by using the logstash aggregate plugin, which increased the performance (10x in some cases). However, i still had the issue in situations with very high message frequency. I've build a little bash script, telling me, how much new records were appended, some more metrics, etc. Then i also wanted the number of updates, that was the point when i went to discuss.elastic.co

i'm fine with the solutions we discussed here:
https://discuss.elastic.co/t/update-stats/110667/7

however, i think it would be nice to have the update/upsert metrics in the stats, maybe it would also help other people finding possible bottlenecks.

in my case, i know the final solution, already built a Prove of concept version. I'm using logstash to forward the signaling messages to a redis store, i'm using an external script to get this messages, aggregate them, query and update existing summary records, send these records the ES. This solution doubled the performance as far as i can see (and it's only single threaded at the moment), and i haven't discovered a possible bottleneck so far

**Comment by bleskes** [comment]
We talked about it in FixedIt friday and the consensus was that indices stats (which are a sum of shard level stats) are supposed to give you insight into the current state of the Engine. From the Engine perspective there is no update, just a "reindex" which counts as index. As Simon pointed out, one can derive a reindex from the total doc count compared to the doc count. We don't see how it's possible to add a reliable update counter. I'm going to close this for now. Feel free to comment if you have any questions.
