### ISSUE TITLE
 java rest client use compressed head, return error message garbled

### ISSUE THREAD

**Issue by maphey** [elastic/elasticsearch#27937]
elasticsearch client version : 5.5.3

**Comment by colings86** [comment]
Please can you provide details of the problem you are seeing here. Raising an issue with only a title doesn't provide enough information to help you. Some examples of things you could provide: the request that you are sending to Elasticsearch, your Java REST client code snippet, the error you receive, any other details that would help explain what you are seeing vs. what you would expect to see.

**Comment by javanna** [comment]
Closing for lack of feedback. @maphey please submit the info that we requested in the comment above and we will certainly look at this. Based on the title of the issue only, we cannot decipher what the problem is.
