### ISSUE TITLE
Search nestedField score

### ISSUE THREAD

**Issue by hilalbursali** [elastic/elasticsearch#27944]
I have an index and there is an nested field in it: 
  ` "user" : [
    {
    "name" : "Alice Dave"
   }
  ]`

  ` "user" : [
    {
    "name" : "Alice Smith"
   },
     {
    "name" : "John"
   }
  ]`

Although, they have one "Alice", the second one's score is higher because of the docCount. I could not omit norms. Is there any way to make their score same?

**Comment by jkakavas** [comment]
Hi @hilalbursali, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!
