### ISSUE TITLE
[CI] Java 10 missing javadoc jar

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#27961]
Java docs were disabled for the Java 10 build in https://github.com/elastic/elasticsearch/commit/d4f914be2a43db785182c0fbbc9dc03572d96b4d

However the aggs-matrix-stats module expects its javadoc jar file to be present:

```
java.nio.file.NoSuchFileException: /var/lib/jenkins/workspace/elastic+elasticsearch+master+java10-periodic/modules/aggs-matrix-stats/build/distributions/aggs-matrix-stats-7.0.0-alpha1-SNAPSHOT-javadoc.jar
```

**Comment by jasontedor** [comment]
I opened #27962.
