### ISSUE TITLE
ES V1.7 Thread Pool Document Is Incomplete 

### ISSUE THREAD

**Issue by wuyirutgers** [elastic/elasticsearch#27969]
**Elasticsearch version** (`bin/elasticsearch --version`): 
1.7

**Description of the problem including expected versus actual behavior**:
The model of 'SCALING' thread pool is not provided
https://www.elastic.co/guide/en/elasticsearch/reference/1.7/modules-threadpool.html

**Steps to reproduce**:
 1. Go to https://www.elastic.co/guide/en/elasticsearch/reference/1.7/modules-threadpool.html
 2. The document says 'snapshot' thread pool in default to 'SCALING' type
 3. There is no example of the configurable parameter of 'SCALING' thread pool

I try to look up the parameters of 'SCALING' thread pool from other versions, but it looks like it has different interface  in 2.1 and 6.1. I am not sure what is the 'SCALING' thread pool parameters in 1.7

**Comment by DaveCTurner** [comment]
Elasticsearch 1.7 reached [end of life](https://www.elastic.co/support/eol) nearly a year ago, so we are no longer updating its documentation. Please upgrade to a supported version and try again.
