### ISSUE TITLE
how to apply filter in computed field used script in elaticsearch

### ISSUE THREAD

**Issue by EasonYan** [elastic/elasticsearch#27978]
My use case  is to filter in my computed field used script field,is there any way  I can reuse the script field definition in order to apply "terms query" in the "bool" ?

`{
  "query": {
    "bool": {
      "must": [
        {
          "script": {
            "script": {"inline":"def monthyear =doc['GoUpDate'].date.year + '-' + doc['GoUpDate'].date.monthOfYear;
                int flag= 0;
                for(int i =0;i<params.enums.length;i++){
                    if(params.enums[i]==monthyear)
                        {
                            flag=1;
                            break;
                        }
                };return flag
            ","lang":"painless",
                "params":{"enums":["2015-1","2015-2"]}
            }
          }
        }
      ]
    }
  }, 
  "script_fields": {
    "test1": {
      "script": {
        "lang": "painless", 
        "inline": "doc['GoUpDate'].date.year + '-' + doc['GoUpDate'].date.monthOfYear "
      }
    }
  }
}`

**Comment by softwaredoug** [comment]
FYI this is best asked at the discussion boards http://discuss.elastic.co. These issues are for filing bugs or feature requests

**Comment by dnhatn** [comment]
@EasonYan,  Please ask questions on https://discuss.elastic.co where we can give you a better support. We use Github for bug reports and feature requests. Thank you.

**Comment by EasonYan** [comment]
@dnhatn @softwaredoug thanks!
