### ISSUE TITLE
UpdateRequest need toString()

### ISSUE THREAD

**Issue by zzt93** [elastic/elasticsearch#27986]
**Describe the feature**:
When using the Java API to do the update/index/delete, I log the request for debug. But the `UpdateRequest` not implemented the `toString()` method, which causes some inconvenience.

**Comment by DaveCTurner** [comment]
Thanks for the report. This does seem to be the case. It shouldn't be too hard to add this - would you care to submit a PR?

**Comment by cybrooke** [comment]
I would like to do this as my first contribution if @zzt93 doesn't want to.

**Comment by DaveCTurner** [comment]
Go for it, @cybrooke.

**Comment by zzt93** [comment]
@cybrooke Actually I implement a version, which suits my need. Anyway, it's up to @DaveCTurner  to decide which one to use.

**Comment by DaveCTurner** [comment]
I reviewed and left comments on both PRs. I think #27997 is the way to go. Thanks both, and apologies for the race that led to the duplicated effort.
