### ISSUE TITLE
Not able to execute "./gradlew build" command.

### ISSUE THREAD

**Issue by PJozeph** [elastic/elasticsearch#27988]
After forking the repo and clone it, I would like to build it but not able to perform it. Even when i want to import project into IntelliJ it says for this project gradle is not configured. I dont't understand this.
![elastic](https://user-images.githubusercontent.com/23094656/34355726-f1c9f606-ea37-11e7-9d6f-825f11381c3a.png)
 
![elasticcmd](https://user-images.githubusercontent.com/23094656/34355774-54e77a9c-ea38-11e7-88ec-c470818fe671.png)

**Comment by jpountz** [comment]
We currently do not use the gradle wrapper, see #13744 for more background. You can generate idea configuration by running `gradle idea`.

**Comment by PJozeph** [comment]
thanks, unfortunately #13744 did not lead me lead me closer how to build up working environment. Where can I find it's documentation ?
