### ISSUE TITLE
[Doc] ignore_above default value is wrong.

### ISSUE THREAD

**Issue by AlJuan** [elastic/elasticsearch#27992]
**Elasticsearch version** (`bin/elasticsearch --version`): Version: 6.1.1, Build: bd92e7f/2017-12-17T20:23:25.338Z, JVM: 1.8.0_151

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): Linux pmitn009906 4.4.0-41-generic #61-Ubuntu SMP Tue Sep 27 17:27:48 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: When i create a new index, the keyword mapping ignore_above defaults to 256. The doc says the default is 2147483647.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. First create an index:
`
curl -XPUT 'localhost:9200/test?pretty' -H 'Content-Type: application/json' -d'
{
    "settings" : {
        "index" : {
        }
    }
}'
`
 2. Then insert some value:
`
curl -XPUT 'localhost:9200/test/testType/1?pretty' -H 'Content-Type: application/json' -d'
{
    "user" : "kimchy",
    "post_date" : "2009-11-15T14:12:12",
    "message" : "trying out Elasticsearch"
}
'
`
 3. When I get the mapping info for that index (curl -XGET 'localhost:9200/test/_mapping/testType?pretty') it returns:
```
{
  "test" : {
    "mappings" : {
      "testType" : {
        "properties" : {
          "message" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "post_date" : {
            "type" : "date"
          },
          "user" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          }
        }
      }
    }
  }
}
```
In addition to this, there is a [blog post](https://www.elastic.co/blog/strings-are-dead-long-live-strings) by Adrien Grand saying that the default ignore_above value is 256.

**Comment by DaveCTurner** [comment]
I think the change proposed in #27991 seemed like the right thing to do, and I'm not sure why it was closed. WDYT @jpountz?

**Comment by jpountz** [comment]
I guess the confusion comes from the fact that there are multiple defaults:
 - `ignore_above` has a default value of 2^31-1 on `keyword` fields. If you create a `keyword` field without providing an explicit value for `ignore_above`, this is the value that will be taken into account.
 - The default dynamic mappings for strings set up a keyword field that has `ignore_above: 256`.

By the way, the reason why `ignore_above` is explicit on the `GET _mapping` call is because it doesn't have the default value. Otherwise it would have been omitted.

**Comment by AlJuan** [comment]
Like @jpountz said, I created an index:
```
curl -XPUT 'localhost:9200/test?pretty' -H 'Content-Type: application/json' -d'
{
  "mappings": {
    "testType": { 
      "properties": { 
        "someField":    { "type": "keyword"  }        
      }
    }
  }
}
'
```
Now the `ignore_above` field is not explicit on the `GET _mapping`. The values I inserted on the `someField`  field are indexed, even if they are longer than 256.

Should I close this issue?

**Comment by jiangjunjian** [comment]
org.springframework.dao.InvalidDataAccessApiUsageException: Document contains at least one immense term in field="detailContent" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped. Please correct the analyzer to not produce such terms.
