### ISSUE TITLE
TOO MANY CORRUPT CHECKSUMS

### ISSUE THREAD

**Issue by morphers82** [elastic/elasticsearch#28003]
I have been using 1.7.1 for 2 years with not a single one of these errors.
Now, switching to 6.0 I get one seems like once a day now, shards are getting "corrupted" and i have to delete them.  what gives?

                  "caused_by": {
                    "type": "corrupt_index_exception",
                    "reason": """checksum failed (hardware problem?) : expected=62db3f44 actual=d7729342 (resource=BufferedChecksumIndexInput(MMapIndexInput(path="/data/elasticsearch/nodes/0/indices/_hfkct4BT

**Comment by jasontedor** [comment]
The checksum protections are stronger in 2.x (inherited to 5.x and 6.x) than they are in 1.x. It’s likely your hardware is bad and you never knew. We do not treat this as a bug. If you need help, please use the [forum](https://discuss.elastic.co).

**Comment by morphers82** [comment]
What if I don't care if a few docs in the shard are bad?

**Comment by morphers82** [comment]
Also, why does it just completely negate the entire shard?  why isn't their a way to fix it instead?  i don't think one single file in a shard's lucene files being corrupt should make it completely done for.

**Comment by tvernum** [comment]
@morphers82 All of those are questions that you can and should ask on [our discussion forum](https://discuss.elastic.co/c/elasticsearch).

**Comment by morphers82** [comment]
I'm asking because it seems to me that there are none of these options, which is why i am asking here because this seems to be an issue that is just brushed to the side.

**Comment by morphers82** [comment]
so have tried to add zfs raidz2 as underlying device for datastore.  the zfs catches checksum failure, but elastic also has checksum failure.  so annoying!!!!
