### ISSUE TITLE
cluster.routing.allocation.enable and cluster.routing.rebalance.enable should be lowercase

### ISSUE THREAD

**Issue by tomsommer** [elastic/elasticsearch#28007]
According to the documentation, the values of `cluster.routing.rebalance.enable` and `cluster.routing.allocation.enable` are lowercase, however the defaults in the code are uppercase,

Ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/shards-allocation.html

**Comment by danielmitterdorfer** [comment]
Thanks for the report. Your observation is correct and we should change the documentation that these values should be specified in uppercase.

Note that whatever casing you specify, these values always [get converted to uppercase internally](https://github.com/elastic/elasticsearch/blob/8085ec5/core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/EnableAllocationDecider.java#L223).

I've also updated the title to reflect that.

**Comment by ywelsch** [comment]
I prefer them to be lower cased (in the docs, as well as the implementation). I find it odd that the setting is auto-converted to uppercase (i.e. a different value is stored than what was provided by the user). For other deciders, we have taken different approaches to parsing. For example, for `cluster.routing.allocation.allow_rebalance` we store the value that the user provided, but are lenient w.r.t. lower-/upper-casing :

https://github.com/elastic/elasticsearch/blob/8085ec504b9909980bc1e73b0b95d4b71d8ef7e2/core/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ClusterRebalanceAllocationDecider.java#L76

**Comment by tomsommer** [comment]
I agree with @ywelsch, everything else appears to be lowercase.

**Comment by danielmitterdorfer** [comment]
Fine for me as well @ywelsch (I just checked the current behavior). I'll adjust the title then once more.
