### ISSUE TITLE
Elasticsearch service fails to start

### ISSUE THREAD

**Issue by ShilpiRachna** [elastic/elasticsearch#28015]
We are using Elasticsearch version 5.4.1 on Windows 10.
We have an automation process that does the following:
1. Installs Java at a known location (JAVA_HOME is always defined in System environment variable)
2. Install Elasticsearch using "elasticsearch-service.bat install"
Output:
[Info @12:06:16.709] Installing service : "elasticsearch-service-x64"
[Info @12:06:16.709] Using JAVA_HOME (64-bit): "C:\Program Files\Java\jre1.8.0_151"
[Info @12:06:16.709] The service 'elasticsearch-service-x64' has been installed.

3. Start Elasticsearch using "elasticsearch-service.bat start"
It fails with the following error:
_2017-12-26 12:06:18 Commons Daemon procrun stderr initialized
The data area passed to a system call is too small.
Failed to start service_

I read that the issue can be caused by JAVA_HOME environment variable not being defined as a System variable. I have verified that it is set correctly. In fact, the issue occurs even if JAVA_HOME is correctly set even before running the automation and we install JAVA at the specified location.
**However, the issue does not repro if Java is already installed.**

Also, verified that heap size is set correctly in the JVM.options.

This issue is intermittent. What else should I check / do to fix this issue?

**Comment by danielmitterdorfer** [comment]
Hi @ShilpiRachna, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). Also, please do not open an issue simultaneously to a Discuss topic (this topic is already discussed in https://discuss.elastic.co/t/elasticsearch-service-fails-to-start/113470).
