### ISSUE TITLE
StringTerms.Bucket.getKeyAsNumber should detect integers

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#28012]
Currently it parses the string as a double, meaning it might lose accuracy if the value is an long which is greater than 2^52. We should try to detect whether the string represents a long or a double first.

**Comment by Chaycej** [comment]
I'll look into this issue.

**Comment by tehgoju** [comment]
@Chaycej are you planning to resolve this issue? If not, I'm willing to do this. :)

**Comment by matarrese** [comment]
If someone is already working on this please ignore my pull request otherwise let me know your thoughts!

**Comment by adityasrini** [comment]
The PR and issue seem to be open and @matarrese has indicated that he's open to others working on it, so I'll try to find a solution to this. Let me know if more contributors for this issue are not necessary!
