### ISSUE TITLE
How to connect elasticsearch and sentry

### ISSUE THREAD

**Issue by gr-jialeiwang** [elastic/elasticsearch#28021]
I am using getsentry/onpremise version 8.22.0. 
I used docker to install sentry on my local MacBook.
And i installed elasticsearch by docker on my local MacBook too.
Elasticsearch's image is docker.elastic.co/elasticsearch/elasticsearch:5.4.1.

I am using log4j2 to config elasticsearch logging.

Now, i want to connect elasticsearch to sentry, the thing i want to do is,
When elasticsearch receive an error data, then automatically push this data to Sentry.

I do not know how to setting elasticsearch,
Is there someone can tell me how to do this?

PS:
I found something like [this](https://stackoverflow.com/questions/34894776/using-sentry-logging-with-elasticsearch)
It seems too old.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
