### ISSUE TITLE
Documentation for elasticsearch-keystore

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#28020]
We added an Elasticsearch Keystore in order to be able to easily manage settings in a secured way: https://github.com/elastic/elasticsearch/issues/22475.

It would be great to document what settings we currently Support (if not all of the settings are supported).

**Comment by gmoskovicz** [comment]
CC @rjernst

**Comment by rjernst** [comment]
The settings are already documented, inline within the documentation for the parts of the system that use it. For example, in [GCS configuration of the service account file](https://www.elastic.co/guide/en/elasticsearch/plugins/master/repository-gcs-usage.html#repository-gcs-using-service-account).

**Comment by danielmitterdorfer** [comment]
Closing as this is already documented as indicated by Ryan in https://github.com/elastic/elasticsearch/issues/28020#issuecomment-354862722.
