### ISSUE TITLE
[CI] DiscountedCumulativeGainTests fails on ARM architecture

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#28048]
The `DiscountedCumulativeGainTests.testDCGAt()`, `testDCGAtSixMissingRatings` and `testDCGAtFourMoreRatings` tests failed on ARM architecture: 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+arm/853

The execution log is [consoleText.txt](https://github.com/elastic/elasticsearch/files/1597872/consoleText.txt)

**Comment by cbuescher** [comment]
@tlrx thanks, it looks like the allowed rounding error in the test needs to be increased slightly in order to pass the tests on ARM. I will push a fix shortly.

**Comment by cbuescher** [comment]
Closed via 8925dab
