### ISSUE TITLE
elasticsearch-spend-all-time-in-build-scorer

### ISSUE THREAD

**Issue by holygost** [elastic/elasticsearch#28043]
I use ES 5.5.0，and I have the same problem, detail as follow:

https://stackoverflow.com/questions/47885899/elasticsearch-spend-all-time-in-build-scorer

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
