### ISSUE TITLE
Significant text - Nested Object support

### ISSUE THREAD

**Issue by arkkanoid** [elastic/elasticsearch#28050]
I'm trying the Significant Text feature on nested objects, but I get 0 items inside the buckets array.
```{
  "hits": { 
    "total": 215,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "result": {
      "doc_count": 3025,
      "my_sample": {
        "doc_count": 3025,
        "keywords": {
          "doc_count": 3025,
          "bg_count": 9705720,
          "buckets": []
        }
      }
    }
  }
```

BUT, if I make a post as a no-nested object it works...
```
    "aggregations" : {
        "my_sample" : {
            "sampler" : {
                "shard_size" : 1000
            },
            "aggregations": {
                "keywords" : {
                    "significant_text" : { "field" : "data.jobs.description" }
                }
            }
        }
    }
```

The mapping is correct, if I try significant_terms with another term inside the nested object it works as I expected. 

My mapping:
```
          "data": {
            "properties": {
              "jobs": {
                "type": "nested",
                "properties": {
                  "applicants": {
                    "type": "long"
                  },
                  "created_at": {
                    "type": "date"
                  },
                  "description": {
                    "type": "text"
                  },...
```

**Comment by cbuescher** [comment]
@arkkanoid thanks for raising this. 
Looking at the [original issue](https://github.com/elastic/elasticsearch/issues/23674) that introduced this, nested objects are not supported initially and apparently are challenging to implement. I will mark this as a feature request but given the assumed complexity probably unlikely to be implemented soon. 
I will also add a note to the docs that should clarify this.

**Comment by polyfractal** [comment]
@elastic/es-search-aggs

**Comment by wchaparro** [comment]
Closing as not planned.
