### ISSUE TITLE
Debian Installation

### ISSUE THREAD

**Issue by jenslink** [elastic/elasticsearch#28064]
I can't install logstash using the following the instructions:

https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html

When running apt-get update I get 

_Failed to fetch https://artifacts.elastic.co/packages/6.x/apt/dists/stable/InRelease  FailReason: ConnectionRefused__

Note: My test server is IPv6 only but artifacts.elastic.co has several AAAA records so that should be no problem.

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
