### ISSUE TITLE
Debian Installation

### ISSUE THREAD

**Issue by jenslink** [elastic/elasticsearch#28066]
**I think the following problem is either a bug in the documentation or a problem with the server.**

I can't install logstash using the following the instructions:

https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html

When running apt-get update I get

_Failed to fetch https://artifacts.elastic.co/packages/6.x/apt/dists/stable/InRelease FailReason: ConnectionRefused__

Note: My test server is IPv6 only but artifacts.elastic.co has several AAAA records so that should be no problem.

**Comment by dnhatn** [comment]
@jenslink Please do not open an issue multiple times. You already opened this at https://github.com/elastic/elasticsearch/issues/28064

**Comment by jenslink** [comment]
Yes and it was closed. If you don't want problem reports just say so.
