### ISSUE TITLE
Loss of mapping information after blackout

### ISSUE THREAD

**Issue by wzgdxg** [elastic/elasticsearch#28075]
# **Before power outage：**
`"properties": {
"submitTime": {
"index": "not_analyzed",
"store": true,
"type": "string"
},
"sourceIp": {
"index": "not_analyzed",
"store": true,
"type": "string"
},
"tenantId": {
"index": "not_analyzed",
"store": true,
"type": "string"
},
"details": {
"store": true,
"type": "string"
},
"logId": {
"index": "not_analyzed",
"type": "string"
},
"source": {
"index": "not_analyzed",
"store": true,
"type": "string"
},
"behaviourType": {
"index": "not_analyzed",
"store": true,
"type": "string"
},
"userId": {
"index": "not_analyzed",
"store": true,
"type": "string"
},
"email": {
"store": true,
"type": "string"
},
"realname": {
"store": true,
"type": "string"
},
"status": {
"store": true,
"type": "string"
}
}`

# **After power outage：**
`"properties": {
"submitTime": {
"type": "string"
},
"sourceIp": {
"type": "string"
},
"tenantId": {
"type": "string"
},
"details": {
"type": "string"
},
"logId": {
"type": "string"
},
"source": {
"type": "string"
},
"behaviourType": {
"type": "string"
},
"userId": {
"type": "string"
},
"email": {
"type": "string"
},
"realname": {
"type": "string"
},
"status": {
"type": "string"
}
}`

False information after starting：
`Mapper for [details] conflicts with existing mapping in other types`

**Comment by ywelsch** [comment]
Can you provide more info, for example ES version? Is there anything in the logs that could indicate a failure to write the cluster state to disk? Is minimum_master_nodes properly configured?

**Comment by colings86** [comment]
No further feedback. If you have the requested information please add a comment and we can look into reopening the issue
