### ISSUE TITLE
Query using script

### ISSUE THREAD

**Issue by hubiao1** [elastic/elasticsearch#28074]
Fielddata is disabled on text fields by default. Set fielddata=true on [textSimHash_sore] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.

**Comment by colings86** [comment]
This does not seem to be a bug report or a feature request. We reserve Github for bug reports and feature requests only. If this is a question please ask it in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead and provide more details of what you are trying to do. Thank you!
