### ISSUE TITLE
How can I highlight not only child but parent？

### ISSUE THREAD

**Issue by yangxiaolei100** [elastic/elasticsearch#28072]
`{
  "sort": [
    {
      "SHOW": "desc"
    }
  ],
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "should": [
              {
                "multi_match": {
                  "minimum_should_match": "100%",
                  "query": "男",
                  "fields": [
                    "abo_blood_type.uni",
                    "rh_blood_type.uni",
                    "name.uni",
                    "nation_name.uni",
                    "gender.uni",
                    "inpatient_no_id.uni"
                  ]
                }
              },
              {
                "has_child": {
                  "query": {
                    "multi_match": {
                      "minimum_should_match": "100%",
                      "query": "男",
                      "fields": [
                        "radio_inpatient_id_no.uni",
                        "radio_diag",
                        "radio_serial_num.uni",
                        "radio_m_stage.uni",
                        "radio_t_stage.uni",
                        "patient_id.uni",
                        "radio_gender.uni",
                        "radio_visit_type.uni",
                        "radio_name.uni",
                        "radio_n_stage.uni",
                        "inpatient_no_id.uni"
                      ]
                    }
                  },
                  "inner_hits": {
                    "highlight": {
                      "fields": {
                        "*": {}
                      }
                    }
                  },
                  "type": "radio_basicinfo"
                }
              }
            ]
          }
        },
        {
          "terms": {
            "_cache": "true",
            "patient_sn.uni": [
              "2dbb4e41598e8359b7336f223fb61225",
              "3f98cd569faf15903bd8e536857d7c49",
              "66894793f1d8e7eef0209d1463d6175e",
              "771892ea5842e2e7e433e24ea2e7058d",
              "923a1ce91ed0cf0f3e0ceb2513ea82e7",
              "9720a779d278a58d8ff5a0d2f0cb71f7",
              "d27ae596048225b7e8c0fae813b63346",
              "d963f251fec3bbb97dd90afc2c1247cf",
              "e3b4fd807c7f2c4c4f14ada0af58e809",
              "f80d30d5e100e3a73d9a01c8348a1bb1"
            ]
          }
        }
      ]
    }
  }
}`

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
