### ISSUE TITLE
Support index specific parameters when multi-index searching

### ISSUE THREAD

**Issue by scottsom** [elastic/elasticsearch#28087]
Today, most of the _search parameters can only be specified at the request level. However, in some situations, it may be desirable to have different values per index for the same search request.

For example, suppose I have two indexes - `index_with_routing` and `index_without_routing`. On the client side, I know which routing values go with which index. Let's say I am routing documents by user and all of the data for user_id=1 is going into `index_without_routing` and all the other users are going into `index_with_routing`. This is similar idea to the [One Big User](https://www.elastic.co/guide/en/elasticsearch/guide/current/one-big-user.html).

Now I want to get the top results for a query against user_id=1 and user_id=2. The search for user_id=1 should go to `index_without_routing` without the routing parameter and the search for user_id=2 should go to `index_with_routing` with the routing parameter. To do this, I can either run each search independently and perform the reduce phase from the client side (greatly increasing my client complexity) or run the search without custom routing (negating the benefits of custom routing). Neither approach is desirable.

One way to avoid this is to add support for index -> routing mappings in the request like this:

```javascript
POST /index_with_routing,index_without_routing/_search
{
  "query": {
    "terms": {
      "user_id": [1,2]
    }
  },
  "routing": [
    { "index_with_routing": "2" }
  ]
}
```

Now the request will execute against all shards in `index_without_routing` and against the shard(s) that `2` is associated with in `index_with_routing`.

However, this is very similar to how [index boosting](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-index-boost.html) looks, so another approach and the feature I'd like to propose is to generalize this pattern into a new parameter like `index_overrides`. As is the case with boosting, this can use aliases and wildcards.

```javascript
POST /index_with_routing,index_without_routing/_search
{
  "query": {
    "terms": {
      "user_id": [1,2]
    }
  },
  "index_overrides": [
    {
      "index_with_routing": {
        "routing": "2",
        "boost": 1.4,
        // ... other parameters
      }
    },
    {
      "index_without_routing": {
        "boost": 1.3,
        // ... other parameters
      }
    }
  ]
}
```

As future extensions, other parameters that have use cases for index specific values could also be exposed here (e.g. preference, timeouts, etc.).

**Comment by jpountz** [comment]
We discussed it in FixitFriday and agreed to close it for now as it sounds like a rare use-case to us. We might reconsider if we find more compelling use-cases for this feature.
