### ISSUE TITLE
elasticsearch Intermittent slow query

### ISSUE THREAD

**Issue by jnercy** [elastic/elasticsearch#28097]
Online environment Documents: 394.9k Data: 242.9 MB of elasticsearch-version:5.4.0
There will be a few full queries every hour, and the following is a slow query
`
took[615.1ms], took_millis[615], types[driverAsso], stats[], search_type[QUERY_THEN_FETCH], total_shards[5], source[{"size":0,"query":{"term":{"_id":{"value":"97230938609757053:97230938609757073","boost":1.0}}}}],
`
![image](https://user-images.githubusercontent.com/16145081/34599628-5ebbd1aa-f22e-11e7-995b-3ad23d669de8.png)
![image](https://user-images.githubusercontent.com/16145081/34599641-6ce5b8ae-f22e-11e7-8c02-b82dcd4c8036.png)
![image](https://user-images.githubusercontent.com/16145081/34599668-9332c1f0-f22e-11e7-84ae-0732c6a75117.png)
Please help to analyze the reasons. Thank you

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
