### ISSUE TITLE
a little misleading about TransportStatus.isRequest()

### ISSUE THREAD

**Issue by kkewwei** [elastic/elasticsearch#28091]
https://github.com/elastic/elasticsearch/blob/7cdbae2da8311d2d2eac1eba84a3964f434b8714/core/src/main/java/org/elasticsearch/transport/TransportStatus.java#L29

we know that is STATUS_REQRES=1, if value is 1,we regard it as a request,but the code says 
    public static boolean isRequest(byte value) {
        return (value & STATUS_REQRES) == 0;
    }
I think it to be this:
   public static boolean isRequest(byte value) {
        return (value & STATUS_REQRES) != 0;
    }

**Comment by ywelsch** [comment]
> if value is 1,we regard it as a request

no, it's the exact opposite.

Look at `setRequest`, which clears the first bit, or `setResponse`, which sets the first bit.
