### ISSUE TITLE
使用elasticsearch 5.5.3版本中的Bulk方式发送数据，发生死锁

### ISSUE THREAD

**Issue by hqch0708** [elastic/elasticsearch#28090]
在spark中使用elasticsearch 5.5.3版本的客户端，多task操作Bulk写数据时，其中一个task发送死锁。
代码：
```java
BulkRequestBuilder bulkRequest = client.prepareBulk();
bulkRequest.request().setRefreshPolicy(WriteRequest.RefreshPolicy.IMMEDIATE);
for (FMEyeChainLog log : logList) {
    //通过add批量添加
    bulkRequest.add(client.prepareIndex(getIndexName(indexName, date), indexType).setSource(getXContentBuilderByChain(log)));
}
BulkResponse bulkResponse = bulkRequest.execute().actionGet();
//如果失败
if (bulkResponse.hasFailures()) {
    // process failures by iterating through each bulk response item
    System.out.println("buildFailureMessage:" + bulkResponse.buildFailureMessage());
}
```

异常线程堆栈：

Thread ID | Thread Name | Thread State | Thread Locks
-- | -- | -- | --
102 | Executor task launch worker-1 | WAITING | Lock(java.util.concurrent.ThreadPoolExecutor$Worker@1595623431})

sun.misc.Unsafe.park(Native Method) java.util.concurrent.locks.LockSupport.park(LockSupport.java:175) java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836) java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997) java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304) org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:248) org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:91) org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:42) com.dazong.eye.analysis.repository.elasticsearch.ElasticsearchRepository.saveChain(ElasticsearchRepository.java:183) com.dazong.eye.analysis.repository.elasticsearch.ElasticsearchRepository.saveChainByBatch(ElasticsearchRepository.java:150) com.dazong.eye.analysis.repository.elasticsearch.ElasticsearchRepository.saveToES(ElasticsearchRepository.java:118) com.dazong.eye.analysis.core.SparkChainAndLog4Kafka$2$1.call(SparkChainAndLog4Kafka.java:198) com.dazong.eye.analysis.core.SparkChainAndLog4Kafka$2$1.call(SparkChainAndLog4Kafka.java:141) org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartitionAsync$1.apply(JavaRDDLike.scala:741) org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartitionAsync$1.apply(JavaRDDLike.scala:741) org.apache.spark.SparkContext$$anonfun$34.apply(SparkContext.scala:2021) org.apache.spark.SparkContext$$anonfun$34.apply(SparkContext.scala:2021) org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87) org.apache.spark.scheduler.Task.run(Task.scala:99) org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282) java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) java.lang.Thread.run(Thread.java:745)

**Comment by tvernum** [comment]
_Courtesy of Google Translate_:

In spark use elasticsearch 5.5.3 version of the client, multi-task operation Bulk write data, one of the task to send a deadlock.
Code:

```java
BulkRequestBuilder bulkRequest = client.prepareBulk();
bulkRequest.request().setRefreshPolicy(WriteRequest.RefreshPolicy.IMMEDIATE);
for (FMEyeChainLog log : logList) {
     // added by add batch
    bulkRequest.add(client.prepareIndex(getIndexName(indexName, date), indexType).setSource(getXContentBuilderByChain(log)));
}
BulkResponse bulkResponse = bulkRequest.execute().actionGet();
// if it fails
if (bulkResponse.hasFailures()) {
    // process failures by iterating through each bulk response item
    System.out.println("buildFailureMessage:" + bulkResponse.buildFailureMessage());
}
```


Abnormal thread stack:

Thread ID | Thread Name | Thread State | Thread Locks
-- | -- | -- | --
102 | Executor task launch worker-1 | WAITING | Lock(java.util.concurrent.ThreadPoolExecutor$Worker@1595623431})


sun.misc.Unsafe.park(Native Method) java.util.concurrent.locks.LockSupport.park(LockSupport.java:175) java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836) java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997) java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304) org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:248) org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:91) org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:42) com.dazong.eye.analysis.repository.elasticsearch.ElasticsearchRepository.saveChain(ElasticsearchRepository.java:183) com.dazong.eye.analysis.repository.elasticsearch.ElasticsearchRepository.saveChainByBatch(ElasticsearchRepository.java:150) com.dazong.eye.analysis.repository.elasticsearch.ElasticsearchRepository.saveToES(ElasticsearchRepository.java:118) com.dazong.eye.analysis.core.SparkChainAndLog4Kafka$2$1.call(SparkChainAndLog4Kafka.java:198) com.dazong.eye.analysis.core.SparkChainAndLog4Kafka$2$1.call(SparkChainAndLog4Kafka.java:141) org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartitionAsync$1.apply(JavaRDDLike.scala:741) org.apache.spark.api.java.JavaRDDLike$$anonfun$foreachPartitionAsync$1.apply(JavaRDDLike.scala:741) org.apache.spark.SparkContext$$anonfun$34.apply(SparkContext.scala:2021) org.apache.spark.SparkContext$$anonfun$34.apply(SparkContext.scala:2021) org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87) org.apache.spark.scheduler.Task.run(Task.scala:99) org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282) java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) java.lang.Thread.run(Thread.java:745)
