### ISSUE TITLE
there is some parts that were confused about gradle in the doc

### ISSUE THREAD

**Issue by llilyy** [elastic/elasticsearch#28094]
I wanted to contribute to the elasticsearch so I was following the document `CONTRIBUTING.md`.
I found some parts that were confused about gradle.
Recently, the gradle wrapper added and mention about gradle version removed in `CONTRIBUTING.md`. 
Here is it.

> Elasticsearch uses the Gradle wrapper for its build. You can execute Gradle using the wrapper via the gradlew script in the root of the repository.

This mean looks like that you can use the `gradle` command if you have run the `gradlew` script.
And after all the example commands use `gradle` command like this.

> Eclipse users can automatically configure their IDE: `gradle eclipse` then.....

But, If you use gradle wrapper for starting task, you must use `./gradlew <task>` in the root of the repository.
So I think we need to 
- add gradle version that needs to build ES 
or 
- add some detail explanation
or
- edit `gradle` -> `gradlew`
etc...

If you do not mind, I want to make it my first commit.
thanks!

**Comment by colings86** [comment]
@llilyy Thanks for pointing this out, I agree that I think this is something that was missed in the documentation when adding the grade wrapper. I think we will probably want to go with the third option:

> edit gradle -> gradlew

Feel free to submit a PR to update the `CONTRIBUTING.md` file.

/cc @jasontedor as he might have a different opinion

**Comment by jasontedor** [comment]
@colings86 I agree with your proposal.

**Comment by jasontedor** [comment]
Closed by #28103
