### ISSUE TITLE
Elastic search environment getting zen-disco-receive error

### ISSUE THREAD

**Issue by rangarajanm** [elastic/elasticsearch#28108]
Hi,

 Were facing  Zen-disco-receive error often in our environment, this results in dropping our different data nodes each time and cluster goes down. At this point indexer will be out for an hour. Our system is hosted in Azure, followed the recommendation. We did profile on the Network, CPU, Memory, Disk R/W  did both healthy time vs unhealthy time doesn't seem anomaly. Attaching the error here for reference of master, data nodes.  

I really appreciate any help or pointer to resolve this error will be great.

[ESClusterError.txt](https://github.com/elastic/elasticsearch/files/1607543/ESClusterError.txt)

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
