### ISSUE TITLE
Supporting dot product via Painless scripting

### ISSUE THREAD

**Issue by adamhadani** [elastic/elasticsearch#28109]
We've been experimenting with implementing a custom dot product based relevancy scoring formula that could help us greatly in combination with the standard Elasticsearch features (specifically, it will be very useful for us to use it in combination with the rescore functionality to only rescore top K results).

### Feature suggestion

TLDR - It will be very useful to be able to pass a Painless inline script a `param` which is essentially a vector (E.g. of floats), and have it perform the dot product of that vector with previously stored vectors associated with the various documents to be scored, and use the result of this dot product as the relevancy score. This is a very general framework which can be used to express a lot of domain-specific logic, so seems like a feature of general interest (Notably, cosine similarity is a particular instance of such a dot product when the vectors are all normalized to have unit norm).

A couple of specific notes:
* Existing solutions involve either a custom plugin (which does not seem to support newer ES versions), or have some pretty severe limitations. See references below.
* Ideally, It should be possible for an inline script to also use a combination of such dot products, i.e have each document be associated with multiple vectors at index time, and then be able to pass in multiple vectors as `params` to the script and have the script compute the score as a weighted combination of multiple dot products, e.g something like `params['weight_a'] * doc['vector_a'].dot(params['vector_a']) + params['weight_b'] * doc['vector_b'].dot(params['vector_b'])`

### References

* ES Plugin for dot products - https://github.com/MLnick/elasticsearch-vector-scoring
* Existing ways of simulating this with Painless and their drawbacks -
 https://stackoverflow.com/a/43836510

**Comment by rjernst** [comment]
> a custom plugin (which does not seem to support newer ES versions)

Why do you think a custom plugin will not work with newer ES versions?

This has less to do with painless itself, and more to do with docvalues. I don't think we should add anything like the "dot" method suggested here. This is a very advanced use case and exactly why we suggest custom script engines for advanced cases. /cc @jpountz for his thoughts.

**Comment by adamhadani** [comment]
@rjernst, thanks for responding so promptly, I'll try to clarify a bit:

1) I didn't mean to suggest a custom plugin will not work with newer ES versions period, just that the particular one I linked to wouldn't as is. I also get that its possible to just write new plugins to achieve this, but i'm specifically suggesting that a dot product / cosine similarity type of operation is general enough to be useful across many contexts, so that it will be useful to have more native support for something like this using inline scripting, without having to resort to writing elaborate custom code that needs to be bundled into the server deployment.

Added benefit here which is equally important for eng. organizations is that AWS ES doesn't currently support arbitrary plugins + there is non-trivial overhead of maintaining plugins that need to be compiled/bundled into service vs. a script that can be tweaked on the fly as it is provided along with the query.

2) Vectorized operations on most modern architectures can be executed very efficiently which makes it compelling to delegate the dot product to the server to execute, which is one motivation for introducing an explicit dot operator vs. just writing an explicit for loop that iterates through individual components and multiplies them / sums the results. Syntax-wise or in terms of supporting a schema type that makes representing a vector for sake of such an operator is of course something that can be debated to large extent

**Comment by jpountz** [comment]
Can you give concrete examples of things that you would like to do with this vector product? Scripting may or may not be the right tool depending on what you want to achieve. For instance I suspect implementing image similarity or a machine-learned scoring algorithm might require different solutions, even if both problems boil down to a dot product in the end. In addition to concrete examples, I'd be curious to know:
 - whether vectors are expected to be dense or sparse
 - how many dimensions do you expect to need?

For the record, we already have a way to run dot products: the `bool` query. If you have 3 sub queries that produce scores sA, sB and sC on a given document, then boosting each of these queries with bA, bB and bC and putting them as `SHOULD` clauses of a `bool` query is effectively going to produce the dot product of [sA, sB, sC] and [bA, bB, bC] as a score. I'm not saying this is necessarily the right tool for the job, this is just to give some perspective. Using the `bool` query comes with a number of benefits like very efficient consumption of sparse clauses. We are also working on optimizing the retrieval of top-scoring hits, so if your use-case can be expressed with a `bool` query, it could that Elasticsearch would be able to efficiently compute the top matches efficiently in the future, without resorting to computing the dot product on every match.

**Comment by adamhadani** [comment]
@jpountz -

My current use case involves sparse vectors with dimensionality on the order of a few hundred dimensions. More specifically, typical number of non-zero entries  is expected to be << 100.

I suspect for a lot of use cases vectors could be expected to be one-hot encoded or integers, although for my current use case they can be floats in general.

Is this something that sounds like it can fit into your suggestion of using `bool` sub-queries? I'm not sure since we are talking about potentially tens or hundreds of 'components'..

**Comment by jdconrad** [comment]
@jpountz Please re-assign this issue if it's not appropriate for you to own.

**Comment by rjernst** [comment]
We discussed this internally and agreed adding this functionality into the server is not something we want to do. This fits much better as a community plugin (like the one linked in the opening comment). Note that this function could now also be added via a [custom function in painless](https://github.com/elastic/elasticsearch/tree/master/plugins/examples/painless-whitelist) which is provided by a server plugin, but called like any normal painless method.

**Comment by seperman** [comment]
I know you have closed down this issue but I am with adamhadani that this is pretty standard math. I don't know how to write ES plugins and probably will just do it in Python then instead. :(

**Comment by yaronp68** [comment]
@jpountz can we label this `7.3` ?
