### ISSUE TITLE
Docs: Are there outdated APIs (e.g., AggregatorBuilder) in Java API docs?

### ISSUE THREAD

**Issue by saleese** [elastic/elasticsearch#28114]
I am checking the APIs in Java API docs, and I found outdated APIs. I hope some contributors may confirm whether the followings are outdated or not:

1. "AggregatorBuilder" should be replaced by "AggregationBuilder" in https://www.elastic.co/guide/en/elasticsearch/client/java-api/master/_bucket_aggregations.html

	> Ip Range Aggregationedit
	> Here is how you can use Ip Range Aggregation with Java API.

	> Prepare aggregation requestedit
	> Here is an example on how to create the aggregation request:

	> AggregatorBuilder<?> aggregation =...

	> Note that you could also use ip masks as ranges:

	> AggregatorBuilder<?> aggregation =...

2. "GeoBoundsBuilder" may be replaced by "GeoBoundsAggregationBuilder" in https://www.elastic.co/guide/en/elasticsearch/client/java-api/master/_metrics_aggregations.html#java-aggs-metrics-geobounds

	> Geo Bounds Aggregationedit
	> Here is how you can use Geo Bounds Aggregation with Java API.

	> Prepare aggregation requestedit
	> Here is an example on how to create the aggregation request:

	> GeoBoundsBuilder aggregation =
    >	    GeoBoundsAggregationBuilder...

3. PutIndexedScriptResponse, GetIndexedScriptResponse, and DeleteIndexedScriptResponse are outdated in https://www.elastic.co/guide/en/elasticsearch/client/java-api/master/indexed-scripts.html

	PutIndexedScriptResponse = client.preparePutIndexedScript()...

	GetIndexedScriptResponse = client.prepareGetIndexedScript()...

	DeleteIndexedScriptResponse = client.prepareDeleteIndexedScript()...

**Comment by danielmitterdorfer** [comment]
Thanks for the report @saleese! You are right indeed. The first two are leftovers from #18377, the third item is a leftover from #17650.

For the first two items, the replacements that you mention are correct. 

For the third item, the replacements are `*IndexedScript*` -> `*StoredScript*` (e.g. `PutIndexedScriptResponse` -> `PutStoredScriptResponse`, `client.preparePutIndexedScript()` -> `client.preparePutStoredScript()`).

Given that these two cover unrelated (functional) areas in the docs, I think it makes sense to create two more focussed tickets and close this one.

**Comment by danielmitterdorfer** [comment]
I've raised #28143 and #28144 as more concrete follow-up tickets and hence close this one now. Thanks for reporting it!
