### ISSUE TITLE
More Like This Query documentation - remove reference to "ids" and "like_text" parameter 

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#28128]
A user on the discuss forums [reported](https://discuss.elastic.co/t/more-like-this-documentation/114477/2) that MLT had deprecated `ids` and `like_text` params but not removed them from the docs following their removal from the codebase.
I tried these params in 6.0 and it does look like docs diverge from code at this point.

The API now only takes a single `like` parameter which either accepts a string (the equivalent behaviour  of the old `like_text`) or an array of objects with index, type and id settings to identify individual docs (the equivalent of the old `ids` setting). Valid examples below:

	GET kaleida/article/_search
	{
	  "query": {
		"more_like_this": {
		  "fields": [
			"headline"
		  ],
		  "like": [
			{
			  "_index": "kaleida",
			  "_type": "article",
			  "_id": "szeNvGABw9SxSpuUzKMH"
			}
		  ]
		}
	  }
	} 

	GET kaleida/article/_search
	{
	  "query": {
		"more_like_this": {
		  "fields": [
			"headline"
		  ],
		  "like": "trump says trump is stable genius"
		}
	  }
	}

The docs however still talk about explicit `ids` and `like_text` params which are no longer supported.

**Comment by Sue-Gallagher** [comment]
The documentation currently is:
`ids` or `docs`::
A list of documents following the same syntax as the <<docs-multi-get,Multi GET API>>.
Do I just remove "id" and leave "docs" and the definition, or does the whole thing go away?

**Comment by pcsanwald** [comment]
@Sue-Gallagher both "id" and "docs", and also "like_text", should go away as parameters, they were removed in 6.x [here's the breaking changes for 6.0](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking_60_search_changes.html)

**Comment by Sue-Gallagher** [comment]
@pcsanwald 
Thanks!
