### ISSUE TITLE
[Doc] Update "Java API Administration >> Indices Administration" page

### ISSUE THREAD

**Issue by sfalquier** [elastic/elasticsearch#28131]
**Elasticsearch version** : 6.1.1

**Description** : 
Since `PutMappingRequestBuilder.setSource(String source)` method has been removed (deprecated since 5.3 in #22691) in favour of `#setSource(String, XContentType)`, Indices Administration page in Java API documentation is obsolete : 
https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-admin-indices.html

All occurences of `setSource(String source)` or `addMapping(String type, String source)` method should be replaced with correct versions taking XContentType as parameter.

**Comment by cbuescher** [comment]
The PR adressing this needed to be reverted temporarily because it broke the docs build, reopening here as well.
