### ISSUE TITLE
Problem with "Elasticsearch: The Definitive Guide" tutorial

### ISSUE THREAD

**Issue by brian-vosburgh** [elastic/elasticsearch#28137]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.1.1, Build: bd92e7f/2017-12-17T20:23:25.338Z, JVM: 1.8.0_151

**Plugins installed**: []
ingest-geoip
ingest-user-agent
x-pack

**JVM version** (`java -version`):
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux 80fde8811f4d 4.9.49-moby #1 SMP Fri Dec 8 13:40:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
When working through the tutorial in _Elasticsearch: The Definitive Guide_, The queries do not work because the "interests" field is mapped as "text".

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Work through the tutorial in _Elasticsearch: The Definitive Guide_ up until the "Analytics" section (https://www.elastic.co/guide/en/elasticsearch/guide/current/_analytics.html).
 2. Execute the first query (or any other query on the page):
```
GET /megacorp/employee/_search
{
  "aggs": {
    "all_interests": {
      "terms": { "field": "interests" }
    }
  }
}
```
 3. Receive the following response:
```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [interests] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."
            }
        ],
        "type": "search_phase_execution_exception",
        "reason": "all shards failed",
        "phase": "query",
        "grouped": true,
        "failed_shards": [
            {
                "shard": 0,
                "index": "megacorp",
                "node": "TjkX3YKgQHmMxLtenJtejw",
                "reason": {
                    "type": "illegal_argument_exception",
                    "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [interests] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."
                }
            }
        ]
    },
    "status": 400
}
```
 4. The query should probably look like this (note the **`.keyword`**):
```
{
  "aggs": {
    "all_interests": {
      "terms": { "field": "interests.keyword" }
    }
  }
}
```
 5. The other queries on this page should be similarly modified.
**Provide logs (if relevant)**:

**Comment by dadoonet** [comment]
The definitive guide is still on 2.x version. Which explains this.

**Comment by abhaysharma419** [comment]
Thanks !!
