### ISSUE TITLE
AggregationBuilder related docs of Java API are outdated

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#28143]
Originally reported in #28114:

1. "AggregatorBuilder" should be replaced by "AggregationBuilder" in https://www.elastic.co/guide/en/elasticsearch/client/java-api/master/_bucket_aggregations.html

	> Ip Range Aggregationedit
	> Here is how you can use Ip Range Aggregation with Java API.

	> Prepare aggregation requestedit
	> Here is an example on how to create the aggregation request:

	> AggregatorBuilder<?> aggregation =...

	> Note that you could also use ip masks as ranges:

	> AggregatorBuilder<?> aggregation =...

2. "GeoBoundsBuilder" may be replaced by "GeoBoundsAggregationBuilder" in https://www.elastic.co/guide/en/elasticsearch/client/java-api/master/_metrics_aggregations.html#java-aggs-metrics-geobounds

	> Geo Bounds Aggregationedit
	> Here is how you can use Geo Bounds Aggregation with Java API.

	> Prepare aggregation requestedit
	> Here is an example on how to create the aggregation request:

	> GeoBoundsBuilder aggregation =
    >	    GeoBoundsAggregationBuilder...

These are leftovers from #18377 and we should revisit all related classes and update the Java API related docs for them.

**Comment by thirugnanamk89** [comment]
Hi @danielmitterdorfer,
I am a newcomer to the Open source community and I would like to contribute to this project. May I take up this doc work if it is still open?

**Comment by danielmitterdorfer** [comment]
Hi @thirugnanamk89, sure. Please see our [contribution guide](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md) which should answer a few of your questions.

**Comment by thirugnanamk89** [comment]
Thanks @danielmitterdorfer. I will go through the guide and raise the PR with required changes.

**Comment by SRITANU** [comment]
Hi @danielmitterdorfer , I have just submitted a pull request #28177 . Looking forward to your feedback.

**Comment by SRITANU** [comment]
Hi @danielmitterdorfer , I have just submitted a pull request #28177 . Looking forward to your feedback.

**Comment by thirugnanamk89** [comment]
@danielmitterdorfer : There was another requirement to change *IndexedScript* -> *StoredScript* in one of the referred PRs. But I am unable to find the text in the latest code. Is that something already taken care of ?

**Comment by danielmitterdorfer** [comment]
Yes in https://github.com/elastic/elasticsearch/commit/4182e9e3bb881b9bdb8ec67c7d96db65594852c1.
