### ISSUE TITLE
Stored script related docs of Java API are outdated

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#28144]
Originally reported in #28114:

3. PutIndexedScriptResponse, GetIndexedScriptResponse, and DeleteIndexedScriptResponse are outdated in https://www.elastic.co/guide/en/elasticsearch/client/java-api/master/indexed-scripts.html

	PutIndexedScriptResponse = client.preparePutIndexedScript()...

	GetIndexedScriptResponse = client.prepareGetIndexedScript()...

	DeleteIndexedScriptResponse = client.prepareDeleteIndexedScript()...

These are leftovers from #17650 and  all  `*IndexedScript*` should be replaced by `*StoredScript*` if I understood the change correctly (e.g. `PutIndexedScriptResponse` -> `PutStoredScriptResponse`, `client.preparePutIndexedScript()` -> `client.preparePutStoredScript()`).

@martijnvg I hope it's ok I'm assigning it to you as you did the change and might remember best.

**Comment by martijnvg** [comment]
> These are leftovers from #17650 and all *IndexedScript* should be replaced by *StoredScript* if I understood the change correctly (e.g. PutIndexedScriptResponse -> PutStoredScriptResponse, client.preparePutIndexedScript() -> client.preparePutStoredScript()).

@danielmitterdorfer That is correct. I'll will update these docs.

**Comment by ankishagarwal** [comment]
@martijnvg the docs are still showing outdated content for release version 5.1
Link -> https://www.elastic.co/guide/en/elasticsearch/client/java-api/5.1/indexed-scripts.html

**Comment by martijnvg** [comment]
@ankishagarwal If I recall correctly for 5.x, only the docs for 5.6 have been updated. Most of the times if doc changes are backported to 5.x, the changes are only backported to 5.6, since that is the only 5.x version that is maintained.
