### ISSUE TITLE
ER - Elasticsearch - 1-5 minute query time for warm tier

### ISSUE THREAD

**Issue by smgduncan** [elastic/elasticsearch#28158]
**Describe the feature**:
For some logging use cases, it is desirable to support a warm (or rather cold) tier for longer term storage, where we favour storage density over query response times.

For example, for a specific use case:
Hot tier: sub 10s query results are acceptable
Warm tier: sub 5 minute query results are acceptable

It would be desireable to reach storage densities in excess of 10Tb per 64G Ram node in this use case, I have seen use cases where 20-25Tb has been mentioned as a target figure.

I understand that Kibana and HTTP in general doesn't really allow this as things time out and get lost with HTTP transactions that take that long.

Is this something that could be considered?

**Comment by aleph-zero** [comment]
@smgduncan I would reach out to @cjgeode. She is conducting research into node density. 

As for long-running queries, I had assumed that the new SQL feature would be a way around that. @costin can you comment as to whether the SQL project will allow for long running queries?

**Comment by costin** [comment]
SQL doesn't alter the query support in ES. In other words, if ES behind the scenes is configured/supports it, SQL will do so as well.
