### ISSUE TITLE
elasticsearch-env overriding environment variables already set in service script

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#28159]
Came across this (6.0.1) while trying to test an install [using RPM (with an additional systemd script for the 2nd instance)](https://github.com/elastic/elasticsearch/issues/16697#issuecomment-185242677).

2nd instance systemd script:

```
[Service]
RuntimeDirectory=elasticsearch
Environment=ES_HOME=/usr/share/elasticsearch
Environment=ES_PATH_CONF=/etc/elasticsearch1
Environment=PID_DIR=/var/run/elasticsearch
EnvironmentFile=-/etc/sysconfig/elasticsearch1

WorkingDirectory=/usr/share/elasticsearch

User=elasticsearch
Group=elasticsearch

ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch1.pid --quiet

...
...

```

The problem here is that if the 2nd instance uses the same ES_HOME, the /usr/share/elasticsearch/bin/elasticsearch script will source /usr/share/elasticsearch/bin/elasticsearch-env, and when it gets to the `if [ -f /etc/sysconfig/elasticsearch ]; then source /etc/sysconfig/elasticsearch; fi` line of elasticsearch-env, it will override the ES_PATH_CONF set within the service for the 2nd instance with /etc/elasticsearch again, and the 2nd instance will end up picking up /etc/elasticsearch (the 1st instance's config directory). 

To workaround this, I have commented out the line in the elasticsearch-env so that it will pick up the right ES_PATH_CONF already set in the service script (in fact, this is what the puppet module has to compensate for as well) - probably not the ideal solution here for it will break on upgrades (alternatively, use a different ES_HOME for the 2nd instance).  

This feels like a bug - not sure why elasticsearch-env has to override existing environment variables like ES_PATH_CONF already set by the service script.

**Comment by jasontedor** [comment]
This is not a bug, this is behaving as intended. If you do not want an environment variable shared between instances, do not set it in the sourced environment file (i.e., remove `ES_PATH_CONF`).

**Comment by martinb3** [comment]
I'm confused about how removing ES_PATH_CONF actually solves this (aside from forcing both instances to use the same identical config). You're basically saying you can't share Elasticsearch homes at all any more, because elasticsearch-env will always use the default settings for the first instance?

**Comment by nemphys** [comment]
Same here with the deb package (Ububntu) and systemd.

In this case, elasticsearch-env just sources /etc/default/elasticsearch so all I had to do was edit the file and change

`ES_PATH_CONF=/etc/elasticsearch`

to

```
if [ -z "$ES_PATH_CONF" ]; then
 ES_PATH_CONF=/etc/elasticsearch
fi
```

in order to get the best of both worlds (cli tools continue to work properly, whereas any path set by systemd scripts do not get overwritten).

Now all seems to work well and I have my 2 instances running on the same server using a templated systemd file and separate /etc/elasticsearch, /var/lib/elasticsearch & /var/log/elasticsearch directories.
