### ISSUE TITLE
Date Range Selection Incorrect in ES 6

### ISSUE THREAD

**Issue by cawoodm** [elastic/elasticsearch#28168]
Until now we have used the following query to select and delete items in Elastic Search. The idea is to delete all items for a given day (e.g. today 10 Jan 2018):

```
{
  "query": {
    "bool": {
      "must": [
        {
          "wildcard": {
            "logfile": "general-app02-*"
          }
        }
      ],
      "filter": [
        {
          "range": {
            "timestamp": {
              "lte": "2018-01-10T00:00:00.0000000Z||+1d"
            }
          }
        }
      ]
    }
  }
}
```

Pretty darn sure this was working fine in ES 5.5 but now in 6.1.1 it's selecting documents from the previous day. Indeed we are seeing documents from the following range:
2018-01-10T12:45:00.0000000Z to 2018-01-08T23:00:00.0000000Z

Was our query incorrect and just worked by accident in ES5 or is something broke?

**Comment by albertzaharovits** [comment]
hello @cawoodm 
The query looks valid in ES 5 and 6 (I have tried some simple queries myself).
"lte": "2018-01-10T00:00:00.0000000Z||+1d" should match all documents on 2018-01-10 as per https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html .
If this is not the case, can you please provide a reproducible bare example?

**Comment by DaveCTurner** [comment]
@cawoodm I think this question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Please add a link to the forum discussion below so others can follow the thread. Many thanks.
