### ISSUE TITLE
timout parameter doesn't work with search

### ISSUE THREAD

**Issue by mmll** [elastic/elasticsearch#28179]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):5.2.2

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_121

**OS version** (`uname -a` if on a Unix-like system): opensuse

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Do search with " curl -XGET 'localhost:9200/_search?pretty&timeout=1ms'  "
 2. The part of response is : 
{
  "took" : 5,
  "timed_out" : false,
  "_shards" : {
    "total" : 208,
    "successful" : 208,
    "failed" : 0
  },
  "hits" : {
    "total" : 104429,
    "max_score" : 1.0,
    "hits" :
...
 3. The took time is 5ms, and timeout setting is 1ms. Why "timed_out" is false rather than true.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
Timeout only refers to the execution time of the search on the shard, it does not account for the total service time (time in the queue, time parsing the query, time rendering the response, etc.).
