### ISSUE TITLE
Filters aggregation does not return meta for date fields in range filter

### ISSUE THREAD

**Issue by ohadravid** [elastic/elasticsearch#28170]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.1.1

**Plugins installed**: []

**JVM version** (`java -version`): From the official docker

**OS version** (`uname -a` if on a Unix-like system): Official docker, On docker for Mac

**Description of the problem including expected versus actual behavior**:
When using `meta` attr for aggregations, it should be returned by ES.
Since ES6, adding `meta` for `filters` aggregation when using a `range` filter on a `date` field does not return the `meta` (other filters and other field types seem to work).

**Steps to reproduce**:

1. Add the document:
```
{
  "event_id": 1,
  "@timestamp": "2018-01-10T00:00:00.0000000Z"
}
```

2. Run the query:
```js
{
  "query": {
    "match_all": {}
  },
  "size": 0,
  "aggs": {
    "f90f4e": {
      "filters": {
        "filters": {
          "some_label": {
            "range": {
              "@timestamp": {
                "gte": "2016-12-01",
                "lte": "2017-02-01"
              }
            }
          }
        }
      },
      "meta": {
        "as_": "filters()"
      },
      "aggs": {
        "3018ae": {
          "cardinality": {'field': "event_id" }
        }
      }
    }
  }
}
```

And the result is:
```js
{
    ...,
    "hits": {...},
    "aggregations": {
        "f90f4e": {
            "buckets": {
                "some_label": {
                    "doc_count": 1,
                    "3018ae": {
                        "value": 1
                    }
                }
            }
        }
    }
}
```

In ES5.6.3, the result is
```
{
    ...,
    "aggregations": {
        "f90f4e": {
            "meta": {
                "as_": "filters()"
            },
            "buckets": {
                "some_label": {
                    "doc_count": 0,
                    "3018ae": {
                        "value": 0
                    }
                }
            }
        }
    }
}
```
as expected.

Using anything but range, and range on a non-date field works.
Replacing `@timestamp` to `event_id`, gives the expected result as well.

**Comment by ohadravid** [comment]
Also, when using the `_all` endpoint, using `range` with **any** type of field doesn't return the `meta`.

```
POST http://../_all/_search
```
With this query 
```
{
  "query": {
    "match_all": {}
  },
  "size": 0,
  "aggs": {
    "f90f4e": {
      "filters": {
        "filters": {
          "some_label": {
            "range": {
              "event_id": {
                "gte": 1,
                "lte": 20
              }
            }
          }
        }
      },
      "meta": {
        "as_": "filters()"
      },
      "aggs": {
        "3018ae": {
          "cardinality": {'field': "event_id" }
        }
      }
    }
  }
}
```
doens't work, but using

```
POST http://../some-index/_search
```
works as expected.

**Comment by colings86** [comment]
@ohadravid thanks for raising this issue. I have found the bug, it seems that when the filters in the filters aggregation are rewritten we don't add the metadata to the new rewritten version. I will have a PR up to fix this shortly.
