### ISSUE TITLE
elasticsearch with node example not working

### ISSUE THREAD

**Issue by venkkiram** [elastic/elasticsearch#28175]
Am exploring elasticsearch integration with node and trying to execute the following example 
https://github.com/sitepoint-editors/node-elasticsearch-tutorial

while trying to import the data from data.json, the 'node index.js' is able to only parse the items in data file but not indexing those items into my elasticsearch instance. 

I am not getting the log statement "Successfully indexed 1000 out of 1000 items" printed.

Any idea what step is missing here?

Thanks. 
Venkkiram

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
