### ISSUE TITLE
Return latest records group by specific field 

### ISSUE THREAD

**Issue by yangjiajun2014** [elastic/elasticsearch#28184]
Examples:
field1:type1 timestamp: 2018.01.11 21:29:00 field2:0
field1:type1 timestamp: 2018.01.11 21:30:00 field2:1
field1:type2 timestamp: 2018.01.11 21:30:00 field2:0
field1:type2 timestamp: 2018.01.11 21:31:00 field2:0
field1:type3 timestamp: 2018.01.11 21:29:00 field2:1
field1:type3 timestamp: 2018.01.11 21:31:00 field2:1
Returns:
field1:type1 timestamp: 2018.01.11 21:30:00 field2:1
field1:type2 timestamp: 2018.01.11 21:31:00 field2:0
field1:type3 timestamp: 2018.01.11 21:31:00 field2:1

Does elasticsearch support such operation?

**Comment by jimczi** [comment]
Elastic provides a forum for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
Regarding your question, field collapsing is what you're looking for: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-collapse.html
