### ISSUE TITLE
Can't merge because of conflicts: [Cannot update includes setting for [_source]]

### ISSUE THREAD

**Issue by yiliaofan** [elastic/elasticsearch#28182]
first:
curl -XPUT "http://localhost:9200/ace/shopping/_mappings" -d '{
"shopping" : {
    "_source" : { "includes" : ["type", "resource_id", "gender", "resource_version", "distribute_country", "recommend_country","update_time","update_date"] },
    "properties" : {
        "type" : { "type" : "text","index" : "not_analyzed"},
        "resource_id" : { "type" : "string","index" : "not_analyzed"},
        "resource_version" : { "type" : "integer","index" : "not_analyzed"},
        "gender" : { "type" : "text","index" : "not_analyzed"},
        "update_time" : { "type" : "long", "index" : "not_analyzed" },
        "update_date" : { "type" : "date", "index" : "not_analyzed" },
        "distribute_country" : { "type" : "text","index" : "not_analyzed"},
        "recommend_country" : { "type" : "text","index" : "not_analyzed"},
        "products" : { "type" : "text","index" : "not_analyzed"}
    }
  }
}'

return success!

next:

curl -XPUT "http://localhost:9200/ace/shopping/_mappings" -d '{
"shopping" : {
    "_source" : { "enabled" : true},
    "properties" : {
        "type" : { "type" : "text","index" : "not_analyzed"},
        "resource_id" : { "type" : "string","index" : "not_analyzed"},
        "resource_version" : { "type" : "integer","index" : "not_analyzed"},
        "gender" : { "type" : "text","index" : "not_analyzed"},
        "update_time" : { "type" : "long", "index" : "not_analyzed" },
        "update_date" : { "type" : "date", "index" : "not_analyzed" },
        "distribute_country" : { "type" : "text","index" : "not_analyzed"},
        "recommend_country" : { "type" : "text","index" : "not_analyzed"},
        "products" : { "type" : "text","index" : "not_analyzed"}
    }
  }
}'

response:
{
    "error":{
        "root_cause":[
            {
                "type":"illegal_argument_exception",
                "reason":"Can't merge because of conflicts: [Cannot update includes setting for [_source]]"
            }
        ],
        "type":"illegal_argument_exception",
        "reason":"Can't merge because of conflicts: [Cannot update includes setting for [_source]]"
    },
    "status":400
}

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

But yes, this is expected as you can't modify the `_source` settings.

**Comment by yiliaofan** [comment]
thanks！
