### ISSUE TITLE
Configuration variable substitution broken in 6.x for array entries

### ISSUE THREAD

**Issue by bra-fsn** [elastic/elasticsearch#28196]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.1.1, Build: bd92e7f/2017-12-17T20:23:25.338Z, JVM: 1.8.0_152

**Plugins installed**: analysis-icu

**JVM version** (`java -version`): 
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (build 1.8.0_152-b16)
OpenJDK 64-Bit Server VM (build 25.152-b16, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
FreeBSD japan 11.1-STABLE FreeBSD 11.1-STABLE #0 r324684: Tue Oct 17 15:07:45 CEST 2017     root@japan:/usr/obj/usr/src/sys/GENERIC  amd64

**Description of the problem including expected versus actual behavior**:
Older (up to 5.6.4 at least) elasticsearch could work with the following in its config (elasticsearch.yml):
discovery.zen.ping.unicast.hosts: ["${ES_MASTER1}:${ES_MASTER_PORT}","${ES_MASTER2}:${ES_MASTER_PORT}","${ES_MASTER3}:${ES_MASTER_PORT}"]
network.bind_host: ["${ES_HOST}","127.0.0.1"]
Newer ones (6.1.1 tested, not sure about previous versions) don't.
It doesn't expand the variable, so it fails for example with:
Caused by: java.net.UnknownHostException: ${ES_HOST}: hostname nor servname provided, or not known

Variables in normal (not list) config lines seem to work.

**Steps to reproduce**:
Use a variable substitution in an array configuration setting.

**Comment by jasontedor** [comment]
Duplicates #27926
