### ISSUE TITLE
Elasticsearch, installed over Repository won´t start

### ISSUE THREAD

**Issue by Happyfeet01** [elastic/elasticsearch#28194]
Hello,

i try to Setup an searchplugin for my Nextcloud installation. i followed this guide but Elasticsearch won´t start. look at the Error log.

What´s wrong?

**Elasticsearch version** (`bin/elasticsearch --version`): 

Version: 6.1.1, Build: bd92e7f/2017-12-17T20:23:25.338Z, JVM: 9-internal

**Plugins installed**: [] 

ingest-attachment  readonlyrest 6.1.1

**JVM version** (`java -version`):

OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Linux panel.domain.tld 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

i do this installation Steps

1. wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
2. sudo apt-get update && sudo apt-get install elasticsearch

then install the plugins;

1. sudo bin/elasticsearch-plugin install ingest-attachment
2. bin/elasticsearch-plugin install file://<download_path>/readonlyrest-*.zip

**Provide logs (if relevant)**:

```
Jan 12 10:34:15  elasticsearch[21473]: java.security.policy: Fehler beim Hinzufügen von Eintrag:
Jan 12 10:34:15 elasticsearch[21473]:         java.net.MalformedURLException: no protocol: ${codebase.lucene-core}
Jan 12 10:34:15  elasticsearch[21473]: java.security.policy: Fehler beim Hinzufügen von Eintrag:
Jan 12 10:34:15  elasticsearch[21473]:         java.net.MalformedURLException: no protocol: ${codebase.lucene-misc}
Jan 12 10:34:16  elasticsearch[21473]: Exception: java.lang.SecurityException thrown from the UncaughtExceptionHandler in thread "main"
 systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: elasticsearch.service: Unit entered failed state.
`systemd[1]: elasticsearch.service: Failed with result 'exit-code'.

```

**Comment by jasontedor** [comment]
Would you please provide the output of `ls /usr/share/elasticsearch/lib` and please also provide the full stacktrace which you can find either in the Elasticsearch logs or in `journalctl -xe -u elasticsearch`?

**Comment by Happyfeet01** [comment]
i have solved it myself. i used the wrong Java Version
