### ISSUE TITLE
Missing `timeout` parameter from the REST API spec JSON files

### ISSUE THREAD

**Issue by TwP** [elastic/elasticsearch#28200]
**Elasticsearch version**: all 2.X, 5.X, and 6.X releases

**Plugins installed**: NA

**JVM version**: NA

**OS version**: NA

**Description of the problem including expected versus actual behavior**:

The [`tasks.list`](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/tasks.list.json) and [`tasks.get`](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/tasks.get.json) REST API specs are missing the `timeout` parameter.

**Steps to reproduce**:

The `timeout` parameter is missing from the REST API spec for the `tasks.list` and `tasks.get` JSON files. Any client code or test validations that rely on these JSON files will be in error because of this missing param.

I've confirmed on ES 5.6.4 that the `timeout` param is accepted by the server:

```
> curl -XGET 'localhost:9200/_tasks?timeout=10s' | jq '.'
{
  "nodes": {
    "oXZa92DeSja4HL1sKHmsdw": { ... }
  }
}
```

**Provide logs (if relevant)**: NA

**Comment by ao** [comment]
@TwP I have submitted a PR for this: https://github.com/elastic/elasticsearch/pull/28328
