### ISSUE TITLE
ERROR Unable to locate plugin type for IfFileName

### ISSUE THREAD

**Issue by ilkiny** [elastic/elasticsearch#28207]
Hello there,

I am faced with such an error, what is the cause?

[Log](https://gist.github.com/ilkiny/e3c478f30595e62ad5d8fd8b5fce3f38)

Stay with love.

**Comment by dadoonet** [comment]
> `java.lang.RuntimeException: can not run elasticsearch as root`

Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
