### ISSUE TITLE
 ES nodes disconnects intermittently from the cluster 

### ISSUE THREAD

**Issue by neeraj20gupta** [elastic/elasticsearch#28201]
I have a 12 node cluster for elasticsearch(version 2.4), all the machines are on EC2-instances. IN between I am getting errors like master left due to which unassigned shards increases and cluster health turns to red.
Environment details:
JVM : java-1.8.0-openjdk-1.8.0.45-28.b13.el6_6.x86_64
OS Version : CentOS release 6.6 (64 bit) 

`[2018-01-11 07:48:44,828][INFO ][discovery.zen ] [esnode21] master_left [{esnode12}{-xxxxxxxxxx}{x.x.x.x}{x.x.x.x:9300}], reason [failed to ping, tried [3] times, each with maximum [1h] timeout]`

Before these logs its just a normal GC activity no errors.
We have tested the network configuration even ran a test to test network drops and everything seems fine.

Increased the fault-detection to following :-
```
discovery.zen.fd.ping_interval: 1800s
discovery.zen.fd.ping_timeout: 3600s
```

After going through various blogs I came across Nodes randomly disconnected from the ES cluster. I have also truned of scatter-gather using ethtool as mentioned in https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1317811.

I have also updated the TCP keepalive settings as below
```
net.ipv4.tcp_keepalive_time = 120
net.ipv4.tcp_keepalive_probes = 3
net.ipv4.tcp_keepalive_intvl = 30
```
Still these errors are occurring intermittently.

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
