### ISSUE TITLE
_id is not configurable

### ISSUE THREAD

**Issue by dmzgxl** [elastic/elasticsearch#28215]
**Describe the feature**:when i create index by assign _id mapping mainkey of the source,it told me _id
 is not configurable

**Elasticsearch version** (`bin/elasticsearch --version`):5.6.3

**Plugins installed**: []

**JVM version** (`java -version`):jdk1.8

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.create index
{
    "settings" : {
        "number_of_shards" : 1,
        "number_of_replicas":0
    },
    "mappings" : {
        "test1" : {
            "_id":{"path":"mainkey"},
            "_source" : { "enabled" : false },
            "properties" : {
                "mainkey" : { "type" : "string", "index" : "not_analyzed" }
            }
        }
    }
}

**Provide logs (if relevant)**:

{
    "error": {
        "root_cause": [
            {
                "type": "mapper_parsing_exception",
                "reason": "_id is not configurable"
            }
        ],
        "type": "mapper_parsing_exception",
        "reason": "Failed to parse mapping [test1]: _id is not configurable",
        "caused_by": {
            "type": "mapper_parsing_exception",
            "reason": "_id is not configurable"
        }
    },
    "status": 400
}

**Comment by jimczi** [comment]
Elastic provides a forum for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by dmzgxl** [comment]
okay,i know.Sorry to bother you.
