### ISSUE TITLE
simple_query_string excepts with number_format_exception

### ISSUE THREAD

**Issue by floggle** [elastic/elasticsearch#28210]
ES 6.1
I have a multi_match query (type: cross_fields) that points at fields that are both string and number type.
If the query is "word 123" this query will work and respond with relevant results.

But if I do the same query against the same fields but via a simple_query_string, I get:
            "type": "number_format_exception",
            "reason": "For input string: \"word\""

Thoughts:
- Query types should be consistent in their acceptance of mixing strings and numbers.
- Because it's in multi_match this seems like an omission/bug in simple_query_string
- If this is intentional behaviour for simple_query_string then it should be documented - I don't see anything about it here: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html

**Comment by jimczi** [comment]
Elastic provides a forum for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
Regarding your questions, the `multi_match` and the `simple_query_string` behaves similarly when the input is not parseable by the targeted field (for a number they throw a number_format_exception if the input is not a number). If you want to ignore these errors and just proceed with the other fields/inputs you can add `lenient:true` to your request:
````
If set to true will cause format based failures (like providing text to a numeric field) to be ignored.
````
