### ISSUE TITLE
Find offset of matched input query terms to the document

### ISSUE THREAD

**Issue by tahirahmad2030** [elastic/elasticsearch#28216]
I have explored elasticsearch and couldn't find how to get those terms in input query which matched an indexed document. Some times the query is itself big and we want to highlight and get offset of terms in the input query.

Can someone help me on this?

**Comment by tahirahmad2030** [comment]
example : I have a query like "I love blue fox". The document which I indexed in elastic search contains "Black and Brown fox are animals".
My requirement is to get offsets of matching tokens in the input query. for example in this case from "I love blue fox" fox is matching to one document. How can I get offsets of query terms which matched the document.

**Comment by jimczi** [comment]
You can use highlighters for this but currently there is no way to "just" return the matching offsets:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html

There's already a feature request for this:
https://github.com/elastic/elasticsearch/issues/5736
I see that you commented on this issue so I hope you don't mind if I close this.

**Comment by tahirahmad2030** [comment]
@jimczi My problem is to highlight the query matching terms not the result terms. So this issue is different from #5736.

**Comment by jimczi** [comment]
Ok I see, then could the named query help ?
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-named-queries-and-filters.html

**Comment by tahirahmad2030** [comment]
@jimczi I don't think named query will help in my case as I have a large single query (a page) from which I need to find the matching terms. Named query seem to be an explicit name given to a query and when it is matched the same explicit name under "_name" gets added to "matched_queries" list.

**Comment by jimczi** [comment]
Yes that's how named queries work. You could also split the large query into several match queries (one for each term) and use named queries to retrieve which term matched ? 
The matches for each document will be different so I don't see how we could highlight the input query (unless we highlight it for every hit).

**Comment by tahirahmad2030** [comment]
@jimczi Thanks
