### ISSUE TITLE
force is still documented as accepted parameter for version_type

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#28229]
https://github.com/elastic/elasticsearch/search?l=JSON&q=force&type=&utf8=✓

Which has been removed: https://www.elastic.co/guide/en/elasticsearch/reference/6.1/breaking_60_docs_changes.html

**Comment by Mpdreamz** [comment]
https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/VersionType.java always check source first before opening an issue..

**Comment by moljac024** [comment]
Why was this closed? This issue is still relevant. The documentation states something that is not true.

**Comment by bleskes** [comment]
Thanks for the doc PR. I'll merge it when tests pass. 

> This might be the wrong place to ask but I have a need to update via script but use my own versioning. How can this be achieved?

You should read the get through the get API, do your modification and write back using your versioning scheme. That said, I'm curious as to what you're trying to do - can you explain a bit more about your versioning scheme and how the update affects it?
