### ISSUE TITLE
Aggregations enhancement - better memory usage estimates to avoid circuit breaking

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#28220]
In a recent [discuss forum post](https://discuss.elastic.co/t/elasticsearch-aggregation-encounters-circuit-breaking-exception/115454) a user reported circuit breaking exceptions when using a large number of `avg` aggregations nested under two layers of `terms` aggregations.
Internally, the estimated memory cost of handling the request was (badly) estimated to be nearly 3GB in size but the actual size should have been much smaller. In part, this is due to a [one-size-fits-all](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/AggregatorBase.java#L106) cost which is added for every aggregation which is hard-coded to 5kb in the aggregator base class.

For some aggregations this is often an underestimate (e.g. cardinality agg) while for simple metric aggregations like the `avg` aggregation it is a large over-estimate (which led to the circuit breaker error in the case mentioned above).

The solution requires 
1) A change to AggregatorBase to allow subclasses to override a new "getWeight" method.
2) Changes to metric aggregations like `avg` to provide a better estimate of their memory cost.

**Comment by polyfractal** [comment]
@elastic/es-search-aggs

**Comment by polyfractal** [comment]
I think this can be closed, now that we are relying heavily on the real-memory circuit breaker in https://github.com/elastic/elasticsearch/pull/46751 and https://github.com/elastic/elasticsearch/pull/57042
