### ISSUE TITLE
Incorrect in the documentation or maybe a bug

### ISSUE THREAD

**Issue by aslamy** [elastic/elasticsearch#28230]
Incorrect in the documentation or maybe a bug (Elasticsearch 6.1.1), It says:

>  boundary_scanner:
> Specifies how to break the highlighted fragments: **chars**, sentence, or word. Only valid for the **unified** and fvh highlighters.
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html

When I use a unified highlighter in combination with chars boundary_scanner I get an exception:
```
"boundary_scanner":"chars",
"type": "unified"
```

exception:
```
"reason": {
"type": "illegal_argument_exception",
"reason": "Invalid boundary scanner type: chars"
}
```

**Comment by jimczi** [comment]
The documentation for the `chars` boundary scanner says:
````
Use the characters specified by boundary_chars as highlighting boundaries. The boundary_max_scan setting controls how far to scan for boundary characters. Only valid for the fvh highlighter.
````
So it's only valid for the `fvh` highlighter and not supported by the `unified` highlighter.
