### ISSUE TITLE
Need same feature "ignore_malformed" for keyword/object type mapping

### ISSUE THREAD

**Issue by neoxue** [elastic/elasticsearch#28234]
For a numeric type, it is possible to use "ignore_malformed" to ignore error type (but receive other correct fields)when the input variable is not numeric;
want a same feature for Keyword/Object type.

**Comment by colings86** [comment]
This relates to the discussion in https://github.com/elastic/elasticsearch/issues/12366

**Comment by jpountz** [comment]
Closing in favour of #12366 where the discussion is happening.
