### ISSUE TITLE
script_exception while applying a string concatenation

### ISSUE THREAD

**Issue by bainim** [elastic/elasticsearch#28243]
**Describe the feature**:
How can make a contatination a string fields?

**Description of the problem including expected versus actual behavior**:

{
  "error": {
    "root_cause": [
      {
        "type": "script_exception",
        "reason": "error evaluating ctx._source.new_field = ctx._source.date + ctx._source.time + ctx._source.tz",
        "script_stack": [],
        "script": "",
        "lang": "groovy"
      }
    ],
    "type": "script_exception",
    "reason": "error evaluating ctx._source.new_field = ctx._source.date + ctx._source.time + ctx._source.tz",
    "caused_by": {
      "type": "null_pointer_exception",
      "reason": "Cannot execute null+null"
    },
    "script_stack": [],
    "script": "",
    "lang": "groovy"
  },
  "status": 500
}
**Steps to reproduce**: 

PUT /myindex/_mapping/mytype
{
"properties": {
"new_field": {
"type": "string"
}
}
}

POST /myindex/mytype/_update_by_query
{
"query":{
"bool":{
"must_not":{
"exists":{
"field":"new_field"
}
}
}
},
"script":{
"inline":"ctx._source.new_field = ctx._source.date + ctx._source.time + ctx._source.tz",
"lang":"groovy"
}
}

**Comment by DaveCTurner** [comment]
@bainim I think this question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. In particular, it is not detailed enough to be useful as a bug report: you do not say what Elasticsearch version you are using, and the "steps to reproduce" do not reproduce this problem on a clean installation of Elasticsearch.

I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Please add a link to the forum discussion below so others can follow the thread. Many thanks.
