### ISSUE TITLE
Third party audit failed due to jaxb

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#28252]
It looks like the third party audit of `:plugins:discovery-ec2:thirdPartyAudit` failed because:
```
20:20:39 > Invalid exclusions, nothing is wrong with these classes: [javax/xml/bind/DatatypeConverter.class, javax/xml/bind/JAXBContext.class]
```

My guess is that this is a Java 9 update issue because of this line in the build file:
```
if (JavaVersion.current() > JavaVersion.VERSION_1_8) {
  thirdPartyAudit.excludes += ['javax.xml.bind.DatatypeConverter']
}
```

I expect we're confused about something though I'm not 100% sure what without digging more.

**Comment by nik9000** [comment]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1195/console

**Comment by nik9000** [comment]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1026/console

**Comment by jasontedor** [comment]
It is known, we are on it. It is because Gradle is still running on JDK 8 in CI. We are fixing this.

**Comment by jasontedor** [comment]
The code that you reference is already gone, it was changed with the JDK 9 change: 0a79555a122f0a2b7361c12760f32337e20fba9a

**Comment by nik9000** [comment]
Got it.

**Comment by jasontedor** [comment]
We also need to make a change to the third party audit task to not run in the Gradle JVM.

**Comment by jasontedor** [comment]
Okay, not running the Gradle JVM turns out to be very difficult. After getting it to work, because we are forking Gradle for every single third party audit task it slows down the build massively (~30 minutes). This is too much. Instead, we are going to handle this in CI only. I have opened an internal issue for this.

**Comment by jasontedor** [comment]
This is addressed now in the sense that builds will pass. The internal changes still need to take place to ensure that we have coverage on JDK 8, JDK 9, and JDK 10 but that's orthogonal to the reported build failures here.
