### ISSUE TITLE
Need a Child Score of ChildScoreMode.First

### ISSUE THREAD

**Issue by DR9885** [elastic/elasticsearch#28254]
**Describe the feature**:
Currently Sorting requires scoring. However, with Child Scoring, it will score all children, not just one. Like if I only want the best child scored.

Ideally I would like to use a "ChildScoreMode.First" along with sorting the children by best value.

**Comment by jimczi** [comment]
Could you be more precise in the description of the feature ? What do you mean by child scoring ? 
Is it `nested` sort: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#nested-sorting ? 
You can choose a sort mode already:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_sort_mode_option
Are you proposing to add a `first` mode that would select the first nested document ?

**Comment by DR9885** [comment]
Sure, I have two documents (Securities and Offers), with a parent-child relationship. The end goal is to sort Securities by Offer Expiration, but only on the "cheapest" offer.

For Example, lets say we have the following data: (* is cheapest offer)

	- Security 1
		-- Offer 1, Price 2, Expiration 1/1/2017 
		-- *Offer 2, Price 1, Expiration 1/1/2018
	- Security 2
		-- Offer 1, Price 3, Expiration 1/1/2018
		-- *Offer 2, Price 2, Expiration 1/1/2019

But I wanted it to sort by Offer Expiration Desc (of the cheapest offer only)

	- Security 2
		-- Offer 1, Price 3, Expiration 1/1/2018
		-- *Offer 2, Price 2, Expiration 1/1/2019
	- Security 1
		-- Offer 1, Price 2, Expiration 1/1/2017 
		-- *Offer 2, Price 1, Expiration 1/1/2018

Note: Security 2 wins because it's cheapest offer is in 2019


The following document suggests that if I want to sort two documents, to write scoring scripts:
Ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-has-child-query.html

**Comment by jimczi** [comment]
Ok I thought you were talking of nested fields but if you use `parent/child` then the only way to sort by a child field is to use a function_score. I think you can achieve what you want by using a function_score like this (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-has-child-query.html#_sorting):

```
"function_score" : {
                    "script_score": {
                        "script": "doc['price'].value"
                    }
                }
```
and then use `inner_hits` with a different sort for the offers:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html

Since this is more a question on how to achieve something I hope you dont mind if I close this issue. We reserve github for verified bugs and feature request so can I ask you to open a new discussion on discuss.elastic.co ? I'll be happy to help there.

**Comment by DR9885** [comment]
I'm aware that some of this feature exists, but it's incomplete for my needs. function_score requires a score_mode of "min, max, sum, avg or none". However, when doing so, it scores all the children. I want it to ignore all but the first. So I'm asking for a Feature "score_mode" : "first"

So I can do something like the following:

`
        {
          "has_child": {
            "type": "offer",
            "score_mode": "first",
            "query": {
              "function_score": {
                "functions": [
                  {
                    "script_score": {
                      "script": {
                        "inline": "doc['expiration'].value"
                      }
                    }
                  }
                ]
              }
            },
            "inner_hits": {
              "sort": [
                {
                  "price": {
                    "order": "asc"
                  }
                }
              ]
            }
          }
        }
`

Ideally that would do the following:

1. sort inner_hits of offers by price (so the first offer is always the best price)
2. score only the first offer
3. the sort the results by the parent

#2 being the most important

**Comment by potatman** [comment]
Hi @jimczi I am hitting this bug as well for a similar use case.  I'm afraid the approach in https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-has-child-query.html#_sorting doesn't help in these sorts of cases.  Any chance this could be reopened and get fixed?  Function_score doesn't work when you need to sort based on a value in a specific child doc.   It just takes the lowest or highest value of any child doc.
