### ISSUE TITLE
Elasticsearch Reference guide: Disable invalid options in the version select box

### ISSUE THREAD

**Issue by mjustin** [elastic/elasticsearch#28272]
I would like to request an enhancement to the Elasticsearch Reference guide.  Currently, when you select a version in the dropdown that does not exist, a dialog appears saying e.g. "This page is not available in the docs for version:5.5" and does not change the page to the selected version.  I think it would be a nicer usability feature if the invalid versions were instead disabled so it would be obvious before selecting it that the page isn't available in the given version.

**My use case:**

I'm currently on an older version of Elasticsearch, and I'm looking to upgrade in the near future.  I often want to compare functionality between versions.  Having the invalid versions disabled would make it quicker to see which versions are valid to switch to, rather than clicking on different ones until I find a valid one.

I've also run across this when Googling a feature and ending up on the page for a different version than I need.

**Comment by jasontedor** [comment]
Thanks for the issue @mjustin. I understand the problem that you're facing and I agree that it's a poor usability experience. That said, this is not the right repository for this issue. Can I ask you to reopen this on [elastic/docs](https://github.com/elastic/docs) and the docs team will see what can be done about this?

**Comment by mjustin** [comment]
Created: https://github.com/elastic/docs/issues/291.
