### ISSUE TITLE
Creating an index with mappings and analysis doesn't work

### ISSUE THREAD

**Issue by hhovhann** [elastic/elasticsearch#28293]
Hi @kimchy, I saw https://github.com/elastic/elasticsearch/issues/767 is closed but my error is similar.

Elastic Search Version is 2.4.4
 
`The first example fails with MapperParsingException[Analyzer [bigrams] not found for field [displayName]];. `

What about the case when we are using `settings.json` in `resource` and spring data annotations (`@Setting(settingPath = "/settings/settings.json")` in class level, and `@Field(type = FieldType.String, analyzer = "bigrams")` for corresponding field)

```{
  "index": {
    "analysis": {
      "filter": {
        "bigrams_filter": {
          "type": "ngram",
          "min_gram": "2",
          "max_gram": "2"
        }
      },
      "analyzer": {
        "bigrams": {
          "type": "custom",
          "tokenizer": "standard",
          "filter": [
            "lowercase",
            "bigrams_filter"
          ]
        }
      }
    }
  }
}```


```
@Setting(settingPath = "/settings/settings.json")
public abstract class AbstractSearchEntity implements Entity {
........
@Field(type = FieldType.String, analyzer = "bigrams")
private String displayName;`
..........

}
```
regards Hayk

**Comment by cbuescher** [comment]
Hi @hhovhann! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by hhovhann** [comment]
Thanks,
Here is https://discuss.elastic.co/t/creating-an-index-with-mappings-and-analysis-doesnt-work/116048
