### ISSUE TITLE
ThreadLocals not cleared

### ISSUE THREAD

**Issue by daspilker** [elastic/elasticsearch#283]
I am running ElasticSearch 0.9.0. My web application uses the Java API to connect to the server. After closing the client node, several API objects are still referenced by ThreadLocals. As a consequence the web application can not be garbage collected after being undeployed. This creates a memory leak.

    30.07.2010 14:59:07 org.apache.catalina.loader.WebappClassLoader clearThreadLocalMap
    SCHWERWIEGEND: The web application [] created a ThreadLocal with key of type [null] (value [org.elasticsearch.common.inject.InjectorImpl$1@19d44df]) and a value of type [java.lang.Object[]] (value [[Ljava.lang.Object;@149895]) but failed to remove it when the web application was stopped. This is very likely to create a memory leak.
    30.07.2010 14:59:07 org.apache.catalina.loader.WebappClassLoader clearThreadLocalMap
    SCHWERWIEGEND: The web application [] created a ThreadLocal with key of type [null] (value [org.elasticsearch.common.util.concurrent.jsr166y.ThreadLocalRandom$1@2d8a59]) and a value of type [org.elasticsearch.common.util.concurrent.jsr166y.ThreadLocalRandom] (value [org.elasticsearch.common.util.concurrent.jsr166y.ThreadLocalRandom@1d60b6a]) but failed to remove it when the web application was stopped. This is very likely to create a memory leak.
    30.07.2010 14:59:07 org.apache.catalina.loader.WebappClassLoader clearThreadLocalMap
    SCHWERWIEGEND: The web application [] created a ThreadLocal with key of type [null] (value [org.elasticsearch.common.inject.InjectorImpl$1@19d44df]) and a value of type [java.lang.Object[]] (value [[Ljava.lang.Object;@1876a6d]) but failed to remove it when the web application was stopped. This is very likely to create a memory leak.

**Comment by nandini-r** [comment]
Is this bug fixed ? I am getting the below memory leak log in tomcat  ::                                             SEVERE: The web application created a ThreadLocal with key of type [
org.elasticsearch.common.inject.InjectorImpl$1] (value [org.elasticsearch.common
.inject.InjectorImpl$1@35ad2c3]) and a value of type [java.lang.Object[]] (value
 [[Ljava.lang.Object;@566ace8c]) but failed to remove it when the web applicatio
n was stopped. Threads are going to be renewed over time to try and avoid a prob
able memory leak.

**Comment by clintongormley** [comment]
@nandini-r what version are you on?

**Comment by nandini-r** [comment]
@clintongormley Elastic search version i am using is 1.4.3 .  Sorry for the late reply

**Comment by clintongormley** [comment]
@nandini-r  OK - lots has changed since then, I would upgrade and see if the problem still exists.  Please let us know either way.

**Comment by nandini-r** [comment]
@clintongormley I tried with 1.7.1 and still the same log appears

**Comment by jsmucr** [comment]
We're dealing with this issue as well. This pretty much spoils any attempts to hot swap new versions of our application automatically.

**Comment by nik9000** [comment]
I've stolen this issue from @kimchy and added it to my queue of things to look it. Its not particularly high on that list but I'll get to it eventually. If anyone feels like working on it then please comment. Or just self assign if you have that power.

**Comment by nandini-r** [comment]
@clintongormley  @nik9000  Wanted to mention this : Not sure if those threads are getting closed slowly because when I try adding delay of say 20-30 s , logs are not seen when I stop webapp . Though it is sometimes reproducible when I use 'reload' webapp option.

**Comment by arosso** [comment]
+1 - This one causes us some major issues with continuous deploys to dev/qa/prd. What we've found with Java and PermGen, is that if there is even the smallest leak of an object, upon a reload *all* classes will be leaked. Basically the classloader can't release the dependency tree of the web app. Even with a PermGen of 512Mb we cannot redeploy our web app more than once before things blow up. All other dependencies we have (and we have quite a bit) have various hooks to close/shutdown when the web app is unloaded. Sometimes we have to dig for them but there's usually a way.

I've seen various patches mentioned. Has anyone found a workaround while an official fix is being worked on?

**Comment by arivazhagan-jeganathan** [comment]
Hi I am using elasticsearch 1.5.1 and Java 7. Upgrading to Java 8 is not an option right now since I am into production deployment.  Is there any workaround available till this issue gets fixed?  Or Is there any fix already available?

**Comment by pengchengluo** [comment]
I still have the problem for elasticsearch 2.3.1

org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [org.elasticsearch.common.inject.InjectorImpl$1] (value [org.elasticsearch.common.inject.InjectorImpl$1@2f5768cb]) and a value of type [java.lang.Object[]] (value [[Ljava.lang.Object;@51ceb57]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
