### ISSUE TITLE
Add cluster level setting to control the max size of warning headers in client HTTP responses

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#28301]
Today warning headers returned on client responses can be unbounded in size without a user knob to control this. Such warning headers can accumulate rapidly on, for example, bulk indexing requests using deprecated fields (e.g., `string` for `keyword` and `text`) across many fields. This can cause problems when there is a proxy between clients which limits the buffer size for proxy responses. This issue proposes adding a cluster level byte size setting that allows users to limit the size of warning headers sent on client HTTP responses. The default should be unbounded.

Relates #17804

**Comment by DaveCTurner** [comment]
It's possible that the proxy rejects the headers because of their number rather than/as well as their total size. It might be useful to limit the number of headers too.

**Comment by kovyrin** [comment]
Yes, please! We've just his this issue on Kibana/ES/ECE deployment, where ECE proxy chokes up on a bunch of warning coming from ES to Kibana and that basically made our Kibana permanently broken until we dropped the index that was generating warnings...
