### ISSUE TITLE
Allow meta-plugins to declare a parent

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#28306]
Meta-plugins should have the ability to declare one plugin as a parent plugin and all other plugins are then loaded into classloaders that are children of the classloader for that parent plugin. Thus with:

 - A
   - B
   - C

we would have the classloader hierarchy:
 - server
   - A
     - B
     - C

whereas today we have
  - server
    - A
    - B
    - C

**Comment by rjernst** [comment]
I don't think we should do this as it would mean plugins would have access to some classes of parents, but not all. The better solution is to not depend on access to package protected members from different jars. This is the java 9 way, and java 9 modules do not allow this.

**Comment by jasontedor** [comment]
We discussed this verbally awhile ago and came to the same conclusion. I should have left notes from that conversation here then and closed this issue. As such, closing.
