### ISSUE TITLE
range value int or float,result different

### ISSUE THREAD

**Issue by githubyyf** [elastic/elasticsearch#28308]
es version: 5.4.0

1.range value type float
code:
GET /shops/baseShops/_search?_source=true&size=10
{"query":{"match_all":{}},"post_filter":{"bool":{"must":[[{"term":{"company_id":75}}],[{"term":{"manager_id":"3685"}}],[{"range":{"out_date":{"gte":1516291200.0,"lte":151698239.0}}}]]}},"sort":[{"created_at":"desc"}]}

result:
nothing
![image|690x185](upload://gZtSuP2du2PMBjqfR8tF9jTA2hf.png)

2.range value type int
code:
GET /shops/baseShops/_search?_source=true&size=10
{"query":{"match_all":{}},"post_filter":{"bool":{"must":[[{"term":{"company_id":75}}],[{"term":{"manager_id":"3685"}}],[{"range":{"out_date":{"gte":1516291200,"lte":151698239}}}]]}},"sort":[{"created_at":"desc"}]}
result:
three data
![image|690x201](upload://d8o1ll7a9rnvx7T8viAt68F1eCF.png)

why like this result different,they are all number???

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
