### ISSUE TITLE
High Level Rest client should use POST when we have body

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#28326]
When elasticsearch is behind a Proxy and this Proxy does not support GET with body (which might be seen as a bug of the Proxy), people can't use our Java Rest Client as explained in https://discuss.elastic.co/t/es-cluster-via-proxy-ip-but-listener-timeout-after-waiting-for-30000-ms/116192/6

For example, the search Request here uses a GET method: https://github.com/elastic/elasticsearch/blob/b98514c6d905e70853d5316f823df38974f98739/client/rest-high-level/src/main/java/org/elasticsearch/client/Request.java#L424

I think we should may be switch to POST instead anytime we might have a body.

Thoughts?

**Comment by javanna** [comment]
Makes sense. What I had in mind was to have an option that lets you choose between GET and POST, like other language clients do. Or switching to POST like you proposed.

**Comment by DaveCTurner** [comment]
The use of bodies in HTTP GET requests is a little unusual. Although the spec is not crystal clear on the subject, it is possible to read it in a way that means the body of a GET request can and should be ignored: https://stackoverflow.com/a/983458

**Comment by javanna** [comment]
@DaveCTurner  I don't think this is the right place to discuss what our API should support. Our API supports both, we always had a preference for `GET` with body but we decided (years ago) to support `POST` too for clients and proxies that don't support `GET` with body. In our clients, we should follow what the API exposes, hence we should allow to choose between `POST and `GET` if the API allows both. This is something that I had wondered about when going for `GET` only but I was waiting for the first user to point out that `GET` causes trouble to them.

**Comment by DaveCTurner** [comment]
Sorry, I didn't mean to open that debate. Supporting both on the API side seems fine. Just wanted to say that a proxy that doesn't pass the body through on a `GET` request shouldn't necessarily be considered buggy - it is more of a bug in the spec itself that this difference of opinion can exist. Using `POST` seems safer in situations that might involve a proxy: not only will it fix the OP's problem but it'll also avoid the possibility that the response is cached and quietly re-used in response to different queries against the same URL.

What'd be the disadvantage of completely switching to `POST` in the client as @dadoonet suggests?

**Comment by jasontedor** [comment]
Completely switching to `POST` for requests with bodies seems like the right approach to me. Since we support both `POST` in all such cases there's no need for the additional complexity of a toggle?

**Comment by Mpdreamz** [comment]
All low level clients either allow you to either pass any HTTP method or expose all the API + allowed http method combinations. 

Defaulting to `POST` for high level clients and **not** making this configurable makes sense though, it's also the approach the high level `c#` client `NEST` takes. 

In some cases `NEST` is smart enough to revert back to a `GET` automatically e.g if only the query on the querystring `(?q=)` is provided on `_search` or if the [source common parameter](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/_common.json#L20-L23) is provided. This is not really standardized though.

**Comment by asmita2201** [comment]
@javanna  Please advise when would this be released?

**Comment by javanna** [comment]
@asmita2201 you can check the labels of the PR that closed this issue: #28342 . It will be released with 6.3.0. Unfortunately the change went in a tiny bit too late for 6.2 .

**Comment by javanna** [comment]
@asmita2201 I am now wondering if we should have merged this as a bug and backported to 6.2 branch (at least it would be released with 6.2.1) and maybe also to 5.6 (it would go out with 5.6.8). I take it that this is a blocker for you?

**Comment by asmita2201** [comment]
Actually I was trying to use 6.3.0 for this change and maven is not able to download the JAR. Is this available?
IF yes, can you please provide the actual JAR?

<dependency>
    <groupId>org.elasticsearch.client</groupId>
    <artifactId>elasticsearch-rest-high-level-client</artifactId>
    <version>6.3.0</version>
</dependency>

**Comment by asmita2201** [comment]
@javanna  - YEs please treat that as a blocker. We are unable to get the right JAR for this.

**Comment by javanna** [comment]
@asmita2201 6.3.0 is not released yet, you can get a snapshot from `https://snapshots.elastic.co/maven/` . That said I wouldn't use a snapshot in production.

**Comment by asmita2201** [comment]
@javanna can you advise how to access?
I get this page:
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>maven/</Key>
<RequestId>ED6094AC6235E7A6</RequestId>
<HostId>
WqwhJ5VYiGtlOkX45a8VCFtGHD+DNdXqSAgxuUqhH40UK4VlomzfA4oVaeLkoP9I2cfCHxlb8yU=
</HostId>
</Error>

**Comment by javanna** [comment]
@asmita2201 we just realized that some recent snapshots are missing in our snapshots repo. We are fixing that as we speak, will let you know once it's fixed so you can try again.

**Comment by asmita2201** [comment]
@javanna  could you please provide an ETA for this?

**Comment by javanna** [comment]
hi @asmita2201 the snapshot artifacts should be back up. Yet the URL the I gave you above needs to be configured in your maven build, it is not directly accessible from a browser.

**Comment by asmita2201** [comment]
@javanna 
I have tried using the maven build. The rest-high-level-cleint snapshot jar is getting downloaded. But one of the dependencies(org.elasticsearch:elasticsearch-secure-sm:jar:6.3.0-SNAPSHOT) needed by therest-high-level-cleint jar is not getting downloaded. 

Failure to find org.elasticsearch:elasticsearch-secure-sm:jar:6.3.0-SNAPSHOT in http://s3.amazonaws.com/download.elasticsearch.org/lucenesnapshots/00142c9 was cached in the local repository, resolution will not be reattempted until the update interval of elastic-lucene-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR]

**Comment by mgreau** [comment]
Hi @asmita2201 
Good catch. I have reproduced the problem and I opened #28658 to track and fix the problem.
Thanks

**Comment by asmita2201** [comment]
@mgreau @javanna 
Thanks, we are able to get the JAR now. Can you confirm:
when would this officially be released?
what version of elastic supports this?
