### ISSUE TITLE
Hot and Warm architecture to be extended for Disk Allocation within Nodes

### ISSUE THREAD

**Issue by antonpious** [elastic/elasticsearch#28323]
In Elastic search one can store data, the data can be divided into multiple types, to name a few important data, data that is regular etc.
The current hot /warm feature splits the nodes which handle the hot and warm indices, which cause nodes to be reserved for hot and warm indices.  What this causes is having to have reservation on nodes for hot and warm leading to wastage of computing resource when the load on both hot and warm nodes are not uniform.
This feature needs to be extended to include this at data storage.

At present most cloud provider have different types of storage namely IO1, GP2 in case of AWS. Due to the high IOPS requirement one could mount a high IO disk to the cluster designate this as hot and a normal IO disk namely GP2 to the same cluster and designate this as warm and so forth. Based on the cost and customer preference we could place the data between these storage devices.

We can then use the same nodes but when indices are created we need to specify which disk type these needs to be stored and place those in these storage devices. When the use of the data is complete we could move these to warm or have both hot and warm data storage devices seamless to the cluster. The client can decide where they need to be place the data depending on the need causing effective shared utilization on all nodes with each node's CPU and memory utilized and the difference is present only on the data store.

**Comment by DaveCTurner** [comment]
We discussed this in our Fix-it Friday meeting. The recommended way to do this is simply to run two nodes on the same host, one using the fast disk and the other the slow one. There would be a bit of a benefit to supporting this within a single node, but the feeling was that this wouldn't outweigh the extra complexity it'd introduce.

**Comment by DaveCTurner** [comment]
This feature request is an interesting idea but we don't think that it is something we should pursue. We prefer to close this issue as a clear indication that we are not going to work on this at this time. We are always open to reconsidering this in the future based on compelling feedback; despite this issue being closed please feel free to leave feedback on the proposal (including +1s).
