### ISSUE TITLE
why es server connect to client，than  throw connect timeout

### ISSUE THREAD

**Issue by fightingaman** [elastic/elasticsearch#28331]
Elasticsearch: 5.2
JVM:1.8
OS:Linux

problem： I use es-rest client api，than the es-server throw connect timeout. It could be this.
I can't imagine why  es-server connect to client?
L :nodeMaster IPAddress , R: client IPAddress
![image](https://user-images.githubusercontent.com/19791332/35263129-972556ec-0052-11e8-90b9-39f8a0c1017f.png)

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support. And please don't use images for code when posting there.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
