### ISSUE TITLE
index.blocks.read_only prevents _status

### ISSUE THREAD

**Issue by devoncrouse** [elastic/elasticsearch#2833]
In trying to protect completed daily indices from future changes, we tried setting index.blocks.read_only : true, but found that we were then unable to query _status, and head  plugin could no longer display shard information.  I think this best illustrates the behavior we're seeing, but not expecting:

curl -XGET 'http://localhost:9200/messages_20130301/_status'
{"error":"ClusterBlockException[blocked by: [FORBIDDEN/5/index read-only (api)];]","status":403}

Also, as an aside: what's the difference between index.blocks.read_only : true and index.blocks.write : true (which lets me query status and prevents delete?)

**Comment by tlrx** [comment]
Closed in af79a2ae49073cd18d415d3c7bc4a798c6ffd9f1
