### ISSUE TITLE
upgrading 1.7.5 to 5X

### ISSUE THREAD

**Issue by danrod1971** [elastic/elasticsearch#28337]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 2.4.6, Build: 5376dca/2017-07-18T12:17:44Z, JVM: 1.8.0_151

**Plugins installed**: [none]

**JVM version** (`java -version`):
Version: 2.4.6, Build: 5376dca/2017-07-18T12:17:44Z, JVM: 1.8.0_151

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
Regarding the upgrade guide to upgrade ES from 1.7.5 to 5X we need to upgrade first to 2.4.
I follow the step describe on https://www.elastic.co/guide/en/elasticsearch/reference/2.4/setup-upgrade.html but the cluster does not restart. The log complains on the mapping for the index ( see log attached )

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. restore snap from production
 2. follow https://www.elastic.co/guide/en/elasticsearch/reference/2.4/restart-upgrade.html
 
[es-cluster.log](https://github.com/elastic/elasticsearch/files/1655955/es-cluster.log)

**Provide logs (if relevant)**:

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

```
[2018-01-23 12:07:56,475][ERROR][bootstrap                ] Guice Exception: java.lang.IllegalStateException: unable to upgrade the mappings for the index [index1], reason: [[zone_surveillance] is defined as a field in mapping [Alarm-GardanneDRS] but this name is already used for an object in other types]
Likely root cause: java.lang.IllegalArgumentException: [zone_surveillance] is defined as a field in mapping [Alarm-GardanneDRS] but this name is already used for an object in other types
```

You need to look at all breaking changes. In clear here, you will probably need to change your model and your mapping.
Which is actually a good news as from 6.0 you can't have multiple types per index.
