### ISSUE TITLE
Can the multi-GET API be expected to return results in the same order as the request?

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#28343]
This question was initially raised on discuss: can clients rely on the order of elements in the response, or do they need to make sure to read the `_index` and `_id` properties to match response items with request items?

https://discuss.elastic.co/t/multi-get-api-reference-and-results-order/116689

**Comment by ywelsch** [comment]
I would say yes, as the REST tests currently rely on this property as well:

https://github.com/elastic/elasticsearch/blob/b10d16619098f99bdd56591004da68c5352b5acb/rest-api-spec/src/main/resources/rest-api-spec/test/mget/10_basic.yml#L16-L45

**Comment by jpountz** [comment]
Mostly because I couldn't see it explicitly stated in the docs. And since the response contains the `_index`, `_type` and `_id`, having the order maintained is not strictly required. There seems to be consensus so I'm making this an adoptme.
