### ISSUE TITLE
ML X pack  Job on Scripted field

### ISSUE THREAD

**Issue by sarvendras** [elastic/elasticsearch#28352]
Hi Team,
Need your advice relating to creating machine learning job.
I am trying to create single metric job for detecting anomalies in mean of some scripted field(which is created with help of injected fields using lucence scripting) but we are getting below error while creating job.

Could not start datafeed for sadads [status_exception] datafeed [datafeed-sadads] cannot retrieve field [Scripted field] because it has no mappings
Could not start datafeed: [status_exception] datafeed [datafeed-sadads] cannot retrieve field [Scripted field]] because it has no mappings

Pls suggest that ML Jobs can be created only with normal fields and can not be created with scripted fields?

Thanks in advance

**Comment by dadoonet** [comment]
I saw you opened that question there https://discuss.elastic.co/t/ml-job-on-scripted-field/116820/1

Which is the right place for this. I'm closing this "issue".
