### ISSUE TITLE
Documentation of section "Limiting the number of nested fields" is not understandable and it is an important topic

### ISSUE THREAD

**Issue by alexmorosmarco** [elastic/elasticsearch#28363]
**Elasticsearch version** (`bin/elasticsearch --version`): 2.4 and all the following ones

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
Hi, I write because i think there is an important part of the documentation that I see really weak because I think the explanation is not good enough to understand it and it is an important topic.
I am talking about the section "Limiting the number of nested fields" of the documentation (https://www.elastic.co/guide/en/elasticsearch/reference/6.1/nested.html#_limiting_the_number_of_literal_nested_literal_fields).
Let's take into account the given example having an array named `user`, defined with `nested` datatype, that can have user **objects** inside.

It mentions that **Indexing a document with 100 nested fields actually indexes 101 documents as each nested document is indexed as a separate document.**.
What does that sentence mean with "100 nested fields"?
* is it talking about a case where we would have 100 **arrays** like `user`, `car` and any other arrays?
* or is it talking about having 100 user **objects** inside the array `user`?

It also mentions **To safeguard against ill-defined mappings the number of nested fields that can be defined per index has been limited to 50**.
What does that sentence mean?
* is it talking about that we can only define 50 arrays as `nested` datatype in a document?
* or about that inside an array defined as `nested` we can only have 50 **objects**?
* In addition, taking into account that this is the documentation of the `nested` datatype, I think it should explain that the 50 default value is stored in the property `index.mapping.nested_fields.limit`.

Please could you answer my question and also explain better this topic in the documentation? Maybe solving those doubts and also writing some examples would be fine.
I see the same problem in the documentation of ElasticSearch 2.4, could you also improve it?

As an extra, in the documentation of ElasticSearch 2.4 I do not see any reference in the Mappings documentation that explains about the `index.mapping.nested_fields.limit` parameter.
Couldn't be described somewhere? I first searched for it in the "Index Modules" docu and then in the "Mappings" docu but without luck.

Thanks a lot!

**Comment by andyb-elastic** [comment]
@elastic/es-search-aggs

**Comment by ludovicth** [comment]
> It mentions that Indexing a document with 100 nested fields actually indexes 101 documents as each nested document is indexed as a separate document..
> What does that sentence mean with "100 nested fields"?
> 
> is it talking about a case where we would have 100 arrays like user, car and any other arrays?
> or is it talking about having 100 user objects inside the array user?

=> it talking about having 100 user **objects** inside the array user.

**Comment by HunderlineK** [comment]
Further more, what happens if there are nested items within a nested items.

Let's say, `user` has 10 `blogs` and each blog has `10` comments; does that create 100 documents and violate the limit if it is set to 50?

**Comment by jtibshirani** [comment]
I merged #42686 to try to clarify the points mentioned above. If you have more feedback about this topic and think it could be clarified further, feel free to reopen the issue or to submit a PR.
