### ISSUE TITLE
persistent setting [discovery.zen.ping.unicast.hosts], not dynamically updateable

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch#28362]
ES: 6.1.1

In trying to move to cluster settings over having things in `elasticsearch.yml`, I'm trying set up my [ZEN discovery settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-zen.html) as documented as follows:
```
PUT /_cluster/settings
{
    "persistent" : {
        "discovery.zen.minimum_master_nodes" : 2,
        "discovery.zen.ping.unicast.hosts": ["host1", "host2"]
    }
}
```

In response I get:
```
persistent setting [discovery.zen.ping.unicast.hosts], not dynamically updateable
```
Is this setting still required to be in the `elasticsearch.yml` file?

**Comment by ywelsch** [comment]
yes, because of the chicken-and-egg problem. That setting is used to make sure that nodes can form a cluster. If it were to become a cluster setting, you would need the cluster to be up to set or change it.

**Comment by tdoman** [comment]
@ywelsch Ok, thanks for the quick response, much appreciated.  Accordingly, I will also try not to count my chickens before they hatch.  ;)
