### ISSUE TITLE
Allow use of search_after within terms aggregation

### ISSUE THREAD

**Issue by snowzach** [elastic/elasticsearch#28378]
I am using the terms aggregation to get unique values (nested terms aggregations actually) but with a very large number of unique terms it becomes problematic. 

It would be great if one of the following would work:

1. The search_after on the outer query applied to the inner aggregation. Seeing as you can retrieve the outer results, I could see how this might not be desirable.
2. The terms aggregation supported the sort/search_after feature that queries support. 

Either if these would allow you to easily paginate through results. I understand the point of the current partition functionality but I do not believe this would work quite as well/fluid as the search_after functionality which is great for search functionality.

If there's another way to do this, it would be great.  (Can I do something like a range+term aggregation?)

**Comment by jimczi** [comment]
We have a new aggregation called `composite` that allows to paginate a terms aggregation easily. See https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html

**Comment by snowzach** [comment]
@jimczi Thanks a lot. This is exactly what I needed. I saw this page but didn't quite get it before.
