### ISSUE TITLE
failed to start after updating java 

### ISSUE THREAD

**Issue by GurjinderSingh** [elastic/elasticsearch#28377]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 2.4.6, Build: 5376dca/2017-07-18T12:17:44Z, JVM: 1.8.0_161

**Plugins installed**: []

**JVM version** (`java -version`):
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux dhol 4.13.0-31-generic # 34~16.04.1-Ubuntu SMP Fri Jan 19 17:11:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Provide logs (if relevant)**:

Jan 25 13:43:09 localhost systemd[1]: Starting Elasticsearch...
Jan 25 13:43:09 localhost systemd[1]: Started Elasticsearch.
Jan 25 13:43:09 localhost kernel: [ 4096.497555] BUG: unable to handle kernel paging request at 0000000006987877
Jan 25 13:43:09 localhost kernel: [ 4096.497978] IP: 0x6987877
Jan 25 13:43:09 localhost kernel: [ 4096.498385] PGD 80000003dec08067
Jan 25 13:43:09 localhost kernel: [ 4096.498386] P4D 80000003dec08067
Jan 25 13:43:09 localhost kernel: [ 4096.498788] PUD 45335f067
Jan 25 13:43:09 localhost kernel: [ 4096.499185] PMD 0
Jan 25 13:43:09 localhost kernel: [ 4096.499582]
Jan 25 13:43:09 localhost kernel: [ 4096.500359] Oops: 0010 [# 19] SMP PTI
Jan 25 13:43:09 localhost kernel: [ 4096.500746] Modules linked in: xt_owner xt_tcpudp nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack libcrc32c iptable_filter ip_tables x_tables nls_iso8859_1 snd_hda_codec_hdmi snd_hda_codec_realtek snd_hda_codec_generic snd_hda_intel snd_hda_codec snd_hda_core snd_hwdep snd_pcm intel_rapl snd_seq_midi x86_pkg_temp_thermal snd_seq_midi_event intel_powerclamp coretemp snd_rawmidi kvm_intel kvm snd_seq irqbypass snd_seq_device snd_timer crct10dif_pclmul crc32_pclmul ghash_clmulni_intel pcbc aesni_intel aes_x86_64 crypto_simd glue_helper cryptd snd intel_cstate intel_rapl_perf serio_raw soundcore mei_me mei shpchp hci_uart btbcm serdev btqca btintel bluetooth ecdh_generic intel_lpss_acpi intel_lpss mac_hid tpm_crb acpi_als acpi_pad kfifo_buf industrialio parport_pc ppdev lp parport autofs4
Jan 25 13:43:09 localhost kernel: [ 4096.503808]  mxm_wmi i915 i2c_algo_bit drm_kms_helper syscopyarea psmouse sysfillrect sysimgblt fb_sys_fops alx drm nvme ahci mdio nvme_core libahci wmi video pinctrl_sunrisepoint i2c_hid pinctrl_intel hid
Jan 25 13:43:09 localhost kernel: [ 4096.504794] CPU: 0 PID: 28844 Comm: java Tainted: G      D         4.13.0-31-generic #34~16.04.1-Ubuntu
Jan 25 13:43:09 localhost kernel: [ 4096.505300] Hardware name: MSI MS-7A57/Z270 MPOWER GAMING TITANIUM (MS-7A57), BIOS A.00 02/23/2017
Jan 25 13:43:09 localhost kernel: [ 4096.505802] task: ffff8dc21c2caf80 task.stack: ffff9c6a47de0000
Jan 25 13:43:09 localhost kernel: [ 4096.506295] RIP: 0010:0x6987877
Jan 25 13:43:09 localhost kernel: [ 4096.506778] RSP: 0018:ffff9c6a47de3f50 EFLAGS: 00010202
Jan 25 13:43:09 localhost kernel: [ 4096.507252] RAX: 00000000000003e7 RBX: 0000000000000000 RCX: 00007f5fa29e94d9
Jan 25 13:43:09 localhost kernel: [ 4096.507722] RDX: 00007f5f9c5c39b0 RSI: 000000004d73aa93 RDI: 0000000000000000
Jan 25 13:43:09 localhost kernel: [ 4096.508181] RBP: 0000000000000000 R08: 00007f5fa1e4fb64 R09: 000000000000000c
Jan 25 13:43:09 localhost kernel: [ 4096.508630] R10: 0000000006987877 R11: ffff8dc21c2caf80 R12: 0000000000000000
Jan 25 13:43:09 localhost kernel: [ 4096.509067] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
Jan 25 13:43:09 localhost kernel: [ 4096.509494] FS:  00007f5fa34ec700(0000) GS:ffff8dc22ec00000(0000) knlGS:0000000000000000
Jan 25 13:43:09 localhost kernel: [ 4096.509918] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Jan 25 13:43:09 localhost kernel: [ 4096.510337] CR2: 0000000006987877 CR3: 000000015ae48003 CR4: 00000000003606f0
Jan 25 13:43:09 localhost kernel: [ 4096.510754] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
Jan 25 13:43:09 localhost kernel: [ 4096.511169] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
Jan 25 13:43:09 localhost kernel: [ 4096.511583] Call Trace:
Jan 25 13:43:09 localhost kernel: [ 4096.511993]  ? entry_SYSCALL_64_fastpath+0x33/0xa3
Jan 25 13:43:09 localhost kernel: [ 4096.512403] Code:  Bad RIP value.
Jan 25 13:43:09 localhost kernel: [ 4096.512812] RIP: 0x6987877 RSP: ffff9c6a47de3f50
Jan 25 13:43:09 localhost kernel: [ 4096.513222] CR2: 0000000006987877
Jan 25 13:43:09 localhost kernel: [ 4096.513631] ---[ end trace 71ffa03814cb197b ]---

**Comment by jasontedor** [comment]
Duplicates #28349, duplicate #28354; you have a buggy kernel and you should rollback.

**Comment by GurjinderSingh** [comment]
thanks now working fine downgraded  to version 4.13.0-26-generic

Linux dhol 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux


thanks you

**Comment by jasontedor** [comment]
You're welcome.
