### ISSUE TITLE
ElasticSearch 2.4.6 does not start at all without any error message Ubuntu 16.04

### ISSUE THREAD

**Issue by tamimcsedu19** [elastic/elasticsearch#28384]
**Elasticsearch version** (`bin/elasticsearch --version`): 2.4.6
* Java Version: java version "1.8.0_121"
* OS: Ubuntu 16.04
Trying to start elasticsearch 2.4.6 with `./elasticsearch` in the bin direcytory. It just closes and nothing happens. See the below screenshot

![screenshot from 2018-01-25 19-05-33](https://user-images.githubusercontent.com/5927446/35425209-1ed84e80-0294-11e8-8faf-732edc59c99b.png)

Stepping through the starter scripts, I can see that  it comes until `exec "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" org.elasticsearch.bootstrap.Elasticsearch start "$@"` line and then closes.

However, please note that elasticsearch 5.* does not have this problem and starts normally without 
![screenshot from 2018-01-25 19-10-00](https://user-images.githubusercontent.com/5927446/35425211-231bea9c-0294-11e8-8e8e-cfabfba8f277.png)

Can anyone tell me what could possibly be causing this? Or at least where can I find any error log. No error is logged in logs file of elasticsearch.

Strace output:
![strace](https://user-images.githubusercontent.com/5927446/35425736-51397cec-0298-11e8-8838-f907ef5c840f.png)

**Comment by jasontedor** [comment]
From your 5.6.6 output I can see the you're on kernel 4.13.0-31. This kernel has a bad bug, see #28349. You can check this by looking at your kernel logs (e.g., `dmesg`) after you try to start 2.4.6.

Duplicates #28349
