### ISSUE TITLE
no http response after 5 requests

### ISSUE THREAD

**Issue by nrobert13** [elastic/elasticsearch#28397]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 2.3.5, Build: 90f439f/2016-07-27T10:36:52Z, JVM: 1.8.0_60 

**Plugins installed**: []

**JVM version** (`java -version`):
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux test02 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

facing a weird behavior with one node in a 5 node cluster. 
If I query the http endpoint on one of the nodes, sometimes I don't get any response. The curl is local, so no network involved. Noticed, if I repeat quickly the same curl, it responds 5 times and the 6th just hangs for hours... I tried to strace the curl and it hangs in a recvfrom syscall, also watched the traffic with tcpdump, and not packets are coming from the process.

After the 6th requests the next 5 requests will get answers and the 6th none again, so the pattern is reproducible.

the other nodes work well. the cluster state is green. thread_pools queues are mostly 0     

ex. curl: 
`curl localhost:9200/_cluster/state > /dev/null`

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. 
 2.
 3.

**Provide logs (if relevant)**:
There are no messages neither in the es logs or in system logs.

**Comment by jasontedor** [comment]
Version 2.3.5 is end of life and we no longer support it. I encourage you to upgrade to a supported version. Note that 2.4.x is still supported, but not maintained, and will be end of life at the end of February. This means we will support it, but if there is a bug here we will not fix it.
