### ISSUE TITLE
Cluster does not report the exact issue

### ISSUE THREAD

**Issue by cemremengu** [elastic/elasticsearch#28400]
Using `docker.elastic.co/elasticsearch/elasticsearch:6.1.2`.

I have a cluster consisting of 2 nodes with `discovery.zen.minimum_master_nodes=2`. Node 2 goes down and when try to execute a query on Node 1 via http, I begin to get a login popup followed by an authentication exception.

If I cancel login popup, it says `Security index is not on the current version - the native realm will not be operational until the upgrade API is run on the security index` which is (I think) irrelevant. 

Of course required monitoring steps should be taken in order to detect such a problem but it would be nice if it said, at least, `cluster inoperable` instead of some misleading error message.

**Comment by bleskes** [comment]
It seems you're using Kibana ans well as Elasticsearch. I'm not sure you meant that something in the UI (Kibana) should change or something in Elasticsearch. I suggest you open an issue on our forums at http://discuss.elastic.co under the project that you feel is most relevant and then we can figure out what should go on github and where. I'm going close this now. We can always reopen if needed.
