### ISSUE TITLE
org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of org.elasticsearch.transport.TransportService

### ISSUE THREAD

**Issue by reeenz20** [elastic/elasticsearch#28414]
Hi guys, I have this error on elasticsearch. The logs keeps on increasing. Urgently needed help here. Thank you! :)

org.elasticsearch.common.util.concurrent.EsRejectedExecutionException: rejected execution of org.elasticsearch.transport.TransportService$7@52bbdff1 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@49c9d421[Running, pool size = 7, active threads = 7, queued tasks = 1000, completed tasks = 7265472

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
