### ISSUE TITLE
Incorrect the number of hits return when use post_filter in scroll

### ISSUE THREAD

**Issue by Nao-Mk2** [elastic/elasticsearch#28411]
**Elasticsearch version**: 6.1.1

**OS version**: CentOS 7

**JVM version (java -version)**:
```
$ java -version
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)
```

**Description of the problem including expected versus actual behavior:**
I use post_filter in scroll API. Elasticsearch returns correct hits.total.
However, when hits.hits array is empty, Elasticsearch returns incorrect the total actual number of retrieved documents.

**Steps to reproduce**:
*Template*
```json
PUT _template/scroll_test_template
{
  "index_patterns": "scroll-test",
  "mappings": {
    "doc": {
      "properties":
 {
        "keyword_field": {
          "type": "keyword"
        }
      }
    }
  }
}
```
*Document*
```json
POST scroll-test/doc/_bulk
{ "index": {} }
{ "keyword_field" : "value00000" }
{ "index": {} }
{ "keyword_field" : "value00001" }
{ "index": {} }
{ "keyword_field" : "value00002" }
   .
   .
   .
{ "index": {} }
{ "keyword_field" : "value49997" }
{ "index": {} }
{ "keyword_field" : "value49998" }
{ "index": {} }
{ "keyword_field" : "value49999" }
```
*Query*
```json
GET scroll-test/_search?scroll=1m
{
  "size": 50,
  "post_filter": {
    "bool": {
      "must": [
        {
          "wildcard": {
            "keyword_field": "value*010*"
          }
        }     
      ]
    }
  }
}

GET /_search/scroll/
{
  "scroll" : "1m",
  "scroll_id": "{_scroll_id}"
}
```
hits.total is 199. However, when hits.hits array is empty, the total actual number of retrieved documents is 111.

**Comment by colings86** [comment]
@jimczi could you take a look at this?

**Comment by jimczi** [comment]
Thanks for reporting and for providing a simple recreation @Nao-Mk2 .
The issue in your case appears only if you use a non-scoring query (wildcard query uses a constant score) and `post_filter` in a `scroll` context. I opened https://github.com/elastic/elasticsearch/pull/28459 to fix this.

**Comment by Nao-Mk2** [comment]
Awesome, thanks for the quick response and fix!
