### ISSUE TITLE
A deleted synonym still yields search results

### ISSUE THREAD

**Issue by IamJeffG** [elastic/elasticsearch#28412]
**Elasticsearch version** 5.6.4
(via `docker -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "xpack.security.enabled=false" docker.elastic.co/elasticsearch/elasticsearch:5.6.4`)

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "1.8.0_141"

**OS version** (`uname -a` if on a Unix-like system): `Linux 00aa6f7d916f 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

After re-defining a synonym analyzer's synonym list, queries for *removed* synonyms still yield hits.

* I verify that the synonym list really was updated, because *new* synonyms added now yield hits that weren't before.
* This happens whether I list the synonyms in-line or in a file via `synonyms_path`.

**Steps to reproduce**:

First, start docker:
```bash
docker -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "xpack.security.enabled=false" docker.elastic.co/elasticsearch/elasticsearch:5.6.4
```

Now define a synonym list and analyzer in a new index
```bash
curl -XPUT localhost:9200/foods -d '{
  "settings" : {
    "analysis": {
      "analyzer": {
        "units_compatibility": {
          "tokenizer": "standard",
          "filter": ["units_compatibility_synonyms"]
        }
      },
      "filter": {
        "units_compatibility_synonyms": {
          "type": "synonym",
          "synonyms": [
            "cups,pints,gallons,liters,milliliters",
            "grams,ounces,pounds"
          ]
        }}}},
  "mappings" : {
    "food" : {
      "properties" : {
        "unit_of_measure" : {
          "type" : "text",
          "analyzer" : "units_compatibility"
          },
          "name" : {
            "type" : "text"
          },
          "value" : {
            "type" : "float"
          }
        }}}}}'
# {"acknowledged":true,"shards_acknowledged":true,"index":"foods"}
```

Add some docs:
```bash
curl -XPUT localhost:9200/foods/food/1 -d '{"value":1, "unit_of_measure":"pints", "name":"milk"}'
curl -XPUT localhost:9200/foods/food/2 -d '{"value":2, "unit_of_measure":"pounds", "name":"potatoes"}'
```

Verify the analyzer works by querying for a synonym:
```bash
curl 'localhost:9200/foods/food/_search?q=unit_of_measure:milliliters'
# 1 hit: `[_id=1]`
```

Now I need to update the synonym list. I need to add "kilograms" and delete "gallons".  I can do this by re-PUTting the index `/_settings` while the index is closed.

```bash
curl -XPOST localhost:9200/foods/_close
# {"acknowledged":true}

curl -XPUT localhost:9200/foods/_settings -d '{
  "settings" : {
    "analysis": {
      "analyzer": {
        "units_compatibility": {
          "tokenizer": "standard",
          "filter": ["units_compatibility_synonyms"]
        }
      },
      "filter": {
        "units_compatibility_synonyms": {
          "type": "synonym",
          "synonyms": [
            "cups,pints,liters,milliliters",
            "grams,kilograms,ounces,pounds"
          ]
        }}}},
  "mappings" : {
    "food" : {
      "properties" : {
        "unit_of_measure" : {
          "type" : "text",
          "analyzer" : "units_compatibility"
          },
          "name" : {
            "type" : "text"
          },
          "value" : {
            "type" : "float"
          }
        }}}}}'
# {"acknowledged":true}

curl -XPOST 'localhost:9200/foods/_open'
# {"acknowledged":true}
```

I can see the update worked.  When querying for the newly added synonym, kiligrams, I get the right document back (which used "pounds").
```bash
curl 'localhost:9200/foods/food/_search?q=unit_of_measure:kilograms'
# 1 hit: `[_id=2]`
```

*Here's the bug:* I have removed "gallons" from the synonym list entirely, yet querying for it still gives hits as if "gallons" remained a synonym!
```bash
curl 'localhost:9200/foods/food/_search?q=unit_of_measure:gallons'
# 1 hit: `[_id=1]`
```

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

It does not look like a bug to me because you did not reindex your documents and you are using bi-directional synonyms here which means that the inverted index contains all the versions of your term.

That's why it matches at query term because the term you are looking for has been indexed at index time.

I believe that if you apply synonyms at search time only you will have a different behavior.

**Comment by IamJeffG** [comment]
Thanks for responding and my apologies for posting this in the wrong place.

> if you apply synonyms at search time only

For future friends who might find this, the way to accomplish your recommendation is by changing the field mapping as follows (both at index creation and when editing the index settings).  I confirmed it works well!

```json
        "unit_of_measure" : {
          "type" : "text",
          "analyzer": "standard",
          "search_analyzer" : "units_compatibility"
          },
```
