### ISSUE TITLE
Deleted .kibana index and can't recreate it correctly (Your Kibana index is out of date, reset it or use the X-Pack upgrade assistant.)

### ISSUE THREAD

**Issue by mimi2204** [elastic/elasticsearch#28420]
**Describe the feature**: .kibana index

 

**Elasticsearch version**: 6.1.0

**OS version**: centos

**Description of the problem including expected versus actual behavior**:

I deleted my .kibana index and when it is recreated by me (by adding an index pattern) or Kibana I get the following error:
`Your Kibana index is out of date, reset it or use the X-Pack upgrade assistant.`

P.S. I haven't upgraded from a previous version. Kibana was working perfectly fine until I deleted the index.

**Steps to reproduce**:

 1. Delete .kibana index
 2. Add an index pattern
 3. Cluster status turns red. Give the error: Your Kibana index is out of date, reset it or use the X-Pack upgrade assistant.

**Comment by jasontedor** [comment]
There is a dedicated repository for [Kibana](https://github.com/elastic/kibana) where I think you will receive better guidance.
