### ISSUE TITLE
WordDelimiterTokenFilter does not produce expected tokens with split_on_case_change and preserve_original set to true

### ISSUE THREAD

**Issue by techninja24** [elastic/elasticsearch#28439]
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 5.4.1, Build: 2cfe0df/2017-05-29T16:05:51.443Z

**Plugins installed**: []

**JVM version** (`java -version`):
 JVM: 1.8.0_151

**OS version** (`uname -a` if on a Unix-like system):
Windows 10

**Description of the problem including expected versus actual behavior**:
When using word delimiter token filter some expected tokens are not generated.

When I try to analyze the text "ElasticSearch.TestProject"

I expect the tokens elastic, search, test, project, elasticsearch, testproject, elasticsearch.testproject to be generated since I have split_on_case_change, split_on_numerics on and using a whitespace tokenizer. 

But Actually I only see following tokens -
elasticsearch.testproject, elastic, search, test, project

**Steps to reproduce**:
 **1. Create index** 
_PUT testindex
 {
    "settings" : {
        "index" : {
            "number_of_shards" : 2, 
            "number_of_replicas" : 2 
        },
    "analysis": {
      "filter": {
        "wordDelimiter": {
          "type": "word_delimiter",
          "generate_word_parts": "true",
          "generate_number_parts": "true",
          "catenate_words": "false",
          "catenate_numbers": "false",
          "catenate_all": "false",
          "split_on_case_change": "true",
          "preserve_original": "true",
          "split_on_numerics": "true",
          "stem_english_possessive": "true"
        }
      },
      "analyzer": {
		"content_analyzer": {
          "type": "custom",
          "tokenizer": "whitespace",
          "filter": [
            "asciifolding",
            "wordDelimiter",
            "lowercase"
          ]
        }
      }
    }
	}
 }_

 **2. Analyze Text-**
_POST testindex/_analyze 
{
  "analyzer": "content_analyzer",
  "text": "ElasticSearch.TestProject"
}_

**Following tokens are generated-**

{
"token": "elasticsearch-testproject",
"start_offset": 0,
"end_offset": 25,
"type": "word",
"position": 0
}
,
{
"token": "elastic",
"start_offset": 0,
"end_offset": 7,
"type": "word",
"position": 0
}
,
{
"token": "search",
"start_offset": 7,
"end_offset": 13,
"type": "word",
"position": 1
}
,
{
"token": "test",
"start_offset": 14,
"end_offset": 18,
"type": "word",
"position": 2
}
,
{
"token": "project",
"start_offset": 18,
"end_offset": 25,
"type": "word",
"position": 3
}

**Expected Result:**
Besides the above tokens even elasticsearch and testproject should be generated. such that the phrase query "elasticsearch testproject" should also match.

**Comment by techninja24** [comment]
Another  example could be -  Text = "Super-Duper-0-AutoCoder" has a token autocoder while "Super-Duper-AutoCoder" doesnot generate the token autocoder.

**Comment by romseygeek** [comment]
Hi @techninja24, this is better suited to the discussion forums at https://discuss.elastic.co - we try and reserve github issues for bugs and feature requests, and this is more of a question on the (admittedly deeply weird) behaviour of WordDelimiterFilter.  I'm going to close this, but do please ask this on the forums.

**Comment by techninja24** [comment]
Thanks @romseygeek! 

I did ask related questions [Question1](https://discuss.elastic.co/t/worddelimitertokenfilter-doesnt-seem-to-be-generating-expected-tokens/116476) and [Question2](https://discuss.elastic.co/t/worddelimitertokenfilter-used-twice-in-same-analyzer-with-different-configurations-causes-issues/116259) on the forum but there was no response. 
This case seems like a genuine issue to me. If it is an issue where can I get the confirmation and should this be filed on ES or Lucene?
