### ISSUE TITLE
disk usage become very large after replace pathdata to a 2T hard disk

### ISSUE THREAD

**Issue by sccds** [elastic/elasticsearch#28436]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 6.0.1, Build: 601be4a/2017-12-04T09:29:09.525Z, JVM: 1.8.0_151

**Plugins installed**: [x-pack, ik-anlyzer]

**JVM version** (`java -version`): 
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux xxx 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. A 3 nodes ES cluster, original path.data is [/home/data1, /root/data2]. Original disk size is about 100G
 2. Add a 2T hard disk. change path.data to /home/data3 (which is the mount path of new hard disk)
 3. when change the path data, I did one by one. Stop 1/3 ES service, change path data config, restart ES, wait until cluster status to green.
 4. after change pathdata, the data usage become very large. (5G used, 101 available) before, (95G used, 1.6T available) after. It looks like the rate keeps 5% ?

![image](https://user-images.githubusercontent.com/6340346/35550045-927b17c8-05c3-11e8-9f8e-5dba202f8513.png)

my size of data doesn't change at all.  But used data changed a lot.

My index are (5 shards 1 replica)

**Provide logs (if relevant)**:

**Comment by romseygeek** [comment]
Hi @sccds, this question is better suited to the support forums at https://discuss.elastic.co - we try and keep github issues for bug reports and feature requests.  I'm going to close this issue here, but please do ask this on the forums instead.

**Comment by sccds** [comment]
@romseygeek Thanks, I will take care of it in the future
