### ISSUE TITLE
awaitBusy returns a boolean!?!

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#28450]
So I've been using `awaitBusy` incorrectly for a while and it looks like I'm not alone. I'd sort of figured it worked like `assertBusy` and would throw an exception if the thing didn't happen in time. It doesn't. It returns a boolean.

I scanned the usages and see a good 15% of calls to `awaitBusy` don't assert that the result is true. I figure most of those are bugs waiting to happen.

Most of the calls to `awaitBusy` ultimately `assertTrue` on the result. Maybe someone just goes and cleans all these up? They are sneaky enough that something like the logger usage check might be useful here. Or actually throwing the exception. I dunno. Discuss?

**Comment by jpountz** [comment]
Agreed this is trappy.

> They are sneaky enough that something like the logger usage check might be useful here. Or actually throwing the exception. I dunno.

If there are arguments to keep the boolean return value then I'd also like to rename to eg. `tryAwaitBusy` (in the same spirit as `tryLock`) so that it is more obvious there is a return value and it needs to be checked.

**Comment by dakrone** [comment]
We discussed this in fix-it-Friday and decided that we'd like to remove `awaitBusy` in favor of `assertBusy`
