### ISSUE TITLE
BUILD FAILURE-2.4.4 SNAPSHOT

### ISSUE THREAD

**Issue by harshbajaj16** [elastic/elasticsearch#28454]
Hi,

can somebody look into below error which i'm getting on eclipse for 2.4.4 snapshot only.

INFO] ------------------------------------------------------------------------
[INFO] Building Distribution: Parent POM 2.4.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Build Tools and Resources .......................... SUCCESS [  2.592 s]
[INFO] Rest API Specification ............................. SUCCESS [  4.579 s]
[INFO] Elasticsearch: Parent POM .......................... SUCCESS [ 19.496 s]
[INFO] Elasticsearch: Core ................................ SUCCESS [03:29 min]
[INFO] Distribution: Parent POM ........................... FAILURE [  0.169 s]
[INFO] Integration Test Package: ZIP ...................... SKIPPED
[INFO] Module: Parent POM ................................. SKIPPED
[INFO] Module: Language: Expression ....................... SKIPPED
[INFO] Module: Language: Groovy ........................... SKIPPED
[INFO] Module: Reindex .................................... SKIPPED
[INFO] Distribution: TAR .................................. SKIPPED
[INFO] Distribution: ZIP .................................. SKIPPED
[INFO] Distribution: Deb .................................. SKIPPED
[INFO] Plugin: Parent POM ................................. SKIPPED
[INFO] Plugin: Analysis: Japanese (kuromoji) .............. SKIPPED
[INFO] Plugin: Analysis: Smart Chinese (smartcn) .......... SKIPPED
[INFO] Plugin: Analysis: Polish (stempel) ................. SKIPPED
[INFO] Plugin: Analysis: Phonetic ......................... SKIPPED
[INFO] Plugin: Analysis: ICU .............................. SKIPPED
[INFO] Plugin: Cloud: Google Compute Engine ............... SKIPPED
[INFO] Plugin: Cloud: Azure ............................... SKIPPED
[INFO] Plugin: Cloud: AWS ................................. SKIPPED
[INFO] Plugin: Delete By Query ............................ SKIPPED
[INFO] Plugin: Discovery: Multicast ....................... SKIPPED
[INFO] Plugin: Language: JavaScript ....................... SKIPPED
[INFO] Plugin: Language: Python ........................... SKIPPED
[INFO] Plugin: Mapper: Attachments ........................ SKIPPED
[INFO] Plugin: Mapper: Murmur3 ............................ SKIPPED
[INFO] Plugin: Mapper: Size ............................... SKIPPED
[INFO] Plugin: JVM example ................................ SKIPPED
[INFO] Plugin: Example site ............................... SKIPPED
[INFO] QA: Parent POM ..................................... SKIPPED
[INFO] QA: Smoke Test Plugins ............................. SKIPPED
[INFO] QA: Smoke Test Multi-Node IT ....................... SKIPPED
[INFO] QA: Smoke Test Client .............................. SKIPPED
[INFO] QA: Smoke Test Command Line Params ................. SKIPPED
[INFO] QA: Smoke Test Reindex with Groovy ................. SKIPPED
[INFO] QA: Backwards Compatibility ........................ SKIPPED
[INFO] QA: BWC: Shared .................................... SKIPPED
[INFO] QA: BWC: Two Versions Parent ....................... SKIPPED
[INFO] QA: BWC: Current ................................... SKIPPED
[INFO] QA: BWC: 2.0 ....................................... SKIPPED
[INFO] QA: BWC: 2.1 ....................................... SKIPPED
[INFO] QA: BWC: 2.2 ....................................... SKIPPED
[INFO] QA: BWC: 2.3 ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:59 min
[INFO] Finished at: 2018-01-31T13:35:50+05:30
[INFO] Final Memory: 63M/771M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project distributions: Could not resolve dependencies for project org.elasticsearch.distribution:distributions:pom:2.4.4-SNAPSHOT: Failure to find org.elasticsearch:elasticsearch:jar:tests:2.4.4-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of oss-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 

thanks in advance.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

2.4.4 has been released BTW.
