### ISSUE TITLE
index.translog.sync_interval is not dynamic setting

### ISSUE THREAD

**Issue by fhalde** [elastic/elasticsearch#28451]
```json
{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[a.b.c.d][a.b.c.d:9300][indices:admin/settings/update]"}],"type":"illegal_argument_exception","reason":"Can't update non dynamic settings [[index.translog.sync_interval]] for open indices [[abcd-2018-01-30/rlvnMJlhS2OUGZYkaIOrFw]]"},"status":400}
```

The doc says the field is dynamic but it isnt

**Comment by jasontedor** [comment]
You have to close the index. Note that the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/index-modules.html) specify the settings that can be updated on an open index and `index.translog.sync_interval` is not among them.
