### ISSUE TITLE
Boolean queries with indexed geoshapes break on Elastic Search 6.0

### ISSUE THREAD

**Issue by INRIX-Trang-Nguyen** [elastic/elasticsearch#28456]
For repro steps, please see:

https://discuss.elastic.co/t/error-using-multiple-geospan-queries-as-bool-should-clauses/113945

The http 500 error occur sporadically under high concurrency (ES queries run as part of an EMR Spark job).

The same job without code changes run in ES 5.5 without issues.

**Comment by jkakavas** [comment]
Hi @INRIX-Trang-Nguyen, thank you for your report. We would appreciate if you can format your issue according to the template and offer clear steps for reproduction, as this would allow us to better triage this and offer a solution if necessary.

**Comment by jimczi** [comment]
This is a bug introduced in 6.0 that appears when more than one `geo_shape` query need to fetch pre-indexed shapes in an index. There is a race condition that can lead to an AIOOBE. I opened https://github.com/elastic/elasticsearch/pull/28458 to fix it.

**Comment by INRIX-Trang-Nguyen** [comment]
Awesome, thanks for the quick response and fix! Will this make it into ES 6.3?

**Comment by jimczi** [comment]
Yes it will.

**Comment by florinvirdol** [comment]
Hi, guys!
What would be a good way to query points inside multiple pre-indexed shapes (eg.: querying for all points inside all shapes)?

Also, can you please advise what are the ways to get all points in shapes / shapes in shapes with Geo query geo_shape (multiple pre-indexed shape) on big geo-spatial data in ElasticSearch?

When you have some time, please, I put this question to [StackOverflow](https://stackoverflow.com/questions/66448137/ways-to-get-all-points-in-shapes-shapes-in-shapes-with-geo-query-geo-shape-mu) and also to [ElasticSearch discuss forum](https://discuss.elastic.co/t/ways-to-get-all-points-in-shapes-shapes-in-shapes-with-geo-query-geo-shape-multiple-pre-indexed-shape-on-big-geo-spatial-data-in-elasticsearch/266024).

cc: @jimczi @jkakavas @nknize
