### ISSUE TITLE
[CI] Azul Zing JVM crashes on CentOS 7.4

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#28477]
Some recent 6.2 builds have failed on the Azul Zing JVM on CentOS 7.4.

Some examples are:

* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+zing/33/consoleFull
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+zing/32/consoleFull
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+zing/31/consoleFull

The fatal error is:

```
At least one slave process threw an exception, first: Forked process returned with error code: 1. Very likely a JVM crash.
```

I could not find any core dumps or `hs_err_pid` files on the Jenkins worker.

The failing builds run on Jenkins workers specified as follows:

```
CentOS 7.4.1708 - 4 CPU Cores / 31744 MB Memory
```

Some examples of recent successful builds of https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+zing/ are:

* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+zing/25/consoleFull
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+zing/21/consoleFull
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+zing/19/consoleFull

These all ran on Jenkins workers specified as follows:

```
Ubuntu 16.04 - 4 CPU Cores / 31903 MB Memory
```

There _have_ been some recent build failures of this Jenkins job on Ubuntu 16.04, but these are for individual test failures rather than JVM crashes.  (An example is https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+zing/28/consoleFull)

The last time this Jenkins job worked on CentOS 7.4 was on 26th January: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+zing/15/consoleFull

**Comment by jasontedor** [comment]
This is being tracked internally through the infra team and is not actionable via this repository at this time. As such, I am going to close this issue.
