### ISSUE TITLE
How to automatically expire elasticsearch6's index

### ISSUE THREAD

**Issue by zzlxf** [elastic/elasticsearch#28475]
in elasticsearch2, metadata is _ttl can be index automatically expire,but elasticsearch6 is delete the metadata,so, if want to automatically expire index,how do it?
PUT my_index  
{  
  "mappings": {  
    "my_type": {  
      "_ttl": {  
        "enabled": true,  
        "default": "5m"  
      }  
    }  
  }  
}

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
