### ISSUE TITLE
Not all Java9 builds support --illegal-access=warn

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#28473]
The conditional logic for enabling `--illegal-access=warn` assumes that all supported Java9 build VMs 
support that option, but at least some of our OpenJDK CI builds don't

Found via: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+openjdk-java9-periodic/47/

```
/usr/lib/jvm/java-9-openjdk-amd64/bin/java --illegal-access=warn
Unrecognized option: --illegal-access=warn
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

/usr/lib/jvm/java-9-openjdk-amd64/bin/java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```

Relates: #28437

**Comment by rjernst** [comment]
That build looks insanely old (2016?). I'm closing this as it looks like a CI infrastructure issue.
