### ISSUE TITLE
Incorrect doc value timestamp

### ISSUE THREAD

**Issue by jbudz** [elastic/elasticsearch#28484]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.1.3

**Plugins installed**: None

**JVM version** (`java -version`): 9.0.1+11

**OS version** (`uname -a` if on a Unix-like system): macOS

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

```
PUT foo
PUT foo/_mapping/doc
{
  "properties": {
    "timestamp": {
      "type": "date",
      "format": "YYYY-MM-DD'T'HH:mm:ss.SSSZ"
    }
  }
}

PUT foo/doc/1
{
  "timestamp": "2018-02-01T09:22:24.962-0700"
}

GET foo/_search
{
  "docvalue_fields": ["timestamp"]
}
```

```
{
  "took": 66,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 1,
    "hits": [
      {
        "_index": "foo",
        "_type": "doc",
        "_id": "1",
        "_score": 1,
        "_source": {
          "timestamp": "2018-02-01T09:22:24.962-0700"
        },
        "fields": {
          "timestamp": [
            "2018-01-01T16:22:24.962Z"
          ]
        }
      }
    ]
  }
}
```

**Comment by jbudz** [comment]
Noted at https://discuss.elastic.co/t/kibana-6-1-2-importing-month-of-february-as-january/118084

**Comment by jimczi** [comment]
Please ask question like this on discuss.elastic.co, we reserve github for verified bugs and feature request. Regarding the behavior, this is not a bug, `D` stands for day of the year and `d` for day of the month so your format is not correct. It should be `YYYY-MM-dd'T'HH:mm:ss.SSSZ` which yields the correct result.
