### ISSUE TITLE
Cannot set password for X-Pack we a Homebrew|MacOS install

### ISSUE THREAD

**Issue by gfelot** [elastic/elasticsearch#28493]
ES : 6.1.3 + X-Pack
Java 9.0.1
MacOS 10.13.3

I made a fresh install of ES and Kibana thanks to homebrew on MacOS.
I wanted to play with X-Pack and the differents modules but since v6 there is no the default user `elastic/changeme` credential.
Instead we have to launch `bin/x-pack/setup-passwords interactive|auto`.
But in the path `/usr/local/etc/elasticsearch/x-pack` or `/usr/local/Cellar/elasticsearch/6.1.3/bin` I don't have any bin `setup-password`. So I cannot choose the credential to login.

**Comment by martijnvg** [comment]
Hey @gfelot the `setup-password` script is located here: `/usr/local/Cellar/elasticsearch/6.1.3/libexec/bin/x-pack/setup-passwords`

It wasn't easy to find and I think the scripts added by xpack (and any other plugin) should be on the path like the other scripts (`elasticsearch`, `elasticsearch-keystore`, `elasticsearch-plugin`, `elasticsearch-translog`), but I don't how feasible that would be.

**Comment by rjernst** [comment]
What @martijnvg suggested here (moving x-pack bin scripts to elasticsearch bin dir) will actually be the case with 6.3.0 and the opening of x-pack. I'm going to close this issue as there is nothing else actionable here.

**Comment by mrdulin** [comment]
@martijnvg 

```bash
☁  ~  ls /usr/local/Cellar/elasticsearch/6.2.4/libexec/plugins/x-pack
meta-plugin-descriptor.properties x-pack-graph                      x-pack-monitoring                 x-pack-watcher
x-pack-core                       x-pack-logstash                   x-pack-security
x-pack-deprecation                x-pack-ml                         x-pack-upgrade
```

there is no `setup-passwords`

**Comment by tvernum** [comment]
@mrdulin The path your are listing is not the one that @martijnvg referenced.
Try
```
ls /usr/local/Cellar/elasticsearch/6.1.3/libexec/bin/x-pack/setup-passwords
```

**Comment by mrdulin** [comment]
@tvernum thanks. I found it.
