### ISSUE TITLE
New default - make search results fail rather than return partial results

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#28494]
7.0 represents an opportunity to make a break with our more lenient past where we would _always_ try return partial hits or aggregations in the event of failures.

When failures occur `hits` and `aggregations` are returned alongside the information that says how many shards failed or if the search timed out. The suspicion is that most client applications will pay little attention to these important failure flags and unwittingly present partial results to clients with no indication that the results are incomplete.

https://github.com/elastic/elasticsearch/issues/27435 introduced a new flag which defines a cluster-level policy with the option of a per-query override. Currently the cluster default is to stick with the lenient policy of returning partial results rather than a complete failure.

The proposal is that we change the cluster default setting to a strict policy which will return an error and no search results for the scenarios that can lead to partial results e.g. 
* A failure to execute within a timeout associated with the search *
* Missing shards (ie a red index)
* Failed shards - e.g. an error executing the query on index 2 of N because fielddata disabled

\* _Related issue: [should we set a default cluster setting for timeouts?](https://github.com/elastic/elasticsearch/issues/27187)_

**Comment by markharwood** [comment]
This is an important choice to make so we will write a blog post explaining the pros and cons and invite opinions to be expressed here.

WE WOULD LIKE TO GAUGE FEEDBACK BY COUNTING REACTIONS SO.....

* if you want to change to errors-by-default then THUMB UP this comment
* If you want to stick with partial results then THUMBS DOWN this comment.

<img width="241" alt="new_default_-_make_search_results_fail_rather_than_return_partial_results_ _issue__28494_ _elastic_elasticsearch" src="https://user-images.githubusercontent.com/170925/35737668-3a7db518-0824-11e8-9c1f-9b0d7038f86e.png">

**Comment by mattweber** [comment]
#27435 is tagged for 7x only, can we get this back ported to a 6x release so we can experiment?

**Comment by tvernum** [comment]
@mattweber It looks like #27435 is incorrectly tagged.
It was backported to 6.x in https://github.com/elastic/elasticsearch/commit/6165676b369d51c9e4498c895460c89d4df741c5

@markharwood Can you confirm and update the version tags for #27435 ?

**Comment by markharwood** [comment]
My bad. Labelled the PRs but forgot the issue. This flag will debut in 6.3

**Comment by markharwood** [comment]
Update - we are not proposing making this breaking change in 7.0
We'd like to gather more feedback first. We have a blog lined up designed to promote discussion and gather feedback more generally.

**Comment by MosheMalin** [comment]
Can it be controlled in 6.X somehow?
Alternatively, while viewing a dashboard, where can I find an indication that the results are partial?
It happens to me from time to time, and it may lead to false alarms.

**Comment by markharwood** [comment]
>Can it be controlled in 6.X somehow? 

Yes, [at cluster and query level.](https://gist.github.com/markharwood/f013e8aa8963d772356ecb7c513f82e5) since 6.3.

>while viewing a dashboard, where can I find an indication that the results are partial?

This is what I see (Kibana 6.6) when partial results are allowed and there's a partial failure:
<img width="188" alt="Kibana" src="https://user-images.githubusercontent.com/170925/54423274-3241e300-4708-11e9-8d3e-d7cd804312d6.png">
The partial results are shown but with a warning message.

This is what I see when partial results are disabled in cluster settings and there was an issue:
<img width="197" alt="Kibana" src="https://user-images.githubusercontent.com/170925/54423606-ee031280-4708-11e9-9e4f-f608493ef5a3.png">
Results are not re-drawn in Kibana (it keeps whatever data was visualised there before) but shows the failure from the unsuccessful search. This is probably not the place to further discuss Kibana behaviour.

**Comment by javanna** [comment]
We have no plans of making this change at this time. Closing.
