### ISSUE TITLE
all shards for all indices unassigned

### ISSUE THREAD

**Issue by ImCarrot** [elastic/elasticsearch#28509]
**Describe the feature**:

**Elasticsearch version** 5.6.2:

**Plugins installed**: None

**JVM version** 1.8:

**OS version** Amazon Linux:

I had a node that was shut down for a while (1 day). Now when I turn that node up and connect it to a master node and a client node, the cluster is formed but still all the shards of all indices remain unassigned. cluster health is `red` can this be an issue of the `segments.gen` file? if so, where can I find it? 

It's strange since, `_cluster/allocation/explain` returns:

    {
        "index": "pu_reviews_prod_db",
        "shard": 2,
        "primary": true,
        "current_state": "unassigned",
        "unassigned_info": {
            "reason": "CLUSTER_RECOVERED",
            "at": "2018-02-03T21:37:38.066Z",
            "last_allocation_status": "no_valid_shard_copy"
        },
        "can_allocate": "no_valid_shard_copy",
        "allocate_explanation": "cannot allocate because all found copies of the shard are either stale or corrupt",
        "node_allocation_decisions": [
            {
                "node_id": "WtN6PQV_SI6CQPe2xOdk6Q",
                "node_name": "ates-data-01",
                "transport_address": "99.0.xx.yy:9300",
                "node_decision": "no",
                "store": {
                    "in_sync": false,
                    "allocation_id": "MglwwWL0QHeRCuMFZVCDKQ"
                }
            }
        ]
    } 

and the old data node is exactly the way it was and the master nodes and client nodes are both v5.6.2 as before.

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
