### ISSUE TITLE
Location awareness in low level RestClient

### ISSUE THREAD

**Issue by edudar** [elastic/elasticsearch#28500]
Right now RestClient accepts a set of hosts it will rotate through doing client-side load balancing. When the server runs in AWS it's good practice to spread instances across multiple availability zones and to make requests within your availability zone preferably, falling back to out of zone requests when necessary. It would be good to have two sets of addresses RestClient rotates through. One is the primary set which can be filled with client/data nodes within your availability zone and the other one is secondary set where client/data nodes outside of your availability zone will reside. In this case, a client should rotate primary nodes (even if there's only one node) and fallback to secondary nodes when the primary is empty/blacklisted.

**Comment by javanna** [comment]
I believe this will be addressed by implementing a custom node selector once we have added support for them as part of #21888 .

**Comment by javanna** [comment]
Closing, will be implemented as part of #21888 like mentioned above.
