### ISSUE TITLE
Extract XContent from the elasticsearch server

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#28504]
One day we'd like the high level rest client not to depend on Elasticsearch's server code. As a first step we're going to extract Elasticsearch's xcontent classes into a jar without dependencies.

* [x] Replace xcontent's explicit dependencies on Log4J with something pluggable and have the Elasticsearch server plug Log4J into it (@dakrone)
* [x] Separate xcontent from Lucene (@dakrone)
* [x] Separate xcontent from other parts of Elasticsearch (like commons) (@dakrone)
* [x] Build the jar

**Comment by nik9000** [comment]
https://github.com/elastic/elasticsearch/pull/28449 and https://github.com/elastic/elasticsearch/pull/28488 started this process. It'll take a few more PRs to finish it.

**Comment by nik9000** [comment]
As is https://github.com/elastic/elasticsearch/pull/28503.

**Comment by dakrone** [comment]
Okay, the first step, decoupling anything related to Log4j and `LoggingDeprecationHandler`, has been finished.

**Comment by dakrone** [comment]
All the currently relevant parts of XContent have been moved into the new x-content artifact, so I'm going to consider this resolved for now.
