### ISSUE TITLE
Suggester suggestion term result.

### ISSUE THREAD

**Issue by arpitdadheech** [elastic/elasticsearch#28511]
Elasticsearch version 6.1
Plugins installed: None
JVM version 1.8
OS version windows

I have used "Suggester" suggester.
I have dumped data as:-
{ 
	"first_name": "Demo",
	"last_name": "Demo",
	"nike_name":  "Aero",
	"suggest" : ["Demo", "Demo", "Aero"]
}

put datas/data/1
{ 
	"first_name": "Alex",
	"last_name": "Alex Ambrose",
	"nike_name":  "Demo",
	"suggest" : ["Alex", "Alex Ambrose", "Demo"]
}

It give me output 

"suggest": {
      "suggest": [
        {
          "text": "A",
          "offset": 0,
          "length": 1,
          "options": [
            {
              "text": "Aero",
              "_index": "er_data",
              "_type": "data",
              "_id": "1",
              "_score": 1,
              "_source": {
                "suggest": [
                  "Demo", 
				  "Demo", 
				  "Aero"
                ]
              }
            },
            {
              "text": "Alex",
              "_index": "er_data",
              "_type": "data",
              "_id": "2",
              "_score": 1,
              "_source": {
                "suggest": [
                  "Alex",
                  "Alex Ambrose",
                  "Demo"
                ]
              }
            }
          ]
        }

Two result set are correct why it does not give me "Alex Ambrose" in the output "Text" field as it returns me "Alex" and "Aero"

My search query is 

"suggest": {
            'suggest': {
              'text':"A",
              'completion': {
                'field': 'suggest'
              }
            }
          }

Thanks in advance.
@dadoonet @colings86

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

You already asked this on discuss. Please keep the discussion there.

**Comment by jasontedor** [comment]
@arpitdadheech Please do not ping people directly.
