### ISSUE TITLE
Add an example of JLH usage in significant terms aggregation docs

### ISSUE THREAD

**Issue by gskema** [elastic/elasticsearch#28513]
https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-bucket-significantterms-aggregation.html#_parameters_5

Presumably one can select between `jlh`, `mutual_information`, `chi_square`, `gnd`, `percentage` or `script_heuristic`.

No usage example is provided for `jlh`, but it is mentioned later:

https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-bucket-significantterms-aggregation.html#_which_one_is_best

There should be an example for `jlh`, even if it has no params.

**Comment by mennoo1996** [comment]
If no one else has picked this up yet, I would like to fix this
