### ISSUE TITLE
Add code example of smoothing model parameter for phrase suggester

### ISSUE THREAD

**Issue by gskema** [elastic/elasticsearch#28512]
https://www.elastic.co/guide/en/elasticsearch/reference/master/search-suggesters-phrase.html#_smoothing_models

This does not show what parameter should be used to configure the smoothing model. I assume it is `"smoothing": ...`. This should be added in the documentation. A code example would be even better.

**Comment by jimczi** [comment]
cc @elastic/es-search-aggs
