### ISSUE TITLE
Gradlew Run Just Sitting at 97%

### ISSUE THREAD

**Issue by danlevy1** [elastic/elasticsearch#28527]
**Elasticsearch version** (`bin/elasticsearch --version`): Command not working in Terminal

**Plugins installed**: [none]

**JVM version**: 9.0.4

**OS version** : macOS 10.13.1

**Description of the problem including expected versus actual behavior**:

When I use the terminal to run `./gradlew run`, the progress bar stops at 97% every time. It says `97% executing` and just below it says `:distribution:run#start`. I have been letting it run for close to 30 minutes. When I run `./gradlew assemble`, I get a `build successful` message. I am using Eclipse to set up the project and running the above commands in Terminal.

**Comment by nik9000** [comment]
`.gradlew run` should just run Elasticsearch and leave it open. The build will indeed sit around 97% done because the only remaining tasks are all "clean up". So this is working as designed. You should be able to work with Elasticsearch on port 9200.
