### ISSUE TITLE
GET _aliases API report error on version 6.x with index filter in URL

### ISSUE THREAD

**Issue by sundag** [elastic/elasticsearch#28529]
Visit 
`GET <some_name>/_aliases`
will list the aliases filtered with <some_name> in previous versions (tried on elasticsearch 5.x )
But after upgraded to elasticsearch 6.1.3. The API returns:
```
{
  "error": "Incorrect HTTP method for uri [/*-<some_name>/_aliases] and method [GET], allowed: [PUT]",
  "status": 405
}
```
Is that a behavior change? Or regression between versions?

**Comment by ywelsch** [comment]
5.x used to support both `_alias` and `_aliases`. This was changed in 6.x to only support `_alias`, see also https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_rest_changes.html#_indices_information_apis
and https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html#alias-retrieving
