### ISSUE TITLE
GCP Discovery Plugin instructions using deprecated util

### ISSUE THREAD

**Issue by sherry-ger** [elastic/elasticsearch#28523]
**Elasticsearch version** (`bin/elasticsearch --version`):
Elasticsearch version: 6.1.3

**Plugins installed**: 
GCE Discovery Plugin 

**JVM version** (`java -version`):
1.8.0_151

**OS version** (`uname -a` if on a Unix-like system):
Ubuntu 16.04

**Description of the problem including expected versus actual behavior**:

The instructions for [Setting up GCE Discovery](https://www.elastic.co/guide/en/elasticsearch/plugins/current/discovery-gce-usage-long.html) are awesome.  However, in the [Clone your existing machine](https://www.elastic.co/guide/en/elasticsearch/plugins/current/discovery-gce-usage-cloning.html), the `gcimagebundle` util has been deprecated and is not available as a part of GCE images anymore.  Should the doc just link to [Exporting an image](https://cloud.google.com/compute/docs/images/export-image)?

**Comment by dadoonet** [comment]
Now that the blog has been released we should remove that part of the documentation.
And may be link to the blog post? https://www.elastic.co/blog/getting-started-gce-discovery-plugin-on-google-cloud

**Comment by kiawin** [comment]
I think the link may not be most ideal as it refers to older version of Java?

**Comment by ywelsch** [comment]
@sherry-ger would you be interested in updating the docs, based on what's in the blog post?

**Comment by sherry-ger** [comment]
Certainly @ywelsch

**Comment by ywelsch** [comment]
Thanks, that will be much appreciated

**Comment by sherry-ger** [comment]
I put in a [PR](https://github.com/elastic/elasticsearch/pull/40874) that is waiting for review.

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open as #40874 is still open.

**Comment by debadair** [comment]
Closing as #40874 was merged.
