### ISSUE TITLE
elasticsearch-core 6.2.0 is not available on maven central

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#28539]
When using the HL Rest Client, it pulls elasticsearch which [pulls elasticsearch-core](http://central.maven.org/maven2/org/elasticsearch/elasticsearch/6.2.0/elasticsearch-6.2.0.pom):

```xml
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-core</artifactId>
  <version>6.2.0</version>
  <scope>compile</scope>
</dependency>
```

The later is not available on maven central: http://central.maven.org/maven2/org/elasticsearch/

**Comment by floragunncom** [comment]
we are also affected
<pre>
Could not find artifact org.elasticsearch:elasticsearch-core:jar:6.2.0 in central (https://repo.maven.apache.org/maven2)
</pre>

**Comment by hub-cap** [comment]
Im on it. Sorry for any noise. Should be fixed soon.

**Comment by hub-cap** [comment]
It has been released and is propagating its bits thru the æther now. Hopefully it will be in central in not too much longer.

**Comment by Montesinnos** [comment]
It seems to be work fine. Earlier this morning, dependencies were breaking. Since @hub-cap last post, this works and my code builds:
```
compile 'org.elasticsearch:elasticsearch:6.2.0'
compile 'org.elasticsearch:elasticsearch-rest-high-level-client:6.2.0'

```
