### ISSUE TITLE
[X-PACK] [Monitoring] Improvement of "Disk Available" display

### ISSUE THREAD

**Issue by Cornoualis** [elastic/elasticsearch#28533]
**Feature request** 

**Describe the feature**: Improve the "Disk Available" value on the main "Monitoring" page, by only counting the free disk space on nodes that have _node.data=true_ in their config.

**Elasticsearch version**: Version: 5.6.2, Build: 57e20f3/2017-09-23T13:16:45.703Z, JVM: 1.8.0_131

**Plugins installed**: [x-pack]

**JVM version** : 1.8.0_131

**OS version** : RHEL7

**Description of the problem including expected versus actual behavior**:

The "Disk Available" value on the main "Monitoring" page displays the sum of free disk space on **all** the nodes in the cluster, even if those nodes don't have the node.data setting to 'true'. The resulting value could be misleading.

**Example:** This morning, I had a **red cluster state**, caused by shards that couldn't be allocated because of no disk space left...and at this moment, **the "Disk Available" value was 20%** (because I have several non data nodes included in that value).

**Comment by polyfractal** [comment]
Hi there @Cornoualis, thanks for the feature request.  Unfortunately, the issues in this repo are reserved for the open source Elasticsearch components, not X-Pack.  Would you mind moving your feature request to the [X-Pack forum](https://discuss.elastic.co/c/x-pack) instead?

Thanks!

**Comment by Cornoualis** [comment]
Hi @polyfractal ! Sure, I will! Have a nice day!
