### ISSUE TITLE
org.elasticsearch.plugin:x-pack-security:6.2.0 transitive dependency not found on Elasticsearch Maven Repository

### ISSUE THREAD

**Issue by pangyikhei** [elastic/elasticsearch#28551]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_161

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:

When trying to retrieve dependencies in my Gradle project that has a compile dependency on org.elasticsearch.client:x-pack-transport:6.2.0, I get:

Could not find org.elasticsearch.plugin:x-pack-security:6.2.0.
Searched in the following locations:
    https://jcenter.bintray.com/org/elasticsearch/plugin/x-pack-security/6.2.0/x-pack-security-6.2.0.pom
    https://jcenter.bintray.com/org/elasticsearch/plugin/x-pack-security/6.2.0/x-pack-security-6.2.0.jar
    https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/x-pack-security/6.2.0/x-pack-security-6.2.0.pom
    https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/x-pack-security/6.2.0/x-pack-security-6.2.0.jar
    https://artifacts.elastic.co/maven/org/elasticsearch/plugin/x-pack-security/6.2.0/x-pack-security-6.2.0.pom
    https://artifacts.elastic.co/maven/org/elasticsearch/plugin/x-pack-security/6.2.0/x-pack-security-6.2.0.jar
Required by:
    project :project > org.elasticsearch.client:x-pack-transport:6.2.0

If I set the dependency version to 6.1.3, I don't get the above error.

**Steps to reproduce**:

Gradle project with org.elasticsearch.client:x-pack-transport:6.2.0 dependency

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch only. Please use the [forum](https://discuss.elastic.co) for X-Pack.
