### ISSUE TITLE
jvm heap size continuous increase

### ISSUE THREAD

**Issue by junkainiu** [elastic/elasticsearch#28560]
**Elasticsearch version** (`bin/elasticsearch --version`):
5.3.0
**Plugins installed**: []
None
**JVM version** (`java -version`):
1.8.0_66
**OS version** (`uname -a` if on a Unix-like system):
centos 7
Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
**Description of the problem including expected versus actual behavior**:

We are running a one node elaticsearch cluster with 32GB heap size, 1458 indices . The heap size is continous increasing even if there are no any indexing and query, so what is increasing in the heap? Is it a bug or it's normal for jvm?
see the img below from x-pack for detail jvm and indexing info.  
**Steps to reproduce**:
![git1](https://user-images.githubusercontent.com/12933695/35959204-988a7e74-0cdf-11e8-9bb9-fadbf9ed4904.png)
![git2](https://user-images.githubusercontent.com/12933695/35959221-a8d7601c-0cdf-11e8-899b-dd2adb736ef9.png)
![git3](https://user-images.githubusercontent.com/12933695/35959231-b2c15c22-0cdf-11e8-803d-f2b8cc5a38f3.png)

**Provide logs (if relevant)**:

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
