### ISSUE TITLE
Add support for specifying multiple ids in the percolate query

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#28573]
Since 6.1, specifying multiple documents in a single percolate query was added. 

It makes sense to also support specifying multiple ids:

```
GET /my-index/_search
{
    "query" : {
        "percolate" : {
            "field" : "query",
            "index": "my-index",
            "ids" : ["1", "2", 3"]
        }
    }
}
```

and in case when fetching from multiple indices:

```
GET /my-index/_search
{
    "query" : {
        "percolate" : {
            "field" : "query",
            "ids" : [
               {
                  "index": "index1"
                  "id": "1"
               },
                {
                  "index": "index2"
                  "id": "2"
               }
            ]
        }
    }
}
```

Not sure about the "ids" name in the above example.

Behind the scene mget should be used to fetch these documents.

**Comment by jpountz** [comment]
Actually I'm not sure we should make it simpler. It makes it look like it is more efficient that getting on client-side and then passing multiple docs, while it isn't?

**Comment by jpountz** [comment]
cc @elastic/es-search-aggs

**Comment by jpountz** [comment]
Discussed in FixitFriday. We are actually thinking of removing APIs that need to fetch documents as part of query execution, such a change would go in the opposite direction. Additionally, this would be no more efficient than fetching documents on the client-side before percolating them as anynymous documents.

@martijnvg What do you think?

**Comment by martijnvg** [comment]
Then in that case I think it makes sense to not add support for fetching multiple documents.

> Additionally, this would be no more efficient than fetching documents on the client-side before percolating them as anynymous documents.

true

The main reason I was in favor of adding this, was that it is possible to specify either a  single or multiple documents in json/smile etc, but not when just specifying index/type/id and that felt incomplete to me.

**Comment by seanlaff** [comment]
@jpountz Even though elasticsearch would be doing nothing more special than the client would (fetch the docs by id, run them through the percolator), it's handy to avoid the roundtrip latency incurred when the client is responsible for fetching the documents and sending them back. 

I understand the desire to slim the api surface down (not to mention this may be an edge case), but I think it has some merit.

**Comment by nafooesi** [comment]
> Discussed in FixitFriday. We are actually thinking of removing APIs that need to fetch documents as part of query execution, such a change would go in the opposite direction. Additionally, this would be no more efficient than fetching documents on the client-side before percolating them as anynymous documents.
> 
Documentation suggest against percolating anonymous documents under heavy usage, because it creates in-memory index for those documents.  https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-percolate-query.html#how-it-works

If it's more efficient to percolate existing documents, it would make a good case to allow sending of  multiple ids to percolator index.
