### ISSUE TITLE
after installing x-pack into elastic search , local host as elasticsearch and kibana can not connect , error: elasticsearch in not connected ,  (plugin:elasticsearch@6.2.1 | Unable to connect to Elasticsearch at http://localhost:9200)

### ISSUE THREAD

**Issue by theragnarpatel** [elastic/elasticsearch#28593]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by theragnarpatel** [comment]
Ok, appreciate that, sorry about that and  thankyou
