### ISSUE TITLE
Should there be a global `max_concurrent_shard_requests` cluster setting?

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#28596]
Search requests have a query parameter called `max_concurrent_shard_requests` which limits the number of shards that will be searched concurrently. At the moment this can be set per request and if not set it defaults to `min(256, nodeCount * default(index.number_of_shards))`. `default(index.number_of_shards)` means the default value of the `index.number_of_shards` settings which itself defaults to 5.

I am wondering if it is a good idea to allow admins to change this default using a `search.default.max_concurrent_shard_requests` cluster setting so they can control this on across all requests knowing the behaviour of their cluster. We can make the default of this cluster setting the same as the current default for the query parameter.

I had initially considered this to be better as an index setting but then realised that if it is an index setting and a search is performed across multiple indices, the setting value might be different on each of the indices and then its ambiguous as to which value should be chosen so I think a cluster setting is appropriate here.

**Comment by colings86** [comment]
We discussed this and decided not to go ahead with it at this time as it doesn't help resource utilisation in the way I had thought.

**Comment by pavdmyt** [comment]
> decided not to go ahead with it at this time as it doesn't help resource utilisation in the way I had thought

@colings86 can you please provide more details? I'm also interested why 
`max_concurrent_shard_requests` can only be set on per-request basis, but not globally for entire cluster via e.g. `_cluster/settings`.

**Comment by alsyia** [comment]
I'm interested too!

**Comment by vanschelven** [comment]
By the way, the default value was changed to "just 5, no calculations" in version 7.0 (and the semantics were changed too)

> Semantics changed for max_concurrent_shard_requests
>
> max_concurrent_shard_requests used to limit the total number of concurrent shard requests a single high level search request can execute. In 7.0 this changed to be the max number of concurrent shard requests per node. The default is now 5.

**Comment by vanschelven** [comment]
Just to make the case for having this as a per-cluster setting explicit: if you have more than 5 shards per node on average (e.g. 50 primary shards, 5 nodes), the default setting implies that search is _never_ fully concurrent i.e. at least part of the search is run in serialized fashion. That problem grows linearly with the amount of shards per node.
