### ISSUE TITLE
Snapshot/Restore API should have an option to be targeted for specific node in cluster

### ISSUE THREAD

**Issue by erdarun** [elastic/elasticsearch#28591]
**Snapshot & Restore API should have an option to target specific node in elasticsearch cluster.**:

**Comment by tvernum** [comment]
Can you please explain this with a bit more detail? What would this targeted node do?
Are you simply attempting to avoid the need for networked storage?

To snapshot an index, you need to snapshot all shards for that index, and those shards may be spread across multiple data nodes. It's not possible to snapshot from a single node except in very simplistic circumstances where all shards are available on single node.

**Comment by erdarun** [comment]
Yes, To add more details

We have dependency with path.repo setup on all cluster nodes for backup location to be pointed for Snapshot/Restore.

If you can specify from Shapshot/Restore API which node can write to backup, then there is no need for backup mount point at all the nodes.

We hav use case where elasticsearch cluster nodes are distributed across DC. Here we can't have common mount point across DC as per the policy, so we got struck due to constraint of common shared location to be available on all nodes.

**Comment by erdarun** [comment]
@tvernum Feedback updated

**Comment by erdarun** [comment]
@tvernum Any updates will be helpful

**Comment by imotov** [comment]
@erdarun how is this different from #6638?

**Comment by javanna** [comment]
This seems to be the same that would be addressed by #6638 mentioned above. I am closing this issue, feel free to reopen if I missed anything.
