### ISSUE TITLE
SocketAccess using AccessController with permissions

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#28594]
Java 8 defines a new [`AccessController#doPrivileged`](https://docs.oracle.com/javase/8/docs/api/java/security/AccessController.html#doPrivileged-java.security.PrivilegedExceptionAction-java.security.AccessControlContext-java.security.Permission...-) method that allows to specify a limited set of permissions, instead of granting all.

We have several `SocketAccess` classes scattered around plugins, e.g.,
https://github.com/elastic/elasticsearch/blob/da1a10fa9266770769881b222ee99e7bdd6af4c2/plugins/discovery-ec2/src/main/java/org/elasticsearch/discovery/ec2/SocketAccess.java#L48

I think it would be beneficial to collate all `SocketAccess` classes under a single `org.elasticsearch.common` one and use the new `doPriviledge` with permissions facility.

**Comment by dadoonet** [comment]
I agree. That'd be nice also to allow OSS plugin developers to have access as well to this method.

**Comment by sarajmunjal** [comment]
I'd like to work on this issue if nobody else is working on it.

**Comment by svshenoy** [comment]
I am a beginner to elastic search interested in contributing, is there a guide for new developers to help get started ?

**Comment by albertzaharovits** [comment]
@svshenoy  See [contribuiting](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md) file in the code base.
@sarajmunjal no one is working on it (I have self assigned it, yet I haven't started to work on it).

We gladly accept contributions!

**Comment by sarajmunjal** [comment]
@albertzaharovits Cool, I'm going to assign it to myself. I already did some part of the implementation. 
I have a question: methods in the [repository-azure SocketAccess impl](https://github.com/elastic/elasticsearch/blob/master/plugins/repository-azure/src/main/java/org/elasticsearch/repositories/azure/SocketAccess.java) currently throw `StorageException`, which is part of the Azure package.

Moving these methods to the common repository with the `throws StorageException` syntax isn't a good idea, as the `commons` module would need the Azure dependency.

I am thinking that I should move everything else to the common SocketAccess class, and keep a separate one in the repository-azure package which uses composition on top of the common class. What do you think?

**Comment by sarajmunjal** [comment]
@dadoonet Do you think the above approach is a good idea?

**Comment by albertzaharovits** [comment]
@sarajmunjal It is better to open a PR to discuss code.
Opening a PR will open the subject to a broader audience. A single opinion is not enough to get it merge anyway.

**Comment by jasontedor** [comment]
Per the discussion in #28874 I am closing this issue.
