### ISSUE TITLE
Build fails with "Could not dispatch a message to the daemon."

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#28601]
Example build failures:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=sles/2027/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu/2027/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+bwc-tests/592/console

At first glance it seems like an issue with runbld as the end of the build output shows gradle reporting build success but runbld claiming that the wrapped process (i.e. gradle) exited with an error code:
```
07:17:50 BUILD SUCCESSFUL in 1h 16m 44s
07:17:50 2566 actionable tasks: 2486 executed, 80 up-to-date
07:17:50 Stopped 1 worker daemon(s).
07:17:50 VCS Checkout Cache (/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-unix-compatibility/os/sles/.gradle/vcsWorkingDirs) has not been cleaned up in 0 days
07:17:54 runbld>>> <<<<<<<<<<<< SCRIPT EXECUTION END <<<<<<<<<<<<
07:17:54 runbld>>> DURATION: 5453640ms
07:17:54 runbld>>> STDOUT: 5054108 bytes
07:17:54 runbld>>> STDERR: 50026 bytes
07:17:54 runbld>>> WRAPPED PROCESS: FAILURE (1)
07:17:54 runbld>>> Searching for build metadata in /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-unix-compatibility/os/sles
07:17:57 runbld>>> Storing build metadata: bwc_refspec_distribution:bwc-snapshot-6.x=c0561382a1fbe472df00f0e53098efcb19ccd380
07:17:57 WARNING: An illegal reflective access operation has occurred
07:17:57 WARNING: Illegal reflective access by clojure.lang.Reflector (file:/usr/local/src/runbld-1.5.9/runbld) to method com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(org.xml.sax.InputSource,org.xml.sax.helpers.DefaultHandler)
07:17:57 WARNING: Please consider reporting this to the maintainers of clojure.lang.Reflector
07:17:57 WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
07:17:57 WARNING: All illegal access operations will be denied in a future release
07:18:15 runbld>>> FAILURES: 0
07:18:16 runbld>>> BUILD: https://5086a1f436ee16623a447bdf25881bbc.us-east-1.aws.found.io:9243/build-1498188341992/t/20180209054652-D3C6ABEF
07:21:54 runbld>>> MAILING: build-elasticsearch@e***.co
07:21:55 runbld>>> Mail sent.  Output: {:code 0, :error :SUCCESS, :message "messages sent"}
07:21:55 
07:24:49 runbld>>> NOTIFYING SLACK
07:24:54 Build step 'Execute shell' marked build as failure
07:24:54 Archiving artifacts
07:24:55 Sending e-mails to: infra-root+build@elastic.co
07:24:57 Recording test results
07:25:06 Finished: FAILURE
```

However if you search for `FAILURE` in the logs something like the following shows up:
```
07:17:49 :qa:wildfly:integTestCluster#configure (Thread[Task worker for ':' Thread 3,5,main]) completed. Took 0.0 secs.
07:17:49 :qa:wildfly:integTestCluster#start (Thread[Task worker for ':' Thread 3,5,main]) started.
07:17:49 
07:17:49 :qa:wildfly:integTestCluster#start
07:17:49 FAILURE: Build failed with an exception.
07:17:49 
07:17:49 * What went wrong:
07:17:49 Could not dispatch a message to the daemon.
07:17:49 
07:17:49 * Try:
07:17:49 Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
07:17:49 
07:17:49 * Get more help at https://help.gradle.org
07:17:49 Task ':qa:wildfly:integTestCluster#start' is not up-to-date because:
07:17:49   Task has not declared any outputs.
```

This failure seems to relate to the gradle daemon which according to the `gradle.properties` file in the root of the repo should not be used with our builds. Its also curious that this failure does not stop the build but rather it continues without any apparent further error.

in the above build failure examples the two master builds (2027os=ubuntu and 2027os=sles) the failure seems to happen during the `:qa:wildfly:integTestCluster` tasks but in the 6.x bwc build it seems to happen in `:qa:verify-version-constants:v6.1.2#oldClusterTestCluster` tasks but these two gradle modules do not seem to share any groovy code so I am not sure what the common link between them could be.

I did see in https://docs.gradle.org/current/userguide/gradle_daemon.html#sec:what_can_go_wrong_with_daemon that you can add `--no-daemon` to the command line to prevent the daemon form being used but I'm not sure if that is in fact something we should do, since the `gradle.properties` file should be stopping the daemon from being used anyway.

/cc @jasontedor @rjernst

**Comment by colings86** [comment]
So from reading more it seems that the gradle daemon is run regardless of the settings but is started and shut down for the build if you disable it so it only survives for that single build.

@danielmitterdorfer and I concentrated just on https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+bwc-tests/592/console and found output indicating where the daemon log file is located:
```
03:30:51 The client will now receive all logging from the daemon (pid: 1151). The daemon log file: /var/lib/jenkins/.gradle/daemon/4.5/daemon-1151.out.log
```

Looking at that file on the CI worker it looks like the daemon shuts down after the `:qa:verify-version-constants:v6.2.2-SNAPSHOT#bwcTest` task because it believes the build is completed when actually only the inner gradle build is completed and the main gradle build is still running:
```
Skipping task ':qa:verify-version-constants:v6.2.2-SNAPSHOT#oldClusterTest' as it has no actions.
:qa:verify-version-constants:v6.2.2-SNAPSHOT#oldClusterTest (Thread[Task worker for ':',5,main]) completed. Took 0.0 secs.
:qa:verify-version-constants:v6.2.2-SNAPSHOT#bwcTest (Thread[Task worker for ':',5,main]) started.
:qa:verify-version-constants:v6.2.2-SNAPSHOT#bwcTest
Skipping task ':qa:verify-version-constants:v6.2.2-SNAPSHOT#bwcTest' as it has no actions.
:qa:verify-version-constants:v6.2.2-SNAPSHOT#bwcTest (Thread[Task worker for ':',5,main]) completed. Took 0.0 secs.
:qa:verify-version-constants:bwcTest (Thread[Task worker for ':',5,main]) started.
:qa:verify-version-constants:bwcTest
Skipping task ':qa:verify-version-constants:bwcTest' as it has no actions.
:qa:verify-version-constants:bwcTest (Thread[Task worker for ':',5,main]) completed. Took 0.0 secs.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 3h 39m 42s
3054 actionable tasks: 2672 executed, 382 up-to-date
Stopped 1 worker daemon(s).
VCS Checkout Cache (/var/lib/jenkins/workspace/elastic+elasticsearch+6.x+bwc-tests/.gradle/vcsWorkingDirs) has not been cleaned up in 0 days
07:10:32.295 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has finished executing the build.
07:10:32.298 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] daemon stop has been requested. Sleeping until state changes.
07:10:32.298 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] Command execution: finished waiting for DaemonCommandExecution[command = Build{id=cbe5c808-c805-4cb3-972f-9777f1bacc6e.1, currentDir=/var/lib/jenkins/workspace/elastic+elasticsearch+6.x+bwc-tests}, connection = DefaultDaemonConnection: socket connection from /0:0:0:0:0:0:0:1:39608 to /0:0:0:0:0:0:0:1:58944]. Result org.gradle.launcher.daemon.server.DaemonStateCoordinator@76bc6ad8 with state StopRequested
...
...
...
...
07:11:27.819 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 16722612224, Free: 12247891968}
07:11:27.819 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 1431830528, Committed: 920649728}
07:11:32.303 [DEBUG] [org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] Received finished message: null
07:11:32.303 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 14: stopping connection
07:11:32.303 [DEBUG] [org.gradle.internal.remote.internal.inet.SocketConnection] Discarding EOFException: java.io.EOFException
07:11:32.303 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 15: received null
07:11:32.303 [DEBUG] [org.gradle.launcher.daemon.server.DefaultDaemonConnection] thread 15: Received end-of-input from client.
07:11:32.304 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 14: stopping connection
07:11:32.343 [DEBUG] [org.gradle.cache.internal.LockOnDemandCrossProcessCacheAccess] Releasing file lock for file hash cache (/var/lib/jenkins/.gradle/caches/4.5/fileHashes)
07:11:32.345 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache fileHashes.bin (/var/lib/jenkins/.gradle/caches/4.5/fileHashes/fileHashes.bin)
07:11:32.345 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache resourceHashesCache.bin (/var/lib/jenkins/.gradle/caches/4.5/fileHashes/resourceHashesCache.bin)
07:11:32.345 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on file hash cache (/var/lib/jenkins/.gradle/caches/4.5/fileHashes).
07:11:32.345 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on cache directory workerMain (/var/lib/jenkins/.gradle/caches/4.5/workerMain).
Daemon vm is shutting down... The daemon has exited normally or was terminated in response to a user interrupt.
07:11:32.351 [DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Removing daemon address: [5e448acc-1014-4927-bf01-d61488a8d021 port:39608, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]]
07:11:32.351 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
07:11:32.351 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
07:11:32.352 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
```

(I have the full daemon log locally if needed)

Whats weird here is that I would have thought that either an inner build finishing would always cause a  shut down of the gradle daemon or never, its strange that most of the time this seems to work as we intend but only occassionally does the daemon wrongly get shut down.

I am a bit lost as to where to go next with this so any advice is very welcome.

**Comment by colings86** [comment]
Another instance of this: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=amazon/2027/console

**Comment by nik9000** [comment]
I get this locally when I run builds in parallel and there is an error.

**Comment by danielmitterdorfer** [comment]
I gathered a bit more information about these failures. They started on August 3, 2017 with `build.last-success.commit-id` 8ef7438d6c874586a97d29687facf162390d7923. We have disabled the Gradle daemon in 2f95e4a86c41b5da4e2c1a20cf337498f9496a01 on November 25, 2017 so we already ran for a while in this configuration before the failures have occurred.

We have 63 build failures until today. I have attached the [build ids of the failed builds](https://github.com/elastic/elasticsearch/files/1719620/failed-builds.csv.zip) for reference.

Looking at the build stats, the only commonality that we see is that the builds have only failed on Linux (that may or may not be a coincidence). Distro, uptime, JDK version or Gradle version do not seem to make a difference.

I also checked with our infrastructure team: We are not allowing concurrent builds in CI so I think we can also rule out concurrent builds as a cause.

**Comment by jasontedor** [comment]
We have not seen this occur in awhile. We can reopen this if it occurs again. Closing.

**Comment by hub-cap** [comment]
I saw this happen today. It does not seem to be related or triggered in the same place, at all.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+intake/150/

Im not sure its yet worth opening the issue up, or if this is pure coincidence. If more trickle in, I will reopen.

**Comment by droberts195** [comment]
Another occurrence: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=sles-12/203/console
