### ISSUE TITLE
[Settings] Allow Deletion of unknown settings

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#28609]
When upgrading a cluster with a `/_cluster/settings` that disappears (or is changed and not properly registered by a plugin), then it becomes impossible to _unset_ a persistent setting. Worse still, it then becomes a problem to apply new settings because it tries to merge the old settings.

```http
PUT /_cluster/settings
{
  "persistent": {
    "unknown.setting": null
  }
}
```

should be allowed  to run even though the setting is unrecognized.

**Comment by mayya-sharipova** [comment]
We have an alternative issue #28026 that says: "we should not archive unknown and broken cluster settings. Instead, we should fail to recover the cluster state. The solution for users in an upgrade case would be to rollback to the previous version, address the settings that would be unknown or broken in the next major version, and then proceed with the upgrade."

Implementing #28026  makes this issue unnecessary, as the broken settings should NOT exist anymore in the cluster state.

But the valid question is what to do with clusters that can't downgrade and have broken settings stuck in the cluster state.

**Comment by gwbrown** [comment]
I believe this issue has been addressed by https://github.com/elastic/elasticsearch/pull/28888, and so I'm going to close it. If you believe I am incorrect about that, please comment and/or reopen this issue.
