### ISSUE TITLE
Support float weights for Completion Suggester

### ISSUE THREAD

**Issue by adamhadani** [elastic/elasticsearch#28612]
Any reason not to? (I understand the default scoring for autocomplete is integer and roughly corresponds to character-level overlap between prefix query and entry)

This will be useful so can then index some arbitrary float `weight` into both a field and into the completion suggester, and then use that weight for tweaking default relevancy using `function_score` as well as using the `weight` support in completion suggester. Such weights more often than not come in as floats so seems like a useful feature.

**Comment by s1monw** [comment]
the underlying technology (lucene) use FSTs to represent the suggesters. I really struggle to remember the full picuture there but the output of an FST must be a semi-ring which is the reason why positive integers are used as it's basic structure. We can't encode floats here efficiently and the math becomes tricky as well on the encoding end. I am afraid this is not an option
