### ISSUE TITLE
RestHighLevelClient endpoint construction does not URL-encode ids

### ISSUE THREAD

**Issue by chrbau** [elastic/elasticsearch#28625]
elasticsearch-rest-high-level-client Version: 6.2.1

org.elasticsearch.client.Request#endpoint (line 461) does not URL-encode document ids - this leads to an invalid request if document id contains special characters like "#" (e.g. via index(IndexRequest indexRequest))

**Comment by javanna** [comment]
That's right, the client leaves ids untouched. Much better than modifying them and leaving users wondering why they can't retrieve those docs back by id. Users can encode their invalid ids as they wish though.

**Comment by chrbau** [comment]
Elasticsearch supports characters which need URL-encoding like "#" in ids - so to my knowledge those ids are perfectly valid ES-ids - right? Thus I need the work-around to build IndexRequests like this:

new IndexRequest(index, type, urlEncode(id))

and retrieve/delete/update like this:

new GetRequest(index, type, urlEncode(id))
new DeleteRequest(index, type, urlEncode(id))
new UpdateRequest(index, type, urlEncode(id))

right? In the database they are then stored as unencoded ids.

From my point of view URL-encoding belongs to the final http-request building and not to RestHighLevelClient-Request building? RestHighLevelClient shouldn't worry about how data is sent and that they might need URL-encoding? They could be consistently encoded in the Request#endPoint method which all request builders use.

**Comment by javanna** [comment]
@chrbau thanks for the additional info, I think you are right :) my initial response was incorrect, encoding ids doesn't modify the way their representation in Elasticsearch.

**Comment by hjxhjh** [comment]
should this considered as a bug？
