### ISSUE TITLE
There is no option to generate word parts on multiple languages in word_delimiter_graph

### ISSUE THREAD

**Issue by ahmadazimi** [elastic/elasticsearch#28624]
Hi there,
Imagine you have texts which they combined by two or more languages characters,
For example: 
`خیابانHashemi`
There is no way to  generate word parts on these texts via word_delimiter_graph filter.

**Comment by jimczi** [comment]
I thought that the `standard` tokenizer would split this input but it doesn't. We don't have any rules regarding arabic characters as it seems that it's not part of the standard unicode segmentation rules that the tokenizer uses (it can split on some eastern language):
http://www.unicode.org/reports/tr29/
You could use the `type_table` option of the `word_delimiter_graph` but that would mean mapping all possible arabic characters.
I don't have a good solution for this so the best would be to ask on the Lucene mailing list or to open an issue in Lucene's jira directly. The `word_delimiter_graph` (as the `standard` tokenizer) is defined in Lucene so it's better to ask there.

**Comment by ahmadazimi** [comment]
@jimczi Thank you for detailed answer.
