### ISSUE TITLE
Merging document _source from 2 indices to a 3rd index

### ISSUE THREAD

**Issue by ehtishamkhan** [elastic/elasticsearch#28621]
I have a couple of indices with the following document structure. 

Index 1
	"_source": {
		"guid": "abc123",
		"documentdescription": "document description",
	}

Index 2
	"_source": {
		"guid": "abc123",
		"documenttitle": "document title",
	}

I want to create a 3rd index by with _source with merged attributes on guid. 

Index 3
	"_source": {
		"guid": "abc123",
		"documentdescription": "document description",
		"documenttitle": "document title",
	}

I have explored logstash ingestion to create a new index (Index 3) however was not able to figure out a technique to accomplish this. Trying to avoid writing a full blown client program to loop over all documents in both indices :)

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
