### ISSUE TITLE
[V6.0.1 ]High IO when use replica

### ISSUE THREAD

**Issue by andrewliuxxx** [elastic/elasticsearch#28630]
Elasticsearch version (bin/elasticsearch --version): 6.0.1
Plugins installed: []
JVM version (java -version): 1.8.0_151
OS version (uname -a if on a Unix-like system): 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

Description of the problem including expected versus actual behavior:
Hi：
I have a ES 6.0.1 cluster with 64 machine and 256 nodes .with about 200000 records will be indexed to ES index every second. And Some problems occur.
if the index has 256 shards ,0 replicas , get a normal IO util(less than 10)
if the index has 64 shards ,0 replicas , get a normal IO util(less than 10)
if the index has 32 shards ,1 replicas , get a normal IO util(less than 10)
if the index has 16 shards ,3 replicas , get a normal IO util(less than 10)
**if the index has 64 shards ,1 replicas , get an abnormal IO util(more than 50)
if the index has 128 shards ,1 replicas , get an abnormal IO util(more than 50)
if the index has 32 shards ,3 replicas , get an abnormal IO util(more than 50)**

Steps to reproduce:
     1.  make a cluster with 1 machine and 4 nodes,
     2.  create a index with 2 shards,1 replica
     3.  with 1000 records being indexed to ES index every second. and we can find the annormal countinious high IO
   

Provide logs (if relevant):
no

**Comment by jasontedor** [comment]
To me this does not look like a bug but rather a consequence of having so many instances co-located on a single machine. Are you using spinning disks, that would be a contributing factor. Also, you haven't specified what you mean by "abnormal" IO utilization (nor how you're measuring it).

Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

I would ask you to provide the above information in any topic that you open there.
