### ISSUE TITLE
Impossible to use sort unmapped_type on multiple indices

### ISSUE THREAD

**Issue by TheFireCookie** [elastic/elasticsearch#28638]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.0

**Plugins installed**: [analysis-icu, discovery-file]

**JVM version** (`java -version`):  1.8.0_162 64 bits

**OS version** (`uname -a` if on a Unix-like system): Windows 10 Pro 64 bits

**Description of the problem including expected versus actual behavior**:
I'm indexing 2 differents types of documents in different indexes. Then I try to sort on a field that is only on 1 of the document mapping. And I encounter this error:
`        "failures": [
            {
                "shard": 0,
                "index": "bug2",
                "node": "GIZlXNt8RHCw8c8m6KyAWg",
                "reason": {
                    "type": "illegal_argument_exception",
                    "reason": "Fielddata is disabled on text fields by default. Set fielddata=true on [__anonymous_text] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead."
                }
            }
        ]`

**Steps to reproduce**:

PUT /bug1
{
    "mappings": {
        "doc1": {
            "properties": {
            	"name": { "type": "keyword"},
                "color": { "type": "text", "fielddata": true }
            }
        }
        
    }
}

PUT /bug2
{
    "mappings": {
        "doc2": {
            "properties": {
            	"name": { "type": "keyword"}
            }
        }
        
    }
}

PUT /bug1/doc1/1
{
	"name": "John Doe",
	"color": "red"
}

PUT /bug2/doc2/1
{
   "name": "Hello World"
}

POST /bug1,bug2/doc1,doc2/_search
{
   "sort":[
      {
         "color":{
            "missing":"_first",
            "order":"asc",
            "unmapped_type":"text"
         }
      }
   ]
}

**Comment by jpountz** [comment]
`text` is not suitable for sorting in general, you should pass `unmapped_type: keyword`.
