### ISSUE TITLE
Release tests fail because bwc artifacts are not generated

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#28653]
The release tests are failing on CI with the following error (this specific output was taken from https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/471/console but there are other build runs failing too on master and 6.x) :

```
00:51:09 FAILURE: Build failed with an exception.
00:51:09 
00:51:09 
00:51:09 * Where:
00:51:09 Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
00:51:09 Build file '/var/lib/jenkins/workspace/elastic+elasticsearch+master+release-tests/distribution/bwc/build.gradle' line: 159
00:51:09 See https://docs.gradle.org/4.5/userguide/command_line_interface.html#sec:command_line_warnings
00:51:09 
00:51:09 2244 actionable tasks: 2193 executed, 51 up-to-date
00:51:09 * What went wrong:
00:51:09 Execution failed for task ':distribution:bwc:next-bugfix-snapshot:buildBwcVersion'.
00:51:09 > Building bwc version didn't generate expected files [/var/lib/jenkins/workspace/elastic+elasticsearch+master+release-tests/distribution/bwc/next-bugfix-snapshot/build/bwc/checkout-6.2/distribution/deb/build/distributions/elasticsearch-6.2.2-SNAPSHOT.deb, /var/lib/jenkins/workspace/elastic+elasticsearch+master+release-tests/distribution/bwc/next-bugfix-snapshot/build/bwc/checkout-6.2/distribution/rpm/build/distributions/elasticsearch-6.2.2-SNAPSHOT.rpm, /var/lib/jenkins/workspace/elastic+elasticsearch+master+release-tests/distribution/bwc/next-bugfix-snapshot/build/bwc/checkout-6.2/distribution/zip/build/distributions/elasticsearch-6.2.2-SNAPSHOT.zip]
```

@hub-cap could these failures be related to your bwc changes in the build last week?

**Comment by DaveCTurner** [comment]
I suspect #28641, since it looks like it reverts the effects of #27778.

**Comment by hub-cap** [comment]
yea that was apparently only a partial fix. These should be testing against those snapshot versions, but bwc was changed to "pretend" those were releases, so it looks like i just missed a spot to unpretend. As you can see from the rpm etc generation, its not appending -SNAPSHOT to these artifacts, as it should be. So another fix on top of #28641 will be incoming to further fix this bug that it uncovered :)

**Comment by hub-cap** [comment]
Its due to the build.snapshot being propagated into the snapshot build of the checkout. I need to chat w @rjernst to see if this is valid. I suspect it should not be passing this down since they are not releases.

```
00:49:56 Starting process 'command 'XXXX/next-bugfix-snapshot/build/bwc/checkout-6.2/gradlew''. Working directory: XXXX/next-bugfix-snapshot/build/bwc/checkout-6.2 Command: XXXX/next-bugfix-snapshot/build/bwc/checkout-6.2/gradlew :distribution:deb:assemble :distribution:rpm:assemble :distribution:zip:assemble -Dbuild.snapshot=false --info

**Comment by jasontedor** [comment]
@hub-cap The mechanism for passing the `build.snapshot` value down to the BWC builds is here: https://github.com/elastic/elasticsearch/blob/d994bbecb92a53732f0c1f7e393a1ee9da91d915/distribution/bwc/build.gradle#L142

**Comment by hub-cap** [comment]
https://github.com/elastic/elasticsearch/blob/798066a96dde8e69ac6bdeb83ec18b0af5d67e04/distribution/bwc/build.gradle#L141

ya and it used to be hardcoded to true @jasontedor

**Comment by hub-cap** [comment]
Ill keep an eye on this and reopen if it continues to fail. itll be a while tho
