### ISSUE TITLE
Expose matchNoneQuery through QueryBuilders

### ISSUE THREAD

**Issue by m9aertner** [elastic/elasticsearch#28679]
I suggest to add method "QueryBuilders::matchNoneQuery()".

During implementation of some (query) code generator that uses the QueryBuilders API I found it odd and somewhat _incomplete_ that there _is_ a method "QueryBuilders::matchAllQuery()", but not the counterpart "QueryBuilders::matchNoneQuery()".

Note: the implementation of underlying "MatchNoneQueryBuilder" is already present and would remain unchanged, as do related unit test or documentation.

Just the additional QueryBuilders method would need to be added to unit test and documentation (not sure where, sorry; `docs/reference/query-dsl/match-all-query.asciidoc` already lists match_none).

**Elasticsearch version** (`bin/elasticsearch --version`): v6.2.0

Clearly, this change is mostly **cosmetic**. It's trivial to just say `new MatchNoneQueryBuilder()`, but that's a different _style_, which I find interferes with surrounding other code that just asks QueryBuilders.

**Comment by cexmmaqsood** [comment]
Out of curiosity, what would be the use case of a `match_none` query?

**Comment by m9aertner** [comment]
We have multi-tenant data in our index with conditions regarding the visibility (i.e. user, maintenance, admin, on-behalf-of and so on). Structured ES queries are _generated_ on the fly based on user input and implicit roles/identity/permissions. In some cases deep down when certain sub-queries are found to not apply, a "match_none" is added to make sure that no preceding partial conditions still permit access.

Come to think of if, it's certainly better to bubble up that bit of information and just drop the whole sub-condition from the query. Thanks for the 2nd thought! I should have asked that "why?" question myself...

**Comment by jasontedor** [comment]
Please take a look @elastic/es-search-aggs.

**Comment by cbuescher** [comment]
@m9aertner thanks for opening this issue and the related PR (#28679) I already responded there.

**Comment by colings86** [comment]
I'm not a fan of exposing this query. The only reason this query exists is so we have something that the rewrite phase can replace the query with that means no documents should match to speed up execution. In clients I think its better to have logic which excluded the clause instead of adding a `match_none` query.

That said the MatchNoneQueryBuilder is public at the moment so I think we need to decide if we want it to be publicly exposed, if so we should add it to the QueryBuilders class for completeness and if not we should see if we can reduce the visibility of MatchNoneQueryBuilder so it is only visible internally (for the rewrite phase to use).

**Comment by cbuescher** [comment]
To argue for keeping it, there have been asks for this kind of query in the past (e.g. https://github.com/elastic/elasticsearch/issues/13406). There is always a workaround on the client side to construct a query that matches no docs (like e.g. an empty ids query), but "match_none" communicates more clearly what it does, and in my opinion there is no downside to having it as a logical complement to "macht_all".

**Comment by m9aertner** [comment]
After reviewing my use case I removed all uses of MatchNoneQueryBuilder and changed the client application code so that no query gets executed at all in these cases @cexmmaqsood @colings86 .

Thanks @cbuescher for mentioning #13406. I was in a somewhat similar situation but in my case it was really no problem to change the client code accordingly.

**Comment by m9aertner** [comment]
Now, does it _make sense_ to expose this specific function on top level?

Having read these other linked considerations, I don't think it's a great idea any longer. By using the existing class "MatchNoneQueryBuilder" directly it is still **possible** to get to the underlying function, but I agree it's not a query language element that will be used regularly.

No _need_ to expose it. Thanks for your consideration and input above, but let me close this request.
