### ISSUE TITLE
Highlighting documentation needs details on the highlighting process

### ISSUE THREAD

**Issue by cexmmaqsood** [elastic/elasticsearch#28681]
The highlighting documentation needs details in how elasticsearch breaks up the text, analyzes it, attempts to highlight it, and how it breaks up the text into fragments. 

Currently from what I understand after testing/reading, is that Elasticsearch will take the query, apply the same analyzer on it as the highlighted field, and then attempt to highlight those analyzed pieces. What I'm unsure about is how fragments get generated (how does Elasticsearch determine the positions inside a large text block to break up into fragments, is it a few characters before/after the highlight?).

It would be very helpful if there were details on the entire process like there is in other documention in Elasticsearch (which is very rich and heplful).

**Comment by jasontedor** [comment]
Please take a look @elastic/es-search-aggs.

**Comment by colings86** [comment]
@cexmmaqsood agreed that it would be nice to add some more information on how each of the highlighters produce fragments.

@jimczi or @mayya-sharipova would you be able to add this information?

**Comment by mayya-sharipova** [comment]
@colings86 I can work on this ticket

**Comment by aguyinmontreal** [comment]
@colings86 @mayya-sharipova @elastic/es-search-aggs 

Could you guys please also take a look at https://github.com/elastic/elasticsearch/issues/28816 ? Thanks

**Comment by jasontedor** [comment]
@aguyinmontreal We appreciate your enthusiasm but please do not ping individuals nor our internal team handles (which end up pinging many people).
