### ISSUE TITLE
How to get random document, at least 5 from each category

### ISSUE THREAD

**Issue by JACK-ARRAY** [elastic/elasticsearch#28693]
I have 1000 documents with 5 categories. Each category has around 200 documents. I want to pull 30 random documents with at-least 5 from each category. Please suggest me any solution.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
