### ISSUE TITLE
Elasticsearch not starting

### ISSUE THREAD

**Issue by modesolaa** [elastic/elasticsearch#28706]
This is similar to: #25789

How do you make the JAVA_HOME the system variable. I already set my JAVA_HOME in environmental variables as: C:\Program Files\Java\jdk1.8.0_152.

Any help will be appreciated

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by jasontedor** [comment]
You can link to a topic that you open on the forum from here, but please use the forum for general help.

**Comment by modesolaa** [comment]
Isn't this suppose be a public forum? Why then close it?

**Comment by jasontedor** [comment]
Each organization is free to work with their community differently. Our preference is to handle bugs and feature requests here, and provide general help via our [forum](https://discuss.elastic.co). We are more than happy to help you on the [forum](https://discuss.elastic.co).

**Comment by modesolaa** [comment]
I have a similar issue to what was described in one of the closed tickets. It was said in the ticket that using JAVA_HOME as the system variable resolved the problem.
My issue is inability to start elasticsearch service on a Windows machine. While I have my JAVA_HOME set in the environmental variable, I do not know the system variable
