### ISSUE TITLE
Could not find or load main class org.elasticsearch.tools.launchers.JavaVersionChecker

### ISSUE THREAD

**Issue by vshideler** [elastic/elasticsearch#28708]
****Elasticsearch version** (`bin/elasticsearch --version`):**

[root@sandbox-hdp elasticsearch-6.2.1]# bin/elasticsearch --version
Version: 6.2.1, Build: 7299dc3/2018-02-07T19:34:26.990113Z, JVM: 1.8.0_161

(also occurs with 6.1.1)

****Plugins installed**: []**

N/A

****JVM version** (`java -version`):**

[elastic@sandbox-hdp elasticsearch-6.1.1]$ sudo update-alternatives --config java

1 /usr/lib/jvm/jre-1.7.0-openjdk.x86_64/bin/java
*+ 2 /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
3 /usr/lib/jvm/jre-1.5.0-gcj/bin/java

****OS version** (`uname -a` if on a Unix-like system):**

[root@sandbox-hdp ~]# uname -a
Linux sandbox-hdp.hortonworks.com 4.4.114-1.el7.elrepo.x86_64 #1 SMP Wed Jan 31 13:03:33 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

****Description of the problem including expected versus actual behavior**:**

Could not find or load main class org.elasticsearch.tools.launchers.JavaVersionChecker

**Steps to reproduce**:

1. Created new user "elastic"
2. Downloaded elasticsearch-6.2.1.tar.gz
3. Extracted the file to the folder /elasticsearch-6.2.1
4. Upon running ./bin/elasticsearch encountered the error above
5. Added user "elastic" to the "wheel" group in order to grant it admin priveledges
6. Ran /.bin/elasticsearch but the error still occurred

Java appears to be installed properly and also appears to be up to date, however, this is a Hortonworks VM, so I do not know the ins and outs of how they have java set up.

There appears to be sufficient free disk space:

root@sandbox-hdp ~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          43G   21G   20G  52% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/sda3        43G   21G   20G  52% /etc/resolv.conf
/dev/sda3        43G   21G   20G  52% /etc/hostname
/dev/sda3        43G   21G   20G  52% /etc/hosts
shm              64M   12K   64M   1% /dev/shm

I'm not sure what else to check. If any assistance could be provided, it would be greatly appreciated!

**Comment by jasontedor** [comment]
I don't know, we have seen issues like this before (from the [forum](https://discuss.elastic.co/t/error-could-not-find-or-load-main-class-org-elasticsearch-tools-javaversionchecker/82213/), [here](https://github.com/elastic/elasticsearch/issues/27599), it's always something environmental. As such, I am going to close this issue as we only handle bugs and feature requests here. I want to help you though yet I encourage you to start with those linked issues first. If that does not help, open a topic on the [forum](https://discuss.elastic.co) and link to it from here.
