### ISSUE TITLE
Retrieving the documents(records) of a saved search in elastic search

### ISSUE THREAD

**Issue by sachidananda04** [elastic/elasticsearch#28701]
Hi,

I need a help in retrieving the documents (records) of a saved search.
I am pushing my jenkins pipeline jobs console logs to elasticsearch using jenkins-logstash plugin and it's pumping the data without any problem. I am filtering my jenkins console data using a field called "ISSUE_ID".I created a saved search with the output fields being
"time" "ISSUE_ID" "message" "BUILD_ID" "JOB_NAME". In kibana, I can see that my saved search is returning around 13 records for last 24 hrs. I used the content available in "Request" tab to retrieve the same no of documents(records) inside my ubuntu host using the below curl command. But it's dumping a huge amount of data.

How to retrieve the records with just the fields mentioned in saved search.

example output data what I am expecting is
![image](https://user-images.githubusercontent.com/22446800/36300557-dc32c4bc-1327-11e8-8c8e-66b30694205b.png)

The curl command is:
curl -X GET http://localhost:9200/logstash-*/_search --data @request.json

The content of the request.json (the Request kibana sent to Elasticsearch from the saved search) is:

{
"highlight": {
"pre_tags": [
"@kibana-highlighted-field@"
],
"post_tags": [
"@/kibana-highlighted-field@"
],
"fields": {
"": {}
},
"require_field_match": false,
"fragment_size": 2147483647
},
"query": {
"filtered": {
"query": {
"query_string": {
"analyze_wildcard": true,
"query": "ISSUE_ID"
}
},
"filter": {
"bool": {
"must": [
{
"range": {
"@timestamp": {
"gte": 1518515132440,
"lte": 1518601532440,
"format": "epoch_millis"
}
}
}
],
"must_not": []
}
}
}
},
"size": 500,
"sort": [
{
"@timestamp": {
"order": "desc",
"unmapped_type": "boolean"
}
}
],
"aggs": {
"2": {
"date_histogram": {
"field": "@timestamp",
"interval": "30m",
"time_zone": "Asia/Kolkata",
"min_doc_count": 0,
"extended_bounds": {
"min": 1518515132440,
"max": 1518601532440
}
}
}
},
"fields": [
"",
"_source"
],
"script_fields": {},
"fielddata_fields": [
"@timestamp",
"@buildTimestamp",
"post_date"
]
}

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by sachidananda04** [comment]
Sure. Thanks for the Info @dadoonet Have already raised the question in discuss.elastic.io
https://discuss.elastic.co/t/how-to-retrieve-the-documents-records-of-a-saved-search-in-elastic-search/119812
