### ISSUE TITLE
_update API should check the syntax in case of scripted updates

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#28740]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.1.2

**Plugins installed**: []

**Description of the problem including expected versus actual behavior**:

The `_update` API doesn't seem to reject a command that is wrong. Actually, this example comes from [The Definitive Guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/partial-updates.html) (which I know it's WIP), but still the ES API should reply back with an error for such a command:

```
POST /website/blog/1/_update
{
  "script": "ctx.op = ctx._source.views == params.count ? 'delete' : 'none'",
  "params": {
    "count": 1
  }
}
```

This returns:

```
{
  "_index": "website",
  "_type": "blog",
  "_id": "1",
  "_version": 2,
  "result": "noop",
  "_shards": {
    "total": 0,
    "successful": 0,
    "failed": 0
  }
}
```

Debugging this with `Debug.explain(params)` shows that there is no `params` registered. Which, in fact, is fine since the syntax is incorrect: there shouldn't be any `params` definitions at the root level, but inside `script` itself. The correct syntax should be:

```
POST /website/blog/1/_update
{
  "script": {
    "source": "ctx.op = ctx._source.views == params.count ? 'delete' : 'none'",
    "params": {
      "count": 1
    }
  }
}
```

**Comment by javanna** [comment]
cc @elastic/es-core-infra

**Comment by rjernst** [comment]
For anyone interested in fixing this, the lenient code is in `UpdateRequest.fromXContent`. The if/elseifs in the while loop need to handle unknown keys. Better yet would be to convert this to ObjectParser.

**Comment by nikhilbarar** [comment]
Is this issue still open? I'd like to pick this up.

**Comment by rjernst** [comment]
@nikhilbarar Please feel free to open a PR for this (or any other issues marked with `adoptme`. Thanks  for picking this up!
