### ISSUE TITLE
[CI] RolloverIT#testRolloverWithDateMath failed at midnight

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#28741]
The rollover test with the date pattern happened and failed at midnight.

```
1> [2018-02-19T11:59:59,017][INFO ][o.e.a.a.i.r.RolloverIT   ] [testRolloverWithDateMath]: before test
...
1> [2018-02-19T12:00:00,546][INFO ][o.e.a.a.i.r.RolloverIT   ] [RolloverIT#testRolloverWithDateMath]: cleaning up after test
```

The new index name was derived from the next day rather than today.

```
FAILURE 1.85s J2 | RolloverIT.testRolloverWithDateMath <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: "test-2018.02.19-000004"
   >      but: was "test-2018.02.20-000004"
   > 	at __randomizedtesting.SeedInfo.seed([DE29C74DF54CE353:5FEB5F63B28659FB]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.action.admin.indices.rollover.RolloverIT.testRolloverWithDateMath(RolloverIT.java:232)

```
CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=sles/695/console
Log: [testRolloverWithDateMath.txt](https://github.com/elastic/elasticsearch/files/1738671/testRolloverWithDateMath.txt)

**Comment by alexander-marquardt** [comment]
@saudurehman and myself have seen this manifest itself at the client site using version 6.2.2. 

When rollover happened, the alias points to a different index than what was created. At midnight, the index was created for the next day, but the alias still pointed to the previous day. 

Index created was 2018-03-27-000004 but the alias was pointing to 2018-03-26-000004. 

(this appears related to the following closed issue: https://github.com/elastic/elasticsearch/issues/24803)
