### ISSUE TITLE
Elasticsearch disabled elastic user after some restart Nodejs app

### ISSUE THREAD

**Issue by samialmorshedi** [elastic/elasticsearch#28764]
I have a Nodejs app using elastic search. For dev mode, I need lots of restarts my app. after some restarts, elastic shows me
`failed to authenticate user [elastic], with { header={ WWW-Authenticat at respond ...
`
I change the x-pack passwords for Elasticsearch and Kibana (auto generator) naw it fixed. Why elastic disable the elastic user after some refresh?

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by samialmorshedi** [comment]
I ask there but nobody (i`m unest nobody) helps me!!
