### ISSUE TITLE
query_string query works wrong for wildcard

### ISSUE THREAD

**Issue by nikoncode** [elastic/elasticsearch#28766]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.1

**Plugins installed**: []

**JVM version** (`java -version`): OpenJDK Runtime Environment (build 1.8.0_162-b01)

**OS version** (`uname -a` if on a Unix-like system): Linux mikita-pc 4.14.20-2-MANJARO #1 SMP PREEMPT Sat Feb 17 21:47:27 CET 2018 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Let's imagine I have two values: ["aa", "bb"]
(aa, bb) -> returns both (expected)
(a*) -> return aa (expected)
(a*, bb) -> returns bb (not expected)
(a*,bb) -> returns nothing (not expected)
(a* bb) -> returns both (kind of expected)

**Steps to reproduce**:

```
POST localhost:9200/tests/test/1
{
	"name": "aa"
}

POST localhost:9200/tests/test/2
{
	"name": "bb"
}

POST localhost:9200/tests/test/_search (return both, expected)
{
   "query":{
      "query_string":{
         "query":"(aa, bb)",
         "default_field":"name"
      }
   }
}

POST localhost:9200/tests/test/_search (return one, expected)
{
   "query":{
      "query_string":{
         "query":"(a*)",
         "default_field":"name"
      }
   }
}

POST localhost:9200/tests/test/_search (return only one, not expected)
{
   "query":{
      "query_string":{
         "query":"(a*, bb)",
         "default_field":"name"
      }
   }
}

POST localhost:9200/tests/test/_search (return nothing, not expected)
{
   "query":{
      "query_string":{
         "query":"(a*,bb)",
         "default_field":"name"
      }
   }
}

POST localhost:9200/tests/test/_search (return both)
{
   "query":{
      "query_string":{
         "query":"(a* bb)",
         "default_field":"name"
      }
   }
}
```

**Comment by dadoonet** [comment]
I never saw this `,` way to write query string. I might be wrong.

Any way, I tried this:

```
DELETE tests
PUT tests/doc/1
{
  "name": "aa"
}
PUT tests/doc/2
{
  "name": "bb"
}

GET tests/_search
{
  "query": {
    "query_string": {
      "query": "(a* OR bb)",
      "default_field": "name"
    }
  }
}
```

And this gives both results. 

I think it's better to discuss that on discuss.elastic.co as I'm unsure that it's a bug here but more how query string query works and is documented (unless I'm wrong).

**Comment by dadoonet** [comment]
`(a*, bb)` basically generates 2 tokens: `a*,` and `bb`. Only `bb` matches.
`(a*,bb)` generates 1 tokens: `a*,bb` which obviously does not match.

I'm closing then.

**Comment by nikoncode** [comment]
@dadoonet This is what i said
`(a*, bb)` generates two tokens `a*`, and `bb`
but why `(aa, bb)` generates `aa` and `bb`?
Where is logic here?

**Comment by dadoonet** [comment]
Please let's talk about this on discuss.elastic.co. You can link from discuss to this "issue" if needed.
