### ISSUE TITLE
Deb/RPM: plugins need to be packaged alongside elasticsearch

### ISSUE THREAD

**Issue by minfrin** [elastic/elasticsearch#28762]
At the moment, elasticsearch is packaged and made available via various means, including rpm and debian.

The plugins however are not packaged, and are instead downloaded at deploy time off the public internet. While useful for prototyping, this mechanism isn't robust enough for use in a production environment where SLAs and security requirements exist.

I have spent some time trying to patch this, however the gradle build has utilised embedded groovy code to build gradle plugin, and I have found that too impenetrable to get the plugin build and the debian/rpm build aligned with one another.

**Comment by colings86** [comment]
@elastic/es-core-infra Could you take a look into this?

**Comment by jasontedor** [comment]
> The plugins however are not packaged, and are instead downloaded at deploy time off the public internet.

It is possible to download these and install them offline from a file URL or via a proxy to a location that you control.

> While useful for prototyping, this mechanism isn't robust enough for use in a production environment where SLAs and security requirements exist.

Would you please elaborate why not given the above caveats?

> I have found that too impenetrable to get the plugin build and the debian/rpm build aligned with one another.

I am not sure what you mean by "alongside" and "aligned"? We currently build all artifacts from a single commit?

**Comment by minfrin** [comment]
Modern operating systems and distributions all offer packaging systems, and we use these packaging systems extensively to deploy software. In the case of Ubuntu, which we use, that packaging system is deb/aptly. Our RPM systems use dnf/yum.

We don't allow any of our systems to use bespoke software distribution systems, as these become an operational nightmare. Elastic is just one part of a larger system that has to be managed, and supporting exceptions is not something we allow.

Our systems make heavy use of autodeployment - there are no user serviceable parts in our systems. As a result, having a human or some bespoke process to handle the special case of downloading the plugins is not something we can automate safely.

Ordinarily, faced with a non-packaged project, we would add the packaging ourselves and contribute that packaging back to the project so we don't have to support that modification ourselves. In this case the gradle build in elasticsearch is a step too far in terms of complexity. We do not have skills in gradle, or groovy, and we do not practically have access to resources with those skills. For reasons that are unclear gradle is importing a custom written plugin written in groovy, to build a software project developed in java.

Our workaround is to build some simple maven projects to generate the debian packages we need. Unfortunately the elasticsearch release process publishes elasticsearch proper to maven central, but some time back publishing the plugins broke, and the only plugins available are obsolete.

While there are obvious workarounds we can deploy, each of those workarounds need to be performed by us, documented by us, and then maintained by us, as opposed to just using packages deployed by the elasticsearch project.

The elasticsearch project publishes packages, which is excellent. But elasticsearch has not packaged plugins, which causes immense headaches for people trying to deploy elasticsearch.

**Comment by jasontedor** [comment]
Thank you for explaining your situation, the context is helpful.

We have considered the idea of enabling the plugins to be installed via package managers (nb. not distributed with the Elasticsearch packages, that would increase the size of the distributions by entirely too much). We do not consider it a priority at this time. As such, I am going to close this issue as we do not intend to take any action right now. We will reopen this or open a new issue when we consider this to be a priority.
