### ISSUE TITLE
Elasticsearch 503 service unavailale

### ISSUE THREAD

**Issue by melvilgit** [elastic/elasticsearch#28763]
I have a kafka consumer continously writing to Elasticsearch.
My Elasticsearch version - 5.6.1
Problem - Getting intermittent errors 
 failed to execute on node  log-4879-org.elasticsearch.transport.ReceiveTimeoutTransportException: [sre-es-23990507-1-315814692][100.65.6.183:9300][cluster:monitor/nodes/stats[n]] request_id [1232041] timed out after [15000ms]

Also seeing lots of gc overhead spent warning messages.
Any help would be highly appreciated.

**Comment by colings86** [comment]
Hi @melvilgit , we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!
