### ISSUE TITLE
the code with title PUT MAPPING is wrong at Java API [6.2] » Java API Administration » Indices Administration

### ISSUE THREAD

**Issue by huangRZ11** [elastic/elasticsearch#28778]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by DaveCTurner** [comment]
Please follow the instructions for reporting issues (quoted above) - a two line issue title and no further detail isn't helpful. We need to know a bit more about what you mean by "wrong": what did you see when you tried it, and how does it differ from what you expected? Did you try any variations and did they help?

**Comment by DaveCTurner** [comment]
Sorry, forgot to mention @elastic/es-clients for a ping.

**Comment by clintongormley** [comment]
@DaveCTurner btw it should be @elastic/es-core-infra , not the clients team.

@huangRZ11 is referring to the code here: https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-admin-indices.html#java-admin-indices-put-mapping  (but I don't know what is wrong either).

**Comment by olcbean** [comment]
@huangRZ11 do you mean that the example should be : 

```
client.admin().indices().prepareCreate("twitter")   
        .addMapping(
                "tweet", "{\n" +               
                "    \"properties\": {\n" +
...
```
instead of 
```
client.admin().indices().prepareCreate("twitter")   
        .addMapping("tweet", "{\n" +               
                "    \"tweet\": {\n" +
                "      \"properties\": {\n" +
....
```
