### ISSUE TITLE
Fixing code snippet testing for attributes that contain a period

### ISSUE THREAD

**Issue by lcawl** [elastic/elasticsearch#28770]
This issue is related to the instructions in  https://github.com/elastic/elasticsearch/blob/master/docs/README.asciidoc 

// TESTRESPONSE[s/"17179869184"/$body.$_path/] failed because it seemed to stumble over the periods in this code snippet:

```
[source,js]
----
{
  "count": 1,
  "datafeeds": [
    {
      "datafeed_id": "datafeed-total-requests",
      "state": "started",
      "node": {
        ...
        "attributes": {
          "ml.machine_memory": "17179869184",
          "ml.max_open_jobs": "20",
          "ml.enabled": "true"
        }
      },
      "assignment_explanation": ""
    }
  ]
}
----
```

The work-around is as follows:
TESTRESPONSE[s/"17179869184"/$body.datafeeds.0.node.attributes.ml\\.machine_memory/]

Ideally the code snippet testing would be better able to handle the periods.

**Comment by nik9000** [comment]
@lcawl this should be fixed in master and 6.x.
