### ISSUE TITLE
make `message.text` not required on Slack action

### ISSUE THREAD

**Issue by twardnw** [elastic/elasticsearch#28775]
The Slack action currently requires `message.text` to be present, though it is not required by Slack itself. A message can have an attachment which contains the text to be displayed. The current requirement for `message.text` means a message with attachment needs both `message.text` and `message.attachments.text`, causing the message displayed in slack to look slightly disjointed.

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch only, we do not handle X-Pack issues here. For that, please use the [forum](https://discuss.elastic.co).

**Comment by twardnw** [comment]
Thanks for the direction.
