### ISSUE TITLE
IndicesClient.exists() can not be resolved

### ISSUE THREAD

**Issue by philboeselager** [elastic/elasticsearch#28789]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.1

**Plugins installed**: []

**JVM version** : 1.8.0_111 (build 1.8.0_111-b14)

**OS version** : Linux 4.4.0-112-generic #135-Ubuntu x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

Following the [official documentation](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.x/java-rest-high-indices-exists.html) , there should be a method `exists(GetIndexRequest)` .

But actually, there's no such method to be found in javadoc, sources, and therefore, the method can not be resolved.

**Steps to reproduce**:

 1. use dependency `"org.elasticsearch.client" % "elasticsearch-rest-high-level-client" % "6.2.1"`

 2. code:

    final RestClientBuilder builder = RestClient.builder(new HttpHost("localhost", "9200", "http"));
    final RestHighLevelClient client = new RestHighLevelClient(builder);
    final GetIndexRequest request = new GetIndexRequest().indices("myindex");
    assert(client.indices().exists(request));
 
3. compile

Alternatively, checkout https://github.com/hbz/oerworldmap/blob/1441-upgradeElasticsearch/app/services/ElasticsearchConfig.java#L119

**Provide logs (if relevant)**:

Error message is:

    org.elasticsearch.action.admin.indices.get.GetIndexRequest cannot be converted to org.elasticsearch.action.get.GetRequest

**Comment by jaymode** [comment]
Thanks for reporting this. The documentation link you've provided is for the next minor release as the version is `6.x`. The docs you should be looking at are for the `6.2` version; there is a version selection drop down to switch between versions. 

The indices exists API is a new edition that will be included in 6.3. https://github.com/elastic/elasticsearch/pull/27384
