### ISSUE TITLE
Terms Aggregation: Java client returns different result from HTTP API

### ISSUE THREAD

**Issue by mvreijn** [elastic/elasticsearch#28793]
For reference, I have an open question on Stackoverflow regarding this issue: https://stackoverflow.com/questions/48885306/elastic-java-client-returns-different-result-from-http-api

**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 5.6.7, Build: 4669214/2018-01-25T21:14:50.776Z, JVM: 1.8.0_162

**Plugins installed**: []
none

**JVM version** (`java -version`):
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): 
Linux nivo-a-idv 4.4.114-94.11-default #1 SMP Thu Feb 1 19:28:26 UTC 2018 (4309ff9) x86_64 x86_64 x86_64 GNU/Linux (SLES12SP3)

**Description of the problem including expected versus actual behavior**:
Executing a term aggregation search using the Java client yields a result without buckets, while the same query executed using the HTTP API (via curl) yields a result which does contain buckets. 

**Steps to reproduce**:

 1. Indexes are created by logstash using default settings
 2. Execute a terms aggregation query (content below) using curl -XPOST http://localhost:9200/logstash-*/logs/_search -d'{...}'
 3. Result contains one or more buckets for different loglevels
 4. Execute the same query using the Java client (using SearchTemplateBuilder)
 5. Result does not contain any buckets

**Provide logs (if relevant)**:
Query content:
`{
  "from" : 0,
  "size" : 0,
  "sort" : [
    {
      "@timestamp" : {
        "order" : "desc"
      }
    }
  ],
  "aggregations" : {
    "level" : {
      "terms" : {
        "field" : "level.keyword",
        "size" : 10,
        "min_doc_count" : 1,
        "shard_min_doc_count" : 0,
        "show_term_doc_count_error" : false,
        "order" : [
          {
            "_count" : "desc"
          },
          {
            "_term" : "asc"
          }
        ]
      }
    }
  }
}`

Query result from curl:
`{"took":1,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":11194,"max_score":0.0,"hits":[]},"aggregations":{"level":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[{"key":"INFO","doc_count":9069},{"key":"ERROR","doc_count":1117},{"key":"WARN","doc_count":1008}]}}}`

Query result from Java:
`{"took":2,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":11194,"max_score":0.0,"hits":[]},"aggregations":{"level":{"doc_count_error_upper_bound":0,"sum_other_doc_count":0,"buckets":[]}}}`

**Comment by jaymode** [comment]
@mvreijn we reserve our GitHub repository for bug reports but this looks more like a usage question and is more appropriate for our [forums](https://discuss.elastic.co/c/elasticsearch). The REST api internally uses the Java client to execute the search, so this is most likely a difference in how your application constructs the request.
