### ISSUE TITLE
Document "Limits to the number of shards which are searched in parallel"

### ISSUE THREAD

**Issue by bobbyi** [elastic/elasticsearch#28791]
The [release notes for ES 6.0](https://www.elastic.co/blog/elasticsearch-6-0-0-released) mention:

> Limits to the number of shards which are searched in parallel, so that a single query cannot dominate the cluster.

However, there is no mention of this feature in the documentation. I think the docs should mention that these limits exists as well as explaining how to remove or raise these limits if such is possible. 

I have searched for information about this new feature and could not find any explanation of it outside of that bullet point in the release notes.

**Comment by jasontedor** [comment]
That is covered on this [page](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/search-search.html#search-search); see the last paragraph. I am sorry that it was so hard for you to find, we need to think about what we can do to make it easier, perhaps a link from the release notes directly to the docs would have helped. I hope this helps you though.

**Comment by bobbyi** [comment]
@jasontedor Thank you! I had looked at that page, but missed the relevant part because it appears to be in the section entitled "Multi-Index, Multi-Type". I am not doing multi-index, multi-type queries, so I didn't think the answer could be there. 

I believe there needs to be a new section heading before the second-to-last paragraph, something like "Parallelism" or "Number of shards searched".

**Comment by jasontedor** [comment]
@bobbyi I agree, I pushed fb073216b1f4071077cdef3528d71da55c815f81. These will update on the [search page](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search.html) within roughly 30 minutes from now.

**Comment by jasontedor** [comment]
This is now [live](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search.html#search-concurrency-and-parallelism). Thanks for the feedback.
