### ISSUE TITLE
Provide additional time indicators for rejected threadpool metrics similar to linux load average

### ISSUE THREAD

**Issue by geekpete** [elastic/elasticsearch#28794]
**Describe the feature**:

Currently we only have cumulative counts for threadpool rejected counts that increment from server start time.

It'd be great to have something similar to linux load average time samples like last 1min, 5mins, last 15mins.
This would give an indication if rejections are happening recently or if they might be more historical.
It might be also good to have these ranges configurable, eg if you want to a metric for last 24h, but anything to start would be nice. The 1min might be too short perhaps, but a set of time period metrics would be great to begin with.

This will allow some time context to the rejected metrics in the case that a user isn't logging these metrics historically in a monitoring system.

**Comment by jasontedor** [comment]
Typically we do not provide analytics over metrics within Elasticsearch, preferring instead to rely on external systems on top of the raw data for that (for example, Kibana via Monitoring). Is there a compelling case for why we should deviate from that here?

**Comment by jasontedor** [comment]
FYI @elastic/es-core-infra.

**Comment by geekpete** [comment]
Yeah this is a great point, and would be a misstep in design of the core stats/engine I'd agree.
There's other/external ways to collect and analyse this type of data and should be separate from the metrics the core engine needs to worry about.
