### ISSUE TITLE
How to expose custom frequencies?

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#28803]
In [LUCENE-7854](https://issues.apache.org/jira/browse/LUCENE-7854), Lucene gained the ability to index custom term frequencies. This is typically useful in order to do index-time boosting of terms. The same can be achieved with payloads, with the downside that payloads are per-position while frequencies are per-term, which makes them much heavier if you don't need per-position boosts. I have seen multiple users do token stuffing in the past, so I think some people would use this feature, though I don't know what their actual use-cases were.

There are multiple options how to expose it:
 1. expose Lucene's `DelimitedTermFrequencyTokenFilter` so that it can be used in any `text` field: #27552
 2. add the ability to configure a term frequency with keyword fields, eg. `my_keyword_field: [{ "keyword": "foo", "frequency": 3 }, { "keyword": "bar", "frequency": 2 }]` instead of `my_keyword_field: [ "foo", "foo", "foo", "bar", "bar" ]`
 3. add a new field type, similar to `keyword`, to support this feature so that `keyword` doesn't have to be modified to accept objects

Some notes/questions about these options:
 - Option 1. would require index options to be set to `docs_and_freqs` since custom frequencies are rejected when positions are indexed, which is the default for `text` fields.
 - Should norms be enabled when this feature is used? Norms are disabled on keywords by default.

cc @elastic/es-search-aggs

**Comment by jpountz** [comment]
Discussed in Fixit Friday. We'll work on a dedicated field type to expose this feature (option 3).

A typical use-case of this feature would be to record keywords as well as boosts representing how well they characterize the document and then use it at search time to score documents using those boosts.

**Comment by jpountz** [comment]
For the record, [LUCENE-8197](https://issues.apache.org/jira/browse/LUCENE-8197) is another high-level feature that leverages custom term frequencies.

**Comment by romseygeek** [comment]
cc @elastic/es-search-aggs

**Comment by jpountz** [comment]
LUCENE-8197 was just pushed and should be available in Lucene 7.4. So hopefully we'll be able to integrate it soon.

**Comment by jpountz** [comment]
This has been implemented via the new `feature` and `feature_vector` fields.

**Comment by mrkamel** [comment]
as it think there was some renaming ... is this the `rank_feature`/`rank_features` datatype? and does it mean that internally it is implemented using https://issues.apache.org/jira/browse/LUCENE-7854 such that rank feature queries are "equally" performant as term queries - as there is just some manipulation of term frequencies internally going on?

**Comment by mayya-sharipova** [comment]
> as it think there was some renaming ... is this the rank_feature/rank_features datatype? 

Yes, these are `rank_feature(s)` field types. 

> and does it mean that internally it is implemented using https://issues.apache.org/jira/browse/LUCENE-7854 such that rank feature queries are "equally" performant as term queries - as there is just some manipulation of term frequencies internally going on?

Yes, they are equally performant and implemented using classes from https://issues.apache.org/jira/browse/LUCENE-7854.  We just store values with some loss of precision, as rank_features accept floats, while Lucene encodes freqs as integers.

**Comment by mrkamel** [comment]
that's great, thx! .. just one remark, if it is true then, that a `rank_features` field internally is a field of type `keyword` where the term frequencies  are modified according to the numeric value of the feature - then it's a bit unfortunate imho that the `keyword` is exposed as `field` in the API only (i.e. the `rank_feature` query), as it unneccessarily applies field name restrictions to it. In our use case, we have keywords with externally calculated "importance scores" for them which we want to index, such that a `rank_features` field fits perfectly conceptually and performance wise. But we still need to "encode" the keywords to work around the field name restrictions. A specialized `rank_features` query would be a nice addition imho, where field and keyword can be stated separately.

```
GET my-index-000001/_search
{
  "query": {
    "rank_features": {
      "field": "topics",
      "keyword": "politics"
    }
  }
}
```

instead of the example given at https://www.elastic.co/guide/en/elasticsearch/reference/current/rank-features.html

**Comment by mayya-sharipova** [comment]
>  it is true then, that a rank_features field internally is a field of type keyword where the term frequencies are modified according to the numeric value of the feature 

No, it is not. Neither is `rank_feature` field.

Indexing a doc with a keyword field : `"field1": "value"`, in Lucene translates to: 
- field name:field1, Term: field1, TermFreq: 1

Indexing a doc with a rank_feature field : `"field1": 10`, in Lucene translates to: 
-  field name:_feature, Term: field1, TermFreq: 10

Indexing a doc with a rank_features field : ` "topics": {"business": 20,"canada": 50 }`, in Lucene translates to: 
- field name: topics, Term: business, TermFreq: 20
- field name: topics, Term: canada, TermFreq: 50

---
> But we still need to "encode" the keywords to work around the field name restriction

I am not super clear what it means. Does it mean that you want to apply some keyword based queries or aggs to rank_feature field?

**Comment by mrkamel** [comment]
thx again for the detailed response

> No, it is not. Neither is rank_feature ...

maybe there was some mix-up regarding nomenclature from my side, but from your description it looks to me like i described or as i wanted to describe it :-)

> I am not super clear what it means. Does it mean that you want to apply some keyword based queries or aggs to rank_feature field?

i'll give an example. we have a "companies" index and companies have "keywords" with externally calculated "importance scores".

```
# company1

{ "keywords": { "car rental": 1.34, "car cleaning": 0.3, "..." } }
```

we want to index those keywords with their importance scores in a `rank_features` field and at search time we want the importance scores of the matching queries e.g. to simply sum up:

```json
{
  "must": [
    {
      "rank_feature": {
         "field": "keywords.car rental",
         "linear": {}
      },
    },
    {
      "rank_feature": {
        "field": "keywords.car cleaning",
        "linear": {}
      }
    }
  ]
}
```

In the query the "keyword" is stated as a "field", such that field name restrictions apply, such that we have to remove dots, etc from it. That's what i meant with "encode" in the previous comment. Maybe not a big deal, but semantically it would be nice to instead have a `rank_features` query where you can state it separately - and this would also be a better fit with regards to how it is stored internally on ES side (plz correct me if i'm wrong):

```json
{
  "must": [
    {
      "rank_features": {
         "field": "keywords",
         "keyword": "car rental",
         "linear": {}
      },
    },
    {
      "rank_features": {
        "field": "keywords",
        "keyword": "car cleaning",
        "linear": {},
      }
    }
  ]
}
```
