### ISSUE TITLE
Allow x-pack client to use provider other than BouncyCastleProvider

### ISSUE THREAD

**Issue by presto9292** [elastic/elasticsearch#28804]
Currently x-pack-api has a hardcoded compile-time dependency on BouncyCastleProvider

I have an application server that's using a FIPS JCE via BouncyCastleFipsProvider, and also needs to access a cloud instance of Elasticsearch via x-pack transport client

The two providers BouncyCastleProvider and BouncyCastleFipsProvider can not co-exist on the same classpath

I excluded bcprov-jdk15on from the maven x-pack-transport dependency of org.elasticsearch.client, but then obviously I encounter "ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider" which I can not resolve

Is there a way for x-pack to support some form of external JCE provider configuration ?

**Comment by jaymode** [comment]
This repository is only for elasticsearch issues. Please report x-pack issues in our [forums](https://discuss.elastic.co/c/x-pack).

We are working on providing support for FIPS compliant providers but we currently use certain features that only the BouncyCastleProvider provides but other providers (including the bc fips) do not provide support for and there are class conflicts between the FIPS and non-FIPS bouncycastle.
