### ISSUE TITLE
Add feature for executing search templates through High Level Rest Client

### ISSUE THREAD

**Issue by bharvidixit** [elastic/elasticsearch#28810]
<!--
I am using High Level Rest Client but unable to execute search template queries using it. For transport java client, the code samples are available on this page:  https://www.elastic.co/guide/en/elasticsearch/client/java-api/6.1/java-search-template.html

But i can't find something similar for high level rest client.

I have included lang-mustache-client in project mavel pom.xml in following way:
<dependency>
    <groupId>org.elasticsearch.plugin</groupId>
    <artifactId>lang-mustache-client</artifactId>
    <version>6.0.1</version>
</dependency>

The import import org.elasticsearch.script.mustache.SearchTemplateRequestBuilder; is working fine, but SearchTemplateRequestBuilder constructo takes reference of org.elasticsearch.client.ElasticsearchClient and this i can not cast rest client into ElasticsearchClient.

**Elasticsearch version** : 6.0.1

My code snipped looks like following:
```
import java.util.HashMap;
import java.util.Map;

import org.apache.http.HttpHost;
import org.elasticsearch.action.search.SearchRequest;
import org.elasticsearch.action.search.SearchResponse;
import org.elasticsearch.client.ElasticsearchClient;
import org.elasticsearch.client.RestClient;
import org.elasticsearch.client.RestHighLevelClient;
import org.elasticsearch.script.ScriptType;
import org.elasticsearch.script.mustache.SearchTemplateRequestBuilder;

public class Asss  {
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		RestHighLevelClient client = new RestHighLevelClient(
    	        RestClient.builder(
    	        		new HttpHost("host", "port", "https")
    	                ));
		Map<String, Object> template_params = new HashMap<>();
		template_params.put("param_gender", "male");
		SearchResponse sr = new SearchTemplateRequestBuilder((ElasticsearchClient) client)
		        .setScript("template_gender")                       
		        .setScriptType(ScriptType.STORED)     
		        .setScriptParams(template_params)                   
		        .setRequest(new SearchRequest())                    
		        .get()                                              
		        .getResponse(); 
	}
}

```
Following error i am getting executing above code:
Exception in thread "main" java.lang.ClassCastException: org.elasticsearch.client.RestHighLevelClient cannot be cast to org.elasticsearch.client.ElasticsearchClient
	at com.curmusic.data.model.elastic.services.Asss.main(Asss.java:27)

**Comment by jasontedor** [comment]
Duplicates #27205
