### ISSUE TITLE
Add documentation for "boundary_scanner_locale" in Highlighting docs

### ISSUE THREAD

**Issue by aguyinmontreal** [elastic/elasticsearch#28816]
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html

For the docs.

What are the accepted values for "boundary_scanner_locale"? What is the default value?

Thanks

**Comment by tlrx** [comment]
Hi, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elastic forums](https://discuss.elastic.co/) instead. Thank you!

**Comment by aslamy** [comment]
There is a lack of documentation.

I don't know why everyone just wants to close issues without even understanding it.

**Comment by tlrx** [comment]
@aslamy We're dealing with a lot of issues and questions and it's sometimes hard to distinguish between a simple question and a demand for improving something, like docs in this case.

I took @aguyinmontreal as a question and therefore I redirected to the Discuss forum which are the appropriate place for question like this. @aslamy If you feel like the doc must be improved then creating an issue with "Improve XX in documentation" - or even better, a pull request :) - is a good start.

**Comment by aguyinmontreal** [comment]
@tlrx @aslamy Yes, I opened this issue for lack of documentation. I don't think I should overwhelm elastic.co/discuss with questions like this. This should be in the documentation to start with.

Thank you

**Comment by tlrx** [comment]
Thanks @aguyinmontreal ! I updated the title and add some labels to make more this more obvious (at least to me).

**Comment by aguyinmontreal** [comment]
@tlrx If someone has an answer, I can submit a PR

**Comment by aguyinmontreal** [comment]
@tlrx Can someone from the team tell me if these are the ones?https://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#field_summary

**Comment by mayya-sharipova** [comment]
@aguyinmontreal  thanks so much for bringing this up. We will work on this, and update the issue once the work is done.

**Comment by aguyinmontreal** [comment]
@mayya-sharipova Not a problem, Thank you for working on this!

**Comment by aguyinmontreal** [comment]
@mayya-sharipova 

Are you sure it accepts `US`, `CHINA`, `JAPAN` as language tags?  

I thought it was `ENGLISH` , `FRENCH` , `GERMAN` , `ITALIAN` , `JAPANESE` , `KOREAN` , `CHINESE` , `SIMPLIFIED_CHINESE` , `TRADITIONAL_CHINESE`  and `CANADA_FRENCH`.

https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#forLanguageTag-java.lang.String-[Locale] (see _Field Detail_ section)

**Comment by mayya-sharipova** [comment]
@aguyinmontreal Thanks, I will double check for this!

**Comment by aguyinmontreal** [comment]
@mayya-sharipova  And also, please let me know if `ENGLISH` is the default value or if there's no default value at all.  Thanks

**Comment by mayya-sharipova** [comment]
@aguyinmontreal Thank so much for your feedback. I was wrong, I have updated the PR accordingly: https://github.com/elastic/elasticsearch/pull/28802/commits/f6e1990784f86d75445dc56563105aee7cea92ad

**Comment by aguyinmontreal** [comment]
@mayya-sharipova  Alright! Thanks!

I'm not sure what `The default value is https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#ROOT[ Locale.ROOT].` means though... Are you saying that the default value is different from one computer to the other?

**Comment by mayya-sharipova** [comment]
@aguyinmontreal I can only cite Java's documentation on this.  In case a `boundary_scanner_locale` is not specified in the request, [Locale.ROOT](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#ROOT) will be used in 
 [Java's BreakIterator](https://docs.oracle.com/javase/8/docs/api/java/text/BreakIterator.html). You can look at Java's BreakIterator source code to see how Locale.ROOT is used there.
Sorry, I don't know the details.

**Comment by aguyinmontreal** [comment]
@mayya-sharipova Alright! Thanks for this clarification.

**Comment by jimczi** [comment]
cc @elastic/es-search-aggs

**Comment by debadair** [comment]
Closed as fixed by https://github.com/elastic/elasticsearch/pull/28802
