### ISSUE TITLE
comment and code are Inconsistent

### ISSUE THREAD

**Issue by hjxhjh** [elastic/elasticsearch#28827]
when reading ES code found this 
`        // optimize search type for cases where there is only one shard group to search on
        if (shardIterators.size() == 1) {
            // if we only have one group, then we always want Q_A_F, no need for DFS, and no need to do THEN since we hit one shard
            searchRequest.searchType(QUERY_THEN_FETCH);
        }
`

comment and the code are Inconsistent？

on branch 5.6 
class is： org.elasticsearch.action.search.TransportSearchAction
in method :
`
private void executeSearch(SearchTask task, SearchTimeProvider timeProvider, SearchRequest searchRequest, OriginalIndices localIndices,
                               Map<String, OriginalIndices> remoteClusterIndices, List<SearchShardIterator> remoteShardIterators,
                               BiFunction<String, String, DiscoveryNode> remoteConnections, ClusterState clusterState,
                               Map<String, AliasFilter> remoteAliasMap, ActionListener<SearchResponse> listener, int nodeCount) {
`
line : 285-288

**Comment by jasontedor** [comment]
In the master branch: https://github.com/elastic/elasticsearch/blob/929dba866758fcf9be4b984a83f6f08196cc6b4e/server/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java#L314-L318

I think it's fine, and we will leave the 5.6 branch as is.
