### ISSUE TITLE
Why elasticsearch Aggregation is named bucket instead of dimension?

### ISSUE THREAD

**Issue by jiangjunjian** [elastic/elasticsearch#28822]
Why elasticsearch Aggregation is named bucket instead of dimension

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by jiangjunjian** [comment]
thank you
