### ISSUE TITLE
Confusing log messages that do not match with the method name

### ISSUE THREAD

**Issue by lzh3636** [elastic/elasticsearch#28828]
**Elasticsearch version** : 6.2.2

**Plugins installed**: [No]

**JVM version** (`java -version`):1.8.0

**OS version** (`uname -a` if on a Unix-like system):OS 10.12.6

**Description of the problem including expected versus actual behavior**:

We found that there are some possible copy and paste errors in the log messages which may cause some confusion when operators are reading the log messages. 

At org.elasticsearch.bootstrap.Natives, there are two methods:

static void tryMlockall() {
        if (!JNA_AVAILABLE) {
            logger.warn("cannot mlockall because JNA is not available");
            return;
        }
        JNANatives.tryMlockall();
    }

static void **tryVirtualLock()** {
        if (!JNA_AVAILABLE) {
            logger.warn("cannot **mlockall** because JNA is not available");
            return;
        }
        JNANatives.tryVirtualLock();
    }

seems like that the log message in tryVirtualLock() doesn't match with the method name.
Maybe just simply change the message to "cannot virtual lock because JNA is not available",
I'll do a PR to fix this issue.

**Comment by jasontedor** [comment]
Thanks @lzh3636. For future reference, an open issue is not necessary to open a PR. It is sufficient to describe the issue within the PR itself, and it saves the overhead of an issue.
