### ISSUE TITLE
Incorrect Calculation of @timestamp 

### ISSUE THREAD

**Issue by cj-nza** [elastic/elasticsearch#28824]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

Version: 6.2.2, Build: 10b1edd/2018-02-16T19:01:30.685723Z, JVM: 1.8.0_151

**Plugins installed**: []

**JVM version** (`java -version`):

openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

4.4.0-116-generic

**Description of the problem including expected versus actual behavior**:

Calculation for timestamp does not correctly consider date boundary (specifically for logs collected via the "system" module in filebeats 

Kibana / Elasticsearch documents are present with @timestamp of February **26th** 2018, 23:59:18.000

These event were logged at February 26 2018,10:59:18 NZDT  

Expected UTC Time February **25** 2018, 21:59:18 
  
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Use local time zone UTC +13 
 2. Enable System module in filebeats (var.convert_timezone: seems to have no effect on unexpected outcome)   
 3. Verify timestamp values of events logged (from syslog and auth.log)
 
**Provide logs (if relevant)**:

**Comment by DaveCTurner** [comment]
I'm afraid it's not possible to reproduce this from the instructions given. Can you give more detail on how to make this happen, ideally so we can run the instructions on a clean installation?

However I note that the actual and desired time are 26 hours apart, which could be explained by confusing UTC+13 and UTC-13, or by confusing local time with UTC somewhere. The time stamps in the OP do not all have timezones attached. Note that IANA timezone `Etc/GMT-13` coincides with New Zealand's time zone at the moment, not `Etc/GMT+13`, although if that's the problem then I recommend using `Pacific/Auckland` instead to correctly handle DST.

**Comment by cj-nza** [comment]
Thanks - my first experimental/discovery install of Elastic 

My system time: 
Local time: Tue 2018-02-27 06:50:58 NZDT
Universal time: Mon 2018-02-26 17:50:58 UTC
RTC time: Mon 2018-02-26 17:50:58
Time zone: Pacific/Auckland (NZDT, +1300)
Network time on: yes
NTP synchronized: yes
RTC in local TZ: no

Clean install of Elasticsearch, Kibana and Filebeat
Follow instructions for filebeat as per https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-getting-started.html

Create two filebeat prospectors in filebeat.yml

Enable ./filebeat -e --modules system (retain default config)

Records displayed in Kibana for two prospectors (router and bind) has correct timestamp
Records displayed in Kibana for syslog and auth.log has timestamp 13 hours in future

**Comment by DaveCTurner** [comment]
Ok, I still cannot reproduce this. I have tried a fresh installation of Elasticsearch + Kibana + Filebeat 6.2.2, in NZDT, and the timestamps I see in Kibana are correct - here is a screenshot of a recent event from syslog (which you report as problematic).

<img width="1215" alt="screen shot 2018-02-28 at 07 38 55" src="https://user-images.githubusercontent.com/5058284/36747669-75a800d2-1baa-11e8-930b-48a55f2378bf.png">

The fact that _some_ timestamps are correct and others are not indicates that it's very likely the problem lives outside Elasticsearch, so this isn't the right repository for this issue. I think the best place to start would be https://github.com/elastic/beats/issues. I'm going to close this issue, but if the investigation with Filebeat results yields a reproduction that involves just Elasticsearch and not Filebeat then please re-open this. Please link to this issue from the issue in the Beats repository so it's easier to follow the thread.
