### ISSUE TITLE
Merge different sites in one global node

### ISSUE THREAD

**Issue by Hanender** [elastic/elasticsearch#28837]
Hi,
I would like to configure a single Elastic system for 4 regions having different addresses instead of having a system for each one of them . That means setting one node for the 4 regions and not a node per region.
(PS: sites are related by VPN Connections).
Is that something feasible please? If so, could you please mention which configurations we should go through to realize that?
Many thanks for your support and help.

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
