### ISSUE TITLE
Backwards-incompatible change introduced in minor version update 5.2 -> 5.3: payload parameter removed

### ISSUE THREAD

**Issue by KrzysztofMadejski** [elastic/elasticsearch#28846]
**Elasticsearch version**: 5.3 and all further ones in 5.x branch

Problem: Payload parameter has been removed in ElasticSearch 5.3.0 . More info on https://stackoverflow.com/questions/43513997/mapping-definition-for-suggest-has-unsupported-parameters-payloads-true

Example error:
```
Mapping definition for [suggest_v7] has unsupported parameters:  [payloads : true  
  ] [context : {dataset={type=category, path=_type, default=[*]}}]
```

Introducing a backwards incompatible changes in minor version is contrary to the declaration at https://www.elastic.co/support/eol

Following up conversation started in #23486

**Comment by KrzysztofMadejski** [comment]
Proposed solution would be to bring it back in the next 5.x version.

**Comment by jasontedor** [comment]
> Proposed solution would be to bring it back in the next 5.x version.

I’m sorry that we disappointed you here. We try not to make breaking changes in minor releases. There have been times we have done it deliberately to address serious bugs. That aside, it’s not clear what happened here, but we are more sensitive to breaking changes these days (as evidenced by enabling rolling upgrades between major releases). We will not be reintroducing this parameter in 5.x, the 5.x series is in maintenance mode only where we focus on stability and fixing critical bugs.

**Comment by KrzysztofMadejski** [comment]
Ok, thanks for replying on it.
