### ISSUE TITLE
"discovery.zen.no_master_block: write" does not work

### ISSUE THREAD

**Issue by GoodMirek** [elastic/elasticsearch#28842]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.2.2 (installed via apt-get from https://artifacts.elastic.co/packages/6.x/apt)

**Plugins installed**: []
discovery-ec2
repository-s3

**JVM version** (`java -version`):
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux ip-172-31-17-123 4.4.0-1050-aws #59-Ubuntu SMP Tue Jan 30 19:57:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
In [doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-zen.html) it is described that setting:
```
discovery.zen.no_master_block: write
```
should allow read operations on cluster when master is not available.
However, actual behavior is that connection to http Elasticsearch API (port 9200) is refused.

**Steps to reproduce**:
1. Setup cluster with `discovery.zen.minimum_master_nodes: 2`. Set discovery to ec2, use security group name for the discovery.
2. Start the cluster with two master-eligible nodes. Verify you can connect to the cluster and both master-eligible nodes are up and running, e.g. with command:
```
curl localhost:9200/_cat/nodes?v
```
3. Shut down one of the master-eligible nodes.
4. Try to connect to the remaining running node, it fails:
```
curl localhost:9200/_cat/nodes?v
```

**Provide logs (if relevant)**:
[2018-02-27T16:54:14,076][WARN ][o.e.d.z.ZenDiscovery     ] [log-es] not enough master nodes discovered during pinging (found [[Candidate{node={log-es}{bo7r6O6vTWylDPXDcjYWDA}{m-WSBSVtQ4W_2JCXEN4ntg}{172.31.17.123}{172.31.17.123:9300}{aws_availability_zone=eu-central-1b}, clusterStateVersion=5}]], but needed [2]), pinging again

**Comment by bleskes** [comment]
I suspect you cluster was never formed. That setting is only relevant once you have a fully running cluster and the master is lost. Can you please open a topic on discuss.elastic.co so we can figure out what's going on? If it turns out to be an issue we can reopen.
