### ISSUE TITLE
Add warning for read-write indices in force merge documentation

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#28843]
Running force merge against a read-write index (an index that can still have read/write activity post force-merge) can cause very large segments to be produced (>5Gb per segment), and the merge policy will never consider it for merging again until it has 75% of deleted docs.  This can cause very large segments to remain in the shards.

This is not currently documented (https://www.elastic.co/guide/en/elasticsearch/reference/6.2/indices-forcemerge.html).  Would like to see a warning message added to the above page to specify force merge as an API call to use only against read-only indices.

**Comment by mueedc** [comment]
I'd be happy to give this a shot if no one else has claimed it

**Comment by javanna** [comment]
go for it @mueedc , looking forward to your PR ;)

**Comment by eloj** [comment]
I know this is an old:ish issue, but the warning text merged seems misleading, at least to relatively inexperienced users like myself.

I immediately assumed that I should set `index.blocks.read_only` (or `.read_only_allow_delete`) to make the index **read-only** before issuing a force merge, but this then results in a `403` when trying to merge.

It was explained to me [on twitter](https://twitter.com/xeraa/status/1104170307139629057) that the actual meaning is that there should be no concurrent writes, not that the index should be set to **read-only**.

Please consider if the warning can be rewritten to be clearer. Thank you.

**Comment by laf-rge** [comment]
> I know this is an old:ish issue, but the warning text merged seems misleading, at least to relatively inexperienced users like myself.
> 
> I immediately assumed that I should set `index.blocks.read_only` (or `.read_only_allow_delete`) to make the index **read-only** before issuing a force merge, but this then results in a `403` when trying to merge.
> 
> It was explained to me [on twitter](https://twitter.com/xeraa/status/1104170307139629057) that the actual meaning is that there should be no concurrent writes, not that the index should be set to **read-only**.
> 
> Please consider if the warning can be rewritten to be clearer. Thank you.

I just did the same thing.

**Comment by DaveCTurner** [comment]
Thanks for the comments @laf-rge and @eloj, I opened https://github.com/elastic/elasticsearch/issues/41624 to discuss fixes.
