### ISSUE TITLE
Rename discovery.zen.minimum_master_nodes setting to simplify docs.

### ISSUE THREAD

**Issue by KrzysztofMadejski** [elastic/elasticsearch#28845]
**Describe the feature**:

Why having a setting that you need to calculate manually a equation. Can't ES do that? 

The equation is super easy, but it just adds to the complexity of the documentation. Why not rename it to `discovery.zen.master_eligible_nodes` and ask people to set it accordingly to their setup. ` discovery.zen.minimum_master_nodes` could be then computed accordingly.

Concerned piece of the documentation: https://www.elastic.co/guide/en/elasticsearch/reference/6.2/discovery-settings.html#minimum_master_nodes

**Comment by jasontedor** [comment]
We are not going to rename this setting. Instead, we have much bigger changes in mind that we think will significantly improve the story. We are not ready to share this quite yet, but will in due time and will be seeking a lot of feedback from the community.
