### ISSUE TITLE
Introduce equals query for geoshape field

### ISSUE THREAD

**Issue by arthurgustin** [elastic/elasticsearch#28853]
#### Current feature
Geoshape only allow geo queries

#### Requested feature
Ability to test the *exact* equality of two geo shapes

**Example 1**: document1 and document2 both have geoshape polygon with points ABCDA (exact same vertices) and we would like to test that those geoshapes are equals

**Example 2**: document1 has polygon ABDCA and document2 has polygon BCDAB (exact same vertices, different ordering) and we would like the test to return that those are equals

Workaround solution: At indexing time, index as a single keyword field a concatenation of all the vertices. For example 2 to work the order of the vertices must be ordered in exact same order for all documents (example starting by top-right vertice)

**Comment by javanna** [comment]
cc @elastic/es-search-aggs

**Comment by colings86** [comment]
@nknize could you comment on how viable this would be?

**Comment by DaveCTurner** [comment]
We discussed this in Fix-it Friday. It seems like it'd probably be feasible but is a long way down the list of things we expect to do, would add some complexity to how shapes are indexed, and can be emulated in the client as described above. Arguably we could keep it open as an "adoptme" for a while, but on balance it seems better to close it now.
