### ISSUE TITLE
REST Client API BulkProcessor should expose few methods to understand it's internal status

### ISSUE THREAD

**Issue by detro** [elastic/elasticsearch#28851]
**Describe the feature**:
`BulkProcessor` provides a very clean way to keep piling up bulk requests, leaving to the official client code to handle how fast and with which back-off strategy errors are retried.

One issue I found quite _annoying_ is that there are no methods exposed on the `BulkProcessor` to help understand it's internal status. I'm after things like:
* how many Requests are still pending?
* how many Requests are being processed right now?

In a _production_ environment, those would have little use, but in a testing environment they are pretty crucial, to ensure reliable tests can be written. Otherwise the only way is to avoid BULK requests during testing, but this leaves us with an area of untested code.

Right now I have setup things to wait a totally arbitrary 5 seconds. But it's a bad and unreliable solution (I'm sure it will make my tests fail sporadically).

Can we get something like this implemented?

**Comment by javanna** [comment]
hi @detro thanks for opening this issue. Could you post an example of a test where you've been struggling and what you would like to see implemented that it's currently missing? In our tests we tend to use `awaitClose` which is usually enough to make sure that all the documents that we need indexed have been sent.

**Comment by detro** [comment]
So, it's complicated to share the details without sharing the actual code.

What I'm testing is, essentially, a DAO that internally uses Elasticsearch as backend. This DAO will allow both single-document requests (normal CRUD kind of thing) and Bulk operations (for when we need to index a lot of stuff).

The `BulkProcessor` is kinda perfect for this, hence the choice of using it (until now we were using Jest as REST client, and we have come up with, essentially, the same kind of Bulk loader you guys built).

What my test does is simple:
1. DAO.bulkLoad(lots_of_write_document_requests)
2. DAO.query(searchRequest)
3. Check Total Hits
4. Check hits
5. Deserialize hits (i.e. deserialize them into our own POJOs)

### Small update since I wrote this issue

@antoniopironti (colleague) suggested I'd take a look at your tests of `BulkProcessor`, and I found that essentially you guys do 2 things to ensure _synchronization_ when testing:
* a `CountDownLatch`
* 2 `AtomicLong` counter to check the amount of BEFORE and AFTER requests

The file: https://github.com/elastic/elasticsearch/blob/99f88f15c5febbca2d13b5b5fda27b844153bf1a/server/src/test/java/org/elasticsearch/action/bulk/BulkProcessorIT.java#L341

So, in my DAO I'm following this route for now (keep 2 counters and have a `hasPendingRequests` method that just does a difference). But I'm essentially inferring the internal status of the `BulkProcessor`. And that smells of _anti pattern_.

**Comment by jasontedor** [comment]
We discussed this in Fix-it-Friday. We think that using the listener callbacks exposed here are the way to track this information, if needed. We prefer to keep our public-facing APIs small and since this information is already available via the callback mechanism, we would prefer not to expose this information directly increasing the weight of the public-facing API.
