### ISSUE TITLE
Different query in multiple indices search

### ISSUE THREAD

**Issue by BDominik** [elastic/elasticsearch#28864]
Elasticsearch 6.*

PHP client
When we searching through multiple indicies is it possible to build different querys for different indices?

$params = [
            'index' => 'serviceme_ngram,serviceme',
            'type' => 'products,products',
            'size' => $size,
            'body' => [
                'query' => [
                    "bool" => [
                        'should' => $query_for_first_index
                    ],
                    "bool" => [
                        'should' => $query_for_second_index
                    ]
                ]
            ]

**Comment by javanna** [comment]
hi @BDominik please ask questions on our forums at https://discuss.elastic.co/ , we reserve github for bug or feature requests. Thank you!
