### ISSUE TITLE
Confusing logging level in IndexShard

### ISSUE THREAD

**Issue by lzh3636** [elastic/elasticsearch#28879]
In org.elasticsearch.index.shard.IndexShard.getActiveOperationsCount(), there is a logging statement:

![image](https://user-images.githubusercontent.com/14232097/36876700-358a10a4-1d84-11e8-81bf-18f00cdb0530.png)

The log level of it is **debug,** but there is a comment near it // if this fails we are in deep shit - fail the request. Does it mean that this is an important log rather than just a debug one?

And also in org.elasticsearch.index.IndexService.maybeFSyncTranslogs(), there is a logging statement which has the same log message:
![image](https://user-images.githubusercontent.com/14232097/36876808-d8f2c8f8-1d84-11e8-9357-2362ff9d03cc.png)

But the log level here is **warn**, should the level of previous one be changed to a higher level, like warn or error?

**Comment by jasontedor** [comment]
I think that we are doing the right thing here. The exception is re-thrown in the translog sync processor and handled elsewhere. In the case of maybe fsyncing the translog, the exception is swallowed so needs to be logged visibly there.
