### ISSUE TITLE
Creating a dynamic swagger for an Elasticsearch API

### ISSUE THREAD

**Issue by Hafyane** [elastic/elasticsearch#28887]
I want to create a **dynamic swagger** of an **elasticsearch API** since the response returned by Api is unexpected because it contains **facets** and I would like to know if there is way to generate the **swagger** automatically through **elasticsearch.**

**Comment by dadoonet** [comment]
In short: no.

But please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by dadoonet** [comment]
Related to #25152
