### ISSUE TITLE
@timestamp can't be updated in painless script

### ISSUE THREAD

**Issue by aslng** [elastic/elasticsearch#28880]
What we would like to achieve is to add/update elasticsearch record with timestamp generated by Elasticsearch daemon such that the timestamp is more consistent.

Option1: use _timestamp mechanism in ES 2.x. However, this has been obsoleted in 5.x.
Option2: use painless script to add @timestamp. However, this won't work with updating doc at the same time. Workaround is to update doc as part of the script. It's ok. Though, painful script doesn't allow the @ character in @timestamp.
The reason we use @timestamp is that it's the standard timestamp name used by elasticsearch.

Can @ character be escaped in painful in the following example? Can this be fixed?

POST /test/test1/1/_update
{
    "script" : {
        "inline" : "DateFormat df = new SimpleDateFormat(\"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'\");\ndf.setTimeZone(TimeZone.getTimeZone(\"UTC\"));\nDate date = new  Date();\nctx._source.@timestamp=df.format(date);ctx._source.hostname='h3';"
    }
}
Error reported:
{
  "error": {
    "root_cause": [
      {
        "type": "remote_transport_exception",
        "reason": "[prismo_es_node][127.0.0.1:9300][indices:data/write/update[s]]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "failed to execute script",
    "caused_by": {
      "type": "script_exception",
      "reason": "compile error",
      "script_stack": [
        "... new  Date();\nctx._source.@timestamp=df.format(date ...",
        "                             ^---- HERE"
      ],
      "script": "DateFormat df = new SimpleDateFormat(\"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'\");\ndf.setTimeZone(TimeZone.getTimeZone(\"UTC\"));\nDate date = new  Date();\nctx._source.@timestamp=df.format(date);ctx._source.hostname='h3';",
      "lang": "painless",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "unexpected character [@].",
        "caused_by": {
          "type": "lexer_no_viable_alt_exception",
          "reason": null
        }
      }
    }
  },
  "status": 400
}

The following is ok.
POST /test/doc/1/_update
{
    "script" : {
        "inline" : "DateFormat df = new SimpleDateFormat(\"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'\");\ndf.setTimeZone(TimeZone.getTimeZone(\"UTC\"));\nDate date = new  Date();\nctx._source.timestamp=df.format(date);ctx._source.hostname='h3';"
    }
}

**Comment by rjernst** [comment]
Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports.

With that said, [see the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-fields.html) for accessing fields from the special `doc` variable in scripts.
