### ISSUE TITLE
HTTP implementation based on elasticsearch-nio

### ISSUE THREAD

**Issue by tbrooks8** [elastic/elasticsearch#28898]
This is related to #27260. We will need a working http plugin based on the elasticsearch-nio work. This should have feature parity with our other http implementations. This means supporting:
- cors
- pipeling
- normal http plugin settings (https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html)
- HTTP/1.1

**Comment by jasontedor** [comment]
FYI @elastic/es-core-infra.

**Comment by spinscale** [comment]
super minor, but just to add it here for the sake of completeness: usage of the `X-Opaque-Id` in `Netty4HttpChannel`, a header that is passed from the request to the response for identification purposes

**Comment by tbrooks8** [comment]
Closing this as the main work has been completed.
