### ISSUE TITLE
Pods should rearrange based on data values or threshold set

### ISSUE THREAD

**Issue by cbabhilash** [elastic/elasticsearch#28913]
Pods should rearrange based on data values or threshold set. Currently each of the pods in a Kibana dashboard are fixed in position. We want the more important ones to show up on top. This cannot be preset because priority is dependent on the value of the data. For ex. there is a high CPU usage then i want the pod for CPU to show up on top

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
This looks like it was opened against the wrong repository. Perhaps [elastic/kibana](https://github.com/elastic/kibana) would be a better repository for this issue?
