### ISSUE TITLE
QueryString query - quoted _exists_ query returns no result

### ISSUE THREAD

**Issue by nikoncode** [elastic/elasticsearch#28922]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.1

**Plugins installed**: []

**JVM version** (`java -version`): OpenJDK Runtime Environment (build 1.8.0_162-b01)

**OS version** (`uname -a` if on a Unix-like system): Linux mikita-pc 4.14.20-2-MANJARO #1 SMP PREEMPT Sat Feb 17 21:47:27 CET 2018 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
` _exists_: test` - works (converted in `NormsFieldExistsQuery`), 
` _exists_: \"test\"` - doesn't work (converted in `MatchNoDocsQuery("unmapped field [_exists_]")`).
It's not possible to use `_exists_` in `query_string` query with fields which contains spaces in name (it works in es 1.7)

**Steps to reproduce**:

```
POST localhost:9200/tests/test/1
{
	"name": "aa"
}

POST localhost:9200/tests/test/_search (returns document, expected)
{
   "query":{
      "query_string":{
         "query":"_exists_: name"
      }
   }
}

POST localhost:9200/tests/test/_search (returns nothing, not expected but works in ES 1.7)
{
   "query":{
      "query_string":{
         "query":"_exists_: \"name\""
      }
   }
}
```

It's impossible to use exists query with field with spaces:
```
POST localhost:9200/tests/test/1
{
	"na me": "aa"
}

POST localhost:9200/tests/test/_search (returns nothing, expected)
{
   "query":{
      "query_string":{
         "query":"_exists_: na me"
      }
   }
}

POST localhost:9200/tests/test/_search (returns nothing, not expected, works in ES 1.7)
{
   "query":{
      "query_string":{
         "query":"_exists_: \"na me\""
      }
   }
}
```

**Comment by spinscale** [comment]
@elastic/es-search-aggs can you take a look?

One can use `"query":"_exists_:na\\ me"` to get the desired result, though I am not sure if the above syntax is expected to work as well

**Comment by jimczi** [comment]
This is a regression, we should accept the quoted version (e.g. `_exists_:"na me"`). I'll work on a fix.

**Comment by nikoncode** [comment]
@jimczi since no progress on this issue, would you mind if I try to fix it by myself?

**Comment by jimczi** [comment]
Sorry for the delay @nikoncode , this issue slipped through the cracks. I opened https://github.com/elastic/elasticsearch/pull/33019 to fix it.
