### ISSUE TITLE
Search for a parent and all it's children in one query in elastic search

### ISSUE THREAD

**Issue by RishuK** [elastic/elasticsearch#28924]
Referring to the examples mentioned in the official documentation of building a parent-child relationship - https://www.elastic.co/guide/en/elasticsearch/reference/current/parent-join.html

The link has provided question-answer join relationship where question is a parent and answer is a child type.

If you need to search for all parents matching some text along with their children matching some text specific to children in one query, how would you do that?

Let's say they have key-value pairs in the json document as below and we search for parents matching a text in the question and children matching a value in answer-text.

Parent --> question --> "question-text" : "Geography: Where is Mt. Everest?"
Child --> answer --> "answer-text" : "Nepal?"
We do not want just parents or just children in the result but all parents with their associated children which matched the query.

I know inner hits is an option but could not figure out the usage - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-inner-hits.html

I hope the question is clear, can add more details if needed.

I also tried the example mentioned here for parent-child inner hits:

Example:

POST labelling_index/_search
    {
      "query": {
        "has_child": {
          "type": "child",
          "query": {
            "match": {
              "number": 2
            }
          },
          "inner_hits": {}    
        }
      }
    }
This gives me the matching children of all parents. How do I add a filter to the parent and query only for specific parents in the same query (along with the child filter)? Is it possible to filter parent records on a specific field in the same query?

**Comment by spinscale** [comment]
Please ask questions like this on our [Elasticsearch discuss forum](https://discuss.elastic.co/c/elasticsearch), as we try to use github for bugs and issues only. Thank you!

**Comment by RishuK** [comment]
Ok, I have posted here - https://discuss.elastic.co/t/search-for-a-parent-and-all-its-children-in-one-query-in-elastic-search/122902

If someone here has an idea and can answer, that would be awesome. Thankyou
