### ISSUE TITLE
Don't load global state when only restoring indices

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#28934]
Restoring from a snapshot currently also always loads the global state (templates, customs, ...) even though it's not always used by the restore process, for example when `include_global_state` is set to `false` in the restore request. In case there are version incompatibilities in the global state file, or corruption issues, this prevents indices from being restored. We could instead simply not load the global state when it's not required for the restore process.

/cc: @elastic/es-distributed

**Comment by bleskes** [comment]
Seems logical to me. @tlrx , any opinions?

**Comment by tlrx** [comment]
> We could instead simply not load the global state when it's not required for the restore process.

It makes sense to me. I think that we can have the same issue when deleting a snapshot but I'm not sure we can avoid loading the global state in this case. I'll take a look.
