### ISSUE TITLE
Canvas Timelion datasource not returning results

### ISSUE THREAD

**Issue by boutcher** [elastic/elasticsearch#28947]
Running ES 6.2, installed latest Canvas, and I'm unable to get the timelion datasources working correctly. All data returned is 0. 

I loaded a few million documents into an index, timeseries data, for Feb 2018. I'm easily able to use this data directly in timelion with a simple query such as `.es(index=callrecord*,timefield=startDate)` with the time selector set to last 60 days. I get a nice line graph showing the count of my records.

In Canvas, I placed a time selector, set it to last 90 days, and then dropped in a data table. Modified the code to this, using the exact same timelion query:

`filters | timelion query=".es(index=callrecord*,timefield=startDate)" | table perPage=1000 | render`

What I end up with is a 3 column table @timestamp, value #, and label:

  2018-02-15T00:00:00-0800             0         q:* > count
  2018-02-15T12:00:00-0800              0         q:* > count
  ...

All the values are 0, when I'm quite sure they're not.

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch only. Please open a topic on the [forum](https://discuss.elastic.co) in the [Kibana category](https://discuss.elastic.co/c/kibana).
