### ISSUE TITLE
Ask the logstash output plug-in hosts configuration, which is the role of the connection cluster, master,data,client?

### ISSUE THREAD

**Issue by BigbigY** [elastic/elasticsearch#28958]

**Comment by BigbigY** [comment]
output {
        elasticsearch {
            user => "elastic"
            password => "password"
            hosts => [ "master01:9200","data01:9200","client01:9200"]
            index => "mysql-slow-query-%{+YYYY-MM-dd}"
        }
----
Master,data,client, or all nodes？

**Comment by jkakavas** [comment]
Hi @BigbigY, we reserve Github for bug reports and feature requests for open source Elasticsearch only. Please ask questions like these in the [Logstash forum](https://discuss.elastic.co/c/logstash) instead. Thank you!
