### ISSUE TITLE
Unable to get correct wildcard query results from ES in some cases.

### ISSUE THREAD

**Issue by shashanksinha1080** [elastic/elasticsearch#28955]
**Describe the feature**:
Elasticsearch wildcard query

**Elasticsearch version** (`bin/elasticsearch --version`):
1.6
**Plugins installed**: []

**JVM version** (`java -version`):
1.8
**OS version** (`uname -a` if on a Unix-like system):
Windows
**Description of the problem including expected versus actual behavior**:
trying to make wildcard search for a few terms results in inappropriate output.
eg. I search for "%cricket%" & "%cricket bat%", they provide me with correct result set, but on querying "%cricket bat set%", results I am getting is for wildcard around "%cricket" or "bat%". 

**Steps to reproduce**:
 I search for "%cricket%" & "%cricket bat%", they provide me with correct result set, but on querying "%cricket bat set%", results I am getting is for wildcard around "%cricket" or "bat%".** 

% denotes * (asterisk) over here.
Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

BTW your version is not supported anymore.

Thanks!
