### ISSUE TITLE
ClassCastException when loading SearchTemplateRequest from within a plugin

### ISSUE THREAD

**Issue by ngsoftwaredev** [elastic/elasticsearch#28964]
**Elasticsearch version** (`bin/elasticsearch --version`):

6.2.2

**Plugins installed**: []

**JVM version** (`java -version`):

1.8.0_161

**OS version** (`uname -a` if on a Unix-like system):

Linux Kirin 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

I have written an Elasticsearch plugin that provides custom search services for a customer. The core idea is to encapsulate the generation of an index template, several search templates and the search query itself in a custom plugin.

However when executing the search by using a *SearchTemplateRequest*, I get a *ClassCastException*:

`org.elasticsearch.script.mustache.SearchTemplateRequest cannot be cast to org.elasticsearch.script.mustache.SearchTemplateRequest`

The actual code triggering this exception is:

```java
        return new SearchTemplateRequestBuilder(client)
                .setScript("sample")
                .setScriptType(ScriptType.STORED)
                .setScriptParams(Collections.emptyMap())
                .setRequest(new SearchRequest())
                .get()
                .getResponse()
                .toString();`
```

This code is located in a class extending `org.elasticsearch.rest.BaseRestHandler`.

The expected behavior is, quite simply, that no exception is thrown.

Initially I thought I had a bad dependency in my classpath, but I use only official dependencies, namely here `org.elasticsearch.plugin:lang-mustache-client:6.2.2` provides the class `org.elasticsearch.script.mustache.SearchTemplateRequest`.

**Steps to reproduce**:

I have set up  a minimal implementation that reproduces the issue. There are only two small Java classes in the `fr.ngsoftwaredev.es` package: 

- `SamplePlugin` that declares an `ActionPlugin` with one endpoint
- `SampleAction` that extends `org.elasticsearch.rest.BaseRestHandler`

 1. Clone the repository at https://github.com/ngsoftwaredev/template-bug-report
 2. Build the plugin with `mvn -U clean install`
 3. Deploy the plugin on an Elasticsearch 6.2.2 node : `./elasticsearch-plugin install file:///path/to/template-bug-report/template-bug-report-plugin/target/releases/template-bug-report-plugin-6.2.2-0.1.0-SNAPSHOT.zip`
4. Start the node
5. Execute `curl -XGET http://localhost:9200/_sample`

**Provide logs (if relevant)**:

Please see attached log.txt file, which is Elasticsearch log.

[log.txt](https://github.com/elastic/elasticsearch/files/1797218/log.txt)

**Comment by jasontedor** [comment]
Your problem is that you are getting a `o.e.s.m.SearchTemplateRequest` from another classloader. In Java, the runtime type of an object is determined not only by the fully-qualified name, but also by the classloader. I do not consider this a bug and therefore I am closing this issue.
