### ISSUE TITLE
ES6.2.2 cannot initialize, allocate physical memory very slow

### ISSUE THREAD

**Issue by jinleileiking** [elastic/elasticsearch#28986]
**Describe the feature**:  

**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.2

**Plugins installed**: [no plugin]

**JVM version** (`java -version`): 1.8.0

**OS version** (`uname -a` if on a Unix-like system): inux tjwq01-ibu-video002158.tjwq01.ksyun.com 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 

500g mem. Total.  2 es (2.1.2) use 31 * 2 g mem

```
work@tjwq01-ibu-video002158.tjwq01.ksyun.com ~/es6_2/node1/elasticsearch-6.2.2]$ free -g                             │          27.43    0.00   13.06    0.75    0.00   58.76
             total       used       free     shared    buffers     cached                                             │
Mem:           504        121        382          0          0         35
```

**Description of the problem including expected versus actual behavior**: When start es. There will be one core to locate memory. My machine had 2 process already running (es 2.1.2 ) . When I ran the third es (6.2.2) . The es process allocate memroy very slowly ( when set xms = 21g, It cost 30min).

`When I comment jvm.options: `alwayspretouch` line.  It also cannot work well `

https://github.com/elastic/elasticsearch/issues/21300

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. hard to produce. I have 5 es machines. 3 allocating memory is fast. these 2 are slow. all the 5 nodes have 2 es already ran on them as data nodes(es 2.1.2)
 2.
 3.

**Provide logs (if relevant)**:

when try jstack es62 process. the es62 will core dump.

top:

![es](https://user-images.githubusercontent.com/93968/37270567-3f415cc2-260a-11e8-91ae-f79f6452be0b.png)

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
