### ISSUE TITLE
Script type inference fault when use Update(with script) Rest API

### ISSUE THREAD

**Issue by nezhazheng** [elastic/elasticsearch#28990]
**Elasticsearch version** 2.3.1 (affected almost all version. I tested 5.x 6.x)
**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_20

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
First of all we already have a doc mapping that include a long field. And we try to update the field with script like ctx._source.longField += longField.
expected:
2000000000 + 2000000000 = 4000000000
actual:
2000000000 + 2000000000 = -294967296

**Mapping snippet:**
{
          "longField": {
            "mapping": {
              "type": "long"
            },
            "match": "longField"
          }
 }

**Steps to reproduce**:
 1. Post a doc that include a long field that the length is int like below.
curl .../_update -d '{"script":{"inline":"ctx._source.longField += longField","params":{"longField":2000000000}},"upsert":{"id":"xxx","word":"a","longField":2000000000}}'

 2. Do above step again.

I think the root cause that is when do update es will convert the exists doc to map but with out mapping. The json library will inference the number type just based on the length of the number. 
Then the long field maybe lose it type.

**Comment by bleskes** [comment]
Thanks @nezhazheng . I can confirm this goes wrong in 6.2 . .Here's a full console repro

```
PUT test
{
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "doc": {
      "properties": {
        "longField": {
          "type": "long"
        }
      }
    }
  }
}


POST test/doc/1/_update
{
  "script": {
    "source": "ctx._source.longField += params.input",
    "params": {
      "input": 2000000000
    }
  },
  "upsert": {
    "longField": 2000000000
  }
}

```

**Comment by jdconrad** [comment]
Given how the JSON is parsed coming out of params, a workaround may be to do a cast to a long.  I don't know if that'll fix the problem for the actual update, though.

```ctx._source.longField += (long)params.input```

**Comment by nezhazheng** [comment]
@jdconrad Thank you. I tested your solution, it works. but a little tricky.:wink:

**Comment by jdconrad** [comment]
Closing this as the work around works for now.  Parsers are a different issue that should be discussed in the future.
