### ISSUE TITLE
Rest _search endpoint accepts invalid json body

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#28995]
This issue was first reported in https://github.com/elastic/elasticsearch/issues/28985.
Any text after the last closing bracket is simply ignored by the request json parser. So for instance a request like:
```
{
  "query": {
          "term": {
            "ProductID": "one"
          }
  }
},
"field_after_last_bracket": {
}
}
```
... is accepted.
I don't know why we have this leniency which is why I am opening this issue as a bug.

**Comment by nikhilbarar** [comment]
Is this issue accepted?

**Comment by nik9000** [comment]
> Is this issue accepted?

We consider it a real issue worth fixing, so, yeah.
