### ISSUE TITLE
Fail shard if IndexShard#storeStats runs into an IOException

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#29008]
If that happens something is totally wrong. We currently just bubble up the exception to the stats caller.

Relates to https://github.com/elastic/elasticsearch/issues/18279#issuecomment-218994716

**Comment by clintongormley** [comment]
@bleskes won't we keep trying to allocate shards to the emptiest mount point (ie the one with the failure?)

**Comment by bleskes** [comment]
@clintongormley we will first try another node. If we end up retrying the node we will probably use the same mount point indeed. If it fails immediately, we will only try 5 times and stop. If the failure is more subtle we will probably rinse repeat later. I agree this is not ideal but this is consistent with how we deal with other failures. I think what you mean is a bigger problem - tracking node/path health and avoiding assigning shards to it in general. That one is a way bigger fish.

**Comment by evanv** [comment]
Does https://github.com/elastic/elasticsearch/pull/16745 address 
> we should check if we can write on the datapath before we allocate
mentioned here https://github.com/elastic/elasticsearch/issues/18279#issuecomment-218994716? I don't think it does. That's just a node launch start up check. It's not really a path reachable check on allocation. 

Inre
> I think what you mean is a bigger problem - tracking node/path health and avoiding assigning shards to it in general. That one is a way bigger fish.

But isn't that exactly what https://github.com/elastic/elasticsearch/issues/18279 is about? I'm honestly unclear why you closed that ticket. Can you share your thinking a bit more and/or revisit https://github.com/elastic/elasticsearch/issues/18279 and leave it open as a known issue that's a high hanging fruit?

**Comment by milan15** [comment]
As a beginner, if no one is working on this i want to try and take this. I hope it would help me with increased understanding and give me commit/review process experience.

**Comment by milan15** [comment]
@bleskes in storeStats, added line to fail shard with message and passing IOException reference. let me know if anything is wrong/missing here.

**Comment by bleskes** [comment]
@evanv I responded on the other issue.

@milan15 the direction looks good. Can you open an PR and we can iterate there? I would love to have some testing but I wanted to first do some research to give you guidance. You'd need some kind of a mock directory implementation that throws exceptions. If you open a PR, I can offer help there if needed.

**Comment by milan15** [comment]
@bleskes i did it here #29078 . thanks for offering your help.
