### ISSUE TITLE
Reindex loosing the data....

### ISSUE THREAD

**Issue by pavangowdasu** [elastic/elasticsearch#29009]
Reindex API is not creating all the documents from source index to dest index, Response says it got updated some documents, but there were no documents exists to update, It was a newly created index, It has to create all the documents. can anyone help me understand whats wrong going on here?

{
"timed_out": false,
"noops": 0,
"total": 19575,
"failures": [],
"updated": 4821,
"deleted": 0,
"requests_per_second": -1.0,
"batches": 22,
"throttled_millis": 0,
"version_conflicts": 0,
"throttled_until_millis": 0,
"took": 88987,
"created": 14754,
"retries": {
"bulk": 0,
"search": 0
},
"slices": [
{
"slice_id": 0,
"noops": 0,
"total": 1947,
"updated": 236,
"deleted": 0,
"requests_per_second": -1.0,
"batches": 2,
"throttled_millis": 0,
"version_conflicts": 0,
"throttled_until_millis": 0,
"created": 1711,
"retries": {
"bulk": 0,
"search": 0
}
},
{
"slice_id": 1,
"noops": 0,
"total": 1942,
"updated": 188,
"deleted": 0,
"requests_per_second": -1.0,
"batches": 2,
"throttled_millis": 0,
"version_conflicts": 0,
"throttled_until_millis": 0,
"created": 1754,
"retries": {
"bulk": 0,
"search": 0
}
},
{
"slice_id": 2,
"noops": 0,
"total": 1938,
"updated": 241,
"deleted": 0,
"requests_per_second": -1.0,
"batches": 2,
"throttled_millis": 0,
"version_conflicts": 0,
"throttled_until_millis": 0,
"created": 1697,
"retries": {
"bulk": 0,
"search": 0
}
},
{
"slice_id": 3,
"noops": 0,
"total": 1918,
"updated": 339,
"deleted": 0,
"requests_per_second": -1.0,
"batches": 2,
"throttled_millis": 0,
"version_conflicts": 0,
"throttled_until_millis": 0,
"created": 1579,
"retries": {
"bulk": 0,
"search": 0
}
},
{
"slice_id": 4,
"noops": 0,
"total": 1960,
"updated": 173,
"deleted": 0,
"requests_per_second": -1.0,
"batches": 2,
"throttled_millis": 0,
"version_conflicts": 0,
"throttled_until_millis": 0,
"created": 1787,
"retries": {
"bulk": 0,
"search": 0
}
},
{
"slice_id": 5,
"noops": 0,
"total": 1965,
"updated": 747,
"deleted": 0,
"requests_per_second": -1.0,
"batches": 2,
"throttled_millis": 0,
"version_conflicts": 0,
"throttled_until_millis": 0,
"created": 1218,
"retries": {
"bulk": 0,
"search": 0
}
},
{
"slice_id": 6,
"noops": 0,
"total": 1912,
"updated": 720,
"deleted": 0,
"requests_per_second": -1.0,
"batches": 2,
"throttled_millis": 0,
"version_conflicts": 0,
"throttled_until_millis": 0,
"created": 1192,
"retries": {
"bulk": 0,
"search": 0
}
},
{
"slice_id": 7,
"noops": 0,
"total": 2010,
"updated": 733,
"deleted": 0,
"requests_per_second": -1.0,
"batches": 3,
"throttled_millis": 0,
"version_conflicts": 0,
"throttled_until_millis": 0,
"created": 1277,
"retries": {
"bulk": 0,
"search": 0
}
},
{
"slice_id": 8,
"noops": 0,
"total": 2029,
"updated": 641,
"deleted": 0,
"requests_per_second": -1.0,
"batches": 3,
"throttled_millis": 0,
"version_conflicts": 0,
"throttled_until_millis": 0,
"created": 1388,
"retries": {
"bulk": 0,
"search": 0
}
},
{
"slice_id": 9,
"noops": 0,
"total": 1954,
"updated": 803,
"deleted": 0,
"requests_per_second": -1.0,
"batches": 2,
"throttled_millis": 0,
"version_conflicts": 0,
"throttled_until_millis": 0,
"created": 1151,
"retries": {
"bulk": 0,
"search": 0
}
}
]
}

**Comment by jimczi** [comment]
@pavangowdasu can you give more informations regarding your setup. Which version of es, number of nodes, number of shards in the source index, number of documents in the source index, ... 
Can you also try without slicing (slices=1) and share the reindex request and response in this issue.

**Comment by pavangowdasu** [comment]
ES version: `5.1.1`
Number of nodes : `2 nodes with 1 tie breaker`
Number of shards : `5`
Number of documents : `700 K`

**Comment by pavangowdasu** [comment]
Reindex query was put down below:
```json
{
  "source": {
    "query": {
      "constant_score": {
        "filter": {
          "range": {
            "id": {
              "gte": 0,
              "lte": 25000
            }
          }
        }
      }
    },
    "_source": ["List of all source fields"],
    "index": "source-index-name"
  },
  "dest": {
    "index": "dest-index-name"
  }
}
```

Source index contains 700k documents i wanted to run reindexing by dividing documents list into 25k each time.

**Comment by pavangowdasu** [comment]
@jimczi I tried running the same reindexing query with `slice=1`, And its worked all documents got created. Thank you so much. 

(Earlier it was `slice=10`)

And still i could not understand how slice makes a difference here, can you help me understand how its worked this time?

**Comment by jimczi** [comment]
Thanks @pavangowdasu , slices in 5.1.1 have a bug when the number of nodes is greater than 1. You should upgrade to 5.latest (5.6.8) which should work fine with slices. Please reopen if upgrading does not fix this issue ;).
