### ISSUE TITLE
RankEval queries using aliases

### ISSUE THREAD

**Issue by paweloque** [elastic/elasticsearch#29011]
**RankEval and aliases**:
Currently it is only possible to run rank_eval queries using an index name. In many situations we use aliases to hide the indices and it would be great to be able to use an alias name to run rank_eval queries to test search results.

**Comment by cbuescher** [comment]
@paweloque thanks for opening this issue. I think this might not yet be working in 6.2 but I just checked in master and the soon-to-be-released 6.3 branch and alias resolution should work as expected there. However I should point out that in the `ratings` section of the request the documents are identified by their real index/id pair, not the index alias. I just added a few test to the master branch that should verify that aliases are working and will close this once those tests are merged.
