### ISSUE TITLE
ES Node leaving the cluster and freezing

### ISSUE THREAD

**Issue by DropCloth** [elastic/elasticsearch#29018]
Hello !

**Elasticsearch version** : 5.6.4

**JVM version** : 1.8.0_161

**OS version** : Linux elastic-node4 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: One of my ES nodes suddenly left the cluster and was unable to perform any action on the Elasticsearch service (stop/status/restart).

Since I upgraded the JVM version following your advices, everything was running well before this crash.

Only a forced reboot made the node join the cluster again.

**Provide logs (if relevant)**: 
Absolutely no logs from the ES side (except that the node left the cluster).
I have an interesting one from syslog tho:

Mar 12 15:44:53 elastic-node4 kernel: [8835413.121798] huge_memory: mapcount 0 page_mapcount 1
Mar 12 15:44:53 elastic-node4 kernel: [8835413.130427] ------------[ cut here ]------------
Mar 12 15:44:53 elastic-node4 kernel: [8835413.138808] kernel BUG at /build/linux-FmWmUC/linux-4.4.0/mm/huge_memory.c:1947!
Mar 12 15:44:53 elastic-node4 kernel: [8835413.156231] invalid opcode: 0000 [#1] SMP 
Mar 12 15:44:53 elastic-node4 kernel: [8835413.166068] Modules linked in: binfmt_misc intel_rapl ipmi_ssif x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel ipmi_si ipmi_msghandler kvm mei_me mei ioatdma input_leds joydev sb_edac edac_core lpc_ich 8250_fintek shpchp irqbypass mac_hid ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi autofs4 btrfs raid10 raid456 async_raid6_recov async_memcpy async_pq async_xor async_tx xor raid6_pq libcrc32c raid1 raid0 multipath linear mlx4_en vxlan ip6_udp_tunnel udp_tunnel hid_generic crct10dif_pclmul crc32_pclmul ghash_clmulni_intel igb aesni_intel isci aes_x86_64 dca lrw libsas usbhid gf128mul ptp glue_helper ahci ablk_helper pps_core cryptd hid libahci mlx4_core scsi_transport_sas i2c_algo_bit wmi fjes
Mar 12 15:44:53 elastic-node4 kernel: [8835413.267002] CPU: 19 PID: 188 Comm: kswapd0 Not tainted 4.4.0-101-generic #124-Ubuntu
Mar 12 15:44:53 elastic-node4 kernel: [8835413.287276] Hardware name: Supermicro X9DRT/X9DRT, BIOS 3.2 01/16/2015
Mar 12 15:44:53 elastic-node4 kernel: [8835413.297523] task: ffff88085b2ce200 ti: ffff881057164000 task.ti: ffff881057164000
Mar 12 15:44:53 elastic-node4 kernel: [8835413.318329] RIP: 0010:[<ffffffff811fb42f>] [<ffffffff811fb42f>] split_huge_page_to_list+0x74f/0x7a0
Mar 12 15:44:53 elastic-node4 kernel: [8835413.339417] RSP: 0018:ffff8810571679c0 EFLAGS: 00010282
Mar 12 15:44:53 elastic-node4 kernel: [8835413.350316] RAX: 0000000000000027 RBX: ffff88031ef7bb58 RCX: 0000000000000000
Mar 12 15:44:53 elastic-node4 kernel: [8835413.372035] RDX: 0000000000000000 RSI: ffff88085fccdd58 RDI: ffff88085fccdd58
Mar 12 15:44:53 elastic-node4 kernel: [8835413.393947] RBP: ffff881057167a50 R08: 0000000000000000 R09: 00000000000005ae
Mar 12 15:44:53 elastic-node4 kernel: [8835413.416217] R10: 0000000000000000 R11: 00000000000005ae R12: 0000000000000000
Mar 12 15:44:53 elastic-node4 kernel: [8835413.438800] R13: 00007fae6d000000 R14: ffffea0006db0000 R15: ffff880033e20800
Mar 12 15:44:53 elastic-node4 kernel: [8835413.461837] FS: 0000000000000000(0000) GS:ffff88085fcc0000(0000) knlGS:0000000000000000
Mar 12 15:44:53 elastic-node4 kernel: [8835413.485331] CS: 0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Mar 12 15:44:53 elastic-node4 kernel: [8835413.496851] CR2: 00000005c1b70004 CR3: 0000000001e0a000 CR4: 00000000000406e0
Mar 12 15:44:53 elastic-node4 kernel: [8835413.519989] Stack:
Mar 12 15:44:53 elastic-node4 kernel: [8835413.530866] ffffffff811d7d16 00000007fae6cffd 00007fae00000001 000000010005ad73
Mar 12 15:44:53 elastic-node4 kernel: [8835413.553232] ffff880490ffd5e0 ffff881057167c00 ffff880490ffd5a0 00007fae6d200000
Mar 12 15:44:53 elastic-node4 kernel: [8835413.575576] 00000007fae6d000 ffff880400000000 ffff881059257000 ffffea002d319330
Mar 12 15:44:53 elastic-node4 kernel: [8835413.597682] Call Trace:
Mar 12 15:44:53 elastic-node4 kernel: [8835413.609010] [<ffffffff811d7d16>] ? scan_swap_map+0x396/0x4e0
Mar 12 15:44:53 elastic-node4 kernel: [8835413.619969] [<ffffffff811d5844>] add_to_swap+0x74/0x80
Mar 12 15:44:53 elastic-node4 kernel: [8835413.630910] [<ffffffff811a5afd>] shrink_page_list+0x2dd/0x7a0
Mar 12 15:44:53 elastic-node4 kernel: [8835413.641266] [<ffffffff811a6659>] shrink_inactive_list+0x209/0x520
Mar 12 15:44:53 elastic-node4 kernel: [8835413.651901] [<ffffffff811a72e3>] shrink_lruvec+0x583/0x740
Mar 12 15:44:53 elastic-node4 kernel: [8835413.662022] [<ffffffff810bab6c>] ? set_next_entity+0x9c/0xb0
Mar 12 15:44:53 elastic-node4 kernel: [8835413.672700] [<ffffffff8111717c>] ? css_next_descendant_pre+0x4c/0x60
Mar 12 15:44:53 elastic-node4 kernel: [8835413.682938] [<ffffffff8111717c>] ? css_next_descendant_pre+0x4c/0x60
Mar 12 15:44:53 elastic-node4 kernel: [8835413.692303] [<ffffffff811a758f>] shrink_zone+0xef/0x2e0
Mar 12 15:44:53 elastic-node4 kernel: [8835413.701741] [<ffffffff811a87ee>] kswapd+0x51e/0x990
Mar 12 15:44:53 elastic-node4 kernel: [8835413.710927] [<ffffffff811a82d0>] ? mem_cgroup_shrink_node_zone+0x1c0/0x1c0
Mar 12 15:44:53 elastic-node4 kernel: [8835413.722026] [<ffffffff810a0c75>] kthread+0xe5/0x100
Mar 12 15:44:53 elastic-node4 kernel: [8835413.732893] [<ffffffff810a0b90>] ? kthread_create_on_node+0x1e0/0x1e0
Mar 12 15:44:53 elastic-node4 kernel: [8835413.743319] [<ffffffff81844b8f>] ret_from_fork+0x3f/0x70
Mar 12 15:44:53 elastic-node4 kernel: [8835413.753876] [<ffffffff810a0b90>] ? kthread_create_on_node+0x1e0/0x1e0
Mar 12 15:44:53 elastic-node4 kernel: [8835413.763891] Code: ff 3f 00 00 0f 85 fd fe ff ff 48 83 e1 fd e9 f4 fe ff ff 0f 0b 41 8b 56 18 8b 75 b8 48 c7 c7 78 67 cd 81 83 c2 01 e8 b8 2e f9 ff <0f> 0b 0f 0b 31 c0 eb a9 0f 0b 8b 55 98 39 55 8c 75 21 65 48 ff 
Mar 12 15:44:53 elastic-node4 kernel: [8835413.794410] RIP [<ffffffff811fb42f>] split_huge_page_to_list+0x74f/0x7a0
Mar 12 15:44:53 elastic-node4 kernel: [8835413.804678] RSP <ffff8810571679c0>
Mar 12 15:44:53 elastic-node4 kernel: [8835413.825294] ---[ end trace 55355dc3d9b38e4e ]---

**Comment by jasontedor** [comment]
> kernel BUG at /build/linux-FmWmUC/linux-4.4.0/mm/huge_memory.c:1947!

You should upgrade your kernel.
