### ISSUE TITLE
Documentation correction for putting Mapping

### ISSUE THREAD

**Issue by pschhikara88** [elastic/elasticsearch#29016]
This link (https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html) contains following information :

PUT twitter/_mapping/_doc

in the description , Uses the PUT mapping API to add a new mapping type called user.

if i am right, the url should be twitter/_mapping/user instead of twitter/_mapping/_doc

Thanks

**Comment by colings86** [comment]
@pschhikara88 I think the documentation is correct in this case. The documentation for 6.x has been updated reflecting the fact that we are removing the ability to have multiple doc types in a single index. In the future there will be no such thing as doc types when indexing documents or modifying mappings so we have updated the documentation to reflect the changes and have made the doc types `_doc` everywhere. So although the document in the referenced link represents a user, its doc_type is `_doc`.

/cc @jpountz @elastic/es-search-aggs

**Comment by pschhikara88** [comment]
Thanks @colings86 . Based on your response, i went through with this link https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html

This link is very helpful and explained everything. Thanks for your quick response. I am closing this issue.
