### ISSUE TITLE
"search_analyzer" disappear in mapping

### ISSUE THREAD

**Issue by VikoTse** [elastic/elasticsearch#29010]
Please check the following pictures.

![image](https://user-images.githubusercontent.com/5728396/37340322-b863bb56-26f8-11e8-8993-fcc09311eedc.png)

![image](https://user-images.githubusercontent.com/5728396/37340445-1a724506-26f9-11e8-96f4-a10e929bb373.png)

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

And don't paste images there but code only using the markdown format to format your code nicely.

BTW setting the same analyzer for both `analyzer` and `search_analyzer` is like setting only `analayzer`.

Thanks!
