### ISSUE TITLE
Do not cache profiled search requests

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#29024]
Today, profiled search requests are eligible for request caching, which can lead to some very confusing situations (fast `took` time but slow profile results because the results are being served by the cache).  Profiling should never really be cached at all because of the nature of profiling.

Related, `ProfileWeight` delegates `isCacheable()` to the wrapped query, but I wonder if we should perhaps return false to prevent the profiled query from affecting Lucene's caching statistics?

**Comment by iverase** [comment]
@polyfractal I have just opened an issue with the opposite case (slow `took`and fast profile) , the question is if profiling should use the cache at all?

**Comment by polyfractal** [comment]
Hiya @iverase, sorry for the delay.  

I may be missing the distinction between the two issues, but that was my intention with this one:  do not cache the profile response in the Elasticsearch query cache (to prevent results from being served from cache), and try to prevent Lucene from caching the query components by flagging the whole thing as not-cacheable.

I probably just explained myself poorly in the first post :)  I agree... we should prevent profiling from being affected by various caches as much as possible since it makes comparisons difficult.

**Comment by silbertmonaphia** [comment]
Is there any progress? get same issue(case 3) while profiling es query

**Comment by polyfractal** [comment]
Hi @silbertmonaphia, there is a (just-opened) PR that I believe will fix this issue: https://github.com/elastic/elasticsearch/pull/48195

**Comment by polyfractal** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/48195
