### ISSUE TITLE
Introduce dedicated threadpool for establishing connections

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#29023]
Today, we attempt to connect to nodes concurrently using the management threadpool:

https://github.com/elastic/elasticsearch/blob/46e16b68feaee112126df0ed2bcd7e78d12a4d57/server/src/main/java/org/elasticsearch/cluster/NodeConnectionsService.java#L94-L115

Connection establishment can be time-consuming if the remote node is unresponsive, and the management threadpool is small and important, so saturating it with attempts to connect to unresponsive nodes is undesirable.

The suggested fix is to create a separate threadpool purely for establishing node-to-node connections instead. As such connections are mostly long-lived the new-connection threadpool will mostly be idle, but after a network partition it would be good for each node to try and re-establish connections to its peers using a lot more concurrency than the management threadpool can support.

Relates #28920 in which cluster state application is blocked for multiple minutes because, in part, of insufficient concurrency when attempting to connect to unresponsive peers.

**Comment by danielmitterdorfer** [comment]
The work in https://github.com/elastic/elasticsearch/pull/35144 is an enabler to open connections asynchronously as an alternative to a dedicated threadpool. Therefore there is no need for a dedicated threadpool anymore and we might only introduce one should we run into unexpected issues with the async approach but for the time being I am closing this issue.
