### ISSUE TITLE
"message" element and Field Parsing

### ISSUE THREAD

**Issue by TamerDev** [elastic/elasticsearch#29037]
Hi,
I'm using Elastic 6.2.2 on windows with Fluentd td-agent v3.1.1,  I'm using the fluend plugin for elastic search, plugin version 1.0.2.

I have .Net program that writes the messages to Fluend td-agent, which then writes out the message to both a local file, and to Elastic. I have an issue with the message that gets written by the td-agent, it seems that the agent "injects" an element that is screwing up the parsing process when the message gets to Elastic. 
First, the .Net program message written is, this is before it reaches the fluentd td-agent:
{"ID":2940,"Action":"RunSomething","Date":"2018-03-13T17:53:58"}

the td-agent, read the message and here is what it writes out to the text file:
2018-03-13T17:53:58-04:00	my.logs	{"message":"{\"ID\":2940,\"Action\":\"RunSomething\",\"Date\":\"2018-03-13T17:53:58\"}"}

You can see, it added a timestamp, "my.logs" which is the tag, and then it enclosed my original json in  a "message" header which I do not need.
When checking for the Json that got inserted into Elastic, I get this from Kibana:

{
  "_index": "simple",
  "_type": "entry",
  "_id": "qKlZIWIBtckwupyAvCEL",
  "_version": 1,
  "_score": 2.330756,
  "_source": {
    "message": "{\"ID\":5074,\"Action\":\"RunSomething\",\"Date\":\"2018-03-13T17:52:29\"}"
  },
  "highlight": {
    "message": [
      "{\"ID\":5074,\"Action\":\"@kibana-highlighted-field@RunSomething@/kibana-highlighted-field@\",\"Date\":\"2018-03-13T17:52:29\"}"
    ]
  }
}

again, under _source, the "message" element is prefixing my json string. because of this I cannot parse the data inside.
I do not want to disable dynamic mapping because some new fields could show up in the future, I need to keep it dynamic. 
How can I remove this "message" that is prefixing all my documents?
Here is the full td-agent config:

&lt;source&gt;
  @type forward  #the most effecient parser from tcp, it cannot parse incoming messages
  port 24224
  bind 0.0.0.0 #from all addresses
&lt;/source&gt;

# Output
&lt;match my.logs&gt;
   @type copy
  &lt;store&gt;
    @type file
    path C:\opt\td-agent\etc\td-agent\manuallog.txt
  &lt;/store&gt;
  &lt;store&gt;
      @type elasticsearch
	  logstash_format false
	  host localhost
	  port 9200
	  index_name simple
	  type_name entry
	  &lt;buffer tag,time&gt;
		flush_mode interval
		retry_type exponential_backoff
		flush_interval 1
		timekey      1s # chunks per hours ("3600" also available)
		timekey_wait 1s
	  &lt;/buffer&gt;
  &lt;/store&gt;
&lt;/match&gt;

**Comment by colings86** [comment]
This seems to be a question about how to configure fluentd correctly for your use-case. As this is the issue tracker for the Elasticsearch project we do not have expertise in fluentd and I think you would be better asking your question to the fluentd community who would probably be in a better position to help (e.g. https://github.com/fluent/fluentd/issues or https://groups.google.com/forum/#!forum/fluentd)
