### ISSUE TITLE
Unable to serialize set with elasticsearch-py client

### ISSUE THREAD

**Issue by jaisharma639** [elastic/elasticsearch#29047]
ES : 2.4.1
Python: 2.7.9

When firing a terms filter query with a set instead of list throws SerializationError. Here is a sample query:

    {
    "query": {
        "filtered": {
            "filter": {
                "bool": {
                    "must": [
                        {
                            "term": {
                                "_type": "2017-08-28"
                            }
                        },
                        {
                            "terms": {
                                "field_name": {"0064000000pJH10"}
                        }
                    ]
                }
            }
        }
    } ,
    "size": 0
    }

Generally while using terms query to get documents matching multiple values, the array contains unique elements. That way it makes more sense to use a set instead of a list. 

My question is as to why elasticsearch can't type cast sets to list in such cases instead of trying to serialize and fail? Obviously this can be done on client side, but that requires implementing my own custom encoder to have the conversion.

**Comment by colings86** [comment]
Your query is missing a closing brace for the `terms` object, I think this is going to be what is causing the serialisation error

**Comment by jaisharma639** [comment]
I've updated my query, the brace must have gone off while formatting my question. This is not a syntax error, i've tried this in kibana and python client both. @colings86

**Comment by colings86** [comment]
Another issue I can see with your query is that this is not valid JSON:
```
"OpID": {"0064000000pJH10"}
```
JSON requires that objects are key-value pairs and does not have the concept of a set, an object that just contains a key is not valid. You need to use an array to specify the list of terms you want to match in your terms query.

**Comment by jaisharma639** [comment]
I understand that set is not json serializable,but that's my exact point. Why would someone like to store the variants of a field in a list instead of set (on client side)? While doing a terms query, i do not obviously care about the order of elements, neither i want to have redundant elements. So why is elasticsearch imposing a restriction of using lists wherever arrays are required? Is this a technical challenge which i'm not understanding?

**Comment by colings86** [comment]
Elasticsearch exposes a JSON API, therefore we support the data types that are set out in the JSON spec. If we add a set type to the API it would no longer be a JSON API and clients would not be able to use JSON parsing libraries like jackson to serialise and de-serialise requests and responses which would be bad for users. Additionally we would not be able to use the jackson library to serialise and deserialise requests and responses on the server which would significantly increase the complexity of our code.

**Comment by jaisharma639** [comment]
How about type casting such objects to json serializable objects before sending them to json parser? Each request and response goes through this layer on ES side before being parsed to json.

**Comment by colings86** [comment]
If you mean doing this casting/conversion in the python client then this might be doable but you would need to raise an issue on the [elasticsearch-py repository](https://github.com/elastic/elasticsearch-py/issues)

**Comment by jaisharma639** [comment]
Thanks @colings86 , i'll follow up in elasticsearch-py issues

**Comment by s-muzaffarbek** [comment]
![Uploading image_32466932_48_970x1182_3.jpg…]()

**Comment by s-muzaffarbek** [comment]
### hi
