### ISSUE TITLE
Updateability of search-time synonyms

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#29051]
We need a way to update synonyms that:
 - allows to change search-time synonyms without reopening
 - makes sure to not allow updating index-time synonyms, which could essentially corrupt the index

**Comment by byronvoorbach** [comment]
+1 

Myself, I solved this by creating a custom plugin that allows for uploading new synonyms. Not ideal but it works. Would be great if this could be built in! (Actually for all query-time resources: stopwords, common grams, etc..)

**Comment by Tobsucht** [comment]
+1

@byronvoorbach how do you do it without reopening the index? I'm also using search-time synonyms and I don't see a possibility to programmatically reload/flush my custom analyzer within my plugin or am I wrong?

**Comment by byronvoorbach** [comment]
@Tobsucht I have a custom implementation of the SynonymFilter, which allows me to update synonyms without closing/opening the index. :)

**Comment by Tobsucht** [comment]
@byronvoorbach I thought there might be a "cleaner" solution ... :) Did it the same way now and it works. For everybody who wants to implement this using the ResourceWatcherService, this might help: https://discuss.elastic.co/t/instance-of-resourcewatcherservice/130285

**Comment by byronvoorbach** [comment]
@Tobsucht yeah was hoping for that too.. Sadly, I couldn't use ResourceWatcherService because I had the requirement of posting a new version of synonyms to a new rest-endpoint in ES, instead of updating the local files on all nodes. Nice that you got it to work!

**Comment by byronvoorbach** [comment]
@jpountz

**Comment by byronvoorbach** [comment]
@jpountz Is this something planned for the near future? :)

**Comment by jpountz** [comment]
It has been discussed, but not scheduled yet.

**Comment by telendt** [comment]
@jpountz: Thanks for the update.

I know you folks have your priorities, but this feature has been brought up many times before. You can clearly see that there's a real need for this feature - just search in Github for [elasticsearch synonymmap](https://github.com/search?q=elasticsearch+synonymmap&type=Code) and look how many repositories with ES plugins are there (most of them really poor quality though).

Don't want to point fingers, but your biggest competitor seems to support this use case via [Managed Resources](https://lucene.apache.org/solr/guide/6_6/managed-resources.html#ManagedResources-Synonyms) (unless I'm misinterpret it).

I think it would be really cool if you could at least put it somewhere on your roadmap.

Cheers!

**Comment by cbuescher** [comment]
@jpountz do you think we can close this issue with #43313 coming up in the 7.3 release?

**Comment by jpountz** [comment]
+1
