### ISSUE TITLE
Deprecate word_delimiter tokenfilter in favour of word_delimiter_graph

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#29061]
WordDelimiterFilter is already deprecated in lucene, and can mess up offsets and highlighting (see #28474 and #3511)

**Comment by ebuildy** [comment]
For now, what about throwing a warning message, when using ``word_delimiter``  and ``preserve_original`` at index creation? this could help to prevent real error at index time later (hence in our case, save lot of time ...).

**Comment by cbuescher** [comment]
We have another issue (#37474) with a different approach here now, so I'm closing here.
