### ISSUE TITLE
Update search.asciidoc

### ISSUE THREAD

**Issue by qq253498229** [elastic/elasticsearch#29065]
[[java-search-terminate-after]]
=== Terminate After

The maximum number of documents to collect for each shard, upon reaching which the query execution will terminate early.
If set, you will be able to check if the operation terminated early by asking for `isTerminatedEarly()` in the
`SearchResponse` onject:

onject => object?

**Comment by jasontedor** [comment]
Closed by 56ee723859be3bad7cfb616080a7c8013f64682c
