### ISSUE TITLE
[CorruptStateException] Failed to read local state, exiting...

### ISSUE THREAD

**Issue by paulokuda** [elastic/elasticsearch#29072]
I've been using `elasticsearch@2.4`, but recently started using `elasticsearch@5.6` for another project. On my mac, I was able to upgrade to `5.6` without any issues; however, downgrading seems to be giving me troubles.

Any docs/tips on how to remove corrupted state files when downgrading 3 versions?

**Comment by jasontedor** [comment]
Sorry @paulokuda, downgrading is not possible once the on disk local state has been re-written in a new format on a higher version.
