### ISSUE TITLE
Composite aggregation doesn't allow filter aggregation

### ISSUE THREAD

**Issue by seanziee** [elastic/elasticsearch#29079]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.2

I'd like to define a filters under the composite aggregation but it seems not allowed. Why not? I could really use it!

Which aggregations are allowed under the composite agg?

```
GET */_search
{
  "size": 0,
  "aggs": {
    "data": {
      "composite": {
        "size": 100,
        "sources": [
          {
            "personname": {
              "terms": {
                "field": "personname.keyword"
              }
            }
          },
          {
            "test": {
              "filters": {
                "filters": {
                  "query": {
                    "query_string": {
                      "query": "all"
                    }
                  }
                }
              }
            }
          }
        ]
      }
    }
  }
}
```
Error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "parsing_exception",
        "reason": "invalid source type: filters",
        "line": 17,
        "col": 26
      }
    ],
    "type": "parsing_exception",
    "reason": "[composite] failed to parse field [sources]",
    "line": 17,
    "col": 26,
    "caused_by": {
      "type": "parsing_exception",
      "reason": "invalid source type: filters",
      "line": 17,
      "col": 26
    }
  },
  "status": 400
}
```

**Comment by colings86** [comment]
You can't add the `filters` aggregation as a `source` in the `composite` aggregation as it only accepts `term`, `histogram` and `date_histogram` sources. However you can have a `filters` aggregation as a sub-aggregation as below:
```
GET */_search
{
  "size": 0,
  "aggs": {
    "data": {
      "composite": {
        "size": 100,
        "sources": [
          {
            "personname": {
              "terms": {
                "field": "personname.keyword"
              }
            }
          }
        ]
      },
      "aggs": {
        "test": {
          "filters": {
            "filters": {
              "query": {
                "query_string": {
                  "query": "all"
                }
              }
            }
          }
        }
      }
    }
  }
}
```
This means that although the `filters` aggregation is not involved in selecting the "page" for the aggregation it will still be returned for every bucket of the `composite` aggregation.

Does this work for your use-case?

**Comment by colings86** [comment]
The difference is that the composite aggregation allows you to page through all the terms in personname.keyword whereas the terms aggregation would only provide the top N terms. 

What is it that you are hoping to get from having the filters aggregation in the sources section of the composite aggregation?

**Comment by seanziee** [comment]
I only put one filter in there but a real example there are a couple.. I'd like to do the pagation through all the terms with filters instead of categorizing by term. I can't get my aggregation from the field itself, I need to get to filtering by the value of the fields. 

I know this sounds nuts, but is there a way you can think of where I can do a composite agg but then limit my results only to the top 10 result sets. I need the data in the form of {person A: value1, filtera:value1}{personA:value2,filtera:value1} etc... but only the top results. This is a workaround I'm trying to create :)

**Comment by colings86** [comment]
>  is there a way you can think of where I can do a composite agg but then limit my results only to the top 10 result sets.

No, the intention of the composite agg is to provide a way to systematically page through all results. Inn order to get the top 10 results you would need to use the terms aggregation with a filters sub-aggregation. If you then need to flatten the response for use in your visualisation this flattening will need to be done client side.

**Comment by jimczi** [comment]
I agree with @colings86 if you need to flatten the top N results of an aggregation the `composite` aggregation is not the solution. You'll have to perform the flattening on the client side. 
I am going to close this issue because the `composite` aggregation can already have a `filter` aggregation as a `sub-aggregation` but the feature request described here is different and cannot be addressed with this aggregation.

**Comment by iukea1** [comment]
yo you guys should make it so you can exclude stuff with composite

**Comment by sdrilias** [comment]
i ran into this same need and figured out a way exclude stuff w/ composite.

requires 3 agg types:
- composite
- filter
- bucket_selector

the composite builds all the buckets, then the filter runs on these buckets. this results in a bucket array that looks like this:

```
{
  "buckets": [
    {
      "key": {
        "genericField1": "Biology",
        "genericField2": "38073"
      },
      "doc_count": 2,
      "filtered": {
        "doc_count": 2
      }
    }
  ]
}

```

then you can use the `bucket_selector` agg to exclude any buckets that have a doc_count of 0:

```
            "bucket_filter": {
              "bucket_selector": {
                "buckets_path": {
                  "filteredDocCount": "filtered>_count"
                },
                "script": "params.filteredDocCount > 0"
              }
            }
```

here it is all together:

```
{
  "aggs": {
    "nestedGeneric": {
      "nested": {
        "path": "genericPath"
      },
      "aggs": {
        "genericBuckets": {
          "composite": {
            "sources": [
              {
                "genericField1": {
                  "terms": {
                    "field": "genericPath.genericField1.raw",
                    "order": "asc"
                  }
                }
              },
              {
                "genericField2": {
                  "terms": {
                    "field": "genericPath.genericField2"
                  }
                }
              }
            ],
            "size": 50
          },
          "aggs": {
            "filtered": {
              "filter": {
                "bool": {
                  "filter": [
                    {
                      "term": {
                        "genericPath.genericFilterField": 1234
                      }
                    },
                    {
                      "match_phrase_prefix": {
                        "genericPath.genericField1": {
                          "query": "bio"
                        }
                      }
                    }
                  ]
                }
              }
            },
            "bucket_filter": {
              "bucket_selector": {
                "buckets_path": {
                  "filteredDocCount": "filtered>_count"
                },
                "script": "params.filteredDocCount > 0"
              }
            }
          }
        }
      }
    }
  }
}

```

end result is only buckets that match the filter defined after the composite agg are returned. they're paginated/sorted based on the defined composite field. unpaginated result set of like ~40k comes back in around 300ms, so the filter/bucket selector doesn't seem to hurt performance too bad. 

and of course, if you can filter the docs outside of the agg w/ a query, do that too. in my case i have to filter in both places b/c of how my data is nested.
