### ISSUE TITLE
Elasticsearch server analysis with SonarQube

### ISSUE THREAD

**Issue by MathiasMeuleman** [elastic/elasticsearch#29081]
I have been analyzing the Elasticsearch repo with use of SonarQube, and the following results emerged when running it on the server package:

![sonarqube-results](https://user-images.githubusercontent.com/9725373/37452781-e415a0fa-2835-11e8-90a3-65b04ad9d05c.png)

Analyzing the different issues and code smells that are presented, a large number of them are explainable with the choices that are made. However, there are also a number of them that can be easily fixed and don't seem to require a lot of overhead from integrators (just to give an example: there are 237 instances of unused imports). Me (and a few colleagues) wouldn't mind spending some time on this, but first we would like to see whether there is any interest in these fixes from your side. If so, if you have any specific issues in this category that you are aware of and would like us to focus on, please let us know.

**Comment by jpountz** [comment]
Is there a link where we can know more about the details? In general we'd be happy to fix whatever might end up being a problem to users. Things like unused imports need more discussion: removing them might help a bit with readability or naming collisions but it will also be one more entry in the history of many files and might introduce conflicts in a number of PRs. If we do that, we might need to have a related discussion about failing the build on unused imports so that we don't have to repeat this operation on a regular basis, etc.

**Comment by MathiasMeuleman** [comment]
It is interesting you mention you would be happy to fix whatever might be a problem to _users_, but what would you happy to fix that might be a problem to _developers_? Removing unused imports was just an example, but probably one of the easier fixable issues here. Setting constraints like failing builds on violations is a way to solve it, but probably it would be easier to enforce these rules as much as possible in the PRs that come along. About that link... the community version of SonarQube doesn't seem to support result sharing (as far as I can see), so that is not really possible at this moment. I can however provide you with an overload of screenshots, if you so desire.

**Comment by jasontedor** [comment]
> Setting constraints like failing builds on violations is a way to solve it, but probably it would be easier to enforce these rules as much as possible in the PRs that come along.

These get missed without automation that enforces them which entails exactly failing the build.

**Comment by nik9000** [comment]
I think if we really care about something like unused imports we should have checkstyle fail the build if we have any. To be honest, I'd be happy with that change in particular.

Other things get more complicated. We *have* checkstyle so if we can enforce stuff with checkstyle I'd prefer that to bringing in some other scanning tools.

**Comment by nik9000** [comment]
> I think if we really care about something like unused imports we should have checkstyle fail the build if we have any. To be honest, I'd be happy with that change in particular.

I had a talk with some folks and we all were of the opinion that unused imports were bad but not really a big deal. We're not willing to fail the build if we have them, at least not at this point.

As far as other SonarQube things, if you have individual PRs to open we'd be happy to review them. It'd be nice to know what Sonar's check is that identified the issue and we can decide if it is the kind of check we'd like to just fix, fix and forbid with checkstyle, or totally ignore.

**Comment by olcbean** [comment]
Browsing around I found a rather recent ES analysis at : https://sonarcloud.io/dashboard?id=elasticsearch_180410

As a side note : I am not sure that checkstyle can warn about *possible* resource leaks or *possible* division by zero ;)
