### ISSUE TITLE
Build failed - problem with Java version

### ISSUE THREAD

**Issue by Mikilll94** [elastic/elasticsearch#29099]
When I am running ./gradlew assemble, I've got:

```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\wasni\Desktop\elasticsearch-master\benchmarks\build.gradle' line: 31

* What went wrong:
A problem occurred evaluating project ':benchmarks'.
> Failed to apply plugin [id 'elasticsearch.build']
   > Java 1.9 or above is required to build Elasticsearch

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.5/userguide/command_line_interface.html#sec:command_line_warnings
```

**JVM version** (`java -version`):

java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Windows 10

**Description of the problem including expected versus actual behavior**:

I got this error also when I had installed Java 1.8. Then I installed Java 9 but this had no impact. The same error happens.

**Comment by jasontedor** [comment]
You need to set `JAVA_HOME` to point to your JDK 9 installation.

**Comment by jasontedor** [comment]
I opened #29101 which I hope is an improvement on the message here so that developers are less confused in the future.
