### ISSUE TITLE
Update the type of the field

### ISSUE THREAD

**Issue by strong666** [elastic/elasticsearch#29104]
I used the head plugin to update the type of the index field, but it never successful.

 
![1521170940 1](https://user-images.githubusercontent.com/26668306/37502405-8318d1ea-290d-11e8-8be9-5ec3dbcccbae.png)
![1521171045 1](https://user-images.githubusercontent.com/26668306/37502406-83420d9e-290d-11e8-8a3f-95800a3b67ea.png)

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

In general, you can't update a data type and you need to reindex.
