### ISSUE TITLE
[CI] DieWithDignityIT testDieWithDignity fails on master and 6.x

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#29136]
This seems to be failing once in a while since at least March 14th:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1373/console

Recently on master:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1394/console

I cannot reproduce it locally so far:
```
gradlew :qa:die-with-dignity:integTestRunner \
  -Dtests.seed=CC001A3DE4EBA57E \
  -Dtests.class=org.elasticsearch.qa.die_with_dignity.DieWithDignityIT \
  -Dtests.method="testDieWithDignity" \
  -Dtests.security.manager=false \
  -Dtests.locale=sr-Latn-BA \
  -Dtests.timezone=AGT
```

Failures look like this:
```
12:51:42 FAILURE 0.98s | DieWithDignityIT.testDieWithDignity <<< FAILURES!
12:51:42    > Throwable #1: junit.framework.AssertionFailedError: Unexpected exception type, expected ConnectionClosedException but got java.io.IOException: An existing connection was forcibly closed by the remote host
12:51:42    > 	at __randomizedtesting.SeedInfo.seed([CC001A3DE4EBA57E:C5CBCC2732703765]:0)
12:51:42    > 	at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2668)
12:51:42    > 	at org.elasticsearch.qa.die_with_dignity.DieWithDignityIT.testDieWithDignity(DieWithDignityIT.java:51)
12:51:42   2> NOTE: leaving temporary files on disk at: C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\qa\die-with-dignity\build\testrun\integTestRunner\J0\temp\org.elasticsearch.qa.die_with_dignity.DieWithDignityIT_CC001A3DE4EBA57E-001
12:51:42    > 	at java.lang.Thread.run(Thread.java:748)
12:51:42 
```

**Comment by nik9000** [comment]
@cbuescher did you notice if all the failures were on Windows?

**Comment by cbuescher** [comment]
@nik9000 you are right, they are. Didn't notice this until now.

**Comment by nik9000** [comment]
Neat! I'll take this one.

**Comment by cbuescher** [comment]
Quick search shows 14 similar looking failures since 14th or march, all on windows.

**Comment by nik9000** [comment]
I did a little digging. It looks like this is caused when the other side closes its connection while we're waiting on our buffer to fill up. We totally expect that in this test. It feels to me like we should throw a `ConnectionClosedException` but upstream does not agree:
https://issues.apache.org/jira/browse/HTTPASYNC-134

So I'm going to catch this exception and "expected".

Alternatively we could translate on our side but that seems like a bigger change to make so I'd like to propose the simpler fix first.
