### ISSUE TITLE
location geo_point

### ISSUE THREAD

**Issue by strong666** [elastic/elasticsearch#29132]
My field has a geo_point type, and when I insert the data, 111.9168341,37.0269508, can't be inserted, but changed to 40.715, -74.011, which is a new success.
![1521441788 1](https://user-images.githubusercontent.com/26668306/37581505-e0c37ca0-2b83-11e8-8238-e937ef43e02c.png)

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

And there, just copy code but not images please.
