### ISSUE TITLE
elasticsearch is not running

### ISSUE THREAD

**Issue by prahlad574** [elastic/elasticsearch#29131]
root@:/# service elasticsearch start
 * Starting Elasticsearch Server                                                                                                                                 [ OK ]
root@:/# service elasticsearch status
 * elasticsearch is not running
this is the issue i am facing. earlier port 9200 is to be in close wait state. i thought closing it forcely will resolve my issue. But, it did not solve my issue.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
