### ISSUE TITLE
elasticsearch 6.2.1 Docker crash

### ISSUE THREAD

**Issue by bolivia** [elastic/elasticsearch#29145]
Hi,

my Docker Conainer with elasticsearch 6.2.1 does not start anymore.

**Elasticsearch Version** 6.2.1

**plugins**
aggs-matrix-stats
analysis-common
ingest-common
long-expression
long-mustache
long-painless
mapper-extras
parent-join
percolator
rank-eval
reindex
repository-url
transport-netty4
tribe
ingest-geoip
ingest-user-agent

**Java** 8 Updated 161

**OS** Windows 10 1709 16299.309

**Description:**

> 
> elasticsearch_1  | [2018-03-19T20:06:29,680][INFO ][o.e.n.Node               ] node name [RP_BSlX] derived from node ID [RP_BSlX2SP-9zgwdGT7yXg]; set [node.name] to override
> elasticsearch_1  | [2018-03-19T20:06:29,681][INFO ][o.e.n.Node               ] version[6.2.1], pid[1], build[7299dc3/2018-02-07T19:34:26.990113Z], OS[Linux/4.9.60-linuxkit-aufs/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_161/25.161-b14]
> elasticsearch_1  | [2018-03-19T20:06:29,681][INFO ][o.e.n.Node               ] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.QtEC3tYE, -XX:+HeapDumpOnOutOfMemoryError, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Des.cgroups.hierarchy.override=/, -Xmx256m, -Xms256m, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config]
> elasticsearch_1  | [2018-03-19T20:06:30,779][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded module [aggs-matrix-stats]
> elasticsearch_1  | [2018-03-19T20:06:30,780][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded module [analysis-common]
> elasticsearch_1  | [2018-03-19T20:06:30,781][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded module [ingest-common]
> elasticsearch_1  | [2018-03-19T20:06:30,781][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded module [lang-expression]
> elasticsearch_1  | [2018-03-19T20:06:30,781][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded module [lang-mustache]
> elasticsearch_1  | [2018-03-19T20:06:30,781][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded module [lang-painless]
> elasticsearch_1  | [2018-03-19T20:06:30,782][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded module [mapper-extras]
> elasticsearch_1  | [2018-03-19T20:06:30,782][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded module [parent-join]
> elasticsearch_1  | [2018-03-19T20:06:30,782][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded module [percolator]
> elasticsearch_1  | [2018-03-19T20:06:30,782][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded module [rank-eval]
> elasticsearch_1  | [2018-03-19T20:06:30,783][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded module [reindex]
> elasticsearch_1  | [2018-03-19T20:06:30,783][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded module [repository-url]
> elasticsearch_1  | [2018-03-19T20:06:30,783][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded module [transport-netty4]
> elasticsearch_1  | [2018-03-19T20:06:30,783][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded module [tribe]
> elasticsearch_1  | [2018-03-19T20:06:30,784][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded plugin [ingest-geoip]
> elasticsearch_1  | [2018-03-19T20:06:30,784][INFO ][o.e.p.PluginsService     ] [RP_BSlX] loaded plugin [ingest-user-agent]
> kibana_1         | {"type":"log","@timestamp":"2018-03-19T20:06:30Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
> kibana_1         | {"type":"log","@timestamp":"2018-03-19T20:06:30Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
> elasticsearch_1  | [2018-03-19T20:06:33,135][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
> elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: **Failed to parse value [fals] as only [true] or [false] are allowed.**
> elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  | Caused by: java.lang.IllegalArgumentException: Failed to parse value [fals] as only [true] or [false] are allowed.
> elasticsearch_1  |      at org.elasticsearch.common.Booleans.parseBoolean(Booleans.java:73) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.common.settings.Setting.get(Setting.java:347) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.common.settings.Setting.get(Setting.java:341) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:362) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:310) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:284) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:134) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:331) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.1.jar:6.2.1]
> elasticsearch_1  |      ... 6 more
> kibana_1         | {"type":"log","@timestamp":"2018-03-19T20:06:33Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"Unable to revive connection: http://elasticsearch:9200/"}
> kibana_1         | {"type":"log","@timestamp":"2018-03-19T20:06:33Z","tags":["warning","elasticsearch","admin"],"pid":1,"message":"No living connections"}
> dockerelkmaster_elasticsearch_1 exited with code 1

I'm grateful for any support.

Thanks.

**Comment by dadoonet** [comment]
Did you change some settings ?

> Failed to parse value [fals] as only [true] or [false] are allowed.

**Comment by jasontedor** [comment]
You have tried to set something to `fals` but that is not a value that we parse for booleans.

```
elasticsearch_1 | Caused by: java.lang.IllegalArgumentException: Failed to parse value [fals] as only [true] or [false] are allowed.
```

**Comment by bolivia** [comment]
Of course I noticed the error message, but I did not change anything.

Where could I look?

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. If you post there, someone will try to help you. I should remark though, you should provide a full reproduction for this, something that another member of the community can run on their machine that reproduces the issue exactly. You have not done that here (you haven't told us what Docker image you're using, how you're customizing that image, etc., and you haven't told us what command you're running to start the container; these are table stakes for an effective bug report in terms of being able to get you meaningful help quickly). Maybe in the course of writing up the reproduction, you will find where you have entered `fals` instead of `false`.
