### ISSUE TITLE
Confusing documentation on Query String Query on the split by whitespace behaviour

### ISSUE THREAD

**Issue by WydD** [elastic/elasticsearch#29148]
**Elasticsearch version**: 6.2.2 (but all 6.x is affected)

Hi everyone,

In the reference documentation for Query String Queries https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-query-string-query.html it is said the following

> Whitespaces are not considered operators, this means that new york city will be passed "as is" to the analyzer configured for the field. If the field is a keyword field the analyzer will create a single term new york city and the query builder will use this term in the query. If you want to query each term separately you need to add explicit operators around the terms (e.g. new AND york AND city).

And right after this, we can find the documentation of the default_operator parameter:

> The default operator used if no explicit operator is specified. For example, with a default operator of OR, the query capital of Hungary is translated to capital OR of OR Hungary, and with default operator of AND, the same query is translated to capital AND of AND Hungary. The default value is OR.

Because the split by whitespace is not available anymore directly (see https://github.com/elastic/elasticsearch/issues/25574), only queries with explicit separations like `(new) (york) (city)` would be indeed parsed as `new AND york AND city` (with default_operator=AND) but not `new york city` which would be sent as one query to the target analyzer(s). The documentation is confusing on that regard.

I'm not sure of the exact implications here but it broke one of our multi field (multi analyzer) unit test when we tried to migrate as is the query string we did.

**Comment by DaveCTurner** [comment]
Pinging @elastic/es-search-aggs

**Comment by jimczi** [comment]
> Because the split by whitespace is not available anymore directly (see #25574), only queries with explicit separations like (new) (york) (city) would be indeed parsed as new AND york AND city (with default_operator=AND) but not new york city which would be sent as one query to the target analyzer(s). The documentation is confusing on that regard.

That's not correct. The `query_string` first splits on operators and then pass each split to the analyzer of the targeted fields. The fact that whitespaces are not considered operator anymore does not change the behavior of the `default_operator`. The query `new york city` for instance is considered as one block of text and is passed "as is" to the analyzers but then the analysis will split this text into tokens and applies the `default_operator` to combine them. With the `standard` analyzer and a `default_operator` set to to `OR` the generated query is: `new OR york OR city`. What changed is if you have multiple fields defined in the `fields` parameter. Suppose you want to apply this query to the fields `title` and `text`,  by default the `query_string` will first apply the analysis on the field `title` and build the query `title:(new OR york OR city)` and then it will combine this query with the `text` field: `title:(new OR york OR city) OR text:(new OR york OR city)`. If you change the `default_operator` to `AND` the query would be: `title:(new AND york AND city) OR text:(new AND york AND city)`. This means that a document will match if it contains `new AND york AND city` in one of the targeted fields. 
Before 6.x the query is translated into `(title:new OR text:new) AND (title:york OR title:york)...`. 
This is the gist of the change, though the split on whitespace was artificial since it was done outside of the analysis so if the `title` field for instance has a `shingle` filter the `query_string` before 6.x is not able to build these shingles and would always build single term since it splits on whitespace prior to the real analysis. 
If you want to restore the old behavior, you can add explicit operator (new AND york AND city) where each term would be considered as a split or if you use the same analyzer for each targeted field you can use the `type:cross_fields` option that will apply the `cross_fields` rewrite on each token created by the analyzer:
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-multi-match-query.html#multi-match-types
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-multi-match-query.html#type-cross-fields

**Comment by ShwethaThakur** [comment]
Hey! I am using query string query function in elasticsearch. If I query something like this query="canada chest" with default operator = "and" and analyzer = "keyword", then returns documents in which canada and chest both are present . But I want the documents in which canada chest is considered as a single term and then output is returned. How do I achieve this?

**Comment by mayya-sharipova** [comment]
@ShwethaThakur  please ask your use case questions in https://discuss.elastic.co/.  Github is only for filing bugs or requests for new features. 
But in short to answer your question here - you either need 1) to have keyword field, or 2) make a phrase from your query  using double quotes inside a query string query or 3) use match phrase query.

**Comment by ShwethaThakur** [comment]
I will raise a query there as well.
1) I have to use keyword field while declaring the mappings?
2)I have tried it. But doesn't work. It splits the word and gives the
result.
3)I cannot use AND and OR operations in match phrase query.

Thank you.

**Comment by LordMike** [comment]
@jimczi we just hit this as well, and I wanted to confirm one thing - sorry for reviving an old issue. Your great explanation helped me understand what was up, and I think there is still a use case that is not covered. In our use case, we've set the default operator to "and", as we want _all_ of our users terms/inputs to be found in the documents, unless they specify f.ex. "OR".

I've discovered that the behavior you mentioned seems to differ if one of the fields is a `keyword` field, versus `text` fields. I've performed some tests below in 8.5.3. We're running 7.17, but I went with the newest to rule out stuff.

<details>
<summary>ES 8.5.3, index w/ keyword+text</summary>

```
# Create index w/ keyword & text property, both with respective Whitespace search analysis
PUT http://localhost:9208/test_index
{
    "mappings": {
            "properties": {
                "title": {
                    "type": "keyword",
                    "split_queries_on_whitespace": true
                },
                "text": {
                    "type": "text",
                    "search_analyzer": "whitespace"
                }
            }
    }
}

# Insert document
POST http://localhost:9208/test_index/_doc/1
{
	"title": "york",
	"text": "sigma bellum"
}

# Explain query, I use a bool/filter to avoid scoring logic
# With this query, "york sigma", I expect to match my doc, as the default operator is "AND" and all inputs are analyzed with whitespaces.
GET http://localhost:9208/test_index/_explain/1
{
    "query": {
        "bool": {
            "filter": [{
                    "query_string": {
                        "default_operator": "and",
                        "fields": [
                            "title", "text"
                        ],
                        "lenient": true,
                        "query": "york sigma",
                        "type": "cross_fields"
                    }
                }
            ]
        }
    }
}


{"_index":"test_index","_id":"1","matched":false,"explanation":{"value":0.0,"description":"ConstantScore(((+title:york +title:sigma) | (+text:york +text:sigma))) doesn't match id 0","details":[]}}
```
</details>

What we get is `((+title:york +title:sigma) | (+text:york +text:sigma))`. So my original query `york sigma` was turned into `title:(york AND sigma) OR text:(york AND sigma)`. 

Then, if we query two text fields instead:

<details>
<summary>ES 8.5.3, index w/ text+text</summary>

```
# Create with two text fields
PUT http://localhost:9208/test_index2
{
    "mappings": {
            "properties": {
                "title": {
                    "type": "text",
                    "search_analyzer": "whitespace"
                },
                "text": {
                    "type": "text",
                    "search_analyzer": "whitespace"
                }
            }
    }
}

# Add the same doc
POST http://localhost:9208/test_index2/_doc/1
{
	"title": "york",
	"text": "sigma bellum"
}

# Do the same query
GET http://localhost:9208/test_index2/_explain/1
{
    "query": {
        "bool": {
            "filter": [{
                    "query_string": {
                        "default_operator": "and",
                        "fields": [
                            "title", "text"
                        ],
                        "lenient": true,
                        "query": "york sigma",
                        "type": "cross_fields"
                    }
                }
            ]
        }
    }
}

{"_index":"test_index2","_id":"1","matched":true,"explanation":{"value":0.0,"description":"ConstantScore(#(text:york | title:york) #(title:sigma | text:sigma))^0.0","details":[]}}
```
</details>

I get the following from my query: `text:(york OR sigma) AND(?) title:(york OR sigma)`. (I'm unsure what hashtag is, but it behaves like a `+`)

That is, the `default_operator` seems to apply to each field here, if one of the fields is a `keyword`, while it applies to each token/term if both fields are `text`. The behavior I'd like is the latter, such that users can continue writing "york sigma" and match documents where _both_ those terms are present in any of the fields specified (that the application chooses).

I suspect that one of the consequences of changing the `split_on_whitespace` is that "york sigma" was previously passed down as "york AND sigma" (two clauses) while it now (post-6.0) is passed down as "(york sigma)" (one clause), and that the default operator now then only can apply in some other place than it used to.

If there's nothing to do here - all other issues are closed as "by-design", then we'll just move on as it is now and instruct users to use AND/OR explicitly. :)

**Comment by akotlar** [comment]
I find this behavior very inconsistent. Here are a few queries and the outcomes. Here "exonic" is a term that exists in one field, "pathogenic" in another field, "chr17" in a third, and some documents have a field, cadd with values above 20.

exonic pathogenic
- no matches

exonic  && pathogenic
 - matches
 
 exonic cadd:>20 pathogenic
 - matches, apparently reverting to "&&" behavior
 
exonic pathogenic cadd > 20
- no match

exonic cadd:>20 pathogenic chr17
- no match, so now order matters

exonic && cadd:>20 pathogenic chr17
- no match

exonic && cadd:> 20 && pathogenic chr17
- matches, despite "pathogenic chr17" not existing in any field
- also works: exonic && cadd:> 20 +pathogenic chr17 
- also works: exonic +cadd:> 20 +pathogenic chr17
- also works: exonic +cadd:> 20 +pathogenic +chr17

Previously, in <6, I could rely on query order not mattering, and understanding that if the user wanted the full term to be considered they could use quotes. Now the behavior requires some nuanced care.

How are others dealing with this?
