### ISSUE TITLE
MLT bug when source disabled?

### ISSUE THREAD

**Issue by rlvoyer** [elastic/elasticsearch#2914]
I'm trying to use the more_like_this handler in almost the exact same way it's used in the documentation here:

http://www.elasticsearch.org/guide/reference/api/more-like-this/

curl -XGET "http://localhost:9200/foo/document/1008534/_mlt?mlt_fields=cs,ks,tpcs&min_doc_freq=2"

{"error":"ElasticSearchException[No fields found to fetch the 'likeText' from]","status":500}

I'm guessing this bug stems from the fact that source is disabled, but I'm not really sure. If it is the case that source is required for MLT, you should document that fact.

**Comment by alexksikes** [comment]
This issue is now outdated, closing.
