### ISSUE TITLE
Improve documentation on Windows SSL / TLS ES 6.X / setup

### ISSUE THREAD

**Issue by jkelastic** [elastic/elasticsearch#29170]
**Elasticsearch version** ES 6.X

**OS version** Windows Server 2012 R2 / Windows Server 2016

**Description of the problem including expected versus actual behavior**:

There seem to be a lack of / lack of details on Windows SSL / TLS setup documentation. For Windows / Linux some notes to add to the current setup doc link below would be

https://www.elastic.co/guide/en/elasticsearch/reference/6.2/configuring-tls.html#node-certificates

For example:

The slashes to use - though the documentation are mostly correct - some sections of LS\ES\Kibana require the use of forward slashes in some locations (I've gotten in the habit of trying multiple combinations before requesting help - one forward slash, one backward, two forward, two backward, etc.)

network.host must match the DNS name in the configuration file used to generate certificates - also the DNS name must the short server name (not necessarily the FQDN which resolves file, but certs don't like it).

If we can have full examples for Windows with step by step instructions that would be great and if SSL / TLS can be taken care of within the is the msi that would awesome.

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch only yet the docs referenced here are for X-Pack.
