### ISSUE TITLE
missing git release tag 6.2.3

### ISSUE THREAD

**Issue by anthraxx** [elastic/elasticsearch#29178]
Apperantly the git tag for 6.2.3 is missing (as announced downloadable on the website).

It would be gorgeos to keep that in sync, i believe a simple push was forgotten :cat: 

cheers

**Comment by jasontedor** [comment]
Thanks for noticing, thanks for opening an issue, we are sorry for the delay and are on it.

**Comment by hub-cap** [comment]
https://github.com/elastic/elasticsearch/tree/v6.2.3

tyvm for the submission!

**Comment by anthraxx** [comment]
no worries, thanks a lot for the fast response, handling and appreciation. awesome
