### ISSUE TITLE
Sorting based on parent/child relationship

### ISSUE THREAD

**Issue by kul** [elastic/elasticsearch#2917]
Currently there is no way to sort documents based on parent child relation. E.g.
Sorting a doc based on child doc field or the opposite.

**Comment by pauleil** [comment]
Are there any plans to support this feature in the foreseeable future?

**Comment by martijnvg** [comment]
Once the refactoring in #8134 is in, this is planned to be added. Like with the current refactoring the sorting by child or parent field should be added to the new Lucene query time join first.

**Comment by pauleil** [comment]
This is very exciting. Is there a plan of integrating this in an upcoming release, now that #8134 is solved?

**Comment by vinusebastian** [comment]
@kul @martijnvg @clintongormley How do I do the workaround mentioned in http://stackoverflow.com/questions/14504180/elasticsearch-sorting-by-nested-documents-values/14519947#14519947 for a parent child relationship? In my script field what should replace "doc['locations.order'].value" to refer to the child document's field?

Thanks in advance

**Comment by archie-sh** [comment]
would really like to see this implemented

**Comment by clintongormley** [comment]
@martijnvg With #8134 in, do you see a way forward for implementing this?

**Comment by martijnvg** [comment]
@clintongormley Yes, I do see a way how this can be implemented. Similar to how the join is implemented, but instead of aggregating child scores per parent the sorting should aggregate sort values instead.

**Comment by jaimemarijke** [comment]
@martijnvg - Do you have an idea on when this might be implemented? I am curious because this is a blocking issue for me for using parent/child relationships, which I would otherwise much prefer over nested documents.

**Comment by martijnvg** [comment]
@jaimemarijke No, there is no effort being done yet to get this feature in.

**Comment by christian-m** [comment]
> **martijnvg** commented on 19 Apr 2013
> @kul At the moment this isn't possible. This feature will be added *in the near future.*

@martijnvg so, what means *in the near future*?

**Comment by padusumilli** [comment]
+1

**Comment by sundarv85** [comment]
+1

**Comment by mrkamel** [comment]
+1

**Comment by ecdeveloper** [comment]
+1

**Comment by dohly** [comment]
+1

**Comment by ecdeveloper** [comment]
[This link at SO](http://stackoverflow.com/questions/10415494/elasticsearch-sort-by-single-nested-document-key-in-array) actually helped me achieving what we need.

**Comment by alkampfergit** [comment]
+1

**Comment by jernejc** [comment]
+1

**Comment by lonre** [comment]
+1

**Comment by robinloxley1** [comment]
In my case, I don't need to wait for the the issue to be solved. Follow the workaround in 2013, something can be done as follows.

`
"query": {
        "has_child": {
          "query": {
            "function_score": {
              "functions": [
                {
                  "field_value_factor": {
                    "factor": 1,
                    "field": "count"
                  }
                }
              ]
            }
          },
          "score_mode": "avg", 
          "type": "my_child_doc_type"
        }

`

**Comment by haizhou** [comment]
@robinloxley1 in your case, did you see the `_score` field on the parent doc from the response reflecting the actual `count` field value in your child doc? I tested the query, and got a response back but the scores don't really reflect what I tried to score on. I'm on 1.6 though.

**Comment by anfomin** [comment]
It will work only on single field but if it's required to sort by 2 fields...

**Comment by twest72** [comment]
+1

**Comment by lucioalmeida** [comment]
+1

**Comment by hajnalben** [comment]
+1

**Comment by vharitonsky** [comment]
+1

**Comment by sjwaller** [comment]
+1

**Comment by zplzpl** [comment]
+1

**Comment by andriytyurnikov** [comment]
+1

**Comment by andriymosin** [comment]
+1

**Comment by nikitasavinov** [comment]
+1

**Comment by jmvallet** [comment]
+1

**Comment by aadamovich** [comment]
+1

**Comment by jonaswebdev** [comment]
+1

**Comment by vosadchuk** [comment]
+1

**Comment by rpedela** [comment]
+1

My use case is returning search results of parents, but sorted by the date of the most relevant child. As far as I can tell, there isn't a way to achieve this. If there is a workaround, please let me know!

**Comment by zarrigoni** [comment]
+1

**Comment by bopeng87** [comment]
+1

**Comment by abogushov** [comment]
+1

**Comment by danipl** [comment]
+1

**Comment by jpountz** [comment]
I don't think we can realistically make it work so I am closing it as a won't fix. When this is needed, a possible workaround is to fold sort values into the score as shown by @danipl in the above message.

**Comment by rpedela** [comment]
@jpountz What has changed? I thought @martijnvg said he saw a way forward?

**Comment by jpountz** [comment]
This is something that could be implemented, but it would require a lot of specialization depending on the types of the fields that are being sorted, and I don't think that would be sustainable in the long term. Moreover, I am concerned about making features that do not scale more appealing (parent/child needs to perform a linear scan in the 2nd phase of its execution in the general case).

**Comment by martijnvg** [comment]
@rpedela I did and still see a way how this could be implemented. Implementing this feature does require writing quite some code that will only be used when using has_child/has_parent queries and sorting by a field, which won't be used if sorting by _score or when other queries are used. Over time I did see that the workaround provided here is sufficient for most people wanting to sort based on a field in a child document or parent document. I think closing this issue as won't fix is jusitfied, since adding this is far from trivial and most of the time the workaround is good enough

**Comment by rpedela** [comment]
Fair enough. Could small but complete examples (sort by parent and sort by child) be added to the docs showing how to sort using the workaround?

**Comment by martijnvg** [comment]
> Could small but complete examples (sort by parent and sort by child) be added to the docs showing how to sort using the workaround?

Yes!

**Comment by sop3k** [comment]
I there any posibility to use this workaround to sort on non numeric field?

**Comment by dimfeld** [comment]
@sop3k I can't think of any normal way to make it work on a string field, but I came up with a method which may or may not work for you depending on your application and tooling.

At index time, convert the string you want to sort into a 63-bit number and index it alongside the string field as a `long`. Assuming a really naive 8-bit encoding, you could get 7 characters worth of sorting accuracy, or you could pack the bits to fit more if you know the range of values you'll be storing. Then when you want to sort on the string field, sort on this number instead using the `function_score` technique described here.

I haven't actually tried the above, but it seems likely to work if you're staying in the ASCII range of characters. Of course, this would not work well with UTF8, and would probably not provide enough accuracy to be useful with UTF16.

**Comment by sop3k** [comment]
Thank @dimfeld for comment. I was thinking about same solution but as you mentoin it's very limited to do so with UTF8 and UTF16.

**Comment by lonre** [comment]
@martijnvg 

Hi, any updates for the workaround?

**Comment by martijnvg** [comment]
@lonre The workaround has been described here:

https://www.elastic.co/guide/en/elasticsearch/reference/5.0/query-dsl-has-child-query.html#_sorting

and here:

https://www.elastic.co/guide/en/elasticsearch/reference/5.0/query-dsl-has-parent-query.html#_sorting_2

**Comment by ayushsangani** [comment]
@martijnvg Does the workaround above work for String fields?

**Comment by boesing** [comment]
+1

**Comment by tomoktan** [comment]
+1

**Comment by zhouchong90** [comment]
+1

**Comment by s6jain** [comment]
+1

**Comment by RomanVashchegin** [comment]
Also need workaround for strings

**Comment by shushantan** [comment]
+ 1

**Comment by song-william** [comment]
I haven't been able to get this workaround to work well with a number field that can have negative, positive, and missing values. This is due to the limited precision of `_score`, the requirement that `_score > 0`, and lack of support of `_last/_first` for missing values.

**Comment by cmk1523** [comment]
+1 for this feature to added

**Comment by Chan-Ro** [comment]
+1 need this feature for string sorting

**Comment by IMayakovsky** [comment]
+1

**Comment by getsolaris** [comment]
+1

**Comment by kiransunkari** [comment]
+1
