### ISSUE TITLE
Visibility of methods and/or classes

### ISSUE THREAD

**Issue by scampi** [elastic/elasticsearch#29185]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.2

There exists public methods which take an object as parameter that is package private, thus making it impossible for plugins to actually use that method.

As an example:

- the [SearchTransportService.sendExecuteQuery](https://github.com/elastic/elasticsearch/blob/v6.2.2/server/src/main/java/org/elasticsearch/action/search/SearchTransportService.java#L148) takes a `SearchActionListener`
- [SearchActionListener](https://github.com/elastic/elasticsearch/blob/v6.2.2/server/src/main/java/org/elasticsearch/action/search/SearchActionListener.java#L29) is package private

There are several other places such a problem occur, so it would be good to make classes, accessible through public methods, public.

**Comment by jimczi** [comment]
This class is not meant to be used outside of the package where it is declared so it should not be needed inside a plugin. Out of curiosity why do you think that you need it ?
