### ISSUE TITLE
Inner_hits in update_by_query

### ISSUE THREAD

**Issue by YavorTelerik** [elastic/elasticsearch#29182]
Hi,
Is it possible to access inner_hits in script when using update_by_query?
I am not able to do it currently. The idea is to update fields on nested documents that meet certain criteria in the query part of the update_by_query.

**Comment by jimczi** [comment]
`update_by_query` uses the original `_source` of the document so only this data is accessible in the update script. There is no easy way to link an inner_hits result with a an entry in the `_source` and you cannot update nested documents partially (an update must resend all nested documents even those that did not changed) so the logic to update only some parts of the `nested` documents is not compatible with `update_by_query`.
