### ISSUE TITLE
Elastic Official NiFi processors

### ISSUE THREAD

**Issue by hijakk** [elastic/elasticsearch#29180]
Apache [NiFi](https://nifi.apache.org/) is an increasingly commonly used Extract/Transform/Load engine. It has some different use cases than Logstash, and is quite popular in some sectors. 

It has some NiFi community maintained processors for interacting with Elasticsearch, but per feedback from Elasticon, some folks who have considered NiFi have decided not to use it due to gaps between the currently available Elasticsearch processors and the current code baselines and implementation standards.

Elastic is uniquely positioned to produce and maintain an optimized set of official NiFi processors for the Elastic stack. I'm requesting that Elastic look at maintaining a set of NiFi processors as a freely distributed NAR (Nifi archive package) with the most up to date Elastic APIs, flexibility in interfacing with various Elastic stack components, etc.

Specific processors might include Elasticsearch bulk indexing, query, scanning, etc. A "nifi beats" processor could produce valuable auditing information for nifi clusters that could route through logstash/etc. Outputs for alerting from X-Pack could be valuable as well.

@tris325

**Comment by jimczi** [comment]
Hi, 
we don't provide anything related to third party ingestion in Elasticsearch directly. For this purpose we use other components of the stack (beats and logstash for instance). You should open an issue in these repos directly. We can also help you in the forum (https://discuss.elastic.co/t) if you want to write such processors by providing advices on the best way to send data to es. For these reasons I hope you don't mind if I close this issue, I'd be happy to help on the forum if you have any questions related.

**Comment by jimczi** [comment]
I am sure there is a chance for further discussions but in another repo or in another call ;). We reserve this github for feature requests regarding Elasticsearch and verified bugs.
