### ISSUE TITLE
sort by preferred nested object

### ISSUE THREAD

**Issue by dstrop** [elastic/elasticsearch#29193]
running docker image docker.elastic.co/elasticsearch/elasticsearch:6.2.3

queries bellow do not return same result
I am trying to sort by nested object, and if main user matches my nested filter, sort by it.
It works as expected if i leave must empty, but any condition in must results in should being ignored

<details><summary>queries</summary><p>

```
POST my_index/_search
{
  "sort": [
    {
      "user.height": {
        "mode": "max",
        "order": "desc",
        "nested": {
          "path": "user",
          "filter": {
            "bool": {
              "minimum_should_match": 0,
              "must": [
                {
                  "match_all": {}
                }
              ],
              "should": [
                {
                  "term": {
                    "user.main": true
                  }
                }
              ]
            }
          }
        }
      }
    }
  ]
}

POST my_index/_search
{
  "sort": [
    {
      "user.height": {
        "mode": "max",
        "order": "desc",
        "nested": {
          "path": "user",
          "filter": {
            "bool": {
              "minimum_should_match": 0,
              "should": [
                {
                  "term": {
                    "user.main": true
                  }
                }
              ]
            }
          }
        }
      }
    }
  ]
}
```
</p></details>

<details><summary>Steps to reproduce</summary><p>

```
PUT my_index
{
  "mappings": {
    "_doc": {
      "properties": {
        "user": {
          "type": "nested" 
        }
      }
    }
  }
}

PUT my_index/_doc/1
{
  "group": "fans",
  "user": [
    {
      "name": "John",
      "height": 150,
      "main": true
    },
    {
      "name": "Alice",
      "height": 200,
      "main": false
    }
  ]
}

PUT my_index/_doc/2
{
  "group": "groupies",
  "user": [
    {
      "name": "Malcolm",
      "height": 175,
      "main": true
    }
  ]
}
```
</p></details>

**Comment by jimczi** [comment]
Hi @dstrop we reserve github for verified bugs and feature requests, your question should be raised on the forum https://discuss.elastic.co/c/elasticsearch and if during the discussion we find something that does not work as expected we can open a more detailed issue.
Regarding your query, the `must` clause is always mandatory even if you have a `minimum_should_match` of 0 so all documents `must` match what is inside this section.

**Comment by dstrop** [comment]
ok, maybe it would be good idea to stipulate as such in issue guidlines

**Comment by jimczi** [comment]
> 1.  GitHub is reserved for bug reports and feature requests. The best place to
    ask a general question is at the Elastic [forums](https://discuss.elastic.co).
    GitHub is not the place for general questions.

We have this in the issue template and we encourage users to post on the forum first when they are not sure that the issue they have is a question or a real issue. I hope you don't mind that I closed your issue, the important point is that we're willing to help you but the forum is a better place for discussing how queries work in elasticsearch.

**Comment by dstrop** [comment]
oh, i dont mind but i understood from your response bug must be first verified to be posted here and there was nothing about bug verification in guidelines. thx
