### ISSUE TITLE
Allow enabling doc_values on meta fields (specifically _field_names)

### ISSUE THREAD

**Issue by snowzach** [elastic/elasticsearch#29191]
We would like the ability to enable doc_values on meta fields (specifically _field_names)

In our situation we don't control all the fields and we want to be able to look up the field names in a subset of documents (filtered by a query) We can do this with mapping but it ends up with all fields and not just the subset we are interested in. 

Older versions used to support this and it would be great if it was an option under the _field_names setting/mapping (with default to off since most people don't use this)

**Comment by jimczi** [comment]
Starting in 6.1 (https://github.com/elastic/elasticsearch/pull/26930) we don't populate the `_field_names` field for fields that have `doc_values` or `norms` activated (so all default field). 
This means that it contains only a subset of the fields (and most of the time it will be empty).
This field should be considered as internal and queries should not try to directly interact with it. It was added to speed up `exists` query but now that doc values are iterable we don't need this extra field for this kind of query and we can save the cost at indexing time.  If you need to access all fields in a document you can implement your own `field_names` field and populate it with the key present in the json document.
