### ISSUE TITLE
Remove http_addresses from Remote Cluster Info API

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#29207]
We currently make node info API requests to remote clusters as part of the Remote Cluster Info API in order to return information about `http_addresses` of the remote nodes.
`http_addresses` was originally introduced for kibana to do `_field_caps` but this is not used in any actionable way and could be removed from the response or replaced with transport addresses, so that the the remote nodes info API calls can be skipped.

Worth noting here that these API calls also require additional privileges for users running x-pack security.

**Comment by jasontedor** [comment]
@nik9000 Can you investigate this one and if appropriate, make the necessary changes?

**Comment by nik9000** [comment]
> @nik9000 Can you investigate this one and if appropriate, make the necessary changes?

I'll take it!
