### ISSUE TITLE
Updates to CONTRIBUTING.md

### ISSUE THREAD

**Issue by danlevy1** [elastic/elasticsearch#29214]
**_Feature Request (Documentation Fix)_**

When I originally tried to run Elasticsearch on my machine (a Mac), I had some trouble following the steps. I kept track of some of the things I had to look up elsewhere in order to get Elasticsearch working. Here are some fixes I came up with:

1) Giving a little more information about running Elasticsearch in a CLI
2) Setting up Elasticsearch in Eclipse
3) Turning steps into numbered steps instead of paragraphs
4) More subsections to help split up the information

I would like to get some more input as to what others want to see in the CONTRIBUTING.md file.

**Comment by danlevy1** [comment]
I have a draft of the overhauled CONTRIBUTING.md file available [here](https://github.com/FloridaTechSharks/elasticsearch/blob/Dan-Levy-Changes/CONTRIBUTING.md). Please take a look and see what other updates should be made.

**Comment by nik9000** [comment]
> I have a draft of the overhauled CONTRIBUTING.md file available here. Please take a look and see what other updates should be made.

It'd be way easier to review your proposal if you made a PR out of it. Automatic diffs and all.

**Comment by rjernst** [comment]
@danlevy1 Please open a PR with your suggested changes. I'm going to close this as there is no need for a parallel discussion or a tracking issue. Any discussion can be had on the PR.
