### ISSUE TITLE
Better Task status reporting in Tasks API

### ISSUE THREAD

**Issue by shivendrasoni** [elastic/elasticsearch#29212]
Allow `Tasks API` to show statuses of completed jobs as well. 
For queries like large bulk updates/ indexing operations the query can take a long time and the client usually times out.  
Instead of setting enormous timeouts, I feel it would be better to allow to check the status of a task, basically in terms of completed/failed etc.

Upon using the Tasks API  to check the status for a running request I receive the response with a `completed` field. However, after it actually completes, querying by task-id shows resource not found.

**Comment by nik9000** [comment]
> Allow Tasks API to show statuses of completed jobs as well.

This is already implemented for jobs that opt in to storing themselves when they are done. Basically just `reindex` and friends do this and only when they are run with `?wait_for_completion=false`. We *expect* them to take a long time so they opt in to this.

The trouble is that *everything* is a task and you'd up in a bad spot if you tried to create a record of every task. To be honest, if a bulk update is so large that you worry about it timing out while waiting on it I think you are better off splitting it up.

**Comment by bleskes** [comment]
@shivendrasoni if your bulk indexing takes longer than what's reasonable for a timeout variable, something else is off. As Nik explained, tasks that are expected to run a very long time have this support. If we're missing it somewhere, we should add it but I don't feel that the bulk API is a good candidate. We can try to figure out what makes the bulk API so slow , if you open a topic on discuss.elastic.co and get back to github if there something to change in the code. Hope this helps.
