### ISSUE TITLE
[CI] Logger status data left around after test

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#29220]
I was not 100% sure if the only happens with the `ESLoggingHandlerIT.testLoggingHandler()` test, however but because a post test assertion failed I made the issue title more generic.

I'm able to reproduce random failures locally on 6.2 branch with the following command:

```
./gradlew :modules:transport-netty4:integTestRunner -Dtests.iters=1024 -Dtests.class=org.elasticsearch.transport.netty4.ESLoggingHandlerIT -Dtests.method="testLoggingHandler"
```

```
FAILURE 4.75s | ESLoggingHandlerIT.testLoggingHandler <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: an empty collection
   >      but: <[An exception occurred processing Appender mock]>
   > 	at __randomizedtesting.SeedInfo.seed([AE4DA961CC2E1FA3:FFD2285652A48E25]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:409)
   > 	at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:291)
   > 	at java.lang.Thread.run(Thread.java:748)
```

[consoleText.txt](https://github.com/elastic/elasticsearch/files/1841231/consoleText.txt)

Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+multijob-unix-compatibility/os=amazon/261/consoleText

**Comment by jasontedor** [comment]
Duplicates #27306
