### ISSUE TITLE
Improve Cluster Allocation Explain API explanation when cluster has nodes with different versions

### ISSUE THREAD

**Issue by luizgpsantos** [elastic/elasticsearch#29228]
**Describe the feature**:

During a [rolling upgrade](https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html) if the shards allocation wasn't disabled some shards may become unassigned due to version incompatibility.

In this situation, the Cluster Allocation Explain API shows this message:

```
target node version [X.X.X] is older than the source node version [Y.Y.Y] and may
not support codecs or postings formats for a newer Lucene version
```

Can we think of a more straightforward message that points the version divergence?

**Comment by bleskes** [comment]
@luizgpsantos can you suggest a message? or perhaps point out what is confusing to you?

**Comment by luizgpsantos** [comment]
Hi @bleskes, the point here is just to make the message easier to digest for those with fewer experience with upgrades. I will write my suggestion in raw words just to try to express the feeling and we may have to adapt to a more formal one:

```
Shard is in 6.2.2 format and cannot be allocated in a 6.0.1 node. All cluster's nodes should have the same version [6.2.2]
```

**Comment by DaveCTurner** [comment]
I can see why the message is confusing, but the confusion for me would be cleared up by simply removing the "and may not support ...":

    target node version [X.X.X] is older than the source node version [Y.Y.Y]

Maybe slightly more friendly wording:

    cannot transfer a shard from a node with version [Y.Y.Y] to a node with older version [X.X.X]

I don't think this message needs any explanation about why this rule exists - it seems enough to state it.

**Comment by DaveCTurner** [comment]
I opened #29356.
