### ISSUE TITLE
[CI] SearchTimeoutIT.testSimpleTimeout()

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#29221]
Timing issue, search time expected but never happened:

```
FAILURE 2.45s J2 | SearchTimeoutIT.testSimpleTimeout <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <true>
   >      but: was <false>
   > 	at __randomizedtesting.SeedInfo.seed([C7A511D27D1BD747:84FFF8844B6B8044]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.search.SearchTimeoutIT.testSimpleTimeout(SearchTimeoutIT.java:67)
   > 	at java.lang.Thread.run(Thread.java:748)
```

Maybe we should lower the time out argument? (currently it is 10ms)

[consoleText.txt](https://github.com/elastic/elasticsearch/files/1841654/consoleText.txt)

Build url: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-windows-compatibility/835/consoleText

**Comment by jpountz** [comment]
I suspect we should also index more documents. Currently it only indexes one document, so if document collection starts before the timeout, there is no reason for Elasticsearch to consider that the search timed out?
