### ISSUE TITLE
TransportClient: InvalidTypeNameException prepareCreate addMapping

### ISSUE THREAD

**Issue by peruzzijl** [elastic/elasticsearch#29237]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.3

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Windows Server 2008 R2

**Description of the problem including expected versus actual behavior**:
Attempting to send a valid mapping JSON object to ElasticSearch 6.2.3 with Java Transport Client 6.2.3 and receive an error stating the type name is too long.  When putting this JSON into Dev Tools in Kibana the index is created.

**Steps to reproduce**:

**Json:**
`"question": {
    "properties": {
      "@timestamp": {
        "doc_values": true,
        "format": "strict_date_optional_time||epoch_millis",
        "locale": "en",
        "ignore_malformed": false,
        "index": true,
        "boost": 0.0,
        "store": false,
        "type": "date"
      },
      "ecs_version": {
        "doc_values": true,
        "eager_global_ordinals": false,
        "ignore_above": 2147483647,
        "index_options": "docs",
        "norms": false,
        "similarity": "BM25",
        "index": true,
        "boost": 0.0,
        "store": false,
        "type": "keyword"
      },
      "message": {
        "analyzer": "standard",
        "eager_global_ordinals": false,
        "fielddata": false,
        "index_options": "positions",
        "norms": true,
        "position_increment_gap": 100,
        "search_analyzer": "standard",
        "search_quote_analyzer": "standard",
        "similarity": "BM25",
        "term_vector": "no",
        "index": true,
        "boost": 0.0,
        "store": false,
        "type": "text"
      },
      "question": {
        "properties": {
          "content_delimiter": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "createdBy": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "created_date": {
            "doc_values": true,
            "format": "basic_date_time||basic_date_time_no_millis||basic_ordinal_date_time||basic_ordinal_date_time_no_millis||date_hour_minute_second_millis",
            "locale": "en",
            "ignore_malformed": false,
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "date"
          },
          "equality": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "filter_type": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "filter_value": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "linux_query_content": {
            "analyzer": "standard",
            "eager_global_ordinals": false,
            "fielddata": false,
            "index_options": "positions",
            "norms": true,
            "position_increment_gap": 100,
            "search_analyzer": "standard",
            "search_quote_analyzer": "standard",
            "similarity": "BM25",
            "term_vector": "no",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "text"
          },
          "linux_script_id": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "mac_query_content": {
            "analyzer": "standard",
            "eager_global_ordinals": false,
            "fielddata": false,
            "index_options": "positions",
            "norms": true,
            "position_increment_gap": 100,
            "search_analyzer": "standard",
            "search_quote_analyzer": "standard",
            "similarity": "BM25",
            "term_vector": "no",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "text"
          },
          "name": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "osx_script_id": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "permission": {
            "properties": {
              "auth_level": {
                "doc_values": true,
                "eager_global_ordinals": false,
                "ignore_above": 2147483647,
                "index_options": "docs",
                "norms": false,
                "similarity": "BM25",
                "index": true,
                "boost": 0.0,
                "store": false,
                "type": "keyword"
              },
              "auth_type": {
                "doc_values": true,
                "eager_global_ordinals": false,
                "ignore_above": 2147483647,
                "index_options": "docs",
                "norms": false,
                "similarity": "BM25",
                "index": true,
                "boost": 0.0,
                "store": false,
                "type": "keyword"
              }
            },
            "dynamic": true,
            "type": "nested"
          },
          "prompt": {
            "doc_values": true,
            "type": "boolean"
          },
          "query_content": {
            "analyzer": "standard",
            "eager_global_ordinals": false,
            "fielddata": false,
            "index_options": "positions",
            "norms": true,
            "position_increment_gap": 100,
            "search_analyzer": "standard",
            "search_quote_analyzer": "standard",
            "similarity": "BM25",
            "term_vector": "no",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "text"
          },
          "question_hidden": {
            "doc_values": true,
            "type": "boolean"
          },
          "short_name": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "sig_type": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "sig_type_pol_id": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "sig_type_sig_id": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "subType": {
            "coerce": true,
            "doc_values": true,
            "ignore_malformed": false,
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "integer"
          },
          "type": {
            "coerce": true,
            "doc_values": true,
            "ignore_malformed": false,
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "integer"
          },
          "windows_script_id": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          }
        },
        "dynamic": true,
        "enabled": true,
        "type": "object"
      }
    },
    "dynamic": true,
    "enabled": true
  }`

**Command**
`client.admin().indices().prepareCreate("tychon_question").setSettings(map.getSettings()).addMapping(xml).get()`

**Provide logs (if relevant)**:

Exception in thread "main" InvalidTypeNameException[mapping type name [
  "question": {
    "properties": {
      "@timestamp": {
        "doc_values": true,
        "format": "strict_date_optional_time||epoch_millis",
        "locale": "en",
        "ignore_malformed": false,
        "index": true,
        "boost": 0.0,
        "store": false,
        "type": "date"
      },
      "ecs_version": {
        "doc_values": true,
        "eager_global_ordinals": false,
        "ignore_above": 2147483647,
        "index_options": "docs",
        "norms": false,
        "similarity": "BM25",
        "index": true,
        "boost": 0.0,
        "store": false,
        "type": "keyword"
      },
      "message": {
        "analyzer": "standard",
        "eager_global_ordinals": false,
        "fielddata": false,
        "index_options": "positions",
        "norms": true,
        "position_increment_gap": 100,
        "search_analyzer": "standard",
        "search_quote_analyzer": "standard",
        "similarity": "BM25",
        "term_vector": "no",
        "index": true,
        "boost": 0.0,
        "store": false,
        "type": "text"
      },
      "question": {
        "properties": {
          "content_delimiter": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "createdBy": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "created_date": {
            "doc_values": true,
            "format": "basic_date_time||basic_date_time_no_millis||basic_ordinal_date_time||basic_ordinal_date_time_no_millis||date_hour_minute_second_millis",
            "locale": "en",
            "ignore_malformed": false,
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "date"
          },
          "equality": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "filter_type": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "filter_value": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "linux_query_content": {
            "analyzer": "standard",
            "eager_global_ordinals": false,
            "fielddata": false,
            "index_options": "positions",
            "norms": true,
            "position_increment_gap": 100,
            "search_analyzer": "standard",
            "search_quote_analyzer": "standard",
            "similarity": "BM25",
            "term_vector": "no",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "text"
          },
          "linux_script_id": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "mac_query_content": {
            "analyzer": "standard",
            "eager_global_ordinals": false,
            "fielddata": false,
            "index_options": "positions",
            "norms": true,
            "position_increment_gap": 100,
            "search_analyzer": "standard",
            "search_quote_analyzer": "standard",
            "similarity": "BM25",
            "term_vector": "no",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "text"
          },
          "name": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "osx_script_id": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "permission": {
            "properties": {
              "auth_level": {
                "doc_values": true,
                "eager_global_ordinals": false,
                "ignore_above": 2147483647,
                "index_options": "docs",
                "norms": false,
                "similarity": "BM25",
                "index": true,
                "boost": 0.0,
                "store": false,
                "type": "keyword"
              },
              "auth_type": {
                "doc_values": true,
                "eager_global_ordinals": false,
                "ignore_above": 2147483647,
                "index_options": "docs",
                "norms": false,
                "similarity": "BM25",
                "index": true,
                "boost": 0.0,
                "store": false,
                "type": "keyword"
              }
            },
            "dynamic": true,
            "type": "nested"
          },
          "prompt": {
            "doc_values": true,
            "type": "boolean"
          },
          "query_content": {
            "analyzer": "standard",
            "eager_global_ordinals": false,
            "fielddata": false,
            "index_options": "positions",
            "norms": true,
            "position_increment_gap": 100,
            "search_analyzer": "standard",
            "search_quote_analyzer": "standard",
            "similarity": "BM25",
            "term_vector": "no",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "text"
          },
          "question_hidden": {
            "doc_values": true,
            "type": "boolean"
          },
          "short_name": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "sig_type": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "sig_type_pol_id": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "sig_type_sig_id": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          },
          "subType": {
            "coerce": true,
            "doc_values": true,
            "ignore_malformed": false,
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "integer"
          },
          "type": {
            "coerce": true,
            "doc_values": true,
            "ignore_malformed": false,
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "integer"
          },
          "windows_script_id": {
            "doc_values": true,
            "eager_global_ordinals": false,
            "ignore_above": 2147483647,
            "index_options": "docs",
            "norms": false,
            "similarity": "BM25",
            "index": true,
            "boost": 0.0,
            "store": false,
            "type": "keyword"
          }
        },
        "dynamic": true,
        "enabled": true,
        "type": "object"
      }
    },
    "dynamic": true,
    "enabled": true
  }
] is too long; limit is length 255 but was [9720]]
	at org.elasticsearch.index.mapper.MapperService.validateTypeName(MapperService.java:361)
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:401)
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:353)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:277)
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:444)
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:643)
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:273)
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198)
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133)
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:573)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by peruzzijl** [comment]
Just an FYI, I did the above following the guidance from the Elastic API Docs:

[Java API](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-admin-indices.html)

**Comment by dadoonet** [comment]
For information @peruzzijl also opened the report on discuss: https://discuss.elastic.co/t/transportclient-invalidtypenameexception-preparecreate-addmapping/125487

I think it's better to have the discussion on discuss and open an issue in github if it's indeed a confirmed bug.

**Comment by peruzzijl** [comment]
@dadoonet Would you like  me to close and submit new or leave open until discussion has reached a point that this is not a bug/documentation needs updating?

**Comment by dadoonet** [comment]
Yeah. That'd be preferable but as I'm feeling that may be it's a documentation issue I did not close it myself :)
