### ISSUE TITLE
 Elasticsearch is poisonous

### ISSUE THREAD

**Issue by ver007** [elastic/elasticsearch#29240]
Please forgive me for taking the liberty that Elasticsearch is poisonous. Every time you update the connection method or query the index name will change, the developer is toxic.
~ (+﹏+)~，I am very helpless

**Comment by jay-dihenkar** [comment]
can u give a minimal reproduction of the issue!???? lollzzz

**Comment by dadoonet** [comment]
@ver007 Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
