### ISSUE TITLE
Extend Parent Pipeline aggs to work with Ranges

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#29250]
Today, parent pipeline aggs (e.g, `derivative`, `avg`, etc) only work with Histo/DateHisto aggs because they provide sequential ordering of data.

It is theoretically possible to extend this to include Range/DateRange aggs as well, which implicitly provide ordering by the range definitions provided by the user.

There are some potentially sticky edge-cases:

- How do we deal with gaps?  Only fill in gaps if they were explicitly defined as ranges by the user?
- Some pipeline aggs assume constant width (e.g. `derivative`), but that assumption is violated when the user can define arbitrary ranges.  This will probably be an issue with the AutoHisto agg too
- How do we deal with overlap between range?  Just blindly calculate and assume the user knows there is overlap?

**Comment by abhiroj** [comment]
can I look into this?

**Comment by polyfractal** [comment]
@abhiroj sure :)  

Fair warning though, it's marked as `high hanging fruit` meaning the solution is probably non-negligible and might be fairly difficult/complex.  And we might decide that the implementation is too complex or too difficult to use and not end up merging.  Just as an FYI. :)

**Comment by wchaparro** [comment]
Closing as not planned for aggregations
