### ISSUE TITLE
Add remove types token filter (as opposite to keep_types token filter)

### ISSUE THREAD

**Issue by edovac** [elastic/elasticsearch#29277]
**Describe the feature**:
Hi, Elasticsearch provides the `keep_types` token filter, but does not provide a token filter to exclude specific token types from the token stream.

As I understand, the `keep_types` token filter is implemented using Lucene  `org.apache.lucene.analysis.core.TypeTokenFilter.TypeTokenFilter(TokenStream, Set<String>, boolean)` which implements both behaviours.
It would be nice to have the remove filter too. 

Elasticsearch version: 6.2

**Comment by edovac** [comment]
Hi, sorry for the delay.
The use case is a little bit articulated, I'll try to keep it plain simple.

The company I work in is developing an analyzer which can manage (among other things) named entity extractions and structured text.
By structured text I mean a text for which I provide explicit sections structure like:

<document>
<title>John Smith hired by Acme Inc.</title>
<body>Last monday the company announced the new hire.</body>
</document>

Sections names are not fixed, the can repeat in the same text and they change on a per project basis. 
Named entities also can vary by project.

We need to support per extraction type queries, and also constraining the search to a specific section.
ie: John Smith as person in section title

We also need to support near queries between different extraction types like:
John Smith as person near Acme Inc. as organization
This could be done both by sentence (using slop) or by named section.

Here is a mapping example:

{
	"settings": {
		"analysis": {
			"analyzer": {
				"field_analyzer": {
					"type": "custom",
					"tokenizer": "structure_tokenizer"
				},
				"sentence_analyzer": {
					"type": "custom",
					"tokenizer": "structure_tokenizer",
					"filter": [
						"not_section"
					]
				},
				"organizations_analyzer": {
					"type": "custom",
					"tokenizer": "structure_tokenizer",
					"filter": [
						"organizations"
					]
				},
				"people_analyzer": {
					"type": "custom",
					"tokenizer": "structure_tokenizer",
					"filter": [
						"people"
					]
				},
			},
			"tokenizer": {
				"structure_tokenizer": {
					"type": "structure-tokenizer"
				}
			},
			"filter": {
				"organizations": {
					"type": "keep_types",
					"types": [
						"organization"
					]
				},
				"people": {
					"type": "keep_types",
					"types": [
						"people"
					]
				},
				"section": {
					"type": "keep_types",
					"types": [
						"section"
					]
				},
				"not_section": {
					"type": "remove_types",
					"types": [
						"section"
					]
				}
			}
		}
	},
	"mappings": {
		"type": {
			"properties": {
				"text": {
					"type": "text",
					"fielddata": true,
					"analyzer": "sentence_analyzer",
					"term_vector": "with_positions_offsets",
					"fields": {
						"organizations": {
							"type": "text",
							"fielddata": true,
							"analyzer": "organizations_analyzer",
							"term_vector": "with_positions_offsets"
						},
						"people": {
							"type": "text",
							"fielddata": true,
							"analyzer": "people_analyzer",
							"term_vector": "with_positions_offsets"
						},
						"section": {
							"type": "text",
							"analyzer": "section_analyzer",
							"term_vector": "with_positions_offsets"
						}
					}
				}
			}
		}
	}
}


structure-tokenizer is developed by us.
Our analysis engine is able to generate a record like this:
- value: John Smith
- offset: [0, 10]
- token pos: 0
- type: people
- section: title

From this records we generate index tokens:

example for text
- value: John Smith
- offset: [0, 10]
- token pos: 0
- type: people

- value: hired
- offset: [11, 16]
- token pos: 1
- type: keyword

example for people:
- value: John Smith
- offset: [0, 10]
- token pos: 0
- type: people

example for section:
- value: title
- offset: [0, 10]
- token pos: 0
- type: section

- value: title
- offset: [11, 16]
- token pos: 0
- type: section

For each token we have an overlapping one in the section field.

"text" field contains all tokens and will be used for match and phrase queries.

To support constraints by section we use the dedicate field "section" in conjunction with field_masking_span and span_containing.
Thus, we use a dedicated "section" field to store section information for each token.
ie: 
GET /_search
{
	"query": {
		"span_containing": {
			"big": {
				"span_term": {
					"people": "John Smith"
				}
			},
			"little": {
				"field_masking_span": {
					"query": {
						"span_term": {
							"section": "title"
						}
					},
					"field": "poeple"
				}
			}
		}
	}
}



Coming back to our main point, "text" field requires all tokens except those relatives to "section" and thus the request for a "remove_types" token filter. 
I'm aware that I can achieve the same results using the "keep_types" to include only useful tokens, but it seems overly verbose, error prone and less readable.

ie:

"not_section": {
	"type": "remove_types",
	"types": [
		"section"
	]
}

vs.

"not_section": {
	"type": "keep_types",
	"types": [
		"keyword",
		"people",
		"organizations"
	]
}

We often have tens of different named extractions. 

I hope this will clarify my request :)

**Comment by jpountz** [comment]
Discussed in FixitFriday: we agreed to do it. Here is the plan we discussed:
 - update the existing filter so that it supports includes and excludes
 - not support wildcards, only exact strings
 - fail if both includes and excludes are specified

**Comment by edovac** [comment]
Thanks :)
