### ISSUE TITLE
Does elasticsearch supports snapshot for nas storage?

### ISSUE THREAD

**Issue by springCkWyy** [elastic/elasticsearch#29308]
From www.elastic.co i know thatr snapshot support hdfs、s3、azure。 But i cannot learn that weather it support NAS? and if true, can tell me how to operate and APIs？ 

thank you very much. and Best washes.

**Comment by jkakavas** [comment]
Hi @springCkWyy , we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!
