### ISSUE TITLE
"The bulk request must be terminated by a newline [\n]"

### ISSUE THREAD

**Issue by strong666** [elastic/elasticsearch#29309]
Why is it always wrong?

curl -H "Content-Type: application/json" -XPOST '172.16.50.232:9200/love/doc/_bulk?pretty&refresh' --data-binary "@demo.json"

{"index":{"_index":"love","_id":"0"}}
{"name":"志明","action":"写信","count":70,"percent":0.579,"avgnum":1502,"maxnum":5215,"minnum":624}
{"index":{"_index":"love","_id":"1"}}
{"name":"志明","action":"约会","count":60,"percent":0.613,"avgnum":3.8,"maxnum":6.4,"minnum":1.6}
{"index":{"_index":"love","_id":"2"}}
{"name":"志明","action":"见家长","count":38,"percent":0.514,"avgnum":0,"maxnum":0,"minnum":0}
{"index":{"_index":"love","_id":"3"}}
{"name":"春娇","action":"写信","count":51,"percent":0.421,"avgnum":1502,"maxnum":5215,"minnum":624}
{"index":{"_index":"love","_id":"4"}}
{"name":"春娇","action":"约会","count":38,"percent":0.387,"avgnum":3.8,"maxnum":6.4,"minnum":1.6}
{"index":{"_index":"love","_id":"5"}}
{"name":"春娇","action":"见家长","count":36,"percent":0.486,"avgnum":0,"maxnum":0,"minnum":0}

**Comment by jkakavas** [comment]
Hi @strong666 , 

Can you provide some more context as to what you're trying to achieve and what the problem might be? If you think you stumbled upon a bug please take the time to provide some details as it is asked in the issue template
```

<!-- Bug report -->

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
```

If this is a question around how to use the bulk api, please ask your question in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!

**Comment by strong666** [comment]
HI@jkakavas， I'm using curl to do batch import data to ES, and one of the reports is wrong, but I think that's what the document does, and I don't know exactly what I did wrong.

--1.  my es index
{"state":"open","settings":{"index":{"creation_date":"1522393650959","number_of_shards":"5","number_of_replicas":"1","uuid":"kiWuPd5aRLihT6FrX8xdBA","version":{"created":"6010199"},"provided_name":"love"}},"mappings":{"doc":{"properties":{"avgnum":{"type":"double"},"count":{"type":"integer"},"name":{"type":"keyword"},"action":{"type":"keyword"},"maxnum":{"type":"double"},"percent":{"type":"double"},"minnum":{"type":"double"}}}},"aliases":[],"primary_terms":{"0":1,"1":1,"2":1,"3":1,"4":1},"in_sync_allocations":{"0":["ZpZHB-yvRcCuHV1RxULxOA"],"1":["9-5biUTdRTelwhJDStBrfw"],"2":["aa8CUCUCS12xeH7MBb2zzA"],"3":["fp0Ths5iSWKfU9F-WZpMbw"],"4":["1IupjkXRQ6KU_8fWVtGeGw"]}}

--2. I need to import the data.
{“index”：{“_ index”：“love”，“_ id”：“0”}} 
{“name”：“志明”，“action”：“写信”，“count”：70， ：0.579，“avgnum”：1502，“maxnum”：5215，“minnum”：624} 
{“index”：{“_ index”：“love”，“_ id”：“1”}} 
{“name”志明“，”行动“：”约会“，”计数“：60，”百分比“：0.613，”avgnum“：3.8，”maxnum“：6.4，”minnum“：1.6} 
{”index“：{”_ index“ ：“爱”，“_ id”：“2”}} 
{“name”：“志明”，“action”：“见家长”，“count”：38，“percent”：0.514，“avgnum” “MAXNUM”：0，”minnum“：0} 
{”index“：{”_ index“：”love“，”_ id“：”3“}} 
{”name“：”春娇“，”action“：”写信“，”count“ ：51，“百分比”：0.421，“avgnum”：1502，“maxnum”：5215，“minnum”：624} 
{“index”：{“_ index”：“love”，“_ id”：“4”}} 
{ “名”： “春娇”， “行动”： “约会”， “伯爵”：38， “百分比”：0.387， “avgnum”：3.8， “MAXNUM”：6.4， “minnum”：1.6} 
{”指数“：{” _指数“：”爱”， “_ ID”： “5”}}春娇“，”动作“：”写信“，”计数“：51，”百分比“：0.421，”avgnum“：1502，”maxnum“：5215，”minnum“：624} {”index“ _index“：”love“，”_ id“：”4“}} {”name“：”春娇“，”action“：”约会“，”count“：38，”percent“：0.387，”avgnum“： 3.8，“maxnum”：6.4，“minnum”：1.6} {“index”：{“_ index”：“love”，“_ id”：“5”}}春娇“，”动作“：”写信“，”计数“：51，”百分比“：0.421，”avgnum“：1502，”maxnum“：5215，”minnum“：624} {”index“ _index“：”love“，”_ id“：”4“}} {”name“：”春娇“，”action“：”约会“，”count“：38，”percent“：0.387，”avgnum“： 3.8，“maxnum”：6.4，“minnum”：1.6} {“index”：{“_ index”：“love”，“_ id”：“5”}}春娇“，”行动“：”约会“，”计数“：38，”百分比“：0.387，”avgnum“：3.8，”maxnum“：6.4，”minnum“：1.6} {”index“：{”_ index “：”爱”， “_ ID”： “5”}}春娇“，”行动“：”约会“，”计数“：38，”百分比“：0.387，”avgnum“：3.8，”maxnum“：6.4，”minnum“：1.6} {”index“：{”_ index “：”爱”， “_ ID”： “5”}}
{ “名称”： “春娇”， “动作”： “见家长”， “计数”：36， “百分比”：0.486， “avgnum”：0 “MAXNUM”：0 “minnum”：0}

--3 I use GIT to import commands.
curl -H 'Content-Type: application/x-ndjson' -XPOST '172.16.50.232:9200/love/doc/_bulk?pretty' --data-binary @demo.json

--4 error
The bulk request must be terminated by a newline [\n]

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

You are most likely missing a final \n or usIng a non UTF8 character encoding

**Comment by FilBot3** [comment]
For those coming here, make sure your JSON file isn't one big long line and actually has new lines. That moved me on to the next error.
