### ISSUE TITLE
Query String Query with quote_field_suffix not using the quote_field_suffix field to search

### ISSUE THREAD

**Issue by sherry-ger** [elastic/elasticsearch#29324]
**Elasticsearch version**
6.2.3

**Plugins installed**: []
X-Pack

**JVM version** (`java -version`):
1.8.0_162

**Description of the problem including expected versus actual behavior**:

Query string query with `quote_field_suffix` not using the correct field for search.  Simple query string query seems to work correctly.  Also, this works fine in version 5.6 and 6.0 alpha 2

**Steps to reproduce**:

```
PUT testindex
{
  "settings": {
    "analysis": {
      "analyzer": {
        "english_exact": {
          "tokenizer": "standard",
          "filter": [
            "lowercase"
          ]
        }
      }
    },
    "number_of_shards": 1,
    "number_of_replicas": 0
  },
  "mappings": {
    "type": {
      "properties": {
        "body": {
          "type": "text",
          "analyzer": "english",
          "fields": {
            "exact": {
              "type": "text",
              "analyzer": "english_exact"
            }
          }
        }
      }
    }
  }
}

PUT testindex/type/1
{
  "body": "Ski resort"
}

PUT testindex/type/2
{
  "body": "A pair of skis"
}

PUT testindex/type/3
{
  "body": "ski boots"
}

POST testindex/_refresh

GET testindex/_search                               <-- works fine 
{
  "query": {
    "simple_query_string": {
      "fields": [ "body" ],
      "quote_field_suffix": ".exact",
      "query": "\"ski boot\""
    }
  }
}

GET testindex/_search
{
  "query": {
    "query_string": {
      "fields": [ "body" ],
      "quote_field_suffix": ".exact",
      "query": "\"ski boot\""
    }
  }
}

GET testindex/_validate/query?rewrite 
{
  "query": {
    "query_string": {
      "fields": [ "body" ],
      "quote_field_suffix": ".exact",
      "query": "\"ski boot\""
    }
  }
}
```

The result of the rewrite seems to drop the `exact` multi-field.

**Comment by ushakanagaraj** [comment]
Hi Sherry, thank you for filing the bug. Is there an ETA on this? One of our feature delivery is dependent on this.

**Comment by imranazad** [comment]
Does anyone know when this will be released officially?

**Comment by jasontedor** [comment]
@imranazad It should be included in 6.3.0, but as a matter of policy we do not provide release dates.

**Comment by imranazad** [comment]
@jasontedor Thanks, I've downloaded the version from here: https://www.elastic.co/downloads/elasticsearch

But the issue persists, I've noticed there are various references to 6.3.0 but I can't seem to figure out where to download it from. 

Can you please advise?

**Comment by jasontedor** [comment]
6.3.0 is not released yet; that’s why I say we do not provide release dates.

**Comment by imranazad** [comment]
@jasontedor Ah I see, thanks I realised that afterwards. I'll keep an eye out.

**Comment by jasontedor** [comment]
You're welcome; sorry for the previous confusion.
