### ISSUE TITLE
2.4.1 disk.watermark.low doesn't work

### ISSUE THREAD

**Issue by iPush** [elastic/elasticsearch#29326]
**Elasticsearch version** (`bin/elasticsearch --version`): 2.4.1

**Plugins installed**: []

**JVM version** (`java -version`):j ava version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):Linux A02-R05-I220-73.JD.LOCAL 2.6.32-504.16.2.el6.x86_64 #1 SMP Wed Apr 22 06:48:29 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

 1. disk section of elasticsearch.yml
cluster.routing.allocation.allow_rebalance: indices_all_active
cluster.routing.allocation.disk.watermark.high: 100gb
cluster.routing.allocation.disk.watermark.low: 200gb

 2. 
[admin@A02-R05-I220-73 config]$ curl -s localhost:9200/_cat/allocation
881   1.1tb   1.1tb 493.5gb 1.6tb 70
881   1.1tb   1.1tb 492.5gb 1.6tb 70 
147  74.7gb  75.7gb   1.5tb 1.6tb  4 
880   1.1tb   1.1tb 518.2gb 1.6tb 69 
881   1.1tb   1.1tb 501.6gb 1.6tb 70 
881     1tb     1tb 548.9gb 1.6tb 67 
880   1.1tb   1.1tb 493.8gb 1.6tb 70
880   1.1tb   1.1tb 530.9gb 1.6tb 68 
881   1.1tb   1.1tb 538.1gb 1.6tb 67 
878 811.2gb   814gb   8.8tb 9.5tb  8 
881   1.1tb   1.1tb   513gb 1.6tb 69 
881     1tb     1tb 560.4gb 1.6tb 66 
879 977.6gb   1.3tb 297.4gb 1.6tb 82 
880   1.1tb   1.1tb 491.8gb 1.6tb 70
881   1.1tb   1.2tb 132.9gb 1.3tb 90  ******** WEIRD ONE **********
881   1.1tb   1.1tb 537.4gb 1.6tb 67 
880   1.1tb   1.1tb 520.2gb 1.6tb 68 
881   1.1tb   1.1tb 481.9gb 1.6tb 71 
878   889gb 894.3gb   8.7tb 9.5tb  9 1
881   1.1tb   1.1tb 541.5gb 1.6tb 67 

3. the WEIRD ONE , disk.available < 200G, but es still allocates new shards to it.
**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
Sorry, but Elasticsearch 2.4 is at end-of-life since the end of February. For us to take a look at an issue, it needs to be on a supported version of Elasticsearch. If you can reproduce this on a supported version of Elasticsearch, we would be happy to take a look.

**Comment by iPush** [comment]
@jasontedor  Could you provide a list of supported version of Elasticsearch?

**Comment by DaveCTurner** [comment]
Please see https://www.elastic.co/support/eol for more details.

**Comment by iPush** [comment]
thank you.
