### ISSUE TITLE
Source Filtering in JAVA REST API

### ISSUE THREAD

**Issue by santoshbeeram** [elastic/elasticsearch#29335]
Hi,

Im trying to do source filtering with the specific key "primary_key" in JAVA REST API
below is the elasticsearch query which gives me correct results how can i do the same in API

GET _search/
{
   "_source": {
        "includes": [ "primary_key" ]
    },
  "query": {
    "match_all": {}
  }
}

Thanks

**Comment by nik9000** [comment]
We try to reserve github for feature requests and bug reports. I'd ask this on https://discuss.elastic.co .
