### ISSUE TITLE
Search query perfomance decrease

### ISSUE THREAD

**Issue by giocaputo** [elastic/elasticsearch#29354]
The query perfomance are about 30 % more expensive! 

**Elasticsearch version** : 6.2.2

Search query performance comparing version 5.2.2 there is about 30% performance decrease.
I have near 300k documents, 

I had care about mapping type using keyword type, and text type.

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
