### ISSUE TITLE
Optimize IndexingMemoryController with IndexWriter.flushNextBuffer

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#29368]
We should look into using `IndexWriter.flushNextBuffer` (available since Lucene 7.3) to release memory from the IndexWriter, which allows to write a single buffer at a time, usually the largest one. I would expect this to create larger segments on average, which in-turn should make indexing faster since those segments will need less merging (to be tested).

**Comment by ywelsch** [comment]
Closing in favor of #34553
