### ISSUE TITLE
UNASSIGNED DANGLING_INDEX_IMPORTED can not delete!!

### ISSUE THREAD

**Issue by dzhyw** [elastic/elasticsearch#29361]
when I upgrade es version，es 2.4.1 to es 5.6.3, some indices shards appeared shard unassigned

status :UNASSIGNED DANGLING_INDEX_IMPORTED , when i delete,it still appeared. can't del 

Here is some information on the index：

logstash-express-error-2018.03.12   1 r STARTED    
logstash-express-error-2018.03.12   1 p STARTED    
logstash-express-error-2018.03.12   3 p STARTED    
logstash-express-error-2018.03.12   3 r STARTED    
logstash-express-error-2018.03.12   4 r STARTED    
logstash-express-error-2018.03.12   4 p STARTED    
logstash-express-error-2018.03.12   0 p STARTED    
logstash-express-error-2018.03.12   0 r STARTED    
logstash-wccpc-2017.10.10           2 p UNASSIGNED DANGLING_INDEX_IMPORTED
logstash-wccpc-2017.10.10           2 r UNASSIGNED DANGLING_INDEX_IMPORTED
logstash-wccpc-2017.10.10           1 p UNASSIGNED DANGLING_INDEX_IMPORTED
logstash-wccpc-2017.10.10           1 r UNASSIGNED DANGLING_INDEX_IMPORTED
logstash-wccpc-2017.10.10           3 p UNASSIGNED DANGLING_INDEX_IMPORTED
logstash-wccpc-2017.10.10           3 r UNASSIGNED DANGLING_INDEX_IMPORTED
logstash-wccpc-2017.10.10           4 p UNASSIGNED DANGLING_INDEX_IMPORTED
logstash-wccpc-2017.10.10           4 r UNASSIGNED DANGLING_INDEX_IMPORTED
logstash-wccpc-2017.10.10           0 p UNASSIGNED DANGLING_INDEX_IMPORTED
logstash-wccpc-2017.10.10           0 r UNASSIGNED DANGLING_INDEX_IMPORTED
logstash-third-2018.04.04           2 p STARTED    
logstash-third-2018.04.04           2 r STARTED    
logstash-third-2018.04.04           1 p STARTED    
logstash-third-2018.04.04           1 r STARTED    
logstash-third-2018.04.04           3 r STARTED    
logstash-third-2018.04.04           3 p STARTED    
logstash-third-2018.04.04           4 r STARTED    
logstash-third-2018.04.04           4 p STARTED    
logstash-third-2018.04.04           0 r STARTED    

logstash-wccpc-2017.10.10: {
status: "red",
number_of_shards: 5,
number_of_replicas: 1,
active_primary_shards: 0,
active_shards: 0,
relocating_shards: 0,
initializing_shards: 0,
unassigned_shards: 10,
shards: {
0: {
status: "red",
primary_active: false,
active_shards: 0,
relocating_shards: 0,
initializing_shards: 0,
unassigned_shards: 2
},
1: {
status: "red",
primary_active: false,
active_shards: 0,
relocating_shards: 0,
initializing_shards: 0,
unassigned_shards: 2
},
2: {
status: "red",
primary_active: false,
active_shards: 0,
relocating_shards: 0,
initializing_shards: 0,
unassigned_shards: 2
},
3: {
status: "red",
primary_active: false,
active_shards: 0,
relocating_shards: 0,
initializing_shards: 0,
unassigned_shards: 2
},
4: {
status: "red",
primary_active: false,
active_shards: 0,
relocating_shards: 0,
initializing_shards: 0,
unassigned_shards: 2
}
}
},

**Elasticsearch version** (`bin/elasticsearch --version`):
cluster_name: "wcc-es",
nodes: {
gBLas-zVSgapBNr_yZbbbA: {
name: "wcc-es-xietiao-node1",
transport_address: "192.168.199.43:9300",
host: "192.168.199.43",
ip: "192.168.199.43",
version: "5.6.3",
build_hash: "1a2f265",
roles: [
"ingest"
],
process: {
refresh_interval_in_millis: 1000,
id: 19259,
mlockall: true
}
},
nZP4zvXWR8CQ4dWC2zwBzA: {
name: "wcc-es-data-node3",
transport_address: "192.168.199.175:9300",
host: "192.168.199.175",
ip: "192.168.199.175",
version: "5.6.3",
build_hash: "1a2f265",
roles: [
"data",
"ingest"
],
process: {
refresh_interval_in_millis: 1000,
id: 2307,
mlockall: true
}
},
hcJjYs8jSVWobbJ-vL7HKA: {
name: "wcc-es-data-node2",
transport_address: "192.168.199.172:9300",
host: "192.168.199.172",
ip: "192.168.199.172",
version: "5.6.3",
build_hash: "1a2f265",
roles: [
"data",
"ingest"
],
process: {
refresh_interval_in_millis: 1000,
id: 21467,
mlockall: true
}
},
o3euD2vmQKOB5zTN211v_A: {
name: "wcc-es-data-node5",
transport_address: "192.168.200.252:9300",
host: "192.168.200.252",
ip: "192.168.200.252",
version: "5.6.3",
build_hash: "1a2f265",
roles: [
"data",
"ingest"
],
process: {
refresh_interval_in_millis: 1000,
id: 5018,
mlockall: true
}
},
guAdzoacQIuCgC4gg1g1og: {
name: "wcc-es-data-node1",
transport_address: "192.168.199.171:9300",
host: "192.168.199.171",
ip: "192.168.199.171",
version: "5.6.3",
build_hash: "1a2f265",
roles: [
"data",
"ingest"
],
process: {
refresh_interval_in_millis: 1000,
id: 28955,
mlockall: true
}
},
_IzDEfV0QhWR3OTXFAUj3w: {
name: "wcc-es-data-node4",
transport_address: "192.168.200.23:9300",
host: "192.168.200.23",
ip: "192.168.200.23",
version: "5.6.3",
build_hash: "1a2f265",
roles: [
"data",
"ingest"
],
process: {
refresh_interval_in_millis: 1000,
id: 23494,
mlockall: true
}
},
6alVMTJDT8iQfT-mfUbmZw: {
name: "wcc-es-master-node1",
transport_address: "192.168.200.24:9300",
host: "192.168.200.24",
ip: "192.168.200.24",
version: "5.6.3",
build_hash: "1a2f265",
roles: [
"master",
"ingest"
],
process: {
refresh_interval_in_millis: 1000,
id: 23041,
mlockall: true
}
}
}

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
