### ISSUE TITLE
[Enhancement]Last know value option for metrics & column and rows

### ISSUE THREAD

**Issue by Sjaak01** [elastic/elasticsearch#29385]
Hi,

**Last known value option**
There should be an option for metrics to display the last known value for a certain field. This will make it much easier to have Kibana show data that is more static in nature.

Right now its possible to achieve the same by selecting top hits, settings the size to one and adding a filter to make sure the field exists but it would be easier to have a last known value option.

Use case:
I'm polling a piece of equipment at a certain interval. This data is static in nature and I want to sort of re-create the equipment web interface in Kibana by showing the last known data for certain fields.

**Colums and rows**
It would also be great if it was possible to set rows and columns in metric visualizations. Right now if you add a lot of fields things become unreadable and ugly fast. 

If its possible to set the amount of rows and columns it would make showing static data much prettier.

**Comment by cbuescher** [comment]
@Sjaak01 Trying to make sure I understand your request correctly: is this is more of a Kibana UI issue? In which case opening a request in the Kibana repo would be better than here. I think that on the elasticsearch side, getting the "last known value" of a field, the best way indeed it to use a combination of `exists`, top hits with size=1 and sorting by whatever field orders your metric (e.g. a timestamp) is the way to go. Is there anything other than convenience that makes this option not viable for you?

**Comment by danielmitterdorfer** [comment]
No further feedback received. @Sjaak01 if you have the requested information please add it in a comment and we can look at re-opening this issue.
