### ISSUE TITLE
unable to import FilterBuilders for java

### ISSUE THREAD

**Issue by amirensit** [elastic/elasticsearch#29389]
Does FilterBuilders is not supported  with java ?

unable for:
`
import org.elasticsearch.index.query.FilterBuilders.*;
`

**Comment by ywelsch** [comment]
Hi @amirensit, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co) instead. Thank you!
