### ISSUE TITLE
Auto-alias

### ISSUE THREAD

**Issue by makitka2007** [elastic/elasticsearch#29396]
It would be great to have something like auto-aliases, like
```
PUT /aliases/(\w+)_([\w\d]+)
{
  "index": "\\1",
  "routing": "\\2",
  "filter": { "term": { "organization_id" : "\\2" } }
}
```

so, when I am searching/writing data to book_org1 alias, it will use book index and "org1" shard automatically.

**Comment by scottsom** [comment]
Similar to #22472

**Comment by makitka2007** [comment]
yep, I read that issue, thank you for a link. actually I am not completely agree with following points: "limited audience" and "can be implemented application side".
It's a widely-used approach for multi-tenant applications, to use aliases with filters and routing parameters inside instead of manually filtering and routing. It allows combining aliases, by simple specifying /some_resource_org1,some_resource_org2 in search url. and the killer feature is that for some customer we can create a new index instead of its alias, and this customer will work with it's own index without any changes on application level.
but now if we have some new customer, we need to create aliases for all resources and this customer, and if new resource is appeared, then aliases should be created for all existing customers. that's really annoying.
so it will be cool to have at least such aliases for each index, like
```
PUT /some_resource/_aliases/some_resource_([\w\d]+)
{
  "routing": "\\1",
  "filter": { "term": { "organization_id" : "\\1" } }
}
```
so, if i create such virtual alias, I guarantee that no intersections can be with other virtual aliases.
but - still need to check existence of index with this name
so, if I perform search on some_resource_org1 and "some_resource_org1" index exists, then this index is used. if not, than "some_resource" is used with "org1" routing and filter parameters.

**Comment by bleskes** [comment]
@makitka2007 we discussed this on FixItFriday and we are very hesitant of introducing templates to add aliases to indices. The two main reasons are:
1) There are already templates for indices, and we are actively looking for ways to simplify them.  Adding templated aliases will added another layer of complexity and will have to resolve how these two interact.
2) Currently, when someone calls `PUT index/type/1` and we can't resolve the index, we can interpret the first string as a index for auto creation (if not disabled). This is important for time based date. With the introduction of templated aliases, this might not be the case anymore - maybe it matches an alias? for this we will have to introduce a whole new interaction between the coordinating node and the master and there are a few edge cases to address there - for example, with *generic* templates there is no guarantee that the incoming string will actually match anything once the template have run.

All in all, we feel the trade off are wrong and thus closing this as won't fix.
