### ISSUE TITLE
[CI] FlushIT#testSyncedFlushSkipOutOfSyncReplicas failure

### ISSUE THREAD

**Issue by davidkyle** [elastic/elasticsearch#29392]
The error is:
```
java.lang.AssertionError: 
Expected: <2>
     but: was <0>
	at __randomizedtesting.SeedInfo.seed([A4109CF51649FE21:7ADE9ABED536E726]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.indices.flush.FlushIT.testSyncedFlushSkipOutOfSyncReplicas(FlushIT.java:281)
```

Does not reproduce:
```
./gradlew :server:integTest \
  -Dtests.seed=A4109CF51649FE21 \
  -Dtests.class=org.elasticsearch.indices.flush.FlushIT \
  -Dtests.method="testSyncedFlushSkipOutOfSyncReplicas" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-AU \
  -Dtests.timezone=Asia/Macau
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=opensuse/884/console

**Comment by dnhatn** [comment]
CI Log: [testSyncedFlushSkipOutOfSyncReplicas.txt](https://github.com/elastic/elasticsearch/files/1879899/testSyncedFlushSkipOutOfSyncReplicas.txt)

**Comment by bleskes** [comment]
@dnhatn did you get anywhere with this?

**Comment by dnhatn** [comment]
A similar instance [testDoNotRenewSyncedFlushWhenAllSealed.txt](https://github.com/elastic/elasticsearch/files/1918013/testDoNotRenewSyncedFlushWhenAllSealed.txt)

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/2323/console

**Comment by dnhatn** [comment]
@bleskes I will be looking at this tomorrow.

**Comment by jkakavas** [comment]
Another instance of this today

```
FAILURE 0.99s J0 | FlushIT.testDoNotRenewSyncedFlushWhenAllSealed <<< FAILURES!
10:53:05    > Throwable #1: java.lang.AssertionError: 
10:53:05    > Expected: <3>
10:53:05    >      but: was <0>
10:53:05    > 	at __randomizedtesting.SeedInfo.seed([B2D1D0AA1E7F53C3:EFEE892888111141]:0)
10:53:05    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
10:53:05    > 	at org.elasticsearch.indices.flush.FlushIT.testDoNotRenewSyncedFlushWhenAllSealed(FlushIT.java:313)
10:53:05    > 	at java.lang.Thread.run(Thread.java:748)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1565/consoleFull

**Comment by dnhatn** [comment]
@bleskes You're right - it's not related to the cluster state. I got a new failure that shows that actual reason.

>   1> [2018-05-02T23:10:32,145][INFO ][o.e.i.f.FlushIT          ] Third seal: Total shards: [2], failed: [true], reason: [[1] ongoing operations on primary], detail: []

Log: [flush.txt](https://github.com/elastic/elasticsearch/files/1967623/flush.txt)
CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+ccr+feature-branch-periodic/636/console

**Comment by bleskes** [comment]
@dnhatn cool. Any idea what the operation is?

**Comment by jtibshirani** [comment]
A similar failure came up today -- the build information is below. While this is being resolved, I plan to mute `testSyncedFlushSkipOutOfSyncReplicas` and `testDoNotRenewSyncedFlushWhenAllSealed`.

CI link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+multijob-unix-compatibility/os=oraclelinux/55/console

Command to reproduce (does not reproduce for me locally):

```
./gradlew :server:integTest \
  -Dtests.seed=A189D899652C33F6 \
  -Dtests.class=org.elasticsearch.indices.flush.FlushIT \
  -Dtests.method="testDoNotRenewSyncedFlushWhenAllSealed" \
  -Dtests.security.manager=true \
  -Dtests.locale=sk \
  -Dtests.timezone=Etc/GMT-9
```

Stack trace:
```
05:27:18 FAILURE 0.61s J1 | FlushIT.testDoNotRenewSyncedFlushWhenAllSealed <<< FAILURES!
05:27:18    > Throwable #1: java.lang.AssertionError: 
05:27:18    > Expected: <2>
05:27:18    >      but: was <0>
05:27:18    > 	at __randomizedtesting.SeedInfo.seed([A189D899652C33F6:FCB6811BF3427174]:0)
05:27:18    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
05:27:18    > 	at org.elasticsearch.indices.flush.FlushIT.testDoNotRenewSyncedFlushWhenAllSealed(FlushIT.java:326)
05:27:18    > 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bleskes** [comment]
@dnhatn can you please prioritize this? Failing tests are not good.

**Comment by dnhatn** [comment]
@bleskes Sorry for the delay. Looking at this now.

**Comment by dnhatn** [comment]
@bleskes 
These tests failed because of ongoing operations on the primary which means someone was holding an index shard permit. I spent several hours on this but could not figure out the acquirer. 

I have re-enabled these tests (in https://github.com/elastic/elasticsearch/commit/d96bc5b22766a3e5d2c7e5c0edfcf0265853e08d ) with a trace log of the permit holders when checking inflight operations. If this fails again, we will know the acquirer.

**Comment by dnhatn** [comment]
Another instance https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1998/console
The test failed because the global checkpoint sync acquired a shard permit while the synced-flushing was happening. I am looking at this again.

```
1> [2018-05-30T04:00:48,248][TRACE][o.e.i.f.SyncedFlushService] [node_s1] in flight operations 1, acquirers [GlobalCheckpointSyncAction.Request{shardId=[test][0], timeout=1m, index='test', waitForActiveShards=1}
1> 	at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:229)
1> 	at org.elasticsearch.index.shard.IndexShard.acquirePrimaryOperationPermit(IndexShard.java:2178)
1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction.acquirePrimaryShardReference(TransportReplicationAction.java:968)
1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction.access$500(TransportReplicationAction.java:98)
1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncPrimaryAction.doRun(TransportReplicationAction.java:318)
1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:293)
1> 	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:280)
1> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
1> 	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:656)
1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:724)
1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
1> 	at java.lang.Thread.run(Thread.java:748)]

1> [2018-05-30T04:00:48,248][INFO ][o.e.i.f.FlushIT          ] Third seal: Total shards: [2], failed: [true], reason: [[1] ongoing operations on primary], detail: []
```
