### ISSUE TITLE
Unable to check non-pending tasks with cluster/monitor privilege

### ISSUE THREAD

**Issue by jgdxtv2** [elastic/elasticsearch#29407]
**Elasticsearch version** 6.2.0

**Plugins installed**: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.0 with x-pack

**JVM version** docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.0

**OS version** Docker

**Description of the problem including expected versus actual behavior**:
What happens:
A user with cluster/monitor privileges can GET pending tasks via _tasks. When the task is done, the user can no longer GET the task, it returns 403. No cluster privilege allows this call for non-superusers.

What should happen:
Either the documentation should be updated with a reference to done tasks, or the cluster/monitor privilege should include non-pending tasks.

In any case, the current docs/behaviour is unexpected.

**Steps to reproduce**:

 1. Let a user have cluster/monitor privilege AND sufficient index privileges for index _a_ and _b_ such that the user can reindex _a_ into _b_.
 2. Reindex _a_ into _b_ with `wait_for_completion=false`
 3. While the task is pending/running, `GET _tasks/<returned task id>`
 4. Wait for task completion.
 5. `GET _tasks/<task id from before>`

**Comment by jgdxtv2** [comment]
I was wrong about the cluster/manage privilege, it does not grant access to reading non-pending tasks.

**Comment by jasontedor** [comment]
This repository is for open source Elasticsearch only yet your issue involves X-Pack. For that, please use the [forum](https://discuss.elastic.co).
