### ISSUE TITLE
QueryStringQueryBuilder equals == true when query is not equal

### ISSUE THREAD

**Issue by jecstarinnovations** [elastic/elasticsearch#29403]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.3

**Plugins installed**: [] D.N.A.

**JVM version** (`java -version`): openjdk version "1.8.0_161"

**OS version** (`uname -a` if on a Unix-like system): Linux jecstar-laptop 4.15.13-300.fc27.x86_64 #1 SMP Mon Mar 26 19:06:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: The doEquals() method in the org.elasticsearch.index.query.QueryStringQueryBuilder is not working properly. When two different instances with different queries are compared by the equals method everything works as expected (equals() == false). 
When adding an equal timezone id to both instances of the QueryStringQueryBuilder, the equals() method will return true despite the query values are not equal. This is caused because parenthesis are missing around the statement at line 928. 

**Steps to reproduce**:
For a complete example see the attached gradle project.
[querystringquerybug.tar.gz](https://github.com/elastic/elasticsearch/files/1881442/querystringquerybug.tar.gz)
 

**Provide logs (if relevant)**: D.N.A.

**Comment by dnhatn** [comment]
@jecstarinnovations This is indeed a bug. Thanks for reporting it.

**Comment by colings86** [comment]
@jecstarinnovations thanks for reporting this bug. I've raised https://github.com/elastic/elasticsearch/pull/29406 which should fix this

**Comment by colings86** [comment]
@jecstarinnovations thanks for raising this issue, I've merged a fix into the master branch and will back port to the 6.x branch shortly
