### ISSUE TITLE
ElasticSearch 5.3 returns 0 hits under high concurrency conditions

### ISSUE THREAD

**Issue by INRIX-Trang-Nguyen** [elastic/elasticsearch#29416]
**Elasticsearch version**: 5.3

**Plugins installed**: [Kibana]

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): AWS ElasticSearch service

Cluster size:
4 i3.2xlarge.elasticsearch worker nodes
2 shards/index
Index size: ~50-60GB primary

**Description of the problem including expected versus actual behavior**:
Under high concurrency conditions on a Spark EMR cluster, elasticsearch returns 0 hits for a query that would succeed otherwise. The query we are using involves geospatial joins across pre-indexed geoshapes.
We retry the requests when encountering this condition and the retries sometimes work, sometimes not.

**Steps to reproduce**:
Attached sample query

[ElasticSearchNoHitsLog.txt](https://github.com/elastic/elasticsearch/files/1884761/ElasticSearchNoHitsLog.txt)

**Comment by INRIX-Trang-Nguyen** [comment]
These indexes have all been refreshed. They were created a while back.
Thanks, I can move to the forum.

**Comment by INRIX-Trang-Nguyen** [comment]
I had filed another concurrency issue involving pre-indexed shapes that will go out in 6.3. I don't believe it is related but just in case, I'll reference it here: https://github.com/elastic/elasticsearch/issues/28456

**Comment by dakrone** [comment]
Since this has moved to the forum for now, I am going to close it. We can re-open if it turns into something different, thanks!
