### ISSUE TITLE
Investigate multiple unit intervals in date_histogram using java.time

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#29411]
Spilt out from #28432.

This issue is also stalled until https://github.com/elastic/elasticsearch/issues/27330 is complete.

Currently if multiple unit intervals (e.g. "2d" as opposed to "1d") are used in the date histogram aggregation we create fixed duration buckets instead of calendar interval buckets. For a 2d interval this means that the buckets represent `2 * 24 * 60 * 60 * 1000 = 172800000 milliseconds` instead of representing two days starting at midnight the first day and ending just before midnight the third day.

This is not a great API experience and it would be better for all intervals to be calendar intervals. We have tried this before using Joda time but it was not possible to implement. Very preliminary investigations into java.time seem to suggest there is more of a chance of getting this working so once the move to java.time is complete we should investigate making all intervals in the date_histogram calendar intervals.

**Comment by polyfractal** [comment]
Related #33727

**Comment by astefan** [comment]
@polyfractal now that https://github.com/elastic/elasticsearch/issues/27330 is done, could this issue be back on our radar?

**Comment by polyfractal** [comment]
@astefan Definitely :)  Especially since https://github.com/elastic/elasticsearch/pull/33727 merged, calendar intervals are "contained" to `calendar_interval` and it should have less unanticipated impact.

That said I personally have no idea how or if we can do it with java time.  But I agree it's something we should look into again.

**Comment by wchaparro** [comment]
This is not something we plan to implement in the near future in aggregations, and has been superceded by our focus on ESQL. Closing as not planned. If your feel strongly about this one, please let us know.
