### ISSUE TITLE
testFactoryValidationForMultipleScriptingTypes fails on 6.x

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#29435]
Error Message:

Unexpected exception type, expected XContentParseException but got 
ElasticsearchParseException[Only one of [id] or [source] may be configured]

CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1516/testReport/org.elasticsearch.ingest.common/ScriptProcessorFactoryTests/testFactoryValidationForMultipleScriptingTypes/

**Comment by dakrone** [comment]
Resolved by a6301be5fc3c5c6760b3d7ca269a984396a5d6bb
