### ISSUE TITLE
Email issue.

### ISSUE THREAD

**Issue by naliniranjan82** [elastic/elasticsearch#29443]
**Describe the feature**:
In-spite  Elastics watcher getting successful executed not reviving email.

**Email host detail in elasticsserach.yml**
*xpack.notification.email.account:
    socgen_account:
        profile: fidessa
        smtp:
            auth: true
            starttls.enable: true
            host: smtp-*******        
            user: *********
            password: *******
*
**Watcher response**
*{
  "watch_id": "system_process_watch",
  "node": "TEfIfaz8R16BbkeH9ah1TA",
  "state": "execution_not_needed",
  "status": {
    "state": {
      "active": true,
      "timestamp": "2018-04-10T07:28:36.198Z"
    },
    "last_checked": "2018-04-10T07:32:36.390Z",
    "actions": {
      "email_administrator": {
        "ack": {
          "timestamp": "2018-04-10T07:28:36.198Z",
          "state": "awaits_successful_execution"
        }
      }
    },
    "execution_state": "execution_not_needed",
    "version": -1
  },
  "trigger_event": {
    "type": "schedule",
    "triggered_time": "2018-04-10T07:32:36.390Z",
    "schedule": {
      "scheduled_time": "2018-04-10T07:32:36.343Z"
    }
  },
  "input": {
    "search": {
      "request": {
        "search_type": "query_then_fetch",
        "indices": [
          "metricbeat-*"
        ],
        "types": [],
        "body": {
          "size": 0,
          "query": {
            "match": {
              "metricset.name": "process"
            }
          }
        }
      }
    }
  },
  "condition": {
    "compare": {
      "system.process.cpu.total.norm.pct": {
        "gt": 0
      }
    }
  },
  "result": {
    "execution_time": "2018-04-10T07:32:36.390Z",
    "execution_duration": 2,
    "input": {
      "type": "search",
      "status": "success",
      "payload": {
        "_shards": {
          "total": 2,
          "failed": 0,
          "successful": 2,
          "skipped": 0
        },
        "hits": {
          "hits": [],
          "total": 11746,
          "max_score": 0
        },
        "took": 0,
        "timed_out": false
      },
      "search": {
        "request": {
          "search_type": "query_then_fetch",
          "indices": [
            "metricbeat-*"
          ],
          "types": [],
          "body": {
            "size": 0,
            "query": {
              "match": {
                "metricset.name": "process"
              }
            }
          }
        }
      }
    },
    "condition": {
      "type": "compare",
      "status": "success",
      "met": false,
      "compare": {
        "resolved_values": {
          "system.process.cpu.total.norm.pct": null
        }
      }
    },
    "actions": []
  },
  "messages": []
}*   

**Elasticsearch version** (`bin/elasticsearch --version`):
6.2.2
**Plugins installed**: [X-pack]

**JVM version** (`java -version`):
1.8.0_101-b13
**OS version** (`uname -a` if on a Unix-like system):
Linux ******** 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2086_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by tvernum** [comment]
Could you please ask this question on our [discuss forum](https://discuss.elastic.co/c/x-pack) where we can provide better support. Those forums are designed to support the kinds of conversations that are necessary for this sort of troubleshooting and problem diagnosis.

Elastic uses GitHub issues for tracking clearly identified bugs and feature requests. Since it does not appear that there is a specific bug identified in your issue, I'm going to close this ticket, but I'm sure someone will be able to help you work through this issue on the [forums](https://discuss.elastic.co/c/x-pack) .

Thank you.
