### ISSUE TITLE
Allow to explain how analyzer was composed

### ISSUE THREAD

**Issue by medcl** [elastic/elasticsearch#29445]
Currently, we have many nice built-in analyzers and also can custom our own, they are various.

For customized analyzer, we can get the definition from the index settings, and for built-in one, we need to navigate to the docs or refer to the source code.

Sometimes, for better understanding the analysis result, we may hope to know what is the components of an analyzer, specifically, which [char_filters]/tokenizer/[filters] are behind, so how about provide a API, allow user to explain the analyzer by provide the name of the analyzer？

**Comment by jpountz** [comment]
This is something that we can't even do internally: once analyzers are created there is no way to know their components. This feature would have a significant cost, while we already document how they are built. I don't think we should add this feature.

**Comment by nik9000** [comment]
Since we already document these I think we're safe not to implement something special for this. I *do* think we should add some test for this and we should be more consistent with how we tell people how they can be recreated. So I filed #29499 which I consider a replacement for this one.
