### ISSUE TITLE
[CI] MovAvgIT.testHoltWintersValuedField fails comparing moving average

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#29456]
On master, `MovAvgIT.testHoltWintersValuedField` is failing with the following:

```
  2> REPRODUCE WITH: ./gradlew :server:integTest -Dtests.seed=CE05B83DF1BEA283 -Dtests.class=org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT -Dtests.method="testHoltWintersValuedField" -Dtests.security.manager=true -Dtests.locale=en-ZA -Dtests.timezone=America/Scoresbysund
FAILURE 0.30s | MovAvgIT.testHoltWintersValuedField <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: [value] movavg does not match expected [-3.472856236891249E11 vs -3.4728562185648425E11] expected:<-3.472856236891249E11> but was:<-3.4728562185648425E11>
   > 	at __randomizedtesting.SeedInfo.seed([CE05B83DF1BEA283:508E63695CA12AD]:0)
   > 	at org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT.assertBucketContents(MovAvgIT.java:1307)
   > 	at org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT.testHoltWintersValuedField(MovAvgIT.java:651)
   > 	at java.lang.Thread.run(Thread.java:748)
```

This does reproduce for me with:

```
./gradlew :server:integTest -Dtests.seed=CE05B83DF1BEA283 -Dtests.class=org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT -Dtests.method="testHoltWintersValuedField" -Dtests.security.manager=true -Dtests.locale=en-ZA -Dtests.timezone=America/Scoresbysund
```

**Comment by polyfractal** [comment]
I'm going to silence this test temporarily while we figure out what to do with it regarding the double comparison code that was removed in #29409

**Comment by jimczi** [comment]
I am reopening this issue and will silent these tests again since we have failures with the last patch:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1528/console
Reproduces with:
````
gradlew :server:integTest -Dtests.seed=3EE75FEEDFF871F4 -Dtests.class=org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT -Dtests.method="testHoltWintersValuedField" -Dtests.security.manager=true -Dtests.locale=fr -Dtests.timezone=America/Catamarca
````

**Comment by polyfractal** [comment]
Thanks @jimczi 

Bleh, I think this is a copy/paste typo.. the second assertion should be checking the value not the count.  Sorry for the noise.  I'll let it run on my machine for most of the day to make sure it's actually fixed this time :)

**Comment by jimczi** [comment]
FYI I just ran `./gradlew :server:integTest -Dtests.class=org.elasticsearch.search.aggregations.pipeline.moving.avg.MovAvgIT -Dtests.method="testHoltWintersValuedField" -Dtests.security.manager=true -Dtests.locale=fr -Dtests.timezone=America/Catamarca -Dtests.iters=10000` without the typo and it didn't fail so 👍 to push the fix.

**Comment by colings86** [comment]
@polyfractal can this be closed now? Did you push the second fix?
