### ISSUE TITLE
Create document API _id not as per documentation

### ISSUE THREAD

**Issue by kolapkardhaval** [elastic/elasticsearch#29459]
**Describe the feature**: _id generated is not a UUID as expected per the document

**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.1

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): OSX

**Description of the problem including expected versus actual behavior**:
As per the documentation, https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html, auto generation id should give a UUID like 6a8ca01c-7896-48e9-81cc-9f70661fcb32. However, it gives YnwksmIBSI4iEKmi9Xrs which looks like a GUID.

**Comment by jasontedor** [comment]
I opened #29461.
