### ISSUE TITLE
Reported GC collectors names contains spaces using Zing JVM

### ISSUE THREAD

**Issue by ebuildy** [elastic/elasticsearch#29457]
**Elasticsearch version**

6.2

**Plugins installed**: []

**JVM version**:

Zing JVM - 1.8.0-zing_18.03.0.0

**OS version**:

Linux

**Description of the problem including expected versus actual behavior**:

The _nodes/stats endpoint is reporting:

```
"gc": {
"collectors": {
"GPGC New": {
"collection_count": 148,
"collection_time_in_millis": 19336
},
"GPGC Old": {
"collection_count": 11,
"collection_time_in_millis": 5688
}
}
}
```

Collectors name should be in snake case like "GPGC New" ==> "gpgc_new", so it's possible to use it with for exemple metricbeat and Kibana.

I remember Shay Banon has said 

> "Spaces in field names will lead to all sorts of problems, its best/crucial to avoid them.".

**Steps to reproduce**:

 1. Use Zing JVM
 2. ``curl localhost:9200/_nodes/stats/jvm``

**Comment by jasontedor** [comment]
For Elasticsearch 6.x we do not support and do not test on Zing so I would say that we are unlikely to make any changes here. I will raise it for discussion with our core/infra team.

**Comment by ebuildy** [comment]
Ho :/ Actually we are running ES 1.5.2 with Zing, because Zing helps a lot to reduce long GC pauses, so you said ES 6.0 will not work at all with Zing?

**Comment by jasontedor** [comment]
I am not necessarily saying that it doesn’t work; I am saying that it is not supported by us meaning that we do not do any testing on Zing, and we do not address issues due to Zing.

**Comment by jasontedor** [comment]
We discussed this internally and agreed that since we do not support Zing, we do not want to go down the path of making product changes that could be construed as us supporting Zing (it's about setting precedent). As such, I am going to close this issue.
