### ISSUE TITLE
SAML integration with elasticsearch 5.6

### ISSUE THREAD

**Issue by RanganathNangineni** [elastic/elasticsearch#29464]
I have a requirement to integrate x-pack on elasticsearch 5.6 with SAML 2.0.

Is this feature available in 5.6 ?

**Comment by albertzaharovits** [comment]
> Is this feature available in 5.6 ?

@RanganathNangineni SAML is available in the [6.2 release](https://www.elastic.co/blog/elasticsearch-6-2-0-released) .
