### ISSUE TITLE
Using custom query builders in standard queries

### ISSUE THREAD

**Issue by Tobsucht** [elastic/elasticsearch#29466]
As I didn't get an answer in the forums and IRC, I'm trying this as an issue:

Scenario:
I've build a custom analyzer which injects a custom attribute that contains informations whether a token is a good candidate for a fuzzy query or not and als computes a prefix length which is as long as possible.

I want that this information is used within the query builder, e.g. whenever a term query is possible the attribute should be read and depending on the information replaced with a fuzzy query.

Problem: 
Is there any way to use the standard queries like "matchQuery" or "multiMatchQuery" but customize the used querybuilder?

https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/search/MatchQuery.java#L272

If I'm not missing anything this is not possible. If so: Is there any reason, why this isn't customizable? E.g. for a query the user can set the name for a registered custom querybuilder.

The solution I'm currently working on is that I define my own query, which just extends the MatchQuery and overrides the parse method. That way I can use my own query builder.
But for getting that working, I have to define my own query(+ the builder for the java API).

Is that solution stupid/inconvenient or a valid feature request for customizing query builders?

**Comment by jimczi** [comment]
@Tobsucht thanks for opening a discussion in the forum:
https://discuss.elastic.co/t/use-lucene-query-within-es-api/126575

I answered there directly so I hope that you don't mind if I close this issue. Let's continue the discussion in the forum where we can better understand what you're trying to do before thinking of a solution that requires a code change ;).
