### ISSUE TITLE
Exclude index failure in the cat indices API

### ISSUE THREAD

**Issue by sachin-frayne** [elastic/elasticsearch#29478]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.3

**Plugins installed**: [x-pack]

**JVM version** (`java -version`): 1.8.0_162

**OS version** (`uname -a` if on a Unix-like system): Darwin MacBook-Pro.local 17.5.0 Darwin Kernel Version 17.5.0; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**: I get an index_not_found_exception when I run the following command;
`GET _cat/indices/my_index*,-my_index2?v` 
but not the following;
`GET _cat/indices/my_index*,-my*index2?v`.

**Steps to reproduce**:

1. Create some test indices:

```
PUT my_index1
PUT my_index2
```

2. This command returns the error:

```
GET _cat/indices/my_index*,-my_index2?v
```

**The response:**

```
{
  "error": {
    "root_cause": [
      {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_or_alias",
        "resource.id": "my_index2",
        "index_uuid": "_na_",
        "index": "my_index2"
      }
    ],
    "type": "index_not_found_exception",
    "reason": "no such index",
    "resource.type": "index_or_alias",
    "resource.id": "my_index2",
    "index_uuid": "_na_",
    "index": "my_index2"
  },
  "status": 404
}
```

3. However this does not:

```
GET _cat/indices/my_index*,-my*index2?v
```

**The response:**

```
health status index     uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   my_index1 D3VDEgzNQsusMfe3gGU-QQ   5   1          0            0      1.1kb          1.1kb
```

4. This appears to only affect the cat indices API, I have not tested all APIs however this one does work as expected:

```
GET my_index*,-my_index2
```

**The response:**

```
{
  "my_index1": {
    "aliases": {},
    "mappings": {},
    "settings": {
      "index": {
        "creation_date": "1523454664826",
        "number_of_shards": "5",
        "number_of_replicas": "1",
        "uuid": "D3VDEgzNQsusMfe3gGU-QQ",
        "version": {
          "created": "6020399"
        },
        "provided_name": "my_index1"
      }
    }
  }
}
```

I have tried this on https://cloud.elastic.co as well.

**Provide logs (if relevant)**:

**Comment by NaveenGurram** [comment]
@colings86  -- what should be the correct behavior for this?  throw or not to throw exception.

**Comment by martijnvg** [comment]
I think this api should expose `indices_options` parameter, so the strictness can be changed.
Also perhaps the default (which is currently strict) should be changed to be more lenient here.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
