### ISSUE TITLE
sort failed

### ISSUE THREAD

**Issue by yjhjeys** [elastic/elasticsearch#29475]
`            body = {
                "query": {
                    "query_string": {
                        "query": query,
                        "default_operator": "AND",
                        "analyzer": "standard"
                    },
                },
                "sort": {
                    "_script" : {
                       "script" : "doc['ID'].value.length()",
                       "type" : "number",
                       "order" : "asc"
                    }
                },
                "from": offset,
                "size": size
            }`

sort is not work, Is there a problem of the configuration?

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
