### ISSUE TITLE
Distinct Top Hit

### ISSUE THREAD

**Issue by GregBoero** [elastic/elasticsearch#29474]
Hi ,

Describe the feature:

The current TopHit metric just Concatenate/Sum/Max.. the last N :
with Concatenate it produce with a data-set {A,A,A,B,C,B,E,F,G} and with a limit at 5 : A,A,A,B,C.

It would be nice if we could have a distinct option :
with Distinct Concatenate it produce with a data-set {A,A,A,B,C,B,E,F,G} and with a limit at 5 : A,B,C,E,F.

Thanks and Regards

**Comment by jimczi** [comment]
This seems related to how Kibana exposes the `top_hit` aggregation, the visualization concatenates the value found in the top_hits but this is done in the client side not in Elasticsearch.
Though this is already possible to achieve this by adding a parent `terms` aggregation on the distinct field so you probably don't need the `top_hits` aggregation at all. You can use a custom `order` for the `terms` aggregation:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-order
.. and returns the last N values based on the metric that you want (`max`, `min`, ...).
I chatted with @timroes which said that the top_hit visualization (or the terms visualization) in Kibana could be enhanced to allows a concatenated view of the buckets so I am going to close this issue and you can probably ask him to reopen your issue in Kibana repo ;).
