### ISSUE TITLE
_id Encoding is Base64 for UUID v4 but decoding is to UUID v3

### ISSUE THREAD

**Issue by kolapkardhaval** [elastic/elasticsearch#29498]
_id encoding is Base64 for UUID v4 but decoding is to UUID v3

**Elasticsearch version** (`bin/elasticsearch --version`):
6.2.1
**Plugins installed**: []

**JVM version** (`java -version`):
1.8
**OS version** (`uname -a` if on a Unix-like system):
OSX
**Description of the problem including expected versus actual behavior**:

_id encoding is Base64 for UUID v4 but decoding is to UUID v3. The decoding should also be to v4.

**Comment by talevy** [comment]
Hi @kolapkardhaval. Would you mind sharing exactly what you mean when you say the UUIDs are being decoded using UUIDv3?

As of 6.0, we use a version of UUIDs that is not necessarily compatible with the "version4" spec.

https://github.com/elastic/elasticsearch/blob/263349f6282d90343f44888a2133e826e5f82fde/server/src/main/java/org/elasticsearch/action/index/IndexRequest.java#L490

We are leveraging a time-based option which resulted in better performance than the traditional random UUID.

**Comment by kolapkardhaval** [comment]
@talevy , Thank you very much. So basically, we have elasticsearch and postgres as our databases. We get the ID from elasticsearch which is a base 64 encoded UUID. We would like to decode this UUID and store it in postgres as postgres supports UUID as a primary key. So, I do this:

        String base64UUID=main.getBase64UUID();
        System.out.println("Base 64 UUID is "+base64UUID);
        Base64.Decoder decoder = Base64.getDecoder();
        byte[] decodedByteArray = decoder.decode(base64UUID);
        UUID uuid=UUID.nameUUIDFromBytes(decodedByteArray);

But now to get the base64 encoded UUID back from the UUID is where I am failing. I don't know how to do that. I need this to verify that I have created the right UUID in the first place and if I need to to the mapping of records in elasticsearch and postgres

**Comment by talevy** [comment]
@kolapkardhaval I think I understand. This is not an issue with our UUID, this is more of an issue with the expectation that we used the same library as you for UUID, so that you can decode effectively.

```UUID uuid=UUID.nameUUIDFromBytes(decodedByteArray);```

the above would not be expected to work since the default UUID generator I linked to above does not follow the same spec that would allow the UUID library to reconstruct itself from the byte array.

You would have to resolve this another way. We are not using the md5 hashing scheme for this

**Comment by kolapkardhaval** [comment]
@talevy Yes, helps a lot in our architecture decision. I guess, we will have to go with String for postgres.
