### ISSUE TITLE
Termvector slow performance

### ISSUE THREAD

**Issue by lahloug** [elastic/elasticsearch#29510]
Hi !
 I am using elasticsearch to catch n-grams on text. Here is my mapping : 
```
    mapp = {'settings': {
                'number_of_shards': 1,
                'analysis': {
                    'analyzer': {
                        'body_analyzer': {
                            "type": "custom",
                            "char_filter": ["html_strip"],
                            "tokenizer": "standard",
                            "filter": ["standard",
                                       "lowercase",
                                       "filter_shingle"]
                        }
                    },
                    "filter": {
                        "filter_shingle": {
                            "type": "shingle",
                            "max_shingle_size": 6,
                            "min_shingle_size": 2,
                            "output_unigrams": "true"
                        }
                    }
                }
            }, 
           'mappings': {

     'article': {
                    'properties': {
                        'body': {'type': 'text',
                                 'analyzer': 'body_analyzer',
                                 'term_vector': 'with_positions_offsets',
                                 'store': "true"}}}}}
```

I have so far several thousands of texts with average length of 200 words.
The thing is, using termvectors to retrieve documents count is unusually slow. Here is the query I do using python client : 

```
    for art_id in [articles_ids[i: i+20] for i in range(0,
                                                        len(articles_ids),
                                                        20)]:
        t3 = time()
        res = cnx.mtermvectors(index=index_name, doc_type='article', ids=art_id,
                               field_statistics=False,
                               positions=False,
                               offsets=False,
                               payloads=False,
                               fields='body')
        t4 = time()
        get_res += t4 - t3
```
It takes ~3 seconds to execute on 2700 articles.

Since our filter ask for 1 gram up to 6 grams, each document has ( 6  * 200 = 1200) 1200 keys. That may be the reason of its slow performance. But we only want to see the count frequencies of a small batch of words.
Is it possible to store dynamically only those specific words? Or ask elasticsearch to filter the keys on specific words in the termvector request ?

**Comment by jpountz** [comment]
I'm not too surprised that this is slow.

> But we only want to see the count frequencies of a small batch of words.

Maybe the `keep` filter? https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-keep-words-tokenfilter.html

**Comment by lahloug** [comment]
Hi @jpountz Thanks for your quick reply ! As far as I understood the keep words is set on the mapping. But my application requires to have a dynamic list of word. So if I use that, I would need to reindex everytime I change the list of word I try to keep which is not good ..

**Comment by jpountz** [comment]
I'm not fully understanding, do you mean that you need to find all documents that have at least X occurences of word1 and Y occurrences of word2?

**Comment by jpountz** [comment]
Could you do a `terms` aggregation and then merge terms that are synonyms together? You could use the `include` parameter to only get counts for a specific set of terms.

It won't work by default since we disallow fielddata on text fields, but if this is your need then we can think of ways to make this work.

**Comment by jimczi** [comment]
No further feedback, hence closing
