### ISSUE TITLE
Convert Php MYSQL query into ElasticSearch Query 

### ISSUE THREAD

**Issue by mrshidashrf** [elastic/elasticsearch#29512]
i'm working on elastic search but not expert in making elastic search queries. find my query bellow and if possible to convert into elasticsearch query then take thanks in advance.

`SELECT `currency`.`id` as `cur_id`, `currency`.`currency_name` as `cur_name`, `currency`.`currency_code` as `cur_code`, `currency`.`currency_slug` as `cur_slug`, `currency`.`logo` as `cur_logo`, `currency`.`added_date` as `cur_added_date`, `currency`.`mineable_or_not` as `mineable_or_not`, `currency`.`market_cap` as `cur_market_cap`, `currency`.`circulating_supply` as `cur_circulating_supply`, `currency`.`max_supply` as `cur_max_supply`, `currency`.`total_supply` as `cur_total_supply`, `currency`.`market_cap` as `ng_cur_market_cap`, `currency`.`added_date` as `ng_cur_added_date`, `currency`.`circulating_supply` as `ng_cur_circulating_supply`, `calculations`.`volume_1hour` as `cal_volume_1hour`, `calculations`.`volume_24hour` as `cal_volume_24hour`, `calculations`.`volume_168hour` as `cal_volume_168hour`, `calculations`.`volume_720hour` as `cal_volume_720hour`, `calculations`.`volume_24hour_btc` as `cal_volume_24hour_btc`, `calculations`.`current_price` as `cal_current_price`, `calculations`.`percentage_change` as `cal_percentage_change_24h`, `calculations`.`percentage_change_1h` as `cal_percentage_change_1h`, `calculations`.`percentage_change_168h` as `cal_percentage_change_168h`, `calculations`.`volume_24hour` as `ng_cal_volume_24hour`, `calculations`.`current_price` as `ng_cal_current_price` FROM `currency` JOIN `calculations` ON `calculations`.`currency_id` = `currency`.`id` WHERE `calculations`.`update_status` = 1 AND `currency`.`currency_type` != 3 AND `calculations`.`update_status` = 1 AND `currency`.`status` = 1 ORDER BY `market_cap` DESC LIMIT 100
`

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
