### ISSUE TITLE
Change path of jvm.options

### ISSUE THREAD

**Issue by d-malko** [elastic/elasticsearch#29521]
Elastiksearch 6.2.3
java 1.8
Good day! Thank you for great application.
Please advice how can I  change default location of jvm.options file. I can't find this options in documentation.

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by d-malko** [comment]
Thank you sorry!
