### ISSUE TITLE
apt-get upgrade bump version to elasticsearch 6.2.4

### ISSUE THREAD

**Issue by larrywax** [elastic/elasticsearch#29564]
**Elasticsearch version** : `Version: 6.2.3, Build: c59ff00/2018-03-13T10:06:29.741383Z, JVM: 1.8.0_162`

**Plugins installed**: ["discovery-ec2", "repository-s3", "search-guard-6", "x-pack"]

**JVM version**: `openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.162-b12, mixed mode)`

**OS version**: `Linux 4.4.0-1052-aws #61-Ubuntu SMP Mon Feb 12 23:05:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:
Running `apt-get upgrade` update elasticsearch to version `6.2.4`, that doesn't seem to be already released. 
The package doesn't observe pinning to version `6.2.3` (was installed with the official ansible playbook that does an `apt-mark hold elasticsearch`)
I can't understand if this is a misbehaviour of my system (a very strange one) or if you have some misconfiguration on the apt source in this moment.

**Steps to reproduce**:
Install elasticsearch 6.2.3 using this repo: `deb https://artifacts.elastic.co/packages/6.x/apt stable main`
Do an `apt-mark hold elasticsearch`
Do an `apt-get upgrade`
Check elasticsearch version: `Version: 6.2.4, Build: ccec39f/2018-04-12T20:37:28.497551Z, JVM: 1.8.0_162`

Thanks

**Comment by jasontedor** [comment]
We are in the process of releasing 6.2.4 right, it is live in the repository although we are still publishing doc updates, blog posts, etc. That 6.2.4 build that you have there is the official build.
