### ISSUE TITLE
Metric aggs support/workaround for sub aggregations

### ISSUE THREAD

**Issue by jstrassb** [elastic/elasticsearch#29580]
With newer development in the stack could their be a way to achieve for example [top_hits and sub-aggregations ](https://github.com/elastic/elasticsearch/issues/16537) without client-side processing? I am currently hitting this issue in use case.
Thanks for any pointers!

**Comment by polyfractal** [comment]
What sort of sub-aggs are you wanting to run on the top_hits?  Metric style aggs (min, max, avg, etc)?  Or are you using top_hits for sorting purposes?

The new [bucket_sort](https://www.elastic.co/guide/en/elasticsearch/reference/6.x/search-aggregations-pipeline-bucket-sort-aggregation.html) pipeline agg can help in some of the sorting use-cases.

For metrics, you can sometimes re-arrange your aggregation tree in a way to get what you need, without relying on top_hits.  

The limitation around sub-aggs and top_hits still exists, nothing has changed on that front in the framework.

**Comment by jstrassb** [comment]
Thanks for the input @polyfractal! They do indeed want to have a sum aggregation on the top_hits.

Basically they want to use top_hits to get the most recent documents only and then sum up their sizes. E.g.
```
  { "name": "foo", "size": 123, "tstamp": "2018-01-01" }
  { "name": "foo", "size": 456, "tstamp": "2018-02-02" }
  { "name": "bar", "size": 789, "tstamp": "2018-01-01" }     
``` 
Only summing up the more recent foo (456) and bar.

Bucket_sort seems exactly what they would need, only they are still on 5.6. Will ask if upgrading would be an option.
