### ISSUE TITLE
Caching duplicate TermsLookups within the same query

### ISSUE THREAD

**Issue by twilson-palantir** [elastic/elasticsearch#29596]
I'm building a system that has security policies for documents that are essentially conjunctions of disjunctions of group principals. The way I'm implementing this is basically indexing the principals in each conjunctive clause into separate fields, then wrapping each query I perform with a bool query that filters an identical terms query (containing all of the user's principals) against each of those fields.

If I'm reading the code and network stats right, it looks like when I write those terms queries as terms lookups, they're each fetched independently by each node when the query is executed.

Would it be possible to cache the results of terms lookups for the duration of a single query to avoid this repeated fetching?

**Comment by jpountz** [comment]
Discussed in FixitFriday. While this is doable, we prefer to not implement it in order to keep the code simple. It is possible to work around this issue by doing the terms lookup on the client side.
