### ISSUE TITLE
Drop java 7 support for Java low-level REST Client

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#29607]
Opening this one up to gather feedback from the community.

The Java high-level REST currently depends on Elasticsearch, and has the same jvm requirements that Elasticsearch has. The Java low-level REST client though has minimal dependencies and works with java 7 and onwards. 

Given that java 7 is EOL for quite some time now, we are considering dropping support for java 7 and require java 8 as minimum java version for the Java low-level REST client, starting from 7.0 version of the client, which will go out with Elasticsearch 7.0. The release is not really around the corner, so that gives us some time to think about this, gather feedback and make an informed decision.

Using java 8 as a minimum Java version (compared to 7) is appealing as it would allow us to us java 8 features,  as we are currently forced to write code that is java 7 compatible when it comes to the low-level REST client and its sniffer component. On the other hand there may be people still stuck on java 7 using our REST client, who would not be able to upgrade to a newer version. We would definitely recommend such people to upgrade their jvms regardless as java 7 is EOL, but this issue should give us a sense of how many people would be negatively affected by the proposed change, and gives them some notice in case we decide to go ahead in this direction.

**Comment by jasontedor** [comment]
I think we are good to move forward with this indeed. I see that other projects in the ecosystem (e.g., Netty) are also dropping support for JDK 7.

**Comment by jasontedor** [comment]
Let's do two things here:
 - if the LLRC is used in 6.x with JDK 7, we should issue deprecation warnings starting in 6.5.0
 - bump the minimum compiler version in master to JDK 8
