### ISSUE TITLE
[CI] Failures in batsPackagingTest

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#29610]
Two failures in the last 24 hours, one for OpenSuse42 and one for Sles12:
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+packaging-tests/772/console
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+packaging-tests/771/console

In both cases an ES node is started up, but the test fails to create an index.  It's not obvious from the console log why though.

**Comment by jasontedor** [comment]
The node timed out, probably due to the VM host being under load. As such, this is not actionable through core/infra or a packaging change.
