### ISSUE TITLE
[CI] SimpleNetty4TransportTests.testTimeoutPerConnection failure

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#29613]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+multijob-windows-compatibility/975/console

Seems flaky, and I can't reproduce it.

**Comment by DaveCTurner** [comment]
Closing this. The build logs are long gone and this hasn't recurred, so there's not much action we can take here.
