### ISSUE TITLE
_cat/health reaches a time out if an unknown index is given as a parameter

### ISSUE THREAD

**Issue by klaasdellschaft** [elastic/elasticsearch#29616]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.4 (I'm using the docker image docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4)

**Plugins installed**: The default plugins installed in docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4

**JVM version** (`java -version`): openjdk version "1.8.0_161"

**OS version** (`uname -a` if on a Unix-like system): Linux ed2b51fded65 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: When calling the _cluster/health API with an unknown index, then the request reaches a timeout after 30 seconds and a health status of "red" is returned. I would have expected that the request does not timeout but that it reaches a response time similar to a _cluster/health check for a known index.

**Steps to reproduce**:

Curl commands for reproducing the problem:
1. Start with an empty, single-node cluster of Elasticsearch (i.e. no indexes / aliases created yet)
2. Create a test-index
3. Check the health of the test-index. => Response time of 50ms and status code 200 OK
4. Check the health of a non existing index. => Response time of 30000ms and status code 408 Request Timeout

[commands.txt](https://github.com/elastic/elasticsearch/files/1928778/commands.txt)

Response body for the 'unknown-index' request:

[response.txt](https://github.com/elastic/elasticsearch/files/1928780/response.txt)

**Comment by jasontedor** [comment]
The [cat health API](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/cat-health.html) acts the same way as the [cluster health API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html). The cluster health API with indices specified will wait for up to a default timeout of 30s for those indices to exist in the cluster state. While the cluster health API has the ability to specify a different timeout, the cat health API does not. This is a larger issue: #9375

As such, there is no issue here and I am closing this one in favor of #9375.
