### ISSUE TITLE
jvmStats does not handle java.lang.InternalError

### ISSUE THREAD

**Issue by GorillaCoder** [elastic/elasticsearch#29624]
jvmStats catches *Exception*. It should be catching *Exception|java.lang.InternalError*. As is noted in the comment in the code, MemoryPoolMXBean throws InternalError, and InternalError is not derived from Exception:
```java
            } catch (Exception ex) {
                /* ignore some JVMs might barf here with:
                 * java.lang.InternalError: Memory Pool not found
                 * we just omit the pool in that case!*/
            }
```

**Comment by jasontedor** [comment]
Are you seeing this in practice? I think this is only a stale comment from when we use to catch throwable in the entire codebase. We have removed that, we do not catch fatal errors that we can not recover from. The Javadocs for `MemoryPoolMXBean` do not document an `InternalError`.

Relates #19231
