### ISSUE TITLE
Get the only failed document response in Bulk API Elasticsearch

### ISSUE THREAD

**Issue by ashishtiwari1993** [elastic/elasticsearch#29632]
I am struggling with Bulk API. I am sending 100 request (index, update) in every Bulk request. It gives me response with status of each request. Suppose my 97th request got fail, I have to make it loop to find the particular error document. I think its not optimize way. If i am sending more number of Bulk request, It makes my process slow. Is there any way where i will get only failed document or count of fail/success document in response? I am using php-elasticsearch SDK .

**Elasticsearch version** : 6.2

**JVM version** : 1.8.0_161

**OS version**: centos7 x86_64 GNU/Linux

**Comment by jasontedor** [comment]
Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by tlrx** [comment]
@ashishtiwari1993  As a side note, this topic has been discussed in #2661 and #17932 where you'll find more information.
