### ISSUE TITLE
Check PRs for appropriate additions to `docs/CHANGELOG.txt`

### ISSUE THREAD

**Issue by pcsanwald** [elastic/elasticsearch#29642]
After discussion with Elasticsearch Engineering team, we've agreed that most PRs should contain a release notes worthy description in the [changelog](https://github.com/elastic/elasticsearch/blob/master/docs/CHANGELOG.asciidoc) file. To remind PR authors and reviewers, we've agreed that we should include a checker step that notifies the PR opener if they've opened a PR without updating the changelog.

Since not every PR should be required to have a changelog entry, the checker should ignore PRs with the labels ">non-issue", ">test" or ">docs". The checker should also add a comment to the PR when it runs to verify that it either 1) performed the check and it either passed or failed, or, 2) ignored PR because of labeling. This comment is important to have as history since labels are mutable.

**Comment by archanid** [comment]
I'm not sure I understand the `>non-issue` label. Can you explain that one?

**Comment by archanid** [comment]
Apologies if this was already discussed, why not use a label like `no-release-notes`? Maybe something is an issue but doesn't need to be mentioned in the changelog--is that a case?

**Comment by nik9000** [comment]
`>non-issue` is fairly old to be honest and we've grown to use it for things where the name doesn't entirely match. Or, maybe, it only matches if you think of `>non-issue` as meaning "this should not be an issue to any of our users, we just did it for contributors". We're retrofitting the release notes behavior onto an existing pattern, thus the funny name.

**Comment by archanid** [comment]
Ah, I see. we are in the elastic/elasticsearch repo right now. I think this issue could live in dev? or infra? Maybe we can unify how we handle the changelog/release notes stuff that way. Or maybe that's a later effort...

**Comment by pcsanwald** [comment]
@archanid I think that would be a later effort. I'm new to elastic, but it's my understanding that for, elasticsearch build/PR steps are owned by elasticsearch's core-infra team.

**Comment by jasontedor** [comment]
This is deployed, closing.
