### ISSUE TITLE
Filter top_hits aggregation data

### ISSUE THREAD

**Issue by nick250386** [elastic/elasticsearch#29648]
If I want to access a field from the result returned by top_hits:(example below)

```
"aggregations": {
    "last_document_of_specific_doc_types": {
        "filter": {
            "terms": {
                "doc_types": [
                    161,
                    162
                ]
            }
        },
        "aggregations": {
            "latest": {
                "top_hits": {
                    "size": 1,
                    "_source": [
                        "creationDate",
                        "required"
                    ],
                    "sort": {
                        "creationDate": "desc"
                    },
                    "script_fields": {
                        "reqd_flag": {
                            "script": {
                                "lang": "painless",
                                "inline": "params['_source']['required'] == 'Y' ? 0 : 1"
                            }
                        }
                    }
                }
            }
        }
    }
}
```
How can I access the source field "required" or the scripted field "reqd_flag" outside this aggregation as I need to pick up only those top_hits data that are meeting the condition present in "reqd_flag" variable ? If not, then can you suggest an alternative to this. Am I missing or doing something wrong ?

[StackOverflow link](https://stackoverflow.com/posts/49962778/edit)
[Elasticsearch forum link](https://discuss.elastic.co/t/filter-based-on-scripted-field-in-an-aggregation/128976)

**Comment by javanna** [comment]
hi @nick250386 I see that you asked the same question in our forums, which is great. I would ask you to be patient there and wait for an answer. We reserve github for feature requests and bug reports hence I am closing this.

**Comment by nick250386** [comment]
Hi Luca,

Thank you for replying back.
There are a lot of questions in the open relating to aggregations and
especially 'top_hits'. It would be of great help if you could give me few
pointers I this regard.

Thanks
Nishant Kumar
