### ISSUE TITLE
Investigate other ranking evaluation metrics

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#29653]
From an old [dicussion in our forums](https://discuss.elastic.co/t/evaluating-your-search-systems-performance/17064/5) I just learned about another interesting looking ranking evaluation metric used in some [TREC competitions](https://trec.nist.gov/pubs/trec16/appendices/measures.pdf) called "bpref" that is advertised to work [well with incomplete data](http://homepages.dcc.ufmg.br/~nivio/cursos/ri10/transp/slideschap_eval.pdf).

I'm opening this issue to do some more investigation into this and other evaluation metrics that we haven't considered yet.

Regarding `bpref` its atm. unclear to me:
* how widely used it is
* in which use cases it might perform better than the metric we currently offer
* if we can implement it with our current API that is based in msearch or if we would need to change something to make it work

**Comment by rpedela** [comment]
I would love to see [expected reciprocal rank (ERR)](http://olivier.chapelle.cc/pub/err.pdf) added.

**Comment by rpedela** [comment]
Doug Turnbull from Open Source Connections does a great job answering your question in [this talk starting at 21:18](https://youtu.be/JqqtWfZQUTU?t=21m18s).

**Comment by rpedela** [comment]
One more data point. [Ranklib](https://sourceforge.net/p/lemur/wiki/RankLib/) is the de facto learning to rank library and ERR is the default optimization metric used for training.

**Comment by cbuescher** [comment]
@rpedela I started looking into ERR and found it to be a great additional metric. I've opened a PR at #31891, maybe you'd like to comment if you are familiar with the calculation of this metric and want to check if my understanding of the algorithm is correct. In particular I was wondering about the handling of ungraded search results. The paper assumes complete labels but this is unrealistic in a real-world scenario. For now I opted for an optional, user-supplied "unknown_doc_rating" parameter that gets substituted for search results without a relevance judgment (it could simply be 0 for most cases). If this parameter is not present, unrated documents are just skipped over in the metric calculation. Not sure if that is common practice but would like to hear thought or get pointers on this.

**Comment by cbuescher** [comment]
Another possible metric that I recently encountered in presentation is Average Precision (or, if taken across multiple user needs: [Mean Average Precison](https://nlp.stanford.edu/IR-book/html/htmledition/evaluation-of-ranked-retrieval-results-1.html)).

**Comment by cbuescher** [comment]
Moving some thoughts from #20441 here since it seems a better fit to keep tracking it:

In case users are able to label entire datasets (likely more academic / ML use cases) they might be interested in metrics including some sort of recall like f-score, AUC of ROC curve. However, we are doubtfull about the likelihood of this for any practical purpose.

**Comment by joshdevins** [comment]
> In case users are able to label entire datasets (likely more academic / ML use cases) they might be interested in metrics including some sort of recall like f-score, AUC of ROC curve. However, we are doubtfull about the likelihood of this for any practical purpose.

I think the "entire datasets of labels" is covered by what we offer today in Machine Learning.

**Comment by javanna** [comment]
There are no concrete plans to work on this issue. Closing.
