### ISSUE TITLE
Feature request: support template in `rename` processor's `target_field`

### ISSUE THREAD

**Issue by jovandeginste** [elastic/elasticsearch#29657]
I'm trying to solve this use case with journalbeat and elastic:

A process outputs json. I use the `json` processor in journalbeat (or in elastic ingest pipeline, same difference) to decode that output from field `message` to field `json_message`. I would like the output to be in field `{{ name_of_process }}` instead (eg. `{{ journald.systemd_unit }}`), to prevent type clashes (same process should not mix types, but different processes could).

I can not use templates in the `json` processor's `target_field` nor the `rename` processor's `target_field`.

Is there a specific reason for this, am I Doing Something Wrong(tm)?

**Comment by jovandeginste** [comment]
@talevy thanks for your kind response! Any idea on ETA? Just to judge if it is worth waiting, or I should dive into the `script` processor...

**Comment by talevy** [comment]
@jovandeginste I will probably get to it next week. No matter how fast it is updated in Github, it will take until `6.4` is released for it to become widely available. We do not have a concrete date for `6.4` yet, so I cannot give a convincing ETA for you.

**Comment by jovandeginste** [comment]
@talevy thanks! For the time being, we patched journalbeat and do that processing part client side.
