### ISSUE TITLE
geo mobile country code plugin

### ISSUE THREAD

**Issue by SigPloiter** [elastic/elasticsearch#29650]
Hello, as elasticsearch is becoming more popular in telecom operators and between telecom security researchers for detection needs, is there a possibility to have a geoip like plugin but for mobile operators, that with the mobile country code and maybe with the operator code as well be easily to identify which operator is the incoming traffic coming from

thanks

**Comment by nik9000** [comment]
To clarify: I think you mean resolving phone numbers into a country code and maybe other data. I used to work for a US based telco so I've implemented this kind of thing in the past but I don't know a tone about it once you get out of NANPA.

This seems like a super reasonable thing to do with Elasticsearch in an ingest processor, but I don't think this is a thing we're interested in implementing as part of Elasticsearch, at least not in the near future. If you are interested in implementing it as an open source plugin then ping me once you've put it somewhere and I'd be happy to review the code and just talk shop about telco stuff.
