### ISSUE TITLE
Safeguard on frequent stats requests

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#29661]
5.6.4

We have seen many Gbs of memory used by ConcurrentHashMap where the map was filled with outstanding indices:monitor/stats[n] requests, holding on to shard-level responses while waiting for the remaining shards to respond.  This was caused by users sending very frequent /_cat/indices requests (5-10 per second back to back).  While it certainly doesn't make sense to request indices stats at such a high rate, I am wondering if there is any safeguard/soft/hard limits we can add to the product to prevent this type of OOM cause.

**Comment by jasontedor** [comment]
I think that the point of safeguards should be to guard against things that on their face seem reasonable but actually are not. For example, a naïve thought is "Elasticsearch is a horizontally scalable system so I can have tens of thousands of shards and it is okay!" but that's not actually reasonable. So, we have safeguards about this.

It is simply not reasonable to send many cat indices API requests per second for second after second.

I want to deliberate for what we safeguard against, and for me a criteria is: is this something that I can empathize on the user with being a reasonable thing to do? If not, I don't want to overwhelm the codebase guarding every action a user could take that can hurt them.

**Comment by nik9000** [comment]
For what it is worth pinging an endpoint for stats every 5-10 seconds is a fairly normal thing for some monitoring tools. It isn't a good idea to hit `/_cat/indices` that frequently though.

**Comment by jasontedor** [comment]
@nik9000 The case presented here is not a request every 5 to 10 seconds; it’s 5 to 10 every second. One is reasonable, the other is not.

**Comment by nik9000** [comment]
> @nik9000 The case presented here is not a request every 5 to 10 seconds; it’s 5 to 10 every second. One is reasonable, the other is not.

I see that now. It isn't reasonable.

I really wish we could just fail requests in situations like this without knocking over the whole server.

**Comment by martijnvg** [comment]
> I really wish we could just fail requests in situations like this without knocking over the whole server.

Agreed, would be better if nodes don't die with OOME if they get swamped with indices stats requests.

**Comment by nik9000** [comment]
I had a talk with @jasontedor and some others. While I still hold that "anything you can do with the API that takes down Elasticsearch is a bug", I think we should be spending our time on the reasonable or reasonable-looking things that take down Elasticsearch. But hammering the `/_cat/indices` API a bunch of times a second isn't really reasonable. If we had infinite contributors we'd fix this. We don't. So I'm going to close it and be sad about it.
