### ISSUE TITLE
invalid_shape_exception for a valid geometry in the Arctic

### ISSUE THREAD

**Issue by samuelbosch** [elastic/elasticsearch#29669]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.4

**Plugins installed**: []

**JVM version** (`java -version`): Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_161/25.161-b14

**OS version** (`uname -a` if on a Unix-like system): Centos 7

**Description of the problem including expected versus actual behavior**:

A query with a seemingly valid geometry in the Arctic is generating an error instead of returning results.
The issue manifests itself for us when you query the following API with a fairly simple geometry in the Arctic:

[http://api2.iobis.org/occurrence?geometry=POLYGON ((-130 70, -180 89.9, -120 89.9, 19 89.6, -130 70))&after=-1&size=10](http://api2.iobis.org/occurrence?geometry=POLYGON%20((-130%2070,%20-180%2089.9,%20-120%2089.9,%2019%2089.6,%20-130%2070))&after=-1&size=10)

Moving away from the dateline (e.g. -179 instead of -180) doesn't fix the issue.

**Steps to reproduce**:

I managed to reproduce the error with the docker image, these are the different steps command which result in the error:

1) Pull and run docker image

```
docker pull docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
```

2) create mapping

```
curl -X PUT "localhost:9200/my_index" -H 'Content-Type: application/json' -d'
{
  "mappings": {
    "_doc": {
      "properties": {
        "location": {
          "type": "geo_shape"
        }
      }
    }
  }
}
'
```
    
3. Add a point

```
curl -X PUT "localhost:9200/my_index/_doc/4" -H 'Content-Type: application/json' -d'
{
  "type": "point",
  "coordinates": [ -71.34, 41.12 ] 
}
'
```

4. Do the query with the failing polygon:

```
curl -X GET "localhost:9200/_search" -H 'Content-Type: application/json' -d'
{
      "query": {
        "bool": {
          "must": [{"bool": {"should": []}},
            {
              "geo_shape": {
                "location": {
                  "shape": {
                    "type": "polygon",
                    "coordinates": [[[-130,70],[-180,89.9],[-120,89.9],[19,89.6],[-130,70]]]
                  },
                  "relation": "within"
                }}}]}}}
'
```

I noticed that the error is probably from the JavaTopologySuite and tried to reproduce it in turf.js,  which should be implemented in the same way, but I didn't succeed. For reference, here is the jsfiddle: https://jsfiddle.net/ftsm8sbd/ 

**Provide logs (if relevant)**:

Generated error:

`{"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: {\n  \"bool\" : {\n    \"must\" : [\n      {\n        \"match_all\" : {\n          \"boost\" : 1.0\n        }\n      },\n      {\n        \"geo_shape\" : {\n          \"location\" : {\n            \"shape\" : {\n              \"type\" : \"polygon\",\n              \"orientation\" : \"right\",\n              \"coordinates\" : [\n                [\n                  [\n                    230.0,\n                    70.0\n                  ],\n                  [\n                    180.0,\n                    89.9\n                  ],\n                  [\n                    240.0,\n                    89.9\n                  ],\n                  [\n                    19.0,\n                    89.6\n                  ],\n                  [\n                    230.0,\n                    70.0\n                  ]\n                ]\n              ]\n            },\n            \"relation\" : \"within\"\n          },\n          \"ignore_unmapped\" : false,\n          \"boost\" : 1.0\n        }\n      }\n    ],\n    \"adjust_pure_negative\" : true,\n    \"boost\" : 1.0\n  }\n}","index_uuid":"jPS24A1DRGSOuWyCe5UBEg","index":"my_index"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"my_index","node":"0BP8BRIgT7a6_MoiU0sIMw","reason":{"type":"query_shard_exception","reason":"failed to create query: {\n  \"bool\" : {\n    \"must\" : [\n      {\n        \"match_all\" : {\n          \"boost\" : 1.0\n        }\n      },\n      {\n        \"geo_shape\" : {\n          \"location\" : {\n            \"shape\" : {\n              \"type\" : \"polygon\",\n              \"orientation\" : \"right\",\n              \"coordinates\" : [\n                [\n                  [\n                    230.0,\n                    70.0\n                  ],\n                  [\n                    180.0,\n                    89.9\n                  ],\n                  [\n                    240.0,\n                    89.9\n                  ],\n                  [\n                    19.0,\n                    89.6\n                  ],\n                  [\n                    230.0,\n                    70.0\n                  ]\n                ]\n              ]\n            },\n            \"relation\" : \"within\"\n          },\n          \"ignore_unmapped\" : false,\n          \"boost\" : 1.0\n        }\n      }\n    ],\n    \"adjust_pure_negative\" : true,\n    \"boost\" : 1.0\n  }\n}","index_uuid":"jPS24A1DRGSOuWyCe5UBEg","index":"my_index","caused_by":{"type":"invalid_shape_exception","reason":"Self-intersection at or near point (-179.79605248249447, 89.81882888803281, NaN)"}}}]},"status":400}`

**Comment by colings86** [comment]
@nknize could you look at this?

**Comment by DaveCTurner** [comment]
This shape is not valid: it is oriented clockwise, and since it is wider than 180° of longitude it cannot be automatically corrected. See https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html:

> IMPORTANT NOTE: WKT does not enforce a specific order for vertices thus ambiguous polygons around the dateline and poles are possible. GeoJSON mandates that the outer polygon must be counterclockwise and interior shapes must be clockwise, which agrees with the Open Geospatial Consortium (OGC) Simple Feature Access specification for vertex ordering.

> Elasticsearch accepts both clockwise and counterclockwise polygons if they appear not to cross the dateline (i.e. they cross less than 180° of longitude), but for polygons that do cross the dateline (or for other polygons wider than 180°) Elasticsearch requires the vertex ordering to comply with the OGC and GeoJSON specifications. Otherwise, an unintended polygon may be created and unexpected query/filter results will be returned.
