### ISSUE TITLE
Abort package install if JAVA_HOME is not set and java is not in the path

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#29665]
Since #28928 we create the keystore in a post-install script. Through our scripts, this requires that `JAVA_HOME` be set or that `java` is in the path. If this is not the case, the post-install script fails and the installation is broken. It is too late to be failing in post-install. Instead, we should add a check in pre-install for this and fail early.

**Comment by jasontedor** [comment]
Pinging @hub-cap

**Comment by Crazybus** [comment]
I ran into some troubles with this when upgrading the ansible-elasticsearch playbook to 6.3. I suspect others are going to run into the same problems too if they are installing elasticsearch and java at the same time. 

If you run `apt-get -y install openjdk-8-jre-headless elasticsearch` java will not be available for the post install tasks of elasticsearch causing the installation to fail. If a pre-install task is added to check for java this is still going to fail. 

To quote #28928

> This commit removes the ability to specify that a plugin requires the keystore and instead creates the keystore on package installation or when Elasticsearch is started for the first time. 

If elasticsearch also creates this file on startup is there a specific reason why we also want to create it in the post install script? I imagine that there must be a good reason but it sounds like the simplest option would be to just remove this from the post install task and let elasticsearch handle creating it.

**Comment by jasontedor** [comment]
> If elasticsearch also creates this file on startup is there a specific reason why we also want to create it in the post install script? I imagine that there must be a good reason but it sounds like the simplest option would be to just remove this from the post install task and let elasticsearch handle creating it. 

This is because when Elasticsearch is run as a service (via Sys V init or `systemd`) we run as the `elasticsearch` user which today does not have permissions to create files in `/etc/elasticsearch`. This is why we do this in post-install when we are running as `root`.
