### ISSUE TITLE
[CI] RecoveryWhileUnderLoadIT.testRecoverWhileUnderLoadAllocateReplicasTest fails

### ISSUE THREAD

**Issue by tlrx** [elastic/elasticsearch#29660]
The test `RecoveryWhileUnderLoadIT.testRecoverWhileUnderLoadAllocateReplicasTest` failed on CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+multijob-unix-compatibility/os=opensuse/410

When cleaning up the indices after the test succeed, the following error occurs:

```
> Throwable #1: java.lang.AssertionError: expected index shard counter on shard [test][1] on node node_s0 to be 0 but was 1. Current replication tasks on node:
> {
>   "tasks" : { }
> }
> 	at __randomizedtesting.SeedInfo.seed([FAAE0D542576702B:BDD92864606318DB]:0)
> 	at org.elasticsearch.test.InternalTestCluster.lambda$assertShardIndexCounter$5(InternalTestCluster.java:1159)
> 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:731)
> 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:705)
> 	at org.elasticsearch.test.InternalTestCluster.assertShardIndexCounter(InternalTestCluster.java:1140)
> 	at org.elasticsearch.test.InternalTestCluster.beforeIndexDeletion(InternalTestCluster.java:1109)
> 	at org.elasticsearch.test.ESIntegTestCase.beforeIndexDeletion(ESIntegTestCase.java:607)
> 	at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:577)
> 	at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2085)
> 	at java.lang.Thread.run(Thread.java:748)
```

It does not reproduce locally with:
```
./gradlew :server:integTest -Dtests.seed=FAAE0D542576702B -Dtests.class=org.elasticsearch.recovery.RecoveryWhileUnderLoadIT -Dtests.method="testRecoverWhileUnderLoadAllocateReplicasTest" -Dtests.security.manager=true -Dtests.locale=de-AT -Dtests.timezone=America/Argentina/Catamarca
```

The complete test execution log is 
[consoleText.txt](https://github.com/elastic/elasticsearch/files/1939029/consoleText.txt)

**Comment by bleskes** [comment]
We chased these for a while and couldn't figure it out, so I tightened up the assertion log to give more info: https://github.com/elastic/elasticsearch/pull/28567  . This went to 6.x and master but sadly didn't fail yet...   . I scanned the console in this failure and I can't find any smoking gun to start an investigation (no docs were lost, test passes). I don't know if it's worth while keeping this issue open while we wait for the next time and see if we get more info.
