### ISSUE TITLE
More Like This Queries should error when Routing Set to "required" and no routing is supplied

### ISSUE THREAD

**Issue by kylelyk** [elastic/elasticsearch#29678]
**Elasticsearch version**: 6.2.4

**Plugins installed**: []

**JVM version**: 1.8.0_101

**OS version**: MacOS (Darwin Kernel Version 15.6.0)

**Description of the problem including expected versus actual behavior**:
"More Like This" queries do not return any results when "mappings.type._routing" = true.

**Steps to reproduce**:

```
PUT test
{
  "mappings": {
    "type": {
      "_routing": {
        "required": true
      },
      "properties": {
        "myField": {
          "type": "text"
        }
      }
    }
  }
}
```

```
POST /_bulk
{ "index":  { "_index": "test", "_type": "type","_id":1, "_routing":1 }}
{"myField":"and_foo"}
{ "index":  { "_index": "test", "_type": "type","_id":2, "_routing":2 }}
{"myField":"and_foo" }
```

The following query returns no results:

```
GET /_search
{
  "query": {
    "more_like_this": {
      "fields": [
        "myField"
      ],
      "like": [
        {
          "_index": "test",
          "_type": "type",
          "_id": "1"
        }
      ],
      "min_term_freq": 1,
      "min_doc_freq": 1
    }
  }
}
```

If the _routing setting in the index mapping is removed, it correctly returns 1 result.

**Comment by colings86** [comment]
You should be able to add a `routing` field next to the `_id` field in the `like` array to specify the routing to use to retrieve the item.

**Comment by kylelyk** [comment]
Adding the routing field makes the query work as expected. Could an error be returned if you attempt to specify a document without a routing id if routing is set to required? Every other API I have used has given an appropriate error if I forget to set the routing id.

**Comment by colings86** [comment]
Thats a good suggestion @kylelyk, I'm going to reword the title of this issue to reflect the intention to change to that behaviour and mark it as an adoptme

**Comment by ashishguptak** [comment]
Hello, Can I take up this issue?
any pointers are much appreciated.

**Comment by cbismuth** [comment]
I'll have a look on this one.

**Comment by cbismuth** [comment]
I can reproduce this issue on `master`, see Gist [here](https://gist.github.com/cbismuth/6c59193b0ab0da39e9ced05cfdb76dd4). As @kylelyk said, its returns no result.

`{"took":5,"timed_out":false,"_shards":{"total":2,"successful":2,"skipped":0,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}`

Besides, Bulk API doesn't seem to allow `_routing` attribute any more, see error below. I've switched to two POST commands with refresh forced.

`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [2] contains an unknown parameter [_routing]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [2] contains an unknown parameter [_routing]"},"status":400}`

I'm now digging a little deeper in issue resolution and let you know.

**Comment by cbismuth** [comment]
I've open a pull request to fix this issue, see https://github.com/elastic/elasticsearch/pull/33815.

**Comment by cbismuth** [comment]
Obsolete PR closed and new one opened in sync with `master` branch.
