### ISSUE TITLE
Handle unresponsive nodes better

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29699]
*Original comment by @ppf2:*

When nodes OOM or about to OOM, they become unresponsive, and the nodes info/stats commands will take a while to return (until the master drops the problem nodes from the cluster).  During this time, the customer (on Marvel 2.x) who relies on Marvel for monitoring saw that Marvel was also complaining that it is no longer receiving data on the nodes.  This is likely because Marvel calls the node stats api in the background (which was not returning because the problem nodes have not yet been dropped from the cluster).  It will be helpful for the administrators to be able to continue to receive stats from nodes that are actually working, instead of no stats at all.  Perhaps Marvel can fallback to using _local mode for the node apis, etc.. Or switch to using _local mode to collect node stats to start with so it is less prone to these situations?

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
