### ISSUE TITLE
Expand remote audit logging info

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29692]
*Original comment by @markwalkom:*

[Here](https://www.elastic.co/guide/en/shield/current/configuring-auditing.html#_forwarding_audit_logs_to_a_remote_cluster) we're a little light on some details that might make it easier for users to understand what is happening.

eg;
- How does this integrate into SSL/TLS secured clusters?
- Are we using transport protocol? It seems implied that we do but it'd be nice to be explicit (I checked the code but wasn't 100% sure).
- Pending ^; Can HTTP be used instead?
- What are these "other settings" that are mentioned below;

> Additional settings may be passed to the remote client by placing them under the shield.audit.index.client namespace

**Comment by tvernum** [comment]
@lcawl Bump - it would be good to at least update the docs to clarify that `hosts` should point to the transport port rather than the http port (actully, the port can just be left blank if the remote cluster is using the default port of `9300`).

**Comment by sgelastic** [comment]
We should also point out that user account on the elasticsearch user on the monitoring cluster must have permissions to create .security-audit.

Many users have more conservative role based permissions, so it's helpful to provide this info for them.
