### ISSUE TITLE
2.0 License Testing

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29696]
*Original comment by @rasroh:*

License 2.0 
- [x] Trial License Test:  Install ES 2.0+ license 2.0+ shield 2.0  trial license . Advance system clock. see license expires as expected. 
- [x] When the trial license is installed, all the features should be enabled for all plugins ( test for watcher, shield, marvel ) and should work seamlessly and should be valid until the trial expires. 
- [x] Test the unlicensed behavior of each product, the behavior when adding a Basic, Gold and Platinum License on top of an expired built-in Trial license. 

Upgrade:
- [x] Install Trial ES 1.0+ license 1.0+ Shield 1.0 -  upgrade to ES 2.0, License 2.0 + shield 2.0—trial license should work without any issues. Logs should be clean
- [x] Generate signed license for 1.0 and upgrade to 2.0 License. 

For signed licenses
- [x] generate signed license ( license generator tool- for different types of license- basic, gold, platinum)  
- [x]  Apply  the license to  the cluster 
- [x] Verify by GET _license - signed license is applied- check the uid. 
- [x]  To expire the signed license- advance  the system clock  and make the signed license expire. Once expired, verify the behavior of each product .
- [x]  change the subscription type from basic> gold> platinum in the generated License.json- see the features enabled/disabled. ( note: Everytime you change the `license.json` we should re- generate the license and reapply.)
- [ ]  Test adding a 1.x license to a 2.0 cluster and check the behavior.

Isolation Plugin Tests

License+ Watcher:
- [x] While the built-in trial license is active, test to make sure that all features of watcher are enabled. 
- [x] When trial license expires- validate that the  watches will still be triggered but no actions will be performed. 
- [x] When trial license expires- validate that you will not be  able to get existing watches or add new ones. ( PUT / GET watch APIs are disabled)
- [x] When trial license expires- validate that you still  will be able to delete watches.
- [x] When trial license expires- validate that watches continue to work and write to watch history.

License+ Watcher+ Shield:

Unlincensed behavior:
- [x]  When under a trial license - ES + Shield+ Watcher > configure the motinor_watcher ( to access watcher stats and get API) and manage_watcher roles ( to get access to all watcher APIs)  in the roles.yml file verify the APIs.
- [x]  Add the `watcher administrator user` , once added this user will be able to call all the watcher APIs and by that manage all watches - validate this behavior
- [x] If Shield is enabled, you need cluster admin privileges to install the license.You can do this update at run time without shutting down the nodes.Validate this behavior.
- [x]  Cluster health, cluster stats and indices stats operations are blocked when trial license expires. 

We also need to test each plugin in isolation, and each of the plugins with Shield. Marvel + Shield (with SSL), Watcher + Shield. For these combinations, we should verify that they work as intended while licensed and properly configured, as well as test their behavior when unlicensed.

**Comment by polyfractal** [comment]
Think this was accidentally re-opened.  Closing.
