### ISSUE TITLE
Monitoring: Listing tasks + operations on them

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29701]
*Original comment by @kimchy:*

Now that we have the task infrastructure in ES, monitoring can have a "tab" that lists all the tasks running, and allow to cancel them and see live stats.

Next step would be a task audit log, where we hook into the task execution and show the history of all tasks executions including statistics over time.

**Comment by jakelandis** [comment]
@elastic/stack-monitoring - Can you take a look at this issue and close/move as appropriate ?

**Comment by chrisronline** [comment]
This looks related: https://github.com/elastic/elasticsearch-team/issues/227

Not sure how @cachedout wants to handle this though

**Comment by cachedout** [comment]
@chrisronline is absolutely right. I think we've got a good handle on this over in https://github.com/elastic/elasticsearch-team/issues/227 and that's where recent discussions have been happening. I am going to go ahead and close this in favor of that issue. cc: @jethr0null and @alisonelizabeth
