### ISSUE TITLE
Monitoring: Incremental Backoff Agent's interval when it hits back pressure

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29700]
*Original comment by @pickypg:*

If the Monitoring Agent runs into back pressure (e.g., HTTP 429 while attempting to index), then we should incrementally back off. This part seems plainly simple, but the implementation seems less obvious:
- Do we stop backing off after awhile?
  - Do we preset this or make it configurable?
- Do we keep backing off until the node is restarted?

The only thing that I think is simple is that we can allow the backoff interval to be reset by dynamically setting the interval. Any strong thoughts either way?

**Comment by tomcallahan** [comment]
Monitoring is in bugfix-only mode in favor of metricbeats, closing
