### ISSUE TITLE
Document user metadata example for custom realms

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29706]
*Original comment by @ppf2:*

Currently, we only document user metadata functionality as part of the native realm (https://www.elastic.co/guide/en/shield/2.3/native-realm.html#managing-native-users).

Per @jaymode 's (thx!) comment below, this actually works for custom realms as well.
LINK REDACTED

Can we document this and maybe also provide an example LINK REDACTED?

**Comment by jrodewig** [comment]
[docs issue triage]

**Comment by lockewritesdocs** [comment]
This issue hasn't been updated in 3+ years so I'm closing it. We can revisit if needed.
