### ISSUE TITLE
Create notification endpoints

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29707]
*Original comment by @uboness:*

Depends on LINK REDACTED 

Once we centralize notification in X-Pack, we can open up a `notify` endpoint that will use any of the notification services that are available (via any of the configured accounts).

This will enable Kibana to send notifications to users if it needs to.

The endpoint should be something in the form of:

```
PUT /_xpack/notification/<service_id>/<account_name>/_notify
{
  // the message structure depends on the service used... should look the same as we do in watcher
}
```

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
