### ISSUE TITLE
Explain diversity setting of Graph

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29710]
*Original comment by @loekvangool:*

The meaning/workings of the Diversity field in Graph settings is not very clear, a link to a doc page with a good example might help a lot here.

<img width="633" alt="screen shot 2016-07-02 at 22 49 23" src="LINK REDACTED">

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open. This is still relevant.

As of writing, the graph documentation is here:
https://www.elastic.co/guide/en/elasticsearch/reference/7.4/graph-explore-api.html
