### ISSUE TITLE
BasicAuth class name can be misleading

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29716]
*Original comment by @jaymode:*

The `BasicAuth` class name can be misleading to new users of the code base; users may think this is the implementation of basic authentication within xpack, when it is just an object level representation of basic authentication credentials for watches.

I think we should document the class to indicate its purpose and determine if we really need equals/hashcode overrides as some may see this as a security issue if they believe the class is used to perform basic auth.

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
