### ISSUE TITLE
Visualize _cluster/allocation/explain

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29728]
*Original comment by @pickypg:*

I'm creating this as a discussion surrounding the implementation of https://github.com/elastic/elasticsearch/pull/17305 and LINK REDACTED

This is a new API in ES 5.0 that @dakrone has some ideas on how to usefully visualize.

**Comment by dakrone** [comment]
We discussed this in fix-it-thursday and decided that this is an issue for the scope of Kibana, Elasticsearch shouldn't be in the business of doing visualizations for things.
