### ISSUE TITLE
Add details to watch state documentation

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29722]
*Original comment by @ppf2:*

Per customer feedback, they would like to see more details in the documentation for the different watch states:

https://www.elastic.co/guide/en/watcher/current/watch-history.html

For example, maybe we can add the following (assuming I have it right myself below):

execution_not_needed
- The watch is triggered, but the condition clause returns a false, so that it does not need to execute the action clause in the watch.

executed
- The watch is triggered, met the condition, and is not throttled, and therefore, the action clause is executed.

throttled
- The watch is triggered, met the condition, but it is throttled (eg. per [throttle_period](https://www.elastic.co/guide/en/watcher/current/configuring-default-throttle-period.html)), and therefore, the action clause is not executed.

**Comment by jrodewig** [comment]
[docs issue triage]
