### ISSUE TITLE
Default graph explore uri specifies {index}

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29731]
*Original comment by @russcam:*

The LINK REDACTED for 5.0.0-alpha3 specifies that `{index}` in the default path can be left blank (or set to `_all`) to explore across all indices and types. Should there be a default path of

```
/_xpack/graph/_explore
```

that does not specify `{index}`, similar to [`search`](https://github.com/elastic/elasticsearch/blob/v5.0.0-alpha3/rest-api-spec/src/main/resources/rest-api-spec/api/search.json#L6)?

**Comment by nik9000** [comment]
The rest api spec now says you can't leave this blank which looks correct.
