### ISSUE TITLE
Include full list of recommended action.auto_create_index values for bootstrap check

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29737]
*Original comment by @ppf2:*

5.0 beta1

If action.auto_create_index is set to false, we are catching this as part of bootstrap check, for security first and it tells the user to set it to .security:

```
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failed to load plugin class [org.elasticsearch.xpack.XPackPlugin]]; nested: InvocationTargetException; nested: IllegalArgumentException[the [action.auto_create_index] setting value [false] is too restrictive. disable [action.auto_create_index] or set it to [.security]];
```

If you then set it to .security, the node will again fail to start up because it then moves on to check for watcher:

```
org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failed to load plugin class [org.elasticsearch.xpack.XPackPlugin]]; nested: InvocationTargetException; nested: IllegalArgumentException[the [action.auto_create_index] setting value [.security] is too restrictive. disable [action.auto_create_index] or set it to [.watches, .triggered_watches, .watcher-history-*]];
```

Certainly, the documentation tells the end user to set it to `action.auto_create_index: .security,.monitoring*,.watches,.triggered_watches,.watcher-history*`, so let's update the error handling `or set it to` to reference the full list of recommended auto_create_index settings.

**Comment by dakrone** [comment]
I believe this is not necessary any more as we now have access to https://github.com/elastic/elasticsearch/pull/61858 within a template itself.
