### ISSUE TITLE
Control graph significance in spidering by scalar values

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29733]
*Original comment by @derickson:*

Sorry if this is a dupe, but I couldn't find it.  People want to be able to encode their own clues for relevance between terms rather than just co-occurrance sig-terms.   $ for financial transactions, text proximity for extracted entities, NLP related distance for advanced entity extraction.

```
{
text: "The president visited Nashville today. ....... reported from washington dc",
entities: [
   {token:"urn:people:BarakHusseinObama", type:"person", position:0},
   {token:"urn:location:NashvilleTennesseeUSA", type:"location", position: 2},
   {token:"urn:location:WashingtonDCUSA", type:"location", position: 2000}, 
] 
```

The ability to remove the false super-connection from Obama to DC. by specifying my own scalar script.  alternatively maybe having to cook my own triples with the distances hard coded.

```
{
  cookedTriples: [
     {s:"obama", o:"nashville", distance: 2},
     {s:"obama", o:"dc", full:"obama|nashville", distance 2000
  ]
}
```

or even just weighting by something like money

```
{
 transaction_amt_usd:5000,
people: [ 'dave', 'mark']
} 
```

**Comment by polyfractal** [comment]
I'm going to close this as stale.  We've not seen any further comment or requests for the feature since it has opened
