### ISSUE TITLE
OAuth Realm Support

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29735]
*Original comment by @skearns64:*

Some users, including those in our company, would like to use OAuth (Google OAuth) to provide SSO support.  This issue tracks the creation of an OAuth realm for X-Pack. 

Initially, I propose that we use Google OAuth as our way of building/testing, though there are other OAuth systems that our customers may use.

**Comment by tvernum** [comment]
Given the description, I think this can be considered a duplicate of https://github.com/elastic/elasticsearch/issues/35339

**Comment by jkakavas** [comment]
Closed in favor  of #35339
