### ISSUE TITLE
Add cross reference links to Java rest client auth and encryption setup

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29743]
*Original comment by @ppf2:*

Somewhere in here (https://www.elastic.co/guide/en/x-pack/current/http-clients.html#_client_libraries_over_http) we should start cross referencing the auth and encryption pages for the new Java REST client, eg.

https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_basic_authentication.html
https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_encrypted_communication.html

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open. This is still relevant.

As of writing, the documentation now lives here:
https://www.elastic.co/guide/en/elasticsearch/reference/master/http-clients.html#_client_libraries_over_http
