### ISSUE TITLE
Documents on xpack.security.audit.index.events.emit_request_body 

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29741]
*Original comment by @masaruh:*

LINK REDACTED says:

> Include or exclude the request body from REST requests on certain event types such as authentication_failed.

Unlike `xpack.security.audit.logfile.events.emit_request_body`, `xpack.security.audit.index.events.emit_request_body` always logs request body, right?

**Comment by debadair** [comment]
Closing as obsolete.
