### ISSUE TITLE
[documentation] clarify basic license download/registration location for monitoring

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29747]
*Original comment by @inqueue:*

The documentation on https://www.elastic.co/guide/en/x-pack/current/license-management.html contains this:

>When you initially install X-Pack, a 30 day trial license is installed that allows access to all features. At the end of the trial period, you can [purchase a subscription](https://www.elastic.co/subscriptions) to keep using the full functionality of the X-Pack components.

Which is not entirely clear to users looking for the free basic license for monitoring. I also looked right over the "purchase" link and tried to find a link to the subscriptions page on https://www.elastic.co/products/x-pack/monitoring as well. 

Could the language be altered on the [X-Pack License Management](https://www.elastic.co/guide/en/x-pack/current/license-management.html) page to mention the basic license for monitoring? I am not seeing any language on the site today driving a user to the subscriptions page for acquiring a basic license.

@bohyun-e

**Comment by jrodewig** [comment]
[docs issue triage]

**Comment by lockewritesdocs** [comment]
This issue hasn't been updated in 3+ years so I'm closing it. We can revisit if needed.
