### ISSUE TITLE
Watcher: Putting invalid JSON as a watch is allowed

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29746]
*Original comment by @spinscale:*

Putting a watch with invalid JSON does not return an error and puts a broken watch into the system. The Watch parser seems to have an issue here - which should throw an exception but does not.

Putting the below watch results in a watch stored without condition and actions.. you can use the execution watch API to see that an `always` condition is used and the actions array is empty.

```
curl -XPUT localhost:9200/_xpack/watcher/watch/1 -d '
{
  "trigger": {
    "schedule": {
      "interval": "10s"
    }
  },
  "input": {
    "simple": {}
  }},
  "condition": {
    "script": {
      "inline": "return false"
    }
  },
  "actions": {
    "logging": {
      "logging": {
        "text": "{{ctx.payload}}"
      }
    }
  }
}'
```

This issue happens on 2.x as well as 5.x

Originating issue was in the forum https://discuss.elastic.co/t/mistake-on-configuring-watches/70943/5

**Comment by jcmcken** [comment]
Can an API endpoint be provided that validates a given watch configuration as well? We have a CI process for ingesting new watches into Elastic, and there's no linting tools, JSONschema, or anything available to validate common issues.

**Comment by spinscale** [comment]
can you be more specific what you mean with *watch configuration* in this context? The watch gets parsed, scripts get compiled to see if everything works, what validation are you missing? Would your problems be solved, when this issue is fixed or is there more to it?

Thanks for your input, much appreciated!

**Comment by jcmcken** [comment]
If I can supply the watch to the execute API without saving it to the index, and get back a detailed account of what's wrong, then that would solve the issue for me

**Comment by jcmcken** [comment]
@spinscale What's the actual contract with the watch API? How do I determine programmatically that there's a problem? Looking at the Elastic documentation, I can't seem to find any examples or concrete description (other than eyeballing the results -- a Jenkins job doesn't have eyes) of how to do this.

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
