### ISSUE TITLE
LDAP timeout tests are flaky

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29758]
*Original comment by @jaymode:*

The various LDAP timeout tests are flaky. They do not fail locally but fail in CI with the read/connect not timing out. I think we should change these to more of a unit test and just validate we set the connection timeout in the appropriate places and the library we use should validate that connection timeouts work.

**Comment by tvernum** [comment]
@albertzaharovits Are you working on this issue?  
If not can you unassign yourself so that someone else can pick it up?

Thanks

**Comment by albertzaharovits** [comment]
I was not working on it... I missed it, I was looking only through >test-failure labels :(

**Comment by tvernum** [comment]
Thanks - I found it by searching for `@AwaitsFix` on master.
