### ISSUE TITLE
Why no node client?

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29752]
*Original comment by @markwalkom:*

[Here](https://www.elastic.co/guide/en/shield/shield-1.1/_java_clients.html) we have a great explantation on why you shouldn't use the node client with Shield.
[Here](https://www.elastic.co/guide/en/shield/current/_using_elasticsearch_java_clients_with_shield.html) has a contextless "we don't support it".

It's a much nicer UX if we explain the _why_, so it'd be great to see that previous explanation reinstated.

**Comment by debadair** [comment]
Closing as obsolete.
