### ISSUE TITLE
Improve Marvel license message for better usability

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29756]
*Original comment by @bohyun-e:*

Currently, we provide the following message to users installing their basic license, i.e. downgrading from trial/gold/platinum to basic license (or from trial/platinum to gold).

``` json
{
  "acknowledged": false,
  "license_status": "valid",
  "acknowledge": {
    "message": "This license update requires acknowledgement. To acknowledge the license, please read the following messages and update the license again, this time with the \"acknowledge=true\" parameter:",
    "marvel": [
      "basic",
      "Automatic index cleanup is locked to 7 days for clusters with [{}] license.basic"
    ]
  }
}
```

Could we improve this message for better usability where the users can just copy and paste? Maybe we can switch it to a single quote to avoid the obvious escaping as @pickypg suggested. Also, it may not even need the "=true" portion as "_license?acknowledge" would do it?

/cc @tsullivan @pickypg

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
