### ISSUE TITLE
[ML] Tombstone deleted model snapshots

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29768]
*Original comment by @polyfractal:*

Right now, deleting a model checks to see if it is in-use by a job before deleting. However, the cluster states are snapshots-in-time, so it's possible that the model becomes "in-use" after or during the physical deletion of the snapshots, since they are individual documents.

The problematic timeline is:

1. Model is not in use
2. DeleteModel action received, CS confirms model not in use, begins deleting individual docs
3. Before docs are deleted, job is updated to put the model back into usage
4. Doc deletion completes.  Now the model is in-use by the job, but the physical documents are gone

We can't do the delete in the CS update thread because that could take a long time and block.

Instead, we could/should record tombstones in the CS so that after a model has been marked for deletion, future modifications to the job cannot put the model back into use.  Once the docs are fully deleted the tombstone can be removed from the CS.

Also probably needs some way to clear out old tombstones, in case deletion processes die and leave stuff in the CS?

**Comment by sophiec20** [comment]
closing as no longer relevant.
