### ISSUE TITLE
[ML] Better handling of DBQ failures in JobStorageDeletionTask

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29769]
*Original comment by @polyfractal:*

If there are any failures in JobStorageDeletionTask's DBQ, the current code just shrugs and logs it, which could potentially leave orphaned data in the index.  

We should probably add some more robust error handling which potentially retries the deletes.  Unclear what exactly needs to be done, as it depends on the nature of the error.  Needs more research

**Comment by sophiec20** [comment]
Closing as old issue. Please feel free to re-open if DBQ failures are experienced.
