### ISSUE TITLE
[ML] Check the model snapshot to restore and use next candidate if not valid

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29775]
*Original comment by @dimitris-athanasiou:*

In the case when a node fails in the middle of persisting state, it is possible that we end up with a model snapshot that does not have all its corresponding model state documents. We should check for this while restoring a snapshot and we should implement a strategy to choose a suitable substitute when the designated snapshot is not valid.

**Comment by droberts195** [comment]
> This will be less of an issue for UI users, once we have snapshot mgmt UI available

I agree.

I don't think we should add any magic into the backend to silently switch to a different model snapshot.  It will lead to a support case where the user supplies a screenshot showing a discontinuity in anomaly detection and then we'll have to work out why that happened via a painstaking trawl of the cluster logs.

> In the case when a node fails in the middle of persisting state

It's not _any_ node; it's the specific node that holds the `.ml-state` index.  And then for the user to notice that this happened the job has to fail before it has a chance to do another background persist, or else the `.ml-state` index has to remain unavailable for several hours.  So a pretty rare occurrence.

If we had a UI where users could select an alternative model snapshot to roll back to after a snapshot becomes corrupt then it would be:

1. Possible for the user to recover without help in this rare situation
2. The reason for any noticeable discontinuity in anomaly detection would be clear
