### ISSUE TITLE
Watcher: Auto creation warning message on watcher history indices is misleading

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29773]
*Original comment by @ppf2:*

Customer is already using the pattern `+active-nginx-access-*,.kibana,.security,.monitoring*,.watches,.triggered_watches,.watcher-history*`

But we are still throwing the warning message:

```
[2017-04-14T03:18:15,078][WARN ][o.e.x.XPackPlugin ] the [action.auto_create_index] setting is configured to be restrictive [+active-nginx-access-*,.kibana,.security,.monitoring*,.watches,.triggered_watches,.watcher-history*]. for the next 6 months daily history indices are allowed to be created, but please make sure that any future history indices after 6 months with the pattern [.watcher-history-YYYY.MM.dd] are allowed to be created 
```

This is because we are hardcoding only LINK REDACTED worth of watcher history indices that are allowed to be auto-created.  So we attempted to warn users that if they want more than 6 months worth of history indices, they will have to go set up the auto create setting to allow for it - except that we are not fully checking if the patterns in their setting already covers older history indices.  In this case, the autocreate pattern shows ".watcher-history*", which will allow for all history indices, but it's still throwing the warning message which ends up confusing the end user.

**Comment by jakelandis** [comment]
I imagine it is really unusual case that a user would actually add an overly restrictive auto_create_index value that passes the first 6 months, but fails for subsequent months. It is also not obvious, even with a wording change, that a warning about something that may happen in 6 months is of value.

I am +1 to simply remove this warning. (but keep the error)

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
