### ISSUE TITLE
[DOCS] Document how to restrict access to some ML job results

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29774]
*Original comment by @lcawl:*

Per LINK REDACTED

"...Additionally you need the read index privilege on the index storing the results. The machine_learning_admin and machine_learning_user roles provide the necessary combination of cluster and index privileges to use this API.

The reason for the extra privilege requirement is that it gives administrators who want to restrict users to seeing the results of some jobs but not others a way to achieve this. It can be done by setting different results indexes for particular groups of jobs, or by applying document level security based on the job_id field.

This same information applies to all 4 results APIs: buckets, records, influencers and categories. So it may be best to put it on a different page and link to it..."

**Comment by droberts195** [comment]
This ties in with Kibana Spaces.  We should probably defer documenting this until our approach to coexisting with Kibana Spaces is confirmed.

**Comment by jrodewig** [comment]
[docs issue triage]

**Comment by droberts195** [comment]
The long term solution for restricting access to ML results by job is the Kibana "ML in Spaces" project.  Therefore I think this issue is obsolete.  We should not document any backend workarounds when the preferred solution will be via Kibana privileges.
