### ISSUE TITLE
[Monitoring]Extra metrics for Elasticsearch nodes

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29772]
*Original comment by @marius-dr:*

From discuss thread: 

> If X-Pack Monitoring has thread pool aggregate stats(for example, max bulk queue size between the nodes) in overview and has circuit breaker metrics, it would be nice.
https://discuss.elastic.co/t/more-thread-pool-and-circuit-breaker-metrics/80943

List of metrics mentioned by the user:
- max bulk queue size between the nodes
- estimated_size_in_bytes & tripped for circuit breaker
Also, he did point us to this repo:
https://github.com/justwatchcom/elasticsearch_exporter/pull/37

^ @bohyun-e

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
