### ISSUE TITLE
CNAME cannot be used in SubjectAlternativeName

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29909]
*Original comment by @PhaedrusTheGreek:*

In the [SSL troubleshooting guide](https://www.elastic.co/guide/en/shield/current/troubleshooting.html#_sslhandshakeexception_causing_connections_to_fail) we should make mention that one should not use DNS CNAMEs to configure Elasticsearch TLS hosts.  

The symptom is a SubjectAlternativeName verification failure:

```
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching <primary-dns-name> found.
```

Cause:
Java resolves `discovery.zen.ping.unicast.hosts` AND `network.host` entries from CNAMEs back to their normal DNS name or IP address in LINK REDACTED

Solution:
Do not use CNAMEs to configure Elasticsearch hosts or Certificate SAN lists.

**Comment by jrodewig** [comment]
[docs issue triage]

**Comment by lockewritesdocs** [comment]
This issue hasn't been updated in 3+ years so I'm closing it. We can revisit if needed.
