### ISSUE TITLE
Provide authorization controls for individual cluster settings

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29908]
*Original comment by @jaymode:*

This is a feature raised by @uboness. There are a large number of settings and some may be considered more sensitive than others (for example security settings). If the settings are dynamic and can be updated via the cluster settings API, we may want to add the ability to authorize changes to the settings. 

This could be a new field on a role that grants the names of settings that can be changed (maybe grant/deny sub-fields).

**Comment by rjernst** [comment]
Discussed in FixItThursday. This issue was proposed almost 2 years ago and there hasn't been any interest that anyone knows about. Thus I am closing.
