### ISSUE TITLE
Unclear errors when monitoring can't index due to lack of ingest node

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29916]
*Original comment by @GlenRSmith:*

With a default installation of x-plugins in 5.0, and no ingest node configured, the monitoring agent fails and just keeps logging out bulk indexing errors.
Should have some clear indication of the issue, maybe the suggestion to disable `use_ingest`.

**Comment by s1monw** [comment]
@GlenRSmith is this still valid?

**Comment by GlenRSmith** [comment]
@s1monw Probably not, checking with picky.
