### ISSUE TITLE
[Docs] Updating shield.yml without the need for node restart

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29910]
*Original comment by @damianpfister:*

In https://www.elastic.co/guide/en/shield/current/mapping-roles.html we mention that shield related yml files can be updated across the cluster via standard configuration management tools.

> For other types of realms, you configure role mappings for users and groups in a YAML file and copy it to each node in the cluster. Tools like Puppet or Chef can help with this.
> What we don't mention is that there is no need to restart any given node after updating and of the shield yml files, which makes users believe they need to perform a rolling restart.

It would be good to add a note to the effect that although the likes of `elasticsearch.yml` and `logging.yml` need a node restart to be reread, any of the shield yml configuration files are reread automatically every 5 seconds.

**Comment by jaymode** [comment]
Current x-pack docs contain the reloading information. https://www.elastic.co/guide/en/x-pack/current/mapping-roles.html
