### ISSUE TITLE
Authenticate API should clear auth cache for authenticating user

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29919]
*Original comment by @skearns64:*

When a user authenticates via `_xpack/security/_authenticate`, we should clear the authentication cache for that user before completing the request. This would allow a user to log out and log back in and pick up any changes to their password (if using AD/LDAP), user-role mappings, etc. 

Inspired by discuss ticket: https://discuss.elastic.co/t/segurity-problem-using-x-pack-with-5-0-1/68298/4

@jaymode thoughts?

**Comment by tvernum** [comment]
We discussed in the @elastic/es-security team meeting and agree that it's not a good idea to do this (by default) in the `_authenticate` API as it is used for a range of purposes and shouldn't be considered to be a "login" interface.

@skearns64 / @joshbressers Is this still a problem we want to solve?
If so, it seems like we'd want some way for Kibana to call "authenticate this user and but don't use the cache" when first validating the password.
It may be that we want to solve that alongside other questions about how Kibana manages "login" (like tracking failed passwords, etc) and drive it from a Kibana issue.
