### ISSUE TITLE
Clarify auto create index step in getting started

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29914]
*Original comment by @jaymode:*

I think we are complicating the getting started process by having the step to set `action.auto_create_index` in the installation guide. Users seem to be setting this even when they do not need to set it, which makes me thing we're just adding a step unnecessarily.

One example:
https://discuss.elastic.co/t/missing-security-index-not-able-to-change-password/66188

**Comment by jaymode** [comment]
Closing as we've had no additional comments or cases where this was a problem
