### ISSUE TITLE
[DOCS] X-Pack "security", "Watcher", and X-Pack "graph" used weirdly

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29924]
*Original comment by @pickypg:*

!LINK REDACTED

This uses lowercase versions of those section titles. I noticed it with reference to LINK REDACTED, but also in the screenshot you can see it does it for other sections too (`X-Pack graph Troubleshooting` shown at the top).

It also uses "Watcher" without X-Pack.

**Comment by jaymode** [comment]
The documentation has changed so much since this was opened, so I am closing this issue as these inconsistencies have been fixed along the way. We should open up new issues/PRs if others are noticed.
