### ISSUE TITLE
Shield: Log warning on startup if HTTP compression is enabled

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29929]
*Original comment by @spinscale:*

Due to the BREACH attack, which attacks HTTP compression based communication, it might make sense to log a warning on startup of shield enabled elasticsearch, if HTTP compression is enabled.

See LINK REDACTED

**Comment by tomcallahan** [comment]
@jaymode closing this one, please reopen if you think it is still important @spinscale
