### ISSUE TITLE
[Monitoring] Collect Details about Unassigned Shards via Allocation Explain API

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29925]
*Original comment by @pickypg:*

https://www.elastic.co/blog/red-elasticsearch-cluster-panic-no-longer
https://www.elastic.co/guide/en/elasticsearch/reference/5.2/cluster-allocation-explain.html

```http
GET /_cluster/allocation/explain
{
  "index": "myindex",
  "shard": 0,
  "primary": false
}
```

We need to ensure that we do this intelligently in order to avoid creating a storm of new documents while shards are unassigned (e.g., when replicas are unassigned because there's only one node), but the explanation would be incredibly helpful for monitoring.

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
