### ISSUE TITLE
Add indices:data/write/create

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29927]
*Original comment by @jaymode:*

_From @pickypg on July 13, 2015 19:1_

The idea is to prevent reindexing of documents, which can hide updates, to allow data to become immutable.

A new setting could be created to live alongside `indices:data/write/index`:

```
indices:data/write/create
```

**Comment by sachinfrayne** [comment]
+1 for this

**Comment by jkakavas** [comment]
Implemented in https://github.com/elastic/elasticsearch/pull/45806
