### ISSUE TITLE
Confusing terminology for ingestion.

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29921]
*Original comment by @jordansissel:*

As we are moving gradually to a world where all our ingest products can be managed together (I hope we are moving this way), I find a number of terms we use to be very confusing and sometimes contradictory -

* Ingest -- the name `ingest node` seems ... wrong. It doesn't add any ingestion features, it adds data processing capabilities to Elasticsearch's existing ingest (document indexing api) capability.
* Pipeline - In Logstash, this refers to the data flow in and out of Logstash. In Ingest Node, this refers to an ordered set of processors. These (ingest node vs logstash) are not really compatible concepts.

My main point is to identify the problem (bad terminology), not necessarily to provide a solution. However, I will try to make a proposal:

* Rename Ingest Node to `Processor Node`
* Come up with a term that represents the "Processing-only" capabilities of the currently-named Ingest Node and use this term for both Logstash filters as well as Ingest Node's currently-named "pipeline"

**Comment by talevy** [comment]
this issue was closed because, although there may be real naming concerns, there has not been any progress on this discussion. If naming is still a concern, then this should be re-opened
