### ISSUE TITLE
Add doc for setting up curator with Shield

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#29928]
*Original comment by @GlenRSmith:*

Possibly docs/public/clients/curator.asciidoc

This issue is a carry-over from the _elasticsearch-shield repo_ [1]. I had a _PR open_ [2] with a draft, and some suggestions from @jaymode . I'll try to address and issue a PR in the next week or so.

 [1]: LINK REDACTED
 [2]: LINK REDACTED

**Comment by debadair** [comment]
Closing as obsolete.
