### ISSUE TITLE
Store Level Throttling (index level) is not dynamic

### ISSUE THREAD

**Issue by jgagnon1** [elastic/elasticsearch#2998]
# Description

Modifying the max_bytes_per_sec value on as open index has no impact on the throttling level and it doesn't seems to be changed unless the index is close/reopen.

In the documentation it says that that this setting can be set using the index udpate settings API dynamically. So I'm expecting that changing the value apply immediately the change to the setting.

I am seeing a confirmation in the logs;

2013-05-06 13:11:35,938][INFO ][index.store.fs           ] [es97b] [public_XX] updating index.store.throttle.max_bytes_per_sec from [200kb] to [500kb], note, type is [all]

But the throttling is not applied until I close and reopen the index.

# Sample update command
```
curl -XPUT  localhost:9200/public_XX/_settings -d '{"index.store": {
>               "throttle.max_bytes_per_sec": "500kb",
>               "throttle.type": "all"
> }}'
```

**Comment by jpountz** [comment]
Closing: throttling setings have been removed as throttling is now dynamic.
