### ISSUE TITLE
Watcher http input and content type

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#30020]
*Original comment by @jaymode:*

As part of the work to require Content-Type for elasticsearch, I added a BWC compatibility temporary workaround for watches that did not provide this header when using the http input LINK REDACTED 

I think we need to figure out what the right thing to do for 6.0 is with regards to these watches.

**Comment by tomcallahan** [comment]
6.0 is already out

**Comment by s1monw** [comment]
@spinscale I guess it's solved. if not please reopen it.
