### ISSUE TITLE
Add a generic plugin template service

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#30029]
*Original comment by @dakrone:*

We have a handful of services that put templates and try to apply them to existing indices.  It would be great if we had a generic template service that could handle these templates (like for the audit trail index, and the admin index template, and maybe watcher).

**Comment by dakrone** [comment]
I'm going to close this as it's very old, and we _do_ have a generic way of managing templates right now, the `IndexTemplateRegistry`
