### ISSUE TITLE
How to perform security migrations when security is not licensed

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#30021]
*Original comment by @tvernum:*

It is possible to have a `.security` index with meaningful data, but have security turned off due to either:

1. installing an incompatible license, _or_
2. by setting `xpack.security.enabled: false`

If the cluster is upgraded while in this state we treat these two scenarios differently:

- In the first case we will upgrade the security index template & mappings to the current (new) version. 
- In the second case, none of the relevant security components are created, so no upgrades happen.

I think these are probably the right decisions, but they create a complication for upgrades to security data.

In LINK REDACTED and LINK REDACTED we make changes to the data stored in the `.security` index immediately before upgrading the index mapping. We rely on the version number in the old mapping to determine which (if any) migrations should apply.

Because we upgrade the mappings in the first scenario, we need to also perform the migrations at that point, or we will never get another chance to do so (because we won't know which version we're upgrading from). **_But_**, because security is not licensed, the `SecurityActionFilter` will prevent the migration from making calls to any security actions.

In LINK REDACTED I was able to skip over the security action as it was not actually needed, but that cannot be assumed to be true in the general case, and we may need a more complete solution.

My immediate thought is that we may need to have a way to by-pass the license check in `SecurityActionFilter` when performing the migration, but I'm open to other ideas.

**Comment by tvernum** [comment]
Closing.
We haven't run into this since 5.2, and that was specifically because we had default passwords to handle (which isn't true now).
It's not worth worrying about unless we run into the problem again.
