### ISSUE TITLE
Link to license rego page

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#30022]
*Original comment by @markwalkom:*

Can we link to the license rego page from somewhere in the docs. It makes sense to at least have it for Monitoring given it's part of the basic license.

I had to use google to find where it was, and the closest I got from that was to the [subscriptions page](https://www.elastic.co/subscriptions) which then references it.

**Comment by jrodewig** [comment]
[docs issue triage]

Closing this issue. It looks like the registration process has been streamlined.

Please re-open if more discussion or action is needed.
