### ISSUE TITLE
Add Kerberos Realm

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#30025]
*Original comment by @skearns64:*

Kerberos is an increasingly common auth system and is a commonly requested integration for Shield. With pluggable realms, a user could create their own realm that integrates with Kerberos, but having a built-in realm that integrates with Kerberos would make it significantly easier to integrate into these environments.

We should consider making this available.

**Comment by loekvangool** [comment]
Has this been superseded by https://github.com/elastic/elasticsearch/issues/30243 and thus, closable? Many ERs are linked to this one and its predecessor: https://github.com/elastic/x-pack-elasticsearch/issues/424

**Comment by jaymode** [comment]
Yes this one is superseded by #30243. Closing.
