### ISSUE TITLE
Internal indices consistent naming

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#30031]
*Original comment by @uboness:*

There are a bunch of internal indices that are created/managed by xpack (e.g. marvel data, security audit logs and users/roles, etc…). There are also internal indices managed by core (e.g. .scripts). And next to those, there the indices that LS/Beats create by default.

I want us to be consistent on how we name internal indices. Today there’s a mix of patterns and it’s not quite clear what’s the consistent way of naming those indices. It’s mostly revolves around the usage of underscores, dots, and dashes.

Marvel for example, creates indices with the following pattern:
- `.marvel-es-data`
- `.marvel-es-<template version>-<date pattern>`

Watcher:
- `.watches`
- `.watch_history-<template version>-<date pattern>`

Shield:
- `.shield`
- `.shield_audit_log-<date pattern>`

Also, expect to have more internal indices as we grow (centralized logging, reporting index, etc...).

We should the following:
1. Decide on a consistent naming pattern for both “config" indices (indices that typically hold configuration - it’s not time based indices) and time-based indices (e.g. audit logs, monitoring data, etc…)
2. try to keep the number of indices to the minimum. For example, in Marvel we have a data index for ES today (.marvel-es-data)… continuing with this scheme means we’ll have dedicated data indices for LS, Kibana and Beats later on. These are really small indices that can easily be collapse to a single index.

Also, while I plead guilty for introducing the underscores in watcher/shield (there was good intention behind it), if I’m honest about it, I think just using dashes (a la marvel) is somewhat easier on the eye.

I have two proposals:
### Proposal 1:

Marvel:
- `.monitoring-data`
- `.monitoring-es-stats-<template version>-<date pattern>`
- `.monitoring-es-logs-<template version>-<date pattern>`
- `.monitoring-ls-stats-<template version>-<date pattern>`
- `.monitoring-ls-logs-<template version>-<date pattern>`
- `.monitoring-kbn-stats-<template version>-<date pattern>`
- `.monitoring-kbn-logs-<template version>-<date pattern>`
- `.monitoring-bts-stats-<template version>-<date pattern>`
- `.monitoring-bts-logs-<template version>-<date pattern>`
- `.monitoring-cloud-stats-<template version>-<date pattern>`
- `.monitoring-cloud-logs-<template version>-<date pattern>`

Watcher:
- `.watcher (used to be .watches)`
- `.watcher-history-<template version>-<date pattern>`

Shield:
- `.security`
- `.security-audit-log-<date pattern>`
### Proposal 2:

Here we collapse all the config indices into a single .xpack index (and still keep the same timebased indices)
- `.xpack` - holds watches, users, roles, etc...

Marvel:
- `.monitoring-data`
- `.monitoring-es-stats-<template version>-<date pattern>`
- `.monitoring-es-logs-<template version>-<date pattern>`
- `.monitoring-ls-stats-<template version>-<date pattern>`
- `.monitoring-ls-logs-<template version>-<date pattern>`
- `.monitoring-kbn-stats-<template version>-<date pattern>`
- `.monitoring-kbn-logs-<template version>-<date pattern>`
- `.monitoring-bts-stats-<template version>-<date pattern>`
- `.monitoring-bts-logs-<template version>-<date pattern>`
- `.monitoring-cloud-stats-<template version>-<date pattern>`
- `.monitoring-cloud-logs-<template version>-<date pattern>`

Watcher:
- `.watcher-history-<template version>-<date pattern>`

Shield:
- `.security-audit-log-<template version>-<date pattern>`

**Comment by talevy** [comment]
We discussed this in FixItThursday and concluded that although this would be nice, it does not help in further development and would potentially only make things difficult for backwards compatibility.

If any of the original authors disagrees, feel free to continue the discussion and reopen after close!
