### ISSUE TITLE
Graph - expanded blacklist features

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#30037]
*Original comment by @markharwood:*

A user ran into a usability issue where they [wanted to exclude all vertices that were numbers from the UI](https://discuss.elastic.co/t/using-regular-expressions-to-blacklist-terms/48604)

They suggested using a regex-based filter as an extension to the existing blacklist capability.
This could be challenging to implement server-side because we rely on terms/significant terms aggs that take regex OR string lists but not both as exclude clauses. 
Maybe this could be implemented as a client-side only filtering rule (along with many other possible filters eg. Gephi allows filtering by properties of nodes).

**Comment by polyfractal** [comment]
I'm going to close this.  We haven't seen anymore requests for this feature and it has been open for a long time. :)
