### ISSUE TITLE
Graphical user/role setup docs

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#30043]
*Original comment by @eskibars:*

Currently all of our documentation on how to add/remove users/roles is API-centric (e.g. [this](https://www.elastic.co/guide/en/x-pack/current/native-realm.html#managing-native-users0)).  It'd be nice to have screenshot-driven walk-throughs of how to do these actions

**Comment by jrodewig** [comment]
[docs issue triage]

This is now covered in https://www.elastic.co/guide/en/kibana/current/kibana-role-management.html.

Please re-open if more discussion or action is needed.
