### ISSUE TITLE
[Monitoring] Validate Templates/Pipelines/Version Nightly for HTTP Exporter

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#30049]
*Original comment by @pickypg:*

The HTTP exporter currently assumes that once it has successfully submitted (or found) the templates / pipeline(s) / resources in general, then it does not need to ever do it again _unless a connection fails_.

We should however check the resources every now-and-then just to be safe. This is in direct response to a scenario where a user seemingly did blew away their templates after the exporter successfully created them in 2.x, without ever restarting the production cluster. They apparently were testing disaster recovery of the monitoring cluster.

In 2.x, the current behavior is a little more naive:

- Once successful, it was impossible to invalidate them without restarting the exporter (generally meaning the node) unless a failure occurred while _opening_ a connection.

In 5.x, the current behavior is a little more likely to catch this scenario:

- Any connection failure results in the resources being rechecked.

- [ ] The resources should be periodically rechecked just in case the interval is set significantly higher and the templates are removed somehow (e.g., manually deleting them or disaster).

LINK REDACTED

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
