### ISSUE TITLE
Monitoring should use Rollover API

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elasticsearch#30045]
*Original comment by @skearns64:*

Today, we create daily indexes for ES and Kibana, but this is often wasteful, as these tend to end up as rather small indexes/shards that take up unnecessary cluster resources to manage. Using the rollover API, we could more easily specify a reasonable target number of docs that, when exceeded, would cause a new index to be created.

Using the rollover API does have the drawback in that it is less efficient to maintain a fixed history duration, so we'd need to decide if we were comfortable with delete-by-query before undertaking this.

**Comment by jakelandis** [comment]
closing in favor of https://github.com/elastic/elasticsearch/issues/38470
