### ISSUE TITLE
Elasticsearch service failed status=78/n/a

### ISSUE THREAD

**Issue by ThompsonLau** [elastic/elasticsearch#30124]
I installed Elasticsearch 6.2.4 on CentOS 7.0

When I start it, I got the following error via systemd,
Apr 25 18:24:18 QVELKSRH01 systemd[1]: elasticsearch.service: main process exited, code=exited, status=78/n/a
Apr 25 18:24:18 QVELKSRH01 systemd[1]: Unit elasticsearch.service entered failed state.
Apr 25 18:24:18 QVELKSRH01 systemd[1]: elasticsearch.service failed.

How to solve it? thanks

**Comment by romseygeek** [comment]
Hi @ThompsonLau , we try and use github for bug reports and feature requests.  Please ask this question instead on our forums at https://discuss.elastic.co
