### ISSUE TITLE
Documentation wrong: still describes index=analyzed/not_analyzed for type string

### ISSUE THREAD

**Issue by OlivierPetri** [elastic/elasticsearch#30122]
**Elasticsearch version**: 6.2

**Plugins installed**: []

**JVM version** (`java -version`): 8

**OS version** (`uname -a` if on a Unix-like system): Windows Server 2016 (or whatever you like)

**Description of the problem including expected versus actual behavior**:

Documentation still explains to model type "string" with a property "index" set to "analyzed", "not_analyzed" or "no", whereas it appears that neither is valid anymore since version 5.0

From what I read in the wild wild web it should be type=text (for analyzed) or type=keyword (for not_analyzed), and i guess "no" has become index=false.

Thus the documentation is currently plain wrong, and pushes the interested user into the abyss of google.

**Steps to reproduce**:

Wrong explanation can be found at least here: https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-intro.html

Other places are of course possible.

**Provide logs (if relevant)**:

**Comment by romseygeek** [comment]
This was fixed in the 6.4 docs.  The original issue refers to the Elasticsearch Definitive Guide, which has not been updated past version 2.x
