### ISSUE TITLE
Require acknowledgement/confirmation before starting trial license

### ISSUE THREAD

**Issue by tbrooks8** [elastic/elasticsearch#30134]
Add the requirement that acknowledgement is passed in start_trial api. Additionally add acknowledgement messages when ack is not passed.

**Comment by jasontedor** [comment]
@tbrooks8 I think that this is closed by #30198?

**Comment by tbrooks8** [comment]
There is an open PR on master (#30218). But the 6.3 and 6.x work is complete.

**Comment by jasontedor** [comment]
I missed that one; thanks for clarifying!

**Comment by tbrooks8** [comment]
This is complete. Closing.
