### ISSUE TITLE
VersionUtilsTests.testGradleVersionsMatchVersionUtils fails on 6.x intake

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#30133]
5 failures within 24 hours

The most recent CI failures:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1608/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1606/console

Reproduction line:
./gradlew :test:framework:test   -Dtests.seed=AD2D0BA6D0112AF0   -Dtests.class=org.elasticsearch.test.VersionUtilsTests   -Dtests.method="testGradleVersionsMatchVersionUtils"   -Dtests.security.manager=true   -Dtests.locale=fr-LU   -Dtests.timezone=America/St_Thomas

It seems that `5.6.10` in not included in `bwcVersions.wireCompatible` versions:

FAILURE 0.18s | VersionUtilsTests.testGradleVersionsMatchVersionUtils <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<[5.0.0, 5.0.1, 5.0.2, 5.1.1, 5.1.2, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.4.0, 5.4.1, 5.4.2, 5.4.3, 5.5.0, 5.5.1, 5.5.2, 5.5.3, 5.6.0, 5.6.1, 5.6.2, 5.6.3, 5.6.4, 5.6.5, 5.6.6, 5.6.7, 5.6.8, 5.6.9, 5.6.10, 6.0.0, 6.0.1, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.1.4, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.2.4]> but was:<[5.0.0, 5.0.1, 5.0.2, 5.1.1, 5.1.2, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.4.0, 5.4.1, 5.4.2, 5.4.3, 5.5.0, 5.5.1, 5.5.2, 5.5.3, 5.6.0, 5.6.1, 5.6.2, 5.6.3, 5.6.4, 5.6.5, 5.6.6, 5.6.7, 5.6.8, 5.6.9, 6.0.0, 6.0.1, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.1.4, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.2.4]>
   >    at __randomizedtesting.SeedInfo.seed([AD2D0BA6D0112AF0:78EE11A31D01673E]:0)
   >    at org.elasticsearch.test.VersionUtilsTests.testGradleVersionsMatchVersionUtils(VersionUtilsTests.java:319)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   >    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   >    at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by mayya-sharipova** [comment]
For now, silencing this test in 6.x:
```
@AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/30133")
public void testGradleVersionsMatchVersionUtils() {
```

**Comment by nik9000** [comment]
I'll have a look!

**Comment by nik9000** [comment]
@hub-cap will do it instead.
