### ISSUE TITLE
QA .bats Files use symlinks, which confuse Git on Windows

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch#30147]
This didn't used to be an issue for me, but something about Windows or our repository changed relative to `git` and now the random slew of `.bats` files that are symlinks are making it impossible to perform `git rebase` because it wants me to stash my "typechanged" files, which I can only do from Windows Subsystem for Linux (WSL) now.

Relevant Files

```
qa/vagrant/src/test/resources/packaging/tests/25_tar_plugins.bats
qa/vagrant/src/test/resources/packaging/tests/50_modules_and_plugins.bats
x-pack/qa/vagrant/src/test/resources/packaging/tests/20_tar_bootstrap_password.bats
x-pack/qa/vagrant/src/test/resources/packaging/tests/25_package_bootstrap_password.bats
x-pack/qa/vagrant/src/test/resources/packaging/tests/30_tar_setup_passwords.bats
x-pack/qa/vagrant/src/test/resources/packaging/tests/35_package_setup_passwords.bats
x-pack/qa/vagrant/src/test/resources/packaging/tests/40_tar_certgen.bats
x-pack/qa/vagrant/src/test/resources/packaging/tests/45_package_certgen.bats
```

**Comment by rjernst** [comment]
The new java based packaging tests should eliminate the need for symlinks. Since there is nothing actionable here, I think we should close this in favor of that work. /cc @andyb-elastic

**Comment by jasontedor** [comment]
Also I would add that we have not changed anything here. Those are the same symlinks in non x-pack that have been there for awhile, and the x-pack ones are only moves from the old repository.
