### ISSUE TITLE
release-tests fail on 6.3 with license.key not set for ':x-pack:plugin:core'

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#30153]
FAILURE elastic/elasticsearch on 6.3 release-tests

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+release-tests/3/console

```
17:38:08 * What went wrong:
17:38:08 A problem occurred evaluating project ':x-pack:plugin:core'.
17:38:08 > Property license.key must be set for release build
```

**Comment by jasontedor** [comment]
This is an internal infra issue. I will follow up with them internally.

**Comment by jasontedor** [comment]
I opened an internal pull request and will close this issue as that pull request can serve as tracking for this issue now.

**Comment by nspatilk29** [comment]
I am facing same issue, 
Error:
"What went wrong:
A problem occurred evaluating project ':x-pack:plugin:core'.
Property license.key must be set for release build"

I am using Gradle 4.7, ES 6.3.1, even tried with Gradle 4.9.

tried with below commands, none worked. Am I missing something.

gradlew assemble -Dbuild.snapshot=false
gradle assemble -Dbuild.snapshot=false

**Comment by jasontedor** [comment]
@nspatilk29 You can’t build a release (non-snapshot build) without a signing key.

**Comment by nspatilk29** [comment]
Thanks Jason, issue is resolved!!

**Comment by minglinlu** [comment]
> signing key

How to get a signing key?

**Comment by jasontedor** [comment]
@minglinlu Why do you think that you need a signing key? They are needed for official release builds only.
