### ISSUE TITLE
Ability to stop and start a cluster without shard movement

### ISSUE THREAD

**Issue by antonpious** [elastic/elasticsearch#30162]
While we have both a  [Rolling Updates](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/rolling-upgrades.html) and  [Full Restart](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/restart-upgrade.html)

What is needed from a cost perspective is the ability to stop a cluster and then start it again without having to have any replica shard movement.

This feature would help in the following use cases
1. Weekend shut down to save cost in a cloud provider
2. Ability to backup an instance like Prod using disk backup and restore the instance in another environment like Test.

Note:
The problem of shard movement happens only when there is a replica shards, the primary shard do come up fine in the nodes but the replica shards always moves if nodes in the cluster are shut down more than a minute.

**Comment by colings86** [comment]
As described in your links we suggest you disable allocation before shutting down nodes and re-enable it when starting nodes up:
```
PUT _cluster/settings
{
  "persistent": {
    "cluster.routing.allocation.enable": "none"
  }
}
```
This should satisfy your needs if I'm not mistaken?

**Comment by antonpious** [comment]
I too thought the same the setting doesn't work as designed. At present the only way for this to work is to enable this for the cluster, we stop one node, start the node the primary shard gets allocated,  then enable the setting the replica gets allocated. We then keep repeating for each node. So in a rolling restart this approach works but not when all the nodes are shut down and started.

At present the primary gets allocated when we bring back the cluster and start all the nodes. So if we have a replication of 1 and there are 100 Primary shards and 100 Secondary Shards, exactly 100 shards gets into active primary shards and 100 goes into unassigned shards. Now when you enable the routing allocation the shard movement happens mostly for the replica shards but then it goes over board and sometimes moves the primary shards too may be for shard balancing between nodes as described below.

There is also another behavior that happens when we restart the entire cluster, the cluster tries to balance the number of shards across all the nodes irrespective of shard size. Just the number of nodes.

**Comment by DaveCTurner** [comment]
The behaviour that you describe suggests that you may not be following the [complete procedure for a full cluster restart](https://www.elastic.co/guide/en/elasticsearch/reference/current/restart-upgrade.html), or that there may be ongoing indexing activity while the cluster is not in a green state. It's important to follow all of the steps in the manual, including the fully-successful synced-flush and the wait-for-green at the end, and also important not to perform any indexing while the cluster is not green as this may cause replicas to require recovery. Can you confirm that you're following all these steps?

**Comment by antonpious** [comment]
We did the test multiple times, all activities are stopped, the steps including the Synced  Flush which returns no error but the same result. I don't think the analysis is correct, if this is due to Synced Flush issue every replica shard wont start the movement only a few of them would. The other is the same works when we restart one by one on a rolling upgrade. Right now the cluster doesn't understand replica shards are local and keeps moving the shards. There is no way to force pick existing replica shard only and only if error start the shard movement. It also doesn't say why it has started the shard movement.

**Comment by DaveCTurner** [comment]
> There is no way to force: pick existing replica shard only

On the contrary, this is supposed to happen automatically, and does so in the tests that I've run. We need to see some specifics here. Please could you re-run your test with the following modifications:

1. Please first increase the logging levels as follows:

```
PUT /_cluster/settings
{
  "persistent": {
    "logger.org.elasticsearch.gateway.ReplicaShardAllocator": "TRACE",
    "logger.org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator": "TRACE",
    "logger.org.elasticsearch.gateway.GatewayAllocator": "TRACE"
  }
}
```

2. After disabling allocation, but before shutting the cluster down, please capture the output of

    GET /_stats?level=shards
    GET /_shard_stores?status=green,yellow,red

3. After restarting the cluster, but before re-enabling allocation, please again capture the output of

    GET /_stats?level=shards
    GET /_shard_stores?status=green,yellow,red

4. After allocation is re-enabled, please allow balancing to complete.

5. Once balancing is complete, please reduce the logging levels back to their defaults:

```
PUT /_cluster/settings
{
  "persistent": {
    "logger.org.elasticsearch.gateway.ReplicaShardAllocator": null,
    "logger.org.elasticsearch.cluster.routing.allocation.allocator.BalancedShardsAllocator": null,
    "logger.org.elasticsearch.gateway.GatewayAllocator": null
  }
}
```

Then could you send the logs from the elected master node and the outputs of the commands above. Ideally zip them up and attach them to this ticket, but if that's not possible then please let us know and we can make alternative arrangements.

**Comment by DaveCTurner** [comment]
Additionally, can you just confirm that you have not changed the value of `cluster.routing.allocation.allow_rebalance` from the default of `indices_all_active`?

**Comment by antonpious** [comment]
Seems design wise the logic is correct. You are saying that by default both the primary and secondaries should be [allocated](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/shards-allocation.html#_shard_rebalancing_settings)  before the shard movement. If this is the case, why do we even need to set this setting. 
`"cluster.routing.allocation.enable":` "none"
The cluster should first try to do the what is the default, what else can cause the shard movement?

Please find attached the [logs](https://github.com/elastic/elasticsearch/files/1986419/E-log.zip)

**Comment by tvernum** [comment]
> If this is the case, why do we even need to set this setting.
"cluster.routing.allocation.enable": "none"
The cluster should first try to do what is the default, what else can cause the shard movement?

Forming a cluster is not an atomic step.

Assume you have a 5 node cluster, where all nodes are master eligible, and `minimum_master_nodes` is set 3 to (the recommended value for a cluster of that topology).

Then you have a working, viable cluster as soon as any 3 nodes are online and have established connections with one another. Those nodes don't know whether or not you are planning to bring the other 2 nodes online (e.g. it might be the case that those 2 machines failed to restart after a power outage), so the cluster will decide to reallocate/recover shards as necessary to turn the 3 node cluster into a correctly balanced cluster.
When you will bring on a 4th node, the cluster will make new decisions about shard allocations.  
Whhen you bring on the 5th node, it happens again.
 
What you want is for the allocations to remain static until you've brought all nodes online, and then have the cluster do whatever it needs to in order to sort things out.

**Comment by antonpious** [comment]
Yep, finally the details !!!, your explanation clearly explains the behavior that is happening.

We have a 7 node cluster and depending on the master setting  either 3 or 5 the cluster is formed and as soon as its formed the cluster is thinking and making its decision assuming something drastic has happened to the cluster and it needs to bring itself alive as fast as possible.

This also explains the automatic rebalancing of shards equally as now the Shard Balancing Heuristics also kicks in due the unbalanced nature of the cluster and it now tries to balance as more and more nodes join the cluster.

The same doesn't happen when we shut it down one by one as the master quorum is maintained and the imbalance of cluster is not present for the balancing to take place.

Yes, you nailed it, what is needed is a difference between a first time cluster formation and a second time cluster formation. So an already formed cluster should wait for all the member nodes to join before making decision.  Either is can be a manual setting or a time bound setting it would be good.
It can ask; Of the 7 members 1 member did not come up can I proceed with the rebalancing and then continue its operations or provide healing diagnostic like hadoop master on why the node could not join the cluster and what can be done to join the cluster by removing violating entries etc.

Thanks a lot for the collaboration...

**Comment by ywelsch** [comment]
> Either it can be a manual setting or a time bound setting it would be good.

Have a look at the [`recover_after_*` settings](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html)

**Comment by DaveCTurner** [comment]
This thread is becoming increasingly off-topic for Github which we prefer to keep for bug reports and much more specific feature requests. There's not obviously any action required here and there seems to be some misunderstandings about how Elasticsearch is designed. I suggest we move to a thread on https://discuss.elastic.co to explore this further and only return to Github if a particular issue can be identified.

> This also explains the automatic rebalancing of shards equally as now the Shard Balancing Heuristics also kicks in due the unbalanced nature of the cluster and it now tries to balance as more and more nodes join the cluster.

Shard balancing does not (by default) kick in until the cluster is completely healthy, i.e. until all of the shards are allocated:

https://github.com/elastic/elasticsearch/blob/4b36ea74334e2664412af3540a64b82e0845e710/server/src/main/java/org/elasticsearch/cluster/routing/allocation/decider/ClusterRebalanceAllocationDecider.java#L120-L133

> So an already formed cluster should wait for all the member nodes to join before making decision.

This is, indeed, how it is designed to work. @antonpious please provide the logs we requested in a thread on https://discuss.elastic.co and we'll continue the discussion there. The attachment above includes the stats outputs that we asked for, but not the logs, and without them we can only speculate about the behaviour that you are seeing.

**Comment by antonpious** [comment]
Opened a discussion thread
https://discuss.elastic.co/t/ability-to-stop-and-start-a-cluster-without-shard-movement/134375
Not able to upload the logs there so uploading it here
[es-logs.zip](https://github.com/elastic/elasticsearch/files/2067271/es-logs.zip)

**Comment by antonpious** [comment]
Apologies for the late responses but have to restart this again. [Ability to stop and start a cluster without shard movement part2](https://discuss.elastic.co/t/ability-to-stop-and-start-a-cluster-without-shard-movement-part2/143767)


[shard_logs.zip](https://github.com/elastic/elasticsearch/files/2275907/shard_logs.zip)
