### ISSUE TITLE
Allow ingest processors to delete events, or to produce new events

### ISSUE THREAD

**Issue by ramon-garcia** [elastic/elasticsearch#30173]
Hello, 

I have tried to write a processor to include in a ingest pipeline, but I see that one can only modify an event, but one cannot produce new events or delete.

I can implement the enhancement myself, but, is it likely to be accepted?

**Comment by dadoonet** [comment]
I think that's similar to https://github.com/elastic/elasticsearch/issues/23726 which has been closed.

**Comment by danielmitterdorfer** [comment]
After reading #23726, I get that this might be tricky to implement and (personally) I am also not sure whether Elasticsearch is really the right place where such things should be done. However, I think we should gather more team input here, hence labelling as "Discuss".

**Comment by nik9000** [comment]
Looking at how ingest is implemented this seems pretty difficult. I think this is something that Logstash was purpose built to do so you are probably better off doing it there. The reason this is difficult is that ingest is built to modify a single document and it'd be pretty complex to turn that into returning multiple documents. To properly implement this your request to index a single document would basically turn into a bulk. Internally, I think we could do it but it'd be a little tricky to get right. I think what is more tricky is what we'd return in the response. We'd want to tell the user about all the documents and that'd be a pretty huge change. But logstash is kind of built for this already....
