### ISSUE TITLE
Add ability to "freeze" and "unfreeze" an index to consume fewer resources on a machine

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#30188]
For deployments that get larger and larger, sometimes it is helpful to be able
to take a number of indices and put them in a low-resource state such that they
are still available, however, they don't take as many resources as a regular
index does. We should add a feature that allows us to put indices in this state
(frozen) and then put them back to a regular state (thaw) if desired.

While in the frozen state, only read operations will be permitted on the index.

This would be similar to what the `/_close` API does, however, instead of the
index being completely inaccessible, a frozen index can still be searched and
have aggregations performed on the data. Additionally, rather than the data on
disk not being balanced/routed in the cluster, a frozen index would be treated
similar to a regular index.

There are a few different steps for this (more may be needed):

- [x] Add APIs for `/_freeze` and `/_thaw`
- [x] Rename `/_thaw` to `/_unfreeze`
- [x] Add a `FROZEN` threadpool with a single worker that all search requests to frozen indices use
- [ ] Block indexing actions when an index is frozen
- [ ] Add a specialized engine that does not keep resources for a frozen shard in memory except while a search is being performed
- [ ] Switch "get" operations on frozen shards to use the FROZEN threadpool
- [ ] Collapse `/_freeze`, `/_unfreeze`, `/_close`, and `/_open` into a single REST/transport handler
- [ ] Add an option for `IndicesOptions` to allow including/excluding frozen indices from wildcards (`expandToFrozenIndices`)

**Comment by chandlermelton** [comment]
This sounds like a great idea!

**Comment by cdahlqvist** [comment]
> Add a FROZEN threadpool with a single worker that all search requests to frozen indices use

@dakrone I can see this being appropriate if I have a mix of frozen and normal indices on a node (which may be a very common deployment pattern). If we however were to implement a dedicated frozen tier where some nodes only have frozen indices, would this then not perhaps be too retrictive?

**Comment by dakrone** [comment]
This issue is being closed in favor of #31141 - rather than add new APIs we'd like to enhance our current closed index implementation.
