### ISSUE TITLE
Docs: X-Pack LDAP Parameter "realms" missing from documentation

### ISSUE THREAD

**Issue by Jymit** [elastic/elasticsearch#30199]
Also making mention of https://github.com/elastic/docs/issues/244 here FAO documentation teams.
cc @MorrieAtElastic 

1. In this document we pertain to `xpack.security.authc.active_directory.files.role_mapping` however this is broken and misleading. https://www.elastic.co/guide/en/x-pack/current/mapping-roles.html

2. Here is more so correct `xpack.security.authc.realms.` https://www.elastic.co/guide/en/x-pack/current/active-directory-realm.html#_configuring_an_active_directory_realm

Please see this as an ask to update doc 1 so there are no discrepancies between the two.
Thanks!

**Comment by jaymode** [comment]
@lcawl can you take a look at this?
