### ISSUE TITLE
Logging dashcam functionality

### ISSUE THREAD

**Issue by geekpete** [elastic/elasticsearch#30197]
It would be great to have the ability to flip verbose logging on but then have a way to trigger retaining logs x seconds before and after an interesting event timestamp and have a very short retention of logging events otherwise.

So much like the way a car dashcam works, it has a very short retention (eg a 5 or 10 minute recording loop) but then also has the ability for the user to hit a button to store the last period of footage in the event they have an accident, sometimes the retention of footage is also automatically activated by a crash detector that measures gforce,etc.

Something similar in Elasticsearch would allow users to enable verbose logging (whatever type of logging, audit or slowlogs,etc), have logs be stored on a very tight retention to avoid consuming too many resources then have a way to trigger keeping logs surrounding a particular event, so retaining some measure of logs before and after the target event time.

An API to trigger the retention would be handy and could be fed parameters of what and how much to retain.

Such a functionality might also tie into X-Pack Machine Learning perhaps, so that interesting events or anomalies could be automatically detected and trigger log retention around those events.

Even if verbose logging is expensive, it might be turned on temporarily to catch some interesting events then turned off, using a feature like this.
Filtering might also be applied when a range of logs are triggered to be kept.

The triggered retention might also be tiered somehow, so that surrounding logs of interesting events  from the initial logging stream are retained for a longer period, but if some other pattern of events occur the the second level retention events could be retained permanently or for a longer retention.
Keep logs in proximitiy of an x event.
Keep retained x event logs in proximity to a y event.

**Comment by DaveCTurner** [comment]
I think this can be achieved in Elasticsearch today by tuning the log4j configuration to write more verbose logs to an appender with a sufficiently enthusiastic rollover policy and a short retention window.

Of course this still imposes the overhead of formatting all the extra messages and writing them out. I think it's essential to format the messages eagerly in any case: if not, the objects needed to format them later may mutate (yielding misleading messages) and the formatted messages may take up much less space than the data we need to format them (e.g. [a copy of the whole cluster state](https://github.com/elastic/elasticsearch/blob/e1e8cf382f629ae9576cd5b1d7a8add023e7dea6/server/src/main/java/org/elasticsearch/cluster/service/ClusterApplierService.java#L421-L425)). Writing the verbose messages out only to delete them a short while later _sounds_ expensive, but I'm not sure it'll be so bad if it only hits the filesystem cache (i.e. goes to a separate filesystem from the data paths to avoid this data being caught up in `fsync()` calls).

I'm adding the discuss label to raise this with the wider team.

**Comment by jasontedor** [comment]
We discussed this during our weekly team discussion meeting (Fix-it-Friday) and concluded that we should not introduce this functionality:
 - we think that the cost and complexity this feature is not worth it given that we do not see it being used much, and our assumption that most of the time when an "interesting" situation occurs an operator is not going to have time to grab the logs before they roll again
 - trace logging is performance taxing on Elasticsearch when it is under any kind of load, even on fast disks, so it's unlikely that anyone would have this feature enabled given the implications there
