### ISSUE TITLE
Missing params in rest-api-specs

### ISSUE THREAD

**Issue by morjo** [elastic/elasticsearch#30202]
There are some missing params in the [rest-api-specs](https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/src/main/resources/rest-api-spec/api)

cat.shards.json is missing: time
cat.indices.json is missing: time
cat.nodes.json is missing: bytes and time

**Comment by morjo** [comment]
Without this in place we cannot use those features in the Perl API.

**Comment by javanna** [comment]
hi @morjo would you like to send a PR to fix this?

**Comment by jrodewig** [comment]
[docs issue triag]

Leaving this open as it's still relevant.
