### ISSUE TITLE
Couldn't start the elasticsearch server in kibana development environment

### ISSUE THREAD

**Issue by aaronoah** [elastic/elasticsearch#30213]
**Describe the feature**:

In my kibana environment I couldn't start the elasticsearch server.

**Elasticsearch version** (`bin/elasticsearch --version`): 

Version: 7.0.0-alpha1-SNAPSHOT, Build: default/tar/80e0e64/2018-04-26T21:18:22.372360Z, JVM: 1.8.0_60

**Plugins installed**: []

**JVM version** (`java -version`):

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Darwin MacBook-Pro-3.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

In kibana project, I try to run `yarn run elasticsearch` and it couldn't start the server and said `Fatal error: Client request error: connect ECONNREFUSED 127.0.0.1:80`

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. clone the kibana repo, install node v8.9.4 and latest yarn
 2. run `yarn kbn bootstrap` to install dependencies
 3. run `yarn run elasticsearch` to run elasticsearch

**Provide logs (if relevant)**:

yarn run v1.6.0
$ grunt esvm:dev:keepalive
Running "esvm:dev:keepalive" (esvm) task
starting up "dev" cluster
Keeping elasticsearch alive, to shutdown press command/control+c
(node:15040) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
INFO -  - cluster - Downloading & installing from "master" branch.
INFO -  - cluster - Installing plugins
INFO -  - cluster - Starting 1 nodes
INFO - ? - ? - [2018-04-27T13:18:43,531][INFO ][o.e.n.Node               ] [] initializing ...
INFO - oHcyjWO - node_environment - using [1] data paths, mounts [[/ (/dev/disk1s1)]], net usable_space [10.4gb], net total_space [112.8gb], types [apfs]
INFO - oHcyjWO - node_environment - heap size [990.7mb], compressed ordinary object pointers [true]
INFO - oHcyjWO - node - node name derived from node ID [oHcyjWOjTBGfP6s1BLZCFg]; set [node.name] to override
INFO - oHcyjWO - node - version[7.0.0-alpha1-SNAPSHOT], pid[15097], build[default/tar/80e0e64/2018-04-26T21:18:22.372360Z], OS[Mac OS X/10.13.4/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_60/25.60-b23]
INFO - oHcyjWO - node - JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/var/folders/nv/18gx6kgn75gdt3tn37pg8q1h0000gn/T/elasticsearch.f8sdeHy3, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m,-Des.path.home=/Users/AaronZhao/Git/kibana/esvm/dev/branch-master, -Des.path.conf=/var/folders/nv/18gx6kgn75gdt3tn37pg8q1h0000gn/T/libesvm-118327-15040-1c3crya.c0sdf, -Des.distribution.flavor=default, -Des.distribution.type=tar]
WARN - oHcyjWO - node - version [7.0.0-alpha1-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
INFO - oHcyjWO - plugins_service - loaded module [aggs-matrix-stats]
INFO - oHcyjWO - plugins_service - loaded module [analysis-common]
INFO - oHcyjWO - plugins_service - loaded module [ingest-common]
INFO - oHcyjWO - plugins_service - loaded module [lang-expression]
INFO - oHcyjWO - plugins_service - loaded module [lang-mustache]
INFO - oHcyjWO - plugins_service - loaded module [lang-painless]
INFO - oHcyjWO - plugins_service - loaded module [mapper-extras]
INFO - oHcyjWO - plugins_service - loaded module [parent-join]
INFO - oHcyjWO - plugins_service - loaded module [percolator]
INFO - oHcyjWO - plugins_service - loaded module [rank-eval]
INFO - oHcyjWO - plugins_service - loaded module [reindex]
INFO - oHcyjWO - plugins_service - loaded module [repository-url]
INFO - oHcyjWO - plugins_service - loaded module [transport-netty4]
INFO - oHcyjWO - plugins_service - loaded module [x-pack-core]
INFO - oHcyjWO - plugins_service - loaded module [x-pack-deprecation]
INFO - oHcyjWO - plugins_service - loaded module [x-pack-graph]
INFO - oHcyjWO - plugins_service - loaded module [x-pack-logstash]
INFO - oHcyjWO - plugins_service - loaded module [x-pack-ml]
INFO - oHcyjWO - plugins_service - loaded module [x-pack-monitoring]
INFO - oHcyjWO - plugins_service - loaded module [x-pack-rollup]
INFO - oHcyjWO - plugins_service - loaded module [x-pack-security]
INFO - oHcyjWO - plugins_service - loaded module [x-pack-sql]
INFO - oHcyjWO - plugins_service - loaded module [x-pack-upgrade]
INFO - oHcyjWO - plugins_service - loaded module [x-pack-watcher]
INFO - oHcyjWO - plugins_service - no plugins loaded
INFO - oHcyjWO - file_roles_store - parsed [0] roles from file [/var/folders/nv/18gx6kgn75gdt3tn37pg8q1h0000gn/T/libesvm-118327-15040-1c3crya.c0sdf/roles.yml]
INFO - controller/15134 - cpp_log_message_handler - [Main.cc@109] controller (64 bit): Version 7.0.0-alpha1-SNAPSHOT (Build 68586458b2a1f6) Copyright (c) 2018 Elasticsearch BV
INFO - oHcyjWO - discovery_module - using discovery type [zen]
INFO - oHcyjWO - node - initialized
INFO - oHcyjWO - node - starting ...
INFO - oHcyjWO - transport_service - publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
INFO - oHcyjWO - master_service - zen-disco-elected-as-master ([0] nodes joined)[, ], reason: master node changed {previous [], current [{oHcyjWO}{oHcyjWOjTBGfP6s1BLZCFg}{nNLQLvmCR_O4GNWREl-QKQ}{127.0.0.1}{127.0.0.1:9300}{ml.machine_memory=8589934592, ml.max_open_jobs=20, ml.enabled=true}]}
INFO - oHcyjWO - cluster_applier_service - master node changed {previous [], current [{oHcyjWO}{oHcyjWOjTBGfP6s1BLZCFg}{nNLQLvmCR_O4GNWREl-QKQ}{127.0.0.1}{127.0.0.1:9300}{ml.machine_memory=8589934592, ml.max_open_jobs=20, ml.enabled=true}]},reason: apply cluster state (from master [master {oHcyjWO}{oHcyjWOjTBGfP6s1BLZCFg}{nNLQLvmCR_O4GNWREl-QKQ}{127.0.0.1}{127.0.0.1:9300}{ml.machine_memory=8589934592, ml.max_open_jobs=20, ml.enabled=true} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)[, ]]])
INFO - oHcyjWO - security_netty_4_http_server_transport - publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}
INFO - oHcyjWO - node - started
Fatal error: Client request error: connect ECONNREFUSED 127.0.0.1:80
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jasontedor** [comment]
The node started fine, but you're trying to hit port 80 and Elasticsearch listens on port 9200 by default:

> Fatal error: Client request error: connect ECONNREFUSED 127.0.0.1:80

This is not an Elasticsearch bug. Elastic provides a [forum](https://discuss.elastic.co) for asking general questions and instead prefers to use GitHub only for verified bug reports and feature requests. There's an active community there that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

Finally, please don't cross post (elastic/kibana#18643), it creates fractured conversations.

**Comment by hmiyakoshi0803** [comment]
I have an error too.
And my elastic search node didn't start.
What is wrong?

[elasticsearch@dev01 kibana]$ yarn elasticsearch
yarn run v1.6.0
$ grunt esvm:dev:keepalive
Running "esvm:dev:keepalive" (esvm) task
starting up "dev" cluster
Keeping elasticsearch alive, to shutdown press command/control+c
INFO -  - cluster - Downloading & installing from "6.x" branch.
INFO -  - cluster - Installing plugins
INFO -  - cluster - Starting 1 nodes
INFO - ? - ? - [2018-05-06T14:50:35,299][INFO ][o.e.n.Node               ] [] initializing ...
INFO - SXlY6FY - node_environment - using [1] data paths, mounts [[/ (rootfs)]], net usable_space [95.2gb], net total_space [99.9gb], types [rootfs]
INFO - SXlY6FY - node_environment - heap size [1007.3mb], compressed ordinary object pointers [true]
INFO - SXlY6FY - node - node name derived from node ID [SXlY6FYCSfWh5pQzBRnCGw]; set [node.name] to override
INFO - SXlY6FY - node - version[6.4.0-SNAPSHOT], pid[3729], build[default/tar/cda131b/2018-05-05T21:18:06.567556Z], OS[Linux/3.10.0-862.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_171/25.171-b10]
INFO - SXlY6FY - node - JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.30eV9OXA, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Des.path.home=/opt/kibana/esvm/dev/branch-6.x, -Des.path.conf=/tmp/libesvm-11846-3603-xc2qhc.gd6jmgf1or, -Des.distribution.flavor=default, -Des.distribution.type=tar]
WARN - SXlY6FY - node - version [6.4.0-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
INFO - SXlY6FY - plugins_service - loaded module [aggs-matrix-stats]
INFO - SXlY6FY - plugins_service - loaded module [analysis-common]
INFO - SXlY6FY - plugins_service - loaded module [ingest-common]
INFO - SXlY6FY - plugins_service - loaded module [lang-expression]
INFO - SXlY6FY - plugins_service - loaded module [lang-mustache]
INFO - SXlY6FY - plugins_service - loaded module [lang-painless]
INFO - SXlY6FY - plugins_service - loaded module [mapper-extras]
INFO - SXlY6FY - plugins_service - loaded module [parent-join]
INFO - SXlY6FY - plugins_service - loaded module [percolator]
INFO - SXlY6FY - plugins_service - loaded module [rank-eval]
INFO - SXlY6FY - plugins_service - loaded module [reindex]
INFO - SXlY6FY - plugins_service - loaded module [repository-url]
INFO - SXlY6FY - plugins_service - loaded module [transport-netty4]
INFO - SXlY6FY - plugins_service - loaded module [tribe]
INFO - SXlY6FY - plugins_service - loaded module [x-pack-core]
INFO - SXlY6FY - plugins_service - loaded module [x-pack-deprecation]
INFO - SXlY6FY - plugins_service - loaded module [x-pack-graph]
INFO - SXlY6FY - plugins_service - loaded module [x-pack-logstash]
INFO - SXlY6FY - plugins_service - loaded module [x-pack-ml]
INFO - SXlY6FY - plugins_service - loaded module [x-pack-monitoring]
INFO - SXlY6FY - plugins_service - loaded module [x-pack-rollup]
INFO - SXlY6FY - plugins_service - loaded module [x-pack-security]
INFO - SXlY6FY - plugins_service - loaded module [x-pack-sql]
INFO - SXlY6FY - plugins_service - loaded module [x-pack-upgrade]
INFO - SXlY6FY - plugins_service - loaded module [x-pack-watcher]
INFO - SXlY6FY - plugins_service - no plugins loaded
INFO - SXlY6FY - file_roles_store - parsed [0] roles from file [/tmp/libesvm-11846-3603-xc2qhc.gd6jmgf1or/roles.yml]
INFO - controller/3782 - cpp_log_message_handler - [Main.cc@109] controller (64 bit): Version 6.4.0-SNAPSHOT (Build d8ffb966ad9625) Copyright (c) 2018 Elasticsearch BV
INFO - SXlY6FY - discovery_module - using discovery type [zen]
INFO - SXlY6FY - node - initialized
INFO - SXlY6FY - node - starting ...
INFO - SXlY6FY - transport_service - publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
INFO - SXlY6FY - master_service - zen-disco-elected-as-master ([0] nodes joined)[, ], reason: new_master {SXlY6FY}{SXlY6FYCSfWh5pQzBRnCGw}{BK_0I6-mQX2Hsg8MEMkCYw}{127.0.0.1}{127.0.0.1:9300}{ml.machine_memory=3972685824, ml.max_open_jobs=20, ml.enabled=true}
INFO - SXlY6FY - cluster_applier_service - new_master {SXlY6FY}{SXlY6FYCSfWh5pQzBRnCGw}{BK_0I6-mQX2Hsg8MEMkCYw}{127.0.0.1}{127.0.0.1:9300}{ml.machine_memory=3972685824, ml.max_open_jobs=20, ml.enabled=true}, reason: apply cluster state (from master [master {SXlY6FY}{SXlY6FYCSfWh5pQzBRnCGw}{BK_0I6-mQX2Hsg8MEMkCYw}{127.0.0.1}{127.0.0.1:9300}{ml.machine_memory=3972685824, ml.max_open_jobs=20, ml.enabled=true} committed version [1] source [zen-disco-elected-as-master ([0] nodes joined)[, ]]])
INFO - SXlY6FY - security_netty_4_http_server_transport - publish_address {127.0.0.1:9200}, bound_addresses {127.0.0.1:9200}
INFO - SXlY6FY - node - started
Fatal error: Client request error: connect ECONNREFUSED 127.0.0.1:80
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[elasticsearch@dev01 kibana]$
[elasticsearch@dev01 kibana]$ ps -ef | grep elastic
root      3283  2171  0 14:31 pts/0    00:00:00 su - elasticsearch
elastic+  3284  3283  0 14:31 pts/0    00:00:00 -bash
elastic+  3825  3284  0 14:51 pts/0    00:00:00 ps -ef
elastic+  3826  3284  0 14:51 pts/0    00:00:00 grep --color=auto elastic
[elasticsearch@dev01 kibana]$

**Comment by aaronoah** [comment]
There are many active changes on Kibana team, as my experience, when you upgrade your codebase against the master branch and use `yarn es snapshot` will sort it out.
