### ISSUE TITLE
Fuzziness parameter disables cutoff_frequency in multi_match query 

### ISSUE THREAD

**Issue by benjaminPurdy** [elastic/elasticsearch#30222]
**Elasticsearch version**: 6.2.3

**Plugins installed**: [ingest-attachment]

**JVM version**: 1.8.0_51

**OS version**: MacOS v10.13.4

**Description of the problem including expected versus actual behavior**:
When performing a multi_match query. If i provide both a **fuzziness** option AND a **cutoff_frequency** option, then the **cutoff_frequency** option isnt respected and doesnt get applied to the results.

**Steps to reproduce**:
To reproduce:
Setup
<pre><code>
{
   "settings":{
      "index":{
         "refresh_interval":"1s",
         "number_of_shards":"1",
         "number_of_replicas":"1"
      }
   },
   "mappings":{
      "generic":{
         "properties":{
            "summary":{
               "type":"text"
            }
         }
      }
   }
}
</pre></code>

Add some data in it:
<pre><code>
http://localhost:9200/test/generic/1
{
  "summary" :         "The firstthingintheindex"
}

http://localhost:9200/test/generic/2
{
  "summary" :         "The secondadditiontotheindex"
}

http://localhost:9200/test/generic/3
{
  "summary" :         "The VeryLongSummaryWhichShouldntBeFound"
}
</pre></code>

Search for something with both cutoff_frequency and fuzziness:
<pre><code>
{
   "query":{
            "multi_match":{
            	"cutoff_frequency": 0.001,
               "fuzziness": "AUTO",
               "query":"The randomsearchhere",
               "fields":[
                  "summary"
               ]
            }
   }
}
</pre></code>

Would expect no results found but returns results for all 3 pieces of data
**Response**
<pre><code>
{
    "took": 3,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 3,
        "max_score": 0.13353139,
        "hits": [
            {
                "_index": "test",
                "_type": "generic",
                "_id": "1",
                "_score": 0.13353139,
                "_source": {
                    "summary": "The firstthingintheindex"
                }
            },
            {
                "_index": "test",
                "_type": "generic",
                "_id": "2",
                "_score": 0.13353139,
                "_source": {
                    "summary": "The secondadditiontotheindex"
                }
            },
            {
                "_index": "test",
                "_type": "generic",
                "_id": "3",
                "_score": 0.13353139,
                "_source": {
                    "summary": "The VeryLongSummaryWhichShouldntBeFound"
                }
            }
        ]
    }
}
</pre></code>

**Comment by jimczi** [comment]
These two options should not be set together, depending on the rewrite mode of the Fuzzy query we might not be able to access the expanded terms and their associated frequencies.  We've also decided to deprecate/remove the [`cutoff_frequency`](https://github.com/elastic/elasticsearch/issues/37096) option so I am closing this issue. `cutoff_frequency` is not needed in Elasticsearch 7.0 where we have optimizations in place that know how to deal with very frequent terms.
