### ISSUE TITLE
Build failed: XContentBuilder not found

### ISSUE THREAD

**Issue by manikanta-kondeti** [elastic/elasticsearch#30235]
Hi,

I have the latest repo and updated grade as well. But getting this following error while rebuilding the project. Here is the error:
Error:(17, 9) java: cannot access org.elasticsearch.common.xcontent.XContentBuilder
class file for org.elasticsearch.common.xcontent.XContentBuilder not found

Please let me know if I am doing something wrong.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
