### ISSUE TITLE
Index phrase query as percolator

### ISSUE THREAD

**Issue by keremcankabadayi** [elastic/elasticsearch#30242]
Hi! I'm having some issues about `elasticsearch-percolate`.

```
$ elasticsearch --version
Version: 6.2.2, Build: 10b1edd/2018-02-16T19:01:30.685723Z, JVM: 1.8.0_151
```
I described my problem [here](https://stackoverflow.com/questions/50084789/index-phrase-query-as-percolator) and [here](https://discuss.elastic.co/t/index-phrase-query-as-percolator/129932).

I just have curiosity it can be done or not. Maybe it's feature request, i don't know.
Thanks in advance for your help!

**Comment by tvernum** [comment]
Please leave the discussion of your issue to the forums.
We can open a feature request at a later date once we get to the bottom of your issue.
