### ISSUE TITLE
[CI] x-pack vagrant opensuse tests failing: Cannot assign requested address

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#30326]
Build URL: https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+6.2+packaging-tests/5/console

Does not reproduce locally (neither on osx/linux).

This message repeats a lot in the logs

```
06:15:56 # /project/build/bats/utils/xpack.bash: connect: Cannot assign requested address
06:15:56 # /project/build/bats/utils/xpack.bash: line 117: /dev/tcp/localhost/9200: Cannot assign requested address
```

It looks to me as if nothing is listening on localhost (but maybe on ipv6 instead?), I could not find any specific configuration for that on start up.

I saw that in commit 4de793bdb066df682070b62b34675069399615b6 did already change the logging in newer branches to get more information about.

@andyb-elastic Did you get any more information in newer branches why this failed?

**Comment by andyb-elastic** [comment]
A little, the logs from other intermittent packaging test failures on opensuse (for example see https://github.com/elastic/elasticsearch/issues/30053#issuecomment-384137430) showed that the cluster was failing to start because of monitoring not initializing, which seemed to be caused by cluster state publishing timing out. I'll follow up with the distributed team

**Comment by andyb-elastic** [comment]
This is in a different test but it's a similar kind of failure so documenting here

[build-2654-opensuse.txt](https://github.com/elastic/elasticsearch/files/1975946/build-2654-opensuse.txt)

Similar connection refused symptom

```
not ok 113 [RPM] test elasticsearch
# (from function `run_elasticsearch_tests' in file /project/build/packaging/bats/utils/utils.bash, line 539,
# (from function `run_elasticsearch_tests' in file /project/build/packaging/bats/utils/utils.bash, line 539,
#  in test file /project/build/packaging/bats/tests/40_rpm_package.bats, line 100)
#  in test file /project/build/packaging/bats/tests/40_rpm_package.bats, line 100)
#   `run_elasticsearch_tests' failed
#   `run_elasticsearch_tests' failed
# Making sure elasticsearch is up...
# --2018-05-04 05:30:49--  http://localhost:9200/_cluster/health
# Resolving localhost (localhost)... 127.0.0.1, ::1
# Connecting to localhost (localhost)|127.0.0.1|:9200... failed: Connection refused.
# Connecting to localhost (localhost)|::1|:9200... failed: Cannot assign requested address.
# Retrying.
```

Another interesting response after it does connect at one point

```
# {
#   "error" : {
#     "root_cause" : [
#       {
#         "type" : "index_not_found_exception",
#         "reason" : "no such index",
#         "resource.type" : "index_expression",
#         "resource.id" : "library",
#         "index_uuid" : "_na_",
#         "index" : "library"
#       }
#     ],
#     "type" : "index_not_found_exception",
#     "reason" : "no such index",
#     "resource.type" : "index_expression",
#     "resource.id" : "library",
#     "index_uuid" : "_na_",
#     "index" : "library"
#   },
#   "status" : 404
# }
# {
#   "error" : {
#     "root_cause" : [
#       {
#         "type" : "unavailable_shards_exception",
#         "reason" : "[library][3] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[library][3]] containing [index {[library][book][2], source[{\n      \"title\": \"Book #2\",\n      \"pages\": 456\n    }]}] and a refresh]"
#       }
#     ],
#     "type" : "unavailable_shards_exception",
#     "reason" : "[library][3] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[library][3]] containing [index {[library][book][2], source[{\n      \"title\": \"Book #2\",\n      \"pages\": 456\n    }]}] and a refresh]"
#   },
#   "status" : 503
# }
```

**Comment by andyb-elastic** [comment]
This is an ongoing issue that only happens on opensuse and sles, it's caused by the cluster starting very slowly, the root cause for which we've been unable to determine.

There are a few issues open for this and I'm fairly certain they all share the same cause so I'm going to close them in favor of #30295 since there's more discussion there
