### ISSUE TITLE
Don't treat unknown prefixed routes as index names

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch#30330]
Today if you call a verb on a resource starting with the reserved `_` prefix it will fall through our routing 

```
GET http://127.0.0.1:9200/_nodess HTTP/1.1
Connection: Keep-Alive
Accept: application/json
Content-Length: 0
Host: 127.0.0.1:9200
```

will return:

```
HTTP/1.1 400 Bad Request
content-type: application/json; charset=UTF-8
content-length: 325

{"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [_nodess], must not start with '_'.","index_uuid":"_na_","index":"_nodess"}],"type":"invalid_index_name_exception","reason":"Invalid index name [_nodess], must not start with '_'.","index_uuid":"_na_","index":"_nodess"},"status":400}
```

As its caught by the Get Index API.

I'd like to propose a generic handler for all requests that use an unknown special underscored API so that 

```
GET /_nodesss
POST /_blah
```

all return a 404.

**Comment by rjernst** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
