### ISSUE TITLE
Some Javadoc links are broken?

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch#30353]
**Elasticsearch version** (`bin/elasticsearch --version`): N/A

**Plugins installed**: N/A

**JVM version** (`java -version`): N/A

**OS version** (`uname -a` if on a Unix-like system): N/A

**Description of the problem including expected versus actual behavior**:

It looks like some of the links on the hosted Javadocs site are broken?  For example in the Constructor Detail on [this page](https://artifacts.elastic.co/javadoc/org/elasticsearch/client/elasticsearch-rest-high-level-client/6.2.4/org/elasticsearch/client/RestHighLevelClient.html#RestHighLevelClient-org.elasticsearch.client.RestClientBuilder-), the link to [RestClientBuilder](https://artifacts.elastic.co/javadoc/org/elasticsearch/elasticsearch/6.2.4/org/elasticsearch/client/RestClientBuilder.html?is-external=true) results in:

![image](https://user-images.githubusercontent.com/7401/39555259-44cb2a90-4ebb-11e8-844d-05a445d788c5.png)

Is there any link checking done for the Javadocs?

**Comment by DaveCTurner** [comment]
This does indeed seem to be the case. It looks like the docs for the classes in the [`org.elasticsearch.client`](https://artifacts.elastic.co/javadoc/org/elasticsearch/client/elasticsearch-rest-high-level-client/6.2.4/org/elasticsearch/client/package-summary.html) package provided by the `rest-high-level` module are there, but not those provided by `rest`.

**Comment by DaveCTurner** [comment]
It seems that `./gradlew javadoc` does not build docs on the 6.2 branch, but does work on 6.1, 6.3, 6.x and master. It was fixed in 6.3-and-later by #29173 - should this be backported to 6.2 perhaps?

**Comment by javanna** [comment]
thanks for digging @DaveCTurner ! I think it's quite important to fix this on 6.2 given that it's our current release and the javadocs links are currently broken. Hopefully backporting the change is possible.

**Comment by jrodewig** [comment]
[docs issue triage]
Leaving open as this is still relevant.

**Comment by jrodewig** [comment]
Closing this issue. This link is currently fixed in our 7.13 docs (which is the current build as time of writing):
https://artifacts.elastic.co/javadoc/org/elasticsearch/client/elasticsearch-rest-high-level-client/7.13.0/org/elasticsearch/client/RestHighLevelClient.html
