### ISSUE TITLE
gradlew :server:test does not work with debug-jvm option

### ISSUE THREAD

**Issue by nyurik** [elastic/elasticsearch#30369]
Using [./gradlew run --debug-jvm](https://github.com/elastic/elasticsearch/blob/master/TESTING.asciidoc#launching-and-debugging-from-an-ide), I can run ES and attach the debugger to it.  Yet if I use `./gradlew :server:test -D.... -D...` command with the `--debug-jvm`, it fails as unrecognized parameter.  What is the proper way to debug unit test execution?

**Comment by rjernst** [comment]
`--debug-jvm` is only meant for attaching to a running instance of elasticsearch. To debug unit/integ tests, I recommend running from within an IDE.

Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports.
