### ISSUE TITLE
Feature request: set timeout for update_mapping + define the cluster_task priority in the REST API

### ISSUE THREAD

**Issue by redlus** [elastic/elasticsearch#30370]
Hi

We're experiencing #30244 on our 6.2.3 cluster on an almost daily basis, which has some severe consequences on cluster maintenance, indices disk size and rollover to warm / cold nodes. We've noticed that the chance of timing out an update_mapping operation greatly increases when during some of our maintenance operations on a cluster (e.g. opening new indices and deleting old ones).

Briefly, when opening a new index, tasks for initializing its primary shards are immediately pushed to the head of the cluster_tasks queue with priority 'urgent'. Meanwhile, live indexed data which requires an update_mapping operation is pushed to the middle of the queue with priority 'high'. As the initialization of the new primary shards can take some time, update_mapping tasks can stack up in the queue - eventually reaching the 30 seconds timeout. Even when not reaching 30 seconds, the fact that the update_mapping task is blocking causes our indexing operations to greatly slow down, creating some backlogs. Below you can see the high correlation between creating indices and update_mapping timeouts:
![image](https://user-images.githubusercontent.com/7827282/39597917-999d0f34-4f1f-11e8-89f8-e0f28625a208.png)

Eventually, we'd propose the following:
1. As the create index operations are specifically spread out through the day during low-activity of the system and not to immediately index to them, we'd like to prevent these operations from interfering with live indexing data by setting their priority to low.

2. We'd like to be able to set a higher value than 30 seconds for update_mapping operations to reduce the chance of them timing out.

Thanks!

**Comment by DaveCTurner** [comment]
First up, #30244 is merged into 6.3, and we are expecting 6.3.0 to be the next release, so making the changes described here will not relieve the issues you are experiencing any sooner.

30 seconds is a very long time to spend on any kinds of change to the cluster state, mapping updates and index creation included, and the fact that you are seeing these things time out regularly indicates some kind of problem in the way your cluster is configured. Please open a discussion about this over on https://discuss.elastic.co/ and give some more details of your cluster setup (e.g. number of nodes, number & size of indices, numbers of shards & replicas, approximate load).

I've raised this issue for discussion with the wider team to gather input on your proposal.

**Comment by bleskes** [comment]
> We'd like to be able to set a higher value than 30 seconds for update_mapping operations to reduce the chance of them timing out.

As a temporary measure you can increase the timeout by setting `indices.mapping.dynamic_timeout` to something higher.  @DaveCTurner's advice is still sound - it's not healthy for the master to be unavailable to process requests. I suggest you follow up on the offer to figure things out there.

> As the create index operations are specifically spread out through the day during low-activity of the system and not to immediately index to them,

Understood. Other use cases may see it differently. Without an active primary, indexing can not continue. In many use cases this is seen as more important. If replicas are not starting, you do not meet your HA requirements. That again is sensitive to other users. All in all, determining these priorities is a very tricky thing. I suggest investing time in making sure the master keeps up to speed. That will cover this and many other issues. I'm going to close this now, we can reopen if the discussion on the forums brings up something that needs changing.

**Comment by bleskes** [comment]
@redlus I agree it's good to evaluate these priorities and as David already indicated we will discuss this internally. I'm more than willing to discuss the examples you gave but let's do on another thread on discuss.elastic.co . If we end up want to change something we can come back here.

> I'll open a thread in the discuss forums to see if we can get to the bottom of this.

All of that put aside, your use case feels abusive as you should not be seeing so many messages. I'm looking forward to hear about your setup on that discuss thread you were going to open.

**Comment by redlus** [comment]
Hi @DaveCTurner and @bleskes,
I've opened a discussion with more information on our cluster in the link below:
https://discuss.elastic.co/t/creating-indices-and-update-mapping-tasks-take-way-too-long/130718

Thanks!
