### ISSUE TITLE
Debug log logs password in base64

### ISSUE THREAD

**Issue by karthikr77** [elastic/elasticsearch#30373]
Enabling Debug log in elastic logs password (Ex. Watch http input password)  in the log file in base64. When the log file is shared for support or for any analysis, it is easy to decode the base64 encoded data to appropriate value. It could be good option to log password value using the encryption_key from keystore as encryption_key is managed.

**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.*

**Plugins installed**: [Xpack]

**JVM version** (`java -version`): 1.8.x

**OS version** (`uname -a` if on a Unix-like system):Linux RH

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**: Enable debug log, Have encrypted password in http input, execute the watch and observe the log to see base64 encoded version is logged.

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by spinscale** [comment]
I assume you mean, the base64 `Authorization` header is logged?

Just to be sure we are talking about the same log message. You are talking about something like

```
[2018-05-04T10:16:23,466][DEBUG][o.a.h.wire               ] http-outgoing-0 >> "Authorization: Basic Zm9vOmJhcg==[\r][\n]"
```

**Comment by spinscale** [comment]
so, after a quick look, the `LoggingOutputStream` of the apache http client simply writes out anything that also gets written on the wire - nothing we can do on top of my head here, I'll keep taking a look if there is anything we can do

**Comment by karthikr77** [comment]
Thanks Alex for responding.

Assuming the client using ssl - the wire has additional encryption over it.
viz. Client ================= Server
     Raw - base64 - ssl =====> ssl offload - base64 decode - Authenticate
How does Server know that it has to do base64  decode?

Regardless, I assume you got the note here that a decode on logged text would lead to password leak.

**Comment by javanna** [comment]
ping @elastic/es-core-infra is there anything we can do here?

**Comment by pgomulka** [comment]
@karthikr77 @spinscale do you think this is still a valid issue?
we have https://www.elastic.co/guide/en/elasticsearch/reference/master/encrypting-data.html

**Comment by spinscale** [comment]
The password will still be written out in base64 as it is part of the HTTP request being - independent from how it's stored. Not a lot we can do about that, as there were no hooks back then to dig into that logging logic of the apache http client, when I looked two years ago.

**Comment by stu-elastic** [comment]
We discussed this in the team meeting.  Debug logging will log the HTTP request, including authorization headers.  While the concern is understandable, such logs should be filtered before being shared.
