### ISSUE TITLE
[BUG]  @timestamp confused by accident in Table and JSON

### ISSUE THREAD

**Issue by regardfs** [elastic/elasticsearch#30380]
**Elasticsearch version** (`bin/elasticsearch --version`):

Use ```docker.elastic.co/elasticsearch/elasticsearch:5.5.2```

**Plugins installed**: [logtrail]

**Description of the problem including expected versus actual behavior**:
sometimes, the "@timestamp" is different in `JSON` and `TABLE`, it happened by accident, I could not figure out why....
in `JSON`:
![image](https://user-images.githubusercontent.com/8295227/39619244-b918c52a-4fb9-11e8-9113-54717e5bbb30.png)
in `TABLE`
![image](https://user-images.githubusercontent.com/8295227/39619260-c82bce54-4fb9-11e8-9950-5baaa5dd43da.png)

**Comment by regardfs** [comment]
The datatime is retrived from my log, the config in logstash pipeline is:
```
filter {
    grok {
        match => {
            "message" => "(?<datetime>(\d{4}-\d{2}-\d{2})*\s*\d{2}:\d{2}:\d{2}.\d{3})\s*%{WORD:loglevel}\s*\[%{WORD:appname},(?<traceid>[a-z0-9\s]*),(?<spanid>[a-z0-9\s]*),(?<flag>[a-z0-9\s]*)\]\s*.*"
        }
    }

    ruby {
      code => " 
      if event.get('message') =~ /#!(\w+)#!/
         event.set( 'orderid', $1)
      end 
      "
    } 


}
```

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
