### ISSUE TITLE
[Watcher] Add support for the PNG report generated image_urls in the Slack action

### ISSUE THREAD

**Issue by alexfrancoeur** [elastic/elasticsearch#30387]
PNG export is currently targeted for reporting in 6.x. One of the major benefits I see for this use case is to add dashboard's or visualizations images to a Slack message. It'd be great if Watcher could support asynchronously generated images from our reporting architecture in the same fashion it supports report URL's with emails. We'd need to add the image generated from the report to the `image_url` and `thumb_url` properties of a [Slack attachment](https://api.slack.com/docs/message-attachments).

<img width="721" alt="screen shot 2018-05-04 at 7 55 09 am" src="https://user-images.githubusercontent.com/25181823/39627246-2e399952-4f73-11e8-9d3b-e8a5fc994985.png">

Export to PNG: https://github.com/elastic/kibana/issues/18130

cc: @Stacey-Gammon @skearns64 @yaronp68 @eskibars @makwarth

**Comment by spinscale** [comment]
Interesting use-case. The `reporting` attachment is a special type of an attachment, which allows us to trigger the creation and then keeps polling kibana until the creation is done (which means it is potentially a long running watch). The above two slack attachment parameters are just links that point to kibana - which means another component first has to keep polling until those images are ready and only then is ready to send the slack message, which does not contain an attachment but just a link.

I am not yet sure how this can be supported in the current architecture, as we need something outside of the slack action that needs to trigger the image generation, but it should only be triggered if the condition is met to prevent useless image generations I suppose - a model, that is no other action is doing currently. Also I suppose we do not want to directly integrate this into the slack action, as it might be useful for pagerduty or hipchat as well.

Maybe a reporting action, that enriches the watch execution context environment with the URL that had been created? This action would do the same that the reporting attachment is doing, by triggering the creation and polling until the final resource has been created. Then the other actions would be able use the created URL in their respective fields such as the `thumb_url` and `image_url`.

**Comment by kapildawar** [comment]
+1

**Comment by tomjnaim** [comment]
Would like to see this implemented. I have several dashboards and would like to see a daily slack message with a snapshot of the dashboard.

**Comment by JakeHardy-sky** [comment]
+1, The ability to include a PNG or a PDF from a dashboard in the message posted to Slack would be super helpful!

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
