### ISSUE TITLE
Add an option to split on whitespace at query time on keyword fields

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#30393]
Follow-up of #30131. We should add a way to configure keyword fields so that text would be split on whitespace at query time. In FixitFriday it was suggested that we do this by adding something like a `split_queries_on_whitespace` flag that sets a whitespace analyzer as a search analyzer when set to true. We also considered making it possible to configure a search analyzer, but it felt too flexible for this simple need.

**Comment by akotlar** [comment]
This relates to #23336 as well, and would serve as a perfectly good substitute for my use case
