### ISSUE TITLE
6.2.4 install failed with RPM, but 6.0.0 is ok

### ISSUE THREAD

**Issue by showmeall** [elastic/elasticsearch#30406]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.4

**Plugins installed**: []

**JVM version** (`java -version`):
1.8.0
**OS version** (`uname -a` if on a Unix-like system):
Centos 7.2
**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

[root@localhost ~]# rpm -ivh elasticsearch-6.2.4.rpm 
warning: elasticsearch-6.2.4.rpm: Header V4 RSA/SHA512 Signature, key ID d88e42b4: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:elasticsearch-0:6.2.4-1          ################################# [100%]
error: unpacking of archive failed on file /usr/share/elasticsearch/NOTICE.txt;5aed18b5: cpio: read failed - No such file or directory
error: elasticsearch-0:6.2.4-1.noarch: install failed

**Comment by jasontedor** [comment]
I think you have a broken download. Check:

```
centos-7:~$ md5sum elasticsearch-6.2.4.rpm 
757f812fa11d7a5af54322b646fc4e0a  elasticsearch-6.2.4.rpm
```

I am closing this as unlikely to be a bug. Please use the [forum](https://discuss.elastic.co).

**Comment by oxwangfeng** [comment]
yes,it check sum error
