### ISSUE TITLE
jar hell in test classpath when running with JDK 1.8.0_171 on OS: WIN 10 

### ISSUE THREAD

**Issue by bLindStalker** [elastic/elasticsearch#30415]
When I try to run test with elastic version 6.2.4 I got exception: found jar hell in test classpath
my code: https://github.com/bLindStalker/test-elastic/

Full exception:

java.lang.RuntimeException: found jar hell in test classpath
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:92)
	at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:190)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:592)

Caused by: java.lang.IllegalStateException: jar hell!
duplicate jar [C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.2\lib\idea_rt.jar] on classpath: C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.2\lib\idea_rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.2\plugins\junit\lib\junit-rt.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.2\plugins\junit\lib\junit5-rt.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_171\jre\lib\rt.jar;C:\playtika\stash\testelastic\target\test-classes;C:\playtika\stash\testelastic\target\classes;C:\Users\ayakimenko\.m2\repository\org\elasticsearch\test\framework\6.2.4\framework-6.2.4.jar;C:\Users\ayakimenko\.m2\repository\org\elasticsearch\client\elasticsearch-rest-client\6.2.4\elasticsearch-rest-client-6.2.4.jar;C:\Users\ayakimenko\.m2\repository\org\apache\httpcomponents\httpasyncclient\4.1.2\httpasyncclient-4.1.2.jar;C:\Users\ayakimenko\.m2\repository\org\apache\httpcomponents\httpcore-nio\4.4.5\httpcore-nio-4.4.5.jar;C:\Users\ayakimenko\.m2\repository\org\elasticsearch\elasticsearch\6.2.4\elasticsearch-6.2.4.jar;C:\Users\ayakimenko\.m2\repository\org\elasticsearch\elasticsearch-core\6.2.4\elasticsearch-core-6.2.4.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-core\7.2.1\lucene-core-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-analyzers-common\7.2.1\lucene-analyzers-common-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-backward-codecs\7.2.1\lucene-backward-codecs-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-grouping\7.2.1\lucene-grouping-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-highlighter\7.2.1\lucene-highlighter-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-join\7.2.1\lucene-join-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-memory\7.2.1\lucene-memory-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-misc\7.2.1\lucene-misc-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-queries\7.2.1\lucene-queries-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-queryparser\7.2.1\lucene-queryparser-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-sandbox\7.2.1\lucene-sandbox-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-spatial\7.2.1\lucene-spatial-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-spatial-extras\7.2.1\lucene-spatial-extras-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-spatial3d\7.2.1\lucene-spatial3d-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-suggest\7.2.1\lucene-suggest-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\elasticsearch\securesm\1.2\securesm-1.2.jar;C:\Users\ayakimenko\.m2\repository\com\carrotsearch\hppc\0.7.1\hppc-0.7.1.jar;C:\Users\ayakimenko\.m2\repository\joda-time\joda-time\2.9.9\joda-time-2.9.9.jar;C:\Users\ayakimenko\.m2\repository\org\yaml\snakeyaml\1.17\snakeyaml-1.17.jar;C:\Users\ayakimenko\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.8.10\jackson-core-2.8.10.jar;C:\Users\ayakimenko\.m2\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-smile\2.8.10\jackson-dataformat-smile-2.8.10.jar;C:\Users\ayakimenko\.m2\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-yaml\2.8.10\jackson-dataformat-yaml-2.8.10.jar;C:\Users\ayakimenko\.m2\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-cbor\2.8.10\jackson-dataformat-cbor-2.8.10.jar;C:\Users\ayakimenko\.m2\repository\com\tdunning\t-digest\3.0\t-digest-3.0.jar;C:\Users\ayakimenko\.m2\repository\org\hdrhistogram\HdrHistogram\2.1.9\HdrHistogram-2.1.9.jar;C:\Users\ayakimenko\.m2\repository\org\apache\logging\log4j\log4j-api\2.9.1\log4j-api-2.9.1.jar;C:\Users\ayakimenko\.m2\repository\org\elasticsearch\jna\4.5.1\jna-4.5.1.jar;C:\Users\ayakimenko\.m2\repository\org\elasticsearch\elasticsearch-cli\6.2.4\elasticsearch-cli-6.2.4.jar;C:\Users\ayakimenko\.m2\repository\net\sf\jopt-simple\jopt-simple\5.0.2\jopt-simple-5.0.2.jar;C:\Users\ayakimenko\.m2\repository\com\carrotsearch\randomizedtesting\randomizedtesting-runner\2.5.2\randomizedtesting-runner-2.5.2.jar;C:\Users\ayakimenko\.m2\repository\junit\junit\4.12\junit-4.12.jar;C:\Users\ayakimenko\.m2\repository\org\hamcrest\hamcrest-all\1.3\hamcrest-all-1.3.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-test-framework\7.2.1\lucene-test-framework-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\lucene\lucene-codecs\7.2.1\lucene-codecs-7.2.1.jar;C:\Users\ayakimenko\.m2\repository\org\apache\httpcomponents\httpclient\4.5.2\httpclient-4.5.2.jar;C:\Users\ayakimenko\.m2\repository\org\apache\httpcomponents\httpcore\4.4.5\httpcore-4.4.5.jar;C:\Users\ayakimenko\.m2\repository\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\ayakimenko\.m2\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\ayakimenko\.m2\repository\org\elasticsearch\securemock\1.2\securemock-1.2.jar;C:\Users\ayakimenko\.m2\repository\org\elasticsearch\mocksocket\1.2\mocksocket-1.2.jar;C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.2\lib\idea_rt.jar
	at org.elasticsearch.bootstrap.JarHell.parseClassPath(JarHell.java:142)
	at org.elasticsearch.bootstrap.JarHell.parseClassPath(JarHell.java:98)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:89)
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:90)
	... 4 more

**Comment by dadoonet** [comment]
Have a look at https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#configuring-ides-and-running-tests

Please ask questions on discuss.elastic.co
