### ISSUE TITLE
Multi-fields with multiple analyzers doesn't work

### ISSUE THREAD

**Issue by mixalistzikas** [elastic/elasticsearch#30417]
**Describe the feature**:

**Elasticsearch version** (5.4.2):

**Plugins installed**: ['elasticsearch-skroutz-greekstemmer', 'elasticsearch-analysis-greeklish']

**JVM version** (openjdk version "1.8.0_131"):

**OS version** (16.04.1-Ubuntu):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

I have the following mapping

    `{
    "settings":{
    "analysis":{
    "analyzer":{
        "greeklish_analyzer":{
            "type":"custom",
            "tokenizer":"standard",
            "filter": ["lower_greek","greeklish_analysis"]
        },
        "stem_analyzer":{
            "type":"custom",
            "tokenizer":"standard",
            "filter": ["lower_greek","stem_greek"]
        }
    },
    "filter": {
        "lower_greek": {
            "type":"lowercase",
            "language":"greek"
        },
        "stem_greek": {
            "type":"skroutz_stem_greek"
        },
        "greeklish_analysis":{
            "type": "skroutz_greeklish",
            "max_expansions": 15
        }
    }
    }
    },
    "mappings": {
    "shooters": {
    "properties": {
        "activated": {
            "type": "boolean"
        },
        "name": {
            "type": "string",
            "analyzer": "stem_analyzer",
            "fields": {
                "english": {
                    "type": "string",
                    "analyzer": "english"
                },
                "greeklish": {
                    "type": "string",
                    "analyzer": "greeklish_analyzer"
                }
            }
        }
    }
    }
    }
    }`

Now... if I search 

    `{
    "query": {
        "multi_match":{
			"query": "Μιχάλης",
			"fields": ["name.greeklish"]
		}
    }
    }`

Nothing returns

if Instead i change the mapping of the name to

    ` "name": {
            "type": "string",
            "analyzer": "greeklish_analyzer"
        }`

and search with

     `{
    "query": {
        "multi_match":{
			"query": "Μιχάλης",
			"fields": ["name"]
		}
    }
    }`

It works...

Something happens with the nested fields of the main field. If I use them, then nothing happens....

Any idea?

Everything works perfect with elasticsearch 2.4.4

**Provide logs (if relevant)**:

**Comment by javanna** [comment]
hi @mixalistzikas , could you please post an example of a document that you indexed and which you would expect to get back with your query? It would be helpful to have a full recreation of the problem with curl statements if possible. Thanks!

**Comment by mixalistzikas** [comment]
Document 1

`{
    "name": "Michalis",
}`

Document 2

`{
    "name": "Μιχάλης",
}`

Document 3

`{
    "name": "Γιώργος",
}`

Document 4

`{
    "name": "Giorgos",
}`

With the "greeklish_analyzer" it is possible even if I search for "Μιχάλης", also find document 1 "Michalis"

So If I search "Μιχάλης" I have to find Document 1 & 2

If I use the analyzer without the "fields" it works perfect. But if I use "fields" to my mapping, seems to ignore my fields. It returns nothing

**Comment by javanna** [comment]
hi @mixalistzikas  thanks for getting back to me so quickly. I tried to reproduce this but everything look good to me. I have tried the following against 5.4.2:

- create the index:

```
curl -XPUT localhost:9200/shooters -H 'Content-Type: application/json' -d '{
"settings":{
"analysis":{
"analyzer":{
    "greeklish_analyzer":{
        "type":"custom",
        "tokenizer":"standard",
        "filter": ["lower_greek","greeklish_analysis"]
    },
    "stem_analyzer":{
        "type":"custom",
        "tokenizer":"standard",
        "filter": ["lower_greek","stem_greek"]
    }
},
"filter": {
    "lower_greek": {
        "type":"lowercase",
        "language":"greek"
    },
    "stem_greek": {
        "type":"skroutz_stem_greek"
    },
    "greeklish_analysis":{
        "type": "skroutz_greeklish",
        "max_expansions": 15
    }
}
}
},
"mappings": {
"shooters": {
"properties": {
    "activated": {
        "type": "boolean"
    },
    "name": {
        "type": "string",
        "analyzer": "stem_analyzer",
        "fields": {
            "english": {
                "type": "string",
                "analyzer": "english"
            },
            "greeklish": {
                "type": "string",
                "analyzer": "greeklish_analyzer"
            }
        }
    }
}
}
}
}'
```

- index some documents

```
curl -XPUT localhost:9200/shooters/shooters/1 -H 'Content-Type: application/json' -d '{
"name": "Michalis"
}
'

curl -XPUT localhost:9200/shooters/shooters/2 -H 'Content-Type: application/json' -d '{
"name": "Μιχάλης"
}
'

curl -XPUT localhost:9200/shooters/shooters/3 -H 'Content-Type: application/json' -d '{
"name": "Γιώργος"
}
'

curl -XPUT localhost:9200/shooters/shooters/4 -H 'Content-Type: application/json' -d '{
"name": "Giorgos"
}
'
```

- execute the search against `name.greeklish`

```
curl localhost:9200/shooters/_search -H 'Content-Type: application/json' -d '{
"query": {
    "multi_match":{
        "query": "Μιχάλης",
        "fields": ["name.greeklish"]
    }
}
}
'
```

- 2 documents are returned, as expected

```
{"took":10,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":2,"max_score":1.5093232,"hits":[{"_index":"shooters","_type":"shooters","_id":"2","_score":1.5093232,"_source":{
"name": "Μιχάλης"
}
},{"_index":"shooters","_type":"shooters","_id":"1","_score":0.2876821,"_source":{
"name": "Michalis"
}
```

I would recommend to double check that the index you are querying really has the mappings that you think it has. And that you reindex the documents after adding the multi_field. I'd expect my steps above to work for you as well, provided that you start from scratch.

**Comment by mixalistzikas** [comment]
I execute your curls..... and.... Zero results.... Something strange happend here....

This is my Dockerfile

    FROM docker.elastic.co/elasticsearch/elasticsearch:5.4.2

    RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install gr.skroutz:elasticsearch-skroutz-greekstemmer:5.4.2.1
    RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install gr.skroutz:elasticsearch-analysis-greeklish:5.4.2.1

    EXPOSE 9200 9300

**Comment by mixalistzikas** [comment]
Your example works....  Thank you!!! I will find my bug
