### ISSUE TITLE
Run ESBlobStoreContainerTestCase tests against real blob store implementations

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#30424]
ESBlobStoreContainerTestCase is an abstract class in test:framework that checks properties that all blob store implementation have to satisfy, for example that writing to a blob that already exists fails.

We currently run these tests only against mock implementations, not the actual services. Running against the actual services would validate that the blob store implementations are compliant to the BlobContainer interface.

**Comment by original-brownbear** [comment]
We could actually do this now quite nicely since we already have `org.elasticsearch.repositories.AbstractThirdPartyRepositoryTestCase`. 

In fact, we could simply add the tests from `ESBlobStoreContainerTestCase` to this class and have what is asked for here.
