### ISSUE TITLE
[CI] CoreFullClusterRestartIT NotMasterException

### ISSUE THREAD

**Issue by jdconrad** [elastic/elasticsearch#30443]
Was unable to reproduce locally.  Pulled the two node log files.

(https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+bwc-tests/39/console)

[full-cluster-restart-node0-part1.log](https://github.com/elastic/elasticsearch/files/1981732/full-cluster-restart-node0-part1.log)
[full-cluster-restart-node0-part2.log](https://github.com/elastic/elasticsearch/files/1981735/full-cluster-restart-node0-part2.log)
[full-cluster-restart-node1-part1.log](https://github.com/elastic/elasticsearch/files/1981738/full-cluster-restart-node1-part1.log)
[full-cluster-restart-node1-part2.log](https://github.com/elastic/elasticsearch/files/1981741/full-cluster-restart-node1-part2.log)

REPRODUCE WITH: ./gradlew :x-pack:qa:full-cluster-restart:with-system-key:v5.0.0#oldClusterTestRunner \
  -Dtests.seed=535F856688D6390 \
  -Dtests.class=org.elasticsearch.xpack.restart.CoreFullClusterRestartIT \
  -Dtests.method="testAliasWithBadName" \
  -Dtests.security.manager=true \
  -Dtests.locale=is \
  -Dtests.timezone=Asia/Ust-Nera

REPRODUCE WITH: ./gradlew :x-pack:qa:full-cluster-restart:with-system-key:v5.0.0#oldClusterTestRunner \
  -Dtests.seed=535F856688D6390 \
  -Dtests.class=org.elasticsearch.xpack.restart.CoreFullClusterRestartIT \
  -Dtests.method="testEmptyShard" \
  -Dtests.security.manager=true \
  -Dtests.locale=is \
  -Dtests.timezone=Asia/Ust-Nera

REPRODUCE WITH: ./gradlew :x-pack:qa:full-cluster-restart:with-system-key:v5.0.0#oldClusterTestRunner \
  -Dtests.seed=535F856688D6390 \
  -Dtests.class=org.elasticsearch.xpack.restart.CoreFullClusterRestartIT \
  -Dtests.method="testSearch" \
  -Dtests.security.manager=true \
  -Dtests.locale=is \
  -Dtests.timezone=Asia/Ust-Nera

REPRODUCE WITH: ./gradlew :x-pack:qa:full-cluster-restart:with-system-key:v5.0.0#oldClusterTestRunner \
  -Dtests.seed=535F856688D6390 \
  -Dtests.class=org.elasticsearch.xpack.restart.CoreFullClusterRestartIT \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=Etc/UTC

**Comment by bleskes** [comment]
@DaveCTurner , @ywelsch can one of you maybe look at this?

**Comment by jasontedor** [comment]
@ywelsch This only needs a backport of #30337. I will do this now.

**Comment by jasontedor** [comment]
Closed by fed949e0b8566760b65a09ffd17b63240fba2723
