### ISSUE TITLE
Rendered search templates are allowed to be incorrectly formatted.

### ISSUE THREAD

**Issue by jtibshirani** [elastic/elasticsearch#30448]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.0

**Description of the problem including expected versus actual behavior**:
When issuing a request to render a search template, it doesn't seem as though inline scripts are verified to be well-formatted. When provided with a malformed script, the render template endpoint returns a successful response containing the invalid script.

It seems undesirable to return a badly formatted response, and this lack of constraints makes it difficult for clients to reliably parse the response.

**Steps to reproduce**:
As an example, the following template is not well-formatted, as the term 'aaa' has been inserted before a map:

```
GET _render/template
{
  "source": "{ \"query\": aaa { \"query_string\": { \"_all\": \"{{input}}\" }}}",
  "params": {
    "input": "hello, world"
  }
}

{"template_output":{ "query": aaa { "query_string": { "_all" : "hello, world" }}}}
```

There are no restrictions on the format of `template_output`, so it is also possible to modify the structure of the response. For example, you could close an extra parenthesis so that a new top-level key is inserted in the response:
```
GET _render/template
{
  "source": "{ \"query\": { \"query_string\": { \"_all\": \"{{input}}\" }}}, \"top_level_key\": \"goodbye\"",
  "params": {
    "input": "hello, world"
  }
}

{
  "template_output": {
    "query": {
      "query_string": {
        "_all": "hello, world"
      }
    }
  },
  "top_level_key": "goodbye"
}
```

**Comment by ZenitK** [comment]
Mustache itself doesn't care much what it "spits" out, so there would have to be separate JSON validation that is polite enough to say at least where is the problem.

My team and I use a relatively complex Template with multiple Queries, Aggregations and mustache Loops and it's truly a pain to find out what's wrong.

**Comment by benwtrent** [comment]
Inline templates are validated. I verified that the above examples fail when rendering in the latest ES version.
