### ISSUE TITLE
Node filters are undocumented

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#30455]
The [introduction to the cluster APIs reference documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster.html) indicates that it's possible to filter the target nodes and gives some examples of how to do so, but there seems to be no comprehensive description of all the possibilities here. In particular, the special filters `{data,master,ingest}:{true,false}` are not documented. The code in question is:

https://github.com/elastic/elasticsearch/blob/27ddb4ffeacf04b3ce09524c839c8e5a39462c8c/server/src/main/java/org/elasticsearch/cluster/node/DiscoveryNodes.java#L303-L368

Noticed in the context of #30313 which changes this method but there's apparently no corresponding docs to change.

**Comment by debadair** [comment]
[doc-issue-triage]

Closed as fixed by #30468
