### ISSUE TITLE
How to use the Java API to build an Aggregation from JSON in 6.2.4 ?

### ISSUE THREAD

**Issue by luxiaoxun** [elastic/elasticsearch#30477]
In old version, we can do this:
```
SearchRequestBuilder builder = client.prepareSearch(index);
QueryBuilder queryBuilder = getQueryBuilder(query);
builder.setQuery(queryBuilder); // set query
builder.setAggregations(agg.toString().getBytes()); // set aggregation
```
But in 6.2.4, we only have these 2 APIs:
```
builder.addAggregation(AggregationBuilder aggregation) 
builder.addAggregation(PipelineAggregationBuilder aggregation)
```
How to make the "set aggregation" from JSON string work correctly?
Thanks.

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
