### ISSUE TITLE
Feature Request - Add support for onezone_ia storage class in repository_s3 plugin

### ISSUE THREAD

**Issue by jamesspi** [elastic/elasticsearch#30474]
Hi all,

Can support for the "onezone_ia" storage class be added to the repository_s3 plugin? 

Thanks!
James

**Comment by tlrx** [comment]
It has been added to AWS SDK 1.11.309, once we upgrade the dependency the storage class will be available.

**Comment by jamesspi** [comment]
Awesome, thanks @tlrx !

**Comment by tlrx** [comment]
Fixed in  #30723
