### ISSUE TITLE
Automatic merge of segments not happening

### ISSUE THREAD

**Issue by intrakislay** [elastic/elasticsearch#30472]
I use Elasticsearch 5.4 . We have a lot of adds/edits/deletes. The Elasticsearch should be able to keep merging the segments.
But we see that number of deleted documents keep on increasing and the segments are not getting merged. We need to do force merge.
Many a time i see , deleted doc count > 60% and even after weeks, it doesnot automatically recover from this unless we do force merge on that index
The threshold in our index is 10%, so whenever deleted document percentage  goes beyond this, segment merge should happen automatically, but this  is not happening

**Comment by danielmitterdorfer** [comment]
No further feedback received. @intrakislay if you have the requested 
information please add it in a comment and we can look at re-opening 
this issue.
