### ISSUE TITLE
[Doc] Issues with numeric callouts

### ISSUE THREAD

**Issue by mortenbock** [elastic/elasticsearch#30532]
https://www.elastic.co/guide/en/elasticsearch/reference/master/search-analyzer.html

https://github.com/elastic/elasticsearch/blob/master/docs/reference/mapping/params/search-analyzer.asciidoc

There is something strange going on with the numeric callouts from the code sample and the bullets under it. It looks like it's the rendering that cannot handle it correctly, since the source document looks fine?

**Comment by cbuescher** [comment]
The problem is caused by two superflous callouts in the prceding page: https://www.elastic.co/guide/en/elasticsearch/reference/master/properties.html. Have a PR that fixes it now.
