### ISSUE TITLE
[CI] SmokeTestMonitoringWithSecurityIT fails due to leaked thread

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#30547]
SmokeTestMonitoringWithSecurityIT failed due to leaked threads.

```
2> SEVERE: 1 thread leaked from SUITE scope at org.elasticsearch.smoketest.SmokeTestMonitoringWithSecurityIT: 
2>    1) Thread[id=18, name=threadDeathWatcher-2-1, state=TIMED_WAITING, group=TGRP-SmokeTestMonitoringWithSecurityIT]
2>         at java.lang.Thread.sleep(Native Method)
2>         at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:152)
2>         at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
2>         at java.lang.Thread.run(Thread.java:748)
```

- Instance: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1627/console

- Log: [testHTTPExporterWithSSL.txt](https://github.com/elastic/elasticsearch/files/1997121/testHTTPExporterWithSSL.txt)

**Comment by jasontedor** [comment]
This thread: `threadDeathWatcher-2-1` is a Netty thread. I think this should be recategorized as :Core/Networking issue.
