### ISSUE TITLE
Fold query-builder-bwc into full-cluster-restart

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#30546]
It looks to me like `qa/query-builder-bwc`'s tests could run along with `qa/full-cluster-restart`. Could we fold those two projects together to save booting all the clusters once?

**Comment by martijnvg** [comment]
@nik9000 👍Just moving `QueryBuilderBWCIT.java` to `qa/full-cluster-restart` module should just work.

**Comment by nik9000** [comment]
I did this in #30979.
