### ISSUE TITLE
Deep Aggregation Support

### ISSUE THREAD

**Issue by simionrobert** [elastic/elasticsearch#30555]
Hi.

I do have a question.

Does elasticsearch support deep aggregations? (nested aggregation in nested aggregation).  To make agg of a nested object inside a nested object. Specifically to count docs.
If so, please give me an example. 

Thank you very much.

**Comment by spinscale** [comment]
we try to use github for fixing bugs/talking about features only, so as Thomas said, please use our discussion forum (specifically the [Elasticsearch one](https://discuss.elastic.co/c/elasticsearch) for this kind of questions). Thank you!
