### ISSUE TITLE
elasticsearch on Centos 7 

### ISSUE THREAD

**Issue by waelc** [elastic/elasticsearch#30554]
Dears 

I installed elasticsearch  and put configuration  in the end file  vi /etc/elasticsearch/elasticsearch.yml
 
```
 script.disable_dynamic: true
network.host: localhost
discovery.zen.ping.multicast.enabled: false
```

after that , I try to start services but i get has  error 

> systemctl start elasticsearch

> Job for elasticsearch.service failed because a configured resource limit was exceeded. See "systemctl status elasticsearch.service" and "journalctl -xe" for details.

**systemctl status elasticsearch.service journalctl -l**

> ● elasticsearch.service - Starts and stops a single elasticsearch instance on this system
>    Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
>    Active: failed (Result: resources) since Sun 2018-05-13 13:55:40 +03; 1min 50s ago
>      Docs: http://www.elasticsearch.org
>   Process: 17682 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -d -p /var/run/elasticsearch/elasticsearch.pid -Des.default.config=$CONF_FILE -Des.default.path.home=$ES_HOME -Des.default.path.logs=$LOG_DIR -Des.default.path.data=$DATA_DIR -Des.default.path.work=$WORK_DIR -Des.default.path.conf=$CONF_DIR (code=exited, status=0/SUCCESS)
>   Process: 17679 ExecStartPre=/bin/chown -R elasticsearch:elasticsearch /var/run/elasticsearch/ (code=exited, status=0/SUCCESS)
>   Process: 17677 ExecStartPre=/bin/mkdir /var/run/elasticsearch (code=exited, status=1/FAILURE)
> 
> May 13 13:55:40 TVTC-clm2 systemd[1]: Starting Starts and stops a single elasticsearch instance on this system...
> May 13 13:55:40 TVTC-clm2 systemd[1]: Ignoring invalid environment assignment 'if [ "x$1"== "xstart" -o "x$1" == "xrestart" -o "x$1" == "xreload" -o "x$1" == "xforce-reload" ];then': /etc/sysconfig/elasticsearch
> May 13 13:55:40 TVTC-clm2 systemd[1]: Ignoring invalid environment assignment 'if [ "$GET_ES_CONFIG_RETURN" !=0]; then': /etc/sysconfig/elasticsearch
> May 13 13:55:40 TVTC-clm2 systemd[1]: Ignoring invalid environment assignment 'if [ "x$1"== "xstart" -o "x$1" == "xrestart" -o "x$1" == "xreload" -o "x$1" == "xforce-reload" ];then': /etc/sysconfig/elasticsearch
> May 13 13:55:40 TVTC-clm2 systemd[1]: Ignoring invalid environment assignment 'if [ "$GET_ES_CONFIG_RETURN" !=0]; then': /etc/sysconfig/elasticsearch
> May 13 13:55:40 TVTC-clm2 systemd[1]: PID file /var/run/elasticsearch/elasticsearch.pid not readable (yet?) after start.
> May 13 13:55:40 TVTC-clm2 systemd[1]: elasticsearch.service never wrote its PID file. Failing.
> May 13 13:55:40 TVTC-clm2 systemd[1]: Failed to start Starts and stops a single elasticsearch instance on this system.
> May 13 13:55:40 TVTC-clm2 systemd[1]: Unit elasticsearch.service entered failed state.
> May 13 13:55:40 TVTC-clm2 systemd[1]: elasticsearch.service failed.
> Unit journalctl.service could not be found.
> 
how i can solve this problem

**Comment by jasontedor** [comment]
There are crucial details missing from this such as what version of Elasticsearch this is, and how you installed Elasticsearch. Most importantly, direct information on how to reproduce would be helpful. That said, I see code here that I do not recognize:

```
May 13 13:55:40 TVTC-clm2 systemd[1]: Ignoring invalid environment assignment 'if [ "x$1"== "xstart" -o "x$1" == "xrestart" -o "x$1" == "xreload" -o "x$1" == "xforce-reload" ];then': /etc/sysconfig/elasticsearch
May 13 13:55:40 TVTC-clm2 systemd[1]: Ignoring invalid environment assignment 'if [ "$GET_ES_CONFIG_RETURN" !=0]; then': /etc/sysconfig/elasticsearch
May 13 13:55:40 TVTC-clm2 systemd[1]: Ignoring invalid environment assignment 'if [ "x$1"== "xstart" -o "x$1" == "xrestart" -o "x$1" == "xreload" -o "x$1" == "xforce-reload" ];then': /etc/sysconfig/elasticsearch
May 13 13:55:40 TVTC-clm2 systemd[1]: Ignoring invalid environment assignment 'if [ "$GET_ES_CONFIG_RETURN" !=0]; then': /etc/sysconfig/elasticsearch
```

This makes me believe this is a custom installation and we are unlikely to consider this a bug and support it. As we only handle verified bugs and feature requests on this repository, I am going to close this issue and suggest that you use the [forum](https://discuss.elastic.co).
