### ISSUE TITLE
[INFO ][o.e.m.j.JvmGcMonitorService] [node-1] [gc][5414000] overhead, spent [296ms] collecting in the last [1s] 

### ISSUE THREAD

**Issue by suchandbabu** [elastic/elasticsearch#30550]
Hi,

I am using Elsticsearch5.5.3 with 4 node cluster( one node is just a coordinating node).

One of my node is showing 100% cpu usage always, and also I can see this below log message from elasticsearch.

[INFO ][o.e.m.j.JvmGcMonitorService] [node-1] [gc][5414000] overhead, spent [296ms] collecting in the last [1s]

16gb is the max and min memory assigned for jvm now.

Can someone please help me to resolve this issue.

Cluster health status is also copying here for referance:
"status" : "green",
"timed_out" : false,
"number_of_nodes" : 4,
"number_of_data_nodes" : 3,
"active_primary_shards" : 856,
"active_shards" : 1712,
"relocating_shards" : 0,
"initializing_shards" : 0,
"unassigned_shards" : 0,
"delayed_unassigned_shards" : 0,
"number_of_pending_tasks" : 0,
"number_of_in_flight_fetch" : 0,
"task_max_waiting_in_queue_millis" : 0,
"active_shards_percent_as_number" : 100.0
}

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
