### ISSUE TITLE
Restart ES node , encounter exception 

### ISSUE THREAD

**Issue by tylercao** [elastic/elasticsearch#30566]
Hi 

Recently ,   I am trying to restart ES node . but during restarting ES node , server was encounter the below exception 

`ClusterBlockException[blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized]`

ES version :2.4.2 
ES node : 5 nodes ,  
Node setting : all nodes are  node.master: true. and node.data : true

**Comment by spinscale** [comment]
We try to use github for fixing bugs/talking about features only. Please use our discussion forum (specifically the [Elasticsearch one](https://discuss.elastic.co/c/elasticsearch) for this kind of questions). Thank you!

Also note, that the Elasticsearch version you are using is no longer maintained and does not even receive bug fixes anymore, so upgrading should be high on your priority list.
