### ISSUE TITLE
[CI] org.elasticsearch.xpack.security.transport.ServerTransportFilterIntegrationTests failure

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#30564]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian/2432/console

Failed to set up a cluster, due to a combination of BindException and locking:
```
Caused by: BindTransportException[Failed to bind to [30381]]; nested: BindException[Address already in use];
```
```
java.lang.IllegalStateException: failed to obtain node locks, tried [[/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-unix-compatibility/os/debian/x-pack/plugin/security/build/testrun/test/J2/temp/org.elasticsearch.xpack.security.transport.ServerTransportFilterIntegrationTests_220B0C98A8697261-001/tempDir-004/data/SUITE-CHILD_VM=[2]-CLUSTER_SEED=[-3630960381495774689]-HASH=[2942144BCED99]-cluster]] with lock ids [0--6]; maybe these locations are not writable or multiple nodes were started without increasing [node.max_local_storage_nodes] (was [7])?
```

**Comment by jkakavas** [comment]
This looks like an ephemeral port selected for transport was already bound by another process. The process with which the tcp port is picked for transport should not make this possible but this has never manifested again and we don't have any logs now so I will close this

The lock issue manifested also the same day (May 14) in https://github.com/elastic/elasticsearch/issues/30559 but I can't find this happening again after that.
