### ISSUE TITLE
Ability to add comments to a query

### ISSUE THREAD

**Issue by sabi0** [elastic/elasticsearch#30576]
Sometimes it is useful to be able to add some comments to a (large) query. Be it for describing a particular syntax in a query template or for documenting purposes in the query examples, like this:
![image](https://user-images.githubusercontent.com/11509875/40003466-b0e15b88-5793-11e8-89e0-8330fc4ba179.png)

Elasticsearch already does a great job of recognizing end-of-line comments in query JSON. But not every editor out there can handle them nicely.

A `"_name"` workaround is usable but not always convenient. At the very least it could blow the response size. And in the worst case I imagine it could hit some unique constraint if there happens to be two identical "commentary names" in a query.

So I would like to suggest implementing something similar to `"_name"` but specifically for commenting purposes. To start with it could even share the same applicability as the `"_name"` (i.e. top level of query / filter).

What do you think of using `"//"` property name for this purpose?

Here is how the modified example from the above screenshot would look like:
```
  "aggs": {
    "models": {
      "terms": { "field": "model", "//": "Returns the most popular models of red shirts by Gucci." } 
    }
  }
```

**Comment by imotov** [comment]
@sabi0 Sorry, I don't think elasticsearch is the right place to address this issue. As you said, the problem is in the tooling (editors) support and should be addressed on the client side. If you need support for comments in DSL in your application, you should probably add a layer in your application that would strip out all `"//"` fields **before** sending requests to elasticsearch. 

Essentially, the query language is a communication protocol between client and server and not a user interface. So, I am not even sure if the existing comments support is justified. We support these comments for historical reasons, but it's not part of the JSON standard.

**Comment by bobtiernay-okta** [comment]
Just want to add another use case that may not have been considered which is the Task API and slow query logs. If Elasticsearch had the capability to add a `_comment` attribute to the search, it would be possible to add app-level "request id" correlation identifier to be able to link together systems to identify the source of problematic queries:

```json
{
  "nodes": {
    "6eP18hh-STe-KmQ27rh3uw": {
       ...
      "tasks": {
        "6eP18hh-STe-KmQ27rh3uw:18421775": {
          "node": "6eP18hh-STe-KmQ27rh3uw",
          "id": 18421775,
          "type": "transport",
          "action": "indices:data/read/search",
          "description": "indices[my-index], types[], search_type[QUERY_THEN_FETCH], source[{\"from\":0,\"size\":0,\"query\": "...",
          "start_time_in_millis": 1580768231241,
          "running_time_in_nanos": 2479194013,
          "cancellable": true
        }
      }
    }
  }
}
```

Today, this isn't possible without resorting to hacks which may not generalize or which may change query semantics (e.g. https://stackoverflow.com/questions/42844111/is-it-possible-to-put-a-comment-in-an-elasticsearch-query). 

@imotov would love to get your thoughts.

**Comment by imotov** [comment]
@bobtiernay-okta do you mean something like [this](https://www.elastic.co/guide/en/elasticsearch/reference/master/tasks.html#_identifying_running_tasks)?

**Comment by bobtiernay-okta** [comment]
@imotov If that can be applied to `/_search` requests and then manifest in the slow query log and Task API responses then yes. Is that the case?

**Comment by imotov** [comment]
> Is that the case?

@bobtiernay-okta starting with 6.4.0 it is indeed the case. It can be applied to any request and if it is applied to search, it will show up in search slow logs. You can find details in the [search slow log docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules-slowlog.html#_identifying_search_slow_log_origin) logs.

I also would to mention that our [discussion forum](https://discuss.elastic.co/) might be a better place for questions like this.

**Comment by bobtiernay-okta** [comment]
That's fair. I honestly thought it was missing behavior as I see this was declined. Will look harder next time!
