### ISSUE TITLE
ObjectParser should throw XContentParseExceptions, not IAE

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#30605]
ParsingException is nicer since it includes the place where the parsing error occurred.

**Comment by nik9000** [comment]
`ParsingException` can't move because it extends `ElasticsearchException`. We made `XContentParseException` which doesn't extend `ElasticsearchException` to use directly from the xcontent stuff. I think the tests should catch either or something should wrap somewhere.

**Comment by dakrone** [comment]
I agree with @nik9000, this should use `XContentParseException` so that it can keep being decoupled from `ElasticsearchException`

**Comment by jpountz** [comment]
This sounds good to me. I updated the title and description of the issue.
