### ISSUE TITLE
Ingest processor to copy the value of a field

### ISSUE THREAD

**Issue by jamesdbaker** [elastic/elasticsearch#30604]
**Describe the feature**: Currently it is possible to rename an existing field using the [Rename processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/rename-processor.html) as part of an ingest pipeline, but it would also be useful to be able to copy a field (without modification). I'm therefore proposing the introduction of a Copy processor that does just that.

The use case for this is that I'm looking to use a pipeline to transform data from a 'raw' index to a normalized one, and we want to transform a raw field in different ways to produce multiple different normalized fields. In some cases, we may also want the same value copied into multiple fields without transformation (for example, our original document may only have a date field but in our normalized version we want a startDate and an endDate set to the same value).

As far as I can tell, this isn't easily possible at the moment but would be relatively easy to implement. I am happy to code up this feature, if there's no reason why it shouldn't be included and it's not already possible through some other route?

**Comment by cbuescher** [comment]
@jamesdbaker have you looked into whether a [script processor](https://www.elastic.co/guide/en/elasticsearch/reference/master/script-processor.html) might solve your problem? Just curious. Also it looks like @dadoonet used just this usecase for his blog about writing an ingest processor: http://david.pilato.fr/blog/2016/07/28/creating-an-ingest-plugin-for-elasticsearch/

**Comment by cbuescher** [comment]
@jamesdbaker I just tried using a simple script to copy the contents of one field to another and it seems to solve at least simple "copy" use cases:
```
PUT _ingest/pipeline/my_pipe
{
  "processors": [
    {
      "script": {
        "lang": "painless",
        "source": "if (ctx.field_a != null) ctx.field_b = ctx.field_a"
      }
    }
  ]
}
```

There are edge cases to consider, e.g. the above will simply overwrite an existing `field_b` in the input document if it exists. I'm also not sure about whether a dedicated ingest processor would be more performant, but at least it looks like a possible workaround.

**Comment by jamesdbaker** [comment]
Thanks, having a script version is a start (although a little more work). I'm trying to create an interface to allow users to configure their own pipelines (in my use case, users can upload their own raw data in any format, and then provide a mapping to normalise it into our standard format) - so having a dedicated Copy processor would make things a little easier from that point of view (and the pipelines cleaner).

**Comment by jamesdbaker** [comment]
Thanks @martijnvg , I wasn't aware that the Set processor could take other fields, I thought it was just for setting literal values.

**Comment by cbuescher** [comment]
@martijnvg same here. @jamesdbaker do you think this is sufficient enough to close this issue?

**Comment by jamesdbaker** [comment]
I've not tested, but yet this should do the job to resolve my issue. Perhaps worth updating the documentation though to reflect that this is an option? (I don't know whether that's a separate ticket or not?)

**Comment by cbuescher** [comment]
Good suggestion, I removed the discussion label and made this a documentation issue. I think it it worth adding an example like this to the set processor documentation.

**Comment by talevy** [comment]
Closing this with an docs example that was added in #39941 thanks to @ajoshbiol!

**Comment by MrTrick** [comment]
There is a problem with using the set command - some characters in the value will be escaped.
For example:
```
PUT _ingest/pipeline/test-pipeline
{
  "description": "Demonstrate set",
  "processors": [
    {
      "set": {
        "field": "dest",
        "value": "{{src}}"
      }
    }
  ]
}

POST _ingest/pipeline/test-pipeline/_simulate
{
  "docs": [
    {
      "_source": {
        "src": "I have \"quotation\" marks"
      }
    }
  ]
}
```
Gives output:
```
{
  "docs" : [
    {
      "doc" : {
        "_index" : "_index",
        "_type" : "_type",
        "_id" : "_id",
        "_source" : {
          "dest" : """I have \"quotation\" marks""",
          "src" : """I have "quotation" marks"""
        },
        "_ingest" : {
          "timestamp" : "2021-06-30T10:21:11.6188071Z"
        }
      }
    }
  ]
}
```

**Comment by MrTrick** [comment]
and for what it's worth, here's the specific processor rule that worked for me, thanks @cbuescher.
```
PUT _ingest/pipeline/test-pipeline
{
  "description": "Working",
  "processors": [
    {
      "script": {
        "lang": "painless",
        "source": "ctx.event = ['original': ctx.message]"
      }
    }
  ]
}

POST _ingest/pipeline/test-pipeline/_simulate
{
  "docs": [ 
    {
      "_source": {
        "message": "I have \"quotation\" marks"
      }
    }
  ]
}
```
and result:
```
{
  "docs" : [
    {
      "doc" : {
        "_index" : "_index",
        "_type" : "_type",
        "_id" : "_id",
        "_source" : {
          "message" : """I have "quotation" marks""",
          "event" : {
            "original" : """I have "quotation" marks"""
          }
        },
        "_ingest" : {
          "timestamp" : "2021-06-30T10:41:52.6867311Z"
        }
      }
    }
  ]
}
```

**Comment by spinscale** [comment]
please use the forum for this kind of enquiries. and not issues that have been closed more than two years ago. Thanks!

Try `{{{src}}}` as mustache is doing HTML escaping otherwise. This is also the reason why some examples use triple braces in the docs.
