### ISSUE TITLE
Elasticsearch process stuck on our machine(or virtual machine failure) which have a NFS mount point when NFS service failure（resulting in `df -h` stuck)

### ISSUE THREAD

**Issue by wuyunfeng** [elastic/elasticsearch#30611]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):5.5.0

**Plugins installed**: [ik、repository-hdfs、repository-s3]

**JVM version** (`java -version`):1.8.0_131

**OS version** (`uname -a` if on a Unix-like system):CentOS 7.3

**Description of the problem including expected versus actual behavior**: Elasticsearch process stuck on our machine(or virtual machine failure) which have a NFS mount point when NFS service failure（resulting in `df -h` stuck)

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Start NFS service which have a mount point /mnt/nfs..
 2. Stop NFS service (do not umount the mount point)
 3. Start Elasticsearch,Elasticsearch stuck forever...

**Provide logs (if relevant)**:
Java Stacktrace:

124 "main" #1 prio=5 os_prio=0 tid=0x00007fe7bc00b000 nid=0x8476 runnable [0x00007fe7c56be000]
125    java.lang.Thread.State: RUNNABLE
126         at java.io.UnixFileSystem.canonicalize0(Native Method)
127         at java.io.UnixFileSystem.canonicalize(UnixFileSystem.java:172)
128         at java.io.File.getCanonicalPath(File.java:618)
129         at java.io.FilePermission$1.run(FilePermission.java:215)
130         at java.io.FilePermission$1.run(FilePermission.java:203)
131         at java.security.AccessController.doPrivileged(Native Method)
132         at java.io.FilePermission.init(FilePermission.java:203)
133         at java.io.FilePermission.<init>(FilePermission.java:277)
134         at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
135         at sun.nio.fs.UnixFileSystem$FileStoreIterator.readNext(UnixFileSystem.java:207)
136         at sun.nio.fs.UnixFileSystem$FileStoreIterator.hasNext(UnixFileSystem.java:224)
137         - locked <0x00000003cb23c398> (a sun.nio.fs.UnixFileSystem$FileStoreIterator)
138         at org.apache.lucene.util.IOUtils.**getFileStore**(IOUtils.java:595)
139         at org.apache.lucene.util.IOUtils.spinsLinux(IOUtils.java:539)
140         at org.apache.lucene.util.IOUtils.spins(IOUtils.java:528)
141         at org.elasticsearch.env.ESFileStore.<init>(ESFileStore.java:60)
142         at org.elasticsearch.env.Environment.<clinit>(Environment.java:119)
143         at org.elasticsearch.node.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:90)
144         at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:72)
145         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
146         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
147         at org.elasticsearch.cli.Command.main(Command.java:88)
148         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
149         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)

**Then we find  the method `IOUtils.**getFileStore** ` invoke the `path.getFileSystem().getFileStores()` , this like the `df  -h` command stucked....**

`static FileStore getFileStore(Path path) throws IOException {
    FileStore store = Files.getFileStore(path);
    String mount = getMountPoint(store);

    // find the "matching" FileStore from system list, it's the one we want, but only return
    // that if it's unambiguous (only one matching):
    FileStore sameMountPoint = null;
    for (FileStore fs : path.getFileSystem().getFileStores()) {
      if (mount.equals(getMountPoint(fs))) {
        if (sameMountPoint == null) {
          sameMountPoint = fs;
        } else {
          // more than one filesystem has the same mount point; something is wrong!
          // fall back to crappy one we got from Files.getFileStore
          return store;
        }
      }
    }`

How we resolve this problem, Can we modify the Lucene `IOUtils.getFileStore` or  elasticsearch team can provide a better solution?

**Comment by ywelsch** [comment]
Shoud be fixed by https://github.com/elastic/elasticsearch/pull/24402. Can you check?

**Comment by wuyunfeng** [comment]
@ywelsch Thanks.  We will merge these changes to 5.5.0 in our local repo.
