### ISSUE TITLE
Low-level REST client: remove support for default headers

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#30616]
The low-level REST client currently supports setting default headers, so that they will be automatically set to each request. Headers can also be set at the request level, and in case they have the same key as default ones they will override them. The http client that we use already supports a similar functionality, the only difference being that default headers cannot be overridden, rather request headers will be sent together with default headers regardless of their keys.

I wonder if we should have added this feature in the first place, the idea was that one may want to set credentials at the client level, yet for some specific requests there may be the need to override those with other credentials, which would require default headers to be overridden with request headers that have the same key. Maybe we should remove such functionality and just rely on what the http client offers out-of-the-box. Replacing headers with same key sounds like a hack as multiple headers with same key are definitely allowed, so this functionality may allow for one use-case while disallowing for different ones. If some default headers need to be overridden, a different client instance should be used instead, although that goes against the "reuse the same client instance" best practice?

We could otherwise look into adding the ability to intercept headers and remove some if overriding is needed, but that would make things quite complicated, so I would be reluctant on making such a change.

This issue is to discuss what people think about this feature and validate that it's needed or whether we should remove it.

**Comment by javanna** [comment]
I am not sure that `RequestOptions` would be a 1:1 replacement for the current default headers. I opened this issue because the apache http client that we use already has a way to provide default headers, so we would not need our own. But our own way works differently and was built to be able to override default headers at the request level, which I realized later is a bit of a hack. 

`RequestOptions` are the new way to provide headers among other things but we don't currently support them globally, and even when we'll have that, I doubt that we will want to do with headers what we currently do (replace the default headers with same name as the provided request headers).

I think that we are agreeing though that we can get rid of our own default headers implementation regardless?

**Comment by nik9000** [comment]
> I think that we are agreeing though that we can get rid of our own default headers implementation regardless?

Yeah. I think we can tell folks to use a common `RequestOptions` if they want any default headers. But the ones in httpclient should be fine too.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
