### ISSUE TITLE
Elastic Search - Free Text Search - Nested fields - (Elastic 6.2)

### ISSUE THREAD

**Issue by Sarathmskr** [elastic/elasticsearch#30622]
```
GET /index/_search
{
    "query": {
        "simple_query_string": {
            "query": "so-well"
        }
     }
}
```
This works fine.

The same I need to search in Nested objects and in non nested at the same time. My full document contain more than 500 fields, most of them are in nested level. when I search non nested It's working fine, but not for nested fields. 

I tried to create a sample .. like below, but no luck.. getting empty result.
```json
{
  "query": {
    "bool": {
      "must": [{
        "nested": {
          "query": {
            "bool": {
              "must": [{
                "simple_query_string": {
                  "query": "so-well"
                }
              }]
            }
          },
          "path": "nestedObj1"
        }
      }, {
        "nested": {
          "query": {
            "bool": {
              "must": [{
                "simple_query_string": {
                  "query": "so-well"
                }
              }]
            }
          },
          "path": "nestedObj2"
        }
      }, {
        "simple_query_string": {
          "query": "so-well"
        }
      }]
    }
  }
}
```
Let me know if anything need to be add.

**Comment by jbaiera** [comment]
@elastic/es-search-aggs

**Comment by jbaiera** [comment]
Can you post your mappings that you are running against here as an additional bit of info?

**Comment by Sarathmskr** [comment]
PUT /companies_v1
{
  "mappings": {
    "companies": {
      "properties": {
        "companyName": {
          "type": "nested"
        },
        "companyState": {
          "type": "nested" 
        },
        "companySpecification": {
          "type": "nested"
        },
        "companyOperator": {
          "type": "nested"
        }
      }
    }
  },
  "settings" :{
    "index.mapping.total_fields.limit": 2000,
              "number_of_shards" :   1,
              "number_of_replicas" : 0
   }
}

I was searching for free Text in all my fields, not specifying any particular, and I have more than 500 fields in each document

**Comment by jimczi** [comment]
Hi @Sarathmskr ,
Please ask questions like this in our forums. We reserve github issues for bug reports and feature requests. Also I tried your example on 6.2 and it works as expected so please add the version and a complete recreation if you open a topic on discuss:
https://discuss.elastic.co/c/elasticsearch

**Comment by Sarathmskr** [comment]
Hi, 
I raised the same in 
https://discuss.elastic.co/t/elastic-search-free-text-search-nested-fields-elastic-6-2/132081
