### ISSUE TITLE
Repository GCS test deprecated settings is broken

### ISSUE THREAD

**Issue by jasontedor** [elastic/elasticsearch#30638]
This assertion:

https://github.com/elastic/elasticsearch/blob/873d380f455811c6f3002ad3436f310e3e3dfb78/plugins/repository-gcs/src/test/java/org/elasticsearch/repositories/gcs/GoogleCloudStorageRepositoryDeprecationTests.java#L53-L56

fails reliably in 6.x This appears to be because code that would produce such methods never appears in production code.

**Comment by jasontedor** [comment]
I pushed c350c22b5c8cb70c980532a60d15a1b06d40dc73.

**Comment by albertzaharovits** [comment]
Apologies for the blunder.
I have botched the backport and autocomplete for the test command jumped to another command `./gradlew :plugins:repository-gcs:clean :plugins:repository-gcs:assemble` .

On it.

**Comment by tlrx** [comment]
And sorry for not having caught this in the review.

**Comment by albertzaharovits** [comment]
I have pushed 0aafb060c640ae0bb230e69fed08 and unawaitsfixed the test. I am sorry for the sloppiness.
