### ISSUE TITLE
Remove IndicesOptions.fromOptions

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#30663]
The idea is to replace `IndicesOptions.fromOptions` with `new IndicesOptions(...,...)`

Now that IndicesOptions is not byte-based ( #30586 ), the [fromOptions](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/support/IndicesOptions.java#L262-L271) methods for creating new IndicesOptions objects is not as direct in its representation. Two things make this method signature problematic. For one thing, it makes adding new flags really difficult since it requires many changes to existing usages and/or adding yet another method signature. Another is that the method is trappy and it is not straightforward to keep track of which boolean is associated to which flag.

**Comment by PedroDMonteiro** [comment]
I'd like to contribute with a PR

**Comment by dakrone** [comment]
This class (IndicesOptions) has been refactored to be much better, so this is no longer applicable.
