### ISSUE TITLE
msearch - bad request - method and path required

### ISSUE THREAD

**Issue by lsotov** [elastic/elasticsearch#30661]
**Describe the feature**:
We just upgraded to Elastic 6.24, and we are executing a request like the following using Postman: 
https://site.com/kibana/api/console/proxy?uri=system-stats/_msearch
with the following payload:
{"index" : "system-stats"}
{"query" : {"match_all" : {}}, "from" : 0, "size" : 10}
Sending the headers:
kbn-version: 6.2.4
Content-type: application/x-ndjson

And we are getting the following result:
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "child \"method\" fails because [\"method\" is required]. child \"path\" fails because [\"path\" is required]",
    "validation": {
        "source": "query",
        "keys": [
            "method",
            "path"
        ]
    }
}

We would like to know what we are missing in the request and/or the elastic/kibana configuration.

Regards,

**Comment by andyb-elastic** [comment]
Hi, we use this issue tracker for bug reports and feature requests. Questions like this are best asked in the elasticsearch forum https://discuss.elastic.co/c/elasticsearch
