### ISSUE TITLE
[docs] indices.store.throttle.max_bytes_per_sec deprecated

### ISSUE THREAD

**Issue by zakkg3** [elastic/elasticsearch#30678]
https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-performance.html

indices.store.throttle.max_bytes_per_sec and indices.store.throttle.type are not recognized anymore.

**Store throttling settings**

> Store throttling has been removed. As a consequence, the indices.store.throttle.type and indices.store.throttle.max_bytes_per_sec cluster settings and the index.store.throttle.type and index.store.throttle.max_bytes_per_sec index settings are not recognized anymore.

**Comment by danielmitterdorfer** [comment]
Note that this note is from the Definitive Guide and not in the Elasticsearch's reference documentation. The Definitive Guide is maintained not here but rather at https://github.com/elastic/elasticsearch-definitive-guide thus closing this issue. Please feel free to open an issue in the repo mentioned above.
