### ISSUE TITLE
conflict between alias routing and parent/child routing

### ISSUE THREAD

**Issue by erikcameron** [elastic/elasticsearch#3068]
I was trying to create aliases with routing on an index that includes parent/child docs. Posting to an alias endpoint while specifying "parent=X" causes an error. I was thinking it shouldn't, because the parent/child routing is to ensure the docs will wind up on the same shard, but this is already guaranteed by the routed alias.

Curl recreation:

https://gist.github.com/erikcameron/5621421

As noted, it looks like it works if you give parent and routing explicitly. 

Thanks!
-E

**Comment by aewhite** [comment]
Any chance of this getting back-ported to ES 2.x? This is a rather high priority bug for us since we can't determine the routing of the parent without investigating the alias directly before every insert (which is very expensive).

**Comment by jondeandres** [comment]
any news on this? This bug is happening still in 2.3.3, has been ported to any 2.x tag?
