### ISSUE TITLE
[CI] SmokeTestWatcherClientYamlTestSuiteIT "Test Jira Action with Error" failure

### ISSUE THREAD

**Issue by rjernst** [elastic/elasticsearch#30705]
This test fails periodically because watcher is not started. This is likely because the node is considered green even when watcher is not started. So on a slow node, the test could start before watcher gets to the started state.

https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+5.6+multijob-unix-compatibility/1568/console

**Comment by hub-cap** [comment]
is it valid to think that a node is green before its plugins have finished starting up? This obviously does not pertain to only watcher, but watcher def has a bunch of internals that take some time to "wake up and start". Does it make sense to not allow the node to be green until this is the case?
