### ISSUE TITLE
[CI] ModelPlotsIT.testPartitionFieldWithTerms

### ISSUE THREAD

**Issue by vladimirdolzhenko** [elastic/elasticsearch#30715]
Log:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=opensuse/1066/console

```
  2> REPRODUCE WITH: ./gradlew :x-pack:qa:ml-native-tests:integTestRunner -Dtests.seed=7B45534D9707C727 -Dtests.class=org.elasticsearch.xpack.ml.integration.ModelPlotsIT -Dtests.method="testPartitionFieldWithTerms" -Dtests.security.manager=true -Dtests.locale=en-PH -Dtests.timezone=Antarctica/Palmer
   > Throwable #1: java.lang.AssertionError: 
   > Expected: <23>
   >      but: was <24>
   >   at __randomizedtesting.SeedInfo.seed([7B45534D9707C727:3650B455272ED35]:0)
   >   at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >   at org.elasticsearch.xpack.ml.integration.ModelPlotsIT.testPartitionFieldWithTerms(ModelPlotsIT.java:104)
   >   at java.lang.Thread.run(Thread.java:748)
```

@elastic/ml-core could you please have a look ?

**Comment by ywelsch** [comment]
This is still failing with same issue:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=amazon/1094/console

**Comment by droberts195** [comment]
@dimitris-athanasiou please could you take a look at the model plot issue?  When you look at the log you'll see it's full of errors like this:

```
[2018-06-01T07:58:25,084][ERROR][o.e.x.m.j.p.l.CppLogMessageHandler] [lookback-job] [autodetect/123361] [CMonotonicTime.cc@40] Failed to get reading from hi-res clock
```

I suspect these are completely unrelated to the problem logged in this issue, but a side effect of the recent seccomp changes in the C++.  I have asked @davidkyle to look into the hi-res clock failures as part of the ml-cpp seccomp work.

**Comment by dimitris-athanasiou** [comment]
@droberts195 I missed relaxing the assertion for one of the tests in #30717. I'll raise a PR fixing that shortly.
