### ISSUE TITLE
Document ingest limitations

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#30724]
Ingest does not process update requests and support the `doc_as_upsert` option properly. This should be clearly documented.

Relates to #30627

**Comment by developedsoftware** [comment]
Spent 2 hours trying to figure out why my pipeline wasnt getting hit when using doc_as_upsert. 
Is a fix on the horizon?

**Comment by debadair** [comment]
[doc-issue-triage]

**Comment by developedsoftware** [comment]
@debadair what was the result of the triage? Is it possible?

**Comment by synaq** [comment]
Hi @debadair,  is there any update to this issue? Also just spent half a day pulling my hair out.

**Comment by asfalots** [comment]
Hi, Same issue for me, spent a few hours to discover the culprit.  

At least updating the document will help

**Comment by jrodewig** [comment]
Closed with #57649
