### ISSUE TITLE
How to stop search operation once match happend

### ISSUE THREAD

**Issue by KSSekhar** [elastic/elasticsearch#30736]
Example: 

I have Bool Query under should array of 5 match cases
Match case 1
Match case 2
Match case 3 
Match case 4
Match case 5

I need to stop search operation once match happend on elastic search or continue up to match case 5.

Due to this search operation performance affected.

**Comment by tsouza** [comment]
This repository is for reporting specific issues in Elasticsearch. For general usage help, please use the discussion forum: https://discuss.elastic.co/c/elasticsearch
