### ISSUE TITLE
[doc] Sample LDAP configuration refers to deprecated setting

### ISSUE THREAD

**Issue by tsouza** [elastic/elasticsearch#30735]
The LDAP Realm sample described here https://www.elastic.co/guide/en/x-pack/current/ldap-realm.html refers to the deprecated setting `user_search.attribute`. It should be removed from the sample.

**Comment by lcawl** [comment]
Per @jstrassb this issue exists in the most recent docs here: https://www.elastic.co/guide/en/elasticsearch/reference/master/configuring-ldap-realm.html
