### ISSUE TITLE
Snapshot and restore queue

### ISSUE THREAD

**Issue by packetrevolt** [elastic/elasticsearch#30742]
Specific to using this in the typical ELK stack logging solution the lack of a snapshot/restore queue is confusing to end users and a major limitation.  This has been brought up here before and also on the forums a few times with the suggestion on the forum to open up an issue here.   I was just wondering if there was (or could be) any reconsideration into adding a snapshot/restore queue.

An example use case:
- Collect 5TB of logs per day
- Keep 30 days online in Elasticsearch
- 30+ days take a snapshot and delete from Elasticsearch
- Keep snapshot for 1+ years
- Users have the ability to create snapshots of indexes not normally snapshotted
- Users have the ability to restore old snapshots to reference old logs

Automation tools that create snapshots need to either wait until completion and then run the next snapshot creation sequentially (Curator) or continually retry the snapshot creation task until successful. The sequential creation of snapshots can get derailed should there be a failure during the process (the server running the snapshot creation tasks getting rebooted for example) and necessary logic introduced to verify that snapshots were indeed created and/or restarting from where the sequential task left off at. This has led to mostly using the continual retry method where independent snapshot jobs all continually attempt to create snapshots until they are successful. It works, but it is very messy and less then idea. This is especially problematic if you want to give certain users the ability to create a snapshot in a cluster where there are continual background snapshot tasks running throughout the day, a user either has to get lucky and create a snapshot when no other one is running or the user has to resort to scripting a loop for the snapshot creation request that continues to loop until successful.

Restores are particularly painful. Users sometimes need to go back to back and reference the data that was archived off in snapshots which means it needs to be restored. This runs into the same problem above in that there is no queue for snapshot tasks in Elasticsearch so a user is either left trying to manually restore a snapshot repeatedly until successful, or writing a script that loops indefinitely until successful. How does a user get his restore to happen sooner? Have the script loop once per second of course!! since the snapshot API is first come first serve.

**Comment by bleskes** [comment]
@tlrx @ywelsch any thoughts here?

**Comment by jasontedor** [comment]
Note that this has been discussed previously in #27353 and closed as won't fix.
