### ISSUE TITLE
create-index: Default number of shards does not match v7 changes

### ISSUE THREAD

**Issue by atc0005** [elastic/elasticsearch#30746]
I saw in the blog post that #30539 changes the default number of primary shards to 1. Looking over the docs I found that in `master` the `create-index` API coverage still showed 5 as the default number instead of 1. I assume that this was just missed in the recent round of doc updates from 4852f34d324408176bbd3857b79af4e66c65621a.

**Comment by jasontedor** [comment]
Thanks for noticing this. Do you want to submit a pull request otherwise I’ll push a fix for this on Monday?

**Comment by jasontedor** [comment]
Oh I see we were racing and you already submitted a pull request. Thanks for that!

**Comment by atc0005** [comment]
> Oh I see we were racing and you already submitted a pull request. Thanks for that!

You're welcome! I started with the PR, but held back once I noticed that one of the "make sure you do X" checklist items included creating an issue first.

Please let me know if I missed anything or need to go about the change in a different way. I'm new to ES, so I may have missed something obvious to long-time users.

**Comment by jasontedor** [comment]
>Please let me know if I missed anything or need to go about the change in a different way. I'm new to ES, so I may have missed something obvious to long-time users.

It’s perfect. Thanks for your interest and your contribution.

**Comment by atc0005** [comment]
> It’s perfect. Thanks for your interest and your contribution.

Awesome! You're welcome, and thanks for the feedback.
