### ISSUE TITLE
Cannot upload snapshots to minio

### ISSUE THREAD

**Issue by iahmad-khan** [elastic/elasticsearch#30752]
Hi,

I am using the latest stable version of minio with elasticsearch 6.1.2. I have created a bucket named: elasticsearch , to which I can upload files using the browser interface.

I want to use the same bucket to stor elasticsearch snapshots. Elastic repo config:

```
PUT _snapshot/backups
{
     "type": "s3",
      "settings": {
         "bucket": "elasticsearch",
         "endpoint": "minio.mydomain:9000",
         "protocol": "http"
      }
}
```

Error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "sdk_client_exception",
        "reason": "sdk_client_exception: Unable to execute HTTP request: elasticsearch.minio.mydomain:9000"
      }
    ],
    "type": "repository_exception",
    "reason": "[backups] failed to create repository",
    "caused_by": {
      "type": "sdk_client_exception",
      "reason": "sdk_client_exception: Unable to execute HTTP request: elasticsearch.minio.mydomain:9000",
      "caused_by": {
        "type": "i_o_exception",
        "reason": "elasticsearch.minio.mydomain:9000"
      }
    }
  },
  "status": 500
}
```

Does it related to the fact that elasticsearch s3 plugin expects s3 kind of url:

`elasticsearch.minio.mydomain:9000`

while the url in minio is:

`minio.mydomain:9000/minio/elasticsearch
`
thanks

**Comment by iahmad-khan** [comment]
Closing , needed to run minio in s3 style urls.

**Comment by iahmad-khan** [comment]
Can we change some elasticsearch plugin configuration to use:

`minio.mydomain:9000/minio/elasticsearch
`


instread of this:
`elasticsearch.minio.mydomain:9000`

as the second one even have problem with dns , it will not even resolve to some valid ip.

**Comment by tlrx** [comment]
@iahmad-khan Elasticsearch uses the official AWS SDK Java client to access to S3 repositories. The SDK decides if it should use path style access or not when accessing a bucket and the documentation can be [found in the SDK source code](https://github.com/aws/aws-sdk-java/blob/1.11.235/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/S3ClientOptions.java#L78):

> The default behaviour is to detect which access style to use based on the configured endpoint (an IP will result in path-style access) and the bucket being accessed (some buckets are not valid DNS names).

So in your case I guess you can try to use an IP address as the endpoint.
