### ISSUE TITLE
Error loading java version in openSuse

### ISSUE THREAD

**Issue by renatofritola** [elastic/elasticsearch#30754]
**Elasticsearch version** (`bin/elasticsearch --version`):

Elasticsearch 5.6.3

**JVM version** (`java -version`): 

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Linux srv-devops 3.16.7-53-desktop #1 SMP PREEMPT Fri Dec 2 13:19:28 UTC 2016 (7b4a1f9) x86_64 x86_64 x86_64 GNU/Linux

NAME=openSUSE
VERSION="13.2 (Harlequin)"
VERSION_ID="13.2"
PRETTY_NAME="openSUSE 13.2 (Harlequin) (x86_64)"

**Description of the problem including expected versus actual behavior**:

When you start elasticsearch through sonarqube, it can not read the installed java version.

The environment variable is configured, and I am not using the root user.

I have already checked other people pages that have had similar problems but they have not solved my problem.

**Steps to reproduce**:

I just execute ./bin/elasticsearch

**Provide logs (if relevant)**:

```
sonar@srv-devops:/opt/sonarqube/elasticsearch/bin> ./elasticsearch
./elasticsearch: line 48: grep: command not found
./elasticsearch: line 108: dirname: command not found
./elasticsearch: line 142: dirname: command not found
Error: Could not find or load main class org.elasticsearch.tools.JavaVersionChecker
Elasticsearch requires at least Java 8 but your Java version from /usr/java/jdk1.8.0_131/jre//bin/java does not meet this requirement

```

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be an environmental issue, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
