### ISSUE TITLE
ContextIndexSearcher conflicts with IndexSearcherWrapper

### ISSUE THREAD

**Issue by salyh** [elastic/elasticsearch#30758]
**Elasticsearch version** (`bin/elasticsearch --version`):
5.0.0+

**Plugins installed**: []
N/A

**JVM version** (`java -version`):
N/A

**OS version** (`uname -a` if on a Unix-like system):
N/A

**Description of the problem including expected versus actual behavior**:

Plugins can override the `onIndexModule(IndexModule indexModule)` method and call `indexModule.setSearcherWrapper`.
They implement a `IndexSearcherWrapper` (via `IndexSearcherWrapperFactory`) and override the `protected IndexSearcher wrap(IndexSearcher searcher) throws IOException` method to
wrap a given IndexSearcher. When i read the newly opened x-pack code correct it seems x-pack is doing this to implement document and field level security.

But it appears that several methods of a such wrapped IndexSearcher (like `search*`) are never really called because the wrapped IndexSearcher get itself wrapped in
a `ContextIndexSearcher` (in `DefaultSearchContext`) which never delegates the wrapped `search*` methods (and others).

For x-pack this means IMHO that the custom searcher optimizations done in [SecurityIndexSearcherWrapper](https://github.com/elastic/elasticsearch/blob/eaf672f6121c4dc2a48f3524c80fa18d39dc9d2e/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/accesscontrol/SecurityIndexSearcherWrapper.java#L190) are never executed.

Or i'am lost in the "wrapper hell"? 

**Steps to reproduce**:
N/A

**Provide logs (if relevant)**:
N/A

**Comment by salyh** [comment]
A fix for this maybe can look like this https://github.com/salyh/elasticsearch/commit/c33c67d9500c78f5159dfb3837da2040b147b330

**Comment by jaymode** [comment]
Heya @salyh, thanks for the report. This indeed appears to be the case where the performance optimizations in the SecurityIndexSearcherWrapper are not being executed.

**Comment by salyh** [comment]
@jaymode @elastic/es-security Any plans to fix this?

**Comment by salyh** [comment]
:hourglass: :disappointed:
