### ISSUE TITLE
Curator started reporting error in delete_indices 'An HTTP line is larger than 4096 bytes.'

### ISSUE THREAD

**Issue by MohammadRamadan** [elastic/elasticsearch#30753]
Hello Friends,
                 I have ELK stack with curator installed to delete logs older than 365 days.
a script created is used to make this process under crontab job that used to delete these older than 365 days logs.
everything was going well for days and suddenly when checking the job logs I found it report and error as follow : 
2018-05-21 13:02:19,057 INFO      Preparing Action ID: 1, "delete_indices"
2018-05-21 13:02:19,067 INFO      Trying Action ID: 1, "delete_indices": Delete indices older than 365 days (based on index name), for custom- prefixed indices. Ignore the error if the filter does not result in an actionable list of indices (ignore_empty_list) and exit cleanly.
2018-05-21 13:02:19,304 ERROR     Failed to complete action: delete_indices.  <class 'elasticsearch.exceptions.RequestError'>: TransportError(400, 'too_long_frame_exception', 'An HTTP line is larger than 4096 bytes.')
------------------------------------------------------------------
versions data as follow: 
di@ELK-5:~$ curl -XGET 'localhost:9200'
{
  "name" : "QInEGiG",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "SEqBRvyiSjCBPJLpMBVgrg",
  "version" : {
    "number" : "5.6.5",
    "build_hash" : "6a37571",
    "build_date" : "2017-12-04T07:50:10.466Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
di@ELK-5:~$ 
---------------------------------------------------------------------
curator, version 5.4.1
---------------------------------------------------------------------
Any help guys, am network engineer and not a developer :( 
TIA

**Comment by jasontedor** [comment]
This likely means that Curator is sending too many indices to delete at once and is exceeding the line length limit on the initial HTTP request line. The first line looks like

```
DELETE /<indices to delete> HTTP/1.1
```

and I suspect it is the list of indices that is entirely too long. First, I would consider this to be a curator bug and I think that you should open an issue on the Curator [issue tracker](https://github.com/elastic/curator). Secondly, you can work around this by finding out how long that initial line length is that Curator is exceeding and then you can set `http.max_initial_line_length` and restart Elasticsearch (the default is 4 KiB).

Given that I do not think this is an Elasticsearch bug, I am going to close this as we reserve GitHub for verified bug reports, feature requests, and pull requests.
