### ISSUE TITLE
Allow GET /_tasks/<taskid> to support a list of tasks

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch#30768]
**Describe the feature**:

It would be cool if `GET /_tasks/<taskid>` could support a list of task ids (i.e., comma separated or as a request body).  

My use case here is to avoid using the `detailed` parameter together with the `actions` parameter, which may cause detailed information to be gathered for quite a few running tasks, which according to the docs can be expensive.  So I'd like to target the `detailed` usage to just a specific subset of tasks.  Rather than issuing a request per tasks, I'd like to issue a single request with a list of tasks.

**Comment by jasontedor** [comment]
I would prefer that we stop adding these APIs that allow GET on a comma-separated list of resources. The problem that I have with them is that it complicates the API:
 - what status do we return if some but not all of the tasks are missing?
 - what status do we return if some but not all of the tasks cause an internal server error?
 - what status do we return if some of the tasks are present, some are missing, and some cause an internal server error?

I have my take on this, but we have endlessly debated questions like this before and I don't think anyone is satisfied with the answers. I especially think that clients are unhappy no matter what we choose. Regardless of how we answer them, it also means that we have to have complicated responses to accommodate for these partial failure scenarios with a response body to account for errors and the details of such, and response for the tasks that exist. We end up with a ball of complicated code and a complicated API for a little convenience all to save multiple roundtrips. To me that tradeoff is not worth it and I would like us to go in the direction of simplicity here.

**Comment by bleskes** [comment]
Another complication here is that that specific API is currently geared towards a single task. If we want to return multiple tasks, we'll need to change the response format to be keyed by task id, which also means a BWC break. Not sure if it's worth it here. 

@joshuar can you share more about what you're building? it sounds like you'd need a kind of pagination on the `_tasks` API?

**Comment by imotov** [comment]
@joshuar we recently added an ability to mark task groups using [X-Opaque-Id](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/tasks.html#_identifying_running_tasks) header.  We don't have an ability to filter by this header yet, but if we implemented that, would it work better for you? What problem are you trying to solve by this feature?

**Comment by joshuar** [comment]
Oh nice @imotov. Filtering by that would be ideal.  

I was mainly just trying to follow what I interpreted as best practice for this API, which is to avoid using  `detailed` where the number of tasks returned might be very large.  Do we know how use of this parameter scales with regards to affecting performance?  For example, doing `GET /_tasks?actions=*search&detailed` where there might be 100 executing searches?  1000 searches?

Side note: we could/should update our best practices to recommend setting this header on requests?  Seems extremely useful?

**Comment by imotov** [comment]
@joshuar I opened #30868. For some reason I thought it was already implemented, but it looks like I never got to it after all. Should we close this issue in favor of #30868?

**Comment by imotov** [comment]
Closing in favor of #30868
