### ISSUE TITLE
Remove hardcoded ports in security vagrant tests

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#30782]
In practice hardcoded ports are a bad idea and lead to conflicts and spurious CI failures. We should try to minimize the use of these as much as possible. To that end, there are a few security test suites that rely on hardcoded port values with vagrant fixtures. 

The idp-fixture hardcodes the following port forwards:

https://github.com/elastic/elasticsearch/blob/5f172b6795c2d7917144c535542ad521698016c5/x-pack/test/idp-fixture/Vagrantfile#L13-L16

The smb-fixture hardcodes the following port forwards:

https://github.com/elastic/elasticsearch/blob/5f172b6795c2d7917144c535542ad521698016c5/x-pack/test/smb-fixture/Vagrantfile#L13-L16

These hardcoded ports are ephemeral ports and could be in use already. We can make use of dynamic port mapping and use [vagrant port](https://www.vagrantup.com/docs/cli/port.html) to get the forwarded port and pass this along to tests.

**Comment by MariaTeresaFerreira** [comment]
Hi! Can I take care of this issue?

**Comment by atorok** [comment]
`smb-fixtures` was ported to docker based fixtures. 
The new plugin exposes the mapped ports as  system properties  to tests automatically. 
I think we should make `idp-fixture` docker based as well.

**Comment by atorok** [comment]
We no longer have vagrant fixtures we use docker based test fixtures that handle port mapping and use no hard coded ports
