### ISSUE TITLE
Auto adjust shard count on index size

### ISSUE THREAD

**Issue by nicolasguyomar** [elastic/elasticsearch#30784]
Since now the new shard count will be 1, I was wondering if it would it be feasible to auto-adjust an newly created index shard count based on a size limit (let's say 25Gb for instance) for timeseries with daily pattern. 
This setting could be part of the index template (auto_increment_shard_by : 2, auto_increment_shard_threshold: 25Gb)

Any thoughts ? Too hard to implement ? 
Thank you

**Comment by dakrone** [comment]
I believe this is resolved by https://github.com/elastic/elasticsearch/pull/106076, it is present on Serverless Elasticsearch. I'm going to close this for now, though we may explore non-Serverless autosharding in the future.
