### ISSUE TITLE
http compression support in RestHighLevelClient

### ISSUE THREAD

**Issue by fiserro** [elastic/elasticsearch#30789]
If we used default headers "Accept-Encoding":"deflate,gzip" then JsonParseException is thrown when RestHighLevelClient is trying to parse compressed data by jackson parser.
Using httpCientBuilder.addInterceptorFirst(new ResponseContentEncoding(true)) does not seems to have any efect.
 Is this feature on the roadmap?

**Comment by javanna** [comment]
I believe this is the same as #24349 . The problem is not in the high-level REST client, but rather on the low-level REST client that the high-level REST client uses to perform http requests.

**Comment by dliappis** [comment]
Closing as duplicate of #24349
