### ISSUE TITLE
when i write painless script in kibana, and i use org.joda.time.MutableDateTime/DateTime， there is a error !

### ISSUE THREAD

**Issue by benhairui** [elastic/elasticsearch#30785]
{
  "error": {
    "root_cause": [
      {
        "type": "script_exception",
        "reason": "compile error",
        "script_stack": [
          "... oda.time.MutableDateTime tt = null;\n          def  ...",
          "                                                  ^---- HERE"
        ],
        "script": "          org.joda.time.MutableDateTime tt = null;\n          def t = (doc['tt'].value);\n        return t.MutableDateTime();",
        "lang": "painless"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "my_index3",
        "node": "IFseLg0mTEyuubB1mKyJPg",
        "reason": {
          "type": "script_exception",
          "reason": "compile error",
          "script_stack": [
            "... oda.time.MutableDateTime tt = null;\n          def  ...",
            "                             ^---- HERE"
          ],
          "script": "          org.joda.time.MutableDateTime tt = null;\n          def t = (doc['tt'].value);\n        return t.MutableDateTime();",
          "lang": "painless",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "unexpected token ['tt'] was expecting one of [{<EOF>, ';'}]."
          }
        }
      }
    ]
  },
  "status": 500
}

**Comment by jdconrad** [comment]
This is expected behavior so I'm going to close this issue.

**Comment by benhairui** [comment]
@rjernst Thanks for your answer, i will take your advice if i have another question. 
I try "Instance.ofEpochMilli(doc['tt'].value.millis)", but it report anther error.

{
  "error": {
    "root_cause": [
      {
        "type": "script_exception",
        "reason": "compile error",
        "script_stack": [
          "          long time = Instance.ofEpochMilli(doc ...",
          "                      ^---- HERE"
        ],
        "script": "          long time = Instance.ofEpochMilli(doc['produceDate'].value.millis);\n        return time;",
        "lang": "painless"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "my_index",
        "node": "IFseLg0mTEyuubB1mKyJPg",
        "reason": {
          "type": "script_exception",
          "reason": "compile error",
          "script_stack": [
            "          long time = Instance.ofEpochMilli(doc ...",
            "                      ^---- HERE"
          ],
          "script": "          long time = Instance.ofEpochMilli(doc['produceDate'].value.millis);\n        return time;",
          "lang": "painless",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "Variable [Instance] is not defined."
          }
        }
      }
    ]
  },
  "status": 500
}

**Comment by benhairui** [comment]
@rjernst thanks for your answer again! I am sorry for asking question on this page. I will take your advice!
Thanks again!!!
