### ISSUE TITLE
MemAvailable and/or Active Memory reporting

### ISSUE THREAD

**Issue by JohnSatriano** [elastic/elasticsearch#30798]
MemAvailable and/or Active Memory reporting. Free memory is often a less useful metric to report, especially when the OS is dedicating a significant portion of memory to the file system cache because of ElasticSearch's heavy use of the file system. The cached memory is easily reclaimed by an application if needed, so it's not very useful for monitoring for an imminent "Out of Memory" condition. 

"Active — The amount of memory, in kibibytes, that has been used more recently and is usually not reclaimed unless absolutely necessary. " https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s2-proc-meminfo

**Comment by dliappis** [comment]
If I understand correctly, the request is to additionally provide in Nodes Stats the `MemAvailable` and/or `Active` metrics on Linux systems, available in `/proc/meminfo` as described in the Kernel docs for the [proc filesysystem[(https://www.kernel.org/doc/Documentation/filesystems/proc.txt).

**Comment by jasontedor** [comment]
We feel that pulling these system-level statistics into Elasticsearch is not the direction that we want to go in. Instead, we feel that the right approach is have monitoring in place alongside Elasticsearch to monitor system-level stats, and Elasticsearch stats endpoints should provide application-level metrics which can be collected externally. For us, we have [metricbeat](https://www.elastic.co/products/beats/metricbeat) in our stack to ship system-level statistics, and today we have monitoring in X-Pack to collect the application-level statistics from Elasticsearch.
