### ISSUE TITLE
Extracted builder (or json request generation) classes to libs with minimal dependencies

### ISSUE THREAD

**Issue by marco-miller** [elastic/elasticsearch#30791]
Using the Elasticsearch low-level Java API or rest client is convenient because of the minimal dependencies that library has. It would be as useful (if not essential) for integrations like ours to benefit from minimal dependencies as well for the Builder classes.

A similar, related extraction was [completed recently for XContent](https://github.com/elastic/elasticsearch/tree/master/libs/x-content): #28504. How about considering doing the same for Builder classes in packages such as index.query, action.support, search.builder and maybe more? Those classes work closely with XContentBuilder thus could benefit from a similar extraction treatment.

Of course, the sibling high-level API aims at a similar purpose, but with more dependencies which conflict with libraries that are already integrated. That approach also prevents a system embedding an Elasticsearch client from supporting multiple Elasticsearch server versions.

**Comment by dadoonet** [comment]
See also #29184

**Comment by davido** [comment]
Yes, I'm aware of the transitive dependency of high level client on Lucene. That why we were considering to use low level rest client.

Still, for queries we have to use classes from ES `org.elasticsearch.index.query` package. But these classes are again depend on Lucene and on the rest of the server ES package, e.g. here `ExistsQueryBuilder` example 

https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/query/ExistsQueryBuilder.java#L22-L39.

And thus could not be easily isolated from the rest of the server code, unfortunately.

**Comment by colings86** [comment]
As mentioned in https://github.com/elastic/elasticsearch/issues/29184#issuecomment-375675720 this is definitely a goal of the High Level REST client (to separate its dependencies from the server dependencies. However this is a lot of work and it will take us time to achieve it as the dependencies are complex and some are used in the client code itself which we would need to unpick. Unfortunately its not as easy as moving classes to a new jar.

I'm going to close this issue in favour of https://github.com/elastic/elasticsearch/issues/29184 since we already have discussion on this there.

**Comment by javanna** [comment]
@davido that is pretty much the reason why the high-level REST client depends on Elasticsearch (and Lucene), we have no choice at the moment.

I find this and #29184 to be the same problem. We need some common library that can be used without depending on Elasticsearch (and Lucene). That sounds easy but requires a ton of work and will take time. The beginning of it is what we have done with the xcontent dependency, and we certainly want to make more progress in that direction.

That said, I am leaning towards closing this issue in favour of #29184, do you have objections?
