### ISSUE TITLE
IndexingIT mixed cluster test fails on master

### ISSUE THREAD

**Issue by tbrooks8** [elastic/elasticsearch#30818]
The following failure is reproducible on master:

```
./gradlew :qa:mixed-cluster:v6.4.0-SNAPSHOT#mixedClusterTestRunner -Dtests.seed=93013818D4459441 -Dtests.class=org.elasticsearch.backwards.IndexingIT -Dtests.method="testSeqNoCheckpoints" -Dtests.security.manager=true -Dtests.locale=es-CU -Dtests.timezone=US/Indiana-Starke
```

This originally failed in this PR build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/10371/

However, it reproduces for me on the normal master build.

**Comment by tbrooks8** [comment]
This actually does not reproduce any more for me. 

I think that 405eb7a751a047b24272f17116d85b157ed30388 fixed this issue. The build that failed here had a bunch of mixed cluster tests fail. If I checkout the commit before 405eb7a751a047b24272f17116d85b157ed30388 the failure reproduces. So I think @jpountz fixed this with his commit.

**Comment by nik9000** [comment]
> So I think @jpountz fixed this with his commit.

Sweet!

**Comment by jpountz** [comment]
Thanks @tbrooks8, this should be fixed now indeed.
