### ISSUE TITLE
_doc vs doc in geo_point mapping tutorial

### ISSUE THREAD

**Issue by yaronp68** [elastic/elasticsearch#30835]
@debadair  
Since version 6.0 ES is using the _doc as the document type while logstash is using the doc as default document type. 
In the geo_point mapping examples there is a _doc notation which means, people who will use it will have problem with logstash ingesting to their index. Suggest to add a warning to use doc in ES or to add the `document_type => "_doc"` directive in logstash configuration

**Comment by jpountz** [comment]
Logstash moved to using `_doc` in 7.x, so this should be fixed in a reasonably near future: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/713?

**Comment by imotov** [comment]
Looks like logstash-plugins/logstash-output-elasticsearch#713 got merged in, should we close this issue then?

**Comment by jrodewig** [comment]
[docs issue triage]

Closing as fixed.
