### ISSUE TITLE
Ranking Evaluation API: Support for ratings to be provided as query instead of documents only

### ISSUE THREAD

**Issue by svola** [elastic/elasticsearch#30839]
The Ranking Evaluation API introduced in Elasticsearch version 6.2 currently only supports ratings to be provided as a single document identified by `_index`, and `_id` with a `rating`.

https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search-rank-eval.html

     "ratings": [ 
             { "_index": "my_index", "_id": "doc1", "rating": 0 },
             { "_index": "my_index", "_id": "doc2", "rating": 3},
             { "_index": "my_index", "_id": "doc3", "rating": 1 }
     ]

It would be nice at least from a feature perspective to being able to provide a query instead of a single rated document. 
This would allow for more documents to match and to semi-automatically create more testdata which is usually one of the most tedious parts/blocker in evaluation. 

Example:

    {
       "ratings":[
          {
             "query":{
                "more_like_this":{
                   "fields":[ "title", "description" ],
                   "like":[{ "_index":"my_index",  "_type":"doc", "_id":"doc2"}]
                }
             },
             "rating":3
          }
       ]
    }

**Comment by cbuescher** [comment]
Closing in favour of a summary in #40865
