### ISSUE TITLE
New feature request: Moving standard deviation

### ISSUE THREAD

**Issue by dipteshnath** [elastic/elasticsearch#30840]
Feature request

1. I have a daily purchase data. I would like to find out anomaly using moving average and moving standard deviation. The standard deviation will help me a create a window, based on which I will find the outliers and then send alert.
2. I would like to have moving standard deviation on time series data with Elasticsearch or TimeLion.

**Comment by dipteshnath** [comment]
Hi @polyfractal, 

Yaa, this helps my cause. I was really looking forward to that feature. Thanks, for the reply. 

 I had also earlier read your article- Implementing a Statistical Anomaly Detector in Elasticsearch. It was also a great help to me.

**Comment by polyfractal** [comment]
Great!  Happy to help, and let us know if you have difficulties with the new agg when it's released :)
