### ISSUE TITLE
Optimized keyword fields that only have integers and only need equality filtering

### ISSUE THREAD

**Issue by ddorian** [elastic/elasticsearch#30871]
Hi,

Does lucene / es optimize (or is there a way to config) keyword fields that are guaranteed to have only numbers and only need equality filtering (for inverted-index, doc-values, term dictionary etc) ?

I remember _id has this optimization, so the number isn't stored as a string(number).

Meaning, if it stores them as strings, then it would be better to store as base64 or something similar to reduce the string size?

Makes sense ?

Regards,
ddorian43

**Comment by javanna** [comment]
hi @ddorian , we reserve github issues for confirmed bug reports and feature requests. Could you please post your question to our forums at https://discuss.elastic.co/ ? Thanks!

**Comment by ddorian** [comment]
I have, but with no response: https://discuss.elastic.co/t/optimized-keyword-fields-that-only-have-integers/130612/2

**Comment by ddorian** [comment]
@javanna Can I change this into a feature-request since it's not available ?
