### ISSUE TITLE
[?] Incorrect `edit` links in the reference documentation

### ISSUE THREAD

**Issue by lipsill** [elastic/elasticsearch#30892]
When trying to edit the master reference docs for [Create Index](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-create-index.html#indices-create-index) (by pressing the `Edit` button on the docs page) I am redirected to the following x-pack doc file: https://github.com/elastic/elasticsearch/edit/master/x-pack/docs/en/security/securing-communications/tls-ldap.asciidoc. The same is happening for `6.x` and `6.3`.
The link for `6.2` and below is correct.

Is this intended as ES `6.3+` are not yet released?

Note: editing any doc in `6.3+` redirects to the same x-pack asciidoc.

**Comment by cbuescher** [comment]
@lipsill thanks for opening the issue.
i just saw this, there was another earlier issue reporting this that is tracking the issue now: #30883 
I will close this as a duplicate then.
