### ISSUE TITLE
Strange piece of code in ElasticsearchAssertions#assertVersionSerializable

### ISSUE THREAD

**Issue by scampi** [elastic/elasticsearch#30907]
The method `ElasticsearchAssertions#assertVersionSerializable` got removed in [commit](https://github.com/elastic/elasticsearch/commit/b7e6fb9ac5c8d0bb771e319c8968ddd89f502720) 
 but I would like to understand why that [line](https://github.com/elastic/elasticsearch/commit/b7e6fb9ac5c8d0bb771e319c8968ddd89f502720#diff-e7168ac65fa4c974595f24e243f2cf7eL701) uses the variable `streamable` instead of `newInstance`.

Shouldn't it have been comparing the serialization output of the newly created instance ?

**Comment by nik9000** [comment]
Yeah, it looks like it was wrong. It should have been using `newInstance`.

**Comment by nik9000** [comment]
I've closed the issue because the wrong code has already been removed so there isn't really anything else for anyone to do about it.

**Comment by scampi** [comment]
In the commit, it said this test didn't catch many errors which the mentioned error may have been the reason. Going forward, do you see that test still worth given the new data, or serialization testing of
objects is still "best left to their respective unit and integration tests." ?

**Comment by nik9000** [comment]
I still think this is best left to the unit and integration tests, yeah. We certainly can't catch everything in unit tests but we have much much better integration testing then we did when we built this at first and I think those are quite good at catching this.
