### ISSUE TITLE
[CI] Packaging tests fail while stopping systemd

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#30914]
Did not reproduce locally, but this is the build:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/2728/consoleFull

REPRODUCE WITH: ./gradlew :qa:vagrant:vagrantCentos7#batsPackagingTest -Dtests.seed=D483E0270BF44156 

And this is what I found in the logs that looks closest to an error:
```
20:32:36 not ok 206 [SYSTEMD] status (stopping)
20:32:36 not ok 206 [SYSTEMD] status (stopping)
20:32:36 # (in test file /project/build/packaging/bats/tests/60_systemd.bats, line 156)
20:32:36 # (in test file /project/build/packaging/bats/tests/60_systemd.bats, line 156)
20:32:36 #   `echo "$output" | grep "Active:" | grep "inactive"' failed
20:32:36 #   `echo "$output" | grep "Active:" | grep "inactive"' failed
20:32:37 ok 207 [SYSTEMD] stop (stopped)
20:32:37 not ok 208 [SYSTEMD] status (stopped)
20:32:37 not ok 208 [SYSTEMD] status (stopped)
20:32:37 # (in test file /project/build/packaging/bats/tests/60_systemd.bats, line 169)
20:32:37 # (in test file /project/build/packaging/bats/tests/60_systemd.bats, line 169)
20:32:37 #   `echo "$output" | grep "Active:" | grep "inactive"' failed
20:32:37 #   `echo "$output" | grep "Active:" | grep "inactive"' failed
```

**Comment by cbuescher** [comment]
Had some in PR builds now as well:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-sample/2364/console

**Comment by talevy** [comment]
@cbuescher do you remember any other context around this issue? It doesn't look like this was a problem in recent weeks, but all the existing build failure links 404.

**Comment by cbuescher** [comment]
@talevy I don't remember, if we don't currently see these issues anymore I think we can close this

**Comment by talevy** [comment]
OK. then I will go ahead and close this for that reason. If similar packaging test failures bubble up, we can re-open
