### ISSUE TITLE
Remove reference to repository-s3 plugin creating an S3 bucket

### ISSUE THREAD

**Issue by maximshd** [elastic/elasticsearch#30910]
[Docs](https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3-repository.html#repository-s3-permissions) mention that repository-s3 plugin is able to create AWS S3 bucket when it doesn't exist (and appropriate IAM permissions were added). 
But it just fails without any validation according to this part of a code:
`.         SocketAccess.doPrivilegedVoid(() -> {
            if (client.doesBucketExist(bucket) == false) {
                throw new IllegalArgumentException("The bucket [" + bucket + "] does not exist. Please create it before " +
                                                   " creating an s3 snapshot repository backed by it.");
            }
        });`

Previously cloud-aws plugin was able to create bucket. 
Is it expected for repository-s3 plugin?
Is it possible to change documentation accordingly to the plugin behavior or add possibility to create S3 bucket by ES/plugin means?

Thanks!

**Comment by dadoonet** [comment]
In doc you linked to I can see

> The bucket needs to exist to register a repository for snapshots. If you did not create the bucket then the repository registration will fail. 

Which part of the doc mentions something else?

**Comment by maximshd** [comment]
Hi, @dadoonet ,

"If you want Elasticsearch to create the bucket instead, you can add the permission to create a specific bucket like this:"

But seems like ES will not try to create any bucket in any cases.

**Comment by dadoonet** [comment]
Ha right. That's a leftover IMO. We should remove that part.
