### ISSUE TITLE
Plugin [analysis-phonetic] and [analysis-icu] is incompatible with ElasticSearch version [5.6.9]

### ISSUE THREAD

**Issue by pankajpragma** [elastic/elasticsearch#30921]
Recently updated the Ubuntu 16.04 and it does update the ElasticSearch from 5.6.8 to 5.6.9.

But it has stopped working ElasticSearch as analysis-phonetic and analysis-icu is incompatible with ElasticSearch 5.6.9

```
java.lang.IllegalArgumentException: plugin [analysis-phonetic] is incompatible with version [5.6.9]; was designed for version [5.6.8]

java.lang.IllegalArgumentException: plugin [analysis-icu] is incompatible with version [5.6.9]; was designed for version [5.6.8]
```

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

Here you need to uninstall old plugins and reinstall them.
