### ISSUE TITLE
Rest explain response missing `exists` field

### ISSUE THREAD

**Issue by PnPie** [elastic/elasticsearch#30981]
I'm recently working on rest high level `expalin` api and I may find an issue (or just a question) about a field in `ExplainResponse`.

The `ExplainResponse` has a field [`exists`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/explain/ExplainResponse.java#L41), which represents if the specified document in ExplainRequest exists. It is always necessary while [creating an `ExplainResponse` object](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/explain/ExplainResponse.java#L48-L63) and also [transfered during serialization](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/explain/ExplainResponse.java#L118), but it's not in the rest response.

In explain's rest response, we have put the [`matched`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/rest/action/search/RestExplainAction.java#L99) field which is derived from lucene's explanation object, briefly to say if there is a match for the passed query.

So as a consuquence, we are not able to re-create the `ExplainResponse` in rest high level client because the `exists` field doesn't exist in low level rest results. So do we initially want to put `exists` instead of `matched` in rest response ? Or we need to add `exists` field in response before `matched` for example ?

CC @javanna am I missing anything ? do you have an idea on it ?

**Comment by javanna** [comment]
@PnPie the exists flag is returned as the REST status code: 404 means false and 200 means true. That should be good enough to recreate the `ExplainResponse`, the only thing is that by default the client will throw exception if an error code is returned, then you will need to configure it to not treat 404 as an error for the explain API, we do it already [here](https://github.com/elastic/elasticsearch/blob/master/client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java#L317) for the get API.

**Comment by PnPie** [comment]
Okay thanks @javanna !
