### ISSUE TITLE
Updated document ID's

### ISSUE THREAD

**Issue by gvijayakumar-16** [elastic/elasticsearch#30997]
Hi,

Can we have an option where we can get the ID's of the documents which got updated?

I am currently dealing with a scenario wherein I need the list of document ID's that got updated using UpdateByQueryAsync and I am making additional calls to retrieve them.

**Comment by bleskes** [comment]
Sadly the update by query can potentially update millions of document and we have no way to collect all of them in a sane fashion for all use cases. If you have a specific use case where you know it's reasonable, you can use a combination of scroll search and bulk updates to achieve the same thing while having full access to the ids. The update by query is just syntactic sugar for the same thing. I'm going to close this as won't fix.
