### ISSUE TITLE
repository-s3 ignores endpoint setting and protocol

### ISSUE THREAD

**Issue by kozmaz87** [elastic/elasticsearch#30995]
**Version: 6.2.4, Build: ccec39f/2018-04-12T20:37:28.497551Z, JVM: 1.8.0_171** (`bin/elasticsearch --version`):

**Plugins installed**: [discovery-ec2, repository-s3, search-guard-6]

**JVM version** (`java -version`): 
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux ip-10-52-6-89 4.4.0-1057-aws #66-Ubuntu SMP Thu May 3 12:49:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
When calling the s3 snapshot functionality over the API as described by documentation: https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3-client.html the endpoint and protocol attributes are largely ignored. The protocol changes but the port remains 443 and the endpoint is just ignored no matter having specified it in the call settings or the keystore. Elasticsearch just goes to a non-regional endpoint. My use case is in a private subnet of an AWS VPC. I can make a gateway to a regional endpoint of S3 but not to s3.amazonaws.com. When I provide the endpoint: s3.eu-west-2.amazonaws.com it gets ignored.

```

{"error":{"root_cause":[{"type":"sdk_client_exception","reason":"sdk_client_exception: Unable to execute HTTP request: Connect to es-snapshot-bucket-name.s3.amazonaws.com:443 [es-snapshot-bucket-name.s3.amazonaws.com/52.216.132.171] failed: connect timed out"}],"type":"repository_exception","reason":"[my_s3_repository] failed to create repository","caused_by":{"type":"sdk_client_exception","reason":"sdk_client_exception: Unable to execute HTTP request: Connect to es-snapshot-bucket-name.s3.amazonaws.com:443 [es-snapshot-bucket-name.s3.amazonaws.com/52.216.132.171] failed: connect timed out","caused_by":{"type":"i_o_exception","reason":"Connect to es-snapshot-bucket-name.s3.amazonaws.com:443 [es-snapshot-bucket-name.s3.amazonaws.com/52.216.132.171] failed: connect timed out","caused_by":{"type":"i_o_exception","reason":"connect timed out"}}}},"status":500}

```
Even though
```
root@ip-10-52-6-89:/usr/share/elasticsearch/bin# netcat -v s3.eu-west-2.amazonaws.com 80
Connection to s3.eu-west-2.amazonaws.com 80 port [tcp/http] succeeded!
^C
root@ip-10-52-6-89:/usr/share/elasticsearch/bin# netcat -v s3.eu-west-2.amazonaws.com 443
Connection to s3.eu-west-2.amazonaws.com 443 port [tcp/https] succeeded!
^C
```
**Steps to reproduce**:
Create private subnet with no generic internet gateway. Create S3 endpoint with VPC endpoints API. 
Try snapshotting ES deployed in these private subnets having defined endpoint to be your regional endpoint you created the gateway for. See it fail.

**Provide logs (if relevant)**:

**Comment by tlrx** [comment]
Note: labeled as bug but it requires a bit of investigation.

**Comment by DaveCTurner** [comment]
It looks like you can connect to the endpoint but not to the bucket itself. Can you confirm that you can interact with this bucket from within your VPC using another client (e.g. the `awscli` command-line tools)? Can you also share a copy of your Elasticsearch configuration?

**Comment by kozmaz87** [comment]
I can talk to the endpoint yes via other tools but ElasticSearch seems to want to go to a non-regional s3 endpoint... which is not what it is supposed to do I think. 

Another thing I noticed that since bucket names can contain dots https validation of S3's wildcard certificate will fail... which is why I tried http as well... to no avail. I shall try to get cli to do an upload for me and will get back to you.

**Comment by DaveCTurner** [comment]
No further feedback received, so I suspect this was a misconfiguration. It's very easy to lock down a VPC too far. I'm closing this, but if it is the case that `aws s3api` works and Elasticsearch does not then please add the information requested above and we'll reopen this.
