### ISSUE TITLE
mktemp issues

### ISSUE THREAD

**Issue by ademariag** [elastic/elasticsearch#30999]
I honestly find pretty poor that you have ignored https://github.com/elastic/elasticsearch/issues/28561 and https://github.com/elastic/elasticsearch/pull/28562 for such a small change, even when a contribution was offered.

The problem is not whether you support alpine or not, but you have a bug in detecting how to use `mktemp`

A compatibility matrix should not prevent you from improving your own product on such a small thing.

@ndegory FYI

**Comment by tlrx** [comment]
@ademariag I can understand your frustration, but I don't find it fair when you say that #28561 and #28562 have been ignored. These issues received the attention of at least 3 Elasticsearch developpers who [commented](https://github.com/elastic/elasticsearch/issues/28561#issuecomment-364040744) and [explained](https://github.com/elastic/elasticsearch/issues/28561#issuecomment-364126503) why we were not willing to merge the change. Also, a workaround has been proposed. This is maybe not what you want, but this is the best option we can offer for now.

As a side note, the size of the change does not really matter: small or large changes can be declined. What is important here is that _we resist making changes to our codebase for OS that we do not support_. We know that from a user point of view it's hard to understand, specially when the change is a one liner. But as maintainers we know that if changes like #28562 are introduced without the right testing infrastructure it will be a pain to maintain and to not break in the future.
