### ISSUE TITLE
Providing a more intuitive alternative for RestFilter/RestFilterChain

### ISSUE THREAD

**Issue by tulumvinh** [elastic/elasticsearch#31038]
Previous to 5.x, RestFilter and RestFilterChain was easy, intuitive to use.  We wrote a plugin which extended/implemented these apis here at Netflix to log all REST requests to our cluster.  These apis have been removed in 5.x (for valid reasons) but there is no complete documentation nor code samples on the replacement.  The current discussion forums, javadocs does not provide a clear picture; rather, there are pieces of information, suggestions that leaves the developer to make educated guesses.

**Comment by tulumvinh** [comment]
@colings86 Hi Collin, in the meantime, could someone comment on this thread (https://discuss.elastic.co/t/restfilters-for-es-5-x/134123) within the Elastic discussion forum?  I have hit blockers on implementing similar feature of RestFilter in our ES 5.x here at Netflix.

Any guidance is appreciated.

**Comment by ebadyano** [comment]
Closing the issue as the javadoc for the alternative ActionPlugin#getRestHandlerWrapper() was updated in https://github.com/elastic/elasticsearch/pull/34376.
