### ISSUE TITLE
DateMathIndexExpressionsIntegrationIT#testIndexNameDateMathExpressions() fails in CI

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#31067]
CI link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=centos/2477/console

Failure:

```
11:46:07 FAILURE 0.50s J1 | DateMathIndexExpressionsIntegrationIT.testIndexNameDateMathExpressions <<< FAILURES!
11:46:07    > Throwable #1: java.lang.AssertionError: 
11:46:07    > Expected: not null
11:46:07    >      but: was null
11:46:07    > 	at __randomizedtesting.SeedInfo.seed([B7B9B064B801973A:3CDA461B4CC8D5A4]:0)
11:46:07    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:46:07    > 	at org.elasticsearch.indices.DateMathIndexExpressionsIntegrationIT.testIndexNameDateMathExpressions(DateMathIndexExpressionsIntegrationIT.java:94)
11:46:07    > 	at java.lang.Thread.run(Thread.java:748)
```

(meaning that the indices stats API did not return an index with the name `.marvel-2018.06.04`).

reproduction line:

```
./gradlew :server:integTest \
  -Dtests.seed=B7B9B064B801973A \
  -Dtests.class=org.elasticsearch.indices.DateMathIndexExpressionsIntegrationIT \
  -Dtests.method="testIndexNameDateMathExpressions" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr \
  -Dtests.timezone=Asia/Dushanbe
```

Does not reproduce locally. This failure has occurred four times within the last year in CI.

**Comment by gmarouli** [comment]
Since there haven't been any recent failures, I will close this issue.

**Comment by masseyke** [comment]
This looks like one that failed because it ran across midnight and made invalid assumptions about the index names. It looks like several of the tests in this class do this, but they all look pretty fast (which is probably why this is so rare).
