### ISSUE TITLE
FullClusterRestartIT#testRecovery() fails in CI

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#31062]
build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+periodic/803/consoleFull

reproduction line:

```
./gradlew :qa:full-cluster-restart:v6.1.5-SNAPSHOT#upgradedClusterTestRunner \
  -Dtests.seed=A360128A15AF807 \
  -Dtests.class=org.elasticsearch.upgrades.FullClusterRestartIT \
  -Dtests.method="testRecovery" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-SV \
  -Dtests.timezone=Indian/Kerguelen
```

failure message:

```
08:33:13 FAILURE 0.13s | FullClusterRestartIT.testRecovery <<< FAILURES!
08:33:14    > Throwable #1: java.lang.AssertionError: mismatch while checking for translog recovery
08:33:14    > testrecovery 0 existing_store done 0
08:33:14    > testrecovery 0 peer           done 0
08:33:14    > testrecovery 1 existing_store done 0
08:33:14    > testrecovery 1 peer           done 0
08:33:14    > testrecovery 2 existing_store done 0
```

**Comment by bleskes** [comment]
@dnhatn do you mind taking a look? Since it's 6.2 - maybe we didn't backport a fix for something?

**Comment by dnhatn** [comment]
@bleskes I will look at this. Log: [testRecovery.txt](https://github.com/elastic/elasticsearch/files/2068259/testRecovery.txt)

**Comment by mayya-sharipova** [comment]
Another instance of this issue: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+default-distro-bwc-tests/37/console

**Comment by dnhatn** [comment]
Last instance's log: [recovery63.txt](https://github.com/elastic/elasticsearch/files/2073979/recovery63.txt)

**Comment by dnhatn** [comment]
Another 6.2 instance: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+bwc-tests/415/consoleText. Looking it now.

**Comment by jbaiera** [comment]
Another 6.2 Instance: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.2+multijob-unix-compatibility/os=centos/555/console

**Comment by bleskes** [comment]
@dnhatn ping.

**Comment by ywelsch** [comment]
Closing this, as we need a recent failure that is not just https://github.com/elastic/elasticsearch/issues/36429

**Comment by przemekwitek** [comment]
It occurred again on 6.8

**Comment by ywelsch** [comment]
@przemekwitek given that you've opened a separate issue, no need to revive this one.
