### ISSUE TITLE
set x-pack user and password 

### ISSUE THREAD

**Issue by AbolfazlDalily** [elastic/elasticsearch#31085]
i run this
Eleatic\elasticsearch-6.2.4\bin\x-pack>setup-passwords auto
command and I got this response : 

Changed password for user kibana
PASSWORD kibana = ********************
Changed password for user logstash_system
PASSWORD logstash_system = **********************
Changed password for user elastic
PASSWORD elastic = ************************ 

now 
how to use elastic  username and password in 
from elasticsearch import Elasticsearch
es = Elasticsearch(
        [{'host':'localhost', 'port':9200}]
    )

Thanks

**Comment by jtibshirani** [comment]
Hi @AbolfazlDalily, thanks for the ticket. This appears to be a question about usage for the elasticsearch python client. These types of questions are better suited to our forums (https://discuss.elastic.co/), as we try to reserve GitHub issues for discussions around development, like bug reports and feature requests.

I'm going to close this issue, but if you find a bug or missing feature after asking your question in the discussion forums, feel free to re-open it or file a new one.
