### ISSUE TITLE
UpdateRequestTests#testUnknownFieldParsing fails reproducibly on 6.x

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#31092]
See for instance this build:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1816/console

@cbuescher It looks related to the change you pushed yesterday?

**Comment by jpountz** [comment]
I just disabled this test.

**Comment by cbuescher** [comment]
The failing test case was accidentally backported to 6.x where we don't throw an error when the parser isn't strict like it is on master. Will delete the whole test like it was before.

**Comment by cbuescher** [comment]
Closed by cad6e2e
