### ISSUE TITLE
Phonetic Plugin for Elasticsearch Cloud

### ISSUE THREAD

**Issue by vishwasPHPDots** [elastic/elasticsearch#31090]
I have deployed cluster on Elasticsearch Cloud . Now , I want to add phonetic search feature.

For that I was putting this setting with php api : 
'settings' => [
					'analysis' => [
						'normalizer' => [
							"lowercase_normalizer" => [
									'type' => 'custom',
									'char_filter' => [],
									'filter' => ['lowercase']
							]
						],
						"filter" => [
							"shingle" => [
								"min_shingle_size" => 2,
								"max_shingle_size" =>  3,
								"type" => "shingle"
							],
							"metaphone" => [
								"type" => "phonetic",
								"encoder" => "metaphone",
								"replace" => false,
							]
						],
						"analyzer" => [
							'suggester' => [
								'type' => "custom",
								'tokenizer' => 'standard',
								'filter' => ["shingle", "lowercase", "my_metaphone"]
							]
						],
			        ]
		]

But I got the error : 
{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[tiebreaker-0000000002][172.17.0.11:19552][indices:admin/create]"}],"type":"illegal_argument_exception","reason":"Unknown filter type [phonetic] for [metaphone]"},"status":400}
 I know we have to install plugin for that, But I don't if I have to install it or not for cloud elasticsearch. And if I have to install it, then how ?

**Comment by tvernum** [comment]
This repository is for tracking bugs and feature request in Elasticsearch. It is not a support forum for Elastic Cloud.
Please ask this question on our [discuss forum](https://discuss.elastic.co/), or raise an issue with [Cloud Support](https://cloud.elastic.co/login)
