### ISSUE TITLE
[ML] Document derivative aggregation use case with partitioning

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#31091]
When creating a custom aggregation for ML, the current [documentation](https://www.elastic.co/guide/en/x-pack/current/ml-configuring-aggregation.html) specifies that it the datafeed aggregation must start with the `buckets` date histogram as the top level aggregation with the terms aggregation as a 2nd level aggregation.

For the use case of doing a top-N aggregation with a derivative as the sub aggregation, we will actually have to create an aggregation with the terms agg being the top level aggregation, i.e.

```
  "aggs": {
    "<terms_agg_name>": {
      "terms": {
        "field": "<field_name>",
        "size": 10
      },
      "aggs": {
        "buckets": {
          "date_histogram": {
            "field": "@timestamp",
            "interval": "5m"
          },
          "aggs": {
            "timestamp": {
              "max": {
                "field": "@timestamp"
              }
            },
            "sum": {
              "sum": {
                "field": "<field>"
              }
            },
            "derivative_sum": {
              "derivative": {
                "buckets_path": [
                  "sum"
                ],
                "gap_policy": "skip"
              }
            }
     ...
     ... so on
```

It will be helpful to update the documentation with this use case and any other use cases where the `buckets` aggregation does not have to be the top level aggregation.

**Comment by davidkyle** [comment]
I've back ported the docs to 6.0 when the change was first introduced.
