### ISSUE TITLE
Request: upgrade Netty.IO to 4.1.25+

### ISSUE THREAD

**Issue by unquietwiki** [elastic/elasticsearch#31124]
Github repo currently has Netty.IO at 4.1.16; the 5.x series has 4.1.13. There appear to be a number of bugfixes that might be helpful for performance reasons. They've also beefed up their HTTP/2 support considerably: which I'm not sure would be useful here, but may be?

http://netty.io/news/2018/05/14/4-1-25-Final.html

**Comment by jasontedor** [comment]
We will leave 5.6 on 4.1.13 barring a bug in Netty that actually impacts us; our focus on that branch is critical fixes only to keep the patch releases stable.

We will upgrade 6.x (in advance of 6.4.0) and master to 4.1.25.Final (#31232) and 6.3.x will remain on 4.1.16.

> They've also beefed up their HTTP/2 support considerably: which I'm not sure would be useful here, but may be?

At this time it would not be.

**Comment by unquietwiki** [comment]
@jasontedor Sounds like a decent set of solutions. Regarding the HTTP/2 situation: its my understanding that ES makes persistent connections between cluster members; that would seem to fall into the scope of using HTTP/2, no?

**Comment by tbrooks8** [comment]
> Regarding the HTTP/2 situation: its my understanding that ES makes persistent connections between cluster members; that would seem to fall into the scope of using HTTP/2, no?

Nodes do open persistent connections, however they do not communicate using HTTP. 

HTTP/2 would be relevant for http clients communicating with Elasticsearch nodes. However, we have not implemented it and the Netty HTTP/2 work is still marked as an unstable API.

**Comment by unquietwiki** [comment]
@tbrooks8 @jasontedor (nods) Thanks for the clarification.

**Comment by jasontedor** [comment]
We ultimately reverted this: #31282. See also netty/netty#8017. I think we can keep this issue closed, we are not going to upgrade in the foreseeable future, and will upgrade after we resolve netty/netty#8017 with the Netty maintainers.

**Comment by jasontedor** [comment]
We think we will have #32511 now that the Netty maintainers addressed netty/netty#8017 for us.
