### ISSUE TITLE
Rest Client: ElasticsearchHostsSniffer not only remains data nodes as TransportClient

### ISSUE THREAD

**Issue by zhaojianyong** [elastic/elasticsearch#31138]
https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html
Keep in mind that the list might possibly not include the original node it connected to if that node is not a data node. If, for instance, you initially connect to a master node, after sniffing, no further requests will go to that master node, but rather to any data nodes instead. The reason the transport client excludes non-data nodes is to avoid sending search traffic to master only nodes.

But it seems that ElasticsearchHostsSniffer of Rest Client does no filter and returns all nodes. 
Why is the action of sniffer in Rest Client different from Transport Client?

**Comment by jimczi** [comment]
There's no logic in the rest client to do that automatically but we're adding a way to support host selection [here](https://github.com/elastic/elasticsearch/pull/30523) with a simple way to exclude master nodes for instance. You can follow the discussion  in the original [issue](https://github.com/elastic/elasticsearch/issues/21888) so I am going to close this one as duplicate.
