### ISSUE TITLE
[ML] Delete forecast API

### ISSUE THREAD

**Issue by sophiec20** [elastic/elasticsearch#31134]
Forecasts are currently deleted when:
- the job is deleted 
- or, as part of midnight maintenance if the `expires_in` value is exceeded (14d default)

The possibility to delete a single forecast would enhance usability of the forecasting feature.

This could be useful in some scenarios, for example if a typo in the forecasting time range happened like 100d instaed of 10d.

Follow on UI changes - https://github.com/elastic/kibana/issues/18511

**Comment by droberts195** [comment]
Closed by #31134.
