### ISSUE TITLE
Make BackOffPolicy serializable (feature request)

### ISSUE THREAD

**Issue by jsteggink** [elastic/elasticsearch#31130]
Hi,

It would be great if you could make org.elasticsearch.action.bulk.BackOffPolicy serializable.

Regards,
Jeroen

**Comment by jimczi** [comment]
Can you describe some reasons why ? Doesn't sound like something we need internally nor externally.

**Comment by jsteggink** [comment]
I'm working on a new Elasticsearch input/output component for Apache Beam which supports ES 6.x. In order to distribute a configuration to other servers, Apache Beam serializes configuration objects. As BackOffPolicy is not serializable I have to implement a workaround in order to serialize the configuration. This means I have to make a custom interface to translate the BackOffPolicy back and forth. The code  would be more maintainable if it's serializable.

See the following links for more information:
https://issues.apache.org/jira/projects/BEAM/issues/BEAM-3199?filter=allopenissues
https://github.com/jsteggink/beam/blob/BEAM-3199/sdks/java/io/elasticsearch-6/src/main/java/org/apache/beam/sdk/io/elasticsearch/ElasticsearchIO.java#L743

**Comment by jimczi** [comment]
> The code would be more maintainable if it's serializable.

I disagree, you'd need to handle backward compatibility, and we'd be forced to refrain adding options to the existing backoff policy because it could break the serialization. 
I think you should manage the BackOffPolicy that you accept in BEAM, with a BEAMBackOffPolicyBuilder for instance, and map the BEAM configuration to a real BackOffPolicy. 
BackOffPolicy is not a builder so there is no good reason to provide serialization here.

**Comment by jsteggink** [comment]
I agree in the case where you would have no control over the version of BackOffPolicy or can expect old serialized versions of it. But we do have control. Though I understand your point of view. The way it's built now it indeed makes less sense. Looking at how Spring Retry implemented a BackOffPolicy they do allow serialization. I just thought it was worth the discussion.

**Comment by jimczi** [comment]
Thanks for understanding, I am going to close this issue. If you have control of everything then it's easier to maintain serialization on your side.
