### ISSUE TITLE
Simple query text field with spaces and * issues after upgrade

### ISSUE THREAD

**Issue by rondelward** [elastic/elasticsearch#31150]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.4

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_171

**OS version** (`uname -a` if on a Unix-like system): Windows sever 2012 R2

**Description of the problem including expected versus actual behavior**:

The simple query string command does not return expected results when the query contains a space and a wildcard e.g ( "Test *"). The same query format works in version 5.6.8 and was noticed after an upgrade. 

**Steps to reproduce**:

Here are the steps (using Kibana) to set up an index to reproduce the issue 

```
PUT test_query
{
  "mappings": {
    "test_type": {
      "_source": {
        "enabled": true
      },
      "properties": {
          "my_field": {
            "type": "text",
            "analyzer": "standard"
          }
        }
    }
  }
}
POST /test_query/test_type
{
  "my_field": "Test Value Here"
}
POST /test_query/test_type
{
  "my_field": "Testing different"
}
POST test_query/_refresh
GET test_query/_search
{
  "query": {
    "simple_query_string": {
      "fields": [
        "my_field"
      ],
      "query": "Test*",
      "default_operator": "and"
    }
  }
}
GET test_query/_search
{
  "query": {
    "simple_query_string": {
      "fields": [
        "my_field"
      ],
      "query": "Test *",
      "default_operator": "and"
    }
  }
}
```

The query "Test*" returns the document as expected. However "Test *" does not work in version 6.2.4. In version 5.6.8, both queries return results as expected using the same standard analyzer for the field. 

Expected 1 hit, actually received 0 hits.

Was there an intentional change made that would impact this query in version 6.X?

**Comment by jimczi** [comment]
This issue is already fixed for the next minor release 6.3.0: https://github.com/elastic/elasticsearch/pull/28871
Thanks for reporting @rondelward .

**Comment by rondelward** [comment]
Thanks for the quick reply @jimczi. Is there a planned release date for the 6.3.0 build?

**Comment by jpountz** [comment]
We don't communicate around release dates, but we would like to release 6.3.0 "soon".
