### ISSUE TITLE
Delete Generated Reports Feature Request

### ISSUE THREAD

**Issue by kaushikbbr** [elastic/elasticsearch#31157]
**_Delete Option for Generated Reports_**

- In the Reporting tab of Management option of Kibana, we can see all the reports generated.
- Under the actions column there is no any button to delete the generated report.
- Please add it, as some times we may have generated multiple reports for the same data which is redundant.
**_- Also an action to rename the file would be an awesome feature_**

![image](https://user-images.githubusercontent.com/38374696/41065209-80decc70-69fb-11e8-9ba3-6febbf70b009.png)

**Comment by dnhatn** [comment]
@kaushikbbr Would you please open it in [kibana repository](https://github.com/elastic/kibana) instead? Thanks!
