### ISSUE TITLE
testReadNonExistingPath fails in S3BlobStoreContainerTests

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#31166]
This fails in `6.x`

`testReadNonExistingPath` was introduced in https://github.com/elastic/elasticsearch/pull/31126.
Failures: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1834/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1835/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1836/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/1838/console

 I've muted the test in 6.x for now

**Comment by ywelsch** [comment]
Thanks @jkakavas. I've pushed a fix and reenabled the test. This was caused by another PR with improvements not being backported to 6.x.
