### ISSUE TITLE
RestHighLevelClient - Default Index and Type should be supported in BulkRequest

### ISSUE THREAD

**Issue by koalalam** [elastic/elasticsearch#31168]
When calling bulk/bulkAsync function in RestHighLevelClient, the parameter BulkRequest doesn't support default index and type which is supported in the Bulk API:

https://www.elastic.co/guide/en/elasticsearch/reference/6.2/docs-bulk.html

"The endpoints are /_bulk, /{index}/_bulk, and {index}/{type}/_bulk. When the index or the index/type are provided, they will be used by default on bulk items that don’t provide them explicitly."

However, when BulkRequest is converted to Request object, only "/_bulk" is used.

**Elasticsearch version** (`bin/elasticsearch --version`): 6.x

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Linux

**Comment by javanna** [comment]
This is the same problem as described in #26026 . Closing in favour of the existing issue.
