### ISSUE TITLE
Elasticsearch stuck after delete index request

### ISSUE THREAD

**Issue by alexz00** [elastic/elasticsearch#31181]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.9

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_91

**OS version** (`uname -a` if on a Unix-like system): Linux/3.10.0-327.el7.x86_64/amd64

**Description of the problem including expected versus actual behavior**: Elasticsearch fails to process an index delete request and this yield to a stuckness situation: the delete-index task is queued but never processed and any other task is not processed since it is blocked by the first one.

**Steps to reproduce**:
We are running an Elasticsearch instance in single node mode. It happens (randomly) that some index delete request (we are using the HTTP REST API) fails to be processed correctly, and an index-delete task is queued: we see it from the pending_tasks API.

The task is never processed, and it prevents any other task (e.g. index creation) to be executed.

The only way we found to restore normal functionality is to restart the Elasticsearch process.

The behavior we would expect is the delete request either to be successfully processed or to fail, but not to be queued forever. At least after some time we would expect the task to be removed from the queue and the subsequent tasks to be eventually processed.

Note that this happens when Elasticsearch is 'at rest': it is not performing any other action, there is no incoming data and no search request running.

Can you please provide some help in understanding the issue?

Thanks. Regards.

**Comment by bleskes** [comment]
@alexz00 do you mind sharing your pending tasks lists when that happens (json format please, it has more info). Can you also share hot threads on the master nodes - I'm curios to see what the thread called `clusterService#updateTask` is doing.  See [here](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/cluster-nodes-hot-threads.html) for documentation. You might need to tweak parameters to get it to show. Last if you have anything in the logs you think is relevant, please share.

**Comment by jasontedor** [comment]
> Can you also share hot threads on the master nodes - I'm curios to see what the thread called `clusterService#updateTask` is doing.  See [here](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/cluster-nodes-hot-threads.html) for documentation. You might need to tweak parameters to get it to show.

In this case I think that `jstack` would be better if the JDK is installed.

**Comment by alexz00** [comment]
Unfortunately the Elasticsearch instance that caused this problem is deployed at a customer, and I've not direct access to it. We have a basic monitoring infrastructure that collects periodically information, this is what I can provide you at the moment:

> Elasticsearch {INFO} Action {Dumping pending task data} InsertOrder {1877} Priority {URGENT} Source {delete-index [[myindexa-2018.05.31/ISUt985ZQuizk86hpki5gA]]} TimeInQueue {1480984}
Elasticsearch {INFO} Action {Dumping pending task data} InsertOrder {1878} Priority {URGENT} Source {delete-index [[myindexb-2018.05.31/L2RVa98xRa2NvteS_oT1EQ]]} TimeInQueue {880359}
Elasticsearch {INFO} Action {Dumping pending task data} InsertOrder {1879} Priority {URGENT} Source {delete-index [[myindexc-2018.05.31/Kswk6DGXRMSB4bs_ON7_DA]]} TimeInQueue {279731}
Elasticsearch {INFO} Action {Hot Threads} HotThreadsDump {::: {MYAPP}{fZ_dw6hbQtqZ705pzah14Q}{2XQyjxFRTseILjucudDOQw}{10.202.101.247}{10.202.101.247:9300}
   Hot threads at 2018-06-07T04:24:55.840Z, interval=500ms, busiestThreads=3, ignoreIdleThreads=true:
}

That is, a dump of the pending tasks and the hot threads in the applicative logs.

**Comment by alexz00** [comment]
We had a similar issue while indexing some data. Brief description of the scenario:
- Data were pushed by Logstash
- We tried to index ~700k events (3.5GB of disk space for ES indices)
- The index requests triggered the creation of ~50 different indices, 5 shards per index
- We are running our tests on an AWS EC2 M4 4xlarge instance (16cores, 64GB, EBS volumes). Elasticsearch heap size is 16GB.

After some minutes after we started the process, ES stopped to index data and to create new indices. We started to see errors like the following:

> ... [o.e.i.IndexingMemoryController] ... now throttling indexing for shard [[indexname][4]]: segment writing can't keep up
> ... [o.e.i.IndexingMemoryController] ... stop throttling indexing for shard [[indexname][1]]

Then Elasticsearch began to queue pending tasks without processing them.

We had to restart Elasticsearch to have the process completed with success.
I understand that we pushed a lot of data in a short time frame, and therefore it is absolutely reasonable to have a slowdown of the indexing process.
But what we see is that after the congestion situation, Elasticsearch became stuck, and it is never able to recover, while our expectation is that, after some time, it should recover and complete the indexing of all the documents.
I think it worth noting that after ES started queueing the tasks, it's CPU consumption was very low.

I attach the following:
- A thread dump generated with jstack
- The output of the hot threads, pending tasks and node stats ES APIs.

Can someone help us in understanding what is happening and if/how is possible to address these situations (we'd like to avoid to restart Elasticsearch every time...)

Let me know if you need some additional information.
Thank you very much.

[nodes_stats.txt](https://github.com/elastic/elasticsearch/files/2119669/nodes_stats.txt)
[jstack.log](https://github.com/elastic/elasticsearch/files/2119667/jstack.log)
[hot_threads.log](https://github.com/elastic/elasticsearch/files/2119668/hot_threads.log)
[pending_tasks.log](https://github.com/elastic/elasticsearch/files/2119671/pending_tasks.log)

**Comment by ywelsch** [comment]
Based on the hot_threads output (see below), it looks like your node is stuck on logging output, which is causing the cluster state thread to hang (occurrence 1 below) and indexing to be forever throttled (occurrence 2 below). Can you provide your logging configuration?

```
0.0% (14.9micros out of 500ms) cpu usage by thread 'elasticsearch[MYNODE][clusterService#updateTask][T#1]'
     10/10 snapshots sharing following 41 elements
       org.apache.logging.log4j.core.appender.OutputStreamManager.writeBytes(OutputStreamManager.java:360)
       org.apache.logging.log4j.core.layout.TextEncoderHelper.writeEncodedText(TextEncoderHelper.java:96)
       org.apache.logging.log4j.core.layout.TextEncoderHelper.encodeText(TextEncoderHelper.java:65)
       org.apache.logging.log4j.core.layout.StringBuilderEncoder.encode(StringBuilderEncoder.java:68)
       org.apache.logging.log4j.core.layout.StringBuilderEncoder.encode(StringBuilderEncoder.java:32)
       org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:219)
       org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:57)
       org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:177)
       org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170)
       org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161)
       org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
       org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
       org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
       org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
       org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
       org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
       org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
       org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
       org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
       org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
       org.apache.logging.log4j.spi.ExtendedLoggerWrapper.logMessage(ExtendedLoggerWrapper.java:217)
       org.elasticsearch.common.logging.PrefixLogger.logMessage(PrefixLogger.java:102)
       org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2116)
       org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2100)
       org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2048)
       org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1931)
       org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1460)
       org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$1.execute(MetaDataCreateIndexService.java:454)
       org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
       org.elasticsearch.cluster.service.ClusterService.executeTasks(ClusterService.java:634)
       org.elasticsearch.cluster.service.ClusterService.calculateTaskOutputs(ClusterService.java:612)
       org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:571)
       org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.run(ClusterService.java:263)
       org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150)
       org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188)
       org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:575)
       org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247)
       org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       java.lang.Thread.run(Thread.java:748)
```

```
0.0% (0s out of 500ms) cpu usage by thread 'elasticsearch[MYNODE][scheduler][T#1]'
     10/10 snapshots sharing following 40 elements
       java.io.FileOutputStream.writeBytes(Native Method)
       java.io.FileOutputStream.write(FileOutputStream.java:326)
       java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
       java.io.PrintStream.write(PrintStream.java:480)
       org.apache.logging.log4j.core.util.CloseShieldOutputStream.write(CloseShieldOutputStream.java:53)
       org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:262)
       org.apache.logging.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:294)
       org.apache.logging.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:303)
       org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:179)
       org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170)
       org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161)
       org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
       org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
       org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
       org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
       org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
       org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
       org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
       org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
       org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
       org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
       org.apache.logging.log4j.spi.ExtendedLoggerWrapper.logMessage(ExtendedLoggerWrapper.java:217)
       org.elasticsearch.common.logging.PrefixLogger.logMessage(PrefixLogger.java:102)
       org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2116)
       org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2100)
       org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2011)
       org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1882)
       org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1427)
       org.elasticsearch.indices.IndexingMemoryController$ShardsIndicesStatusChecker.runUnlocked(IndexingMemoryController.java:373)
       org.elasticsearch.indices.IndexingMemoryController$ShardsIndicesStatusChecker.run(IndexingMemoryController.java:277)
       org.elasticsearch.threadpool.ThreadPool$ReschedulingRunnable.doRun(ThreadPool.java:811)
       org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
       org.elasticsearch.threadpool.ThreadPool$LoggingRunnable.run(ThreadPool.java:436)
       java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
       java.util.concurrent.FutureTask.run(FutureTask.java:266)
       java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
       java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
       java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       java.lang.Thread.run(Thread.java:748)
```

**Comment by alexz00** [comment]
Yes, of course.
I'll attach the log4j2.properties.

Thanks.

[log4j2.zip](https://github.com/elastic/elasticsearch/files/2123271/log4j2.zip)

**Comment by alexz00** [comment]
The environment is a bit non standard, indeed.
My environment is running inside Docker, and I'm logging on a volume mounted in the container from the EBS volume.

**Comment by ywelsch** [comment]
Something is blocking the writes to the log files on the EBS volume, which in turn blocks the logger, which in turn hangs important threads in ES, which results in the stuckness that you're seeing. There's nothing we can do here on the ES side of things. As such, I'm closing this issue.
