### ISSUE TITLE
Proposal to remove Debian 8 from Packaging Tests and CI

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#31193]
Debian 8.0 became [EOL on June 6th 2018](https://wiki.debian.org/DebianReleases).

While there's still LTS support until June 6th 2020, [LTS means](https://wiki.debian.org/LTS):

> Debian LTS will not be handled by the Debian security team, but by a separate group of volunteers and companies interested in making it a success.

Given the above points, I am raising this issue to discuss whether it makes sense to remove Debian 8 from the:

1. [Vagrantfile](https://github.com/elastic/elasticsearch/blob/07a57cc1310f04ee0544b9222e737897e9e3ff99/Vagrantfile#L64-L68)
2. CI
3. Support Matrix

starting with 6.3 or some newer version.

**Comment by jasontedor** [comment]
We can not remove this from the support matrix from any 6.x version. Whether or not we can remove this from master requires some internal discussion.

**Comment by pcsanwald** [comment]
Removing discuss as @eskibars has agreed to take the ball on this.

**Comment by rjernst** [comment]
Debian 8 was removed from packaging tests and CI for 8.0.
