### ISSUE TITLE
Reproduction info for failing tess for "multi run" style tests is incorrect

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#31205]
Right now if a test fails in the "rolling restart" or "full cluster restart" test cases then the reproduction information isn't quite right because it prints out the task task for the last test run. This won't reproduce the issue because the tests from previous runs are usually required to create the state used in that test run.

**Comment by atorok** [comment]
Bwc tests use testclusters now, so all the cluster management is  no longer done with tasks. The test tasks have a `dependsOn` so a reproduction line will go trough all the previous tasks, run the upgrades etc. then when it gets to the failing task will only run that single test from there. It will take more time, but it will work.
