### ISSUE TITLE
Documentation specifies wrong Java version.

### ISSUE THREAD

**Issue by seangarita** [elastic/elasticsearch#31219]
The documentation states:
![image](https://user-images.githubusercontent.com/1189338/41181877-0e4a6928-6b39-11e8-8ac3-d1988e5adadf.png)
"Elasticsearch requires Java 8 or later."

Elasticsearch does not work with Java 9. Please let's update the documentation so that developers don't have to discover this by trial and error.

Perhaps something like: "Elasticsearch requires Java 8".

**Comment by damienalexandre** [comment]
Elasticsearch 6.2 support Java 9, so I suppose it depends which version you are looking at in the documentation.

There is also a great support matrix here: https://www.elastic.co/support/matrix#matrix_jvm

**Comment by nik9000** [comment]
The minimum runtime version of Elasticsearch 6.x is Java 8:
https://github.com/elastic/elasticsearch/blob/6.x/buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy#L61

**Comment by jasontedor** [comment]
This sentence appears in earlier versions of the docs. We should fix this to reflect that prior to 6.2 we only supported JDK 8.

**Comment by nik9000** [comment]
> We should fix this to reflect that prior to 6.2 we only supported JDK 8.

Sure

**Comment by nik9000** [comment]
Closed by merging ce4a80c to 6.2 and its backports to 6.1, 6.0, and 5.6.

**Comment by jasontedor** [comment]
Looks good, thanks @nik9000.
