### ISSUE TITLE
Should we add WatchBackwardsCompatibilityIT to master?

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#31216]
In 6.x we have [WatchBackwardsCompatibilityIT](https://github.com/elastic/elasticsearch/blob/6.x/x-pack/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/WatchBackwardsCompatibilityIT.java) but master doesn't have this. It *looks* like a thing that we want though. I mean the big changes to watcher were in 6.0 but still, we could probably use some basic tests for it on upgrade to 7.0. Should we drag this file forward?

**Comment by colings86** [comment]
@spinscale IS a test like this needed in master or do we have other tests now what cover these backwards compatibility areas?

**Comment by jasontedor** [comment]
We agreed that we should have BWC tests for Watcher (and, in general, all X-Pack functionality).
