### ISSUE TITLE
Customized per field doc-value

### ISSUE THREAD

**Issue by ybtsdst** [elastic/elasticsearch#31225]
Hi guys,

I'm looking for a way to add a customized doc-value format in plugin. 

Current the Codec instance is created by SPI loader and passed to IndexWriter from CodecService. The default Codec uses PerFieldDocValuesFormat to return default doc-value format. 

My questions: 

1. How to get my customized doc-value from codec for specific fields? It seems I have to add a new Codec, but the new Codec is not aware of mappings. 
2. If I want to have some per field settings, how to pass the settings to Codec or doc-value format?

**Comment by jpountz** [comment]
Indeed, PerFieldMappingPostingFormatCodec has access to mappings to use a different postings format for completion fields (it seems like you want to do the same for doc-values), but we do not offer ways to do the same thing from plugins.

We used to have ways to configure postings formats and doc-value formats from mappings, but it was very expert and we ended up removing this feature.

I'm not sure I would like to add such a feature back, but it shouldn't be too hard to do it with a custom build.

**Comment by ybtsdst** [comment]
Thanks @jpountz 
l
I find that in es old versions, each field mapping has a 'doc_values_format' settings and later was removed. Is there any traps about why removing this feature?

Besides, the SPI mechanism allows loading codec simply from classpath, but es seems not supporting this feature. Current the customized codec/doc-value/posting format is hard coded in PerFieldMappingPostingFormatCodec class. I really don't want to add my format into core module(may import some third-party dependencies)

**Comment by jpountz** [comment]
Trapiness was not the concern, it was more backward compatibility: Lucene only guarantees backward compatibility for the default codec. If you start using a custom codecs or custom index formats, then either it's your own and you need to maintain it (I suspect there was at most a handful of users in that case), or you are using one of Lucene's experimental formats and then you need to be ready to reindex for each upgrade (even for a minor). In either case, this is something that very few users would choose to do so this feature was not worth maintaining.

**Comment by ybtsdst** [comment]
Thanks @jpountz 

If backward compatibility is the only concern, will customizing codec be provided as an expert usage? May be some undocumented settings; the option is off by default.

In my scenario, I will maintain and upgrade the codec as needed. So I'm hoping there is a way which users can add their own formats in plugins.

Another questions is about passing configurations on field(or index settings) to lower formats. I find that default codec has some params which can be tuned in a more fine-grained way(e.g. chunkSize/maxDocsPerChunk/blockSize versus BEST_SPEED/BEST_COMPRESSION). In Lucene, it seems unable to change these low-level params. Why don't expose these low-level params to user? It might help for some optimizing cases. 

May be I got a wrong direction for optimizing es performance :)

**Comment by jpountz** [comment]
Lucene doesn't expose these settings on purpose because it wants to make sure that all values that an option may take are tested. This is why the only supported option for now is the BEST_SPEED vs BEST_COMPRESSION option, which for now only applies to stored fields.

Why do you need a custom codec? What happened in the past is that when a different codec or format proved useful, we tried to think about whether its benefits could be brought to the default codec. For instance there initially was a postings format that was specialized for primary keys, which we replaced in favor of better support for primary keys in the custom codec by inlining postings into the terms dictionary when docFreq==1 and indexOptions==DOCS to save one seek.

**Comment by jpountz** [comment]
Discussed in FixitFriday: it's unlikely we will add this level of configuration again, but we would like to learn more about the use-case, maybe there are other ways that we could support it.

**Comment by javanna** [comment]
hi @ybtsdst could you add some info on your usecase like Adrien asked above?

**Comment by ybtsdst** [comment]
Thanks @jpountz 

Sorry for delaying to reply this issue, I have some other things to handle.

For current spatial index structure(geohash/quadtree), if the Geometry is complex such as linestrings and polygons, indexing speed is really slow.
I have some spatial data, and I want to have a trial on some other index structures. I store the spatial Geometry object as doc-value, and try to implement a specific codec based on current doc-value format.

Current I find the PerFieldMappingPostingFormatCodec class is able to support my scenario by overiding the getDocValuesFormatForField() method.

**Comment by jpountz** [comment]
@ybtsdst Thanks for the details. I don't think we will want to introduce more complexity in our codebase for such an expert use-case, so I am going to close this issue. Sorry about that. We would be open to discuss it again however if your experiments prove to provide significant gains for geo indexing and search.

You might be interested to follow some geo developments in Lucene that are moving the indexing of geo-shape from geohashes or quadtrees in an inverted index to a triangular mesh indexed in an R-tree-like structure: https://issues.apache.org/jira/browse/LUCENE-8396. We haven't performed comprehensive benchmarking yet but we are hopeful that it will help indexing and search speed.
