### ISSUE TITLE
Make Translog an implementation detail of an Engine instead of required

### ISSUE THREAD

**Issue by dakrone** [elastic/elasticsearch#31248]
This is a followup to https://github.com/elastic/elasticsearch/pull/31220#discussion_r194303773 where it would be nice if we could make the abstract `Engine` class not expose information that made it seem like it has a Translog. This would include functions with `Translog` in the name, as well as perhaps using return values that aren't sub classes of `Translog`.

It would be nice if an engine consumer could use an engine without having to know about translog implementation details (or without the presence of a translog, if desired).

**Comment by dakrone** [comment]
Here's an initial list that would need renaming:

- `isTranslogSyncNeeded` -> `isSyncNeeded`
- `syncTranslog` -> `sync`
- `ensureTranslogSynced` -> `ensureSynced`
- `acquireTranslogRetentionLock` -> `acquireRetentionLock`
- `newTranslogSnapshotFromMinSeqNo` -> `newSnapshotFromMinSeqNo`
- `estimateTranslogOperationsFromMinSeq` -> `estimateOperationsFromMinSeq`
- `getTranslogStats` -> `getStats`
- `getTranslogLastWriteLocation` -> `getLastWriteLocation`

Additionally, if we wanted to do this we'd have to have generic return values and eschew our use of `Translog.Snapshot` and `Translog.Location`

**Comment by jasontedor** [comment]
I don't think this issue should be about renaming these methods but rather removing their need to be on the `Engine` public API? These methods simply do not make sense without `translog` in the name if they are doing something to the translog.

**Comment by dakrone** [comment]
I agree, we don't have to keep all the methods, I editing the comment to say "renaming, removing, or reorganizing"

**Comment by ywelsch** [comment]
@dakrone Can this be closed now with #31220 merged?

**Comment by dakrone** [comment]
I think this can be closed now.
