### ISSUE TITLE
Why ES index name can not be upper letters?

### ISSUE THREAD

**Issue by springCkWyy** [elastic/elasticsearch#31262]
when I create a new index with upper letters, i shows “"error"=>{"type"=>"invalid_index_name_exception", "reason"=>"Invalid index name [test0612FX_FXlogFlow0612_2018.06.12], must be lowercase",”

**Comment by jasontedor** [comment]
This is ancient history. In prior versions, Elasticsearch used the name of the index as the name of a directory on disk. Some filesystems are case insensitive which meant that `foo` and `FOO` should be different indices yet could collide on disk. That’s bad so we forbid it. We no longer use the name of the index on disk so this limitation could be lifted. Yet, we think this limitation should remain. Having two indices whose name differ in case only is an anti-pattern and can be trappy (if a user searches `foo` but meant `Foo` that leads to hard to diagnose bugs). We have no intent of lifting this limitation.

In the future please follow our contributing guidelines which point out that this repository is for verified bugs and feature requests only. For questions like you have here, please use the [forum](https://discuss.elastic.co).
