### ISSUE TITLE
Read-only/audit mode

### ISSUE THREAD

**Issue by jumpingfella** [elastic/elasticsearch#31278]
Hello,

I'm looking into configuration of elasticsearch, where it allows write only from certain application (graylog) and new entries are becoming non-modifiable (checksums chain, similar to how blockchain does it).
So far, I was able to find the following plugin: https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin
But it doesn't really provide "audit" mode. 

Would appreciate if you shed some light on this. If it's possible with current version of elasticsearch, or may be it's in the roadmap for the next version.

Thanks, Stepan.

**Comment by eskibars** [comment]
Hi @jumpingfella.  Thanks for asking the question!  Elastic -- the company behind Elasticsearch -- produces a [security component](https://www.elastic.co/products/x-pack/security) which allows role based access control.  You can use it to set read-only access for some users in exactly the fashion you describe.  We supply that functionality through a [subscription](https://www.elastic.co/subscriptions) or [our official cloud offering](https://www.elastic.co/cloud/elasticsearch-service).  If you'd like to learn more about our on-prem subscription offerings, you can let us know and ask any questions on the [subscriptions page](https://www.elastic.co/subscriptions) (look for "Want to Learn More? We Love a Good Query" on the page).
