### ISSUE TITLE
ES version : 5.1.2 - Retained heap is keep on increasing - causing more GCs after some time - increasing CPU spike

### ISSUE THREAD

**Issue by srikhark** [elastic/elasticsearch#31292]
ES version : 5.1.2 - Retained heap is keep on increasing - causing more GCs after some time - increasing CPU spike

![1](https://user-images.githubusercontent.com/22318500/41345741-20721b04-6f22-11e8-9302-a979bf717479.png)
![2](https://user-images.githubusercontent.com/22318500/41345758-26a1e9d2-6f22-11e8-8485-ae4b8f171796.png)

Any idea, why it is keep on increasing its retained heap space ?
Are there any memory leak issues with this version ??

**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
