### ISSUE TITLE
elasticsearch-oss can not be installed via apt

### ISSUE THREAD

**Issue by ymc-dabe** [elastic/elasticsearch#31317]
**Elasticsearch version**: `Desired 6.3.0, but not installable as flavor 'oss'`

**Plugins installed**: `none`

**JVM version**: `not relevant`

**OS version**: `Debian 9.4 "Stretch" (amd64)`

**Description of the problem including expected versus actual behavior**:
The package `elasticsearch-oss` can not be installed via apt, since it is not listed in the package list:
```
# curl -s https://artifacts.elastic.co/packages/6.x/apt/dists/stable/main/binary-amd64/Packages | grep Package: | sort -u
Package: apm-server
Package: auditbeat
Package: elasticsearch
Package: filebeat
Package: heartbeat-elastic
Package: kibana
Package: kibana-oss
Package: logstash
Package: metricbeat
Package: packetbeat

# curl -s https://artifacts.elastic.co/packages/6.x/apt/dists/stable/main/binary-i386/Packages | grep Package: | sort -u
Package: apm-server
Package: auditbeat
Package: elasticsearch
Package: filebeat
Package: heartbeat-elastic
Package: logstash
Package: metricbeat
Package: packetbeat
```

Note that the package already exists inside the pool:
```
#curl --head https://artifacts.elastic.co/packages/6.x/apt/pool/main/e/elasticsearch/elasticsearch-6.3.0.deb
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 91359636
Content-Type: application/octet-stream
Date: Thu, 14 Jun 2018 06:08:15 GMT
ETag: "edd5e29cd9db9b8efcbf93c644a62a15-18"
Last-Modified: Wed, 13 Jun 2018 14:58:38 GMT
Server: nginx/1.4.6 (Ubuntu)
(...)
Connection: keep-alive
```

* Actual behavior:
  Trying to install `elasticsearch-oss` is not possible using apt:
  ```
  # sudo apt-get install elasticsearch-oss
  Reading package lists... Done
  Building dependency tree       
  Reading state information... Done
  Package elasticsearch-oss is not available, but is referred to by another package.
  This may mean that the package is missing, has been obsoleted, or
  is only available from another source
  
  E: Package 'elasticsearch-oss' has no installation candidate
  ```

* Expected behavior:
  `sudo apt-get install elasticsearch-oss` installs elasticsearch (flavor 'oss')

**Steps to reproduce**:
Follow the ["Install Elasticsearch with Debian Package"](https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html) instructions, but instead of installing `elasticsearch`, try to install `elasticsearch-oss`:
```
sudo apt-get update && sudo apt-get install elasticsearch-oss
```

**Comment by rjernst** [comment]
The oss packages are in a different repository (`oss-6.x`):
``
➜  curl -s https://artifacts.elastic.co/packages/oss-6.x/apt/dists/stable/main/binary-amd64/Packages | grep Package: | sort -u
Package: apm-server-oss
Package: auditbeat-oss
Package: elasticsearch-oss
Package: filebeat-oss
Package: heartbeat-elastic-oss
Package: logstash
Package: metricbeat-oss
Package: packetbeat-oss
```

This does need to be updated in packaging docs, though.

**Comment by Conky5** [comment]
@rjernst this was noticed again today, should a new ticket get created to track updating the docs?

**Comment by rjernst** [comment]
@Conky5 I think a new issue should be created. This should be closed as it is not an issue with the repository, just making the docs clear.

@ymc-dabe I'm going to close this issue as the oss binaries are available in a different repository as noted in my previous post.
