### ISSUE TITLE
`es_release_notes` should check the `backport_pending` label

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#31310]
In the same way that it checks whether a PR that has the appropriate label is still open, es_release_notes should verify that a PR doesn't have the `backport_pending` label set. This should not happen (as the PR should be labelled X.Y.Z+1 in that case) but adding this check would be an extra safety to avoid creating wrong release notes.

**Comment by mark-vieira** [comment]
Closing this in favor of #62481.
