### ISSUE TITLE
FollowingEngine shouldn't fill history gaps upon promotion and recovery

### ISSUE THREAD

**Issue by bleskes** [elastic/elasticsearch#31318]
The following engine doesn't own the history but rather follows a remote one. As such, it can not close gaps on its own. 

/cc @martijnvg @jasontedor

**Comment by martijnvg** [comment]
Gaps are closed in: `Engine#fillSeqNoGaps(...)`

I talked about this with @bleskes and he said the easiest way to achieve this is by making the `fillSeqNoGaps(...)` method a noop in the `FollowingEngine` implementation. Besides the unit test on the engine level, it would be good to have a test that simulates the need for this.

**Comment by martijnvg** [comment]
Implemented via #31751
