### ISSUE TITLE
ASM incompatibility between SQL/Painless and FeatureAwareCheck

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#31322]
The X-Pack FeatureAwareCheck (#31081) requires ASM 6 (in order to parse recent class file formats).
Painless uses ASM 5, and SQL is now dependent on painless (#30681).

That means that when the feature aware check runs for SQL it has both versions of asm on the commandline and  asm 5 gets used which fails to read the JRE's classes.

I pushed 89a24698b1e60abc0d5021a02bbc4bc411fdc59c to work around it and get the build running again, but I think a better fix is in order.

**Comment by tvernum** [comment]
I think this is only a problem on Java 10 (and maybe 9 as well, but not 8)
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java10,nodes=virtual&&linux/113/console

**Comment by costin** [comment]
Fixed by https://github.com/elastic/elasticsearch/commit/f7a0cafe557275cf1d3b6f87209f9c41ecb39b8d and https://github.com/elastic/elasticsearch/commit/83053321242006c1fd6b652be041e7a0690f5231
