### ISSUE TITLE
analyze_wildcard is ignored when using synonym_graph filter

### ISSUE THREAD

**Issue by weberhofer** [elastic/elasticsearch#31335]
**Elasticsearch version** 6.3.0 (and before)

**Plugins installed**: none

**JVM version**: openjdk version "1.8.0_161"

**OS version**: openSUSE Leap 42.3

**Description of the problem including expected versus actual behavior**:

To search in within a text-field I'm using a QueryStringQuery with the following parameters:
```json
{
  "analyze_wildcard": true,
  "auto_generate_phrase_queries": true,
  "analyzer": "search_synonyms_case_insensitive",
  "phrase_slop": 1,
  "default_operator": "AND"
}
```
The following filter is defined:
```json
"filter": {
  "graph_synonyms": {
    "type": "synonym_graph",
    "synonyms_path": "/var/lib/elasticsearch/synonyms.txt",
    "tokenizer": "standard",
    "ignore_case": true,
    "expand": true
},
"analyzer": {
  "search_synonyms_case_insensitive": {
    "type": "custom",
    "tokenizer": "standard",
    "filter": [
      "asciifolding",
      "lowercase",
      "graph_synonyms",
      "standard"
    ]
  }
```
The token **lgbt** is in our synonym list (and has various synonyms).

When we search **including synonyms** we get the following number of rows:
lgbt -> 15000
lgbt* -> 0
Without thesaurus we see more than 7.000 results no matter if we search "lgbt" or "lgbt*".

Is this the expected behavior? Users do not understand this behavior...

**Comment by weberhofer** [comment]
Could be related to #25518

**Comment by jpountz** [comment]
I suspect that you expand synonyms only at search time, or at index time by replacing mapping `lgbt` to some other term `lgbt => some_other_term`.

The fact that it doesn't work is expected: Elasticsearch doesn't apply synonyms on what might be a partial term.

If you want this to work, you will need to apply synonyms at index time using a comma-separated list of synonyms, such as `lgbt, some_other_term`.

**Comment by weberhofer** [comment]
Thanks for your answer. For our use-case synonyms replacement on search-time was a huge improvement, especially together with the automatic phrase detection. I'll see if I have an idea how I can work around this issue.
