### ISSUE TITLE
Can Index Parsing Errors Impact node/cluster stability?

### ISSUE THREAD

**Issue by russellday** [elastic/elasticsearch#31344]
I use index templates to validate data before indexing. Recently, I have encountered instability with some of my data nodes. We encounter a high number of parsing exceptions, which is expected based on the nature of our app but is there any detrimental impact? Can this impact node heap usage or anything that might lead to instability? 

ES Version 6.1.1

HighLevelRestWriter:77 - 38 records failed out of 60: Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse [removed]]

**Comment by danielmitterdorfer** [comment]
Hi @russellday, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch) instead. Thank you!

**Comment by russellday** [comment]
'GitHub is reserved for bug reports and feature requests".............................
