### ISSUE TITLE
gradle idea failed

### ISSUE THREAD

**Issue by doubleuhy** [elastic/elasticsearch#31382]
Gradle Version        : 4.8
 OS Info               : Mac OS X 10.13.4 (x86_64)
 JDK Version           : Oracle Corporation 10.0.1 [Java HotSpot(TM) 64-Bit Server VM 10.0.1+10]
 

> Task :client:benchmark:ideaModule FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':client:benchmark:ideaModule'.
> Could not resolve all dependencies for configuration ':client:benchmark:compileClasspath'.
   > A conflict was found between the following modules:
      - org.elasticsearch.plugin:transport-netty4:7.0.0-alpha1-SNAPSHOT
      - org.elasticsearch.plugin:transport-netty4:7.0.0-alpha1-SNAPSHOT

**Comment by minhlongdo** [comment]
@doubleuhy did you use `./gradlew idea`? I ran `./gradlew idea` against the `master` branch and it looks like the project uses `Gradle Version: 4.7` which works fine.

**Comment by jpountz** [comment]
It works for me on master by running `./gradlew idea`. What exact command are you running and on which branch? Is your checkout clean? Does it still reproduce if you run `git clean -xdf`?

**Comment by ywelsch** [comment]
@doubleuhy please use Gradle 4.7 for now (i.e. the one provided by the wrapper). we're working on 4.8 compatibility, see https://github.com/elastic/elasticsearch/pull/31271

**Comment by doubleuhy** [comment]
it's not work, when i change gradle version 4.8 to 4.7, failed too
~/elasticsearch ❯❯❯ gradle idea
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.7/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :benchmarks
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/zhouwuhong/elasticsearch/benchmarks/build.gradle' line: 31

* What went wrong:
A problem occurred evaluating project ':benchmarks'.
> Failed to apply plugin [id 'elasticsearch.build']
   > **JAVA_HOME must be set to build Elasticsearch**

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9s
~/elasticsearch ❯❯❯ echo $JAVA_HOME
**/Library/Java/JavaVirtualMachines/jdk-10.jdk/Contents/Home**

**Comment by ywelsch** [comment]
Can you use the gradle wrapper? i.e. invoke `./gradlew idea`

**Comment by doubleuhy** [comment]
gradle version change to 4.7, failed too😭
* Where:
Build file '/Users/zhouwuhong/elasticsearch/benchmarks/build.gradle' line: 31

* What went wrong:
A problem occurred evaluating project ':benchmarks'.
> Failed to apply plugin [id 'elasticsearch.build']
   > JAVA_HOME must be set to build Elasticsearch

echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-10.jdk/Contents/Home

**Comment by doubleuhy** [comment]
yes, i'm use ./gradlew idea

**Comment by doubleuhy** [comment]
thanks, i have resolve this question. it seems like groovy `System.getenv('JAVA_HOME')` don't work when java version is 10 and gradle version is 4.7
solution:
--- a/buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy
+++ b/buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy
@@ -206,6 +206,7 @@ class BuildPlugin implements Plugin<Project> {
     }

     private static String findCompilerJavaHome() {
+        return "/Library/Java/JavaVirtualMachines/jdk-10.jdk/Contents/Home"
         final String javaHome = System.getenv('JAVA_HOME')
         if (javaHome == null) {
             if (System.getProperty("idea.active") != null || System.getProperty("eclipse.launcher") != null) {

**Comment by ywelsch** [comment]
I have JDK 10 and gradle 4.7 on my machine and it works. This sounds more like something's wrong with how you've set up your JAVA_HOME.

**Comment by doubleuhy** [comment]
i'm use fish shell, in config.fish
``` set JAVA_HOME (/usr/libexec/java_home)```
echo $JAVA_HOME is work
......
......
and i have another problem, when i run Elasticsearch.java -Des.path.home=/Users/zhouwuhong/elasticsearch -Des.path.conf=/Users/zhouwuhong/elasticsearch/distribution/src/config -Dlog4j2.disable.jmx=true
```
[2018-06-18T19:46:45,235][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]

org.elasticsearch.bootstrap.StartupException: 
org.elasticsearch.bootstrap.BootstrapException:
 java.nio.file.NoSuchFileException: 
/Users/zhouwuhong/elasticsearch/modules/percolator/plugin-descriptor.properties
```
and **modules/percolator/plugin-descriptor.properties** is acturallu not exist

**Comment by ywelsch** [comment]
Please use https://discuss.elastic.co for these questions.

**Comment by atorok** [comment]
I think the second failure is #31399

**Comment by warriorSL2016** [comment]
I try to build it on my pc, I found that first you download and unzip it , then attention that never modify any files and execute the command './gradlew idea' in the bash , and it works.
