### ISSUE TITLE
Feature request: More detailed logging on index creation.

### ISSUE THREAD

**Issue by upuv** [elastic/elasticsearch#31384]
**Describe the feature**:

Additional Logging for _action.auto_create_index_ when set to non-default.  

If index creation fails due to rule violation set in _action.auto_create_index_ a corresponding log entry should indicate the name of the index that was attempted to be created and that it failed do to __Blocked by rule__ _action.auto_create_index blah blah_ based on request from _remote source_.

Note: This will highlight potential mis-configurations in elastic search and remote nodes.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
