### ISSUE TITLE
Alias to an alias

### ISSUE THREAD

**Issue by asm89** [elastic/elasticsearch#3138]
We are potentially interested in exposing parts of our Elasticsearch cluster to the Internet. The idea is to do authentication in Varnish before we hit the actual backend. With the authentication done we do want to limit the accessible documents on a per customer basis.

With [Filtered Aliases] it is possible to create an alias for an existing index and add additional filters to each request. It is possible to create such an index alias for every customer in our system. When a request comes in we use Varnish to rewrite the original request URL to include the customer id returned by the authentication backend. Simplified example:

[Filtered Aliases]: http://www.elasticsearch.org/guide/reference/api/admin-indices-aliases/

    Client
       | /jobs/123
       v
    Varnish
       | /{customerId}/jobs/123
       v
    Elasticsearch

In our current setup we already use aliases in order to do live reindexing. We have an alias `production_jobs` pointing to an index `production_jobs_1368699241`. We can swap the alias to another index without noticeable downtime for our users. It would be great if the setup described above could also leverage this pattern, but now by pointing the alias for a customer to the production index alias. In that case we would only have to update the alias as we do now, instead of doing it for every customer specific alias.

**Comment by perryn** [comment]
Another vote for this feature.

(I'm looking at combining mutli-tenancy via filtered aliases with index-per-timeframe and I'd rather not have to manage a combinatorial explosion of aliases)

**Comment by jaytaylor** [comment]
FWIW, my use case was similar.  This would be a very useful feature imo!

**Comment by cosminkusiri** [comment]
+1

**Comment by jannemann** [comment]
+1

**Comment by Osiriz** [comment]
+1

**Comment by kubz** [comment]
+1

**Comment by bradvido** [comment]
I have many use cases for this as well, especially since aliases can be filtered -- it would be nice to "nest" those filtered aliases instead of repeating the same common filters in each alias.

**Comment by lewchuk** [comment]
+1 for aliases of aliases, my usecase is multiple streams of time based data, I want to window alias each stream individually and have a combined alias for all my streams.

**Comment by j0hnsmith** [comment]
+1 for aliases of aliases

**Comment by mattaylor** [comment]
+1

**Comment by nik9000** [comment]
So I took a look at this a while ago and its not a simple thing to implement which is why no one's done it.

**Comment by pcerioli** [comment]
+1 I would love to see this feature added as well.

**Comment by clintongormley** [comment]
We've talked about this a lot internally and nobody is particularly keen on it.  For a start, there is nowhere to store an alias which points to other aliases (an alias is stored with the index it points to).  Then you have the problems of cycles.  Plus there is a practical limit to the number of aliases you can use, as they are stored in the cluster state.

I think we are unlikely to implement this feature.

**Comment by colings86** [comment]
Agreed, closing this issue

**Comment by yinrong** [comment]
+1 need this

**Comment by sleaze** [comment]
I did need this, but since they said they'll never implement it I found another data store instead to solve my problem and it turned out just fine.

Thanks anyways ES team!

**Comment by bjorn-ali-goransson** [comment]
@clintongormley + gang, the crucial part of alias-of-aliases isn't to make the whole monolithic aliases feature work recursively. The most attractive USP of the aliases feature is the **Index Alias and Zero Downtime** part.

But if you want the filtering or routing feature for your indices, you're busted on the zero-downtime feature. This is clearly suboptimal.

Surely, it cannot be so complex to make the mere *index rewriting* recursive, so we should maybe consider splitting them up physically and logically? Aliases do not imply that there is any special functionality - an alias is *just an alias*: another name for the index.

The other stuff (as I'm not very familiar with it) may be called dynamic/pluggable index filtering or routing, or something else.

**Comment by clintongormley** [comment]
> But if you want the filtering or routing feature for your indices, you're busted on the zero-downtime feature. This is clearly suboptimal.

Why?  You can remove multiple aliases from one index (incl filtering and routing) and add them to another in a single atomic step.

**Comment by bjorn-ali-goransson** [comment]
Ok then. :+1:

2016-04-18 11:36 GMT+02:00 Clinton Gormley <notifications@github.com>:

**Comment by shayts7** [comment]
I wonder if this is the time to revive this idea? 

I have a use case coming from kibana perspective: I have a lot of visualizations, sometimes I want to switch the visualizations to my "staging env".
Alias could be a great way to do it, but since I'm already using aliases in my elasticsearch index layer (I have "latest" alias that points to a new index that I create every day) I cannot do it :-(

**Comment by a1exus** [comment]
+1

**Comment by mikijov** [comment]
+1

I run a large Elastic platform, 1.5TB of RAM worth of clusters, so you can believe me when I tell you that I have many many indices. To keep the platform healthy we need to start automating some index management tasks and we need either alias-to-alias or index-renaming to allow us to transparently manage indices without disrupting users. Basically our problem is that we need two layers, one for users to manage aliased to group related indices together, and one for operators to give us abstraction to manage indices (reindex, reshard, etc) without disrupting the user.

**Comment by mapiram** [comment]
+1

**Comment by slanich** [comment]
Ended up here looking for the same thing. I'm not sure why I didn't think of this sooner, but here was my problem:
Actual index name: prod.xenial-logs
Deployed service, trying to read with hard-coded stage name: prod-blue.xenial-logs

Developers are working to fix that, but a great interim fix, was just setting a new alias, pointing to the actual prod indices:
POST /_aliases
{
  "actions": [
    {
      "add": {
        "index": "prod.xenial-logs*",
        "alias": "prod-blue.xenial-logs"
      }
    }
  ]
}

Since ILM is creating a new index every ~4 hours (rapid ingestion), this will allow our service to read in real time, despite using a stage name prefixing the index. Hope this helps someone!

**Comment by kaykumar** [comment]
+1 alias to alias

**Comment by hauntingEcho** [comment]
+1 on this.  Alias-to-alias mapping makes it a lot easier to present a consistent API to users while updating mappings, when many filters are used.  For example:

* index `customers-v1.0` holds the actual data
* alias `customers` points to `customers-v1.0`
* alias `customers_na` filters `customers` to customers based in North America
* alias `customers_eu` filters `customers` to customers based in Europe
* { more filtering aliases... }

When we need to update e.g. the customer's street name from a `keyword` to `text`, this cannot be done in-place on `customers-v1.0`, so we have to create `customers-v1.1` and use the re-indexing API to move the data over.  We then need to hunt down all existing filter aliases that point to `customers-v1.0` and update them to point to `customers-v1.1`.  With the option to use aliases-of-aliases, this means we only have one alias to update.

**Comment by freakynit** [comment]
+1 we need aliaseption

**Comment by yinrong** [comment]
@elastic-crm @elastic-jira @elastic-data-integration @elastic-stack-testing @elastic-Mak-Ito would you please reopen this issue?

**Comment by jlarroque** [comment]
+1 to this, is truly needed
