### ISSUE TITLE
Docs:  some glossary terms

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/elasticsearch#31390]
Some missing [terminology](https://www.elastic.co/guide/en/elastic-stack-glossary/current/terms.html):

**merge** - This term is used to describe the merging of Lucene segments in automatic background merging, or in a [force merge](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-forcemerge.html).

**reindex** - To cycle through some or all documents in one or more indices, re-writing them into the same or new index in a local or remote cluster.  This is most commonly done to update mappings, or to upgrade Elasticsearch between two incompatible index versions.

**shrink** - To reduce the amount of shards in an index.   See the [Shrink Index API](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-shrink-index.html)

**split** - To grow the amount of shards in an index.  See the [Split Index API](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-split-index.html).

**Comment by Sue-Gallagher** [comment]
Questions:
1. It's never a good idea to use a word to define itself. Can we say:
merge - The combining of Lucene segments, either automatically in the background or initiated using force merge.
2. You said:
"...all documents in one or more indices, re-writing them into the same or new index..."
We spend a lot of electrons telling our users that an index is immutable, so how does rewriting index data back into itself work?

**Comment by PhaedrusTheGreek** [comment]
1.  Sounds better, yes
2. An in-place re-index is actually an simple [_update_by_query](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/docs-update-by-query.html), which is a shared code base with the reindex API - although it is one of those esoteric things.    We could always add another sentence:  "Reindexing to the same index is known as an [Update By Query](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/docs-update-by-query.html)"

**Comment by Sue-Gallagher** [comment]
Fixed. See PR #66.
