### ISSUE TITLE
'enabled' mapping parameter not consistently applied when using dynamic_templates

### ISSUE THREAD

**Issue by derkcrezee** [elastic/elasticsearch#31391]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.0

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_171

**OS version** (`uname -a` if on a Unix-like system): macOs 10.13.5

**Description of the problem including expected versus actual behavior**:

When using dynamic_templates in the mapping, the `enabled` mapping parameter doesn't seem to be applied the same way as using a direct mapping. 

**Steps to reproduce**:

Create a new mapping with dynamic templates, add a document and look at the mapping.

```
PUT my_index
{
  "mappings": {
    "_doc": {
      "dynamic_templates": [
        {
          "full_name": {
            "path_match":   "name.*",
            "path_unmatch": "*.middle",
            "mapping": {
              "enabled": false
            }
          }
        }
      ]
    }
  }
}

PUT my_index/_doc/1
{
  "name": {
    "first":  "Alice",
    "middle": "Mary",
    "last":   "White"
  }
}

GET my_index/_mappings
```

This returns the following mapping.
```
{
  "my_index": {
    "mappings": {
      "_doc": {
        "dynamic_templates": [
          {
            "full_name": {
              "path_match": "name.*",
              "path_unmatch": "*.middle",
              "mapping": {
                "enabled": false
              }
            }
          }
        ],
        "properties": {
          "name": {
            "properties": {
              "first": {
                "type": "text"
              },
              "last": {
                "type": "text"
              },
              "middle": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

I would expect the `name.first` and `name.last` to be disabled, similar to when I provide the following mapping.

```
PUT my_index
{
  "mappings": {
    "_doc": {
      "properties": {
        "name": {
          "properties": {
            "first": {
              "enabled": false
            },
            "last": {
              "enabled": false
            }
          }
        }
      }
    }
  }
}
```

**Comment by imotov** [comment]
The `enabled` setting can be applied only to the mapping type and to object fields. In case of the static mapping, elasticsearch would automatically deduce that `first` and `last` are objects based on the presence of the `enable` setting. In case of the dynamic setting, we use the actual type of the field (string) and the `enabled` flag has a strange side effect of disabling multifield but not the actual field. 

A workaround is to explicitly define `first` and `last` as objects:
```
PUT my_index
{
  "mappings": {
    "_doc": {
      "dynamic_templates": [
        {
          "full_name": {
            "path_match":   "name.*",
            "path_unmatch": "*.middle",
            "mapping": {
              "type": "object",
              "enabled": false
            }
          }
        }
      ]
    }
  }
}
```
That will work, but it's not really a good option since `first` and `last` are not really objects, so a better solution might be to just disable indexing on these fields
```
PUT my_index
{
  "mappings": {
    "_doc": {
      "dynamic_templates": [
        {
          "full_name": {
            "path_match":   "name.*",
            "path_unmatch": "*.middle",
            "mapping": {
              "index": false
            }
          }
        }
      ]
    }
  }
}
```

**Comment by derkcrezee** [comment]
Thanks for the reply. These are both good workarounds indeed.

**Comment by jtibshirani** [comment]
I'll close this out -- while the behavior is subtle, it does not seem like there's a bug.
