### ISSUE TITLE
[FEATURE] Persist Task ID status when a task is cancelled

### ISSUE THREAD

**Issue by untergeek** [elastic/elasticsearch#31432]
A Curator user submitted [an issue](https://github.com/elastic/curator/issues/1236) where if a reindex task is cancelled, it is treated as a regular completion. Curator moves on to the next action in its chain, so long as the target index exists, irrespective of whether the reindex was actually complete.

It would be useful, and hopefully not just for Curator, to be able to identify Task IDs which were cancelled, even if only for a time (1 hour, 1 day, user determined...).  This metadata might identify cancelled tasks, what time they were cancelled, and if x-pack was installed/active, which user issued the cancellation call.

**Comment by bleskes** [comment]
@tlrx can you check what's reasonable possible here?

**Comment by tlrx** [comment]
@untergeek I think that something like this already exists. When a Reindex request is executed with the `wait_for_completion` parameter set to false you get back a task id and the result of the reindex task will be stored in a `.tasks` index. If you use the task id to cancel the task, the reindex task is cancelled and you can get back the task result from the `.tasks` index, something like :

```
GET /.tasks/task/dW_Lc0UcT92Z64bGwzU8jQ:565

{
  "_index" : ".tasks",
  "_type" : "task",
  "_id" : "dW_Lc0UcT92Z64bGwzU8jQ:565",
  "_version" : 1,
  "found" : true,
  "_source" : {
    "completed" : true,
    "task" : {
      "node" : "dW_Lc0UcT92Z64bGwzU8jQ",
      "id" : 565,
      "type" : "transport",
      "action" : "indices:data/write/reindex",
      "status" : {
        "total" : 87,
        "updated" : 0,
        "created" : 51,
        ...
      },
      "description" : "reindex from [docs] to [reindex-docs]",
      "start_time_in_millis" : 1529482732581,
      "running_time_in_nanos" : 60113248976,
      "cancellable" : true,
      "headers" : { }
    },
    "response" : {
      "took" : 50841,
      "timed_out" : false,
      "total" : 87,
      "updated" : 0,
      ...
      "canceled" : "by user request",
      "throttled_until_millis" : 0,
      "failures" : [ ]
    }
  }
}
```

In the reindex task result you can check that the task was effectively cancelled upon user request.

I think that Curator can build something around this?

**Comment by untergeek** [comment]
Yes, I will try.  Thank you.

**Comment by untergeek** [comment]
Closing this as it's been addressed.
