### ISSUE TITLE
Mockito failure in HttpExporterTests - "Checked exception is invalid for this method"

### ISSUE THREAD

**Issue by markharwood** [elastic/elasticsearch#31433]
Failure on master:

    https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu&&virtual/2507/console

Reproduces for me with this seed:

	   REPRODUCE WITH: ./gradlew :x-pack:plugin:monitoring:test -Dtests.seed=8D2608B025564A6 -Dtests.class=org.elasticsearch.xpack.monitoring.exporter.http.HttpExporterTests -Dtests.method="testHttpExporterShutdown" -Dtests.security.manager=true -Dtests.locale=ar-SA -Dtests.timezone=Asia/Damascus
	 ERROR   0.02s J2 | HttpExporterTests.testHttpExporterShutdown <<< FAILURES!
	    > Throwable #1: org.mockito.exceptions.base.MockitoException: 
	    > Checked exception is invalid for this method!
	    > Invalid: java.io.IOException: expected
	    > 	at __randomizedtesting.SeedInfo.seed([8D2608B025564A6:86026F40A148152D]:0)
	    > 	at org.elasticsearch.xpack.monitoring.exporter.http.HttpExporterTests.testHttpExporterShutdown(HttpExporterTests.java:471)
	    > 	at java.lang.Thread.run(Thread.java:748)

**Comment by original-brownbear** [comment]
Fixed in #31527 I think :)
