### ISSUE TITLE
Some error with my elasticsearch stdout

### ISSUE THREAD

**Issue by MD65** [elastic/elasticsearch#31454]
**Elasticsearch version** : 6.2

**Plugins installed**: vega  (I have uninstalled x-pack with `/usr/share/elasticsearch/bin/elasticsearch-plugin remove x-pack` and `elasticsearch-keystore remove bootstrap.password`)

**JVM version** : java version "1.8.0_161"

**OS version** ubuntu:

I have several nodes, and for each elasticsearch stdout, there are 4 cases : 

1. The node works correctly

 2. Without stdout (frozen) 

 3. This error
` [2018-06-19T10:33:35,507][ERROR][o.e.b.Bootstrap ] Exception [2018-06-19T10:33:35,529][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [SOCdata-16] uncaught exception in thread [main]`

 4. And this error
` [2018-06-19T09:23:26,805][WARN ][o.e.c.m.MetaData ] Skipping unknown custom object with type licenses [2018-06-19T09:23:26,806][WARN ][o.e.c.m.MetaData ] Skipping unknown custom object with type ml –`

Thanks.

**Comment by ywelsch** [comment]
Please ask questions like these on our discuss forums (discuss.elastic.co). Github should only be used for reporting verified bugs and feature requests.
