### ISSUE TITLE
JDBC Driver Missing

### ISSUE THREAD

**Issue by RokaFogtaCsukaFarka** [elastic/elasticsearch#31455]
**Describe the feature**: I would like to be able to download the JDBCDriver.java of the elasticsearch product from maven.

**Elasticsearch version** (`bin/elasticsearch --version`): Java lib 6.3.0

**Plugins installed**: []

**JVM version** (`java -version`):  "1.8.0_45"

**OS version** (`uname -a` if on a Unix-like system): Windows

**Description of the problem including expected versus actual behavior**:
I cannot find the JDBCDriver class in the downloaded maven elasticsearch artifact-id package.
Indeed the whole xpack folder - package is missing.

**Steps to reproduce**: Import maven 

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
Import maven dependency:
           <dependency>
                <groupId>org.elasticsearch</groupId>
                <artifactId>elasticsearch-core</artifactId>
                <version>6.3/0</version>
            </dependency>
 2. Use datasource bean 
	@Bean
	public DataSource dataSource(){
		DriverManagerDataSource dataSource = new DriverManagerDataSource();
		dataSource.setDriverClassName("org.elasticsearch.xpack.sql.jdbc.jdbc.JdbcDriver");
		dataSource.setUrl("jdbc:es://" + getDbHostName() + ":" + DB_PORT + "/" + DB_NAME);
		dataSource.setUsername( "elastic" );
		dataSource.setPassword( "abcd1234" );
		return dataSource;
	}
 3. Use the javax.persistence API for using elasticsearch with JPA and Hibernate

**Provide logs (if relevant)**:
java.lang.ClassNotFoundException: org.elasticsearch.xpack.sql.jdbc.jdbc.JdbcDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.setDriverClassName(DriverManagerDataSource.java:127)
	... 53 more

****

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

Here you need to follow the instructions here: https://www.elastic.co/guide/en/elasticsearch/reference/6.3/sql-jdbc.html
