### ISSUE TITLE
Indexing on SSD vs HDD hardisk

### ISSUE THREAD

**Issue by tahirahmad2030** [elastic/elasticsearch#31452]
**Describe the feature**: Performance of indexing

**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.4

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Ubuntu

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
I am indexing a csv file on a Dell system(Ubuntu 16) with HDD hardisk and it takes 3 hours to index it. However I also indexed the same csv file on Macpro with SSD hardisk and it took 15 minutes to index the same. Is this the expected behaviour in performance with respect to SSD vs HDD. or Do the need to tune HDD machine further?

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
