### ISSUE TITLE
cluster.routing.allocation.same_shard.host doesnt seem to work properly

### ISSUE THREAD

**Issue by tuudik** [elastic/elasticsearch#31453]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.0

**Plugins installed**: [ingest-geoip]

**JVM version** (`java -version`): openjdk version "1.8.0_171"

**OS version** (`uname -a` if on a Unix-like system): Linux elk-ela-1f 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
I have setup 4 nodes in one machine elk-ela-1f. Did this with elastic/ansible-elasticsearch.
Each node has setup `cluster.routing.allocation.same_shard.host: true` to prevent same shard allocation on same host. But when I check the shard allocation with head, I can see that same shard have been allocated on same host, but different nodes.
```
data-1/elasticsearch.yml:cluster.routing.allocation.same_shard.host: true
data-2/elasticsearch.yml:cluster.routing.allocation.same_shard.host: true
data-3/elasticsearch.yml:cluster.routing.allocation.same_shard.host: true
data-4/elasticsearch.yml:cluster.routing.allocation.same_shard.host: true
```
![screen shot 2018-06-20 at 09 37 44](https://user-images.githubusercontent.com/788492/41641704-d16d7902-746e-11e8-9810-543a3a64dd9e.png)

**Comment by ywelsch** [comment]
In order for the system to identify these nodes as the "same host", they need to have the same host name or host address. Can you check the output of `/_nodes/stats` to verify that they indeed share the same host name or address? Note that you can alternatively also use [cluster allocation awareness](https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-awareness.html) to achieve the same thing. Please also ask further questions on our discuss forums (discuss.elastic.co), as we reserve Github for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

**Comment by tuudik** [comment]
@ywelsch https://discuss.elastic.co/t/cluster-routing-allocation-same-shard-host-doesnt-seem-to-work-properly/136625

Added there some additional information.

Are you sure it's not a bug?
