### ISSUE TITLE
Partial Update : for better write performance 

### ISSUE THREAD

**Issue by xzhthu2018** [elastic/elasticsearch#31467]
Hi,
    Support Partial Update can achieve better bulk performance when the docs with many fields and frequent updates for just several fields.
    for example:
    doc schema:
   `{"id":1,"status":1, "modify_time":"2018-06-20 23:39:00","field1":"xxxx",...,"field...":"xxxx"}`
    we frequently updates the fields {status} and {modify_time}
    I found that the relative [issue ](https://github.com/elastic/elasticsearch/issues/211) is closed for long years ago.  It seems to be closed automatically. But i can not find a practical solution to achieve it.
    Finally I found that If the es / lucene support the [field /field family segment ](https://github.com/elastic/elasticsearch/issues/31464) , we can achieve the partial update much more easily. We make the hot-update-field to a isolate field family. if the relative fields are update, the hot-update-field will be re-built for reverse index or doc values, but the non-update fields won't be changed, so that we can save more cpu to achieve much better index throughput.

**Comment by ywelsch** [comment]
There's more info on this in #30433
