### ISSUE TITLE
Make watch history searchable (again)

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch#31460]
**Describe the feature**:

Sometimes we want to pull the `results.input.payload.error.reason` information and maybe create visualizations or cron jobs to see if inputs in watches are failing. This doesn't seems to be possible (as expected) because the watch history template that disables most of this fields (for previous errors regarding mapping). 

I think we need a way (common way) of storing failures in some exception/failure field in the watch result so then we can automate or manually search through results without the need of pulling everything and grepping/grabbing the values manually.

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
