### ISSUE TITLE
Injecting RestController in 5.6.8

### ISSUE THREAD

**Issue by arulsince1975** [elastic/elasticsearch#31475]
I have the following code in one of my plugins which works well with ES 5.1.2. However with ES 5.6.8 it compiles, but runs into problem as it is not possible to inject RestController directly.
Please let me know the workaround for the same?

public class IndexCleanerAction implements RestHandler {
  
    @Inject
    public IndexCleanerAction(final RestController controller) {
        controller.registerHandler(RestRequest.Method.GET, "/_indexcleaner/indexcleanup", this);
        controller.registerHandler(RestRequest.Method.POST, "/_indexcleaner/indexcleanup", this);
        controller.registerHandler(RestRequest.Method.PUT, "/_indexcleaner/indexcleanup/{id}", this);
        controller.registerHandler(RestRequest.Method.DELETE, "/_indexcleaner/indexcleanup/{id}", this);
    }

**Comment by rjernst** [comment]
Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports.

With that said, you need to implement an `ActionPlugin`, and return your rest handler from `getRestControllers`, which takes the `RestController` as an argument.
