### ISSUE TITLE
Prompt to retype key/password when adding secure settings

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#31488]
**Elasticsearch version**: 6.2

When using [elasticsearch-keystore](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/secure-settings.html#add-string-to-keystore) to add a new string, we only prompt for the user to type in the desired key/password once.

It will be a nicer experience to ask the user to retype the key/password one more time in case the wrong value was entered on the first (and only) try.

**Comment by bleskes** [comment]
@jkakavas @rjernst seems logical to me?

**Comment by rjernst** [comment]
Why is running the command again not sufficient? Entering the keystore password is not like entering an account password, where the hash is compared. It is used to decrypt the keystore immediately, and the decryption not throwing an error is the only indication we have of success. So prompting again would mean wrapping the decryption in a try/catch and repeating. But there could be the reasons the decryption fails (for example, the file is truncated). We could potentially change the format so we can detect if the password identify if the password is correct "early" (eg checking some header info quickly to identify if decryption is succeeding). But the Java `keytool` does not do this, so I am unsure if we really need to.

**Comment by jkakavas** [comment]
I think what @ppf2 had in mind was not about the keystore password, but the value that is being added in the keystore (which is presumably more often than not, a password/key). 

As in 

```
$ bin/elasticsearch-keystore add the.setting.name.to.set
Enter value for the.setting.name.to.set: 
Confirm value for the.setting.name.to.set: 
```

for example. 
This would be the logical equivalent of typing your password twice during an account registration form.  

I don't think it's a bad idea, but I can imagine it might be considered as cumbersome by some users too.

**Comment by ppf2** [comment]
It can certainly be cumbersome to prompt for every setting.  But it can be really helpful to prompt for these important ones for if the admin mistakenly type in something wrong (without noticing), they will find out later (in a painful way) that things will simply not work in Elasticsearch.

```
bin/elasticsearch-keystore add "bootstrap.password"
bin/elasticsearch-keystore add xpack.security.transport.ssl.keystore.secure_password
bin/elasticsearch-keystore add xpack.security.transport.ssl.truststore.secure_password
```

**Comment by rjernst** [comment]
I don't know of any storage systems that require setting values twice. We also haven't really heard many asks for this. Semi related, I created https://github.com/elastic/elasticsearch/issues/46148 as a general issue for keystore validation, which could also be used for validation of things like certifcate passphrases if we were to check the passphrase can actually decrypt the configured cert. Additionally, it is still possible we will add the ability to place certs directly into the keystore. Given all of that, I will close this issue.
