### ISSUE TITLE
[docs] High-level REST client : incomplete docs

### ISSUE THREAD

**Issue by olcbean** [elastic/elasticsearch#31499]
In the high level REST client, a client specific response has been create for the get alias API that holds not only the aliases but also an _error message_, an _exception_ and the _status_ as part of the response. 

For this API the rest client always returns a response ( even when an exception occurs, it is parsed and set in the response ). Should the docs be extended and clarify that the users should analyze the response in order to determine if an exception has occurred on the server or not? 

Currently the docs refer only to the aliases :

https://github.com/elastic/elasticsearch/blob/c4f8df3ad6b8657557a7efb9399e70927e1f0340/docs/java-rest/high-level/indices/get_alias.asciidoc#L84-L94 https://github.com/elastic/elasticsearch/blob/c4f8df3ad6b8657557a7efb9399e70927e1f0340/client/rest-high-level/src/test/java/org/elasticsearch/client/documentation/IndicesClientDocumentationIT.java#L1772-L1774

---
#30536 : discusses the current get aliases API
#28799 : added the get aliases API to the high level REST client and introduced the client specific response

**Comment by debadair** [comment]
[doc-issue-triage]
