### ISSUE TITLE
Feature request: report the expected mapping type on every mapping_exception

### ISSUE THREAD

**Issue by redlus** [elastic/elasticsearch#31502]
Hi,

As part of our product, we're indexing our customer's data on elasticsearch clusters. For this reason, we cannot control the mapping types of each source, and cannot prevent mapping_exceptions from occurring. For each mapping_exception we're modifying the original document to avoid dataloss.

Currently, this is a difficult task, as elasticsearch does not report which mapping type is expected upon an exception - but only the field name that caused the exception within the indexed document; e.g.
> failed to parse [field.with.mapping.exception]

There is one exception to this rule, which is when dealing with objects; e.g., when indexing a concrete value into a field with mapping_type of object:
> object mapping for [object.field] tried to parse field [object.field] as object, but found a concrete value

Or when indexing a nested object into a concrete value:
>  Could not dynamically add mapping for field [boolfield.test]. Existing mapping for [boolfield] must be of type object but found [boolean].

The two exceptions above make it much easier to actually handle the exception and prevent dataloss. I'd like to suggest adding the expected mapping type for all mapping exceptions.

**Comment by lipsill** [comment]
Hi! I would like to give this one a try.
@redlus would something like `failed to parse field [field.with.mapping.exception], expected type [field.type]` work for you?

**Comment by redlus** [comment]
Hey @lipsill, that would be great 👍🏼
