### ISSUE TITLE
failed to get node info for {#transport#-1}{52.43.xx.xxx}{52.43.xx.xxx:9243}, disconnecting...

### ISSUE THREAD

**Issue by santoshcareerwaze** [elastic/elasticsearch#31503]
Trying to connect to cloud elastic search, getting below error.
[][generic][T#2]] org.elasticsearch.client.transport       : [Jimaine Szardos] failed to get node info for {#transport#-1}{52.43.xx.xxx}{52.43.xx.xxx:9243}, disconnecting...

org.elasticsearch.transport.NodeDisconnectedException: [][52.43.xx.xxx:9243][cluster:monitor/nodes/liveness] disconnected

This is how I'm connecting
	@Bean
	public Client client() throws Exception {

		Settings esSettings = Settings.settingsBuilder()
				.put("http.enabled", true)
				.build();

		return TransportClient.builder().settings(esSettings).build()
				.addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName(EsHost), EsPort));
	}

**Comment by javanna** [comment]
Please ask your question in our forums at https://discuss.elastic.co/ . We reserve github issues for confirmed bugs and feature requests. Thanks!
