### ISSUE TITLE
NodeSelector?

### ISSUE THREAD

**Issue by gmarshall56** [elastic/elasticsearch#31504]
I have brought the RequestOptions class into my maven project.  I have a compiler error concerning the NodeSelector.  Stupid question:  Where can I find this NodeSelector class that is required for this RequestOptions class?
Thank you
Gary

**Comment by javanna** [comment]
hi @gmarshall56 please ask your question on our forums at https://discuss.elastic.co/ . We reserve github issues for feature requests and confirmed bug reports.
