### ISSUE TITLE
Completion suggester ignores trailing spaces in queries

### ISSUE THREAD

**Issue by kylelyk** [elastic/elasticsearch#31536]
**Elasticsearch version**: 6.2.4

**Plugins installed**: []

**JVM version**: 1.8.0_101

**OS version**: MacOS (Darwin Kernel Version 15.6.0)

**Description of the problem including expected versus actual behavior**:
When specifying a prefix query for the completion suggester, trailing spaces in the query do not have an effect on the results. This is annoying to users since a query for "car " will return suggestions like "carpet" rather than "car shop".

**Steps to reproduce**:

```
PUT music
{
  "mappings": {
    "_doc": {
      "properties": {
        "suggest": {
          "type": "completion"
        }
      }
    }
  }
}

PUT music/_doc/1?refresh
{
    "suggest" : "foo bar baz"
}
```
```
POST music/_search?pretty
{
    "suggest": {
        "song-suggest" : {
            "prefix" : "foo b ",
            "completion" : { 
                "field" : "suggest"
            }
        }
    }
}
```

returns 1 suggestion when it should fail to find any suggestions that start with "foo b ".

**Comment by imotov** [comment]
The completion terms are processed by an analyzer, by default the `standard` analyzer is used, this analyzer will split text into word and will ignore punctuation marks and spaces. If you need a precise suggestion, you need to switch to another analyzer, for example `keywords`

```
PUT music
{
  "mappings": {
    "_doc": {
      "properties": {
        "suggest": {
          "type": "completion",
          "analyzer": "keyword"
        }
      }
    }
  }
}
```

If you have any other questions about functionality of the suggesters, please consider using our discussion forum https://discuss.elastic.co/ .
