### ISSUE TITLE
startObject "details" throws UncategorizedExecutionException  ES 6.3.0

### ISSUE THREAD

**Issue by gmarshall56** [elastic/elasticsearch#31531]
Bug report

**Elasticsearch version: 6.3.0

Plugins installed: none

JVM version: java version "1.8.0_172"

OS version: Windows 10

Description of the problem including expected versus actual behavior:
Including a startObject field with the name "details" in the "properties" of XContentBuilder results in a UncategorizedExecutionException to be thrown.

Steps to reproduce:
See next.

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

Here is the code for the XContentBuilder we are instantiating( the "..." indicates there are more .startObject statements:
` XContentBuilder builder = jsonBuilder().startObject()
	.startObject(RESOURCE_TYPE)
		.startObject("properties")
			.startObject("details").field("type", "string").endObject()  <== causes exception
			.startObject("latlon").field("type", "geo_point").endObject()
			.startObject("path").field("type", "text").field("analyzer", "path-analyzer").field("fielddata", 
 true).endObject()
			.startObject("emailString").field("type", "text").field("analyzer", "url-email-analyzer").endObject()
			... 	
		.endObject()
	.endObject().endObject();`

Provide logs:
Having that `.startObject("details").field("type", "string").endObject()` defined in the XContentBuilder throws this exception when the code is executed:
> UncategorizedExecutionException[Failed execution]; nested: IOException[Duplicate field 'details'
 at [Source: java.io.StringReader@e455a7c; line: 1, column: 616]];
	at org.elasticsearch.common.util.concurrent.FutureUtils.rethrowExecutionException(FutureUtils.java:90)
	at org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:55)
	at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:34)
...
...
<
When the `.startObject("details").field("type", "string").endObject()` is commented out there is no exception thrown.

We have had the XContentBuilder defined as you see here for quite some time now without any issues.  With ES version 6.3.0 I am now getting this exception.  Please advise:  Can we no longer define a "details" field defined in ES version 6.3.0?  Or should this "details" filed be defined in the .startObject in another way?
Thank you for your time.

**Comment by martijnvg** [comment]
Hey @gmarshall56 please ask your question on our forums at https://discuss.elastic.co/ . We reserve github issues for feature requests and confirmed bug reports. It looks like two `detail` fields appear in your mapping. If you include the entire mapping in your question then it will be easier to for people to help you in the forum.
