### ISSUE TITLE
sudo apt update failing

### ISSUE THREAD

**Issue by jhkrischel** [elastic/elasticsearch#31543]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.x

**Plugins installed**: []

**JVM version** (`java -version`): N/A

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 16.04

**Description of the problem including expected versus actual behavior**:

apt installs are failing with "does not have a Release file", even with ca-certificates and apt-transport-https installed.

**Steps to reproduce**:

```
vagrant@graylog:~$ sudo apt install ca-certificates apt-transport-https
Reading package lists... Done
Building dependency tree       
Reading state information... Done
apt-transport-https is already the newest version (1.2.26).
ca-certificates is already the newest version (20170717~16.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
vagrant@graylog:~$ sudo apt update
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Ign:5 https://artifacts.elastic.co/packages/oss-5.x/apt stable InRelease
Err:6 https://artifacts.elastic.co/packages/oss-5.x/apt stable Release
  404  Not Found
Reading package lists... Done
E: The repository 'https://artifacts.elastic.co/packages/oss-5.x/apt stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
vagrant@graylog:~$ 
```

You can also hit the repository URL directly in a browser, and get this:
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>packages/oss-5.x/apt</Key>
<RequestId>4643F2C7A09863B2</RequestId>
<HostId>
iAVtFqc3gcwJwDtF2rw3Z3HiO3kZ3vtaW1D3hXtDDBRMct34nMzVqSa+pIt7qzwNeq9YECVFHdM=
</HostId>
</Error>
```
**Provide logs (if relevant)**:

**Comment by jasontedor** [comment]
There is no oss-5.x repository. 5.x is distributed as before: the Apache 2.0 licensed code is shipped in archive or package form (in the existing 5.x repositories) and X-Pack must be installed after the fact.

**Comment by jhkrischel** [comment]
Same error for non-oss: https://artifacts.elastic.co/packages/5.x/apt

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>packages/5.x/apt</Key>
<RequestId>05AA63FF6D018A6E</RequestId>
<HostId>
lfA2gG8aXu4K09CEYooZK3y7wnkXA3OrbN7kc5vSL0auRouV6kYSdPvH5BVqsAasdK4GJ4AQ9GU=
</HostId>
</Error>
```

Is the URL I'm citing the wrong pattern entirely?

**Comment by jhkrischel** [comment]
Hrm...looks like issue with ansible role for elasticsearch when disabling xpack - it goes to the oss-5.x repo that doesn't exist.

**Comment by Mephistokrates** [comment]
We cant get there either:
`Ign:1 https://artifacts.elastic.co/packages/5.x/apt stable InRelease
Fehl:2 https://artifacts.elastic.co/packages/5.x/apt stable Release
  Received HTTP code 403 from proxy after CONNECT
OK:3 http://security.debian.org/debian-security stretch/updates InRelease
Ign:4 http://ftp.de.debian.org/debian stretch InRelease
OK:5 http://ftp.de.debian.org/debian stretch-updates InRelease
OK:6 http://ftp.de.debian.org/debian stretch Release
Paketlisten werden gelesen... Fertig
E: The repository 'https://artifacts.elastic.co/packages/5.x/apt stable Release' does not have a Release file.
`

`<Error>
<script/>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>packages/5.x/apt</Key>
<RequestId>A7CAD6AA54DEDC85</RequestId>
<HostId>
JdSjZMGZrdroKhO2gUhqhLjQNYUvQtN0Xpil5wUAg80/Y900p3uQHn3/bQdudRpZBO9ePTttQQk=
</HostId>
</Error>`
