### ISSUE TITLE
ML getting started docs

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch#31541]
The [ML getting started docs](https://www.elastic.co/guide/en/elastic-stack-overview/current/ml-gs-data.html) and sample scripts expect that security must be enabled first.  This is no longer the case.  Setting up security is now an orthogonal task and doesn't need to be explained in the ML section.  Also, we should provide scripts that work with security enabled or disabled.

**Comment by clintongormley** [comment]
Also, the script runs hundreds of times faster if the output from the bulk indexing commands is sent to /dev/null, ie:

```
curl -s  -X POST -H "Content-Type: application/json" ${URL}/${INDEX_NAME}/_bulk --data-binary "@server-metrics_1.json" > /dev/null
```

**Comment by lcawl** [comment]
Related to https://github.com/elastic/stack-docs/pull/68

**Comment by lcawl** [comment]
This has been closed in the aforementioned PRs and backported to 5.4.
