### ISSUE TITLE
IntelliJ: cannot find symbol ExtendedPluginsClassLoader

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#31555]
My development environment was recently in a state where I could not run a plugin test suite in my IDE. I use IntelliJ 2017.3.5, and was attempting to run the `AwsEc2ServiceImplTests` test suite in the `ec2-discovery` plugin against a commit that's a couple of small changes away from current `master` (8b698f0bce8c73cb6d8510ce6a3f857cb0fb2f02). The error reported was at build time:

```
Error:(31, 16) java: cannot find symbol
  symbol:   variable ExtendedPluginsClassLoader
  location: class org.elasticsearch.plugins.PluginLoaderIndirection
```

This persisted after running `git clean -dxf && ./gradlew idea` and then `Invalidate Caches & Restart` in IntelliJ.

I resolved this by running `TimeZoneRoundingTests` (which are in `server`) which built successfully and passed. I then tried `AwsEc2ServiceImplTests` again and they also worked.

I then tried `git clean -dxf && ./gradlew idea` again and attempted to re-run `AwsEc2ServiceImplTests` and it once again failed with the message reported above.

Searching our internal Slack history indicates this has been seen by others at least twice before.

Running `git clean -dxf && ./gradlew :plugins:discovery-ec2:test -Dtests.class=org.elasticsearch.discovery.ec2.AwsEc2ServiceImplTests` yields no such problem.

**Comment by rjernst** [comment]
For unclear reasons, IntelliJ won't trigger a build of the plugins classloader when it is "provided" (ie on the compileOnly classpath. If you trigger a full build, or run a core test, it get's built, and it never changes, so all tests work after that. Unfortunately this is just one of the many oddities of IntelliJ+Gradle.

**Comment by mark-vieira** [comment]
Looks like this is still an issue. There are potentially ways to improve this, such as configuring the build to compile these dependencies on import so they're available for the IDE.

**Comment by mark-vieira** [comment]
Looking into this it does seem like IntelliJ is getting confused by the provided scope dependency. It compiles the `:server` project correctly but can't seem to figure out that it needs to compile `plugin-classloader` if you simply trigger a test to run.

That said, if you simply trigger a build in IntelliJ with ⌘F9 it builds everything properly (in the correct order) and tests run fine. I'm not sure there's much we can do here except maybe update some docs to suggest folks do a full build in IntelliJ before running any tests.

**Comment by mark-vieira** [comment]
I've not observed this happen in some time. I'm going to assume IntelliJ has fixed this in recent releases.
