### ISSUE TITLE
kibana-oss can not be installed via APT repository oss-6.x but it is included in 6.x

### ISSUE THREAD

**Issue by ddiazpinto** [elastic/elasticsearch#31567]
**Elasticsearch version** (`bin/elasticsearch --version`): trying to install 6.x

**Plugins installed**: none

**JVM version** (`java -version`): not applicable

**OS version** (`uname -a` if on a Unix-like system): Debian 9

**Description of the problem including expected versus actual behavior**: kibana-oss is not included in oss-6.x repository but it is in 6.x.

**Steps to reproduce**:
*6.x repository*
$ curl -s https://artifacts.elastic.co/packages/6.x/apt/dists/stable/main/binary-amd64/Packages | grep Package: | sort -u
Package: apm-server
Package: auditbeat
Package: elasticsearch
Package: filebeat
Package: heartbeat-elastic
Package: kibana
**Package: kibana-oss**
Package: logstash
Package: metricbeat
Package: packetbeat

*oss-6.x repository*
$ curl -s https://artifacts.elastic.co/packages/oss-6.x/apt/dists/stable/main/binary-amd64/Packages | grep Package: | sort -u
Package: apm-server-oss
Package: auditbeat-oss
Package: elasticsearch-oss
Package: filebeat-oss
Package: heartbeat-elastic-oss
Package: logstash
Package: metricbeat-oss
Package: packetbeat-oss

**Comment by jasontedor** [comment]
Thanks for the report and sorry for the trouble. We have addressed this for the 6.3.1 release (not currently available, but will be in the correct location when available).
