### ISSUE TITLE
Do not include an aggregation's `extended_bounds` in cache key

### ISSUE THREAD

**Issue by polyfractal** [elastic/elasticsearch#31561]
Today, if `extended_bounds` is specified on an aggregation it is included in the key for caching the query/aggregation results.  Because `extended_bounds` tend to be highly dynamic, changing on each request, this can incur a fairly serious performance penalty.  Each time the bounds change the old cached results are missed (even if it would be identical) and causes another entry to be cached.

For example, Kibana manually performs the `extended_bounds` filling client-side to avoid this performance penalty.

We should find a way to avoid including `extended_bounds` in the cache key, and only use it to "enrich" the agg result before returning to the user.  That way the underlying cached values will be used even if the bounds shift.

**Comment by Kiriakos1998** [comment]
Hello @rjernst @polyfractal , if this issue is still open may I work on it?

**Comment by wchaparro** [comment]
This is not something we plan to implement in the near future in aggregations, and has been superceded by our focus on ESQL. Closing as not planned. If your feel strongly about this one, please let us know.
