### ISSUE TITLE
switch new index to alias and remove old index ,request timeout 

### ISSUE THREAD

**Issue by mylinuxsa** [elastic/elasticsearch#31566]
request rate qps 1000/s ,

switch new index to alias and remove old index ,request timeout

**Comment by markharwood** [comment]
It sounds like you're looking for advice here on "index warming" rather than raising a specific bug. 
This sort of discussion is best handled in our [discuss forums](https://discuss.elastic.co/c/elasticsearch) rather than here where we track specific bugs or new features. Closing.

**Comment by mylinuxsa** [comment]
request rate 1000/s

curl -s -H  "Content-Type:application/json; charset=UTF-8"  -X POST 'http://localhost:9200/_aliases' -d '{"actions":[{"add":{"index":"user-20180701","alias":"userdata"}}]}'
curl -s -H  "Content-Type:application/json; charset=UTF-8"  -X POST 'http://localhost:9200/_aliases' -d '{"remove":[{"add":{"index":"user-20180631","alias":"userdata"}}]}'


switch index period a little request timeout continued 30s
