### ISSUE TITLE
Single master with two load balancing nodes 

### ISSUE THREAD

**Issue by manoj4321** [elastic/elasticsearch#31560]
hello,
I am trying to make a cluster in which there is one master node and the other two are data nodes (for load balancing during search query). Currently i am facing the problem in which all the shards are diverted to one of the two data nodes (checked via monitoring through kibana). When I intentionally shut down that node, I am getting the error that all primary shards are lost. But when, I shut down the other node (that too intentionally) cluster is running ok. I am running all three nodes on different machines, shared with each other. So,
1. Instead of two data nodes should I make two coordinating nodes ?? (As far as I know every node is a coordinating node)
2. I want, if my one load balancing node breaks down the other node should handle it's work. For that what should i do ??

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by manoj4321** [comment]
thank you
