### ISSUE TITLE
HELP!!!! Why the search took 237ms????  HELP!

### ISSUE THREAD

**Issue by sd1026203** [elastic/elasticsearch#31573]
The elasticsearch version is 6.2.4
The query source is below:
`{"from":0,"size":20,"query":{"bool":{"filter":[{"term":{"entityID":{"value":28683680,"boost":1.0}}},{"term":{"businessID":{"value":1,"boost":1.0}}},{"term":{"isdel":{"value":0,"boost":1.0}}},{"term":{"partnerID":{"value":0,"boost":1.0}}},{"bool":{"should":[{"term":{"checkStatus":{"value":2,"boost":1.0}}},{"term":{"checkStatus":{"value":1,"boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}},"profile":true,"_source":false,"sort":[{"createdTime":{"order":"desc"}}]}`
The profile is as below; Any one can tell me why it took 237ms? 
> {
"took":237,
"timed_out":false,
"_shards":{
"total":3,
"successful":3,
"skipped":0,
"failed":0
},
"hits":{
"total":133,
"max_score":null,
"hits":[
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1011521625796923392",
"_score":null,
"sort":[
1530000523414
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1011216755818782721",
"_score":null,
"sort":[
1529927836742
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1011215118995845120",
"_score":null,
"sort":[
1529927446494
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010800364796010496",
"_score":null,
"sort":[
1529828561389
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010699787260948480",
"_score":null,
"sort":[
1529804581846
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010539799846617089",
"_score":null,
"sort":[
1529766437863
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010455726826487808",
"_score":null,
"sort":[
1529746393292
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010432912811646976",
"_score":null,
"sort":[
1529740954012
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010419840294346752",
"_score":null,
"sort":[
1529737837287
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010404237873545216",
"_score":null,
"sort":[
1529734117383
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010403951759089664",
"_score":null,
"sort":[
1529734049166
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010388934624038913",
"_score":null,
"sort":[
1529730468796
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010386766143705088",
"_score":null,
"sort":[
1529729951797
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010385596134223873",
"_score":null,
"sort":[
1529729672836
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010369493777534976",
"_score":null,
"sort":[
1529725833746
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010363319816585216",
"_score":null,
"sort":[
1529724361753
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010337323566522368",
"_score":null,
"sort":[
1529718163765
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010337285972975617",
"_score":null,
"sort":[
1529718154802
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010337075989340161",
"_score":null,
"sort":[
1529718104739
]
},
{
"_index":"newpinglunsearchindex",
"_type":"pinglunsearch",
"_id":"1010329739723833345",
"_score":null,
"sort":[
1529716355628
]
}
]
},
"profile":{
"shards":[
{
"id":"[2QemTRuhSPSCZd5qrpvQig][newpinglunsearchindex][2]",
"searches":[
{
"query":[
{
"type":"BooleanQuery",
"description":"#entityID:[28683680 TO 28683680] #businessID:[1 TO 1] #isdel:[0 TO 0] #partnerID:[0 TO 0] #((checkStatus:[2 TO 2] checkStatus:[1 TO 1])~1)",
"time_in_nanos":1979733,
"breakdown":{
"score":0,
"build_scorer_count":38,
"match_count":0,
"create_weight":6480,
"next_doc":125866,
"match":0,
"create_weight_count":1,
"next_doc_count":128,
"score_count":0,
"build_scorer":1847220,
"advance":0,
"advance_count":0
},
"children":[
{
"type":"PointRangeQuery",
"description":"entityID:[28683680 TO 28683680]",
"time_in_nanos":486265,
"breakdown":{
"score":0,
"build_scorer_count":57,
"match_count":0,
"create_weight":1024,
"next_doc":9547,
"match":0,
"create_weight_count":1,
"next_doc_count":128,
"score_count":0,
"build_scorer":470234,
"advance":5202,
"advance_count":72
}
},
{
"type":"PointRangeQuery",
"description":"businessID:[1 TO 1]",
"time_in_nanos":298519,
"breakdown":{
"score":0,
"build_scorer_count":57,
"match_count":0,
"create_weight":141,
"next_doc":0,
"match":0,
"create_weight_count":1,
"next_doc_count":0,
"score_count":0,
"build_scorer":288763,
"advance":9399,
"advance_count":158
}
},
{
"type":"PointRangeQuery",
"description":"isdel:[0 TO 0]",
"time_in_nanos":17524,
"breakdown":{
"score":0,
"build_scorer_count":57,
"match_count":0,
"create_weight":129,
"next_doc":0,
"match":0,
"create_weight_count":1,
"next_doc_count":0,
"score_count":0,
"build_scorer":9457,
"advance":7752,
"advance_count":128
}
},
{
"type":"PointRangeQuery",
"description":"partnerID:[0 TO 0]",
"time_in_nanos":359384,
"breakdown":{
"score":0,
"build_scorer_count":57,
"match_count":0,
"create_weight":136,
"next_doc":0,
"match":0,
"create_weight_count":1,
"next_doc_count":0,
"score_count":0,
"build_scorer":348358,
"advance":10652,
"advance_count":180
}
},
{
"type":"BooleanQuery",
"description":"(checkStatus:[2 TO 2] checkStatus:[1 TO 1])~1",
"time_in_nanos":667558,
"breakdown":{
"score":0,
"build_scorer_count":57,
"match_count":0,
"create_weight":1709,
"next_doc":0,
"match":0,
"create_weight_count":1,
"next_doc_count":0,
"score_count":0,
"build_scorer":637181,
"advance":28434,
"advance_count":176
},
"children":[
{
"type":"PointRangeQuery",
"description":"checkStatus:[2 TO 2]",
"time_in_nanos":253413,
"breakdown":{
"score":0,
"build_scorer_count":51,
"match_count":0,
"create_weight":201,
"next_doc":0,
"match":0,
"create_weight_count":1,
"next_doc_count":0,
"score_count":0,
"build_scorer":251306,
"advance":1836,
"advance_count":18
}
},
{
"type":"PointRangeQuery",
"description":"checkStatus:[1 TO 1]",
"time_in_nanos":334046,
"breakdown":{
"score":0,
"build_scorer_count":51,
"match_count":0,
"create_weight":129,
"next_doc":0,
"match":0,
"create_weight_count":1,
"next_doc_count":0,
"score_count":0,
"build_scorer":329373,
"advance":4407,
"advance_count":85
}
}
]
}
]
}
],
"rewrite_time":6616,
"collector":[
{
"name":"CancellableCollector",
"reason":"search_cancelled",
"time_in_nanos":49996,
"children":[
{
"name":"MultiCollector",
"reason":"search_top_hits",
"time_in_nanos":40254
}
]
}
]
}
],
"aggregations":[
]
},
{
"id":"[S8c8O6OLTh6bhbIPa8RX0w][newpinglunsearchindex][1]",
"searches":[
{
"query":[],
"rewrite_time":14402,
"collector":[
{
"name":"CancellableCollector",
"reason":"search_cancelled",
"time_in_nanos":188447,
"children":[
{
"name":"MultiCollector",
"reason":"search_top_hits",
"time_in_nanos":145904
}
]
}
]
}
],
"aggregations":[
]
},
{
"id":"[aUHyWwNZRPyfP3jYGYuSsg][newpinglunsearchindex][0]",
"searches":[
{
"query":[
{
"type":"BooleanQuery",
"description":"#entityID:[28683680 TO 28683680] #businessID:[1 TO 1] #isdel:[0 TO 0] #partnerID:[0 TO 0] #((checkStatus:[2 TO 2] checkStatus:[1 TO 1])~1)",
"time_in_nanos":1496860,
"breakdown":{
"score":0,
"build_scorer_count":26,
"match_count":0,
"create_weight":6743,
"next_doc":109439,
"match":0,
"create_weight_count":1,
"next_doc_count":93,
"score_count":0,
"build_scorer":1380558,
"advance":0,
"advance_count":0
},
"children":[
{
"type":"PointRangeQuery",
"description":"entityID:[28683680 TO 28683680]",
"time_in_nanos":433773,
"breakdown":{
"score":0,
"build_scorer_count":39,
"match_count":0,
"create_weight":1146,
"next_doc":7898,
"match":0,
"create_weight_count":1,
"next_doc_count":93,
"score_count":0,
"build_scorer":418940,
"advance":5575,
"advance_count":81
}
},
{
"type":"PointRangeQuery",
"description":"businessID:[1 TO 1]",
"time_in_nanos":198984,
"breakdown":{
"score":0,
"build_scorer_count":39,
"match_count":0,
"create_weight":184,
"next_doc":0,
"match":0,
"create_weight_count":1,
"next_doc_count":0,
"score_count":0,
"build_scorer":189391,
"advance":9257,
"advance_count":112
}
},
{
"type":"PointRangeQuery",
"description":"isdel:[0 TO 0]",
"time_in_nanos":101801,
"breakdown":{
"score":0,
"build_scorer_count":39,
"match_count":0,
"create_weight":174,
"next_doc":0,
"match":0,
"create_weight_count":1,
"next_doc_count":0,
"score_count":0,
"build_scorer":88680,
"advance":12814,
"advance_count":93
}
},
{
"type":"PointRangeQuery",
"description":"partnerID:[0 TO 0]",
"time_in_nanos":229277,
"breakdown":{
"score":0,
"build_scorer_count":39,
"match_count":0,
"create_weight":173,
"next_doc":0,
"match":0,
"create_weight_count":1,
"next_doc_count":0,
"score_count":0,
"build_scorer":217545,
"advance":11374,
"advance_count":145
}
},
{
"type":"BooleanQuery",
"description":"(checkStatus:[2 TO 2] checkStatus:[1 TO 1])~1",
"time_in_nanos":399909,
"breakdown":{
"score":0,
"build_scorer_count":39,
"match_count":0,
"create_weight":1723,
"next_doc":0,
"match":0,
"create_weight_count":1,
"next_doc_count":0,
"score_count":0,
"build_scorer":379347,
"advance":18644,
"advance_count":155
},
"children":[
{
"type":"PointRangeQuery",
"description":"checkStatus:[2 TO 2]",
"time_in_nanos":139999,
"breakdown":{
"score":0,
"build_scorer_count":24,
"match_count":0,
"create_weight":183,
"next_doc":0,
"match":0,
"create_weight_count":1,
"next_doc_count":0,
"score_count":0,
"build_scorer":138697,
"advance":1086,
"advance_count":8
}
},
{
"type":"PointRangeQuery",
"description":"checkStatus:[1 TO 1]",
"time_in_nanos":204555,
"breakdown":{
"score":0,
"build_scorer_count":24,
"match_count":0,
"create_weight":172,
"next_doc":0,
"match":0,
"create_weight_count":1,
"next_doc_count":0,
"score_count":0,
"build_scorer":201657,
"advance":2655,
"advance_count":46
}
}
]
}
]
}
],
"rewrite_time":7877,
"collector":[
{
"name":"CancellableCollector",
"reason":"search_cancelled",
"time_in_nanos":46525,
"children":[
{
"name":"MultiCollector",
"reason":"search_top_hits",
"time_in_nanos":38539
}
]
}
]
}
],
"aggregations":[
]
}
]
}
}

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
