### ISSUE TITLE
ingest-attachment 6.3.0 can't be installed on elk 6.3.0

### ISSUE THREAD

**Issue by xiaoxin01** [elastic/elasticsearch#31571]
Hi,

I wan't to install ingest-attachment on elk 6.3.0 but got an error.

cmd:

    bin/elasticsearch-plugin install ingest-attachment

error:
```
[=================================================] 100%??
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.security.SecurityPermission createAccessControlContext
* java.security.SecurityPermission insertProvider
* java.security.SecurityPermission putProviderProperty.BC
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Exception in thread "main" java.lang.IllegalStateException: unable to read from standard input; is standard input open and a tty attached?

```

I find an issue related:
    https://github.com/elastic/elasticsearch/pull/29359

Please help, Thanks~

**Comment by dadoonet** [comment]
Are you running that command from the command line or from a script or from docker? 

Anyway please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

**Comment by Jotschi** [comment]
@xiaoxin01 Use can use the -b flag to ignore the check if you have no tty.

```bin/elasticsearch-plugin install -b ingest-attachment```

I encountered the same error while building my docker image which includes the plugin (docker build env has no tty).

**Comment by mateuspadua** [comment]
Tks a lot
