### ISSUE TITLE
FR: Connection metadata file option

### ISSUE THREAD

**Issue by chriswhite199** [elastic/elasticsearch#31584]
**JSON Connection File**

Would it be possible to add a CLI option, similar to the `-p` PID file option, to output a connection metadata file (say JSON), with connection information (hostname, port) for the HTTP (and while it's still around / not-quite-deprecated-yet, Transport too):

`bin/elasticsearch -c/tmp/es-connection.json -p/tmp/es.pid`

```json
{
   "transport_bound_addresses": [ "127.0.0.1:9300" ],
   "http_bound_addresses": [ "127.0.0.1:9200" ]
}
```

This is particularly useful when spinning up an ES node for integration testing purposes (esp now running embedded node is not supported).

Granted, you can start the node passing in the desired ports for both HTTP and Transport, but the specific use case i'm targetting is running integration tests on a CI server, where multiple integration tests might be running in parallel - so i can't hard code a port for conflict reasons.

In my case, i'm using the `-Ehttp.port=9200-9300` CLI argument to get the first free port, but at the moment i have to parse the log file for the spun up node to extract the actual port used (which is brittle if the Logger name, `TransportClient` and `HttpServerTransport` changes, or the strings used in BoundAddress.toString() change - `bound_addresses`)

If there was a connection metadata file, then this would be much easier and certainly less brittle to future changes

For background: https://discuss.elastic.co/t/discovering-dynamic-port-assignment/137328

**Comment by jasontedor** [comment]
We have this today: you can set `node.portsfile` to `true`.

**Comment by dadoonet** [comment]
Ha! My bad. Was not aware of it. Thanks Jason!

**Comment by chriswhite199** [comment]
There's like zero documentation for this feature!

For those who stumble here in the future - I had to [search the source](https://github.com/elastic/elasticsearch/blob/237650e9c054149fd08213b38a81a3666c1868e5/server/src/main/java/org/elasticsearch/node/Node.java#L878) to find it and then ascertain that the file will be written to the logs directory under files named `http.port` and `transport.port`, and those files should contain newline delimited list of address:port pairs, for example (noting that if you run with the default network.host you'll get both ipv4 and v6 addresses listed):

```
[::1]:9200
127.0.0.1:9200
```

**Comment by jasontedor** [comment]
> There's like zero documentation for this feature!

It's intentional, it's for testing only.
