### ISSUE TITLE
SQL: Align class packages in sql-proto and shared-proto projects

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#31593]
Looks like a left-over from the various class movements:
1. the package name of the `sql-proto` project is `sql.plugin`. This is incorrect and misleading since that's the package of the server. It should be changed to something more appropriate like `sql.proto` or (to avoid a cycle with 2 below) `sql.proto.action.

2. the package name of the shared-proto project is `sql.proto`. Due to 1 above, it should be `sql.proto.shared` or (since that creates a cycle between `proto.shared` and `proto`) to `sql.shared.proto` or `sql.proto.common` .

That is, the package name should properly convey the project name and the hierarchy (`sql-proto` depends on `shared-proto` not vice versa) without splitting an existing package name.

**Comment by imotov** [comment]
I think we can kill the word `shared` from the project names and package names. Basically we can
1. rename project `sql-proto`-> `sql-action`, 
2. rename package `sql.plugin` to `sql.action` (while moving CliFormatter to `sql.client.common`)
3. rename project `sql-shared-client` -> `sql-client`
4. rename package `sql.shard.client` to `sql.client`
5. rename `sql-shared-proto` -> `sql-proto` (leave `sql.proto` there as is)

**Comment by costin** [comment]
+1
I would move `CliFormatter` either to `sql.cli.common` (since it's not used in other clients) or just leave it in `sql.action` for the time being.
