### ISSUE TITLE
Document the `node.portsfile` option

### ISSUE THREAD

**Issue by chriswhite199** [elastic/elasticsearch#31598]
Document the `node.portsfile` option, as this is exceptionally useful for integration tests when spinning up a node.

Origin: https://github.com/elastic/elasticsearch/issues/31584#issuecomment-400545270

**Comment by danielmitterdorfer** [comment]
Marked as ":Core/Build" because it is needed in the context of tests.

**Comment by jasontedor** [comment]
I do not think that we should document this functionality since it's for testing only and we want to reserve the right to change it at any time.
