### ISSUE TITLE
OAuth2 / OIDC Realm

### ISSUE THREAD

**Issue by joshbressers** [elastic/elasticsearch#31590]
We need an OAuth2 / Open ID Connect realm.

Kibana has an issue for this
https://github.com/elastic/kibana/issues/18189

**Comment by whatisnormal** [comment]
Any update on this?

**Comment by cpmoore** [comment]
It's available now in 7.2
https://www.elastic.co/guide/en/elastic-stack-overview/current/oidc-guide-authentication.html

Be aware that your client id cannot contain special characters (at least I know of / and : for sure)
See #43709

**Comment by gwbrown** [comment]
This should have been closed a long time ago; as noted above this functionality is long since available in Elasticsearch.
