### ISSUE TITLE
Make possible to enforce path-style access method to buckets in S3 client settings

### ISSUE THREAD

**Issue by akolosov-a** [elastic/elasticsearch#31608]
Hi,

We use [Minio](https://www.minio.io/) as an ES snapshots repository and it would be easier if it was possible to control the method (DNS- or Path-style) used by AWS S3 client inside the repository-S3 plugin to access the buckets. 

The ES repository-S3 plugin doesn't specify pathStyle setting when instantiates the AWS S3 client, so the client auto-detects that DNS-style access method should be used. Minio supports DNS-style access method, but in our case it's impossible to maintain DNS-entries for the buckets. 

The solution proposed in #30752 to use IP-address as an endpoint doesn't suit us too for number of reasons (at least it's not an appropriate solution when Minio is clustered).

The lacking setting actually already existed, but was deprecated by #24143 and removed by #24445 during the reorganisation of repository/client settings.

**Comment by bleskes** [comment]
@tlrx any thoughts here?

**Comment by Battleroid** [comment]
Kind of need the ability to enforce path style access. Without it, it basically full stop halts our ability to upgrade for now as we don't have a way to backup to our ceph/minio clusters. The IP solution won't work for us as well.

**Comment by mitchellmaler** [comment]
I just ran into this same issue. Our minio is not set up with dns style and is running in kubernetes with a single IP. Path style is needed to be enforced.

**Comment by yokhahn** [comment]
Yep, minio in a kubernetes cluster trying to identify the service with DNS, stops working because of this too.
