### ISSUE TITLE
Rest high-level client: add support for document _count

### ISSUE THREAD

**Issue by mrdjen** [elastic/elasticsearch#31602]
Relates to #27205 
See https://github.com/elastic/elasticsearch/issues/27205#issuecomment-400455374
Mention: @javanna

**Comment by danielmitterdorfer** [comment]
As far as I followed the conversation in the other ticket you plan to create a PR that adds support for said operation. In that case we don't need a separate issue and you can just mention the meta-issue #27205 in your PR.

If you could confirm my assumption then I think we can close this ticket.

**Comment by mrdjen** [comment]
Yes, there will be PR with support for the document _count.
Still looking at #27205 there are at least 30 other issues referencing it (same as this one).

**Comment by danielmitterdorfer** [comment]
> there are at least 30 other issues referencing it

Those are the respective PRs that implement a feature so they are easier to find. We'll take care that your PR is linked there as well once it is up.

So I'll close this issue as it is fine that you just raise your PR once you are ready and reference #27205 there. Thanks!

**Comment by mrdjen** [comment]
OK!
