### ISSUE TITLE
SQL XPack should allow index names to be escaped.

### ISSUE THREAD

**Issue by ahazelwood** [elastic/elasticsearch#31610]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.0, Build: default/deb/424e937/2018-06-11T23:38:03.357887Z, JVM: 1.8.0_171

**Plugins installed**: []
**JVM version** (`java -version`):"1.8.0_171

**OS version** (`uname -a` if on a Unix-like system): 4.4.0-128-generic

I am issuing a SQL query against indexes that have dashes in the names which is perfectly legal from a elasticsearch standpoint.  However this is invalid from a sql standpoint and errors while parsing.  There should be a way to escape index names (potentially something like [index-name] ).

Query is as follows:
`{ "query": "SELECT * FROM news-20180620", "fetch_size": 5 }`

Error:
`{
    "error": {
        "root_cause": [
            {
                "type": "x_content_parse_exception",
                "reason": "[1:12] [sql/query] failed to parse field [query]"
            }
        ],
        "type": "x_content_parse_exception",
        "reason": "[1:12] [sql/query] failed to parse field [query]",
        "caused_by": {
            "type": "json_parse_exception",
            "reason": "Unrecognized character escape '-' (code 45)\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@8dfc1ae; line: 1, column: 33]"
        }
    },
    "status": 400
}`

**Comment by costin** [comment]
There is the standard SQL way - using double quotes:

`SELECT * FROM "news-20180620"`

See also the docs:
https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-syntax-select.html#sql-syntax-from

**Comment by ahazelwood** [comment]
Thanks.  I missed that little point in reviewing the documentation.
