### ISSUE TITLE
Fix range and wildcard queries on type-field for single-type indices

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#31632]
This comes from a discussion with @jpountz after looking at https://github.com/elastic/elasticsearch/issues/31476. 
Range and wildcard queries throw an error when run against a `_type` field for single-type indices in 6.x and most likely also
in master. While `_type` is deprecated, it might still we worth fixing these for the time being. In the other hand it seems to be a
rare use-case to query the `_type` field with a `range` query, so I'd probably discuss this before diving deeper into it.

**Comment by cbuescher** [comment]
Talked about this in the group, while supporting `range`queries on single type indices seems a bit of an esoteric usecase, supporting wildcards seems desirable to do. Unfortunately this seems to be the harder case technically, so there are no clear ideas of how to do this. Marking this as "adoptme" regardless.

**Comment by jtibshirani** [comment]
@cbuescher I'm wondering if it’s worth still keeping this open, or if we should close it. In 7.0 it is deprecated to use `_type` in searches, and I think wildcard queries on `_type` are rare.

**Comment by cbuescher** [comment]
@jtibshirani agreed, since we are moving close to 7.0 and there hasn't been much outside need to fix this since when I opened it last year, I think we can close the issue. If this limitation gets raised from a user side we can still re-evaluate considering the context.
