### ISSUE TITLE
ES 6.3: X-Pack Licence is "Expired" on New Install

### ISSUE THREAD

**Issue by JonathanHourany** [elastic/elasticsearch#31639]
**Elasticsearch version**: 6.3

**JVM version** (`java -version`): 1.8.0_171

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-128-generic x86_64)

**Description of the problem including expected versus actual behavior**:

Following the steps provided at [Install Elasticsearch with Debian Package](https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.htmlh) I downloaded and installed the DEB files for both Elasticsearch 6.3 and Kibana. I continued following the steps and at some point (I'm no longer able to find them) the steps recommended using `bin/elasticsearch-setup-passwords interactive` to setup passwords across packages. On running this script I got the following error

```
Unexpected response code [403] from calling GET http://127.0.0.1:9200/_xpack/security/_authenticate?pretty
It doesn't look like the X-Pack security feature is available on this Elasticsearch node.
Please check if you have installed a license that allows access to X-Pack Security feature.

ERROR: X-Pack Security is not available.`
```
Following the trail I sent out a `GET` to `_xpack/security/_authenticate

```
GET "http://127.0.0.1:9200/_xpack/security/_authenticate?pretty"
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "current license is non-compliant for [security]",
        "license.expired.feature" : "security"
      }
    ],
    "type" : "security_exception",
    "reason" : "current license is non-compliant for [security]",
    "license.expired.feature" : "security"
  },
  "status" : 403
}
```

And querying the X-Pack licence API get me this:

```
GET "http://localhost:9200/_xpack/license"{
  "license" : {
    "status" : "active",
    "uid" : "a5100a6a-cce1-4d51-b197-97fc2304e50a",
    "type" : "basic",
    "issue_date" : "2018-06-20T22:13:12.053Z",
    "issue_date_in_millis" : 1529532792053,
    "max_nodes" : 1000,
    "issued_to" : "elasticsearch",
    "issuer" : "elasticsearch",
    "start_date_in_millis" : -1
  }
}
````
It looks like X-Pack thinks the licence is expired for some reason. Like the `.deb` version might be shipping with expired licenses. There's a thread going on the [Elasticsearch forums](https://discuss.elastic.co/t/elasticsearch-6-3-x-pack-and-remote-connection-doesnt-work/136618) with other useres experiancing this issue.

**Comment by jasontedor** [comment]
A basic license is not entitled to security features. To try out security you need to use a trial license or obtain a subscription.

**Comment by JonathanHourany** [comment]
Is it not in 6.3? It defaults to true
https://www.elastic.co/guide/en/elastic-stack-overview/6.3/installing-xpack.html

**Comment by jasontedor** [comment]
Security is in 6.3. It’s not available with a basic license. You can see the [license levels](https://www.elastic.co/subscriptions) and what a basic license provides. Yes it is enabled by default, but the functionality is simply not available with a basic license.

**Comment by Karmadon** [comment]
so much greedy

**Comment by weyderfs** [comment]
So how to work around the problem? I'm install ELK stack 6.3 and can't login in Kibana because this...

**Comment by rafarnaez** [comment]
> So how to work around the problem? I'm install ELK stack 6.3 and can't login in Kibana because this...

This could help to those who install kibana elasticsearch without xpack as basic / free license

https://aboullaite.me/secure-kibana-keycloak/
