### ISSUE TITLE
Issue with  QueryStringQuery regular expression pattern

### ISSUE THREAD

**Issue by shashanka981** [elastic/elasticsearch#31664]
ES is upgraded to 5.6.9. the following query which used to return hits in 2.4 version doesnt return anymore.Assume that there is a field 'PlanID' whose value is "Plan1005". In 5.6.9, this works only when search string is lowercased "/plan1005/", but not with "/PLAN1005/"

{
  "from": 0,
  "size": 20,
  "query": {
    "bool": {
      "must": {
        "query_string": {
          "query": "PlanID: /Plan1005/",
          "default_field": "PlanID",
          "default_operator": "and",
          "allow_leading_wildcard": true,
          "analyze_wildcard": true
        }
      }
    }
  },
  "stored_fields": "*"
}

**Comment by dadoonet** [comment]
I see you asked this question on discuss.elastic.co which is the right place to ask.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!
