### ISSUE TITLE
Show JVM and OS info in Monitoring

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#31672]
**Describe the feature**: It'd be great if we showed the JVM and OS version for a node in the Monitoring dashboards.

As it is now you can get that from calling `_nodes` but it seems like it would be super handy to have exposed here. That way you could see if there were discrepancies, and we could even add warnings if we found drift.

Perhaps in the node overview page?

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
