### ISSUE TITLE
Assemble as SNAPSHOT

### ISSUE THREAD

**Issue by talexu** [elastic/elasticsearch#31677]
**Describe the feature**: Assemble

**Elasticsearch version** (6.3.0):

**Plugins installed**: []

**JVM version** (1.10):

**OS version** (Mac OS):

**Description of the problem including expected versus actual behavior**:
Hi all, I am new to ES and trying to assemble from source code.
I got elasticsearch-6.3.0-SNAPSHOT.zip in distribution folder after I run ./gradlew assemble from root path of the repository.

My question is how can I assemble a release package without the SNAPSHOT suffix?

**Comment by javanna** [comment]
hi @talexu we reserve github issues for confirmed bug reports and feature requests. Could you please ask your question in our discuss forum at https://discuss.elastic.co/ ? Thanks!
