### ISSUE TITLE
Extra _cat/tasks URI paths not accepted

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch#31673]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.0

**Plugins installed**: X-Pack

**JVM version** (`java -version`): 1.8.0_144

**OS version** (`uname -a` if on a Unix-like system): Elastic Cloud

**Description of the problem including expected versus actual behavior**: If you run `_cat/tasks/$TASKID` it complains that it's not a valid index.

**Steps to reproduce**:

 1. Generate a task that will take a while, I was doing a reindex.
 2. Take the task ID and call `_cat/tasks/$TASKID`
 3. It'll respond with `index_not_found_exception`

**Provide logs (if relevant)**:
eg;
```
GET _cat/tasks/eEZluOL6Q-Of-wE0GMriSA:14490789

{
  "error": {
    "root_cause": [
      {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_expression",
        "resource.id": "_cat",
        "index_uuid": "_na_",
        "index": "_cat"
      }
    ],
    "type": "index_not_found_exception",
    "reason": "no such index",
    "resource.type": "index_expression",
    "resource.id": "_cat",
    "index_uuid": "_na_",
    "index": "_cat"
  },
  "status": 404
}
```

It seems like we should return just the data about that specific task, as that is what `_cat/indices/$INDEXNAME` would do for eg.

**Comment by martijnvg** [comment]
So there is no path for that particular url registered, just for `/_cat/tasks`. The error is confusing, but since we should aim to support this particular usage, I have labelled this is an enhancement instead of a bug.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
