### ISSUE TITLE
License issue after upgrade to 6.3.0

### ISSUE THREAD

**Issue by iahmad-khan** [elastic/elasticsearch#31686]
Does elasticsearch still requires basic license after upgrading to 6.3.0

 I read somewhere in elastic announcements , that basic license will no longer bee needed for free features in new version. 

```
Your basic license has expired
Your license expired on June 26, 2018 5:02:25 PM
```

posting new license:

`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Installing basic licenses is no longer allowed. Use the POST /_xpack/license/start_basic API to install a basic license that does not expire."}],"type":"illegal_argument_exception","reason":"Installing basic licenses is no longer allowed. Use the POST /_xpack/license/start_basic API to install a basic license that does not expire."},"status":400}`

POST /_xpack/license/start_basic:

```
{
  "acknowledged": true,
  "basic_was_started": false,
  "error_message": "Operation failed: Current license is basic."
}
```

**Comment by jasontedor** [comment]
The behavior here is correct. You still need a basic license yet you can use one that is issued by the server itself. Please use the start basic API as indicated in the message here and you will have a non-expiring basic license that entitles you to use the basic-licensed features within the default distribution.

**Comment by dcvtruong** [comment]
Hi @jasontedor,

I'm trying to test out the Watcher and the current license is basic for elasticsearch 6.4.  Unfortunately, the Watcher (Alerting) is not enable for 'basic' license.  Hoping there is trial license type I can use to test the Watcher and demo it to my team.  I try to update the license to non basic type to enable Watcher with no success.

Thanks.
