### ISSUE TITLE
6.3.0 Release Notes for Updatable Secure Settings Incorrect

### ISSUE THREAD

**Issue by scottsom** [elastic/elasticsearch#31695]
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-6.3.0.html

The 6.3.0 release notes mention a few features that as far as I can tell didn't actually make it into the release, for example:

> Update s3 secure settings #28517
> Update ec2 secure settings #29134

It seems these PRs were merged into a feature branch then eventually made their way into 7.0.0 & 6.4.0 via #29135

**Comment by albertzaharovits** [comment]
@scottsom Your assessment is correct.
Those PRs where against a feature branch and had version labels, which they shouldn't have had.
I have removed the version labels on these PRs. The merge https://github.com/elastic/elasticsearch/pull/31383 and backport https://github.com/elastic/elasticsearch/pull/31481 PRs for the [reload-secure-store-action](https://github.com/elastic/elasticsearch/tree/reload-secure-store-action) feature branch are the only ones keeping the version labels.

@lcawl Apologies for the blunder, if there's anything else I can do to remedy, such as regenerating the release notes, please let me know.

**Comment by lcawl** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/31771
