### ISSUE TITLE
why merge thread num set a aggressive-style which work well with SSD?

### ISSUE THREAD

**Issue by cyberdak** [elastic/elasticsearch#31709]
now es provide a index level merge thread num set , but by default it is work for SSD.But multi-thread merge on spinning platter drives will cause a high io load, in the badest case ,it will cause the system down because linux io timeout(xxx blocked for more the 120 seconds). 

I think the **default value** should set to **1** , if the cluster deploy on SSD, SA can change it to `Math.max(1, Math.min(4, Runtime.getRuntime().availableProcessors() / 2))` by some switch.

**Comment by jasontedor** [comment]
We agree with you that having a large number of merge threads on a spinning disk is bad. However, we think that SSDs are common enough these days that our default should be tuned to that use-case. We [document](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/index-modules-merge.html#merge-scheduling) that if you're on spinning disks then this setting needs to be tuned down to one.

Please note in the future that we prefer for user questions to be addressed on the [forums](https://discuss.elastic.co). This allows us to use GitHub for verified bug reports, feature requests, and pull requests and we put this in our issue template. If you have follow-up questions, would you please use the [forum](https://discuss.elastic.co)?
