### ISSUE TITLE
Java High Level Rest Bulk API with OpType.CREATE not backward compatible (6.2.2 -> 2.4.4)

### ISSUE THREAD

**Issue by joelstewart** [elastic/elasticsearch#31704]
**Elasticsearch version** (`bin/elasticsearch --version`):  Java High Level Rest Client 6.2.2

**Plugins installed**: []

**JVM version** (`java -version`): jdk1.8

**OS version** (`uname -a` if on a Unix-like system): win

**Description of the problem including expected versus actual behavior**:

Using a 6.2.2 High Level Rest Client,  code snippet:

`	IndexRequest createRequest = new IndexRequest("index", "message", "id")			.opType(DocWriteRequest.OpType.CREATE).source( jsonstring , XContentType.JSON);`

- works when using DocWriteRequest.OpType.INDEX when calling 6.2.2 cluster
- works when using DocWriteRequest.OpType.INDEX when calling 2.4.4 cluster
- works when using DocWriteRequest.OpType.CREATE when calling 6.2.2 cluster
- FAILS when using DocWriteRequest.OpType.CREATE when calling 2.4.4 cluster

with exception:

`
 org.elasticsearch.client.ResponseException: method [POST], host [http://localhost:9200], URI [/_bulk?timeout=1m], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: illegal version value [-4] for version type [INTERNAL];"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: illegal version value [-4] for version type [INTERNAL];"},"status":400}
`

**Steps to reproduce**:
snippet provided

**Provide logs (if relevant)**:
exception provided.

**Comment by jasontedor** [comment]
The high level REST client is not intended to be BWC to 2.x.
