### ISSUE TITLE
Can’t change settings for an index with a geo_shape field using term strategy

### ISSUE THREAD

**Issue by tristanbuckner** [elastic/elasticsearch#31707]
**Elasticsearch version**: 6.3.0

**Plugins installed**: Vanilla found.io installation

**JVM version**: Vanilla found.io installation

**OS version**: Vanilla found.io options

**Description of the problem including expected versus actual behavior**:
When creating an index with a field of type geo_shape that uses the term strategy, I've observed some strange behaviors (this is in hosted 6.3.0).

Creating an index with a geoshape field set to term strategy takes just over 30 seconds (feeling very much like a timeout), but does ultimately report success. However, if you subsequently try to change any settings, you get a mapper parsing error about the original supposedly successfully created mapping having an unsupported points_only field (whether or not not you explicitly specified it, or just got it from using the term strategy).

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create mapping 
```
PUT /example
{
  "mappings": {
    "doc": {
      "properties": {
        "location": {
          "type": "geo_shape",
          "tree": "quadtree",
          "precision": "10m",
          "strategy": "term"
        }
      }
    }
  }
}
```
 2. Change a setting
 ```
PUT /example/_settings
{
 "settings": {"refresh_interval": "-1"} 
}
```
Response 
```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Mapping definition for [location] has unsupported parameters:  [points_only : true]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [doc]: Mapping definition for [location] has unsupported parameters:  [points_only : true]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "Mapping definition for [location] has unsupported parameters:  [points_only : true]"
    }
  },
  "status": 400
}
```

**Comment by imotov** [comment]
@tristanbuckner could you run the following command to see if this index got any shards assigned?
```
GET /_cat/shards/example
```

**Comment by tristanbuckner** [comment]
@imotov Looks like they didn't.
```
example 4 p UNASSIGNED    
example 4 r UNASSIGNED    
example 3 p UNASSIGNED    
example 3 r UNASSIGNED    
example 1 p UNASSIGNED    
example 1 r UNASSIGNED    
example 2 p UNASSIGNED    
example 2 r UNASSIGNED    
example 0 p UNASSIGNED    
example 0 r UNASSIGNED
```

**Comment by imotov** [comment]
OK, that makes sense then. I am going to open PR with a fix in a bit. Unfortunately, I cannot think of any workaround at the moment besides not using `"strategy": "term"` until the issue is fixed. Sorry about that.
