### ISSUE TITLE
Reconsider the hard character limit in Painless compiler

### ISSUE THREAD

**Issue by oersted** [elastic/elasticsearch#31705]
Executing a query with a  Painless script that is too long returns the following error message.

`Scripts may be no longer than 16384 characters.  The passed in script is ____ characters.  Consider using a plugin if a script longer than this length is a requirement.`

Apparently this cap is hard-coded as a constant in the compiler code. I understand the advice for keeping scripts short, they are not designed to be abused. However, there are cases where writing a plugin may not be an option or may not be desirable. Writing a Java plugin is more involved and, for example, AWS Elasticsearch doesn't support non pre-installed plugins.

It happens that I have fallen into this narrow case where I do need to write a long Painless script, and I'm having to use hackish tricks to keep it under the limit. Having a hard cap, although understandable, seems a bit arbitrary.

I would like to open a discussion about this issue and ask that it is at least set as a configuration option if serious internal conflicts don't come up in the discussion. I would also appreciate to hear some arguments against using long Painless (update) scripts, to make sure I'm not doing a serious mistake.

Thanks!

**Comment by jasontedor** [comment]
Thanks for opening the issue and sharing your thinking with us. We have an open issue for this though: #23209. I will close this issue as a duplicate but would you mind sharing your thoughts on the existing issue?

**Comment by oersted** [comment]
I see, sorry for the trouble, I tried to find a duplicate before posting. Thanks.

**Comment by jasontedor** [comment]
@oersted It's no trouble at all.
