### ISSUE TITLE
AsyncAfterWriteAction error handling improvement

### ISSUE THREAD

**Issue by vladimirdolzhenko** [elastic/elasticsearch#31716]
There are several small problems related to performing `AsyncAfterWriteAction`:

- [ ] any exceptions in `indexShard.sync` could be swallowed - as it could be done asynchronously and synchronously - at the moment `listener` could not be registered. #31755 
- [ ] be single node failure tolerant - even if `AsyncAfterWriteAction` fails on primary -  shard has to be marked as failed; primary failure has to be handled as any other replica failure i.e. request should not fail  if there is at least one successfully performed shard (replica or primary) #31969

**Comment by bleskes** [comment]
@vladimirdolzhenko can you add a bullet point for (locally) failing shard if you have an exception on sync? 

Also, can you clarify what you mean with the struck through line (or just remove it)?

**Comment by arteam** [comment]
#31755 and #31969 are closed
