### ISSUE TITLE
Add unit conversion ingest node processor

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#31737]
**Describe the feature**:
Working with Filebeat modules, I have come across several instances where I need to convert seconds to millis and kilobytes/megabytes/gigabytes to bytes. While the script processor is available to perform such unit conversions, a dedicated processor for this task would facilitate the development of modules greatly by eliminating the need to write and rewrite them in painless. It might look something like this:

```
{
  "units": {
    "field": "duration_sec",
    "from": "seconds",
    "to": "milliseconds"
  }
}
```

Then use `rename` to adjust the field name accordingly:
```
{
  "rename": {
    "field": "duration_sec",
    "target_field": "duration_ms"
  }
}
```

Even better might a processor that accepts a conversion factor or possibly formula so it could be applied to any unit of measure; e.g., temperature, speed, energy, leagues, etc. 

```
{
  "units": {
    "field": "duration_sec",
    "factor": .001,
    "target_field": "duration_ms"
  }
}
```

**Comment by inqueue** [comment]
Relates to https://github.com/elastic/elasticsearch/issues/31244.

**Comment by jakelandis** [comment]
Would you expect all these types to need to convert numeric type to numeric type ? 

> Even better might a processor that accepts a conversion factor or possibly formula

That sounds alot like a general purpose math processor. Would something like this satisfy your use case(s) ?

```
{
  "math": {
    "field": "duration_sec",
    "operation" : "divide"
    "by": 1000,
    "target_field": "duration_ms"
  }
}
```
It could be expanded (if needed) for user defined functions. 

_related: I just submitted a PR for converting human readable byte string to their byte value. (e.g 1kb -> 1024)_

**Comment by rjernst** [comment]
> While the script processor is available to perform such unit conversions, a dedicated processor for this task would facilitate the development of modules greatly by eliminating the need to write and rewrite them in painless

Can you show what script doing conversion looks like, for comparison against your other suggested examples here?

**Comment by ruflin** [comment]
Linking https://github.com/elastic/elasticsearch/issues/31244 here as in case we have such a processor, it should work well together with a potential duration type in this example.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
