### ISSUE TITLE
Folder with no group execute permissions in Elasticsearch config path causes failure to start

### ISSUE THREAD

**Issue by danleerunk** [elastic/elasticsearch#31741]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.0

**Plugins installed**: []

**JVM version** (`java -version`): `openjdk version "1.8.0_171"`

**OS version** (`uname -a` if on a Unix-like system): CentOS 7.4.1708, 3.10.0-693.11.6.el7.x86_64

**Description of the problem including expected versus actual behavior**:
Elasticsearch fails to start if a directory exists in the configuration path (e.g. `/etc/elasticsearch/`) when that directory is both non-empty, and the directory is not configured with group execute permissions.

**Steps to reproduce**:

1. Create a directory in the Elasticsearch configuration path (`mkdir test` in `/etc/elasticsearch/`)
2. Add content to that directory (`touch test/a_file`)
3. Ensure group permissions on the `test` folder do not include execute (`chmod g-x test`)
4. Attempt to start Elasticsearch

**Provide logs (if relevant)**:
The system journal will shows the following on failure:
```
Jun 30 17:04:24 localhost.localdomain elasticsearch[16270]: Exception in thread "main" org.elasticsearch.bootstrap.BootstrapException: java.nio.file.AccessDeniedException: /etc/elasticsearch/test/a_file
Jun 30 17:04:24 localhost.localdomain elasticsearch[16270]: Likely root cause: java.nio.file.AccessDeniedException: /etc/elasticsearch/test/a_file
```

Discovered this with @jpcarey - let us know if any additional information is required.

**Comment by danleerunk** [comment]
Tagging @tvernum here too since we had a bit of discussion on this!

**Comment by rjernst** [comment]
Is there a stacktrace in the elasticsearch log? This seems expected to me. This is simply how linux filesystem permissions work. `/etc/elasticsearch` is meant to be controlled by elasticsearch, not filled with arbitrary things.

**Comment by gwbrown** [comment]
@danleerunk Can you provide more information on if there are errors in the Elasticsearch log, and why you have a need for this to work?

**Comment by danleerunk** [comment]
Hey @gwbrown, it's been a while but I gave this another shot - as expected, it failed, and I did not see anything related to the failure in any of the Elasticsearch logs. I totally missed @rjernst's observation back in the day; given this is expected Linux behavior, I'll go ahead and close!
