### ISSUE TITLE
After a full cluster restart, all replica shards come to be unassigned.

### ISSUE THREAD

**Issue by zhaojianyong** [elastic/elasticsearch#31763]
Elasticsearch version 6.2.4 with xpack.
JDK 1.8
"number_of_nodes": 6,
"number_of_data_nodes": 3
"active_primary_shards": 379
"active_shards": 758

I stop most index writes, and follow the steps of  "https://www.elastic.co/guide/en/elasticsearch/reference/6.2/restart-upgrade.html" to stop my elasticsearch cluster.
After the full cluster restart, all replica shards come to be unassigned. And it cost so much time before cluster change to green.

With some try, i found if cluster.routing.rebalance.enable set to be "none", the unassigneds will not happen. And the full cluster restart will be very fast. 

But cluster.routing.rebalance.enable do not to be mentioned in restart-upgrade doc.

**Comment by javanna** [comment]
heya @elastic/es-distributed is this just a doc issue or something else?

**Comment by bleskes** [comment]
@zhaojianyong do you mind clarifying a bit more about what you did? the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/restart-upgrade.html) say to set `cluster.routing.rebalance.enable` to `none`. Note that docs also use `persistent` setting. Maybe you used `transient` by mistake?

**Comment by zhaojianyong** [comment]
@bleskes the docs say cluster.routing.**allocation**.enable should be set to "none" and i did it . but say nothing about cluster.routing.**rebalance**.enable.

**Comment by bleskes** [comment]
@zhaojianyong sorry for the confusion, I misread your ticket. The default value for `cluster.routing.allocation.allow_rebalance` is `indices_all_active` (see [here](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/shards-allocation.html#_shard_rebalancing_settings) which means that rebalancing should only start once one all shards are allocated and the cluster is green. Can you write a more detailed description of what your were doing?

**Comment by DaveCTurner** [comment]
Superficially similar to https://github.com/elastic/elasticsearch/issues/30162 which we moved to https://discuss.elastic.co/t/ability-to-stop-and-start-a-cluster-without-shard-movement/134375 but we didn't get enough information to proceed.

**Comment by DaveCTurner** [comment]
We haven't yet received a more detailed description of the issue, so I think this can be closed.
