### ISSUE TITLE
[Docs] Transform not listed as request body list

### ISSUE THREAD

**Issue by yaronp68** [elastic/elasticsearch#31764]
https://www.elastic.co/guide/en/elasticsearch/reference/6.3/watcher-api-put-watch.html

**Comment by javanna** [comment]
Hi @yaronp68 can you clarify ? Did you mean to send a PR rather than opening an issue?

**Comment by yaronp68** [comment]
Hi @javanna ,
I meant reporting an issue. The docs seems to be missing the reference to transform as a top level watch object. see the atta
![image](https://user-images.githubusercontent.com/1367657/42228763-a822839e-7edc-11e8-9524-4527ba8320a4.png)
ched screenshot

**Comment by debadair** [comment]
[doc-issue-triage]
