### ISSUE TITLE
Expose index uuid in _stats endpoint

### ISSUE THREAD

**Issue by ruflin** [elastic/elasticsearch#31791]
To collect metrics about the Elasticsearch indices Metricbeat calls the `/_stats` endpoint. Inside the object `"indices" : {` all indices are listed with its names. The data that is missing inside is the index uuid. It can be fetched by calling `GET /index-name` and then can be found under `uuid`. Having to make a separate request for each index to fetch the identifier is not an optimal solution.

The uuid is important for the following reasons:

* The same index name can exist in multiple clusters. Beats can collect data from multiple clusters into a single monitoring cluster.
* An index can be deleted and a new one created with the same name. In this case only the UUID is different.
* With cross cluster replication matching indices from 2 different clusters with the same uuid could become even more interesting: https://github.com/elastic/elasticsearch/issues/30086

NOTE: The _stats endpoint also currently does not expose the `cluster_uuid` and we fetch it in a separate call.

**Comment by rjernst** [comment]
We discussed this in FixItThursday and it sounds reasonable and should be relatively easy to do. I'm marking this as adopt me for anyone to pick up.

**Comment by ruflin** [comment]
Thanks, great to hear.

**Comment by original-brownbear** [comment]
Opened https://github.com/elastic/elasticsearch/pull/31871 for this one

**Comment by ruflin** [comment]
@original-brownbear Thanks for making this happen.
@ycombinator FYI
