### ISSUE TITLE
Your repository is broken *again*

### ISSUE THREAD

**Issue by mirabilos** [elastic/elasticsearch#31799]
I cannot install Elasticsearch on Debian stable (9 “stretch”). This precise way used to work in Debian oldstable (8 “jessie”), which is however out of normal security support now and thus not suitable for new setups. (Unfortunately, we still need a 2.x Elasticsearch to mirror precisely the setup at the customer’s site.)

    root@HOSTNAME:~ # cat /etc/apt/sources.list.d/elasticsearch.list
    deb https://packages.elastic.co/elasticsearch/2.x/debian stable main
    root@HOSTNAME:~ # apt-get update
    Hit:1 http://debs.tarent.de stretch InRelease
    Ign:2 http://mirror.lan.tarent.de/debian stretch InRelease
    Hit:3 http://mirror.lan.tarent.de/debian-security stretch/updates InRelease
    Hit:4 http://mirror.lan.tarent.de/debian stretch-updates InRelease
    Hit:5 http://mirror.lan.tarent.de/debian stretch-backports InRelease
    Hit:6 http://mirror.lan.tarent.de/debian stretch Release
    Ign:7 https://packages.elastic.co/elasticsearch/2.x/debian stable InRelease
    Hit:8 http://security.eu.debian.org/debian-security stretch/updates InRelease
    Ign:9 https://packages.elastic.co/elasticsearch/2.x/debian stable Release
    Ign:10 https://packages.elastic.co/elasticsearch/2.x/debian stable/main all Packages
    Ign:11 https://packages.elastic.co/elasticsearch/2.x/debian stable/main amd64 Packages
    Ign:13 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-en
    Ign:14 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-de
    Ign:15 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-de_DE
    Ign:10 https://packages.elastic.co/elasticsearch/2.x/debian stable/main all Packages
    Ign:11 https://packages.elastic.co/elasticsearch/2.x/debian stable/main amd64 Packages
    Ign:13 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-en
    Ign:14 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-de
    Ign:15 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-de_DE
    Ign:10 https://packages.elastic.co/elasticsearch/2.x/debian stable/main all Packages
    Ign:11 https://packages.elastic.co/elasticsearch/2.x/debian stable/main amd64 Packages
    Ign:13 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-en
    Ign:14 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-de
    Ign:15 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-de_DE
    Ign:10 https://packages.elastic.co/elasticsearch/2.x/debian stable/main all Packages
    Ign:11 https://packages.elastic.co/elasticsearch/2.x/debian stable/main amd64 Packages
    Ign:13 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-en
    Ign:14 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-de
    Ign:15 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-de_DE
    Ign:10 https://packages.elastic.co/elasticsearch/2.x/debian stable/main all Packages
    Ign:11 https://packages.elastic.co/elasticsearch/2.x/debian stable/main amd64 Packages
    Ign:13 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-en
    Ign:14 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-de
    Ign:15 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-de_DE
    Ign:10 https://packages.elastic.co/elasticsearch/2.x/debian stable/main all Packages
    Err:11 https://packages.elastic.co/elasticsearch/2.x/debian stable/main amd64 Packages
    
    Ign:13 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-en
    Ign:14 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-de
    Ign:15 https://packages.elastic.co/elasticsearch/2.x/debian stable/main Translation-de_DE
    Reading package lists... Done
    W: The repository 'https://packages.elastic.co/elasticsearch/2.x/debian stable Release' does not have a Release file.
    N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
    N: See apt-secure(8) manpage for repository creation and user configuration details.
    E: Failed to fetch https://packages.elastic.co/elasticsearch/2.x/debian/dists/stable/main/binary-amd64/Packages
    E: Some index files failed to download. They have been ignored, or old ones used instead.
    100|root@HOSTNAME:~ # apt-cache policy elasticsearch
    N: Unable to locate package elasticsearch

As you can see, the repository is plain invalid.

**Comment by dliappis** [comment]
@mirabilos Note that you can always directly the latest 2.x package using the links mentioned in https://www.elastic.co/guide/en/elasticsearch/reference/2.4/_installation.html

**Comment by mirabilos** [comment]
@dliappis I downloaded the file manually using the webbrowser now, but that’s of course no solution (especially not for a semiautomated installation).

**Comment by tomcallahan** [comment]
Hi,

I have reached out to our internal infrastructure team and will keep you apprised.  Thanks for the report.

**Comment by tomcallahan** [comment]
Hi @mirabilos did you install our signing key as outlined [here](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/setup-repositories.html#_apt)

**Comment by mirabilos** [comment]
Tom Callahan dixit:

>Hi @mirabilos did you install our signing key as outlined
>[here](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/setup-repositories.html#_apt)

Yes, of course. (Full disclosure: I’m a proper Debian Developer…)

As I said, the entire procedure used to work on Debian jessie.

**Comment by tomcallahan** [comment]
@mirabilos both a colleague and I have tried to reproduce but we could not... perhaps you ran into some transient error?  I tried reproducing using Docker.  Let me know if you see something incorrect, I get a successful build with the below:

```
FROM debian:9

RUN apt-get update && \
  apt-get install -y wget gnupg apt-transport-https && \
  echo "deb https://packages.elastic.co/elasticsearch/2.x/debian stable main" > /etc/apt/sources.list.d/elasticsearch-2.x.list && \
  wget -qO - https://packages.elastic.co/GPG-KEY-elasticsearch | apt-key add - && \
  apt-get update && \
  apt-get install elasticsearch

```

**Comment by mirabilos** [comment]
Tom Callahan dixit:

>@mirabilos both a colleague and I have tried to reproduce but we could
>@not... perhaps you ran into some transient error? I tried reproducing
>@using Docker. Let me know if you see something incorrect, I get a
>@successful build with the below:

Hm weird, it still fails here:

W: The repository 'https://packages.elastic.co/elasticsearch/2.x/debian stable Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://packages.elastic.co/elasticsearch/2.x/debian/dists/stable/main/binary-amd64/Packages
E: Some index files failed to download. They have been ignored, or old ones used instead.

One thing that baffles me is that, with wget, I *can* download:

https://packages.elastic.co/elasticsearch/2.x/debian/dists/stable/main/binary-amd64/Packages
https://packages.elastic.co/elasticsearch/2.x/debian/dists/stable/Release
https://packages.elastic.co/elasticsearch/2.x/debian/dists/stable/Release.gpg

(Incidentally, the last two failed, the last time I tried.)

I also looked into “apt-key list” output, and your key was
explicitly listed there, so that’s also out. I guess we’ll
have to dig into APT debugging options…

With “apt-get -o Acquire::AllowWeakRepositories=true update”
or “apt-get -o Acquire::AllowInsecureRepositories=true update”
I did not have any luck.

With “apt-get update -o Debug::Acquire::https=true” I hit luck:
* error reading ca cert file /etc/ssl/certs/ca-certificates.crt (Error while reading file.)
And indeed, something seems to have removed that file since its creation.

----

So, while the “Release file does not exist (cannot be downloaded
with wget either)” problem actually occurred and is now fixed,
apparently, apt and wget use different SSL configurations. Huh.

Incidentally, apt seems to use the same thing as cURL does, so
perhaps asking people to try to retrieve the aforementioned file
with curl, explicitly not wget, may help in debugging.

OK, thanks for fixing the missing Release file error and for your
patience with tracking down the remaining issues. Feel free to
close this issue now (no idea if I can do it per eMail, and I only
have text mode interfaces right now).

bye,
//mirabilos
-- 
tarent solutions GmbH
Rochusstraße 2-4, D-53123 Bonn • http://www.tarent.de/
Tel: +49 228 54881-393 • Fax: +49 228 54881-235
HRB 5168 (AG Bonn) • USt-ID (VAT): DE122264941
Geschäftsführer: Dr. Stefan Barth, Kai Ebenrett, Boris Esser, Alexander Steeg

**Comment by tomcallahan** [comment]
Great, thanks for the update and telling us how you debugged it, that'll help us out in the future.  Since the (persistent) issue seems to not be with Elasticsearch, I'll close this issue -- but if at some point you see our repo down again please let us know.

**Comment by mirabilos** [comment]
Tom Callahan dixit:

>that'll help us out in the future. Since the (persistent) issue seems
>to not be with Elasticsearch, I'll close this issue -- but if at some
>point you see our repo down again please let us know.

OK, sure, and I hope this will indeed help people in the future.
