### ISSUE TITLE
Getting fields and their values of a top_hits sub-aggregation of a date_histogram

### ISSUE THREAD

**Issue by spiewok** [elastic/elasticsearch#31805]
**Elasticsearch version:** 6.1.2

**HighLevelRestClient:** 6.1.2/6.1.3/6.1.4

**JVM version (java -version):** Java(TM) SE Runtime Environment (build 1.8.0_131-b11)

**OS version (uname -a if on a Unix-like system)**: macOS High Sierra 10.13.4 (Darwin Kernel Version 17.5.0)

**Description of the problem including expected versus actual behavior:**
Not able to access source fields while fetching a top_hits aggregation per bucket of a date_histogram aggregation with the HighLevelRestClient

**Steps to reproduce:**

**Index structure (json):**
[
{"id":289105,"sourceId":"2","xId":"1","vivaId":"7","xDensity":1,"xTimestamp":"2018-06-01T23:22:52Z","xValue1":20000,"xValue2":0,"xValue3":0,"xValue4":0,"xStringValue1":"","xStringValue2":"","xStringValue3":"","xStringValue4":"","checksum":"","createdAt":"2018-06-25T16:18:45Z","xDataType":"ABSOLUTE"},
{"id":289108,"sourceId":"2","xId":"1","vivaId":"7","xDensity":1,"xTimestamp":"2018-06-02T08:00:52Z","xValue1":10000,"xValue2":0,"xValue3":0,"xValue4":0,"xStringValue1":"","xStringValue2":"","xStringValue3":"","xStringValue4":"","checksum":"","createdAt":"2018-06-25T16:25:45Z","xDataType":"ABSOLUTE"},
{"id":289091,"sourceId":"2","xId":"1","vivaId":"5","xDensity":1,"xTimestamp":"2018-06-02T23:22:52Z","xValue1":10000,"xValue2":0,"xValue3":0,"xValue4":0,"xStringValue1":"","xStringValue2":"","xStringValue3":"","xStringValue4":"","checksum":"","createdAt":"2018-06-05T09:23:34Z","xDataType":"OUT"}]

**Query:**
{
  "size": 0,
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "vivaId": {
              "query": "7",
              "operator": "OR",
              "prefix_length": 0,
              "max_expansions": 50,
              "fuzzy_transpositions": true,
              "lenient": false,
              "zero_terms_query": "NONE",
              "boost": 1
            }
          }
        },
        {
          "range": {
            "xTimestamp": {
              "from": "2018-06-01T00:00:00Z",
              "to": "2018-06-05T23:59:00Z",
              "include_lower": true,
              "include_upper": true,
              "boost": 1
            }
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "aggregations": {
    "dateHisto": {
      "date_histogram": {
        "field": "xTimestamp",
        "interval": "1d",
        "offset": 0,
        "order": {
          "_key": "asc"
        },
        "keyed": false,
        "min_doc_count": 0,
        "extended_bounds": {
          "min": 1527811200000,
          "max": 1528243140000
        }
      },
      "aggregations": {
        "top_values": {
          "top_hits": {
            "from": 0,
            "size": 1,
            "version": false,
            "explain": false,
            "_source": {
              "includes": [],
              "excludes": []
            },
            "sort": [
              {
                "xTimestamp": {
                  "order": "desc"
                }
              }
            ]
          }
        }
      }
    }
  }
}

**Output:**
"buckets":[
   {
      "key_as_string":"2018-06-01T00:00:00.000Z",
      "key":1527811200000,
      "doc_count":3,
      "top_values":{
         "hits":{
            "total":3,
            "max_score":null,
            "hits":[
               {
                  "_index":"xdata",
                  "_type":"doc",
                  "_id":"289105",
                  "_score":null,
                  "_source":{
                     "id":289105,
                     "sourceId":"2",
                     "xId":"1",
                     "vivaId":"7",
                     "xDensity":1,
                     "xTimestamp":"2018-06-01T23:22:52Z",
                     "xValue1":20000,
                     "xValue2":0,
                     "xValue3":0,
                     "xValue4":0,
                     "xStringValue1":"",
                     "xStringValue2":"",
                     "xStringValue3":"",
                     "xStringValue4":"",
                     "checksum":"",
                     "createdAt":"2018-06-25T16:18:45Z",
                     "xDataType":"ABSOLUTE"
                  },
                  "sort":[
                     1527895372000
                  ]
               }
            ]
         }
      }
   }

So the output from elasticsearch (if done manually) is all right. The "_source" is included.

If I now do the query with the HighLevelRestClient which is like:
        SearchRequest searchRequest = new SearchRequest(ELASTICSEARCH_INDEX);

        QueryBuilder rangeQueryBuilder = rangeQuery("xTimestamp")
            .gte(from)
            .lte(to);

        BoolQueryBuilder queryBuilder = QueryBuilders.boolQuery();
        queryBuilder.must(matchQuery("vivaId", vivaId));
        queryBuilder.must(rangeQueryBuilder);

        DateHistogramAggregationBuilder dateHistogram = new DateHistogramAggregationBuilder("dateHisto");
        dateHistogram.field("xTimestamp");
        ExtendedBounds bounds = new ExtendedBounds(from.toEpochMilli(), to.toEpochMilli());
        dateHistogram.extendedBounds(bounds);

        switch (resolution) {
            case DAY:
                dateHistogram.dateHistogramInterval(DateHistogramInterval.DAY);
                break;
            case MONTH:
                dateHistogram.dateHistogramInterval(DateHistogramInterval.MONTH);
                break;
            case HOUR:
                dateHistogram.dateHistogramInterval(DateHistogramInterval.HOUR);
                break;
            case WEEK:
                dateHistogram.dateHistogramInterval(DateHistogramInterval.WEEK);
                break;
        }

        
        TopHitsAggregationBuilder aggregator = new TopHitsAggregationBuilder("top_values");
        aggregator.fetchSource(true);
        aggregator.sort("xTimestamp", SortOrder.DESC);
        aggregator.size(1);

        dateHistogram.subAggregation(aggregator);

        searchRequest.source(new SearchSourceBuilder()
            .query(queryBuilder)
            .aggregation(dateHistogram)
            .size(0)
        );

        SearchResponse searchResponse = client.search(searchRequest);
        Aggregations aggs = searchResponse.getAggregations();
        ParsedDateHistogram histogram = aggs.get("dateHisto");

there is no way to access the "_source", and therefore, I can't get the fields and their values.

So, if I do for instance: 
_((ParsedTopHits)histogram.getBuckets().get(0).getAggregations().get("top_values")).getHits().getHits()[0].getFields()_

the size of the fields is zero, though I state "fetch source", as seen above. And it's there if I do the query directly within in elasticsearch.

Is this a bug, or do I do something fundamentally wrong?

![bildschirmfoto 2018-07-04 um 21 18 34](https://user-images.githubusercontent.com/3295038/42292093-4929fe86-7fd0-11e8-9144-1e4db747e2ae.png)

**Comment by ywelsch** [comment]
@javanna can you have a look?

**Comment by javanna** [comment]
hi @spiewok please ask your question in our forums at https://discuss.elastic.co . We reserve github issues for confirmed bug reports and feature requests.

As far as I can see you do have the source as part of the top hits parsed aggregation, you can retrieve it by calling `getSourceAsMap` or `getSourceAsString` or `getSourceRef` depending on how you need to retrieve it.
