### ISSUE TITLE
add and remove alias timeout

### ISSUE THREAD

**Issue by mylinuxsa** [elastic/elasticsearch#31802]
es : 5.6.3  1 master and 4 datanode

OS : centos 6.9 x86_64

JAVA : java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

request rate:  2k/s

Steps:

1, create inde user-20180701
2, loaddata to user-20180701
3, sleep 30 and flush
4, curl -s -H "Content-Type:application/json; charset=UTF-8" -X POST 'http://localhost:9200/_aliases' -d '{"actions":[{"add":{"index":"user-20180701","alias":"userdata"}}]}'
5, curl -s -H "Content-Type:application/json; charset=UTF-8" -X POST 'http://localhost:9200/_aliases' -d '{"remove":[{"add":{"index":"user-20180631","alias":"userdata"}}]}'

Steps 4 , 10% - 20% request timeout

**Comment by dnhatn** [comment]
> request rate: 2k/s

@mylinuxsa Did you mean that you were issuing 2k add/remove alias requests per second?

**Comment by mylinuxsa** [comment]
@dnhatn  query per second 2000k.

**Comment by ywelsch** [comment]
my guess is that loading your data is issuing a storm of dynamic mapping updates, overloading the master to update the aliases. Anyhow, let's continue discussing this on our discuss forums (discuss.elastic.co), Github is reserved for verified bugs and feature requests only.
