### ISSUE TITLE
Improve shard follow task retry mechanism

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#31816]
Currently there is one simple counter for counting retries caused by remote failures when invoking shard changes, updating mapping (cluster state api and put mapping api), bulk shard operations api.

The shard follow task api likely needs multiple counters per read / write, so that an unstable network does not cause to immediately fail the shard follow task.

Things to do and investigate:
* https://github.com/elastic/elasticsearch/pull/31581#discussion_r200260653

Relates to #30086

**Comment by jasontedor** [comment]
Closed by #31930
