### ISSUE TITLE
Don't compile script fields when size is 0

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#31824]
Today Kibana sends the list of script fields that it may need for convenience, even if it doesn't need any hits. This may be confusing to users sometimes when this causes for instance the script compilation limit to break. While things could be improved on the Kibana side, this issue looks easy to fix in `SearchService.parseSource` by just ignoring script fields when size is 0.

**Comment by dakrone** [comment]
We discussed this in fix-it-thursday and decided this sounds like a good idea. Let's do it

**Comment by Parth-Vader** [comment]
@dakrone @jpountz 

I would like to take this up. From what I understand, I would have to make changes in [this](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/SearchService.java#L712) condition and adding `source.size() == 0`. 

Please correct me if I'm wrong.

**Comment by rjernst** [comment]
@Parth-Vader I think it would be [this line](https://github.com/elastic/elasticsearch/blob/dd21ad0d9d48642704cf64260bb5f86a75fc3803/server/src/main/java/org/elasticsearch/search/SearchService.java#L809), so that script fields are not compiled or added to the search context.

Upon further thought, I also wonder whether this should be an error case? Otherwise part of the request is being silently ignored.

**Comment by jpountz** [comment]
Failing the request is another option indeed. I guess ignoring the script has by preference since it avoids introducing a significant breaking change: to be consistent we'd have to do the same with stored fields, source filtering, highlighting or sort orders.

**Comment by Parth-Vader** [comment]
@rjernst @jpountz  So to get started, `source.scriptFields() != null && source.size() != 0` in that line? Or do we want to  throw an error too?

**Comment by jpountz** [comment]
@Parth-Vader We're still having second thoughts regarding whether we want to raise an error, let's give @rjernst a chance to comment.

**Comment by Parth-Vader** [comment]
@rjernst @jpountz Thanks, I've made this PR #31917.
