### ISSUE TITLE
Document that setting script.allowed_types: inline is needed for x-pack monitoring

### ISSUE THREAD

**Issue by jakommo** [elastic/elasticsearch#31832]
Setting `script.allowed_types: none` breaks local x-pack monitoring. 
There is an exception thrown at startup:
```
[2018-07-05T17:14:35,478][ERROR][o.e.x.m.e.l.LocalExporter] failed to set monitoring pipeline [xpack_monitoring_2]
org.elasticsearch.ElasticsearchException: java.lang.IllegalArgumentException: [inline] scripts cannot be executed
```
But it could easily be missed and I suggest we document this requirement.

I.e. adding a warning to https://www.elastic.co/guide/en/elasticsearch/reference/5.6/modules-scripting-security.html#allowed-script-types-setting that `inline` is required for monitoring to work and maybe also somewhere in the x-pack monitoring setup that `script.allowed_types: inline` is required.

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open. This is still relevant:
https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-security.html#allowed-script-types-setting
