### ISSUE TITLE
[FEATURE REQUEST] - ingest nodes - run a pipeline as a processor in another pipeline

### ISSUE THREAD

**Issue by tallavi** [elastic/elasticsearch#31842]
Hi,

I'm using ingest nodes. I have some steps which are shared by multiple ingest nodes. Currently, I have to duplicate these steps across multiple pipelines.

I believe it would be great to have a process called "runPipeline" with the ability to name another pipeline to run as a step in the current pipeline. It would be a great way to reuse steps.

Thanks!

Tal

**Comment by original-brownbear** [comment]
@rjernst this was on the list of enhancements initially requested by @tsg. Since there's nothing else open that can be worked on by me I'm looking into this now.
Let me know if we don't want to do this (yet) though :)
