### ISSUE TITLE
Support Put User API for reserved users if reserved realm is disabled   

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#31848]
The validation for `PutUserRequest` calls `Validation.validateUsername` which prevents putting a user with a reserved name.

There is a check for `RESERVED_REALM_ENABLED_SETTING` in `ClientReservedRealm`, that would allow but this setting is not consulted in the API, only for file realm.

It would be helpful if the native realm could support storing users with reserved names in the same way that the file realm can.

**Comment by jaymode** [comment]
We discussed this in the security team meeting. The disabling of the reserved realm was added for a specific use case and in that use case, the reserved users should all be managed the same way which is the file realm. Ultimately in an ideal world we would completely disable the ability to disable the reserved realm.
