### ISSUE TITLE
[doc] Consider mentioning Kibana supports only PEM while Elasticsearch supports both PEM and PKCS#12

### ISSUE THREAD

**Issue by kiju98** [elastic/elasticsearch#31850]
We may consider adding a note at https://www.elastic.co/guide/en/elasticsearch/reference/6.3/configuring-tls.html#node-certificates that currently Kibana supports only PEM while Elasticsearch supports both PEM and PKCS#12.
Some people may want to use the same certificate on both Elasticsearch and Kibana. They may create a PKCS#12 certificate and get frustrated.

Also we can consider adding

> If you upload a non-trial license, the default value changes to true.

after

> 2. Verify that the xpack.security.enabled setting is true on each node in your cluster. If you are using a trial license, the default value is false.

at https://www.elastic.co/guide/en/elasticsearch/reference/6.3/configuring-security.html.
Some people get embarrassed when they upload a license and get an error "Cannot install a [PLATINUM] license unless TLS is configured..."

**Comment by lockewritesdocs** [comment]
We document how to create a PEM file specifically for Kibana in [Encrypting client communications for Kibana](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-basic-setup-https.html#encrypt-kibana-http). Marking this issue as closed.
