### ISSUE TITLE
Watcher: Storing a watch with more than one scripted condition should return an error

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#31852]
The following watch is stored just fine despite having two conditions in the `compare` condition

```
PUT _xpack/watcher/watch/my_watch
{
  "trigger": {
    "schedule": {
      "interval": "10h"
    }
  },
  "input": {
    "none" : {}
  },
  "condition": {
    "compare": {
      "ctx.payload.status": {
        "eq": "yellow"
      },
      "ctx.execution_time": {
        "gte": "<{now/d+5m}>"
      }
    }
  },
  "actions": {
    "logme": {
      "logging": {
        "text": "{{ctx.payload}}"
      }
    }
  }
}

GET _xpack/watcher/watch/my_watch
```

If you now receive the watch back, the first condition will be gone. We should return a proper error message in this case when the watch is stored instead of silently dropping the invalid JSON.

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
