### ISSUE TITLE
SQL: SELECT [constant] FROM [index] returns one record only

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#31863]
Assuming an index that has more than one document in it, issuing a query that `SELECT`s a constant from it will return just one document, whereas it should return [number_of_documents_in_index] records.

Example query: `SELECT 1=1 FROM "test_emp"`.
Result:
```
---------------
true
```

Desired result:
```
---------------
true
true
true
....
```

**Comment by nikoncode** [comment]
I have found root cause, I will work on fix.

**Comment by nikoncode** [comment]
My idea - skip optimization, doesn't work after e5d18ad45cc9530ec4a7f8b0328e8bc65dafc344 commit.

**Comment by astefan** [comment]
@nikoncode thank you for looking at this one. Indeed, that PR you are mentioning did change a lot of things inside SQL code.
I've had a look at the issue and I pushed a fix in 
https://github.com/elastic/elasticsearch/commit/60b8118d3a9036d2b828f967863049be08d018f8 (master) and https://github.com/elastic/elasticsearch/commit/c6f55b2fcb05670b399c4c6c74b91ccca871b3f0 (6.x).

There are still some cases that don't work (the one you mention in your last comment included).
