### ISSUE TITLE
Include java version information in reproduction info

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#31898]
As brought up in #31739 we should print the Java version in the reproduction line as: 
```
JAVA_HOME=$JAVA10_HOME RUNTIME_JAVA_HOME=$JAVA11_HOME ./gradlew
``` 
This will work because the build already requires people to have these env vars set.
We could also include the full paths instead of the env vars, as the build will have to pass in information anyhow for this to work as the test runner will not be aware what was used to build the tests. 

This will help reproduce issues that are specific to some java versions without requiring one to look at how the CI job is configured.

**Comment by rjernst** [comment]
> We could also include the full paths instead of the env vars

In order to keep the ability to copy/paste a repro line from CI to my our own workstations, the env vars should be used.

But +1 to the idea in general.

**Comment by atorok** [comment]
Discussed with @jkakavas , this needs to be extended to FIPS.

**Comment by atorok** [comment]
I am considering adding a new parameter for run-time java such as `-Druntime.java=11` or `-Druntime.java=8fips`. This will take precedence to `RUNTIME_JAVA_HOME` which we will keep for comparability.  The property will use the  `JAVA11_HOME` etc env vars that we already use to figure out the actual paths. This is so this will work well with the Gradle daemon on JDK 9+ where new daemons are not spawn for env changes and setting `RUNTIME_JAVA_HOME` might not have any effect.
