### ISSUE TITLE
Add refresh=wait_for to update_by_query 

### ISSUE THREAD

**Issue by konkol** [elastic/elasticsearch#31911]
Elasticsearch 6
No plugins.
OpenJDK 1.8
Debian Testing - Buster - 4.16

While update/index/etc have the option to use refresh=wait_for, the update_by_query and delete_by_query have only the option to use true and false.

In my use case, i need to do two consecutive updates on different but possibly intersecting sets of documents. At the moment I need to use the refresh=true option to solve possible conflicts, but I am concerned with the performance.

Would it be possible to add the refresh=wait_for option to update_by_query and delete_by_query?

**Comment by bleskes** [comment]
@konkol it seems you're using delete by query for a very small number of documents where you think a refresh will hit performance too much. Can you elaborate a bit on your use case?

**Comment by atorok** [comment]
No further feedback received. @konkol  if you have the requested 
information please add it in a comment and we can look at re-opening 
this issue.
