### ISSUE TITLE
result of  Avg Aggregation is null or Infinity

### ISSUE THREAD

**Issue by ydzhu** [elastic/elasticsearch#31920]
A single-value metrics aggregation that computes the average of numeric values that are extracted from the aggregated documents. For example:
` {
    "aggs" : {
        "avg_grade" : { "avg" : { "field" : "grade" } }
    }
}`
If document count is 0,  the avg_grade is null。Do you think it's reasonable? When it happended, we use getValue method of Avg on java API, this return value is Inifity. 
We hope to get more information for Avg Aggregation when document count is 0.

**Comment by colings86** [comment]
@ydzhu What information are you hoping to get from an avg aggregation when the document count is zero? Note that one reason that we emit null for the value in this case is that JSON does not support infinite and NaN values

**Comment by ydzhu** [comment]
Because we need to handle this exceptional case at our programmer,  I hope to get zero when the document count is zero which is consistent with the actual situation.  Better I can get null or zero by set up parameter at API when document count is zero.

**Comment by polyfractal** [comment]
A zero average is not quite the same as no documents.  E.g. a mixture of positive and negative values can give you a zero average:

`((5 + -5 + 2 + -2) / 4) == 0`

Whereas no documents at all is a division by zero situation:

` 0 / 0 == undefined`

That's why we don't use zero as the return value when there are no documents, since zero is a valid, numerical answer whereas no documents is an empty set, and has no numerical value.

**Comment by ydzhu** [comment]
@polyfractal  Although that it cause some trouble, I agree with your idea. Thanks for your help.

**Comment by larrycinnabar** [comment]
@polyfractal 

But is this possible to detect such situations in script inside `AvgAggregation`?
something like this does not work:
```
"avg":{  
  "field":"index",
  "script":{  
    "lang":"painless",
    "source":"if (_value == null) {return 0} else {return _value}"
  }
}
```

**Comment by polyfractal** [comment]
Agreed that for a script, we should be allowing the script to inspect the value and choose for itself.  That's unfortunately just a bug at the moment, due to how the pipeline framework works :(

**Comment by longvd89** [comment]
if i have 10 documents and AVG aggregation:   { "aggs" : { "avg_grade" : { "avg" : { "field" : "grade" } } } }
but 1 document have grade = undefined (or not exist field grade in document). I have question : the value of AVG is is calculated on 10 documents or  9 documents (have value of grade )

**Comment by polyfractal** [comment]
@longvd89 the forums are probably better place for this kind of question in the future.

But to answer your question: documents that do not have the field (or the field is `null`) will not be included in the calculation.  E.g. aggregations skip documents that don't have the field unless `missing` parameter is configured to give a default.

So only 9 documents would be averaged in your case.
