### ISSUE TITLE
Forbid negative values for "weight"  in Function Score Query

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#31927]
If a negative weight is submitted for a query:
- issue a deprecation message for 6.x
- error for 7

related to https://github.com/elastic/elasticsearch/issues/24910

**Comment by aditya-agrawal** [comment]
Hi, I would like to pick this issue.

**Comment by mayya-sharipova** [comment]
Thanks @aditya-agrawal, your PR would be very much appreciated

**Comment by mayya-sharipova** [comment]
@aditya-agrawal  We have an urgent need for this PR, as we are preparing for Lucene 8 upgrade. Do you think you will be able to submit a PR within several days?

If not, no problem, we can work on it ourselves.

**Comment by aditya-agrawal** [comment]
@mayya-sharipova yes I will try to complete this in few days.

**Comment by jimczi** [comment]
Closed by #33390
