### ISSUE TITLE
Clearly document how to disable bootstrap checks

### ISSUE THREAD

**Issue by melissachang** [elastic/elasticsearch#31933]
https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html says "If you are running a single node in production, it is possible to evade the bootstrap checks (either by not binding transport to an external interface, or by binding transport to an external interface and setting the discovery type to single-node)."

But I'm not sure how to "not binding transport to an external interface, or by binding transport to an external interface and setting the discovery type to single-node". If you could clearly put the command-line flags for disabling bootstrap checks, that would be great.

**Comment by jbaiera** [comment]
Closing this out for now. If there is any more feedback on this, we can reopen and discuss further.

**Comment by amit10may** [comment]
I am using ES 6.3 and I had to edit elasticsearch.yml to include discovery.type: single-node
It would help to mention the config location. Earlier I was trying to put this in jvm.options and command line variables. I may be doing wrong things but having a clear statement in official document can help lot of mistakes.
