### ISSUE TITLE
Impossibile to set a CustomClassloader in RequestHightLevelClient

### ISSUE THREAD

**Issue by dvivarelli** [elastic/elasticsearch#31956]
RequestHightLevel client use ServiceLoader.load(NamedXContentProvider.class) in getProvidedNamedXContents() method, but in case the application use a custom classloader, a ClassCastException is thrown because the default classloader is LuncherClassloader.
It should use ServiceLoader.load(Class, ClassLoader) instead, or shoud be provided a way to set the class loader to use.

**Elasticsearch version**  6.3.1

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Windows 10 Home

**Comment by nik9000** [comment]
@rjernst , you are our expert in ServiceLoader. Could you have a look at this?

**Comment by rjernst** [comment]
@dvivarelli Can you describe in more detail the hierarchy of classloaders you have? The assumption we make is that all of the elastic jars eg the rest client + module jars like matrix agg would been in the same classloader.

**Comment by dvivarelli** [comment]
We have a web app on tomcat 8, so the main class loader is a webapp classloader. 
On the main app we need some plugins to add functionalities. Every plugin works its own plugin classloader (our custom classloader).
That custom classloader resolve classes inside the plugin jar (a fat jar) except for some jar that must be in common.
Because some jar could be "duplicated" between plugin and main app (some dipendencies could be the same),  the plugin classloader is not a child of webapp classloader, but plugin classloader has a reference on the webapp classloader.

So the structure is:

class PluginClassloader:
    private Classloader delegate;  //it is the webapp classloader injected in the costructor

      - this classloader has SystemClassloader has parent. 
      - try to resolve the class on the jar
           - if class already loaded by SystemClassLoader, found
           - else search on the fat jar
     -  if found return, 
      - else try to resolve with delegate classloader  


We want to use rest high level client in a plugin (and the elastic jars and its dependencies inside the jar).
So we have a class loaded by plugin classloader with  new RestHightLevelClient( .... ), the RestHightLevelClient is loaded by PluginClassLoader but, when the ServiceLoader.load() is called (in the protected costructor) it use the webapp classloader because in the SystemLoader,load() there this instruction:
ClassLoader cl = Thread.currentThread().getContextClassLoader();   // in our case this return webapp classloader
So we have a class cast exception.


A possible workaround is set the Thread.currentThread().setContextClassloader(<pluginclassloader>) before the new RestHightLevelClient( ... ) and evetrhing works.

**Comment by rjernst** [comment]
@dvivarelli Sorry for the long delay in replying here. I think setting the context class loader in this case is exactly what we want. You have an expert case (your own classloader hierarchy) and java's ServiceLoader defaults to the context classloader for this exact reason: to allow selecting which classloader is looked at, without having to plumb through a ClassLoader all the way down to where ServiceLoader is called. I'm going to close this issue as I don't see a need to add this plumbing (an optional constructor arg to RestHighLevelClient) when there is already a viable solution.
