### ISSUE TITLE
How do I increase 'index.max_result_window'?

### ISSUE THREAD

**Issue by marklcfc** [elastic/elasticsearch#31953]
I am using Elasticsearch on an Invision forum. It works fine mostly, but there is a task locking every 5 minutes and this is the error its giving.

`Result window is too large, from + size must be less than or equal to: [10000] but was [11450]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.`

I've been advised to raise the index.max_result_window to 20000.  I asked my hosts to do this but we had a problem, after they added that figure, elasticsearch stopped working. This is what they said. 

> "This was restarted however it appears with this setting in place it stays running for 10seconds before killing itself. 
> root@server1 $ service elasticsearch status
> elasticsearch (pid 13336) is running...
> root@server1 $ service elasticsearch status
> elasticsearch dead but subsys locked
> 
> We had added this setting at the end of /etc/elasticsearch/elasticsearch.yml with: index.max_result_window: 20000"

Once removing that line, it started working again. Please advise how to raise the max result window setting

**Comment by dakrone** [comment]
Hi,

We reserve Github issues for feature requests and bug reports. If you are having problems please use https://discuss.elastic.co instead!

As a quick note, you are no longer allowed to set index-level settings (settings starting with `index.`) on a node level. You'll need to set them with an index template or through the [update index settings API](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/indices-update-settings.html)

**Comment by marklcfc** [comment]
My host tried that but this happened.

I have now run the command:
>
> curl -X PUT "localhost:9200/twitter/_settings" -H 'Content-Type:
>> application/json' -d' { "index" : { "max_result_window" : 20000 } } '
>
> However this has outputted the following response:
>
> {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no
>> such index","resource.type":"index_or_alias","resource.id":"twitter","index_uuid":"_na_","index":"twitter"}],"type":"index_not_found_exception","reason":"no
>> such index","resource.type":"index_or_alias","resource.id
>> ":"twitter","index_uuid":"_na_","index":"twitter"},"status":404}
>
>
