### ISSUE TITLE
Running a single test got harder

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#31964]
The changes introduced in #30975 unfortunately mean that it's harder to run a single test from the command line, and in particular the command that `REPRODUCE WITH` says will reproduce a failure will not work if the failing test was from the `:server:test` task. For instance:

```
$ ./gradlew :server:test -Dtests.class=org.elasticsearch.common.rounding.TimeZoneRoundingTests -Dtests.method="testUTCTimeUnitRounding"
...
> Task :server:testScriptDocValuesMissingV6Behaviour FAILED
   [junit4] <JUnit4> says jolly good day! Master seed: AA38CDFBB89D3357
==> Test Summary: 0 suites, 0 tests
   [junit4] Tests summary: 0 suites, 0 tests

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':server:testScriptDocValuesMissingV6Behaviour'.
> There were no executed tests: 0 suites, 0 tests
...
```

As a workaround, one can add `-x :server:testScriptDocValuesMissingV6Behaviour` to the command line.

**Comment by rjernst** [comment]
This has not worked out like I had hoped. I will create a PR to make `check` depend on this test task instead of `test`.
