### ISSUE TITLE
geo_shape precision

### ISSUE THREAD

**Issue by halleystar** [elastic/elasticsearch#31983]
Elasticsearch version (bin/elasticsearch --version):

5.6.4

Plugins installed: []

JVM version (java -version):

openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10)
OpenJDK 64-Bit Server VM (build 10.0.1+10, mixed mode)
OS version (uname -a if on a Unix-like system):

Linux f076156ce113 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_6

I am doing migrate from  1.7 to 5.6.4. I use geo_shape datetype. but I found the precision is not the same as which is in 1.7.  at the same time,  the sort is also different;
1. the reason  why  the precision is different;
2. the reason why  the sort is different;

mapping
{
    "mappings" : {
        "region" : {
            "dynamic": "false", 
			"properties" : {
				"id": {
					"type":"string"
				},
				"region" : {
					"type": "geo_shape",
					"tree": "geohash",
					"precision": 50
				}
			}
    	}
    }
}

**Comment by cbuescher** [comment]
Hi @halleystar ! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
If you open this question in the forum, could you also include what differences you observe with precision and sort in 5.6 compared to 1.7? To me it's not clear from the description above.

**Comment by halleystar** [comment]
I don't think this is  a question。the same precision and the same Dsl but the result is diff

in the case of elasticsearch1.7
{"took":5,"hits":{"total":2,"max_score":1,"hits":[{"_index":"gis-region","_type":"region","_id":"4","_score":1,"_source":{"id":470,"region":{"coordinates":[[["116.434225","39.975287"],["116.449568","39.995107"],["116.43970170867237","39.99497761177407"],["116.41369680731","39.994408212752"],["116.41369689850515","39.99443664024678"],["116.394484","39.993918"],["116.39572144035283","39.99167941863296"],["116.40043","39.983206"],["116.40043011431644","39.98319769105138"],["116.40052165971491","39.98321634473732"],["116.40052","39.983323"],["116.40094644633666","39.98330290109479"],["116.401634","39.983443"],["116.410042","39.981093"],["116.414031","39.975205"],["116.434225","39.975287"]]],"type":"polygon"}}},{"_index":"gis-region","_type":"region","_id":"41","_score":1,"_source":{"id":472,"region":{"coordinates":[[["116.414246","39.975163"],["116.41421538644542","39.97520574872182"],["116.414031","39.975205"],["116.41078942906539","39.979989750479554"],["116.4099886912492","39.9811078995676"],["116.40550358152854","39.98236146853092"],["116.40159620813535","39.98343529936638"],["116.400484","39.983069"],["116.400664","39.974665"],["116.414246","39.975163"]]],"type":"polygon"}}}]}}

the result in the case of 5.6.4
{"hits":{"total":1,"max_score":1,"hits":[{"_index":"gis-region","_type":"region","_id":"41","_score":1,"_source":{"id":472,"region":{"coordinates":[[["116.414246","39.975163"],["116.41421538644542","39.97520574872182"],["116.414031","39.975205"],["116.41078942906539","39.979989750479554"],["116.4099886912492","39.9811078995676"],["116.40550358152854","39.98236146853092"],["116.40159620813535","39.98343529936638"],["116.400484","39.983069"],["116.400664","39.974665"],["116.414246","39.975163"]]],"type":"polygon"}}}]}}

The query DSL
{
"query" : {
"geo_shape" : {
"region" : {
"shape" : {
"type" : "point",
"coordinates" : [
116.414235,
39.975154
]
},
"relation" : "intersects"
}
}
}
}

The mapping
curl -X PUT 'http://127.0.0.1:9200/gis-region' -d '
{"mappings" : {"region" : {"properties" : {"id": {"type":"long"},"region" : {"type": "geo_shape","tree": "geohash","precision": 26}}}}}

**Comment by cbuescher** [comment]
@halleystar lets discuss this in https://discuss.elastic.co/t/geo-shape-sort/139724 where I posted an answer.

**Comment by halleystar** [comment]
when i set the precision exactly. the index and bulk performance is very very slow then which in 1.7
