### ISSUE TITLE
Not able to build the source code in Windows 10

### ISSUE THREAD

**Issue by jhalagaiah** [elastic/elasticsearch#31984]
**Elasticsearch version** (`bin/elasticsearch --version`): v5.5.3

**Plugins installed**: []

**JVM version** (`java -version`): 8

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**: Not able to build the source code

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Downloaded source code (.zip) from "https://github.com/elastic/elasticsearch/tree/v5.5.1" and un-zipped it.
 2. Installed gradle 4.8.1
 3. Went to source code location, and ran the command "gradle assemble". 

**Provide logs (if relevant)**:
* What went wrong:
Could not resolve all files for configuration ':buildSrc:runtimeClasspath'.
> Could not resolve com.carrotsearch.randomizedtesting:junit4-ant:2.5.0.
  Required by:
      project :buildSrc
   > Could not resolve com.carrotsearch.randomizedtesting:junit4-ant:2.5.0.
      > Could not get resource 'https://jcenter.bintray.com/com/carrotsearch/ran
domizedtesting/junit4-ant/2.5.0/junit4-ant-2.5.0.pom'.
         > Could not GET 'https://jcenter.bintray.com/com/carrotsearch/randomize
dtesting/junit4-ant/2.5.0/junit4-ant-2.5.0.pom'.
            > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/5.153.35.2
48] failed: Connection timed out: connect
   > Could not resolve com.carrotsearch.randomizedtesting:junit4-ant:2.5.0.
      > Could not get resource 'https://repo.maven.apache.org/maven2/com/carrots
earch/randomizedtesting/junit4-ant/2.5.0/junit4-ant-2.5.0.pom'.
         > Could not GET 'https://repo.maven.apache.org/maven2/com/carrotsearch/
randomizedtesting/junit4-ant/2.5.0/junit4-ant-2.5.0.pom'.
            > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.10
1.112.215] failed: Connection timed out: connect
> Could not resolve junit:junit:4.12.
  Required by:
      project :buildSrc
   > Could not resolve junit:junit:4.12.
      > Could not get resource 'https://jcenter.bintray.com/junit/junit/4.12/jun
it-4.12.pom'.
         > Could not HEAD 'https://jcenter.bintray.com/junit/junit/4.12/junit-4.
12.pom'.
            > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/5.153.35.2
48] failed: Connection timed out: connect
   > Could not resolve junit:junit:4.12.
      > Could not get resource 'https://repo.maven.apache.org/maven2/junit/junit
/4.12/junit-4.12.pom'.
         > Could not HEAD 'https://repo.maven.apache.org/maven2/junit/junit/4.12
/junit-4.12.pom'.
            > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.10
1.112.215] failed: Connection timed out: connect
> Could not resolve com.netflix.nebula:gradle-extra-configurations-plugin:3.0.3.

  Required by:
      project :buildSrc
   > Could not resolve com.netflix.nebula:gradle-extra-configurations-plugin:3.0
.3.
      > Could not get resource 'https://jcenter.bintray.com/com/netflix/nebula/g
radle-extra-configurations-plugin/3.0.3/gradle-extra-configurations-plugin-3.0.3
.pom'.
         > Could not GET 'https://jcenter.bintray.com/com/netflix/nebula/gradle-
extra-configurations-plugin/3.0.3/gradle-extra-configurations-plugin-3.0.3.pom'.

            > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/5.153.35.2
48] failed: Connection timed out: connect
   > Could not resolve com.netflix.nebula:gradle-extra-configurations-plugin:3.0
.3.
      > Could not get resource 'https://repo.maven.apache.org/maven2/com/netflix
/nebula/gradle-extra-configurations-plugin/3.0.3/gradle-extra-configurations-plu
gin-3.0.3.pom'.
         > Could not GET 'https://repo.maven.apache.org/maven2/com/netflix/nebul
a/gradle-extra-configurations-plugin/3.0.3/gradle-extra-configurations-plugin-3.
0.3.pom'.
            > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.10
1.112.215] failed: Connection timed out: connect
> Could not resolve com.netflix.nebula:nebula-publishing-plugin:4.4.4.
  Required by:
      project :buildSrc
   > Could not resolve com.netflix.nebula:nebula-publishing-plugin:4.4.4.
      > Could not get resource 'https://jcenter.bintray.com/com/netflix/nebula/n
ebula-publishing-plugin/4.4.4/nebula-publishing-plugin-4.4.4.pom'.
         > Could not GET 'https://jcenter.bintray.com/com/netflix/nebula/nebula-
publishing-plugin/4.4.4/nebula-publishing-plugin-4.4.4.pom'.
            > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/5.153.35.2
48] failed: Connection timed out: connect
   > Could not resolve com.netflix.nebula:nebula-publishing-plugin:4.4.4.
      > Could not get resource 'https://repo.maven.apache.org/maven2/com/netflix
/nebula/nebula-publishing-plugin/4.4.4/nebula-publishing-plugin-4.4.4.pom'.
         > Could not GET 'https://repo.maven.apache.org/maven2/com/netflix/nebul
a/nebula-publishing-plugin/4.4.4/nebula-publishing-plugin-4.4.4.pom'.
            > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.10
1.112.215] failed: Connection timed out: connect
> Could not resolve com.netflix.nebula:gradle-info-plugin:3.0.3.
  Required by:
      project :buildSrc
   > Could not resolve com.netflix.nebula:gradle-info-plugin:3.0.3.
      > Could not get resource 'https://jcenter.bintray.com/com/netflix/nebula/g
radle-info-plugin/3.0.3/gradle-info-plugin-3.0.3.pom'.
         > Could not GET 'https://jcenter.bintray.com/com/netflix/nebula/gradle-
info-plugin/3.0.3/gradle-info-plugin-3.0.3.pom'.
            > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/5.153.35.2
48] failed: Connection timed out: connect
   > Could not resolve com.netflix.nebula:gradle-info-plugin:3.0.3.
      > Could not get resource 'https://repo.maven.apache.org/maven2/com/netflix
/nebula/gradle-info-plugin/3.0.3/gradle-info-plugin-3.0.3.pom'.
         > Could not GET 'https://repo.maven.apache.org/maven2/com/netflix/nebul
a/gradle-info-plugin/3.0.3/gradle-info-plugin-3.0.3.pom'.
            > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.10
1.112.215] failed: Connection timed out: connect
> Could not resolve org.eclipse.jgit:org.eclipse.jgit:3.2.0.201312181205-r.
  Required by:
      project :buildSrc
   > Could not resolve org.eclipse.jgit:org.eclipse.jgit:3.2.0.201312181205-r.
      > Could not get resource 'https://jcenter.bintray.com/org/eclipse/jgit/org
.eclipse.jgit/3.2.0.201312181205-r/org.eclipse.jgit-3.2.0.201312181205-r.pom'.
         > Could not GET 'https://jcenter.bintray.com/org/eclipse/jgit/org.eclip
se.jgit/3.2.0.201312181205-r/org.eclipse.jgit-3.2.0.201312181205-r.pom'.
            > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/5.153.35.2
48] failed: Connection timed out: connect
   > Could not resolve org.eclipse.jgit:org.eclipse.jgit:3.2.0.201312181205-r.
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/eclipse
/jgit/org.eclipse.jgit/3.2.0.201312181205-r/org.eclipse.jgit-3.2.0.201312181205-
r.pom'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/eclipse/jgit/
org.eclipse.jgit/3.2.0.201312181205-r/org.eclipse.jgit-3.2.0.201312181205-r.pom'
.
            > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.10
1.112.215] failed: Connection timed out: connect
> Could not resolve com.perforce:p4java:2012.3.551082.
  Required by:
      project :buildSrc
   > Could not resolve com.perforce:p4java:2012.3.551082.
      > Could not get resource 'https://jcenter.bintray.com/com/perforce/p4java/
2012.3.551082/p4java-2012.3.551082.pom'.
         > Could not GET 'https://jcenter.bintray.com/com/perforce/p4java/2012.3
.551082/p4java-2012.3.551082.pom'.
            > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/5.153.35.2
48] failed: Connection timed out: connect
   > Could not resolve com.perforce:p4java:2012.3.551082.
      > Could not get resource 'https://repo.maven.apache.org/maven2/com/perforc
e/p4java/2012.3.551082/p4java-2012.3.551082.pom'.
         > Could not GET 'https://repo.maven.apache.org/maven2/com/perforce/p4ja
va/2012.3.551082/p4java-2012.3.551082.pom'.
            > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.10
1.112.215] failed: Connection timed out: connect
> Could not resolve de.thetaphi:forbiddenapis:2.3.
  Required by:
      project :buildSrc
   > Could not resolve de.thetaphi:forbiddenapis:2.3.
      > Could not get resource 'https://jcenter.bintray.com/de/thetaphi/forbidde
napis/2.3/forbiddenapis-2.3.pom'.
         > Could not GET 'https://jcenter.bintray.com/de/thetaphi/forbiddenapis/
2.3/forbiddenapis-2.3.pom'.
            > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/5.153.35.2
48] failed: Connection timed out: connect
   > Could not resolve de.thetaphi:forbiddenapis:2.3.
      > Could not get resource 'https://repo.maven.apache.org/maven2/de/thetaphi
/forbiddenapis/2.3/forbiddenapis-2.3.pom'.
         > Could not GET 'https://repo.maven.apache.org/maven2/de/thetaphi/forbi
ddenapis/2.3/forbiddenapis-2.3.pom'.
            > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.10
1.112.215] failed: Connection timed out: connect
> Could not resolve org.apache.rat:apache-rat:0.11.
  Required by:
      project :buildSrc
   > Could not resolve org.apache.rat:apache-rat:0.11.
      > Could not get resource 'https://jcenter.bintray.com/org/apache/rat/apach
e-rat/0.11/apache-rat-0.11.pom'.
         > Could not GET 'https://jcenter.bintray.com/org/apache/rat/apache-rat/
0.11/apache-rat-0.11.pom'.
            > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/5.153.35.2
48] failed: Connection timed out: connect
   > Could not resolve org.apache.rat:apache-rat:0.11.
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/apache/
rat/apache-rat/0.11/apache-rat-0.11.pom'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/apache/rat/ap
ache-rat/0.11/apache-rat-0.11.pom'.
            > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.10
1.112.215] failed: Connection timed out: connect
> Could not resolve ru.vyarus:gradle-animalsniffer-plugin:1.2.0.
  Required by:
      project :buildSrc
   > Could not resolve ru.vyarus:gradle-animalsniffer-plugin:1.2.0.
      > Could not get resource 'https://jcenter.bintray.com/ru/vyarus/gradle-ani
malsniffer-plugin/1.2.0/gradle-animalsniffer-plugin-1.2.0.pom'.
         > Could not GET 'https://jcenter.bintray.com/ru/vyarus/gradle-animalsni
ffer-plugin/1.2.0/gradle-animalsniffer-plugin-1.2.0.pom'.
            > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/5.153.35.2
48] failed: Connection timed out: connect
   > Could not resolve ru.vyarus:gradle-animalsniffer-plugin:1.2.0.
      > Could not get resource 'https://repo.maven.apache.org/maven2/ru/vyarus/g
radle-animalsniffer-plugin/1.2.0/gradle-animalsniffer-plugin-1.2.0.pom'.
         > Could not GET 'https://repo.maven.apache.org/maven2/ru/vyarus/gradle-
animalsniffer-plugin/1.2.0/gradle-animalsniffer-plugin-1.2.0.pom'.
            > Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.10
1.112.215] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 14s

**Comment by jasontedor** [comment]
The 5.5.1 build is not supported with Gradle 4.8.1, please use the Gradle wrapper so you use the appropriate version. The dependency get failures look like a local issue to me. Given these comments, I will close this issue but we can always reopen.
