### ISSUE TITLE
Search with "cowan" results in no matches with default_operator AND but if using AND between terms returns match

### ISSUE THREAD

**Issue by boyter** [elastic/elasticsearch#31981]
**Elasticsearch version** (`bin/elasticsearch --version`):

Docker Elastic `docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4`

**OS version** (`uname -a` if on a Unix-like system):

Microsoft Windows [Version 10.0.17134.165]

**Description of the problem including expected versus actual behavior**:

After adding a document, searching for "cowan nsw seaplane" produces no results. However searching for "cowan AND nsw AND seaplane" produces the expected result. Playing around with the terms shows that the text cowan appears to be causing issues? Is this a reserved word or some such? Steps to reproduce below.

**Steps to reproduce**:

 1.

```
docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -d docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
```

 2.
```
POST http://localhost:9200/metadata/meta/
{
  "meta": {
    "place": [
      "COWAN,NSW,AUSTRALIA"
    ],
    "description": "SEAPLANE CRASHES INTO HAWKESBURY RIVER AT JERUSALEM BAY, POLICE CONFIRM THE 6 PEOPLE ON BOARD DID NOT SURVIVE, 3 BODIES HAVE BEEN RECOVERED SO FAR"
  }
}

RESPONSE
{
    "_index": "metadata",
    "_type": "meta",
    "_id": "W31qjGQBqyAQ5SdCNt4J",
    "_version": 1,
    "result": "created",
    "_shards": {
        "total": 2,
        "successful": 1,
        "failed": 0
    },
    "_seq_no": 0,
    "_primary_term": 1
}
```
 3.
```
POST http://localhost:9200/metadata/meta/_search/
{
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "seaplane hawkesbury cowan",
            "default_operator": "AND",
            "fields": [
		    	"meta.place",
		        "meta.description"
            ]
          }
        }
      ]
    }
  }
}

RESPONSE
{
    "took": 5,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 0,
        "max_score": null,
        "hits": []
    }
}
```
4. 
```
POST http://localhost:9200/metadata/meta/_search/
{
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "seaplane AND hawkesbury AND cowan",
            "default_operator": "AND",
            "fields": [
		    	"meta.place",
		        "meta.description"
            ]
          }
        }
      ]
    }
  }
}

RESPONSE
{
    "took": 4,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 1,
        "max_score": 0.8630463,
        "hits": [
            {
                "_index": "metadata",
                "_type": "meta",
                "_id": "W31qjGQBqyAQ5SdCNt4J",
                "_score": 0.8630463,
                "_source": {
                    "meta": {
                        "place": [
                            "COWAN,NSW,AUSTRALIA"
                        ],
                        "description": "SEAPLANE CRASHES INTO HAWKESBURY RIVER AT JERUSALEM BAY, POLICE CONFIRM THE 6 PEOPLE ON BOARD DID NOT SURVIVE, 3 BODIES HAVE BEEN RECOVERED SO FAR"
                    }
                }
            }
        ]
    }
}
```

**Comment by jimczi** [comment]
This is expected since in 6.x the `query_string` does not split on whitespace anymore. By default in 6.x a query like `seaplane hawkesbury cowan` will build one query per field where all terms are mandatory if the `default_operator` is `AND`. You can restore the `cross_fields` matching by setting the`type` option to [`cross_fields`](
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#multi-match-types) but fields are grouped by analyzer so it won't work if your fields do not share the same analyzer/type. If this is the case for you (fields do not share the same analyzer) you have no choice but to add an explicit operator where you need a split. I am going to close the issue because the behavior is expected, @boyter please comment if the proposed workaround does not work for you and we can reopen if needed.

**Comment by boyter** [comment]
@jimczi Ah that explains it. I was coming from older versions where `_all` was there and resolved a lot of these issues. Annoying, but not a huge issue in this case as they all have the same analyzer and type.

Is the recommendation to create a new `_all` during indexing to avoid this in the future and search across that?
