### ISSUE TITLE
SQL: Consider adding support for multiple fields and indices

### ISSUE THREAD

**Issue by gufeng20081010** [elastic/elasticsearch#31990]
At the moment, ES SQL supports group by only one field and search one indices. Would be helpful to also support multiple fields and indices .
Like this： select count (*) from index1, index2 group by field1, field2

**Comment by astefan** [comment]
Grouping by multiple fields is possible and the change was merged quite recently: https://github.com/elastic/elasticsearch/pull/31818

But, when it comes to searching multiple indices, you can do this by defining an alias in Elasticsearch that will include those indices, but **with the restriction** of indices having identical mappings. There is an issue already created for improving this: https://github.com/elastic/elasticsearch/issues/31837
