### ISSUE TITLE
Provide ability to have simple calculated "fields" for a scalar properties during ingestion

### ISSUE THREAD

**Issue by roytmana** [elastic/elasticsearch#32019]
When elastic index represents a real world business entity whos JSON representation is important in itself we would not want introduce additional properties that may be needed to make searching or aggregations more performant/simple/useful. 

It would be very helpful if it were possible to define fields within a given scalar property which are calculated based on property value during indexing using painless or lucene expression script.

Example below creates a `"not-zero"` field on a cost field because in my hypothetical use case it is important to efficiently and simply report on free vs paid items

```javascript
  "cost": {
    "type": "long",
    "fields": {
      "not_zero": {
        "type": "boolean",
        "script": {
          "lang": "expression",
          "source": "value > 0" //value is the value of the property
        }
      }
    }
  }
```
Ideally script would have two predefined parameters - property value and document being indexed properties of which could be accessible via dot-notation so that more complex computations could be made. But even just the value itself would be very useful for simple transformations

**Comment by colings86** [comment]
I don't think this type of thing belongs in the mappings, to me this should be a pre-processing step and shouldn't involve mappings which are there to define the schema not to transform the input data. 

One way to achieve this as a pre-processing step is to use an ingest pipeline which contains a [script processor](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/script-processor.html) to add the `non_zero` field to the document and then have the `non-zero` mapped as a standard boolean field in the mappings.

**Comment by roytmana** [comment]
@colings86 Maybe I did not explain in well but i do not want to add `non_zero` to my document (which represents a real world business entity, widely used and not to be polluted with derivative properties such as `non_zero` needed for efficiency of queries and aggregations. all I want is for it to be in lucene but not the _source. Think of it as the common practice of having several fields with different analyzers defined on a single property (ex: shingled, stemmed, keyword in addition to standard text defined on the property itself) - same concept. Another example of derived fields is for every important date field in my document i may want to have fields that compute fiscal year, fiscal month, fiscal quarter quarter to support aggregations on them instead of polluting my document with those fields or using scripts at runtime. Once again it is not about how to put these in the document (i do not need reprocessing for it I am in full control (technically) of the document content and can easily add all those derived fields to it before i submit it to elastic. it is about producing lucene fields needed for searches and analytics without affecting the document itself

**Comment by jpountz** [comment]
Hello @roytmana. We discussed it in FixitFriday and think that there are easy workarounds that don't require adding such features. For instance assuming that your document initially looks like this:

```
{
  "foo": "bar",
  "cost": 42
}
```

you could map your document like this:

```
{
  "properties": {
    "foo": {
      "type": "keyword"
    },
    "cost": {
      "type": "long"
    },
    "cost_not_zero": {
      "type": "boolean"
    },
    "original_document": {
      "type": "object",
      "enabled": false // causes nothing to be indexed, only stored
    }
  }
}
```

and have your documents look like this:

```
{
  "original_document": {
    "foo": "bar",
    "cost": 42
  },
  "foo": "bar",
  "cost": 42,
  "cost_not_zero": true
}
```

This way, you still always have access to the original document. It might look a bit heavy in terms of storage, but duplicates are actually something that the compression algorithm that is used under the hood deals with very efficiently, so it would have little overhead.

**Comment by roytmana** [comment]
Hi @jpountz ,

Thank you for looking into it. It was not really about a work around - I thought it would be a rather useful extension of "fields" concept which for cases of multiple analyzers on a single property works extremely well in organizing those different representations of a property value

Thank you,
alex
