### ISSUE TITLE
file missing in rpm installation

### ISSUE THREAD

**Issue by IzekChen** [elastic/elasticsearch#32023]
When I use yum upgrade from 6.3.0-1 to 6.3.1-1
It shows a file is missing
md5sum: /etc/elasticsearch/.elasticsearch.keystore.initial_md5sum: No such file or directory

![image](https://user-images.githubusercontent.com/7790230/42676922-89729498-86ac-11e8-988e-333491321dfd.png)

**Comment by jkakavas** [comment]
Possibly related to https://github.com/elastic/elasticsearch/pull/29121

**Comment by rjernst** [comment]
This was fixed last year and we have packaging tests to ensure it is not broken again.
