### ISSUE TITLE
Add breaking change for upgrades to 6.3 when using the file realm

### ISSUE THREAD

**Issue by jakommo** [elastic/elasticsearch#32038]
When upgrading to 6.3 and using the file realm, the default location for the `users, roles.yml etc` files changed from `config/x-pack` to `config/`.
We do have a [fallback in place](https://github.com/elastic/elasticsearch/blob/6.3/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/XPackPlugin.java#L308-L319), however this only kicks in if e.g. the `config/users` file is not found, in which case it would use `config/x-pack/users`.

The problem is that, e.g. the 6.3.1 PRM, does create an empty `config/users` file upon upgrade of the package, which prevents the fallback from kicking in. 

There are two ways to solve this:
* Either remove the newly created `{users,users_role,roles.yml,role_mapping.yml}` from `/etc/elasticsearch`, so that the fallback is reading the "old" files from `/etc/elasticsearch/x-pack/`
* Move `{users,users_role,roles.yml,role_mapping.yml}`  from `/etc/elasticsearch/x-pack/` to `/etc/elasticsearch`

This should be added as breaking change of 6.3 so users of the file realm are aware of this when they upgrade. 

Pining @elastic/es-core-infra as this might also affect packaging. 
Slightly related https://github.com/elastic/elasticsearch/issues/31465

**Comment by rjernst** [comment]
While this change would have been good, 6.3 is long past its maintenance lifetime. Closing as this hasn't come up again since the default distro became the norm.
