### ISSUE TITLE
Watcher: Decouple history index cleaning from monitoring

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#32041]
Monitoring has a `xpack.watcher.history.cleaner_service.enabled` setting to clean out old watcher history index settings.

This setting should be correctly parsed on the watcher side of things and also work properly if monitoring is disabled, probably by just switching to ILM soon.

**Comment by JalehD** [comment]
@hub-cap can we revive this please, the issue of these indices not being cleaned gets magnified in cloud land. You can spin up a small cluster and it will auto destruct itself by filling up disk with watcher.history stuff 🗡

**Comment by JalehD** [comment]
@elastic/cloud-pms FYI
