### ISSUE TITLE
In master when starting a trial users get locked out

### ISSUE THREAD

**Issue by AlonaNadler** [elastic/elasticsearch#32057]
**Elasticsearch version** (`bin/elasticsearch --version`): master

**Description of the problem including expected versus actual behavior**: 
When using master with basic license and starting a trial, security should be disabled by default, currently, in master, it is enabled by default so when starting a trial the user gets locked out 

![trial_license](https://user-images.githubusercontent.com/32550316/42713823-a76091fa-86a5-11e8-91ca-bcf3303bad0b.gif)

cc: @zuketo @eskibars

**Comment by tylersmalley** [comment]
Tracked this down to an issue in the Kibana developer tools for running ES.
