### ISSUE TITLE
A problem occurred evaluating project ':client:rest'.

### ISSUE THREAD

**Issue by easyishappy** [elastic/elasticsearch#32062]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by Heeexy** [comment]
hello ,  how did you resolve it?

**Comment by Heeexy** [comment]
https://github.com/elastic/elasticsearch/issues/31236

I changed gradle version  to the version in elasticsearch-master\gradle\wrapper\gradle-wrapper.properties

it works

**Comment by nik9000** [comment]
We've just [recently](https://github.com/elastic/elasticsearch/pull/32200) added enforcement to the build to check this. Sorry for the trouble!
