### ISSUE TITLE
Inconsistency between treating boolean type in aggs and term queries

### ISSUE THREAD

**Issue by roytmana** [elastic/elasticsearch#32069]
When aggregating on a boolean field elastic put 0/1 as aggregation key however when performing a term query on the same field using 0/1 values fails with exception. I think it should be consistent either true/false should be used as agg bucket key or term query on a boolean field should accept 0/1 as valid values (in addition to true/false). As it is I can't consistency use aggregation key to produce queries drill down into documents behind a given aggregation

**Comment by jpountz** [comment]
I agree that the fact that aggregations leak the underlying way that data is stored is annoying. For reference I'd like to fix it by replacing the existing key/key_as_string keys in the response with a single key that would contain data in the appropriate type, ie. a formatted string for dates and a boolean for booleans. #18518

**Comment by jpountz** [comment]
Closing in favor of #18518
