### ISSUE TITLE
SQL JDBC: enquoting literals and simple identifiers in JDBC 4.3

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#32084]
A set of four methods have been added to `java.sql.Statement` dealing with enquoting literals and simple identifiers: `enquoteIdentifer`, `enquoteLiteral`, `enquoteNCharLiteral`, and `isSimpleIdentifier`. Look into implementing this as part of ES SQL JDBC support.
Spin off from https://github.com/elastic/elasticsearch/issues/31881

**Comment by wchaparro** [comment]
Closing as not planned, superceded by our work in ES|QL. Please reopen if you have concerns.
