### ISSUE TITLE
SQL JDBC: investigate the new beginRequest and endRequest methods added to java.sql.Connection in JDBC 4.3

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#32082]
JDBC 4.3 added two new methods that should be used by Connections pooling managers to indicate the beginning and ending of a unit of work (a Connection). Probably will not be used by ES SQL, since we do not support connection pooling, but should evaluate all the implications.
Spin off from https://github.com/elastic/elasticsearch/issues/31881.

**Comment by wchaparro** [comment]
superceded by ES|QL
