### ISSUE TITLE
Change kibana_user and kibana_dashboard_only_user to use application privileges

### ISSUE THREAD

**Issue by kobelb** [elastic/elasticsearch#32091]
Now that we have the application privileges in place, and we're reviewing https://github.com/elastic/kibana/pull/19723 , we'll want to switch the `kibana_user` and `kibana_dashboard_only_user` roles to utilize the new application privileges and no longer have direct access to the `.kibana*` indices.

We'd like the `kibana_user` role to have the `all` privilege on `*` resources; and the `kibana_dashboard_only_user` role to have the `read` privilege on `*` resources.

It should be noted that we won't want to merge this change until https://github.com/elastic/kibana/pull/19723 merges, or else we risk making existing users with the `kibana_user` roles non-functional.

**Comment by jaymode** [comment]
@kobelb this will prevent users from using kibana until kibana has also been upgraded if I understand correctly. I'm just pointing this out because we'll need to document this.

**Comment by kobelb** [comment]
> @kobelb this will prevent users from using kibana until kibana has also been upgraded if I understand correctly. I'm just pointing this out because we'll need to document this.

That's a good point, and something we should definitely document because I can't think of a way around this.

**Comment by kobelb** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/32137
