### ISSUE TITLE
How to implement the use of and and or in SQL

### ISSUE THREAD

**Issue by heartlhj** [elastic/elasticsearch#32149]
Like SQL (SELECT NAME,AGE FORM USER WHERE 1=1 AND AGE=25 AND (NAME LIKE '%TOM%' OR 
NAME LIKE '%JASPER%').How do I implement it with elasticsearch.
If user 
{
   "bool" : {
      "must" :     [],
      "should" :   []
   }
}
As long as must is met, it hits, regardless of whether or not should hits. The current demand is to have at least one should hit.What shall I do?

**Comment by heartlhj** [comment]
have already been solved

**Comment by dadoonet** [comment]
@heartlhj Great. If you have further questions, please ask on discuss.elastic.co where we can give a better support. Thanks.
