### ISSUE TITLE
es transport layer cost too much time exception

### ISSUE THREAD

**Issue by weizijun** [elastic/elasticsearch#32150]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
2.3.3

**Plugins installed**: []
delete-by-query
license
marvel-agent

**JVM version** (`java -version`):
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
2.6.32-573.18.1.el6.toav2.x86_64 #1 SMP Sun Jul 17 12:44:29 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
client send search request to tribenode, but the transport layer cost too much time.This case  happens accidentally.But everyday it appears.

	 public class ReleaseChannelFutureListener implements ChannelFutureListener {
		private final ESLogger tracerLog = Loggers.getLogger("requestIdLog");

	    private final Releasable releasable;
	    
	    private TransportResponse response;
	    
	    private long requestId;

	    public ReleaseChannelFutureListener(Releasable releasable) {
	        this.releasable = releasable;
	    }
	    
	    public ReleaseChannelFutureListener(Releasable releasable, TransportResponse response, long requestId) {
	        this.releasable = releasable;
	        this.response = response;
	        this.requestId = requestId;
	    }

	    @Override
	    public void operationComplete(ChannelFuture future) throws Exception {
	        releasable.close();
	        
	        if (response instanceof SearchResponse
	        		|| response instanceof MultiSearchResponse) {
	        	tracerLog.warn("[{}] sentResponse operationComplete", requestId);
	        }
	    }
	}

	NettyTransportChannel.sendResponse:
	ReleaseChannelFutureListener listener = new ReleaseChannelFutureListener(bytes, response, requestId);

**Provide logs (if relevant)**:
search dsl:
{"size":1,"query":{"bool":{"filter":[{"term":{"dltag":"_com_request_in"}},{"term":{"uri":"/gulfstream/openapi-inner/v1/info/passenger"}}],"should":[{"range":{"logTime":{"gte":1531783800000,"lte":1531784399000,"format":"epoch_millis"}}}]}},"_source":{"includes":["traceid","spanid"],"excludes":[]}}

responseLen=377
tookInMillis=16944

client log
[TRACE][2018-07-18 09:13:14,359][78150089][rest-es-thread-8][TransportService.java:650] [Exterminator] [2090581][indices:data/read/search] sent to [{...}}{max_local_storage_nodes=1, client=true, data=false, master=false}] (timeout: [null])
[TRACE][2018-07-18 09:13:44,929][78180659][elasticsearch[Exterminator][transport_client_worker][T#1]{New I/O worker #391}][TransportService.java:642] [Exterminator] [2090581][indices:data/read/search] received response from [{...}{max_local_storage_nodes=1, client=true, data=false, master=false}]

tribenode log
[2018-07-18 09:13:14,359][TRACE ][transport.tracer         ] [xxx] [2090581][indices:data/read/search] received request
[2018-07-18 09:13:31,326][TRACE ][transport.tracer         ] [xxx] [2090581][indices:data/read/search] sent response
[2018-07-18 09:13:44,929][WARN ][requestIdLog             ] [2090581] sentResponse operationComplete

**Comment by jasontedor** [comment]
Sorry but Elasticsearch 2.x is end of life. If you can reproduce this on the latest release we could take a look. If you can’t, you can try the [forum](https://discuss.elastic.co).
