### ISSUE TITLE
Feature request: minimum_nested_match

### ISSUE THREAD

**Issue by robtesch** [elastic/elasticsearch#32165]
**Describe the feature**:

I would love to see an option of a nested query where instead of returning parent docs where any nested doc matches a nested query, there could be an option to return only parent docs when some minimum number of nested docs matched. Similar to the way we set up minimum_should_match. In my particular case I would want to only return parent docs where ALL the nested docs match a specific query.

Example:

```
PUT test
{
  "mappings": {
    "_doc": {
      "properties": {
        "comments": {
          "type": "nested"
        }
      }
    }
  }
}
```

```
PUT test/_doc/1?refresh
{
  "title": "Test title",
  "comments": [
    {
      "author": "kimchy",
      "number": 1
    },
    {
      "author": "nik9000",
      "number": 2
    }
  ]
}
```

```
PUT test/_doc/2?refresh
{
  "title": "Test title 2",
  "comments": [
    {
      "author": "kimchy",
      "number": 1
    },
    {
      "author": "kimchy",
      "number": 2
    }
  ]
}
```

Then, in order to only match doc 2, where all the nested docs match the query:

```
POST test/_search
{
  "query": {
    "nested": {
      "path": "comments",
      "query": {
        "match": {"comments.author" : "kimchy"}
      },
      "minimum_nested_match": "100%",
    }
  }
}
```

Perhaps there is already some way of doing this that I don't know about?

**Comment by jpountz** [comment]
Closing in favor of #10043.
