### ISSUE TITLE
CCE when re-throwing "shard not available" exception in TransportShardMultiGetAction

### ISSUE THREAD

**Issue by sabi0** [elastic/elasticsearch#32173]
https://github.com/elastic/elasticsearch/blob/cfb30144c9175d1f1538af0aa5c1841f72159128/server/src/main/java/org/elasticsearch/action/get/TransportShardMultiGetAction.java#L95

`TransportActions.isShardNotAvailableException()` is also `true` for Lucene's `AlreadyClosedException`, which is not `ElasticsearchException` sub-class.
When that happens CCE will be thrown instead of re-throwing the actual exception.

**Comment by ashokn** [comment]
I would like to work on this issue 
@dnhatn

**Comment by itsnotv** [comment]
@ashokn missed your comment and submitted a PR. Let me know if my change is good.

**Comment by itsnotv** [comment]
@sabi0 I can't find TransportShardMultiPercolateAction in master, I have fixed for TransportShardMultiTermsVectorAction.

**Comment by sabi0** [comment]
@itsnotv Sorry, I was looking the older version of the source. There isn't `TransportShardMultiPercolateAction` in master anymore, indeed.
