### ISSUE TITLE
Need clarification LB send request to data node 

### ISSUE THREAD

**Issue by cloudmelon** [elastic/elasticsearch#32198]
Hi, I am deploying ES with Docker, but I would like to deploy 3 dedicated master node and a couple of data node in the cluster ( huge cluster can be scaled up to100 instances ) , is there any way to deploy a master node by Azure VMs and a data node by VMSS?

As data node and master node can communicate with each other via the network call, so load balancer can send the request directly to data node cluster ? 

Many Thanks !

**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by romseygeek** [comment]
Elastic has a discussion forum at https://discuss.elastic.co/c/elasticsearch where we can provide support for this kind of question.  We use github for tracking identified bugs and feature requests.  As this is a question more suited to the forums, I hope you don't mind me closing this.
