### ISSUE TITLE
Geo Context suggester not working in version 5.5.2

### ISSUE THREAD

**Issue by vandanachadha** [elastic/elasticsearch#32202]
I ned to use the geo context for my autocomplete. But it is not returning any results. When I run the autocomplete query without the context, results are returned.

1. Autocomplete query with context:
===============================
GET staging/_search
{
     "suggest": {
        "suggestion": {
          "prefix": "Südsteiermark",
          "completion": {
            "field": "autoCompleteName",
            "size": 10,
            "contexts": {
              "locationContext": [{
                "lat": "40.74164831951294",
                "lon": "-73.98714780807495",
                "precision": 12
              }]
            }
          }
        }
     }
}
==================================
RESULT of Autocomplete query with context
====================================
{
  "took": 0,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  },
  "suggest": {
    "suggestion": [
      {
        "text": "Südsteiermark",
        "offset": 0,
        "length": 13,
        "options": []
      }
    ]
  }
}
===================================

3. RESULT OF QUERY WITHOUT CONTEXT:
===========================
  "took": 1713,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": 0,
    "hits": []
  },
  "suggest": {
    "suggestion": [
      {
        "text": "Südsteiermark",
        "offset": 0,
        "length": 13,
        "options": [
          {
            "text": "Südsteiermark, Tement, Zieregg 2008",
            "_index": "staging",
            "_type": "menuitemES",
            "_id": "591df0affa035585189619510x3bc",
            "_score": 1,
            "_source": {
              "venueId": "457ebeaaf964a5203f3f1fe3",
              "name": "Eleven Madison Park",
              "locP": {
                "type": "Point",
                "coordinates": [
                  40.74164831951294,
                  -73.98714780807495
                ]

========================================

4. Mapping portion:
          "autoCompleteName": {
            "type": "completion",
            "analyzer": "standard",
            "preserve_separators": true,
            "preserve_position_increments": false,
            "max_input_length": 50,
            "contexts": [
                {
                    "name":"locationContext",
                    "type":"geo",
                    "precision":"25m",
                    "path":"locP"
                }
            ]
=====================================

Please suggest what is wrong.

**Comment by imotov** [comment]
@vandanachadha could you make sure that `locP` has a `geo_point` type? By looking at your output I suspect it might be mapped as an object. I was trying to reproduce it with 6.3.1 and everything seems to work as expected after I applied the proper mapping and fixed the locP format. This is the reproduction that I used:

```
DELETE test

PUT test
{
  "mappings": {
    "doc": {
      "properties": {
        "autoCompleteName": {
          "type": "completion",
          "analyzer": "standard",
          "preserve_separators": true,
          "preserve_position_increments": false,
          "max_input_length": 50,
          "contexts": [
            {
              "name": "locationContext",
              "type": "geo",
              "precision": "25m",
              "path": "locP"
            }
          ]
        },
        "locP": {
          "type": "geo_point"
        }
      }
    }
  }
}


PUT test/doc/1
{
  "venueId": "457ebeaaf964a5203f3f1fe3",
  "name": "Eleven Madison Park",
  "locP": {
    "lat": 40.74164831951294,
    "lon": -73.98714780807495
  },
  "autoCompleteName": "Südsteiermark, Tement, Zieregg 2008"
}

GET test/doc/_search
{
  "suggest": {
    "suggestion": {
      "prefix": "Südsteiermark",
      "completion": {
        "field": "autoCompleteName",
        "size": 10,
        "contexts": {
          "locationContext": [
            {
              "lat": "40.74164831951294",
              "lon": "-73.98714780807495",
              "precision": 12
            }
          ]
        }
      }
    }
  }
}
```

In the future when you have questions like this, it might be the best to start with asking them in our discussion forum https://discuss.elastic.co/ Also having a small reproduction similar to one I pasted above instead of small bits and pieces really helps the person who is trying to understand your issue and help you. 


Saying this, I have to agree, that is indeed trappy, and we should probably add additional check to make sure that something like this causes an error message instead of silently ignoring the context:

```
PUT test
{
  "mappings": {
    "doc": {
      "properties": {
        "autoCompleteName": {
          "type": "completion",
          "analyzer": "standard",
          "preserve_separators": true,
          "preserve_position_increments": false,
          "max_input_length": 50,
          "contexts": [
            {
              "name": "locationContext",
              "type": "geo",
              "precision": "25m",
              "path": "locP"
            }
          ]
        },
        "locP": {
          "type": "object"
        }
      }
    }
  }
}
```

I can see [some code](https://github.com/elastic/elasticsearch/blob/15ff3da653c5dd9eae7f7a654a9ee6a931d478b7/server/src/main/java/org/elasticsearch/search/suggest/completion/context/GeoContextMapping.java#L141-L144) that seems to be there to prevent this from happening, but it doesn't seem to work. I will dig into it next week.

**Comment by imotov** [comment]
@vandanachadha I would need to see your document to answer that question. I cannot reproduce this error based on your description.

**Comment by vandanachadha** [comment]
@imotov 
The number_format error got fixed once I removed the "store true" from the geo-point mapping:
"locP": {
"properties": {
"coordinates": {
"type": "geo_point",
"store": true
}

Dont understand why though.

But thanks a lot for putting me in the right direction for using the correct property for geo context. My suggest now works with geo-context

**Comment by imotov** [comment]
@vandanachadha Thank you for letting me know about this, I am looking into this code at the moment and going to try fixing this issue as well.
