### ISSUE TITLE
Expose cluster uuid in _cluster/stats endpoint

### ISSUE THREAD

**Issue by ycombinator** [elastic/elasticsearch#32205]
Metricbeat would like to collect cluster stats from the Elasticsearch cluster stats API (`GET _cluster/stats`). In a similar vein to #31791, please expose `cluster_uuid` as a field in the API response. This would help Metricbeat avoid making an additional API request to Elasticsearch to fetch the cluster UUID.

**Comment by jasontedor** [comment]
@ycombinator Note for the future that we do not require an issue if you're going to open a PR for it. As long as the PR explains why the change is being made, we consider that enough and prefer to minimize the overhead of additional issues.

**Comment by ycombinator** [comment]
Good to know, thanks @jasontedor!
