### ISSUE TITLE
watcher es_redacted handling of passwords does not allow changes properly for attachment sections of email actions

### ISSUE THREAD

**Issue by mikeh-elastic** [elastic/elasticsearch#32210]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.3
**Plugins installed**: []
x-pack
**JVM version** (`java -version`):
Elastic cloud and Java 8 for nodes on Linux
**OS version** (`uname -a` if on a Unix-like system):
Elastic cloud instance but also node on Linux
**Description of the problem including expected versus actual behavior**:
When attempting to edit a watch where the es_redacted handling of passwords is triggered you cannot remove or modify a block of the watch via the watcher ui or via API calls.

**Steps to reproduce**:
PUT _xpack/watcher/watch/testing_teams
{
  "trigger": {
    "schedule": {
      "cron": "0 0 11 ? * MON *"
    }
  },
  "input": {
    "none": {}
  },
  "condition": {
    "always": {}
  },
  "actions": {
    "email_admin": {
      "email": {
        "profile": "standard",
        "attachments": {
          "reddit_report.pdf": {
            "reporting": {
              "url": "[REPORT GENERATION URL]",
              "retries": 6,
              "interval": "30s",
              "auth": {
                "basic": {
                  "username": "asdfasdf",
                  "password": "dfgsdfg"
                }
              }
            }
          }
        },
        "to": [
          "'Recipient Name <youremail@elastic.co>'"
        ],
        "subject": "Reddit Weekly Report",
        "body": {
          "text": "Good morning,\n\nAttached is a visual dashboard and an excel report on your mentions on reddit over the last week.\n\nFor a full list of subreddits monitored or a request to change this reporting, contact the team at youremail@elastic.co\n\nThank you,\nThe Team"
        }
      }
    }
  }
}

2.  Change reddit_report.pdf to reddit_report2.pdf and run the PUT again (or via the UI), the reddit_report.pdf will not be replaced but exist along with the reddit_report2.pdf block when you GET or view the watch in the UI.

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
