### ISSUE TITLE
[DOCS] Improve documentation on Watcher secure_ settings for notification actions

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#32217]
Watcher documentation can be improved when it comes to secure settings. 

For example, in this [section](https://www.elastic.co/guide/en/elastic-stack-overview/current/actions-slack.html#configuring-slack):

>To configure a Slack account, at a minimum you need to specify the account name and webhook URL in the elasticsearch keystore (see secure settings):
bin/elasticsearch-keystore add xpack.notification.slack.account.monitoring.secure_url
You can also configure this via settings in the elasticsearch.yml file by removing the secure_ prefix, but using the keystore is the preferred and secure way of doing this.

It talks about how the account name and webhook URL are required, but they can either be set as secure or regular settings (both are supported).

Suggested improvements:

- "at a minimum you need to specify the account name".  Not really clear what this means and the example following shows only `xpack.notification.slack.account.monitoring.secure_url`, there is not a separate "account name" setting.  I think we mean that in this case, "monitoring" is the account name (i.e. a custom account name because you can define multiple account names under xpack.notification.slack.account), so by specifying xpack.notification.slack.account.monitoring as part of the setting name, the account name is already implied via the secure_url setting.
- It doesn't clarify when using the settings in the yml, the setting name is different.  It can be helpful to note that when not using secure settings, the setting name is `xpack.notification.slack.account.monitoring.url`.  Alternatively, we can link to this section of the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/notification-settings.html#slack-notification-settings) with the Slack settings.  However, this section of the documentation should also list out the secure setting (we already do that in the general x-pack settings documentation and on the same page when we talk about TLS settings for Watcher).  Currently, the Slack notification section only specifies `url` as a valid setting, not `secure_url`.   Something like the following can help:

url
The Incoming Webhook URL to use to post messages to Slack.  Either url or secure_url (in the keystore) is required.

secure_url (<link to Secure settings>)
The Incoming Webhook URL to use to post messages to Slack when using the keystore.  Either url or secure_url (in the keystore) is required.

We will want to make similar changes to the other Watcher notification settings section so that we are documenting both regular and secure_ forms of the settings for the other actions as well.

**Comment by jrodewig** [comment]
[docs issue triage]

Leaving open. This is still relevant:
https://www.elastic.co/guide/en/elasticsearch/reference/master/actions-slack.html#configuring-slack

**Comment by ppf2** [comment]
btw, [starting in 7.0](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html#watcher-notifications-account-settings), we no longer allow `xpack.notification.slack.account.monitoring.url` as a setting and only support `xpack.notification.slack.account.monitoring.secure_url`.  So the paragraph above suggesting clarification to xpack.notification.slack.account.monitoring.url is no longer relevant.

**Comment by mohitzim** [comment]
@ppf2 : How can we configure `xpack.notification.slack.account.monitoring.secure_url` using docker based elasticsearch. We use environment keys to define elasticsearch settings inside docker-compose.yml. 
Can you please guide in this?
