### ISSUE TITLE
Newly created shards are unbalanced after joining a new machine

### ISSUE THREAD

**Issue by zcola** [elastic/elasticsearch#32230]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.9

**Plugins installed**: []

**JVM version** (`java -version`):jdk8

**OS version** (`uname -a` if on a Unix-like system):debian

**Description of the problem including expected versus actual behavior**:

* 35 data hot nodes, 100+ fragments per node
* 60 data cold nodes
* Index template sets index_per_node to 2

Joined 4 new data hot nodes and performed "shard reblance".

When the new index 70+ is created the next day (the size of each index is not the same as the number of shards), the newly added data hot nodes are each assigned 40+ shards, and the old data hot nodes are only allocated 20 + shards

The result is that logstash has a lot of "write 429" and needs to exclude the index from some nodes.

**Comment by colings86** [comment]
@zcola Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.

**Comment by zcola** [comment]
Is this not a bug?
Is this not a bug?
Is this not a bug?
