### ISSUE TITLE
REST high-level client: check naming conventions for xpack API

### ISSUE THREAD

**Issue by javanna** [elastic/elasticsearch#32245]
As a follow-up of #31825 we should look into checking naming conventions also for xpack API that are being added to the REST high-level client. There's currently [this TODO](https://github.com/elastic/elasticsearch/blob/master/client/rest-high-level/src/test/java/org/elasticsearch/client/RestHighLevelClientTests.java#L750) that needs to be addressed around that.

**Comment by hub-cap** [comment]
ty for adding @javanna
