### ISSUE TITLE
Java High Level REST Client  Some questions about the Search

### ISSUE THREAD

**Issue by javavito** [elastic/elasticsearch#32264]
Hi!, How to find multiple search criteria together?for example:
`SearchSourceBuilder searchSourceBuilder = new SearchSourceBuilder();
RangeQueryBuilder rangequerybuilder = QueryBuilders
                .rangeQuery("order_calculate_time_1")
                .from("2018-07-20 17:36:00").to("2018-07-20 17:40:00");
TermsQueryBuilder termsQueryBuilder = QueryBuilders.termsQuery("lottery_type_id_0", "0");
searchSourceBuilder.query(rangequerybuilder).query(termsQueryBuilder);
`
I have tried this method,Not the right way.
To find out results that all search criteria meet

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
