### ISSUE TITLE
dose ESSQL support this syntax like(select c1,c2,count(*) from index1 group by c1,c2) in elasticsearch6.3?

### ISSUE THREAD

**Issue by wenfang6** [elastic/elasticsearch#32275]
dose ESSQL support this syntax like(select c1,c2,count(*) from index1 group by c1,c2) in elasticsearch6.3?
what about subqueries???         does  ESSQL support it ?

**Comment by tvernum** [comment]
Please do not open issues to ask questions.
The first point in the issue template is:

> 1.  GitHub is reserved for bug reports and feature requests. The best place to
    ask a general question is at the Elastic [forums](https://discuss.elastic.co).
    GitHub is not the place for general questions.

Please ask your questions on that forum.
