### ISSUE TITLE
Support TLSv1.3 when running on Java 11

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#32276]
Java 11 will include support for TLS 1.3.

X-Pack SSL includes specific behaviours around TLS versions including:
- Default values for supported versions `XPackSettings.DEFAULT_SUPPORTED_PROTOCOLS`
- Configurable version support `SSLConfigurationSettings.supportedProtocols`
- Mapping those setting strings to TLS algorithm names `SSLService.sslContextAlgorithm`

Plus we have tests for the above.

Customers who run on Java 11 may wish to enable TLSv1.3, but we
- will reject it as a value in `sslContextAlgorithm` if it comes before TLSv1.2
- don't test it
- don't document how to enable it

**Comment by tbrooks8** [comment]
`AbstractSimpleSecurityTransportTestCase#testRenegotiation` will probably need to be adjusted when we enable TLS 1.3 as I believe that TLS 1.3 does not support renegotiation.
