### ISSUE TITLE
Support additional TLS settings for the SQL CLI client 

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#32306]
Currently SQL CLI client only allows to define key/trust configuration by passing `keystore_location` arg that is then used for both `ssl.keystore.location` and `ssl.truststore.location`. 

We should support an independent setting for the truststore. Additionally, we should also support setting the key/trust configuration using PEM files for keys and certificates in the same manner as we do for Elasticsearch ssl settings. 

The caveat is that since this code needs to be able to run standalone, it cannot depend on Elasticsearch and as such cannot use `PemUtils` for reading TLS private keys from file. Alternatives would include copying PemUtils functionality here or depending on BouncyCastle.

**Comment by tvernum** [comment]
This should be able to use the [ssl-config](https://github.com/elastic/elasticsearch/tree/6.7/libs/ssl-config) jar to support the full range of `ssl.*` options that the rest of the stack uses, without pulling in any additional dependencies (ssl-config depends only on elasticsearch-core, which is already an sql-cli dependency via elasticsearch-cli).

**Comment by wchaparro** [comment]
superceded by ES|QL
