### ISSUE TITLE
Enable S3 repo temporary/EC2/ECS credentials tests for third-party tests

### ISSUE THREAD

**Issue by vladimirdolzhenko** [elastic/elasticsearch#32318]
temporary/EC2/ECS credentials tests for `repository-s3` are disabled for third-party tests

See: #31919 and #32315

It is required to extend configuration of CI build to support env variables 
* `amazon_s3_access_key_temporary`, `amazon_s3_secret_key_temporary`, `amazon_s3_session_token_temporary`, `amazon_s3_bucket_temporary`, `amazon_s3_base_path_temporary`
* `amazon_s3_bucket_ec2`, `amazon_s3_base_path_ec2` 
* `amazon_s3_bucket_ecs`, `amazon_s3_base_path_ecs`

**Comment by original-brownbear** [comment]
I'm closing this one as it doesn't really get us anything to run the temporary/EC2/ECS test suits against real S3. They are just subsets of the currently running permanent credentials suit at this point anyway.
We can maybe look into drying the tests up here to make that fact more obvious but running redundant tests against real S3 is unnecessary.
