### ISSUE TITLE
Support further comparison using the result of bucket aggregation

### ISSUE THREAD

**Issue by ranranxiaoya** [elastic/elasticsearch#32311]
**Describe the feature**:

We want to do the following:
1. Get the average(for example, AVG ) of field-A for every 5 minutes.
2. Return the bucket where AVG is above 10 for example.

Will this request be supported in the future?

**Comment by atorok** [comment]
@ranranxiaoya  this seems to be something you could achieve with [search-aggregations-pipeline-bucket-selector-aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-selector-aggregation.html). Can you please offer more details if what you are describing is different ?

**Comment by ranranxiaoya** [comment]
This is exactly what i need, thank you very much.
