### ISSUE TITLE
I have a question about histogram and time zone

### ISSUE THREAD

**Issue by kklingjie** [elastic/elasticsearch#32317]
I have a question about histogram :
--------------------------------------------

Data source:
---------------------

"hits": [
         {
            "_index": "log",
            "_type": "accesslog",
            "_id": "5b2977e843644c8a7e8b4582",
            "_score": 1,
            "_source": {
               "id": {
                  "$id": "5b2977e843644c8a7e8b4582"
               },
               "ip": "117.30.209.86",
               "source_url": "www",
               "ctime": "2018-06-20 05:38:48",
               "ctimeint": 1529444328,
               "pagemarks": "PC",
               "user_id": 1021001,
               "url": "id=101119055",
               "user_agent": "Microsoft Internet Explorer"
            }
         },

ES Code:
-----------------------------

GET /log/accesslog/_search
{
    "size": 0,
    "query": {
        "filtered":{
            "query": {
                "bool": {
                    "must":[{
                        "range" : {
                            "ctimeint" : {
                                "gte" : **1532016000**,
                                "lt" : **1532275200**
                            }
                        }
                    }]
                }
            }
        }
    }, 
    "aggs": {
        "time": {
            "histogram": {
                "field": "**ctimeint**",
                "interval": **86400**
            },
            "aggs": {
                "mark": {
                    "terms": {
                        "field": "pagemarks",
                        "size": 0,
                        "collect_mode" : "breadth_first"
                    },
                    "aggs": {
                        "ip": {
                          "cardinality": {
                            "field": "ip"
                          }
                        }
                    }
                }
            }
        }
    }
}

Result：
-------------------------------

"aggregations": {
      "time": {
         "buckets": [
            {
               "key": **1531958400**,
               "doc_count": 1266094,
               "mark": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                     {
                        "key": "groupbuydetail_s",
                        "doc_count": 89115,
                        "ip": {
                           "value": 3494
                        }
                     },
                   ]
               }
            }
         ]
      }

Question:
----------------------------------

I would like to querythe agg data between 2018/7/20 and 2018/7/23;  BUT the time for aggregation statistics is 2018/7/19 08:00:00

my elasticsearch version is 1.7.3 

Excuse me, big cow
**How to make the aggregation statistics time 2018/7/20?**

Waiting online! 3Q!

**Comment by dadoonet** [comment]
Please ask this question on discuss.elastic.co where we can give a better support.
This space is only for confirmed issues or feature requests which have been discussed on discuss.elastic.co.

Thanks!

BTW we don't support anymore 1.7 series.
