### ISSUE TITLE
Elasticsearch is going down very frequently 

### ISSUE THREAD

**Issue by balajikandagaddala** [elastic/elasticsearch#32312]
We have noticed that the elasticsearch is going down very frequently without any specific error related to the crash. 

We are using 6.2.4 version of elasticsearch

Please find the attached logs 
[elasticsearch.log](https://github.com/elastic/elasticsearch/files/2222765/elasticsearch.log)
[gc.log](https://github.com/elastic/elasticsearch/files/2222766/gc.log)

**JVM version** (`java -version`):
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux XXXXXXXXXXX 3.10.0-693.21.1.el7.x86_64 #1 SMP Fri Feb 23 18:54:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by atorok** [comment]
@balajikandagaddala are you sure that elasticsearch is not stopped externally ? it could be something like the [OOM Killer](https://www.kernel.org/doc/gorman/html/understand/understand016.html). You can check that by looking at system logs like the output of `dmesg`.

**Comment by balajikandagaddala** [comment]
@atorok  there is no log present in dmesg under /var/log. I am new to the operating system, Can you please provide me few more hints on this.

**Comment by balajikandagaddala** [comment]
Again we hit the same issue today as well, attached is the logs. 

[elasticsearch.log](https://github.com/elastic/elasticsearch/files/2228831/elasticsearch.log)
[start.log](https://github.com/elastic/elasticsearch/files/2228832/start.log)
[gc.log](https://github.com/elastic/elasticsearch/files/2228833/gc.log)

**Comment by atorok** [comment]
@balajikandagaddala see my previous  comment

**Comment by Ethan-Zhang** [comment]
why not ask question in [https://discuss.elastic.co/c/elasticsearch](url). will get more answer.

**Comment by jasontedor** [comment]
An issue like this is best handled on the [forum](https://discuss.elastic.co). We reserve GitHub for verified bug reports and feature requests. We can reopen this if investigation uncovers an issue specific to Elasticsearch.
