### ISSUE TITLE
Whitelisting / from Circuit Breaker Exception

### ISSUE THREAD

**Issue by nssuresh2007** [elastic/elasticsearch#32325]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.1.1 (This issue observed from v5.0.0 onwards)

**Plugins installed**: []

**JVM version** (`java -version`): 1.7.0_181

**OS version** (`uname -a` if on a Unix-like system): 4.9.70-25.242.amzn1.x86_64 (Amazon EC2)

**Description of the problem including expected versus actual behavior**:

When Circuit Breaker has tripped, certain diagnostic requests like "_cluster/health" succeed where as request to / fails with 503 Service Unavailable.
This behavior is observed because of this commit: https://github.com/elastic/elasticsearch/commit/f32b70047241fe319cb37047cc2a47d1b56da6e1 where certain API paths are whitelisted from Circuit Breaking exception, but / is not whitelisted.
Could you please let us know if you foresee any issues if we add / to the Circuit Breaking whitelist? If not, we can submit a pull-request with the above mentioned change.

##### Actual Behavior
When Circuit Breaker has tripped, request to / results in "503 Service Unavailable" even if the cluster is up and running.

```
curl localhost:9200/
{"error":{"root_cause":[{"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [2293752404/2.1gb], which is larger than the limit of [1968537600/1.8gb]","bytes_wanted":2293752404,"bytes_limit":1968537600}],"type":"circuit_breaking_exception","reason":"[parent] Data too large, data for [<http_request>] would be [2293752404/2.1gb], which is larger than the limit of [1968537600/1.8gb]","bytes_wanted":2293752404,"bytes_limit":1968537600},"status":503}
```

#####  Expected behavior
When circuit breaker has tripped, request to / should still pass with "200 OK" if the cluster is up and running.

```
curl localhost:9200/
{
  "name" : "ixU6uZF",
  "cluster_name" : "my-cluster",
  "cluster_uuid" : "ahqlzl0DQAWgE6TLOmlAvA",
  "version" : {
    "number" : "5.1.1",
    "build_hash" : "a90c920",
    "build_date" : "2017-10-18T07:05:07.994Z",
    "build_snapshot" : true,
    "lucene_version" : "6.3.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Steps to reproduce**:
- Stress test the ElasticSearch cluster to make it enter into the Circuit Breaker scenario and ensure that parent circuit breaker is tripped (If required, we can change the default parent circuit breaker limits to reproduce the issue quickly)
- Try hitting `localhost:9200/` on the cluster and it should result in circuit breaker exception similar to the output mentioned in Actual behavior section

**Provide logs (if relevant)**:

**Comment by dakrone** [comment]
+1, I think whitelisting `/` sounds reasonable, given that it's the easiest way to get the cluster version (which you could still want for diagnostics purposes).

> If not, we can submit a pull-request with the above mentioned change.

Sounds good, feel free to ping me for a review when you submit the PR

**Comment by nssuresh2007** [comment]
Hi @dakrone,
I have raised a PR for this issue: https://github.com/elastic/elasticsearch/pull/32666
Could you please review?

**Comment by dakrone** [comment]
The PR has been merged so I'm closing this issue, thanks!
