### ISSUE TITLE
Elasticsearch 6.3 RPM packages are not signed 

### ISSUE THREAD

**Issue by John-Whittington-Slate** [elastic/elasticsearch#32338]
**Elasticsearch version**:  
6.3  
  
**OS version**:
Centos 7.4

**Description of the problem including expected versus actual behavior**:  
It looks like the 6.3 RPM packages are not signed and this causes installation to fail by default. 
   
**Steps to reproduce**:
Follow the [installation guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/rpm.html) for this release of Elasticsearch  
  
``` 
$ sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch 

$ cat /etc/yum.repos.d/elasticsearch-6x.repo 
[elasticsearch-6.x]
name=Elasticsearch repository for 6.x packages
baseurl=https://artifacts.elastic.co/packages/6.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md

$ sudo yum install elasticsearch
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.rackspace.com
 * extras: mirrors.centos.webair.com
 * updates: mirror.vcu.edu
Resolving Dependencies
--> Running transaction check
---> Package elasticsearch.noarch 0:6.3.2-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================================================================================================================================
 Package                                            Arch                                        Version                                        Repository                                              Size
============================================================================================================================================================================================================
Installing:
 elasticsearch                                      noarch                                      6.3.2-1                                        elasticsearch-6.x                                       87 M

Transaction Summary
============================================================================================================================================================================================================
Install  1 Package

Total size: 87 M
Installed size: 136 M
Is this ok [y/d/N]: y
Downloading packages:


Package elasticsearch-6.3.2.rpm is not signed 
```

**Comment by John-Whittington-Slate** [comment]
This seems very similar to [this issue](https://github.com/elastic/elasticsearch/issues/20930) from 2016, and the same workaround applies:  
  
`$ sudo yum install --nogpgcheck elasticsearch`  
  
Disabling GPG checks is not an option for us in production, however.

**Comment by jasontedor** [comment]
Thanks for the report, we are looking into this.

**Comment by Nirjonadda** [comment]
Same issue we are getting, Can not update to v6.3.2

````
Package elasticsearch-6.3.2.rpm is not signed
````

**Comment by jasontedor** [comment]
We believe that this issue is addressed. We are very sorry for the trouble. We are taking steps to ensure that this never happens again. As far we can tell the only artifacts not signed for this release were the Elasticsearch default RPM, Logstash OSS RPM, and the Kibana RPM, all other artifacts appear to have been signed. Would you please try again and confirm that you now see correctly signed artifacts?

**Comment by jasontedor** [comment]
Note that you might need to run `sudo yum --enablerepo=elasticsearch-6.x clean metadata`.

**Comment by John-Whittington-Slate** [comment]
I ran the `clean metadata` command you suggested then downloaded the RPM and verified the signature. Subsequent installs worked fine.  
Thanks for the quick response. This didn't cause us any real problems today, just wanted to let you know the sig was missing. Cheers
