### ISSUE TITLE
Cant access the response 

### ISSUE THREAD

**Issue by patelprakashp** [elastic/elasticsearch#32379]
Response should be declare as `public` so client can access the http response. I would like to know the what all bulk request items failed if there is an error on bulk insert.
https://github.com/elastic/elasticsearch/blob/10bfedeb530f2ad082ddaf74a8efc3fc45644b1b/client/rest/src/main/java/org/elasticsearch/client/Response.java#L99

**Comment by jasontedor** [comment]
You can get the body from `Response#getEntity`. It seems this satisfies your stated use-case?

**Comment by javanna** [comment]
Closing for lack of feedback but I do think that the comment above is the right answer.
