### ISSUE TITLE
Kerberos QA test runs vagrant update on precommit

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#32387]
The `x-pack/qa/kerberos-tests` project has the following flow:

It generated source (`generatedResources`) in the `copyKeytabToGeneratedResources` task
```
project.sourceSets.test.output.dir(generatedResources, builtBy: copyKeytabToGeneratedResources)
```

That task depends on `krb5AddPrincipals`
```
task copyKeytabToGeneratedResources(type: Copy) {
    Path peppaKeytab = project(':test:fixtures:krb5kdc-fixture').buildDir.toPath().resolve("keytabs").resolve("peppa.keytab").toAbsolutePath()
    from peppaKeytab;
    into generatedResources
    dependsOn krb5AddPrincipals
}
```

which in turn depends on `krb5kdcFixture`
```
ask krb5AddPrincipals { dependsOn krb5kdcFixture }
```

which provisions and brings up a vagrant box:
```
task krb5kdcFixture(type: org.elasticsearch.gradle.test.VagrantFixture) {
    command 'up'
    args '--provision', '--provider', 'virtualbox'
    boxName box
    environmentVars vagrantEnvVars
    dependsOn krb5kdcUpdate
}
```

Tha is, building the _source_ for this project requires bringing up a vagrant box, which means it adds a massive weight (and wait) to simple tasks like `precommit`.

We either need to
1. be able to get keytab file without provisioning the vagrant box. For example this is what we do for the IDP cert in saml-idp-tests (see `copyIdpCertificate`), it used to be generated inside vagrant, but is now a static file in the project itself.
2. only copy the keytab from the vagrant box when running the `integTestCluster`. This is how the saml-idp-tests get the `idp-metadata.xml` file from the vagrant box.

**Comment by colings86** [comment]
@tvernum Could you please ensure all issues and PRs you create have an area label so the relevant team is made aware of them?
