### ISSUE TITLE
thirdPartyAudit fails on java8fips JVMs for ingest-attachment and transport-netty4

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#32388]
`:plugins:ingest-attachment:thirdPartyAudit` task fails with jarhell because it has a compile dependency on BouncyCastle 

```
JAR HELL WITH JDK! [org/bouncycastle/LICENSE.class, org/bouncycastle/asn1/ASN1ApplicationSpecific.class,....
```

`:modules:transport-netty4:thirdPartyAudit` fails because of an invalid exclusion
```
What went wrong:
Execution failed for task ':modules:transport-netty4:thirdPartyAudit'.
1485 actionable tasks: 1447 executed, 38 up-to-date
Invalid exclusions, nothing is wrong with these classes: [org/bouncycastle/asn1/x500/X500Name.class]
Stopped 1 worker daemon(s).
```
because `org/bouncycastle/asn1/x500/X500Name.class` is available in this JVM (Provided by the bcfips jar that provides the BCFIPS Security Provider)

Example output: 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/199/consoleText
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/197/consoleText

**Comment by colings86** [comment]
@jkakavas Could you please ensure all PRs you create have an area label so the relevant team is made aware of your PR?

**Comment by jkakavas** [comment]
Resolved by not using a FIPS 140 JVM for Gradle.
