### ISSUE TITLE
Phonetic plugin: Daitch-Mokotoff gives overly broad results for names containing RS

### ISSUE THREAD

**Issue by bkazez** [elastic/elasticsearch#32384]
1) GIERSZLIK codes to 548500 or 594850
2) GOTSALK codes to 548500
3) These names don't sound alike, but the matching codes means a search for one returns the other.

Solution: I exchanged emails with Gary Mokotoff, co-creator of the algorithm, who said:

> I would drop RS from the table. ... I cannot think of any language where RS is pronounced "S" (4).

**Comment by cbuescher** [comment]
@bkazez Thanks for raising this issue. The Daitch-Mokotoff Soundex phonetic filter from Lucene, which in turn seems to be imported from commons-codec if I read this [issue](Daitch-Mokotoff Soundex phonetic filter) right. So I'm afraid we won't be able to adress this issue inside Elasticsearch. I believe the best way to adress this would be to open an issue in Apache commons codec project, so I hope you don't mind me closing this issue.

**Comment by bkazez** [comment]
Thanks. https://issues.apache.org/jira/browse/CODEC-248

On Thu, Jul 26, 2018 at 8:22 AM, Christoph Büscher <notifications@github.com

**Comment by melloware** [comment]
@bkazez Running into some trouble with your suggested fix.  Please see the JIRA issue: https://issues.apache.org/jira/browse/CODEC-248
