### ISSUE TITLE
ram.percent value is misleading

### ISSUE THREAD

**Issue by adrianlzt** [elastic/elasticsearch#32393]
**Elasticsearch version** (`bin/elasticsearch --version`):
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Version: 6.3.0, Build: default/tar/424e937/2018-06-11T23:38:03.357887Z, JVM: 10.0.1

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk 10.0.1 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10)
OpenJDK 64-Bit Server VM (build 10.0.1+10, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux 06831d4f8986 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Docker image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0

**Description of the problem including expected versus actual behavior**:
_cat/nodes value for ram.percent seems to be [calculated](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/monitor/os/OsStats.java#L262) using the "free" available memory:
```
(total-free)/total
```
This value (free) is confusing as it only reports the unused memory (explained [here](https://www.linuxatemyram.com/)).
A more useful value is "available" memory, that reports which memory is reclaimable for new procs.

Example, I have a ES server with 32GB, where 13GB are available and 365MB free. ES ram.percent is 99%. Looking only at that value I will say that server ia having a problem, but it is perfectly correct.

**Steps to reproduce**:
 1. GET _cat/nodes?h=ram.percent
 2. free
 3. compare values

**Comment by asgs** [comment]
any activity on this one? very misleading

**Comment by bargitta** [comment]
Agree, this value is misleading

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
