### ISSUE TITLE
Will ES SQL support pipeline aggregation in the future?

### ISSUE THREAD

**Issue by ranranxiaoya** [elastic/elasticsearch#32423]
**Describe the feature**:

Will ES SQL support pipeline aggregation in the future? Such as bucket_selector, percentiles_bucket...

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by nik9000** [comment]
The `stalled` label on that issue implies that we do plant to support it but aren't actively working on it.
