### ISSUE TITLE
Compatibility matrix for Monitoring

### ISSUE THREAD

**Issue by robin13** [elastic/elasticsearch#32424]
For larger Elasticsearch installations it is common to have one monitoring cluster for multiple elasticsearch clusters, and in this situation it can be difficult to upgrade all of these clusters in parallel so there will always be some diversity amongst the reporting clusters.
The general understanding to-date is that of all of the clusters the monitoring should be the highest version, and the reporting clusters should be compatible as long as they are in the same major version, though there have been cases in the past where this has not even been the case for compatibility across patch releases.
Would it be possible to publish a matrix with the compatibility between reporting clusters and monitoring clusters on the [compatibility matrix page](https://www.elastic.co/support/matrix#matrix_compatibility)?

**Comment by jasontedor** [comment]
This repository is not where changes to the compatibility matrix are managed. For that, there is an internal repository. I will reach out to point you to the right repository.
