### ISSUE TITLE
Remove support for CBOR and Smile on the REST layer

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#32433]
Related to #22811. Even though we use Smile internally eg. for cluster-state serialization, we are considering remove support for Smile and CBOR on the REST layer. We suspect that very few users use these formats, especially as CBOR doesn't support bulk because there is no character that may be used as a separator.

If you are using one of these formats, please let us know.

**Comment by dakrone** [comment]
Have we done any benchmarking (ping @danielmitterdorfer) of Elasticsearch with CBOR or Smile to know how much of an improvement these binary protocols do use?

Also, why are we considering removing CBOR and Smile, but keeping YAML? Do that many people use YAML for the APIs?

**Comment by mattweber** [comment]
-1 for removing Smile, I use it on some projects.  The uses are mainly for scrolls as @jpountz suggest as well as when we have large sources that need to be returned.

**Comment by imotov** [comment]
In the discussions with Kibana team last week they shared an interest in being able to send a large number of geo shapes between elasticsearch and kibana as well as load a large number of geoshapes into elasticsearch. There is a standard compact binary presentation for geoshapes called "Well Known Binary" (WKB) that is currently not supported by elasticsearch, but we are planning to add this support in the near future. WKB in conjunction with a binary protocol over REST can be the answer to speeding up Kibana's GIS functionality.  cc @nknize

**Comment by dliappis** [comment]
ping @nknize do you think there's still use for any of the binary formats mentioned here?

**Comment by imotov** [comment]
@dliappis yes, we still think that the binary protocol support on the interface would be quite beneficial after we add support for WKB to geo.

**Comment by romseygeek** [comment]
@jpountz I think this can be closed?

**Comment by harsimranb** [comment]
We are considering using CBOR to send file attachments for processing with the Ingest Attachment Plugin.  I imagine this is an important use case for users using Elastic at scale to process and index files - who want to avoid overhead of Base64 decode.

**Comment by jpountz** [comment]
Agreed @romseygeek.

**Comment by azhuchkov** [comment]
I suppose returning data in a **non-native** format require extra conversion step at the server-side that makes supporting those formats less useful in terms of performance.

Which format does not require such a step?
