### ISSUE TITLE
Composite aggregation doesn't support min_doc_count option

### ISSUE THREAD

**Issue by tobias74** [elastic/elasticsearch#32452]
**Elasticsearch version** : docker.elastic.co/elasticsearch/elasticsearch:6.3.1

**Plugins installed**: []

**JVM version** the one from the docker-image (docker.elastic.co/elasticsearch/elasticsearch:6.3.1):

**OS version** like above (docker.elastic.co/elasticsearch/elasticsearch:6.3.1):

**Description of the problem including expected versus actual behavior**:

I am experiencing the error "unknown field [min_doc_count]" on a terms-aggregation. I placed said terms-aggregation as the single source in a composite-aggregation like so:

```
{
"aggs" : {
    "my_buckets": {
        "composite" : {
            "sources" : [
                { "product": { "terms" : { "field": "product", "min_doc_count": 2 } } }
            ]
        }
    }
 }

```

 (I did that because I wanted to use the pagination-feature of composite-aggregations)

The aggregation works fine on it's own. Only when I put it in a composite-aggregation it fails.

I have asked an according question on SO:

[https://stackoverflow.com/questions/51557626/elasticsearch-unknown-field-min-doc-count](https://stackoverflow.com/questions/51557626/elasticsearch-unknown-field-min-doc-count)

 

**Steps to reproduce**:
(see query above)

I hope this is just a bug, although I fear that maybe I just did not understand composite-queries...

Hope anybody can help?

Thanks!

**Comment by jimczi** [comment]
`min_doc_count` is not implemented in the `composite` aggregation. This aggregation can be used to retrieve **all** buckets (with pagination) so if you need to filter some of them you'll need to do it on client side or use a pipeline aggregation:

````
{
"aggs" : {
    "my_buckets": {
        "composite" : {
            "sources" : [
                { "product": { "terms" : { "field": "product", "min_doc_count": 2 } } }
            ]
        }
    },
    "aggs": {
        "filter": {
          "bucket_selector": {
            "buckets_path": {
              "doc_count": "_count"
            },
            "script": "doc_count > 2"
          }
        }
   }
}
```` 
The `bucket_selector` will keep buckets with a doc count greater than 2 and will preserve the `after_key` to handle pagination correctly. 

Though it should be possible to handle `min_doc_count` natively in the `composite` aggregation, this would be consistent with the other aggregations so I'll mark this issue as an enhancement and adoptme tags.

**Comment by jimczi** [comment]
@chester89 thanks I updated the query, `min_doc_count` is not handled by the `composite` agg and indeed it should be removed.

**Comment by chester89** [comment]
@jimczi would it be easy to add support for `min_doc_count`? And is there any plans to mark this aggregation as production ready?

**Comment by jimczi** [comment]
I checked how we could implement `min_doc_count` for the `composite` aggregation and found out that this would require a big refactoring since we don't keep track of all buckets but only those that are in the top N. Adding this feature would defeat the purpose since we'd need to keep **all** buckets and make the selection (based on `min_doc_count`) at the end. Since this would use a lot of memory I don't think we should handle this feature natively in this aggregation and instead rely on client filtering or the `bucket_selector`. 

> And is there any plans to mark this aggregation as production ready?

The `composite` aggregation is marked as `beta` now (previously `experimental`). We'll remove the `beta` label soon but this label does not mean that we don't provide support if a bug is found and we plan to keep this functionality so there is no reason to not use it in production.

**Comment by chester89** [comment]
@jimczi I see. can you tell me if there's any query in ES that would allow me to count unique field values with count condition on them (e.g. count unique users that visited site more than X times in particular period)? [here's my SO question](http://bit.ly/2wjbx3s)

**Comment by jimczi** [comment]
Nope I don't see a scalable way to do that in a single aggregation. One solution is to count unique users on client side using the `composite` aggregation. You can retrieve the buckets page by page and do the counting based on the doc count. You'll need multiple requests to paginate over the `composite` aggregation but the retrieval of each page is optimized (the `composite` aggregation doesn't need to visit all documents). If you have millions of unique user this might take some time to compute but it won't kill your cluster (each `composite` query is light weight)  and you could cache the final response for visualization.

**Comment by mutecamel** [comment]
> `min_doc_count` is not implemented in the `composite` aggregation. This aggregation can be used to retrieve **all** buckets (with pagination) so if you need to filter some of them you'll need to do it on client side or use a pipeline aggregation:
> 
> ```
> {
> "aggs" : {
>     "my_buckets": {
>         "composite" : {
>             "sources" : [
>                 { "product": { "terms" : { "field": "product" } } }
>             ]
>         },
>         "aggs": {
>           "filter": {
>             "bucket_selector": {
>               "buckets_path": {
>                 "doc_count": "_count"
>               },
>               "script": "doc_count > 2"
>             }
>          }
>       }
>    }
> }
> ```
> 
> The `bucket_selector` will keep buckets with a doc count greater than 2 and will preserve the `after_key` to handle pagination correctly.
> 
> Though it should be possible to handle `min_doc_count` natively in the `composite` aggregation, this would be consistent with the other aggregations so I'll mark this issue as an enhancement and adoptme tags.

Here is a minor correction to the original solution:
```
{
"aggs" : {
    "my_buckets": {
        "composite" : {
            "sources" : [
                { "product": { "terms" : { "field": "product" } } }
            ]
        },
        "aggs": {
          "filter": {
            "bucket_selector": {
              "buckets_path": {
                "doc_count": "_count"
              },
              "script": "params.doc_count > 2"
            }
         }
      }
   }
}
```

**Comment by charlie-wasp** [comment]
It seems that offered solution doesn't work anymore? According to the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html#_pipeline_aggregations) for 7.6:

> The composite agg is not currently compatible with pipeline aggregations, nor does it make sense in most cases

**Comment by polyfractal** [comment]
@charlie-wasp the documentation was updated due to discussions about composite + pipeline in general (https://github.com/elastic/elasticsearch/issues/32692#issuecomment-517810517).  

Some pipelines work with composite, some do not work at all, and some _technically_ work but can give bad data (like a derivative that would span between composite pages).  While we decide what to do with composite and pipelines, we decided it would be prudent to just document that they are not supported so that users don't accidentally get themselves into a pickle.

In this particular scenario, the bucket_selector is one of the "safe" pipelines that does work as expected and I don't believe anything has changed in that regard.  But I would view pipelines + composite as "experimental" until we come to a decision about how/which should be supported.  I.e. might change in the future :)

**Comment by manasnayakstamps** [comment]
@jimczi I apologize for asking this on a closed issue. Is there a way we can do pagination on top of the bucket_selector result in composite aggregation? I have a requirement where the pagination should be applied after removing the buckets which don't satisfy certain conditions.  It also is good if you can provide any other workaround besides composite aggregations. Please keep in mind that we want something similar to the search_after feature in aggregated data.

**Comment by Dimeji98** [comment]
> `min_doc_count` is not implemented in the `composite` aggregation. This aggregation can be used to retrieve **all** buckets (with pagination) so if you need to filter some of them you'll need to do it on client side or use a pipeline aggregation:
> 
> ```
> {
> "aggs" : {
>     "my_buckets": {
>         "composite" : {
>             "sources" : [
>                 { "product": { "terms" : { "field": "product" } } }
>             ]
>         },
>         "aggs": {
>           "filter": {
>             "bucket_selector": {
>               "buckets_path": {
>                 "doc_count": "_count"
>               },
>               "script": "doc_count > 2"
>             }
>          }
>       }
>    }
> }
> ```
> 
> The `bucket_selector` will keep buckets with a doc count greater than 2 and will preserve the `after_key` to handle pagination correctly.
> 
> Though it should be possible to handle `min_doc_count` natively in the `composite` aggregation, this would be consistent with the other aggregations so I'll mark this issue as an enhancement and adoptme tags.

I unable to get this to work as I am getting a "cannot resolve symbol [doc_count]" error? Is there a fix for that?
