### ISSUE TITLE
upgrade java req to warn in doc for debian install

### ISSUE THREAD

**Issue by NCarson** [elastic/elasticsearch#32454]
If you TLDR the instructions about the java req you will get this:
```
sudo dpkg -i elasticsearch-6.3.2.deb
(Reading database ... 58518 files and directories currently installed.)
Preparing to unpack elasticsearch-6.3.2.deb ...
dpkg: error processing archive elasticsearch-6.3.2.deb (--install):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 elasticsearch-6.3.2.deb
```
Which is classical Debian cryptic. After unpacking the deb and running the pre-install script. It printed the java error to the screen, but `dpkg` is suppressing the output. So, you have to understand debs pretty well to figure it out. 

And, I know you did put this in the instructions. And, I can see why you would not give a hard requirement since there are a bunch of different Java's you can install. And, I mostly blame Debian/Ubuntu for not printing the error. But, I think there will be other people that will just fly by the top part of the instructions. Since, it is quite common to have to add repositories I mostly just copy / paste the commands. 

Or add `java -version && ...` on the last part of the command chain and you get a good error.

**Comment by tomcallahan** [comment]
Relates #31845

**Comment by dliappis** [comment]
Hello @NCarson ,

Indeed this was a bug that we've since addressed in https://github.com/elastic/elasticsearch/pull/36077.

Elasticsearch deb packages since 6.5.3 will display:

```
$ sudo dpkg -i ./elasticsearch-6.5.3.deb
(Reading database ... 54165 files and directories currently installed.)
Preparing to unpack ./elasticsearch-6.5.3.deb ...
could not find java; set JAVA_HOME or ensure java is in PATH
dpkg: error processing archive ./elasticsearch-6.5.3.deb (--install):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 ./elasticsearch-6.5.3.deb
```

which hopefully helps identifying that there's no java installed in the system.
