### ISSUE TITLE
Some alert or indicator for master/client node going down

### ISSUE THREAD

**Issue by fhalde** [elastic/elasticsearch#32484]
Today we only have cluster health which talks about the data availability, but its equally good to have an indicator if master/client node is down. Because of the absence of such metric, we have to rely on a separate script that monitors the availability of a master/client node. This is important since all the interaction with the cluster primarily happens with master/client nodes. Such metrics can also help in deactivating a node that is down from an LB

**Comment by DaveCTurner** [comment]
I don't see how Elasticsearch could itself tell the difference between an unexpected failure requiring an alert and a node being deliberately taken down for maintenance or retirement. That distinction is the responsibility of the environment outside of Elasticsearch.

A shut down node will refuse connections on its HTTP port, and LBs can normally be configured to detect this and take the shut-down node out of rotation until it starts accepting connections again.

Marking this for discussion in the team to gather others' thoughts.

**Comment by fhalde** [comment]
hmm. agreed about the LB part. but the way of detecting a master/client node going down would be the same as detecting a data node going down right? am i missing anything fundamental here?

**Comment by DaveCTurner** [comment]
This sounds like it could be achieved today with a combination of the X-pack [monitoring](https://www.elastic.co/guide/en/elastic-stack-overview/6.4/xpack-monitoring.html) and [alerting](https://www.elastic.co/guide/en/elastic-stack-overview/6.4/xpack-alerting.html) features, and indeed there is [an example of a watch that sends email when the cluster membership changes here](https://github.com/elastic/elasticsearch/blob/22415fa2de1d7d07cea7dd5e7263eb1ed4270503/x-pack/plugin/monitoring/src/main/resources/monitoring/watches/elasticsearch_nodes.json).
