### ISSUE TITLE
SQL: Support for IP address fields

### ISSUE THREAD

**Issue by bluefangs** [elastic/elasticsearch#32499]
Hello,

This is on the back of [this](https://discuss.elastic.co/t/dealing-with-arrays-and-ip-address-fields-in-elasticsearch-sql/142122/2?u=blueren) brief discussion in the es forums.

At present, there is no support for querying IP address fields in SQL format.

**QUERY:** 
```
POST _xpack/sql?format=txt
{
  "query":"SELECT flow.src_addr FROM elastiflow*"
}
```

**OUTPUT:**

```
{
  "error": {
    "root_cause": [
      {
        "type": "verification_exception",
        "reason": "Found 1 problem(s)\nline 1:8: Cannot use field [flow.src_addr] type [ip] as is unsupported"
      }
    ],
    "type": "verification_exception",
    "reason": "Found 1 problem(s)\nline 1:8: Cannot use field [flow.src_addr] type [ip] as is unsupported"
  },
  "status": 400
}
```

**CURRENT WORKAROUND  (as quoted in the forum):** 

For IP fields, you could do something like the following, but this requires a new field to be added and any already indexed data to be re-indexed:

        "ip_addr": {
          "type": "ip",
          "copy_to": "keyword_ip_addr"
        },
        "keyword_ip_addr": {
          "type": "keyword"
        }

And then in the select you will select that `keyword_ip_addr` specifically.

**Comment by pranavg189** [comment]
Hello, I want to work on this feature. Can I get some pointers on how to get started on this ?

**Comment by imotov** [comment]
@pranavg189 I would start with studying our [contributing guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md), make sure that you can build elasticsearch from sources, run tests, etc. Then take a look at how other types are implemented and ask concrete questions if you have any. Most of the work will be concentrated in [DataType](https://github.com/elastic/elasticsearch/blob/0b1a0641efb306caf073a63d5683fe0deade3f58/x-pack/plugin/sql/sql-proto/src/main/java/org/elasticsearch/xpack/sql/type/DataType.java), [TypeConverter](https://github.com/elastic/elasticsearch/blob/de9e56aa0161abb30047e7d96b814ad250b69165/x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/jdbc/TypeConverter.java) and possibly [JdbcResultSet](https://github.com/elastic/elasticsearch/blob/ce78925732f17a3628a356133cbd75b71fc79c57/x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/jdbc/JdbcResultSet.java)'s getObject methods and friends. To a certain degree you can use my [geosql](https://github.com/elastic/elasticsearch/tree/geosql) branch as an example.

**Comment by costin** [comment]
@bluefangs the feature was merged into the code base and will be part of the upcoming 6.5 release.
Thanks for waiting.
@pranavg189 Thank you for the interest You're welcome to pick another issue - there are plenty to go around :). 

Cheers
