### ISSUE TITLE
[CI] KerberosAuthenticationIT fails in CI

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch#32498]
Build failure link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+multijob-unix-compatibility/os=centos/7/console

```
./gradlew :x-pack:qa:kerberos-tests:integTestRunner \
  -Dtests.seed=96A4AD9F42092F61 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.kerberos.KerberosAuthenticationIT \
  -Dtests.security.manager=true \
  -Dtests.locale=und \
  -Dtests.timezone=Etc/GMT-11
```

`testLoginByKeytab` and `testLoginByUsernamePassword` fail with:

`KrbException: Identifier doesn't match expected value (906)`

and also

`KrbException: Server not found in Kerberos database (7) - LOOKING_UP_SERVER`

This issue does not reproduce locally.

**Comment by danielmitterdorfer** [comment]
The tests are muted now on 6.4, 6.x and master (see above for commit ids).

**Comment by danielmitterdorfer** [comment]
Another failure happened in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=centos/1214/console.

**Comment by jaymode** [comment]
This is failing due to the use of `[::1]` as the address in the rest client and the fact that the test always expects the http address to be `localhost`. I opened #32514 to address this

**Comment by colings86** [comment]
Looks like this is still failing on the same tests though with a different (my related) exception. The build in question is:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=centos/1217/console

It now seems to fail with the following exception suggesting that the host name is not resolvable on the CI server:
```
08:08:14   1> >>> KrbKdcReq send: kdc=kerberos.build.elastic.co UDP:88, timeout=3000, number of retries =3, #bytes=142
08:08:14   1> >>> KrbKdcReq send: error trying kerberos.build.elastic.co:88
08:08:14   1> java.net.UnknownHostException: kerberos.build.elastic.co: Name or service not known
08:08:14   1> 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
08:08:14   1> 	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
08:08:14   1> 	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
08:08:14   1> 	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
08:08:14   1> 	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
08:08:14   1> 	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
08:08:14   1> 	at java.net.InetAddress.getByName(InetAddress.java:1076)
08:08:14   1> 	at sun.security.krb5.internal.UDPClient.<init>(NetClient.java:187)
08:08:14   1> 	at sun.security.krb5.internal.NetClient.getInstance(NetClient.java:45)
08:08:14   1> 	at sun.security.krb5.KdcComm$KdcCommunication.run(KdcComm.java:393)
```

Reopening this issue first as it seems to be very related to this fix but if its an infra issue instead I can raise an infra issue for it.
