### ISSUE TITLE
Failed to search against Search Template with conditional clauses

### ISSUE THREAD

**Issue by Wing333** [elastic/elasticsearch#32527]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.2

**Plugins installed**: [n/a]

**JVM version** (`java -version`): java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): Linux version 2.6.32-131.0.15.el6.x86_64 (mockbuild@x86-007.build.bos.redhat.com) (gcc version 4.4.4 20100726 (Red Hat 4.4.4-13) (GCC) ) #1 SMP Tue May 10 15:42:40 EDT 2011

**Description of the problem including expected versus actual behavior**:
Failed to search against template with conditional clauses.
Expected: search successfully.
Actual behavior: search failed with error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "general_script_exception",
        "reason": "Failed to compile inline script [{\"query\":{\"bool\":{\"must\":{\"match\":{\"line\":\"{{text}}\"}},\"filter\":{{{#line_no}}\"range\":{\"line_no\":{{{#start}}\"gte\":\"{{start}}\"{{#end}},{{/end}}{{/start}}{{#end}}\"lte\":\"{{end}}\"{{/end}}}}{{/line_no}}}}}}] using lang [mustache]"
      }
    ],
    "type": "general_script_exception",
    "reason": "Failed to compile inline script [{\"query\":{\"bool\":{\"must\":{\"match\":{\"line\":\"{{text}}\"}},\"filter\":{{{#line_no}}\"range\":{\"line_no\":{{{#start}}\"gte\":\"{{start}}\"{{#end}},{{/end}}{{/start}}{{#end}}\"lte\":\"{{end}}\"{{/end}}}}{{/line_no}}}}}}] using lang [mustache]",
    "caused_by": {
      "type": "mustache_exception",
      "reason": "Improperly closed variable in query-template:1"
    }
  },
  "status": 500
}
```

**Steps to reproduce**:

This is a sample query presented as an example in
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search-template.html#_conditional_clauses:
```
{
  "query": {
    "bool": {
      "must": {
        "match": {
          "line": "{{text}}" 
        }
      },
      "filter": {
        {{#line_no}} 
          "range": {
            "line_no": {
              {{#start}} 
                "gte": "{{start}}" 
                {{#end}},{{/end}} 
              {{/start}} 
              {{#end}} 
                "lte": "{{end}}" 
              {{/end}} 
            }
          }
        {{/line_no}} 
      }
    }
  }
}
```

And this is the escaped string documented in the same page:
```
"source": "{\"query\":{\"bool\":{\"must\":{\"match\":{\"line\":\"{{text}}\"}},\"filter\":{{{#line_no}}\"range\":{\"line_no\":{{{#start}}\"gte\":\"{{start}}\"{{#end}},{{/end}}{{/start}}{{#end}}\"lte\":\"{{end}}\"{{/end}}}}{{/line_no}}}}}}"
```

If I validate above query as below:
```
GET _render/template
{
  "source": "{\"query\":{\"bool\":{\"must\":{\"match\":{\"line\":\"{{text}}\"}},\"filter\":{{{#line_no}}\"range\":{\"line_no\":{{{#start}}\"gte\":\"{{start}}\"{{#end}},{{/end}}{{/start}}{{#end}}\"lte\":\"{{end}}\"{{/end}}}}{{/line_no}}}}}}",
  "params": {
    "text": "words to search for",
    "line_no": {
      "start": 10,
      "end": 20
    }
  }
}
```

It will fail with error:
```
{
  "error": {
    "root_cause": [
      {
        "type": "general_script_exception",
        "reason": "Failed to compile inline script [{\"query\":{\"bool\":{\"must\":{\"match\":{\"line\":\"{{text}}\"}},\"filter\":{{{#line_no}}\"range\":{\"line_no\":{{{#start}}\"gte\":\"{{start}}\"{{#end}},{{/end}}{{/start}}{{#end}}\"lte\":\"{{end}}\"{{/end}}}}{{/line_no}}}}}}] using lang [mustache]"
      }
    ],
    "type": "general_script_exception",
    "reason": "Failed to compile inline script [{\"query\":{\"bool\":{\"must\":{\"match\":{\"line\":\"{{text}}\"}},\"filter\":{{{#line_no}}\"range\":{\"line_no\":{{{#start}}\"gte\":\"{{start}}\"{{#end}},{{/end}}{{/start}}{{#end}}\"lte\":\"{{end}}\"{{/end}}}}{{/line_no}}}}}}] using lang [mustache]",
    "caused_by": {
      "type": "mustache_exception",
      "reason": "Improperly closed variable in query-template:1"
    }
  },
  "status": 500
}
```

However if I escape the original query (and also remove spaces afterwards, but this is optional and does not affect the result) as below:
```
GET _render/template
{
  "source": "{\r\n\"query\":{\r\n\"bool\":{\r\n\"must\":{\r\n\"match\":{\r\n\"line\":\"{{text}}\"\r\n}\r\n},\r\n\"filter\":{\r\n{{#line_no}}\r\n\"range\":{\r\n\"line_no\":{\r\n{{#start}}\r\n\"gte\":\"{{start}}\"\r\n{{#end}},{{/end}}\r\n{{/start}}\r\n{{#end}}\r\n\"lte\":\"{{end}}\"\r\n{{/end}}\r\n}\r\n}\r\n{{/line_no}}\r\n}\r\n}\r\n}\r\n}",
  "params": {
    "text": "words to search for",
    "line_no": {
      "start": 10,
      "end": 20
    }
  }
}
```

Then it will work:
```
{
  "template_output": {
    "query": {
      "bool": {
        "must": {
          "match": {
            "line": "words to search for"
          }
        },
        "filter": {
          "range": {
            "line_no": {
              "gte": "10",
              "lte": "20"
            }
          }
        }
      }
    }
  }
}
```

I'm wondering why it does not work in the first case?

**Comment by original-brownbear** [comment]
@Wing333 I don't think this is a bug, the problem is that by removing all whitespaces in your first escaped example you're creating sections like this one:

```

**Comment by Wing333** [comment]
Hi @original-brownbear 
Thanks for your reply. Now I understand why it fails in the first case.

However please note that I did NOT delete any whitespace in the first case, I just copied exactly the same query as documented in:
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search-template.html#_conditional_clauses

I'd suggest someone update that sample query from the document (to add missing whitespaces as you implied) and highlight that whitespace is mandatory in case of "tripple mustache".

**Comment by wchrisdean** [comment]
[doc issue triage]

**Comment by nilaonai** [comment]
> @Wing333 I don't think this is a bug, the problem is that by removing all whitespaces in your first escaped example you're creating sections like this one:
> 
> ```
> \"filter\":{{{#line_no}}
> ```
> 
> => tripple mustache with a section start.
> 
> if you simple add whitespaces at the beginning of your two section starts to prevent the tripple mustache there it all works fine via:
> 
> ```
> "{\"query\":{\"bool\":{\"must\":{\"match\":{\"line\":\"{{text}}\"}},\"filter\":{ {{#line_no}}\"range\":{\"line_no\":{ {{#start}}\"gte\":\"{{start}}\"{{#end}},{{/end}}{{/start}}{{#end}}\"lte\":\"{{end}}\"{{/end}}}}{{/line_no}}}}}}"
> ```
> 
> Hope that helps :), closing here as there's no actionable issue.

is there has other methods to resolve the problems.  my template is too large to when compress and transfer into  string。so, it is really some trouble to add **blank** in the string.
