### ISSUE TITLE
logging a correlation id for each processing stage a request goes through

### ISSUE THREAD

**Issue by fhalde** [elastic/elasticsearch#32540]
it would be really convenient to debug what a search request processing goes through

**Comment by ywelsch** [comment]
Can you describe the use case a bit more? Is the [profile API](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-profile.html) not good enough for this?

**Comment by fhalde** [comment]
awesome!! I wasn't aware of this. thanks a lot @ywelsch

**Comment by mayya-sharipova** [comment]
@fhalde If profile API addresses your needs, I am going to close this issue.
