### ISSUE TITLE
[ML] Custom rule w/ time condition specified is accepted for forbidden functions

### ISSUE THREAD

**Issue by dolaru** [elastic/elasticsearch#32545]
## Description
Found in 6.4.0-BC1

According to documentation:
> If your detector uses lat_long, metric, rare, or freq_rare functions, you cannot specify conditions for your rule.

If the user tries to create a job that:
 - uses one of the forbidden functions (`lat_long`, `metric`, `rare` or `freq_rare`)
 - has a custom rule specifying a condition with `applies_to` set to `time`

... the job gets created, even though it shouldn't have according to documentation.

## Steps to reproduce
1. Create a job that uses one of the forbidden functions (`lat_long`, `metric`, `rare` or `freq_rare`) and has a custom rule with a time condition:
```json
PUT _xpack/ml/anomaly_detectors/custom_rule_forbidden_function
{
  "analysis_config": {
    "detectors": [
      {
        "function": "metric",
        "field_name": "someFieldName",
        "custom_rules": [
          {
            "actions": [
              "skip_result"
            ],
            "conditions": [
              {
                "applies_to": "time",
                "operator": "gte",
                "value": 0
              }
            ]
          }
        ]
      }
    ]
  },
  "data_description": {}
}
```
2. Notice the job was created, even though it shouldn't have according to documentation.

**Comment by dimitris-athanasiou** [comment]
Indeed, conditions that apply to `time` are valid regardless of the function. I raised #32548 where I improve the docs and the error message to reflect this.
