### ISSUE TITLE
testNoNodeNameWarning fails on Windows

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#32546]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/1793/console

```
12:28:27 FAILURE 0.03s J2 | EvilLoggerTests.testNoNodeNameWarning <<< FAILURES!
12:28:27    > Throwable #1: java.lang.AssertionError: 
12:28:27    > Expected: a string ending with "no_node_name/log4j2.properties"
12:28:27    >      but: was "  C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\qa\evil-tests\build\resources\test\org\elasticsearch\common\logging\no_node_name\log4j2.properties"
```

NB forward slashes vs backslashes 👿 

Introduced in #31588 which is labelled backport-pending so this may propagate further back. I'm suppressing the test for now.

**Comment by jasontedor** [comment]
@nik9000 Would you take a look?

**Comment by nik9000** [comment]
I pushed a fix for this. Simple code change but it takes me a while to get windows back up and running. The fun thing this time was figuring out `rm -rf` in powershell. I know I could have done it in the file explorer, but it is a matter of pride!
