### ISSUE TITLE
Broken @link in Javadocs

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#32553]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/212/console failed with a compile error due to something wrong in a Javadoc comment introduced in #32356

I pushed these to suppress this issue for now, but am opening this issue to fix it properly.

dd939ebe2e9fa3781d2b0d467b17e4a7fa37ad26 (6.x)
621350c1b973d8c02afe62b6130231f46ae1affc (master)

@astefan could you have a look?

**Comment by astefan** [comment]
Yep, I have it. Thanks @DaveCTurner
