### ISSUE TITLE
OpenSuse packaging tests fail on 6.3 due to missing SATA controller

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#32577]
Build failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+packaging-tests/298/console

This build fails with:

08:16:36 ["storagectl", :id, "--name", "SATA Controller", "--hostiocache", "on"]
08:16:36 
08:16:36 The following error was experienced:
08:16:36 
08:16:36 #<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
08:16:36 for controlling VirtualBox. The command and stderr is shown below.
08:16:36 
08:16:36 Command: ["storagectl", "d32776ee-49d7-4a15-82d1-3bdd90701ced", "--name", "SATA Controller", "--hostiocache", "on"]
08:16:36 
08:16:36 Stderr: VBoxManage: error: Could not find a storage controller named 'SATA Controller'
08:16:36 VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component SessionMachine, interface IMachine, callee nsISupports
08:16:36 VBoxManage: error: Context: "GetStorageControllerByName(Bstr(pszCtl).raw(), ctl.asOutParam())" at line 1207 of file VBoxManageStorageController.cpp
08:16:36 VBoxManage: error: Couldn't find the controller with the name: 'SATA Controller'
I think a recent commit (32e08f7) has removed the SATA controller form the openSuse VM image but i suspect the 6.3 packaging tests are still relying on it. I wonder if we should have a openSuse-42-for-ES-6.3 image that will work with the 6.3 packaging tests?

There is also an infra issue (https://github.com/elastic/infra/issues/6255) for this as I'm not sure whether the fix should be on infra VM images or on our side.

**Comment by jasontedor** [comment]
Closed by 432f1b646f226996653eed0cef740267282d604a.

**Comment by andyb-elastic** [comment]
Thanks for fixing this, I'd forgotten that I'd backported that change
