### ISSUE TITLE
SQL: investigate the option of using a Locale for some of the functions

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#32603]
At the moment, Elasticsearch SQL is ignoring any Locale when using functions like UCASE or LCASE. We could add another parameter to these functions or use a general mechanism for specifying a user-defined Locale per "session".

Relates to https://github.com/elastic/elasticsearch/pull/30453
Relates to https://github.com/elastic/elasticsearch/issues/32589

**Comment by nafeespeer** [comment]
Is this still an issue?

**Comment by wchaparro** [comment]
Closing as not planned, superceded by our work in ES|QL. Please reopen if you have concerns.
