### ISSUE TITLE
[ML] 'finished_time' still reported after job has been reopened

### ISSUE THREAD

**Issue by dolaru** [elastic/elasticsearch#32605]
## Description
Found in 6.3.2

Currently, when a job closes, the `finished_time` key is created/updated in the job config and it's value represents the timestamp of when the job was last closed.

If the user reopens the job, we still show the last `finished_time` until the job closes again. This is misleading, as there shouldn't be a `finished_time` reported while a job is still open.

## Steps to reproduce
1. Create a job
2. Open the job
3. Close the job
4. Re-open the job
5. Notice that `finished_time` is still being reported and the value coincides with the time at which the job was last closed.

**Comment by benwtrent** [comment]
https://github.com/elastic/elasticsearch/pull/32755 fixes this issue
