### ISSUE TITLE
Sort on _id causes OOM

### ISSUE THREAD

**Issue by danielkasen** [elastic/elasticsearch#32626]
**Elasticsearch 6.3.0**

**JVM 1.8.72**:

**OS Ubuntu 14.04**:

The _id field fills up the fielddata cache even though fieldddata cache is not enabled for any field. A user can sort a list of results by the _id field in kibana and this issues a query that loads all of these values into the fielddata cache, which increases the heap usage, which then causes an OOM and nodes fall over. Is there a way to get _id to stop being loaded into the fielddata, or prevent it from being a sortable index so my users don't accidentally knock out a cluster?

**Steps to reproduce**:

step 1) clear the cache on the index we are searching `POST test-2018.08.03.14.00-1/_cache/clear`
step 2) Confirm the cache is cleared `GET _nodes/stats/indices/fielddata?level=indices` search for your index
step 3) Run A query over the time that would use that index
step 4) Now sort those results on the `_id` field
step 5) Check the size again  `GET _nodes/stats/indices/fielddata?level=indices` search for your index

**Comment by imotov** [comment]
@danielkasen please see #11887 for some background on the issue. The current suggestion according to the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html) is

> The value of the `_id` field is also accessible in aggregations or for sorting, but doing so is discouraged as it requires to load a lot of data in memory. In case sorting or aggregating on the `_id` field is required, it is advised to duplicate the content of the `_id` field in another field that has doc_values enabled."  

Unfortunately, there is no good solution for this in 6.x, but we are working on it for 7.0. The issue #25674 is the next step in this direction.

**Comment by danielkasen** [comment]
ok, thanks. Mainly wanted to see if the issue was addressed. For now I just removed that _meta field in Kibana so at least most of my users won't accidentally stumble on this.

**Comment by imotov** [comment]
I am going to close this issue then, since it is already tracked elsewhere.

**Comment by wfhartford** [comment]
I've been encountering this issue when sorting on timestamp and `_id` in order to page through a large query result using the search after feature. Is there a recommended way to achieve this without sorting on `_id`? Issue #11887 seems to suggest that sorting on `_uid` would be preferred, but that results in the warning:
```
Fielddata access on the _uid field is deprecated, use _id instead
```

**Comment by yunnanabel** [comment]
> 
why  dose it work that "duplicate the content of the _id field in another field that has doc_values enabled."what's the difference when sorting?
