### ISSUE TITLE
Changing indices.recovery.max_bytes_per_sec doesn't affect shard recovery speed/time 

### ISSUE THREAD

**Issue by ctluce** [elastic/elasticsearch#32622]
**Elasticsearch version**: 6.3.2

**Plugins installed**: [discovery-ec2]

**JVM version**:
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

**OS version** :
4.14.55-62.37.amzn1.x86_64 #1 SMP Fri Jul 20 00:44:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
On a 6.3.2 cluster changing indices.recovery.max_bytes_per_sec setting doesn't affect recovery speed/time.  Looking at recovery API for shards no throttling time is shown.  No matter what I change the value to network throughput/CPU/disk read/write doesn't change.  I have enabled trace logging on logger.org.elasticsearch.indices.recovery and searched through logs and cannot find anything that points to an issue.

Index Information
1 index 5 shards 1 replica
Shard size is ~9 GB per shard

Relevant settings to recovery
cluster.routing.allocation.node_initial_primaries_recoveries: 5
cluster.routing.allocation.node_concurrent_incoming_recoveries: 5
cluster.routing.allocation.node_concurrent_outgoing_recoveries: 5
cluster.routing.allocation.node_concurrent_recoveries: 5
cluster.routing.allocation.cluster_concurrent_rebalance: 5
indices.recovery.max_bytes_per_sec: 400mb

After looking through documentation I cannot find another setting that would affect this, trying to understand why changing indices.recovery.max_bytes_per_sec to 2000mb doesn't affect the recovery speed.

Elasticsearch forum post contains more information https://discuss.elastic.co/t/elasticsearch-6-3-0-shard-recovery-is-slow/140940

**Comment by bleskes** [comment]
@ctluce thx. I see Nhat is already engaged on the forums. No need to open up a ticket here until we resolve this to a concrete issue. I'm closing this until the discuss thread is completed.
