### ISSUE TITLE
[Doc] Update "Java High Level REST Client » Indices APIs » Index Aliases API" page

### ISSUE THREAD

**Issue by lockwobr** [elastic/elasticsearch#32647]
When reading the [docs](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-update-aliases.html) to use the sdk to add an alias to an index I found the docs are out of date it seems. I am not 100% sure what they should be but I was able to make something work, but is a lot different the docs suggest.

I found that this line:
```
AliasActions aliasAction =
        new AliasActions(AliasActions.Type.ADD)
        .index("index1")
        .alias("alias1");
```
seems it should be
```
AliasActions aliasAction =
       AliasActions.add()
        .index("index1")
        .alias("alias1");
```

And when trying to figure out how to execute request I could not figure out how to do it a similar way to the docs:
```
IndicesAliasesResponse indicesAliasesResponse =
        client.indices().updateAliases(request, RequestOptions.DEFAULT);
```

What I figured out is something like this (this one line should be all you need for a simple add):
```
Response indicesAliasesResponse = client.admin().indices().prepareAliases().addAlias("index1", "alias1").get()

```

**Comment by javanna** [comment]
hi @lockwobr I think that you are using the transport client rather than the high-level REST client. Docs are ok, we actually execute the docs snippets so they can't go out of date ;)
