### ISSUE TITLE
GetAlias JAVA API Result hard to process.

### ISSUE THREAD

**Issue by skombijohn** [elastic/elasticsearch#32680]
using Elasticsearch Version 6.3.2

The Java API offers an API to "get Aliases". 
Given that an index "testIndex_0" is targeted by an alias "testIndex", I want to find out which actual index the alias is pointing to. This is important for deletion for example..

In general, the result of the query is a little bit confusing. It returns a HashMap'esque structure (the slightly weird ObjectObjectMap.." containing **index-names** as keys and a List of AliasMetaData as value.

Wouldn't it be more convenient the other way round, considering the use case here?

Now, in Elasticsearch 2 a query for a given alias identifier returned the ObjectObjectMap with only the index / indices in question in the keySet. This was easy to process nevertheless.

Now, in Elasticsearch 6 (can't really tell how it was with 5) the result is really inconvenient. 
The Map now contains EVERY possible key (= all index names!) and 99% empty lists as values, besides the one that contains the alias in question...

This is super difficult to parse..

Please look at the below code:

```
public String aliasTarget(String alias) {
        final GetAliasesResponse response = client.admin().indices().prepareGetAliases().addAliases(alias).execute().actionGet();
        String indexInstanceName = null;
        ImmutableOpenMap<String, List<AliasMetaData>> aliasMap = response.getAliases();
        for (ObjectObjectCursor<String, List<AliasMetaData>> cursor : aliasMap) {
            List<AliasMetaData> meta = aliasMap.get(cursor.key);
            if (meta != null && !meta.isEmpty()) {
                if (meta.get(0).alias().equals(alias)) {
                    indexInstanceName = cursor.key;
                    break;
                }
            }
        }
        return indexInstanceName;
    }
```

This is what I have to do, to find out the actual indexName an alias is pointing to. Please note, that the iteration over the list of meta data is left out here for "simplicity".

Cheers

Chris

**Comment by dliappis** [comment]
While the Transport Client is [deprecated in 7.0.0](https://github.com/elastic/elasticsearch/commit/3e8ca38fcaaa2e92d14baa09ac5aed8e560756de#diff-706d3c5fc23f7c60ffb0655dcfe1e1a9) in favor of the [Java High Level Rest Client](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.4/java-rest-high.html), the request here is relevant to the HLRC as well and it will be tackled in HLRC instead.

Relabeling issue accordingly.

**Comment by timoninmaxim** [comment]
Hi @dliappis ! I've made some exploration. There are [tests](https://github.com/elastic/elasticsearch/blob/09b46c8/client/rest-high-level/src/test/java/org/elasticsearch/client/IndicesClientIT.java#L979) that cover the case described in the issue. Filters by aliases or indices works correctly. Looks like it already fixed.

Is there a necessity to implement a new API that would return more convenient map for such case (**alias** to **index**)?

**Comment by probakowski** [comment]
Thanks @timoninmaxim for checking this. I don't think there is need for another API here.
Response from `getAlias` is consistent with REST API and returns easy-to-work-with `Map`. 
If we need reverted relation (map alias-> set of indices, as alias can point to multiple indices) we can use something like:
```java
Map<String, Set<String>> getAliasesMap(GetAliasesResponse response) {
    return response.getAliases().entrySet().stream()
        .flatMap(e -> e.getValue().stream().map(v -> new Tuple<>(v.getAlias(), e.getKey())))
        .collect(groupingBy(Tuple::v1, mapping(Tuple::v2, toSet())));
}
```
I'll close this issue for now, feel free to reopen if the problem still persists in HLRC
