### ISSUE TITLE
Reintroduce Ouput field on Completion Suggester

### ISSUE THREAD

**Issue by Tiedye** [elastic/elasticsearch#32690]
I have a document that contains a nested array of things I'd like to use the completion suggester for, however since there is no way for me know witch nested field matched the query I cannot reformat the output in a consistent format.  For example:

A document:
```
{
    "products": [
        {
            "name": ["cows milk", "milk"]
        },
        {
            "name": ["green apples", "apples green"]
        }
    ]
}
```

If I search `apple` I would like the suggestion to be `green apples` not `apples green`.  This would have been possible previously with the `output` field as the document could be described as follows:

```
{
    "products": [
        {
            "name": {"output": "milk", "input": ["cows milk", "milk"]}
        },
        {
            "name": {"output": "green apples", "input": ["green apples", "apples green"]}
        }
    ]
}
```

And the completion suggester would return what you would expect.

If there is another efficient way to achieve the same result I'd love to see it.

**Comment by Tiedye** [comment]
What kind of response time should usually be expected for these kinds of issues?

**Comment by Tiedye** [comment]
Any update?

**Comment by javanna** [comment]
hi @Tiedye sorry about the radio silence. Given that the completion suggester returns now the `_source` field, meaning the entire documents that match, you can have the desired output in any field of your documents. I had a look at your example and I have a couple of questions though: why use an array for the suggestions? Would it be possible to simplify things and have one suggestion per top-level document, maybe in a separate index? Could you share more about your use-case please including your mappings?

**Comment by Tiedye** [comment]
@javanna The suggester does return the whole documents, but that is insufficient when you need to know which text exactly matched the input.  In my example you have a document with an array of unique products each with a unique name.   Returning the whole document doesn't tell me which product is matching and thus doesn't tell me what suggestion I should put in an autocomplete.

A separate index would solve this problem (with the performance hit of maintaining another index) but having the output field return would be a mach cleaner and likely more efficient solution.

If you mean why use an array like `["green apples", "apples green"]` for the suggestions, it's to make the same "product" match multiple prefixes (as the completion suggester does prefix matching.)

The mapping is a bit of a PITA to get atm, let me know if you really want it.

**Comment by javanna** [comment]
thanks for your explanation @Tiedye . Each one of your documents contains an array of products, each product item is a separate suggestion. I wonder, why do you need to store suggestions within your ordinary documents? Do you only want to return suggestions or more? What does your whole search request look like?

**Comment by Tiedye** [comment]
@javanna The query is just asking for suggestions.  There is no particular need for storing the suggestions alongside the ordinary documents besides keeping related information together in the index, allowing easy creating/updating/deleting of the data.  There are other fields which are used by other (non suggest) queries.

**Comment by javanna** [comment]
ok, you might be able to get the 2.4 behaviour (which I have verified, I was not sure it would work but it indeed does!) if you add your own output field to your documents in the products array, but I guess you will need to use the nested type in combination with inner_hits to get back the matching nested docs only. I honestly don't think this is worth the trouble . Generally speaking, suggestions are better handled in their own separate index, and I would recommend that you do that.

**Comment by Tiedye** [comment]
Yeah nested documents probably would work in this case, thanks for the feedback
