### ISSUE TITLE
startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards

### ISSUE THREAD

**Issue by shaunstone** [elastic/elasticsearch#32694]
I have followed this issue #28474  and I am still getting the offset issue. 
 if i switch to a whitespace  tokenizer it resolves this issue (however it causes other use case of mine to fail)

below is a simple test showing the failure (assuming elasticsearch is running locally on 9200)

```
#!/bin/bash

MAPPING=$(cat << 'EOM'
{
  "mappings": {
    "stadium": {
      "properties": {
        "name": {
          "type": "text",
          "analyzer": "autocomplete"
        }
      }
    }
  },
  "settings": {
    "index": {
      "analysis": {
        "filter": {
          "synonym": {
            "type": "synonym",
            "synonyms": [
              "msg,madison square garden"
            ]
          },
          "edge_n_gram": {
            "type": "edgeNGram",
            "min_gram": 2,
            "max_gram": 15
          }
        },
        "analyzer": {
          "autocomplete": {
            "tokenizer": "keyword",
            "filter": [
              "lowercase",
              "synonym",
              "word_delimiter_graph"
            ]
          }
        }
      }
    }
  }
}
EOM
)
DOC='{"name":"Madison Square Garden"}'
INDEX=location

echo $MAPPING
curl -X DELETE http://localhost:9200/$INDEX
echo "$INDEX Deleted"
curl -d "$MAPPING" -X PUT -H 'Content-Type: application/json'  http://localhost:9200/$INDEX
echo "$INDEX Created"

curl -d "$DOC" -X POST -H 'Content-Type: application/json'  http://localhost:9200/$INDEX/stadium/msg ```

**Comment by jimczi** [comment]
If you switch the `synonym` filter to a `synonym_graph` your example works as expected. Mixing `synonym_graph` and `word_delimiter_graph` is not fully supported though since these filters are not able to handle an input with multiple paths. Your example is a bit different because it uses a `keyword` tokenizer so you can only have one position in the stream. I am closing this issue because the recreation works with a `synonym_graph`, thanks @shaunstone for reporting.

**Comment by shaunstone** [comment]
Thanks for the update @jimczi.  I have a couple of concerns about switching to the `synonym_graph` was that for one it is marked as "experimental" in the es [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-graph-tokenfilter.html) (as is `word_delimiter_graph`) and also it is recommended that we not use the `synonym_graph` for index time synonyms.

**Comment by jimczi** [comment]
The recommendation around synonyms in general is that you should use `synonym_graph` at query time if you have multi word rules like `msg, madison square garden`. This way we are able to preserve the path of each synonym in the query and combine it with other terms that appear before and after it. 
In your example you apply synonyms at index *and* query time but you use expanding rules (`mvg, madison square garden`) so you should apply it only at query time and use the `synonym_graph`.
Regarding the `experimental` status we'll remove it soon so you shouldn't worry too much. We plan to keep this filter and we will not change its behavior without proper deprecation.

**Comment by shaunstone** [comment]
awesome thanks alot @jimczi

**Comment by pankaj3-s** [comment]
Fantastic!!
