### ISSUE TITLE
Security CLI test suite is empty on FIPS JVM

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#32698]
I pushed 4cbcc1d to add a dummy test.

That may be all we need to do (in which case this issue can be closed) but we may want to skip the whole project instead.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/223/console

**Comment by tvernum** [comment]
Also pushed dummy test to 6.4/6.x
- 597ed28
- 5b17341

**Comment by jkakavas** [comment]
Handled in https://github.com/elastic/elasticsearch/pull/32812
