### ISSUE TITLE
Field Alias / Field Collapsing Rest Tests fail on BWC builds

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#32697]
I disabled these tests:
- `6.4`: 86c77d0 
- `6.x`: 9e6bf75

The problem is two-fold
1. field aliases require "single-type", but it's not possible to set "single-type" on 5.x
2. it's not possible to create a field alias before 6.4

Those 2 index settings (/mapping) need to go in the `setup` section, but be skipped on versions before 6.4
I _think_ that can only be done by moving these tests to a new `yml` file and skipping it all before `6.3.99` as I don't think we can conditionally skip 1 setup block based on BWC version (but I may be mistaken, I'm no expert)

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+intake/36/consoleFull
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/2229/console

Relates: 32648

**Comment by jtibshirani** [comment]
Thank you @tvernum for diagnosing the issue! Next time I will keep an eye on those BWC builds...

**Comment by jtibshirani** [comment]
This has been fixed in the following commits:
- 6.4: https://github.com/elastic/elasticsearch/commit/456999a872e63aee53813ef346f90369c4c4bc4d
- 6.x: https://github.com/elastic/elasticsearch/commit/45b114ac31b51fa4c6a8272e69ecdd183bf76e6c
