### ISSUE TITLE
[CI] Netty4HttpServerPipeliningTests is susceptible to timeouts

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#32702]
From https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java10,nodes=virtual&&linux/23/console

```
20:18:30 HEARTBEAT J3 PID(3393@worker-098f258273371858e.build.us-west-2a.elasticnet.co): 2018-08-07T20:18:30, stalled for 21.5s at: Netty4HttpServerPipeliningTests.testThatHttpPipeliningCanBeDisabled
20:18:40 HEARTBEAT J3 PID(3393@worker-098f258273371858e.build.us-west-2a.elasticnet.co): 2018-08-07T20:18:40, stalled for 31.5s at: Netty4HttpServerPipeliningTests.testThatHttpPipeliningCanBeDisabled
20:18:45 Suite: org.elasticsearch.http.netty4.Netty4HttpServerPipeliningTests
...
20:18:45 FAILURE 32.8s J3 | Netty4HttpServerPipeliningTests.testThatHttpPipeliningCanBeDisabled <<< FAILURES!
20:18:45    > Throwable #1: java.lang.AssertionError: 
20:18:45    > Expected: a collection with size <6>
20:18:45    >      but: collection size was <1>
20:18:45    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
20:18:45    > 	at org.elasticsearch.http.netty4.Netty4HttpServerPipeliningTests.testThatHttpPipeliningCanBeDisabled(Netty4HttpServerPipeliningTests.java:150)
```

Based on the 30+ second stalling, and the resulting failure it looks like it timed-out waiting on this latch:
https://github.com/elastic/elasticsearch/blob/c313f11e1f06b7b84bbbe2c70e69fca976c15a28/modules/transport-netty4/src/test/java/org/elasticsearch/http/netty4/Netty4HttpClient.java#L148

It might be better to have an explicitly timeout failure rather than continue on and fail with an unrelated assertion. (Or just increase the timeout).

**Comment by tvernum** [comment]
I see that the Netty client has just been replace with a Nio client on master (https://github.com/elastic/elasticsearch/pull/32621) but it has the same latch behaviour.

**Comment by original-brownbear** [comment]
@tvernum makes sense to me. I don't think we really need a higher timeout here (I can't see where it wouldn't be a bug of sorts when the requests in a single batch need more than 30s to get a response) so I added the explicit `fail`s in https://github.com/elastic/elasticsearch/pull/32708
