### ISSUE TITLE
[CI] Failure due to hard coded minio port

### ISSUE THREAD

**Issue by tvernum** [elastic/elasticsearch#32701]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.4+multijob-unix-compatibility/os=fedora/20/console

```
20:21:44 > Task :plugins:repository-s3:startMinio FAILED
20:21:44 Task ':plugins:repository-s3:startMinio' is not up-to-date because:
20:21:44   Task has not declared any outputs despite executing actions.
20:21:44 7ERROR 8[6CUnable to start the server: Port :60920 is already in use.
20:21:44 7      8[6C> Please ensure no other program uses the same address/port.
20:21:44 :plugins:repository-s3:startMinio (Thread[Task worker for ':' Thread 13,5,main]) completed. Took 0.018 secs.
20:21:44 * Where:
20:21:44 :plugins:repository-s3:integTestMinioCluster#stop (Thread[Task worker for ':' Thread 13,5,main]) started.
20:21:44 Build file '/var/lib/jenkins/workspace/elastic+elasticsearch+6.4+multijob-unix-compatibility/os/fedora/plugins/repository-s3/build.gradle' line: 245
```

The tests for minio use a hard-coded port number (`60920`), which caused a CI failure.
https://github.com/elastic/elasticsearch/blob/4cbcc1d659c7d51703345cce01f51fb24f4e9bde/plugins/repository-s3/build.gradle#L135

**Comment by tvernum** [comment]
Another:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2487/console

```
05:17:04 > Task :plugins:repository-s3:startMinio FAILED
...
05:17:04 7ERROR 8[6CUnable to start the server: Port :60920 is already in use.
05:17:04 7      8[6C> Please ensure no other program uses the same address/port.
```

**Comment by bleskes** [comment]
@tlrx can you take a look when you have a moment? Thanks.

**Comment by jasontedor** [comment]
@ywelsch Might be interested too. If I recall from a past discussion this is a limitation at this time?

**Comment by spinscale** [comment]
another one: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java10,nodes=virtual&&linux/228/console

had a quick look and minio does not allow for binding to any port and report back, you have to specify a port between 1 and 65535 yourself

**Comment by ywelsch** [comment]
We can have it retry on a higher port. I'm astonished though that this is causing issues on CI as we have other places in our build with hard-coded ports.

**Comment by dnhatn** [comment]
Relates https://github.com/elastic/elasticsearch/issues/32208
