### ISSUE TITLE
Identify incoming TLS connections to a non-TLS transport port

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#32704]
Today if something attempts to make a TLS connection to a non-TLS-enabled transport port, the resulting message is somewhat cryptic:

```
[2018-08-08T08:03:30,639][WARN ][o.e.x.s.t.n.SecurityNetty4ServerTransport] [9lL0_Bb] exception caught on transport layer [NettyTcpChannel{localAddress=/127.0.0.1:9300, remoteAddress=/127.0.0.1:57059}], closing connection
io.netty.handler.codec.DecoderException: java.io.StreamCorruptedException: invalid internal transport message format, got (16,3,1,2)
```

The first three bytes `16 03 01` identify this as a TLS 1.0 handshake, and the 6th byte (available but not shown here) is `01` since this is a `Client Hello` message). `16 03 02` and `16 03 03` respectively mean TLS 1.1 and TLS 1.2.

We currently identify traffic that looks like HTTP arriving at a transport port and respond accordingly, helping users to debug some networking issues, and I think it'd be useful to enhance the message logged here similarly.

I think it would be enough to match `16 03 ?? ?? ?? 01` but maybe there should be tighter bounds on the third byte?

Relates https://discuss.elastic.co/t/getting-invalid-internal-transport-message-format-when-using-java-transportclient-shield/79951

**Comment by jasontedor** [comment]
Thanks @DaveCTurner although I think @jpcarey opened #32688 before this and this one could be closed as a duplicate of that?
