### ISSUE TITLE
To be able to distinguish relavancy score using highlighting when combining with match and prefix queries on not analized fields

### ISSUE THREAD

**Issue by contactonder** [elastic/elasticsearch#32718]
Hi, 

I want to be able to distinguish relevancy score using highlighting when combining with the match and prefix queries on not analyzed fields. Let me give you an example.

Sample DSL to search Product numbers and highlight resultset :

{
  "size": 15,
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "must": [
              {"term": {"AvailableForMarket": {"value": "true"}}},
              {"range": {"AvailabilityDate": {"lte": "now/d"}}}
            ]
          }
        },
        {
          "bool": {
			"should": [
			  {"term": {"ProductNumber.keyword": {"value": "TL072ACP","boost": 5}}},
			  {"term": {"ProductNumber.normalised": {"value": "TL072ACP","boost": 4}}},
			  {"prefix" : { "ProductNumber.keyword" :  { "value" : "TL072ACP", "boost" : 2 }}}
			]
		  }              
        }		
      ]
    }
  },
  "_source": {
    "includes": [
      "ProductNumber", 
      "LongDescription",      
      "Brand",      
      "AvailabilityDate"    
    ],
    "excludes": []
  },
  "highlight": {"type" : "unified", "require_field_match": true,"fields": {"ProductNumber*": {}}
  }
}

When I execute this query, I saw highlighted section like below.

"highlight": {
                    "ProductNumber.keyword": [
                        "<em>TL072ACPE4</em>"
                    ]
                }

Instead, I want to see as something like this:

"highlight": {
                    "ProductNumber.prefix": [
                        "<em>TL072ACP</em>E4"
                    ]
                }

Is it something possible? Many thanks.

Kind Regards,
Onder

**Comment by jimczi** [comment]
I like the idea of tagging an highlight with the leaf query that matches but currently we don't have this information at hand in the highlighters.
Can you use [named queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-named-queries-and-filters.html) instead ? They are made for this kind of use case.

**Comment by nik9000** [comment]
No further feedback received. @contactonder if you have the requested 
information please add it in a comment and we can look at re-opening 
this issue.
