### ISSUE TITLE
Phrase suggester not respecting certain filters in collate query

### ISSUE THREAD

**Issue by nickdatum** [elastic/elasticsearch#32712]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.2

**Plugins installed**: none

**JVM version** (`java -version`): Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:

When adding bool / filter to the collate as inline query, the results do not return accurately. This did not happen on a small index with my test environment but did on a larger index with several thousand items

In the example below, when deleted was changed from status "no" to "yes", suggestions were still occuring.

This works fine on my local test environment setup on Vagrant with the same setup as live, the only difference is my test environment has a small index of about 10 documents where the live environment has hundreds of documents in the index.

**Steps to reproduce**:

Request:

`{"index":"r_search_2","type":"_doc","request_cache":false,"body":{"size":1,"suggest":{"text":"qwertt","ruby_search_2":{"phrase":{"field":"Name","max_errors":2,"confidence":1,"highlight":{"pre_tag":"<strong>","post_tag":"<\/strong>"},"size":1,"collate":{"query":{"inline":{"bool":{"filter":[{"term":{"Deleted":"no"}}]}}},"prune":false}}}}}}`

```
(
    [index] => r_search_2
    [type] => _doc
    [body] => Array
        (
            [size] => 1
            [suggest] => Array
                (
                    [text] => qwertt
                    [r_search_2] => Array
                        (
                            [phrase] => Array
                                (
                                    [field] => Name
                                    [max_errors] => 2
                                    [confidence] => 1
                                    [highlight] => Array
                                        (
                                            [pre_tag] => <strong>
                                            [post_tag] => </strong>
                                        )
                                    [size] => 1
                                    [collate] => Array
                                        (
                                            [query] => Array
                                                (
                                                    [inline] => Array
                                                        (
                                                            [bool] => Array
                                                                (
                                                                    [filter] => Array
                                                                        (
                                                                            [0] => Array
                                                                                (
                                                                                    [term] => Array
                                                                                        (
                                                                                            [Deleted] => no
                                                                                        )
                                                                                )
                                                                        )
                                                                )
                                                        )
                                                )
                                            [prune] => false
                                        )
                                )
                        )
                )
        )
)
```

**Comment by jimczi** [comment]
Can you provide a full recreation of the issue. It's hard to understand your problem if you don't describe what you want to achieve and the operations you've made on your cluster. Can you add the mapping of your index and an explanation of why a suggestion should not occur. The `collate` query can be used to ensure that the `suggestion` can match documents, in your example the `collate` query is the same for all suggestions so any suggestion will be returned if the shard has at least one document that match the `collate` filter.

**Comment by nik9000** [comment]
No further feedback received. @nickdatum  if you have the requested 
information please add it in a comment and we can look at re-opening 
this issue.
