### ISSUE TITLE
Support for custom per request maxRetryTimeout on RestClient

### ISSUE THREAD

**Issue by filiphr** [elastic/elasticsearch#32724]
Currently it is not possible to configure the `maxRetryTimeout` in the `RestClient` on a case by case bases for the sync requests. It would be good to have such support.

**Comment by javanna** [comment]
Agreed, related to #21789 if not the same issue. Also #25951 is related.

**Comment by filiphr** [comment]
Just saw that this has been marked for the High Level REST Client. It would be good to have it there as well, but I was referring more to the Low Level REST Client. I think it would make sense to have it there as well.

**Comment by javanna** [comment]
you are correct @filiphr , this is a low-level REST client change that the high-level REST would also benefit from, automatically. Thanks for noticing that.

**Comment by javanna** [comment]
This no longer applies, we have deprecated max retry timeout in 6.x, as well as increased its default value to 90 seconds (#38425) and removed it in 7.0 (#38085).
