### ISSUE TITLE
[DOCS] Refine full verification mode requirements for Transport layer TLS

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch#32729]
Relates: https://discuss.elastic.co/t/elasticsearch-tls-with-wildcard-san/139972/7

The documentation for configuring TLS on the Transport layer could be improved to provide additional detail when configuring `full` verification mode for TLS on the Transport layer.

When specifying the hostname as `network.publish_host` or (`network.host`), the publish address resolves to the IP address on the network. For example, in config

```
network.host: ["data-0"]
```

results in
```
[2018-07-02T00:45:20,095][INFO ][o.e.t.TransportService   ] [data-0] publish_address {10.0.0.6:9300}, bound_addresses {10.0.0.6:9300}
```

and it looks like `NetworkService` always resolves a string host to an `InetAddress`:

https://github.com/elastic/elasticsearch/blob/9b00f095b94c7fb6b568e5e36a264d2ae8c293c5/server/src/main/java/org/elasticsearch/common/network/NetworkService.java#L133-L176

What this ultimately means is that a certificate with _only_ a DNS Subject Alternative Name can't be used with `full` verification mode for the Transport layer, _without_ also specifying an IP SAN, since communication on the Transport layer with other nodes will be using the IP address.

I think the documentation should include a NOTE admonition or similar against `xpack.security.transport.ssl.verification_mode` under https://www.elastic.co/guide/en/elasticsearch/reference/6.3/security-settings.html#transport-tls-ssl-settings to indicate that a certificate must include an [ipAddress SAN](https://tools.ietf.org/html/rfc5280#section-4.2.1.6) to be used with `full` verification mode for the Transport layer.

It may also be worth calling this out in the `certutil` docs too at https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-tls.html#node-certificates ?

**Comment by jaymode** [comment]
This seems more like a bug than a docs issue to me. We should be able to perform full hostname verification with only a DNS SAN. In the discuss issue, it doesn't seem like publish host is set?

The fact that we resolve a string host to an InetAddress should not be an issue. The InetAddress should retain the host string that it was created with.

**Comment by jaymode** [comment]
Based on the discuss issue's lack of response and a recent test by @DaveCTurner showed that full works with a DNS only SAN, I am going to close this issue.
