### ISSUE TITLE
Cluster routing allocation filtering by node can break with multiple exclusions

### ISSUE THREAD

**Issue by inqueue** [elastic/elasticsearch#32721]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.1

**JVM version** (`java -version`): openjdk version "1.8.0_171"

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 16.04.2 LTS

**Description of the problem including expected versus actual behavior**:
Shard allocation exclusions appear to be broken after multiple exclusions have been applied for the same node, then one exclusion removed. 

**Steps to reproduce**:
The repro this is pretty straightforward. This may be a corner case, but it is enough to add confusion when managing a cluster. This repro excludes a single node by both IP and host in dynamic cluster settings, then removes the host exclusion. Once the condition is created, the IP exclusion is ignored. Full requests and responses have been posted to https://gist.github.com/inqueue/43fab958c708b485676f82b225090040.

```
GET _cluster/settings

GET _cat/allocation?v&s=node

PUT _cluster/settings
{
  "transient" : {
    "cluster.routing.allocation.cluster_concurrent_rebalance" : "2",
    "cluster.routing.allocation.exclude._ip" : "10.0.2.55",
    "cluster.routing.allocation.exclude._host" : "json5x60-3.ip.es.io"
  }
}

GET _cat/allocation?v&s=node

PUT _cluster/settings
{
  "transient" : {
    "cluster.routing.allocation.cluster_concurrent_rebalance" : "2",
    "cluster.routing.allocation.exclude._ip" : "10.0.2.55",
    "cluster.routing.allocation.exclude._host" : null
  }
}

GET _cat/allocation?v&s=node

PUT _cluster/settings
{
  "transient" : {
    "cluster.routing.allocation.cluster_concurrent_rebalance" : "2",
    "cluster.routing.allocation.exclude._ip" : "10.0.2.55",
    "cluster.routing.allocation.exclude._host" : null
  }
}

GET _cat/allocation?v&s=node

PUT _cluster/settings
{
  "transient" : {
    "cluster.routing.allocation.cluster_concurrent_rebalance" : "2",
    "cluster.routing.allocation.exclude._ip" : "10.0.2.55",
    "cluster.routing.allocation.exclude._host" : "json5x60-3.ip.es.io"
  }
}

GET _cat/allocation?v&s=node
```

To fix null out all exclusions and reapply if needed:
```
PUT _cluster/settings
{
  "transient" : {
    "cluster.routing.allocation.cluster_concurrent_rebalance" : "2",
    "cluster.routing.allocation.exclude._ip" : null,
    "cluster.routing.allocation.exclude._host" : null
  }
}

GET _cat/allocation?v&s=node

PUT _cluster/settings
{
  "transient" : {
    "cluster.routing.allocation.cluster_concurrent_rebalance" : "2",
    "cluster.routing.allocation.exclude._ip" : "10.0.2.55",
    "cluster.routing.allocation.exclude._host" : null
  }
}

GET _cat/allocation?v&s=node
```

**Comment by cbismuth** [comment]
Looks pretty interesting! I'm digging into this one.

**Comment by cbismuth** [comment]
I've opened a pull request to fix this issue, see https://github.com/elastic/elasticsearch/pull/33638.
