### ISSUE TITLE
Tune for search speed documentation

### ISSUE THREAD

**Issue by ahadadi** [elastic/elasticsearch#32733]
In [Tune for search speed](https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-search-speed.html#tune-for-search-speed) there are two sections recommending to map numeric identifiers as keywords.
One is [Mappings](https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-search-speed.html#_mappings) and the other is [Map identifiers as keyword](https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-search-speed.html#_map_identifiers_as_literal_keyword_literal).
Only [Map identifiers as keyword](https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-search-speed.html#_map_identifiers_as_literal_keyword_literal) should be kept, or the sections can be merged.

**Comment by cbuescher** [comment]
@ahadadi thanks for this observation, I agree and opened #33315. Lets see what others think.
