### ISSUE TITLE
Questions about sequence number

### ISSUE THREAD

**Issue by yiguolei** [elastic/elasticsearch#32740]
when primary changes, I only find the primary shard will send resyc request to replicas. And the replica only trim translogs but not trim the state in lucene.   There will be some errors in race conditions. For example:
3 replicas, A,B,C. 
A is primary.
A send record (seq=10) to B, C    but B not receive the record , C received the record and A crashed.
Master selects B as the new primary, the primary term changes.
But B not trim the record with seq=10 on C. so that C has an extra record. The 2 replica are not in consistency state.

I think B should send a trim request to C but I could not find it in source code.

Do I miss anything?

**Comment by ywelsch** [comment]
We are currently working this (see the open points on https://github.com/elastic/elasticsearch/issues/10708 under the section titled "Live replica/primary sync with rollback"). This work was a little delayed as we were evaluating different options for the Lucene rollbacks, in particular in light of Lucene's new soft-delete feature. If you have more questions on this, please open a topic on `discuss.elastic.co` and ping me there. Github is meant to be mainly used for feature requests and bug reports.
