### ISSUE TITLE
Documentation claims "index.translog.sync_interval" is dynamic, but it can not be set dynamically

### ISSUE THREAD

**Issue by ferronrsmith** [elastic/elasticsearch#32763]
```json
{
    "error": {
        "root_cause": [
            {
                "type": "remote_transport_exception",
                "reason": "[fKNxi7c][10.0.0.155:9300][indices:admin/settings/update]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "Can't update non dynamic settings [[index.translog.sync_interval]] for open indices ["
    },
    "status": 400
}
```

Tested on ES 6.3.2

https://www.elastic.co/guide/en/elasticsearch/reference/6.4/index-modules-translog.html

**Comment by markharwood** [comment]
A "dynamically updatable" setting has a strict definition - that nodes don't have to be restarted for them to take effect.
The error message is not complaining about the fact that the setting is not dynamic - it's because your index is still open.
If you close the index first this setting can be changed without restarting nodes.
Does that solve this issue?

**Comment by ferronrsmith** [comment]
In a production environment that's a problem, but thanks. I'll see how best to do this. Feel free to close. Documentation should be a bit more clear on the strictness

**Comment by markharwood** [comment]
I suspect it's not the only setting that requires a closed index so that's probably worth considering in any alteration to the docs.

**Comment by ywelsch** [comment]
As `index.translog.durability` is a dynamic setting, I think we should make this one dynamic as well. In terms of implementation, it can reuse the same triggers we have build to make `index.translog.durability` dynamically switchable. Could be a adoptme / low-hanging fruit. In the mean-while we should fix the docs though. WDYT @markharwood ?

**Comment by jubyvictor** [comment]
I would like to work on this.

**Comment by jubyvictor** [comment]
Yes I'm.

**Comment by ywelsch** [comment]
There is already another attempt of this up, see #37382
