### ISSUE TITLE
Truncated score when using the significat terms aggregation

### ISSUE THREAD

**Issue by Blakko** [elastic/elasticsearch#32770]
When using the significant terms aggregation with the `Java High Level REST Client` the returned score is truncated.
What i mean is that when querying ES via API i get the correct score eg: `0.1243235`, but the same query executed via the client returns a score of `0.0`.

Looking at the code it feels like here https://github.com/elastic/elasticsearch/blob/9561a0a66ed4eedd98b479681df81f938234651b/server/src/main/java/org/elasticsearch/search/aggregations/bucket/significant/ParsedSignificantTerms.java#L178

there should be 
```javascript
bucket.score = parser.doubleValue();
```

**Comment by markharwood** [comment]
Thanks, good catch!
