### ISSUE TITLE
[Feature request]: Bool query needs real OR semantic

### ISSUE THREAD

**Issue by aimeos** [elastic/elasticsearch#32778]
When building BOOL queries, there's no real OR semantic, only SHOULD but it behaves differently.
Example:
```
"bool": {
  "must": [{
    "product_status": 1
  }],
  "should": [{
    "terms": {"product_category": [1, 3, 5]}
  }]
}
```
This ignores the product_category limitation completely because "should" is ignored if "must" is available too. This leads to totally wrong results because all active products are returns but not limited to the categories. It's also not possible to use the "product_category" values in the "must" term because then the products must be in category 1, 3 AND 5 which returns no result set.

**Comment by markharwood** [comment]
You mean this?

	POST test/_search
	{
	  "query": {
		"bool": {
		  "must": [
			{
			  "term": {
				"product_status": 1
			  }
			},
			{
			  "bool": {
				"should": [
				  {
					"terms": {
					  "product_category": [1,3,5]
					}
				  }
				]
			  }
			}
		  ]
		}
	  }
	}

I can't see us changing `bool` syntax now - Lucene has had close to 20 years of using this style and if I recall correctly the early days of elasticsearch had "OR" type clauses which were removed in favour of the current bool syntax.

Closing.
