### ISSUE TITLE
[ci] SearchIT.testSearchWithSignificantTermsAgg

### ISSUE THREAD

**Issue by andyb-elastic** [elastic/elasticsearch#32855]
On 6.x, reproduces locally. Looks like this test was added in https://github.com/elastic/elasticsearch/pull/32774

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/2257/console

[build-2257.txt](https://github.com/elastic/elasticsearch/files/2287960/build-2257.txt)

```
REPRODUCE WITH: ./gradlew :client:rest-high-level:integTestRunner -Dtests.seed=4207CF2E79C9815D -Dtests.class=org.elasticsearch.client.SearchIT -Dtests.method="testSearchWithSignificantTermsAgg" -Dtests.security.manager=true -Dtests.locale=pl -Dtests.timezone=Africa/Douala -Dcompiler.java=10 -Druntime.java=8
```

```
  1> [2018-08-14T17:59:39,804][INFO ][o.e.c.SearchIT           ] [testSearchWithSignificantTermsAgg] after test
FAILURE 0.76s | SearchIT.testSearchWithSignificantTermsAgg <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<3> but was:<1>
   >    at __randomizedtesting.SeedInfo.seed([4207CF2E79C9815D:D189593C6CEFC175]:0)
   >    at org.elasticsearch.client.SearchIT.testSearchWithSignificantTermsAgg(SearchIT.java:299)
   >    at java.lang.Thread.run(Thread.java:748)

```

Others
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/2256/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/2255/console

**Comment by markharwood** [comment]
Ugh. Sorry for the noise. Remove now redundant test in https://github.com/elastic/elasticsearch/commit/ecc6dfb1b1b5d2f720c9eb516e892f4325d01043 but forgot about unused imports which are addressed in https://github.com/elastic/elasticsearch/commit/2582b389a3c5baa3c35fdf929d64c2d13cc17876

Will also remove from master.
