### ISSUE TITLE
ES 6.3 flush documentation regarding transaction log deletion

### ISSUE THREAD

**Issue by ahadadi** [elastic/elasticsearch#32869]
ES 6.3 [flush documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-flush.html#indices-flush) states:

"The flush process of an index basically frees memory from the index by flushing data to the index storage and clearing the internal transaction log"

However in [ES 6.0 breaking changes section](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/breaking_60_indices_changes.html#_translog_retention) it's stated that:

"Translog files are now kept for up to 12 hours (by default), with a maximum size of 512mb (default), and are no longer deleted on flush"

Does the transaction log get deleted on flush or not?

**Comment by jasontedor** [comment]
Good catch @ahadadi, this is a documentation bug indeed. We will get that updated.

**Comment by cam72cam** [comment]
It would also be useful to point to this on the reindexing page.  I ran into a issue where I had just enough space to reindex my dataset (with a few % leeway) and spent most of the day trying to track down where all the disk space was being used and why the data would not fit.
