### ISSUE TITLE
JVM heap dump path documentation is incorrect

### ISSUE THREAD

**Issue by bittusarkar** [elastic/elasticsearch#32873]
**Elasticsearch version** (`bin/elasticsearch --version`): Does not matter

**Plugins installed**: Does not matter

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:
The documentation in [https://www.elastic.co/guide/en/elasticsearch/reference/master/heap-dump-path.html](https://www.elastic.co/guide/en/elasticsearch/reference/master/heap-dump-path.html) says 

> If you specify a fixed filename instead of a directory, the JVM will repeatedly use the same file; this is one mechanism for preventing heap dumps from accumulating in the heap dump path.

This is not true. JVM fails to overwrite the heap file with following error (if say the JVM option `-XX:HeapDumpPath=.\heapdump.hprof` was used):
```
java.lang.OutOfMemoryError: Java heap space
Dumping heap to .\heapdump.hprof ...
Unable to create .\heapdump.hprof: File exists
```
As a result, only the first heap dump file will be created. No heap dump file will be created subsequently as the file would already exist. Can you please fix the documentation?

**Comment by jasontedor** [comment]
The documentation is indeed incorrect. The relevant JDK source is when the heap dump writer is [constructed](http://hg.openjdk.java.net/jdk8/jdk8/hotspot/file/87ee5ee27509/src/share/vm/services/heapDumper.cpp#l449), a flag is explicitly passed to *not* overwrite an existing file. Thanks for catching this @bittusarkar, we will get the documentation corrected!
