### ISSUE TITLE
Highlighting with a large field value causes an exception that brings data nodes down

### ISSUE THREAD

**Issue by jorgelbg** [elastic/elasticsearch#32875]
**Elasticsearch version** (`bin/elasticsearch --version`): `6.2.3` / `6.3.2`

**Plugins installed**: `x-pack`

**JVM version** (`java -version`):

```
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):

```
Linux elastic4 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:

If a query with a very long field value is fired against the cluster, like the one shown below *with highlighting enabled*

ℹ️ _Full query can be found in: https://gist.github.com/jorgelbg/ff86aa5632b802f6bcf49c2f6ef90492_

```
{
  "version": true,
  "size": 500,
  "sort": [
    {
      "@timestamp": {
        "order": "desc",
        "unmapped_type": "boolean"
      }
    }
  ],
  "_source": {
    "excludes": [
      
    ]
  },
  "aggs": {
    "2": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "12h",
        "time_zone": "Europe/Berlin",
        "min_doc_count": 1
      }
    }
  },
  "stored_fields": [
    "*"
  ],
  "script_fields": {
    
  },
  "docvalue_fields": [
    "@timestamp"
  ],
  "query": {
    "bool": {
      "must": [
        {
          "match_all": {
            
          }
        },
        {
          "match_phrase": {
            "exception": {
              "query": "<VERY_LONG_TERM>"
            }
          }
        },
        {
          "range": {
            "@timestamp": {
              "gte": 1533074400000,
              "lte": 1535752799999,
              "format": "epoch_millis"
            }
          }
        }
      ],
      "filter": [
        
      ],
      "should": [
        
      ],
      "must_not": [
        
      ]
    }
  },
  "highlight": {
    "pre_tags": [
      "@kibana-highlighted-field@"
    ],
    "post_tags": [
      "@/kibana-highlighted-field@"
    ],
    "fields": {
      "*": {
        
      }
    },
    "fragment_size": 2147483647
  }
}
```

Hits the data nodes, the cluster logs a StackOverflowError and dies with the following error:

```
java.lang.StackOverflowError: null
	at org.apache.lucene.util.automaton.DaciukMihovAutomatonBuilder.replaceOrRegister(DaciukMihovAutomatonBuilder.java:324) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
	at org.apache.lucene.util.automaton.DaciukMihovAutomatonBuilder.replaceOrRegister(DaciukMihovAutomatonBuilder.java:324) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
	at org.apache.lucene.util.automaton.DaciukMihovAutomatonBuilder.replaceOrRegister(DaciukMihovAutomatonBuilder.java:324) ~[lucene-core-7.2.1.jar:7.2.1 b2b6438b37073bee1fca40374e85bf91aa457c0b - ubuntu - 2018-01-10 00:48:43]
```

The `exception` field is stored as a `keyword` type. This is related to the bug fixed in (https://git-wip-us.apache.org/repos/asf?p=lucene-solr.git;h=d78feb2) but since this is in for Lucene 7.5/8.0 probably some safeguard needs to be added from the elasticsearch side.

```json
"exception": {
    "type": "keyword"
},
```

**Steps to reproduce**:

We've encountered this issue in our production cluster, and was able to reproduce it successfully in Elasticsearch 6.2.3/6.3.2 running in a local Docker container:

1. Run an `elasticsearch/elasticsearch` container:

```sh
$ docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:6.3.2
```

2. Create a new index with the `exception` field mapped to a `keyword` type:

```
PUT /php
{
  "mappings": {
    "logs": {
      "_all": {
        "enabled": false
      },
      "properties": {
        "exception": {
          "type": "keyword"
        }
      }
    }
  }
}
```

3. Add a sample document with some long random text on the `exception` field.

4. Fire the query. (Could be done from Kibana, just by adding a filter on the given field/value)

I think this relates to #27517. The danger is not only about slow execution but it could easily take a cluster partially/entirely down.

**Comment by jimczi** [comment]
Thanks @jorgelbg, we are aware of this issue so we've added a protection against long terms in the `DaciukMihovAutomatonBuilder`:
https://issues.apache.org/jira/browse/LUCENE-8429
The fix should be available in Elasticsearch 6.5.
