### ISSUE TITLE
Rollover API is inconsistent and does not guarantee the index rollover successfully

### ISSUE THREAD

**Issue by adeshp** [elastic/elasticsearch#32883]
Elasticsearch version: 6.2.4,
lucene_version :  7.2.1,
Plugins installed: Kibana
JVM version(`java -version`):
         openjdk version "1.8.0_181"
         OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
         OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

OS version (`uname -a` if on a Unix-like system):  
          Linux 4.4.0-1062-aws #71-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux

Description of the problem including expected versus actual behavior:

     ES rollover API should create a new index for a given alias.
     (https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-rollover-index.html)
     
    Actual Behavior is inconsistent. Sometimes it does rollover as it should and create a new index
    with the index name provided in the API request and the alias provided to it.

     Other times, it creates the new index but uses the alias name to name the index rather than the 
     provided index name in the API parameter.

    And there were also couple of instances when it created the the new index using the alias name, 
    then  threw exception that the source alias is a concrete index.
 
 
**Steps to reproduce**:

 1. Create an index.
 2. Add an alias to it.
 3. Use Rollover API provided to rollover this index by providing the new index name that you want to 
      be created and the above alias.

      As the behavior is inconsistent, you may need to try doing it multiple times.

**Provide logs (if relevant)**:
I used Elastic search PHP client latest one. (6.0)
The API is documented at https://www.elastic.co/guide/en/elasticsearch/client/php-api/master/ElasticsearchPHP_Endpoints.html#Elasticsearch_Namespaces_IndicesNamespacerollover_rollover.

The exception that I got:

{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[i-0d69a7ef7e924b55b][172.17.5.70:9300][indices:admin/rollover]"}],"type":"illegal_argument_exception","reason":"source alias is a concrete index"},"status":400}

for the request that I sent:

```
Array
(
    [newIndex] => 1-emails-index-2018-08-13-1
    [alias] => 1-emails-index
    [body] => Array
        (
            [conditions] => Array
                (
                    [max_age] => 167h
                )
            [aliases] => Array
                (
                    [1-emails-index-search] => stdClass Object
                        (
                        )

                )
            [settings] => Array
                (
                    [number_of_shards] => 1
                    [number_of_replicas] => 3
                )
        )
)

```

**Comment by adeshp** [comment]
After debugging our indexing processing, below observations:
We index using bulk api, there is a good amount traffic coming into elastic search for indexing at any second in a day. I run the rollover job at 12 am UTC everyday,  and if traffic is coming to elastic search (content to be indexed) and rollover is in progress, then the bulk API is creating the index from the Alias sent as its parameter. However Bulk API does not specify that it would create an index if the index does not exist but the `index `action can create the index if it does not exist (Automatic Index Creation). Hence it might throw they exceptions that source alias is a concrete index while still in the rollover phase.

Without knowing how rollover is implemented internally, I could only speculate that rollover is not an atomic operation or there is no locking mechanism. The moderators can close this bug if they decide to do so.

**Comment by dakrone** [comment]
I think with ILM in place and supporting Rollover, this is no longer needed since the instructions there set up a single alias to which to direct indexing. Hopefully this is an easier setup for indexing timeseries data.
