### ISSUE TITLE
How to use from and limit in _rollup_search

### ISSUE THREAD

**Issue by jdu-mydevices** [elastic/elasticsearch#32885]
**Describe the feature**:
In the spec below, I didn't find the `from` and `limit` in rollup_search api.
https://github.com/elastic/elasticsearch/blob/72f57c8e72500cb27dc69e902edf5cd270249c14/x-pack/plugin/src/test/resources/rest-api-spec/api/xpack.rollup.rollup_search.json

I had to search and return data to a web page table using `http://eshost/index1,index1_rollup/_rollup_search/`.
How can I send the `from` and `limit`? For example, I only want to show data from 0 to 50, or 51 to 100 to users.

Similar problem in xpack/sql: 
`select campaign_id from campaigndailyreport limit 1 offset 0`
xpack sql can use limit but can not use offset. offset is important for paging.

**Elasticsearch version** (`6.3.2`):

**Plugins installed**: [_xpack]

**JVM version** (`1.8.0_161-b14`):

**OS version** (`Linux 3.10.0-327.10.1.el7.x86_64`):

**Comment by jimczi** [comment]
Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports. Regarding limits in `rollup` search, this API can be used for aggregations only so you cannot retrieve `top_hits` (the `size` is always set to 0). For `sql` there is an open issue about `offset` [here](https://github.com/elastic/elasticsearch/issues/31549).
As such, I hope you don't mind that I close this.
