### ISSUE TITLE
Dynamic index mapper does not allow to set "Strict" rule

### ISSUE THREAD

**Issue by askids** [elastic/elasticsearch#32898]
**Elasticsearch version** (`bin/elasticsearch --version`): 5.5.1
**Plugins installed**: [X-Pack Basic, ReadOnlyRest 1.6.20, Search Guard SSL ]
**JVM version** (`java -version`): 
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b25, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): Windows 2012
**Description of the problem including expected versus actual behavior**:
I am trying apply rule to prevent dynamic creation of fields. So as per documentation, true/false/strict values are allowed.

```
PUT myindex/_settings
{
    "index.mapper.dynamic": "strict"
}

```
But I get the error message as below. Looks like only true and false is allowed as its defined as boolean field. But documentation says that true, false or strict can be used.

https://www.elastic.co/guide/en/elasticsearch/reference/5.5/dynamic.html

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Failed to parse value [strict] cannot be parsed to boolean [ true/1/on/yes OR false/0/off/no ]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Failed to parse value [strict] cannot be parsed to boolean [ true/1/on/yes OR false/0/off/no ]"
  },
  "status": 400
}
```
When I tried without double quotes.
```
{
  "error": {
    "root_cause": [
      {
        "type": "json_parse_exception",
        "reason": "Unrecognized token 'strict': was expecting ('true', 'false' or 'null')\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@50a2e9ab; line: 2, column: 35]"
      }
    ],
    "type": "json_parse_exception",
    "reason": "Unrecognized token 'strict': was expecting ('true', 'false' or 'null')\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@50a2e9ab; line: 2, column: 35]"
  },
  "status": 500
}
```

**Comment by jimczi** [comment]
This setting (`index.mapper.dynamic`)  does not refer to dynamic creation of fields. It controls the dynamic creation of types as explained here:
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/dynamic-mapping.html#_disabling_automatic_type_creation
The docs you linked in the issue is about dynamic fields creation which accepts `true, `false` and `strict` and can only be set inside the mapping.
