### ISSUE TITLE
that is not equal to the supplied origin. Origin 'http://ip:9100' is therefore not allowed access.

### ISSUE THREAD

**Issue by liaoqiArno** [elastic/elasticsearch#32894]
I used the HEAD plugin，and I config the proxy on port 9101,if use the google Elasticsearch Head plugin ,the HEAD can connect the es cluster by use http://ip:9101,It's OK.
but I use  the codes  on the git,I got errors:

Failed to load http://IP:9101/_cluster/state: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:9100' that is not equal to the supplied origin. Origin 'http://IP:9100' is therefore not allowed access.
(index):1 Failed to load http://IP:9101/_stats: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:9100' that is not equal to the supplied origin. Origin 'http://IP:9100' is therefore not allowed access.
app.js:1307 {XHR Error: "error", message: ""}
(index):1 Failed to load http://IP:9101/_nodes: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:9100' that is not equal to the supplied origin. Origin 'http://IP:9100' is therefore not allowed access.
app.js:1307 {XHR Error: "error", message: ""}
(index):1 Failed to load http://IP:9101/_cluster/health: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:9100' that is not equal to the supplied origin. Origin 'http://IP:9100' is therefore not allowed access.
app.js:1307 {XHR Error: "error", message: ""}
(index):1 Failed to load http://IP:9101/_nodes/stats: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:9100' that is not equal to the supplied origin. Origin 'http://IP:9100' is therefore not allowed access. 

my elasticsearch.yml:
cluster.name: ocean-stream-es
node.name: node-91
node.master: true
node.data: true
path.data: /opt/app/elsticsearch-6-3-2/data
path.logs: /opt/app/elsticsearch-6-3-2/logs
network.host: 172.16.30.91
http.port: 9200
transport.tcp.port: 9300
discovery.zen.ping.unicast.hosts: ["172.16.30.91:9300","172.16.30.93:9300","172.16.30.94:9300"]
discovery.zen.minimum_master_nodes: 3
http.cors.enabled: true
http.cors.allow-origin: "*"

Who can help me? 
Thank you very much

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
