### ISSUE TITLE
Cannot bulk index a JSON file greater than 100MB in Elasticsearch. Tried chaning HTTP content length but it doesn't work.

### ISSUE THREAD

**Issue by ShwethaThakur** [elastic/elasticsearch#32933]
I do not get any error when i run this curl command but the index will not be created.
curl -XPOST -u elastic:e2JecfPx "localhost:9200/complete/doc/_bulk?pretty&refresh" --data-binary "@blah.json" -H "Content-Type: application/json"

**Comment by spinscale** [comment]
please create a new post in the discuss forums about this, see https://discuss.elastic.co/c/elasticsearch - also check your logfiles and attach them properly so others have more information, along with the version you are using etc. I will close this issue in github which we try to use for bugs only.

in general you should avoid having such big bulk requests as this will lead to a lot of garbage collection and slow downs (especially on lower heaps), but divide your bulk requests into much smaller pieces (like 5-10 MB is a good place to start and find your sweet spot by changing the size of them).

Testing such a big request in a 1GB instance lead to immediate GC collections and an over all slow down of my ES instance.
