### ISSUE TITLE
SQL query failed due to multi-nested

### ISSUE THREAD

**Issue by spinwang** [elastic/elasticsearch#32930]
I am trying to index the following document and I have made `results` a nested type. 
```
 {
      "template_version": "B",
      "study": {
        "source": "A"
      },
      "results": [
        {
          "barcode": "S",
          "assay": {
            "type": "B",
            "sub_type": "H"
          },
          "value": 0.98,
          "unit": "nM",
          "image": "1d6",
          "metric": "I"
        },
        {
          "barcode": "S",
          "assay": {
            "type": "B",
            "sub_type": "LC"
          },
          "value": 2.3,
          "unit": "nM",
          "image": "1dac",
          "metric": "I"
        }
     ]
}
```

When I run the SQL query `SELECT *, results.*, results.assay.* FROM index`, I got the following error 
```
sql_illegal_argument_exception
Multi-nested docs not yet supported [results, results.assay]
```
Is this a known issue? If so, when/if will this be solved? Is it possible to run `SELECT * FROM index` to get back all the fields/properties (including `results.assay.type` and `results.assay.sub_type`), independent how nested they are?

**Comment by astefan** [comment]
The limitation (so far) here is related to multiple nested fields being retrieved in the same `SELECT`. A nested field could have multiple values (just like an array), another nested field could have an array of values as well (of different size likely). In SQL terms there are rows and columns in the result, meaning a flat data structure like a matrix.

For an index with one document, with a single `nested` field (let's call it `my_nested_field`) that has 7 values and a simple field (non-nested and having a single value, let's call it `my_simple_field`), ES-SQL shows you 7 rows where the value of `my_simple_field` is repeated 7 times and on each row you see each value from the `my_nested_field` field.

The current limitation is that using multiple nested fields, there is no solution (yet) for flattening a combination of nested fields in the matrix-like representation I mentioned before.

**Comment by spinwang** [comment]
thanks @astefan! 

Just curious if there plan to identify a solution in the near future?

**Comment by astefan** [comment]
@spinwang probably not in the near future.
