### ISSUE TITLE
Failing to create create-index-template/put-mapping within 30's

### ISSUE THREAD

**Issue by DarrenV79** [elastic/elasticsearch#32934]
Hi,

Appologies for this bug but I can't find any information anywhere on how to fix this that either works or relates.

Updated the cluster from 6.3.0 to 6.3.2 and started seeing my number_of_pending_tasks never go to 0.

Cluster is 2 clients, 1 master and 2 data, running on AWS.  Up until this update it had been fine.  After I then setup a fresh cluster and changed the endpoint and even a fresh cluster has these issues.  The only logs are either from the log4net appender or Elastic Beats (winevents, packet, metrics).  Errors occur for both types.  All Ubuntu 16.04, runs as systemd where I increase the file limits only.  We only change the swapiness in the sysctl.conf to 1.

"status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 5,
  "number_of_data_nodes" : 2,
  "active_primary_shards" : 200,
  "active_shards" : 400,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 105,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 1931025,
  "active_shards_percent_as_number" : 100.0

Master state
  "compressed_size_in_bytes" : 1096280,
  "master_node" : "-gcmmML3RHu-3XyAWupLBw"

Then pending tasks are all either create-index-template or put-mapping

{"insert_order":5812,"priority":"URGENT","source":"create-index-template [<redacted>], cause [api]","executing":false,"time_in_queue_millis":17977,"time_in_queue":"17.9s"},{"insert_order":5775,"priority":"HIGH","source":"put-mapping","executing":false,"time_in_queue_millis":28602,"time_in_queue":"28.6s"},

These are failing for 95% of the indices.

org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (create-index-template [windeventlog], cause [api]) within 30s
        at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$0(MasterService.java:124) ~[elasticsearch-6.3.2.jar:6.3.2]
        at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_131]
        at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$1(MasterService.java:123) ~[elasticsearch-6.3.2.jar:6.3.2]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:626) [elasticsearch-6.3.2.jar:6.3.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

Cluster settings:

cluster.name: <redacted>
plugin.mandatory: discovery-ec2,repository-s3
discovery.zen.hosts_provider: ec2
discovery.ec2.groups: elasticsearch-6
discovery.ec2.endpoint: ec2.eu-central-1.amazonaws.com
cloud.node.auto_attributes: true
discovery.ec2.availability_zones: ["eu-central-1a", "eu-central-1b"]
network.host: _ec2:privateIp_
xpack.security.enabled: false
thread_pool.bulk.queue_size: 5000
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
node.master: true  <depends on node type>
node.data: false  <depends on node type>
http.enabled: false  <depends on node type>

The only thing changed in the jvm options is the heap sizes (which are half the server size or 32GB for the data nodes).

I have tried putmapping myself and that also fails.

**Comment by DarrenV79** [comment]
So, it seems to rectify if I reboot the data nodes.  Takes a while but does eventually.

If I recreate the cluster and do the data nodes first, then master and clients (currently master, data and client) it seems also to work flawlessly.

**Comment by dakrone** [comment]
This appears to be an issue due to the cluster being overloaded and unable to process the cluster state, rather than a bug.
We reserve Github issues for feature requests and bug reports. If you are having problems please use https://discuss.elastic.co instead!

**Comment by DarrenV79** [comment]
As mentioned it was as totally clean cluster.  

In the end I put the clients back on data nodes.  Otherwise it was 100% repeatable for me at the time.
