### ISSUE TITLE
Make 0 as invalid value for `min_children` in `has_child` query

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch#32949]
0 for `min_children` option in `has_child` query doesn't make sense, because:
1. It is ambiguous. Does it mean to match only parents that either have children matching the specified constraints or no have no children at all.
2. It currently behaves as a value of `1`, that is if there is no at least 1 child matching a specified constrained, a parent document is not returned.

For these reasons, we should make 0 value as invalid value.

Related #21224

**Comment by kevinaud** [comment]
I'm interested in working on this

**Comment by rajeshggwp** [comment]
Is anyone still working on this? If not can I pick this?

**Comment by mayya-sharipova** [comment]
@rajeshggwp  Sorry, we do have an open PR for this: https://github.com/elastic/elasticsearch/pull/33073

**Comment by shoaib4330** [comment]
Is someone working on it? The issue is still open, I plan on working on int.

**Comment by mayya-sharipova** [comment]
@shoaib4330 Sorry, we have a stalled PR opened for it. I think we will just finish that PR.

**Comment by mayya-sharipova** [comment]
@shoaib4330 We have closed a stalled PR #33073, because of inactivity!  If you still would like to work on this issue, please go ahead.

**Comment by shoaib4330** [comment]
Sure. I'm on it then.

**Comment by kutty-kumar** [comment]
@shoaib4330 have u started working on this, if not then i will pick it up.

**Comment by codebird** [comment]
@mayya-sharipova I am new here, can I take on this issue?

**Comment by cbuescher** [comment]
Closed by https://github.com/elastic/elasticsearch/pull/41347
