### ISSUE TITLE
SQL: document the limitations

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#32948]
There are several limitations in ES-SQL in various areas that are not so obvious at first look, especially for users coming from SQL background and with little knowledge about Elasticsearch.
For example, ordering by COUNT(*) not being supported in combination with GROUP BY. It would be useful to have all these limitations in a single page dedicated to this purpose.

**Comment by lanerjo** [comment]
+1

**Comment by astefan** [comment]
This is now done via https://github.com/elastic/elasticsearch/pull/36918.
