### ISSUE TITLE
Document the default max number of buckets in the auto_date_histogram documentation

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#32950]
Document that max_bucket setting means that by default the max number of buckets you can request in the `auto_date_histogram` aggregation is 333.

This is because we need collect `num_buckets * 30` buckets before we can merge up to the next interval

We should also mention that this limit can be changed using the max_buckets setting

**Comment by debadair** [comment]
[doc issue triage]

See discussion in #28993.

**Comment by not-napoleon** [comment]
I think we can close this now that we've resolved #57042, which causes max buckets to only be checked during the reduce phase.  Feel free to reopen if there's a need, but it seems redundant to me at this point.
