### ISSUE TITLE
SQL: consider adding the IN operator support

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#32955]
At the moment the workaround for the missing `IN` support is to provide a long list of `OR` statements. It would be easier/more comfortable to use `IN` instead.
Related to https://github.com/elastic/elasticsearch/issues/32942

**Comment by lanerjo** [comment]
+1
`WHERE visit.app.appName IN ('appA', 'appB')` <- does not work
`terms: {visit.app.appName: [appA, appB]}` <- expected translation of above

`WHERE visit.app.appName = appA OR visit.app.appName = appB` <- very very very inconvenient workaround
