### ISSUE TITLE
[CI] ScriptedMetricIT testInitMapWithParams fails

### ISSUE THREAD

**Issue by jkakavas** [elastic/elasticsearch#32959]
Failed in master twice : https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2549/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2548/console

```
./gradlew :server:integTest \
  -Dtests.seed=D714A8F18E960CA2 \
  -Dtests.class=org.elasticsearch.search.aggregations.metrics.ScriptedMetricIT \
  -Dtests.method="testInitMapWithParams" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-UY \
  -Dtests.timezone=America/Puerto_Rico \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

Reproduces locally also. 

It looks like it fails because of the changes merged today in https://github.com/elastic/elasticsearch/pull/31597

**Comment by rationull** [comment]
This is my mistake -- an oversight in my changes to ScriptedMetricIT. There's a hole where a shard with 0 documents in it will cause a failure because the assertions rely on a side effect from the map script. I will submit a PR with a fix.
