### ISSUE TITLE
SQL: consider adding conditional expression support

### ISSUE THREAD

**Issue by AdiJurca** [elastic/elasticsearch#32984]
At the moment there is no way of doing conditional expressions in SQL.

Having at least the CASE statement and COALESCE as described here 

https://www.postgresql.org/docs/9.4/static/functions-conditional.html

would be of great help.

**Comment by astefan** [comment]
This is already implemented by https://github.com/elastic/elasticsearch/pull/41349 and https://github.com/elastic/elasticsearch/pull/35253.
