### ISSUE TITLE
Plugin install with redirect 301 URL HTTP->HTTPS

### ISSUE THREAD

**Issue by cdenneen** [elastic/elasticsearch#33001]
Tested this with 5.6.9 and 6.3.2 and if you run a `elasticsearch-plugin` with --batch http://url and that url redirects to https it will fail to install the plugin.
If you switch the URL to https it works as it avoids the 301 redirection.

Not sure if it's java or what part is not handling the 301 redirection but it seems like basic functionality it should support.

**Comment by rjernst** [comment]
HttpURLConnection should follow redirects by default. What output do you get from `elasticsearch-plugin` that indicates the installation failure is because of a failure to follow the redirect?

**Comment by javanna** [comment]
Closing due to lack of feedback, we will reopen if we get the requested info above.
