### ISSUE TITLE
Stop-words not removed in simple_query_string when more then one field

### ISSUE THREAD

**Issue by pluk** [elastic/elasticsearch#33009]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.1

**Plugins installed**: []

**JVM version** (`java -version`): java version "1.8.0_102"

**OS version** : ArchLinux

**Description of the problem including expected versus actual behavior**:
Like in #28855 stop-words not removed in simple_query_string but when we use more than one field

**Steps to reproduce**:
1.
PUT /simp_idx
```json
{
  "mappings": {
    "my_type": {
      "properties": {
  		"field_1": {
    			"type": "text"
    		},
                "field_2": {
    			"type": "text"
    		}
      }
    }
  },
  	"settings": {
		"number_of_shards": 1,
		"number_of_replicas": 0,
		"analysis": {

			"filter": {
				"english_stop": {
					"type": "stop",
					"stopwords": "_english_"
				}
			},
			"analyzer": {
				"default": {
					"tokenizer": "standard",
					"filter": [
						"english_stop"
					]
				}
			}
		}
	}
}
```

2.
```json
PUT /simp_idx/my_type/1
{
  "field_1": "normal",
  "field_2": "place of beauty"
}
PUT /simp_idx/my_type/2
{
  "field_1": "place",
  "field_2": "of beauty"
}
PUT /simp_idx/my_type/3
{
  "field_1": "place of beauty",
  "field_2": "place and beauty"
}
```
3.
POST simp_idx/_search
```json
{
  "query": {
    "simple_query_string" : {
        "query": "place of beauty",
        "default_operator": "and",
        "fields": [ "field_1", "field_2"]
    }
  }
}
```
Finds no results.

4. Without "of" returns all 3 documents
POST simp_idx/_search
```json
{
  "query": {
    "simple_query_string" : {
        "query": "place beauty",
        "default_operator": "and",
        "fields": [ "field_1", "field_2"]
    }
  }
}
```

**Comment by metalmumu** [comment]
I still have this issue with 6.3.1
I've tested with 6.4.0 and still here

**Comment by jimczi** [comment]
@metalmumu the fix is not released yet, the pr is marked with 6.4.1 and 6.5.0.

**Comment by metalmumu** [comment]
This issue is still not fixed, tested it with 6.3.2 and 6.4.0

**Comment by metalmumu** [comment]
Do you know when 6.4.1 will be released?
Or could you tell me if there is a version 6.x without this bug?

**Comment by metalmumu** [comment]
I've tested all 6.x version, the bug is since 6.0 ....
