### ISSUE TITLE
what does Rewriteable.rewriteAndFetch do?

### ISSUE THREAD

**Issue by comdotwang162** [elastic/elasticsearch#33054]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
6.2.0
**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
I would like to know what does Rewriteable.rewriteAndFetch do? why twice?

Note of SearchService  method rewriteShardRequest
        // we also do rewrite on the coordinating node (TransportSearchService) but we also need to do it here for BWC as well as
        // AliasFilters that might need to be rewritten. These are edge-cases but we are every efficient doing the rewrite here so it's not
        // adding a lot of overhead

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by javanna** [comment]
hi @comdotwang162 we reserve github issues for verified bugs or feature requests. Could you please ask your question on our forums at https://discuss.elastic.co/ ?
