### ISSUE TITLE
Get extended information about index mappings (templated or not)

### ISSUE THREAD

**Issue by pkaramol** [elastic/elasticsearch#33053]
# Feature Request

**Describe the feature**:

Unless I am wrong, currently there is no way of knowing if an index mapping was

a) auto generated by elastic search during the process of documents' fields discovery

b) enforced by a guideline in the `output` plugin as e.g. in the following example:

```
  elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "my_index"
      template => "/path/to/a/template.json"
      template_name => "my_template_name"
      manage_template => true
      template_overwrite => true
    }
```

When one performs `GET index_name` in `kibana` he does get a mappings json field but how can he say if this was auto generated or came from a template ?

**Comment by colings86** [comment]
@pkaramol Could you explain why its important to you to know if the field was defined in an index template or not? I would like to understand the use case

**Comment by pkaramol** [comment]
It would give prompt feedback on whether the template was applied properly;

today I run in the following case:

I had a template applied to index pattern "somename*"
I had another template applied to index pattern "*some_pattern*"

Then it just so happened that a few index had the name "somename_some_pattern"

It took me some time to figure out that the above situation was giving precedence to the template applied to index pattern: "somename*" (the first one).

I think this is just a case but in general I find it useful for the developer/devops to be able to know whether appropriate template application has occurred or not.

**Comment by markharwood** [comment]
>isn't a good thing to be able to control the field type via templating?

As a general point on prevention, use of `strict` in template mappings can help limit the introduction of new fields. It can be applied at various levels in a document hierarchy to limit the fields introduced.

If you can't prevent unwanted field introduction with `strict` then there are a number of strategies that can aid the detection of the offending template source:
1) On index creation the list of templates that were applied is logged (but not the details of which fields came from which template)
2) In your index template you can associate arbitrary information in the "meta" part of the index mapping - you could use this to include information about templates, versions, fields , author etc
3) We have plans to introduce more granular `meta` information down to field-level (do you have an issue you can share @ruflin ?) which, like 2) would allow recording of your template source in the mapping but applies down to field-level .

Closing given the options presented here.

**Comment by ruflin** [comment]
@markharwood There is no public issue for 3) yet. @jpountz Should we start one or too early?
