### ISSUE TITLE
Show name of cluster in e-mails sent by default watches

### ISSUE THREAD

**Issue by C0FFEEC0FFEE** [elastic/elasticsearch#33051]
**Show name of cluster in e-mails sent by default watches**:
The e-mails sent by the default watches (cluster status, nodes change, version mismatch) should contain the name of the cluster in the subject line for ease of filtering them.

**Comment by dakrone** [comment]
Internal monitoring has been deprecated for quite a while, and we're no longer doing any active development on it. I'm going to close this issue.
