### ISSUE TITLE
regexp does not follow recognized regex if "." or "/" are in the query

### ISSUE THREAD

**Issue by svanschalkwyk** [elastic/elasticsearch#33067]
Elasticsearch version 6.1.5

**Steps to reproduce**:
This is the query
```
{
	"query": {
 			"regexp": {
				"url": ".*reporting\/customer_reporting_data\.aspx"
			}
  }
}
```
it should match 
http://inside.com/pages/sales/reporting/customer_reporting_data.aspx
as per online regex evaluator. 
The last "\." raises an error:
```
{
	"error": {
		"root_cause": [
			{
				"type": "json_parse_exception",
				"reason": "Unrecognized character escape '.' (code 46)\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@1c2730e; line: 4, column: 77]"
			}
		],
		"type": "json_parse_exception",
		"reason": "Unrecognized character escape '.' (code 46)\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@1c2730e; line: 4, column: 77]"
	},
	"status": 500
}
```
When I don't escape the final ".", nothing is matched. 
Issue seem to stem from using a "/" anywhere in the regex, escaped or not.

**Comment by jasontedor** [comment]
You need two `\\` as in `\\/` and `\\.`. This is because there will be two levels of interpretation of the backslashes. The first by the JSON parser (to get you to `\.`) and then by the Lucene regular expressions engine.
