### ISSUE TITLE
Limit the maximum number of concurrent shard searches issued by an msearch request.

### ISSUE THREAD

**Issue by ebernhardson** [elastic/elasticsearch#33072]
The msearch API currently allows limiting the maximum number of concurrent searches performed. I'm interpreting this feature as having the goal of limiting the maximum concurrent load generated by the msearch request. I'm defining maximum concurrent load as the maximum number of threads consumed from search thread pools across cluster at any point in time.  When clusters are fairly uniform the number of searches is a reasonable proxy for generated load, but in heterogeneous clusters (we have indicies ranging from a single shard with <100MB, to 600GB indices with 20 shards) this proxy is less useful.

If the number of concurrent shard searches could be specified it would allow finer grained control of the maximum concurrent load generated by a single msearch query. Single requests could still be processed as normal, but the condition for issuing the next request in the msearch batch would be if the number of shards in the referenced index(es) is less than the remainder of the concurrent shard limit. Queries that can't be issued because they would query more shards than the concurrent limit  would return a failure.

An alternate solution that might be presented is to use the thread pool queues as they were intended, and accept thread pool rejections as back pressure. The difficulty with this solution is there is a single search thread pool, but there can be many kinds of requests. Forcing interactive searches, where latency matters, to sit behind (by default) 1000 non-interactive queries currently waiting for the thread pool is undesirable. Because latency of the interactive searches is important we don't want them to queue up and we treat anything beyond minor queueing to smooth spikes as a problem to be addressed.

**Comment by javanna** [comment]
hi @ebernhardson the search API supports the `max_concurrent_shard_requests` parameter which, from 7.0 on, limits the number of concurrent shard requests per node. This parameter is also exposed to the msearch API, and the same value will be used for each search request included in the msearch request body. It sounds like that would be something along the lines of what you were looking for when you opened the issue, what do you think?

**Comment by ebernhardson** [comment]
Thought about it a bit, this is still indirectly controlling what I would like, but it's significantly better than the previously existing solution. Essentially instead of controlling the concurrent requests per node, i would really like to control the overall number of concurrent requests against all nodes.  I'd accept this as close enough and close if you like.

Thanks for bringing this to my attention, I hadn't noticed this new parameter.

**Comment by jimczi** [comment]
We changed the limit to be applied per node rather than per cluster so I don't think we'll rollback here.
The limitation per node is close to what is proposed in this issue and it is configurable on a per request basis so I am closing this issue.
