### ISSUE TITLE
SQL: Implement missing date/time scalar functions

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#33092]
This is part of https://github.com/elastic/elasticsearch/issues/30007.
Functions considered for implementation:
- [x] CURRENT_DATE( )
- [x] CURRENT_TIME[( time-precision )]
- [x] CURRENT_TIMESTAMP[( timestamp-precision )]
- [x] CURDATE()
- [x] CURTIME()
- [x] DAYNAME( date_exp )
- [x] MONTHNAME( date_exp )
- [x] NOW( )
- [x] QUARTER( date_exp )

**Comment by matriv** [comment]
All listed functions have been implemented.
