### ISSUE TITLE
immediately after 6.4.0 released, apt repository missing all older versions (eg, 6.3.2)

### ISSUE THREAD

**Issue by rpardini** [elastic/elasticsearch#33105]
**This is a bug regarding the APT repositories only, not ES itself!**

**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.0

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 16.04

**Description of the problem including expected versus actual behavior**:
```bash
[root] ~
# cat /etc/apt/sources.list.d/elasticsearch6x.list
deb https://artifacts.elastic.co/packages/6.x/apt stable main

[root] ~
# before 6.4.0 was released...
# apt-cache show elasticsearch | grep ^Version
Version: 6.3.2
Version: 6.3.1
Version: 6.3.0
Version: 6.2.4
Version: 6.2.3
Version: 6.2.2
....etc....
Version: 6.0.1
Version: 6.0.0
Version: 1.7.3+dfsg-3

[root] ~
# after 6.4.0 was released...
# apt-get update
... etc ...

[root] ~
# apt-cache show elasticsearch | grep ^Version
Version: 6.4.0
Version: 6.3.2
Version: 1.7.3+dfsg-3

# where did all the other versions go?
# 6.3.2 still shows up, because that is the version installed on the system
# but on a new system it is impossible to install 6.3.2 using apt repo
# I know I can get 6.3.2 from a .deb file directly, but...
```

**Steps to reproduce**:

Doing an `apt update` after 6.4.0 makes older versions unavailable from the apt repo.
This has happened with 6.3 and 6.2 as well.
After a while (?) it shows back again, maybe a nightly job updates them?

**Comment by nik9000** [comment]
We're aware of this and working to bring them back. Sorry!

**Comment by Conky5** [comment]
The older versions should be back now, apologies!

**Comment by rpardini** [comment]
Confirmed working again, thanks.
