### ISSUE TITLE
Docs build fails due to missing nexus.png

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#33101]
I checked out the https://github.com/elastic/docs/ repo at `../docs` (relative to my ES root checkout) and tried to build the reference manual with

    ../docs/build_docs.pl --doc docs/reference/index.asciidoc --chunk 1 --out ~/temp/asciidoc/ --open

This failed as follows:

```
Building HTML from docs/reference/index.asciidoc

Error executing: a2x -v --icons -d book -f chunked -a showcomments=1 -a lang=en -a base_edit_url= -a root_dir=/Users/davidturner/src/elasticsearch-master/docs/reference --xsl-file resources/website_chunked.xsl --asciidoc-opts -fresources/es-asciidoc.conf --destination-dir=/Users/davidturner/temp/asciidoc --xsltproc-opts --stringparam toc.max.depth '5' --xsltproc-opts --stringparam toc.section.depth '1' --xsltproc-opts --stringparam chunk.section.depth '1' --xsltproc-opts --stringparam local.book.version 'test build' --xsltproc-opts --stringparam local.book.multi_version '0' --xsltproc-opts --stringparam local.page.header '' --xsltproc-opts --stringparam local.book.section.title 'Learn/Docs/' --xsltproc-opts --stringparam local.book.subject '' --xsltproc-opts --stringparam local.noindex '' /Users/davidturner/src/elasticsearch-master/docs/reference/index.asciidoc







---
a2x: ERROR: missing resource: /Users/davidturner/src/elasticsearch-master/docs/reference/security/images/nexus.png
```

Looking at the actual docs I think the image in question is [here](https://github.com/elastic/elasticsearch/blob/d5ebcd97675ea250cc42bec4bf55707fcfb06bcf/x-pack/docs/en/security/images/nexus.png) but the path seems to be wrong.

This was working off of current `master` (d5ebcd97675ea250cc42bec4bf55707fcfb06bcf) and I haven't tried other branches.

**Comment by cbuescher** [comment]
@DaveCTurner I have found I had to add `--resource=x-pack/docs/` for quite a while now, does this help? I think I had a chat about it with docs team at some point, cannot find the exchange though atm.

**Comment by cbuescher** [comment]
Found the exchange I had about this with @lcawl in https://github.com/elastic/docs/pull/372. @DaveCTurner Does this help?

**Comment by lcawl** [comment]
For up-to-date documentation build commands, see https://github.com/elastic/docs/blob/master/doc_build_aliases.sh

**Comment by DaveCTurner** [comment]
Thanks @lcawl, that's exactly what I was looking for.
