### ISSUE TITLE
Watcher: Expose more information when watcherservice reload has happened

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#33129]
Right now, we are essentially blind to get more/verbose information when a reload has happened, how many watches have been reloaded, what was the reason for the reload.

This makes debugging issues very hard, especially when there is someone checking for duplicate watch executions. Is this really a bug, or have shards been moved around and thus a reload was triggered? Sometimes it is hard to tell because one cannot correlate events.

We could either ensure that we have proper log levels for this (without spamming the logfile to hard, but still expose useful information), that we keep the last `n` recordings in the watcher stats per host (this could be implemented via an `EvictingQueue` or that we log those entries into the watch history index/an own dedicated index (just dumping things here, not necessarily good ones, requires further discussion).

**Comment by dakrone** [comment]
This has been open for quite a while, and hasn't had a lot of interest. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
