### ISSUE TITLE
put template mapping without type can throw exception

### ISSUE THREAD

**Issue by pakein** [elastic/elasticsearch#33122]
when put template , use `addMapping(String type, XContentBuilder source)` , source miss type,  document parsed automatic add the type , but not write into meta file, and  the request is success.

when master restart, read mapping from meta file fail.
`
if (mapping.size() == 1) {
                                String mappingType = mapping.keySet().iterator().next();
                                String mappingSource = Strings.toString(XContentFactory.jsonBuilder().map(mapping));

                                if (mappingSource == null) {
                                    // crap, no mapping source, warn?
                                } else {
                                    builder.putMapping(mappingType, mappingSource);
                                }
                            }
`

**Comment by pakein** [comment]
I use 6.3.0， i read the code of 6.4.0, it seems have the same problem

my code， the client api addMapping（type，XContentBuilder ） is confused，it seems XContentBuilder do not need the type
```
XContentBuilder build;
build.startObject()  
// this is not wrap by type
builder.startObject("properties");
........
builder.endObject();
build.endObject();
addMapping（“type”， build) 
```

contains  ***** is my comment 
MetaDataIndexTemplateService.validateAndAddTemplate
 ```
Map<String, Map<String, Object>> mappingsForValidation = new HashMap<>();
            for (Map.Entry<String, String> entry : request.mappings.entrySet()) {
                try {

//************* direct write meta, not check entry.value ********************
                    templateBuilder.putMapping(entry.getKey(), entry.getValue());
                } catch (Exception e) {
                    throw new MapperParsingException("Failed to parse mapping [{}]: {}", e, entry.getKey(), e.getMessage());
                }
                mappingsForValidation.put(entry.getKey(), MapperService.parseMapping(xContentRegistry, entry.getValue()));
            }

//************ call MappingService,  check and add type  see below. *************
dummyIndexService.mapperService().merge(mappingsForValidation, MergeReason.MAPPING_UPDATE, false);
````

MappingService
```
private Tuple<String, Map<String, Object>> extractMapping(String type, Map<String, Object> root) throws MapperParsingException {
        if (root.size() == 0) {
            // if we don't have any keys throw an exception
            throw new MapperParsingException("malformed mapping no root object found");
        }
        String rootName = root.keySet().iterator().next();
        
     // ************* add type, so the request is success, this can throw exception ?? *****************
        Tuple<String, Map<String, Object>> mapping;
        if (type == null || type.equals(rootName)) {
            mapping = new Tuple<>(rootName, (Map<String, Object>) root.get(rootName));
        } else {
            mapping = new Tuple<>(type, root);
        }
        return mapping;
    }

```

when read meta from file , check mapping size == 1, so read meta fail.

```
Map<String, Object> mapping = parser.mapOrdered();
//*****************  mapping size != 1 , there has not type *************
                            if (mapping.size() == 1) {
                                String mappingType = mapping.keySet().iterator().next();
                                String mappingSource = Strings.toString(XContentFactory.jsonBuilder().map(mapping));

                                if (mappingSource == null) {
                                    // crap, no mapping source, warn?
                                } else {
                                    builder.putMapping(mappingType, mappingSource);
                                }
                            }
```

**Comment by javanna** [comment]
hi @pakein , I have a hard time understanding what the problem is. Could you elaborate on what the request that you send looks like, what result you would expect and what is happening instead? I think that would be very helpful to troubleshoot this issue on our end. Thanks!

**Comment by danielmitterdorfer** [comment]
No further feedback received. @pakein if you have the requested 
information please add it in a comment and we can look at re-opening 
this issue.
