### ISSUE TITLE
[DOCS] CONTRIBUTING.md has a typo

### ISSUE THREAD

**Issue by li-boxuan** [elastic/elasticsearch#33169]
In section https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-to-the-elasticsearch-codebase, it seems the position of comma is wrong.

> However, since **Elasticsearch, supports JDK 8** the build supports compiling with JDK 10 and testing on a JDK 8 runtime

should be

> However, since **Elasticsearch supports JDK 8,** the build supports compiling with JDK 10 and testing on a JDK 8 runtime

**Comment by jasontedor** [comment]
Closed by c41c614527c70e54245df848ab17e23359837566.

**Comment by jasontedor** [comment]
Thanks a lot for the report @li-boxuan. I have pushed a correction for this.
