### ISSUE TITLE
fips builds don't pass forbidden api tests

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#33179]
Ever since https://github.com/elastic/elasticsearch/commit/82d10b484a20514e70f6d773544ffea62e57f711 the forbidden API checks have been failing on the fips builds. It isn't clear if this is a problem with the build or it is revealing a real problem with our fips compliance. I'm assigning to @atorok to investigate because he made the commit that broke the builds. If it turns out that this is a problem with our compliance he'll pass it off to someone who knows more about that stuff.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/263/console

**Comment by jkakavas** [comment]
`:x-pack:plugin:security:cli:` is the only module that has a compile and runtime dependency in BouncyCastle ( it was split out of security for that exact reason ). 

We already do not run tests in a FIPS JVM, 
https://github.com/elastic/elasticsearch/blob/71d5c66fd384aaebfb83e0b24920df984eb9f09b/x-pack/plugin/security/cli/build.gradle#L23-L25
so should we also disable forbiddenApi ?

**Comment by atorok** [comment]
Forbidden APIs used to be ran with the JVM running Gradle and I switched to running it with run-time java, which in this case is FIPS. I would like to understand why the forbidden patterns are triggered, maybe we could selectively disable rules instead of disabling it all.
