### ISSUE TITLE
UnboundID SDK catches throwable and rewraps hiding a fatal error

### ISSUE THREAD

**Issue by jaymode** [elastic/elasticsearch#33175]
As with some other libraries used in our codebase, the unboundid ldap sdk catches throwable in places and re-wraps what could be a potentially fatal error in an LDAPException:

https://github.com/pingidentity/ldapsdk/blob/0eac394a077323485b850a90e55f926bc035023f/src/com/unboundid/ldap/sdk/LDAPConnectionPool.java#L1623-L1675

We should raise an issue with the upstream library to ask that they stop catching throwable or at least rethrow properly. In the interim we should use `ExceptionsHelper#maybeError` with these exceptions so that we can properly die if an unrecoverable error is being hidden.

**Comment by jasontedor** [comment]
😱

**Comment by jaymode** [comment]
I opened https://github.com/pingidentity/ldapsdk/issues/49 for the library maintainers' consideration; PingIdentity does not accept third party contributions for the ldapsdk so this is not something we could submit a patch for.

**Comment by jaymode** [comment]
This has been addressed in the upstream library by commit https://github.com/pingidentity/ldapsdk/commit/9b012d25b8555a5eddb6fd47aafe6b931abe8fe6. We'll still want a stop-gap until a version with said commit is released and we upgrade to it.
