### ISSUE TITLE
Checking the existence of the index by mask.

### ISSUE THREAD

**Issue by greenx** [elastic/elasticsearch#33192]
I tried to check the existence of indexes by mask. 
Elasitsaarch always returns "200".
```
curl -i -X GET 'http://dev-elastic:9200/d2oc-*' -I
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 2
```
```
curl -i -X GET 'http://dev-elastic:9200/_cat/indices' -s |fgrep d2oc; echo $?
1
```
ES 5.6.9

**Comment by markharwood** [comment]
Reproduced in 6.4

**Comment by jasontedor** [comment]
When you issue a wildcard request, there are various flags on the request that control how the wildcard is expanded. The default is strict expand open which means that any concrete indices must exist, wildcards expand to open indices only, and it is allowed that no indices are resolved. This is why `d2oc-*` can expand to no indices. If you don't want this behavior, you need to use different flags: `?allow_no_indices=false`:

```
 $ curl -i -I -XGET "localhost:9200/d2oc-*?allow_no_indices=false&pretty=true"
HTTP/1.1 404 Not Found
content-type: application/json; charset=UTF-8
content-length: 496
```

**Comment by greenx** [comment]
It is clear, but not logical.
And in the docs not a word.
IMHO, then defalult value for this request must "false".
P.S. In the examples "-XGET" superfluous. -I ~= -X HEAD.

**Comment by jasontedor** [comment]
> And in the docs not a word.

We have a page on [API conventions](https://www.elastic.co/guide/en/elasticsearch/reference/6.4/multi-index.html). What the docs do not spell out is the defaults, but in most cases it is the strict expand open that I mentioned (which translates to `allow_no_indices=true` and acts on open indices only.

> IMHO, then defalult value for this request must "false".

I agree, if I could do it over it would be the default. At this point it would be a massive breaking change though.

> P.S. In the examples "-XGET" superfluous. -I ~= -X HEAD.
