### ISSUE TITLE
Scroll by indices mask fails

### ISSUE THREAD

**Issue by sergpsu** [elastic/elasticsearch#33225]
I'm using this scroll API query to search multiple indices:
-XPOST activity_stats*/type1,type2,type3/_search?scroll=1h '--some query data--'
it gives me required amount of records, but following

_search/scroll?scroll=1h&scroll_id=$scrollId

returns 404 error:
array(6) {
        ["type"]=>
        string(25) "index_not_found_exception"
        ["reason"]=>
        string(13) "no such index"
        ["resource.type"]=>
        string(14) "index_or_alias"
        ["resource.id"]=>
        string(11) "bad-request"
        ["index_uuid"]=>
        string(4) "_na_"
        ["index"]=>
        string(11) "bad-request"
      }

Elasticsearch version 5.1.2

**Comment by romseygeek** [comment]
Hi,

I think you need to check that `$scrollId` is being pasted back in correctly - `index_not_found_exception` suggests that elasticsearch can't parse what is being sent back as the scroll_id.

We try to reserve Github issues for feature requests and bug reports, and use https://discuss.elastic.co for usage issues.  I'll close this ticket, but please feel free to open a discussion there instead.

**Comment by sergpsu** [comment]
scrollId is NOT PASTED. Curl syntax is used here just for clarity. Actually it is php script, and yes i'm sure scroll id is POSTED back correctly
