### ISSUE TITLE
Live API for Elasticsearch

### ISSUE THREAD

**Issue by iahmad-khan** [elastic/elasticsearch#33244]
**Describe the feature**:

Is there any Live API available with installation ( live documentation for REST requests that gets installed with local cluster so that users can don't have to copy paste and search things on internet ) ? There is Dev Tools but it doesnt provide live API. It will make things super easy if there is a live API gets installed with elasticsearch and is available as new tab in kibana where users select pre-formatted queries and can just plug in values and run those queries. Users should also be able to tag some of them as favourts ( or the system should keep the frequently used operations on the top  ).

**Proposal:**

 - Implementing it as a plugin
 - something like this   : `/bin/plugin-install elastic-live` 

Thanks

**Comment by jasontedor** [comment]
Please forgive my ignorance, but what is a live API? I followed the link to YouTube and I'm sorry to say that I do not have the time to watch a thirty minute video in the hopes to find out. A quick explanation here would help us address your request more adequately and quickly.

**Comment by iahmad-khan** [comment]
Hi,

A live API is a web UI to all the POST and GET requests to the REST interface supported by the service. In this case  the users just click a partcular GET or POST , it shows the short info about what it does , the parameters it takes , the possible response codes and an option to try it out where user plugin the values if needed and click execute , under the hood it makes the query and posts it to the RESt service. 

Screen shots attached from the Diocker UCP live API. 

![screenshot from 2018-08-30 11-20-39](https://user-images.githubusercontent.com/13478264/44846132-70355900-ac47-11e8-9d81-39ae8a4448b5.png)
![screenshot from 2018-08-30 11-14-33](https://user-images.githubusercontent.com/13478264/44846133-70355900-ac47-11e8-882f-666e802624e5.png)
![screenshot from 2018-08-30 11-14-04](https://user-images.githubusercontent.com/13478264/44846134-70355900-ac47-11e8-9233-4cd7db78e887.png)
![screenshot from 2018-08-30 11-13-48](https://user-images.githubusercontent.com/13478264/44846135-70355900-ac47-11e8-965a-48b9c3167dad.png)
![screenshot from 2018-08-30 11-13-18](https://user-images.githubusercontent.com/13478264/44846136-70cdef80-ac47-11e8-9f1e-fcc296807fd5.png)

**Comment by jasontedor** [comment]
> A live API is a web UI to all the POST and GET requests to the REST interface supported by the service. 

Elasticsearch does not offer a web UI. Within our stack, we have Kibana for this kind of functionality on top of Elasticsearch. I would encourage you to pursue whether or not a feature request like this makes sense via the Kibana repository.
