### ISSUE TITLE
SQL: Refactoring/Removing Unsupported type

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#33246]
Currently SQL supports a subset of the core ES types, throwing an exception when handling a field with a different type (considered unsupported).
This might be improved by having a more lenient approach for unsupported types; by checking their aggregatable and searchable capabilities, SQL can decide if and how it can use them.
It might not be exact about their type but it can fall back to treating them as generic strings.

Related to #31837 #32499

**Comment by wchaparro** [comment]
Closing as not planned, superceded by our work in ES|QL. Please reopen if you have concerns.
