### ISSUE TITLE
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Limit of total fields [1000] in index [pv3] has been exceeded')

### ISSUE THREAD

**Issue by NikitaDuggal** [elastic/elasticsearch#33269]
I am indexing around 80000 documents  with 2 GB of data size from mongodb to elastic search index using Python. After indexing 16000 documents i receive this error. 
 Note : I have been using elasticsearch locally on my computer and not cloud.

Can you please let me know what exactly can be the issue and how can it be resolved?

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
