### ISSUE TITLE
How to apply aggregations to collapsed/grouped results?

### ISSUE THREAD

**Issue by TheoVitkovskiy** [elastic/elasticsearch#33266]
In the documentation for field collapsing it states: The collapsing is applied to the top hits only and does not affect aggregations.

My question:

Is there a way to apply aggregations to collapsed/grouped results? I just want the numbers next to the different item attributes reflect the results the user sees on the page.

**Comment by romseygeek** [comment]
You should be able to get what you need by using a top_hits aggregation - see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-top-hits-aggregation.html#_field_collapse_example

This appears to be a user question, and we'd like to direct these kinds of things to the forums. If you can ask further questions there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the forums that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by pumpadump** [comment]
@TheoVitkovskiy were you able to find a solution to your problem? We have the same issue.

@romseygeek It is possible to emulate the collapse feature with a top_hits aggregation but I don't understand how you could apply new Aggregations to the set of documents that are made up by the top hit of each group. Is it even possible? @TheoVitkovskiy didn't receive any help in the forums: https://discuss.elastic.co/t/how-to-apply-aggregations-to-collapsed-grouped-results/146673

With top_hits you can apply aggregations to each group but not to the total set of groups considering only the top hit in each group, at least I didn't figure out a way to do this yet.

**Comment by jengel3** [comment]
@pumpadump Any chance you've found a solution yourself? Dealing with the same issue.

**Comment by pumpadump** [comment]
@jengel3 I got in contact with the original author, He didn't find a solution, I asked @spinscale an Elasticsearch expert at the find meetup in Munich he told me it's not possible. 

What you can do is get the total hits count after grouping through a cardinality aggregation on the collapse field and basically use it as an upper bound and approximate normalization factor for the other aggregation counts in your middleware.

Something like:
Math.Min(cardinality count, ((original agg value) * (cardinality count / total count))

The results will be wrong, but if your aggregation buckets are evenly distributed over your search results the error might not be noticeable.

We will probably display both counts, the total count before field collapsing and the cardinality count (after field collapsing) to the user. So, you will see "found x products from y articles in total". And make it clear that the aggregation counts relate to the total article count and not the products count.

**Comment by pumpadump** [comment]
@jengel3 @TheoVitkovskiy 
We actually found a better solution. It has the drawback that it works only on single shard indexes but for most e-commerce use-cases that should be ok. You can use the diversified_sampler aggregation. Here is an example that calculates the counts after field collapsing with the diversified_sampler aggregation on the kibana ecommerce example index:
```JSON
GET kibana_sample_data_ecommerce/_search
{
  "query": {
    "term": {
      "products.manufacturer.keyword": {
        "value": "Elitelligence"
      }
    }
  },
  "collapse": {
    "field": "customer_id"
  },
  "aggs": {
    "my_unbiased_sample": {
      "diversified_sampler": {
       "shard_size":20000,
        "field": "customer_id"
      },
      "aggs": {
        "type_count": {
          "terms": {
            "field": "products.manufacturer.keyword"
          }
        }
      }
    }
  }
}
```
I'm not sure how much memory is consumed if you have to set the shard_size to very high values to calculate accurate results, so keep an eye on that.
