### ISSUE TITLE
ILM: fix `after` rendering to xcontent

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#33282]
we currently ignore the TimeValue string representation and use our own that forces it to be represented in seconds. This is not user friendly, since our time-scale is often way beyond seconds.

The offending code: https://github.com/elastic/elasticsearch/blob/ba8d4eba8b227a153550ce5a2c30f83a1f5ca1f8/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/indexlifecycle/Phase.java#L131

**Comment by colings86** [comment]
I'll have a PR up for this shortly

**Comment by colings86** [comment]
@bmcconaghy This should be fixed shortly in https://github.com/elastic/elasticsearch/pull/33304

**Comment by colings86** [comment]
This was fixed in #33304
