### ISSUE TITLE
SQL: Replace Scroll with search_after

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#33287]
SQL currently uses scroll API for queries which works but requires state on the server.
An alternative to it is using search_after, which is stateless the downside being it's a live cursor any updates to the data will be picked up, which can affect ordering.

Considering in 7.x there are more improvements scheduled for this area, to give it more of a snapshot approach, plus aligning the composite and querying behavior point to doing the migration in the 6.x line.

**Comment by costin** [comment]
For `search_after` to work reliably, queries would need to be sorted and have a tie breaker (which is problematic since doc ids are not part of doc values).

**Comment by Luegg** [comment]
Given https://github.com/elastic/elasticsearch/pull/83381 and https://github.com/elastic/elasticsearch/pull/84605/ switched the scroll based pagination to PIT + `search_after`, this issue can probably be closed @costin ?

**Comment by wchaparro** [comment]
superceded by ES|QL
