### ISSUE TITLE
SQL: SYS TABLES adjustments for ODBC: enumeration of catalogs and table types

### ISSUE THREAD

**Issue by bpintea** [elastic/elasticsearch#33312]
**Elasticsearch version**: master @ 014b277

ODBC's API allows enumerating a data source's available catalogs, schemas, and table types. This is done through [SQLTables](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqltables-function) function. The function is invoked with different arguments configuration in order to get back the desired set: catalogs only, schemas only or table types only.[*] The ODBC driver translates these parameters into a `SYS TABLES` query and provides the result back to the calling application as is.

In this driver working configuration, in order to comply with ODBC's requirements, the result to `SYS TABLES` would need to be altered as follows:

* catalogs enumeration: `SYS TABLES CATALOG LIKE '%'` would need to return _a list of valid catalogs for the data source. (All columns except the TABLE_CAT column contain NULLs.)_
Currently, this query is treated like a normal query: all ”tables” in all "catalogs" (=1 currently) are returned, with each column being populated with respective data:
```
sql> SYS TABLES CATALOG LIKE '%';
   TABLE_CAT    |  TABLE_SCHEM  |     TABLE_NAME     |  TABLE_TYPE   |    REMARKS    |   TYPE_CAT    |  TYPE_SCHEM   |   TYPE_NAME   |SELF_REFERENCING_COL_NAME|REF_GENERATION
----------------+---------------+--------------------+---------------+---------------+---------------+---------------+---------------+-------------------------+---------------
distribution_run|               |test_alias          |ALIAS          |               |null           |null           |null           |null                     |null
distribution_run|               |test_alias_emp      |ALIAS          |               |null           |null           |null           |null                     |null
distribution_run|               |test_emp            |BASE TABLE     |               |null           |null           |null           |null                     |null
distribution_run|               |test_emp_copy       |BASE TABLE     |               |null           |null           |null           |null                     |null
```
Expected (one row per existing catalog):
```
sql> SYS TABLES CATALOG LIKE '%';
   TABLE_CAT    |  TABLE_SCHEM  |     TABLE_NAME     |  TABLE_TYPE   |    REMARKS    |   TYPE_CAT    |  TYPE_SCHEM   |   TYPE_NAME   |SELF_REFERENCING_COL_NAME|REF_GENERATION
----------------+---------------+--------------------+---------------+---------------+---------------+---------------+---------------+-------------------------+---------------
distribution_run|null           |null                |null           |null           |null           |null           |null           |null                     |null
```

* table types enumeration: `SYS TABLES TYPE '%'` would need to return _a list of valid table types for the data source. (All columns except the TABLE_TYPE column contain NULLs.)_. Note that this would require a list of all table types **supported**, not just only of those present.
Current: same as above.
Expected (one row for each supported table **type**):
```
sql> SYS TABLES TYPE '%';
   TABLE_CAT    |  TABLE_SCHEM  |     TABLE_NAME     |  TABLE_TYPE   |    REMARKS    |   TYPE_CAT    |  TYPE_SCHEM   |   TYPE_NAME   |SELF_REFERENCING_COL_NAME|REF_GENERATION
----------------+---------------+--------------------+---------------+---------------+---------------+---------------+---------------+-------------------------+---------------
null            |null           |null                |ALIAS          |null           |null           |null           |null           |null                     |null
null            |null           |null                |BASE TABLE     |null           |null           |null           |null           |null                     |null
```

* ~schema enumeration~: no support for schema exists currently, but it would require a similar semantic: schema param would be `%`, the others would not be present.

In other respects the current implementation is in line with the standard (i.e. the filtering of rows by given columns as with any table/index).

[*] The exact requirement is in [Comments](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqltables-function?view=sql-server-2017#comments), paragraph starting with `To support enumeration of catalogs, schemas, and table types,`.

**Comment by costin** [comment]
Raised #33364 to address the issues above (the code was in place but the if did not match).
To clarify one behavior - based on the current understand/implementation of the ODBC spec, `SYS TABLES` is equivalent to `SYS TABLES TYPE` and `SYS TABLE TYPE '%'` meaning the possible table types are returned.
This is based on https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/value-list-arguments?view=ssdt-18vs2017 and 
https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqltables-function?view=ssdt-18vs2017#comments

Can you confirm this is correct?

**Comment by bpintea** [comment]
> SYS TABLES is equivalent to SYS TABLES TYPE and SYS TABLE TYPE '%'

I guess there were some typos: SYS TABLE TYPE**S** and SYS TABLE**S** TYPE? 
(I've noticed I did a c&p error in the expected output for the table types my initial post too, showing the wrong query, which I've just corrected.)

In respect to the equivalence, conceptually yes, `SYS TABLES TYPE '%'` is equivalent to `SYS TABLE TYPES` in that an enumeration of supported table types is returned (but ofc, framed as a `SYS TABLES` answer, with all the other columns than `TABLE_TYPE` set to `null`.)
