### ISSUE TITLE
Full Backup API

### ISSUE THREAD

**Issue by iahmad-khan** [elastic/elasticsearch#33311]
**Describe the feature**:

Hi,

Its not practial to manage many snapshots , that grow in number with time , and restoring things is not practial from many snapshots. Can there be a full backup API endpoint please. 

Thanks

**Comment by astefan** [comment]
Hi @iahmad-khan,
What do you mean by "full backup API endpoint"? What should this endpoint handle?

**Comment by iahmad-khan** [comment]
@astefan It should take a complete backup of all the indices/shards and store it in the repo.

**Comment by astefan** [comment]
This is already possible by creating a new repository and snapshotting all the indices. The first snapshot is always a full snapshot, the subsequent ones are incremental.

Previous snapshots can also be deleted. If the number of snapshots grows with time and becomes unmanageable, you can delete older snapshots. I will close this for now, as I don't think having a separate endpoint for a full backup makes sense, given the functionality that's already existent.

**Comment by iahmad-khan** [comment]
But for that we have to manage many repositories , and also manually delete data from those backend repos , becuase deleting snapshot doesnt delete the bucket or sub directories in that. It is extremely painful. Having a separate end point for creating full backup will be more cleaner and avoid the pain of managing multiple repos.
