### ISSUE TITLE
bulk upsert is not working correctly

### ISSUE THREAD

**Issue by skumar4120** [elastic/elasticsearch#33322]
I am doing bulk upsert in the ES index and this is deleting the old document and creating new document for the given record

Function to create bulk update satements:

async function toBulk(data: any, index: string, action: string, body: any) {
    if (index === process.env.ES_INDEX) {
        body.push({
            update: {
                '_index': process.env.ES_INDEX,
                '_type': process.env.ES_TYPE,
                '_id': data.nwVehicleId,
                'retry_on_conflict': 25
            }
        });
    } else {
        body.push({
            update: {
                '_index': process.env.LBES_INDEX,
                '_type': process.env.LBES_TYPE,
                '_id': data.nwLiveblockEventId,
                'retry_on_conflict': 25
            }
        });
    }
    switch (action) {
        case 'update':
            body.push({
                'doc': data,
                'doc_as_upsert': true
            });
            break;
        case 'get_update':
            const lbInfo = await client.get({
                'index': process.env.LBES_INDEX,
                'type': process.env.LBES_TYPE,
                'id': data.nwLiveblockEventId
            });
            body.push({
                'doc': lbInfo._source,
                'doc_as_upsert': true
            });
            log('Merged_ES Live Block event', lbInfo);
            break;
        default:
    }
}

Input record:
"data":{"nwVehicleId":"5C8650DD-8133-4F64-AC57-4ABD21775A05","originVehicleId":"402384270","vin":"3GTP2WE78CG271115","make":"GMC","model":"Sierra 1500","year":2012,"series":"SLT","bodyStyle":"4WD CREW CAB 143.5\"","trim":"","odometer":66456,"odometerUnitOfMeasure":"MI","exteriorColor":"Blue","interiorColor":"Blue","carGroupConfigName":"DLRAVE1- Dealer Avenue 1000 ADESA","originCarGroupConfigId":"886","nwCarGroupConfigId":"","vehicleStatus":"Auction","vehicleSize":"","vehicleType":"Retail","assetType":"Car/Light Truck","cylinders":"8","displacement":5.3,"doors":"4","driveTrain":"4WD","emissionsStandard":"","engineName":"8 CYLINDER FLEX-FUEL","fuelType":"Flex Fuel","headlightType":"","inventoryType":"Retail","roofColor":"","speeds":"","transmission":"Automatic","turbo":0,"truck":"","cylinderType":"","originSellerOrganizationId":"249116","nwSellerOrganizationId":"1E3B71C5-F662-4A20-B107-493E7CF5A7FE","sellerOrganizationName":"PAR NORTH AMERICA","countryName":"United States","sellerModelCode":"TK10543","sellerAuctionAccessId":"5999998","locationCity":"BARNHART","stateAbbreviation":"MO","systemUuid":"6286E116-4D78-4CDF-9CF9-1D118A832036","systemOrigin":"classic","systemWhenCreated":1535744120131,"systemTopic":"nw-inventory-develop","systemTopicKey":"5C8650DD-8133-4F64-AC57-4ABD21775A05","systemEvent":"vehicle_updated_inventory","originTimestamp":1535744114000,"originCreatedBy":"ADAPPL","originModifiedBy":"","viewAccessGroupList":[1,297,296],"isCarGroupRunlistEnabled":false,"isAllowProcessingAuction":true,"isActive":true,"registrationProvince":"","warrantyStartDate":0,"displayEmissionCompliance":false,"msrp":"","epaStickers":"","titleStatus":"","odometerDigits":"6","openRecall":"","sellerVehicleCode":"14295","processingLocation":"ADESA St.Louis","listingCategory":"Enhanced","isDealerblock":false,"isRunlist":false,"isLiveblock":false,"address":"7858 HIGHWAY 61-67","zipcode":"63012","origYear":2012,"origMake":"GMC","origModel":"SIERRA 1500","origExteriorcolor":"BLUE","origInteriorcolor":"BLUE","origOdometer":66456,"origDrivetrain":"4WD","origProcessinglocation":"ADESA St. Louis","origEnginename":"5.3L 8CYL FLEX FUEL CAPAB","bodyType":""}

Output expexted is to do upsert whne the document is present but however the old document is deleted in elasticsearch and new document is created which is not the required functionality.

JSon.stringify version of the bulk upsert statements created for ES indexing:

{"timestamp":"2018-08-31T19:35:23.597Z","lambdaContext":{"functionName":"nwSearch-testdev-putIndex-f3d26e02df","awsRequestId":"ce4adbf0-7770-46dc-bb42-a8a7972f142f"},"service":"nwSearch","severity":"CONSOLE.LOG","message":{"text":"Successfully indexed 2 out of 2 events [{\"update\":{\"_index\":\"nwsearchindex\",\"_type\":\"nwsearchtype\",\"_id\":\"5C8650DD-8133-4F64-AC57-4ABD21775A05\",\"retry_on_conflict\":25}},{\"doc\":{\"nwVehicleId\":\"5C8650DD-8133-4F64-AC57-4ABD21775A05\",\"originVehicleId\":\"402384270\",\"vin\":\"3GTP2WE78CG271115\",\"make\":\"GMC\",\"model\":\"Sierra 1500\",\"year\":2012,\"series\":\"SLT\",\"bodyStyle\":\"4WD CREW CAB 143.5\\\"\",\"trim\":\"\",\"odometer\":66456,\"odometerUnitOfMeasure\":\"MI\",\"exteriorColor\":\"Blue\",\"interiorColor\":\"Blue\",\"carGroupConfigName\":\"DLRAVE1- Dealer Avenue 1000 ADESA\",\"originCarGroupConfigId\":\"886\",\"nwCarGroupConfigId\":\"\",\"vehicleStatus\":\"Auction\",\"vehicleSize\":\"\",\"vehicleType\":\"Retail\",\"assetType\":\"Car/Light Truck\",\"cylinders\":\"8\",\"displacement\":5.3,\"doors\":\"4\",\"driveTrain\":\"4WD\",\"emissionsStandard\":\"\",\"engineName\":\"8 CYLINDER FLEX-FUEL\",\"fuelType\":\"Flex Fuel\",\"headlightType\":\"\",\"inventoryType\":\"Retail\",\"roofColor\":\"\",\"speeds\":\"\",\"transmission\":\"Automatic\",\"turbo\":0,\"truck\":\"\",\"cylinderType\":\"\",\"originSellerOrganizationId\":\"249116\",\"nwSellerOrganizationId\":\"1E3B71C5-F662-4A20-B107-493E7CF5A7FE\",\"sellerOrganizationName\":\"PAR NORTH AMERICA\",\"countryName\":\"United States\",\"sellerModelCode\":\"TK10543\",\"sellerAuctionAccessId\":\"5999998\",\"locationCity\":\"BARNHART\",\"stateAbbreviation\":\"MO\",\"systemUuid\":\"6286E116-4D78-4CDF-9CF9-1D118A832036\",\"systemOrigin\":\"classic\",\"systemWhenCreated\":1535744120131,\"systemTopic\":\"nw-inventory-develop\",\"systemTopicKey\":\"5C8650DD-8133-4F64-AC57-4ABD21775A05\",\"systemEvent\":\"vehicle_updated_inventory\",\"originTimestamp\":1535744114000,\"originCreatedBy\":\"ADAPPL\",\"originModifiedBy\":\"\",\"viewAccessGroupList\":[1,297,296],\"isCarGroupRunlistEnabled\":false,\"isAllowProcessingAuction\":true,\"isActive\":true,\"registrationProvince\":\"\",\"warrantyStartDate\":0,\"displayEmissionCompliance\":false,\"msrp\":\"\",\"epaStickers\":\"\",\"titleStatus\":\"\",\"odometerDigits\":\"6\",\"openRecall\":\"\",\"sellerVehicleCode\":\"14295\",\"processingLocation\":\"ADESA St.Louis\",\"listingCategory\":\"Enhanced\",\"isDealerblock\":false,\"isRunlist\":false,\"isLiveblock\":false,\"address\":\"7858 HIGHWAY 61-67\",\"zipcode\":\"63012\",\"origYear\":2012,\"origMake\":\"GMC\",\"origModel\":\"SIERRA 1500\",\"origExteriorcolor\":\"BLUE\",\"origInteriorcolor\":\"BLUE\",\"origOdometer\":66456,\"origDrivetrain\":\"4WD\",\"origProcessinglocation\":\"ADESA St. Louis\",\"origEnginename\":\"5.3L 8CYL FLEX FUEL CAPAB\",\"bodyType\":\"\"},\"doc_as_upsert\":true},{\"update\":{\"_index\":\"nwsearchindex\",\"_type\":\"nwsearchtype\",\"_id\":\"5C8650DD-8133-4F64-AC57-4ABD21775A05\",\"retry_on_conflict\":25}},{\"doc\":{\"originAuctionId\":\"154062739\",\"nwAuctionId\":\"7655F783-E95F-4ACF-BCF8-F17FA6F1200F\",\"originVehicleId\":\"402384270\",\"nwVehicleId\":\"5C8650DD-8133-4F64-AC57-4ABD21775A05\",\"openTimestamp\":1535744107000,\"auctionStartTime\":1535734800000,\"auctionEndTime\":1536091200000,\"closeTimestamp\":0,\"resolveTime\":1536102000000,\"startPrice\":7500,\"reservePrice\":8500,\"buyNowPrice\":9500,\"bidIncrement\":100,\"iteration\":1,\"systemUuid\":\"60EA5F81-46FC-4690-BA99-5F821F01D925\",\"systemOrigin\":\"classic\",\"systemWhenCreated\":1535744120139,\"systemTopic\":\"nw-auction-develop\",\"systemTopicKey\":\"5C8650DD-8133-4F64-AC57-4ABD21775A05\",\"systemEvent\":\"db_auction_started\",\"originTimestamp\":1535744114000,\"originCreatedBy\":\"ADAPPL\",\"originModifiedBy\":\"529715\",\"viewAccessGroupList\":[1,297,296],\"bidAccessGroupList\":\"1,297,296\",\"bestOfferAccessGroupList\":\"\",\"buyAccessGroupList\":\"1,297,296\",\"buyDisappearLimitType\":\"Fixed Amount\",\"buyDisappearLimit\":0,\"previewStartTime\":0,\"previewType\":\"\",\"isDealerBlockSearchable\":true},\"doc_as_upsert\":true}]"}}

**Comment by danielmitterdorfer** [comment]
Initially I used your source documents which are pretty complex for such a report btw. But it turns out we get the same behavior with a simpler example as well which I'll also use below (tested on a fresh install of Elasticsearch 6.4.1):

```
curl -X POST "localhost:9200/_bulk" -H 'Content-Type: application/json' -d'
{"update":{"_index":"cars","_type":"_doc","_id":"1","retry_on_conflict":25}},
{"doc":{"make":"GMC","model":"Sierra 1500","year":2012},"doc_as_upsert":true},
{"update":{"_index":"cars","_type":"_doc","_id":"1","retry_on_conflict":25}},
{"doc":{"year":2014,"color":"green"},"doc_as_upsert":true}
'
```

We'll create a document in the first bulk item and update a property and also add a new one (`color`) to demonstrate everything is merged.

We get the following response:

```
{
  "took": 1457,
  "errors": false,
  "items": [
    {
      "update": {
        "_index": "cars",
        "_type": "_doc",
        "_id": "1",
        "_version": 1,
        "result": "created",
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 0
        },
        "_seq_no": 0,
        "_primary_term": 1,
        "status": 201
      }
    },
    {
      "update": {
        "_index": "cars",
        "_type": "_doc",
        "_id": "1",
        "_version": 2,
        "result": "updated",
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 0
        },
        "_seq_no": 1,
        "_primary_term": 1,
        "status": 200
      }
    }
  ]
}
```

When we retrieve the document ...

```
curl -X GET "localhost:9200/cars/_doc/1?pretty"
```

... , we get the merged version just as we expect:

```
{
  "_index" : "cars",
  "_type" : "_doc",
  "_id" : "1",
  "_version" : 2,
  "found" : true,
  "_source" : {
    "make" : "GMC",
    "model" : "Sierra 1500",
    "year" : 2014,
    "color" : "green"
  }
}
```
