### ISSUE TITLE
Resize should validate/carryover soft-deletes settings

### ISSUE THREAD

**Issue by dnhatn** [elastic/elasticsearch#33321]
We should carryover and validate the soft-deletes settings when shrinking/splitting an index.

**Comment by jasontedor** [comment]
This *should* be automatic starting in 7.0.0, yet requires manual intervention in the 6.x series. See #30255; in 7.0.0 `copySettings` can not be set to `false`.

**Comment by dnhatn** [comment]
@jasontedor Thanks for the pointer.
