### ISSUE TITLE
Error: failed to compare string that has uppercase letters as value of a field in search query with match.

### ISSUE THREAD

**Issue by GobindaGobinda** [elastic/elasticsearch#33334]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 5.5.0

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system): Ubunutu 16.0

**Description of the problem including expected versus actual behavior**:
I found that when we run the search query for string which has Uppercase and Lowercase characters, it failed to return the correct records. Anyone faced the problem.
So, changing the string to lowercase before search solved the problem for my system. 
Can that be changed in the package, so that its easier for other users.
Spent a long time solve problem caused by this. 

**Steps to reproduce**:
![errorcorrection](https://user-images.githubusercontent.com/20100080/44950797-59495f00-ae1f-11e8-80a5-40dcb5b767a3.png)

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by dnhatn** [comment]
You're using a [term query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html) which finds documents that contain the **exact** term specified in the inverted index.

I am closing this as we use Github for bug reports and feature requests. Please ask questions on https://discuss.elastic.co where we can give you a better support.

**Comment by GobindaGobinda** [comment]
The **exact** value that is stored in field is the word that starts with the uppercase "Gobinda". 
whereas the search term only works with the lowercase not while putting the word with uppercase.

**Comment by dnhatn** [comment]
@GobindaGobinda Which [analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-analyzers.html) do you use?  Let's continue the discussion on https://discuss.elastic.co/ as we use Github for bug reports and feature requests.
