### ISSUE TITLE
[CI] LuceneChangesSnapshotTests#testUpdateAndReadChangesConcurrently fails 

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#33344]
`LuceneChangesSnapshotTests#testUpdateAndReadChangesConcurrently` fails occasionally on master and 6x. I reproduce locally with the following seed (the failure doesn't occur on each run though but I was able to reproduce after a few ones):
```
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+release-tests/1005/console

./gradlew :server:test \
  -Dtests.seed=95ED5AB5FEF63FF6 \
  -Dtests.class=org.elasticsearch.index.engine.LuceneChangesSnapshotTests \
  -Dtests.method="testUpdateAndReadChangesConcurrently" \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=bg \
  -Dtests.timezone=Pacific/Enderbury \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

**Comment by jimczi** [comment]
I muted the test in master and 6.x:
https://github.com/elastic/elasticsearch/commit/2fa75b4438fe33d4e39d5e932e0231f76a4c7514

**Comment by jakelandis** [comment]
Re-opening issue test failed on commit https://github.com/elastic/elasticsearch/commit/43f80fa82b8a69763665bb45744703bd063e2d19 which is after the intended fix on https://github.com/elastic/elasticsearch/commit/1f046617bf8891e194653bd2b46dda0c16a95bc7

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/954/console

```
REPRODUCE WITH: ./gradlew :server:test \
  -Dtests.seed=87DF0F7EA13546C4 \
  -Dtests.class=org.elasticsearch.index.engine.LuceneChangesSnapshotTests \
  -Dtests.method="testUpdateAndReadChangesConcurrently" \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=fi-FI \
  -Dtests.timezone=Europe/Stockholm \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

I have not re-muted the test, but may do so if this appears again.
