### ISSUE TITLE
Can't set action.auto_create_index to any value(too restrictive)

### ISSUE THREAD

**Issue by teuneboon** [elastic/elasticsearch#33369]
**Elasticsearch version**: 6.4.0

**Plugins installed**: []

**JVM version**: OpenJDK 1.8.0_181

**OS version**: Linux 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
When I try to set `action.auto_create_index: false` I get the following error when starting Elasticsearch:

`Caused by: java.lang.IllegalArgumentException: the [action.auto_create_index] setting value [false] is too restrictive. disable [action.auto_create_index] or set it to [.watches, .triggered_watches, .watcher-history-*]`

After trying some different values(`-*` and `+foobar,-*`) I decided to try setting it to exactly what the error message recommended: `action.auto_create_index: watches, .triggered_watches, .watcher-history-*` which is when I got the amazing error:

`Caused by: java.lang.IllegalArgumentException: the [action.auto_create_index] setting value [.watches, .triggered_watches, .watcher-history-*] is too restrictive. disable [action.auto_create_index] or set it to [.watches, .triggered_watches, .watcher-history-*]`

The initial issue still isn't solved(still can't disable automatic index creation), but this seems like a documentation/errormessage bug at the very least.

**Steps to reproduce**:

 1. Install Elasticsearch 6.4.0
 2. Put `action.auto_create_index: false` in elasticsearch.yml
 3. (Re)start Elasticsearch

**Comment by teuneboon** [comment]
Alright thanks, this fixes it.

**Comment by cavalier23** [comment]
> Thanks for raising the issue.
> 
> You need to specify the index patterns without any spaces in between. The following works:
> 
> ```
> action.auto_create_index: ".watches,.triggered_watches,.watcher-history-*"
> ```
> 
> (note how I removed the spaces after each comma).
> 
> I'll create a PR to remove the spaces in the error message so it is copy&pasteable.

that means we can't close action.auto_create_index setting? btw, I just tried this on elasticsearch server version of 7.9.2, still  can't close auto_create_index!
