### ISSUE TITLE
Yaml tests: catch error regex

### ISSUE THREAD

**Issue by delvedor** [elastic/elasticsearch#33383]
Hi everyone!

While writing the integrations tests for [`elasticsearch-js`](https://github.com/elastic/elasticsearch-js), I got an [error failing](https://github.com/elastic/elasticsearch/blob/7f7e8fd733d3f98e7422288099b530610b4c4d1e/rest-api-spec/src/main/resources/rest-api-spec/test/search/115_multiple_field_collapsing.yml#L43-L54), and I’m struggling to understand why.
The test expects me to catch a `/parse_exception/`, but instead, I got a `parsing_exception`.

You can test this by using [this gist](https://gist.github.com/delvedor/486ca8ea1b66739c66139ea4a92ccb17) (JavaScript example), I'm using Elasticsearch `v6.4`.
Following the JSON that I’m getting back:
```json
{  
  "error":{  
    "root_cause":[  
      {  
        "type":"parsing_exception",
        "reason":"Invalid token in the inner collapse",
        "line":1,
        "col":114
      }
    ],
    "type":"x_content_parse_exception",
    "reason":"[1:114] [collapse] failed to parse field [inner_hits]",
    "caused_by":{  
      "type":"x_content_parse_exception",
      "reason":"[1:114] [inner_hits] failed to parse field [collapse]",
      "caused_by":{  
        "type":"parsing_exception",
        "reason":"Invalid token in the inner collapse",
        "line":1,
        "col":114
      }
    }
  },
  "status":400
}
```

What field of the JSON do you expect us to verify?
We can also run the regex against the full JSON string (which should fix the issue), but in this case we will not be able to catch breaking changes in the responses.

cc @elastic/es-clients

**Comment by jasontedor** [comment]
@delvedor Can we close this issue?

**Comment by delvedor** [comment]
@jasontedor yes, I'll update my tests and check the entire response body.
I'll open a separate discussion on how we might want to test specific fields of the JSON :)

Thank you for clarifying!
