### ISSUE TITLE
invalid empty json on 404 INDEX/_doc/ID/_source

### ISSUE THREAD

**Issue by exe-dealer** [elastic/elasticsearch#33384]
GET /existing-index/_doc/notexisting-id/_source
returns empty body when document is not found. 
Empty string is invalid json but content-type of response is `application/json; charset=UTF-8`
it whould be better if response body will be `null` to make json parser happy

**Comment by exe-dealer** [comment]
elasticsearch version 6.4

**Comment by original-brownbear** [comment]
@jasontedor marked this as "discuss", but I think this should be a bug. Empty body is not a valid return for the json content type (even if it's a 404). "null" sounds like a better choice here.

**Comment by danielmitterdorfer** [comment]
We discussed this in the core-infra team meeting and want to do the following:

* If the document is not found, raise a resource not found exception and return this as a proper JSON body
* If source is disabled also raise an exception and return this as a proper JSON body.

**Comment by cbismuth** [comment]
cURL recreation script created in [this Gist](https://gist.github.com/cbismuth/eb1a421bf152c4bc4eb732809436cafc).

**Comment by nik9000** [comment]
> I'd like to have a look at this one.

Enjoy!

**Comment by cbismuth** [comment]
PR is open, see https://github.com/elastic/elasticsearch/pull/34083.

I've built on top of the previous behavior. This means we don't make a difference when source is disabled or document is missing: in both cases a `ResourceNotFoundException` is raised with the same JSON message.
Do you think a difference should be made?
