### ISSUE TITLE
Introduce "good first issue" tags for new contributors

### ISSUE THREAD

**Issue by vignesh380** [elastic/elasticsearch#33385]
I am a new contributor to ElasticSearch but don't know where to start contributing. Would be awesome if the tag "good first issue" was used for new contributors.

**Comment by nik9000** [comment]
We have the `low hanging fruit` label that should be fairly similar. I suppose there is some merit in using the standard name, but we've had this tag for quite a while now so I suspect we'll keep it.

**Comment by nik9000** [comment]
I talked to @rjernst and he agreed with me that we should stick with the label that we already have. I'm going to marks this as a documentation issue and update `CONTRIBUTING.md` to point to the label.

**Comment by nik9000** [comment]
So I ended up building consensus around renaming the tags and finally renamed them a few days ago.
