### ISSUE TITLE
Expose proximity boosting

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#33382]
In addition to static features (ctr, pagerank, url length) it is common to also want to boost by recency or geo-distance, which are going to perform differently on every request depending on the current time or on the location of the user that runs the query.

Lucene just added support for efficient [boosting by recency](https://issues.apache.org/jira/browse/LUCENE-8340) and plans to add something similar for [boosting by geo-distance](https://issues.apache.org/jira/browse/LUCENE-8482).

How should we expose it in Elasticsearch?

Relates #27588
cc @polyfractal @mayya-sharipova

**Comment by mayya-sharipova** [comment]
@jpountz   Thanks for developing this query. `LongPoint.newDistanceFeatureQuery` seems to useful indeed. It looks to be similar to decay functions in Function Score query, but seems to be computed much more efficiently.  Is the plan for this query to support  only saturation function? 

About exposing I think it is good to have this query by itself on long fields, but also I am wondering if we can take advantage of it in function score query/

**Comment by jpountz** [comment]
>  Is the plan for this query to support only saturation function?

For now yes since this is the only function that was proposed in "Relevance weighting for query independent evidence" that allowed to incorporate features that are inversely correlated with the score (the longer the distance, the lower score contribution).

**Comment by jpountz** [comment]
We discussed in the search/aggs meeting. We are also in the process of replacing function_score with a scripting context that would make applying decays easy. We still think it would be nice to have both since they have different trade-offs: scripts would be more flexible but slower since they can't skip non-competitive hits like these new queries can.

One open question left is whether we should have 1 or 3 different queries to handle boosting numbers, dates and geo-points. The main issue is that these queries take a pivot distance as a parameter that would be a number for numeric fields, a duration for date fields and a geo distance for geo-point fields.
