### ISSUE TITLE
Monitoring: node is not displayed although shards are moving

### ISSUE THREAD

**Issue by dadoonet** [elastic/elasticsearch#33417]
**Elasticsearch version** (`bin/elasticsearch --version`):

This is a bug I have seen for a long time now (so not a new thing). But tested on latest 6.4.0.

**JVM version** (`java -version`):

```
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

Also happening with other Java versions like Java8.

**OS version** (`uname -a` if on a Unix-like system):

```
Darwin macbook-pro-david.home 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

**Description of the problem including expected versus actual behavior**:

I'm running a demo which consist of:

1) start a local single node
2) index 1 million documents (5 shards / 1 replica)
3) start a new node and wait for all replicas being allocated (check Monitoring UI)
4) start a new node and check Monitoring UI (refresh rate is 5s)

You can look at [this video](https://www.dropbox.com/s/2ht9kbmu4u0nj5w/bug-missing-node-when-moving-shards.mov?dl=0).

At 1:08 you can see the second node coming and primaires being replicated: correct
At 2:19 all shards are started.
At 2:30 I'm starting the third node.
At 3:10 you can see all shards have disappeared
At 3:15 you can see that all shards are back but 2 shards are being relocated although we can't see yet the 3rd node.
![image](https://user-images.githubusercontent.com/274222/45088152-6f4d6d00-b108-11e8-9e0c-521f944dcc6f.png)

At 3:41 the 3rd node is showing up and everything is fine from that point.

This is not a bug in the way elasticsearch behaves because everything is running very well but just a bug in the way monitoring data is collected I guess.

**Comment by jasontedor** [comment]
> This is not a bug in the way elasticsearch behaves because everything is running very well but just a bug in the way monitoring data is collected I guess.

Maybe you're right, but why are we guessing? Since this is manifesting as a UI issue, would you please start the investigation there?
