### ISSUE TITLE
[Painless] Augmentation.join can't handle empty strings at the start

### ISSUE THREAD

**Issue by fredgalvao** [elastic/elasticsearch#33434]
**Elasticsearch version** (`bin/elasticsearch --version`):

6.3.1

The issue is not exclusive to the mentioned version, as the code is faulty on master too.

Source links relevant:
https://github.com/elastic/elasticsearch/blob/v6.3.1/modules/lang-painless/src/main/java/org/elasticsearch/painless/api/Augmentation.java#L174
https://github.com/elastic/elasticsearch/blob/master/modules/lang-painless/src/main/java/org/elasticsearch/painless/api/Augmentation.java#L174

**Plugins installed**:

`[]` (none)

**JVM version** (`java -version`):

zulu 1.8.0_172 build of java8

**OS version** (`uname -a` if on a Unix-like system):

`3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux`
But this has been tested on Debian, Ubuntu, CentOS, and other Redhat machines.

**Description of the problem including expected versus actual behavior**:

The `join` method for `Iterable`s provided by the `Augmentation` class for Painless can't deal with iterables containing zero-length members at the head of the iterable.
This script: `"script": "['', 0, '', 1, null, 3, ''].join(';')"` should output
`";0;;1;null;3;"`
But it outputs
`"0;;1;null;3;"`

The empty string on the start is appended to the StringBuilder, but the second pass will see it as `sb.length() == 0` still, and then will continue without a separator until it finds a non-zero-length member.

As counter-examples of why it should be different, the following cases output the expected one:
- In groovy: `['', 0, '', 1, null, 3, ''].join(';')`
- In java8: `String.join(";", Arrays.asList("", "0", "", "1", "null", "3", ""))`
- In java8: `Stream.of("", "0", "", "1", "null", "3", "").collect(Collectors.joining(";"))`
- In javascript: `['', 0, '', 1, null, 3, ''].join(';')`

**Steps to reproduce**:

 1. Pick literally any elasticsearch cluster with N>0 indexes/types
 2. Run the following query:
```json
GET _search
{
  "size": 1,
  "script_fields": {
    "bacon": {
      "script": "['', 0, '', 1, null, 3, ''].join(';')"
    }
  }
}

```
 3. Taste the bacon

**Comment by fredgalvao** [comment]
The following patch, inspired by the [groovy join implementation](https://github.com/groovy/groovy-core/blob/01309f9d4be34ddf93c4a9943b5a97843bff6181/src/main/org/codehaus/groovy/runtime/DefaultGroovyMethods.java#L5960-L5975), fixes the issue.

```patch
      */
     public static <T> String join(Iterable<T> receiver, String separator) {
         StringBuilder sb = new StringBuilder();
+        boolean first = true;
         for (T t : receiver) {
-            if (sb.length() > 0) {
+            if (first) {
+                first = false
+            } else {
                 sb.append(separator);
             }
             sb.append(t);
```

This other patch will add a simple test for it on `AugmentationTests.java`:
```patch
     public void testIterable_Join() {
         assertEquals("test,ing",
                 exec("List l = new ArrayList(); l.add('test'); l.add('ing'); l.join(',')"));
+        assertEquals(";0;;1;null;3;",
+                exec("List l = Arrays.asList(\"\", \"0\", \"\", \"1\", null, \"3\", \"\"); l.join(';')"));
     }
 
     public void testIterable_Sum() {
```

**Comment by seekingshell** [comment]
Working on it!

**Comment by nik9000** [comment]
This looks like my fault. @fredgalvao or @seekingshell, do you want to submit a PR? I'd be happy to merge it.

**Comment by seekingshell** [comment]
@nik9000 Up to you! I'm new to contributing to open source, this was the first project I picked. Unfortunately having some issues with the build environment. @fredgalvao I had a question about your suggested fix. Would this only exclude the first empty string and is it worth considering the edge case of more than one empty string at the head of the list?

**Comment by fredgalvao** [comment]
@nik9000 I actually started that route, but the all-so-needed steps for me to be able to officialy submit a PR made my availability go down to "just paste the patch". I would be able to do it, but it'd take a few days for me to find the time.

@seekingshell Not really, no. That flag is for the first (`index==0`) because the presence of `N>1` elements is the only criteria to determine the presence of `N-1` separators. So, for every element after the first, there will be a separator, **regardless of it's length**.

You can test it here: http://tpcg.io/N8PwIX
