### ISSUE TITLE
GetRequest can not get a document when "id" contains a special character

### ISSUE THREAD

**Issue by casper1149** [elastic/elasticsearch#33445]
Hello,

Elasticsearch version: 6.4.0

JVM version: 1.8.0

OS version: MacOSX 17.6.0 Darwin Kernel

I have an index with the next mapping
```
{
  "_doc": {
    "properties": {
      "id": {
        "type": "keyword"
      }
    }
  }
}
```

and next setting
```
"analysis": {
    "analyzer": {
        "default": {
            "tokenizer": "keyword"
        }
     }
}
```

I indexed a simple document using the IndexRequest API, where the "id" value contains a special character "+", so the result document looks like this
```
{
  "_index": "index_v1",
  "_type": "_doc",
  "_id": "my-id.1+8",
  "_source": {
    "id": "my-id.1+8",
  }
}
```

As expected I am not able to GET this document without encoding the "+" character
```
GET index_v1/_doc/my-id.1+8
```

But I am able to GET it using an encoded "+" character
```
GET index_v1/_doc/my-id.1%2B8
```

and to make sure I tested it with a simple HTTP GET request
```
curl http://host:port/index_v1/_doc/my-id.1%2B8
```

also it is possible to SEARCH for this document using the value as it is, i.e.
```
GET index_v1/_search
{
  "query": {
    "term": {
      "id": {
        "value": "my-id.1+8"
      }
    }
  }
}
```

However when I try to use the GetRequest API, the document is not found
```
GetRequest getRequest = new GetRequest("index_v1").id("my-id.1%2B8").type("_doc");
GetResponse response = client.get(getRequest, RequestOptions.DEFAULT);
```

If I print the "getRequest" it looks correct
```
get [index_v1][_doc][my-id.1%2B8]: routing [null]
```

The "response" also looks correct, however the document was not found
```
{"_index":"index_v1","_type":"_doc","_id":"my-id.1%2B8","found":false}
```

So I was expecting to be able to get the same result using the GetRequest API as I am getting when I GET this document manually.

Can you please take a look and explain whether it is a bug or an expected behavior, or may be I am just missing something?

**Comment by casper1149** [comment]
I also tried to get the same document using the low level client and it worked
```
Request request = new Request("GET", "http://host:port/index_v1/_doc/my-id.1%2B8");
Response response = client.getLowLevelClient().performRequest(request);
```

**Comment by jasontedor** [comment]
The REST layer does decoding of `+` into space and decoding of percent-encoded characters that the transport layer does not. The issue of `+` being decoded into a space is one fraught with some history. See [the discussion](
https://github.com/elastic/elasticsearch/pull/33164#discussion_r212973677) on #33164 for some recent history on this. We have a [proposal](
https://github.com/elastic/elasticsearch/pull/33164#pullrequestreview-149934785) that we modify this behavior in a future release, your feedback there is certainty welcome. Does that help? I think then that we can close this issue? 🤔

**Comment by casper1149** [comment]
Thanks for the info, in this case I'll be using the low level client to perform this operation until this gets resolved in the future release
