### ISSUE TITLE
Effect of role_mapping.yml breaks with upgrade to ES >= 6.3

### ISSUE THREAD

**Issue by fkelbert** [elastic/elasticsearch#33464]
We just spent a significant amount of time figuring out why Active Directory / LDAP stops working after upgrading from ES 5.6 to ES 6.4.

The reason is:
- in ES 6.2 (with x-pack), the default path for role_mapping.yml is ES_PATH_CONF/x-pack/role_mapping.yml (see https://www.elastic.co/guide/en/elasticsearch/reference/6.2/security-settings.html)
- in ES 6.3 (no x-pack), the default path for role_mapping.yml is ES_PATH_CONF/role_mapping.yml (see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html)

We did not find any explicit documentation of this change, even though it did actually break functionality.
In particular, also the Interactive Upgrade Guide should highlight these and similar required changes.

**Comment by lcawl** [comment]
@fkelbert and @jaymode If there are specific error messages that appear in this problem scenario, please let me know and I'll include them in the troubleshooting information.

**Comment by fkelbert** [comment]
@lcawl I remember that the config file was just silently ignored. There was no error message. That is why it took as quite a while to actually figure out what the problem was.

**Comment by lcawl** [comment]
Thanks @fkelbert I've updated https://github.com/elastic/stack-docs/pull/122 and https://github.com/elastic/elasticsearch/pull/33541

**Comment by jaymode** [comment]
This is fixed by #33688
