### ISSUE TITLE
Elasticsearch-test fails on a host where InetAddress.getLocalHost() throws an exception

### ISSUE THREAD

**Issue by vmassol** [elastic/elasticsearch#33470]
On XWiki we're using elastic-search 1.2.1 like this:

```
EsSetup esSetup = new EsSetup();
```

When our test executes on some of our Jenkins agents we get a NPE. We analyzed the problem and it's coming from LocalClientProvider which calls NetworkUtils.getLocalAddress() which in turns is calling InetAddress.getLocalHost(). In this case NetworkUtils stores a NULL localAddress, which makes NetworkUtils.getLocalAddress().getHostName() throw the NPE in:

```
    protected Settings buildNodeSettings() {
        // Build settings
        ImmutableSettings.Builder builder = ImmutableSettings.settingsBuilder()
                .put("node.name", "node-test-" + System.currentTimeMillis())
                .put("node.data", true)
                .put("cluster.name", "cluster-test-" + NetworkUtils.getLocalAddress().getHostName())
...
```

Since the local address seems to be used only as the test name of the cluster, it would be nice to use a different name that is not subject to variations/limitations, i.e. that doesn't depend on some environment setup.

Thanks!

**Comment by vmassol** [comment]
See also https://jira.xwiki.org/browse/XWIKI-15577

**Comment by tlrx** [comment]
elastisearch-test is not maintained anymore (thanks for using it! :) and this repository is for elastisearch bug only, so I'm going to close it.

We don't have much documentation around integration tests but you can still have a look at https://www.elastic.co/guide/en/elasticsearch/reference/current/integration-tests.html and also the various test classes in the elasticsearch codebase.
