### ISSUE TITLE
HEAD / don't close response

### ISSUE THREAD

**Issue by Wing924** [elastic/elasticsearch#33490]
**Elasticsearch version** (`bin/elasticsearch --version`):
6.4.0 (rpm version)
**Plugins installed**: []
none
**JVM version** (`java -version`):
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
**OS version** (`uname -a` if on a Unix-like system):
Linux myhostname 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
**Description of the problem including expected versus actual behavior**:
`HEAD /` returns `200 OK`, not connection never be closed.
**Steps to reproduce**:
```bash
$ curl -vs -XHEAD http://localhost:9200
* About to connect() to localhost port 9200 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9200 (#0)
> HEAD / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9200
> Accept: */*
>
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 511
<

# hang up here
```

**Provide logs (if relevant)**:

**Comment by danielmitterdorfer** [comment]
Thanks for your report. However, the problem here is curl. You need to use `--head` instad of `-XHEAD` to get `curl` to behave properly. To quote the man page:

> This  option  only  changes  the  actual  word  used in the HTTP
> request, it does not alter the way curl behaves. So for  example
> if  you  want  to make a proper HEAD request, using -X HEAD will
> not suffice. You need to use the -I, --head option.

See also https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/ for further info.

**Comment by Wing924** [comment]
@danielmitterdorfer Thank you.
