### ISSUE TITLE
Issues with Arrays with a mixture of datatypes

### ISSUE THREAD

**Issue by aniude** [elastic/elasticsearch#33495]
I read the office document about it .https://www.elastic.co/guide/en/elasticsearch/reference/6.2/array.html. 

Till now still no any plan to support it?

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

The reason mixed data types in arrays are not supported has to do with the fact how those are represented under the hood and there are no intentions to change this in the foreseeable future.
