### ISSUE TITLE
Protection against too many deprecation warnings

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#33508]
As highlighted in #33479, triggering too many deprecation warnings may have bad consequences with proxies. While this particular issue could be fixed easily by checking all fields up-front in order to trigger only one deprecation warning per request rather than one per field per request, it would be nice to have better protection against this in practice, so that we won't break users if we ever make a similar mistake again.

One solution that was proposed was to limit the number of deprecation warnings to some configurable limit, which some of us were not happy with due to the fact that it would silently ignore some warnings. As a consequence a second proposal was made so that if the limit is N then we only emit N-1 deprecation warnings and reserve the last one to add a new warning that would say that due to the high number of deprecation warnings, some of them were ignored.

**Comment by jpountz** [comment]
We like the idea of using one warning to say something like "X warnings have been ignored because they would make the number or size of warning headers exceed the configured limit". Now the question is: if we have a limit of 10 warnings, should we have 9 actual warnings plus this one, or 10 actual warnings plus this one? We didn't have enough time to reach consensus on that one. Opinions?

**Comment by tomcallahan** [comment]
Removing the discuss label as we've previously agreed to iron out the rest of this discussion on the issue here.

**Comment by dvisztempacct** [comment]
Here is a reproduction in case it is useful. I was filing an issue accidentally against `elasticsearch-js` when I realized my mistake and came here to find this issue.

https://gist.github.com/dvisztempacct/54a4d208903ea9eb84b44b9a6a1cb7fe

It breaks not only the Node.js HTTP response header decoder but also the one in Wireshark.

**Comment by gwbrown** [comment]
There is still an open question from [this comment](https://github.com/elastic/elasticsearch/issues/33508#issuecomment-423556169):
> if we have a limit of 10 warnings, should we have 9 actual warnings plus this one, or 10 actual warnings plus this one?

However, this is broadly something we would like to do and tweaking the exact behavior will be trivial. We can move ahead with an implementation whenever someone has time to implement this.

**Comment by abprash** [comment]
Hi  @jpountz, @gwbrown , i was thinking of looking into this. I'm a beginner, wanted to know how to go about reproducing & where i can start from.

**Comment by nasserabd** [comment]
Hey @jpountz @gwbrown, I was wondering if this issue is still available and I am able to look into it? I am a beginner and looking to make some contributions

**Comment by mosche** [comment]
Is this still relevant? Are `http.max_warning_header_count` and `http.max_warning_header_size` not sufficient?
On the other hand, by means of above, the request headers won't contain any warning that additional warnings (e.g. deprecations) got dropped, this will only be visible in logs.

**Comment by mosche** [comment]
We discussed this in our team sync and currently don't see a need for this. There's settings available to limit the number of headers returned.

> On the other hand, by means of above, the request headers won't contain any warning that additional warnings (e.g. deprecations) got dropped, this will only be visible in logs.

Additionally, deprecation warnings are indexed and won't be lost, even if warning headers get truncated.
But we're happy to be convinced otherwise.
