### ISSUE TITLE
Elastic Search Snapshot to Azure Blob is failing with storageexception

### ISSUE THREAD

**Issue by vijayaramb** [elastic/elasticsearch#33502]
I have been using this for more than 1 year, suddently today I am getting the below error while doing snapshot in kibana dev console

Error:
IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: IOException; nested: StorageException[The value for one of the HTTP headers is not in the correct format.];

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch. Unfortunately, as it is written now, this issue is not actionable for us.

Can you please provide the following information?

```
**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
```

**Comment by andyb-elastic** [comment]
I'm going to close this because we haven't received any feedback
