### ISSUE TITLE
ILM: Ensure phase credentials are preserved across master failover

### ISSUE THREAD

**Issue by talevy** [elastic/elasticsearch#33535]
It can be the case that a policy is updated by a user with different credentials from the original one currently being executed. Currently, the previous policy's phase would be executed with the new policy's credentials.

This task is to cache the credentials along the phase execution info so that a new master can pick up with the appropriate credentials.

This task should also add an integration test to verify

**Comment by dakrone** [comment]
As we discussed, we don't need to do this, so I'm going to close this for now.

**Comment by talevy** [comment]
One thing I would add is that closing this doesn't mean it is a no-op. The revised change is to not cache credentials at all, even in-memory for the currently executed phase. Instead, we will rebuild the client for every iteration of execution with the latest version of the policy's credentials
