### ISSUE TITLE
Logging: unconfigured_node_name.NodeNameInLogsIT fails on OSes that can't instal seccomp

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#33540]
We don't have the node name when we try to install seccomp. If we can't install all of the seccomp filters we log a warning. If the node name isn't in elasticsearch.yml then we'll log `unknown` as the node name which fails this test. I'll implement a work around soon but for now I'll disable the test so it doesn't fail the build over and over again.

**Comment by nik9000** [comment]
> I'll implement a work around soon but for now I'll disable the test so it doesn't fail the build over and over again.

I figured out a fairly ok work around: skip the test if we're running on a platform that doesn't support the syscall filters we try to install. This is fairly safe because for the most part we run our tests on platforms where we *can* install the filter.

**Comment by jasontedor** [comment]
@nik9000 I have not look at the hostname solution yet, but I am wondering if this can be reversed when that work goes in? It's an open question for you when you have time to revisit this.

**Comment by nik9000** [comment]
I do reverse it when I switch to the hostname.
