### ISSUE TITLE
Index can get stuck closed if any of its shards has half or less of its lucene indexes running

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#3354]
You can wedge an index in the closed state by closing it when any one of its shards has half or less of its lucene indexes running.  I'm not sure if they just have to be open or if they have to be up to date.  Here is the gist:  https://gist.github.com/nik9000/6030428

**Comment by ywelsch** [comment]
#15708 makes `index.recovery.initial_shards` obsolete. This means that a single shard is only needed to successfully reopen index. #15708 is for v3.0.0 though. Can we close this @clintongormley @bleskes?

**Comment by bleskes** [comment]
+1 to closing this.

**Comment by nik9000** [comment]
This was either my first or second interaction with the ES team on github, btw.

**Comment by clintongormley** [comment]
w00t
