### ISSUE TITLE
ForecastIT testDelete failed

### ISSUE THREAD

**Issue by droberts195** [elastic/elasticsearch#33561]
This happened in 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=sles/2661/consoleText

The REPRO line is this, although since it's timing-related it won't reproduce reliably:

```
./gradlew :x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner \
  -Dtests.seed=C417041F0B398073 \
  -Dtests.class=org.elasticsearch.xpack.ml.integration.ForecastIT \
  -Dtests.method="testDelete" \
  -Dtests.security.manager=true \
  -Dtests.locale=ja-JP \
  -Dtests.timezone=Asia/Tbilisi \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

I think the problem is that we're not refreshing the index after deleting the forecast documents, yet the test is assuming that all documents will be unsearchable when the delete call returns.  I think it's good that the contract of the delete forecast endpoint is that you will not find documents related to the forecast if you search for them after the endpoint returns.  So that means we need to refresh the index in the delete forecast code.  The simplest way should be to add `setRefresh(true)` to the DBQ request, similar to https://github.com/elastic/elasticsearch/blob/284c45a6ffb1a4eb2ce7498db25d362cae2c0c02/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/job/persistence/JobStorageDeletionTask.java#L103

**Comment by droberts195** [comment]
Please could you have a look at this when you're back from X-School @benwtrent?

**Comment by benwtrent** [comment]
I have not been able to reproduce :(. I have added the refresh to the delete by query command. I will open a PR and see what our build does, but I am 100% it will fix it. 

Any ideas on how to reproduce it more reliably @droberts195 ?

**Comment by droberts195** [comment]
> Any ideas on how to reproduce it more reliably

The only way is to run many times on different hardware that might have different timing characteristics.

I'm pretty sure #33647 will help.  Let's get that merged and then close this issue.  Whoever is on test triage can reopen this issue if the problem recurs after #33647 is merged.

**Comment by benwtrent** [comment]
Potentially fixed this issue through: https://github.com/elastic/elasticsearch/pull/33647
🤞
