### ISSUE TITLE
The enabled setting is not updatable (and probably shouldn't)

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#33566]
[According to the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/enabled.html) , the `enabled` setting for mappings should be updatable (see TIP at the end), which it actually isn't:

```
PUT my_index 
{
  "mappings": {
    "doc": { 
      "properties": {
        "bla": {
          "properties": {
            "title":    { "type": "text"  }
          }
        }
      }
    }
  }
}

GET /my_index/_mapping/doc

PUT /my_index/_mapping/doc
{
  "properties": {
    "bla": {
      "enabled" : false
    }
  }
}

GET /my_index/_mapping/doc
```

-> returns same initial mapping :sadtrombone:

While implementing a fix, I noticed that we probably do not want to change and fix this, as this might lead to a surprising effects if the setting is changed during indexing (A field might be indexed on the primary but not on the replica (or vice versa)). Similarly, it might interfere in funny ways with reindexing.

I suggest updating the docs to say that this field is non-updateable, but wanted to raise it first for discussion with @elastic/es-search-aggs.

**Comment by colings86** [comment]
Additionally we should probably fail the request to update the mappings in this case too!

**Comment by jpountz** [comment]
+1 to disallow updating this field

Relates to #28070

**Comment by jpountz** [comment]
We discussed this issue and agreed to disallow updates to the `enabled` property via mapping updates both ways (false -> true and true -> false). Such mapping updates should raise an error and we should fix our docs.

**Comment by cbismuth** [comment]
I'll have a look on this one.

**Comment by cbismuth** [comment]
Here is a complete cURL recreation script in [this Gist](https://gist.github.com/cbismuth/07a80dadbc2e651feb8a57259afcda25).

I'm now debugging to see how `o.e.r.a.a.i.RestPutMappingAction` is implemented.

**Comment by cbismuth** [comment]
I looks like an exception should be raised in the conditional block below.

https://github.com/elastic/elasticsearch/blob/15ff3da653c5dd9eae7f7a654a9ee6a931d478b7/server/src/main/java/org/elasticsearch/index/mapper/ObjectMapper.java#L257

**Comment by ywelsch** [comment]
> Sorry @ywelsch, I missed the line where you were saying you has already started to work on this. Feel free to let me know what you want to do.

The "fix" I was working on was to allow dynamically changing "enable", until I noticed that this is not what we want. I have not done any subsequent work on this, so you are free to proceed on this.

**Comment by cbismuth** [comment]
I've opened a PR, could please tell me if this design could fit?

If you agree on this, I'll then implement test cases and check for existing test failures.

**Comment by BMomani** [comment]
what is the current status of this 
the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/enabled.html) say 
The enabled setting can be updated on existing fields using the PUT mapping API.
is that correct or not?

**Comment by javanna** [comment]
@BMomani the docs you linked are for 6.5. We have updated more recent docs to reflect code changes, see #https://github.com/elastic/elasticsearch/pull/43701 . It is correct that you cannot update the `enabled` flag.
