### ISSUE TITLE
Unable to fetch the data with help of QueryBuilders.termQuery

### ISSUE THREAD

**Issue by sparun160782** [elastic/elasticsearch#33574]
Hi All

I am a newcomer to elastic search I was trying to work with high-level Rest Client

I am able to work with CRUD operations, With Search functionality, I got stuck up.

My objective to bring all the data based on the book id start with E106 search criteria

http://localhost:5918/book-elastic/books/book/E106

I added the part of the code below

I am able to get all the data using

QueryBuilders.matchAllQuery()

But I couldn't get a specific field value

QueryBuilders.termQuery("_id",bookId)

I have also shared the screenshot of the both results

Can somebody help me out on the query?

for more information with code and screenshot shared in stack-overflow

https://stackoverflow.com/questions/52245298/unable-to-fetch-the-data-with-help-of-querybuilders-termquery

Kindly revert in case of any further information needed.

Thanks in Advance

**Comment by colings86** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.

**Comment by sparun160782** [comment]
Thanks for the direction

**Comment by sparun160782** [comment]
Thanks for your direction But still no one answered my query

**Comment by colings86** [comment]
The discuss forum is a community forum and questions do not always get and immediate response. We ask that people are patient when asking questions on the forum. For more information on what you can expect when interacting with the Elastic community please see the [Code of Conduct](https://www.elastic.co/community/codeofconduct).
