### ISSUE TITLE
DiskThresholdDecider#canAllocate can report negative free bytes

### ISSUE THREAD

**Issue by jimczi** [elastic/elasticsearch#33596]
The allocation decider computes the free bytes available on the node as the number of bytes available on disk minus the size of the relocating shards. This value is then used to decide whether or not a shard can be allocated on the node and reported as a ByteSizeValue. However it is not allowed to create a ByteSizeValue from a negative value on master (deprecated in 6x) which seems to be the case if the size of the relocating shards is greater than the number of bytes available on the machine.
This issue was reported by a user on 6x that is seeing deprecation warning on allocations:
````
[2018-08-27T04:28:58,902][WARN ][o.e.c.r.a.d.DiskThresholdDecider] [ip-host_name_3] after allocating, node [nslg_UChT3CH9NLfN0SoYg] would have less than the required 0b free bytes threshold (-2629423012 bytes free), preventing allocation
````

**Comment by bleskes** [comment]
@vladimirdolzhenko do you mind taking a look?
