### ISSUE TITLE
Do not check self references in metric agg per document

### ISSUE THREAD

**Issue by jonaslan** [elastic/elasticsearch#33593]
#31044 introduced ensureNoSelfReference on the _agg object in scripted metric aggregations. 
It would be nice if there was a switch to disable the it. Upgrading to 6.4 caused something around 20x performance degradation for us. And downgrading was no fun.

**Comment by jpountz** [comment]
I agree #31044 was not good, it should not check for self references in the aggregation state after every collected document, only once all documents are collected.

**Comment by rjernst** [comment]
We discussed in FixItThursday and believe Adrien's idea should work. @polyfractal suggested doing this check in a post collection hook. I'm marking this as adoptme and updating the title accordingly.

**Comment by cbismuth** [comment]
I'm having a look at this one.

**Comment by cbismuth** [comment]
I've opened PR https://github.com/elastic/elasticsearch/pull/34001, could you please have a look on it? Thank you.

**Comment by cbismuth** [comment]
I think we can close this one as #34001 has been merged.

**Comment by polyfractal** [comment]
Ah yep, you're right.  Thanks for the ping, and the PR fix @cbismuth! :)

**Comment by cbismuth** [comment]
You're welcome :wink:
