### ISSUE TITLE
Should we use a higher order than 0 for most internal index templates

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#33595]
The internal index templates for ml, monitoring, watcher, kibana etc. (all except the security templates) have an order of `0`. This means that all other index templates will override them. Overriding the internal templates can be useful for customising the number of replicas or the shard allocation filtering but in other cases users would like to be sure that this internal templates will have precedence. 

Maybe we should set the internal templates to have an order which is something like `1000` so users can choose whether they want their templates to take precedence or not when combined with the internal templates.

NoteL: This may be less relevant depending on what we decide with the discussion around https://github.com/elastic/elasticsearch/issues/21105

**Comment by tomcallahan** [comment]
Stalled on elastic/elasticsearch#21105

**Comment by dakrone** [comment]
I believe this is a not necessary as we're moving to composable index templates where our internal templates will only match a single template.
