### ISSUE TITLE
On Debian, installing java and elasticsearch in the same apt-get run fails

### ISSUE THREAD

**Issue by sanvila** [elastic/elasticsearch#33607]
I'm using Debian 9 and elasticsearch 6.4.0. In a freshly installed Debian system I do this:

`apt-get install elasticsearch openjdk-8-jre-headless`

and it fails with this error:

```
dpkg: error processing archive /var/cache/apt/archives/elasticsearch_6.4.0_all.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/elasticsearch_6.4.0_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
This happens because the preinst (not the postinst) checks that java is in the PATH, and it fails if it's not, but java will not be in the PATH until we let the openjdk-8-jre-headless package to be configured, since the /usr/bin/java executable is handled via the alternatives mechanism.

I could of course install java first and then elasticsearch, in separate apt-get runs, but that would be only a workaround and not a real and elegant solution.

It would be better to tell dpkg that the java package should be configured first, and this already happens when a simple Depends is used.

`Depends: openjdk-8-jre-headless | every-other-package-providing-java-8`

Then the current stuff in the preinst could be moved to postinst again, where it probably belongs.

BTW: The current Depends field is not very orthodox:

`Depends: bash, libc6, adduser, coreutils`

Both bash and coreutils are essential, so they don't need to be there.

The dependency on libc6 is also suspicious because normally they are versioned and created automatically by dpkg-shlibdeps, and this one seems to be added by hand. If the package does not contain any ELF binary, there is no need to add a dependency on libc6.

Thanks.

**Comment by jasontedor** [comment]
Thanks for the well-written summary, and sorry for the trouble. This is effectively covered under #31845, work that we plan to do. As such, I hope you do not mind at all that I close this.

cc @dliappis for more background on #31845.
