### ISSUE TITLE
[CI] NamedDateTimeProcessorTests fails

### ISSUE THREAD

**Issue by vladimirdolzhenko** [elastic/elasticsearch#33621]
Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java10,nodes=virtual&&linux/297/console

Quite well reproduced locally with
```
./gradlew :x-pack:plugin:sql:test -Dtests.seed=8648CDF8F6D4BBCC -Dtests.class=org.elasticsearch.xpack.sql.expression.function.scalar.datetime.NamedDateTimeProcessorTests -Dtests.method="testValidMonthNamesInUTC" -Dtests.security.manager=true -Dtests.locale=fr-ML -Dtests.timezone=America/Asuncion -Dcompiler.java=11 -Druntime.java=10
```

```
05:45:03 FAILURE 0.01s J1 | NamedDateTimeProcessorTests.testValidMonthNamesInUTC <<< FAILURES!
05:45:03    > Throwable #1: org.junit.ComparisonFailure: expected:<Jan[uary]> but was:<Jan[]>
05:45:03    > 	at __randomizedtesting.SeedInfo.seed([8648CDF8F6D4BBCC:5B6DAFD26B51202D]:0)
05:45:03    > 	at org.elasticsearch.xpack.sql.expression.function.scalar.datetime.NamedDateTimeProcessorTests.testValidMonthNamesInUTC(NamedDateTimeProcessorTests.java:67)
05:45:03    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:45:03    > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05:45:03    > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:45:03    > 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
05:45:03    > 	at java.base/java.lang.Thread.run(Thread.java:844)
```

Relates to #33411

**Comment by astefan** [comment]
After digging into this one, this is specific to Java 9+. The change that makes the day names be returned in narrow format (as opposed to FULL) is documented [here](http://www.oracle.com/technetwork/java/javase/9-relnote-issues-3704069.html#JDK-8008577).

**Comment by astefan** [comment]
ES is already using `-Djava.locale.providers=COMPAT` but the testing infra doesn't pass this one to the forked jvm for the test.

**Comment by DaveCTurner** [comment]
I marked these tests as @AwaitsFix in master in 44a80d61b287b48e4e2a5782bfdb008d552858aa.

**Comment by DaveCTurner** [comment]
Bah, @vladimirdolzhenko already did so in cfc20825ab8dea80d2e9dd3b5ff04a151602d8c1, but I didn't realise. Reverted in 94f6d4560df.

**Comment by cbuescher** [comment]
These tests were not muted on 6.x and continued failing, I pushed an @Awaitsfix with 68aff719454ffb385e9ae3c09fcfe77ef3d4d0f2
