### ISSUE TITLE
Update-By-Query can index into another index with the right pipeline

### ISSUE THREAD

**Issue by spinscale** [elastic/elasticsearch#33628]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.0

**Description of the problem including expected versus actual behavior**:

When modifying the `_index` metadata in a pipeline, you can use update by query to accidentally index into another index - if and only if the version of the two affected documents across indices is exactly the same.

**Steps to reproduce**:

```
DELETE foo,other

PUT foo/doc/1?refresh=true
{
  "key" : "value"
}

PUT other/doc/1?refresh=true
{
  "key" : "OTHER"
}


PUT _ingest/pipeline/my-index-id
{
  "description": "describe pipeline",
  "processors": [
    {
      "script": {
        "source": "ctx._index = 'other'"
      }
    }
  ]
}

POST foo/doc/_update_by_query?pipeline=my-index-id

# the document is there with key == value
GET other/doc/1

# now increase the version of one of those documents by modifying
PUT other/doc/1
{ "key" : "modified" }

# this will fail with a version conflict exception
POST foo/doc/_update_by_query?pipeline=my-index-id
```

I am not too sure if there is anything that we want to do about this as people have picked a pipeline that is not suitable for update by query.

**Comment by dakrone** [comment]
Related to #41618

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
