### ISSUE TITLE
RestHighLevelClient should implement type-less APIs

### ISSUE THREAD

**Issue by jpountz** [elastic/elasticsearch#33625]
The high-level REST client should support the following type-less APIs:
 - [ ] index creation
 - [ ] put mapping
 - [ ] get mapping
 - [ ] index
 - [ ] update
 - [ ] get
 - [ ] delete

Sub tasks of #15613 and #27205

**Comment by jtibshirani** [comment]
I'm closing this in favor of #35190, our main tracking issue for types deprecation. We've been updating the HLRC as part of the same PRs where we deprecate each API.
