### ISSUE TITLE
java rest client is slow

### ISSUE THREAD

**Issue by ouyangchucai** [elastic/elasticsearch#33637]
When I use java rest client for search，the return json shows Elasticsearch server took only 14ms，but the java code execute time is 665ms. It cost about 509ms to create rest client, and the get request cost 149ms. 
When I use curl request Elasticsearch rest URL, it shows cost 25ms.
`time curl -XGET 'http://localhost:9200/fulltext001/_search?_source=id&sort=id&size=10000&q=content:%22KTV%22' > es_result.txt`
How can I make the java search code faster? 

search code:
import org.apache.http.HttpEntity;
import org.apache.http.HttpHost;
import org.apache.http.auth.AuthScope;
import org.apache.http.auth.UsernamePasswordCredentials;
import org.apache.http.client.CredentialsProvider;
import org.apache.http.entity.ContentType;
import org.apache.http.impl.client.BasicCredentialsProvider;
import org.apache.http.impl.client.SystemDefaultCredentialsProvider;
import org.apache.http.impl.nio.client.HttpAsyncClientBuilder;
import org.apache.http.nio.entity.NStringEntity;
import org.apache.http.util.EntityUtils;
import org.elasticsearch.client.Response;
import org.elasticsearch.client.RestClient;
import org.elasticsearch.client.RestClientBuilder;
import org.elasticsearch.client.transport.TransportClient;
import org.elasticsearch.client.*;

import java.io.IOException;
import java.util.Collections;
public class RestClientTest {
    public  static void main(String[]args){
        long startTime = System.currentTimeMillis();
        String host = "127.0.0.1";
        int port = 9200; 
        String username="elastic";
        String password="changeme";

        final CredentialsProvider credentialsProvider = new BasicCredentialsProvider();
        credentialsProvider.setCredentials(AuthScope.ANY,
                new UsernamePasswordCredentials(username, password));

        long clientStartTime = System.currentTimeMillis();
        RestClient restClient = RestClient.builder(new HttpHost(host, port))
                .setHttpClientConfigCallback(new RestClientBuilder.HttpClientConfigCallback() {
                    public HttpAsyncClientBuilder customizeHttpClient(HttpAsyncClientBuilder httpClientBuilder) {
                        return httpClientBuilder.setDefaultCredentialsProvider(credentialsProvider);
                    }
                }).build();

        long clientEndTime = System.currentTimeMillis();

        long indexStartTime = 0;
        long indexEndTime = 0;
        long searchStartTime = 0;
        long searchEndTime = 0;
        long startReponseTime =0;
        long endReponseTime = 0;
        try {

            //index a document
            /*
            HttpEntity entity = new NStringEntity("{\n\"id\" : \"https://www.huxiu.com/article/215169.html\"\n, \n\"content\" : \"“娃娃机，迷你KTV，VR体验馆，堪称商场三大标配‘神器’。”一家地处商业中心的大型综合体负责人告诉懂懂笔记，在过去的这几个月里，几乎所有的综合体都“标配”了这三种“设备”…\"\n}", ContentType.APPLICATION_JSON);
            indexStartTime = System.currentTimeMillis();
            Response indexResponse = restClient.performRequest("PUT", "/fulltext001/doc/123", Collections.<String, String>emptyMap(), entity);
            indexEndTime = System.currentTimeMillis();
            */

            //search a document
            searchStartTime = System.currentTimeMillis();
            //Response response = restClient.performRequest("GET", "/fulltext001/doc/123", Collections.singletonMap("pretty", "true"));
            Response response = restClient.performRequest("GET", "/fulltext001/doc/_search?_source=id&sort=id&size=10000&q=content:KTV", Collections.singletonMap("pretty", "true"));

            searchEndTime = System.currentTimeMillis();

            startReponseTime = System.currentTimeMillis();
            System.out.println(EntityUtils.toString(response.getEntity()));
            endReponseTime = System.currentTimeMillis();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {

        }

        long endTime = System.currentTimeMillis();
        System.out.println("total cost time:"+(endTime-startTime)/1000.0+"s, client create time:"+(clientEndTime-clientStartTime)/1000.0+"s, index time:"+(indexEndTime-indexStartTime)/1000.0+"s, search time:"+(searchEndTime-searchStartTime)/1000.0+"s, response to string time:"+(endReponseTime-startReponseTime)/1000.0+"s");
        //total cost time:0.665s, client create time:0.509s, index time:0.0s, search time:0.149s, response to string time:0.001s.  Elasticsearch took 14ms.
        //total cost time:0.714s, client create time:0.553s, index time:0.0s, search time:0.152s, response to string time:0.001s. Elasticsearch took 37ms.

    }
}

return elasticsearch search result json:
{
  "took" : 14,
  "timed_out" : false,
  "_shards" : {
    "total" : 27,
    "successful" : 27,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : null,
    "hits" : [
      {
        "_index" : "fulltext001",
        "_type" : "doc",
        "_id" : "123",
        "_score" : null,
        "_source" : {
          "id" : "https://www.huxiu.com/article/215169.html"
        },
        "sort" : [
          "https://www.huxiu.com/article/215169.html"
        ]
      },
      {
        "_index" : "fulltext001",
        "_type" : "doc",
        "_id" : "1",
        "_score" : null,
        "_source" : {
          "id" : "https://www.huxiu.com/article/215169.html"
        },
        "sort" : [
          "https://www.huxiu.com/article/215169.html"
        ]
      }
    ]
  }
}

#create index
curl -XPUT http://localhost:9200/fulltext001?pretty -H 'Content-Type: application/json'   -d ' 
{
    "settings" : {
      "index" : {
        "number_of_shards" : "27",
        "number_of_replicas" : "0"
      }
    }
}
'

#create mapping
curl -XPOST http://localhost:9200/fulltext001/doc/_mapping?pretty  -H 'Content-Type: application/json' -d ' 
{
    "doc" : {
        "_all" : {
	  "enabled" : false
	},
        "properties" : {
          "content" : {
            "type" : "text",
            "analyzer":"cjk"
          },
          "id" : {
            "type" : "keyword"
          }
        }
    }
}
'

#index demo
curl -XPUT 'http://localhost:9200/fulltext001/doc/1?pretty' -H 'Content-Type: application/json' -d '
{
    "id": "https://www.huxiu.com/article/215169.html",
    "content": "“娃娃机，迷你KTV，VR体验馆，堪称商场三大标配‘神器’。”一家地处商业中心的大型综合体负责人告诉懂懂笔记，在过去的这几个月里，几乎所有的综合体都“标配”了这三种“设备”…"
}'

curl -XPUT 'http://localhost:9200/fulltext001/doc/2?pretty' -H 'Content-Type: application/json' -d '
{
    "id": "https://www.huxiu.com/article/217588.html",
    "content": "虎嗅注：本文转载自微信公众号“PingWest品玩”（wepingwest），作者：范俊杰。  趣店集团成立于2014年3月。近日据外媒报道，趣店计划于美国东部时间10月18日（万圣节前夕）在纽约证券交易所挂牌上市，预计融资7.69亿美元。…"
}'

curl -XPUT 'http://localhost:9200/fulltext001/doc/3?pretty' -H 'Content-Type: application/json' -d '
{
    "id": "https://www.huxiu.com/article/222027.html",
    "content": "趣分期和分期乐曾经是校园贷领域的两大明星公司，之后二者都进行了品牌升级，成为如今的趣店和乐信，也都表示退出校园贷领域。如今二者又延续了相同的步调，继趣店在美上市后，乐信也在美发布招股书，计划在美上市。虽然两家公司经常被作为对标公司，但从目前的业务状况看，二者还是有比较大的差异。…"
}'

curl -XPUT 'http://localhost:9200/fulltext001/doc/4?pretty' -H 'Content-Type: application/json' -d '
{
    "id": "https://www.huxiu.com/article/239920.html",
    "content": "虎嗅注：昨日（4月13日），虎嗅 “2018 WOW! 新媒体营销分享会” 在北京召开，luckin coffee作为咖啡新零售品牌，准备凭借其优选的产品原料、精湛的咖啡工艺，创新的商业模式和领先的移动互联网技术来改变咖啡行业。…"
}'

curl -XPUT 'http://localhost:9200/fulltext001/doc/5?pretty' -H 'Content-Type: application/json' -d '
{
    "id": "https://www.huxiu.com/article/204310.html",
    "content": "虎嗅注：无人便利店突然成为创投圈的新风口。  然而，它究竟是否真的那么具有“颠覆性”？而这种与消费者自身关系并不紧密的人工成本节省是否真的有意义？本文对上述疑问一一进行了探讨。  本文首发自微信公众号快刀三侠（ID：iyqkpd），虎嗅获授权转载。  盛夏，资本市场的升温速度令人咋舌。  7月1日，F5未来商店完成3000万元A+轮融资；7月3日，缤果盒子完成超1亿元A轮融资；短短一周，融资便超过1.3亿元。  紧接着，7月8日，阿里巴巴无人超市“淘咖啡”正式亮相杭州。…"
}'

#search demo
time curl -XGET 'http://localhost:9200/fulltext001/_search?_source=id&sort=id&size=10000&q=content:%22KTV%22' > es_result.txt

**Comment by danielmitterdorfer** [comment]
Thank you for your interest in Elasticsearch. 

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.

Nevertheless, I want to provide a few hints here already. I think there are several problems with your benchmark and the methodology you use to measure response times, the most apparent ones being:

* No warmup (either on client-side and probably also not on client-side)
* Only measuring a single iteration
* Not using a monotonic clock (i.e. `System.nanoTime()`)

We have also client-side benchmarking code in our repository at https://github.com/elastic/elasticsearch/tree/master/client/benchmark which you can look at as an inspiration for your own benchmarks.

To improve your benchmarking methodology you can read https://www.elastic.co/blog/seven-tips-for-better-elasticsearch-benchmarks. Although the blog post is written for server-side benchmarks, a lot of these tips apply to client-side benchmarks as well.

Finally, to identify where time is spent you should attach a Java profiler such as Yourkit or Java flight recorder to your application. This helps you to see how long it takes to execute different parts of the code.
