### ISSUE TITLE
limit field name length

### ISSUE THREAD

**Issue by hub-cap** [elastic/elasticsearch#33651]
Adding a soft limit to the field name length in case users need to limit the number of characters in a field's name.

**Comment by MarianaFerrDias** [comment]
Hi! Can I take care of this issue?

**Comment by mayya-sharipova** [comment]
@MarianaFerrDias Yes, please do.  This issue is still open and your help is very much welcome!

**Comment by diogopontual** [comment]
Hello Mr. @hub-cap, where the "soft limit" should be created?

**Comment by alex101101** [comment]
Hi,

I am interested in looking into this issue.

I have already raised a Pull Request. Could someone please review it if they have time?

Thanks,
Alex
