### ISSUE TITLE
unexpected aggregation result

### ISSUE THREAD

**Issue by liorg2** [elastic/elasticsearch#33659]
I'm using aws elasticsearch service

Elasticsearch version 5.3

can anybody please check this question?
https://discuss.elastic.co/t/unclear-aggregation-results-version-5-3/148346

**Comment by colings86** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to keep these kinds 
of things to the [forums](https://discuss.elastic.co/). I see there is some 
discussion already happening there so I hope you don't mind if we keep 
this discussion on that thread. This allows us to use GitHub for verified bug 
reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.

**Comment by liorg2** [comment]
hi, I actually think it's a bug in elasticsaech
