### ISSUE TITLE
[CI] GlobalCheckpointListenersTests.testFailingListenerAfterTimeout fails

### ISSUE THREAD

**Issue by vladimirdolzhenko** [elastic/elasticsearch#33665]
Logs:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/7031/console

It is hardly to catch due to the raise condition nature:

[GlobalCheckpointListeners.java:144](https://github.com/elastic/elasticsearch/blob/9b8fe85edb81378f16d3f0819b4f5604bad7e7cf/server/src/main/java/org/elasticsearch/index/shard/GlobalCheckpointListeners.java#L144)
```
final TimeoutException e = new TimeoutException(timeout.getStringRep());
logger.trace("global checkpoint listener timed out", e);
```

is invoked always and countDownLatch in test could already pass further in the main thread while executor still did not handled exception

Refers to https://github.com/elastic/elasticsearch/pull/33620

**Comment by jasontedor** [comment]
Closed by d806a0e59d1cf0730c5f089b551385f667bad26e
