### ISSUE TITLE
SetupPasswordTool should parse the ports file

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#33666]
Currently the `SetupPasswordTool` parses the `elasticsearch.yml`
config file while trying to build the URL to connect to the
local node on the REST interface.

This is suboptimal because the bound addresses is generated
by consulting the discovery plugins. It is unwieldy (if possible at all)
to start a `Node` instance, inside the command line tool, to resolve
the published address inside the tool too.

A starting node has the option to write the bound address, after it has
been resolved by the discovery plugins, in a [ports file](https://github.com/elastic/elasticsearch/blob/a69ae6b89f0560b2dfc97e86eebd1268e945e2b9/server/src/main/java/org/elasticsearch/node/Node.java#L770) . Implicitly, this is not written.

I think the node should default to writing the ports file, the command line
tool should parse the file, and if it is missing and the `--url` option is also
missing, then the tool should gracefully fail.

Closes: https://github.com/elastic/elasticsearch/issues/33580

**Comment by tvernum** [comment]
As much as I like to provide a good user experience, I feel this would introduce too much overhead just so the user doesn't need to pass `--url`.
Maybe we just need to handle these sorts of errors more cleanly and point users to the `--url` option.

**Comment by jasontedor** [comment]
This setting is undocumented because it is for testing only and I am not sure if we should expose it. It becomes yet another piece of functionality to support and the story here is not compelling enough to me.

**Comment by tvernum** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/pull/40151
