### ISSUE TITLE
Rework AckIT tests

### ISSUE THREAD

**Issue by ywelsch** [elastic/elasticsearch#33673]
#30672 fixed the acking mechanism in Elasticsearch, which would previously just erroneously report failures as successful acks. The `AckIT` tests that accompanied the acking implementation are unfortunately fundamentally broken and would have never worked if the acking implementation had not been broken since its inception. The reason that the acking cannot work in this class is that it uses a publish timeout of 0, which can result in cluster states to arrive out-of-order on nodes, which can in certain situations lead to cluster states being rejected as a better cluster state was already fully applied on the node. One way to work around the limitations in the test here might be to bring the cluster to a stable state first, and only then change the publish timeout for the one publishing round we want to check the acking for.

The AckIT tests have been disabled as part of #32767 and should be reworked / possibly replaced by a new set of tests.

**Comment by imotov** [comment]
As per discussion with @ywelsch in #34053 I have disabled `AckClusterUpdateSettingsIT` in master as well. I am going to close #34053 in favor of this issue.

**Comment by DaveCTurner** [comment]
See also https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=opensuse/58/console

**Comment by tlrx** [comment]
I have disabled `AckClusterUpdateSettingsIT` in 6.x and closed #37478 in favor of this issue.

**Comment by ywelsch** [comment]
These tests have been removed and replaced with others as part of the Zen2 work.
