### ISSUE TITLE
JdbcSqlSpecIT testUcaseInline1/testUcaseInline3 failing

### ISSUE THREAD

**Issue by hub-cap** [elastic/elasticsearch#33687]
Reproduce line. Seen on 2 builds today.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/7034
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/7032

```
./gradlew :x-pack:qa:sql:security:ssl:integTestRunner \                                                                           src/elasticsearch (master ⚡) localhost
  -Dtests.seed=B72DBE4A4ACBC832 \
  -Dtests.class=org.elasticsearch.xpack.qa.sql.security.JdbcSqlSpecIT \
  -Dtests.method="test {string-functions.testUcaseInline1}" \
  -Dtests.security.manager=true \
  -Dtests.locale=tr-TR \
  -Dtests.timezone=GMT \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

**Comment by astefan** [comment]
Yep, it's about the Turkish locale (and another one). We ignore the locale, but the DB we use for testing this in parallel with, doesn't. And comparing the two results, it will obviously fail. These tests need to be moved to a different file which will not do the parallel comparison with H2 (the other DB we test with).

**Comment by hub-cap** [comment]
Muted in https://github.com/elastic/elasticsearch/commit/7dd22f09dcebb44da6e9f6aa22bdd2f7ceb78c9a

**Comment by imotov** [comment]
Failed in 6.x https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=centos/1290/console
I muted it in 6.x branch as well.

**Comment by astefan** [comment]
Fixed.
7.0: https://github.com/elastic/elasticsearch/commit/0d4683850c069d973050880f63970c7fa57b72af
6x: https://github.com/elastic/elasticsearch/commit/393b7b09af69b43e6f387f89514284c89293c990
