### ISSUE TITLE
role_mapping.yml breaks with upgrade to ES >= 6.3

### ISSUE THREAD

**Issue by fkelbert** [elastic/elasticsearch#33680]
We just spent a significant amount of time figuring out why Active Directory / LDAP stops working after upgrading from ES 5.6 to ES 6.4.

The reason is: 
- in ES 6.2 (with x-pack), the default path for role_mapping.yml is ES_PATH_CONF/x-pack/role_mapping.yml (see https://www.elastic.co/guide/en/elasticsearch/reference/6.2/security-settings.html)
- in ES 6.3 (no x-pack), the default path for role_mapping.yml is ES_PATH_CONF/role_mapping.yml (see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html)

We did not find any explicit documentation of this change, even though it did actually break functionality.
In particular, also the Interactive Upgrade Guide should highlight these and similar required changes.

**Comment by jkakavas** [comment]
Hi

Isn't this a duplicate of https://github.com/elastic/elasticsearch/issues/33464 ? Any reason for opening a second one ?
