### ISSUE TITLE
elasticsearch节点数据盘数量不一致导致数据分布问题

### ISSUE THREAD

**Issue by caipengtao** [elastic/elasticsearch#33695]
你好，我的elasticsearch集群有20个节点，其中19个节点，每个节点有3块数据盘，磁盘使用量在60%左右，剩下的一个节点有1块数据盘，然后发现这个节点磁盘使用量将近90%，请问如何解决类似的问题？

**Comment by imotov** [comment]
Please, ask this question in https://discuss.elastic.co/c/in-your-native-tongue/chinese We use github for bug reports and feature requests.

**Comment by caipengtao** [comment]
ok，thx
