### ISSUE TITLE
How do you get rid of the piled "number_of_pending_tasks"

### ISSUE THREAD

**Issue by chinesepython** [elastic/elasticsearch#33705]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by romseygeek** [comment]
Thank you for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds
of things to the forums at https://discuss.elastic.co/c/elasticsearch  - if you can stop
by there, we'd appreciate it. This allows us to use GitHub for verified
bug reports, feature requests, and pull requests.

There's an active community in the forums
that should be able to help get an answer to your question. As such, I
hope you don't mind that I close this.
