### ISSUE TITLE
[re-open 3180] Update ttl after update document 

### ISSUE THREAD

**Issue by max-inetgiant** [elastic/elasticsearch#3371]
https://github.com/elasticsearch/elasticsearch/issues/3180

ok, can you add parameter "autoupdate" : [true|false] for _ttl?

```json
{
  "product": {
    "dynamic": true,
    "_ttl": {
      "autoupdate": true,
      "enabled": true,
      "default": 864000000
    },
    "properties": {
      "title": {
        "type": "string",
        "index": "not_analyzed"
      }
    }
  }
}
```

**Comment by jpountz** [comment]
I don't think we should add more parameters to the update API for something that can be easily addressed from client side. Additionally, `_ttl` already has traps, I'm on the fence about adding even more traps.
