### ISSUE TITLE
Invalid initial heap size 

### ISSUE THREAD

**Issue by Grashee** [elastic/elasticsearch#33714]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.0

**Plugins installed**: [no plugins]

**JVM version** (`java -version`): 1.8.0_171_i586

**OS version** (`uname -a` if on a Unix-like system): CentOS

**Description of the problem including expected versus actual behavior**:
I have increased the RAM of my virtual machine to 11 GB, so I can set the XMS/XMX JVM options to around 5 GB. Actually my elasticsearch installation uses 3GB RAM which works, but when I want to increase the RAM to 4 or 5 GB RAM I got an error that I have set "invalid initial heap size" or "The specified size exceeds the maximum representable size.".

My system definitivly has the RAM free and the VM is correctly configured.

**Steps to reproduce**:

 1. Install elasticsearch (with 3GB RAM heap)
 2. Increase RAM of VM server to 11GB
 3. Increase RAM in the jvm.options of elasticsearch
 4. Run elasticsearch
 5. Look into the logs.

**Provide logs (if relevant)**:

> Sep 13 15:15:08 elk systemd[1]: Started Elasticsearch.
Sep 13 15:15:08 elk systemd[1]: Starting Elasticsearch...
Sep 13 15:15:11 elk elasticsearch[1617]: Invalid initial heap size: -Xms4g
Sep 13 15:15:11 elk elasticsearch[1617]: The specified size exceeds the maximum representable size.
Sep 13 15:15:11 elk elasticsearch[1617]: Error: Could not create the Java Virtual Machine.
Sep 13 15:15:11 elk systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Sep 13 15:15:11 elk systemd[1]: Unit elasticsearch.service entered failed state.
Sep 13 15:15:11 elk systemd[1]: elasticsearch.service failed.

**Discussion at discuss.elastic.co**
https://discuss.elastic.co/t/invalid-initial-heap-size/143248

**Comment by jasontedor** [comment]
>Increase RAM in the jvm.options of elasticsearch

Would you please show *exactly* the change you made, either representing it as a diff against a jvm.options from a fresh install, or showing the full contents of the modified jvm.options file. The former is easier, but either way it’s a lot easier for us to help you if we don’t have to guess the steps involved to reproduced.

**Comment by Grashee** [comment]
This is before I changed the jvm.options (this version works)

> -Xms3G
> -Xmx3G

and this version brings me the error:

> -Xms4G
> -Xmx4G

The rest of the `jvm.options` file is orginal.

**Comment by jasontedor** [comment]
You will need to upgrade to a 64-bit JVM, we do not support 32-bit JVMs (and, of course, you could never have a 4g heap with a 32-bit JVM, this is not an Elasticsearch limitation but a fundamental limitation).

**Comment by Grashee** [comment]
Sometimes it´s the little things. I thought that I´ve installed the 64bit java version,. 
Thanks, I will test it on monday.

Best regards and thanks a lot!
Robert

**Comment by jasontedor** [comment]
Cheers!
