### ISSUE TITLE
Unable to start elastic server, getting following error

### ISSUE THREAD

**Issue by suhas-ingrainhub** [elastic/elasticsearch#33746]
Elasticsearch version: 1.4.4
JVM version:  1.8.0_171
OS version: Ubuntu 16.04LTS (Linux <name> 4.13.0-41-generic #46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)

Issue: Unable to start elastic search.

Commands used:
sudo service elasticsearch stop
sudo service elasticsearch start
sudo service elasticsearch status

● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-09-17 11:20:23 IST; 2s ago
     Docs: http://www.elastic.co
  Process: 32485 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=2)
 Main PID: 32485 (code=exited, status=2)

Sep 17 11:20:23 WFX-SVR-006 systemd[1]: Started Elasticsearch.
Sep 17 11:20:23 WFX-SVR-006 systemd[1]: elasticsearch.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 17 11:20:23 WFX-SVR-006 systemd[1]: elasticsearch.service: Unit entered failed state.
Sep 17 11:20:23 WFX-SVR-006 systemd[1]: elasticsearch.service: Failed with result 'exit-code'.

Note:
  Unable to restart as well since it gives same error when restarted.
Logs:
  Unable to check logs in /var/log/elasticsearch since its "elasticsearch" service itself is not able to start.

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
