### ISSUE TITLE
Elasticsearch dynamic generation summary

### ISSUE THREAD

**Issue by liufan1993** [elastic/elasticsearch#33748]
The project encountered a problem.
 After obtaining the article summary through hanlp, the summary does not need to be highlighted in the search, because the keywords entered by the user are random, so I would like to ask, can es dynamically get the summary?

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
