### ISSUE TITLE
[CI] DateTimeUnitTests.testConversion fails reproducibly for certain seeds

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch#33749]
Build:  https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-windows-compatibility/2/console

Reproduces locally for me with:
```
./gradlew :server:test \
  -Dtests.seed=695728E1EC933467 \
  -Dtests.class=org.elasticsearch.common.rounding.DateTimeUnitTests \
  -Dtests.method="testConversion" \
  -Dtests.security.manager=true \
  -Dtests.locale=ja \
  -Dtests.timezone=Africa/Juba \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

Failure:
```
FAILURE 0.40s | DateTimeUnitTests.testConversion <<< FAILURES!
   > Throwable #1: java.lang.AssertionError:
   > Expected: is <685935125775L>
   >      but: was <685931525775L>
   >    at __randomizedtesting.SeedInfo.seed([695728E1EC933467:6F5FADDBC15C6BF3]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.common.rounding.DateTimeUnitTests.testConversion(DateTimeUnitTests.java:79)
   >    at java.lang.Thread.run(Thread.java:748
```

**Comment by cbuescher** [comment]
A second one here: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=oraclelinux/1/console

**Comment by cbuescher** [comment]
I muted this tests with https://github.com/elastic/elasticsearch/commit/1f2a90cb3937dcc6a6164e24b3a5350d69283f91 on master.

**Comment by original-brownbear** [comment]
This seems to just be a bug in Joda I opened https://github.com/JodaOrg/joda-time/issues/485

**Comment by original-brownbear** [comment]
The issue was fixed in Joda, once a new version is released we can fix this by upgrading.

**Comment by danielmitterdorfer** [comment]
@original-brownbear seems [Joda Time 2.10.1](https://www.joda.org/joda-time/changes-report.html#a2.10.1) has been released a few days ago which fixes this issue. Could you please do the upgrade?

**Comment by cbuescher** [comment]
Just talked to @original-brownbear since I already halfway started the upgrade I'm going to see if the new version fixed the testing problem.

**Comment by danielmitterdorfer** [comment]
Thanks @cbuescher!

**Comment by cbuescher** [comment]
I checked and can confirm that `2.10.1` fixed the problem we observed in that particular test run (tz = "Africa/Windhoek").
