### ISSUE TITLE
ConnectionTimeout causes deleting index data... 

### ISSUE THREAD

**Issue by xyprojectd** [elastic/elasticsearch#33802]
**Describe the feature**:

**Elasticsearch version** (`Version: 6.2.4`):

**Plugins installed**: [ik]

**JVM version** (JVM: 1.8.0_171):

**OS version** (Linux 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux):

**Description of the problem including expected versus actual behavior**:
bulk writing index data time out causes deleting index, I don't know why, really need help, thank you

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

![3bbd7463ef8416cc63dda32bb8e5d70a](https://user-images.githubusercontent.com/3380147/45678906-06371200-bb6a-11e8-9296-ddf6c919333b.jpg)
![9d05cec6ea7b39e003d8af846ae5baae](https://user-images.githubusercontent.com/3380147/45678934-1222d400-bb6a-11e8-9722-b7afd61f266a.jpg)

code log
2018-09-14 16:27:14,132  [WARNING] ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host=, port): Read timed out. (read timeout=10))

es  log
[2018-09-14T16:27:02,408][INFO ][o.e.c.m.MetaDataDeleteIndexService] [node-1]  ...  deleting index

**Comment by javanna** [comment]
Hello, we reserve github issues for confirmed bugs and feature requests. Please could you move your question to our forums at https://discuss.elastic.co/ ? While doing that, could you also add some more info on what you've been doing and what behaviour you are experiencing? Thanks.
