### ISSUE TITLE
Add support for running packaging tests in the cloud

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#33806]
We now use vagrant with the Virtualbox provider. 
This works ok, but has important drawbacks in terms of required infrastructure ( bare metal in CI ) and speed to run.  
We may be able to use the [vagrant-google](https://github.com/mitchellh/vagrant-google) provider to run packaging tests in the cloud, we should be able to run our images there since custom OSes are [supported](https://cloud.google.com/compute/docs/images/building-custom-os).
The idea would be that we spin up VMs for the test, terminate them after and have some infrastructure to act as a safety net in case the build dies off and the VM is not terminated. 

I would like to gather thoughts trough this ticket. Some questions come to mind:
- Does the idea have merit ? Is it worth to further investigate what it would take to complete this migration ? 
- Would we need to maintain compatibility with Virtualbox  or should we just switch over completely? Comparability will  be more work, so what are the compelling reasons for it ?

Thoughts from @Crazybus @drewr also appreciated.

**Comment by Crazybus** [comment]
> Does the idea have merit ? Is it worth to further investigate what it would take to complete this migration ?

From an Infra point of view this is something we really want too https://github.com/elastic/infra/issues/4626

> Would we need to maintain compatibility with Virtualbox or should we just switch over completely? Comparability will be more work, so what are the compelling reasons for it ?

There are two options here.

1. Have packer build a VirtualBox and a GCP image separately using the same provisioning code. 
2. Switch to building a generic image and convert it for the required cloud provider. 

2 is more work however it is something we are going to need to soon anyway as part of https://github.com/elastic/infra/issues/5700. GCP does not have base images for all of the distributions that we test against. So building our own custom images and converting them into GCP images is going to be the future.

**Comment by atorok** [comment]
We have #11593 instead now
