### ISSUE TITLE
SQL: http | https option in JDBC connection string is ignored

### ISSUE THREAD

**Issue by n0othing** [elastic/elasticsearch#33817]
**Elasticsearch version** (`bin/elasticsearch --version`): 
```
Version: 6.4.0, Build: default/zip/595516e/2018-08-17T23:18:47.308994Z, JVM: 1.8.0_181
```
**JVM version** (`java -version`):
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**Description of the problem including expected versus actual behavior**:

The `http | https` option in the JDBC connection string is ignored, and only `?sql=true` can be used to enable SSL/TLS. Here are the results for connecting to a TLS protected ES cluster:
```
jdbc:es://https://localhost:9200 ---> fails
jdbc:es://https://localhost:9200?ssl=true ---> works
jdbc:es://http://localhost:9200?ssl=true ---> works
jdbc:es://localhost:9200?ssl=true  ---> works
```

**Comment by costin** [comment]
@astefan can you please take a look at this? It might go to 6.4.x as well.

**Comment by astefan** [comment]
Fixed by https://github.com/elastic/elasticsearch/commit/91434f7721954465e21c52373dcb53f5881d6160 (master - 7.0.0).
Fixed by https://github.com/astefan/elasticsearch/commit/1c6c21f90275fb515e2b079792adefc685a71867 (6.x - 6.5.0)
