### ISSUE TITLE
kibana_system role: add read privilege to `apm-*`

### ISSUE THREAD

**Issue by tsullivan** [elastic/elasticsearch#33876]
For monitoring, management and telemetry work going into 6.5.0, we sometimes need to rely on a Kibana-server background task executing a search against data in Elasticsearch. These searches typically run in the context of the kibana/kibana_system user/role. 

Currently we'll have privilege problems if we try to execute a search against `apm-*` indices. The most straightforward solution to this would be to grant `read` access to the kibana user for `apm-*` data.

The kibana_system role grants `read` privilege to `.monitoring-*` indices. Based on the commit history, that also seems to be for management purposes. 

cc @sqren @makwarth @pickypg

**Comment by skearns64** [comment]
@tsullivan - Instead of granting this privilege to the `kibana_system` user, would it be possible to always do the APM portion of the checks "live" as the logged in user, not as the `kibana` system user? I'm hesitant to grant read privileges to non-system indices to `kibana_system`, as it exposes a greater attack surface (and not an obvious one), were someone to compromise the `kibana` user.  

cc @joshbressers @yaronp68

**Comment by sqren** [comment]
> Instead of granting this privilege to the kibana_system user, would it be possible to always do the APM portion of the checks "live" as the logged in user, not as the kibana system user? 

We cannot guarantee the user will have access to `apm-*`, so the request could fail. I'm okay with that though, if we deem it an edge case.
What do you think @tsullivan ?

**Comment by pickypg** [comment]
The API in question has won't really have a user-level context, so it would be awkward for it to require a user to have the privileges.

**Comment by tsullivan** [comment]
> Instead of granting this privilege to the kibana_system user, would it be possible to always do the APM portion of the checks "live" as the logged in user, not as the kibana system user?

> We cannot guarantee the user will have access to apm-*, so the request could fail. I'm okay with that though, if we deem it an edge case.
What do you think @tsullivan ?

Telemetry for Kibana today does not to "live" checks for data the way that Elasticsearch information can be gathered live when Monitoring is disabled. This is a tech debt piece that remains because there isn't a great security model for user context on fetching live data from Kibana, partly due to Spaces making it likely the calling user will not have read access to all the objects in the .kibana index. But it means that there is no "live" pulling phase for Kibana telemetry. See: https://github.com/elastic/kibana/issues/21241, and there is also a story about this in the Kibana Platform team backlog in Clubhouse.

APM usage data only being available when Monitoring is enabled means that it gets initially stored there in the background task where the internal user queries for stats and uploads them to the Monitoring bulk endpoint to populate kibana_stats data.

It would be possible to piggy back other requests that authorized users have for APM stats and keep an updated document stored in the `.kibana` index. That way, the APM usage collector could get that information from `.kibana` instead of `apm-*`. That does mean a more complicated implementation model for @sqren to implement

**Comment by sqren** [comment]
> It would be possible to piggy back other requests that authorized users have for APM stats and keep an updated document stored in the .kibana index (...) That does mean a more complicated implementation model for @sqren to implement

Yes, this would be a more complicated implementation. It sounds more like a temporary bandaid, than the "real solution", but depending on how far out a real solution is, we might do this.

I have a few concerns:
 - End user perf: it could make requests from the user's browser slower
 - tech debt: adding this to every APM endpoint is not ideal, and something we want to remove again in the future
 - Time: it could take a non-trivial amount of time to set this up

@makwarth any thoughts?

**Comment by makwarth** [comment]
Discussed this with @sqren. We could temporarily do:

- Piggy back on user requests, but only on the Services list page (APM homepage)
- Store telemetry data in `.kibana` index
- Have our usage collector query the `.kibana` index

@tsullivan Where in the `.kibana` index should we store [our telemetry](https://github.com/elastic/telemetry/issues/55#issue-361015957) data exactly?

**Comment by tsullivan** [comment]
I'll refer you to the KQL telemetry PR for this, which is doing something similar and has gone through a few rounds of feedback already: https://github.com/elastic/kibana/pull/23547

**Comment by makwarth** [comment]
Closing for https://github.com/elastic/kibana/issues/24142
