### ISSUE TITLE
Cluster goes into a yellow state when relocating active primary shards

### ISSUE THREAD

**Issue by rlhh** [elastic/elasticsearch#33872]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.2

**Plugins installed**: []

JVM version (java -version): openJDK 8

OS version (uname -a if on a Unix-like system): Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:
While trying to decommission nodes by using "index.routing.allocation.exclude._ip", we noticed that the cluster will go into a yellow state when it's  trying to move a primary shard for an index that's still receiving data. The same behaviour is observed when we use a move command. 

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Find a primary shard for an active index, note down the node id and shard number
 2. Find a node where you can move the shard  to
 3. Use the cluster/reroute to move the shard
`
POST /_cluster/reroute
{
    "commands" : [
        {
            "move" : {
                "index" : "auditbeat-2018.09.07.17.00-1", "shard" : 0, "from_node": "qeAlD-qDS8yY_Okmcfqihg", "to_node": "zLhxQOynRJSF8a_58D-vyA"
            }
        }
    ]
}
`
 4. You'll notice that the cluster is now in a yellow state now because there's a shard that's not allocated

The move and relocation of inactive primary shards are however ok. Is this the expected behaviour?

**Comment by ywelsch** [comment]
@rlhh are you getting any failures in the logs that might indicate why the shard failed? If not, can you set the logger level of `org.elasticsearch.cluster.action.shard` to `DEBUG`, and try to reproduce this again?

**Comment by DaveCTurner** [comment]
I tried to reproduce this and could not. I started a three-node cluster and created a one-shard one-replica index:

```
PUT /i
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 1,
    "refresh_interval": 0,
    "routing.allocation.include._name": "node-1"
  }
}
```

I then started 30 processes concurrently bulk-indexing documents into this shard (10 per node), each repeatedly doing this:

```
POST /i/_doc/_bulk
{"index":{}}
{}
{"index":{}}
{}
{"index":{}}
{}
{"index":{}}
{}
{"index":{}}
{}
{"index":{}}
{}
{"index":{}}
{}
{"index":{}}
{}
{"index":{}}
{}
{"index":{}}
{}
```

I then repeatedly moved the primary shard between the two nodes that didn't hold the replica using this:

```
POST /_cluster/reroute
{
  "commands": [
    {
      "move": {
        "index": "i",
        "shard": 0,
        "from_node": "node-0",
        "to_node": "node-1"
      }
    }
  ]
}

GET _cluster/health?wait_for_no_relocating_shards=true

POST /_cluster/reroute
{
  "commands": [
    {
      "move": {
        "index": "i",
        "shard": 0,
        "from_node": "node-1",
        "to_node": "node-0"
      }
    }
  ]
}

GET _cluster/health?wait_for_no_relocating_shards=true
```

At no point did I see a log message indicating there were any unallocated shards, or that the cluster health had dropped from GREEN. However, it was notable that sometimes the relocation took quite some time, and in this case stopping the source node prematurely would result in an unassigned shard. Is this perhaps what's happening?

**Comment by rlhh** [comment]
I just tried reproducing this earlier today and was unable to. The only cluster setting change that we've made since opening this issue in the first place is that we've turned off tcp compression (because it has been slowing down our recoveries https://github.com/elastic/elasticsearch/issues/33844#issuecomment-423251859). I'll close this for now and report back again if I can reproduce it.
