### ISSUE TITLE
Access _source in scripted metric aggregation with state context

### ISSUE THREAD

**Issue by ruizmarc** [elastic/elasticsearch#33884]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.1

**Plugins installed**: No plugins installed

**JVM version** (`java -version`):  java version "1.8.0_25"

**OS version** (`uname -a` if on a Unix-like system): Darwin Kernel Version 17.5.0

**Description of the problem including expected versus actual behavior**:

I was trying to use an scripted metric aggregation with the new context (state) instead the old one (params). And aggregations are working properly if accessing doc. However, with previous versions I was able to access _source by doing: params._source. With this new context, I cannot access _source with: state._source, nor params._source. 

I was expecting to be able to continue accessing _source as in previous versions because some of my current scripts  are not working with this new version. 

For our use case it is very convinient to be able to access the _source because we have quite complex structures with deep nested array fields that must be evaluated independently and being able to access _source allows us to do very complex calculations on some of those nested fields.

**Comment by rjernst** [comment]
This was unintentional and a side effect of the state refactoring work. Note, though, that the intent is not to have _source under state. Instead, we will add it back to params for now. I'll work on a fix for this in 6.4.2.

**Comment by ruizmarc** [comment]
Thanks for your quick response! It will be great to have the feature back :)
