### ISSUE TITLE
SQL: refactor FunctionRegistry to deal with optional parameters functions differently

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch#33885]
Locate, Round and Truncate can have optional parameters and, [at the moment](https://github.com/elastic/elasticsearch/pull/33779#discussion_r219041553) this is dealt with inside FunctionRegistry, which is rather not the best place where this check should be done.

**Comment by wchaparro** [comment]
Closing as not planned, superceded by our work in ES|QL. Please reopen if you have concerns.
