### ISSUE TITLE
Problem with org.elasticsearch.join.ParentJoinPlugin

### ISSUE THREAD

**Issue by ritwik1994** [elastic/elasticsearch#33887]
Hi, 

I have created the configuration of elasticservice in my spring boot app with the code :- 
TransportClient client = new PreBuiltTransportClient(Settings.EMPTY);

But I am getting the error :- 
15:36:02.963 [main] ERROR org.springframework.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'contentController': Unsatisfied dependency expressed through field 'contentSearchService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'contentSearchImpl': Unsatisfied dependency expressed through field 'contentSearch'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'contentSearch': Cannot resolve reference to bean 'elasticsearchTemplate' while setting bean property 'elasticsearchOperations'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'elasticsearchTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/elasticsearch/ElasticsearchDataAutoConfiguration.class]: Unsatisfied dependency expressed through method 'elasticsearchTemplate' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'client' defined in class path resource [com/khabri/config/ElasticSearchConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.elasticsearch.client.Client]: Factory method 'client' threw exception; nested exception is java.lang.IllegalArgumentException: NamedWriteable [org.elasticsearch.index.query.QueryBuilder][parent_id] is already registered for [org.elasticsearch.search.SearchModule$$Lambda$756/688426301], cannot register [org.elasticsearch.join.ParentJoinPlugin$$Lambda$766/1660136848]

**Comment by cbuescher** [comment]
Hi @ritwik1994! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.
