### ISSUE TITLE
Support date histograms over date range fields

### ISSUE THREAD

**Issue by jimmyjones2** [elastic/elasticsearch#33897]
**Describe the feature**:

I've got a dataset that contains date range fields eg. employment start to finish dates. I'd like to plot a date histograms of the number of records it matched in a time period eg. how many employees did we have on each day of the last year

**Elasticsearch version**

6.4.1

**Comment by jpountz** [comment]
We agree that it would be a nice feature to support. Closing in favor of #23182 which already captures this need and has some discussion.
