### ISSUE TITLE
Rename max_write_buffer_size in _ccr/stats as it's misleading

### ISSUE THREAD

**Issue by dliappis** [elastic/elasticsearch#33906]
The [max_write_buffer_size](https://github.com/elastic/elasticsearch/blob/b9e2b5cfec81c6bfa652368926d0d4102521dd72/x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/ShardFollowTask.java#L50) parameter name is misleading: it gives the impression that you are controlling directly the size of the allocated write buffer per shard, however it is a threshold controlling the amount of subsequent reads.

For example with the following index settings:

```
{
  "max_concurrent_read_batches": 1,
  "max_concurrent_write_batches": 1,
  "max_batch_operation_count": 32768,
  "max_batch_size_in_bytes": 4718592,
  "max_write_buffer_size": 33000
}
```

it's possible that one read brings `max_batch_operation_count` **32768** # of docs, the subsequent read sees that `max_write_buffer_size` is still higher (33000) and retrieves another batch of `32768` documents. In this case and instance, the `_ccr/stats` field `number_of_queued_writes` correctly reports `65535`.

One suggestion would be to rename:
`max_write_buffer_size` -> `max_subsequent_reads_into_write_buffer` or replace `subsequent` with `next` to make it shorter. Any other suggestion is welcome of course.

**Comment by dliappis** [comment]
cc @jasontedor for awareness.

**Comment by bleskes** [comment]
+1 to rename. I would propose `max_queued_writes`

**Comment by martijnvg** [comment]
@dliappis Yes, I think we can close this issue.

**Comment by dliappis** [comment]
Closed as per https://github.com/elastic/elasticsearch/issues/33906#issuecomment-432774798
