### ISSUE TITLE
[Rollup] Update create job API endpoint to support starting the job immediately

### ISSUE THREAD

**Issue by cjcenizal** [elastic/elasticsearch#33909]
Per discussion with @eskibars, we think it'd be a nice UX improvement to give the user a checkbox for starting a new job immediately after it's created. This will be straightforward to implement once the create job API supports this.

**Comment by cjcenizal** [comment]
We were able to workaround this within Kibana, so I'm going to close this (https://github.com/elastic/kibana/pull/41573).

**Comment by Dumbaz** [comment]
Hi,

I think that this Option in the create Job API would be very useful to have. In my Project we do not create Rollup Jobs via Kibana, all configuration lives in Git as JSON files and gets rolled out from there. This is the only point where I have to create a configuration in the cluster first and then issue a second request to start it, which makes it different from all other API requests. I can of course work around that easily with the `_rollup/job/<job_id>/_start` API, but I´d rather issue only 1 call to ES without having this dependency on the second step.
