### ISSUE TITLE
XContentElasticsearchExtension's TimeValue handling looks wrong

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#33908]
Right now we handle serializing `TimeValue` with:
```
        writers.put(TimeValue.class, (b, v) -> b.value(v.toString()));
```

But I *think* we should be doing it with
```
        writers.put(TimeValue.class, (b, v) -> b.value(v.getStringRep()));
```

because `toString` produces fractional time values which we can't parse.

**Comment by nik9000** [comment]
Or maybe it isn't *wrong* because sometimes we want to produce a shortened result for the user. But it is *confusing* because when we want to parse the result back we have to use `getStringRep`.

**Comment by pinaksawhney** [comment]
Hi @nik9000 , just wanted to check if this issue is still active?

If so I could try to implement 
>         writers.put(TimeValue.class, (b, v) -> b.value(v.getStringRep()));

**Comment by vamuzumd** [comment]
@pinaksawhney are you still working on this? If not, I'd like to send out a PR.

**Comment by nik9000** [comment]
Oh boy, I missed the last comment by a few months. Its been long enough since I filed this that I don't really know if that is the right way to parse it any more. But its worth looking at. I'd appreciate any investigation you'd like to do @vamuzumd or @pinaksawhney .

**Comment by vamuzumd** [comment]
> Oh boy, I missed the last comment by a few months. Its been long enough since I filed this that I don't really know if that is the right way to parse it any more. But its worth looking at. I'd appreciate any investigation you'd like to do @vamuzumd or @pinaksawhney .

@nik9000 , can you elaborate on the problem with current actual output and what is the expected/dersired output for TimeValue?

**Comment by nik9000** [comment]
I think we actually handle this properly now. Its been a few years since I made this so its out of date. By [default](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/xcontent/XContentElasticsearchExtension.java#L71) we do indeed output fractional time values. Those are useful for people but we can't parse them. At least, I think its easier to read something like `1.2 hours` than `72 minutes`. It might not be. Anyway! We [hook](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/xcontent/XContentElasticsearchExtension.java#L110) a "raw" representation that writes milliseconds. So I *think* that what this was about.

I'm also pretty sure it was never a "good first issue". It's really hard to find "good first issues" in a project as, uh, venerable and expansive as Elasticsearch. I've been working on it for years and get muddled about what is "normal". There are lots of "things" to discover. I'll keep trying to add this tag, but I'll keep making mistakes.
