### ISSUE TITLE
Infinite loop on malformed input JSON

### ISSUE THREAD

**Issue by sabi0** [elastic/elasticsearch#33901]
Loops like this will iterate forever if the input stream does not have a closing curly brace:
https://github.com/elastic/elasticsearch/blob/8f2feb84143aff46225f0bca84d6f7d0d40f99fc/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/input/chain/ChainInput.java#L62

A null check should be added to prevent this:
```
while ((token = parser.nextToken()) != XContentParser.Token.END_OBJECT && token != null) {
```

Some other occurrences of the same problem:

https://github.com/elastic/elasticsearch/blob/1136a9583792ae20ffc2d6c58324ce4e04962976/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/action/privilege/PutPrivilegesRequestBuilder.java#L64

https://github.com/elastic/elasticsearch/blob/5bcdff73d756814f270794110fb4502d0a2a513a/server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/SnapshotStats.java#L229

Note that sometimes there is an (indirect) check for `token == null` inside the loop. See e.g. BasicAuth.java:
https://github.com/elastic/elasticsearch/blob/e1206a6272d1ce2269efa97119071584cc35f44c/x-pack/plugin/watcher/src/main/java/org/elasticsearch/xpack/watcher/common/http/BasicAuth.java#L78

And a few more with `END_ARRAY`:

https://github.com/elastic/elasticsearch/blob/237650e9c054149fd08213b38a81a3666c1868e5/server/src/main/java/org/elasticsearch/search/profile/SearchProfileShardResults.java#L147

https://github.com/elastic/elasticsearch/blob/237650e9c054149fd08213b38a81a3666c1868e5/server/src/main/java/org/elasticsearch/search/profile/aggregation/AggregationProfileShardResult.java#L88

https://github.com/elastic/elasticsearch/blob/38bdf9ce3238c5399e18b33efba34df3a269e17c/x-pack/plugin/graph/src/main/java/org/elasticsearch/xpack/graph/rest/action/RestGraphAction.java#L146

**Comment by sabi0** [comment]
It might be reasonable to have `nextToken()` throw an "Unexpected end of stream" exception. And provide `nextTokenOrNull()` for those (presumably rare) cases when end of stream needs to be handled in a special way.

It would also be nice to be able to iterate the tokens in a more streamlined way:
```
for (Token token : parser.iterateUntil(XContentParser.Token.END_OBJECT)) {
```
I could create a PR for the latter change if you think it would be a useful addition.

**Comment by nik9000** [comment]
@sabi0, It looks to me like we're protected from this by a `com.fasterxml.jackson.core.io.JsonEOFException` that jackson throws at us when it hits the end of the steam but expects an END_ARRAY or END_OBJECT. Do these cause infinite loops for you?

For the most part we're pushing folks towards using `ObjectParser` which makes it a lot easier to look at the parsing code and say "this is right". I'm weary of making behavioral changes to methods like `nextToken` because they are still used in a ton of places. If most places used `ObjectParser` then a change to that method would be fine.

**Comment by nik9000** [comment]
> P.S. Do all XContent formats have "unexpected EOF" protection?

They do, yes.
