### ISSUE TITLE
What to use in ES in absence of removed MLT?

### ISSUE THREAD

**Issue by hipertracker2** [elastic/elasticsearch#33939]
The documentation is confusing. I found that, first "more_like_this", and later "mlt" were removed from the API. I need MLT for the searching similar docs.

**Comment by nik9000** [comment]
Could you send me some links to the documentation about removing `more_like_this`? It looks like `more_like_this` is the name it should have and I'd be happy to clean up any confusing documentation.

**Comment by hipertracker2** [comment]
I closed the ticket since it's not relevant. more_like_this is there, it only lost few params, like "mlt" https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_search_changes.html

**Comment by nik9000** [comment]
Got it, thanks! In general I'm quite happy to go and fix confusing documentation.
