### ISSUE TITLE
Highlighting is not working as expected with synonym wordnet filter in elasticsearch

### ISSUE THREAD

**Issue by ashwinrao286** [elastic/elasticsearch#33941]
Hi Guys,
I am facing some issue in highlighting synonyms which are mapped from Wordnet. It is highlighting irrelevant words while searching.

Here's my code below.
```
{
  "settings" : {
    "index" : {
        "analysis" : {
            "analyzer" : {
                "synonym" : {
                    "tokenizer" : "standard",
                    "filter" : ["synonym","lowercase"]
                }
            },
            "filter" : {
                "synonym" : {
                    "type": "synonym",
                    "format" : "wordnet",
                    "synonyms_path": "analysis/wn_s.pl"
                }
            }
        }
    }
  },
    "mappings": {
        "header": {
            "properties": {
              "test_string": { 
                "type": "text",
                "analyzer": "synonym",
                "term_vector": "with_positions_offsets"
              }
            }
        }
    }
}
```
My search query
```
{
  "query": {
    "query_string": {
      "query": "info~"
    }
  },
  "highlight": {
    "pre_tags": [
      "<span>"
    ],
    "post_tags": [
      "</span>"
    ],
    "fields": {
      "test_string": {}
    },
    "fragment_size": 501,
    "number_of_fragments": 1
  }
}
```

Results are as below.

TEST: This area contains the Customer name: TEST Customer Type TEST: This area contains **information** on the  type: TEST DLA

Note : Please click '**new** value' column and 'old value' column on the Contract Header page to view complete values.

Note: Transaction report present on Header display only partial value, user need to click '**Old** Value' and 'New Value' to view complete.

Please suggest where I am going wrong. Thanks.

**Comment by astefan** [comment]
Hi @ashwinrao286,
Github is for issues (confirmed bugs) or new feature requests, while your question doesn't fit this purpose. Can you, please, post your question in [our forum](https://discuss.elastic.co/) and someone will help you there?

When you post there, do please provide a more clear description of your issue:
* ES version
* sample data to reproduce the problem 
* desired output vs. current output
