### ISSUE TITLE
SearchResponse.isTerminatedEarly() returns null instead of false

### ISSUE THREAD

**Issue by phoerious** [elastic/elasticsearch#33949]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.1

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_181

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 18.04

**Description of the problem including expected versus actual behavior**: `org.elasticsearch.action.search.SearchResponse.isTerminatedEarly()` returns `null` when the result list is too short. It should only return `true` or `false`.

I just upgraded from Elasticsearch 5.6 to 6.4.1 and using the Java transport API, I got an unexpected `NullPointerException` in my existing code by forwarding the return value of `isTerminatedEarly()` as a `boolean`. I had a quick look through git blame, but I don't see any immediate and obvious changes to the function itself, so the behaviour must have changed somewhere deeper in the system.

**Steps to reproduce**:
Run a query which returns a result list shorter than the termination threshold and `isTerminatedEarly()` returns `null`.

**Comment by jimczi** [comment]
It is true that the format changed in 6x, we return `null` if none of the shards terminates the search early. However this change is not listed in the breaking changes so I'd prefer if we update the documentation rather than changing the format again.

**Comment by phoerious** [comment]
I don't understand the rationale. Under which circumstances do you return `false` then? When only some of the shards terminated early? That doesn't make a lot of sense to me.

**Comment by jimczi** [comment]
This is when you use `terminate_after`, right ? Sorry I was confused because we have other places that can "early" terminate a search but none of them set the `isTerminatedEarly` flag as I initially thought. I agree that this is a regression and I'll mark this issue as a bug. When `terminate_after` is set `terminated_early` should not be null in the response.

**Comment by phoerious** [comment]
Yes, I terminate the search after 70k results on a node to reduce search times. A return value of `null` makes no sense here.
