### ISSUE TITLE
[CCR] Shard follow task should validate follow shard history uuid

### ISSUE THREAD

**Issue by martijnvg** [elastic/elasticsearch#33956]
Currently it is possible to to remove the follower index while ccr replicates document from a leader index into it and then to create a new follower index (just via create index api) and ccr will then after retrying continue to replicate documents into the the just newly created index. This is bad, because all checks that we do in the follow index are bypassed and the follow index is no longer identical to the leader index.

In order to prevent this situation, the shard follow tasks need to continuously check whether the follow shard is the same shard. I think the best way to do this is to record the history uuid of the follow shard when the shard follow task is started and the pass that down to the bulk shard operations api. In the bulk shard operations api we would then check if the provided history uuid is identical to the current history uuid and if not fail with an error that the shard follow task does not retry (e.g. IllegalStateException).

Note that in #33954, we plan to no longer retry `IndexNotFoundException` exception and that should fail a shard follow task if it would replicate the documents into a follow shard. However that doesn't help in the case that a shard follow task is idle (because there are no documents to replicate), because when after the idle period, when the shard follow task starts to replicate, the underlying follow index could have been changed.

**Comment by bleskes** [comment]
I think that makes sense and is relevant in more cases (force allocate stale primary, restore from snapshot etc). Later when we have the recovery logic in place we can verify the history is identical to the primary. Also I’m good with just stopping the task for now. Later we’ll probably want to reboot it.
