### ISSUE TITLE
Ingest-Date-Processor: date parse failure for ISO8601

### ISSUE THREAD

**Issue by omnidepp** [elastic/elasticsearch#33959]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.1

**Description of the problem including expected versus actual behavior**:
If milliseconds are missing, a timestamp string in ISO8601-format causes a date parse failure.

This parses correctly: `018-09-18T10:09:09.007Z`
This does not: `2018-09-18T10:09:09Z`

**Steps to reproduce**:

Parsing a timestamp like this **2018-09-18T10:09:09Z** with the date processor in an ingest pipeline results in an exception:

```
"type": "exception",
        "reason": "java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: unable to parse date [2018-09-18T10:09:09Z]",
        "caused_by": {
          "type": "illegal_argument_exception",
          "reason": "java.lang.IllegalArgumentException: unable to parse date [2018-09-18T10:09:09Z]",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": "unable to parse date [2018-09-18T10:09:09Z]",
            "caused_by": {
              "type": "illegal_argument_exception",
              "reason": """Invalid format: "2018-09-18T10:09:09Z" is malformed at "Z""""
            }
          }
       }
```

My ingest processor:

```
"date": {
        "field": "FirstTime",
        "formats": [
          "ISO8601"
        ]
}
```

Something like this does not work either:
```
"date": {
        "field": "FirstTime",
        "formats": [
          "ISO8601",
          "yyyy-MM-dd'T'hh:mm:ss'Z'"
        ]
}
```
Seems java-related according to this: [https://stackoverflow.com/questions/2580925/simpledateformat-parsing-date-with-z-literal](url)

**Comment by danielmitterdorfer** [comment]
I ran the following simulate pipeline API call against Elasticsearch 6.4.1:

```
curl -X POST "localhost:9200/_ingest/pipeline/_simulate?pretty" -H 'Content-Type: application/json' -d'
{
  "pipeline" :
  {
    "processors": [
    {
      "date" : {
        "field" : "initial_date",
        "target_field" : "timestamp",
        "formats" : [
          "ISO8601"
        ]
      }
    }
  ]
  },
  "docs": [
    {
      "_index": "index",
      "_type": "_doc",
      "_id": "id",
      "_source": {
        "initial_date": "2018-09-18T10:09:09Z"
      }
    }
  ]
}
'
```

which returned the following response:

```
{
  "docs" : [
    {
      "doc" : {
        "_index" : "index",
        "_type" : "_doc",
        "_id" : "id",
        "_source" : {
          "initial_date" : "2018-09-18T10:09:09Z",
          "timestamp" : "2018-09-18T10:09:09.000Z"
        },
        "_ingest" : {
          "timestamp" : "2018-09-24T07:32:47.777311Z"
        }
      }
    }
  ]
}
```

So it seems the date "2018-09-18T10:09:09Z" has been parsed just fine? Can you please try that API call as well? Does your pipeline contain other processors that might cause this behavior? You can check the pipeline definition for a pipeline named `my-pipeline` with:

```
curl -X GET "localhost:9200/_ingest/pipeline/my-pipeline"
```

**Comment by omnidepp** [comment]
You are right! Your example works smoothly.
The error I was getting, didn't point me to the right processor. 
The issue is with date_index_name - or with the way I use it.

I was using it like this:

```
{
      "date": {
        "field": "FirstTime",
        "formats": [
          "ISO8601"
        ]
      }
    },
    {
      "date_index_name": {
        "field": "FirstTime",
        "index_name_prefix": "myprefix-",
        "index_name_format": "yyyy-MM",
        "date_rounding": "M"
      }
    }
```

Because of your comment, I modified the pipeline to store the parsed time in a separate field, which date_index_name apparently understands:

```
{

      "date": {
        "field": "FirstTime",
        "target_field": "@timestamp",
        "formats": [
          "ISO8601"
        ]
      }
    },
    {
      "date_index_name": {
        "field": "@timestamp",
        "index_name_prefix": "myprefix-",
        "index_name_format": "yyyy-MM",
        "date_rounding": "M"
      }
    }
```
Unless this is an issue with date_index_name, please close this one - I apologize.
Thank you for getting me in the right direction.

**Comment by danielmitterdorfer** [comment]
I see. So, based on your feedback I'm closing the issue. 

By the way, I don't think you need to use the `date` processor here (unless you need to store the timestamp as date). You can provide the `date_formats` parameter so the `date_index_name` processor itself will convert the string representation to a date. E.g.:

```
curl -X POST "localhost:9200/_ingest/pipeline/_simulate?pretty" -H 'Content-Type: application/json' -d'
{
  "pipeline" :
  {
    "processors": [
    {
      "date_index_name" : {
        "field": "FirstTime",
        "index_name_prefix": "myprefix-",
        "index_name_format": "yyyy-MM",
        "date_rounding": "M",
        "date_formats" : [
          "ISO8601"
        ]
      }
    }
  ]
  },
  "docs": [
    {
      "_index": "index",
      "_type": "_doc",
      "_id": "id",
      "_source": {
        "FirstTime": "2018-09-18T10:09:09Z"
      }
    }
  ]
}
'
```
