### ISSUE TITLE
Why is donald trump mentioned in the code?

### ISSUE THREAD

**Issue by slammerhammer** [elastic/elasticsearch#33969]
Everyone can agree that donald trump is racist and sexist. Everyone can agree he hates everyone who isn't white and male. Why is donald trump mentioned in the code how could you let some neo nazi trump supporter sneak propaganda into the source code. i am very offended by this and hope it gets removed immediately. do this in the name of equality, justice, and saving your project from nazis

https://github.com/elastic/elasticsearch/blob/2fa09f062e5fe4165b457fb2b42ff4b65acdb8c7/plugins/mapper-annotated-text/src/test/java/org/elasticsearch/search/highlight/AnnotatedTextHighlighterTests.java#L136

**Comment by M-BoloDyebambewe** [comment]
What the fuck? This must be a joke. Why would anyone do that? Reporting for CoC violatoin
