### ISSUE TITLE
[CI] Test failure in MachineLearningIT#testStartDataFeed

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#33966]
Reproduces for me locally on 6.x:
```
REPRODUCE WITH: ./gradlew :client:rest-high-level:integTestRunner \
  -Dtests.seed=A88FBA013EB3D65 \
  -Dtests.class=org.elasticsearch.client.MachineLearningIT \
  -Dtests.method="testStartDatafeed" \
  -Dtests.security.manager=true \
  -Dtests.locale=en-ZA \
  -Dtests.timezone=America/Montevideo \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

The log is full of repeated messages like so:
```
[2018-09-22T10:19:56,693][ERROR][o.e.x.m.j.p.l.CppLogMessageHandler] [node-0] [test-start-datafeed] [autodetect/35664] [CCountingModel.cc@120] No statistics at 1537607553, current bucket = [1537607554,1537607555)
[2018-09-22T10:19:56,693][ERROR][o.e.x.m.j.p.l.CppLogMessageHandler] [node-0] [test-start-datafeed] [autodetect/35664] [CJsonOutputWriter.cc@174] Simple count detector has no current rate
```

**Comment by romseygeek** [comment]
Build log links:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=fedora/15/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/45/console

**Comment by cbuescher** [comment]
This has failed quite often over the past weekend, I will mute this test on master and 6.x

**Comment by cbuescher** [comment]
Muted with a9ded8f1d5f3d8f27a9386c51073c95658666144 and 6e4ec89bd7c5fe93ade41e1951ecff076bb2953d

**Comment by cbuescher** [comment]
Going through the failures, I also see one where the "testDeleteDatafeed" method failed:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=ubuntu&&virtual/17/console

This seems to be the only instance of this over the weekend though, not sure if this is related. Will keep that one unmuted for now.
