### ISSUE TITLE
Watcher email action fails completely if there is at least one invalid email

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/elasticsearch#33980]
**Elasticsearch version**: `6.2+ but can be applied to previous and latest versions`

**JVM version**: `not relevant`

**OS version**: `not relevant`

**Description of the problem including expected versus actual behavior**:

In case we have several recipient emails in a email action, the watcher is NOT successful until ALL emails are valid.

Should we notify about the invalid format?
Should we notify about the failed delivery?

**Steps to reproduce**:

 1. Install Elasticsearch and Kibana
 2. Add email settings for watcher (a valid smtp)
 3. Create a dummy watcher with an email notification and provide the several addresses as recipients
 4. Test with recipients below

FYI the emails below are redacted:
`xxxxxxxxx@gmail.com` is a valid address.
`yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy@gmail.com` is a not existing address.
`xxxxxxxxx+ahaha@gmail.com` is a valid address (will be sent to `xxxxxxxxx@gmail.com`)

**Several tests**

`xxxxxxxxx@gmail.com, gudsauigdsagiusadsadui, lol.com, a@com, xxxxxxxxx+ahaha@gmail.com, yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy@gmail.com`

> The watcher fails completely, no mail sent.

`xxxxxxxxx@gmail.com, a@com, xxxxxxxxx+ahaha@gmail.com, yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy@gmail.com`

> The watcher is successful, all mails sent by SMTP. The SMTP Delivery service will notify later 2 out (`a@com` and `yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy@gmail.com`) of 4 emails cannot be delivered.

`a@com, xxxxxxxxx+ahaha@gmail.com, yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy@gmail.com`

> The watcher is successful, all mails sent by SMTP. The SMTP Delivery service will notify later 2 out (`a@com` and `yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy@gmail.com`) of 3 emails cannot be delivered.

`a@com, x`

> The watcher fails completely, no mail sent.

`x, xxxxxxxxx@gmail.com`

> The watcher fails completely, no mail sent.

**Comment by JalehD** [comment]
@lucabelluccini I don't think this is explicit to whitelisting as @henrikno explained even a misspelled (wrong email address) email in the watcher configuration blocks the sending of the email to all email recipients. 

Can you please test and verify if that's the case update this issue?

**Comment by lucabelluccini** [comment]
Hello @JalehD, yes I think I should specify more in detail. Updating the issue report above.

**Comment by spinscale** [comment]
@lucabelluccini the correct solution to this would be to throw an error when putting the watch and any of those email addresses is not valid. Would that make sense?

**Comment by lucabelluccini** [comment]
Hello @spinscale, thank you for following this up.
Showing an error mentioning the email format would be more explicit for the user.

**Comment by spinscale** [comment]
I took a quick look into this, and all those email addresses are templateable - which means, they might be containing mustache templates instead of actual email adresses that are replaced on runtime. I opened #34042 - but I'd like to discuss this first.
