### ISSUE TITLE
Can't use fuzzy query and wildcard together?

### ISSUE THREAD

**Issue by pranav241996** [elastic/elasticsearch#34003]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by danielmitterdorfer** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.

**Comment by pranav241996** [comment]
Thanks for reply.

I tried asking same question on community forum, but no one replied. So, I
thought to ask it here.

**Comment by dayuebai** [comment]
I have a similar question. I am building a system to support searching school directory. We are trying to find whether Elasticsearch supports a query to do both fuzzy and prefix match between the searching term and every term in each document. I know Elasticsearch, currently, supports `Autocomplete suggester`. However, this feature is to implement functionality like "autocomplete". I would like to support such a feature for each term (behave like full prefix fuzzy search).

For detail, I also post this question to Elastic discussion forum:

https://discuss.elastic.co/t/implement-full-text-fuzzy-prefix-search-in-elastic-search/158990
