### ISSUE TITLE
elasticsearch-5.6.12.rpm gets rpm tag errors on Fedora 28 and fails to install

### ISSUE THREAD

**Issue by william8000** [elastic/elasticsearch#34087]
**Describe the feature**: I want to install elasticsearch 5 on Fedora 28 by rpm

**Elasticsearch version** (`bin/elasticsearch --version`): 5.6.12 (but this happens on older versions also)

**Plugins installed**: [] none

**JVM version** (`java -version`): openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b15)
OpenJDK 64-Bit Server VM (build 25.181-b15, mixed mode)

**OS version** (`uname -a` if on a Unix-like system): Linux scslaptop37.scs.com 4.18.9-200.fc28.x86_64 #1 SMP Thu Sep 20 02:43:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**: Fedora 28 rpm gets an error on the elasticsearch rpm and does not install it: `elasticsearch-5.6.12.rpm: tag[43]: BAD, tag 1096 type 5 offset 20392 count 126 len 504`

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Download an elasticsearch 5 rpm
 2. Try to install it with rpm -ivh
 3.

**Provide logs (if relevant)**:
```
scslaptop37 ~/Downloads$ sudo rpm -ivh elasticsearch-5.6.12.rpm
error: elasticsearch-5.6.12.rpm: tag[43]: BAD, tag 1096 type 5 offset 20392 count 126 len 504
error: elasticsearch-5.6.12.rpm cannot be installed
scslaptop37 ~/Downloads$ sha512sum elasticsearch-5.6.12.rpm
3ade714b95235f3a334d398575a18cdb0c500d77fa4946e5839ea8557501a076dec547777642dd540b091ba7ef46815294bb2723149ed9a59ed42771cc189e99  elasticsearch-5.6.12.rpm
scslaptop37 ~/Downloads$ cat elasticsearch-5.6.12.rpm.sha512 ; echo
3ade714b95235f3a334d398575a18cdb0c500d77fa4946e5839ea8557501a076dec547777642dd540b091ba7ef46815294bb2723149ed9a59ed42771cc189e99
scslaptop37 ~/Downloads$ ls -l elasticsearch-5.6.12.rpm elasticsearch-5.6.12.rpm.sha512 
-r--r--r-- 1 william william 33775471 Sep 26 12:51 elasticsearch-5.6.12.rpm
-rw-r--r-- 1 william william      128 Sep 26 12:56 elasticsearch-5.6.12.rpm.sha512
scslaptop37 ~/Downloads$ uname -a
Linux scslaptop37.scs.com 4.18.9-200.fc28.x86_64 #1 SMP Thu Sep 20 02:43:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
scslaptop37 ~/Downloads$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b15)
OpenJDK 64-Bit Server VM (build 25.181-b15, mixed mode)
scslaptop37 ~/Downloads$ sudo dnf update
Last metadata expiration check: 2:09:39 ago on Wed 26 Sep 2018 10:55:56 AM EDT.
Dependencies resolved.
Nothing to do.
Complete!
scslaptop37 ~/Downloads$ 
```

**Comment by william8000** [comment]
The tag in question is called `Fileinodes` and is declared as RPM_INT32_TYPE in the tag table but the header item is RPM_INT64_TYPE.

**Comment by jasontedor** [comment]
This appears to be due to a change in `rpm` itself. It appears that `rpm` is stricter now, from some change between 4.14.1 and 4.14.2. Quite likely the offending [change](http://rpm.org/wiki/Releases/4.14.2) is:

>Add header tag type validation prior import

It is very likely that the bug that we are seeing here is in redline, the upstream library that we use to build RPMs.

@atorok Would you please investigate this issue, I consider it serious and potentially a blocker.

**Comment by atorok** [comment]
I was wondering why this was not caught by our packaging tests. 
The reason is that we added fedora to master only, and this is not reproducible there. 
I was able to reproduce this using the image we use for our packaging tests:
```
   vagrant up fedora-28 
   vagrant ssh fedora-28
   sudo rpm -ivh https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.12.rpm
```

**Comment by atorok** [comment]
I couldn't find a bug report, but the problem is not there with never versions of the library. 
Back-porting the tests is not straight forward as we already have releases with this bug that fail in the upgrade tests.

**Comment by jasontedor** [comment]
@william8000 At this time you would have to:
 - use an older version of `rpm` to workaround the issue
 - build from source
 - wait until we do another release <-- we can not give any indication on timing of this
