### ISSUE TITLE
Replace Virtualbox  based test fixtures with docker-compose

### ISSUE THREAD

**Issue by atorok** [elastic/elasticsearch#34095]
Fixtures: We have some fixtures (Kerberos, HDFS, SMB, idp) that use Vagrant with the Virtualbox provider. There isn't a string reason to use neither vagrant nor Virtualbox for these fixtures and we want to reduce reliance on VirtualBox  in the build.

 We would use docker images instead with docker-compose and the [gradle-docker-compose-plugin](https://github.com/avast/gradle-docker-compose-plugin). 
This should work reliably across all OSes. We would skip these tests if `docker-compose` is not available.

Will require CI images to have docker-compose installed.

**Comment by elasticdog** [comment]
> Will require CI images to have docker-compose installed.

All worker images that are capable of running Docker do receive a `docker` label on them in Jenkins, so that can be used as a target for these particular jobs.
