### ISSUE TITLE
SQL Function name resolution depends on the case

### ISSUE THREAD

**Issue by imotov** [elastic/elasticsearch#34114]
When SQL resolves function names, it takes case into consideration that produces unexpected results.

For example, the following tree statements work
```
SELECT CHAR_LENGTH("blah");
SELECT Char_Length("blah");
SELECT CharLength("blah");
```

But if the following 2 statements produce error messages:
```
SELECT cHaR_length("blah");
SELECT CHARLENGTH("blah");
```
In the first case the error message is
```
Unknown function [cHaR_length], did you mean any of [CHAR_LENGTH, CHARACTER_LENGTH, BIT_LENGTH]?
```
Expected behavior is SQL should be case insensitive in the function name resolution.

**Comment by matriv** [comment]
@imotov For the mixed capitalization we can have a fix, but for resolving `CHARLENGTH` we'll need to add some more "magic" since we have no indication on how to guess the position of the underscore. Imho we should just add the alias `CHARLENGTH` for such cases.

@costin what do you think?

**Comment by imotov** [comment]
@matriv the way I understand it `CHARLENGTH` shouldn't actually work. I think the following statements should work:

```
SELECT CHAR_LENGTH("blah");  - currently works 
SELECT Char_Length("blah");  - currently works 
SELECT cHaR_length("blah");  - currently fails
```

And the following statements should fail:

```
SELECT CharLength("blah"); - currently works
SELECT CHARLENGTH("blah"); - currently fails
```

**Comment by matriv** [comment]
- The `cHaR_length` that currently fails, should be fixed.
 - For the `CharLength` that currently works (because we convert camelCase to CAMEL_CASE) there is a discussion here: #34137

**Comment by matriv** [comment]
@imotov The "magic" to convert camelCase to CAMEL_CASE when trying to resolve the functions has been removed. Now the function name provided by the user is just converted to uppercase and tried to be matched with one of the functions or their aliases.

**Comment by imotov** [comment]
@matriv awesome! Thanks!
