### ISSUE TITLE
Elastic Search Does not Start

### ISSUE THREAD

**Issue by sebasdigital** [elastic/elasticsearch#34128]
**Describe the feature**: ElasticSearch does not start

**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.1

**Plugins installed**: [none]

**JVM version** (`java -version`): 18.9

**OS version** (`uname -a` if on a Unix-like system): macOS Mojave 10.14

**Description of the problem including expected versus actual behavior**: After I run elasticsearch, it dies on [2018-09-27T21:12:35,677][INFO ][o.e.g.GatewayService     ] [zWhCPlo] recovered [0] indices into cluster_state line. 

**Steps to reproduce**: Execute bin/elasticsearch

**Provide logs (if relevant)**:
[elasticsearch.log](https://github.com/elastic/elasticsearch/files/2426319/elasticsearch.log)

**Comment by cbuescher** [comment]
Hi @sebasdigital! Your question is better suited to the support forums over at https://discuss.elastic.co. We prefer to use Github issues only for bug reports and feature requests, and we think it's more likely this is a question than a bug report. I'm closing this as an issue here, but encourage you to ask this question in the forum instead. Many thanks.

**Comment by sebasdigital** [comment]
Thanks @cbuescher for your help and guidance and apologies for the mistake.
