### ISSUE TITLE
Azure snapshot request returns 500 error: 

### ISSUE THREAD

**Issue by brandonmichaelhunter** [elastic/elasticsearch#34122]
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 6.4

**Plugins installed**: []Azure Repository, X-Page

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system):ubuntu 16 LTE

**Description of the problem including expected versus actual behavior**:
When attempting to take a Azure snapshot request via kibana I get the following error:
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": null
      }
    ],
    "type": "null_pointer_exception",
    "reason": null
  },
  "status": 500
}
**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. For setting the account and keys I used the following commands:
sudo cat ~/ESKeystoreSettings/azure.client.default.account.txt | bin/elasticsearch-keystore add --stdin azure.client.default.account
sudo cat ~/ESKeystoreSettings/azure.client.default.key.txt | bin/elasticsearch-keystore add --stdin azure.client.default.key
 2. Restarted my node.
 3. Ran the following command in Dev Tools
PUT _snapshot/es-2018-01?pretty=true
{
  "settings": {
    "base_path": "es-2018-01",
    "compress": true,
    "chunk_size": "64mb"
  },
  "type": "azure"
}
**Provide logs (if relevant)**:

Log files are the same from issue #28299

**Comment by ywelsch** [comment]
@brandonmichaelhunter thanks for reporting this. Can you access the logs on your Elasticsearch server? This will give us the full stack trace for the NullPointerException. Also, are you running ES 6.4.0 or 6.4.1?

**Comment by brandonmichaelhunter** [comment]
Hey team,
Thank you for your response. This issue has been resolved on my end. It appears to be a syntax error on my end.

**Comment by DaveCTurner** [comment]
Hi @brandonmichaelhunter, glad to hear you've solved your problem! However a null pointer exception is not something that should happen, even with a syntax error. It'd be great to see a stack trace so we can at least fail more gracefully in this situation.

**Comment by danielmitterdorfer** [comment]
@brandonmichaelhunter is it possible to provide an example stack trace for us as requested in earlier comments? That would really be helpful in improving the situation in the future.

**Comment by iverase** [comment]
No further feedback received. @brandonmichaelhunter  if you have the requested 
information please add it in a comment and we can look at re-opening 
this issue.
