### ISSUE TITLE
ElasticSearch upgrade from 6.4.0 to 6.4.1 breaks keystore and gcs plugin setup

### ISSUE THREAD

**Issue by orlandoescalante** [elastic/elasticsearch#34158]
We recently upgraded to Elastic 6.4.0 and included into the configuration the steps suggested to use GCS plugin for Google Clous Storage snaphots for the backup/restore process. Following what is publish here: https://www.elastic.co/guide/en/elasticsearch/plugins/6.x/repository-gcs-client.html. All was working fine, Elastic starting without problem and backups working as expected on the buckets,

Today I was testing the upgrade to 6.4.1, doing the rolling upgrade suggested: https://www.elastic.co/guide/en/elasticsearch/reference/6.4/rolling-upgrades.html

After the install of Elastic, Plugins updates too, the server started showing some errors like this:

`[2018-09-28T12:50:35,588][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalArgumentException: unknown secure setting [gcs.client.default.credentials_file] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
`
As action plan for the validation I removed/reset the keystore again to see if error can be skipped, and in fact it worked but a new warning appeared:

`[2018-09-28T12:52:36,881][WARN ][o.e.r.RepositoriesService] [node-1] failed to create repository [es-core-backup]
org.elasticsearch.repositories.RepositoryException: [es-core-backup] repository type [gcs] does not exist
`

My doubt is that Upgrade was not as clean as expected, and it evidently broke the GCS/Elastic Keystore setup and the snapshot previous bucket configuration. Is there something I was missing in the process to perform the upgrade?  

I've done other versions upgrade for Elastic in the past and this type of issues never happened on our environments.

**Comment by nik9000** [comment]
@rjernst, could you have a look at this one?

**Comment by rjernst** [comment]
Did you upgrade the `repository-gcs` plugin? This sounds like the plugin is not installed. Can you do listing of your installed plugins and paste the output here?

**Comment by danielmitterdorfer** [comment]
No further feedback received. @orlandoescalante if you have the requested 
information please add it in a comment and we can look at re-opening 
this issue.
