### ISSUE TITLE
Include size values for cluster state 

### ISSUE THREAD

**Issue by F21** [elastic/elasticsearch#3415]
When getting the status using `_status`, the size of each index is given. However, the translog and cluster state's sizes aren't given. This means that we cannot really tell how much space is being occupied by the index on disk.

It would be nice if these 2 pieces of information can be included in the response for each index in `_status`, so that we can calculate the exact disk space the index occupies.

**Comment by SahilC** [comment]
Hi, I'm new to ES, and I want to contribute. Can I take this up?

**Comment by clintongormley** [comment]
Hi @SahilC 

Yes, anything labelled adoptme is up for grabs :)

**Comment by SahilC** [comment]
Hey Clint, please assign this to me. Additionally, I may need a little bit of help getting on my feet with this, could you tell me where to get started?

**Comment by clintongormley** [comment]
@SahilC no need to assign - just send a PR when you're ready.  Sorry I can't provide advice about where to start, that's part of the learning process :)  The forums may helpful to you: https://discuss.elastic.co/

**Comment by mi-hol** [comment]
@clintongormley  with v2.4.2 released on Nov 16 I was wondering if this issue should be closed

**Comment by clintongormley** [comment]
@mi-hol no, this hasn't been done yet
