### ISSUE TITLE
How to use HasPrivilegesAction to check user's privileges

### ISSUE THREAD

**Issue by jemoii** [elastic/elasticsearch#34166]
When I follow [security-api-privileges](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-api-privileges.html) to check user's privileges, 

- curl:
```
curl -X POST \
  http://localhost:9200/_xpack/security/user/_has_privileges \
  -H 'Authorization: Basic ${base64}' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{"cluster": [ "monitor", "manage" ]}'
```
```json
{
    "username": "linda",
    "has_all_requested": true,
    "cluster": {
        "monitor": true,
        "manage": false
    },
    "index": {}
}
```

- Java code(`org.elasticsearch.plugin:x-pack-api:5.5.0`):
```java
HasPrivilegesRequestBuilder hasPrivilegesRequestBuilder = HasPrivilegesAction.INSTANCE.newRequestBuilder(transportClient);
hasPrivilegesRequestBuilder.request().username("linda");
hasPrivilegesRequestBuilder.request().clusterPrivileges("monitor", "manage");
hasPrivilegesRequestBuilder.request().indexPrivileges(new RoleDescriptor.IndicesPrivileges[0]);
HasPrivilegesResponse hasPrivilegesResponse = hasPrivilegesRequestBuilder.get(TimeValue.timeValueMillis(2000));
```

`linda` is my username for cluster, if has no specified username , `HasPrivilegesRequest#writeTo` will throw NullPointException.
But I'm puzzled about `HasPrivilegesResponse`,

```java
public class HasPrivilegesResponse extends ActionResponse {
    private boolean completeMatch;
    private Map<String, Boolean> cluster;
    private List<HasPrivilegesResponse.IndexPrivileges> index;
```
In `HasPrivilegesResponse`, it's `completeMatch` not `has_all_request` or `hasAllRequest`, and `cluster` is always empty.

Is there something wrong with my code? Thank you for pointing it.

- elasticsearch version, 5.5.0
- Java version, 1.8.0_151

**Comment by tlrx** [comment]
You can try something like:

```
final HasPrivilegesRequest request = new HasPrivilegesRequest();
request.username("linda");
request.clusterPrivileges(ClusterPrivilege.MONITOR, ClusterPrivilege.MANAGE);
request.indexPrivileges(new RoleDescriptor.IndicesPrivileges[0]);

HasPrivilegeResponse response = client.execute(HasPrivilegesAction.INSTANCE, privRequest).actionGet();
```

In the response, has_all_requested corresponds to response.isCompleteMatch().

Anyway, we reserve Github for bug reports and feature requests only. Please ask questions like these in the [Elastic forums](https://discuss.elastic.co/) instead. Thank you!
