### ISSUE TITLE
Differentiate between OSS and non-OSS features in the release notes

### ISSUE THREAD

**Issue by xeraa** [elastic/elasticsearch#34208]
**Describe the feature**: Based on a quick discussion with @pcsanwald:

Currently we do not differentiate between X-Pack features and Apache licensed features. As an example, we include ML features: https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-6.4.0.html , which includes this PR: https://github.com/elastic/elasticsearch/pull/31330 (which is an "X-Pack" PR, in that the files use the Elastic license).

Let's discuss in FixIt Friday how this could be changed. There were already comments from the community that the release notes are hard to read, since you need to figure out to which version every change applies.

Once there is an approach in Elasticsearch I'll try to take it to the other open source projects to keep this in sync.

**Comment by tomcallahan** [comment]
Closing this; @xeraa will re-open the discussion in a different venue
