### ISSUE TITLE
ILM shrink action may cause in-flight search requests to fail

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#34229]
The shrink action in ILM goes through the following steps:
1. allocate one copy of each shard for the index to a single node
2. Perform shrink operation
3. Wait for allocation of any replicas on shrunk index
4. As an atomic action, delete the original index and add an alias to the shrunk index for the original index name

The issue comes with step 4. IF there are search requests in flight when the original index is deleted the shard requests may get to the node that the original index was residing on and find the shard no longer exists causing a shard failure. Note that this does not mean all in flight requests will have shard failures but only those which resolved the shards of the original index but did not get received by the shard before it was deleted.

I spoke with @eskibars about this and he felt that it is not a blocker for ILM but is something we should document as a limitation. We should look to solve this in a future release though

**Comment by jakelandis** [comment]
A few additional points:
* Only impacts inflight search requests, and client's re-trying will likely work (fairly short window of impact)
* ILM shrink operation is different then normal shrink operations in that ILM also deletes the original index 
* A potential (but still problematic) fix could be to implement a grace period for the original index delete (can't have index and alias with same name)
* Only impacts searches going to concrete index. Searches through the alias or index pattern are not impacted by this.

**Comment by dakrone** [comment]
Talked a bit with Tal about this. I think we would need something similar to
what we have for shard indexing operation permits, but for search. This would
allow us to wait for all ongoing queries to finish, blocking new ones until the
index was deleted and the alias created, then allowing the queued queries to be
executed.

**Comment by dakrone** [comment]
After discussing this, we determined it is actually something to be solved at a higher level than ILM (meaning in ES itself), I've opened #37323 to that effect.
