### ISSUE TITLE
Enhance position of nulls inside composite aggs sorting

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch#34221]
Currently, missing values are treated as `null`s and appear either first by default (using `ASC` sorting) or last for `DESC` sorting.
It would be useful to further enhance the sorting similar to `FieldSortBuilder` to specify whether the missing values should appear last (`_last`) or first (`_first`). In SQL this would allow implementing `NULLS FIRST/LAST` functionality as well as offer the expected behavior (that NULLs have a fixed position regardless of ordering).

**Comment by Luegg** [comment]
A related (the same?) issue from a user: https://github.com/elastic/elasticsearch/issues/63523
