### ISSUE TITLE
search_after unexpected/undocumented behaviour

### ISSUE THREAD

**Issue by patrykk21** [elastic/elasticsearch#34232]
**Elasticsearch version** (`curl localhost:9200`):
"version" : {
    "number" : "6.2.4",
    "build_hash" : "ccec39f",
    "build_date" : "2018-04-12T20:37:28.497551Z",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  }

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux ********* 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
When using the search_after [API](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-search-after.html), it doesn't look for an exact match on `_id` but for a partial one.

More specific example:

I've set a query like so (ruby):
```
{:sort=>[{:timestamp=>"desc"}, {:_id=>"desc"}],
:search_after=>["1538490843000", "fd5e06f3-ded0-4cc1-8dc5-f798f3165ca2"]}
```

So I'd expect ElasticSearch to look for a record with an `_id` of `fd5e06f3-ded0-4cc1-8dc5-f798f3165ca2`.

However using:
```
{:sort=>[{:timestamp=>"desc"}, {:_id=>"desc"}],
:search_after=>["1538490843000", "fd5e06f3"]}
```
OR
```
{:sort=>[{:timestamp=>"desc"}, {:_id=>"desc"}],
:search_after=>["1538490843000", "f798f3165ca2"]}
```

Respectively the first part of the UUID and the last part of the UUID the same result is yielded, at least for my data.

Basically what I'm understanding is that the matching between the `_id` and the value I provided for the `search_after` API is not an exact (boolean) match, but rather a partial one. If the string I'm passing fits completely into an `_id` of one of the records, then the results after that specific record get yielded.

The expected behaviour is to not have a partial matching but an exact (or boolean) matching. Therefore only the record with the same exact `_id` of the value I'm passing should be used as a starting point.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create an index with timestamp, identifier
 2. Insert some data into the index and have two consecutive values have the beginning of their `_id` value being equal; and the same timestamp. For example "test12345" and test "test45678" with a timestamp of your choice.
 3. Run a search_after with a sorting of [timestamp, _id] and values of [chosen_timestamp, "test"]

You'll see yielded results starting right after one of the documents having an `_id` starting with "test" yielded, however none of the documents exactly matches the given `_id`.

This has been quite a hassle for me and might not even be an undesired behaviour but it is surely not documented or at least it wasn't findable for me.

**Provide logs (if relevant)**:

I'm not sure if this is really an issue but I'd like to know if this is an expected behaviour or rather a lacking documentation issue. Either way, let me know. 

Thank you

**Comment by nik9000** [comment]
@jimczi, could you have a look at this?

**Comment by jimczi** [comment]
This is the expected behavior. The sort values are used to filter documents that compare smaller (or greater depending on the order of the sort). If you want to ensure that the response starts exactly at the `search_after` values you'll need to check the first hit in the response and compare the `sort` values from those provided in the query. However the values used in a `search_after` query are usually  extracted from the last hit of the previous search so you shouldn't deal with partial values at all. Can you explain what you're trying to achieve with `search_after`?

**Comment by jimczi** [comment]
> Overall I think you did a great job with elastcisearch and it's within my intentions to try to help you improve it, even by a little margin, if possible

Thanks, your help is welcome !  I agree that we could add a small note regarding how we handle the provided sort values in `search_after`. Would you like to contribute with improving the documentation ?

**Comment by patrykk21** [comment]
I think the most fitting place for such information would be [this doc page](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html). Do you think it would be possible?

However, if we are talking about this repo I'll create a PR in the next couple of days if I find a fitting place.

Thank you

**Comment by jimczi** [comment]
> I think the most fitting place for such information would be this doc page. Do you think it would be possible?

Yes that's possible, the doc page is in this repo, you can find it [here](https://github.com/elastic/elasticsearch/blob/master/docs/reference/search/request/search-after.asciidoc) and create a PR to modify it.

**Comment by patrykk21** [comment]
I created a [PR](https://github.com/elastic/elasticsearch/pull/36111)

Let me know.
