### ISSUE TITLE
Tasks: API to remove preserved task status

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#34249]
When a user runs any of reindex and friends with `wait_for_completion=false` we create a record of the task when it is finish so that the `/_tasks/{task_id}` API can find the task after it has finished. Right now it is up to the user to delete the record manually from the `.tasks` index but this sort of thing ties us to an implementation detail (the `.tasks` index) in a way that we don't feel comfortable with. We'd like to create an API to clear this preserved task status. That way, in the future, we can move the task preservation mechanism to whatever we'd like without breaking API compatibility.

**Comment by nik9000** [comment]
I think, also, that we should clean up the docs for reindex and friends so they reference some common docs for cleaning up the task status rather than describing how to do it in place. Basically, I think we should *have* docs in one place for how to clean up the preserved task status. And this seems like the right place to do that.

**Comment by idegtiarenko** [comment]
Closing this one as a duplicate: #77383
