### ISSUE TITLE
Move breaking changes to (or near) Upgrading Elasticsearch section

### ISSUE THREAD

**Issue by ppf2** [elastic/elasticsearch#34251]
Somehow breaking changes section is ending up towards the very bottom of the table of contents for the Elasticsearch documentation.

![image](https://user-images.githubusercontent.com/7216393/46380683-16fe8200-c658-11e8-9a34-448b20748c67.png)

Breaking changes is such an important section for upgrades.  Let's move this back up towards the "Upgrade Elasticsearch" section, either as a section parallel to "Upgrade Elasticsearch", or as a subsection within "Upgrade Elasticsearch".

**Comment by lcawl** [comment]
This was an intentional change in https://github.com/elastic/elasticsearch/pull/33588 related to https://github.com/elastic/docs/issues/382

**Comment by lcawl** [comment]
I've verified that there's a link to the breaking changes in the "important" section of each of the following upgrade pages:
https://www.elastic.co/guide/en/logstash/master/upgrading-logstash.html
https://www.elastic.co/guide/en/elasticsearch/reference/master/setup-upgrade.html
https://www.elastic.co/guide/en/kibana/master/upgrade.html

If you have suggestions for other places to link from, though, let me know!

**Comment by ppf2** [comment]
Thanks @lcawl .  While we are linking to breaking changes from https://www.elastic.co/guide/en/elasticsearch/reference/master/setup-upgrade.html and https://www.elastic.co/guide/en/elasticsearch/reference/master/release-highlights.html, as soon as the user starts clicking through the pages linked from these landing pages, they will no longer see the breaking changes link unless they go back to the main page (or scroll all the way down just to find the Breaking Changes section again).

It can be helpful to have the breaking changes section link be prominently displayed alongside "Upgrading ..." sections (below it), or as a subsection of "Upgrading ..." so that it is right there towards the top of the right navigation as a reminder regardless of what subpages they may end up on.

**Comment by debadair** [comment]
[docs issue triage]

Related to ES reorg and general docs navigation. Leaving open for discussion.

**Comment by jrodewig** [comment]
We have some pending redesign and reorganization projects that will make this issue moot. Closing for now. We can re-open later if needed.
