### ISSUE TITLE
Add filter capability to CustomSuggester

### ISSUE THREAD

**Issue by UD1412** [elastic/elasticsearch#34255]
Currently, Filter capabilities are only supported in CompleteionSuggester. This has been achieved by adding a context to the CompletionSuggester.
But there is no such support for a CustomSuggester.

There should be a way to add filter capability to a CustomSuggester.

**Comment by jimczi** [comment]
Can you describe the feature with examples ? `CustomSuggester` refers to the ability to write a custom suggester where you can have all the logics you want. If you meant the `phrase` or `term` suggesters, there is already a way to filter suggestions:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-phrase.html#_basic_phrase_suggest_api_parameters
Check the `collate` option which allows to prune the suggestions for which no matching docs exist in the index.

**Comment by mayya-sharipova** [comment]
Closing as no feedback for more that 2 weeks.
