### ISSUE TITLE
Unbounded Sampler Aggregation will crash ES

### ISSUE THREAD

**Issue by cdekker** [elastic/elasticsearch#34269]
**Elasticsearch version** (`bin/elasticsearch --version`): 6.2.4

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_131

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

When running a [Sampler Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-sampler-aggregation.html) with an extremely high value for `shard_size` it will cause an OOM exception on all nodes handling queries for their shards.

This problem occurs even when the index is nearly empty.

I would expect a Circuit-breaker exception to be triggered in this case, as it should be pretty clear that I don't have the heap memory available for loading that many aggregation samples. Alternatively, the sampler aggregation should be capped at the total number of documents, never (trying to) allocate more memory then there are documents for aggregations. 

In that spirit, I would expect a sampler aggregation to always perform faster or equal to not having a sampler and aggregating over the entire result set.

**Steps to reproduce**:

I was able to reproduce the issue using the following query:

```
{
  "size": 0,
  "aggs": {
    "sample": {
      "sampler": {
        "shard_size": 2000000000
      },
      "aggs": {
        "documentdate": {
          "date_range": {
            "field": "documentdate",
            "format": "yyyy-MM-dd",
            "ranges": [
              {
                "from": "now-360001d"
              },
              {
                "from": "now-366d"
              },
              {
                "from": "now-181d"
              },
              {
                "from": "now-91d"
              },
              {
                "from": "now-31d"
              },
              {
                "from": "now-8d"
              }
            ]
          }
        }
      }
    }
  }
}
```

**Comment by colings86** [comment]
@markharwood could you take a look at this one?
