### ISSUE TITLE
Feature request: multiple simultaneous snapshots

### ISSUE THREAD

**Issue by benhyland** [elastic/elasticsearch#34274]
The docs (https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html) say
`Only one snapshot process can be executed in the cluster at any time`.

I would like to index multiple independent data streams onto a single cluster, and take snapshots of each index for backup.
I don't want to have the overhead of coordination between data sources to avoid simultaneous snapshot attempts, or to retry failed attempts.
It's important that the indexing and backups complete both independently, and very quickly, so running snapshots in parallel is very desirable.

Why does the restriction exist?
Is it possible for it to be removed?
Is this issue on the roadmap at all?

Many thanks for any answers or advice!

**Comment by original-brownbear** [comment]
@ywelsch I marked this team discuss now since I think we never quite finished the discussion of whether we want this or not.
Tbh. though I'd probably close here if there's no objection. Implementing this is going to be quite tricky in the near future and the added value is pretty questionable (I don't think we should necessarily encourage continuously taking snapshots at a very high frequency).

@benhyland why not just periodically take a snapshot of all the indices you'd like to snapshot?

**Comment by benhyland** [comment]
Our use case involves temporary deployment of a cluster for running end to end tests with.
Intermediate output of several of our data processing steps includes an index snapshot, which we’d like to examine to ensure our automation and config is correct.
Because many tests run in parallel, we’re not currently able to extend our e2e tests of our own automation beyond this stage involving elasticsearch without needing to handle snapshot queueing ourselves, which introduces complexity and delays the test feedback loop.

We don’t have a need to snapshot frequently or in parallel in our production cluster - in fact, we go to some lengths to decouple production from data processing in the first place - partly by using snapshots :)

Hope that all makes sense, thank you for considering the feature.

**Comment by original-brownbear** [comment]
We discussed this during our sync today and decided to not move forward with this for now.
The use-cases for this are really limited and due to the nature of how the snapshot repositories' metadata is handled currently, it would be very complex to implement this.
=> closing here
