### ISSUE TITLE
Nori (Korean) analyzer tokenization issues

### ISSUE THREAD

**Issue by Trey314159** [elastic/elasticsearch#34283]
It makes sense to me to report these all together, but I can split these into separate bugs if that's better.

**Elasticsearch version** (`curl -XGET 'localhost:9200'`):
```
{
  "name" : "adOS8gy",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "GVS7gpVBQDGwtHl3xnJbLw",
  "version" : {
    "number" : "6.4.0",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "595516e",
    "build_date" : "2018-08-17T23:18:47.308994Z",
    "build_snapshot" : false,
    "lucene_version" : "7.4.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Plugins installed**: [analysis-icu, analysis-nori]

**JVM version** (`java -version`):
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Linux vagrantes6 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

I've uncovered a number of oddities in tokenization in the Nori analyzer. All examples are from [Korean Wikipedia](https://ko.wikipedia.org) or [Korean Wiktionary](https://ko.wiktionary.org) (including non-CJK examples). In rough order of importance:

A. Tokens are split on different character POS types (which seem to not quite line up with Unicode character blocks), which leads to weird results for non-CJK tokens:
* `εἰμί` is tokenized as three tokens: `ε/SL(Foreign language) + ἰ/SY(Other symbol) + μί/SL(Foreign language)`
* `ka̠k̚t͡ɕ͈a̠k̚` is tokenized as `ka/SL(Foreign language) + ̠/SY(Other symbol) + k/SL(Foreign language) + ̚/SY(Other symbol) + t/SL(Foreign language) + ͡ɕ͈/SY(Other symbol) + a/SL(Foreign language) + ̠/SY(Other symbol) + k/SL(Foreign language) + ̚/SY(Other symbol)`
* `Ба̀лтичко̄` is tokenized as `ба/SL(Foreign language) + ̀/SY(Other symbol) + лтичко/SL(Foreign language) + ̄/SY(Other symbol)`
* `don't` is tokenized as `don + t`; same for `don’t` (with a curly apostrophe).
* `אוֹג׳וּ` is tokenized as `אוֹג/SY(Other symbol) + וּ/SY(Other symbol)`
* `Мoscow` (with a Cyrillic М and the rest in Latin) is tokenized as `м + oscow`

While it is still possible to find these words using Nori, there are many more chances for false positives when the tokens are split up like this. In particular, individual numbers and combining diacritics are indexed separately (e.g., the `/` in the Cyrillic example above), which can lead to a performance hit on large corpora like Wiktionary or Wikipedia.

Work around: use a character filter to get rid of combining diacritics before Nori processes the text. This doesn't solve the Greek, Hebrew, or English cases, though.

Suggested fix: Characters in related Unicode blocks—like "Greek" and "Greek Extended", or "Latin" and "IPA Extensions"—should not trigger token splits. Combining diacritics should not trigger token splits. Non-CJK text should be tokenized on spaces and punctuation, not by character type shifts. Apostrophe-like characters should not trigger token splits (though I could see someone disagreeing on this one). 

B. The character "arae-a" (ㆍ, U+318D) is sometimes used instead of a middle dot (·, U+00B7) for [lists](https://en.wikipedia.org/wiki/Korean_punctuation#Differences_from_European_punctuation). When the arae-a is used, everything after the first one ends up in one giant token. `도로ㆍ지반ㆍ수자원ㆍ건설환경ㆍ건축ㆍ화재설비연구` is tokenized as `도로 + ㆍ지반ㆍ수자원ㆍ건설환경ㆍ건축ㆍ화재설비연구`.
* Note that "HANGUL LETTER ARAEA" (ㆍ, U+318D) is used this way, while "HANGUL JUNGSEONG ARAEA" (ᆞ, U+119E) is used to create syllable blocks for which there is no precomposed Unicode character.

Work around: use a character filter to convert arae-a (U+318D) to a space.

Suggested fix: split tokens on all instances of arae-a (U+318D).

C. Nori splits tokens on soft hyphens (U+00AD) and zero-width non-joiners (U+200C), splitting tokens that should not be split.
* `hyphen­ation` is tokenized as `hyphen + ation`.
* `بازی‌های ` is tokenized as `بازی + های`.

Work around: use a character filter to strip soft hyphens and zero-width non-joiners before Nori.

Suggested fix: Nori should strip soft hyphens and zero-width non-joiners.

D. Analyzing 그레이맨 generates an extra empty token after it. There may be others, but this is the only one I've found. Work around: at a min length token filter with a minimum length of 1.

E. Analyzing 튜토리얼 generates a token with an extra space at the end of it. There may be others, but this is the only one I've found. No work around needed, I guess, since this is only the internal representation of the token. I'm not sure if it has any negative effects.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Set up Nori analyzer
```
curl -X PUT "localhost:9200/nori?pretty" -H 'Content-Type: application/json' -d'
{
  "settings" : {
    "index": {
      "analysis": {
        "analyzer": {
          "text": {
            "type": "nori"
          }
        }
      }
    }
  }
}
'
```
 2. Analyze example tokens:

A. POS Types cause token splits
```
curl -sk localhost:9200/nori/_analyze?pretty -H 'Content-Type: application/json' -d '{"analyzer": "text", "text" : "εἰμί", "attributes" : ["leftPOS"], "explain": true }'

{
  "detail" : {
    "custom_analyzer" : false,
    "analyzer" : {
      "name" : "text",
      "tokens" : [
        {
          "token" : "ε",
          "start_offset" : 0,
          "end_offset" : 1,
          "type" : "word",
          "position" : 0,
          "leftPOS" : "SL(Foreign language)"
        },
        {
          "token" : "ἰ",
          "start_offset" : 1,
          "end_offset" : 2,
          "type" : "word",
          "position" : 1,
          "leftPOS" : "SY(Other symbol)"
        },
        {
          "token" : "μί",
          "start_offset" : 2,
          "end_offset" : 4,
          "type" : "word",
          "position" : 2,
          "leftPOS" : "SL(Foreign language)"
        }
      ]
    }
  }


curl -sk localhost:9200/nori/_analyze?pretty -H 'Content-Type: application/json' -d '{"analyzer": "text", "text" : "ka̠k̚t͡ɕ͈a̠k̚", "attributes" : ["leftPOS"], "explain": true }'

{
  "detail" : {
    "custom_analyzer" : false,
    "analyzer" : {
      "name" : "text",
      "tokens" : [
        {
          "token" : "ka",
          "start_offset" : 0,
          "end_offset" : 2,
          "type" : "word",
          "position" : 0,
          "leftPOS" : "SL(Foreign language)"
        },
        {
          "token" : "̠",
          "start_offset" : 2,
          "end_offset" : 3,
          "type" : "word",
          "position" : 1,
          "leftPOS" : "SY(Other symbol)"
        },
        {
          "token" : "k",
          "start_offset" : 3,
          "end_offset" : 4,
          "type" : "word",
          "position" : 2,
          "leftPOS" : "SL(Foreign language)"
        },
        {
          "token" : "̚",
          "start_offset" : 4,
          "end_offset" : 5,
          "type" : "word",
          "position" : 3,
          "leftPOS" : "SY(Other symbol)"
        },
        {
          "token" : "t",
          "start_offset" : 5,
          "end_offset" : 6,
          "type" : "word",
          "position" : 4,
          "leftPOS" : "SL(Foreign language)"
        },
        {
          "token" : "͡ɕ͈",
          "start_offset" : 6,
          "end_offset" : 9,
          "type" : "word",
          "position" : 5,
          "leftPOS" : "SY(Other symbol)"
        },
        {
          "token" : "a",
          "start_offset" : 9,
          "end_offset" : 10,
          "type" : "word",
          "position" : 6,
          "leftPOS" : "SL(Foreign language)"
        },
        {
          "token" : "̠",
          "start_offset" : 10,
          "end_offset" : 11,
          "type" : "word",
          "position" : 7,
          "leftPOS" : "SY(Other symbol)"
        },
        {
          "token" : "k",
          "start_offset" : 11,
          "end_offset" : 12,
          "type" : "word",
          "position" : 8,
          "leftPOS" : "SL(Foreign language)"
        },
        {
          "token" : "̚",
          "start_offset" : 12,
          "end_offset" : 13,
          "type" : "word",
          "position" : 9,
          "leftPOS" : "SY(Other symbol)"
        }
      ]
    }
  }
}

curl -sk localhost:9200/nori/_analyze?pretty -H 'Content-Type: application/json' -d '{"analyzer": "text", "text" : "Ба̀лтичко̄", "attributes" : ["leftPOS"], "explain": true }'

{
  "detail" : {
    "custom_analyzer" : false,
    "analyzer" : {
      "name" : "text",
      "tokens" : [
        {
          "token" : "ба",
          "start_offset" : 0,
          "end_offset" : 2,
          "type" : "word",
          "position" : 0,
          "leftPOS" : "SL(Foreign language)"
        },
        {
          "token" : "̀",
          "start_offset" : 2,
          "end_offset" : 3,
          "type" : "word",
          "position" : 1,
          "leftPOS" : "SY(Other symbol)"
        },
        {
          "token" : "лтичко",
          "start_offset" : 3,
          "end_offset" : 9,
          "type" : "word",
          "position" : 2,
          "leftPOS" : "SL(Foreign language)"
        },
        {
          "token" : "̄",
          "start_offset" : 9,
          "end_offset" : 10,
          "type" : "word",
          "position" : 3,
          "leftPOS" : "SY(Other symbol)"
        }
      ]
    }
  }
}

curl -sk localhost:9200/nori/_analyze?pretty -H 'Content-Type: application/json' -d '{"analyzer": "text", "text" : "don'"'"'t", "attributes" : ["leftPOS"], "explain": true }'

{
  "detail" : {
    "custom_analyzer" : false,
    "analyzer" : {
      "name" : "text",
      "tokens" : [
        {
          "token" : "don",
          "start_offset" : 0,
          "end_offset" : 3,
          "type" : "word",
          "position" : 0,
          "leftPOS" : "SL(Foreign language)"
        },
        {
          "token" : "t",
          "start_offset" : 4,
          "end_offset" : 5,
          "type" : "word",
          "position" : 1,
          "leftPOS" : "SL(Foreign language)"
        }
      ]
    }
  }
}


curl -sk localhost:9200/nori/_analyze?pretty -H 'Content-Type: application/json' -d '{"analyzer": "text", "text" : "don’t", "attributes" : ["leftPOS"], "explain": true }'

{
  "detail" : {
    "custom_analyzer" : false,
    "analyzer" : {
      "name" : "text",
      "tokens" : [
        {
          "token" : "don",
          "start_offset" : 0,
          "end_offset" : 3,
          "type" : "word",
          "position" : 0,
          "leftPOS" : "SL(Foreign language)"
        },
        {
          "token" : "t",
          "start_offset" : 4,
          "end_offset" : 5,
          "type" : "word",
          "position" : 1,
          "leftPOS" : "SL(Foreign language)"
        }
      ]
    }
  }
}


curl -sk localhost:9200/nori/_analyze?pretty -H 'Content-Type: application/json' -d '{"analyzer": "text", "text" : "אוֹג׳וּ", "attributes" : ["leftPOS"], "explain": true }'

{
  "detail" : {
    "custom_analyzer" : false,
    "analyzer" : {
      "name" : "text",
      "tokens" : [
        {
          "token" : "אוֹג",
          "start_offset" : 0,
          "end_offset" : 4,
          "type" : "word",
          "position" : 0,
          "leftPOS" : "SY(Other symbol)"
        },
        {
          "token" : "וּ",
          "start_offset" : 5,
          "end_offset" : 7,
          "type" : "word",
          "position" : 1,
          "leftPOS" : "SY(Other symbol)"
        }
      ]
    }
  }
}
```

B. arae-a as middle dot

```
curl -sk localhost:9200/nori/_analyze?pretty -H 'Content-Type: application/json' -d '{"analyzer": "text", "text" : "도로ㆍ지반ㆍ수자원ㆍ건설환경ㆍ건축ㆍ화재설비연구", "attributes" : ["leftPOS"], "explain": true }'

{
  "detail" : {
    "custom_analyzer" : false,
    "analyzer" : {
      "name" : "text",
      "tokens" : [
        {
          "token" : "도로",
          "start_offset" : 0,
          "end_offset" : 2,
          "type" : "word",
          "position" : 0,
          "leftPOS" : "NNG(General Noun)"
        },
        {
          "token" : "ㆍ지반ㆍ수자원ㆍ건설환경ㆍ건축ㆍ화재설비연구",
          "start_offset" : 2,
          "end_offset" : 24,
          "type" : "word",
          "position" : 1,
          "leftPOS" : "UNKNOWN(Unknown)"
        }
      ]
    }
  }
}
```

C. soft hyphens and zero-width non-joiners

```
curl -sk localhost:9200/nori/_analyze?pretty -H 'Content-Type: application/json' -d '{"analyzer": "text", "text" : "hyphen­ation", "attributes" : ["leftPOS"], "explain": true }'

{
  "detail" : {
    "custom_analyzer" : false,
    "analyzer" : {
      "name" : "text",
      "tokens" : [
        {
          "token" : "hyphen",
          "start_offset" : 0,
          "end_offset" : 6,
          "type" : "word",
          "position" : 0,
          "leftPOS" : "SL(Foreign language)"
        },
        {
          "token" : "ation",
          "start_offset" : 7,
          "end_offset" : 12,
          "type" : "word",
          "position" : 1,
          "leftPOS" : "SL(Foreign language)"
        }
      ]
    }
  }
}

curl -sk localhost:9200/nori/_analyze?pretty -H 'Content-Type: application/json' -d '{"analyzer": "text", "text" : "بازی‌های", "attributes" : ["leftPOS"], "explain": true }'

{
  "detail" : {
    "custom_analyzer" : false,
    "analyzer" : {
      "name" : "text",
      "tokens" : [
        {
          "token" : "بازی",
          "start_offset" : 0,
          "end_offset" : 4,
          "type" : "word",
          "position" : 0,
          "leftPOS" : "SY(Other symbol)"
        },
        {
          "token" : "های",
          "start_offset" : 5,
          "end_offset" : 8,
          "type" : "word",
          "position" : 1,
          "leftPOS" : "SY(Other symbol)"
        }
      ]
    }
  }
}

```

D. 그레이맨 generates empty token

```
curl -sk localhost:9200/nori/_analyze?pretty -H 'Content-Type: application/json' -d '{"analyzer": "text", "text" : "그레이맨", "attributes" : ["leftPOS"], "explain": true }'

{
  "detail" : {
    "custom_analyzer" : false,
    "analyzer" : {
      "name" : "text",
      "tokens" : [
        {
          "token" : "그레이",
          "start_offset" : 1,
          "end_offset" : 4,
          "type" : "word",
          "position" : 0,
          "leftPOS" : "NNG(General Noun)"
        },
        {
          "token" : "",
          "start_offset" : 4,
          "end_offset" : 4,
          "type" : "word",
          "position" : 1,
          "leftPOS" : "NNG(General Noun)"
        }
      ]
    }
  }
}
```

E. 튜토리얼 has a space added during tokenization

```
curl -sk localhost:9200/nori/_analyze?pretty -H 'Content-Type: application/json' -d '{"analyzer": "text", "text" : "튜토리얼", "attributes" : ["leftPOS"], "explain": true }'

{
  "detail" : {
    "custom_analyzer" : false,
    "analyzer" : {
      "name" : "text",
      "tokens" : [
        {
          "token" : "튜토리얼 ",
          "start_offset" : 0,
          "end_offset" : 4,
          "type" : "word",
          "position" : 0,
          "leftPOS" : "NNG(General Noun)"
        }
      ]
    }
  }
}

```

**Comment by colings86** [comment]
@jimczi could you take a look at this one?

**Comment by jimczi** [comment]
Thanks @Trey314159 for the detailed report ! This is really appreciated. 

> A. Tokens are split on different character POS types (which seem to not quite line up with Unicode character blocks), which leads to weird results for non-CJK tokens:

That's the rule we follow for unknown words. Though we don't have a specific rule for combining diacritical marks, they are detected as `SYMBOL` because it's the default class for unknown characters. We could probably mark them as `ALPHA` in order to group them with latin characters but we also separate Cyrillic from latin chars... I like the idea of adding a character filter to remove them since we don't need precision on foreign languages, maybe we could add this filter automatically in the `analyzer` ?

> Мoscow (with a Cyrillic М and the rest in Latin) is tokenized as м + oscow

That's the rule we follow, we distinguish Latin from Cyrillic and split unknown words that mixes alphabets. I don't know Cyrillic at all but I guess that we could get rid of this rule if it's common to mix these characters class in existing words.

> The character "arae-a" (ㆍ, U+318D) is sometimes used instead of a middle dot (·, U+00B7) for lists. When the arae-a is used, everything after the first one ends up in one giant token. 도로ㆍ지반ㆍ수자원ㆍ건설환경ㆍ건축ㆍ화재설비연구 is tokenized as 도로 + ㆍ지반ㆍ수자원ㆍ건설환경ㆍ건축ㆍ화재설비연구.

I agree this is a bug,  the dictionary we use doesn't contain the "arae-a" character as a separator so it is considered as a simple hangul character. The workaround as you noticed is to remap this character before tokenization but I'll fill a bug report for [mecab-ko-dic]([https://bitbucket.org/eunjeon/mecab-ko-dic).

> C. Nori splits tokens on soft hyphens (U+00AD) and zero-width non-joiners (U+200C), splitting tokens that should not be split.

I don't see why it's an issue. Soft hyphens indicates a word boundary (or at least a boundary that can be used to split a very long word) so I don't think we should change the default behavior. You can (as you noticed) remap these characters if you don't want to split.

> D. Analyzing 그레이맨 generates an extra empty token after it. There may be others, but this is the only one I've found. Work around: at a min length token filter with a minimum length of 1.

> E. Analyzing 튜토리얼 generates a token with an extra space at the end of it. There may be others, but this is the only one I've found. No work around needed, I guess, since this is only the internal representation of the token. I'm not sure if it has any negative effects.

That's a bug, thanks ! The `meca-ko-dic` contains some invalid rules that we should ignore or normalize (we should trim tokens when we read them and remove the empty ones).

Thanks again for reporting and testing this analyzer. However the implementation is in a Lucene module so we should continue this discussion there. Would you mind opening a new issue in [Lucene](https://issues.apache.org/jira/projects/LUCENE/issues) with the same description ? I can do it if you don't want to but if we fix something it will be in Lucene.

**Comment by Trey314159** [comment]
> I like the idea of adding a character filter to remove them since we don't need precision on foreign languages, maybe we could add this filter automatically in the `analyzer` ?

For use on Wikipedia, I usually set up filters to remove most combining diacritics and to normalizer characters with diacritics that are not in the alphabet of the language of the wiki. (Swedish really does need å, ä, and ö, but doesn't really need ß and ł.)

For a Korean analyzer, normalizing diacritics for non-Korean text sounds good to me.

> > Мoscow (with a Cyrillic М and the rest in Latin) is tokenized as м + oscow
> 
> That's the rule we follow, we distinguish Latin from Cyrillic and split unknown words that mixes alphabets. I don't know Cyrillic at all but I guess that we could get rid of this rule if it's common to mix these characters class in existing words.

Depends on your definition of common. There are intentional cases like the band _KoЯn_ and _NGiИX_ software. It's also common enough on Wikipedias when people are transliterating or translating text and they don't change the homoglyphs (i.e., they have _Москва,_ hit delete 4 or 5 times, and then keep typing), or they need a less common character (like Cyrillic і, ј, or ѕ, or accented ѐ), and they substitute the handier Latin versions (i, j, s, è). I see it a lot, but I also go looking for them. `;)`

> > The character "arae-a" (ㆍ, U+318D) is sometimes used instead of a middle dot (·, U+00B7) for lists. When the arae-a is used, everything after the first one ends up in one giant token. 도로ㆍ지반ㆍ수자원ㆍ건설환경ㆍ건축ㆍ화재설비연구 is tokenized as 도로 + ㆍ지반ㆍ수자원ㆍ건설환경ㆍ건축ㆍ화재설비연구.
> 
> I agree this is a bug, the dictionary we use doesn't contain the "arae-a" character as a separator so it is considered as a simple hangul character. The workaround as you noticed is to remap this character before tokenization but I'll fill a bug report for mecab-ko-dic.

Thanks!

> > C. Nori splits tokens on soft hyphens (U+00AD) and zero-width non-joiners (U+200C), splitting tokens that should not be split.
> 
> I don't see why it's an issue. Soft hyphens indicates a word boundary (or at least a boundary that can be used to split a very long word) so I don't think we should change the default behavior. You can (as you noticed) remap these characters if you don't want to split.

[Soft hyphens](https://en.wikipedia.org/wiki/Soft_hyphen) and [zero-width non-joiners](https://en.wikipedia.org/wiki/Zero-width_non-joiner) (zwnj) are typographic marks that have no semantic meaning. And since they are invisible, people often don't know they are there. As I mentioned in the other ticket, _hyphenation_ and _hyphen­ation_ look the same, but are not. Zwnj's prevent ligatures that shouldn't occur automatically, like across morpheme boundaries. So hardcore English typography nerds might use it to block rendering of the ffl ligature, ﬄ, in words like _offload_ or _cufflink_; they get used in Arabic a lot more, though.

> > D. Analyzing 그레이맨 generates an extra empty token after it. There may be others, but this is the only one I've found. Work around: at a min length token filter with a minimum length of 1.
> 
> > E. Analyzing 튜토리얼 generates a token with an extra space at the end of it. There may be others, but this is the only one I've found. No work around needed, I guess, since this is only the internal representation of the token. I'm not sure if it has any negative effects.
> 
> That's a bug, thanks ! The `meca-ko-dic` contains some invalid rules that we should ignore or normalize (we should trim tokens when we read them and remove the empty ones).
>
> Thanks again for reporting and testing this analyzer. However the implementation is in a Lucene module so we should continue this discussion there. Would you mind opening a new issue in [Lucene](https://issues.apache.org/jira/projects/LUCENE/issues) with the same description ? I can do it if you don't want to but if we fix something it will be in Lucene.

I've refiled [the ticket](https://issues.apache.org/jira/browse/LUCENE-8524) there. Thanks!

**Comment by jimczi** [comment]
The Lucene [issue](https://issues.apache.org/jira/browse/LUCENE-8548) is now resolved so I am closing this one. The Korean tokenizer will no longer split unknown words on combining diacritics and will detect script boundaries more accurately with java UnicodeScript. 
However we'll not merge different scripts together (cyrillic and latin for instance), this is not in the specifications and would complicate the handling of unknown words with custom rules. The same applies for special punctuations split (e.g. `don't`) that depends on the type of characters that appear before and after the `'`.

**Comment by Trey314159** [comment]
Thanks, @jimczi!
