### ISSUE TITLE
elasticsearch 6.4.2-1 installations fails on Fedora 28 with "Exception in thread "main" java.lang.NoSuchMethodError: org.elasticsearch.cli.Command.<init>(Ljava/lang/String;)V"

### ISSUE THREAD

**Issue by william8000** [elastic/elasticsearch#34281]
**Describe the feature**: Install elasticsearch 6 on Fedora 28

I updated my laptop from Fedora 27 to 28. I had been using elasticsearch 5 on Fedora 27, but due to an elasticsearch packaging issue https://github.com/elastic/elasticsearch/issues/34087 the update could not install elasticsearch 5 on Fedora 28. I tried installing elasticsearch 6, and it failed with the log below.

```
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                         1/1
  Running scriptlet: elasticsearch-6.4.2-1.noarch                                                                                                                            1/1
  Installing       : elasticsearch-6.4.2-1.noarch                                                                                                                            1/1
  Running scriptlet: elasticsearch-6.4.2-1.noarch                                                                                                                            1/1
warning: /etc/elasticsearch/elasticsearch.yml created as /etc/elasticsearch/elasticsearch.yml.rpmnew
warning: /etc/elasticsearch/jvm.options created as /etc/elasticsearch/jvm.options.rpmnew
warning: /etc/elasticsearch/log4j2.properties created as /etc/elasticsearch/log4j2.properties.rpmnew
warning: /etc/init.d/elasticsearch created as /etc/init.d/elasticsearch.rpmnew
warning: /etc/sysconfig/elasticsearch created as /etc/sysconfig/elasticsearch.rpmnew
warning: /usr/lib/systemd/system/elasticsearch.service created as /usr/lib/systemd/system/elasticsearch.service.rpmnew
### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
### You can start elasticsearch service by executing
 sudo systemctl start elasticsearch.service
ES_PATH_CONF must be set to the configuration path
chown: cannot access '/etc/elasticsearch/elasticsearch.keystore': No such file or directory
chmod: cannot access '/etc/elasticsearch/elasticsearch.keystore': No such file or directory
md5sum: /etc/elasticsearch/elasticsearch.keystore: No such file or directory
warning: %posttrans(elasticsearch-0:6.4.2-1.noarch) scriptlet failed, exit status 1
Non-fatal POSTTRANS scriptlet failure in rpm package elasticsearch
Non-fatal POSTTRANS scriptlet failure in rpm package elasticsearch
  Verifying        : elasticsearch-6.4.2-1.noarch                                                                                                                            1/1
  
Installed:
  elasticsearch.noarch 6.4.2-1
Complete!
```

I updated the rpmnew files (merging the yml and moving the other rpmnew files into place), but starting elasticsearch gives an error.

```
/usr/share/elasticsearch/bin/elasticsearch
Exception in thread "main" java.lang.NoSuchMethodError: org.elasticsearch.cli.Command.<init>(Ljava/lang/String;)V
        at org.elasticsearch.cli.EnvironmentAwareCommand.<init>(EnvironmentAwareCommand.java:39)
        at org.elasticsearch.bootstrap.Elasticsearch.<init>(Elasticsearch.java:53)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:83)  
```

This was with
```
java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b15)
OpenJDK 64-Bit Server VM (build 25.181-b15, mixed mode)
```

I suspect that NoSuchMethodError is related to the version of java, so I updated to 10, but that did not help.

```
sudo dnf install java-openjdk

alternatives --config java
switch from java-1.8.0-openjdk.x86_64 to java-openjdk.x86_64

java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13)
OpenJDK 64-Bit Server VM (build 10.0.2+13, mixed mode)

/usr/share/elasticsearch/bin/elasticsearch
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: UseAVX=2 is not supported on this CPU, setting it to UseAVX=1
Exception in thread "main" java.lang.NoSuchMethodError: org.elasticsearch.cli.Command.<init>(Ljava/lang/String;)V
        at org.elasticsearch.cli.EnvironmentAwareCommand.<init>(EnvironmentAwareCommand.java:39)
        at org.elasticsearch.bootstrap.Elasticsearch.<init>(Elasticsearch.java:53)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:83)  
```

Then I tried updating to Oracle java 8, but that did not help either.

```
dnf install jdk-8u181-linux-x64.rpm

alternatives --config java
switch to /usr/java/jdk1.8.0_181-amd64/jre/bin/java

java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

/usr/share/elasticsearch/bin/elasticsearch
Exception in thread "main" java.lang.NoSuchMethodError: org.elasticsearch.cli.Command.<init>(Ljava/lang/String;)V
        at org.elasticsearch.cli.EnvironmentAwareCommand.<init>(EnvironmentAwareCommand.java:39)
        at org.elasticsearch.bootstrap.Elasticsearch.<init>(Elasticsearch.java:53)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:83)  
```

Is there anything left over from elasticsearch 5 that the update from Fedora 27 to 28 could have left behind when it removed elasticsearch 5?

**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.2-1

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b15)
OpenJDK 64-Bit Server VM (build 25.181-b15, mixed mode)

openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13)
OpenJDK 64-Bit Server VM (build 10.0.2+13, mixed mode)

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):

Linux scslaptop37.scs.com 4.18.10-200.fc28.x86_64 #1 SMP Wed Sep 26 09:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

/usr/share/elasticsearch/bin/elasticsearch
fails with
Exception in thread "main" java.lang.NoSuchMethodError: org.elasticsearch.cli.Command.<init>(Ljava/lang/String;)V
        at org.elasticsearch.cli.EnvironmentAwareCommand.<init>(EnvironmentAwareCommand.java:39)
        at org.elasticsearch.bootstrap.Elasticsearch.<init>(Elasticsearch.java:53)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:83)

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. install elasticsearch6 on Fedora 28, either by downloading the rpm or by adding the repository and installing with dnf
 2. try to start elasticsearch
 3.

**Provide logs (if relevant)**:

**Comment by rjernst** [comment]
Thanks very much for your interest in Elasticsearch.

This does not appear to be a bug. The reason I say this is because our build are green right now, so this failure is likely environmental. In particular, you likely have a mix of elasticsearch 5 and 6 jars, which could cause an error like this. We'd like to direct these kinds of things to the forums. If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.

**Comment by william8000** [comment]
Thanks for suggesting a mix of versions. I removed elasticsearch 6 with dnf, and then I ran `find / -name '*elasticsearch*'`, and I still had elasticsearch 5 files in `/usr/share/elasticsearch`. I removed that directory and re-installed elasticsearch 6, and it is working now! I just need to update my application for the api changes.
