### ISSUE TITLE
license expiration doc clarification

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/elasticsearch#34289]
According to https://www.elastic.co/guide/en/elastic-stack-overview/current/license-expiration.html#_security, it mentions below and it is not too clear what it means in 2nd point.
Can we word it better with more focus on security?

- Cluster  health, cluster stats and indices stats operations will be blocked
- All data operations (read and write) will continue to work

**Comment by jasontedor** [comment]
Would you take this to the elastic/stack-docs repository please, that is where these docs are maintained.
