### ISSUE TITLE
Multi Index Expression resolution discrepancy with Security

### ISSUE THREAD

**Issue by albertzaharovits** [elastic/elasticsearch#34291]
Some APIs that work with indices can specify a [Multi Index Expression](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html) instead of a single concrete index/alias name.
The Security plugin, during the authorization process (before the processing of the request) will evaluate this expression. Moreover, if the authorization succeed, the Security plugin rewrites the expression as a list of concrete indices and aliases. This is done because the code handling the request also has the ability to evaluate expressions (it has to, the functionality exists in vanilla ES), but it will do it "unconstrained" by the authenticated user's visibility scope.
Therefore, the expression could be evaluated differently with and without the Security plugin **but only if the difference stems from a narrowed visibility of the authenticated user.**

This issue illustrates a discrepancy in the expression evaluation when user visibility is not of concern.
I say it is a bug. The following example illustrates it:

```
#setup
curl -X PUT "localhost:9200/a"
curl -X PUT "localhost:9200/b" -H "Content-Type: application/json" -d'
{
  "aliases": {
    "aa": {}
  }
}
'

# without Security plugin
curl -X GET "localhost:9200/a*,-aa?pretty"
{
  "a" : {
    "aliases" : { },
    "mappings" : { },
    "settings" : {
      "index" : {
        "creation_date" : "1538633629102",
        "number_of_shards" : "1",
        "number_of_replicas" : "1",
        "uuid" : "Y6MmUk9ATKOEM8uOoG8X4A",
        "version" : {
          "created" : "7000001"
        },
        "provided_name" : "a"
      }
    }
  },
  "b" : {
    "aliases" : {
      "aa" : { }
    },
    "mappings" : { },
    "settings" : {
      "index" : {
        "creation_date" : "1538633726513",
        "number_of_shards" : "1",
        "number_of_replicas" : "1",
        "uuid" : "eeLOS3s6Si6qPx0OFEVEwA",
        "version" : {
          "created" : "7000001"
        },
        "provided_name" : "b"
      }
    }
  }
}

# with Security plugin
curl -u elastic-admin:elastic-password -X GET "localhost:9200/a*,-aa?pretty"
{
  "a" : {
    "aliases" : { },
    "mappings" : { },
    "settings" : {
      "index" : {
        "creation_date" : "1538634279689",
        "number_of_shards" : "1",
        "number_of_replicas" : "1",
        "uuid" : "rYtgAvq_QmWlGYlNsUpnzA",
        "version" : {
          "created" : "7000001"
        },
        "provided_name" : "a"
      }
    }
  }
}
```
This is a particular example, and in general this manifests when you have **wildcards that
expand to aliases and then some of these aliases are excluded.**

The different actors at play are `IndicesAndAliasesResolver#replaceWildcardsWithAuthorizedIndices`
and `IndexNameExpressionResolver#innerResolver`. They both should do *roughly* the same thing.
**I believe, that the code in core is broken and that actually the Security plugin rectifies it.**

I think the code in core is broken because alias exclusion after alias wildcards does not work. Yet wildcard alias exclusion works is fine.
Given the previous example, the following works just just fine for both Security on/off:
```
curl -X GET "localhost:9200/a*,-aa*?pretty"
{
  "a" : {
    "aliases" : { },
    "mappings" : { },
    "settings" : {
      "index" : {
        "creation_date" : "1538639931136",
        "number_of_shards" : "1",
        "number_of_replicas" : "1",
        "uuid" : "l1cHq5B8RSeUhOnz2bSw5g",
        "version" : {
          "created" : "7000001"
        },
        "provided_name" : "a"
      }
    }
  }
}
```
The problem is that inclusion wildcards of aliases are expanded
https://github.com/elastic/elasticsearch/blob/74993fe1519b11ae45666ab7af31d1303a7633a5/server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java#L687
but the explicit wildcard exclusion is not
https://github.com/elastic/elasticsearch/blob/74993fe1519b11ae45666ab7af31d1303a7633a5/server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java#L680

I have labeled it as a Security issue because vanilla ES behavior can be considered authoritative, but **I think the problem really is in the core code.**

CC @javanna

**Comment by javanna** [comment]
I agree @albertzaharovits , looks like a bug in the Elasticsearch indices resolution code, I guess introduced with the recent addition of aliases pattern exclusions. Great catch.

**Comment by albertzaharovits** [comment]
Thank you @javanna ! I will relabel.

**Comment by dakrone** [comment]
This has been open for quite a while, and we haven't made much progress on this due to focus in other areas. For now I'm going to close this as something we aren't planning on implementing. We can re-open it later if needed.
