### ISSUE TITLE
Review TokenFilterFactory.getSynonymFilter() implementations

### ISSUE THREAD

**Issue by romseygeek** [elastic/elasticsearch#34298]
#33702 introduced a new method on the `TokenFilterFactory` interface allowing filters to return specialized versions of themselves for synonym parsing.  Currently only the `multiplexer` implements this, to return the original token.  We should review all the filter factories shipped with elasticsearch to see if any others need changing.

[] AsciiFoldingFilter -> should return only the folded token
[] CJKBigramFilter -> ignore if emitUnigrams = true
[] CommonGramsTokenFilter -> ignore
[] CompoundWordTokenFilterBase -> ??
[] EdgeNGramTokenFilter -> ??
[] Fingerprint & MinHash -> shouldn't be used with synonyms anyway...
[] Keyword repeat -> ignore
[] NGramTokenFilter -> ??
[] Shingle -> shouldn't output unigrams
[] SynonymGraph & Synonym -> should we allow multiple synonym chains?
[] Phonetic -> ignore
[] WordDelimiterGraph & WordDelimiter -> ??

**Comment by romseygeek** [comment]
Having thought about this some more, I think we should also ignore the ngram and shingle filters here, as synonyms generally are applied to whole tokens.  Similarly, Synonym and SynonymGraph should also be ignored, because applying synonyms to a synonym file will make the end result very difficult to reason about.

I can see arguments both ways for WordDelimiterFilter and CompoundWordTokenFilterBase, but I think the simplest solution will be to ignore both for now.  We can add a setting in future to allow them to be used when parsing synonyms if there's an obvious user need for it.

**Comment by matthuhiggins** [comment]
I was using the word delimiter filter in conjunction with filters, and I am unsure how to upgrade to 7.x with this change:

```
curl -X PUT "localhost:9200/my_index" -H 'Content-Type: application/json' -d'
{
  "settings": {
    "analysis": {
      "analyzer": {
        "company_name_analyzer": {
          "type":      "custom", 
          "tokenizer": "standard",
          "filter": [
            "company_name_camel_case",
            "lowercase",
            "company_name_abbreviations"
          ]
        }
      },
      "filter": {
        "company_name_abbreviations": {
          "type": "synonym",
          "synonyms": ["co-op => cooperative", "corp,corporation"]
        },
        "company_name_camel_case": {
          "type": "word_delimiter"
        }
      }
    }
  }
}'
```
I need the word delimiter filter to run _before_ the lowercase filter, so that "AcmeTech" is filtered to `["Acme", "Tech"]`. I need the lowercase filter to run before the synonym filter so that "Corp" is tokenized to `["corporation"]`.

"AcmeTech Corp" is an example of a business name to search against. The term "Acme" should match to AcmeCorp, and the term "Corporation" should match to "Corp".

```
curl -X POST "localhost:9200/my_index/_analyze" -H 'Content-Type: application/json' -d'
{
  "analyzer": "company_name_analyzer",
  "text": "AcmeTech Corp"
}'

I am unsure how to structure this analyzer for 7.x. I do not need the word delimiter filter to run a "synonym filter", but I need it to run before the lowercase filter. I can take this to the message boards, but currently this is less of a question or more a concern that my capabilities are lost.

**Comment by romseygeek** [comment]
You can use the multiplexer filter to build two parallel filter chains:
```
"filter" : {
  "company_name" : {
    "type" : "multiplexer",
    "filters" : [ "company_name_camel_case, lowercase", "lowercase, company_name_abbreviations" ]
  }
}
```

**Comment by matthuhiggins** [comment]
`multiplexer` is brilliant. However, I am running into an "offsets must not go backwards" error when using it with 6.8. I put exact repro steps into this gist: https://gist.github.com/matthuhiggins/b5139bfade363744dbad942e2b44f90d

There is a new `adjust_offsets: false` option in 7.0 but not in 6.8.

If there is no obvious answer, should I make a separate github issue or post to the message board?

**Comment by romseygeek** [comment]
It's an annoying limitation in 6.8, I know.  You can get round it by reversing the order of the `filters` list:
```
"filters" : [ 
  "lowercase, company_name_abbreviations",
  "company_name_camel_case, lowercase" ]
```

**Comment by matthuhiggins** [comment]
Putting the synonym filter inside a multiplexer changes its behavior when the input (LHS) synonym is multiple tokens (ES v6.8):

https://gist.github.com/matthuhiggins/16b5d29c2ea0bb4a9e21f64268b6865f

Everything you've answered so far has put me in a step in the right direction. Thanks for everything so far!
