### ISSUE TITLE
Read only index templates silently ignore updates

### ISSUE THREAD

**Issue by colings86** [elastic/elasticsearch#34308]
This was first raised by @bmcconaghy.

**Steps to reproduce:**
1. try to modify a read nly index template such as the `logstash-index-template`:
```
PUT _template/logstash-index-template
{
   “order”: 0,
   “index_patterns”: [
     “.logstash”
   ],
   “settings”: {
       “number_of_shards”: 10,
       “auto_expand_replicas”: 0,
       “codec”: “best_compression”
     }
   }
}
```
2. Observe that the response is `acknowledged: true`
3. Get the same template:
```
GET _template/logstash-index-template
```
4. Observe that the template has not changed in the above request
5. Try to delete the template:
```
DELETE _template/logstash-index-template
```
6. Observe that the response is `acknowledged: true`
7. Try to get the template:
```
GET _template/logstash-index-template
```
8. Observe that the template still exists.

**Expected results:**
If the template is read only then we should return an error response on PUT or DELETE explaining that the template cannot be modified

It would also be useful to have an indication on the template that its read-only

**Comment by colings86** [comment]
It looks like the Logstash plugin registers a template upgrader that overwrites any changes to the template on any cluster state update. @bleskes is going to investigate what we should do here

**Comment by bmcconaghy** [comment]
thx for the update @colings86

**Comment by bmcconaghy** [comment]
This continues to be an issue on master @bleskes.

**Comment by dakrone** [comment]
@colings86 can you add more information to this or close it if it's no longer appropriate? I tried to reproduce this with ES+LS 7.3.1 and I was able to change the template logstash put in place with no problems. Is there a special "read only template" setting that I'm not aware of?

**Comment by gwbrown** [comment]
@dakrone This doesn't actually have to do with anything Logstash installs, it's the plugin which installs the index template for Logstash central management which is the issue. 

In particular, it overrides this method:
https://github.com/elastic/elasticsearch/blob/5bc3b7f741a4c60e4ef4d81314951532654bf8ee/server/src/main/java/org/elasticsearch/plugins/Plugin.java#L191-L205

Like so:
https://github.com/elastic/elasticsearch/blob/a8530c55314ae9acb99998638db3247ff00de98d/x-pack/plugin/logstash/src/main/java/org/elasticsearch/xpack/logstash/Logstash.java#L62-L71

Which always overwrites the index template - I think that's the issue.

(I noticed this while making unrelated changes to this plugin, but had completely forgotten about it until just now.)

**Comment by dakrone** [comment]
Thanks @gwbrown, that adds helpful context around this issue

**Comment by dakrone** [comment]
We now indicate that templates are managed using metadata, and the UI exposes this information as well. Closing this for now.
