### ISSUE TITLE
wait_for_completion with s3 plugin no longer waits (6.4)

### ISSUE THREAD

**Issue by abridgett** [elastic/elasticsearch#34343]
ES: 6.4.2
plugins: repository-s3

After upgrading from 5.4.2 to 6.4.2, our backup script started to fail.

Firstly curl reports an empty reply from the server, secondly, wait_for_completion seems to be ignored I suspect these two are related.   Checking the status of the backup shows "STARTED" as the current status which isn't listed in  https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html

The master logs show the backup starting and finishing successfully (and the status does change from STARTED to SUCCESS).  No other logs from nodes.

This is a cluster in K8s (client, data, master nodes) but can't see any problems with e.g. service load balancing (and it was fine in 5.4.2)

For now I'm just going to poll the status for a while until it says SUCCESS but this looks like perhaps a bug somewhere (it could very well be our setup, but thought it worth raising in case others were hitting this too).

**Comment by ywelsch** [comment]
> Firstly curl reports an empty reply from the server, secondly, wait_for_completion seems to be ignored I suspect these two are related.

Are you sending your CURL command directly to an ES server, or is this done through a proxy? It sounds as if there's a proxy that is terminating the connection before the snapshot has completed.
