### ISSUE TITLE
Discuss: Use Java 8 for reindex-from-old tests

### ISSUE THREAD

**Issue by nik9000** [elastic/elasticsearch#34341]
Right now we use Java 7 to run the "old" versions of Elasticsearch to test reindex-from-remote from old versions of Elasticsearch. Java 7 is getting harder and harder to install though. I think we could get away with using Java 8 to run these versions of Elasticsearch. We actually supported Java 8 on ES 1 and ES 2. We didn't on ES 0.90 and we're testing against that too. I expect we could get away with running 0.90 with Java 8 for these tests.

Thoughts?

**Comment by nik9000** [comment]
> Thoughts?

We could drop the test against 0.90 but I'm proud that we support reindex-from-remote from that far back to be honest.

**Comment by jasontedor** [comment]
We discussed this during our weekly discussion meeting and agreed that we should drop the JDK 7 requirement here. It will ease the burden on contributors and developers. See #34628 for a recent case of this.

I opened #34646.
