### ISSUE TITLE
Unexpected Behavior in output after firing Script to search across multiple Indices

### ISSUE THREAD

**Issue by TejasC-CS** [elastic/elasticsearch#34356]
**Elasticsearch version** (`bin/elasticsearch --version`): "6.4.2"

**Plugins installed**: No Plugins Installed

**JVM version** (`java -version`): "1.8.0_181"

**OS version** (`uname -a` if on a Unix-like system): "Windows 10 Pro"

**Description of the problem including expected versus actual behavior**: Unexpected behavior on firing rest call to search across multiple indexes using script in query.

**Steps to reproduce**:

In my case there are two indexes named model_cluster_02 and model_edge_01.
Mapping in these indexes is as follows:

"model_edge_01": {
        "mappings": {
            "em": {
                "properties": {
                    "distance": {
                        "type": "long"
                    },
                    "edge_id": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword",
                                "ignore_above": 256
                            }
                        },
                        "fielddata": true
                    },
                    "from": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword",
                                "ignore_above": 256
                            }
                        },
                        "fielddata": true
                    },
                    "to": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword",
                                "ignore_above": 256
                            }
                        },
                        "fielddata": true
                    }
                }
            }
        }
    },
    "model_cluster_02": {
        "mappings": {
            "cm_001": {
                "properties": {
                    "cluster_id": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword",
                                "ignore_above": 256
                            }
                        },
                        "fielddata": true
                    },
                    "edges": {
                        "type": "text",
                        "fields": {
                            "keyword": {
                                "type": "keyword",
                                "ignore_above": 256
                            }
                        },
                        "fielddata": true
                    },
                    "tags": {
                        "properties": {
                            "Accessories": {
                                "type": "long"
                            },
                            "Clothing": {
                                "type": "long"
                            },
                            "Female": {
                                "type": "long"
                            },
                            "Football": {
                                "type": "long"
                            },
                            "Footware": {
                                "type": "long"
                            },
                            "Formal": {
                                "type": "long"
                            },
                            "Hockey": {
                                "type": "long"
                            },
                            "Male": {
                                "type": "long"
                            },
                            "Sports": {
                                "type": "long"
                            },
                            "Tennis": {
                                "type": "long"
                            }
                        }
                    }
                }
            }
        }
    } 

As you can see "fielddata" is set to true to use values of those particular fields in script.
To search across multiple indexes, we fire rest call to elasticsearch like:
GET/model_edge_01,model_cluster_02/_search

After firing this rest call we'll get results from both the indexes.
But when we write a script in query and fire it, search results are as expected in case of fields of 1st index in the URL (i.e. model_edge_01).
But we get unexpected search results in case of 2nd index(i.e. model_cluster_02).
Query, results for the fired query and expected results are as follows:
{
    "query": {
    	"bool":{
    		 	"must":[
        		   {
						"match":{
							"to":"p12"
						}
        		   },
					{
						"script" :{
						 	"script":"doc['edge_id'].value == doc['to'].value"
						}	
                	}
    		 	]
    	}
    }
}

Expected Result:
{
    "took": 9,
    "timed_out": false,
    "_shards": {
        "total": 10,
        "successful": 10,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 0,
        "max_score": null,
        "hits": []
    }
}
And we are getting the same result as model_edge_01 is the first index in url.

But in case where we'll use fields of second index in script, we get unexpected result as follows:

{
    "query": {
    	"bool":{
    		 	"must":[
        		   {
						"match":{
							"to":"p12"
						}
        		   },
					{
						"script" :{
						 	"script":"doc['tags'].value == doc['cluster_id'].value"
						}	
                	}
    		 	]
    	}
    }
}

Expected result:
{
    "took": 9,
    "timed_out": false,
    "_shards": {
        "total": 10,
        "successful": 10,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": 0,
        "max_score": null,
        "hits": []
    }
}

Result we are getting:
{
    "took": 14,
    "timed_out": false,
    "_shards": {
        "total": 10,
        "successful": 9,
        "skipped": 0,
        "failed": 1,
        "failures": [
            {
                "shard": 1,
                "index": "model_edge_01",
                "node": "J3GgjhjLTbOiRyn2RJJZAQ",
                "reason": {
                    "type": "script_exception",
                    "reason": "runtime error",
                    "script_stack": [
                        "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:81)",
                        "org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:39)",
                        "doc['tags'].value == doc['cluster_id'].value",
                        "    ^---- HERE"
                    ],
                    "script": "doc['tags'].value == doc['cluster_id'].value",
                    "lang": "painless",
                    "caused_by": {
                        "type": "illegal_argument_exception",
                        "reason": "No field found for [tags] in mapping with types []"
                    }
                }
            }
        ]
    },
    "hits": {
        "total": 0,
        "max_score": null,
        "hits": []
    }
}

**Comment by rjernst** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

As a starter to finding a solution to your problem, note that the `tags` field does not exist in your first index. There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
