### ISSUE TITLE
Dependency issue on rest high level client (version higher than 6.4.0)

### ISSUE THREAD

**Issue by sujieim** [elastic/elasticsearch#34360]
ClassNotFoundException error occurs when importing rest-high-level-client on versions higher than 6.4.0.

As said in the document(https://www.elastic.co/guide/en/elasticsearch/client/java-rest/6.4/java-rest-high-getting-started-maven.html) I tried importing rest-high-level-client but had some conflicting dependency issues.

Here is my gradle dependency statement:
`compile 'org.elasticsearch.client:elasticsearch-rest-high-level-client:6.4.0'`

and the result being 
`Caused by: java.lang.ClassNotFoundException: org.elasticsearch.common.xcontent.DeprecationHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 53 more
`

which seems it was caused by a lower version of elasticsearch(5.6.9 here) being included in my libraries which I haven't declared in my build.gradle.. 
![image](https://user-images.githubusercontent.com/25717142/46609760-d7e29c00-cb43-11e8-835d-58c8a619021a.png)

This problem is re-occuring from issue  #26959 which is already closed but still unresolved. 

I could fix it as it says by declaring elasticsearch with the exact same version of your rest client, such as `
compile 'org.elasticsearch.client:elasticsearch-rest-high-level-client:6.4.0'
compile 'org.elasticsearch:elasticsearch:6.4.0'`

Please double check this dependency issue. Thanks.

**Comment by vladimirdolzhenko** [comment]
Could you please provide a full gradle dependencies list for you app ?

**Comment by rjernst** [comment]
This is a bug that was introduced in 6.4.0 in the pom for the HLRC, due to refactoring to use shadow jars. This was reworked and is fixed in 6.5.0. At this time, there are no plans to backport the change to 6.4.x.

**Comment by rjernst** [comment]
Additionally, the list of dependent jars shown in the original issue comment indicate multiple versions of elasticsearch are being pulled in, creating jar hell.

**Comment by wangzhenhui1992** [comment]
Include the dependency in your dependencyManagement and add dependency to dependencies if you did not.
```
            <dependency>
                <groupId>org.elasticsearch</groupId>
                <artifactId>elasticsearch</artifactId>
                <version>6.4.2</version>
            </dependency>
```
