### ISSUE TITLE
Offline build option is not passed to inner BWC builds

### ISSUE THREAD

**Issue by DaveCTurner** [elastic/elasticsearch#34361]
At least I think this is what's happening. I am trying to run a full cluster restart IT offline.

I have a checkout of `master` (6f32f7) and of a recent 6.4 commit (7d09fb) for the BWC snapshot, but trying to run the test fails during the BWC build because it's unable to download the ML snapshot.

The lack of WiFi makes it hard to report this properly, but I can follow up when I have connectivity if needed.

**Comment by jasontedor** [comment]
This does not sound right, can you work with me for a reproduction? The reason I think is because we account for being offline: https://github.com/elastic/elasticsearch/blob/76310eb3f16110325dc7798a7a1db907f019c8e8/distribution/bwc/build.gradle#L99

**Comment by DaveCTurner** [comment]
This seems to reproduce the issue I saw, if run while offline:

```
$ git rev-parse HEAD
6f32f7138db47f503974bd7ce71f32449289a3c7
$ git rev-parse 6.x
22cb973bfd3ca6dbc52e21ebc1b7effba6274624
$ rm -rf distribution/bwc/next-minor-snapshot/build/ && git clean -dxf
$ ./gradlew --offline :qa:full-cluster-restart:v6.5.0-SNAPSHOT#oldClusterTest -Dtests.bwc.refspec.6.x=22cb973bfd3ca6dbc52e21ebc1b7effba6274624 2>&1 >testoutput.log
[...snip...]
  [bwc] FAILURE: Build failed with an exception.
  [bwc]
  [bwc] * Where:
  [bwc] Build file '/Users/davidturner/src/elasticsearch-master/distribution/bwc/next-minor-snapshot/build/bwc/checkout-6.x/x-pack/plugin/ml/cpp-snapshot/build.gradle' line: 18
  [bwc]
  [bwc] * What went wrong:
  [bwc] Execution failed for task ':x-pack:plugin:ml:cpp-snapshot:downloadMachineLearningSnapshot'.
  [bwc] > java.net.UnknownHostException: prelert-artifacts.s3.amazonaws.com
[...snip...]
```

**Comment by rjernst** [comment]
The ML cpp snapshot build is a custom task we add to our build, outside of maven artifact resolution. We do have logic in it accounting for the offline build:

```
task downloadMachineLearningSnapshot {
  onlyIf {
    // skip if ml-cpp is being built locally
    findProject(':ml-cpp') == null &&
      // skip for offline builds - just rely on the artifact already having been downloaded before here
      project.gradle.startParameter.isOffline() == false
  }
```

The code linked by @jasontedor avoids updating the bwc checkout from git, but we need to actually pass the `--offline` through to the bwc build so the ML snapshot build can act on this information.
