### ISSUE TITLE
Circuit Breaker dynamic update settings incorrect

### ISSUE THREAD

**Issue by freakingid** [elastic/elasticsearch#34368]
In the [Circuit Breaker Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/circuit-breaker.html#accounting-circuit-breaker), we say that:

> These settings can be dynamically updated on a live cluster with the cluster-update-settings API.

However, the "Accounting Requests Circuit Breaker" may not be changed dynamically.

**Attempt**
```
PUT /_cluster/settings
{
    "persistent" : {
        "indices.breaker.accounting.limit" : "70%"
    }
}
```

**Result**
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "persistent setting [indices.breaker.accounting.limit], not dynamically updateable"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "persistent setting [indices.breaker.accounting.limit], not dynamically updateable"
  },
  "status": 400
}
```

**Comment by dakrone** [comment]
This is an actual bug (the setting should be marked as dynamic and it is not), I'll open a PR to fix
