### ISSUE TITLE
Pakistan Admin Boundaries (Province, District, Tehsil) To be added in Vector Maps/Layers

### ISSUE THREAD

**Issue by junaid-gis** [elastic/elasticsearch#34375]
We are a mapping startup in Pakistan and our team is working on Elastic Search tools to search and visualize data, currently we are working on Kibana Visualizations for our country, but the lower level (provinces, districts, tehsil) vector layers are not available due to which we are unable to join our polygon data and make a region map visualization.

Since we are a mapping company, we can share these datasets with you, so that it can be made available for all users.

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:

**Comment by tvernum** [comment]
Hi @junaid-gis,

The Elasticsearch team does not operate the tile service.
Per the instructions in the footer at https://maps.elastic.co/, this issue needs to be opened in the [Kibana repository](https://github.com/elastic/kibana/issues/new)

**Comment by junaid-gis** [comment]
@tvernum thanks, i will share it over there.
