### ISSUE TITLE
DSL query slower than EDB

### ISSUE THREAD

**Issue by koala775** [elastic/elasticsearch#34388]
Here is my DSL,can I optimization
{
    index: 'xxx',
    type: 'doc',
    body: {
        "query": {
            "bool" : {
                "filter": [
                    {
                        "range": {
                            "xxx": {"gt" : start, "lte" : end}
                        }
                    }
                ]
            }
        },
        size :0,
        "aggregations": {
            "time": {
                "date_histogram" : {
                    "field" : "xxx" ,
                    "format": "yyyy-MM-dd kk:mm:ss",
                    "interval": "1m",
                    "time_zone": "Asia/Shanghai",
                    "order" : { "_key" : "desc" },
                    "offset":    "+8h",
                    "min_doc_count": 1
                },
                "aggregations": {
                    "xxx": {
                        "terms": {
                            "script": "doc['xxx.keyword'].value + '_' +doc['xxx.keyword'].value "
                        },
                        "aggregations": {
                            "xxx": {
                                "terms": {
                                    "field": "xxx"
                                },
                                "aggregations": {
                                    "xxx": {
                                        "terms": {
                                            "field": "xxx.keyword"

                                        },
                                        "aggregations": {
                                            "xxx": {
                                                "terms": {
                                                    "field": "xxx.keyword"
                                                },
                                                "aggregations": {
                                                    "xxx": {
                                                        "avg": {
                                                            "field": "xxx"
                                                        }
                                                    },
                                                    "xxx": {
                                                        "sum": {
                                                            "field": "xxx"
                                                        }
                                                    },
                                                    "xxx": {
                                                        "sum": {
                                                            "field": "xxx"
                                                        }
                                                    },
                                                    "xxx": {
                                                        "max": {
                                                            "field": "xxx"
                                                        }
                                                    },
                                                    "xxx": {
                                                        "min": {
                                                            "field": "xxx"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
};

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
