### ISSUE TITLE
where is the core source code since version 6.2?

### ISSUE THREAD

**Issue by haiying1991** [elastic/elasticsearch#34395]
In lots of earlier version before 6.2, there is a  'core' folder that contains the source code, 

![es](https://user-images.githubusercontent.com/21289834/46796604-a9e99b80-cd7f-11e8-9959-e9679752a8c3.png)

but from version 6.2，the folder doesn't exist any more and I  didn't find the core source code, anyone tell me how to find the source code since version 6.2?  Thank a lot.

**Comment by dakrone** [comment]
Hi @haiying1991,

The "core" folder has moved to the "server" folder.

In the future though, we reserve Github issues for feature requests and bug reports, so please ask at https://discuss.elastic.co instead!

**Comment by haiying1991** [comment]
> Hi @haiying1991,
> 
> The "core" folder has moved to the "server" folder.
> 
> In the future though, we reserve Github issues for feature requests and bug reports, so please ask at https://discuss.elastic.co instead!

OK，thanks a lot！
