### ISSUE TITLE
How are “active” threads counted in ElasticSearch?

### ISSUE THREAD

**Issue by maxshortzp** [elastic/elasticsearch#34406]
Hi,

I'm trying to get a better understanding of how many "active" threads are consumed by a typical search request in order to better understand why our search queues sometimes back up. I have not received a response on [the Elastic discussion forum](https://discuss.elastic.co/t/how-many-threads-does-a-typical-search-use/150934) or [StackOverflow](https://stackoverflow.com/questions/52745062/how-are-active-threads-counted-in-elasticsearch) so I thought I would try here.

When a search request fans over multiple shards, does it use threads from each node's thread pool? Would these threads be reflected in the shard's "active" thread count? 

For example, if I have 10 nodes with 1 shard each (10 shards total) and I do a search request, would this search request be reflected as:

10 "active" threads (one for each node/shard)? Or 1 "active" thread for the search request?

Thanks!

**Comment by DaveCTurner** [comment]
Hi @maxshortzp, thanks very much for your question. However, we prefer to keep Github for verified bug reports and feature requests, and the forum is a better place for this question. Unfortunately not all questions can receive a timely answer from the community, as there is no SLA and all contributors are volunteers.
