### ISSUE TITLE
es可以获取一篇文章，权重比较高的片段吗？

### ISSUE THREAD

**Issue by liufan1993** [elastic/elasticsearch#34413]
如题：es可以获取一篇文章，权重比较高的片段吗？

**Comment by colings86** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.
