### ISSUE TITLE
gradlew throws error due to RollupJobIdentifierUtils.java comment containing ">="

### ISSUE THREAD

**Issue by svanschalkwyk** [elastic/elasticsearch#34422]
In /elasticsearch-6.4.3/elasticsearch/x-pack/plugin/rollup/src/main/java/org/elasticsearch/xpack/rollup/RollupJobIdentifierUtils.java
line 224 and 255 the ">=" throws a gradle error. Changing it to "&ge;" fixes it.

```
  /**
     * If intervals are mixed (one calendar, one fixed), this attempts to compare the two and make sure they are roughly
     * in the right arrangement (request **&ge;** config).  This always logs a deprecation warning because the behavior is gone
     * in 6.5
     */
```

ES 6.4.3
JDK 11
Gradle 4.9
invoked with ./gradlew assemble -Dorg.gradle.java.home=/usr/lib/jvm/jdk-11

**Comment by jasontedor** [comment]
Elasticsearch 6.4 is not intended to be built with JDK 11. Please use JDK 10. If this reproduces with JDK 10, we can reopen this issue.
