### ISSUE TITLE
How to specify minor build version?

### ISSUE THREAD

**Issue by svanschalkwyk** [elastic/elasticsearch#34423]
Building 6.4 repository produces 6.4.3-SNAPSHOT.
How can one build 6.4.2?
And remove SNAPSHOT ?
ES 6.4 github
Gradle 4.9
./gradlew assemble -Dorg.gradle.java.home=/usr/lib/jvm/jdk-11 -Pversion=6.4.2 (?)

**Comment by jasontedor** [comment]
Thanks very much for your interest in Elasticsearch.

This appears to be a user question, and we'd like to direct these kinds of things to the [forums](https://discuss.elastic.co). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co) that should be able to help get an answer to your question. As such, I hope you don't mind that I close this.
